### ISSUE TITLE
Asset pipeline tries to serve non-assets when they start with the asset prefix

### ISSUE THREAD

**Issue by mcrowe** [rails/rails#10132]
### Actions
- Start with a basic Rails 3.2.13 application
- Change the asset prefix in `application.rb` to `'/a'`
- Create an `apples` resource
- Visit `/apples`

### Expected Result
- The index action for the apples resource is rendered

### Actual Result
- `Served asset /pples - 404 Not Found`

The asset pipeline tries to render an asset any time a route is accessed that starts with the prefix, regardless of whether there is a trailing slash after the prefix. We *should* render an asset only if there is a slash after the prefix. E.g. `/a/pples` should try to render the `pples` asset, but `/apples` should not. This occurs with the default `/assets` prefix, but its less apparent because its rare to have other routes that begin with 'assets'.

From what I can tell, this is a result of the way that `Mapper::Base#mount` works (the sprockets application is mounted at the `config.assets.prefix` path). I was hoping to provide a patch, but I can't think of a clean way to do it. Any thoughts or tips would be appreciated.

**Comment by maclover7** [comment]
On a new Rails application generated from master, with `config.assets.prefix = '/a'`, and `resources :apples`, this error cannot be reproduced.
