### ISSUE TITLE
Add Curaçao to ActiveSupport::TimeZone

### ISSUE THREAD

**Issue by acesuares** [rails/rails#10276]
Or is that a way to do that runtime?

I tried ActiveSupport::TimeZone::zones_map["Curaçao"] = ActiveSupport::TimeZone['La Paz'] but that didn't work, and MAPPING is a frozen hash and can't be modified.

How to add Curaçao to the list of timezones?

**Comment by rafaelfranca** [comment]
https://github.com/rails/rails/issues/22440#issuecomment-178095649
