### ISSUE TITLE
Live streaming doesn't work with basic authentication or builder

### ISSUE THREAD

**Issue by rubys** [rails/rails#10984]
The depot application in Agile Web Development with Rails is a store where the products are books.  I looked into adding a "download" action which would download an ebook using live streaming.  After I did that, other actions started to fail.  It is understandable that other actions in the same controller would perform differently, but I didn't expect hangs.

Basic scenario: rails new depot; cd depot; rails generate scaffold Product title; rake db:migrate; rails server.  At that point, navigate to http://localhost:3000/products/, and create a single new product using whatever title you like.

Replace app/controllers/products_controller.rb with https://gist.github.com/rubys/5801812

Create app/views/products/index.xml.builder with https://gist.github.com/rubys/5801817

With builder, hangs are intermittent. Navigate to http://localhost:3000/products.xml and refresh the page repeatedly (⌘R or F5).

With authentication hangs are repeatable.  Navigate to http://localhost:3000/products/1/edit

**Comment by dhh** [comment]
@tenderlove Sam is seeing this issue again. So re-opening. I'll let him fill in the details.

**Comment by tenderlove** [comment]
Ok, thanks! I'll take a look

**Comment by rubys** [comment]
I don't have much to add yet... this could be a false positive.

Background: when I open a ticket for a problem I see in AWDwR, I add a check for the symptoms in my script, and when I find a match, I report the ticket number.  When the ticket gets fixed, I don't promptly remove the check.  So whether this is the same problem as before or a different problem, I can't say yet.  And as I am still looking at problems earlier in the scenario, this could be a cascading error from a prior issue.

With all that out of the way, here is the expected results as produced by Rails 4.2:

http://intertwingly.net/projects/AWDwR4/checkdepot-215-42/section-21.1.html#cmd3

Here are the empty results I'm seeing with master:

http://intertwingly.net/projects/AWDwR4/checkdepot/section-21.1.html#cmd3

**Comment by rubys** [comment]
There looks to be much deeper problems here: https://github.com/rails/rails/issues/23483

**Comment by matthewd** [comment]
Re-closing in favour of #23483; looks like this is a fairly unrelated issue, which happened to have matching symptoms.
