### ISSUE TITLE
Live streaming threads not dying

### ISSUE THREAD

**Issue by egru** [rails/rails#10989]
Hello,

I'm running into a weird issue with live streams in rails4. I noticed when I refresh a page that is streaming data, the thread that has been created for it sometimes doesn't die. Here's an example controller I'm using:

``` ruby
class GetJobController < ApplicationController
    include ActionController::Live

    def get_job
    response.headers["Content-Type"] = "text/event-stream"
    redis = Redis.new
    redis.subscribe('job') do |on|
      on.message do |event, data|
        response.stream.write("event: #{event}\n")
        response.stream.write("data: #{data}\n\n")
       end
    end
    rescue IOError
        puts "Stream closed"
    ensure
        redis.quit
        response.stream.close
    end
end
```

Here is the coffeescript I am using

``` coffeescript
source = new EventSource("/job")
        source.addEventListener 'job', (e) ->
          message = e.data
          $("#job.id").text message
```

When I start up Puma, the number of threads starts at two. When I refresh the page, the number of threads is three. If I refresh the page too much, the thread limit for Puma gets reached and the server just freezes. I narrowed it down to the controller causing the problem. If I remove the redis.subscribe portion, I obviously don't get any data back and no threads are created. Is there something I am doing wrong? My first thought was something with thread safety, but I am not sure.

Thanks

**Comment by h0jeZvgoxFepBQ2C** [comment]
Is this still open?

**Comment by nhh** [comment]
I still got hanging threads in 2019 with basically exact the same code shown on top of this issue... i saw some workaround but no solutions. Would like to see this happen 

+1

**Comment by nhh** [comment]
And the cause, as some people already pointed out, seems to be Rails not releasing the ActiveRecord connection.

Neither sse code nor redis uses a loop to access a ActiveRecord Connection/Model but after all threads are exhausted, this exception is thrown.

```
ActiveRecord::ConnectionTimeoutError (could not obtain a connection from the pool within 5.000 seconds (waited 5.003 seconds); all pooled connections were in use):
```

**Comment by h0jeZvgoxFepBQ2C** [comment]
Has this been fixed @egru ?
