### ISSUE TITLE
Eager loading bug with has_many :through and STI (Rails 4.0.0rc2)

### ISSUE THREAD

**Issue by balvig** [rails/rails#11078]
When using eager loading on a `has_many :through` to a model using STI, the output SQL seems to be incorrect:

``` ruby
class Group < ActiveRecord::Base
  has_many :users
  has_many :articles, through: :users
end

class User < ActiveRecord::Base
  belongs_to :group
  has_many :articles
end

class Post < ActiveRecord::Base
  belongs_to :user
end

class Article < Post
end
```

Running

``` ruby
Group.includes(:articles).to_a
```

results in

```
ActiveRecord::StatementInvalid: SQLite3::SQLException: 
no such column: posts.type: SELECT "users".* FROM "users"  
WHERE "posts"."type" IN ('Article') AND "users"."group_id" 
IN (298486374, 980190962, 980190963)
```

Dummy app showing the problem with test:
https://github.com/balvig/bug/blob/master/test/models/group_test.rb

**Comment by maclover7** [comment]
Looks ready to be closed to me.

**Comment by senny** [comment]
@maclover7 is it no longer an issue? I never finished my PR (https://github.com/rails/rails/pull/11082#issuecomment-156118260) and #14312 is still open.

**Comment by jturkel** [comment]
I've confirmed this is still an issue on master. Reproducible test case can be found here: https://gist.github.com/jturkel/a4d7f761eff7d7cef980

**Comment by AlfonsoUceda** [comment]
This bug is still in master (5.1.0.alpha) and I've seen there is an [attached PR](https://github.com/rails/rails/pull/14312), will this bug fixed?

**Comment by moktin** [comment]
#14312 has been rebased

**Comment by shubham-studypad** [comment]
migrating an app from rails 3.2 to 4.2, facing this issue. why is this closed if it's not fixed?
