### ISSUE TITLE
Interaction races between flashes, CSRF tokens and other session features, and streaming rendering

### ISSUE THREAD

**Issue by jcoglan** [rails/rails#11476]
This may very well be a case of me holding it wrong, but I'm wondering if this is an overlooked case that Rails should handle gracefully, or if it's up to the user to fix.

Basically, some things like CSRF tokens and flashes live in the session, and involve mutable state. CSRF tokens are lazily generated and put in the session when you call `form_authenticity_token`, and the `Flash` object is lazily created and swept when you access the `flash` API, also typically during rendering.

If you're using streaming rendering (`render :stream => true`), this means the session is being modified after it is serialized and sent as a `Set-Cookie` header, if you are using the cookie store. This means you get races where flash messages persist forever, and forms cannot be submitted.

I am currently fixing them by adding the following to `ApplicationController` for force-generate these values before the headers are sent:

``` rb
before_filter :form_authenticity_token
before_filter :flash
```

Should Rails handle this transparently, or is it on me to fix it, and if the latter, is there a better way of fixing it?

**Comment by jarthod** [comment]
Hi, I just started using streaming with Rails 4.2 and fell into this exact two issue (flash messages persisting forever and form not submitted because of invalid CSRF).
So I confirm this issue is still present on latest stable Rails version, I'm currently working around this the same way @jcoglan did, by running `form_authenticity_token` and `flash` before rendering.

This is low priority but a bit annoying and prevents streaming adoption.

**Comment by jarthod** [comment]
Sorry to revive this but has anything been done (or at least thought) about this issue for Rails 5 ?
Because the issue is still present in rails `4.2`.

**Comment by maclover7** [comment]
Reopening.

**Comment by rafaelfranca** [comment]
Still need a way to reproduce it, so please provide it.

**Comment by maclover7** [comment]
Can you create an executable test script using one of the templates [here](https://github.com/rails/rails/tree/master/guides/bug_report_templates)?

**Comment by jarthod** [comment]
Sure, i'll try to do that ;)

**Comment by jarthod** [comment]
Here is my test:
```ruby
#!/usr/bin/env ruby

begin
  require 'bundler/inline'
rescue LoadError => e
  $stderr.puts 'Bundler version 1.10 or later is required. Please update your Bundler'
  raise e
end

gemfile(true) do
  source 'https://rubygems.org'
  gem 'rails', '4.2.5'
end

require 'rack/test'
require 'action_controller/railtie'

class TestApp < Rails::Application
  config.root = File.dirname(__FILE__)
  config.session_store :cookie_store, key: 'cookie_store_key'
  secrets.secret_token    = 'secret_token'
  secrets.secret_key_base = 'secret_key_base'

  config.logger = Logger.new($stdout)
  Rails.logger  = config.logger

  routes.draw do
    get '/' => 'test#index'
    get '/set_flash' => 'test#set_flash'
  end
end

class TestController < ActionController::Base
  include Rails.application.routes.url_helpers

  def index
    render file: 'template.html.erb', stream: params[:stream]
  end

  def set_flash
    flash.notice = 'notice'
    render text: 'ok'
  end
end

require 'minitest/autorun'

# Ensure backward compatibility with Minitest 4
Minitest::Test = MiniTest::Unit::TestCase unless defined?(Minitest::Test)

class BugTest < Minitest::Test
  include Rack::Test::Methods

  def setup
    IO.write('template.html.erb', '<%= flash.notice %>')
  end

  def teardown
    File.unlink('template.html.erb')
  end

  def test_works_without_stream
    get '/set_flash'
    assert last_response.ok?
    get '/'
    assert last_response.ok?
    assert_match /notice/, last_response.body
    get '/'
    assert last_response.ok?
    refute_match /notice/, last_response.body
  end

  def test_works_with_stream
    get '/set_flash'
    assert last_response.ok?
    get '/', stream: true
    assert last_response.ok?
    assert_match /notice/, last_response.body
    get '/', stream: true
    assert last_response.ok?
    refute_match /notice/, last_response.body
  end

  private

  def app
    Rails.application
  end
end
```

It tests for flash message here but the problem is the same with CSRF.
There one test without streaming (working fine) and one with streaming (broken).

Here is the expected result on my machine (ruby 2.3.0):
```
Finished in 0.044771s, 44.6719 runs/s, 312.7034 assertions/s.

  1) Failure:
BugTest#test_works_with_stream [./rails-streaming.rb:81]:
Expected /notice/ to not match "6\r\nnotice\r\n0\r\n\r\n".

2 runs, 14 assertions, 1 failures, 0 errors, 0 skips
```

There are also weird characters in the streamed output as you can see in the failure line, I don't know where they come from, they're not present in the standard render output. I've used `match` to ignore them here as this is not the subject of this issue. Hope this helps !

**Comment by maclover7** [comment]
Using the above test script, it looks like the bug is somewhere on 4-2-stable, because the script is passing on Rails master. Will perform a bisect to see if we can backport something.

**Comment by jarthod** [comment]
Interesting and good to hear, i'll try to do a real life test with the CSRF too to see if it fixes both.

**Comment by jarthod** [comment]
Hello, I just upgraded to Rails 5 and tried this again but the problem is still present and can be reproduced with the script I gave above on rails `5.0.2` and `5.1.0`.

**Comment by seanlinsley** [comment]
I can confirm that this happens with both Rails 5.0 and 5.1.

**Comment by jarthod** [comment]
I just updated my test and verified this problem still exists in `5.2`, `6.0` and `6.1.0.rc1`. Here is the slightly updated test file:

```ruby
#!/usr/bin/env ruby

begin
  require 'bundler/inline'
rescue LoadError => e
  $stderr.puts 'Bundler version 1.10 or later is required. Please update your Bundler'
  raise e
end

gemfile(true) do
  source 'https://rubygems.org'
  gem 'rails', "~> #{ARGV.first || "6.0"}"
end

require 'rack/test'
require 'action_controller/railtie'

class TestApp < Rails::Application
  config.root = File.dirname(__FILE__)
  config.hosts.clear if config.respond_to? :hosts # needed to allow request in Rails 6
  config.session_store :cookie_store, key: 'cookie_store_key'
  secrets.secret_token    = 'secret_token'
  secrets.secret_key_base = 'secret_key_base'

  config.logger = Logger.new($stdout)
  Rails.logger  = config.logger

  routes.draw do
    get '/' => 'test#index'
    get '/set_flash' => 'test#set_flash'
  end
end

class TestController < ActionController::Base
  include Rails.application.routes.url_helpers
  prepend_view_path Rails.root

  def index
    render template: 'template', stream: params[:stream]
  end

  def set_flash
    flash.notice = 'notice'
    render plain: 'ok'
  end
end

require 'minitest/autorun'

# Ensure backward compatibility with Minitest 4
Minitest::Test = MiniTest::Unit::TestCase unless defined?(Minitest::Test)

class BugTest < Minitest::Test
  include Rack::Test::Methods

  def setup
    IO.write('template.html.erb', '<%= csrf_meta_tag %><%= flash.notice %>')
  end

  def teardown
    File.unlink('template.html.erb')
  end

  def test_works_without_stream
    get '/set_flash'
    assert last_response.ok?
    get '/'
    assert last_response.ok?
    assert_match /notice/, last_response.body
    get '/'
    assert last_response.ok?
    refute_match /notice/, last_response.body
  end

  def test_works_with_stream
    get '/set_flash'
    assert last_response.ok?
    get '/', stream: true
    assert last_response.ok?
    assert_match /notice/, last_response.body
    get '/', stream: true
    assert last_response.ok?
    refute_match /notice/, last_response.body
  end

  private

  def app
    Rails.application
  end
end
```

It's now possible to pass the Rails version directly as parameter, e.g.: `./rails-streaming.rb 6.1.0.rc1` (this test file should work with Rails `4.0` to `6.1`, tested with ruby `2.6.4`)
Could you please reopen the issue?
