### ISSUE TITLE
Can't manage cookies in custom 404 or 500 actions or their filters

### ISSUE THREAD

**Issue by enthrops** [rails/rails#11679]
Steps to reproduce:
1) Create a brand new project (tested on Rails 4.0.0 stable)
2) Add `config.exceptions_app = self.routes` to `config/application.rb`
3) Set `config.consider_all_requests_local = false` in `development.rb`
4) Set up two routes in `routes.rb`:
   
    get '404' => 'application#not_found'
    get 'ok' => 'application#ok'

5) Create `not_found` action in `application_controller.rb`:

    def not_found
      cookies[:not_found] = true
      # render any template here
    end

5) Create `ok` action in `application_controller.rb`:

    def ok
      cookies[:ok] = true
      # render any template here
    end

6) Go to `/ok`, watch `ok = true` cookies get created
7) Go to non-existent url, watch no cookies get created

Same think applies to 500 custom action, and to before filters that run before custom 404 and 500 actions. Flash is also not working correctly (it sticks forever as you reload)

**Comment by rafaelfranca** [comment]
You should not be dealing with cookies in custom error pages. In fact we don't even recommend to use routes as an exception application.
