### ISSUE TITLE
Attempt to connect the database during assets precompilation when using virtual attributes validation

### ISSUE THREAD

**Issue by x3qt** [rails/rails#11853]
Assets precompilation requires database connection. Issue appears when using virtual attribute validation:
```rails
validates :agreement, acceptance: true
```
With normal attributes validations (not virtual) assets precompilation goes without initializing database connection.

Someone on stackoverflow.com said that this may be a bug - http://stackoverflow.com/questions/18184937/assets-precompilation-requires-database-connection#comment26650242_18185239

Update 1:
Rails 4.0, Ruby 2.0.0-p247.

Update 2:
Demo app - https://github.com/x3qt/validation_bug_demo

**Comment by luisincrespo** [comment]
@AKoetsier I cannot recall what was the mistake I was making, but I'm pretty sure it was some foolishness haha. If something comes to my mind I'll let you know.

**Comment by frenkel** [comment]
I worked around this by manually adding the virtual attribute using attr_accessor before the validation.

**Comment by jimmykarily** [comment]
@AKoetsier binstubs is not the problem. The preloading of the Rails environment is (that's why I wrote "springified binstubs"). Maybe you are running some other preloader (Guard?).

**Comment by rafaelfranca** [comment]
This issue is fixed in https://github.com/rails/rails/commit/37661bfc810da7384ac6650d60be8669baa16813

**Comment by adrianmacneil** [comment]
:clap: thanks!

**Comment by mergulhao** [comment]
:clap: :clap: :clap: //cc @FlaviaFortes
