### ISSUE TITLE
Regression in rails 4 when generating routes with optional scope

### ISSUE THREAD

**Issue by deivid-rodriguez** [rails/rails#12178]
Hi! I just upgraded one application to rails 4 and I'm getting an error I didn't expect. I'm sorry if I'm missing something and this is an intentional change.

When there's an optional scope, `link_to resource` doesn't seem to work properly in rails 4. I can change every link to `link_to resource_path(id: resource.id)` but that's a lot of links to change and that kind of shortcut seemed nice and readable...

To reproduce copy and paste the following into a terminal

```
rails new optional_scope_routes_rails4
cd optional_scope_routes_rails4
rails generate scaffold post title body:text published:boolean
rake db:migrate
echo 'Post.create(title: "Hi", body: "Hello", published: false)' | rails c
cat <<EOF > config/routes.rb
OptionalScopeRoutesRails4::Application.routes.draw do
  scope '(:locale)', locale: /en|es/  do
    resources :posts
    root 'posts#index'
  end
end
EOF
cat <<EOF > app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  before_filter :set_locale

  private
    def set_locale
      I18n.locale = params[:locale] || I18n.default_locale
      Rails.application.routes.default_url_options[:locale] = I18n.locale
    end
end
EOF
rails s
```

When I open the browser at `0.0.0.0:3000` I get the error

```
No route matches {:controller=>"posts", :action=>"show", :locale=>#<Post id: 1, title: "Hi", body: "Hello", published: false, created_at: "2013-09-09 18:44:45", updated_at: "2013-09-09 18:44:45">, :id=>nil, :format=>nil} missing required keys: [:id]
```

in `optional_scope_routes_rails4/app/views/posts/index.html.erb` line `#21`

```
<td><%= link_to 'Show', post %></td>
```

But in rails3 it works just fine... Open another terminal and try it with the following

```
rails _3.2.14_ new optional_scope_routes_rails3
cd optional_scope_routes_rails3
rails generate scaffold post title body:text published:boolean
rake db:migrate
echo 'Post.create(title: "Hi", body: "Hello", published: false)' | rails c
cat <<EOF > config/routes.rb
OptionalScopeRoutesRails3::Application.routes.draw do
  scope '(:locale)', locale: /en|es/  do
    resources :posts
    root :to => 'posts#index'
  end
end
EOF
cat <<EOF > app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  before_filter :set_locale

  private
    def set_locale
      I18n.locale = params[:locale] || I18n.default_locale
      Rails.application.routes.default_url_options[:locale] = I18n.locale
    end
end
EOF
rm public/index.html
rails s -p3001
```

Thanks a lot in advance!

**Comment by luisdoubrava** [comment]
I patched extract_parameterized_parts in action_dispatch/journey/formatter.rb to use symbolize_keys when extracting bad_keys
This seems to fix the issue in my case:
```
def extract_parameterized_parts(route, options, recall, parameterize = nil)
        parameterized_parts = recall.merge(options)
        keys_to_keep = route.parts.reverse.drop_while { |part|
          !options.key?(part) || (options[part] || recall[part]).nil?
        } | route.required_parts

        # symbolize keys to make sure the right parameters are removed
        (parameterized_parts.symbolize_keys.keys - keys_to_keep.map(&:to_sym)).each do |bad_key|
          parameterized_parts.delete(bad_key)
        end

        if parameterize
          parameterized_parts.each do |k, v|
            parameterized_parts[k] = parameterize.call(k, v)
          end
        end

        parameterized_parts.keep_if { |_, v| v }
        parameterized_parts
      end
```

**Comment by nofxx** [comment]
OP workaround works! Hope had find this earlier. 
Bump for search and subscribe.

**Comment by evgen3d** [comment]
deivid-rodriguez, thank you for posting your code - it helps a lot!
Its strange that there is not so much comments regarding this bug. Its really important and makes some troubles.
Thanks for future fixing it in 5.0.0!

**Comment by maclover7** [comment]
Opened up #22767 to try and fix this problem. :-)

**Comment by DamodarSojka** [comment]
Is this bug still present in rails 4.2? Or has it been fixed? Is there a solution that does not require updating to 5.0.0?

**Comment by trantorLiu** [comment]
@luisdoubrava Would you explain more how you implement it? I tried the following but did work. Thank you!

```ruby
# lib/core_extensions/action_dispatch/formatter.rb
module CoreExtensions
  module ActionDispatch
    module Formatter
      def self.included(base)
        class << base
          private
          def extract_parameterized_parts(route, options, recall, parameterize = nil)
            parameterized_parts = recall.merge(options)
            keys_to_keep = route.parts.reverse.drop_while { |part|
              !options.key?(part) || (options[part] || recall[part]).nil?
            } | route.required_parts

            # symbolize keys to make sure the right parameters are removed
            (parameterized_parts.symbolize_keys.keys - keys_to_keep.map(&:to_sym)).each do |bad_key|
              parameterized_parts.delete(bad_key)
            end

            if parameterize
              parameterized_parts.each do |k, v|
                parameterized_parts[k] = parameterize.call(k, v)
              end
            end

            parameterized_parts.keep_if { |_, v| v }
            parameterized_parts
          end
        end
      end
    end
  end
end
```

```ruby
# config/initializers/monkey_patches.rb
require Rails.root.join('lib/core_extensions/action_dispatch/formatter.rb')
ActionDispatch::Journey::Formatter.include CoreExtensions::ActionDispatch::Formatter
```

**Comment by robzolkos** [comment]
Should we close this one @pixeltrix ?  Rails 4 is ⚰️

**Comment by dsazup** [comment]
I just run into this issue it seems like it exists in master branch still. In my case I have these routes
```
scope "(:team)" do
    resources :courses
    resources :users
  end
```

- If I am on `example.com/users`,  `edit_user_path(user)` will generate `example.com/users/1/edit`
- If I am on `example.com/5/users`, `edit_user_path(user)` will generate same  `example.com/users/1/edit`. I would expect it to be `example.com/5/users/1/edit`
- If I am on `example.com/5/users` and use `edit_user_path(id: user.id)` it then generates expected url, `example.com/5/users/1/edit`, but it feels cumbersome adding id: user.id everywhere

**Comment by dsazup** [comment]
I have written a failing test for this https://gist.github.com/dsazup/c7d425854fa6bb81f2d7d8572da7ee4c#file-test-rb-L53 which. I would be happy to try and fix it, but I am fairly new to rails, so if someone could point me to the right direction that would be great. 😀

**Comment by jonathanhefner** [comment]
@dsazup Please do take a shot at it!  :pray: To get started, check out the [Contributing to the Rails Code](https://guides.rubyonrails.org/contributing_to_ruby_on_rails.html#contributing-to-the-rails-code) section of the contributing guide.  Since you'll be working on the routing code, you may not need the rails-dev-box VM it mentions, but it wouldn't hurt to set it up (for future contributions :wink:).  And if there's anything in the guide that needs improvement, please let me know!

**Comment by ghiculescu** [comment]
Closing as this is super old and Rails 4 is end of lifed. If it's still a problem today, let's open a new issue so that's more clear.
