### ISSUE TITLE
has_and_belongs_to_many association with scope not joining correct table in scope

### ISSUE THREAD

**Issue by mikecmpbll** [rails/rails#12492]
When I try to use a scope on a `has_and_belongs_to_many` association that needs to join from the associated model to another, it works fine when using the association method, but not when using that association in an `.includes` or `.joins` on the model. For example:

    class Student < ActiveRecord::Base
      has_and_belongs_to_many :groups
      has_and_belongs_to_many :tutor_groups, -> { merge(Group.filter_type(:tutor_group)) }, class_name: "Group", join_table: "groups_students"
      has_and_belongs_to_many :tutor_groups2, -> { joins(:group_type).where(group_type: { name: :tutor_group }) }
    end
     
    class Group < ActiveRecord::Base
      has_and_belongs_to_many :students
      belongs_to :group_type

      def self.filter_type(type)
        joins(:group_type).where(group_types: { name: type })
      end
    end

In the rails console:

    2.0.0p0 :001 > Student.first.tutor_groups
      Student Load (0.7ms)  SELECT `students`.* FROM `students` ORDER BY `students`.`id` ASC LIMIT 1
      Group Load (0.3ms)  SELECT `groups`.* FROM `groups` INNER JOIN `group_types` ON `group_types`.`id` = `groups`.`group_type_id` INNER JOIN `groups_students` ON `groups`.`id` = `groups_students`.`group_id` WHERE `groups_students`.`student_id` = 1 AND `group_types`.`name` = 'tutor_group'
     => #<ActiveRecord::Associations::CollectionProxy [#<Group id: 1, name: "5A", group_type_id: 1, new: false>]> 
    2.0.0p0 :002 >  Student.includes(:tutor_groups).where(id: 1)
      Student Load (0.6ms)  SELECT `students`.* FROM `students` WHERE `students`.`id` = 1
      SQL (1.2ms)  SELECT `groups`.*, `t0`.`student_id` AS ar_association_key_name FROM `groups` INNER JOIN `groups_students` `t0` ON `groups`.`id` = `t0`.`group_id` WHERE `group_types`.`name` = 'tutor_group' AND `t0`.`student_id` IN (1)
    Mysql2::Error: Unknown column 'group_types.name' in 'where clause': SELECT `groups`.*, `t0`.`student_id` AS ar_association_key_name FROM `groups` INNER JOIN `groups_students` `t0` ON `groups`.`id` = `t0`.`group_id` WHERE `group_types`.`name` = 'tutor_group' AND `t0`.`student_id` IN (1)
    ActiveRecord::StatementInvalid: Mysql2::Error: Unknown column 'group_types.name' in 'where clause': SELECT `groups`.*, `t0`.`student_id` AS ar_association_key_name FROM `groups` INNER JOIN `groups_students` `t0` ON `groups`.`id` = `t0`.`group_id` WHERE `group_types`.`name` = 'tutor_group' AND `t0`.`student_id` IN (1)

Rails 4.0.0, Ruby 2.0.0

Self-contained gist: https://gist.github.com/mikecmpbll/6921120

It's similar to other issues regarding includes in Rails 4, but I couldn't see that it was the same as any of them, however, they may well be related so feel free to let me know if they are and we can close this one.

**Comment by nixme** [comment]
I believe this is fixed in 4.2 with https://github.com/rails/rails/commit/91e3dab804fffe0b1daebb438091418faa1fa256 but cannot understand the original gist as a test case. Is the test supposed to use tutor_groups2 to make the error occur?

**Comment by mikecmpbll** [comment]
@nixme yup that pull request looks nigh-on identical to the one I made a year or so ago, so one would assume it fixes this bug, too.

I think my console excerpt in OP explains it better than I could now; I think this can be closed.
