### ISSUE TITLE
unescapeHTML crashes with certain *.html_safe inputs

### ISSUE THREAD

**Issue by ptsneves** [rails/rails#12672]
I have a situation where I need to call _unescapeHTML_ on a string that was marked as html_safe but when certain strings are set for unescape a crash happens with an error like:

```
CGI.unescapeHTML('The experimental macro Hello Latex[&amp;quot;\&amp;quot;sdsd\&amp;quot;&amp;quot;'.html_safe)
TypeError: can't dup NilClass
        from /usr/lib/ruby/1.9.1/cgi/util.rb:56:in `dup'
        from /usr/lib/ruby/1.9.1/cgi/util.rb:56:in `block in unescapeHTML'
        from /var/lib/gems/1.9.1/gems/activesupport-3.2.13/lib/active_support/core_ext/string/output_safety.rb:169:in `gsub'
        from /var/lib/gems/1.9.1/gems/activesupport-3.2.13/lib/active_support/core_ext/string/output_safety.rb:169:in `gsub'
```

I can reproduce it in a rails console:

``` ruby
txt='The experimental macro Hello Latex[&amp;quot;\&amp;quot;sdsd\&amp;quot;&amp;quot;'
txt=txt.html_safe
CGI.unescapeHTML(txt)
```

The string is:

```
'The experimental macro Hello Latex[&amp;quot;\&amp;quot;sdsd\&amp;quot;&amp;quot;'
```

One way to not trigger this problem is to interpolate the _SafeBuffer_ generated by html_safe in a string. Then, no crash occurs. Using the to_s method of _SafeBuffer_ does not work because it returns _self_.

``` ruby
txt='The experimental macro Hello Latex[&amp;quot;\&amp;quot;sdsd\&amp;quote;&amp;quote;'
txt="#{txt.html_safe}"
CGI.unescapeHTML(txt)
```

My configuration is as follows:
Environment:
  Ruby version                   1.9.3-p194 (2012-04-20) [x86_64-linux]
  Rails version                  3.2.13
  Database adapter               Mysql2

**Comment by Dorian** [comment]
The example doesn't crash on Rails 5.2.0.beta2, so seems like it was fixed.

**Comment by byroot** [comment]
Seems like it has been fixed at some point:

```ruby
>> Rails::VERSION::STRING
=> "6.1.3.1"
>> CGI.unescapeHTML('The experimental macro Hello Latex[&amp;quot;\&amp;quot;sdsd\&amp;quot;&amp;quot;'.html_safe)
=> "The experimental macro Hello Latex[&quot;\\&quot;sdsd\\&quot;&quot;"
>> RUBY_VERSION
=> "3.1.0"
```
