### ISSUE TITLE
Scopes, Sub Selects and Bind Values

### ISSUE THREAD

**Issue by brocktimus** [rails/rails#12753]
This issue is tested using Rails 4.0.1. Running against Postgres 9.3 with the latest pg gem.

I've only realised recently that AR will change Relations into Sub Selects and have been trying to use them to simplify my queries and scopes.

I've started to run into a couple of issues, particularly with binds and sub selects. An example of one such problem below:

```ruby
class Article < AR::Base
  has_many :comments
end

class Comment < AR::Base
  belongs_to
  has_many :replies, class_name: "Comment", foreign_key: :parent_id

  def self.leaves
    where.not(id: all.select(:parent_id))
  end
end

article = Article.first
Comment.leaves.count # => Works as expected
article.comments.leaves.count # => Fails with an error due to binds as below

  PG::ProtocolViolation: ERROR:  bind message supplies 2 parameters, but prepared statement "a29" requires 1
SELECT "comments".* FROM "comments"  WHERE "comments"."article_id" = $1 AND ("comments"."id" NOT IN (SELECT parent_id FROM "comments"  WHERE "comments"."article_id" = $1))
```

I've also got some much more complex examples which have the opposite problem. In those I'm trying to OR together some large and complex scopes. I read that this was possible using ```#where_values``` on a relation. However whenever I try and use that I run into errors because the Arel nodes contain prepared $1 values (and the like) that don't get populated when I do anything with them manually.

I suspect it could come down to a common problem? I might be misusing something or stretching the ORM too far. I suspect both could be solved if I could "force" the substitution of the value into the query selectively. That or manually supply the binds to the query. I've dug about as far as I can get though.

Any ideas?

I can provide a more fleshed out example of the larger problem I alluded to. It just needs more models and a bit of time to boil down.

Thanks for the great work guys!

**Comment by stiff** [comment]
Why not assign indexes right before execution, say in `ActiveRecord::ConnectionAdapters::DatabaseStatements#to_sql`? Otherwise it seems to be very tricky and database-tied.

**Comment by sgrif** [comment]
That's what we do, though we handle it somewhere that isn't a performance hit.

**Comment by sgrif** [comment]
Can someone confirm whether this issue still exists? I believe it's been resolved on both 4.2 and 4.1

**Comment by stiff** [comment]
In 4.2 it seems to be fixed! In 4.0.13 still remains.

**Comment by matthewd** [comment]
> In 4.2 it seems to be fixed!

Thanks!

4.0 is no longer supported.

**Comment by brocktimus** [comment]
@sgrif @matthewd it isn't fixed in 4.1. Not saying issue should be reopened but letting you all know if you thought it was fixed. Error has changed slightly to...

```
  1) Error:
SubQueryTest#test_bind_values:
ActiveRecord::StatementInvalid: PG::IndeterminateDatatype: ERROR:  could not determine data type of parameter $1
: SELECT COUNT(*) FROM "comments"  WHERE "comments"."article_id" = $2 AND ("comments"."id" NOT IN (SELECT "comments"."parent_id" FROM "comments"  WHERE "comments"."article_id" = $2))
    /home/brock/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/activerecord-4.1.9/lib/active_record/connection_adapters/postgresql_adapter.rb:869:in `prepare'
    /home/brock/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/activerecord-4.1.9/lib/active_record/connection_adapters/postgresql_adapter.rb:869:in `prepare_statement'
    /home/brock/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/activerecord-4.1.9/lib/active_record/connection_adapters/postgresql_adapter.rb:826:in `exec_cache'
    /home/brock/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/activerecord-4.1.9/lib/active_record/connection_adapters/postgresql/database_statements.rb:138:in `exec_query'
    /home/brock/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/activerecord-4.1.9/lib/active_record/connection_adapters/postgresql_adapter.rb:954:in `select'
    /home/brock/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/activerecord-4.1.9/lib/active_record/connection_adapters/abstract/database_statements.rb:24:in `select_all'
    /home/brock/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/activerecord-4.1.9/lib/active_record/connection_adapters/abstract/query_cache.rb:70:in `select_all'
    /home/brock/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/activerecord-4.1.9/lib/active_record/relation/calculations.rb:265:in `execute_simple_calculation'
    /home/brock/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/activerecord-4.1.9/lib/active_record/relation/calculations.rb:227:in `perform_calculation'
    /home/brock/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/activerecord-4.1.9/lib/active_record/relation/calculations.rb:119:in `calculate'
    /home/brock/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/activerecord-4.1.9/lib/active_record/relation/calculations.rb:34:in `count'
    script.rb:62:in `test_bind_values'
```

When using reproduction script from above (and changing rails AR to 4.1.9).

**Comment by matthewd** [comment]
Hmm. Given how long it's been broken, I'm tempted to just declare 4.2 good enough -- if 4.1 is still no go, then I imagine it'd be non-trivial to improve. @sgrif?

**Comment by sgrif** [comment]
It actually is supposed to be fixed on 4.1. Has anyone checked on 4-1-stable?

**Comment by brocktimus** [comment]
Same error as above when running again 4-1-stable. 

I wrote a failing test that might be useful to import into AR, failing test available in #17185. I couldn't even get close to fixing it though without breaking a huge amount of things. Might be worth putting on master as well as  a regression test, even though it will be passing there already.

**Comment by sgrif** [comment]
I'll take a look. It should be pretty simple to fix (famous last words, I know)

**Comment by brocktimus** [comment]
:heart:

**Comment by sgrif** [comment]
Fixed in https://github.com/rails/rails/commit/ac1fbc1734a86d000a9da2b016b523c11a3c7781

**Comment by stiff** [comment]
It would be great to add failing test to ensure it's really fixed, because the test I tried ( https://gist.github.com/stiff/4d435d5744ed83d7e6ed ) is working even in 4.1.9 without the error mentioned by @brocktimus.
