### ISSUE TITLE
find_by on ID column should not convert non-numeric strings to 0

### ISSUE THREAD

**Issue by senny** [rails/rails#12793]
source: #11902 

### Example:

```
> Model1.find_by(id: "lol i'm no integer")
SELECT "model1".* FROM "model1" WHERE "model1"."id" = 0 LIMIT 1
=> nil
```

### Expected behavior

ActiveRecord should send the given `String` as is to the database.

**Comment by rafaelfranca** [comment]
@senny I think this will break `Model.find('123-my-slug')`.

**Comment by sgrif** [comment]
I also think we sufficiently discussed this over the last year to decide this is a bad idea. The biggest reason for which is that going to `http://example.com/posts/omglol` will now be able to make the server 500.

**Comment by rafaelfranca** [comment]
Right. So closing.
