### ISSUE TITLE
Nested scope in route removes slash at the beginning of the url

### ISSUE THREAD

**Issue by saratovsource** [rails/rails#12805]
First example:

``` ruby
# config/routes.rb
scope "(:locale)" do
  root_to "welcome#index"
end
```

When i run `rake routes` result is:
`web/welcome#index      root      /(:locale)(.:format)`
and helper method returns
`root_path #=>"/"`

If i add second scope:

``` ruby
# config/routes.rb
scope "(:locale)" do
  scope "(:platform)" do
    root_to "welcome#index"
  end
end
```

Result is:
`web/welcome#index      root      (/:locale)(/:platform)(.:format)`
and
`root_path #=> ""` - empty string

The first slash in the url is inside the optional parameter. It is correct?

**Comment by tarasmatsyk** [comment]
added pull request. The fix was easy :) 

@robin850, your failing gist helped a lot!
