### ISSUE TITLE
Strange ActiveRecord behaviour when using merge and joins

### ISSUE THREAD

**Issue by iwiznia** [rails/rails#12953]
There's a strange behaviour on AR in which using merge on a scope varies the order of the joins depending on how you define the join (string vs symbol).
Here's the testcase:
https://gist.github.com/iwiznia/7547713

I know that in the test there's a table that doesn't exist, it's there only to check the order of the join clauses.
There are 3 tests which should yield the same result, but when you combine joins as strings and joins as symbols or classes, it mangles the order of the joins.
Maybe it has to do with the fact that it's using the join_sources of the Arel::SelectManager class, but I thought that was a valid use case, and doing the same thing, but calling to_sql first solves the error.

What do you think? Is this a bug? I think it is since the three join statements should produce the same sql.

**Comment by magikid** [comment]
I'm not sure what versions @iwiznia was using but when I run this using ruby 2.3 and rails 4.2.6, all of the tests pass.

**Comment by tibbon** [comment]
We're running into this problem ourselves. Curious to see if there's any new thoughts on it.
