### ISSUE TITLE
Sending JSON in functional tests does not populate the params hash

### ISSUE THREAD

**Issue by haihappen** [rails/rails#13135]
```ruby
test 'sending raw JSON does not populate the params hash' do
  @request.headers['Content-Type'] = 'application/json'
  post :create, { key: "value" }.to_json

  assert_equal "value", params['key'] # => Will fail!
end
```

will result in following `params` hash:

```ruby
{"controller"=>"posts", "action"=>"create"} # Hence the missing key-value pair.
```

However sending the corresponding request with curl or other apps, it works like intended. I even asked [on StackOverflow](http://stackoverflow.com/questions/20327627/functional-testing-of-a-json-rails-api), however no answer yet. Looks like a bug for me.

**Comment by shuhaowu** [comment]
Can still reproduce on rails 4.2

**Comment by jarthod** [comment]
Yep still present, no easy way to work with raw body in 4.2

**Comment by rafaelfranca** [comment]
It was fixed on the master branch. Unfortunately it is not easy to backport so it will not be fixed on Rails 4

**Comment by cdcooksey** [comment]
I've spent about 16 hours trying to figure out why my test wasn't working, and now I'm finally finding this thread and it all makes sense.

In our case, we're using ```rails-api```.  Rather than inherit from ```IntegrationTest```, we're just passing a non-JSON hash, and it seems to work. 

It's a hideous workaround for an API, but it's faster and we can't wait until Rails 5.

For google purposes so others can find this thread:

strong parameters
rails 4
top level nested key
wrap_parameters
json minitest
empty parameters
empty params

**Comment by apotonick** [comment]
I started to test with Rack-test. It is a million times faster, no magic and does exactly what you would think it does.

**Comment by cdcooksey** [comment]
Nice. :+1:  Personally, I want to move to RSpec. I miss it. :smile:

**Comment by pixeltrix** [comment]
@apotonick yes, you're right - if only it'd been around when integration tests were implemented in Rail 1.1 :wink:

**Comment by apotonick** [comment]
Haha I hear ya @pixeltrix but I still wonder why it never got cleaned up? It's _so much code_ to do a very simple thing. What's the plan with this?

**Comment by rafaelfranca** [comment]
It is already being done in master branch

**Comment by sixty4bit** [comment]
Has this been fixed in 5.0.0?

**Comment by cdcooksey** [comment]
@sixty4bit  Yes

**Comment by sandstrom** [comment]
In case anyone end up here via Google (like I did), the correct way to do this in Rails 5 is:

```ruby
post new_widget_url, as: :json, params: { foo: "bar" }
# will set the correct content-type header automatically
```
