### ISSUE TITLE
Set Session Time Zone While Connecting to Mysql

### ISSUE THREAD

**Issue by azitabh** [rails/rails#13494]
Mysql sets the time zone for all the connections as `SYSTEM` which is the time zone of the system where mysql-server is running. In my case it is `+05:30`. It stores all the values in `UTC` while it accepts and returns all values in the timezone set as `session time_zone`.

Default timezone for rails4 is `:local` whereas AR default for rails4 is `UTC` . So when I set a timestamp field by doing `Time.now`, AR converts the time into `UTC` and sends it to Mysql. Mysql assumes the incoming value to be in `+05:30` and hence converts it to `UTC` before storing. So, the conversion to `UTC` is happening twice.

This problem can be solved by letting AR know what Mysql session time_zone is.
`config.active_record.default_timezone = :local`

But the problem is if mysql server is to be moved to a separate machine with different time zone setting, our rails application needs to aware of this change and `config.active_record.default_timezone` must be changed accordingly for a consistent behavior.

This dependency can be removed if AR sets the `session time_zone` to whatever is set as `config.active_record.default_timezone` while connecting to the mysql server.
It can be done at the same time when AR sets variables like `wait_timeout` and etc.

Please point out if I am missing something.

**Comment by halida** [comment]
I think this feature is needed, rails timezone is not always same with database timezone.

**Comment by lepek** [comment]
This issue is very important.
If I use STR_TO_DATE in MySQL for example, I will end with the MySQL timezone in the datetime field, while in Rails I will end with the Rails app timezone when generating a datetime. There is no strict reason why this two timezone should match, so this feature is important.

**Comment by mufid** [comment]
Any update on this?

**Comment by azitabh** [comment]
@eric-chahin Is there a plan to take this up? if not, i can raise as pull request.

**Comment by pixeltrix** [comment]
Closing because we now support setting arbitrary session variables via the connection specification so if someone needs to set the timezone they can do something like this:

``` yaml
development:
  variables:
    time_zone: "Europe/London"
```

To use named timezones you'll need to import them first using the `mysql_tzinfo_to_sql` tool, e.g:

``` bash
mysql_tzinfo_to_sql /usr/share/zoneinfo | mysql -D mysql
```
