### ISSUE TITLE
The request.path isn't reset across multiple calls to process in functional tests

### ISSUE THREAD

**Issue by pixeltrix** [rails/rails#13851]
Because of [this line][1], any further calls to `get`, `post`, etc. will use the first request's `PATH_INFO` environment variable because it isn't reset between requests. However it isn't as simple as deleting `PATH_INFO` from the environment in `recycle!` because someone may have set it directly before the request as part of the test setup.

Similarly, it can't be simply deleted after the request because someone may be asserting on it afterwards. Here's a failing example test:

``` ruby
require 'action_controller/railtie'
require 'minitest/autorun'
require 'rails/test_help'

class TestApp < Rails::Application
  config.eager_load = true
  config.root = File.dirname(__FILE__)
  config.session_store :cookie_store, key: 'cookie_store_key'
  config.secret_token    = 'secret_token'
  config.secret_key_base = 'secret_key_base'

  config.logger = Logger.new('/dev/null')
  Rails.logger  = config.logger
end

TestApp.initialize!

TestApp.routes.draw do
  get '/foo', to: 'test#foo'
  get '/bar', to: 'test#bar'
end

class TestController < ActionController::Base
  def foo
    render text: 'foo'
  end

  def bar
    render text: 'bar'
  end
end

class TestControllerTest < ActionController::TestCase
  def test_path_reset_between_requests
    get :foo
    assert_equal "/foo", @request.path

    get :bar
    assert_equal "/bar", @request.path
  end
end
```

One possible solution is to have an explicit `@request.recycle!` phase where `process` will recycle the request before processing the action unless it has been already called, e.g:

``` ruby
# request.recycle! called implicitly
get :foo

@request.recycle!
@request.env['PATH_INFO'] = '/bar'

# request.recycle! not called as it's been called explicitly
get :bar
# request.recycled? flag reset here
```

Whilst this isn't ideal it's probably the easiest solution until a refactoring of `ActionController::TestCase` takes place for Rails 4.2. The reason that it isn't ideal is that we still don't know what the developer has set in the environment so it's hard to know whether something is the default or has been explicitly set.

[1]: https://github.com/rails/rails/blob/master/actionpack/lib/action_controller/test_case.rb#L631

**Comment by JamesJahraus** [comment]
Maybe this can help http://api.rubyonrails.org/classes/ActionController/TestCase.html

"Functional tests allow you to test a single controller action per test method."

The problem may be having two get requests, which is more for ActionDispatch::IntegrationTest

Ruby on Rails 4.2.0
Class
ActionController::TestCase < ActiveSupport::TestCase
actionpack/lib/action_controller/test_case.rb
railties/lib/rails/test_help.rb
Superclass for ActionController functional tests. Functional tests allow you to test a single controller action per test method. This should not be confused with integration tests (see ActionDispatch::IntegrationTest), which are more like “stories” that can involve multiple controllers and multiple actions (i.e. multiple different HTTP requests).

**Comment by hsm3** [comment]
I just got bit badly by this issue.  It's not a simple one to track down, and the effects within our app were subtle (the controller's params were right, but the controller's request's url was wrong).

I suggest any of the following would be an improvement (but I admit I don't know the codebase well):

1) TestCase's build_request_url, get rid of the initial << unless @request.env["PATH_INFO"] >>, and just recalc all the request pieces properly each time.  Is the current test a valuable optimization?

2) Clear @env["PATH_INFO"] in the request's recycle.  If someone had set that intentionally before the request, they can set it again.  Sharing state seen by the server side across requests is looney.

3) Or, if we have to live in a church where we can only do one action per test method (I'm not fond of these strident rules), make your code fail obviously when it's not used in the way you expect.  Throw some sort of error if two requests are done within the same test!  Far preferable to the subtle bugs.

**Comment by jrochkind** [comment]
This is annoying me too, something has changed in Rails 4.2 around this stuff I think, making tests that used to pass for me no longer do so, related to this stuff. I wish there were a way to do multiple requests in a functional test, sometimes it really is convenient. Does anyone have an easy workaround to make this possible in rails 4.2?

**Comment by hsm3** [comment]
My embarassingly ugly hack was `request.env.delete 'PATH_INFO'` in my test before issuing the second request.

**Comment by rafaelfranca** [comment]
Closing since ActionController::TestCase is deprecated in favor of `ActionDispatch::IntegrationTest` and it doesn't have this problem.
