### ISSUE TITLE
class_attribute not thread-safe

### ISSUE THREAD

**Issue by dwbutler** [rails/rails#14021]
I'm encountering this issue in a production application with the Paper Trail gem. (See https://github.com/airblade/paper_trail/issues/307). It's running in JRuby/TorqueBox under Rails 3.2.16. The implementation in Rails 4 looks nearly identical.

If I understand the [implementation](https://github.com/rails/rails/blob/v3.2.16/activesupport/lib/active_support/core_ext/class/attribute.rb#L80) of `class_attribute` correctly, every time you set the class attribute, it undefines the existing singleton method and defines a new singleton method that simply returns the new value.

In my app, several threads are setting the class attribute of different instances of the same class. This causes the singleton method of the class to be undefined in one thread, and then another thread raises a `NameError` because the method has been temporarily removed.

It sounds like an unlikely scenario, but this is happening a couple times a day in a relatively low-traffic app.

`class_attribute` is pretty complex, so I'm not sure how to fix this while retaining the existing functionality. Any advice would be appreciated. Perhaps putting a mutex around the code that undefines/defines would be best?

**Comment by ankuriitk** [comment]
Any update on the bug?

**Comment by ankuriitk** [comment]
awesome @matthewd : I presume PR #29233 fixes this. When will this be released? Will it be part of Rails 5.0.6 (I see a release candidate for 5.0.6) or a later version?
