### ISSUE TITLE
ActiveRecord: has_many through with foreign scope misses joining the table and generates wrong sql

### ISSUE THREAD

**Issue by doits** [rails/rails#14110]
See gist https://gist.github.com/doits/60b862bb45855b506ad9 for test template.

Basically when going from model `Person` over `Houses` to `Colors`, where `Houses` is filtered by a scope `damaged` that joins `Conditions`, the generated SQL misses to join the table `Conditions`.

The generated SQL for getting `person.damaged_houses` is correctly joining the tables:

```
  SELECT "houses".* FROM "houses" 
    INNER JOIN "conditions_houses" ON "conditions_houses"."house_id" = "houses"."id"
    INNER JOIN "conditions" ON "conditions"."id" = "conditions_houses"."condition_id"
    WHERE "houses"."person_id" = ? AND "conditions"."condition" = 'damaged'
```

But when selecting `person.damaged_colors`, the join is missed, only the condition is inserted:

```
SQLite3::SQLException: no such column: conditions.condition:
  SELECT "colors".* FROM "colors"
    INNER JOIN "houses" ON "colors"."house_id" = "houses"."id"
    WHERE "houses"."person_id" = ? AND "conditions"."condition" = 'damaged'
```

If I see it correctly, simply the join is missing, so the query should be:

```
SELECT "colors".* FROM "colors"
  INNER JOIN "houses" ON "colors"."house_id" = "houses"."id"
  INNER JOIN "conditions_houses" ON "conditions_houses"."house_id" = "houses"."id"
  INNER JOIN "conditions" ON "conditions"."id" = "conditions_houses"."condition_id"
  WHERE "houses"."person_id" = ? AND "conditions"."condition" = 'damaged'
```

Is this an ActiveRecord bug or am I doing it wrong?

**Comment by dsimard** [comment]
I have the same error in 4.2.1 : https://gist.github.com/dsimard/aca75b6c7e3dc2d31646

**Comment by PlugIN73** [comment]
Hi all. Happened to me:

     has_many :course_members, -> (object) { joins(:course).where(courses: {state: :approved, locale: object.locale}) }, class_name: 'Course::Member'
     has_many :lesson_members, through: :course_members

**Comment by miguelgraz** [comment]
Confirming that it still happens on current `master`, I'll try to suggest a solution if no one is already working on this.

**Comment by sevaorlov** [comment]
might be related to https://github.com/rails/rails/issues/22538

**Comment by rafaelfranca** [comment]
This should be fixed by https://github.com/rails/rails/pull/29413
