### ISSUE TITLE
Discrepancy between `date.to_s(:long)` and `l(date, format: :long)`

### ISSUE THREAD

**Issue by gabrielecirulli** [rails/rails#14237]
This is happening on my Rails 4.0.3 app but seems to also be present in master.

There seems to be a discrepancy between the `:long` format [defined in `Date::DATE_FORMATS`](https://github.com/rails/rails/blob/c6897b7d7b18b5c89aca46d4595b47c2590ce335/activesupport/lib/active_support/core_ext/date/conversions.rb#L9) (`%B %e, %Y`) and the one [defined in the default `locale/en.yml`](https://github.com/rails/rails/blob/master/activesupport/lib/active_support/locale/en.yml#L9) (`%B %d, %Y`).

Namely, the `%e` parameter in the former causes the rendered date to have two spaces between the month and the day when the day is single-digit, due to the fact that it pads the day number with spaces. The latter instead pads the day number with zeroes.

Is this discrepancy known of? I discovered it today while testing, because I used `to_s(:long)` in my test and the `l` helper in my view.

In my opinion, the date should be displayed without leading zeros on the day but also without repeated spaces. A format string of `%B %-e, %Y` seems to accomplish this.

**Comment by alexcameron89** [comment]
This should be good to close.

`:long` in `Date::DATE_FORMATS` was updated to `"%B %d, %Y"` in https://github.com/rails/rails/commit/2c5a8ba6f6e2e9c9d3ff2f2b5b36fb50e8a34b8b.

**Comment by pixeltrix** [comment]
@alexcameron89 thanks 👍
