### ISSUE TITLE
Support dynamic postgres column defaults 

### ISSUE THREAD

**Issue by searls** [rails/rails#14300]
I was surprised to find that I couldn't write the following migration when using postgresql:

``` ruby
class CreateMessages < ActiveRecord::Migration
  def change
    create_table :messages do |t|
      t.timestamp :received_at, default: "now()"
    end
  end
end
```

Doing so will immediately evaluate `now()` such that a psql description of the table will report the default is something like `default '2014-03-06 16:16:45.108266'::timestamp without time zone`.

I worked around this in my migration by using an alter statement immediately after creating the table:

``` ruby
ActiveRecord::Base.connection.execute "ALTER TABLE messages ALTER COLUMN received_at SET DEFAULT now()"
```

This seemed to solve our issue (the description of the column default was `default now()` and it worked fine).

However, any rake command dependent on `db:schema:load` and the schema.rb file are causing exactly the same issue, because `db:schema:dump` records this into my `db/schema.rb` file:

``` ruby
t.datetime "received_at", default: "now()"
```

Because `db/schema.rb` is generated and checked into source control, I'm struggling to think of any graceful workarounds to the issue.

**Comment by searls** [comment]
I can still reproduce this on 4.2.

**Comment by tejasbubane** [comment]
@searls Yes, the [Column Modifiers section on rails-guides](https://github.com/rails/rails/blob/master/guides/source/active_record_migrations.md#column-modifiers) states that when using dynamic values like date, the default will only be calculated for the first time.

@davekapp Thanks for the workaround.

**Comment by matfiz** [comment]
Just to update people who were searching for an answer. As for > Rails 4.2, defining the default with proc works:
`...,  default: -> { 'NOW()' }`

It produces the expected `default now()` in Postgres database.
