### ISSUE TITLE
Possible bug ordering mysql -> sqlite

### ISSUE THREAD

**Issue by vairix-dfernandez** [rails/rails#14418]
While I was working on an application, I found an issue when I changed the database engine.
I was using mysql and when I changed to sqlite I found out that the order of one  collection was different than before. I have data with same name but one have capital letters and others not.

### Query:
<code>Thing.order(:name)</code>
### Output in Mysql: 
-Apple
-apple
-Zinc
-zinc
### Output in Sqlite:
-Apple
-Zinc
-apple
-zinc

### Gems: 

ActiveRecord version: 4.0.1
Arel version: 4.0.2
mysql2 version: 5.5.35
sqlite3 version: 1.3.9

In case of want the application behaviour doesn’t change when we switch the database engine, I can think in two possible solutions:

Modifying ActiveRecord (best solution I think):

File: active_record/connection_adapters/sqlite3_adapter.rb
We could override ```to_sql``` method applying the lower method to each order node.

```
def to_sql(arel, binds = [])
  if arel.respond_to?(:ast)
    arel.ast.orders = arel.ast.orders.map do |order|
      order.expr.relation[order.expr.name].lower
    end
    binds = binds.dup
    visitor.accept(arel.ast) do
      quote(*binds.shift.reverse)
    end
  else
    arel
  end
end
```

Modifying Arel:

We could override the next methods in the following file:

arel/lib/arel/visitors/sqlite.rb

```
def visit_Arel_Nodes_Ascending o, a
  "LOWER(#{visit o.expr, a}) ASC"
end

def visit_Arel_Nodes_Descending o, a
  "LOWER(#{visit o.expr, a}) DESC"
end

```
What do you think about it?

/cc @tenderlove

**Comment by rafaelfranca** [comment]
Closing this one since it is more a feature request.

**Comment by rafaelfranca** [comment]
BTW, this feature is already in our roadmap.
