### ISSUE TITLE
`references` does not work with nested `includes`

### ISSUE THREAD

**Issue by sudhirj** [rails/rails#14657]
The following code works fine in Rails 4.0 and 4.1:

```
Movie.first.schedules.includes(:show).references(:show)
```

but this works only in Rails 4.0, and is broken in 4.1

```
Movie.first.schedules.includes(show: [:language]).references(:show)
```

In Rails 4.1, when the a nested include is used, the SQL generated seems to rename the `shows` table into `shows_schedules` for some reason, while continuing to refer to it later as simply `shows`. And this is with or without `references` being used.

```
LEFT OUTER JOIN `shows` `shows_schedules` ON `shows_schedules`.`id` = `schedules`.`show_id` 
..... 
INNER JOIN `shows` ON `schedules`.`show_id` = `shows`.`id`
```

**Comment by uberllama** [comment]
I **think** I've just run into this same issue, where I have the same relation being included twice and the arises not generated properly.

```ruby
posts = Post.includes(user: [:company], approver: [:company]))

ActiveRecord::StatementInvalid: PG::UndefinedTable: ERROR:  missing FROM-clause entry for table "companies_users"
LINE 1: ..._r12, "users"."updated_at" AS t3_r13, "companies...
```

Was there any progress on this from a year ago?

**Comment by senny** [comment]
@uberllama there has not been any progress. We always cross reference the issues when something is hapenning.

**Comment by kamipo** [comment]
I confirmed that `where("cities.id": 42)` works expected.
Please use hash condition instead.

**Comment by richardwan** [comment]
was this issue resolved by a future release of rails? i believe we ran into this issue when we added a nested includes (to force eager loading) to an existing references query.  we were quite surprised when the models were incorrectly populated even though the number of records was as expected.
