### ISSUE TITLE
Arel uses premature version of `to_sql` when unioning queries that use `eager_load` or `includes`

### ISSUE THREAD

**Issue by shekibobo** [rails/rails#14696]
This is related to #6132 and #13385.

It appears that Arel actually uses `#to_sql` in certain cases:

I've created a [gist that illustrates this happening](https://gist.github.com/shekibobo/10418963).

In the example gist, you can pop into it with `pry` and see the following:

``` irb
>> Division.without_users
D, [2014-04-10T16:51:06.897686 #68462] DEBUG -- :   SQL (1.2ms)  SELECT "divisions"."id" AS t0_r0, "users"."id" AS t1_r0, "users"."division_id" AS t1_r1 FROM "divisions" LEFT OUTER JOIN "users" ON "users"."division_id" = "divisions"."id" WHERE "users"."id" IS NULL
=> [#<Division id: 2>]
>> Division.without_users.to_sql
=> "SELECT \"divisions\".\"id\" AS t0_r0, \"users\".\"id\" AS t1_r0, \"users\".\"division_id\" AS t1_r1 FROM \"divisions\" LEFT OUTER JOIN \"users\" ON \"users\".\"division_id\" = \"divisions\".\"id\" WHERE \"users\".\"id\" IS NULL"
>> Division.without_admins
D, [2014-04-10T16:51:27.229423 #68462] DEBUG -- :   SQL (0.9ms)  SELECT "divisions"."id" AS t0_r0, "admins"."id" AS t1_r0, "admins"."division_id" AS t1_r1 FROM "divisions" LEFT OUTER JOIN "admins" ON "admins"."division_id" = "divisions"."id" WHERE "admins"."id" IS NULL
=> [#<Division id: 1>]
>> Division.without_admins.to_sql
=> "SELECT \"divisions\".\"id\" AS t0_r0, \"admins\".\"id\" AS t1_r0, \"admins\".\"division_id\" AS t1_r1 FROM \"divisions\" LEFT OUTER JOIN \"admins\" ON \"admins\".\"division_id\" = \"divisions\".\"id\" WHERE \"admins\".\"id\" IS NULL"
>> Division.without_users_or_without_admins.to_sql
=> "SELECT \"divisions\".* FROM ( SELECT \"divisions\".* FROM \"divisions\"  WHERE \"users\".\"id\" IS NULL UNION SELECT \"divisions\".* FROM \"divisions\"  WHERE \"admins\".\"id\" IS NULL ) \"divisions\""
>> Division.without_users_or_without_admins
D, [2014-04-10T16:51:46.427828 #68462] DEBUG -- :   Division Load (259.9ms)  SELECT "divisions".* FROM ( SELECT "divisions".* FROM "divisions"  WHERE "users"."id" IS NULL UNION SELECT "divisions".* FROM "divisions"  WHERE "admins"."id" IS NULL ) "divisions"
E, [2014-04-10T16:51:46.427967 #68462] ERROR -- : PG::UndefinedTable: ERROR:  missing FROM-clause entry for table "users"
LINE 1: ...OM ( SELECT "divisions".* FROM "divisions"  WHERE "users"."i...
                                                             ^
: SELECT "divisions".* FROM ( SELECT "divisions".* FROM "divisions"  WHERE "users"."id" IS NULL UNION SELECT "divisions".* FROM "divisions"  WHERE "admins"."id" IS NULL ) "divisions"
=> #<#<Class:#<Division::ActiveRecord_Relation:0x00000101ac8aa8>>:0x80d64554>
```

Since (as of edge rails), the `to_sql` output appears correct (though not sure when that got fixed, or if it's possible to backport that to `4-0-stable`). Originally I thought this was just a problem with `<= 4.0.4`, but since it is still broken when `to_sql` is supposedly fixed, it looks like Arel itself might be broken in this respect.

**Comment by joegiralt** [comment]
I'm not sure if this is still stale but i'm also having this issue
```
pry(main)> Teacher.where(id: 1).eager_load(:partnerships).to_sql
```
the SQL is then executed
```
  SQL (1.0ms)  SELECT "teachers"."id" AS t0_r0, "teachers"."member_id" AS t0_r1, "teachers"."created_at" AS t0_r2, "teachers"."updated_at" AS t0_r3, "teachers"."status" AS t0_r4, "teachers"."manager_id" AS t0_r5, "teachers"."status_dates" AS t0_r6, "teachers"."group_id" AS t0_r7, "teachers"."preferences" AS t0_r8, "teachers"."had_partnership" AS t0_r9, "teachers"."status_at" AS t0_r10, "teachers"."onboarded_at" AS t0_r11, "teachers"."tenant_id" AS t0_r12, "teachers"."ready_for_match_at" AS t0_r13, "teachers"."rematch_count" AS t0_r14, "partnerships"."id" AS t1_r0, "partnerships"."match_proposal_id" AS t1_r1, "partnerships"."created_at" AS t1_r2, "partnerships"."updated_at" AS t1_r3, "partnerships"."active" AS t1_r4, "partnerships"."kickoff_scheduled_for" AS t1_r5, "partnerships"."manager_id" AS t1_r6, "partnerships"."data" AS t1_r7, "partnerships"."rm_watch" AS t1_r8, "partnerships"."tenant_id" AS t1_r9, "partnerships"."rematch_needed" AS t1_r10, "partnerships"."scheduled_end_date" AS t1_r11, "partnerships"."date_ended" AS t1_r12 FROM "teachers" LEFT OUTER JOIN "match_proposals" ON "match_proposals"."teacher_id" = "teachers"."id" LEFT OUTER JOIN "partnerships" ON "partnerships"."match_proposal_id" = "match_proposals"."id" WHERE "teachers"."id" = $1  [["id", 1]]
```
and then the wrong sql string query is generated
```
=> "SELECT \"teachers\".* FROM \"teachers\" WHERE \"teachers\".\"id\" = 1"
```
It's my understanding that calling `.sql` on a  a ActiveRecord query shouldn't execute. I only have this problem when I use `eager_load`

**Comment by nickborromeo** [comment]
> I wonder if this is the same issue
> 
> ```
> [5] pry(main)> posts = Post.includes(:post_search_data).references(:post_search_data);
> [6] pry(main)> posts.select('id').to_sql
> => "SELECT \"posts\".\"id\", \"posts\".\"id\" AS t0_r0, \"posts\".\"user_id\" AS t0_r1, \"posts\".\"topic_id\" AS t0_r2, \"posts\".\"post_number\" AS t0_r3, \"posts\".\"raw\" AS t0_r4, \"posts\".\"cooked\" AS t0_r5, \"posts\".\"created_at\" AS t0_r6, \"posts\".\"updated_at\" AS t0_r7, \"posts\".\"reply_to_post_number\" AS t0_r8, \"posts\".\"reply_count\" AS t0_r9, \"posts\".\"quote_count\" AS t0_r10, \"posts\".\"deleted_at\" AS t0_r11, \"posts\".\"off_topic_count\" AS t0_r12, \"posts\".\"like_count\" AS t0_r13, \"posts\".\"incoming_link_count\" AS t0_r14, \"posts\".\"bookmark_count\" AS t0_r15, \"posts\".\"avg_time\" AS t0_r16, \"posts\".\"score\" AS t0_r17, \"posts\".\"reads\" AS t0_r18, \"posts\".\"post_type\" AS t0_r19, \"posts\".\"vote_count\" AS t0_r20, \"posts\".\"sort_order\" AS t0_r21, \"posts\".\"last_editor_id\" AS t0_r22, \"posts\".\"hidden\" AS t0_r23, \"posts\".\"hidden_reason_id\" AS t0_r24, \"posts\".\"notify_moderators_count\" AS t0_r25, \"posts\".\"spam_count\" AS t0_r26, \"posts\".\"illegal_count\" AS t0_r27, \"posts\".\"inappropriate_count\" AS t0_r28, \"posts\".\"last_version_at\" AS t0_r29, \"posts\".\"user_deleted\" AS t0_r30, \"posts\".\"reply_to_user_id\" AS t0_r31, \"posts\".\"percent_rank\" AS t0_r32, \"posts\".\"notify_user_count\" AS t0_r33, \"posts\".\"like_score\" AS t0_r34, \"posts\".\"deleted_by_id\" AS t0_r35, \"posts\".\"edit_reason\" AS t0_r36, \"posts\".\"word_count\" AS t0_r37, \"posts\".\"version\" AS t0_r38, \"posts\".\"cook_method\" AS t0_r39, \"posts\".\"wiki\" AS t0_r40, \"posts\".\"baked_at\" AS t0_r41, \"posts\".\"baked_version\" AS t0_r42, \"posts\".\"hidden_at\" AS t0_r43, \"posts\".\"self_edits\" AS t0_r44, \"posts\".\"reply_quoted\" AS t0_r45, \"post_search_data\".\"post_id\" AS t1_r0, \"post_search_data\".\"search_data\" AS t1_r1, \"post_search_data\".\"raw_data\" AS t1_r2, \"post_search_data\".\"locale\" AS t1_r3 FROM \"posts\" LEFT OUTER JOIN \"post_search_data\" ON \"post_search_data\".\"post_id\" = \"posts\".\"id\" WHERE (\"posts\".\"deleted_at\" IS NULL)"
> ```
> 
> Notice how the select is not being respected and all columns are being selected.

I wonder now that we have `left_outer_joins` maybe this can be an alternative when chaining with `select` so that it will filter the columns. It will produce the same query but with the `left_outer_join` `select` will be respected.

**Using includes and references**
```
[54] pry(#<BugTest>)> Division.includes(:users).references(:users).select("id").to_sql
=> "SELECT \"divisions\".\"id\", \"divisions\".\"id\" AS t0_r0, \"users\".\"id\" AS t1_r0, \"users\".\"division_id\" AS t1_r1 FROM \"divisions\" LEFT OUTER JOIN \"users\" ON \"users\".\"division_id\" = \"divisions\".\"id\""
```

This example shows that we still take all the columns of the model plus whatever is in the `select` method

**Using left_outer_joins**
```
[56] pry(#<BugTest>)> Division.left_outer_joins(:users).select("id").to_sql
=> "SELECT \"divisions\".\"id\" FROM \"divisions\" LEFT OUTER JOIN \"users\" ON \"users\".\"division_id\" = \"divisions\".\"id\""
```

This example shows it respects the `select` method.

cc @SamSaffron @rafaelfranca

**Comment by nickborromeo** [comment]
Regarding the script that was included in the OP, I do not think this is valid anymore. 🤔 When trying to run this script against master, I get 

```
NoMethodError: undefined method `union' for #<ActiveRecord::Relation [#<Division id: 2>]>
```

Since this issue is quiet old, I think if we wanted to union something like this, we can now use `or` instead. However, the way this is setup, `or` will not work. 

```
ArgumentError: Relation passed to #or must be structurally compatible. Incompatible values: [:eager_load]
```

https://github.com/rails/rails/blob/dcf545d20ca6110a360780bda1ba058d7083167a/activerecord/lib/active_record/relation/query_methods.rb#L747-L749

https://github.com/rails/rails/blob/dcf545d20ca6110a360780bda1ba058d7083167a/activerecord/lib/active_record/relation/query_methods.rb#L1523-L1535

cc @rafaelfranca @shekibobo thoughts on closing out this issue?

**Comment by kamipo** [comment]
Closing this since we can use `left_outer_joins` instead of `eager_load` now.

(About `union`, implicit delegation to arel is deprecated in 5.2 (#29619) and removed in 6.0 (d97980a16d76ad190042b4d8578109714e9c53d0)).
