### ISSUE TITLE
Rails 4 Database Connection Pool is very slow under load

### ISSUE THREAD

**Issue by reidmorrison** [rails/rails#14891]
Running many concurrent threads on Rails 4 slows down considerably when the threads are all trying to get a database connection from the pool. 

It can take over 3,000ms to get a database connection in production. The following code demonstrates the issue:

```ruby
proc = Proc.new do
  begin
    p Benchmark.ms { ActiveRecord::Base.connection.select('select 1=1') }
  rescue Exception => exc
    p exc
  ensure
    ActiveRecord::Base.clear_active_connections!
  end
end
100.times { Thread.new { p Benchmark.ms(&proc) } }
```

Below is the output from production showing the steadily growing connection times:
```
132.0
=> 100
irb(main):011:0> 100.0
283.0
351.0
416.0
477.0
506.0
542.0
580.0
617.0
667.0
704.0
742.0
770.0
791.0
813.0
849.0
896.0
899.0
932.0
953.0
983.0
1006.9999999999999
1038.0
1064.0
1082.0
1109.0
1128.0
1160.0
1192.0
1214.0
1242.0
1268.0
1297.0
1316.0
1344.0
1403.0
1431.0
1452.0
1483.0
1506.0
1539.0
1586.0
1611.0
1644.0
1673.0
1714.0
1767.0
1841.0
1948.0
2017.9999999999998
2054.0
2084.0
2115.0
2152.0
2192.0
2219.0
2256.0
2288.0
2318.0
2341.0
2340.0
2365.0
2509.0
2383.0
2398.0
2421.0
2443.0
2466.0
2499.0
2528.0
2554.0
2576.0
2597.0
2619.0
2638.0
2662.0
2692.0
2712.0
2740.0
2759.0
2780.0
2800.0
2819.0
2846.0
2869.0
2888.0
2908.0
2928.0
2948.0
2967.0
2989.0
3013.0
3035.0
3054.0
3075.0
3093.0
3114.0
3131.0
3155.0
3328.0
3328.0
3326.0
3326.0
3219.0
3320.0
3178.0
3323.0
3321.0
3321.0
3321.0
3320.0
3320.0
3320.0
3307.0
3305.0
3305.0
3321.0
3301.0
3301.0
3299.0
3300.0
3299.0
3300.0
3299.0
3297.0
3301.0
3295.0
3295.0
3294.0
3295.0
3294.0
3294.0
3292.0
3292.0
3292.0
3292.0
3291.0
3283.0
3284.0
3282.0
3284.0
3281.0
3284.0
3284.0
3285.0
3283.0
3283.0
3285.0
3289.0
3304.0
3304.0
3304.0
3304.0
3304.0
3304.0
3304.0
3304.0
3304.0
3304.0
3304.0
3282.0
3288.0
3284.0
3277.0
3277.0
3277.0
3277.0
3277.0
3278.0
3277.0
3277.0
3278.0
3278.0
3278.0
3278.0
3278.0
3277.0
3278.0
3278.0
3278.0
3278.0
3278.0
3278.0
3279.0
3278.0
3278.0
3279.0
3278.0
3278.0
3279.0
3279.0
3278.0
3279.0
3279.0
3279.0
3279.0
3279.0
3278.0
3279.0
```

The problem is with the global mutex around all the calls to the connection pool. Also, the database connection verification (ping) is performed inside the sync, blocking all other threads while a connection is verified, created, or re-created. 

After replacing the custom connection pool code with [GenePool](https://github.com/bpardee/gene_pool), the times drop significantly. It now only takes 1ms to checkout the connection and then about 5ms to do the verification (database ping) before the connection is returned.

Working on converting our patch into a pull request. The Rails code is much simpler and the GenePool Gem appears to maintain the current Rails connection pool behavior.

**Comment by matthewd** [comment]
Fixed in #14938
