### ISSUE TITLE
ActionDispatch::Routing::UrlFor.url_for with Hash raises error in an Engine's tests

### ISSUE THREAD

**Issue by BMorearty** [rails/rails#14935]
In a Rails controller of an engine, when the Hash form of `url_for` is called from controller tests, `url_for` raises an error if you try to let it use the default values for `:controller`, `:action`, and any other route-specific params:

    ActionController::UrlGenerationError Exception: No route matches {:action=>"index"}

This means you can't do things like `redirect_to action: :show` in the controller being tested. 

The error occurs whether url_for is called from the controller being tested, or from the test itself. E.g., `assert_redirected_to action: :edit`.

When called from within a Rails server, it does not raise an error. When I try to reproduce in a Rails app instead of an engine, it does not raise an error.

The error seems to stem from the fact that when running from inside a test, the routes don't have their `@defaults` ivar set correctly. At runtime, `@defaults` has `:controller` and `:action` keys. But in tests, `@defaults` is an empty hash.

To reproduce:

1. `rails plugin new engine_urlfor --mountable`
2. `rails g controller Foo index`
3. In FooController#index, add `render text: url_for` (you don't have to pass any params). This should render the current action's url.
4. In the controller test, `get :index, use_route: :engine_urlfor`. Watch it crash.
5. To watch it succeed at runtime, `cd test/dummy` and then `rails s`, then hit http://localhost:3000/engine_urlfor/foo/index.

This bug exists in 4.0 and 4.1. I'm not sure how far back it goes.

**Comment by sintro** [comment]
Can confirm this problem with 4.2.6. 
I am using RefineryCMS as engine. If you will try to do something like 
`redirect_to action: :index` in controller, you will get the error: `ActionController::UrlGenerationError No route matches {:action=>"index", :controller=>"-current-controller-full-path-"}`
Trying ``redirect_to action: :index, **use_route: :refinery**``, not working also.
The only working way is: 
``
redirect_to **refinery**.url_for(action: :index, use_route: :refinery)
``
or using named route (..._path).
