### ISSUE TITLE
Non-persisted polymorphic association reference behaves differently from non-polymorphic one

### ISSUE THREAD

**Issue by shunwen** [rails/rails#15028]
Here is the test case https://gist.github.com/shunwen/99b89c495eea5ad24079

I want to apologize first for that I don't have any idea is there a well-known term for what I am going to describe.

Here is the definition of models used in examples:

````ruby
class Post < ActiveRecord::Base
  has_many :comments, as: :commentable
end
 
class Comment < ActiveRecord::Base
  belongs_to :commentable, polymorphic: true
end
````
The inconsistent behavior I found:

**Polymorphic example**
````ruby
post = Post.new
post.comments.new
comment = post.comments.first
comment.commentable #=> nil
````

**Non-polymorphic example**
````ruby
post = Post.new
post.comments.new
comment = post.comments.first
comment.post #=> post
````

In **non-persisted polymorphic association**, I'd expect that `comment` knows its `commentable` object as in **non-polymorphic association**. The reason I am expecting this behavior is that, in the following example, when saving `post`, it also tries to validate and save `comment` as well. But my validation on `comment` depends on its `commentable`, it'd error if it can't access the `commentable` it belongs to.

````ruby
post = Post.new
post.comments.new
post.save #=> It saves both post and its comment
````

Currently my workaround is to build `comment` in non-chained syntax (see below). By doing so it doesn't save comment when saving `post`:

````ruby
post = Post.new
comment = Comment.new
comment.commentable = post
post.save #=> Only post is saved
comment.save
````

**Comment by senny** [comment]
@shunwen this is working because Rails usually tries to figure out the inverse association on it's own. This is not the case for polymorphic associations. Things should start working once you specify the inverse association yourself:

```ruby
class Post < ActiveRecord::Base
  has_many :comments, as: :commentable, inverse_of: :commentable
end

class Comment < ActiveRecord::Base
  belongs_to :commentable, polymorphic: true, inverse_of: :comments
end
```

**Comment by senny** [comment]
xref #9522 #15343
