### ISSUE TITLE
Invalid SQL generated when using count with select values

### ISSUE THREAD

**Issue by joshjordan** [rails/rails#15138]
`ExampleModel.select(ExampleModel.arel_table[:id]).count` produces this query:

```
SELECT COUNT(#<struct Arel::Attributes::Attribute relation=#<Arel::Table:0x007f982e9292a8 @name="example_models", @engine=ExampleModel(id: integer, created_at: datetime, updated_at: datetime), @columns=nil, @aliases=[], @table_alias=nil, @primary_key=nil>, name=:id>) FROM "example_models"
ActiveRecord::StatementInvalid: SQLite3::SQLException: unrecognized token: "#": SELECT COUNT(#<struct Arel::Attributes::Attribute relation=#<Arel::Table:0x007f982e9292a8 @name="example_models", @engine=ExampleModel(id: integer, created_at: datetime, updated_at: datetime), @columns=nil, @aliases=[], @table_alias=nil, @primary_key=nil>, name=:id>) FROM "example_models"
```

This is true of any `select` parameters I've tried (`ExampleModel.arel_table[Arel.star]`, static values, columns, etc.). Rails 3.2 correctly generated a `COUNT(*)` in this case regardless of the `select` parameters.

A real-world example of this is in a security layer, where you might do something like `ExampleModel.select([ExampleModel.arel_table[Arel.star], security_column_1, security_column_2])` for each relation before passing them on to your controllers, who now may perform a count on them. Of course, the controllers should not have to know that there's a `select` in the relation its working with.

Here's an example you can grab: https://github.com/joshjordan/rails-4-arel-count-fail

I'm happy to work on this issue (especially since its blocking our Rails 4 upgrade :), but lack the necessary experience. I'd need some guidance.

**Comment by leods92** [comment]
> the correct API is collection.count(:all). You can find this change listed on the CHANGELOG entry of 4.1

@rafaelfranca How about `#size`? It calls `#count` by default if collection is not loaded. I understand that when #size makes sense collection is usually already loaded, but still I'd be nice to have a way to solve this. It's tricky and I got that it's better to raise an exception than to make assumptions and deliver counts that might be unexpected.

What if we change #size behaviour? We could make it work as #length and load collection before calling #size. If current #count behaviour is kept (I'm personally for that) and :all continues to be a required argument when using any custom #select with #count, I think this is the best way to go.
Another way would be to accept an argument in #size and forward it to SQL but I think that's messy as it changes the common #size API (i.e. no arguments) and is not very semantic as sometimes that argument won't be used at all (i.e. when counting a loaded collection).

I'm looking forward to knowing your thoughts on this. :)

**Comment by matthewd** [comment]
@leods92 `size` was fixed (along with its friends, like `any?`) a year ago, in 4.1.2: 968c581ea34b5236af14805e6a77913b1cb36238 / #13648.

This issue remains open for the [TODO in calculations.rb](https://github.com/rails/rails/blob/228e3f01cb7cc5d0b51311c5c0185b878c4853cb/activerecord/lib/active_record/relation/calculations.rb#L368-L375).

**Comment by leods92** [comment]
@matthewd `size` hasn't been completely fixed yet. But I honestly haven't look this commit. Anyway, there's still a problem when size is called in an association.

I've written a test for such case: https://github.com/leods92/rails421sizebug

Should I open a new issue for it?

**Comment by leods92** [comment]
@matthewd I've just stumbled on this bug again today and realized I got no answer. No worries. Did you take a look at the test I wrote? Thanks! :)

**Comment by matthewd** [comment]
@leods92 sorry.. yes, please go ahead and open a new issue (or PR :smile:) for that -- they both involve counting, but as a specific case of something that's currently expected to work, it seems unrelated to this issue.
