### ISSUE TITLE
association as cache key not expand 

### ISSUE THREAD

**Issue by williamherry** [rails/rails#15225]
we have some code like this: 
```
json.cache! [course, course.tags] do
  json.merge! CourseSerializer.new(course).as_json
end
```

course has many tags. I looked data in memcached, the cache key is some like this: 
```
ITEM smartlion-cache:courses/65-20140429030214000000000/#<ActiveRecord::Associations::CollectionProxy::ActiveRecord_Associations_CollectionProxy_Tag:0x007f21c7ec13b0>/54c9a3c64e31adaf1742c16c77649599 [971 b; 1400155264 s]
```

looks it not expand tags but just call to_s, and every time this return differenct string, so it make course cache broken totally

the code https://github.com/rails/rails/blob/4-1-stable/activesupport/lib/active_support/cache.rb#L79-99 seems will expand

I also find some other people find ActiveRecord::Relation also have this issue http://stackoverflow.com/questions/15194270/rails-cache-key-generated-as-activerecordrelation

**Comment by yasyf** [comment]
I'm unable to reproduce this in `4.2.0`; it appears to be fixed.

**Comment by sgrif** [comment]
Thanks
