### ISSUE TITLE
"Couldn't find template for digesting" error when using provide in layouts

### ISSUE THREAD

**Issue by Dorian** [rails/rails#15255]
Hey, I had a lot of errors like that in my production app:

    Couldn't find template for digesting: templates/template

So I tried to figure out what happens and even built saw that the digest `template` was not correctly set (it was `templates/template` instead of `layouts/products` for instance).

So I built a sample app to reproduce the issue: [Dorian/template-digesting-bug](https://github.com/Dorian/template-digesting-bug)

If you run it and go to `/products`, you will see: `Couldn't find template for digesting: templates/template` in the logs.

![screen shot 2014-05-22 at 3 27 31 pm](https://cloud.githubusercontent.com/assets/129149/3058415/481f9cea-e1e0-11e3-8a77-ec94667a1068.png)

Hope that helps and maybe someone will find the issue, It should be somewhere in the digestor: [/actionview/lib/action_view/digestor.rb](https://github.com/rails/docrails/blob/master/actionview/lib/action_view/digestor.rb)

Also, see [rails/cache_digests#31](https://github.com/rails/cache_digests/issues/31).

**Comment by rafaelfranca** [comment]
I'm closing for now. Let us know if you could reproduce it.

**Comment by kakra** [comment]
I still can reproduce it in Rails 4.0.13 when using cache with `render collection: @somethings, partial: 'something_other'`. The error is:

    Couldn't find template for digesting: collections/collection.xml

**Comment by kirichkov** [comment]
I can reproduce this on 4.1.10 when using the shorthand syntax of render, e.g.

    render @somethings

Setting the partial explicitly solves it. E.g.:

    render @somethings, partial: 'somethings/something'

**Comment by Dorian** [comment]
@kirichkov: You need an explicit dependency:

```
<%# Template Dependency: todolists/todolist %>
<%= render_sortable_todolists @project.todolists %>
```

http://api.rubyonrails.org/v4.1.1/classes/ActionView/Helpers/CacheHelper.html

**Comment by kirichkov** [comment]
@Dorian This could be it. My assumption was that ````cache```` would use the same algorithm to determine the relevant template as ````render````

**Comment by Dorian** [comment]
@kirichkov: The cache digest is a regexp-based parsing of the template files, see: https://github.com/rails/rails/blob/master/actionview/lib/action_view/dependency_tracker.rb

**Comment by BM5k** [comment]
I’m seeing this when rendering partials like `render ‘my_partial’` where `my_partial` is in a different directory. For instance, with a partial in `views/application` while the parent template is in `views/admin/users`.

How is it that the template can be found to render, but not for digesting? This feels like a bug. It is certainly unexpected behavior.

The workaround of avoiding the shortcut form of `render` unless passing an object or collection seems to be the right answer.

**Comment by robotmay** [comment]
Just bumped into this myself. There's still an issue with Rails struggling to perform the digests if you use `render template: 'blah'`, as illustrated by the example @Dorian provided in the initial ticket. Using the `template` option is the recommended way of doing nested layouts according to the Rails guides, so it should probably be supported by the digest system.

Anyone have any ideas on how to alter the digest system to accommodate that option?

**Comment by casiodk** [comment]
+1

**Comment by agis-** [comment]
Just stumbled upon this issue too on Rails 4.2.4. Not sure what's the actual case yet though.

**Comment by prosanelli** [comment]
i am seeing the render template issue too

**Comment by existent-co-uk** [comment]
This is affecting me too, in 4.2.4; definitely still an issue

**Comment by matteomelani** [comment]
+1 
my 4.2.4 app is also affected

**Comment by guinslym** [comment]
??? not sure also what's going on. My 4.2.1 app have the same issue

**Comment by conzett** [comment]
I'm still running into this error but was able to work around it in my case by specifying the full path to the shared partial. For example changing:
`= render partial: 'errors', locals: { model: @user }`
to
`= render partial: 'application/errors', locals: { model: @user }`
seems to fix it.

**Comment by chrishough** [comment]
This error is showing up in rails 4.2.6

**Comment by yivo** [comment]
Rails 4.2.7.1
`Couldn't find template for digesting: accounting/_blocks/_menu`

**Comment by elia** [comment]
Apparently `controller_name` ignores the namespace

```
Spree::HomePagesController.controller_name
=> "home_pages"
```

But it's used by `EtagWithTemplateDigest` to get the template name:

```rb
    def pick_template_for_etag(options)
      options.fetch(:template) { "#{controller_name}/#{action_name}" }
    end

    def lookup_and_digest_template(template)
      ActionView::Digestor.digest name: template, finder: lookup_context
    end
```

At that point the digestor can't find a template for `home_pages/index`, but would be able to for `spree/home_pages/index` (_output was partially redacted_):

```
> finder = ApplicationController.new.lookup_context;
> ActionView::Digestor.new(name: 'home_pages/index', finder: finder).send(:template) rescue $!.class
=> ActionView::MissingTemplate
> ActionView::Digestor.new(name: 'spree/home_pages/index', finder: finder).send(:template)
=> "app/views/spree/home_pages/index.html.haml"
```

––

At least this should be **one** of the causes, probably the one encountered by:

- @yivo https://github.com/rails/rails/issues/15255#issuecomment-239830630
- @BM5k https://github.com/rails/rails/issues/15255#issuecomment-102179108

**Comment by elia** [comment]
Ok, just found it's been fixed on master by https://github.com/rails/rails/pull/25817
@rafaelfranca any chance for it to be backported to 4.x?
