### ISSUE TITLE
Wrong form field names in nested fields_for

### ISSUE THREAD

**Issue by ojab** [rails/rails#15332]
I have a view with structure like this:
```
<%= form_for :foos, url: root_path do |f| %>
  <% @foos.each do |foo| %>
    <%= f.fields_for "foo[]", foo do |f2| %>
      <%= f2.fields_for :bars do |b| %>
        <%= f2.text_field :id %>
        <%= b.text_field :id %>
      <% end %>
    <% end %>
  <% end %>
<% end %>
```
and there is an issue with inner form fields naming: while outer(f2) fields has names that starts with 'foos[foo][]', inner(b) fields has names like 'foos[foo[]]', so submitting of such form fails with something like 'expected Array (got Rack::Utils::KeySpaceConstrainedParams) for param `foo''.

This issue is reproducible both in 4.1.1 and master, test repo can be found at https://github.com/ojab/nested_fail

**Comment by MhdSyrwan** [comment]
@ojab to generate what you hard coded using rails you should use `accept_nested_attributes_for`, check this link as an example http://stackoverflow.com/questions/2212622/accepts-nested-attributes-for-with-has-many-through-options
