### ISSUE TITLE
Thread test state leak

### ISSUE THREAD

**Issue by zuhao** [rails/rails#15770]
In `activesupport/test/core_ext/thread_test.rb`, we have the following test case:

```ruby
def test_main_thread_variable_in_enumerator
  assert_equal Thread.main, Thread.current

  Thread.current.thread_variable_set :foo, "bar"

  thread, value = Fiber.new {
    Fiber.yield [Thread.current, Thread.current.thread_variable_get(:foo)]
  }.resume

  assert_equal Thread.current, thread
  assert_equal Thread.current.thread_variable_get(:foo), value
end
```

This test actually adds a new thread variable `:foo` to the main thread, without deleting it after the test, which leads to potential state leaks.

However, currently neither Ruby or Rails seem to support removing thread variables. I've tried to add `remove_thread_variable` method in `activesupport/lib/core_ext/thread.rb` but it was not evaluated because of https://github.com/rails/rails/blob/master/activesupport/lib/active_support/core_ext/thread.rb#L86, as Ruby's core Thread has already implemented `thread_variable_set`.

Do we want to add the new method and modify L86 accordingly, or is there any other workaround to restore the test states?

cc @senny

**Comment by rafaelfranca** [comment]
Closed by 8b3cd74
