### ISSUE TITLE
Problem with columns named 'format' on edge.

### ISSUE THREAD

**Issue by thelucid** [rails/rails#15900]
I am running on the latest edge and there is a problem when using a column named 'format', this is a regression as it was fine on 4.1.2. The error I am getting is:

```
too few arguments
```

when calling:

```ruby
record.send('format')
```

I'm guessing there is some monkey patching of `Object` in active_support.

**Comment by nerdinand** [comment]
I tried to reproduce this here: https://gist.github.com/nerdinand/d6d839841a18a481eed7
Looks fine to me on current master...
Or maybe I misunderstood something?
