### ISSUE TITLE
redirect_to with second argument should not delete the "status" param of the url options

### ISSUE THREAD

**Issue by donv** [rails/rails#15901]
Hi!

Currently it is difficult to have a route with a parameter called ```status```.  When redirecting to such a route, the ```_extract_redirect_to_status``` will gobble it up.  Calling

```ruby
redirect_to(controller: 'foo', action: 'bar', status: 'baz')
```

will delete the ```status: baz``` value of the ```options``` and try to use it as an HTTP response status code.  For backwards compatibility, this must be kept.

There should be a way to avoid this using the second argument to ```redirect_to```:

```ruby
redirect_to({controller: 'foo', action: 'bar', status: 'baz'}, status: 302)
```

This will currently delete the ```status: baz``` value of the ```options``` and ignore the given ```status: 302``` value in the ```response_status```.  The given response status should have priority over a url option of the same name.

If the ```response_status``` hash is given, the ```status``` key of the url ```options``` should be left alone, even if the ```response_status``` hash does not include the ```status:``` key.  That way we can use the second argument as a switch to indicate that the first argument is a pure location argument.

I guess the same should be true for ```flash``` options like ```notice```and ```alert```.

Tested with Rails 3.2.18.

**Comment by arthurnn** [comment]
As I explained above, the first argument on `redirect_to` method, can receives `status`, flash options and more. So if you are passing them intending to set a parameter instead of the status code, you will need to use the `url_for` helper.
