### ISSUE TITLE
Format constrained routes causes `ArgumentError` to be raised when attempting to use `url_helpers`.

### ISSUE THREAD

**Issue by sebjacobs** [rails/rails#15923]
I found this issue when working on a Rails `4.0.4` app, however it appears to present in later versions too.

I have setup an example application[1], however I would also like to demonstrate this issue below.

Let's say we have an application with a basic routes file and a `Presenter` like object which wants to make use
of these routes.

    RoutesExample::Application.routes.draw do
      resources :posts
    end

    class PostPresenter
      include Rails.application.routes.url_helpers
      include ActionView::Helpers::UrlHelper
    
      def index_path
        posts_path
      end
      
      def index_link
        link_to 'Index', index_path
      end
    end

Calling `PostPresenter.new.index_path` work fines.

However once you introduce a `format` constraint to your routes,

    RoutesExample::Application.routes.draw do
      resources :posts, constraints: { format: :html }
    end

calling `PostPresenter.new.index_path` now results in an `ArgumentError` being raised[2].

[1] https://github.com/sebjacobs/routes_example/
[2] https://github.com/rails/rails/blob/master/actionview/lib/action_view/helpers/url_helper.rb#L38

**Comment by justincase** [comment]
Appears to be fixed in 4.2.0

**Comment by magikid** [comment]
@sebjacobs if this is fixed as of 4.2.0, can you close this issue?

**Comment by sebjacobs** [comment]
@magikid I can confirm that this is no longer an issue in `4.2.x`.
