### ISSUE TITLE
content_tag, when called with a block, isnt respecting `escape` parameter

### ISSUE THREAD

**Issue by ktaragorn** [rails/rails#16060]
[content_tag](http://apidock.com/rails/v4.0.2/ActionView/Helpers/TagHelper/content_tag) when called with a block, calls `capture` which escapes the string result of the block regardless of what is specified in the `escape` argument to `content_tag`, `content_tag_string` eventually checks the argument, but it appears to be too late by then.

https://github.com/rails/rails/blob/master/actionview/lib/action_view/helpers/tag_helper.rb  
`````
      def content_tag(name, content_or_options_with_block = nil, options = nil, escape = true, &block)
        if block_given?
          options = content_or_options_with_block if content_or_options_with_block.is_a?(Hash)
          content_tag_string(name, capture(&block), options, escape)
        else
          content_tag_string(name, content_or_options_with_block, options, escape)
        end
      end
`````

https://github.com/rails/rails/blob/master/actionview/lib/action_view/helpers/capture_helper.rb  
`````
     def capture(*args)
        value = nil
        buffer = with_output_buffer { value = yield(*args) }
        if string = buffer.presence || value and string.is_a?(String)
          ERB::Util.html_escape string
        end
      end
`````

**Comment by christianlerke** [comment]
I have switched from Rails 4 to 5 and have the following probelm in rails 5.1.4:
This code snippet or in fact any nested tag helper now escapes whatever is inside the block which did not happen in Rails 4.
```
content_tag :div, class: 'result-icon' do
    content_tag :span, nil, class: "icon-customer"
end
```

**Rails 4 result**
`<div class="result-icon"><span class='icon-customer'></span></div>`

**Rails 5 result**
`<div class="result-icon">&amp;lt;span class=&amp;quot;icon-customer&amp;quot;&amp;gt;&amp;lt;/span&amp;gt;</div>`

This does not happen if I do not use the block but send the content as a variable:
`content_tag(name, content_or_options_with_block = nil, options = nil, escape = true, &block)`

`content_tag :div, content_tag(:span, nil, class: "icon-customer"), class: 'result-icon'` produces the expected result in Rails 4 as well as 5.

However this becomes infeasible with more than one layer of nesting

**Comment by christianlerke** [comment]
@ktaragorn @matthewd did you find a solution for this?
