### ISSUE TITLE
Through associations are not setting both parent IDs correctly

### ISSUE THREAD

**Issue by sgrif** [rails/rails#16139]
Present on 4-0-stable, 4-1-stable, and master. Gist to reproduce: https://gist.github.com/sgrif/fbb71923cb0bc35df57a -- Appears to be an edge case that was not handled by https://github.com/rails/rails/pull/15579. Originally reported as https://github.com/rails/protected_attributes/issues/39, and here https://github.com/rails/rails/commit/c6a8e097046d9cd2b565664748bb180714103429#commitcomment-6975794. 

/cc @peternash

**Comment by rafaelfranca** [comment]
@sgrif bot will close but if you disagree please reopen and add the "With reproduction steps" tag.
