### ISSUE TITLE
Counter cache doesn't update if parent model primary key changes

### ISSUE THREAD

**Issue by noinkling** [rails/rails#16159]
I'm not sure if you would even want to account for this because primary keys shouldn't typically be changing, and I don't know how you'd work a fix into the current implementation, but I thought I'd report it regardless.

``` ruby
class Post < ActiveRecord::Base
  has_many :comments
end

class Comment < ActiveRecord::Base
  belongs_to :post, counter_cache: true
end
```

``` ruby
post = Post.create
comment = Comment.create
post.comments << comment
post.reload.comments_count  # => 1

post.update(id: 9999)  # or any new id
post.reload.comments_count  # => 1
post.comments.count  # => 0 (executes SQL query)

post.comments << comment
post.reload.comments_count  # => 2
post.comments.count  # => 1
```

Similarly when adding a new parent record which is already referenced:

``` ruby
comment = Comment.create(post_id: 50)
post = Post.create(id: 50)
post.reload.comments_count  # => 0
post.comments.count  # => 1

post.comments << comment
post.reload.comments_count  # => 1
post.comments.count  # => 2
```

I assume this is because it hooks into the callback cycle of child records only (in this case `comments`). 

Like I said this obviously wouldn't be typical Active Record usage, and I know it's not equivalent to the similar issue that was fixed recently (on the other side of the association) in #9722. But at the very least I think the docs should make it clear that `counter_cache` does have its caveats which may result in inconsistencies.

**Comment by maximus242** [comment]
> I'm not sure if you would even want to account for this because primary keys shouldn't typically be changing, and I don't know how you'd work a fix into the current implementation, but I thought I'd report it regardless.
> 
> ```ruby
> class Post < ActiveRecord::Base
>   has_many :comments
> end
> 
> class Comment < ActiveRecord::Base
>   belongs_to :post, counter_cache: true
> end
> ```
> 
> ```ruby
> post = Post.create
> comment = Comment.create
> post.comments << comment
> post.reload.comments_count  # => 1
> 
> post.update(id: 9999)  # or any new id
> post.reload.comments_count  # => 1
> post.comments.count  # => 0 (executes SQL query)
> 
> post.comments << comment
> post.reload.comments_count  # => 2
> post.comments.count  # => 1
> ```
> 
> Similarly when adding a new parent record which is already referenced:
> 
> ```ruby
> comment = Comment.create(post_id: 50)
> post = Post.create(id: 50)
> post.reload.comments_count  # => 0
> post.comments.count  # => 1
> 
> post.comments << comment
> post.reload.comments_count  # => 1
> post.comments.count  # => 2
> ```
> 
> I assume this is because it hooks into the callback cycle of child records only (in this case `comments`).
> 
> Like I said this obviously wouldn't be typical Active Record usage, and I know it's not equivalent to the similar issue that was fixed recently (on the other side of the association) in #9722. But at the very least I think the docs should make it clear that `counter_cache` does have its caveats which may result in inconsistencies.

I personally find this inconsistency odd, why would we have a cache for a stale object? We should break the cache then no?
