### ISSUE TITLE
HashWithIndifferentAccess#symbolize_keys converts values (rails 4+)

### ISSUE THREAD

**Issue by bughit** [rails/rails#16247]
``` ruby
    def symbolize_keys; to_hash.symbolize_keys! end

    def to_hash
      _new_hash= {}
      each do |key, value|
        _new_hash[convert_key(key)] = convert_value(value, for: :to_hash)
      end
      Hash.new(default).merge!(_new_hash)
    end
```

symbolize_keys should do what it says, should not mess with values

**Comment by berniechiu** [comment]
Found this an issue when you want the first level of keyword arguments from symbolize keys, but keep the `IndifferentHash` intact.

```ruby
params = ActiveSupport::HashWithIndifferentAccess.new({ 'hello' => 'world', 'world' => { 'hello' => 'world' } })

def something_to_do(hello:, world:)
  puts "Access world with indifferent "#{world[:hello]}" #=> empty value
end

something_to_do(params.symbolize_keys)
```

**Comment by ximus** [comment]
yeah i'm on the same boat as @berniechiu , super confusing until you open the source of `to_hash`.

It runs against convention and expectations for a `#to_*` method to modify child values.

I get must be convenient for some cases to magically "un-withindifferentaccess-ize" an entire tree of hashes. Do we prefer rails magic, or rais principle of least expecation. Seems like we can't have both here.
