### ISSUE TITLE
Possible issue w/ `becomes`

### ISSUE THREAD

**Issue by kyledecot** [rails/rails#16269]
In my migration I'm converting my `posts` table to use uuids instead of the default integers via something like the following:

```
...
create_table :posts_temp, id: :uuid do |t|
  t.string :title
  ...
end

post_temp_model = Class.new(ActiveRecord::Base) do
  self.table_name = :posts_temp
end

Post.all.each do |post|
  post_temp = post.dup.becomes(post_temp_model)
  binding.pry
  post_temp.title # => "foobar"
  post_temp.save # => true
  post_temp.reload
  post_temp.title # => nil
end
...
```

When running this and inspecting what `post_temp.title` is the value appears to be there. When calling `post_temp.reload` and inspecting the `title` again however it's `nil`. It seems as though the value is not being saved to the database.

Is this a bug or am I doing something incorrectly here?

**Comment by maclover7** [comment]
This passes for me on Rails master. I think the issue is that you are using SQLite for your database -- I don't think SQLite supports UUID. I think this should be closed.
