### ISSUE TITLE
nested `has many :though` associations don't work as expected on unpersisted instances

### ISSUE THREAD

**Issue by zoltankiss** [rails/rails#16313]
gist to reproduce this issue: https://gist.github.com/zoltankiss/bd8a28fb749e66b449b5

If we have

``` ruby
class Post < ActiveRecord::Base
  has_many :books, through: :author
  has_many :subscriptions, through: :books
end

class Author < ActiveRecord::Base
  has_one :post
  has_many :books
  has_many :subscriptions, through: :books
end

class Book < ActiveRecord::Base
  belongs_to :author
  has_many :subscriptions
end

class Subscription < ActiveRecord::Base
  belongs_to :book
end
```

then if `post` is not persisted, e.g `post = Post.new`, then
`post.subscriptions` will be empty no matter what.

In contrast if `post` is persisted,
e.g if `post = Post.create!` then `post.subscriptions` works as
expected.

This property could be considered even more unusual since
associations in general, work on records that are not persisted.

e.g if

``` ruby
class Post < ActiveRecord::Base
  has_many :subscriptions, through: :author
end
```

then `post.subscriptions` works as expected in all of the
above cases.

**Comment by zoltankiss** [comment]
@rafaelfranca update: this issue seems to still be present on `master`, `4-2-stable`, and `4-1-stable`.
I've rebased the pull request, and travis is passing.

**Comment by guzart** [comment]
I believe this is also an issue for `has_one :through`. 

The reason I need to access the chained association for a new record if because a custom active model validator.
