### ISSUE TITLE
NoMethodError: undefined method `reverse' for nil:NilClass

### ISSUE THREAD

**Issue by z5h** [rails/rails#16423]
I have an ActiveRecord class where 
`self.groups` is used for permissioning and returns an instance of Group::ActiveRecord_Associations_CollectionProxy.

In Rails 3  I could call:
`User.joins(:user_groups).where(:user_groups => {:group_id => self.groups})` 
to find users with access to the resource.

The tables are as one would expect.

In Rails 4, the same call results in the stacktrace included below.

I can be fixed by calling  
`User.joins(:user_groups).where(:user_groups => {:group_id => self.groups.pluck(:id)})`
which has the unfortunate effect of an extra trip to the database.

------
<pre>
Minitest::UnexpectedError: NoMethodError: undefined method `reverse' for nil:NilClass
    activerecord (4.1.4) lib/active_record/connection_adapters/abstract/database_statements.rb:14:in `block in to_sql'
    arel (5.0.1.20140414130214) lib/arel/visitors/bind_visitor.rb:26:in `call'
    arel (5.0.1.20140414130214) lib/arel/visitors/bind_visitor.rb:26:in `visit_Arel_Nodes_BindParam'
    arel (5.0.1.20140414130214) lib/arel/visitors/visitor.rb:22:in `visit'
    arel (5.0.1.20140414130214) lib/arel/visitors/to_sql.rb:515:in `visit_Arel_Nodes_Equality'
    arel (5.0.1.20140414130214) lib/arel/visitors/visitor.rb:22:in `visit'
    arel (5.0.1.20140414130214) lib/arel/visitors/to_sql.rb:496:in `block in visit_Arel_Nodes_And'
    arel (5.0.1.20140414130214) lib/arel/visitors/to_sql.rb:496:in `map'
    arel (5.0.1.20140414130214) lib/arel/visitors/to_sql.rb:496:in `visit_Arel_Nodes_And'
    arel (5.0.1.20140414130214) lib/arel/visitors/visitor.rb:22:in `visit'
    arel (5.0.1.20140414130214) lib/arel/visitors/to_sql.rb:204:in `block in visit_Arel_Nodes_SelectCore'
    arel (5.0.1.20140414130214) lib/arel/visitors/to_sql.rb:203:in `each'
    arel (5.0.1.20140414130214) lib/arel/visitors/to_sql.rb:203:in `each_with_index'
    arel (5.0.1.20140414130214) lib/arel/visitors/to_sql.rb:203:in `visit_Arel_Nodes_SelectCore'
    arel (5.0.1.20140414130214) lib/arel/visitors/mysql.rb:41:in `visit_Arel_Nodes_SelectCore'
    arel (5.0.1.20140414130214) lib/arel/visitors/to_sql.rb:163:in `block in visit_Arel_Nodes_SelectStatement'
    arel (5.0.1.20140414130214) lib/arel/visitors/to_sql.rb:163:in `each'
    arel (5.0.1.20140414130214) lib/arel/visitors/to_sql.rb:163:in `visit_Arel_Nodes_SelectStatement'
    arel (5.0.1.20140414130214) lib/arel/visitors/mysql.rb:36:in `visit_Arel_Nodes_SelectStatement'
    arel (5.0.1.20140414130214) lib/arel/visitors/visitor.rb:22:in `visit'
    arel (5.0.1.20140414130214) lib/arel/visitors/to_sql.rb:482:in `visit_Arel_Nodes_In'
    arel (5.0.1.20140414130214) lib/arel/visitors/visitor.rb:22:in `visit'
    arel (5.0.1.20140414130214) lib/arel/visitors/to_sql.rb:496:in `block in visit_Arel_Nodes_And'
    arel (5.0.1.20140414130214) lib/arel/visitors/to_sql.rb:496:in `map'
    arel (5.0.1.20140414130214) lib/arel/visitors/to_sql.rb:496:in `visit_Arel_Nodes_And'
    arel (5.0.1.20140414130214) lib/arel/visitors/visitor.rb:22:in `visit'
    arel (5.0.1.20140414130214) lib/arel/visitors/to_sql.rb:204:in `block in visit_Arel_Nodes_SelectCore'
    arel (5.0.1.20140414130214) lib/arel/visitors/to_sql.rb:203:in `each'
    arel (5.0.1.20140414130214) lib/arel/visitors/to_sql.rb:203:in `each_with_index'
    arel (5.0.1.20140414130214) lib/arel/visitors/to_sql.rb:203:in `visit_Arel_Nodes_SelectCore'
    arel (5.0.1.20140414130214) lib/arel/visitors/mysql.rb:41:in `visit_Arel_Nodes_SelectCore'
    arel (5.0.1.20140414130214) lib/arel/visitors/to_sql.rb:163:in `block in visit_Arel_Nodes_SelectStatement'
    arel (5.0.1.20140414130214) lib/arel/visitors/to_sql.rb:163:in `each'
    arel (5.0.1.20140414130214) lib/arel/visitors/to_sql.rb:163:in `visit_Arel_Nodes_SelectStatement'
    arel (5.0.1.20140414130214) lib/arel/visitors/mysql.rb:36:in `visit_Arel_Nodes_SelectStatement'
    arel (5.0.1.20140414130214) lib/arel/visitors/visitor.rb:22:in `visit'
    arel (5.0.1.20140414130214) lib/arel/visitors/visitor.rb:5:in `accept'
    arel (5.0.1.20140414130214) lib/arel/visitors/bind_visitor.rb:11:in `accept'
    activerecord (4.1.4) lib/active_record/connection_adapters/abstract/database_statements.rb:13:in `to_sql'
    activerecord (4.1.4) lib/active_record/connection_adapters/abstract/database_statements.rb:24:in `select_all'
    activerecord (4.1.4) lib/active_record/connection_adapters/abstract/query_cache.rb:70:in `select_all'
    activerecord (4.1.4) lib/active_record/querying.rb:39:in `find_by_sql'
    activerecord (4.1.4) lib/active_record/relation.rb:604:in `exec_queries'
    activerecord (4.1.4) lib/active_record/relation.rb:486:in `load'
    activerecord (4.1.4) lib/active_record/relation.rb:231:in `to_a'
    activerecord (4.1.4) lib/active_record/relation/delegation.rb:46:in `to_ary'

</pre>

**Comment by MGotink** [comment]
@arthurnn, I believe this issue can be closed, it's solved since 4.1.6.rc1 with 9ab12cb.

**Comment by arthurnn** [comment]
thank @MGotink .
I will close this, please let me know if this doesn't work on 4.1.10.rc3 .

thanks

**Comment by MGotink** [comment]
It's working fine in 4.1.10.rc3 for me.
