### ISSUE TITLE
Different behaviors while fetching value for enum fields

### ISSUE THREAD

**Issue by hansyadav** [rails/rails#16459]
Is there any reason that we don't have consistent implementation across all the methods while fetching value for enum fields? some of them return db values while others return their corresponding labels as defined in models. 
For ex.
enum enum_field: {a: 1, b: 2}       # defined in model

while accessing the field, it gives:
obj.enum_field => a 
obj[:enum_field] => 1

This issue is related to https://github.com/rails/rails/pull/14017

**Comment by chancancode** [comment]
This is now fixed on master (Rails 5) via c51f9b6
