### ISSUE TITLE
No longer possible to override templates for migrations created by scaffolding

### ISSUE THREAD

**Issue by PatrickKing** [rails/rails#16507]
Generally, templates for Rails' generators can be overridden by placing an alternative template at `lib/templates/<gem_name>/<generator_name>/<template>`, but sometime after upgrading to Rails 4 the override template for scaffolded create table migrations stopped working. 

I've traced the change to [this commit](https://github.com/rails/rails/commit/20e041579f5fe9df51bdc40048cc1ef78915e116), and the file `activerecord/lib/rails/generators/active_record/model/model_generator.rb `. Previously there was a lookup for the template file, it is now hard coded to point to the internal Rails template. 

To reproduce, all you need is some content in the expected place for a custom template: `lib/templates/active_model/migration/create_table_migration.rb` (based on the template being in `generators/active_record/migration/templates/create_table_migration.rb`), and to then generate a scaffold, `rails g scaffold MyModel foo:bar`. The created migration won't reflect the overridden template.

**Comment by senny** [comment]
I'm closing this in favor of #13972 to keep the discussion focused.

@PatrickKing thank you for reporting.
