### ISSUE TITLE
validates_uniquness_of possibly takes into account other configured databases

### ISSUE THREAD

**Issue by ShayDavidson** [rails/rails#16530]
I'm creating a migration of legacy data from one Rails application to another (both DBs are Postgresql).

My new application has a v`alidates_uniqueness_of` validation for one of the models.

I created legacy models classes that establish a connection to the legacy DB (using establish_connection :legacy). During the application-level migration, I copy the model data from the legacy table to create a new model in my new application, row by row. The process fails with the first model creation, since the uniqueness validation fails (even though the __new DB is still empty__).

This makes me believe `validates_uniqueness_of` takes the legacy DB into account as well for some reason.

The table for the model with the validation, has the same name both in the legacy database and in the new one (may be related to the issue).

**Comment by al2o3cr** [comment]
I've attempted to reproduce this behavior:

https://gist.github.com/al2o3cr/e8b9be3c083f906743d3

4.0.8, 4.1.8 and 4.2.0 all save the record successfully.

**Comment by rafaelfranca** [comment]
Closing so. @ShayDavidson Let us know if you still can reproduce.
