### ISSUE TITLE
Options for belongs_to does not contain primary_key in documentation

### ISSUE THREAD

**Issue by gorn** [rails/rails#16694]
[Chapter 4.1.2] (http://edgeguides.rubyonrails.org/association_basics.html#options-for-belongs-to) of Active Record Associations documetation does not mention `:primary_key` option which however works as expected - giving the name of index column in the other table.

**Comment by gorn** [comment]
Still an issue in master. However girishso commit b5b773f fixes this, so it just needs to be pulled in.

**Comment by zzak** [comment]
This was fixed by #16698, thanks for the report!
