### ISSUE TITLE
Add has_secure_key to Active Record

### ISSUE THREAD

**Issue by dhh** [rails/rails#16879]
In line with `#has_secure_password`, we should have `#has_secure_key`, which can be used for email-in dropbox keys and the like. Here's a proposed implementation. If anyone wants to wrap it up as a full patch with tests, that'd be swell:

```ruby
require 'securerandom'

module HasSecureKey
  def has_secure_key(attribute, key_length: 24)
    before_create "set_generated_#{attribute}_key"

    define_method("rekey_#{attribute}") do
      send("set_generated_#{attribute}_key")
      save!
    end

    define_method("set_generated_#{attribute}_key") do
      send "#{attribute}=", self.class.generate_unique_random_secure_key(key_length) { |key| self.class.find_by(attribute => key) }
    end

    private "set_generated_#{attribute}_key"
  end

  def generate_unique_random_secure_key(key_length)
    1000.times do
      bytes = (key_length / 2.0).ceil
      token = SecureRandom.hex(bytes).first(key_length)

      return token unless yield(token)
    end

    raise 'No unique key found after 1000 tries'
  end
end

ActiveRecord::Base.send :extend, HasSecureKey
```

**Comment by habermann24** [comment]
What about something really simple like this for the actual random token generation?
Pretty confused why one would need to implement Base62 here!?

```ruby
key_length = 24
range = [*'0'..'9', *'a'..'z', *'A'..'Z']
Array.new(key_length) { range.sample }.join
```

**Comment by aprescott** [comment]
@habermann I don't think `Enumerable#sample` is cryptigraphically secure. Not all methods with "random" in their description are the same quality when it comes to secure tokens or keys.

**Comment by aprescott** [comment]
(Whoops. Forgot that the `sample` method isn't on Enumerable. Fixed.)

**Comment by dhh** [comment]
@robertomiranda made this happen :tada:
