### ISSUE TITLE
`redirect_to` in ActionController doesn't respect `trailing_slash` on `default_url_options`

### ISSUE THREAD

**Issue by andremedeiros** [rails/rails#16939]
I have the following on my `config/application.rb` file:
`config.action_controller.default_url_options = { trailing_slash: true }`

URLs seem to be generated properly, but when I pass a hash to `redirect_to`, for some reason it's not generating the URLs with the trailing slash.

Is this intended behaviour, or should it respect `default_url_options` as well?

**Comment by dabrorius** [comment]
@pixeltrix I believe that redirect inside routes.rb can't accept controller and action as parameters, you need to pass in exact path. So it's up to you to add trailing slash in that case, right?

I tried to reproduce the issue but it seems to work fine in rails 4.2.0 just as @tgxworld said.
