### ISSUE TITLE
Query with 'exists' subquery fails to bind parameters on 4.2.0.beta1, raises error on master

### ISSUE THREAD

**Issue by seanwalbran** [rails/rails#16959]
Trying execute a query with an 'exists' subquery breaks on 4.2.0.beta1 and master in different ways, both having to do with binding parameters:

Standalone repro gists here:
- master: undefined method 'first' for nil:NilClass: https://gist.github.com/seanwalbran/d1a99a8b83ed528a6737
- 4.2.0.beta1: unbound parameter: https://gist.github.com/seanwalbran/fa4497016cbf498b4734
- 4.1.6: works: https://gist.github.com/seanwalbran/6ff642b03d4e1bf291d8

**Comment by stiff** [comment]
I tried the `where.exists` proposed by @chancancode and it works great, waiting to see it in mainline. I can put it into PR if it would help :)

**Comment by aaronchi** [comment]
+1 for this

**Comment by sockmonk** [comment]
+1 for implementing where.exists as proposed.

**Comment by svoop** [comment]
+1 – EXISTS is often the faster choice than IN

**Comment by ClayShentrup** [comment]
+1

**Comment by ryanswood** [comment]
+1 I have a query that closely mimics @chancancode example and it now blows up. :( Being able to use `where.exists` would be very helpful!

[Code example](https://gist.github.com/ryanswood/7342b58552741fc126ed) if interested.

**Comment by Dantemss** [comment]
Seems fixed in Rails 5. A query like `Record.where.not(OtherRecord.where('"id" = "records"."other_record_id"').exists)` produces `SELECT "records".* FROM "records" WHERE (NOT (EXISTS (SELECT "other_records".* FROM "other_records" WHERE ("id" = "records"."other_record_id"))))`

**Comment by kamipo** [comment]
It works on master.

**Comment by travisp** [comment]
@kamipo Can you help clarify which version of Rails that was (i.e. where rails users can expect this to begin working)?
