### ISSUE TITLE
ActiveJob should have an explicit app-specific base class a la ApplicationController

### ISSUE THREAD

**Issue by tamird** [rails/rails#16976]
Title's a mouthful, but having an explicit base class (and documentation that indicates how the queue adapter can be changed on it) will be hugely useful for users that wish to implement multiple job hierarchies. For instance, I may want my mail delivery jobs to have different durability semantics than my log processing jobs (which can be in-memory and best-effort).

/cc @strzalek @dhh

**Comment by jvanbaarsen** [comment]
@tamird Does this mean that when you create your first Job you get a `jobs/application_job.rb` file? And that when you generate a job you will extend from that file? That does mean that the `application_job.rb` file will be empty at the start correct? If this is the idea I would really like to work on this :)

**Comment by tamird** [comment]
@jvanbaarsen yes

**Comment by jvanbaarsen** [comment]
@tamird Would you be interested to help me out when I get stuck? (Dont really have much experience with the rails core codebase, and really want to get involved)

**Comment by cristianbica** [comment]
so @dhh are you satisfied with the example above?

**Comment by dhh** [comment]
Yup. Let's roll with ApplicationJob.
