### ISSUE TITLE
Rails/Arel union query with mysql2 driver fails but works with sqlite3

### ISSUE THREAD

**Issue by maletor** [rails/rails#16978]
I have produced a Gist that proves what I am talking about. The failing line is within Rails, but I believe the actual bug may be in the mysql2 driver. That being said, I'm not completely sure who's responsibility this bug is so I have also posted [the same bug](https://github.com/brianmario/mysql2/issues/546) on mysql2.

https://gist.github.com/maletor/af1aae5086ba10ed7cad

This is the failing line where we have a block trying to call `reverse` on `nil`: https://github.com/rails/rails/blob/v4.1.5/activerecord/lib/active_record/connection_adapters/abstract/database_statements.rb#L14

**Comment by matthewd** [comment]
I'm closing this as a dup of the (later, notabug) https://github.com/rails/rails/issues/18379#issuecomment-69448530
