### ISSUE TITLE
SQLite3 true/false 't'/'f' isn't useful, should be 0/1.

### ISSUE THREAD

**Issue by ioquatix** [rails/rails#17062]
ActiveRecord uses 't' and 'f' constants when talking to SQLite columns for true and false, but it would probably be better if it used 1 and 0.

Sample data:

```
select * from poicat;
_id|major|poi__id|cat__id
1|t|1|1
```

Example of poor incorrect results:

```
sqlite> update poicat set major = 'f';
sqlite> select * from poicat where major;
sqlite> select * from poicat where NOT major;
_id|major|poi__id|cat__id
1|f|1|1
sqlite> update poicat set major = 't';
sqlite> select * from poicat where major;
sqlite> select * from poicat where NOT major;
_id|major|poi__id|cat__id
1|t|1|1
```

Correct results using 0/1:

```
sqlite> update poicat set major = 0;
sqlite> select * from poicat where major;
sqlite> select * from poicat where NOT major;
_id|major|poi__id|cat__id
1|0|1|1
sqlite> update poicat set major = 1;
sqlite> select * from poicat where major;
_id|major|poi__id|cat__id
1|1|1|1
sqlite> select * from poicat where NOT major;
```

Internally, SQLite prefers 0 and 1, e.g.:

```
sqlite> update poicat set major = 't';
sqlite> update poicat set major = NOT major;
sqlite> select * from poicat;
_id|major|poi__id|cat__id
1|1|1|1
sqlite> update poicat set major = NOT major;
sqlite> select * from poicat;
_id|major|poi__id|cat__id
1|0|1|1
```

From the above example, we can see that `NOT 't'` is `1` which is clearly illogical if we consider 't' and 'f' to be true and false constants.

**Comment by ioquatix** [comment]
This is still an issue.

**Comment by rafaelfranca** [comment]
This is more a feature request than an issue so I'm closing it since we don't get feature requests on the issue tracker. Thanks.

**Comment by ioquatix** [comment]
I don't think this is a feature request, but a bug because the behaviour is broken relative to existing functionality in the database. But, whatever.

**Comment by mikecmpbll** [comment]
Am I right in thinking that if you have boolean column with sqlite, you cannot do Foo.where(boolean_column: true) with this implementation if the values are stored in sqlite as 0 and 1?

If this is the case then _surely_ this is a bug, not a feature request, especially given the first line of SQLite's documentation on booleans outlines how boolean values ought to be stored: https://www.sqlite.org/datatype3.html#boolean

**Comment by ioquatix** [comment]
@mikecmpbll Yes that is correct. IMHO this is a bug.

**Comment by ioquatix** [comment]
Can we please re-open this issue?

http://stackoverflow.com/questions/21066345/regression-in-activerecord-4-sqlite3-boolean-query-support

The way ActiveRecord works is contrary to what Sqlite3 states here: http://www.sqlite.org/datatype3.html#boolean

This also means that boolean logic doesn't work correctly.

**Comment by rafaelfranca** [comment]
Reopening will not fix it. SQLite3 is not priority for us. The issue was closed because it was stale so I recommend you to try to fix

**Comment by rafaelfranca** [comment]
by for us I really mean me, of course it is a priority for Rails but since we had no response in the ticket and it was closed as stale having someone that care about it trying to fix is the best action we can take here.

**Comment by ioquatix** [comment]
Okay I will supply a PR. I was under the impression that this was still not even considered a bug based on your the last response. But, clearly it's a bug.

**Comment by rafaelfranca** [comment]
👍 Thanks!

**Comment by ioquatix** [comment]
Okay, I've submitted a PR. I'd suggest this would be a good candidate for Rails 5.0 but that window may have passed already.

**Comment by ioquatix** [comment]
Can you please re-open this issue and acknowledge it is a bug? Thanks.

**Comment by rafaelfranca** [comment]
Of course. Thank you so much.

**Comment by ioquatix** [comment]
@rafaelfranca Thanks dude I appreciate it.

**Comment by ioquatix** [comment]
Bump.
