### ISSUE TITLE
Rails 3/4 regression: Duplicating a has_many association collection on a new AR record resets the association

### ISSUE THREAD

**Issue by BRMatt** [rails/rails#17117]
All of the following was done on `ruby 2.0.0-p576`

In Rails 3.2.19 I could call `#dup` on a new record's association, and be able to work on it independently from the collection associated with the record.

In Rails 4.1.6 calling `#dup` on a new record's association **empties, and mutates the record's collection**, and returns the empty collection. `#dup` should really product a copy of the collection, and should definitely not mutate the original collection.

See this gist for an example of behaviour in both versions: https://gist.github.com/BRMatt/ded04736f285d7cd04b3

It seems that in 3.2 the collection was an array:

```
[1] pry(#<BugTest>)> post.comments.method(:dup)
=> #<Method: Array(Kernel)#dup>
```

And in 4.1 that changed to `ActiveRecord::Associations::CollectionProxy`, which is a subclass of `ActiveRecord::Relation`:

```
[2] pry(#<BugTest>)> post.comments.method(:dup)
=> #<Method: Comment::ActiveRecord_Associations_CollectionProxy(Kernel)#dup>
```

It seems that the problem is rooted in [`ActiveRecord::Relation#initialize_copy`](https://github.com/rails/rails/blob/v4.1.6/activerecord/lib/active_record/relation.rb#L31-L37), which calls  [`ActiveRecord::Associations::CollectionProxy#reset`](https://github.com/rails/rails/blob/v4.1.6/activerecord/lib/active_record/associations/collection_proxy.rb#L1028-L1032). This in turn calls `#reset` on `#association_proxy` which is handled by [`ActiveRecord::Associations::CollectionAssociation#reset`](https://github.com/rails/rails/blob/v4.1.6/activerecord/lib/active_record/associations/collection_association.rb#L64-L67).

It's at this point that `@target` is reset to `[]`. Now in theory changing `@target` shouldn't affect the original collection proxy, as we're "within" a dup of the proxy, not the proxy itself. However, it seems that the original association and its dup share the same `#object_id`:

``` ruby
From: /home/vagrant/.gem/ruby/2.0.0/gems/activerecord-4.1.6/lib/active_record/associations/collection_association.rb @ line 65 ActiveRecord::Associations::CollectionAssociation#reset:

    64: def reset
 => 65:   super
    66:   @target = []
    67: end

[34] pry(#<ActiveRecord::Associations::HasManyAssociation>)> self.owner.association(:comments).object_id == self.object_id
=> true
[35] pry(#<ActiveRecord::Associations::HasManyAssociation>)> self.owner.association(:comments).reader.object_id == self.reader.object_id
=> true
```

I'm not entirely sure why this is the case, hopefully someone else can shed some light on the situation.

In the meantime the only solution I've found is to call `#to_a` on the collection, which duplicates `#target` in the `CollectionProxy`.

**Comment by jvanbaarsen** [comment]
@rafaelfranca I think this needs the label "With Reproduction steps" correct?

**Comment by rafaelfranca** [comment]
@jvanbaarsen correct! Thanks :smile:

**Comment by jbhatab** [comment]
I have come across this too.

I did order.order_items << negotiation_round.order_items.dup and it completely took all of them away from negotiation_items. If I do them individually then it works fine.

I'm on rails 5.0beta3. I've attached pictures showing what happens.

Basically I make a new order. I then try and duplicate the order_items from my negotiation to my order and it just moves them over.

```
o = Order.new
negotiation = Negotiation.last
o.order_items << negotiation.order_items.dup
o.save
```

After this negotiation has no order items and order takes them with their original ids.

I attached some pics.

![screen shot 2016-04-14 at 8 30 58 am](https://cloud.githubusercontent.com/assets/2458718/14529880/22d465c0-021c-11e6-82e5-6b195b58cd34.png)
![screen shot 2016-04-14 at 8 32 14 am](https://cloud.githubusercontent.com/assets/2458718/14529881/22d7a302-021c-11e6-9909-aea8e6095185.png)
![screen shot 2016-04-14 at 8 32 44 am](https://cloud.githubusercontent.com/assets/2458718/14529882/22dd3d4e-021c-11e6-8d0d-39315806cd4b.png)

**Comment by eileencodes** [comment]
Fixed in master and backported to 5-0-stable in 2194029

**Comment by eileencodes** [comment]
I had to revert this because I incorrectly changed the behavior of dup. After talking with Aaron about this it seems that this is technically correct behavior for `dup` - that calling dup on a collection proxy should re-initialize a CollectionProxy. The correct call should be `clone` but it might not be working correctly (which I am testing and will open a new issue for if I determine it is not behaving correctly).
