### ISSUE TITLE
ActiveModel::AcceptanceValidator initialize causes an error because the overridden hash is not HashWithIndifferentAccess

### ISSUE THREAD

**Issue by mikkelwf** [rails/rails#17115]
I've noticed that the AcceptanceValidator throws this error if initialized with the `validates` method

````ruby
ArgumentError: :attributes cannot be blank
````

After doing some research i found that the `initialize`method in `acceptance.rb` overrides the `EachValidator` initializer. But the options hash from the overridden method is not of type HashWithIndifferentAccess, only a normal hash.

This sometimes causes the `@attributes` to be empty, because the 
```ruby
@attributes = Array(options.delete(:attributes))
```` 
fails to extract the attributes from options.

Rails 4.1.1

**Comment by vipulnsward** [comment]
@mikkelwf I don't see how this should cause an issue. Both hash and hwia would have the same behaviour for our case.
Can you show a way to reproduce this?
