### ISSUE TITLE
Single table inheritance does not cast new instances to default type on initialize

### ISSUE THREAD

**Issue by montanalow** [rails/rails#17121]
Foo.new should be consistent, prefereably by returning a Bar in both cases, never a Foo. 

```ruby
class Foo < ActiveRecord::Base
# add_column :foos, :type, :text, default: 'Bar'
end

class Bar < Foo
end

Foo.new #=> #<Foo id:nil, type: 'Bar'>
Foo.new(type: 'Bar') #=> #<Bar id:nil, type: 'Bar'>
```

Notice `type: 'Bar'` is properly set from the database default on Foo.new(), but it's *not* used to type cast the value, and when new(type:'Bar') is passed as a param, it *is* used to type cast the value.

**Comment by senny** [comment]
A patch has been applied on `master`. This will be fixed in Rails 5. I won't backport to `4-2-stable`.

@montanalow thank you for reporting :yellow_heart:

**Comment by montanalow** [comment]
Wahoo, thanks for fixing :+1:

**Comment by bluehallu** [comment]
Can still reproduce as of Rails 5 beta 3

**Comment by senny** [comment]
@bluehallu can you write an executable test-case to reproduce the issue? You can use [this script](https://github.com/rails/rails/blob/master/guides/bug_report_templates/active_record_master.rb) as a starting point.
