### ISSUE TITLE
Removing objects from has_many collection doesn't update updated_at filed.

### ISSUE THREAD

**Issue by mbie** [rails/rails#17161]
I've recently noticed that whenever I want to remove object from association value for `updated_at` column doesn't change at all.

Here is sample code:
```ruby
gem 'activerecord', '4.1.6'
require 'active_record'
require 'minitest/autorun'
require 'logger'

Minitest::Test = MiniTest::Unit::TestCase unless defined?(Minitest::Test)

ActiveRecord::Base.establish_connection(adapter: 'sqlite3', database: ':memory:')
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :posts do |t|
    t.timestamps
  end

  create_table :comments do |t|
    t.integer :post_id
    t.timestamps
  end
end

class Post < ActiveRecord::Base
  has_many :comments
end

class Comment < ActiveRecord::Base
  belongs_to :post
end

class BugTest < Minitest::Test
  def test_association_stuff
    post = Post.create!
    comment = Comment.create!
    post.comments << comment
    updated_at = comment.updated_at
    post.comments.clear
    # post.comment_ids = []
    # post.comments.delete(comment)
    comment.reload
    assert_nil comment.post
    refute_equal updated_at.to_i, comment.updated_at.to_i
  end
end

```

According to logs adding new object to collection sets foreign key and updates `updated_at` column.
```sql
UPDATE "comments" SET "post_id" = ?, "updated_at" = ? WHERE "comments"."id" = 1  [["post_id", 1], ["updated_at", "2014-10-03 10:33:51.888594"]]
```

However, removing object from collection only nullifies foreign key
```sql
UPDATE "comments" SET "post_id" = NULL WHERE "comments"."post_id" = ?  [["post_id", 1]]
```

IMHO adding and removing operations should behave the same and they both should change `updated_at` field (so cached object could be invalidated properly).

**Comment by Sxl1092** [comment]
If I understand what's being spoken of correctly, none of has_and_belongs_to_many, has_one, and has_many modify the associated object's updated_at. If this is indeed the case then I am not sure that this behavior is expected. Is this the case? Do you feel like this is behavior that should be expected and if so, why? I am just trying to understand the situation fully because if this behavior is expected maybe it should be expected across the board? I would like to try to tackle the issue if that is indeed the case. Thanks for the specs by the way.

**Comment by rafaelfranca** [comment]
Yeah this is expected behavior. When you call `clear` you are just calling `delete_all` that does the query straight in the database, this doesn't change the `updated_at` column.

Mind do open a pull request updating the documentation?

**Comment by mbie** [comment]
@rafaelfranca so my question is why `delete_all` does not change `updated_at` column in such case? When you remove an object from an association the object **is changed** (foreign key is nullified). However, `updated_at` field stays **untouched**. It's quite unexpected for me. Moreover it is inconsistent with the opposite action of adding an object to an association (which sets both foreign key and `updated_at` column)

**Comment by rafaelfranca** [comment]
`delete_all` don't change `updated_at` because it doesn't change the object, just the data in the straight in the database.

**Comment by frankyston** [comment]
what's the point of making a update_at it is being made a delete_all? As @rafaelfranca said, delete_all does not change the update_at, for me it does not make sense.
