### ISSUE TITLE
eager_load on a scoped has_one association can trigger n queries

### ISSUE THREAD

**Issue by agios** [rails/rails#17166]
For any row where the association is empty, when the eager loaded association is accessed, another unnecessary query is triggered, trying again to fetch a result. 

Test case: https://gist.github.com/agios/9fffc2cdaf7630f4eb68

If the association is changed to has_many and used in combination with .first then it works fine, however it becomes less intuitive.

**Comment by kurko** [comment]
I have exactly the same issue in my app. That PR would solve this issue for me.

**Comment by agios** [comment]
@kurko Just noticed that #18312 was a duplicate of this, but was recently fixed
