### ISSUE TITLE
ActiveJob places jobs in "default" queue, but Que expects no queue name by default

### ISSUE THREAD

**Issue by bgentry** [rails/rails#17195]
Took me awhile to figure out why my Que jobs weren't running in anything other than `:sync` mode.

Turns out that Que workers, by default, [expect jobs to be queued with no queue name](https://github.com/chanks/que/blob/c1f32f63cdbf037da45f9f9c32412e22964b1cbd/lib/que/worker.rb#L13). ActiveJob enqueues jobs into the `default` queue out-of-the-box. This means that Que's `:async` (background threads) or `:off` (separate process) workers will repeatedly log messages that jobs weren't available for processing (`job_unavailable`) even though they're actually queued in the `default` queue.

Setting `QUE_QUEUE=default` on my webserver and/or background workers was required in order to make these jobs get processed.

At the very least, it seems like this could use some documentation. Ideally we would set `ENV['QUE_QUEUE'] ||= "default"` so this adapter just works out-of-the-box.

**Comment by jvanbaarsen** [comment]
@cristianbica Since empty queue names are now supported, I think this issue can be closed, right?
