### ISSUE TITLE
Caching of default_url_options causing weird behaviour

### ISSUE THREAD

**Issue by victorarias** [rails/rails#17210]
We found a bug in one of our systems that was caused by the way the route helpers caches the `default_url_options` method. Consider the code below:

    def default_url_options(options={})
        { locale: I18n.locale }
    end

This works fine almost all the time, but in a specific request we did this:

    I18n.with_locale(some_other_locale_different_than_the_current_one) do
        # do something with a url helper, like:
        root_path
    end

When the code above was executed before any other code that called a route helper, every subsequent url generated by helpers were created with the locale used within the `with_locale` call instead of the expected `I18n.locale`.

I wrote the following gist to reproduce the issue: https://gist.github.com/victorarias/539afc9875d67cd03209

I tested this in Rails 3.2.19 only, so I don't know if the same applies to Rails 4.

**Comment by pixeltrix** [comment]
Have to agree with @thedarkone here - regenerating the default options every time a route is generated would be a significant performance hit and isn't the typical use case. Maybe a note added to the guide would appropriate saying that the default options are cached.

**Comment by fxn** [comment]
I have documented that [the returned hash is cached per request](https://github.com/rails/rails/commit/c865b8298f12e898430496d4b3f719ee20172765) and added a [warning about the generation of locale selectors in the i18n guide](https://github.com/rails/rails/commit/7789dfe779c8588fe4e8078077bdf07d436db3e5).

I guess we can close this issue now.
