### ISSUE TITLE
Render layout blocks don't work with collections

### ISSUE THREAD

**Issue by calebanderson** [rails/rails#17224]
The documented way of rendering an array of objects and using a block for yield fails.

`<%# app/views/users/_user.html.erb &>`
`<div class="user">`
`Budget: $<%= user.budget %>`
`<%= yield user %>`
`</div>`

`<%# app/views/users/index.html.erb &>`
`<%= render layout: @users do |user| %>`
`Title: <%= user.title %>`
`<% end %>`

Error:
ActionView::MissingTemplate - Missing partial search/[#<Resource id: 1, cfc_resource_id: 12345, name: ...

It does work if given a single object to render

**Comment by dungdm93** [comment]
I'm using ```rails 4.2.0``` and also get the same problem:
```ruby
<%= render layout: @books do |book| %>
```
Error: ```Missing partial books/[#<Book id: 1, isbn:....```
and other tries:
````ruby
<%= render layout: 'book', book: @books do |book| %>
<%= render layout: 'book', collection: @books, as: book do |book| %>
<%= render layout: 'book', locals: {collection: @books, as: book} do |book| %>
```
Error: ```undefined local variable or method 'book' for #<#<Class:0x007fe6aab386f0>:0x00000008c0c6e8>```
```ruby
<%= render layout: 'book', locals: {book: @books} do |book| %>
<%= render layout: 'book', object: @books do |book| %>
```
Error: ```undefined method `title' for #<Array:0x007fe6aa1326b0>```
```ruby
<%= render layout: 'book', collection: @books do |book| %>
```
Error: ```no block given (yield)```
and my ```_book.html.erb```
```erb
Title: <%= book.title %>
<%= yield  %>
```

**Comment by ch1na-d0ll** [comment]
I'm having the same problem.

Using `rails 4.2.1` with this `movies/_movie.html.haml` view
```
= content_tag_for :div, movie do
  = yield movie
```

The following `movies/index.html.haml` __does NOT work__ as documentation say
```
= render layout: @movies do |mov|
  = mov.title
```

It raised the following error

    Missing partial movies/_#<Movie::ActiveRecord_Relation:0x007fdf31a1b720>

However, the following `movies/index.html.haml` __does work__
```
- @movies.each do |movie|
  = render layout: movie do |mov|
    = mov.title
```

**Comment by myidisnotthis** [comment]
Using `Rails 5.1.2`, still have **no blocks given** error if with collections

`<%= render  @users do |user| %>` will have **no blocks given**

but for single object:

`<%= render  @user do |user| %>` **will work**

index.html.erb:
```erb
<%= render  @users do |user| %>
    Title contains: <%= user.title %>
<% end %>
```

_user.html.erb:
```erb
<div class="user">
  Budget: $ <%= user.budget %>
</div>
```

**Comment by guilleiguaran** [comment]
See #42617
