### ISSUE TITLE
queries with ActiveSupport::TimeZone have extra fractional time

### ISSUE THREAD

**Issue by alfredr** [rails/rails#17239]
Hi,

I'm not exactly sure where the issue lies, but something with serializing ActiveSupport::TimeZone objects to queries seems to result in additional fractional time being included in the query text. At the very least this breaks delayed_job_active_record running against a mysql2 backend on 4.2.0.beta2

When taking locks in delayed_job with a mysql/active record backend, the following code is executed
 ```ruby
    when "MySQL", "Mysql2"
     count = ready_scope.limit(1).update_all(locked_at: now, locked_by: worker.name)
     return nil if count == 0
     where(locked_at: now, locked_by: worker.name, failed_at: nil).first
```

the locked_at time is being set with a query resembling

    UPDATE `delayed_jobs` SET `delayed_jobs`.`locked_at` = '2014-10-12 07:23:07.418156' ...

But the 'locked_at' column lacks the precision for the extra fractional seconds and the value is stored rounded.

Immediately after taking the lock, dj attempts to select the record it has just locked, when it does it specifies locked_at = '2014-10-12 07:23:07.418156' in the where-clause, but this query isn't rounded by mysql on input. As a result, mysql does not match it against what was stored, effectively preventing delayed job from finding the record it just locked.

( cf. lines 70-72 of delayed_job_active_record's [backend/active_record.rb](https://github.com/collectiveidea/delayed_job_active_record/blob/04b8451069d348f37195a9e8b1965e8da45da292/lib/delayed/backend/active_record.rb#L70) )

**Comment by mvladimirovic** [comment]
I can confirm this bug and that it is fixed in '4-2-stable' by https://github.com/rails/rails/pull/14359

**Comment by sgrif** [comment]
Thank you
