### ISSUE TITLE
rake db:structure:dump doesn't work well for PostgreSQL with schema_search_path and extensions

### ISSUE THREAD

**Issue by rywall** [rails/rails#17261]
If the user has specified a schema_search_path and also has extensions, the resulting pg_dump call generated by rake db:structure:dump includes the --schema flag which means that no CREATE EXTENSION statements will be created in the resulting structure.sql. According to the pg_dump documentation:

> When --schema is specified, pg_dump makes no attempt to dump any other database objects that the selected schema(s) might depend upon. Therefore, there is no guarantee that the results of a specific-schema dump can be successfully restored by themselves into a clean database.

This will most likely cause any attempts to load this file to fail.

I'm not sure what the best solution is in this case... In my opinion, it would be better to disregard the schema_search_path and dump the structure of all schemas rather than create invalid SQL dumps. 

Thoughts?

**Comment by senny** [comment]
@rywall  this looks a lot like #17157.

**Comment by rywall** [comment]
This is the same issue as #17151. I'm surprised I didn't find it in my search before posting. He beat me by 10 days :). At least I'm not the only one with this issue!

Closing in favour of #17157.

**Comment by senny** [comment]
@rywall thank you for reporting :yellow_heart:
