### ISSUE TITLE
no backtrace appears in log when 500 error is shown in RAILS_ENV=production

### ISSUE THREAD

**Issue by Nowaker** [rails/rails#17354]
Start [virtkick-webapp](https://github.com/virtkick/virtkick-webapp) without `db:migrate` first. The 500 page will appear with no exception in the console at all. It turned out to be a database problem after I changed to `config.consider_all_requests_local = true` so I can identify the problem in my browser. The backtrace should appear in the console output I believe.

Start with: `SECRET_KEY_BASE=x DEVISE_SECRET_KEY=x RAILS_ENV=production bundle exec rails s`

I work on Rails master branch (4.2), so I'm up to date.

**Comment by justincase** [comment]
Perhaps a silly question but did you check the production log file? By default `RAILS_ENV=production` writes to `log/production.log`. Setting `config.logger = Logger.new(STDOUT)` in `production.rb` will make Rails log to the console.

**Comment by abitdodgy** [comment]
I have the very same problem here.

**Comment by rafaelfranca** [comment]
I just did it and got the error in the console. Closing.

**Comment by abitdodgy** [comment]
Just of note if anyone lands on this page again, This happens with Ruby 2.2.0-preview1. Using 2.2.0 will not produce this problem. In my case they stack trace was available in the console, but the browser served the `public/500.html` production error page.
