### ISSUE TITLE
Live streaming thread safety issue

### ISSUE THREAD

**Issue by foeken** [rails/rails#17428]
We have been getting intermittent errors in our production environment:

```
ERROR -- : Mysql2::Error: This connection is in use by: #<Thread:0x00000004c50838 sleep>
```

Eventually we end up with a worker (Passenger) that is completely stuck. The worker seems to be caught in a endless mutex lock inside the ActiveRecord connection pool. One thread is stuck in an endless `ping` action inside the mysql2 adapter and another is waiting for the lock to check if the database pool is connected.

We traced back the cause to a database connection that was checked back into the pool but was still used by a thread inside a streaming request. When we disabled streaming for a while, we found the issue disappeared. 

Looking deeper, I believe the following code is to blame:

```ruby
# Since we're processing the view in a different thread, copy the
# thread locals from the main thread to the child thread. :'(
locals.each { |k,v| t2[k] = v }
```
> Source: https://github.com/rails/rails/blob/master/actionpack/lib/action_controller/metal/live.rb#L275

Inside the live controller all local thread variables are copied including the `ActiveRecord::RuntimeRegistry`. The request thread finishes at some point checking the database connection back in, but the thread that actually performs the action code is still running (streaming) and somehow using the connection (from the registry?). The Passenger worker moves on to the next request and checks the connection back out, when it tries to use it: `Mysql2::Error: This connection is in use by: XXX`.

I want to set up a small test case app that demonstrates the case in code but for now I wanted to get it out here so other people know this might happen.

There are a few possible solutions that spring to mind:

 1. **Do not copy the registry and use an explicit `with_connection`**: This would solve the active_record concurrency issue, but the core problem remains with any other thread local variables that cannot be used simultaneously. 
 
 2. **Change `@_response.await_commit` into `@_response.await_stream`**: This would ensure the stream would finish before the next request is handled. This might be a good solution for some use cases but also removes a big advantage of streaming (the fact that the request can continue while new ones are picked up). So probably a no there.

I would love some more insight on how to proceed. I want to try and fix the issue myself, but I would need some guidance on which route to take.

**Comment by fake-or-dead** [comment]
I found out this problems too, thanks for explanation ;D
