### ISSUE TITLE
config.eager_load when set to true, my datetime attribute is not using ActiveSupport::TimeWithZone

### ISSUE THREAD

**Issue by tungwini** [rails/rails#17446]
I just pushed a Rails 4 application to a new production env and noticed the timestamp is showed with UTC zone. They have been shown correctly in all other environment with PST zone , the Application config.time_zone I set in application.rb. Further triaging the problem, I discovered that, in production env, the timestamp attributed is of Ruby class Time, not ActiveSupport::TimeWithZone

my_record.start_at.is_a?(ActiveSupport::TimeWithZone)
=>  false
But, in test env, the timestamp attributed is class ActiveSupport::TimeWithZone

my_record.start_at.is_a?(ActiveSupport::TimeWithZone)
=>  true
This is the same code base, and the vm was cloned from test, so the software versions are the same. 

The only difference is the production.rb setting. 
When I change config.eager_load from true to false -- the ActiveSupport timezone is working again.

The eager loading seemed to impact how ActiveSupport classes are loaded?

**Comment by senny** [comment]
@tungwini it's been a long time since we heard from you. I'm closing this issue out of inactivity. If you still experience this issue, please report back and provide the necessary information so we can help you debug the problem.

Thank you for your understanding.
