### ISSUE TITLE
ArgumentError: invalid byte sequence in UTF-8 after upgrading to 3.2.20

### ISSUE THREAD

**Issue by gingerlime** [rails/rails#17454]
We're trying to upgrade to rails 3.2.20 from 3.2.19 and one of our feature tests is now failing with an error coming from action_dispatch middleware when we send a malformed UTF-8 strings. Previously the path was passed down to our app, and we applied some sanitizing there. Now the exception is raised higher-up. Not sure if this is a bug or a feature, but certainly feels like a change in behaviour for us

```
ArgumentError: invalid byte sequence in UTF-8
from /root/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/actionpack-3.2.20/lib/action_dispatch/middleware/static.rb:51:in `split'
```

**Comment by senny** [comment]
@gingerlime is this still an issue? Looks like 307402f fixed it. (see #17595)

**Comment by gingerlime** [comment]
HI @senny - we upgraded to Rails 4.1 meanwhile, so I can't really say unfortunately... Sorry. Probably makes sense to close it?

**Comment by senny** [comment]
@gingerlime thank you for reporting back. Closing this issue.
