### ISSUE TITLE
Active Record Enum - Same values, different columns

### ISSUE THREAD

**Issue by dgsan** [rails/rails#17511]
It's currently not possible to have enums with the same values on different columns in the same model.

A crude example might be a `Book` with `author_visibility` and `illustrator_visibility` columns for which you'd like to use the same `public`/`private` values on both columns.

It'd require changing the current enum API some.
Probably you'd have to do `book.author_visibility.private!` rather than `book.private!`.

I feel like that kind of approach might be nicer as it could potentially allow enum reuse between models, too. Maybe syntax like:
```
enum VisibilityEnum :illustrator_visibility
```
where VisibilityEnum is an object with the enum mapping and the symbol is the column name.

Anyway, I'm probably going to work around the issue manually for the moment. (I have 3 columns with the same 12-value 'enum,' none can be `null`, and can't decompose since they're essentially treated as a 3-tupple coordinate.)

My use case may be atypical, too, but thought I'd bring it up.

**Comment by scarfacedeb** [comment]
@agis- Do you still plan to make this PR?  
I also need this feature, and I can prepare it for you, if you don't have time right now.

**Comment by agis-** [comment]
@scarfacedeb I plan to work on this the next week. Will report back soon.

**Comment by scarfacedeb** [comment]
@agis- OK, thanks!

**Comment by hgtesta** [comment]
+1 Just stumbled on this too. In my case the columns are safe_mailer and unsafe_mailer.

**Comment by salza80** [comment]
I'm also looking for this. Looking forward to this issue being resolved!

**Comment by alexbrahastoll** [comment]
:+1: I also came across a situation in which it would be great to have the prefix option.

**Comment by pascalbetz** [comment]
Stumbled on this as well.
What would be the expected interface, where would that ```prefix``` option go?
Currently ```enum``` takes a single hash where every key value pair defines one enum.

**Comment by darryn02** [comment]
+1

**Comment by dhh** [comment]
I think enum_prefix and enum_postfix are unique enough that they can just
be reserved, thus allowing us to stick with the one hash.

**Comment by pascalbetz** [comment]
I've come up with something. I'll have it reviewed first since it's my first PR.

**Comment by kaspth** [comment]
@pascalbetz sorry, @igas is already working on this. Check #19813.

**Comment by pascalbetz** [comment]
@kaspth / @igas: Sorry, only realized after i was done.

**Comment by gollawil** [comment]
+1

Just upgraded to rails 4 and would like to take advantage of the built-in Enum class, but I have models with multiple 'status' columns that have some overlapping values('success, 'error', etc). 

The custom Enum class we currently have defined works exactly as @dgsan is suggesting: 
instead of ``model.success?`` we use ``model.col1.success?`` and ``model.col2.success?``

Would like to see this added in.

**Comment by igas** [comment]
@gollawil take a look at #19813

**Comment by gollawil** [comment]
@igas looks like that is coming out with rails 5.

Guess I can add it in myself.
