### ISSUE TITLE
inflections are now case sensitive?

### ISSUE THREAD

**Issue by bigtunacan** [rails/rails#17546]
Just updated from Rails 4.1.1 to 4.1.7 and now inflections are not working properly.

An example here of using `inflect.irregular` previously.

```
    inflect.irregular 'ProtocolSpecies', 'ProtocolSpecies'
```

This would correctly inflect on something like follows.

```
animal_protocol.protocol_species
```

After updating to Rails 4.1.4 the above line will return an error that the class ActiveRecord::Animal::ProtocolSpecy is undefined instead of correctly inflecting to ActiveRecord::Animal::ProtocolSpecies.

This appears to be related to this commit https://github.com/rails/rails/commit/643409dcb04e7ac6a6c7b09edfb9606563e9aa21#diff-7981f69995a3750c52e68d1aa65d0c12 that went in not long after the Rails 4.1.1 release so Rails 4.1.2 and on appear to be affected.

The result for us appears to be that for each inflection I will need to specify it multiple times; is this the intended behavior?

**Comment by yoongkang** [comment]
Should we inflect both camel and snake case? I've opened a pull request although it really needs further feedback on it: #20123.

**Comment by lfalcao** [comment]
This issue shouldn't be closed? :thinking:

**Comment by zzak** [comment]
@lfalcao I believe so, based on this comment: https://github.com/rails/rails/pull/20123#issuecomment-124559689

I'm going to close this ticket, but feel free to re-open if I'm missing some context. :bow:
