### ISSUE TITLE
Special handling when options[:message] is a Proc in #normalize_message.

### ISSUE THREAD

**Issue by nengxu** [rails/rails#17547]
# Background

In our project, we are using the standard "validates_inclusion_of" ActiveRecord validation, but with custom error message which needs to be localized. For example:

    validates_inclusion_of :priority, :in => 1..999, :message => validate_inclusion_message('1-999')

In order to dynamically localize the error message at run time, a Proc is provided as the :message parameter:

    def self.validate_inclusion_message(range)
      lambda {|| I18n.t(:range_error, default: "Valid Range %{range}", range: range)}
    end

However, I18n will raise an error "wrong number of arguments (2 for 0)", with the trace back:

     ArgumentError - wrong number of arguments (2 for 0):
      i18n (0.6.9) lib/i18n/backend/base.rb:122:in `block in resolve'
      i18n (0.6.9) lib/i18n/backend/base.rb:116:in `resolve'
      i18n (0.6.9) lib/i18n/backend/base.rb:103:in `block in default'
      i18n (0.6.9) lib/i18n/backend/base.rb:102:in `default'
      i18n (0.6.9) lib/i18n/backend/base.rb:34:in `translate'
      i18n (0.6.9) lib/i18n.rb:157:in `block in translate'
      i18n (0.6.9) lib/i18n.rb:153:in `translate'
      activemodel (4.0.3) lib/active_model/errors.rb:435:in `generate_message'
      activemodel (4.0.3) lib/active_model/errors.rb:444:in `normalize_message'
      activemodel (4.0.3) lib/active_model/errors.rb:293:in `add'
      activemodel (4.0.3) lib/active_model/validations/inclusion.rb:11:in `validate_each'
      activemodel (4.0.3) lib/active_model/validator.rb:153:in `block in validate'
      activemodel (4.0.3) lib/active_model/validator.rb:150:in `validate'

After investigation, I found that the error is caused by ActiveModel::Validations::InclusionValidator

    module ActiveModel

      module Validations
        class InclusionValidator < EachValidator # :nodoc:
          include Clusivity

          def validate_each(record, attribute, value)
            unless include?(record, value)
              record.errors.add(attribute, :inclusion, options.except(:in, :within).merge!(:value => value))
            end
          end
        end

Although we had passed a custom :message option, the default ":inclusion" was still passed to errors.add as the :message parameter, as in active_model/errors.rb:

    def add(attribute, message = nil, options = {})
      message = normalize_message(attribute, message, options)
      if exception = options[:strict]
        exception = ActiveModel::StrictValidationFailed if exception == true
        raise exception, full_message(attribute, message)
      end

      self[attribute] << message
    end

Hence when in #normalize_message, the path of generate_message was chosen:

    def normalize_message(attribute, message, options)
      message ||= :invalid

      case message
      when Symbol
        generate_message(attribute, message, options.except(*CALLBACKS_OPTIONS))
      when Proc
        message.call
      else
        message
      end
    end

Then in #generate_message, 

    def generate_message(attribute, type = :invalid, options = {})
      type = options.delete(:message) if options[:message].is_a?(Symbol)

      if @base.class.respond_to?(:i18n_scope)
        defaults = @base.class.lookup_ancestors.map do |klass|
          [ :"#{@base.class.i18n_scope}.errors.models.#{klass.model_name.i18n_key}.attributes.#{attribute}.#{type}",
            :"#{@base.class.i18n_scope}.errors.models.#{klass.model_name.i18n_key}.#{type}" ]
        end
      else
        defaults = []
      end

      defaults << options.delete(:message)
      defaults << :"#{@base.class.i18n_scope}.errors.messages.#{type}" if @base.class.respond_to?(:i18n_scope)
      defaults << :"errors.attributes.#{attribute}.#{type}"
      defaults << :"errors.messages.#{type}"

      defaults.compact!
      defaults.flatten!

      key = defaults.shift
      value = (attribute != :base ? @base.send(:read_attribute_for_validation, attribute) : nil)

      options = {
        :default => defaults,
        :model => @base.class.model_name.human,
        :attribute => @base.class.human_attribute_name(attribute),
        :value => value
      }.merge!(options)

      I18n.translate(key, options)
    end

Our Proc was passed in as an element of the :default parameter to I18n.translate, by this line of code:

      defaults << options.delete(:message)

So in lib/i18n/backend/base.rb:122, I18n raised the error when it was processing our Proc as one element of :default

              resolve(locale, object, subject.call(date_or_time, options))

Where "subject" is our Proc, which by chance takes no parameter. Hence the 2 for 0 error.

# Analysis (updated: please see comments below)

In our case, the error was detected by the chance that our Proc takes no parameter. However, the behavior of ActiveModel::Validations::InclusionValidator in the following line is not reasonable, when a custom message has been specified:

              record.errors.add(attribute, :inclusion, options.except(:in, :within).merge!(:value => value))

No matter whether we specify a normal string, or a Proc as the custom message in the form of the :message option, this custom message should be passed to errors.add as the :message parameter. Not the default :inclusion. In other words, the code should be changed to:

          # check custom message
          if options[:message]
            record.errors.add(attribute, options[:message], options.except(:in, :within, :message).merge!(:value => value))
          else
            record.errors.add(attribute, :inclusion, options.except(:in, :within).merge!(:value => value))
          end

Then as in our case of a Proc passed in as the :message option, the right path would be chosen in #normalize_message:

      when Proc
        message.call

When a symbol is passed in as the :message option, it will go through the #generate_message route correctly.

When a string is passed in as the :message option, it will go through the other route correctly.

      else
        message

So in all scenarios, the custom message will be used correctly.

# Solution

I will submit a Pull Request for the fix soon.

**Comment by morgoth** [comment]
@nengxu To fix your issue, all you need to do is change proc, to take arguments:
```
validates_inclusion_of :priority, :in => 1..999, :message => ->(*) { I18n.t(:range_error, default: "Valid Range %{range}", range: "1-999") }
```

**Comment by nengxu** [comment]
@morgoth Your suggested way can work. However, it forces a developer to know the implementation details of a gem (I18n in this case). The purpose of the proc is to generate a custom dynamic error message. It is count-intuitive to use this "accept unknown number of arguments" when none of such argument is expected or required for generating the custom message.

**Comment by rafaelfranca** [comment]
This is how ruby works. If you don't want to think which arguments you lambda will receive don't use lambdas, use a proc instead. Lambdas check the arguments length, procs, doesn't.
