### ISSUE TITLE
ActionMailer adds recipient to command line for sendmail

### ISSUE THREAD

**Issue by villi** [rails/rails#1755]
I have been debugging a situation where all emails sent through ActionMailer get duplicated.  

By using a sendmail wrapper, I found that the command issued by ActionMailer added the recipient to the command line as well as the message headers.

In my case it looked similar to:
<pre>
/usr/sbin/sendmail -i -t -f sender@example.com recipient@example.com
</pre>
The sendmail command on this server (from qmail) seems to add the recipients on the command line to those read from the email headers and delivers the message twice.

The ActionMailer documentation http://api.rubyonrails.org/classes/ActionMailer/Base.html  specifies:
<pre>
# sendmail_settings - Allows you to override options for the :sendmail delivery method.

    * :location - The location of the sendmail executable. Defaults to /usr/sbin/sendmail.
    * :arguments - The command line arguments. Defaults to -i -t with -f sender@addres added automatically before the message is sent.
</pre>
If the sendmail command would be generated as documented, this problem would go away.

When searching for solutions on the web, I also found that this seems to cause problems with Postfix  as well (see http://stackoverflow.com/questions/6085723/sendmail-setting-for-hostingrails )

I observed this on 3.0.7 and reproduced with 3.0.9.

**Comment by chewi** [comment]
This should be reopened. The issue was fixed in mikel/mail#70 but Rails overrides the fix with it's own arguments, including -t.

**Comment by shane-axiom** [comment]
Yes, please reopen, this still needs to be fixed.

**Comment by arktisklada** [comment]
I'm happy to work on a fix to this
