### ISSUE TITLE
ActionMailer default content_type has no effect

### ISSUE THREAD

**Issue by cezarykluczynski** [rails/rails#17560]
I cannot get to work the default content_type for ActionMailer.

I tried setting it in both classes extending ActionMailer::Base (default content_type: "text/html") and in application.rb (ActionMailer::Base.default :content_type => "text/html"). There are no errors raised, there's just no effect on mail being sent, they are delivered with "text/plain" type.

content_type does work fine when passed into mail() method.

**Comment by aditya-kapoor** [comment]
@cezarykluczynski I think there is some confusion in the docs.
On my side, the following are not working.
```config.action_mailer.default = {from: "no-reply@example.org"}```
```config.action_mailer.default(from: "no-reply@example.org")```
The following is working,
```config.action_mailer.default_options = { content_type: "text/html" }```

@rafaelfranca Please try and see if there is something missing.

**Comment by cezarykluczynski** [comment]
As of Rails 4.1.8, both are working and no hacks are needed:

```ruby
config.action_mailer.default = { content_type: "text/html" }
config.action_mailer.default_options = { content_type: "text/html" }
```

It migth have been my misundertunding of ERB rather than a mailer error. Sorry and thanks for help.

**Comment by senny** [comment]
It looks like there is nothing left to do here. I'm going to close the issue.
