### ISSUE TITLE
Strange scoping behaviour when `first_or_initialize` takes a block.

### ISSUE THREAD

**Issue by jnicklas** [rails/rails#17577]
When calling `first_or_initialize` or `first_or_create` with a block, there's some really weird interaction with ActiveRecord scopes. I believe this is caused by the same problem as #7391, #7853 and #9894 all of which were closed as "expected behaviour". However in all three of these issues, the behaviour in question presented itself in Callbacks.

I believe the fact that this behaviour also presents itself in the block parameter opens this issue up for reconsideration.

An example of the problematic behaviour:

``` ruby
[1] pry(main)> Label.where(color: "foo").first_or_initialize { p Label.all }
  Label Load (0.5ms)  SELECT  "labels".* FROM "labels"  WHERE "labels"."color" = 'foo'  ORDER BY "labels"."id" ASC LIMIT 1
  Label Load (0.3ms)  SELECT "labels".* FROM "labels"  WHERE "labels"."color" = 'foo'
#<ActiveRecord::Relation []>
```

Look closely at the generated SQL. The call to `Label.all` within the block generates the following SQL:

``` sql
SELECT "labels".* FROM "labels"  WHERE "labels"."color" = 'foo'
```

It has clearly applied the scope that `first_or_initialize` was called on. IMO this is completely unexpected. It breaks all expectations of how Ruby code usually works. In our situation, the problem presented itself in an even evil-er way. We were calling `first_or_initialize` like this:

``` ruby
Label.where(color: "foo").first_or_initialize(&:pick_color)
```

And then:

``` ruby
class Label < ActiveRecord::Base
   belongs_to :account

   def pick_color
     labels  = account.labels 
     # ...
   end
end
```

Here we'd expect `account.labels` to return all labels of the account, but it doesn't! It finds only those labels which have `color = "foo"`, since the scope is (imo) erroneously applied.

We unit tested the `pick_color` method and verified that it worked as expected, only to find that it broke in a really surprising way when we called it through `find_or_initialize`. Again it seems very unexpected that the caller of the method could affect its behaviour in such a way.

Here's a Gist using the AR bug template: https://gist.github.com/jnicklas/7c7e27e6880cd8c40ecd

EDIT:

here's a workaround in case anyone else runs into this problem. Not exactly pretty :(

``` ruby
class Label < ActiveRecord::Base
   belongs_to :account

   def pick_color
     labels  = Label.unscoped.where(account_id: account_id)
     # ...
   end
end
```

**Comment by rafaelfranca** [comment]
@sgrif lets talk about how to fix this issue, it is one of things we should change at Rails 5
