### ISSUE TITLE
jsonb 'exists' operator synax conflicts with `.where` templates

### ISSUE THREAD

**Issue by tomeara** [rails/rails#17589]
The new Postgres operator for determining existence of a key/element a `jsonb` field uses `?`, which is the same as the templating syntax in the `.where` method in `ActiveRecord::QueryMethods`.

Should `?` be deprecated in favor of using `%s` in its place? Should the `?` operator just be escaped?

[Postgres documentation](http://www.postgresql.org/docs/9.4/static/functions-json.html#FUNCTIONS-JSONB-OP-TABLE)

**Comment by lfalcao** [comment]
This issue shouldn't be closed? 🤔 
- https://github.com/rails/rails/pull/19165#issuecomment-76742525
- https://github.com/rails/rails/pull/19165#issuecomment-88954223

**Comment by tomeara** [comment]
Yep! It's been a little bit. I forgot about this one. 😁
