### ISSUE TITLE
before_save ignores on: option silently

### ISSUE THREAD

**Issue by Soleone** [rails/rails#17622]
**Problem**

It looks like the following line will not do what users expect:

```
before_save :do_something, on: :create
```

The `on: :create` option will just get silently ignored and `do_something` will get called after _every_ save on the record, not just the initial create. Same goes for `after_save`.

This might cause some hard to trace bugs in your rails app. I just stumbled upon this today by accident, I asked around and a lot of my coworkers weren't aware either that this is how it works.

Instead users have to do:

```
before_create :do_something
```

see also http://stackoverflow.com/questions/10640221/is-on-create-valid-for-a-before-save-callback-in-rails-3-2-3

**Suggestion**

Either have `before_save` with `on: :create` option behave like `before_create` or raise an error that the `:on` option is not allowed here.

**Comment by Soleone** [comment]
just to clarify because i failed to realize, the `:on` option is also not respected for the `after_initialize` callback - if i understand the only callback that respects the `:on` option is `before_validation`. makes for very subtle bugs

**Comment by seanlinsley** [comment]
My team just ran into this bug. I'm looking into submitting a PR for this.

**Comment by seanlinsley** [comment]
I'm happy to use keyword arguments, but I noticed that in other places we have custom code to raise an error:

https://github.com/rails/rails/blob/cd92d2e57d8d504db2b9d01912902700bcf8d3e5/activemodel/lib/active_model/validations.rb#L154-L163

Ah, and it looks like `if:` isn't a valid keyword argument because it's reserved by Ruby. So we'll have to have custom error code no matter what.

**Comment by seanlinsley** [comment]
I submitted a PR for this if anyone has thoughts on the implementation: https://github.com/rails/rails/pull/30919

**Comment by ybakos** [comment]
Bump. https://github.com/rails/rails/pull/30919

**Comment by phoet** [comment]
hm, in rails `5.2.1.1` it looks like you can still pass the `on:` option to the `before_save` callback and it gets ignored silently, just like any other option i pass in there. `if:` works fine though.

i was wondering if it would make sense to at least update the documentation in rails 5 on where to use what option. its very confusing.

**Comment by hopewise** [comment]
that works well in rails 5
    before_save :create_roles, if: Proc.new { |u| u.id.nil? } #only new users condition
