### ISSUE TITLE
ActiveRecord::Associations::AliasTracker assumes strings don't respond to :left

### ISSUE THREAD

**Issue by scpike** [rails/rails#17656]
There is at least one (non-rails) gem out in the wild that adds a "left" method to String:  https://github.com/tj/terminal-table/blob/master/lib/terminal-table/core_ext.rb

AliasTracker uses respond_to?(:left) to determine (I think, but I don't know what it's doing exactly) whether a join is some sort of Arel join object:

   https://github.com/rails/rails/blob/8e9cb9787bab976fa3a9a7722c5a024dc8384de4/activerecord/lib/active_record/associations/alias_tracker.rb#L35

Now, just doing `User.joins("foo")` causes a StringJoin to be passed in, so everything works fine. If you use both includes and references, however, you can get a string passed in (sorry, but I don't know nearly enough about what's going on here to know why this is happening), which throws an exception. In this case the gem I linked has aliased `left` to `ljust`, so you get:

   > Car.includes(:bulbs).references(:bulbs).joins("inner join tyres tyres.car_id = cars.id") 
       ArgumentError: wrong number of arguments (0 for 1..2)
        from /.../activerecord-4.1.8/lib/active_record/associations/alias_tracker.rb:36:in `ljust'

This is all a bit insane, but I figured it's worth getting down in writing.  I'm testing on rails 4.1.8.

**Comment by nateberkopec** [comment]
FWIW, this is now fixed in terminal-table.

**Comment by scpike** [comment]
@nateberkopec would it be worth re-opening if I post a test case which adds `left` to String, or are you only concerned about code that doesn't open core classes?

**Comment by nateberkopec** [comment]
> would it be worth re-opening if I post a test case which adds left to String

You mean, added a test case that adds `left` to string and then runs some Arel code that fails? I mean, I'm not a core team member (just Some Dude From The Internet here), but that seems like a silly test to me. We can't have tests for every single possible conflicting method that could _possibly_ be added to a core class. The moral is, IMO: don't monkey-patch Ruby core in your libraries unless you're ActiveSupport. String should not respond to `left`. That doesn't even make sense.

Also, there's a reason that code you cited is written the way it is. It's duck-typing. This gives Arel flexibility in the future to use different types of objects to build joins. That's good. _Maybe_ they should have chosen a more descriptive method name than `left`, but that's the only nitpick I can see here.

**Comment by scpike** [comment]
Oh, I totally agree what this library was doing is insane. The reason I offered the test case was in case this part of my report is unexpected:

> Now, just doing User.joins("foo") causes a StringJoin to be passed in, so everything works fine. If you use both includes and references, however, you can get a string passed in (sorry, but I don't know nearly enough about what's going on here to know why this is happening), which throws an exception. In this case the gem I linked has aliased left to ljust, so you get:

I don't know what `StringJoin` is, and I don't know if a raw `String` getting into the mix is a bug.

**Comment by nateberkopec** [comment]
>you can get a string passed in (sorry, but I don't know nearly enough about what's going on here to know why this is happening), which throws an exception.

Wait, so just _any string_ passed in raises an exception? Yeah, I think that might be novel, but that's beyond my depth in ActiveRecord as well.

**Comment by scpike** [comment]
Sorry, I'm talking past you. Only strings with `left` on them cause an exception. I was surprised that there was this one code path (requiring both `includes` AND `references`) where the function got a raw string, given that there's this `StringJoin` thing coming in with other joins calls, but I don't know enough to know whether it's something worth looking at. 

Anyway, I don't think I'm adding anything useful here, so if you don't think it looks odd too let's just drop it.
