### ISSUE TITLE
content_tag ignores block with non-string value b/c capture ignores non-strings

### ISSUE THREAD

**Issue by carpodaster** [rails/rails#17661]
Given the following code outside an ERB context returns an empty `<p></p>` tag instead of my assumed `<p>1.0</p>`:
```ruby
content_tag(:p) do
  1.0
end
```
I find this counter-intuitive and would argue for an implicit `#to_s`, but the underlying [capture](https://github.com/rails/rails/blob/master/actionview/lib/action_view/helpers/capture_helper.rb#L39) ignores non-String values.

Is the behaviour for `content_tag` intentional? Are there any foul consquences for a `capture` that looks like this?
```ruby
def capture(*args)
  value = nil
  buffer = with_output_buffer { value = yield(*args) }
  if string = buffer.presence || value.to_s
    ERB::Util.html_escape string
  end
end
```

**Edit**: My question is less directed at breaking `capture_helper_test.rb:28` and `capture_helper_test.rb:137` but any real world breakage :smile:

**Comment by rafaelfranca** [comment]
Closing given it was indeed the expected behavior see https://github.com/rails/rails/pull/18024#commitcomment-8975180
