### ISSUE TITLE
link_to / form_for doesn't work for singular resource

### ISSUE THREAD

**Issue by Godisemo** [rails/rails#1769]
In my routes I have

```ruby
resource :company
```

and in my views

```erb
<% form_for(@store) do |f| %>
    …
<% end %>
```

When 

new action gets an error when rendering

```undefined method `hash_for_companies_path' for #<Module:0x00000102bfd3f0>```

The stack trace reviels that the problem occurs in

```lib/action_dispatch/routing/polymorphic_routes.rb:133:in `polymorphic_url'```

edit action can render without errors but the forms url is ```/company.4``` where 4 is the id of the company.

This seems to be a bug that has been around for a very long time so I think it's time to fix it.

**Comment by azul** [comment]
@pixeltrix, How about trying the plural route first. Then catching the undefined method error in polymorphic_url and trying the singular route?
That would not solve the problem when both methods are defined. But I think it would be easy to document and understand. If one has both a resource and resources defined for the same model they will have to state which one they want anyway (using the url option for example).

**Comment by justinj656** [comment]
The workaroud I use is to add as: to change the path helper for the singular resources, like
`resource company, as: :companies`

**Comment by philipgiuliani** [comment]
Why a bug like this isn't fixed yet?

**Comment by notrab** [comment]
@philipgiuliani I'm sure you'll discover, judging by the comments above, there isn't any easy way to do this without polluting other classes within Rails for this behaviour. 

The workaround is quite simple and to be honest, I don't see a problem. Throw it in the docs and just be done with it. Adding `url: ` to the form declaration isn't so hard work for singular routes.

😴

**Comment by rafaelfranca** [comment]
See https://github.com/rails/rails/pull/17066#issuecomment-57363051

**Comment by schuetzm** [comment]
@rafaelfranca Care to explain why you closed this issue? The comment you referenced says it is still open "because it's a difficult problem to solve". Has it finally been fixed?

**Comment by rafaelfranca** [comment]
Oops! Looks like I linked to the wrong comment. I could not find the comment that I explained that it is fine to use the `:url` option and that this problem is not something that we need to fix.

https://github.com/rails/rails/pull/23138 may fix this issue introducing a new API.

**Comment by matkoniecz** [comment]
Why it is closed? #23138 is not merged and it is explicitly documented as existing bug in http://guides.rubyonrails.org/v4.1/routing.html

**Comment by azul** [comment]
@matkoniecz - it's documented as you said including a workaround with the url param. And there is a bug that may fix this in the longer run. I think that is why it's closed. #23138 will track the progress on the fix now.

**Comment by IamNaN** [comment]
For anyone landing here via google, this is what got implemented: http://edgeguides.rubyonrails.org/routing.html#singular-resources

In short, add something like `resolve('User') { [:user] }` after you define the singular resource in routes.rb, where 'User' is the class name and :user is the resource name.

**Comment by tomrossi7** [comment]
Couldn't this be fixed in the latest rails implementation by changing the behavior of `form_with`?

**Comment by johnpitchko** [comment]
> resolve

To expand on @IamNaN 's valuable information, `resolve` cannot be used for nested singular resources e.g.

```
resources :posts do
  resource :comment
end
```
