### ISSUE TITLE
ActiveRecord joins/includes bug

### ISSUE THREAD

**Issue by dgobaud** [rails/rails#17795]
rails 4.1.8

```
email_threads = EmailThread.joins(:emails => :gmail_labels).
                            includes(:emails => [:gmail_labels, :email_attachments]).
                            where(:id => email_threads).
                            order('"emails"."draft_id" NULLS FIRST, "emails"."date" DESC, "email_threads"."id" DESC')
```

doesn't eager load and results in n+1 queries https://gist.github.com/anonymous/1a711c1eeb431284d7ae

```
email_threads = EmailThread.joins(:emails => :gmail_labels).
                                includes(:emails => :gmail_labels).
                                where(:id => email_threads).
                                order('"emails"."draft_id" NULLS FIRST, "emails"."date" DESC, "email_threads"."id" DESC')

email_threads = email_threads.includes(:emails => :email_attachments)
```

does eager load and only does 1 query https://gist.github.com/anonymous/a4e64afa11a811aa54e2

**Comment by alexcameron89** [comment]
It looks like this has been fixed is good to close.

**Ruby Method**
`email_threads = EmailThread.joins(:emails => :gmail_labels).
    includes(:emails => [:gmail_labels, :email_attachments]).
    where(:id => thread_ids).
    order('"email_threads"."id" DESC')`

**Generated SQL Query**
`SELECT "email_threads".* FROM "email_threads" INNER JOIN "emails" ON "emails"."email_thread_id" = "email_threads"."id" INNER JOIN "email_folder_mappings" ON "email_folder_mappings"."email_id" = "emails"."id" AND "email_folder_mappings"."email_folder_type" = ? INNER JOIN "gmail_labels" ON "gmail_labels"."id" = "email_folder_mappings"."email_folder_id" WHERE "email_threads"."id" = ? ORDER BY "email_threads"."id" DESC  [["email_folder_type", "GmailLabel"], ["id", 1]]
`

---
**Ruby Method**
`email_threads = EmailThread.joins(:emails => [:gmail_labels, :email_attachments]).
    includes(:emails => [:gmail_labels, :email_attachments]).
    where(:id => thread_ids).
    order('"email_threads"."id" DESC')`

**Generated SQL Query**
`SELECT "email_threads"."id" AS t0_r0, "email_threads"."uid" AS t0_r1, "email_threads"."created_at" AS t0_r2, "email_threads"."updated_at" AS t0_r3, "emails"."id" AS t1_r0, "emails"."email_thread_id" AS t1_r1, "emails"."uid" AS t1_r2, "emails"."draft_id" AS t1_r3, "emails"."message_id" AS t1_r4, "emails"."created_at" AS t1_r5, "emails"."updated_at" AS t1_r6, "gmail_labels"."id" AS t2_r0, "gmail_labels"."gmail_account_id" AS t2_r1, "gmail_labels"."label_id" AS t2_r2, "gmail_labels"."name" AS t2_r3, "gmail_labels"."created_at" AS t2_r4, "gmail_labels"."updated_at" AS t2_r5, "email_attachments"."id" AS t3_r0, "email_attachments"."email_id" AS t3_r1, "email_attachments"."filename" AS t3_r2, "email_attachments"."content_type" AS t3_r3, "email_attachments"."file_size" AS t3_r4, "email_attachments"."created_at" AS t3_r5, "email_attachments"."updated_at" AS t3_r6 FROM "email_threads" INNER JOIN "emails" ON "emails"."email_thread_id" = "email_threads"."id" INNER JOIN "email_folder_mappings" ON "email_folder_mappings"."email_id" = "emails"."id" AND "email_folder_mappings"."email_folder_type" = ? INNER JOIN "gmail_labels" ON "gmail_labels"."id" = "email_folder_mappings"."email_folder_id" LEFT OUTER JOIN "email_attachments" ON "email_attachments"."email_id" = "emails"."id" WHERE "email_threads"."id" = ? ORDER BY "email_threads"."id" DESC  [["email_folder_type", "GmailLabel"], ["id", 1]]
`

**Comment by kamipo** [comment]
I also think n+1 queries has been fixed.
