### ISSUE TITLE
Bug when using find_in_batches and reverse_order

### ISSUE THREAD

**Issue by robertjlooby** [rails/rails#17854]
There is a bug in activerecord when using `reverse_order` along with `find_in_batches`/`find_each`. 

Using the standard Post model example:

```
2.1.3 :002 > 30.times { Post.create! }
2.1.3 :003 > Post.where('id < ?', 100).reverse_order.find_in_batches(batch_size: 10) { |batch| puts batch.map(&:id).to_s }
Scoped order and limit are ignored, it's forced to be batch order and batch size
  Post Load (0.2ms)  SELECT  "posts".* FROM "posts"  WHERE (id < 100)  ORDER BY "posts"."id" DESC LIMIT 10
[30, 29, 28, 27, 26, 25, 24, 23, 22, 21]
  Post Load (0.2ms)  SELECT  "posts".* FROM "posts"  WHERE (id < 100) AND ("posts"."id" > 21)  ORDER BY "posts"."id" DESC LIMIT 10
[30, 29, 28, 27, 26, 25, 24, 23, 22]
 => nil
```

It does show the warning about ignoring order when using batches, but it doesn't exactly ignore the reverse which causes the bug.

Essentially if the batch size is less than the number of records, then it will always return 2 batches. The first batch contains the first batch of records (starting with the greatest id), and the second batch contains the same records minus the last one.

The root cause seems to be a conflict with the way the ids are ordered [here](https://github.com/rails/rails/blob/3d70f0740b26b0a137d7e6436f9909330f8ee888/activerecord/lib/active_record/relation/batches.rb#L117) and allowing `reverse_order` to [rewrite](https://github.com/rails/rails/blob/a975407a0a4f8bb06f8d4696de6a8b5e5a086622/activerecord/lib/active_record/relation/query_methods.rb#L1083) the ASC reordering [here](https://github.com/rails/rails/blob/3d70f0740b26b0a137d7e6436f9909330f8ee888/activerecord/lib/active_record/relation/batches.rb#L116)

**Comment by prathamesh-sonpatki** [comment]
@rafaelfranca This can be closed now :)

**Comment by rafaelfranca** [comment]
:heart: :green_heart: :blue_heart: :yellow_heart: :purple_heart:
