### ISSUE TITLE
hm:t association with order clause that references join table cannot be preloaded

### ISSUE THREAD

**Issue by rywall** [rails/rails#17904]
In Rails 4.0, the order clause was ignored. 
In Rails 4.1, invalid SQL is generated.

Please see this runnable test case: https://gist.github.com/rywall/8854c36f104b2eb91bdb

**Comment by rywall** [comment]
FYI, this issue also occurs in Rails 4.2 and master.

**Comment by rywall** [comment]
I've opened a pull request which fixes this issue. Feedback welcome! #19329.

**Comment by sevaorlov** [comment]
that seems to be related to https://github.com/rails/rails/issues/22538, but in my PR I only merge joins in scopes
