### ISSUE TITLE
QueryCache works only for ActiveRecord::Base.connection

### ISSUE THREAD

**Issue by Fivell** [rails/rails#17921]
Hello, can you please advise about QueryCache middleware. By default it thinks that I'm using only one connection (ActiveRecord::Base.connection) and sql generated by models connected to other DBs are not cached 

For instance cache works for this
```
class Item < ActiveRecord::Base
end
```

and doesn't work for this
```
class SlaveItem < ActiveRecord::Base
    establish_connection "#{Rails.env}_slave".to_sym
end
```

But manual says "Query caching is a Rails feature that caches the result set returned by each query"

SO thread http://stackoverflow.com/questions/4326250/why-is-rails-query-caching-not-working

**Comment by magikid** [comment]
@fivell read through the comments in #17776 for some ideas of what to do if you're still seeing this issue.

**Comment by Fivell** [comment]
@magikid , this issue is about query_cache middleware, which not cashing queries for other db connection different from ActiveRecord::Base.

**Comment by arthurnn** [comment]
We have a similar issue, as we have multiple connections to the db. We have this method, and wrap the calls with it:
```
      def with_query_cache
        if Sharding.master_connection.query_cache_enabled
          Sharding.connection.cache { yield }
        else
          yield
        end
      end
```

You can do something similar. Ideally AR should handle multiple connections at some point.

**Comment by Fivell** [comment]
@arthurnn , 
>> Ideally AR should handle multiple connections at some point.

That would be awesome 

BTW when are you clearing connection cache in your example ?
I mean this https://github.com/rails/rails/blob/3d70f0740b26b0a137d7e6436f9909330f8ee888/activerecord/lib/active_record/query_cache.rb#L51

**Comment by jeremywadsack** [comment]
With #20818 (as a proposed solution for #17776) I've added a notification for ActiveRecord connections established after start-up. QueryCache could then subscribe to the notification and keep a collection of connections.

I don't understand the `restore_query_cache_settings` method but this might help the class use less global singleton variables and take a step towards supporting multiple databases.

**Comment by arthurnn** [comment]
@Fivell we iterate over all connections and clear the cache in all of them. nothing special honestly.

@jeremywadsack thanks for the references, i will take a look.

for now i will close this, as we are aware that AR has some limitations around using the base connection, and we have some work fixing the issue.
