### ISSUE TITLE
Unnecessary BEGIN/COMMIT happens when model save is a no-op

### ISSUE THREAD

**Issue by Fryguy** [rails/rails#17937]
When a model is saved, and Rails detects that no changes are necessary to send to the server, it still sends a BEGIN/COMMIT to the server.

[Rails console on 4.1.8 showing the issue](https://gist.github.com/Fryguy/2d13e9fafc4a89862d68).  Note that this is using sqlite, but it also happens with PG, which is what we use on our application.

This BEGIN/COMMIT is unnecessary, and contributes to a performance penalty.  The performance penalty is exacerbated by
- having the database on a remote server
- calling save on (thousands) of records where a majority do not change.
  For our application we hit both of those bullet points, and the performance penalty was noticeable.

Unfortunately, when I first discovered this problem our code was running on Rails 2.2.2, a long time ago.  I don't have the numbers on how much performance impact it made anymore, but I remember it being significant for us.  We are currently on Rails 3.2, but I never completed porting the fix to our Rails 3.2 based system, mainly because so much changed in that area of the code.  Now that we are going to Rails 4 and then eventually 5, I am very far removed on how to fix this.  (Not to mention that my personal cycles for fixing are limited).

However, if it helps, I still have the changes I made to fix this for Rails 2.2.2.  The approach was to introduce a delay in the transaction block to not send the "BEGIN" until the first executable statement was also sent.  This worked very well for us, but the down side was every adapter had to be changed to support delaying, which I didn't like.  It felt like there should be a better way to do it for all adapters that support transactions.  This was one reason I never contributed the code to rails proper; I didn't think the fix would be accepted.  

[Delayed BEGIN on Rails 2.2.2 patch](https://gist.github.com/Fryguy/9ea050eda27e5f2ac24a)

EDIT: Clarification on the patch.  This is a patch relative to other patches we had on our code base.  I doubt it's directly applicable to Rails 2.2.2.  It's more meant to give the idea of what we did.

---

@tenderlove This is the stuff we spoke about yesterday.  Hopefully this patch file helps you or whoever might work on it to figure out the best approach.

**Comment by rafaelfranca** [comment]
@tenderlove @matthewd you may be interested on fixing this since it is related to your project, so I'll keep it open.

**Comment by jeremy** [comment]
Critically, this causes database adapters like [Makara](https://github.com/taskrabbit/makara) that do read/write splitting to end up switching to the write db for an empty transaction… then sticking to it for some time thereafter to avoid stale reads.

Lazy transactions would ensure that an empty BEGIN…COMMIT is never issued, avoiding the false signal to switch from reader to writer connection.

@Fryguy, the concept in your patch looks good. Up for bringing a PR up to speed with current Rails?

/cc @rosa @tenderlove @matthewd @georgeclaghorn @dhh

**Comment by wollkind** [comment]
Throughout our code we call save without regard for whether the save is actually necessary, so this is of interest to me as well.  Glad to see it's being worked on.  I was wondering about the safety of overriding the save method to first call .changed? and do nothing if it is false, but that makes me nervous.

**Comment by Rosa** [comment]
@wollkind @jeremy that was the sort of approach we took in my previous job in the past, not exactly using `changed?`, but doing something similar to the current implementation of `update_attribute`, [that doesn't call `save`](https://github.com/rails/rails/blob/7fcd25f44ce059bf9d68b9fd125c44c46b08c074/activerecord/lib/active_record/persistence.rb#L270-L274) unless it has something to save. We didn't patch `save`, though, only `update_attribute` that was being the problematic for us at that time, in Rails 3.2.

**Comment by Fryguy** [comment]
We had tweaked the specific hotspot in our app with the following.

```ruby
  def update_attributes!(ar_model, attributes, remove_keys)
    ar_model.assign_attributes(attributes.except(*remove_keys))
    # HACK: Avoid empty BEGIN/COMMIT pair until fix is made for https://github.com/rails/rails/issues/17937
    ar_model.save! if ar_model.changed?
  end
```

@jeremy I've been swamped lately, but I'll try to give it a shot 😄

**Comment by Rosa** [comment]
I realised that the approach of "not saving if it doesn't changed" taken in `update_attribute` cannot be easily translated to `update`. The reason is that `assign_attributes` might modify and perform actions in the DB due to child attributes being passed as well. These need to be wrapped in a transaction so they can be rolled back if the changes in the parent fail. https://github.com/rails/rails/commit/f4fbc2c1f943ff11776b2c7c34df6bcbe655a4e5 made me realise this. I didn't think enough about doing the same with `save`. I believe the delayed transaction approach is more promising! I'm going to think about it as well, perhaps there is a more generic way that doesn't require modifying all the adapters.

**Comment by Fryguy** [comment]
> I've been swamped lately, but I'll try to give it a shot 😄

Still swamped 😕  ...not sure when I'll be able to get to this, but anyone that wants to give it a shot, please do.

**Comment by kbrock** [comment]
I've been going on the premise that a delayed `"BEGIN"` is the way to go. The framework emits a begin and the driver only sends the command to the database if there is meat to the query.

But this does require updates to all the database specific drivers. And potentially modifying an endpoint that some extensions may be tweaking. (not sure if that is a concern)

@rosa have you come up with an alternate approach? Or do you have any ideas that look to avoid the need of modifying all database specific drivers?

**Comment by rosa** [comment]
@kbrock not yet... I started to implement a `DelayedTransaction` type of `Transaction`, used by the `TransactionManager` in `connection_adapters/abstract/transaction.rb`. That one would use new methods implemented in `active_record/connection_adapters/abstract/database_statements.rb`, that don't `BEGIN` the transaction directly, but open a delayed transaction instead, sending the `BEGIN` only when there's going to be a query. But I had to modify the individual drivers, though, at least to differentiate between `commit_db_transaction` and `exec_commit_db_transaction`.  I thought about other gems or extensions that might be using these directly, which would probably cause issues with them...

Anyway, I haven't got to make it work yet, it's something I work from time to time without devoting enough time 😓 If you have an approach that works that would be great!

**Comment by arthurnn** [comment]
Hi,
A way I was wondering to implement this was to change the `RealTransaction#initialize` method, and instead of sending the BEGIN to the db at that point, just wait until the transaction actually had started.
I have a super WIP commit that illustrates that. Not all tests pass yet, but it is an idea out there. (Especially the names of methods/APIs need to be re-worked)
here is the branch: https://github.com/rails/rails/compare/master...arthurnn:arthurnn/lazy_begin_txn

**Comment by kbrock** [comment]
@rosa Yea, so many other things going on. A bunch of low-priority thread still get the job done. I just stumbled upon a performance issue and thought to tip my hat back into the ring.

@arthurnn Thanks. I'll revisit this approach. Think that had led me to a duplicate `commit_db_transaction`, but always worth another look.

**Comment by krainboltgreene** [comment]
Hey, I would love to work on this, but also my company has a vested interest in improving this problem.

I'm going to approach this first as a hack on our application then a gem and then finally a PR. Does anyone have this already done or has insight into the changes that need to be made?

**Comment by matthewd** [comment]
@krainboltgreene  I'm normally very strong on the "start with monkeypatches / a gem" approach, but in this case, given how much I think you're going to end up needing to override/mangle, I think I'd personally go straight to a fork of whichever Rails version you're using. (And then later forward-port it to master to make the PR.)

Big picture, I think the approach discussed above is the way to go: keep track of how many transactions the code thinks it's in, and how many transactions deep we actually are on the DB side, and then only do as much as needed to synchronize those two immediately before a query is executed.

e.g., note that `begin; begin; select 1; begin; begin; select 2; select 3; begin; begin` only needs to be two transactions deep on the server -- one started immediately before each of the first two selects. Any sequence of commits and rollbacks (and subsequent queries) for the "virtual" transactions can be achieved with just those two "real" ones.

**Comment by krainboltgreene** [comment]
Sadly I think a fork of the rails would be a bigger ask. I know, I know.

I'll keep this advice in mind.
