### ISSUE TITLE
Invertible relationship not set when using build in has_many :through

### ISSUE THREAD

**Issue by deepinsand** [rails/rails#18042]
```ruby
# Activate the gem you are reporting the issue against.
gem 'activerecord', '4.1.1'
require 'active_record'
require 'minitest/autorun'
require 'logger'

# Ensure backward compatibility with Minitest 4
Minitest::Test = MiniTest::Unit::TestCase unless defined?(Minitest::Test)

# This connection will do for database-independent bug reports.
ActiveRecord::Base.establish_connection(adapter: 'sqlite3', database: ':memory:')
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :posts do |t| end

  create_table :readers do |t| end

  create_table :posts_readers do |t|
    t.integer :post_id
    t.integer :reader_id
  end
end

class PostsReader < ActiveRecord::Base
  belongs_to :post, inverse_of: :posts_readers
  belongs_to :reader, inverse_of: :posts_readers
end

class Post < ActiveRecord::Base
  has_many :posts_readers, inverse_of: :post
  has_many :readers, through: :posts_readers
end

class Reader < ActiveRecord::Base
  has_many :posts_readers, inverse_of: :reader
  has_many :posts, through: :posts_readers
end

class BugTest < Minitest::Test
  def test_has_many_through_build
    post = Post.create!
    post.readers.build

    assert_equal post, post.readers[0].posts[0]
  end
end
```

The above gist will fail, presumably because the invertible relationship on a hm:t relationship is not set.  The use case I have is to implement validation on the child object that touches the parent (Reader in this example), so the same applies to a create or << call.

**Comment by pixeltrix** [comment]
This is expected since the through association record hasn't been saved so the query to load `the reader's posts will try to find a post reader with an id of `NULL`.

**Comment by deepinsand** [comment]
@pixeltrix Should the inverse_of work before the record has been saved?

**Comment by pixeltrix** [comment]
@deepinsand it'd be reasonable to expect direct `:inverse_of` to work but hm:t associations need to go to the database. The only way to make it work would be an identity mapper which we've tried in the past but it turns out there's a lot of hard edge cases where behaviour is unexpected.

So this should work:

``` ruby
class BugTest < Minitest::Test
  def test_has_many_through_build
    post = Post.create!
    reader = post.readers.build

    assert_equal post, reader.post_readers[0].post
  end
end
```

But `:inverse_of` is [explicitly documented][1] as not working:

> Specifies the name of the belongs_to association on the associated object that is the inverse of this has_many association. Does not work in combination with :through or :as options. See ActiveRecord::Associations::ClassMethods's overview on Bi-directional associations for more detail.

[1]: http://api.rubyonrails.org/classes/ActiveRecord/Associations/ClassMethods.html#method-i-has_many
