### ISSUE TITLE
assets.compress could be documented better

### ISSUE THREAD

**Issue by ashanbrown** [rails/rails#18057]
I think there are some places in the docs where it still gives the impression that the `config.compress` flag does something.   I also don't think it's completely clear that `nil` is a legitimate option to pass to `js_compressor`, and that is is in fact the default for everything but prod.  Not only is it legitimate, but it is a really good idea in development which is presumably why it is the default.  The strange thing is that if you you set `config.assets.debug = true`, it will look like your javascript has not been compressed (because all assets are fetched with the `body=1` query param), but in fact, sprockets will still have gone and uglified your entire `application.js` file in the process of checking for errors.  Add `therubyracer`, which appears to slow down execjs by a factor of 3 (at least on my box) and reload times for an ember app become ridiculous.  Having spent a few hours figuring this all out, it would be great if other's who have upgraded to rails4 wouldn't have to experience to this.  Perhaps the upgrade guide should make it clear that you should really set `assets.js_compressor = nil` in development.

Here are the doc issues:

From upgrading_ruby_on_rails.md (https://github.com/rails/rails/blob/master/guides/source/upgrading_ruby_on_rails.md#sprockets-rails)

> ### sprockets-rails

* `assets:precompile:primary` and `assets:precompile:all` have been removed. Use `assets:precompile` instead.
* The `config.assets.compress` option should be changed to `config.assets.js_compressor` like so for instance:

```ruby
config.assets.js_compressor = :uglifier
```
configuring.md, still reads:

> * `config.assets.compress` a flag that enables the compression of compiled assets. It is explicitly set to true in `config/environments/production.rb`.

In asset_pipeline.md, it still says:

> ### Manifest Files and Directives
>
> Sprockets uses manifest files to determine which assets to include and serve.
> These manifest files contain _directives_ - instructions that tell Sprockets
> which files to require in order to build a single CSS or JavaScript file. With
> these directives, Sprockets loads the files specified, processes them if
> necessary, concatenates them into one single file and then compresses them (if
> `Rails.application.config.assets.compress` is true).

**Comment by BrianTheCoder** [comment]
In 4.2 setting ```config.assets.js_compressor = nil``` or ```config.assets.compress = false``` is still compressing my assets in production :(
