### ISSUE TITLE
add_index creates a full index when database doesn't support partial indexes

### ISSUE THREAD

**Issue by rainhead** [rails/rails#18106]
add_index :group_discussions, :column, unique: true, where: "column = 123"
generates the SQL
    CREATE UNIQUE INDEX `index_group_discussions_on_column`  ON `group_discussions` (`column`)
when run against a mysql database.

Expected result: an error stating that the database doesn't support partial indexes.

**Comment by schmidt** [comment]
Similar to other `add_index` options the documentation should mention, that the `where` option is not supported on MySQL.
