### ISSUE TITLE
Thread-safety problem in ActiveRecord's DelegateCache

### ISSUE THREAD

**Issue by mertguldur** [rails/rails#18115]
I get the following error when multiple threads execute `<Relation>.where` in an application running on Rubinius 2.2.10. 

```
kernel/delta/kernel.rb:78→ [] (method_missing)
/export/rails/activerecord/lib/active_record/relation/delegation.rb:12→ relation_delegate_class
/export/rails/activerecord/lib/active_record/relation/delegation.rb:116→ relation_class_for
/export/rails/activerecord/lib/active_record/relation/delegation.rb:110→ create
/export/rails/activerecord/lib/active_record/core.rb:164→ relation
/export/rails/activerecord/lib/active_record/scoping/named.rb:33→ default_scoped
/export/rails/activerecord/lib/active_record/scoping/named.rb:28→ all
/export/rails/activerecord/lib/active_record/querying.rb:10→ where
```

It seems that `@relation_delegate_cache` was initialized once for that relation when the application started up, but I have no idea about what is setting that cache to `nil`. I don't have a gist that reproduces the bug, because simply calling `<Relation>.where` continuously in multiple threads doesn't trigger it.

**Comment by rafaelfranca** [comment]
I can't see a reason for this cache being nil. It is defined when the model is defined and it should behaves before the query is made.

Does it happen on production? It is just when loading the application?

**Comment by mertguldur** [comment]
It happens on all environments. The bug gets triggered when I let multiple threads to execute ActiveRecord calls right after the application loads up. However when I make the other threads wait while the first one does its job, and then let the others run in parallel, the bug doesn't get triggered.

**Comment by rafaelfranca** [comment]
Right. Thank you for confirming.

**Comment by rafaelfranca** [comment]
cc @thedarkone @tenderlove @matthewd I know you guys like to play with tread-safety problems :smile:

**Comment by tenderlove** [comment]
What version of Rails?  Does this happen on a basic app, or can you post an app that demonstrates the problem?

**Comment by thedarkone** [comment]
@mertguldur are you sure you are not somehow concurrently autoloading Active Record classes?

Can you maybe monkey-patch [`DelegateCache.initialize_relation_delegate_cache`](https://github.com/rails/rails/blob/6489a84eb69162ccefac106d08bae1c31a2b4fa5/activerecord/lib/active_record/relation/delegation.rb#L11) to print out class names:

```ruby
def initialize_relation_delegate_cache
   puts "initialize_relation_delegate_cache on #{name}"
   # ... rest of initialize_relation_delegate_cache
end
```

while also patching to print out any uninitialized caches:
```ruby
def relation_delegate_class(klass) # :nodoc:
  puts "missing relation_delegate_class on #{klass.name}" unless @relation_delegate_cache
  @relation_delegate_cache[klass]
end
```

Note that `initialize_relation_delegate_cache` should never run after your app finishes booting up (ie before you spin up any additional threads).

**Comment by tenderlove** [comment]
> The failing thread printed out "missing relation_delegate_class on #{klass.name}" right before erroring out, but that model's cache had been initialized during the boot up.

If that's the case, then it sounds like we're setting up the cache correctly.  Are you able to run this app on JRuby?  I'm curious if it breaks there too.

**Comment by jbodah** [comment]
Old thread - wanted to post that an app I was upgrading ran into this because they had a subclass of ActiveRecord::Base with a custom defined `inherited` hook that was doing work before ActiveRecord's `inherited` hooks had been fired; had to `super` first (rather than after applying the custom hook's code which seemed to work in Rails 3.2). Specifically this hook was calling `self.table_name=`
