### ISSUE TITLE
Pare back default options for the migration generator

### ISSUE THREAD

**Issue by dhh** [rails/rails#18146]
Currently, `rails g model lock recording:references user:references` generates the following:

```ruby
class CreateLocks < ActiveRecord::Migration
  def change
    create_table :locks do |t|
      t.references :recording, index: true
      t.references :user, index: true

      t.timestamps null: false
    end
    add_foreign_key :locks, :recordings
    add_foreign_key :locks, :users
  end
end
```

That's just a nasty soup of option galore. I'd like to slim that down to:

```ruby
class CreateLocks < ActiveRecord::Migration
  def change
    create_table :locks do |t|
      t.references :recording
      t.references :user

      t.timestamps
    end
  end
end
```

That'll require the following changes:

* #references should automatically add a index -- it's what you want in 9/10 cases. So instead people can do index: false if they DON'T want the index.
* timestamps are maintained by AR. I'm not sure we need to have a DB protection against them not being nil. If we absolutely must, then that should be the default as well.
* Don't add the foreign keys by default, and for those who'd like them, let's add `r.references :recording, foreign_key: true` as an option that can be added by `r g model recording:references{foreign_key}`.

There are certainly some complications with changing the migration format, but let's figure those out and mitigate (ha!) as best we can. Rails 5.0 should not be generating such crufty migrations by default as we're doing in 4.2, that much is clear.

**Comment by senny** [comment]
Just ran the generator on the latest `master`. Migration currently looks like this:

```ruby
class CreateLocks < ActiveRecord::Migration
  def change
    create_table :locks do |t|
      t.references :recording, index: true, foreign_key: true
      t.references :user, index: true, foreign_key: true

      t.timestamps
    end
  end
end
```

**Comment by dhh** [comment]
Much nicer!

**Comment by dhh** [comment]
@matthewd Is this now solved?

**Comment by rafaelfranca** [comment]
Yes. It is

**Comment by matthewd** [comment]
No; we have the infrastructure to do it, but my PR didn't change the current defaults on `t.references`.

**Comment by rafaelfranca** [comment]
:+1:
