### ISSUE TITLE
Unexpected (?) behavior when generating translation keys for validations in namespaced classes

### ISSUE THREAD

**Issue by hubertlepicki** [rails/rails#18207]
So I have this form model, namespeced in registration module. I am adding validation for complexity of password (I know, I know), with ``errors.add(:password, :too_simple)``. The result is that the translation key Rails is looking for is 
``en.activemodel.errors.models.registration/form.attributes.password.too_simple`` 
while I would expect
``en.activemodel.errors.models.registration.form.attributes.password.too_simple``. 

I have made a demo app to show the case, the model is here:
https://github.com/hubertlepicki/i18n_class_in_module_validation_message/blob/master/app/services/registration/form.rb

and the en.yml file that *works* with this example can be seen here:
https://github.com/hubertlepicki/i18n_class_in_module_validation_message/blob/master/config/locales/en.yml

Is that intended behavior?

**Comment by rafaelfranca** [comment]
Yes. It is intended behavior. See the documentation at http://guides.rubyonrails.org/i18n.html#translations-for-active-record-models
