### ISSUE TITLE
Rails 3.2.21 (4.x too?): attribute_will_change! with symbol parameter causes "multiple assignment" error in Postgres

### ISSUE THREAD

**Issue by jensb** [rails/rails#18273]
It seems `attribute_will_change!` does not normalize its parameters (to strings). Example:

    class Foo < AR::Base
      def method1
         attribute_will_change!(:bar)
         something_thatll_modify_bar_indirectly
      end
      def method2
         self.bar = "whatever"
      end
    end

and

    f = Foo.new
    f.bar = "one"
    f.method1         # or call method2 first, it seems the order doesn't matter
    f.method2
    f.save!
    => PG::SyntaxError: ERROR:  multiple assignments to same column "bar"

This does not happen if you change method1 to

        attribute_will_change!("bar")

Note this only happens with Postgres, since other DBMS seem to accept multiple assignments in the same UPDATE command.

**Comment by prathamesh-sonpatki** [comment]
The issue seems to be fixed on 4.1.8 https://gist.github.com/prathamesh-sonpatki/c0ea72ebc1bedd92924c and 4.2.0 https://gist.github.com/prathamesh-sonpatki/e76270335ef0246ace59. Looks like bind parameters fixed it.

**Comment by rafaelfranca** [comment]
@prathamesh-sonpatki thank you for confirming.
