### ISSUE TITLE
4.2.0: undefined method `val' for Arel::Nodes::SelectStatement

### ISSUE THREAD

**Issue by jaredbeck** [rails/rails#18280]
In a new rails 4.2.0 app (https://github.com/jaredbeck/rails42_arel_val_error) there are three models, whose names have been changed to protect the innocent.

Banana belongs_to Bowl, which belongs_to Kitchen.  Banana has a (unusual) default scope that references a (unusual) scope in Bowl.  When we call Banana.new, we get 

    NoMethodError: undefined method `val' for #<Arel::Nodes::SelectStatement:0x007fbceb437380>

In the app, see `spec/models/banana_spec.rb` for a spec that reproduces this error.

Digging a bit, I found that after [this change](https://github.com/rails/rails/commit/426ae869fe85462f5592fb225b431144804e25af) to AR, the `where_values_hash` method seems to no longer support sub-queries.

For example, if we use a debugger to inspect `where` and `where.right` ..

```
[1] pry(#<Banana::ActiveRecord_Relation>)> where.to_sql
=> "bananas"."bowl_id" IN (
  SELECT "bowls"."id" 
  FROM "bowls" 
  INNER JOIN "kitchens" ON "kitchens"."id" = "bowls"."kitchen_id" 
  WHERE "bowls"."active" = 't' AND "kitchens"."active" = 't'
)
[2] pry(#<Banana::ActiveRecord_Relation>)> where.right.to_sql
=> SELECT "bowls"."id" 
  FROM "bowls" 
  INNER JOIN "kitchens" ON "kitchens"."id" = "bowls"."kitchen_id" 
  WHERE "bowls"."active" = 't' AND "kitchens"."active" = 't'
```

.. we see that `where.right` is a `SELECT`.

If there is a better way to implement this, I'd welcome it.  It's not my code, I'm just trying to upgrade it to rails 4.2.  But, just in case you think it's a bug in AR or arel, I thought you'd appreciate an executable bug report.

**Comment by jaredbeck** [comment]
Oh, and happy new year, anyone in EST  :cake:

**Comment by vipulnsward** [comment]
@jaredbeck this has been fixed at https://github.com/rails/rails/commit/78bd18a90992e3da767cfe492f1bc5d63077da8a .It also points out how you can fix this.

**Comment by sgrif** [comment]
In the future, please use [this template](https://github.com/rails/rails/blob/master/guides/bug_report_templates/active_record_master.rb) when reporting bugs rather than an app, it is much more work for us to replicate the issue otherwise. This appears to be separate from the issue that 78bd18a90992e3da767cfe492f1bc5d63077da8a was addressing, contrary to the previous comment.

**Comment by sgrif** [comment]
Especially when you generate it with structure.sql...

**Comment by vipulnsward** [comment]
@sgrif the specs from the App run successfully with @rafaelfranca 's fix.

**Comment by sgrif** [comment]
It does technically represent a change in behavior of `where_values_hash`, however. Though I'm not sure it's a bad one.

**Comment by sgrif** [comment]
I think you're right, this has already been sufficiently resolved.

**Comment by jaredbeck** [comment]
Switching to `4-2-stable` resolves the issue.  Thanks for the quick response! :heart:

> In the future, please use this template when reporting bugs rather than an app
> Especially when you generate it with structure.sql...

Will do.  That makes sense.

**Comment by bglbruno** [comment]
@jaredbeck, I have the same problem. You solve this like that?
` gem 'rails', github: 'rails/rails', branch: '4-2-stable' `

**Comment by jaredbeck** [comment]
> You solve this like that?
> gem 'rails', github: 'rails/rails', branch: '4-2-stable'

*precisement*

Or, you can wait for 4.2.1 (https://github.com/rails/rails/milestones/4.2.1) which is scheduled for February 19th.

**Comment by bglbruno** [comment]
Ok. Thanks @jaredbeck!
