### ISSUE TITLE
Rails 4.2.0: Scaffold generator with --helper=false produced an error

### ISSUE THREAD

**Issue by dldinternet** [rails/rails#18287]
This is a similar problem to the one reported in #9525.
This was on Rails `4.2.0` with Ruby `2.1.5`
 `rails g scaffold user name:string{64}:index first_name:string last_name:string password:digest --assets=false --helper=false`

              invoke  active_record
           identical    db/migrate/20141229044922_create_users.rb
           identical    app/models/user.rb
              invoke    rspec
           identical      spec/models/user_spec.rb
              invoke      factory_girl
            conflict        spec/factories/users.rb
              Overwrite spec/factories/users.rb? (enter "h" for help) [Ynaqdh] n
                skip        spec/factories/users.rb
              invoke  resource_route
               route    resources :users
              invoke  scaffold_controller
           identical    app/controllers/users_controller.rb
              invoke    haml
               exist      app/views/users
           identical      app/views/users/index.html.haml
           identical      app/views/users/edit.html.haml
           identical      app/views/users/show.html.haml
           identical      app/views/users/new.html.haml
           identical      app/views/users/_form.html.haml
              invoke    rspec
           identical      spec/controllers/users_controller_spec.rb
           identical      spec/views/users/edit.html.haml_spec.rb
           identical      spec/views/users/index.html.haml_spec.rb
           identical      spec/views/users/new.html.haml_spec.rb
           identical      spec/views/users/show.html.haml_spec.rb
           identical      spec/routing/users_routing_spec.rb
              invoke      rspec
           identical        spec/requests/users_spec.rb
               error    false [not found]

**Comment by dldinternet** [comment]
I have debugged the behavior a little and found the following.

The setting in the config 'g.assets false' is handled internally as if it was `g.assets :false` (Note the symbol instead of FalseClass here)

This causes the class eval dynamic method `_invoke_from_option_assets`  in `invoke_from_option` in `gems/thor-0.19.1/lib/thor/group.rb` to proceed past the `return unless options[#{name.inspect}]` but fail to match the invocation to a class and spit out an error. (`say_status :error, %(\#{value} [not found]), :red`)

It seems the fix here is to figure out how to prevent the `config.generators.assets false` from insisting that `false` is a symbol ...

**Comment by rafaelfranca** [comment]
Fixed by 4ba0e2f, backported as c84ff5c
