### ISSUE TITLE
activerecord should set association_id attribute when using `build`

### ISSUE THREAD

**Issue by xpepermint** [rails/rails#18297]
I have two models (`rails 4.2`)

``` ruby
class Project < ActiveRecord::Base
  has_many :memberships
end

class Membership < ActiveRecord::Base
  belongs_to :user
  belongs_to :project
  validates :user_id, :project_id, presence: true
end
```

In the example bellow the `save` method fails because `project_id` is not set but I validate its presence in the `Membership` model.
``` ruby
@project = Project.new(project_params)
@project.memberships.build(user_id: current_user.id, role: 'owner')
if @project.save
   redirect_to projects_path
else
   render :new
end
```

I have to add this
``` ruby
def project=(p)
    self.project_id = p.id if p
    super(p)
end
```
inside `Membership` model to fix this.

I think that his should be treated as a bug. I would expect that if I set association's object then also the {association}_id would be set.

**Comment by rafaelfranca** [comment]
Does it work if you change the validation of the _id to the association?

The _id is only set after the validation callback is run so it will be absent, but in the end of the process it will be there.

But since you are using Rails 4.2 use the new `required` option of the association and you will not have to think about which field you should validate.

**Comment by rafaelfranca** [comment]
Here is a reproduction test that is passing:

```ruby
# Activate the gem you are reporting the issue against.
gem 'activerecord', '4.2.0'
require 'active_record'
require 'minitest/autorun'
require 'logger'

# Ensure backward compatibility with Minitest 4
Minitest::Test = MiniTest::Unit::TestCase unless defined?(Minitest::Test)

# This connection will do for database-independent bug reports.
ActiveRecord::Base.establish_connection(adapter: 'sqlite3', database: ':memory:')
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :posts do |t|
  end

  create_table :comments do |t|
    t.integer :post_id
  end
end

class Post < ActiveRecord::Base
  has_many :comments
end

class Comment < ActiveRecord::Base
  belongs_to :post, required: true
end

class BugTest < Minitest::Test
  def test_association_stuff
    post = Post.new
    post.comments.build
    assert_equal true, post.save
    refute_equal nil, post.comments.first.post_id
  end
end
```

**Comment by xpepermint** [comment]
Thanks @rafaelfranca. Changing
``` ruby
class Membership < ActiveRecord::Base
  belongs_to :user, required: true
  belongs_to :project, required: true
end
```
works but the problem is still there. Model.errors should hold error messages for both `project` and `project_id` not only one of them thus you can easily show errors on simple_form.

**Comment by rafaelfranca** [comment]
The error is only at the validated field. I believe it is more a problem at Simple Form than Rails.

**Comment by xpepermint** [comment]
Hum...ok, thanks anyway.

**Comment by rafaelfranca** [comment]
If Simple Form is requiring you to validate the _id it is advertising a bad practice and should be changed. Please open an issue at Simple Form issue tracker with a way to reproduce it and I'll take a look.

**Comment by xpepermint** [comment]
I think I'll reconsider my case first. Thanks @rafaelfranca!
