### ISSUE TITLE
change/create_table should have foreign key support

### ISSUE THREAD

**Issue by wlipa** [rails/rails#18304]
It's inelegant to have to do foreign key operations outside of the change/create table block.  Foreign keys should be supported the same way as indexes.  What we have to do now, as far as I can tell:

    def change
      change_table :folders do |t|
        t.references :document
      end
      add_foreign_key :folders, :documents
    end

The foreigner gem had a foreign_key method for the block so it could be expressed like this, which I think is cleaner:

    def change
      change_table :folders do |t|
        t.references :document
        t.foreign_key :documents
      end
    end

**Comment by rafaelfranca** [comment]
Thank you so much for the issue but we don't take feature request on the issue tracker. We recommend you to try to implement the feature and send us a pull request or if you are in doubt if the feature will be accepts ask in Rails Core mailing list for feedback.

**Comment by brainopia** [comment]
@wlipa Hello, on rails master you can achieve your goal in one of two ways:

```ruby
def change
  change_table :folders do |t|
    t.references :document, foreign_key: true
  end
end
```

or

```ruby
def change
  change_table :folders do |t|
    t.foreign_key :document
  end
end
```

**Comment by wlipa** [comment]
Sounds great, thanks.
