### ISSUE TITLE
Migration silently fails when altering SQLite sequence

### ISSUE THREAD

**Issue by wiggly** [rails/rails#18302]
I am on a project to migrate a system and so we need to leave some headroom on all new IDs for models since migrated data from the old system already occupies a lot of the ID space.

I can easily set the sequence start for postgres/mysql in an AR migration but it silently fails for SQLite.

The SQL below succeeds on a plain SQLite db from the console but silently fails, and makes subsequent changes in the same migration fail, if performed from an ActiveRecord Migration.

I have tried a number of things that I thought might have a chance of affecting things such as setting ddl trans off but to no avail.

UPDATE sqlite_sequence SET seq = 1000 WHERE name = 'cats';

I have created an empty Rails 4 project that demonstrates the problem [here](https://github.com/wiggly/test-sqlite-seq-migration)

**Comment by prathamesh-sonpatki** [comment]
```ruby
irb(main):016:0> sql
=> "INSERT INTO cats ( name ) VALUES ( 'MIGRATION 1' );UPDATE sqlite_sequence SET seq = 100000 WHERE name = 'cats';INSERT INTO cats ( name ) VALUES ( 'MIGRATION 2' );\n\n"
irb(main):017:0> ActiveRecord::Base.connection.execute sql
   (1.8ms)  INSERT INTO cats ( name ) VALUES ( 'MIGRATION 1' );UPDATE sqlite_sequence SET seq = 100000 WHERE name = 'cats';INSERT INTO cats ( name ) VALUES ( 'MIGRATION 2' );


=> []
irb(main):018:0> Cat.last
  Cat Load (0.2ms)  SELECT  "cats".* FROM "cats"  ORDER BY "cats"."id" DESC LIMIT 1
=> #<Cat id: 10006, name: "MIGRATION 1">
irb(main):019:0> Cat.create! name: 'gorbypuff'
   (0.1ms)  begin transaction
  SQL (0.3ms)  INSERT INTO "cats" ("name") VALUES (?)  [["name", "gorbypuff"]]
   (1.5ms)  commit transaction
=> #<Cat id: 10007, name: "gorbypuff">
irb(main):020:0>
```

This query fails with ActiveRecord::Base.connection.execute also with sqlite3.

**Comment by prathamesh-sonpatki** [comment]
I don't think sqlite3 gem allows multiple queries in the same call to `execute`.

Even `sql = "INSERT INTO numbers ( name ) VALUES ( 'MIGRATION 1' );INSERT INTO numbers ( name ) VALUES ( 'MIGRATION 2' );"` this does not run second query. Only first query is run.

**Comment by rafaelfranca** [comment]
Yeah, it definitely don't support this for security reason.
