### ISSUE TITLE
Nested model size is +1 bigger when you declare it inside controller

### ISSUE THREAD

**Issue by manorie** [rails/rails#18311]
I have two models, 

~~~ruby
class Donkey < ActiveRecord::Base
  has_many :comments, dependent: :destroy
  validates :name, :surname, :age, presence: true 
end

class Comment < ActiveRecord::Base
  belongs_to :donkey
  validates :comment, :commenter, presence: true
end
~~~

The problem I have found is,

When you declare, `@comment = @donkey.comments.build` inside the Donkey controller, the size of `@donkey.comments.size` is +1 bigger. For instance if we do not have any comment record, the size of `@donkey.comments` is 1.

I tried to add records from rails console and inspected size there, problem disappeared, so I found that the problem is inside controller. 

New comment declaration mixes with previous records.

Hence, when I declare it inside form_for:

~~~html+erb
<%= form_for([@donkey, @donkey.comments.build]) do |f| %>
~~~

versus

~~~html+erb
<%= form_for([@donkey, @comment]) do |f| %>
~~~

that problem disappears. But `@donkey.comments.size` is still + 1 even if I escape that in my view file with `<% unless comment.new_record? %>`, when you declare comment inside controller.

Why do we have to declare `@comment` inside view file to solve this problem rather than controller. Why does new nil comment mix with previous records? I think `@donkey.comments` must include only recorded objects.

Thanks for your time and making rails better everyday.

**Comment by manorie** [comment]
<label>Active Record</label>

**Comment by al2o3cr** [comment]
`build` adds the newly-constructed, not-yet-saved record to the collection. `size` reflects the number of records in the association, saved or not. This isn't a bug.

One workaround is to instead use `@donkey.comments.count`, which will run a SQL `COUNT` statement which *won't* see the unsaved record.

**Comment by manorie** [comment]
Thank you very much for your explanation. I was trying to understand work arounds and posted that here maybe it may come strange to you too. Sorry for taking your time.

**Comment by robin850** [comment]
Closing this then ; thank you guys!
