### ISSUE TITLE
Enhance protect_from_forgery with inline skipping

### ISSUE THREAD

**Issue by dhh** [rails/rails#18329]
Currently we want you to do this to only partially apply the forgery protection:

```ruby
class FooController < ApplicationController
  protect_from_forgery except: :index
  skip_before_action :verify_authenticity_token, if: -> { request.format.json? }
end
```
That's needlessly meddling with the forgery implementation. Let's just do this:

```ruby
class FooController < ApplicationController
  protect_from_forgery except: :index, unless: -> { request.format.json? }
end
```

The unless argument can be either a symbol reference to a method or a proc.

**Comment by simi** [comment]
Looks like it should be easy to implement. I'm trying to bring some initial code.

**Comment by dhh** [comment]
Thanks, Josef! Yeah, I don’t think there are any bones in it.

**Comment by simi** [comment]
Actually this works but it is not documented. `protect_from_forgery` is passing `options` direct to `prepend_before_action`.

With this rails source code change:
```diff
diff --git a/actionpack/test/controller/request_forgery_protection_test.rb b/actionpack/test/controller/request_forgery_protection_test.rb
index 3e0bfe8..417863d 100644
--- a/actionpack/test/controller/request_forgery_protection_test.rb
+++ b/actionpack/test/controller/request_forgery_protection_test.rb
@@ -81,7 +81,7 @@ end
 
 class RequestForgeryProtectionControllerUsingException < ActionController::Base
   include RequestForgeryProtectionActions
-  protect_from_forgery :only => %w(index meta same_origin_js negotiate_same_origin), :with => :exception
+  protect_from_forgery :only => %w(index meta same_origin_js negotiate_same_origin), :with => :exception, if: -> {false}
 end
 
 class RequestForgeryProtectionControllerUsingNullSession < ActionController::Base
```

```
$ ruby -Itest test/controller/request_forgery_protection_test.rb

Run options: --seed 20095

# Running:

..............................................FFFFFFFF.........F......

Finished in 0.607172s, 115.2886 runs/s, 202.5786 assertions/s.

  1) Failure:
RequestForgeryProtectionControllerUsingExceptionTest#test_should_not_allow_delete_without_token [test/controller/request_forgery_protection_test.rb:236]:
ActionController::InvalidAuthenticityToken expected but nothing was raised.


  2) Failure:
RequestForgeryProtectionControllerUsingExceptionTest#test_should_not_allow_post_without_token_irrespective_of_format [test/controller/request_forgery_protection_test.rb:224]:
ActionController::InvalidAuthenticityToken expected but nothing was raised.


  3) Failure:
RequestForgeryProtectionControllerUsingExceptionTest#test_should_not_allow_patch_without_token [test/controller/request_forgery_protection_test.rb:228]:
ActionController::InvalidAuthenticityToken expected but nothing was raised.


  4) Failure:
RequestForgeryProtectionControllerUsingExceptionTest#test_should_not_allow_post_without_token [test/controller/request_forgery_protection_test.rb:220]:
ActionController::InvalidAuthenticityToken expected but nothing was raised.


  5) Failure:
RequestForgeryProtectionControllerUsingExceptionTest#test_should_not_allow_put_without_token [test/controller/request_forgery_protection_test.rb:232]:
ActionController::InvalidAuthenticityToken expected but nothing was raised.


  6) Failure:
RequestForgeryProtectionControllerUsingExceptionTest#test_should_not_warn_if_csrf_logging_disabled [test/controller/request_forgery_protection_test.rb:301]:
ActionController::InvalidAuthenticityToken expected but nothing was raised.


  7) Failure:
RequestForgeryProtectionControllerUsingExceptionTest#test_should_not_allow_xhr_post_without_token [test/controller/request_forgery_protection_test.rb:240]:
ActionController::InvalidAuthenticityToken expected but nothing was raised.


  8) Failure:
RequestForgeryProtectionControllerUsingExceptionTest#test_should_only_allow_same_origin_js_get_with_xhr_header [test/controller/request_forgery_protection_test.rb:311]:
ActionController::InvalidCrossOriginRequest expected but nothing was raised.


  9) Failure:
RequestForgeryProtectionControllerUsingExceptionTest#test_should_warn_on_missing_csrf_token [test/controller/request_forgery_protection_test.rb:285]:
ActionController::InvalidAuthenticityToken expected but nothing was raised.

70 runs, 123 assertions, 9 failures, 0 errors, 0 skips
```

**Comment by dhh** [comment]
Oh? So this is just a documentation issue?

Something else I realized. We prepend verify_authenticity_token as a before filter, which means that you can’t actually use the conditional to rely on anything in previous filters. I don’t think it actually makes sense to prepend. You just want the callback chain to be halted before reaching the action in case of an invalid token.

My specific case is that I want to only apply CRSF protection against requests authenticated with cookies, not, say, oauth. So I need to run the filters that do authentication before the CRSF protection.

**Comment by simi** [comment]
I think current implementation of `protect_from_forgery` works great in 99% of use-cases. You can use lazy evaluation for your use-case or add forgery protection callback and setup it manually via custom macro. 

*I see `before filters` modifying database rows (for example current user last visit) often. IMHO it will be better to keep it prepended to ensure it is called before custom before callbacks.*

**Comment by dhh** [comment]
I can't lazy eval because the evaluation is run when the filter is run, which is before all other filters are run.

What I don't like about prepend is that you have no way of doing anything about that. protect_from_forgery is essentially a macro for adding these filters, so why do we need to do prepend? If someone wants to run it first, just declare it first.

Making a change is of course backwards incompatible. We could do something like `prepend: false` to deal with that.

**Comment by dhh** [comment]
Here's the hack I currently have to do. That's just not reasonable for something that is a common use case (that CRSF protection is only for cookie-authenticated/web requests):

```ruby
module ForgeryProtection
  extend ActiveSupport::Concern
  
  included do
    protect_from_forgery with: :exception
    
    # protect_from_forgery adds the verify_authenticity_token callback as a prepend, 
    # which means it runs before we have figured out which authentication method is used.
    # This swapperoo ensures the callback isn't called until after the authentication method
    # is known.
    skip_before_action :verify_authenticity_token
    before_action :verify_authenticity_token, if: -> { authenticated_by.cookie? }
  end
end
```

**Comment by simi** [comment]
It can be achieved very easily here with `prepend: false` [here](https://github.com/rails/rails/blob/master/actionpack/lib/action_controller/metal/request_forgery_protection.rb#L99). But maybe `prepend: true` should be useful for `before_action` also.

**Comment by dhh** [comment]
Not sure I follow? prepend: true is essentially what we have now, no? But yeah, I like having a `prepend: false` option for now.

**Comment by simi** [comment]
Actually `prepend: true` is already option for `set_callback`. It will be very easy to switch to `before_action` and make `prepend: true` as default option inside `protect_from_forgery`.

**Comment by dhh** [comment]
:+1: – let's make it so.
