### ISSUE TITLE
ActiveRecord::DangerousAttributeError - model_name is defined by Active Record. Check to make sure that you don't have an attribute or method with the same name

### ISSUE THREAD

**Issue by anbublacky** [rails/rails#18338]
While upgrading from 4.1 to 4.2, i'm getting following error

ActiveRecord::DangerousAttributeError - model_name is defined by Active Record. Check to make sure that you don't have an attribute or method with the same name.:
  activerecord (4.2.0) lib/active_record/attribute_methods.rb:115:in `instance_method_already_implemented?'
  activemodel (4.2.0) lib/active_model/attribute_methods.rb:288:in `block in define_attribute_method'
  activemodel (4.2.0) lib/active_model/attribute_methods.rb:285:in `define_attribute_method'
  activemodel (4.2.0) lib/active_model/attribute_methods.rb:252:in `block in define_attribute_methods'
  activemodel (4.2.0) lib/active_model/attribute_methods.rb:252:in `define_attribute_methods'

Whenever TestDrive.new or ModelDefinition.new is executed i'm getting the above error, are TestDrive and ModelDefinition used by activerecord?

**Comment by yuki24** [comment]
You are probably using `model_name` _column_ and `model_name` _method_ is also defined by Active Record.

**Comment by anbublacky** [comment]
Hi,
Yes I'm using model_name as column in my table, I'm trying to migrate from 4.1. to 4.2, it is ok i cannot do anything now except to change the column, but I tried to create new app, while creating the scaffold itself it should show error right, after migration while accessing in browser it shows error.

**Comment by senny** [comment]
@anbublacky it's correct. We added protection that detects when you use a column name, which has the same name as a method already defined on `ActiveRecord::Base`. This is to prevent broken functionality when parts of Rails rely on certain contracts for methods (URL generation and translation in the case of `model_name`).

/cc @chancancode

**Comment by nishu** [comment]
Is there a way to permit this for legacy databases?

**Comment by senny** [comment]
@nishu there's no supported way around this behavior. You "could" monkey patch [this method](https://github.com/rails/rails/blob/6d72485b6977804a872dcfa5d7ade2cec74c768e/activerecord/lib/active_record/attribute_methods.rb#L131-L133) but there's no guarantee that you'll end up with working code.

**Comment by nishu** [comment]
Thanks @senny.  Monkey patch should not break other functionality for my use case.

**Comment by gf59ru** [comment]
Hi, i'm gets same error in new rails project that use existing database
I can't change db structure, inclulding column names, because this database is using by other not-rails projects
Can i bypass this error somehow? Column aliases or any other ways?

**Comment by peterwillcn** [comment]
gem 'safe_attributes'

**Comment by peterwillcn** [comment]
def bad_attribute_names(*attrs)
        @bad_attribute_names ||= lambda {
          methods = Array.new(attrs.collect { |x| x.to_sym })
          methods += ActiveRecord::Base.public_instance_methods.collect { |x| x.to_sym }
          methods += ActiveRecord::Base.protected_instance_methods.collect { |x| x.to_sym }
          methods += ActiveRecord::Base.private_instance_methods.collect { |x| x.to_sym }
          methods -= [:id]
          return methods
        }.call
      end

**Comment by manas11** [comment]
Rails 6.1.1 onwards gem 'safe_attributed' doesn't work. Its kinda obsolete

**Comment by figarrido** [comment]
I was connecting to a legacy database with the column `changes` and rails throw this errors, I didn't need the column so I used 
```ruby
class Model
  ...
  self.ignored_columns = [:changes]
end
```
I know this is not applicable to all, but in case you don't need the column, here is your solution
