### ISSUE TITLE
Remove ActionController::HideActions

### ISSUE THREAD

**Issue by dhh** [rails/rails#18336]
The whole concept of hidden actions was when we allowed all public methods of a controller to be auto-available through the router. We no longer do. So strip it out. Since it actually doesn't even do anything at this point, I wonder if we even need a deprecation step.

**Comment by rafaelfranca** [comment]
I don't know why but we are using these methods at devise today.

https://github.com/plataformatec/devise/blob/master/app/controllers/devise_controller.rb#L9

@lucasmazza @josevalim @carlosantoniodasilva do you remember?

**Comment by dhh** [comment]
Probably legacy from when we did route directly to actions?

**Comment by aditya-kapoor** [comment]
the code on Devise is added in this [commit](https://github.com/plataformatec/devise/commit/d9df6326) about three years ago. 
The definition for method [`action_methods`](https://github.com/rails/rails/blob/master/actionpack/lib/abstract_controller/base.rb#L78) would be in jeopardy.

**Comment by simi** [comment]
@aditya-kapoor it was added much earlier. https://github.com/plataformatec/devise/commit/dede8af5b099d79b1478e2a54e3aeb2c63c881b8

**Comment by cristianbica** [comment]
For controllers `action_methods` / `hide_actions` doesn't make much sense now but we probably should deprecate (on GH there are [9k ruby files](https://github.com/search?l=ruby&p=1&q=hide_action&ref=reposearch&type=Code&utf8=✓) that have `hide_action`). 
For mailers we use `action_methods` do determine if we should wrap in `MessageDelivery`. This is pretty sensitive as any public instance method is considered a mailer and will be wrapped inside `MessageDelivery`. People usually have some helper instance methods and they can easy forget to mark them protected. While working on the ActiveJob I was thinking on a way to mark the mailer methods more explicit. Some ideas I had:
```ruby
class UserMailer < ActionMailer::Base
  mailer def notification(user)
  end
  #or
  mailer :notification do |user|
  end
end
```

**Comment by carlosantoniodasilva** [comment]
Controllers and mailers all mark all public methods as "actions", so if someone ends up adding a public method that should work as a helper and not an action in these cases, they could be busted on both sides.

In short, I think the idea of public methods being actions works just fine as an api.

**Comment by dhh** [comment]
:+1: to public/private being the split rather than hide_actions.

**Comment by brainopia** [comment]
@dhh should `hide_action` be deprecated first?

**Comment by dhh** [comment]
If it doesn’t do anything at the moment, I think it should just be removed.

**Comment by dhh** [comment]
Closed by #18371.

**Comment by aditya-kapoor** [comment]
@dhh should we also deprecate the `action_methods`?

**Comment by dhh** [comment]
Do you have a use case where people would be using that for something that's not a no-op?
