### ISSUE TITLE
Bug in after_commit

### ISSUE THREAD

**Issue by mdemare** [rails/rails#18346]
In 4.2.0, calling `save` in the `after_commit` `on: :create` handler, also triggers the after_commit handler, even though the save is not a `create` anymore, but an `update`. This is a regression from the 4.1 branch. See the following code:

```
# Table name: counters
#
#  id                    :integer          not null, primary key
#  count                 :integer
class Counter < ActiveRecord::Base
  after_commit :kaboom, on: :create

  def kaboom
    self.count += 1
    save!
  end
end
Counter.create count: 0
```

**Comment by rafaelfranca** [comment]
I don't think this is a regression from 4.1 branch. This behavior is happening since Rails 3.2.

This is a dup of #14493.
