### ISSUE TITLE
Pry debugger instance is not using the Model.inspect methods anymore for final output.

### ISSUE THREAD

**Issue by mwesigwa** [rails/rails#18353]
My team recently upgraded to Rails 4.2 and I noticed that the inspect methods that we had defined on our models were not being called before displaying the final output in Pry. Take the following example:

```ruby 
class Foo < ActiveRecord::Base
end
Rails(4.1) Foo.new                  #=> "#<Foo:0x0300c868>"
Rails(4.2) Foo.new                  #=> "#<Foo:0x0300c868>"

class Foo < ActiveRecord::Base
  def inspect
     "Foo is awesome"
  end
end
Rails(4.1) Foo.new                  #=> "Foo is awesome"
Rails(4.2) Foo.new                  #=> "#<Foo:0x0300c868>"
```
Is this the new behavior going forward? How do we restore the previous behavior?

Thanks,

**Comment by sgrif** [comment]
Please open an issue on pry, this doesn't appear to be a Rails bug.

**Comment by rafaelfranca** [comment]
See https://github.com/rails/rails/pull/15172#issuecomment-69248584

**Comment by katxiao** [comment]
This seems to be fixed. /cc @tenderlove

**Comment by tenderlove** [comment]
I think this is fixed, so I'm closing it.  If it's not fixed, please let me know.
