### ISSUE TITLE
serialized attributes incorrectly report as changed for same values with different yaml

### ISSUE THREAD

**Issue by seanwalbran** [rails/rails#18352]
Rails 4.2.0 (and master) is incorrectly reporting that serialized attributes have `changed?` for objects that have been freshly loaded from the database.  It appears that this is due to the data having been persisted under previous versions of rails, which generated equivalent, but not identical, YAML string representations of the data.  

Standalone reproduction gists for master and 4.2.0: https://gist.github.com/seanwalbran/2b392b97677bb41b5784
 
The cause appears to be the changed-ness being determined by comparing the encoded values, rather than the decoded values, here: https://github.com/rails/rails/blob/00dad0343b3aa6cf019afe3c727d4a3d95ddc383/activerecord/lib/active_record/type/serialized.rb#L32

**Comment by sgrif** [comment]
The only way to fix this would be to decode multiple times to perform the comparison, which is extremely expensive for most types. I don't want to introduce a performance regression for an edge case like this. I'm not sure there's a good solution here, short of recommending that you re-persist the affected records from the console.

**Comment by seanwalbran** [comment]
@sgrif How stable do you believe that this will remain going forward?  It seems to me like this is could be an annoyingly recurring issue, with people needing to migrate database records every time e.g. yaml gems change their formatting preferences.

**Comment by sgrif** [comment]
The plan is to start moving away from `serialize` and using YAML for this, in general. I don't disagree with your statement, I just don't have a solution that I believe could work.

**Comment by seanwalbran** [comment]
@sgrif Since the encoded comparison is fast and reliable for a not-changed check (which is presumably also the most frequent scenario), and necessary but not sufficient for the (less-frequent) changed-check, what would you think about doing something like the below, as a 'usually fast but always correct' compromise?

```ruby
def changed_in_place?(raw_old_value, value)
  return false if value.nil?
  return false unless subtype.changed_in_place?(raw_old_value, type_cast_for_database(value))
  return false if type_cast_from_database(raw_old_value) == value
  true
end
```

**Comment by matthewd** [comment]
I think the use of the serialized format was pretty deliberate: the only thing we can definitively answer is whether the currently stored value exactly matches what we'd store now, given the opportunity.

Otherwise, we're trusting that `==` is distinguishing everything the application cares about. And that assumption has potential to break down before we even look beyond Hash.

Also, tanking performance for all writes forever doesn't seem likely to excite many people. If you have a particular use case which calls for a gentler definition of "unchanged", I believe we provide all the primitives you need to build it.

**Comment by seanwalbran** [comment]
@matthewd Ok, if the intent of `changed?` is 'would write something different' instead of 'has a different value', fair enough, I can just do `value_changed? && value_was != value` to get the latter when necessary.  Thanks to you and @sgrif for looking into it.
