### ISSUE TITLE
Is it safe to remove Foreigner from Gemfile on upgrading to Rails 4.2?

### ISSUE THREAD

**Issue by andreynering** [rails/rails#18360]
Many people used [foreigner](https://github.com/matthuhiggins/foreigner) to have foreign key support in Rails <= 4.1.

I just upgraded an app to 4.2, removed foreigner and had no problems using the default support. But I'm not certain if it is safe in 100% of the cases (when using database specific options, etc).

I think we should have a subsection [in the "upgrading" guides](http://edgeguides.rubyonrails.org/upgrading_ruby_on_rails.html#upgrading-from-rails-4-1-to-rails-4-2) informing if removing the gem on upgrading is the right thing to do or not.

**Comment by senny** [comment]
@andreynering the support we shipped with 4.2 does not have all the features that foreigner had. We also follow different conventions when naming the foreign keys.

It's safe as long as you don't use these specific options and don't care about the key names. A possible sanity check would be to:

1. remove `foreigner` from the `Gemfile` and `bundle`
2. perform `bin/rake db:schema:dump`
3. Check the changes in `db/schema.rb`-

**Comment by andreynering** [comment]
@senny Yes, in my test, all foreign keys were dumped in `schema.rb` file, but with a slight different syntax: without the constraint names.

> We also follow different conventions when naming the foreign keys.

Won't this cause problems when trying to rollback migrations witch adds foreign keys?

Also, won't https://github.com/rails/rails/issues/18146 cause problems in the future?

**Comment by senny** [comment]
Where do you see issues with #18146 ? Generally speaking, rolling back and re-applying the migration will leave you with different foreign key names (unless you explicitly specify a name using the `:name` option).

**Comment by andreynering** [comment]
@senny I thought maybe Rails relied on the naming convention to do things like removing a foreign key.

About https://github.com/rails/rails/issues/18146, I was talking about syntax. But now I read it better and, if the version control be implemented, it should not be a problem.

I made a PR about this: https://github.com/rails/rails/pull/18363

**Comment by senny** [comment]
I think there is no actionable task here. Going to close this issue.

@andreynering thank you for reporting.
