### ISSUE TITLE
Incorrect SQL on a STI model using a has_many :through relation

### ISSUE THREAD

**Issue by naiyt** [rails/rails#18375]
I believe this issue is related to #12474. However, #12659 supposedly fixes that issue, but is not resolving mine, which is why I'm opening another issue.

[Here is my self contained gist demonstrating the issue](https://gist.github.com/naiyt/7a761b44abc28f9157ff). The problem is occurring for me on all versions of Rails 4.0, 4.1, and 4.2. The issue does not occur on Rails 3, versions >= 3.2.12.

As shown on the gist, I have a parent table with one STI child model. The parent has a `:has_many :through` relation with another table. On Rails 4, the `update_all` I'm using inside the Parent model (as shown in the gist linked above) is generating invalid SQL:

``` sql
UPDATE `other_models`
INNER JOIN `join_child_others` 
ON `other_models`.`id` = `join_child_others`.`other_model_id`
SET `other_models`.`active_id` = 1
WHERE `join_child_others`.`parent_id` = NULL
```

The problem is in `WHERE `join_child_others`.`parent_id` = NULL`. Rails 3 has an identical query, except the `where` condition specifies `WHERE `join_child_others`.`parent_id` = 1`.

Just calling `.to_sql` on the Parent's `other_models` also generates SQL in Rails 4 with the `where` clause: `WHERE `join_child_others`.`parent_id` = 1`.

**Comment by dfpfernandez** [comment]
I'm not sure if this is a bug, you have the has_many relation in the Child model instead of Parent. And you are trying to update the related object from Parent model.
```Ruby
class Parent < ActiveRecord::Base
  has_many :join_child_others
  after_create :set_active_id
 
  def set_active_id
    other_models.update_all(:active_id => id)
  end
end
 
class Child < Parent
  has_many :other_models, :through => :join_child_others
end
```

If you change the has_many relation to the Parent model, it should work.

```Ruby
class Parent < ActiveRecord::Base
  has_many :join_child_others
  has_many :other_models, :through => :join_child_others
  after_create :set_active_id
 
  def set_active_id
    other_models.update_all(:active_id => id)
  end
end
 
class Child < Parent
  ...
end
```

**Comment by naiyt** [comment]
There is a reason that the `has_many` is on the child in our situation, but unfortunately my example doesn't demonstrate that. The actual relations are a bit more complex with some other models thrown in as well, but this was the simplest example that I could replicate the problem with. The weird thing is that it worked fine on Rails 3, but not Rails 4, making me think it's a bug.

**Comment by naiyt** [comment]
I can explain a bit more about why we need the relation to the joined table on the child and the relation to the joining table on the parent if anybody needs it. (Although I'm not sure that's necessary for the bug report.) I know it's a bit weird, but does seem like a regression since Rails 3 supported it.

[I created a failing test here](https://github.com/naiyt/rails/compare/fix_18375). (My first Rails commit, so that test may be bad.) I'm going to dive in a bit and see if I can isolate where this is happening.

**Comment by 42001983** [comment]
It mighat be wife and son

**Comment by mfazekas** [comment]
@naiyt That test has some issues:
1. https://github.com/rails/rails/compare/master...naiyt:fix_18375#diff-95d3dfc38be7275845454d444b0826f9R906:
> t.boolean :answer
should b integer not boolean

2. You do reload, the test where you read values but not in after_create where you set them. If you're verifying the semantics before after reload you should do an assert for that. 
https://github.com/rails/rails/compare/master...naiyt:fix_18375#diff-79fcb40bc6f590b0fb4ea54f891f3114R1167
Also i don't think this behaviour is related on sti.

**Comment by mfazekas** [comment]
So what his issue boil downs to is the order of after_create and the has_many declarations.
So code like this will not work:
```ruby
class Parent < ActiveRecord::Base
  has_many :join_child_others
  after_create :set_active_id
  has_many :other_models, :through => :join_child_others
  #after_create :set_active_id

  def set_active_id
    other_models.update_all(:active_id => id)
  end
end
```

I assume active record unified after create callbacks with save of has_many on create. So when ```set_active_id``` called ```other_models``` is not yet persisted to db, therefore you cannot yet use update_all. Something like this might work but there might be more idiomatic solution:
```ruby
  def set_active_id
    other_models.create!
    other_models.reload.scope.update_all(:active_id => id)
    true
  end
```
