### ISSUE TITLE
Extra “be” in Configuring a Database Guide

### ISSUE THREAD

**Issue by joepasq** [rails/rails#18372]
in [Configuring a Database](http://guides.rubyonrails.org/configuring.html#configuring-a-database) section 3.13.3 talks about configuring PostgreSQL and states 

> You can be disable prepared statements by setting `prepared_statements` to `false`:

I would remove the “be”.

**Comment by claudiob** [comment]
Thanks @joepasq! 

The code for the guide was fixed and the change will soon be reflected on the site
