### ISSUE TITLE
Rails 3.2.21 `:has_many` behaviour difference when Ruby 2.1.5 and Ruby 2.2.0

### ISSUE THREAD

**Issue by ivar** [rails/rails#18376]
Somehow the `#size` method of an Array returned via a `:has_many through:` association breaks when run under Ruby 2.2.0.  

Rails console with Ruby 2.2.0p0
```
Loading development environment (Rails 3.2.21)
development (main):0 > a = Property::Agent.last
  Property::Agent Load (1.0ms)  SELECT "property_agents".* FROM "property_agents" ORDER BY "property_agents"."id" DESC LIMIT 1
=> #<Property::Agent id: 73624>
development (main):0 > a.geographies
  Geography Load (6.0ms)  SELECT "geographies".* FROM "geographies" INNER JOIN "property_agent_locations" ON "geographies"."id" = "property_agent_locations"."geography_id" WHERE "property_agent_locations"."agent_id" = 73624
=> []
development (main):0 > a.geographies.size
NoMethodError: undefined method `name' for nil:NilClass
from /home/rew/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/activerecord-3.2.21/lib/active_record/associations/has_many_association.rb:58:in `cached_counter_attribute_name'
development (main):0 > a.geographies.count
   (1.2ms)  SELECT COUNT(*) FROM "geographies" INNER JOIN "property_agent_locations" ON "geographies"."id" = "property_agent_locations"."geography_id" WHERE "property_agent_locations"."agent_id" = 73624
=> 0
development (main):0 > a.geographies.try(:size)
=> 0
development (main):0 > a.geographies.class
=> Array
development (main):0 > ar = []
=> []
development (main):0 > ar.size
=> 0
```

and to sanity check, here's using ruby 2.1.5p273
```
Loading development environment (Rails 3.2.21)
development (main):0 > a = Property::Agent.last
  Property::Agent Load (148.3ms)  SELECT "property_agents".* FROM "property_agents" ORDER BY "property_agents"."id" DESC LIMIT 1
=> #<Property::Agent id: 73624>
development (main):0 > a.geographies
  Geography Load (20.8ms)  SELECT "geographies".* FROM "geographies" INNER JOIN "property_agent_locations" ON "geographies"."id" = "property_agent_locations"."geography_id" WHERE "property_agent_locations"."agent_id" = 73624
=> []
development (main):0 > a.geographies.size
=> 0
development (main):0 > a.geographies.count
   (0.8ms)  SELECT COUNT(*) FROM "geographies" INNER JOIN "property_agent_locations" ON "geographies"."id" = "property_agent_locations"."geography_id" WHERE "property_agent_locations"."agent_id" = 73624
=> 0
```

**Comment by rafaelfranca** [comment]
Rails 3 doesn't support Ruby 2.2 officially.

**Comment by rafaelfranca** [comment]
Could you check 3-2-stable branch?

**Comment by ivar** [comment]
@rafaelfranca I tested with 37f2defa99 (`3-2-stable` HEAD)  and the issue is fixed!
Thanks so much for your time support us laggards.

**Comment by runephilosof** [comment]
@rafaelfranca You say that rails 3 doesn't support Ruby 2.2 officially. I cannot find that anywhere. 

The only reference to ruby versions I can find is in the getting started guide, where it says to use 1.9.3 or higher.
http://guides.rubyonrails.org/v3.2.21/getting_started.html

**Comment by joshuapinter** [comment]
I concur that the `3-2-stable` branch of Rails fixes the problem.

Also, related to Issue #18991.

**Comment by espen** [comment]
I know Rails 3.x is only for security patches but just wanted to say that I'm still seeing this problem with the 3-2-stable branch.

Another strange thing is that while I have this problem locally I cannot reproduce this problem in production on Heroku. Using Ruby 2.2.2. Using 2.1.6 works.

I also tried changing to reflection() as in https://github.com/rails/rails/commit/e88da370f190cabd1e9750c5b3531735950ab415 but without any luck. 3-2-stable uses self.reflection https://github.com/rails/rails/commit/3a30b12c774dfaa72acfe520e823374131631ea9

**Comment by gmoore** [comment]
@espen We were also having this issue locally but could not reproduce on Heroku. The problem was the bullet gem which is enabled in development but not in other envs. I couldn't get any version of bullet to work for us so we took it out for now.

**Comment by espen** [comment]
Ah, well that makes sense looking at https://github.com/flyerhzm/bullet/pull/238. Thanks for the info.

**Comment by dgilperez** [comment]
I also got hit by this on Rails 4.1.12 and Ruby 2.2, and solved it upgrading bullet to last version. Thanks @espen !
