### ISSUE TITLE
AR#find_sti_class rescues name error and hides error messages

### ISSUE THREAD

**Issue by AMHOL** [rails/rails#18382]
I recently came across the following error when using STI in Rails 4.0.4

```
ActiveRecord::SubclassNotFound: The single-table inheritance mechanism failed to locate the subclass: 'CompanyManager'. This error is raised because the column 'type' is reserved for storing the class in case of inheritance. Please rename this column if you didn't intend it to be used for storing the inheritance class or overwrite Permission.inheritance_column to use another column for that information.
```

However, I knew that the class existed and the type field was correct, after debugging with some puts statements in the AR gem code, I found that the real issue was an included module nested within two namespaces, the second of which clashed with a class in the global namespace - so in some scenarios, there was a load error, however, that was hidden due to the rescue statement referenced below.

https://github.com/rails/rails/blob/master/activerecord/lib/active_record/inheritance.rb#L175

I would have submitted a PR, but I can't think of a good solution to this at the moment.

**Comment by tenderlove** [comment]
Can you provide a test or something?  Maybe we can think up a better solution when we see the issue in action.

**Comment by AMHOL** [comment]
@tenderlove, I will try to get an example posted back soon.

**Comment by senny** [comment]
It's been months without feedback. I'm going to close this issue.

If you still experience this problem on a supported Rails version `4.1.` or `4.2.` please post a reproduction case to help us debug the problem. You can use [this script](https://github.com/rails/rails/blob/master/guides/bug_report_templates/active_record_gem.rb) as a starting point.

**Comment by Galiullinko** [comment]
Hey guys. I met the same bug(?) as the issue creator. Rails 5.1.4, Ruby 2.1.4. 
In my case, I have `Publisher::CrmIntegration` model and STI subclass `Publisher::CrmIntegration::Intercom`. There I had constant `CLIENT = Intercom::Client.new(token: Rails.application.secrets.intercom_api_key)`.
So, when I tried to create `Publisher::CrmIntegration::Intercom` object, I got 
```
ActiveRecord::SubclassNotFound: The single-table inheritance mechanism failed to locate the s
ubclass: 'Publisher::CrmIntegration::Intercom'. This error is raised because the column 'type
' is reserved for storing the class in case of inheritance. Please rename this column if you 
didn't intend it to be used for storing the inheritance class or overwrite Publisher::CrmInte
gration.inheritance_column to use another column for that information.
from /home/arthurka_o/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/activerecord-5.1.4/lib/a
ctive_record/inheritance.rb:196:in `rescue in find_sti_class'
```
But I was sure that path for class and naming were okay. I checked `find_sti_class` and tried to call ` ActiveSupport::Dependencies.constantize('Publisher::CrmIntegration::Intercom'
)`. It raised the error 
```
NameError: uninitialized constant Publisher::CrmIntegration::Intercom::Client
from .../app/models/publisher/crm_integration/intercom.rb:3:in `<class:Intercom>'
```
After that I knew what was a problem, but I think `ActiveRecord::SubclassNotFound` error shouldn't fully rewrite original error from class. It confuses.
