### ISSUE TITLE
ActiveRecord serialize JSON produces YAML

### ISSUE THREAD

**Issue by PeterBengtson** [rails/rails#18385]
The following stores serialized data as YAML rather than JSON: 

`class Foo < ActiveRecord::Base`
    `serialize :bar, JSON`
`end`

Reading back the contents then results in a JSON parse error. Thus, it seems that it's only the serialization which is in error. However, this is serious as it breaks existing applications.

**Comment by claudiob** [comment]
@PeterBengtson hello! :grinning: 

Could you provide some code to reproduce your error? 
I tried the following code and did not experience any exception… please let me know what I'm missing.
Thanks!

---
```bash
~/code$ rails new tmp
      create  
      create  README.rdoc
      [...]
         run  bundle install

~/code$ cd tmp/

~/code/tmp$ rails g scaffold article title
      invoke  active_record
      [...]
      create    app/assets/stylesheets/scaffolds.scss

~/code/tmp$ rake db:create db:migrate
      == 20150107190500 CreateArticles: migrating ===================================
      -- create_table(:articles)
         -> 0.0009s
      == 20150107190500 CreateArticles: migrated (0.0010s) ==========================

~/code/tmp$ vi app/models/article.rb 
      # add serialize :title, JSON

~/code/tmp$ rc
    Loading development environment (Rails 4.2.0)

    irb(main):002:0> article = Article.create! title: {h1: 'Hello', h2: 'World'}
       (0.0ms)  begin transaction
      SQL (0.3ms)  INSERT INTO "articles" ("title", "created_at", "updated_at") VALUES (?, ?, ?)  [["title", "{\"h1\":\"Hello\",\"h2\":\"World\"}"], ["created_at", "2015-01-07 19:06:25.053573"], ["updated_at", "2015-01-07 19:06:25.053573"]]
       (0.8ms)  commit transaction
    => #<Article id: 1, title: {"h1"=>"Hello", "h2"=>"World"}, created_at: "2015-01-07 19:06:25", updated_at: "2015-01-07 19:06:25">

    irb(main):003:0> Article.first.title
      Article Load (0.3ms)  SELECT  "articles".* FROM "articles"  ORDER BY "articles"."id" ASC LIMIT 1
    => {"h1"=>"Hello", "h2"=>"World"}
```

**Comment by chancancode** [comment]
Yes, please try to isolate your issue in this format and we will take a look: https://github.com/rails/rails/blob/master/guides/bug_report_templates/active_record_gem.rb

**Comment by elciok** [comment]
I have the same issue. Apparently, it happens when using optimistic locking and a not-YAML serialized field in the same model. 

```ruby
# Activate the gem you are reporting the issue against.
gem 'activerecord', '4.2.0'
require 'active_record'
require 'minitest/autorun'
require 'logger'
require 'json'
require 'sqlite3'

# Ensure backward compatibility with Minitest 4
Minitest::Test = MiniTest::Unit::TestCase unless defined?(Minitest::Test)

# This connection will do for database-independent bug reports.
ActiveRecord::Base.establish_connection(adapter: 'sqlite3', database: ':memory:')
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :posts do |t|
    t.text :comments
    t.integer :lock_version, default: 0, null: false
  end
end

class Post < ActiveRecord::Base
  serialize :comments, JSON
end


class BugTest < Minitest::Test
  def test_serialization_bug
    post = Post.new
    post.comments = ["first", "another one"]
    post.save

    assert_equal 1, Post.all.count
    assert_equal 2, post.comments.size
    assert_equal "first", post.comments[0]
    assert_equal "another one", post.comments[1]

    post.reload
    post.comments = ["changed"]
    post.save

    post.reload #JSON::ParserError should happen here

    assert_equal 1, Post.all.count
    assert_equal 1, post.comments.size
    assert_equal "changed", post.comments[0]
  end
end
```

**Comment by PeterBengtson** [comment]
This is my use case exactly. Thanks, elciok.

**Comment by sgrif** [comment]
Ironically, this has nothing to do with serialize. The type information is coming from the connection adapter in the lock column, rather than the AR subclass which has the proper type information for things like serialized. So the casting behavior occurs thinking that it's a `Type::String` and not a `Type::Serialized`. `Type::String#type_cast_for_database` is a no-op for unrecognized types, so the array goes through to `quote` untouched. `quote` won't know how to handle an array, and it's default behavior is to YAML dump the value for reasons I don't know.

I don't expect this explanation to matter to anyone affected in this thread, I'm just commenting to document a concrete issue which is a result of the current behavior, and is driving the current set of refactorings/changes such as https://github.com/rails/arel/commit/008445d6fd5f825d9b445ac75a7be67f0f7ab52c

**Comment by sgrif** [comment]
Fixed in https://github.com/rails/rails/commit/cb277485f9d78f3661c7103e7b468812cc283223 (Github won't close issues from pushing to 4-2-stable)
