### ISSUE TITLE
ActiveRecord serialize calling coder multiple times

### ISSUE THREAD

**Issue by diegossilveira** [rails/rails#18389]
If you have an ActiveRecord class like this:

```ruby
class Sample < ActiveRecord::Base
  serialize :some_property, CustomSerializer
end
```

and let CustomSerializer be

```ruby
class CustomSerializer

  def self.load(value)
    "some"
  end

  def self.dump(value)
    "some"
  end

end
```
After upgrading to rails 4.2, `CustomSerializer::dump` is being called multiple times when an instance of `Sample` is saved.

**Comment by sgrif** [comment]
This is intentional, and is used to detect mutations. It shouldn't be calling `dump` with the result of previous calls to `dump`, but it will call it multiple times. I'd like to memoize in a few cases where it's safe in the future, but it requires additional refactoring to be possible.

**Comment by apeiros** [comment]
Detecting mutation is fine, but I see a single .create! call dump 7 times and load 27 times. That seems excessive, no?
Loading a record calls load twice, which also doesn't make sense.
Demo (tested against rails 4.2 with sqlite3): https://gist.github.com/apeiros/395f161ca002b0abe666

**Comment by sgrif** [comment]
Yes, it is fixed in 4.2.1

**Comment by apeiros** [comment]
Great! Thanks for your work!

**Comment by felipegs** [comment]
:+1:
