### ISSUE TITLE
Postgresql Adapter can't connect to database

### ISSUE THREAD

**Issue by neosb** [rails/rails#18391]
`CentOS 7`
`Postgresql 9.4`
`ActiveRecord 4.2.0`

connecting to database, effect: `could not connect to server: no such file or directory is the server running locally and accepting connections on unix domain socket "/var/run/postgresql/.s.pgsql.5432"?`

workaround: set `host` to `/tmp`

**Comment by sgrif** [comment]
This is likely an issue with your computer's configuration, not with Rails.
