### ISSUE TITLE
Installing ri documentation for rails-4.2.0 takes a lot on windows 7

### ISSUE THREAD

**Issue by jjgh** [rails/rails#18398]
Ok I'm sure this has been reported multiple times for other Rails / Ruby versions but I just wanted to make it explicit that I'm still seeing the same behaviour with ruby 2.1.5p273 (2014-11-13 revision 48405) [x64-mingw32] on Win 7 x64, while installing rails 4.2 ri documentation...

**Comment by jjgh** [comment]
Ok faceplant. While I was writing this it finished running :)

(still it has to be noted that it took a very high amout of time! )

**Comment by andreynering** [comment]
@jjgh I think it is normal to this take some time, specially on Windows.

You can skip it by using:

```
gem install rails --no-ri --no-doc
```

**Comment by jjgh** [comment]
@andreynering  why you think it's normal?

What I feel is, it wouldn't be a surprise if we'd find some bugs that only affect the Windows platform on this part of the code..

**Comment by andreynering** [comment]
@jjgh I think this isn't related to Rails, it is related to [rdoc](https://github.com/rdoc/rdoc). Bundler skips rdoc installation by default for all gems, because it take to much time.

It is slow even in Linux, actually. But is slower in Windows.

**Comment by jjgh** [comment]
Yes I did not want to imply it is a Rails thing but since the only times I happen to see this is when insta

**Comment by rafaelfranca** [comment]
This is not a Rails issue. Our documentation is huge, so the time to compile it is huge, even more on Windows machine.

**Comment by KevinMatte** [comment]
I'd appreciate some sort of progress indicator.

**Comment by Basilmir** [comment]
Ditto! You should see how long it takes to install on an Raspberry Pi 2 (900mhz quad-core ARM + class 10 microsd card :)

**Comment by techsethi** [comment]
I use -V option (verbose) , so that it dumps out some messages, so that I know it is doing something...

**Comment by vedmant** [comment]
Macbook Air, "Installing ri documentation for railties-4.2.6" takes forever, I thought it hung and was thinking of pressing ctr+c...
