### ISSUE TITLE
Fix `rake stats` LOC/M counting when using testing DSL methods

### ISSUE THREAD

**Issue by dhh** [rails/rails#18408]
If you use the following test form:

```ruby
test "something do
  assert
end
```

Then rake stats won't do proper LOC/M calculations. So you end up with something like:

```
| Controller tests     |  1350 |  1037 |      49 |       7 |   0 |   146 |
| Helper tests         |   295 |   221 |       9 |       3 |   0 |    71 |
| Model tests          |  1500 |  1151 |      58 |       9 |   0 |   125 |
| Mailer tests         |    22 |    20 |       3 |       4 |   1 |     3 |
| Job tests            |    48 |    39 |       3 |       0 |   0 |     0 |
| Integration tests    |   141 |   114 |       4 |       1 |   0 |   112 |
```

Let's fix that.

**Comment by brainopia** [comment]
I'd be happy to help.

Do you prefer a small change (fixing a pattern for ruby methods to recognize "test" definition) but it can screw numbers a bit for application code?

Or is it worth the effort to add an additional file type in https://github.com/rails/rails/blob/master/railties/lib/rails/code_statistics_calculator.rb#L4 (for files ending in '_test.rb')?

**Comment by dhh** [comment]
Awesome. I’d like to get the numbers right. So if that means an additional file type, I think that’s just fine :+1:.
