### ISSUE TITLE
attribute_will_change! can add non persisted attributes to arel and try to write them to the database

### ISSUE THREAD

**Issue by dandlezzz** [rails/rails#18407]
When I call attribtue_will_change! on a non-persisted attribute it adds the attribute to the changes hash. Eventually, this hash is sent to arel_attributes_with_values and the code attempts to write to a column that is non-existent. This is new to rails 4.2, I was attempting to use the attribue_will_change! method to trigger various callbacks that run on save, these callbacks take the non-persisted attribute and parse it into its various database fields. Before the rails 4.2 upgrade the code would know that the non-persisted attribute shouldn't be saved and would build the query without it. I'm not sure of the change or the most efficient fix. 
Thanks for the help!

**Comment by sgrif** [comment]
Can you provide an executable test case which demonstrates the issue, using this template? https://github.com/rails/rails/blob/master/guides/bug_report_templates/active_record_master.rb

**Comment by dandlezzz** [comment]
@sgrif Please check out 
https://github.com/dandlezzz/attribute_will_change_bug

I think my inline comments will explain things well enough. I guess I am using the method not as it was intended but I can verify that this did work in previous versions, so it would be nice to fix if possible. 
Thanks so much for your help we are upgrading our app to 4.2 and have almost no issues and really enjoy the features.

**Comment by sgrif** [comment]
What is the use case for calling `attribute_will_change!` on an attribute that won't be persisted?

**Comment by dandlezzz** [comment]
It permits the use of the method non_persisted_attribute_changed? and allows the object to be marked as dirty and trigger any callbacks that you would want as a result of that. In the app I am working on, the non_persisted_attribute has an array that needs to be parsed to it can be saved as part of a polymorphic relationship. So for example
attr_accessor :non_persisted
after_save :do_work_on_non_persisted_people_and_save_them_to_polymorphic_table

def do_work_on_non_persisted_people_and_save_them_to_polymorphic_table
  if non_persisted_changed?

Additionally, it also marks the object as dirty which has similar benefits. Maybe a better fix would be to throw an exception if attribute_will_change! is called on a non-persisted attribute?

**Comment by sgrif** [comment]
Thanks. In the future you don't need a repo with the Gemfile, just a gist with the ruby file is enough.

**Comment by minaguib** [comment]
@dandlezzz For the time being you until released, you can use rails from git, or instead:
```
def changed?
  defined?(@non_persisted_attribute) || super
end
```

**Comment by metaskills** [comment]
I just started testing 4.2.1.rc1 with the SQL Server adapter and noticed that I have a test failing due to this change. The test is `test_partial_update` when saving the `pirate` instance twice using `with_partial_writes`. The reason this test now fails for us is due to and `id` column now being included in the update. 

SQL Server does not allow at any time an identity column to be updated. So we override [attributes_for_update](https://github.com/rails-sqlserver/activerecord-sqlserver-adapter/blob/master/lib/active_record/connection_adapters/sqlserver/core_ext/attribute_methods.rb) to remove columns. This works for that test in 4.2.0, but not after this change. 

So now that we have `persistable_attribute_names` in dirty. The `attributes_for_update` is taking a back seat. Does this feel right? Should I now freedom patch `persistable_attribute_names` too?

**Comment by metaskills** [comment]
Perhaps from an API perspective and if Dirty is included into base after Attributes, then maybe the `persistable_attribute_names` should use the same interface name of `attributes_for_update` and super up too?

**Comment by rafaelfranca** [comment]
@metaskills I was looking at this issue and I don't get how this change could affect your `attributes_for_update` override. The code path is still passing trough `attributes_for_update`. The code that removed `id` from the list of attributes is that `is_identity?` check?

**Comment by rafaelfranca** [comment]
@metaskills also could you open an new issue about this so I can assign for the milestone?

**Comment by metaskills** [comment]
@rafaelfranca Thanks working on creating that issue now. I found that `attributes_for_update` is not called during the `test_partial_update_with_optimistic_locking` test when it was in Rails 4.2.0. Finding out why is kind of perplexing me. Seems unrelated to dirty.rb changes.

**Comment by metaskills** [comment]
@rafaelfranca Done! See issue #19057

**Comment by BintLopez** [comment]
I'm experiencing the issue linked above (https://github.com/plataformatec/devise/issues/3947) with rails 5.1.5 and devise 4.2.

It's only happening when I try to create factories from my seeds file using `rake db/seed`

If I put a breakpoint in my seeds file, I can successfully create a User with FactoryBot. However, if I let `rake db/seed` execute, it throws the following error:

```
rake aborted!
ActiveRecord::StatementInvalid: PG::UndefinedColumn: ERROR:  column users.password does not exist
LINE 1: ...rs"."last_name" = $2 AND "users"."email" = $3 AND "users"."p...
                                                             ^
: SELECT  "users".* FROM "users" WHERE "users"."first_name" = $1 AND "users"."last_name" = $2 AND "users"."email" = $3 AND "users"."password" = $4 ORDER BY "users"."id" ASC LIMIT $5
/my_project/db/seeds.rb:13:in `<top (required)>'

Caused by:
PG::UndefinedColumn: ERROR:  column users.password does not exist
LINE 1: ...rs"."last_name" = $2 AND "users"."email" = $3 AND "users"."p...
                                                             ^
/my_project/db/seeds.rb:13:in `<top (required)>'
Tasks: TOP => db:seed
(See full trace by running task with --trace)
```

Heres what's in my `db/seeds.rb`
```ruby
require "factory_bot"
require "faker"

# Both creation and FactoryBot throw an error when
# running from seeds.

# But if I run the below code from console when
# I hit my breakpoint, it doesn't throw an error
binding.pry

User.create(
	first_name: Faker::Name.first_name,
	last_name: Faker::Name.last_name,
	email: Faker::Internet.email,
	password: Faker::Internet.password
)

FactoryBot.create(:user)
```
