### ISSUE TITLE
Find requests in a scope are cached by Adequate Records

### ISSUE THREAD

**Issue by such** [rails/rails#18419]
Hello,

Please see this executable gist that demonstrates the issue: https://gist.github.com/such/9d52b6b632bd296152a5.

If the first find request on a model is enclosed in a scope, following find requests will keep using the same scope.

Am I doing something unexpected/unsupported here?

**Comment by sgrif** [comment]
This is the expected behavior of the `scoping` method.

**Comment by sgrif** [comment]
Wow I really misread that gist. Sorry, I shouldn't comment on issues before I've had my coffee.

**Comment by dmitry** [comment]
Just want to proof that it doesn't work on 4.2.0:

```
  1) Error:
BugTest#test_adequate_records:
ActiveRecord::RecordNotFound: Couldn't find Post with 'id'=1
    gems/ruby-1.9.3-p547/gems/activerecord-4.2.0/lib/active_record/core.rb:154:in `find'
    a.rb:31:in `test_adequate_records'
```

**Comment by pixeltrix** [comment]
@such can you test it against master/4-2-stable? I think this may have already been fixed by fb160f6

**Comment by sgrif** [comment]
Yeah, this looks like a duplicate of https://github.com/rails/rails/issues/18117 which has already been fixed.

**Comment by such** [comment]
Yeah you're right it works on 4-2-stable. Sorry for that.
I'm closing the issue then.
