### ISSUE TITLE
template dependencies aren't being calculated at all?

### ISSUE THREAD

**Issue by jjb** [rails/rails#18428]
I notice that my caches don't get busted up the hierarchy like I expect them to.

invocations of `rake cache_digests:dependencies` and `rake cache_digests:nested_dependencies` suggest that rails thinks there are no dependencies:

```
➔ rake cache_digests:nested_dependencies TEMPLATE=posts/show
[

]
➔ rake cache_digests:nested_dependencies TEMPLATE=posts/show
[

]
```

poking around in the console agrees with this:

```
app(dev)> finder = ApplicationController.new.lookup_context
app(dev)> d = ActionView::Digestor.new(name: "posts/show", finder: finder)
app(dev)> d.digest
  Cache digest for app/views/posts/show.html.haml: 42bf3496bacfcf84492d8c05d81305fe
=> "42bf3496bacfcf84492d8c05d81305fe"
app(dev)> d.dependencies
=> []
```

However, the posts show template has many dependencies. A couple examples, with names changed:

```haml
= render partial: "myspecialpartial"
```

```haml
= render partial: "discussions/thing", locals: {bar: @foo.bar, baz: nil}
```

rails 4.1.8, haml 4.0.5, `config.assets.digest = true`

----

also discovered this, unsure if related: http://stackoverflow.com/questions/27871275/what-formats-does-actionviewdigestor-new-accept-for-name

**Comment by jjb** [comment]
related: http://stackoverflow.com/questions/27871275/what-formats-does-actionviewdigestor-new-accept-for-name

**Comment by jjb** [comment]
@rafaelfranca @jiripospisil @tvdeyen any ideas?

**Comment by jiripospisil** [comment]
@jjb Could you create a minimal app that reproduces the problem and put it to a repo?

**Comment by jjb** [comment]
Looks like the culprit is my use of haml, and that the haml-rails gem solves the problem.

Sorry for not checking this before submitting the ticket! I had figured haml was supported or would be mentioned in the docs.

BTW the primary docs I found for cache digests is in the readme for the old retired gem. Are there other docs? And/or where would they go. I'll submit a PR to improve them!

**Comment by jjb** [comment]
for anyone who comes across this ticket, here is the initializer I ended up using (or use haml-rails if you want everything else it comes with)

```
raise "might need to update haml rails initializer" unless ::Rails.version.to_s < "4.2"
# https://github.com/indirect/haml-rails/blob/master/lib/haml-rails.rb#L35-L38

require 'action_view/dependency_tracker'
ActionView::DependencyTracker.register_tracker :haml, ActionView::DependencyTracker::ERBTracker
ActionView::Base.cache_template_loading = false if ::Rails.env.development?
```

**Comment by jjb** [comment]
and FWIW, I encountered this problem: cross-referential templates blowing up the rake task but not the server: http://stackoverflow.com/questions/28018187/why-do-my-self-referential-templates-break-cache-digest-calculation-in-the-conso
