### ISSUE TITLE
Rails 4.1 Issue #15920 Arel Regression

### ISSUE THREAD

**Issue by felixbuenemann** [rails/rails#18469]
The changes introduced in Rails 4.1.8 to fix issue #15920 cause some code that works with arel to fail with `TypeError: Cannot visit Arel::SelectManager` that works fine on both 4.1.7(.1) and 4.2.0.

Breaking test case for ActiveRecord: https://gist.github.com/5a964d5c718f576eb101

The code works as expected on 4.1.7/4.1.7.1/4.2.0, but is broken on 4.1.8 and 4.1.9.

**Comment by felixbuenemann** [comment]
One possible solution would be to add a `if bvs.any?` around the call to `arel.ast.grep` introduced in 0d74c5c, but I'm not sure if that the best approach.

**Comment by sgrif** [comment]
The solution is probably to backport https://github.com/rails/arel/commit/590c784a30b13153667f8db7915998d7731e24e5 and then update 4-1-stable to use that code. Please feel free to take the lead on doing that.

**Comment by jaredbeck** [comment]
> The solution is probably to backport rails/arel@590c784 and then update 4-1-stable to use that code. 

Sean, to clarify, when you say "backport arel", you're suggesting a new release of arel, e.g. 5.0.2?

@rafaelfranca I remember reading your kind offer to backport bug fixes to 4-1-stable.  Is the commit Sean mentioned something you'd feel comfortable backporting?

**Comment by rafaelfranca** [comment]
I'd prefer the minimal patch to make it work as before

**Comment by felixbuenemann** [comment]
Thanks, Rafael!
