### ISSUE TITLE
Unnecessary deprecation warning on inclusion of association with both scope and extension

### ISSUE THREAD

**Issue by plehoux** [rails/rails#18468]
Self-contained gist : https://gist.github.com/plehoux/31d73b161199c0bcb317

Above code will trigger following deprecation warning :

> DEPRECATION WARNING: The association scope 'comments' is instance dependent (the scope block takes an argument). Preloading happens before the individual instances are created. This means that there is no instance being passed to the association scope. This will most likely result in broken or incorrect behavior. Joining, Preloading and eager loading of these associations is deprecated and will be removed in the future. (called from test_association_stuff at

Note that the scope ` -> { self }` does not take any argument. There is no warning if we remove the extension block.

**Comment by jaroslawr** [comment]
I was just a little faster: https://github.com/rails/rails/issues/18467 ;)

**Comment by senny** [comment]
Closing in favor of #18467

**Comment by senny** [comment]
@plehoux @jaroslawr thank you for reporting :yellow_heart:
