### ISSUE TITLE
Model.find(:first) no longer works

### ISSUE THREAD

**Issue by nsimmons** [rails/rails#18470]
According to the [docs](http://apidock.com/rails/ActiveRecord/Base/find/class) `Model.find(:first)` is supported. 

Excerpt from the docs:

> Find first - This will return the first record matched by the options used. These options can either be specific conditions or merely an order. If no record can be matched, nil is returned. Use Model.find(:first, *args) or its shortcut Model.first(*args).

But since upgrading to Rails 4.1.8 this appears to be broken (or possibly removed).

See https://gist.github.com/arthurnn/57e789ae1ac8297f47bd for a failing test example.

**Comment by nsimmons** [comment]
@arthurnn for follow up

**Comment by arthurnn** [comment]
This doesn't work on 4-1-stable and 4-2-stable.

**Comment by rafaelfranca** [comment]
I'm almost sure it was deprecated in 4.0.

**Comment by rafaelfranca** [comment]
Yes. It was. See activerecord-deprecated_finders

**Comment by nsimmons** [comment]
Who is responsible for updating the docs to reflect this?

**Comment by matthewd** [comment]
@nsimmons on a third party site, which says "The last existing version (v2.3.8) is shown here"?

**Comment by nsimmons** [comment]
http://api.rubyonrails.org/ is correct. :+1:

**Comment by arthurnn** [comment]
@nsimmons you should use devdocs http://devdocs.io/rails/activerecord/findermethods#method-i-find they are always right =) =) =) . /cc @Thibaut
