### ISSUE TITLE
Safari "Preload Top Hit in the background" requests (no HTTP headers?)

### ISSUE THREAD

**Issue by AUS3RIS** [rails/rails#18484]
Hello,

Is there a way somehow to identify requests made by Safari in the background, while editing address bar? This is caused when Safari option "Preload Top Hit in the background" enabled, which is by default.

Seems like Safari doesn't send any additional headers on these requests, like it does with `HTTP_X_PURPOSE`: `preview` when it generates thumb images for 'Top Hit' view.

Unlikely, but can we even identify these requests somehow?

**Comment by matthewd** [comment]
Please use the mailing list or StackOverflow for questions/help, where a wider community will be able to help you. We reserve the issues tracker for issues only.
