### ISSUE TITLE
where_values binding issue in 4.2?

### ISSUE THREAD

**Issue by apneadiving** [rails/rails#18481]
Hi,

I know `where_values` is supposed to be internal but its really convenient to use iot create OR queries for instance.

Actually I did use it this way but it seems there is a binding issue appearing in 4.2.

Here is a gist https://gist.github.com/apneadiving/15a3de9fa6d9031bedfd illustrating I end up with a `$1` after a `.to_sql`.

Is this expected? Is there a work around?

Thanks,

Benjamin

**Comment by matthewd** [comment]
> I know where_values is supposed to be internal

**Comment by apneadiving** [comment]
ok so no work around I suppose?

**Comment by mikejholly** [comment]
@matthewd Very helpful.

**Comment by BuonOmo** [comment]
Damn, I thought I would have something by clicking here... It is internal but it looks like this is the only way to acces a scope sql definition...
