### ISSUE TITLE
Adding responders gem in gemspec does not work.

### ISSUE THREAD

**Issue by runwaldarshu** [rails/rails#18487]
I am using responders gem in my gemspec but it is not working. It needs to be added in the Gemfile only why is so?
It will be nice to add it in gemspec that way every dependency using my gem does not have to add that in their Gemfile too. It should come as a transitive dependency.

**Comment by chancancode** [comment]
The difference is that adding something to the Gemfile would require it by default, whereas adding to the gemspec would not. So you would need to explicitly require that somewhere, presumably in your gem_name.rb
