### ISSUE TITLE
Active job should have support for custom types with custom serializers

### ISSUE THREAD

**Issue by kinnrot** [rails/rails#18486]
Currently we can only send to perform the following:

```
[ NilClass, Fixnum, Float, String, TrueClass, FalseClass, Bignum ]
````

And it's pretty strict,

Sometimes I'd like to send a BSON::ObjectId

and it's very simple to implement serialization and deserialization on it.
just no suitable infra for it.

**Comment by rafaelfranca** [comment]
Thank you so much for the issue but we don't take feature request on the issue tracker. We recommend you to try to implement the feature and send us a pull request or if you are in doubt if the feature will be accepts ask in Rails Core mailing list for feedback.
