### ISSUE TITLE
Rails 4.2 - when in development, 'routes/route' partial will be overriden by web-console gem

### ISSUE THREAD

**Issue by rikas** [rails/rails#18488]
Hi,

I have an application and I have a partial living under `app/views/routes/_route.html.erb`

If `Rails.env == 'development'`, when I try to use it within a view, with `<%= render partial: 'routes/route' %>` it does not render my partial and renders the web-console gem partial.

I did find a `lib/action_dispatch/templates/routes/_route.html.erb` inside web-console-2.0.0

Here's the log output showing that it is indeed using the web-console gem partial:

```
...
Rendered /Users/rikas/.rvm/gems/ruby-2.2.0@backend/gems/web-console-2.0.0/lib/action_dispatch/templates/routes/_route.html.erb (2.4ms)
 Rendered link_maps/index.html.erb within layouts/application (18.9ms)
...
```

So, are we supposed to be aware and not use the same name or is this some sort of a bug?

Thanks!

**Comment by gsamokovarov** [comment]
I can confirm the bug on 2.0, however it is not present on web-console master since we fixed the whole Rails error templates hijacking in rails/web-console#69.

@rikas can you test if web-console master works for you? I'll try to release a new version soon.

**Comment by rikas** [comment]
@gsamokovarov it does work with master. Thanks.
