### ISSUE TITLE
SQL Binds missing on joins with default scopes - 4.0.12 vs. 4.2.0

### ISSUE THREAD

**Issue by tjchambers** [rails/rails#18498]
In the gist: https://gist.github.com/tjchambers/636507ec330a9e88dc10/edit you can see a test setup that succeeds on 4.0.12 of Rails and fails on 4.2.0. 

In Summary the binds which would be generated for the stage !=7 are not generated twice as needed for the SQL statement, so in 4.2 there are 2 bind values mapped to 3 bind insertion points, which offsets the binds and leaves one bind missing a value making the statement not valid. 

In experimentation if the "where.not(stage: ARCHIVED)" default scope has it's bind value changed to a hardcoded "where('stage != 7')" then a single bind value is needed and supplied. Of Course counting on that or requiring hardcoded SQL strings is not acceptable. 

This severe bug is generating 1000's of incorrect SQL statements in our application being upgraded to 4.2.

Thanks for your attention to this.

**Comment by vipulnsward** [comment]
@tjchambers I tried to reproduce this here - 
https://gist.github.com/vipulnsward/d4503eaaaf58f5a3afd7
This passed for for me both on rails 4-2 stable and master and properly produced the binds.

**Comment by tjchambers** [comment]
Ok - thanks  - will wait till 4.2.1 release to reassess.

**Comment by sgrif** [comment]
As mentioned, this is a duplicate issue and has already been fixed.

**Comment by tjchambers** [comment]
Please reference the duplicate so I can examine.

**Comment by sgrif** [comment]
https://github.com/rails/rails/issues/18343 https://github.com/rails/rails/pull/18350
