### ISSUE TITLE
Fixtures not working with single table inheritance

### ISSUE THREAD

**Issue by macarenomarco** [rails/rails#18492]
I've found that when using single table inheritance it's necessary to use a single fixture file for all the test objects of that particular inheritance tree. For example when using a base class Person and Two child classes Student and Teacher, the expected behavior would be that when loading the files `teacher.yml` and `students.yml` the table people would have all the fixtures in it. The following are some simple files to explain it.

```yaml
#teachers.yml
presto:
    name: Test Teacher
```

```yaml
#students.yml
testo:
    name: Test Person
    teacher: presto
```

However when loading this fixtures only the teacher fixture exists in the database, after some messing around with the fixtures API and console I found that only the last fixtures of the table are that ones that are kept, which in default behaviour is the teachers fixtures because of the alphabetical loading order. Moreover, if the last fixture file is an empty one, the table stays empty.

 Maybe I didn't find it, but when researching it I saw no mention of this behavior in the docs.

The workaround I've found to work, is to use a single fixture file for any table that uses single table inheritance and erasing all other fixture files for the subclasses, or to load them explicitly by calling the fixtures API.

**Comment by prathamesh-sonpatki** [comment]
I can confirm this issue on master. This is happening because we are not merging the rows for STI tables - https://github.com/rails/rails/blob/master/activerecord/lib/active_record/fixtures.rb#L526 and deleting previous rows before addings rows in same table(in case of STI only)- https://github.com/rails/rails/blob/master/activerecord/lib/active_record/fixtures.rb#L528-L530

**Comment by wyde19** [comment]
Will this be backported to Rails4, or should we use some kind of workaround?

**Comment by zenspider** [comment]
@tenderlove ping. Was this backported to r4? @wyde19 hints that it wasn't.

**Comment by arthurnn** [comment]
Are you asking about rails 4.0, 4.1, or 4.2?

**Comment by wyde19** [comment]
I have 4.2.1 btw
You can easily tap into sources and see for yourself, which branches were
affected by fix.

2016-02-05 7:31 GMT+03:00 Arthur Nogueira Neves <notifications@github.com>:

**Comment by arthurnn** [comment]
backported https://github.com/rails/rails/commit/c79220368e8180141e9d796cf026d2b7da9f6384 to 4-2-stable. (https://github.com/rails/rails/commit/6a25fd1d694b8420fd6d525dd2bd243ea95ba490)

**Comment by zenspider** [comment]
@arthurnn thanks! Unfortunately that doesn't fix my client's test run. I'm gonna try to pair with @tenderlove to see if there's some other STI / fixtures bug.

**Comment by wyde19** [comment]
There is. I found something when you use abstract_class=true recently, but
I was too busy to sit with debugger so I can't put my finger on it. I just
made a quick workaround.
You can always get a debugger and do step-by-step investigation if it's
crucial for you.

2016-02-19 4:59 GMT+03:00 Ryan Davis <notifications@github.com>:

**Comment by arthurnn** [comment]
I reverted the backport btw. https://github.com/rails/rails/commit/8097019c75a07eeda6025e138ef8073e717a3d25

**Comment by wyde19** [comment]
@arturnn
Can you, please, tell why?
Or provide a link to some rails contribution guidelines, which made you do so?

**Comment by arthurnn** [comment]
@wyde19 the reason is on the commit message: 

> Reverting this as I thought it was a bug fix, but actually it is not.
This is more like a feature addition, as you can have STI for fixtures
right now if you have one fixture file for that table.

**Comment by nicohvi** [comment]
For anyone still running into this problem you need to add a `type` attribute to your fixtures, which represents the STI attribute on your model. For the provided example this would be:

```yaml
#teachers.yml
presto:
    name: Test Teacher
    type: Teacher
```
```yaml
#students.yml
testo:
    name: Test Person
    teacher: presto
    type: Student
```

At least I haven't found a way to avoid this. Happy coding!

**Comment by clthck** [comment]
@nicohvi I'm using rails 4.2.7.1, but fixtures with STI doesn't work even with `type` field added as you suggested.

**Comment by taltas** [comment]
@clthck This was fixed in Rails 5.0 https://github.com/rails/rails/blob/5-0-stable/activerecord/lib/active_record/fixtures.rb#L544-L549

**Comment by allanberry** [comment]
@taltas I am still having trouble with this in 5.1.

**Comment by taltas** [comment]
@allanberry Can you give a description of your problem?

**Comment by gilbert** [comment]
For the record, I just ran into this on rails 6.0.2.1; @nicohvi's workaround is still necessary.

**Comment by kimili** [comment]
Working in Rails 7.1.2, I found one more thing regarding this I haven't seen mentioned elsewhere. If you use the same keys in the different fixture files that populate your STI table, like so...

```yaml
#teachers.yml
one:
  type: Teacher
  name: Test Teacher
```

```yaml
#students.yml
one:
  type: Student
  name: Test Person
  teacher: one
```

…you will run into uniqueness violation errors on the row IDs when the test tries to populate the fixtures in the database.

I think Rails hashes or serializes the key string to generate a unique ID for that row when populating the database with fixture data. Because a given key always generates a specific ID, you can't use the same key in different fixtures that populate the same table (in this case, `one` in both files). Using unique keys across your different STI model fixtures avoids this problem.
