### ISSUE TITLE
Routing tests fail for routes that match all verbs

### ISSUE THREAD

**Issue by dideler** [rails/rails#18511]
Since upgrading to 4.2, my routing specs are failing for routes that match all HTTP methods.

```ruby
# config/routes.rb

match '/webhooks/mailgun/emails', to: 'webhooks/mailgun#emails', via: :all
```

```ruby
# spec/controllers/webhooks/mailgun_controller_spec.rb

it "routes all HTTP methods to #emails" do
  expect(all: 'webhooks/mailgun/emails').to route_to(action: 'emails')
end
```

If you were using Test::Unit, I think the test would look like
```ruby
test "routes all HTTP methods to #emails" do
  assert_routing({ method: 'all', path: 'webhooks/mailgun/emails' }, { controller: "webhooks/mailgun", action: "emails" })
end
```

The (RSpec) test fails
```
1) Webhooks::MailgunController should route ALL webhooks/mailgun/emails to/from {:action=>"emails", :controller=>"webhooks/mailgun"}
   Failure/Error: expect(all: 'webhooks/mailgun/emails').to route_to(action: 'emails')
   ActionController::UnknownHttpMethod:
     ALL, accepted HTTP methods are OPTIONS, GET, HEAD, POST, PUT, DELETE, TRACE, CONNECT, PROPFIND, PROPPATCH, MKCOL, COPY, MOVE, LOCK, UNLOCK, VERSION-CONTROL, REPORT, CHECKOUT, CHECKIN, UNCHECKOUT, MKWORKSPACE, UPDATE, LABEL, MERGE, BASELINE-CONTROL, MKACTIVITY, ORDERPATCH, ACL, SEARCH, MKCALENDAR, and PATCH
```

It's not recognizing ALL as an HTTP method (and that's true, it's not), but it is a valid route option and it used to work in tests. I don't know if it was intentional that it worked before, but if it was, then I would consider this a regression.

Someone in the #rspec channel mentioned (and I'm paraphrasing) that it's possible Rails used to default to a GET request when it didn't recognize the HTTP method in a test, which would explain why it worked previously.

Related issue: rspec/rspec-rails#1274

**Comment by Soleone** [comment]
I noticed a similar issue today where previously a HEAD request worked in rails 4.1 when the routes was defined as follows, but no longer does in rails 4.2:

    match '/ping' => 'tools#ping', via: [:get, :post]
