### ISSUE TITLE
ActionController::RoutingError (No route matches [OPTIONS] "/assets")

### ISSUE THREAD

**Issue by zpaulovics** [rails/rails#18513]
Hi,

In a Rails 4.2 application I have changed config parameter in the config/environments/porduction.rg file
from config.serve_static_assets = false 
to config.serve_static_files = false
according to the deprication message.  Since that time I have got the following fatal error:

I, [2015-01-14T12:43:41.747355 #22151]  INFO -- : Started OPTIONS "/assets/" for 91.120.37.4 at 2015-01-14 12:43:41 +0100
F, [2015-01-14T12:43:41.756075 #22151] FATAL -- : 
ActionController::RoutingError (No route matches [OPTIONS] "/assets"):
  vendor/ruby/2.2.0/gems/actionpack-4.2.0/lib/action_dispatch/middleware/debug_exceptions.rb:21:in `call'
  vendor/ruby/2.2.0/gems/actionpack-4.2.0/lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
  vendor/ruby/2.2.0/gems/railties-4.2.0/lib/rails/rack/logger.rb:38:in `call_app'
  vendor/ruby/2.2.0/gems/railties-4.2.0/lib/rails/rack/logger.rb:22:in `call'
  vendor/ruby/2.2.0/gems/actionpack-4.2.0/lib/action_dispatch/middleware/request_id.rb:21:in `call'
  vendor/ruby/2.2.0/gems/rack-1.6.0/lib/rack/methodoverride.rb:22:in `call'
  vendor/ruby/2.2.0/gems/rack-1.6.0/lib/rack/runtime.rb:18:in `call'
  vendor/ruby/2.2.0/gems/activesupport-4.2.0/lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
  vendor/ruby/2.2.0/gems/rack-1.6.0/lib/rack/sendfile.rb:113:in `call'
  vendor/ruby/2.2.0/gems/actionpack-4.2.0/lib/action_dispatch/middleware/ssl.rb:24:in `call'
  vendor/ruby/2.2.0/gems/railties-4.2.0/lib/rails/engine.rb:518:in `call'
  vendor/ruby/2.2.0/gems/railties-4.2.0/lib/rails/application.rb:164:in `call'
  /home/tamop614/.rvm/gems/ruby-2.2.0@trainer/gems/passenger-4.0.57/lib/phusion_passenger/rack/thread_handler_extension.rb:74:in `process_request'
  /home/tamop614/.rvm/gems/ruby-2.2.0@trainer/gems/passenger-4.0.57/lib/phusion_passenger/request_handler/thread_handler.rb:141:in `accept_and_process_next_request'
  /home/tamop614/.rvm/gems/ruby-2.2.0@trainer/gems/passenger-4.0.57/lib/phusion_passenger/request_handler/thread_handler.rb:109:in `main_loop'
  /home/tamop614/.rvm/gems/ruby-2.2.0@trainer/gems/passenger-4.0.57/lib/phusion_passenger/request_handler.rb:455:in `block (3 levels) in start_threads'

**Comment by rafaelfranca** [comment]
Can you please provide a sample application that reproduces the error?

**Comment by senny** [comment]
@zpaulovics It's been some time without feedback. Do you still experience that problem? If so, please provide a sample application to reproduce the problem, this goes a long way in debugging the issue.

**Comment by zpaulovics** [comment]
Hi, unfortunately I could not reproduce the problem.

**Comment by fjfish** [comment]
You see this when the remote app sends an OPTIONS http verb. I'm hitting this using the Ionic framework from a phone - I think it's some kind of check to see if the host will accept XSS. I can't quite work out how to set up a route that will accept the options verb - you used to be able to do it with match according so some ancient blog posts I found.
