### ISSUE TITLE
When using the sqlite3 database, some model callbacks are not being triggered.

### ISSUE THREAD

**Issue by matiasdh** [rails/rails#18518]
The following code does not work properly when using a sqlite3 database.

class ModelName < ActiveRecord::Base
  before_create :random_function

  def random_function
    puts "Hello World!"
  end
end

and from the rails console:
 > ModelName.new

A "Hello World!" text should be printed but nothing happens :( .

**Comment by seuros** [comment]
You user `before_create` not `before_initialize`, save the record to trigger the callback.
