### ISSUE TITLE
Inconsistent behaviour of Hash#stringify_keys, Hash#symbolize_keys and bang variants

### ISSUE THREAD

**Issue by pgeraghty** [rails/rails#18515]
Just thought I'd report this since I stumbled across it and maybe others can confirm/explain.

Rails 4 (checked under 4.0.9, 4.2.0):
```ruby
> {surprise: true, 'surprise' => false}.symbolize_keys
=> {:surprise=>false} 

> {surprise: true, 'surprise' => false}.symbolize_keys!
=> {:surprise=>false}

> {surprise: true, 'surprise' => false}.stringify_keys
=> {"surprise"=>false}

> {surprise: true, 'surprise' => false}.stringify_keys!
=> {"surprise"=>true}
```
Rails 3.2 (checked under 3.2.16):
```ruby
> {surprise: true, 'surprise' => false}.symbolize_keys
=> {:surprise=>false}

> {surprise: true, 'surprise' => false}.symbolize_keys!
=> {:surprise=>false}

> {surprise: true, 'surprise' => false}.stringify_keys
=> {"surprise"=>true}

> {surprise: true, 'surprise' => false}.stringify_keys!
=> {"surprise"=>true}
```

**Comment by spidergears** [comment]
Confirmed on Rails 4.1.6,  Ruby 2.1.5
```ruby
> {:key => "true", "key" => "false"}.stringify_keys
 => {"key"=>"false"} 
 > {:key => "true", "key" => "false"}.stringify_keys!
 => {"key"=>"true"} 
 > {:key => "true", "key" => "false"}.symbolize_keys
 => {:key=>"false"} 
 > {:key => "true", "key" => "false"}.symbolize_keys!
 => {:key=>"false"} 
```

**Comment by dbackowski** [comment]
Confirmed on Rails 4.1.8, Ruby 2.0.0

**Comment by sivsushruth** [comment]
I think the issue is because of the delete method being called on hash with duplicate values.

Rewriting the transorm_keys! method as 

```
def transform_keys!
    return enum_for(:transform_keys!) unless block_given?
    keys.each do |key|
      if keys.map{|k| k.intern}.count(key.intern) == 1 
        self[yield(key)] = delete(key) 
      else
         delete(key) 
      end
    end
    self
 end
```

seems to work.

```
> {:key => "true", "key" => "false"}.stringify_keys
 => {"key"=>"false"} 
> {:key => "true", "key" => "false"}.stringify_keys!
 => {"key"=>"false"} 
```

Is this acceptable ?

**Comment by sivsushruth** [comment]
Any news on this issue ?

**Comment by georgeclaghorn** [comment]
I'll take a look at patching this when I get a chance.

**Comment by sivsushruth** [comment]
But, is this because of the delete method being called on the hash with duplicate keys ?

**Comment by aditya-kapoor** [comment]
I gave this issue a look last night and made this progress:
```
def transform_keys!
  return enum_for(:transform_keys!) unless block_given?
  keys.each do |key|
    yielded_key_value   = yield(key)
    deleted_key_value   = delete(key)
    existing_hash_value = self[yielded_key_value]
    self[yield(key)]    = existing_hash_value || deleted_key_value
  end
  self
end
```
the patch works fine when hash is ```{surprise: true, 'surprise' => false}``` but fails for ```{'surprise' => true, surprise: false}```

I am not able to improve upon this, any help in this would be appreciated.

**Comment by georgeclaghorn** [comment]
@sivsushruth: Yes, this worked as it did in 3.2 because `symbolize_keys` and `stringify_keys` duplicated the original hash and transformed the duplicate's keys in-place.

This was changed in 6ddbd1844a6fd6aca2992f5f75c9f605cf89808f, when `symbolize_keys` and `stringify_keys` were changed to build up a new hash by iterating over the original hash for a performance improvement.

Your patch seems correct, but is noticeably less efficient than the existing behavior:

```
Calculating -------------------------------------
     stringify_keys!    17.025k i/100ms
 new_stringify_keys!    14.052k i/100ms
-------------------------------------------------
     stringify_keys!    484.238k (± 6.4%) i/s -      2.418M
 new_stringify_keys!    282.493k (± 5.9%) i/s -      1.419M
```

The script I used to benchmark the patch is [here](https://gist.github.com/georgeclaghorn/27cb945c32e1211fb6a7).

**Comment by sivsushruth** [comment]
Okay, this is noticeably slower.
Working on an alternate solution in the meanwhile.

ᐧ

Regards,
Sushruth Sivaramakrishnan
*bill anyone, anywhere <http://hummingbill.com/>*
+91 9158310963

**Comment by sivsushruth** [comment]
Okay, this is noticeably slower.
Working on an alternate solution in the meanwhile.

ᐧ

**Comment by sivsushruth** [comment]
Using 
```
keys.map(&:to_s)
```
instead of 

```
 keys.map(&:to_sym)
```

is faster

```
     stringify_keys!    16.595k i/100ms
 new_stringify_keys!    15.580k i/100ms
-------------------------------------------------
     stringify_keys!    409.530k (± 4.7%) i/s -      2.041M
 new_stringify_keys!    377.352k (± 4.8%) i/s -      1.885M
```

This is the script I used to benchmark[ here](https://gist.github.com/sivsushruth/71cf61472d5c5ba9c9cd)

**Comment by georgeclaghorn** [comment]
Nice, @sivsushruth.

Though that's faster, it trades speed for many more string allocations. I wonder if there's an algorithmic solution -- one that doesn't require iterating over the entire set of keys for each key. I tried to find one earlier but couldn't. Have any ideas?

**Comment by sivsushruth** [comment]
Here is another solution
```
def transform_keys!
    return enum_for(:transform_keys!) unless block_given?
    counts = Hash.new 0
    keys.each do |key|
      counts[key.to_s] += 1
    end
    keys.each do |key|
      if counts[key.to_s] == 1
        self[yield(key)] = delete(key)
      else
        delete(key)
        counts[key]-=1
      end
    end
    self
 end
 ```

This is better as we are doing just one extra iteration for the entire set of keys.
What do you think ?

**Comment by egilburg** [comment]
What's the expected behavior in case original hash has conflicting values for string and symbol keys?
- Always use the string variant, as non-transformed value should take precedence over transformed value?
- Or, always use the first value in the hash (ruby 1.9 hashes are sorted, so it could be argued the sort should take precedence?
- Or, always use the last value present? This is most closely implied by a loop construct, and also mimics how Ruby handles other hash operations with a many-to-one folding, e.g.:

```ruby
{a: 1, b: 1}.invert
# => {1=>:b}
```

Although consistency is nice, this type of operation in general should be verified by programmer because it doesn't really make sense, and therefore the behavior might be considered undefined implementation detail.

**Comment by sivsushruth** [comment]
I think the 3rd option might be the preferred one, where the last value/key gets priority.
Refer #18598

**Comment by sgrif** [comment]
See https://github.com/rails/rails/pull/18598#issuecomment-73537978
