### ISSUE TITLE
Mail and deliver_later doesn't work with date argument

### ISSUE THREAD

**Issue by russellquinn** [rails/rails#18519]
If you pass :date into mail with a deliver_later:

    mail(:from => "test@test.com", :to => "another@another.com", :subject => "hey", :date => Time.now).deliver_later

Then it throws a SerializationError, because Time is an unsupported argument type:

http://edgeapi.rubyonrails.org/classes/ActiveJob/SerializationError.html

**Comment by rafaelfranca** [comment]
Yes, it is. We can't pass Time objects to the background adapters since sone of them only support some basic errors. You should serialize the Time object in your side.

**Comment by russellquinn** [comment]
There's also no documentation about the expected format :date for mail.

**Comment by rafaelfranca** [comment]
Hmm, in other side you are not implementing the delivery job and you would have to deserialize it on the views, what is not a good option. Not sure what we can do given that some adapters just accept basic types.

cc @seuros @cristianbica

**Comment by russellquinn** [comment]
Right, considering deliver_later is a it-just-works method. It should just work. At the very least, it should be clearly documented that it doesn't work with :date.

**Comment by cristianbica** [comment]
You don't need to deserialize in the view. You don't call deliver_later on the result of the `mail` method but on an ActionMailer action method. You will deserialize in there. The way I use this is UserMailer.welcome(user, Time.now.to_i) and in the welcome method I use Time.at.
I'm not sure how often dates are passed to the jobs but I would avoid handling that in ActiveJob because we would need to do some custom stuff to preserve timezone

**Comment by russellquinn** [comment]
> You don't call deliver_later on the result of the mail method but on an ActionMailer action method.

Right, sorry.

**Comment by zawaideh** [comment]
There should be a symmetry between deliver_now and deliver_later. If parameters are accepted in one, they should be accepted in the other.

Also, shouldn't the adapter itself do the enforcing of the parameter? If it doesn't support Time object it can raise an error?

**Comment by deeTEEcee** [comment]
hmm, activerecord works but the data types an activerecord would hold cannot be separately serialized?

**Comment by benrugg** [comment]
Please excuse my coming to this conversation late, but... It seems like a pretty big limitation that ActiveJob doesn't serialize Date or Time objects. There are many scenarios (in addition to ActiveMailer) where this could cause issues, and it seems like a difficult thing to track down when upgrading from Rails 4.1 to 4.2.

It would be great for someone to fix this in the future!

**Comment by ayb** [comment]
This is still a real problem and is not working for me in Rails 4.2.6

`MyMailer.my_action(Time.now).deliver_later` yields an error `ActiveJob::SerializationError: Unsupported argument type: Time`

**Comment by jacquescrocker** [comment]
I just ran into this bug as well. Pretty surprising IMO. Seems like a really easy thing for ActiveJob to serialize by default

**Comment by anklos** [comment]
just happened to me too...

**Comment by ysyyork** [comment]
Just happened to me too... Is there a easy fix?

**Comment by jonhoo** [comment]
Is there a way to render the e-mail immediately, and only delay the *sending* of the e-mail. This would allow something like
```ruby
MyMailer.my_action(Time.now).deliver_later
```
to work just fine without serializing `Date`. If the full message, and not just the body is rendered like this, then even the original code segment would work:
```ruby
mail(
  :from => "test@test.com",
  :to => "another@another.com",
  :subject => "hey",
  :date => Time.now
).deliver_later
```

**Comment by Dorian** [comment]
For now doing with a:

```
class MyMailer < ActionMailer::Base
  def my_action(date)
    date = Time.zone.parse(date)
    mail(to: "me@example.com", subject: "my subject in #{date.year}")
  end
end
```

And: `MyMailer.my_action(Time.now).deliver_later` works fine.

**Comment by pierre-pretorius** [comment]
If you don't mind loosing millisecond accuracy and you are looking for a quick and dirty fix: create an initializer with the following content:
```Ruby
# https://github.com/rails/rails/issues/18519
class ActiveSupport::TimeWithZone
  include GlobalID::Identification

  alias_method :id, :to_i
  def self.find(seconds_since_epoch)
    Time.zone.at(seconds_since_epoch.to_i)
  end
end

class Time
  include GlobalID::Identification

  alias_method :id, :to_i
  def self.find(seconds_since_epoch)
    Time.at(seconds_since_epoch.to_i)
  end
end
```

ActiveJob supports anything than includes GlobalID::Identification.  This patch adds it to Time:
```Ruby
Time.now.to_global_id.to_s
# => "gid://your-app-name/Time/1490354247"

GlobalID::Locator.locate "gid://your-app-name/Time/1490349356"
# => 2017-03-24 11:55:56 +0200
```

**Comment by Riddlerrr** [comment]
And for `Date` too:
```ruby
class Date
  include GlobalID::Identification

  alias_method :id, :to_s
  def self.find(date_string)
    Date.parse(date_string)
  end
end

```

**Comment by vnnoder** [comment]
If you want millisecond accuracy

```
class ActiveSupport::TimeWithZone
  include GlobalID::Identification

  def id
    (Time.zone.now.to_f * 1000).round
  end

  def self.find(milliseconds_since_epoch)
    Time.zone.at(milliseconds_since_epoch.to_f / 1000)
  end
end

class Time
  include GlobalID::Identification

  def id
    (Time.zone.now.to_f * 1000).round
  end

  def self.find(milliseconds_since_epoch)
    Time.zone.at(milliseconds_since_epoch.to_f / 1000)
  end
end
```

**Comment by kjbkjb** [comment]
Just ran into this myself. Very strange design decision to not support Date serialization.

**Comment by cristianbica** [comment]
@CodingAnarchy support has been added https://github.com/rails/rails/pull/32026 but it didn't make it into 5.2 so it will be 6.0

**Comment by Startouf** [comment]
Be careful when using @pierre-pretorius solution, it seems to have problems if you serialize dates in nested hashes

**Comment by nickstanish** [comment]
Or serialize with iso8601

**Comment by dknox20** [comment]
@vnnoder I believe you need to change your definition of id on time to be 

```
def id
  (to_f * 1000).round
end
```

or use @nickstanish suggestion
```
def id
  iso8601
end
```
