### ISSUE TITLE
A concern that contains a skip_before_action does not skip the before_action of a parent's concern

### ISSUE THREAD

**Issue by seanahrens** [rails/rails#18529]
I know that title sounds complicated, let me break it down:

I have my ApplicationController and my RegistrationsController both including their own concerns. In the concern of the ApplicationController I have a before_action. In the concern of the RegistrationsController I have a skip_before_action. The skip_before_action does not work. The action gets executed anyway.

I believe this is a bug / not desired behavior of Rails but I'm open to the fact I may have done something wrong.

Here's the code:

```ruby
class ApplicationController < ActionController::Base
  def initialize
    self.class.send(:include, ApplicationConcernController)
  end
  ...
end
```

```ruby
module ApplicationConcernController
  extend ActiveSupport::Concern

  included do
    before_action :foo
  end
  ...
end
```

```ruby
class RegistrationsController < Devise::RegistrationsController
  def initialize
    self.class.send(:include, RegistrationConcernController)
  end
  ...
end
```

```ruby
module RegistrationsConcernController
  extend ActiveSupport::Concern

  included do
    skip_before_action :foo #but....this does not work. actions of RegistrationsController still call foo.
  end
  ...
end
```

Thanks. Happy to hear if I'm doing something wrong, but I would expect the skip_before_action to work in the way I've coded it.

**Comment by claudiob** [comment]
@seanahrens Hello! 

It looks to me like there is something weird going on with those `initialize` in your code:
`RegistrationController` inherits from a `Devise::RegistrationsController` which probably does not inherit from the same `ApplicationController` you reported above. 
Also, `RegistrationController` does not call `super`, so probably the original `initializer` gets lost.

I suggest you try try your code again in a brand new app (without Devise).
If you still encounter a bug, please report the code snippet so it can be easily reproduced.
If you don't find a bug but need help or suggestions with your code, please use the [Ruby on Rails - Talk Google Group](https://groups.google.com/forum/#!forum/rubyonrails-talk). 

Thanks! :ribbon:

**Comment by seanahrens** [comment]
@claudiob thanks for your prompt reply. Actually, the problem IS solved when I move "before_action :foo" into ApplicationController, and take it out of ApplicationConcernController. And do nothing else.

`
class ApplicationController < ActionController::Base
  before_action :foo
end
`

This leads me to believe it's a Rails thing. But if given this, you still think I should move it to the google group, please let me know and I will.

**Comment by sgrif** [comment]
You should not be calling `include` inside of `initialize`. Perhaps you should look into the `inherited` method that ruby provides. However, we won't be able to skip an action before it's defined, so you'll probably need to do some legwork to make sure the order of inheritance is correct. This is due to the semantics of Ruby, not Rails, and we can't really do a lot to change that.
