### ISSUE TITLE
strip_tags escapes other characters like quotes and ampersands 

### ISSUE THREAD

**Issue by kommen** [rails/rails#18527]
This behavior changed from rails 4.1 to 4.2 with https://github.com/rails/rails/pull/11218 (thanks for that amazing work btw!).

```ruby
strip_tags '"' # => "&quot;"
```
```ruby
strip_tags '&' # => "&amp;"
```

I would expect `strip_tags` to not behave like that and just remove tags and comments as documented, because maybe the output won't be used in HTML.

As a workaround, I use ```Rails::Html::WhiteListSanitizer.new.sanitize(string, tags: [])```, which seems to behave like `strip_tags` from rails 4.1.

cc @kaspth

**Comment by matthewd** [comment]
I think this is a dup of https://github.com/rails/rails-html-sanitizer/issues/28

**Comment by sgrif** [comment]
This indeed appears to be a duplicate.
