### ISSUE TITLE
Can we get a method "HashWithIndifferentAccess#symbolize_keys!"

### ISSUE THREAD

**Issue by georgemillo** [rails/rails#18531]
When I'm writing a method which takes an options hash, I often use `symbolize_keys!` on the hash to avoid any issues with users passing in string keys:

    def my_awesome_method(opts={})
      opts.symbolize_keys!
      # Perform magic...
    end

The problem is, if somebody passes in a `HashWithIndifferentAccess` to this method, it will fail with a `NoMethodError`: `undefined method `symbolize_keys!'`.

I could always work around this by avoiding the bang-method:

    def my_awesome_method(opts={})
      opts = opts .symbolize_keys
      # Perform magic...
    end

But I don't understand why this method should be removed in the first place.

Looks like this was added by [2472f1026](https://github.com/rails/rails/commit/2472f1026a7d3b3309937568204a5b46b60c2c3c) back in 2010. 

Just wondering what the reasoning behind this is? Wouldn't it make more sense to define `symbolize_keys!` as a no-op an make HashWithIndifferentAccess quack completely like a Hash?

**Comment by georgeclaghorn** [comment]
Judging from [the CHANGELOG entry](https://github.com/rails/rails/blob/9891ca89c69732a21743f0349f2995956a7802e7/activesupport/CHANGELOG#L77), it looks like it was removed because the implementation of HashWithIndifferentAccess relies on the internal hash having string keys.

cc @spastorino @jeremy

**Comment by georgemillo** [comment]
Do we care about the internal implementation though? Can't we just add

    def symbolize_keys!
      self
    end

    def stringify_keys!
      self
    end

Then HashWithIndifferentAccess won't cause any unexpected behaviour with APIs which are expecting a Hash?

**Comment by matthewd** [comment]
@georgemillo `keys`.

**Comment by georgemillo** [comment]
Ah I see, so if someone typed

    def my_method(opts={})
      opts.symbolize_keys!
      keys = opts.keys
      # whatever
    end

Then they'd expect `keys` to be an Array of Symbols, but if opts is a HWIDA it would actually be an Array of Strings. Hmmm.... point taken.

**Comment by sgrif** [comment]
Seems like there's a consensus that this method doesn't make sense for HWIDA. I'm going to close this to clear out the issues tracker. If you think there's additional discussion to be had, please let me know and I will re-open.
