### ISSUE TITLE
Guide => Getting Started with Rails (explanation missing about jquery_ujs)

### ISSUE THREAD

**Issue by fera2k** [rails/rails#18533]
In section "**5.13 Deleting Articles**", when the text refers to the "**jquery_ujs**" asset, and say that it is a javascript file that is included in the application's layout (app/views/layouts/application.html.erb). 
So as a newbie myself, I looked there, but found no real reference.

**Suggestion**: for completeness, the explanation must tell about the application.js file (app/assets/javascripts) which contains the "//=require" line, and that the actual javascript file is provided by the included gem "jquery-rails", (would be perfect with a link to some other guide about how the Javascript assets and coffee processing model for more info).

_PS: Sorry for not being able to make the modifications myself. Hope I`d contribute more in near future!_

**Comment by andreynering** [comment]
@fera2k See: https://github.com/rails/rails/pull/18541

I just added a reference to Javascript guide. Don't need to explain all the process on the getting started.
