### ISSUE TITLE
Using "becomes" on a "dirty" ActiveRecord object causes disappearance of nested attributes

### ISSUE THREAD

**Issue by dmastylo** [rails/rails#18549]
Sample code (with some unnecessary items removed for brevity).

This issue came about when trying to do custom validations via a service object on an STI user. The user already exists when getting to "finish signup" page, and from there they set the "type" of user they become, and based on that type, different form fields, and different nested associations are possible. Due to this, standard model validations are very unwieldy as this is use case is pretty weird. This is why I have to do a lot of "hacky" behavior.

```
user = User.new
params = ActionController::Parameters.new(user: { name: "hey", nested_attributes: [{ parent_id: Parent.last.id, title: "test" }] } ).require(:user).permit(:name, nested_attributes: [:parent_id, :title])
 => {"name"=>"hey", "nested_attributes"=>[{"parent_id"=>9, "title"=>"test"}]} 

user.attributes = params
 => {"name"=>"hey", "nested_attributes"=>[{"parent_id"=>9, "title"=>"test"}]} 

user
 => #<User id: nil, ... name: "hey", ...> 

user.attributes
 => {"id"=>nil, "email"=>"", ... "name"=>"hey", ...} 

user.nested
 => #<ActiveRecord::Associations::CollectionProxy [#<Nested id: nil, title: "test", parent_id: 9, ...>]> 

user = user.becomes!(SubClass)
 => #<SubClass id: nil, email: "", encrypted_password: "", ... name: "hey", ... type: "SubClass", ...> 

user.nested
 => #<ActiveRecord::Associations::CollectionProxy []> 
```

**Comment by dmastylo** [comment]
Might I add that ```becomes``` causes this behavior too. Looking at the source of becomes shows

```
# File activerecord/lib/active_record/persistence.rb, line 197
def becomes(klass)
  became = klass.new
  became.instance_variable_set("@attributes", @attributes)
  became.instance_variable_set("@changed_attributes", @changed_attributes) if defined?(@changed_attributes)
  became.instance_variable_set("@new_record", new_record?)
  became.instance_variable_set("@destroyed", destroyed?)
  became.instance_variable_set("@errors", errors)
  became
end
```

Setting nested attributes in the new ```klass``` never happens. I can't seem to find any methods that can grab all nested attributes, however.

**Comment by dmastylo** [comment]
I have found a fix and will be making a pull request today or tomorrow and submit it.

**Comment by dmastylo** [comment]
I made a pull request (albeit a little later than I said I would)

**Comment by rafaelfranca** [comment]
https://github.com/rails/rails/pull/18668#issuecomment-71299257
