### ISSUE TITLE
Cannot run Rails performance tests in Rails 3.2.21 and Ruby > 2.0

### ISSUE THREAD

**Issue by blzabub** [rails/rails#18542]
Due to this line:

https://github.com/rails/rails/blob/3-2-stable/activesupport/lib/active_support/testing/performance/ruby.rb#L145

We can't run performance tests under Ruby 2.1.x. Instead we get this error message as one might expect:

> Update your ruby interpreter to be able to run benchmarks.

 If we monkey patch the ActiveSupport gem our performance tests will run successfully. Not sure if there are actual protections being provided that are necessary or if code here is just outdated.

**Comment by rafaelfranca** [comment]
Thank you for the report. Rails 3 is not supported anymore

**Comment by blzabub** [comment]
Ah right...sorry.

**Comment by bjm88** [comment]
blzabub, have you been successful in running rails 3.2 on ruby 2.1 ?

Does 3.2 actually certify and support ruby 2.0?  2.1?  We are considering first upgrading ruby from 1.9.latest to 2.latestRailsWillSupport.

Thoughts?

**Comment by blzabub** [comment]
@bjm88, yes we got our Rails 3.2.21 app running on Ruby 2.0, 2.1.x without many issues. The problem is now with Ruby 2.2.x. Can sort of get it running there as well, but we have many test failures, so have shelved it for now.

**Comment by bjm88** [comment]
Thasnks blzabub, I just did some digging.  I suspect you want to pull in Rails 3.2-stable, they made a key merge for 2.2 but didn't put out a new 3.2.22 release.....this is what we are going to try..

https://github.com/rails/rails/pull/18306

**Comment by blzabub** [comment]
Yes, that's what we did as well, but we had trouble with other areas of our stack, can't remember which but probably gems we're pinned to aren't ruby 2.2 compatible and upgrading them involves rewriting tests to deal with API changes in those gems.

**Comment by Maximus1285** [comment]
Sorry to ask on a closed issue, but I just don't want to open a new issue unnecessarily.
But as it is right: 
given this chunk of code in `rails/activesupport/lib/active_support/testing/performance/ruby.rb` 
```ruby
if RUBY_VERSION.between?('1.9.2', '2.0.0')
  require 'active_support/testing/performance/ruby/yarv'
elsif RUBY_VERSION.between?('1.8.6', '1.9')
  require 'active_support/testing/performance/ruby/mri'
else
  $stderr.puts 'Update your ruby interpreter to be able to run benchmarks.'
  exit
end
```
It is scoping the support of performance tests to ruby version between 1.9.2 and 2.0.0 
So any version above ruby 2.0.0 won't be able to run performance tests. What about any version above 2?
