### ISSUE TITLE
ActiveRecord::Core#== doesn't work for STI

### ISSUE THREAD

**Issue by mhuggins** [rails/rails#18547]
I'm trying to work with STI, and I'm testing equality.  Let's say I have model User along with inheriting models Administrator and Client.

```ruby
class User < ActiveRecord::Base
end

class Administrator < User
end

class Client < User
end
```

Now consider the following:

```ruby
user = User.create(type: 'Client', name: 'Joe', email: 'joe@example.com')
# => #<User id: 1, type: "Client", name: "Joe", email: "joe@example.com">

client = Client.find(user.id)
# => #<Client id: 1, type: "Client", name: "Joe", email: "joe@example.com">

user == client
# => false
```

The reason that the equality check returns false is due to [the implementation of `ActiveRecord::Core#==`](https://github.com/rails/rails/blob/cca85ba699242c3266c5132dd601fdd8c5c5bb16/activerecord/lib/active_record/core.rb#L299):

```ruby
def ==(comparison_object)
  super ||
    comparison_object.instance_of?(self.class) &&
    !id.nil? &&
    comparison_object.id == id
end
alias :eql? :==
```

Because of how `#instance_of?` works, it is returning `false` when I'm wanting a `true` result due to STI.  I would argue that the method definition should be changed to read:

```ruby
def ==(comparison_object)
  super ||
    comparison_object.is_a?(self.class) &&
    !id.nil? &&
    comparison_object.id == id
end
alias :eql? :==
```

Is there any reason for the use of `#instance_of?` over `#is_a?`, or does this sound like an acceptable pull request to change the behavior?

**Comment by mhuggins** [comment]
After more consideration, the test would still return false if I called `client == user` instead of `user == client`, so perhaps an even better solution would be:

```ruby
def ==(comparison_object)
  super ||
    (comparison_object.is_a?(self.class) || is_a?(comparison_object.class) &&
    !id.nil? &&
    comparison_object.id == id
end
alias :eql? :==
```

**Comment by sgrif** [comment]
Yes, please open a pull request.
