### ISSUE TITLE
Adding a middleware to a controllers middleware stack causes problems with helper inclusion

### ISSUE THREAD

**Issue by nateberkopec** [rails/rails#18555]
Given a blank rails app fresh from ```rails new```, add two helper methods:

```ruby
#app/helpers/application_helper.rb
module ApplicationHelper
  def hello
    "world"
  end
end

#app/helpers/foo_helper.rb
module FooHelper
  def foo
    "bar"
  end
end
```

Now, add a middleware to the ApplicationController in an environment's config file. For example:

```ruby
#config/environments/development.rb
ApplicationController.middleware.use("::Rack::Auth::Basic", "Test") do |u, p|
  u == "user" && p == "secret"
end
```

FooHelper will no longer be included by default in ActionView::Base.

```ruby
irb(main):001:0> helper.foo
NoMethodError: undefined method `foo' for #<ActionView::Base:0x00000109927778>
```

Present on 4.1 and 4.2, unsure of other versions. A blank app that reproduces this is [here](https://github.com/nateberkopec/helpertest).

**Comment by sebjacobs** [comment]
You should be able to configure the middleware directly on `config`.

e.g

```ruby
Rails.application.configure do
  config.middleware.use("::Rack::Auth::Basic", "Test") do |u, p|
    u == "user" && p == "secret"
  end
end
```

**Comment by nateberkopec** [comment]
@sebjacobs I could, but in this case, I actually only want to add it to ApplicationController.

**Comment by nateberkopec** [comment]
Add the middleware directly in application_controller.rb and all helpers are included as usual. This isn't super ideal for us - I like keeping environment specific code in config/environments. I may not be able to do this due to load order issues, and if thats the case, then this should be closed.

**Comment by rafaelfranca** [comment]
It happens because when you call `ApplicationController` in a initializer it load the ActionController before action_view helpers and hooked. Yeah, it is not possible to use this right now.
