### ISSUE TITLE
Not very sure it's a bug or not

### ISSUE THREAD

**Issue by jadeydi** [rails/rails#18553]
I want to support IOS emoji so I change mysql's encoding to utf8mb4 and database.yml encoding to utf8mb4 .

But when I search a record from  console it can't  correctly return data. e.g.
There is an artist has album.

@artist.albums.find 1 will return
name: "Name of a album :smile: :laughing: :smiley: "

but if I use Album.find 1 will return 
name:  "Name of a album ???"

How can i resolve it?

**Comment by rafaelfranca** [comment]
Please use the mailing list or StackOverflow for questions/help, where a wider community will be able to help you. We reserve the issues tracker for issues only.
