### ISSUE TITLE
Cannot assign a frozen Array to a HashWithIndifferentAccess

### ISSUE THREAD

**Issue by jasonhutchens** [rails/rails#18550]
This was broken in Rails 4.0, because `ActiveSupport::HashWithIndifferentAccess#convert_value` calls `#map!` on the frozen value, not a dup, which raises the exception. I presume that was an optimisation? A check for `#frozen?` would fix this. Here's a demo:

```
Loading development environment (Rails 4.2.0)
> value = [1, 2, 3].freeze
 => [1, 2, 3]
> hash = {}.with_indifferent_access
 => {}
> hash[:key] = value
RuntimeError: can't modify frozen Array
```

**Comment by pixeltrix** [comment]
@jasonhutchens broken in Rails 4.0, 4.1 or 4.2 ?

**Comment by jasonhutchens** [comment]
Sorry @pixeltrix... broken in Rails 4.0, still broken in 4.2.

**Comment by pixeltrix** [comment]
Looks like it used to have a dup if frozen line in there when `map!` was introduced in 808592b, however if was removed in c44a929 so if you're saying that 4.0 doesn't work then it must have been broken before for other reasons :smile:

**Comment by jasonhutchens** [comment]
Based on discussion in the PR above, that would have been https://github.com/rails/rails/issues/10526
