### ISSUE TITLE
belongs_to validations failing

### ISSUE THREAD

**Issue by slavingia** [rails/rails#18563]
After upgrading from Rails 4.1.7.1 to 4.2.0, validations for belongs_to associations in our factories fail.

The two model files:

```
class User < ActiveRecord::Base    
  ...
  has_many :things
  ...
end

class Thing < ActiveRecord::Base
  ...
  belongs_to :user   
  validates_presence_of :user
  ...
end
```

The factory:

```
FactoryGirl.define
  factory :thing do
    association :user      
    ...
  end
end
```

Creating a new thing always fails saying User must be provided. Any ideas?

Environment:

```
ruby 2.1.5

factory_girl 4.5.0
factory_girl_rails 4.5.0
rails 4.2.0
rspec 3.1.0
```

**Comment by nateberkopec** [comment]
Hm, is this reproducible in a blank/new app? I'm not seeing this in our Rails 4.2 app.

**Comment by jmondo** [comment]
Check that your user is getting saved. It could be some error down the line when it tries to save the user. Is `FactoryGirl.create(:user)` working? (Open it up, make sure it is actually persisted and valid.) If that works, does `FactoryGirl.create(:thing, user: FactoryGirl.create(:user))` work?

**Comment by slavingia** [comment]
@jmondo:

```
>> user = create(:user)
  ( returns saved "user" object )
>> user.id
1
>> thing = build(:thing, user: user)
  ( returns new "thing" object )
>> thing.valid?
false
>> thing.user_id
1
>> User.find(1).present?
true
>> thing.user
nil
```

**Comment by jmondo** [comment]
at `thing.valid? => false`
what does `thing.errors` return?

**Comment by sgrif** [comment]
Can you please provide a script that we can use to reproduce the issue, using https://github.com/rails/rails/blob/master/guides/bug_report_templates/active_record_master.rb as a template?

**Comment by slavingia** [comment]
@jmondo:

```
>> thing.errors
{
    :user => [
        [0] "must be provided."
    ]
}
```

**Comment by slavingia** [comment]
For what it's worth, I can do this totally outside testing/factories to the same affect.

**Comment by sgrif** [comment]
@slavinga Please provide a script that we can use to reproduce the issue. If the issue cannot be reproduced outside of factory girl, this is not a bug in rails. No action can be taken on this issue unless you provide a script that we can use to reproduce the issue. Please use https://github.com/rails/rails/blob/master/guides/bug_report_templates/active_record_master.rb as a template.

**Comment by slavingia** [comment]
@sgrif: I have been working on a script (as of this morning). I can replicate this outside of Factory Girl (with standard rails c in our environment), but have been having trouble getting the bug report file to replicate the same behavior as of yet (even with the same Gems).

Any ideas? I'll continue poking around.

**Comment by sgrif** [comment]
Sorry, I don't have any ideas for you. Part of the reason that we ask for the reproduction script is to ensure that the bug is in fact something wrong with rails, and not some part of your application doing something bad.

**Comment by slavingia** [comment]
Fair. I'll keep searching. Thanks!

**Comment by senny** [comment]
@slavingia It's been a while since we heard from you. Do you still experience this issue? If so, it would be great to get that reproduction script. This goes a long way in debugging the issue.

**Comment by slavingia** [comment]
Still an issue. Unfortunately, can't get it to work with the reproduction script.

**Comment by sgrif** [comment]
If you can't reproduce it in isolation, its likely a bug in your app, not Rails. Feel free to open a new issue if you're able to reproduce in the future.
