### ISSUE TITLE
autosave association fails when associated model has uniqueness validation

### ISSUE THREAD

**Issue by fw42** [rails/rails#18573]
I think https://github.com/rails/rails/pull/10417 didn't completely fix the issue I believe it was meant to fix.

See https://github.com/rails/rails/pull/10417#issuecomment-70385369.

If the associated model does not only have a uniqueness index but also a uniqueness validation, then saving the parent will still fail. I believe the reason is that ```validate_collection_association``` is called **before** any records are destroyed (i.e. even though the records that were marked for destruction are not validated, the new record is invalid because the old one still exists in the database at that time (```save_collection_association``` didn't run yet)). Similar problems can occur for any type of validation that considers records other than the one that is being validated.

Shitty workaround for now is to ```has_many ... autosave: true, validate: false``` on the parent model.

@arthurnn @jholton

**Comment by dharanimanne** [comment]
Can I take up this issue and start working on it?

**Comment by fw42** [comment]
I don't think you need to ask for permission :)

**Comment by mdluo** [comment]
The bug cannot be reproduced by this test case:

```ruby
  def test_should_save_new_record_that_has_same_value_as_existing_record_marked_for_destruction_on_field_that_has_uniqueness_validation
    bird = Class.new(ActiveRecord::Base) {
      self.table_name = 'birds'
      validates :name, uniqueness: true
      belongs_to :pirate, autosave: true
      def self.name; 'Bird'; end
    }
    bird.connection.add_index :birds, :name, unique: true

    p = Pirate.create!(:catchphrase => "Test")
    3.times { |i| bird.create(name: "unique_bird_#{i}", pirate: p) }

    p.birds[0].mark_for_destruction
    p.birds.build(name: p.birds[0].name)    # birds[2].name == unique_bird_0
    p.save!
    assert_equal 3, p.birds.reload.length
  end
```

Could you please provide a test case that trigger the bug?

**Comment by fw42** [comment]
Hmmm. I'm not really sure why your tests passes, but the following test fails for me:
```ruby
def test_should_save_new_record_that_has_same_value_as_existing_record_marked_for_destruction_on_field_that_has_unique_index
  Bird.connection.add_index :birds, :name, unique: true
  Bird.validates :name, uniqueness: true
  Bird.belongs_to :pirate, autosave: true

  3.times { |i| @pirate.birds.create(name: "unique_birds_#{i}") }

  @pirate.birds[0].mark_for_destruction
  @pirate.birds.build(name: @pirate.birds[0].name)
  @pirate.save!

  assert_equal 3, @pirate.birds.reload.length
ensure
  Bird.connection.remove_index :birds, column: :name
end
```
message:
```
  1) Error:
TestDestroyAsPartOfAutosaveAssociation#test_should_save_new_record_that_has_same_value_as_existing_record_marked_for_destruction_on_field_that_has_unique_index:
ActiveRecord::RecordInvalid: Validation failed: Birds name has already been taken
    /home/vagrant/src/rails/activerecord/lib/active_record/validations.rb:79:in `raise_record_invalid'
    /home/vagrant/src/rails/activerecord/lib/active_record/validations.rb:43:in `save!'
    /home/vagrant/src/rails/activerecord/lib/active_record/attribute_methods/dirty.rb:29:in `save!'
    /home/vagrant/src/rails/activerecord/lib/active_record/transactions.rb:281:in `block in save!'
    /home/vagrant/src/rails/activerecord/lib/active_record/transactions.rb:337:in `block in with_transaction_returning_status'
    /home/vagrant/src/rails/activerecord/lib/active_record/connection_adapters/abstract/database_statements.rb:213:in `block in transaction'
    /home/vagrant/src/rails/activerecord/lib/active_record/connection_adapters/abstract/transaction.rb:185:in `within_new_transaction'
    /home/vagrant/src/rails/activerecord/lib/active_record/connection_adapters/abstract/database_statements.rb:213:in `transaction'
    /home/vagrant/src/rails/activerecord/lib/active_record/transactions.rb:206:in `transaction'
    /home/vagrant/src/rails/activerecord/lib/active_record/transactions.rb:334:in `with_transaction_returning_status'
    /home/vagrant/src/rails/activerecord/lib/active_record/transactions.rb:281:in `save!'
    test/cases/autosave_association_test.rb:866:in `test_should_save_new_record_that_has_same_value_as_existing_record_marked_for_destruction_on_field_that_has_unique_index'
```
Thanks for looking into this.

**Comment by fw42** [comment]
(same happens when using ```has_many :birds, autosave: true``` on ```Pirate```)

**Comment by fw42** [comment]
And as I said in the description, using ```has_many :birds, autosave: true, validate: false``` makes the test pass (because it's not validating the new bird before destroying the old one).

**Comment by sgrif** [comment]
What versions of Rails does this occur on?

**Comment by fw42** [comment]
I tried it this morning on latest master (151747ff0d13344a12b83d2f92175b7c53d2d39b).

**Comment by sgrif** [comment]
Right, I'm trying to find out if this is a regression from a previous version, and if so what the first version with this bug was. Does this also occur on all of the 4.x series?

**Comment by sgrif** [comment]
I don't think this is an issue we can resolve. The validation failing is actually reasonable behavior, when you consider that we don't attempt to save unless validations pass, and we don't destroy records which are marked until we're actually going to try and save.

Really this is an example of uniqueness validations not actually being able to validate uniqueness. (As an aside, I think many of the places that people are using uniqueness validations aren't needed, as they're often non-actionable by the end-user, in which case a unique index is all you need since you're simply verifying integrity).

The only solution I can see here would be to remove all marked records in a transaction, run validations, then rollback the transaction. However, there's just too many cases where that could lead to unexpected behavior. Destroy callbacks with side effects like deleting files would get run when they shouldn't be, any database changes in validation callbacks would be unexpectedly rolled back, etc.

For that reason, I don't think this is an issue that we can fix.

**Comment by fw42** [comment]
ok fair enough, thanks anyway
