### ISSUE TITLE
ruby-2.2.0 + activesupport-4.2.0 =>  cannot load such file -- test/unit/assertions (LoadError)

### ISSUE THREAD

**Issue by the-teacher** [rails/rails#18572]
hello!

When I try to run rspec tests on ruby-2.2 I have following exception

```ruby
/Users/admin/.rvm/gems/ruby-2.2.0/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:274:
in `require': cannot load such file -- test/unit/assertions (LoadError)
```

Probably, it can be related with `rspec-rails-2.14.0`. If you think so - just close this issue.
Thanks

**Comment by the-teacher** [comment]
looks like  rspec 2.14 missing dependency

```ruby
require 'delegate'
require 'active_support/concern'
require 'test/unit/assertions'

module RSpec
  module Rails
    class AssertionDelegator < Module
```

**Comment by giedriusr** [comment]
Having same issue.

**Comment by the-teacher** [comment]
@giedriusr you need to find gem which based on ruby version <= `2.2` and update or remove it.
some core parts was removed from ruby 2.2

**Comment by giedriusr** [comment]
@the-teacher adding 
```ruby
gem 'test-unit'
``` 
to my `Gemfile` did the job! Thanks.

**Comment by the-teacher** [comment]
@giedriusr :+1:

**Comment by apux** [comment]
I have the same issue with ruby 2.2.1 and rails 4.0.13, and adding 'test-unit' to my gemfile didn't work.

**Comment by BrainBuzzer** [comment]
thanks **@the-teacher** It helped a lot @brainbuzzerme
