### ISSUE TITLE
blank? documentation vs. implementation viz-a-viz handling of false

### ISSUE THREAD

**Issue by palfvin** [rails/rails#18583]
I understand that making false.blank? == true would be a significant breaking change. I personally think this would be worth it, as `false` seems intuitively to be very much "not blank"

If we're going to keep the implementation as is, however, then I think we should remove or replace the API documentation which rationalizes the method as a more compact alternative to `nil? || empty?`. That is not only misleading; it adds insult to injury.

**Comment by rafaelfranca** [comment]
Thank you so much for the issue but we don't take features requests in the issue tracker. Use the rails core mailing list

**Comment by palfvin** [comment]
I meant this to be a bug report against the inline API documentation in the code (i.e. that the method is implicitly documented in terms of `nil?`). Is this not the right place for that?

**Comment by rafaelfranca** [comment]
The documentation is not saying that it is equals to `nil? || empty?`, but that it can be used to simplify this expression, what is true.

**Comment by palfvin** [comment]
I don't mean to be argumentative, but I don't see how something that produces a different result for a subset of the domain can be considered a "simplification" of the expression. At the very least, I would contend that it is a misleading simplification that ought to be changed or more explicitly annotated.

**Comment by shunsukeaida** [comment]
Perhaps you could provide a real world example where you call `blank?` for something expected to be `true` or `false`?

**Comment by palfvin** [comment]
The canonical example is `validate presence: true` for boolean ActiveRecord
fields where you are trying to ensure that the field has been set (i.e. is
not `nil`).
