### ISSUE TITLE
How about an absent? method to fix the problem with blank?

### ISSUE THREAD

**Issue by palfvin** [rails/rails#18584]
Given the problem of `false.blank?` being `true`, how about introducing an `absent?` method which would  be defined in terms of `nil?` instead of `!!self`? On a related point, perhaps we could introduce a configuration option which would allow the `absence` and `presence` validators to be defined in terms of `absent?` rather than `blank?`.

**Comment by rafaelfranca** [comment]
Thank you so much for the issue but we don't take features requests in the issue tracker. Use the rails core mailing list
