### ISSUE TITLE
Rails 4.2 SQLite3 regression: Encoding::UndefinedConversionError: "\xE9" from ASCII-8BIT to UTF-8

### ISSUE THREAD

**Issue by marutosi** [rails/rails#18580]
Redmine team ported Redmine from Rails 4.1 to 4.2.
We got errors on SQLite3.

http://www.redmine.org/builds/logs/build_trunk_sqlite3_ruby-2.1_2301.html

```
 22) Error:
ChangesetTest#test_invalid_utf8_sequences_in_comments_should_be_replaced_latin1:
Encoding::UndefinedConversionError: "\xE9" from ASCII-8BIT to UTF-8
    test/unit/changeset_test.rb:417:in `test_invalid_utf8_sequences_in_comments_should_be_replaced_latin1'
```

As you see this line, we test replacing invalid encoding character.
http://www.redmine.org/projects/redmine/repository/revisions/13893/entry/trunk/test/unit/changeset_test.rb#L407

```ruby
str1 = "Texte encod\xe9 en ISO-8859-1.".force_encoding("UTF-8")
...
c = Changeset.new(...)
....
assert_equal "Texte encod? en ISO-8859-1.", c.comments
```

MySQL tests pass, so I think this is regression of Rails 2.2 SQLite3 adapter.

**Comment by marutosi** [comment]
This is workaround fix.
http://www.redmine.org/projects/redmine/repository/revisions/13896

**Comment by sgrif** [comment]
Can you provide a script we can use to easily reproduce the issue, using this as a template? https://github.com/rails/rails/blob/master/guides/bug_report_templates/active_record_master.rb
