### ISSUE TITLE
Setting attributes in ActiveRecord is not thread safe

### ISSUE THREAD

**Issue by bpardee** [rails/rails#18592]
If you set attributes to the same instance in separate threads, there is a race condition where your attribute might not actually get set.

I've created a test program (along with a workaround if you set the environment variable FIX_FOO)  that illustrates the problem [here] (https://gist.github.com/bpardee/b700fa1da841a9b933ca).  If you run this program, the output should be 10 empty hashes but a typical output when run with jruby-1.7.18 is as follows:

{}
{"field46"=>nil, "field68"=>nil, "field69"=>nil, "field74"=>nil}
{"field17"=>nil, "field27"=>nil, "field35"=>nil, "field36"=>nil, "field47"=>nil, "field48"=>nil, "field50"=>nil, "field51"=>nil}
{}
{"field11"=>nil, "field44"=>nil}
{"field19"=>nil, "field34"=>nil, "field39"=>nil}
{}
{"field56"=>nil, "field57"=>nil, "field59"=>nil}
{"field65"=>nil}
{"field68"=>nil}

I tested against Rails 4.1.8 and 4.2.0.  I tried to do 5.0Alpha but I think this requires ruby 2.1 or 2.2 and jruby only has a 2.0 mode?.

**Comment by fxn** [comment]
Not sure AR instances are supposed to be thread-safe (classes are).

@tenderlove c/d

**Comment by thedarkone** [comment]
No, instances of AR are not guaranteed to be thread-safe, the internal machinery is too complex for that.

**Comment by bpardee** [comment]
Wouldn't just using a ThreadSafe::Hash for the attributes resolve the issue?

**Comment by rafaelfranca** [comment]
@bpardee no, it wont. As @thedarkone said, the internal of Active Record instance is too complex to be thread-safe.
