### ISSUE TITLE
How to fix "Calling URL helpers with string keys"

### ISSUE THREAD

**Issue by ineu** [rails/rails#18609]
Trying to upgrade rails from 4.1.9 to 4.2.0, I receive following error:

```
DEPRECATION WARNING: Calling URL helpers with string keys controller, action is deprecated. Use symbols instead. (called from expander at (pry):24)
ArgumentError: comparison of Array with Array failed
```

So basically there are two issues here:
1. Deprecation warning
2. Real error

The problem with 1 is that I don't explicitly pass any string keys to the helper, but rather pass `params`, like `root_path(params)`. How should I fix my code to avoid this warning, if the code is not involved in it, but rails internals are?

The problem 2 happens because after `params.merge(foo: 1, bar: 2)` (note symbol keys) I receive following in Journey::Formatter#generate:

```
[1] pry(#<ActionDispatch::Journey::Formatter>)> constraints
=> {:controller=>"survey_distributions",
 :action=>"show",
 :id=>"cd681f8267471232",
 "ignore"=>"me",
 "sctest"=>"1",
 "id"=>"cd681f8267471232",
 "foo"=>1,
 "bar"=>2,
 "controller"=>"survey_distributions",
 "action"=>"expander"}
```

So there are basically two 'controller', two 'action', 'foo' and 'bar' are converted to strings. Obviously sort fails comparing keys of mixed types.
It doesn't seem like proper behavior because Rails fails to work correctly with its own `params`.
Is it possible to fix this one as well without converting params to Hash with symbolized key in every place where I need to use route helpers? Thank you.

**Comment by danielpuglisi** [comment]
Same behaviour here. Except for the duplicated controller and action key. 

I also use `params` to build paths in certain areas and all the keys are returned as strings.

**Comment by brainopia** [comment]
@ineu Warning has been removed from master. And I've created a pull-request with a fix for the error.

**Comment by pixeltrix** [comment]
@ineu @danielpuglisi shoving the whole params hash into a url helper is asking for trouble and could lead to an XSS security problem so it's not something we'd want to support. It's easy enough to slice out the keys and symbolize that known set so it's really an application level concern.

**Comment by ineu** [comment]
@pixeltrix Agree, but it should have been mentioned in Changelog.

**Comment by pixeltrix** [comment]
@ineu it was: 4d84922840deb89754f5b5fb61ebea0aeadc52df

**Comment by philrosenstein** [comment]
@pixeltrix just wondering if you have any feedback on my particular situation:

Here is what I have done to avert this deprecation warning.  I suppose it is more secure than passing the raw params, but it feels clunky to me:

    @search_params = params.permit(%w[ utf8 commit controller action ]).symbolize_keys 
    @search_params[:q] = params[:q] # add :q back in since permit only allows scalars

What will the behaviour be once this deprecated functionality is fully gone?  Will the 'controller' and 'action' keys be quietly removed from params?  That could lead to some frustrating bugs I'd imagine.  Or would they automatically converted to symbols?  In that case, I'd end up removing these 2 lines that I've had to add just to suppress the warning.  It strikes me as odd (or maybe its not?) that I would have to make one change to suppress a deprecation warning, and then in the future make another change when the function is actually deprecated.

**Comment by pixeltrix** [comment]
> Here is what I have done to avert this deprecation warning. I suppose it is more secure than passing the raw params, but it feels clunky to me

Whenever I do a search these days I generally use a class to represent the search request and pass in the params hash to `initialize` - that tends to make your controller and view code much clearer.

> What will the behaviour be once this deprecated functionality is fully gone? Will the 'controller' and 'action' keys be quietly removed from params? That could lead to some frustrating bugs I'd imagine.

I suspect they'll be left as string keys and appended to the URL as query params.

**Comment by danielricecodes** [comment]
pretty easy solution (however, the XSS concerns are still valid) just to get the warning to go away:

`params.except(:controller, :action)` FTW.
