### ISSUE TITLE
Anchor is not available in ActionDispatch::Request

### ISSUE THREAD

**Issue by tilo** [rails/rails#18603]
Rails 4.1.7

`request.original_fullpath` and `request.original_url` do not contain the anchor portion of the URL

A convenience method to get to the anchor might be good as well.

e.g.

clicking on `= link_to 'this' , products_path(anchor: there)`  will result in the response.fullpath to be '/products' .. without the '#there' anchor.

**Comment by rafaelfranca** [comment]
The anchor is not sent to the server side so there is no way to retrieve this information.
