### ISSUE TITLE
Stack level too deep from LocalCache on file upload 

### ISSUE THREAD

**Issue by pehrlich** [rails/rails#18608]
In development: testing uploading a file, causes the following:

`22:28:48 web.1  | [2015-01-19 22:28:48] ERROR SystemStackError: stack level too deep
22:28:48 web.1  | 	/Users/pehrlich/.rvm/gems/ruby-2.1.5/gems/activesupport-4.1.8/lib/active_support/cache/strategy/local_cache_middleware.rb:33`

... Which appears to be actually a `Rack::Utils::InvalidParameterError`

Even with [this ruby patch](https://coderwall.com/p/eqmmyg/full-backtrace-for-systemstackerror), there appears to be no more verbose output.  I suppose the next step would be to add customized logging to the middleware to find out more.

EDIT: reproed with a 200kb JSON file..

EDIT2: It looks like was being caused by a JSON parsing error, on a string which was not meant to be parsed as JSON.  After removing the catch inside this middleware, i was able to alter `rack-1.5.2/lib/rack/utils.rb:126` to actually print out its error messages instead of eating them, and saw this:

`23:11:08 web.1  | expected Hash (got NilClass) for param `x{"metadata":{"formatVersion":2,"generatedBy":"simulatorFrontend","frames":64,"modified":"2015-01-20T06:55:31.229 00:00"},"frames":'`.

No idea why this was getting parsed as JSON (fault of Rails? jQuery?) but assigning the string as instead a value in a JS object, and then POSTing that object, caused no parsing to be attempted (yay).

**Comment by tenderlove** [comment]
@pehrlich are you able to reproduce this with a newly created app and some JSON?
