### ISSUE TITLE
Time.zone.local doesn't raise an exception during the dead hour on DST

### ISSUE THREAD

**Issue by sobrinho** [rails/rails#18615]
At the begin of DST rails is accepting the 0 hour which in fact doesn't exists:

``` ruby
Time.zone.local(2014, 10, 19, 0, 30)
#=> Sun, 19 Oct 2014 01:30:00 BRST -02:00

Time.zone.local(2014, 10, 19, 1, 30)
#=> Sun, 19 Oct 2014 01:30:00 BRST -02:00

Time.zone.local(2014, 10, 19, 2, 30)
#=> Sun, 19 Oct 2014 02:30:00 BRST -02:00
```

In fact it is returning the next hour for some reason, causing a really strange behaviour:

``` ruby
Time.zone.local(2014, 10, 19, 0, 30) == Time.zone.local(2014, 10, 19, 1, 30)
#=> true
```

I think it makes more sense to raise an exception as happens when you specify a invalid month, day, hour, minute or second:

``` ruby
Time.zone.local(2014, 10, 19, 1, 60) # 60 minutes doesn't exists
ArgumentError: invalid date

Time.zone.local(2014, 10, 19, 25, 30) # 25 hours doesn't exists
ArgumentError: invalid date
```

Makes sense?

**Comment by raybaxter** [comment]
This is the way that Ruby's `Time.local` works.

    2.0.0-p247 :001 > Time.local(2015,3,8,2,30,00)
     => 2015-03-08 03:30:00 -0700 

Without looking at the code, I would expect that AS uses the underlying Ruby methods. In either case, I would expect them to behave consistently. Perhaps this issue should be raised on Ruby, not on AS.

**Comment by rafaelfranca** [comment]
Right.

**Comment by sobrinho** [comment]
@raybaxter makes sense, I will report on ruby, thanks! :+1:

**Comment by sobrinho** [comment]
For who wants to follow: https://bugs.ruby-lang.org/issues/10767
