### ISSUE TITLE
undefined method 'assert_enqueued_with'

### ISSUE THREAD

**Issue by lazaronixon** [rails/rails#18624]
assert_enqueued_with is not available for ActiveSupport::TestCase,  like showed on rails guides it should work.
http://guides.rubyonrails.org/testing.html#custom-assertions-and-testing-jobs-inside-other-components
````ruby
require 'test_helper'
 
class ProductTest < ActiveSupport::TestCase
  test 'billing job scheduling' do
    assert_enqueued_with(job: BillingJob) do
      product.charge(account)
    end
  end
end
````

**Comment by rafaelfranca** [comment]
Yes. It should be `ActiveJob::TestCase`. Fixed thanks.

**Comment by acjay** [comment]
@rafaelfranca 

What if you want to test whether a job is enqueued from a controller?

**Comment by acjay** [comment]
Nevermind, figured out I can do this:

```
class MyControllerTest < ActionController::TestCase
  include ActiveJob::TestHelper # needed for assert_enqueued_with helper
  
  # ...

end
```

Might be a good idea to add this to the documentation? In many cases it seems like the enqueuement (sp?) of a job wouldn't be done within the job itself, unless one job is farming out work to another.

**Comment by benlakey** [comment]
Why was this closed without action? This seems like legitimate documentation feedback?

**Comment by janwerkhoven** [comment]
Great find @acjay !

This also seems to work in integration request tests:

```ruby
# test/integration/requests/some_resource_request_test.rb

require 'test_helper'

class SomeResourceRequestTest < ActionDispatch::IntegrationTest
    include ActiveJob::TestHelper
    
    # ...
end
```
Rails 5 + Minitest
