### ISSUE TITLE
Call `model_name` on result from `to_model` in Placeholderable

### ISSUE THREAD

**Issue by mcls** [rails/rails#18646]
Shouldn't `model_name` be called on the result from `to_model` instead of the class on the following line?
https://github.com/rails/rails/blob/v4.2.0/actionview/lib/action_view/helpers/tags/placeholderable.rb#L15

It's what I was lead to believe after reading the docs for `#to_model`.
https://github.com/rails/rails/blob/v4.2.0/activemodel/lib/active_model/conversion.rb#L25-L38

**Comment by rafaelfranca** [comment]
Yes, it should. Could you open a PR?

**Comment by mcls** [comment]
Will do

**Comment by solnic** [comment]
I fear a similar mistake might be in other places too
