### ISSUE TITLE
Serializing ActionController::Parameters as Hash doesn't ensure the serialization is a Hash

### ISSUE THREAD

**Issue by sb8244** [rails/rails#18648]
This may or may not be a bug. I could see it being expected behavior (just let me know and close), but wanted to touch base just in case it is a bug.

I am accepting parameters as a hash and storing it in my model using:

```ruby
serialize :params, Hash
```

In my full rails app, everything works great and the attribute appears to act like a hash. 

However, in my only ActiveRecord only Ernie stack, I kept getting an ::ActionController not found error. This is because the params come in as `ActionController::Parameters`, where `.is_a?(Hash) == true` and then `YAML.load` crashes.

Best,
Steve

**Comment by rafaelfranca** [comment]
You should make it a hash before assigning. In Rails 5 `ActionController::Parameters` will not inherit from Hash anymore and in Rails 4.2 we already discouraging dealing with parameters as it was a Hash.

**Comment by sb8244** [comment]
Thanks Rafael.
