### ISSUE TITLE
HTML fallback causes rendering of wrong views in JS requests

### ISSUE THREAD

**Issue by SebastianVomMeer** [rails/rails#18656]
Given two views

    app/views/animals/new.js.erb
    app/views/dogs/new.html.erb

and a controller:

    class DogsController < AnimalsController
      def new
      end
    end

I don't need a specific new.js for dogs, so normally view inheritance should choose the one from animals. However, requesting dog's new action with format JS delivers the HTML content of app/views/dogs/new.**html**.erb. Is this intended behaviour?

I think this is caused by a workaround to allow HTML partials in JS views (https://github.com/rails/rails/blob/master/actionview/lib/action_view/lookup_context.rb#L207). But responding JS requests with HTML seems like a bug to me.

**Comment by rafaelfranca** [comment]
Thank you for the report. This is a dup of #5892
