### ISSUE TITLE
Migration to remove a "references" writes "remove_foreign_key" after "remove_references"

### ISSUE THREAD

**Issue by demery** [rails/rails#18664]
I created a migration to remove a references/belongs_to column from a model:

```bash
$ bin/rails g migration remove_title_from_copies title:belongs_to
```

The generated migration was:

```ruby
class RemoveTitleFromCopies < ActiveRecord::Migration
  def change
    remove_reference :copies, :title, index: true
    remove_foreign_key :copies, :titles
  end
end
```

When run, this migration raises a `StatementInvalid` error:

```
ActiveRecord::StatementInvalid: Mysql2::Error: Cannot drop index 'index_copies_on_title_id': needed in a foreign key constraint: ALTER TABLE `copies` DROP `title_id`
```

The order is correct for adding a `references` column -- `add_reference` then `add_foreign_key`, but not for removing it. When I reversed the order of the two commands the migration worked, but rollback failed. Splitting the migration into separate `up` and `down` methods with opposite command orders works for both migration and rollback.

```ruby
class RemoveTitleFromCopies < ActiveRecord::Migration
  def up
    remove_foreign_key :copies, :titles
    remove_reference :copies, :title, index: true
  end

  def down
    add_reference :copies, :title, index: true
    add_foreign_key :copies, :titles
  end
end
```

**Comment by jvnill** [comment]
In the current activerecord migration generator, the `remove_foreign_key` line has already been removed as shown in https://github.com/rails/rails/blob/master/activerecord/lib/rails/generators/active_record/migration/templates/migration.rb#L31.

I guess this is a more proper implementation since adding foreign key constraints are optional.  Not sure why it was the default migration.  I've forked rails and added changes to the generator which now generates a reversible block instead of just the `remove_reference` line.

https://github.com/jvnill/rails/commit/8219b164aee44d3861fdfa8f97cf93c6ac9042cb

Now, if I can only figure out how to run the tests for the generators.

**Comment by senny** [comment]
Considering that we removed the default foreign key generation on `master` I think we should revert #17759 on `4-2-stable` as well and wait for 5 to make a decision on wether this option should be default or not.

/cc @rafaelfranca @sgrif @derekprior

**Comment by sgrif** [comment]
We didn't remove it we changed it to use an option on references

**Comment by senny** [comment]
@sgrif This is a session from a newly generated application with `--dev` from `master`:

```
$ bin/rails g model user name:string                                                                                                             
      invoke  active_record
      create    db/migrate/20150125110311_create_users.rb
      create    app/models/user.rb
      invoke    test_unit
      create      test/models/user_test.rb
      create      test/fixtures/users.yml

$ bin/rails g model article user:reference
      invoke  active_record
      create    db/migrate/20150125110324_create_articles.rb
      create    app/models/article.rb
      invoke    test_unit
      create      test/models/article_test.rb
      create      test/fixtures/articles.yml

$ cat db/migrate/20150125110324_create_articles.rb
class CreateArticles < ActiveRecord::Migration
  def change
    create_table :articles do |t|
      t.reference :user

      t.timestamps
    end
  end
end
```

As far as I can remember we not only changed to a `:foreign_key` option but also removed it as a default.

**Comment by senny** [comment]
Having the flag present as an option on `add_reference` and `remove_reference` solves this issue. It might be best to backport the patch from `master` which introduced the option. 

@sgrif what do you think?

**Comment by sgrif** [comment]
Backporting the option feels pretty low-risk to me. If that's easier than the alternative, I think we should go with that.

**Comment by senny** [comment]
A quick update. This bug was present on `master` as well. See https://github.com/rails/rails/commit/a893718c3165aa6ef6b2b500f7922954ba21eb02

Having the flag makes the generator output a lot nicer. I'll look into a possible backport for `4-2-stable`.

**Comment by senny** [comment]
Fixed and backported to `4-2-stable`.

@demery thank you for reporting. :yellow_heart:

**Comment by raelgc** [comment]
Not sure if this is the same problem described here (it appears to be, sorry if not), but I tried to create a table with foreign keys and a triple index with the following migration:

```ruby
class CreateSurveyAnswers < ActiveRecord::Migration

  def change
    create_table :survey_answers do |t|
      t.references :survey_participation, foreign_key: {on_delete: :cascade}
      t.references :survey_question, foreign_key: {on_delete: :cascade}
      t.references :survey_question_option, foreign_key: {on_delete: :cascade}
      t.timestamps null: false
    end
   add_index :survey_answers, [:survey_participation_id, :survey_question_id, :survey_question_option_id], unique: true, name: 'survey_answer_unique_index'
  end

end
```

Then, in the `db:rollback` it failed, because it tried to remove the index first, then the foreign key.

To fix it, I changed to have `up` and `down` methods:

```ruby
class CreateSurveyAnswers < ActiveRecord::Migration

  def up
    create_table :survey_answers do |t|
      t.references :survey_participation, foreign_key: {on_delete: :cascade}
      t.references :survey_question, foreign_key: {on_delete: :cascade}
      t.references :survey_question_option, foreign_key: {on_delete: :cascade}
      t.timestamps null: false
    end
   add_index :survey_answers, [:survey_participation_id, :survey_question_id, :survey_question_option_id], unique: true, name: 'survey_answer_unique_index'
  end

  def down
    remove_foreign_key :survey_answers, :survey_participations
    remove_foreign_key :survey_answers, :survey_questions
    remove_foreign_key :survey_answers, :survey_question_options
    remove_index :survey_answers, name: 'survey_answer_unique_index'
    drop_table :survey_answers
  end

end
```

If I'm supposed to create this in other way, I'll appreciate any clarification.
