### ISSUE TITLE
`to_sql` does not work as intended when `as` is used.

### ISSUE THREAD

**Issue by fdeschenes** [rails/rails#18675]
**Without `as`, works as intended**  
```
2.1.0 :001 > Post.where(id: 2).to_sql
 => "SELECT \"posts\".* FROM \"posts\" WHERE \"posts\".\"id\" = 2" 
```

**With `as`, does not work as intended**
```
2.1.0 :001 > Post.where(id: 2).as('post').to_sql
 => "(SELECT \"posts\".* FROM \"posts\" WHERE \"posts\".\"id\" = $1) post" 
```

I expect the returned value to be `"(SELECT \"posts\".* FROM \"posts\" WHERE \"posts\".\"id\" = 2) post"`

**Comment by matthewd** [comment]
See #18379; you're (maybe unknowingly) using an Arel method; its return value has some similar methods to AR::Relation, including `to_sql`... but it's not the same.
