### ISSUE TITLE
chained having statements should be grouped with parentheses (like where)

### ISSUE THREAD

**Issue by dontfidget** [rails/rails#18684]
On rails 4.1.8, I see this in the rails console:

```
> User.group(:id).having(id: 1).having('id = 1 || id = 2').to_sql
"SELECT `users`.* FROM `users`  GROUP BY id HAVING `users`.`id` = 1 AND id = 1 || id = 2"
```
whereas each `where` statement is surrounded by parentheses:

```
> User.where(id: 1).where('id = 1 || id = 2').to_sql
"SELECT `users`.* FROM `users`  WHERE `users`.`id` = 1 AND (id == 1 || id == 2)"
```

This is a bug, no?

**Comment by sgrif** [comment]
Can you test if this is still present on 4.2 and master?

**Comment by sgrif** [comment]
Fixed by https://github.com/rails/rails/commit/c2c95cd279c988e7bd94008264e956e30b78c9ec

**Comment by dontfidget** [comment]
Thanks for solving this one.  Sorry I didn't get around to testing it.  I do wonder if this is ultimately an arel problem.  Using the same code for `where` would be expected to work around an underlying arel problem since the problem doesn't exist for `where`.

**Comment by sgrif** [comment]
Arel doesn't group `where`, either. We do it in Active Record.
