### ISSUE TITLE
ActiveRecord is failing to establishing an association

### ISSUE THREAD

**Issue by pruchai** [rails/rails#18682]
I have a very detailed explanation of the problem here:

http://stackoverflow.com/questions/28059189/unable-to-update-or-create-records-using-post-with-strong-parameters-and-nested

TLDR: I am able to establish an association between 2 records  by hand in `rails console`

    contact = Contact.find_by_id(1)
    command = Command.find_by_id(1)
    contact.host_notification_commands << command

However, doing the same thing via controller and POSTing nested parameters does not work.

    contact = Contact.find_by_id(params[:id])
    contact.update(safe_params)

It fails with:

    Couldn't find Command with ID=1 for Contact with ID=1

Both of these records (contact and command) exist in the database and I am trying to establish this association, why is Rails trying to find it?

I made a simple rake task to remove any and all external factors from the equation (my Angular views, POST data, strong_parameters, etc). I simply defined a nested JSON object and tried to update the database, but it failed with the same error as above, so I believe the problem is somewhere in my models.

Please take a look at this Gist
https://gist.github.com/pruchai/6afe74b170da2a3d307f

**Comment by rafaelfranca** [comment]
Could you create an reproduction script with this template https://github.com/rails/rails/blob/master/guides/bug_report_templates/active_record_master.rb?

**Comment by pruchai** [comment]
@rafaelfranca: Here you go

https://gist.github.com/pruchai/c2e190611aa02c5a03b9

It fails on the last test, but I am not entirely sure how to fix that.

**Comment by sgrif** [comment]
@pruchai The reproduction script you provided passes.

**Comment by pruchai** [comment]
@sgrif 

Correct. I believe I was mis-understanding framework functionality. I assumed that when I post a nested form to the controller and if a relationship between 2 objects referenced in the form does not already exist, it would be automatically created by Rails. I was wrong... 

Please close this issue.
