### ISSUE TITLE
Scaffold generator invokes responder_controller by default if Responders is the dependency of another gem

### ISSUE THREAD

**Issue by noinkling** [rails/rails#18687]
For instance, Devise (3.4.0+) has the recently extracted Responders gem as a dependency. Adding Devise to a Rails 4.2 gemfile causes the scaffold generator to invoke the `responders_controller` generator rather than the `scaffold_controller` generator, even though Responders isn't explicitly specified in the gemfile.

The readme for Responders provides an option to change it back, but it seems weird to expect developers to find that option if it's simply an unwanted side-effect of adding another gem. I'm not sure if it's a Rails or a Devise or a Responders issue though.

**Comment by rafaelfranca** [comment]
Agree. But this issue is more a responders issue than a Rails issue. Please open it at responders issue tracker.

**Comment by noinkling** [comment]
[Done](plataformatec/responders#113).
