### ISSUE TITLE
ActiveRecord counter_cache column calculated even when not specified in 4.2.0

### ISSUE THREAD

**Issue by negative** [rails/rails#18689]
I found this unexpected behavior while updating my apps to 4.2.0 from 4.1.9. It is a breaking change for me because I am managing counter columns manually with the assumption that Rails doesn't increment them unless I explicitly specify `counter_cache` on my `belongs_to`.

Example code:

``` ruby
# Gemfile
gem 'activerecord', '4.2.0'
# gem 'activerecord', '4.1.9'
gem 'sqlite3'
```

``` ruby
require 'bundler'
Bundler.setup(:default)
require 'active_record'

ActiveRecord::Base.establish_connection(adapter: 'sqlite3', database: ':memory:')

ActiveRecord::Schema.define do
  create_table :users do |t|
    t.integer :comments_count, null: false, default: 0
  end
  create_table :comments do |t|
    t.integer :user_id
  end
end

class User < ActiveRecord::Base
  has_many :comments
end
class Comment < ActiveRecord::Base
  belongs_to :user
end

user = User.create!(comments: [Comment.new])

puts "user.comments_count: #{user.comments_count}"
puts "user.reload.comments_count: #{user.reload.comments_count}"
```

I get:

``` ruby
# Rails 4.1.9
user.comments_count: 0
user.reload.comments_count: 0

# Rails 4.2.0
user.comments_count: 1
user.reload.comments_count: 0
```

Also, if `counter_cache` is specified like so:
``` ruby
class Comment < ActiveRecord::Base
  belongs_to :user, counter_cache: true
end
```

It seems the in memory counter is fixed to 1:
``` ruby
user = User.create!(comments: [Comment.new, Comment.new])
# Rails 4.1.9
user.comments_count: 0
user.reload.comments_count: 2

# Rails 4.2.0
user.comments_count: 1
user.reload.comments_count: 2
```

**Comment by secondwtq** [comment]
I found this: 

* SHA: ac01db533eebb60c6ffe9d56252274e605370dd5

Maybe has_many needs the same fix, too.

**Comment by negative** [comment]
@secondwtq Thanks for tracking down the commit. I was wondering if the `*_count` column being updated when `counter_cache` is not specified (or even set to false) in the `belongs_to` is the correct behavior or not.

**Comment by sgrif** [comment]
So there's a couple of issues that I'd like to address independently. For the case where the counter cache is unspecified, I'd say the bug is that we are only updating in memory, but not in the database. In Rails 4.1, we are inconsistent about whether we update when unspecified or not. For example:

```
user = User.create!(comments: [Comment.new])
user.comments.destroy_all
```

That will set the counter cache to -1 both in memory and in the database. I think we need to address whether specifying the counter cache is required, or based on convention, and update the documentation accordingly.

As for the case with `counter_cache: true`, yeah that's definitely a bug which I'll dig into.

**Comment by secondwtq** [comment]
@segif That's because the hash

```ruby
comments: [Comment.new, Comment.new]
```
is wrapped to
```ruby
[[Comment.new, Comment.new]]
```

in the call stack (maybe at ActiveRecord::Associations::concat) and its length is 1.

If you try to append with <<, you'll get:

```ruby
user = User.create!(comments: [Comment.new, Comment.new])

user.comments << Comment.new << Comment.new

user.comments_count: 3
user.comments_count: 4
```
