### ISSUE TITLE
header fetching does not work any more with rails 4.2

### ISSUE THREAD

**Issue by dspaeth-faber** [rails/rails#18698]
Hi,

I have the following setup:

routes.rb
```ruby
   get 'is-alive-token' => 'heart_beat#index'
```
heart_beat_controller,rb

```ruby
class HeartBeatController < ApplicationController
  def index
    render json: {}, status: 200
  end
end
```

When I use:

```
  curl -I http://127.0.0.1:3000/is-alive-token
```

prior rails 4.2 I got `HTTP/1.1 200`

with rails 4.2 I get `HTTP/1.1 404` + an exception

```ruby
ActionController::RoutingError (No route matches [HEAD] "/is-alive-token")
```

Is there a new directive within the routes to get HEAD calls up and running?

regards
dieter

**Comment by dspaeth-faber** [comment]
Is it a duplicate of #18513 ?

**Comment by rafaelfranca** [comment]
Don't sees so

**Comment by senny** [comment]
@dspaeth-faber is your issue reproducible using [this script](https://github.com/rails/rails/blob/master/guides/bug_report_templates/action_controller_gem.rb) as a starting point?

**Comment by dspaeth-faber** [comment]
Ok, I can reproduce it. It happens when I mount a rack-app on root-path:


```ruby

unless File.exist?('Gemfile')
  File.write('Gemfile', <<-GEMFILE)
source 'https://rubygems.org'
gem 'rails', github: 'rails/rails'
gem 'arel', github: 'rails/arel'
gem 'grape', '0.9.0'
  GEMFILE
  system 'bundle'
end
require 'bundler'
Bundler.setup(:default)
require 'rails'
require 'action_controller/railtie'

require 'grape'

class API < Grape::API

end

class TestApp < Rails::Application
  config.root = File.dirname(__FILE__)
  config.session_store :cookie_store, key: 'cookie_store_key'
  secrets.secret_token = 'secret_token'
  secrets.secret_key_base = 'secret_key_base'
  config.logger = Logger.new($stdout)
  Rails.logger = config.logger
  config.log_level = :debug
  routes.draw do
    get '/is-alive' => 'test#index'
    mount API => '/' #, as: 'api'
  end
end
class TestController < ActionController::Base
  include Rails.application.routes.url_helpers
  def index
    render  json: {}, status: 200
  end
end
require 'minitest/autorun'
require 'rack/test'
class BugTest < Minitest::Test
  include Rack::Test::Methods
  def test_returns_success
    head '/is-alive'
    assert last_response.ok?
  end

  private
  def app
    Rails.application
  end
end

```

**Comment by pixeltrix** [comment]
Suspect this is down to this commit d3eb92d - I'll take a look at it

**Comment by dspaeth-faber** [comment]
I did only take a quick glance but wouldn't it be good to support a HEAD request with a keyword
like it is done with get, post and so on? Maybe it will make it easier to fix this bug that way.

Also at the moment I have no documented way to set a new action for head requests.

**Comment by pixeltrix** [comment]
> I did only take a quick glance but wouldn't it be good to support a HEAD request with a keyword
like it is done with get, post and so on? Maybe it will make it easier to fix this bug that way.

Do you mean a `head` method in the routes.rb DSL or responding to a HEAD request? Obviously we do the latter but the former may be worth doing though I've vary rarely seen one in the wild.

> Also at the moment I have no documented way to set a new action for head requests.

Does this not work?

``` ruby
match '/ping', to: 'status#ping', as: 'ping', via: :head` 
```

**Comment by dspaeth-faber** [comment]
> Do you mean a head method in the routes.rb DSL or responding to a HEAD request? 

Yes. A DSL method would be nice. 

> ... but the former may be worth doing though I've vary rarely seen one in the wild. 

Nobody knows the way, so nobody use it ;)
I did only see this [question](http://stackoverflow.com/questions/10439023/head-http-requests-in-rails-3) on stackoverflow. With a `head` DSL method you can get rid of the `if request.head?` statement.

I think it is a good thing for heart beak checks and maybe API's can profit too.

> ```ruby match '/ping', to: 'status#ping', as: 'ping', via: :head ```

Works just fine.

**Comment by jwaldrip** [comment]
My heartbeat on rails 4.2 responds just fine.

**Comment by dspaeth-faber** [comment]
@jwaldrip It's a special situation. Look at the test case. It only happen when you mount a rack-app with mount path '/'.
