### ISSUE TITLE
ParamsParser too lenient about incoming JSON

### ISSUE THREAD

**Issue by thegcat** [rails/rails#18699]
I've already scratched my itch by sidestepping the built-in JSON handling in ParamsParser, but I think this still is wrong behaviour.

A current default Rails app will accept raw inputs as JSON that are not JSON at all. For example, `POST abcd` will correctly return a `400 Bad Request`, `POST 1234` doesn't though, and this will be passed on to the controller. The effects are among others, that malformed JSON might be reported as `422 Unprocessable Entity` instead of `400 Bad Request`.

**Comment by thegcat** [comment]
See https://github.com/thegcat/quirky_json for an example app.

```
curl -w '%{http_code}' -H "content-type: application/json" --data '1234' -X POST http://localhost:3000
```

Result: 200. Expected: 400.

**Comment by chancancode** [comment]
Hm, I see you point. So you are suggesting that we should only accept valid JSON documents (arrays and objects) and the JSON primitive values? (booleans, numbers, strings).

I can't image why you would want to use the latter, but on the other hand I would not be surprised at all if there are people depending on that behavior. I'm not sure how safe this is to change, and whether the benefits are worth the risk. But since we are doing 5.0, perhaps that's fine.

@jeremy thoughts?

**Comment by jeremy** [comment]
If I recall, this responsibility falls to the JSON parser currently. Some parsers gladly accept bare primitives and others accept documents only. Requiring a JSON document is sensible to me, but I'm sure there's more backstory & compat concerns.

**Comment by thegcat** [comment]
I did a little digging: the json parsing from [way back when was already done by `ActiveSupport::JSON.decode`](https://github.com/rails/rails/commit/4d594cffcfc93b37fad4e423ec8593299e50133c#diff-8f1d0b5dd5bc3bd139113764af36aa2eR409), at that time [`ActiveSupport::JSON.decode` was a very different beast though](https://github.com/rails/rails/blob/4d594cffcfc93b37fad4e423ec8593299e50133c/activesupport/lib/active_support/json/decoding.rb#L11). I have no idea how it would have treated parsing just a string made of numbers only though.

The quirks mode, which allows those invalid JSONs to be parsed without error, has been added in 52fb1a9, somewhat ironically because "ActionPack depends on [it]".

If I change `ParamsParser` to strictly parse JSON, [this test fails](https://github.com/rails/rails/blob/master/actionpack/test/dispatch/request/json_params_parsing_test.rb#L139-L144), which points to bae9268, but I don't think that last commit nor the associated issues #8845 added this behaviour but only corrected a regression, i.e. the behaviour was there before.

I still think that strict mode should be the default with a bit of documentation on how to enable a more lax mode (probably in a similar way to how I changed the parsing to strict for me as a stop-gap thegcat/oskiosk@3ee5ba3), and the upcoming rails 5 would be a good opportunity to do that.

(and thanks to anyone who had the patience to read this until the end :-) )

**Comment by thegcat** [comment]
This still holds true on 4.2.3, and will probably for the whole life of 4.2, as this would be a breaking change and shouldn't be changed before 5.0.

**Comment by dijonkitchen** [comment]
Rails 5+ is out. Still relevant?

**Comment by thegcat** [comment]
This is still relevant, the stock Rails 5 ParamsParser will still happily accept non-standard json.

**Comment by PragTob** [comment]
:wave:

I know Rails has a lot going on and I deeply appreciate all the hard work! :green_heart: 

Just sayin, this also hit/hits us. With a1ced8b52ce60d0634e65aa36cb89f015f9f543d the shown work around also doesn't work anymore (although I'm sure there's another, but I won't tackle that during our Rails 5 migration :) ). Would be great if that behaviour could change, maybe Rails 6 will be the darling to do it? :)

**Comment by rafaelfranca** [comment]
I think at this point it is too hard to change this behavior without breaking a lot of applications. It is not something we can deprecate easily because it depends on the user input. You can still use the "work around" now, just that it is not a work around anymore, it has a public API.

```ruby
original_parsers = ActionDispatch::Request.parameter_parsers
ActionDispatch::Request.parameter_parsers = original_parsers.merge(Mime[:json].symbol => THE_PROC_YOU_WANT)
```

I guess it is safe to say we will never change this default behavior.
