### ISSUE TITLE
Assets compilation is taking much more time since the migration to Rails 4.2

### ISSUE THREAD

**Issue by zedtux** [rails/rails#18703]
After having migrated from Rails 4.1.9 to Rails 4.2.0, my test suite is failing with a timeout exception.

I'm using Capybara with Poltergeist and all my scenario are executed as Javascript (`default_driver` is poltergeist).

I don't know why it is taking much more time but increasing the Poltergeist timeout (as described in the issue teampoltergeist/poltergeist#571) "fixed" the issue and now my tests are passing again.

Can you please give me some directions or options I could play with in order to reduce/revert the amount of time needed to compile the assets pipeline ?

**Comment by rafaelfranca** [comment]
Can you please provide a sample application that reproduces the error?

**Comment by zedtux** [comment]
Unfortunately the project where I have the issue is not open source.

I have a Rails application I can try to upgrade and see if it reproduces the issue but it's not sure, I'll let you know.

**Comment by noinkling** [comment]
Did you try clearing out your `tmp` folder? Not sure if this is related or not, but I was having an issue with assets taking forever to load after upgrading, clearing out that folder fixed it.

**Comment by zedtux** [comment]
Thank you @noinkling for your comment. I've tried but it's not working :(

**Comment by zedtux** [comment]
I have maybe another hint for this issue...

Just to let you know, I'm using Docker on OS X (so with boot2docker).
Also I'm testing a lot of Javascript using the Poltergeist driver with Capybara.

I have generated the assets using the `rake assets:precompile` command (with and without `RAILS_ENV=test`) and set explicitly in my `config/environments/test.rb` file `config.assets.compile = false`.

While cucumber started and is waiting, I did a `top` command within the boot2docker image.
What I can see is that PhantomJS is the most CPU consuming process...

So it's like if PhantomJS is not aware of my precompiled assets and is generating them.

**Comment by sorentwo** [comment]
You may want to investigate if your app or Poltergeist is using `ThreadSafe::Cache`. This is a common solution for asset compilation errors in a multi-process/multi-threaded environment (Konacha, Capybara). Within one of my apps I specifically enable it for thread safe testing within `test.rb`:

```ruby
  if ENV['THREAD_SAFE_ASSETS']
    config.assets.configure do |env|
      env.cache = ThreadSafe::Cache.new
    end
  end
```
With that cache configured Rails won't use anything cached in `tmp` and you'll experience the repeated long compile times.

**Comment by zedtux** [comment]
Thank you @sorentwo. I didn't knew about `ThreadSafe::Cache` so it's not used in my application and Poltergeist seems not to use is.

**Comment by zedtux** [comment]
@sorentwo you gave me a good hint. I didn't knew that the assets were generated in the `tmp/cache/` folder.

Using the `watch` command, after having completely emptied the `tmp/cache/` folder shows me that the assets are well generated but it's taking a really long time !
I have started my test suite at 11:53 and the latest created file in the path `tmp/cache/assets/test/sprockets` has been created at 12:07.
Cucumber is running and executing scenarios during this time and when I look to screenshots of failing scenarios I can see the right color and so on but the font is missing and I see only squares instead of the text.

OK so then I've re-executed my test suite, thinking that then it should be faster as everything is already generated thanks to the previous execution, but it takes the same amount of time but no file changed in the `tmp/cache/assets/test/sprockets` path (The update time of the folder remains 12:07).

I guess Rails is checking for updates ?

**Comment by zedtux** [comment]
Ha ... I was wrong, the second time the test suite is executed the assets files are updated (not the folder content).

**Comment by zedtux** [comment]
Using the command `rake assets:precompile RAILS_ENV=test` creates all the assets really quickly and when I execute my test suite no one of the assets files are updated but it takes the same amount of time than without the `rake assets:precompile RAILS_ENV=test` ...

I'm a bit lost for now...

**Comment by zedtux** [comment]
I have tried to create a new Rails 4.2 application and copy my `app/` and `lib/` folders and imported files like `database.yml` and `routes/rb`.

I still have the same issue.

Now I'm trying to figure out how to force my application to not refresh the assets pipeline when running tests (I prefer to run the `rake assets:precompile RAILS_ENV=test` when something changed than waiting this long time each tome I'm running a single test).

**Comment by paulociecomp** [comment]
@zedtux, you can try capybara-webkit. it provide a better performance than poltergeist with rails 4.2

**Comment by sorentwo** [comment]
@paulociecomp: That may be true, but this is related to the asset cache being blown during testing. No matter what test runner your are using recompiling assets every time is going to slow you down.

**Comment by zedtux** [comment]
@paulociecomp thank you for your help but changing the JS driver between Rails version is not an option (we're already missing time on the implementation ... like always :wink:).

**Comment by zedtux** [comment]
I tried the same out of Docker and it's much more faster (obviously) which then "hide" (in my opinion) the issue.
I don't understand then why before it was running in an acceptable manner and since I did the upgrade to Rails 4.2 it's no more the case.

I will try to revert to Rails 4.1 and see if it's about the Rails upgrade or another gem.

**Comment by zedtux** [comment]
I have installed Debian on my iMac and the performances are really better. Let's say this is due to the couple of FS layers on OS X ...

**Comment by yordis** [comment]
100% confirmed, using Docker containers the assets compiling make the container takes forever. 

I read somewhere (I forgot sorry) that could be the volumes problem, because the container could be changing the timestamp (or something) and Rails is detecting as a change.
