### ISSUE TITLE
Rails.cache.logger missing

### ISSUE THREAD

**Issue by aripollak** [rails/rails#18712]
Rails.cache.logger is not initialized to anything by default, but it used to be. It seems to have been removed in 7fcf8590e788cef8b64cc266f75931c418902ca9, but I can't tell if it was on purpose or not. Should it be added back?

**Comment by rafaelfranca** [comment]
It seem to be on purpose. If you need the logger just set it.

**Comment by aripollak** [comment]
It seems like `silence!` is unnecessary then, no?

**Comment by rafaelfranca** [comment]
Not if you set a log and want to disable the log in some places.

**Comment by aripollak** [comment]
But then you'd just use `mute`; `silence!` seems like it's permanent, just like setting `logger = nil`.

**Comment by rafaelfranca** [comment]
Yeah, true. But I'm not sure if it is worth to remove it. The implementation is very simple.
