### ISSUE TITLE
Improve escape_javascript documentation on HTML safeness

### ISSUE THREAD

**Issue by toncid** [rails/rails#18711]
Hello,

The fact that strings produced by `escape_javascript` (aka `j`) are not HTML safe, should be clearly documented: http://api.rubyonrails.org/classes/ActionView/Helpers/JavaScriptHelper.html#method-i-escape_javascript

It's counterintuitive to see HTML entities appear in JavaScript strings after escaping the string for JavaScript.

The same issue was reported multiple times (e.g. #5127, #8844).

Thoughts?

**Comment by rafaelfranca** [comment]
Actually the strings produced by `escape_javascript` are HTML safe, if the argument is HTML safe. I don't think this need to be documented. Any transformation function in a non-HTML safe string will always result in a non-HTML safe string.

Thank you for the report.
