### ISSUE TITLE
Default ActionMailer queue should be configurable

### ISSUE THREAD

**Issue by peteygao** [rails/rails#18724]
ActionMailer's `deliver_later` function enqueues the job under the queue `mailers` which is currently hardcoded:

https://github.com/rails/rails/blob/ced687fe710b2f3d6cf0d0e978bdb531357299e4/actionmailer/lib/action_mailer/delivery_job.rb#L7

It'd be nice to be able to configure the default mailer queue to one of the worker queues that are already running so we don't have to spin up an one-off worker to process an extra queue.

**Comment by rafaelfranca** [comment]
This is a dup of https://github.com/rails/rails/pull/18587.
