### ISSUE TITLE
ActiveRecord where and find do not treat sets as arrays

### ISSUE THREAD

**Issue by jkorz** [rails/rails#18723]
Since sets behave very similar to arrays, I expect that:

```ruby
Widget.find([1,2,3].to_set) 
Widget.where(:id => [1,2,3].to_set)
```

Would be functionally identical to:

```ruby
Widget.find([1,2,3])
Widget.where(:id => [1,2,3])
```

Instead, the set gets coerced into a string and it tries to find a record based on the string representation of the set instead of iterating over the elements.

> ActiveRecord::RecordNotFound: Couldn't find Widget with 'id'=#<Set:0x007fc81e1725a8>

I think I've tracked the issue with find to [this spot](https://github.com/rails/rails/blob/76d6d8828007083faa6ccca3ad0feb7ba126ef79/activerecord/lib/active_record/relation/finder_methods.rb#L426) where it checks the class of the first arg, but I've never made a rails pull request before so I'm kind of scared to do it myself.

If anyone who is familiar with the process of changing the rails codebase would be up for pairing with me on this I'd love to get my feet wet.

**Comment by jkorz** [comment]
```ruby
gem 'activerecord', '4.2.0'
require 'active_record'
require 'minitest/autorun'
require 'logger'

# Ensure backward compatibility with Minitest 4
Minitest::Test = MiniTest::Unit::TestCase unless defined?(Minitest::Test)

# This connection will do for database-independent bug reports.
ActiveRecord::Base.establish_connection(adapter: 'sqlite3', database: ':memory:')
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :posts, force: true do |t|
  end

end

class Post < ActiveRecord::Base
end

class BugTest < Minitest::Test
  def test_association_stuff
    post1 = Post.create!
    post2 = Post.create!

    id_arr = [1, 2]
    id_set = id_arr.to_set

    assert_equal Post.find(id_arr), Post.find(id_set)
    assert_equal Post.where(:id => id_arr), Post.where(:id => id_set)
  end
end
```

**Comment by sgrif** [comment]
If we were to make this change, it would set a precedent for treating any enumerable as an array, which is not something I would like to do. So I don't think this is a change we would like to make.
