### ISSUE TITLE
Validation not performed for nested associations

### ISSUE THREAD

**Issue by afn** [rails/rails#18735]
This fails in the current `4-2-stable` (174547f51df405138fb2d0c5e03490333ce37a2d):

```ruby
class List < ActiveRecord::Base
  has_many :items, inverse_of: :list
  validates :title, presence: true
end

class Item < ActiveRecord::Base
  belongs_to :list, inverse_of: :items
  accepts_nested_attributes_for :list
end

describe Item, type: :model do
  it 'validates presence of description' do
    expect {
      Item.create! list_attributes: { title: nil }
    }.to raise_error
  end
end
```

Passes in 83e9005bf09974c004ded137eac679399add7f0e.

**Comment by afn** [comment]
@sgrif It looks like this was broken in ef7d79a8613f5aa55a84cc6024703c966ee70881 :(

**Comment by sgrif** [comment]
Yay yet coverage. :(

**Comment by sgrif** [comment]
Test coverage*

**Comment by sgrif** [comment]
Backported in https://github.com/rails/rails/commit/d9715fcde450cebec3aeff74d4d39db5542d6625

**Comment by sgrif** [comment]
Thank you for the report.

**Comment by afn** [comment]
Thanks again for the quick turnaround! :+1:
