### ISSUE TITLE
Single and double quotes are mixed together in a single file.

### ISSUE THREAD

**Issue by GildedHonour** [rails/rails#18737]
I know using double or single quotes is totally depends on a developer, what they like more. However, even in the source code of Rails within the **same file** there's a mix of double and single quotes when there's no necessity to do so.  For example:

https://github.com/rails/rails/blob/master/actionpack/lib/action_controller/base.rb

``` 
require 'action_view'
require "action_controller/log_subscriber"
require "action_controller/metal/params_wrapper"

```
or https://github.com/rails/rails/blob/master/actionpack/lib/action_controller.rb And there're other examples as well.

Is wonder, how come? What's the **recommended** style of using single quotes versus double ones according to the developers and contributors of **Rails**?

**Comment by matthewd** [comment]
The recommended style is: it simply doesn't matter.

(Also, please direct questions to the rails-core mailing list; we reserve the issue tracker for issues.)
