### ISSUE TITLE
ActionController::Live should be on a per action basis

### ISSUE THREAD

**Issue by jcoyne** [rails/rails#18730]
Currently I'm doing something like this:

```
  alias_method :process_without_streaming, :process
  include ActionController::Live

  # turn off ActionController::Live for he show action
  def process(name)
    if name == 'show'
      process_without_streaming(name)
    else
      super
    end
  end
```

**Comment by matthewd** [comment]
@jcoyne how does AC::Live's presence manifest, if your action doesn't actually write to the stream (and thereby trigger the early header commit, etc)?

I don't doubt that it does.. just looking for a reminder / insight into which part you're needing to avoid.

**Comment by jcoyne** [comment]
@matthewd I was getting some Deadlock errors and I found this technique useful for debugging. I think the problem was just trying to write to the stream after it had been closed and probably only manifested itself in a test case.  I'm going to close this ticket, because I won't pursue it further.

**Comment by jcoyne** [comment]
I thought of a good reason for this, but its just a way to work around #18714.  I want a "head" request to show the Content-Length so a client can decide whether they want to proceed with the download.
