### ISSUE TITLE
:null => false constrains from migration don't get written into schema on oracle

### ISSUE THREAD

**Issue by suung** [rails/rails#18738]
I upgraded a project to rails 4.1.8 ruby 2.1.5 on oracle

If i run rake db:reset db:migrate

three things change in the schema.rb

* the new hash syntax is used
* all null constraints are removed
* (some?) foreign keys get foreign key constraints

particularly all affected columns are

* either having a default
and or
* are a boolean having a default
or
* are a created_at timestamp

I don't find anything in any changelog for that and i am a bit concerned moving along.

Thanks for clarification.

**Comment by suung** [comment]
now i found this reference https://forum.upcase.com/t/null-false-for-t-timestamps-changed-in-rails-4-x/3073

**Comment by rafaelfranca** [comment]
Had you reported to the oracle adapter?

**Comment by suung** [comment]
@rafaelfranca no i didn't. Is the adapter responsible for such decisions?
can you point me to the code that makes decisions like that in rails so i can investigate further?

my reasoning, why it could have happened like that, would have been this:

* forein keys dont get the null constraint anymore from 4.1.something, because they get a forein_key_constraint like in rails 4.2
* default values in oracle MIGHT (i have no idea) replace the need for null constraints
** in general this is insufficient right?
* active record removes null constraints from timestamps because it considers them maintained outside of database level (which would be correct in a way for me)

i think if someone helps me to find the code, that makes decisions like that, i will figure it out quite fast, but i have no experience with database adapters.

thanks

**Comment by senny** [comment]
Closing this in favor of https://github.com/rsim/oracle-enhanced/issues/543

@suung thank you for reporting.
