### ISSUE TITLE
AR: MySQL rollbacks to non-existent savepoints.

### ISSUE THREAD

**Issue by brewski** [rails/rails#18740]
MySQL will release all savepoints in a transaction when a deadlock is detected. In nested, non-joinable transactions in ActiveRecord, when a deadlock error is raised, it will attempt to rollback to savepoints that no longer exist.

I opened pull request #18728 before submitting this bug report. I'm not sure I did this in the right order (my apologies if not). The pull request includes a test case that triggers the behavior, but isn't passing the travis-ci tests. It passes in my Vagrant environment, so I'm not sure how to proceed.

**Comment by jeremy** [comment]
cc @arthurnn

**Comment by arthurnn** [comment]
@brewski as you already sent a PR , explaining the problem, that should be enough. We can discuss the issue in there.
thanks
