### ISSUE TITLE
ActiveJob should support passing of keyword arguments to perform method

### ISSUE THREAD

**Issue by threadhead** [rails/rails#18741]
Since Rails 5+ will required Ruby 2.2+, ActiveJob should support the passing of keyword arguments to the perform method.

```
class MyAwesomeJob < ActiveJob::Base
  def perform(ginger_ninjas: 1)
    attack!(ginger_ninjas)
  end
end

MyAwesomeJob.perform_later(ginger_ninjas: 5)
```

Currently (rails 4.2), you get a `ArgumentError: wrong number of arguments (1 for 0)` if you try to pass keyword arguments.

**Comment by sgrif** [comment]
This appears to be due to the hash getting converted to string keys during job serialization/deserialization, while keyword arguments only work with symbol keyed hashes.

**Comment by sgrif** [comment]
Backported in https://github.com/rails/rails/commit/31085a5cd47894b6fa397ca22fe8aa552d339ce8

**Comment by threadhead** [comment]
@sgrif Impressive. I was going to start hacking on it after I got back from lunch, but you beat me to it. Thank you.

**Comment by chrisnicola** [comment]
This is awesome. I was testing it out with Ruby 4.2.4 and noticed that if you mix keyword and regular arguments it doesn't work. For example:

```
perform(message, channel: '#default')
```

Won't work but

```
perform(message:, channel: '#default')
```

Does.

**Comment by liaogz82** [comment]
curious, can I use it for `perform_later`??
