### ISSUE TITLE
rails 4.2 server error in production

### ISSUE THREAD

**Issue by ajinkyashukla** [rails/rails#18768]
I get the following error when server is started using 'rails server -e=production' and request is made even if the secret_key_base is set. However everything works fine if 'SET RAILS_ENV=production'. As per the documentation secret_token is not required in rails 4.2.

Error:
DEPRECATION WARNING: You didn't set `secret_key_base`. Read the upgrade document
ation to learn more about this new config option. (called from require at bin/ra
ils:4)
!! Unexpected error while processing request: Missing `secret_token` and `secret
_key_base` for '=production' environment, set these values in `config/secrets.ym
l`

**Comment by lostpupil** [comment]
@ajinkyashukla So what did you do to solve your problem?
