### ISSUE TITLE
Intermittent error on postgresql_adapter.

### ISSUE THREAD

**Issue by rodrigopinto** [rails/rails#18780]
I've just updated my rails app to rails version 4.2.0, and when I execute my test suíte I get stopped by an intermittent error on postgresql_adapter. Does anyone else had this problem?

```
/Users/rodrigopinto/.rvm/gems/ruby-2.1.3@dashboard-lasa/gems/activerecord-4.2.0/lib/active_record/connection_adapters/postgresql_adapter.rb:592:in `async_exec': PG::ConnectionBad: connection is closed:               SELECT COUNT(*) (ActiveRecord::StatementInvalid)
              FROM pg_class c
              LEFT JOIN pg_namespace n ON n.oid = c.relnamespace
              WHERE c.relkind IN ('r','v','m') -- (r)elation/table, (v)iew, (m)aterialized view
              AND c.relname = 'schema_migrations'
              AND n.nspname = ANY (current_schemas(false))
```

**Comment by pixeltrix** [comment]
@rodrigopinto are you sharing the database connection when running JS Capybara tests?

**Comment by rodrigopinto** [comment]
@pixeltrix No. I not even have capybara on my suite. I paid attention and it always happen interleaved.

**Comment by pixeltrix** [comment]
@senny maybe this is something to do with the automatic test database schema updating? I seem to remember something causing connection problems related to FK support.

**Comment by senny** [comment]
I'm on vacation right now. I'll have a look when I get back next week. 

@rodrigopinto can you try to create a sample app to reproduce the error?

**Comment by paulociecomp** [comment]
hi @rodrigopinto. I tried to reproduce the issue with ruby 2.1.3, rails 4.2, rspec 3.1.7 and postgres 9.4.0.1. Its run fine. You have to provide additional information to help reproduce the bug.

**Comment by rodrigopinto** [comment]
@senny @paulociecomp I'll try to reproduce it here and send feedback.

**Comment by rodrigopinto** [comment]
@senny @paulociecomp @pixeltrix Sorry for the inconvenience. 

I've debugged, and the problem was a configuration missing on my  `config/environments/test.rb`. 

I was using `ActiveRecord::Migration.maintain_test_schema!` on rails_spec.rb, but `config.active_record.maintain_test_schema = false` was missing on `config/environments/test.rb`.

Thanks for the support.

**Comment by justinschier** [comment]
My god. @rodrigopinto that worked!

**Comment by rodrigopinto** [comment]
@justinschier :+1:

**Comment by justinschier** [comment]
One more thing that maybe would help others in addition to the `maintain_test_schema` setting above. I've also had an issue where the actual schema can get out of sync with my schema.rb.

This always seems to fix everything:

```
RAILS_ENV=test rake db:drop db:create db:test:prepare db:migrate
```
