### ISSUE TITLE
alias_attribute cannot be put between/before attribute_method_xxxx (ActiveModel 4.2.0 & 4.0.0)

### ISSUE THREAD

**Issue by ypxing** [rails/rails#18807]
alias_attribute cannot be between/before attribute_method_xxx since method alias_attribute depends on the "final" attribute_method_matchers.

The document should at least mention this if we don't want to support putting alias_attribute between attribute_method_xxx.

Below is the example code and exception in 'rails c'.

tmp/a.rb
class A
  include ActiveModel::AttributeMethods

  attribute_method_prefix 'clear_'
  alias_attribute :nickname, :name

  attribute_method_suffix '_clear'
  define_attribute_methods :name

  private
  def clear_attribute(attr_name)
    puts "in clear_#{attr_name}"
  end

  def attribute_clear(attr_name)
    puts "in #{attr_name}_clear"
  end
end

A.new.clear_name
A.new.clear_nickname
A.new.nickname_clear

=========================================
irb(main):001:0> load 'tmp/a.rb'
in clear_name
in clear_name
NoMethodError: undefined method `nickname_clear' for #<A:0xbb0c0c90>
        from .rbenv/versions/2.1.4/lib/ruby/gems/2.1.0/gems/activemodel-4.0.0/lib/active_model/attribute_methods.rb:436:in `method_missing'
        from tmp/a.rb:22:in `<top (required)>'

**Comment by sgrif** [comment]
4.0 is no longer supported.

**Comment by ypxing** [comment]
@sgrif  can you reopen this issue since it's NOT just for 4.0.0 (I just verified this issue with 4.0.0 the first place)? 4.2.0 (if it's still supported) also has this issue.

**Comment by pinglamb** [comment]
A more readable example code:

```RUBY
class A
  include ActiveModel::AttributeMethods

  attribute_method_prefix 'clear_'
  alias_attribute :nickname, :name

  attribute_method_suffix '_clear'
  define_attribute_methods :name

  private

    def clear_attribute(attr_name)
      puts "in clear_#{attr_name}"
    end

    def attribute_clear(attr_name)
      puts "in #{attr_name}_clear"
    end
end

A.new.clear_name
A.new.clear_nickname
A.new.nickname_clear
```

**Comment by repinel** [comment]
Would it be reasonable to take aliases in consideration when defining `attribute_method_*`?

**Comment by rafaelfranca** [comment]
I think the way that it is working right now make sense and it should work that way.

It is a class level method so the method order make difference here. We can't know how to alias a method that don't exists before we called `alias_attribute`. The same would occur with the Ruby's `alias_method`.
