### ISSUE TITLE
perform_enqueued_jobs should take an only: argument as well

### ISSUE THREAD

**Issue by dhh** [rails/rails#18802]
It should be possible to only perform certain enqueued jobs, just like it is possible to assert that only certain jobs have been enqueued with `assert_enqueued_jobs only:`.

**Comment by perceptec** [comment]
Do you have a particular use case in mind for this one?

I was looking into implementing it and see how `assert_enqueued_jobs` functions, but given that `perform_enqueued_jobs` is more of an apparatus used to quickly switch processing on and off in a testing context (essentially the engine at the core of the surrounding assertions), and jobs are cleared on each run, it seems like it would be better to simply define the desired test jobs in the block as-is.

I'd understand this better if it wasn't internally-focused, but I may be missing the point...

**Comment by dhh** [comment]
Use case: You have a method that generates a variety of jobs, but you're only interested in testing the effects on one kind. And the other jobs spawned may need elaborate mocks to prevent them from contacting real remote service.

**Comment by perceptec** [comment]
I think the block form poses a problem, in the current scheme. We can't really introspect that, right?

I was going to roughly mirror `assert_enqueued_jobs`, but if I'm reading it correctly, `only` isn't actually preventing jobs from being queued--instead we queue all the things and then basically misreport the size by filtering the list. (Someone please correct me if I'm wrong.)

Maybe that only adds a little overhead, but the `perform_enqueued_jobs` equivalent would entail running all the jobs, and similarly manipulating the `performed_jobs` result (which wouldn't solve the problem outlined above).

Hmm...

**Comment by dhh** [comment]
I think you’d just enqueue all the jobs, then you’d filter the list of enqueued jobs and run the ones that match. Seems pretty similar to me?

**Comment by liseki** [comment]
@perceptec You'll have to look at the ```TestAdapter``` and perhaps pass a hash to ```perform_enqueued_jobs```.

**Comment by perceptec** [comment]
Still looking into this, but the sticking point was how to preserve the block syntax while filtering the jobs, because the test helper's `perform_enqueued_jobs` doesn't actually perform anything--instead it toggles the test adapter's `perform_enqueued_jobs` switch and yields to the block, which means the jobs passed in the block are executed immediately when they call `perform_later`.

Does that make sense? In other words, I need a hook in there somewhere to counteract the "immediately."

`only` would give me the job type, but not the argument passed to `perform_later`.

**Comment by liseki** [comment]
The jobs passed in the block are not executed immediately, they are passed on to the ```TestAdapter``` which is where you should do sorting based on class.
