### ISSUE TITLE
belongs_to with touch: true and record_timestamps = false

### ISSUE THREAD

**Issue by glampr** [rails/rails#18811]
When ```ActiveRecord::Base.record_timestamps = false``` and a record from a ```belongs_to``` association with ```touch: true``` is updated then the parent's ```updated_at``` column is automagically set to the current time.

https://gist.github.com/glampr/a43c0b90cf9649788e17#file-belongs_to_with_touch-rb

**Comment by arthurnn** [comment]
the problem here is that `touch` method (https://github.com/rails/rails/tree/master/activerecord/lib/active_record/persistence.rb#L463) does not respect `record_timestamps` flag. Not sure if thats intentional or a bug.
See that only the timestamp module uses the flag:
https://github.com/rails/rails/tree/master/activerecord/lib/active_record/timestamp.rb#L61

It most likely seems like a bug to me. 
@rafaelfranca @carlosantoniodasilva do you guys have more context around this?

**Comment by sgrif** [comment]
Seems like a bug to me, as well.

**Comment by carlosantoniodasilva** [comment]
The question might be: why setting up touch if you don't want the parent to
be updated?

On Wed, Feb 4, 2015 at 1:45 PM, Arthur Nogueira Neves <
notifications@github.com> wrote:

> the problem here is that touch method (
> https://github.com/rails/rails/tree/master/activerecord/lib/active_record/persistence.rb#L463)
> does not respect record_timestamps flag. Not sure if thats intentional or
> a bug.
> See that only the timestamp module uses the flag:
>
> https://github.com/rails/rails/tree/master/activerecord/lib/active_record/timestamp.rb#L61
>
> It most likely seems like a bug to me.
> @rafaelfranca <https://github.com/rafaelfranca> @carlosantoniodasilva
> <https://github.com/carlosantoniodasilva> do you guys have more context
> around this?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/rails/rails/issues/18811#issuecomment-72877805>.
>



-- 
At.
Carlos Antonio

**Comment by arthurnn** [comment]
@carlosantoniodasilva You might want to have the parent updated most of the times, but for that particular code path, you want to disable that. I think thats a reasonable use case.

**Comment by carlosantoniodasilva** [comment]
Well, then you might be looking for no_touching instead? Just trying to
understand the use case better.

On Wed, Feb 4, 2015 at 2:13 PM, Arthur Nogueira Neves <
notifications@github.com> wrote:

> @carlosantoniodasilva <https://github.com/carlosantoniodasilva> You might
> want to have the parent updated most of the times, but for that particular
> code path, you want to disable that. I think thats a reasonable use case.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/rails/rails/issues/18811#issuecomment-72883438>.
>



-- 
At.
Carlos Antonio

**Comment by sgrif** [comment]
I agree with that, but I'd expect no_touching and record_timestamps to be implemented in terms of each other, since one just seems to be the "permanent" form of the other. I think having them do different things is surprising behavior.

**Comment by carlosantoniodasilva** [comment]
Wondering: would we expect using no_touching not to record timestamps on
any model being saved? It seems they serve different purposes.

However I'd not be totally opposed to make record_timestamps also skip
touch, but that'd be a breaking change. Maybe we should review the entire
thing.

On Wed, Feb 4, 2015 at 2:17 PM, Sean Griffin <notifications@github.com>
wrote:

> I agree with that, but I'd expect no_touching and record_timestamps to be
> implemented in terms of each other, since one just seems to be the
> "permanent" form of the other. I think having them do different things is
> surprising behavior.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/rails/rails/issues/18811#issuecomment-72884185>.
>



-- 
At.
Carlos Antonio

**Comment by glampr** [comment]
The use case where I stumbled upon was globalize using the touch option when setting up the original <=> translation association, but when I run some data migrations I want the record_timestamps feature disabled. Hope it makes sense.

**Comment by sgrif** [comment]
`no_touching` is definitely the better option for that use case.

**Comment by glampr** [comment]
So data migrations would require both:

```ruby
ActiveRecord::Base.record_timestamps = false
ActiveRecord::Base.no_touching do
    ...
end
ActiveRecord::Base.record_timestamps = true
```
