### ISSUE TITLE
.html_safe is ambiguous and should be renamed

### ISSUE THREAD

**Issue by redbar0n** [rails/rails#18814]
`.html_safe` does not mean "please make this html safe", it's the opposite - it is you the programmer telling rails that "this string is html safe, promise!"

This can be confused by programmers, and hence be a potential security risk. A programmer should be able to read the name of a method and unambiguously be able to predict what it does, precisely.

I suggest renaming it to: `.prevent_html_escaping` to make it unambiguous, and to directly refer to what is actually being done (so that the programmer doesn't have to infer what "safe" means, precisely).

**Comment by redbar0n** [comment]
another name could be something like: `.render_html`

**Comment by seuros** [comment]
Thank you very much for the suggestion , the issue tracker is reserved for bugs only. 
Please use the rails core mailing list for suggestions and feature requests.

**Comment by redbar0n** [comment]
Ah, ok, thanks, I didn't know that. I now found the core list: http://groups.google.com/group/rubyonrails-core
