### ISSUE TITLE
Querying against a non-default primary key uses wrong value

### ISSUE THREAD

**Issue by x2764tech** [rails/rails#18813]
I have a gist: https://gist.github.com/x2764tech/4ff7c015cd5d7137c295

I have the follow models:

```
class Post < ActiveRecord::Base
  has_many :comments, primary_key: :system_id
end
 
class Comment < ActiveRecord::Base
  belongs_to :post, primary_key: :system_id
end
```
and the test
```
class BugTest < Minitest::Test
  def test_association_stuff
    post = Post.create! system_id: 23
    post.comments << Comment.create!
 
    assert Comment.exists?(post: post)
  end
end
```

The data is created successfully, but the query to check whether a post exists uses `Post.id` and not `Post.system_id`:

    SELECT  1 AS one FROM "comments" WHERE "comments"."post_id" = 1 LIMIT 1

The query should use the primary key specified in the relationship.

**Comment by x2764tech** [comment]
I don't know if it helps, but I noticed this in `4.1.6`, and replicated it in `4.1.9` and `4.2.0`, as well as the master branch

**Comment by sgrif** [comment]
This looks like the correct behavior. You are confusing the primary_key and foreign_key options.

**Comment by sgrif** [comment]
Never mind, I misread your issue.

**Comment by sgrif** [comment]
This is my daily reminder not to go through the issue tracker before I've had my coffee...

**Comment by x2764tech** [comment]
@sgrif In production code, it uses a named `foreign_key` as well, so I was pretty certain I had it right.

**Comment by sgrif** [comment]
Yes, you have it right. I was just reading it wrong. I'm drinking my coffee now, and then I'll fix it. :grin:

**Comment by sgrif** [comment]
This might not be something that can be backported to pre-5.0, since the fix on master depends a lot on the refactoring work I've been doing this year. I'll see what I can do to get it on 4.2 and 4.1 though

**Comment by x2764tech** [comment]
In case I hit this again:

The obvious work-around is to query the foreign-key column with the correct primary-key value instead of the object, e.g. in the example above 

`Comment.exists?(post_id: post.system_id)` 

returns the correct result.

**Comment by sgrif** [comment]
You can also just pass the ID without changing the column. Doing `Comment.exists?(post: post.system_id)` will work, as well. However, I got the backport working for 4.2 and 4.1, I'll link the commits here when I'm done.

**Comment by sgrif** [comment]
Backported for 4.1.10 in https://github.com/rails/rails/commit/b8ba202d5412cd311e40554903a5be0d7f369605

Backported for 4.2.1 in https://github.com/rails/rails/commit/e43d96c12a3de240d70ef730942cc1bc73238481

Thank you for the report.

**Comment by x2764tech** [comment]
@sgrif Thanks for the quick fix!

**Comment by sgrif** [comment]
Any time. It's my job. :)
