### ISSUE TITLE
Validates numericality and uniqueness throws exception for non-numeric value

### ISSUE THREAD

**Issue by F2Andy** [rails/rails#18819]
Say I have a model wit this validation:

class Post < ActiveRecord::Base
  validates :count, :presence => true, :numericality => true, :uniqueness => true
end

If I pass a value to count that is not numeric and then try to save the record, Rails will test for uniqueness by accessing the database, which will then object that it has been given the wrong type of data for an integer field, for example throwing up:

ActiveRecord::StatementInvalid: ActiveRecord::JDBCError: org.postgresql.util.PSQLException: ERROR: invalid input syntax for integer: "abc"

This worked properly (i.e., save failed gracefully, adding an appropriate error message to the record) in Rails 4.1.

This was tested on a new Rails 4.2 project (JRuby, PostgreSQL), with a single model set up like this:

rails g scaffold Post name:string comment:text count:integer

**Comment by prathamesh-sonpatki** [comment]
I tried to reproduce this with MRI but could not do it. Please check https://gist.github.com/prathamesh-sonpatki/f1e1b40534c9c6d3c52b. I guess problem might be AR-JDBC adapter.

**Comment by sgrif** [comment]
AR-JDBC does not support 4.2
