### ISSUE TITLE
Bug en el modelo

### ISSUE THREAD

**Issue by KAAF030191** [rails/rails#18823]
Existe un bug cuando el modelo termina con la palabra lista lo cual internamente RoR por algún motivo lo convierte en Listum y para las inserciones no hay problema... pero esto se va para las consultas cuando esta tabla se enlaza por un includes dentro de otra.

**Comment by rafaelfranca** [comment]
cc @spastorino @guilleiguaran

**Comment by guilleiguaran** [comment]
Something like this: 

"There is a bug when a model finish with the word `Lista` and internally for some reason Rails converts it to `Listum` and there aren't any troubles with insertions... but there are a problem with queries when this table is linked by an include inside of another"

**Comment by guilleiguaran** [comment]
@KAAF030191 can you paste here an example query to see what is the problem?

@KAAF030191 puedes pegar acá una consulta de ejemplo para ver cual es el problema?

**Comment by seuros** [comment]
Puedes por favor acer una aplicación ejemplo que reproduce el error?

**Comment by KAAF030191** [comment]
El error se produce en este caso.

TCurso.includes(:TUsuarioTCursoEvtMiLista).where('TCurso.estado=?', 'Publicado')

Lo comprobé luego de intentar todo pensando que el problema era de programación, sin embargo, finalmente cambié la llamada por 

TCurso.includes(:TUsuarioTCursoEvtMiL).where('TCurso.estado=?', 'Publicado')

haciendo lo cambios respectivos en cada parte para probar mi teoría... y pude ver que el error era cuando terminaba el nombre de modelo en Lista ya que en el mismo error de rails que me mostraba daba que no se tenía inicializado TCurso::TUsuarioTCursoEvtMiListum con lo que pude asumir que por algún motivo cambiaba mi definición de Lista al de Listum.

Bueno... ese sería el caso... Saludos.

**Comment by KAAF030191** [comment]
Cabe mencionar que en ninguna parte tenía definido algo como Listum... en incluso busqué esa cadena en todo el proyecto bajo un programa que busca texto en una carpeta completa... en este caso el proyecto... y lo único que encontraba era el Listum que me lanzaba en la excepción lo cual estaba en el log.

**Comment by robertomiranda** [comment]
@KAAF030191 deberias creo q tienes un error de typo

de tener algo como `TCurso.includes(:TUsuarioTCursoEvtMiLista).where('TCurso.estado=?', 'Publicado')` deberia ser `TCurso.includes(:t_usuario_t_curso_evt_mi_lista).where('TCurso.estado=?', 'Publicado')`

Te recomiendo que uses Ingles para los modelos, rails  convertir lo nombre de tus en plural para asociarlo a la base de datos. Además seria buena idea que  siguieras todas las convenciones de rails http://guides.rubyonrails.org/

**Comment by KAAF030191** [comment]
al contrario... yo creo que tú estás equivocado... ya que se debe incluir el modelo no el archivo así que se debe apuntar al nombre del modelo... el archivo tiene esa definición que tu pusiste pero el modelo como clase no... en tantos Framework que he usado... así es como funciona y Rails no es la excepción si tenemos el mapeador de datos, todo debe apuntar al nombre del modelo como clase y no al archivo. Y lo de la definición que dices en inglés no tiene  mayor importancia ya que en español no debe haber problemas siempre y cuando no se usen caracteres como la "ñ" o las "tildes", entre otros.

**Comment by jgonzalezd** [comment]
la gente que programa rails en espanol tiene un lugar especial en el infierno

**Comment by brayancastrop** [comment]
@KAAF030191 Te recomiendo que leas un poco la documentacion sobre las convenciones usadas http://guides.rubyonrails.org/active_record_basics.html#naming-conventions

Y t_usuario_t_curso_evt_mi_lista no se refiere al archivo, es la forma como rails hace referencia a la tabla

**Comment by KAAF030191** [comment]
Si realmente sabes desarrollar no importa si lo haces en español o en inglés.

**Comment by KAAF030191** [comment]
Ahí mismo lo dice... al parecer lo estás entendiendo mal @brayancastrop una cosa es la clase y otra la nomenclatura de la tabla... léelo bien y entiéndelo como debe ser que yo estoy siguiendo la convención tal cual es.

**Comment by rafaelfranca** [comment]
For what I could get this is the expected behavior of Rails. The plural of Lista is Listum because of our inflections. Rails use the table always in the plural. If you want to keep using Spanish in your models you have to correctly configure the inflections.

**Comment by KAAF030191** [comment]
@rafaelfranca gracias... es mucho más razonable esa respuesta... sin embargo ya lo corregí sólo cambiando el nombre del modelo.

**Comment by robertomiranda** [comment]
@rafaelfranca :+1:

**Comment by jgonzalezd** [comment]
@rafaelfranca da una opcion, pero atenta contra CoC y es una patada justo en las we** para los que le toque coger el proyecto despues.

**Comment by KAAF030191** [comment]
De acuerdo con @jgonzalezd no hay porque cambiar especificaciones del FW... y yo insiste que no tiene nada que ver programar en inglés o español... si se hace bien debe funcionar correctamente... sin embargo... una solución mejor para no chocar con las configuraciones de ruby fue cambiar el nombre del modelo y nada más.

**Comment by rafaelfranca** [comment]
@KAAF030191 :+1: with proper configuration you can keep using the name you want, I think the guys want to point that you would not need any of these configurations if you were using english, but of course, both ways are fine and this is a decision that only you can make.

**Comment by rafaelfranca** [comment]
Ah, just one think that I said incorrectly. Is not the plural of Lista that is Listum. Actually Listum is the singular and Lista is the plural by the Rails default inflection configuration.
