### ISSUE TITLE
ActiveJob not returning true job_id

### ISSUE THREAD

**Issue by xpepermint** [rails/rails#18821]
ActiveJob does not return provider's job_id but uuid instead.

I use `Que` which stores an incremental id for each job (as a numeric value) in database. When executing `MyJob.perform_later(MyRecord.first)` the returning `job_id` is not the one from the database but ActiveJob's unique value instead. The `job_id` should be the one from the database in this case.

Ref: https://github.com/chanks/que/issues/84

I mad a workaround for now: 
```ruby
# config/initializers/active_job_fix.rb
class ActiveJob::Base
  def enqueue(options={})
    self.scheduled_at = options[:wait].seconds.from_now.to_f if options[:wait]
    self.scheduled_at = options[:wait_until].to_f if options[:wait_until]
    self.queue_name   = self.class.queue_name_from_part(options[:queue]) if options[:queue]
    # hide this to set job_id before logger picks it (I would change ActiveJob::Logger before_enqueue to after_enqueue)
    # run_callbacks :enqueue do
      if self.scheduled_at
        j = self.class.queue_adapter.enqueue_at self, self.scheduled_at
      else
        j = self.class.queue_adapter.enqueue self
      end
      self.job_id = j.attrs["job_id"] || j.attrs["id"] # this should be set inside each adapter
    # end
    self
  end
end
```

**Comment by jvanbaarsen** [comment]
@xpepermint Can you provide a sample app containing this issue? That would really help :)

**Comment by piotrj** [comment]
I guess the question the question is whether job_id was supposed to be the identifier that the provider assigns. It rather looks that it was supposed to be ActiveJob's generated UID. Maybe we need another attribute like `provider_job_id`?

**Comment by rafaelfranca** [comment]
Yeah, it is supposed to be a unique identifier in the Active Job side, not something the adapter provide.

We maybe need another attribute, so feel free to implement it and send a PR or ask in the Rails Core mailing list if you are in doubt.

**Comment by jvanbaarsen** [comment]
@rafaelfranca Are you interested in a PR that implements an attribute called `provider_job_id` or something like that? If so I would like to try and tackle this one :)

**Comment by rafaelfranca** [comment]
@jvanbaarsen yes, it seems a good addition.

**Comment by jvanbaarsen** [comment]
@rafaelfranca Ok :) I'll see what I can come up with. Who from the core team is most familiar with ActiveJob that I might ping for help?

**Comment by rafaelfranca** [comment]
You can ping @cristianbica and @seuros

**Comment by seuros** [comment]
@jvanbaarsen I'm willing to help.

**Comment by jvanbaarsen** [comment]
@seuros Im looking into this, and this is what my assumptions are at the moment (I took que as an example)

1. When a Job is created the specific adapter is called (in this case `activejob/lib/active_job/queue_adapters/que_adapter.rb`)
2. The `JobWrapper.enque` is called, which directly sends the job to Que since JobWrapper inherents from `Que::Job`
3. My assumption would be that the enqueue method would return some form of internal ID used by Que. But this seems not to be the case. Instead I get the following data back:      
```
#<ActiveJob::QueueAdapters::QueAdapter::JobWrapper:0xa0b3754 @attrs={:args=>    [{"job_class"=>"RescueJob", "job_id"=>"8b17a740-a1c1-4b6b-869c-1dac8f03f8ae", "queue_name"=
>"default", "arguments"=>[[{"_aj_globalid"=>"gid://aj/Person/404"}]]}]}>
```
4. So this leaves me to the conclusion that either the Que library does not return a Job ID or the ID gets somehow lost in space.

Sorry if my questions are stupid, but im fairly new to the rails core codebase. Where do you suggest to search further? Or am I looking in the totally wrong direction?

**Comment by seuros** [comment]
@jvanbaarsen I think we don't return the jid from any adapter for now. It not hard to implement, but do all supported adapter return a JID ?

**Comment by jvanbaarsen** [comment]
@seuros Im not sure, I believe at least Sidekiq does. I'll make a list of all the adapters that return a JID. If it turns out to be just Sidekiq this feature might not be that usefull after all. I'll get back to you on this!

**Comment by cristianbica** [comment]
Resque does also. Que/queue_classic/delayed_job should return ActiveRecord
instances

**Comment by cristianbica** [comment]
@jvanbaarsen the way I see this doable is having an attribute on the job `adapter_job_id` (or `provider_job_id`) and that attribute will be set by the adapter upon `enqueue`. Example:
```ruby
#this is the sidekiq adapter found at rails/activejob/lib/active_job/queue_adapters/sidekiq_adapter.rb
require 'sidekiq'

module ActiveJob
  module QueueAdapters
    # == Sidekiq adapter for Active Job
    #
    # Simple, efficient background processing for Ruby. Sidekiq uses threads to
    # handle many jobs at the same time in the same process. It does not
    # require Rails but will integrate tightly with it to make background
    # processing dead simple.
    #
    # Read more about Sidekiq {here}[http://sidekiq.org].
    #
    # To use Sidekiq set the queue_adapter config to +:sidekiq+.
    #
    #   Rails.application.config.active_job.queue_adapter = :sidekiq
    class SidekiqAdapter
      class << self
        def enqueue(job) #:nodoc:
          #Sidekiq::Client does not support symbols as keys
          job.provider_job_id = Sidekiq::Client.push \
            'class' => JobWrapper,
            'queue' => job.queue_name,
            'args'  => [ job.serialize ]
        end

        def enqueue_at(job, timestamp) #:nodoc:
          job.provider_job_id = Sidekiq::Client.push \
            'class' => JobWrapper,
            'queue' => job.queue_name,
            'args'  => [ job.serialize ],
            'at'    => timestamp
        end
      end

      class JobWrapper #:nodoc:
        include Sidekiq::Worker

        def perform(job_data)
          Base.execute job_data
        end
      end
    end
  end
end
```

The downside of all this is that you have access to the provider_job_id only at enqueue time. When your job is executed you cannot get from AJ. But I don't think is needed nor the purpose of this talk

**Comment by jvanbaarsen** [comment]
@cristianbica Thanks for the reply, for sidekiq this would be a great option. But for the others that should return a active record object, somehow they don't (I'm probably looking in the totally wrong place). Some examples of return data:

**DelayedJob**:
```
#<Delayed::Backend::Test::Job:0x99500ac @attempts=0, @priority=0, @queue="default", @payload_object=#<ActiveJob::QueueAdapters::DelayedJobAdapter::JobWrapper:0x99500fc @job_data={"job_class"=>"RescueJob", "job_id"=>"ea275914-016b-414e-8615-b46e6c3d099d", "qu
eue_name"=>"default", "arguments"=>["DIFFERENT!"]}>, @handler="--- !ruby/object:ActiveJob::QueueAdapters::DelayedJobAdapter::JobWrapper\njob_data:\n  job_class: RescueJob\n  job_id: ea275914-016b-414e-8615-b46e6c3d099d\n  queue_name: default\n  arguments:\n  - DIFFERENT!\
n">
```

**Rescue** (This one only returns if the job is properly queue'ed or not)
```
true
```

**Que**
```
#<ActiveJob::QueueAdapters::QueAdapter::JobWrapper:0xa0b3754 @attrs={:args=>    [{"job_class"=>"RescueJob", "job_id"=>"8b17a740-a1c1-4b6b-869c-1dac8f03f8ae", "queue_name"=
>"default", "arguments"=>[[{"_aj_globalid"=>"gid://aj/Person/404"}]]}]}>
```

**Comment by cristianbica** [comment]
In test mode usually the adapters don't hit the backend (Redis, ActiveRecord, etc). So you'll need to check for each adapter what do they return when enqueueing a job.

**Comment by jvanbaarsen** [comment]
@cristianbica Ok! Thanks for the tip! I'll setup a test app for this :)

**Comment by jvanbaarsen** [comment]
@cristianbica I did some more investigating and created on PR to fix an minor issue in the Delayed Job adapter. But I run into the following problems:

* Que seems to return a job_id, which AJ overrides with its own ID. I'm not really sure where that is happening. Also I'm not sure if the testing adapter for Que is adequate. We might need to change that to reflect the reality a bit better.
* Resque only returns `true` or `false` So perhaps we can pass in the AJ job_id in cases such as this?

**Comment by cristianbica** [comment]
Yep it will be a bit hard to test this as for testing most of the adapters run kind of `:inline` behaviour.
Resque in non-test I think it returns the job_id as a string while in testing it returns true/false because it's run with `Resque.inline = true`. I think that, for the adapters that provides a JobID, we can test that the `ActiveJob::Base` subclass instance returned has a non-nil value set for `provider_job_id`

**Comment by uberllama** [comment]
Just ran into this, needing the DelayedJob record/id back from `perform_later` so I can cancel it later if needed. So consider this a :+1: and a thank you for your efforts.

**Comment by kddeisz** [comment]
I realize this is closed, but is anyone working on it? Just ran into this myself. Also, does it need to be implemented wholesale? I could take a crack at implementing it for DelayedJob (this is where I'm running into needing the ID).

**Comment by jvanbaarsen** [comment]
@kddeisz I was working on it, but I won't have time to work on it in the next 2 weeks. So feel free to create a fix for DelayedJob!

**Comment by rebyn** [comment]
If tomorrow allows, I think I'll take a stab at this as well :-).

**Comment by kddeisz** [comment]
Just put in a PR for DelayedJob https://github.com/rails/rails/pull/19910
