### ISSUE TITLE
Select insert blank option with required: true

### ISSUE THREAD

**Issue by Sega100500** [rails/rails#18827]
select(:related_data, :person_type_id, options_for_select(types_list, @related_data.person_type_id))
- all fine

select(:related_data, :person_type_id, options_for_select(types_list, @related_data.person_type_id), include_blank: true)
- all fine - with needle blank

select(:related_data, :person_type_id, options_for_select(types_list, @related_data.person_type_id), {}, { required: true })
- WRONG - insert blank option

select(:related_data, :person_type_id, options_for_select(types_list, @related_data.person_type_id), { include_blank: false }, { required: true })
- WRONG - insert blank option

**Comment by rafaelfranca** [comment]
It is by design. If you set the required attribute in a select and it doesn't include the blank value option you get a HTML 5 validation error.

See #5908
