### ISSUE TITLE
Asset serving from Webrick causes mutex error

### ISSUE THREAD

**Issue by richardnuno** [rails/rails#18822]
We're seeing a issue related to asset serving with Webrick that is causing the server to lock up.
These errors were intermittent and hard to reproduce but this [test application](https://github.com/bonobos/asset_mutex_bug) tries to do that.

When refreshing the root page repeatedly the following error appears in the server log (you might have to hold refresh hotkeys for a few seconds):

```
ERROR Errno::ECONNRESET: Connection reset by peer @ io_fillbuf - fd:16
```

or

```
ERROR Errno::EPROTOTYPE: Protocol wrong type for socket
```

When shutting down the server the follow error is displayed:

```
Internal Server Error

Attempt to unlock a mutex which is not locked
```

Removing the requires from application.js seemed to make the Errno errors disappear.

**Comment by richardnuno** [comment]
Forgot to mention, ruby version is 2.2.0 and rails version is 4.2.0

**Comment by sivsushruth** [comment]
@richardnuno I tried to reproduce the bug with ruby 2.1.0 and rails 4.2.0 several times, but in vein.

**Comment by TiuTalk** [comment]
@richardnuno Can you please provide a sample application that reproduces the issue?

**Comment by kamui** [comment]
@TiuTalk The sample app is here: https://github.com/bonobos/asset_mutex_bug

I can reproduce the issue on my MacBook Pro running 10.10 with ruby 2.2.0.

**Comment by benjaminsigidi** [comment]
Having the same problem.

**Comment by danieldocki** [comment]
Same here
Ruby 2.1.2
Rails 4.0.12

```
11:28:10 web.1  | [2015-03-04 11:28:10] ERROR Errno::ECONNRESET: Connection reset by peer @ io_fillbuf - fd:16
11:28:10 web.1  | 	/Users/danieldocki/.rbenv/versions/2.1.2/lib/ruby/2.1.0/webrick/httpserver.rb:80:in `eof?'
11:28:10 web.1  | 	/Users/danieldocki/.rbenv/versions/2.1.2/lib/ruby/2.1.0/webrick/httpserver.rb:80:in `run'
11:28:10 web.1  | 	/Users/danieldocki/.rbenv/versions/2.1.2/lib/ruby/2.1.0/webrick/server.rb:295:in `block in start_thread'
```

**Comment by arthurnn** [comment]
This seems like to be a bug on Webrick and not on Rails TBH.

**Comment by ossrapaport** [comment]
It's a Webrick bug, switch to Thin and it goes away.

**Comment by arthurnn** [comment]
This belongs to Webrick as far as I can tell.

**Comment by TonyShuangYuan** [comment]
I also encounter this issue in Rails 4.2.6,  Some times chrome hold refresh hotkeys for several minutes .After i hit keys in rails console(my rails runs as develop mode) the console display :"ERROR Errno::ECONNRESET: An existing connection was forcibly closed by the remote host..."

**Comment by ioquatix** [comment]
The `EPROTOTYPE` issue is a bug with the macOS kernel. More details can be found here: https://bugs.ruby-lang.org/issues/14713
