### ISSUE TITLE
strong param that is not an array between two or more strong parameters that are an array 

### ISSUE THREAD

**Issue by ramigb** [rails/rails#18857]
This will **work** : 
params.require(:post).permit(**:title**, :categories_ids => [],  :worlds_ids => [])

This will throw a **"unexpected ',', expecting =>"** error: 
params.require(:post).permit(:categories_ids => [], **:title**,  :worlds_ids => [])

Any idea why?

**Comment by radar** [comment]
This is invalid Ruby syntax.

A correct version would be:

```ruby
params.require(:post).permit(:title, :categories_ids => [], :worlds_ids => [])
```

You should put all your "normal" keys first.

**Comment by kaspth** [comment]
@radar is correct.

The error is telling you Ruby is expecting title to be another hash key.

**Comment by CJBrew** [comment]
Thanks @radar and @kaspth. I was trying to understand this problem. Is it documented somewhere?

**Comment by kaspth** [comment]
@CJBrew the problem is a misunderstanding of Ruby's syntax. When you start a Hash you can't reference non-Hash keys.
