### ISSUE TITLE
Custom param routing behaviour seems not correct

### ISSUE THREAD

**Issue by jvanbaarsen** [rails/rails#18855]
WhenI was working on an app I noticed the `param` keyword for a route returns behaviour that I was not expecting.

Lets say I have the following route:
```ruby
resources :profiles, :param => :username do
  get :details, :on => :member
  resources :messages
end
```

And when I call the url: `get '/profiles/bob/messages/34'` I expect the username to be in the `params[:username]`. But instead it's in the `params[:profile_username]`. When I looked at the testcase the behaviour seems to be planned, since there was a testcase written for it :

```ruby
  def test_custom_param
    draw do
      resources :profiles, :param => :username do
        get :details, :on => :member
        resources :messages
      end
    end

    get '/profiles/bob'
    assert_equal 'profiles#show', @response.body
    assert_equal 'bob', @request.params[:username]

    get '/profiles/bob/details'
    assert_equal 'bob', @request.params[:username]

    get '/profiles/bob/messages/34'
    assert_equal 'bob', @request.params[:profile_username]
    assert_equal '34', @request.params[:id]
  end
```

I was wondering if this behaviour is correct, or that it would be more logical to in this case always have the `params[:username]` there instead of `profile_username`. Since that way it would be possible to guess the param name.

Looking forward hearing from what you think!

**Comment by sivsushruth** [comment]
I think the current implementation is more logical. Consider two resources "user" and "admin".
Each of them might have a username param. So it is cleaner to have user_username and admin_username as this provides us a way to demarcate between the two.

**Comment by jvanbaarsen** [comment]
@sivsushruth Well the problem with that is (in the above example) that you can't always fetch the profile username with `params[:username]`. So you must always write custom code when you;re deeper in the nested resource in since you have to change to `params[:profile_username]`.

**Comment by rewritten** [comment]
:+1: I was about to open an issue exactly for the same reason.

The critical path seems to pass through https://github.com/rails/rails/blob/4-2-stable/actionpack/lib/action_dispatch/routing/mapper.rb#L1684, where one could have this:
```ruby
def nested_options #:nodoc:
  # options = { :as => parent_resource.member_name }
  options = { :as => (parent_resource.member_name unless parent_resource.param) }
  options[:constraints] = {
    parent_resource.nested_param => param_constraint
  } if param_constraint?

  options
end
```
or another opt-in way
