### ISSUE TITLE
action_dispatch/routing/route_set.rb#user_relative_controller

### ISSUE THREAD

**Issue by jimmykarily** [rails/rails#18858]
We have the following bug in our application. 
The user is in a page served by a controller "dashboard/settings/something". In this page the user is logged in with devise. If the user logs out (in an other tab or simply by deleting cookies) and tryies to POST to an action in a controller under "dashboard" namespace, which needs authentication, the devise controller searched is:
"dashboard/auth/sessions" instead of "auth/sessions" which is set in config/routes. We have some more configuration for devise (overridden failure_app) but I tracked the problem down to this method in Rails:
https://github.com/rails/rails/blob/4-1-stable/actionpack/lib/action_dispatch/routing/route_set.rb#L587

The [commit](https://github.com/rails/rails/commit/9444ac9312470696b6a5d73cd0044329211ec4c6) that introduced this method is a refactor and is not supposed to introduce new logic. It does not provide any reasoning for this so I'm wondering where the problem lies, in this method, devise or our configuration. Does anybody know why this handling is needed in the Rails side?

**Comment by jvanbaarsen** [comment]
@jimmykarily Can you maybe provide a sample application that reproduces this error?

**Comment by jimmykarily** [comment]
Sure. There you go:
https://github.com/jimmykarily/sample_app_rails_issue_18858

(I didn't use devise to reproduce it since it is irrelevant with the bug.)

**Comment by jvanbaarsen** [comment]
@jimmykarily Ok, good to know that Devise is ruled out!
@zzak Can you add the label "With reproduction steps"?

**Comment by nishantmodak** [comment]
I think this is not a bug

Following should solve it for you

At [Line 7 of tests controller](https://github.com/jimmykarily/sample_app_rails_issue_18858/blob/master/app/controllers/dashboard/tests_controller.rb#L7) , if you write it as 

```redirect_to url_for(controller: '/target', action: 'index')```  - notice the prepended ```/``` - it works.

This is also [documented](https://github.com/rails/rails/blob/master/guides/source/routing.md#controller-namespaces-and-routing)  . Look at the TIP section which says

*If you need to use a different controller namespace inside a namespace block you can specify an absolute controller path, e.g: get '/foo' => '/foo#index'.*

**Comment by jimmykarily** [comment]
@nishantmodak you are right. I missed it in the docs. Closing this.
