### ISSUE TITLE
JavaScript asset not found if directory has extension (.js)

### ISSUE THREAD

**Issue by ledestin** [rails/rails#18859]
Tried installing uri.js with Bower, and /assets/uri.js is not found by Rails. On the other hand, /assets/uri works without a hitch.

**Comment by ledestin** [comment]
I.e. I copied uri.js to uri to try.

**Comment by rafaelfranca** [comment]
Can you please provide a sample application that reproduces the error?

**Comment by ledestin** [comment]
https://github.com/ledestin/rails-bug-18859

URL of interest is /assets/uri.js. It works if I add `uri` symlink to `uri.js`.

**Comment by ajgrover** [comment]
Just tried this with the sample app - both /assets/uri and /assets/uri.js seem to work for me.

**Comment by ledestin** [comment]
Maybe you're not using `bundle exec`? I can't think of another reason.

**Comment by rafaelfranca** [comment]
This seems to be a sprockets issue. Could you open an issue there. Thanks.
