### ISSUE TITLE
Rename transactional fixtures to something clearer and more descriptive

### ISSUE THREAD

**Issue by brandonweiss** [rails/rails#18864]
I think the name "transactional fixtures" is a little misleading and confusing, because (as far as I can tell) it doesn't really have anything to do with fixtures.

This is pretty embarrassing, but I've been using Rails almost since 1.0 and I had no idea that transactional fixtures were running on my tests. I don't use fixtures so I just erroneously assumed that feature didn't work for me. I've been using Database Cleaner unnecessarily for like the last four years. I know, it seems ridiculous, but I talked to a few other fairly savvy Rails users and they had no idea either. I'm beginning to think my misunderstanding is fairly common.

Is there any interest in renaming the feature to something clearer and more descriptive, like "transactional tests"? E.g. `use_transactional_tests`. If so, I'd be happy to do the work to deprecate the old name, add the new name, and rename/update everything where necessary.

**Comment by georgemillo** [comment]
+1

**Comment by senny** [comment]
@brandonweiss thank you for your thoughts. Would you mind posting this to the [rubyonrails-core](https://groups.google.com/forum/?fromgroups#!forum/rubyonrails-core) mailing list? We don't use the GitHub issue tracker for suggestions and feature requests. You can find more in our [contribution guidelines](https://github.com/rails/rails/blob/master/CONTRIBUTING.md). Thank you for your understanding.
