### ISSUE TITLE
AR: Model scope is changed by previous scopes

### ISSUE THREAD

**Issue by stiff** [rails/rails#18862]
Say we have a model like this:
```ruby
class Booking < ActiveRecord::Base
  scope :cancelled, -> { where(:status => :cancelled) }
  scope :by_new_client, -> { a = arel_table.alias; where(:start_time => Booking.select('min(bookings_2.start_time)').from(a).where(:client_id => a[:client_id])) }
end
```

The `by_new_client` scope looks artificial, weird, inefficient and probably wrong, because it's a stripped down version of actual much more complex query (but it's unimportant here), the critical part is that subquery calls `select` on the `Booking` class, not on the current relation.

Then if we want to get all cancelled bookings by new clients we write:
```ruby
Booking.cancelled.by_new_client.to_sql
```
```sql
SELECT bookings.* FROM bookings 
  WHERE 
         bookings.status = 'cancelled' AND 
         bookings.start_time IN 
               (SELECT min(bookings_2.start_time) FROM bookings bookings_2 
                    WHERE 
                        bookings.status = 'cancelled' AND   --- <- BUG!
                        bookings.client_id = bookings_2.client_id)
```

Here the `cancelled` scope is _somehow_ propagated into the subquery. If we swap scopes, then we get the correct sql (as it was in Rails 3):
```ruby
Booking.by_new_client.cancelled.to_sql
```
```sql
SELECT bookings.* FROM bookings 
  WHERE 
         bookings.status = 'cancelled' AND 
         bookings.start_time IN 
               (SELECT min(bookings_2.start_time) FROM bookings bookings_2 
                    WHERE 
                        bookings.client_id = bookings_2.client_id)
```

No `status = cancelled` stuff in subquery.

Adding `.unscoped` fixes the thing, but it will break the `defaul_scope` if it would be added at some point and looks like a bug to me that the static method on model is somehow mutated by the invocation chain.

Here's gist that verifies SQL produced with these particular scopes is the same no matter in what order they were called: https://gist.github.com/stiff/e967dc2bc7ab1eb21e04

**Comment by sgrif** [comment]
This is the expected behavior. Scopes are executed in the context of the "current_scope", which is in this case the relation that you called the next scope on. You should use `unscoped` for this case.

**Comment by stiff** [comment]
It is expected that static class methods called directly on the class behave differently? ok.

**Comment by rafaelfranca** [comment]
Yes, it is. It is the same as:

```ruby
Model.where(foo: 'bar').scoping {
  Model.where(bar: 'baz')
}
```

The current scope inside that block is the `where(foo: 'bar')`. Like @sgrif said you have to call `unscope` if you don't want to apply the `current_scope`

**Comment by stiff** [comment]
Thanks!
