### ISSUE TITLE
engines routes don't work in render_to_string 

### ISSUE THREAD

**Issue by vsorlov** [rails/rails#18869]
Hi, I have an engine in my app and I'm trying to `render_to_string` a template, that uses engine routes helper.
So I'm rendering with `ApplicationController.new.render_to_string...`
In the main app routes.rb I mounted the engine to `my_engine_name`, so in my template I use `my_engine_name.some_path`.

Main app routes works ok when rendering through `render_to_string`, because they are generated through ActionDispatch https://github.com/rails/rails/blob/3-2-stable/actionpack/lib/action_dispatch/routing/url_for.rb#L148

But `main_app.*` and `my_engine_name.*` get an error ``#<ActionView::Template::Error: undefined method `host' for nil:NilClass>`` because of they need a request https://github.com/rails/rails/blob/3-2-stable/actionpack/lib/action_controller/metal/url_for.rb#L29

I'm using Rails 3.2.18, but I see the problem is still present in Rails 4.2 code.

Thanks.

**Comment by lxsameer** [comment]
@vsorlov can you please create a failing example ?

**Comment by vsorlov** [comment]
@lxsameer yes, I'll try to do it

**Comment by vsorlov** [comment]
@lxsameer I've created failing example. I can try to fix the bug, but I think I need some suggestions

**Comment by vsorlov** [comment]
the problem is that `_routes_context` here https://github.com/rails/rails/blob/master/actionpack/lib/action_dispatch/routing/route_set.rb#L427
is `ApplicationController`

**Comment by vsorlov** [comment]
actually I found out, that main app routes are also not working
strange, I thought they were

**Comment by pixeltrix** [comment]
@vsorlov this sounds more like a support issue than a bug - are you sure you're using something in the correct way? For example the pattern `ApplicationController.new.render_to_string` is not one that you'd expect to see in a Rails application. If you could explain more about what you're trying to achieve then we can see whether it really is a bug or you're using something in a manner it wasn't designed for.

**Comment by vsorlov** [comment]
@pixeltrix we're rendering users notifications to string and push them to [Faye](http://faye.jcoglan.com/) with [PrivatePub](https://github.com/ryanb/private_pub). Faye loads these notifications through ajax to users browsers.
In these notifications we need to render route paths.

**Comment by pixeltrix** [comment]
@vsorlov thanks, that's a little clearer - the way you're trying to use `ApplicationController` isn't really designed for what you're trying to do because it expects a request. You need to setup a view context manually and you can either use Action View or alternatively a lighter weight template engine like Tilt, e.g:

``` erb
<%# foo.html.erb %>
<div class="navigation">
<%= link_to('Home', root_url) %>
<%= link_to('Home', blog.root_url) %>
</div>
```

``` ruby
# action_view.rb
require 'action_dispatch'
require 'action_view'
require 'rails/engine'

module Blog
  class Engine < ::Rails::Engine
    isolate_namespace Blog
  end
end

Blog::Engine.routes.draw do
  root to: 'blog#index'
end

# Typically would be Rails.application.routes
routes = ActionDispatch::Routing::RouteSet.new
routes.draw do
  root to: 'pages#index'
  mount Blog::Engine, at: 'blog'
end

# View class to render the template
context = Class.new(ActionView::Base) do
  include ActionView::RoutingUrlFor
  include routes.url_helpers
  include routes.mounted_helpers

  self.default_url_options[:host] = 'www.rubyonrails.org'
end

# View paths to search for template, e.g: #{Rails.root}/app/views
view_paths = [Dir.pwd]

# Instance variables in templates, e.g: <%= @foo.bar %>
assigns = {}

view = context.new(view_paths, assigns)
puts view.render(template: 'foo')
```

Running `ruby action_view.rb` gives the following output:

```
<div class="navigation">
<a href="http://www.rubyonrails.org/">Home</a>
<a href="http://www.rubyonrails.org/blog/">Home</a>
</div>
```

The Tilt alternative is slightly easier to setup:

``` ruby
# tilt.rb
require 'action_dispatch'
require 'action_view'
require 'rails/engine'
require 'tilt'

module Blog
  class Engine < ::Rails::Engine
    isolate_namespace Blog
  end
end

Blog::Engine.routes.draw do
  root to: 'blog#index'
end

# Typically would be Rails.application.routes
routes = ActionDispatch::Routing::RouteSet.new
routes.draw do
  root to: 'pages#index'
  mount Blog::Engine, at: 'blog'
end

# View class to render the template
context = Class.new do
  include ActionView::Helpers
  include ActionView::RoutingUrlFor
  include routes.url_helpers
  include routes.mounted_helpers

  self.default_url_options[:host] = 'www.rubyonrails.org'
end

template = Tilt.new("foo.html.erb")
puts template.render(context.new)
```

Which you need to use depends on whether the templates are in engines, what view helpers you are using, etc. but as you can see the engine routes work fine so this isn't a bug.

**Comment by pixeltrix** [comment]
FYI, in Rails 5 this will be easier since we've added [`ActionController::Renderer`][1] - this allows you to just do `FooController.render :index, locals: {}, assigns: {}`.

[1]: http://edgeapi.rubyonrails.org/classes/ActionController/Renderer.html

**Comment by vsorlov** [comment]
@pixeltrix thanks, I'll try it :)
