### ISSUE TITLE
weird variant template rendering

### ISSUE THREAD

**Issue by FeGs** [rails/rails#18879]
**To reproduce a bug**
Clone https://github.com/FeGs/rails-variant-bug, and type `rake`.

**Summary**

When accessing '/posts.html', application renders a template 'index.html+tablet.erb'. Is it correct behavior? (Rails 4.2.0)

```ruby
# routes
resources :posts, only: [:index]

# controller
class PostsController < ApplicationController
  def index
    request.variant = :tablet
    respond_to do |format|
      format.html do |html|
        html.phone
      end

      format.xml do |xml|
        xml.tablet
      end
    end
  end
end

# views: posts/index.html+phone.erb, posts/index.html+tablet.erb, ...
```

**Comment by kaspth** [comment]
It's not a bug. Rails has an implicit render call that will look for a template with action.format+variant.erb in its name.
You could just as well leave out the respond_to block here and Rails would still render the other templates if you set the right format and variant.
