### ISSUE TITLE
Error handling of to_many relation with accepts_nested_attributes_for indexes problem

### ISSUE THREAD

**Issue by knagode** [rails/rails#18870]
I have vehicle has many vehicle_services relation. I am trying to insert vehicle_services via accepts_nested_attributes_for method.

Vehicle.rb
```ruby
class Vehicle < ActiveRecord::Base
  has_many :vehicle_services
  accepts_nested_attributes_for :vehicle_services, :reject_if => lambda { |service| service[:service_on].blank? }
```

If I try to save vehicle with not valid vehicle_services params I do not get information about which child relation did cause error(s).

Method:
```ruby
vehicle_params = {"licence_plate"=>"PO-XYZ", 
                  "vehicle_services_attributes"=>
                       {"0"=>{"service_on"=>"2015-11-11"}, 
                        "1"=>{"service_on"=>"SHOULD_RAISE_ERROR-not-correct-date"} ...}
vehicle = Vehicle.create(vehicle_p)
puts vehicle.errors.to_json
```

Outputs:

```javascript
{"vehicle_services.service_on":["wrong date format"]}
```
In vehicle variable I didn't get any information about which vehicle_service is causing errors. Was it index 0 or 1? I would expect errors like:
```javascript
{"vehicle_services.1.service_on":["wrong date format"]}
```

**Comment by rafaelfranca** [comment]
This is a dup of #8638
