### ISSUE TITLE
rake restart

### ISSUE THREAD

**Issue by dhh** [rails/rails#18876]
Wrap up the pattern of `touch tmp/restart.txt` as a rake task, so others can depend on it, like `rake dev:cache`. Also allows us to document the feature.

**Comment by dhh** [comment]
This will now be `rails restart` following #18878 (but should still be implemented as a rake task, so other tasks can declare dependency on it).

**Comment by senny** [comment]
This should probably restart `spring` as well.

**Comment by dhh** [comment]
:+1:
