### ISSUE TITLE
rake dev:cache

### ISSUE THREAD

**Issue by dhh** [rails/rails#18875]
It's common to want to test the caching strategy of your app in development mode. A simple pattern to dealing with toggling that on/off is using a file like tmp/caching-dev as a trigger, and then have something like this in config/environments/development.rb:

```ruby
  if Rails.root.join('tmp/caching-dev').exist?
    config.action_controller.perform_caching = true
    config.static_cache_control = "public, max-age=172800"
    config.cache_store = :mem_cache_store
  else
    config.action_controller.perform_caching = false
    config.cache_store = :null_store
  end
```

Let's expose that pattern fully with a toggle through `rake dev:cache` which will turn caching on if it's off and vice versa. And then output status, like "Development mode is now being cached".

That command also needs to touch tmp/restart.txt (which I also want to wrap up as a command).

**Comment by vipulnsward** [comment]
Nice :+1: 
Would be pretty useful!

**Comment by dhh** [comment]
This will now be `rails dev:cache` following #18878 (but should still be implemented as a rake task, so other tasks can declare dependency on it).

**Comment by dhh** [comment]
This issue is open again, if someone wants to tackle it. openacademy didn't get to it.

**Comment by nhodges** [comment]
I'd like to take a look at this.

**Comment by dhh** [comment]
Excellent. Please do have a swing at it!
