### ISSUE TITLE
ActiveRecord 4.2: Defined ordering of Attributes Keys() on Model Instances

### ISSUE THREAD

**Issue by nartzmag** [rails/rails#18871]
It seems that the ordering of attribute keys is not always the same for instances of the same model - i.e.

Post.find(1).attributes.keys != Post.find(2).attributes.keys

This is confusing - i would expect keys to always be sent in the same order, i.e. the same order as Post.column_names. Especially since ruby has added ordered hashes (via insert ordering) - I would imagine this could be an assumption made about this data structure.

It seems this class may be the problem ActiveRecord::AttributeSet - when inspecting, it appears that the instance variable called '@delegate_hash' can have a different ordering of keys than the 'types' or the 'values' internal hashes (which seems to have the correct ordering, based on column_names).

Is this somehow a desired behavior? It seems confusing.

**Comment by rafaelfranca** [comment]
You should not expect hashes in Ruby to be ordered. There is no reason to us to order the hash and add performance penalty to everyone if the mostly part of people don't need it to be ordered

**Comment by nartzmag** [comment]
I think you should take a deeper look at this - because the underlying implementation has changed from 4.1.8 to 4.2, and I think it should be changed back, or at least documented properly as a large change.

This appears to be broken from 4.1.8 to 4.20 - 

4.1.8
`
def attributes
  attribute_names.each_with_object({}) { |name, attrs|
    attrs[name] = read_attribute(name)
  }
end
`
https://github.com/rails/rails/blob/1d6d72ac7be9512041bfd1dfb928f242ede5c061/activerecord/lib/active_record/attribute_methods.rb#L285

4.20

`
def attributes
  @attributes.to_hash
end
`
https://github.com/rails/rails/blob/08576b94ad4f19dfc368619d7751e211d23dcad8/activerecord/lib/active_record/attribute_methods.rb#L283

Hashes in ruby ARE ordered for a reason - so you can enumerate them in the same order the keys were added.

There is no performance penalty here. The internal hash **could** have the same ordering, but the ordering is broken by wrapping the 'attributes' by ActiveRecord::AttributeSet and adding them to the 'delegate_hash' not in the same order as originally added. It **appears** that activerecord tries to achieve this behavior,

**Comment by rafaelfranca** [comment]
I'd say that it was never documented to be ordered and like I said you should not expect it.

The documentation only said:

> Returns a hash of all the attributes with their names as keys and the values of the attributes as values.

Not a `hash with all the keys ordered in the insertion order.`

If you need them ordered just call `sort` in your application.

**Comment by nartzmag** [comment]
Fair enough. I still disagree, i think that it would be nicer to keep them in the same order as the column names. Calling 'sort' will not give me the original order of the column names, instead i would have to get this hash and enumerate through the column names looking them up in the attributes, which the original method achieved, but is now lost. Also, calling sort on each row of, say, a csv file with 50k rows isn't the nicest solution really.

**Comment by rafaelfranca** [comment]
I think it is possible, just not needed. Could you explain why you need it
in a specific order? That may help to make a decision if we change it to
return that order or not.

**Comment by nartzmag** [comment]
What i really want to know is simply how to get the values returned in the same way as the column names, for say, when i generate a CSV

**Comment by rafaelfranca** [comment]
And column names are ordered by name?

**Comment by nartzmag** [comment]
No - by the default ordering on the table itself - the same as what is returned by say Post.column_names

**Comment by rafaelfranca** [comment]
Worth to investigate to see if ordering attributes will give any performance penalty.

cc @sgrif

**Comment by sgrif** [comment]
Reading through now.

**Comment by sgrif** [comment]
I agree with Rafael that you should not rely on hashes being ordered. The fact that they are in MRI is an implementation detail not something to rely on as part of the language.

**Comment by sgrif** [comment]
Yes I can make them ordered. It'll cause a performance hit, but I'm not too worried about it as `attributes` is usually a debugging method not one used in production code.

**Comment by nartzmag** [comment]
Thats fine, I'm wondering if the Api itself plans on providing a method to
return values ordered by the default table ordering, or if that's left to
the user.

**Comment by sgrif** [comment]
Its not a major concern of mine personally, but I can definitely make `attributes` ordered and I'll glance through to see if there's any easy inconsistencies in the more performance critical code.

**Comment by nartzmag** [comment]
cool - thanks for taking a look - i'm curious though - 

`as attributes is usually a debugging method not one used in production code.`

Is there a better method for returning the values in production code that I should be using that can be called on a model instance?

**Comment by sgrif** [comment]
Not a hash of all of the values. Usually you'd just use your model directly if you need all of its attributes.

**Comment by nartzmag** [comment]
Sorry - i meant just an array of the database 'row' ?

**Comment by sgrif** [comment]
Not in the public API. Same answer as before

**Comment by nartzmag** [comment]
alright cool -thanks for your help!

**Comment by thedarkone** [comment]
I'm worried that - in the future - we might regret having a semi-implicit (it is not in the docs, but there is now a test asserting it) guarantee about the order of `.attributes`.

> What i really want to know is simply how to get the values returned in the same way as the column names, for say, when i generate a CSV - i.e. if the header was Post.column_names and the rows, instead of doing like Post.first.attributes.values_at(*column_names) or something ...

What's wrong with doing `Post.first.attributes.values_at(*column_names)`?

**Comment by nartzmag** [comment]
I think it makes sense to have, as part of the public api, a way to get the
actual database row - almost every driver exposes this basic functionality.
My own ( but possible biased?) opinion is that this is the minimum a model
should offer, simpler APIs to do straightforward things. I actually think
this could be a place to guarentee ordering.

**Comment by sgrif** [comment]
I would like to express that my fixing this does not make it part of the public API. I absolutely agree with @thedarkone's concerns. Please do not read too much into this fix. It was made because it was convenient, not because I'd like to maintain this behavior long term.

**Comment by acurley** [comment]
The documentation for the `as_json` method `ActiveModel::Serializers::JSON` (which ultimately relies upon the `attributes` method) clearly **implies** that the attributes will be returned in a hash ordered in such a way that `id` will be first.  Cf. [as_json method in Rails API docs](http://api.rubyonrails.org/classes/ActiveModel/Serializers/JSON.html#method-i-as_json).  

While clearly not being a promise in a technical sense, it is certainly misleading to those of us who used the `as_json` method assuming that the `id` attribute would be first.

**Comment by chancancode** [comment]
There is definitely no intention of making that promise as far as `as_json` goes. It doesn't make sense — JSON objects are *unordered* key-value pairs.

In fact, you shouldn't be calling `as_json` at all. It is a hook method intended to be consumed by the JSON encoders. (Just like how you can override `setup` and `teardown` in minitest, but you won't generally call them yourself.) The specifics of the return values for this hook (e.g. symbol keys vs string keys, whether relationships are "flattened" or not) is not guaranteed at all so long as it gives the expected result when passed through a JSON encoder.

In general, we over guarantee what we explicitly say in the documentations. You shouldn't be making other assumptions about any other implications.

(It's not that we loving breaking people's app and would flip these things in every point release: but we can't guarentee what we don't intend to guarentee - there are no tests for these things, we won't know if we "broke" it, and we don't want to overcommit in ways that might hinder future refactoring and optimization for no good reason.)

**Comment by chancancode** [comment]
(The `as_json` thing isn't very well documented though, and it's pretty ambiguous in the current docs. We should probably clearify it before Rails 5.)

**Comment by vceron** [comment]
I think I've the same issue as you @nartzmag ([Rorschart issue](https://github.com/viadeo/rorschart/issues/13)).
I'd like to know if you could solve it. If yes, may I know how ?
