### ISSUE TITLE
ActiveJob + Sidekiq: Add possibility to pass options to deliver / deliver_later

### ISSUE THREAD

**Issue by karlingen** [rails/rails#18899]
Would be nice if we could pass options to above methods so that gems such as Sidekiq would be able to use these options in different circumstances. 

For instance, before ActiveJob was implemented in Rails one could add `.delay(retry:false)` to any mailer class so that Sidekiq would stop retrying e-mail sending when delivery failed.

For now, has anyone found a workaround for this?

**Comment by rafaelfranca** [comment]
There is already a thread about it in the Rails Core mailing list. Also we don't take feature request on the issue tracker. We recommend you to try to implement the feature and send us a pull request or if you are in doubt if the feature will be accepts ask in Rails Core mailing list for feedback.

**Comment by karlingen** [comment]
@rafaelfranca sweet, didn't know that! 

For anyone that might come across this issue, check here: https://groups.google.com/forum/#!topic/rubyonrails-core/r_incU_gtcw
