### ISSUE TITLE
Activerecord::Associations has autoloads that are not eager loaded

### ISSUE THREAD

**Issue by tinco** [rails/rails#18898]
Hi,

I'm not sure why this hasn't been noticed by anyone else before, but `lib/active_record/associations.rb` has this comment:

```
   # These classes will be loaded when associations are created.
    # So there is no need to eager load them.
```

Which is not actually true, and we are running into LoadErrors in our production systems because these files are being loaded during requests. The solution would be to wrap these in eager_load blocks as well.

Same for `lib/active_record/associations/join_dependency.rb` which does not even extend ActiveSupport::Autoload.

This should be affecting anyone who runs Rails in multithreaded mode in Puma or Passenger Enterprise, I don't know why no one noticed before now as we can very reliably produce these errors.

The solution I think is just wrapping these autoloads in eager_load blocks. No reason not to err on the side of caution with these.

**Comment by sgrif** [comment]
Can you create a simple Rails app which demonstrates the issue?

**Comment by carsonreinke** [comment]
Ugh, I've been burned by this.  I am going to try and create something testable.

**Comment by tinco** [comment]
Thanks, my apologies that I didn't. It happened to us in a rather stressful situation and I just couldn't find the time to build something to prove that it happens. In my opinion just looking at the code should tell you that it is buggy.

**Comment by carsonreinke** [comment]
The problem I am having is that `ActiveRecord::Associations::HasOneAssociation` is only autoloaded after the association is used and not created.  Basically the environment is Resque forking and a thread is started, everything at the point is suppose to be eager loaded.  For some reason in some cases, I get a `NameError`.  It is proving hard to reproduce.

**Comment by carsonreinke** [comment]
@tinco What ruby and Rails version did you have this problem?

**Comment by tinco** [comment]
I did not use Rails, I got this behaviour using ActiveRecord from Grape. I used whatever release was latest stable on Feb 11, 2015.

**Comment by carsonreinke** [comment]
Probably MRI 2.1.5 or 2.2.0 then, thought this was from 2.3 beforehand.

I am seeing this same issue with another gem also, where a class is set to autoload, but am receiving `NameError`s randomly.  So, probably nothing to do with ActiveRecord/Rails.

Started a thread also to get a feeler if anyone else was having the issue (no luck so far): https://www.ruby-forum.com/topic/6877694#new
