### ISSUE TITLE
Unexpected behaviour for `none` scope

### ISSUE THREAD

**Issue by bendilley** [rails/rails#18897]
```ruby
where post_id: Post.none
```
creates a clause like
```sql
"post_id" IN (SELECT "posts"."id" FROM "posts")
```
which is exactly the same as you get with
```
where post_id: Post.all
```
This is contrary to what I think most would expect.

I'm not sure how this particular scenario should be addressed. One option might be to generate something like this instead:
```sql
"post_id" IN (SELECT "posts"."id" FROM "posts" WHERE 1 = 0)
```

**Comment by kaspth** [comment]
The `none` relation was meant to be used in queries like this.

Honestly I'm having trouble understanding what you're trying to fetch. Won't `where(post_id: nil)` work?

**Comment by senny** [comment]
Probably related to #15763

@kaspth the use case I can see is that you have a method which determines the subquery using a relation. That method could return `Post.none` in some cases and a different relation in others.

**Comment by kaspth** [comment]
@senny :+1: that would make sense.

**Comment by senny** [comment]
@bendilley what version of Rails are you using?

I remember working on that exact issue. See #15176 and https://github.com/rails/rails/commit/c2357eba4d63a3365601267a55f56853eabd8971

**Comment by bendilley** [comment]
@senny I'm using Rails 4.0.12

You're right - your commit does address this very problem. From which version of Rails is your fix applied?

**Comment by bendilley** [comment]
Oh I see - it's in 4.2.0. Thanks for your help @senny!

Closing as a dupe of #15176

**Comment by senny** [comment]
@bendilley I just checked and the patch is only applied on `4-2-stable` and `master`. I'll look into a possible backport to `4-1-stable`.

As far as I know the last bugfix release for `4.0.` is over so you'd have to upgrade.

**Comment by bendilley** [comment]
No worries, thanks @senny. I have a serviceable workaround for now - I just wanted to raise it coz it caught me out. Evidently I wasn't alone... I guess I didn't search existing issues thoroughly enough :sweat_smile:

**Comment by senny** [comment]
backported the patch to `4-1-stable`.

@bendilley thank you for reporting! :yellow_heart:
