### ISSUE TITLE
Rails bug? ActiveRecord invalid data...

### ISSUE THREAD

**Issue by fabioanselmo** [rails/rails#18893]
Rails ActiveRecord is not returning accurate data.

    2.1.3 :072 > ids = [290, 291]
     => [290, 291] 
    2.1.3 :073 > pp ShortLink.where(id: ids)
      ShortLink Load (0.6ms)  SELECT "short_links".* FROM "short_links" WHERE "short_links"."id" IN (290, 291)
    [#<ShortLink:0x007f9ab317b1f0
      id: 290,
      redirect_to: "http://aol.com",
      title: "AOL - News, Sports, Weather, Entertainment, Local & Lifestyle",
      short_link: "77",
      created_at: Wed, 11 Feb 2015 06:07:33 UTC +00:00,
      updated_at: Wed, 11 Feb 2015 06:07:34 UTC +00:00,
      owner_id: nil,
      screenshot: nil,
      click_counter: 0>,
     #<ShortLink:0x007f9ab317a688
      id: 291,
      redirect_to: "http://aol.com",
      title: "AOL - News, Sports, Weather, Entertainment, Local & Lifestyle",
      short_link: "szbc",
      created_at: Wed, 11 Feb 2015 06:07:34 UTC +00:00,
      updated_at: Wed, 11 Feb 2015 06:07:35 UTC +00:00,
      owner_id: nil,
      screenshot: nil,
      click_counter: 0>]

So now assume I want to return each record if the title OR screenshot property is NOT nil. I use the following code:

    ShortLink.where(id: ids).where.not('title = :nil OR screenshot = :nil', nil: nil)

I expect both records to be returned `ids = [290, 291]` but I get back an empty `ActiveRecord::Relation` as such: 

    ShortLink Load (0.9ms)  SELECT "short_links".* FROM "short_links" WHERE "short_links"."id" IN (290, 291) AND (NOT (title = NULL OR screenshot = NULL))
    #=> #<ActiveRecord::Relation []>

**Comment by yesmeck** [comment]
If you are looking for some column is NULL or NOT NULL, you should always use `ShortLink.where(id: ids).where('title IS NOT NULL OR screenshot IS NOT NULL')`, because in SQL, NULL is not equals anything, even NULL is not equals NULL.

**Comment by fabioanselmo** [comment]
@yesmeck You're suggestion worked for me. Thanks for the help!

**Comment by yesmeck** [comment]
@fabioanselmo :smile:

**Comment by sivsushruth** [comment]
Fabio,

not (A or B) is equal to (not A )and (not B.)
And, not(A and B) is equal to (not A) or (not B)
So your statement is actually -> where title and screenshot, both are not
nil
To quickly achieve what you want, convert the OR to AND.

Correct me if I am wrong.
ᐧ
