### ISSUE TITLE
Merge multi-fetch fragments into core

### ISSUE THREAD

**Issue by dhh** [rails/rails#18900]
Using multi_get is a major level-up for performance when iterating over multiple items. This gem makes that happen when rendering a collection: https://github.com/n8/multi_fetch_fragments.

The one improvement I'd like to see is that the partial being rendered should still be able to have it's own caching call that's used when the partial is referred to on it's own, but this call obviously needs to be disregarded when rendered as part of a multi_get.

**Comment by kaspth** [comment]
I know it's an MIT license, but are the people in charge of that gem onboard with this?

**Comment by rafaelfranca** [comment]
@kaspth yes. Just asked this in the Campfire Room

**Comment by kaspth** [comment]
Great :+1:

**Comment by dhh** [comment]
Yep! Spoke to @n8 about it this morning. He doesn’t have time to pursue it at the moment, but would love it in Rails.

**Comment by n8** [comment]
:+1:  from me. I don't have time to do it this very moment myself, so happy to see anyone else want to take it up.

**Comment by kaspth** [comment]
@n8 Great to hear we can sprinkle in a little of that leftover Hope and Change :smile:

**Comment by dhh** [comment]
I don’t think there’s actually any left, /play sadtrombone

**Comment by kaspth** [comment]
Ah well, let's just move Forward then!

**Comment by kaspth** [comment]
I'm going to take a look at this.

**Comment by dhh** [comment]
Excellent, @kaspth. This should be a big performance boost for Russian doll style apps.

One approach I'd think to consider is for this to become fully automatic, though. Treat the caching dependencies like template dependencies in a sense, so the following would Just Work:

```
# notifications/index.html.erb
<%= render @notifications %>
<%= render partial: 'notifications/notification', collection: @notifications, as: :notification %>

# notifications/_notification.html.erb
<% cache notification %>
  Something with <%= notification.name %>
<% end %>
```

So like with template dependencies, the both of the render calls in index are able to deduce that they depend on this specific notifications/_notification template. And if that template starts with a call to <% cache $nameMatchingEitherAsOptionOrInferredAs %>, then the whole thing will just work.

You could still consider to have the explicit cache call in the render collection, but it would only be for cases that do not fit this default path. And when an explicit cache call is provided in render collection, we'll just ignore any cache calls in the element partial through maybe something like suppress_caching or whatever.

**Comment by kaspth** [comment]
By "explicit cache call in the render collection" are you talking about passing `cache: true`?

You say "able to deduce they depend on", but what does it mean for a collection to depend on an elements template? That the cache digest of the collection includes that template rendered in the context of the element?

Otherwise, I'm :+1: for trying to make it happen.

**Comment by dhh** [comment]
I mean you shouldn't have to pass `cache: true` if we can deduce from the partials you're rendering through the collection that they already match what we expect.

So `render @notifications` will lookup whether `notifications/_notification` partial has a `cache` call at the top, and if so, it'll do a multi_get automatically.

**Comment by kaspth** [comment]
Right, I'll ping you back when I have some code.
