### ISSUE TITLE
`:time` option for `#touch`

### ISSUE THREAD

**Issue by jeremy** [rails/rails#18905]
`#touch` always uses the current time. If we want to touch with a different time, we have to do it ourselves. That makes it awkward to touch a record to match another record, to touch a record with current transaction time, to touch with an associated file's mtime, or to touch with a previous time reflecting an earlier occurrence.

We can take an optional `time:` argument that defaults to `current_time_from_proper_timezone` to make these cases possible.

**Comment by andyatkinson** [comment]
@jeremy Does #18824 fix the issue? If not, is this something I could look at? I see there is an openacademy tag and I don't know whether that means it has been claimed. I don't see a specific assignee. Thanks.

**Comment by kaspth** [comment]
@andyatkinson A number of our Core Team members and Committers are mentoring students for Facebook's Open Academy and giving them tasks to work. Your interest is appreciated, but we have reserved the rights for the students (even if anyone in particular hasn't been picked yet).

Also @jeremy's [comment here](https://github.com/rails/rails/pull/18824#issuecomment-73949736) explains the relationship between these two issues. I hope you won't be deterred :yellow_heart:

**Comment by andyatkinson** [comment]
@kaspth I'm an aspiring Rails contributor. If you see an issue that you think is not appropriate for the Open Academy group, please ping me about it, I'd like to take a look. Thanks!

**Comment by hjoo** [comment]
Hi, I'm working on this issue and am wondering if there's a clean way to have optional arguments in ruby?
