### ISSUE TITLE
rails routes -g pattern to search for specific routes

### ISSUE THREAD

**Issue by dhh** [rails/rails#18902]
This is a common pattern: `rake routes | grep pattern`. Let's bake it into the command once we have #18878 in place with `rails routes -g pattern`.

**Comment by chancancode** [comment]
We have some pretty nice fuzzy search thing for the routes error page :wink: do we need to match that experience?

**Comment by chancancode** [comment]
https://github.com/rails/rails/pull/14619

**Comment by dhh** [comment]
We should share the behavior between the two.

**Comment by georgebrock** [comment]
What's wrong with `rake routes | grep <pattern>`?

Learning this pattern teaches users how to filter the output of any command, but a flag for `rake routes` (or `rails routes`) only teaches users how to filter their Rails routes. Unix command line interfaces have always been designed to be single-purpose, composable tools.

**Comment by dhh** [comment]
George, because we can share behavior with the fuzzy matching we already have. And because it’ll work on all platforms.

**Comment by georgebrock** [comment]
@dhh Something that works on non-Unix platforms makes a lot of sense. Thanks for clarifying.

**Comment by chancancode** [comment]
Actually, the fuzzy matching was implemented in JavaScript :P But as long as we can confirm that's the experience we want, I'm sure an Open Academy student will be able to figure something out :wink:

Another advantage of an in-command search is that it could keep the headers and grouping (e.g. `Routes for Some::Engine:` intact) :smile:

**Comment by dhh** [comment]
:+1:

**Comment by repinel** [comment]
I could work on this once #18878 is done.

**Comment by dannysperry** [comment]
@dhh what would be the point of -g, is there another option we would send to rails routes? I find myself writing something like `rake routes pattern` on accident. and then deleting some rewrite. I'd love to see this be as simple as `rails routes pattern` and `rails routes`

**Comment by dhh** [comment]
Not using an option paints you into a corner where you can't do something
else in the future. I could well imagine that say -g searches a pattern but
-m does some kind of model look-up.

**Comment by Ch4s3** [comment]
`rails routes -g <pattern>` would be nice. What would be killer for me would be a -c option for finding routes for controllers and their actions. Something like `rails routes -c some_controller:some_action` or `rails routes -c some_controller`.

**Comment by kaspth** [comment]
@Ch4s3 take a look at the linked PR which does exactly that :grin:

(There's also a CONTROLLER env variable for this currently, but don't get too attached as I'd like to deprecate it :smile:)

**Comment by Ch4s3** [comment]
@kaspth oh awesome! Yeah, that env variable seems odd to me.
