### ISSUE TITLE
Broken Assets Pipeline Rails 4

### ISSUE THREAD

**Issue by sonali1908** [rails/rails#18913]
These tags:
`<%= stylesheet_link_tag    'application', media: 'all' %>
<%= javascript_include_tag 'application' %>`

are resulting in:

`<link rel="stylesheet" media="all" href="/stylesheets/application.css">
<script src="/javascripts/application.js">`

instead of the fingerprinted links. 

I am running my app on Ubuntu Ruby on Rails on 14.04 (Nginx + Unicorn) on digitalocean. I have done rake:assets:precompile. I have also added `require "sprockets/railtie"` in application.rb

**Comment by rafaelfranca** [comment]
Are you running in development or production environment?

Also which version are you using?

**Comment by sonali1908** [comment]
production. It is rails 4

**Comment by rafaelfranca** [comment]
4.0.x, 4.1.x or 4.2.x?

**Comment by rafaelfranca** [comment]
Also,  Can you please provide a sample application that reproduces the error?

**Comment by sonali1908** [comment]
It is rails 4.1.6

What should I share?

**Comment by rafaelfranca** [comment]
How to reproduce it. Because a new application doesn't reproduce this error. If you could build a new application and make it reproduce the error that would help.

**Comment by sonali1908** [comment]
My application was actually running fine until a few days back. So I believe something has broken down in settings. I am uncertain if a new application will produce the same error.

**Comment by rafaelfranca** [comment]
It would be hard to us fix or provide any help if we could not reproduce the problem or even know what is the state of the configuration/application.

**Comment by sonali1908** [comment]
Should i share the config folder?

**Comment by rafaelfranca** [comment]
You can paste the application.rb, assets.rb and production.rb here if you want.

**Comment by sonali1908** [comment]
Application.rb

require 'rails/all'
require 'sprockets/railtie'
Bundler.require(*Rails.groups)

module Ocean
  class Application < Rails::Application
    config.assets.precompile += %w(*.png *.jpg *.jpeg *.gif)
    config.action_mailer.default_url_options = { host: 'abc.com' }
    config.assets.paths << Rails.root.join("app", "assets", "fonts")
    Koala.config.api_version = 'v2.0'
  end
end

**Comment by sonali1908** [comment]
Assets.rb

Rails.application.config.assets.version = '1.0'

**Comment by sonali1908** [comment]
Production.rb 

config.cache_classes = true
config.eager_load = true
config.consider_all_requests_local       = false
config.action_controller.perform_caching = true
config.serve_static_assets = true
config.assets.js_compressor = :uglifier
config.assets.compile = false
config.assets.digest = true
config.log_level = :info
config.i18n.fallbacks = true
config.active_support.deprecation = :notify
config.log_formatter = ::Logger::Formatter.new
config.active_record.dump_schema_after_migration = false
config.action_mailer.delivery_method = :smtp
config.action_mailer.smtp_settings = {
    address:              'smtp.gmail.com',
    port:                 587,
    domain:               'abc.com',
    user_name:            'abc@abc.com',
    password:             '',
    authentication:       'plain',
    enable_starttls_auto: true  
  }
end

**Comment by rafaelfranca** [comment]
I could not see anything wrong in your configuration.

I don't see how I could help you more just with this information.

Let me know if you could track down the cause.
