### ISSUE TITLE
upload files

### ISSUE THREAD

**Issue by kiranterugu** [rails/rails#18927]
validates_attachment :resume,
    :presence => true,
    content_type: { content_type: "application/pdf",  } in this i trayed to give some other file validation but it show an error .error message is def new expected out of end

**Comment by arunagw** [comment]
Please ask technical questions at Stackoverflow or other forums.

This issues list is for Rails core bugs

**Comment by kiranterugu** [comment]
![screenshot from 2015-04-08 16 33 00](https://cloud.githubusercontent.com/assets/10413505/7044082/27a6a768-de0d-11e4-8db6-d54356ec618e.png)
in this image having Teaching and non-Teaching radio buttons.if select teaching it shows divisions.if i select non-teaching it shows category,But in edit time it shows non-teaching for divisions
