### ISSUE TITLE
Associated objects being touched on touch.

### ISSUE THREAD

**Issue by arenoir** [rails/rails#18929]
According to the [documentation](http://api.rubyonrails.org/classes/ActiveRecord/Associations/ClassMethods.html#method-i-belongs_to)

> **touch:** If true, the associated object will be touched when this record is either saved or destroyed

However I am experiencing this behavior on touch as well.

**Comment by carlosantoniodasilva** [comment]
The behavior is correct, but we might need an update in the documentation in this case, though.

**Comment by arenoir** [comment]
Yeah this isn't much of an issue, just something I ran into while optimizing my application.  I was using an after touch callback and not wanting it to trigger when a grand child changed.
