### ISSUE TITLE
Better access to request.variant

### ISSUE THREAD

**Issue by dhh** [rails/rails#18933]
Currently, `variant=` sets an ivar with an array of the options. So request.variant will return something like `[ :phone ]` if you set `request.variant = :phone`. That's cumbersome to deal with on query. You now have to do either `request.variant.first == :phone` or you have to do `request.variant == [ :phone ]`. It gets even worse if you set multiple variants, like `request.variant = [ :tablet, :phone ]`. Checking if either is in there is a hassle.

So, let's wrap that variant in a better access class, so the following api works:

```ruby
request.variant = :phone
request.variant.phone? # => true
request.variant.whatever? # => false

request.variant = [ :tablet, :phone ]
request.variant.tablet? # => true
request.variant.phone? # => true
request.variant.any?(:tablet, :phone) => true
request.variant.any?(:tablet, :desktop) => true
request.variant.any?(:watch, :desktop) => false
```

**Comment by georgeclaghorn** [comment]
I'll take this.

**Comment by sdhull** [comment]
Hah I was just about to submit a PR for something like this.
