### ISSUE TITLE
fresh_when and expires_in sends message body agains http specs

### ISSUE THREAD

**Issue by ekampp** [rails/rails#18941]
Hi everybody. 

I just realized that using `fresh_when` and `expires_in` still uses time and effort to compile views and render then to the browser, even though the [http specification for 304](http://www.w3.org/Protocols/rfc2616/rfc2616-sec10.html) specifically says that no message body should be send along with a 304 Not Modified status. 

Quote from the page: The 304 response MUST NOT contain a message-body, and thus is always terminated by the first empty line after the header fields

Is there something that I'm forgetting to flag to avoid this behaviour, or is this one of the places where Rails is breaking the specifications, and if so, is it an intentional or unintentional breach?

Any input appreciated. 

Thanks in advance, 

Emil

**Comment by TiuTalk** [comment]
@ekampp 

Could you please provide a snippet/gist of code to reproduce this issue? Maybe an unit test?

**Comment by ekampp** [comment]
I looked into the issue further and realized that it's because I have the caching in an after_action filter. My bad. Sorry for the incorrectly raised issue.

**Comment by kamui** [comment]
This is good to know. I'd been setting `fresh_when` in an `after_action` so I could set an Etag/Last-Modified and use action caching at the same time. I just tested it myself recently and saw that in an `after_action` hook, rails will still go through the process of rending the view, even though when passing a matching `If-None-Match` header, it'll return no content like it should. It's tricky to call `fresh_when` and still have it set the proper Etag/Last-Modified on a cache hit and miss.
