### ISSUE TITLE
ActiveRecord retrieves infinity dates from postgres as nil

### ISSUE THREAD

**Issue by odigity** [rails/rails#18957]
https://gist.github.com/odigity/561ec3dfd45108085a05

As you can see, I have no problem saving the value, but it comes back as nil.

Seems very similar to this issue: https://github.com/rails/rails/issues/544

(FYI-sevenseacat tried it on Ruby 2.2 with the same result)

**Comment by prathamesh-sonpatki** [comment]
Created a reproducible script using https://gist.github.com/prathamesh-sonpatki/668a93128bd460d2e165.

**Comment by mrnugget** [comment]
There is currently no support for Infinity as a date value in the PostgreSQL adapter. I have a proposed solution here https://github.com/rails/rails/pull/17365

**Comment by odigity** [comment]
You guys rock!

**Comment by sgrif** [comment]
Closing as a duplicate of https://github.com/rails/rails/pull/17365
