### ISSUE TITLE
Make template locals available as a hash to the template itself

### ISSUE THREAD

**Issue by dhh** [rails/rails#18962]
This is a common piece of code:

```
# Template 1
<%= render 'some/partial', magic: variable %>

# Template 2
<%= render 'some/partial' %>

# some/partial
<%= defined?(magic) ? magic : '' %>
```

That `defined?` check is pretty gross. I'd much rather be able to do:

```
# some/partial
<%= locals[:magic] %>
```

**Comment by dhh** [comment]
These fucking Rails people have thought of everything! `local_assigns` is exactly this and already available. TIL!

**Comment by cristianbica** [comment]
This is actually an kind of private API as it's a local_variables eval'ed [here](https://github.com/rails/rails/blob/master/actionview/lib/action_view/template.rb#L275). There's an isssue (#15700) to document it. Probably the naming `local_assigns` will remain

**Comment by ondrek** [comment]
:facepunch:
