### ISSUE TITLE
Make ActiveSupport depend on i18n >= 0.6.4, < 0.7.0 [3-2-stable]

### ISSUE THREAD

**Issue by joneslee85** [rails/rails#18967]
Because i18n 0.7.0 no longer support Ruby < 1.9.3. I think we should remove the pessimistic versioning (as of https://github.com/rails/rails/blob/3-2-stable/activesupport/activesupport.gemspec#L23). Thoughts?

**Comment by carlosantoniodasilva** [comment]
I18n 0.7 should work fine for Rails 3.2 for Ruby 1.9.3+ users, do you have any specific use case that might be causing problems?

**Comment by joneslee85** [comment]
@carlosantoniodasilva There are apps and gems that still run Ruby 1.8.7. For example: newrelic_rpm gem tests against Rails 3.2 and its Ruby 1.8.7 failed because of this.

**Comment by carlosantoniodasilva** [comment]
Hm I see.. Well, I think they should not be getting I18n 0.7 then, due to the ruby version check. I'm not sure it's Rails responsibility in this case.

**Comment by joneslee85** [comment]
Most of the cases i18n is not explicit dependency and version conflicts are likely caused by Rails. Workaround is to explicitly cap the version of i18n gem in those projects. It would be ideal to get Rails cap the upper version within 0.6.x series of i18n. I've prepared a PR https://github.com/rails/rails/pull/18969, love to get your feedback on that. TIA

**Comment by rafaelfranca** [comment]
0.7 works with Rails 3.2 if you are not using Ruby < 1.9.3, so we should not change the dependency in Rails side. Like @carlosantoniodasilva said the Ruby version check should be sufficient to tell users to explicitly set i18n version in your application.
