### ISSUE TITLE
ActionDispatch, UploadedFile is returning pdf files with content_type of "application/force-download"

### ISSUE THREAD

**Issue by imorcott** [rails/rails#18978]
ruby '2.1.5'
gem 'rails', '~> 4.2.0'

When I am uploading a file
view code:
<%= f.input :document, :as => :file %>
 and then check the temp file content type of a known good pdf file the content_type is "application/force-download".
Any clues as to the reason why the content type is  "application/force-download" and not "application/pdf"?

Thanks,
-Ian

**Comment by matthewd** [comment]
Please use the mailing list or StackOverflow for questions/help, where a wider community will be able to help you. We reserve the issues tracker for issues only.

**Comment by imorcott** [comment]
It seems to be an issue that has been discussed on StackOverflow without resolution.  
There are work-arounds: http://stackoverflow.com/questions/6912073/paperclip-validate-pdfs-with-content-type-application-octet-stream. And I have posted a work around on Paperclip's issues too: https://github.com/thoughtbot/paperclip/issues/1771

The issue is: Uploading known good pdf files has the content type changed to "application/force-download". This is inconsistent from any other type of file uploads in regards that the reported content type is as I expected them to be.


To test that this issue is not related to my use of Paperclip,  I have created a new project with a single model, view and controller 
I am using ruby '2.1.5'
The only gems are:
gem 'rails', '~> 4.2.0'
gem 'mysql2'

The layout has nothing in the <header> section. So there is no java script being injected from an external source.
The view is:
<%= form_for @document do |f| %>
    <%= f.file_field :document %>
    <div class="actions">
      <%= f.submit %>
    </div>
<% end %>

The controller is nothing other than default scaffolding and the issue is present prior to landing in the controller.

It is easy enough to see the content type. Put a break point at line 33 of :ruby-2.1.5/gems/actionpack-4.2.0/lib/action_dispatch/http/upload.rb in the initialize method and you will see the value of @content_type set incorrectly for pdf files and correctly for the others.

So I do think this is an issue and your consideration to reopen this issue is requested.

Thanks,
-Ian

**Comment by pixeltrix** [comment]
@imorcott is this across different browsers? My initial research seems to show that this content type is returned by servers to override content sniffing by browsers and there's at least [one bug report][1] for Firefox that it modifies associated filetypes. Is it possible that you've downloaded a PDF which returned this header and it's corrupted your type associations?

[1]: https://bugzilla.mozilla.org/show_bug.cgi?id=649321

**Comment by imorcott** [comment]
When using a terminal session on my mac I check the file type using file -b --mime I get the correct content_type returned. 
For instance, running: file -b --mime QIG_MULTI_TEW410APB_FW1.1.05.pdf
Returns:  application/pdf; charset=binary
The above has been tested on several of my test upload files... So, I am sure that the content types are correct as the files exist on my machine prior to upload.

MAC 10.10.2 tested using FireFox 36.0, Chrome Version 40.0.2214.115 (64-bit) and Safari Versión 8.0.3 (10600.3.18)

I do think there is a FireFox issue playing some role:
http://jsbin.com/ulamor/213/edit?html,css,console,output
FireFox returns "application/force-download" where Chrome and Safari both return "application/pdf"

I guess a fallback position could be: If there is a known issue for pdf's getting a reported content_type of 'application/forced download' or 'application/pdf' maybe the config of Mime::Type for pdf needs to allow either content_type for the .pdf file extension and be of the rails base set of Mime:Types which IMHO are already a very limited set of mime  types. 

Thanks for working this issue.

FYI 
I have added the following Mime Types for my application:
Mime::Type.unregister(:pdf)

Mime::Type.register "application/force-download", :pdf, [], %w(pdf)

Mime::Type.register "application/vnd.ms-office", :pot, [], %w(pot)
Mime::Type.register "application/vnd.ms-office", :ppt, [], %w(ppt)
Mime::Type.register "application/vnd.ms-office", :xls, [], %w(xls)
Mime::Type.register "application/vnd.ms-office", :xlt, [], %w(xlt)

Mime::Type.register "text/x-markdown", :md, [], %w(md)
Mime::Type.register "application/x-freemind", :mm, [], %w(mm)

Mime::Type.register "application/vnd.oasis.opendocument.presentation", :odp, [], %w(odp)
Mime::Type.register "application/vnd.oasis.opendocument.spreadsheet", :ods, [], %w(ods)

# Microsoft https://technet.microsoft.com/en-us/library/ee309278%28office.12%29.aspx
# http://filext.com/faq/office_mime_types.php
Mime::Type.register "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet", :xlsx, [], %w(xlsx)
Mime::Type.register "application/vnd.openxmlformats-officedocument.spreadsheetml.template", :xltx, [], %w(xltx)
Mime::Type.register "application/vnd.openxmlformats-officedocument.presentationml.template", :potx, [], %w(potx)
Mime::Type.register "application/vnd.openxmlformats-officedocument.presentationml.slideshow", :ppsx, [], %w(ppsx)
Mime::Type.register "application/vnd.openxmlformats-officedocument.presentationml.presentation", :pptx, [], %w(pptx)
Mime::Type.register "application/vnd.openxmlformats-officedocument.presentationml.slide", :sldx, [], %w(sldx)
Mime::Type.register "application/vnd.openxmlformats-officedocument.wordprocessingml.document", :docx, [], %w(docx)
Mime::Type.register "application/vnd.openxmlformats-officedocument.wordprocessingml.template", :dotx, [], %w(dotx)
Mime::Type.register "application/vnd.ms-excel.addin.macroEnabled.12", :xlam, [], %w(xlam)
Mime::Type.register "application/vnd.ms-excel.sheet.binary.macroEnabled.12", :xlsb, [], %w(xlsb)

Mime::Type.register "application/vnd.ms-word.document.macroEnabled.12", :docm, [], %w(docm)
Mime::Type.register "application/vnd.ms-excel.sheet.macroEnabled.12", :xlsm, [], %w(xlsm)
Mime::Type.register "application/vnd.ms-excel.template.macroEnabled.12", :xltm, [], %w(xltm)
Mime::Type.register "application/vnd.ms-powerpoint.presentation.macroEnabled.12", :pptm, [], %w(pptm)
Mime::Type.register "application/vnd.ms-powerpoint.slideshow.macroEnabled.12", :ppsm, [], %w(ppsm)
Mime::Type.register "application/vnd.ms-powerpoint.template.macroEnabled.12", :potm, [], %w(potm)
Mime::Type.register "application/vnd.ms-powerpoint.addin.macroEnabled.12", :ppam, [], %w(ppam)
Mime::Type.register "application/vnd.ms-powerpoint.slide.macroEnabled.12", :sldm, [], %w(sldm)
Mime::Type.register "application/msonenote", :one, [], %w(one onetoc2 onetmp onepkg)
Mime::Type.register "application/vnd.ms-officetheme", :thmx, [], %w(thmx)
Mime::Type.register "application/msword", :doc, [], %w(doc dot)
Mime::Type.register "application/vnd.ms-word.template.macroEnabled.12", :dotm, [], %w(dotm)
Mime::Type.register "video/vnd.dlna.mpeg-tts", :mts, [], %w(mts)

**Comment by pixeltrix** [comment]
@imorcott the problem is I don't think we can blindly assume that content/force-download should map to PDF as the bug report talks about MS Office file types - the only way around this is to use something like the [`file`][1] command to actually sniff the content and not to rely on the header from the browser. I guess you could argue that this would be more secure as well.

It looks like paperclip defaults to using the header with the option of [detecting spoof headers][2].

[1]: http://linux.die.net/man/1/file
[2]: https://github.com/thoughtbot/paperclip/blob/dca87ec5d8038b2d436a75ad6119c8eb67b73e70/lib/paperclip/validators/media_type_spoof_detection_validator.rb
