### ISSUE TITLE
Not work concern class_methods block

### ISSUE THREAD

**Issue by akicho8** [rails/rails#18981]
Collision in active_support concern class_methods
https://github.com/mongoid/mongoid/issues/3951

Since not know Which problem, write here too

Using mongoid, and concern class_methods block, class method does not replace correctly.

```ruby
# -*- coding: utf-8 -*-
gem "psych", "2.0.12"
require "psych"

gem "activesupport", "4.2.0"
require "active_support/core_ext/kernel/concern"

gem "mongoid", "4.0.1"
require "mongoid" if true       # <-- If false the result is ok

class B
  def self.f
    "xxx"
  end
end

if true                         # <-- If false the result is ok
  concern :M do
    class_methods do
      def f
        "ok"
      end
    end
  end
else
  module M
    extend ActiveSupport::Concern
    module ClassMethods
      def f
        "ok"
      end
    end
  end
end

class C < B
  include M
end

C.f                             # => "xxx"
```

**Comment by kaspth** [comment]
Since your problem only happens when Mongoid is loaded, I think it's best we keep the issue over there for now. Feel free to reopen if you and @arthurnn find out the issue is on our end. :yellow_heart:

**Comment by akicho8** [comment]
https://github.com/rails/rails/pull/20494
