### ISSUE TITLE
ActiveSupport::SafeBuffer losts $1 in block of String#gsub

### ISSUE THREAD

**Issue by tdtds** [rails/rails#18985]
ActiveSupport::SafeBuffer#html_safe injected into String instances, it losts captured string ($1...) in the block of String#gsub. see:

```ruby
require 'active_support/core_ext/string/output_safety'
'abc'.html_safe.gsub(/(b)/){p $1} # => nil
'abc'.gsub(/(b)/){p $1} # => "b"
```

**Comment by matthewd** [comment]
Duplicate of #1555 (see also #12672)
