### ISSUE TITLE
Eager loading forcefully includes the default scope

### ISSUE THREAD

**Issue by andremedeiros** [rails/rails#18983]
I'm trying to eager load some records that may or may not match the default scope through a relation. Here's what I mean (and a reproduction):

```ruby
require 'active_record'

ActiveRecord::Base.logger = Logger.new(STDOUT)
ActiveSupport::LogSubscriber.colorize_logging = false

ActiveRecord::Base.establish_connection(
  adapter:  'sqlite3',
  database: ':memory:'
)

ActiveRecord::Schema.define do
  create_table :publications do |t|
    t.column :title,      :string
    t.column :deleted_at, :datetime
  end
  
  create_table :pages do |t|
    t.column :position,       :integer
    t.column :text,           :text
    t.column :publication_id, :integer
  end
end

class Publication < ActiveRecord::Base
  has_many :pages
  
  default_scope -> { where(deleted_at: nil) }
  
  def trash!
    self.class.unscoped.where(id: id).update_all(deleted_at: Time.now)
  end
end

class Page < ActiveRecord::Base
  belongs_to :publication
  belongs_to :unscoped_publication, -> { unscoped }, foreign_key: :publication_id, class_name: 'Publication'
end

enders_game = Publication.create(title: "Ender's Game")
enders_game.pages.create(position: 1, text: 'Kid goes to military school')
enders_game.pages.create(position: 2, text: 'Kid gets bullied')

enders_game.trash!

# Now I expect to find the publication
puts Page.joins(:publication).includes(:publication).to_sql

# Or here too
puts Page.joins(:unscoped_publication).includes(:unscoped_publication).to_sql
```

The problem is that both of these cases will add `"publications"."deleted_at" IS NULL` to the conditions, making it impossible to get the records I need without, at least, another query and loop. Here's the full query that is produced:

```sql
SELECT "pages"."id" AS t0_r0, 
    "pages"."position" AS t0_r1,
    "pages"."text" AS t0_r2,
    "pages"."publication_id" AS t0_r3,
    "publications"."id" AS t1_r0,
    "publications"."title" AS t1_r1,
    "publications"."deleted_at" AS t1_r2
FROM "pages"
INNER JOIN "publications" ON
    "publications"."id" = "pages"."publication_id" AND
    "publications"."deleted_at" IS NULL
```

I've searched for ways to enable this with AR, but have so far been unsuccessful. Could we get an option to disable this on specific relationships?

**Comment by eileencodes** [comment]
Hey this sounds a lot like issue #10643. Can you confirm if this is your problem?

**Comment by eileencodes** [comment]
It's not about eager loading but it sounds like `unscoped` doesn't work as expected which is why your `unscoped_publication` is possible failing.

**Comment by andremedeiros** [comment]
Hi @eileencodes, thanks for coming back to me.

This isn't the same issue. The issue is I can't preload that association with `.joins`, `.includes` or `.eager_load`.

**Comment by eileencodes** [comment]
@andremedeiros Oh I misunderstood I thought you were saying the default scope was being applied when you didn't want it to. Thanks for clarifying

**Comment by andremedeiros** [comment]
Nothing to apologise (and thanks for your hard work! <3)

Essentially, what I'm looking at here is to avoid a second query, or even worse, N+1.

**Comment by andremedeiros** [comment]
OK, a little more detail for @sgrif, if it helps. This problem is essentially divided into 2:

1. I can't avoid, at best, a second query. I guess I could get the `Page`s, get the distinct values for `publication_id`, `Publication.find_by(id: <ids>)` that collection and assign it, but doing it on a ton of places in the code is going to be cumbersome. Worst, of course, is a `Publication.unscoped { page.publication }` block to make sure it pulls the publication, but that would mean N+1 queries.

2. If your only concern is filtering out by potential out-of-scope relations, you can use the following:
```ruby
Page
  .joins("INNER JOIN publications ON pages.publication_id = publications")
  .where("publications.example IS FALSE")
```

It's not pretty, as I would prefer the `.joins(:publication)` syntax, but it helps. Let me know if you need more info.

**Comment by rafaelfranca** [comment]
@andremedeiros sorry bro, the bot closed your issue. Let me know if we need to reopen.

**Comment by andremedeiros** [comment]
That's absolutely fine, @rafaelfranca. I'll ping you if I can come up with a small replication example.
