### ISSUE TITLE
v4.2: rake db:test:prepare is run before individual tests

### ISSUE THREAD

**Issue by notalex** [rails/rails#18982]
I am in the process of upgrading a Rails 4.1.7 app to Rails 4.2. In the newer version `rake db:test:prepare` is run for individual tests, which significantly slows down individual test runs for my application.

I have setup a [sample application](https://github.com/notalex/rails_sample_app/tree/test_issue) to demonstrate the problem. The README has instructions to replicate the issue.

`rake db:test:prepare` did not run for individual tests in v4.1.7. Is there any way to make v4.2 behave in the same way?

Thanks.

**Comment by senny** [comment]
@notalex `rake db:test:prepare` should only be called when your test database needs to be synchronized (see [this](https://github.com/rails/rails/blob/master/activerecord/lib/active_record/migration.rb#L410-L414) and [this](https://github.com/rails/rails/blob/master/activerecord/lib/active_record/migration.rb#L396-L397)).

the instructions in your sample application didn't work out:

```
$ time ruby -I test test/models/user_test.rb
test/models/user_test.rb:3:in `<main>': undefined method `describe' for main:Object (NoMethodError)
ruby -I test test/models/user_test.rb  2.68s user 0.47s system 99% cpu 3.167 total
```

**Comment by notalex** [comment]
@senny, I have fixed the application now.

**Comment by senny** [comment]
@notalex this happens because the application does not have any migrations. [`!ActiveRecord::Migrator.any_migrations?`](https://github.com/rails/rails/blob/master/activerecord/lib/active_record/migration.rb#L397)
This will trigger `db:test:prepare` on every run.

This behavior was added by https://github.com/rails/rails/commit/61bacd6ef9c302238f3b8d9e6b432ee2090f6b78 to solve #17170

/cc @sgrif

**Comment by notalex** [comment]
@senny, in my original application, we use a `structure.sql` and have no migration files. I have updated the sample application to reflect the same.

Can we avoid running `rake db:test:prepare` for cases like these?

**Comment by senny** [comment]
@notalex you could monkey patch `ActiveRecord::Migrator.any_migrations?` to return `true`. This should serve as a workaround for now.

**Comment by notalex** [comment]
@senny, thanks for your input. The proposed patch resolves the problem.
