### ISSUE TITLE
incorrect behavior when joining has_many through relation

### ISSUE THREAD

**Issue by andrewpcone** [rails/rails#18995]
I have
```ruby
class User
  has_many :follower_joins, class_name:'Follow', foreign_key: :followed_id
  has_many :followers, through: :follower_joins
end

class Follow < ActiveRecord::Base
  belongs_to :follower, class_name:'User'
end
```

I want to find all of a User's followers whose email is null. So I did:
```ruby
User.where(id: [1,2,3]).joins(:followers).where(followers: {email: nil})
```
which yields:
```sql
SELECT `users`.* FROM `users` INNER JOIN `follows` ON `follows`.`followed_id` = `users`.`id` INNER JOIN `users` `followers_users` ON `followers_users`.`id` = `follows`.`follower_id` WHERE `users`.`id` IN (1, 2, 3) AND `followers`.`email` IS NULL
```

But there is no SQL table called `followers`—it is the name of the AR association. Since ActiveRecord knows that `User` is the model for `followers`, and it knows that `users` is the SQL table for `User`, it should impose the condition on the appropriate autogenerated SQL alias for `users`, namely `followers_users`:

```sql
SELECT `users`.* FROM `users` INNER JOIN `follows` ON `follows`.`followed_id` = `users`.`id` INNER JOIN `users` `followers_users` ON `followers_users`.`id` = `follows`.`follower_id` WHERE `users`.`id` IN (1, 2, 3) AND `followers_users`.`email` IS NULL
```

As it stands, I see no way to tell AR that a given `where` clause should apply to the joined association, not the model at the front of the chain. Even if there is, my code should still work: there is enough information to deduce that `followers` is an association, not a table.

However, if there are any workarounds for this problem that don't require altering AR, I'd appreciate any advice along those lines.

**Comment by gonzaloaune** [comment]
If Im not mistaken, you should be using the :source option instead:

```Ruby
has_many :followers, through: :follower_joins, source: :follow
```

http://guides.rubyonrails.org/association_basics.html#has-many-association-reference

**Comment by rafaelfranca** [comment]
I don't think `source` will fix this issue, but it is not an issue actually. There is not way of Rails doing this automatically so you should be providing the right condition in your own:

```ruby
User.where(id: [1,2,3]).joins(:followers).where('followers_users.email' => nil)
```

**Comment by andrewpcone** [comment]
Is there a way to deduce the name "followers_users"? That seems to be
what's missing. As I understand it, depending on which other clauses are
included, the name of that table might be something else.

I know that alias lives somewhere deep within activerecord, but I can not
figure out how to fetch it. And without that, it is not clear how to
define, for example, a scope that left joins some Users (perhaps they are
from an already-aliased table) with their followers.

Or maybe I'm going about this all wrong. Either way, the lack of an obvious
way to do this seems like a deficiency.

--AC

**Comment by rafaelfranca** [comment]
Actually I tried to reproduce your problem and I could not.

The following script get exactly the right table to do the query:

```ruby
unless File.exist?('Gemfile')
  File.write('Gemfile', <<-GEMFILE)
    source 'https://rubygems.org'
    gem 'rails', github: 'rails/rails'
    gem 'arel', github: 'rails/arel'
    gem 'sqlite3'
  GEMFILE

  system 'bundle'
end

require 'bundler'
Bundler.setup(:default)

require 'active_record'
require 'minitest/autorun'
require 'logger'

# This connection will do for database-independent bug reports.
ActiveRecord::Base.establish_connection(adapter: 'sqlite3', database: ':memory:')
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :follows do |t|
    t.references :follower
  end

  create_table :users do |t|
    t.integer :post_id
    t.string :email
  end
end

class User < ActiveRecord::Base
  has_many :follower_joins, class_name: 'Follow', foreign_key: :follower_id
  has_many :followers, through: :follower_joins, source: :follower
end

class Follow < ActiveRecord::Base
  belongs_to :follower, class_name: 'User'
end

class BugTest < MiniTest::Unit::TestCase
  def test_association_stuff
    User.where(id: [1, 2, 3]).joins(:followers).where(followers: { email: nil }).to_a
  end
end
```

As you can see the generated query is:

```
SELECT "users".* FROM "users"
  INNER JOIN "follows" ON "follows"."follower_id" = "users"."id"
  INNER JOIN "users" "followers_users" ON "followers_users"."id" = "follows"."follower_id"
  WHERE "users"."id" IN (1, 2, 3) AND "users"."email" IS NULL
```

`followers_users` and `users` are just aliases so the result will be the same.
