### ISSUE TITLE
`redirect_to` with a String does not respect `default_url_options`

### ISSUE THREAD

**Issue by shepmaster** [rails/rails#18997]
Rails [4.2.0](https://github.com/rails/rails/blob/v4.2.0/actionpack/lib/action_controller/metal/redirecting.rb#L89) and [4.1.8](https://github.com/rails/rails/blob/v4.1.8/actionpack/lib/action_controller/metal/redirecting.rb#L85) do not use `config.action_controller.default_url_options` to build the fully-qualified URL, but they should.

I am trying to avoid using the `Host` and `X-Forwarded-Host` headers to work around a [potential security vulnerability](http://carlos.bueno.org/2008/06/host-header-injection.html). I have set static protocol, host, and port values in my `ApplicationController#default_url_options`, but those are not used when `redirect_to` is called with a String (which would be the common case when using a `foo_path` helper).

**Comment by jvanbaarsen** [comment]
@shepmaster It seems like it never used it before? Since its also not in [4.0.0](https://github.com/rails/rails/blob/v4.0.0/actionpack/lib/action_controller/metal/redirecting.rb#L94). What makes you think that its a bug that appeared in either one of those 2 version?

**Comment by shepmaster** [comment]
@jvanbaarsen Sorry, I didn't mean to indicate it was a regression - just that the behavior is incorrect (or less-than-desired, if I'm being nice :smiling_imp:). I was pointing out that the current behavior existed in a few versions, and now you've added a third! :heart: 

I think it's incorrect because if you pass a hash to `redirect_to`, it [will use `url_for`](https://github.com/rails/rails/blob/v4.2.0/actionpack/lib/action_controller/metal/redirecting.rb#L94-L95), which will leverage the default URL options.

**Comment by jvanbaarsen** [comment]
Haha ok thanks for clarifying:heart:

**Comment by rafaelfranca** [comment]
Thank you so much for the issue but we don't take feature request on the issue tracker. We recommend you to try to implement the feature and send us a pull request or if you are in doubt if the feature will be accepts ask in Rails Core mailing list for feedback.
