### ISSUE TITLE
Removing references wrong order

### ISSUE THREAD

**Issue by sjchmiela** [rails/rails#19009]
When removing reference by eg. `rails g migration RemoveValueIdFromField value:references` the migration ends up like this:

```
remove_reference :values, :fields, index: true 
remove_foreign_key :values, :fields
```

When migrating it shouts an error *Cannot drop index 'index_fields_on_value_id': needed in a foreign key constraint*. 

Swapping the `remove_*` in migration code removes the problem.

**Comment by rafaelfranca** [comment]
This should be fixed at 4-2-stable branch.
