### ISSUE TITLE
Rails 4.2 limit columns in schema keep changing on db:migrate 

### ISSUE THREAD

**Issue by slavosarik** [rails/rails#19001]
Hello,

since upgrade to rails 4.2, everytime someone calls command "db: migrate", it randomly add or remove limit: 255 to every t.string column in whole db schema. It started to be annoying as it causes conflicts on every string column when code is being merged. We are using postgresql adapter. 

[Schema change on migration - Image attachment ](https://www.dropbox.com/s/jxg2el9nn42bfiw/migration.png?dl=0)

**Comment by rafaelfranca** [comment]
Rails doesn't add the limit value for strings anymore. If it is being removed it is because it is not specified in the column. If it is being added it is because the current schema in the database has this limit. You should specify this limit if you want.

**Comment by dahal** [comment]
I am getting the same/similar error here. Like @rafaelfranca suggested, I have defined the limit on my column. 

In addition to that, it also removed / adds the extensions. :point_down: 

![screen shot 2015-05-28 at 8 17 44 pm](https://cloud.githubusercontent.com/assets/3684236/7875809/c2e1d00a-0576-11e5-882c-7354ec81efd1.png)

**Comment by dahal** [comment]
I dropped my tables, and ran `rake db:schema:load` instead of `rake db:migrate` , it appears to have loaded the schema just fine. But I am afraid if I make any changes and run migration, the issue will repeat. Is this is rails (`migration`) issue or Postgres ?

**Comment by dahal** [comment]
I ran a new migration after loading the clean schema. And it did not change my schema (delete or add). Looks like, `rake db:migrate` does not add any limits or extensions to postgres tables anymore, not sure if thats a bug or a feature.

**Comment by bittelc** [comment]
Is the solution here to drop all tables, and :load them in again from scratch, as @dahal suggests? I am similar issue to him (limits being added to certain attributes).

What was the conclusion that closed this issue?

**Comment by jmatheus** [comment]
In case anyone still have this problem and the drop and `rake db:schema:load` didn't work. In my case dropping and using `bundle exec rake db:migrate `(to execute the command in the context of the current Bundle) did the trick.

**Comment by Ch4s3** [comment]
I have the same problem. `rake db:reset` seems to fix it until migrations get run with `rake db:migrate`, `bundle exec rake db:migrate` doesn't seem to help.

**Comment by AnthonyIsaacs** [comment]
Just run `rake db:drop db:create db:migrate` and then re-seed. For some reason my postgres DB had that limit on strings, so any `db:migrate` would run the `db:schema:dump` and pick up on the limit in postgres. Dropping will clear that structure.

**Comment by evandavis** [comment]
This is still happening for me with 4.2.5; if I run a migration, I get `limit: 4` on my integer fields even though my DB has them set to 11.

**Comment by bittelc** [comment]
There is not a clear solution in this ticket, and it should not be closed.
Solutions provided by some, do not work for all.

**Comment by evandavis** [comment]
Interestingly, the newly added limits are _completely ignored_ when doing a `db:schema:load`. :confused:

**Comment by darrenleeweber** [comment]
:+1: to re-open this and fix it.

**Comment by bittelc** [comment]
:+1:

**Comment by vishaldeepak** [comment]
has this been fixed? I having trouble and the solution given does not work for me.

**Comment by sic-f** [comment]
setting limit on a string column also does not work for me. I set a limit of 3 on a username column and still accepts a string of more than 3 characters.

**Comment by lleolin** [comment]
I don't know if anyone's problem is the same as mine. Essentially what I'm dealing with is that the production database schema is out of sync with a schema generated from scratch.

If I load a database dump from our production servers into my local database, string columns have `limits` or `money` columns will instead be `decimal` columns. However, if I `rake db:drop && rake db:create && rake db:migrate`, the resultant schema will not have the limits, or I'll find a `money` field where there used to be a `decimal` field. The resultant schema will diverge in many ways from the schema that the actual production servers are using.

This creates all manner of conflicts. What I can't figure out is how to address this, to make the production schema the same as a "fresh" schema, without a crap-ton of handwritten migrations to remove limits and turn decimal columns into money columns.

**Comment by nekogami** [comment]
I also have a problem on that,
For some reason, when I run rake db:migrate on my computer, the generated schema.rb add limits statement to ALL string/text/integer fields.
The biggest problem here is that integer are marked as limit: 4 while in mysql show columns they are marked as INT(11).

I tried to install the same version as the other devs, checked the gemfile.lock everything is the same, I even did a clean install from scratch just in case.
I have just no idea where it comes from.

Rails 4.2.3
Ruby 2.2.3-p173
mysql2 driver: 0.3.18
mysql version: 5.7.11 (from home brew, but I also tried various version directly from the oracle website before making the clean install)

**Comment by gamov** [comment]
Same here, all those limits were added automatically to my schema (along side the force: cascade) when I ran rake db:migrate 😓:
```ruby
    t.string  "marking",            limit: 255
    t.text    "desc",               limit: 65535
    t.integer "company_profile_id", limit: 4, null: false
```
Integers in the DB are still defined as int(11), string as varchar(255) and text as text

Rails 4.2.6
ruby 2.2.5p319 
mysql2 0.4.4
mysql version: 5.7.12

The limits seem to come from abstract_mysql_adapter#initialize_type_map

**Comment by LucasArruda** [comment]
Thanks @AnthonyIsaacs !
That is indeed why it happens sporadically or randomly.
Rails just picks whatever is set by the DB (PG in this case).

**Comment by frsantos** [comment]
@evandavis The `limit: 4` in the schema refers to how many bytes of storage uses the field. The `int(11)` in the DB refers to how many digits will be displayed, independently of storage.

See http://dev.mysql.com/doc/refman/5.7/en/numeric-type-attributes.html.

> The display width does not constrain the range of values that can be stored in the column

**Comment by buckspencer** [comment]
I was able to solve this issue by upgrading to PostgreSQL version >= 9.5

**Comment by jonathonnordquist** [comment]
Madness that this was closed, or that this problem is still ongoing with no workable fix.  I'm in Rails 6.1, trying to add a single column to an existing table and running the migration removes the `limit` constraint from literally hundreds of unrelated fields.  I don't know why this is happening, I don't know what it will or will not break and I don't know why Rails is doing something that I'm very much not telling it to.

**Comment by zzak** [comment]
@jonathonnordquist I understand this sounds very frustrating, but I'm afraid if the issue has persisted this long then "fixing" it will likely take large amounts of effort.

If someone could help create an [executable bug report](https://github.com/rails/rails/blob/main/guides/bug_report_templates/active_record_migrations_main.rb) that might help move this forward. :bow:
