### ISSUE TITLE
Option "selected" unnecessary for the "select_tag"

### ISSUE THREAD

**Issue by LeandroSNunes** [rails/rails#19011]
The "selected" option is not doing what it should do

The example:
```ruby
select_tag "people", options_from_collection_for_select(@people, "id", "name"), selected: ["1", "David"]
# <select id="people" name="people"><option value="1" selected="selected">David</option></select>
```
could be
```ruby
select_tag "people", options_from_collection_for_select(@people, "id", "name", "1")
# <select id="people" name="people"><option value="1" selected="selected">David</option></select>
```
Due to have not treatment to set the selected option_tags in https://github.com/rails/rails/blob/e0e9d5bd8600c01de6b73487bf66046d179c0ed7/actionview/lib/action_view/helpers/form_tag_helper.rb#L132

**Comment by rafaelfranca** [comment]
I think this is a documentation problem. That option don't work for `select_tag`. I'll remove it.

**Comment by LeandroSNunes** [comment]
@rafaelfranca https://github.com/rails/rails/pull/19012 :wink:
