### ISSUE TITLE
Not is possible execute rake db:fixtures:load with helpers in fixtures

### ISSUE THREAD

**Issue by lazaronixon** [rails/rails#19020]
According to http://api.rubyonrails.org/classes/ActiveRecord/FixtureSet.html
Is possible inject helpers on fixtures using 
```
ActiveRecord::FixtureSet.context_class.send :include, FixtureFileHelpers
```

It works when execute rake test.. But if execute rake db:fixtures:load this throw a undefined method exception.

**Comment by rafaelfranca** [comment]
Can you please provide a sample application that reproduces the error?

**Comment by lazaronixon** [comment]
https://github.com/lazaronixon/fixture_helper_error

**Comment by senny** [comment]
@lazaronixon We put:

```erb
<% require Rails.root + "test/support/fixture_upload" %>
```

At the top of fixtures to solve that issue. Also what should work is to extend the `:environment` task and load the file there.

**Comment by lazaronixon** [comment]
Didn't work to me, Could you do a pull request with the solution to example application?

**Comment by senny** [comment]
@lazaronixon https://gist.github.com/senny/c8cad80acf0f124151ae patching the `environment` task is intrusive, a better option would be to overwrite `db:fixtures:load` and prepend the require there.

**Comment by lazaronixon** [comment]
Thank you @senny is working now...
