### ISSUE TITLE
`circular dependency`  caused by inheritance in application controller of Rails 4.2.0 engine

### ISSUE THREAD

**Issue by emclab** [rails/rails#19022]
When upgrading engine from rails 3.2 to rails 4.2.0, the following inheritance in application controller causes `circular dependency` error in rspec (3.2):

    class ApplicationController < ApplicationController
    end

There is `config.eager_load = false`  in config/development.rb.

The error is:

    activesupport-4.2.0/lib/active_support/dependencies.rb:492:in `load_missing_constant': Circular dependency detected while autoloading con
    stant Authentify::ApplicationController (RuntimeError)

Here is the rails engine document (ch:4.3.2) explaining the purpose of the inheritance - http://guides.rubyonrails.org/engines.html#using-a-class-provided-by-the-application.

The error disappears if changing to '< ActionController::Base'. Is there way fixing the problem?

**Comment by rafaelfranca** [comment]
Could you provide a way to reproduce it?

**Comment by kaspth** [comment]
From the example you've given, it seems you don't have a namespace. I'm pretty sure that's your problem.

When Rails encounters the `< ApplicationController` bit, it tries to reload the `application_controller.rb` file because the original `ApplicationController` isn't completely defined yet. Adding a namespace should fix this:

```ruby
module EngineName
  class ApplicationController < ApplicationController
  end
end
```

**Comment by emclab** [comment]
There is namespace module EngineName in engine's application controller.

**Comment by kaspth** [comment]
And does your directory structure reflect the namespace like the documentation, you link to, says? `app/controllers/engine_name/application_controller.rb`

**Comment by emclab** [comment]
yes, it is.

**Comment by emclab** [comment]
Here is a test engine I created  git@github.com:emclab/test4.git.

bundle exec rspec spec causes the error:
$ bundle exec rspec spec
c:/Ruby200/lib/ruby/gems/2.0.0/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:492:in `load_missing_constant': Circular dependency detected while autoloading con
stant Test4::ApplicationController (RuntimeError)

**Comment by kaspth** [comment]
Okay, I think I see it :smile: Either inline the namespace:

```ruby
class EngineName::ApplicationController < ApplicationController
```

Or clarify that you're inheriting from the `ApplicationController` at the top level scope:

```ruby
module EngineName
  class ApplicationController < ::ApplicationController
  end
end
```

**Comment by emclab** [comment]
Great, thank you kaspth! BTW, is it helpful if rails document is upgraded accordingly?

**Comment by kaspth** [comment]
Great, :+1:. Send us a pull request with your proposed change and we'll see :smile:

--
Kasper

**Comment by emclab** [comment]
Somehow 
class MyEngineName::ApplicationController < ApplicationController still not work (same error). But
class ApplicationController < ::ApplicationController  and
class MyEngineName::ApplicationController < ::ApplicationController work. On this regard, the engine's doc needs to be changed a little bit. Here is the current engine doc:

class Blorgh::ApplicationController < ApplicationController
end 

The correct one format is:

class Blorgh::ApplicationController < ::ApplicationController
end

Not sure how I can send a pull  request for the doc. Never done it before.

**Comment by emclab** [comment]
Created a pull request
