### ISSUE TITLE
Controller actions should default to head :ok if no template exists

### ISSUE THREAD

**Issue by dhh** [rails/rails#19036]
It's a great default for controllers that generate HTML that we default to rendering the corresponding template, but it's a hassle for API-controllers. The default should be "everything went fine" in both cases. So let's instead return `head :ok` for actions with no corresponding templates, rather than raising an error. That'll slim down API controller methods that simply worked, and need no further instructions.

**Comment by simi** [comment]
I can take a look at this.

**Comment by dhh** [comment]
👌

**Comment by pixeltrix** [comment]
@dhh do you have an example of an API controller action that doesn't have a template and doesn't render a response like `render json: object` ?

**Comment by dhh** [comment]
Sure, any method that basically just triggers an action. Here are a few examples:

* PinsController#create (creates a pinned message)
* UnreadsController#destroy (removes unread counter for a message)
* PositionsController#update (sets the position for a todo in a todolist)

I have a total of 22 such actions via the API/Ajax in my current project.

**Comment by pixeltrix** [comment]
> PinsController#create

Shouldn't this be a `201 Created` with a `Location` header?

> UnreadsController#destroy
> PositionsController#update

These should probably be `204 No Content` rather than `200 OK` shouldn't they?

My concern is that for the sake of saving one line from an action we're masking behaviour and adding 'magic' which is the primary reason we took out `respond_with`, etc. isn't it?

**Comment by dhh** [comment]
201 Created with Location is great when you care about the resource created, but often you don’t. In this case, you don’t.

Actually, yes, 204 No Content is the correct answer for these.

I don’t think there’s any magic here, because it’s not content type specific (the problem with respond_with). This is just the default behavior: If there’s a template, render that. If not, assume 204 No Content success.

**Comment by sb8244** [comment]
Looking to do a contribution to Rails and found this issue. @simi are you still looking into this?

I dug around a little bit this morning and think it could be done through `ActionDispatch::ExceptionWrapper`. I'm not sure that actionpack handles missing templates other than through this class. It looks to me like actionview is the gem in charge of that.

Rendering status 200 for HEAD requests (but not others) could be done by allowing `@@rescue_responses` to respond based on `env["REQUEST_METHOD"]`. This feels a bit hacky, so I would be happy to look into it more, or not if @simi is handling it.

**Comment by dhh** [comment]
Hi @sb8244, thanks for looking into this. As I recall, we declare the default behavior for controllers somewhere. I think it's default_render something. That's where we need to hook in. We don't want this response to have to flow through an exception (that's slow, and this is not an exceptional state). As @pixeltrix says, we'll want to return a 204 (so head :no_content). There's no difference between an API vs HTML rendering controller in this case.

**Comment by sb8244** [comment]
Thanks @dhh. I opened a PR so that it is easier to accept feedback.

**Comment by dhh** [comment]
Nice. What’s the link?

**Comment by sb8244** [comment]
Oh email doesn't show the reference: https://github.com/rails/rails/pull/19377 Rafael has given some feedback which I will soon apply.

**Comment by dhh** [comment]
👍

Also, make sure we explicit log what’s happening. I could see a potential for people being confused with a blank screen, if we’re not very explicit in the log about why that’s happening.

**Comment by simi** [comment]
@sb8244 thanks for taking this. I was on vacation for few weeks.

**Comment by sb8244** [comment]
Thanks @simi . I have a few outstanding items on the PR. Help would be appreciated. The failing test right now has to do with implicit rendering of variants. It seems that the default render is to render the variant's name, which is not inline with the normal rendering behavior. 

So no template exists,  I am triggering `head :no_content` and it is failing specs as the content should be "variant_name"

**Comment by kaspth** [comment]
@dhh do we need an upgrade flag for this? People might be surprised to see explicit erring move to implicit successes.

**Comment by dhh** [comment]
Don't think so. Nobody is going to leave an action that willfully does a 500 in place. Well, nobody sane that is. And even if they were, returning a 204 no content isn't going to break anything meaningful over a 500.

**Comment by kaspth** [comment]
Right on! Then the PR is ready to be merged if you wanna pull the trigger :wink:

--
Kasper

> Den 05/04/2015 kl. 19.31 skrev David Heinemeier Hansson <notifications@github.com>:
> 
> Don't think so. Nobody is going to leave an action that willfully does a 500 in place. Well, nobody sane that is. And even if they were, returning a 204 no content isn't going to break anything meaningful over a 500. 
> 
>

**Comment by claudiob** [comment]
@dhh I think this change might generate some confusion among beginners.

When you are building a new controller, you typically write the routes and the actions before adding the views to `app/views`.

In Rails < 5, if you clicked on a link that goes to one of the actions for which you haven't written a view yet, you would see an big red error page saying "Template is missing!" which would help you understand where to add the view.

In Rails 5.0.0.beta, if you clicked on the same link, you would just see a brief flash in the browser and then… nothing, like you didn't click at all. You can click, click, click, and nothing happens, the page does not change and no error shows up.

Only looking at your log you would see the message

```
No template found, rendering head :no_content
Completed 204 No Content in 5ms (ActiveRecord: 0.0ms)
```  

I don't have a better solution to suggest, I just wanted to make this clear.

**Comment by radar** [comment]
:+1: for making this a configurable thing that is _off_ by default.

**Comment by matthewd** [comment]
Can we 500 in response to a "real" browser request, but 204 for XMLHTTP and other non-browser clients?

**Comment by baweaver** [comment]
Agreed on the confusing aspect, and on the configurable option.

It makes sense as long as you explicitly set it as such, but a purely implicit version would lead to a lot of interesting headaches on IRC and SO. 

It might be a worthwhile consideration to get a variant of the hallway test for this type of thing, except preference to newer users. What makes sense to someone with experience may be incomprehensible to a newer developer, raising the barrier to entry.

**Comment by sb8244** [comment]
If it were configurable, I would personally want it as a config option that is always on, not xhr dependent. I often debug problemsome xhr requests by "open request in new tab", and different behavior would also be confusing.

**Comment by matthewd** [comment]
@sb8244 to me, the point is that a 204 in a browser is always going to be confusing. So a message that describes what just happened [1] should be clearer than a browser that just refuses to navigate to the URL you want.

1. "your action completed successfully without rendering a response, and no view was found, but as this is a browser request, we can't return a 204. If you intend to use this via XHR/an API, it's working fine. If you intended to display a view: we searched app/views for ..."

**Comment by sb8244** [comment]
That is a fair point. Just tested it and I would be confused if the browser request didn't have a body when I didn't mean for it.

**Comment by kevinhofmaenner** [comment]
Just a heads up, the [official beginners guide](http://guides.rubyonrails.org/getting_started.html) references the 'Template is missing' error page multiple times and even teaches beginners to build routes and controllers before views to see what happens (teaching new users to expect a template is missing error). As a beginner myself, this change in rails 5 really threw me off as I couldn't figure out what was going on until I looked at the server logs.

**Comment by dhh** [comment]
We should certainly update those guides to not suggest such a workflow. Please do open a PR.

Training wheels are great, when they don't interfere with what a final app should look like. In this case, they unfortunately do. 

If there's a way to keep rendering a training wheel page on the 204, when the request is a regular browser hit, then that's fine with me. But we are not going back to what we had. That ship has sailed.

**Comment by hopewise** [comment]
I am struggling to let rails conceive the fact that I am asking for json response, as it keeps to look for missing templates on a json request, as here:  https://stackoverflow.com/questions/59962060/why-rails-fails-to-detect-ajax-request-in-production
