### ISSUE TITLE
to_param sometimes not calling for Model

### ISSUE THREAD

**Issue by bezludny** [rails/rails#19031]
I have strange problem looks like a rails bug (not sure). There is the situation: I use to_param for make seo-friendly urls for my objects (Products and Categories). On my views I use helpers product_path and category_path. The problem is sometimes I have expected to_param based urls (/categories/39-средства-дезинфекции), sometimes is not (/categories/39) for the same objects on the same pages and using the same views. 

I have done some research and this is what I found. My method to_param for Category model:

```ruby
def to_param
  puts 'I am in Category to_param'
  "#{id}-#{title.to_slug.normalize.to_s}"
end
```

So, when url_helpers work correctly I can see on my server console string 'I am in Category to_param'. That means method is working as expected. But when I have incorrect urls on my view, I can see any strings on my console from to_param model method. Looks like it's not calling or working only to_param from base class. 

The problem is I can't reproduce this issue. There is no regularity and conditions. The same models, the same objects and the same url_helpers for views. 

P. S. Sorry if my description is not clear.

**Comment by jvanbaarsen** [comment]
@bezludny When you call the `product_path` route helper, are you always passing in a `Product` object? or are you passing in the ID of the product?
i.e:

```ruby
@product = Product.find(1234)
product_path(@product)

# Or

product_path(id: 1234)
```

**Comment by bezludny** [comment]
Yes. Also strange thing that this behaviour is not regular. If I may use helper without ID, so why sometimes I have this issue and sometimes is not?

My Rails version was 4.1.6 and Ruby 2.2.0
Now I updated to 4.2 – I'll inspect how it works.

**Comment by bezludny** [comment]
Also, after server restart problem may disappear. 
On the same page, where I can see incorrect url, after cap deploy:restart

**Comment by rafaelfranca** [comment]
If there is no predictable way to reproduce it we don't have how to help. It may be related with some thread safety issue, but we can't be sure without having a way to reproduce.

**Comment by bezludny** [comment]
I found the reason. 
I have defined for my ActiveAdmin before filter with:

  before_filter do
    Product.class_eval do
      def to_param
        id.to_s
      end
    end

    Category.class_eval do
      def to_param
        id.to_s
      end
    end
  end

So, when I logged in into admin panel and go to the Products page – to_param for my models redefine. My fault.
