### ISSUE TITLE
Project with the same directory name

### ISSUE THREAD

**Issue by thalesfp** [rails/rails#19049]
When I create a project with the same directory name that he is, sometimes the scaffold command stucks and if there is a project inside this directory with the same scaffold name, rails indicates a conflict. Even if you force the command, the files are created on the another project.

**Comment by rafaelfranca** [comment]
Could you provide the steps to reproduce this issue?

**Comment by thalesfp** [comment]
```shell
mkdir myapp
cd myapp

rails new myapp
cd myapp
rails g scaffold Person name:string

cd ..
mv myapp myapp.old

rails new myapp
cd myapp
rails g scaffold Person name:string
```
In this last scaffold the files will be created as identical.

**Comment by thalesfp** [comment]
I test it in 4.2.0 and 4.2.1.rc1

**Comment by tejasbubane** [comment]
I can reproduce this in 4.2.0

**Comment by kennyj** [comment]
I can reproduce this too (on ubuntu linux)
I think it is caused by `spring` processes. When stopping `spring` processes,  this issue disappears.

**Comment by renanoronfle** [comment]
i can reproduce this too and @kennyj is right when restart spring the issue disappears.
Create project and run scaffold and check spring status:

```bash
rails new myapp
rails g scaffold user name:string
bundle exec spring status
24843 spring server | myapp | started 11 secs ago  RBENV_VERSION=2.1.5 TERM_PROGRAM=iTerm.app SHELL=/bin/zsh
24844 spring app    | myapp | started 11 secs ago | development mode

cd ..
mv myapp myapp.old
rails new myapp
cd myapp
bundle exec spring status

24843 spring server | myapp | started 1 min ago    RBENV_VERSION=2.1.5
24905 spring app    | myapp.old | started 35 secs ago | development mode
```

but this is not happing when the project has other name for example:

```bash
cd ..
rails new myproject
cd myproject
bundle exec spring status
Spring is not running.
```

**Comment by hjoo** [comment]
I was looking through this issue with @stepzhou, and it looks like this is a problem with how Spring stores state. Spring stores state using a file lock of MD5(ruby version + project root).pid and checks the server status accordingly (https://github.com/rails/spring/blob/master/lib/spring/env.rb#L68-L78). So for example, when you make an app called Test and start the Spring server for it, Spring will create a file lock hashed on the application root (Test) and the server is tied to the original app name. 

Should this issue be moved to rails/spring?

**Comment by eileencodes** [comment]
@hjoo and @stepzhou this does sound like it should be moved to spring, can you test with spring master branch to see if the issue is currently present there? If not you can send a PR to spring or open an issue there.

**Comment by hjoo** [comment]
It looks like there's a spring issue for the problem here: https://github.com/rails/spring/issues/247.
