### ISSUE TITLE
Belongs to relation validation doesn't check if relation is valid

### ISSUE THREAD

**Issue by jensljungblad** [rails/rails#19043]
Using Rails 4.2.0, given these models
```ruby
class Favoriting < ActiveRecord::Base
  belongs_to :card
  validates :card, presence: true
end

class Card
  has_many :favoritings
  validates :title, presence: true
end
```

Or using the new `required` keyword:
```ruby
class Favoriting < ActiveRecord::Base
  belongs_to :card, required: true
end
```

This saves the `Favoriting` to the database (without a card_id) even though I have a validation for card presence in my `Favoriting` model.
```ruby
favoriting = Favoriting.create!(card: Card.new)
```

Is this intended behavior? It saves an invalid favoriting to the database.

**Comment by simi** [comment]
Can you try: `belongs_to :card, required: true`?

Also check out http://api.rubyonrails.org/classes/ActiveRecord/Associations/ClassMethods.html#method-i-belongs_to.

**Comment by jensljungblad** [comment]
Yes I've tried that as well. Same behavior.

**Comment by simi** [comment]
Can you provide minimal script to reproduce using https://github.com/rails/rails/blob/master/guides/bug_report_templates/active_record_gem.rb ?

**Comment by jensljungblad** [comment]
```ruby
# Activate the gem you are reporting the issue against.
gem 'activerecord', '4.2.0'
require 'active_record'
require 'minitest/autorun'
require 'logger'

# Ensure backward compatibility with Minitest 4
Minitest::Test = MiniTest::Unit::TestCase unless defined?(Minitest::Test)

# This connection will do for database-independent bug reports.
ActiveRecord::Base.establish_connection(adapter: 'sqlite3', database: ':memory:')
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :cards, force: true do |t|
    t.string :title
  end

  create_table :favoritings, force: true do |t|
    t.integer :card_id
  end
end

class Card < ActiveRecord::Base
  has_many :favoritings
  validates :title, presence: true
end

class Favoriting < ActiveRecord::Base
  belongs_to :card
  validates :card, presence: true
end

class BugTest < Minitest::Test
  def test_valid
    favoriting = Favoriting.create!(card: Card.new(title: "foo"))

    assert favoriting.valid?, "should be valid"
    assert favoriting.persisted?, "should be persisted"
    assert Favoriting.last.valid?, "should be valid"
  end

  def test_invalid
    favoriting = Favoriting.create!(card: Card.new)

    refute favoriting.valid?, "should not be valid"
    refute favoriting.persisted?, "should not be persisted"

    # Favoriting.last.valid returns false here, should not even
    # be persisted
  end
end
```

**Comment by rafaelfranca** [comment]
Presence validation only check if the record is present but not if it is valid. What you want is http://api.rubyonrails.org/classes/ActiveRecord/Validations/ClassMethods.html#method-i-validates_associated

**Comment by jensljungblad** [comment]
Okay, I played a bit with the script and apparently this works as you say:

```ruby
class Favoriting < ActiveRecord::Base
  belongs_to :card, validate: true
  validates :card, presence: true
end
```

I was wondering why I never noticed this before when I tried:

```ruby
class Favoriting < ActiveRecord::Base
  belongs_to :card
  validates :card, presence: true
  accepts_nested_attributes_for :card
end
```

Which also works. So `accepts_nested_attributes_for` sets `validate` to true. This seems kinda confusing to me... Also, why would you ever use `required` without also having the relation validated? 

Sorry if I posted this in the wrong place. Should these things go in the mailing list?

**Comment by rafaelfranca** [comment]
@jensljungblad no, this is the correct place in this case.

> Also, why would you ever use required without also having the relation validated?

This is a good question. I thought the same when I saw your question. In Rails 5 we will default the required option of `belongs_to` to be `true`, so maybe we should make `validate` true by default too.

**Comment by jensljungblad** [comment]
Sounds like a good idea. What's the rationale for not having it on for `has_one` and `has_many`? I cannot really think of any reason you'd want to save invalid models to the database.

**Comment by rafaelfranca** [comment]
`has_one` is not usually required, but we can try to enable by default.

Want to try an implementation?

**Comment by ricsdeol** [comment]
Hi, I had other situation:

```
class Pop < ActiveRecord::Base
