### ISSUE TITLE
Mailer previews does not work properly!

### ISSUE THREAD

**Issue by zeitnot** [rails/rails#19040]
Rails can preview the mail content but but it does not render it with UTF-8. For example if you are using 
```html
<meta charset='utf-8'></meta>
```
it translates this as `<meta charset=3D'utf-8'>`.  This is a turkish example.

```haml
!!!
%html{:lang => "en"}
  %head
    %meta{charset: "utf-8"}
  %body
    %p Merhaba,
    %p Mustafa Efe sizi test adlı takıma katılmanız için davet etti. 
    %p Takıma katılmayı onaylıyorsanız lütfen #{link_to('buraya',verify_organization_member_url(token: @organization_member.invitation_token))} tıklayınız.
```

And this becames:

```html
<!DOCTYPE html>
<html lang=3D'en'>
  <head>
    <meta charset=3D'utf-8'>
  </head>
  <body>
    <p>Merhaba,</p>
    <p>Mehmet Y=C4=B1ld=C4=B1z sizi Organization - 616 adl=C4=B1 tak=C4=B1=
ma kat=C4=B1lman=C4=B1z i=C3=A7in davet etti.</p>
    <p>Tak=C4=B1ma kat=C4=B1lmay=C4=B1 onayl=C4=B1yorsan=C4=B1z l=C3=BCtf=
en <a href=3D"http://localhost:3000/organizations/verify_member/oO86ZuU5"=
>buraya</a> t=C4=B1klay=C4=B1n=C4=B1z.</p>
  </body>
</html>

```

As you see turkish chars are broken and html nodes get `3D` prefix for all attributes. I do not know how to solve this. 

## Update
I am using rails `4.1.9` and someone is looking for a solution [here][0] as well.

[0]: https://www.ruby-forum.com/topic/77045

**Comment by jvanbaarsen** [comment]
@zeitnot Can you please provide a test project that has this issue? Also you have a minor typo in your title: Miler -> Mailer

**Comment by zeitnot** [comment]
@jvanbaarsen [here][0] is the sample repo. I think I find where from the error occurs. When using `include Sidekiq::Mailer` into mailer's class this error occurs. If we remove it then everything is normal. 

[0]: https://github.com/zeitnot/rails-mailer-preview

**Comment by jvanbaarsen** [comment]
@zeitnot What is the reason for including SIdekiq::Mailer? You can also send out emails using sidekiq with: `SampleMailer.delay.email_method`: https://github.com/mperham/sidekiq/wiki/Delayed-extensions#actionmailer

**Comment by zeitnot** [comment]
@jvanbaarsen I know but I do not want use `delay` method as extra. With SIdekiq::Mailer I can send the email with sidekiq without `delay` extra method.

**Comment by zeitnot** [comment]
@jvanbaarsen btw this error occurs only on preview mode. The email is going properly.

**Comment by jvanbaarsen** [comment]
@rafaelfranca Can you add the label ActionMailer?

**Comment by zeitnot** [comment]
@jvanbaarsen I can't add that label.

**Comment by jvanbaarsen** [comment]
@zeitnot Thats why I pinged @rafaelfranca  ;)

**Comment by kaspth** [comment]
@zeitnot can you update the title again? You know more about the issue now so adding that information is helpful for other's when looking through the issues list :wink:

Also in the future please don't use titles like "does not work properly!", it kills our motivation to help you. Thanks :heart:

Have you tried filing this issue on Sidekiq? I think it feels more apt there because you include a Sidekiq module which breaks the preview feature. @seuros, what do you think?

**Comment by rafaelfranca** [comment]
Yeah, this seems to be more a sidekiq problem. Let us know if you can reproduce it without sidekiq and I'll reopen.

Thank you for the report.

**Comment by zeitnot** [comment]
@kaspth I am really sorry for that and thank you for your courtesy.
