### ISSUE TITLE
Infinite loop calling to_json on ActiveModel::Name

### ISSUE THREAD

**Issue by jonswar** [rails/rails#19050]
Calling to_json on an ActiveModel::Name, or any data structure containing it, results in an infinite loop.

    #!/usr/bin/env ruby
    unless File.exists?('Gemfile')
      File.write('Gemfile', <<-GEMFILE)
        source 'https://rubygems.org'
        gem 'rails', '4.2.0'
        gem 'json', '1.8.1'
        gem 'sqlite3'
      GEMFILE
    
      system 'bundle'
    end
    
    require 'bundler'
    Bundler.setup(:default)
    
    require 'active_record'
    require 'minitest/autorun'
    require 'logger'
    
    # This connection will do for database-independent bug reports.
    ActiveRecord::Base.establish_connection(adapter: 'sqlite3', database: ':memory:')
    ActiveRecord::Base.logger = Logger.new(STDOUT)
    
    ActiveRecord::Schema.define do
      create_table :books do |t|
      end
    end
    
    class Book < ActiveRecord::Base
    end
    
    class BugTest < MiniTest::Test
      def test_convert_model_name_to_json
        assert Book.model_name.to_json.present?
      end
    end

**Comment by ianks** [comment]
I'll take a stab at this.

**Comment by VanessaHenderson** [comment]
Is this fix included in 4.2.1.rc3?
