### ISSUE TITLE
etag_matches? does not work correctly when the tags include the '-gzip' suffix

### ISSUE THREAD

**Issue by ruipgpinheiro** [rails/rails#19056]
So, I've been trying to figure out why my application running on 4.2 wasn't answering using 304 Not Modified, except in very rare cases, even though the etag and if-modified-since header are correct.

I keep having situations where Firefox sent the following headers:
> If-Modified-Since	Tue, 24 Feb 2015 02:56:06 GMT
> If-None-Match	"d7ce2a284581b0ecbd36707d44647d47-gzip"

And rails answered with these, and a 200 response (so it was processing the request from scratch):
>Etag	"d7ce2a284581b0ecbd36707d44647d47-gzip"
>Last-Modified	Tue, 24 Feb 2015 02:56:06 GMT

As can be seen, both the etag and the modified date match. To be exact, they're *exactly the same*.

And that's the problem - when the browser requests the content the first time, it receives the correct etag and last modified date. On further requests, it sends if-modified-since with the last-modified date it received previously.

For some reason, rails is considering that is stale, and processes the request again.

The code I'm using (and yes, it is generating dynamic CSS. It works, just not the stale? caching):

    def shows
        etag = "#{ current_user.id }"
        last_modified = current_user.shows_updated_at
	
        if stale?(etag: etag, last_modified: last_modified)
            respond_to do |format|
                format.css { render :content_type => "text/css" }
            end
        end
    end

**Comment by ruipgpinheiro** [comment]
After some further digging, I discovered that it's failing at the etag_matches?(etag) call in fresh?.

That function is defined like this:

    # File actionpack/lib/action_dispatch/http/cache.rb, line 30
    def etag_matches?(etag)
      if etag
        etag = etag.gsub(/^\"|\"$/, "")
        if_none_match_etags.include?(etag)
      end
    end

I logged the parameters after the etag = etag.gsub line, before returning the result, and this in an example:
> etag = ca6b75a007da7a11d49de32d16a51809
> if_none_match_etags = ["ca6b75a007da7a11d49de32d16a51809-gzip"]

That '-gzip' appended at the end breaks the etag comparison.

**Comment by ruipgpinheiro** [comment]
I'm not sure if it's the best way of doing it, but I've implemented a temporary fix for myself, which completely fixes the problem I was having. I just dropped this into an initializer:

    module ActionDispatch::Http::Cache::Request
    	 def etag_matches?(etag)
    		if etag
    			etag = etag.gsub(/^\"|\"$/, "")
    			if_none_match_etags.each do |if_none_match_etag|
    				return true if if_none_match_etag.include?(etag)
    			end
     			return false
     		end
     	end
     end

The idea is that instead of searching the array for the etag I aim to compare against, I search EACH of the entries in the array for the etag as a substring.

**Comment by rafaelfranca** [comment]
What is generating this gzip in the end of the etag? It seems to be the
problem

**Comment by ruipgpinheiro** [comment]
I'm not sure. The server (I'm running rails 4.2 with Apache and Passenger Phusion) seems to do it. WebBrick doesn't.

Might have something to do with the fact that I'm rendering CSS? Does Rails/Passenger/Apache compress CSS or something?

**Comment by ruipgpinheiro** [comment]
I investigated a bit more, and my browser *does* send the header
> Accept-Encoding	gzip, deflate

And the replies (not just the ones I'm trying to manually cache client-side) contain the header:
> Content-Encoding	gzip

I just checked, and my Apache install has mod_deflate active. So I assume Apache is compressing stuff with gzip, and as a side-effect adding the suffix "-gzip" to the etag. Rails doesn't expect that, so etag_matches? breaks.

After some googling, it does seem to be the case that Apache mod_deflate appends -gzip to the etag so that public proxies/caches don't cache it as if it were the same content as the non-compressed file.

I think this counts as a rails bug - there's no reason Rails shouldn't work with Apache and mod_deflate. At least there should be a warning in the docs, I think!

**Comment by ianks** [comment]
Inside your controller, can you give me the output of `env[HTTP_IF_NONE_MATCH]`?

**Comment by ruipgpinheiro** [comment]
I looked at the output of request.env['HTTP_IF_NONE_MATCH'] during the controller call, and it exhibits the same suffix. For example:

"d19bf4831f99b40fca08772de129afb2-gzip"
when the etag that Rails/Apache sends after the 200 response is 
"d19bf4831f99b40fca08772de129afb2-gzip"
but the etag that Rails compares against during etag_matches? is
"d19bf4831f99b40fca08772de129afb2"

**Comment by georgeclaghorn** [comment]
Matching ETags indicate that the responses associated with each are byte-for-byte identical. The compressed response generated by mod_deflate is not identical to the response generated by Rails, so their respective ETags must not match. In a similar vein, Nginx strips ETags from compressed responses.

**Comment by rafaelfranca** [comment]
> The compressed response generated by mod_deflate is not identical to the response generated by Rails, so their respective ETags must not match.

Yes. Exactly this.

**Comment by ruipgpinheiro** [comment]
I know, but I don't think this should be closed. This is because etag_matches? ignores the fact that the response is compressed, and as such will *never* work if the server compresses the response.

It can be seen that the server *is* sending the "-gzip" etag, which the client stores and sends back later, but rails thinks the data sent is out-of-date as it does not include the "-gzip" tag in the comparison. This means that the data sent will **always** be stale in the eyes of Rails, even though it shouldn't be.

Anyway, I have got my fix, so if you really want to close it I won't protest any more. I still think that this is a bug, or should at least be added as a note to the documentation.

Thanks for your time

**Comment by ianks** [comment]
I tend to agree that this is a bug. I think this case argues for Weak Validation as the hashed value is, for all intents and purposes, the only semantically important value here.

**Comment by ianks** [comment]
@ruipgpinheiro Could you create an example app? I am having some trouble recreating this behavior. Namely, I'm having trouble seeing how `env[HTTP_IF_NONE_MATCH]` can be different from the etag that `etag_matches` recieves. It seems to me that Rails directly uses `env[HTTP_IF_NONE_MATCH]` in `etag_matches?`

**Comment by ruipgpinheiro** [comment]
The code at the start of the thread reproduces the problem. I can make it an app and post it here if you need.

I think you've slightly misunderstood the problem - the etag_matches? receives as argument the tag that was sent into the stale? method, which is a hash relating to the up-to-date data. The if_none_match_etags vector contains env[HTTP_IF_NONE_MATCH].

    # File actionpack/lib/action_dispatch/http/cache.rb, line 30
    def etag_matches?(etag)
      if etag
        etag = etag.gsub(/^\"|\"$/, "")
        if_none_match_etags.include?(etag)
      end
    end

The thing is, Rails generates a tag *without* the "-gzip" suffix. Apache, before sending it to the client, appends that suffix, so the client sends it to the server in later requests. Rails compares tags before Apache has appended the suffix, so it compares it's own suffix-less etag with the suffixed Apache etag, and fails, even though they're semantically the same.

So it's not that

>env[HTTP_IF_NONE_MATCH] can be different from the etag that etag_matches recieves

but instead that

>the etag Rails generates is different than the etag sent by Apache (and later received from the client), due to the "-gzip" suffix

**Comment by georgeclaghorn** [comment]
In this particular case, you can configure mod_deflate not to append the -gzip suffix with the [DeflateAlterETag](http://httpd.apache.org/docs/trunk/mod/mod_deflate.html#deflatealteretag) directive.

**Comment by ianks** [comment]
I think this issue presents the issue that we need a proper abstraction for creatings ETags, esp. Weakly Validated ETags. http://www.w3.org/Protocols/rfc2616/rfc2616-sec13.html#sec13.3.3

The way that it is done now is to assume that all ETags are to be strongly validated (i.e. byte-for-byte match). 

Typically, an ETag is casted as 'weak' by prepending "W/" to the start of the tag. So your tag would become `W/ca6b75a007da7a11d49de32d16a51809`. This is actually a feature supported by Rack. As of now, you will need some middleware to make this happen. 

Supporting weak ETags seems like it can be quite the challenge, because the idea of 'semantically equivalent` is highly subjective. For example, if your implementation, any substring will be considered valid although it does not truly match the hash.

**Comment by ruipgpinheiro** [comment]
@georgeclaghorn Thanks, that works. The only problem is that Apache appends -gzip to it for a reason (so that proxies can cache a gzipped and non-gzipped version depending on if the client supports it or not), but that doesn't affect me as the things that matter for me are all set to private and won't be cached anyway

@ianks I know my implementation isn't correct, but I wanted a quick fix, and seeing as rails uses MD5 hashes and it's impossible for an MD5 hash to be inside a different MD5 (as MD5 hashes always have the same length), that shouldn't happen. But of course, there's much better ways to do it.
