### ISSUE TITLE
Pattern to translate model enum

### ISSUE THREAD

**Issue by dhyegofernando** [rails/rails#19059]
I have been looking for a good pattern to follow when I want to translate model enum but I have not found  anything.

Check out this code:
```ruby
# models/model.rb
class Model < ActiveRecord::Base
  enum status: [:accepted, :rejected]
end

# locales/en.yml
en:
  activerecord:
    attributes:
      model:
        status:
          accepted: In
          rejected: Out
```

Since enum values are not attributes, **we can not get the translation juts like another attribute**:
```ruby
Model.human_attribute_name("status.accepted")
```

Is there any built-in way?

**Comment by rafaelfranca** [comment]
Please use the mailing list or StackOverflow for questions/help, where a wider community will be able to help you. We reserve the issues tracker for issues only.

**Comment by dhyegofernando** [comment]
Ok, my bad. Thanks.
