### ISSUE TITLE
Regression - Non-Partial Reads For Optimistic Locking Ignores #attributes_for_update

### ISSUE THREAD

**Issue by metaskills** [rails/rails#19057]
While testing the SQL Server adapter for 4.2.1.rc1, I noticed that the `test_partial_update_with_optimistic_locking` test was failing for us. SQL Server does not allow identity columns in updates so we override [attributes_for_update](https://github.com/rails-sqlserver/activerecord-sqlserver-adapter/blob/master/lib/active_record/connection_adapters/sqlserver/core_ext/attribute_methods.rb) to remove identity columns. This works for that test in 4.2.0, but not after this change (https://github.com/rails/rails/commit/cb277485f9d78f3661c7103e7b468812cc283223) done for issue #18385.

With that commit, optimistic locking does not seem to use the proper active record/model attribute chain. Would really like some opinions from @sgrif and @rafaelfranca Thanks!

**Comment by sgrif** [comment]
So this should have been called with `keys_for_partial_write`. Is there a case where the identity column would end up in here where the user didn't explicitly change it? Doesn't it make more sense to error loudly than silently swallow it?

**Comment by metaskills** [comment]
Just changed the title of this issue to "Updates With Optimistic Locking Ignores #attributes_for_update" since it does not seem to be related to setting partial writes to false.

> So this should have been called with `keys_for_partial_write`.

If I put a `binding.pry` in the `test_partial_update_with_optimistic_locking` method and call `person.save!` twice without setting the partial write to false, I can see that `keys_for_partial_write` is called and I get expected dirty behavior. However, once `Person.partial_writes = false` is set, I can easily see that `keys_for_partial_write` or anything below like my `attributes_for_update` is not called. Maybe this method should go back to using `arel_attributes_with_values_for_update`?

> Is there a case where the identity column would end up in here where the user didn't explicitly change it?

Oh yea, twice. Here is the SQL from my end when `Person.partial_writes = false` for both `person.save!` results. See how it has all attributes twice? SQL Server can cope with the identity insert, but not the update.

```
SQL (2.8ms)  EXEC sp_executesql N'INSERT INTO [people] ([first_name], [primary_contact_id], [gender], [number1_fan_id], [lock_version], [comments], [followers_count], [friends_too_count], [best_friend_id], [best_friend_of_id], [insures], [born_at], [created_at], [updated_at]) OUTPUT INSERTED.[id] VALUES (@0, @1, @2, @3, @4, @5, @6, @7, @8, @9, @10, @11, @12, @13)', N'@0 nvarchar(4000), @1 int, @2 nvarchar(1), @3 int, @4 int, @5 nvarchar(4000), @6 int, @7 int, @8 int, @9 int, @10 int, @11 datetime, @12 datetime, @13 datetime', @0 = N'foo', @1 = NULL, @2 = NULL, @3 = NULL, @4 = 0, @5 = NULL, @6 = 0, @7 = 0, @8 = NULL, @9 = NULL, @10 = 0, @11 = NULL, @12 = '02-24-2015 13:20:14.26', @13 = '02-24-2015 13:20:14.26'  [["first_name", "foo"], ["primary_contact_id", nil], ["gender", nil], ["number1_fan_id", nil], ["lock_version", 0], ["comments", nil], ["followers_count", 0], ["friends_too_count", 0], ["best_friend_id", nil], ["best_friend_of_id", nil], ["insures", 0], ["born_at", nil], ["created_at", 2015-02-24 13:20:14 UTC], ["updated_at", 2015-02-24 13:20:14 UTC]]

SQL (1.5ms)  EXEC sp_executesql N'UPDATE [people] SET [people].[first_name] = N''foo'', [people].[id] = 4, [people].[primary_contact_id] = NULL, [people].[gender] = NULL, [people].[number1_fan_id] = NULL, [people].[lock_version] = 1, [people].[comments] = NULL, [people].[followers_count] = 0, [people].[friends_too_count] = 0, [people].[best_friend_id] = NULL, [people].[best_friend_of_id] = NULL, [people].[insures] = 0, [people].[born_at] = NULL, [people].[created_at] = ''02-24-2015 13:20:14.26'', [people].[updated_at] = ''02-24-2015 13:20:37.623'' WHERE [people].[id] = @0 AND [people].[lock_version] = @1; SELECT @@ROWCOUNT AS AffectedRows', N'@0 int, @1 int', @0 = 4, @1 = 0  [["id", 4], ["lock_version", 0]]
TinyTds::Error: Cannot update identity column 'id'
```

**Comment by sgrif** [comment]
Gotcha. Makes sense. I'll fix it today.

**Comment by sgrif** [comment]
Fixed in https://github.com/rails/rails/commit/bc211ea607fddd2b7a6eeee28870f8057adb9328

**Comment by metaskills** [comment]
Thanks, we are all green now.
