### ISSUE TITLE
Rails.cache.fetch in before_filter triggers infinite loop in Marshal::load_with_autoloading

### ISSUE THREAD

**Issue by alediaferia** [rails/rails#19067]
`Rails 4.2`

I'm trying to unmarshal an ActiveRecord model instance in a before_filter but this trigger an infinite loop in `active_support/core_ext/marshal.rb`.

The code looks like this:

    @my_var = Rails.cache.fetch('mykey', expires_in: 120.minutes) do
        MyModel.last(3)
    end

In particular the exception message is: **"undefined class/module ActiveRecord::ConnectionAdapters::Mysql2Adapter::Column"**.

I see there's a special case handling for this kind of exception where you try to autoload the required module and `retry`. Unfortunately, in my case, for some reason the autoload doesn't work and the retry triggers the same exception in an infinite loop.

Any hint?

**Comment by rafaelfranca** [comment]
Could you create an reproduction script with this template https://github.com/rails/rails/blob/master/guides/bug_report_templates/active_record_master.rb?

**Comment by alediaferia** [comment]
I tried creating a new Rails app with the same before_filter that causes the deadlock but don't manage to reproduce the issue. Any hint on what to check on my app?

**Comment by alediaferia** [comment]
I've updated the original post in order to clarify how I perform the fetch.

**Comment by alediaferia** [comment]
I can confirm reverting back to Rails 4.1.9 fixes the issue.

**Comment by daqing** [comment]
I have the same issue today, and after I clear the local cache using `rake tmp:clear`, the infinite loop disappears.

**Comment by daqing** [comment]
@alediaferia I guess this problem is related to corrupted/outdated cache.

**Comment by alediaferia** [comment]
@daqing I'll definitely try again ASAP with your suggestion and report here. Thank you.

**Comment by alediaferia** [comment]
It looks like the issue is gone. I'll be testing more and then close this issue.

**Comment by alediaferia** [comment]
No more issues with it. `rake tmp:clear` definitely helped.
