### ISSUE TITLE
Relative vs absolute table names for namespaced models 

### ISSUE THREAD

**Issue by raouldevil** [rails/rails#19071]
On Rails 4.1.9 and 4.2.0, when I generate a namespaced model with the following line:

`rails g model A::B::C::D::E name:string`

It generates the following directory structure
```
models/
  a/
    b/
      c/
        d/
          d.rb
          e/
            e.rb
```

`d.rb` seems to enable activerecord to find the correct table when working with the model A::B::C::D::E using `table_name_prefix` as follows:

```
module A::B::C::D
  def self.table_name_prefix
    'a_b_c_d_'
  end
end
```

However, we can eliminate the need for this module entirely and keep the directory structure clean by simply adding this line to `e.rb`: `self.table_name = :a_b_c_d_es`. So my question is this: For namespaced models, can a model not explicitly (by adding this line automatically to each generated model) or implicitly (somewhere in ActiveRecord::Base) always refer to the absolute and not the relative table name?

I am happy to try and solve this if the appetite is there.

**Comment by rafaelfranca** [comment]
Thank you so much for the issue but we don't take feature request on the issue tracker. We recommend you to try to implement the feature and send us a pull request or if you are in doubt if the feature will be accepts ask in Rails Core mailing list for feedback.

**Comment by raouldevil** [comment]
Apologies, that's what I thought (I'm new here) but then I saw a few issues which could be interpreted as feature requests. Thanks for the feedback.
