### ISSUE TITLE
Has-many-through fails to create join model when used with scope

### ISSUE THREAD

**Issue by RKushnir** [rails/rails#19073]
I have the following models
```ruby
class User < ActiveRecord::Base
  has_many :likes, dependent: :destroy
  has_many :liked_collections, through: :likes, source: :liked, source_type: 'Collection'
end

class Like < ActiveRecord::Base
  belongs_to :user
  belongs_to :liked, polymorphic: true, counter_cache: true
end

class Collection < ActiveRecord::Base
  scope :with_public_access, -> { where(private: false) }
end
```
Now, `user.liked_collections.create!` works.
And `user.liked_collections.with_public_access.create!` creates the `collection`, but fails to create a `like` to link it to the `user`.

UPD. Gist to reproduce https://gist.github.com/RKushnir/57d0064541da39f9b8e4

**Comment by rafaelfranca** [comment]
Could you create an reproduction script with this template https://github.com/rails/rails/blob/master/guides/bug_report_templates/active_record_master.rb?

**Comment by RKushnir** [comment]
@rafaelfranca of course, here you are https://gist.github.com/RKushnir/57d0064541da39f9b8e4
I simplified it a bit and removed the details the appeared to be irrelevant.
