### ISSUE TITLE
Include module in engine's application contorller causes circular dependency error

### ISSUE THREAD

**Issue by emclab** [rails/rails#19079]
in_quotex is a Rails 4.2.0 engine. In its application controller, there includes:

  module InQuotex
    class ApplicationController < ::ApplicationController
      include BizWorkflowx::WfHelper
     .....
  end

When loading the WfHelper module, there is an error if we run InQuotex::QuotexController.public_instance_methods:

  InQuotex::QuotesController.public_instance_methods(false) = {RuntimeError}Circular dependency   detected while autoloading constant InQuotex::QuotesController

The error above disappears (return empty array) if the include is moved into quotes controller from engine's application controller. The same code does not cause any error in Rails 3.2.12.

**Comment by emclab** [comment]
BTW none of the methods defined in WfHelper was there for quotes controller. I am wondering if it has something to do with this circular dependency error.

**Comment by kaspth** [comment]
Let's test this a bit.

Can you try defining your engines' application controller as `class InQuotex::ApplicationController < ApplicationController` and report back?

Likewise fully qualifying the include as `include ::BizWorkflowx::WfHelper`.

**Comment by emclab** [comment]
1. Define in engine's application controller as: class InQuotex::ApplicationController < ApplicationController
   Same error.
And 2. fully qualifying the include as include ::BizWorkflowx::WfHelper
   same error.

**Comment by emclab** [comment]
Here is a post I put on stackoverflow.com about the issue:

http://stackoverflow.com/questions/28728910/methods-included-not-found-after-upgrading-to-rails-4

**Comment by kaspth** [comment]
Can you reproduce the error in a sample application?

**Comment by emclab** [comment]
I can try later.  I am working on engine upgrading to rails 4.2.0 with an issue I am trying to solve for last a few days.
