### ISSUE TITLE
migrations: t.references doesn't allow index name to be specified

### ISSUE THREAD

**Issue by drewda** [rails/rails#19078]
I have the following in a migration:

````ruby
create_table :model_with_a_long_name do |t|
  t.references :other_model_with_an_equally_long_name, index: true
end
````

That produces an index with too long of a name for Postgres.

Is there a way to manually specify the index name (without adding the integer column and the index separately)?

Something like the following:
````ruby
create_table :model_with_a_long_name do |t|
  t.references :other_model_with_an_equally_long_name, index: true, index_name: 'model_and_other'
end
````
?

**Comment by rafaelfranca** [comment]
Please use the mailing list or StackOverflow for questions/help, where a wider community will be able to help you. We reserve the issues tracker for issues only.

**Comment by drewda** [comment]
Thanks, will do.
