### ISSUE TITLE
Rails 4.2.0 action pack: self.class.action_methods not showing method included in application controller 

### ISSUE THREAD

**Issue by emclab** [rails/rails#19103]
In application controller of Rails 4.2.0 engine in_quotex, there is:

  include BizWorkflowx::WfHelper

wf_helper loads several methods dynamically during the execution. It is like this:

  module BizWorkflowx
    module WfHelper
      def self.included(base)
        base.before_action :load_wf_action_def
      end
      protected
      def load_wf_action_def
        #load methods with eval()
      end
   end
  end

With this setup, when calling action submit which is defined in WfHelper in quotes controller, there is an error:

  AbstractController::ActionNotFound:
         The action 'submit' could not be found for InQuotex::QuotesController

I find in base.rb in action pack, self.class.action_names.include?(:submit) returns false which causes ActionNotFound error. However self.methods.include?(:submit) returns true.

Is action pack 4.2.0 supposed to behave like that? I confirm that in rails 3.2.12, self.class.action_methods does include method submit and other methods in module wf_helper.

**Comment by pixeltrix** [comment]
@emclab are you defining the `submit` action inside the `load_wf_action_def` method? If so it's possible that an internal change of behaviour has triggered the caching of the action methods in later versions of Rails before the filter is called. If you're dynamically adding action methods you need to ensure that you clear the cache by using [`clear_action_methods!`][1].

Closing for now - if this doesn't solve your problem please let me know and I'll re-open and take another look.

[1]: http://api.rubyonrails.org/classes/AbstractController/Base.html#method-c-clear_action_methods-21
