### ISSUE TITLE
Bug in inflections

### ISSUE THREAD

**Issue by troelskn** [rails/rails#19109]
In the method `ActiveSupport:: Inflector#apply_inflections`, the current locale is not respected - it just assumes the default on `:en`. This means that `uncountable` rules aren't observed for other languages than English.

**Comment by JuanitoFatas** [comment]
Can add a label for `attached PR`, right?

**Comment by rafaelfranca** [comment]
The default is `:en` and unfortunately we can't change because it will break Active Record since we use inflection rules to infer tables and columns. That said you need to be explicit about the locale if you want to use something different than `:en`.

Thank you for reporting.

**Comment by EilisHamilton** [comment]
The original pull request didn't actually solve this issue, so I have made one which does.
