### ISSUE TITLE
installer problem for Rails

### ISSUE THREAD

**Issue by antonrr90** [rails/rails#19115]
Any one having this:

D:\Ruby21-x64>gem install rails
ERROR:  Could not find a valid gem 'rails' (>= 0), here is why:
          Unable to download data from https://rubygems.org/ - SSL_connect retur
ned=1 errno=0 state=SSLv3 read server certificate B: certificate verify failed (
https://api.rubygems.org/latest_specs.4.8.gz)

D:\Ruby21-x64>

and I know it something on your end, as my firewall is open for this app. Did someone forget to renew the server certificate?

**Comment by rafaelfranca** [comment]
Please use the mailing list or StackOverflow for questions/help, where a wider community will be able to help you. We reserve the issues tracker for issues only.

**Comment by antonrr90** [comment]
So, let me get this straight. RubyOnRails.org sends me here to report bugs, and your sending me elsewhere. If that is the case, why is there not another link on the RubyOnRails.org website for installer problems. Common Sense would have all the links available on the RubyOnRails.org website, would it not?
