### ISSUE TITLE
bug in form helpers

### ISSUE THREAD

**Issue by lifeiscontent** [rails/rails#19117]
when you do something like

``` erb
<%= f.label :attribute %>
```

it will render out the value inside of the label

however when you do this with a do block there's no way to get the contents of the label back.

new api proposal:

``` erb
<%= f.label :attribute do | label_text | %>
  <%= f.radio_button :attribute, true %>
  <%= label_text %>
<% end %>
```

I think we should take some time and think about what we're leaving out of the rails form helpers and expose them as parameters in the do blocks.

what do you guys think?

**Comment by rafaelfranca** [comment]
Thank you so much for the issue but we don't take feature request on the issue tracker. We recommend you to try to implement the feature and send us a pull request or if you are in doubt if the feature will be accepts ask in Rails Core mailing list for feedback.

**Comment by rafaelfranca** [comment]
BTW this is already possible.

```erb
<%= f.label :attribute do |label_builder| %>
  <%= f.radio_button :attribute, true %>
  <%= label_builder.translation %>
<% end %>
```

**Comment by lifeiscontent** [comment]
@rafaelfranca which version of rails is this available in?

**Comment by rafaelfranca** [comment]
4.2.0

**Comment by lifeiscontent** [comment]
@rafaelfranca thank you very much! :+1:
