### ISSUE TITLE
Webrick block app start in production

### ISSUE THREAD

**Issue by goodniceweb** [rails/rails#19127]
Hello

I have long story for its bug. So please, sit back and relax :)

I have Rails 4.1.8 app([Gemfile.lock](http://pastie.org/private/6ydx2qvvb7znrsjdkqmt4w)). One day I want to deploy it in production. Used `capistrano (3.3.5)` for it.
On server I used Apache2 + Passenger (4.0.59). Install of apache module was fine as usual.
But on visit web it raise `stdin is not a tty` passenger error. I looked into [few](https://code.google.com/p/phusion-passenger/issues/detail?id=891) [places](https://code.google.com/p/phusion-passenger/issues/detail?id=891) [for](https://code.google.com/p/phusion-passenger/issues/detail?id=914) [figure out](https://github.com/phusion/passenger/issues/1129) problem but have not success. 
Then I remove apache + passenger and install nginx + unicorn. It also not worked for me. Any useful info in logs - only "500 error", "smth. went wrong". I felt that something magical going on and disable capistrano recipies. I run it by hand like a daemon. In retrospect I see its mistake.
Next time I tried to use `thin` instead of `unicorn` but it not worked too. With `puma` also have not result. 
Then I tried to run server manually from console and gotcha: puma was blocked by webrick with some custom settings. Here is output:

```bash
$ RAILS_ENV=production bundle exec rails s      
=> Booting Puma
=> Rails 4.1.8 application starting in production on http://0.0.0.0:3000
=> Run `rails server -h` for more startup options
=> Notice: server is listening on all interfaces (0.0.0.0). Consider using 127.0.0.1 (--binding option)
=> Ctrl-C to shutdown server
[2015-02-28 06:32:46] INFO  WEBrick 1.3.1
[2015-02-28 06:32:46] INFO  ruby 2.1.5 (2014-11-13) [i686-linux]
[2015-02-28 06:32:46] INFO  WEBrick::HTTPServer#start: pid=19659 port=2010
^C[2015-02-28 06:32:54] INFO  going to shutdown ...
[2015-02-28 06:32:54] INFO  WEBrick::HTTPServer#start done.
Puma 2.11.1 starting...
* Min threads: 0, max threads: 16
* Environment: production
* Listening on tcp://0.0.0.0:3000
```

Above you can see: puma tried to initialize, reach line `=> Ctrl-C to shutdown server`, than webrick interrupt her flow, initialize and block it. 
When I shut down webrick by `^C`. puma continue to initialize and everything work fine.

I tried to search in whole rails repo, in whole source of my app and no found smth. for initialize webrick in production with such strange custom behaviour: always `pid=19659 port=2010`, always block any server you use: passenger, unicorn, thin, puma, and... webrick o_0. Here is output:
```bash
$ RAILS_ENV=production bundle exec rails s webrick
=> Booting WEBrick
=> Rails 4.1.8 application starting in production on http://0.0.0.0:3000
=> Run `rails server -h` for more startup options
=> Notice: server is listening on all interfaces (0.0.0.0). Consider using 127.0.0.1 (--binding option)
=> Ctrl-C to shutdown server
[2015-02-28 06:35:31] INFO  WEBrick 1.3.1
[2015-02-28 06:35:31] INFO  ruby 2.1.5 (2014-11-13) [i686-linux]
[2015-02-28 06:35:31] INFO  WEBrick::HTTPServer#start: pid=19698 port=2010
^C[2015-02-28 06:35:43] INFO  going to shutdown ...
[2015-02-28 06:35:43] INFO  WEBrick::HTTPServer#start done.
[2015-02-28 06:35:43] INFO  WEBrick 1.3.1
[2015-02-28 06:35:43] INFO  ruby 2.1.5 (2014-11-13) [i686-linux]
[2015-02-28 06:35:43] INFO  WEBrick::HTTPServer#start: pid=19698 port=3000
```

I tried to upgrade my rails app to 4.1.9 - same result. Then - to 4.2.0 and it also not work. Have no idea why it occur.

Finally, I tried to run it in development mode and everything was fine for it. So here my [application.rb](http://pastie.org/private/8v06gjo10qikltm8htppea), [production.rb](http://pastie.org/private/zy4andykmidmcrz2gxw42a) and [development.rb](http://pastie.org/private/alhx3hw8odtq0tvwzru7zw). 

Can anybody explain what is going on here?

**Comment by rafaelfranca** [comment]
I guess it is some gem injecting code to start the server. As you can see it uses a port that is not the default of Rails (`2010`). I'd start to look at the gems you included in the project.

Closing since this doesn't seems to be a Rails bug.

**Comment by goodniceweb** [comment]
I used [Kernel#set_trace_func](http://ruby-doc.org//core-2.2.0/Kernel.html#method-i-set_trace_func) to figure out which line of code broked everything and gotcha: it was `syntaxhighlighter_3.0.83/tests/webrick.rb` from tinymce custom stack. 
Thank you so much for prompted me to check every dependency one more time.
