### ISSUE TITLE
ActiveRecord: select breaks count

### ISSUE THREAD

**Issue by Zyphrax** [rails/rails#19146]
When you combine `.select` with `.count` ActiveRecord will generate a T-SQL statement that does a count on multiple columns, which is not allowed.

I know that the combination of a select and count doesn't really make sense, but I've inherited some code with `default_scope` statements that filter out columns that contain a lot of base64 data. 

My statement:
```ruby
Order.select(:id, :quantity).count
```

Result:
```sql
SELECT COUNT(id, quantity) FROM "orders"
PG::UndefinedFunction: ERROR:  function count(integer, integer) does not exist
LINE 1: SELECT COUNT(id, quantity) FROM "orders"
               ^
HINT:  No function matches the given name and argument types. You might need to add explicit type casts.
: SELECT COUNT(id, quantity) FROM "orders"
ActiveRecord::StatementInvalid: PG::UndefinedFunction: ERROR:  function count(integer, integer) does not exist
LINE 1: SELECT COUNT(id, quantity) FROM "orders"
```

Ruby 2.2 - Rails version 4.2.1 RC2 - Database: Postgres 9.4.1

**Comment by kaspth** [comment]
I believe the `unscoped` method is what you want :smile:

**Comment by cristianbica** [comment]
Kasper when I call count on an ActiveRecord scope I'm expecting to get the
number of records that the scope returns even if I the scope has a custom
select. We should either fix this or document on the count method that if
you do custom selects you should unscope select before calling count.

**Comment by cristianbica** [comment]
Nevermind it's documented
http://api.rubyonrails.org/classes/ActiveRecord/Calculations.html#method-i-count
:)

**Comment by Zyphrax** [comment]
I've inherited this project and I decided that the first order of business is to upgrade it from Rails 3.2.18 / Ruby 1.8.7. World of pain (sigh...).

Of course I know about the `unscoped` method :stuck_out_tongue:

The default_scope `select` was used to filter out some (data heavy) columns, but it doesn't seem like the proper solution for the problem. Drizzling `unscoped` all over the code, doesn't sound a lot better. Do you guys have a suggestion for filtering out the columns (without moving the columns to other tables)?

Also, wouldn't it make sense to fallback to `COUNT(*)` if the number of columns in the select is more than one? Or would that cover up potential bugs.

**Comment by rafaelfranca** [comment]
What you want is count(:all). count without the :all argument will respect
the select clause.

**Comment by mraj-rpx** [comment]
Hi Guys, I am also getting the same issue with count when the result has select scope with multiple columns, 

below is the actual error,

From: /home/mohanrajr/.rbenv/versions/2.2.2/gemsets/pacer_data_service/gems/activerecord-4.2.0/lib/active_record/relation/calculations.rb @ line 267 ActiveRecord::Calculations#execute_simple_calculation:

    262: 
    263:         query_builder = relation.arel
    264:         bind_values = query_builder.bind_values + relation.bind_values
    265:       end
    266: 
    267:       result = @klass.connection.select_all(query_builder, nil, bind_values)
    268:       row    = result.first
    269:       value  = row && row.values.first
    270:       column = result.column_types.fetch(column_alias) do
    271:         type_for(column_name)
    272:       end

[1] pry(#<Product::ActiveRecord_AssociationRelation>)> query_builder.to_sql
=> "SELECT COUNT(products.id, products.date_filed, products.entered, products.entry_markup, products.row_num, products.doc_num, products.category, products.event) FROM \"products\" WHERE \"products\".\"docket_info_id\" = $1"
[2] pry(#<Product::ActiveRecord_AssociationRelation>)> 


     Failure/Error: expect(docket_row_details.count).to eq(docket_info.products.count)
     ActiveRecord::StatementInvalid:
       PG::InFailedSqlTransaction: ERROR:  current transaction is aborted, commands ignored until end of transaction block
       : SELECT COUNT(products.id, products.date_filed, products.entered, products.entry_markup, products.row_num, products.doc_num, products.category, products.event) FROM "products" WHERE "products"."docket_info_id" = $1

I tried it with rails 4.2.1 getting the same issue.
Please suggest me a way? Thanks.
