### ISSUE TITLE
http://guides.rubyonrails.org/caching_with_rails.html

### ISSUE THREAD

**Issue by rahuldess** [rails/rails#19154]
Why isn't this "caching_with_rails.html" path not given in  link in Guides Index of "guides.rubyonrails.org" ?

**Comment by senny** [comment]
@rahuldess because the guide has not been published yet. It's still in the "draft" form. That's why we don't link to it on the public site.

**Comment by djpowers** [comment]
I came across the "Caching with Rails" guide and had the same question.

Out of curiosity, is there a distinction between this guide being in "draft" form, and other guides listed on the index with the "Work in progress" banner?

It seems that it would be helpful to have this and others listed on the root page to help with discoverability, even if they are not in a completed state.

**Comment by FlowerWrong** [comment]
+1

**Comment by senny** [comment]
Work in progress guides have been reviewed by a member of the documentation team. The contained information is accurate and the wording fits our guidelines. A "draft" is basically just a document that someone started working on. They are in the same directory to make it easier to collaborate but often times it's a single person who started working on a new guide and hasn't had the time to finish it yet. Getting the guides in state that we feel comfortable publishing on the official guides website usually takes some refining (see #21052 in the case of the caching guide).

Hope that helps.

**Comment by djpowers** [comment]
Thanks for the explanation! Good timing with the example, as it was merged in shortly after you commented. :+1:
