### ISSUE TITLE
tzinfo-data warning on boot if not present in Gemfile

### ISSUE THREAD

**Issue by sivsushruth** [rails/rails#19175]
Developers all the time clone rails apps and usually they do not have the tzinfo-data gem(since they were being developed on a non-windows machine).
I think it would be better if rails gave a gentle reminder on boot, if it sees that the app is on a windows machine now and it does not have the tzinfo-data gem.
Is this something that seems beneficial to rails guys on windows ?

**Comment by rafaelfranca** [comment]
If we can, I think it is fine to do this.
