### ISSUE TITLE
Support for :add_index with json-columns/attributes? [PostgreSQL]

### ISSUE THREAD

**Issue by johvet** [rails/rails#19179]
Are there any intentions on adding support for json-columns/attributes to :add_index ?
Currently a column name give in an add-index inside a migration must be an existing column name, but what if I want to do something like this:
```
CREATE UNIQUE INDEX ix_geography_geoname_id ON classifications ((metadata->>'geoname_id')) WITH (FILLFACTOR = 100) WHERE type = 'Geography'
```
Of course, there's also no support for the fill-factor, but even "(metadata->>'geoname_id')" is not acceptable, as it's not in #column_names. 

Maybe #quoted_column_names in schema_statements.rb could check if a column-name is a string and if it's wrapped with parenthesis (so it looks like an expression) it could pass it through.

Any thoughts in that direction?

**Comment by matthewd** [comment]
xref #19090

**Comment by senny** [comment]
Hey @johvet 

We use GitHub exclusively to track issues and discuss patches. I'm going to close this issue as it's a feature request. You can find more details in our [contribution guidelines](https://github.com/rails/rails/blob/master/CONTRIBUTING.md). Feature suggestions can be sent to the [rails-core mailing list](https://groups.google.com/forum/?fromgroups#!forum/rubyonrails-core).

Thank you for your understanding :yellow_heart:
