### ISSUE TITLE
ActiveJob batching

### ISSUE THREAD

**Issue by kostya** [rails/rails#19182]
would be nice to have such api for grouping events, to minimize sql requests for example

```ruby
class MyJob < ActiveJob::Base
  batch_size 100
  def perform(ids)
    User.where(:id => ids).update_all "status = 0"
  end
end

MyJob.perform_later id1
MyJob.perform_later id2
MyJob.perform_later id3
...
```

or batch condition:
```ruby
class MyJob < ActiveJob::Base
  batch_by { |id|  id / 100 }
  def perform(ids)
    User.where(:id => ids).update_all "status = 0"
  end
end

MyJob.perform_later id1
MyJob.perform_later id2
MyJob.perform_later id3
...
```

this should be easy to implement, just collect events in memory, and call perform on condition, and if batch raised, just raise all events. If it trap a signal, resend all in memory events.

**Comment by egilburg** [comment]
If this is implemented, `:batch_size` should be an argument passed from outisde, just like `find_in_batches` is called by consumer rather than receiver Active Record. (but if you want, can support `default_batch_size`/`default_batch_by` on the Job.

**Comment by senny** [comment]
We don't use the GitHub tracker for feature requests. Please post to the [rails-core](https://groups.google.com/forum/?fromgroups#!forum/rubyonrails-core) mailing list. You can find more details in our [contribution guidelines](https://github.com/rails/rails/blob/master/CONTRIBUTING.md).

@kostya thank you for your suggestion.
