### ISSUE TITLE
Using joins on polymorphic association fails, but manual join works fine

### ISSUE THREAD

**Issue by lserman** [rails/rails#19183]
Is there a reason why `joins` on a polymorphic association does not work as expected? Or maybe I am doing something wrong?

```ruby
class User
  has_many :devices, class_name: 'Pushable::Device', as: :pushable
end
```

```ruby
module Pushable
  class Device < ActiveRecord::Base
    belongs_to :pushable, polymorphic: true
  end
end
```

I want to find all devices owned by a User ActiveRecord::Relation, for example: `Pushable::Device.owned_by(User.where(push: true))`.

**Fails** (`Cannot eagerly load the polymorphic association :pushable`):

```ruby
def self.owned_by(pushable)
  joins(:pushable).merge(pushable)
end
```

**Succeeds**:

```ruby
def self.owned_by(pushable)
  klass = pushable.klass.name
  table = pushable.table.name
  joins("JOIN #{table} ON #{table}.id = pushable_devices.pushable_id").
    where(pushable_type: klass).
    merge(pushable).
    uniq
end
```

If there is another way I can do this that would be awesome... but I can't find out how. I expected the first method to work but couldn't get around the `ActiveRecord::EagerLoadPolymorphicError`.

**Comment by rafaelfranca** [comment]
Please use the mailing list or StackOverflow for questions/help, where a wider community will be able to help you. We reserve the issues tracker for issues only.

**Comment by lserman** [comment]
Is this not an issue? Shouldn't the failing method return the same SQL as the succeeding method (aside from `uniq`)?

**Comment by rosskevin** [comment]
I'm with @lserman on this one, this seems to be an issue, not a question.

**Comment by Dschee** [comment]
I agree, too:
This is clearly an issue if Rails wants to support polymorphic associations the way one would expect.

**Comment by uhrohraggy** [comment]
Bump. This needs a resolution or documentation and is still an issue.
