### ISSUE TITLE
Rails 4.1.1 will not update

### ISSUE THREAD

**Issue by rlanagan** [rails/rails#19188]
My computer will not recognize any version of Rails beyond 4.1.1 no matter what, and as of the last week has refused to run any rake commands due to a "circular argument reference error" referencing an unknown gem. Here's the error that runs after any rake command:

    $ rake db:seed
    /Users/rachel/.rvm/gems/ruby-2.2.0@rails4.2/gems/activesupport-4.1.1/lib/active_support/values/time_zone.rb:285: warning: circular argument reference - now
    rake aborted!
    ActiveRecord::UnknownAttributeError: unknown attribute: description

After researching, it seemed that the best way to fix this was to upgrade Rails to the most recent version. I created a new rvm for this purpose, ran bundle install and noticed that Rails installed as version 4.1.1. I ran the following to install Rails 4.2.0:

    $ gem install rails -v 4.2.0
    Successfully installed rails-4.2.0
    Parsing documentation for rails-4.2.0
    Done installing documentation for rails after 1 seconds
    1 gem installed
    $ which rails
    /Users/rachel/.rvm/gems/ruby-2.2.0@rails4.2/bin/rails
    $ rails --version
    Rails 4.1.1

If I try uninstalling Rails 4.1.1 it will uninstall, but then the computer won't recognize the gem at all:

    $ gem uninstall rails -v 4.1.1
    Successfully uninstalled rails-4.1.1
    $ rails -v
    Could not find rails-4.1.1 in any of the sources
    Run `bundle install` to install missing gems. 

Installing 4.2.0 after this will say it worked successfully, but then a `rails --version` check will lead to the same "could not find rails-4.1.1" error, as will running a `gem update --system` command or any of its variants (`gem 'rails', '>= 4.2.0'`; `rails use 4.2.0`). Finally I ran a `gem install rails --pre` command since a new version was released yesterday - it installed rails4.2.1.rc3 successfully but then a version check immediately after returned "Rails 4.1.1".

Is there any way to fix this so that I can update Rails and (hopefully) solve the "circular argument reference" error as a result?

**Comment by rafaelfranca** [comment]
Please use the mailing list or StackOverflow for questions/help, where a wider community will be able to help you. We reserve the issues tracker for issues only.

**Comment by rlanagan** [comment]
Hi, thanks for your help although I was actually directed to post this issue here by someone on SO after I posted it there in detail, maybe they misunderstood the rules as well. Could you please point me to the mailing list so I can be sure to submit it correctly? Thank you!

**Comment by rafaelfranca** [comment]
You can use this mailing list https://groups.google.com/forum/#!forum/rubyonrails-talk.

I have a suspicion, it may be spring. Try to run `spring stop` after you uninstall rails.
