### ISSUE TITLE
ActiveRecord includes, order by bug

### ISSUE THREAD

**Issue by annethereshewent** [rails/rails#19192]
I have the following query that retrieves a user's posts as well as post tags. However, if I try to pass an order clause to it, it returns less than the amount specified by limit. Here is my query:

		@posts = @user.posts.order('posts.id desc').includes(:tags).order('post_tags.created_at').includes(:images).paginate(page: params[:page], per_page: 15)

That returns 7 posts instead of the 15 specified. If I remove the order, it returns 15 posts but the tags are out of order. 

Here is the query generated by that association:

 SQL (0.5ms)  SELECT  DISTINCT "posts"."id", posts.id AS alias_0, post_tags.created_at AS alias_1 FROM "posts" LEFT OUTER JOIN "post_tags" ON "post_tags"."post_id" = "posts"."id" LEFT OUTER JOIN "tags" ON "tags"."id" = "post_tags"."tag_id" LEFT OUTER JOIN "images" ON "images"."post_id" = "posts"."id" WHERE "posts"."user_id" = $1  ORDER BY posts.id desc, post_tags.created_at LIMIT 15 OFFSET 0  [["user_id", 1]]

SQL (0.6ms)  SELECT "posts"."id" AS t0_r0, "posts"."post" AS t0_r1, "posts"."edited" AS t0_r2, "posts"."num_comments" AS t0_r3, "posts"."user_id" AS t0_r4, "posts"."created_at" AS t0_r5, "posts"."updated_at" AS t0_r6, "posts"."tags" AS t0_r7, "tags"."id" AS t1_r0, "tags"."tag_name" AS t1_r1, "tags"."created_at" AS t1_r2, "tags"."updated_at" AS t1_r3, "images"."id" AS t2_r0, "images"."post_id" AS t2_r1, "images"."created_at" AS t2_r2, "images"."updated_at" AS t2_r3, "images"."file_file_name" AS t2_r4, "images"."file_content_type" AS t2_r5, "images"."file_file_size" AS t2_r6, "images"."file_updated_at" AS t2_r7 FROM "posts" LEFT OUTER JOIN "post_tags" ON "post_tags"."post_id" = "posts"."id" LEFT OUTER JOIN "tags" ON "tags"."id" = "post_tags"."tag_id" LEFT OUTER JOIN "images" ON "images"."post_id" = "posts"."id" WHERE "posts"."user_id" = $1 AND **"posts"."id" IN (208, 208, 208, 205, 205, 205, 205, 205, 203, 203, 203, 202, 196, 193, 182)** ORDER BY posts.id desc, post_tags.created_at  [["user_id", 1]]

For some reason it's repeating the post IDs several times, which results in less posts. Also, if I remove the paginate gem and use a limit, it still returns 7 posts instead of the 15

**Comment by annethereshewent** [comment]
Also, if I remove the paginate gem and use a limit, it still returns 7 posts instead of the 15

**Comment by sgrif** [comment]
As per our contributing guide at http://guides.rubyonrails.org/contributing_to_ruby_on_rails.html, please provide a script we can use to reproduce your issue, using this template: https://github.com/rails/rails/blob/master/guides/bug_report_templates/active_record_master.rb

**Comment by annethereshewent** [comment]
unless File.exist?('Gemfile')
      File.write('Gemfile', <<-GEMFILE)
        source 'https://rubygems.org'
        gem 'rails', github: 'rails/rails'
        gem 'arel', github: 'rails/arel'
        gem 'sqlite3'
      GEMFILE

      system 'bundle'
    end

    require 'bundler'
    Bundler.setup(:default)

    require 'active_record'
    require 'minitest/autorun'
    require 'logger'

    # This connection will do for database-independent bug reports.
    ActiveRecord::Base.establish_connection(adapter: 'sqlite3', database: ':memory:')
    ActiveRecord::Base.logger = Logger.new(STDOUT)

    ActiveRecord::Schema.define do
      create_table :posts, force: true  do |t|
      end

      create_table :comments, force: true  do |t|
        t.integer :post_id
      end

      create_table :post_tags, force: true do |t|
        t.integer post_id
        t.integer tag_id
      end

      create_table :tags, force: true do |t|
        t.tag_name
      end

    end

    class Post < ActiveRecord::Base
      has_many :comments
      has_many :post_tags
      has_many :tags, through: :post_tags
    end

    class Comment < ActiveRecord::Base
      belongs_to :post
    end

    class PostTag < ActiveRecord::Base
      belongs_to :post
      belongs_to :tag
    end

    class Tag < ActiveRecord::Base
      has_many :post_tags
      has_many :posts, :through => :post_tags
    end


    class BugTest < Minitest::Test
      def test_association_stuff
    
        15.times do |i|
          posts << Post.create!
        end

        posts.each do |post| 
          post.tags.create!
        end
    

        post.comments << Comment.create!

        # here is the actual problem:

        @posts = Post.includes(:tags).order('post_tags.created_at').limit(15).count


        assert_equal 15, Post.order('posts.id desc').includes(:tags).order('post_tags.created_at').limit(15).count
        assert_equal 1, Comment.count
        assert_equal post.id, Comment.first.post.id
      end
    end

**Comment by pinglamb** [comment]
Updated reproduction scripts to make it able to run:

```RUBY
unless File.exist?('Gemfile')
  File.write('Gemfile', <<-GEMFILE)
    source 'https://rubygems.org'
    gem 'rails', github: 'rails/rails'
    gem 'arel', github: 'rails/arel'
    gem 'sqlite3'
  GEMFILE

  system 'bundle'
end

require 'bundler'
Bundler.setup(:default)

require 'active_record'
require 'minitest/autorun'
require 'logger'

# This connection will do for database-independent bug reports.
ActiveRecord::Base.establish_connection(adapter: 'sqlite3', database: ':memory:')
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :posts, force: true  do |t|
  end

  create_table :comments, force: true  do |t|
    t.integer :post_id
  end

  create_table :post_tags, force: true do |t|
    t.integer :post_id
    t.integer :tag_id
    t.datetime :created_at
  end

  create_table :tags, force: true do |t|
    t.string :tag_name
  end

end

class Post < ActiveRecord::Base
  has_many :comments
  has_many :post_tags
  has_many :tags, through: :post_tags
end

class Comment < ActiveRecord::Base
  belongs_to :post
end

class PostTag < ActiveRecord::Base
  belongs_to :post
  belongs_to :tag
end

class Tag < ActiveRecord::Base
  has_many :post_tags
  has_many :posts, :through => :post_tags
end


class BugTest < Minitest::Test
  def test_association_stuff
    posts = []

    15.times do |i|
      posts << Post.create!
    end

    posts.each do |post|
      post.tags.create!
    end

    post = posts.sample
    post.comments << Comment.create!

    assert_equal 15, Post.order('posts.id desc').includes(:tags).order('post_tags.created_at').limit(15).count
    assert_equal 1, Comment.count
    assert_equal post.id, Comment.first.post.id
  end
end
```

(Diff: https://gist.github.com/pinglamb/15c66f4bc8bc80bfc51f)

But the test passes as expected. Any changes I made altered the behaviour?

**Comment by annethereshewent** [comment]
Erm, the problem usually happens when posts have multiple tags. Can you change the line starting with "posts.each do |post|" to

    5.times do |i|
      3.times do |j|
        posts[i].tags.create!
      end
    end

That will make sure that 5 out of the 15 posts each have multiple tags, which should throw off the results. Let me know if you need anything else from me and I'll be glad to assist. Thank you!

**Comment by pinglamb** [comment]
Test still passes. Added this to ensure at least one post has multiple tags:

```RUBY
assert_equal 3, Post.first.tags.count
```

Do you think there are other gems in your project affecting the behaviour? Or default_scope?

**Comment by sgrif** [comment]
I'm going to close this. The original script doesn't run and every runnable script posted passes. This is probably a bug in your application. If you have a runnable, failing reproduction script please ping me and I'll reopen.
