### ISSUE TITLE
Custom scaffold erb templates not used when project name has underscore

### ISSUE THREAD

**Issue by derekmwright** [rails/rails#19200]
Steps to reproduce:
1. `rails new project_a`
2. `mkdir -p lib/templates/erb/scaffold`
3. `touch lib/templates/erb/scaffold/index.html.erb`
4. `rails generate scaffold test`
5. `cat app/views/tests/index.html.erb` (File should be empty but its using the default from the railties gem)

Works as expected when the reproduction steps are followed using a project name with no underscore (`rails new projecta`).

**Comment by frankyston** [comment]
could tell that this version using the rails and ruby?

**Comment by derekmwright** [comment]
Sorry! Here's the info:

$ ruby --version
ruby 2.1.5p273 (2014-11-13 revision 48405) [x86_64-linux]
$ rails --version                                                                                                                                                                           
Rails 4.2.0

**Comment by frankyston** [comment]
@derekmwright 

performed with the steps with:

```
Rails 4.2.0
ruby 2.1.5p273 (2014-11-13 revision 48405) [x86_64-darwin14.0]
```
and
```
Rails 4.2.0
ruby 2.2.0p0 (2014-12-25 revision 49005) [x86_64-darwin12.0]
```
and every two generated template with no problem.

**Comment by rafaelfranca** [comment]
Same here. I guess you need to stop spring after creating the template.

**Comment by derekmwright** [comment]
I haven't started the rails server at that point so spring shouldn't be causing an issue. I'll test a bit further and see if I can do some more debugging.
