### ISSUE TITLE
assert_generates doesn't take route constraints (with an object responding to matches?) into account

### ISSUE THREAD

**Issue by tbalthazar** [rails/rails#19208]
Hi,

The context here is that I'm playing with API versionning. 

I've defined 2 `users` resources in my route file, scoped in a v1 module and in a v2 module. The scopes use constraints (an object responding to `matches?`) to determine which version of the API should be used.

The [route file is here](https://github.com/tbalthazar/RailsRouteTestsProblem/blob/master/config/routes.rb), the [constraint object is here](https://github.com/tbalthazar/RailsRouteTestsProblem/blob/master/lib/api_version.rb). (The APIVersion class is silly here, but I've simplified it to the max).

I've created a [V1::UsersController](https://github.com/tbalthazar/RailsRouteTestsProblem/blob/master/app/controllers/v1/users_controller.rb) and a [V2::UsersController](https://github.com/tbalthazar/RailsRouteTestsProblem/blob/master/app/controllers/v2/users_controller.rb), and when I hit `http://localhost:3000/users`, I see `Hello Users v2` as expected, so I assume my routing is correct.

Now I want to test that when I hit `/users` the controller that responds is `V2::UsersController`.

I wrote [those tests](https://github.com/tbalthazar/RailsRouteTestsProblem/blob/master/test/integration/routes_test.rb) :
```
# this one succeeds but it should fail, because /users should map to v2/users
test 'route version 1' do
  assert_generates '/users', { controller: 'v1/users', action: 'index' }
end

# this one succeeds, as expected
test 'route version 2' do
  assert_generates '/users', { controller: 'v2/users', action: 'index' }
end
```
I expect the `route version 1` test to fail (but it succeeds).
The `route version 2` succeeds as expected.

Sounds like a bug to me.
There is [a sample Rails (4.2) app here](https://github.com/tbalthazar/RailsRouteTestsProblem). If you run `rake`, you'll see that the tests are passing.

**Comment by pixeltrix** [comment]
This is what I'd expect - you're only testing the path generation and there's no reason two different controller/action pairs couldn't generate the same path.
