### ISSUE TITLE
ID params not properly passed in nested FROM-subqueries

### ISSUE THREAD

**Issue by tbreier** [rails/rails#19201]
When trying to upgrade from Rails 4.1.5 to Rails 4.2, I encountered a problem with nested statements within FROM clauses of the kind `...where(id: something)` or `...where(foreign_id: something)`.
I was able to reproduce it, see https://gist.github.com/tbreier/c167ddc63902ea7a17af.
Notice how when there are two nested FROMs, passing the ID doesn't work - it gets niled or thrown away. Passing an object works, however.

**Comment by sgrif** [comment]
This is already fixed in 4.2.1

**Comment by tbreier** [comment]
Thank you! And sorry for not checking whether this was already fixed myself.
