### ISSUE TITLE
The condition in an association's default_scope with a join is applied before the join

### ISSUE THREAD

**Issue by mbillard** [rails/rails#19226]
``` ruby
unless File.exist?('Gemfile')
  File.write('Gemfile', <<-GEMFILE)
    source 'https://rubygems.org'
    gem 'rails', github: 'rails/rails'
    gem 'arel', github: 'rails/arel'
    gem 'sqlite3'
  GEMFILE

  system 'bundle'
end

require 'bundler'
Bundler.setup(:default)

require 'active_record'
require 'minitest/autorun'
require 'logger'

# This connection will do for database-independent bug reports.
ActiveRecord::Base.establish_connection(adapter: 'sqlite3', database: ':memory:')
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :posts, force: true  do |t|
  end

  create_table :comments, force: true  do |t|
    t.integer :post_id
  end

  create_table :likes, force: true do |t|
    t.integer :comment_id
  end
end

class Post < ActiveRecord::Base
  has_many :comments
end

class Comment < ActiveRecord::Base
  belongs_to :post
  has_many :likes

  default_scope { joins(:post).where(posts: { id: 1 }) }
end

class Like < ActiveRecord::Base
  belongs_to :comment

  default_scope { joins(:comment).where(comments: { id: 1 }) }
end

class BugTest < Minitest::Test
  def test_association_stuff
    post = Post.create!
    post.comments << (comment = Comment.create!)
    comment.likes << (like = Like.create!)

    assert_equal Like.all.to_a, [like]
  end
end
```

The query raises the following error:

```
ActiveRecord::StatementInvalid: SQLite3::SQLException: no such column: posts.id: SELECT "likes".* FROM "likes" INNER JOIN "comments" ON "comments"."id" = "likes"."comment_id" AND "posts"."id" = ? WHERE "comments"."id" = ?
```

You can see that the `"posts"."id" = ?` condition is applied to the `INNER JOIN` instead of at the end in the `WHERE` clauses.

A workaround for this is to do the join in the `default_scope` of `Like` manually which bypasses the association's `default_scope`:

``` ruby
default_scope { joins("INNER JOIN comments ON comments.id = likes.comment_id").where(comments: { id: 1 }) }
```

**Comment by kassio** [comment]
I'm not sure if it's a bug. I don't know if the `join(:comment)` should trigger the Comment's default scope. You can easily fix this problem with:

```ruby
class Like < ActiveRecord::Base
  belongs_to :comment

  default_scope { joins(comment: :post).where(comments: { id: 1 }) }
end
```

**Comment by kassio** [comment]
Actually, I guess I was wrong. I don't know whether it should include all the default scopes or not. We really have a problem because, for now, it's merging only the `where`, but not the `join`.

@rafaelfranca Could you help us here? What should be the result with those nested default scoped?

**Comment by mbillard** [comment]
I feel like the default scope should be included but instead of being part of the join clause (`ON ...`) be appended to the where clause.

**Comment by FlaviaFortes** [comment]
What do you think @rafaelfranca?

**Comment by al2o3cr** [comment]
Moving the clause from the `ON` to the `WHERE` has consequences for outer joins. For instance:

```
SELECT * FROM posts
LEFT JOIN comments ON comments.post_id = posts.id AND comments.spammy = 0
WHERE posts.featured = 1
```
With the condition in the `ON` clause, you'll always get at least one row in the result set even if there are no no-spammy comments for a post.

```
SELECT * FROM posts
LEFT JOIN comments ON comments.post_id = posts.id
WHERE posts.featured = 1 AND comments.spammy = 0
```
In this case, you'll get zero rows for a post that doesn't have any matching.

I believe the code for generating join clauses in `includes` and `joins` is mostly shared, so any fix needs to make sure to not break `includes` which needs the default scope to be part of the join clause.

**Comment by johncblandii** [comment]
I ran into this exact issue today when working with the `Paranoia` and `acts_as_paranoid` gems. I thought it was their fault but it turns out to be `default_scope`. 

I expect:
`SELECT "task_results".* FROM "task_results" INNER JOIN tasks on tasks.id = task_results.task_id WHERE "task_results"."deleted_at" IS NULL AND (tasks.system_type = 1)`

but get:
`SELECT "task_results".* FROM "task_results" INNER JOIN "tasks" ON "tasks"."id" = "task_results"."task_id" AND "tasks"."deleted_at" IS NULL WHERE "task_results"."deleted_at" IS NULL AND (tasks.system_type = 1)`

This removes `pg_search` gem from being able to join properly as well.

**Comment by maclover7** [comment]
This still hasn't been fixed, since #27069 was opened.

**Comment by kamipo** [comment]
It works on master.

**Comment by owen2345** [comment]
The problem still happens on rails 7

**Comment by zzak** [comment]
@owen2345 I couldn't reproduce with main, here is the updated script to use the most recent `gemfile` style bug report:

```ruby
# frozen_string_literal: true

require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  gem "rails", github: "rails/rails", branch: "main"
  gem "sqlite3"
end

require "active_record"
require "minitest/autorun"
require "logger"

# This connection will do for database-independent bug reports.
ActiveRecord::Base.establish_connection(adapter: "sqlite3", database: ":memory:")
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :posts, force: true  do |t|
  end

  create_table :comments, force: true  do |t|
    t.integer :post_id
  end

  create_table :likes, force: true do |t|
    t.integer :comment_id
  end
end

class Post < ActiveRecord::Base
  has_many :comments
end

class Comment < ActiveRecord::Base
  belongs_to :post
  has_many :likes

  default_scope { joins(:post).where(posts: { id: 1 }) }
end

class Like < ActiveRecord::Base
  belongs_to :comment

  default_scope { joins(:comment).where(comments: { id: 1 }) }
end

class BugTest < Minitest::Test
  def test_association_stuff
    post = Post.create!
    post.comments << (comment = Comment.create!)
    comment.likes << (like = Like.create!)

    assert_equal Like.all.to_a, [like]
  end
end
```
