### ISSUE TITLE
mysql microsecond precision support violates defaults

### ISSUE THREAD

**Issue by dre-hh** [rails/rails#19223]
This feature was introduced in df5a38fc6aeb8dfaa816fcbe0efb3fe4de169833

>MySQL 5.6 and later supports microsecond precision in datetime.
You might want to branch it to include this only for 5.6, but
passing these values to 5.6 doesn't cause issues either. 

Unfortunately it does. Let's consider following usecase. you insert some records, which recieve a created at.

```SQL
 INSERT INTO `recent_contact_requests` (`requester_id`, `requestee_id`, `created_at`, `updated_at`) VALUES (2, 3, '2014-11-23 13:41:38.394797', '2014-11-22 13:41:38.394797')
INSERT INTO `recent_contact_requests` (`requester_id`, `requestee_id`, `created_at`, `updated_at`) VALUES (1, 3, '2014-11-24 13:41:38.394797', '2014-11-23 13:41:38.394797')
INSERT INTO `recent_contact_requests` (`requester_id`, `requestee_id`, `created_at`, `updated_at`) VALUES (1, 2, '2014-11-22 13:41:38.394797', '2014-11-24 13:41:38.394797')
```

```ruby
RecentContactRequest.where('created_at < ?', 100.days.ago)
```

which will generate the query 

```SQL
SELECT `recent_contact_requests`.* FROM `recent_contact_requests` WHERE (created_at < '2014-11-24 13:41:38.394797')
```

So you would expect it to return the first 2 records but not the last one, because the it's created is exactly`2014-11-24 13:41:38.39479` but not less than it.

However this is not what will happen on mysql below 5.6.  Below 5.6 all the records will be stored without the microsecond timestamp. So the last record will be stored with `created_at: "2014-11-22 13:41:38"`.

And for the comparison of dates mysql, will just do a lexical comparison. So `2014-11-22 13:41:38` is actually less than `2014-11-24 13:41:38.394797` and the query will return the last record also.

>You might want to branch it to include this only for 5.6

I.d.k why, but we experience this behavior on 5.6 either. The timestamps have been truncated on insert. 

This implementation of microseconds also ignores the fact, that a a precision was set manually. 

You can define the precision of timestamps for db queries by setting `Time::DATE_FORMATS[:db]`. If you then pass a datetime like object to an AR query it will automatically respect this setting.

So 
```ruby
# set date format to have 3 places for microseconds
Time::DATE_FORMATS[:db] = '%Y-%m-%d %H:%M:%S.%3N'
#fire up a query
RecentContactRequest.where('created_at < ?', 100.days.ago)
```
will result in
```SQL
SELECT `recent_contact_requests`.* FROM `recent_contact_requests` WHERE (created_at < '2014-11-24 13:41:38.394.394797')
```

This feature was moved to active_record/connection_adapters/abstract/quoting.rb:130 in f1a0fa9e19b7e4ccaea191fc6cf0613880222ee7

I suggest to remove `#{sprintf("%06d", value.usec)}"` from the mysqladapter and just set a new default `Time::DATE_FORMATS[:db]` which will allow microseconds (need to check first, whether it will be supported by all latest db versions ) and let the user specify it's own format if  using an older db version.

By the way, at the same time a precision option (within a migration) was introduced for datetime fields. Another question would be, whether AR should automatically consider the defined precision setting for a field when this field is used within a query (ignoring the `Time::DATE_FORMATS[:db]` setting)

See https://gist.github.com/dre-hh/67cf05d08b40ffa0dc82

**Comment by sgrif** [comment]
As I mentioned on the commit, `Time::DATE_FORMATS[:db]` isn't a "setting" as you put it, it's a standard ANSI format. It isn't something that should be overridden, and that usage is not supported.

As for the bug you mention, as per our contributing guide (which can be found at http://guides.rubyonrails.org/contributing_to_ruby_on_rails.html), can you please provide a script we can use to reproduce the issue, using https://github.com/rails/rails/blob/master/guides/bug_report_templates/active_record_master.rb as a template?

**Comment by dre-hh** [comment]
>Time::DATE_FORMATS[:db] isn't a setting
Good to know. However quoting.rb won't also respect the new precision setting  for a field, wouldn't it?

> can you please provide a script we can use to reproduce the issue
sure, as soon as i find find the time

**Comment by dre-hh** [comment]
Here it is
https://gist.github.com/dre-hh/67cf05d08b40ffa0dc82

**Comment by dre-hh** [comment]
The fractional seconds have been added to mysql at version 5.6.4 btw.
http://dev.mysql.com/doc/refman/5.6/en/fractional-seconds.html

**Comment by sodabrew** [comment]
Does the merge of #20732 resolve this? /cc @jorihardman @sgrif

**Comment by sgrif** [comment]
Yes. Thank you.
