### ISSUE TITLE
enable_extension portability gotcha?

### ISSUE THREAD

**Issue by tardate** [rails/rails#19228]
I'm not sure what the right approach to fixing this might be. For now I can just offer observations and see if others can help. Ran into this issue when updating an app to Rails 4.1.0. Production PostgreSQL is 9.0.3 and cannot change anytime soon. But our dev machines have PostgreSQL 9.3.

We run into issue with `enable_extension "plpgsql"` in the generated `schema.rb`, when for example schema loading onto a staging server. This wants to `CREATE EXTENSION..`, a PostgreSQL command not support before 9.1. However running migrations in 9.0 is not an issue. 

If I'm reading ActiveRecord::Schema dumper correctly, schema dump will add `enable_extension "plpgsql"` to schema.rb if the current (i.e. development) database supports it, regardless if needed or not.

This raises a couple of issues, that may or may not really need fixing:
* If I am developing with PostgreSQL >=9.1, my app will not be fully portable to all officially supported PostgreSQL versions, [still 8.2+ according to RailsGuides](http://edgeguides.rubyonrails.org/active_record_postgresql.html). Should I expect to be able to develop fully portable apps by default, or does the minimal supported PostgreSQL version need changing?
* Even if my development adds `enable_extension "plpgsql"` to schema.rb, shouldn't the schema loaded be smart enough to ignore/alter how this is applied to older, supported PostgreSQL versions that can't grok `CREATE EXTENSION..`?
* Since I only see this issue when doing a schema load, but not when running migrations in full, the implication is that a pure-migration based deployment is never performing the equivalent of `enable_extension "plpgsql"`. This is perhaps more concerning than the other issues (which have work-arounds), because I guess it means I end up with a functionally different deployment depending on whether I did schema:load or just db:migrate

**Comment by rafaelfranca** [comment]
> If I am developing with PostgreSQL >=9.1, my app will not be fully portable to all officially supported PostgreSQL versions, still 8.2+ according to RailsGuides. Should I expect to be able to develop fully portable apps by default, or does the minimal supported PostgreSQL version need changing?

I'd not recommend to develop in a version different of the production environment. This is just one of the problems that may happen.

> Even if my development adds enable_extension "plpgsql" to schema.rb, shouldn't the schema loaded be smart enough to ignore/alter how this is applied to older, supported PostgreSQL versions that can't grok CREATE EXTENSION..?

Yes. We can improve that.

**Comment by rafaelfranca** [comment]
I'm closing this issue since it is not causing wrong behavior. Feel free to send a PR to improve the `enable_extension`.

**Comment by tardate** [comment]
@rafaelfranca just heard from someone else who ran into this problem. Maybe I should try for that P/R!

`.. since it is not causing wrong behavior` - not sure I agree with that. I'd call this a definite portability bug, especially when developing apps for deployment by third parties.
