### ISSUE TITLE
JRuby OpenSSL::Cipher::CipherError

### ISSUE THREAD

**Issue by sivsushruth** [rails/rails#19235]
Please view this, http://stackoverflow.com/questions/14552303/opensslcipherciphererror-with-rails4-on-jruby
In short, an error is thrown when rails tries to encrypt:

```
OpenSSL::Cipher::CipherError: Illegal key size: possibly you need to install Java Cryptography Extension (JCE) Unlimited Strength Jurisdiction Policy Files for your JRE
```

I was thinking if it we could add **config/initializers/unlimited_strength_cryptography.rb** to the rails generator templates with the following code:

```
if RUBY_PLATFORM == 'java' # Allows the application to work with other Rubies if not JRuby
  require 'java'
  java_import 'java.lang.ClassNotFoundException'

  begin
    security_class = java.lang.Class.for_name('javax.crypto.JceSecurity')
    restricted_field = security_class.get_declared_field('isRestricted')
    restricted_field.accessible = true
    restricted_field.set nil, false
  rescue ClassNotFoundException => e
    # Handle Mac Java, etc not having this configuration setting
    $stderr.print "Java told me: #{e}n"
  end
end
```

**Comment by sivsushruth** [comment]
I suggest we do a conditional generation of this file. 
If the platform is Jruby and you do **rails new app_name**  then this file is generated.

I will be more than happy to code this.

**Comment by sivsushruth** [comment]
error case 1) This error pops up if i use devise without adding this file manually.

**Comment by atambo** [comment]
This code snippet does not work on all JVM implementations (it blows up on the IBM JVM because the isRestricted field doesn't exist).

Also, this is probably not legal to do this...

**Comment by sivsushruth** [comment]
@atambo Any workarounds that you are aware of ?

**Comment by atambo** [comment]
The information on the jruby wiki talks about options:

https://github.com/jruby/jruby/wiki/UnlimitedStrengthCrypto

Another option is to add a feature to rails that allows you to disable encryption of cookies.

**Comment by sivsushruth** [comment]
Refer #19237 
Added a rescue statement for OpenSSLCipherError and the message says
```
Unlimited Strength Crypto not available on this JVM. To know more, read https://github.com/jruby/jruby/wiki/UnlimitedStrengthCrypto
```

**Comment by robin850** [comment]
(cross-refs #12320)

**Comment by kares** [comment]
similar code is now part of JRuby and its probably better to only have it there since its been kind of changing lately with Java 8 releases (that or simply installing JCE). the proposed code no longer works on 8u111 and there are also other issues with that release. also Java 9 will completely change and JRuby will likely handle that for you (since around 9.1.7). voting to close as "won-t fix" on Rails' end.

**Comment by robin850** [comment]
Yep, you are right, that's certainly not something that should be handled at the Rails level. I'm giving this a close.

Thank you very much for the update @kares !
