### ISSUE TITLE
Windows alternative for `which abc`

### ISSUE THREAD

**Issue by sivsushruth** [rails/rails#19244]
Take for example:
```
unless `which kindlerb` 
  abort "Please gem install kindlerb"
end
```
This simply wont work on Windows.
There is an alternative for **which** in Windows ->  **where**.

What I suggest we do is, instead of calling `which kindlerb` we can have something like,
```
Class.find_in_system("kindlerb")
```
And we have platform specific codes for this functionality. 
Let me know what you guys think.
Thanks

**Comment by schneems** [comment]
Where in the code or docs do we use "which"? We shouldn't be doing the example you gave us, we should be requiring and rescuing load error

**Comment by sivsushruth** [comment]
@schneems https://github.com/rails/rails/blob/390449ab8c55dacc08517bc270c6203bb1f50e02/guides/rails_guides/kindle.rb#L3

**Comment by rafaelfranca** [comment]
This code is not to run in people application. It is an internal tool for
the Rails maintainers. It is part of our release process and we only use
Unix systems, so there is no need to support Windows

**Comment by sivsushruth** [comment]
Got it.
