### ISSUE TITLE
Rails console doesn't use DATABASE_URL environment variable

### ISSUE THREAD

**Issue by andrewhamon** [rails/rails#19256]
If I have `DATABASE_URL` set and run `rails c` the settings in config/database.yml are used even though `DATABASE_URL` should override the settings. If I delete database.yml entirely, then I get the following error: `Could not load database configuration. No such file - ["config/database.yml"] (RuntimeError)`.

In irb I can run `ENV['DATABASE_URL']` and get the correct URL so I know the environment variable is correctly set.

[This rails guide](http://guides.rubyonrails.org/configuring.html#configuring-a-database) seems to indicate that database.yml is optional and indeed I can run a server with `rails s` even with no database.yml present.

Perhaps this is by design, but I can't imagine why the `DATABASE_URL` would be ignored when using a rails console.

**Comment by jvanbaarsen** [comment]
@andrewhamon What rails version are you using?

**Comment by andrewhamon** [comment]
Rails 4.2 / Ruby 2.1.5 installed with RVM

**Comment by schneems** [comment]
It works but you have to make sure DATABASE_URL is set before rails loads. Here's where that error comes from https://github.com/rails/rails/blob/fb764ba63e53b728873075a0d207b993409798a2/railties/lib/rails/application/configuration.rb#L88-L102

You can see it checks for `DATABASE_URL`

For me, I use a `.env` file to set environment variables. I had to run my command with `foreman start` which sources the env before the process gets run

```
$ rm config/database.yml
$ foreman run bundle exec rails runner 'puts ENV["DATABASE_URL"].present?'
true
```

I also tried running this with the `dotenv` gem which doesn't load env vars until later, when I did that I got an error. 

You can definitely run rails without a `database.yml`.

**Comment by andrewhamon** [comment]
@schneems That is quite compelling, surely it must be an issue on my part.

Any idea what might be causing this?

```
export DATABASE_URL="postgresql://user:password@localhost/database"
echo $DATABASE_URL
# postgresql://user:password@localhost/database

bundle exec echo $DATABASE_URL
# postgresql://user:password@localhost/database

irb
>  ENV['DATABASE_URL']
# postgresql://user:password@localhost/database

bundle exec irb
>  ENV['DATABASE_URL']
# postgresql://user:password@localhost/database

bundle exec rails runner ''puts ENV["DATABASE_URL"]'
# /usr/local/rvm/gems/ruby-2.1.5/gems/railties-4.2.0/lib/rails/application/configuration.rb:110:in `database_configuration': Cannot load `Rails.application.database_configuration`:
# Could not load database configuration. No such file - ["config/database.yml"] (RuntimeError)
```

Further info
```
which bundler
# /usr/local/rvm/gems/ruby-2.1.5@global/bin/bundler

which rails
# /usr/local/rvm/gems/ruby-2.1.5/bin/rails

which ruby
# /usr/local/rvm/rubies/ruby-2.1.5/bin/ruby
```

**Comment by schneems** [comment]
Don't know what to say. Works for me

```
2.1.5  ~/documents/projects/codetriage (master)
$ bundle exec rails -v
Rails 4.2.0
2.1.5  ~/documents/projects/codetriage (master)
$ bundle exec rails runner 'puts ENV["DATABASE_URL"]'
postgresql://localhost/triage_development
```

Try to reproduce the problem on a new rails app. Try `bundle open railties` and see if it matches this:

```
      # Loads and returns the entire raw configuration of database from
      # values stored in `config/database.yml`.
      def database_configuration
        path = paths["config/database"].existent.first
        yaml = Pathname.new(path) if path

        config = if yaml && yaml.exist?
          require "yaml"
          require "erb"
          YAML.load(ERB.new(yaml.read).result) || {}
        elsif ENV['DATABASE_URL']
          # Value from ENV['DATABASE_URL'] is set to default database connection
          # by Active Record.
          {}
        else
          raise "Could not load database configuration. No such file - #{paths["config/database"].instance_variable_get(:@paths)}"
        end
```

Try upgrading to a newer version of Rails.

**Comment by andrewhamon** [comment]
Hi @schneems

I appreciate the time you've taken to help.

I'm using Rails 4.2 (but not originally, it has been upgraded from 4.1 iirc) and Ruby 2.1.5 on Ubuntu 14.04 at the moment. I will try upgrading to Ruby 2.2.x and test using a new rails app. Maybe I should have mentioned this sooner but I'm also using the [rails-api](https://github.com/rails-api/rails-api) gem.

I am experiencing the same issue with the same app on a different server, this one using rbenv instead of rvm, but otherwise configured very similarly to what I had on the previous server. Maybe that's my problem...


To further illustrate:
```
$ bundle exec rails -v
Rails 4.2.0

# This time database.yml is present (but with values I would like to override)
$ bundle exec rails c
Loading development environment (Rails 4.2.0)
irb(main):001:0> ENV['DATABASE_URL']
=> "postgresql://user:password@localhost/database"

irb(main):002:0> User.first
PG::ConnectionBad: FATAL:  password authentication failed for user "user_from_yml"
```

Running `bundle open railties` gives me a vim error `"~/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/railties-4.2.0" is a directory 0,0-1`

However looking deeper in to the directory and finding the file you referenced earlier `~/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/railties-4.2.0/lib/rails/application/configuration.rb` I can indeed find these lines: 
```
# Loads and returns the entire raw configuration of database from
      # values stored in `config/database.yml`.
      def database_configuration
        path = paths["config/database"].existent.first
        yaml = Pathname.new(path) if path

        config = if yaml && yaml.exist?
          require "yaml"
          require "erb"
          YAML.load(ERB.new(yaml.read).result) || {}
        elsif ENV['DATABASE_URL']
          # Value from ENV['DATABASE_URL'] is set to default database connection
          # by Active Record.
          {}
        else
          raise "Could not load database configuration. No such file - #{paths["config/database"].instance_variable_get(:@paths)}"
        end
```

Once again, thanks for your time. I'll post back when I get another moment to do some more troubleshooting.

**Comment by vsurrel** [comment]
Ran into to the same problem, `rails c` won't start with this error.

After deleting all my gems `rm -Rf ~/.gem` followed by `bundle install`, `bundle exec rails c` went ok

**Comment by haihappen** [comment]
If you still encounter this problem with Rails 4.2, please try to stop spring with `spring stop` first. Spring will accept the new ENV variable when it starts again.

**Comment by andrewhamon** [comment]
Sorry for abandoning my issue for so long guys. @haihappen's solution worked like a charm. Thanks and my bad!

**Comment by schneems** [comment]
Thanks for letting us know.

**Comment by juanpastas** [comment]
Thanks @haihappen.

**Comment by jakeonrails** [comment]
:( I'm getting the same issue. I have successfully used `DATABASE_URL=xyz rails c` on a previous 3.x Rails project. But on Rails 4.1.8 it doesn't work.

**Comment by jakeonrails** [comment]
There's no spring or any application pre-loader involved. It just insists on connecting to the DB in `database.yml`

**Comment by schneems** [comment]
@jakeonrails you should be using 4.1.12 it's the latest. Can you post a small example application that exhibits the problem?

**Comment by duleorlovic** [comment]
:+1:  @haihappen  `spring stop` works for me too

**Comment by dfjosh** [comment]
@haihappen ftw!

**Comment by jakeonrails** [comment]
This can probably be closed. I'm pretty sure I didn't realize spring was loading in the background somehow. I never used it, never did spring start, etc, but coming back to this issue again today I tried spring stop and it worked great. Thanks for the support @schneems and @haihappen!

**Comment by maniankara** [comment]
Thanks for the support @schneems and @haihappen! 
But now I wonder what things run on my system when I say "bundle install" :(

**Comment by schneems** [comment]
@maniankara I don't follow your comment can you please open up a new issue with a detailed explanation of the problem you're seeing?

**Comment by maniankara** [comment]
@schneems I had the same problem as above and it was solved with the `spring stop` command. 
However, I was worried that there were something else running which was overriding rails' normal behaviour without me starting anything.
But I just found its my mistake. I did start the spring my self.
```
[anovil@ubuntu-anovil rails-app]$ rails runner 'puts ActiveRecord::Base.configurations'
Running via Spring preloader in process 18288
...
```
So, all good ! Thanks again !

**Comment by rafaelcgo** [comment]
@haihappen nailed it! Spring won't reload `.env` (as expected, I think).
Totally forgot about this!

**Comment by WvanLelyveld** [comment]
@haihappen is now @ream88? 
Anyway, that worked :)

**Comment by ream88** [comment]
Ah yeah, changed my name to match to other online profiles! Anyway glad I could help you all with this pesky bug! 😊

**Comment by nhodges** [comment]
Thanks, @ream88 `spring stop` did the trick.

**Comment by zackxu1** [comment]
I had the same issue.  `spring stop` did not work for me.  However it seems to be gem-related.  I changed ruby version in rvm, and did fresh `bundle install`.  Then I got into `rails console` and it worked!

**Comment by kasi1999999** [comment]
I used `PROJECT_PATH/bin/spring stop`. Worked like a charm
