### ISSUE TITLE
Where true/false conditions are broken for Postgres

### ISSUE THREAD

**Issue by brandoncc** [rails/rails#19268]
According to the PostgreSQL documentation, the proper way to check if a boolean field is true or false is with `IS TRUE` or `IS FALSE` and conversely `IS NOT TRUE` and `IS NOT FALSE`.

http://www.postgresql.org/docs/9.3/static/functions-comparison.html

Here is the SQL currently being generated for `where.not(primary: true)`:

```
[24] pry(DataEncryptionKey)> where.not(primary: true).to_sql
=> "SELECT \"data_encryption_keys\".* FROM \"data_encryption_keys\" WHERE (\"data_encryption_keys\".\"primary\" != 't')"
```

This returns no results, even when there are items which should match.

**Comment by brandoncc** [comment]
My apologies, this is regarding ActiveRecord 4.2.0.

**Comment by brandoncc** [comment]
One last addendum sorry, here is the actual output using the two, showing which one works:

```
[27] pry(DataEncryptionKey)> select('"data_encryption_keys"."primary" IS NOT TRUE')
=> [#<DataEncryptionKey:0x007feaf58682f0 id: nil>, #<DataEncryptionKey:0x007feaf5868048 id: nil>]

[28] pry(DataEncryptionKey)> where.not(primary: true)
=> []
```

**Comment by sgrif** [comment]
Please provide a script that we can use to reproduce the issue, using https://github.com/rails/rails/blob/master/guides/bug_report_templates/active_record_master.rb as a template.

**Comment by sgrif** [comment]
Actually I'm just going to go ahead and close this. `where.not` will never return null values for a field, for any type. This is the ANSI SQL behavior, which defines very clear semantics for NULL. It is not specific to PostgreSQL, and it certainly is not specific to boolean fields.

**Comment by brandoncc** [comment]
Wow, my apologies. I changed it to false instead of nil and it works fine. That seems very non-intuitive, but is that's the spec, then who am I to argue! Thanks for your time and reply.

**Comment by sgrif** [comment]
I definitely agree that it's non-intuitive, but the only way that Active Record could change the behavior is by changing every `where.not` query to `(foo != 'bar' OR foo IS NULL)`, which isn't a change that would make sense for Active Record

**Comment by 007lva** [comment]
Maybe a new feature to implement 
```ruby
where.not!
``` 
with this 'intuitive' behavior could be useful
