### ISSUE TITLE
Weird behavior of POST, PUT and DELETE in Mozilla Firefox

### ISSUE THREAD

**Issue by vladzzag** [rails/rails#19278]
Hi! I'm making forum https://github.com/vladzzag/rails-forum . And I've found some problems with POST, PUT and DELETE request methods in Mozilla Firefox. These requests are sending multiple times per click(e.g.), look at screenshots("Unban" link fire action "bans#destroy" with method DELETE). Also, I've noticed that Google Chrome have no problems.
Can someone tell me is it bug in Mozilla Firefox?

Sorry, my English skills is not so perfect.

![zzzzzz4](https://cloud.githubusercontent.com/assets/5022495/6577780/f0acea68-c748-11e4-9465-a6eaf337d423.png)
![zzzzz3](https://cloud.githubusercontent.com/assets/5022495/6577779/f0ab20fc-c748-11e4-9ee0-ddde49a6c5ef.png)
![zzzzz2](https://cloud.githubusercontent.com/assets/5022495/6577781/f0b0960e-c748-11e4-9149-e5bb34d37cac.png)
![zzzz1](https://cloud.githubusercontent.com/assets/5022495/6577782/f0b1d028-c748-11e4-9e74-d6f98d30fdc4.png)

**Comment by kaspth** [comment]
We can't help you debug or test Firefox. Try StackOverflow or the rubyonrails-talk mailing list.

**Comment by vladzzag** [comment]
Ok. link_to with DELETE and added "data: { confirm: "ololollo" }" sends only 1 POST request instead of 3. Maybe it was reason.

**Comment by vladzzag** [comment]
It is so weird...

**Comment by mkhuda** [comment]
I think the problem lies on Firefox (within Turbolinks-maybe), even when we do right-click on the link with data-method='delete', Firefox will call it. While in the other browsers the link is not executed.
