### ISSUE TITLE
When updating migrations, the last `end` statement is removed from `schema.rb`

### ISSUE THREAD

**Issue by onebree** [rails/rails#19286]
We are currently using Rails 4.2, and I do not think I noticed this issue before upgrading.

If new migrations are available, I run `rake db:migrate`. Everything is fine. When I enter check `git status`, it says that the schema has changed. Again, everything looks fine... However, when I diff the file, the last `end` statement (end of file) is removed. If I try to repopulate the database (for testing), it says it cannot complete the task because the schema is missing an `end` statement.

Why is this happening? Is it an issue with Rails 4.2, my development environment, or the version history of `schema.rb`?

**Comment by matthewd** [comment]
It's certainly not the version history; `schema.rb` gets regenerated from scratch.

My first guess would be that you are using a gem that manipulates the `schema.rb` construction process.

Can you post a gist of your gemfile?

Can you reproduce the problem on a new application? Which DB adapter are you using?

**Comment by onebree** [comment]
https://gist.github.com/onebree/eefe5c895076dc81f17e

At the moment, I am unable to create a new application. I am currently working on a company project. As far as a DB adapter, I believe we use mysql2

**Comment by renanoronfle** [comment]
I can't reproduce this bug.
I agree with @matthewd, probably a gem in your project must be causing this error

**Comment by onebree** [comment]
This is a gist of our Gemfile.
https://gist.github.com/onebree/eefe5c895076dc81f17e#file-gemfile

**Comment by onebree** [comment]
@renanoronfle do you know which gem could possibly cause the bug? Gemfile can be found in the gist I posted above.

**Comment by renanoronfle** [comment]
@onebree no, but i will try help you :)
