### ISSUE TITLE
Relation not loaded with includes(:profile) if order attribute is of format “profile”.“firstname” ASC

### ISSUE THREAD

**Issue by phlegx** [rails/rails#19287]
**Rails:** 4.1.7
**Ruby:** 2.1.4
**Postgresql:** 9.3
**Gem pg:** 0.17.1

Using the following order configuration, ```includes(:profile)``` don't includes the relation to the profile.

```ruby
class Account < ActiveRecord::Base
  has_one :profile
  scope :order_by, -> value { includes(:profile).reorder(value) }
end

class Profile < ActiveRecord::Base
  belongs_to :account
end
```

Using the following value to order all accounts works fine:

```ruby
> Account.order_by('profiles.firstname ASC')
```

Using the following value ```includes(:profile)``` don't includes relation ```:profile``` in the query:

```ruby
> Account.order_by('"profiles"."firstname" ASC')
```

**Any idea? I want to use the second one but without using `references(:profile)` in the scope.**

http://stackoverflow.com/questions/28987403/relations-are-not-loaded-with-includes-if-order-attributes-is-of-format-profi

**Comment by senny** [comment]
@phlegx what version of Rails are you using? Would be nice if you could attach an executable test-case that describes your issue. We have a [script](https://github.com/rails/rails/blob/master/guides/bug_report_templates/active_record_gem.rb) you can use as a starting point.

**Comment by phlegx** [comment]
I use Rails version 4.1.7.

**Comment by senny** [comment]
@phlegx automatic `references` are only added when the table and column names are not quoted. You should fall back on using `references`. Another option is to use `eager_load` instead of `includes`.
