### ISSUE TITLE
Having problem with Guidlines step error

### ISSUE THREAD

**Issue by prio101** [rails/rails#19284]
I am new in rails . I was following the [Getting Started](http://guides.rubyonrails.org/getting_started.html), but sorry to say in [Section 5.3](http://guides.rubyonrails.org/getting_started.html) It tells me to create a method in articles controller. Which is,

```rb
    def create
    end
```

but , the router doesn't show the promised error there , which should be, *"TEMPLATE MISSING ERROR"*

after that when I create a show method in the controller , it start to show the promised error in create route.

I took the sense of creating show method from rake commands.
But it can be more good to know that that thing was written in 5.3 section of getting started guide.
I don't know If I am telling the actual something matters but I think I have to start with community advice sooner or later.

**Comment by cdwort** [comment]
Hi @prio101 I'm not any kind of official person here, but I ran through the steps in the Getting Started guide, and I did get the "Template is missing" error right after I added the 
```
def create
end
```
to the articles controller. 

What behavior do you see after you add this method and resubmit the form?

**Comment by prio101** [comment]
I was having the "Routing error" ... but just right now after watching your
post I tried resubmit button ( submit buttons ) rather than writing url as
"localhost:3000/articles/new/create" and it's really showing the "Template
missing error" ... I am sorry to being stupid. Next time before asking I
will be more through with what really meant there ..

**Comment by prio101** [comment]
Hi,

I'd like to add you to my professional network on LinkedIn.

- mahabub islam

Confirm that you know mahabub islam: https://www.linkedin.com/e/v2?e=tl6a71-icdvl5iv-6x&amp;t=ssuw&amp;tracking=eml-guest-invite-cta&amp;ek=invite_guest&amp;sharedKey=mcO9dTUL&amp;invitationId=6029376769281265664


You received an invitation to connect. LinkedIn will use your email address to make suggestions to our members in features like People You May Know. Unsubscribe here: https://www.linkedin.com/e/v2?e=tl6a71-icdvl5iv-6x&amp;t=lun&amp;midToken=AQFmrFVhGEd36Q&amp;ek=invite_guest&amp;loid=AQEngo8iwy6rLAAAAU6ymTf53HXO_1LiwJ8YVM4wz0GnVJ-dpdC8uw5v5Jc2F5CdXAW5ZU0N5Ga0C3Ztji_0AtpNZppfCxwGoKuLd035aCSTDfWiQnJkig0PZ7Yn-qLqVlfbKQsyh1zEMlzm5kmAucsmF4cWmoHSe5C9YErZu5kZlqJJ7X4Yp9gip7KO5lwBL1aQ&amp;eid=tl6a71-icdvl5iv-6x Learn why we included this at the following link: https://www.linkedin.com/e/v2?e=tl6a71-icdvl5iv-6x&a=customerServiceUrl&ek=invite_guest&articleId=4788
&copy; 2015, LinkedIn Corporation. 2029 Stierlin Ct. Mountain View, CA 94043, USA

**Comment by prio101** [comment]
mahabub islam prio would like to connect on LinkedIn. How would you like to respond?

Accept: https://www.linkedin.com/blink?simpleRedirect=d3oSdjoOcjwOejoTdzsPej8MdzR4imVLqnhxt6BSrCACj5lkp3BfoSQZumlbp6lOomxP9DhUpnhvt71BoSdxfndQ9CZOpmwZrioPfmBI9z4MnT9Bp6VFrmlOnThPpnlDnThPsCBCfmJB9ClQqnpKimtBkClOs3Rx9CENbjpAd35RrmdFbj4TojpIt3RBfP9SbSkLrmZzbCVFp6lHrCBIbDtTtOYLeDdMt7hE&msgID=I6029376831189196800_500&markAsRead=

View mahabub islam prio&#39;s profile: https://www.linkedin.com/blink?simpleRedirect=d3oMcPoVc3wZh4BOpm9JpmQCt7xBt5ZBr6BCrT9MfndQ9CZOpmwZrioQfmBI9z4MnT9Bp6VFrmlOnThPpnlDnThPsCBCfmJB9DpMrzRQ9CENbjpAd35RrmdFbj4TojpIt3RBfP9SbSkLrmZzbCVFp6lHrCBIbDtTtOYLeDdMt7hE&msgID=I6029376831189196800_500&markAsRead=

You are receiving Reminder emails for pending invitations. Unsubscribe here: https://www.linkedin.com/blink?simpleRedirect=rmZzhj8BoDlEt6BDhj8BumNMpn8Md2lBcPAMp3APc6lzejoNoj8Vdz4OozwNcj4Nc30Mc30Mc6pzczANe64Qejhxe68VejoVc3wPcz0NdCkSdPkOcmgTpm8Te3kNdjtBd35zcmdyc38Pc312cylVr71BszRIqm5JpioMdz0MczRAqioQdzoRdz8Ne38VdzsSdPcVcz0SfmhFpOoNc5ZOpmhKqmRBsBZQsSlRpRZQsT9FpzRHpipQu6lQnS9RsSVRbjkJoDlPrDkJcj1vsClArCBJpn9vt7dBtmtvt7dOqmoJr6RBfmtKqmJzon9Q9CZLpPRQ9CENbjpAd35RrmdFbj4TojpIt3RBfP9SbSkLrmZzbCVFp6lHrCBIbDtTtOYLeDdMt7hE&msgID=I6029376831189196800_500&markAsRead=

You received an invitation to connect. LinkedIn will use your email address to make suggestions to our members in features like People You May Know. Unsubscribe here: https://www.linkedin.com/blink?simpleRedirect=6ENbjpAd35RrmdFbj4TojpIt3RAqmkCj3xzgBFWpjBdk4VzcyRgclwOnP4Sk6AVqT5ikAV9hRhLcDtGsCFAu4INm79HdRBNdP5brSJ6tScMp7BScAkTp4tHoDd7tAATcP5dnQsShCp3hSdkq7hEtnAOdj5ml7tvrRBpkARHt6hkizdkdP15dSUUpSN9dD9RdSZ5cAwThQN2lThUtRxPpTkPtB5yh6gTm7wMtDAJh6hvpThWtTxIt3lBkj94snhWoA8PmmtPi4xldRl1gk5DrmhyqP1RnQ5IckxhgjRAqmZI9z4MnT9Bp6VFrmlOnThPpnlDnThPsCBCfmJB9B4ScSh5hSxmhD9JhB51fmVBqSZkp6BJ9CVRr3RQ9CENbjpAd35RrmdFbj4TojpIt3RBfP9SbSkLrmZzbCVFp6lHrCBIbDtTtOYLeDdMt7hE&amp;msgID=I6029376831189196800_500&amp;markAsRead=This email was intended for rails/rails. Learn why we included this at the following link: https://www.linkedin.com/blink?simpleRedirect=3wUdPgZp4BBr6dFt79x9z4MnT9Bp6VFrmlOnThPpnlDnThPsCBCfmJB9CNOlmlzqnpOpldOpmRLt7dRoPRx9CENbjpAd35RrmdFbj4TojpIt3RBfP9SbSkLrmZzbCVFp6lHrCBIbDtTtOYLeDdMt7hE&msgID=I6029376831189196800_500&markAsRead=
&copy; 2015, LinkedIn Corporation. 2029 Stierlin Ct. Mountain View, CA 94043, USA

**Comment by kaspth** [comment]
Closed this to prevent more LinkedIn spam.
