### ISSUE TITLE
ActiveRecord object collection to_set causes memory leak

### ISSUE THREAD

**Issue by danmaz74** [rails/rails#19292]
I've been debugging a memory leak in a rails 3.2.21 app, and in the end discovered the problem, that I think could be a bug.

I had a comparison like this: 

    def foo
        return object.related_objects.to_set == object2.related_objects.to_set
    end

This was called thousands of times, and memory consumption went into the gigabytes in time.

I then substituted the comparison like this (this is also more efficient, but that's not the point):

    def foo
        return object.related_objects.select(:id).to_set == object2.related_objects.select(:id).to_set
    end

And the memory leak disappeared. So I guess there something wring with the to_set, as no reference was left, but the objects never got garbage collected.

**Comment by tibbon** [comment]
Ruby version?

**Comment by eileencodes** [comment]
@danmaz74 Rails 3.2 is only taking security updates at this point, and not merging in bug fixes or features. Can you reproduce this on a newer version of Rails?

**Comment by danmaz74** [comment]
@tibbon: Ruby version: 1.9.3 through 2.1.5

@eileencodes: unfortunately we don't have the time to upgrade our codebase to rails 4 in the near future and I didn't test it there. If you don't have the time to try testing yourselves and think the issue can be closed as it's related to an older version I don't have any problems, I just wanted to warn about a possible bug - for our needs we already found a workaround :)

**Comment by arthurnn** [comment]
thanks @danmaz74 for letting us know.
