### ISSUE TITLE
Add ability to filter out email address from ActionMailer log.

### ISSUE THREAD

**Issue by monfresh** [rails/rails#19293]
Hi,

It would be great to be able to filter out email addresses from the ActionMailer log without having to monkey-patch ActionMailer. 

Thoughts?

**Comment by eileencodes** [comment]
Hi @monfresh thanks for the idea! - Unfortunately, Rails doesn't accept feature requests on the issues tracker. You can either write up a PR and send it in, or if you're worried about it being accepted you can discuss it on mailing list: https://groups.google.com/forum/?fromgroups#!forum/rubyonrails-core

More information on feature requests can be found here: http://guides.rubyonrails.org/contributing_to_ruby_on_rails.html#what-about-feature-requests-questionmark
