### ISSUE TITLE
Validation of uniqueness fails on updating object with nested attributes

### ISSUE THREAD

**Issue by suratpyari** [rails/rails#19306]
I have element model

class Element < ActiveRecord::Base
  has_many :banners
  accepts_nested_attributes_for :banners
end

and in banner model I have

class Banner < ActiveRecord::Base
  belongs_to :element
  belongs_to :locale
  validates :locale, :content, :element_case, presence: true
  validates :locale_id, uniqueness: {scope: :element_id}
end

When I update it I get 'Banners locale has already been taken'.
Attributes sent on update:
 "element"=>{"uid"=>"uid1234", "banners_attributes"=>{"0"=>{"element_case"=>"Error", "locale_id"=>"1", "content"=>"content en", "id"=>"7"}, "1"=>{"locale_id"=>"2", "content"=>"content de", "id"=>"8"}, "2"=>{"locale_id"=>"3", "content"=>"content it", "id"=>"9"}}}

**Comment by suratpyari** [comment]
Rails version is 4.2.0

**Comment by eileencodes** [comment]
@suratpyari can you provide a reproduction script? That will help us understand your issue. You can find examples of runnable reproduction scripts here: https://github.com/rails/rails/blob/master/guides/bug_report_templates/active_record_master.rb

Thanks!

**Comment by kuldeepaggarwal** [comment]
Just formatted the input.

```ruby
class Element < ActiveRecord::Base
  has_many :banners
  
  accepts_nested_attributes_for :banners
end
```
and in banner model I have

```ruby
class Banner < ActiveRecord::Base
  belongs_to :element
  belongs_to :locale

  validates :locale, :content, :element_case, presence: true
  validates :locale_id, uniqueness: {scope: :element_id}
end
```


```hash
"element"=>{
  "uid"=>"uid1234", 
  "banners_attributes"=>{
    "0"=>{"element_case"=>"Error", "locale_id"=>"1", "content"=>"content en", "id"=>"7"},
    "1"=>{"locale_id"=>"2", "content"=>"content de", "id"=>"8"},
    "2"=>{"locale_id"=>"3", "content"=>"content it", "id"=>"9"}
  }
}
```

**Comment by suratpyari** [comment]
My mistake. I was missing id in banners_attributes
