### ISSUE TITLE
Setting / Resetting Release Expectations

### ISSUE THREAD

**Issue by jwaldrip** [rails/rails#19307]
I would love to see some truth to what is being said in the blog as to when the next release or release candidate is going to be live. I appreciate when the team resets expectations about a why there was a new RC instead of release and why. That being said, here we are 7 days past when 4.2.1 was supposed to be released and we have no update on why its delayed or when we can ACTUALLY expect the release. Let me know if there is anything I can do to help improve this.

**Comment by jwaldrip** [comment]
@matthewd please close with a response.

**Comment by schneems** [comment]
We only use issue tracker for PR and bug reports all discussion needs to go through the mailing list. As for release timing, were an all volunteer staff, and releases get cut when there's no more bugs reported as open on the current RC. If you want to help follow the issue tracker or use www.codetriage.com. You can triage, confirm, and maybe fix bugs blocking a release.

**Comment by jwaldrip** [comment]
I understand that. But there are no open issues in 4.2.1 and the last blog post stated the following:

> If no regressions are found expect the final release this Thursday, on March 5, 2015. If you find one, please open an issue on GitHub and mention me (@rafaelfranca) on it, so that we can fix it before the final release.

All I am asking is that when a release is scheduled that that expectation be either met or reset. That was the last bit of news the rails community heard from the rails team.

**Comment by rafaelfranca** [comment]
Sorry for the delay. As @schneems said all our time is limited and all volunteer. Last Thursday I was without decent internet and could not release. This happened to be a good thing because @amatsuda and @arthurnn found two regressions that were fixed Monday. I was going to release a new RC yesterday but got sick. But I'm going to do it today.

**Comment by schneems** [comment]
Thanks @rafaelfranca. 

@jwaldrip If this post had been on the mailing list, then lots of developers would have access to this information. It's why we want discussion over there. Please direct future questions and conversation to the mailing list
