### ISSUE TITLE
collection_check_boxes sets wrong id on check box field

### ISSUE THREAD

**Issue by japed** [rails/rails#19304]
If I do
`<%= f.collection_check_boxes :page_ids, Page.order(title: :asc), :id, :title %>`

I get the following HTML

    <input name="office[page_ids][]" type="hidden" value="0">
    <input class="check_box" type="checkbox" value="1" name="office[page_ids][]" id="office_page_ids_1">
    <label for="office_page_ids_1">About Us</label>
    
    <input name="office[page_ids][]" type="hidden" value="0">
    <input class="check_box" type="checkbox" value="1" name="office[page_ids][]" id="office_page_ids_1">
    <label for="office_page_ids_4">Accreditations and Affiliations</label>
    
    <input name="office[page_ids][]" type="hidden" value="0">
    <input class="check_box" type="checkbox" value="1" name="office[page_ids][]" id="office_page_ids_1">
    <label for="office_page_ids_2">Careers</label>
    
    <input name="office[page_ids][]" type="hidden" value="0">
    <input class="check_box" type="checkbox" value="1" name="office[page_ids][]" id="office_page_ids_1">
    <label for="office_page_ids_3">Mentoring</label>
    <input type="hidden" name="office[page_ids][]" value="">

So each check box uses `id="office_page_ids_1"` which means that clicking the labels doesn't check the check boxes (except for the first one).  Instead it should be using the id of the object which is what occurs on the labels.

Just taking the last one as an example it should be rendering

    <input class="check_box" type="checkbox" value="1" name="office[page_ids][]" id="office_page_ids_3">
    <label for="office_page_ids_3">Mentoring</label>

Hopefully you get what I mean

**Comment by kuldeepaggarwal** [comment]
@japed Which version of rails are you using? `collection_check_boxes` form helper method is working fine on master branch.

```ruby
class Post < ActiveRecord::Base
  has_many :comments, dependent: :destroy
end
```

```ruby
class Comment < ActiveRecord::Base
  belongs_to :post
end
```

In view:
```erb
<%= form_for Post.new do |f| %>

  <%= f.collection_check_boxes :comment_ids, Comment.all, :id, :description %>

<% end %>
```

```html
#output:

<form class="new_post" id="new_post" action="/posts" accept-charset="UTF-8" method="post">

  <input name="utf8" type="hidden" value="✓">
  <input type="hidden" name="authenticity_token" value="hsQV+XvVxAbRZ621tzOks+i3qqjI9LnOuf3gtB27Ywbdj9eABa2a9zhVtYq7UHDo4pYVVAlXwPRq54hgHNaoLQ==">
 

 <input type="checkbox" value="1" name="post[comment_ids][]" id="post_comment_ids_1">
  <label for="post_comment_ids_1">ds1</label>

  <input type="checkbox" value="2" name="post[comment_ids][]" id="post_comment_ids_2">
  <label for="post_comment_ids_2">ds2</label>

  <input type="hidden" name="post[comment_ids][]" value="">
</form>
```

**Comment by japed** [comment]
That is on 4.2.0.  Just made a test app that works.  So I'm going to close this as it's obviously something within my app causing it.
