### ISSUE TITLE
Set attribute default value on new record

### ISSUE THREAD

**Issue by dmitry** [rails/rails#19302]
The default value is not set while you are creating an instance of the model. Currently default value is only available through the columns_hash[:attribute_name].default. One of the solutions, is to rewrite reader of the record, like that:

```ruby
class User < ActiveRecord::Base
  def admin
    super || columns_hash[:admin].default
  end
end
```

This code is easy only when admin is `NOT NULL`, in other way it's a bit more complicated.

Why not to embed the functionality of setting the default value for the new record in rails 5.x?

PS. More info on that issue: http://stackoverflow.com/questions/328525/how-can-i-set-default-values-in-activerecord

**Comment by rafaelfranca** [comment]
Thank you so much for the issue but we don't take feature request on the issue tracker. We recommend you to try to implement the feature and send us a pull request or if you are in doubt if the feature will be accepts ask in Rails Core mailing list for feedback.
