### ISSUE TITLE
AR attribute lookup performed incorrectly if records are instantiated from cache

### ISSUE THREAD

**Issue by enthrops** [rails/rails#19318]
Background: A table named **people** with columns **format** and **name**, along with a corresponding ActiveRecord model and a sample row in the table.

STR:
1) Open up rails console and execute `Rails.cache.fetch('whatever') { Person.all.load }`. This will return all people and generate the cache entry.
2) Quit and open rails console again
3) Execute `Rails.cache.fetch('whatever') { Person.all.load }[0].name`. You will get the sample name back
4) Execute `Rails.cache.fetch('whatever') { Person.all.load }[0].format`. You will get **NoMethodError: private method `format' called for ...**
5) If you then execute `Person.new`, step 4 will work as expected
This is probably related to the fact that `format` is a method in `Kernel`, so I suppose something goes wrong with the AR lookup chain

**Comment by enthrops** [comment]
I've also noticed that despite both attributes being strings, **name** gets serialized as **ActiveRecord::Type::String**, while **format** gets serialized as **ActiveRecord::Type::Value**

**Comment by Qianfinland** [comment]
Which version of ruby and rails are you using? I try to reproduce with Rails 4.2.0 and ruby 2.2.1, and didn't have problems. Which database are you using?

**Comment by Qianfinland** [comment]
Rails has some reserved column names, format is one of them, you should rename the column.
Format is a private method in Object and you cannot use it for column name.

**Comment by enthrops** [comment]
Why is it working properly when serialization is not involved, and why does not it raise an exception when objects with such column names are instantiated?

**Comment by rafaelfranca** [comment]
Could you create an reproduction script with this template https://github.com/rails/rails/blob/master/guides/bug_report_templates/active_record_master.rb?

**Comment by enthrops** [comment]
Can not reproduce using the template, as failing to infer model column names depends on the model not being loaded yet, and that requires a proper rails application (or it's just that I don't know how to do that in a single file).
However, here is a [gist](https://gist.github.com/enthrops/1262dc765ca0aa5c6ec7) that shows that **format** is being serialized as **ActiveRecord::Type::Value**, not **ActiveRecord::Type::String**

**Comment by palkan** [comment]
Marshaling is ok. `format` is dumped as String, you can see something like `T@` after `format` in the dump - this is a reference to `ActiveRecord::Type::String` defined earlier for `title`.

You can check it simply:
```ruby
post = Post.first
# Print model types
p post.instance_eval('@attributes').send(:attributes).send(:types)

dump = Marshal.dump(post)
restored = Marshal.load(dump)
# Restored instance types
p restored.instance_eval('@attributes').send(:attributes).send(:types)
```

What is the full error message? `NoMethodError: private method `format' called for ...` what?

**Comment by enthrops** [comment]
For my initial example that would be `NoMethodError: private method 'format' called for #<Person:0x007fc99fb48f00>`

**Comment by byroot** [comment]
Updated repro script:

```ruby
# frozen_string_literal: true

require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  gem "rails"
  # If you want to test against edge Rails replace the previous line with this:
  # gem "rails", github: "rails/rails", branch: "main"

  gem "sqlite3"
end

require "active_record/railtie"
require "minitest/autorun"

# This connection will do for database-independent bug reports.
ENV["DATABASE_URL"] = "sqlite3::memory:"

class TestApp < Rails::Application
  config.load_defaults Rails::VERSION::STRING.to_f
  config.eager_load = false
  config.logger = Logger.new(nil)
end
Rails.application.initialize!

ActiveRecord::Schema.define do
  create_table :users, force: true do |t|
    t.string :name
    t.string :format
  end
end

class User < ActiveRecord::Base
end

User.create!(name: "name", format: "format")


class BugTest < ActiveSupport::TestCase
  def test_cached_records
    Rails.cache.write("users", User.all.to_a)
    users = Rails.cache.read("users")
    assert_equal "format", users.first.format
  end
end
```

This has been fixed years ago. Closing.
