### ISSUE TITLE
comparison of Array with Array failed in formatter.rb

### ISSUE THREAD

**Issue by JasonBarnabe** [rails/rails#19314]
I just upgraded Rails from 4.1.6 to 4.2.0, and I'm getting a new error. The intention of my code is to take a "bad" request and redirect it to the proper URL.

Relevant [routes](https://github.com/JasonBarnabe/greasyfork/blob/c706578cc0b200b96fbde0530cb4d76a3c45f6c0/config/routes.rb#L55) (the "bad" URL is handled by `show`, the proper URL is the `meta_js` route.
```ruby
resources :scripts, :only => [:index, :show] do
  match 'code/:name.meta.js', :to => 'scripts#meta_js', :locale => nil, :via => :options
end
```

In the [controller](https://github.com/JasonBarnabe/greasyfork/blob/c706578cc0b200b96fbde0530cb4d76a3c45f6c0/app/controllers/scripts_controller.rb#L170), handling the "bad" request:
```ruby
redirect_to script_meta_js_path(params.merge({:script_id => params[:id], :name => @script.name, :format => nil}))
```
Requesting `/en/scripts/3286-tumblr-mass-post-features` with the proper `Accept` header to trigger the logic, the result is:
```
ArgumentError in ScriptsController#show
comparison of Array with Array failed

actionpack (4.2.0) lib/action_dispatch/journey/formatter.rb:44:in `sort'
actionpack (4.2.0) lib/action_dispatch/journey/formatter.rb:44:in `generate'
actionpack (4.2.0) lib/action_dispatch/routing/route_set.rb:710:in `generate'
actionpack (4.2.0) lib/action_dispatch/routing/route_set.rb:741:in `generate'
actionpack (4.2.0) lib/action_dispatch/routing/route_set.rb:784:in `url_for'
actionpack (4.2.0) lib/action_dispatch/routing/route_set.rb:279:in `call'
actionpack (4.2.0) lib/action_dispatch/routing/route_set.rb:222:in `call'
actionpack (4.2.0) lib/action_dispatch/routing/route_set.rb:334:in `block (2 levels) in define_url_helper'
app/controllers/scripts_controller.rb:170:in `block (2 levels) in show'
```
The error in formatter.rb is on:
```ruby
        message = "No route matches #{Hash[constraints.sort].inspect}"
 ```
Adding some debugging to formatter.rb, I see that `constraints` is set to:
```ruby
{:controller=>"scripts", :action=>"meta_js", :locale=>nil, :id=>"3286-tumblr-mass-post-features", "locale"=>"en", "id"=>"3286-tumblr-mass-post-features", "script_id"=>"3286-tumblr-mass-post-features", "name"=>"Tumblr - Mass Post Features", "format"=>nil, "controller"=>"scripts", "action"=>"show"}
```
Both `:id` and `"id"` are present, so maybe that's why it fails.

It's possible that my routing logic is wrong, but this looks like it's failing on giving me an error message...

**Comment by JasonBarnabe** [comment]
Simplified test case:

Route:
```ruby
get 'test/:name', :to => "test#test", :as => 'test'
```
From `rails console`:
```
2.2.0 :002 > app.test_path(:foo => 'bar', 'foo' => 'bar')
ArgumentError: comparison of Array with Array failed
	from /home/jason/.rvm/gems/ruby-2.2.0/gems/actionpack-4.2.0/lib/action_dispatch/journey/formatter.rb:43:in `sort'
	from /home/jason/.rvm/gems/ruby-2.2.0/gems/actionpack-4.2.0/lib/action_dispatch/journey/formatter.rb:43:in `generate'
	from /home/jason/.rvm/gems/ruby-2.2.0/gems/actionpack-4.2.0/lib/action_dispatch/routing/route_set.rb:710:in `generate'
	from /home/jason/.rvm/gems/ruby-2.2.0/gems/actionpack-4.2.0/lib/action_dispatch/routing/route_set.rb:741:in `generate'
	from /home/jason/.rvm/gems/ruby-2.2.0/gems/actionpack-4.2.0/lib/action_dispatch/routing/route_set.rb:784:in `url_for'
	from /home/jason/.rvm/gems/ruby-2.2.0/gems/actionpack-4.2.0/lib/action_dispatch/routing/route_set.rb:279:in `call'
	from /home/jason/.rvm/gems/ruby-2.2.0/gems/actionpack-4.2.0/lib/action_dispatch/routing/route_set.rb:222:in `call'
	from /home/jason/.rvm/gems/ruby-2.2.0/gems/actionpack-4.2.0/lib/action_dispatch/routing/route_set.rb:334:in `block (2 levels) in define_url_helper'
	from (irb):2
```
Looks like a missing routing key combined with a duplicated routing key (one symbol, one string) causes this error. I'm unsure how my app is ending up with the duplicated key though.

**Comment by pixeltrix** [comment]
Sigh, the mixture of string keys and symbol keys makes me :cry:

The reason is because the `sort` method uses `<=>` and that doesn't work when comparing a symbol with a string:

``` irb
>> :foo <=> 'foo'
=> nil
```

You're getting a mix because you're merging on the params hash which is not really recommended as you're sending untrusted user data into your url helpers - I'd suggest slicing out the required params first and then merging them.
