### ISSUE TITLE
Disable ParamsWrapper by default in 5.0

### ISSUE THREAD

**Issue by printercu** [rails/rails#19319]
wdyt?
It seems to be not so useful with StrongParams and also can be a bit confusing.

It can be left as mixin and one will be able to include it to ApplicationController.

**Comment by rafaelfranca** [comment]
Thank you so much for the issue but we don't take feature request on the issue tracker. We recommend you to try to implement the feature and send us a pull request or if you are in doubt if the feature will be accepts ask in Rails Core mailing list for feedback.

I believe we already have a thread for this in the mailing list.

**Comment by morgoth** [comment]
@printercu it is discussed on https://groups.google.com/forum/#!topic/rubyonrails-core/e50YAHA6BKc

**Comment by printercu** [comment]
@morgoth thanks!
