### ISSUE TITLE
undefined method `content_tag' from other undefined method within nested `content_tag`

### ISSUE THREAD

**Issue by GolfyMcG** [rails/rails#19328]
I experienced this error today despite being 100% certain that `content_tag` was in fact defined. The error stemmed from calling a different method (`include?`) which was actually undefined from within a `content_tag` block. Is this intended behavior?

In case it isn't clear from my description, below are the relevant pieces of my code to help demonstrate:

```rb
def item_list(name, items, options)
  content_tag(:ul, class: "item-list #{name}-list" do
    items.map { |item| item_tag(item, options) }.inject(:+)
  end
end

def item_tag(item, options)
  item_class = options[:matches].include?(item) ? 'match' : nil
  content_tag(:li, item.name, class: item_class)
end
```

I was continually given the error that the content tag from the `item_list` method was undefined. My actual problem stemmed from the `include?` being undefined. I had passed a `ActiveRecord` object, rather than a collection so obviously it didn't work.

It was incredibly confusing, and I was hoping to get some clarification or potentially correct it.

**Comment by endersstocker** [comment]
I cannot seem to reproduce this in Rails 4.2. When assigning options[:matches] to a non-enumberable object, I receive the expected exception: ``undefined method `include?'``. Is the above code in a view helper? In what versions of Ruby and Rails are you seeing this unexpected behavior?

**Comment by GolfyMcG** [comment]
My apologies - this is in a decorator object created with [Draper](https://github.com/drapergem/draper) , and we've included all rails helpers in the class using `include Draper::LazyHelpers`.

**Comment by matthewd** [comment]
https://github.com/drapergem/draper/blob/master/lib/draper/lazy_helpers.rb#L10-L11

**Comment by GolfyMcG** [comment]
@matthewd and @endersstocker - thanks for taking a look! Didn't realize this would happen when mixing in all the helpers ><
