### ISSUE TITLE
Connection leakage when inspecting exceptions across Threads

### ISSUE THREAD

**Issue by halorgium** [rails/rails#19332]
We've been tracking an issue with Celluloid (https://github.com/celluloid/celluloid/issues/499) where an exception occurs inside ActiveRecord and is then handled by the core Celluloid actor as a crash. 
As part of the handling, the exception is inspected which causes a connection to be checked out of the pool. Then the thread dies and orphans the connection. 

Was the assumption around `.inspect` (and `.table_exists?`) that these methods would be used inside Threads which already hold a checked-out connection?
In Celluloid, we run blocks of code inside separate Threads or Fibers to allow for pipelining and suspending. Because of this, any methods which only checkout connections are prone to leakage. 

Is this change an acceptable one? https://github.com/halorgium/rails/commit/8599bf2912215ba3e17568212bd3ff1c96dacf7f
I note that many other methods are along a similar vein. 

/cc @tarcieri @nullstyle

**Comment by halorgium** [comment]
I have distilled the issue to a simpler repro: https://gist.github.com/halorgium/2778b0db4286b907343a

**Comment by matthewd** [comment]
Which Rails version are you using? 4.2 should reclaim the connection shortly after the owning thread dies.

That commit seems fine.. though as we are currently pretty free with our use of `connection`, I'm not sure whether I'd consider it a back-portable bug fix.

**Comment by tarcieri** [comment]
@matthewd what sort of mechanism does it use to reclaim them? Celluloid pools threads, as it were...

**Comment by halorgium** [comment]
@matthewd using 4.2 produces the same result. I am mostly concerned about the thread holding the connection if it does not die. 
There is another code path within Celluloid which causes this affect where the core actor thread does not die.

**Comment by halorgium** [comment]
@tarcieri it is using a `#alive?` check on the owner thread. 

``` ruby
        stale_connections = synchronize do
          @connections.select do |conn|
            conn.in_use? && !conn.owner.alive?
          end
        end
```

**Comment by halorgium** [comment]
@matthewd the other concern is that a simple `#inspect` on a model can cause a DB connection and query. This seems somewhat excessive, especially if this is called in non-DB threads. 
Ideally, a system would not have exceptions, but it does happen and if the result is starving the connection pool, I am :cry:ing.

**Comment by halorgium** [comment]
Is this issue able to get some attention?

**Comment by spscream** [comment]
I have tested this issue on rails 4-2-stable and on master branch with celluloid master and issue still persists. 
Here some logs:
https://gist.github.com/spscream/0c2a6a0758a6f75afbfc

**Comment by TiagoCardoso1983** [comment]
I've been experiencing issues with AR and Celluloid for like years. I don't if we're all talking about the same issue here, but I have two main issues with AR:

* touching the ActiveRecord::Base class or anything inheriting it causes the connection to the DB to be established;
* that each new Fiber task will check out a new connection from the pool, even if a connection has been checked out in the current thread already. 

About the first problem, it's quite hard to solve without knowing the AR internals. As for the second, can't we just replace every Thead#[] usage (which creates fiber-local variables) with [Thread#thread_variable_get/set](http://ruby-doc.org/core-2.2.0/Thread.html#method-i-thread_variable_get)? What are the drawbacks? Or has this been discussed elsewhere already?

**Comment by halorgium** [comment]
@TiagoCardoso1983 the main problem is the assumption that objects (like exceptions) do not often travel between threads. This assumption results in connections being opened (and not closed) in threads which Rails is not managing. The problem is independent of `Fiber`s but is definitely exacerbated.
