### ISSUE TITLE
Rails Documentation. Getting Started Tutorial not working.

### ISSUE THREAD

**Issue by itsportspe** [rails/rails#19331]
If you follow the "getting started" tutorial on the rubyonrails.org site (linked below) you will notice that at the end of section 5.2 upon filling out the form and clicking submit, there is a routing error that doesn't follow the tutorial. I don't know how to fix this. Can someone please fix this?

Link to the tutorial
http://guides.rubyonrails.org/getting_started.html

Here are some extra photos, and my code links. Hope this helps.

The error that you are supposed to get.
http://snag.gy/dmtwH.jpg

The error that I am getting now.
http://snag.gy/gsEUD.jpg

My Code:

app/views/articles/new.html.erb
http://pastebin.com/sAXUhK7v

config/routes.rb
http://pastebin.com/9zVP7i1P

controllers/articles_controller.rb
http://pastebin.com/rGMWjztX

**Comment by kaspth** [comment]
This is a refiling of #19330.

Next time don't open a new issue but comment on the original one. Also as a tip, look into github flavored markdown it supports both images and code, which is easier for both of us because we don't have to open links and you don't have to make them :smile:

Anyway, I'm going to let this one stay open for now and let others have a go. At first glance your code looks correct.

**Comment by endersstocker** [comment]
The error that you are seeing is the result of the form posting back to the original path, */articles/new*, instead of */articles*. You would certainly receive that error if  `, url: articles_path` were absent from **config/routes.rb:1**. When you restart the Rails application server, refresh the form at */articles/new*, and submit, do you still receive this error?

**Comment by itsportspe** [comment]
When I try to restart the server with either `, url: articles_path` or `url: articles_path` in the **config/routes.rb** the server won't start. Also I have no idea what **config/routes.rb:1** is.

The whole point of this post is that the tutorial seems to be incorrect. When I looked to find a way to contact the author, this is where I was sent. That is why I'm posting here. In the future I hope other people wanting to learn won't have same problem as me.

**Comment by adsteel** [comment]
`url: articles_path` or `url: articles_url` needs to be in the form, just like you have it, not in *config/routes.rb*. When I follow the tutorial, and even when I copy-paste your text, everything works as expected for me. If you want to push your app up to github and send a link to the repository, I could take another look.

**Comment by endersstocker** [comment]
I apologize @itsportspe, I meant **app/views/articles/new.html.erb:1**.

**Comment by itsportspe** [comment]
I have restarted the server many times and still get the same error.

**Comment by endersstocker** [comment]
Have you tried submitting the form in another browser, to rule out any caching of the form? Also, can you verify that line 1 of app/views/articles/new.html.erb is currently exactly as you have it in your link: `<%= form_for :article, url: articles_path do |f| %>`. Lastly, when you inspect the HTML at */articles/new*, what is the content of the form tag (the line that starts `<form`)?

**Comment by itsportspe** [comment]
Yes. I can verify that it is exactly the same. http://snag.gy/ACmTk.jpg
Yes. The Cache is cleared. Still the same issue.
Here is my clone. https://github.com/itsportspe/errorRails.git

**Comment by adsteel** [comment]
Your clone works for me with no modifications. When I navigate to `/articles/new` and submit the form, I get `The action 'create' could not be found for ArticlesController`, which is the expected error message. If you're still getting the error `No routes matches [POST] "articles/new"`, it seems like that is a product of your local environment.

**Comment by endersstocker** [comment]
The clone gives the expected error message, `The action 'create' could not be found for ArticlesController`, for me as well.

**Comment by itsportspe** [comment]
Yeah. It looks like something is going on with my environment. Thank you for the help everyone.

**Comment by kaspth** [comment]
I hope you can figure it out, so you can get started with Rails :heart:

**Comment by mnetke2** [comment]
how to set URL in form_for article
