### ISSUE TITLE
image_path looks for images in "images/" instead of "assets/" in production

### ISSUE THREAD

**Issue by jffrymrtn** [rails/rails#19370]
The catch is, some images properly use the "assets/" directory, while some use the wrong "images/" directory.

My images are in the "assets/images" folder and are all in the same subfolder. Confused as to what's going on and changing anything in my production.rb file doesn't change anything.

Thinking it could be a Rails 4 bug, but can anyone confirm?

**Comment by kuldeepaggarwal** [comment]
Thanks for reporting the issue but can you please provide steps to reproduce this bug or create a sample app having this issue?

**Comment by rafaelfranca** [comment]
This is not a bug, unless the image that is using the /images path is a valid image inside the assets folder. Make sure there is no typo in the image name and also that the image is inside the assets folder. Rails only generate /assets url if the image exists in the assets/images folder.
