### ISSUE TITLE
ActiveRecord rails 4.2 it appears you can no longer declare your serialized Hash columns as NOT NULL

### ISSUE THREAD

**Issue by house9** [rails/rails#19394]
I am in the process of upgrading an existing rails app from 4.1.9 to 4.2.1.rc4 and came across some new (unusual) behavior with [serialized attributes](http://api.rubyonrails.org/classes/ActiveRecord/AttributeMethods/Serialization/ClassMethods.html#method-i-serialize) - it appears you can no longer declare your serialized Hash columns as NOT NULL

feel free to close this issue immediately as my 'fix' is to now allow NULL on the serialized columns;
it appears even if the attribute is NULL in the database it will be an empty Hash when accessing the attribute from the active record model

posting this here in case others run into the same issue

--------

ruby 2.1.4p265 (2014-10-27 revision 48166) [x86_64-darwin14.0]
Rails 4.2.0 and 4.2.1.rc4

I created a test repo here: https://github.com/house9/take_a_look_4.2.1.rc4 for reproducing the issue

From the repo:

migration with NOT NULL 

```
class CreateFoos < ActiveRecord::Migration
  def change
    create_table :foos do |t|
      t.string :title, null: false
      t.text :bar, null: false # => NOT NULL
      t.text :baz, null: true

      t.timestamps null: false
    end
  end
end
```

model 

```
class Foo < ActiveRecord::Base
  serialize :bar, Hash
  serialize :baz, Hash
end
```

failing test case

```
  test "saves serialized empty hash" do
    bar = {}
    foo = Foo.new(title: "the-title", bar: bar)
    assert foo.bar == {}
    assert foo.save # BOOM! SQLite3::ConstraintException: NOT NULL constraint failed: foos.bar
  end
```

looking into this more, the object will never be nil (which is good) but the data in the database must be

```
  test "serialized Hash that allows null defaults to empty hash" do
    baz = nil
    foo = Foo.new(title: "the-title", bar: { x: "X"}, baz: baz)
    assert foo.baz == {}
    assert foo.save
    assert foo.baz == {}
    assert foo.reload.baz == {}
  end

```

**Comment by sgrif** [comment]
This is the expected behavior. Thank you for the thorough report. :)
