### ISSUE TITLE
Active Record callbacks with nested values

### ISSUE THREAD

**Issue by pragmaticivan** [rails/rails#19395]
Should Active Record execute after_create more than one time When I save an Object with Nested  Attributes?

ex:

Plan
- accepts_nested_attributes_for :jobs

plan[:jobs_attributes] = [job,job]

The callback `after_create` of plan is executed 3 times, the plan time and 2 more for the jobs.

rails version 4.2

**Comment by radar** [comment]
Do you have an application which can reproduce this problem?

**Comment by imanel** [comment]
Could not confirm. Test used:

**Comment by rafaelfranca** [comment]
Closing until we have reproduction. Thank you for reporting it.

**Comment by imanel** [comment]
@pragmaticivan if you will be able to reproduce using template from above then please reopen.

**Comment by rafaelfranca** [comment]
@imanel right. @pragmaticivan if you can provide a reproduction steps please ask us for reopening.
