### ISSUE TITLE
Rails responding inconsistently with 'transfer-encoding' sometimes and  'content-length' sometimes

### ISSUE THREAD

**Issue by kalpitad** [rails/rails#19392]
When I send the exact same request (with only the Authorization header value changed) to my Rails server, sometimes it sends back `transfer-encoding: chunked` and sometimes it sends back `Content-Length: <number>`. I thought that maybe it had something to do with the response size, but in the example responses whose headers I've pasted below, the data returned in the body is EXACTLY the same. Based on the docs that I read, I thought that `transfer-encoding` was the default now, but I can't seem to understand why `Content-Length` is returned sometimes. If it is indeed unpredictable, is there a way to force it to return one over the other? I'm using Rails version 4.1.7 on Nginx.

    Response #1
    HTTP/1.1 200 OK
    Cache-Control: max-age=0, private, must-revalidate
    Content-Type: application/json; charset=utf-8
    Date: Wed, 18 Mar 2015 00:59:31 GMT
    ETag: "86f277ea63295460d4f3bed9a073eaa2"
    Server: nginx/1.6.2
    Status: 200 OK
    X-Content-Type-Options: nosniff
    X-Frame-Options: SAMEORIGIN
    X-Request-Id: dd36f139-1986-4da6-9645-4438d41e74b0
    X-Runtime: 0.123865
    X-XSS-Protection: 1; mode=block
    transfer-encoding: chunked
    Connection: keep-alive
 
    Request #2
    HTTP/1.1 200 OK
    Cache-Control: max-age=0, private, must-revalidate
    Content-Type: application/json; charset=utf-8
    Date: Wed, 18 Mar 2015 00:59:36 GMT
    ETag: "86f277ea63295460d4f3bed9a073eaa2"
    Server: nginx/1.6.2
    Status: 200 OK
    X-Content-Type-Options: nosniff
    X-Frame-Options: SAMEORIGIN
    X-Request-Id: 0cfd7705-157b-41b5-aa36-739bc6f8302e
    X-Runtime: 0.092672
    X-XSS-Protection: 1; mode=block
    Content-Length: 2234
    Connection: keep-alive

**Comment by rafaelfranca** [comment]
Can you please provide a sample application that reproduces the error?

**Comment by kalpitad** [comment]
OK, let me see how I can pare down my app to show it to you, without exposing any IP. I'll be back...

**Comment by rafaelfranca** [comment]
Just create a new empty application and try to do the minimum setup to reproduce this issue. If can't debug in your application.
