### ISSUE TITLE
Rails 4.2.1 breaks if there is a nil and a string in the default translations

### ISSUE THREAD

**Issue by jcoyne** [rails/rails#19419]
In rails 4.2.0 I could do this:

```ruby
    t(:"try_this", default: [:"how_about.this", nil, "Finally this")
```
and if `:"try_this"` and `:"how_about.this"` are not found in the locale file, then `"Finally this"` would be returned.

In Rails 4.2.1 I get:
```
     ActionView::Template::Error:
       translation missing: en.Finally this
```

**Comment by jcoyne** [comment]
This behavior is documented here: http://guides.rubyonrails.org/i18n.html#defaults

**Comment by rafaelfranca** [comment]
Thanks. I believe it is related with https://github.com/rails/rails/pull/18308 or with the fix of one regression that this PR caused https://github.com/rails/rails/pull/19102.

**Comment by jcoyne** [comment]
Yeah, I think I broke it in https://github.com/rails/rails/commit/90fcfeade632cc32821f695a305ee8b4734d3a56 and I'll try to fix/test this case.

**Comment by jcoyne** [comment]
After doing some bisecting, this error was introduced by 362557e.

**Comment by aprescott** [comment]
I'm wondering why this issue was closed. Is it still considered a regression bug? Was it fixed in a separate PR?

I have a problem that looks to be related to this. We had some code that uses `default: [[]]` because we want the default to be `[]` if nothing is found. This broke in 4.2.1 because 4.2.1 made changes to the way that `default: [[]]` is "unwrapped" to `[]` (because it uses `options.delete` and then re-adds it with `options[:delete]=`).

```ruby
class NestedArrayTest
  include ActionView::Helpers::TranslationHelper

  def translate(key, options = {})
    default = super

    super(key, options.merge(scope: "this.does.not.exist", default: [[]]))
  end
  alias_method :t, :translate
end

class SimpleArrayTest
  include ActionView::Helpers::TranslationHelper

  def translate(key, options = {})
    default = super

    super(key, options.merge(scope: "this.does.not.exist", default: []))
  end
  alias_method :t, :translate
end
```

```ruby
# pre-4.2.1
NestedArrayTest.new.translate("lol") #=> []
SimpleArrayTest.new.translate("lol") #=> translation missing <span>

# 4.2.1
NestedArrayTest.new.translate("lol") #=> translation missing <span>
SimpleArrayTest.new.translate("lol") #=> translation missing <span>
```

**Comment by jcoyne** [comment]
@aprescott see  #19421

**Comment by aprescott** [comment]
Ah, thanks! It looks like my problem still exists. I'll open a PR/issue if it's still broken on `4-2-stable`/`master`.
