### ISSUE TITLE
ActiveJob should allow for custom Argument serializers

### ISSUE THREAD

**Issue by natematykiewicz** [rails/rails#19418]
For objects that don't fall into ActiveJob's current Argument serializers. It would be nice to have a way to define how an object should be serialized/deserialized.

**Comment by rafaelfranca** [comment]
Thank you so much for the issue but we don't take feature request on the issue tracker. We recommend you to try to implement the feature and send us a pull request or if you are in doubt if the feature will be accepts ask in Rails Core mailing list for feedback.

Also, this is already possible, you just need to override serialize_argument and deserialize_argument
