### ISSUE TITLE
When using postgresql on Rails 4.2.1 with data type integer, limit: 8 and array: true the generated schema.rb file does not include the limit: 8

### ISSUE THREAD

**Issue by wallerjake** [rails/rails#19420]
While trying to upgrade to Rails 4.2.1 I discovered an issue with the generation of schema.rb. It appears that when using postgresql as the driver and using the data type integer, array true and a limit the limit does not make it into the schema.rb file. This causes the schema to load with the data type array of integers instead of an array of big integers. This was something that did work prior to rails 4.2.1. I have tested this same pattern out in Rails 4.1.10 and it works good there too.

I have created a self contained script that is able to reproduce this problem. Please see https://gist.github.com/wallerjake/fcc0d55ee6afdce600a6. As you will see the tests do pass under Rails 4.1.10 but do not pass under 4.2.1.

If this is intentional then it would be nice to get the work around as to how I can generate the schema off of the schema.rb using the schema:load rake task.

@sgrif - This is the issue that I mentioned from https://github.com/rails/rails/issues/17935. Please let me know if you need further information.

**Comment by radar** [comment]
@wallerjake Is this still an issue on Rails 4.2.1?
