### ISSUE TITLE
Multi hierarchy query fails

### ISSUE THREAD

**Issue by leifg** [rails/rails#19436]
I recently stumbled upon this behaviour and I would say it's not behaving correctly:

Suppose you have the following hierarchy:

Company has_many Employees
Employee has_many Projects

Say you want to query all projects of a company.

One way to go would be:

    Project.includes(:employee).where(employees: { company: Company.last })

However this particular line throws the following error:

    Company Load (0.3ms)  SELECT  "companies".* FROM "companies"  ORDER BY "companies"."id" DESC LIMIT 1
    SQL (0.7ms)  SELECT "projects"."id" AS t0_r0, "projects"."name" AS t0_r1, "projects"."employee_id" AS t0_r2, "projects"."created_at" AS t0_r3, "projects"."updated_at" AS t0_r4, "employees"."id" AS t1_r0, "employees"."name" AS t1_r1, "employees"."company_id" AS t1_r2, "employees"."created_at" AS t1_r3, "employees"."updated_at" AS t1_r4 FROM "projects" LEFT OUTER JOIN "employees" ON "employees"."id" = "projects"."employee_id" WHERE "employees"."company" = 1
    SQLite3::SQLException: no such column: employees.company: SELECT "projects"."id" AS t0_r0, "projects"."name" AS t0_r1, "projects"."employee_id" AS t0_r2, "projects"."created_at" AS t0_r3, "projects"."updated_at" AS t0_r4, "employees"."id" AS t1_r0, "employees"."name" AS t1_r1, "employees"."company_id" AS t1_r2, "employees"."created_at" AS t1_r3, "employees"."updated_at" AS t1_r4 FROM "projects" LEFT OUTER JOIN "employees" ON "employees"."id" = "projects"."employee_id" WHERE "employees"."company" = 1
    ActiveRecord::StatementInvalid: SQLite3::SQLException: no such column: employees.company: SELECT "projects"."id" AS t0_r0, "projects"."name" AS t0_r1, "projects"."employee_id" AS t0_r2, "projects"."created_at" AS t0_r3, "projects"."updated_at" AS t0_r4, "employees"."id" AS t1_r0, "employees"."name" AS t1_r1, "employees"."company_id" AS t1_r2, "employees"."created_at" AS t1_r3, "employees"."updated_at" AS t1_r4 FROM "projects" LEFT OUTER JOIN "employees" ON "employees"."id" = "projects"."employee_id" WHERE "employees"."company" = 1
            from /Users/leifg/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/sqlite3-1.3.10/lib/sqlite3/database.rb:91:in `initialize'
            from /Users/leifg/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/sqlite3-1.3.10/lib/sqlite3/database.rb:91:in `new'
            from /Users/leifg/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/sqlite3-1.3.10/lib/sqlite3/database.rb:91:in `prepare'
            from /Users/leifg/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/activerecord-4.2.1/lib/active_record/connection_adapters/sqlite3_adapter.rb:296:in `block in exec_query'
            from /Users/leifg/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/activerecord-4.2.1/lib/active_record/connection_adapters/abstract_adapter.rb:473:in `block in log'
            from /Users/leifg/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/activesupport-4.2.1/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
            from /Users/leifg/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/activerecord-4.2.1/lib/active_record/connection_adapters/abstract_adapter.rb:467:in `log'
            from /Users/leifg/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/activerecord-4.2.1/lib/active_record/connection_adapters/sqlite3_adapter.rb:293:in `exec_query'
            from /Users/leifg/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/activerecord-4.2.1/lib/active_record/connection_adapters/abstract/database_statements.rb:347:in `select'
            from /Users/leifg/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/activerecord-4.2.1/lib/active_record/connection_adapters/abstract/database_statements.rb:32:in `select_all'
            from /Users/leifg/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/activerecord-4.2.1/lib/active_record/connection_adapters/abstract/query_cache.rb:70:in `select_all'
            from /Users/leifg/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/activerecord-4.2.1/lib/active_record/relation/finder_methods.rb:368:in `find_with_associations'
            from /Users/leifg/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/activerecord-4.2.1/lib/active_record/relation.rb:638:in `exec_queries'
            from /Users/leifg/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/activerecord-4.2.1/lib/active_record/relation.rb:514:in `load'
            from /Users/leifg/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/activerecord-4.2.1/lib/active_record/relation.rb:243:in `to_a'
            from /Users/leifg/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/activerecord-4.2.1/lib/active_record/relation.rb:629:in `inspect'

Somehow the column "employees.company" is not found (which makes sense, because only the id is stored).

Changing the query like this works:

    Project.includes(:employee).where(employees: { company_id: Company.last })

Is this really how it is supposed to work? I reproduced this on sqlite3 and postgres.

I created a project for this [here](https://github.com/leifg/ar_debug) to reproduce the issue:

    bundle exec rake db:migrate
    bundle exec rake db:seed
    bundle exec rake association:create

**Comment by rafaelfranca** [comment]
Thank you for the issue. Yes, this is how it is supposed to work right now. We may implement a more inteligente query builder but there is no much gain for doing it.

See also #14427 and linked issues.
