### ISSUE TITLE
name attribute being blended into the index name for add_index migration 

### ISSUE THREAD

**Issue by iDiogenes** [rails/rails#19430]
I am using jruby-1.7.19 with rails 4.1.9 and I am getting the following error while running a migration:
```
-- add_index(:ip_addresses, {:column=>[:location_id, :address], :name=>"index_ip_addr_on_location_id_and_address", :unique=>true})
rake aborted!
StandardError: An error has occurred, this and all later migrations canceled:

Index name 'index_ip_addresses_on_column_and_location_id_and_address_and_name_and_index_ip_addr_on_location_id_and_address_and_unique_and_true' on table 'ip_addresses' is too long; the limit is 63
```
As you can see the name option being passed into the migration is not the name being used to create the index. It looks like it is taking my name in adding into the middle of the default index name. Unfortunately, not adding the name at all still makes the index name too long.

**Comment by rafaelfranca** [comment]
Should not the add_index call be the following:

```ruby
add_index(:ip_addresses, [:location_id, :address], :name=>"index_ip_addr_on_location_id_and_address", :unique=>true)
```

See the absent of the `column` key. As explained at http://api.rubyonrails.org/classes/ActiveRecord/ConnectionAdapters/SchemaStatements.html#method-i-add_index

**Comment by iDiogenes** [comment]
That did it, thanks! Sorry, I was doing a copy change with remove_index and when looking at the add_index docs I didn't see the column key was not present.
