### ISSUE TITLE
Error 500, but everything seems to be correct.

### ISSUE THREAD

**Issue by itsportspe** [rails/rails#19458]
I have a rails project that was auto created with a Digital Ocean droplet. It uses nginx and unicorn. I deleted the `index.html.erb` in `home/index`, and later on made a new one. Now everytime I try to view my rails project online I get an error 500 ***we're sorry, but something went wrong.*** I looked at ***/log/production.log*** and this is what I see.
`I, [2015-03-20T08:39:14.324642 #908]  INFO -- : Processing by HomeController#index as HTML`
`I, [2015-03-20T08:39:14.325744 #908]  INFO -- : Completed 500 Internal Server Error in 1ms`
`F, [2015-03-20T08:39:14.329870 #908] FATAL -- : `
`ActionView::MissingTemplate (Missing template home/index, application/index with {:locale=>[:en], :formats=>[:html], :handlers=>[:erb, :builder, :raw, :ruby, :jbuilder, :coffee]}. Searched in:`
  `* "/home/rails/app/views"`
`):`

This is odd because the template isn't missing, and the file permissions look okay.

I've tried everything I can think of even restarting the server with `service nginx restart`

I made a clone for anyone who has time to look at it. https://github.com/itsportspe/railserror500.git

This is running **Ruby 2.0.0p353** with **Rails 4.0.2**

**Comment by teknull** [comment]
I tried pulling your repo and reproducing the error and cannot.  What are your perms on the index.html.erb file?  And the perms on the app directory?

**Comment by itsportspe** [comment]
drwxr-xr-x 8 rails www-data 4096 Dec 20  2013 app
drwxr-xr-x 4 rails www-data 4096 Dec 20  2013 views

views dir
drwxr-xr-x 2 rails www-data 4096 Mar 19 13:21 home
drwxr-xr-x 2 rails www-data 4096 Dec 20  2013 layouts

home dir
-rw-r--r-- 1 rails www-data 700 Dec 20  2013 index.html.erb

**Comment by matthewd** [comment]
You need to restart unicorn, not nginx.

Please use StackOverflow or the mailing list for support questions, where you can get help from the wider community. We prefer to reserve the issue tracker for issues.
