### ISSUE TITLE
Nested association's association is not persisted for new records

### ISSUE THREAD

**Issue by sethvargo** [rails/rails#19466]
This is a fun one :smile: 

```ruby
class Parent < ActiveRecord::Base
  has_many :versions, autosave: true
end
```

```ruby
class Version < ActiveRecord::Base
  belongs_to :parent
end
```

Consider the first request where neither a parent nor a version exist. If the creation of a version is designed to be an upsert (meaning the creation of a version also creates the parent), it makes sense to use the [AutosaveAssociation](http://api.rubyonrails.org/classes/ActiveRecord/AutosaveAssociation.html) here when creating the resource:

```ruby
class SomeController < ApplicationController
  def create
    @parent = Parent.new(name: params[:name])
    @version = @parent.versions.build(
      number: "1",
    )

    # At this point, parent has a reference to the version, but the relationship
    # is not reciprocal:
    #
    #     @parent.versions #=> [#<Version...>]
    #     @version.parent #=> nil
    #

    @parent.save # both the parent and version are saved in a transaction as expected
  end
end
```

This is problematic when trying to use custom validators or performing pre-save callbacks that depends on the relationship to the parent resource inside the version:

```ruby
class MagicalValidator < ActiveModel::Validator
  def validate(record)
    # Inside this method, the record does not have a reference to the parent. However,
    # if you search the object space, you can actually find the parent and verify that one of
    # the children is the same object as `record`.
    record.parent #=> nil
  end
end

class Version < ActiveModel::Base
  validates :version, magical: true
end
```

The workaround is to manually set the association in the `build` step:

```ruby
@version = @parent.versions.build(
  parent: @parent, # This should be assumed from above, but it's not :(
  number: "1",
)
```

Please let me know if I can help any further!

- Rails 4.1.8
- Ruby 2.1

**Comment by mprobber** [comment]
@tsun1215 and I are looking into it!

In the mean time could you replicate the issue in a bug report [template?](https://github.com/rails/rails/tree/master/guides/bug_report_templates)

**Comment by sethvargo** [comment]
Sure!

```ruby
# Activate the gem you are reporting the issue against.
gem 'activerecord', '4.1.8'
require 'active_record'
require 'minitest/autorun'
require 'logger'

# Ensure backward compatibility with Minitest 4
Minitest::Test = MiniTest::Unit::TestCase unless defined?(Minitest::Test)

# This connection will do for database-independent bug reports.
ActiveRecord::Base.establish_connection(adapter: 'sqlite3', database: ':memory:')
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :posts, force: true do |t|
    t.string :name
  end

  create_table :comments, force: true do |t|
    t.integer :post_id
    t.string :number
  end
end

module Blog
  class Post < ActiveRecord::Base
    has_many :comments, autosave: true
  end

  class Comment < ActiveRecord::Base
    belongs_to :post
  end
end

class BugTest < Minitest::Test
  def test_association_stuff
    post = Blog::Post.new(name: "test")

    comment = post.comments.build(
      number: "1",
    )

    refute_nil comment.post
  end
end
```

I narrowed it down to something related to the models being nested inside a module. However, even if I set `class_name` or `inverse_of`, I can't get it to keep a reference to the parent :frowning:.

**Comment by imanel** [comment]
You need to set `inverse_of` on `Post`. This example is passing:

```
# Activate the gem you are reporting the issue against.
gem 'activerecord', '4.2.0'
require 'active_record'
require 'minitest/autorun'
require 'logger'

# Ensure backward compatibility with Minitest 4
Minitest::Test = MiniTest::Unit::TestCase unless defined?(Minitest::Test)

# This connection will do for database-independent bug reports.
ActiveRecord::Base.establish_connection(adapter: 'sqlite3', database: ':memory:')
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :posts, force: true do |t|
    t.string :name
  end

  create_table :comments, force: true do |t|
    t.integer :post_id
    t.string :number
  end
end

module Blog
  class Post < ActiveRecord::Base
    has_many :comments, autosave: true, inverse_of: :post
  end

  class Comment < ActiveRecord::Base
    belongs_to :post
  end
end

class BugTest < Minitest::Test
  def test_association_stuff
    post = Blog::Post.new(name: "test")

    comment = post.comments.build(
      number: "1",
    )

    refute_nil comment.post
  end
end
```

However I'm using 4.2.0 so it might be bug in 4.1.8 - if so then please let me know and I will try to help finding it.

**Comment by sethvargo** [comment]
Hrm. Weird - I can't test it right now, but I definitely tried `inverse_of` and got the same result. I can try your example later.

Even if it's working with `inverse_of`, shouldn't Rails be able to resolve the association name even though it's under a namespace?

**Comment by imanel** [comment]
Did little more testing and it looks like it's fixed in newest versions. Current table looks like this:

| Rails version | `inverse_of` required? |
|-------------------|-------------------------------|
| 4.2.1              | no                                |
| 4.2.0              | yes                              |
| 4.1.10            | no                                |
| 4.1.9              | yes                              |

In all cases `inverse_of` solves problem, but in 4.2.1 and 4.1.10 it's no longer required.

**Comment by rafaelfranca** [comment]
Right. Closing them.

**Comment by sethvargo** [comment]
Cool, thanks folks!
