### ISSUE TITLE
Rendering partial with layout does not generate cache digest for layout template

### ISSUE THREAD

**Issue by matthooks** [rails/rails#19462]
The following code will generate a cache digest for `shared/inner` but not for `shared/outer`.

```erb
<% cache do %>
  <%= render partial: "shared/inner", layout: "shared/outer" %>
<% end %>
```

The workaround is fairly simple:

```erb
<% cache do %>
  <%# Template Dependency: shared/outer %>
  <%= render partial: "shared/inner", layout: "shared/outer" %>
<% end %>
```

However, this seems like something that could be supported out of the box. If someone could point me to the right place to put a failing test case, I'd be more than happy to submit a PR.

**Comment by rafaelfranca** [comment]
Thank you for the report. This should be fixed on master.

**Comment by matthooks** [comment]
Cool -- thanks for the quick response.
