### ISSUE TITLE
Mysql quoted_date precision on Mysql <= 5.6

### ISSUE THREAD

**Issue by phoenixek12** [rails/rails#19468]
Hello,
we have encountered a bug, where on mysql without precision for usec on datetime columns it is rounding. It does not seems as bug, but for example this one:

```ruby
Attendance.update( departure: Time.now.end_of_day )
```
gets after reload Attendance the next day, which is unexpected behaviour. Would it be possible to add formated usecs only if there is a support for it? Or any easy opt, which turns them off on demand?

**Comment by rafaelfranca** [comment]
Which version are you using?

**Comment by rafaelfranca** [comment]
Could you create an reproduction script with this template https://github.com/rails/rails/blob/master/guides/bug_report_templates/active_record_master.rb?

**Comment by pixeltrix** [comment]
@phoenixek12 is it possible that your system timezone and application timezone are out of sync? I've tried to verify it here with MySQL 5.5.30 and it truncates the usec value correctly, but I'm using `Time.current.end_of_day` whereas you're using `Time.now.end_of_day` which may be the source of your problem.

**Comment by phoenixek12** [comment]
Sorry, after a while of digging, I have found that this problem( usecs in final query ) is gone in Rails 4.2.1, where it is truncated correctly, (even though in code I see them - AbstractAdapter), we had locked version 4.2.0, where the problem is.
Sorry :(

**Comment by pixeltrix** [comment]
@phoenixek12 no need to apologise - thanks for coming back to us and glad we've already fixed it :smile:
