### ISSUE TITLE
Engines that interact with app data are not testable

### ISSUE THREAD

**Issue by z5h** [rails/rails#19477]
I have had trouble testing an engine. Specifically the engine augments/interacts with an apps active records, and the tests need to interact with my_engine/test/dummy to ensure things work as expected.

It's not working. I couldn't figure out why.

I have an 11 day-old question with bounty on Stackoverflow with 80 views and no responses. It tells me that one of: rails functionality, or rails documentation, is lacking in this area.

http://stackoverflow.com/questions/28994758/how-can-i-use-fixtures-from-dummy-in-my-rails-engine-tests

**Comment by rafaelfranca** [comment]
Which version are you using? What is the problem that you are getting?

If you think it is an issue please provide ways for reproducing it. If it is just a question you should avoid using the Rails issue tracker since we reserve it just for issues.

**Comment by pixeltrix** [comment]
@z5h if your engine is that tied to the app's models then it shouldn't really be an engine. If you want to test you engine create models in the dummy application to use for testing.

**Comment by z5h** [comment]
@pixeltrix the engine is not tied to the apps models. It is not tied to the business of the app. It augments Activerecord. So it needs to test that augmentation.

**Comment by rafaelfranca** [comment]
@z5h right. I may open it, but before doing so I think it would be great if you provide more information.

**Comment by z5h** [comment]
@rafaelfranca working on it...

**Comment by rafaelfranca** [comment]
:heart:

**Comment by pixeltrix** [comment]
@z5h you can create models in the dummy application to test your Active Record integration with - there should be a models folder inside the generated dummy_app folder/

**Comment by z5h** [comment]
Create engine:

`(~/) > rails -v`
Rails 4.2.1
`(~/) > rails plugin new my_engine --mountable`
...
`(~/)>cd my_engine`
`(~/my_engine) > rake`
`1 runs, 1 assertions, 0 failures, 0 errors, 0 skips`

Create dummy resource, and write a test that uses fixtures.

`(~/my_engine) > cd test/dummy`
`(~/my_engine/test/dummy) > rails generate resource Thing name:string`

note: test/fixtures/things.yml now has 2 default fixtures

`(~/my_engine/test/dummy) > vim test/models/thing_test.rb`
note: make sure to test `assert Thing.all.count > 0, 'no things!'`

Run tests and fail.

`(~/my_engine/test/dummy >cd ../..`

`(~/my_engine) > rake db:migrate`
`(~/my_entime) > rake`
`... Failure: .. no things!`

**Comment by rafaelfranca** [comment]
` test/fixtures/things.yml ` is inside dummy directory or inside the engine directory?

**Comment by z5h** [comment]
`rails generate resource Thing name:string`

is run from dummy directory, and puts fixtures in the subdirectory test/fixtures. So they are in the dummy directory.

**Comment by rafaelfranca** [comment]
By default Rails loads fixtures from the engine directory https://github.com/rails/rails/blob/master/railties/lib/rails/generators/rails/plugin/templates/test/test_helper.rb#L22. If you like to load from the dummy application directory you will need to change the fixtures_path.

**Comment by z5h** [comment]
So my complaint is that it is valid to have a dummy app with fixtures. Separate and at the same time, it is valid to test an engine with its own fixtures.

Basically dummy isn't a good enough dummy. 
Can I add all the fixtures in dummy and run tests from there? There is no test_helper, which seems to indicate I shouldn't run tests from there.

I tried hacking my test helper and tests to get both sets of fixtures loading but failed. Having 2 fixture paths seems to be the problem.

There is nothing to inform me: http://guides.rubyonrails.org/engines.html#functional-tests

**Comment by rafaelfranca** [comment]
The dummy app was made to be an application to run the engine tests. If you want to run tests from the application you need a real application that uses the engine.

**Comment by z5h** [comment]
So if `rails generate` from within dummy put fixtures up in the engine-level fixtures directory, the problem would be solved? 

Then is there a reason for that not to happen?

**Comment by rafaelfranca** [comment]
I don't see any reason for that no happen.

**Comment by z5h** [comment]
So should this be re-opened or should I create another issue?

**Comment by rafaelfranca** [comment]
We don't take feature requests on the issue tracker, because there is no guarantee that they will be implemented and the issue will be just sit here forever. You can now:

1) open a PR if you are comfortable

2) Send an email to Rails Core mailing list, so someone with interest will implement it

**Comment by z5h** [comment]
Got it. Thanks.
