### ISSUE TITLE
serialized hash field of model will not save string output of number_with_delimiter() [rails 3.2.21, possibly later]

### ISSUE THREAD

**Issue by jpwynn** [rails/rails#19486]
Although I use an older version of Rails (3.2.21) I report this bug just in case the bug persists in current versions of Rails, because it seems quite subtle.

An active record field that is a serialized Hash will refuse to save the string version of the output of number_with_delimiter, unless wrapped in String.new. number_as_currency() works fine, making me thing there is something goofy going on in the internals of number_with_delimiter(), or possibly with the serialize code.

for any activerecord model Foo with 
```ruby
serialize :stuff, Hash

f = Foo.create
f.stuff = { a: "aaaa", b: 1111, c: helper.number_with_delimiter(123456) }
=> {:a=>"aaaa", :b=>1111, :c=>"123,456"} # APPEARS OKbut it isnt...
f.save!
f.stuff
=> {:a=>"aaaa", :b=>1111, :c=>123456} # c should be a STRING
```
If on the other hand you wrap it in String.new() it works:
`{ c: String.new(helper.number_with_delimiter(123456)) }`

It is not specific to the console, I ran into this in a model where I needed to save the stringified version of a number with delimiters, eg, "12,345")

**Comment by kuldeepaggarwal** [comment]
It is working on master branch.


```ruby
# comment.rb
class Comment < ActiveRecord::Base
  serialize(:description, Hash)
end
```

![19486](https://cloud.githubusercontent.com/assets/1930730/6796790/099716f8-d21f-11e4-8760-65e2c3138bb4.PNG)
