### ISSUE TITLE
Using accepts_nested_attributes for and :reject_if => :all_blank on deep nesting

### ISSUE THREAD

**Issue by mikemerritt** [rails/rails#19490]
Given the following models.

````ruby
class Pet < ActiveRecord::Base
  has_and_belongs_to_many :owners
  accepts_nested_attributes_for :owners, :reject_if => :all_blank
end

class Owner < ActiveRecord::Base
  has_and_belongs_to_many :pets
  has_one :phone_number
  accepts_nested_attributes_for :phone_number
end

class PhoneNumber < ActiveRecord::Base
  belongs_to :owner
end
````

And a form like this.

````slim
= form_for @pet do |f|
  // pet fields here
  
  = f.fields_for :owners do |o|
    // owner fields here
    
    = o.fields_for :phone_number do |p|
      // phone number fields here
````

When the form is submitted with completely blank owner fields and phone number fields the ````:all_blank```` proc will return false because it checks only the top level owner parameters and it sees the ````phone_number_attributes```` parameter which has the type ````hash:ActionController::Parameters```` which is evaluated as not blank.

It would be helpful if the built in ````:all_blank```` proc looped through all child parameters as well as those of the top level. Of course custom procs can be written but in my opinion this is the expected behavior of ````:all_blank````

**Comment by carlosantoniodasilva** [comment]
Just wondering, shouldn't you have `all_blank` on phone number as well in this scenario? I'm really not sure that the default functionality it provides should be recursive/handle deep nesting.

**Comment by mikemerritt** [comment]
I simplified my example. Having all_blank on the phone number does not matter since when the proc on owner is run to check for blanks it will always return false due to blank? thinking the phone_number_attributes parameter is not blank.



—

**Comment by kuldeepaggarwal** [comment]
@mikemerritt Which Rails version are you using?

**Comment by mikemerritt** [comment]
4.1.6 is the version that I ran into the problem with but it appears ````all_blank```` has remained the same for a long time now.

[This is the offending line](https://github.com/rails/rails/blob/82d12eb9045cba57172ec7cc0786d0f72a8b711f/activerecord/lib/active_record/nested_attributes.rb#L257). When it gets to the nested parameters, ````value```` will be ````ActionController::Parameters```` which means ````value.blank?```` will return false.

**Comment by kuldeepaggarwal** [comment]
@mikemerritt: Actually It's working on my side. 

```rb
param = ActionController::Parameters.new({})
attributes = ActionController::Parameters.new({a: '', b: nil, c: param}) # => {"a"=>"", "b"=>nil, "c"=>{}}
attributes[:c].class # => ActionController::Parameters

REJECT_ALL_BLANK_PROC = proc { |attributes| attributes.all? { |key, value| key == '_destroy' || value.blank? } }

REJECT_ALL_BLANK_PROC.call(attributes) # => true
```

**Comment by mikemerritt** [comment]
ActionController::Parameters.new({}).blank? will return true because it is actually blank, but if you have a key set like this...

````ruby
param = ActionController::Parameters.new({nested_attribute: ''})
````

it will false because that ActionController::Parameters hash is technically not blank but all of the values inside of it are. When using strong parameters the hash will always evaluate as not blank because it has keys in it.

**Comment by kuldeepaggarwal** [comment]
@mikemerritt Can you please provide the input data?

**Comment by kuldeepaggarwal** [comment]
The issue is still present.

**Comment by kuldeepaggarwal** [comment]
It is still present.

**Comment by rafaelfranca** [comment]
I know it is, but we don't have information needed to keep this issue open.

**Comment by kuldeepaggarwal** [comment]
I think we have.

**Comment by siakaramalegos** [comment]
It's definitely still an issue in Rails 4.2.4 - what information do you need to keep this open?

**Comment by danielricecodes** [comment]
I am running into this still with Rails 5.0.5.  Just an FYI to anyone who lands on this issue from the year 2017 :)

**Comment by devkir** [comment]
Still present in Rails 5.2.1

**Comment by Aiderlei** [comment]
Still present in Rails 6.1

**Comment by clickworkorange** [comment]
Hurt my head bumping into this, and I'm on Rails 8.0.1. Spent quite a while trying to figure out why `:all_blank` didn't reject an associated model when all its attributes were empty, ended up using a proc similar to the one suggested by @mikemerritt way back in 2015, which solved the problem. Might be worth looking into.
