### ISSUE TITLE
Looking for Interviewees

### ISSUE THREAD

**Issue by LeninaCrowne** [rails/rails#19509]
Hello!
I’m currently working on my bachelor’s thesis in “leader emergence in open source software projects“. For my research I’m looking for interviewees, preferably 2 people per OSS project: one person with some sort of leadership role and one “normal” project member.
The interviews will take place via Skype over the next couple of weeks and last around half an hour.
Feel free to forward this request to anyone who might be interested and do not hesitate to contact me with any questions you might have.
Thank you so much for your help!
Greetings from Munich,
Katy
PS: My e-mail is katharina.ring@web.de

**Comment by teknull** [comment]
This is not an actual issue.  This should be sent to the mailing list, I think.

**Comment by senny** [comment]
Hey @LeninaCrowne 

We use the issue tracker to keep track of bug reports and discuss patches. Please post to the [rubyonrails-talk mailing list](https://groups.google.com/forum/?fromgroups#!forum/rubyonrails-talk) instead.

You can find more details in our [contribution guidelines](https://github.com/rails/rails/blob/master/CONTRIBUTING.md).
