### ISSUE TITLE
ActiveRecord::DangerousAttributeError: model_name is defined by Active Record.

### ISSUE THREAD

**Issue by NielsKSchjoedt** [rails/rails#19515]
Since the release of rails 4.2 there has been quite a bit of issues with the name of the new `model_name` concept. A few examples.

- https://github.com/rails/rails/issues/18338
- https://github.com/saulabs/reportable/issues/36
- https://github.com/celsodantas/protokoll/issues/16

I recently discovered this too while trying to upgrade a big rails project. Reading that the only real solution is to rename the attribute I have called `model_name` really freaked me out. In this project `model_name` is one of the most important attributes om one of our most important models `Car`. Of  cause a car has a model name right? Renaming it would take carefully renaming more than 2.000 lines of code. Migrating millions of rows in postgresql, millions of saved sessions in memcahed. Millions of serialized objects stored in redis and Hstore. Apart from this it could also potentially completely ruin our google rank (due to many urls using this) etc. etc. 

For this reason I did not do the renaming, instead I had a look at the code in rails. While doing this I discovered that the usage of `model_name` and i found it a bit misleading too.

I think it's an extremely bad idea, 10 years into the development of rails, to suddenly claim a very generic word like `model_name` as part of the public API. This is really asking for trouble.

My suggestion is that we rename it in rails altogether. Something like `NameContainer` or `NameManager` could probably be better. What do you think?

https://github.com/NielsKSchjoedt/rails/commit/ce26b4da2150c62aca0ad9f85b0871f2b5c46e1a

**Comment by NielsKSchjoedt** [comment]
newer mind

**Comment by prakashmurthy** [comment]
Wow, very complicated issue to deal with.

Looks like `model_name` made its appearance in rails code base with this [commit](https://github.com/rails/rails/commit/c1a98209da7422965f5dd4f475603b8a3cc887e4) way back in 2008 as part of rails 2.2.0.

I doubt if anyone would agree to rename it within the rails code base given how long it has been around and how much it has become part of the accepted public API.

**Comment by NielsKSchjoedt** [comment]
Hmmm, true probably. However it's only in rails 4.2 it seems to have become public.

I just feel extremely frustrated that a generic word like `model_name` has suddenly been claimed by rails. If I had another option that would not involve renaming and migration my entire codebase (with no benefit what so ever btw.) then I would be happy to suggestion :-)

**Comment by sgrif** [comment]
It's been public prior to 4.2, it was just changed to be an instance method instead of a class method. Unfortunately this is not a bug, and there's really nothing to be done at this point.
