### ISSUE TITLE
Default URI format is forced over Accept header

### ISSUE THREAD

**Issue by gmile** [rails/rails#19514]
Rails forces format, [specified in default](http://guides.rubyonrails.org/routing.html#defining-defaults) over the one, provided in `Accept` header.

This is somewhat counterintuitive. Semantic meaning of `default` is to yield a _fallback option_ if no other option was provided. However, right now `default` is forced.

Upon digging up the Rails, codebase, it became apparent that Rails [takes the `format` param](https://github.com/rails/rails/blob/master/actionpack/lib/action_dispatch/http/mime_negotiation.rb#L64-L67) as the one having priority over `Accept` header. 

I personally don't think it is correct, but I can't quickly establish anything RFC-like to prove which one should take precedence: the inferred (in my case: default) response content type, or the one provided by the `Accept` header.

I'm going to provide an example app (via a [template](https://github.com/rails/rails/blob/master/guides/bug_report_templates/action_controller_master.rb)) to back my point.

**Comment by kostyl** [comment]
@gmile will it change respond_with behavior?

**Comment by gmile** [comment]
@kostyl hmm, no, I don't think so.

1. you must make sure you always pass in `.json` type with your URLs (do you?),
2. I think browser (actually, some ember middleware) should set `Accept: application/json` automatically, but I'm not certain,
3. tests pass, so I think we're good at least in some way?

**Comment by matthewd** [comment]
The `:format` parameter is, by design, a means of overriding the best guess that would be derived from `Accept`.

So, setting it as a route's default parameter is not something I'd expect to need a lot.

.. what behaviour were you intending to achieve?

**Comment by gmile** [comment]
@matthewd I 100% agree with you.

I'd expect the following:

1. if `Accept: ...` is given – take it on a priority,
2. if `:format` is given – take it,
3. if `:format` is not given – go with default `format` (if specified),
4. if none of 1–3 worked, return 415.

Meanwhile, in our app we've removed `defaults: { format: :json }` to work over this issue.

**Comment by matthewd** [comment]
Yeah, that's not going to happen: browsers (for example) always send `Accept`; the above ordering would entirely break `:format`.

**Comment by gmile** [comment]
@matthewd hmm indeed, now I fully understand your point. Thank you!
