### ISSUE TITLE
Array#to API change in rails 4.2

### ISSUE THREAD

**Issue by dspangen** [rails/rails#19512]
In Rails 4.1 `Array#to(arg)`, when passed a negative argument, would return an empty array.

In rails 4.2 `Array#to(arg)` now returns the first `size - arg` values in the array when `arg` is negative.

This change was not documented. Was it intended?

**Comment by jonatack** [comment]
It was intended. See https://github.com/rails/rails/commit/a31277011814b7bdb6be41a807e14d6bf2852620.

**Comment by rafaelfranca** [comment]
Right. It worked like this but because a performance optimisation, the behavior changed to return an empty array, now it is working as it is intended.
