### ISSUE TITLE
trouble with ordering with conditional

### ISSUE THREAD

**Issue by mathieujobin** [rails/rails#19520]
Hello,

I am having an issue with the relation ordering in active record.

I must admit, I may be doing something unusual, but not that far stretch.

I am using datagrid and I am setting an column order value to something like

```sql
 if ( col1 = val, col1, col2 )
```

but when mysql gets it, it becomes...

```sql
 if ( col1 = val DESC, col1 DESC, col2 DESC)
```

where the first DESC is wrong. I tried to understand the code generating it and I got to that point

https://github.com/rails/rails/blob/master/activerecord/lib/active_record/relation/query_methods.rb#L333-344

but I am a bit loss.

anyone could guide me further down the rabbit hole ? 

cheers,

**Comment by rafaelfranca** [comment]
Could you create an reproduction script with this template https://github.com/rails/rails/blob/master/guides/bug_report_templates/active_record_master.rb?

**Comment by mathieujobin** [comment]
I will give it a try, thanks,

the bug might be in kaminari, I'm not too sure yet, but I will reopen accordingly when I find out.

I found there is a workaround, is to use the the MySQL CASE statement instead of if 

so if ever someone else gets this trouble, in your datagrid report,  you do.

```ruby
   column(:col1,
           #:order => ("if(col1=#{v}, col1, col2)"), ### DOES NOT WORK
           :order => ("(CASE WHEN (col1=#{v}) THEN col1 ELSE col2 END)"),
           :header => 'col1')) do |asset|
```

cheers,
