### ISSUE TITLE
rails generate model Model type:string => warning

### ISSUE THREAD

**Issue by fwininger** [rails/rails#19525]
It's possible to add a warning when you make a rails generate model Model type:string because "type" is a keyword ? So we can't access to the value with the commande Model.type

Thanks
Florian

**Comment by yacinebenz** [comment]
Good idea, but in the meantime use modules to prevent name clashes.

**Comment by nfedyashev** [comment]
It is possible to add this warning although this doesn't look like a bug or something user should be warned about.

There are plenty or Rails apps that uses `type` column for non-STI related purposes.
For example:

    class MyModel < ActiveRecord::Base
      # disable STI
      self.inheritance_column = :_type_disabled
    end

**Comment by rafaelfranca** [comment]
Thank you so much for the issue but we don't take feature request on the issue tracker. We recommend you to try to implement the feature and send us a pull request or if you are in doubt if the feature will be accepts ask in Rails Core mailing list for feedback.
