### ISSUE TITLE
current_page? does not work in views?!

### ISSUE THREAD

**Issue by ThomasAlxDmy** [rails/rails#19529]
https://github.com/rails/rails/blame/606ce3f907cbccd9159bb558c0b57433b42f3975/actionview/lib/action_view/helpers/url_helper.rb#L532

I don't understand why returning false if it's a get request?! How am I supposed to use it in my view then??

**Comment by matthewd** [comment]
Please use the mailing list or StackOverflow for questions/help, where a wider community will be able to help you. We reserve the issues tracker for issues only.

**Comment by ThomasAlxDmy** [comment]
@mattewd if you want I can reopen another bug tracking saying it's a bug ;).
