### ISSUE TITLE
Is this bug?

### ISSUE THREAD

**Issue by ZhangHanDong** [rails/rails#19524]
In Rails4.1

```ruby
user = User.first
user.respond_to?(nil) #=> false
```

In Rails 4.2

```ruby
user = User.first
user.respond_to?(nil)  
#=> TypeError: nil is not a symbol
..../gems/activemodel-4.2.1.rc2/lib/active_model/attribute_methods.rb:450:in `respond_to?'
```

note： the ‘nil’ is just to illustrate the problem.

**Comment by kaspth** [comment]
It's not clear which version you're saying is wrong? If you're saying 4.1 swallows `TypeError`s then I'll have to assume the bug is fixed because you explain which 4.1 release you we're using.

In the future please articulate the problem better in the title and in the description. You're making it really tough for us to figure out what you mean by saying only "is this a bug?" and not giving more detail :heart:

**Comment by ZhangHanDong** [comment]
I'm not sure this is a bug, so  i use only "is this a bug? " for title.

I think  I said sufficient detail cause of the code case。 

Thanks for your reply.

**Comment by kaspth** [comment]
All I'm saying is the more info you can give the easier it'll be for us to help you :smile:

Sorry, I didn't spot 4.2.1.rc2 in there. Release candidates are not considered stable, can you try 4.2.1?

Can you try the latest 4.1 release, 4.1.10, and compare?

Thanks :heart:

**Comment by ZhangHanDong** [comment]
@kaspth 

in Ruby:

```ruby
"hello".respond_to?(nil) 
#=> TypeError: nil is not a symbol  from (pry):1:in `respond_to?'

```
This is not a problem。

The "respond_to?" method in Rails 4.1.2 not the same behavior with  the "respond_to?" in Ruby .

when i use  Rails 4.2.1.rc2 ,  agian, the "respond_to?" method not the same behavior with that one in Rails 4.1.2  。

I just do not understand how do you define the 'respond_to?' behavior for 'nil' in Rails ？

Do you understand what I mean ？

**Comment by kaspth** [comment]
I'm with you. But I need you to try Rails 4.1.10. The reason is, the Rails version you said had an error was released a long time ago and we might have fixed this in later versions.

Do you understand me? :smile:

**Comment by ZhangHanDong** [comment]
@kaspth 

I try it in Rails 4.1.10.   

```ruby
t = Ticket.find 1113313
#=>  Ticket Load (8.3ms)  SELECT  `tickets`.* FROM `tickets`  WHERE `tickets`.`id` = 1113313 LIMIT 1

t.respond_to?(nil) 
#=> false
```

**Comment by ZhangHanDong** [comment]
@kaspth 

How's it going?  is this a bug?

**Comment by rafaelfranca** [comment]
No, it is not a bug. This is how Ruby works. If there is a bug it is on Rails 4.1

```irb
>> class Foo
>>   end
=> nil
>> Foo.respond_to?(nil)
TypeError: nil is not a symbol
	from (irb):3:in `respond_to?'
	from (irb):3
	from /opt/boxen/rbenv/versions/2.0.0-p247/bin/irb:12:in `<main>'
```

**Comment by ZhangHanDong** [comment]
@rafaelfranca 

maybe。
