### ISSUE TITLE
No possible way to provide fallback on video_tag 

### ISSUE THREAD

**Issue by aaron-coding** [rails/rails#19537]
I need to use a fallback option to the video html tag. There is no possible way to provide this using the video_tag method. Maybe have an option fallback: "my_image.png" which creates <img src="my_image.png">.

**Comment by rafaelfranca** [comment]
Thank you so much for the issue but we don't take feature request on the issue tracker. We recommend you to try to implement the feature and send us a pull request or if you are in doubt if the feature will be accepts ask in Rails Core mailing list for feedback.
