### ISSUE TITLE
ActiveRecord postgres adapter doesn't dump integer limit for a array: true

### ISSUE THREAD

**Issue by thesmart** [rails/rails#19532]
Suppose we have a migration like:

```
add_column :posts, :user_ids, :integer, limit: 8, default: [], null: false, array: true
```

The data type is inserted in the DB correctly:

```
<Debug>:  (16.3ms)  ALTER TABLE "posts" ADD "user_ids" bigint[] DEFAULT '{}' NOT NULL
```

However, the schema.rb dump is incorrect because it is missing the limit option that sets use of the BIGINT type:

```
t.integer  "user_ids",              default: [], null: false, array: true
```

I am using activerecord (4.2.0) w/ ActiveRecord::ConnectionAdapters::PostgreSQLAdapter

**Comment by matthewd** [comment]
Fixed #19447
