### ISSUE TITLE
Adding foreign key fails on db:schema:load task for some table names

### ISSUE THREAD

**Issue by ppawlikmb** [rails/rails#19545]
After migrating to 4.2.1 the `db:schema:load` task fails on:
```ruby
add_foreign_key "examples", "waves", name: "examples_wave_id_fk"
```
due to `config/initializers/inflections.rb` with a custom inflection:
```ruby
ActiveSupport::Inflector.inflections do |inflect|
  inflect.irregular 'wave', 'waves'
end
```
not being loaded. Because of that:
```ruby
>> 'waves'.singularize
=> 'wafe' #should be 'wave'
```
and the task crashes with `ActiveRecord::StatementInvalid: PG::UndefinedColumn: ERROR: column "wafe_id" does not exist`.

It was introduced in 4f357ea104b0a69db332f6af17ffef174715bbc7. If this is intentional is there any workaround?

**Comment by senny** [comment]
@ppawlikmb This is a regression caused by the linked PR #18907. I'll look into a revert. Thank you for reporting :yellow_heart:

**Comment by senny** [comment]
@ppawlikmb on a second look 4f357ea104b0a69db332f6af17ffef174715bbc7 only applies to `db/structure.sql` but you are mentioning `db/schema.rb`. How did you identify the offending commit?

**Comment by senny** [comment]
The cause is most likely #17920. 

/cc @sgrif

**Comment by prakashmurthy** [comment]
I was able to reproduce the issue, and confirm that adding back `:environment` dependency for `db:schema:load` fixes the issue.

**Comment by ppawlikmb** [comment]
@senny of course you are right on the cause. I have no idea how could I miss that. :confused:

**Comment by senny** [comment]
@ppawlikmb I reverted the offending commit and backported the revert to `4-2-stable` and `4-1-stable`.

**Comment by ppawlikmb** [comment]
Great! Thanks! :+1:
