### ISSUE TITLE
Page is rendered without action

### ISSUE THREAD

**Issue by steventen** [rails/rails#19552]
Hi, guys

I just found if for example, you have a route set up like this:
  `resources :projects`

Then even though you remove the 'index' action inside of projects controller, you can still visit /projects page. Looks like rails can skip the action method and use the view template to render the page directly.

I'm using `rails 4.2.1` and [here](https://github.com/steventen/render-without-action) is the repo that reproduced this issue. I'm not sure if it's a bug or just a convention I need to aware of? Thanks

**Comment by masterkain** [comment]
it is like that since quite some time now, I believe it's just convention you needs to be aware of, I agree that this behaviour might be surprising to some extent.

**Comment by rafaelfranca** [comment]
Yes, this is a convention called implicit rendering.
