### ISSUE TITLE
Why doesn't Rails automatically permit resource_id for nested attributes.?

### ISSUE THREAD

**Issue by ahmad-alkheat** [rails/rails#19558]
Say I have a Question model that accepts nested attributes for PossibleAnswer, strong parameter would look something like this 

```ruby
params.require(:question).permit(:title, { possible_answers_attributes: [:title, :question_id] } )
```

Is there a reason why Rails requires me to permit the question_id manually? Shouldn't that be done automatically? I was thinking of implementing it but I want to make sure that I should.

**Comment by rafaelfranca** [comment]
Thank you so much for the issue but we don't take feature request on the issue tracker. We recommend you to try to implement the feature and send us a pull request or if you are in doubt if the feature will be accepts ask in Rails Core mailing list for feedback.
