### ISSUE TITLE
Suggestion: Add the line option also for unique indexes

### ISSUE THREAD

**Issue by brunoocasali** [rails/rails#19561]
Hello people!

When you have a migration with unique indexes you need to create a call to add_index method and then write the code like this:

Suppose I want to add a unique to `:email` index on my `users` table:

```ruby
create_table :users do |t|
  t.string :email
  t.string :name

  t.timestamps null: false
end

add_index :users, :email, unique: true # this is the problem!
```

But what about use something like this? :

```ruby
create_table :users do |t|
  t.string :email, index: true, unique: true # removing the unnecessary call to `add_index`
  t.string :name

  t.timestamps null: false
end
```

Thanks in advance!

**Comment by rafaelfranca** [comment]
Thank you so much for the issue but we don't take feature request on the issue tracker. We recommend you to try to implement the feature and send us a pull request or if you are in doubt if the feature will be accepts ask in Rails Core mailing list for feedback.

**Comment by brunoocasali** [comment]
Oh, sorry! Then, yes I'll try it!
