### ISSUE TITLE
ActiveSupport Cache#rerieve_cache_key is inefficient for ActiveRecord Relations

### ISSUE THREAD

**Issue by turlockmike** [rails/rails#19560]
When caching an active record relation, the expand_cache_key method is pretty inefficient

```ruby
  ActiveSupport::Cache.expand_cache_key(@posts, :html)
```

This tries to generate a key for the cache. 
https://github.com/rails/rails/blob/master/activesupport/lib/active_support/cache.rb line 91.

In order to do this, it calls .to_a on the relation, then calls cache_key on each item in the array and mashes it together.

My proposal is that the better solution would be for active record relations (especially long results). The cache key should instead be a list of ids along with the Max updated_at on the relation. 

This will reduce the overall bandwidth of the requests and will in most cases be faster (because of reduced bandwidth). 

I can submit a pull request if no one else is willing to offer one.

**Comment by rafaelfranca** [comment]
Maybe this fix your problem https://github.com/rails/rails/pull/18948?

**Comment by turlockmike** [comment]
#18948 fixes the problem with rendering a lot of partials, but I was more concerned about the bandwidth use of the sql query that ends up fetching values for caching. Say if I want to cache 100 records in an index.json request, right now the cache_key is function is iterating through all the records in that relation, calling cache_key on each object and concatenating it. While this isn't terrible, it means that all of the data is being fetched each time which kinda defeats the purpose of caching. 

In order to get better performance, it would be better if the request in order to fetch the cache keys only fetched the ids and the max updated_at time. 

I think having both would greatly improve caching speed. 

I want to add this class method to ActiveRecord::Integration

```ruby
def cache_key(records)
        if records.is_a?(ActiveRecord::Relation)
          timestamp_name = (['updated_at', 'updated_on'] & column_names)[0]
          if timestamp_name
            "#{model_name.cache_key}/#{records.ids.join(',')}-#{records.maximum(timestamp_name).utc.to_s(cache_time
          else
            "#{model_name.cache_key}/#{records.ids.join(',')}"
          end
        elsif records.is_a?(Array)
          "#{records.map{|record| record.cache_key}.join('/')}"
        end
      end
```

combined with this method on ActiveRecord::Relation

```ruby
def cache_key
  @klass.cache_key(self)
end
```

Would mean that ActiveSupport#retrieve_cache_key could call .cache_key on the relation

```ruby
        def retrieve_cache_key(key)
          case
          when key.respond_to?(:cache_key) then key.cache_key
          when key.is_a?(Array)            then key.map { |element| retrieve_cache_key(element) }.to_param
          when key.respond_to?(:to_a)      then retrieve_cache_key(key.to_a)
          else                                  key.to_param
          end.to_s
        end
```

**Comment by rafaelfranca** [comment]
Yeah, this is somewhat we did with fresh_when/stale https://github.com/rails/rails/pull/18374.

Maybe we can use just the relation options and the maximun updated_at.

Seems a good feature yeah.

I'm closing this issue since we don't take feature requests on the issue tracker but I think you already have information to open a PR.

Thank you and I'm waiting the PR so we can discuss the details of the implementation.

**Comment by kaspth** [comment]
If there's a feature you want in Rails, we recommend sending a pull request.
So take that sample code, write some benchmarks and send a pull request :wink:

I can't guarantee it will be accepted, but since you've already got the code :smile:

--
Kasper

**Comment by turlockmike** [comment]
Thank you very much. I couldn't find information on the process. I'll open a pull request sometime.
