### ISSUE TITLE
Using a form to update individual JSON attributes in a postgres JSON datatype column

### ISSUE THREAD

**Issue by jgrannas** [rails/rails#19563]
I am running into an issue with updating a rails 4.2.1 JSON column in a model.

I have a OrderItem model with an :options column with the postgres json datatype.

I have a form where I am only trying to update two attributes in that JSON column. However, when i run the update action from my controller, it is resetting the entire options column to only the fields in my form rather than just updating the two individual attributes. Is this a bug? I am on Rails 4.2.1 and from what I read this should work, and I can manually update individual attributes in rails console.

In my controller:
```
def update
  @order_item.update(order_item_params)
  respond_with(:update)
end

private 

    def order_item_params
      params.require(:order_item).permit(:product_id, :quantity, options:[:esp, :size])
    end
```

My form:
```
    <%= f.fields_for :options do |option| %>
        <%= option.label :size %>
        <%= option.select :size, options_for_select((5..13), item.options["size"]) %>
        <%= option.select :esp, options_for_select(["yes","no"], item.options["esp"]) %>
    <% end %>
```

```
Form Data
utf8:✓
_method:patch
order_item[quantity]:2
order_item[options][size]:5
order_item[options][esp]:no
```
When that form is submitted it does not update the individual attributes. It resets the entire json column to only the size & esp attributes

In console I can manually update attributes easily...
```
o = OrderItem.last
o.options["esp"] = "yes"
o.save

#PERSISTS!
```

**Comment by rafaelfranca** [comment]
Yes, it is expected. What you are doing is the same as:

```
o = OrderItem.last
o.options = { "esp" => "yes" }
o.save
```

And this will reset the entire json column.

**Comment by jgrannas** [comment]
Ok, thank you. any advice on how to approach a solution to update only the passed in attributes?

**Comment by rafaelfranca** [comment]
You can pass all the options if possible or you can not mass assign them and just set individually, or merge both hashes.

```
@order_item.attribute = order_item_params
@order_item.options.merge!(params[:order_item][:options].slice(:esp, :size))
@order.save
```

```
def order_item_params
      params.require(:order_item).permit(:product_id, :quantity)
    end
```

**Comment by Frank004** [comment]
Did you fin a way to update the individual items form the json? @jgrannas

**Comment by advanced-composites-inc** [comment]
you can pass all attributes but mark the one you don't want to see in your form as 'hidden'
