### ISSUE TITLE
rake db:migrate ignores STEP argument

### ISSUE THREAD

**Issue by mahemoff** [rails/rails#19573]
Not sure if I'm doing something wrong, but it seems that `bundle exec rake db:migrate STEP=2` just runs through all remaining migrations as if the STEP arg is ignored.

`bundle exec rake db:rollback STEP=2` works as expected, rolling back 2 steps.

**Comment by gaurish** [comment]
`db:migrate` doesn't use `STEP` args. it uses version

```
$ bin/rake db:migrate VERSION=20080906120000
```

so this doesn't sound like a bug to me

**Comment by mahemoff** [comment]
I'd seen [it mentioned](http://makandracards.com/makandra/845-migrate-or-revert-only-some-migrations) that STEP is possible for migration and it certainly seems like it should be supported to be consistent with STEP for rollback and redo. I can't see any reason to not include it for migration too.

The most obvious use case is running a migration one step at a time.

**Comment by mahemoff** [comment]
@jonatack Thanks, done.
