### ISSUE TITLE
Rename ActiveRecord::Aggregations to ActiveModel::Aggregations

### ISSUE THREAD

**Issue by pabloh** [rails/rails#19572]
Since it seems is gonna be sticking around for a while it could be a good idea to move the `composed_of` functionality to active_model. Given the fact that is not really persistence related.

**Comment by sgrif** [comment]
We do not accept feature requests on the issue tracker. It is also unlikely that we will accept a pull request moving `composed_of` to Active Model, as we are currently working on a more general purpose replacement for that feature in Rails 5.

**Comment by pabloh** [comment]
@sgrif That's great news!. Is there any branch or PR where you can follow the progress?

**Comment by sgrif** [comment]
Commits made on master
