### ISSUE TITLE
Length validator only working with strings?

### ISSUE THREAD

**Issue by mmontossi** [rails/rails#19570]
I was looking at this:

https://github.com/rails/rails/blob/v4.2.1/activemodel/lib/active_model/validations/length.rb#L64

I notice the length validator only allows strings to be tokenize, there is any reason this is so strict?

I think would pretty nice to allow any object to be tokenize, here is an example:

```ruby
validates_length_of :photos, within: 1..3, tokenizer: ->(photos) { photos.reject(&:marked_for_destruction?) }
```

The only way I know to achieve the same result is using custom validators, which seems to me not too dry and needs a lot more code.

Thanks in advance

**Comment by mmontossi** [comment]
Maybe something like this:

```ruby
def tokenize(value)
  if value.present? && options[:tokenizer]
    options[:tokenizer].call(value)
  else
    value
  end
end
```

**Comment by sgrif** [comment]
The definition of a "tokenizer" is something that processes a string. You can achieve what you're looking for by defining a `photos_not_marked_for_destruction` method, and validating that instead.

**Comment by mmontossi** [comment]
Ok, so if validates_length_of is only for strings, we maybe need a validator for quantity?

Something like this? https://gist.github.com/mmontossi/984f8ebfd50ea843b5f2

And add the errors messages keys:

errors.messages.too_many
errors.messages.too_few
errors.messages.wrong_count

**Comment by sgrif** [comment]
`validates_length_of` is not only for strings, the `tokenizer` option is.

**Comment by mmontossi** [comment]
I know it works with anything that responds to the length method but the errors messages express the idea of number of characters and the tokenizer only work with strings.

Not looks like a validator that is intended to work with strings or expressing the concept of length instead of quantity? To use the length validator to express quantity we need to override the message too.

**Comment by sgrif** [comment]
I agree with you that deeper control over the error messages would be a nice thing to add. However, we do not accept feature requests on the issues tracker. If you'd like to discuss interest in adding a new feature to Rails, please open a thread on the Rails Core mailing list.

**Comment by sgrif** [comment]
For reference, it appears that the `too_short` and `too_long` options are intended to fill the gap that you're looking for.

**Comment by mmontossi** [comment]
I was thinking in something more like:

```ruby
validates_count_of :photos, within: 1..3, selector: ->(photos) { photos.reject(&:marked_for_destruction?) }
```

In which too_short and too_long is used by validates_length_of to express length and validates_count_of uses too_few and too_many to express quantity plus the ability to pass a selector proc to filter.

I was not aware this king of things needs to be post on the mailing list, can you please send me the url of it?

**Comment by sgrif** [comment]
You can find this url, and all other relevant links on the [Rails Contribution Guide](http://guides.rubyonrails.org/contributing_to_ruby_on_rails.html#what-about-feature-requests-questionmark)

**Comment by mmontossi** [comment]
I continued working on this for a project of the company and I notice some caveat, if we use `photos_not_marked_for_destruction` in the `validates_length_of` to solve those cases the `field_error_proc` of action_view will not wrap properly the attributes because probably the attribute in the form will be named `photos` and not `photos_not_marked_for_destruction`.

**Comment by TALlama** [comment]
I know this ship has long since sailed, but the "errors on my new field don't show up on the form" issue is pretty large. We're going to have to add a custom validator to keep this functionality, which seems to have been deprecated for very little reason.

**Comment by TALlama** [comment]
For anyone else who needs it based on this change, a `ByteLengthValidator`:

```rb
class ByteLengthValidator < ActiveModel::EachValidator
  def validate_each(record, attribute, value)
    record.errors.add(attribute, :blank) if !allow_nil? && value.nil?
    
    length = (value.presence || '').bytesize
    record.errors.add(attribute, :too_long, value: value, count: max) if length > max
  end
  
  private
  
  def max
    options[:in]
  end
  
  def allow_nil?
    !!options.fetch(:allow_nil, false)
  end
end
```

**Comment by mmontossi** [comment]
@TALlama I ended up adding this to a gem, you may find it useful: https://github.com/museways/tuning

Take a look at validates_count_of
