### ISSUE TITLE
Enum verb methods

### ISSUE THREAD

**Issue by lukerollans** [rails/rails#19589]
Hello Internet,

I'm currently 6 months in to Rails, so please forgive me if this has already been discussed or implemented in some other form. That being said, I have the below idea.

Consider this `Post` model

```ruby
class Post < ActiveRecord::Base
  enum status: [:draft, :published, :archived]
end
```
As you know, ActiveRecord then goes on to create helper methods such as `draft?`, `published?`, `archived!` etc. I would find it very useful to expose, what I would call, "enum verb methods" where you can check if `status` was being changed to a particular option. For example

```ruby
class Post < ActiveRecord::Base
  enum status: [:draft, :published, :archived]

  def publishing?
    status_changed? && published?
  end
end
```

This would make it easier, with less lines of code, to check the status (or any enum attribute) of a models callback lifecycle.

My use case is that I have a collection of Courses categorised in to different Themes and Industries. In this example, we'll just refer to Themes. I am tracking the `course_count` as a static field to avoid database lookups on the fly, and I believe because of this `published` dependency, `counter_cache` is not an option (as far as I know)

An untested example:

```ruby
class Course < ActiveRecord::Base
  belongs_to :theme
  enum status: [:draft, :published, :archived]

  after_save :update_theme_course_count

  private

  def update_theme_course_count
    if theme.present?
      if publishing?
        theme.course_count += 1
      else
        theme.course_count -= 1 if status_was == "published"
      end
      theme.save if theme.changed?
    end
  end
end
```

Happy to create a patch if this is an original idea and if it's met with enthusiasm.

**Comment by sgrif** [comment]
`attribute_changed?` already accepts a `:from` and `:to` option.

**Comment by al2o3cr** [comment]
The inflections here seem like a challenge - plural/singular is complicated, but past-tense-verb to gerund seems incredibly ambitious. Not to mention that even the example isn't consistent; what should the "verb" form of "draft" be? "drafting"?

**Comment by chancancode** [comment]
Sounds like you might be implementing a [state machine](http://en.m.wikipedia.org/wiki/Finite-state_machine), specially it appears that you need to execute certain logic on a transition. For the most part, it's just a fancy word that makes you feel smart for knowing it, but if you google for that term it might find some more full-featured gems to help you with these kind of things.

Alternatively, you can probably do this with enums too. The default transition is a no-op, but you should be able to change it:

```ruby
def publish!
  Post.transaction do
    # do stuff before
    super
    # do stuff after
  end
end
```

**Comment by lukerollans** [comment]
Thanks for the feedback guys

@sgrif I'm aware that this is possible in a number of ways, including leveraging `attribute_changed?`, the main purpose of this is to allow this kind of logic without needing to write any code.

@al2o3cr Yeah, definitely agree. This would need some work

@chancancode For sure, however as mentioned above, the core behind this idea would be to completely negate the need to write any code. It would be much cleaner than overriding methods and introducing a margin of risk for bugs etc

**Comment by sgrif** [comment]
I didn't mention above, but I'm also strongly opposed to features which would add new instance methods to Active Record without an overwhelmingly convincing use case.

**Comment by lukerollans** [comment]
No probs. Might make a good candidate for a gem. Cheers!
