### ISSUE TITLE
consecutive after_commit callbacks overwrite each other

### ISSUE THREAD

**Issue by f1sherman** [rails/rails#19590]
I noticed that if I have 2 `after_commit` callbacks for the same method in the same class, they overwrite each other. Reproduced this in ActiveRecord 4.2.1.

Test case:
```ruby
require 'active_record'

# Suppress deprecation warning
ActiveRecord::Base.raise_in_transactional_callbacks = true

ActiveRecord::Base.establish_connection adapter: "sqlite3", database: ":memory:"

ActiveRecord::Schema.define do
  self.verbose = false

  create_table :things, :force => true do |t|
    t.string :text
  end
end

class Thing < ActiveRecord::Base
  after_commit :callback, :on => :create
  after_commit :callback, :on => :update, :if => :condition

  def callback
    puts "callback triggered"
  end

  def condition
    true
  end
end

puts "Creating..."
thing = Thing.create! :text => "create"

puts "Updating..."
thing.update_attributes! :text => "update"
```

```shell
$ gem list activerecord

*** LOCAL GEMS ***

activerecord (4.2.1)
$ ruby test.rb
Creating...
Updating...
callback triggered
```

**Comment by arthurnn** [comment]
I would say this is the expected behaviour. If you declare the same callback more than once, rails will use the latest.
The others callback behave like that too right?!

**Comment by f1sherman** [comment]
@arthurnn I don't think this is expected behavior and other callbacks don't seem to behave this way. If I change the above `after_commit` callbacks to `after_save`, both callbacks are triggered.

**Comment by claudiob** [comment]
@f1sherman – If I’m correct, `after_save` does not take an `:on` option.

The `:on` options is defined in [transactions.rb](https://github.com/rails/rails/blob/master/activerecord/lib/active_record/transactions.rb#L218L228), specifically in the [`set_options_for_callbacks!` method](https://github.com/rails/rails/blob/master/activerecord/lib/active_record/transactions.rb#L270) which is not invoked by `after_save`.

Therefore, the reason why you see `"callback triggered"` twice when you use `after_save` is that the `:on` options is ignored, and the code is equivalent to:

```ruby
class Thing < ActiveRecord::Base
  after_save :callback
  after_save :callback, :if => :condition
  ...
```

---

The fact that `after_commit` only prints out `"callback triggered"` is due to the fact that Active Support considers the two callbacks to be **duplicate**. Active Support compares the callback with the [following method](https://github.com/rails/rails/blob/master/activesupport/lib/active_support/callbacks.rb#L385):

```ruby
def matches?(_kind, _filter)
  @kind == _kind && filter == _filter
end
```

In the example above, both callbacks have `kind: after` and `filter: callback`. 
Therefore Active Support understands that with your second `after_commit` you want to overwrite the first one.

I don’t know if this can be called "expected behavior", but I hope I clarified why it’s happening.

**Comment by f1sherman** [comment]
@claudiob thanks for pointing out that `after_save` does not take an `:on` option, I hadn't thought of that. The `after_validation` callback, which does take an `on` option, has the same behavior as `after_commit`. This doesn't feel like expected behavior to me, but it does seem consistent.

**Comment by rafaelfranca** [comment]
It is expected behavior. If you declare the same method twice in a ruby class just the last one is executable, no matter if the arguments are different. Callbacks are just using the same logic, the argument is different but the method name is still the same.

**Comment by f1sherman** [comment]
@rafaelfranca sounds good, thanks for the explanation

**Comment by naw** [comment]
I believe the new aliases `after_create_commit` and `after_update_commit` exacerbate the potential confusion on whether `after_commit` declarations override previous declarations.

For example, in the following code, line 2 will override line 1, and the `:queue_worker` method will only be called for updates.

```ruby
after_create_commit :queue_worker
after_update_commit :queue_worker
```

If you know that these methods are effectively aliases for `after_commit`, with `:on` specified, _and_ if you know that subsequent `after_commit` declarations override former declarations for the same method, then you might readily ascertain that line 2 overrides line 1. Otherwise, this (can be) pretty surprising.

@rafaelfranca Are there any changes in behavior you would be willing to consider to alleviate some of this surprise? If not, perhaps there are some additions we can make to the docs to help clarify this behavior?  Thank you.

xr #22515

**Comment by pmichna** [comment]
I have stumbled upon this problem today. What about a situation like this?

```ruby
after_create_commit :do_something, if: ->(obj) { obj.condition_1? }
after_update_commit :do_something, if: ->(obj) { obj.condition_1? && obj.condition_2? }
```
How should it be solved? Currently `after_create_commit` does not work.

**Comment by thisismydesign** [comment]
The following works:

```ruby
after_create_commit -> { foo }
after_update_commit -> { foo }
```

Conditions can also be applied:
```ruby
after_update_commit -> { foo }, if: :saved_change_to_bar?
after_update_commit -> { foo }, if: -> { saved_change_to_bar?(from: false, to: true) }
```

**Comment by khalilgharbaoui** [comment]
@thisismydesign your solution with multiple line of `after_update_commit` does not when multiple are truthy!
The only this that worked is like the following example:

```
after_update_commit -> { schedule_task },
                      if: -> { saved_change_to_aaa? || saved_change_to_bbb? || saved_change_to_ccc? }
```
this works for either one and/or all of them.

**Comment by malibeg** [comment]
The best for me was to introduce new method signitures for create or update
```
after_create_commit -> { foo_after_create }
after_update_commit -> { foo_after_update }

def foo_after_create
  foo
end
...
```

**Comment by ghiculescu** [comment]
I agree with https://github.com/rails/rails/issues/19590#issuecomment-274209827 that this gotcha is becoming more common now. I think one way to decrease the confusion could be to log a warning in [`remove_duplicates?`](https://github.com/rails/rails/blob/5cfd58bbfb8425ab1931c618d98b649bab059ce6/activesupport/lib/active_support/callbacks.rb#L597), if a duplicate callback is added (and discarded). I can't think of any legitimate reasons to add a duplicate (particularly as they're removed), but having this fail silently is very confusing particularly the first time someone comes across this issue.

**Comment by spuyet** [comment]
The real fix is to have the same behavior than other callbacks, it does not make sense that the `*_commit` callbacks behave differently.

To the people stumbling upon this PR, please add a comment or a like for the follow up, we will see how many people encounter this issue.

**Comment by shahafabileah** [comment]
Adding this little script I used when trying to wrap my brain around this behavior.  In my case I was looking to add multiple `after_create_commit` hooks and I was surprised that they didn't all get called.

I saw commentary elsewhere that the return value from a hook can affect whether subsequent hooks are called, but that does not seem to be the case here.

I also wondered whether doing an `update` in the middle of an `after_create_commit` hook might somehow interrupt the sequence and prevent subsequent create-hooks from running, but that doesn't appear to be the case.

```
class Gadget < ApplicationRecord
  # With this, only set_size_to_4 is called
  # after_create_commit :set_size_to_1, :set_size_to_2_return_true, :set_size_to_3_return_false, :set_size_to_4

  # With this, only set_size_to_4 is called
  # after_create_commit :set_size_to_1
  # after_create_commit :set_size_to_2_return_true
  # after_create_commit :set_size_to_3_return_false
  # after_create_commit :set_size_to_4

  # With this, only set_size_to_1 is called
  # after_create_commit :set_size_to_4
  # after_create_commit :set_size_to_3_return_false
  # after_create_commit :set_size_to_2_return_true
  # after_create_commit :set_size_to_1

  # With this, only set_size_to_1 is called
  # after_create_commit :set_size_to_4, :set_size_to_3_return_false, :set_size_to_2_return_true, :set_size_to_1

  # With this, only set_size_to_4 is called
  # after_create_commit -> { set_size_to_1 }
  # after_create_commit -> { set_size_to_2_return_true }
  # after_create_commit -> { set_size_to_3_return_false }
  # after_create_commit -> { set_size_to_4 }

  # With this, all of them are called
  # after_create :set_size_to_1, :set_size_to_2_return_true, :set_size_to_3_return_false, :set_size_to_4

  # With this, all of them are called
  # after_create :set_size_to_1
  # after_create :set_size_to_2_return_true
  # after_create :set_size_to_3_return_false
  # after_create :set_size_to_4

  # With this, all of them are called
  after_create_commit :do_them_all

  def do_them_all
    set_size_to_1
    set_size_to_2_return_true
    set_size_to_3_return_false
    set_size_to_4
  end

  def set_size_to_1
    puts "Setting size to 1"
    self.update(size: 1)
  end

  def set_size_to_2_return_true
    puts "Setting size to 2"
    self.update(size: 2)
    return true
  end

  def set_size_to_3_return_false
    puts "Setting size to 3"
    self.update(size: 3)
    return false
  end

  def set_size_to_4
    puts "Setting size to 4"
    self.update(size: 4)
  end
end
```

**Comment by ericpowell03** [comment]
I encountered this today and was surprised by the behavior, @spuyet, so would also encourage at least a warning or some other behavior. I think the aliases `after_create_commit` and `after_update_commit` make this especially confusing. I had written something like:

```
after_create_commit :do_something
after_update_commit :do_something, if: :saved_change_to_some_attribute?
```
And that eventually led me here to realize what had happened. My solution was to include a guard clause in the callback, e.g.

```
    def do_something
      return unless saved_change_to_some_attribute? || saved_change_to_id? # to catch newly created records
      
      ...
    end
 ```
 
 This works fine, but I find the original way I had written it to be more intuitive.

**Comment by rbzinnia** [comment]
`And that eventually led me here to realize what had happened`  @ericpowell03 Could you elaborate a bit about what you meant here? I am in a similar situation where my after_create_commit trigger is firing but not the after_update_commit one.
