### ISSUE TITLE
Using a model called "Order" in a doc about ActiveRecord#order is confusing

### ISSUE THREAD

**Issue by heeton** [rails/rails#19591]
Just noticed [this guide](http://guides.rubyonrails.org/active_record_querying.html#order) uses both an `Order` model and talks about the various AR `#order` `#reorder` methods too. Not particularly clear for someone who isn't familiar with what's happening.

**Comment by sgrif** [comment]
Feel free to submit a pull request improving the guide. Otherwise this technically would qualify as a "Feature Request", and should be discussed on the mailing list.
