### ISSUE TITLE
Remove "Considerations when deploying to a subdirectory" section in guides?

### ISSUE THREAD

**Issue by eliotsykes** [rails/rails#19602]
There's a small section in the Configuring guide titled "Considerations when deploying to a subdirectory".

It looks like it is originally contributed in 2013 although it is awaiting more information.

Source: https://github.com/rails/rails/blob/master/guides/source/configuring.md

Section copied from above:
```
Considerations when deploying to a subdirectory

Deploying to a subdirectory in production has implications on various parts of Rails.

development environment:
testing environment:
serving static assets:
asset pipeline:
```

Should the section be removed?

**Comment by rafaelfranca** [comment]
:+1:. Please submit a pull request. Thanks
