### ISSUE TITLE
ActiveJob: serializing a deserialized job loses arguments

### ISSUE THREAD

**Issue by ippeiukai** [rails/rails#19619]
Enqueuing a deserialized job in adapter calls `serialize` again, and that loses the arguments.

```Ruby
class DemoJob < ActiveJob::Base
  def perform(name)
     puts 'hello #{name}!'
  end
end

p ActiveJob::Base.deserialize(DemoJob.new('world').serialize).serialize # => {"job_class"=>"DemoJob", "job_id"=>"#################", "queue_name"=>"default", "arguments"=>[]}
```

Actual deserialization of arguments is currently delayed until `perform_now` (its `deserialize_arguments_if_needed` call), but `serialize` method neither deserializes arguments nor passes on the still deserialized arguments.

I was trying to construct a job that receives another job to be performed conditionally using `ActiveJob::Base#serialize` and `ActiveJob::Base.deserialize` pair.

**Comment by rafaelfranca** [comment]
Hmm, this use case is not supported and you would have to override the `deserialize` method of your job to handle this case.

**Comment by prem-prakash** [comment]
Not good!
