### ISSUE TITLE
[Getting started] Issue with /views/articles/show.html.erb in 'Getting Started with Rails Guide'

### ISSUE THREAD

**Issue by StompyElephant** [rails/rails#19612]
Hi.
In section 6.4 of 'Getting Started with Rails' is the listing of /views/articles/show.html.erb:
```
<p>
  <strong>Title:</strong>
  <%= @article.title %>
</p>
...
<h2>Comments</h2>
<% @article.comments.each do |comment| %>
...
<% end %>
 
<h2>Add a comment:</h2>
<%= form_for([@article, @article.comments.build]) do |f| %>
...
  <p>
    <%= f.submit %>
  </p>
<% end %>
...
```

For some reason, i wanted to move the comments form above the list of comments. The line
    <%= form_for([@article, @article.comments.build]) do |f| %>
adds an extra empty comment to the list. This can even lead nil induced exceptions.

I found that 
    <%= form_for([@article, Comments.new ) do |f| %>
worked better for me.

Thanks for feedback.

**Comment by rafaelfranca** [comment]
it works but don't associate the comment with the article. This only happen because you changed the guides code so I don't think it is a problem.

**Comment by StompyElephant** [comment]
Sorry, i think when you look further down in the same section, [6.4](http://guides.rubyonrails.org/getting_started.html#generating-a-controller) this is, the association is done in app/controllers/comments_controller.rb:

```
class CommentsController < ApplicationController
  def create
    @article = Article.find(params[:article_id])
    @comment = @article.comments.create(comment_params)
    redirect_to article_path(@article)
  end
```
So, article and comment are linked just fine.

The fact remains, that you have an unwanted side effect in the /views/articles/show.html.erb, when you move the form for comments above the list of comments.

Thanks.

**Comment by StompyElephant** [comment]
Sorry, i think when you look further down in the same section, [6.4](http://guides.rubyonrails.org/getting_started.html#generating-a-controller) this is, the association is done in app/controllers/comments_controller.rb:

```
class CommentsController < ApplicationController
  def create
    @article = Article.find(params[:article_id])
    @comment = @article.comments.create(comment_params)
    redirect_to article_path(@article)
  end
```
So, article and comment are linked just fine.

The fact remains, that you have an unwanted side effect in the /views/articles/show.html.erb, when you move the form for comments above the list for comments.

Thanks.

**Comment by rafaelfranca** [comment]
Yeah, if you think it can be improved please send a PR.
