### ISSUE TITLE
Bundling edge rails complains about not finding compatible versions of arel gem

### ISSUE THREAD

**Issue by prakashmurthy** [rails/rails#19624]
Setting `gem 'rails', github: 'rails/rails'` in Gemfile, and installing bundler gives the following output:

    Bundler could not find compatible versions for gem "arel":
      In Gemfile:
        rails (>= 0) ruby depends on
          activerecord (= 5.0.0.alpha) ruby depends on
            arel (= 7.0.0.alpha) ruby
    Could not find gem 'arel (= 7.0.0.alpha) ruby', which is required by gem 'activerecord (= 5.0.0.alpha) ruby', in any of the sources.

**Comment by rafaelfranca** [comment]
Yes. To use Rails edge you must add arel edge to the gemfile too.

**Comment by schneems** [comment]
You must specify edge Ariel as well https://gist.github.com/schneems/e5a7075bca0a5feaca0f
