### ISSUE TITLE
New Bundler `bin/` => `exe/` executables convention

### ISSUE THREAD

**Issue by kirs** [rails/rails#19622]
> To modify an existing gem to use this convention, we only need to move the executable(s), if any, into exe/, and modify the gemspec executables directory to exe/, as above.

Since Bundler [introduced the new executables convention](http://bundler.io/blog/2015/03/20/moving-bins-to-exe.html), should we rename `railties/bin/` into `railties/exe/`?

@indirect

**Comment by indirect** [comment]
I'm in favor of this now that Rails has established the bin/ norm for project scripts.

**Comment by rafaelfranca** [comment]
:+1:

**Comment by wazery** [comment]
I asked Kirill for some issue I can work on, and he recommended me this one, so I will start working on it and will issue a PR referencing it soon.

**Comment by kirs** [comment]
@wazery how it goes?

**Comment by wazery** [comment]
I just got busy with some stuff at work, I will finish it tomorrow at max.

**Comment by wazery** [comment]
@kirs I referenced a PR, I hope that nothing is missing with it.
