### ISSUE TITLE
cattr_ methods not working inside class << self?

### ISSUE THREAD

**Issue by mmontossi** [rails/rails#19639]
I notice if you do something like this:

```ruby
class Sample
  cattr_reader :some_attribute
end
```

Everything works just fine, but if you go like this:

```ruby
class Sample
  class << self
    cattr_reader :some_atribute
  end
end
```

The method alway returns nil, I know it's intended to work directly in the class but it's a common pattern to use attr_reader like this:

```ruby
class Sample
  class << self
    attr_reader :some_attribute
  end
end
```

Maybe would be nicer to make the cattr_ methods behave the same as attr_ just creating only the wrapper around the class variable?

```ruby
  def cattr_reader(attributes)
    attributes.each do |attribute|
      define_method name do
        class_variable_get "@@#{name}"
      end
    end
  end
```

**Comment by kaspth** [comment]
`cattr_reader` wraps the common pattern you're talking about so it doesn't make sense to me to change it.

Why do you want to use `cattr_reader` in the singleton class?

**Comment by mmontossi** [comment]
What I understand after reading the source code at https://github.com/rails/rails/blob/master/activesupport/lib/active_support/core_ext/module/attribute_accessors.rb#L53-L75 is that activesupport is defining two methods at the same time 'self.some_attribute' and 'some_attribute'.

What I consider "strange" is that any of the ruby core methods attr_reader, attr_writer, etc do this considering the context, instance method directly in the class and singleton method inside class << self block.

So it's not following the same behavior as the ruby core methods and I think it's a little bit confusing this way.

Maybe there is a reason behind this?

**Comment by kaspth** [comment]
Well, the methods don't guarantee parity with the Ruby attribute generators.
They generate a class variable accessor with an optional, but on by default, convenience instance accessor.

I don't see anything that needs changing here. Thanks :heart:

**Comment by mmontossi** [comment]
Well if that method is call inside class << self always returns nil, the above code is prove of it and I think that should be consider a bug.

To fix it some refactor would be needed, so I suggested why I think is the best way to do it.

Thanks anyway.

**Comment by kaspth** [comment]
The whole point of the method is to not call it in a singleton class. So there's no bug :wink:

**Comment by mmontossi** [comment]
I just understood, I was thinking about this from another point of view, the intention is using the helper to create both instance and singleton methods simultaneous, not to generate "the class version" of the ruby attr_ methods.

There is any tool in rails to accomplish what I'm looking for?

**Comment by kaspth** [comment]
`cattr_reader` is Rails' tool to accomplish this. I still don't understand why you want to call it in the singleton class?

**Comment by mmontossi** [comment]
Is not a technical reason, I think it feels a little bit "wrong", as we are used to use attr_reader in the singleton or directly in the class depending of what we need maybe the most intuitive way to go would be to follow that pattern.

It's only a suggestion since rails persouit that feeling of "this is the right way to do it", I wanted to share my thoughts about this and see if anyone shares this point of view.

Thanks
