### ISSUE TITLE
302: Moved

### ISSUE THREAD

**Issue by matthewjamesr** [rails/rails#19638]
Hello, when I try to install rails or gem install activejob, I get a error 302 stating the resource has moved temp.

Ideas?

GET http://rubygems.org/quick/Marshal.4.8/activejob-4.2.1.gemspec.rz
302 Moved Temporarily

**Comment by mxhold** [comment]
I don't think this is an issue with Rails.

See: [Why do I get HTTP Response 302 or 301 when installing a gem?](http://help.rubygems.org/kb/rubygems/why-do-i-get-http-response-302-or-301-when-installing-a-gem) and try upgrading rubygems.

**Comment by matthewjamesr** [comment]
Thanks for the response!
