### ISSUE TITLE
Active Record count method throws MySQL error when selecting multiple columns

### ISSUE THREAD

**Issue by matisoffn** [rails/rails#19637]
I ran into this error today/yesterday.  When writing any Active Record query, if multiple columns are selected and the `count` method is called it throws a MySQL syntax error.

`model = Model.find(1).select('model.this, model.that')`

The snippet `model.count` throws a MySQL error because MySQL can not accept multiple columns to count rows.  Active Record should take one column to count the data rather than throwing a MySQL syntax error, or at least throw an error that is more descriptive.

**Comment by al2o3cr** [comment]
"Active Record should take one column to count the data" - this is really tricky to detect with a SQL string as in your example. We'd need to parse the value completely, since `Model.select('some_function_that_takes_multiple_args(col1, col2)')` should still work.

**Comment by matthewd** [comment]
> Active Record should take one column to count the data

The closest approximation we could offer would actually be more like `COUNT(COALESCE(...))`. But making that work would also require far more SQL string parsing & manipulation than is in our remit.

Thus, we must trust that you've asked for what you meant: to even offer our own error, we'd need to somehow work out that the specified `select` value actually contained multiple columns. (And know that your RDBMS hadn't been extended to apply some meaning to that spelling, I suppose.)

If you just want the problem to go away, you're probably looking for `count(:all)`.

Given the above complications, I don't see how we can practically improve the current behaviour. But any suggestions to improve the surrounding documentation are very welcome.
