### ISSUE TITLE
[Rails Guide Error] - i18n Section 2.4

### ISSUE THREAD

**Issue by yuchunc** [rails/rails#19648]
Hi, I think I spotted a small error on the guide, but couldn't find the right place to submit a change.

Under the page about [i18n section 2.4](http://guides.rubyonrails.org/i18n.html#setting-the-locale-from-the-domain-name), the last code container. 

    link_to("Deutsch", "#{APP_CONFIG[:deutsch_website_url]}#{request.env['REQUEST_URI']}")

`request.env['REQUEST_URI']` actually produced the full url instead of just the path. It should be replace with `request.evn['PATH_INFO']`, and look something like this.

    link_to("Deutsch", "#{APP_CONFIG[:deutsch_website_url]}#{request.env['PATH_INFO']}")

Cheers.

**Comment by simi** [comment]
@yuchunc check https://github.com/rails/rails/blob/191facc857bb4fb52078fb544c6bc1613a81cc80/guides/source/i18n.md and please read https://github.com/rails/rails/blob/master/CONTRIBUTING.md before creating GH issue.

> We only accept bug reports and pull requests on GitHub.
> 
* If you have a question about how to use Ruby on Rails, please [ask the rubyonrails-talk mailing list](https://groups.google.com/forum/?fromgroups#!forum/rubyonrails-talk).

**Comment by matthewd** [comment]
@simi :question: 

> We only accept bug reports and pull requests on GitHub

+

> Hi, I think I spotted a small error on the guide

.. seems legit to me?

**Comment by meinac** [comment]
@yuchunc thanks for reporting. I've created a pull request for this issue.

**Comment by simi** [comment]
I was probably a little confused @matthewd. Sorry @yuchunc. :bouquet:

**Comment by yuchunc** [comment]
@Simi It's cool, small as it is, I'm just thrill to know my first contribution to rails is legit. = ) 

TD;IL The guide exist in the gem.

**Comment by arthurnn** [comment]
merged https://github.com/rails/rails/pull/19650, which fixes this.
Thanks @meinac for the PR, and @yuchunc for spotting the issue.
:heart:
