### ISSUE TITLE
Scaffold creates input for ids

### ISSUE THREAD

**Issue by AmitJoki** [rails/rails#19658]
I think it's bad idea as end users don't know what their ids are, also it can be easily manipulated. 

When I do

`rails g scaffold Post user:references`

The `_form.html.erb` contains

```
<div class="field">
    <%= f.label :user_id %><br>
    <%= f.text_field :user_id %>
</div>
```

Basically, shouldn't this be handled in a more secure way, inside code?

**Comment by pixeltrix** [comment]
Hmm, I don't think they should be hidden - perhaps it should generate a select with the list of users?

**Comment by rafaelfranca** [comment]
Yeah, there are a lot of possible solutions but I don't think it is up to the framework to take one of them on this case. Scaffold os just initial code, that can end up in production I know, but it should not be put in production without review. 

That said I think the best solution is keep it this way.

**Comment by pixeltrix** [comment]
Agree with @rafaelfranca that scaffold generator is just initial code and it's not an application builder so closing the ticket.
