### ISSUE TITLE
time_zone_select doesn't support DST

### ISSUE THREAD

**Issue by lifeiscontent** [rails/rails#19653]
I can't seem to find any information regarding the issue I'm currently seeing.

from what it looks like, the time_zone_select doesn't take into account for Daylight Savings Time.

if I select `Pacific Time (US & Canada)` it should set the time_zone to -7 currently. not -8 (which is does)

is there a way to tell the time_zone_select to be aware of DST?

**Comment by matthewd** [comment]
Please use the mailing list or StackOverflow for questions/help, where a wider community will be able to help you. We reserve the issues tracker for issues only.
