### ISSUE TITLE
active_record_callbacks and active_record_validations mismatching on http://guides.rubyonrails.org/

### ISSUE THREAD

**Issue by sselvamani22** [rails/rails#19656]
When I goes http://guides.rubyonrails.org/active_record_callbacks.html#running-callbacks here I can see `decrement!` comes under `Running Callbacks`. But http://guides.rubyonrails.org/active_record_validations.html#skipping-validations here It also comes under `skipping-validations`. Same as `increment!` and `update_attribute`

**Comment by rafaelfranca** [comment]
The information is correct. `decrement!` runs the callbacks but skip validations. I can't see anything wrong there.
