### ISSUE TITLE
_changed? returns inconsistent results on attributes serialized as Array

### ISSUE THREAD

**Issue by Hirurg103** [rails/rails#19664]
```ruby
class User < ActiveRecord::Base
  serialize :tabs, Array
end

u = User.create name: 'Jane', tabs: [1, 2]
u.tabs.delete 1
u.tabs_changed?
=> true
u.tabs.delete 2
u.tabs_changed?
=> nil
```

**Comment by Hirurg103** [comment]
I forgot to mention that this issue is reproducible on Rails 4.2.1

**Comment by matthewd** [comment]
This sounds like #19467. Can you confirm it's fixed on `4-2-stable`?

**Comment by DNNX** [comment]
@Hirurg103 and I are working on the same codebase currently, so I can answer for him while he's unavailable. 

I have just tried the 4-2-stable branch (which happens to be at bf535c31d275a40cdd2854369262d9482a4ec5ec at the moment), and I can confirm that the bug is fixed on 4-2-stable.

```
u = User.create tabs: [1, 2]
u.tabs.delete 1
u.tabs_changed?
=> true
u.tabs.delete 2
u.tabs_changed?
=> true
```

**Comment by kaspth** [comment]
@DNNX @Hirurg103 thanks guys and good luck with your codebase :smile:
