### ISSUE TITLE
Rails uses one ID for database

### ISSUE THREAD

**Issue by Frank2016** [rails/rails#19669]
HI,

I am a beginner for Rails. I just studied the GUIDE and did some exercises (https://www.railstutorial.org/book). However I have one concern. Rails uses ONE ID (usually is ROOT) to do everything on database, such as DB migration, application accesses database, etc. This architecture raises a security concern, especially the cyber attack is happening so often nowadays. Although RAILS has strong parameters feature but once a hacker is hacking into database, hacker has total control on the database. Is a way to use one ID for database migration (i.e. database schema owner) and another ID for application access (to database)? The ID for application to access database should have limited privileges.

**Comment by kaspth** [comment]
Thanks for filing, but we reserve the issue tracker for actual bugs. Please use StackOverflow or the rubyonrails-talk mailing list where a wider community will be able to help you.

Good luck :heart:

**Comment by Frank2016** [comment]
This is a Rails architecture issue. No one else (except Rails users) will be interested in this topic.

**Comment by rafaelfranca** [comment]
Rails doesn't disallow you to change the database users for migration and application access. You can do it easily, but our default is to use the same user. It is not as secure as splitting permissions, but it is sufficient secure.

**Comment by Frank2016** [comment]
Hi, rafaelfranca:

Would you mind sharing how to change the database users for migration and application access?

**Comment by matthewd** [comment]
> Please use StackOverflow or the rubyonrails-talk mailing list where a wider community will be able to help you.
