### ISSUE TITLE
Rails 4.2.1 not routing HEAD requests to mounted Rack applications

### ISSUE THREAD

**Issue by pbyrne** [rails/rails#19673]
`HEAD` requests to Rack applications mounted in a Rails 4.2.1 app are serving 404's. `HEAD` requests to other routes in the application get processed identically to `GET` requests, as expected; in Rails 4.1.10 and earlier did the same for these mounted Rack apps. I have not tested whether Rails 4.2.0 is affected by this.

I've created a demo app which demonstrates the problem: https://github.com/pbyrne/routing_error_demo.

---------

A normal `GET` goes through to the mounted Rack app.

```
$ curl -v http://0.0.0.0:3000/resque/overview > /dev/null
* Hostname was NOT found in DNS cache
*   Trying 0.0.0.0...
* Connected to 0.0.0.0 (127.0.0.1) port 3000 (#0)
> GET /resque/overview HTTP/1.1
> User-Agent: curl/7.37.1
> Host: 0.0.0.0:3000
> Accept: */*
> 
< HTTP/1.1 200 OK 
< Content-Type: text/html;charset=utf-8
< Cache-Control: max-age=0, private, must-revalidate
< Content-Length: 2081
< X-Xss-Protection: 1; mode=block
< X-Content-Type-Options: nosniff
< X-Frame-Options: SAMEORIGIN
< Etag: W/"8fd8b9c6721e2a1d13b815eefa3c6cb4"
< X-Request-Id: 7b82c221-f038-4e13-8894-dd65f69aebf3
< X-Runtime: 0.012765
* Server WEBrick/1.3.1 (Ruby/2.1.5/2014-11-13) is not blacklisted
< Server: WEBrick/1.3.1 (Ruby/2.1.5/2014-11-13)
< Date: Mon, 06 Apr 2015 21:18:04 GMT
< Connection: Keep-Alive
< 
{ [data not shown]
* Connection #0 to host 0.0.0.0 left intact
```

Whereas switching to a `HEAD` request (here, using `curl`'s `-I` flag, but `-XHEAD` does the trick just as well), `ActionController::RoutingError (No route matches [HEAD] "/resque/overview")` gets logged.

```
$ curl -vI http://0.0.0.0:3000/resque/overview > /dev/null
* Hostname was NOT found in DNS cache
*   Trying 0.0.0.0...
* Connected to 0.0.0.0 (127.0.0.1) port 3000 (#0)
> HEAD /resque/overview HTTP/1.1
> User-Agent: curl/7.37.1
> Host: 0.0.0.0:3000
> Accept: */*
> 
< HTTP/1.1 404 Not Found 
< Content-Type: text/html; charset=utf-8
< Content-Length: 34831
< X-Request-Id: ce75953d-9b8a-41b7-9b81-67bf59900ff8
< X-Runtime: 0.069064
* Server WEBrick/1.3.1 (Ruby/2.1.5/2014-11-13) is not blacklisted
< Server: WEBrick/1.3.1 (Ruby/2.1.5/2014-11-13)
< Date: Mon, 06 Apr 2015 21:18:13 GMT
< Connection: Keep-Alive
< 
* Connection #0 to host 0.0.0.0 left intact
```

This initially came up in https://github.com/sportngin/okcomputer/issues/53 regarding a Rails Engine. Upon further review, this occurs with other Rack applications mounted into a Rails 4.2.1 app, like Resque's web component and MailView's mail previewer, so it doesn't appear to be a problem with the underlying apps which are being mounted. 

Please let me know if I'm missing something or misunderstanding something with routing of `HEAD` requests. I took a quick spin through open and closed issues to see if this had already been reported, and I was unable to find anything.

**Comment by rafaelfranca** [comment]
Thank you for the report. This is a dup of https://github.com/rails/rails/pull/19431. Could you check if that PR fix the issue for you?

**Comment by pbyrne** [comment]
Dangit. I looked at that issue, but it didn't seem to be the same thing. Turns out I was wrong. https://github.com/rails/rails/pull/19431 totally fixes this bug. Thanks!
