### ISSUE TITLE
In iterlation, '#'(String) is gone

### ISSUE THREAD

**Issue by hiphapis** [rails/rails#19676]
field `color` is hex code. ex) `#123123`
```erb
<% Product.all.each do |product| %>
  <% byebug %>
  <h4 style="background-color: <%= product.color # first called %>; color: <%= text_color_by_bg(product.color) %>"><%= product.name %></h4>
  <ul class="legend">
    <% product.options.each do |option| %>
      <li style="background-color: <%= option.color %>; color: <%= text_color_by_bg(option.color) %>; border-bottom-color: <%= product.color # second called %>">[<%= option.code %>] <%= option.name %></li>
    <% end %>
  </ul>
<% end %>
```
when first called return correct value. `#123123`
but second called removed `#`. so return value is `123123`
i confirmed by `byebug`

i'm not sure. is from `ruby`? or `rails`?
if you have any idea plz tell me.

ENV.
ruby: 2.2.1p85 (2015-02-26 revision 49769) [x86_64-darwin14] ... installed by rbenv
rails: 4.2.1

**Comment by matthewd** [comment]
Please use the mailing list or StackOverflow for questions/help, where a wider community will be able to help you. We reserve the issues tracker for issues only.

**Comment by matthewd** [comment]
(when you do, you should include the definition of `text_color_by_bg` -- the problem is probably in there)

**Comment by hiphapis** [comment]
aha. my thought it's bug. so i written here. sorry! :)
