### ISSUE TITLE
ActiveRecord postgresql tests are failing

### ISSUE THREAD

**Issue by meinac** [rails/rails#19681]
Is there anyone encountered with this problem?
I'm working with rails-dev-box. These tests fails on local machine but passes on travis.
```
1) Failure:
SchemaDumperTest#test_types_line_up [/vagrant/rails/rails/activerecord/test/cases/schema_dumper_test.rb:81]:
Expected: 1
  Actual: 0


  2) Failure:
SchemaTest#test_schema_names [/vagrant/rails/rails/activerecord/test/cases/adapters/postgresql/schema_test.rb:92]:
--- expected
+++ actual
@@ -1 +1 @@
-["public", "test_schema", "test_schema2"]
+["public", "schema_1", "test_schema", "test_schema2"]
```

**Comment by matthewd** [comment]
Please use the mailing list or StackOverflow for questions/help, where a wider community will be able to help you. We reserve the issues tracker for issues only.

**Comment by meinac** [comment]
@matthewd I thought that this is an issue about activerecord. This is why I opened this issue here.
