### ISSUE TITLE
set_owner_attributes and nullify_owner_attributes not symmetric on has_one relation

### ISSUE THREAD

**Issue by trcarden** [rails/rails#19697]
I am not sure if this is a proper bug but it seems to me that in has_one_association.rb that the nullify_owner_attributes should clear out the "type" attribute as well. You can see in association.rb that the set_owner_attributes will set the type if "as" is defined.

**Comment by rafaelfranca** [comment]
You need to give us more information on how to reproduce this issue, otherwise there is nothing we can do. Please read CONTRIBUTING.md file for more information about creating bug reports. Thanks!
