### ISSUE TITLE
form_for helper arguments: symbols vs instance variables.

### ISSUE THREAD

**Issue by lakesare** [rails/rails#19699]
`fields_for`does't act the same way as it would with `@post` instead of `:post` as `form_for` argument (it will act as if it didn't recognize :comments association), is it done on purpose? 

    <% @post = Post.find(1) %>

    <%= form_for :post do |f| %>
      <%= f.fields_for :comments do |ff| %>
        <%= ff.text_field :body %>
      <%- end -%>
    <%- end -%>

    post has_many :comments, post accepts_nested_attributes_for :comments. comment belongs_to :post.

Here are the relevant docs: http://apidock.com/rails/v4.1.8/ActionView/Helpers/FormHelper/form_for and code https://github.com/rails/rails/blob/master/actionview/lib/action_view/helpers/form_helper.rb.
We should probably change this behaviour or describe it in the docs?
Why do we need this slightly different behaviour in `form_for` for symbols and instance variables at all? Is there a use case?

**Comment by rafaelfranca** [comment]
Could you explain better the problem that you have. A example application reproducing the problem would be great.

Thanks

**Comment by lakesare** [comment]
https://github.com/lakesare/rails_example/blob/master/app/views/posts/edit.html.erb here it is. 
In brief, my problem is that `form_for :post` doesn't understand `fields_for :comments` and in general has   confusing and useless (?) behaviour.

**Comment by meinac** [comment]
I've created a pull request which solves this problem.

**Comment by carlosantoniodasilva** [comment]
I'd recommend against using a symbol in `form_for` if you are actually referencing an instance variable, I think that's confusing and we should move away from it, just pass the variable since you have it at hand.

@rafaelfranca wdyt about deprecating this functionality?

**Comment by meinac** [comment]
I agree with you. IMHO giving this as a feature is error prone and too much magic.

**Comment by derekprior** [comment]
Sounds like this one is good to close?

**Comment by meinac** [comment]
There is a question to @rafaelfranca . We are still waiting response from him.

**Comment by rafaelfranca** [comment]
:+1: about deprecating. I always wanted to do.
