### ISSUE TITLE
Why Are Dates Not Supported As Argument Types for ActiveJob?

### ISSUE THREAD

**Issue by alexwilkinson** [rails/rails#19696]
It seems like a reasonable type for the white list. Just wanted to see whether there was any reason in particular why they aren't currently supported, and whether there are plans to do so. We currently store dates in our delayed jobs, and we wouldn't want there to be a discrepancy between Date.current as it was called when the job is enqueued and as it was called when the job's perform method is called.

**Comment by al2o3cr** [comment]
Many of the job backends serialize the arguments as a JSON object, so I'm guessing the whitelist blocks everything but classes that can be cleanly round-tripped via `JSON.dump` and `JSON.load`.

**Comment by alexwilkinson** [comment]
That makes sense. We can probably just convert to and from iso ourselves.

**Comment by rafaelfranca** [comment]
Please use the mailing list or StackOverflow for questions/help, where a wider community will be able to help you. We reserve the issues tracker for issues only.
