### ISSUE TITLE
Regression in ActiveRecord::AttributeAssignment (multiparameter attributes)

### ISSUE THREAD

**Issue by kirs** [rails/rails#19704]
Here is the sample script:

```ruby
require 'bundler/setup'
require 'active_record'

conn = { adapter: 'postgresql', database: 'activerecord_unittest' }
ActiveRecord::Base.establish_connection(conn)

ActiveRecord::Schema.define do
  create_table :accounts, force: true do |t|
    t.string  :name
    t.timestamps null: false
  end
end

class Account < ActiveRecord::Base
end

acc = Account.create!(name: "demo")
puts "initial name: "acc.name.inspect

# Try to set multiple params to non-multiple field
acc.attributes = {
  'name(1)' => 'John',
  'name(2)' => 'Doe'
}
puts acc.inspect
puts "name: #{acc.name.inspect}"

acc.reload
puts acc.inspect
puts "name: #{acc.name.inspect}"

acc = Account.last
puts acc.inspect
puts "name: #{acc.name.inspect}"

```

Under `4-1-stable` it raises an exception as expected:
```
1 error(s) on assignment of multiparameter attributes [error on assignment ["John", "Doe"] to name (wrong number of arguments (2 for 0..1))] (ActiveRecord::MultiparameterAssignmentErrors)
```

Basically, Rails can't assign multiple attributes on non-multiple attribute.

But under `4-2-stable` it doesn't raise an exception and it keeps assigned multiple values on `name` field even after `reload`.

Here is the script output under 4-2-stable:

```
initial: name: fff
#<Account id: 1, name: nil, created_at: "2015-04-09 08:51:39", updated_at: "2015-04-09 08:51:39">
name: {1=>"John", 2=>"Doe"}

#<Account id: 1, name: nil, created_at: "2015-04-09 08:51:39", updated_at: "2015-04-09 08:51:39">
name: {1=>"John", 2=>"Doe"} # can't be reset even after reload!

# name can be reset only after find(1)
#<Account id: 1, name: nil, created_at: "2015-04-09 08:51:39", updated_at: "2015-04-09 08:51:39">
name: nil
```

I believe the regression happened after 631707a572fe14f3bbea2779cc97fcc581048d62 commit.
/cc @sgrif @rafaelfranca

**Comment by sgrif** [comment]
It definitely has nothing to do with the linked commit, since that only affects mastet

**Comment by kirs** [comment]
Sorry, my fault. I couldn't find the source of regression yet.

**Comment by sgrif** [comment]
The change in behavior is a combination of 36e9be852, and the fact that string columns no longer have a `klass` (which I believe we've removed entirely at this point).

The current behavior on 4-2-stable is not as you've described it, it's what I'd expect. The hash is cast to a string. `.reload` works properly. (Note: The script you provided had a syntax error, that might be the cause of the difference in output here). I'd say that assigning multiparameter values to a non-multiparameter column constitutes as "undefined behavior", so this is not a regression.
