### ISSUE TITLE
ActionMailer rendering duplicate Mail Parts using format block

### ISSUE THREAD

**Issue by erolms** [rails/rails#19707]
I am composing an email as a calendar invitation to an event using ActionMailer (Version 4.2.0) and Icalendar gem for the Calendar part.

The Email is composed as multipart/altenative email containing three parts - text/plain, text/html and text/calendar. I'm using following code to create and send the invitation:
```ruby
include ERB::Util

class NotificationMailer < ApplicationMailer
  default from: 'some@email.com'

  def tech_bridge(recipients, subject, ical, bridge, bridge_url)
    @bridge = bridge
    @bridge_url = html_escape(bridge_url)
 
    ical_part = Mail::Part.new do
      content_type 'text/calendar; charset=UTF-8; method=REQUEST'
      body ical
    end
 
    cnt_type = 'multipart/alternative;' + "\n" + 'boundary="' + mail.body.boundary.to_s + '"'
    mail.charset = 'UTF-8'
    mail.add_part(ical_part)
 
    mail(to: recipients, subject: subject, content_type: cnt_type) do |format|
      format.text(charset: 'UTF-8')
      format.html(charset: 'UTF-8')
    end
  end
end
```
This code would produce five (5) email Parts: 2 x text/plain, 2 x text/html and 1 x text/calendar. Duplicate text and html rendering can be seen in the logs too:
```
[ActiveJob] [ActionMailer::DeliveryJob] [263ed437-e398-4d83-a7f7-853c8e259322]   Rendered notification_mailer/tech_bridge.html.erb within layouts/mailer (0.3ms)
[ActiveJob] [ActionMailer::DeliveryJob] [263ed437-e398-4d83-a7f7-853c8e259322]   Rendered notification_mailer/tech_bridge.text.erb within layouts/mailer (0.1ms)
[ActiveJob] [ActionMailer::DeliveryJob] [263ed437-e398-4d83-a7f7-853c8e259322]   Rendered notification_mailer/tech_bridge.text.erb within layouts/mailer (0.6ms)
[ActiveJob] [ActionMailer::DeliveryJob] [263ed437-e398-4d83-a7f7-853c8e259322]   Rendered notification_mailer/tech_bridge.html.erb within layouts/mailer (0.1ms)
[ActiveJob] [ActionMailer::DeliveryJob] [263ed437-e398-4d83-a7f7-853c8e259322]
NotificationMailer#tech_bridge: processed outbound mail in 23.7ms
```
Email with this content is being processed well by Gmail but reading it with Microsoft Outlook does not produce desired result - the email will be displayed as HTML email and Calendar Invitation is not to be seen.

I tried circumventing the double rendered parts by renaming the view templates into something else and then using the `format.html { render 'other_template' }` trick. This did not work at all as mail was requiring the templates to be present:
```
Missing template notification_mailer/tech_bridge with "mailer". Searched in:
  * "notification_mailer"
```
After checking the Issue #2686 I came up with the workaround for my problem. I created another method that selects the three required parts of an email, composes a new one and replaces @_message with it. With newly rearranged mail message Outlook is properly displaying the invitation request to the end user. This method is called at the end of the tech_bridge one.
```ruby
  def fix_multipart_mail
    mail = Mail.new
 
    txt = Mail::Part.new
    txt = @_message.parts.find { |p| p.content_type.match 'plain' }
    mail.add_part txt
 
    html = Mail::Part.new
    html = @_message.parts.find { |p| p.content_type.match 'html' }
    mail.add_part html
 
    cal = Mail::Part.new
    cal = @_message.parts.find { |p| p.content_type.match 'calendar' }
    mail.add_part cal
 
    mail.header = @_message.header.to_s
    mail.content_type = 'multipart/alternative;' + "\n" + 'boundary="' + mail.body.boundary.to_s + '"'
    mail.charset = 'UTF-8'
 
    @_message = mail
    wrap_delivery_behavior!(delivery_method.to_sym)
  end
```
I cannot tell whether this issue is ActionMailer or ActionPack (render) related but it is pretty much annoying. :unamused:

**Comment by rafaelfranca** [comment]
You are calling `mail` inside your method 4 times. In the first three just one is rendered, but in the last one it will render again because you passed the block.

Does this fix your problem?

```ruby
  def tech_bridge(recipients, subject, ical, bridge, bridge_url)
    @bridge = bridge
    @bridge_url = html_escape(bridge_url)

    ical_part = Mail::Part.new do
      content_type 'text/calendar; charset=UTF-8; method=REQUEST'
      body ical
    end

    message = mail(to: recipients, subject: subject) do |format|
       format.text(charset: 'UTF-8')
       format.html(charset: 'UTF-8')
    end

    message.content_type = 'multipart/alternative;' + "\n" + 'boundary="' + message.body.boundary.to_s + '"'
    message.charset = 'UTF-8'
    message.add_part(ical_part)

    message
  end
```

**Comment by erolms** [comment]
I refactored the code as you suggested, that did the trick. Thanks a bunch @rafaelfranca!

Using your suggestion I even managed to get rid of the content_type fiddling, so final code looks like this:
```ruby
  def tech_bridge(recipients, subject, ical, bridge, bridge_url)
    @bridge = bridge
    @bridge_url = html_escape(bridge_url)

    ical_part = Mail::Part.new do
      content_type 'text/calendar; charset=UTF-8; method=REQUEST'
      body ical
    end

    message = mail(to: recipients, subject: subject) do |format|
      format.text(charset: 'UTF-8')
      format.html(charset: 'UTF-8')
    end
    message.add_part(ical_part)

    message
  end
```
The `mail(to: ...)` part will set content type to multipart/alternative and adding another message part won't change it so Outlook understands the invitation properly now.

Shall I document this somewhere and create a pull request?

**Comment by rafaelfranca** [comment]
If there is something to document is the fact that calling mail method more than once inside a method using blog will render the mail again.

**Comment by kaspth** [comment]
Action View has a double render error. Perhaps we should add that here. But making sure it won't raise if you've rendered text and then render html for instance.

--
Kasper

**Comment by rafaelfranca** [comment]
@kaspth :+1: seems a good plan.

Closing this issue since it was solved not calling `mail` more than once.
