### ISSUE TITLE
ActiveRecord 4.2 column default is no longer type-cast

### ISSUE THREAD

**Issue by kliuless** [rails/rails#19714]
In 4.2, When retrieving a column via `ModelClass.columns`, the `default` value is no longer type-cast to ruby, but is returned in a raw format. In 4.0 & 4.1 the casting was automatic. It might be good to include this change in the release notes (unless I missed it?).

Example: on sqlite3, a `:boolean` column with `default: false` is retrieved as `"f"` instead of `false`.

Is this this best way to cast it?
```ruby
column = ModelClass.columns.find{ |c| c.name == 'name' }
column.type_cast_from_database(column.default)
```

**Comment by rafaelfranca** [comment]
I don't think there is a better way to cast it. BTW, in Rails 4.2 you should not try to cast using a column. You should use the attribute type cast. I just don't remember what is the API.

cc @sgrif

**Comment by sgrif** [comment]
`Column#default` was intentionally changed, as it's an internal API. The best way to cast it would be `type_for_attribute(column.name).type_cast_from_database(column.default)`. In Rails 5, that would change to `type_for_attribute(column.name).deserialize(column.default)`. I should note that `type_for_attribute` is an internal API as well, but it's the least likely to break.

**Comment by sgrif** [comment]
Random extremely delayed note: The default value on the column (or any information from the column, for that matter) should never be used as authoritative information about a model. It represents the database schema, not the structure of the model itself.
