### ISSUE TITLE
Validation for presence of parent is failing if the parent is created inline with the child and if parent is invalid

### ISSUE THREAD

**Issue by prasadsurase** [rails/rails#19719]
```ruby
unless File.exist?('Gemfile')
  File.write('Gemfile', <<-GEMFILE)
   source 'https://rubygems.org'

   ruby '2.2.1'

   gem 'rails' , '4.2.1'
   gem 'activerecord', '4.2.1'
   gem 'arel'
   gem 'sqlite3'
   gem 'pry'
  GEMFILE

  system 'bundle'
end

require 'bundler'
Bundler.setup(:default)

# Activate the gem you are reporting the issue against.
require 'active_record'
require 'minitest/autorun'
require 'logger'
#  
# Ensure backward compatibility with Minitest 4
Minitest::Test = MiniTest::Unit::TestCase unless defined?(Minitest::Test)
#   
# This connection will do for database-independent bug reports.
ActiveRecord::Base.establish_connection(adapter: 'sqlite3', database: ':memory:')
ActiveRecord::Base.logger = Logger.new(STDOUT)
#    
# turn off partial_writes
ActiveRecord::Base.partial_writes = false

ActiveRecord::Schema.define do
  create_table :posts, force: true do |t|
    t.string :title
  end

  create_table :comments, force: true do |t|
    t.text :comment
    t.integer :post_id
  end
end

class Post < ActiveRecord::Base
  validates :title, presence: true
  
  has_many :comments
end

class Comment < ActiveRecord::Base
  validates :post, presence: true
  
  belongs_to :post
end

class BugTest < Minitest::Test
  def test_comment_is_invalid_if_post_is_not_specified
    comment = Comment.create()
    assert_same comment.valid?, false
  end

  def test_comment_is_invalid_if_invalid_post_is_specified
    comment = Comment.create(comment: 'some random comment', post: Post.create())
    assert_same comment.valid?, false
    assert_same comment.post, Post.last
  end
end
```
Here, the comment is created with post_id as 'nil'. This is unexpected and maybe a bug.

**Comment by palkan** [comment]
As I can see, your `Post` model requires `title` to be present. But you create _empty_ Post, that's why `post_id` is `nil` (the post haven't been created).

**Comment by prasadsurase** [comment]
@palkan, thats true. But what I meant to say is that Comment has a validation to check the presence of Post. Creating the Comment as specified above should result in an invalid Comment object because the Post is invalid, which is not happening.

**Comment by palkan** [comment]
Ok. A little bit more readable example:

```ruby
class Post < ActiveRecord::Base
  validates :title, presence: true
  has_many :comments
end

class Comment < ActiveRecord::Base
  validates :post, presence: true
  belongs_to :post
end

class BugTest < ActiveSupport::TestCase
  def test_invalid_record_belongs_to_presence
    post = Post.new
    comment = Comment.new(post: post)
    assert_not comment.valid?
  end

  def test_new_record_belongs_to_presence
    post = Post.new(title: "Test")
    comment = Comment.new(post: post)
    assert_not comment.valid?
  end
end
```

Both test fail, because `PresenceValidator` checks attribute for presence (using `blank?`) and absence of _mark\_as\_destroyed_ records, but do nothing with persistence.

To handle both these situations you can write `validates :user, :user_id, presence: true` (which, of course, looks strange, but works).

@rafaelfranca 
Maybe it's not that bad to extend `PresenceValidator` to handle persistence?

**Comment by meinac** [comment]
I think it's not a bug. If you say ```validates_presence_of :post ```
 this will look the comment object, post was assigned or not. 
If you inspect your comment model before the assertion in second test you can see that post object assigned to the comment object(but not persistent one).
As @palkan said it can be a feature to check the persistence of the model.

**Comment by prasadsurase** [comment]
The notes for presence validation specify that "If you want to be sure that an association is present, you'll need to test whether the associated object itself is present, and not the foreign key used to map the association. In order to validate associated records whose presence is required, you must specify the :inverse_of option for the association.". Specifying the option in the Post model has no difference in the output

**Comment by meinac** [comment]
Can you try presence validation with associated validation? I think this what you are looking for.
```ruby
class Comment < ActiveRecord::Base
  validates :post, presence: true, associated: true
  belongs_to :post
end
```
