### ISSUE TITLE
Different timestamp precision in activerecord where queries depending on whether a string or map is used 

### ISSUE THREAD

**Issue by jorihardman** [rails/rails#19711]
May be related to #19223

There seems to be a lot of issues surrounding time precision when using mysql 5.6 and Rails 4.2. This particular issue is seen with mysql2 0.3.18, Rails 4.2.1, and mysql 5.6.23.

Here is a straightforward example:

```
(byebug) User.where(created_at: Time.now).to_sql
"SELECT `users`.* FROM `users` WHERE `users`.`created_at` = '2015-04-09 17:35:58'"
(byebug) User.where('created_at = ?', Time.now).to_sql
"SELECT `users`.* FROM `users` WHERE (created_at = '2015-04-09 17:36:11.234855')"
```

The first query uses second precision, and the second uses millisecond precision.

**Comment by yoongkang** [comment]
I'm unable to reproduce this. Is anyone else having the problem?

**Comment by rafaelfranca** [comment]
@yoongkang thanks

@jorihardman if you think it is still an issue could you give us a way to reproduce it? Maybe creating a reproduction script with this template https://github.com/rails/rails/blob/master/guides/bug_report_templates/active_record_master.rb.

**Comment by jorihardman** [comment]
This seems like an issue with the mysql2 gem as I don't see the issue when using sqlite in a new 4.2 app. Should I submit an issue to them, or would you still like the reproduction script?

**Comment by jorihardman** [comment]
@rafaelfranca I noticed that the repro script seems to be set up for database independent bugs. I've confirmed that this is only an issue with mysql2 gem, so are you still interested in looking into it, or should I take it over to the mysql2 issues?

**Comment by rafaelfranca** [comment]
@jorihardman it seems to be specific for Active Record so we still need to investigate. I'm reopening. Could you post the reproduction script?

**Comment by jorihardman** [comment]
Here's a script that fails for me:

https://gist.github.com/jorihardman/4f12c83541b07c4b6084

**Comment by sodabrew** [comment]
Thanks for reopening it! The mysql2 gem doesn't interpret the incoming query string, so it must be AR that is generating it. Subscribing to this issue in case I can help in any way.

**Comment by jorihardman** [comment]
I started looking into this more and the issue is that when using a string, activerecord can't infer which column is being accessed, and so is unable to check the precision on the column object itself. When using symbols in a map, the column object can be fetched, and thus the precision can be determined. 

I upgraded my app from rails 4.1 and so never explicitly set a precision. I noticed the issue, because the particular version of mysql I had on my dev machine failed when performing date range queries when using microsecond precision. 

I would argue that the default behavior should be to be less precise when the column precision is unknown as opposed to more precise.

**Comment by jorihardman** [comment]
I've hunted down what causes this default behavior and it is here:

https://github.com/rails/rails/blob/master/activerecord/lib/active_record/connection_adapters/abstract/quoting.rb#L137-142

It's very confusing to have the default to_s(:db) format manipulated like this.

**Comment by sodabrew** [comment]
This comment on f1a0fa9e19b7e4ccaea191fc6cf0613880222ee7 points out that it would cause exactly this bug. Is the issue that unit tests aren't running on MySQL 5.6 yet, I would imagine they'd catch this already.
https://github.com/rails/rails/commit/f1a0fa9e19b7e4ccaea191fc6cf0613880222ee7#commitcomment-10048579

**Comment by jorihardman** [comment]
I absolutely agree with @dre-hh on that one.

**Comment by jorihardman** [comment]
Been awhile since there was any discussion on this. I'd be happy to submit a pull request to remove that code and add an additional test for precision equality if that's what you all think the solution should be.

**Comment by jorihardman** [comment]
@sodabrew To answer your question from May 28th, tests are running for MySQL 5.6, however this issue is specific to MySQL 5.5 since it does not support microsecond precision.

After a little more thought on this, the real problem is that the quoted_date method (https://github.com/rails/rails/blob/master/activerecord/lib/active_record/connection_adapters/abstract/quoting.rb#L128) assumes the current adapter supports datetime with usec precision. MySQL < 5.6.4 does not.

Another solution is to override this method in the AbstractMysqlAdapter so the connection can be checked for support. I will add a pull request with that as well as an alternative.
