### ISSUE TITLE
Fix autoload_paths in Rails Guides #docs

### ISSUE THREAD

**Issue by ifyouseewendy** [rails/rails#19729]
There is a code block in Rails Guides [Autoloading and Reloading Constants](http://guides.rubyonrails.org/autoloading_and_reloading_constants.html)

```ruby
config.autoload_paths += "#{Rails.root}/lib"
```

But `config.autoload_paths` is an Array, it causes `no implicit conversion of String into Array
(TypeError)`. Maybe it should be write like this

```ruby
config.autoload_paths += ["#{Rails.root}/lib"]
```

**Comment by eileencodes** [comment]
@ifyouseewendy feel free to send a pull request :smile:

**Comment by fxn** [comment]
Guess pushing with `<<` would be simpler than using `+=` with an array with one element. WDYT?

**Comment by zzak** [comment]
I this was fixed by dd0cae3138e3187ea67f64edeff3585ac3f5f99d, so I will backport it.

**Comment by zzak** [comment]
Backported in be8064c566dbb6711e19cf3a46447926b6f75ff8

**Comment by fxn** [comment]
Good!
