### ISSUE TITLE
`validates_uniqueness_of` only validating existing records should be documented

### ISSUE THREAD

**Issue by tgroutars** [rails/rails#19720]
So I've been struggling for some days now to figure out why `validates_uniqueness_of` didn't work with nested attributes. I know this is an old issue that has been reported many times, and that it is not going to be fixed, and I'm ok with enforcing uniqueness at the database level, but it should be documented.

Reading in the doc that `validates_uniqueness_of` only validates the record being saved against the existing record in database would have saved me a lot of time and energy, and I'm sure people will continue to struggle with it if it's not rightly documented.

**Comment by teknull** [comment]
Why not submit a PR documenting the behavior?  I'm sure many of us would appreciate it.

**Comment by tgr-odoo** [comment]
You're totally right, but I'm pretty new to Rails and figured that I might let it to someone who would use better words than me to describe that behavior. I haven't looked at any part of the code yet, so I can't be sure that what I would describe would be completely right.
Some day, I hope I'll know enough about rails to contribute actively, but for now I'm not too comfortable with it

**Comment by tgroutars** [comment]
You're totally right, but I'm pretty new to Rails and figured that I might let it to someone who would use better words than me to describe that behavior. I haven't looked at any part of the code yet, so I can't be sure that what I would describe would be completely right.
Some day, I hope I'll know enough about rails to contribute actively, but for now I'm not too comfortable with it

**Comment by gouravtiwari** [comment]
@tgroutars I might be missing a point, but I think docs do mention about existing records only
https://github.com/rails/rails/blob/master/activerecord/lib/active_record/validations/uniqueness.rb#L137

Is there anything else you would like to be added?

**Comment by sgrif** [comment]
I agree with the other comments here, please submit a PR if you have a specific improvement that you'd like to see.
