### ISSUE TITLE
commented `config.i18n.load_path`  suggestion in `application.rb` should have 'config' instead of 'my'

### ISSUE THREAD

**Issue by allenwlee** [rails/rails#19730]
this: 
`config.i18n.load_path += Dir[Rails.root.join('my', 'locales', '*.{rb,yml}').to_s]`

should be this:
`config.i18n.load_path += Dir[Rails.root.join('config', 'locales', '*.{rb,yml}').to_s]`

**Comment by naliwajek** [comment]
But `config/locales/*` are auto-loaded (just as comment says), so there's no reason to add it to the `config.i18n.load_path` - this line of code gives you an option to add locales held somewhere else and therefore putting there `config` would be IMO confusing. Am I wrong?

```
# The default locale is :en and all translations from config/locales/*.rb,yml are auto loaded.
# config.i18n.load_path += Dir[Rails.root.join('my', 'locales', '*.{rb,yml}').to_s]
```

**Comment by matthewd** [comment]
Agree with @naliwajek; the point of the comment is to describe what you'd need to do if your locales live somewhere odd -- not to imply you need the line when you're doing The Normal Thing.
