### ISSUE TITLE
Should AR::Base#lock! raise an exception if called with dirty attributes?

### ISSUE THREAD

**Issue by mathie** [rails/rails#19743]
I had a curious problem this morning whereby some attributes weren't getting persisted on a model. An example:

```ruby
def issue
  invoice.issued_at = Time.now
  invoice.set_issue_number
end

def set_issue_number
  with_lock do
    invoice.update_attribute(:issue_number, maximum_issue_number + 1)
  end
end
```

After calling `issue`, the attribute `issued_at` would mysteriously be nil. It transpires that the problem is with locking the table to claim a new issue number. The `lock!` method reloads the instance, throwing away the dirty attributes (including `issued_at`).

Since `lock!` does reload the model, would it make sense for it to raise an exception when it's called with dirty attributes, or log a warning? That would certainly have helped me solve the problem quicker! :smile:

**Comment by sgrif** [comment]
Possibly, but this is a question that should be directed at the Rails Core mailing list. We reserve the issue tracker for bugs only.
