### ISSUE TITLE
Controller generator improvement

### ISSUE THREAD

**Issue by mib32** [rails/rails#19747]
When i do `rails g controller admin/infobar index edit update show` i get that in my `routes.rb`:

*generator's indentation remains unchanged*
```
  namespace :admin do
  get 'infobar/index'
  end

  namespace :admin do
  get 'infobar/edit'
  end

  namespace :admin do
  get 'infobar/update'
  end

  namespace :admin do
  get 'infobar/show'
  end
```

Is it possible for it to maybe receive option `--rest` and produce that instead?
```
namespace :admin do 
  resource :infobar, only: [:index, :edit, :update, :show]
end
```

**Comment by kaspth** [comment]
We don't accept feature requests on the issue tracker. We recommend you try to implement this yourself and submit a pull request or ask questions like this on the rails-core mailing list. Thanks :heart:

**Comment by mib32** [comment]
@kaspth thanks! I just wanted to ask if there's any chance that this could be merged and i should work on that.

**Comment by kaspth** [comment]
Right on, that’s what we have the Rails core mailing list for :wink:

https://groups.google.com/forum/#!forum/rubyonrails-core

> Den 13/04/2015 kl. 21.04 skrev Anton Mur <notifications@github.com>:
> 
> @kaspth <https://github.com/kaspth> thanks! I just wanted to ask if there's any chance that this could be merged and i should work on that.
> 
> —
> Reply to this email directly or view it on GitHub <https://github.com/rails/rails/issues/19747#issuecomment-92462555>.
> 

--
Kasper
