### ISSUE TITLE
ActiveJob TestHelper assert_enqueue_with should accepts wait key

### ISSUE THREAD

**Issue by Aethelflaed** [rails/rails#19762]
I enqueue jobs using e.g. `wait: 5.seconds`, but to test if the job is enqueued correctly, I have first to `Timecop.freeze`, then compute `at: 5.seconds.from_now.to_f`, which sucks.

It's easy to compute `:at` from `:wait` in the same way, so why not supporting it ?

Also, float comparison sucks for timestamps...

**Comment by rafaelfranca** [comment]
Thank you so much for the issue but we don't take feature request on the issue tracker. We recommend you to try to implement the feature and send us a pull request or if you are in doubt if the feature will be accepts ask in Rails Core mailing list for feedback.

**Comment by rahuldess** [comment]
@Aethelflaed did you implement this feature ? If yes, Any reference ?

**Comment by Aethelflaed** [comment]
@rahuldess nope, I didn't have the time to do it properly, so I just added a method which in turns called `assert_enqueue_with` and transformed the `wait` parameter to `at` and did the `Timecop.freeze`
