### ISSUE TITLE
destroy! getting called on dependent models prevents the relating model from executing before_destroy

### ISSUE THREAD

**Issue by naiyt** [rails/rails#19761]
[This commit](https://github.com/rails/rails/commit/5aab0c053832ded70a3a4b58cb97f8f8bba796ba) changed it so that models that have `:dependent => :destroy` relations have `destroy!` called on all of the relations, rather than `destroy`. This is causing several issues.

The particular scenario we're running into is this. Model A has: `has_many :b, :dependent => :destroy`. Both `A` and `B` have `before_destroy` methods. In some situations, both should return false and add errors to their respective models. However, since the dependent model gets `destroy!` called on it instead of `destroy`, it raises `ActiveRecord::RecordNotDestroyed`, which means A never executes its `before_destroy`. This means we don't get the proper error messages on model A, or any other cleanup that might be desired in the `before_destroy`.

[Here is a self contained gist that demonstrates the issue](https://gist.github.com/naiyt/8bb130e8e4c1a0b9bdea). If you remove the `:dependent => :destroy` in model `Thing` that test passes.

I'm happy to try and solve this myself and open a PR if somebody else hasn't already encountered this and started on a fix. (I couldn't find anything from searching.)

**Comment by rafaelfranca** [comment]
If we managed to fix the [original issue](https://github.com/rails/rails/issues/12812) without raising the exception :+1:

**Comment by naiyt** [comment]
I'll see what I can do to keep the original fix without raising the exception too soon.

**Comment by albertopriore** [comment]
Do you have any update on this issue?

**Comment by naiyt** [comment]
@albertopriore this was a PR that fixed it: https://github.com/rails/rails/pull/19773

We ended up doing something else that made it no longer a problem, but I think it's still a good fix. If people agree I can go back in, clean it up, and bring it up to date.

**Comment by albertopriore** [comment]
@naiyt for me your fix will solve my problem

**Comment by guigs** [comment]
I hit this issue with my app today. I made a monkey patch based on #19773 and it solved the problem.

**Comment by naiyt** [comment]
Since multiple people seem to be running into this same problem, I brought my branch back up to date and fixed the merge conflicts. It'd be great to see if we could get that merged. Anyone know who would be the best to review it that I could contact?

**Comment by davidakachaos** [comment]
@naiyt is this issue still current? Or is your new PR already merged and can this issue be closed?

**Comment by naiyt** [comment]
This is technically still an issue, but as I wasn't able to get a code review on the PR for over a year I ended up closing it.

**Comment by jasonperrone** [comment]
This seems to me to a big issue, because basically, as far as I am concerned, it runs counter to the dependent: :restrict_with_error clause on the has_many. I am clearly saying there I don't want a failed destroy of the child to raise an exception. Yet by calling destroy! it does and I have no way to stop it. Does anybody else agree that changing to destroy! in 4.1 broke dependent: :restrict_with_error?
