### ISSUE TITLE
"touch" can corrupt lock_version and does not raise StaleObjectError

### ISSUE THREAD

**Issue by markpmitchell** [rails/rails#19776]
In Rails 4.2, ActiveRecord::Persistence.touch increments lock_version (if optimistic locking is in use), but bypasses ActiveRecord::Locking::Pessimistic._update_record, and thereby will happily touch an out-of-date object, possibly corrupting lock_version in the process. Consider:

   p = Post.create(title: 'Original Title') # lock_version = 0
   p2 = Post.find(p.id) # A second in-memory copy. # lock_version = 0
   p.update(title: 'New Title') # lock_version = 1
   p.update(title: 'Another New Title') # lock_version = 2
   p2.touch # Does not raise exception, resets lock_version to 1

I think that the call to touch should raise StaleObjectError. If not, it should at the very least not reset the lock_version to an already used value.

**Comment by sgrif** [comment]
Can you please provide a script that we can use to reproduce the issue, using [this template](https://github.com/rails/rails/blob/master/guides/bug_report_templates/active_record_master.rb)? You can find our bug report guidelines [here](http://guides.rubyonrails.org/contributing_to_ruby_on_rails.html#reporting-an-issue)

**Comment by markpmitchell** [comment]
Thank you for the pointer to the template. Here is the issue in that form, including a failing test.

    unless File.exist?('Gemfile')
      File.write('Gemfile', <<-GEMFILE)
        source 'https://rubygems.org'
        gem 'rails', github: 'rails/rails'
        gem 'arel', github: 'rails/arel'
        gem 'sqlite3'
      GEMFILE

      system 'bundle'
    end

    require 'bundler'
    Bundler.setup(:default)

    require 'active_record'
    require 'minitest/autorun'
    require 'logger'

    # This connection will do for database-independent bug reports.
    ActiveRecord::Base.establish_connection(adapter: 'sqlite3', database: ':memory:')
    ActiveRecord::Base.logger = Logger.new(STDOUT)

    ActiveRecord::Schema.define do
      create_table :posts, force: true  do |t|
        t.string :title
        t.integer :lock_version, default: 0
        t.timestamps
      end
    end

    class Post < ActiveRecord::Base
      has_many :comments
    end

    class BugTest < Minitest::Test
      def test_association_stuff
        post = Post.create!(title: 'Original Title')
        post_copy = Post.find(post.id)
        post.update!(title: 'New Title')
        post.update!(title: 'Another New Title')
        post_version = post.lock_version
        # This line should probably raise ActiveRecord::StaleObjectError,
        # but does not.
        post_copy.touch
        # And, surely, the lock_version should never go backwards.
        assert post.reload.lock_version >= post_version
      end
    end

**Comment by markpmitchell** [comment]
I am happy to attempt a patch for the problem, provided that there is consensus about the desired behavior. In particular, should the call to touch raise `StaleObjectError`? If that's not the desired behavior, should `lock_version` be updated at all? And, if so, presumably it should be atomically incremented so that the lock_version doesn't go backwards?

The reason that I think it should raise StaleObjectError is motivated by examples like this:

    class Post < ActiveRecord::Base
      has_many :comments
    end
  
    class Comment < ActiveRecord::Base
      belongs_to :post, touch: true
    end

That "touch" is implying that Comments really are contained in a Post; a change to a Comment is, logically, a change to the containing Post. I'd like an error when trying to update a Comment, if the copy of the Post I have is stale.

**Comment by sgrif** [comment]
Thank you. I'll take a closer look at this tomorrow.
