### ISSUE TITLE
Display the exception page when format is js

### ISSUE THREAD

**Issue by jvenezia** [rails/rails#19781]
I think that exceptions should be displayed with **format js** the same way html is. What do you think?

As a workaround, I'm trying to do this manually like so:

```ruby
# app/controllers/application_controller.rb

class ApplicationController < ActionController::Base
    rescue_from Exception, with: :render_error

    def render_error(exception)
        respond_with do |format|
            format.html { raise exception }
            format.json { raise exception }
            format.js { render 'errors/error' }
        end
    end
end

#app/view/errors/error.js.erb

$('body').html("<%= escape_javascript(render partial: 'rails_template_for_exceptions') %>");
```

But actually I don't know how to get the html of this rais exception page.
Those templates seems to be [here](https://github.com/rails/rails/tree/master/actionpack/lib/action_dispatch/middleware/templates/rescues), but how can I use them ?

Do you have any idea how could I achieve this ?

Here is a related stackoverflow : [http://stackoverflow.com/questions/29651992/manually-render-a-rails-error-page](http://stackoverflow.com/questions/29651992/manually-render-a-rails-error-page)

**Comment by rafaelfranca** [comment]
I think it is already fixed on master branch. Please give it a try.

**Comment by jvenezia** [comment]
Hi, I just checked the behaviour on master branch and it seems not to be fixed, or my issue what not clear enough. Can you explain me why you say it is fixed ?

For an example, I expect that an error from a `remote: true` link is displayed directly on the browser, in html, like any other standard error, without needing to check the HTTP response.

Please tell me if you need more information. I understand if the issue remains closed, I will not have the time to work on this at the moment, but i'll check this if I can.

**Comment by rafaelfranca** [comment]
The error is displayed as a JavaScript error because it is a JavaScript request. You need to handle it. We have no plans to show a HTML error page if the error is in a JavaScript request.

**Comment by jvenezia** [comment]
Yes, I know. It was an idea. I think it would be more convenient.
