### ISSUE TITLE
after_commit callback only triggered for first of multiple instances of the same model

### ISSUE THREAD

**Issue by stemps** [rails/rails#19797]
If multiple instances of the same model are updated in an ActiveRecord transaction, only the object that is first updated receives an `after_commit` callback:

```ruby
Thing.transaction do
  thing1 = Thing.find(1)
  thing2 = Thing.find(1)

  thing1.save!  #will receive after_commit callback at end of transaction
  thing2.save!  #will NOT receive after_commit callback
end
```

The can easily occur in a read world scenario if a `Thing` is loaded and updated multiple times through different associations.

I was able to reproduce this in `4.2.0` and on `master`. A full test script can be found here: https://gist.github.com/stemps/3a8ef0edf7030d7874cb

I would offer to look into the issue and help fix it, but before I do it'd be great to hear what the opinion of the rails team is how ActiveRecord should behave in this case. Is the described behavior considered a bug or does it work like this on purpose?

**Comment by arthurnn** [comment]
We use the `id` to identify the uniqueness of the objects before running the after_commit callbacks, as we dont want to run the callback 2x+ if the same element was touched inside the transaction.
This is by design, and I dont think we can do anything about it.

**Comment by yashBiz** [comment]
@stemps Did you find a good workaround for this ?

**Comment by stemps** [comment]
@yashBiz no, we now avoid relying on `after_commit` callbacks that rely on the state of a specific model instance

**Comment by yashBiz** [comment]
@stemps So, what technique/tool did you adopt to achieve a similar logic flow now ?
