### ISSUE TITLE
has_many with scope and extensions

### ISSUE THREAD

**Issue by youroff** [rails/rails#19792]
With Rails 4.2.1 this definition raises a SyntaxError: "unexpected keyword_do, expecting keyword_end"
```
  has_many :steps, -> { order "position" }, class_name: 'Recon::Step' do
    ...
  end
```

Though it works fine if I remove either a default scope or extensions block. Is it how it's supposed to be?

**Comment by kaspth** [comment]
Ruby doesn't know what block the -> refers to. You need to add parens around the has_many arguments like this: `has_many(...) do`
