### ISSUE TITLE
Can't catch deserialization error when sending email with ActiveJob

### ISSUE THREAD

**Issue by bolshakov** [rails/rails#19793]
For example:

```ruby
class UserMailer < ActionMailer::Base
  def payment_required(customer)
    # ...
  end
end
```

If I send delayed email:

```ruby
UserMailer.payment_required(customer).deliver_later(wait: 30.days)
```

And then user deletes his account the mailer fails with error `ActiveJob::DeserializationErrorError while trying to deserialize arguments: Couldn't find User with 'id'=2 `

So I can't cancel this job and I can catch this error to deal with it some way

**Comment by artofhuman** [comment]
@bolshakov, i think u need implement `rescue_from(ActiveJob::DeserializationError) { # some logic }`

**Comment by bolshakov** [comment]
Right, but ActionMailer does not implement ActiveSupport::Rescuable

**Comment by rafaelfranca** [comment]
Is not job of the queue library to ignore jobs that failed?

**Comment by bolshakov** [comment]
@rafaelfranca `ActiveJob` itself supports this feature. Here example from `ActiveJob` guide:

```ruby
class GuestsCleanupJob < ActiveJob::Base
  queue_as :default
 
  rescue_from(ActiveRecord::RecordNotFound) do |exception|
   # Do something with the exception
  end
 
  def perform
    # Do something later
  end
end
```

But currently when I use `ActiveJob` with `ActionMailer` it is impossible to use error handling and callbacks

**Comment by JuanitoFatas** [comment]
Maybe related to https://github.com/rails/globalid/issues/66.

**Comment by cristianbica** [comment]
So the issue here is emails sent with `perform_later` are enqueued and executed with the internal class `ActionMailer::DeliveryJob`. So a user cannot use `rescue_from` to catch this kind of errors.
@rafaelfranca what do you think about making the job class used by AM configurable. So if anyone wants to customize something can configure another job (which inherits from `ActionMailer::DeliveryJob`)  and configure things in there?

**Comment by jeremy** [comment]
How about updating DeliveryJob to delegate rescue_from to the affected mailer?

**Comment by jeremy** [comment]
Implemented https://github.com/rails/rails/pull/25018

**Comment by philipgiuliani** [comment]
I've fixed this in the meanwhile by putting `initializers/delivery_job.rb` into my project with this:
```ruby
ActionMailer::DeliveryJob.class_eval do
  rescue_from ActiveJob::DeserializationError do |exception|
    # Just skip this, we dont want to perform the job again
  end
end
```

Seems to work fine! But its of course for all mailer jobs.
