### ISSUE TITLE
Outer scope is applied to subquery even though the subquery is built independently

### ISSUE THREAD

**Issue by phallguy** [rails/rails#19804]
This appears to be an issue with current_scope caching at the class level. When a where condition uses a subquery, the current scope is merged into the subquery producing incorrect results.

Test cases

```ruby
unless File.exist?('Gemfile')
  File.write('Gemfile', <<-GEMFILE)
    source 'https://rubygems.org'
    gem 'rails', github: 'rails/rails'
    gem 'arel', github: 'rails/arel'
    gem 'rack', github: 'rack/rack'
    gem 'i18n', github: 'svenfuchs/i18n'
    gem 'sqlite3'
  GEMFILE

  system 'bundle'
end

require 'bundler'
Bundler.setup(:default)

require 'active_record'
require 'minitest/autorun'
require 'logger'

# This connection will do for database-independent bug reports.
ActiveRecord::Base.establish_connection(adapter: 'sqlite3', database: ':memory:')
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table(:campaigns) do |t|
    t.string :name
  end

  create_table(:participants) do |t|
    t.integer :priority
    t.references :campaign
    t.references :user
  end

  create_table(:users) do |t|
    t.string :name
  end
end


class Campaign < ActiveRecord::Base
  has_many :participants, inverse_of: :resource
end

class Participant < ActiveRecord::Base
  belongs_to :user, inverse_of: :participants
  belongs_to :campaign, inverse_of: :participants

  # @!attribute priority
  # @return [Integer] some arbitrary column to filter by.

  scope :in_campaigns, ->( campaigns ) {
    campaigns = campaigns.select( :id )
    where( campaign_id: campaigns )
  }

  scope :with_priority, ->( priority ) {
    where( priority: priority )
  }
end

class User < ActiveRecord::Base
  has_many :participants, inverse_of: :user
  has_many :campaigns, through: :participants
end


class BugTest < Minitest::Test

  def setup
    @john  = User.create! name: "John"
    @jane  = User.create! name: "Jane"

    book  = Campaign.create! name: "Book"
    shoe  = Campaign.create! name: "Shoe"


    @john.participants.create campaign: book, priority: 1

    @jane.participants.create campaign: shoe, priority: 1
    @jane.participants.create campaign: book, priority: 5
  end

  def test_includes_intersection_when_filter_preceeds_join
    participants = Participant.with_priority 1
    participants = participants.in_campaigns( @jane.campaigns )

    assert participants.size == 2
  end

  def test_includes_intersection_when_filter_succeeds_join
    participants = Participant.in_campaigns( @jane.campaigns )
    participants = participants.with_priority 1

    assert participants.size == 2
  end

end
```

Both tests should produce the same result. The order however becomes significant because the precondition `with_priority 1` is applied to `jane.campaigns`  in which there is only one participant in that campaign.

You can observe the incorrect behavior by examining the SQL itself. In both cases, the SQL generated should be

```sql
SELECT COUNT(*)
FROM "participants"
WHERE "participants"."campaign_id" IN
    (SELECT "campaigns"."id"
     FROM "campaigns"
     INNER JOIN "participants" ON "campaigns"."id" = "participants"."campaign_id"
     WHERE "participants"."user_id" = ?)
  AND "participants"."priority" = ? 

[["user_id", 4], ["priority", 1]]
```

Notice that priority is only applied once. In the failing test however, priority is applied twice:

```sql
SELECT COUNT(*)
FROM "participants"
WHERE "participants"."priority" = ?
  AND "participants"."campaign_id" IN
    (SELECT "campaigns"."id"
     FROM "campaigns"
     INNER JOIN "participants" ON "campaigns"."id" = "participants"."campaign_id"
     WHERE "participants"."priority" = ?
       AND "participants"."user_id" = ?) 

[["priority", 1], ["priority", 1], ["user_id", 2]]
```

I've done some initial debugging and it seems to be related to the #scoping call using #current_scope when merging the in_campaigns scope, but #current_scope is overwritten to include the priority constraint wen the in_campaigns scope is resolved, and that applies an additional unwanted constraint.

**Comment by sgrif** [comment]
Unfortunately, this is by design not a bug. Associations are always mean to respect the scope they're executed in, not the scope they're created in. You can work around this in your app by replacing your scope with what would normally be considered the idiomatic form of: `Participant.where(campaign: @jane.campaigns)`

**Comment by sgrif** [comment]
Note: while I agree the current behavior is confusing, and I am not endorsing it, changing it would be a major breaking change.

**Comment by phallguy** [comment]
I'm not sure I understand the rejection here. This used to work in 3.x. It is a regression - restoring it wouldn't be a breaking change. The association isn't respecting the scope it's executed in. It is inheriting an unrelated scope that doesn't apply to it. @jane.campaigns should never pick up any additional constraints from some other object. Now if there were a default scope, or a surrounding `scope` call I could maybe see the argument, but neither is the case here. One relation's scope is being incorrectly applied to a different relation without any sort of parent/context relationship between the two. The order that the AST is built should not matter.
