### ISSUE TITLE
Fixture should support '.yaml' or give a warning when you use foo.yaml.

### ISSUE THREAD

**Issue by chenge** [rails/rails#19805]
I tried to use fixture to do test. I found it support only '.yml'.

**Comment by tgxworld** [comment]
@chenge Could you provide more details on what is it you are trying to do as the description is too vague right now :smile_cat:

**Comment by chenge** [comment]
I test Review model and make a file "review.yaml". But it is useless and no any hint.
Later I tried to modify the name to "review.yml", it works.

That's it.

**Comment by arekf** [comment]
Current [YAML specification](http://www.yaml.org/spec/1.2/spec.html) does not specify extension for YAML files.

An outdated version of YAML [FAQ](http://www.yaml.org/faq.html) states the following:
> **Is there an official extension for YAML files?**
> Please use ".yaml" when possible.

**Comment by rafaelfranca** [comment]
Yeah, agree that both should work.

**Comment by tgxworld** [comment]
@rafaelfranca I'm not sure if we really want to support `.yaml` as well. Currently, the default extension used in the code base and documentation uses `.yml` and if we were to support `.yaml` for fixtures, it'll also start to raise questions such as: "[Shouldn I18n support `.yaml` too?](https://github.com/svenfuchs/i18n/blob/b1200f0289a59ba0368f800473d8ac79f713bc26/lib/i18n/backend/base.rb#L11) or "Can I name my config file `database.yaml`?" In my opinion, `.yml` can be viewed as a "naming convention` adopted by Rails. Thoughts? :smile:

**Comment by robertjlooby** [comment]
The fixtures documentation clearly specifies `.yml` [here](https://github.com/rails/rails/blob/master/activerecord/lib/active_record/fixtures.rb#L19).
It looks like the only place where `.yaml` is supported is the [`rake notes`](https://github.com/rails/rails/blob/master/railties/lib/rails/source_annotation_extractor.rb#L31) task.
`.yaml` and `.yml` support was [added](https://github.com/rails/rails/commit/f43421cb65da635988f2bb5341d519c3c2748b74) there at the same time, but I don't see any particular reason for why it was decided to add both besides a comment on the issue [here](https://github.com/rails/rails/pull/14214).
