### ISSUE TITLE
In Rails 4.2.1, remote forms throw InvalidAuthenticityToken

### ISSUE THREAD

**Issue by miskolc** [rails/rails#19810]
I'm trying to submit a form using AJAX and data-remote unfortunately I receive an InvalidAuthenticityToken error. It seems that the authentication token is not added to the form when using remote: true so  I did some research and found out the following options for solving the problem:
- adding the following line in the Controller
  skip_before_action :verify_authenticity_token, :only => :create
-  adding the following line inside the form_for block
 <%= f.hidden_field :authenticity_token, value: form_authenticity_token %>
- adding :authenticity_token => true to the form_for params
- setting config.action_view.embed_authenticity_token_in_remote_forms to true in development.rb

I tried using all the above and each of them helped me get rid of the InvalidAuthenticityToken error, however, even though I still had the remote: true option, the request doesn't seem to be performed using AJAX since the page reloads and renders another view template.

**Comment by matthewd** [comment]
Please use the mailing list or StackOverflow for questions/help, where a wider community will be able to help you. We reserve the issues tracker for issues only.
