### ISSUE TITLE
127.0.0.1 not accessible when rails binds to localhost

### ISSUE THREAD

**Issue by tpitale** [rails/rails#19815]
I'm finding the statement in http://guides.rubyonrails.org/4_2_release_notes.html#default-host-for-rails-server that both 127.0.0.1 and localhost will work the same to be not true.

When left to the default rails settings in 4.2.0, localhost:3000 works fine, but 127.0.0.1:3000 does not. No matter the browser, or curl, I get: `curl: (7) Failed to connect to 127.0.0.1 port 3000: Connection refused` when `Rails 4.2.0 application starting in development on http://localhost:3000`.

I'm not sure if the statement in the guide is just a mistake, or if there is more going on here. I'm developing on Mac OS X 10.10.3, with Ruby 2.2.2 and Rails 4.2.0.

**Comment by rafaelfranca** [comment]
It is a documentation mistake. Could you send a patch please?

**Comment by tpitale** [comment]
Sure!

Also of note, if I bind to 127.0.0.1 with -b, I can visit localhost because of /etc/hosts, but then sessions don't work (wrong domain, I guess).

**Comment by chancancode** [comment]
Checked with @rafaelfranca, as far as we can tell, this is "supposed" to work, so we should probably figure out what went wrong instead. Reopening!

**Comment by chancancode** [comment]
(see #19817 for some more context)

**Comment by lime** [comment]
It looks like we are using the defaults from `Rack::Server`, which are defined here: https://github.com/rack/rack/blob/1.6.1/lib/rack/server.rb#L195

Not sure if this is something we would want to define separately on the Rails side, or if it would make sense for Rack to default to 127.0.0.1. I could submit a PR on the Rack side and see what people think.

**Comment by lime** [comment]
Although now that I read through the original PR, it kind of makes sense: https://github.com/rack/rack/pull/514#issuecomment-14016369

> Using 127.0.0.1 would assume the system supports IPv4. Better to use localhost and let /etc/hosts map it to the correct address/interface.

I'm not sure how we could make all three options (`localhost`, `127.0.0.1`, `::1`) work by default, even on the Rails side...

**Comment by chancancode** [comment]
@lime does this not work for you as well? Because I cannot reproduce this locally, see #19817. Still trying to figure out what's dofferent on our systems

**Comment by lime** [comment]
You're right @chancancode, it works in a vanilla rails app! The difference was that I am using Puma instead of WEBrick.

```
$ bundle exec rails s --daemon
=> Booting WEBrick
=> Rails 4.2.1 application starting in development on http://localhost:3000
=> Run `rails server -h` for more startup options
$ curl -i -X HEAD http://127.0.0.1:3000
HTTP/1.1 200 OK
X-Frame-Options: SAMEORIGIN
X-Xss-Protection: 1; mode=block
X-Content-Type-Options: nosniff
Content-Type: text/html; charset=utf-8
Etag: W/"b56dd5f9363ed0f7bd4d11c36d9471dd"
Cache-Control: max-age=0, private, must-revalidate
X-Request-Id: 6bd681e1-6b92-4e84-a6ad-b74e65da9b9a
X-Runtime: 0.236624
Server: WEBrick/1.3.1 (Ruby/2.1.2/2014-05-08)
Date: Thu, 11 Jun 2015 12:16:29 GMT
Content-Length: 0
Connection: Keep-Alive
Set-Cookie: request_method=HEAD; path=/
```
When I added `gem 'puma'` to Gemfile:
```
$ bundle exec rails s --daemon
=> Booting Puma
=> Rails 4.2.1 application starting in development on http://localhost:3000
=> Run `rails server -h` for more startup options
$ curl -i -X HEAD http://127.0.0.1:3000
curl: (7) Failed to connect to 127.0.0.1 port 3000: Connection refused
```
Interestingly, `curl -I http://\[::1\]:3000` worked for both.

So I guess for the default configuration, everything is working properly. :) Not sure if anything should be changed in Puma.

**Comment by tpitale** [comment]
Interesting. I'm also using puma in my project(s). I'll try swapping out for webrick.

**Comment by lime** [comment]
Some googling indicates that Puma ends up binding only to IPv6, which explains my results above. See e.g. [this superuser question](http://superuser.com/q/906123/71614).

I ended up overriding the default options for the `rails server` command to use `127.0.0.1` by default.  [Here is a gist](https://gist.github.com/lime/611e4ad2f997c52c0b84) if someone else wants to go that route.

**Comment by chancancode** [comment]
Mystery solved! While we should probably work with puma to fix this there, it doesn't seem like this is a rails bug, so closing again for now :grin:

Thanks for confirming!
