### ISSUE TITLE
force_ssl loses port when redirecting to https

### ISSUE THREAD

**Issue by emirkin** [rails/rails#19820]
```
Started GET "/plan" for 127.0.0.1 at 2015-04-19 19:06:52 -0700
Processing by AccountsController#change_rate_plan as HTML
Redirected to http://localhost:3000/payments
Completed 302 Found in 70ms

Started GET "/payments" for 127.0.0.1 at 2015-04-19 19:06:52 -0700
Processing by AccountsController#edit_payment_info as HTML
Redirected to https://localhost/payments # <<<<<< what????
Filter chain halted as #<Proc:0x007f8ddb7a24c8@/Library/Ruby/Gems/2.0.0/gems/actionpack-4.2.1/lib/action_controller/metal/force_ssl.rb:65> rendered or redirected
Completed 301 Moved Permanently in 2ms
```

As you can see from the log above, the redirect caused by force_ssl loses the port, which should be 3001.

Here's my controller (`/plan` and `/payments` point to 2 different methods):
```
class AccountsController < ApplicationController
  force_ssl only: :edit_payment_info
  ...
```

Here's what I have in my development.rb (not having this doesn't have any effect on this particular issue):
```
  config.action_controller.asset_host = Proc.new do |source, request = nil, *_| # The *_ is present due to a bug with option arguments in Proc http://bugs.ruby-lang.org/issues/5694
    is_ssl = request && request.ssl?
    port = is_ssl ? 3001 : 3000
    protocol = is_ssl ? 'https:' : 'http:'
    "#{protocol}//localhost:#{port}"
  end
```

**Comment by matthewd** [comment]
You rightly observe that the `asset_host` configuration is unrelated to how we treat "real" requests. So, could you please show where you've specified the `3001` port, for it to have been lost?

**Comment by emirkin** [comment]
Just like I don't set 3000 anywhere explicitly (not talking about mailer or assets here), I don't know any way to set the HTTPS port (which is not 443 on a dev machine). Where would you specify it globally?

**Comment by pascalbetz** [comment]
@emirkin 
see http://api.rubyonrails.org/classes/ActionController/ForceSSL/ClassMethods.html

```
force_ssl port: 3001
```

leads to:

```
Started GET "/" for 127.0.0.1 at 2015-04-22 12:48:41 +0200
Processing by OrdersController#index as HTML
Redirected to https://localhost:3001/
```

which is probably what you want? Does not seem like a bug in Rails. Btw: the port ist not lost, it's just defaulted to 443.
