### ISSUE TITLE
Slash in file name for render does not search in the application folder

### ISSUE THREAD

**Issue by BenMorganIO** [rails/rails#19834]
Hey there,

While rendering a partial via `render 'meta_tags'` I received this error:

``` ruby
15:15:42 web.1    | Completed 500 Internal Server Error in 547ms (ActiveRecord: 0.0ms)
15:15:42 web.1    |
15:15:42 web.1    | ActionView::MissingTemplate - Missing partial home/_meta_tags, base/_meta_tags, application/_meta_tags with {:locale=>[:en], :formats=>[:html], :variants=>[], :handlers=>[:erb, :builder, :raw, :ruby, :slim, :coffee, :rabl], :versions=>[:v10, :v9, :v8, :v7, :v6, :v5, :v4, :v3, :v2, :v1]}. Searched in:
15:15:42 web.1    |   * "/Users/benmorgan/Sites/rails_app/app/views"
15:15:42 web.1    |   * "/Users/benmorgan/.rvm/gems/ruby-2.2.2/bundler/gems/spree_social-5580ada3dc9b/app/views"
15:15:42 web.1    |   * "/Users/benmorgan/.rvm/gems/ruby-2.2.2/bundler/gems/spree_auth_devise-07f16255c8e8/lib/views/backend"
15:15:42 web.1    |   * "/Users/benmorgan/.rvm/gems/ruby-2.2.2/gems/devise-3.4.1/app/views"
15:15:42 web.1    |   * "/Users/benmorgan/.rvm/gems/ruby-2.2.2/bundler/gems/spree_gateway-d9305a348d25/lib/views/backend"
15:15:42 web.1    |   * "/Users/benmorgan/.rvm/gems/ruby-2.2.2/bundler/gems/spree-8221fa59029f/backend/app/views"
15:15:42 web.1    |   * "/Users/benmorgan/.rvm/gems/ruby-2.2.2/bundler/gems/spree-8221fa59029f/api/app/views"
15:15:42 web.1    |   * "/Users/benmorgan/.rvm/gems/ruby-2.2.2/bundler/gems/spree-8221fa59029f/core/app/views"
15:15:42 web.1    |   * "/Users/benmorgan/.rvm/gems/ruby-2.2.2/gems/kaminari-0.16.3/app/views"
```

Notice that it searched in three places:
- `home/_meta_tags`
- `base/_meta_tags`
- `application/_meta_tags`

For my Rails apps, I always namespace them since I deal with several rails engines in my views, controllers, and models. Namespacing really helps keep things organized. Placing the partial at `application/_meta_tags` worked.

You'll notice that the last place it searched was `application/_meta_tags`. Then, I tried doing `render 'shared/meta_tags` and the error message that was returned was:

``` ruby
15:22:28 web.1    | ActionView::MissingTemplate - Missing partial shared/_meta_tags with {:locale=>[:en], :formats=>[:html], :variants=>[], :handlers=>[:erb, :builder, :raw, :ruby, :slim, :coffee, :rabl], :versions=>[:v10, :v9, :v8, :v7, :v6, :v5, :v4, :v3, :v2, :v1]}. Searched in:
15:22:28 web.1    |   * "/Users/benmorgan/Sites/rails_app/app/views"
15:22:28 web.1    |   * "/Users/benmorgan/.rvm/gems/ruby-2.2.2/bundler/gems/spree_social-5580ada3dc9b/app/views"
15:22:28 web.1    |   * "/Users/benmorgan/.rvm/gems/ruby-2.2.2/bundler/gems/spree_auth_devise-07f16255c8e8/lib/views/backend"
15:22:28 web.1    |   * "/Users/benmorgan/.rvm/gems/ruby-2.2.2/gems/devise-3.4.1/app/views"
15:22:28 web.1    |   * "/Users/benmorgan/.rvm/gems/ruby-2.2.2/bundler/gems/spree_gateway-d9305a348d25/lib/views/backend"
15:22:28 web.1    |   * "/Users/benmorgan/.rvm/gems/ruby-2.2.2/bundler/gems/spree-8221fa59029f/backend/app/views"
15:22:28 web.1    |   * "/Users/benmorgan/.rvm/gems/ruby-2.2.2/bundler/gems/spree-8221fa59029f/api/app/views"
15:22:28 web.1    |   * "/Users/benmorgan/.rvm/gems/ruby-2.2.2/bundler/gems/spree-8221fa59029f/core/app/views"
15:22:28 web.1    |   * "/Users/benmorgan/.rvm/gems/ruby-2.2.2/gems/kaminari-0.16.3/app/views"
```

Placing the partial at `application/shared/_meta_tags` did not work. You'll also notice the `base` folder is no longer there, but considering its "base" then I don't think it should be searched in.

As Rails apps get bigger (and when developing with Spree), I find that namespacing the Rails app to help enormously width code organization and a clear separation of who owns what logic. I'm wondering if we can add support for searching within the application folder when the string passed to `render` contains a `/`.

**Versions**:
- Ruby 2.2.2
- Rails: 4.2.1

**Expected Result**: Rails would render `"application/shared/_meta_tags.html.slim"` via a `render 'shared/meta_tags'`

**Given Result**: Rails could only render `shared/_meta_tags.html.slim` if it was placed at the root and returned with `ActionView::MissingTemplate` error when `_meta_tags.html.slim` was placed in `application/shared`. It did, however, render when there was no `/` in the string and the folder structure was updated.

**Comment by meinac** [comment]
:+1:  For this case rails can keep looking to the home, base, and application folders for `shared/meta_tags.html.slim` if can not find `shared/meta_tags.html.slim` at view root directory.

**Comment by radar** [comment]
@BenMorganIO Do you have an app that can reproduce this issue?

**Comment by BenMorganIO** [comment]
I believe this still reproduce-able.

**Comment by meinac** [comment]
I've opened a pr for this and @rafaelfranca is working on it.
