### ISSUE TITLE
place holder previews for NullMail

### ISSUE THREAD

**Issue by maninalift** [rails/rails#19849]
The mailer previews that arrived in rails 4.1 should do something sensible (i.e. render some informative message) when they encounter a `ActionMailer::Base::NullMail` at the moment they result in an error because nil data is encountered.

**Comment by senny** [comment]
@maninalift I'll take a look.

**Comment by prathamesh-sonpatki** [comment]
@senny Can we rely on https://github.com/rails/rails/blob/master/actionmailer/lib/action_mailer/base.rb#L598 for checking if the `@email` variable here - https://github.com/rails/rails/blob/master/railties/lib/rails/mailers_controller.rb#L22 - is `NullMail` or not?

**Comment by prathamesh-sonpatki** [comment]
@senny I tried to fix the issue as this - https://github.com/prathamesh-sonpatki/rails/commit/836e515a7bd159508671b336052d27331f8051ad

**Comment by senny** [comment]
@prathamesh-sonpatki I had a fix already prepared. You can follow the discussion here: #19917

**Comment by senny** [comment]
@maninalift solved and backported to `4-2-stable` and `4-1-stable`. Thank you for reporting.
