### ISSUE TITLE
"render :file" caches contents

### ISSUE THREAD

**Issue by caiosba** [rails/rails#19840]
I have a controller method that serves static HTML files if they are present. Those files can be changed by external applications. The problem is that when any of those files are changed, Rails still serves the cached version of when the server started.

Another thread started on 2011 mentioning the same issue: https://rails.lighthouseapp.com/projects/8994/tickets/4449-render-file-caches-contents-doesnt-reload-until-webserver-reloaded.

I originally noticed that on Rails 4.0.2, Ruby 2.0.0. Could reproduce it now on Ruby 2.2.2, Rails 5 Alpha (master branch at e539866d80fa614412f65a12a63a9063fd89ce5e), only in Production mode.

I checked the code (actionview/lib/action_view/renderer/abstract_renderer.rb line 30, actionview/lib/action_view/renderer/partial_renderer.rb line 420, actionview/lib/action_view/lookup_context.rb and actionview/lib/action_view/renderer/template_renderer.rb line 43) and I'm not sure whether this is a bug or a design decision. Right now, as a workaround, I'm using `render text: File.read(file_path)` instead of `render file: file_path`.

Should it be solved? I would be happy in providing a fix for that, if acknowledged as a bug.

**Comment by rafaelfranca** [comment]
It is a design decision. View templates are cached in production.

Thank you for the report.
