### ISSUE TITLE
[PERF] Regression in 4.2+ when creating/updating records 

### ISSUE THREAD

**Issue by tgxworld** [rails/rails#19859]
The following URLs link to the benchmark scripts and results that we've benchmarked for every Rails releases since 3.2.0:
 
* http://rubybench.org/rails/rails/releases?result_type=activerecord/sqlite3_create
* http://rubybench.org/rails/rails/releases?result_type=activerecord/sqlite3_save
* http://rubybench.org/rails/rails/releases?result_type=activerecord/sqlite3_update

Benchmark Results ran on my local machine for the `sqlite3_update` benchmark: 
```
{
  "label":"activerecord/sqlite3_update",
  "version":"5.0.0.alpha",
  "iterations_per_second":6294.703952433717,
  "iterations_per_second_standard_deviation":2.0493418113829613,
  "total_allocated_objects_per_iteration":184
}

{
  "label":"activerecord/sqlite3_update",
  "version":"4.2.1",
  "iterations_per_second":6276.6898115635695,
  "iterations_per_second_standard_deviation":0.9877818063555915,
  "total_allocated_objects_per_iteration":188
}

{
  "label":"activerecord/sqlite3_update",
  "version":"4.1.10",
  "iterations_per_second":9944.386576623452,
  "iterations_per_second_standard_deviation":1.9106256432813897,
  "total_allocated_objects_per_iteration":133
}
```

Do let me know if I can provide more information and I'll be happy to help.

cc/ @sgrif @senny

**Comment by rafaelfranca** [comment]
@tgxworld thank you so much! I can't express with words how you work is important for us so I'll give you some hearts  :heart: :green_heart: :blue_heart: :yellow_heart: :purple_heart:

**Comment by sgrif** [comment]
Thanks for the additional info. There was a lot of focus on getting reads back up to speed so we could get 4.2 out, since writes are generally less of a bottleneck than reads. I have a couple of ideas of ways we can improve it, but I just haven't had time yet. This is very high up on the list, though.

**Comment by tgxworld** [comment]
@rafaelfranca :smile: 

@sgrif No worries! :smile: I just wanted to highlight those regressions first.

**Comment by sgrif** [comment]
:heart:

**Comment by kernel-io** [comment]
<3 <3

**Comment by sgrif** [comment]
Sorry for the delay in getting to this. Rails 5 now should be comparable to 4.1 in this regard. We're still slightly slower, but it's much less drastic, and I should be able to eke out several more minor improvements before we ship. Either way I think we're close enough to call this fixed.
