### ISSUE TITLE
require 'active_support/core_ext' outside of rails raises NameError

### ISSUE THREAD

**Issue by apeiros** [rails/rails#19855]
Tested with rails 4.2.0 and rails 4.2.1 on ruby 2.1.5 and 2.2.2.
Running `ruby -r active_support/core_ext -e 'p "hi"'` raises the following exception:

    .../activesupport-4.2.1/lib/active_support/core_ext/module/deprecation.rb:21:in `deprecate': uninitialized constant ActiveSupport::Deprecation (NameError)
      from .../activesupport-4.2.1/lib/active_support/core_ext/class/delegating_attributes.rb:26:in `<class:Class>'
      from .../activesupport-4.2.1/lib/active_support/core_ext/class/delegating_attributes.rb:6:in `<top (required)>'
      from ...ruby-2.2.2/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:69:in `require'
      from ...ruby-2.2.2/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:69:in `require'
      from .../activesupport-4.2.1/lib/active_support/core_ext/class.rb:2:in `<top (required)>'
      from ...ruby-2.2.2/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:121:in `require'
      from ...ruby-2.2.2/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:121:in `require'
      from .../activesupport-4.2.1/lib/active_support/core_ext.rb:2:in `block in <top (required)>'
      from .../activesupport-4.2.1/lib/active_support/core_ext.rb:1:in `each'
      from .../activesupport-4.2.1/lib/active_support/core_ext.rb:1:in `<top (required)>'
      from ...ruby-2.2.2/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:128:in `require'
      from ...ruby-2.2.2/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:128:in `rescue in require'
      from ...ruby-2.2.2/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:39:in `require'

As far as I'm aware, `require 'active_support/core_ext'` was the canonical way to load AS outside of rails and extending the core classes. Until rails 4.1.x, this works.
For other people experiencing the same problem - a momentary work-around is to require 'active_support' prior to requiring 'active_support/core_ext'.

**Comment by rafaelfranca** [comment]
> a momentary work-around is to require 'active_support' prior to requiring 'active_support/core_ext'.

It is not a work around, it is the documented way of requiring any part of the rails framework. The first think you have to do is require the top level file to setup all the common dependencies. After that you can require any file of the framework.

Thank you for the issue.

**Comment by apeiros** [comment]
@rafaelfranca please educate me - where is that documented?
Please note that in general, I consider this poor design. Requiring top-level means potentially loading everything. Better design is when every file requires its own dependencies. From past experience I guess I'll be talking to walls, though. Not sure why I try.

**Comment by matthewd** [comment]
> Requiring top-level means potentially loading everything.

I'm not sure what definition of "potentially" you're using, but for ActiveSupport, that's not how it works.

> please educate me - where is that documented?

http://guides.rubyonrails.org/active_support_core_extensions.html#stand-alone-active-support

> From past experience I guess I'll be talking to walls, though. Not sure why I try.

Nor do I. Next time, please feel free to not.

**Comment by rafaelfranca** [comment]
The top level files don't load everything, just the shared dependencies. We careful designed this so you could have the advantages of loading just what you need and we maintainers don't have to add a lot of individual requires on top of each file. We believe it is a win-win for maintainers and users.

About where it is documented, please take a look at http://guides.rubyonrails.org/active_support_core_extensions.html#stand-alone-active-support

**Comment by apeiros** [comment]
OK. Thank you for the explanation and the link. I only looked in the repository itself for documentation.

**Comment by rafaelfranca** [comment]
You are welcome. Maybe we should document it better? I only can think in a blog post, but please let me know if you have an suggestion how we can improve that
