### ISSUE TITLE
All Helpers Will Not Load in Rails 4.2.x

### ISSUE THREAD

**Issue by roberts1000** [rails/rails#19850]
I'm struggling with a helper loading issue in Rails 4.2.x.  For some unknown reason, Rails appears to be using the old helper loading strategy (i.e. ApplicationHelper is always is loaded along with the helper for the current controller - all other helpers are not loaded). 

I've compared all files in a pristine Rails 4.2.1 app and all base files are exactly the same (expect for the Gemfile of course).  So there's nothing I'm intentionally doing to force Rails into the old behavior.

I'm using Virtual Box with a Fedora image to run the Rails server and install the gems.  The code lives in a Virtual Box shared folder that can be accessed by Windows.  I use an editor in Windows to edit code and use a browser in Windows to bring up the page.  I'm in the process of building an engine that adds some enhancements, but I don't *think* I'm doing anything stupid there.  Even when I disconnect all of the Railties and other interesting code, the issue still occurs.

What's really weird is what happens when I try and debug the issue. I tried eliminating gems and commenting out code to try and identify the culprit, and every now and then I'll make a random change to a piece of completely unrelated code in the application and Rails will start working correctly.  If at that point I restart the server and try to confirm, Rails will revert and stop loading all helpers.  In essence, I can never find any realistic cause.  For instance, things magically started working when I removed the HAML gem from the application and re-bundled. The helpers loaded briefly and then the app reverted.

If I create a brand new Rails 4.2.1 application and drop in a couple helpers, it looks like everything works as expected.  On the other hand, I've stripped darn near everything out the main app and still have the problem.

I thought the issue might be related to Virtual Box and the shared folder.  Even if I completely cut out the shared folder and Windows (by moving the project to a non shared location in Fedora and using a browser from within Fedora), I still get the issue.

Our team actually builds lots of little applications.  This problem exists in all 3 apps that are piloting this engine we're building (all apps built by different developers). That seems to suggest that the engine is the root cause, but the engine isn't doing a whole lot at this point and I am able to get the correct helper loading behavior for periods of time with the engine attached.

Can anyone recommend a good place in the Rails internals where I can stick some debugging code to see why the helpers aren't being loaded?  Maybe I can get some more information.

**Comment by rafaelfranca** [comment]
Which version of Ruby are you using?

**Comment by roberts1000** [comment]
2.1.5

**Comment by rafaelfranca** [comment]
Hmm, interesting problem. It is hard to us to debug since you don't have an way to reproduce the problem in a new application. I was thinking that it is may related to an issue that we have with Ruby 2.2 and directories with mixed case (https://github.com/rails/rails/issues/18660). Also I thought that is was an issue with non matching times in the different machines (https://github.com/rails/rails/issues/12272).

Seems that both suspicions are not true since you are using 2.1 and you removed virtual box and windows from the game.

I can't think in any reason to that happen, sorry.

**Comment by aaronrussell** [comment]
I've got what sounds like exactly the same issue happening here. My project is a mounted engine on rails 4.2.x, and in development when using the mounted engine I will only have access to the `Engine::***Helper` matching the current controller.

**Comment by roberts1000** [comment]
I figured out a solution (it looks like I was using some loading/initialization hooks wrong).  I had the following railtie initializer in my engine

    initializer "my_gem_additions.action_controller" do
      ActiveSupport.on_load(:action_controller) do
        ApplicationController.include MyEngine::ApplicationControllerAdditions
      end
    end

That `include` call through the `on_load` hook was causing Rails to go crazy.  Apparently I can't fully interact with ApplicationController at this point.  When I change

    ApplicationController.include MyGem::ApplicationControllerAdditions

to

    include MyGem::ApplicationControllerAdditions  //or
    ActionController::Base.include MyGem::ApplicationControllerAdditions

everything appears to work fine.  I'm not exactly sure why I can't talk directly to `ApplicationController` in this method, but Rails probably does some other loading magic on it later on in the boot process.

Making the following change might have worked as well, but I didn't try it out

    ActiveSupport.on_load(:application_controller)

In the end, I decided to scrap the `on_load` method altogether and use `after_initialize` instead

    config.after_initialize do
      ApplicationController.include DiditRailsFramework::ApplicationControllerAdditions
    end
