### ISSUE TITLE
!! Unexpected error while processing request: undefined method `>' for nil:NilClass

### ISSUE THREAD

**Issue by manjunath-nm89** [rails/rails#19865]
I'm in the process of upgrading an app from 3.1 to 3.2.11 and eventually rails 4 and I get this error ( without any backtrace ) on my server log when I make a request from the browser. 

I'm on Ruby 1.9.3

**Comment by rafaelfranca** [comment]
You need to give us more information on how to reproduce this issue, otherwise there is nothing we can do. Please read CONTRIBUTING.md file for more information about creating bug reports. Thanks!
