### ISSUE TITLE
ActiveJob: Improve Error Message for Unpersisted Models

### ISSUE THREAD

**Issue by fny** [rails/rails#19861]
```ruby
class User
  def email_hi
    UserMailer.say_hi(self).deliver_now
  end
end
```

When switching from `deliver_now` to `deliver_later`, the following error started popping up in my tests: 

    Failure/Error: note.send_email_alert_if_issue
      URI::InvalidComponentError:
        Expected a URI like gid://app/Person/1234: #<URI::GID gid://pro-metrics>

After a long head scratching, I had used unpersisted model instances in my tests, which caused the error.

Perhaps a more job-specific error should be raised with an explanation of what went wrong?

**Comment by rafaelfranca** [comment]
cc @kaspth since I believe it is related to globalid

**Comment by fny** [comment]
Also, I'd love to take a stab at this with some guidance.

**Comment by kaspth** [comment]
@fny have at it! Find a place to rescue the error and then raise an `ArgumentError` with a message along the lines of "Can't identify and look up new records. Call save before sending email."

Submit a pull request and then we'll take it from there :smile:

**Comment by fny** [comment]
Anyway to run the test suite without install MySQL?

**Comment by rafaelfranca** [comment]
Which component are you changing? Just actionmailer?

**Comment by fny** [comment]
Nope. Just added a rescue to the end of actionjob's argument serializer.

Nevermind the previous message, I got everything working.

What are the appropriate branches to branch from and make a PR to? 4.2 or
master?

**Comment by rafaelfranca** [comment]
> What are the appropriate branches to branch from and make a PR to? 4.2 or
> master?

master

**Comment by cristianbica** [comment]
shouldn't this be added to globalid gem?

-- 
Cristian Bica

**Comment by fny** [comment]
Current thought is that `GlobalId` should raise a `GlobalId::BlankIdError`, which can later be rescued by ActiveJob, which could then raise a more specific error. See rails/globalid#68.

**Comment by fny** [comment]
What's the proper way to make a PR that depends on the unreleased addition to `GlobalID`?

**Comment by kaspth** [comment]
You could add a `gem 'globalid', github: 'rails/globalid'` line to Rails' gemfile to get things going :smile:

**Comment by fny** [comment]
Already done that, so I'll push what I've got shortly.
