### ISSUE TITLE
Active Job default inline adapter vs async one

### ISSUE THREAD

**Issue by brykov** [rails/rails#19866]
The [documentation](http://api.rubyonrails.org/classes/ActiveJob/QueueAdapters.html) for Queue Adapters enumerates a list of supported backends. The last 2 rows of a table mention built-in adapters: ```Active Job Inline``` and ```Active Job```. The last one is mentioned as asynchronous. The question is: where can I find the implementation of this adapter and how do I set up my application to use it?

As far as I can see now, there are following modules being included:
```ruby
  module QueueAdapters
    extend ActiveSupport::Autoload

    autoload :InlineAdapter
    autoload :BackburnerAdapter
    autoload :DelayedJobAdapter
    autoload :QuAdapter
    autoload :QueAdapter
    autoload :QueueClassicAdapter
    autoload :ResqueAdapter
    autoload :SidekiqAdapter
    autoload :SneakersAdapter
    autoload :SuckerPunchAdapter
    autoload :TestAdapter
  end
```

Ok, I see ```Inline``` adapter. But I see no ```Async``` one.

This is pretty confusing. Am I missing something obvious?

**Comment by rafaelfranca** [comment]
Sorry about that. That adapter doesn't exists.

Thank you for report.
