### ISSUE TITLE
ActiveRecord logger bug for binary column

### ISSUE THREAD

**Issue by pienkowskip** [rails/rails#19871]
I found out there is a problem with logging update operation when record binary field is set to `nil`. Here goes simple script which illustrates the problem:

```ruby
#!/usr/bin/env ruby

require 'active_record'

puts "Active Record #{ActiveRecord::VERSION::STRING}"

ActiveRecord::Base.establish_connection(
    :adapter  => 'sqlite3',
    :database => ':memory:'
)

ActiveRecord::Schema.define do
    create_table :variables, :force => true do |t|
        t.binary :value
    end
end

class Variable < ActiveRecord::Base
end

ActiveRecord::Base.logger = Logger.new(STDOUT)

var = Variable.new
var.value = 'abc'
var.save!
var.value = nil
var.save!
```

During the second `save!` I get such error instead of proper log message:
`E, [2015-04-23T10:48:53.992962 #14127] ERROR -- : Could not log "sql.active_record" event. NoMethodError: undefined method 'bytesize' for nil:NilClass [...`

The record is properly updated - this is a problem with logger.

My ActiveRecord version is 4.1.0.

**Comment by prathamesh-sonpatki** [comment]
@pienkowskip This issue does not exist in latest versions of Rails 4.1.10 and 4.2.1.
Please check https://gist.github.com/prathamesh-sonpatki/dbe80e376c11cdc45b02 and https://gist.github.com/prathamesh-sonpatki/7b198264ccbe8f6713fe

**Comment by pienkowskip** [comment]
Thanks! You are right.
