### ISSUE TITLE
Rails 4.2 Regression: before_configuration hook is run too late

### ISSUE THREAD

**Issue by laserlemon** [rails/rails#19880]
## The problem :cry: 

According to the [latest Rails guides](https://github.com/rails/rails/blob/f5ae289/guides/source/configuring.md#initialization-events) as of this writing:

> `before_configuration`: This is run as soon as the application constant inherits from `Rails::Application`. The `config` calls are evaluated before this happens.

Part of the issue here may be poor wording of this documentation. The meaning of the last sentence isn't entirely clear. My focus for this issue is the first sentence:

> This is run as soon as the application constant inherits from `Rails::Application`.

This was true until recently. In the latest release, `before_configuration` hooks are **not** run immediately after the application constant definition/inheritance, but should be.

## Rails :four::point_right::one:

Here's a slimmed down `config/application.rb` under Rails 4.1.10 to demonstrate:

```ruby
require "rails"

class EarlyRailtie < Rails::Railtie
  config.before_configuration do
    puts "before_configuration hook"
  end
end

module Example
  class Application < Rails::Application
    puts "before config call"
    config.foo = "bar"
    puts "after config call"
  end
end
```

When I run `bundle exec rails console`, I get the following output:

```
before_configuration hook
before config call
after config call
```

This is the expected behavior and what's described by the Rails Guides. :+1:

## Rails :four::point_right::two:

With the same `application.rb` as above, Rails 4.2.1 produces a different result:

```
before config call
before_configuration hook
after config call
```

Rails 4.2 is running `before_configuration` hooks later than should. :-1:

It looks like the `config` method is [delegated](https://github.com/rails/rails/blob/master/railties/lib/rails/railtie/configurable.rb#L9) to `instance`, which is [overridden](https://github.com/rails/rails/blob/master/railties/lib/rails/application.rb#L95-L97) in `Rails::Application` to run the load hooks. This lazy evaluation is the cause of the `before_configuration` hook's delay.

Might it work to initialize the Rails::Application instance immediately upon constant [inheritance](https://github.com/rails/rails/blob/master/railties/lib/rails/application.rb#L89-L93)?

## So what? :trollface:

The `before_configuration` hook is meant to be the earliest hook run during the Rails initialization process where one can count on Rails already being initialized with `Rails.root`, `Rails.env`, etc.

[Figaro](https://github.com/laserlemon/figaro) is a Rails configuration library so `before_configuration` is the logical choice as Figaro makes use of both `Rails.root` and `Rails.env`. With the release of Rails 4.2, there have been [reports](https://github.com/laserlemon/figaro/issues/186) of Figaro not running early enough during Rails initialization, which led me to discover this regression.

Any library that depends on the ability to run as early as possible during Rails initialization could suffer from this behavior, particularly configuration libraries.

Please let me know if I can provide any more information.

**Thank you!** :clap: :heart: :trophy: :bouquet:

**Comment by rafaelfranca** [comment]
oh man. I hate these railties problem, thank you so much for finding it.

I'll take a look why it changed and try to fix it but if anyone to do before than me please go ahead.

**Comment by laserlemon** [comment]
Thank you for the prompt attention!

**Comment by rhuppert** [comment]
I've been struggling for the past several days with parsing issues with the interpretation of Rails.application.secrets and .bashrc in 4.2.1 and ruby 2.2.2.  Perhaps there is a connection?

**Comment by pixeltrix** [comment]
I think it was probably d25fe31 that caused this because it explicitly defers instantiating the application instance so that methods can be overridden.

**Comment by kugaevsky** [comment]
@laserlemon is there any workaround there? All my application's configuration is based on `figaro` (thank you for awesome gem) and it's really hard to maintain different yml-files for almost each gem.

**Comment by laserlemon** [comment]
In Figaro's case, you can call `Figaro.load` manually immediately after the Rails application class definition, until this regression is patched.

**Comment by repinel** [comment]
As @pixeltrix suspected, I bisected and confirmed it was caused by d25fe31c40928712b5e08fe0afb567c3bc88eddf.

@rafaelfranca Do you see a way of running the hooks when inherited without losing the lazy loading feature?

**Comment by laserlemon** [comment]
Oh no! :scream: I'll try to look into whether this is still an issue on `4-2-stable` and `4-1-stable` and report back. Thank you!

**Comment by laserlemon** [comment]
As originally reported, I can confirm that this is still an issue on the `4-2-stable` branch, while the `4-1-stable` branch behaves as expected. In addition, `master` (0d2675f84f54504e5ba25b2f53b00bac239ef393) is showing the broken behavior. I believe this should be reopened as it's still an issue. Thank you!

**Comment by eileencodes** [comment]
@laserlemon the issue isn't closed, it's just marked as stale. It will be closed in the next round if still stale. I'll add it to pinned so it doesn't end up closed.

Thanks for following up :)

**Comment by AmitPatel-BoTreeConsulting** [comment]
I am not sure but I am facing the issue with config gem in Rails 4.2.5 running on Phusion Passenger in production, which could be related to this. 

http://stackoverflow.com/questions/35698111/settings-returns-nil-for-all-configurations-which-reads-from-environment-variabl

**Comment by maclover7** [comment]
@rafaelfranca @tenderlove Do we want to try to work out a solution for this, in time for Rails 5.0? This is regression from 4.1 --> 4.2 😬
