### ISSUE TITLE
AR 4.2.1 .includes give undefined method `each' for nil:NilClass

### ISSUE THREAD

**Issue by vnazarenko** [rails/rails#19891]
I use MSSQL as primary db. It use decimal(19, 0) type for ids.
I have 2 models:
```
class TaskCardImportStatus < ActiveRecord::Base
  has_many :poison_records, class: TaskCardImportPoisonRecord
....
end

class TaskCardImportPoisonRecord < ActiveRecord::Base
  belongs_to :task_card_import_status
end
```
when I try to do 
```
rows = InvoiceImportStatus.includes(:poison_records).all
```
and after that access each elements like:
```
 rows.each do |r|
   puts r.id
end
```
I get exception:
```
NoMethodError: undefined method `each' for nil:NilClass
	from /Users/viktornazarenko/.rvm/gems/ruby-2.2.1/gems/activerecord-4.2.1/lib/active_record/associations/preloader/association.rb:96:in `block in associated_records_by_owner'
	from /Users/viktornazarenko/.rvm/gems/ruby-2.2.1/gems/activerecord-4.2.1/lib/active_record/associations/preloader/association.rb:94:in `each'
	from /Users/viktornazarenko/.rvm/gems/ruby-2.2.1/gems/activerecord-4.2.1/lib/active_record/associations/preloader/association.rb:94:in `associated_records_by_owner'
	from /Users/viktornazarenko/.rvm/gems/ruby-2.2.1/gems/activerecord-4.2.1/lib/active_record/associations/preloader/collection_association.rb:13:in `preload'
	from /Users/viktornazarenko/.rvm/gems/ruby-2.2.1/gems/activerecord-4.2.1/lib/active_record/associations/preloader/association.rb:20:in `run'
	from /Users/viktornazarenko/.rvm/gems/ruby-2.2.1/gems/activerecord-4.2.1/lib/active_record/associations/preloader.rb:146:in `block (2 levels) in preloaders_for_one'
	from /Users/viktornazarenko/.rvm/gems/ruby-2.2.1/gems/activerecord-4.2.1/lib/active_record/associations/preloader.rb:144:in `each'
	from /Users/viktornazarenko/.rvm/gems/ruby-2.2.1/gems/activerecord-4.2.1/lib/active_record/associations/preloader.rb:144:in `map'
```
Looks like problem is here:
```
            records.each do |record, owner_key|
              owners_map[owner_key].each do |owner|
                records_by_owner[owner] << record
              end
            end
```
I made a small debug and found that 
owners_map do mapping by ids in float point format like this:
```
{"38.0"=>[#<InvoiceImportStatus id: #<BigDecimal:7fd29a4e4278,'0.38E2',9(18)>, completedAt:  ...}
```
But then try to access it with integer id (owner_key == "38" in this case" )
```
             owners_map[owner_key] 
```
and it will not be found in map ( "38.0" != "38" )

**Comment by senny** [comment]
@vnazarenko thank you for your report. Can you create an executable test-case to reproduce the error? You can use [this script](https://github.com/rails/rails/blob/master/guides/bug_report_templates/active_record_gem.rb) as a foundation.

**Comment by al2o3cr** [comment]
Unrelated to the root issue here, but the `class` option to `has_many` shouldn't be used - use `class_name` instead.

**Comment by Genkilabs** [comment]
I reproduced this with ```MyModel.preload(:belongs_to_model).other_scopes``` where the model joined by belongs_to can have very large ids, well over 1,000,000,000.

**Comment by senny** [comment]
@Genkilabs can you put that reproduction into executable code? You can use the script I posted above.

**Comment by vnazarenko** [comment]
Hi, the problem is in database types, so it's impossible to reproduce thin on sqllite, maximum what i could create is https://gist.github.com/vnazarenko/ab4dc7d7c26c90a515af

After investigation, i found the problem. It's simple:
# Table name: InvoiceImportStatus
#
#  id                  :decimal(19, 0)   not null, primary key

# Table name: InvoiceImportPoisonRecord
#
#  id                       :decimal(19, 0)   not null, primary key
#  invoice_import_status_id                :integer

So, it's just different data types for  primary key and foreign key. So i just fixed datatype in InvoiceImportPoisonRecord to decimal, and all is working

**Comment by Genkilabs** [comment]
Ah, thanks for the tip @vnazarenko. I'm finding this on a legacy Oracle DB where the PK and FK are a varchar2 (4). ie. whomever made this DB gave 4 character IDs to the tables. <_<
@senny I'll see if I can reproduce in your script, but if the problem arises from a nuance in Oracle then it might be gnarly.

**Comment by senny** [comment]
@Genkilabs we do not officially support Oracle. If it's a nuance that only happens with Oracle I suggest you report it on the corresponding adapter project.

**Comment by Genkilabs** [comment]
@senny Ok, thanks. The symptoms were a match so I chimed in.
For others finding their way here, I encountered this on Rails 4.0.13 using https://github.com/rsim/oracle-enhanced and Oracle 9.2.0.x

**Comment by abepetrillo** [comment]
Just hit this error myself on 4.2.5.2, using postgres. Still digging into the issue.

**Comment by josercruz01** [comment]
I'm hitting this error randomly on production, but the cause is a bit obscure. Since I can't reproduce it locally I added debugging statements and we got an insight on what's happening, but don't understand why.

It looks like the associated AR model retrieved from the database has an ID of 0 which causes the `owner_key` to be `0`. And, since the `owners_keys` has no key with value 0 then we get the exception of `undefined method `each' for nil:NilClass`.

This is the context we logged:

```
{
  "key_conversion_required" => false,
  "association_key_type" => "integer",
  "association_key_name" => "id",
  "association_class" => "Company",
  "association_record" => "#<Company id: 0, name: \"Google Inc.\", listed: nil, ... MORE FIELDS>",
  "owner_key_type" => "integer",
  "owner_key_name" => "company_id",
  "owner_key" => 0,
  "owner_class" => "Job",
  "available_owner_keys" => "[3531, 2831,  ...]",
  "klass" => "Company"
}
```

The problem is that `owner_keys` does not contain a `key=0`, which is correct since none of the owners are pointing to a company that has the ID=0. Both fields (primary_key and association_key) are integer, so no key conversion is required.

It seems that the problem is when `records_for(ids)` is called one of the records comes back with the `id=0` even though that value is not in the list of `ids`.

Any ideas on why does the AR model has an ID of 0?

**Note**: In some other logged cases, the AR model has all the fields as `nil`.

**Comment by vnazarenko** [comment]
@josercruz01 did you have the same data types in db for id and owner_id ?

**Comment by josercruz01** [comment]
@vnazarenko Yes. Both are `integer`.

The types on the DB are:

```
  CREATE TABLE jobs {
     company_id integer,
     ...
  }

  CREATE TABLE companies {
     id integer NOT NULL,
    ...
  }
```

And just to make sure the types are being read correctly I logged the types and it shows both are integer:

```
{
  "association_key_type" => "integer",  # This is the type of Company.id
  "owner_key_type" => "integer",          # This is the type of Job.company_id
  "key_conversion_required" => false
}
```

**Comment by viniciusoyama** [comment]
I'm having the same issue but it's because my column types are different. 
In one table (items) the ID is integer but in another table (for logs purpose) the item_id field's type  is string (and it must be. because sometimes people enter invalid values). 

How can I fix this? Is this really a bug or I should store the id in another column when user enters the correct value?

**Comment by timon** [comment]
Hi all,

I am also experiencing this problem, and found another cause.
We have two tables in MySQL 5.5.32 server, one references another:

``` sql
CREATE TABLE locations (id varchar(10) not null primary key, name varchar(255));
CREATE TABLE deliveries (
  id int(11) auto_increment not null primary key, 
  delivery_location_id varchar(10),
  CONSTRAINT  fk_delivery_location 
    FOREIGN KEY (delivery_location_id) REFERENCES locations (id)
);
```

For values in `delivery_location_id` column MySQL will treat values with trailing spaces to be equal to the trailing values, so, given the `locations` table is filled with some values:

```sql
INSERT INTO locations (id, name) VALUES
('BG VAZ ', 'Vadul-Siret'); -- note the trailing space in +id+ column
```

both row would be inserted:

```sql
INSERT INTO deliveries (delivery_location_id) VALUES
('BG VAZ '), -- trailing space is ok
('BG VAZ'); -- trimming the trailing space is also ok for MySQL
```

For the second record the preloader would expect database to return `'BG VAZ'` in the `id` column, but server returns `'BG VAZ '` which is not in the owner map, thus triggering the error

**Comment by steve-cmi** [comment]
I'm running into this issue with Rails 4.2.7.

I have a Contact table imported from Salesforce and User `belongs_to :contact` using those Salesforce's ID tokens as keys.

Calling `User.includes(:contact).all.group_by(&:contact)` results in the exact error above. Sounds like this is because the JOIN keys are string (Salesforce IDs) not numeric.

Calling `User.all.group_by(&:contact)` works fine but is substantially slower.

**Comment by jmccartie** [comment]
I'm having this issue as well.  Production database has primary key as `double precision` (PG).  The related tabled has its foreign key as an integer.  So when I try to run `includes`, it errors.

```
Ticket Load (86.2ms)  SELECT "tickets".* FROM "tickets" WHERE "tickets"."id" IN (380800.0)

undefined method `each' for nil:NilClass
```

I can't change the ID data type of the Ticket table (not owned by me).

**Comment by jmccartie** [comment]
@sgrif Helped me out here by letting me know how to coerce the ID out of the table.  So by adding `attribute :id, Type::Integer.new` on my model (the one with the float as a primary key), I can now properly use `includes` without hitting the `.each` error.

YMMV

**Comment by mihairadulescu** [comment]
i had the some problem when i was trying to link two tables with different collation set.
for table users: email - i had no collation set.
for table invite: email - i had utf8_general_ci collation set.
setting the same collation on the column targeted for join in the model fixes the issue.
