### ISSUE TITLE
ActiveRecord::ProtectedModel

### ISSUE THREAD

**Issue by msroot** [rails/rails#19912]
I would like to protect my model in production of of being deleted

```ruby 
require "active_record"
require 'active_record/errors'

module ActiveRecord
  
  class ProtectedModelError < ActiveRecordError #:nodoc:
    def initialize
      super("Cannot delete record because its protected")
    end
  end
  

  module ProtectedModel
    extend ActiveSupport::Concern

    protected
    def delete(*args)
      raise ProtectedModelError.new
    end
    
    def destroy_all(*args)
      raise ProtectedModelError.new
    end

    def destroy(*args)
      raise ProtectedModelError.new
    end
    
    module ClassMethods
      def delete_all(*args)
        raise ProtectedModelError.new
      end

    end
  end
end

```

My model:
```ruby
class Query < ActiveRecord::Base
  include ActiveRecord::ProtectedModel if Rails.env.production?
end
```
or for define this in `production.rb`

```bash 
2.1.3 :001 > Language.delete_all
ActiveRecord::ProtectedModelError: Cannot delete_all record because its protected
```

It would be nice if rails provide this functionality `by default` ?
I don't know if there is a functionality like this already but for me its something fundamental
If there is i couldn't find nothing till now
Of Course there is the `soft delete` but this is a different concept 
I dont know if my concept its valid or not i or what is the gotchas but why `protected_attributes` and not `protected_model`?

**Comment by rafaelfranca** [comment]
Thank you so much for the issue but we don't take feature request on the issue tracker. We recommend you to try to implement the feature and send us a pull request or if you are in doubt if the feature will be accepts ask in Rails Core mailing list for feedback.
