### ISSUE TITLE
ActionController render_to_string() converting HTML to unicode characters

### ISSUE THREAD

**Issue by matisoffn** [rails/rails#19946]
I have the line below in a method in one of my Rails controllers:

```ruby
def template
  render json: { :template => render_to_string(:template => "emails/template.html.erb") }
end
```

The JSON in the HTTP response has converted all of the HTML characters to unicode, ex: `<` to `\u003c`.  Why does this convert to unicode by default, and how can I tell Rails not to convert the HTML to unicode characters?

**Comment by matthewd** [comment]
Please use the mailing list or StackOverflow for questions/help, where a wider community will be able to help you. We reserve the issues tracker for issues only.

**Comment by matisoffn** [comment]
This isn't an issue?  Shouldn't it convert it to an HTML string?
