### ISSUE TITLE
Add deprecation message for ActionController::Parameters...?

### ISSUE THREAD

**Issue by PikachuEXE** [rails/rails#19951]
In 5109740c6be67047df56feb164012c3a1a3c619b, `ActionController::Parameters`'s inheritance from `HashWithIndifferentAccess` is stated to be deprecated (although not yet according to master)

I think methods which exists in `HashWithIndifferentAccess` (and thus `Hash` as well) but not in `ActionController::Parameters` should have deprecation message.

**Comment by rafaelfranca** [comment]
Thank you for the suggestion but we will take the path of letting it raise a no method error.  since those methods may not work correctly right now, there is no point to deprecate them.
