### ISSUE TITLE
hash is implemented suboptimally for ActiveRecord instances with no id

### ISSUE THREAD

**Issue by z5h** [rails/rails#19958]
The default ActiveRecord hash implementation is to return the hash of the id.

This is great for persisted instances. It's terrible for un-persisted instances especially because Rails defaults to BasicObject.== for ActiveRecord instances with no IDs.

So all unsaved ActiveRecord instances will have the same hash and not be equal. This is a worst-case scenario for performance of putting many un-persisted ActiveRecord instances into a Set (for example).

Could we do

    def hash
      id ? id.hash : object_id
    end

Happy to make a PR if this sounds reasonable.

**Comment by matthewd** [comment]
[activerecord/lib/active_record/core.rb#L416-L422](https://github.com/rails/rails/blob/8cf22cefd4e44b6dae1152b4fddea240c7ee479b/activerecord/lib/active_record/core.rb#L416-L422)
