### ISSUE TITLE
Rails 4.2: using aliased attribute in joined relation's where condition

### ISSUE THREAD

**Issue by bostrom** [rails/rails#19955]
So I came across this behavior today while querying a model using the joined-in model's aliased attribute as condition:
```
class Author < ActiveRecord::Base
  has_many :books
end
class Book < ActiveRecord::Base
  belongs_to :author
  alias_attribute :title, :name
end
```
Now with this setup, the query 
```
Author.joins(:books).where(books: {title: 'Pippi Longstocking'})
```
Fails with 
```
Unknown column 'books.title' in 'where clause': 
  SELECT  `authors`.* FROM `authors` 
  INNER JOIN `books` ON `books`.`author_id` = `authors`.`id` 
  WHERE `books`.`title` = 'Pippi Longstocking' ORDER BY `authors`.`id` ASC
```
Is this expected behavior, not being able to use the attribute alias in a where condition like this, or am I doing something wrong?

A normal where condition on the Books model works fine:

```
Book.where(title: 'Pippi Longstocking')
```

Working test case here: https://gist.github.com/bostrom/aa2fe1ca8ccce6caf0ea/abd090fdb16e6c4f21cd8c4a60af435d74da4e4d

**Comment by sgrif** [comment]
This is the expected behavior, but the ability to use things like aliased attributes or custom types through a join will improve in 5.0
