### ISSUE TITLE
When running cache_digests dependency rake tasks, notify if file not found

### ISSUE THREAD

**Issue by travisp** [rails/rails#19968]
Currently ActionView::Digestor silently fails if it's not able to find the provided template.

````
rescue ActionView::MissingTemplate
  [] # File doesn't exist, so no dependencies
end
````

When using the rake task to look up nested dependencies this makes it difficult to know if a bad template name has been provided or not.

**Comment by rafaelfranca** [comment]
Yeah, you are right. Could you open a PR?
