### ISSUE TITLE
Rails 4.2: ActiveRecord enum builds incorrect query when used with string or symbol

### ISSUE THREAD

**Issue by jacekgrzybowski** [rails/rails#19964]
Happens to me when working with `Rails 4.2.0 and Ruby 2.2.1`.

My enum definition:

    class Example < ActiveRecord::Base
      enum status: [:active, :unrolled, :rewarded]
      ...
    end

Scope works properly:

    2.2.1 :001 > Example.unrolled 
    Example Load (0.5ms)  SELECT `examples`.* FROM `examples` WHERE `examples`.`status` = 1  

However, according to the docs, when querying with not, I should pass a symbol to the `where` clause:

    2.2.1 :002 >   Example.where.not(status: :unrolled)
    Example Load (0.2ms)  SELECT `examples`.* FROM `examples` WHERE (`examples`.`status` != NULL) 

Same thing happens without `not`:

    2.2.1 :003 > Example.where(status: :unrolled)
    Example Load (0.4ms)  SELECT `examples`.* FROM `examples` WHERE `examples`.`status` = NULL

I also tried with string - in this case instead of `NULL`, `0` is put into the clause:

    2.2.1 :004 > Example.where.not(status: 'unrolled')
    Example Load (0.3ms)  SELECT `examples`.* FROM `examples` WHERE (`examples`.`status` != 0)

And with querying with multiple statuses:

    2.2.1 :005 > Example.where(status: [:active, :rewarded]) 
    Example Load (0.4ms)  SELECT `examples`.* FROM `examples` WHERE `examples`.`status` IN (NULL, NULL)

**Comment by matthewd** [comment]
As far as I'm aware, those spellings aren't supported. If documentation claims otherwise, I think it's the thing that's wrong.

**Comment by jacekgrzybowski** [comment]
Well, you might be right.
https://github.com/rails/rails/blob/master/activerecord/lib/active_record/enum.rb#L35-L39

**Comment by rafaelfranca** [comment]
@sgrif I think you changed something about this right?

**Comment by sgrif** [comment]
Yes, this works on master. It has never worked in 4.x. Passing enum values to where isn't supported prior to Rails 5.

**Comment by cireficc** [comment]
@sgrif Is this mentioned *anywhere*? I just spent about 2 hours wondering why `0` was always passed into the `where` clause...

**Comment by rafaelfranca** [comment]
Yes, it is. http://api.rubyonrails.org/v4.2/classes/ActiveRecord/Enum.html

**Comment by cireficc** [comment]
@rafaelfranca Thanks for that. I swear that I've read that doc before, but maybe not thoroughly enough. Good to know in any case, I'm glad that Rails 5 made this a bit easier!
