### ISSUE TITLE
image-url in background vs background-image properties behave differently?

### ISSUE THREAD

**Issue by sxasraf** [rails/rails#19985]
For some reason, this:

    &.female {
        // compiles into: background-url: url('/images/avatar-blank-female.png');
        background-url: image-url('avatar-blank-female.png');
    }

Is different than this:

    &.female {
        // compiles into: background: url('/assets/avatar-blank-female.png') no-repeat center center;
        background: image-url('avatar-blank-female.png') no-repeat center center;
        background-size: cover;
    }

Notice the difference in the `/images/` vs `/assets/`? The former doesn't work, it's a 404. Not sure why it should behave differently.

I found this out because I was giving `.avatar` a default image, and overrode it with `.female` when necessary. I wanted to only override the image URL and not it's position/repitition etc, but now I have to explicitly fully specify the properties on both.

Am I missing something or is this a bug?

I'm using Rails 4.1.7, Ruby 2.1.5.

Thanks

**Comment by kaspth** [comment]
Please use StackOverflow or the ruby on rails talk mailing list for questions like these. There's a wider community to help you there. Thanks :heart:
