### ISSUE TITLE
rake db:schema:dump is incorrectly setting default: nil on postgres tables using uuid identifiers

### ISSUE THREAD

**Issue by desaperados** [rails/rails#20020]
Rails version 4.2.1

Using the uuid-ossp postgres extension for uuid identifiers and have the following schema.rb and postgres output as you would expect:

````ruby
# db/schema.rb

enable_extension "uuid-ossp"

create_table "users", id: :uuid, force: :cascade do |t|
  t.string   "name", limit: 255
end
````
````
\d users;

      Column      |            Type        |               Modifiers
------------------+------------------------+----------------------------------------
 id               | uuid                   | not null default uuid_generate_v4()
 name             | character varying(255) |
````

However, running rake db:schema:dump is introducing `default: nil` into the table declaration which breaks uuid functionality:

````
rake db:schema:dump
git diff

diff --git a/db/schema.rb b/db/schema.rb

-  create_table "users", id: :uuid, force: :cascade do |t|
+  create_table "users", id: :uuid, default: nil, force: :cascade do |t|
````

Which is overriding the `uuid_generate_v4()` default required for uuids to work. The resulting error is a by product of the missing `default uuid_generate_v4()` and obvious incompatibility of both default: nil and not null.

> ActiveRecord::StatementInvalid: PG::NotNullViolation: ERROR:  null value in column "id" violates not-null constraint

**Comment by nixpulvis** [comment]
I cannot recreate this issue in a Rails 4.2.1 application I have. I tried running removing my schema.rb then running `rake db:schema:dump` and it worked as expected with no diff in git.

**Comment by desaperados** [comment]
I've narrowed this down a bit more and found the behaviour is actually being caused by the active record postgis adapter where an issue has already been raised https://github.com/rgeo/activerecord-postgis-adapter/issues/175
