### ISSUE TITLE
Schema dump support for multiple schemas

### ISSUE THREAD

**Issue by stenver** [rails/rails#20033]
What do you guys think of adding support for multiple schemas in the schema dump. The way it would work is instead of exporting 
```create_table 'table_name' ``` in schema.rb, it would 
```create_table 'schema.table_name'```
This could be figured with some configuration flag.

I would be happy to work on this PR myself if you guys think its a good idea. If not, please let me know why not.

**Comment by matthewd** [comment]
Per the [contribution guidelines](https://github.com/rails/rails/blob/master/CONTRIBUTING.md), we prefer to keep the issue tracker for issues only; feature discussions should occur on the mailing list.

Thanks!
