### ISSUE TITLE
Calling `.primary_key` before schema is defined incorrectly returns "id"

### ISSUE THREAD

**Issue by nixpulvis** [rails/rails#20037]
The following code example demonstrates how calling `.primary_key` on a model before the schema is loaded not only returns `"id"` but also sets the primary key to `'id"` for future calls.

```ruby
unless File.exist?('Gemfile')
  File.write('Gemfile', <<-GEMFILE)
    source 'https://rubygems.org'
    gem 'rails', github: 'rails/rails'
    gem 'arel', github: 'rails/arel'
    gem 'sqlite3'
    gem 'pry'
  GEMFILE

  system 'bundle'
end

require 'bundler'
Bundler.setup(:default)

require 'active_record'
require 'minitest/autorun'
require 'logger'
require 'pry'

# This connection will do for database-independent bug reports.
ActiveRecord::Base.establish_connection(adapter: 'sqlite3', database: ':memory:')
ActiveRecord::Base.logger = Logger.new(STDOUT)

class Foo < ActiveRecord::Base
  primary_key # Calling `.primary_key`
end

class Bar < ActiveRecord::Base
end

ActiveRecord::Schema.define do
  create_table :foos, id: false, force: true  do |t|
    t.timestamps
  end
  create_table :bars, id: false, force: true  do |t|
    t.timestamps
  end
  create_table :bazs, id: false, force: true  do |t|
    t.timestamps
  end
end

class Baz < ActiveRecord::Base
end

class BugTest < Minitest::Test
  def test_primary_keys
    assert_equal nil, Foo.primary_key
    assert_equal nil, Bar.primary_key
    assert_equal nil, Baz.primary_key
  end
end
```

**Comment by senny** [comment]
I'm not sure this is a bug. Active Record uses the database to define your models schema. If you use a model without an existing table to infer the schema from, Active Record is forced to fall back on defaults. Adding such table later on of course invalidates these assumptions. To update the models schema we have `Foo.reset_column_information`.

/cc @sgrif @rafaelfranca

**Comment by nixpulvis** [comment]
I just feel that a primary key of nil would be a more sane choice given the lack of a database.

**Comment by rafaelfranca** [comment]
Yes, if that is your case you should reset the column information after the schema is loaded, or on Rails 5 define the attributes by yourself with the attributes API.

**Comment by nixpulvis** [comment]
Eh I guess this is a weird use case, but I still think telling people your primary key is `"id"` when it's not defined is misleading.
