### ISSUE TITLE
Flash message not being displayed while rescuing from ActionController::InvalidAuthenticityToken

### ISSUE THREAD

**Issue by prakashmurthy** [rails/rails#20035]
I am trying to rescue from ActionController::InvalidAuthenticityToken in the application controller with the following code:

```
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  rescue_from ActionController::InvalidAuthenticityToken, with: :show_errors

  ....

  private

  def show_errors
    redirect_to root_path, alert: "Cookies are disabled"
  end
end
```

The redirect works fine, but the alert message does not show. The flash hash is empty in the new page: `#<ActionDispatch::Flash::FlashHash:0x007f9dbdb5c1d0 @discard=#<Set: {}>, @flashes={}, @now=nil>`

There are no other filters in the application controller that could be affecting the hash / causing another redirect. The logs show only one redirect as expected.

Tried `flash.keep[:alert] = ..` and `flash.now[:alert] = ..` as well; no luck.

Getting this behavior on two different rails apps, one with 4.2.0 and another with 4.1.6.

**Comment by pixeltrix** [comment]
Since flash is dependent on the session and the session is dependent on cookies working then it's never going to work if you think about it, :smile:

I'd suggest redirecting to a custom url or add a query param to the url that triggers the display of the message. Sorry, there's nothing else we can do.

**Comment by prakashmurthy** [comment]
Thanks @pixeltrix That does make sense. Will redirect to a custom url.
