### ISSUE TITLE
Rails session_store custom session_options are ignored in testing environment

### ISSUE THREAD

**Issue by kaelumania** [rails/rails#20043]
We experienced a Problem using a custom session store and some optional session_options in our testing environment for controller tests. Our rails configuration contains the following line:

`Rails.application.config.session_store :active_record_store_with_url_parameter, session_key: '_my_session_key'`

Everything is fine when we start up the development environment and the session variable in our controller is filled with our additional session_options. But in our testing environment, e.g. `bundle exec rspec`, the additional options are missing. The custom session store is setup correctly except the `session_options`. I already talked to an rspec maintainer and he concludes that it must be an issue with rails.

**Comment by ChristianPeters** [comment]
I am a team mate of @kaelumania and had a chance to dig a bit deeper into this.

We are talking about RSpec controller specs which are a wrapper for a Rails functional test using [ActionController::TestCase::Behavior](https://github.com/rails/rails/blob/e260975baf5b1a54d03ecd685f62f697871b9b65/actionpack/lib/action_controller/test_case.rb).

The `session_options` seem to be picked up only [in the Rails::Application::DefaultMiddlewareStack](https://github.com/rails/rails/blob/2d04bdd86fb4a9c69e1ca1ffe92188a9ca4f88c8/railties/lib/rails/application/default_middleware_stack.rb#L51).

Rails functional tests can be seen as unit tests of controllers and don't include the Rake middleware stack – this seems to be our problem.

Nonetheless, there is a `session` available in our functional tests which seems to be a [`TestSession`](https://github.com/rails/rails/blob/e260975baf5b1a54d03ecd685f62f697871b9b65/actionpack/lib/action_controller/test_case.rb#L305) provided by [`TestRequest`](https://github.com/rails/rails/blob/e260975baf5b1a54d03ecd685f62f697871b9b65/actionpack/lib/action_controller/test_case.rb#L203).

Shouldn't the Rails session configuration go into the equation there somewhere? Should the functional test really be independent from the Rails configuration?

**Comment by senny** [comment]
Can you reproduce this error with Rails integration tests? Functional tests try to exercise the controllers in isolation. Request, response etc. are stub objects to connect the dots. It seems that what you are looking for is what Rails calls integration tests. They will go through the middleware stack and should use proper configuration.

On a side note, we are moving away from functional tests and try to implement them on top of integration tests (for backwards compatibility).
