### ISSUE TITLE
assert_file fails when filename has special characters (~, +)

### ISSUE THREAD

**Issue by pravi** [rails/rails#20042]
See https://github.com/mperham/sidekiq/issues/2065 for background. These are used to give special meanings to package names in debian (x.y.z~something, means a lower version of x.y.z. this is used to convey ~alpha, ~beta or ~rc should be updated by x.y.z version). I hope this will will be fixed.

**Comment by senny** [comment]
After a first glimpse I think this is caused by https://github.com/rails/rails/pull/12606/files#diff-790f18b5ff852b81b7b3784b5ce52a79R24

I'll take a look.

**Comment by senny** [comment]
A fix is merged and backported to `4-2-stable`. Will be released with the next non-security `4.2.x` release.

@pravi thanks for reporting :yellow_heart:
