### ISSUE TITLE
remove_foreign_key do not remove fk index from mysql database

### ISSUE THREAD

**Issue by chenghung** [rails/rails#20048]
rails 4.2.1
mysql 5.6

```
$ rake db:migrate 
== 20150506143859 Test: migrating =============================================
-- add_foreign_key(:albums, :users)
   -> 0.9685s
== 20150506143859 Test: migrated (0.9687s) ====================================
```

```
$ rake db:rollback
== 20150506143859 Test: reverting =============================================
-- remove_foreign_key(:albums, :users)
   -> 0.1299s
== 20150506143859 Test: reverted (0.1300s) ====================================
```

execute rake db:rollback without errors
but fk_index still in database

**Comment by al2o3cr** [comment]
Can you show the database structure before and after the rollback? I'm not clear on what you mean by "fk_index".

**Comment by pascalbetz** [comment]
AFAIK: 
MySQL requires an index for FK constraints.
When a FK constraint is created then an index is created by MySQL automatically.
This index can not be dropped without dropping the FK first, MySQL will complain that it is required for the FK constraint.

If you drop the FK through a migration then the index is not removed (as it was not added though the migration in the first place).

**Comment by al2o3cr** [comment]
I've observed this behavior in the real world.
Example:

Given this initial database schema:
```sql
CREATE TABLE `parents` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`id`)
)

CREATE TABLE `children` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `parent_id` int(11) NOT NULL,
  PRIMARY KEY (`id`)
)
```

Then adding a foreign key constraint to `children.parent_id` will produce a new schema like this:
```sql
ALTER TABLE `children`
  ADD CONSTRAINT `foo_bar`
  FOREIGN KEY (`parent_id`)
  REFERENCES `parents` (`id`);
```
```sql
CREATE TABLE `children` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `parent_id` int(11) NOT NULL,
  PRIMARY KEY (`id`),
  KEY `foo_bar` (`parent_id`),
  CONSTRAINT `foo_bar` FOREIGN KEY (`parent_id`) REFERENCES `parents` (`id`)
)
```
So the name of the constraint is also used to name the index.

BUT, if an index that has the specified columns first and in the right order is already present, MySQL will not create an additional one. So in this example, if `children` already had an index on `parent_id` a second one would not be created when the foreign key was added.

Dropping the foreign key does not drop the index, even if it was created automatically:
```sql
ALTER TABLE `children` DROP FOREIGN KEY `foo_bar`;
```
```sql
CREATE TABLE `children` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `parent_id` int(11) NOT NULL,
  PRIMARY KEY (`id`),
  KEY `foo_bar` (`parent_id`)
)
```

One further thing: the automatically-created index will silently disappear if an equivalent index is added manually. So given the schema with foreign key constraint named `foo_bar`, adding a manual index on `parent_id` has this result:
```sql
ALTER TABLE `children` ADD INDEX (`parent_id`);
```
```sql
CREATE TABLE `children` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `parent_id` int(11) NOT NULL,
  PRIMARY KEY (`id`),
  KEY `parent_id` (`parent_id`), -- NOTE THAT THIS HAS CHANGED
  CONSTRAINT `foo_bar` FOREIGN KEY (`parent_id`) REFERENCES `parents` (`id`)
)
```

I'm unsure what the desired behavior should be; on the one hand, it's a fairly surprising result that creating an FK and then rolling it back leaves the DB in a potentially-altered state (if the index didn't exist previously). On the other hand, unexpectedly dropping an index is also surprising (and expensive in production, potentially).

**Comment by jaredbeck** [comment]
This is still an issue in rails 5.0.2.

**Comment by ispyropoulos** [comment]
Maybe the correct way to go with this would be to raise an error when using `add_foreign_key` to begin with, in the case where an index is not already there. This way, a explicit migration to add an index will be required beforehand.

Then both migrations will be reversible and the database will not be left at altered state after rolling them back.
