### ISSUE TITLE
Problem with MaterializeCSS (toast)

### ISSUE THREAD

**Issue by matbrb2** [rails/rails#20059]
Hello,
For my website, i need to use Materialize.toast for notification, but it doesn't work.
The part of code is : <code> <? if ($_SESSION['delete'] = 'ok') {echo"
<script type='text/javascript'>Materialize.toast('I am a toast', 4000)</script>";
}
</code>

Thank :)

**Comment by rafaelfranca** [comment]
Please use the mailing list or StackOverflow for questions/help, where a wider community will be able to help you. We reserve the issues tracker for issues only.

**Comment by matbrb2** [comment]
Thanks!
