### ISSUE TITLE
Thoughts on GraphQL and Relay?

### ISSUE THREAD

**Issue by imton** [rails/rails#20052]
I was watching the way facebook is building their new apps and how they are modeling and fetching data.

As the evolution of React they now let components declarative state which data they need and state that in GraphQL. Is it kind of the end of REST endpoints for this model?

I really feel this is the future of writing software for many different platforms. Shouldn't Rails be part of it?

I invite you to watch key presentations:

- [F8 2015 - React Native & Relay: Bringing Modern Web Techniques to Mobile](
https://www.youtube.com/watch?v=X6YbAKiLCLU&list=PLb0IAmt7-GS1_7FcSupSJoUe21tF12eu8&index=1)
- [React.js Conf 2015 - Data fetching for React applications at Facebook](
https://www.youtube.com/watch?v=9sc8Pyc51uU)

And the docs:

- [GraphQL Introduction](https://facebook.github.io/react/blog/2015/05/01/graphql-introduction.html)
- [Introducing Relay and GraphQL](https://facebook.github.io/react/blog/2015/02/20/introducing-relay-and-graphql.html)

**Comment by senny** [comment]
@imton we use the GitHub issue tracker for bug reports and pull request discussions. Please use the [rubyonrails-core mailing list](https://groups.google.com/forum/?fromgroups#!forum/rubyonrails-core) for feature discussions and suggestions.

You can find more details in our [contribution guidelines](https://github.com/rails/rails/blob/master/CONTRIBUTING.md).

**Comment by ncri** [comment]
Highly interested in this too, did you start a discussion at the mailing list @imton? Didn't find any yet...

**Comment by imton** [comment]
@ncri no time yet, still interested on this.

**Comment by barsukov** [comment]
It is very important staff I think. What I found a gem called https://github.com/rmosolgo/graphql-ruby but it should be support in rails I think. I did not found anything in the google group about that. Why it is so slow reaction? :)
