### ISSUE TITLE
Asset Pipeline can't find compiled resource in production for an asset directory shared by the app and a gem.

### ISSUE THREAD

**Issue by robertleelittleiii** [rails/rails#20053]
Noticed this issue while using tinymce-rails gem

Rails 4.2.0 allows asset to be loaded (after precompile) from local asset directory.  I have a custom js plugin for tinymce-rails.  This plugin has a path in assets of:

/assets/javascripts/tinymce/plugins/codemirror/plugin.js

In Rails 4.2.1 the asset is not found even though it is in the compiled assets directory.  The gem has the same path: /assets/javascripts/tinymce/plugins/ for the pre-installed plugins.   (see gem on git hub https://github.com/spohlenz/tinymce-rails)  Those plugin.js files are available via the URL, the local application plugin is not found.

**Comment by rafaelfranca** [comment]
Can you please provide a sample application that reproduces the error?
