### ISSUE TITLE
why rails new xx failed on win7 x64?

### ISSUE THREAD

**Issue by afilter** [rails/rails#20069]
`rails new xxx`

...

Using jbuilder 2.2.13

**Gem::RemoteFetcher::FetchError: Errno::ECONNABORTED: An established connection was aborted by the software in your host machine. - SSL_connect** (https://rubygems.org/gems/jquery-rails-4.0.3.gem
)
An error occurred while installing jquery-rails (4.0.3), and Bundler cannot
continue.
Make sure that `gem install jquery-rails -v '4.0.3'` succeeds before bundling.

**Comment by Rohnin** [comment]
Maybe firewall or antivirus problem?

**Comment by robin850** [comment]
Hi!

We are sorry but this tracker is for issues only, not support. You can ask such questions on StackOverflow of the [rails-talk](https://groups.google.com/forum/#!forum/rubyonrails-talk) mailing list. Also it looks like this is a RubyGems and not a Rails problem. Thanks!
