### ISSUE TITLE
PG::ProtocolViolation: ERROR:  bind message supplies 0 parameters, but prepared statement "" requires 1

### ISSUE THREAD

**Issue by cxz** [rails/rails#20077]
This issue is related to:
#12753
#18469
#17983
#17770

Test case:
https://gist.github.com/cxz/64efd78be1167a66f127

Activerecord: 4.2.1
Bug happens only with **postgresql** (works fine with sqlite3).

In summary:
```
from(arel_table.create_table_alias(where(id: 1).arel, table_name))
```
fails with:
```
PG::ProtocolViolation: ERROR:  bind message supplies 0 parameters, but prepared statement "" requires 1
: SELECT "posts".* FROM (SELECT "posts".* FROM "posts" WHERE "posts"."id" = $1) "posts"
```

**Comment by meinac** [comment]
Actually the bug is not about postgresql adapter. If you inspect your query with sqlite3, you can see that there is no parameters sending with the query. 
The only reason this will raise an exception with postgre is postgre validates the query. I'll dig into this today.

**Comment by meinac** [comment]
I've found the problem but it requires lots of changes in both arel and activerecord.
The breaking change is in https://github.com/rails/arel/commit/590c784a30b13153667f8db7915998d7731e24e5 this commit.

**Comment by norman** [comment]
Just tried updating my app from 4.0 to 4.2 again, and I get this error in pretty much everywhere. Happy to lend a hand fixing it.

**Comment by norman** [comment]
Another facet to this bug: to try to get my specs to run, I added `prepared_statements: false` to my database.yml, but Arel then simply omits the bind parameter, generating an invalid statement:

    WHERE "unsubscriptions"."message_id" = $1 AND "users...

versus:

    WHERE "unsubscriptions"."message_id" =  AND "users...

**Comment by joshukraine** [comment]
I'm trying to update a Rails app from 4.0.13 to 4.2.1. I have quite a few failing specs with a very similar error:

```sh
ActiveRecord::StatementInvalid in StudentsController#create
PG::ProtocolViolation: ERROR: bind message supplies 3 parameters, but prepared statement "a12" requires 4 : SELECT 1 AS one FROM "lessons" WHERE "lessons"."student_id" = $1 AND "lessons"."student_id" = $2 AND "lessons"."number" = $3 AND "lessons"."status" = $4 LIMIT 1
```

Just curious if there has been any progress in fixing this issue? Any suggestions for an interim workaround? Thanks!

**Comment by norman** [comment]
@joshukraine I am affected by this issue in an application that uses Arel to generate EXISTS clauses in code similar to the below example:

```ruby
def foobar
  scope = where(:column => 'value')
  scope = scope.where(arel_table[:id].eq(Bar.arel_table[:foo_id]))
  where(scope.exists)
end
```

The workaround for me was to invoke `to_sql` on the scope and pass the resulting SQL string into the WHERE clause:

```ruby
def foobar
  scope = where(:column => 'value')
  scope = scope.where(arel_table[:id].eq(Bar.arel_table[:foo_id]))
  where("EXISTS #{scope.to_sql}")
end
```

**Comment by joshukraine** [comment]
@norman Thanks for the info! I'll give that a try and see what I can work out.

**Comment by mbhnyc** [comment]
Checking on this issue, is there a workaround for 4.2.1 or 4.2.0, or are we stuck?

**Comment by matthewd** [comment]
Raw Arel + Relation binds don't mix very well.

The short answer is that these sorts of rough edges are why Arel's not part of the officially supported API.

The longer answer is: patches welcome. :smile:

**Comment by mbhnyc** [comment]
Indeed :)  Well, @norman's fix is very good, `to_sql`'ing the fragments and then combining them using execute did the trick.

**Comment by ClayShentrup** [comment]
Why was this issue closed? The bug seems alive and well for me on Rails 4.2.5.

**Comment by sevenseacat** [comment]
@ClayShentrup likely because 

> The short answer is that these sorts of rough edges are why Arel's not part of the officially supported API.

You're using a private API externally, things aren't always going to work as expected, or be stable. Use at your own peril.

**Comment by ClayShentrup** [comment]
@sevenseacat Jes, mi vidis tion post mi demandis mian demandon. Dankon.

**Comment by sevenseacat** [comment]
@ClayShentrup nedankinde ;)

**Comment by TrevorHinesley** [comment]
This is still very much a problem, even without Arel. For instance, I have a scope that joins on a polymorphic join table, counts the uniq results and returns those with at least that many matches.

Here's the scope:

```ruby
has_many :taggable_tags, as: :taggable, dependent: :destroy
has_many :tags, through: :taggable_tags

scope :with_all_tags, -> (tag_ids) { where id: select(:id).distinct
                                                            .joins(:tags)
                                                            .where(tags: { id: tag_ids })
                                                            .group("songs.id")
                                                            .having("count(tags.id) = ?", tag_ids.size) }
```

Tags are 

The error (when passing an array to tag_ids, which worked before making taggable_tags polymorphic, it used to only have a belongs_to :song):

```
ActiveRecord::StatementInvalid: PG::ProtocolViolation: ERROR:  bind message supplies 0 parameters, but prepared statement "" requires 1
: SELECT "songs".* FROM "songs" WHERE "songs"."id" IN (SELECT DISTINCT "songs"."id" FROM "songs" INNER JOIN "taggable_tags" ON "taggable_tags"."taggable_id" = "songs"."id" AND "taggable_tags"."taggable_type" = $1 INNER JOIN "tags" ON "tags"."id" = "taggable_tags"."tag_id" WHERE "tags"."id" = 1 GROUP BY songs.id HAVING count(tags.id) = 1)
```

**Comment by januszm** [comment]
So to avoid that we should just avoid using Arel whenver possible? ;) Just curious, I've noticed that error message that lead me here when I tried to upgrade a legacy app to 4.2.7. Apparently the app uses a lot of Arel (sigh :/ )

**Comment by samuel012** [comment]
I accidentally found a workaround while I was playing with a different query. I think my workaround will be related to the OP's issue. I passed the Id inside an array instead of just passing a literal id.

try this:

`from(arel_table.create_table_alias(where(id: [1]).arel, table_name))`

I dunno why it works, but it does.

I'm using **4.2.4** btw.

**Comment by Kache** [comment]
I'm finding that this bug can occur even without explicit use of Arel, and just with nested AR relations. My current workaround in an old version of AR is to avoid using prepared statements.

Example, forked from @cxz 's original testcase: https://gist.github.com/Kache/524a475cffc2191c97a6580949892c03

(This bug appears fixed for me when I use 4.2.1, though, which doesn't match the original report)

**Comment by jrochkind** [comment]
I have had a similar problem show up in Rails 5 that did not occur in the same app in Rails 4.2. Anyone have any info on Rails 5-era regressions here?

**Comment by fernandobrito** [comment]
Upgraing Rails from 4.2.1 to 4.28 caused the query:

```
  def self.with_no_measures
    where(SchoolMeasure.where(school_id: self.arel_table[:id]).exists.not)
  end
```

To raise: 
`ERROR:  bind message supplies 1 parameters, but prepared statement "a33" requires 3`

However, @samuel012's suggestion of adding id to array fixed the issue!

```
  def self.with_no_scoring_data
    where(SchoolDatum.where(school_id: [self.arel_table[:id]]).exists.not)
  end
```

Thanks, Samuel! :+1:

**Comment by coorasse** [comment]
This issue is still alive also with Arel 8 and Rails 5.1. @samuel012 saved my day!

**Comment by schmijos** [comment]
Having this issue also with Rails 5.0 and Rails 5.1. Solved it with the brackets trick for now.

**Comment by andrewculver** [comment]
I think we've started running into this issue when trying to upgrade to Rails 5.2.0-rc1. We've had the following authorization defined in CanCanCan for ages:

```
can :manage, Team, id: user.administrating_team_ids
can :read, Team, id: user.team_ids
```

But the following error now happens when we try to hit teams#index:

```
ActionView::Template::Error: PG::ProtocolViolation: ERROR:  bind message supplies 0 parameters, but prepared statement "" requires 2
: SELECT "teams".* FROM "teams" WHERE (("teams"."id" IN ($1, $2)) OR ("teams"."id" = $1))
```

(In that case, the user had one team they administrate and two teams they're a member of. Seems weird that the prepared statement has `$1` twice. I would not expect that.)

I'll file the issue with CanCanCan, but my guess is we're being affected by this same issue, so I wanted to share this incase it's helpful at all.

**Comment by LuisDeHaro** [comment]
Is there other options besides the brackets trick?

I just upgraded from Rails 4.2.6 to 5.0.7 and basically half of my queries are now broken.

The brackets work but, what's the ultimate solution for this?

**Comment by bendilley** [comment]
@norman just want to thank you 4 years later: your Arel `exists` scenario was exactly what I was battling with today and your workaround is a good compromise that manages not to ruin the code's readability 🙇
