### ISSUE TITLE
Create association with override reference

### ISSUE THREAD

**Issue by lorenso** [rails/rails#20084]
Hi, when i creating association with override reference (ex: role allow set user_id) - 
user_id not override.

```
class User < ActiveRecord::Base
  has_many :projects
end
```

```
class Project < ActiveRecord::Base
  belongs_to :user
end
```

current user id = 1

```
project = current_user.projects.create({ user_id: 2 })
```

Created object with user_id = 1

Bug or correctly?

ps sorry for bad english:)

**Comment by matthewd** [comment]
Yeah, that's expected behaviour.
