### ISSUE TITLE
I18n locale not automatically reset to defaul

### ISSUE THREAD

**Issue by SDEagle** [rails/rails#20091]
Recently worked on a rails app where we activated i18n for some admin sites but not for the main site (defining translations with the glaobalize gem, but not rolling them out yet). So the AdminController had some before_filter :set_locale, the ApplicationController did not. We were expecting the main site to stick to the default locale but it turned out, that if you have the main site in one tab and in another the admin site, when you change the locale in the admin site and reload the main site tab it actually reflects the locale change.

A minimal app (fresh rails 4.2.1, ruby 2.2.0) to reproduce can be found here https://github.com/SDEagle/i18n-isolation
The gist of it: `application.rb` specifies default locale to `:en` and there is a controller which looks like this:
```ruby
class LocalsController < ApplicationController
  def german
    I18n.locale = :de
    render :language
  end

  def english
    I18n.locale = :en
    render :language
  end

  def language
  end
end
```

If you visit `language` alone, you get the default locale `:en` as expected but if you visit first `german` and then immediately afterwords `language` you surprisingly get `:de`. It changes back after a minute or so, though.

**Comment by rafaelfranca** [comment]
Yes, this is the expected behavior. You are changing a global configuration so unless you set it back to the original value it will stick with that value for all the requests.
