### ISSUE TITLE
ConnectionPool leaking connections on database outage and recovery

### ISSUE THREAD

**Issue by jrochkind** [rails/rails#20114]
Rails 4.2.1, MRI 2.2.2, mysql2 0.3.18, passenger 4.0.59 

Normally, in a Rails app, if the MySQL database goes down (or is network inaccessible for some reason), then of course the Rails app will start raising lots of `Mysql::Error` and be unable to function, as expected. However, if the database again becomes acceptable, normally a Rails app can pick this up and begin functioning again, without an app restart. This is of course a good thing. 

However, there are some cases, under heavy concurrency, using multi-threading and explicit `ConnectionPool#with_connection` calls, where connections are somehow leaked from the pool, and the app is unable to recover. 

I'm afraid I haven't been able to isolate this to a simple reproduction yet, but I'm hoping someone will have some ideas anyway, and I'll continue to update as I discover more. 

* I have an app that creates it's own Threads with Thread.new, and uses AR, always within `ActiveRecord::Base.connection_pool.with_connection` blocks. 
* I simulate heavy traffic to it with apache siege
* I intentionally stop the MySQL server (to reproduce an unexpected outage) -- at this point, there are lost of `Mysql2::Error`s in the log as expected. 
* Still with the siege running, I restart the MySQL server. 
* At this point, the logs fill up with `ActiveRecord::ConnectionTimeoutError` errors. And the app can not function or recover, any attempt at database access results in one of these. 

Trying to diagnose what's going on, I notice that the ActiveRecord::ConnectionPool has three separate data structures in which it keeps track of connections:

* all existing connections are in ConnectionPool#@connections
* currently checked out and in use connections are in ConnectionPool#@reserved_connections
* Not in use available-for-checkout connections are in ConnectionPool#@available_connections

These three data structures need to be kept in sync, with the invariant that reserved_connections + available_connections == connections. 

I have put some diagnostic output in my app that gives the count of all of these:

    Rails.logger.info "available connections: #{Request.connection_pool.instance_variable_get("@available").instance_variable_get("@queue").size}"  +
    "reserved connections: #{Request.connection_pool.instance_variable_get("@reserved_connections").size};" + 
    " total connections: #{Request.connection_pool.instance_variable_get("@connections").size}"

Normally, available connections + reserved connections = total connections. 

However, when the error condition occurs, and I'm getting  `ActiveRecord::ConnectionTimeoutError` on most/all database attempts, the invariable is not met:

    available connections: 0; reserved connections: 1; total connections: 10

There are connections existing in `@connections`, but not listed in either `@reserved_connections` or `@available`. They have been leaked somehow.  It seems like there is a race condition bug somewhere where, due to an exception occuring at the wrong time/place, a connection can be removed from `@reserved_connections` without being added to `@available`. 

Also, `reap` does not seem to recover these connections and restore them to `@available`, even when run after the database has returned to availability. I have not yet explored to figure out why `@reap` isn't recovering.

**Comment by jrochkind** [comment]
`reap` doesn't catch them because they are *not* `in_use?` -- they have had `expire` called on them, so their `@owner` is not set, and they are not `in_use?`.  But they are still not back in `@available` as they should be, so `checkout` will not use them. 

I could write my own custom reap-like code that, in a synchronization block, finds these connections which are not `in_use?` but also not in `@available` and adds them back to `@available`. Or maybe this should be part of what `reap` does?

But it seems better to figure out why they are being leaked in the first place -- ideally it should not be possible. But the AR code here is pretty complicated, with different methods taking care of different things. `connection.expire` will make it no longer `in_use?`, but this method can be called by itself, something else has to ensure it becomes listed in `@available` again too. It's making my head hurt.

**Comment by jrochkind** [comment]
Okay, getting closer. After the database goes down and then comes back, subsequent attempts to ConnectionPool#checkout will raise an exception. 

Either from a `with_connection`, like so:

~~~
/Users/jrochkind/.gem/ruby/2.2.2/gems/mysql2-0.3.18/lib/mysql2/client.rb:70:in `initialize'
/Users/jrochkind/code/rails/activerecord/lib/active_record/connection_adapters/mysql2_adapter.rb:264:in `new'
/Users/jrochkind/code/rails/activerecord/lib/active_record/connection_adapters/mysql2_adapter.rb:264:in `connect'
/Users/jrochkind/code/rails/activerecord/lib/active_record/connection_adapters/mysql2_adapter.rb:97:in `reconnect!'
/Users/jrochkind/code/rails/activerecord/lib/active_record/connection_adapters/abstract_adapter.rb:328:in `verify!'
/Users/jrochkind/code/rails/activerecord/lib/active_record/connection_adapters/abstract/connection_pool.rb:466:in `block in checkout_and_verify'
/Users/jrochkind/.gem/ruby/2.2.2/gems/activesupport-4.2.1/lib/active_support/callbacks.rb:88:in `call'
/Users/jrochkind/.gem/ruby/2.2.2/gems/activesupport-4.2.1/lib/active_support/callbacks.rb:88:in `_run_callbacks'
/Users/jrochkind/.gem/ruby/2.2.2/gems/activesupport-4.2.1/lib/active_support/callbacks.rb:776:in `_run_checkout_callbacks'
/Users/jrochkind/code/rails/activerecord/lib/active_record/connection_adapters/abstract/connection_pool.rb:465:in `checkout_and_verify'
/Users/jrochkind/code/rails/activerecord/lib/active_record/connection_adapters/abstract/connection_pool.rb:352:in `block in checkout'
/opt/rubies/ruby-2.2.2/lib/ruby/2.2.0/monitor.rb:211:in `mon_synchronize'
/Users/jrochkind/code/rails/activerecord/lib/active_record/connection_adapters/abstract/connection_pool.rb:349:in `checkout'
/Users/jrochkind/code/rails/activerecord/lib/active_record/connection_adapters/abstract/connection_pool.rb:263:in `block in connection'
/opt/rubies/ruby-2.2.2/lib/ruby/2.2.0/monitor.rb:211:in `mon_synchronize'
/Users/jrochkind/code/rails/activerecord/lib/active_record/connection_adapters/abstract/connection_pool.rb:262:in `connection'
/Users/jrochkind/code/rails/activerecord/lib/active_record/connection_adapters/abstract/connection_pool.rb:292:in `with_connection'
~~~

Or from a straight `SomeModel#connection` like so:

~~~
[2015-05-11 14:29:58.399] 59888 ERROR  EXCEPTION ON CHECKOUT: Can't connect to MySQL server on '10.161.51.103' (61); /Users/jrochkind/.gem/ruby/2.2.2/gems/mysql2-0.3.18/lib/mysql2/client.rb:70:in `connect'
/Users/jrochkind/.gem/ruby/2.2.2/gems/mysql2-0.3.18/lib/mysql2/client.rb:70:in `initialize'
/Users/jrochkind/code/rails/activerecord/lib/active_record/connection_adapters/mysql2_adapter.rb:264:in `new'
/Users/jrochkind/code/rails/activerecord/lib/active_record/connection_adapters/mysql2_adapter.rb:264:in `connect'
/Users/jrochkind/code/rails/activerecord/lib/active_record/connection_adapters/mysql2_adapter.rb:97:in `reconnect!'
/Users/jrochkind/code/rails/activerecord/lib/active_record/connection_adapters/abstract_adapter.rb:328:in `verify!'
/Users/jrochkind/code/rails/activerecord/lib/active_record/connection_adapters/abstract/connection_pool.rb:466:in `block in checkout_and_verify'
/Users/jrochkind/.gem/ruby/2.2.2/gems/activesupport-4.2.1/lib/active_support/callbacks.rb:88:in `call'
/Users/jrochkind/.gem/ruby/2.2.2/gems/activesupport-4.2.1/lib/active_support/callbacks.rb:88:in `_run_callbacks'
/Users/jrochkind/.gem/ruby/2.2.2/gems/activesupport-4.2.1/lib/active_support/callbacks.rb:776:in `_run_checkout_callbacks'
/Users/jrochkind/code/rails/activerecord/lib/active_record/connection_adapters/abstract/connection_pool.rb:465:in `checkout_and_verify'
/Users/jrochkind/code/rails/activerecord/lib/active_record/connection_adapters/abstract/connection_pool.rb:352:in `block in checkout'
/opt/rubies/ruby-2.2.2/lib/ruby/2.2.0/monitor.rb:211:in `mon_synchronize'
/Users/jrochkind/code/rails/activerecord/lib/active_record/connection_adapters/abstract/connection_pool.rb:349:in `checkout'
/Users/jrochkind/code/rails/activerecord/lib/active_record/connection_adapters/abstract/connection_pool.rb:263:in `block in connection'
/opt/rubies/ruby-2.2.2/lib/ruby/2.2.0/monitor.rb:211:in `mon_synchronize'
/Users/jrochkind/code/rails/activerecord/lib/active_record/connection_adapters/abstract/connection_pool.rb:262:in `connection'
/Users/jrochkind/code/rails/activerecord/lib/active_record/connection_adapters/abstract/connection_pool.rb:577:in `retrieve_connection'
/Users/jrochkind/code/rails/activerecord/lib/active_record/connection_handling.rb:113:in `retrieve_connection'
/Users/jrochkind/code/rails/activerecord/lib/active_record/connection_handling.rb:87:in `connection'
~~~

I am guessing that unrescued exception at that point somehow results in a connection that is still in `@connections` but neither in `@available` nor `@reserved_connections`.  But I'm having trouble pinning down exactly how/where that would occur -- still trying to figure out how to follow the logic of the callbacks involved in `_run_checkout_callbacks`

I could make a mega-reap that manages to reap these lost-between-the-cracks exceptions, but that would just be a workaround, better to keep them from getting lost in the first place, but not sure how to do that. 

(Also no idea at all how to write a failing test for this stuff, which requires massive request volume to trigger the race condition, as well as a database which disappears and comes back).

**Comment by jrochkind** [comment]
Okay, and indeed monkey-patching ConnectionPool#checkout to be like so seems to make the problem no longer reproduce for me:

~~~ruby
      def checkout
        synchronize do
          begin
            conn = acquire_connection
            conn.lease
            checkout_and_verify(conn)
          rescue Exception => e
            checkin conn if conn
            raise e
          end
        end
      end
~~~

I have no idea if this is a good idea though, as a monkey patch or PR. And still no idea how to make a failing test. 

Advice from someone who works on ActiveRecord::ConnectionPool is very welcome at this point!

**Comment by matthewd** [comment]
Maybe relevant: #14938

**Comment by thedarkone** [comment]
@matthewd I'm afraid #14938 will be of no help here. IMHO this is a clear case of a "naked rescue" (#11780 or #11497).

@jrochkind can you check that this also fixes your problem:

```diff
 def checkout_and_verify(c)
   c._run_checkout_callbacks do
     c.verify!
   end
   c
-rescue
+rescue Exception
   remove c
   c.disconnect!
   raise
 end
```

**Comment by jrochkind** [comment]
Thanks @matthewd and @thedarkone. 

@thedarkone, the existing version of ConnectionPool#checkout_and_verify that I have in Rails 4.2.1 has no rescue in it at all, not even a naked rescue -- the naked rescue was added sometime between 4.2.1 and master.   

I will try adding a rescue per your specs...

It **does** seem to fix my problem.  This does seem to be the simplest and appropriate solution. 

I'm going to try the 'naked rescue' too just to see...   the naked rescue **also** fixes things for me. The problem was that in 4.2.1 there was no rescue at all.  It may be that rescuing Exception instead of StandardError is still a good idea, I'm not sure?  But my particular problem is fine with the naked/StandardError rescue. 

So... I guess it's already fixed in master?  Any chance of getting it backported to 4.2? Any advice @thedarkone ?

Otherwise and in the meantime, I think this suggests a fairly reasonable and forwards-compatible monkey patch I can do to workaround:

~~~ruby
# Workaround to leaked connections database outage/recovery, 
  # https://github.com/rails/rails/issues/20114
  if Rails.version.split(".").first.to_i < 5
    class ActiveRecord::ConnectionAdapters::ConnectionPool

      def checkout_and_verify_with_rescue(c)
        checkout_and_verify_without_rescue(c)
      rescue Exception
        remove c
        c.disconnect!
        raise
      end
      alias_method_chain :checkout_and_verify, :rescue

    end  
  end
~~~

Seems to work to solve my problem too as a monkey patch in current Rails version. What do you think? Thanks so much for the tips @thedarkone.

**Comment by jrochkind** [comment]
Looks like the `rescue` in `checkout_and_verify` was added here 205a561e5 by @yoshiokatsuneo , and the comment suggests it was added to fix the very problem I am having, exactly, indeed. 

The commit did not come along with any tests, so I feel better about being completely lost trying to figure out how to write a failing test myself. :)

I do think this should be backported to a 4.2 patch release, it is a bug, which can be easily fixed.

**Comment by matthewd** [comment]
Looks like it was already backported in 1997f7bf0e5c0bfbf2245c6d795271fc502e2b33, so I'll close this. (Though we should probably separately address the bare rescue, for completeness.)

**Comment by jrochkind** [comment]
Thanks @matthewd. Does that backport in 1997f7b mean it will likely be showing up in an upcoming 4.2.2?

**Comment by matthewd** [comment]
@jrochkind yup

**Comment by jrochkind** [comment]
Excellent. For anyone else reading along, I've guarded my monkeypatch like so, to automatically disable it when 4.2.2 is released:

~~~ruby
  rails_version = Gem::Version.new(Rails.version)
  if (rails_version >= Gem::Version.new("4.0")) && (rails_version < Gem::Version.new("4.2.2"))
~~~
