### ISSUE TITLE
Trouble with updating nested models, that has an overriden association

### ISSUE THREAD

**Issue by bartalameo** [rails/rails#20120]
Hi!

There are some troubles with updating nested model (defined through `:has_one`), that has an overriden association.

I use:
- Ruby 2.1.5
- Rails 4.2.1

Take a look at next models:

``` ruby
class Report < ActiveRecord::Base
  has_one :problem
end

# Child from Report
class Report::UnitInformation < Report 
  # :problem is overriden to use another class - 'Problem::DetectionDate'
  has_one :problem, class_name: 'Problem::DetectionDate', foreign_key: 'report_id'
  accepts_nested_attributes_for :problem, update_only: true

  validates_associated :problem
end

class Problem < ActiveRecord::Base
  belongs_to :report
end

# Child from Problem
class Problem::DetectionDate < Problem
  validates :detected_at, presence: true
end
```

When I try to update instance of `Report::UnitInformation` with a `Problem` attrs like this:

``` ruby
report = Report::UnitInformation.last # or .new/create
  => #Report::UnitInformation Load (0.7ms)  SELECT  "reports".* FROM "reports"  ORDER BY "reports"."id" DESC LIMIT 1
  => #<Report::UnitInformation id: 2, ...> 

params = { problem_attributes: { detected_at: '2015-01-01'}}
report.update(params)
```

It generantes next SQL and result:

``` sql
2.1.5 :008 > report.update(params)
   (0.3ms)  BEGIN
  Problem::DetectionDate Load (0.8ms)  SELECT  "problems".* FROM "problems" WHERE "problems"."report_id" = $1 LIMIT 1  [["report_id", 2]]
   (0.4ms)  COMMIT
 => true 
```

As you can see - **nothing** is updated (but the `:problem` record had to update). 

My research shows, that if I will use a new name for the `:problem` association (`:trouble` for example), then all is fine and nested model successfully updating! But if the name of the association is same (take a look to the `Report::UnitInformation` model `has_one`), as in parent model (w. `Report` model) - then nothing happened!

I am interested - why? Can anybody explain the situation?
Thanks.

**Comment by senny** [comment]
@bartalameo tried to reproduce the scenario in a test-case but had no luck. Could you please provide an executable reproduction? You can take [this script](https://github.com/rails/rails/blob/master/guides/bug_report_templates/active_record_gem.rb) as a starting point.

**Comment by nbulaj** [comment]
Problem still exists for the Rails 4-2-stable.

**Comment by senny** [comment]
@nbulaj could you write an executable test-case using the script I linked above? That goes a long way to help debug and fix the issue.
