### ISSUE TITLE
Model.method_defined? does not always return true, if a method is defined

### ISSUE THREAD

**Issue by dennisvandehoef** [rails/rails#20122]
`Model.method_defined?` only works after a record has been touched.
Witch gives back crazy results.

See my example:
![production](https://cloud.githubusercontent.com/assets/7486464/7586931/43759390-f8b2-11e4-93a5-a78a17a9c9ec.png)

and `Rails.application.config.cache_classes` is on

**Comment by matthewd** [comment]
Yeah, this is expected behaviour.

We can't return `true` there until we've looked at the database schema, and we don't do that until the first instance is created.

**Comment by dennisvandehoef** [comment]
For all of those wo need this, in the end I used: `Page.column_names.include? :created_by_id`
