### ISSUE TITLE
TypeError when using json column with ActiveRecord serialize and Postgres

### ISSUE THREAD

**Issue by lleger** [rails/rails#20132]
I'm having issues with ActiveRecord's `serialize` when using the `json` column type in PostgreSQL. When assigning a value, a `TypeError` is thrown. I dumped the full stack trace [in a gist](https://gist.github.com/lleger/4390d9f42a57984dc6d5).

Here's a sample model:
```ruby
class CreateBrokenPosts < ActiveRecord::Migration
  def change
    create_table :broken_posts do |t|
      t.string :title
      t.json :comments

      t.timestamps null: false
    end
  end
end
```

```ruby
class BrokenPost < ActiveRecord::Base
  serialize :comments, JSON
end
```

If you do something like this:
```ruby
post = BrokenPost.new(title: "Test title", comments: Comment.first)
```
it throws an error.

However, if you simply use a regular `string` column, it works perfectly.

```ruby
class CreateWorkingPosts < ActiveRecord::Migration
  def change
    create_table :working_posts do |t|
      t.string :title
      t.string :comments

      t.timestamps null: false
    end
  end
end
```

```ruby
class WorkingPost < ActiveRecord::Base
  serialize :comments, JSON
end
```

```ruby
post = WorkingPost.new(title: "Test title", comments: Comment.first)
=> #<WorkingPost id: nil, title: "Test title", comments: {"id"=>1, "name"=>"Logan Leger", "body"=>"This was a great post!", "created_at"=>"2015-05-12T22:38:52.270Z", "updated_at"=>"2015-05-12T22:38:52.270Z"}, created_at: nil, updated_at: nil>
```

I tried to dig into the source, following the stack trace. Unfortunately I got a bit lost in the type casting, which is where the problem seems to be occurring. I *think* the JSON may be getting pulled through the encoder multiple times, causing it to short circuit, but this part of the Rails codebase is a bit new to me.

Is this a bug? Or is `serialize` just not designed to be used with the `json` type? Am I doing something else wrong? Any help or guidance to isolate the error is much appreciated.

I uploaded a [sample app](https://github.com/lleger/rails_421_serialize_json_postgresql_bug). This is a clean app with a working model and a broken model. I added some simple seeds to show the difference.

**Comment by senny** [comment]
`serialized` is designed to serialize complex data into a `text` field. When you have a `json` column, there is no need for that. The type will already parse the data into the right structure.

There is an [example](http://edgeguides.rubyonrails.org/active_record_postgresql.html#json) in the PostgreSQL for Rails guide.

**Comment by lleger** [comment]
I almost didn't ask the question because I assumed I was just doing something wrong. That makes sense. Thanks for the help, @senny. I'll do a better job of reading the manual next time!

**Comment by fourcolors** [comment]
I have a `t.json` type but when I try to retrieve it ie: `Map.objects` it's returning a String instead of a Hash of objects. 

This only started happening in Rails 5.2.1 for me. Any chance this is related? I haven't found anyone talking about this.

**Comment by loybert** [comment]
@fourcolors faced this issue by myself, but this comment helped me to fix it:

https://github.com/rails/rails/issues/27788#issuecomment-323000251
> Fix for me was to pass hash/array instead of JSON string.

I just had to parse it once, reassign it to the model's field and store it. After reloading this model-instance all worked again as expected.
```
MyModel.foreach do |m|
  j = JSON.parse(m.my_jsonb_field)
 m.my_jsonb_field = j
 m.save
end
```

**Comment by mnifakram** [comment]
If you're upgrading you Rails from 5.1 and lower then you should reassign your existing records as @loybert suggested.
