### ISSUE TITLE
Out of range association ids throw exception before validation.

### ISSUE THREAD

**Issue by thomasfedb** [rails/rails#20140]
Often applications allow a client to supply an associated id and then validate that the referenced record does in fact exist. For example:

``` ruby
class Bone < ActiveRecord::Base
  belongs_to :dog
  validates :dog, presence: true
end
```

Thus when a non-existant but legal `dog_id` is supplied the result is a validation error and `bone.dog` produces `nil`.

However, if lookup of an illegal `dog_id` supplied results in a `RangeError` then the validations cannot be run, validation errors are not generated, and this makes it difficult to support a good user experience in this case.

I propose that a `RangeError` produced when looking up an association should result in that association being assigned as `nil` and then validations proceeding as per usual.

**Comment by ptashman** [comment]
How would it help to assign the nonexistent associated object as nil?

**Comment by ptashman** [comment]
Can you come up with a use case in which you would want to look up this nonexistent associated object?

**Comment by thomasfedb** [comment]
@ptashman It's less that I want to look up a non-existent object, and more that I'd rather the issue was handled by my validation rather than erroring out immediately.

Often we assign association id values from a user (form or api) to a model. For example `@person.update_attributes(params.require(:person).allow(:name, :role_id))`.

If the `role_id` is out of range, that should be able to be returned to the user via a validation error (eg: "role does not exist", no need to reveal too much about our database), rather than resulting in a 500.

**Comment by rwadstein** [comment]
This stems from the change where an error is now raised, but `#valid?` happens to not be one that does *not* handle that error, but a lot of find methods rescue this error.
https://github.com/rails/rails/commit/e62fff40edde10bd04bbb91ce242f4a7f7ea64a8

This is actually a bigger problem in general with any integer backed column and validation.  
Any value larger than the db column can handle that is assigned to an attribute will raise an `RangeError` if `#valid?` is called from the model.  The whole point of `valid?` is to return true/false so this breaks the intended behavior of the method.

Unfortunately, we have had to write custom validations that `rescue` those errors, which should have been unnecessary.  I hope this gets fixed.

**Comment by rwadstein** [comment]
The specifics of our uses cases have been around custom validations of the existence of such values in another model and also have a validation using `less_than_or_equal_to`.  But the custom validation results with a DB query which then gets a `RangeError` because of the invalid cast value for the DB.

It would seem that validations in general might need to rescue that error or at least maybe only from `#valid?` ?.

**Comment by thomasfedb** [comment]
Any further thoughts on this @ptashman?
