### ISSUE TITLE
`rails server` fails with sqlite3_native load error

### ISSUE THREAD

**Issue by Brrrknee** [rails/rails#20152]
just created a new "myApp" CD'd to that new directory, and got this load error on sqlite3 for `rails server`.  
I pulled that package again, successfully via `gem install sqlite3` and tried again, same error.  
Also happens with `rails console`

`C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/sqlite3-1.3.10-x64-mingw32/lib/sqlite3.rb:6:in "require": cannot load such file -- sqlite3/sqlite3_native (LoadError)  `

**Comment by arunagw** [comment]
Seems like a problem with `sqlite3` or local setup? Can you please try looking on stackoverflow and other places.

This issue tracker is for rails-core bugs.

thanks

**Comment by Brrrknee** [comment]
Sure.  you bet.  the simple "install Ruby, start server" fails and it is "not a core" problem.
the "solution" listed on this site  http://rubyonwindowsguides.github.io/book/ch02-05.html is so low-level and beyond the mantra of ruby making things easier for developing ruby code, it is counter-productive, introducing several other complexities to have fail and added dependencies to search out. The dozen or so steps to resolve just the one 'native gem' issue shows a gap to be addressed.

**Comment by arunagw** [comment]
@Brrrknee It seems like that on your machine `sqlite3` is broken. 

Found this which might help http://stackoverflow.com/questions/5800920/error-no-such-file-to-load-sqlite3-sqlite3-native-loaderror

Seems like the link you give has a solution as well. Also as suggested here https://groups.google.com/forum/#!msg/sqlite3-ruby/cNqvONJmocU/C0Rdg6ZxhV4J lowering down ruby version might help?
