### ISSUE TITLE
Rows always affected

### ISSUE THREAD

**Issue by wirasto** [rails/rails#20158]
Update my row data with same data.

```ruby
affected_rows = Pegawai.where(:id => params[:id]).update_all(nama_depan: 'test', nama: 'test 2')
puts "COUNT : #{affected_rows}"
```

This said affected row is 1. 
Why result 1? I don't change anything.

**Comment by rafaelfranca** [comment]
Please use the mailing list or StackOverflow for questions/help, where a wider community will be able to help you. We reserve the issues tracker for issues only.

**Comment by rafaelfranca** [comment]
To answer the question the return is the number of affected rows, even if the data didn't changed on the rows, they are still affected.

**Comment by wirasto** [comment]
Owh, this is normal for rails. Okay,,,, 
and sorry for wrong post,,,, ;)
