### ISSUE TITLE
rails g mailer layout has a mispelling (hmtl)

### ISSUE THREAD

**Issue by collimarco** [rails/rails#20185]
I use haml 4.0.6 and rails 4.2.0. Here's the template generated by `rails g mailer ...`:

```
%hmtl
  %body
    = yield
```

As you can see there's a mispelling of `html`.

**Comment by senny** [comment]
@collimarco this [template](https://github.com/indirect/haml-rails/blob/master/lib/generators/haml/mailer/templates/layout.html.haml) is generated by [`haml-rails`](https://github.com/indirect/haml-rails).

**Comment by simi** [comment]
And this was fixed in https://github.com/indirect/haml-rails/commit/248c3bb098b45cf465bf333c9912788fe19a725e.

**Comment by collimarco** [comment]
Oops... I thought that HAML was using erb2haml feature to convert the template (and not an its own template).
