### ISSUE TITLE
response.content_type should not remove charset

### ISSUE THREAD

**Issue by joelpresence** [rails/rails#20194]
Hi,

When I run rails and perform a certain request, I get a response with:

```
Content-Type: application/json; charset=utf-8
```

However, when performing a controller test against that same controller, the `response.content_type` is just `application/json` which is not correct.  Somehow, rails tests are splitting off charset into `response.charset` which comes back as `utf-8`.  This feels odd to do this since the actual header name where the charset is returned is `Content-Type`.

I'm not sure which code is doing this and obviously not breaking a bunch of existing tests is a concern, but this seems like a mismatch to me ...

This is on rails 4.2.1 and ruby 2.2.2p95 (2015-04-13 revision 50295) [x86_64-darwin14].

Thoughts?

Thanks!

**Comment by rafaelfranca** [comment]
Yes, we are aware of this. Rails override `content_type` to return `Mime::Type#to_s` loosing some information, but this is not something we can change easily.

See https://github.com/rails/rails/pull/16018
