### ISSUE TITLE
before_update provides no errors on rollback

### ISSUE THREAD

**Issue by danielpclark** [rails/rails#20199]
I've used the bug report example to replicate this issue.  Here's the code tested against ActiveRecord 4.1.10 and 4.2.1

```ruby
# Activate the gem you are reporting the issue against.
gem 'activerecord', '4.1.10'
require 'active_record'
require 'minitest/autorun'
require 'logger'

# Ensure backward compatibility with Minitest 4
Minitest::Test = MiniTest::Unit::TestCase unless defined?(Minitest::Test)

# This connection will do for database-independent bug reports.
ActiveRecord::Base.establish_connection(adapter: 'sqlite3', database: ':memory:')
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :togs, force: true  do |t|
    t.string :togname, null: false
    t.boolean :changable, default: true
  end

end

class Tog < ActiveRecord::Base

  before_update proc {
    if togname_changed?
      write_attribute(:changable, false)
    end
  }

end

class BugTest < Minitest::Test

  def setup
    Tog.all.destroy_all
    Tog.create!(togname: "foo")

    @tog = Tog.where(togname: "foo").first
    @tog.update(togname: "bar") if @tog.changable
  end

  def test_this_passes
    assert_equal @tog.togname, "bar"
  end

  def test_this_does_not_pass
    @tog.reload
    assert_equal @tog.togname, "bar"
  end

  def test_no_error_messages_even_with_rollback
    @tog.reload
    refute_empty @tog.errors
  end
end

```

And here's its output:

    -- create_table(:togs, {:force=>true})
    D, [2015-05-19T01:12:19.318388 #16198] DEBUG -- :    (0.3ms)  CREATE TABLE "togs" ("id" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, "togname" varchar(255) NOT NULL, "changable" boolean DEFAULT 't') 
       -> 0.0080s
    Run options: --seed 56262

    # Running:

    D, [2015-05-19T01:12:19.485923 #16198] DEBUG -- :   Tog Load (0.2ms)  SELECT "togs".* FROM "togs"
    D, [2015-05-19T01:12:19.494139 #16198] DEBUG -- :    (0.1ms)  begin transaction
    D, [2015-05-19T01:12:19.496555 #16198] DEBUG -- :   SQL (0.1ms)  INSERT INTO "togs" ("togname") VALUES (?)  [["togname", "foo"]]
    D, [2015-05-19T01:12:19.496852 #16198] DEBUG -- :    (0.1ms)  commit transaction
    D, [2015-05-19T01:12:19.499976 #16198] DEBUG -- :   Tog Load (0.1ms)  SELECT  "togs".* FROM "togs"  WHERE "togs"."togname" = 'foo'  ORDER BY "togs"."id" ASC LIMIT 1
    D, [2015-05-19T01:12:19.500232 #16198] DEBUG -- :    (0.0ms)  begin transaction
    D, [2015-05-19T01:12:19.500707 #16198] DEBUG -- :    (0.1ms)  rollback transaction
    .D, [2015-05-19T01:12:19.501262 #16198] DEBUG -- :   Tog Load (0.1ms)  SELECT "togs".* FROM "togs"
    D, [2015-05-19T01:12:19.501507 #16198] DEBUG -- :    (0.1ms)  begin transaction
    D, [2015-05-19T01:12:19.502056 #16198] DEBUG -- :   SQL (0.1ms)  DELETE FROM "togs" WHERE "togs"."id" = ?  [["id", 1]]
    D, [2015-05-19T01:12:19.502196 #16198] DEBUG -- :    (0.0ms)  commit transaction
    D, [2015-05-19T01:12:19.502478 #16198] DEBUG -- :    (0.0ms)  begin transaction
    D, [2015-05-19T01:12:19.502938 #16198] DEBUG -- :   SQL (0.0ms)  INSERT INTO "togs" ("togname") VALUES (?)  [["togname", "foo"]]
    D, [2015-05-19T01:12:19.503118 #16198] DEBUG -- :    (0.0ms)  commit transaction
    D, [2015-05-19T01:12:19.503698 #16198] DEBUG -- :   Tog Load (0.1ms)  SELECT  "togs".* FROM "togs"  WHERE "togs"."togname" = 'foo'  ORDER BY "togs"."id" ASC LIMIT 1
    D, [2015-05-19T01:12:19.503888 #16198] DEBUG -- :    (0.0ms)  begin transaction
    D, [2015-05-19T01:12:19.504236 #16198] DEBUG -- :    (0.0ms)  rollback transaction
    D, [2015-05-19T01:12:19.504821 #16198] DEBUG -- :   Tog Load (0.1ms)  SELECT  "togs".* FROM "togs"  WHERE "togs"."id" = ? LIMIT 1  [["id", 2]]
    FD, [2015-05-19T01:12:19.505421 #16198] DEBUG -- :   Tog Load (0.1ms)  SELECT "togs".* FROM "togs"
    D, [2015-05-19T01:12:19.505648 #16198] DEBUG -- :    (0.1ms)  begin transaction
    D, [2015-05-19T01:12:19.506086 #16198] DEBUG -- :   SQL (0.1ms)  DELETE FROM "togs" WHERE "togs"."id" = ?  [["id", 2]]
    D, [2015-05-19T01:12:19.506256 #16198] DEBUG -- :    (0.1ms)  commit transaction
    D, [2015-05-19T01:12:19.506472 #16198] DEBUG -- :    (0.0ms)  begin transaction
    D, [2015-05-19T01:12:19.506866 #16198] DEBUG -- :   SQL (0.0ms)  INSERT INTO "togs" ("togname") VALUES (?)  [["togname", "foo"]]
    D, [2015-05-19T01:12:19.507022 #16198] DEBUG -- :    (0.0ms)  commit transaction
    D, [2015-05-19T01:12:19.507476 #16198] DEBUG -- :   Tog Load (0.1ms)  SELECT  "togs".* FROM "togs"  WHERE "togs"."togname" = 'foo'  ORDER BY "togs"."id" ASC LIMIT 1
    D, [2015-05-19T01:12:19.507637 #16198] DEBUG -- :    (0.0ms)  begin transaction
    D, [2015-05-19T01:12:19.507942 #16198] DEBUG -- :    (0.0ms)  rollback transaction
    D, [2015-05-19T01:12:19.508377 #16198] DEBUG -- :   Tog Load (0.0ms)  SELECT  "togs".* FROM "togs"  WHERE "togs"."id" = ? LIMIT 1  [["id", 3]]
    F

    Finished in 0.026384s, 113.7062 runs/s, 151.6083 assertions/s.

      1) Failure:
    BugTest#test_no_error_messages_even_with_rollback [validate-unique-update-issue.rb:53]:
    Expected #<ActiveModel::Errors:0x00000003644328 @base=#<Tog id: 2, togname: "foo", changable: true>, @messages={}> to not be empty.

      2) Failure:
    BugTest#test_this_does_not_pass [validate-unique-update-issue.rb:48]:
    Expected: "foo"
      Actual: "bar"

    3 runs, 4 assertions, 2 failures, 0 errors, 0 skips

I didn't figure out what was going on in my own project as there were no error messages telling me why the record didn't commit.  My first discovery was when I used **reload** to show that the record didn't update.  I didn't find out it was related to **before_update** until I experimented with the sample bug report.  As far as I can tell this should work.  I've tried alternative ways of updating attributes in **before_update** with the same results.  There should be at least some error reporting for when this behavior occurs IMHO.

**Comment by danielpclark** [comment]
I'm not quite sure why this code doesn't work.  But for anyone else who runs into this problem I've found a work around.

```ruby
# Activate the gem you are reporting the issue against.
gem 'activerecord', '4.2.1'
require 'active_record'
require 'minitest/autorun'
require 'logger'

# Ensure backward compatibility with Minitest 4
Minitest::Test = MiniTest::Unit::TestCase unless defined?(Minitest::Test)

# This connection will do for database-independent bug reports.
ActiveRecord::Base.establish_connection(adapter: 'sqlite3', database: ':memory:')
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :togs, force: true  do |t|
    t.string :togname, null: false
    t.boolean :changable, default: true
  end

end

class Tog < ActiveRecord::Base

  def update(attributes)
    attributes.update( changable: false )
    super
  end

end

class BugTest < Minitest::Test

  def setup
    Tog.all.destroy_all
    Tog.create!(togname: "foo")

    @tog = Tog.where(togname: "foo").first
    @tog.update(togname: "bar") 
  end

  def test_this_passes
    assert_equal @tog.togname, "bar"
  end

  def test_this_does_not_pass
    @tog.reload
    assert_equal @tog.togname, "bar"
  end

  def test_no_error_messages_even_with_rollback
    @tog.reload
    assert_empty @tog.errors
  end
end
```

**Comment by al2o3cr** [comment]
`write_attribute` returns the value it was passed (`false` in this case) which means the `before_update` returns false, aborting the save.

**Comment by danielpclark** [comment]
Thanks for the insight!  Same thing happens with `self.changable=false`.  So I perceive it's the same issue for that as well.

**Comment by rafaelfranca** [comment]
This is fixed in master. Returning `false` in a callbacks doesn't abort the execution anymore.
