### ISSUE TITLE
Invalid sample test generated for engine controller tests

### ISSUE THREAD

**Issue by repinel** [rails/rails#20197]
Please follow the steps to reproduce with `4.2.1`:
1. `rails plugin new blorgh --mountable`
2. `rails g controller articles index`

It will generate the test:
```
test "should get index" do
  get :index
  assert_response :success
end
```
The correct one for this engine would be:
```
test "should get index" do
  get :index, use_route: 'blorgh'
  assert_response :success
end
```

**Comment by rafaelfranca** [comment]
This option was deprecated in Rails 4.2 and removed, so it can't be correct. In fact the guide was incorrect. See the deprecation message at https://github.com/rails/rails/commit/e4cfd353a47369dd32198b0e67b8cbb2f9a1c548#diff-600d5368b55e46ed961abb4295977ac3L719

**Comment by repinel** [comment]
I was wondering that. Thanks for the feedback!
