### ISSUE TITLE
NullStore local caching makes tests fail

### ISSUE THREAD

**Issue by jfornoff** [rails/rails#20202]
Hi everyone!

I've been having some issues lately with NullStore in testing contexts.

NullStore seems to actually cache within blocks (because of Strategy::LocalCache).
Because the tests go really fast, the default cache keys do not change at times (updated_at timestamps are second-precision) and old cache entries get pulled, which causes tests to fail.

A workaround is littering your tests with "sleep 1", but I don't feel that is the correct way to do it.

Can anyone give me a hand with that one?

**Comment by jfornoff** [comment]
Monkeypatching ActiveSupport::Cache::Strategy::LocalCache#local_cache to return false in test environment does fix the problem, but that's probably not the correct way to do it.

Maybe it would make sense to introduce a configuration key that disables local caching within blocks?

Hope that makes any sense at all, it's my first time posting here.

**Comment by arunagw** [comment]
Hey @jfornoff do you still have this issue? Can this be closed?

**Comment by jfornoff** [comment]
Still got the above monkeypatch running in my project, I'll try disabling it on 4.2 stable release and check if the issue is still present. Will be at work around thursday, I'll get back to you!

**Comment by jfornoff** [comment]
Sorry for taking so long, I forgot.

Problem unfortunately still persisting on 4.2.5

**Comment by rafaelfranca** [comment]
Can you please provide a sample application that reproduces the error?

**Comment by jfornoff** [comment]
Thanks for the quick reply, I'll try to figure out how to reproduce it reliably.
