### ISSUE TITLE
Rails 4.2 under Jruby can't find PGconn class

### ISSUE THREAD

**Issue by ninkibah** [rails/rails#20229]
I am trying to upgrade our Rails 3.2 app to 4.2.1. So far, I've managed to get to 4.1.6 and I'm almost there. However, I am getting an 
`
unknown constant  ActiveRecord::ConnectionAdapters::PostgreSQL::OID:Bytea::PGconn
`

I suspect it has something to do with the ARJDBC adapter.

As a workaround, I added the following code to a config/initializer:

```ruby
  module ConnectionAdapters
    module PostgreSQL
      module OID # :nodoc:
        class Bytea < Type::Binary # :nodoc:
          def type_cast_from_database(value)
            return if value.nil?
            return value.to_s if value.is_a?(Type::Binary::Data)
            val = super
            return val unless val.starts_with?('\x')
            [val[2..-1]].pack('H*')
          end
        end
      end
    end
```

The last two lines seem to be functionally equivalent to PGconn.unescape_bytea(super).

Question 1: Is this code as good as using the C/Java function which would normally be called? I presume pack is efficiently implemented in both Ruby and JRuby.

Question 2: Is this code worth doing a pull request for, or is it better to have the dependency on PGconn?

**Comment by rafaelfranca** [comment]
> or is it better to have the dependency on PGconn

We already depend o PGconn, so we should just use it normally here. Maybe we should change `PGconn.unescape_bytea(super)` to `::PGconn.unescape_bytea(super)`?

**Comment by prathamesh-sonpatki** [comment]
PG gem is not used with JRuby, This code needs to be overridden in ActiveRecord JDBC side.

**Comment by rafaelfranca** [comment]
I see. I think we see where we use `PGconn` inside Rails adapter directly and isolate that in internal adapter calls so the JRuby adapter only override these isolated methods. @ninkibah do you want to work on this?

**Comment by rafaelfranca** [comment]
hmm, but I think the type objects should not know about the connection. So maybe your patch is fine. @sgrif WDYT?

**Comment by sgrif** [comment]
This shouldn't be new in 4.2, `PGConn` was used in 4.1 as well. I think this is a bug for the JRuby adapter. The type object in question is PG specific, so it should be allowed to make those sorts of assumptions. JDBC can provide its own type.

**Comment by rafaelfranca** [comment]
:+1: I'll try to move the issue to their adapter

**Comment by rafaelfranca** [comment]
This issue was moved to jruby/activerecord-jdbc-adapter#652
