### ISSUE TITLE
AR and equivalent SQL query return different outputs

### ISSUE THREAD

**Issue by jdanielnd** [rails/rails#20249]
Rails 4.2.1

This AR query

    TotalSales.joins(:customer).includes(:product_category).
      where("customers.organization_id = ?", 1).
      group("customers.external_id, product_categories.external_id").
      maximum(:start_date)

generates this SQL query

    SELECT
      MAX("total_sales"."start_date") AS maximum_start_date, 
      customers.external_id, product_categories.external_id AS customers_external_id_product_categories_external_id
    FROM
      "total_sales"
    INNER JOIN "customers" ON
      "customers"."id" = "total_sales"."customer_id"
    LEFT OUTER JOIN "product_categories" ON
      "product_categories"."id" = "total_sales"."product_category_id" 
    WHERE
      (customers.organization_id = 1)
    GROUP BY
      customers.external_id, product_categories.external_id

However, they output different things! Look at the outputs:

AR:

    => {"DIA"=>Wed, 01 Jan 2014, "MES"=>Wed, 01 Jan 2014, nil=>Wed, 01 Jan 2014}

SQL:

    "2014-01-01";"CLIENTE.1";"DIA"
    "2014-01-01";"CLIENTE.1";"MES"
    "2014-01-01";"CLIENTE.1";""
    "2014-01-01";"CLIENTE.10";"DIA"
    "2014-01-01";"CLIENTE.10";"MES"
    "2014-01-01";"CLIENTE.10";""
    "2014-01-01";"CLIENTE.100";"DIA"
    "2014-01-01";"CLIENTE.100";"MES"
    ...

Looks like because both group columns are called `external_id`, but from different tables, AR record used just one to generate the output hash.

**Comment by al2o3cr** [comment]
@jdanielnd Do the results change if you split the SQL string passed to `group` into two strings? So `.group('customers.external_id', 'product_categories.external_id')` instead of what's currently there. A quick test on 4.2 shows that the split version gives results closer to what you're expecting.

**Comment by jdanielnd** [comment]
@al2o3cr they do change! Is it some documented behaviour? It seems `group` method gets the number of grouping keys from the number of strings on the parameters rather than the SQL response, right?

**Comment by al2o3cr** [comment]
@jdanielnd I believe so. Will try to track down a source reference for this behavior.

**Comment by joaofraga** [comment]
:+1:

**Comment by jdanielnd** [comment]
It seems the method treat it as an Array of string or Symbols, but don't assume a String may contain more than one group condition:

https://github.com/rails/arel/blob/6160bfbda1d1781c3b08a33ec4955f170e95be11/lib/arel/table.rb#L55
https://github.com/rails/arel/blob/6160bfbda1d1781c3b08a33ec4955f170e95be11/lib/arel/select_manager.rb#L76
