### ISSUE TITLE
Accessing a not selected belongs_to association behaves differently since AR 4.2

### ISSUE THREAD

**Issue by amatsuda** [rails/rails#20253]
For example, given two models `User` and `Post` in `Post.belongs_to :user` relationship,
then executing following code:
```ruby
Post.select(:id).first.user
```

4.1 raises `ActiveModel::MissingAttributeError: missing attribute: user_id`
but 4.2 returns `nil`.

This change was introduced in 8b9542001d5e3fefa67f15af0b303aaf1ea95875, where 
`owner['post_id']` raises but `owner._read_attribute('post_id')` does not.

IMO 4.2 behavior seems a little bit inconsistent, because even in 4.2,
`Post.select(:id).first.user_id`
raises `missing attribute: user_id (ActiveModel::MissingAttributeError)`.
So it's strange that `Post.select(:id).first.user` does not raise.

**Comment by sgrif** [comment]
This was fixed by https://github.com/rails/rails/issues/20578

**Comment by amatsuda** [comment]
@dcrec1 @sgrif Awesome! Thank you :heart:💜:heart:
