### ISSUE TITLE
Not recognizing _method during resource update

### ISSUE THREAD

**Issue by meltingice** [rails/rails#20266]
Currently running Rails 4.2.1.

I'm using the built-in form helper, and I'm getting the error `No route matches [POST] "/admin/foo/1/bar/3”` when attempting to update the resource.

Looking at the request data, `_method` is clearly set to `patch`, but Rails seems to be trying to process it as a POST anyways.

```
Parameters:

{"utf8"=>"✓",
 "_method"=>"patch”,
 "authenticity_token": "...",
 "bar": { }
}
```

And the route:

`PATCH    /admin/foo/:foo_id/bar/:id(.:format)    admin/bar#update`

The ERB looks like:

`<%= form_for [:admin, @foo, @bar] do |f| %>`

I've triple checked my code and I can't find anything that would be making Rails act this way.

**Comment by agis-** [comment]
Can you please upload a minimal rails app reproducing the issue? That would make things easier.

**Comment by venkatramanka** [comment]
I tried to reproduce this issue, and I found that Rails just works as expected. I created the exact namespaced structure as posted by @meltingice and the form triggered a PATCH request. I believe it must have been some other issue causing the problem there, and this can be closed.

**Comment by senny** [comment]
@meltingice it's been a month without feedback, any luck with that reproduction?

**Comment by hut8** [comment]
I have this issue also. I'm working on a reproduction

**Comment by hut8** [comment]
@meltingice is there any chance you're using the `rails-api` gem? This issue was resolved for me when I just removed that gem and inherited my API controller from `ActiveRecord::Base` instead.

**Comment by senny** [comment]
@hut8 thanks for reporting your solution. Since we haven't heard back from the issue author I'm going to close this for now.

If this is still an issue, please report back with further details and I'll happily reopen.

**Comment by meltingice** [comment]
Yeah, I believe it's caused by rails-api. Removing it solved it for me as well.

--
Ryan LeFevre (@meltingice)
HODINKEE, Inc.
Sr. Software Engineer




On Sun, Sep 13, 2015 at 10:28 AM -0700, "Yves Senn" <notifications@github.com> wrote:












Closed #20266.

**Comment by hut8** [comment]
The combination of these two lines breaks it:

[setting config.api_only = true](https://github.com/rails-api/rails-api/blob/master/lib/rails-api/application.rb#L37)
[don't include Rack::MethodOverride in the middleware stack for the application if config.api_only = true](https://github.com/rails-api/rails-api/blob/master/lib/rails-api/application/default_rails_four_middleware_stack.rb#L33)

**Comment by itay-grudev** [comment]
Hey Guys,
I have the same issue. Two identical requests (apart from the authenticity token), both are POST and both have the same headers (I compared the raw version dumped in Firefox) and both have the `_method` set to `patch`, but one of them is always recognized as `POST`. IDK how to debug the issue further. Would it help to use an HTTP proxy and dump raw HTTP requests for comparison?

**Comment by itay-grudev** [comment]
```ruby
// routes.rb
namespace :admin do
    resources :something, param: :slug
end
```

```javascript
// An example request that causes the issue
$.ajax({
  url: '/admin/something/test',
  method: 'POST',
  data: {
    '_method': 'patch',
    'something[something_else_attributes][1465480387891][alt]': '',
    'something[something_else_attributes][][id]': '51',
  }
});
```

**Comment by itay-grudev** [comment]
Here is a [Rails App](https://github.com/itay-grudev/rails_method_ignored/commits?author=itay-grudev) that reproduces the issue.

**Comment by itay-grudev** [comment]
Sorry. The link was to a private repo. It's set to public now.
