### ISSUE TITLE
Constraints on format of glob routes do not work

### ISSUE THREAD

**Issue by mrnugget** [rails/rails#20264]
While trying to fix requests for missing assets being handled by our catch-all route I noticed that specifying the format in the `constraints` hash of the route does not work. The requests still get routed to the specified controller, even though the format doesn't match. Using a lambda (or object that responds to `matches?`) works.

```ruby
# Doesn't work:
get '/*page', to: 'pages#show', constraints: { format: 'html' }
# Works:
get '/*page', to: 'pages#show', constraints: lambda {|req| req == :html }
```

The documentation specifically says that this should work:

> Request constraints work by calling a method on the Request object with the same name as the hash key and then compare the return value with the hash value. Therefore, constraint values should match the corresponding Request object method return type. For example: constraints: { subdomain: 'api' } will match an api subdomain as expected, however using a symbol constraints: { subdomain: :api } will not, because request.subdomain returns 'api' as a String.
[Source](http://guides.rubyonrails.org/routing.html#request-based-constraints)

So I went digging and produced a failing test case in the ActionDispatch test suite:

```ruby
class TestGlobFormatConstraints < ActionDispatch::IntegrationTest
  Routes = ActionDispatch::Routing::RouteSet.new.tap do |app|
    app.draw do
      ok = lambda { |env| [200, { 'Content-Type' => 'text/plain' }, []] }

      # These routes do not work:
      get '/*page', to: ok, constraints: { format: 'html' }
      # get '/*page', to: ok, format: 'html'
      # get '/*page', to: ok, constraints: { format: /html/}
      # get '/*page', to: ok, format: false, constraints: { format: 'html'}
      # get '/*page', to: ok, format: true, constraints: { format: 'html'}
      # get '/*page', to: ok, format: 'html', constraints: { format: 'html'}

      # This works:
      # get '/*page', to: ok, constraints: lambda {|request| request.format == :html }
    end
  end

  APP = build_app Routes
  def app; APP end

  def test_glob_format_constraints
    get 'http://www.example.com/foobar.html'
    assert_response :success

    get 'http://www.example.com/foobar'
    assert_response :success

    get 'http://www.example.com/foobar.json'
    assert_response :not_found
  end
end
# Fails on `master` and `4-2-stable`:
#   1) Failure:
# TestGlobFormatConstraints#test_glob_format_constraints [test/dispatch/routing_test.rb:4019]:
# Expected response to be a <not_found>, but was <200>.
# Expected: 404
#   Actual: 200
```

But I didn't get very far in finding a fix. I'm not sure if the problem is in Journey or in ActionDispatch. Or if this is simply unsupported behaviour and the documentation should be changed to mention that only certain hash keys are checked against the request.

If you think this is a bug, I'd love to fix it, but I guess I'd need some pointers as to where to look. After trying and failing to fix this for nearly a full day, I'm at my wit's end.

**Comment by davidguilherme** [comment]
Options supported: [:protocol, :subdomain, :domain, :host, :port].

See:
```ruby
# action_dispatch/routing/mapper.rb line 777
def scope(*args)
  #...
  if options[:constraints].is_a?(Hash)
    defaults = options[:constraints].select do
      |k, v| URL_OPTIONS.include?(k) && (v.is_a?(String) || v.is_a?(Fixnum))
    end

    (options[:defaults] ||= {}).reverse_merge!(defaults)
  else
    block, options[:constraints] = options[:constraints], {}
  end
  #...
end
```
[Source](https://github.com/rails/rails/blob/master/actionpack/lib/action_dispatch/routing/mapper.rb#L777)

```ruby
# action_dispatch/routing/mapper.rb line 14
URL_OPTIONS = [:protocol, :subdomain, :domain, :host, :port]
```
[Source](https://github.com/rails/rails/blob/master/actionpack/lib/action_dispatch/routing/mapper.rb#L14)

**Comment by mrnugget** [comment]
I saw this too. That's what I meant, when I said that the documentation should be changed to reflect this. Because, as of now, it says:

> Request constraints work by calling a method on the Request object with the same name as the hash key and then compare the return value with the hash value.

There should at least a mention of `URL_OPTIONS` and what it contains.

**Comment by rafaelfranca** [comment]
:+1:. Care to send a PR upgrading the documentation?

**Comment by mrnugget** [comment]
If the behaviour described above is correct and only the documentation is lacking, then yes, of course!

**Comment by rafaelfranca** [comment]
I think we can do both, change the documentation first and in other PR we can add support to `format`.

**Comment by mrnugget** [comment]
Sounds good! I'm really busy this week, so I'll send a PR at the beginning of next week! Thanks

**Comment by mrnugget** [comment]
After further investigation I wasn't sure anymore as to how to update the documentation. I don't think `URL_OPTIONS` has anything to do with this "bug". 

The problem I described only arises with globbing routes. [These test cases all work](https://github.com/rails/rails/blob/4-2-stable/actionpack/test/dispatch/routing_test.rb#L4287-L4290):

```ruby
      get '/string', to: ok, constraints: { format: 'json'  }
      get '/regexp',  to: ok, constraints: { format: /json/ }
      get '/json_only', to: ok, format: true, constraints: { format: /json/ }
      get '/xml_only', to: ok, format: 'xml'
```

But, again, this doesn't work:

```ruby
      get '/*page', to: ok, constraints: { format: 'html' }
```

So if I were to update the documentation: what should I write? After rechecking this and playing around with `URL_OPTIONS` and my test case I'm convinced that the problem is how glob routes handle `constraints`.

Any ideas? Thoughts? Opinions?

**Comment by Ferdy89** [comment]
@mrnugget I investigated this a little and found that the reason your last examples work is because the `format` constraint falls under the [segment ones](http://guides.rubyonrails.org/routing.html#segment-constraints) since it's always implicitly part of the path as an optional parameter. These constraints are enforced through generated regexes:
```ruby
# Generates /\A\/page(?:\.(html))?\Z/
# Matches /page
# Matches /page.html where format == 'html'
# Does not match /page.json
get '/page', to: ok, constraints: { format: 'html' }

# Generates /\A\/((?-mix:.+?))(?:\.(html))?\Z/
# Matches /page
# Matches /page.html where format == 'html'
# Matches /page.json where page == 'page.json' and format == nil
# The glob pattern also matches dots, which makes sense
get '/*page', to: ok, constraints: { format: 'html' }
```
Note how the first one will also match `/page` because it makes the `.html` an optional match, even though it does not explicitly have that format and there's a constraint against it.

So it seems to me like the actual bug would be that the regex _always_ makes `format` optional. Making it not optional when there's a constraint would fix the problem but would cause
```ruby
# This will not match /page anymore
get '/page', to: ok, constraints: { format: 'html' }
```
Which kind of seems like a breaking change. I haven't gone deep enough to make this change in code, but I could if you guys think it's the right thing to do.

About the documentation, there's really nothing to do with `URL_OPTIONS` that I can see. The reason `format` seems to not be working is because it's being treated as a [segment constraint](http://guides.rubyonrails.org/routing.html#segment-constraints) instead of a [request-based constraint](http://guides.rubyonrails.org/routing.html#request-based-constraints), even though it's a method in the [Request object](http://guides.rubyonrails.org/action_controller_overview.html#the-request-object). The separation of the two is made here:
```ruby
# actionpack/lib/action_dispatch/routing/mapper.rb line 244
def split_constraints(path_params, constraints)
  constraints.partition do |key, requirement|
    path_params.include?(key) || key == :controller
  end
end
```
I guess this exception is worth mentioning. `Request#format` returns a `Mime::Type` though, which is probably not what a user would expect.

I can change the documentation to reflect that exception and work on a fix if the proposed solution is accepted as valid.

**Comment by mrnugget** [comment]
Thanks for investigating this, @Ferdy89! I think I understand the behaviour now, thanks to your explanation in regards to segment based constraints and request-based constraints. I expected "format" to work with the Request object.

I think reflecting this exception in the documentation would be great.

**Comment by Ferdy89** [comment]
While writing an update to the docs, I realized that in they mention the peculiarity of the `format` parameter in the [section about glob routes](http://guides.rubyonrails.org/routing.html#route-globbing-and-wildcard-segments). That means the original test in this issue could be rewritten as:

```ruby
class TestGlobFormatConstraints < ActionDispatch::IntegrationTest
  Routes = ActionDispatch::Routing::RouteSet.new.tap do |app|
    app.draw do
      ok = lambda { |env| [200, { 'Content-Type' => 'text/plain' }, []] }

      get '/*page', to: ok, format: true, constraints: { format: 'html' }
    end
  end

  APP = build_app Routes
  def app; APP end

  def test_glob_format_constraints
    get 'http://www.example.com/foobar.html'
    assert_response :success

    # format is set as mandatory, so this doesn't match
    get 'http://www.example.com/foobar'
    assert_response :not_found

    # but this doesn't match either
    get 'http://www.example.com/foobar.json'
    assert_response :not_found
  end
end
```

**Comment by Ferdy89** [comment]
So the exception of the `format` constraint is documented now, is there anything else left for this issue to address @mrnugget?

**Comment by mrnugget** [comment]
I don't think so, no. Thanks a lot for updating the documentation and explaining the issue so clearly. I appreciate it.

**Comment by pixeltrix** [comment]
Just a note to say that you can do `format: true` or put the `:format` key in the path to make the format required, e.g:

``` ruby
get '/*page', to: ok, format: true, constraints: { format: 'html' }
get '/*page.:format`, to: ok, constraints: { format: 'html' }
```

Obviously it'll no longer match `/page` since that's missing the extension.
