### ISSUE TITLE
[Bug] rails 4.2(ruby 2.0) , cannot display error in development mode.

### ISSUE THREAD

**Issue by chenge** [rails/rails#20271]
Detail info in: https://ruby-china.org/topics/25714

Test with this sample: https://github.com/58383788/sample_app
Reproduce error: register---->click User---->error

If I use ruby 2.2.1, it's OK.
I want to know the reason.  Does rails have test suit?

**Comment by simlegate** [comment]
Chinese !!!

**Comment by tgxworld** [comment]
Tested in `2.0.0p643` and I couldn't reproduce your error with the application that you've provided. :confused:
