### ISSUE TITLE
undefined method http_basic_authenticate_with  in ArticlesController

### ISSUE THREAD

**Issue by EddieDow** [rails/rails#20287]
I am encounter issue when trying to run the demo project on http://edgeguides.rubyonrails.org/contributing_to_ruby_on_rails.html#contributing-to-the-rails-documentation, that failed when involved with function http_basic_authenticate_with, I just copy code sample code from the guidelines blog, the environment is rails 4.2.1, ruby 2.2.1p85 (2015-02-26 revision 49769) [x86_64-darwin14]

Any help are welcomed.

**Comment by prathamesh-sonpatki** [comment]
Hi @EddieDow Please provide some more information about what error you are getting. Preferably try to create a sample app and upload it to Github so others can see the code and help you with the error.
Thanks.

**Comment by senny** [comment]
It's been a month without feedback. I'm going to close this issue.

@EddieDow if you still experience that problem, please report back with a way to reproduce and I'll gladly reopen the issue. Thank you for reporting.
