### ISSUE TITLE
[Bug] Rails 4.2.1 - integration test incorrect path join

### ISSUE THREAD

**Issue by syndbg** [rails/rails#20283]
I'm learning Rails and loving it so far.
But I have some troubles testing a `show` resource route and I'm sure I encountered a bug.

In an integration test I want to test `resources :users`, UserController#show. I would do so by `assert_select assert_select 'a[href=?]', users_path(@user) `, but it fails due to users_path joining `@user` by '.' ? 

I have the following files
```ruby
class UsersController < ApplicationController
  def index
    @users = User.paginate(page: params[:page])
  end

  def show
    @user = User.find(params[:id])
  end
end
```

```ruby
Rails.application.routes.draw do
  resources :users
end
```

```ruby
class SiteLayoutTest < ActionDispatch::IntegrationTest
  def setup
    @user = users(:joe)
  end

  test 'layout links when logged in as non-admin user' do
    login_as(@user)
    get root_path
    assert_template 'static_pages/home'
    assert_select 'a[href=?]', users_path(@user) # fails cause it tries to mach "a[href="/users.950961012"]",
    assert_select 'a[href=?]', "/users/#{@user.id}" # manual and correct
  end
end
```

If the following is a bug, I'll gladly submit a PR and make this (possibly) my first Rails PR. However I require a bit of guidance where the problem lies. I think it may be in `action_dispatcher.rb` or `route_set.rb`, but needless to say I'm not too familiar with Rails :8ball:

**Comment by yoongkang** [comment]
That's because you're using `users_path`. That's a different route, which is matched to your index action, and doesn't take an `:id` param.

Try using `user_path` in your test (singular, not plural). 

If you enter `rake routes` in your terminal you'll see a list of routes and the path helpers.

**Comment by syndbg** [comment]
I wanted to test specifically the `#show` path and as you mentioned that's possible with `user_path`.

Thank you, very much!
