### ISSUE TITLE
bin/setup doesn't work out of the box after git clone

### ISSUE THREAD

**Issue by chancancode** [rails/rails#20299]
The last step of `bin/setup` is to run `touch tmp/restart`: https://github.com/rails/rails/blob/master/railties/lib/rails/generators/rails/app/templates/bin/setup#L28

This doesn't seem to work after cloning a Rails app:

```
== Restarting application server ==
touch: tmp/restart.txt: No such file or directory
```

Presumably, this is because the `tmp` directory doesn't exists since it is `.gitignore`d by default.

1. we should make it work
2. `tmp` should probably exists after clone (maybe `.gitkeep`?)
3. we should probably use [`rake restart`](https://github.com/rails/rails/blob/230393a5bdf10089006b7666fa15cb4543a46486/railties/lib/rails/tasks/restart.rake#L1-L3) instead of touching the file directly

**Comment by whatasunnyday** [comment]
I'm giving this a go now! If I don't get a PR by EOD, someone else feel free to take it over.

**Comment by yoongkang** [comment]
Oh crap.. Sorry @whatasunnyday, I didn't see your comment until I pushed..

**Comment by whatasunnyday** [comment]
@yoongkang np. Good work!

**Comment by whatasunnyday** [comment]
Also, @yoongkang to address 2 of @chancancode's comment you might want to change https://github.com/rails/rails/blob/master/railties/lib/rails/generators/rails/app/templates/gitignore

```
/log/*
<% if keeps? -%>
!/log/.keep
<% end -%>
/tmp
```

to
```
/log/*
/tmp/*
<% if keeps? -%>
!/log/.keep
!/tmp/.keep
<% end -%>
```

and add `.keep` file to tmp instead of creating a new `/tmp/` directory in the rake task.

**Comment by simi** [comment]
@whatasunnyday yes, that will be good to keep `bin/setup` as much bulletproof as it is possible.

**Comment by yoongkang** [comment]
@whatasunnyday thanks, I've added your name to the changelog, hope you don't mind! :)

https://github.com/yoongkang/rails/commit/32f8763780f6a036d75b5089de2c10f17d03006b

**Comment by whatasunnyday** [comment]
@yoongkang not one bit ;)
