### ISSUE TITLE
Rabl/JSON views are hanging and not being rendered with ActionController::Live

### ISSUE THREAD

**Issue by mattclar** [rails/rails#20301]
Simply when I include ActionController::live in my Appointments Controller my apptbook view which i request as appointments/apptbook.json is loaded (i can see the database loads on the terminal attached to my server) but nothing is returned to the browser, the browser hangs waiting for a response. Can't seem to work this out none of my usual html views in this same controller stall out like this, however i just tried my index json which I can confirm stalls out, so when i request /appointments I get a normal html response, however when i request /appointments.json or /appointments/apptbook.json I never see anything returned to the browser.

this happens for json requests, be they via rabl, rendering straight to json or Activemodel:serializers

Is there an incompatibility with ActionController::Live??

I have tried only including it in my events method but it seems to need to be loaded at the top.

Is there a way of unloading it for a few of my methods??

Controller:

    class AppointmentsController < ApplicationController
    include ActionController::Live
    
    def index

    @appointments = Appointment.all

    ActiveRecord::Base.include_root_in_json = false
    
    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @appointments.to_json(:only => [:id, :start, :end], :methods => :title) }
        end
    end
           def apptbook
                @appointments = Appointment.last(2)
           end

    end
View:

    collection @appointments
    attributes :id
    node(:start) { |appointment| appointment.start.iso8601}
    node(:end) { |appointment| appointment.finish.iso8601}
    node(:title) { |appointment| '<a class="patient-select-link" data-id="'+appointment.patient.id.to_s+'">'+appointment.patient.full_name+'</a>' }

**Comment by mattclar** [comment]
Ok so I decided to extract all my SSE ActionController:live code out of the seperate controllers and into a dedicated events controller, which obviously solves my problem, but I still think this is a bug, including   ActionController::live shouldnt disrupt other parts of the controller?!

**Comment by rafaelfranca** [comment]
> Including ActionController::live shouldnt disrupt other parts of the controller?!

Yes, it does. Because you include in the whole controller not just in the action. This is one of the gotchas from using `ActionController::Live`, and it is documented. See http://api.rubyonrails.org/classes/ActionController/Live.html.
