### ISSUE TITLE
Using an association name as the key in a call to `where` can act inconsistently

### ISSUE THREAD

**Issue by sgrif** [rails/rails#20308]
https://gist.github.com/senny/1ae4d8ea7b0e269ed7a0

This is something I'm currently working on, but wanted to document.

**Comment by matthewd** [comment]
Per discussion in the vicinity of https://github.com/rails/rails/pull/13555#issuecomment-43038895, if we don't manage to make this work properly for 5.0, I think we should return to the 4.2 behaviour (no support for association names) rather than release with the behaviour shown in that gist.

**Comment by sgrif** [comment]
So I'm a bit torn on how to go about tackling this. Ultimately we cannot possibly know what the name of the table will be until we know all joins at the final construction of the tree. While that seems like something that we should be able to do, it requires a pretty big re-architecting, which I don't think I can finish in time for Rails 5.

My immediate reaction to this is that we should *always* alias the table name based on the association name, but that raised some obvious problems in the test. Since methods like `order` don't have an API to deal with joined columns (e.g. `User.joins(:posts).order(posts: :id)`), there's likely a ton of code out there relying on the current aliasing behavior (or lack thererof)

In the short term, I'm going to revert to something closer to Rails 4.2 behavior (it's assumed the association name and the table name match, which is subtly different than the current behavior WRT type casting.) However, I'm wondering if we can support the simple case, and just raise an exception if there's ambiguity. I'll explore that further.

Long term, the plan stays the same: I'm hoping to re-evaluate the entirety of how we construct joins, and publish an explicit contract for aliasing, in as much of a backwards compatible way as possible. However I think this should target Rails 5.1, unless I end up being able to go back to full time OSS soon and can really devote the time required to this.

**Comment by sgrif** [comment]
Additional thoughts about this issue are in the message of the commit closing this issue.
