### ISSUE TITLE
Complex issue with transactions in testing

### ISSUE THREAD

**Issue by nyarly** [rails/rails#20311]
Apologies up front for a terrible bug report. It seemed better to make a public note than do nothing.

In recent work, I set up a large list of records with FactoryGirl in a request spec. To shave time in the tests, I pushed the factorying to a before(:all), complete with transaction based DatabaseCleaner commands. (i.e. there was also an `after(:all){ DatabaseCleaner.clean }` ). If these tests were run along with a Capybara feature test that worked with the same tables, the *second* example in the request specs (one the second, and the second example in both related groups) would fail as if the tables were empty.

In the test logs, I found that the working examples were surrounded in BEGIN and COMMIT statements, and that there were activerecord SAVEPOINTS interspersed, as I'd expect. But the failing specs were using full transactions instead of savepoints - in other words, where I'd expect a SAVEPOINT in the test logs, there was a COMMIT-BEGIN pair.

Most worrying, grepping the log for BEGIN|COMMIT|ROLLBACK exposed that there was a pair of BEGIN statements without a COMMIT or ROLLBACK.

That's when I stopped trying to fix my tests: I switch the factories into a before :all and went on with other work.

I'm reporting this because it looks to me like this particular configuration has gotten Activerecord to lose its understanding of where in the transaction chain it is, which shouldn't ever happen.

I know that without a executable test case, this'll be very difficult to diagnose, but unfortunately this is happening in client code, and I'm on their dime: I can't share the code and I can't spare the hours to produce a reduced test case.

I can report that the relevant gems and their versions are:
```
activerecord (4.1.9)
capybara (2.4.4)
factory_girl (4.5.0)
factory_girl_rails (4.5.0)
selenium-webdriver (2.45.0)
rspec (3.0.0)
rspec-rails (3.0.2)
```

**Comment by arthurnn** [comment]
> I'm reporting this because it looks to me like this particular configuration has gotten Activerecord to lose its understanding of where in the transaction chain it is, which shouldn't ever happen.

Thats possible. TBH I saw this before, but it was my fault, as it was due a monkey patch we had in our code. Not sure if I saw this happening in a vanilla rails app.

> I can't share the code and I can't spare the hours to produce a reduced test case.

Unfortunately, the only way I can fix the bug is if I can simulate it, and I would need a script or an app to work on.
For the time being, I will close the issue. Fell free to reopen it, with a reproducible script, or to send a PR to fix the actual problem.
