### ISSUE TITLE
route helper methods are not getting created while using the controller option.

### ISSUE THREAD

**Issue by aruprakshit** [rails/rails#20312]
I have the the below chunk inside my _routes.rb_ file.

``` ruby
  controller :post do
    post 'post/:id/like' =>  :like
    delete 'post/:id/unlike' =>  :unlike
  end
```

But it is not generating helper methods.

``` sh
[shreyas@app (master)]$ rake routes | grep post
                                    POST       /post/:id/like(.:format)                       post#like
                                    DELETE     /post/:id/unlike(.:format)                     post#unlike
[shreyas@app (master)]$ rails -v
Rails 4.2.1
```

I found [this](http://api.rubyonrails.org/classes/ActionDispatch/Routing.html) in the doco as : 

> Note: when using controller, the route is simply named after the method you call on the block parameter rather than map.

**Comment by universal** [comment]
Taking the example from http://api.rubyonrails.org/classes/ActionDispatch/Routing.html:

```
controller :blog do
  get 'blog/show'     => :list
  get 'blog/delete'   => :delete
  get 'blog/edit/:id' => :edit
end
```

This results in the following routes to be generated on 4.2.1:

```
                       blog_show GET    /blog/show(.:format)                                                               blog#list
                     blog_delete GET    /blog/delete(.:format)                                                             blog#delete
                                 GET    /blog/edit/:id(.:format) 
```

It looks like the two routes without an ```:id``` parameter work as advertised, but the route with the ```:id``` parameter does not generate a named path. I'm not sure if this is simply an error in the documentation, or an error in the routing code.

**Comment by rafaelfranca** [comment]
I never remember how this works. @pixeltrix @carlosantoniodasilva @fxn do you know?

**Comment by universal** [comment]
If i found the correct lines in the long mapper file, these should be it:

controller: https://github.com/rails/rails/blob/4-2-stable/actionpack/lib/action_dispatch/routing/mapper.rb#L827-L830
scope: https://github.com/rails/rails/blob/4-2-stable/actionpack/lib/action_dispatch/routing/mapper.rb#L779-L820
map_method: https://github.com/rails/rails/blob/4-2-stable/actionpack/lib/action_dispatch/routing/mapper.rb#L686-L691 and directly above the wrappers for this function
match: https://github.com/rails/rails/blob/4-2-stable/actionpack/lib/action_dispatch/routing/mapper.rb#L1472

This probably helps someone knowing a bit more about the routing code :-)

**Comment by carlosantoniodasilva** [comment]
It looks like the ones with the dynamic segment `:id` do not generate the name, but I don't really remember the details off the top of my head, will look it further.

**Comment by meinac** [comment]
I've found the problem, [here is the breaking point](https://github.com/rails/rails/commit/f63d35fba55867111427bfeb54c31b11e02d5d3f). I'm trying to understand reason behind of this commit and try to achieve it in another way.

**Comment by yoongkang** [comment]
I have a proposed solution for this at #20374.

**Comment by pixeltrix** [comment]
This is unrelated to the `controller` scoping - it's just that the automatic name generator fails when there's a `:id` in the path. This is probably because Rails 3.0 was overwriting the names with each route, e.g.

``` ruby
resources :posts
```

would generate in Rails 3.0.0:

```
   Prefix Verb   URI Pattern               Controller#Action
    posts GET    /posts(.:format)          {:action=>"index", :controller=>"posts"}
    posts POST   /posts(.:format)          {:action=>"create", :controller=>"posts"}
 new_post GET    /posts/new(.:format)      {:action=>"new", :controller=>"posts"}
edit_post GET    /posts/:id/edit(.:format) {:action=>"edit", :controller=>"posts"}
     post GET    /posts/:id(.:format)      {:action=>"show", :controller=>"posts"}
     post PUT    /posts/:id(.:format)      {:action=>"update", :controller=>"posts"}
     post DELETE /posts/:id(.:format)      {:action=>"destroy", :controller=>"posts"}
```

whereas today in Rails 4.2.4 it generates:

```
   Prefix Verb   URI Pattern               Controller#Action
          POST   /posts(.:format)          posts#create
 new_post GET    /posts/new(.:format)      posts#new
edit_post GET    /posts/:id/edit(.:format) posts#edit
     post GET    /posts/:id(.:format)      posts#show
          PATCH  /posts/:id(.:format)      posts#update
          PUT    /posts/:id(.:format)      posts#update
          DELETE /posts/:id(.:format)      posts#destroy
```

See how the later member routes clobber the original route in Rails 3.0.0. What's happening is that the code that detects this is also being applied to non resource routes as well - we should probably have a different set of logic for routes outside of a resource scope.
