### ISSUE TITLE
Ruby on Rails Security Guide Additional Resources No Longer Available

### ISSUE THREAD

**Issue by tihuan** [rails/rails#20318]
http://guides.rubyonrails.org/security.html#additional-resources

`A good security blog including the Cross-Site scripting Cheat Sheet`
http://ha.ckers.org/ is no longer available.

**Comment by yoongkang** [comment]
Thanks, this had already been fixed in master: http://edgeguides.rubyonrails.org/security.html#additional-resources

However, I found another link to the ha.ckers.org domain and opened a PR which is now merged.
