### ISSUE TITLE
prev_week doesn't work like what the doc said 

### ISSUE THREAD

**Issue by ShallmentMo** [rails/rails#20315]
I want to use prev_week to get Monday in last week.Here is the code

    "2015-05-24".to_date.prev_week :monday #=> Mon, 18 May 2015

I want :monday to be the first day of prev_week, I think it should return Mon, 11 May 2015, so I add the config:

    config.beginning_of_week = :monday

then, I get this

    "2015-05-24".to_date.prev_week #=>Mon, 11 May 2015
    "2015-05-24".to_date.prev_week :monday #=>Mon, 11 May 2015

so I think it doesn't work like what the doc says.

**Comment by claudiob** [comment]
Hello @ShallmentMo !

The [documentation](http://api.rubyonrails.org/classes/DateAndTime/Calculations.html#method-i-prev_week) of `prev_week` says:

> Returns a new date/time representing the given day in the previous week. 

Here's a representation of the days in May 2015, with the weeks starting on Monday:

```
| Mo | Tu | We | Th | Fr | Sa | Su |
|  4 |  5 |  6 |  7 |  8 |  9 | 10 |
| 11 | 12 | 13 | 14 | 15 | 16 | 17 |
| 18 | 19 | 20 | 21 | 22 | 23 | 24 |
| 25 | 26 | 27 | 28 | 29 | 30 | 31 |
``` 

The date you specified (May 24th) falls into the week of May 18th to May 24th.
The Monday of the previous week is therefore May 11th, as returned by `prev_week`.

**Comment by ShallmentMo** [comment]
@claudiob , I understand why it's May 11th. Which I don't understand is the first line of codes when I haven't set config.beginning_of_week. It return Mon, 18 May 2015 when I pass :monday as parameter.

**Comment by claudiob** [comment]
@ShallmentMo Under which circumstances is the result "Mon, 18 May 2015"? 

From your code above, it looks like the result is correct. 
Maybe your Rails application is overriding the default value of `Rails.configuration.beginning_of_week`?

**Comment by ShallmentMo** [comment]
Is it I misunderstand? The parameter start_day will not override the  config.beginning_of_week ,  it is just ask the day of previous week, not set the beginning_of_week to be the day?
