### ISSUE TITLE
Add Enumerable#pluck

### ISSUE THREAD

**Issue by dhh** [rails/rails#20339]
It's common to have methods that can operate on either an array, an unloaded Active Record scope, or a loaded AR scope. AR scopes supply the #pluck method to grab just a single value efficiently through SQL. It should be possible to call #pluck on an array of ARs or hashes and expect the same, as well as not requiring another SQL call if the scope has already been loaded.

Implementation:

```ruby
module Enumerable
  def pluck(key)
    collect { |item| item[key] }
  end
end
```

Using #[] allows us to match the behavior of scope#pluck as close as possible, as ActiveRecord::Base#[] will grab the value straight from the attributes hash – not by calling #key. As that might well have been overwritten by the user, and thus the values between unloaded_scope#pluck and loaded_scope#pluck would differ.

**Comment by kddeisz** [comment]
I'd be happy to do this is that's alright?

**Comment by kddeisz** [comment]
PR: https://github.com/rails/rails/pull/20350
