### ISSUE TITLE
Relation does not respond to #compact

### ISSUE THREAD

**Issue by amilligan** [rails/rails#20330]
PRs #19836 and #20328 are both entirely valid resolutions for this issue. 

Given, that `#compact` does not mutate a collection, and the rule is that that `Relation` should not respond to mutating methods, the blacklist is not necessary.  

The missing method forces use of RTTI, or extraneous use of `#to_a`, to work around the interface mismatch.

**Comment by rafaelfranca** [comment]
:+1: reopening the PRs

**Comment by amilligan** [comment]
Great, thanks for taking another look.
