### ISSUE TITLE
ActiveRecord::Base#find(array) should return result in same order as the array

### ISSUE THREAD

**Issue by dhh** [rails/rails#20338]
It's common to want to find a group of records and have them returned in the same order that you asked for them. We can't expect SQL to do this for us. So instead we should make #find do the work. Here's a naive implementation:

```ruby
  def records_in_sequence(records, sequence_of_ids)
    records_by_id = records.each_with_object(Hash.new) do |record, records_by_id|
      records_by_id[record.id] = record
    end

    sequence_of_ids.collect { |id| records_by_id[id] }
  end
```

#find should call #records_in_sequence on any calls where the *ids set size is >1.

**Comment by bogdan** [comment]
`find` argument may contain duplicated ids. Right now, it de-duplicates them automatically. I use this behaviour because sometimes I am too lazy to call `uniq` myself. Especially in console, I relay on it a lot.
It can break existing behaviour by returning same record twice.

Also other people may relay on a fact that it will return records in the order specified in the relation.
The following will change it's behaviour:

``` ruby
User.order(:email).find([1,2,3,4])
``` 

Even no order in relation can give default order by `id`. Relaying on this fact is not so good idea, but people do it ALOT.

So it is very tricky thing to support. Sometime you would want order in `find` argument, sometimes you don't.

I would prefer to see it as another method.

**Comment by dhh** [comment]
We don't need to return the same record twice, even if that was a blocker.
Could just interpolate on the first occurrence. This is not worth a
separate method in my mind.

**Comment by rafaelfranca** [comment]
@dhh but I have to agree with the `order` case. Which order should we follow, if the argument order it will be a breaking change and we don't have a good way to warn users about it. If it is the `order` definition it will be backward compatible but the implementation will be tricky.

**Comment by dhh** [comment]
Happy to make this happen only when no order is given. I never use order when I give a specific list of ids.

**Comment by rafaelfranca** [comment]
:+1:

**Comment by bogdan** [comment]
Well order is a common thing as default scope or in association. 

Nevertheless it is still a breaking change because of default order by `id desc`. Even though it is not officially supported by the database. But I'll leave it for rails-no-breaking-changes team to decide.

**Comment by dhh** [comment]
I think allow you to get records back in a ordered fashion is more
important in this case, so let's proceed.

**Comment by snags88** [comment]
just curious if this would be applicable to #find_by(attribute: array) as well?

**Comment by dhh** [comment]
I wouldn't expect it in the same way I expect #find(pks) to.

**Comment by miguelgraz** [comment]
In case you didn't see that yet, I took my chances and submitted [this PR](https://github.com/rails/rails/pull/20453) in attempt to "fix" this issue. Would love all feedbacks <3

**Comment by miguelgraz** [comment]
What about the `offset` clause? Is it correct to think that `Topic.offset(2).find([3,2,5,1,4])` would return the same as `Topic.find([5,1,4])`?

**Comment by dhh** [comment]
Yes, that makes sense to me.

**Comment by cristianbica** [comment]
There are some ways of doing this sorting at the adapter level http://stackoverflow.com/questions/866465/sql-order-by-the-in-value-list

**Comment by miguelgraz** [comment]
Okay so the current PR-candidate to fix this has an issue with chained `offset` clause, not sure on how to fix this but we already raised some discussion on if it should be supported/handled by ActiveRecord or if it should have a simpler approach and just let the database handle the `offset`.

If anyone would like to review here's [my last comment](https://github.com/rails/rails/pull/20453#issuecomment-128829740) on the PR explaining the current situation, would love your feedback and opinions <3
