### ISSUE TITLE
Code reloading constant lookup issue

### ISSUE THREAD

**Issue by dreyks** [rails/rails#20340]
My app uses several unbuilt isolated engines, sometimes class and module names inside them coinside.
Say I have an Engine `A` and a `B` class in it, so it is `A::B`. Then I have an engine `B`. So there's a class `A::B` and a module `B`.
In order to be sure that all the constants resolve well I put `config.eager_load = true` into `development.rb`
Now when in the controller of `A` (which is properly namespaced) I write `@b = B.new` and start up the server, everything goes fine: I get an instance of `A::B`. But that's untill I make a change somewhere in codebase. A soon as this happens I get `undefined method 'new' for B:Module`

I've made up a sample app 
https://github.com/dreyks/rails_constant_lookup

Steps to reproduce:
  1. Start the server and navigate to `http://localhost:3000/a` (everything is fine you get the `A::B` output)
  2. Make any change to any file that triggers rails code reload (e.g. to the controller)
  3. Refresh the page (you get an error)
  4. Restart the server and refresh the page. The error is gone

**Comment by Alric** [comment]
I was able to reproduce using the sample app.

It always works fine if you fully qualify the class, i.e., use A::B to refer to, but I get your point that it seems you shouldn't have to here – especially as the B class and B module are in separate, isolated engines.

And it never works in dev if you leave eager_load false. So I guess the question here is what is different between the eager load behavior and the autoloader, which I think uses ActiveSupport::Dependencies. 

I don't know the answer to that, but I think this is a real issue that at least needs a better explanation.

**Comment by matthewd** [comment]
http://guides.rubyonrails.org/autoloading_and_reloading_constants.html#when-constants-aren-t-missed
