### ISSUE TITLE
Remove of File.expand_path in Rails::Server

### ISSUE THREAD

**Issue by radar** [rails/rails#20345]
Currently, Rails has [this code in `Rails::Server`](https://github.com/rails/rails/blob/73aab036eeeb297dc85dc812f54e26aa943f48f7/railties/lib/rails/commands/server.rb#L101):

```ruby
config:             File.expand_path("config.ru")
```

I am not sure that this is `File.expand_path` is necessary any longer, as Rack [has this code](https://github.com/rack/rack/blob/99293fa13d86cd48021630fcc4bd5acc9de5bdc3/lib/rack/server.rb#L333):

```ruby
@options[:config] = ::File.expand_path(options[:config])
```

It looks like `File.expand_path` is being called twice on `options[:config]` in two different contexts. I think it would be OK to remove the one from `Rails::Server`, but I'm opening this issue just so I can get a second opinion on that before I submit the patch.

**Comment by rafaelfranca** [comment]
If it works, seems fine to remove.

**Comment by kuldeepaggarwal** [comment]
@radar Are you still working on this? If not, then I would like.

**Comment by radar** [comment]
Sure, take it away :)
