### ISSUE TITLE
Fix Docs in regards to boolean presence validation

### ISSUE THREAD

**Issue by jcockhren** [rails/rails#20343]
### Problem
The ActiveRecord documentation contradicts itself.  See the [section on presence validation in regards to boolean values](http://guides.rubyonrails.org/active_record_validations.html#presence).

And I quote:

> Since false.blank? is true, if you want to validate the presence of a boolean field you should use one of the following validations:
```ruby
validates :boolean_field_name, presence: true
validates :boolean_field_name, inclusion: { in: [true, false] }
validates :boolean_field_name, exclusion: { in: [nil] }
```

However, given #18583, #7508 and #6953 seem to suggest that `false.blank? == true` is the intended behaviour. This in turns causes the presence validation of a boolean attribute with the value `false` to always fail. 

### Solution

Fix the docs. Remove the first "method" for validating boolean attributes from the code block shown above. The docs should now say:

Since false.blank? is true, if you want to validate the presence of a boolean field you should use one of the following validations:
```ruby
validates :boolean_field_name, inclusion: { in: [true, false] }
validates :boolean_field_name, exclusion: { in: [nil] }
```

PR forthcoming.

**Comment by jcockhren** [comment]
there ^

**Comment by laurocaetano** [comment]
closed by https://github.com/rails/rails/pull/20344
