### ISSUE TITLE
Rails 4.2 deprecation warning when using params in url helper

### ISSUE THREAD

**Issue by sethvargo** [rails/rails#20353]
When using a URL helper like:

```ruby
my_path(params.merge(foo: "bar"))
```

Where `params` is an `ActionController::Parameters`, the following deprecations is shown:

```text
DEPRECATION WARNING: Calling URL helpers with string keys controller, action is deprecated.
```

See also https://github.com/rails/rails/pull/17743#issuecomment-102393355

**Comment by rafaelfranca** [comment]
Yes. This is by design. You should filter and make the keys symbols before passing to the helper.

**Comment by sethvargo** [comment]
At the very least, I think the deprecation warning is misleading... I'm not using string keys - I'm using an object, and the appropriate path to fixing the deprecation is not immediately clear.

**Comment by sethvargo** [comment]
I also disagree a bit with your assessment. Consider a search page that uses query parameters. When linking to the next page, you want to pass in all the params from the URL into the link to the "next page". Those URL parameters may be unknown, and you may need to duplicate that logic multiple times on the page. It doesn't seem like the best approach.

**Comment by rafaelfranca** [comment]
@pixeltrix WDYT?

**Comment by patrickemuller** [comment]
@sethvargo Why you not try to create a helper called `params_without_controller` where you remove the controller and action and can pass arguments (removing the merge)? Can be a clear approach. What you think @rafaelfranca?

**Comment by carpodaster** [comment]
Wouldn't it be feasable to let the generated route helpers remove the `"controller"` and `"action"` key? The deprecation would still show up if string keys were passed to `url_for` directly. 

I can wrap that in a PR if this is an option.

**Comment by cmalpeli** [comment]
@sethvargo what did you end up doing here to resolve this?  running into the same issue (search results page).

**Comment by sethvargo** [comment]
@cmalpeli I used `grep -v` to ignore the warning.

**Comment by Frank004** [comment]
Hi I don't want to ignore the warning I want to fix it better? :/
