### ISSUE TITLE
ActionController::Base.helpers.image_url doesnt generate hashed version in initializer

### ISSUE THREAD

**Issue by christianonrails** [rails/rails#20377]
I got an constants.rb file in config/initializers with the following content:

```
DEFAULT_IMAGES  = {
  profile: ActionController::Base.helpers.image_url('v2/default_profilepic.jpg'),
  banner: ActionController::Base.helpers.image_url('v2/profile-banner.jpg'),
  missing: ActionController::Base.helpers.image_url('v2/missing.png'),
}
```

When I try to call DEFAULT_IMAGES somewhere in the code or even in the console then I get the images back without the hash. Is it that what its supposed to do and am I wrong in my expectations?

DEFAULT_IMAGES
=> {:profile=>"http://localhost:3000/assets/v2/default_profilepic.jpg", :banner=>"http://localhost:3000/assets/v2/profile-banner.jpg", :missing=>"http://localhost:3000/assets/v2/missing.png"}

I would expect something like this "/assets/v2/missing-d38d4bdbf9f2cf313e346a844de298c0.png"

**Comment by matthewd** [comment]
Please use the mailing list or StackOverflow for questions/help, where a wider community will be able to help you. We reserve the issues tracker for issues only.
