### ISSUE TITLE
any? overwrites COUNT(*) AS in custom select

### ISSUE THREAD

**Issue by collimarco** [rails/rails#20376]
I have the following query which is correct:

```
    Skill.select("similar_skills.*, COUNT(*) AS similarity") 
      .from("skill_similarities, skills AS similar_skills")
      .where("skill_similarities.skill2_id = #{self.id} AND skill_similarities.skill1_id = similar_skills.id
        OR skill_similarities.skill1_id = #{self.id} AND skill_similarities.skill2_id = similar_skills.id")
      .group("similar_skills.id")
      .order("similarity DESC")
```
The relevant part is `COUNT(*) AS similarity` because this gets overwritten when calling `any?`.

I get:

```
       PG::UndefinedColumn: ERROR:  column "similarity" does not exist
       LINE 2: ...r_skills.id) GROUP BY similar_skills.id  ORDER BY similarity...
                                                                    ^
       : SELECT COUNT(*) AS count_all, similar_skills.id AS similar_skills_id FROM skill_similarities, skills AS similar_skills WHERE (skill_similarities.skill2_id = 45 AND skill_similarities.skill1_id = similar_skills.id
               OR skill_similarities.skill1_id = 45 AND skill_similarities.skill2_id = similar_skills.id) GROUP BY similar_skills.id  ORDER BY similarity DESC
```

As you can see now we have `COUNT(*) AS count_all` instead of `COUNT(*) AS similarity`. IMHO this overwrite should not happen.

A workaround might be to name the alias `count_all` from the beginning, but this should be at least documented.

**Comment by sgrif** [comment]
This is more or less the expected behavior. Generally speaking, the values of `select` shouldn't affect the results of `any?` and are safe to override. That said, you've definitely got an edge case here. If you feel this could use additional documentation, please feel free to open a PR.
