### ISSUE TITLE
rake db:migrate fails with DATABASE_URL

### ISSUE THREAD

**Issue by bsodmike** [rails/rails#20373]
Hi guys,

I'm getting `Mysql2::Error: Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock'` and have verified that `DATABASE_URL` is set in the env.  The rake task is run with an entrypoint script within a Docker container.

This currently works if the container is given access to the mysql socket (via -v, to bind a local path), yet my app runs via `DATABASE_URL`.

Appreciate any thoughts on this, thanks.

**Comment by manishspuri** [comment]
is the db server running?i tried on local.. looks good...!

**Comment by bsodmike** [comment]
Hey manish, it connects fine if I disable the need to run migrations.

**Comment by bsodmike** [comment]
My config is as follows

```yaml
production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
```

It's running right now here, mwdesilva.com, but that's cause the migrations run via the socket.  If I prevent the container having access to the socket, then migrations fail, i.e. `-v /var/run/mysqld/:/var/run/mysqld/ `.  I've double confirmed that the container `ENTRYPOINT` script has indeed got access to `DATABASE_URL` (simulated by doing `echo $DATABASE_URL; exit 1`).

Scratching my head here...

**Comment by bsodmike** [comment]
Well, I learned something interesting today.  First off, `DATABASE_URL` cannot have `localhost` but rather `127.0.0.1`.  But the loop-back address inside a Docker container is the container itself.  One approach is to link containers, or pass the host IP (setup by docker) as `172.17.42.1`.

**Comment by bsodmike** [comment]
Hey @manishspuri, do me a favour please.  Change your `DATABASE_URL` to have `localhost` instead of `127.0.0.1`.  Does migration throw any errors now?
