### ISSUE TITLE
`.where` with array like object returns empty array

### ISSUE THREAD

**Issue by davidpdrsn** [rails/rails#20388]
`User.where(id: some_array_object)` works fine when `some_array_object` actually is an instance of `Array`, but returns an empty array when its only "array like". Could be that a decorator made with `SimpleDelegator` had been applied.

Here is an example:

```ruby
require "active_record"
require "pp"

puts "Active Record #{ActiveRecord::VERSION::STRING}"

ActiveRecord::Base.establish_connection(adapter: "sqlite3", database: ":memory:")
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :users, force: true do |t|
  end
end

class User < ActiveRecord::Base
end

class ArrayLike < SimpleDelegator
end

user = User.create!

puts "\n"

# This finds the user
pp User.where(id: [user.id])

puts "\n"

# This doesn't find the user
pp User.where(id: ArrayLike.new([user.id]))
```

I'm not sure if this is actually intended behaviour, but to me this seems like something that should work.

**Comment by yoongkang** [comment]
I had a brief poke around and so far it seems to be a typecasting issue.

Bizarrely, if you used this:

```ruby
User.where(id: ArrayLike.new([user.id]).all
```

It would work. But not:

```ruby
User.where(id: ArrayLike.new([user.id]).first
```

I might take a closer look later, but would be happy if anyone else wants to work on it.

**Comment by anand-mohanaveeramani** [comment]
Pull request : https://github.com/rails/rails/pull/20391

**Comment by matthewd** [comment]
https://github.com/rails/rails/pull/20391#issuecomment-107434338
