### ISSUE TITLE
Add Object#attempt to activesupport.

### ISSUE THREAD

**Issue by westoque** [rails/rails#20395]
I always encountered code that looked like:

```ruby
my_object.do_something if my_object.respond_to?(:do_something)
````

 I was thinking of adding `Object#attempt` to shorten this call. It would look like 

```ruby
my_object.attempt(:do_something)
```

Internally it would call `Object#try` and return the value of the call and not raise a `NoMethodError` if the method does not exist, instead it would fail gracefully and would return `nil`.

**Comment by chancancode** [comment]
Thanks exactly what Object#try does today :)

**Comment by chancancode** [comment]
See http://api.rubyonrails.org/classes/Object.html#method-i-try

**Comment by westoque** [comment]
@chancancode oh thanks. didn't see that.
