### ISSUE TITLE
add_column ignores index: true

### ISSUE THREAD

**Issue by collimarco** [rails/rails#20400]
Using Rails 4.2.0 the `index: true` part in the following statement is completely ignored:

```
add_column :my_table, :my_column, :boolean, index: true
```

This happens for any type of column (e.g. `boolean`, `string`).

To reproduce this issue just create a table:

```
class CreateExamples < ActiveRecord::Migration
  def change
    create_table :examples
  end
end
```

Then add:

```
class AddSomethingToExamples < ActiveRecord::Migration
  def change
    add_column :examples, :something, :string, index: true
  end
end
```

Run the migrations. Then check `schema.rb`or directly the database and you won't find any index.

The documentation says:

> See ActiveRecord::ConnectionAdapters::TableDefinition#column for details of the options you can use.

> :index - Create an index for the column. Can be either true or an options hash.

**Comment by rafaelfranca** [comment]
This is a documentation problem. Could you send a PR?

**Comment by collimarco** [comment]
What's wrong exactly with [the documentation](http://api.rubyonrails.org/classes/ActiveRecord/ConnectionAdapters/SchemaStatements.html#method-i-add_column)?

Is it the whole statement?

> See ActiveRecord::ConnectionAdapters::TableDefinition#column for details of the options you can use.

Or only a part of it?

Furthermore I find it useful to be able to pass options (such as `index: true`) to `add_column`. Are you sure that is only documentation that needs to be fixed and not the code?

**Comment by rafaelfranca** [comment]
The whole statement. `add_column` don't call `TableDefinition#column`, its call [`AlterTable#add_column`](https://github.com/rails/rails/blob/7785417984f61a9d5e00416c13b89dce2ee02daf/activerecord/lib/active_record/connection_adapters/abstract/schema_definitions.rb#L391) and this function don't accept all the options of `TableDefinition#column`.

The code can be changed, yes, bug only on the master branch. Meanwhile the stable branch will be with the wrong documentation so it is better to fix the documentation first and we can change the code later.

**Comment by collimarco** [comment]
Ok, sure! As you say the index option is passed up to [this method](
https://github.com/rails/rails/blob/21a60c15cca12c03f6c9e7500b9d1a4eaa05db1a/activerecord/lib/active_record/connection_adapters/abstract/schema_definitions.rb#L414), where, indeed, is lost.

**Comment by senny** [comment]
@collimarco I moved the documentation of common options to `add_column`. The `column` method now only documents the additional behavior. That should prevent further confusion. Thank you for reporting :yellow_heart:

**Comment by wagenet** [comment]
https://edgeguides.rubyonrails.org/active_record_migrations.html#column-modifiers still implies that this works.

**Comment by dogweather** [comment]
@wagenet I'd say it's even more than that: The Guide affirmatively states that `index` is a valid option:

> `index` Adds an index for the column.

@rafaelfranca I'd like to work on removing silent failures. Here, if the programmer uses an unknown or invalid option (like `index`), the code can help. It could log at the `WARN` level about the ignored option, or raise an error.

Would a PR for this be welcomed?
