### ISSUE TITLE
ActiveSupport::MessageVerifier raises "ArgumentError: invalid byte sequence in UTF-8" on malformed cookie

### ISSUE THREAD

**Issue by kenn** [rails/rails#20416]
Last night, we received a bunch of error notifications like this:

```ruby
ArgumentError: invalid byte sequence in UTF-8
/gems/activesupport-4.2.1/lib/active_support/core_ext/object/blank.rb:117 in ===
/gems/activesupport-4.2.1/lib/active_support/core_ext/object/blank.rb:117 in blank?
/gems/activesupport-4.2.1/lib/active_support/message_verifier.rb:38 in verify
/gems/activesupport-4.2.1/lib/active_support/message_encryptor.rb:64 in decrypt_and_verify
/gems/actionpack-4.2.1/lib/action_dispatch/middleware/cookies.rb:535 in decrypt_and_verify
/gems/actionpack-4.2.1/lib/action_dispatch/middleware/cookies.rb:516 in []
app/controllers/application_controller.rb:50 in current_user
app/controllers/application_controller.rb:61 in authenticate
```

and it turns out, the following code raises the error when an invalid string (e.g. "\xff") is given as the cookie value, set by a (potentially malicious) client.

```ruby
def current_user
  @current_user ||= User.find_by(id: cookies.encrypted[:user_id]) if cookies[:user_id]
end
```

Considering that it's a client error (or an attack attempt), we shouldn't raise an error and return 500.

Here's a minimal repro:

```ruby
verifier=ActiveSupport::MessageVerifier.new('secret')
verifier.verify("\xff")
ArgumentError: invalid byte sequence in UTF-8
```

I would suggest that `MessageVerifier#verify` will check if `signed_message` is a `valid_encoding?` before checking `blank?`.

```ruby
def verify(signed_message)
  raise InvalidSignature if !signed_message.valid_encoding? || signed_message.blank?
  ...
```

Let me know what you think.

**Comment by rafaelfranca** [comment]
> would suggest that MessageVerifier#verify will check if signed_message is a valid_encoding? before checking blank?.

Yeah, we should check if it is a valid encoding and return otherwise.
