### ISSUE TITLE
ActiveRecord::Calculations#count surprising results with conditions

### ISSUE THREAD

**Issue by rousisk** [rails/rails#20434]
Hello everyone,

Could you please share your thoughts on the following behaviour?

Rails 4.0.13

    User.count(conditions: { username: 'rousis' }) 
      SELECT COUNT(*) FROM "users" WHERE "users"."username = 'rousis' )
    => 1

Rails 4.1.10

    User.count(conditions: { username: 'rousis' }) 
      SELECT COUNT(*) FROM "users"
    => 0

Rails 4.2.1

    User.count(conditions: { username: 'rousis' }) 
      SELECT COUNT(*) FROM "users"
    => 0

I know that these type of finders have been deprecated. 

Nonetheless, while updating a project, I didn't see any deprecation for `count` (in 4.0.x), and in the next version the code "failed" silently (by not applying any conditions). The conditions are completely ignored (you can even specify non-existent columns without an error).

If you can think of any way to handle that more gracefully I would be happy to prepare a PR.

**Comment by matthewd** [comment]
Hmmm... does `activerecord-deprecated_finders` help?

If this case was somehow missed, it's too late to add the deprecation message to 4.0 (and with it having been MIA for quite a while now, I'm disinclined to temporarily add it back to 4.1, even though that's what a strict reading of our API policy seems to dictate). But if deprecated_finders is also unaware, we can definitely fix that.

**Comment by rousisk** [comment]
Hi @matthewd,

Indeed, `activerecord-deprecated_finders` brings back this functionality. This could be a gotcha for those upgrading from 4.0 or earlier but I do get your point about adding a deprecation message back to 4.0, so up to you.

Isn't it surprising though that passing any kind of hash to the current implementation of `count` just silently ignores that hash, without any error (as in the case where you specify a non-existing column, for example) or warning?

**Comment by rafaelfranca** [comment]
I think this feature was deprecated in 3.0 but we forgot to remove the code and we also forgot to deprecate again in 4.0.



> Isn't it surprising though that passing any kind of hash to the current implementation of count just silently ignores that hash, without any error (as in the case where you specify a non-existing column, for example) or warning?

Yes, we should raise Argument error if the argument is not a string or symbol. Could you work in a PR?

**Comment by rousisk** [comment]
Thanks for the input. 

Yes, I will prepare a PR for further feedback.

**Comment by rousisk** [comment]
@rafaelfranca it looks like everything is OK [on master](https://github.com/rails/rails/blob/master/activerecord/lib/active_record/relation/calculations.rb#L38).  `count` accepts a single argument. If you pass a hash to it you will eventually get an `ActiveRecord::StatementInvalid` exception.

On [4-1-stable](https://github.com/rails/rails/blob/4-1-stable/activerecord/lib/active_record/relation/calculations.rb#L30) and [4-2-stable](https://github.com/rails/rails/blob/4-2-stable/activerecord/lib/active_record/relation/calculations.rb#L38), however, when a hash is supplied as the only argument,  the effect is exactly the same as calling `count` without any arguments at all. [This being the cause](https://github.com/rails/rails/blob/4-2-stable/activerecord/lib/active_record/relation/calculations.rb#L41):

    column_name, options = nil, column_name if column_name.is_a?(Hash)

So, should I target a PR to 4-1 and/or 4-2 which raises an ArgumentError when a hash is passed as the single argument of `count`? Or at least a warning stating that anything provided in the hash is ignored?

**Comment by sgrif** [comment]
You'd need to detect whether deprecated finders is present since it won't override your argument error.

**Comment by rousisk** [comment]
Thanks for the input @sgrif. So you mean only raising an error if the deprecated finders gem is not present?

**Comment by sgrif** [comment]
Correct.

**Comment by rousisk** [comment]
Great, thanks!

**Comment by rafaelfranca** [comment]
Fixed by https://github.com/rails/rails/pull/20450. Thanks
