### ISSUE TITLE
Not installing RVN on ubuntu 12.04

### ISSUE THREAD

**Issue by dimplea999** [rails/rails#20435]
i am getting error 

Error running 'requirements_debian_libs_install gawk libreadline6-dev libssl-dev libyaml-dev libsqlite3-dev sqlite3 libgdbm-dev libncurses5-dev libtool bison libffi-dev',
showing last 15 lines of /home/dimplea/.rvm/log/1433417955_ruby-2.2.1/package_install_gawk_libreadline6-dev_libssl-dev_libyaml-dev_libsqlite3-dev_sqlite3_libgdbm-dev_libncurses5-dev_libtool_bison_libffi-dev.log
Building dependency tree...
Reading state information...
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 libsqlite3-dev : Depends: libsqlite3-0 (= 3.7.9-2ubuntu1) but 3.7.9-2ubuntu1.1 is to be installed
 libssl-dev : Depends: libssl1.0.0 (= 1.0.1-4ubuntu3) but 1.0.1-4ubuntu5.9 is to be installed
 sqlite3 : Depends: libsqlite3-0 (= 3.7.9-2ubuntu1) but 3.7.9-2ubuntu1.1 is to be installed
E: Unable to correct problems, you have held broken packages.
++ /scripts/functions/utility : __rvm_try_sudo()  381 > return 100
++ /scripts/functions/requirements/ubuntu : requirements_debian_libs_install()  36 > return 100
Requirements installation failed with status: 100.

i fired this command : 

\curl -sSL https://get.rvm.io | bash -s stable --ruby

**Comment by arunagw** [comment]
This is not a issue related to Rails at all. Please ask these questions to StackOverflow or proper channels.
