### ISSUE TITLE
Rail4) How to default return created_at.to_time.iso8601 in API with datetime

### ISSUE THREAD

**Issue by vfa-dunghn** [rails/rails#20433]
Hi guys
Can we config globally for any api return with ex: return create_at with automatically convert to 
value.to_time.iso8601,
Thanks !

**Comment by kaspth** [comment]
Please use the Ruby on Rails talk mailing list or StackOverflow for questions/help, where a wider community will be able to help you. We reserve the issues tracker for issues only :heart:
