### ISSUE TITLE
duration instrumenter fails with TypeError can't convert nil into an exact number

### ISSUE THREAD

**Issue by frobichaud** [rails/rails#20447]
We have the following Rack middleware that computes the total active_record duration for a request:

```
ActiveSupport::Notifications.subscribe('sql.active_record') do |*args|
  event = ActiveSupport::Notifications::Event.new(*args)
  env[:db_duration] += event.duration
end if defined?(ActiveRecord)
```

We randomly have the following error:

```
TypeError can't convert nil into an exact number
```

in 

```
gems/activesupport-4.2.1/lib/active_support/core_ext/time/calculations.rb:226
```

```
226:      minus_without_duration(other)
227:    end
228:  end
229:  alias_method :minus_without_duration, :-
```

It looks like the parameter other is nil

**Comment by senny** [comment]
@frobichaud can you post the full backtrace of the error? Also the `*args` of the events that trigger the issue would be a big help.

**Comment by Draiken** [comment]
Colleague of mine also had this error. Working on getting the backtrace with event args too.

**Comment by Draiken** [comment]
Here is the stacktrace I recovered: https://gist.github.com/Draiken/21e4a55c23b8831ad1f0
Unfortunately we didn't log the `args` from the event.

I've added a new rescue statement to recover them, if this happens again I'll probably be able to provide those.

**Comment by stephankaag** [comment]
Probably related to https://github.com/rails/rails/issues/12069
