### ISSUE TITLE
Columns with arrays of points are not working

### ISSUE THREAD

**Issue by daniel-rikowski** [rails/rails#20441]
It is not possible to have attributes of arrays of points, i.e. columns like `t.column :polygon, :point, array: true`. Assigning them leads to wrongly cast SQL values.

Instead of `{ (x,y), (x,y) }`,   `{ {x,y}, {x,y} }` is sent to the database (which is rejected by PostgreSQL)

This is because the array column type can process nested/multidimensional arrays, which is perfect for most sub types. But for arrays of points the lowest array level belongs to the points and should be handled by the point type and not the array type.

Executable test case: https://gist.github.com/daniel-rikowski/8579c2c591ec01814036

 
I've hacked together two monkey patches for Rails 4 and 5 which modify the array casting methods: For arrays of points the casting stops at the second lowest level and leaves the rest to the sub type. 

I'd put together a pull request, but I'm not sure this is the best solution. It feels wrong to have special handling in the array type for a specific sub type...

**Comment by rafaelfranca** [comment]
cc @sgrif

**Comment by sgrif** [comment]
Basically the long term fix is that we need to treat `string[]` as a different type than `string[][]`, but that's not an option at the moment... I think we can handle this case at least, though. I should have some time to work on it tomorrow. Agreed that we don't want to special case this too much.

**Comment by saurabhbhatia** [comment]
@daniel-rikowski I am using the following to store a polygon.

```
    add_column :locations, :polygon, :float, array: true, default: []
```
It casts the elements of array as the column datatype at the moment, during save.
```
[[151.274529, -33.566859], [151.342163, -33.579731]]
```

**Comment by daniel-rikowski** [comment]
@saurabhbhatia Yes of course, a multidimensional array would work, too, it wouldn't even require any changes in the Ruby code. But I want to use the native PostgreSQL point type, mainly because I'm already using single points at various places. It seems just natural to use them in arrays, too, instead of using a different column type.

@sgrif Perhaps in the long run we can support specifying the array length, something like this:

```ruby
t.integer :rgb, array: 3
t.integer :matrix_2x3, array: [2, 3]
```
But I don't know how helpful that actually will be, since PostgreSQL doesn't enforce array dimensions at the moment...

**Comment by sgrif** [comment]
That would be too large of a breaking change I'm afraid

**Comment by sgrif** [comment]
Right now I'm thinking that we could deprecate the current point type in Rails 5, and replace it with one that returns `Point` objects instead of `Array`s in Rails 5.1, since the attributes API allows us to have a proper deprecation cycle on this.

**Comment by daniel-rikowski** [comment]
:+1:  Sounds good!

**Comment by saurabhbhatia** [comment]
:+1: agreed @daniel-rikowski

**Comment by sgrif** [comment]
The old point type has been deprecated in 5.0, and you'll be able to use a new type which returns a struct instead at that point in time. Unfortunately this cannot be backported to 4.2.

**Comment by daniel-rikowski** [comment]
Well, for Rails 4 one could use either @saurabhbhatia's solution or my Rails 4 monkey patch.
