### ISSUE TITLE
AbsenceValidator should check if associated records are marked_for_destruction?

### ISSUE THREAD

**Issue by thomasfedb** [rails/rails#20449]
Currently `AbsenceValidator` simply checks if attributes are `present?`:

```ruby
class AbsenceValidator < EachValidator
  def validate_each(record, attr_name, value)
    record.errors.add(attr_name, :present, options) if value.present?
  end
end
```

However this can be problematic when using `mark_for_destruction` from `AutosaveAssociation`, which is used by the `:allow_destroy` option of `accepts_nested_attributes_for`. It's enabled for the association if not already enabled:

```ruby
def accepts_nested_attributes_for(*attr_names)
  # ...

  attr_names.each do |association_name|
    if reflection = _reflect_on_association(association_name)
      reflection.autosave = true
      
      # ...
    end
  end
end
```

For example, with the following models:

```ruby
class Person < ActiveRecord::Base
  # has_pets:boolean

  has_many :pets
  accepts_nested_attributes_for :pets, allow_destroy: true

  validates :pets, absence: {unless: :has_pets?}
end

class Pet  < ActiveRecord::Base
  # name:string
end
```

If we first create a person with a pet:

```ruby
person = Person.create(has_pets: true, pets_attributes: [{name: "Teddy"}]
```

Then we find that we're unable to unset `:has_pets` and destroy Teddy using the `:_destroy` attribute. We would expect the following to work:

```ruby
person.update_attributes(has_pets: false, pets_attributes: [{id: 1, _destroy: true}])
```

However it will fail with a validation error, as during validation the associated `Pet` is still present, although it has been `marked_for_destruction?`.

A validator that handles this particular case looks something like this:

```ruby
def validate_pets
  unless pets.select {|p| !p.marked_for_destruction? }.empty?
    errors.add(:pets, "must be empty")
  end
end
```

We should update `AbsenceValidator` to exhibit this same behaviour when handling associations with `autosave: true`.

**Comment by thomasfedb** [comment]
:sparkles:

**Comment by senny** [comment]
I've added a Active Record specific validator to account for `marked_for_destruction?`.

@thomasfedb thanks for reporting :yellow_heart:

**Comment by thomasfedb** [comment]
@senny How can I go about having this fixed for 4.2.x?

**Comment by senny** [comment]
You can put [this patch](https://github.com/rails/rails/blob/30c9aa7883b5363ce3f50aa010a4245a418bca29/activerecord/lib/active_record/validations/absence.rb) into your `config/initializers` and surround it with:

```ruby
if Rails.version < '5.0.0'
  # linked patch here
else
  raise "With Rails 5 this patch is no longer needed."
end
```

**Comment by thomasfedb** [comment]
Hey @senny, I'm well aware have to monkey patch Rails, but I wondered if it was worth submitting a patch for the 4.2 branch?

**Comment by senny** [comment]
I'd rather not backport this change. The current behavior has been around for a long time and we didn't get any bug report feedback until this one. It might very well be that some applications now rely on the old behavior. Patch level releases should be a breeze to upgrade so I'll keep this patch for `5.0`. Hope that makes sense.

**Comment by thomasfedb** [comment]
Yeah, that's understandable. Cheers.
