### ISSUE TITLE
ActiveRecord::Relation#merge unexpected behavior

### ISSUE THREAD

**Issue by kangkyu** [rails/rails#20458]
This is not a typical use case, but when I tried following
```
> Post.where(id: 1).merge(Post.where(id: 2))
=> #<ActiveRecord::Relation [#<Post id: 2, ...]> # array with Post.where(id: 2) object in it
```

Was this intended and not documented?

**Comment by todd** [comment]
This behavior seems correct to me - calling merge is overriding the `id` in the conditions Hash. It makes sense that it would only return `where(id: 2)`.

**Comment by sgrif** [comment]
This is the expected behavior. Think about `Hash#merge`. In the case of conflicting keys, the right side wins. The same is true here.
