### ISSUE TITLE
Can't use symbol on where query with enum

### ISSUE THREAD

**Issue by meinac** [rails/rails#20467]
Using symbol in where query creates wrong sql for enum attribute.
`Post.where(status: :active)` generates `SELECT "posts".* FROM "posts" WHERE "posts"."status" = ?  [["status", nil]]`
I've created a script for this problem. I've tested it with version `4.2.1`, `4.2-stable` and `master`. I can't reproduce the bug on `master` but `4.2.1`, `4.2-stable` have this bug.
Here is the script for reproduce the bug;
```ruby
begin
  require 'bundler/inline'
rescue LoadError => e
  $stderr.puts 'Bundler version 1.10 or later is required. Please update your Bundler'
  raise e
end

gemfile(true) do
  source 'https://rubygems.org'
  gem 'rails', github: 'rails/rails', branch: '4-2-stable'
  gem 'arel'
  gem 'sqlite3'
end

require 'active_record'
require 'minitest/autorun'
require 'logger'

# This connection will do for database-independent bug reports.
ActiveRecord::Base.establish_connection(adapter: 'sqlite3', database: ':memory:')
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :posts, force: true  do |t|
    t.integer :status
  end
end

class Post < ActiveRecord::Base
  enum status: [:active, :passive]
end

class BugTest < Minitest::Test
  def test_association_stuff
    post = Post.create(status: :active)
    posts = Post.where(status: :active)

    assert_equal 1, posts.length
    assert_equal post.id, posts.first.id
  end
end
```

I would love to work for this bug but as far as I know rails team accept pull requests for only master.

**Comment by kaspth** [comment]
iirc querying enums by symbol is only supported in master. c/d, @sgrif.

Unfortunately that means there's no bug here. Thanks for taking the time to make a detailed report :heart:

**Comment by voltechs** [comment]
For posterity, [this commit](https://github.com/rails/rails/commit/c51f9b61ce1e167f5f58f07441adcfa117694301) introduces the feature in Rails 5.0 🎉

(I'm sharing because there is so much to learn from code, and when people search (like I am) for things like this or want to build a similar feature, they can find themselves landing here! :D)
