### ISSUE TITLE
ActiveRecord fails to save empty Hash serialized field

### ISSUE THREAD

**Issue by joelpresence** [rails/rails#20478]
Thanks for all of your hard work on Rails!

Suppose I have the following:
```
# In app/models/branch_version.rb
# Two fields:
#    published_data is a text
#    branch_id is a string
class BranchVersion < ActiveRecord::Base
  serialize :published_data, Hash
end

# In db/migrate/somedate_create_branch_versions.rb
class CreateBranchVersions < ActiveRecord::Migration
  def change
    create_table :branch_versions do |t|
      t.string :branch_id, limit: 128, null: false
      t.text :published_data, null: false

      t.timestamps null: false
    end

    add_index :branch_versions, [:branch_id, :id]
  end
end
```

Now, if I do:
```
shell> rails console
rails console> branch_version = BranchVersion.create! branch_id: 'abc', published_data: Hash.new
Failure/Error: branch_version = BranchVersion.create! branch_id: 'abc', published_data: Hash.new
     ActiveRecord::StatementInvalid:
       PG::NotNullViolation: ERROR:  null value in column "published_data" violates not-null constraint
       DETAIL:  Failing row contains (1, abc, null, 2015-06-08 17:31:50.950348, 2015-06-08 17:31:50.950348).
       : INSERT INTO "branch_versions" ("branch_id", "created_at", "updated_at") VALUES ($1, $2, $3) RETURNING "id"

rails console> Failure/Error: branch_version = BranchVersion.create! branch_id: 'abc', published_data: {}
     ActiveRecord::StatementInvalid:
       PG::NotNullViolation: ERROR:  null value in column "published_data" violates not-null constraint
       DETAIL:  Failing row contains (1, abc, null, 2015-06-08 17:32:42.119459, 2015-06-08 17:32:42.119459).
       : INSERT INTO "branch_versions" ("branch_id", "created_at", "updated_at") VALUES ($1, $2, $3) RETURNING "id"
```

This is a bug in either ActiveRecord, the pg driver, or both.  It is perfectly valid to insert an empty Hash with no key-value pairs.  That is a legal Ruby Hash instance and it should be perfectly valid to insert this into the database.  Empty Hashes can be important stateful info for an app and Rails needs to support them.  It's not correct to say that we are inserting null here - something is broken in the serialization code.

It is also perfectly valid for me to use a non-null text column here because an empty Hash serializes to and from Yaml just fine:
```
rails console> {}.to_yaml
 => "--- {}\n" 

rails console> YAML.load({}.to_yaml)
 => {} 
```

It looks like the serialize code on ActiveRecord is being overzealous in optimizing away the empty Hash and that is a bug.  Empty hashes are valid and we need to store them.

I am using:
* Rails 4.2.1
* Ruby 2.2.2p95 (2015-04-13 revision 50295) [x86_64-darwin14]
* Postgresql 9.4.1
* OS X 10.10.3

I can reproduce this every time with 100% repeatability.

Please let me know if I can help and I would be happy to do so.

**Comment by sgrif** [comment]
This is the expected behavior. `serialize` must never return `nil` and so the default value is assumed to be `nil` for proper dirty tracking. I agree this is quirky, but it is not an issue worth a breaking change. You should remove your `NOT NULL` constraint, as Rails will properly handle treating the empty value as `nil` in all cases.

**Comment by dcrec1** [comment]
What if the fix doesn't break anything? Also, the behaviour of `serialize` is not being questioned, just the not sending of the value to the database.

**Comment by sgrif** [comment]
Changing the documented behavior of a method for this would be a breaking change.

**Comment by sgrif** [comment]
The value sent to the database is part of the behavior of `serialize`

**Comment by dcrec1** [comment]
Sorry, is this the documentation?

http://api.rubyonrails.org/classes/ActiveRecord/AttributeMethods/Serialization/ClassMethods.html#method-i-serialize

In case it this, maybe I'am misunderstanding the documentation, but I don't see how this current behaviour is documented.

**Comment by sgrif** [comment]
"If class_name is specified, the serialized object must be of that class on
assignment and retrieval." does cover this, but you're right, it could be a
lot clearer.

Keep in mind we are actively discouraging the use of `serialize` for new
apps.
http://edgeapi.rubyonrails.org/classes/ActiveRecord/AttributeMethods/Serialization/ClassMethods.html#method-i-serialize

That said, feel free to open a PR to improve the documentation.

**Comment by dcrec1** [comment]
@sgrif can you please re-evaluate? No behaviour is being broken and this seems like the expected behaviour.

**Comment by moritzschepp** [comment]
For @joelpresence's scenario, I have the problem that the check happens before persistence, and somehow just once, consider the following:

    b = BranchVersion.new
    p (b[:published_data] ||= {})["test"] = 12
    p b[:published_data]
    p (b[:published_data] ||= {})["test"] = 12
    p b[:published_data]

on my project and a few tests within the activerecord test suite, that outputs

    12
    {}
    12
    {"test"=>12}

Is that intended?
