### ISSUE TITLE
Memory leak in transactions / has_(one/many) and find_each

### ISSUE THREAD

**Issue by cconstantine** [rails/rails#20484]
There appears to be a memory leak when using find_each and save in a transaction with a model that has a has_one or has_many.

to repro ( rails 4.2.1 ):

Create a new rails app with a model and create a bunch of them:
``` ruby
rails new memory_leak
cd memory_leak
bundle
bundle exec rails generate model SomeModel
bundle exec rake db:migrate
bundle exec rails c
echo "ActiveRecord::Base.logger = nil;50000.times { SomeModel.create! }" | bundle exec rails c
exit
```

Add a has_one or has_many to SomeModel.  It doesn't need to reference anything that exists:
`has_one :derp`

Add the following lib/tasks/test.rake:
``` ruby
namespace :derp do
  task :the_thing => :environment do
    i = 0
    ActiveRecord::Base.transaction do
      SomeModel.find_each do | some_model |
        i += 1
        if i % 1000 == 0
          GC.start
          STDOUT.puts "SomeModel: #{ObjectSpace.each_object(SomeModel).count}"
        end
        some_model.save!
      end
    end

    thread.exit
  end
end

```

Run the task and watch the number of SomeModel instances grow well beyond the page size for find_each:
`bundle exec rake derp:the_thing`

Removing one of:
 - The `ActiveRecord::Base.transaction` 
 - The `has_one :derp`
 - the `some_model.save!`

Will remove the memory leak.

**Comment by sgrif** [comment]
This is the expected behavior. Transactions will keep a reference to objects which save within them in order to reset state in the case of a transaction rollback, and to perform `after_commit` callbacks.

**Comment by cconstantine** [comment]
I don't understand how this is expected behavior.  

 - I'm holding no references to those objects between calls to the block so I don't expect them to revert to their previous values.  
 - Only the presence of `has_one` and `has_many` create this behavior.  If the model is empty or has a `belongs_to` or uses any other ActiveRecord::Base feature doesn't create this leak.
 - It is preventing me from doing a batch job that updates the entire database at once.  

Would you be ok with me opening this again with the understanding that I'll try to attach a pull-request that fixes the issue?

**Comment by matthewd** [comment]
`has_*` associations internally use a rollback callback, to restore their own state. That callback is defined at the class level, merely because the association exists.

I won't reopen this, because it is indeed expected behaviour (ergo not a bug, per se)... but if you can find a way to avoid/reduce the circumstances under which we're obliged to do this, while maintaining the existing behaviours, I'm sure a PR would be very welcome.

Thanks! :yellow_heart:

**Comment by cconstantine** [comment]
Hmm, the `after_commit` hooks aren't really solvable I guess.  I think leaving this closed unless I can come up with a fix is the right answer.

Thanks :)

**Comment by skatenerd** [comment]
Hey folks,

I just stumbled across this really helpful discussion.

I'm wondering specifically why the `has_one` matters.  It seems like, according to @sgrif's explanation, the transaction should maintain references to `SomeModel` instances, as they are saved within the transaction, even if they don't have any associations.

Thanks!

**Comment by gabrieljoelc** [comment]
The [documentation](http://api.rubyonrails.org/classes/ActiveRecord/Batches.html#method-i-find_each) has this note for `find_each`:

> NOTE: By its nature, batch processing is subject to race conditions if other processes are modifying the database.

It makes me think that a `find_each` nested in transaction block will not rollback objects in previous batches if there are multiple batches. However, @sgrif 's [first comment](https://github.com/rails/rails/issues/20484#issuecomment-110203544) seems to confirm that transactions do maintain the normal behavior even with `find_each`.
