### ISSUE TITLE
deploy rollback after previous deploy failed caused asset_path to be in wrong format

### ISSUE THREAD

**Issue by drhenner** [rails/rails#20485]
I think I found a unicorn.

SYSTEM

```
    gem 'rails', '4.0.13'
    gem 'capistrano', '2.15.5'
```

STEPS

1 - I depoyed my app to production (no issues)
2 - I deployed to production but the deploy failed (specifically after new assets were created)
3 - Everything works great (the app stayed on the deploy in step 1)
4 - I deployed to production with a bug in production
5 - The deploy was SMALL so I did a `cap production deploy:rollback` (the rollback failed so we decided to live with the bug in production until the next day)
6 - Everything except the small bug was in production (or so we thought)
7 - 12 hours later some type of cache must have been busted.  (BANG asset_path method returned a path in the wrong format SEE BELOW )

Expected: 

```
    http://mycdnsubdomain.fictional-cdn.com/assets/smile-d0e099e021c95eb0de3615fd1d8c4d83.js
```

Received

```
    http://mycdnsubdomain.fictional-cdn.com/assets/smile.js
```

I understand this is an edge case yet this did cause Major SITE DOWN issues.  I'm guessing this is specific to the rails version given the # of times the `asset_path` method has been refactored. 

I'll be glad to test in rails 4.1 if my company upgrades any time soon.  (the goal is in 2 months)

**Comment by sgrif** [comment]
Are you able to provide a bare Rails app which can be used to reproduce the issue? We cannot do anything to help without some form of steps to reproduce.

**Comment by drhenner** [comment]
Let me try and reproduce on another app.  I won't be able to focus on this until the weekend.
