### ISSUE TITLE
Environment variables SMTP_USERNAME and SMTP_PASSWORD result in strange behavior in production mode

### ISSUE THREAD

**Issue by hkraji** [rails/rails#20488]
This is going to sound really strange but while using environment variables `SMTP_USERNAME` and `SMTP_PASSWORD` to set action mailer settinwg I was having problem authenticating with SES (was getting `535 Authentication Credentials Invalid` in `production` all was working ok in `development` environment. Here are action mailer settings:

    config.action_mailer.delivery_method = :smtp
    config.action_mailer.perform_deliveries = true
    config.action_mailer.default_url_options = { :host => 'localhost:3000' }
    config.action_mailer.smtp_settings = {
      address: ENV['SMTP_HOSTNAME'],
      port: ENV['SMTP_PORT'],
      enable_starttls_auto: true,
      user_name: ENV['SMTP_USERNAME'],
      password:  ENV['SMTP_PASSWORD'],
      :authentication => :plain
    }

All my efforts to print/log/write to file values of mentioned variables resulted in `xxxxxx` values for given variables. I was assuming that Rails was filtering out sensitive information as it does. But after changing prefixes `SMTP_` to `MAIL_` all started working as expected in `production` mode.

My assumption is that instead of real values smtp mailer was using `xxxxxxx` (filtered values) and that is why I was stuck with 535 error. I am really surprised with this bug, and would like to know what happened :)

**Comment by matthewd** [comment]
I would guess you have something else in your environment that's setting those environment variables, where someone has used "xxxxxx" to mean "fill this in later", rather than "this is a hidden secret".

**Comment by hkraji** [comment]
You are right, I did confirm that fact I still do not know who does it but in process of finding out. Makes sense now more that this being Rails bug. Thanks for help and I am closing this "issue" :)
