### ISSUE TITLE
Logger silence raises weird exception when called on built-in Logger class

### ISSUE THREAD

**Issue by bogdan** [rails/rails#20492]
Consider the following irb output:

```
$ irb
2.2.2 :001 > Logger.new(STDOUT).silence {}
NoMethodError: undefined method `silence' for #<Logger:0x007fe55d8b0ca0>
        from (irb):1
        from /Users/bogdan/.rvm/rubies/ruby-2.2.2/bin/irb:11:in `<main>'
2.2.2 :002 > require 'active_support'
 => true
2.2.2 :003 > require 'active_support/core_ext'
 => true
2.2.2 :004 > Logger.new(STDOUT).silence {}
ArgumentError: wrong number of arguments (0 for 1)
        from /Users/bogdan/.rvm/gems/ruby-2.2.2@talkable/gems/activesupport-4.1.10/lib/active_support/core_ext/kernel/reporting.rb:82:in `capture'
        from (irb):4
        from /Users/bogdan/.rvm/rubies/ruby-2.2.2/bin/irb:11:in `<main>'
2.2.2 :006 > Logger.new(StringIO.new).silence {}
ArgumentError: wrong number of arguments (0 for 1)
        from /Users/bogdan/.rvm/gems/ruby-2.2.2@talkable/gems/activesupport-4.1.10/lib/active_support/core_ext/kernel/reporting.rb:82:in `capture'
        from (irb):6
        from /Users/bogdan/.rvm/rubies/ruby-2.2.2/bin/irb:11:in `<main>'

```

Rails 4.1.10

**Comment by rafaelfranca** [comment]
You are calling [`Kernel#silence`](https://github.com/rails/rails/blob/4-1-stable/activesupport/lib/active_support/core_ext/kernel/reporting.rb#L98) instead of `LoggerSilencer#silence`, and it requires an argument.

**Comment by bogdan** [comment]
If I am calling `Kernel#silence`, why do I get `NoMethodError: undefined method `silence' for #<Logger:0x007fe55d8b0ca0>` when AS is not loaded?

**Comment by rafaelfranca** [comment]
Because `::Logger` don't have `silence` method. It is defined only in `ActiveSupport::Logger`.

**Comment by bogdan** [comment]
Ah! I see thanks for you time.

It still drives me crazy:
Now in order to do what I want I need the following code:

def silence_logger(logger)
  if logger && logger.respond_to?(:silence) && logger.method(:silence).arity == 0
     logger.silence {yield }
 else
    yield
  end
end
```

That's super crazy. Maybe having `silence` as an alias for `capture` is bad idea.

**Comment by rafaelfranca** [comment]
Yeah, we removed `silence` and `capture` in Rails master, so I think it was deprecated in 4.2
