### ISSUE TITLE
Migration of trigram search

### ISSUE THREAD

**Issue by desofto** [rails/rails#20495]
I have a migration:

    class AddGinIndexToContacts < ActiveRecord::Migration
      def up
        execute("CREATE INDEX contacts_search_idx ON contacts USING gin (first_name gin_trgm_ops, last_name gin_trgm_ops, name gin_trgm_ops)")
      end

      def down
        execute("DROP INDEX contacts_search_idx")
      end
    end

It generates this code in `schema.rb`:

    add_index "contacts", ["first_name", "last_name", "name"], name: "contacts_search_idx", using: :gin

and later, when I execute `rake db:schema:load` it generates wrong sql:

    CREATE  INDEX  "contacts_search_idx" ON "contacts" USING gin ("first_name", "last_name", "name")

Firstly, it says:

> ERROR:  data type character varying has no default operator class for
> access method "gin"

Secondly, there is lost `gin_trgm_ops`.

It works fine if you use `structure.sql`, but it does not work with `schema.rb`

`Rails 4.2`

Discussion on stackoverflow: http://stackoverflow.com/questions/29098712/migration-of-trigram-search-in-rails

**Comment by rafaelfranca** [comment]
Thank you for the report. schema.rb don't work for all the database specific features. If you are using `execute` in a migration in very likely that schema.rb will not work for you.

**Comment by desofto** [comment]
But it does not work even in this way:

```ruby
add_index "contacts", ["first_name", "last_name", "name"], name: "contacts_search_idx", using: :gin, order: {first_name: :gin_trgm_ops, last_name: :gin_trgm_ops, name: :gin_trgm_ops}
```
It looses `gin_trgm_ops`

**Comment by matthewd** [comment]
@desofto that's a hack; `gin_trgm_ops` is neither `asc` nor `desc`, and is thus clearly not an order.

You may be interested in #19090 -- but as you have found, the current solution (and the more general, "Rails doesn't know about this DB specific feature", solution) is to use `structure.sql` instead.
