### ISSUE TITLE
ActiveRecord::Base.connection.exec_query ignores binds argument

### ISSUE THREAD

**Issue by ivanoblomov** [rails/rails#20498]
Because .exec_query just wraps .execute, the binds argument is completely ignored...

https://github.com/rails/rails/blob/37e5770fd3db04f3206075d736fc14161dd04530/activerecord/lib/active_record/connection_adapters/mysql2_adapter.rb#L234

This makes it impossible to create parametric queries.

**Comment by rafaelfranca** [comment]
Yes. MySQL2 adapter don't works with binds. But mysql adapter does https://github.com/rails/rails/blob/37e5770fd3db04f3206075d736fc14161dd04530/activerecord/lib/active_record/connection_adapters/mysql_adapter.rb#L253
