### ISSUE TITLE
Type cast milliseconds in DateTime ActiveRecord attribute

### ISSUE THREAD

**Issue by ka8725** [rails/rails#20503]
I suppose to add typecasting milliseconds to time for date time attributes in ActiveRecord:

Currently:

```ruby
model.start_at = '1434326698123'
model.start_at # => nil
```

With the fix:

```ruby
module MillisecondsTypeCase
  private

  def cast_value(string)
    return string unless string.is_a?(::String)
    if string =~ /\d{13}/ # milliseconds
      ::Time.strptime(string, '%Q')
    else
      super
    end
  end
end

ActiveRecord::Type::DateTime.prepend(MillisecondsTypeCase)

model.start_at = '1434326698123'
model.start _at # => 2015-06-15 03:04:58 +0300
```

**Comment by rafaelfranca** [comment]
Thank you for the issue. I don't think this should be added in the framework by default. If you want to use it you can use the attributes API to use your defined type but you can also Parse the time object before sending through Active Record.
