### ISSUE TITLE
Unscope Joins

### ISSUE THREAD

**Issue by Vanuan** [rails/rails#20506]
Currently, `unscope` supports only `where` option: https://github.com/rails/rails/blob/0ef7e73f0af752002c6150bd1cf29586d8bd21c9/activerecord/lib/active_record/relation/query_methods.rb#L398

I want to be able to unscope joins too.

Here's what I did:

```
module UnscopeJoins
  extend ActiveSupport::Concern

  def unscope_joins(joins_string)
    joins_values.reject! {|val| val == joins_string}
    self
  end
end

ActiveRecord::Relation.send :include, UnscopeJoins
```

Usage:

```
scope :without_joins, -> { unscope_joins("JOIN table on table2.id = table1.table2_id") }
```

**Comment by sgrif** [comment]
You can remove all joins by doing `unscope(:joins)`. Removing individual joins by a SQL string is not something we'd currently be interested in adding. In the future, please direct feature requests to the [rails core mailing list](https://groups.google.com/forum/#!forum/rubyonrails-core), as we reserve the issues tracker for bugs only.
