### ISSUE TITLE
Buggy Timezone from offset

### ISSUE THREAD

**Issue by brauliobo** [rails/rails#20504]
Detected on this case, there might be others
```
2.1.5 :001 > Time.zone = ActiveSupport::TimeZone[-4]
T => #<ActiveSupport::TimeZone:0x00000005b01b20 @name="Atlantic Time (Canada)", @utc_offset=nil, @tzinfo=#<TZInfo::TimezoneProxy: America/Halifax>, @current_period=#<TZInfo::TimezonePeriod: #<TZInfo::TimezoneTransitionDefinition: #<TZInfo::TimeOrDateTime: 1425794400>,#<TZInfo::TimezoneOffset: -14400,3600,ADT>>,#<TZInfo::TimezoneTransitionDefinition: #<TZInfo::TimeOrDateTime: 1446354000>,#<TZInfo::TimezoneOffset: -14400,0,AST>>>> 
2.1.5 :002 > Time.zone.now
 => Wed, 10 Jun 2015 11:35:35 ADT -03:00 
```
Tested on Rails 3.2.21 and 4.2.0

**Comment by brauliobo** [comment]
The problem is that it is finding a timezone using DST. How to disable DST or to strictly use offsets?

**Comment by brauliobo** [comment]
Works with `Time.zone = 'Etc/GMT+4'`, maybe `ActiveSupport::TimeZone[]` should use something like this.

**Comment by al2o3cr** [comment]
The hour offset of Atlantic Time *is* -4, it just happens to be DST right now. `ActiveSupport::TimeZone#[]` seems to be satisfying its documentation.

If you're looking to search for a timezone by the *current* offset from UTC, you may want a similar algorithm to `[]` but comparing `utc_total_offset` for the current time. For instance:
```ruby
ActiveSupport::TimeZone[-4].period_for_local(Time.now).utc_total_offset # => -10800, since ADT is -3:00
```

**Comment by matthewd** [comment]
See also #15209 / #19279.

We can't internally adopt the `Etc/UTC+N` solution: firstly, because I believe we try to use the OS's TZ data, so can't rely on a particular zone name existing. And secondly, because those only exist for integer offsets -- we'd be deceptively accurate for the most common TZs, while having to fall back to a lesser guess otherwise.

**Comment by brauliobo** [comment]
@matthewd It is quite strange that for a given offset, which is used by many different cities and countries near the meridian, that the API should give the most common TZ. That would privilege developed countries' TZ :(
Also the `Etc/UTC+N` and `Etc/GMT+N` is part of the OS's TZ.

So still I can't understand why from a given offset the API should arbitrarily choose a timezone from tens of timezones that match the offset.

**Comment by matthewd** [comment]
> It is quite strange that [..] the API should give the most common TZ.

That's just luck. Or maybe a property of the order the TZs are defined by the OS. We certainly make no effort to favour any particular TZ for a given offset. 

> Besides the Etc/UTC+N and Etc/GMT+N is part of the OS's TZ.

Maybe on your OS. (To be clear: I believe you. They're defined by mine too. But not all.)

> So still I can't understand why from a given offset the API should arbitrarily choose a timezone from tens of timezones that match the offset.

I agree that's a silly thing for it to do... but that's what it's being asked for, so it doesn't have much choice. There is, by definition, no "correct" TZ for a given UTC offset. #19279 is attempting to improve our guess, but ultimately, if you intend to manipulate the resulting timestamp, you're gonna have a bad time (no pun intended... but that too).

... unless you happen to be working in a non-DST-observing region. But then, if you're prepared to force that assumption upon your application, you clearly have a specific location in mind, and you might as well just give it the actual TZ.
