### ISSUE TITLE
Fragment Caching and content_for

### ISSUE THREAD

**Issue by davydotcom** [rails/rails#20513]
It would be great if a cache block could be wrapped around an iterative generation of content_for blocks. I think this is totally feasible as long as a cached content encoding groups these into blocks during the fragment cache. Another thought is if an action is known to fetch 4 cache fragments on every request, can a prefix or distinguishing marker be placed on the fragment such that a prefetch can be performed from a remote cache store in a wildcard style. Instead of incurring overhead for for calls to memcache or redis, you get all your data back in one go

**Comment by claudiob** [comment]
Hello @davydotcom! 

GitHub issues should be reserved for issues like bugs, bug fixes, whereas feature requests can be suggested and better discussed in the [Ruby on Rails – Core Group](https://groups.google.com/forum/#!forum/rubyonrails-core).

Thanks! :ribbon:

**Comment by kaspth** [comment]
Closing for the reason given by @claudiob. Good luck, @davydotcom :smile:
