### ISSUE TITLE
Connect to a database based on HTTP header value

### ISSUE THREAD

**Issue by franckt** [rails/rails#20524]
I'm currenlty work on a project with multiple openstreetmap postgresql databases installed
and one api instance, i added a X-Venue header for requests to route to a specified correctly installed database.

i updated ApplicationController to connect to the specified database, it works but when i connect to a non existing database, it returns database not found even if the database is correct on future calls

Here is the code : https://gist.github.com/franckt/7c6a8cf5f0d7deffb9be

i'm not sure how rails works with pgsql, when the first connection occurs, and if establish_connection() is the good way, it seems that some connection polling somewhere keeps latest bad connection.

If i restart the server (bundle exec rails server) it works again

Any help on that ?

(original issue was posted on https://github.com/openstreetmap/openstreetmap-website/issues/980 but it's a rails issue in fact)

**Comment by matthewd** [comment]
Please use the mailing list or StackOverflow for questions/help, where a wider community will be able to help you. We reserve the issues tracker for issues only.
