### ISSUE TITLE
Asset pipeline doesn't precompile css and javascript files with index name

### ISSUE THREAD

**Issue by hlmerscher** [rails/rails#20525]
rake assets:precompile isn't working with css and javascript files when they have name index.css / index.js.

```bash
$ RAILS_ENV=production rake assets:precompile
I, [2015-06-11T19:13:48.218279 #15772]  INFO -- : Writing /home/hercules/Crafters/bug-asset-pipeline/public/assets/application-1e31a2a1f5906db77c76acfa995edbe974f161209935fca5404515e00b57a3b3.js
I, [2015-06-11T19:13:48.231635 #15772]  INFO -- : Writing /home/hercules/Crafters/bug-asset-pipeline/public/assets/home/test-5c51c7a87588f9c19716ea727a6ae79778cdfe8d19a4b4711136c04984602ef4.js
I, [2015-06-11T19:13:48.240721 #15772]  INFO -- : Writing /home/hercules/Crafters/bug-asset-pipeline/public/assets/home/xpto-28a9ed29d5a4c0dca7bf410c679aa76b7381104eaba0cdf70e4e963f06f278d9.js
I, [2015-06-11T19:13:48.250769 #15772]  INFO -- : Writing /home/hercules/Crafters/bug-asset-pipeline/public/assets/application-a705b7f5faa767b1f279024bc97eb0bc7f4519bcbc89a44fcc566f27a4477a6c.css
I, [2015-06-11T19:13:48.258987 #15772]  INFO -- : Writing /home/hercules/Crafters/bug-asset-pipeline/public/assets/home/test-c2a554223f35a3559a51576e270c9b898c37f86a0c2ad51d731d9efe80f37ce6.css
I, [2015-06-11T19:13:48.266911 #15772]  INFO -- : Writing /home/hercules/Crafters/bug-asset-pipeline/public/assets/home/xpto-c509b005a1ab844bc4ab5c0041a309c678488c33b3b1669d5b5742585be82a78.css
```

Take a look at this example app:

https://github.com/hlmerscher/bug-asset-pipeline

**Comment by rafaelfranca** [comment]
Thank you for the issue. This is something that needs to be improved but it happens because sprockets has a feature that detects `index.(js|css)` inside the folders and use it as aliases. So `home/index.js` is aliased as `home.js` so if you put `home.js` in your precompile list I think it will be compiled. Could you try that?

**Comment by hlmerscher** [comment]
That's weird, but it worked. :smile:

**Comment by rafaelfranca** [comment]
Yeah, this is how it works. Any index file inside a folder will be precompiled as the `folder_name.js`. Right now we can't change this behavior but it is something that I want to change in the future.

**Comment by hlmerscher** [comment]
Why it started to happens now? I mean, it wasn't a problem until now. 6 weeks ago it was working just fine.

I checked my Gemfile.lock and then I saw something. Before I was using sprockets 2.12.3, so I updated the gems and the new sprockets in use is 3.0.1.
