### ISSUE TITLE
Issue running AutomaticCollectionCacheTest tests in a specific order

### ISSUE THREAD

**Issue by repinel** [rails/rails#20535]
It appeared in [this build](https://travis-ci.org/rails/rails/jobs/66489622) for the commit 0965be14e22c4d1fd6befda4fd3efb942e0701ca using `--seed 49713`. Even with that seed, it does not always happen.

So far, it seems that [AutomaticCollectionCacheTest#test_explicit_render_call_with_options](https://github.com/rails/rails/blob/8beb328befa53d74fe9c7942ddb188563bd4de33/actionpack/test/controller/caching_test.rb#L400) is being called before [AutomaticCollectionCacheTest#test_caching_works_with_beginning_comment](https://github.com/rails/rails/blob/8beb328befa53d74fe9c7942ddb188563bd4de33/actionpack/test/controller/caching_test.rb#L406) and is adding the partial `customers/customer` to the cache. That prevents the action `index_with_comment` to actually render `customers/commented_customer` and provides it the cached output, since both partials do generate the same output and have the same `collection`.

I thought that ActiveSupport::Cache::MemoryStore was having issues keeping it thread-safe, but I believe is working as designed if you consider that the tests are running from the same process and thread.

@rafaelfranca any thought on this?

**Comment by kaspth** [comment]
Hey, thanks for looking into this :smile:

I could see your argument if the problem happened every time, but not when the test fails some of the time. Besides the cache keys will have a digest at the end of the templates contents. Since the `customer` and `commented_customer` won't generate the same digest, the keys won't clash.

Thought you're right, we need some second eyes on this. @rafaelfranca @matthewd, do you have any suggestions?

**Comment by matthewd** [comment]
Most of the test classes in that file seem to be (quite reasonably) [setting a per-run cache store in `setup`](https://github.com/rails/rails/blob/8beb328befa53d74fe9c7942ddb188563bd4de33/actionpack/test/controller/caching_test.rb#L50-L53). It sounds like this class should follow that precedent.

**Comment by matthewd** [comment]
To be clear: that should fix any current test flakiness... but isn't necessarily a statement either way on #20538. I think it may well be useful to have a test like that, but I haven't formed an opinion on what it should be asserting.

**Comment by kaspth** [comment]
Heh, some jerk removed that when he was "fixing" the caching tests in #20284: https://github.com/rails/rails/pull/20284/files#diff-4efdae80219114e3e90f64fbc7a8851dL380 :sweat_smile:

**Comment by repinel** [comment]
What a moment :sweat_smile:

**Comment by kaspth** [comment]
Got it: https://github.com/rails/rails/pull/20573

**Comment by kaspth** [comment]
Thanks @repinel and @matthewd! I'll try not to break Rails randomly in the future :smile:

**Comment by repinel** [comment]
Thanks!

Should #20538 be kept around because of the test? Do you see as valid scenario?

**Comment by kaspth** [comment]
@repinel yes, we should. I've commented on that now :smile:

**Comment by repinel** [comment]
The ci [failed](https://travis-ci.org/rails/rails/builds/66958582) again a few hours ago on master and it seems to related. Everything is green now. It does depend on the run, not only the seed.

This should do the trick `until false ; do TESTOPTS="--seed=4398" rake test ; test $? -ne 0 && break ; done`.

Reopen this issue until #20538 kicks in?

**Comment by repinel** [comment]
Based on a new [failed build](https://travis-ci.org/rails/rails/jobs/69252346), it seems that the the `collection_cache` being used in [CollectionCaching](https://github.com/rails/rails/blob/626b10ef1f34fbc5595107e1cdbd3f839a46d96a/actionview/lib/action_view/renderer/partial_renderer/collection_caching.rb#L18) is no the one from [AutomaticCollectionCacheTest](https://github.com/rails/rails/blob/626b10ef1f34fbc5595107e1cdbd3f839a46d96a/actionpack/test/controller/caching_test.rb#L383). At least the `object_id` didn't match.

@kaspth What do you think? Reopen?
