### ISSUE TITLE
Builder views cannot readily use some ActionView::Helper methods

### ISSUE THREAD

**Issue by jashank** [rails/rails#20530]
Creating views using Builder templates leads to interesting issues when using some ActionView::Helper methods.

### Background ###

To use ActionView::Helpers in a Builder, we cannot use it as readily as we would if we were using ERB.  Things like `<%= csrf_meta_tags %>` cannot be simply dropped into a Builder template, but must be appended using the left-shift operator:

```{.ruby}
xml << csrf_meta_tags
```

Worse, we have things like

```{.ruby}
xml << yield
```

### The Problem ###

Any ActionView::Helper which assumes they have full control of the output of the contents of their block, which would be the case with an ERB template is wrong.  This is especially true for things that think they are responsible for grouping, and so one cannot nest Builder calls into (e.g.) a `form_for` block.

Concretely, this:

```{.ruby}
xml.main class: "container" do
  xml << form_for(:article) do |f|
    xml.p "I'm in a form!"
  end
end
```

... generates this:

```{.xml}
<main class="container">
  <p>I'm in a form!</p>
  <form action="/articles/new" accept-charset="UTF-8" method="post">
    <input name="utf8" type="hidden" value="&#x2713;" />
    <input type="hidden" name="authenticity_token" value="..." />
  </form>
</main>
```

This strikes me as a bug, and one I cannot readily monkey-patch away.

Is this supported, or should I go and submit a PR against the documentation saying, essentially, "don't do this, it won't work"?

**Comment by rafaelfranca** [comment]
I'd say that we don't have any reason to not properly support these helpers outside ERB/Haml and it is worth to investigate ways to fixing it.

But before digging on it, could you try:

```
xml.main class: "container" do
  xml << form_for(:article) do |f|
    capture xml.p "I'm in a form!"
  end
end
```

**Comment by jashank** [comment]
That exact block gives `LocalJumpError - no block given (yield)`; wrapping the `xml.p` in a block yields unexpected and surprising results:

```{.xml}

<main class="container">
  <p>I'm in a form!</p>
<form action="/articles/new" accept-charset="UTF-8" method="post"><input name="utf8" type="hidden" value="&#x2713;" /><input type="hidden" name="authenticity_token" value="..." />&lt;main class=&quot;container&quot;&gt;
  &lt;p&gt;I&#39;m in a form!&lt;/p&gt;
</form></main>
```

That renders as the literal

> I'm in a form!
>
> &lt;main class="container"&gt; &lt;p&gt;I'm in a form!&lt;/p&gt;

No, I don't understand it, either.
