### ISSUE TITLE
Rails 4.2 call save in `getter` method causes "instance variable @cached_changed_attributes not defined" bug.

### ISSUE THREAD

**Issue by raven-chen** [rails/rails#20531]
If I overwrite a getter method and call save inside it like
```
  def some_attribute
     update_attribute :some_attribute, "value"
  end
```
`cache_changed_attributes` will raise **instance variable @cached_changed_attributes not defined** exception. because it will be called twice, the one inside yield removed @cached_changed_attributes so the second time, remove_instance_variable(:@cached_changed_attributes) can not find @cached_changed_attributes.

I've created test case here https://gist.github.com/raven-chen/fc5669ecda5f8b62e2fa

the change that bring this bug made here https://github.com/rails/rails/commit/9384fa43c

**Comment by matthewd** [comment]
@raven-chen independent of the error, that sounds like you're breaking the "known that the computed value cannot change" assumption that allows us to cache in the first place. @sgrif?

**Comment by sgrif** [comment]
I mean it should go without saying that having side effects in a getter is a bad idea. Still, this is technically valid so we should handle it.

**Comment by sgrif** [comment]
Backported in https://github.com/rails/rails/commit/02e6bccbeb108ae0d8d92c84c6fc0b3330af360f

**Comment by raven-chen** [comment]
Thanks :+1:
