### ISSUE TITLE
NameError instead of AssociationTypeMismatch when passing the wrong class of object to namespaced model associations

### ISSUE THREAD

**Issue by danfinnie** [rails/rails#20541]
Suppose you have a Car model and a Wheel model, where Wheel belongs_to Car and Car has_many Wheels.  If you attempt to do `Wheel.new(car: "hi")`, you receive an error of type ActiveRecord::AssociationTypeMismatch because `"hi"`is not of class Car.  This works if Wheel and Car are at the root namespace.  If Wheel and Car are in a namespace, however, you receive a confusing `NameError: uninitialized constant Car`.  I'm guessing that this is thrown inside of Rails while trying to do the type checking or throw the correct error.

Here's a test case.  The relationships and assertions are the same, the only difference is that one is namespaced in the `Namespace` module and one is not.  I had to use 2 differently named sets of models so that the error for `Namespace::Apple` didn't accidentally reference `::Apple`.

```ruby
begin
  require 'bundler/inline'
rescue LoadError => e
  $stderr.puts 'Bundler version 1.10 or later is required. Please update your Bundler'
  raise e
end

gemfile(true) do
  source 'https://rubygems.org'
  # Activate the gem you are reporting the issue against.
  gem 'activerecord', '4.2.1'
  gem 'sqlite3'
end

require 'active_record'
require 'minitest/autorun'
require 'logger'

# Ensure backward compatibility with Minitest 4
Minitest::Test = MiniTest::Unit::TestCase unless defined?(Minitest::Test)

# This connection will do for database-independent bug reports.
ActiveRecord::Base.establish_connection(adapter: 'sqlite3', database: ':memory:')
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table "cars", force: :cascade do |t|
  end

  create_table "wheels", force: :cascade do |t|
    t.integer  "car_id"
  end

  create_table "namespace_apples", force: :cascade do |t|
    t.integer  "teacher_id"
  end

  create_table "namespace_teachers", force: :cascade do |t|
  end
end

class Wheel < ActiveRecord::Base
  belongs_to :car
end

class Car < ActiveRecord::Base
  has_many :wheels
end

module Namespace
  def self.table_name_prefix
    'namespace_'
  end
end

class Namespace::Teacher < ActiveRecord::Base
  has_many :apples
end

class Namespace::Apple < ActiveRecord::Base
  belongs_to :teacher
end

class BugTest < Minitest::Test
  def test_association_stuff
    assert_raises(ActiveRecord::AssociationTypeMismatch) { Namespace::Apple.new(teacher: "hello") }
    assert_raises(ActiveRecord::AssociationTypeMismatch) { Wheel.new(car: "hello") }
  end
end
```

**Comment by danfinnie** [comment]
@mkenyon @styeung

**Comment by dcrec1** [comment]
In case this is a bug, I've submitted a patch.

**Comment by danfinnie** [comment]
@dcrec1 Thanks for taking a peek.  Does your code give the class name in the association type mismatch error?  With the `rescue false` I'm think it won't but I want to fork your test to add the class to the error message test and see.

I was playing around in pry and found that this returned the type of the association:

```ruby
Namespace::Apple.new.association(:teacher).reflection.klass
```

I think it might be better to use that for the is_a? test that you found instead of constantizing the class name.

**Comment by danfinnie** [comment]
I took another peek at this.  I see why the `rescue false` will still produce the class name in the error now.  It still seems suboptimal to have to rescue.

Taking another peek at the or statement [here](https://github.com/rails/rails/blob/3e36db4406beea32772b1db1e9a16cc1e8aea14c/activerecord/lib/active_record/associations/association.rb#L213-L218), at first glance it seems like the first clause is the normal case and the second clause is used if the association has a `class_name` attribute.  However, `reflection.klass` seems to return the correct class even if there's a `class_name` attribute.  Do you know what the second clause of the or statement is for?  Can it be dropped or conditionally evaluated?

**Comment by dcrec1** [comment]
@danfinnie it gives the class name, but not namespaced, for example `Teacher(#53453) expected, ...` instead of `Namespace::Teacher(#53453) expected, ...`.

Removing the second clause breaks this tests:

[test_saving_a_new_record_belonging_to_invalid_parent_with_touch_should_not_raise_exception](https://github.com/rails/rails/blob/3e36db4406beea32772b1db1e9a16cc1e8aea14c/activerecord/test/cases/timestamp_test.rb#L218)
[test_has_one_with_reload](https://github.com/rails/rails/blob/3e36db4406beea32772b1db1e9a16cc1e8aea14c/activerecord/test/cases/reload_models_test.rb#L8)

**Comment by danfinnie** [comment]
@alicia

**Comment by senny** [comment]
@danfinnie I merged a fix and backported it to `4-2-stable`. Thanks for reporting.
