### ISSUE TITLE
STDOUT logger causes an error when being silenced

### ISSUE THREAD

**Issue by ZeroMax-dev** [rails/rails#20555]
When you use `Logger.new(STDOUT)` as the logger in Rails, ActiveSupport throws an error when using `ActiveRecord::Base.logger.silence`:

	ArgumentError: wrong number of arguments (0 for 1)
			from /usr/local/lib/ruby/gems/2.2.0/gems/activesupport-4.2.0/lib/active_support/core_ext/kernel/reporting.rb:88:in `capture'
			from lib/test.rb:2:in `<top (required)>'
			from /usr/local/lib/ruby/gems/2.2.0/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:268:in `load'
			from /usr/local/lib/ruby/gems/2.2.0/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:268:in `block in load'
			from /usr/local/lib/ruby/gems/2.2.0/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:240:in `load_dependency'
			from /usr/local/lib/ruby/gems/2.2.0/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:268:in `load'
			from (irb):3
			from /usr/local/lib/ruby/gems/2.2.0/gems/railties-4.2.0/lib/rails/commands/console.rb:110:in `start'
			from /usr/local/lib/ruby/gems/2.2.0/gems/railties-4.2.0/lib/rails/commands/console.rb:9:in `start'
			from /usr/local/lib/ruby/gems/2.2.0/gems/railties-4.2.0/lib/rails/commands/commands_tasks.rb:68:in `console'
			from /usr/local/lib/ruby/gems/2.2.0/gems/railties-4.2.0/lib/rails/commands/commands_tasks.rb:39:in `run_command!'
			from /usr/local/lib/ruby/gems/2.2.0/gems/railties-4.2.0/lib/rails/commands.rb:17:in `<top (required)>'
			from bin/rails:4:in `require'
			from bin/rails:4:in `<main>'

Steps to reproduce:

Make a new app:

	rails new TestApp

Set the logger in `application.rb`

	module Testapp
	  class Application < Rails::Application

		# Standard logger
		config.logger = Logger.new(STDOUT)
		
	  end
	end

(Create a model to use in the test, e.g. `rails g model Entity` and migrate)
Create a testfile, e.g. in the lib directory.

	# lib/test.rb
	ActiveRecord::Base.logger.silence do # Causes an error
	  A = Entity.all
	end
	
Load the testfile in the `rails console`:

	load 'lib/test.rb'

**Comment by simon2k** [comment]
Hi,

The `#silence` method is an alias of `#capture`, and it needs one parameter, as you got in the error message. You could specify param for the method, e.g. `:stdout` or use for instance `quietly`, both methods are removed now on master.
