### ISSUE TITLE
Why ActiveRecord readonly method unnecessarily generating the DIRTY methods

### ISSUE THREAD

**Issue by senthil88** [rails/rails#20565]
Consider the 'User' table consists of 40 columns.

UserController#Index
@users = User.readonly.all

It's just for readonly purpose and no need track the changes. But ActiveRecord unnecessarily generating the DIRTY suffix methods. In my case, for each ActiveRecord object 40(columns) * 4 (suffix) = 160 methods.

Is there any way to disable the Dirty module methods ['_changed?', '_change', '_will_change!', '_was']?

**Comment by rafaelfranca** [comment]
No. There is no ways to disable the Dirty module methods and I don't think it is worth to micro optimising this by not defining some methods unless it is proven that these methods make the code considerably slower or more memory consuming.
