### ISSUE TITLE
regression: callback symbol conditions can't refer to instance variables in 4.2

### ISSUE THREAD

**Issue by bughit** [rails/rails#20568]
## 4.0
a symbol filter was just embedded in a string and therefore could refer to instance vars (among other things)
```ruby
      def _compile_filter(filter)
        case filter
        when Array
          filter.map {|f| _compile_filter(f)}
        when Symbol
          filter
```
## 4.2
only methods in 4.2
```ruby
      def make_lambda(filter)
        case filter
        when Symbol
          lambda { |target, _, &blk| target.send filter, &blk }
```

**Comment by simon2k** [comment]
Hi, could you create a sample app for reproducing the issue? :) https://github.com/rails/rails/blob/master/guides/bug_report_templates/active_record_gem.rb

**Comment by bughit** [comment]
First, do you consider this a bug?  It may not have clear from the description:
the following works in 4.0 but not in 4.2
```ruby
after_destroy :do_something, if: :@need_to_do_something
```

**Comment by simon2k** [comment]
Right, thanks for giving example. It's correct behaviour, here's the reason behind: 

https://github.com/rails/rails/blob/4-2-stable/activesupport/lib/active_support/callbacks.rb#L420 - a symbol should be a method call.

**Comment by bughit** [comment]
but considering symbols worked also for ivars in 4.0, why not preserve this?

**Comment by simon2k** [comment]
It was removed in this commit:
https://github.com/rails/rails/commit/6189e2714b730d4ae0da11884b8082cbee0fb44c One way to use variable in the condition, is to pass it as a string: `'@need_to_do_something'` - it'll be evaluated. / @rafaelfranca should we handle :@var in filters for callbacks? Or we'll just stick to strings? :)

**Comment by bughit** [comment]
of course there's a way to refer to ivars (string or proc), but the point is :@ivar worked for a long time so why not keep it working.

**Comment by chancancode** [comment]
It is not a bug; as @simon2k pointed out, the documented behavior is that symbols means ["a method to call"](https://github.com/rails/rails/blob/4-0-stable/activesupport/lib/active_support/callbacks.rb#L244), and that was true even for 4.0. Arguably, the 4.0 behavior is incorrect, and it was merely a side-effect of the implementation details. As there are better alternatives to accomplish what you want to do, I suggest that you just stick to one of the documented ways to do it (a string or a proc, or make an `attr_reader` for the ivar).
