### ISSUE TITLE
Provide "staging" environment by default. Maybe?

### ISSUE THREAD

**Issue by hubertlepicki** [rails/rails#20576]
Something I'd like to suggest, because I think it makes sense, is to include "staging" environment by default along "development", "production" and "test". My reasoning is:

1. I have been adding 'staging.rb' to every single project I create, to add this environment
2. It is a good practice not to deploy your code straight away to production
3. Not having 'staging' environment might actually suggest people this is the way forward

I do understand that a lot of people probably do not have 'staging' environment even if they have staging/testing servers set up. It is my feeling, however, that this is the right approach, I wonder what other people think about it?

**Comment by simon2k** [comment]
Hi, from my experience it varies. So far I have projects on which I don't have separate staging env. Maybe there should be kind of option for creating env config based on others? Not sure though, since it's just copy & paste with minor changes. Let's see what others think about that.

**Comment by schneems** [comment]
I disagree with the use of a "staging" environment https://devcenter.heroku.com/articles/deploying-to-a-custom-rails-environment

It causes more problems than it solves.

Even if that wasn't the case issues are for bug reports only. If you want to talk about this please do so in the mailing list, alternatively open a PR. Closing this issue.
