### ISSUE TITLE
Rails assumes content-type json for HEAD/GET requests

### ISSUE THREAD

**Issue by colinreidbrown** [rails/rails#20571]
when making a simple HEAD or GET request for a txt only file type served by rails, the rails server assumes the request is of type json instead of handling for the txt mime type

======================================
telnet 127.0.0.1 3000
Trying 127.0.0.1...
Connected to localhost.
Escape character is '^]'.
HEAD /alive.txt HTTP/1.1
host: localhost

HTTP/1.1 200 OK
Content-Type: application/json; charset=utf-8
X-UA-Compatible: IE=Edge

======================================
telnet 127.0.0.1 3000
Trying 127.0.0.1...
Connected to localhost.
Escape character is '^]'.
GET /alive.txt HTTP/1.1
host: localhost

HTTP/1.1 200 OK
Content-Type: application/json; charset=utf-8

**Comment by simon2k** [comment]
Hi @colinreidbrown 

I tried both calls, and have the following result:

```
Trying 127.0.0.1...
Connected to localhost.
Escape character is '^]'.
HEAD /pub.txt HTTP/1.1
host: localhost

HTTP/1.1 200 OK
Last-Modified: Mon, 15 Jun 2015 19:26:55 GMT
Content-Type: text/plain
Content-Length: 5
Server: WEBrick/1.3.1 (Ruby/2.1.2/2014-05-08)
Date: Mon, 15 Jun 2015 19:30:23 GMT
Connection: Keep-Alive
```

```
Trying 127.0.0.1...
Connected to localhost.
Escape character is '^]'.
GET /pub.txt HTTP/1.1
host: localhost

HTTP/1.1 200 OK
Last-Modified: Mon, 15 Jun 2015 19:26:55 GMT
Content-Type: text/plain
Content-Length: 5
Server: WEBrick/1.3.1 (Ruby/2.1.2/2014-05-08)
Date: Mon, 15 Jun 2015 19:31:41 GMT
Connection: Keep-Alive
```

Could you provide more details about your setup?

**Comment by colinreidbrown** [comment]
require a status page that dies when rails dies or monitoring. so /public won't work as nginx will still serve the static file. 

first go was to set up a routed page:

routes.rb
```
get "/alive.txt", to: 'alive#index', via: :head 
```

alive_controller.rb
```
  respond_to :text  
    def index
        render :index, layout: false, content_type: 'text/plain' 
    end
```
simple curl request of
```
curl -i -X HEAD http://localhost:3000/alive.txt
```
responds fine with 
```
curl -i -X HEAD http://localhost:3000/alive.txt
HTTP/1.1 200 OK
Content-Type: text/plain; charset=utf-8
X-UA-Compatible: IE=Edge
ETag: "d36f8f9425c4a8000ad9c4a97185aca5"
Cache-Control: max-age=0, private, must-revalidate
X-Request-Id: 22dd32e12d287ec2427498297d315b0b
X-Runtime: 0.012388
Date: Mon, 15 Jun 2015 18:15:46 GMT
X-Rack-Cache: stale, invalid
Content-Length: 0
Connection: keep-alive
Server: thin
```

but subsequent calls with telnet, load balancer etc fail.
```
HTTP/1.1 500 Internal Server Error
Content-Type: text/plain; charset=utf-8
X-Request-Id: 50868ea64154b927afa8db9d7dd4cb0c
X-Runtime: 0.050029
Date: Mon, 15 Jun 2015 18:50:15 GMT
X-Rack-Cache: miss
Connection: close
Server: thin

ActionView::MissingTemplate at /alive.txt
=========================================

> Missing template alive/index, application/index with {:locale=>[:en], :formats=>[:json], :handlers=>[:erb, :builder, :coffee, :haml]}. Searched in:
  * "/Users/cobrown/workspace/elmer/app/views"
  * "/Users/cobrown/.rvm/gems/ruby-2.0.0-p594@elmer/gems/swagger-ui_rails-0.1.7/app/views"
  * "/Users/cobrown/.rvm/gems/ruby-2.0.0-p594@elmer/gems/grape-swagger-ui-0.0.9/app/views"
  * "/Users/cobrown/.rvm/gems/ruby-2.0.0-p594@elmer/gems/rails_admin-0.4.9/app/views"
  * "/Users/cobrown/.rvm/gems/ruby-2.0.0-p594@elmer/gems/kaminari-0.16.3/app/views"
  * "/Users/cobrown/.rvm/gems/ruby-2.0.0-p594@elmer/gems/devise-2.2.7/app/views"


app/controllers/alive_controller.rb, line 3
-------------------------------------------

   ruby
    1   class AliveController < ApplicationController
    2     def index
>   3       render :index, layout: false, content_type: 'text/plain'
    4     end
    5   end
```

only get a valid ok response if i set the responder to 
```
  respond_with do |format| 
    format.all{ render text: 'ok' }
  end
```

using thin (locally) and unicorn+nginx (staging)

**Comment by simon2k** [comment]
I'm trying really hard to reproduce the error, but without success:
```
Started HEAD "/alive.txt" for 127.0.0.1 at 2015-06-16 07:43:54 +0200
Processing by AliveController#index as HTML
request.format => #<Mime::Type:0x007fcb42d657a8 @string="text/html", @symbol=:html, @synonyms=["application/xhtml+xml"]>
```

I'm not sure about this `json` format - could you check out `request.format`? It's kinda  weird that telnet sends `text/plain` and rails processes it as `json`. Could you use this: https://github.com/rails/rails/blob/master/guides/bug_report_templates/action_controller_gem.rb for setting a sample app where it can be reproducible?

**Comment by colinreidbrown** [comment]
created a sample app here ->  https://github.com/colinreidbrown/txt_bug 
several examples in alive_controller.rb 

curl responds ok, telnet not so much.

**Comment by simon2k** [comment]
Thanks for creating the app. Checked it against several cases. By default if you don’t specify format for the request it will use a `html` file, even if in the URL we have `txt` postfix - adding `index.html.erb` solves issue in this context.

If you still want to use `index.text.erb`, then it should be a bit differently. There should be specified format for the request. You can specify it within routes, for instance: `get '/alive', to: 'alive#index', defaults: { format: :txt }`. What is kinda misleading is the fact that when you specify format within name of route (`’/alive.txt’`), it’s not taken into the consideration as a format but as a whole path, so you need to specify the format second time:

```
HEAD /alive.txt.txt HTTP/1.1
host: localhost
```
And that's why you need to create a html file, since it's treating it as a html format.

Also, when you drop `.txt` from the path name: `get '/alive', to: 'alive#index’`, and you specify format in the request: `HEAD /alive.txt HTTP/1.1`, it’ll use the txt format. I think, that's the solution you're looking for.

**Comment by colinreidbrown** [comment]
Thanks for the clarification.
