### ISSUE TITLE
Rails v4.2.2 security release bumps Sprockets from 2 to 3

### ISSUE THREAD

**Issue by jgross206** [rails/rails#20592]
Hi,

I went to apply the new security patch and found my app broken because it updates Sprockets from 2 to 3.  Here's the line for the diff:

https://github.com/rails/rails/compare/v4.2.1...v4.2.2#diff-e79a60dc6b85309ae70a6ea8261eaf95R194

Is this intentional?

Thanks!

**Comment by rafaelfranca** [comment]
This is the Rails gemfile.lock and it does not affect your application. This release don't dump sprockets, but 4.2.1 allowed both sprockets 2 and 3. If your application needs sprocket 2 make sure you define it in your gemfile

**Comment by jgross206** [comment]
thanks, sorry for the mixup
