### ISSUE TITLE
Caching of URL Helpers Introduced in 4.2.1 Breaks for Me

### ISSUE THREAD

**Issue by benmmurphy** [rails/rails#20604]
This commit (https://github.com/rails/rails/commit/60543fe4ac5d9273442675f8ff1879fe0a991bc5) causes the url helpers to disappear from my views in 4.2.1 compared to 4.2.0. I'm not sure if this is because my use case which involves a weird inheritance hierarchy with a rails engine is not supported.

So basically I have this inheritance hierarchy:

XXController < RailsEngine::AuthenticatedController < ApplicationController

where XXController and ApplicationController are from the Rails application and RailsEngine::AuthenticatedController is from the Rails engine.

The problem is the dynamic URL helper module is included multiple times into the controller but the URL helper module uses self.included which will only be invoked the first time it is included.

https://github.com/rails/rails/blob/60543fe4ac5d9273442675f8ff1879fe0a991bc5/actionpack/lib/action_dispatch/routing/route_set.rb#L528

          included do
            singleton_class.send(:redefine_method, :_routes) { routes }
          end

So without module caching we have unique module instances so the _routes method follows:

_routes -> Route Set from Main Rails App (ApplicationController)
_routes -> Route Set from Engine (RailsEngine::AuthenticatedController)
_routes -> Route Set from Main Rails App (XXController)

but with module caching the _routes method follows:

_routes -> Route Set from Main Rails App (ApplicationController)
_routes -> Route Set from Engine (RailsEngine::AuthenticatedController)
*** the included block does not run because the module was already included from ApplicationController

**Comment by arthurnn** [comment]
Right, I guess this is a valid use case and probably a bug.
TBH, i am not sure how hot the method `url_helpers` is, so I dunno if we can safely rever that commit. @eileencodes does the memoization on 60543fe4ac5d9273442675f8ff1879fe0a991bc5 bring a lot of perf improvements? 

cc @pixeltrix

**Comment by eileencodes** [comment]
Huh I know that commit was already reverted in and made unnecessary by 0acd4a5. Maybe the revert didn't make it into 4.2?

**Comment by arthurnn** [comment]
@eileencodes yeah. I think it didnt. I will revert that piece only on 4.2, is that fine with you?

**Comment by eileencodes** [comment]
Either revert or backport  0acd4a5. 60543fe really didn't make that much of a difference anyway.
