### ISSUE TITLE
rubygems gem does not match version code

### ISSUE THREAD

**Issue by jimmykarily** [rails/rails#20601]
https://rubygems.org/downloads/activerecord-4.1.11.gem

check [this file](https://github.com/rails/rails/blob/4-1-stable/activerecord/lib/active_record/relation/delegation.rb#L40) in the gem version above. Compact should be missing but it is still there. Failed gem build?

**Comment by matthewd** [comment]
4.1.11 was a security release; it contains only the described security fix

**Comment by jimmykarily** [comment]
So what? Shouldn't it be included in the gem? If not how are we supposed to apply the fix?

**Comment by jimmykarily** [comment]
Oh got it
