### ISSUE TITLE
Sanitize helper truncates text. 4.2.1

### ISSUE THREAD

**Issue by FlySnake** [rails/rails#20617]
I have a large text stored in postres `text` field which should be displayed on a page. Before displaying it gets sanitized with `sanitize` helper.
Original text in file and sanitized: https://yadi.sk/d/tpPMTsjWhKjTM

You can download original file and check its length with and without sanitizing
```
raw = File.read('/Users/oleg_antonyan/Desktop/raw.txt')
raw.length
=> 423459
helper.sanitize(raw).length
=> 33815
```

**Comment by FlySnake** [comment]
Turns out it's problem with Loofah (or Nokogiri) https://github.com/flavorjones/loofah/issues/89

**Comment by kaspth** [comment]
Nice digging, @FlySnake! We'll close this here, people with the same issue can now follow through the real one. Thanks :heart:
