### ISSUE TITLE
[Meta] Rails 5.0 Release Notes

### ISSUE THREAD

**Issue by chancancode** [rails/rails#20612]
Reference this issue in a commit message/comment, and they will show up here! :sparkles: :heart:

**Comment by robin850** [comment]
I take the liberty to comment there to avoid creating notifications for each ticket:

#19216
#19813
#19832

**Comment by robin850** [comment]
#20781 (feature)
#20866 (deprecation)
#20868 (possible breaking change)

**Comment by rafaelfranca** [comment]
https://github.com/rails/rails/pull/21161

**Comment by robin850** [comment]
#20884 (feature)

Also maybe we could add a note about speed improvements (e.g. #21057 and also symbol GC).

**Comment by sgrif** [comment]
#21135

**Comment by maclover7** [comment]
All of these repos say they are being deprecated when 5.0 ships:
- https://github.com/rails/activerecord-deprecated_finders
- https://github.com/rails/prototype-rails
- https://github.com/rails/rails-deprecated_sanitizer

As well, all of these projects (see below) have semi-uncertain futures. Should everything extracted in 4.0 to a gem be deprecated when 5.0 comes out, or should it be supported until next major version?
- https://github.com/rails/actionpack-page_caching
- https://github.com/rails/actionpack-xml_parser
- https://github.com/rails/journey
- https://github.com/rails/rails-observers

**Comment by sgrif** [comment]
If the gem doesn't specifically say that it'll be supported until X version, we have no plans to stop supporting it at this time.

**Comment by rafaelfranca** [comment]
journey is deprecated since Rails 4.2. But the others will still be supported

**Comment by claudiob** [comment]
If Rails 5 ships with Sprockets 3, then a reference to https://github.com/rails/sprockets/blob/master/UPGRADING.md will be needed in the Rails 5.0 release notes

**Comment by prathamesh-sonpatki** [comment]
https://github.com/rails/rails/pull/21069 (Feature)

**Comment by sgrif** [comment]
#12071 (Feature)

**Comment by maclover7** [comment]
#22457

**Comment by simi** [comment]
https://github.com/rails/rails/pull/18937

**Comment by yui-knk** [comment]
#21601 (deprecation)

**Comment by senny** [comment]
I've started extracting notable changes, deprecations and removals for Rails 5. I'm going to close this issue, further updates should be done directly to [5_0_release_notes.md](https://github.com/rails/rails/blob/master/guides/source/5_0_release_notes.md).
