### ISSUE TITLE
Confusion around form_for defaults and json/js

### ISSUE THREAD

**Issue by joallard** [rails/rails#20610]
With Convention over configuration, you can usually trust the defaults to get you there. In this case, not so much. I've been banging my head on the wall for a few hours now, in between trying things and researching.

For the usual cases, how do I set up an AJAX form. Is it using JS or JSON format?

**Case 1: `form_for remote: true` default, `format.js`**

UJS sends a request as JS.  
Exception: Missing template for update.js.

`form_for remote: true, format: :json`

No difference in HTML output, though `form_for` doc examples says you can do that.

**Case 2: `form_for remote: true, html: {"data-type" => :json}` not the default**

Responder will answer 204, but why is this not default in either `form_for` or UJS?

What is the expected use case and can it be documented? I suspect it's the latter, but I expected there to be good defaults in place.

**Comment by rafaelfranca** [comment]
Please use the mailing list or StackOverflow for questions/help, where a wider community will be able to help you. We reserve the issues tracker for issues only.

**Comment by joallard** [comment]
Does the Google Groups UX count as an issue?

**Comment by joallard** [comment]
I think that summarizes my experience of the mailing list pretty well:
https://groups.google.com/forum/#!topic/rubyonrails-talk/FFgltQ_6vhg

There's no urgency to respond or to do anything really to change anything...

**Comment by rafaelfranca** [comment]
> Is it using JS or JSON format?

The default is JS format.

`format: :json` only works if you use it on the URL helper.

**Comment by rafaelfranca** [comment]
> though form_for doc examples says you can do that.

Looks like the doc is wrong for this case.

**Comment by rafaelfranca** [comment]
> What is the expected use case and can it be documented?

It is the first. The default is JS not JSON.

**Comment by joallard** [comment]
Thank you. 

Do we expect a JS template to be provided for JS responses? (My problem is mainly that the defaults aren't/are hard to work out of the box)

**Comment by rafaelfranca** [comment]
Yes, we expect a JS template to be provided or just a empty response like `204`

**Comment by joallard** [comment]
I've just tried a scaffold on a new 4.2.3 app: the form is sent by default in JS, but the controller has `respond.json` clauses, and no template. I guess it works that way. I just expected both formats to match.

Is there a reason that the default is to respond to JS (or using JS)? I admit I'm kinda lost. Maybe clarifying this in the docs would be of help.

**Comment by rafaelfranca** [comment]
> Is there a reason that the default is to respond to JS (or using JS)?

Yes, the reason is https://signalvnoise.com/posts/3697-server-generated-javascript-responses.

> Maybe clarifying this in the docs would be of help.

:+1:. Feel free to send a PR.

**Comment by joallard** [comment]
I'll take a look, thanks for the help!

**Comment by natetech333** [comment]
I think this issue needs reopened and resolved because it still has not been resolved in 4 years. It is adding a lot of confusion on stackoverflow. And now Rails 5.1 uses form_with which defaults to remote forms. The primary problem is Rails scaffolds controllers with format.json but the form_with uses format.js by default. It ks breaking the concept of convention over configuration. And I honestly do not understand why form_with was changed to use remote ajax forms by default.
