### ISSUE TITLE
template_name method is being called

### ISSUE THREAD

**Issue by rbarrera87** [rails/rails#20613]
I have a model with a property called template_name, when I try to run a rake task creating a record with a code as follows it gets an error:
```ruby
m = MyModel.new
m.template_name = "Template"
m.save
#=>undefined method `split' for nil:NilClass
#=>/bundler/ruby/2.1.0/gems/actionview-4.2.1/lib/action_view/tasks/dependencies.rake:15:in `template_name'
```

Looking at that file, it seems like this method is being called:
```ruby
def template_name
  ENV['TEMPLATE'].split('.', 2).first
end
```

It should be emphasized that this error only happens when it runs through a rake task, in rails console that code works pretty well.

I don't know why that method is being called, should I rename my property_name? 

Ruby version: **ruby 2.1.2p95**
Rails version: **4.2.1**

**Comment by rafaelfranca** [comment]
Could you check the 4-2-stable branch?

**Comment by rbarrera87** [comment]
I just tried it with rails 4.2.2 and I'm getting the same error :disappointed: The workaround is just running the rake task with  **TEMPLATE** as an empty string
```
$ TEMPLATE="" bundle exec rake your_rake_task
```

**Comment by pascalbetz** [comment]
Are you sure you calling ```template_name``` on your model and not on your rake rask? I can reproduce your error message if i do the following:

```rake
task :foo => :environment do
  template_name
end
```
=>
```console
rake aborted!
NoMethodError: undefined method `split' for nil:NilClass
/Users/pascal/.rvm/gems/ruby-2.2.0/gems/actionview-4.2.1/lib/action_view/tasks/dependencies.rake:15:in `template_name'
/Users/pascal/repositories/playground/codepay/lib/tasks/foo.rake:2:in `block in <top (required)>'
/Users/pascal/.rvm/gems/ruby-2.2.0/bin/ruby_executable_hooks:15:in `eval'
/Users/pascal/.rvm/gems/ruby-2.2.0/bin/ruby_executable_hooks:15:in `<main>'
Tasks: TOP => foo
(See full trace by running task with --trace)
```

Following code works:
```rake
task :foo => :environment do
  f = Foo.new
  f.template_name = 'FooBarBaz'
  f.save
end
```

So i'm pretty sure your code sample is not producing the error when you run it. And then this issue is probably not a bug.

**Comment by prathamesh-sonpatki** [comment]
I verified this issue on Rails 4.2.1, 4.2.4 and master and could not reproduce. I have uploaded the sample app to Github here - https://github.com/prathamesh-sonpatki/reproduction-for-20613.

I am closing this issue. Please upload the sample app on Github which causes this issue and I will reopen.

Thanks everyone.

**Comment by bluerabbit** [comment]
It fixed by https://github.com/rails/rails/pull/1706
