### ISSUE TITLE
ActiveRecord Associations PG incorrectly handles uuid ID

### ISSUE THREAD

**Issue by avongluck-r1soft** [rails/rails#20611]
ActiveRecord Assocations with PG incorrectly handles uuid key id types.

*    rails (4.2.1)
   *   actionmailer (= 4.2.1)
   *   actionpack (= 4.2.1)
   *   actionview (= 4.2.1)
   *   activejob (= 4.2.1)
   *   activemodel (= 4.2.1)
   *   activerecord (= 4.2.1)
   *   activesupport (= 4.2.1)
   *   bundler (>= 1.3.0, < 2.0)
   *   railties (= 4.2.1)
   *   sprockets-rails

**Example:**
  enable_extension "uuid-ossp"

**Schema:**
sbm 
```
def change
    remove_column :sbms, :id
    rename_column :sbms, :uuid, :id
    execute "ALTER TABLE sbms ADD PRIMARY KEY (id);"
end
```
sbm_stats
```    t.uuid     "sbm_id"```

**Relations:**
class SbmStat < ActiveRecord::Base
    belongs_to :sbm
end
class Sbm < ActiveRecord::Base
    has_many :sbm_stats
end

**Forms incorrect SQL**
```@sbm.sbm_stats.where(:name => "cpu_user")```

(notice the WHERE "sbm_stats"."sbm_id" = $1 below)
```PG::InvalidTextRepresentation: ERROR: invalid input syntax for integer: "da4340f6-89a2-4039-90ec-5781d84c155e" : SELECT "sbm_stats".* FROM "sbm_stats" WHERE "sbm_stats"."sbm_id" = $1 AND "sbm_stats"."name" = $2 ORDER BY "sbm_stats"."time" DESC```

**Forms correct SQL (bypassing ActiveRecord Associations)**
```SbmStat.where(:name => "cpu_user", :sbm_id => @sbm.id)```

**Comment by matthewd** [comment]
> notice the `WHERE "sbm_stats"."sbm_id" = $1` below

I'm obviously being thick, because that sounds right to me.

Can you please show us the generated "correct" SQL for comparison, and/or turn the above into an [executable script](http://edgeguides.rubyonrails.org/contributing_to_ruby_on_rails.html#create-an-executable-test-case)?

**Comment by avongluck-r1soft** [comment]
Easy. 

What active record assoc generates:
```
XXX_dev=# select * from sbm_stats where sbm_id = e8674c6b-3567-4b44-6605-24e1f96d089b;
ERROR:  syntax error at or near "b44"
LINE 1: ...ct * from sbm_stats where sbm_id = e8674c6b-3567-4b44-9605-2...
```

Correct:
```
XXX_dev=# select * from sbm_stats where sbm_id = 'e8674c6b-3567-4b44-6605-24e1f96d089b' LIMIT 1;
   id   |        time         |   name   | data | unit |         created_at         |         updated_at         |                sbm_id                
--------+---------------------+----------+------+------+----------------------------+----------------------------+--------------------------------------
 113983 | 2015-06-17 21:04:04 | cpu_user |    0 | %    | 2015-06-17 21:04:38.446928 | 2015-06-17 21:04:38.446928 | e8674c6b-3567-4b44-6605-24e1f96d089b
(1 row)
```

**Comment by avongluck-r1soft** [comment]
interestingly postgresql seems to mention using the straight uuid query (no 's)
http://www.postgresql.org/docs/9.4/static/datatype-uuid.html

However in practice it doesn't work...
```
XXX_dev=# select column_name, data_type from information_schema.columns where table_name = 'sbm_stats';
 column_name |          data_type          
-------------+-----------------------------
 id          | integer
 time        | timestamp without time zone
 name        | character varying
 data        | integer
 unit        | character varying
 created_at  | timestamp without time zone
 updated_at  | timestamp without time zone
 sbm_id      | uuid
```

**Comment by matthewd** [comment]
> What active record assoc generates:

Now I'm even more confused. That's producing a different error than you gave earlier (and sounds unlikely that we'd generate it).

Earlier you said:

> **Forms correct SQL (bypassing ActiveRecord Associations)**
> `SbmStat.where(:name => "cpu_user", :sbm_id => @sbm.id)`

Can you please show the SQL generated by that line? I would expect it to produce the same as the association:

``` sql
SELECT "sbm_stats".* FROM "sbm_stats" WHERE "sbm_stats"."sbm_id" = $1 AND "sbm_stats"."name" = $2 ORDER BY "sbm_stats"."time" DESC
```

... which still sounds correct to me.

**Comment by avongluck-r1soft** [comment]
**Code:**
```
      render json: [{:name => "user", data: SbmStat.where(:name => "cpu_user", :sbm_id => @sbm.id).order(time: :desc).map {|row| [row[:time], row[:data]] }},
        {:name => "system", data: SbmStat.where(:name => "cpu_system", :sbm_id => @sbm.id).order(time: :desc).map {|row| [row[:time], row[:data]] }},
        {:name => "idle", data: SbmStat.where(:name => "cpu_idle", :sbm_id => @sbm.id).order(time: :desc).map {|row| [row[:time], row[:data]] }}]
```

**Resulting SQL**
```
  Sbm Load (0.3ms)  SELECT  "sbms".* FROM "sbms" WHERE "sbms"."id" = $1 LIMIT 1  [["id", "da4340f6-89a2-4039-90ec-5781d84c155e"]]
  SbmStat Load (2.0ms)  SELECT "sbm_stats".* FROM "sbm_stats" WHERE "sbm_stats"."name" = $1 AND "sbm_stats"."sbm_id" = $2  ORDER BY "sbm_stats"."time" DESC  [["name", "cpu_user"], ["sbm_id", "da4340f6-89a2-4039-90ec-5781d84c155e"]]
```


**Code**
```
      render json: [{:name => "user", data: @sbm.sbm_stats.where(:name => "cpu_user").order(time: :desc).map {|row| [row[:time], row[:data]] }},
        {:name => "system", data: @sbm.sbm_stats.where(:name => "cpu_system").order(time: :desc).map {|row| [row[:time], row[:data]] }},
        {:name => "idle", data: @sbm.sbm_stats.where(:name => "cpu_idle").order(time: :desc).map {|row| [row[:time], row[:data]] }}]
```

**Result**
```
Started GET "/sbms/da4340f6-89a2-4039-90ec-5781d84c155e/chart/cpu" for 10.80.65.13 at 2015-06-17 17:09:02 -0500
Processing by SbmsController#chart as HTML
  Parameters: {"id"=>"da4340f6-89a2-4039-90ec-5781d84c155e", "metric"=>"cpu"}
  Sbm Load (0.2ms)  SELECT  "sbms".* FROM "sbms" WHERE "sbms"."id" = $1 LIMIT 1  [["id", "da4340f6-89a2-4039-90ec-5781d84c155e"]]
  SbmStat Load (0.8ms)  SELECT "sbm_stats".* FROM "sbm_stats" WHERE "sbm_stats"."sbm_id" = $1 AND "sbm_stats"."name" = $2  ORDER BY "sbm_stats"."time" DESC  [["sbm_id", "da4340f6-89a2-4039-90ec-5781d84c155e"], ["name", "cpu_user"]]
PG::InvalidTextRepresentation: ERROR:  invalid input syntax for integer: "da4340f6-89a2-4039-90ec-5781d84c155e"
: SELECT "sbm_stats".* FROM "sbm_stats" WHERE "sbm_stats"."sbm_id" = $1 AND "sbm_stats"."name" = $2  ORDER BY "sbm_stats"."time" DESC
Completed 500 Internal Server Error in 18ms (ActiveRecord: 3.5ms)

ActiveRecord::StatementInvalid (PG::InvalidTextRepresentation: ERROR:  invalid input syntax for integer: "da4340f6-89a2-4039-90ec-5781d84c155e"
: SELECT "sbm_stats".* FROM "sbm_stats" WHERE "sbm_stats"."sbm_id" = $1 AND "sbm_stats"."name" = $2  ORDER BY "sbm_stats"."time" DESC):
  app/controllers/sbms_controller.rb:32:in `chart'


  Rendered /var/lib/gems/2.1.0/gems/actionpack-4.2.1/lib/action_dispatch/middleware/templates/rescues/_source.erb (4.9ms)
  Rendered /var/lib/gems/2.1.0/gems/actionpack-4.2.1/lib/action_dispatch/middleware/templates/rescues/_trace.html.erb (1.8ms)
  Rendered /var/lib/gems/2.1.0/gems/actionpack-4.2.1/lib/action_dispatch/middleware/templates/rescues/_request_and_response.html.erb (0.6ms)
  Rendered /var/lib/gems/2.1.0/gems/actionpack-4.2.1/lib/action_dispatch/middleware/templates/rescues/diagnostics.html.erb within rescues/layout (14.3ms)
  Rendered /var/lib/gems/2.1.0/gems/web-console-2.1.2/lib/web_console/templates/_markup.html.erb (0.2ms)
  Rendered /var/lib/gems/2.1.0/gems/web-console-2.1.2/lib/web_console/templates/style.css.erb within layouts/inlined_string (0.2ms)
  Rendered /var/lib/gems/2.1.0/gems/web-console-2.1.2/lib/web_console/templates/_inner_console_markup.html.erb within layouts/inlined_string (0.2ms)
  Rendered /var/lib/gems/2.1.0/gems/web-console-2.1.2/lib/web_console/templates/_prompt_box_markup.html.erb within layouts/inlined_string (0.2ms)
  Rendered /var/lib/gems/2.1.0/gems/web-console-2.1.2/lib/web_console/templates/console.js.erb within layouts/javascript (7.9ms)
  Rendered /var/lib/gems/2.1.0/gems/web-console-2.1.2/lib/web_console/templates/main.js.erb within layouts/javascript (0.2ms)
  Rendered /var/lib/gems/2.1.0/gems/web-console-2.1.2/lib/web_console/templates/error_page.js.erb within layouts/javascript (0.2ms)
  Rendered /var/lib/gems/2.1.0/gems/web-console-2.1.2/lib/web_console/templates/index.html.erb (16.4ms)
```

**Comment by avongluck-r1soft** [comment]
... those look identical to me but one is failing oddly.

```
  SbmStat Load (2.0ms)  SELECT "sbm_stats".* FROM "sbm_stats" WHERE "sbm_stats"."name" = $1 AND "sbm_stats"."sbm_id" = $2  ORDER BY "sbm_stats"."time" DESC  [["name", "cpu_user"], ["sbm_id", "da4340f6-89a2-4039-90ec-5781d84c155e"]]
  SbmStat Load (0.8ms)  SELECT "sbm_stats".* FROM "sbm_stats" WHERE "sbm_stats"."sbm_id" = $1 AND "sbm_stats"."name" = $2  ORDER BY "sbm_stats"."time" DESC  [["sbm_id", "da4340f6-89a2-4039-90ec-5781d84c155e"], ["name", "cpu_user"]]
```

**Comment by matthewd** [comment]
A hopefully-obvious question, just for my own sanity: these are both from the same machine, talking to the same database instance, where the only thing that's changed between them is that line of code, right?

Because the second one really sounds like PostgreSQL thinks `"sbm_stats"."sbm_id"` is an integer.

Was that recently the case?

**Comment by avongluck-r1soft** [comment]
Same dev server. I did do a migration from int to uuid for sbm_id and haven't restarted the server... Migrations should be picked up though in dev environment without a restart... Right?

**Comment by matthewd** [comment]
On the Rails side, sure. But it sounds like PostgreSQL failed to flush its internal schema cache, and you haven't reconnected to force it to go away.

I thought that was fixed back in one of the later 8.x releases, though. :confused:

**Comment by avongluck-r1soft** [comment]
Ah. I'll restart the rails server tomorrow when I get in the office to see if it goes away.  Also using puma in case that's a factor

**Comment by senny** [comment]
On a side note, if it is related to how Active Record generates the query, please provide an executable test-case to reproduce the problem. This goes a long way to bring everyone on the same page. You can use [this script](https://github.com/rails/rails/blob/master/guides/bug_report_templates/active_record_master.rb) as a starting point.

**Comment by avongluck-r1soft** [comment]
Yup. A simple restart of the app server fixed this issue. It has a work around, i'll leave it up to you guys to close if desired.
