### ISSUE TITLE
Parse_query fix in #19665 was reverted

### ISSUE THREAD

**Issue by ejenks** [rails/rails#20624]
When generating a new rails app I went to do a sanity check by running ```rails s```, I received this error:

```md
Started GET "/" for ::1 at 2015-06-18 15:29:27 -0400

ArgumentError (wrong number of arguments (2 for 1)):
  actionpack (4.2.2) lib/action_dispatch/http/request.rb:338:in `parse_query'
  rack (1.6.3) lib/rack/request.rb:191:in `GET'
```

This was fixed in #19665, but it is only present in the master branch, not in the v4.2.2 tag.

**Comment by lamielle** [comment]
We are seeing this issue right now as well.

**Comment by johanns** [comment]
Ditto!

**Comment by lamielle** [comment]
Here is our hack fix to our Gemfile to get our UI/builds running again:

gem 'rack', '1.6.1'

**Comment by alakra** [comment]
Seeing this also.

**Comment by johanns** [comment]
@lamielle Yes, I used the same workaround. But I'd recommend using 1.6.2 for the time being... see:
https://groups.google.com/forum/#!msg/rubyonrails-security/gcUbICUmKMc/qiCotVZwXrMJ

`gem 'rack', '1.6.2'`

**Comment by lamielle** [comment]
Thanks @johanns.  Also, rack/rack#896 looks to be tracking this too.

**Comment by matthewd** [comment]
Yeah, this isn't a rails issue: rack has accidentally broken API compatibility, and the problem is being fixed there.

**Comment by zavan** [comment]
This is now solved by the release of rack 1.6.4.

**Comment by rbpicanco** [comment]
So how do I get rack 1.6.4?  I tried bundle install but no luck

**Comment by jonathantimm** [comment]
@zavan, I updated to that version and I'm having the same problem. :-(

**Comment by johanns** [comment]
@jonathantimm What's the version of **rack** shown when you run `bundle list` in your project directory?

**Comment by jonathantimm** [comment]
"Could not locate Gemfile or .bundle/ directory"

Earlier I tried bundle list and got 

    rack (1.6.4, 1.6.3)

I was following the directions here: http://installfest.railsbridge.org/installfest/create_a_rails_app
So I tried running bundle list on the railsbridge directory and got the above error. Thanks for your help!

**Comment by jonathantimm** [comment]
For anyone who sees this - I got it. I had to do the bundle update so that it got rid of 1.6.3.

**Comment by SyMak** [comment]
OMG thx! I have wasted 2,5 hours on this - i am a super newbie so it was very frustrating thanks again!
