### ISSUE TITLE
ActiveRecord::RecordInvalid is not eager loaded

### ISSUE THREAD

**Issue by davidcelis** [rails/rails#20626]
The `ActiveRecord::RecordInvalid` exception, located in `lib/active_record/validations.rb` is not eager loaded. This has been causing a `NameError` on one of my Rack apps using ActiveRecord that try to define a rescuer for `ActiveRecord::RecordInvalid` before, apparently, ActiveRecord::Validations has autoloaded. I can manually `require 'active_record/validations'` but it seems to me that class should be Autoloadable or something. This is probably related to #18898

**Comment by rafaelfranca** [comment]
Backported in 819bc2c and 741a3e8

**Comment by davidcelis** [comment]
Thanks for the quick fix! :sparkling_heart:
