### ISSUE TITLE
Eager loading scoped conditions on remapped table names

### ISSUE THREAD

**Issue by foeken** [rails/rails#20628]
I am unsure if this is a bug or just me not knowing the correct Arel syntax to accomplish this so please stay with me for a few minutes while I explain.

Say we have two AR classes. `Node` and `Property`. `Node` has another `Node` as a parent. And each `Node` has many `Property` objects:

```ruby
class Node < ActiveRecord::Base
  belongs_to :parent, class_name: "Node"
  has_many :properties, -> { test_scope }
end

class Property < ActiveRecord::Base
  belongs_to :node
  scope :test_scope, -> { where(self.arel_table[:key].eq("test")) }
end
```

How do I define a (complex) scope on my has_many relationship that survives remapping though eager loading?

```ruby
Node.eager_load( :properties, :parent => :properties )
```

yields

```sql
SELECT "nodes"."id" 
[...] 
"properties_nodes" ON "properties_nodes"."node_id" = "parents_nodes"."id" 
AND "properties"."key" = 'test'
```

> NOTE: the last part: `AND "properties"."key" = 'test'` should be `AND "properties_nodes"."key" = 'test'` as it has been remapped by the eager loading.

Now for simple scopes this works:

```ruby
scope :test_scope, -> { where(key: "test") }
```

But when I need I range query ( like gt or lt ) how I achieve this? Normally you could do the string based version:

```ruby
scope :test_scope, -> { where("date > ?", Date.today) }
```

But that does not get remapped (quite logically). 

```ruby
scope :test_scope, -> { where(self.arel_table[:date].gt(Date.today)) }
```

When using Arel I would expect it to get remapped to the proper join table name. **How do I achieve this, or is this a bug and should the Arel code have been remapped by rails?**

**Comment by matthewd** [comment]
Please use the mailing list or StackOverflow for questions/help, where a wider community will be able to help you. We reserve the issues tracker for issues only.

**Comment by matthewd** [comment]
I think you might be looking at an API limitation... but I don't see a bug.

**Comment by foeken** [comment]
Okay, I do feel that now that you guys made the effort to push the magic of these associations through this far, this might not be clear to people.

In short: HM and HMT associations support scopes, but they *might* not successfully apply them when they are eager loaded and are remapped. They might even generate invalid SQL if the original table name is not part of the join.

Sorry about posting it here, but I still feel this borders more on a bug then on a question :) Though I agree  the magic required to fix this might be too much :smile:
