### ISSUE TITLE
#valid? clear erros before `run_validations!` clears previous DB dependent validations

### ISSUE THREAD

**Issue by filipebarcos** [rails/rails#20623]
We have a piece of code where we run `save!` method for a couple of instances of the same model inside a transaction.
```ruby
MyModel.transaction { array_of_my_models.map(&:save!) }
```
Inside of my model I have
```ruby
class MyModel < AR::Base
  validate :some_validation_dependent_on_other_records_on_db, on: :create

  def some_validation_dependent_on_other_records_on_db
    errors.add(:relationship_id, 'message') if relationship.can_i_add_more?
  end
end
```
Basically, my business logic says that I can only add new `MyModel` records if `MyModel#relationship` has enough room for add more of it. So, in my example, I can only add 1 new record, although, I'm testing if I can add 2. So `array_of_my_models.count` is 2.

So, for the second record I'm trying to add, I got a `ActiveRecord::RecordInvalid`, since my validation fails and I'm using `save!`. I'm rescuing this exception, and returning.

With this result, I get my collection of resources (`array_of_my_models`), and send it over to another class which is responsible for handling the errors of each invalid entry. The code, basically loops through each calling `valid?`, if invalid something is done, if valid, is ignored.

The problem with this approach is because `valid?` clears the errors and calls `run_validations!`. Since my validation is dependent on DB state, now, all records are valid, individually, since they're not wrapped in a transaction anymore.
```ruby
def handle_errors(array_of_my_models)
  array_of_my_models.each |model|
    next if model.valid?
    handle_individually(model)
  end
end
```

I noticed this when I was updating my rails version from `4.2.0` to `4.2.2`. So I tested with `4.2.1` to narrow down the changes (it fails with `4.2.1`). So I checked the changes in `activerecord` and `activemodel` nothing really changed. So valid clears the erros since "forever".
```ruby
def valid(context = nil)
  current_context, self.validation_context = validation_context, context
  errors.clear
  run_validations!
ensure
  self.validation_context = current_context
end
```

How this ever worked for me before?! :sweat_smile: 

Can someone help? Or at least say that I'm not crazy to wrap my `handle_errros` method logic in a transaction? :smile_cat: 

Rails Version: `4.2.1` and `4.2.2` (`4.2.0` works -- which is the most weird thing)
Ruby Version: `2.2.0` and `2.2.2`

**Comment by rafaelsales** [comment]
To me it kinda feels natural to think that every `valid?` call will clear out errors list of a previous `run_validations`.

I was wondering if this was a bug, and that was fixed not in activerecord but perhaps in another gem, since the `errors.clear` was always there. Maybe sharing your Gemfile.lock diff of before/after rails upgrade might help identifying that.

Suggestion: instead of calling `valid?`, check for `errors.any?` in your error handling class. It seems that you are already relying that this error handling class will receive models with errors of a previous validation, right?

**Comment by rafaelfranca** [comment]
> Suggestion: instead of calling valid?, check for errors.any? in your error handling class.

This is the way to going.

`valid?` always cleaned the errors before running the validations.

**Comment by filipebarcos** [comment]
thanks anyway :)
