### ISSUE TITLE
ActiveSupport autoload should load ::A::B, but loads ::B

### ISSUE THREAD

**Issue by jaredbeck** [rails/rails#20621]
Consider these two classes with the same name (`B`):

```
# lib/b.rb
class B; end

# lib/a/b.rb
module A
  class B; end
end

# test/lib/b_test.rb
B # will always autoload ::B, no problem

# test/lib/a/b_test.rb
module A
  B 
  # Will either autoload ::B or ::A::B depending on which has already 
  # been loaded.  This is really confusing.  Autoload should try harder
  # to find the right class.
end
```

**Comment by kaspth** [comment]
Autoloading relies on `const_missing` to load constants, which won't be called if the constant is already set. It can't try harder, unfortunately. Though if you can find a way we'd love to see it :heart:

**Comment by jaredbeck** [comment]
> Autoloading relies on const_missing to load constants, which won't be called if the constant is already set. It can't try harder, unfortunately.

That makes sense.  What is the recommended workaround?  

1. Fully qualify the reference to `B`

    ```ruby
    # test/lib/a/b_test.rb
    module A
      ::A::B 
    end
    ```

2. Explicitly require `B`

    ```ruby
    # test/lib/a/b_test.rb
    require "a/b.rb"
    module A
      B 
    end
    ```

I've been using workaround 2, explicit `require`.

Thanks.

**Comment by kaspth** [comment]
Those two work, though you should use `require_dependency` and not `require`. See our autoloading guide: http://guides.rubyonrails.org/autoloading_and_reloading_constants.html#when-constants-aren-t-missed - I recommend reading that through completely :smile:

**Comment by jaredbeck** [comment]
Thanks.  All of this complexity (a 25-page guide!) is the price we pay for quickly reloading files in development mode, isn't it?  Everything's a trade-off :grinning:
