### ISSUE TITLE
Some links on Rails on Rack guide are broken

### ISSUE THREAD

**Issue by repinel** [rails/rails#20637]
The following links from [this guide](https://github.com/rails/rails/blob/7d14bd3ff553d6aba11a50b43773bc21ae20f31e/guides/source/rails_on_rack.md) are returning an `Application Error`:

```
* [Ruby on Rack #1 - Hello Rack!](http://m.onkey.org/ruby-on-rack-1-hello-rack)
* [Ruby on Rack #2 - The Builder](http://m.onkey.org/ruby-on-rack-2-the-builder)
```

@lifo Would you be able to check the website or should I create a PR to remove them? Thanks!

/cc @zzak

**Comment by gaurish** [comment]
Removed via https://github.com/rails/docrails/commit/29a64f2384f53760e9133d11a0c60e0d32ed9187
