### ISSUE TITLE
Shouldn't nested updates respect the relationship's scope?

### ISSUE THREAD

**Issue by agoodno** [rails/rails#20633]
Here, we have a Report which can contain Assets which might have been deleted (from user's perspective).

```ruby
class Report < ActiveRecord::Base
  has_and_belongs_to_many :assets, -> { unscope(where: :is_fake_deleted) }
end

class Asset < ActiveRecord::Base
  default_scope { where is_fake_deleted: false }
end

class ReportsController < ApplicationController
  def update
    if @report.update(report_params)
      head :no_content
    else
      ...
    end
  end

  def report_params
    params.require(:report).permit(..., asset_ids: [], ...)
  end
end
```

So in the console..

```ruby
#Find a report with assets
report = Report.find(1)

#Correctly, returns all assets, including deleted. Here, say, 3 is deleted.
report.assets.map(&:ids)
> [1, 2, 3]
```

Then, in a test (pretend we have the same report data in the database)...
```ruby
#Update action attempts to save exactly the same asset ids back to report fails
put :update, id: 1, report: { ..., asset_ids: [1, 2, 3], ... }
```

```bash
["Couldn't find all Assets with 'id': (1, 2, 3) [WHERE \"assets\".\"is_fake_deleted\" = 'f'] (found 2 results, but was looking for 3)"]
Completed 404 Not Found in 163ms (Views: 0.8ms | ActiveRecord: 49.0ms)
```

The sql that loads the assets just before the update was:
```bash
  Asset Load (0.4ms)  SELECT "assets".* FROM "assets"  WHERE "assets"."is_fake_deleted" = 'f' AND "assets"."id" IN (1, 2, 3)
   (0.2ms)  ROLLBACK TO SAVEPOINT active_record_1
```

You can see that it is respecting Report's `has_and_belongs_to_many :assets` scope during the query through the Report object _but not on update_ (and instead uses the default scope). Is this intended or a bug?

**Comment by meinac** [comment]
Can you please provide a script to reproduce this issue with using this [template](https://github.com/rails/rails/blob/master/guides/bug_report_templates/active_record_gem.rb).

**Comment by agoodno** [comment]
I can but can you tell me if this is desired behaviour or not?

**Comment by meinac** [comment]
I don't know whether it's intended or not, I'm not from Rails team. I'm just trying to help some one while improving my skills about internals of Rails. Just provide a script which reproduce the bug, I'll dive into deep with it and I would say this is intended or not.

**Comment by everton** [comment]
I believe that this problem is somehow related with #20679

On the other issue I linked to this gist: 

> https://gist.github.com/everton/7eed6c00c42712cc0a1f

(Which follows the bug report template)

Does this script represents the same problem for you @agoodno ?
