### ISSUE TITLE
Rails Guides - Needs update to specify that Devkit installation is also needed 

### ISSUE THREAD

**Issue by srikanthps** [rails/rails#20644]
**Applies to windows only**
The getting start page of Rails Guides - http://guides.rubyonrails.org/getting_started.html  - should mention that after installing ruby, one has to install the Development Kit  (http://rubyinstaller.org/downloads/)  to avoid the issue mentioned here: http://stackoverflow.com/questions/8100891/the-json-native-gem-requires-installed-build-tools

**Comment by vijaydev** [comment]
Feel free to send a pull request.

**Comment by srikanthps** [comment]
Thanks Vijay.  I have forked "rails" project.  I want to change the documentation and test it out before sending pull request.

I could not find any documentation on Google on how to run the rails guides locally on my laptop.

Any tips?

**Comment by srikanthps** [comment]
Pull request submitted - https://github.com/rails/rails/pull/20734
