### ISSUE TITLE
Names in API Guides do not reflect diversity of Rails community

### ISSUE THREAD

**Issue by trosborn** [rails/rails#20642]
From what I have seen, whenever a name is used in the API guide it is an English, male name. For example, in [FormOptionsHelper](http://api.rubyonrails.org/classes/ActionView/Helpers/FormOptionsHelper.html) the names used are David, Sam, and Tobias.

I think it would be nice to have these names reflect the diversity of the Rails community. For example, instead of David, Sam, and Tobias, why not David, Eileen, and Rafael? 

:rainbow: :blue_heart: :rainbow: :yellow_heart:  :rainbow: :purple_heart:  :rainbow: :green_heart:  :rainbow: :heart: :rainbow:

**Comment by bf4** [comment]
Why not submit a PR? That way someone can act on this :)

**Comment by rafaelfranca** [comment]
I'll happily apply a PR to reflect the diversity :smile:

**Comment by trosborn** [comment]
Awesome!! I'll go ahead and make one :)
