### ISSUE TITLE
Rails 4.2.0 - manifest.json missing after assets precompile on production server

### ISSUE THREAD

**Issue by emclab** [rails/rails#20648]
Here is the production.rb in our rails 4.2.0 app:

  config.cache_classes = true
  config.eager_load = true
  config.consider_all_requests_local       = false
  config.action_controller.perform_caching = true
  config.serve_static_files = false #ENV['RAILS_SERVE_STATIC_FILES'].present?
  config.assets.compress = true
  config.assets.js_compressor = :uglifier
  config.assets.compile = false
  config.assets.digest = true
  config.log_level = :debug
  config.i18n.fallbacks = true
  config.active_support.deprecation = :notify
  config.log_formatter = ::Logger::Formatter.new
  config.active_record.dump_schema_after_migration = false

Our problem is that manifestxxx.json is missing after assets precompiie on production server (ubuntu 12.1) and there is no css available at all.

 RAILS_ENV=production bundle exec rake assets:precompile RAILS_RELATIVE_URL_ROOT=/mysuburi

There are manifest in the application.js and @import in application.css.scss. However there is no manifestxxx.json after assets precompile. If we set live compilation: config.assets.compile = true, then the css works. Since there are only a few params we can reset about assets and we have tried pretty much every one of them. More details is available at http://stackoverflow.com/questions/30925390/rails-4-manifest-json-missing-after-assets-precompile-on-production-server. Thanks.

**Comment by emclab** [comment]
The problem is solved by rolling back sprockets to version 2.12.3 from 3.2.0 and it corresponding tilt.

**Comment by emclab** [comment]
https://github.com/vigetlabs/gulp-rails-pipeline/issues/19

here is another issue reported with Rails 4.2.1 and sprockets 3.2.0. The cause of the problem may be the same with sprockets.

**Comment by emclab** [comment]
This may be a bug and leave it open.

**Comment by rafaelfranca** [comment]
In sprockets 3 this file is not called manifest.json, not it is called `.sprockets-abc123.json`. See the changelog for more information https://github.com/rails/sprockets/blob/master/CHANGELOG.md
