### ISSUE TITLE
state_machine no more maintained but have some stateS_machine on gem maintained...

### ISSUE THREAD

**Issue by jerome2** [rails/rails#20650]
So there is issuers on state_machine who never been resolved...
Why do you choose to keep legacy the state_machine no more maintained (and who has some bugs) instead of include the sates_machine gem and make it legacy one ?

Don't be hurt by the question, i'm sure there is a good technical reason to not offer users a maintained code inside the framework, but i lake of knowledge and just would like to understand why you not include some other works from gem community inside legacy part of the framework and particulary when there is anmaintained part inside and just some other works near that who provide solutions.

thanks for find the time to provide an explain.

**Comment by matthewd** [comment]
I don't know of any mention or endorsement of any state-machine gem, anywhere in the framework, its documentation, or guides.

I'm closing this for now, but if you can point to anywhere we do make such a statement, I'm sure we'd be glad to update (or remove) it.

**Comment by jerome2** [comment]
The link of this story started at gem 'the_comments'. After installed it i had a server error 500 when try to publicate a comment. Then i read issues around that and see hackers point on state_machine legacy no more maintained. Then one of the hackers product 'the_comment' find a little patch to add in users apps, an other one hackers works on an other state_machine named 'states_machine', but for use it, it is not the end user, but the hacker of a gem to hack with this states_machine (no legacy one, but maintained).
It's not to long time and to complicate to read around that, just go on gem rails web site, put 'the_comments' and after that 'states_machine', choose to read on github homepage for each => go read issues for the_comments and the patch, then go read 'states_machine' gem.
Tell me if something is not clear around state_machine (if it's clear and be able to provide an answer, i will be happy to read it).
thanks for your quick reply.
PS: if you really need i copy/paste what you can read by search this way (5 minutes really...) here, tell me, i will do for you.

**Comment by kaspth** [comment]
I don't understand your comment or how this has anything to do with Rails?

**Comment by jerome2** [comment]
@kaspth did you go to look at the_comments gem and try to install and use it ?
did you read the posts issues around error server 500 and stat_machine legacy from Rails ?
Because, "state_machine" is a part of Rails (that is the link for understand "hos this has anything to do with Rails". Or maybe i'm wrong... 
I'm wrong if when install Rails, state_machine is not an obligation installation (i think state_machine is installed whith Rails, but i'm not sure, and if not, so sure, my comment is out and i'm wrong).
Could you tell me if when install Rails, state_machine is needed by Rails ? (i not find information about that)

**Comment by matthewd** [comment]
> Because, i think (but maybe is false) that "state_machine" is a dependance need by Rails

No; state_machine has no relationship to Rails.

**Comment by jerome2** [comment]
ho well... that is why my coment is out of topic and stupid. sorry guys.
have a good day.

**Comment by kaspth** [comment]
No worries :heart:
