### ISSUE TITLE
proposal: deprecate save() in favor of save!()

### ISSUE THREAD

**Issue by pseidemann** [rails/rails#20662]
hello,

currently in rails you have two methods to save a record: `save` and `save!`.
I think `save` is often used wrong because the return value is not always checked. 
even the documentation is not very clear about the subtle different about the two methods. for `save` the first sentence is:
> Saves the model.

it's not clearly mentioned there that it will _not_ save the model at all when validation fails. so developers will introduce bugs when not always checking for the return value e.g. in delayed job methods or in rake tasks (or maybe even in controllers).

my proposal would be to deprecate the usage of `save` and introduce a new method called `try_save` which has the same implementation as the old `save` method. this would make the implementation and the usage of the saving method more clear.

what do you think?

**Comment by kaspth** [comment]
We reserve the issues tracker for issues only. Please use the Ruby on Rails core mailing list for feature requests. Thanks :heart:

**Comment by pseidemann** [comment]
added post to https://groups.google.com/forum/#!forum/rubyonrails-core
thx!
