### ISSUE TITLE
Rails 4.2.2 still includes Rack::Lock (even in production mode)

### ISSUE THREAD

**Issue by vincentwoo** [rails/rails#20660]
Hey Rails maintainers! Lately, I have been reading about the state of multithreading in Rails, and discovered that Discourse is still [manually deleting `Rack::Lock`](https://github.com/discourse/discourse/blob/28a0cb494ad901d648763372bc198aa9a3b6e393/config/application.rb#L101), even in Rails 4+.

Examining a fresh Rails 4.2.2 install:

```bash
$ rails new testlock
...
$ cd testlock
$ rake middleware
```

yields a list that still includes `Rack::Lock`

```
use Rack::Sendfile
use ActionDispatch::Static
*** use Rack::Lock ***
use #<ActiveSupport::Cache::Strategy::LocalCache::Middleware:0x007fd3f9c9f890>
use Rack::Runtime
use Rack::MethodOverride
use ActionDispatch::RequestId
use Rails::Rack::Logger
use ActionDispatch::ShowExceptions
use WebConsole::Middleware
use ActionDispatch::DebugExceptions
use ActionDispatch::RemoteIp
use ActionDispatch::Reloader
use ActionDispatch::Callbacks
use ActiveRecord::Migration::CheckPending
use ActiveRecord::ConnectionAdapters::ConnectionManagement
use ActiveRecord::QueryCache
use ActionDispatch::Cookies
use ActionDispatch::Session::CookieStore
use ActionDispatch::Flash
use ActionDispatch::ParamsParser
use Rack::Head
use Rack::ConditionalGet
use Rack::ETag
run Testlock::Application.routes
```

even attempting to run explicitly in production mode yields the same results:

```
$ RACK_ENV=production RAILS_ENV=production rake middleware

use Rack::Sendfile
*** use Rack::Lock ***
use #<ActiveSupport::Cache::Strategy::LocalCache::Middleware:0x007fbbf4c1c7a0>
use Rack::Runtime
use Rack::MethodOverride
use ActionDispatch::RequestId
use Rails::Rack::Logger
use ActionDispatch::ShowExceptions
use ActionDispatch::DebugExceptions
use ActionDispatch::RemoteIp
use ActionDispatch::Callbacks
use ActiveRecord::ConnectionAdapters::ConnectionManagement
use ActiveRecord::QueryCache
use ActionDispatch::Cookies
use ActionDispatch::Session::CookieStore
use ActionDispatch::Flash
use ActionDispatch::ParamsParser
use Rack::Head
use Rack::ConditionalGet
use Rack::ETag
run Testlock::Application.routes
```

Is this intended behavior? My cursory understanding is that having both `cache_classes` and `eager_loading` on should trigger multithreaded mode by default, and thus not cause `Rack::Lock` to be added to the stack. Am I mistaken?

**Comment by tamird** [comment]
There are two cases in which `Rack::Lock` is added to the middleware stack, and neither has anything to do with production mode:
1. If you're using WEBrick: https://github.com/rails/rails/blob/v4.2.2/railties/lib/rails/commands/server.rb#L99
2. If `allow_concurrency?` is falsey: https://github.com/rails/rails/blob/v4.2.2/railties/lib/rails/application/default_middleware_stack.rb#L29
  1. `allow_concurrency?` is either explicitly set: https://github.com/rails/rails/blob/v4.2.2/railties/lib/rails/application/default_middleware_stack.rb#L72
  2. or inferred from `cache_classes` and `eager_load` (as you describe): https://github.com/rails/rails/blob/v4.2.2/railties/lib/rails/application/default_middleware_stack.rb#L70

My guess is that you're using WEBrick.

**Comment by rafaelfranca** [comment]
Yes, exactly that.

**Comment by vincentwoo** [comment]
@rafaelfranca Upon further investigation, I am sure the problem is more complicated. I'm definitely *not* running WEBRick. Indeed, it should be impossible for `rake middleware` to even know what server I'm running, as the WEBRick check-code is only executed on `rails server` (it's in the commands folder)

I started instrumenting the railties bundle with some help from @tamird like so:

```ruby
# default_middleware_stack.rb
def allow_concurrency?
  p [config.allow_concurrency, config.cache_classes, config.eager_load] # this line added
  if config.allow_concurrency.nil?
    config.cache_classes && config.eager_load
  else
    config.allow_concurrency
  end
end
```

and then ran:

```
$ RACK_ENV=production RAILS_ENV=production rake middleware
[nil, true, false]
[nil, true, false]
use Rack::Sendfile
use Rack::Lock
use #<ActiveSupport::Cache::Strategy::LocalCache::Middleware:0x007fefd93888f0>
use Rack::Runtime
use Rack::MethodOverride
use ActionDispatch::RequestId
use Rails::Rack::Logger
use ActionDispatch::ShowExceptions
use ActionDispatch::DebugExceptions
use ActionDispatch::RemoteIp
use ActionDispatch::Callbacks
use ActiveRecord::ConnectionAdapters::ConnectionManagement
use ActiveRecord::QueryCache
use ActionDispatch::Cookies
use ActionDispatch::Session::CookieStore
use ActionDispatch::Flash
use ActionDispatch::ParamsParser
use Rack::Head
use Rack::ConditionalGet
use Rack::ETag
run Testlock::Application.routes
```

Which implies that the stack is seeing `eager_load` as false despite this line clearly setting it to true in `production.rb` by default:

```ruby
  # Eager load code on boot. This eager loads most of Rails and
  # your application in memory, allowing both threaded web servers
  # and those relying on copy on write to perform better.
  # Rake tasks automatically ignore this option for performance.
  config.eager_load = true
```

Can we reopen the issue?

**Comment by vincentwoo** [comment]
Ah, a quick test confirms that this is due to this line: https://github.com/rails/rails/blob/ebc4c607a7859c9c35246d7fe74a17208ef3a66e/railties/lib/rails/application.rb#L446

Is THAT bit intended? I'm not sure why it's there.

**Comment by rafaelfranca** [comment]
Yes, it is intended https://github.com/rails/rails/commit/9cac69c602f57e397fe01d866cb24ce1781606d4

**Comment by tamird** [comment]
@rafaelfranca seems like that should be reverted in light of this issue and the fact that initialize_on_precompile is no longer a thing.

**Comment by rafaelfranca** [comment]
So seems that it is being added only when running rake tasks, but not on the server.

**Comment by rafaelfranca** [comment]
@tamird it being a thing or not reverting it will make rake tasks to eager load and fail if the conditions listed on that issue happen

**Comment by vincentwoo** [comment]
What's a good fix? Should Rails therefore ship default apps with `allow_concurrency = true` turned on in `production.rb`? Having `rake middleware` lie to you all the time as a workaround for specific apps having trouble precompiling seems less than ideal.

**Comment by rafaelfranca** [comment]
A good fix would split the rake tasks that needs to load the environment respecting the eager loading and tasks that don't need to. So let say precompile tasks don't call `:environment` and call a specific parent task. Could you work on that?

**Comment by vincentwoo** [comment]
I could take a crack. Can you point at a few of the relevant files? Been a long time since I've had to poke around in Rails.

**Comment by rafaelfranca** [comment]
Besides reverting the change made to the file that you pointed, we should change this https://github.com/rails/sprockets-rails/blob/2.x/lib/sprockets/rails/task.rb#L64 to do exactly what the `:environment` task does right now.

**Comment by vincentwoo** [comment]
Fixed by https://github.com/rails/rails/pull/17102
