### ISSUE TITLE
belongs_to presence validation broken when creating from association and setting id to nil

### ISSUE THREAD

**Issue by oseiskar** [rails/rails#20670]
With a usual association featuring a presence validation,

    class Post < ActiveRecord::Base
      has_many :comments
    end

    class Comment < ActiveRecord::Base
      belongs_to :post
      validates :post, presence: true
    end

the following code passes without exceptions, saving the invalid record to the database:

    post = Post.create!
    comment = post.comments.create!
    comment.post_id = nil
    comment.save!

This does not happen if the second line is replaced with, e.g., `comment = Comment.create!(post: post)`. This bug does not appear in ActiveRecord 4.0.13, but is present in versions 4.2.2, 4.1.11 and master (as of today).

The executable test case: https://gist.github.com/oseiskar/38e09756902fbec211d0

**Comment by senny** [comment]
@oseiskar I'll have a look.

**Comment by senny** [comment]
@oseiskar as I see it, this is not really related to validation logic. What's happening is that the `_id`-writer does not have any affect on the associated object. Here's a sample to demonstrate that:

```ruby
    post = Post.create!
    other_post = Post.create!
    comment = post.comments.create!
    other_comment.post_id = post.id
    other_comment.post # => still points to `post`
```

This seems odd. I'll dig into the history and try to find out what patch changed this behavior.

**Comment by senny** [comment]
The above behavior changed between `4-0-stable` and `4-1-stable`. Specifically this PR #9499

The issue has been brought up in the past #18633. The decision was to keep the current behavior and rely on the use of association methods (eg. `post = nil`) than id-writers (eg. `post_id = nil`).

From the issue it looks like @sgrif has more context around that matter. I'll leave the decision up to him and keep the issue around for the time being.

/cc @rafaelfranca

**Comment by meinac** [comment]
@senny I think relying on only association writer method is unacceptable. How do you document this? This is a bug and I believe should be fixed. Every bug on rails hurt my hearth :broken_heart:

**Comment by sgrif** [comment]
I'm not opposed to fixing this, but as was summed up in https://github.com/rails/rails/issues/18633#issuecomment-74015197 there's currently no way to fix this that I can see without breaking other behavior. If we have a way to do so, by all means do it. However, given the current state of things, I think this bug is completely acceptable, as the association and the ID writer are two completely different levels of abstraction.

**Comment by rafaelfranca** [comment]
> I think this bug is completely acceptable, as the association and the ID writer are two completely different levels of abstraction.

:+1:
