### ISSUE TITLE
Missing documentation

### ISSUE THREAD

**Issue by xhoy** [rails/rails#20671]
Thanks for all great work on rails! its super awesome :) but today i found something in the documentation:

Since https://github.com/rails/rails/pull/13528 db:test:* have been deprecated.

Today i was following the edge guide http://edgeguides.rubyonrails.org/testing.html#maintaining-the-test-database-schema this still references the deprecated commands.

Since i am new to the testing stuff i haven't got a clue how this should work since the documentation is only referencing the old commands and old workflow?

**Comment by senny** [comment]
@xhoy thank you for reporting but `db:test:prepare` is an exception to that deprecation. While it's true that that command was deprecated for some time we removed the deprecation a while ago. The use-case described in the guide is valid and up-to-date.

Hope that helps.
