### ISSUE TITLE
it is nightmare to use rails on windows7 

### ISSUE THREAD

**Issue by chapgaga** [rails/rails#20675]
rails new xxx, and then failed ...

DL is deprecated, please use Fiddle
Fetching gem metadata from https://rubygems.org/............
Fetching version metadata from https://rubygems.org/...
Fetching dependency metadata from https://rubygems.org/..
Resolving dependencies...
Using rake 10.4.2
Using i18n 0.7.0

Gem::RemoteFetcher::FetchError: Errno::ECONNRESET: An existing connection was forcibly closed by the remote host. - SSL_connect (https://rubygems.org/gems/json-1.8.3.gem)
An error occurred while installing json (1.8.3), and Bundler cannot continue.
Make sure that `gem install json -v '1.8.3'` succeeds before bundling.

**Comment by matthewd** [comment]
Sorry, it sounds like you're having an issue with rubygems, which is well outside of our control.
