### ISSUE TITLE
Controller before_action callbacks are not appended

### ISSUE THREAD

**Issue by toncid** [rails/rails#20687]
Hello,

It seems that calling `before_action` multiple times for the same method overwrites calls from before.  Shouldn't `skip_before_action` be used to remove callbacks?

In the example below, the `check_roles` method will not be called for the `destroy` method.

Example concern:
```ruby
module DestroyObjectConcern
  extend ActiveSupport::Concern

  included do
    before_action :check_roles, only: :destroy
  end
end
```

Example controller:
```ruby
class ProductsController < ApplicationController
  include DestroyObjectConcern

  before_action :check_roles, only: [:create, :update]  # overwrites the call from the concern

  # def create/update/destroy...
end
```

**Comment by toncid** [comment]
The same thing happens without the concern:

```ruby
class ProductsController < ApplicationController
  before_action :check_roles, only: :destroy
  before_action :check_roles, only: [:create, :update]  # overwrites the first call

  # def create/update/destroy...
end
```

**Comment by fenec** [comment]
@toncid looking at implementation of `AbstractController::Callbacks`, it can be seen they are created using `define_method` so it's expected that next call will redefine the callback. so I guess it's expected behaviour

**Comment by rafaelfranca** [comment]
Yes, it is the expected behavior.

**Comment by toncid** [comment]
In that case it is not very well documented. It seems like you are binding callbacks to a chain independently of previous calls to the `before_action`.

**Comment by ToTenMilan** [comment]
I wasn't expecting such behaviour in case like this one:
```ruby
class ImportantObjectsController < ApplicationController
  before_action :authenticate_user!

  # low level user has access to index
  before_action :access_denied, unless: :low_level_user, only: [:index]
  # mid level user has access to index, show
  before_action :access_denied, unless: :mid_level_user, only: [:show]
  # high level user has access to index, show, create
  before_action :access_denied, unless: :high_level_user, only: [:create]

  def index/show/create
    (...)
end
```
At least good that documentation now states about it:

> Calling the same filter multiple times with different options will not work, since the last filter definition will overwrite the previous ones.

from [Guides](https://guides.rubyonrails.org/action_controller_overview.html#filters)

**Comment by TruePath** [comment]
This needs to be better documented.  I literally ended up here because I felt queasy about how callbacks worked in a concern and couldn't find it documented anywhere until I came here.

Merely saying that calling the same filter multiple times will not work isn't helpful.  For all the reader knows filter definitions in modules/super classes count as different filters if they occur in different modules/classes (e.g. super/sub classes).  

Heck, even reading this I'm not sure if this works the same way for superclasses.

**Comment by TruePath** [comment]
That's not very helpful documentation without some kind of indication of what it means to be the same filter.  I mean are filters with the same symbol but defined in different scopes (super classes) the 'same' filter.  What about filters with the same symbol but applied to different actions or filters that refer to the same method but via different aliases?

**Comment by phoet** [comment]
This can lead to hard to debug errors. Would be great if rails was not silently overwriting the callbacks but issuing some kind of warning that an action was registered multiple times and where those came from.

**Comment by motine** [comment]
I agree. I also stumbled upon this problem. @rafaelfranca, do you think this issue is worth looking at again (i.e. implement a warning)?
