### ISSUE TITLE
Rails 4.2.3.rc1 can't do rake db:drop:all

### ISSUE THREAD

**Issue by swaroopmurthy** [rails/rails#20685]
rake db:drop:all
rake aborted!
TypeError: CacheDigests is not a class
gems/actionview-4.2.3.rc1/lib/action_view/tasks/dependencies.rake:14:in `(root)'
gems/actionview-4.2.3.rc1/lib/action_view/tasks/dependencies.rake:1:in `(root)'
gems/activesupport-4.2.3.rc1/lib/active_support/dependencies.rb:1:in `(root)'
gems/activesupport-4.2.3.rc1/lib/active_support/dependencies.rb:240:in `load_dependency'
gems/activesupport-4.2.3.rc1/lib/active_support/dependencies.rb:268:in `load'
gems/activesupport-4.2.3.rc1/lib/active_support/dependencies.rb:268:in `load'
gems/actionview-4.2.3.rc1/lib/action_view/railtie.rb:46:in `Railtie'
gems/railties-4.2.3.rc1/lib/rails/railtie.rb:237:in `run_tasks_blocks'
gems/railties-4.2.3.rc1/lib/rails/railtie.rb:245:in `each_registered_block'
gems/railties-4.2.3.rc1/lib/rails/railtie.rb:237:in `run_tasks_blocks'
gems/railties-4.2.3.rc1/lib/rails/application.rb:451:in `run_tasks_blocks'
gems/railties-4.2.3.rc1/lib/rails/engine/railties.rb:13:in `each'
gems/railties-4.2.3.rc1/lib/rails/application.rb:451:in `run_tasks_blocks'
gems/railties-4.2.3.rc1/lib/rails/engine.rb:453:in `load_tasks'
gems/railties-4.2.3.rc1/lib/rails/railtie.rb:194:in `method_missing'

I'm on jruby and oracle_enhanced driver. But it does look like this stack trace has nothing to do with those things..

**Comment by rafaelfranca** [comment]
Something is defining a module called `CacheDigests` in your application. Could you check it?

**Comment by swaroopmurthy** [comment]
ag CacheDigests 
returns a blank line

**Comment by rafaelfranca** [comment]
So, some gem that you are using defines it.

**Comment by swaroopmurthy** [comment]
Are you sure [this](https://github.com/rails/rails/blob/v4.2.3.rc1/actionview/lib/action_view/tasks/dependencies.rake#L11) has nothing to do with it?

**Comment by rafaelfranca** [comment]
Yes, it has, but only because something else is defining the same constant as a module. We need to know what is doing this to do the right fix.

**Comment by swaroopmurthy** [comment]
cache_digests-0.3.1/lib/cache_digests/engine.rb
    module CacheDigests

I have this gem which defines CacheDigests as a module

**Comment by rafaelfranca** [comment]
You can remove this gem. It was added to Rails 4.0

**Comment by swaroopmurthy** [comment]
thanks! that did it. so I suppose it worked with rails4.2.1 because CacheDigests was still a module then?

**Comment by rafaelfranca** [comment]
It worked because we didn't have a `CacheDigest` constant

**Comment by PikachuEXE** [comment]
I suppose the gem `cache_digest` should have its version constraint updated

**Comment by chancancode** [comment]
I don't think that works, that would just lock people on an old veriosn of the gem right? 😄

**Comment by PikachuEXE** [comment]
Old version of `cache_digest` or `actionpack`?
I guess for `cache_digest`, adding `actionpack` => `<= 5` is fine?
Not sure about 4.x

**Comment by chancancode** [comment]
The problem is `cache_digest` gem is not necessary since Rails 4 and should be removed from the Gemfile. The "current" version is 0.3.1 with a `'actionpack', '>= 3.2'` constraint. I am inferring that you suggest we release a 0.3.2 with `'actionpack', '>= 3.2', '< 4'`, but it won't achieve the desired effect, because for people on Rails 4+ with this in their Gemfile, bundler would happily install 0.3.1 ("the last compatible version") for them.

**Comment by PikachuEXE** [comment]
Maybe print warning while installing / loading the gem?
