### ISSUE TITLE
Date.parse doesn't handle time_zone

### ISSUE THREAD

**Issue by pierrickrouxel** [rails/rails#20684]
I use rails as a backend for my javascript application.

My application is configured as this:
```ruby
config.time_zone = 'Paris'
config.active_record.default_timezone = :local
```

If I perform these commands, I can see that the same date can be parse to two differents.
```ruby
puts Date.parse('2015-06-21 22:00:00Z') # 2015-06-21
puts Date.parse('2015-06-22 00:00:00 GMT+2') # 2015-06-22
```

I think, with `config.time_zone= 'Paris'`, `2015-06-21 22:00:00Z` should be parsed to `2015-06-22`.

Javascript hasn't pure Date object. Dates are always delivered with time and time_zone. In this state when I try to save a date, it is generally set back 1 day.

**Comment by al2o3cr** [comment]
If you're getting complete time values as input, I'd recommend parsing them as such and then using `to_date`.

**Comment by pierrickrouxel** [comment]
Yes but if my table has a `date` column, rails do the parsing automatically and then it uses Date not Datetime. I think it should take care of the timezone.
