### ISSUE TITLE
jquery warning while using js request

### ISSUE THREAD

**Issue by adityashankert** [rails/rails#20686]
I am getting following warning while using js request

> Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience. For more help, check http://xhr.spec.whatwg.org/.

rails version - 4.1.8
jquery version - 1.10.2

**Comment by rafaelfranca** [comment]
Thank you for the issue. Are you sure this is related to Rails? How can I reproduce this warning?

**Comment by adityashankert** [comment]
This issue occurs when remote = true is used which means the issue with ajax implementation of rails

**Comment by rafaelfranca** [comment]
This issue was moved to rails/jquery-ujs#424
