### ISSUE TITLE
method 'url_for': given 3, expected 1

### ISSUE THREAD

**Issue by ryan2johnson9** [rails/rails#20680]
Just updated to Rails 4.2.2 so using actionpack 4.2.2. I'm on rbx 2.2.10 (but also tried with rbx 2.5.7)

I was getting error mentioned in title until I changed this line from
_actionpack (4.2.2) lib/action_dispatch/routing/route_set.rb:280:in `call'_
`t._routes.url_for(hash, route_name, url_strategy)`
to
`t._routes.url_for(hash)`

happens with any call to a url helper, I can get the error from rails console using `Rails.application.routes.url_helpers::users_path`
here is an example [backtrace](https://gist.github.com/ryan2johnson9/7dc31fde306a6be8cd84)

I have another application in 4.2.2 which works, so I'm a bit confused..

[Gemfile](https://gist.github.com/ryan2johnson9/23b068d64b0c8e41e675)
[Gemfile.lock](https://gist.github.com/ryan2johnson9/890870ccf78814ca963c)

**Comment by ryan2johnson9** [comment]
I just added a debug point just before the error in `actionpack (4.2.2) lib/action_dispatch/routing/route_set.rb:280:in call'` in both of my applications. The one that works, A,  and the one where I get this error, B.
I opened a console in both apps.
I do `Rails.application.routes.url_helpers::users_path` and it gets me to my debug line. Within the debug line I run
`Rails.application.routes.url_helpers.url_for(1,2,3,4)` in both
*result for A:*
`method 'url_for': given 4, expected 3 (ArgumentError)` - good - expects 3 args

    #<Module:0x40f80>.url_for at /home/ryan/.rvm/gems/rbx-2.5.7@rails4.2_communication/gems/actionpack-4.2.2/lib
    /action_dispatch/routing/route_set.rb:505
    { } in ActionDispatch::Routing::RouteSet::NamedRouteCollection::UrlHelper#call at /home/ryan/.rvm/gems/rbx-2.5.7@rails4.2_communication/gems/actionpack-4.2.2/lib
    /action_dispatch/routing/route_set.rb:1

*for B:*
`method 'url_for': given 4, expected 1` - bad - only expects one argument

backtrace:

    #<Module:0xbfba8>.url_for at /home/ryan/.rvm/gems/rbx-2.5.7@rails4.2_registration/gems/actionpack-4.2.2/lib
    /action_dispatch/routing/route_set.rb:505
    { } in ActionDispatch::Routing::RouteSet::NamedRouteCollection::UrlHelper(ActionDispatch::Routing::RouteSet::NamedRouteCollection::UrlHelper::OptimizedUrlHelper)#call at \
    /home/ryan/.rvm/gems/rbx-2.5.7@rails4.2_registration/gems/actionpack-4.2.2/lib/action_dispatch/routing/route_set.rb:1

The difference I see is that the backtrace in B has `UrlHelper(ActionDispatch::Routing::RouteSet::NamedRouteCollection::UrlHelper::OptimizedUrlHelper)#call` where the backtrace in A has `UrlHelper#call`. I wonder if this is some kind of caching...

**Comment by senny** [comment]
@ryan2johnson9 can you upload a sample application to GitHub that displays the issue? This will help us investigate the issue.

**Comment by pixeltrix** [comment]
@ryan2johnson9 closing this because it seems like Devise is involved in some way and we haven't heard anything for four weeks - if you have any more information please post it and I'll have a look.

**Comment by ryan2johnson9** [comment]
I've been away and busy and unsure of how to upload a sample application - know of any tutorials on how to do this? Anyway, when/if I get more time and motivation I'll look into it more and add a comment here.

**Comment by pixeltrix** [comment]
@ryan2johnson9 we have some templates for creating self-contained single file reproduction scripts - see [the guide][1] for details. Alternatively create a simple application using `rails new` and then publish it to a GitHub repo and post the url here.

[1]: http://guides.rubyonrails.org/contributing_to_ruby_on_rails.html#create-a-self-contained-gist-for-active-record-and-action-controller-issues

**Comment by robin850** [comment]
@ryan2johnson9 : I may be wrong but since you're running on Rubinius, you're maybe hitting rubinius/rubinius#3363.

**Comment by pixeltrix** [comment]
@robin850 I didn't see that this was on Rubinius, however I don't think we're using kwargs in that bit of the code yet especially on 4-2-stable.as we're still meant to be 1.9.3 compatible. I suspect that it is Rubinius at fault though so good catch.
