### ISSUE TITLE
Rails 4.2.2 maybe made it impossible to handle HEAD requests in a mounted engine

### ISSUE THREAD

**Issue by burnettk** [rails/rails#20688]
b9c63b0, via #18698, I suspect.

In my rails app's routes:

```` ruby
mount AppStatusApi::Engine => 'api/status'
````

In my app-status-api gem/engine's config/routes.rb:

```` ruby
AppStatusApi::Engine.routes.draw do
  # i'm using :all, but :head doesn't work any better
  match '/', to: 'status#status', defaults: { format: :json }, via: :all 
end
````

when i do this:

```` bash
curl -v -I localhost:3000/api/status
````

i get this in development.log:

````
Started HEAD "/api/status" for ::1 at 2015-06-24 11:22:20 -0400

ActionController::RoutingError (No route matches [HEAD] "/api/status"):
````

we ran into this while trying to apply the 4.2.2 security fixes in a bunch of apps. we can hack around it by adding this in every app's routes.rb:

```` ruby
 match '/api/status', to: 'app_status_api/status#status', defaults: { format: :json }, via: :all
````

**Comment by rafaelfranca** [comment]
Could you check 4.2.3.rc1?

**Comment by rafaelfranca** [comment]
It should be fixed on 4.2.3.rc1, if not please report back. Thanks

**Comment by burnettk** [comment]
you're right. my use-case is fixed in 4.2.3.rc1. thanks.

**Comment by danbob** [comment]
This fix seems to have broken HEAD requests in the main app when you have an engine mounted at '/'. Should I open a new issue?

**Comment by burnettk** [comment]
Are you still broken with 4.2.3.rc1, Dan?

**Comment by danbob** [comment]
Sorry, I should have been more clear. I've got a slightly different setup:
```ruby
Rails.application.routes.draw do
  get 'status', to: 'application#status' # meant to accept HEAD requests
  mount Some::Engine => '/'
end
```
so the route receiving the HEAD requests is in the main app, not the mounted engine. This was working in 4.2.2 but broke when I updated to 4.2.3. I had to use the same workaround as yours, replaced that line with
```ruby
match 'status', to: 'application#status', via: :all
```

**Comment by rafaelfranca** [comment]
@danbob had you check 4-2-stable?

**Comment by danbob** [comment]
Ah, 4-2-stable works.
