### ISSUE TITLE
Association nil with accepts_nested_attributes

### ISSUE THREAD

**Issue by jordanthomas** [rails/rails#20690]
Encountered some strange behavior with associations when a model `accepts_nested_attributes`.

Test file showing behavior:
https://gist.github.com/jordanthomas/e6cc3f7c2db773adeb7d

When a parent model with a `has_many` association `accepts_nested_attributes` the association from child to parent is nil. It came to our attention when removing the protected_attributes gem from a project. With it, this behavior did not exist.

``` ruby
c = Car.new
w = c.wheel.build
w.car # nil
```

I'd be happy to invest some time tracking this down further if someone can point me in the right direction.

**Comment by pascalbetz** [comment]
Looks like the association is only set when you _save_ the parent. Or if you add _inverse_of_ option to the _has_many_. Not sure if the difference with _nested_attributes_ is intended.

**Comment by jordanthomas** [comment]
Added a test to the gist above demonstrating how adding `inverse_of` to an association with `accepts_nested_attributes` effects the outcome.

https://gist.github.com/jordanthomas/e6cc3f7c2db773adeb7d

**Comment by mberning** [comment]
Ran tests provided in gist and received the failure

**Comment by tjshipe** [comment]
Same +1

**Comment by Rafe** [comment]
Looks related to #20451, accepts_nested_attributes make the association not able to inverse.

**Comment by ojab** [comment]
Reproducible also with `has_one` on current master.

**Comment by ojab** [comment]
[Up-to-date testcase with has_one added](https://gist.github.com/ojab/f4fe4448bcbaf5694184)

**Comment by ojab** [comment]
(I've tried to bisect this, it's reproducible on 3.0.3 and older versions are not so easy to install because of `bundler '~> 1.0'` dependency and alike)

**Comment by xhoy** [comment]
This bug is fixed with this commit: https://github.com/rails/rails/commit/c7adc610f0233b9afd51a6d68aa9061cdb250fad seems to be fixed in 5.1.rc3+?

**Comment by sgrif** [comment]
Confirmed that the provided reproduction script passes on master.

**Comment by sgrif** [comment]
Confirmed that the provided reproduction script passes on 5-1-stable.
