### ISSUE TITLE
A Guide to Testing Rails Applications: generate unit test if controller and/or model exist

### ISSUE THREAD

**Issue by kasiaul** [rails/rails#20694]
I did not find this information in documentation but often facing projects without tests I think it is very useful information:

rails g test_unit:scaffold user
It will generate controller test with filled all usual actions.
      create  test/controllers/users_controller_test.rb

rails g test_unit:model user
      create  test/models/user_test.rb
      create  test/fixtures/users.yml

**Comment by jvanbaarsen** [comment]
@rafaelfranca Would be great if you can add the `doc` label :yellow_heart:
