### ISSUE TITLE
Rails Guides: Generated migration different than one shown in guide

### ISSUE THREAD

**Issue by onebree** [rails/rails#20705]
**Rails 4.2.2**

http://guides.rubyonrails.org/getting_started.html#generating-a-model

I ran the rake command to create a Comment model and migration. The guide says the migration should look like (without the comments, of course):

```ruby
class CreateComments < ActiveRecord::Migration
  def change
    create_table :comments do |t|
      t.string :commenter
      t.text :body
 
      # this line adds an integer column called `article_id`.
      t.references :article, index: true
 
      t.timestamps null: false
    end
    add_foreign_key :comments, :articles
  end
end
```

However, my migration does not include the last line:
```ruby
class CreateComments < ActiveRecord::Migration
  def change
    create_table :comments do |t|
      t.string :commenter
      t.text :body
      t.references :article, index: true, foreign_key: true
 
      t.timestamps null: false
    end
  end
end
```

On the master branch, the [guide](https://github.com/rails/rails/blob/master/guides/source/getting_started.md#generating-a-model) has the same code block as me. While 4.2 Stable is the current guide posted online.

**Comment by onebree** [comment]
I would like to note: After running the migration, the schema's diff not show any created foreign keys. I do not know if they were supposed to be created. In the mean time, I am rolling back my migration and using the class provided from the Rails Guides.

**Comment by vijaydev** [comment]
Yes, this was changed in master recently. https://github.com/rails/rails/commit/79da9804482ab8357c24c7d62a9faa403acee655. 

What guides.rubyonrails.org shows is as per the latest stable release version (4.2.3), which has the explicit  `add_foreign_key` call. https://github.com/rails/rails/blob/4-2-stable/guides/source/getting_started.md

The `foreign_key: true` change made in the guide on master branch should be available in edgeguides.rubyonrails.org which I see is not the case. Pinging @fxn to check if the edge guides generation has any problems.

**Comment by onebree** [comment]
@vijaydev If I am using Rails 4.2.2, then why was my migration class different than from the Rails Guides? When I ran both migrations, neither seemed to create a foreign key for comments>articles in the schema. I am using the recommended SQLite3.

**Comment by fxn** [comment]
@vijaydev yep, I see a problem with a locally generated *Gemfile.lock* that prevents pulling. Going to investigate what's going on.

**Comment by fxn** [comment]
This is why https://github.com/bundler/bundler/issues/3697. I see [Bundler 1.10 does not have this issue](http://bundler.io/blog/2015/06/24/version-1-10-released.html#bundled-with).

**Comment by fxn** [comment]
@vijaydev fixed!

**Comment by vijaydev** [comment]
@onebree the guide was not updated when the change was introduced. I've now updated the guide in 4-2-stable https://github.com/rails/rails/commit/eeed8ab7d27b6bccf0a4253c35389cf795d55420 and this will reflect in guides.rubyonrails.org when 4.2.4 or 5.0.0 comes out.

**Comment by vijaydev** [comment]
@fxn :+1:

**Comment by onebree** [comment]
@vijaydev thank you very much!
