### ISSUE TITLE
Rails scopes generating invalid scope type messages.

### ISSUE THREAD

**Issue by JonRowe** [rails/rails#20700]
Since upgrading to 4.2.2 I've received a few random occurrences of:

> Invalid scope type '' sent to the registry. Scope types must be included in VALID_SCOPE_TYPES

They don't appear to come from one particular place and I'm not doing anything particularly custom with my scopes, so I'm not sure what I can do to resolve this...

**Comment by JonRowe** [comment]
Sample stack traces can be found here: https://gist.github.com/JonRowe/d1440b1ab1261a7ea271

**Comment by christophemaximin** [comment]
Can you please post the model `my_model` ?

**Comment by sgrif** [comment]
Please provide a script we can use to reproduce your issue, using [this template](https://github.com/rails/rails/blob/master/guides/bug_report_templates/active_record_master.rb) as a starting point.

**Comment by JonRowe** [comment]
I'm still getting these in production so I'll try! But I'm in transit half way around the world this weekend so it'll be next week sometime hope thats ok.

**Comment by JonRowe** [comment]
I haven't been able to reproduce this in a small script on my machine, but it's still occurring sporadically in production. The pattern is always the same however, the key sent is somehow lost when being sent through `ActiveSupport::PerThreadRegistry` to the underlying scoping implementation, I'm wondering if this is related to https://bugs.ruby-lang.org/issues/11153 someone

**Comment by sgrif** [comment]
Unfortunately, without a way to reproduce the issue, there's nothing we can do. This doesn't appear to be a bug with Rails. If you find any more information in the future feel free to comment here.

**Comment by JonRowe** [comment]
Monkey patch active record it is then.

**Comment by JonRowe** [comment]
If anyone else runs into this, my solution is going to be to define the singleton method directly rather than relying on method_missing to automatically cache it later on, I think that will avoid the issue I'm seeing.

**Comment by brianjlandau** [comment]
I've experienced this too, sporadically with no predictability or reproducibility as far as I can tell. Never happens in tests or development and given what @JonRowe said above I'm guessing it's a multiple thread related issue. The full error message I get is also `ArgumentError: Invalid scope type '' sent to the registry. Scope types must be included in VALID_SCOPE_TYPES`

The last few lines of the backtrace is:

```
activerecord-4.2.3/lib/active_record/scoping.rb:82 in raise_invalid_scope_type!
activerecord-4.2.3/lib/active_record/scoping.rb:68 in value_for
activesupport-4.2.3/lib/active_support/per_thread_registry.rb:47 in public_send
activesupport-4.2.3/lib/active_support/per_thread_registry.rb:47 in block in method_missing
activerecord-4.2.3/lib/active_record/scoping.rb:14 in current_scope
```

Looking at the code https://github.com/rails/rails/blob/v4.2.3/activerecord/lib/active_record/scoping.rb#L14 it seems likely due to some threading related issue. The first parameter `:current_scope` being sent to `ScopeRegistry.value_for` is "disappearing" because the message has that empty string.

While this may not be a problem with Rails code and instead a threading issue in Ruby, it would still be nice to get a workaround. Plus, given it's a known issue seems like it would be worth addressing in some way, even if that isn't a code change.

If someone can think of a good way to test and reproduce threading related issues like this that would helpful.

Finally, since it's a threading related issue I will mention I'm using Unicorn 4.9.0 as my app server.

**Comment by JonRowe** [comment]
Yep that was what was happening to me too @brianjlandau, except I believe it's nil due to the symbol being GC'd on 2.2.2 (hypothesis only, still unable to replicate locally) similarly I'm using Unicorn as my app server.

FWIW this patch has fixed it:
```Ruby
module ActiveRecord
  module Scoping
    class ScopeRegistry # :nodoc:

      def self.value_for(scope_type, variable_name)
        instance.value_for(scope_type, variable_name)
      end

      def self.set_value_for(scope_type, variable_name, value)
        instance.set_value_for(scope_type, variable_name, value)
      end

    end
  end
end
```

**Comment by sgrif** [comment]
While I'm not doubting that this bug, there is literally nothing I can do without a script to reproduce it. I realize that this might be frustrating, but saying you're having the issue without a repro script is not particularly helpful here.

**Comment by JonRowe** [comment]
It's all good, just providing the information for other people encountering this issue; in the hope that if they search for the error they'll come across this Github issue and it will be helpful to them! Either by just highlighting it's existence elsewhere, or allow them to fix it with the patch themselves. I'm confident at this stage the issue is due to the use of `define_singleton_method` and a bug in Ruby causing the symbol to disappear (possibly being GC'd like I mentioned).

It's unfortunate this is proving hard to track down in an isolated fashion but so far there is a fix, and it'd also only be a minor refactoring of the component involved (I would say an improvement to the code style given my own dislike of using `method_missing` when I can be explicit but I'm not a maintainer of Rails :))

I will keep trying to reproduce it in a script but my time for this issue is limited at the moment :)

**Comment by sgrif** [comment]
I understand completely. Since this has drifted away from "how Rails can fix this issue", and I'm getting emailed when people comment, I'm going to unsubscribe. If any future readers believe they have relevant information, please ping me or contact me directly.

**Comment by quentindemetz** [comment]
I'm running into this sporadically as well.

**Comment by hennevogel** [comment]
@JonRowe did you ever follow up on this with the ruby peepz why/if this is GC'd?

**Comment by JonRowe** [comment]
No because I think it's a derivative of a known bug

**Comment by byroot** [comment]
Is anyone having this issue not running MRI 2.2.x ?

**Comment by yjukaku** [comment]
In case this helps, I'm having the same issue running Rails 4.2.3 on `ruby 2.2.2p95 (2015-04-13 revision 50295) [x86_64-linux]`

**Comment by techsethi** [comment]
+1 Getting this issue sporadically. rails 4.2.4 ruby 2.2.2p95
