### ISSUE TITLE
asset_path(...) returns the plain path without the fingerprint 

### ISSUE THREAD

**Issue by GildedHonour** [rails/rails#20703]
I precompiled the assets locally and uploaded them to S3 (I'm not using CloudFront for now) and then setup my app this way:
```
  config.assets.digest = true
  config.assets.enabled = true
  # config.assets.compile = true
  config.assets.compile = false
  
  config.assets.compress = true
  # config.serve_static_assets = false
  # config.serve_static_files = false 
  config.action_controller.asset_host = "https://s3.amazonaws.com/my-bucket"
```

And here's my asserts.rb:
```
Dir.glob("#{Rails.root}/app/assets/images/**/").each do |path|
  Rails.application.config.assets.paths << path
end

Dir.glob("#{Rails.root}/app/assets/javascripts/**/").each do |path|
  Rails.application.config.assets.paths << path
end

Dir.glob("#{Rails.root}/app/assets/stylesheets/**/").each do |path|
  Rails.application.config.assets.paths << path
end

Dir.glob("#{Rails.root}/app/assets/fonts/**/").each do |path|
  Rails.application.config.assets.paths << path
end
```

I have a lot of subdirectories for images as a photo gallery. These images are static - I only have to upload them once. And the paths they're located are similar:

```
gallery/subdir1/small/my_image-1.jpg
gallery/subdir1/medium/my_image-1.jpg
gallery/subdir1/large/my_image-1.jpg
```

After precompiling they exist in ```public/assets``` and in ```public/assets/manifiest.json``` and on Amazon S3 too under the same path.

The issue I have is that the images from this gallery (in subfolders) don't get  the fingerprint appended to their paths when I call `asset_path` 

```div data-src="#{asset_path('assets/gallery/small/my_image-1.jpg')}" data-min-width="700"```

resolves to 

```
https://s3.amazonaws.com/my-bucket/assets/gallery/small/my_image-1.jpg
```

(**without the fingerprint**), whereas the file `https://s3.amazonaws.com/my-bucket/assets/gallery/small/my_image-1-<md5hash>.jpg` **does exist on S3**

I've already recompiled and re-uploaded them to S3  a few times using s3cmd and I'm not using the gem asset_sync.

For now I'm deploying to Heroku to a free account and here's my gitignore:

```
.....

/app/assets/

public/assets/*
!public/assets/*.json
!public/assets/favicon/*.json
```

What can be the problem?

**Comment by rafaelfranca** [comment]
You are prefixing with `assets`, so Rails think you are giving the production path.

**Comment by GildedHonour** [comment]
And it's a production path because locally I launch it as "rails s -e production"

**Comment by rafaelfranca** [comment]
You should not use `assets` as prefix for your urls. Try `asset_path('gallery/small/my_image-1.jpg')`

**Comment by GildedHonour** [comment]
@rafaelfranca the images **are** located on "assets" in their paths. For example, the one of the full valid paths is `https://s3.amazonaws.com/my-bucket/assets/gallery/set-3/large/something-cdb63c93c928600db36c620055571f6f.jpg`

**Comment by rafaelfranca** [comment]
Yes, I know, but you don't need to pass `assets` in the URL. Rails does this automatically.

**Comment by GildedHonour** [comment]
@rafaelfranca  Thank you. On reddit and SO no body could answer this for 1 or 2 days, and here I got  help while I editing my question after submitting it for the first time. Awesome.

**Comment by rafaelfranca** [comment]
:+1:

**Comment by Jwan622** [comment]
I notice a similar bug... Rails doens't seem to prepend `assets` to my asset_path path in production. Anyone know why? It also isn't digesting the image. What gives? Any thoughts on why this might be?

**Comment by ChalkyBrush** [comment]
Still having this problem. Removing the 'assets' prefix does not solve the issue

**Comment by mvz** [comment]
@Jwan622 this may happen when Rails can't find the asset. It falls back to using the path as given in that case.
