### ISSUE TITLE
custom @locking_column is *not* being inherited by subclasses

### ISSUE THREAD

**Issue by dzajic** [rails/rails#20702]
Not sure if this is a bug or not, but it seems like a subclass should get its parent's locking_column by default, if not always. Would it ever make sense to use a different one?

Here's a test I propose adding to activerecord/test/cases/locking_test.rb:

    def test_custom_lock_with_sti_gets_parent_column
      c1 = Class.new(LockWithCustomColumnWithoutDefault)
      assert_equal LockWithCustomColumnWithoutDefault.locking_column, c1.locking_column,
        'Subclass should have the same :locking_column as the parent'
    end

If this is not a bug, doing this in my parent class seems to work:

    def self.inherited(child)
      child.locking_column = locking_column
    end

Do you see anything wrong with doing that?

**Comment by dzajic** [comment]
FTR, I ended up using the default locking column, because it turns out I didn't *need* a custom column name after all, but I'm still curious if anyone thinks this is a bug or not. The few people I've talked to on my team seem to think it is. It's probably just a case of obscurity, and very few people out there using STI, optimistic locking, and a custom locking column. And anyone that did probably just set the column in each subclass after they looked into the Rails source and got scared. ;-)

**Comment by sgrif** [comment]
The locking column should be inherited by child classes. If it isn't, please provide a reproducible test case using [this template](https://github.com/rails/rails/blob/master/guides/bug_report_templates/active_record_master.rb)

**Comment by sgrif** [comment]
Looks like the code isn't intended to inherit locking columns. This seems like a reasonable feature request, though. Feel free to submit a PR, or to propose it on the [Rails Core Mailing List](https://groups.google.com/forum/#!forum/rubyonrails-core), which is where we handle feature requests. The issues tracker is reserved only for bugs.

**Comment by dzajic** [comment]
Thanks, @sgrif, I'll consider it. At least this issue will be here in case anyone else runs into the same issue.
