### ISSUE TITLE
Rails 4.2.3 possible regression with has_many, order, and through

### ISSUE THREAD

**Issue by tovodeverett** [rails/rails#20719]
I have a vague recollection that somewhere between Rails 3.2.* and Rails 4.2.* there have been changes back and forth on the behavior of chained calls to order for ActiveRecord.  For instance, does `order(:foo).order(:bar)` order first by `foo` and then by `bar`, or vice-versa.

In any event, it appears that there has been a behavioral change between Rails 4.2.2 and 4.2.3 on this issue.

First, I'm going to roughly lay out the applicable parts of my model hierarchy:

* `Roll`: This represents a roll of photos.  It has an `id`, a `name`, etc.
* `Photo`: This represents a single photo, and each `Photo` belongs to one and only one `Roll`.  Each has an `id`, a `roll_id`, an `idx` that represents its ordinal position within the `Roll`, etc.
* `Pset`: This represents a set of individual photos from one or more rolls.  It has an `id`, a `name`, etc.
* `Pset_Photo`: This represents a photo that is a member of a `Pset`.  It has an `id`, a `pset_id`, a `photo_id`, and an `idx` that represents its ordinal position within the `Pset`.

On the `Pset` model, I have historically had code like this:
```
  has_many :pset_photos, -> { order('idx') }, dependent: :destroy, inverse_of: :pset
  has_many :photos, -> { order('pset_photos.idx') }, through: :pset_photos
```

The SQL generated for `:pset_photos` and `:photos` under Rails 4.2.2 looks like so:
```
SELECT "pset_photos".* FROM "pset_photos" WHERE "pset_photos"."pset_id" = $1  ORDER BY idx
SELECT "photos".* FROM "photos" INNER JOIN "pset_photos" ON "photos"."id" = "pset_photos"."photo_id" WHERE "pset_photos"."pset_id" = $1  ORDER BY pset_photos.idx, idx
```
Inspecting that, one notices that precedence in PostgreSQL is the root of some of this interesting behavior.  If one removes the order call in `:photos`, look at the SQL:
```
SELECT "photos".* FROM "photos" INNER JOIN "pset_photos" ON "photos"."id" = "pset_photos"."photo_id" WHERE "pset_photos"."pset_id" = $1  ORDER BY idx
```
There are two `idx` fields that PostgreSQL could choose to order on, one in `photos` and one in `pset_photos`.  PostgreSQL chooses to order by the one in `photos` because it interprets `idx` as applying to the output field names from the SELECT clause rather than interpreting it as applying to the tables in the FROM clause (in which case the ORDER BY would be indeterminate).  This means that the meaning of the order imposed by the `:pset_photos` relation is being silently redirected.  In the `:pset_photos` relation the order is on the `idx` field in the `pset_photos` table, whereas in the `:photos` relation the order is on the `idx` field in the `photos` table.  Interesting!

When I upgraded to 4.2.3, my test suite had one failure, and it was on the verification of the order for the `:photos` relation.  Using the historical code, I got the following SQL:
```
SELECT "photos".* FROM "photos" INNER JOIN "pset_photos" ON "photos"."id" = "pset_photos"."photo_id" WHERE "pset_photos"."pset_id" = $1  ORDER BY idx, pset_photos.idx
```
Notice how in 4.2.2, the order imposed by the `:photos` relation took precedence over the one imposed by the `:through` relation, but in 4.2.3 they chain so that the `:pset_photos` order has precedence.  Since the `:pset_photos` order is on `idx`, it applies to the `:idx` field in the `photos` table, and I don't get the desired ordering.  In fact, there is no way to override the ordering imposed by the `:pset_photos` relation, and since that ordering is getting misinterpreted by PostgreSQL based on it's rules for binding precedence in ORDER BY clauses, I'm sort of in a pickle.

Except that there's a get-out-of-jail card.  Apply the `pset_photos.idx` ordering in the `:pset_photos` relation.  In that case, I don't need any ordering on the `:photos` relation, the code behaved identically in both versions, and everything is grand.  I probably should have done this from the beginning, but I didn't understand the root problem until this change made it evident and I looked at the actual SQL.

I'd be happy with this Issue getting closed with a 'this is by design', but I have two requests first:
* Verify that it was intentional that the behavior of chained order calls changed from 4.2.2 to 4.2.3
* Consider whether the column occlusion issue in chained relations that allows the meaning of a order call on the base relation to change when it is used as a `:through` should be addressed somehow.  Unfortunately, the only reliable way to address it is to auto-scope the order to the table on the base relation, and I'm not sure if there's a robust way to do that.  Perhaps a documentation note would be a better solution.

Thanks!

**Comment by rafaelfranca** [comment]
Could you create a reproduction script with this template https://github.com/rails/rails/blob/master/guides/bug_report_templates/active_record_gem.rb?

**Comment by tovodeverett** [comment]
I believe this [Gist](https://gist.github.com/tovodeverett/51c20888616bc0702ffa) demonstrates the issue.  When run under 4.2.2, there is no failure.  When run under 4.2.3, there is a failure.

**Comment by sgrif** [comment]
This was fixed by https://github.com/rails/rails/commit/449241cc30545783419bd8f3cbc7b81137316001

**Comment by tovodeverett** [comment]
I can confirm that 4-2-stable resolves this issue.  Thanks!
