### ISSUE TITLE
Images in Mailer Preview still fail in Rails 4.2.3

### ISSUE THREAD

**Issue by davenguyen** [rails/rails#20713]
This is in reference to [#14435](https://github.com/rails/rails/issues/14435).

The **actionmailer-4.2.3 gem** needs [this one line of code](https://github.com/rails/rails/blob/master/actionmailer/lib/action_mailer/preview.rb#L24) to work

Correct on master: `self.preview_interceptors = [ActionMailer::InlinePreviewInterceptor]`
Incorrect on gem: `self.preview_interceptors = []`

Confused why it wasn't changed, as everything else on [this commit](https://github.com/rails/rails/commit/faaed863dd374b6c3c3ee0e317ed213edce1dd4d) was committed.

**Comment by rafaelfranca** [comment]
See https://github.com/rails/rails/blob/4-2-stable/railties/CHANGELOG.md#rails-423-june-25-2015.

> The interceptor is not enabled by default but can be done in an initializer:
