### ISSUE TITLE
Rails 4.2.3 controller tests parse RSS responses as HTML not XML

### ISSUE THREAD

**Issue by tomhughes** [rails/rails#20710]
A side effect of https://github.com/rails/rails/commit/4be3997c9f317e4295421d31204a31962206b55c is that responses of type `application/rss+xml` are now parsed as HTML instead of XML which then leads to test failures.

**Comment by rafaelfranca** [comment]
What is the mime object created for this type?

**Comment by tomhughes** [comment]
It's `Mime::RSS`.

**Comment by tomhughes** [comment]
Although it didn't affect my tests `Mime::ATOM` which expands to `application/atom+xml` will have the same problem.

**Comment by rafaelfranca** [comment]
It affects `Mime::RSS` but not `Mime::ATOM`?

**Comment by tomhughes** [comment]
No I just don't have any tests that test ATOM or they don't do anything that happens to be affected.

**Comment by sgrif** [comment]
Fixed by #20715
