### ISSUE TITLE
ActionDispatch response headers for status code 205

### ISSUE THREAD

**Issue by lazylester** [rails/rails#20729]
In the file lib/action_dispatch/http/response.rb, a constant called NO_CONTENT_CODES has a list of status codes for which the CONTENT_TYPE header should be deleted.

There is similar behaviour in Rack, (see the commit https://github.com/rack/rack/commit/2c5b076aaba6c83ffce8c6c2b5c49085c1abb5a5), but they have included the 205 response code. I believe this is the correct and desirable behaviour and that the NO_CONTENT_CODES list in ActionDispatch::Response should be changed from [204, 304] to [204, 205, 304].

Note that in Rack, they also remove the CONTENT_LENGTH header for status code 205. I don't know if this is the correct behaviour, but I imagine that the Rack folks thought so.

If there is agreement that this change should be made, I'll submit a PR.

**Comment by matthewd** [comment]
[RFC7231 6.3.6](https://tools.ietf.org/html/rfc7231#section-6.3.6):

> Since the 205 status code implies that no additional content will be provided, a server MUST NOT generate a payload in a 205 response.  In other words, a server MUST do one of the following for a 205 response: a) indicate a zero-length body for the response by including a Content-Length header field with a value of 0; b) indicate a zero-length payload for the response by including a Transfer-Encoding header field with a value of chunked and a message body consisting of a single chunk of zero-length; or, c) close the connection immediately after sending the blank line terminating the header section.

and [3.1.1.5](https://tools.ietf.org/html/rfc7231#section-3.1.1.5) (emphasis mine):

> A sender that generates a message **containing a payload body** SHOULD generate a Content-Type header field in that message

---

Agreed. It seems pointless, at best, for us to include a Content-Type for a 205 -- and inconsistent for us to not actively suppress the body.

The above also seems to clearly state that Rack's no-Content-Length-allowed behaviour is wrong; if you're interested, a PR to fix that would be welcome too. (It seems to just be a consequence of https://github.com/rack/rack/pull/221 adding 205 to the other no-content responses -- [1xx and 204 do indeed carry a MUST NOT prohibition](https://tools.ietf.org/html/rfc7230#section-3.3.2).)

**Comment by lazylester** [comment]
By way of context, and for the benefit of future googlers, I'll mention here that suppression of the Content-Type header and body content is required in order for jQuery.ajax to receive a 205 without error. Perhaps jQuery could be more defensive in its strategy here, but it's hard to claim that it's non-conformant with the rfc. So a fix in ActionDispatch::Response is appropriate.

A workaround is to redefine the NO_CONTENT_CODES array in an initializer:
````
ActionDispatch::Response.send(:remove_const, :NO_CONTENT_CODES) 
ActionDispatch::Response::NO_CONTENT_CODES = [204, 205, 304]
````

**Comment by matthewd** [comment]
> it's hard to claim that it's non-conformant with the rfc

FWIW, I'll go ahead and do just that: from your description, jQuery's behaviour is non-conformant with the RFC.

From what I found above (and reading some of the related sections), I found no prohibition on supplying a Content-Type header with a 205, as long as the so-typed body has a length of zero. It obviously doesn't seem terribly *useful*, but as far as I can see, you're describing jQuery choking on an entirely legal HTTP response.

If we stop doing the pointless thing, however, I guess it doesn't really matter either way. :smile:

**Comment by lazylester** [comment]
It's possible that my suggested change is a fix for a problem elsewhere in Rails. But I don't know where, perhaps you have some idea? But it's actually not pointless to fix ActionDispatch, and jQuery is choking b/c Rails is improperly sending content in a 205.

My controller action is:
````
render :nothing => true, :status => 205
````

If 205 is not included in the NO_CONTENT_CODES array, Rails responds with headers including:
````
Content-Type: text/plain; charset=utf-8
Content-Length: 1
````
If 205 is included in the NO_CONTENT_CODES array, Rails response does not have a Content-Type header, and headers include:
````
Content-Length: 0
````

**Comment by michielboekhoff** [comment]
I'm not able to replicate this behaviour with Rails 5.0.0.alpha using jQuery 1.11.2 and 2.1.3 (through jquery-rails). Rails correctly sets the Content-Length header to be 0, in accordance with the RFC. In addition, it also sets the Content-Type header and jQuery (again, as per the RFC) correctly handles this.
