### ISSUE TITLE
root path issues when server is run as a daemon

### ISSUE THREAD

**Issue by brewster1134** [rails/rails#20723]
i have several views, as well as some gems, that access the filesystem.  this seems to work fine until i run the server as a daemon. _rails (4.2.3)_

__for example__ in one of my views I access the README file in the root of the app

```ruby
File.read('README.md')
```

when running as a daemon, i get the error `No such file or directory @ rb_sysopen - README.md`

the error page shows the Rails.root path, which is correct.  i CAN fix this problem by doing:
```ruby
File.read("#{Rails.root}/README.md")
```

however this issue breaks more than just my views. It would seem an issue with the rails server.

**Comment by matthewd** [comment]
Please use the mailing list or StackOverflow for questions/help, where a wider community will be able to help you. We reserve the issues tracker for issues only.

**Comment by brewster1134** [comment]
Sorry for the confusion. I thought perhaps this might be an issue with rails. Shouldnt the rails server retain the `pwd` for the daemon process?

**Comment by brewster1134** [comment]
Taking a step back.. it makes sense the daemon should run without understanding the context it is running in. I guess it's more appropriate to file issues with the gems that throw the errors.
