### ISSUE TITLE
Outdated rubyonrails.org, messy blog

### ISSUE THREAD

**Issue by alpracka** [rails/rails#20725]
Hi,

I wrote similar thing to the google group but my post wasn't approved at all. I used to come to rubyonrails.org to check what is the current version of RoR. That information haven't been updated for a months.

Weblog.rubyonrails.org is so messy I can't recognize where a new post starts and where ends. Today I can see the new version 4.2.3 was released but I missed 4.2.2 totally.

The (official?) https://twitter.com/rubyonrails outdated also.

I don't want to hate but it is a pity. It doesn't look good for beginners at least.

So if there is a way how to contribute to the official site and blog (github?), please tell me. Also, I would be thankful for solid information source when the new version of RoR comes out.

**Comment by matthewd** [comment]
> So if there is a way how to contribute to the official site and blog (github?), please tell me.

[rails/rails.github.com](https://github.com/rails/rails.github.com), [rails/weblog](https://github.com/rails/weblog)

> Also, I would be thankful for solid information source when the new version of RoR comes out.

As you've noticed, the main website doesn't always keep up with releases. :confused:

There are a few places that generally do a better job, though:

[rubyonrails-core](https://groups.google.com/forum/#!topic/rubyonrails-core/g2eiwIW8uJY), [rubyonrails-talk](https://groups.google.com/forum/#!topic/rubyonrails-talk/g2eiwIW8uJY)
https://twitter.com/rails
http://weblog.rubyonrails.org/
https://rails-weekly.ongoodbits.com/
https://rubygems.org/gems/rails
