### ISSUE TITLE
ActiveRecord: order direction ignored when using #last

### ISSUE THREAD

**Issue by hotgazpacho** [rails/rails#20731]
When using `#order` and `#last` to fetch a single record record ordered by the `created_at` column in descending order, `#last` honors the sort column, but not the direction.

```
# INCORRECT: Order direction ignored, single result fetched
Document.order(created_at: :desc).last
#=> SELECT  "documents".* FROM "documents"  ORDER BY "documents"."created_at" ASC LIMIT 1

# INCORRECT: Order direction ignored, single result fetched
Document.order('created_at desc').last
#=> SELECT  "documents".* FROM "documents"  ORDER BY created_at ASC LIMIT 1

# CORRECT: Order direction honored, and single result fetched
Document.order(created_at: :desc).limit(1).last
#=> SELECT  "documents".* FROM "documents"  ORDER BY "documents"."created_at" DESC LIMIT 1
```

This is in ActiveRecord 4.2.2, using the Postgres adapter (0.18.1).

**Comment by matthewd** [comment]
This is expected behaviour; the order direction is being honored, not ignored. You want the last record: we're doing that by reversing the order, then grabbing the first.

**Comment by hotgazpacho** [comment]
Well, at the very least, [the documentation for this](http://api.rubyonrails.org/classes/ActiveRecord/FinderMethods.html#method-i-last) is very confusing. In fact, one of the examples explicitly supplies a direction in the order, but is unclear about what the expected results will be:

```
Person.last # returns the last object fetched by SELECT * FROM people
Person.where(["user_name = ?", user_name]).last
Person.order("created_on DESC").offset(5).last
Person.last(3) # returns the last three objects fetched by SELECT * FROM people.
```

**Comment by hotgazpacho** [comment]
And really, take a look at the SQL that is being generated:

```sql
SELECT  "documents".* FROM "documents"  ORDER BY "documents"."created_at" ASC LIMIT 1
```

That will NOT pull back the most recently created document. It will, in fact, pull back the oldest document.

**Comment by matthewd** [comment]
`Document.order(created_at: :desc)` == "all documents, in `created_at` order, **newest to oldest**"

The last one of those is the oldest. No?

**Comment by hotgazpacho** [comment]
What I am saying is that, given the documentation, I found that behavior of `#last` surprising. It would be helpful if the documentation made it clear what is going on when you supply an `order` clause.
