### ISSUE TITLE
Rails.cache.fetch is active in spite of ActionController::Base.perform_caching

### ISSUE THREAD

**Issue by antoine-lizee** [rails/rails#20733]
I am not sure how to create a simple Minimal Working Example.
This happens when testing my caching behavior, and something along these lines fails:

      context "without cache" do
    
        it "should return the appropriate result, computing it every time", :caching => false do
          p ActionController::Base.perform_caching
          Object.should_receive(:where).exactly(4).and_call_original
          result1 = SomeService.action(args1, args2)
          result2 = SomeService.action(args1, args2)
        end
    
      end

...even though `false` is printed out for the `ActionController::Base.perform_caching`.
[I set this to false by the `:caching => false` option of the bloc (I use a hook)]

If I annihilate caching by switching from the default `:memory_store` to the `:null_store` for the testing environment, the test passes as expected. 
[I just add `config.cache_store = :null_store` in `test.rb`]

My `action` method uses the core caching from Rails:

    def action(args1, args2):
    ...
      objects = Rails.cache.fetch(cache_key, expires_in: 5.days) do
        object.where(id: args1).where(charac: args2).includes(...).to_a
      end
    ...
    end

**Comment by matthewd** [comment]
This sounds like expected behaviour to me; maybe the documentation can be improved.

It says `ActionController::Base.perform_caching` can be used "to turn off all caching". It could be clearer, but it means "to turn off all caching *involving this module*" -- direct access to `Rails.cache` is entirely outside ActionController's responsibility.

If you want to prevent *all* caching, rather than just having AC opt out of using it, `:null_store` what you want.

**Comment by antoine-lizee** [comment]
Well, after looking at the code from the active_support library, I am wondering if low-level caching has ever been meant to answer from `ActionController::Base.perform_caching`... Maybe we should improve the documentation that is clearly misleading here: guides.rubyonrails.org/caching_with_rails.html

**Comment by antoine-lizee** [comment]
@matthewd Yeah, I got it too. But the caching guide of rails is clearly misleading - it talks about the perform_caching as if it governed the while thing, including the low level caching stuff it is describing later on. I'll propose a PR.

**Comment by antoine-lizee** [comment]
On a related note, what would involve supporting this?

**Comment by antoine-lizee** [comment]
Closing, as the doc PR has been merged. Discussion could be restarted elsewhere if some new feature is desirable around this issue.
