### ISSUE TITLE
Named primary key with specified type is not reflected in schema.rb

### ISSUE THREAD

**Issue by plukevdh** [rails/rails#20749]
If I create a table via a migration using any of the following methods, the `schema.rb` ends up representing the table in the same format as the **first** `create_table` statement found below:

```ruby
create_table "users", id: false, primary_key: "my_cool_pk" do
  # ... 
end

# Or...

create_table "users", id: false do |t|
  t.primary_key :my_cool_pk, :uuid
  # ...
end

# Or...

create_table "users", id: false do |t|
  t.uuid :my_cool_pk, primary_key: true
  # ...
end
```

If you notice, in that first statement, the PK type is not represented. While all of these migration formats runs and create the table in the proper configuration (a primary key with the name `my_cool_pk` of type `uuid`), the schema.rb is left representing the table the same way:

```ruby
create_table "users", id: false, primary_key: "my_cool_pk" do
  # ... 
end
```

This becomes a problem when loading the db using the `db:schema:load` task, because the lack of type causes Rails to fill in the blank with the default `sequence` type (or `integer` depending on the database), meaning that migrate vs. schema:load leads to inconsistent databases. This is particularly a problem when using `load_schema_if_pending!` by default in Rails 4.1+ as it will cause the test database to differ from dev (and likely production too for that matter). 

I believe this is a bug, not only because it leads to inconsistent behavior, but because Rails stated purpose in the `schema.rb` file is as follows (emphasis mine): 

> Note that this schema.rb definition is the **authoritative source** for your database schema. If you need to create the application database on another system, **you should be using db:schema:load, _not_ running all the migrations from scratch**. The latter is a flawed and unsustainable approach (the more migrations you’ll amass, the slower it’ll run and the greater likelihood for issues).

There were a number of issues close to this one, so hopefully this isn't a dupe.

**Comment by senny** [comment]
@plukevdh on what version are you experiencing this issue? Does it still happen on `master`? Also, it would be nice to have an executable reproduction. Could you write one using [this script](https://github.com/rails/rails/blob/master/guides/bug_report_templates/active_record_master.rb) as a foundation?

**Comment by plukevdh** [comment]
@senny This was latest 4.2 release. I can write a quick example if you like. Do you prefer it written against master?

**Comment by senny** [comment]
@plukevdh against `4-2-stable` seems fine. I can run it against `master` and see wether we changed something in that area. I vaguely remember a similar report.

**Comment by plukevdh** [comment]
@senny I couldn't use your exact setup because it involves having tables persist beyond a single runtime (or at least, I couldn't figure out how this would replicate to sqlite:memory). I also am not sure whether or not this is PG specific, as even using sqlite3:file, the issue did not show up in the same manner. I do have a dummy app with simple instructions on how to replicate [here](https://github.com/plukevdh/ar-debug-app). Please let me know how I can further assist. 

I will also attempt to run this same test on mysql in a bit to see if the same issue exists, or if it is PG specific.

**Comment by plukevdh** [comment]
Looks to be (at least for now) a PG specific issue. Note the schema difference here

MySQL (after migration)

```ruby
ActiveRecord::Schema.define(version: 20150706175926) do

  create_table "comments", force: :cascade do |t|
    t.string "uuid", limit: 255
  end

  create_table "posts", id: false, force: :cascade do |t|
    t.string "uuid", limit: 255
  end

end
```

and for Postgres (after migration)

```ruby
ActiveRecord::Schema.define(version: 20150706175926) do

  # These are extensions that must be enabled in order to support this database
  enable_extension "plpgsql"

  create_table "comments", force: :cascade do |t|
    t.string "uuid"
  end

  create_table "posts", primary_key: "uuid", force: :cascade do |t|
  end

end
```

Note the missing field definition in the Postgres version.

**Comment by kapso** [comment]
I am having the same issue #20859

**Comment by Manifold0** [comment]
This has been an issue for a little while now: https://github.com/rails-sqlserver/activerecord-sqlserver-adapter/issues/395

**Comment by arnvald** [comment]
Hi everyone,

I'm having the same problem, so I thought maybe I could fix this issue, and... it appears it's been already fixed for almost a year! https://github.com/rails/rails/pull/18228 fixed the problem. Unfortunately that commit is only in master, it was never ported to `4-2-stable`. @senny any idea if this can be fixed in Rails 4.2?

**Comment by plukevdh** [comment]
![clouddance](https://cloud.githubusercontent.com/assets/16054/11035567/49768f54-86c1-11e5-84ff-e98446c68f41.gif)

**Comment by plukevdh** [comment]
This appears to be fixed in 5. `schema.rb` file after a migration form of the examples given in the initial description now looks like:

```ruby
create_table "users", primary_key: "my_cool_pk", id: :uuid, default: nil, force: :cascade do |t|
  # ...
end
```

`id: :uuid` is now being properly added to the table defn.
