### ISSUE TITLE
ActiveRecord dump_schema_after_migration setting should apply to all migration rake tasks

### ISSUE THREAD

**Issue by jturkel** [rails/rails#20743]
The `ActiveRecord::Base.dump_schema_after_migration` configuration setting is great for running migrations without errors in environments like Heroku that don't have `pg_dump` installed. Unfortunately it only applies to the `db:migrate` rake task. It would be great if it also applied to the `db:migrate:up`, `db:migrate:down`, `db:forward`, and `db:rollback` rake tasks so those tasks could be run without errors in Heroku.

**Comment by senny** [comment]
@jturkel I'll have a look.

**Comment by senny** [comment]
I can confirm this behavior on `master`. I'll submit a patch.

**Comment by jturkel** [comment]
Thanks for the quick turnaround @senny !

**Comment by senny** [comment]
Fixed on `master` and backported to `4-2-stable`.
