### ISSUE TITLE
default_scope of has_one :through model cached too agressively

### ISSUE THREAD

**Issue by bernerdschaefer** [rails/rails#20745]
### Context

We have been seeing intermittent test failures on our application.
When run in a certain order, two tests would fail for unknown reasons.
Digging into the cases revealed that an association was failing to load,
as it was being queried with an id that did not exist,
or rather with an id from a previous test.

The most likely culprit seemed to be `acts_as_tenant`,
but I confirmed that its state was being correctly reset
between test cases.

It seems that when model `A.has_one :c, through: :B`
and B has a default scope,
its scope is not re-evaluated if it changes.

### Reproduction

See this [self-contained gist][gist] for a reproduction.
I've checked this against `4.2.1`, `4.2.2`, and `4.2.3`, and `4-2-stable`.

[gist]: https://gist.github.com/bernerdschaefer/4e6afb2501331b10e98e

/cc @sgrif

**Comment by rafaelfranca** [comment]
Backported in d1dbfee45a5d2fb51423bee045b4c6199801b78a
