### ISSUE TITLE
Rails 4.2.3 : can't merge a scope when joining same table twice

### ISSUE THREAD

**Issue by my-kel** [rails/rails#20750]
Hi all,

First of all, I'm using Rails 4.2.3.

When I join a table twice the second table is renamed => good
If I merge a scope, the merged scope table's name is not renamed => bad

Here is the sql produced by my sample code below :

``` sql
SELECT "offers".* FROM "offers" 
  INNER JOIN "users" ON "users"."id" = "offers"."jobber_id" 
  INNER JOIN "jobs" ON "jobs"."id" = "offers"."job_id 
  INNER JOIN "users" "posters_jobs" ON "posters_jobs"."id" = "jobs"."poster_id" 
  WHERE "users"."deleted_at" IS NULL
```

and here is the result I was expecting :

``` sql
SELECT "offers".* FROM "offers" 
  INNER JOIN "users" ON "users"."id" = "offers"."jobber_id" 
  INNER JOIN "jobs" ON "jobs"."id" = "offers"."job_id 
  INNER JOIN "users" "posters_jobs" ON "posters_jobs"."id" = "jobs"."poster_id" 
  WHERE "users"."deleted_at" IS NULL AND "posters_jobs"."deleted_at" IS NULL
```

You can reproduce the bug with this code sampe :

``` ruby
begin
  require 'bundler/inline'
rescue LoadError => e
  $stderr.puts 'Bundler version 1.10 or later is required. Please update your Bundler'
  raise e
end

gemfile(true) do
  source 'https://rubygems.org'
  # Activate the gem you are reporting the issue against.
  gem 'activerecord', '4.2.0'
  gem 'sqlite3'
end

require 'active_record'
require 'minitest/autorun'
require 'logger'

# Ensure backward compatibility with Minitest 4
Minitest::Test = MiniTest::Unit::TestCase unless defined?(Minitest::Test)

# This connection will do for database-independent bug reports.
ActiveRecord::Base.establish_connection(adapter: 'sqlite3', database: ':memory:')
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :users, force: true do |t|
    t.datetime :deleted_at
  end

  create_table :jobs, force: true do |t|
    t.integer :poster_id
  end

  create_table :offers, force: true do |t|
    t.integer :jobber_id
    t.integer :job_id
  end
end

class User < ActiveRecord::Base
  has_many :jobs, foreign_key: :poster_id
  has_many :offers, foreign_key: :jobber_id

  scope :not_deleted, -> { where(deleted_at: nil) }
end

class Job < ActiveRecord::Base
  has_many :offers
  belongs_to :poster, class_name: User
end

class Offer < ActiveRecord::Base
  belongs_to :job
  belongs_to :jobber, class_name: User

  scope :jobber_not_deleted, -> { joins(:jobber).merge(User.not_deleted) }
  scope :poster_not_deleted, -> { joins(job: :poster).merge(User.not_deleted) }
end

class BugTest < Minitest::Test
  def test_association_stuff
    poster = User.create!(deleted_at: Time.now)
    jobber = User.create!
    job = poster.jobs.create!
    offer = jobber.offers.create!(job: job)

    assert_empty Offer.jobber_not_deleted.poster_not_deleted
  end
end
```

Is it a known issue ?

Regards.

**Comment by arthurnn** [comment]
Is this a bug only on 4.2.3 , do you know if it was working on 4.2.2 ? how about 4.2.4 , have you tried in that version.

thanks

**Comment by my-kel** [comment]
Hi @arthurnn. This bug already happened on Rails 3.2.x version. It is present on Rails 4.2.2 and 4.2.4 too.

Hope this will help.

**Comment by al2o3cr** [comment]
@my-kel Quick, unrelated note - the `class_name` option should be a string, not a class. I don't believe it's relevant here, but it has been known to cause mysterious behavior in concert with the autoloader.

Regarding the issue, it's tricky to get the table aliases into `merge`. As a possible workaround, I'd recommend scoping the `belongs_to` which will move the `deleted_at IS NULL` SQL up into the `ON` clauses of the join. Something like:

```ruby
class Job < ActiveRecord::Base
  has_many :offers
  belongs_to :poster, class_name: 'User'
  belongs_to :live_poster, -> { not_deleted }, class_name: 'User', foreign_key: 'poster_id'
end
```

then join against `live_poster` instead of just `poster`.

**Comment by my-kel** [comment]
@al2o3cr thanks for the note about the `class_name` option. But as you mentioned, it doesn't matter in this case.

Do you really find this issue tricky? Even if it is, I would prefer that ActiveRecord raise an exception rather then generating a buggy query.

Thanks for your workaround. What should I do if I need to join the same table multiple times, with different chained scopes? Would I have to define a lot of associations having a lambda operator to filter data, only because AR can't use the good table alias name via a `merge` ?

Another note : I can't imagine why the `or` operator isn't implemented on Rails 4. Cheers, it will come on Rails 5! Enjoy! :+1:

**Comment by al2o3cr** [comment]
@my-kel - the issue is that when the `merge` method runs, it does not have any information about its surroundings. All it can see is that you're merging a Relation that references the `users` table (`User.not_deleted`) into one that references that table twice.

Regarding `or`, I'd recommend digging through some of the PRs attempting to add it (there were many) for some background.

**Comment by maclover7** [comment]
Reproduction script fails on master.

**Comment by AlexeyMK** [comment]
FWIW, I'm having a very similar issue; conditions in the `where` clause does not respect a table we renamed because we use it twice in a join.

**Comment by tambakoo** [comment]
@rails-bot I can still produce this `Rails 5.2.0`. Can we open this again? Is there a way around this?
