### ISSUE TITLE
ActiveSupport #titleize does not work with Unicode characters

### ISSUE THREAD

**Issue by mariosant** [rails/rails#20756]
Consider the following:

``` ruby
> "happy string".titleize                                       
 => "Happy String"

> "ελληνικοί χαρακτήρες".titleize
 => "ελληνικοί χαρακτήρες"
```

The second case should return `"Ελληνικοί Χαρακτήρες"` .

This happens due the regex expression ```/\b(?<!['’`])[a-z]/ ``` which supports only ASCII characters. 
Source: https://github.com/rails/rails/blob/861b70e92f4a1fc0e465ffcf2ee62680519c8f6f/activesupport/lib/active_support/inflector/methods.rb#L154

**Comment by utilum** [comment]
This also happens due to Ruby's capitalize. Consider the following:
```
"happy string".gsub(/\b(?<!['’`])[\p{L}]/) { $&.capitalize }
  => "Happy String"
"ελληνικοί χαρακτήρες".gsub(/\b(?<!['’`])[\p{L}]/) { $&.capitalize }
  => "ελληνικοί χαρακτήρες"
```
What we need is also to modify the block:
```
"happy string".gsub(/\b(?<!['’`])[\p{L}]/) { $&.mb_chars.capitalize.to_s }
  => "Happy String"
"ελληνικοί χαρακτήρες".gsub(/\b(?<!['’`])[\p{L}]/) { $&.mb_chars.capitalize.to_s }
  => "Ελληνικοί Χαρακτήρες"
```

**Comment by utilum** [comment]
Well... to be precise, no need to replace first letters already capital:

"happy string".gsub(/\b(?<!['’`])[\p{Ll}]/) { $&.mb_chars.capitalize.to_s }
  => "Happy String"
"ελληνικοί χαρακτήρες".gsub(/\b(?<!['’`])[\p{Ll}]/) { $&.mb_chars.capitalize.to_s }
  => "Ελληνικοί Χαρακτήρες"

**Comment by bf4** [comment]
fwiw, have you seen the stringex gem? https://github.com/rsl/stringex https://github.com/rsl/stringex/blob/master/lib/stringex/unidecoder.rb

**Comment by utilum** [comment]
So titleize misses unicode chacaters. Is this the expected behavior? 
I'd be happy to pr.

**Comment by simi** [comment]
AFAIK it is expected behaviour.

You can see also inspect [babosa gem](https://github.com/norman/babosa) providing this funcionality.

**Comment by utilum** [comment]
I think simi's right:

"The Rails core team has stated patches for the inflections library will not be accepted in order to avoid breaking legacy applications which may be relying on errant inflections. If you discover an incorrect inflection and require it for your application or wish to define rules for languages other than English, please correct or add them yourself."

**Comment by mariosant** [comment]
Thanks for pointing this statement, @utilum . I was unaware of that. So the proper way to fix this is by patching it or develop another module to do the work.

This should be closed then, no?

**Comment by utilum** [comment]
pleasure, @mariosant I'm learning with you. 
titleize is part of Inflector api.rubyonrails.org/classes/ActiveSupport/Inflector.html , which is also where the doc comment above is from.
So I think you can override ActiveSupport::Inflector#titleize to suit your needs, or write your own mb_titleize method.
