### ISSUE TITLE
4.2.3 escape angle brackets in classname for exceptions

### ISSUE THREAD

**Issue by inspire22** [rails/rails#20776]
The default error message always says "Exception error in #msg< classname >< /classname > - the angle brackets always cause issues.

It's a simple fix if someone with easy access to a dev environment feels like submitting it please:

actionpack-4.2.3/lib/action_dispatch/middleware/templates/rescues/diagnostics.html.erb, line 11:

    <h2><%= h @exception.message.gsub(/>/,'&gt;').gsub(/</,'&lt;') %></h2>

**Comment by matthewd** [comment]
That change shouldn't be necessary... and shouldn't work.

**Comment by inspire22** [comment]
It was both necessary and worked for me.  Why didn't you think it would?
