### ISSUE TITLE
ActionController::TestCase uses symbols for request.query_parameters keys

### ISSUE THREAD

**Issue by odedniv** [rails/rails#20777]
When calling `request.query_parameters` inside a controller for a "request" that comes from a controller test, the keys of the hash come out as symbols, and the hash doesn't have indifferent access.

When request testing, feature testing, or running live - the keys come out as strings (which makes sense, as this is user input) and the hash is of `ActiveSupport::HashWithIndifferentAccess`.

`params` however comes out with strings for keys.

This can be reproduced in minitest functional test:

``` ruby
# app/controllers/widgets_controller.rb
class WidgetsController < ApplicationController
  def index
    p params
    p request.query_parameters
    p request.query_parameters["foo"]
    p request.query_parameters[:foo]
    p request.query_parameters.class
  end
end
```

``` ruby
# test/controllers/widgets_controller_test.rb
require 'test_helper'

class WidgetsControllerTest < ActionController::TestCase
  test "should get index" do
    puts "No params"
    get :index

    puts "\nString params"
    get :index, "foo" => 123

    puts "\nSymbol params"
    get :index, foo: 123
  end
end
```

Results in:

```
No params
{"controller"=>"widgets", "action"=>"index"}
{}
nil
nil
Hash

String params
{"foo"=>"123", "controller"=>"widgets", "action"=>"index"}
{:foo=>"123"}
nil
"123"
Hash

Symbol params
{"foo"=>"123", "controller"=>"widgets", "action"=>"index"}
{:foo=>"123"}
nil
"123"
Hash
```

However, this differs from an actual request:

```
{"foo"=>"123", "controller"=>"widgets", "action"=>"index"}
{"foo"=>"123"}
"123"
"123"
ActiveSupport::HashWithIndifferentAccess
```

Version:

```
ruby-2.2.2
rails-4.2.3
```

**Comment by atul-shimpi** [comment]
Looks same as #21032.
Root cause is same.

**Comment by rafaelfranca** [comment]
Could you check the master branch. I believe this issue is fixed there

**Comment by odedniv** [comment]
Unfortunately I get this error when trying to use `master` branch (it seems to be versioned `5.0.0`):

```
Bundler could not find compatible versions for gem "activesupport":
  In Gemfile:
    activesupport (>= 3.0) ruby

    activesupport (> 3) ruby

    activesupport (< 5, >= 3.0.0) ruby

    activesupport (< 4.3, >= 3.0) ruby

    activesupport (>= 2.0) ruby

    activesupport (>= 3.0) ruby

    activesupport (>= 3.0.0) ruby

    mongoid (>= 0) ruby depends on
      activemodel (~> 4.0) ruby depends on
        activesupport (= 4.2.3) ruby

    sass-rails (>= 0) ruby depends on
      railties (< 5.0, >= 4.0.0) ruby depends on
        activesupport (= 4.2.0) ruby

    sass-rails (>= 0) ruby depends on
      railties (< 5.0, >= 4.0.0) ruby depends on
        activesupport (= 4.2.0) ruby

    sass-rails (>= 0) ruby depends on
      railties (< 5.0, >= 4.0.0) ruby depends on
        activesupport (= 4.2.0) ruby

    activesupport (< 5.0, >= 4.2.0.beta) ruby

    mongoid (>= 0) ruby depends on
      activemodel (~> 4.0) ruby depends on
        activesupport (= 4.2.3) ruby
Bundler could not find compatible versions for gem "rack":
  In snapshot (Gemfile.lock):
    rack (= 1.6.4)

  In Gemfile:
    thin (>= 0) ruby depends on
      rack (~> 1.0) ruby

    thin (>= 0) ruby depends on
      rack (~> 1.0) ruby

    poltergeist (>= 0) ruby depends on
      capybara (~> 2.1) ruby depends on
        rack (>= 1.0.0) ruby

    poltergeist (>= 0) ruby depends on
      capybara (~> 2.1) ruby depends on
        rack-test (>= 0.5.4) ruby depends on
          rack (>= 1.0) ruby

    sass-rails (>= 0) ruby depends on
      railties (< 5.0, >= 4.0.0) ruby depends on
        actionpack (= 4.0.0) ruby depends on
          rack (~> 1.5.2) ruby

Running `bundle update` will rebuild your snapshot from scratch, using only
the gems in your Gemfile, which may resolve the conflict.
```

Tried branch `4-2-stable` and had the same problem mentioned in the description of the issue (not the bundler issue).

**Comment by atul-shimpi** [comment]
@rafaelfranca
Tested in master branch. Working as expected.
Below is the output of rake test
========================================
No params
{}
{}
nil
nil
ActiveSupport::HashWithIndifferentAccess
String params
{"foo"=>"123"}
{"foo"=>"123"}
"123"
"123"
ActiveSupport::HashWithIndifferentAccess
Symbol params
{"foo"=>"123"}
{"foo"=>"123"}
"123"
"123"
ActiveSupport::HashWithIndifferentAccess
.

Finished in 0.331318s, 3.0182 runs/s, 0.0000 assertions/s.

1 runs, 0 assertions, 0 failures, 0 errors, 0 skips
===========================================
Env 
1] ruby-2.2.2 [ x86_64 ]
2] Rails : gem 'rails', path: "/home/ashimpi/ror/rails"
    rails rep : git://github.com/rails/rails.git

**Comment by atul-shimpi** [comment]
@odedniv 
May i know your steps?

**Comment by odedniv** [comment]
@atul-shimpi, I wasn't able to use rails master in my project, I could only try out 4.2. If it works for you on master I guess master is good. You can try switching to 4-2-stable branch and get my results.

Do you close the issue in this case? Can it be fixed for 4.2?

**Comment by atul-shimpi** [comment]
@rafaelfranca 
What do u suggestion ? Should this integrated in 4.2 ?
I am working on for 2 years. However, started contributing just 1 week back. So would like to be active here.

**Comment by arthurnn** [comment]
@atul-shimpi what I would suggest is: As this is working in master, try isolate a test case, in a brand new app, and change that from 4-2-stable to master, and see that the error is indeed on 4-2-stable. After that, you can use `git bisect` to find the commit that fixed that on master, than you can try to backport that to 4-2-stable.
