### ISSUE TITLE
ActiveJob ignores locale during serialization

### ISSUE THREAD

**Issue by xijo** [rails/rails#20799]
The current ActiveJob implementation does not store `I18n.locale` during its serialization.

This results e.g. in emails, that are sent with the wrong language settings, described in #20774.

My previous PR #20758 didn't tackle the problem right, it just solved it on the layer of ActionMailer. The expected behavior would be that the locale is stored on and restored from the queue and is used while performing the job.

**Comment by jvanbaarsen** [comment]
New PR is here: https://github.com/rails/rails/pull/20800

**Comment by xijo** [comment]
@kaspth any news on this issue and the pull request? Thanks!

**Comment by xijo** [comment]
@kaspth I updated the active job guide, please have a look at it.

BTW: I can't comment on the PR any more since it's limited to collaborators, which is why I'm writing you here instead.
