### ISSUE TITLE
ActiveRecord 4.2 breaks find_by association subquery

### ISSUE THREAD

**Issue by griffithchaffee** [rails/rails#20817]
Active Record 4.2.x (4.2.0 - 4.2.3) breaks association subqueries that worked in 4.1.x (4.1.6 - 4.1.11).

It looks like the subquery in a `find_by(association_id: subquery)` statement is interpreted as a bind parameter. Interestingly enough using the `find_by(association: subquery)` format seems to work.

[bugtest](https://gist.github.com/griffithchaffee/852a1a218951d160d033)

### Overview:

```ruby
# always works
# SELECT  "admins".* FROM "admins"  WHERE "admins"."group_id" IN (SELECT "groups"."id" FROM "groups"  WHERE "groups"."id" = 1) LIMIT 1
good_query = Admin.find_by(group: Group.where(id: group))

# breaks in AR 4.2
# SELECT  "admins".* FROM "admins" WHERE "admins"."group_id" = ? LIMIT 1  [["group_id", nil]]
bad_query  = Admin.find_by(group_id: Group.where(id: group))
```

**Comment by agis-** [comment]
I find it surprising that `bad_query` works in 4.1. It *seems* wrong.

Why not just do `find_by(group_id: Group.where(id: group).id)`?

**Comment by griffithchaffee** [comment]
@agis- Your code example is invalid but I'm guessing you are just trying to show an easier way of making the query. This is just a simple example that reveals the underlying bug. The bug is that ActiveRecord incorrectly handles a subquery in a find_by and possibly other methods.

A good bypass for now is using: `Admin.where(group_id: Group.where(id: group)).first`

Just watch for similar subquery bugs like: #20802
