### ISSUE TITLE
form helper formatting of array attributes changed from Array#to_s to Array#join(' ')

### ISSUE THREAD

**Issue by bughit** [rails/rails#20814]
between 4.0 and 4.2

Why change the resulting format?  This just introduces bugs with no benefit.

**Comment by rafaelfranca** [comment]
You need to give us more information on how to reproduce this issue, otherwise there is nothing we can do. Please read CONTRIBUTING.md file for more information about creating bug reports. Thanks!

**Comment by bughit** [comment]
https://github.com/rails/rails/commit/19af434840802ca0feb39253241917286467a86e#diff-240949893f36da11390dc227e2c352ccL10

this commit removed the code that did a #to_s on the array

`options["value"] &&= ERB::Util.html_escape(options["value"])`

now the value remains an array until TagHelper#tag_option does a join(' ')

```ruby
        def tag_option(key, value, escape)
          if value.is_a?(Array)
            value = escape ? safe_join(value, " ") : value.join(" ")
          else
            value = escape ? ERB::Util.unwrapped_html_escape(value) : value
          end
          %(#{key}="#{value}")
        end
```

so not only does this gratuitously introduce bugs, but the new join(" ") encoding is terrible because you can't reliably parse the values back from it

I think I've shown enough specific relevant code, so please reopen

**Comment by rafaelfranca** [comment]
Could you please explain what was the output before and after this change?

**Comment by rafaelfranca** [comment]
As far I can see the behavior that you are relying was a unwanted side effect of that call. Array options were always expected to use `join(' ')`

**Comment by bughit** [comment]
1. this "side effect" that was there probably from the beginning of form field helpers
2. as to whether it's unwanted, how can you possibly believe that a lossy join(' ') is better than a lossless to_s (effectively json), as I mentioned you can't reliably parse values out of a join (`['a b', 'c d']`)

**Comment by rafaelfranca** [comment]
> this "side effect" that was there probably from the beginning of form field helpers

Yeah, not it is already changed and probably someone relies on not having that side-effect so it is unlikely we will change back.


> as to whether it's unwanted, how can you possibly believe that a lossy join(' ') is better than a lossless to_s (effectively json), as I mentioned you can't reliably parse values out of a join (['a b', 'c d'])

If you want a lossless `to_s` just call it when calling the form helper. It is explicit and will hardly change between versions.

**Comment by bughit** [comment]
4.0.8
```
>> helper.text_field('array', :array, object: OpenStruct.new(array: ['a b', 'c d']))
"<input id=\"array_array\" name=\"array[array]\" type=\"text\" value=\"[&quot;a b&quot;, &quot;c d&quot;]\" />"
```

4.2.3
```
>> helper.text_field('array', :array, object: OpenStruct.new(array: ['a b', 'c d']))
"<input type=\"text\" value=\"a b c d\" name=\"array[array]\" id=\"array_array\" />"
```

Not only does this needlessly introduce bugs into upgraded code, but the new behavior, regardless of whether you call it a fix or a feature is objectively worse.  If you were building this from scratch would you encode arrays with a join(' ')?  You seem to be reflexively defending the status quo without considering what would actually be better,.

**Comment by rafaelfranca** [comment]
> If you were building this from scratch would you encode arrays with a join(' ')

Yes, I'd. Maybe not for `value` attribute like your case but look at the `class` attribute behavior, it relies on the fact that arrays are joined with a whitespace.

> You seem to be reflexively defending the status quo without considering what would actually be better,.

In my opinion explicit conversion is better than implicit conversion. If you want an special format of your attribute value explicitly call it.

**Comment by rafaelfranca** [comment]
```ruby
helper.text_field('array', :array, value: ['a b', 'c d'].to_s)
```

**Comment by bughit** [comment]
`class` is a strawman, we are explicitly discussing the value attribute
`options["value"] &&= ERB::Util.html_escape(options["value"])`
since that's what has changed

so you have basically admitted that join(' ') is a stupid default formatting for values

**Comment by rafaelfranca** [comment]
Yes, but we are in a really bad situation. Changing back this behavior may break a lot of applications that relies on it and I really don't want to do that in a stable release. But maybe I'm being too pessimistic and it is worth to try patching and reverting on release candidate if my concerns are true.

**Comment by bughit** [comment]
> In my opinion explicit conversion is better than implicit conversion

regardless of this opinion, there will always be a default implicit conversion, and we are discussing what this default should be.  The to_s json like default is better because it was there forever and it's less lossy.

**Comment by bughit** [comment]
So what should happen here?  Are you looking for other opinions or a pull request or will you be making the change yourself?

**Comment by matthewd** [comment]
I think the current `join(' ')` seems more useful.

The previous behaviour was 1) never documented, and 2) very definitely not JSON -- anyone treating it as such is surely in for a nasty surprise at some point.

It also seems very obscure, to deliberately give special handling to this one attribute on this one tag.

**Comment by bughit** [comment]
> I think the current join(' ') seems more useful.

The main if not the only reason to encode an array in a form field value string is so you can decode it back later.  join(' ') makes that impossible (elements with spaces).  So this opinion is objectively wrong.

**Comment by matthewd** [comment]
> this opinion is objectively wrong

Thanks for playing.
