### ISSUE TITLE
Put back #19073 fix without the association regression.

### ISSUE THREAD

**Issue by rafaelfranca** [rails/rails#20816]
https://github.com/rails/rails/commit/728a5d50af7303425541ac69aaf86139cc7c28e5 caused a regression when building a `has_many` association object in a non-persisted where the foreign key remains `nil` even after the parent object is saved. It was reverted in https://github.com/rails/rails/commit/788b78a4d7a922a35abe3e95335bd34751794f42 for 4-2-stable just to avoid the regression in my application.

We need to put back the original code and try to fix the foreign key being `nil` issue before the next 4.2.x bug fix release.

cc @sgrif

**Comment by sgrif** [comment]
Can you give me any additional details on what's happening? I currently have no way to reproduce your issue.

**Comment by rafaelfranca** [comment]
Let me get the reproduction script that I created. But I still can not reproduce it even with the script.

**Comment by rafaelfranca** [comment]
```ruby
require 'bundler/setup'

require 'active_record'
require 'minitest/autorun'
require 'logger'

# This connection will do for database-independent bug reports.
ActiveRecord::Base.establish_connection(adapter: 'sqlite3', database: ':memory:')
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :blogs, force: true  do |t|
  end

  create_table :comments, force: true  do |t|
    t.integer :post_id
  end

  create_table :posts, force: true  do |t|
    t.integer :main_author_id
    t.integer :blog_id
    t.string :name
  end

  create_table :authors, force: true  do |t|
    t.string :signature
    t.integer :post_id
  end
end

class Blog < ActiveRecord::Base
  has_many :posts
end

class Comment < ActiveRecord::Base
  belongs_to :post
end

class Post < ActiveRecord::Base
  belongs_to :blog
  has_many :comments
  has_many :authors, -> { order "id" }, inverse_of: :post, class_name: 'Author'
  belongs_to :main_author, class_name: 'Author', inverse_of: :post
end

class Author < ActiveRecord::Base
  belongs_to :post, inverse_of: :authors, touch: true
end

class BugTest < Minitest::Test
  def test_association_stuff
    blog = Blog.create!
    post = blog.posts.new
    post.main_author = post.authors.where(signature: 'signature').build.tap do |a|
      post.authors.proxy_association.add_to_target(a)
    end
    post.update_attributes(name: 'foo')

    refute_nil post.main_author.post_id
  end
end
```

This is a simplification of the code that is getting me the problem.

**Comment by sgrif** [comment]
Must be a monkey patch on your guys end?

**Comment by rafaelfranca** [comment]
I thought it, so I ran this same script inside the application and tests also pass, so I think I still could not isolate the problem.

**Comment by rafaelfranca** [comment]
Closed by the linked commit :heart:
