### ISSUE TITLE
Belongs to with nil scope gives confusing error message

### ISSUE THREAD

**Issue by ZeroFries** [rails/rails#20823]
The issue can be reproduced by creating a belongs_to association with an optional scope which returns nil.

```
belongs_to :account, -> { nil }
```

This generates the following error when calling the parent association:
undefined method `visited' for nil:NilClass

The stack trace is not very useful either. It can be non-obvious locating the issue if the scope does not obviously return nil, or only sometimes does (for example, if there's an if statement).

**Comment by fenec** [comment]
I created a PR to fix this issue https://github.com/rails/rails/pull/20826

**Comment by maclover7** [comment]
Opened #25143.

**Comment by prathamesh-sonpatki** [comment]
@ZeroFries @maclover7 I am trying to understand this issue.

Is `belongs_to :account, -> { nil }` same as `belongs_to :account` ? What is the expectation here?
