### ISSUE TITLE
new_record? unexpectedly returns true

### ISSUE THREAD

**Issue by firien** [rails/rails#20824]
This [gist](https://gist.github.com/firien/f2211669a2e539e63d20) demonstrates bug/issue. In ActiveRecord 4.2.2 everything acts as expected. 4.2.3 however #new_record? returns `true` for a record that is clearly persisted.

So far I have tracked it down as far as [transactions.rb#L390](https://github.com/rails/rails/blob/v4.2.3/activerecord/lib/active_record/transactions.rb#L390). In 4.2.2. the `transaction_level` variable is 1, in 4.2.3 it is 0.

**Comment by firien** [comment]
throwing a backtrace at [transactions.rb#L376](https://github.com/rails/rails/blob/v4.2.3/activerecord/lib/active_record/transactions.rb#L376) you can see that save is being called 3 times in 4.2.3, while only twice in 4.2.2.

<img width="1041" alt="bt" src="https://cloud.githubusercontent.com/assets/58729/8607213/6c101ef8-265f-11e5-85b0-a47dd066f4eb.png">

**Comment by firien** [comment]
@arthurnn, this one [line](https://github.com/rails/rails/commit/ec712fb4ca5289a22872eabf32c74459a304115d#diff-174733f2db65ef1bc53e3222d6ac0e61R334) is responsible for this [gists](https://gist.github.com/firien/f2211669a2e539e63d20) odd behavior - thoughts?

**Comment by meinac** [comment]
This bug also appears in master branch. After rollback of the transaction it loads the previous transaction state. We should clear the `@_start_transaction_state` after commit.

**Comment by sgrif** [comment]
Fixed by #20947
