### ISSUE TITLE
'select as' and count are not getting along

### ISSUE THREAD

**Issue by blunckr** [rails/rails#20825]
When I use a custom select statement with AS in it, and then try to do a count on it, it generates invalid SQL. 
```ruby
User.select('username AS name', '*').count
```
```
: SELECT COUNT(username AS name, *) FROM "users"
ActiveRecord::StatementInvalid: PG::SyntaxError: ERROR:  syntax error at or near "AS"
LINE 1: SELECT COUNT(username AS name, *) FROM "users"
```
Note that I'm using postgres, I'm not sure if that matters.

The reason I'm doing this is to sort by a 'fake' column, like this
```ruby
User.select('sign_in_count * 2 AS something', '*').order("something DESC").count
```
(No, that's not the actual query I'm running)
Is there simply a better way to do something like this that I'm missing? For now I'm just using .length instead of .count

**Comment by rafaelfranca** [comment]
You want to ignore the selected columns statement when doing the count? if that is the case use `count(:all)` otherwise it will use what you asked to select.

**Comment by blunckr** [comment]
Ah thank you, that worked. Sorry I didn't think to look at the count documentation for some reason.
