### ISSUE TITLE
Creating Records via #new on an AR::Relation object can fail due to enums.

### ISSUE THREAD

**Issue by tobypinder** [rails/rails#20820]
ActiveRecord relations where a `where` clause specifies multiple possible enum values for a given `enum` can cause failures when trying to call `#new` on that relation. I've included a test case using the Rails guidelines to illustrate this.

[Gistified here, for easier manipulation](https://gist.github.com/tobypinder/929c5afbedd76b170bfb) 

```ruby
begin
  require 'bundler/inline'
rescue LoadError => e
  $stderr.puts 'Bundler version 1.10 or later is required. Please update your Bundler'
  raise e
end

gemfile(true) do
  source 'https://rubygems.org'
  gem 'rails', '4.2.3' # github: 'rails/rails'
  # gem 'arel', github: 'rails/arel'
  gem 'sqlite3'
end

require 'active_record'
require 'minitest/autorun'
require 'logger'

# This connection will do for database-independent bug reports.
ActiveRecord::Base.establish_connection(adapter: 'sqlite3', database: ':memory:')
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :things, force: true  do |t|
    t.integer :enum_field
  end
end



class Thing < ActiveRecord::Base
  enum enum_field: {
    foo: 1,
    bar: 2,
    baz: 3
  }
end

class BugTest < Minitest::Test
  def test_creating_new_record_from_existing_relation
    Thing.all.new # OK
    Thing.all.where(enum_field: 2).new # OK
  end

  def test_creating_new_record_from_existing_relation_with_single_element_in_array
    Thing.all.where(enum_field: [1]).new # OK, since it gets coerced into the same as `enum_field: 1`
  end

  def test_creating_new_record_from_existing_relation_with_multiple_elements_in_array
    Thing.all.where(enum_field: [1, 2]).new # FAIL, despite being the valid way to craft IN() statements
  end
end
```

I would guess that expected behaviour would be that the newly initialized object has `enum_field` initialized to `nil`.

```
> ruby -v
< ruby 2.2.2p95 (2015-04-13 revision 50295) [x86_64-linux]
```

**Comment by fenec** [comment]
I think it's correct because you cannot create an object with an array as a enum field (it's an integer).

**Comment by tobypinder** [comment]
@fenec - My understanding is that the current scope should not try to set default parameters when they are ambiguous. Logically, the scope used is an array because `ActiveRecord` uses it to create an IN statement (`WHERE enum_field IN(1, 2)`). The fact that Rails is attempting to create the field *with* the array *is* the bug. Removing the `enum enum_field { ... }` statement from my example results in the expected behaviour - a `Thing` class is created but because the current relation is ambiguous about what `enum_field` should equal, it's initialised to `nil`.

**Comment by tobypinder** [comment]
I've tried to look into this, but without much knowledge of where AR does it's internal handling of supplied array arguments for strings, integers etc. I'm getting nowhere. This particular bug only manifests itself with Enums - it seems that by the time things get casted in the enum it's being passed the array, whereas for other type classes the methods are being called twice for the individual parameters. So something in between is properly handling this case for other types than enums. 

I'll try to get more of a look at this after work some time, but if anyone can point me in the right direction I'd be more than grateful!

**Comment by sgrif** [comment]
In general the behavior of arrays with `build`/`create` is undefined. We only explicitly handle it for integers (https://github.com/rails/rails/blob/master/activerecord/lib/active_record/type/integer.rb#L43 to be precise, the `rescue nil` part). This is mainly because it's ergonomic to be able to use an array for foreign keys when doing things like multi-tenancy. However we don't handle it in the general case. For example, a string type does this:

```ruby
ActiveRecord::Base.establish_connection(adapter: 'sqlite3', database: ':memory:')
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :posts do |t|
    t.string :foo
  end
end

class Post < ActiveRecord::Base
end

p Post.where(foo: ["foo", "bar"]).new # => #<Post id: nil, foo: "[\"foo\", \"bar\"]">
```

If you'd like to attempt to handle this in the general case, feel free to take a swing at it (keeping in mind that we have types like `Array` and `JSON` that do need to receive arrays). However, this is unsupported behavior which I'd rather not special case for enum without a more compelling use case.

**Comment by tobypinder** [comment]
I see. I had assumed this was defined behaviour of `AR::Relation#build`, and so we've been using "current" scopes in our applications to allow users to create an object similar to the one they're currently "looking at" (taking the user-defined "WHERE" conditions of the index). I can tell you that the "undefined" behaviour works absolutely fine with strings too - SQL generates the `IN()` blocks as expected but when `build`ing on top of such a scope the field is `nil`. I haven't tried many other types to expand on this.

I'll look into this further, but I see a possible solution as 

* Define a `#multiple?` method on `ActiveRecord::Type::Value` that defaults to `false`.
* Override this with `true` with types like Array and JSON to signal that these shouldn't be processed.
* When using `build`/`create` call something above `cast_value` that will return `nil` for supplied arrays unless that particular class allows `#multiple?`

All this said I have no idea how common or useful my usecase is - it seems like lots of people might benefit from more robust "current scope initialisation" but feedback is appreciated. Regardless of my proposal, I'm just not sure that throwing a stacktrace here is beneficial.
