### ISSUE TITLE
Documentation for ActiveRecord::Enum is wrong

### ISSUE THREAD

**Issue by glentakahashi** [rails/rails#20834]
I think the documentation for http://edgeapi.rubyonrails.org/classes/ActiveRecord/Enum.html is wrong here:

    Of course, you can also query them directly if the scopes don't fit your needs:
    Conversation.where(status: [:active, :archived])
    Conversation.where.not(status: :active)

On that page it says that you should be able to query Conversation.where(status: :active), but many other websites I have looked into say this functionality is not included. I have tested it myself on Rails 4.2.1 and seen that it doesn't not work as expected.

**Comment by glentakahashi** [comment]
Closed because I am wrong. Documentation is correct on http://api.rubyonrails.org/v4.2.1/classes/ActiveRecord/Enum.html, I was looking at the wrong link.

**Comment by sintro** [comment]
a
