### ISSUE TITLE
Spelling mistake in auto-generated Gemfile

### ISSUE THREAD

**Issue by VELVETDETH** [rails/rails#20844]
When I run something simple like: 

    rails new demo

And you could find out that, in `Gemfile`, there're 2 lines:

    # Use SCSS for stylesheets
    gem 'sass-rails', '~> 4.0.0'

Should **SCSS** be **SASS**? 

Anyway, I think SCSS is ok here, but quite confusing. Especially for someone who just recognize SASS(like me).

**Comment by matthewd** [comment]
No; we use SCSS by default.
