### ISSUE TITLE
#to_json hangs with Redis client on payload

### ISSUE THREAD

**Issue by jondeandres** [rails/rails#20862]
Hi,

in https://github.com/rollbar/rollbar-gem we are having some problems when we are trying to serialize a payload that has a `Redis` instance on it. The serialization process just hangs.

The test is this:

```ruby
  context "with Redis instance in payload and ActiveSupport is enabled" do
        let(:redis) { ::Redis.new }
        let(:payload) do
          {
            :key => {
              :value => redis
            }
          }
        end
        it 'dumps to JSON correctly' do
          redis.set('foo', 'bar')
          json = payload.to_json

          result = expect(json).to be_kind_of(String)
        end
  end
```

If I remove monkey patch in `lib/active_support/core_ext/object/to_json.rb` then is solved.

Also, if I add this to `lib/active_support/json/encoding.rb` it's also solved:

```ruby
class Socket
  def as_json
    to_s
  end
end
```

Any idea about how to solve this correctly? Maybe my monkey patch is enough, but I'd like to avoid it.

Thanks.

**Comment by jondeandres** [comment]
Ok, I think this is fixed in from activesupport 4.1.0. I guess we'll need to monkey patch `Socket` so it doesn't hang,

**Comment by jondeandres** [comment]
@matthewd I guess you've closed this since I've found the version from we can use native JSON without use ActiveSupport.

But were you concerned about this error serializing data? There are plans to solve it?

Thanks.

**Comment by matthewd** [comment]
Sorry, I forgot to add a comment. :confused: 

My interpretation of your previous comment was that you'd originally reported the problem based on an earlier (`< 4.1`) version, and that you'd subsequently determined upgrading to 4.1.0 fixed it. Is that right?

**Comment by jondeandres** [comment]
@matthewd upgrading active_support fix that resolves the problem of being able to use just JSON, without active_support. But it doesn't solve the problem of serializing a payload with a `Socket` instance on it.

But it works fine using just JSON.
