### ISSUE TITLE
createjointable - does it generate model?

### ISSUE THREAD

**Issue by kasiaul** [rails/rails#20864]
I used code from doc
$ bin/rails g migration CreateJoinTableCustomerProduct customer product
to create:
rails g migration CreateJoinTableProductTypeSpecification product_type specification

With generated code in migration index name was too long I had to use in migration different code:
      t.belongs_to :product_type,  index: true
      t.belongs_to :specification,   index: true
But model was not created.

Generating model
$ rails generate model ProductTypesSpecification
 adds another migration.

What is Rails 4 way to do it?

**Comment by japed** [comment]
Just delete the secondary migration.  You should have just used the model generator if you wanted that too.  This isn't an issue with the code, you should ask these sorts of questions on [StackOverflow](http://stackoverflow.com/questions/tagged/ruby-on-rails)

**Comment by kasiaul** [comment]
Thank you. However I consider it as Contributing to Ruby on Rails guide for guidelines. We should be clear what results to expect from code.
