### ISSUE TITLE
Creating Table in Mysql

### ISSUE THREAD

**Issue by sasiraju** [rails/rails#20861]
I have one question

Shall I create a table with uppercase in Mysql from ruby on rails.

becoz whatever iam giving the tablename only table creation format like
1.lowercase
2.underscore
3.plural

example
-------------
tab_names .

shall i change tab_names--->TABNAME....??

is it  rails default or  possible to change???

please provide the answer....

**Comment by matthewd** [comment]
Please use the mailing list or StackOverflow for questions/help, where a wider community will be able to help you. We reserve the issues tracker for issues only.
