### ISSUE TITLE
Add wildcards to template dependencies

### ISSUE THREAD

**Issue by dhh** [rails/rails#20878]
```erb
    <% # Template Dependency: recordings/threads/events/subscribers_changed %>
    <% # Template Dependency: recordings/threads/events/completed %>
    <% # Template Dependency: recordings/threads/events/uncompleted %>
```

Would be great if that could be written as:

```erb
    <% # Template Dependency: recordings/threads/events/* %>
```

**Comment by dhh** [comment]
Any thoughts on this @kaspth?

**Comment by kaspth** [comment]
I assume you're doing something like:

```erb
<% # Template Dependency: recordings/threads/events/subscribers_changed %>
<% # Template Dependency: recordings/threads/events/completed %>
 <% # Template Dependency: recordings/threads/events/oh_my_gawd_im_so_bored %>
<%= render_shit_fit_for_print @person.events %>
```

Yup, I could definitely see that becoming tedious if you add another STI event (or however they're setup) - especially if you're rendering the same stuff elsewhere. It would be cooler if that got picked up automatically.

I think it's doable if we resolve the directory to its files - and thereby track file addition and removal. Then we leverage the existing file based dependency tracking, but only gently dip our toes in directory land.

You've got my go ahead and I'll gladly merge your pull request :+1:

That's what you wanted me to say, right? :smile:

**Comment by dhh** [comment]
Haha, that's exactly it :)

**Comment by kaspth** [comment]
Now I'm too curious, so I'll steal this right from under you :grin:

Unfortunately, if you're not writing the PR, your commit count won't go up and there's less chance of you being recognized for helping Rails out. I hope you're okay with that :smile:

**Comment by dhh** [comment]
Ahh, shoot! 😋
