### ISSUE TITLE
Rails is not converting timezones (config.time_zone not working)

### ISSUE THREAD

**Issue by andreynering** [rails/rails#20876]
A found this bug on many apps I made, from Rails 4.1.* to 4.2.* (including 4.2.3). I use PostgreSQL.

I live in Brazil, so I always add this to `application.rb`:

```ruby
class Application < Rails::Application
  config.time_zone = 'Brasilia'
end
```

At first, it does what it is supposed to do: it converts the time input (from user) from UTC-03:00 to UTC before saving in the database. And in forms and views, it converts from UTC to UTC-03:00.

But after some days/few weeks, it simply stops working. Rails does the default behavior instead: assumes UTC for everything and stops converting timestamps from and to UTC-03:00.

It's weird, but I couldn't reproduce it in an isolated app. Maybe it is some configuration or gem changing the behavior?

**Comment by andreynering** [comment]
Just found that hardcoding it worked (Rails 4.2.3):

```ruby
class Application < Rails::Application
end

Application.config.time_zone = 'Brasilia'
```

**Comment by krlsdu** [comment]
http://guides.rubyonrails.org/configuring.html
Look for timezone, maybe help you.

**Comment by rafaelfranca** [comment]
> It's weird, but I couldn't reproduce it in an isolated app. Maybe it is some configuration or gem changing the behavior?

Seems so. Let us know if you could reproduce the issue, otherwise there is nothing that we can do to help.

Thanks.

**Comment by andreynering** [comment]
Finally found the root of the problem.

One of the installed gems was messing up with the initialization process. It's not a Rails bug.

**Comment by tholka-hypto** [comment]
> Finally found the root of the problem.
> 
> One of the installed gems was messing up with the initialization process. It's not a Rails bug.

@andreynering I am facing similar issue. Can you please share which gem was causing the issue?

**Comment by andreynering** [comment]
@tholka-hypto Sorry, that was a long time ago, and I don't remember which gems caused this problem.
