### ISSUE TITLE
New records are autosaved with parent even though marked for destruction

### ISSUE THREAD

**Issue by betesh** [rails/rails#20882]
unless the association is `autosave: true` or the record is invalid

Failing test: https://gist.github.com/betesh/be51479c11fbc9a419c6

**Comment by sgrif** [comment]
Can you please use the standard testing template? I'm an RSpec user, but I still can't follow these examples through that much RSpec magic.

**Comment by betesh** [comment]
Sorry, I'm not sure what you mean by Standard Testing Template.  Can you provide a link?

**Comment by sgrif** [comment]
https://github.com/rails/rails/blob/master/guides/bug_report_templates/active_record_master.rb

**Comment by sgrif** [comment]
See also: http://guides.rubyonrails.org/contributing_to_ruby_on_rails.html

**Comment by betesh** [comment]
New gist, using Standard Testing Template: https://gist.github.com/betesh/209e8c6be27c709a0a8d

When I build a Post with a Comment, and the Comment is marked for destruction, I expect validations not to run on it and I expect it not to be saved.  In `test_valid_comment`, however, the record is saved.

If, for some reason, a `new_record` that is `marked_for_destruction` **is** supposed to be validated & saved, then when it is invalid, `post.save!` should raise a `ActiveRecord::RecordInvalid`.  However, `test_invalid_comment` passes, showing that this is not the case.

Note that a workaround is to use `autosave: true` on the association.

**Comment by sgrif** [comment]
From the docs for `mark_for_destruction` (http://api.rubyonrails.org/classes/ActiveRecord/AutosaveAssociation.html#method-i-mark_for_destruction)

> Only useful if the :autosave option on the parent is enabled for this associated model.

**Comment by betesh** [comment]
I figured there was something in the docs that I wasn't connecting.  In that case, there is a reason the mark_for_destruction is supposed to be ignored.  As I stated in my initial description:

> If, for some reason, a new_record that is marked_for_destruction is supposed to be validated & saved, then when it is invalid, post.save! should raise a ActiveRecord::RecordInvalid. However, test_invalid_comment passes, showing that this is not the case.

So there is still a bug here.

**Comment by betesh** [comment]
@sgrif Shall I open a new issue and create a new failing-test gist since I mis-stated what the bug is here?

**Comment by sgrif** [comment]
@betesh No, I'm about to push a fix. Thanks.

**Comment by betesh** [comment]
Thank you!

**Comment by sgrif** [comment]
Fixed in https://github.com/rails/rails/commit/c0ef95a1c6db3095c4b5f80f8044fbbbdfebeff1 and backported in https://github.com/rails/rails/commit/cd1bbf8ede61dd5ca1c60c9801a1978d322d447b
