### ISSUE TITLE
Add a note to Active Record Validations Guide for acceptance method

### ISSUE THREAD

**Issue by lukechesser** [rails/rails#20896]
The documentation in the [Active Record Validation Guide for the validator method `acceptance`](http://guides.rubyonrails.org/active_record_validations.html#acceptance) could include a note that the validation won't run if the field exists in the database.

The [API documentation for the helper method](http://api.rubyonrails.org/classes/ActiveModel/Validations/HelperMethods.html#method-i-validates_acceptance_of) `validates_acceptance_of` makes it a little more clear, saying:

> This should be set to true if you are validating a database column, since the attribute is typecast from “1” to true before validation.

An easy change for the Active Record Validation Guide could be:

> This validation is very specific to web applications and this 'acceptance' does not need to be recorded anywhere in your database (if you don't have a field for it, the helper will just create a virtual attribute).

To be changed to:

> This validation is very specific to web applications and this 'acceptance' does not need to be recorded anywhere in your database. If you don't have a field for it, the helper will just create a virtual attribute. If the field does exist in your database, the `accept` option must be set to `true` or else the validation will not run.

Might be helpful as it looks like a number of other people have had the same problem:

http://stackoverflow.com/questions/4746710/validates-acceptance-always-failing

Happy to add a pull-request for the documentation or reword if it helps.

**Comment by rafaelfranca** [comment]
Feel free to send a PR.

**Comment by lukechesser** [comment]
Added a PR #20897

**Comment by arthurnn** [comment]
PR merged.. thanks
