### ISSUE TITLE
Shallow resource routes in Engine not being respected

### ISSUE THREAD

**Issue by mlarraz** [rails/rails#20891]
Given a resource `Baz` with its controller in module `Bar` and its routes nested inside resource `Foo`:

```ruby
# config/routes.rb
resources :foo, param: :foo_id do
   namespace :bar do
     resources :baz, shallow: true
   end
end 
```
if I want to extract code in the `Bar` module to an engine, I move its routes to the engine's route file, and mount it
```ruby
# bar/config/routes.rb
resources :baz, shallow: true

# config/routes.rb
resources :foo, param: :foo_id do
  mount Bar::Engine, at: '/bar'
end
```

I expect to still have the shallow route:
```
foo/bar/baz/:id => bar/baz#show
```

Instead, I have
```
foo/:foo_id/bar/baz/:id => bar/baz#show
```

Effectively, the `shallow: true` is doing nothing, and to get the routing I want I have to declare it in the application instead of the engine.

Is there some obvious alternative that I'm missing?

**Comment by pixeltrix** [comment]
Sorry, there's no way to do what you want as the engines routes are independent of the application's routes and can't intermingle unless you define your engine routes on the application's routes and don't use `mount`.
