### ISSUE TITLE
find_each and find_in_batches don't work with_index

### ISSUE THREAD

**Issue by jayant1992** [rails/rails#20898]
```ruby
Person.find_each.with_index do |person, index|
  person.award_trophy(index + 1)
end

Person.find_in_batches.with_index do |group, batch|
  puts "Processing group ##{batch}"
  group.each(&:recover_from_last_night!)
end
```

Both code samples are from the [official documentation](http://api.rubyonrails.org/classes/ActiveRecord/Batches.html#method-i-find_each)

They give a ```LocalJumpError: no block given (yield)``` error
Both methods should probably return an Enumerable in case a block is not passed

#20125 and #13201 are probably relevant

**Comment by sgrif** [comment]
Hi there! Thanks for the report! Can you give us a script that we can use to reproduce the issue, using [this template](https://github.com/rails/rails/blob/master/guides/bug_report_templates/active_record_master.rb)? Both of these methods return an enumerator without a block, and those code samples should Just Work :tm:

**Comment by timbreitkreutz** [comment]
@jayant1992  -- can you make sure your Gemfile specifies Rails 4.1 or greater?  This feature didn't exist until then. I got the same LocalJumpError you specified when I tried in with 4.0 but not >= 4.1

**Comment by jayant1992** [comment]
@timbreitkreutz -- yeah, just checked, my rails version was 4.0.9 at the time I had this error. Works fine with >= 4.1

**Comment by eileencodes** [comment]
Sounds like we can close this then. @jayant1992 if there's still a problem let me know and I'll reopen.

**Comment by fellipecastro** [comment]
Actually, this issue remains when you pass the parameter batch_size.

Eg: Person.find_each.with_index(batch_size: 1000) do |person, i|
