### ISSUE TITLE
Routes display order is misleading for single 'resource'

### ISSUE THREAD

**Issue by loicteixeira** [rails/rails#20894]
If you define a resource which does not need the id to be part of the url like this:

```
# config/routes.rb
Rails.application.routes.draw do
  resource :profile
end
```

and run `rake routes`, the output will be the following:

```
      Prefix Verb   URI Pattern             Controller#Action
     profile POST   /profile(.:format)      profiles#create
 new_profile GET    /profile/new(.:format)  profiles#new
edit_profile GET    /profile/edit(.:format) profiles#edit
             GET    /profile(.:format)      profiles#show
             PATCH  /profile(.:format)      profiles#update
             PUT    /profile(.:format)      profiles#update
             DELETE /profile(.:format)      profiles#destroy
```

It is misleading because the path helper prefix for the `profiles#show`, `profiles#update` and `profiles#destroy` routes is not `edit_profile` but `profile`. The expected result would look something like:

```
      Prefix Verb   URI Pattern             Controller#Action
     profile POST   /profile(.:format)      profiles#create
             GET    /profile(.:format)      profiles#show
             PATCH  /profile(.:format)      profiles#update
             PUT    /profile(.:format)      profiles#update
             DELETE /profile(.:format)      profiles#destroy
 new_profile GET    /profile/new(.:format)  profiles#new
edit_profile GET    /profile/edit(.:format) profiles#edit
```

The `resource` method is defined in [actionpack/lib/action_dispatch/routing/mapper.rb](https://github.com/rails/rails/blob/a0b4dc21a2188a4379bc401b73336608fec56c64/actionpack/lib/action_dispatch/routing/mapper.rb#L1195-L1203) (namespace `ActionDispatch::Routing::Mapper::Resources`) and by moving things around the order can be rearranged.

I'm new to this and did not feel like creating a pull request but I'd be happy to provide any more information as requested.

**Comment by thejamespinto** [comment]
@loicteixeira maybe simply placing `POST /profile` at the bottom would do the trick.
I was inspired by your commentary so I played with this part of Rails for a while and came up with a solution with readability in mind.
Please take a look.

**Comment by loicteixeira** [comment]
That's awesome. I like that there are some test as well. This is mostly what hold me back, I didn't know how to test the changes.

**Comment by pixeltrix** [comment]
@loicteixeira the blank spaces in the routes output doesn't mean ditto (the name from above), it means that the route doesn't have a path helper because there is already a path helper for that path. The HTTP method has no bearing when generating a path so whenever you use `profile_path` you're using the one defined by the `create` route.

There is a reason they're in the order that they are - the new route comes before the show route for a normal resource otherwise it would match to `resources#show` with an id of `new`. It would be confusing to change the order for singleton resources.

Thanks for your input.
