### ISSUE TITLE
Strange query in 4.1.12

### ISSUE THREAD

**Issue by mmontossi** [rails/rails#20907]
The following test case can be use:

https://gist.github.com/mmontossi/dcf71457e98a169c28a5

I notice an strange query:

SELECT COUNT(*) FROM "products"  WHERE "products"."visible" = 't' AND "products"."visible" = 'f'

Visible is query as true and false at the same time?

**Comment by matthewd** [comment]
Please use the mailing list or StackOverflow for questions/help, where a wider community will be able to help you. We reserve the issues tracker for issues only.

**Comment by mmontossi** [comment]
What I should understand is that this is the desired behavior?

**Comment by matthewd** [comment]
Sorry, that was a bit unclear. Yes, that's expected behaviour.

**Comment by mmontossi** [comment]
Thanks
