### ISSUE TITLE
foreign key references wrong column

### ISSUE THREAD

**Issue by ror6ax** [rails/rails#20912]
I create migration with the following code. My aim is to create foreign keys, which refer to students\subjects\teachers tables, column name:

```
  def change
    create_table :courses do |t|
      t.date :date
      t.string :student_name
      t.string :subject_name
      t.string :teacher_name
      t.timestamps null: false
    end
    
    add_foreign_key :courses, :students, :name =>"student_name", column:  :name, foreign_key: :name
    add_foreign_key :courses, :subjects, :name =>"subject_name", column:  :name, foreign_key: :name
    add_foreign_key :courses, :teachers, :name =>"teacher_name", column:  :name, foreign_key: :name

  end

```

Unfortunately, the result fails with following error:

```
ActiveRecord::StatementInvalid: Mysql2::Error: Key column 'name' doesn't exist in table: ALTER TABLE `courses` ADD CONSTRAINT `student_name`
FOREIGN KEY (`name`)
  REFERENCES `students` (`id`)
```

Why, after specifying column and foreign key it still tries to refer to `id` in students, not `name` ?

The following sql code does the work for me, I just want to make it work Rails-way:

```
create table courses(id int primary key auto_increment, date date, student_name varchar(255),subject_name varchar(255),teacher_name varchar(255), FOREIGN KEY (student_name) references students(name), FOREIGN KEY (subject_name) references subjects(name), FOREIGN KEY (teacher_name) references teachers(name));


```

**Comment by al2o3cr** [comment]
The value passed to `column` should be the name of the foreign key column in `from_table` (`:courses` here). It would be `:student_name`, etc.

`foreign_key` is not a supported option. If the intent is to specify the name of the column in `to_table` (`:students`, etc) then you should use the `primary_key` option.

FWIW, I'd highly recommend considering carefully the use of names as foreign keys; they have an unfortunate tendency to change sometimes.

**Comment by ror6ax** [comment]
The intent is to have 3 foreign keys to 3 different tables and them(foreign keys) being not `id`. 
Thanks for help, though. Activerecord docs are close to useless, for me at least.

**Comment by sgrif** [comment]
We'd love a PR to improve them if they were unclear to you in this case. However, this doesn't appear to be a bug in Active Record. Thanks for the report!
