### ISSUE TITLE
enum with form for "selected" option seems to failed to point the selection

### ISSUE THREAD

**Issue by jerome2** [rails/rails#20910]
Hi,

I have 3 tables (models) linked like this:

Photos (belongs_to :travails), Travails (belongs_to :wconcerns, has_many :photos), Wconcern (has_many :travails)

inside Wconcern model, i have:

"enum categorie: [:no_one, :travails, :voyages]"

so categorie is a column type integer (as indicate by Rails guide about enum definition)

 

Now from a partial "_form" view (form who will be render for new and edit call view), i would like to show a select box who can list the different "categorie(s)" choices, and selected this one exist allready.

i arrived to show "categorie" list of the enum(erate), but not show the selected one.

 

when i do from rails console:

@photo.travail.wconcern.categorie

i have back:

"travails"

and then this is good i think... yes ?

 

but why not works with the _form patial view ?

here is concerned part of the code of my partial _form.haml view 'sorry, i can not attach a file... .haml file can not):

[code]
= simple_form_for(@photo) do |f|
(...)
  .associations
    - if @photo.travail_id || @photo.voyage_id
      = f.association :travail, collection: Wconcern.categories,
                                label: "Categories",
                                selected: @photo.travail.wconcern.categorie,
                                as: :radio_buttons
(...)
[code]

in the view, at render time, the list of radio buttons are good, but there is no selected one. And i don't know why and how to just show the correct selected categorie.

in my table, i can see that the categorie field concerned with the "photo" is well define by an integer (1). then normally, it has to show "travails" case to be selected... but no one is selected.

if i reload the page, i have "voyage" who is selected (very strange) instead of "travails".

what i forgot or done wrong ?

**Comment by jerome2** [comment]
also, i see that if i try this code:

= simple_form_for @wconcern do |x|
            = x.collection_radio_buttons :categorie, Wconcern.categories, :last, :first , selected: give_concerned_categorie
then this not works because the hach or list give by the enum is [["ni-one", 0], ["travails", 1], [voyages", 2]] (inversed) and i think helpers forms collection_select will works only if it would be [[0, "no_one"],[1, "Travails"],[2,"voyages"]]... then at this poitn will works without selected option to maybe.

is it a bug or i forgot something to pass correctly enum type ?

**Comment by jerome2** [comment]
this works:
= simple_form_for @wconcern do |w|
            = w.collection_radio_buttons :categorie, Wconcern.categories, :first, :first, selected: @photo.travail.wconcern.categorie

but i think this is not very good and point the problem of "inverted" form of an enum list and the difficulty for point hte enum (no choice, .categorie give back the title, not the index... no option for ask the index).
is looks like a half-bug

**Comment by sgrif** [comment]
It doesn't appear that any of the code you've mentioned is a bug in the documented behavior of `enum`.

**Comment by jerome2** [comment]
sure, because i not what i said. I said that for use correctly enum with form hrlpers, this is just difficult due to "enum" construction in the design patern. But also, enum not use enum, it is a artificial enum, also difficult to use with helpers, and impossible with form associations.
that is why i said maybe: "half-bugged". right or wrong ?
so i think it is a good place here for signal this and re-open the issue.
