### ISSUE TITLE
Model.find is failing after after_create

### ISSUE THREAD

**Issue by kapso** [rails/rails#20927]
I have a `after_create` callback in model that sends email in a background worker (Sidekiq). However background worker sometimes fails with `ActiveRecord::RecordNotFound` -- meaning the record that was just created cannot be found. Hows that possible? Is it possible that the `after_create` is firing before the data is actually committed? Is it better to use `after_commit :send_welcome_email, on: :create`

```ruby
after_create :send_welcome_email

def send_welcome_email
  UserMailer.delay.welcome(id) # This errors out sometimes
  # UserMailer.delay_for(5.seconds).welcome(id) # This never throws an error
end
```

Gemfile:
```ruby
gem 'rails', '4.2.3'
```

**Comment by sgrif** [comment]
Can you please provide a minimal rails app with a test case defined to demonstrate the behavior?

**Comment by luke-gru** [comment]
This is a common issue with background job libraries, see: https://github.com/mperham/sidekiq/wiki/Problems-and-Troubleshooting#cannot-find-modelname-with-id12345

**Comment by kapso** [comment]
Ah thanks for pointing that out, so it is indeed a commit issue.
