### ISSUE TITLE
AC::Parameters no longer being a Hash has broken nested attributes

### ISSUE THREAD

**Issue by twalpole** [rails/rails#20922]
Since AC::Parameters is no longer derived from Hash, and each nested "hash" inside Parameters is also an instance of AC::Parameters,   https://github.com/rails/rails/blob/master/activerecord/lib/active_record/nested_attributes.rb#L446  raises an error since it only allows Hash or Array, https://github.com/rails/rails/blob/master/activerecord/lib/active_record/nested_attributes.rb#L446 calls #map which isnt supported on AC::Parameters, and https://github.com/rails/rails/blob/master/activerecord/lib/active_record/nested_attributes.rb#L471 calls #with_indifferent_access which isn't supported on AC::Parameters.   

I'm willing to submit a fix if wanted, just wondered whether the preferred solution would be to have AC::Parameters call #to_h on accessed elements so they return filtered hashes rather than AC::Parameters instances, or update the nested_attributes code to support AC::Parameters

**Comment by jonatack** [comment]
Yes. Experiencing this issue as well.

**Comment by jonatack** [comment]
Needs test coverage in addition to a fix. The current test suite is passing.

**Comment by sgrif** [comment]
I've pushed a fix for this problem, and added an isolated test case for it. However I'm going to leave this issue open. This should have never passed CI and I consider our lack of integration test coverage a bug. We need to make sure that we have the tests required to prevent this from happening in the future.

**Comment by jonatack** [comment]
Thank you, Sean, for looking into this. The test passes with the fix and fails without it. However, the issue seems to still be there.

**Comment by twalpole** [comment]
@sgrif Your fix only fixed this issue for singular associations - PR# 20932 continues that for collection associations

**Comment by jonatack** [comment]
@twalpole Good call. Tried your PR and it seems to fix the remaining issue.

**Comment by sgrif** [comment]
I've opened a separate issue for the testing problem.

**Comment by sgrif** [comment]
I forgot the link (https://github.com/rails/rails/issues/20945)
