### ISSUE TITLE
flash messages are empty with rails 3.2.22

### ISSUE THREAD

**Issue by krishnarohitreddy** [rails/rails#20948]
controller

 elsif @foo.errors[:bar].any?
      flash[:notice] = "Sorry no longer available."
      redirect_to xxx
end

but in views flash notice is empty

**Comment by matthewd** [comment]
Rails 3.2 is no longer supported

**Comment by krishnarohitreddy** [comment]
Mine problem is something else
The problem was that it redirects twice. When that happens with 3.2.22, i have passed it in args and that worked for me. Any ways thanks for the responding
