### ISSUE TITLE
coffeescript files from views are embeded inside a "function"

### ISSUE THREAD

**Issue by jerome2** [rails/rails#20942]
difficult to use simply coffeescript code from views just because the code is embeded inside a function.
I don't know and i don't understand why this choice, but this is not funny.

is there a reason for doing that ?
what could be the solution to use coffeescript file without have it embeded inside a function by default ?

**Comment by sgrif** [comment]
This is not a bug in rails. Please go ask this on https://github.com/jashkenas/coffeescript/ or StackOverflow.

**Comment by jerome2** [comment]
ok, thank you i will post question this place.
