### ISSUE TITLE
app/views/layout/application.haml failed with use of ajax

### ISSUE THREAD

**Issue by jerome2** [rails/rails#20941]
if my application layout is named "application.html.haml", then ajax (remote true) mechanism works fine, if i change this name by "application.haml", ajax mechanism failed to execute normaly the javascript file

**Comment by sgrif** [comment]
We reserve the issues tracker only for bugs in Rails. I recommend asking this question on the mailing list, or StackOverflow.

**Comment by jerome2** [comment]
But in practice: i can no ask question on stakoverflow... could you ask for me ? Or i have to conclude that it is impossible to ask this question for me ?
please... open mind or do something for we can communicate easy. It becomes difficult to just have an answer to a question (and i don't know why).
This question is a question for rails devs... it could be a bug or not, but, if it is not a bug and if there is a reason of that, why just, in practice, refused to answer ? 
please...

**Comment by sgrif** [comment]
The Rails team is not tech support. If we answer your questions here, we would have to handle all of them and we do not have the man power to do so. There are other forums for you to get help, I would recommend you go there. Sorry.

**Comment by jerome2** [comment]
ok, i understand well, sorry.
Also if you have a good link where the politic is not to stretch or elitist, i would be happy to go there for have a way to ask a question and find people could answer (and also answer myself some other questions).
thanks and sorry again.
