### ISSUE TITLE
How to run Gradle(android Studio) project in Eclipse LUNA

### ISSUE THREAD

**Issue by sunjithc** [rails/rails#20978]
I import the project but i can't know how to run the project..

![untitled](https://cloud.githubusercontent.com/assets/12294662/8822940/afd0a5fa-3086-11e5-9205-48d0b5a631dc.jpg)
![run](https://cloud.githubusercontent.com/assets/12294662/8822939/af972028-3086-11e5-85f4-2e291d3cfd5a.jpg)

**Comment by kaspth** [comment]
Don't see how this has anything to do with Rails. Good luck :)
