### ISSUE TITLE
BigDecimal number_to_currency

### ISSUE THREAD

**Issue by exsurgolabs** [rails/rails#20979]
Have an issue using a float in the number_to_currency  method in ActionView::Helpers::NumberHelper

Because this method uses a float there is a loss in accuracy especially when using big numbers. 

Would it be possible to have this method only use BigDecimals in order to keep accuracy. 

Example code I'm working on is 

    number_for_currency = BigDecimal.new('99999999999999700.0') 
    return_value = number_to_currency(number_for_currency, precision: 0, unit: '')

returns 

    99,999,999,999,999,696 instead of 99,999,999,999,999,700

**Comment by maurogeorge** [comment]
Hi @exsurgolabs thanks for the report.

Not sure if this is a Rails problem, I think it is a Ruby stuff. If you try:

```ruby
precision = 0
number_for_currency = BigDecimal.new('99999999999999700.0')
"%00.#{precision}f" % number_for_currency # => 99999999999999696
```
As you can see it loss accuracy.

Rails [rounds the number to a `Fixnum` before send](https://github.com/rails/rails/blob/52cf1a71b393486435fab4386a8663b146608996/activesupport/lib/active_support/number_helper/number_to_rounded_converter.rb#L36) to the [`sprintf`](http://ruby-doc.org/core-2.2.0/Kernel.html#method-i-sprintf) but we got the same result with a `Fixnum`.


```ruby
precision = 0
number_for_currency = 99999999999999700
"%00.#{precision}f" % number_for_currency # => 99999999999999696
```

**Comment by meinac** [comment]
This is not a rails bug, I believe you are using ruby version under `2.1.1`, I've tested this with ruby versions `2.0.0`, `2.1.1` and `2.2.2` I could reproduce this bug with only ruby `2.0.0` try to upgrade your ruby version at least `2.1.1` and things will work as you expected.

**Comment by exsurgolabs** [comment]
Yeah thank's for this, working in a corporate development environment so switching versions to check isn't easy. Had my suspicions about the ruby version however. Thanks for the replies
