### ISSUE TITLE
Postgresql Adapter Fails Silently if psql is not installed

### ISSUE THREAD

**Issue by workmaster2n** [rails/rails#20980]
I was running `db:structure:load` but was not getting any of my database structure loaded.  I also was not getting any errors.

Digging through the source code, I came to this line (https://github.com/rails/rails/blob/master/activerecord/lib/active_record/tasks/postgresql_database_tasks.rb#L70):

` Kernel.system("psql -X -q -f #{Shellwords.escape(filename)} #{configuration['database']}")`

This line will fail silently if `psql` is not installed. 

I ran into this problem in my production environment where my machine did not have the `postgresql` package installed.

I was able to fix this issue by installing the correct psql client.

Should we perhaps check that `psql` is a valid executable before running any psql commands?

**Comment by nateberkopec** [comment]
Actually, `Kernel.system` will return false (and thus `structure_load`) will return false if the command exits with non-zero exit status.

Perhaps if `structure_load` returns false we should fail more loudly - this would also cover other "silent failures" other than just psql not being installed. Perhaps just output something to `$stderr`?

**Comment by workmaster2n** [comment]
Does it return `false` or `nil`? I was seeing `nil`, but that could be due to `pry`

**Comment by matthewd** [comment]
This is a duplicate of #17666 / #17885.
