### ISSUE TITLE
ActiveRecord has_one associations not working after deserialization

### ISSUE THREAD

**Issue by mmontossi** [rails/rails#20988]
Is this the expected behavior? I couldn't find any reason in the documentation of this outcome and others associations like has_many and belongs_to are working properly.

I made this test case: https://gist.github.com/mmontossi/0e7210b727b2265c6d50

**Comment by meinac** [comment]
This is working as expected in Rails versions `4.2.1`, `4.2.2` and `4.2.3`

**Comment by mmontossi** [comment]
Thanks @meinac I just updated the app to 4.2.3 and everything is working fine.
