### ISSUE TITLE
Save many-to-many objects based on association primary key

### ISSUE THREAD

**Issue by himesh-r** [rails/rails#20995]
I have a scenario where I am using a primary key different than id.
```ruby
  class Client < ActiveRecord::Base
    has_many :clients_health_conditions, primary_key: :ext_id
    has_many :health_conditions, through: :clients_health_conditions, primary_key: :ext_id
  end
```

So when I try to associate the two models in this way:

```ruby
  @client.health_condition_ids = ['4']
```

It gives me an error because, as per rails 'ids_writer' method, it checks for an object with id = 4, not considering my association primary_key. I guess it should be considering association primary_key.

**Comment by himesh-r** [comment]
This issue still exists in master branch.

The fix is already committed and needs merging.

**Comment by arthurnn** [comment]
https://github.com/rails/rails/commit/bcd0c8cfc250039ddc145c3302633c4890880930 should fix the problem on master.
