### ISSUE TITLE
AC::Parameters no longer being a Hash has broken find_or_initialize_by

### ISSUE THREAD

**Issue by twalpole** [rails/rails#20990]
Strong parameters can no longer be passed to find_or_initialize_by since it expects a Hash to be passed through to the find_by cal which errors with "Cannot visit ActionController::Parameters.

**Comment by MRageh** [comment]
@twalpole I am not sure but this commit may be relevant to this issue https://github.com/rails/rails/commit/68af63618223c238468af1afb093eb4ccc706761

**Comment by jonatack** [comment]
And #20945 / #20922.

I'm seeing various kinds of breakage from the AC::Parameters changes.

**Comment by jaredbeck** [comment]
In case anyone is curious (I was) about why Parameters no longer inherits Hash, it's explained in this commit: https://github.com/rails/rails/commit/14a3bd520dd4bbf1247fd3e0071b59c02c115ce0

**Comment by sikachu** [comment]
@sgrif would you mind taking a look at this? Your commit was referred to in the first comment.

**Comment by sgrif** [comment]
Yup, I'm on vacation but I'll look when I get back

**Comment by twalpole** [comment]
This was fixed by PR #21000

**Comment by sgrif** [comment]
thanks
