### ISSUE TITLE
Under concurrent load Dependencies.interlock might miss file changes

### ISSUE THREAD

**Issue by thedarkone** [rails/rails#21006]
While helping @mperham in #20989 I realized that the current code (under concurrent load) is broken.

The problem arises if there are multiple threads in app space region of `Dependencies.interlock`, then an `.rb` file is changed. Next thread arrives at `ActionDispatch::Reloader` middleware, it invokes `reloaders` to check if any of the files have changed, and indeed there is a change, the thread attempts to grab an exclusive `Dependencies.interlock` (via poll) does not succeed (because of those other threads in app space) and proceeds on.

However `reloaders` report a change in `.rb` file only once, subsequent calls to `updated?` return `false`, this is because since the last time `updated?` has been invoked nothing has changed, so if an exclusive grab of `Dependencies.interlock` was not successful a change to `.rb` file is "lost".

Additionally, if a typical use case of `sidekiq` is somewhat similar to @mperham's example in https://github.com/rails/rails/pull/20928#issuecomment-123876079, I'm fairly confident that even if the "lost" `.rb` change issue is fixed, unless `unloading` is blocking (and an attempt to obtain an exclusive lock blocks out new readers), then update is going to be probably "starved" anyways.

/cc @matthewd

**Comment by matthewd** [comment]
Yeah.. I was thinking of the `reload_classes_only_on_change=false` case, where polling would eventually work (and more importantly, a wait would be pointless: it would by definition unblock at the same moment that the "last" request finished).

Having reminded myself that we've actually been doing a reload at the *start* of requests for several years, I agree we should block; given the choice, it's infinitely better that the first request arriving after the file change, regardless of concurrency, can insist on running under the latest available code.

I'm still on the fence about blocking new requests while we're awaiting the load lock, but if we need to do so for the unload lock, it's probably simpler to just make it a general rule unless/until I can present an actual argument in favour of the starvation-prone behaviour.

**Comment by mperham** [comment]
Anyone know the latest status of Interlock and this issue?

**Comment by matthewd** [comment]
@mperham I knew I wanted to come back and settle on a public API, but had forgotten there was still some Proper Thinking to iron out. :sweat_smile: 

I'll get it sorted in the Very Near Future.
