### ISSUE TITLE
to_partial_path namespaced model - wrong path

### ISSUE THREAD

**Issue by olegantonyan** [rails/rails#21004]
Rails 4.2.3
```ruby
# app/models/user.rb
class User < ActiveRecord::Base
  has_one :profile
end

# app/models/user/profile.rb
class User::Profile < ActiveRecord::Base
  belongs_to :user
end
```

In this case when you use `render @user.profile` you get missing template because:
```
User::Profile.first.to_partial_path
=> "user/profiles/profile"
```
But templates related to users are stored in `users/`, not `user/`, so I expect templates for nested models there as well.

**Comment by mjhoy** [comment]
I believe this is the expected behavior. See the test case here:

https://github.com/rails/rails/blob/9caf2cbf268137113447ac8156b862b5d84063b5/activemodel/test/cases/conversion_test.rb#L47-L49

**Comment by FlySnake** [comment]
But why? I cannot imagine a reason except historical.

**Comment by mjhoy** [comment]
the general case is that you are namespacing by modules; the fact that `User` is also an active model class is incidental. see for instance how namespaces are used in this post: http://www.iain.nl/backends-in-rails-3-1

i agree in this case it's slightly unexpected and should maybe be documented a little better.

**Comment by olegantonyan** [comment]
Thanks @mjhoy , now I understand why it works this way.
I created a tiny gem to override this behaviour in my projects. Just in case someone else find it useful https://github.com/olegantonyan/partial_namespaceble

**Comment by mjhoy** [comment]
@olegantonyan perhaps close the issue?
