### ISSUE TITLE
ActiveRecord source plus inverse_of possibly broken in rails 4.2.x 

### ISSUE THREAD

**Issue by mmontossi** [rails/rails#21002]
I notice you can't use source and inverse_of in rails 4.2 without explicitly telling class_name, this was working well in 4.1.

I made this test case: https://gist.github.com/mmontossi/c42ad1249de522e7bf68

**Comment by mayurkhatri** [comment]
Hi @mmontossi.I ran you test case for rails 4.1.12 with ruby-2.2.2, got this error ActiveRecord::InverseOfAssociationNotFoundError: Could not find the inverse association for owners (:user in User).
For rails 4.2.3 with ruby-2.2.2, got the error : NameError: uninitialized constant Shop::Owner

**Comment by sgrif** [comment]
As per the guides, `inverse_of` is not supported on through associations. http://guides.rubyonrails.org/association_basics.html#bi-directional-associations

**Comment by mmontossi** [comment]
@mayurkhatri I have a very similar case in an app using 4.1.12 and it's not throwing an exception, either way, but I couldn't reduce the problem to a test case, so I was wrong about the this being working on 4.1.

**Comment by mmontossi** [comment]
@sgrif maybe would be better to make inverse_of do nothing if there is through or raise an exception instead of break?

**Comment by sgrif** [comment]
Feel free to open a PR.

**Comment by al2o3cr** [comment]
@sgrif - In the process of reproducing #21466, I ran into this exact thing.

Test case:
https://gist.github.com/al2o3cr/3b694da67151e47912a5

It's a minor regression (changing an ignored option to an error) but an annoying one if there are stray `inverse_of`s in a large codebase.

I'll put together a PR for this in the next couple days.
