### ISSUE TITLE
wrap_parameters not including GET parameters

### ISSUE THREAD

**Issue by thenadz** [rails/rails#21011]
Rails: 4.2.3 | Ruby: ruby 2.1.1p76 (2014-02-24 revision 45161) [x86_64-linux]

It really is as simple as the title suggests. According to the [documentation](http://api.rubyonrails.org/classes/ActionController/ParamsWrapper.html), `wrap_parameters` only applies to `POST` requests, so it's possible this is intended behavior, but it would seem that the functionality is just as applicable to `GET` parameters. So, depending on whether `POST` was really the only intended wrappable HTTP method, this is either an enhancement request or a bug report.

In any event, I've got param wrapping working as expected with `POST`ed `JSON`, but trying the same logic in a different controller which receives URL parameters results in no wrapping. Manually wrapping and sending to the same controller works.

I think this is a straightforward issue, but I'm happy to elaborate if needed.

**Comment by jvanbaarsen** [comment]
@thenadz Since there is at least one testcase for a GET call, I think this is intended behaviour and the documentation needs to be updates.

```ruby
  #actionpack/test/controller/params_wrapper_test.rb:192
  def test_preserves_query_string_params
    with_default_wrapper_options do
      @request.env['CONTENT_TYPE'] = 'application/json'
      get :parse, params: { 'user' => { 'username' => 'nixon' } }
      assert_parameters(
        {'user' => { 'username' => 'nixon' } }
      )
    end
  end
```

@rafaelfranca What do you think?

**Comment by thenadz** [comment]
@jvanbaarsen, thanks for the quick response, but if this functionality is intended to include `GET` params then my results indicate that this is not working.

My controller looks like this:
```ruby
  1 class SubscriptionsController < ApplicationController
  2   include ApiAuthenticate
  3
  4   # allow API actions to respond to JSON
  5   respond_to :json
  6
  7   wrap_parameters format: :json, include: %i[ nonce timestamp checksum uid ]
  8
  9   before_action :authenticate
 10
 11   def show
 12   end
 13
 14   private
 15     def authenticate
 16       logger.debug 'Authenticating subscription req'
 17       api_authenticate subscription_params
 18     end
 19
 20     def subscription_params
 21       params.require(:subscription).permit(%i[ nonce timestamp checksum uid ])
 22     end
 23 end
```

But the logs indicate that no wrapping occurs. Am I missing something? This matches what I'm doing in other controllers where `POST`ed JSON is the only concern.
```
Started GET "/subscription.json?uid=13a304bf-d9a0-47a3-bc45-0dd10531a08c&nonce=93b1bd1e7bea16e065030b1f2694326c&timestamp=1437740337&checksum=664a56fbd9152511334ad542988ca003d7e604b2a829a7ef828585ec96eec18b" for 127.0.0.1 at 2015-07-24 07:22:49 -0500
Processing by SubscriptionsController#show as JSON
  Parameters: {"uid"=>"13a304bf-d9a0-47a3-bc45-0dd10531a08c", "nonce"=>"93b1bd1e7bea16e065030b1f2694326c", "timestamp"=>"1437740337", "checksum"=>"664a56fbd9152511334ad542988ca003d7e604b2a829a7ef828585ec96eec18b", "subdomain"=>"api"}
```

**Comment by jvanbaarsen** [comment]
I believe this is a PR that will fix the docs: https://github.com/rails/rails/pull/21031
