### ISSUE TITLE
Update CONTRIBUTING.md

### ISSUE THREAD

**Issue by maclover7** [rails/rails#21028]
Would it make sense to move the bulk of Rails' contributing guide to CONTRIBUTING.md? I think this would make getting started for beginners much easier.

Also, I think @sgrif mentioned this on The Bike Shed? :bike:

**Comment by fxn** [comment]
No, the file links to the guide.

Guides are our uniform place for docs, including release notes, guidelines, etc.

Someone willing to patch Rails should be able to follow a link.
