### ISSUE TITLE
Custom ActiveModel validations can only be declared once

### ISSUE THREAD

**Issue by mlarraz** [rails/rails#21029]
If I define a custom validation method and try to set multiple callbacks for it (say, with different options), only the last one will take effect.

```ruby
require 'active_model'

class Foo
  include ActiveModel::Model

  attr_accessor :bar, :baz

  validate :bar_equals_baz, if: -> { bar.present? }
  validate :bar_equals_baz, if: -> { baz.present? } # overwrites callback above

  def bar_equals_baz
    errors.add(:base, "bar must match baz") unless bar == baz
  end
end

foo = Foo.new

foo.bar = 'bar'
foo.valid? # => true, should be false

foo.bar = nil
foo.baz = 'baz'
foo.valid? # => false
```

This is unlike built-in validations on attributes, which can be set repeatedly without clobbering each other.

In this example it's trivial to fix by combining the two conditions into a single lambda
```ruby
validate :bar_equals_baz, if: -> { bar.present? || baz.present? }
```
but for more complex options this gets very tedious.

This can also be avoided by passing a string one time and a symbol another:
```ruby
validate :bar_equals_baz,  if: -> { bar.present? }
validate 'bar_equals_baz', if: -> { baz.present? }
```

Or just a proc both times:
```ruby
validate -> { bar_equals_baz }, if: -> { bar.present? }
validate -> { bar_equals_baz }, if: -> { baz.present? }
```

**Comment by meinac** [comment]
I think overriding is what we want because If you want to change the logic of the `:if` option of a callback which inherited from a superclass then you have to override it.

**Comment by rafaelfranca** [comment]
Exactly. This is also the same behavior of callbacks
