### ISSUE TITLE
update_all and update_columns does not work with not operator

### ISSUE THREAD

**Issue by NielsKSchjoedt** [rails/rails#21038]
The following works:

```ruby
Car.where(brand: 'Ford', number_of_doors: 4).update_all(number_of_doors: 5)
```

However if using the `not` operator, then it throws an error:

```ruby
Car.where.not(brand: 'Ford', number_of_doors: 5).update_all(number_of_doors: 5)
#=> ActiveRecord::ActiveRecordError: No integer type has byte size 10. Use a numeric with precision 0 instead.
```

Same goes for `update_columns`

I'm using rails 4.1.10. The column looks lige this in the schema: `number_of_doors integer DEFAULT 0,`

**Comment by rafaelfranca** [comment]
Could you create a reproduction script with this template https://github.com/rails/rails/blob/master/guides/bug_report_templates/active_record_master.rb?

**Comment by repinel** [comment]
With this script it passes for `4.1.10` and `master` https://gist.github.com/repinel/b1f3a60afaca27f0f7fe

@NielsKSchjoedt Could you check it to see if it's covering your case?

**Comment by smeade** [comment]
Can confirm also passes with Car and attributes posted by @NielsKSchjoedt. https://gist.github.com/smeade/555a13b4d2fee9d6fccf

@NielsKSchjoedt: That error is raised when `limit:` is < 8 for postgresql migrations (https://gist.github.com/rails/rails/blob/4-1-stable/activerecord/lib/active_record/connection_adapters/postgresql/schema_statements.rb#L478). But it's expected that you would see it during migration. Is the error you posted returned when running the `Car.where.not` clause in console, or is it independent of the `Car.where.not` operation?

Perhaps try checking your code for `limit: 10` or `limit:10` and change to `limit: 8`.
