### ISSUE TITLE
Enqueuing jobs inside a job can lead to memory bloat

### ISSUE THREAD

**Issue by pixeltrix** [rails/rails#21036]
On the [UK Parliament and Government petitions website](https://petition.parliament.uk) we're queuing up emails to be sent using a background job and `deliver_later` so that the email sending is not limited to one worker thread. Essentially the code looks somewhat like this:

``` ruby
class EmailSignees < ActiveJob::Base
  def perform(petition)
    petition.signatures.find_each do |signature|
      PetitionMailer.notify_signee_of_response(petition, signature),deliver_later
    end
  end
end
```

The problem is that even though we are using `find_each`, because Active Job uses a single log subscriber for both `enqueue` and `perform` events the `deliver_later` call gets treated as a child event of the `perform`event so eventually we end up with 100,000+ objects in the event object even though we're using `find_each`. This obviously causes the worker to eventually crash due to a lack of memory.

The questions are:
1.  is this behaviour intentional?
2.  do we want to keep this behaviour, given the above scenario?
3.  if it is intentional and we want to keep it, what's the solution?

For question 3 there are multiple ways of working round it I can think of, just wondering what our recommendation would be.

**Comment by rafaelfranca** [comment]
I'd say:

1. No
2. No

I can't see any good reason to share the same subscriber.

**Comment by pixeltrix** [comment]
@rafaelfranca turns out that this behaviour [is explicitly tested for][1]. The test was added in rails/activejob@6eb163a - @cristianbica was this an explicit change that was requested by someone?

[1]: https://github.com/rails/rails/blob/bc3956c/activejob/test/cases/logging_test.rb#L89-L99

**Comment by cristianbica** [comment]
In the initial implementation the tags weren't nested. This is the original PR that contained that commit https://github.com/rails/activejob/pull/61

**Comment by cristianbica** [comment]
See comment https://github.com/rails/activejob/pull/61#issuecomment-44421759

**Comment by cristianbica** [comment]
I'm not aware of what's the architecture of LogSubscriber but I will take a look. I'm not sure if having two subscribers will fix any other similar edge cases.

**Comment by pixeltrix** [comment]
@cristianbica the way that the `Subscriber` class works is that any events that happen inside a parent event are added to an array of child events. I could see how this is useful but then we also don't want to add 100,000 elements to that array either. If we want to keep this behaviour we should point out the possibility of high memory usage in the guide so that other people don't have the same problem that we had.

**Comment by cristianbica** [comment]
@pixeltrix but by using two log subscribers one for enqueuing and one for performing like you did here https://github.com/alphagov/e-petitions/pull/359 fixes the problem, right?

**Comment by pixeltrix** [comment]
@cristianbica yes, that fixes the problem but will break the nested job test if I make the change in Active Job so just trying to work out whether the behaviour is intentional or just a consequence of the original implementation being a single log subscriber.

**Comment by cristianbica** [comment]
I think the nested logging is a nice to have rather than a mandatory
feature. Behavior is intentional as requested by dhh. But I think we should
drop nested logging to fix the memory issue. @dhh wdyt?
