### ISSUE TITLE
Super weird pluralization and singularization inflections

### ISSUE THREAD

**Issue by MitchellGeere** [rails/rails#21046]
I found the strangest thing today.  I put together a little [library](https://github.com/Daybear/grammarize) to help myself with some grammatical inflections and part of that required me to add the plural / singular combinations of the pronouns. 

I added them as irregulars because it is what makes sense. However I have two that are misbehaving:

```ruby
  inflect.irregular "my", "our"
  inflect.irregular "me", "us"
```

What happens is I happen to have two models that get messed with by each. The first is Hours / Hour and the second is Menus / Menu. I end up with routes like "hmy_path" instead of "hour_path" or "menme_path" instead of "menu_path". It made for some interesting hair pulling. 

I temporarily fixed this by adding the following: 

```ruby
  inflect.irregular "hour", "hours"
  inflect.irregular "menu", "menus"
```

However that is nothing more than a bandaid and I'm sure I will see more surprises soon. Now I understand why I am getting the error because the inflector wants to optimally utilize every added word combination to maximize its performance in converting other similar words to their respective forms. In this case I think it shouldn't be allowed to do so or at least require the full match of both parts of the plural / singular split. 

Is there a permanent workaround I could implement in my library to circumvent this issue going forward especially for others who may use the library.

**Comment by pixeltrix** [comment]
In a application using `irregular` is the recommend way of making sure the pluralization is correct, e.g from the comments for `ActiveSupport::Inflector::Inflections`:

```
# New rules are added at the top. So in the example above, the irregular
# rule for octopus will now be the first of the pluralization and
# singularization rules that is runs. This guarantees that your rules run
# before any of the rules that may already have been loaded.
```

However since you're writing a library and a user may call `clear` I would use a different stack of rules like you have for `gender` and `person` - that way you can have much more control over what happens and when.
