### ISSUE TITLE
Rails 4.2.2: limit being removed during db:migrate when limit and array are both specified on an integer field

### ISSUE THREAD

**Issue by ThatsNinja** [rails/rails#21042]
I'm attempting to uplift an existing project to Rails <~ 4.2.0. This project relies upon Postgres, and I'm attempting to store 64-bit integers in an array.

When using the following in a migration:
`t.integer  :intfield, array: true, :limit => 8`

This is generated in the resulting *schema.rb*:
`t.integer  "intfield",                                          array: true`

The limit is being lost in translation. This issue was listed as fixed with pull #19447, but persists in Rails 4.2.2, unless it's the case that I'm doing something foolish.

**Comment by rafaelfranca** [comment]
Should be fixed now at 4-2-stable branch.
