### ISSUE TITLE
Exception Backburner::Job::JobTimeout -> ActiveJob::QueueAdapters::BackburnerAdapter::JobWrapper hit 119s timeout.

### ISSUE THREAD

**Issue by ancyabraham** [rails/rails#21055]
How can we set timeout per job when using activejob. I have a global config file for backburner.
Backburner.configure do |config|
    config.beanstalk_url    = ["beanstalk://127.0.0.1"]
    config.tube_namespace   = "mysite.development"
    config.on_error         = lambda { |e| puts e }
    config.max_job_retries  = 3 
    config.retry_delay      = 5 
    config.default_priority = 65536
    config.respond_timeout  = 300
    config.default_worker   = Backburner::Workers::Simple
    config.logger           = Logger.new(STDOUT)
    config.reserve_timeout  = nil
  end
end

And i have a job file MyJob.

class MyJob < ActiveJob::Base
  queue_as 'sample-job'

  def perform()
end

Is it possible to set a timeout for MyJob

**Comment by kaspth** [comment]
.Please use the Ruby on Rails talk mailing list or StackOverflow for questions/help, where a wider community will be able to help you. We reserve the issues tracker for issues only. Thanks :heart:
