### ISSUE TITLE
Can't redirect to the same URL with a forward-slash appended

### ISSUE THREAD

**Issue by lukehorvat** [rails/rails#21068]
I have the following static redirect in my `routes.rb` (Rails 4.2.3):

```ruby
Rails.application.routes.draw do
  get '/app', to: redirect('/app/')
end
```

Basically, I want `/app` to always append a forward-slash to the URL. But it doesn't seem to do work; Rails simply doesn't perform a redirect when visiting `/app`.

However, if I specify some *other* path to redirect from, it works!

```ruby
Rails.application.routes.draw do
  get '/ui', to: redirect('/app/')
end
```

In this case, Rails successfully redirects `/ui` to `/app/`.

Quite strange. Have I stumbled across a bug here?

**Comment by lukehorvat** [comment]
Ah. I have a file at `public/app/index.html`. It looks like that file is served when `/app` (without the forward-slash`) is requested, overriding the redirect.

Still, is there any way I can get the redirect working? Basically, `public/app/index.html` references some scripts and stylesheets using relative paths. At `/app/`, the relative paths works fine; at `/app`, they are all screwed up. :/

**Comment by atul-shimpi** [comment]
As i understaood, when u send localhost:3000/app you are directed to index.html.
Can u send me your routes.rb file.
I tried to reproduce this with Rails 4.2.3, Its giving below error

==============================
No route matches [GET] "/app"

Rails.root: /home/ashimpi/projects/my_profile
Application Trace | Framework Trace | Full Trace

Routes

Routes match in priority from top to bottom

You don't have any routes defined!

    Please add some routes in config/routes.rb.
    For more information about routes, please see the Rails guide Rails Routing from the Outside In.

Helper 	HTTP Verb 	Path 	Controller#Action
Path / Url 			
Request

**Comment by pixeltrix** [comment]
Currently Rails doesn't distinguish between routes with or without a trailing slash - they are treated as the same route. Therefore the redirect to `/app/` in your routes file is matched by the route itself. If you remove the route and have Apache/nginx serve the `/app` path then they will handle the redirect to the path with the trailing slash.

**Comment by lukehorvat** [comment]
I ended up using the [rack-rewrite](https://github.com/jtrupiano/rack-rewrite) gem to solve this.

```ruby
config.middleware.insert_before 0, Rack::Rewrite do
  r301 '/app', '/app/'
end
```
