### ISSUE TITLE
Can ruby 2.2 be used in a Rails 4.0 project?

### ISSUE THREAD

**Issue by apux** [rails/rails#21078]
Hi.

I'm working with a Rails 4.0.13 project and Ruby 2.1.6. I tried to update Ruby to 2.2.2 but I got an error when trying to run my tests because of the minitest/unit file.

I also tried to add `minitest`, `minitest-rails`, and `test-unit` gems to the project but the error remains.

I created a vanilla project (with a scaffold) to show this behaviour.

https://github.com/apux/railsminitest

The project has 5 branches: `ruby-2.1`, `ruby-2.2.2` and `ruby-2.2.2-with-minitest-rails`, `ruby-2.2.2-with-test-unit` and `ruby-2.2.2-with-minitest-rails-and-test-unit`.

`rake` can run in `ruby-2.1` but it fails in the others. For example:

```
➜  railsminitest git:(ruby-2.2.2) rake
rake aborted!
LoadError: cannot load such file -- minitest/unit
```
Is Rails 4.0 supposed to work with Ruby 2.2? Do I have to do anything else to have it working?

Thanks.

**Comment by rafaelfranca** [comment]
I tested your vanilla project and it worked with both Ruby 2.1 and Ruby 2.2. It seems to be something wrong with your Ruby installation.

Thank you for the detailed report.

**Comment by shakycode** [comment]
I also tested with Ruby 2.1.1 and Ruby 2.2.2 and had no problem FYI

**Comment by apux** [comment]
I just tested it in a new virtual machine and it seems to work. Now I have to check my local enviroment.
I'm sorry guys for wasting your time.
Thank you for the quickly answer.
