### ISSUE TITLE
[edge guides] [Active Job Basics] Unclear information about queueing a job with args

### ISSUE THREAD

**Issue by dhiachou** [rails/rails#21073]
I believe that the section " 3.2 Enqueue the Job " misses information about how to pass arguments to the job. I assume the mentioned "record" is a passed argument to the perform method. It would be clearer to mention it.

## Original text : 
> 3.2 Enqueue the Job

> Enqueue a job like so:
>```ruby
> # Enqueue a job to be performed as soon the queuing system is
> # free.
> MyJob.perform_later record
> # Enqueue a job to be performed tomorrow at noon.
> MyJob.set(wait_until: Date.tomorrow.noon).perform_later(record)
> # Enqueue a job to be performed 1 week from now.
> MyJob.set(wait: 1.week).perform_later(record)
> ```

> That's it!

**Comment by embedMaster** [comment]
Please edit this to make the quoted text unformatted as it is just a code and not a markdown. My browser didn't allow me to edit.

**Comment by repinel** [comment]
@embedMaster Would you care to create a PR?

**Comment by embedMaster** [comment]
@repinel  I will do that ASAP

**Comment by robin850** [comment]
Fixed by #21120. Thank you guys!
