### ISSUE TITLE
how to pass custom keys to the has_one and has_many relationships

### ISSUE THREAD

**Issue by aravindgd** [rails/rails#21081]
I searched the docs and found that I cannot pass custom options to the relationship definitions. For example:
```
has_many :posts, custom_keys: { test_key: :value}
```
 I want it so that I can do a reflect_on_all_associations and find that custom key to do run my own custom code.

**Comment by repinel** [comment]
Can you just rely on the name of the association for that model? Would you care to share a case?

**Comment by matthewd** [comment]
I don't think we're likely to add this; to access the value again, you'd need to be going through the at-best "semi-published" reflection APIs. 

However: we prefer to reserve the issue tracker for issues; please use the rails-core mailing list to propose new features. Alternatively, if it's not too complex to implement, a pull request would give us something more concrete to discuss.
