### ISSUE TITLE
ActiveRecord borken for arel tables

### ISSUE THREAD

**Issue by jstin** [rails/rails#21084]
We make use of `Model.arel_table` to eager load some of our more complex queries. This is now broken with active record 4.2.3. The commit in question is (https://github.com/rails/rails/commit/c99bea1df015eeff4764e2d886de90620ab9fb67)

Here is a simplified test of what is going on. In particular the line 
```ruby
  where(test_parent_id: TestChild.arel_table[:test_parent_id]).grownup
```

```ruby
  require 'test_helper'

  ActiveRecord::Schema.define do
    drop_table(:test_parents, if_exists: true)
    drop_table(:test_children, if_exists: true)

    create_table :test_parents  do |t|
      t.string :name
    end

    create_table :test_children  do |t|
      t.integer :test_parent_id
      t.integer :age
    end
  end

  class TestParent < ActiveRecord::Base
    has_many :test_children
    has_many :grownup_children, -> {
      where(test_parent_id: TestChild.arel_table[:test_parent_id]).grownup
    }, :class_name => "TestChild", :source => :test_children
  end

  class TestChild < ActiveRecord::Base
    scope :grownup, -> {where('age > 18')}
  end

  class BrokenTest < ActiveSupport::TestCase
    test "face" do
      parent = TestParent.create(:name => 'Fred')
      old_child = parent.test_children.create(:age => 19)
      young_child = parent.test_children.create(:age => 13)

      assert_equal 1, parent.grownup_children.count
    end
  end
```

The method causing this to fail is `ActiveRecord::PredicateBuilder.self.can_be_bound?` 

The reason is the param in that method, `value`, is `#<struct Arel::Attributes::Attribute>` 

This is the monkey patch we are using in our app as a temporary fix:

```ruby
module ActiveRecord
  class PredicateBuilder # :nodoc:
    def self.can_be_bound?(value) # :nodoc:
      !value.nil? &&
        !value.is_a?(Hash) &&
        !value.is_a?(Struct) &&
        handler_for(value) == BASIC_OBJECT_HANDLER
    end
  end
end
```

However I feel that the old way (https://github.com/rails/rails/commit/c99bea1df015eeff4764e2d886de90620ab9fb67#diff-bf6dd6226db3aab589916f09236881c7L969) was a whitelist and this new approach is a blacklist, so there might be other things to check for beyond just `Hash` and `Struct`.

**Comment by rafaelfranca** [comment]
cc @sgrif

**Comment by sgrif** [comment]
Arel is a private internal implementation detail, not public API. This doesn't fall under supported usage. Can you give an example of a use case that `where('"test_parents"."id" = "test_children"."test_parent_id")')` doesn't handle here?

**Comment by jstin** [comment]
The issue comes from a more complex query using `eager_load`. I tried to use the equivalent of `where('"test_parents"."id" = "test_children"."test_parent_id"')` for our actual query (`where('"warehouse_mtrs"."line_number"="sales_order_line_items"."line_number"')`), and it does not build the correct SQL. Here is the relevant difference:

```SQL
...
LEFT OUTER JOIN 
"warehouse_mtrs" "preloaded_warehouse_mtrs_sales_order_line_items" 
ON "preloaded_warehouse_mtrs_sales_order_line_items"."order_number" = "sales_order_headers_sales_order_line_items_join"."order_number" 
AND ("warehouse_mtrs"."line_number"="sales_order_line_items"."line_number") 
AND ("preloaded_warehouse_mtrs_sales_order_line_items"."heat_number" 
IS NOT NULL)
...
```

```SQL
...
LEFT OUTER JOIN 
"warehouse_mtrs" "preloaded_warehouse_mtrs_sales_order_line_items" 
ON "preloaded_warehouse_mtrs_sales_order_line_items"."order_number" = "sales_order_headers_sales_order_line_items_join"."order_number" 
AND "preloaded_warehouse_mtrs_sales_order_line_items"."line_number" = "sales_order_line_items"."line_number" 
AND ("preloaded_warehouse_mtrs_sales_order_line_items"."heat_number" 
IS NOT NULL) 
...
```

The difference being `"warehouse_mtrs"."line_number"="sales_order_line_items"."line_number"` vs `"preloaded_warehouse_mtrs_sales_order_line_items"."line_number" = "sales_order_line_items"."line_number" `

Of course I can change the query to this:

`where('"preloaded_warehouse_mtrs_sales_order_line_items"."line_number"="sales_order_line_items"."line_number"')`

But what we have is much cleaner: `where(line_number: SalesOrderLineItem.arel_table[:line_number])`


However, I'm confused on how Arel is considered a private implementation detail. From a post you authored in 2014: (https://robots.thoughtbot.com/using-arel-to-compose-sql-queries#arel)

> Arel is a library that was introduced in Rails 3 for use in constructing SQL queries. Every time you pass a hash to where, it goes through Arel eventually. **Rails exposes this with a public API that we can hook into when we need to build a more complex query.**

Is it considered bad practice to use Arel directly now?

**Comment by rafaelfranca** [comment]
It always was. When that post was written Sean had no idea that the Rails Core considered Arel private API since its introduction for the framework. In fact, we never made that clean besides for some posts in our internal mailing list.

I was going to close the issue because of that exactly reason but I had the same problem in my application (which I choose to not use arel anymore) and maybe @sgrif would agree to change it back to a whitelist, as it was not the case I'm closing this issue. Thanks.

**Comment by jstin** [comment]
Perhaps then `ActiveRecord::Core.arel_table` should be a private method? 

https://github.com/rails/rails/blob/master/activerecord/lib/active_record/core.rb#L240
https://github.com/rails/rails/blob/master/activerecord/lib/active_record/core.rb#L267

**Comment by rafaelfranca** [comment]
It is. A private API method (see the `:nodoc:`), but it needs to have public visibility for internal use.

**Comment by jstin** [comment]
ok I see that now, thanks. Looks like i missed that :nodoc addition in the 4.1 release.

**Comment by sgrif** [comment]
For the record, I think this is a legitimate use case, but I'd rather figure out a good public API to handle this, rather than supporting reaching into internals.

**Comment by stiff** [comment]
Guys, it's extremely frustrating that every upgrade since 3.2 (4, 4.1, 4.2, 4.2.2->4.2.3+) limits the expressive possibilities of ActiveRecord query language down to just find_by_id and writing plain sql for everything else. Referencing column in other table shouldn't require writing custom sql. There are some apps beyond CRUD written in Rails. Whats wrong with making Arel public? It's a great lib that does  lots of useful things.
