### ISSUE TITLE
Add a way to change a column's method name

### ISSUE THREAD

**Issue by jomo** [rails/rails#21080]
Currently it seems to be impossible to have a database column named `attribute` because it is a method defined by ActiveRecord and throws `ActiveRecord::DangerousAttributeError`.

It would be nice to have a way to change a column's method name, where the method's name can be different from the column's name. For example:

```ruby
class Radcheck < ActiveRecord::Base
  self.set_column_method "attribute", "attr"
end
```

```ruby
Radcheck.create(attr: "something")
# INSERT INTO `radcheck` (`attribute`, …) VALUES ('something', …)

Radcheck.where(attr: "something")
# SELECT `radcheck`.* FROM `radcheck` WHERE `radcheck`.`attribute` = 'something'
```

**Comment by al2o3cr** [comment]
FWIW, there's the `safe_attributes` [gem](https://github.com/bjones/safe_attributes) that does this for most things. In your particular case, there are still difficulties (from the `README`):
```
It is virtually impossible to have a column named 'attribute' in your schema
when using ActiveRecord. After spending some time trying to make it work
I've come to the conclusion the only way to support this will be to change
the tactic I'm using entirely, and likely to get the developers of ActiveRecord
to agree to a patch.
```

**Comment by rafaelfranca** [comment]
Thank you so much for the issue but we don't take feature request on the issue tracker. We recommend you to try to implement the feature and send us a pull request or if you are in doubt if the feature will be accepts ask in Rails Core mailing list for feedback.
