### ISSUE TITLE
The RDoc for scopes in association declarations wrongly includes examples with non-owner parameters

### ISSUE THREAD

**Issue by mrj** [rails/rails#21083]
The second parameter of an association declaration can be a callable scope, which either takes no parameter or takes the [assocation's owner object](https://github.com/rails/rails/blob/master/activerecord/lib/active_record/associations.rb#L516) as a parameter.

However for each association type, the documentation gives an example of a scope with a non-owner parameter: [belongs_to](https://github.com/rails/rails/blob/master/activerecord/lib/active_record/associations.rb#L1537), [has_and_belongs_to_many](https://github.com/rails/rails/blob/master/activerecord/lib/active_record/associations.rb#L1726), [has_many](https://github.com/rails/rails/blob/master/activerecord/lib/active_record/associations.rb#L1248), and [has_one](https://github.com/rails/rails/blob/master/activerecord/lib/active_record/associations.rb#L1408).

These examples should be deleted, and references added back to the "Accessing the owner object" section.

Once confirmed, I can work up a patch.

**Comment by al2o3cr** [comment]
@mrj - The `has_one` example appears to have Ruby code-ish text inside a SQL literal. Wat.

**Comment by mrj** [comment]
Ha, didn't notice that before.

**Comment by mrj** [comment]
These five doc errors are still present in master.

**Comment by rafaelfranca** [comment]
Please send a PR fixing those errors.

**Comment by davidwessman** [comment]
Should you delete all the examples or write new ones with the `owner object` as parameter instead?

**Comment by mrj** [comment]
The examples should cover the range of possibilities, each explained in the text.

I've been delaying making the PR until I confirm whether the blocks are executed in the context of the owner objects, meaning that owner-object parameters are unnecessary.
