### ISSUE TITLE
habtm associations: `other_ids` method is not memoized unless `other_ids=` is called

### ISSUE THREAD

**Issue by vaharoni** [rails/rails#21082]
```ruby
x = Student.first
x.courses
# => Performs query
x.courses
# => Memoized: does not perform query (good!)

x.course_ids
# => Performs query
x.course_ids
# => Performs query again (bad!)

x.course_ids = x.course_ids
x.course_ids
# => Memoized: does not perform query from now on (good, but weird)
```

This is particularly an issue inside a view:
```ruby
form_for @student do |f| 
  f.collection_check_boxes :course_ids, Course.all, :id, :name
end 
```
Unless the `other_ids=` workaround is used, the code will result in one query per course, because @student.course_ids never gets memoized, and it is called one time per course in `#collection_check_boxes`.

**Comment by eileencodes** [comment]
Thanks for the report @vaharoni - does this happen on HM:T associations or just HABTM associations?

Can you create a runnable script that reproduces this bug using this template https://github.com/rails/rails/blob/master/guides/bug_report_templates/active_record_master.rb?

**Comment by meinac** [comment]
This happens for all type of collection associations.
