### ISSUE TITLE
it is impossible to use custom reporter for minitest

### ISSUE THREAD

**Issue by os97673** [rails/rails#21102]
minitest_plugin.rb explicitly modifies Minitest.extensions (https://github.com/rails/rails/blob/master/railties/lib/rails/test_unit/minitest_plugin.rb#L51) and so Minitest doesn't try to load any other extension and (as result) it is impossible to use custom reporter with rails :(
Unfortunately I have no idea why the line was added and so I have no chance to create a PR to fix the problem.

**Comment by zenspider** [comment]
You don't need to know the "why"s in order to send in PRs.

**Comment by os97673** [comment]
Ok, I've created a one-liner for the problem.
