### ISSUE TITLE
ActiveRecord looks in wrong DB for HABTM join table

### ISSUE THREAD

**Issue by manlon** [rails/rails#21113]
I am upgrading a rails app to v 4.2.3 (from 3.2.x). The app has two independent sets of models that are stored in different databases -- ActiveRecord::Base.connection is configured in the normal way, and the secondary set of models descend from another "base" class, along the lines of:

```ruby
class Secondary < ActiveRecord::Base
  establish_connection :secondary
  self.abstract_class = true
end
class SecondaryModel < Secondary
  has_and_belongs_to_many :secondary_associateds
end
```
Certain operations involving the HABTM association fail with `ActiveRecord::StatementInvalid: Could not find table`, presumably because AR attempts to use the "default" AR connection to find the join table, even though both models in the association are configured to use a different connection:

```ruby
m = SecondaryModel.create!
puts m.secondary_associateds.count # works fine
m.secondary_associateds << something # raises ActiveRecord::StatementInvalid: Could not find table 'secondary_associateds_models'
```

A full repro is here: https://gist.github.com/manlon/d17fdde1f97c4b8d03c6 .

This issue reproduces in Rails 4 and on master.

**Comment by pixeltrix** [comment]
This will be because `has_and_belongs_to_many` has been re-implemented using `has_many :through` and Active Record now creates a nested class for that association which will use the default connection.

As a temporary workaround until this is fixed you should be able to reopen the generated class after the `has_and_belongs_to_many` call and add the custom connection code there. I'm not sure whether this is how we want to recommend people handle this situation though as a final solution.

@tenderlove @rafaelfranca @sgrif wdyt?

**Comment by manlon** [comment]
I have worked around this so far by creating dummy classes for the join tables and using explicitly named `has_many :through` assocs. It's a bit onerous but mostly works w/o schema changes if you don't touch the intermediate associations.

What is a sensible way to get a handle on the generated class as you suggest? From what I can tell the generated name is a bit funny.

**Comment by pixeltrix** [comment]
@manlon the name is a bit funny but consistent - [this][1] is the code that generates the name of the class and then it's nested inside the model, e.g:

``` ruby
class Category < ActiveRecord::Base
  has_and_belongs_to_many :products

  class HABTM_Products < ActiveRecord::Base
    establish_connection :secondary
  end
end
```

This should work - you won't be able to inherit from your abstract class as the superclass is already defined. Actually, that gives me an idea on how to fix it - we could detect whether the LHS model descends from an abstract AR::Base subclass and use that as the superclass for the generated model. We could also add a superclass option maybe to `has_and_belongs_to_many`.

[1]: https://github.com/rails/rails/blob/v4.2.3/activerecord/lib/active_record/associations/builder/has_and_belongs_to_many.rb#L77

**Comment by sgrif** [comment]
I think that HABTM is a helpful time saver, but we don't need to add lots of options to cover edge cases. Most likely this is a case that can "just work", but if that isn't the case, I'd say that just having to drop to `has_many :through` is fine here.

**Comment by stephankaag** [comment]
Isn't the fix as easy as this?

https://github.com/stephankaag/rails/commit/296faa94d4a777676555b6732beb538bea41a8ef

**Comment by sgrif** [comment]
No clue. Run the tests and open a PR.

**Comment by stephankaag** [comment]
Is that something you can do @manlon?

**Comment by pixeltrix** [comment]
@stephankaag not sure that will work in all cases - what about STI for example where the superclass is a model in itself. Restricting it to this seems safer:

``` ruby
base_class = lhs_model.superclass.abstract_class? ? lhs_model.superclass : ActiveRecord::Base
```

@sgrif this is a regression though so we should fix it, but I'm fine with no extra options being added. Forcing someone to drop down to HMT would require them to perform migrations to add a id column to their join tables - something that may be a lengthy operation on large tables.

**Comment by manlon** [comment]
@pixeltrix I don't think the problem is restricted to descendants of abstract classes. If the model classes each establish_connection on their own you hit the same issue.

What about explicitly connecting after constructing the join model?:
```ruby
join_model = Class.new(ActiveRecord::Base){
  # stuff
}
join_model.establish_connection lhs_model.connection_config
```

**Comment by matthewd** [comment]
@manlon yeah, that sounds best. Are you able to make a PR with that + a test?

**Comment by manlon** [comment]
Using `establish_connection` turns out not to be easy since it makes another connection concurrently accessing the DB, which sqlite doesn't like. I tried a few options but ended up overriding `retrieve_connection` in the generated class. Is this safe?
