### ISSUE TITLE
improve error message for relations missing in includes

### ISSUE THREAD

**Issue by eiked** [rails/rails#21111]
I'd like to suggest an improvement for the error messages.

I deleted a relation from my model but it was still referenced in an includes clause.

So I got an error message like:
'Association named 'label' was not found on Disk; perhaps you misspelled it?'
and it was not really obvious where this came from.

I believe the error message can be improved.
This obviously comes from a part of rails that wants to resolve the includes clause.

So maybe something like:
'Association named 'label' **_referenced in includes**_ was not found on Disk; perhaps you misspelled it?'
could be done

I was thinking about:
We might want to add more information to the call chain,
to improve error reporting (in debug mode)

We actually might want to add a debug:{} to every binding.
2p

~eike

**Comment by arthurnn** [comment]
@eiked yep, I guess would be great to have a better message for sure.
Fell free to send a PR for it.

**Comment by kamipo** [comment]
Fixed by #22518.
