### ISSUE TITLE
has_many allow to define singular and plural both cases for a same model witout giving any other information

### ISSUE THREAD

**Issue by kumarsunil** [rails/rails#21128]
class user
 has_many :comments
 has_many :comment
end

class comment
  belongs_to :user
end

foreign key in comment table is (user_id)

**Comment by sevenseacat** [comment]
Is this a request for a new feature, to allow the `has_many :comment` to work? I don't think it will be accepted.

**Comment by pixeltrix** [comment]
@kumarsunil this issue tracker is for dealing with bugs and pull requests only - feature requests should be discussed on the [mailing list][1] first before someone implementing them and submitting a PR.

[1]: https://groups.google.com/forum/#!forum/rubyonrails-core
