### ISSUE TITLE
has_and_belongs_to_many :through

### ISSUE THREAD

**Issue by adamwohlberg** [rails/rails#21127]
Isn't "has_and_belongs_to_many :through" a valid association type?

The Types of Associations section lists 6 association types:
belongs_to
has_one
has_many
has_many :through
has_one :through
has_and_belongs_to_many

Shouldn't there be a seventh, "has_and_belongs_to_many :through" ?

**Comment by aditya-kapoor** [comment]
what kind of relationship you want to model using `has_and_belongs_to_many` through?
`has_and_belongs_to_many` and `has_many :through` itself are sufficient to model any kind of Many to many relationship.

**Comment by FlowerWrong** [comment]
Nope, maybe you need `has_many :through`.
