### ISSUE TITLE
ActiveRecord truncates :datetime columns

### ISSUE THREAD

**Issue by NobodysNightmare** [rails/rails#21139]
## Reproduction

* Store a value in a table with the following schema:

````ruby
  create_table "test", :force => true do |t|
    t.datetime "created_at", :limit => 4
  end
````

* Use MySQL as backend (probably others too, but don't use PostgreSQL; see below)
    * MySQL version has to be [at least 5.6.4 for fractional second support](http://dev.mysql.com/doc/refman/5.6/en/fractional-seconds.html)

## Expected

* The created column has a specified subsecond precision (4 decimal places)
* When storing a creation date, it is stored with the desired precision

## Actual

* The created column has the desired precision (*as expected*)
* Storing a creation date, the subsecond precision is lost (***not*** *expected*)

## Solution

According to a SO post ([see post here](http://stackoverflow.com/a/19169101/968531)), the problem is caused in [conversions.rb:6](https://github.com/rails/rails/blob/3d32a50ca1933ee96abbe5db7ee99617fd0c328c/activesupport/lib/active_support/core_ext/time/conversions.rb#L6), where the format for a datetime formatted for the database is specified without subsecond precision.

When overriding the corresponding constant like

````ruby
Time::DATE_FORMATS[:db] = '%Y-%m-%d %H:%M:%S.%6N'
````

the desired datetime is stored in the database (without precision loss).

Would this be an apropriate solution to the problem? I can't tell if this would cause problems with other database vendors or versions.

## PostgreSQL

For PostgreSQL the described problem is not apparent. Even without specifying a desired precision, the `timestamp`s used by PostgreSQL have subsecond precision and are also stored with this precision. I *suspect* this is because the Postgres adapter will use a different insert-format than the MySQL adapter...

**Comment by matthewd** [comment]
You didn't mention which version you're seeing this behaviour on. I've carefully avoided getting too deep into the whole MySQL + timestamps thing, but I *think* this sounds like what #20732 claims to fix.

**Comment by NobodysNightmare** [comment]
Hey, thanks for the quick response. Admittedly the issue occurs for a rather old Rails 3.2.x and I did not verify it on Rails 4.x. I just assumed it would still be present because I could see the afforementioned `:db` format string on the `master` branch.

I will verify if the problem is present on a recent Rails version and close this ticket in that case.

**Comment by NobodysNightmare** [comment]
Works on Rails 4.2 :)
