### ISSUE TITLE
complex css cause sanitize to take forever

### ISSUE THREAD

**Issue by mfazekas** [rails/rails#21136]
```ruby
  def test_returns_success
    complex_inline_style = "some-attribute: 10px 10px 10px 10px !important; "*40+"background-image: -webkit-linear-gradient(top, rgb(254, 254, 254) 0%, rgb(236, 236, 236) 100%) !important;"
    html = "<div style=\"#{complex_inline_style}\"></div>"

    sanitize html
  end
```
[full test](https://gist.github.com/mfazekas/197b133755e8d21a1317)

see also https://github.com/rails/rails-html-sanitizer/issues/41

```ruby
gem 'rails-deprecated_sanitizer'
```
works around the issue for us

**Comment by claudiob** [comment]
@mfazekas I was able to reproduce the error. 

It’s caused [by this regex](https://github.com/flavorjones/loofah/blob/master/lib/loofah/html5/scrub.rb#L70) in the loofah codebase:

```ruby
return '' unless style =~ /\A([-:,;#%.\sa-zA-Z0-9!]|\w-\w|\'[\s\w]+\'|\"[\s\w]+\"|\([\d,\s]+\))*\z/
```

It looks like Ruby gets stuck when trying to parse your string against that regular expression.

In fact, to reproduce the error, you don’t even need to install Rails or Loofah, simply open a Ruby session and type the following:

```ruby
complex_inline_style = "some-attribute: 10px 10px 10px 10px !important; "*40+"background-image: -webkit-linear-gradient(top, rgb(254, 254, 254) 0%, rgb(236, 236, 236) 100%) !important;"
complex_inline_style =~ /\A([-:,;#%.\sa-zA-Z0-9!]|\w-\w|\'[\s\w]+\'|\"[\s\w]+\"|\([\d,\s]+\))*\z/
```

Maybe @flavorjones or @kaspth who worked on that regular expression might have a better idea about the reason why.

**Comment by claudiob** [comment]
More details: looks like the regular expression was last changed in https://github.com/flavorjones/loofah/commit/37e5011033c5aafb0f2aee12a0b66f0058f34235 by adding a `-` sign. 

If you remove that `-` sign, then Ruby does not get stuck in trying to parse the string:

```ruby
complex_inline_style = "some-attribute: 10px 10px 10px 10px !important; "*40+"background-image: -webkit-linear-gradient(top, rgb(254, 254, 254) 0%, rgb(236, 236, 236) 100%) !important;"
complex_inline_style =~ /\A([:,;#%.\sa-zA-Z0-9!]|\w-\w|\'[\s\w]+\'|\"[\s\w]+\"|\([\d,\s]+\))*\z/
# => nil
```

**Comment by claudiob** [comment]
And this is what [the message for that change](https://github.com/flavorjones/loofah/commit/ca618fc5f8e6ba146e2d4731c0361368c4b464b2) by @joncalhoun  says:

>  Gauntlet section is out of date with html5lib and doesn't allow for things like "letter-spacing:-0.03em;". 
> See http://code.google.com/searchframe#NXg3toovv0g/ruby/lib/html5/sanitizer.rb&q=gauntlet%20package:html5lib%5C.googlecode%5C.com&l=176

Unfortunately, the previous URL returns a 404 Not Found.

**Comment by kaspth** [comment]
Thanks for the report, @mfazekas, and nice digging, @claudiob :+1:

Yes, this seems to be a problem in Loofah: flavorjones/loofah#90.
