### ISSUE TITLE
Pluralize - negative values incorrectly always plural

### ISSUE THREAD

**Issue by carlosbutler** [rails/rails#21130]
I believe that with negative values, pluralize should differentiate between '-1' and '-2 or less'.

```
[1] pry(main)> include ActionView::Helpers::TextHelper
=> Object
[2] pry(main)> pluralize(1, 'day')
=> "1 day"
[3] pry(main)> pluralize(2, 'day')
=> "2 days"
[4] pry(main)> pluralize(-1, 'day') # should show "-1 day"
=> "-1 days"
[5] pry(main)> pluralize(-2, 'day')
=> "-2 days"
```

Quick fix is to use absolute
```
[6] pry(main)> "-#{pluralize(-1.abs, 'day')}"
=> "-1 day"
```
... but this is cumbersome.

**Comment by robin850** [comment]
Hi @carlosbutler,

Actually the Active Support's inflector is kind of frozen ; we avoid as much as possible changes to it to avoid breaking applications during upgrade. Also, it looks like there's [no real consensus](http://english.stackexchange.com/a/10471) on whether the plural or singular should be used with "-1"/"- 1". Ultimately, this also depends on the language so you should better rely on the I18n library's pluralization feature. Thanks for reporting!
