### ISSUE TITLE
Calling require in initializer before app eager load causes constant warning 

### ISSUE THREAD

**Issue by jbodah** [rails/rails#21146]
Haven't been able to dig too deep. Changing [Rails::Engine#eager_load!](https://github.com/rails/rails/blob/v4.2.3.rc1/railties/lib/rails/engine.rb#L472) to use [require](https://github.com/rails/rails/blob/v4.2.3/activesupport/lib/active_support/dependencies.rb#L272) fixes the issue. Also hacking the initializer to use [require_dependency](https://github.com/rails/rails/blob/v4.2.3/activesupport/lib/active_support/dependencies.rb#L227) instead will work, but it's not an ideal solution

Here are the steps to reproduce:

```rb
# config/environments/production.rb
config.eager_load = true
config.eager_load_paths = ['lib']

# config/initializers/require_constant.rb
require 'constant_file'

# lib/constant_file.rb
HELLO_WORLD = 'hello world'

# command line
$ bundle exec rails s
=> Booting WEBrick
=> Rails 4.2.3 application starting in development on http://localhost:5555
=> Run `rails server -h` for more startup options
=> Ctrl-C to shutdown server
/Users/Bodah/repos/dummy/lib/constant_file.rb:3: warning: already initialized constant HELLO_WORLD
/Users/Bodah/repos/dummy/lib/constant_file.rb:3: warning: previous definition of HELLO_WORLD was here
[2015-08-06 12:22:50] INFO  WEBrick 1.3.1
[2015-08-06 12:22:50] INFO  ruby 2.1.3 (2014-09-19) [x86_64-darwin14.0]
[2015-08-06 12:22:50] INFO  WEBrick::HTTPServer#start: pid=91305 port=3000
```

**Comment by rafaelfranca** [comment]
cc @matthewd @fxn

**Comment by agis-** [comment]
@jbodah I assume you set the eager load settings in `development.rb` and *not* `production.rb` (as your first comment states).

If that's the case, I'm guessing you also have `config.cache_classes` set to `false` since you're in development. Right?

From [Configuring Rails Applications](http://guides.rubyonrails.org/configuring.html):

> config.eager_load_paths accepts an array of paths from which Rails will eager load on boot if cache classes is enabled. Defaults to every folder in the app directory of the application.

So you should also turn on `config.cache_classes` and it will work fine. However, not sure what the expected behavior is when `cache_classes` is turned off.

**Comment by jbodah** [comment]
This explains things. Also explains why I was getting constant redefinition errors (eager loading `lib` and some lib files call `require` on other files, so those files would get `load`'ed twice)
