### ISSUE TITLE
Invalid SQL is generated when calling .count on GROUP BY with HAVING clause

### ISSUE THREAD

**Issue by thinkalike-dev** [rails/rails#21147]
Hello,

When we call .count on this ActiveRecord scope, it throws this invalid SQL exception: `PG::SyntaxError: ERROR:  syntax error at or near "AS"`. Here is the code that demonstrates this issue:

```ruby
ModelA.joins(:modelb).group("modela.id HAVING MAX((CASE WHEN (modelb.user_id = 123) THEN 1 ELSE 0 END)) = 0").count
```

This is the SQL that is generated by the ruby code above:

```sql
SELECT COUNT(*) AS count_all, 
  thoughts.id HAVING MAX((CASE WHEN (ratings.user_id = 1) THEN 1 ELSE 0 END)) = 0 AS thoughts_id_having_max_case_when_ratings_user_id_1_then_1_else_ 
FROM "thoughts" 
INNER JOIN "ratings" ON "ratings"."thought_id" = "thoughts"."id"
GROUP BY thoughts.id HAVING MAX((CASE WHEN (ratings.user_id = 123) THEN 1 ELSE 0 END)) = 0
```

Whereas the correct SQL should be

```sql
SELECT COUNT(*) AS count_all
FROM "thoughts" 
INNER JOIN "ratings" ON "ratings"."thought_id" = "thoughts"."id" 
GROUP BY thoughts.id HAVING MAX((CASE WHEN (ratings.user_id = 123) THEN 1 ELSE 0 END)) = 0
```

Any thoughts on why the invalid SQL is produced ?

Thanks,
Alex

**Comment by matthewd** [comment]
Is there documentation somewhere that mislead you to believe you could/should include a full HAVING clause in the argument to `group`? Because.. [you shouldn't](http://api.rubyonrails.org/classes/ActiveRecord/QueryMethods.html#method-i-having).
