### ISSUE TITLE
uniq does not include joins columns in the select'ed columns (needed for sorting)

### ISSUE THREAD

**Issue by eiked** [rails/rails#21148]
I have a simple query on a model.
I now want to joins() this with another table.
I want to order on the joined columns.
This works perfect so far.

But if I add uniq, it fails: postgres says:
SELECT DISTINCT, ORDER BY expressions must appear in select list

As of my current understanding of the problem,
not using uniq just selects *
but applying uniq does include select clauses for every column in the original table,
while it does not include select clauses for the joins (aka the joined columns)

I believe this might be a bug.

I believe that using uniq on a relation should include in the select clause
the colums from the joined tables as well.

Currently applying uniq to a table results in only the columns from the base model being selected.
This is a problem, because we can not then sort then on joined tables columns.

I was looking for a way to rectify this,
maybe something like #unpluck could be handy (bad name though)

Like pluck reduces the select clause,
unpluck would extend the select clause, to add user defined columns to the select clause.

**Comment by al2o3cr** [comment]
Feature requests are not typically accepted as issues; if you'd like to propose something try the rails-core mailing list.

Regarding your particular case, can you be more specific about the models you're using and the SQL you're expecting to generate? It's impractical to debug without more information.
