### ISSUE TITLE
checking migrations before rails server runs

### ISSUE THREAD

**Issue by mtczerwinski** [rails/rails#21140]
Hi,

What do you think about a simple feature? It will be checking for migration before rails server runs. If there are migrations which wait for migrating, it can migrate it automatically. I think, it would be a big delay.

**Comment by pascalbetz** [comment]
I would not want my migrations to be run automatically. Manipulating the DB is something which i want to be in control of.

**Comment by artofhuman** [comment]
@pascalbetz :+1:

**Comment by rafaelfranca** [comment]
Thank you so much for the issue but we don't take feature request on the issue tracker. We recommend you to try to implement the feature and send us a pull request or if you are in doubt if the feature will be accepts ask in Rails Core mailing list for feedback.

**Comment by rafaelfranca** [comment]
Yeah. I agree with @pascalbetz
