### ISSUE TITLE
has_many wrong pluralisation with "f" and "v"

### ISSUE THREAD

**Issue by damoiser** [rails/rails#21157]
I have discovered a bug when using the ```has_many``` with a name that ends with ```ves```, let me write an example:

Class definition
```
class LocalDrive < ActiveRecord::Base
end

class Server < ActiveRecord::Base
  has_many :local_drives
end
```

In this case, when trying to access to the ```LocalDrive``` model, I receive the following error:

```
NameError: uninitialized constant Server::LocalDrife
    /Users/xxx/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/activerecord-4.2.3/lib/active_record/inheritance.rb:158:in `compute_type'
    /Users/xxx/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/activerecord-4.2.3/lib/active_record/reflection.rb:271:in `compute_class'
    /Users/xxx/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/activerecord-4.2.3/lib/active_record/reflection.rb:267:in `klass'
    /Users/xxx/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/activerecord-4.2.3/lib/active_record/associations/association.rb:118:in `klass'
    /Users/xxx/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/activerecord-4.2.3/lib/active_record/associations/collection_association.rb:41:in `reader'
    /Users/xxx/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/activerecord-4.2.3/lib/active_record/associations/builder/association.rb:115:in `local_drives'
```

Please note the change from ```LocalDrive``` to ```LocalDrife```.

If I explicitly define the ```class_name``` attribute

```
class Server < ActiveRecord::Base
  has_many :local_drives, class_name: "LocalDrive"
end
```
The error disappears, BUT the accessories methods are still wrongs: 

```
% rails c
pry(main)> Server.first.local_dri
Server.first.local_drife_ids   Server.first.local_drife_ids=  Server.first.local_drive       Server.first.local_drive=      Server.first.local_drives      Server.first.local_drives=
```

Note the ```Server.first.local_drife_ids```

Code to reproduce: https://gist.github.com/damoiser/a0ef124a5ba1aee78135

**Comment by matthewd** [comment]
You want to define a custom inflection in [`config/initializers/inflections.rb`](http://api.rubyonrails.org/classes/ActiveSupport/Inflector/Inflections.html).

**Comment by damoiser** [comment]
thanks @matthewd for your fast reply! 

I think that this is a rollback. We are updating our rails app from 3.2 to 4.2 and before we didn't have this bug. 

Anyway, your solution with the inflections works well.
