### ISSUE TITLE
link_to helper method with remote option causes uncaught error in jquery side

### ISSUE THREAD

**Issue by kevin-jj** [rails/rails#21171]
Rails 4.3.2
Jquery 1.11.2

```ruby

<%= link_to new_address_path,remote: true, class: "btn btn-fg",id: "add_new_shipping_address","data-toggle"=>"modal" do%>
   <h5 class="pure"><%= t '.add_new_shipping_address'%></h5>
<% end %>
```

google developer shows  "Uncaught Error: Syntax error, unrecognized expression: /addresses/new"

**Comment by rafaelfranca** [comment]
You need to give us more information on how to reproduce this issue, otherwise there is nothing we can do. Please read CONTRIBUTING.md file for more information about creating bug reports. Thanks!
