### ISSUE TITLE
Getting middleware class DEPRECATION WARNINGs using edge rails

### ISSUE THREAD

**Issue by jasnow** [rails/rails#21172]
Getting the new **middleware class "DEPRECATION WARNING"** message (see full message at bottom of this write-up) for four patterns.

 *  1) (4 times) "::ActionDispatch::Callbacks" => ActionDispatch::Callbacks
 *  2) (2 times) "ActiveRecord::QueryCache" => ActiveRecord::QueryCache
 *  3) (2 times) "ActiveRecord::ConnectionAdapters::ConnectionManagement" =>
     ActiveRecord::ConnectionAdapters::ConnectionManagement
 *  ~~4) (1 time)  "Rack::Runtime" => Rack::Runtime~~ (https://github.com/rails/rails/commit/12f08acbacf823041dae27afd1a1a1458bb1e3fa fixed this.)

when I use the latest edge version of rails/rails e7007e384c2ccfda3228c1ccdb1331e89fb17f4d on a sample rails project, such as https://github.com/jasnow/rt_demo_app5 .

I checked the tsort.rb code (no help) and then the rails code and found these references to the above before-patterns in rails/rails repo:
```
actionview/test/abstract_unit.rb:152:
  middleware.use "ActionDispatch::Callbacks"

activerecord/lib/active_record/railtie.rb:20:
  "ActiveRecord::QueryCache"

activerecord/lib/active_record/railtie.rb:23:
  "ActiveRecord::ConnectionAdapters::ConnectionManagement"

railties/lib/rails/application/bootstrap.rb:66:
  config.middleware.insert_before("Rack::Runtime", Rails.cache.middleware)
```
......................................................................
FULL EXAMPLE MESSAGE:
```
DEPRECATION WARNING: Passing strings or symbols to the middleware builder
is deprecated, please change them to actual class references.  For example:

  "::ActionDispatch::Callbacks" => ActionDispatch::Callbacks

  . (called from block in tsort_each at .../.rvm/rubies/
  ruby-2.2.2/lib/ruby/2.2.0/tsort.rb:226)
```

**Comment by rafaelfranca** [comment]
The fixes are pretty simple and you already spot the right files. Do you want to send the patch? I can do myself but since you already did almost all the work I think it is a great first contribution :wink:

**Comment by gringocl** [comment]
I was playing around with the edge release and got bored of seeing these warnings!!!

**Comment by jasnow** [comment]
Never got the comment by @rafaelfranca . Thanks @gringocl . Verified fixed.
