### ISSUE TITLE
Improve includes() prefetches - add debug hints, explore automation

### ISSUE THREAD

**Issue by eiked** [rails/rails#21178]
When working with queries across multiple tables,
or when rendering datasets resulting from multiple tables,
it is very important to get the includes() right, to avoid the n+1 fetch problem.

Finding the missing includes() clauses however is not always easy.

I believe it could be possible to add some code to rails/ActiveRecord
to detect queries that would benefit from includes()

I believe this could help in 2 situations:
- detecting the query where a includes() clause is missing
- hinting the developer, where a includes() clause may be beneficial

Such a tool should be available in developer mode, and it should be possible to disable it ...

I've not yet gone deep into the details how this could be achieved.
But let me sketch a first idea:

A common case is accessing m:n relations:
A->B->C

Usually B is fetched on first access, and trouble starts when accessing C, one by one
(we want to includes(B: :C) here)

Maybe we could mark B as 'not prefetched, yet'
and on the second access to C (aka B->C[1])
log a debug hint, that prefetching A.includes(B: :C) might be a good idea.

I believe could add a reference to the code line where A (or A->B or even A->B->C.first) was triggered.

Such a mechanism should be request scoped,
so that it works for the lifetime of the requests object graph.

If this works well, we might even go ahead and add some auto_includes mechanism.
Aka on the third access to B->C prefetch that automatically (within bounds)
This could result in a prefetch hint on relations (please excuse if there already is such thing)
aka: prefetch:true or prefetch:100 or prefetch:{min:3, max:100} ... you get the idea

**Comment by senny** [comment]
Hey @eiked thank you for your suggestion. Would you mind posting it again to the [rubyonrails-core](https://groups.google.com/forum/?fromgroups#!forum/rubyonrails-core) mailing list? We use the GitHub tracker for bug reports and code discussions exclusively. You can find more in our [contribution guidelines](https://github.com/rails/rails/blob/master/CONTRIBUTING.md).

Thank you for your understanding.
