### ISSUE TITLE
config.assets.debug = true suddenly stops working in development

### ISSUE THREAD

**Issue by JohnMerlino1** [rails/rails#21185]
I have this bizarre behavior that I cannot even debug. Usually development is supposed to run slower than production. Not only is it now running extremely fast (the page loads instantly whereas it usually takes a little time), but it does not recognize my javascript code (it does recognize javascript outside of the assets/javascripts directory), unless I modify the javascript code and refresh page or simply just refresh the page (and then it will only work for that one request).

The reason why I am stumped is because I have the following in /config/environments/development.rb:
config.assets.debug = true

Why is my site suddenly running so fast in development and none of my javascript in assets is being recognized?

My development.rb is set to the Rails defaults:

Rails.application.configure do

  config.cache_classes = false

  config.eager_load = false

  config.consider_all_requests_local       = true
  config.action_controller.perform_caching = false

  config.action_mailer.raise_delivery_errors = false

  config.active_support.deprecation = :log

  config.active_record.migration_error = :page_load

  config.assets.debug = true

  config.assets.digest = true

  config.assets.raise_runtime_errors = true

  config.action_mailer.smtp_settings = {
      address: 'smtp.sendgrid.net',
      port: 587,
      domain: APP_CONFIG['sendgrid']['domain'],
      authentication: "plain",
      enable_starttls_auto: true,
      user_name: APP_CONFIG['sendgrid']['username'],
      password: APP_CONFIG['sendgrid']['password']
  }
  
  # ActionMailer Config
  config.action_mailer.default_url_options = { host: 'localhost', port: 3000 }
  config.action_mailer.delivery_method = :smtp
  config.action_mailer.raise_delivery_errors = true
  config.action_mailer.perform_deliveries = true # set this back to false
end

**Comment by rafaelfranca** [comment]
What is the content of the `public/assets` folder?

**Comment by JohnMerlino1** [comment]
There is nothing in public/assets folder, as I deleted it. Also I deleted everything in tmp. And the problem persisted. Here's the behavior: site responds very quickly (when it should not), and when I click on link on page that should trigger javascript, nothing happens. When I refresh page, then magically the javascript works. This just started happening today. I removed turbolinks from application.js and still problem occurs.

**Comment by rafaelfranca** [comment]
Can you please provide a sample application that reproduces the error?

**Comment by JohnMerlino1** [comment]
Unfortunately, the problem is so arcane that I don't know how to reproduce it. On Friday, everything was fine. Today I ran rake recompile:assets and everything went to hell.

**Comment by rafaelfranca** [comment]
Thank you for the report but unfortunately we can't do anything if we don't know how to reproduce the problem. That said I'm closing this issue but let us know if you get a way to reproduce it. It may be related to assets be already precompiled in development for some reason.
