### ISSUE TITLE
ActionMailer's default subject doesn't use interpolation options

### ISSUE THREAD

**Issue by fnando** [rails/rails#21186]
ActionMailer tries to retrieve subject from i18n. So if I have a `Mailer` class, it will look at `en.mailer.<mail name>.subject`. The documentation states that you can pass in interpolation options by setting `:interpolations`. The problem is that these options aren't used at all.

Here's the line that calls `default_i18n_subject`: https://github.com/rails/rails/blob/6ac6daa43e1c5b7388f8fd69f8117eb7668887c7/actionmailer/lib/action_mailer/base.rb#L816

And here's the line that defines the method: https://github.com/rails/rails/blob/6ac6daa43e1c5b7388f8fd69f8117eb7668887c7/actionmailer/lib/action_mailer/base.rb#L879

**Comment by senny** [comment]
@fnando I don't think I understand the issue your pointing out. Could you please point to the relevant part of the documentation? Also please post some example code, like your `Mailer` that tries to use this feature. This should help to get the issue across.

**Comment by fnando** [comment]
`ActionMailer::Base#default_i18n_subject` [documentation](https://github.com/rails/rails/blob/2475168de89742d0072e300db5ae97a8ee8057cb/actionmailer/lib/action_mailer/base.rb#L875-L882) states the following:

> Translates the +subject+ using Rails I18n class under <tt>[mailer_scope, action_name]</tt> scope.
> If it does not find a translation for the +subject+ under the specified scope it will default to a humanized version of the <tt>action_name</tt>.
> If the subject has interpolations, you can pass them through the +interpolations+ parameter.

So, given the `Mailer#welcome` action below:

```ruby
class Mailer < ApplicationMailer
  def welcome(user)
    mail to: user.email, interpolations: {name: user.name}
  end
end
```

And this translation:

```yaml
en:
  mailer:
    welcome:
      subject: 'Welcome, %{name}'
```

The following subject must be generated: `Welcome, John Doe`.

**Comment by senny** [comment]
@fnando the documentation you pointed to is from the `default_i18n_subject` method. It does indeed accept `interpolations` and passes them along. However your example is using the `mail` method it does not document an `interpolations` option.

Are you looking for:?

```ruby
mail to: user.email, subject: default_i18n_subject(name: user.name)
```

**Comment by fnando** [comment]
Yeah, that would do, but it doesn't make sense having a different usage since `default_i18n_subject` is already being used by `mail`. I think having a convention is better here.

My suggestion is changing [this line](https://github.com/rails/rails/blob/6ac6daa43e1c5b7388f8fd69f8117eb7668887c7/actionmailer/lib/action_mailer/base.rb#L816) to something like `headers[:subject] ||= default_i18n_subject(headers[:interpolations] || {})`.

**Comment by senny** [comment]
I disagree. This only bloats the interface of `mail` to support one more corner case. In my opinion passing an explicit subject is the way to go.

/cc @rafaelfranca

**Comment by rafaelfranca** [comment]
Yeah, I agree with that, I'd not bloat `mail` with one more option that is only used to build the subject. That helper is there to make easier to use I18n subjects without having to bloat the `mail` API.
