### ISSUE TITLE
What is the reason behind having 3000 has default port for rails instance ?

### ISSUE THREAD

**Issue by marudhupandiyang** [rails/rails#21182]
I really want to know the reason behind assigning port 3000 for rails.
I also know i can assign it to any port i need and which is not used at the moment.
But if you can understand my question "What is the reason behind it".

Anybody ??

**Comment by matthewd** [comment]
Please use the mailing list or StackOverflow for questions/help, where a wider community will be able to help you. We reserve the issues tracker for issues only.
