### ISSUE TITLE
Rails Truck Factor

### ISSUE THREAD

**Issue by gavelino** [rails/rails#21196]
As part of my PhD research on code authorship, we calculated the Truck Factor (TF) of some popular GitHub repositories.

As you probably know, the [Truck (or Bus) Factor](https://en.wikipedia.org/wiki/Bus_factor) designates the minimal number of developers that have to be hit by a truck (or quit) before a project is incapacitated. In our work, we consider that a system is in trouble if more than 50% of its files become orphan (i.e., without a main author).

More details on our work in this preprint: https://peerj.com/preprints/1233

We calculated the TF for **Rails** and obtained a value of **9**.

The developers responsible for this TF are:

David Heinemeier Hansson - author of 16% of the files
Jose Valim - author of 11% of the files
Jeremy Kemper - author of 11% of the files
Piotr Sarnacki - author of 8% of the files
Aaron Patterson - author of 8% of the files
Sean Griffin - author of 6% of the files
Jon Leighton - author of 6% of the files
Łukasz Strzałkowski - author of 5% of the files
Joshua Peek - author of 5% of the files

To validate our results, we would like to ask **Rails** developers the following three brief questions:

(a) Do you agree that the listed developers are the main developers of **Rails**?

(b) Do you agree that **Rails** will be in trouble if the listed developers leave the project (e.g., if they win in the lottery, to be less morbid)?

(c) Does **Rails** have some characteristics that would attenuate the loss of the listed developers (e.g., detailed documentation)?

Thanks in advance for your collaboration,

Guilherme Avelino
PhD Student
Applied Software Engineering Group (ASERG)
UFMG, Brazil
http://aserg.labsoft.dcc.ufmg.br/

**Comment by rafaelfranca** [comment]
a) It is almost correct, see http://rubyonrails.org/core/.
b) No, Rails can survive even if all the Rails core win in the lottery, we have a bunch of active contributors
c) Yes, I'd say that the vibrant community is the reason for it.

**Comment by gavelino** [comment]
Thank you.
