### ISSUE TITLE
The authorization scheme for HTTP Basic Authentication should not be case sensitive.

### ISSUE THREAD

**Issue by tokenshift** [rails/rails#21199]
An application I support recently upgraded from Rails 4.0.2 to 4.1.11. This has broken several API clients that use HTTP Basic Auth to authenticate, but send authentication headers of the form:

```
Authorization: BASIC ...encoded username and password...
```

With `BASIC` rather than the more common `Basic`.

According to [RFC 2617](http://tools.ietf.org/html/rfc2617#section-1.2), the authorization scheme should not be case sensitive; thus `BASIC`, or `Basic`, or `basic` are all valid. The code in question appears to be https://github.com/rails/rails/blob/master/actionpack/lib/action_controller/metal/http_authentication.rb#L97.

**Comment by denniss** [comment]
Can you point to where in the RFC does it say that the the auth scheme should not be case sensitive? I might have skipped it....

**Comment by tokenshift** [comment]
Section 1.2:

```
HTTP provides a simple challenge-response authentication mechanism
that MAY be used by a server to challenge a client request and by a
client to provide authentication information. It uses an extensible,
case-insensitive token to identify the authentication scheme...
```

**Comment by denniss** [comment]
Thank you! I wrote a failing spec and a potential fix for this.

**Comment by tokenshift** [comment]
Awesome, thanks!
