### ISSUE TITLE
Redirect not working for app deployed to a subdirectory

### ISSUE THREAD

**Issue by lukehorvat** [rails/rails#21193]
I have the following routes defined:

``` ruby
Rails.application.routes.draw do
  root to: redirect("/ui")

  mount UI, at: "/ui"
end
```

I am deploying my Rails 4.2 app to a subdirectory, `/api`. Unfortunately I am finding that the app's root URL redirects to `http://example.com/ui`, _not_ to my Rack app mounted at `http://example.com/api/ui`.

If I manually navigate to `http://example.com/api/ui`, I can definitely access the Rack app. So it's only the root URL redirect that isn't working.

Eventually, I managed to get the redirect working by defining `$RAILS_RELATIVE_URL_ROOT` and changing my routes to this:

``` ruby
Rails.application.routes.draw do
  root to: redirect("#{Rails.application.config.relative_url_root}/ui")

  mount UI, at: "/ui"
end
```

But this isn't ideal. How come I don't need to specify `relative_url_root` for the Rack app, but I do for the root URL? :disappointed: Is this a bug?

It would be cool if we could use relative paths in redirects. Example: `redirect("./ui")` (which would be equivalent to `redirect("#{Rails.application.config.relative_url_root}/ui")`).

**Comment by pixeltrix** [comment]
Using leading slash for redirects indicates that it's an absolute path - try removing that and see if it works.

**Comment by lukehorvat** [comment]
Nah, that doesn't seem to work. Even if it did, it wouldn't explain why the mounted Rack app works with `/ui` specified.

**Comment by djhopper01** [comment]
@lukehorvat have you seen #4308? It's a little bit old, but there might be something that helps. It talks about SCRIPT_NAME which is also mentioned in the Rails docs.

According to [the docs on redirect](http://api.rubyonrails.org/classes/ActionDispatch/Routing/Redirection.html), it's supposed to work as you'd expect. Basically, it should know you've deployed the app to a subdirectory and take that into account for the redirect.

**Comment by lukehorvat** [comment]
@djhopper01 Thanks. [This doc](http://api.rubyonrails.org/classes/ActionDispatch/Routing/Redirection.html) states that `SCRIPT_NAME`  will be used if the leading slash is omitted. But I've tried it, and it doesn't seem to do so. Not sure why... :neutral_face: Anyway I'm not particularly interested in defining new environment variables like `SCRIPT_NAME`, because `mount` and `redirect` should share the same routing logic, no?

I'm not familiar with Rails' internals, but does anyone know how `relative_url_root` is utilized by [`mount`](https://github.com/rails/rails/blob/048235b5642c1d33055926946d918b8427e19f5c/actionpack/lib/action_dispatch/routing/mapper.rb#L567) in ActionDispatch::Routing::Mapper? Couldn't we do the same for [`redirect`](https://github.com/rails/rails/blob/69c7c06923249e7c95491db33933bbafa19707d3/actionpack/lib/action_dispatch/routing/redirection.rb#L177) in ActionDispatch::Routing::Redirection?

**Comment by merhard** [comment]
@lukehorvat Is this still an issue? If so, can you please create a test app that demonstrates this?

I tried to create one myself, but using `root to: redirect('ui')` as @pixeltrix recommended fixed the issue for me.

**Comment by lukehorvat** [comment]
@merhard Yep, still an issue. Here's a test app: https://github.com/lukehorvat/rails-issue-21193

It's just a completely blank Rails app with some small modifications to `routes.rb`. There's also a `Dockerfile` included if you want to host the app in a subdirectory via nginx.

**Comment by merhard** [comment]
@lukehorvat I see the nginx web server location is configured for a subdirectory. Shouldn't the app server (webrick, puma, unicorn, passenger, thin, ...) be configured to serve the application from a subdirectory as well?

Some examples:
- passenger - https://www.phusionpassenger.com/library/deploy/nginx/deploy/ruby/#deploying-an-app-to-a-sub-uri
- thin - `thin start --prefix=/app`
- webrick -
    ```ruby
    # config.ru
    require ::File.expand_path('../config/environment', __FILE__)

    map Rails.application.config.relative_url_root || '/' do
      run Rails.application
    end
    ```

===
Changes for your test app:
```diff
 # config.ru
 require ::File.expand_path('../config/environment', __FILE__)
-run Rails.application
+map Rails.application.config.relative_url_root || '/' do
+  run Rails.application
+end

 # config/application.rb
 module Webapp
   class Application < Rails::Application
     # ...
+    config.relative_url_root = '/app'
   end
 end

 # config/routes.rb
 UI = Proc.new { ['200', {'Content-Type' => 'text/html'}, ['Hello!']] }
 
 Rails.application.routes.draw do
-  root to: redirect('/ui')
+  root to: redirect('ui')
 
   mount UI, at: '/ui'
 end

 # nginx.conf
 server {
     listen 9000;

     location /app/ {
-        rewrite /app/(.*) /$1 break;
         proxy_pass http://localhost:3000;
     }
 }
```

===
Does it work after these changes?

**Comment by lukehorvat** [comment]
@merhard Yep, that works. But I was hoping to avoid this, since it requires the app to "know" the name of the subdirectory it is deployed to. Why should any of this be necessary if resource routes don't need it?

Also, on another note, shouldn't `map Rails.application.config.relative_url_root || '/' do` be in `config.ru` by default when generating a new Rails app? Would be one less thing for people to configure, and it doesn't affect folks who don't need it.
