### ISSUE TITLE
ActiveSupport::Cache methods naming

### ISSUE THREAD

**Issue by NickolasVashchenko** [rails/rails#21190]
I think cache method naming conventions should resemble the AcriveRecord ones. I'm speaking about Cache#exist? 
It would be more reasonable if it will be "#exists?". May I fix it?

**Comment by rafaelfranca** [comment]
Thank you so much for the issue but we don't take feature request on the issue tracker. We recommend you to try to implement the feature and send us a pull request or if you are in doubt if the feature will be accepts ask in Rails Core mailing list for feedback.

**Comment by NickolasVashchenko** [comment]
Okay, sure
