### ISSUE TITLE
Testing errors when the fixture file is referencing a missing column is obtuse

### ISSUE THREAD

**Issue by dhh** [rails/rails#21201]
Here's the error I got from having an extra, since-removed column mentioned in a yml fixture:

```
 30) Error:
RecurrenceScheduleTest#test_every_Friday_morning:
NoMethodError: undefined method `sql_type' for nil:NilClass
```

Ouch. We can do better than that.

**Comment by senny** [comment]
@dhh yea, this was more expressive in earlier versions. I'll have a look.

**Comment by senny** [comment]
Changed it to raise an `ActiveRecord::FixtureError`:

```
ActiveRecord::Fixture::FixtureError: table "parrots" has no column named "arrr"
```

**Comment by dhh** [comment]
Awesome! Thanks!
