### ISSUE TITLE
EXPLAIN Queries with Different Connections

### ISSUE THREAD

**Issue by kapkaev** [rails/rails#21216]
I encountered an issue with EXPLAIN queries being run on the same connection, while multiple databases are involved in a query.

For example, there are two tables located in different databases. When I try to run a query on a large collection of records, AR automatically executes EXPLAIN queries. As a result, it throws an error.

```ruby
class Book < ActiveRecord::Base
  establish_connection :db1
end

class Author < ActiveRecord::Base
  establish_connection :db2

  belongs_to :book
end

Book.includes(:author).explain
```

```ruby
EXPLAIN (201.9ms)  EXPLAIN SELECT "authors".* FROM "authors" WHERE "authors"."id" IN (917, 929, 30, 186434, 188423)
PG::UndefinedTable: ERROR:  relation "authors" does not exist
LINE 1: EXPLAIN SELECT "authors".* FROM "authors"  WHERE "autho...
```

It seems like the code that causes the issue is here:
https://github.com/rails/rails/blob/master/activerecord/lib/active_record/explain.rb#L26

Tested on Rails 3.2 and 4.2

**Comment by senny** [comment]
Explain queries should be executed on the connection specified by `connection_id` on the corresponding AS notification. 

#11284 seems related.

Something along the lines of https://gist.github.com/senny/dd6cfb12bee084f11bbb should do the trick. I'm not sure this is the right way to solve it though. I'll leave it to @rafaelfranca and @tenderlove wether it's a feasible approach.

**Comment by kapkaev** [comment]
@senny Thank you!

**Comment by rafaelfranca** [comment]
I'm not sure if this is something we want to fix. The automatic explain feature was removed and this is corner case that doesn't justify adding the complexity of walking the connection pool to find the right connection object. I'm closing.
