### ISSUE TITLE
Rails branch 2.3.18 stable / bundle exec rails / uninitialized constant AppGenerator::Config

### ISSUE THREAD

**Issue by DouglasAllen** [rails/rails#21215]
That's what I get using either this branch or the rubygems version 2.3.18
My gem file:

gem 'rails', '2.3.18'

The bundle is installing all the dependencies like activerecord and ...
I'm running it from rbenv with only bundler installed. gem install does the same thing.
I was only going to try to make a skelleten app like I have here https://github.com/DouglasAllen/rails-v3.2.22-starter for the 2.3.11 Railsguides. Is there anything like that out there on github that I could just fork? Thanks in advance.

**Comment by rafaelfranca** [comment]
Rails 2 is not supported anymore. The version that you are using is from more than 5 years ago and contains security bugs and a lot of issues that we don't recommend anyone to use it in a new application.
