### ISSUE TITLE
setting a model's boolean attribute to false in before_validation(:on => :update) cause validation error

### ISSUE THREAD

**Issue by dgobaud** [rails/rails#21212]
https://github.com/dgobaud/rails_before_validation_set_boolean_bug

how to reproduce

rake db:migrate
rails c
o = Order.new
o.save!
o.update_attributes!({}

ActiveRecord::RecordInvalid: Validation failed: 
	from /Users/davidgobaud/.rvm/gems/ruby-2.2.2/gems/activerecord-4.2.1/lib/active_record/validations.rb:79:in `raise_record_invalid'
	from /Users/davidgobaud/.rvm/gems/ruby-2.2.2/gems/activerecord-4.2.1/lib/active_record/validations.rb:43:in `save!'
	from /Users/davidgobaud/.rvm/gems/ruby-2.2.2/gems/activerecord-4.2.1/lib/active_record/attribute_methods/dirty.rb:29:in `save!'
	from /Users/davidgobaud/.rvm/gems/ruby-2.2.2/gems/activerecord-4.2.1/lib/active_record/transactions.rb:291:in `block in save!'
	from /Users/davidgobaud/.rvm/gems/ruby-2.2.2/gems/activerecord-4.2.1/lib/active_record/transactions.rb:347:in `block in with_transaction_returning_status'
	from /Users/davidgobaud/.rvm/gems/ruby-2.2.2/gems/activerecord-4.2.1/lib/active_record/connection_adapters/abstract/database_statements.rb:211:in `transaction'
	from /Users/davidgobaud/.rvm/gems/ruby-2.2.2/gems/activerecord-4.2.1/lib/active_record/transactions.rb:220:in `transaction'
	from /Users/davidgobaud/.rvm/gems/ruby-2.2.2/gems/activerecord-4.2.1/lib/active_record/transactions.rb:344:in `with_transaction_returning_status'
	from /Users/davidgobaud/.rvm/gems/ruby-2.2.2/gems/activerecord-4.2.1/lib/active_record/transactions.rb:291:in `save!'
	from /Users/davidgobaud/.rvm/gems/ruby-2.2.2/gems/activerecord-4.2.1/lib/active_record/persistence.rb:264:in `block in update!'
	from /Users/davidgobaud/.rvm/gems/ruby-2.2.2/gems/activerecord-4.2.1/lib/active_record/transactions.rb:347:in `block in with_transaction_returning_status'
	from /Users/davidgobaud/.rvm/gems/ruby-2.2.2/gems/activerecord-4.2.1/lib/active_record/connection_adapters/abstract/database_statements.rb:213:in `block in transaction'
	from /Users/davidgobaud/.rvm/gems/ruby-2.2.2/gems/activerecord-4.2.1/lib/active_record/connection_adapters/abstract/transaction.rb:188:in `within_new_transaction'
	from /Users/davidgobaud/.rvm/gems/ruby-2.2.2/gems/activerecord-4.2.1/lib/active_record/connection_adapters/abstract/database_statements.rb:213:in `transaction'
	from /Users/davidgobaud/.rvm/gems/ruby-2.2.2/gems/activerecord-4.2.1/lib/active_record/transactions.rb:220:in `transaction'
	from /Users/davidgobaud/.rvm/gems/ruby-2.2.2/gems/activerecord-4.2.1/lib/active_record/transactions.rb:344:in `with_transaction_returning_status'
... 3 levels...
	from /Users/davidgobaud/.rvm/gems/ruby-2.2.2/gems/railties-4.2.1/lib/rails/commands/console.rb:9:in `start'
	from /Users/davidgobaud/.rvm/gems/ruby-2.2.2/gems/railties-4.2.1/lib/rails/commands/commands_tasks.rb:68:in `console'
	from /Users/davidgobaud/.rvm/gems/ruby-2.2.2/gems/railties-4.2.1/lib/rails/commands/commands_tasks.rb:39:in `run_command!'
	from /Users/davidgobaud/.rvm/gems/ruby-2.2.2/gems/railties-4.2.1/lib/rails/commands.rb:17:in `<top (required)>'
	from /Users/davidgobaud/.rvm/gems/ruby-2.2.2/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:274:in `require'
	from /Users/davidgobaud/.rvm/gems/ruby-2.2.2/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:274:in `block in require'
	from /Users/davidgobaud/.rvm/gems/ruby-2.2.2/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:240:in `load_dependency'
	from /Users/davidgobaud/.rvm/gems/ruby-2.2.2/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:274:in `require'
	from /Users/davidgobaud/Desktop/testapp/bin/rails:8:in `<top (required)>'
	from /Users/davidgobaud/.rvm/gems/ruby-2.2.2/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:268:in `load'
	from /Users/davidgobaud/.rvm/gems/ruby-2.2.2/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:268:in `block in load'
	from /Users/davidgobaud/.rvm/gems/ruby-2.2.2/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:240:in `load_dependency'
	from /Users/davidgobaud/.rvm/gems/ruby-2.2.2/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:268:in `load'
	from /Users/davidgobaud/.rvm/rubies/ruby-2.2.2/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /Users/davidgobaud/.rvm/rubies/ruby-2.2.2/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'

**Comment by dgobaud** [comment]
the problem was it was "returning" false from the block and this is documented behavior

http://api.rubyonrails.org/classes/ActiveRecord/Callbacks.html

"before_validation* returning statements

If the returning value of a before_validation callback can be evaluated to false, the process will be aborted and Base#save will return false. If ActiveRecord::Validations#save! is called it will raise a ActiveRecord::RecordInvalid exception. Nothing will be appended to the errors object."

that seems odd so that might be the real issue

**Comment by rafaelfranca** [comment]
It is the documented behavior. It will change on Rails 5, though.
