### ISSUE TITLE
ActiveRecord - MySQL 5.7.7 JSON support

### ISSUE THREAD

**Issue by crypticsymbols** [rails/rails#21227]
Not so much an issue as a general question, apologies if there is a better place for this question.

http://mysqlserverteam.com/json-labs-release-native-json-data-type-and-binary-format/

The above article regards native JSON column support upcoming in MySQL. I think that's a fantastic feature and IIRC the Postgres adapter does support querying of JSON columns. I'm working on a few things right now that make me extra super excited because... well, because it's awesome. 3 questions:

1) Does that functionality depend on ActiveRecord or the adapter gem (in this case mysql2) or both?
2) If it's ActiveRecord, is this something that the community is already working on?
3) Is there any way I can help? I work with Rails but I am unfamiliar with the source code. However I'm happy to jump in to anything I can grok.

Edit: I think the scope of question should also include the new JSON type in MariaDB: https://mariadb.com/kb/en/mariadb/connect-json-table-type/

Also a big thank you to everyone who works on Rails source. You're all gods and I love you.

**Comment by senny** [comment]
Hey @crypticsymbols 

We use GitHub issues for bug reports exclusively and prefer the [rails-core mailing list](https://groups.google.com/forum/?fromgroups#!forum/rubyonrails-core) for general discussions about the framework itself.

Adding JSON support for MySQL has been brought up previously and there is even an open PR for it #21110. I'm going to close this issue to keep the discussion focused but please join in on #21110 with your questions.

Thank you :yellow_heart:
