### ISSUE TITLE
Postgres db:structure:dump and :load don't work with remote databases

### ISSUE THREAD

**Issue by schneems** [rails/rails#21226]
On this line https://github.com/rails/rails/blob/e50fe85180648be0c4216bd0111f05be1df0988a/activerecord/lib/active_record/tasks/postgresql_database_tasks.rb#L64

We are shelling out to `pg_dump` and passing in the database name. This doesn't include, host, password, or any other connection information. if your database is not on the same server where rails is, then this command will fail with a cryptic error:

```
Error: You must install at least one postgresql-client-<version> package.
```

The same is true here: https://github.com/rails/rails/blob/e50fe85180648be0c4216bd0111f05be1df0988a/activerecord/lib/active_record/tasks/postgresql_database_tasks.rb#L71

We need to pass in full configuration options to these tasks so that they'll work with remote databases.

**Comment by myrridin** [comment]
I've posted a pull request that I believe satisfies this request. Please let me know if you have any feedback. I'd be happy to make any required changes.

https://github.com/rails/rails/pull/21232

**Comment by myrridin** [comment]
Ok I think I figured out the issue, and it means this isn't actually necessary in the first place. The method `set_psql_env` (https://github.com/myrridin/rails/blob/master/activerecord/lib/active_record/tasks/postgresql_database_tasks.rb#L91-L96) sets a number of environment variables that make the command line options redundant. It's called as the first line in both the dump and load routines.

I'm going to close the pull request. Sorry for the wasted Travis CI time.

**Comment by matthewd** [comment]
> `set_psql_env`

Indeed. @schneems, you need to.. install at least one `postgresql-client-<version>` package.

(Unless you're saying it's cryptic because you actually already have one. But in that case, it would be a bug for [elsewhere](https://tracker.debian.org/pkg/postgresql-common).)

**Comment by schneems** [comment]
You're quite correct, I'm able to run this locally, specifying a remote database:

```
$ env DATABASE_URL=postgres://bar@ec2-54-163-253-141.compute-1.amazonaws.com:5602/name bundle exec rake db:structure:dump
```

Thanks for the look!
