### ISSUE TITLE
 ActionDispatch::Routing::Mapper::Scope no longer provides `[]=`

### ISSUE THREAD

**Issue by jashank** [rails/rails#21231]
This was removed in 5e81e6ca31aa0d2a38f8db5c8fe9bcbce98d9689 with a commit note that it isn't used; this, however, is incorrect and it's used in other projects such as (e.g.) [cerebris/jsonapi-resources]
(https://github.com/cerebris/jsonapi-resources/blob/master/lib/jsonapi/routing_ext.rb#L80).  Given that this was a public method, and no documented replacement has been provided, this strikes me as an issue.

See also cerebris/jsonapi-resources#380.

**Comment by rafaelfranca** [comment]
That class is entirely private and should not be used directly. We removed a private API method but you can use public methods to archive the same. See https://github.com/plataformatec/devise/issues/3701#issuecomment-130831743
