### ISSUE TITLE
Move ActiveModel::Serializers to Rails Github Org

### ISSUE THREAD

**Issue by maclover7** [rails/rails#21260]
A recently extracted gem, ActiveModel::Serializers::Xml, is now hosted in the Rails Github organization. For consistency, and since rails-api is now in Rails master, does it make sense to move active_model_serializers as well, and to deprecate the rails-api Github org?

**Comment by rafaelfranca** [comment]
Please don't open issues for discussions, we reserve the issue tracker only for issues and pull requests. About `active_model_serializers` I don't think it needs to be moved to rails organization. It is maintained by a different team not by Rails Core.
