### ISSUE TITLE
BigDecimal::NaN not quoted in SQL query

### ISSUE THREAD

**Issue by Hugo-Hache** [rails/rails#21262]
With any model with a decimal column, if you try to query for the rows with a NaN value you get the following error:

<pre>
Model.where(column: BigDecimal::NAN)

PG::UndefinedColumn: ERROR:  column "nan" does not exist
LINE 1: ... "model"."column" = NaN
</pre>

The problem is the missing quotes around NaN, as <pre>Model.where(" column = 'NaN' ")</pre> works just fine.

By browsing the source code I presume there is a missing BigDecimal case in this class, https://github.com/rails/rails/blob/master/activerecord/lib/active_record/connection_adapters/postgresql/quoting.rb#L83, but being not aware of the AR internals I was not confident enough to propose a patch.

**Comment by robin850** [comment]
Hi @Hugo-Hache,

Thanks for reporting! Yes, this is the right place to edit. Would you mind to open a pull request with the patch, a changelog entry and a test ?

**Comment by BenEddy** [comment]
[Here](https://github.com/BenEddy/rails/commit/b1421b8ce8786503090f89cff09945c897969228) is a patch per @Hugo-Hache's suggestion. 

I can open a PR and apply it to this issue, but quick question: Is there a reason NaN and infinity handling doesn't happen in the [abstract implementation](https://github.com/rails/rails/blob/master/activerecord/lib/active_record/connection_adapters/abstract/quoting.rb#L155)? As far as I can tell `'NaN'` and `'Infinity'` are supported by SQLite, pg and mysql.

**Comment by idler921** [comment]
Same problem for mysql

ActiveRecord::StatementInvalid: Mysql2::Error: Unknown column 'NaN' in 'field list': UPDATE `t` SET `f` = NaN WHERE `t`.id = 2

        from /usr/local/rvm/gems/ruby-2.2.1/gems/mysql2-0.4.2/lib/mysql2/client.rb:107:in `_query'
        from /usr/local/rvm/gems/ruby-2.2.1/gems/mysql2-0.4.2/lib/mysql2/client.rb:107:in `block in query'
        from /usr/local/rvm/gems/ruby-2.2.1/gems/mysql2-0.4.2/lib/mysql2/client.rb:106:in `handle_interrupt'
        from /usr/local/rvm/gems/ruby-2.2.1/gems/mysql2-0.4.2/lib/mysql2/client.rb:106:in `query'
        from /usr/local/rvm/gems/ruby-2.2.1/gems/activerecord-4.2.5/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:305:in `block in execute'
        from /usr/local/rvm/gems/ruby-2.2.1/gems/activerecord-4.2.5/lib/active_record/connection_adapters/abstract_adapter.rb:472:in `block in log'
        from /usr/local/rvm/gems/ruby-2.2.1/gems/activesupport-4.2.5/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
        from /usr/local/rvm/gems/ruby-2.2.1/gems/activerecord-4.2.5/lib/active_record/connection_adapters/abstract_adapter.rb:466:in `log'

**Comment by maclover7** [comment]
Hmm, seems like this has been fixed on Rails master and `4-2-stable` -- the following script passes for me :

```ruby
require 'active_record'
require 'minitest/autorun'
require 'logger'

# This connection will do for database-independent bug reports.
ActiveRecord::Base.establish_connection(adapter: 'sqlite3', database: ':memory:')
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :posts, force: true do |t|
    t.string :test_column
  end
end

class Post < ActiveRecord::Base
end

class BugTest < MiniTest::Test
  def test_21262
    p = Post.create!(test_column: BigDecimal::NAN)
    assert_equal p, Post.where(test_column: BigDecimal::NAN).first
  end
end
```

**Comment by philtr** [comment]
👋 Hello, running into this issue when prepared statements are disabled. The following adaptation of the above test case will blow up:

```ruby
require 'active_record'
require 'minitest/autorun'
require 'logger'

# This connection will do for database-independent bug reports.
connection_options = {
  adapter: 'sqlite3',
  database: ':memory:',
  prepared_statements: false
}
ActiveRecord::Base.establish_connection(connection_options)
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :posts, force: true do |t|
    t.decimal :test_column
  end
end

class Post < ActiveRecord::Base
end

class BugTest < MiniTest::Test
  def test_21262
    p = Post.create!(test_column: BigDecimal::NAN)
    assert_equal p, Post.where(test_column: BigDecimal::NAN).first
  end
end
```

I tried this on `4.2.8`, `4-2-stable`, `5-0-stable`, and `master` with the same result.
