### ISSUE TITLE
[PERF] ActiveRecord save

### ISSUE THREAD

**Issue by tgxworld** [rails/rails#21266]
BenchmarkScript: https://github.com/ruby-bench/ruby-bench-suite/blob/426e2fb379d2c2e6a7d3a1f00feb57ab53149be8/rails/benchmarks/bm_activerecord_save.rb

#### Before https://github.com/rails/rails/commit/e0cb21f
```
activerecord/postgres_save 970.6787719264458/ips
activerecord/mysql2_save 1159.4730621393544/ips
```

#### At https://github.com/rails/rails/commit/e0cb21f
```
activerecord/postgres_save 951.5163865085796/ips (-1.98%)
activerecord/mysql2_save 1078.8367875046874/ips (-6.95%)
```

View full graphs
http://rubybench.org/rails/rails/commits?result_type=activerecord/mysql2_save&display_count=2000
http://rubybench.org/rails/rails/commits?result_type=activerecord/postgres_save&display_count=2000

cc/ @tristang

Let me know if you need more information :smile:

**Comment by senny** [comment]
Merged with #19683

/cc @rafaelfranca

**Comment by tristang** [comment]
At a guess I'd say it's looking up the inverse relation (`inverse_which_updates_counter_cache(reflection)`) that's slowing things down here.

If the `counter_cache` was required on both sides of the relation (both the `has_many` and `belongs_to`) we could bypass this, but otherwise I'm not sure what can be done.

**Comment by rafaelfranca** [comment]
Can we confirm it locally? It should not affect saving a model without any association given the location of the changes on that commit.

**Comment by tgxworld** [comment]
@rafaelfranca opps my mistake. It should be one of the commits within this [range](https://github.com/rails/rails/compare/e2530ca...e0cb21f). I forgot I skipped some of the commits when backfilling. I'll find the commit soon.

**Comment by rafaelfranca** [comment]
OMG! The range is huge. Let me know if I can help with finding it

**Comment by rafaelfranca** [comment]
Maybe it is related to the callbacks optmization revert? It seems to be in that range.

**Comment by tgxworld** [comment]
@rafaelfranca xD I'll just backfill all commits within that range on RubyBench. Should be able to find out tml.

**Comment by tgxworld** [comment]
@rafaelfranca xD I'll just backfill all commits within that range on RubyBench. Should be able to find out tml.

**Comment by tgxworld** [comment]
:sob: sorry @rafaelfranca @tristang double whammy by me. I recently made a change that broke the ordering on the graph.....so it was a self generated performance regression..... I pushed a [fix](https://github.com/ruby-bench/ruby-bench-web/commit/bca50b1940cdf2770d8c6137128920598a4068fd) for it. Sorry!
