### ISSUE TITLE
ActiveModel::Validator classes break when using instance variables

### ISSUE THREAD

**Issue by abe4mvp** [rails/rails#21261]
I discovered this in Rails 3.2.1 but based on this [code](https://github.com/rails/rails/blob/master/activemodel/lib/active_model/validations/with.rb#L77-L95) Im pretty sure it still applies in the latest version.

Since the class is only instantiated once you can not use instance variable because they will be polluted by previous times that the same validator was used. This is unexpected since the key method of the `ActiveModel::Validator` class is the `#validate` instance method which would imply that an new instance is always created. 

It might be more intuitive that these classes must define an `.validate` class method instead but this would be a breaking change. Therefore ideally the Validator would be instantiated each time.

**Comment by rafaelfranca** [comment]
If you want this behavior you can use `validates_with` on the instance level. The validation object is instantiated on definition time if you use class level methods.

Also see https://github.com/rails/rails/blob/master/activemodel/lib/active_model/validator.rb#L63-L64
