### ISSUE TITLE
Missing time zone for Namibia

### ISSUE THREAD

**Issue by eyaleizenberg** [rails/rails#21285]
Hi,
At the moment Rails only supports the West Central Africa time zone. Namibia uses this time zone but they also use "West Africa Summer Time (Daylight Saving Time)". Can you please add this time zone as well?

Thank you.

**Comment by repinel** [comment]
Related to #10276.

**Comment by nlcurry** [comment]
Has there been progress on this issue? What is the pr associated with it?

**Comment by rafaelfranca** [comment]
https://github.com/rails/rails/issues/22440#issuecomment-178095649
