### ISSUE TITLE
Prevent hydration of AR object if after_initialize returns false

### ISSUE THREAD

**Issue by danlaffan** [rails/rails#21291]
Ref: http://stackoverflow.com/questions/32077572/return-nil-object-if-after-initialize-callback-returns-false

If I have a Department model with code as follows:

    # app/models/department.rb
    class Department < ActiveRecord::Base
      after_initialize :check_permission

      protected

      def check_permission
        # some code that returns true or false
      end

    end

I would like <code>Department.first</code> to return <code>nil</code> if the <code>check_permission</code> method returns <code>false</code>.  Is there any way of achieving this?

Will this behaviour change in Rails 5?

**Comment by rafaelfranca** [comment]
Please use the mailing list or StackOverflow for questions/help, where a wider community will be able to help you. We reserve the issues tracker for issues only.
