### ISSUE TITLE
Issues with bundle 

### ISSUE THREAD

**Issue by vipulnsward** [rails/rails#21299]
celluloid version 0.16.1 got yanked- https://rubygems.org/gems/celluloid/versions
Its causing issues with bundle- https://github.com/rails/rails/blob/master/Gemfile.lock#L137

**Comment by mrbrdo** [comment]
getting same issue

**Comment by senny** [comment]
Fixed by https://github.com/rails/rails/commit/51211a94bd7a34d80f2412a7f94fefe7366647a5
