### ISSUE TITLE
create_join_table incorrectly prepends table_name_prefix to first table name before generating table name

### ISSUE THREAD

**Issue by frenkel** [rails/rails#21307]
In Ruby On Rails 4.2.3, the join_table name will be derived incorrectly. For example:

```
ActiveRecord::Base.table_name_prefix = 'test_'

create_join_table :actions, :scenarios
```

This will create a table named `scenarios_test_actions`. I debugged the code a bit and it seems the table_1 argument of create_join_table gets the prefixed name instead of later prepending it.

**Comment by EddM** [comment]
#21329 *should* fix this

**Comment by frenkel** [comment]
@senny Will this get merged before a new release is made?

**Comment by senny** [comment]
I'm worried that if we just merge and release, that this might break apps with migrations written prior to this patch.

@matthewd what is the state of the versioned migration DSL?

**Comment by frenkel** [comment]
@senny @matthewd @EddM Any news?

**Comment by senny** [comment]
@frenkel now that the migration DSL has landed I think we should be able to solve this issue.

**Comment by frenkel** [comment]
Great, let me know when I can help!
