### ISSUE TITLE
RangeError when querying for big integer using #where in Rails 4.2

### ISSUE THREAD

**Issue by januszm** [rails/rails#21309]
Rails 3

Product.where(associated_id: 1311344470881970878875083923).first
=> nil

Rails 4.2.3

Product.where(associated_id: 1311344470881970878875083923).first
RangeError: 1311344470881970878875083923 is out of range for ActiveRecord::ConnectionAdapters::PostgreSQL::OID::Integer with limit 8
from ~/.rvm/gems/ruby-2.2.1@gemset/gems/activerecord-4.2.3/lib/active_record/type/integer.rb:45:in ```ensure_in_range```

I'd expect that the finder returns nothing in Rails 4.2.3 as well in such a case. It's just searching for results, we don't need to call ensure_in_range.

As a workaround, someone could use ```find_by```, but when there's a need for returning multiple records, then there's no such method as ```find_all_by``` that could be used. BTW. find_by works because it rescues from RangeError.

**Comment by matthewd** [comment]
> It's just searching for results, we don't need to call ensure_in_range.

Yes, we do. That value won't fit into a PostgreSQL bigint, so we cannot run the query with it.

Previous versions didn't use parameterized queries, so PostgreSQL was able to dynamically guess the type based on the size of the literal.

**Comment by januszm** [comment]
@matthewd  no it doesn't, look, it's just a simple query to find something in the database

development=> select * from products where associated_id = 1184827921141444343875083923;
(0 rows)

PostgreSQL 9.4.4 , no error. 

Anyway, perhaps it's easier to just add find_all_by method as I described above.

```ruby
def find_all_by(*args)
  where(*args).load
rescue RangeError
  none
end
```

**Comment by matthewd** [comment]
> look, it's just a simple query

Great! Patch welcome.

> perhaps it's easier to just add find_all_by method

We can't do that, for the same reason we don't currently rescue the RangeError everywhere: it would behave incorrectly any time the out-of-range value *didn't* imply no results. (e.g., `where.not(id: BIG_NUMBER).find_all_by(name: 'Fred')`)

**Comment by agis-** [comment]
@matthewd What about introducing a new exception class so we can rescue it instead of the general `RangeError`? /cc @sgrif 

If it sounds good, I can submit a PR.

**Comment by eavgerinos** [comment]
@matthewd IMHO, this behavior is kind of strange.

If you use `find(903475239045782034957203945782934058230498)` you get an `ActiveRecord::RecordNotFound` with a customized message for the out of range id.

If you use `where(id: 903475239045782034957203945782934058230498)`, you get a `RangeError`.

**Comment by sgrif** [comment]
The for `where` is that we don't actually have a thing that we can do consistently to handle it other than raise an exception. 

> ActiveRecord should be able to perform select queries with everything that the RDBMS allows you to.

The RBDMS will not allow you to query with an out of range integer (sometimes, depending on context). This change was made to allow you to handle a `RangeError` with consistent semantics, rather than sometimes get `StatementInvalid`

**Comment by januszm** [comment]
I'm OK with it but it would be good to add a method which returns multiple records,  similar to find_by to FinderMethods module

```ruby
##
# Like <tt>find_by</tt>, but returns multiple records or none relation
#
def find_all_by(*args)
  where(*args).load
rescue RangeError
  none
end
```

**Comment by agis-** [comment]
@sgrif What about https://github.com/rails/rails/issues/21309#issuecomment-144967189?

**Comment by sgrif** [comment]
@januszm If it were that simple, we would have just done that in `where`. Whether `none` vs `all` is correct varies by context in non-intuitive ways that we can't infer programmatically. 

@agis- I think that `RangeError` is sufficiently specific for a value that is out of the valid range.

**Comment by agis-** [comment]
@sgrif Thing is, we are now forced to rescue `RangeError` in `ApplicationController` just to handle the ActiveRecord cases, when in fact `RangeError` may be coming from lots of other places which have nothing to do with AR. I was thinking something more specific like `QueryRangeError` which could inherit from `RangeError`.

**Comment by kdavh** [comment]
@agis- I completely agree, something like `ActiveRecord::RangeError` would be much better than a generic error like `RangeError`.

@sgrif I would agree that `RangeError` is acceptable, except the context of ActiveRecord's general use makes it so that a more specific error class is appropriate.  `class ActiveRecord::RangeError < RangeError` is a good direction to go.
