### ISSUE TITLE
Activerecord bug with reflection method in counter_cache_attribute_name 

### ISSUE THREAD

**Issue by bluebird-communication** [rails/rails#21316]
When I use the inherited activerecord's methods (such has `empty?`) on my objects in my controller, it throws the error :

> undefined method `name' for nil:NilClass

Despite my object has a valid Class with a valid ID (I checked it in my logger.debug).

The full trace showy activerecord as origine of this issue :

> activerecord (3.2.21) lib/active_record/associations/has_many_association.rb:58:in `cached_counter_attribute_name'

> activerecord (3.2.21) lib/active_record/associations/has_many_association.rb:54:in `has_cached_counter?'

> activerecord (3.2.21) lib/active_record/associations/has_many_association.rb:37:in `count_records'

> activerecord (3.2.21) lib/active_record/associations/collection_association.rb:261:in `size'

> activerecord (3.2.21) lib/active_record/associations/collection_association.rb:280:in `empty?'

> activerecord (3.2.21) lib/active_record/associations/collection_proxy.rb:46:in `empty?

If I check lib/active_record/associations/collection_association.rb file on my gemset I got the following :

        def has_cached_counter?(reflection = reflection)
          owner.attribute_present?(cached_counter_attribute_name(reflection))
        end

        def cached_counter_attribute_name(reflection = reflection)
          "#{reflection.name}_count"
        end

**Which leads me to ask : "What is `reflection`and why does it return `nil`**

Checking the official 3.2.21 repository, I found that it looks slightly different :

        def has_cached_counter?(reflection = self.reflection)
          owner.attribute_present?(cached_counter_attribute_name(reflection))
        end

        def cached_counter_attribute_name(reflection = self.reflection)
          "#{reflection.name}_count"
        end

Could this `self`protected word be the cause of my pain ? and how could this happend ?

More over If I check the [last **3.2 stable** commit 8 monthes ago] I see  : **use self.method syntax to resolve circular argument issues** and then compare it with the last **4.2 stable**, then it does not include this correction (`reflection()` instead of `self.reflection`).

Why ?

  [1]: https://github.com/rails/rails/commit/3a30b12c774dfaa72acfe520e823374131631ea9

**Comment by matthewd** [comment]
Rails 3.2 is no longer supported
