### ISSUE TITLE
Mailer preview unknown error

### ISSUE THREAD

**Issue by poc7667** [rails/rails#21325]
I got `NoMethodError (undefined method `multipart?' for true:TrueClass):`

here's my mail template, i can find any useful clue from the error message

![](https://i.imgur.com/HUkfT5J.png)

here's my mail template, i can send the mail by delivery method but can not preview it.

**Comment by agis-** [comment]
Can you try with the latest 4.2 release? If this doesn't do the trick, can you provide a sample app that reproduces the issue?

**Comment by poc7667** [comment]
Sure, thanks for your suggestion, i've upgraded to 4.2.3.and the exception changed to `undefined method `find_first_mime_type' for #<Hash` and here my app code https://gist.github.com/poc7667/395958fe40610310cbd3

**Comment by agis-** [comment]
I was talking about a sample (ideally stripped down) rails application that demonstrates the issue. It would certainly help to diagnose the problem.

**Comment by arthurnn** [comment]
@poc7667 any updates on this? wondering if it is still a problem with latest Rails 4.2.x or not, also we need to simulate that locally, otherwise we cannot fix the problem.
I will close this for now, fell free to re-open it with a failing app.

thanks

**Comment by chrisnicola** [comment]
I'm seeing this with 4.2.4. I don't have a repro in a simple app yet but here is the end of the stack trace:

```
15:25:57 rails.1   |
15:25:57 rails.1   | NoMethodError (undefined method `find_first_mime_type' for nil:NilClass):
15:25:57 rails.1   |   railties (4.2.4) lib/rails/mailers_controller.rb:58:in `block in find_preferred_part'
15:25:57 rails.1   |   railties (4.2.4) lib/rails/mailers_controller.rb:57:in `each'
15:25:57 rails.1   |   railties (4.2.4) lib/rails/mailers_controller.rb:57:in `find_preferred_part'
15:25:57 rails.1   |   railties (4.2.4) lib/rails/mailers_controller.rb:34:in `preview'
1
```

**Comment by atinder90** [comment]
Facing same issue with fresh installation of Rails 4.2.5
Sample app https://github.com/atinder90/rails-mailer-bug

**Comment by del-flexe** [comment]
I believe the error occurs if the method in _test/mailers/previews/my_preview.rb_ returns anything but an actual email type ... i.e. forgetting to call _MyMailer.my_email_method(args)_
