### ISSUE TITLE
Support for Indian system in number_to_currency helper

### ISSUE THREAD

**Issue by shireeshj** [rails/rails#21330]
In India currency units are expressed somewhat differently. For example,

      In the USA | In India
      ----------------|------------- 
    One Hundred Thousand (100,000)  | One Lakh (1,00,000)
    Million (1,000,000) | Ten Lakhs (10,00,000)
    Ten Millions (10,000,000) | One Crore (1,00,00,000)

As you can notice, number formatting changes a bit. Initial grouping of digits starts with 3 digits, thereafter grouping is of 2 digits.

I could not tackle this using the locale file as there is no option to specify a format-mask

I am guessing that this can be fixed by modifying the regex a bit in `/activesupport/lib/active_support/number_helper/number_to_delimited_converter.rb`

if we conditionally change

     DELIMITED_REGEX = /(\d)(?=(\d\d\d)+(?!\d))/

to

     DELIMITED_REGEX = /(\d+?)(?=(\d\d)+(\d)(?!\d))(\.\d+)?/

when locale is `en-in`, it will format the currency properly for India.

Is this the right approach?

**Comment by shireeshj** [comment]
I realized I am not supposed to make feature requests here. I have dropped an email to the rails core group mailing list as recommended by the guide. In the meanwhile, I have also make code change and submitted a PR  #21394

**Comment by sgrif** [comment]
https://github.com/rails/rails/pull/21394#issuecomment-135594086
