### ISSUE TITLE
Doc: Unexplained feature or bug in Active Record Query Interface begin_at doc example

### ISSUE THREAD

**Issue by thomassnielsen** [rails/rails#21349]
https://github.com/rails/rails/blame/master/guides/source/active_record_querying.md#L344

In the `Active Record Query Interface` guide, there is an example of using `begin_at` to split work between workers:

> Another example would be if you wanted multiple workers handling the same processing queue. You could have each worker handle 10000 records by setting the appropriate `:begin_at` option on each worker.

Either there is some sort of multi-worker locking going on behind the scenes (which should be explained here), or I misunderstand the usage described, or this usage would end in doing double work:

### Example

Users table with 50.000 records

First worker: 
```
User.find_each(begin_at: 0, batch_size: 10000) do |user|
  NewsMailer.weekly(user).deliver_now
end
```

Second worker:
```
User.find_each(begin_at: 10000, batch_size: 10000) do |user|
  NewsMailer.weekly(user).deliver_now
end
```

I would expect the workers to run through 50.000 and 40.000 records, respectively.  

If there is indeed some magic going on in the background stopping the workers from overlapping, this should be explained here.

(side note: There seems to be a transition going on from `start` to `begin_at`, where the repo was updated to use `begin_at` in February, while [guides.rubyonrails.org](http://guides.rubyonrails.org/active_record_querying.html) still says `start`.)

**Comment by senny** [comment]
@thomassnielsen the examples given in the guides are not directly related to the sentence:

> Another example would be if you wanted multiple workers handling the same processing queue. You could have each worker handle 10000 records by setting the appropriate :begin_at option on each worker.

If you wanted to achieve this, you would have to use both `begin_at` and `end_at`.

The official guides (http://guides.rubyonrails.org) still mention `start` and not `begin_` because the change you mentioned is only present on `master` and will be part of Rails 5. The official guides represent the current latest released version. If you want to read the edge guides you can go to http://edgeguides.rubyonrails.org/

**Comment by thomassnielsen** [comment]
I see. It seems to be the case that `end_at` isn't a part of Rails 4 either (there is no `end_at` equivalent together with `start`). How would one achieve the multiple workers scenario that is described? I'd like to see the docs updated with a more complete example, or remove/replace it if it isn't easily explainable. For master/Rails 5 I guess adding an `end_at` example and updating the text to mention `end_at` would suffice.

**Comment by senny** [comment]
@thomassnielsen you're right, I'll take care.

**Comment by senny** [comment]
I changed the guides both on `master` and `4-2-stable` to reflect this discussion. http://guides.rubyonrails.org will update once a new `4.2.x` release is out.

@thomassnielsen thank you for reporting :yellow_heart:

**Comment by thomassnielsen** [comment]
Awesome, thanks :smile:
