### ISSUE TITLE
Where.not illogical behavour

### ISSUE THREAD

**Issue by biomancer** [rails/rails#21352]
As stated in docs, and as it is in fact, 

    User.where.not(name: "Jon", role: "admin")

is translated to 

    SELECT * FROM users WHERE name != 'Jon' AND role != 'admin'

which is kind of strange, because `!(a && b)` is equivalent to `!a || !b`, not to `!a && !b`.

So correct negation of `where(name: "Jon", role: "admin")` condition is  

    SELECT * FROM users WHERE name != 'Jon' OR role != 'admin'

Implementing `.not` in that way would allow building correct negation conditions, while allowing old behaviour in logically correct and predictable `where.not(name: "Jon").where.not( role: "admin")`. 
Currently building negation of `where(name: "Jon", role: "admin")` condition is not possible without using raw SQL or arel.

**Comment by sgrif** [comment]
You can build the negation you want using relation.or in Rails 5. A breaking change of this magnitude would not be accepted
