### ISSUE TITLE
ActiveRecord saves records with invalid associations

### ISSUE THREAD

**Issue by anildigital** [rails/rails#21357]
My friend @sahilm is facing below issue with Active Record. Creating this issue on behalf of him.

Original gist here https://gist.github.com/sahilm/77c921e9299fdcbfb772

```ruby
require 'bundler/setup'
require 'active_record'
require 'minitest/autorun'

describe ActiveRecord do
  it 'saves records with invalid associations' do
    # initialize an invalid address
    invalid_address = Address.new
    # It's not valid. Cool!
    invalid_address.valid?.must_equal false
    # Assign this invalid address to a new user
    user = User.new(name: 'John doe', address: invalid_address)
    # Attempt to save the user. Expect it to fail with an exception
    user.save!
    # What? It doesn't fail!
    # The address is reported as a invalid address. How can this be?
    user.address.must_equal invalid_address
    # Reload the user from the database
    user.reload
    # Poof fails here. user.address == nil.
    user.address.must_equal invalid_address
    # Notice the presence validation on address in the User class.
    # ActiveRecord just saved an invalid model.
    # This is expected behaviour. You're supposed to do
    # validates_associated :address
    # But why? This is surprising behaviour.
  end

  before do
    ActiveRecord::Migration.verbose = false
    ActiveRecord::Base.establish_connection(adapter: 'sqlite3',
                                            database: ':memory:')
    ActiveRecord::Schema.define(version: 1) do
      create_table :users do |t|
        t.string :name
      end
      create_table :addresses do |t|
        t.string :city
        t.string :state
        t.integer :user_id
      end
    end
  end

  after do
    ActiveRecord::Base.connection.close
  end

  class User < ActiveRecord::Base
    has_one :address
    validates :name, :address, presence: true
  end

  class Address < ActiveRecord::Base
    belongs_to :user
    validates :city, :state, presence: true
  end
end
```

**Comment by johnpaulashenfelter** [comment]
@anildigital @sahilm  can you verify which version(s) of active_record you are using?

**Comment by al2o3cr** [comment]
The autosave mechanism will persist models even if they aren't valid unless explicitly told with `validate: true`:
```ruby
  has_one :address, validate: true
```

**Comment by johnpaulashenfelter** [comment]
+1 @al2o3cr 

The address *is* present, which is what `presence: true` checks. The `user` definitely has an address when you call `.save!` in your example, its just not valid and there's no code that shows you have to check the validity.

http://guides.rubyonrails.org/association_basics.html has some details, section 4.1.2.9 for example.

**Comment by sgrif** [comment]
From the same guide that you just linked to, documenting the `has_one` association:

> If you set the :validate option to true, then associated objects will be validated whenever you save this > object. By default, this is false: associated objects will not be validated when this object is saved.

This is the expected behavior. You can fix it by changing `has_one :address` to `has_one :address, validate: true`

**Comment by sgrif** [comment]
Also just to be clear since you mentioned a different part of the guide, you were pointing to the behavior of `belongs_to`, which has different behavior.
