### ISSUE TITLE
render and return

### ISSUE THREAD

**Issue by elfassy** [rails/rails#21358]
Using Rails4.2

```ruby
render json: {name: "json"}
@out = "after json"
```

In the view, `@out == "after json"`
but

```ruby
render 'template'
@out = "after template"
```

In the view `@out == nil`. It seems strange to me that in one case render returns and in another it doesn't. Am i missing something?

cheers!

**Comment by al2o3cr** [comment]
@elfassy - where exactly is the code you're describing as "in the view" in the first example? Rendering a template after the `render json:` call will (I believe) give a `DoubleRenderError`.

In the second case, the behavior is as expected - the call to `render` runs immediately, so instance variables set afterwards are naturally unavailable.

**Comment by repinel** [comment]
@elfassy Could you clarify the issue? Thanks

**Comment by ajm188** [comment]
If I had to guess, @elfassy is not rendering twice in the same action. I believe the question is about why rendering a template returns control from the controller action immediately, but rendering json does not.

**Comment by elfassy** [comment]
ajm188 is correct, the issue is that `render 'template'` will return so anything after will not run, but with `render json:` it does not return and in my example the `@out` instance variable is set.

**Comment by bf4** [comment]
Close as stale? Or as resolved?
