### ISSUE TITLE
Error in documentation about ActiveRecord::Enum

### ISSUE THREAD

**Issue by agrimm** [rails/rails#21364]
The documentation about ActiveRecord::Enum has an error.

It has

    # conversation.update! status: 1
    conversation.status = "archived"

indicating that `conversation` gets saved when the method is called (because of the bang in `update!`), but `conversation` doesn't get saved.

I haven't submitted a pull request, because I haven't checked whether the rest of the documentation is correct.

**Comment by rafaelfranca** [comment]
You are right. Could you send a PR? Only this case and the `nil` case are wrong.

**Comment by agrimm** [comment]
Ok, will do.
