### ISSUE TITLE
Rails 4.2.3 Mailers#preview + inline attachment not displaying

### ISSUE THREAD

**Issue by hackeron** [rails/rails#21376]
This is in my mailer:

```ruby
  def new_sign_in(user, timeline_name)
    add_logo
    mail to: "test@test.com", subject: "test"
  end

  def add_logo
    attachments.inline['logo.png'] = \
      File.read(File.expand_path('../../assets/images/logo.png', __FILE__))
  end
```

This is in my mailer preview file:

```ruby
  def new_sign_in
    UserMailer.new_sign_in(User.new, 'test')
  end
```

In my template file I have:

```slim
= image_tag attachments['logo.png'].url
```

When going to http://localhost:3000/rails/mailers/user_mailer/new_sign_in in the browser, instead of seeing an image, I see this:

```html
<img height="64px" style="display:block" src="cid:55dc9623ce524_e1e3feb273f27ec70f0@Romans-Mac-Pro.local.mail">
```

However, if I run UserMailer.new_sign_in(user, timeline_name).deliver_now with the 'letter_opener' gem installed, I can see a correct preview of the email with the image.

I think it could be related to: http://stackoverflow.com/questions/26574811/rails-4-mailer-preview-preview-attached-images - but the linked issue (#14435) there has been resolved, so this appears to be a new issue?

**Comment by hackeron** [comment]
It seems creating a new initialiser file with this does the trick:

```ruby
# config/initializer/preview_interceptors.rb
ActionMailer::Base.register_preview_interceptor(ActionMailer::InlinePreviewInterceptor)
```

**Comment by pixeltrix** [comment]
@hackeron yes, since it's implemented as preview interceptor it's disabled by default in 4.2 for backwards compatibility and enabled by default in Rails 5.
