### ISSUE TITLE
Option to disable triggering after_(commit|rollback) callbacks for belongs_to with touch: true 

### ISSUE THREAD

**Issue by eavgerinos** [rails/rails#21397]
Back in Rails 3.2 the `touch: true` option didn't trigger any of the `after_commit` or `after_rollback` callbacks.

The above behavior, was [changed in Rails 4](https://github.com/rails/rails/pull/12031), and now, when touching a model, it triggers `after_commit` and `after_rollback` callbacks.

I believe, since many applications are still running on Rails 3.2 and are based on its conventions, that there should be an option like `:skip_transaction_state_callbacks` for touching.

**Comment by sevenseacat** [comment]
its a bit late to bring this in, isn't it? The behaviour was changed a full two years ago.

**Comment by rafaelfranca** [comment]
Yeah, also it make sense to trigger the callbacks

**Comment by natesholland** [comment]
Any chance this will be reviewed? I'm upgrading an app from 3.2 to 4.1 and this just bit me and it would be nice if we could turn it off.

**Comment by arthurnn** [comment]
@natesholland I had issues with that when upgrading apps too. If you wanna tackle this and create a gem for better compatibility, would be awesome. Otherwise I can do it next time I do an upgrade.

**Comment by natesholland** [comment]
@arthurnn I was able to solve this by putting this oneliner in an initializer:

`ActiveRecord::Transactions.send(:remove_method, :touch)`

I'm not sure it needs a whole gem, but it should be easy enough to wrap up into one.

**Comment by arthurnn** [comment]
if thats the only change, I guess no need for a gem.
Thanks
