### ISSUE TITLE
ActiveRecord index: true in Rails 4.2 pg 9.4.1

### ISSUE THREAD

**Issue by zw963** [rails/rails#21395]
When create a table in migrate, follow definition is valid. 
```ruby
  def change
    create_table :add_new_tables do |t|
      t.jsonb :data, index: true
    end
  end
```
I found this create a `btree index` for this `data` jsonb field, not `gin` or `gist`.

I think those should be a misusage for index: true ? 

Or just `index: true` will autoselect the best index for me, `btree` is  the best result for this case?

Thanks

**Comment by senny** [comment]
@zw963 `index: true` behaves the same way as `add_index` does. By default this means a basic `CREATE INDEX` statement. If you want something different you need to supply the `:using` option (eg. `add_index(:developers, :name, using: 'gin')`)

In your example this translates to `t.jsonb :data, index: {using: "gin"}`.

`add_index` has no logic based on the column type and I think we should keep it that way. It's very close to how the generated SQL operates.

**Comment by zw963** [comment]
Cool ! , Thanks a lot.

**Comment by zw963** [comment]
Oh, think more question about this. Thanks

1.   Why add_column not support index: true ？
2.  Any plan to support `postgres jsonb_path_ops` GIN index with somethings like
   `` index: {using: "gin_path"}``? it seem like more fast than gin, and less diskspace usage.
   I had to use like this in migrate
```ruby
CREATE INDEX index_notifications_on_data ON notifications USING gin (data jsonb_path_ops);
```
But schema.rb is not worked, it only generate default gin index jsonb_ops instead of jsonb_path_ops.

**Comment by senny** [comment]
@zw963 we use the bug tracker for bug reports and pull requests exclusively. You can ask general questions on the [rails-core mailing list](https://groups.google.com/forum/?fromgroups#!forum/rubyonrails-core). Please read our [contribution guidelines](https://github.com/rails/rails/blob/master/CONTRIBUTING.md) for further details.

**Comment by zw963** [comment]
I have to say, the problem for this issue is resolved in Rails 5 with expression index. 

for 

```SQL
CREATE INDEX index_notifications_on_data ON notifications USING gin (data jsonb_path_ops);
```

can be generate with following migration:
```rb
  add_index :notifications, 'data jsonb_path_ops', using: :gin
```
