### ISSUE TITLE
autosave: true + protect_from_forgery with: :null_session causes saving invalid record

### ISSUE THREAD

**Issue by olegantonyan** [rails/rails#21399]
Hi! I have a very strange bug.
I'm using gaffe gem (https://github.com/mirego/gaffe) to intercept all errors and display them nicely. It uses special controller for errors. But I think it's an issue with rails rather than gaffe (please, correct me I'm wrong).
So, I have `User` model and `Profile`:
``` ruby
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_one :profile, inverse_of: :user, dependent: :destroy, autosave: true

  after_create do
    create_profile name: 'hello'
  end
end
```
``` ruby
class Profile < ActiveRecord::Base
  belongs_to :user, inverse_of: :profile
  validates :name, presence: true, length: {maximum: 5}
end
```
Also I have api controller to update the profile
``` ruby
class Api::V2::ProfilesController < ApplicationController

  def update
    profile = current_user.profile
    profile.name = SecureRandom.hex
    profile.save!
  end
end
```
And my `ApplicationController` has `protect_from_forgery with: :null_session`.
When I trigger `Api::V2::ProfilesController.update` action it fails with `ActiveRecord::RecordInvalid`, then gaffe catches this error and calls its `Api::ErrorsController`. That's where interesting thing happen. 
ErrorsController is dead simple:
``` ruby
class Api::ErrorsController < ActionController::Base
  include Gaffe::Errors

  #protect_from_forgery with: :null_session

  layout false

  def show
    output = { error: "#{@rescue_response}: #{@exception.to_s}" }
    output.merge! exception: @exception.inspect, backtrace: @exception.backtrace.first(10) if Rails.env.development? || Rails.env.test?
    render json: output, status: @status_code
  end

end
```
But the key point is `protect_from_forgery with: :null_session`. Without it all is good. But, with it profile is saved even when it's invalid!
```
Started PATCH "/api/v2/my/profile" for ::1 at 2015-08-27 12:06:05 +0200
  ActiveRecord::SchemaMigration Load (0.6ms)  SELECT "schema_migrations".* FROM "schema_migrations"
Processing by Api::V2::ProfilesController#update as JSON
  Parameters: {"my"=>true, "profile"=>{}}
Can't verify CSRF token authenticity
  User Load (0.3ms)  SELECT  "users".* FROM "users" WHERE "users"."email" = ? LIMIT 1  [["email", "user@example.com"]]
   (0.1ms)  begin transaction
  SQL (0.4ms)  UPDATE "users" SET "last_sign_in_at" = ?, "current_sign_in_at" = ?, "sign_in_count" = ?, "updated_at" = ? WHERE "users"."id" = ?  [["last_sign_in_at", "2015-08-27 10:00:42.276091"], ["current_sign_in_at", "2015-08-27 10:06:05.720058"], ["sign_in_count", 23], ["updated_at", "2015-08-27 10:06:05.721133"], ["id", 1]]
   (18.6ms)  commit transaction
  Profile Load (0.4ms)  SELECT  "profiles".* FROM "profiles" WHERE "profiles"."user_id" = ? LIMIT 1  [["user_id", 1]]
   (0.1ms)  begin transaction
   (0.1ms)  rollback transaction
Completed 422 Unprocessable Entity in 67ms (ActiveRecord: 20.6ms)

ActiveRecord::RecordInvalid (Validation failed: Name is too long (maximum is 5 characters)):
  app/controllers/api/v2/profiles_controller.rb:6:in `update'


Processing by Api::ErrorsController#show as JSON
  Parameters: {"my"=>true, "profile"=>{}, "error"=>{"profile"=>{}}}
Can't verify CSRF token authenticity
   (0.1ms)  begin transaction
  SQL (0.4ms)  UPDATE "profiles" SET "name" = ?, "updated_at" = ? WHERE "profiles"."id" = ?  [["name", "4298b19af767fc891f39c330f24013de"], ["updated_at", "2015-08-27 10:06:05.783271"], ["id", 1]]
   (18.3ms)  commit transaction
Completed 422 Unprocessable Entity in 27ms (Views: 0.9ms | ActiveRecord: 18.7ms)
```
Notice UPDATE "profiles" at the end.
Without `protect_from_forgery with: :null_session` in ErrorsController all is good:
```
Started PATCH "/api/v2/my/profile" for ::1 at 2015-08-27 12:06:18 +0200
Processing by Api::V2::ProfilesController#update as JSON
  Parameters: {"my"=>true, "profile"=>{}}
Can't verify CSRF token authenticity
  User Load (0.2ms)  SELECT  "users".* FROM "users" WHERE "users"."email" = ? LIMIT 1  [["email", "user@example.com"]]
   (0.1ms)  begin transaction
  SQL (0.3ms)  UPDATE "users" SET "last_sign_in_at" = ?, "current_sign_in_at" = ?, "sign_in_count" = ?, "updated_at" = ? WHERE "users"."id" = ?  [["last_sign_in_at", "2015-08-27 10:06:05.720058"], ["current_sign_in_at", "2015-08-27 10:06:18.609242"], ["sign_in_count", 24], ["updated_at", "2015-08-27 10:06:18.610201"], ["id", 1]]
   (30.0ms)  commit transaction
  Profile Load (0.3ms)  SELECT  "profiles".* FROM "profiles" WHERE "profiles"."user_id" = ? LIMIT 1  [["user_id", 1]]
   (0.2ms)  begin transaction
   (0.1ms)  rollback transaction
Completed 422 Unprocessable Entity in 53ms (ActiveRecord: 31.8ms)

ActiveRecord::RecordInvalid (Validation failed: Name is too long (maximum is 5 characters)):
  app/controllers/api/v2/profiles_controller.rb:6:in `update'


Processing by Api::ErrorsController#show as JSON
  Parameters: {"my"=>true, "profile"=>{}, "error"=>{"profile"=>{}}}
Completed 422 Unprocessable Entity in 1ms (Views: 0.5ms | ActiveRecord: 0.0ms)
```

Here is call stack from `before_save` in `Profile` https://gist.github.com/olegantonyan/e68999d7c8f6d8f007ba

Test app: https://github.com/olegantonyan/rails_failed_validations_example
Run db:seed and use test.sh (wrapper for curl) to make a request

**Comment by atul-shimpi** [comment]
Hello,
My Test Results : Working as expected
   Environment : Ubuntu 12.04.4 LTS
   Ruby : ruby-2.2.2 [ x86_64 ] (using RVM)
   Rails : Rails 4.2.4
   Environment : Development/Test

Can you check the value of update_at in profiles table to see if its really getting updated.

With : protect_from_forgery with: :null_session
-------------------------------------------------------------------------------
User Load (0.3ms)  SELECT  "users".* FROM "users" WHERE "users"."email" = ? LIMIT 1  [["email", "user@example.com"]]
   (0.1ms)  begin transaction
  SQL (0.5ms)  UPDATE "users" SET "last_sign_in_at" = ?, "current_sign_in_at" = ?, "sign_in_count" = ?, "updated_at" = ? WHERE "users"."id" = ?  [["last_sign_in_at", "2015-08-31 02:01:29.360765"], ["current_sign_in_at", "2015-08-31 02:06:28.670959"], ["sign_in_count", 13], ["updated_at", "2015-08-31 02:06:28.672554"], ["id", 1]]
   (214.2ms)  commit transaction
  Profile Load (0.3ms)  SELECT  "profiles".* FROM "profiles" WHERE "profiles"."user_id" = ? LIMIT 1  [["user_id", 1]]
   (0.1ms)  begin transaction
   (0.1ms)  rollback transaction
Completed 422 Unprocessable Entity in 291ms (ActiveRecord: 216.6ms)

ActiveRecord::RecordInvalid (Validation failed: Name is too long (maximum is 5 characters)):
  app/controllers/api/v2/profiles_controller.rb:6:in `update'


Processing by Api::ErrorsController#show as JSON
  Parameters: {"my"=>true, "profile"=>{}, "error"=>{"profile"=>{}}}
Completed 422 Unprocessable Entity in 2ms (Views: 1.3ms | ActiveRecord: 0.0ms)

Without : protect_from_forgery with: :null_session
---------------------------------------------------------------------------------------------
Parameters: {"my"=>true, "profile"=>{}}
  User Load (0.4ms)  SELECT  "users".* FROM "users" WHERE "users"."email" = ? LIMIT 1  [["email", "user@example.com"]]
   (0.2ms)  begin transaction
  SQL (0.5ms)  UPDATE "users" SET "last_sign_in_at" = ?, "current_sign_in_at" = ?, "sign_in_count" = ?, "updated_at" = ? WHERE "users"."id" = ?  [["last_sign_in_at", "2015-08-31 01:55:34.605078"], ["current_sign_in_at", "2015-08-31 02:01:29.360765"], ["sign_in_count", 12], ["updated_at", "2015-08-31 02:01:29.362467"], ["id", 1]]
   (267.0ms)  commit transaction
  Profile Load (0.5ms)  SELECT  "profiles".* FROM "profiles" WHERE "profiles"."user_id" = ? LIMIT 1  [["user_id", 1]]
   (0.2ms)  begin transaction
   (0.1ms)  rollback transaction
Completed 422 Unprocessable Entity in 387ms (ActiveRecord: 269.7ms)
========================================================================

**Comment by olegantonyan** [comment]
This is strange. It's really getting updated. I found this in real production app and then isolated here. Just tried on another machine (openSUSE 13.2 x86-64, ruby 2.2.3, rails 4.2.4) - same problem.
@atul-shimpi maybe you've tried with `protect_from_forgery with: :null_session` in `ApplicationController`? The problem is not there, but in `Api::ErrorsController`

**Comment by nateberkopec** [comment]
The provided reproduction application does reproduce the issue for me.

**Comment by maclover7** [comment]
Can you create an executable test script using one of the templates [here](https://github.com/rails/rails/tree/master/guides/bug_report_templates)?

**Comment by olegantonyan** [comment]
Cannot reproduce it with test script.

**Comment by maclover7** [comment]
On Rails master, and on 4-2-stable, I am unable to reproduce the error you are seeing. By commenting and uncommenting the `protect_from_forgery with: :null_session`, this is not causing an visible changes to the tests. I think this is a third part issue with gaffe. Test script I am using can be found [here](https://gist.github.com/maclover7/d1944d33bcd6ef199094)
