### ISSUE TITLE
Support for logging nested exceptions

### ISSUE THREAD

**Issue by tonywok** [rails/rails#21404]
Rails doesn't seem to have support for logging nested exceptions. As you may know, a feature was added to ruby in version 2.1 to aid in supporting this. You can read about it here: http://devblog.avdi.org/2013/12/25/exception-causes-in-ruby-2-1/

At work, we use a tool called sentry to report errors in staging and production. Their client gem has support for unraveling nested exceptions. You can see how they achieve that here: https://github.com/getsentry/raven-ruby/blob/3f890829973dba6be542c16d6b5357be38215c5d/lib/raven/event.rb#L168.

_Note: I'm aware that rails likely needs to support versions of ruby that don't yet have this feature, but the above code handles that case with a simple check to see if the exception `responds_to?(:cause)`._

I've become quite fond of this feature, as it gives more context when debugging exceptions. However, it's not available to me in development without actually sending the exception event to a third party. While that is an option, albeit not a very good one, ideally rails could just log the exception (including any nested `cause`s) in the development log.

I was poking around in the action dispatch middleware, and it seems like https://github.com/rails/rails/blob/master/actionpack/lib/action_dispatch/middleware/debug_exceptions.rb#L110 could be a good place to start.

Is there any interest in supporting this? I'd be happy to take a stab at it, but would like to avoid wasting my effort if it is explicitly not supported for a reason I am not aware of.

Thanks for your time :)

**Comment by kaspth** [comment]
We don't accept feature requests on the issue tracker, as we reserve this for bugs only. Please email the rails-core mailing list.

In this case I think you wouldn't be wasting your time, as I can't see what strong opposition there would be about this. Especially as Rails 5 supports Ruby 2.2+ we wouldn't even need any conditions :grin:

Thanks

**Comment by tonywok** [comment]
@kaspth Gotcha, thanks for the response and apologies. I read the contributing guide and must have missed that bit - will direct feature requests to mailing list going forward.
