### ISSUE TITLE
[3.2.22] Self-join associations return wrong results for new records

### ISSUE THREAD

**Issue by radiohead** [rails/rails#21419]
I am not sure if this is a bug or just something that should be documented.

Consider the following scenario:

```ruby
class Node < ActiveRecord::Base
  has_many :linked_nodes, foreign_key: :created_from_node_id, dependent: :destroy
end
```

And if I create a new `Node` which is not persisted yet and will try to access the association:

```ruby
node = Node.new
node.linked_nodes
```

That will result in the following SQL query:

```sql
SELECT * FROM `nodes` WHERE created_from_node_id = NULL
```

that will (probably) return some `Nodes`

This issue is easily solved by asking if we're dealing with `new_record?` but I wonder whether this is an expected behavior.

**Comment by rafaelfranca** [comment]
Thank you so much for the issue but Rails 3 is no supported anymore. Does it happen on Rails 4.2?

**Comment by zerothabhishek** [comment]
It doesn't happen on Rails 4.2. When we do node.linked_node, we get this -

    SELECT nodes.* FROM nodes WHERE nodes.created_from_node_id = NULL AND (1=0)

And it actually adds the **(1=0)** part by checking for `new_record` (and a few other things).
