### ISSUE TITLE
Singular of focus

### ISSUE THREAD

**Issue by BenZhang** [rails/rails#21425]
Hi,

Just found out pretty wired singularize and pluralize result for focus. Actually English is my second language. I have look up the dictionary. the plural of focus is focuses or foci. I am wondering whether is it an exception of Rails' Inflector.

```ruby
   'focus'.singularize # => "focu"
   'focus'.pluralize # => "focus"
```

Thanks

**Comment by matthewd** [comment]
Thanks for the report, but [the inflector is frozen](https://github.com/rails/rails/blob/74c7246238960d82bbba450b1888ae2790e688d2/activesupport/lib/active_support/inflector/methods.rb#L11-L15).

You can add exceptions in [`config/initializers/inflections.rb`](http://api.rubyonrails.org/classes/ActiveSupport/Inflector/Inflections.html).

**Comment by kaspth** [comment]
Thanks, but the inflector is locked down to prevent apps from silently breaking. You'll have to add your own inflection config.
