### ISSUE TITLE
Rails master is un-Bundleable

### ISSUE THREAD

**Issue by maclover7** [rails/rails#21422]
When trying to listing Rails master in my Gemfile (`gem "rails", github: "rails/rails"`), Bundler cannot resolve Rails' dependencies due to that ActionPack relies on the unreleased Rack 2.0. This is the [trouble line](https://github.com/rails/rails/blob/master/actionpack/actionpack.gemspec#L24). 

Here's the backtrace:

```
Updating git://github.com/rails/rails.git
Fetching gem metadata from https://rubygems.org/.......
Fetching version metadata from https://rubygems.org/..
Fetching dependency metadata from https://rubygems.org/..
Resolving dependencies.....
Bundler could not find compatible versions for gem "rack":
  In Gemfile:
    rails (>= 0) ruby depends on
      actionpack (= 5.0.0.alpha) ruby depends on
        rack (~> 2.x) ruby
Could not find gem 'rack (~> 2.x) ruby', which is required by gem 'actionpack (= 5.0.0.alpha) ruby', in any of the sources.
```

Can we revert [this commit](https://github.com/rails/rails/commit/51211a94bd7a34d80f2412a7f94fefe7366647a5) for the time being, and go back to depending on Rack `~> 1.6`?

cc @tenderlove

**Comment by tenderlove** [comment]
We can't just revert that change.  Rails master depends on changes that were made in Rack master.  Rack master is not backwards compatible with 1.6, so I don't feel comfortable changing the version in Rack either.

**Comment by maclover7** [comment]
Do you know when Rack 2.0 is being released? I'm just concerned that people trying to test their apps (like I am) on master, aren't able to bundle install.

**Comment by rafaelfranca** [comment]
To get an application running against Rails master you need to declare all the dependencies on your Gemfile. There is a generator for that in the Rails repository.

```
git clone git@github.com:/rails/rails.git
cd rails
./railties/exe/rails new --edge my_edge_app
```

This is the only supported way to test their applications on master.

**Comment by maclover7** [comment]
:+1: ok. Is this documented in the guides anywhere? Didn't see it in http://guides.rubyonrails.org/upgrading_ruby_on_rails.html

**Comment by rafaelfranca** [comment]
Upgrading guide is only for released gems, when Rails master is done you don't need to worry about this, it will be smooth as changing the version on the Gemfile. This "testing edge Rails" workflow is not documented thought, only in the `rails new` output.

**Comment by maclover7** [comment]
:+1: ok

**Comment by schneems** [comment]
You can see what code we generate when you  `rails new` here: https://github.com/rails/rails/blob/d12daa4b3370447e55710cadf7579d1b96cdfcad/railties/lib/rails/generators/app_base.rb#L219-L224

**Comment by chrisbloom7** [comment]
There's really no reason to do so if you can get the same results by just cloning the main repo, but in case you're wondering about another way to do it, here's short how-to

http://www.christopherbloom.com/2015/04/26/setting-up-a-rails-5-app-from-edge/

**Comment by pramodshinde** [comment]
Getting following error after `./railties/exe/rails new --edge my_edge_app`
```
/home/pramod/.rvm/rubies/ruby-2.2.2/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require': cannot load such file -- thor/group (LoadError)
	from /home/pramod/.rvm/rubies/ruby-2.2.2/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /home/pramod/open_source/rails/railties/lib/rails/generators.rb:4:in `<top (required)>'
	from /home/pramod/.rvm/rubies/ruby-2.2.2/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /home/pramod/.rvm/rubies/ruby-2.2.2/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /home/pramod/open_source/rails/railties/lib/rails/commands/application.rb:1:in `<top (required)>'
	from /home/pramod/.rvm/rubies/ruby-2.2.2/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /home/pramod/.rvm/rubies/ruby-2.2.2/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /home/pramod/open_source/rails/railties/lib/rails/cli.rb:14:in `<top (required)>'
	from /home/pramod/.rvm/rubies/ruby-2.2.2/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /home/pramod/.rvm/rubies/ruby-2.2.2/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from ./railties/exe/rails:9:in `<main>'
```
Firstly I was getting 
```
Could not find gem 'rack (~> 2.x) ruby', which is required by gem 'rails (>= 0) ruby', in any of the sources.
````
Then I tried : `./railties/exe/rails new --edge my_edge_app`, got following
```
Rails 5 requires Ruby 2.2.2 or newer.

    You're running
      ruby 2.2.1p85 (2015-02-26 revision 49769) [x86_64-linux]

    Please upgrade to Ruby 2.2.2 or newer to continue
```
I installed ruby `rvm install ruby-2.2.2 && rvm use ruby-2.2.2`, then  executed 
`./railties/exe/rails new --edge my_edge_app` and received above error `cannot load such file -- thor/group (LoadError)`

**Comment by jeremy** [comment]
@pramodshinde Run `bundle install` before `./railties/exe/rails new --edge my_edge_app`.
