### ISSUE TITLE
Enum _prefix and _suffix options raise NoMethodError: undefined method `each_with_index'

### ISSUE THREAD

**Issue by sethdeckard** [rails/rails#21439]
1. Create a model with an integer column 'status'
2. Add an enum declaration per the docs using _prefix: 

`enum status: [:active, :inactive], _prefix: :comments`
or 
`enum status: [:active, :archived], _suffix: true`

Running a test or in the console produces the following:

NoMethodError: undefined method `each_with_index' for :comments:Symbol
	from /Users/seth/.rvm/gems/ruby-2.2.2/gems/activerecord-4.2.4/lib/active_record/enum.rb:117:in `block (2 levels) in enum'
	from /Users/seth/.rvm/gems/ruby-2.2.2/gems/activerecord-4.2.4/lib/active_record/enum.rb:93:in `module_eval'
	from /Users/seth/.rvm/gems/ruby-2.2.2/gems/activerecord-4.2.4/lib/active_record/enum.rb:93:in `block in enum'
	from /Users/seth/.rvm/gems/ruby-2.2.2/gems/activerecord-4.2.4/lib/active_record/enum.rb:84:in `each'

When using the `true` option the error looks like this:
NoMethodError: undefined method `each_with_index' for true:TrueClass
	from /Users/seth/.rvm/gems/ruby-2.2.2/gems/activerecord-4.2.3/lib/active_record/enum.rb:117:in `block (2 levels) in enum'
	from /Users/seth/.rvm/gems/ruby-2.2.2/gems/activerecord-4.2.3/lib/active_record/enum.rb:93:in `module_eval'
	from /Users/seth/.rvm/gems/ruby-2.2.2/gems/activerecord-4.2.3/lib/active_record/enum.rb:93:in `block in enum'
	from /Users/seth/.rvm/gems/ruby-2.2.2/gems/activerecord-4.2.3/lib/active_record/enum.rb:84:in `each'
	from /Users/seth/.rvm/gems/ruby-2.2.2/gems/activerecord-4.2.3/lib/active_record/enum.rb:84:in `enum'

Maybe I'm just doing something wrong but I tried in a brand new project as well and ran into the same issue.

Occurs in 4.2.3 and 4.2.4

**Comment by matthewd** [comment]
Are you looking at the edge docs? I see no mention of `_prefix` in http://api.rubyonrails.org/v4.2.4/classes/ActiveRecord/Enum.html. (Which sounds right.. I believe it was added fairly recently.)

**Comment by kaspth** [comment]
Prefix and suffix are only on master as far as I'm aware. Check the Active Record changelog: https://github.com/rails/rails/blob/master/activerecord/CHANGELOG.md

**Comment by sethdeckard** [comment]
Ah I was looking at the edge docs, sorry about that, I didn't realize it was a new change.

**Comment by kaka-ruto** [comment]
I am facing the same same issue in Rails 4.2.10
