### ISSUE TITLE
Rails decorator auto-loading sequence strange behavior in namespace

### ISSUE THREAD

**Issue by schwannden** [rails/rails#21437]
In rails 4.2.3
When starting the WEBrick server in development mode, the decorator is loaded after the controller when controller is in a namespace (say Admin::ToursController).
Therefore, the very first call (after the server starts up) to decorator results in this error
`Unable to autoload constant Admin::ToursDecorator, expected some_path to define it`
(notice some_path does contain the required file defining the decorator)
Subsequent references to decorator will be successful because decorator is already loaded after the first failed controller method call.

Example, for the following file structure:
```
app
|--controllers--admin--tours_controller.rb (class Admin::ToursController < ApplicationsController)
|--decorators--admin--tours_decorator.rb(class ToursDecorator < ApplicationsController)
```

If `ToursController` references `ToursDecorator` for the first time after the server starts up, the following error is shown:
`Unable to autoload constant Admin::ToursDecorator, expected /project_path/app/decorators/admin/tours_decorator.rb` to define it

Subsequent usage of the decorate is successful. Why?

Manually adding
`require Rails.root.join('app/decorators/admin/tours_decorator.rb')` inside of `app/controller/admin/tours_controller` solves the problem
Defining the decorator as `Admin::ToursDecorator` also behaves as expected.

**Comment by fxn** [comment]
Are the class definitions using constant paths with colons as in

```ruby
class Admin::ToursController
  # ...
end
```

?

**Comment by schwannden** [comment]
Yes it does

**Comment by fxn** [comment]
Try defining them with a nesting that reflects the namespace:

```ruby
module Admin
  class ToursController
    # ...
  end
end
```

See http://guides.rubyonrails.org/autoloading_and_reloading_constants.html#nesting-and-qualified-constants for an explanation.

**Comment by fxn** [comment]
Ah! I see it in the issue description now, didn't catch the mismatch before.

Constant names have to match the directory structure. In order to be autoloadable, the class `Admin::ToursDecorator` has to live in a file *admin/tours_decorator.rb* below some of the directories in `config.autoload_paths` (all directories below *app* belong to them, in this case *app/decorators*).

That's also explained in that guide.
