### ISSUE TITLE
Application throwing error with the combination of Ruby-2.2.2 and Rails-4.1.6 not able to run any commands

### ISSUE THREAD

**Issue by kishore-mohan** [rails/rails#21445]
Looks like application breaking with the combination Ruby-2.2.2 and Rails 4.1.6 . While trying to start the application or running any rails generate throwing error.

Application pushed into [rails_error](https://github.com/kishore-mohan/rails_error), feel free to clone the application go ahead and run bundle install and try to run the application.

Its just a new stack application without any new feature.

## Error Backtrace for rails g migration: 
.rvm/gems/ruby-2.2.2/gems/activerecord-4.1.6/lib/active_record/dynamic_matchers.rb:26:in `method_missing': undefined method `raise_in_transactional_callbacks=' for #<Class:0x007f959a74ca20> (NoMethodError)
	from /Users/kishorem/.rvm/gems/ruby-2.2.2/gems/activerecord-4.1.6/lib/active_record/railtie.rb:110:in `block (3 levels) in <class:Railtie>'
	from /Users/kishorem/.rvm/gems/ruby-2.2.2/gems/activerecord-4.1.6/lib/active_record/railtie.rb:109:in `each'
	from /Users/kishorem/.rvm/gems/ruby-2.2.2/gems/activerecord-4.1.6/lib/active_record/railtie.rb:109:in `block (2 levels) in <class:Railtie>'
	from /Users/kishorem/.rvm/gems/ruby-2.2.2/gems/activesupport-4.1.6/lib/active_support/lazy_load_hooks.rb:38:in `instance_eval'
	from /Users/kishorem/.rvm/gems/ruby-2.2.2/gems/activesupport-4.1.6/lib/active_support/lazy_load_hooks.rb:38:in `execute_hook'
	from /Users/kishorem/.rvm/gems/ruby-2.2.2/gems/activesupport-4.1.6/lib/active_support/lazy_load_hooks.rb:45:in `block in run_load_hooks'
	from /Users/kishorem/.rvm/gems/ruby-2.2.2/gems/activesupport-4.1.6/lib/active_support/lazy_load_hooks.rb:44:in `each'
	from /Users/kishorem/.rvm/gems/ruby-2.2.2/gems/activesupport-4.1.6/lib/active_support/lazy_load_hooks.rb:44:in `run_load_hooks'
	from /Users/kishorem/.rvm/gems/ruby-2.2.2/gems/activerecord-4.1.6/lib/active_record/base.rb:326:in `<module:ActiveRecord>'
	from /Users/kishorem/.rvm/gems/ruby-2.2.2/gems/activerecord-4.1.6/lib/active_record/base.rb:23:in `<top (required)>'
	from /Users/kishorem/.rvm/gems/ruby-2.2.2/gems/activerecord-4.1.6/lib/active_record/migration.rb:711:in `next_migration_number'
	from /Users/kishorem/.rvm/gems/ruby-2.2.2/gems/activerecord-4.1.6/lib/active_record/migration.rb:406:in `method_missing'
	from /Users/kishorem/.rvm/gems/ruby-2.2.2/gems/activerecord-4.1.6/lib/rails/generators/active_record/migration.rb:13:in `next_migration_number'
	from /Users/kishorem/.rvm/gems/ruby-2.2.2/gems/railties-4.1.6/lib/rails/generators/migration.rb:41:in `set_migration_assigns!'
	from /Users/kishorem/.rvm/gems/ruby-2.2.2/gems/railties-4.1.6/lib/rails/generators/migration.rb:57:in `migration_template'
	from /Users/kishorem/.rvm/gems/ruby-2.2.2/gems/activerecord-4.1.6/lib/rails/generators/active_record/migration/migration_generator.rb:11:in `create_migration_file'
	from /Users/kishorem/.rvm/gems/ruby-2.2.2/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
	from /Users/kishorem/.rvm/gems/ruby-2.2.2/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
	from /Users/kishorem/.rvm/gems/ruby-2.2.2/gems/thor-0.19.1/lib/thor/invocation.rb:133:in `block in invoke_all'
	from /Users/kishorem/.rvm/gems/ruby-2.2.2/gems/thor-0.19.1/lib/thor/invocation.rb:133:in `each'
	from /Users/kishorem/.rvm/gems/ruby-2.2.2/gems/thor-0.19.1/lib/thor/invocation.rb:133:in `map'
	from /Users/kishorem/.rvm/gems/ruby-2.2.2/gems/thor-0.19.1/lib/thor/invocation.rb:133:in `invoke_all'
	from /Users/kishorem/.rvm/gems/ruby-2.2.2/gems/thor-0.19.1/lib/thor/group.rb:232:in `dispatch'
	from /Users/kishorem/.rvm/gems/ruby-2.2.2/gems/thor-0.19.1/lib/thor/invocation.rb:115:in `invoke'
	from /Users/kishorem/.rvm/gems/ruby-2.2.2/gems/thor-0.19.1/lib/thor/group.rb:277:in `block in _invoke_for_class_method'
	from /Users/kishorem/.rvm/gems/ruby-2.2.2/gems/thor-0.19.1/lib/thor/shell.rb:68:in `with_padding'
	from /Users/kishorem/.rvm/gems/ruby-2.2.2/gems/thor-0.19.1/lib/thor/group.rb:266:in `_invoke_for_class_method'
	from /Users/kishorem/.rvm/gems/ruby-2.2.2/gems/thor-0.19.1/lib/thor/group.rb:133:in `_invoke_from_option_orm'
	from /Users/kishorem/.rvm/gems/ruby-2.2.2/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
	from /Users/kishorem/.rvm/gems/ruby-2.2.2/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
	from /Users/kishorem/.rvm/gems/ruby-2.2.2/gems/thor-0.19.1/lib/thor/invocation.rb:133:in `block in invoke_all'
	from /Users/kishorem/.rvm/gems/ruby-2.2.2/gems/thor-0.19.1/lib/thor/invocation.rb:133:in `each'
	from /Users/kishorem/.rvm/gems/ruby-2.2.2/gems/thor-0.19.1/lib/thor/invocation.rb:133:in `map'
	from /Users/kishorem/.rvm/gems/ruby-2.2.2/gems/thor-0.19.1/lib/thor/invocation.rb:133:in `invoke_all'
	from /Users/kishorem/.rvm/gems/ruby-2.2.2/gems/thor-0.19.1/lib/thor/group.rb:232:in `dispatch'
	from /Users/kishorem/.rvm/gems/ruby-2.2.2/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
	from /Users/kishorem/.rvm/gems/ruby-2.2.2/gems/railties-4.1.6/lib/rails/generators.rb:157:in `invoke'
	from /Users/kishorem/.rvm/gems/ruby-2.2.2/gems/railties-4.1.6/lib/rails/commands/generate.rb:11:in `<top (required)>'
	from /Users/kishorem/.rvm/gems/ruby-2.2.2/gems/activesupport-4.1.6/lib/active_support/dependencies.rb:247:in `require'
	from /Users/kishorem/.rvm/gems/ruby-2.2.2/gems/activesupport-4.1.6/lib/active_support/dependencies.rb:247:in `block in require'
	from /Users/kishorem/.rvm/gems/ruby-2.2.2/gems/activesupport-4.1.6/lib/active_support/dependencies.rb:232:in `load_dependency'
	from /Users/kishorem/.rvm/gems/ruby-2.2.2/gems/activesupport-4.1.6/lib/active_support/dependencies.rb:247:in `require'
	from /Users/kishorem/.rvm/gems/ruby-2.2.2/gems/railties-4.1.6/lib/rails/commands/commands_tasks.rb:135:in `generate_or_destroy'
	from /Users/kishorem/.rvm/gems/ruby-2.2.2/gems/railties-4.1.6/lib/rails/commands/commands_tasks.rb:51:in `generate'
	from /Users/kishorem/.rvm/gems/ruby-2.2.2/gems/railties-4.1.6/lib/rails/commands/commands_tasks.rb:40:in `run_command!'
	from /Users/kishorem/.rvm/gems/ruby-2.2.2/gems/railties-4.1.6/lib/rails/commands.rb:17:in `<top (required)>'
	from bin/rails:4:in `require'
	from bin/rails:4:in `<main>'

**Comment by al2o3cr** [comment]
Not sure how you got into this state, but it appears the `config/application.rb` in your project was generated with Rails 4.2.x - the config value that's blowing up was added in https://github.com/rails/rails/commit/b11b1e868a89319b8523c5f7b0da4c130ee42992 which first shipped in 4.2.0.

**Comment by kishore-mohan** [comment]
thanks @al2o3cr for the help.. understand this issue from [stackoverflow](http://stackoverflow.com/questions/28006358/undefined-method-raise-in-transactional-callbacks-for-activerecordbaseclass). 

Looking how it can be handled better without affecting other rails versions. Is the config can be moved in other level?

**Comment by rafaelfranca** [comment]
You can check if the config exists before using it.

**Comment by al2o3cr** [comment]
@kishore-mohan The ultimate cause here is that a config file intended for a Rails 4.2+ application was generated in an app using 4.1. If you can reproduce this behavior reliably, please open another issue - if the Rails 4.2 generators created the file, they *should* have also set the Gemfile to Rails 4.2...
