### ISSUE TITLE
Dangerous DATABASE_URL / database.yml default

### ISSUE THREAD

**Issue by frankpinto** [rails/rails#21441]
Rails version: 4.2.4

As a result of the current way Rails handles config/database.yml + DATABASE_URL I ended up dropping two production tables when I ran a test on a model w/ RAILS_ENV=test on my local machine.

**What happened**
On a new Rails install for an existing infrastructure I'm creating a simple CRUD interface for companies. My config/database.yml, when the undesired behavior happened, looked like the following:

```yaml
test:
  <<: *default
  database: ayalo_test
  username: postgres

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
```

I had DATABASE_URL set to my production database. I ran `RAILS_ENV=test bin/rake test test/models/company_test.rb` and that dropped my production tables when filling them with fixture data.

As stated in the [docs](http://guides.rubyonrails.org/configuring.html#connection-preference) this is expected behavior; however, it doesn't mention it in the comments of config/database.yml and the comments there make it sound as if the only way it will used is if you explicitly use it:

```ruby
# On Heroku and other platform providers, you may have a full connection URL
# available as an environment variable. For example:
#
#   DATABASE_URL="postgres://myuser:mypass@localhost/somedatabase"
#
# You can use this database configuration with:
#
#   production:
#     url: <%= ENV['DATABASE_URL'] %>
```

**Proposed Solutions**

1. Allow a `url: nil` value so that you can overwrite the DATABASE_URL environment variable in dev / test if you want to
2. Put in the comments of config/database.yml that if DATABASE_URL is defined in your environment it will likely take precedence over any configuration set in that file
3. Don't implicitly use it. Use it if it appears in config/database.yml

**Comment by frankpinto** [comment]
As per your request @roolo, here's the issue

**Comment by rafaelfranca** [comment]
Thank you for the issue. It is not related if you are using DATABASE_URL in the config file or not, it is related to how DATABASE_URL works. It override the behavior of `config/database.yml` entirely. We are aware of it and we are fixing at https://github.com/rails/rails/pull/21237.

I'm closing this issue in favor of that PR.

**Comment by frankpinto** [comment]
Thanks for the quick response @rafaelfranca, glad to see it'll be better soon :)

**Comment by roolo** [comment]
Ty @frankpinto for letting me know about it
