### ISSUE TITLE
Replace use of IPAddr in poostgres adapter with a better implementation

### ISSUE THREAD

**Issue by gucki** [rails/rails#21448]
The postgresql adapter of AR is using IPAddr for columns of type inet/ cidr. IPAddr sucks in various ways, for example not giving direct access to the netmask. Just look at the current hacks in the ar postgresql adapter having to use instance_variable_get. https://github.com/rails/rails/blob/f17fa8ef6f2abffeea5398cc450172c0975cad27/activerecord/lib/active_record/connection_adapters/postgresql/oid/cidr.rb#L10

It also fails to deal correctly with host addresses, so for example IPAddr.new("192.168.1.1/24") results in #<IPAddr: IPv4:192.168.1.0/255.255.255.0>. Using a money-patch in this case is unavoidable.

It should be replaced with a better implementation like the one in the IPAddress gem.

    module ActiveRecord
      module ConnectionAdapters
        module PostgreSQL
          module OID
            class Cidr
              def type
                :cidr
              end

              def type_cast_for_schema(value)
                value.to_string
              end

              def type_cast_for_database(value)
                (IPAddress === value) ? value.to_string : value
              end

              def cast_value(value)
                if value.nil?
                  nil
                elsif String === value
                  begin
                    IPAddress.parse(value)
                  rescue ArgumentError
                    nil
                  end
                else
                  value
                end
              end
            end
          end
        end
      end
    end

**Comment by rafaelfranca** [comment]
Thank you so much for the issue but we don't take feature request on the issue tracker. We recommend you to try to implement the feature and send us a pull request or if you are in doubt if the feature will be accepts ask in Rails Core mailing list for feedback.

About this specific issue, :+1: for improving the implementation.
