### ISSUE TITLE
"reload" method of "active record" clears the dirty flag set in after_find callback

### ISSUE THREAD

**Issue by ypxing** [rails/rails#21442]
As titled, any dirty flag would be cleared set in after_find callback. So the change made in after_find cannot be saved later.

######################
Example to show this.
```
class User < ActiveRecord::Base
  after_find do
    self.name = 'new name'
  end
end

Loading development environment (Rails 4.2.4)
irb(main):001:0> user = User.first
  User Load (0.2ms)  SELECT  "users".* FROM "users"  ORDER BY "users"."id" ASC LIMIT 1
=> #<User id: 1, created_at: "2015-09-01 06:11:29", updated_at: "2015-09-01 06:11:29", name: "new name">
irb(main):002:0> user.name_changed?
=> true
irb(main):003:0> user.reload
  User Load (0.1ms)  SELECT  "users".* FROM "users" WHERE "users"."id" = ? LIMIT 1  [["id", 1]]
=> #<User id: 1, created_at: "2015-09-01 06:11:29", updated_at: "2015-09-01 06:11:29", name: "new name">
irb(main):004:0> user.name_changed?
=> false
irb(main):005:0> user.save
   (0.2ms)  begin transaction
   (0.3ms)  commit transaction
=> true
```

######################
Related rails source code
activerecord-4.2.4/lib/active_record/persistence.rb
```
    def reload(options = nil)
      clear_aggregation_cache
      clear_association_cache
      self.class.connection.clear_query_cache

      fresh_object =
        if options && options[:lock]
          self.class.unscoped { self.class.lock(options[:lock]).find(id) }
        else
          self.class.unscoped { self.class.find(id) }
        end

      @attributes = fresh_object.instance_variable_get('@attributes')
      @new_record = false
      self
    end
```

active_record/attribute_methods/dirty.rb
```
      def reload(*)
        super.tap do
          clear_changes_information ####
        end
      end
```

**Comment by rafaelfranca** [comment]
Yes, it is the desired behavior. `reload` will get the record from the database and so drop any change you did in the object.

**Comment by ypxing** [comment]
It just dropped the "flag" and did NOT drop the change.
user.name has been changed to "new name". But the "change flag" is false.
It seems not desired.

**Comment by rafaelfranca** [comment]
I see now. The change is still there only not in the changes hash because we clear after we find. Yeah it is no desired.

**Comment by ronakjangir47** [comment]
@rafaelfranca I would like to investigate and fix this issue.

**Comment by meinac** [comment]
This is bug is not about `reload`. If you register an `after_save` callback which changes an attribute of the instance `changed?` still returns `false` after save.
```ruby
class Foo < ActiveRecord::Base
  after_save do
    self.attribute = 'Changed'
  end
end

f = Foo.create(attribute: 'Bar')
f.changed? # => false
f.attribute # => 'Changed'
```
This bug is about callbacks.

**Comment by ypxing** [comment]
@meinac the callbacks are fine.

It's all about the "change flags" have been cleared unconditionally for "dirty handling" after querying/persisting data.

For the "after_save" case, the related rails source code is as follows.

active_record/attribute_methods/dirty.rb
```
      # Attempts to +save+ the record and clears changed attributes if successful.
      def save(*)
        if status = super
           changes_applied
        end
        status
      end
```

**change_applied** (of ative_model version) will reset **@changed_attributes**

```
      # Removes current changes and makes them accessible through +previous_changes+.
      def changes_applied # :doc:
        @previously_changed = changes
        @changed_attributes = ActiveSupport::HashWithIndifferentAccess.new
      end
```

That's why you can see "f.changed? # => false"

**Comment by al2o3cr** [comment]
@ypxing Stepping back a bit, what's the use case for modifying a record in `after_save`? It breaks an (expected) invariant of the `save` method, namely that the record afterwards should reflect the underlying database state.

**Comment by rxinginfo** [comment]
@al2o3cr The issue is about **after_find** NOT after_save. After finding one AR instance, you may want to set its fields once some other conditions are met.

**Comment by rxinginfo** [comment]
The issue is about **after_find** NOT after_save. After finding one AR instance, you may want to set its fields once some other conditions are met.

**Comment by sgrif** [comment]
@rxinginfo Can you confirm that's still a problem on master? That shouldn't happen w/ the new implementation.

**Comment by akshay-vishnoi** [comment]
@sgrif - I tried with master and the behaviour is as following:

```ruby
# user.rb
class User  < ActiveRecord::Base
  after_find do
    self.name = 'new name'
  end
end

# Console
Loading development environment (Rails 5.0.0.alpha)
2.2.2 :001 > u = User.first
  User Load (0.9ms)  SELECT  "users".* FROM "users" ORDER BY "users"."id" ASC LIMIT 1
 => #<User id: 1, name: "new name", created_at: "2015-10-06 04:48:24", updated_at: "2015-10-06 04:48:24"> 
2.2.2 :002 > u.changed?
 => true 
2.2.2 :003 > u.changes
 => {"name"=>["Akshay", "new name"]} 
2.2.2 :004 > u.reload
  User Load (0.4ms)  SELECT  "users".* FROM "users" WHERE "users"."id" = $1 LIMIT 1  [["id", 1]]
 => #<User id: 1, name: "new name", created_at: "2015-10-06 04:48:24", updated_at: "2015-10-06 04:48:24"> 
2.2.2 :005 > u.changed?
 => true 
2.2.2 :006 > u.changes
 => {"name"=>["Akshay", "new name"]}
```

After reload it keeps the changes.

**Comment by ypxing** [comment]
@sgrif the issue has gone in master branch.

**Comment by sgrif** [comment]
Looks like the current behavior is correct. Thanks for verifying.
