### ISSUE TITLE
What do you think of a way of automatically handle crud actions?

### ISSUE THREAD

**Issue by NullVoxPopuli** [rails/rails#21440]
I find boilerplate crud actions kinda tedious, so I wrote this gem:
 https://github.com/NullVoxPopuli/lazy_crud

Currently, the way lazy_crud is used, is to include it in a controller.

```ruby
class ItemController < ApplicationController
  include LazyCrud
end
```

that will allow all CRUD operations, for html and json requests.
- putting in default views for each action would be really easy, too. (but not implemented, as I am using lazy_crud for my api app, and don't need views)

Is there a possibility that something like this could be included in rails?

**Comment by rafaelfranca** [comment]
Thank you for the request. No. In the past we had this and we removed in favor of generated scaffold. Also see https://github.com/josevalim/inherited_resources

**Comment by NullVoxPopuli** [comment]
ah ok. Thanks!

I have seen inherited_resources, but it didn't quite fit my needs. :-)
