### ISSUE TITLE
Anchor / URL hash (incorrectly?) stripped from request

### ISSUE THREAD

**Issue by bf4** [rails/rails#21458]
I have a Rails 4.2.3 app and I'm hitting `https://www.rails-server.dev/system_status/#failed` which has some navigation tabs on it.  Strangely, `request.url` wasn't returning the `#failed` anchor / url hash (I'm not sure what to call it).  I've inspected the request object and trolled through the Rails source code present and past, but am not sure where it's being removing.  There is code for **building** a url with an anchor, but none I see that removes it, though I do see [tests that imply Rails knows it's being removed](https://github.com/rails/rails/search?utf8=%E2%9C%93&q=anchor)

Now, Javascript has no trouble with this:  `window.location.hash` or via the History API. Is this intentional or a bug?

Best I can figure it's some relationship between the `ActionDispatch::Routing::RouteSet` and `url_for` but I'm not sure.  It doesn't appear to be in [Rack](https://github.com/rack/rack/blob/1-6-stable/SPEC).

My middlewares are

```ruby
use Rack::MiniProfiler
use ActionDispatch::SSL
use Rack::Sendfile
use Rack::Cors
use ActionDispatch::Static
use Rack::Lock
use Rack::Runtime
use Rack::MethodOverride
use ActionDispatch::RequestId
use RequestStore::Middleware
use Rails::Rack::Logger
use ActionDispatch::ShowExceptions
use WebConsole::Middleware
use ActionDispatch::DebugExceptions
use MetaRequest::Middlewares::Headers
use BetterErrors::Middleware
use ActionDispatch::RemoteIp
use ActionDispatch::Reloader
use ActionDispatch::Callbacks
use ActiveRecord::Migration::CheckPending
use ActiveRecord::ConnectionAdapters::ConnectionManagement
use ActiveRecord::QueryCache
use ActionDispatch::Cookies
use ActionDispatch::Session::CookieStore
use ActionDispatch::Flash
use ActionDispatch::ParamsParser
use Remotipart::Middleware
use Rack::Head
use Rack::ConditionalGet
use Rack::ETag
use Warden::Manager
use MetaRequest::Middlewares::MetaRequestHandler
use MetaRequest::Middlewares::AppRequestHandler
use Rack::Pjax
run RailsApp::Application.routes
```

**Comment by al2o3cr** [comment]
This is expected behavior - user agents do not send fragments when making an HTTP request.

**Comment by bf4** [comment]
So only in javascript, huh?  Ok, I'll close this.  Is there an RFC you are familiar with? (Or know the proper words to use to refer to this anchor / hash?)
