### ISSUE TITLE
RailsAPI: ActionController::MimeResponds breaks ActionController::RespondWith usage

### ISSUE THREAD

**Issue by abrisse** [rails/rails#21469]
## What?

It is currently impossible to use the class-level method `respond_to` defined in `ActionController::RespondWith` (responders gem) when using `rails-api` and `ActionController::MimeResponds`.
## Why?

Indeed the class-level method `respond_to` given by `ActionController::RespondWith` is automatically loaded [[Link](https://github.com/plataformatec/responders/blob/master/lib/responders.rb#L34)]. If the developer wants to include in its controller `ActionController::MimeResponds` (to use the  instance-level method `respond_to` for example) this last one monkey-patches the class-method `respond_to` [[Link](https://github.com/rails/rails/blob/4-2-stable/actionpack/lib/action_controller/metal/mime_responds.rb#L9)]. Because of the automatic load of the module `ActionController::RespondWith`, it is impossible to change the order of the includes.

Example:

``` ruby
class ApplicationController < ActionController::API
  include ActionController::RespondWith  # done by the gem `responders`
  include ActionController::ImplicitRender
  include ActionController::MimeResponds 

 respond_to :json # will raise a NoMethod error
```
## How to fix?
1. Cherry pick https://github.com/rails/rails/commit/afd5e9a7ff0072e482b0b0e8e238d21b070b6280 into 4-2- stable. This commit fixes the problem has been merged into master a few months ago but has not been merged into the _4-2-stable_ yet.
2. Use a `unless defined?` strategy

**Comment by kbogtob** [comment]
Imho, cherry picking the commit seems the best strategy.

**Comment by abrisse** [comment]
@rafaelfranca : any update?

**Comment by amrutashah** [comment]
Any updates here?

**Comment by bf4** [comment]
@amrutashah Are you asking if there's a plan to backport afd5e9a7ff0072e482b0b0e8e238d21b070b6280 to 4-2-stable?  I agree that I think it's a good idea. It hasn't been done yet.
