### ISSUE TITLE
table_name_prefix not getting called for namespaced models

### ISSUE THREAD

**Issue by jchilders** [rails/rails#21476]
Steps to reproduce:

1) `rails new abc`
2) `cd abc`
3) `rails g model Abc::User` - This creates app/model/abc.rb and app/model/abc/user.rb. The former contains:

```
module Abc
  def self.table_name_prefix
    'abc_'
  end
end
```

4) `rails c`
5) `Abc::User.table_name`
    `=> "users"`

Expected:
    `=> "abc_users"`

This appears to be due to the module being defined in two places: `config/application.rb` and `app/models/abc.rb`. Changing the generated `module Abc` line in application.rb file to `module AbcApp` superficially fixes the problem.

**Comment by codebaker95** [comment]
I'd like to note that this only appears to be an issue in development/testing environments. The application.rb file is automatically loaded during app initialization, loading the `Abc` module in it. Therefore, when referencing `Abc::User`, the `Abc` constant is already defined, so rails doesn't go looking for it in the `models/abc.rb` file.

However, on production, all the files are eagerly loaded on initialization, so `Abc::User.table_name` returns the correct value.

One way to prevent this bug would be to add a line like `
load "app/models/abc2.rb" if Rails.env.development? || Rails.env.test?` to the application.rb file. However, I think a better solution would be simply to prevent generators from adding classes to the main application's module to prevent similar headaches in the future. If I wanted to create an Abc model, rails would display a class collusion error, and therefore a file `models/abc.rb

**Comment by codebaker95** [comment]
I'd like to note that this only appears to be an issue in development/testing environments. The `application.rb` file is automatically loaded during app initialization, loading the Abc module in it. Therefore, when referencing `Abc::User`, the `Abc` constant is already defined, so rails doesn't go looking for it in the `models/abc.rb` file.

However, on production, all the files are eagerly loaded on initialization, so `Abc::User.table_name` returns the correct value.

One way to prevent this bug would be to add a line like `load "app/models/abc2.rb" if Rails.env.development? || Rails.env.test?` to the `application.rb` file. However, I think a better solution would be simply to prevent generators from adding classes to the main application's module to prevent similar headaches in the future. If I wanted to create an `Abc` model, rails would display a class collusion error, therefore preventing the file `models/abc.rb` from being created. Thus I think this file shouldn't be permitted to be generated, even if it's a module file. I proposed a pull request [here](https://github.com/rails/rails/pull/21508), any feedback is welcome.

**Comment by inertia186** [comment]
Confirmed behavior present in Rails 5.1.1.  Engines created with namespaced models can see `table_name_prefix` in `dummy` but not when the engine is mounted in a rails project.

**Comment by enatividad** [comment]
This is still an issue in Rails 5.1.3, at least in the development environment. Restarting the server will sometimes fix the issue. The issue presents itself even if the module name isn't declared anywhere else.

**Comment by enatividad** [comment]
For some reason, when I edited my application_helper.rb, the namespace issue has been constantly bugging me. I'm not sure if something happened in Rails or Ruby, when I edited it. I hope you guys can reproduce the namespacing error by using these project files.

Please don't judge my code ;_;

### Attached Files
[sen_sys_prototype.zip](https://github.com/rails/rails/files/1234578/sen_sys_prototype.zip)

**Comment by joegaudet** [comment]
Seeing the same behavior still

**Comment by YSavir** [comment]
I am getting this error as well. However, with an strong oddity: It's working for one namespaced class, but not another.

Each class is using a different namespace.

As far as I can tell, the file setups are identical. 

Both were generated using the command `rails g model <namespace>::<modelname>`.

**Comment by abepark01** [comment]
I get the same issue in `rails 5.2.1` on a namespaced model using the rails model generator
I actually ran the `rails s` command and the table_name is not recognized.

I discovered the issue when trying to load the rails_admin root (dashboard)
See https://github.com/sferik/rails_admin/issues/3062

Any suggestions on getting rails to load the module the model is namespaced under first to get the `table_name_prefix` to get set properly?


```
rails g model collective/application
```

It creates 2 files: `app/models/collective.rb` and `app/models/collective/application.rb`

**app/models/collective.rb**
```ruby
module Collective
  self.table_name_prefix = 'collective_'
end
```

**app/models/collective/application.rb**
```ruby
class Collective::Application < ApplicationRecord
end
```

I also tried converting the generated namespace model to use the module approach and got the same result where the table_name was not including the prefix `collective_`

```ruby
module Collective
 class Application < ApplicationRecord
 end
end
```

**Workaround**
I ended up having to explicitly setting the `table_name` to `collective_applications`.


**app/models/collective/application.rb**
```ruby
module Collective
  class Application < ApplicationRecord
    self.table_name = 'collective_applications`
  end
end
```

**Comment by rafaelfranca** [comment]
See https://github.com/rails/rails/pull/21508#issuecomment-428357404 and comment below.
