### ISSUE TITLE
A bunch of AR exception classes break default method signature

### ISSUE THREAD

**Issue by rwz** [rails/rails#21474]
Example: `ActiveRecord::StatementInvalid.new` expects at least one argument, where by default subclasses of `Exception` should have all arguments optional.

This breaks a lot of code that used to just `raise ActiveRecord::StatementInvalid` or pretty much all specs that do something similar to:

```ruby
expect(MyModel).to receive(:some_method).and_raise(ActiveRecord::StatementInvalid)
```

Is there any rationale behind requiring arguments for exceptions and breaking expected behavior?

**Comment by rafaelfranca** [comment]
> where by default subclasses of Exception should have all arguments optional.

It is default but not mandatory. A subclass can have required arguments.

I believe some cases like this one can change to be optional though. Mind to work in a PR?

**Comment by rafaelfranca** [comment]
BTW, I'm closing since this is more a feature request.

**Comment by rwz** [comment]
> Mind to work in a PR?

Sure
