### ISSUE TITLE
Rails.application.routes.recognize_path is not working for paths in engine

### ISSUE THREAD

**Issue by orlandoAppfolio** [rails/rails#21477]
In the main_app, Rails.application.routes.recognize_path('path/in/engine') 
e.g. we have a Dummy engine and OccupancyYearsController
```
Rails.application.routes.recognize_path('dummy/occupancy_years')
```
will throw an exception 
```
ActionController::RoutingError: A route matches "/dummy/occupancy_years", but references missing controller: DummyController
from /Users/user_name/.rvm/gems/ruby-2.2.3/gems/actionpack-4.0.12/lib/action_dispatch/routing/route_set.rb:711:in `block in recognize_path'
```

though
```
Dummy::Engine.routes.recognize_path('occupancy_years')
```
 works just fine giving
 ``` {:action=>"index", :controller=>"dummy/occupancy_years"}```

recognize_path calls #recognize  https://github.com/rails/rails/blob/master/actionpack/lib/action_dispatch/journey/router.rb#L57

where as normal request calls #serve https://github.com/rails/rails/blob/master/actionpack/lib/action_dispatch/journey/router.rb#L28

Are there any plans to make normal request and recognize_path#recognize consistent or support passing an option to recognize_path to recognize engine paths?

**Comment by orlandoAppfolio** [comment]
attempting to fix it. in this pull request: https://github.com/rails/rails/pull/21494

**Comment by actionnick** [comment]
I'm interested to see if we think that `Rails.application.routes.recognize_path` _should_ return engine controllers. I rolled my own solution to cover this problem.

**Comment by dtelaroli** [comment]
+1

**Comment by rafaelfranca** [comment]
This method is private API and should not be used in engines or applications

**Comment by dtelaroli** [comment]
:-/

**Comment by kayakyakr** [comment]
@rafaelfranca any suggestions on getting path information for the referer, eg `Rails.application.routes.recognize_path(request.referer)`, while still using the public API?
