### ISSUE TITLE
ActiveRecord::QueryMethods#from no longer escapes mysql attributes when using #alias_attribute

### ISSUE THREAD

**Issue by johanlunds** [rails/rails#21488]
This is the same as https://github.com/rails/rails/issues/20360, but for a special case of that issue.

The special case: when using `#alias_attribute` in model it generates the same, invalid query as in previously reported (and fixed) issue.

## Script to reproduce

```ruby
unless File.exist?('Gemfile')
  File.write('Gemfile', <<-GEMFILE)
    source 'https://rubygems.org'
    gem 'rails', '4.2.4' # works with '4.2.0'
    gem 'mysql2'
  GEMFILE

  system 'bundle'
end

require 'bundler'
Bundler.setup(:default)

require 'active_record'
require 'minitest/autorun'
require 'logger'

# This connection will do for database-independent bug reports.
ActiveRecord::Base.establish_connection(adapter: 'mysql2',
                                        host: 'localhost',
                                        username: 'root',
                                        password: '',
                                        database: 'rails_mysql_bug_test')
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :test, force: true  do |t|
    t.integer :desc
  end
end

class Test < ActiveRecord::Base
  self.table_name = :test

  alias_attribute :description, :desc

  # NOTE: that we select the aliased name here, ie. "description" and not "desc"
  default_scope { select(:description) }
end

class BugTest < Minitest::Test
  def test_from_escaping_attributes
    Test.create!(desc: 10)
    Test.create!(desc: 11)

    result = Test.from(Test.where(desc: 10), Test.table_name)

    assert_equal 1, result.to_a.size
  end
end
```

## Diff of script in previously, reported issue

```diff
35c35,39
<   default_scope { select(:desc) }
---
>   alias_attribute :description, :desc
>
>   # NOTE: that we select the aliased name here, ie. "description" and not "desc"
>   default_scope { select(:description) }
```

## Rails 4.2.0

Generates query:

```sql
SELECT `test`.`desc` FROM (SELECT `test`.`desc` FROM `test` WHERE `test`.`desc` = 10) test
```

## Rails 4.2.4

Generates query:

```sql
SELECT desc FROM (SELECT `test`.`desc` FROM `test` WHERE `test`.`desc` = 10) test
```

Once again `desc` is not escaped, which causes a syntax error in Mysql:

```
Mysql2::Error: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'desc FROM (SELECT `test`.`desc` FROM `test` WHERE `test`.`desc` = 10) test' at line 1: SELECT desc FROM (SELECT `test`.`desc` FROM `test` WHERE `test`.`desc` = 10) test
```

## Investigation to root cause/what happens

1. Calling `#alias_attribute` will set `self.attribute_aliases = { 'description' => 'desc' }`. [Source](https://github.com/rails/rails/blob/20f60f276fe3d455b2a9b9fdd1f902fd00f3558e/activemodel/lib/active_model/attribute_methods.rb#L209). Note that both key and value are strings.
2. Execute `#from`
  1. Which generates a default scope by executing the block in `#default_scope`
    1. Which executes `#select` and sets `@values[:select] = ['desc']`. Note that the array contains a string. This is because the call to `#attribute_alias` returns a string. [Source](https://github.com/rails/rails/blob/b9af060569907ce83a2680aff0718e8bad310345/activerecord/lib/active_record/relation/query_methods.rb#L261).
3. Execute `#to_a` (ie. execute query) on the relation which will call `#build_arel`
  1. `#arel_columns` won't escape the column name because `@values[:select]` contains a string `'desc'`. [Source](https://github.com/rails/rails/blob/b9af060569907ce83a2680aff0718e8bad310345/activerecord/lib/active_record/relation/query_methods.rb#L1067)

## Suggested fix

Change `klass.attribute_alias(field)` to `klass.attribute_alias(field).to_sym` in `#select`. [Source](https://github.com/rails/rails/blob/b9af060569907ce83a2680aff0718e8bad310345/activerecord/lib/active_record/relation/query_methods.rb#L261)

## Temporary workaround

We changed this code:

```ruby
default_scope { select(:description) }
```

To this in our app:

```ruby
default_scope { select(:desc) }
```

**Comment by sgrif** [comment]
Backported in https://github.com/rails/rails/commit/ad078767fb4d4a78224efaaf541e9bc847cde245. I credited you for the commit since I just applied your suggested fix. Feel free to just open a PR in the future.

**Comment by sgrif** [comment]
(Ultimately this change is still lacking, but the "correct" solution requires better hooks into our aliasing behavior, which I'm planning on doing in the future, but is impossible today)

**Comment by johanlunds** [comment]
Thanks! Happy to help. Will try to create a PR next time. 



—
