### ISSUE TITLE
timestamps not present in rendered Model.all

### ISSUE THREAD

**Issue by ror6ax** [rails/rails#21499]
`Model.all` does not return created_at and updated_at fields when rendered as a page.
Confirmed by `curl` to appropriate route+.json 

When running `rails console` the same model returns timestamps.

**Comment by senny** [comment]
@ror6ax I'm not sure I understand the problem you are describing. Could you explain the issue in more detail? Or maybe put up a sample application that exhibits the problem.

**Comment by smeade** [comment]
@ror6ax and @senny - I think @ror6ax is describing rendering of json when using scaffolded views.

`http://localhost:3000/cars/1.json`
```
[{"id":1,"make":"Ford","model":"Escort","url":"http://localhost:3000/cars/1.json"}]
```

`http://localhost:3000/cars.json`
```
[{"id":1,"make":"Ford","model":"Mustang","created_at":"2015-09-09T12:57:10.333Z","updated_at":"2015-09-09T12:57:10.333Z","url":"http://localhost:3000/cars/1.json"}]
```

@ror6ax - Scaffold generated views for json are created via [jbuilder](https://github.com/rails/jbuilder). Jbuilder's template for `show.json.jbuilder` includes timestamps while `index.json.jbuilder` does not. 

Compare:
https://github.com/rails/jbuilder/blob/master/lib/generators/rails/templates/index.json.jbuilder#L2
https://github.com/rails/jbuilder/blob/master/lib/generators/rails/templates/show.json.jbuilder#L1

After generating the scaffolded views, it's easy enough to customize the rendered json to your liking, 

Look in your project for views like this (you didn't mention a specific Model name, so using Car here).

`views/cars/index.json.builder`

```ruby
json.array!(@cars) do |car|
  json.extract! car, :id, :make, :model
  json.url car_url(car, format: :json)
end
```

`views/cars/index.json.builder`
```ruby
json.extract! @car, :id, :make, :model, :created_at, :updated_at
```

To get the timestamps into cars.json, you can update your index.json.builder to include those attributes by appending them to the `json.extract!` call.
`views/cars/index.json.builder`

```ruby
json.array!(@cars) do |car|
  json.extract! car, :id, :make, :model, :created_at, :updated_at
  json.url car_url(car, format: :json)
end
```

**Comment by ror6ax** [comment]
Exactly. Thanks for explaining. Issue resolved :)
