### ISSUE TITLE
ActiveSupport::TimeZone#formatted_offset doesn't respect CEST

### ISSUE THREAD

**Issue by ilyakatz** [rails/rails#21501]
`ActiveSupport::TimeZone#formatted_offset` does not respect Central European Summer Time" (UTC+2:00). Instead it shows "Central European Time Zone" (UTC+1:00)

I created failing tests https://github.com/rails/rails/compare/master...ilyakatz:timezone?expand=1 but got confused on the implementation. There seems to be some overlap with  `ActiveSupport::TimeWithZone`. Happy to implement with some guidance

**Comment by codebaker95** [comment]
The `ActiveSupport::TimeZone#utc_offset` method that the formatted offset is shown based on is calculated with the `utc_offset` method of the current period returned by tzinfo, here's the code: 

```ruby
def utc_offset
  if @utc_offset
    @utc_offset
  else
    @current_period ||= tzinfo.current_period if tzinfo
    @current_period.utc_offset if @current_period
  end
end
```

One solution would we to change `@current_period.utc_offset` to `@current_period.utc_total_offset`, which calculates the offset including the daylight saving time. However, that could cause some problems - when `utc_offset` gets called, `@current_period` gets cached. If the method gets called the second time and the period changes in the meantime, it could return the wrong result. To fix that, we could create a separate method, like 
```
def utc_total_offset
  tzinfo.current_periot.utc_total_offset
end
``` 
that would always calculate the correct offset in a given time.

**Comment by pixeltrix** [comment]
Is this only a problem using the transition? i.e. where a timezone instance is kept around long enough for the the clocks to go forward.

**Comment by ilyakatz** [comment]
No, it is not. Check out my failing test, it doesn't not move time

**Comment by kv109** [comment]
How about this [solution](https://github.com/rails/rails/issues/21942#issuecomment-154694593)?

**Comment by al2o3cr** [comment]
See also #7297

**Comment by kv109** [comment]
Ok, so this would be my PR for that: https://github.com/rails/rails/compare/master...kv109:21501?expand=1

Let me guys now what do you think.

**Comment by ilyakatz** [comment]
@kv109 can you put summer time in your tests such that it would so `GMT+02:00`, otherwise, this test is not really testing the change

:+1: on using the stub instead of my Timecop dependency

**Comment by kv109** [comment]
@ilyakatz Thanks for the answer. 
About test: Isn't [this line](https://github.com/rails/rails/compare/master...kv109:21942?expand=1#diff-bd4b826d0145a9668aee008cbdf8c5baR464) enough?

**Comment by ilyakatz** [comment]
Oh, sorry, missed that one. Yes, it looks good to me!
--
PGP Key https://onename.io/katzmopolitan <https://onename.io/katzmopolitan>

**Comment by maclover7** [comment]
If this is still an issue, can you please create a reproduction script using one of the templates available [here](https://github.com/rails/rails/tree/master/guides/bug_report_templates)?

**Comment by kv109** [comment]
It is still an issue. Reproduction script:

```ruby
begin
  require 'bundler/inline'
rescue LoadError => e
  $stderr.puts 'Bundler version 1.10 or later is required. Please update your Bundler'
  raise e
end

gemfile(true) do
  source 'https://rubygems.org'
  gem 'rails', github: 'rails/rails'
end

require 'active_support'
require 'active_support/core_ext/object/blank'
require 'minitest/autorun'

# Ensure backward compatibility with Minitest 4
Minitest::Test = MiniTest::Unit::TestCase unless defined?(Minitest::Test)

class BugTest < Minitest::Test
  def test_to_s_in_summer_time
    zone = ActiveSupport::TimeZone['Amsterdam']
    Time.stub(:now, Time.new(2000, 6)) do
      assert_equal "(GMT+02:00) Amsterdam", zone.to_s
    end
  end
end

```

Result:
```
  1) Failure:
BugTest#test_to_s_in_summer_time [test.rb:29]:
Expected: "(GMT+02:00) Amsterdam"
  Actual: "(GMT+01:00) Amsterdam"
```

My PR: https://github.com/rails/rails/pull/22243/

**Comment by avit** [comment]
Duplicates #7297.

This shouldn't be based on the current time, that assumption won't be right for anything else. The most obvious behaviour is to always list time zones with their Standard offset. (We can get the correct offset for a given `Time` or `TimeWithZone` already.)

**Comment by pixeltrix** [comment]
@avit thanks - agree with your assessment
