### ISSUE TITLE
Behavior of AR::ConnectionAdapters handling VIEW differ

### ISSUE THREAD

**Issue by yui-knk** [rails/rails#21509]
I found out behavior of `tables` method differ by each adapters. pg does not include VIEW, but mysql and sqlite include VIEW. Code sample is below.

## What we should do ?
I think we should unify the behavior.
In my opinion, remove VIEWs from `tables` method.
`tables` method is used when we dump schema ([here](https://github.com/rails/rails/blob/master/activerecord/lib/active_record/schema_dumper.rb#L92)), now schema.rb uses `create_table` method only which mislead to create actual tables.

If this is correct way, I will write some documents and tests taking care of VIEWs for `tables` method :)
Thanks :yellow_heart: 

## Code example
books is table, ebooks is view

```ruby
class MigrationA < ActiveRecord::Migration
  def change
    create_table :books, force: true do |t|
      t.integer :author_id
      t.string :format
      t.column :name, :string
      t.column :status, :integer, default: 0
      t.column :read_status, :integer, default: 0
      t.column :nullable_status, :integer
      t.column :language, :integer, default: 0
      t.column :author_visibility, :integer, default: 0
      t.column :illustrator_visibility, :integer, default: 0
      t.column :font_size, :integer, default: 0
    end
  end
end

class MigrationB < ActiveRecord::Migration
  def create_view(name, query)
    execute "CREATE VIEW #{name} AS #{query}"
  end

  def change
    create_view "ebooks", <<-SQL
      SELECT id, name, status FROM books WHERE format = 'ebook'
    SQL
  end
end
```

### pg

```ruby
[2] pry(main)> ActiveRecord::Base.connection.tables
=> ["schema_migrations", "books"]
[3] pry(main)> ActiveRecord::Base.connection.table_exists? :ebooks
=> true
```

### mysql2

```ruby
[5] pry(main)> ActiveRecord::Base.connection.tables
=> ["books", "ebooks", "schema_migrations"]
[6] pry(main)> ActiveRecord::Base.connection.table_exists? :ebooks
=> true
```

### sqlite

```ruby
[2] pry(main)> ActiveRecord::Base.connection.tables
=> ["schema_migrations", "books", "ebooks"]
[3] pry(main)> ActiveRecord::Base.connection.table_exists? :ebooks
=> true
```

**Comment by al2o3cr** [comment]
Given a database with views, dumping it to `schema.rb` format will not be correct - just as it will be if the DB uses other features that aren't supported by the format.
