### ISSUE TITLE
Backslash in "WHERE" SQL Query

### ISSUE THREAD

**Issue by AndrzejJantos** [rails/rails#21526]
In my current project I'm trying to get results WHERE search field contain backslash.
When I run SQL Query direct on the MySql console WHERE LIKE '%\\\\%' I retrieve needed data. Unfornatelly Active Records give me error. Could someone help me with this?

**Comment by senny** [comment]
@AndrzejJantos can you attach an executable test-case that reproduces the your error? You can use [this script](https://github.com/rails/rails/blob/master/guides/bug_report_templates/active_record_gem.rb) as a starting point.

**Comment by siddhant-mohan** [comment]
@AndrzejJantos 
see the following working script for the active record query with WHERE LIKE '%\\%'.
https://gist.github.com/siddhant-mohan/65be309a40950994f1da

**Comment by matthewd** [comment]
Please use the mailing list or StackOverflow for questions/help, where a wider community will be able to help you. We reserve the issues tracker for issues only.
