### ISSUE TITLE
Fixnum becomes dirty when set to false from 0

### ISSUE THREAD

**Issue by jfragoulis** [rails/rails#21549]
```sql
CREATE TABLE `products` (
  ...
  `visible` tinyint(4) NOT NULL DEFAULT '0',
  ...
)
```

```ruby
product = Product.first
product.visible # => 0
product.visible = false
product.visible_change # => [0, 0]
# expected nil
```

The fact that, while the column is created as `tinyint(4)` the attribute is used as a boolean, surfaced this behavior.

I traced the bug [here](https://github.com/rails/rails/blob/master/activerecord/lib/active_record/type/helpers/numeric.rb#L25).

What happens is that, when `value` is boolean, `value.to_s` will turn it to string and the method will return true, which is wrong. The solution is to not go into `non_numeric_string?` at all if its a boolean.

**Comment by sgrif** [comment]
This is the expected behavior when assigning integer columns, so that the numericality validation is able to run. `tinyint(4)` is not treated as a boolean by Active Record on MySQL, only `tinyint(1)` is.

**Comment by jfragoulis** [comment]
This might be the expected behavior but is clearly not consistent. You cannot allow assignments of strings and booleans on Fixnum, then type cast them to Fixnum one and zeros and then persist that the attribute is dirty.

This inconsistency is clearly shown in my example, where the user gets the same old/new value. It is wrong for the framework to say that an attribute's state/value has changed, and then, to not be able to display the difference between the old and the new state/value. It doesn't even throw a warning.

My opinion is that the framework either needs to compare the type-casted values only (and display a warning if the new value is of different type) or show the **actual** change which would be even better and more reliable. In the example above it would be:

```ruby
product.visible_change # => [0, false]
```

The next step would be for the client to understand the error and fix it.

**Comment by sgrif** [comment]
This is what numericality validations are for.
