### ISSUE TITLE
Gemfile not found directory containing 'é' 

### ISSUE THREAD

**Issue by nieup** [rails/rails#21546]
Directories containing accents in Windows environment cause problem to find Gemfile when running `rails server`

**Comment by schneems** [comment]
What is the error message you are getting?

Can you give me an example app that reproduces the problem that uses the latest version of Rails?

**Comment by nieup** [comment]
I am getting this message, see screen shot. I am running Rails 4.2.4. 
I only initialized the server doing ‘rails new blog’  






De : Richard Schneeman
Envoyé : ‎mardi‎ ‎8‎ ‎septembre‎ ‎2015 ‎15‎:‎44
À : rails/rails
Cc : Cédric





What is the error message you are getting?

Can you give me an example app that reproduces the problem that uses the latest version of Rails?

**Comment by rafaelfranca** [comment]
You didn't attached the screenshot.

**Comment by nieup** [comment]
I am pretty sure I did, it is in this one I am certain. 






De : Rafael Mendonça França
Envoyé : ‎mardi‎ ‎8‎ ‎septembre‎ ‎2015 ‎18‎:‎05
À : rails/rails
Cc : Cédric





You didn't attached the screenshot.

**Comment by rafaelfranca** [comment]
If you attach the screenshot as email attachment it doesn't work. You need to upload in someplace and embed the image.

**Comment by nieup** [comment]
https://drive.google.com/open?id=0B2Ee2HFbmkJ4Rm9JT1BFTUF5YUk






De : Rafael Mendonça França
Envoyé : ‎mardi‎ ‎8‎ ‎septembre‎ ‎2015 ‎19‎:‎38
À : rails/rails
Cc : Cédric





If you attach the screenshot as email attachment it doesn't work. You need to upload in someplace and embed the image.

**Comment by cireficc** [comment]
Very interesting find... looks like a Unicode bug. @nieup, it would be helpful if you included your version of Windows.

**Comment by nieup** [comment]
It is a windows 8.1

**Comment by arthurnn** [comment]
isn't this a bundler issue tho? @indirect might know.

**Comment by Anagha22** [comment]
From the screenshot, I can see the error as "Gemfile not found".Try creating a Gemfile  with the needed dependencies and run $bundle install.It might work.

**Comment by arthurnn** [comment]
I will close this, as I don't think it is a rails issue.
I thinking you should [open an issue on the bundler project](https://github.com/bundler/bundler/issues/new)
