### ISSUE TITLE
mysql2 gem v0.4.0 doesn't work

### ISSUE THREAD

**Issue by lesleh** [rails/rails#21544]
When creating a new app with `rails new myapp --database=mysql`, I get an error when attempting to load the app:

    Specified 'mysql2' for database adapter, but the gem is not loaded. Add `gem 'mysql2'` to your Gemfile (and ensure its version is at the minimum required by ActiveRecord).

Manually specifying the version of mysql2 to be v0.3.20 works fine.

**Comment by sodabrew** [comment]
I didn't realize the AR adapter was using a squiggly require, so this will cause some confusion because Bundler doesn't know that it needs to hold back the mysql2 version.

@jeremy Thanks for updating the adapter - I left you a few comments on #21536

**Comment by rafaelfranca** [comment]
Backported

**Comment by rafaelfranca** [comment]
I mean, next Rails 4.2 will support mysql2 0.4

**Comment by jaredbeck** [comment]
> .. next Rails 4.2 will support mysql2 0.4

Thanks for backporting! :heart:

**Comment by slicedpan** [comment]
Just a suggestion, this issue would have been easier to diagnose if the exception message from Gem::LoadError was not swallowed up by the exception handler when the adapter specific code is required.

**Comment by Sega100500** [comment]
@jaredbeck
For Rails 3.2.xxx need use:
gem 'mysql2', '~> 0.3.20' ?

RoR 3.2.xxx no longer supported

**Comment by kaleemullah360** [comment]
do 
`gem 'mysql2', '~> 0.3.18'` this gem works with `rails version 4.x.x` 
if install `gem 'mysql2', '~> 0.4.0'` it produces gem load error

**Comment by saizai** [comment]
When will this be released?

**Comment by Anle90** [comment]
Rails v 4.2.4 error with mysql 0.4. has to use mysql2', '~> 0.3.18 to work
