### ISSUE TITLE
Rails 4.1 ActionController::TestCase::Behavior strange behaviour while sending the JSON data

### ISSUE THREAD

**Issue by DreamWalker87** [rails/rails#21545]
Hello.

I've discovered a strange behavior: Rails, seems, is unable to properly parse the JSON data if it was send by methods from ActionController::TestCase::Behavior. 

In the doc it'is mentioned that sending an entire JSON document is possible:
>  # You can also send a real document in the simulated HTTP request.
>  #
>  #   def test_create
>  #     json = {book: { title: "Love Hina" }}.to_json
>  #     post :create, json
>  #   end

but this causes **param is missing or vlue is empty** error, though the request body contains the proper JSON document, e. g. ```"{\"book\":{\"title\":\"Love Hina\"}}"```. So, **request.params** would return ```{"controller"=>"api/books", "action"=>"create", "book"=>{}}``` in this case. But this doesn't happen if:
* I don't send the JSON data

  E. g. ```post :create, book: {title: 'Love Hina'}``` would be properly parsed and  **request.params** would return ```{"controller"=>"api/books", "action"=>"create", "book"=>{"title"=>"Love Hina"}}```
* I send the same JSON data with curl:
```
curl -i -X POST -d '{\"book\":{\"title\":\"Love Hina\"}}' \
-H "Accept: application/json" \ 
-H "Content-Type: application/json" http://api.example.com:3000/books
```
  The request body would contain the *same* JSON, but this time it would be parsed properly. Bizarre!
 
Controller and test scenarios examples are [here](http://stackoverflow.com/questions/32203124/rails-4-1-1-param-is-missing-or-value-is-empty-while-sending-json-with-rspec).

P. S.: In the first case I also cared about setting the proper content type.

**Comment by al2o3cr** [comment]
`In the doc it'is mentioned that sending an entire JSON document is possible`

The doc is hard-to-read and confusing. The documentation for `ActionController::TestCase` says:
```
      # - +parameters+: The HTTP parameters. This may be +nil+, a hash, or a
      #   string that is appropriately encoded (+application/x-www-form-urlencoded+
      #   or +multipart/form-data+).
```

The thing being referenced here is the behavior of this line, introduced in https://github.com/rails/rails/pull/4272:

https://github.com/rails/rails/blob/v4.1.13/actionpack/lib/action_controller/test_case.rb#L555

It allows passing the raw POST body directly as an additional argument at the beginning of the list. It doesn't parse the supplied data, so you need to *also* send the params as a Hash. This was reported as #13135 back in 2013.

**Comment by rafaelfranca** [comment]
Right, it is not supported to pass JSON data, but it will be in Rails 5.
