### ISSUE TITLE
CSRF protection and <script> tags

### ISSUE THREAD

**Issue by designgrill** [rails/rails#21547]
Rails guide and documentation [here](http://edgeguides.rubyonrails.org/upgrading_ruby_on_rails.html#csrf-protection-from-remote-script-tags) and [here](http://guides.rubyonrails.org/security.html#csrf-countermeasures) mentions that cross-site (or remote) `<script>` tags are blocked to get a javascript response. I think the messaging can be made better.

* The blocking happens only for JS responses generated by a controller and doesn't apply to static files
* The blocking happens irrespective of whether the request was a remote `<script>` or made through the same domain. Any JS response generated by a controller for a non XHR request, by default, even from the same origin, will get blocked.

**Comment by rafaelfranca** [comment]
Could you please open a PR?

**Comment by designgrill** [comment]
@rafaelfranca Sure. Will do that soon.

Raised it as an issue to check if I am missing something. A rails rookie here.

**Comment by rafaelfranca** [comment]
I think you are correct but with a PR we can have a better idea on how you think the text could be improved and give better feedback.
