### ISSUE TITLE
Rails 4.2.3 rails engine will drop test database when running cucumber

### ISSUE THREAD

**Issue by wellsonjain** [rails/rails#21558]
Hello, here is my scenario. Because I want to modular my application, I try to encapsulate model layer and db/migration to rails engine, configure the migration path, bundle it and setup the test database . When I run cucumber It will reset my database again, but I set some default to migration and seed and it won't run `rake db:seed`. Turns out I run cucumber with empty database. Is there any configuration I missed?

**Comment by rafaelfranca** [comment]
The wiki is maintained by the community. So if there aren't any up to date instructions, we recommend you to explore the solution yourself and hopefully contribute your findings back!
