### ISSUE TITLE
Duplicated Foreign Keys

### ISSUE THREAD

**Issue by msxavi** [rails/rails#21563]
Dear contributors,

I've been facing the following issue during development phase: when it is needed to add more than one FK related to the same table, Rails generates the same FK name which results in a SQL Error.

For instance, my unit model.
```
class Unit < ActiveRecord::Base
  belongs_to :director, class_name: 'AdminUser'
  belongs_to :secretary, class_name: 'AdminUser'
```
Then the migration I have changed:
```
class AddSecretaryIdToUnit < ActiveRecord::Migration
  def change
    remove_foreign_key :units, name: 'fk_rails_6f5a58689d'
    add_reference :units, :admin_user, index: true, foreign_key: true # here rails generates the same 'fk_rails_6f5a58689d' name
    rename_column :units, :admin_user_id, :secretary_id
    add_foreign_key :units, :admin_users, column: :director_id # here I create again the previous removed FK. ugly!
  end
end
```

I know I can customize the way FK is created, however, I am wondering if 'add_reference' method could always generate a unused new name.

**Comment by senny** [comment]
@msxavi thanks for reporting :yellow_heart: 

Yea, this looks like we should consider the column as well when determining the foreign key name. I'll look into a possible patch.

For now you can work around the problem by specifying the name of the foreign key yourself:

```ruby
add_foreign_key :units, :admin_users, column: :director_id, name: "fk_non_conflicting_name"
```

**Comment by senny** [comment]
@msxavi I investigated a bit but couldn't reproduce the issue. Would you mind writing an executable test-case to reproduce the problem? You can use [this script](https://github.com/rails/rails/blob/master/guides/bug_report_templates/active_record_gem.rb) as a starting point. Then we should have common grounds what's going wrong.

**Comment by msxavi** [comment]
Hello, @senny!  Thank you for replying!

Well, I relised that the correct error is "Duplicated column name" and not FK name as mentioned.

Imagine this scenario: 
1 - Two days ago a mate wrote a migration to add a reference (column + FK):
```
class AddDirectorIdToUnit < ActiveRecord::Migration
  def change
    add_reference :units, :admin_user, index: true, foreign_key: true
    rename_column :units, :admin_user_id, :director_id
  end
end

```
2 - Then today I realised that I need one more reference then I write this:
```
class AddSecretaryIdToUnit < ActiveRecord::Migration
  def change
    add_reference :units, :admin_user, index: true, foreign_key: true
  end
end

```
Then I got Duplicated FK name! 

It is not a big deal perhaps. To solve this I need some changes in my migration:
```
class AddSecretaryIdToUnit < ActiveRecord::Migration
  def change
    add_column :units, :secretary_id, :integer
    add_foreign_key :units, :admin_users, column: :director_id, name: "fk_non_conflicting_name"
  end
end

```
In my view add_reference method does not have more useful options such as reference_table_name or column_name to customise the column and FK created.

**Comment by senny** [comment]
@msxavi instead of `add_references` + `rename_column` it'd be better to `add_column` + `add_foreign_key`. This way you don't get a foreign key name based on the wrong column name.

One possible addition would be to extend the `:foreign_key` option to `add_references` in way that lets you specify the target table. Something along the lines of:

```ruby
add_reference :units, :director, index: true, foreign_key: { to_table: :admin_users }
```

This would then allow Rails to generate the key name based on the right column.

@rafaelfranca @sgrif thoughts?

**Comment by msxavi** [comment]
@senny Agreed! This simple and clear addition would be enough! :+1: 

Another possible approach would be customise the column_name instead of table.
```
add_reference :units, :admin_user, index: true, foreign_key: { column_name: :director_id }

```
Same result. Rails would also be able to generate based on the column. It depends on the view. =)

**Comment by senny** [comment]
@msxavi passing the column name nested under `:foreign_key` doesn't feel right. `add_reference` basically has a signature of `add_reference table, column(without_id), options = {}`. The second argument is not the `to_table` but the name of the reference column without the `_id` part. In many cases this happens to be `to_table` but it's not necessary.

**Comment by msxavi** [comment]
@senny ooh.. you're right. My mistake.

I have thought it was similar to create_join_table method:
```
add_reference table_1, table_2, options = {}

```

**Comment by senny** [comment]
@msxavi I added a `:to_table` option on `master`. It will be available with Rails 5.

**Comment by lukeredpath** [comment]
@senny this feature seems to result in migrations that do not reverse when they should, please see my issue above.
