### ISSUE TITLE
Problem in development when reloading page after a bug

### ISSUE THREAD

**Issue by jonathantribouharet** [rails/rails#21561]
Hi,
I have a strange bug (present on many projects, on Rails 4.2.3 and 4.2.4).
When I have a bug in development (like NoMethodError or anything else), I fix this bug and reload the page, I still have the error but in "extracted source" section you can see the code is good (it's the new code without the bug).
I have to restart the server for fix the bug. It seems inconsistent, sometime it happen at every bugs and sometime I don't have any problem (on the same project with no change).

I take a screenshot.

<img width="1440" alt="screen shot 2015-09-09 at 10 41 39" src="https://cloud.githubusercontent.com/assets/188946/9757278/d6db8abe-56df-11e5-85d9-cb606d0d6789.png">

Here my gemfile:

	source 'https://rubygems.org'

	gem 'rails', '4.2.4'

	gem 'pg'

	gem 'sass-rails', '~> 5.0'
	gem 'uglifier', '>= 1.3.0'
	gem 'coffee-rails', '~> 4.1.0'
	gem 'therubyracer', platforms: :ruby
	gem 'jquery-rails'
	gem 'jbuilder', '~> 2.0'
	gem 'sdoc', '~> 0.4.0', group: :doc

	gem 'bcrypt', '~> 3.1.7'

	group :development, :test do
		gem 'byebug'
		gem 'web-console', '~> 2.0'
		gem 'spring'

		gem 'hirb'
	end

	gem 'jt-rails-toolbox', '~> 1.0'

	gem 'puma'
	gem 'activeadmin', github: 'activeadmin'

	gem 'simple_form'
	gem 'country_select'

	gem 'bootstrap-sass', '~> 3.3.5'
	gem 'bootstrap_form', '~> 2.3'

I didn't change anything in the config folder (except database.yml, routes.rb and locales).

**Comment by rafaelfranca** [comment]
Can you please provide a sample application that reproduces the error?

**Comment by jonathantribouharet** [comment]
I could but it happen with an empty project.
Here the steps for installing an empty project:

- `mkdir test-bug; cd test-bug`
- ` gem install rails`
- `rails new -T ../test-bug/`
- uncomment  `gem 'therubyracer', platforms: :ruby"`
- `bundle install`
- `rake db:create`
- `rails s -b 0.0.0.0`

The problem may be coming from the fact I use vagrant with `synced folder` [Vagrant file](https://github.com/jonathantribouharet/vagrant-rails-dev/blob/master/Vagrantfile) and rails doesn't see the change of the file.

**Comment by pixeltrix** [comment]
I assume you're using Virtual Box? If so it's because it's not propagating the file change notification and it never will: https://www.virtualbox.org/ticket/10660. If you're not using Virtual Box I'll reopen and have another look.

**Comment by jonathantribouharet** [comment]
Thank's, I used VMWare before.

**Comment by pixeltrix** [comment]
@jonathantribouharet looks like the VMWare shared folder system doesn't support file change notifications either: https://groups.google.com/d/msg/vagrant-up/ZZpM1nTCSSQ/PQhRzgTD1-wJ

:sob: 

I think the intermittent nature is due to something being change in the host environment which is triggering the reloader. 

I'm sorry but there's not much you can do - either you'll need to avoid shared folders and use something like rsync to copy the changed files or there's always the nuclear option of turning off watching for updates by setting `config.reload_classes_only_on_change = false` in your development,rb file.

**Comment by jonathantribouharet** [comment]
I used VMWare for Rails (from 2.x to 4.2) development for 5 years, I didn't have the same problem.
Shared folder is very useful, I develop on my native system (Mac OS) and I run the server on the same environment than the production server, and I keep my system clean without installing homebrew or macport.

**Comment by pixeltrix** [comment]
@jonathantribouharet you say that you've used shared folders for this before - so is it a change in a patch release of Rails, e.g. 4.2.2 => 4.2.3 ?

**Comment by jonathantribouharet** [comment]
It's possible but I can't confirm, I have another project on 4.2.1 and I don't remember having this bug.
