### ISSUE TITLE
button_tag doesn't trigger UJS driver unless it type='submit'

### ISSUE THREAD

**Issue by cireficc** [rails/rails#21564]
The `button_tag` will trigger the UJS driver only when the button's `type='submit'`.

For example, if I want to generate a delete button with confirmation I could do:

`button_tag "Delete", data: { confirm: "Are you sure you want to delete this resource?"}`

However, I want to use a button with confirmation to delete a nested resource on the main resource's form, but if I use the above method, the button's type is `'submit'` so it immediately submits the form after confirmation. That is not desirable.

I would like to use:

`button_tag type: 'button', data: { confirm: "Are you sure you want to delete this resource?"}`

However, because the button type is `'button'` and not `'submit'`, the UJS driver isn't triggered, thus no confirmation is shown.

It seems to me that the UJS driver should pick up anything that has `data-confirm` (and `data-disable`, for that matter), instead of only activating for `'submit'` buttons.

Is this by design or is this something that should be changed?

**Comment by rafaelfranca** [comment]
This issue was moved to rails/jquery-ujs#437
