### ISSUE TITLE
Gemfile doesn't respect group

### ISSUE THREAD

**Issue by chirag7jain** [rails/rails#21571]
I added **puma gem** to my **gemfile** with group **production, staging**

```
group :production, :staging do
  gem 'puma'
end
```

added config for puma in config/puma.rb

```
# REF https://devcenter.heroku.com/articles/deploying-rails-applications-with-the-puma-web-server
workers Integer(ENV['WEB_CONCURRENCY'] || 2)
threads_count = Integer(ENV['MAX_THREADS'] || 5)
threads threads_count, threads_count

preload_app!

rackup      DefaultRackup
port        ENV['PORT']     || 3000
environment ENV['RACK_ENV'] || 'development'

on_worker_boot do
  # Worker specific setup for Rails 4.1+
  # See: https://devcenter.heroku.com/articles/deploying-rails-applications-with-the-puma-web-server#on-worker-boot
  ActiveRecord::Base.establish_connection
end

```

after adding the gem I did 

```
bundle install
```

I am using **rvm** with application specific gemset

when I do 

```
rails s -e development
```

I expect that it would **only load development gems** and my webserver would be **webrick** not **puma**

If its not a rails specific please also point what is issue related to

if there is an easy way around forcing the application to use webrick in development please added it in the comments

**Comment by chirag7jain** [comment]
I removed staging from the group and its working without puma

**Comment by chirag7jain** [comment]
currently I work with

```
bundle install --without production staging
rails s
```

**Comment by rafaelfranca** [comment]
Gemfile groups are not the same as environments they are only used to filter gems on `bundle install` so what you are doing right now (using `--without`) is the right things to do.
