### ISSUE TITLE
references() overrides select()

### ISSUE THREAD

**Issue by NobodysNightmare** [rails/rails#21578]
## Reproduction

Given the following models:
````ruby
class Foo < ActiveRecord::Base
  belongs_to :bar
end

class Bar < ActiveRecord::Base
end
````

Run the following via `rails c`:
````ruby
2.1.4 :016 >   Foo.all.select(:id).to_sql
 => "SELECT `foos`.`id` FROM `foos`" 

2.1.4 :017 > Foo.all.includes(:bar).references(:bar).select(:id).to_sql
 => "SELECT `foos`.`id`, `foos`.`id` AS t0_r0, ..., `bars`.`id` AS t1_r0, ... FROM `foos` LEFT OUTER JOIN `bars` ON `bars`.`id` = `foos`.`bar_id`" 
````

## Description

I'd expect that by specifying `select(:id)`, the resulting SQL will always only have the specified columns inside the `SELECT` statement and no other columns.
However, by adding `includes` and `references` the projection (`SELECT`) is extended by all columns of `foos` and all columns of `bars`.

I first thought this might be the desired behaviour, but then I realized that I only need `references` to refer to foreign tables in a `where` statement (e.g. `where('bars.id = 4')`), but I could never make use of those automatically generated `t0_r0` column names in the SELECT.

In the real world code I want to use an aggregate function\* inside the `select`, which makes it critical that no other columns are selected at the same time. Otherwise the query would fail (at least for PostgreSQL).

\* Of course I am aware of `sum(:my_column)` and `caulculate(:sum, ...)`.
However in my use case this is not powerful enough because I want to combine multiple aggregations in a single query. Also the underlying data is... special... and so my aggregation looks something like this: `SUM(CAST(foos.value AS decimal(60,3))) AS value`

**Comment by al2o3cr** [comment]
This is a known issue (for instance, https://github.com/rails/rails/issues/12423 but there are others) with `includes` and `select`.

In your case, I'm not at all clear what the purpose of `includes` in your query is. If you're only wanting aggregate columns, the record preloading that `includes` specifies won't be useful - all you're getting from `includes` at that point is a LEFT OUTER JOIN (and a bunch of columns you *don't* want).

**Comment by NobodysNightmare** [comment]
That is the part where my example is a bit too minimalistic. In the real world I would have a `where` on a foreign attribute (e.g. `where('bars.id = 4')`). Something that makes me need the `includes` for the `where`.

**Comment by matthewd** [comment]
It sounds to me like you want `joins` (or possibly a left join -- #12071). `includes` has a specific meaning, and it ain't "please add a left join to my query".

**Comment by NobodysNightmare** [comment]
@matthewd 
> It sounds to me like you want joins (or possibly a left join -- #12071). includes has a specific meaning, and it ain't "please add a left join to my query".

I am using it because I need to reference something from another record in my `where` clause. That is exactly what is done in the [documentation of `includes`](http://apidock.com/rails/ActiveRecord/QueryMethods/includes):

````ruby
User.includes(:posts).where('posts.name = ?', 'example').references(:posts)
````

I could add that `where` statement to my example, but tried putting together a minimalistic one that is pleasant to reproduce.

Thinking about it, probably AR will use the `t0_r0` values to put my `Foo` and its referenced `Bar` together correctly. Still I find it irritating, that `select` loses its property to exclude all default projections...

So is it simply *wrong* to use includes when you need a foreign attribute in a `where` clause?

**Comment by matthewd** [comment]
Yes and no.

As you surmise, `includes` means more than just a join -- it also instructs AR to construct the associated objects. So, if you want to load and populate a set of related objects all in one query, while applying a foreign-attribute condition, then yes, `includes`+`references`+`where` will do just what you want.

However, that's not what you want to do; you're trying to construct a raw query.. that's a much lower level operation than `includes`. (To wit: you care what the query looks like; in the regular `includes` use case, one does not.) So, while `includes` happens to construct the join you're looking for as one step in doing its job, you can't expect it to *only* do the thing you want, and surrender its ability to *actually* do the thing its contract promises. You only want a particular thing (the join), without any post-processing during the load... so that's what you need to ask for.

**Comment by NobodysNightmare** [comment]
@matthewd Thank you for your explanation. It totally makes sense.

I will close this ticket, because everything seems to work as expected. I will take this last chance to link to another issue I opened in this context: https://github.com/rails/rails/issues/21577

The problem described there was my try to evade the behaviour observed here, but without luck ^^
