### ISSUE TITLE
includes().references() not expanded in subqueries

### ISSUE THREAD

**Issue by NobodysNightmare** [rails/rails#21577]
## Reproduction

edit: Upon request by @senny I now also provided [a test case](https://gist.github.com/NobodysNightmare/45992e1020ec092b9e4b). This is probably more self-explanatory than my bla bla below.

---

Given the following models:

``` ruby
class Foo < ActiveRecord::Base
  belongs_to :bar
end

class Bar < ActiveRecord::Base
end
```

Run the following on `rails c` (tested on Rails 4.2.3 and 4.1.13):

```
2.1.4 :007 > query = Foo.includes(:bar).references(:bar)
 => #<ActiveRecord::Relation []> 

2.1.4 :008 > query.to_sql
 => "SELECT `foos`.`id` AS t0_r0, ..., `bars`.`id` AS t1_r0, ... FROM `foos` LEFT OUTER JOIN `bars` ON `bars`.`id` = `foos`.`bar_id`" 

2.1.4 :009 > Foo.from(query, 'baz').select('baz.id').to_sql
 => "SELECT baz.id FROM (SELECT `foos`.* FROM `foos`) baz" 
```
## Description

Normally the `includes` + `references` of `query` are correctly evaluated, leading to an expansion of the SQL query to contain a `JOIN`. As soon as I wrap the `query` inside a `from` call, the expansion is gone and it behaves like a regular `Foo.all`.

The SQL string I'd expect pretty much looks like this:

``` ruby
"SELECT baz.id FROM (#{query.to_sql}) baz" 
```

The behaviour does not change if I add a `when` condition on a property of `Bar`, which will now fail, because the when condition refers to an attribute that was not joined. The query fails.

Is this the desired/expected behaviour? Am I doing it wrong? If I am doing it wrong: How do I filter by attributes of a related model in a subquery?
## Disclaimer

Of course this is only a minimalistic example and not the actual code where I've encountered the problem. I hope that the example is good enough to explain the problem and small enough to require no domain knowledge.

Note: I discovered this behaviour after trying to evade some [other unexpected behaviour](https://github.com/rails/rails/issues/21578).

**Comment by NobodysNightmare** [comment]
I noticed that the same problem also occurs for subqueries that active-record will perform all by itself (i.e. without an explicit `from` call):

````ruby
# give me the foos whoose Bar has an id of three
my_foos = Foo.includes(:bar).references(:bar).where("#{Bar.table_name}.id = 3")
my_foos.to_sql
 => SELECT `foos`.`id` AS t0_r0, ... FROM `foos` LEFT OUTER JOIN `bars` ON `bars`.`id` = `foos`.`bar_id` WHERE `bars`.`id` = 3


# now give me all Foos whoose parent is one of the previously  found foos
Foo.where(parent: my_foos).to_sql
 => "SELECT `foos`.* FROM `foos` WHERE `foos`.`parent_id` IN (SELECT `foos`.`id` FROM `foos` WHERE (bars.id = 3))"
````

ActiveRecord cleverly transforms the relation `my_foos` into a subquery. However, this query will break, since the WHERE of the subquery does not JOIN the required `bars` table anymore.

*Note: this example assumes an additional `belongs_to :parent` on `Foo`. Basically anything that references a `Foo` will work.*

**Comment by senny** [comment]
@NobodysNightmare can you write an executable test-case to reproduce the issue? You can use [this script](https://github.com/rails/rails/blob/master/guides/bug_report_templates/active_record_gem.rb) as a starting point.

**Comment by NobodysNightmare** [comment]
@senny Those templates are great! I uploaded my test case in the following gist:
https://gist.github.com/NobodysNightmare/45992e1020ec092b9e4b

**Comment by NobodysNightmare** [comment]
Hello @rails-bot / @senny 

Sorry for the delay, I can still reproduce the issue with the latest rails version:

> Using activesupport 4.2.5.1
...
Using activemodel 4.2.5.1
...
Using activerecord 4.2.5.1
...
BugTest#test_reference_expansion_in_subquery:
ActiveRecord::StatementInvalid: SQLite3::SQLException: no such column: bars.value: SELECT COUNT(*) FROM "blubbs" WHERE "blubbs"."foo_id" IN (SELECT "foos"."id" FROM "foos" WHERE (bars.value > 3))

Also for Rails 5:

> Installing activesupport 5.0.0.beta2
Installing activemodel 5.0.0.beta2
Installing arel 7.0.0
Installing activerecord 5.0.0.beta2
...
BugTest#test_reference_expansion_in_subquery:
ActiveRecord::StatementInvalid: SQLite3::SQLException: no such column: bars.value: SELECT COUNT(*) FROM "blubbs" WHERE "blubbs"."foo_id" IN (SELECT "foos"."id" FROM "foos" WHERE (bars.value > 3))
