### ISSUE TITLE
Rails should not depend on JavaScript (hard to port beyond x86)

### ISSUE THREAD

**Issue by eiked** [rails/rails#21583]
I am trying to get my rails application to run on a rig other than x86/amd64.

The problem is sprockets, relying on a JavaScript engine for the respective platform.

All other parts of ruby (and rails) port just fine across all architectures.

But not having a JavaScript engine on a platform just breaks it badly.
(because sprockets depends on it) -- aka rails does not work.
[and we all know that compling libv8 is a bad drag, every version again -- thank you google]

I'd like to suggest: that Rails should not depend on JavaScript.

I believe, Sprockets could fallback and still work,
even if there's no JavaScript Engine available.
Please just concat that javascript files.

Aka: Rails should not depend on JavaScript.
Ruby just ports fine across all platforms, works like a charme!
-- but Rails does not (because of sprockets relying on x86/js)

But that processing is only needed in the precompile stage.
Maybe we should offer that as a service?

---

Ruby (and Rails) should not depend on JavaScript

~eike

**Comment by rafaelfranca** [comment]
Thank you so much for the issue but we don't take feature request on the issue tracker. We recommend you to try to implement the feature and send us a pull request or if you are in doubt if the feature will be accepts ask in Rails Core mailing list for feedback.
