### ISSUE TITLE
ActiveRecord opens an uncontrollable number of threads

### ISSUE THREAD

**Issue by whistlerbrk** [rails/rails#21587]
I've created a gist here: https://gist.github.com/whistlerbrk/a8766e0199333aed1075

I've been wrestling with this for a while.

A simple script, a simple simple script which isn't using any queuing libraries.

Can I no longer use ActiveRecord outside of Rails?

**Comment by whistlerbrk** [comment]
Please note that I've also run this w/the connection_pool block commented out and had the same exact thing occur.

`ps aux | grep importer | wc -l` => very high

Lots of key violations from multiple threads trying to save the same thing.

I've been a Rails user since 1.2.0, I've never had a problem scripting with AR. I can't figure this out.

I've resorted to establishing and disconnected after the top and before the end of every loop. It's the only thing which lets me build...

**Comment by matthewd** [comment]
Can you please make a standard [executable test case](http://edgeguides.rubyonrails.org/contributing_to_ruby_on_rails.html#create-an-executable-test-case)?

That should show us the relevant parts of the Product model, which seems relevant... the fact you're configuring the reaper implies you expect multiple threads to be in play.

**Comment by whistlerbrk** [comment]
Yes, give me a little time

**Comment by oliverswitzer** [comment]
"Simply use ActiveRecord::Base.connection as with Active Record 2.1 and
earlier (pre-connection-pooling). Eventually, when you're done with
the connection(s) and wish it to be returned to the pool, you call
ActiveRecord::Base.clear_active_connections!. This will be the
default behavior for Active Record when used in conjunction with
Action Pack's request handling cycle."

sees in ConnectionPool.rb

Have you tried calling `.clear_active_connections!` for each connection you spawn?

**Comment by oliverswitzer** [comment]
actually, perhaps using connection_pool checkout/checkin will solve your thread spawing issue? 

```    
    # 2. Manually check out a connection from the pool with
    #    ActiveRecord::Base.connection_pool.checkout. You are responsible for
    #    returning this connection to the pool when finished by calling
    #    ActiveRecord::Base.connection_pool.checkin(connection).
```

**Comment by whistlerbrk** [comment]
I just built a new machine so I haven't had time to test this out. I will
and if that solves my issue I'll close. But I'll likely send a PR for
documentation because it isn't very clear in the edge guide

**Comment by thedarkone** [comment]
Guys, a couple of points:
 * you seem to be talking about `AR::Connection` and a `Thread` as if they are the same thing, they are not, you're not making any sense!
 * `.clear_active_connections!` does nothing to clean up rogue threads, it deals with connections,
 * `with_connection` automatically checks the connection back in the end of the block (this is what the method is for), there is no need to call `.clear_active_connections!`,
 * I run a test with the provided gist and no extra threads are spawn.

**Comment by whistlerbrk** [comment]
I don't have time to reproduce the error now and it's more likely it was coming from my code or a dependency than it was from AR.
