### ISSUE TITLE
Privatize or remove `ActiveRecord::Attribute#came_from_user?` and associated attribute methods?

### ISSUE THREAD

**Issue by gkop** [rails/rails#21586]
My impression is that this is not an API that should be public. More info at https://github.com/thoughtbot/factory_girl/issues/813

**Comment by rafaelfranca** [comment]
Thank for the issue. The whole class is private api of Rails, so we don't need to change anything.

**Comment by gkop** [comment]
You're right. Thanks for your consideration.

**Comment by gkop** [comment]
Oh @rafaelfranca what do you think of this idea: since the attribute meta methods are only used at https://github.com/rails/rails/blob/9f4f08cdc1fb43f9b14d49f32db9a179abc77f6c/actionview/lib/action_view/helpers/tags/base.rb#L43-L46 , couldn't we just ditch them and hit the instance variable directly here? That design would remove a bunch of infrequently used methods, and reduce code overall...

**Comment by gkop** [comment]
Also, is it new for rails 5 that the methods are private? In 4.24 they are definitely plain public :/

**Comment by matthewd** [comment]
@gkop `:nodoc:` means internal, regardless of ruby access specifiers

**Comment by gkop** [comment]
Thanks Matthew, I didn't know that.
