### ISSUE TITLE
ActiveRecord raw sql very slower than MySql

### ISSUE THREAD

**Issue by AugustoPedraza** [rails/rails#21590]
I'm running a simple raw MySql query with ActiveRecord(*#select_all* method) and the time used to return result is slower that running the same query directly in MySql Workbench.

The query is the following:

```sql
SELECT 
      CASE 
        WHEN
        WeekDay(c.collect_date) >=0 AND WeekDay(c.collect_date) <5 THEN 1
      ELSE 0 
      END AS is_business_day, 
      HOUR(c.collect_date) consumption_hour, 
        SUM(c.energy), 
        AVG(c.power) 
    FROM consumptions c
    INNER JOIN devices d ON c.device_id=d.device_id AND d.ftp_id=1    
    GROUP BY CASE WHEN
        WeekDay(c.collect_date) >=0 AND WeekDay(c.collect_date) <5 THEN 1
      ELSE 0 
      END, HOUR(c.collect_date)
```

For your information, the *consumptions* table have ~3 millions of records and the devices have < 1000 records.

The times consumed for every approach are:

  - ActiveRecord: **33.6** seconds.
  - Mysql Bench: **14.0** seconds.

The result of the query are just ~100 records.

Should I consider it a bug?

**Comment by rodzyn** [comment]
@AugustoPedraza Why `select_all`? Did you try `ActiveRecord::Base.connection.execute`?

**Comment by rafaelfranca** [comment]
When you say time to return the result are you only considering the query time or also the time to build the object array?

**Comment by roqui2000** [comment]
@rafaelfranca , The resultset is just around 50 records. I don't believe rails should take more than 300ms to build up 50 records with 4 columns to any model after the db engine returns the result.

**Comment by rafaelfranca** [comment]
Yeah, I agree but to better understand what is going on it would be great if we could measure only the time to result the query. Maybe it is not Rails fault but some difference in how the connection client is configured in MySql Workbench.

**Comment by AugustoPedraza** [comment]
@rodzyn I already run some profiling with [ruby-prof](https://github.com/ruby-prof/ruby-prof) and I got the following results:

Method | Consumed time for ftp_id= 1 | Consumed time for ftp_id= 2
-----------|---------------------------------------|-----------------------------------------
*Rails mysql console*| 470 ms|28_900 ms
*Mysql Workbench* |8_728 ms| 12_974 ms
*ActiveRecord(__execute__)*|  430 ms | 29_121 ms
*ActiveRecord(__select_all__)*|  474 ms | 29_889 ms

Below, also you can see some db's data:

  - Total records Consumptions: 3_873_814
      - For ftp_id 1: 226_047
      - For ftp_id 2: 3_647_767
  - Total records Devices:      170
      - For ftp_id 1: 73
      - For ftp_id 2: 97

Also, @rafaelfranca you can check the profiling results [this Google Drive link](https://drive.google.com/file/d/0B8MdWulMFj-oSjVJOU1FZG1oUFU/view?usp=sharing)

cc @roqui2000,

**Comment by rafaelfranca** [comment]
For what I could get on the profiling results more than 98% of the time is consumed in the query itself, so it doesn't seems like an Active Record problem. Even it is a problem on the Mysql2 client or it is configuration difference between the Mysql Workbench and the Mysql2 connection.

**Comment by AugustoPedraza** [comment]
@rafaelfranca you were right. The "problem" is that MysqlWorbenck is faster than ActiveRecord and Mysql. ([this is the related issue that I created](https://github.com/brianmario/mysql2/issues/682))
