### ISSUE TITLE
:mem_cache_store vs. :dalli_store?

### ISSUE THREAD

**Issue by wjordan** [rails/rails#21595]
It seems that Rails ActiveSupport provides a Memcached adapter [`:mem_cache_store`](https://github.com/rails/rails/blob/master/activesupport/lib/active_support/cache/mem_cache_store.rb), that requires the `dalli` gem and provides a cache store implementation that wraps `Dalli::Client`. However, dalli also provides its own Memcached adapter, [`:dalli_store`](https://github.com/mperham/dalli/blob/master/lib/active_support/cache/dalli_store.rb) that seems to do the exact same thing. :confused: 

Could someone compare these two competing Rails cache store implementations and provide some guidelines as to when it's appropriate to use one or the other?

(I've cross-posted this to mperham/dalli#557, since this confusion affects both projects.)

**Comment by rodzyn** [comment]
After quick look on both implementations, Rails mem_cache_store is truly based on Dalli client, but also it's compatible with Rails' generic `Store` implementation. On the other side Dalli has a standalone solution.
The first difference that you can notice is Dalli support for connection pool, thus if you are using multithreaded Rails it might be an option (although I don't have an experience with that).

**Comment by rafaelfranca** [comment]
Please use the mailing list or StackOverflow for questions/help, where a wider community will be able to help you. We reserve the issues tracker for issues only.

**Comment by wjordan** [comment]
@rafaelfranca thanks for your attention, allow me to rephrase in a way that makes the code-quality/documentation issue I wished to raise more clear:

There are two conflicting Rails ActiveSupport cache store implementations for Memcached, one depending on the `dalli` gem (no version range specified) and another provided by the `dalli` gem itself. Rails provides `ActiveSupport::Cache::MemCacheStore`, which developers are currently instructed to use in the [Rails Guide](http://guides.rubyonrails.org/caching_with_rails.html#activesupport-cache-memcachestore). Dalli provides its own `ActiveSupport::Cache::DalliStore`, which developers are instructed to use in Dalli's own [README](https://github.com/mperham/dalli#usage-with-rails-3x-and-4x). This duplicated functionality and conflicting documentation creates confusion among Rails developers as to which implementation is the correct or officially-supported one. This could be resolved by either deprecating one implementation in favor of the other (Dalli's current maintainer [suggests](https://github.com/mperham/dalli/issues/557#issuecomment-139649630) that `DalliStore` is probably better maintained and tested currently) or, if there are actually significant reasons for continuing to maintain the cache store implementations in parallel, adding documentation describing when it's appropriate to use one or the other.

Does this description clarify the issue at all? If it's welcome, I would be happy to contribute a pull request to deprecate `ActiveSupport::Cache::MemCacheStore` in favor of `ActiveSupport::Cache::DalliStore`, or to refactor `MemCacheStore` as a thin wrapper around `DalliStore` to eliminate the duplicated code, if either of these sound like a valid approach.

**Comment by rafaelfranca** [comment]
Yeah, I understand that but MemCacheStore using dalli is just an implementation detail, so I'd keep it as it is. If in the feature we decide to change it to use a new gem we could without having to tell users to change their code.

We could refactor it to be a wapper around `DalliStore` if that is going to keep its actual behavior the same. Feel free to submit a pull request.

**Comment by jeremy** [comment]
(History: Dalli's bundled cache store broke compatibility for existing memcache store users. Different options, different value wrappers, etc. A quick perusal of git history will show you the story.)
