### ISSUE TITLE
Rails 4.2.4 is having issues with mysql 0.4.0

### ISSUE THREAD

**Issue by xw19** [rails/rails#21597]
Hello
I just tried to create a new rails app with 
```ruby
 rails new MyNewApp -d mysql
```
Now when I am doing rake db:create

I was getting error

```
   Specified 'mysql2' for database adapter, but the gem is not loaded. Add `gem 'mysql2'` to your Gemfile (and ensure its version is at the minimum required by ActiveRecord).
```
So, I have to add 

```
  gem 'mysql2', '~> 0.3.18'
```

to make it work

**Comment by rafaelfranca** [comment]
Thank you for the issue. Yes, you have to add that but it is also fixed on the 4-2-stable branch.
