### ISSUE TITLE
In activejob,how get the real job id with sidekiq?

### ISSUE THREAD

**Issue by arnkorty** [rails/rails#21613]
```ruby
#environment:
sidekiq (3.5.0)
activejob (4.2.4)
```
<img width="857" alt="ec23d641-b51b-40d5-9b82-402df1458f85" src="https://cloud.githubusercontent.com/assets/2126904/9837775/fa88ddb8-5a7c-11e5-8098-3ea3734a5329.png">
<img width="952" alt="47230d7b-cb9c-4e5c-ac2d-5262e8209d5e" src="https://cloud.githubusercontent.com/assets/2126904/9837780/0b8e361c-5a7d-11e5-9fb8-48e6cb012767.png">

**Comment by mperham** [comment]
https://github.com/mperham/sidekiq/wiki/Active-Job#job-id

**Comment by arnkorty** [comment]
thanks

**Comment by arnkorty** [comment]
`provider_job_id` method,It seems not to support in activejob 4.2.4. Now only support in 5.0 or later.

**Comment by arnkorty** [comment]
@matthewd , do activejob 4.2.x  support `provider_job_id` method in  future?
