### ISSUE TITLE
using select with AS in default_scope breaks count

### ISSUE THREAD

**Issue by thomassnielsen** [rails/rails#21633]
Related issue: https://github.com/rails/rails/issues/19146

When having a default_scope with a `SELECT` statement that uses `AS`, count breaks.

```ruby
default_scope { select("#{self.table_name}.*, slugs.name AS slug_str").joins("LEFT JOIN slugs ON slugs.relation_type = '#{self.table_name.singularize}' AND slugs.target = #{self.table_name}.id") }
```

Having this code breaks `records.count`, with the following error:

```sh
PG::SyntaxError: ERROR:  syntax error at or near "AS"
LINE 1: SELECT COUNT(shops.*, slugs.name AS slug_str) FROM "shops" I...
```

I think there should be a way to either define a default_scope for count, or otherwise define that `COUNT` should skip the `SELECT` part of the query. In any case, ActiveRecord shouldn't produce invalid SQL based on valid input.

**Comment by matthewd** [comment]
That's what `count` does.

If you want a `COUNT(*)` that ignores the established `select`, you should use `count(:all)` (or `size`).

**Comment by thomassnielsen** [comment]
For anyone finding this issue: Another issue is that `COUNT` can't have more than one input either. Using `count(:all)` works in some cases, but be aware that you might get another result (if some rows have a NULL value in the column you were selecting by).
