### ISSUE TITLE
Postgresql connection adapter's faulty default value logic

### ISSUE THREAD

**Issue by kenaniah** [rails/rails#21630]
While diving into #21627, I discovered that the postgresql adapter uses multiple code paths for setting default values during schema migrations. These code paths, however, produce different results, and thus bugs.

[4-2-stable activerecord/lib/active_record/connection_adapters/postgresql/quoting.rb:59](https://github.com/rails/rails/blob/4-2-stable/activerecord/lib/active_record/connection_adapters/postgresql/quoting.rb#L59)

``` ruby
        # Does not quote function default values for UUID columns
        def quote_default_value(value, column) #:nodoc:
          if column.type == :uuid && value =~ /\(\)/
            value
          else
            quote(value, column)
          end
        end
```

This function is supposed to be used to determine how a default value should be quoted for a column during schema migration (note that this has been renamed to `quote_default_expression` on master).

This function is used by `change_column` and friends, but `add_column` and `add_column_options!` never call this method and instead delegate their work to `super`. This causes improper default values to be set as the quoting logic varies by operation.

**Comment by jeremy** [comment]
Nice catch! Could you open a pull req with a fix? 👏
