### ISSUE TITLE
something went wrong error while accessing localhost Rails 5.0.0 alpha

### ISSUE THREAD

**Issue by manivi** [rails/rails#21642]
Rails newbie here, was following a pluralsight tutorial in installing Rails 5.0.0 alpha. Installed Rails 5.0.0 alpha by pointing the rails gem & other gems to git hub repo 
```ruby
gem 'rails', github:'rails/rails'
gem 'arel', github: 'rails/arel'
gem 'rack', github: 'rack/rack'
gem 'sass-rails', github: 'rails/sass-rails'
gem 'sprockets',  github: 'rails/sprockets'
gem 'sprockets-rails', '3.0.0.beta2'
```
then issued bundle install gave yes to override current gem file and then updated the gem file with above gem entries. Issued bundle install command again, fired up web rick server and when I try to access localhost:3000/ in my browser I am presented with something went wrong error. No detailed error logs in server console as well.

```logs
rails s
=> Booting WEBrick
=> Rails 5.0.0.alpha application starting in development on http://localhost:3000
=> Run `rails server -h` for more startup options
=> Ctrl-C to shutdown server
[2015-09-15 22:20:37] INFO  WEBrick 1.3.1
[2015-09-15 22:20:37] INFO  ruby 2.2.2 (2015-04-13) [x86_64-darwin14]
[2015-09-15 22:20:37] INFO  WEBrick::HTTPServer#start: pid=69775 port=3000
DEPRECATION WARNING: before_filter is deprecated and will be removed in Rails 5.1. Use before_action instead. (called from block (3 levels) in <class:Engine> at /Users/manikandanviswanathan/.rvm/gems/ruby-2.2.2@Rails5/gems/turbolinks-2.5.3/lib/turbolinks.rb:14)
DEPRECATION WARNING: after_filter is deprecated and will be removed in Rails 5.1. Use after_action instead. (called from block (3 levels) in <class:Engine> at /Users/manikandanviswanathan/.rvm/gems/ruby-2.2.2@Rails5/gems/turbolinks-2.5.3/lib/turbolinks.rb:15)


Started GET "/" for ::1 at 2015-09-15 22:20:39 -0700
```
not sure what is the exact issue.

**Comment by adrianmacneil** [comment]
Fyi.. there is no such thing as "Rails 5.0.0 alpha", you're just loading the latest in-development code from github. It's fairly likely that you will run into errors, so unless you want to debug them yourself I'd highly recommend starting with the latest official release (rails 4.2.4) instead of using the bleeding edge code.

Rails 5 will be out soon enough... :)

**Comment by manivi** [comment]
@adrianmacneil oh ! I was following a tutorial, it said alpha version - my bad .. Yes currently I have switched to official release 4.2.4 ! 
Thanks !

**Comment by rejeep** [comment]
I'm actually having the exact same issue with `5.0.0.beta1`. Any ideas?

**Comment by rafaelfranca** [comment]
Can you please provide a sample application that reproduces the error?

**Comment by rejeep** [comment]
It's a private app and I don't have permissions to invite you I'm afraid. But I'm happy to find the issue myself if you would give me some suggestions where to start as the logs say nothing.
