### ISSUE TITLE
rake assets:precompile does not replace files whose permissions have changed

### ISSUE THREAD

**Issue by trevorfrese** [rails/rails#21656]
Steps to reproduce: 
> touch assets/blah.txt 
> chmod 600 assets/blah.txt
> rake assets:precompile
Check public/assets for permissions on blah.txt 
> chmod 644 assets/blah.txt
> rake assets:precompile
Verify that public/assets permissions on blah.txt have not changed

Is rake assets:precompile not supposed to replace files when the permissions change? Is this an intentional design decision? And if so, can you explain why? 

Thanks!

**Comment by schneems** [comment]
Can you give me an app that reproduces the behavior using the latest released version of rails?

Sprockets uses mtime to determine when assets have changed, I would assume that chmod would change a file's mtime.

**Comment by trevorfrese** [comment]
Both of the rails apps I'm working on are private apps. Should I create an app with rails 4 to prove it? 

But on a side note, I just tested in terminal on an OS X Mac that using chmod does not change a file's modified time. Is this machine specific? Perhaps on linux distr's chmod changes modified time, but on OS X it doesn't appear to. 
![tfrese_ _bash_ _80x24_and_sessions_controller_test_rb_-_web_-____invoca_web_](https://cloud.githubusercontent.com/assets/1146935/9942368/842ec0f0-5d2f-11e5-82e8-de9232cb6794.png)

**Comment by al2o3cr** [comment]
Changing a file's permissions with `chmod` is going to alter the ctime, but not the mtime:

http://www.unix.com/tips-and-tutorials/20526-mtime-ctime-atime.html

Unless you've aliased `ls` to already include `-c`, you can see the difference with `ls -l` (shows mtime) vs `ls -lc` (shows ctime).

**Comment by trevorfrese** [comment]
So then according to what @al2o3cr  is saying, shouldn't `precompile` use a files ctime, instead of the mtime, to determine when assets have changed?

**Comment by rafaelfranca** [comment]
This issue was moved to rails/sprockets#137
