### ISSUE TITLE
Doesn't work pluralization with I18n::Backend::KeyValue as i18n backend with disabled subtrees.

### ISSUE THREAD

**Issue by Galathius** [rails/rails#21655]
I can't enable pluralization with Redis as I18n backend when subtrees is disabled.
I have:

config/initializers/i18n_backend.rb:

    I18n.backend = I18n::Backend::Chain.new(
        I18n::Backend::KeyValue.new(Redis.new, false),
        I18n.backend
    )

seed.rb:

    I18n.backend.store_translations(:ru,
      translation: {
        one: 'one %{count}',
        many: 'many %{count}'
      }
    )

When I try execute:

    I18n.t('translation', count: 1)

I get:

    translation missing: "ru.translation"

**Comment by perfectritone** [comment]
Are you running Redis locally on port 6379?

**Comment by rafaelfranca** [comment]
This is not related to Rails but to I18n itself. Mind to open an issue there?
