### ISSUE TITLE
ActiveSupport::TimeWithZone slowness due to reliance on method_missing

### ISSUE THREAD

**Issue by ajvondrak** [rails/rails#21657]
Recently I refactored some data validation in my app that went from checking `String#blank?` before a timestamp was parsed to checking `ActiveSupport::TimeWithZone#blank?` after a timestamp was parsed. This was happening for a lot of timestamps per request.

So of course, I only noticed that this change really mattered when my app's performance slowed to a crawl! With some profiling, I discovered that `ActiveSupport::TimeWithZone` appears to rely heavily on `method_missing`. While `method_missing` has enough of a reputation to warrant putting the "slow" stamp on it out the gate, I did take the time to produce a minimal benchmark that shows off this issue: https://gist.github.com/ajvondrak/50d495bdfb96a2976256

Spoiler:

```
       user     system      total        real
String#blank?  4.610000   0.020000   4.630000 (  4.632452)
Time#blank?  1.770000   0.000000   1.770000 (  1.771400)
ActiveSupport::TimeWithZone#blank?  5.860000   0.020000   5.880000 (  5.888176)
```

Presumably, this slowness I experienced with `#blank?` extends to *any other* method, due to the use of `method_missing`. Otherwise, the fix would simply be to slap a `def blank?; ... end` on `ActiveSupport::TimeWithZone`. Is there any good way to refactor `ActiveSupport::TimeWithZone` away from `method_missing`, towards something more performant?

**Comment by bwheeler96** [comment]
:+1:

**Comment by ajvondrak** [comment]
I already realize I probably misspoke: the majority of the trace is in `ActiveSupport::TimeWithZone#respond_to?` & `ActiveSupport::TimeWithZone#respond_to_missing?`, and `#respond_to?` is called from `Object#blank?`. So maybe it does have a little to do with `#blank?`. All the same...

**Comment by findchris** [comment]
Nice sleuthing.  

I suppose this hasn't been an issue for many people simply because it would go unnoticed unless one was calling `TimeWithZone#blank?` many times within a request.  

Nonetheless, this is a pretty bad performance issue :+1: (and one that is not currently resolved with the `fast_blank` gem :wink:).

**Comment by ajvondrak** [comment]
@findchris Went ahead and added benchmarks using @SamSaffron's `fast_blank` gem to my gist, for comparison.

```
       user     system      total        real
String#blank?  4.600000   0.020000   4.620000 (  4.631222)
String#blank? (fast_blank)  0.850000   0.000000   0.850000 (  0.850358)
Time#blank?  1.730000   0.010000   1.740000 (  1.742615)
ActiveSupport::TimeWithZone#blank?  6.000000   0.020000   6.020000 (  6.020612)
```

Yowza!

**Comment by ajvondrak** [comment]
More benchmark data in the gist comparing `Time.now` vs `Time.current`:
```
       user     system      total        real
String#blank?  4.900000   0.030000   4.930000 (  4.976133)
String#blank? (fast_blank)  0.840000   0.000000   0.840000 (  0.848890)
Time#blank?  1.800000   0.010000   1.810000 (  1.806959)
ActiveSupport::TimeWithZone#blank?  6.130000   0.040000   6.170000 (  6.214902)
Time.current (no zone set)  5.970000   0.150000   6.120000 (  6.169529)
Time.current (zone set) 30.990000   0.200000  31.190000 ( 31.380357)
Time.now  4.590000   0.140000   4.730000 (  4.783195)
```

Don't think it's quite related to the same reasons for slowness here, other than `in_time_zone` being called. But still interesting that using `Time.current` is 5-6x slower.

**Comment by SamSaffron** [comment]
Hmmm, what is a blank time even? does one exist? can you simply monkey patch a return false there and be done? 

I am open for fast blank to monkey in a few return falses throughout to resolve this.

**Comment by ajvondrak** [comment]
@SamSaffron Thanks for chiming in! Yeah, that sounds about right. `ActiveSupport::TimeWithZone#blank?` resolves to just `Object#blank?`, which is defined as

```ruby
def blank?
  respond_to?(:empty?) ? !!empty? : !self
end
```

That *should* be returning `false` for dates/times of any sort, as far as I can tell.

You might still reasonably expect to be calling `ActiveSupport::TimeWithZone#blank?` in a code base if you're doing something like `timestamp.blank?` where `timestamp` may be `nil` or a properly-instantiated `ActiveSupport::TimeWithZone`. (Fun trivia about my refactoring story: this wasn't the case for me, so my refactoring was just wrong. :P)

I noticed that `Time.current` was similarly slow, but it seems to be for different reasons (seems to be spending its time in `Time.find_zone!`). So, maybe patching `#blank?` is enough for my particular use case, but if there are easy ways to optimize time zone code as a whole, those would be more worthwhile.

**Comment by findchris** [comment]
Thanks for the quick turnaround @pixeltrix :clap:
