### ISSUE TITLE
ActiveRecord::FinderMethods does not work as expected with a UUID as the primary key

### ISSUE THREAD

**Issue by marcgreenstock** [rails/rails#21663]
[ActiveRecord::FinderMethods](http://api.rubyonrails.org/classes/ActiveRecord/FinderMethods.html) uses the `primary_key` to order the results. This doesn't work as expected when using a UUID as the primary key.

I have thought of a potential workaround, but this involves a settable attribute on the class to define what column should be used, something like:

```ruby
module ActiveRecord
  module FinderMethods
    attr_accessor :finder_column

    def find_nth_with_limit(offset, limit)
      relation = if order_values.empty? && (finder_column || primary_key)
        order(arel_table[finder_column || primary_key].asc)
      else
        self
      end
     
      relation = relation.offset(offset) unless offset.zero?
      relation.limit(limit).to_a
    end
  end
end
```

If this is something worth considering I will be happy to make a pull request.

**Comment by al2o3cr** [comment]
If you want a different order of results from (say) `find_nth`, call it on a Relation with the desired order.

If you *always* want results for a particular model in a different order, consider `default_scope`. 

The fallback to `primary_key` is used in `find_nth_with_limit` because with no `ORDER BY` clause some databases very-literally-but-still-correctly interpret the SQL standard as meaning they can return any matching records - so, for instance, they could return the SAME set of records for different offset values.

**Comment by marcgreenstock** [comment]
@al2o3cr assigning a default scope with explicit intention of enabling correct behaviour of the FinderMethods has the side-effect adding the scope to all select queries. It's my opinion the default order should be configureable if no order is provided when using FinderMethods.

After thought, I think having something like `default_finder_methods_scope` (working title) would be better than simply using an attribute. If no order is provided this method is called. By default it is defined with `order(arel_table[primary_key].asc)`.

**Comment by al2o3cr** [comment]
YMMV; I'd argue in the general case that if there's an ordering of the records that is natural enough that `SomeModel.first(5)` should use that order then it's pretty likely that's the desired order for most contexts (`SELECT`, etc).

**Comment by jeremy** [comment]
+1 to the ability to provide an alternative "natural" ordering. That's an elegant alternative to `default_scope` which applies everywhere, even unordered PK lookups and joins, causing needlessly poor query plans.

Nice ripple effects in our other ordering finders, too: #21695.

**Comment by jeremy** [comment]
Moving to the PR. Thanks @marcgreenstock!
