### ISSUE TITLE
4.2 regression: inverse_of no longer works for through associations

### ISSUE THREAD

**Issue by al2o3cr** [rails/rails#21692]
Executable test case: https://gist.github.com/al2o3cr/86ec767b9140729f86fa

Between 4.1 and 4.2, a change was made that caused the `inverse_of` option for `has_many :through` associations to break. The relevant part appears to be in f8d2899d12d59360f29c5eb6a1b1a8fe4ec82ca0, where the base class of `ThroughAssociation` was changed to `AbstractReflection` and methods that were previously inherited from `AssociationReflection` (in particular, `check_validity_of_inverse!` and `inverse_of`) were instead delegated to the `ThroughAssociation`s `delegate_reflection`.

This causes a failure, since `delegate_association` does not have the correct `klass`, etc to resolve the association name passed in `inverse_of`.

While `inverse_of` is only used by ActiveRecord internals for `has_many`/`belongs_to` pairs, it has been supported for `through` associations since it was originally added. The call to `check_validity_of_inverse!` dates all the way back to https://github.com/rails/rails/commit/ccea98389abbf150b886c9f964b1def47f00f237#diff-1663e5f930ac83fef235d7e2aa5edf65R323 where it was introduced in 2009. At a minimum, the functionality should be reinstated for subsequent 4.2.x releases as its accidental removal is a breaking change to the API.

Going forward, I believe this option should be supported even though AR does not make use of it internally. If it isn't, then support for it should be more clearly removed (deprecation warning in 4.2 / runtime error in master).

**Comment by jeremy** [comment]
?r @tenderlove

**Comment by tenderlove** [comment]
@al2o3cr thanks for the test case, I'll take a look!

**Comment by eileencodes** [comment]
Thanks @al2o3cr! :smile:

**Comment by rafaelfranca** [comment]
@eileencodes could you backport the fix to 4-2-stable?

**Comment by eileencodes** [comment]
Done! Backported at 4686258. :+1:
