### ISSUE TITLE
strip-tags regression in Rails 4.2.4

### ISSUE THREAD

**Issue by tjchambers** [rails/rails#21708]
Rails 4.2.1

```
2.2.0 :001 > include ActionView::Helpers::SanitizeHelper
 => Object
2.2.0 :002 > strip_tags('&lt;<title>&gt;')
 => "&lt;&gt;"
```

Rails 4.2.4

```
2.2.0 :004 > include ActionView::Helpers::SanitizeHelper
 => Object
2.2.0 :006 > strip_tags('&lt;<title>&gt;')
 => "<>"
```

Therefore strip_tags is NOW in Rails 4.2.4 also translating text as well as stripping out tags. The lt; and gt; are TEXT and should be left alone.
 
I have not been able to find anything in the change log regarding this FUNCTIONAL change. Why was it not noted?
 
From the 4.2.4 documentation on sanitization:

```
Please note that sanitizing user-provided text does not guarantee that the resulting markup is valid or even well-formed. For example, the output may still contain unescaped characters like <, >, or &.
```

Note the reference to &

**Comment by rafaelfranca** [comment]
This is a dup of https://github.com/rails/rails-html-sanitizer/issues/44
