### ISSUE TITLE
Should we consider deprecating `Request#xhr?`

### ISSUE THREAD

**Issue by sgrif** [rails/rails#21709]
I noticed today in an app that a request would work when made with `$.ajax`, but not when using `fetch` (this was during a debugging session in the console). It ultimately turned out to be because there was a branch in a `before_filter` which was using `request.xhr?`, a.k.a. "Is `X-Requested-With` set", a.k.a. "is the user using jQuery"?

I think we should consider deprecating this method. We're at the point where jQuery can no longer be assumed to be the thing developers are using, the whole idea behind `X-Requested-With` has proven to be a bad idea, and there is no reasonable implementation we can use to bring this method up to date.

Considering that this method is no longer able to be correct in a large number of cases, and most of the valid use cases have been replaced by more secure alternatives (such as CORS), I think we should consider deprecating this method in Rails 5.0.

**Comment by tenderlove** [comment]
We're not using it at work FWIW.

**Comment by jeremy** [comment]
The presence of `X-Requested-With` became a de facto standard to communicate that the request is a same-origin `XMLHttpRequest`, not a `<script>` tag or cross-origin XHR. So it acts as a reliable guard against cross-site request forgery. This has been far from a bad idea.

Could you be more specific about what is "no longer able to be correct in a large number of cases?" And what are the "valid use cases" (with more secure alternatives)? CORS is the opposite of this: for enabling cross-origin requests, not for ensuring same-origin requests.

**Comment by sgrif** [comment]
> The presence of X-Requested-With became a de facto standard to communicate that the request is a same-origin XMLHttpRequest

`XMLHttpRequest` doesn't add the `X-Requested-With` header. jQuery does.

> not a <script> tag or cross-origin XHR.

Not a script tag, sure. There's absolutely no reason to trust the presence of that header as a same-origin XHR request though. Using it that way is very much a bad idea (and is what I was referring to)

> Could you be more specific about what is "no longer able to be correct in a large number of cases?"

Any usage of `XMLHttpRequest` or `fetch`, which is intended to replace it. (Also as an aside, I find the notion of needing to write `fetch(url, { headers: { "X-Requested-With": "XMLHttpRequest" }})` hilariously reminiscent of modern `User-Agent` strings.

I don't have a list of "here are web frameworks that don't use jQuery and don't manually set that header", but I think that fact that the canonical way to send an ajax request (`fetch`) not sending this header is more than enough.

> And what are the "valid use cases" (with more secure alternatives)?

The majority of uses that I've seen historically have been to determine if a request is same-domain or not, often to add additional auth requirements in the latter case. I don't have a canonical source, but my understanding is that this was the original intention of that header, as well.

I would also be curious what valid use cases you do see, which aren't security related, and aren't easily handled otherwise (by things like the content-type header)

**Comment by sgrif** [comment]
Github appears to have lost half my comment... I will write it up again.

**Comment by sgrif** [comment]
Ah there it is... (see edits)

**Comment by rafaelfranca** [comment]
> Not a script tag, sure. There's absolutely no reason to trust the presence of that header as a same-origin XHR request though. Using it that way is very much a bad idea (and is what I was referring to)

So should not we just change the implementation of `xhr?` to not rely on `X-Requested-With`?

**Comment by sgrif** [comment]
There is no implementation to replace it with. A request made with `fetch` from JS is pretty much indistinguishable from a CURL request

**Comment by sgrif** [comment]
After some discussion in campfire, the answer to this question is "No."

**Comment by mikeycgto** [comment]
FWIW, I just got tripped up by this when using `fetch()`. CSRF Exceptions are raised because `verify_same_origin_request` calls `non_xhr_javascript_response?` which checks `request.xhr?`.
