### ISSUE TITLE
New Rails/Ruby App Server Crashing

### ISSUE THREAD

**Issue by dezguy** [rails/rails#21719]
I installed the latest Ruby / Rails and I can't get the rails server to start. I haven't done any programming or addition of my own code. This is straight from the standard install.

Operating System: Yosemite
rvm use ruby-2.2.1
Using /Users/mike/.rvm/gems/ruby-2.2.1
Rails 4.2.4
ruby 2.2.1p85 (2015-02-26 revision 49769) [x86_64-darwin14]

[2015-09-22 10:48:34] INFO  WEBrick 1.3.1
[2015-09-22 10:48:34] INFO  ruby 2.2.1 (2015-02-26) [x86_64-darwin14]
[2015-09-22 10:48:34] INFO  WEBrick::HTTPServer#start: pid=79178 port=3000

I receive the following error after hitting localhost:3000:

---

undefined method `tr' for nil:NilClass

Extracted source (around line #37): 
          raise "Database URL cannot be empty" if url.blank?
          @uri     = uri_parser.parse(url)
          @adapter = @uri.scheme.tr('-', '_')
          @adapter = "postgresql" if @adapter == "postgres"

          if @uri.opaque

----

activerecord (4.2.4) lib/active_record/connection_adapters/connection_specification.rb:37:in `initialize'
activerecord (4.2.4) lib/active_record/connection_adapters/connection_specification.rb:270:in `new'
activerecord (4.2.4) lib/active_record/connection_adapters/connection_specification.rb:270:in `resolve_url_connection'
activerecord (4.2.4) lib/active_record/connection_adapters/connection_specification.rb:258:in `resolve_hash_connection'
activerecord (4.2.4) lib/active_record/connection_adapters/connection_specification.rb:215:in `resolve_connection'
activerecord (4.2.4) lib/active_record/connection_adapters/connection_specification.rb:139:in `resolve'
activerecord (4.2.4) lib/active_record/connection_adapters/connection_specification.rb:151:in `block in resolve_all'
activerecord (4.2.4) lib/active_record/connection_adapters/connection_specification.rb:150:in `each'
activerecord (4.2.4) lib/active_record/connection_adapters/connection_specification.rb:150:in `resolve_all'
activerecord (4.2.4) lib/active_record/connection_handling.rb:69:in `resolve'
activerecord (4.2.4) lib/active_record/core.rb:46:in `configurations='
activerecord (4.2.4) lib/active_record/core.rb:48:in `block in <module:Core>'
activesupport (4.2.4) lib/active_support/concern.rb:120:in `class_eval'
activesupport (4.2.4) lib/active_support/concern.rb:120:in `append_features'
activerecord (4.2.4) lib/active_record/base.rb:284:in `include'
activerecord (4.2.4) lib/active_record/base.rb:284:in `<class:Base>'
activerecord (4.2.4) lib/active_record/base.rb:269:in `<module:ActiveRecord>'
activerecord (4.2.4) lib/active_record/base.rb:26:in `<top (required)>'
activerecord (4.2.4) lib/active_record/migration.rb:383:in `connection'
activerecord (4.2.4) lib/active_record/migration.rb:370:in `call'
actionpack (4.2.4) lib/action_dispatch/middleware/callbacks.rb:29:in `block in call'
activesupport (4.2.4) lib/active_support/callbacks.rb:88:in `__run_callbacks__'
activesupport (4.2.4) lib/active_support/callbacks.rb:778:in `_run_call_callbacks'
activesupport (4.2.4) lib/active_support/callbacks.rb:81:in `run_callbacks'
actionpack (4.2.4) lib/action_dispatch/middleware/callbacks.rb:27:in `call'
actionpack (4.2.4) lib/action_dispatch/middleware/reloader.rb:73:in `call'
actionpack (4.2.4) lib/action_dispatch/middleware/remote_ip.rb:78:in `call'
actionpack (4.2.4) lib/action_dispatch/middleware/debug_exceptions.rb:17:in `call'
web-console (2.2.1) lib/web_console/middleware.rb:39:in `call'
actionpack (4.2.4) lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
railties (4.2.4) lib/rails/rack/logger.rb:38:in `call_app'
railties (4.2.4) lib/rails/rack/logger.rb:20:in `block in call'
activesupport (4.2.4) lib/active_support/tagged_logging.rb:68:in `block in tagged'
activesupport (4.2.4) lib/active_support/tagged_logging.rb:26:in `tagged'
activesupport (4.2.4) lib/active_support/tagged_logging.rb:68:in `tagged'
railties (4.2.4) lib/rails/rack/logger.rb:20:in `call'
actionpack (4.2.4) lib/action_dispatch/middleware/request_id.rb:21:in `call'
rack (1.6.4) lib/rack/methodoverride.rb:22:in `call'
rack (1.6.4) lib/rack/runtime.rb:18:in `call'
activesupport (4.2.4) lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
rack (1.6.4) lib/rack/lock.rb:17:in `call'
actionpack (4.2.4) lib/action_dispatch/middleware/static.rb:116:in `call'
rack (1.6.4) lib/rack/sendfile.rb:113:in `call'
railties (4.2.4) lib/rails/engine.rb:518:in `call'
railties (4.2.4) lib/rails/application.rb:165:in `call'
rack (1.6.4) lib/rack/lock.rb:17:in `call'
rack (1.6.4) lib/rack/content_length.rb:15:in `call'
rack (1.6.4) lib/rack/handler/webrick.rb:88:in `service'
/Users/mike/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/webrick/httpserver.rb:138:in `service'
/Users/mike/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/webrick/httpserver.rb:94:in `run'
/Users/mike/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/webrick/server.rb:294:in `block in start_thread'

**Comment by rafaelfranca** [comment]
What is the return of `echo $DATABASE_URL`?

**Comment by dezguy** [comment]
echo $DATABASE_URL?
local_database?

**Comment by dezguy** [comment]
It's setup with the stock configuration:

development:
  <<: *default
  database: db/development.sqlite3

**Comment by rafaelfranca** [comment]
Right. But looks like `DATABASE_URL` environment variable is set. This is why it is trying to parse a URL. It should not be set, of if it need to be set you should provide a valid URL.

**Comment by dezguy** [comment]
Ok, yeah, I removed the DATABASE_URL from my bash_profile and it now starts fine. Weird, I'm not sure why that was set. 

Everything is running! Thanks or the help :)

**Comment by rafaelfranca** [comment]
You are welcome
