### ISSUE TITLE
Flagging has_secure_token naming concern (like html_safe)

### ISSUE THREAD

**Issue by eliotsykes** [rails/rails#21716]
+1 for introduction of the functionality of `has_secure_token`, however I think the name may generate over-confidence in what it is doing behind the scenes. It may lead to potential vulnerabilities in apps. 

(See how the name `.html_safe` is sometimes mistaken for doing something to improve the security of an application.)

This name, when I first read it, I wrongly assumed it was hashing the stored value as `has_secure_password` does.

Its generating a token using `SecureRandom`, which explains the name, though perhaps there's no need for the name to reveal this detail of the underlying implementation.

Would it be possible to consider renaming `has_secure_token` to something that explains what it does without including `secure` or similar as part of the name?

**Comment by matthewd** [comment]
This was discussed at the time: https://github.com/rails/rails/pull/18217#issuecomment-69435136

**Comment by eliotsykes** [comment]
Thanks @matthewd, hopefully this is revisited before Rails 5.0 makes that API official. I'd be happy to submit a PR with `has_secure_token` renamed to `has_token` if it'd help.
