### ISSUE TITLE
When using a custom foreign_key/table_name, the parent record is not touched when updating the child

### ISSUE THREAD

**Issue by jlecour** [rails/rails#21713]
Hi,

I have a `Post` model, using a custom table name (`my_posts` instead of `posts`) and a related `Comment` model, with an `has_many`/`belongs_to` relation.

Even with `touch: true` in the `belongs_to` class macro, the parent `Post` is not touched when the `Comment` is touched.

It works fine with a conventional table name (and foreign key).

Here is a reproductible test : 

```ruby
begin
  require 'bundler/inline'
rescue LoadError => e
  $stderr.puts 'Bundler version 1.10 or later is required. Please update your Bundler'
  raise e
end

gemfile(true) do
  source 'https://rubygems.org'
  # Activate the gem you are reporting the issue against.
  gem 'activerecord', '4.2.4'
  gem 'sqlite3'
end

require 'active_record'
require 'minitest/autorun'
require 'logger'

# Ensure backward compatibility with Minitest 4
Minitest::Test = MiniTest::Unit::TestCase unless defined?(Minitest::Test)

# This connection will do for database-independent bug reports.
ActiveRecord::Base.establish_connection(adapter: 'sqlite3', database: ':memory:')
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do

  ## Conventional table name and foreign key
  # create_table :posts, force: true do |t|
  #   t.timestamps null: false
  # end
  #
  # create_table :comments, force: true do |t|
  #   t.integer :post_id
  #   t.timestamps null: false
  # end
  
  ## Custom table name and foreign key
  create_table :my_posts, force: true do |t|
    t.timestamps null: false
  end

  create_table :comments, force: true do |t|
    t.integer :my_post_id
    t.timestamps null: false
  end
end

class Post < ActiveRecord::Base
  ## Conventional table name and foreign key
  # has_many :comments
  
  ## Custom table name and foreign key
  self.table_name = "my_posts"

  has_many :comments, :foreign_key => 'my_post_id'
end

class Comment < ActiveRecord::Base
  belongs_to :post, touch: true
end

class BugTest < Minitest::Test
  def test_touch_belongs_to_on_create
    post = Post.create!
    assert_equal post.updated_at, post.created_at
    
    sleep(1)
    
    post.comments << Comment.create!

    assert_operator post.updated_at, :>, post.created_at
  end
  def test_touch_belongs_to_on_update
    post = Post.create!
    post.comments << Comment.create!
    
    original_updated_at = post.updated_at
    
    sleep(1)
    
    post.comments.first.touch

    assert_operator post.updated_at, :>, original_updated_at
  end
end
```

The test is not very idiomatic and the `sleep` is a smell, but it shows the problem.

Again, if I use `posts` as a table name and the default foreign key, the tests pass.
I've commented the 2 examples to facilitate the reproduction of both situations.

**Comment by al2o3cr** [comment]
Your test case, as far as I can tell, needs to call `post.reload` before checking `updated_at`, or set `inverse_of` on the associations so that `post.comments.first.post` actually returns `post`.

More importantly, your `belongs_to` is missing the `foreign_key` option, so code like `Comment.first.post` will always return `nil`. Adding `foreign_key: 'my_post_id'` to `Comment` and reloading the `Post` models (or adding `inverse_of` to the associations) makes this test pass.

**Comment by jlecour** [comment]
Oh man, I feel so dumb!

Of course my `belongs_to` needed the `:foreign_key`.

As of the `inverse_of`, I've never fully understood its use case. It seems to be useful for validations, but is not needed in my specific case.

Thanks for the help and sorry for the dumb question.
