### ISSUE TITLE
AR: Concurrent connections during testing, monkey patch required

### ISSUE THREAD

**Issue by onebree** [rails/rails#21734]
**Rails 4.2.0, Ruby 1.9.3, RSpec 3.1.0, mysql2 0.3.17**

In reference to this issue/comment: https://github.com/brianmario/mysql2/issues/587#issuecomment-142391980

**TL;DR** - Without a monkey-patch, we are unable to run tests properly (same gems/ruby, different servers). The first scenario of every feature spec fails. RSpec/Capybara said it's because page elements did not display, but I am always emailed the same type of mesage and backtrace. (The mysql2 issue includes sample rspec and backtrace output

**Emailed error**
```
A Mysql2::Error occurred in login#auth:
  This connection is in use by: #<Thread:0x00000001168fe0 sleep>
```

**Monkey patch in AR**
```ruby
# v4.2.0/activerecord/lib/active_record/connection_adapters/abstract_mysql_adapter.rb

# Original
def execute(sql, name = nil)
  log(sql, name) { @connection.query(sql) }
end

# Monkey-patch
SEMAPHORE = Mutex.new
def execute(sql, name = nil)
  begin
    raise 'Debugging'
  rescue => e
    SEMAPHORE.synchronize { log(sql, name) { @connection.query(sql) } }
  end
end
```

I am not sure if this is a bug exactly. If not, any advice on how to handle this, without a monkey patch?

**Comment by rafaelfranca** [comment]
Have you checked if this is not related to the shared connection patch that you have? How can we reproduce this problem?

**Comment by onebree** [comment]
I may not have been clear... The error occurs with stock active record. We are no longer emailed the mysql2 error once we put the monkey patch into play

**Comment by rafaelfranca** [comment]
I see. Do you know how to reproduce this error? Because without a way to reproduce it will be hard to fix. The only reason that I can think to this fail is if two threads are sharing the same connection and that is not a supported use case.

@tenderlove @matthewd do you have any ideas?

**Comment by onebree** [comment]
I am not sure how to reproduce. It may just be an environment issue, but I know that different servers can have the same error. (With each server accessing a different database)

**Comment by thedarkone** [comment]
From the looks of it, you're using the same connection from multiple threads, this is not allowed. You should investigate how come multiple threads get the same conn? Do you spin up multiple threads? How do they get their db connections?

**Comment by matthewd** [comment]
Are you using AC::Live?

**Comment by onebree** [comment]
Is that a gem? I do not think we call `AC::Live` anywhere, but I will check in the morning.

**Comment by zerothabhishek** [comment]
Hello @onebree. From the first comment of the other thread (mysql2), its clear that connection sharing was indeed in use. When we use Capybara for tests, it starts a server in a separate thread. That causes some issues with database-cleaner. What you initially is a well known but unreliable solution for that. And as others noted, connection sharing is not supported by ActiveRecord. The monkey patch applied later works for most people (Check the discussion in this [gist](https://gist.github.com/josevalim/470808))

Take a look at [this post by Avdi Grimm](http://devblog.avdi.org/2012/08/31/configuring-database_cleaner-with-rails-rspec-capybara-and-selenium/) for a detailed analysis and better solution.

**Comment by onebree** [comment]
@zerothabhishek We have since removed database-cleaner. The monkey-patch in your gist we DO use -- it's enabled in the spring initializer (`config/spring.rb`)

```ruby
Spring.after_fork do
  if Rails.env == "test"
    class ActiveRecord::Base
      mattr_accessor :shared_connection
      @@shared_connection = nil
      def self.connection
        @@shared_connection || ConnectionPool::Wrapper.new(size: 1) { retrieve_connection }
      end
    end
    ActiveRecord::Base.shared_connection = ActiveRecord::Base.connection

    RSpec.configure do |config|
      srand; config.seed = srand % 0xFFFF
    end
  end
end
```

**Comment by matthewd** [comment]
Ah, that'll do it.

Yes, if you monkey-patch AR to do an unsupported thing, it may then misbehave.

**Comment by onebree** [comment]
Could I ask why this was closed? we need both monkey patches to get threading to work properly. Do you think Capybara is the culprit?

**Comment by matthewd** [comment]
@onebree [this one](https://github.com/rails/rails/issues/21734#issuecomment-142910934) is *causing* the problem. If you don't do that, you won't get the described error.

**Comment by onebree** [comment]
Okay, we kept that patch in the code, because we used to need it with SPork (Rails 3, RSpec 2)... I will see how everything goes without any MP and get back to you.
