### ISSUE TITLE
ActiveRecord not compatible with mysql2 0.4?

### ISSUE THREAD

**Issue by jkxyz** [rails/rails#21733]
Running `rails new -d mysql` installs the latest version of the `mysql2` gem by default. But this requires manually downgrading the gem to 0.3.20, whilst the latest version is 0.4.1. Should the new project generator be updated to use this version of the gem?

**Comment by Amit-Thawait** [comment]
This issue has been backported in the latest `4-2-stable` branch https://github.com/rails/rails/tree/4-2-stable

Probably you are using rails <= 4.2.4

Reference link : https://github.com/rails/rails/issues/21544

**Comment by jkxyz** [comment]
Thanks. I'm not using a checkout version at the moment. For the time being I've just tagged the gem at 0.3.20. I'll keep an eye on the next updates to see if it needs to be updated.
