### ISSUE TITLE
Cannot override find method of associations

### ISSUE THREAD

**Issue by SebastianVomMeer** [rails/rails#21731]
I'm looking for a way to decode a ID inside a ActiveRecord model's find method, e.g.:

    class Model < ActiveRecord::Base
      def self.find(*ids)
        super(decode_ids(*ids))
      end
      # ...
    end

This works fine for `Model.find(encoded_id)`. However, in a has-many-association the custom implementation of find is ignored:

    parent.models.find(encoded_id)
    ActiveRecord::RecordNotFound: Couldn't find Model with 'id'=237842376 [WHERE "models"."parent_id" = ?]

Is this intended behavior? If yes, is there a better way to inject this auto-decode feature?

**Comment by rafaelfranca** [comment]
Yes, it is the intended behavior. The object that you are accessing on a association is not the model itself but the association proxy. You will need to override the method on that object too.
