### ISSUE TITLE
rake issue

### ISSUE THREAD

**Issue by GreyValleys** [rails/rails#21741]
# database.yml;

development:
adapter: mysql2
encoding: utf8
database: simple_cms_development
pool: 5
username: simple_cms
password: xxxxxx
host: localhost

the other's are basically as follows, i have noticed that the default database i created never put the socket: under host?
# gemfile:

source 'https://rubygems.org'

#Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '4.0.0'

#Use mysql as the database for Active Record
gem 'mysql2', '~> 0.3.18'

ruby v 2.0.0p647
# Issue:

C:\Users\nickm\sites\simple_cms>rake -v --trace
rake aborted!
LoadError: cannot load such file -- msql/all
C:/Users/nickm/sites/simple_cms/config/application.rb:4:in require' C:/Users/nickm/sites/simple_cms/config/application.rb:4:in'
C:/Ruby200-x64/lib/ruby/site_ruby/2.0.0/rubygems/core_ext/kernel_require.rb:54:in require' C:/Ruby200-x64/lib/ruby/site_ruby/2.0.0/rubygems/core_ext/kernel_require.rb:54:inrequire'
C:/Users/nickm/sites/simple_cms/Rakefile:4:in <top (required)>' C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/rake-10.4.2/lib/rake/rake_module.rb:28:inload'
C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/rake-10.4.2/lib/rake/rake_module.rb:28:in load_rakefile' C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/rake-10.4.2/lib/rake/application.rb:689:inraw_load_rakefile'
C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/rake-10.4.2/lib/rake/application.rb:94:in block in load_rakefile' C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/rake-10.4.2/lib/rake/application.rb:176:instandard_exception_handling'
C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/rake-10.4.2/lib/rake/application.rb:93:in load_rakefile' C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/rake-10.4.2/lib/rake/application.rb:77:inblock in run'
C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/rake-10.4.2/lib/rake/application.rb:176:in standard_exception_handling' C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/rake-10.4.2/lib/rake/application.rb:75:inrun'
C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/rake-10.4.2/bin/rake:33:in <top (required)>' C:/Ruby200-x64/bin/rake:23:inload'
C:/Ruby200-x64/bin/rake:23:in `
'
_____________________________________________________________________
I've been at this for awhile... I'm on windows 10 x64..... lost on this one, tempted to start from scratch, if that is the best way to go, could you please tell me the best way of deleting everything off the computer so i can start fresh, and then, tell me which version of ruby, rails, and mysql would work best for me, your time is greatly appreciated. Also my rake version is 10.4.2, thanks again

**Comment by rafaelfranca** [comment]
It is failling because you have `require 'msql/all'` in your `config/application.rb` and this gem is not present in your Gemfile.

**Comment by rafaelfranca** [comment]
I guess you mean `require 'rails/all'` in that line
