### ISSUE TITLE
 config.action_dispatch.x_sendfile_header = 'X-Accel-Redirect' does not do the job

### ISSUE THREAD

**Issue by ciaoben** [rails/rails#21747]
I have put this in my `development.rb`

     config.action_dispatch.x_sendfile_header = 'X-Accel-Redirect'

But when I call something like this:

    send_file path_to_file
    log response.header

It does not add the 'X-Accel-Redirect' header, so Nginx don't do the job
I am using thin server.

**Comment by kaspth** [comment]
Please use the Ruby on Rails talk mailing list or StackOverflow for questions/help, where a wider community will be able to help you. We reserve the issues tracker for bugs only. Thanks!

**Comment by ciaoben** [comment]
@kaspth to me this is a bug. In rails guide it simple says to use that line in config/development.rb (or whatever env), but It does not work.

**Comment by kaspth** [comment]
Which guide are you talking about? :smile:

**Comment by ciaoben** [comment]
The official one:
http://guides.rubyonrails.org/asset_pipeline.html#x-sendfile-headers

**Comment by kaspth** [comment]
That guide is talking about `production.rb`, and involves your Nginx setup with Thin. It could be that there's something off with that setup. So If there's a bug in Rails here, I'm sorry, but I don't see it :grin:

**Comment by kaspth** [comment]
Sorry, I forgot to mention that for us to look into this, we'd need access to an app that reproduces the problem (so we can rule out any configuration woes). So send us one and we'll take a look.

**Comment by ciaoben** [comment]
cit the guide:

"If you are upgrading an existing application and intend to use this option, take care to paste this configuration option only into production.rb and any other environments you define with production behavior (not application.rb)."

Anyway, I will try with a fresh new app and in case I see the same behaviour will link the code

**Comment by kaspth** [comment]
Cool, thanks :+1:
