### ISSUE TITLE
Rails.logger usage from initializer in development

### ISSUE THREAD

**Issue by masciugo** [rails/rails#21748]
I am trying to access and use the logger in an initializer:

    begin
      raise "REDIS_URL environment var not found" unless ENV["REDIS_URL"]
      $redis = Redis.new
      $redis.ping
      Rails.logger.info "Successfully connected to redis: #{ENV["REDIS_URL"]}" if $redis.connected?
    rescue Exception => e
      Rails.logger.warn e.message
      Rails.logger.warn 'API only mode. Request to root will not return any index.html'
    end

debugging inside the block I can access it:

    (byebug) Rails.logger
    #<ActiveSupport::Logger:0x007ffb69ef48d8>
    (byebug) Rails.logger.level
    0
    (byebug) 

but I don't see any msg in development. Is the logger supposed to be accessible but not to be used in there? Is [this](http://stackoverflow.com/questions/26377359/rails-logger-info-is-not-working-in-initializer#answer-26377540) this considered a correct solution?

(It works in production)

thank you

**Comment by kaspth** [comment]
Please use the Ruby on Rails talk mailing list or StackOverflow for questions/help, where a wider community will be able to help you. We reserve the issues tracker for bugs only. Thanks!

**Comment by masciugo** [comment]
Sorry I thought it was not the expected behaviour. I'll follow your suggestion
