### ISSUE TITLE
Mime::Type should interpret text/plain,text/html; correctly

### ISSUE THREAD

**Issue by johannesluedke** [rails/rails#21749]
Background: For a html page accessible on /  when I set the Accpet Header`curl -v -H "Accept: text/plain,text/html;" localhost:3000`, which returns a 200 OK for example for http://nginx.org, my rails 4.1 app returns a 500 error page with an Unknown Format Error. 
The base to this seems to be that 

    Mime::Type.parse("Accept: text/plain,text/html;").map(&:to_sym)
     => [nil, nil]
    Mime::Type.parse("Accept: text/plain,text/html").map(&:to_sym)
     => [nil, :html]

On the upper example it's not parsed to html.

**Comment by matthewd** [comment]
Can you point to some documentation that defines how to parse that "correctly"? [RFC 7231](https://tools.ietf.org/html/rfc7231#section-3.1.1.1) says it's malformed.

Alternatively, which broken client is sending such a header? If it's sufficiently widely deployed, we may have no choice but to accommodate it... but were that the case, I imagine it would be a more widely-known misbehaviour.

`curl -v -H "Accept: this is extremely malformed, wouldn't you say?" http://nginx.org` returns a 200, so I don't think we'll be treating that server's behaviour as normative.

**Comment by johannesluedke** [comment]
Client:
The seokicks.de engine used this header and generated a whole lot of 500 server erros. 

I thought nginx.org 200 OK would be a sign that it's widely seen as "correctly" - you showed that it doesn't have to mean anything. If RFC7231 says it's malformed, then you're right it's more about supporting malformed Acceptance Headers.

Could be a case that appears for a lot of clients, and be worth to strip the wrong `;`?

**Comment by rafaelfranca** [comment]
> Could be a case that appears for a lot of clients, and be worth to strip the wrong `;`?

I'd say not. This is the first bug report that we get and well, we should fix the client to not send malformed headers not Rails to accept malformed headers.
