### ISSUE TITLE
rake rails:update in rails5 do not create app/assets/manifest.js

### ISSUE THREAD

**Issue by mariochavez** [rails/rails#21755]
I did try Rails master to upgrade an app, everything was smooth but then when I started Rails server, I got:

```
Asset was not declared to be precompiled in production.
Add `Rails.application.config.assets.precompile += %w( application.css )` to `config/initializers/assets.rb` and restart your server
```

Looks like with sprockets 4.0 now is required to set `Rails.application.config.assets.precompile` with the list off all assets that our Rails app wil be using or have a `manifest.js` file in place - this looks like the best options -.

Would you accept a patch that will:
- Create a `manifest.js` file when `rake rails:update` is executed
- Add information on `config/initializers/assets.rb` about the need of `manifest.js`, current message says `# application.js, application.css, and all non-JS/CSS in app/assets folder are already added.` which seems to not be the case anymore.

Cheers,
Mario

**Comment by rafaelfranca** [comment]
This part is still work in progress. We don't know where the manifest file will be yet and neither what will be the upgrade path. We will fix this when we figure it out. Thanks.
