### ISSUE TITLE
ActiveRecord::Base.connection.indexes() Postgres. Does not return indexes with functions

### ISSUE THREAD

**Issue by henriqueltrindade** [rails/rails#21765]
active_record/connection_adapters/postgresql/schema_statements.rb linha 155

# Returns an array of indexes for the given table.
def indexes(table_name, name = nil)
--
--
end

#-> Line 172 -> Return indkey = 0
indkey = row[2].split(" ").map(&:to_i)  

#-> Lines 183 -> Indexes function always returns empty
column_names = columns.values_at(*indkey).compact  

1) Does not return indexes function

example
- Indexes function
CREATE INDEX ix_tabela_1 ON tabela USING btree ( date_part('year'::text, created_at ))
CREATE INDEX ix_tabela_1 ON tabela USING btree ( unaccent(name))

2) The return of indkey = 0 e column_names is empty

3) My suggestion, returns all columns separated by "|" even with indices functions

 # Returns an array of indexes for the given table.
def indexes(table_name, name = nil)
   result = query(<<-SQL, 'SCHEMA')
	SELECT distinct i.relname, d.indisunique, pg_get_indexdef(d.indexrelid),
		array_to_string
		(
		  ARRAY
		  (
		   SELECT pg_get_indexdef(d.indexrelid, k + 1, TRUE)
		   FROM generate_subscripts(d.indkey, 1) AS k ORDER BY k
		  )
		  , '|'
		) AS index_keys
   FROM pg_class t
   INNER JOIN pg_index d ON t.oid = d.indrelid
   INNER JOIN pg_class i ON d.indexrelid = i.oid
   WHERE i.relkind = 'i'
	 AND d.indisprimary = 'f'
	 AND t.relname = '#{table_name}'
	 AND i.relnamespace IN (SELECT oid FROM pg_namespace WHERE nspname = ANY (current_schemas(false)) )
   ORDER BY i.relname
  SQL

  result.map do |row|
	index_name = row[0]
	unique = row[1] == 't'
	inddef = row[2]
	column_names = row[3].split('|')

	unless column_names.empty?
	  # add info on sort order for columns (only desc order is explicitly specified, asc is the default)
	  desc_order_columns = inddef.scan(/(\w+) DESC/).flatten
	  orders = desc_order_columns.any? ? Hash[desc_order_columns.map {|order_column| [order_column, :desc]}] : {}
	  where = inddef.scan(/WHERE (.+)$/).flatten[0]
	  using = inddef.scan(/USING (.+?) /).flatten[0].to_sym

	  IndexDefinition.new(table_name, index_name, unique, column_names, [], orders, where, nil, using)
	end
  end.compact
end

Sorry if it is not a problem! What do you think?

**Comment by rafaelfranca** [comment]
Could you create a reproduction script with this template https://github.com/rails/rails/blob/master/guides/bug_report_templates/active_record_master.rb?
