### ISSUE TITLE
Nothing to with the current project, but need to contact this GitHub organisation.

### ISSUE THREAD

**Issue by ytrezq** [rails/rails#21772]
Hello, it seems some of your privates pages are public.
Interesting to know *(for example)* https://github.com/organizations/rails/teams/617 corresponds to “Rails Core Team” :)

You might want to better check what you are currently publishing.

**Comment by rafaelfranca** [comment]
Thank you for the report.

That page is not private and doesn't contains any information that is not already public (http://rubyonrails.org/core/). All teams that are public should be public so our contributors can know who is part of the teams.
