### ISSUE TITLE
Unexpected behavior of the distinct() method when chained with any ActiveRecord::Calculations method

### ISSUE THREAD

**Issue by ClaudioFloreani** [rails/rails#21799]
The `distinct()` method from **ActiveRecord::QueryMethods**, when chained with any **ActiveRecord::Calculations** method, ignores the `SELECT`-ed attributes (if any) and uses the ones in the **ActiveRecord::Calculations** method (if any) as a `DISTINCT` list inside the aggregate function. Following some examples with the `count` method, but the same behavior holds true for other calculation methods. 

```
2.2.1 > Rails.version
 => "4.2.2" 
```

---

_Count all distinct records_:

```
> Box.distinct.count
   (1.5ms)  SELECT DISTINCT COUNT(DISTINCT "boxes"."id") FROM "boxes"
 => 7 
```

**Expected behavior:**

```
SELECT DISTINCT COUNT(*) FROM "boxes"
```

---

_Count distinct 'color' attributes_:

```
> Box.select( :color ).distinct.count
   (0.9ms)  SELECT DISTINCT COUNT(DISTINCT "boxes"."color") FROM "boxes"
 => 3 
```

**Expected behavior:**

```
SELECT COUNT(DISTINCT "boxes"."color") FROM "boxes"
```

---

_Trying to count distinct 'size' attributes when only 'color' is SELECT-ed_:

```
> Box.select( :color ).distinct.count( :size )
   (0.7ms)  SELECT DISTINCT COUNT(DISTINCT "boxes"."size") FROM "boxes"
 => 4 
```

**Expected behavior**: throw some error (cannot count on `:size` if only `:color` is selected)

---

_Count records having different pairs of 'color' and 'size'_:

```
 > Box.select( :color, :size ).distinct.count
   (18.3ms)  SELECT DISTINCT COUNT(DISTINCT color, size) FROM "boxes"
PG::UndefinedFunction: ERROR:  function count(character varying, integer) does not exist
```

**Expected behavior:**

```
SELECT COUNT(DISTINCT ("boxes"."color", "boxes"."size")) FROM "boxes"
```

---

_Count records having different pairs of 'color' and 'size'_:

```
 > Box.select( :color, :size ).distinct.count( :size, :color )
   (0.9ms)  SELECT DISTINCT COUNT(DISTINCT "boxes"."size") FROM "boxes"
 => 4 
```

**Expected behavior:**

```
SELECT COUNT(DISTINCT ("boxes"."color", "boxes"."size")) FROM "boxes"
```

---

Another proof of this wrong behavior is that the followings should return the same result, but they don't:

**Right result:**

```
 > Box.select( :color, :size ).distinct.length
  Box Load (0.8ms)  SELECT DISTINCT "boxes"."color", "boxes"."size" FROM "boxes"
 => 6 
```

**Wrong result:**

```
 > Box.select( :color, :size ).distinct.pluck.length
   (0.9ms)  SELECT DISTINCT "boxes".* FROM "boxes"
 => 7 
```

**Comment by maclover7** [comment]
If this is still an issue, can you please create a reproduction script using one of the templates available [here](https://github.com/rails/rails/tree/master/guides/bug_report_templates)?
