### ISSUE TITLE
ActiveRecord::Dirty - callbacks are called before persist dirty changes

### ISSUE THREAD

**Issue by Strnadj** [rails/rails#21802]
This is bad, if you want to set a values in callbacks from some reason (for example, I am reseting cache values in after_save or arround_save callbacks). Then after **save!** nothing happens and **will_change!** has no effect..

Test example:
https://gist.github.com/Strnadj/09d0bab6df94b3e0ac9e

**Comment by al2o3cr** [comment]
https://github.com/rails/rails/issues/21442 is likely related.

**Comment by maclover7** [comment]
Can confirm this is still an issue on master.

**Comment by Strnadj** [comment]
No, unfortunately still experiencing this issue. 

viz: https://gist.github.com/Strnadj/f0b8593f0e9c7df16a6b#file-activerecord_test-rb-L43

Probably I will be able to solve this using two callbacks: after_commit and before_save...
