### ISSUE TITLE
ActiveRecord#unscope behaviours not consistent across `joins()`.

### ISSUE THREAD

**Issue by tobypinder** [rails/rails#21814]
Unscope is great for me as it provides a way of dynamically creating content based on similar queries to the "main" one on a page. However as we deployed it we noticed a couple of systemic issues with how it handles unscoping across multiple joined tables. I've [included an isolated test case gist](https://gist.github.com/tobypinder/bf2dd87524029d38589e) which highlights these problems. They persist in both the latest and github (`master` branch, `5.x` target) versions of Rails/AR but fail in subtly different ways. To reproduce the issues, try to unscope a `join()`ed column and you'll discover one of two problems.

### Nested hash where references cannot be unscoped
To rails and its internal creation of Arel nodes, `where(foo: { bar: 'baz' })` and `where('foo.bar' => 'baz')` look different. The nodes appear to be 'named' based on just the column name, meaning that any attempt to unscope `bar` would unscope ALL `bar` columns, in all tables that are part of the join.

### No column disambiguation across multiple tables
The other failure mode is more obvious, a column named `bar` that exists on table `foo` will be automatically unscoped when trying to unscope `baz.bar`. In fact, in Rails 4.2 this will produce a broken query of form `WHERE "bbb"."bar" =  AND "aaa"."bar" = 'baz'` (see test `(d)` in the Rails 4 output capture of the [test case](https://gist.github.com/tobypinder/bf2dd87524029d38589e))

## Security Considerations

While I don't think these issues have a security impact in isolation, it's possible to imagine many developers misconfiguring their applications without being aware of this behaviour. If a `User` can unscope arbitrary attributes e.g. `Thing#name` from his or her advanced search query, that could potentially silently unscope `User#name` from some access control elements of that query, leading to unintended information disclosure.

## Proposals

Either one of these two proposals should be considered in my opinion:

1) **Ensure that both nested hash based and string based column references in `where` nodes are named based on `table_name.column_name`.**

Then `#unscope` can do its unscoping based on a name that's less ambiguous and avoid unscoping unrelated columns with the same name.

2) **Thoroughly document the lack of support for joined unscoping, throwing exceptions if possible when a user tries to perform it or there are ambiguously named nodes.** 

This would entail ensuring that rails will never unscope `'bar'` if the query has both a `foo.bar` and a `baz.bar`, preferably via some kind of exception. This prevents developers relying on undocumented and potentially dangerous behaviour, although it makes this kind of query more difficult (I'd assume you might be able to get around it with `select()` and column aliases but I have not tested it and this doesn't feel very ActiveRecordey/ORMey).

## Conclusion

Neither of these two is a "fix" for the nested hash variant, which I assume must be addressed regardless.

My personal preference here would be for option `(1)`, to provide support for these other means of unscoping, but I lack sufficient understanding of `ActiveRecord` internals to know if this is feasible.

Please take a look at and play with the supplied test case and draw your own conclusions, I'm happy to assist with any questions and look forward to your comments on this issue.

## Links
* [Isolated Test Case](https://gist.github.com/tobypinder/bf2dd87524029d38589e)

**Comment by sgrif** [comment]
I appreciate the thorough report. However, this is about adding support for an unsupported use case, not necessarily a bug (and as you point out, there are considerations that we need to make in terms of an API if we're going to support this). The issues tracker is reserved for bugs only. Please post this on the Rails Core mailing list, and we can have the discussion there. Thanks!

**Comment by tobypinder** [comment]
I'll certainly consider discussing this on the mailing list; even if this is unsupported behaviour then my option (2) proposal of either documenting the limitations or throwing exception when attempting `unscope`d `joins` would presumably be worth discussing. I'd considered this a bug because of the lack of documentation suggesting this is undocumented but I appreciate that my fix proposal veers closer to an FR.
