### ISSUE TITLE
ActiveRecord `cache_key` goes out-of-sync because of nanoseconds precision

### ISSUE THREAD

**Issue by tarzan** [rails/rails#21815]
I've been doing some extensive caching on my Rails project and encountered the following bug:

When relying on the ActiveRecord `cache_key` and on an OS that supports nanoseconds-time there is a synchronisation problem between the `cache_key` of the Ruby object returned by `.create` and the same object re-fetched from the database. The former is with nanoseconds precision and the second one with microseconds (at most) precision. Therefor the `cache_keys` don't match.

This template illustrates the 'bug', it fails on Ubuntu but passes on OS X:
https://gist.github.com/tarzan/77298ec393598dd4e854

I think it would be wise to tone down the precision of the `cache_key` timestamp to micro-seconds and am willing to do this in a PR. Are you guys interested?

**Comment by pixeltrix** [comment]
@tarzan it is probably a good idea to reduce the `cache_key` precision but I think we need to be careful how we do it otherwise we could break some things. In reality it won't affect most people since the cache won't be generated during the `create`, only once it's been read from the database in a subsequent `show` or `index`.

**Comment by tarzan** [comment]
Thanks for the response @pixeltrix!

As far as I can see now, the things that will break are tests that specifically test on conversion to `:nsec`. I am not as familiar with the AR codebase as you are of course, but did spend a couple of hours in the caching implementation of it ;)

As far as a scenario goes where this does matter, I'll briefly describe a setup similar to the one I encountered this in:
```ruby
class Book < ActiveRecord::Base
  has_many :chapters

  def current_progress_for(user)
     #irrelevant implementation, but complex & has some calculations
     #this method is cached and dependent on the cache_key
  end

  def clear_cache
    #invalidates the cache manually
  end
end

class Chapter < ActiveRecord::Base
  belongs_to :book, touch: true
end

class Completion < ActiveRecord::Base
  belongs_to :chapter
  belongs_to :user

  after_create :clear_cache_on_book

  private

  def clear_cache_on_book
    chapter.book.clear_cache!
  end
end
```

Now, I am using Rails as an API and same records are being requested and serialized (by AMS) multiple times. Actual calculation of `current_progress_for` is a bottleneck in my scenario and that's why I decided to implement low-level caching on this. The method result is being cached on redis based on its cache_key. In the following scenario I will get incorrect results:

```ruby
my_book = Book.find(1)
my_progress = my_book.current_progress_for(current_user)
Completion.create(user: current_user, chapter: some_chapter_in_my_book)
new_progress = my_book.current_progress_for(current_user)
assert_not_equal my_progress, new_progress  # -> FAIL
```
I agree that this block does seem a bit artificial, it actually is from an integration spec but I need to actually be certain that cache is being reset in the correct scenario's. I have been dealing with cache related bugs in the past, having reasonable integration specs helps a lot in preventing them.

**Comment by pixeltrix** [comment]
@tarzan I can certainly see scenarios in which it could cause a problem like pre-warming caches on object creation and if it's a problem then you can override `cache_key` in your model.

My main concern about breakage is if we blow away someone's carefully constructed cache entries. Since we're coming up to the Rails 5 release then it's a perfect time to change it as it's unlikely that someone will maintain cache entries across deployments of a major version (though I have seen people do it for minor versions like from 3.1 to 3.2).

**Comment by tarzan** [comment]
Ok, putting it on the agenda for Rails 5 seems reasonable. 

Working around it is indeed not too hard. I put all my low-level caching in an `ActiveSupport::Concern` with
```ruby
  included do
    self.cache_timestamp_format = :usec
  end
```
and defined the `:usec` as a formatter in an initializer:
```ruby
Time::DATE_FORMATS[:usec] = "%Y%m%d%H%M%S%6N"
```

Question remains, would you appreciate it if I added this to ActiveRecord in a PR? Should I base it on a rails5 branch?

**Comment by pixeltrix** [comment]
It should be a simple PR so please create one and we can discuss it further there - the master branch is Rails 5 so you should base your PR on that.
