### ISSUE TITLE
ActiveRecord::Generators::Base template not found

### ISSUE THREAD

**Issue by maclover7** [rails/rails#21822]
Hi, I created a `ActiveRecord::Generators::Base` migration generator, but an example Rails application ([available here](https://github.com/moss-rb/notebook-test)) says the migration template cannot be found. Not sure if this is a bug per say, but putting the template in the same place works for [paperclip](https://github.com/thoughtbot/paperclip/tree/master/lib/generators/paperclip). Documentation for migration generators isn't great, so that's why I'm opening up a ticket here. Happy to update the docs with whatever is found here. :smiley: 

[Here's the code for the generator / migration template file](https://github.com/moss-rb/notebook/tree/master/lib/generators/notebook). Below is a screen shot of Bundler / the generator error. Any help would be appreciated :heart: cc @rafaelfranca 

![screen shot 2015-09-30 at 6 49 09 pm](https://cloud.githubusercontent.com/assets/3020626/10208810/fd9877f0-67a3-11e5-9bd3-cc06cce6af75.png)

**Comment by rafaelfranca** [comment]
Just to make sure was spring running before you called the generator? Could you try to run without it?

**Comment by maclover7** [comment]
Removed spring from the Gemfile, bundled, and generator is getting the same error as in the screenshot above. :(

**Comment by tamalw** [comment]
@maclover7 Rename "tempates" directory to "templates": https://github.com/tamalw/notebook/tree/master/lib/generators/notebook

**Comment by maclover7** [comment]
:disappointed: renaming the directory solved the problem - will close the issue. Thanks for your help, @tamalw!
