### ISSUE TITLE
Querying JSONB columns with Array and Hash arguments somewhat confusing

### ISSUE THREAD

**Issue by hale** [rails/rails#21820]
Array and Hash arguments are treated as a group of values rather than a single value. 

This means to query on a JSON column you can only use Pure String Conditions.

### Array arguments

Pure String Conditions:

```ruby
# Die(id: integer, sides: jsonb)

Die.where("sides = '[1, 2, 3]'").to_sql
#=> SELECT "dice".* FROM "dice" WHERE (sides = '[1, 2, 3]')
```

Hash Conditions (unexpected behaviour):

```ruby
# Die(id: integer, sides: jsonb)

Die.where(sides: [1, 2, 3]).to_sql
#=> SELECT "dice".* FROM "dice" WHERE "dice"."sides" IN (1, 2, 3)
```

### Hash arguments

Pure String Conditions:

```ruby
# Die(id: integer, rolls: jsonb)

Die.where(%{ attributes = '{"type":"d4"}' })
#=> SELECT "dice".* FROM "dice" WHERE "dice"."attributes" = '{"type":"d4"}'
```

Hash Conditions (unexpected behaviour):

```ruby
# Die(id: integer, rolls: jsonb)

Die.where(attributes: { type: :d4 })
#=> SELECT "dice".* FROM "dice" WHERE "dice"."type" = 'd4'
```

Workaround:

```ruby
# Die(id: integer, rolls: jsonb)

Die.where(attributes: [{ type: :d4 }])
#=> SELECT "dice".* FROM "dice" WHERE "dice"."attributes" = '{"type":"d4"}'
```
----

I'm not sure if any change to the API makes sense, though.

Maybe we just need to add some documentation to state that if you use JSONB columns you should use Pure String Conditions for where queries?

I bring this up because the behaviour is less obvious when you're querying by a variable instead of a literal and it errors, e.g. `Die.where(rolls: die.rolls)`.

**Comment by sgrif** [comment]
Yup, this is a known issue and a limitation of the query API. We can't change it. Your workaround is the recommended way to do it.

**Comment by hale** [comment]
Okay, thanks.
