### ISSUE TITLE
[Rails API] Question - Nokogiri gem

### ISSUE THREAD

**Issue by yordis** [rails/rails#21831]
Do we need the nokogiri gem when we create a JSON API? I am trying to remove any gem that I don't need for make the application lighter.

P.S: the same with Sprocket because I created the API without Sprocket but still loading the gem I think

**Comment by Fudoshiki** [comment]
You can remove requires from application.rb, but gems will install with rails anyway.
```
require 'rails'
# Pick the frameworks you want:
require 'active_model/railtie'
require 'active_job/railtie'
require 'action_controller/railtie'
require 'action_mailer/railtie'
require 'action_view/railtie'
require 'sprockets/railtie'
```

**Comment by arthurnn** [comment]
`rails new --api` should do the right thing!
Have you tried that?

Closing this, as this is a question and we reserve the issue tracker for issues.
(check Stackoverflow for questions)

**Comment by yordis** [comment]
@arthurnn I shouldn't put question in the title.

My concern is about install gems that we don't need for an API, like sprockets, nokogiri?!?!?!? Still I don't understand why I need it. 

@Fudoshiki I am complaining because every time I have to build a docker container, the building get stuck installing nokogiri! So, why install something that we don't need. I prefer to add `nokogiri` in the Gemfile when I do need it. That's why I want to know if we need `nokogiri` in an API.

I think the title with question distracted my reasons :(
