### ISSUE TITLE
How to parameterized array with activerecord

### ISSUE THREAD

**Issue by faisalmansoor** [rails/rails#21834]
Activerecord generates parameterized queries for basic types, but, it does parametrize array types.

E.g.

```
Article.where(id: 1) 
# generates
# SELECT "articles".* FROM "articles" WHERE "articles"."id" = $1  [["id", 1]]
```

But,

```
Article.where(id: [1,2])
# generates
# SELECT "articles".* FROM "articles" WHERE "articles"."id" IN (1, 2)
# rather than
# SELECT "articles".* FROM "articles" WHERE "articles"."id" IN ($1, $2)
  [["id", 1], ["id", 2],]
```

Is it possible to restructure the query or use Arel to generate parametrized query for IN clauses?

**Comment by rafaelfranca** [comment]
Please use the mailing list or StackOverflow for questions/help, where a wider community will be able to help you. We reserve the issues tracker for issues only.

**Comment by faisalmansoor** [comment]
Sorry for that will as on the mailing list, 
Thanks.
