### ISSUE TITLE
ActionController's request.env['SERVER_ADDR'] was removed?

### ISSUE THREAD

**Issue by rc5273** [rails/rails#21830]
I've just switched from Rails 4.0 to Rails 4.1. 

Within my controller I used to be able to extract the server's IP address out of the HTTP request environment using request.env['SERVER_ADDR'] as was documented in the ActionController documentation. This worked fine prior to the switch to 4.1.

I've searched the issues and the only reference I've found to SERVER_ADDR is issue #17779 which updates the ActionController class documentation to reference REMOTE_ADDR instead of SERVER_ADDR.  The comments in the issue don't provide any information as to why.

**Comment by rafaelfranca** [comment]
The reason is that rack was upgrade and it stopped to set this header.
