### ISSUE TITLE
Unable to assign associated records in lazy enumerator

### ISSUE THREAD

**Issue by jcarlson** [rails/rails#21874]
I have a process which build a list of records using a lazy enumerator (since it pings a third party API). When I assign the enumerable list to an association, I get an error.

Here is roughly the scenario, which basically tries to find the first 10 products in the local database which meet a condition that only a third party API can verify:

```
class Product < ActiveRecord::Base
  belongs_to :shopping_bag
end

class ShoppingBag < ActiveRecord::Base
  has_many :products
end
```
running:
```
products = Product.where(condition: true).lazy.select do |product|
  ThirdPartyService.expensive_operation?(product)
end.take(10)

shopping_bag.products = products
```
raises:

```
NoMethodError: undefined method `&' for #<Enumerator::Lazy:0x007fa9231a2f60>
from activerecord-4.2.4/lib/active_record/associations/collection_association.rb:550:in `replace_common_records_in_memory'
```

This could be an error on my part, since an `Enumerator` is not technically an `Array`, and the implementation of `#replace_common_records_in_memory` is assuming it is. Or, this could be an error on the implementation of `#replace_common_records_in_memory` for assuming it is receiving an array.

**Comment by al2o3cr** [comment]
@jcarlson The AR code is definitely expecting an `Array`.

A related note: `Product.where(...).lazy` doesn't do anything smart yet; it loads ALL the resulting products and then returns a lazy iterator over the resulting array. Your code will invoke `expensive_operation?` only ten times, but will instantiate a ton more AR objects.

**Comment by sgrif** [comment]
Yeah, this isn't a bug. Call `.to_a` on it. AR doesn't work with things which implement enumerable, it works with arrays.

**Comment by al2o3cr** [comment]
@jcarlson A quick followup, for future reference - if you want a lazy-loaded collection of AR objects use `find_each` to get an Enumerator first:
```ruby
Product.where(...).lazy.take(10) # => loads all the products then produces a lazy enumerator

Product.where(...).find_each(batch_size: 5).lazy.take(10) # => loads the products in chunks of 5 as-needed
```

**Comment by jcarlson** [comment]
@al2o3cr The code I provided here isn't _exactly_ what I have in my project, it was just the simplest way of demonstrating the issue I was reporting. My project actually inverts the problem and gets a big list of items from the third party API and then proceeds to find local records until it satisfies the task at hand. I did _not_ know about `.find_each`, though, so that's neat and I'll use that if I need to lazily load AR objects. +1

@sgrif As for ActiveRecord not supporting Enumerables, the reason I opened this ticket was because I felt like the error I got did not match the use case. IMHO, either AR _should_ support Enumerables, and thus we have a defect here since it does not work as expected, or AR _should not_ support Enumerables, and should explicitly raise an `ArgumentError` because it did not receive an instance of `Array`, which it does not currently do.

**Comment by sgrif** [comment]
@jcarlson We do not accept feature requests on the issues tracker. They should be directed to the Rails core mailing list (hint, we probably wouldn't accept that request, as there are massive performance gains by only supporting arrays in this case)
