### ISSUE TITLE
reorder in association is ignored with includes

### ISSUE THREAD

**Issue by moktin** [rails/rails#21886]
Here is a gist illustrating what I believe is a bug in activerecord.
https://gist.github.com/moktin/6c75aed8960c4b8ba233

basically considering this two models:

```ruby
class Post < ActiveRecord::Base
  has_many :comments

  has_one :oldest_comment, -> { reorder(:created_at) }, class_name: 'Comment'
end

class Comment < ActiveRecord::Base
  default_scope { order('updated_at desc') }
end
```

This ruby code:
```ruby
Post.last.oldest_comment
```
will generate this SQL
```sql
SELECT  "posts".* FROM "posts"  ORDER BY "posts"."id" DESC LIMIT 1
SELECT "comments".* FROM "comments" WHERE "comments"."post_id" IN (3)  ORDER BY "comments"."created_at" ASC
```
It looks all fine.

However, this ruby code:
```ruby
Post.includes(:oldest_comment).last.oldest_comment
```
will generate this SQL
```sql
SELECT  "posts".* FROM "posts"  ORDER BY "posts"."id" DESC LIMIT 1 
SELECT "comments".* FROM "comments" WHERE "comments"."post_id" IN (1)  ORDER BY updated_at desc, "comments"."created_at" ASC
```

Shouldn't `ORDER BY updated_at DESC, "comments"."created_at" ASC` be `ORDER BY "comments"."created_at" ASC`?

**Comment by senny** [comment]
Attached PR is looking good. I'm assigning the issue to me until merged.

@moktin thank you for reporting! :yellow_heart:
