### ISSUE TITLE
Ruby version conflict in 3.2.22 when using rack-cache 1.3

### ISSUE THREAD

**Issue by juanedi** [rails/rails#21889]
Problem:
   * action_pack 3.2.2 declares to be compatible with ruby >= 1.8.7
   * action_pack 3.2.2 requires rack-cache ~> 1.2 (this allows version 1.3 of rack-cache)
   * rack-cache 1.3 requires ruby => 2.0.0

This means that if version 1.3 of rack-cache is resolved, ruby 1.9.3 cannot be used.

**Comment by rafaelfranca** [comment]
Thank you for the issue but it is not a Rails bug. Your application should explicitly lock `rack-cache` in `< 1.3`. Also Rails 3 is not supported anymore.
