### ISSUE TITLE
ActiveRecord#find_each performance improvement when searching by PK

### ISSUE THREAD

**Issue by jcarbo** [rails/rails#21898]
Imagine you have a large list of PKs and you want to loop through each object. I try to avoid `.each` since it could potentially try to load way too much data into memory so there are two approaches:
```ruby
# Approach 1 (each_slice)
ids.each_slice(250) do |slice|
  User.where(:id => slice).each do |user|
    # Do something
  end
end

# Approach 2 (find_each)
User.where(:id => ids).find_each(:batch_size => 250) do |user|
  # Do something
end
```

Let's say 10000 ids are passed in and batch size 250:
- `each_slice` will execute 40 queries, each for just the 250 ids it wants during that iteration.
- `where(:id => ids).find_each` will execute 40 queries for 10000 ids and use `ORDER BY`, `LIMIT`, `OFFSET` to get the slice of 250 we want.

As an example I took a subset of a records on a production DB (13668 records total):
```ruby
# ids = an array of 13668 ids

batch_size = 250
bench = Benchmark.bm do |x|
  x.report { ids.each_slice(batch_size) { |slice| User.where(:id => slice).each(&:id) } }
  x.report { User.where(:id => ids).find_each(:batch_size => 250).each(&:id) }
end

       user     system      total        real
  0.760000   0.100000   0.860000 (  2.048195)
  9.550000   0.250000   9.800000 ( 18.864559)
```

The improvement is pretty significant, but `Approach 2` looks way cleaner and seems like "the Rails way" to do it.

Question: Is there any way AR can identify this case and use `each_slice` internally?

**Comment by al2o3cr** [comment]
`find_each` doesn't use `OFFSET`. It's building a query that looks like:
```sql
SELECT * FROM users WHERE id > last_id_we_found AND id IN (13688 ids...) ORDER BY id ASC LIMIT 250
```
My guess is that the performance difference here is from turning an array of 13688 ids into SQL 40 times. The `each_slice` code avoids this overhead by doing that conversion exactly once for each group of 250.

**Comment by rafaelfranca** [comment]
Please use the mailing list or StackOverflow for questions/help, where a wider community will be able to help you. We reserve the issues tracker for issues only.
