### ISSUE TITLE
We don't have a method to convert different values to boolean.

### ISSUE THREAD

**Issue by ptashman** [rails/rails#21905]
I would like to propose that the [gem wannabe_bool](https://github.com/prodis/wannabe_bool) be merged into Rails. This boolean conversion is useful to most users of Rails, especially those dealing with varied params sent into Rails APIs.

**Comment by rafaelfranca** [comment]
Thank you so much for the issue but we don't take feature request on the issue tracker. We recommend you to try to implement the feature and send us a pull request or if you are in doubt if the feature will be accepts ask in Rails Core mailing list for feedback.
