### ISSUE TITLE
Improving distance_of_time_in_words 

### ISSUE THREAD

**Issue by tuexss** [rails/rails#21916]
I had a look at distance_of_time_in_words ( https://github.com/rails/rails/blob/97f2c4129ae23ee074986a588628acc689a86462/actionview/lib/action_view/helpers/date_helper.rb#L71-L138 ) this week, and why it is slow and tried to refactor it. But there are several issues with this method, mainly its design:

### No clean idea about difference between two timestamps vs. duration vs. human readable duration.
  * Parameter are two timestamps
  * Algorithm works with difference of unix-seconds of the timestamps
  * Algorithm has tweaks to sometimes handle leapstuff, sometimes not

I'd suggest, to decide whether this algorithm sticks to the actual dates of the timestamps in the parameter or to abstract them away. The former means: take all leap seconds, hours, years into account. The latter means: Ignore all leapstuff, work with averages (1 month=30.4375 days, 1 year=365.25 days).

### Double rounding
The distance_in_minutes is rounded, then used in the algorithm, then used in calculation, then rounded again. This is horrible and leads to 1.475 minutes being displayed as 2 minutes.
Depending on the decision above, I'd go for working with distance_in_seconds and keep precision to a maximum until the very end, shortly before it's returned. Also, instead of `.round` I'd go for `.ceil`, as the ranges-table also implies a ceiling-based approach most of the time. But with a second-precision level it wouldn't make much of a difference anyway. 

### Different boundaries on different precisions
On the default precision, there is a 30 second boundary - but on the fine precision, this boundary disappears. This causes additional effort, and doesn't make much sense. `less than a minute` would be fine with the 40th second boundary.

### Weird almost/above feature
There is no almost/above for anything below year-level. To be consistent, we should either have it on all levels (minutes,hours,days,months,years) or on none. Or a third way which I favor would be to replace this functionality with keeping month precision even on year level. So it's not almost `8 years`, but rather `7 years and 10 months`.

### 42 easter egg
I know there are probably fans of the 42 hours boundary. e.g. `41 hours` is rendered as `1 day`. I'd drop the 1 day boundary completely, or at least apply it to an area closer around the 24 hours mark, like 20..36

wdyt?

**Comment by sgrif** [comment]
Feel free to open a PR. We reserve the issues tracker for bugs only.
