### ISSUE TITLE
has_many :association, touch: true

### ISSUE THREAD

**Issue by eidge** [rails/rails#21929]
Hello guys,

I need to touch every associated has_many object when my model is updated. I just realized this doesn't work.

Would adding support to this use-case to rails be a contribution you would accept or is there strong reason it wasn't added in the first place?

Thank you,
HR

**Comment by rafaelfranca** [comment]
Thank you so much for the issue but we don't take feature request on the issue tracker. We recommend you to try to implement the feature and send us a pull request or if you are in doubt if the feature will be accepts ask in Rails Core mailing list for feedback.
