### ISSUE TITLE
..too many redirects occurred trying to open 'https://moneytree.space/catalogs/traders'. This is occur if you open a page that is redirected to open another page which then is redirected to open the original page"

### ISSUE THREAD

**Issue by zhall** [rails/rails#21925]
I am trying to deploy my rails app using https protocol.

When I add the index.html page to the public directory, then type https://moneytree.space in the browser, the 'index.html' page is displayed. But when I add https://moneytree.space/catalogs/traders I get the following error message:

...too many redirects occurred trying to open 'https://moneytree.space/catalogs/traders'. This is occur if you open a page that is redirected to open another page which then is redirected to open the original page"

Only the 'index' page that is in the public directory is displayed. This is not what I want. I know that is to do with redirects. But I don't know what steps must I follow to correct this issue.

In my config/root file, root is 'catalogs/traders'.
In my unicorn.rb file I have:

# set path to application
app_dir = "/home/zhall/zoulfia"
shared_dir = "#{app_dir}/shared"
working_directory app_dir

# Set unicorn options
worker_processes (ENV['RAILS_ENV'] == 'production' ? 4 : 1)
preload_app true
timeout 300

# Set the working directory of this unicorn instance.
working_directory app_dir

# Set up socket location
listen "#{shared_dir}/sockets/unicorn.sock", :backlog => 64

# Logging
stderr_path "#{shared_dir}log/unicorn.stderr.log"
stdout_path "#{shared_dir}/log/unicorn.stdout.log"

# Set master PID location
pid "#{shared_dir}/pids/unicorn.pid"

When I type: sudo nano /home/zhall/zoulfia/shared/sockets/unicorn.sock

I get

[ Error reading /home/zhall/zoulfia/shared/sockets/unicorn.sock: No such device or address ]

In my /etc/nginx/site-enabled/default file I have:
upstream @app {
# Path to Unicorn SOCK file, as defined previously
server unix:/home/zhall/zoulfia/shared/sockets/unicorn.sock
fail_timeout=0;
}

This file does exists, I am using FileZilla UI, I can see the file is in the directory specified but is empty.

Any help would be welcomed. Thank you.

**Comment by rafaelfranca** [comment]
Please use the mailing list or StackOverflow for questions/help, where a wider community will be able to help you. We reserve the issues tracker for issues only.

**Comment by zhall** [comment]
Thank you.What does 'We reserve the issues tracker for issues only.' mean?

**Comment by pixeltrix** [comment]
@zhall issues are bugs in the Rails framework itself and not problems that people are having writing Rails application which is catered for elsewhere by StackOverflow, mailing lists, IRC, etc.

**Comment by zhall** [comment]
Hi
Sorry if I bothered  you. I resolved this issue now.
Thank you.

**Comment by zhall** [comment]
Hello there,

I just signed the petition "Purley MP: Overground Tube station to Purley"
and wanted to see if you could help by adding your name.

Our goal is to reach 100 signatures and we need more support. You can read
more and sign the petition here:

http://chng.it/XbCjL7dwWv

Thanks!
Zoulfia
