### ISSUE TITLE
Guides: References to `params` as a hash

### ISSUE THREAD

**Issue by scottgonzalez** [rails/rails#21926]
In #21906, @claudiob [said](https://github.com/rails/rails/pull/21906#discussion_r41469298):

> Since `params` does not inherit from Hash anymore, do you mind changing this line as well to "…make its way to the `params` in the controller…"?

There are a lot of other references to `params` as a hash in the guides, but I'm not sure what the best replacement is. Should the word "hash" just be dropped as @claudiob suggested? Or should it be changed to "the `params` object", "`params`", "the `params` variable", something else?

I can send a PR updating all of the guides once a decision is made.

**Comment by rafaelfranca** [comment]
`"the params object"` looks good to me.
