### ISSUE TITLE
config.i18n.default_locale is not respected after using .parameterize in a gem

### ISSUE THREAD

**Issue by alexhanh** [rails/rails#21939]
We have a gem that simply does the following
```
module Foo
  BAR = 'öäå'.parameterize
end
```

we then have a Rails 4.2.4 project that uses that gem. In that project, we have `config.i18n.default_locale = :fi`. Without the gem, we get the following output

```
Loading development environment (Rails 4.2.4)
2.2.1 :001 > I18n.locale
 => :fi
```
with the gem
```
Loading development environment (Rails 4.2.4)
2.2.1 :001 > I18n.locale
 => :en
```

`parameterize` uses `transliterate`, which again uses the `I18n.transliterate`. For some reason, calling parameterize before setting the default_locale will prevent the default_locale to be set afterwards.

Is this a bug or intended behaviour? If the latter, how are we supposed to use parameterize without affecting default_locale later on?

**Comment by senny** [comment]
This is that [`I18n::Config`](https://github.com/mattetti/i18n/blob/32eed2028c1d6148fd0de2079ded40da740ae259/lib/i18n/config.rb#L6) assigns and caches `I18n.locale` on the first call.

I don't think there's much we can do. Basically if `I18n.locale` `I18n.default_locale` is assigned you'll get `:en`.

/cc @carlosantoniodasilva

**Comment by thedarkone** [comment]
> how are we supposed to use parameterize without affecting `default_locale` later on?

@alexhanh I know this might be nitpicking, but isn't `I18n.default_locale` unaffected?

expected output:
```
2.2.1 :001 > I18n.default_locale
 => :fi
```

`I18n.locale` is a current thread's currently selected locale, for example with `I18n.default_locale = :fi` new threads should default to `:fi` locale `Thread.new { I18n.locale }.value # => :fi`.

I don't think this is a bug and you will probably have to change your init code to something like this:
```ruby
config.i18n.default_locale = :fi
I18n.locale = config.i18n.default_locale
```

**Comment by senny** [comment]
I'm closing for the reasons presented above. Thank you for reporting.
