### ISSUE TITLE
"Running tests" documentation is wrong

### ISSUE THREAD

**Issue by radar** [rails/rails#21935]
[Under "Running Tests" in the "Guide To Testing Rails Applications"](http://guides.rubyonrails.org/testing.html#running-tests), it advises you can do this:

```
bin/rake test test/models/article_test.rb
```

It appears that this will run a single test. This is not the truth, as in my brand new Rails app it shows me this:

```
bin/rake test test/models
Run options: --seed 57732

# Running:

..E

Finished in 0.115559s, 25.9608 runs/s, 17.3072 assertions/s.

  1) Error:
PostsTest#test_posts:
AbstractController::ActionNotFound: The action 'create' could not be found for PostsController
    test/integration/posts_test.rb:20:in `test_posts'

3 runs, 2 assertions, 0 failures, 1 errors, 0 skips
```

This is running `test/integration` tests, rather than just the tests in `test/models`. I think this is a documentation bug.

**Comment by radar** [comment]
On further investigation, `bin/rake test test/models/invoice_test.rb` works, but `bin/rake test test/models` doesn't. `bin/rake test test/models/*` also works.

Can we make `bin/rake test test/models` work automatically?

**Comment by pixeltrix** [comment]
@radar probably - do you want to file a PR or should I look at it?

**Comment by radar** [comment]
@pixeltrix All yours :)

**Comment by senny** [comment]
@radar what version did your brand new Rails app use? `4.2.x` or `master`? If it's `master` you should refer to the [`edge guide`](edgeguides.rubyonrails.org/testing.html) which has all the examples rewritten using the new test runner `bin/test`.

**Comment by radar** [comment]
4.2.4 is the version I used.

**Comment by senny** [comment]
mmm, I'll have a look. Since Rails 5 is moving away from `bin/rake` we add anything new on `4-2-stable`. But it seems worth to have a look why a documented example stopped working.

**Comment by pixeltrix** [comment]
@senny I think the documented example works, it's just the folder. I'm in two minds over this - one is that it would be good to not have to remember that it doesn't work when on an 4.2 app and the other is that we don't add new features. I guess it'd depend on how big a change it is.

**Comment by senny** [comment]
@pixeltrix after reading the issue once more I noticed it's about adding something new. The guide only gives advice on how to run a file using `bin/rake test`. 

I'm :-1: on adding anything to `rake test`. This will be possible with Rails 5 and `bin/test`. In the meantime you can use the designated tasks to run only a specific suite: `bin/rake test:models`.

**Comment by rafaelfranca** [comment]
Agree with @senny.

**Comment by senny** [comment]
@radar thank you for reporting. Hope you can wait till Rails 5 :relaxed:
