### ISSUE TITLE
Misleading documentation: "Class methods on your model are automatically available on scopes"

### ISSUE THREAD

**Issue by DreadPirateShawn** [rails/rails#21943]
The documentation at http://apidock.com/rails/ActiveRecord/NamedScope/ClassMethods/scope states, near the bottom, that **"Class methods on your model are automatically available on scopes,"** and provides a couple examples.

While this technically works as written, it has one extremely subtle difference from previous versions of the same document, a deal-breaking difference that I think should be called out more clearly.

[v4.2.4 official doc](http://api.rubyonrails.org/classes/ActiveRecord/Scoping/Named/ClassMethods.html)

```
class Article < ActiveRecord::Base
  scope :published, -> { where(published: true) }
  scope :featured, -> { where(featured: true) }

  def self.latest_article
    order('published_at desc').first
  end

  def self.titles
    pluck(:title)
  end
end

Article.published.featured.latest_article
Article.featured.titles
```

vs [v3.1.0 unofficial apidock older version of doc](http://apidock.com/rails/v3.1.0/ActiveRecord/NamedScope/ClassMethods/scope) which is nearly identical except with `map(&:title)` instead of `pluck(:title)`.

This matters greatly, because although the feature descriptions are identical, if you attempt to use `map(&:title)` in **activerecord 4.1.4** you will receive the following error:

```
     NoMethodError:
       undefined method `map' for #<Class:0xb5535150>
```

Since every other aspect of this feature description is identical between versions, anyone reading both would reasonably assume that both `map(&:title)` and `pluck(:title)` are equally valid examples of the feature, and that both should work.

This may not have worked in Rails v3 either, judging from a StackOverflow post from [2 years ago for v3.1.3](http://stackoverflow.com/questions/14195591/how-did-the-class-method-call-on-activerecordrelation-takes-a-context).

In another StackOverflow post [more recently](http://stackoverflow.com/questions/31155085/rails-model-class-method-for-collection-of-objects), the same issue is seen again, although here a workaround is suggested -- **using `all.map(&:title)` instead of simple `map(&:title)` will make the chaining feature work as desired & documented.**

In my opinion, the next steps should be:
* update the current doc to call out this unexpected error when chaining with `map`, and to suggest the `all.map` workaround
* consider whether this `undefined method 'map'` error is desired, and whether this behavior itself should be fixed to work in the same manner that `pluck` does

**Comment by rafaelfranca** [comment]
`map` and `pluck` are not the same so they will behave differently indeed. The old documentation that you are referring is just wrong. Also apidoc.com is not the official documentation. I don't think the current documentation should mention something that was wrong in a non-mainteined version of our documentation.

Thank you for the issue.

**Comment by DreadPirateShawn** [comment]
Ahh, my apologies for the incorrect links -- I found the official link for 4.x (updated in the description above), the all the details of the ticket still apply, the doc has the same info as cited.

So, my concern is simply that old versions of the Rails doc are still easy to stumble onto, when the current doc has simply changed a single word with no other warning that the change is actually a *fix* rather than just a variety in examples.

Plus I don't think it's unreasonable for the doc to clarify what the expectation is -- that is, what metric should a dev use to know that `pluck` is viable here but `map` is not? The raw version of both examples does work -- `Article.featured.pluck(:title)` and `Article.featured.map(&:titles)` -- so why did the earlier invalid example in the doc need to be changed, how do we know to determine that `pluck` should work but `map` should not?

I'm a bit concerned that this ticket was closed prematurely based solely on my usage of an unofficial doc link (sorry about that!) and the premise that strictly accurate docs are sufficient even though the doc isn't clear about the usage considerations of the feature it's defining.

That being said, if you prefer to leave this ticket closed, then I understand -- you're the maintainer, ultimately it's your baby to nourish :-) -- and at least this ticket will serve as recap of the workaround and confirmation that the behavior is intentional.

Many thanks for your time!

**Comment by rafaelfranca** [comment]
I'll take a closer look. Thank you!

**Comment by kaspth** [comment]
I don't think an unofficial doc link for Rails 3.1 is enough to warrant a change in our docs.

Active Record's relation API underwent major changes in 4.0, part of which was that enumerable methods should be called on a scope, e.g. `Post.all.map(&:titles)`.

Thanks!
