### ISSUE TITLE
Misleading deprecation warning when calling update with an instance

### ISSUE THREAD

**Issue by Drenmi** [rails/rails#21945]
### Problem

When calling [ActiveRecord::Relation#update](http://api.rubyonrails.org/classes/ActiveRecord/Relation.html#method-i-update) with an instance of ActiveRecord::Base instead of an id, a deprecation warning like the following is shown:

```
user = User.first
User.update(user, nickname: "Tenderlove")

DEPRECATION WARNING: You are passing an instance of ActiveRecord::Base to `find`.
Please pass the id of the object by calling `.id`.
(called from index at /home/vagrant/my-test-app/app/controllers/users_controller.rb:4)
```

This is happening because [update](https://github.com/rails/rails/blob/master/activerecord/lib/active_record/relation.rb#L408) is calling [find](https://github.com/rails/rails/blob/fb03a9ab35ed22e569ec9cef8a50ef72754b5dbe/activerecord/lib/active_record/core.rb#L140) internally, and only the latter will raise a deprecation warning. This gets a bit confusing, since the message claims:

> You are passing an instance [...] to `find`.

But this (:cake:) is a lie. If the developer looks at the offending line, they won't find (pun unintended) any calls to `find`. Furthermore, because the call is internal, the call stack frame with the actual method invokation is discarded on extraction, leaving us with a half-truth of the correct line, but the wrong method name.

---

### Possible solution

This is an easy thing to fix, but might warrant a discussion on how to handle deprecation messages in this kind of case in general. (Unless such discussion has already been had, and I just can't find it, in which case I apologize.)

I would suggest raising a deprecation warning in `update`, and replace the `ActiveRecord::Base` with its `id` before passing it to `find`. This will copy some code (outlined below) between `update` and `find`, but leaves a singular, correct deprecation message (which I find preferable to several, or incorrect ones), without the need for more complex mechanisms.

```
if ActiveRecord::Base === id
  id = id.id
  ActiveSupport::Deprecation.warn(<<-MSG.squish)
    You are passing an instance of ActiveRecord::Base to `update`.
    Please pass the id of the object by calling `.id`
  MSG
end
```

**Comment by Drenmi** [comment]
Fixed in https://github.com/rails/rails/pull/21964

**Comment by bobintornado** [comment]
:+1:
