### ISSUE TITLE
ActiveModel numericality validator integer_only should validate against type_cast value

### ISSUE THREAD

**Issue by jsteinberg** [rails/rails#21941]
I stumbled across what I believe is an issue with ActiveRecord 4.2+(potentially effects older versions).  I have been away from rails for a bit but I believe the type casting got reworked recently.  I think that the NumericalityValidator should validate against the type casted value instead of the raw value.  

Here is the beginning of the [validate_each method](https://github.com/rails/rails/blob/master/activemodel/lib/active_model/validations/numericality.rb#L20)

```ruby
def validate_each(record, attr_name, value)
  before_type_cast = :"#{attr_name}_before_type_cast"

  raw_value = record.send(before_type_cast) if record.respond_to?(before_type_cast)
  raw_value ||= value
...
end
```

I feel like this is incorrect behavior.  It breaks when you assign a BigDecimal number to an integer attribute.  [ActiveModel::Type::Integer](https://github.com/rails/rails/blob/master/activemodel/lib/active_model/type/integer.rb#L43) will typecast a BigDecimal by calling .to_i on it.  

```ruby
# ActiveModel::Type::Integer

def cast_value(value)
  case value
  when true then 1
  when false then 0
  else
    value.to_i rescue nil
  end
end

```

The NumericalityValidator calls .to_s and compares it to a regex.  You can see it used in the [parse_raw_value_as_an_integer](https://github.com/rails/rails/blob/master/activemodel/lib/active_model/validations/numericality.rb#L73) method.

```ruby
def parse_raw_value_as_an_integer(raw_value)
  raw_value.to_i if raw_value.to_s =~ /\A[+-]?\d+\z/
end
```

I have created a [example gist](https://gist.github.com/jsteinberg/db245ae326c0a55154a3) that displays this odd behavior.  Here is a simplified version of the gist.

```ruby
class Post < ActiveRecord::Base
  validates :value, numericality: { only_integer: true }
end

post = Post.new
post.value = BigDecimal.new('100')

assert_equal true, post.value.integer?
assert_equal 100, post.value
assert_equal true, post.valid?
```

This fails on the line attempting to check if the post if valid.

```ruby
assert_equal true, post.valid?
```

I am not sure where exactly the issue is.  I believe it is most likely in the NumericalityValidator but is potentially how ActiveModel::Type::Integer typecasts BigDecimal values.  I think the behaviors should be in sync.  I am willing to submit a fix but am unsure of what is considered broken here.

**Comment by al2o3cr** [comment]
@jsteinberg FWIW, I vaguely recall that it *used* to work like this, but was changed because the default type-casting converts silly things (like `"foo"`) into `0`. I'll track down the relevant commits / PRs when I get a minute.

**Comment by jsteinberg** [comment]
I understand that "foo".to_i resolving to 0 is bad and should not validate.  Floats also would validate when they should not(12.34.to_i).  Maybe the type casting should somehow reject these values instead of calling .to_i on them?  This is especially tricky because I'm not sure if 100.0 should pass the integer_only check.

I just feel like this is inconsistent and that makes it confusing.

**Comment by sgrif** [comment]
The entire point is to validate the before type cast version, since for an integer column, the validation would always pass. The point is to make sure that by converting to an integer, no information was lost.
