### ISSUE TITLE
Timezone offsets in time_zone_select not taking into consideration DST

### ISSUE THREAD

**Issue by MatTarantini** [rails/rails#21942]
https://github.com/rails/rails/blob/2061c15f80f0c0302f8aadd201e8ef0ee5e59803/activesupport/lib/active_support/values/time_zone.rb#L283

I would recommend changing this to utc_total_offset to take Daylight Savings Time into consideration, unless this was done on purpose for a reason that I'm currently unaware of.

Example: time_zone_select shows US/Pacific as "(GMT-08:00) US/Pacific", when it should be -07:00 right now.

**Comment by pixeltrix** [comment]
This is a presentational issue - the question is whether we should show the current offset in the popup menu or not. It's arguable that either is correct or even that we shouldn't show the offset at all. I think this would be best solved by moving the presentational aspect of the content to locales as we've looked at before.

**Comment by MatTarantini** [comment]
@pixeltrix Thanks for the response.

I've had quite a few clients contact me worried that the incorrect offset on the timezone select would transfer over to issues on the website.

Personally, I would keep the offset display on each timezone since people use them as a quick guide to find the general area where they will then start reading the timezone names.

And I agree that it would be nice to have more control over the presentation of the timezones listed through locales.

Any idea which way this might be going?
Also, is there anything that I can do at the moment to display the current offset and put my clients at ease?

**Comment by kv109** [comment]
@MatTarantini, maybe you should check out `ActiveSupport::TimeWithZone`? Its `#formatted_offset` takes DST into consideration:

```ruby
assert_equal '-05:00', ActiveSupport::TimeWithZone.new(Time.utc(2000, 1), @time_zone).formatted_offset
assert_equal '-04:00', ActiveSupport::TimeWithZone.new(Time.utc(2000, 6), @time_zone).formatted_offset #dst
```

See this [test](https://github.com/rails/rails/blob/4d8f62dcfa0a5157b3facbd71f75fc6639636347/activesupport/test/core_ext/time_with_zone_test.rb#L73-L74).

**Comment by pixeltrix** [comment]
@MatTarantini it's relatively easy to construct your own timezone select helper method - I'm looking at moving it out to locales for Rails 5.

**Comment by kv109** [comment]
@pixeltrix 
What do you think about adding following option:
```ruby
TimeZone.to_s(utc_total_offset: true) #=> "(GMT+02:00) Amsterdam"
TimeZone.to_s                         #=> "(GMT+01:00) Amsterdam"
```
?
 https://github.com/rails/rails/compare/master...kv109:21942?expand=1

**Comment by avit** [comment]
I'm guessing that any use of `time_zone_select` might be used alongside a `date_select` or `date_field` or similar.

This is going to be impossible to resolve on server-side so it shows the correct offset based on changing inputs. I would recommend closing this issue.

Any listing of time zones is always given as the Standard offset, without DST:

https://en.wikipedia.org/wiki/List_of_UTC_time_offsets

**Comment by pixeltrix** [comment]
Agree with @avit - closing
