### ISSUE TITLE
Url error in security guide

### ISSUE THREAD

**Issue by fnicola** [rails/rails#21949]
From [here](http://guides.rubyonrails.org/security.html) On the paragraph `7.3.2.1 Cookie Theft` when it says  `will still be visible using Ajax` the link incorporated is not working anymore: http://ha.ckers.org/blog/20070719/firefox-implements-httponly-and-is-vulnerable-to-xmlhttprequest/
I can see [here](https://github.com/rails/rails/pull/20327) though that the link was replaced in May. I wonder why in the documentation is still broken?

**Comment by Gaurav2728** [comment]
@fnicola it's fixed in that PR https://github.com/rails/rails/pull/20327/files. If you want to check and read latest stuff we prefar to read http://edgeguides.rubyonrails.org/security.html

**Comment by fnicola** [comment]
@Gaurav2728 I didn't know that! Thanks.

**Comment by senny** [comment]
I did a quick backport (52a9beb6594094a7d440f4f340534d9cc80a6325) of the relevant changes to `4-2-stable`.

@fnicola note that they will not immediately reflect on [`http://guides.rubyonrails.org/`]. That website is only updated when a new version of Rails is released. These are the docs of the latest stable Release of Rails.

As @Gaurav2728 pointed out, for the latest docs (from the `master` branch) use the [`edge guides`](http://edgeguides.rubyonrails.org/)
