### ISSUE TITLE
Rails Query throws Mysql2::Error: Unknown column randomly 

### ISSUE THREAD

**Issue by hadiS** [rails/rails#21965]
In my Rails application I have the following Rails Query:

``` ruby
Delivery.includes(delivery_products: :product).where('delivery_products.delivery_count > ? or delivery_products.back_count > ?', 0, 0)
.references(:delivery_products).joins(:customer)
.where(customers: {category: 'Auslieferer'})
.where('delivery_date >= ? AND delivery_date <= ?', from_date, to_date)
```

This is converted to the following SQL query:

``` sql
SELECT `deliveries`.`id` AS t0_r0, `deliveries`.`delivery_date` AS t0_r1, `deliveries`.`price_group` AS t0_r2, `deliveries`.`customer_id` AS t0_r3, `deliveries`.`created_at` AS t0_r4, `deliveries`.`updated_at` AS t0_r5, `deliveries`.`invoice_id` AS t0_r6, `deliveries`.`user_id` AS t0_r7, `delivery_products`.`id` AS t1_r0, `delivery_products`.`product_id` AS t1_r1, `delivery_products`.`delivery_id` AS t1_r2, `delivery_products`.`delivery_count` AS t1_r3, `delivery_products`.`back_count` AS t1_r4, `delivery_products`.`price` AS t1_r5, `delivery_products`.`created_at` AS t1_r6, `delivery_products`.`updated_at` AS t1_r7, `products`.`id` AS t2_r0, `products`.`product_number` AS t2_r1, `products`.`name` AS t2_r2, `products`.`tax` AS t2_r3, `products`.`created_at` AS t2_r4, `products`.`updated_at` AS t2_r5, `products`.`deleted` AS t2_r6 
FROM `deliveries` 
INNER JOIN `customers` ON `customers`.`id` = `deliveries`.`customer_id` 
LEFT OUTER JOIN `delivery_products` ON `delivery_products`.`delivery_id` = `deliveries`.`id` 
LEFT OUTER JOIN `products` ON `products`.`id` = `delivery_products`.`product_id` 
WHERE (delivery_products.delivery_count > 0 or delivery_products.back_count > 0) AND `customers`.`category` = 'Auslieferer' AND (delivery_date >= '2015-10-01 00:00:00.000000' AND delivery_date <= '2015-10-31 23:59:59.000000')
```

which works perfectly fine. Now, when I visit other parts of the Rails App and come back to the page, where this query is triggered Rails throws an error  because the following SQL Query is produced instead of the one above:

Error thrown: Mysql2::Error: Unknown column 'products.product_prices.price' in 'field list'

``` sql
SELECT `deliveries`.`id` AS t0_r0, `deliveries`.`delivery_date` AS t0_r1, `deliveries`.`price_group` AS t0_r2, `deliveries`.`customer_id` AS t0_r3, `deliveries`.`created_at` AS t0_r4, `deliveries`.`updated_at` AS t0_r5, `deliveries`.`invoice_id` AS t0_r6, `deliveries`.`user_id` AS t0_r7, `delivery_products`.`id` AS t1_r0, `delivery_products`.`product_id` AS t1_r1, `delivery_products`.`delivery_id` AS t1_r2, `delivery_products`.`delivery_count` AS t1_r3, `delivery_products`.`back_count` AS t1_r4, `delivery_products`.`price` AS t1_r5, `delivery_products`.`created_at` AS t1_r6, `delivery_products`.`updated_at` AS t1_r7, `products`.`id` AS t2_r0, `products`.`product_number` AS t2_r1, `products`.`name` AS t2_r2, `products`.`tax` AS t2_r3, `products`.`created_at` AS t2_r4, `products`.`updated_at` AS t2_r5, `products`.`deleted` AS t2_r6, `products`.`product_prices.price` AS t2_r7, `products`.`product_prices.price` AS t2_r8, `products`.`product_prices.price` AS t2_r9, `products`.`product_prices.price` AS t2_r10, `products`.`product_prices.price` AS t2_r11, `products`.`product_prices.price` AS t2_r12, `products`.`product_prices.price` AS t2_r13, `products`.`product_prices.price` AS t2_r14, `products`.`product_prices.price` AS t2_r15, `products`.`product_prices.price` AS t2_r16, `products`.`product_prices.price` AS t2_r17, `products`.`product_prices.price` AS t2_r18 
FROM `deliveries` 
INNER JOIN `customers` ON `customers`.`id` = `deliveries`.`customer_id` 
LEFT OUTER JOIN `delivery_products` ON `delivery_products`.`delivery_id` = `deliveries`.`id` 
LEFT OUTER JOIN `products` ON `products`.`id` = `delivery_products`.`product_id` 
WHERE (delivery_products.delivery_count > 0 or delivery_products.back_count > 0) AND `customers`.`category` = 'Auslieferer' AND (delivery_date >= '2015-10-01 00:00:00.000000' AND delivery_date <= '2015-10-31 23:59:59.000000')
```

Why does Rails suddenly produce all the `products.product_prices.price AS t2_r11` selects? Could it be that Rails caches Queries between requests and somehow mixes queries together, which produce wrong SQL queries?

**Comment by pixeltrix** [comment]
@hadiS is there a `product_prices` table within your application? Without access to the source code it's nigh-on impossible to debug these but it doesn't sound like a problem in Rails since the query cache doesn't work that way. Also letting us know what the Rails version is would be a big help.

An off the cuff thought would be that your creating some kind of pricing table on `Product` by joining to `product_prices` multiple times and that's leaking into the subsequent query - maybe it's even a view?

**Comment by hadiS** [comment]
Rails version: 4.2.0
Yes, I have a `product_prices` table. It is a joint table for a `has_many :through` association. Within the same request there is not a single Query where `product_prices` is involved. (And even if, how could it leak into the query from above? One time the query works and produces the correct SQL query, the other time not.)

What I figured out now is that the Rails query from above throws the error ONLY after you visit a page where the following query is triggered a couple of times (with different product_ids):

```
SELECT  `product_prices`.* FROM `product_prices` WHERE `product_prices`.`product_id` = 1 AND `product_prices`.`price_group_id` = 1  ORDER BY `product_prices`.`id` ASC LIMIT 1
```

But this query and the query from above are not within the same request. If I restart my Rails server and visit the first page, then, as already said, the query works. After I visit the page where the query in this post is triggered, and then go back to the first page then the error prone query is produced. But I can't find any relation between these to queries as they are in different requests.

If you need more information, I am glad to share it with you.

**Comment by pixeltrix** [comment]
@hadiS any chance you can update to 4.2.4 and retry? It shouldn't be a big change but there are some changes around prepared query caching introduced in 4.2 that may have fixed things - thanks.

**Comment by hadiS** [comment]
I updated to 4.2.4 but sadly it didn't solve the problem. Funny thing is, that when I replace the 'includes' method with 'joins' then the query works all the time, but then I get a n+1 Problem which I really want to avoid (it takes ages to finish)

So replacing the query
```ruby
Delivery.includes(delivery_products: :product).where('delivery_products.delivery_count > ? or delivery_products.back_count > ?', 0, 0)
.references(:delivery_products).joins(:customer)
.where(customers: {category: 'Auslieferer'})
.where('delivery_date >= ? AND delivery_date <= ?', from_date, to_date)
```

with this one
```ruby
Delivery.joins(delivery_products: :product).where('delivery_products.delivery_count > ? or delivery_products.back_count > ?', 0, 0)
.references(:delivery_products).joins(:customer)
.where(customers: {category: 'Auslieferer'})
.where('delivery_date >= ? AND delivery_date <= ?', from_date, to_date)
``` 
then everything works properly.

**Comment by senny** [comment]
@hadiS if joins is working, you might want to use `.eager_load` to solve your `N+1`. Basically `includes` picks a preloading strategy based on your query, which results in either a `.preload` or a `.eager_load`.

**Comment by hadiS** [comment]
I already tried `.eager_load`. It has the same result as `.includes, hence it throws an error as explained above.

**Comment by pixeltrix** [comment]
@hadiS can you try adding `prepared_statements: false` to your `database.yml` file and see if that fixes the error - that disables the statement cache.

Another thing to look for is something like this:

```
Delivery.some_custom_scope.scoping do
  Delivery.includes.where.etc
end
```

Using `scoping` will set the `current_scope` on `Delivery` and affect any other queries inside the block - is it possible that could be the case here? Also any default scopes?

**Comment by sgrif** [comment]
I can't imagine that setting that would affect this since the mysql adapter doesn't support prepared statements.

**Comment by pixeltrix** [comment]
@sgrif ah yes, getting the mysql and mysql2 adapters the wrong way round - thanks

**Comment by hadiS** [comment]
Thanks all for your help. I think I found the problem. 

In my `Delivery` model I have a class method where the query from above is triggered:

`Delivery.includes(delivery_products: :product).where...` 

Because `delivery_products` is a joint table, in the same model I have:

```ruby
has_many :delivery_products
has_many :products, through: :delivery_products
```
Hence having a `has_many :through` relation and making a query, where you try to eager load `products` and `delivery_products` is a no-go?!

When I use 

`Delivery.includes(:delivery_products).where...` (without eager loading products)

then no error is thrown. 

So my questions are: Why does the first query still works randomly and how can I also eager load `products` in this query without an error thrown.

**Comment by pixeltrix** [comment]
@hadiS is there a default scope on `Product`? I can't see how removing the `:product` from the `includes` would affect whether `product_prices` was added to the query or not otherwise. When you do `includes(delivery_products: :product)` it's using the `:product` association on `DeliveryProduct` not `Delivery` - to use that one you'd have to define it as `includes(:delivery_products, :products)`.

As for the query working sometimes and not other times then it's possible that the times that it works it's preloading the product association on `DeliveryProduct` and not trying to eager load it - it's hard to say without seeing the SQL generated each time. Can you try the query using `preload(delivery_products: :product)` ?

I'm still not sure there's a bug here but there may be - is it possible to reproduce this in a standalone gist as described in the [contribution guidelines][1]?

[1]: http://guides.rubyonrails.org/contributing_to_ruby_on_rails.html#create-a-self-contained-gist-for-active-record-and-action-controller-issues

**Comment by IgorMiller** [comment]
I have a similar error when using `includes` with polymorphism using 'mysql2'  '0.3.20' and rails 4.2.4. Here is a gist reproducing the error: https://gist.github.com/IgorMiller/67592a2a0cd24402415b , with sqlite3 and the last version of rails.

It generates the exception: 
```SQL
SQLite3::SQLException: no such column: blogs.media_type: SELECT "texts".* FROM "texts" WHERE "blogs"."media_type" = ? AND "texts"."id" = 1
```
As you can see the FROM statement does not include the "blogs" table and the selection fails.

I don't know if it may be related to the above problem

**Comment by al2o3cr** [comment]
@IgorMiller To fix your case, AR needs to be told (someplace) that loading `Text` objects via that association involves the `blogs` table. Some options:

* Specify a join explicitly on the association scope:
```ruby
  # in Blog
  belongs_to :text, -> { joins(:blog).where(blogs: {media_type: 'Text'}) }, foreign_key: 'media_id'

  # produces queries like
  # SELECT  "blogs".* FROM "blogs" WHERE "blogs"."title" = ? ORDER BY "blogs"."id" ASC LIMIT 1
  # SELECT "texts".* FROM "texts" INNER JOIN "blogs" ON "blogs"."media_id" = "texts"."id" AND "blogs"."media_type" = ? WHERE "blogs"."media_type" = ? AND "texts"."id" = 1
```

* Explicitly use `references` at the point of use:
```ruby
  # in the test
  data = Blog.where(title: t).includes(:text).references(:text => :blog)

  # produces a query like
  # SELECT  "blogs"."id" AS t0_r0, "blogs"."title" AS t0_r1, "blogs"."description" AS t0_r2, "blogs"."media_id" AS t0_r3, "blogs"."media_type" AS t0_r4, "blogs"."created_at" AS t0_r5, "blogs"."updated_at" AS t0_r6, "texts"."id" AS t1_r0, "texts"."content" AS t1_r1, "texts"."blog_id" AS t1_r2, "texts"."created_at" AS t1_r3, "texts"."updated_at" AS t1_r4 FROM "blogs" LEFT OUTER JOIN "texts" ON "texts"."id" = "blogs"."media_id" AND "blogs"."media_type" = ? WHERE "blogs"."title" = ? ORDER BY "blogs"."id" ASC LIMIT 1
```

* Use `eager_load` rather than `include` at the point of use:
```ruby
  # in the test
  data = Blog.where(title: t).eager_load(:text)

  # produces the same query as `references`
```

Without one of these approaches, AR is going to assume the `text` association can be loaded given ONLY the value from `media_id`.

**Comment by IgorMiller** [comment]
Ok. Thank you. eager_load works perfectly :+1:
