### ISSUE TITLE
development server stuck in ActiveSupport::FileUpdateChecker

### ISSUE THREAD

**Issue by damsonn** [rails/rails#21963]
I got a problem on my rails 4.2.4 project. The auto reload seems to be going in an endless loop and get the server (development) stuck.

Here is how I reproduce it locally.
1. `rails server`
2. `watch -n1 curl http://localhost:3000/api/v1/status`
3. `touch app/controllers/application_controller.rb`
Then the *curl* request hangs and the server goes to 100% cpu.

Unfortunately I can't figured out a way to reproduce it in an example project (and I can't show you my project).

Here is a screenshot of the calltree I got from  [ruby-prof](https://github.com/ruby-prof/ruby-prof)
<img width="1124" alt="screen shot 2015-10-15 at 5 33 11 pm" src="https://cloud.githubusercontent.com/assets/2840366/10510027/fba74f0a-7362-11e5-8a8d-c0032401c698.png">

**Comment by rafaelfranca** [comment]
Unfortunately without a way to reproduce there is no much what we can do to help. :cry:

**Comment by damsonn** [comment]
YeahI know... I thought maybe you saw something similar or could point me in the right direction. I'll keep digging ;-)

**Comment by rafaelfranca** [comment]
Yes, that is fine. I never saw it but maybe someone did. This is why I didn't closed the issue yet.

**Comment by damsonn** [comment]
sorry just found out why. one of our dev added the following, which seems to be the cause the problem :
```
ActiveSupport::Dependencies.explicitly_unloadable_constants << 'API' if Rails.env.development?
```
