### ISSUE TITLE
Add :enum as field type in model generator

### ISSUE THREAD

**Issue by Epigene** [rails/rails#21970]
__labels: enum; enhancement__

Could be handy to be able to do

```
rails g model User user_type:enum
```

and get a migration

```ruby
class CreateUsers < ActiveRecord::Migration
  def change
    create_table :users do |t|
      t.integer :user_type, index: true, null: false, default: 0     

      t.timestamps null: false
    end
  end
end

```

**Comment by davidcelis** [comment]
Ideally this sort of thing would also throw a line into the model for `enum user_type: [:values]` but this seems like a potentially weird generator field unless there's a reasonable way to pass in the possible values during generation

**Comment by Epigene** [comment]
@davidcelis That would sure be nice to also touch the model.  
I can only add that I would prefer the generated enum line use the hash syntax as I argue [here](https://github.com/bbatsov/rails-style-guide/pull/158) and, maybe, leave the line commented out?  

So `rails g model User user_type:enum` begets a model

```ruby
class User < ActiveRecord::Base
  # enum user_type: { example_1: 0, example_2: 1 }
end
```

**Comment by rafaelfranca** [comment]
Thank you for the suggestion but I don't want o give enum this kind of importance to have a specific generator option, mainly because it is not something common to have in models
