### ISSUE TITLE
Unsupported argument type: Arel::Nodes::Equality on save or valid?

### ISSUE THREAD

**Issue by alanwilhelm** [rails/rails#21984]
Simple User.create(:foo => 'bar') throws this randomly. User.new is fine. valid? on an unsaved object throws the same error.

**Comment by rafaelfranca** [comment]
You need to give us more information on how to reproduce this issue, otherwise there is nothing we can do. Please read CONTRIBUTING.md file for more information about creating bug reports. Thanks!
