### ISSUE TITLE
link_to '/file.txt' doesn't respect RAILS_RELATIVE_URL_ROOT

### ISSUE THREAD

**Issue by VorontsovIE** [rails/rails#21983]
I've an app which use `RAILS_RELATIVE_URL_ROOT` with a url-prefix of my app. When I work with controller actions everything works nice, but when I give a link to a static file in `/public` folder - this URL goes as is without URL-prefix. 
A far as I understood, `link_to` yield path to `url_for` and `url_for(String)` just returns it back.
I wonder if it's safe to check whether path starts with a `/` character and append URL-prefix from `RAILS_RELATIVE_URL_ROOT`? Are there any conventional ways to generate links to static files considering URL root rather than gluing strings?

**Comment by pixeltrix** [comment]
@VorontsovIE the long standing convention with `link_to` is that if you pass it a string it's treated as a fully formed URL and the only way to do anything different would be to parse the string and inspect the host value which would undoubtably lead to all sort of new bugs - for example what if '/file.txt' is meant to be at the site root and not relative? How would Rails tell one from the other? In these circumstances it's best to leave it up to the application to interpret - it's simple enough to add a helper method that would prefix the path for you, e.g:

``` ruby
module ApplicationHelper
  def relative_url(path)
    "#{Rails.application.config.relative_url_root}#{path}"
  end
end
```

So I think that changing anything here runs the risk of causing a slowdown in performance as well as breaking existing apps - so I'll have to close it as a won't fix, sorry.
