### ISSUE TITLE
javascript_include_tag silently fails

### ISSUE THREAD

**Issue by ror6ax** [rails/rails#21997]
I'm calling javascript_include_tag to include a Angular.js file into a page. Now, while other JS files can be seen in full detail via Firefox'es Network Monitor, it looks like these Angular files cannot be actually seen:
`(function() {
`
`}).call(this);
`

Their content is trivial JS code, nothing extraordinary.
`Rails.application.config.assets.precompile` is called do precompile those as well as other JS files that work fine.

I'm no wizard in these things, but I presume `call(this)` is a wrapper around JS code inside of it. Now, the questions are - why does including of empty line does not call some kind of exception and why does this happen to some of my files, while others load OK?

Thanks.

**Comment by matthewd** [comment]
Please use the mailing list or StackOverflow for questions/help, where a wider community will be able to help you. We reserve the issues tracker for issues only.
