### ISSUE TITLE
Improper assertion for ActiveRecord test for proper scope inheritance

### ISSUE THREAD

**Issue by mtodd** [rails/rails#21993]
I've ["reproduced" a scenario][reproduce] where [`InheriteanceTest#test_scope_inherited_properly`][test] *does* raise an exception which leads me to believe that this test isn't adequately implemented. The error I get follows:

```
ActiveRecord::ConfigurationError: Association named 'account' was not found on Company; perhaps you misspelled it?
```

The full stacktrace is below.

The test only asserts that building an `ActiveRecord::Relation` doesn't raise an exception for a scenario that could lead to improper scope inheritance.

When I change the line:

``` ruby
assert_nothing_raised { Company.of_first_firm }
```

to:

``` ruby
assert_nothing_raised { Company.of_first_firm.to_sql }
```

This forces the `ActiveRecord::Relation` to `build_arel` and reflect on the associations of the join dependency, triggering the exception to raise.

Without this change (or executing the query), we don't really know if the associations are properly inherited because `ActiveRecord::Relation` is lazy about reflecting on associations for joins.

## Fix

I have a fix being prepared, assuming that this is a simple typo (my current hunch).

## Exception & Stacktrace

```
InheritanceTest#test_scope_inherited_properly:
ActiveRecord::ConfigurationError: Association named 'account' was not found on Company; perhaps you misspelled it?
    /opt/boxen/rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/bundler/gems/rails-dd2c94aea6de/activerecord/lib/active_record/associations/join_dependency.rb:217:in `find_reflection'
    /opt/boxen/rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/bundler/gems/rails-dd2c94aea6de/activerecord/lib/active_record/associations/join_dependency.rb:222:in `block in build'
    /opt/boxen/rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/bundler/gems/rails-dd2c94aea6de/activerecord/lib/active_record/associations/join_dependency.rb:221:in `each'
    /opt/boxen/rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/bundler/gems/rails-dd2c94aea6de/activerecord/lib/active_record/associations/join_dependency.rb:221:in `map'
    /opt/boxen/rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/bundler/gems/rails-dd2c94aea6de/activerecord/lib/active_record/associations/join_dependency.rb:221:in `build'
    /opt/boxen/rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/bundler/gems/rails-dd2c94aea6de/activerecord/lib/active_record/associations/join_dependency.rb:98:in `initialize'
    /opt/boxen/rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/bundler/gems/rails-dd2c94aea6de/activerecord/lib/active_record/relation/query_methods.rb:966:in `new'
    /opt/boxen/rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/bundler/gems/rails-dd2c94aea6de/activerecord/lib/active_record/relation/query_methods.rb:966:in `build_joins'
    /opt/boxen/rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/bundler/gems/rails-dd2c94aea6de/activerecord/lib/active_record/relation/query_methods.rb:882:in `build_arel'
    /opt/boxen/rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/bundler/gems/rails-dd2c94aea6de/activerecord/lib/active_record/relation/query_methods.rb:869:in `arel'
    /opt/boxen/rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/bundler/gems/rails-dd2c94aea6de/activerecord/lib/active_record/relation/query_methods.rb:96:in `bound_attributes'
    /opt/boxen/rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/bundler/gems/rails-dd2c94aea6de/activerecord/lib/active_record/relation.rb:606:in `to_sql'
    ./active_record_master.rb:67:in `block in test_scope_inherited_properly'
    /opt/boxen/rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/bundler/gems/rails-dd2c94aea6de/activesupport/lib/active_support/test_case.rb:85:in `assert_nothing_raised'
    ./active_record_master.rb:67:in `test_scope_inherited_properly'
```

[reproduce]: https://gist.github.com/mtodd/6e40adff3ba0459c34a3
[test]: https://github.com/rails/rails/blob/dd2c94aea6de51b58f75f192e5de16e791b9d2d9/activerecord/test/cases/inheritance_test.rb#L354-L357

**Comment by mtodd** [comment]
I've opened https://github.com/rails/rails/pull/21994 to address this but I'm not totally convinced that is the correct solution/implementation: was the original intent to associate via the `has_one :account`? How do I know `has_one` associations are properly inherited?

I was hoping https://github.com/mtodd/rails/commit/b780f9581c76ef1176409036b2fdcc2a84acfbf3 was going to built but I should've created the PR after pushing that commit first, then push the "fix" after.

cc @carlosantoniodasilva because you're assigned on https://github.com/rails/rails/pull/21994

**Comment by mtodd** [comment]
The test was introduced in https://github.com/rails/rails/pull/12084 (see referenced issues/pulls therein).

**Comment by arthurnn** [comment]
thanks
