### ISSUE TITLE
Typecasting float to decimal with specified precision broken in 4.2

### ISSUE THREAD

**Issue by nestegg** [rails/rails#22006]
In activerecord/lib/active_record/type/decimal.rb
```ruby
      def convert_float_to_big_decimal(value)
        if precision
          BigDecimal(value, float_precision)
        else
          value.to_d
        end
      end
```
BigDecimal() is used incorrectly.  The second parameter is NOT precision, it's significant digits.  Hence:

```ruby
BigDecimal(123.456789, 3).to_s  =>  "123.0"  # rather than "123.456"
```
Maybe this should be:

```ruby
BigDecimal(value).round(float_precision)
```

**Comment by rafaelfranca** [comment]
Could you try 4-2-stable branch?

**Comment by nestegg** [comment]
This is from 4-2-stable, but as far as I can tell it effects everything from 4.2.0 on.

**Comment by rafaelfranca** [comment]
According with PostgreSQL documentation this behavior is correct:

> The scale of a numeric is the count of decimal digits in the fractional part, to the right of the decimal point. The precision of a numeric is the total count of significant digits in the whole number, that is, the number of digits to both sides of the decimal point.

If the precision is 3 so `123.0` is the expected result in your example.

**Comment by rafaelfranca** [comment]
I asked about 4-2-stable because I applied this patch https://github.com/rails/rails/commit/0b94384bef44535a408b034e44b90d08318e258a there and it was to correct this behavior.

**Comment by nestegg** [comment]
mea culpa, this represented a change in behavior from 4.1 which broke a test case.  In creating an isolated test, scale and precision got mixed up in the migration.  I understand what's happening.  I apologize.
