### ISSUE TITLE
ActiveRecord calculation raises EagerLoadPolymorphicError when #includes uses a polymorphic association

### ISSUE THREAD

**Issue by rwadstein** [rails/rails#22007]
Back in Rails 3 we could make a query like so:
`Invoice.includes(:transaction_record => :origin).sum('dr')` where `:origin` was a nested polymorphic association on the associated `:transaction_record`.
In Rails 4, that same query is now assuming the `includes` is a `join` which raises the polymorphic error.
This is due to the the code [here](https://github.com/rails/rails/blob/master/activerecord/lib/active_record/relation/calculations.rb#L193)
because we are using the #sum method.
This was only introduced in this commit: https://github.com/rails/rails/commit/1f98493e4a3c53e53666ff740860b20dcd6d08ec#diff-e0e70620d0897d6819a6bcc2b5ee7a73R111 where it validates that a `column_name` is specified

This is implicitly converting an `includes` to be a join directly in the query, and essentially brings back the N+1 problem, but  `includes` was supposed to eager load data.

For summing a column that is not even from the nested association, why does it need to join?
Obviously, we can remove the `:origin` from includes, but that just brings back the N+1 problem for us.

**Comment by rwadstein** [comment]
I dug a little more and the N+1 problem does not come back which is good.

In order to be able to convert `includes` to `joins` in order to accommodate `pluck` and other calculation methods, as well as be able to use eager loaded polymorphic `includes` with those same methods, we could exclude polymorphic associations.  Those associations could be excluded only under the specific condition of knowing they came via an `includes` statement.

E.g. Possibly something like this in the active_record/associations/join_dependency.rb
```ruby
def build(associations, base_klass)
  mapping = associations.map do |name, right|
    reflection = find_reflection base_klass, name
    reflection.check_validity!
    reflection.check_eager_loadable!

    # Skip the polymorphic association if it was defined via an :include statement
    next if reflection.polymorphic? && reflection.include_value?
  
    if reflection.polymorphic?
      raise EagerLoadPolymorphicError.new(reflection)
    end

    JoinAssociation.new reflection, build(right, reflection.klass)
  end
  mapping.compact
end
```

`reflection.include_value?` would be the only new piece and would allow polymorphic eager loaded associations to continue to work.

**Comment by waiting-for-dev** [comment]
This is still an issue... The polymorphic association does not need to be nested, so, in order to reproduce it, it is enough to do something like:

```ruby
Model.all.includes(:polymorhic_association).sum(:field)
```

Tested in Rails 5.0.3

**Comment by saveriomiroddi** [comment]
Still an issue as of v5.2.3; @waiting-for-dev's test case applies also to us, with the difference that we use `pluck()`.

**Comment by Hareramrai** [comment]
Still an issue with Rails 6.1.3, my code snippet is `Image.includes(:imageable).pluck :title`
