### ISSUE TITLE
Attacking Ruby on Rails

### ISSUE THREAD

**Issue by miles** [rails/rails#22014]
FYI

http://phrack.org/papers/attacking_ruby_on_rails.html

**Comment by mrtorks** [comment]
@rafaelfranca

**Comment by matthewd** [comment]
The mailing list seems a more appropriate forum to discuss this

**Comment by azul** [comment]
Haven't seen it discussed on the core, security announce or talk lists.
@matthewd - is there another list I'm missing or has this not been discussed yet?
