### ISSUE TITLE
image_tag not worked when config.assets.digest = false in development.

### ISSUE THREAD

**Issue by zw963** [rails/rails#22017]
Change config.assets.digest = false in config/environments/development.rb

```erb
<% url = ActionController::Base.helpers.asset_path('fallback/avatar.gif') %>
# url = '/assets/fallback/avatar.gif'
<%= image_tag url %> 

ActionView::Template::Error (Asset names passed to helpers should not include the "/assets/" prefix. Instead of "/assets/fallback/avatar.gif", use "fallback/avatar.gif")
```

I think in this special case (`assets.digesst = false`),  /assets/fallback/avatar.gif should be a valid
args for image_tag.

**Comment by zw963** [comment]
If change to:
```erb
<% url = ActionController::Base.helpers.asset_path('fallback/avatar.gif').sub(%r{^/assets/}, '') %>
<%= image_tag url %> 
```
it not worked in production, because the img tags is: 
```erb
<img alt="buyer" class="avatar" src="/images/fallback/avatar-6eee006c1c4aabcf44ea49a711e0a7540400036eaa77aedd5865d6a9e99df967.gif">
```

How could i make following three case work well together?

1. config.assets.digest = false
2. use ActionController::Base.helpers.asset_path('fallback/avatar.gif') generate a image url
3. use this url in image_tag helper

**Comment by zw963** [comment]
I understood the philosophy about this, thanks.

perhaps this not a bug,  what i need is just
```erb
<%= image_tag 'fallback/avatar.gif' %>
```
let image_tag to do the assets transformation for me, it worked in production
 and development.

Though, I still think when set `config.assets.digest = false`, image_tag should not
recognize '/assets/fallback/avatar.gif' as invalid format and raise a ActionView::Template::Error.

**Comment by sgrif** [comment]
The error message tells you exactly what you need to do.
