### ISSUE TITLE
Make secrets.yml optional when session store is disabled?

### ISSUE THREAD

**Issue by lukehorvat** [rails/rails#22015]
For some of my apps, I have `Rails.application.config.session_store :disabled` configured, rendering `secrets.yml` unnecessary (but please correct me if I am wrong about this). Can we disable the secrets checks ([here](https://github.com/rails/rails/blob/4-2-stable/activesupport/lib/active_support/key_generator.rb#L58-L71) and [here](https://github.com/rails/rails/blob/4-2-stable/railties/lib/rails/application.rb#L528-L537)) when this is the case?

**Comment by jeremy** [comment]
`secrets.yml` is for any other secure config, too! The cookie secret happens to be the only thing in there by default, but dropping cookies doesn't remove the need for keeping sensitive data out of the source repos.

**Comment by lukehorvat** [comment]
A bit annoying if your app doesn't have any secrets. :disappointed:
