### ISSUE TITLE
Rails error: Model naming convention with `ve` ending

### ISSUE THREAD

**Issue by CQBinh** [rails/rails#22036]
## Background
In English, noun in sungular that ending with `fe` will be transformed to `ves` in plural.

For example: `cafe` -> `caves` or `wife` -> `wives`.
## What do rails does?
When you name your model with the `ve`-ending (`thank_give` for example).
Your `model` in plural is `ThankGives`, and rails treats the singular as `ThankGife` (not `ThankGive` as expected).
### Relationship
One `ThankGive` belongs to one `User`.
One `User` has many `ThankGive`.
#### One `User` has many `ThankGive`
```
irb(main):002:0> User.first.thank_gives
  User Load (0.5ms)  SELECT  `users`.* FROM `users`  ORDER BY `users`.`id` ASC LIMIT 1
NameError: uninitialized constant User::ThankGife
```
I have pushed a demo project to [github](https://github.com/CQBinh/Rails-error-ve-ending-model-name) to explain more about this issue. Please read more at README.
I don't know how to fix it. Currently, I'm thinking about use another model name.

**Comment by rafaelfranca** [comment]
Yes, that is because the default inflections rules are like that. The default inflections rules are frozen and will be not changed in the framework so if you want the proper rule you can change your application inflections to do what you expect.
