### ISSUE TITLE
Destroy associated records in before_destroy Hook (4.2.4)

### ISSUE THREAD

**Issue by krisdigital** [rails/rails#22046]
I am facing a strange behavior when trying to destroy associated objects.

The association is "an Event has_many appointments through apoointment_assignments", which is a polymorphic join table.

``` ruby
has_many :appointment_assignments, as: :appointable
has_many :appointments, through: :appointment_assignments
accepts_nested_attributes_for :appointments, allow_destroy: true, reject_if: proc {|a| a[:url].blank?}
```

Because I do not only want the associations to be destroyed, I create a before_destroy callback

``` ruby
before_destroy :destroy_appointments

def destroy_appointments
      self.appointments.destroy_all
end
```

Running this TestCase Fails

``` ruby
require 'test_helper'

class EventTest < ActiveSupport::TestCase
  def setup
    @event = events(:one)
  end

  test "delete appointments" do
    assert_equal(1, @event.appointments.count)

    assert_difference('Appointment.count', -1) do
      @event.destroy
    end
  end
end
```

Now the strange thing:
If I write

``` ruby
def destroy_appointments
    Appointment.where(id: self.appointments.map(&:id)).destroy_all
end
```

the appointments get destroyed..

Does anybody have a clue, why this could happen? Is it a bug?

**Comment by al2o3cr** [comment]
Not sure why that's happening. What SQL does running the failing test produce in the logs?

BTW, if you want to have `AppointmentAssignment` records automatically destroyed when their `Appointment` is destroyed you should add `dependent: :destroy` to the association in `Appointment`:
```ruby
class Appointment < ActiveRecord::Base
  ...
  has_many :appointment_assignments, dependent: :destroy
  ...
end
```

**Comment by krisdigital** [comment]
Thanks for answering @al2o3cr.
The Logs from the test run only say that the assignments are deleted:

```
Appointment Load (0.3ms)  SELECT "appointments".* FROM "appointments" INNER JOIN "appointment_assignments" ON "appointments"."id" = "appointment_assignments"."appointment_id" WHERE "appointment_assignments"."appointable_id" = $1 AND "appointment_assignments"."appointable_type" = $2  [["appointable_id", 980190962], ["appointable_type", "Event"]]
AppointmentAssignment Load (0.3ms)  SELECT "appointment_assignments".* FROM "appointment_assignments" WHERE "appointment_assignments"."appointable_id" = $1 AND "appointment_assignments"."appointable_type" = $2 AND "appointment_assignments"."appointment_id" = 980190962  [["appointable_id", 980190962], ["appointable_type", "Event"]]
SQL (0.3ms)  DELETE FROM "appointment_assignments" WHERE "appointment_assignments"."id" = $1  [["id", 980190962]]
```

I have exactly the same line in my Appointment Class as you posted, good guess!

**Comment by swapnilchincholkar** [comment]
@krisdigital 

As appointments are through associated you need to dependently destroy intermediate object & through it delete an associated appointment. 
```
class Event < ActiveRecord::Base
  has_many :appointment_assignments, dependent: :destroy
  has_many :appointments, through: :appointment_assignments
  accepts_nested_attributes_for :appointments, allow_destroy: true, reject_if: proc {|a| a[:url].blank?}
end

class AppointmentAssignment < ActiveRecord::Base
  belongs_to :event
  has_many :appointments, dependent: :destroy
end

class Appointment < ActiveRecord::Base
  belongs_to :appointment_assignment
end
```

**Comment by krisdigital** [comment]
@swapnilchincholkar I am pretty sure I did that initially, but thank you. Even though the other way should work and I ask myself, why it does not, e.g. why self.appointments.destroy_all does not do anything. I will try in a minimal use case if I have the time and report back.
