### ISSUE TITLE
ActiveJob retry_job in rescue_from ActiveJob::DeserializationError retries with no arguments

### ISSUE THREAD

**Issue by DMA57361** [rails/rails#22044]
While I understand that most of the time if you can't deserialize a job's attributes then retrying it is probably not useful, however it is possible to get this exception under recoverable circumstances where retrying could be useful.

For example, we have been seeing some cases of `ActiveJob::DeserializationError` that were caused by an `ActiveRecord::ConnectionTimeoutError` - so the records passed as attributes exist, we just had a database cough at the wrong moment - trying again later should allow the job to run successfully. By examining the `cause` of the deserialization exception we retry only when the underlying problem was a connection timeout, however when we do this the recreated job is delivered to Sidekiq with no arguments and so immediately crashes when it is run.

Having had a dig around it seems that (unsurprisingly!) in a `rescue_from` block for an `ActiveJob::DeserializationError`, the job's `self.attributes` is empty, however the original serialized values are still stored in `@serialized_arguments`. For now, I've put a money patch into our application that extends the `serialize` method of `ActiveJob::Base` (from `ActiveJob::Core`), allowing a job to recycle the `@serialized_arguments` if they are present but the arguments were going to be returned empty.

**Comment by shawnstephens** [comment]
DMA57361 I have the same issue. Can you share the monkey patch?

**Comment by Burgestrand** [comment]
It's useful for more than retries. I ran into this error as well (Rails 5.0.0.1), but in the context of error handling. Without a patch around this, my error tracking log will not include the arguments given to the job; and the arguments are quite useful in debugging when jobs go bonkers.

```ruby
class ApplicationJob < ActiveJob::Base
  rescue_from StandardError do |exception|
    ExceptionTrackingThingy.track(exception, job: serialize)
    raise exception
  end

  # @see https://github.com/rails/rails/issues/22044
  def serialize
    serialized = super

    # @see https://github.com/rails/rails/blob/v5.0.0.1/activejob/lib/active_job/core.rb#L116
    if defined?(@serialized_arguments) && @serialized_arguments.present?
      serialized["arguments"] = @serialized_arguments
    end

    serialized
  end
end
```
