### ISSUE TITLE
action-mailer 4.2 render method called in mail method do end block does not honor custom default template_path

### ISSUE THREAD

**Issue by byrnejb** [rails/rails#22045]
By (problematic) design the render method when used in a do end block will not use an explicit template_path or template_name passed as an argument to the related mail method:

``` ruby
    mail( :to => recipients,
          :from => fm_address,
          :subject => subject,
          :template_path => "/custom/template/path"
        ) \
      do |format|
        format.text
      end
```

> Missing template hll_th_forex_mailer/hll_th_forex_commercial_rates_notice with 
> {:locale=>[:en], :formats=>[:text], :variants=>[], 
> :handlers=>[:erb, :builder, :raw, :ruby, :coffee, :jbuilder]}. 
> Searched in:
>        \* "/home/byrnejb/Projects/Software/theHeart/code/hll_th_main/app/views"

However, it also fails to honour a custom default path set using the default method on the calling class.  

``` ruby
class HllThForexMailer < ActionMailer::Base
  x = default( :template_path =>  "/custom/template/path"  )
  warn( x.inspect )
. . .
    mail( :to => recipients,
          :from => fm_address,
          :subject => subject
        ) \
      do |format|
        format.text
      end
```

> {:mime_version=>"1.0", :charset=>"UTF-8", :content_type=>"text/plain", 
> :parts_order=>["text/plain", "text/enriched", "text/html"], :template_path=>"/custom/template/path"}
> . . .
>      Missing template hll_th_forex_mailer/hll_th_forex_commercial_rates_notice with 
> {:locale=>[:en], :formats=>[:text], :variants=>[], 
> :handlers=>[:erb, :builder, :raw, :ruby, :coffee, :jbuilder]}.
> Searched in:
>        \* "/home/byrnejb/Projects/Software/theHeart/code/hll_th_main/app/views"
>        \* "/home/byrnejb/Projects/Software/theHeart/code/hll_th_main/libexec/bundle/lib/gems/declarative_authorization-0.5.7/app/views"
>        \* "/home/byrnejb/Projects/Software/theHeart/code/hll_th_main/libexec/bundle/lib/gems/devise_security_extension-0.9.2/app/views"
>        \* "/home/byrnejb/Projects/Software/theHeart/code/hll_th_main/libexec/bundle/lib/gems/devise-3.5.1/app/views"
>       (ActionView::MissingTemplate)

The expected action is that notwithstanding the questionable decision to ignore arguments passed to the related method the do block render method should at least use the default template_path set in the class from which it is called.

I strongly oppose the decision that the do block render method ignores some, but not all, of the arguments passed to the preceding mail method.  Selectively excluding the `:template_name` and `:template_path` keys is non-intuitive to say the least and is really a questionable design choice given that the render method does not appear to support passing an absolute path to a custom view (it always removes the leading '/'). This combination makes such arrangements difficult if not impossible to implement.

**Comment by jpaas** [comment]
I can confirm this is still an issue on Rails 5.0.0

In a scenario like this...
```ruby
def normal_action
    mail(
      from: from_support,
      subject: "will use the wrong template",
      template_name: "custom"
      to: @user.email
    ) do |format|
      format.html { render layout: 'mailer_bulk', template_name: "custom" }
      format.text { render layout: 'mailer_bulk', template_name: "custom" }
    end
end
```

It will render with the 'normal_action' template instead of the 'custom' template.

**Comment by cmrd-senya** [comment]
To workaround this I used the following approach:
```ruby
def normal_action
    mail(
      from: from_support,
      subject: "will use the wrong template",
      template_name: "custom"
      to: @user.email
    ) do |format|
      self.action_name = "custom"
      format.html { render layout: 'mailer_bulk'}
      format.text { render layout: 'mailer_bulk'}
    end
end
```

**Comment by jpaas** [comment]
Ooh nice workaround. I'll try that. Thanks!
