### ISSUE TITLE
Windows 10: AbstractController complains about non-existent file 

### ISSUE THREAD

**Issue by rodrigoargumedo** [rails/rails#22058]
I made a empty Rails application using Ruby 2.2.3p173 and set up everything correctly from scratch. I find this so strange that it gave me this AbstractController error, which outputs:

    Started GET "/" for ::1 at 2015-10-24 21:58:25 -0500

    AbstractController::Helpers::MissingHelperError (Missing helper file helpers/c:/users/rodrigo/documents/code/go_app/app/helpers/application_helper.rb_helper.rb):
    app/controllers/application_controller.rb:1:in `<top (required)>'

     Rendered C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/actionpack-4.2.4/lib/action_dispatch/middleware/templates/rescues/_source.erb (1.0ms)
     Rendered C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/actionpack-4.2.4/lib/action_dispatch/middleware/templates/rescues/_trace.html.erb (4.0ms)
     Rendered C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/actionpack-4.2.4/lib/action_dispatch/middleware/templates/rescues/_request_and_response.html.erb (1.0ms)
     Rendered C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/actionpack-4.2.4/lib/action_dispatch/middleware/templates/rescues/diagnostics.html.erb within rescues/layout (839.6ms)
     Rendered C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/web-console-2.2.1/lib/web_console/templates/_markup.html.erb (0.0ms)
     Rendered C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/web-console-2.2.1/lib/web_console/templates/_inner_console_markup.html.erb within layouts/inlined_string (0.0ms)
     Rendered C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/web-console-2.2.1/lib/web_console/templates/_prompt_box_markup.html.erb within layouts/inlined_string (0.0ms)
     Rendered C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/web-console-2.2.1/lib/web_console/templates/style.css.erb within layouts/inlined_string (0.0ms)
     Rendered C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/web-console-2.2.1/lib/web_console/templates/console.js.erb within layouts/javascript (757.5ms)
     Rendered C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/web-console-2.2.1/lib/web_console/templates/main.js.erb within layouts/javascript (0.0ms)
     Rendered C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/web-console-2.2.1/lib/web_console/templates/error_page.js.erb within layouts/javascript (1.0ms)
     Rendered C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/web-console-2.2.1/lib/web_console/templates/index.html.erb (1741.1ms)

To reproduce this bug and test it against in Windows 10:

    rails new app_name --skip-bundle # because nokogiri 1.6.7 is not released yet but use 1.6.7rc3 instead
    generate a controller with resources in routes
    fix MissingTemplate errors
    open Chrome, Firefox or MS Edge and type localhost:3000
    then you run into the error

Can anyone confirm this bug?

Edit: This is where the [error](https://github.com/rails/rails/blob/master/actionpack/lib/abstract_controller/helpers.rb#L15-L27) was coming from.

**Comment by al2o3cr** [comment]
This seems like it may be related to #18660 - the doubled `_helper.rb` is a common symptom of both.

**Comment by rafaelfranca** [comment]
Yeah. Closing in favor of that issue.
