### ISSUE TITLE
Additional tmp:clear locations

### ISSUE THREAD

**Issue by amnesia7** [rails/rails#22050]
Would it be possible to be able to add additions to what `tmp:clear` can perform?

I'm thinking along the lines of; capybara can generate static versions of pages to help debug using `save_and_open_page` which get saved in `/tmp/capybara/` but as far as I'm aware it is up to the developer to configure something to empty these out as they can build up over time.

What if capybara could register a tmp folder with rails that could be included in `tmp:clear` as well as having its own `tmp:capybara:clear` or something like that so that these can be run more easily?

The equivalent could be added by any other gems that feel the need to generate files in the `tmp` folder area so that they can be tidied up as well.

**Comment by senny** [comment]
[`bin/rake tmp:clear`](https://github.com/rails/rails/blob/master/railties/lib/rails/tasks/tmp.rake#L3) is a very basic task. Other railties can easily extend it:

```
task "tmp:capybara:clear" do
  # ...
end

task "tmp:clear" => ["tmp:capybara:clear"]
```

I don't think Rails needs to provide more functionality here. The basic workings of Rake should be sufficient.

**Comment by amnesia7** [comment]
Ok doke, thanks @senny
