### ISSUE TITLE
'Rails.application.config.relative_url_root' does not alter route helpers output.

### ISSUE THREAD

**Issue by maxcal** [rails/rails#22074]
As per the documentation on http://guides.rubyonrails.org/configuring.html#deploy-to-a-subdirectory-relative-url-root I set the ENV var `RAILS_RELATIVE_URL_ROOT = "/app1"`.

I setup a basic route:

```
Rails.application.routes.draw do
  root 'pages#home'
  resources :cats, only: [:show, :index]
end
```

To test this I output:

```
# views/pages/home.html.erb
<pre>
  <%= cats_url %>
  <%= cats_path %>
  <%= Rails.application.config.relative_url_root %>
</pre>
```

The output is:

```
  http://localhost:3000/cats
  /cats
  /app1
```

Not `http://localhost:3000/app1/cats` as could be expected.

Sorry if there is no test to go along with this issue but I currently have really limited bandwidth and cannot download the whole rails repo to set it up.

**Comment by arunagw** [comment]
As I can see in current version by setting this every assets gets this path appended.

**Comment by maxcal** [comment]
Forgot to mention this was tested on 4.2.1

**Comment by jon2992** [comment]
Just glancing, it looks like [this line](https://github.com/rails/rails/blob/v5.0.0.rc1/actionpack/lib/action_dispatch/routing/mapper.rb#L664) may be the problem. It's freezing that option as an empty string rather than pulling the config in and using it.

**Comment by SxDx** [comment]
Stil happening on Rails 4.2.6

**Comment by maclover7** [comment]
Going to close this ticket as a duplicate, in favor of #24393, since there is more info on that ticket.
