### ISSUE TITLE
rails server Segmentation fault 0x00000000000071

### ISSUE THREAD

**Issue by DarkNath** [rails/rails#22079]
I'm using ruby 2.1.0p0 (2013-12-25 revision 44422) [x86-64_linux] (installated with rbenv) 

and rails 4.0.11 and when i run the command 'bundle exec rails s', i get a segmentation fault. 

Here is the trace: http://pastebin.com/LpjXRmvu

Regards

**Comment by al2o3cr** [comment]
@DarkNath Not sure if it's related, but the `debugger` gem is only supported on Ruby 1.9.x, not 2.1.0 (from the [README](https://github.com/cldwalker/debugger#known-issues)). Does the issue still manifest if you remove it?

**Comment by rafaelfranca** [comment]
Also segfaults are never Rails issue because Rails don't have any C extentions code.
