### ISSUE TITLE
Controller generators should be creating IntegrationTest stubs instead of ControllerTest

### ISSUE THREAD

**Issue by dhh** [rails/rails#22076]
ActionController::TestCase is deprecated. Let's get the controller test generation using our ActionDispatch::IntegrationTest future instead.

**Comment by seuros** [comment]
I will work on it.

**Comment by dhh** [comment]
👍❤️

**Comment by kaspth** [comment]
Weren't these deprecated a long time ago? We should probably remove any remnants too.

**Comment by dhh** [comment]
Kasper, "long time" in development time, but not in release time. They have
not been deprecated in any public release.

**Comment by kaspth** [comment]
Ah! I read `ActionController::TestCase` as `ActionController::IntegrationTest` (which I saw in a deprecation warning when upgrading an app to 4.0 recently). Never mind :grin:

**Comment by dhh** [comment]
@seuros Did you make any progress on this?

**Comment by chareice** [comment]
Why?
