### ISSUE TITLE
Making ActiveSupport::TimeZone.MAPPING a data file

### ISSUE THREAD

**Issue by scottconnerly** [rails/rails#22088]
RE: https://github.com/rails/rails/blob/master/activesupport/lib/active_support/values/time_zone.rb

I'm a PHP developer. Our application environment can only give us the FULL list of time Zones (and the Links too) in one 417 item object. I've been hunting for this beautifully named and concise list (of currently 149) that you maintain in ActiveSupport::TimeZone. If you were to make that data available to the rest of the programming world by way of a CSV or JSON file or something (that we could pull in every so often into our projects), I'd be eternally grateful.

FYI, companion request logged to PHP team:
https://bugs.php.net/bug.php?id=70801

**Comment by rafaelfranca** [comment]
Related with #13852.

If that change is implemented we may extract it to a YAML file but there is no promise about it.

I'm closing this issue since we don't take feature requests in the issue tracker but it is linked to the PR so we can reference this issue when implementing.

**Comment by scottconnerly** [comment]
FYI, here is the repo I made to scrape time_zone.rb.
https://github.com/scottconnerly/timezone
If/when you do move it to a YAML, please let me know, and I'll update my repo to pull from that.

Thanks
