### ISSUE TITLE
Rake task initializers

### ISSUE THREAD

**Issue by tak1n** [rails/rails#22085]
When running `rake db:migrate` the initializers are executed but when running `rake db:create` they are not. Is this the appropriate behavior because it feels kinda inconsistent?

For now we solved it through appending this to our Rakefile:

```ruby
namespace :db do
  task :create => :environment
end
```

**Comment by rafaelfranca** [comment]
Yes. It is the appropriate behavior. We avoid loading the environment if it is not needed, and to create the database it is not

**Comment by nicksterious** [comment]
Interestingly, `rake db:` tasks don't load the environment, but they do load models and if a model depends on something set in an initializer (eg `self.table_name`) then the task fails.
