### ISSUE TITLE
mismatch setting and preloading of polymorphic association for STI models

### ISSUE THREAD

**Issue by senid231** [rails/rails#22089]
let see we have polymorphic table
```ruby
class DB::Document < ActiveRecord::Base
  # documentable_type, documentable_id
  belongs_to :documentable, polymorphic: true
end

class DB::Ticket < ActiveRecord::Base
  has_one :document, as: :documentable
 
  def self.find_sti_class(type_name)
    ActiveSupport::Dependencies.constantize("DB::Ticket::#{sti_type_for(type_name)}")
  end

  self.inheritance_column = :type
  self.store_full_sti_class = false

  def self.sti_name
    self.to_s.split('::').last
  end

end

class DB::Ticket::Train < DB::Ticket
end

class Ticket::Airplain < DB::Ticket
end
```

when we set association:
```ruby
doc = Document.new
doc.documentable = DB::Ticket::Train.first! # docuementable_type will be 'DB::Ticket'
```
when we preload polymorphic association:
```ruby
DB::Ticket.where(id: [1,2]).preload(:document).to_a
# SELECT * FROM documents WHERE documentable_id IN (1,2) AND documentable_type = 'Ticket'
```

i think its because on association.writer it uses `name` of base_class
```ruby
module ActiveRecord
  # = Active Record Belongs To Polymorphic Association
  module Associations
    class BelongsToPolymorphicAssociation < BelongsToAssociation #:nodoc:
      ...

        def replace_keys(record)
          super
          owner[reflection.foreign_type] = record.class.base_class.name
        end

      ...
    end
  end
end
```
and on preloading it uses `sti_name` of base_class
```ruby
module ActiveRecord
  module Associations
    class Preloader
      class Association #:nodoc:
        ...

        def build_scope
          scope = klass.unscoped
          ...

          if options[:as]
            scope.where!(klass.table_name => { reflection.type => model.base_class.sti_name })
          end

          ...
        end

        ...
      end
    end
  end
end
```

**Comment by senid231** [comment]
i change `sti_name` method to fix this issue
```ruby
def self.sti_name
    if self.base_class == self
      self.to_s
    else
      self.to_s.split('::').last
    end
end
```
but it smells

**Comment by pixeltrix** [comment]
As discussed in #4729 and #5441 the fact that `belongs_to polymorphic: true` uses `base_class` is intentional - it indicates where to look for the records and not what class to use when instantiating the object which is where the `type` column on the table comes in. For your schema you don't need to use `polymorphic: true` since all of the records are in the same table - just organise your models like this:

``` ruby
class DB::Document < ActiveRecord::Base
  belongs_to :ticket
end

class DB::Ticket < ActiveRecord::Base
  has_one :document
end

class DB::Ticket::Train < DB::Ticket; end
class DB::Ticket::Airplane < DB::Ticket; end
```

There's no need to mess with the defaults for `store_full_sti_class` or anything else.

**Comment by al2o3cr** [comment]
@pixeltrix Certainly true in this particular example, but it shouldn't be difficult to construct an example where overriding `sti_name` doesn't work quite right. For instance, I suspect that doing that may be a way out of situations like #22089. I'll see if I can construct a more-realistic reproduction for this issue.

**Comment by senid231** [comment]
@pixeltrix, it is just small example of problem. I know that I should use polymorphic only if it can belongs to diferent entities from different tables. i show particular case when preload doesn't work right
(I added `DB::Cargo` model to first post. example should be more understandable now)
