### ISSUE TITLE
The way we write code of controllers in mountable engines should be the same as the main application's ones.

### ISSUE THREAD

**Issue by claudix** [rails/rails#22098]
I've been struggling for a long time to find out what was making my web application go wrong. You can read the full story [here](http://stackoverflow.com/questions/33387039/rails-sometimes-issues-nomethoderror-when-calling-an-inherited-method-from-an-en/33388108). 

In summary, I discovered that controllers in mountable plugins must contain a `require_dependency` line at the top of the controller file. Otherwise Rails works in a erratic way, as explained in the link above.

Controllers in a standard Rails application are written following the pattern below:

``` ruby
# foo_controller.rb:
class FooController < ActionController::Base
  # Stuff
end
```

But in mountable plugins, controllers must make explicit that they inherit from the ApplicationController defined in the module itself! (i.e. isolated from the main app):

``` ruby
# Plugin's application_controller.rb:
module MyPlugin
  class ApplicationController < ActionController::Base
  end
end

# Plugin's bar_controller.rb:
require_dependency "my_plugin/application_controller"  # <-- Why this line??
module MyPlugin
  class BarController < ApplicationController
  end
end
```

Since I wrote the controller by hand (not using scaffolding), that missing line made my app have a strange behaviour. Why can't controllers in isolated plugins be written in the same way as main application's ones?

**Comment by rafaelfranca** [comment]
@fxn do you know about this?

**Comment by fxn** [comment]
@rafaelfranca no, but from the description I suspect it is a case of [this gotcha](http://guides.rubyonrails.org/autoloading_and_reloading_constants.html#when-constants-aren-t-missed).

**Comment by claudix** [comment]
Good point @fxn ... If it's just a gotcha and no fixing is planned, I think this issue should be at least documented in the [Getting Started With Engines](http://guides.rubyonrails.org/engines.html). That's the entry point of anyone who starts writing engines and the tutorial doesn't say a word about this (maybe because it's assumed the reader will use scaffoling).

**Comment by fxn** [comment]
@claudix yeah... as you see it is an intrinsic problem. Saying something in the guide sounds great, maybe a warning in [this section](http://guides.rubyonrails.org/engines.html#overriding-models-and-controllers#app-directory#app-directory)?

**Comment by claudix** [comment]
Your link is broken but I guess you mean the ['app directory' section](http://guides.rubyonrails.org/engines.html#app-directory). I think it's the best place to put the warning into because there's currently a hint that is actually confusing (it somehow encourages the reader to write the controller as in a normal application):

    The ApplicationController class inside an engine is named 
    just like a Rails application in order to make it easier for you 
    to convert your applications into engines.

Obviously the point we're discussing here is missing in that statement. 

It's the first time I discuss in the Rails community. May I address this issue to someone in particular or is it enough by having this issue open?

**Comment by fxn** [comment]
@claudix I encourage you to write a patch with the warning if you liked to contribute to Rails. We have [some guidelines](http://edgeguides.rubyonrails.org/contributing_to_ruby_on_rails.html#contributing-to-the-rails-documentation), it would be a matter of opening a PR and cc for example me.

What do you think?

**Comment by claudix** [comment]
Sure, @fxn! I'll take a look at the guidelines and open a PR. May I contact you directly for questions/doubts about them? (segur que ens entendrem ;-) )

**Comment by fxn** [comment]
Macasundena ets català! I tant tio! 😀
