### ISSUE TITLE
Support PgBouncer in transaction-pooling mode

### ISSUE THREAD

**Issue by Sinjo** [rails/rails#22102]
An issue people frequently run into when scaling apps that use Postgres is high memory use per-connection on the Postgres server. This is commonly solved by running PgBouncer in transaction-pooling mode in front of Postgres to share those connections between many clients (Heroku [recommend this approach](https://devcenter.heroku.com/articles/concurrency-and-database-connections#limit-connections-with-pgbouncer) and even [have a buildpack for it](https://github.com/heroku/heroku-buildpack-pgbouncer).

The big caveat of transaction-pooling mode is that you [can't use session-level features of Postgres](https://wiki.postgresql.org/wiki/PgBouncer#Feature_matrix_for_pooling_modes) (e.g. session-level config, session-level advisory-locks).

Unfortunately, ActiveRecord makes use of connection-level settings, which are set during connection initialisation. In most cases, it's not a huge problem. You can use [PgBouncer's connect_query](https://pgbouncer.github.io/config.html#connectquery) to set the same settings as ActiveRecord (making the ActiveRecord `SET` commands effectively no-op).

However, in a notable exception, ActiveRecord temporarily [disables reporting of query errors](https://github.com/rails/rails/blob/f7d0a3ba7e9e676d399e7aeed7485a8bf03992f8/activerecord/lib/active_record/connection_adapters/postgresql_adapter.rb#L286). This leaves random server connections in a bad state, where they won't report any errors, including constraint violations (see #22101).

At a minimum, it feels like #22101 should be merged, and some documentation written for Rails users who are running PgBouncer (we're happy to write this).

It would also be nice to provide a flag which stops ActiveRecord from using connection-level settings. This would reduce instances of weird behaviour where people have a connect_query that is out of sync with what ActiveRecord does (which itself may change between releases).

From a quick search, other people are running into this in the wild:

* rails/rails#14864
* rails/rails#18027
* https://groups.google.com/forum/#!topic/ruby-pg/QaN4UaSvkyc

**Comment by matthewd** [comment]
> other people are running into this in the wild

What's "this"?

As written, this sounds like a discussion for the mailing list. Is there a specific issue we can fix? (Other than #22101)

**Comment by arthurnn** [comment]
i guess the issue and the fix are already on #22101 , so closing this

thanks

**Comment by Sinjo** [comment]
I'm cool with moving this to the mailing list if that's the right place. The thing I want to address specifically is to make it easy for people to get this right. It's a really subtle problem, and not too uncommon a setup.

The two ideas I have on that are providing documentation for using Rails with PgBouncer and adding a flag into ActiveRecord. Is the mailing list a better place for discussing those than here?

**Comment by arthurnn** [comment]
@Sinjo yeah I think this deserves a discussion indeed and you will get more thoughts on it from the mailing list.
thanks
