### ISSUE TITLE
I18n translations for labels used within fields_for

### ISSUE THREAD

**Issue by KevinSjoberg** [rails/rails#22117]
Translations for labels used in a form builder can be set using the following format:  

```
helpers.label.record.attribute
```

However when using `fields_for` the exact format isn't documented. I fiddled with this myself and found out translations can be added by using the following format: 

```
helpers.label.record[nested_record].attribute
```

This looks a bit funky to me. Is it supposed to be like this or is it a side effect of the current implementation? For reference, I did found an old issue similar to this back in 2011. See https://github.com/rails/rails/pull/3654.

**Comment by rafaelfranca** [comment]
Looking at that PR that you liked it should not be like that. That PR even added tests to make sure it is not.

**Comment by rafaelfranca** [comment]
Could you take a look?

**Comment by gambala** [comment]
I think it's supposed to be like this, @KevinSjoberg you can also use `[0]`/`[1]`/`[any]`-like translations for has_many fields_for: http://stackoverflow.com/a/4867303/2237879

**Comment by KevinSjoberg** [comment]
I'll take a closer look and report back @rafaelfranca.
