### ISSUE TITLE
Renaming a table in migration, doesn't update an index when the name is very long/cut off

### ISSUE THREAD

**Issue by sbwoodside** [rails/rails#22123]
I have renamed a model/table with a long name: SurveyQuestionResponse to LabelMeasurementResponse. The migration is:

    class RenameSurveyQuestionResponseToLabelMeasurementResponse < ActiveRecord::Migration
      def change
        rename_table :survey_question_responses, :label_measurement_responses
        rename_column :text_response_measurement_responses, :survey_question_response_id, :label_measurement_response_id
      end
    end

I noticed that one of my indexes did not get updated correctly:

    add_index "text_response_measurement_responses", ["survey_question_response_id"], name: "index_text_response_measurement_responses_on_survey_question_re", using: :btree

Note that the index name "index_text_response_measurement_responses_on_survey_question_re" is cut off, this seems to have been done automatically by a previously migration.

The index might have been renamed to:

    add_index "text_response_measurement_responses", ["label_measurement_response_id"], name: "index_text_response_measurement_responses_on_label_measurement_responses", using: :btree

But it wasn't modified at all.

I have thus manually renamed it to this (honouring the 64 character limit):

    add_index "text_response_measurement_responses", ["label_measurement_response_id"], name: "index_text_response_measurement_responses_on_label_measurement_", using: :btree

Is that a bug, and did I make the correct manual fix?

**Comment by rdavila** [comment]
@sbwoodside I don't think this is a bug, it's a expected behaviour from Rails to play nice with the constraints of your Database. When working with large field names you may want to use a custom name.

In this case you can rename your index with: 
```ruby
rename_index :table_name, 'old_index_name', 'new_index_name'
```

**Comment by atul-shimpi** [comment]
rename_index will also cut the index name
Max index length is 64. This is forced by ActiveRecord

See below code snipper from activerecord, databaselimites.rb
 # Returns the maximum allowed length for an index name. This
      # limit is enforced by rails and Is less than or equal to
      # <tt>index_name_length</tt>. The gap between
      # <tt>index_name_length</tt> is to allow internal rails
      # operations to use prefixes in temporary operations.
      def allowed_index_name_length
        index_name_length
      end

      # Returns the maximum length of an index name.
      def index_name_length
        64
      end

      # Returns the maximum number of columns per table.
      def columns_per_table
        1024
      end

Kindly refer to below file for all the database limits
<your_ruby_directory>/gems/activerecord-4.2.4/lib/active_record/connection_adapters/abstract/database_limits.rb

**Comment by atul-shimpi** [comment]
@rafaelfranca 
We can close this bug.

**Comment by sbwoodside** [comment]
Sorry, the actual issue wasn't addressed I don't think. The bug was that this table name had *already* been cut off once, and when I generated a rename migration, rails didn't recognize the previously automatically cut off name.

Does that make sense?
