### ISSUE TITLE
Edge Guides - ActiveRecord Migrations - Remove 'required' option for column

### ISSUE THREAD

**Issue by atul-shimpi** [rails/rails#22139]
Edge guide says 'required' as one of the options for adding or changing columns in migration methods

Url : http://edgeguides.rubyonrails.org/active_record_migrations.html
Section : 3.5 Column Modifiers
Section Content :
Column modifiers can be applied when creating or changing a column:
**required** Adds required: true for belongs_to associations and null: false to the column in the migration.

However, in api doc 'required' is not there. Below are the options for column.
column(name, type, options = {}) Link
Instantiates a new column for the table. The type parameter is normally one of the migrations native types, which is one of the following: :primary_key, :string, :text, :integer, :float, :decimal, :datetime, :time, :date, :binary, :boolean.

You may use a type not in this list as long as it is supported by your database (for example, “polygon” in MySQL), but this will not be database agnostic and should usually be avoided.

Available options are (none of these exists by default):

:limit - Requests a maximum column length. This is number of characters for :string and :text columns and number of bytes for :binary and :integer columns.
:default - The column's default value. Use nil for NULL.
:null - Allows or disallows NULL values in the column. This option could have been named :null_allowed.
:precision - Specifies the precision for a :decimal column.
:scale - Specifies the scale for a :decimal column.
:index - Create an index for the column. Can be either true or an options hash.

**Comment by atul-shimpi** [comment]
@senny 
Any comments?

**Comment by senny** [comment]
@atul-shimpi I think `required` is only meant to be passed to the generator:

```
bin/rails g user username:required
```

Because it will modify the `belongs_to` definition alongside the migration. I can see that the current location in the guide is not optimal to describe that behavior.

**Comment by atul-shimpi** [comment]
@senny 
Sorry for this long message. But i want to explain everything without any ambiguity.
But below is the findinds so far. I am still doing it.

1] Is 'bin/rails g user username:required', model or migration generation?
Anyway, i tried both. Nothng such as 'required' is added to either migration or model

2] From the migrations module, it looks as if the 'required' validation is added when you add a polymorphic model using the model generator (not the migration generator)
https://github.com/rails/rails/blob/master/activerecord/lib/rails/generators/active_record/model/templates/model.rb

```ruby
<% module_namespacing do -%>
class <%= class_name %> < <%= parent_class_name.classify %>
<% attributes.select(&:reference?).each do |attribute| -%>
  belongs_to :<%= attribute.name %><%= ', polymorphic: true' if attribute.polymorphic? %><%= ', required: true' if attribute.required? %>
<% end -%>
<% attributes.select(&:token?).each do |attribute| -%>
  has_secure_token<% if attribute.name != "token" %> :<%= attribute.name %><% end %>
<% end -%>
<% if attributes.any?(&:password_digest?) -%>
  has_secure_password
<% end -%>
end
<% end -%>
```

Take example
```ruby
class Picture < ActiveRecord::Base
  belongs_to :imageable, polymorphic: true
end
 
class Employee < ActiveRecord::Base
  has_many :pictures, as: :imageable
end
 
class Product < ActiveRecord::Base
  has_many :pictures, as: :imageable
end
```

After running above migration I am expecting below
1] imageable_type and imageable_id fields should be added to the table
2] A validation of required: true should be added for imageable_type and imageable_id in Picture model
3] Creating/Saving Picture  without specifying  imageable_type and  imageable_id should failed.

Only 1] in above is happening. 2] and 3] are not happening
How i checked 2]
2.1.6 :026 > Picture.validators
 => [] 
2.1.6 :027 > Employee.validators
 => [] 
If fact, theres not validator called 'required'

How I checked 3]
2.1.6 :028 > Picture.create
   (0.2ms)  begin transaction
  SQL (0.5ms)  INSERT INTO "pictures" ("created_at", "updated_at") VALUES (?, ?)  [["created_at", "2015-11-06 01:31:29.816109"], ["updated_at", "2015-11-06 01:31:29.816109"]]
   (303.1ms)  commit transaction
 => #<Picture id: 4, imageable_id: nil, imageable_type: nil, created_at: "2015-11-06 01:31:29", updated_at: "2015-11-06 01:31:29"> 
2.1.6 :029 > Picture.all
  Picture Load (0.4ms)  SELECT "pictures".* FROM "pictures"
 => #<ActiveRecord::Relation [#<Picture id: 1, imageable_id: nil, imageable_type: nil, created_at: "2015-11-06 01:19:18", updated_at: "2015-11-06 01:19:18">, #<Picture id: 2, imageable_id: 1, imageable_type: "Employee", created_at: "2015-11-06 01:26:27", updated_at: "2015-11-06 01:26:27">, #<Picture id: 3, imageable_id: nil, imageable_type: nil, created_at: "2015-11-06 01:27:34", updated_at: "2015-11-06 01:27:34">, #<Picture id: 4, imageable_id: nil, imageable_type: nil, created_at: "2015-11-06 01:31:29", updated_at: "2015-11-06 01:31:29">]> 

Still investigating more on this to confirm our findings and take correct action.

**Comment by senny** [comment]
@atul-shimpi sorry my bad. It's been changed on `master`. `required` is true by default now and there is an `optional: true` flag. However that has not been added to the generator (#18937). Removing the info about the required option seems fine, can you submit a PR and ping me?

**Comment by atul-shimpi** [comment]
yes sure.
I will be online in 2-3 hours. Will do it then

Date: Fri, 6 Nov 2015 06:09:14 -0800

**Comment by kaspth** [comment]
There's a PR here: https://github.com/rails/rails/pull/22145 — could use a bit more info in the commit message @atul-shimpi :smile:

**Comment by kaspth** [comment]
A whoops that's just in the guides — @atul-shimpi maybe you can extend that PR with the above changes?

**Comment by atul-shimpi** [comment]
ok.

Date: Fri, 6 Nov 2015 07:06:43 -0800

**Comment by atul-shimpi** [comment]
ok

Date: Fri, 6 Nov 2015 07:07:38 -0800

**Comment by atul-shimpi** [comment]
@senny 
The PR is already raised #22145

**Comment by atul-shimpi** [comment]
@kaspth 
May i know which PR i should extend?

**Comment by kaspth** [comment]
@atul-shimpi I was thinking of #22145 :)
