### ISSUE TITLE
Document of ActiveRecord::Core::ClassMethods#find_by  in ActiveRecord::FinderMethods#find_by ?

### ISSUE THREAD

**Issue by shingo-nakanishi** [rails/rails#22135]
https://github.com/rails/rails/blob/428d47adfed8d6aa7b21aec2bf5ad890961c9de3/activerecord/lib/active_record/relation/finder_methods.rb#L75

Document(comment) say

```
    #   Post.find_by name: 'Spartacus', rating: 4
    #   Post.find_by "published_at < ?", 2.weeks.ago
    def find_by(arg, *args)
      where(arg, *args).take
    rescue RangeError
      nil
    end
```

I think  `Post.find_by` call `ActiveRecord::Core::ClassMethods#find_by`, not `ActiveRecord::FinderMethods#find_by`.

`Post` is `Class`.
`Post.find_by` is class method.

other methods document in `rails/activerecord/lib/active_record/relation/finder_methods.rb` same.

**Comment by arthurnn** [comment]
I am not sure if I understand the issue. I think if you are proposing a doc change, would be easier if you open a PR with the change and we can discuss it there.

Thanks
