### ISSUE TITLE
Improve MimeResponds respond_to documentation

### ISSUE THREAD

**Issue by sealocal** [rails/rails#22144]
The documentation for the [respond_to](https://github.com/rails/rails/blob/master/actionpack/lib/action_controller/metal/mime_responds.rb#L186) method could be improved by adding another basic example.

It is documented that a controller action can respond to multiple formats.

```ruby
def index
  @people = Person.all
  
  respond_to do |format|
    format.html
    format.js
    fromat.json
  end
end
```

We can express the same controller action as:

```ruby
def index
  @people = Person.all
  respond_to :html, :js, :json
end
```

The method signature is clear for an experienced Rubyist, but
I was not able to find the more concise example documented anywhere in the [source](https://github.com/rails/rails/blob/master/actionpack/lib/action_controller/metal/mime_responds.rb), the [api docs](http://edgeapi.rubyonrails.org/classes/ActionController/MimeResponds.html#method-i-respond_to), or the [guides](http://guides.rubyonrails.org/action_controller_overview.html).

While it may be a trivial example, I think it would be appreciated by a novice Rails user.

Thoughts?  Would that be a welcome change to the docs?

**Comment by pixeltrix** [comment]
Yes, it would be helpful - also can you look at the remaining references to `ActionController::MimeResponds.respond_to` - this was extracted out to the responders gem along with `respond_with` in Rails 4.2.

**Comment by sealocal** [comment]
I see one reference that says to be sure to check the documentation for the class method `ActionController::MimeResponds.respond_to`.

I added the example I mentioned and removed the reference to the extracted class method.

Here's a compare: https://github.com/rails/rails/compare/master...sealocal:master

What do you think? Is that sufficient to open a PR to Rails master?

**Comment by magikid** [comment]
I would like to see this change implemented @sealocal.  Would you mind opening a PR?

**Comment by sealocal** [comment]
@magikid will do!
