### ISSUE TITLE
ActiveRecord::StatementInvalid: PG::ProtocolViolation: ERROR:  bind message supplies 1 parameters, but prepared statement "a1" requires 0 : SELECT  "groups".* FROM "groups" WHERE "groups"."id" = 0 LIMIT 1

### ISSUE THREAD

**Issue by bussiere** [rails/rails#22148]
I have this error 
    ActiveRecord::StatementInvalid: PG::ProtocolViolation: ERROR: bind message supplies 1      parameters, but prepared statement "a1" requires 0 : SELECT "groups".* FROM "groups" WHERE "groups"."id" = 0 LIMIT 1
Here are my versions of urby and rails     :    
discourse@057b1d5b9339:~/discourse$ ruby -v
ruby 2.2.2p95 (2015-04-13 revision 50295) [x86_64-linux]
discourse@057b1d5b9339:~/discourse$ rails -v
Rails 4.2.4
discourse@057b1d5b9339:~/discourse$

**Comment by pixeltrix** [comment]
@bussiere this appears to be either a bug in Discourse or your changes to your copy of it - please try the support channels for Discourse and the Discourse bug tracker first. If you can reproduce the error in a simple Rails app or using the standalone test script we'll re-open the issue and take another look.
