### ISSUE TITLE
ActiveRecord::QueryCache and migration pending should disable if there is no database connection

### ISSUE THREAD

**Issue by williscool** [rails/rails#22154]
I had one hell of a time working on a status route for a rails 4.2.1 app 

chronicled here https://gitter.im/rails/rails?at=5636b7b53d7306ae0f297155

because QueryCache was expecting the database to be up

solved with this rack middleware

``` ruby
# lib/custom_active_record_query_cache.rb
class CustomActiveRecordQueryCache < ActiveRecord::QueryCache
  def call(env)
    ## had to add the extra connections active check for if a connection that was good dies
    #http://stackoverflow.com/a/28771717/511710
    if  ActiveRecord::Base.connected? && (ActiveRecord::Base.connection.active? rescue false)
      super(env)
    else
      # dont monkey with activerecord just do everything else
      # https://github.com/rails/rails/blob/v4.2.1/activerecord/lib/active_record/query_cache.rb#L36
      # http://stackoverflow.com/questions/21293953/adding-a-custom-middleware-to-rails4
      response = @app.call(env)
      response[2] = Rack::BodyProxy.new(response[2]) do
        # nuthin
      end 
      response
    end 
  end 
end
```

and then obviously

``` ruby
 config.middleware.swap ActiveRecord::QueryCache , ::CustomActiveRecordQueryCache
```

**Comment by williscool** [comment]
This is also an issue with migration pending check as well https://github.com/rails/rails/blob/v4.2.1/activerecord/lib/active_record/migration.rb#L384

**Comment by arthurnn** [comment]
I remember seeing this problem before, maybe @fw1729 told me about when they were trying to make Shopify more resilient. cc @rafaelfranca

**Comment by Sirupsen** [comment]
Yup. I uncovered this as well in Shopify. I've mentioned it to @rafaelfranca and @sgrif before. I think the underlying problem here is that the physical database connection is tied too much to the activerecord object. The actual connection should be lazily established. This assumption also has other implications, e.g. if booting Rails and accessing the schema cache (which is useful for metaprogramming to instantiate models)  it'll establish a connection as well by default.

**Comment by jakehow** [comment]
@arthurnn my PR above patches this in place (where the connection is currently being accessed directly during the request lifecycle), as making the connection lazy everywhere is probably a big project.

For anyone finding this, you can monkey patch QueryCache and Migration easily using the code in the PR in your application.rb right after requiring `active_record/railtie`

**Comment by jakehow** [comment]
If anyone needs this in the meantime we wrapped it in a gem here -> https://github.com/zipmark/active_record-allow_connection_failure

**Comment by kamipo** [comment]
Since #26978, QueryCache doesn't ensure connection.
