### ISSUE TITLE
Add ActionCable as a topic to the guide

### ISSUE THREAD

**Issue by openscript** [rails/rails#22178]
The release of Rails 5 is coming closer and closer. I've been spending some time with ActionCable, but I think there are still a few things to discover. Howsoever, I thought I can contribute something to the guides. So let's start the ActionCable topic.

---
Here is my idea about the chapter structure, based on Active Job Basics and Action Mailer Basics:
- [ ] Introduction: A few lines about what's ActionCable
- [ ] Technical background: How does ActionCable work? What's the PubSub pattern?
- [ ] Configuration of the service
- [ ] Creating a Cable
  - [ ] At the server-side
  - [ ] At the browser-side
- [ ] Opening a channel
  - [ ] At the server-side
  - [ ] At the browser-side
- [ ] Running the service

---
What do you think about? Is someone else working on this?

**Comment by rafaelfranca** [comment]
Lets move this discussion for Action Cable repository so you can start to work closer to the code.

**Comment by rafaelfranca** [comment]
This issue was moved to rails/actioncable#114
