### ISSUE TITLE
cookie dose not set correctly.

### ISSUE THREAD

**Issue by yoonsy** [rails/rails#22175]
I am using Rails ver 3.2.13.

let suppose, my domain is `mydomain.com`.
In browser, there is already cookie named 'xxxx' like below.
`xxxx=xxxx; path=/; expires=Sun, 04-Nov-2035 03:29:43 GMT; HttpOnly`

I want to apply the cookie to all sub domain, so I tried like this.
```rb
cookies.delete(:xxxx)
cookies.permanent[:xxxx] = { value: :xxxx, httponly: true, domain: :all }
```

But `Set-Cookie` in response header is 
`Set-Cookie:xxxx=xxxx; domain=.watcha.net; path=/; expires=Sun, 04-Nov-2035 03:21:48 GMT; HttpOnly`

`Set-Cookie` header for remove disappeared.

Is this fixed bug in Rails 4 ? or not?

Thank you in advance :)

**Comment by rafaelfranca** [comment]
Please use the mailing list or StackOverflow for questions/help, where a wider community will be able to help you. We reserve the issues tracker for issues only.
