### ISSUE TITLE
'Learn more' links are broken for ActiveRecord and ActiveModel README

### ISSUE THREAD

**Issue by wurde** [rails/rails#22181]
Files with broken links:

https://github.com/rails/rails/blob/master/activerecord/README.rdoc
https://github.com/rails/rails/blob/master/activemodel/README.rdoc

**Comment by rafaelfranca** [comment]
These pages are made to be read in the official documentation website and they work there. It will be break in GitHub because it is not the target of these files.

**Comment by wurde** [comment]
We can't make these full links?

**Comment by wurde** [comment]
I found it convenient to read the documentation alongside the code and I'm sure other people do as well.

**Comment by rafaelfranca** [comment]
We can't. Or they work in the documentation site or they work in GitHub.
