### ISSUE TITLE
Store accessor issue : Can't read old already stored json object serialized ( hash ) values in mysql database in Rails 4

### ISSUE THREAD

**Issue by psahni108** [rails/rails#22186]
I am upgrading my application to Rails 4.2.4 from Rails 3.2.8 . I have a 'extras' attribute for a table 'editorials' which is serialized 
```ruby
        store :extras, accessors: [:attr1, :attr2, :attr3], coder: JSON
        
        #The way it is stored in **Rails 3** is 
        
        ---
        :attr1: value
        :attr2: value
        :attr3: value
    
       #The way it is stored in **Rails 4** is
       {"attr1":"value", "attr2":"value", "attr3":"value"}

#The problem when i fetch old records created when my app is in rails 3, it is throwing me error

 #JSON::ParserError: 795: unexpected token at '---

```
The problem when i fetch old records created when my app is in rails 3, it is throwing me error

 ```
JSON::ParserError: 795: unexpected token at '---
```
But when i create new records, it is working normally. Have not got any clue yet, how it get it working in Rails 4

**Comment by al2o3cr** [comment]
The serialized data in the old records is stored as YAML, so parsing it as JSON will not work.

You'll either want to convert the old records to the new format, or remove the `coder: JSON` option from the new code.

**Comment by psahni108** [comment]
@jeremy - Thanks for your reply,  Yes i changed the coder to YAML, and it worked, but the question is when coder was JSON, how it was stored in YAML.
The code unchanged.

**Comment by al2o3cr** [comment]
@psahni108 Prior to https://github.com/rails/rails/commit/3c0bf0435cfbc7a349faec5e1b5631e506b5dc70 it was not possible to change the coder, so `store` values were always encoded as YAML in the database.
