### ISSUE TITLE
MessageEncryptor broke compatibility between 3.1 and 3.2+

### ISSUE THREAD

**Issue by bjeanes** [rails/rails#22195]
I left the following comment on commit a625523e755421b0f96fe5b0a885462ef51582b1 about 18 months ago. I never followed up on it since I worked around it in my case, but since I was bit by it again, I'm posting it here for wider visibility.

> [This commit](https://github.com/rails/rails/commit/a625523e755421b0f96fe5b0a885462ef51582b1) broke the ability to decrypt persisted values that were encrypted using Rails 3.1. The `:serializer` option here is essentially hard-coded to use `NullSerializer` while [the fall-back in MessageVerifier](https://github.com/rails/rails/blob/a625523e755421b0f96fe5b0a885462ef51582b1/activesupport/lib/active_support/message_verifier.rb#L37) is and was `Marshal`.
> 
> Attempting to decrypt a value saved with Rails 3.1 from Rails 3.2 results in an `ActiveSupport::MessageEncryptor::InvalidMessage` exception. Judging by the code even in the latest 4.1.0 release candidate, this is still the case. Prior to this commit, all encrypted values would have the message verifier marshaling the value. If those values are persisted, any attempt to decrypt would fail.
> 
> Because the verifier's serializer is not configurable, in order to start upgrading my old encrypted values I had to (unfortunately) do the following:
> 
> ``` ruby
> legacy_encryptor = ::ActiveSupport::MessageEncryptor.new(default_encryption_key)
> legacy_verifier = ::ActiveSupport::MessageVerifier.new(default_encryption_key, serializer: Marshal)
> legacy_encryptor.instance_variable_set(:@verifier, legacy_verifier)
> ```

It seems to still be the case in master that the message verifier's serializer is not configurable from the message encryptor, and the configuration changed between versions. In my case, this meant values persisted in a data store could not be loaded again after an upgrade. In our case, we monkey-patched as per above but now that we are looking at a 3.2 to 4+ jump, I'd like to try to get rid of that patch, if possible.

**Comment by p8** [comment]
@bjeanes since https://github.com/rails/rails/pull/29716 it's possible define fallback serializers. 
```ruby
verifier = ActiveSupport::MessageVerifier.new(@secret, digest: "SHA512", serializer: JSON)
```
> Then gradually rotate the old values out by adding them as fallbacks. Any message generated with the old values will then work until the rotation is removed.
```ruby
verifier.rotate old_secret          # Fallback to an old secret instead of @secret.
verifier.rotate digest: "SHA256"    # Fallback to an old digest instead of SHA512.
verifier.rotate serializer: Marshal # Fallback to an old serializer instead of JSON.
```
https://edgeapi.rubyonrails.org/classes/ActiveSupport/MessageVerifier.html

This doesn't fix compatibility between 3.1 and 3.2+.
But those versions are no longer supported and I'm not seeing this backported to 3.2.
I don't think we need to keep this issue open any longer.

**Comment by bjeanes** [comment]
Agreed. This issue was opened in 2015, and the [message on the commit](https://github.com/rails/rails/commit/a625523e755421b0f96fe5b0a885462ef51582b1#commitcomment-5612905) was early 2014. It's no longer relevant to me and any one stuck on those old versions can use my workaround posted in the original comment.

**Comment by p8** [comment]
Thanks @bjeanes !
