### ISSUE TITLE
Rails Guides > Rails Routing from the Outside In > Singular Resources

### ISSUE THREAD

**Issue by danialm** [rails/rails#22204]
I think we are missing something here:

`get 'profile', to: :show`

How can it find the right controller for this action?

**Comment by eileencodes** [comment]
Hi @danialm! I think the answer here explains it well: http://stackoverflow.com/questions/19882932/how-does-rails-know-which-controllers-show-action-to-use-in-this-example-from

As in this would work if it were inside a resource, but I agree the guides are unclear. Do you want to open a pull request making it clearer?

**Comment by danialm** [comment]
I did @eileencodes, you can find it [here](https://github.com/rails/rails/pull/22221)
