### ISSUE TITLE
Insert "," to break the information.

### ISSUE THREAD

**Issue by atul-shimpi** [rails/rails#22210]
http://guides.rubyonrails.org/form_helpers.html

5.2 Dealing with Ajax
Unlike other forms making an asynchronous file upload form is not as simple as providing form_for with remote: true. 

Insert comma after 'Unlike other forms.' as shown below
Unlike other forms, making an asynchronous file upload form is not as simple as providing form_for with remote: true.

**Comment by kaspth** [comment]
Thanks, but for changes as simple as a comma change, please don't submit issues. That costs us reviewers a lot of time, instead of just submitting a pull request we could merge.

In the future, just open a pull request please 😁

**Comment by atul-shimpi** [comment]
ooh. ok.Sure
