### ISSUE TITLE
I18n.t("") raises I18n::ArgumentError

### ISSUE THREAD

**Issue by eiked** [rails/rails#22227]
using rails (4.2.4) / i18n (0.7.0)

I18n.translate('')
I18n::ArgumentError: I18n::ArgumentError
from /usr/local/lib/ruby/gems/2.2.0/gems/i18n-0.7.0/lib/i18n.rb:152:in `translate'

While nil can be translated easily

I18n.translate(nil)
=> "translation missing: de.no key"

I believe this should be changed.

First of all, it is common practice in the ruby (and rails) apis that exceptions should only be raised if something goes really wrong. But I can easily translate the empty string to just about any language in the world, so where's the probem?

Even worse, this also does happen, when a default is given like in:
I18n.translate('', default:'the empty string')
I18n::ArgumentError: I18n::ArgumentError
from /usr/local/lib/ruby/gems/2.2.0/gems/i18n-0.7.0/lib/i18n.rb:152:in `translate'

I blieve changing this would not break many existing applications.

I suggest to be changed as:
- I18n.t('"") should return "", possibly logging a warning (maybe only logging at debug level)

Let's discuss the defaults:
- I18n("", default: foo)
I believe it should return foo in this case, because this is how I18n.t(nil, default:foo) behaves.

But while looking at it, I'm not even sure if I18n.t(nil) does the right thing.
- I might want to argue that translating nil should return nil tring
- others might argue that I18n.t() should always return a String Object
(i'll copy this to another issue)

**Comment by pixeltrix** [comment]
Whilst I probably agree with most of what you say the problem doesn't lie with Rails itself - please open an issue on the I18n repo at: https://github.com/svenfuchs/i18n

Thanks for reporting.
