### ISSUE TITLE
I18n.t(nil) returns "translation missing: de.no key"

### ISSUE THREAD

**Issue by eiked** [rails/rails#22228]
I came here because of the other bug, aka I18n.t("")

But while looking at it, I'm not even sure if I18n.t(nil) does the right thing.
1) I might want to argue that translating nil should return nil
2) others might argue that I18n.t() should always return a String Object

I believe I18n.t(nil) should be changed to return nil.
because that is the only sensible answer if you try to translate nothing.
(don't complaint, don't raise, just simply return nil)

This might also help when localizing applications,
because nil would traverse through th localization layer
without no further effort.

I18n.translate(nil)
=> "translation missing: de.no key"

looks like a bad choice.
because I really can imagine a reason to translate nil.
(but in oaccassions you really want to this: I18n.t(foo || "nil")

but as it currently stands, nil is lost in translation,
and this is a lot more trouble.

This change will break software that relies on I18n.t(nil) to return a string.
but then I18n.t("") raises.

**Comment by eiked** [comment]
Let's discuss what how default should be handled with a nil argument

I suggest tthat I18n.t(nil) should always return nil,
even on I18n.t(nil, default:foo)
because nil is really a special case that should not be catched by the default:
I believe that would really make it more predictable.

I might to suggest another paramter for the nil case,
that would be:
I18n.t(foo, default:'key missing', nil:'Oops I'm NIL')

while some people might oppose to use the nil: as a keyword argument ...

but I believe this is completely legal within the ruby syntax, and it looks nice
(because :nil != nil)

**Comment by rafaelfranca** [comment]
This issue was moved to svenfuchs/i18n#329
