### ISSUE TITLE
Wrong timezone mapping for Switzerland

### ISSUE THREAD

**Issue by Jadaw1n** [rails/rails#22233]
The timezone mapping for Switzerland is wrong.
https://github.com/rails/rails/blob/master/activesupport/lib/active_support/values/time_zone.rb#L89

      "Bern" => "Europe/Berlin",

According to IANA standards, this should be Zurich => Europe/Zurich. Since this would change the key, this will break existing applications. So I propose adding both, while deprecating the Bern timezone.

      "Bern" => "Europe/Zurich",
      "Zurich" => "Europe/Zurich",

**Comment by kv109** [comment]
Fixed by https://github.com/rails/rails/issues/22348 and can be closed.
