### ISSUE TITLE
Path containing null byte returns 500 status code

### ISSUE THREAD

**Issue by questionmarc** [rails/rails#22235]
Arguably this should instead return the 400 http status code instead, since the path could be considered malformed / invalid. Throwing an error is expensive and should be reserved for truly exceptional situations.

**Steps to reproduce:**
Creating a new rails app
start up the rails server 
run `curl "localhost:3000/index.jsp%00x"` 

**Stacktrace:**
```
[2015-11-09 14:22:59] ERROR ArgumentError: string contains null byte
	/Users/pivotal/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/rack-1.6.4/lib/rack/utils.rb:679:in `join'
	/Users/pivotal/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/rack-1.6.4/lib/rack/utils.rb:679:in `clean_path_info'
	/Users/pivotal/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/actionpack-4.2.4/lib/action_dispatch/middleware/static.rb:28:in `block in match?'
	/Users/pivotal/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/actionpack-4.2.4/lib/action_dispatch/middleware/static.rb:27:in `map'
	/Users/pivotal/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/actionpack-4.2.4/lib/action_dispatch/middleware/static.rb:27:in `match?'
	/Users/pivotal/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/actionpack-4.2.4/lib/action_dispatch/middleware/static.rb:110:in `call'
	/Users/pivotal/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/rack-1.6.4/lib/rack/sendfile.rb:113:in `call'
	/Users/pivotal/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/railties-4.2.4/lib/rails/engine.rb:518:in `call'
	/Users/pivotal/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/railties-4.2.4/lib/rails/application.rb:165:in `call'
	/Users/pivotal/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/rack-1.6.4/lib/rack/lock.rb:17:in `call'
	/Users/pivotal/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/rack-1.6.4/lib/rack/content_length.rb:15:in `call'
	/Users/pivotal/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/rack-1.6.4/lib/rack/handler/webrick.rb:88:in `service'
	/Users/pivotal/.rbenv/versions/2.2.2/lib/ruby/2.2.0/webrick/httpserver.rb:138:in `service'
	/Users/pivotal/.rbenv/versions/2.2.2/lib/ruby/2.2.0/webrick/httpserver.rb:94:in `run'
	/Users/pivotal/.rbenv/versions/2.2.2/lib/ruby/2.2.0/webrick/server.rb:294:in `block in start_thread'
```

**Comment by rafaelfranca** [comment]
For what I could see in the stacktrace the exception is being raised at Rack. I don't think Rails should silently rescue ArgumentError to raise a 400 http status code, so this issue should be fixed in rack. I'll move the issue there.

**Comment by rafaelfranca** [comment]
This issue was moved to rack/rack#971

**Comment by jkowens** [comment]
@rafaelfranca after doing some digging, I thinking this is actually a Rails issue. In `ActionDispatch::FileHandler#match?` a call is made to `Rack::Utils#clean_path_info`. If a path is passed to that method that contains a null byte, an ArgumentError is raised causing the 500 status.

I think it would have to be Rails' responsibility to make sure the path is valid. In this case if the Static middleware determined it wasn't a valid path it would delegate the request to the application stack and that would result in a 404 error.
