### ISSUE TITLE
ArgumentError: No association found for name [ such as 'order_specification']

### ISSUE THREAD

**Issue by rocLv** [rails/rails#22249]
@al2o3cr I tried again using [rails bug template](https://github.com/rails/rails/blob/master/guides/bug_report_templates/active_record_gem.rb), all are fine.

I guess it's my problem. So I closed this issue. Thank your guys. Next time, I'll be more careful at reporting issues.

**Comment by yui-knk** [comment]
@rocLv I think you should use `order_specifications` (plural form) instead of `order_specification` (singular form).

**Comment by arnvald** [comment]
Your error message says `order_spicification` (sp**i**cification) instead of `odrder_specification`. Maybe you just made a typo in the relation name before?

btw preferably you should call model `OrderSpecification` (singular form), plural form should be used in `has_many` relation and table name, but the model name should be singular

**Comment by yui-knk** [comment]
@arnvald nice catch!

**Comment by rocLv** [comment]
@arnvald @yui-knk  Sorry, those were spelling mistakes. Really sorry to mislead your guys.
I checked this error again, they still not work.

**Comment by al2o3cr** [comment]
@rocLv Can you be more specific about what exactly isn't working? From the discussion, it appears that your original post has had several typos corrected and it isn't entirely clear what the remaining issue is.

It will speed things up considerably if you can reproduce the issue in the [standard template](https://github.com/rails/rails/blob/master/guides/bug_report_templates/active_record_gem.rb) as it allows others to interact with the malfunctioning code.

**Comment by swapnilchincholkar** [comment]
@rocLv 

Looks like you are making some mistake with spelling. Below is my code & is working fine.
```ruby
class CreateOrders < ActiveRecord::Migration
  def change
    create_table :orders do |t| 
      t.timestamps null: false
    end 
  end 
end

class CreateOrderSpecifications < ActiveRecord::Migration
  def change
    create_table :order_specifications do |t| 
      t.references :order
      t.timestamps null: false
    end 
  end 
end

class Order < ActiveRecord::Base
  has_many :order_specifications
end

class OrderSpecification < ActiveRecord::Base
  belongs_to :order
end

SwapnilChincholkar: tester $rails c
Loading development environment (Rails 4.2.4)
2.2.0 :001 > Order.new
 => #<Order id: nil, created_at: nil, updated_at: nil> 
2.2.0 :002 > OrderSpecification.new
 => #<OrderSpecification id: nil, order_id: nil, created_at: nil, updated_at: nil> 
```
