### ISSUE TITLE
ActiveRecord, foreign keys not created by option

### ISSUE THREAD

**Issue by waghanza** [rails/rails#22242]
Hi,

In my thought the `foreign_key` migration options
~~~ruby
create_table :products do |t|
  t.integer :season_id, index: true, foreign_key: true
end
~~~
would create a `foreign key` (not only an **index**), between `products` and `seasons`.

When running my **migration** it seems not be this way.

I have to write (in my **migration**) 
~~~ruby
 add_foreign_key :products, :seasons
~~~
to fulfill my wish(have a real foreign key s database constraint)

Is this intentional ? or am using it right ?

Regards,

**Comment by sevenseacat** [comment]
I believe you need to use the `references` syntax, ie. `t.references :season, index: true, foreign_key: true`. Otherwise Rails doesn't connect the dots.

**Comment by swapnilchincholkar** [comment]
As per [guides](http://edgeguides.rubyonrails.org/active_record_migrations.html#highlighter_333352) what @sevenseacat says is correct. Instead of adding association_id field, try to add references, that should suffice.

**Comment by waghanza** [comment]
right of it, thanks
