### ISSUE TITLE
No bind parameters used for Limit and Offset

### ISSUE THREAD

**Issue by schneems** [rails/rails#22250]
I was looking through a production heap dump and found a ton of these strings:

```
"\"$user\",public-SELECT \"issues\".* FROM \"issues\" WHERE \"issues\".\"repo_id\" = $1 AND \"issues\".\"state\" = $2 ORDER BY created_at DESC LIMIT 20 OFFSET 540"
```

It looks like they're being retained by the prepared statement cache. I'm using `will_paginate` to set offset and limit, and it looks like for every query with a new page, there is a new query generated. This will quickly consume the whole prepared statement cache which is less than ideal, see https://github.com/rails/rails/issues/21992 for examples as to why. 

@pixeltrix pointed out this line in AR https://github.com/rails/arel/blob/master/lib/arel/visitors/to_sql.rb#L419-L422 showing where we concat the number. 

We could also get some minor savings by constantizing more sql strings similar to this list https://github.com/rails/arel/blob/3c429c5d86e9e2201c2a35d934ca6a8911c18e69/lib/arel/visitors/to_sql.rb#L51-L57

**Comment by al2o3cr** [comment]
There's a gotcha where placeholders in `LIMIT` clauses isn't supported universally in all DBs. For instance, MySQL didn't support them until [this commit](https://github.com/mysql/mysql-server/commit/9f379d7f05c43b2d09de91c3af5cc35613a745e4) which released with 5.0.7 (see [MySQL issue #7306](https://bugs.mysql.com/bug.php?id=7306) for additional color). 

I'll see what I can find out about the other supported adapters (PG + SQLite).

**Comment by matthewd** [comment]
I *believe* PG does support them as being ~literals, even though it doesn't allow expressions

**Comment by schneems** [comment]
Seems like the solution would be to deprecate support for mysql :trollface:

**Comment by al2o3cr** [comment]
@schneems It may be reasonable to say "use something more recent than 5.0.7", being that that was released 10+ years ago :)

**Comment by sgrif** [comment]
Spiked on this briefly. All the backends work fine using binds here. Will do a proper fix tomorrow.

**Comment by schneems** [comment]
Thanks! :rocket:

**Comment by SamSaffron** [comment]
@schneems  :heart:  for finding this

**Comment by maia** [comment]
May I assume any AR query clause using greater-than / lesser-than comparisons like:
````ruby
.where("created_at > ?", Time.now - 1.week)
````
will fill up the prepared statement cache too? If yes, is there a workaround besides using sql?
````ruby
.where("created_at > now() - interval '7 days' ")
````
Is there e.g. a way to disable the creation of a prepared statement on a per-query basis? E.g. 
````ruby
SomeClass.skip_prepared_statement.where("created_at > ?", Time.now - 1.week).blah
````
This might be a hotfix for some apps, other than disabling the feature completely (I assume by  setting statement_limit=0 in database.yml, but I havn't tried it yet).

**Comment by schneems** [comment]
@maia i think if you're manually putting in bind parameters `?` then your prepared statements would also have bind parameters.

So if we make a prepared statement for this should be fine:

```
.where("created_at > ?", Time.now - 1.week)
```

If we make a prepared statemetn for this it would not:

```
.where("created_at > #{ Time.now - 1.week} ")
```

Rails master already has logic to only try to generate a prepared statement when bind parameters are present. This issue is specifically about `limit` and `offset` which generate non-bind parameter sql by default.

You can see your SQL that is going over the wire using http://www.schneems.com/2015/10/27/sql-in-rails-logs.html.

**Comment by maia** [comment]
@schneems As it looks to me using bind parameters will not create proper prepared statements on my example above – at least, if it's any indication that I have log entries with e.g. `execute a234` without bind parameters, and not just log entries that prefix the SQL with `execute <unnamed>`, which I believe is the indication of Rails not placing a query into the prepared statement cache). 

I'm aware that it's a slightly different issue, but it's leading to the same problem: the prepared statement cache filling up with one-time queries, causing additional memory load. Still it might be better to create a new issue after some detailed investigation.

**Comment by SamSaffron** [comment]
Thanks!

**Comment by jonatack** [comment]
Thanks @schneems and @sgrif :heart:  :rocket:
