### ISSUE TITLE
issue related to 11609

### ISSUE THREAD

**Issue by epinault** [rails/rails#22268]
The issue #11609 is closed but I believe something is not quite right as far as documentation or code

Why would you set 
```
ActiveRecord::Base.configurations = DatabaseTasks.database_configuration 
```
when the database_configuration is part of the DatabaseTasks as an attr accessor. I can see the code that accesses directly ActiveRecord::Base.configurations in the DatabaseTasks file 
 but why not accessing the value set in DatabaseTasks.database_configuration ? If not, then the doc at the top of that file should warn you when using it outside of Rails to set it. Because it was not working for me until I looked at the code and found after an issue file in Rails

**Comment by rafaelfranca** [comment]
Please use the mailing list or StackOverflow for questions/help, where a wider community will be able to help you. We reserve the issues tracker for issues only.

**Comment by epinault** [comment]
Rafael. I am pointing at the issue,. Not a question really. There is  a mismatch between code example and how to really reuse the databaseTask outside of Rails.

And even more I actually do not agree that DatabaseTasks should depend on Base.configuration since you are setting already database_configuration...
