### ISSUE TITLE
accepts_nested_attributes_for should accept allow_update option

### ISSUE THREAD

**Issue by nileshtrivedi** [rails/rails#22262]
We should support `allow_update` option in `accept_nested_attributes_for` which would work similar to `allow_destroy` (but with default set to true to maintain backward compatibility).

This would come in handy when we want only addition to a nested resource and no modification of existing records (eg: comments on a blog).

**Comment by yogeshjain999** [comment]
@nileshtrivedi modification of existing record only happens when you pass its `id`. Otherwise, it'll be considered as new record.

```ruby
blog.attributes = { comments_attributes: [
  { id: 1, body: 'updated comment' },
  { body: 'new comment' }
]}
```

**Comment by dmitry** [comment]
Looks like an idea is to restrict to update, but instead allow only to create new. Seems it's better to move to the validations, rather than into the nested attributes.

**Comment by maclover7** [comment]
Thank you for the issue but we don't take feature request in the issue tracker. Please read the contributing guides about which is the best channel for them.
