### ISSUE TITLE
ActiveRecord::Migrator hardcodes 'db/migrate' path

### ISSUE THREAD

**Issue by dreyks** [rails/rails#22261]
https://github.com/rails/rails/blob/4-2-stable/activerecord/lib/active_record/migration.rb#L874

``` ruby
def migrations_paths
  @migrations_paths ||= ['db/migrate']
  # just to not break things if someone uses: migration_path = some_string
  Array(@migrations_paths)
end
```

This results in `ActiveRecord::Migration.maintain_test_schema!` constantly triggering `rake db:test:prepare`, because it can't find any migration files under `db/migrate`

**Comment by pkmiec** [comment]
I'm also having this issue in 4.2.

When running `rake`, this is usually not a problem because rake tasks depend on `db:load_config`, which sets `ActiveRecord::Migrator.migrations_paths` to `Rails.application.paths['db/migrate']`. However, when simply calling `ActiveRecord::Migration.maintain_test_schema!` which happens in a helper, the ActiveRecord::Migrator defaults to `db/migrate`.

**Comment by maclover7** [comment]
Can you create a reproduction script using one of the templates [here](https://github.com/rails/rails/tree/master/guides/bug_report_templates)?

**Comment by dreyks** [comment]
The quickest example I can come up with is
```ruby
begin
  require 'bundler/inline'
rescue LoadError => e
  $stderr.puts 'Bundler version 1.10 or later is required. Please update your Bundler'
  raise e
end

gemfile(true) do
  source 'https://rubygems.org'
  gem 'rails', '4.2.4'
end

require 'active_record'
require 'minitest/autorun'
require 'logger'

class TestApp < Rails::Application
  config.paths['db/migrate'] << 'some_additional_path'
end

# Ensure backward compatibility with Minitest 4
Minitest::Test = MiniTest::Unit::TestCase unless defined?(Minitest::Test)

class BugTest < Minitest::Test
  def test_migrator_migrations_paths
    assert_includes ActiveRecord::Migrator.migrations_paths, 'some_additional_path'
  end
end
```

If you need a more high-level example (make an app, put a migration file in a non-standard folder, run migrations and then assert that `ActiveRecord::Migration.maintain_test_schema!` does not result in another migration run) tell me and I'll make one

**Comment by pierre-pretorius** [comment]
I'm also getting this issue, we used this in our Rails engines:
```Ruby
initializer :append_migrations do |app|
  config.paths['db/migrate'].expanded.each do |expanded_path|
    app.config.paths['db/migrate'] << expanded_path
  end
end
```
Now we use this to get around this issue:
```Ruby
initializer :append_migrations do |app|
  config.paths['db/migrate'].expanded.each do |expanded_path|
    app.config.paths['db/migrate'] << expanded_path
    ActiveRecord::Migrator.migrations_paths << expanded_path
  end
end
```

Note other following articles such as this pivital labs one called [leave-your-migrations-in-your-rails-engines](https://blog.pivotal.io/labs/labs/leave-your-migrations-in-your-rails-engines) will run into this issue.

**Comment by natesalisbury** [comment]
I'm seeing this issue too. I was able to get around it by adding this monkey patch to my app:

```ruby
module ActiveRecord
  class Migrator
    class << self
      def migrations_paths
        @migrations_paths ||= Rails.application.paths['db/migrate'].to_a
      end
    end
  end
end
```

**Comment by maclover7** [comment]
Reopening since there is an open PR to solve this.

**Comment by marlonglopes** [comment]
I hade this issue too, and here is my fix,

module ActiveRecord
  class Schema < Migration
    def migrations_paths
      (ActiveRecord::Migrator.migrations_paths + Rails.application.paths['db/migrate'].to_a).uniq
    end
  end
end

**Comment by njakobsen** [comment]
I'm also having this issue on Rails 5.1.7

**Comment by eileencodes** [comment]
@njakobsen I think this is likely solved by the changes we made for multiple databases in Rails 6.0 where the migrations path is set on the connection instead of a class. Unfortunately, Rails 5.1 is no longer supported for bug fixes so upgrading is going to be your best option.

**Comment by eileencodes** [comment]
I'm going to close this since I believe it's fixed, please comment if you're using 6.0 and still seeing the issue.

**Comment by njakobsen** [comment]
@eileencodes thanks for the update. I'll monkeypatch it for now until we upgrade to 6.x.

**Comment by danieldenis01** [comment]
Just a heads-up for those following this issue:
This workaround no longer works after updating to Rails 8.x — the migrations simply don’t load anymore, not even in the dummy app.
It still works as expected on Rails 7.2.

**Comment by zzak** [comment]
The workaround is to put `migrations_paths` in your `database.yml` or am I missing something?

**Comment by eileencodes** [comment]
If something new is broken open a new issue with a reproduction. Commenting on old issues means only the people subscribed here will see it.
