### ISSUE TITLE
Passing 'false' as partial object doesn't work (4.2.4)

### ISSUE THREAD

**Issue by dabroz** [rails/rails#22260]
Rails version 4.2.4

I have a following rendering code:

    <%= render partial: 'value', object: 'foo' %>
    <%= render partial: 'value', object: 1337 %>
    <%= render partial: 'value', object: true %>
    <%= render partial: 'value', object: false %>

Partial is defined as:

    <%= value %>
    <%= "(#{value.class.name})" %>

I have expected this to pass object as-is, therefore resulting in:

    foo (String)
    1337 (Fixnum)
    true (TrueClass)
    false (FalseClass)

Actual result is different - `false` gets discarded and I'm getting `nil` instead:

    foo (String)
    1337 (Fixnum)
    true (TrueClass)
    (NilClass)

Is this an expected behavior? I can box value inside another object to prevent this as a workaround, but it isn't a perfect solution.

Test case: https://github.com/dabroz/RailsPartialBug (sorry, don't know how to prepare a single-file testcase with actionview).

**Comment by dabroz** [comment]
@yui-knk  Thanks for the fix! :)

**Comment by yui-knk** [comment]
No problem :)
For your information, now opening PR for 4-1-stable and 4-2-stable :+1:
