### ISSUE TITLE
Relation#count produces invalid sql when select and group are involved

### ISSUE THREAD

**Issue by bughit** [rails/rails#22266]
``` ruby
begin
  require 'bundler/inline'
rescue LoadError => e
  $stderr.puts 'Bundler version 1.10 or later is required. Please update your Bundler'
  raise e
end

gemfile(true) do
  source 'https://rubygems.org'
  # Activate the gem you are reporting the issue against.
  gem 'activerecord', '4.2.5rc2'
  gem 'sqlite3'
end

require 'active_record'
require 'minitest/autorun'
require 'logger'

# Ensure backward compatibility with Minitest 4
Minitest::Test = MiniTest::Unit::TestCase unless defined?(Minitest::Test)

# This connection will do for database-independent bug reports.
ActiveRecord::Base.establish_connection(adapter: 'sqlite3', database: ':memory:')
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do

  create_table :posts, force: true

  create_table :comments, force: true do |t|
    t.belongs_to :post
  end

end

class Post < ActiveRecord::Base
  has_many :comments
end

class Comment < ActiveRecord::Base
  belongs_to :post
end

class BugTest < Minitest::Test
  def test_association_stuff
    Post.create! comments: Comment.create!(Array.new(2))

    select = Post.select('posts.*')
    group_select = Post.group(:id).select('posts.*')
    join_group_select = Post
                        .joins('left join comments on comments.post_id = posts.id')
                        .group('posts.id')
                        .select('posts.*', 'count(comments.id) as comment_count')

    #assert_equal 1, select.count

    #assert_equal 1, group_select.count

    assert_equal 2, join_group_select.first.comment_count
    assert_equal 1, join_group_select.count

  end
end
```

The useful query here is the  join_group_select, but the others should also probably work.
###### select

``` sql
SELECT COUNT(posts.*) FROM "posts"
```
###### group_select

``` sql
SELECT COUNT(posts.*) AS count_posts_all, id AS id FROM "posts" GROUP BY "posts"."id"
```
###### join_group_select

``` sql
SELECT COUNT(posts.*, count(comments.id) as comment_count) AS count_posts_all_count_comments_id_as_comment_count, posts.id AS posts_id FROM "posts" left join comments on comments.post_id = posts.id GROUP BY posts.id
```

**Comment by matthewd** [comment]
This is by design; `select(..)` with a bare `count` uses the `select` to determine what we're counting -- without any attempt to decide whether the DB server can support what you've requested.

`count(:all)` (or more generally, supplying any expression parameter to `count`) might give you the answer you're looking for... maybe?

Things get generally complicated when `group` is involved, because of how fundamentally it changes the nature of the relation. :confused:

**Comment by bughit** [comment]
about the group scenario: I don't think invalid sql is intended, there is already some support for returning a hash of counts per group, but a count of groups ( via a nested query) is probably more useful.  Both should be possible via an arg.

So currently when there's a select and group, select handling of count wins.  I'm suggesting:

1. that group handling of count would win, which would currently give you a per group count instead of invalid sql
2. additionally group count should be supported
3. ultimately group count should become the default

**Comment by matthewd** [comment]
The behaviour you're seeing is unrelated to the use of `group`, as far as I can see... you'd get similarly invalid SQL for `Post.select('id, id').count`.

Conversely, `Post.group('posts.author_id').select('published_on').count` would give you a grouped hash of author IDs to number of published posts (that is, posts with a non-null `published_on`).

Note the `posts.id AS posts_id` field in the erroneous query: it's *trying* to do a grouped count, and "only" failing because [it believes] it has been asked to count a multi-column expression.

**Comment by bughit** [comment]
yes it's unrelated to group, because there's special handling of count in the presence of select and a different special handling of count in the presence of group.  When there's both select and group, the select special handling wins evidently.  I am suggesting it should not.  And furthermore, group handling of count should at least support and ultimately default to counting groups, as that is more intuitive, logical and useful.

`Post.group().count` reads like give me the count of groups.  If you wanted counts per group, you'd put that in the select.

**Comment by bughit** [comment]
> select(..) with a bare count uses the select to determine what we're counting

that should only be done when selecting a single value, counting a select multiple expressions is guaranteed to produce an error, so the following would be ideal behavior for count in the presence of select and/or group:

1. no group, select single: count(select expression)
2. no group, select multiple: count(*)
3. group, with or without select: count groups `select count(*) from (subquery)`
