### ISSUE TITLE
Composite table name

### ISSUE THREAD

**Issue by waghanza** [rails/rails#22274]
Hi,

I have a problem with `references` keyword in my migration.
I run this migration
~~~ruby
create_table :point_of_sales do |t|
      t.string :name
    end
~~~
and after I create an other table to add a `foreign key` **constraint**
~~~ruby
def change
    create_table :purchases do |t|
      t.references :point_of_sales, index: true, foreign_key: true
    end
end
~~~
But I have the following error
~~~sql
PG::UndefinedColumn: ERREUR:  la colonne « point_of_sale_id » référencée dans la contrainte de clé étrangère n'existe pas
: ALTER TABLE "purchases" ADD CONSTRAINT "fk_rails_73c78df8df"
FOREIGN KEY ("point_of_sale_id")
  REFERENCES "point_of_sales" ("id")
~~~
How rails `pluralize` a composite noun to add foreign key ?

**Comment by fdel15** [comment]
Hello Waghanza,

The following code should allow your migration to run without any errors.

```ruby
def change
    create_table :purchases do |t|
      t.references :point_of_sale, index: true
    end
end
```
`t.references` will automatically create a foreign key column named `point_of_sale_id`.

**Comment by arthurnn** [comment]
@fdel15 I think if you want to create a fk you need to pass `foreign_key: true` , as @waghanza is trying to do. @senny can  you confirm?

**Comment by senny** [comment]
`references` in it's own will add the foreign key column but not the foreign key constraint. Passing `foreign_key: true` will do that.

@waghanza Can you write an executable test-case to reproduce your problem? You can use [this script](https://github.com/rails/rails/blob/master/guides/bug_report_templates/active_record_gem.rb) as a starting point.
