### ISSUE TITLE
Accessing route helpers in route redirect block

### ISSUE THREAD

**Issue by toncid** [rails/rails#22285]
Hello!

Is there a convenient way to access route helpers in the route redirect block?

```ruby
get 'new-page' => 'home#new_page', as: :new_page

get 'old-page', to: redirect(:new_page)
# or something like:
get 'old-page', to: redirect { |_, _| new_page_path }
```

Thanks!

**Comment by raminator** [comment]
Try this...
get 'old-page', to: redirect { |_, _| Rails.application.routes.url_helpers.new_page_path }

**Comment by arthurnn** [comment]
thanks @raminator for answering this.
@toncid We reserver our issue tracker for issues only. Please use StackOverflow for questions
