### ISSUE TITLE
includes() has many problems

### ISSUE THREAD

**Issue by eiked** [rails/rails#22293]
Hi at the rails bugs,

I did encounter a lot of problems,
which I believe are caused by the includes() clause.

I did not look up other bugs around includes(), so you might want to file it there.

One of my biggest problems is,
that the includes() is sometimes folded into LEFT OUTER joins.

I believe that should not happen.
Instead the includes() should always be resolved by issuing seperate queries.
It currently is really unpredictable if it happens this way or the other way.

This especially happens to me if I rebase my relations.
I can come around that with excludes(:includes)
but then there are new problems lurking around there.

I'd like to suggest:
- for the reason to make the includes() clause more predictable
   that relations mentioned in includes()
   shall always be fetched in a new roundtrip to the database,
   and shall not be optimized to left outer joins

WIthin my current software, includes() sometimes works as a second fetch,
but when chaining more complex queries, I sometimes get outer join behaviour.
(more on this in another bug report)

left outer join just leads to an explosion of the records returned.
and while the ActiveRecord does a god job of getting them all together,
it's just running at the wall.

I believe that this outer join "optimization"
should be dropped in rails5

One complaint about the OR mapping has always been,
that strange things happen (behind the scenes)
(and actually rails is no exceptance to this with all the magic)

please also see the next bug

**Comment by schneems** [comment]
Can you give us an example app showing the problem?

**Comment by matthewd** [comment]
> I believe that this outer join "optimization" should be dropped in rails5

It's not an optimization; it's necessary to satisfy the query you're issuing. Feel free to use `preload` instead of `includes` if you always want multiple queries... but if AR believes it needs a join, you'll probably just get an error.

Our documentation isn't as clear or detailed as it could be around `includes` / `preload` / `eager_load`, but see, for example: http://blog.bigbinary.com/2013/07/01/preload-vs-eager-load-vs-joins-vs-includes.html
