### ISSUE TITLE
rebasing queries does not work well

### ISSUE THREAD

**Issue by eiked** [rails/rails#22295]
Hi at  the rails.5 team,
you know, me know
rails.5 is done now.

I should not complaint.
Nice to meet you.
If the problem's not fixed:
Take the Overtime Man:
https://en.wikipedia.org/wiki/Don_Covay
(being there)

Back in rails4,
the mapping got better.
But when I tried it hard, I ran against a wall everywhere.

-- just my assumptions:
I believe this has not yet been fully fixed in rails5 either.

To get this right, we need to go the road to Lisp or related.
Getting the OR mapping right for complex queries
now goes well beyond the scope of basic Rails.

{on the hurd road}

[broke in the middle of the road]
But it should be on the internet.

**Comment by arunagw** [comment]
Can you point to specific issue you are getting?

**Comment by maclover7** [comment]
Can't really tell what the issue here is. The issue tracker is reserved for bugs only.
