### ISSUE TITLE
ActiveRecord Callbacks guide lacks a mention about raising ActiveRecord::RecordInvalid

### ISSUE THREAD

**Issue by shuhei** [rails/rails#22297]
[The Halting Execution section](https://github.com/rails/rails/blob/v4.2.5/guides/source/active_record_callbacks.md#halting-execution) lacks a mention to `ActiveRecord::RecordInvalid`. It only refers to `AcitveRecord::Rollback` that will not be raised by `save` and `update_attributes`. However, `save` and `update_attributes`, which internally uses `save`, actually [catch `ActiveRecord::RecordInvalid` and don't raise the exception](https://github.com/rails/rails/blob/v4.2.5/activerecord/lib/active_record/persistence.rb#L119-L123).

Sometimes it's handy to do validations that involves associations in `after_save` callback and raise `ActiveRecord::Rollback` if the validations fails. Before saving associations, we cannot use convenient AR queries to check associations and have to deal with `marked_for_destruction?` and such. When I implemented such a validation, I was confused by the guide that states we should not raise exceptions other than `ActiveRecord::Rollback`. It would be helpful if it also mentions to `ActiveRecord::RecordInvalid`.

```rb
class Foo < ActiveRecord::Base
  has_many :bars

  after_save :check_bar_count

  def check_bar_count
    errors.add(:bars, 'should be less than or equal to 3')
    raise ActiveRecord::RecordInvalid.new(self) if bars.count > 3
  end
end
```

**Comment by maclover7** [comment]
Feel free to open up a PR with documentation changes.
