### ISSUE TITLE
ActiveModel::Dirty module documentation mistake.

### ISSUE THREAD

**Issue by harrykiselev** [rails/rails#22307]
Hi! I found a little mistake at the documentation of ActiveModel::Dirty module.

When we start follow the [instructions](https://github.com/rails/rails/blob/master/activemodel/lib/active_model/dirty.rb#L55-L69), we call [that line](https://github.com/rails/rails/blob/master/activemodel/lib/active_model/dirty.rb#L65)

```
...
person.name_changed?(from: "Uncle Bob", to: "Bob") # => true
...
```

Comment for this line tell us that this line should return true, but it is not, because after initialize person object [here](https://github.com/rails/rails/blob/master/activemodel/lib/active_model/dirty.rb#L57) the @name attribute of new object is nil.

I found two variants of fixing it:

I. Change value of "from" argument for .name_changed? method in documentation:

```
...
person.name_changed?(from: nil, to: "Bob") # => true
...
```

II. Changing Person class:

* add initialize method with initializing name attribute for Person objects:

```
class Person
  include ActiveModel::Dirty
  ...

  def initialize(name)
    @name = name
  end

  ...
end
```

* and fix documentation [here](https://github.com/rails/rails/blob/master/activemodel/lib/active_model/dirty.rb#L57):

```
...
person = Person.new(name: "Uncle Bob")
...
```

Can you help me choose right solution for PR to fixing it? :)

**Comment by swapnilchincholkar** [comment]
@harrykiselev 

I think solution 1 will make more sense as it will be more easier to understand for a newbie.

In solution 1, along with changes in line 65, we will need more changes. All listed below,

[Line 65](https://github.com/rails/rails/blob/master/activemodel/lib/active_model/dirty.rb#L65)
```ruby
person.name_changed?(from: "nil", to: "Bob") # => true
```


[Line 66](https://github.com/rails/rails/blob/master/activemodel/lib/active_model/dirty.rb#L66)
```ruby
person.name_was       # => ""
```

[Line 67](https://github.com/rails/rails/blob/master/activemodel/lib/active_model/dirty.rb#L67)
```ruby
person.name_change    # => ["", "Bob"]
```

[Line 69](https://github.com/rails/rails/blob/master/activemodel/lib/active_model/dirty.rb#L69)
```ruby
person.name_change    # => ["Bob", "Bill"]
```

**Comment by harrykiselev** [comment]
@swapnilchincholkar thanks for notice that editions in one line touches another :)
But if take into consideration that nil != "nil", all empty strings in your editions transform into the nil.

I think so I will send PR with the second variant, because:
* originally conceived by authors of this module
* most of developers knows what is done "initialize" method in a class.

Thus I think it is right way for fix that issue. :)
