### ISSUE TITLE
Incorrect documentation for mattr_accessor

### ISSUE THREAD

**Issue by ypxing** [rails/rails#22305]
Below document seems incorrect.

http://api.rubyonrails.org/classes/Module.html#method-i-mattr_accessor

```
module HairColors
  mattr_accessor :hair_colors
end

class Person
  include HairColors
end

Person.hair_colors = [:brown, :black, :blonde, :red]
```

**Comment by tjblonsk** [comment]
I can confirm the above:
`Person.hair_colors`
`=> NoMethodError: undefined method `hair_colors' for Person:Class`

Question is whether the documentation is wrong or the behavior is wrong.
Assuming the behavior is wrong, I will compose a test case.

**Comment by matthewd** [comment]
The documentation is wrong; they appear to have diverged in 7dfbd91b0780fbd6a1dd9bfbc176e10894871d2d.

**Comment by tjblonsk** [comment]
Thanks @matthewd.

How is it possible that the api doc is different from the code and how to reconcile?

**Comment by arthurnn** [comment]
@tjblonsk The docs is wrong, as of the commit that @matthewd pointed out. We need to fix the comment on that file in order to update the api.rubyonrails.org . Do you want to send a PR with the fix?
thanks

**Comment by tjblonsk** [comment]
Will do!

**Comment by rishav** [comment]
What is the expected behaviour ?

**Comment by matthewd** [comment]
The expected behaviour was correctly documented before 7dfbd91b0780fbd6a1dd9bfbc176e10894871d2d; see https://github.com/rails/rails/blob/7dfbd91b0780fbd6a1dd9bfbc176e10894871d2d%5E/activesupport/lib/active_support/core_ext/class/attribute_accessors.rb.
