### ISSUE TITLE
Passing string to limit sets limit_value to string

### ISSUE THREAD

**Issue by jwoertink** [rails/rails#22309]
I'm not sure if this is considered a bug or not, but when using `limit` in a AR query, if you pass a string like `"10"` it will limit to 10 records like it should. This also sets the `limit_value` attribute to that string `"10"` (https://github.com/rails/rails/blob/master/activerecord/lib/active_record/relation/query_methods.rb#L656). There are a few gems out there that use this `limit_value` for doing calculations like [pagination and such](https://github.com/amatsuda/kaminari/blob/master/lib/kaminari/models/page_scope_methods.rb#L28). It would seem to me that if `nil` is passed, then `limit_value` should be `nil` otherwise it should be an integer to denote the actual limit.

**Comment by matthewd** [comment]
`limit_value` is not public API

**Comment by jwoertink** [comment]
Then shouldn't that be protected then? You can still call `User.limit(1).limit_value`.

**Comment by matthewd** [comment]
http://guides.rubyonrails.org/api_documentation_guidelines.html#method-visibility

**Comment by jwoertink** [comment]
Ah! I always wondered what that `:nodoc:` meant. Thanks for pointing that out.
