### ISSUE TITLE
Generators: Allow deeply nested namespacing

### ISSUE THREAD

**Issue by rwassey** [rails/rails#22319]
I noticed that when trying to generate an Engine using [a conventional gem name](http://guides.rubygems.org/name-your-gem/), the `PluginBuilder` raises an error.

```shell
rails plugin new my-shiny_new-plugin --mountable
Invalid plugin name my-shiny_new-app. Please give a name which use only alphabetic or numeric or "_" characters.
```

whereas `bundler` doesn't have a problem with such names.

```shell
bundle gem my-shiny_new-gem
Creating gem 'my-shiny_new-gem'...
      create  my-shiny_new-gem/Gemfile
      create  my-shiny_new-gem/.gitignore
      create  my-shiny_new-gem/lib/my/shiny_new/gem.rb
      create  my-shiny_new-gem/lib/my/shiny_new/gem/version.rb
      create  my-shiny_new-gem/my-shiny_new-gem.gemspec
      create  my-shiny_new-gem/Rakefile
      create  my-shiny_new-gem/README.md
      create  my-shiny_new-gem/bin/console
      create  my-shiny_new-gem/bin/setup
      create  my-shiny_new-gem/.travis.yml
      create  my-shiny_new-gem/.rspec
      create  my-shiny_new-gem/spec/spec_helper.rb
      create  my-shiny_new-gem/spec/my/shiny_new/gem_spec.rb
Initializing git repo in /Users/<user>/my-shiny_new-gem
```

I'm thinking of starting a project which would enable Rails engines with these sorts of names, but I first wanted to reach out to see if there is are reason that Rails generators consider such names invalid?

(Also, if this discussion has been had already please point me to the thread.)

**Comment by arthurnn** [comment]
this has changed on master branch (rails 5), https://github.com/rails/rails/commit/ee9e4c340e68cd6f274b1443b68f1d3e91db7b6f , We cannot backport this behaviour as it is a new behaviour.
But new versions of Rails will allow `-` on the plugin name
