### ISSUE TITLE
Running railties tests leaves processes running

### ISSUE THREAD

**Issue by merhard** [rails/rails#22312]
Running the tests for the railties gem is leaving orphaned processes running on my dev machine (Ruby 2.2.3, Rails master, OSX El Capitan).

When I compare the output of `ps -xf` before and after I run `RUBYOPT=-W0 bundle exec ruby -w -Itest test/railties/engine_test.rb -n "test_paths_are_properly_generated_when_application_is_mounted_at_sub-path_and_relative_url_root_is_set"`, I see:
```
  501  4943     1   0 12:48PM ttys004    0:00.01 /Users/merhard/.rvm/gems/ruby-2.2.3/gems/rb-fsevent-0.9.6/bin/fsevent_watch --latency 0.1 /Users/merhard/Documents/personal/rails/activesupport/lib/active_support/locale
  501  4944     1   0 12:48PM ttys004    0:00.01 /Users/merhard/.rvm/gems/ruby-2.2.3/gems/rb-fsevent-0.9.6/bin/fsevent_watch --latency 0.1 /Users/merhard/Documents/personal/rails/activemodel/lib/active_model/locale
  501  4945     1   0 12:48PM ttys004    0:00.01 /Users/merhard/.rvm/gems/ruby-2.2.3/gems/rb-fsevent-0.9.6/bin/fsevent_watch --latency 0.1 /Users/merhard/Documents/personal/rails/activerecord/lib/active_record/locale
  501  4946     1   0 12:48PM ttys004    0:00.01 /Users/merhard/.rvm/gems/ruby-2.2.3/gems/rb-fsevent-0.9.6/bin/fsevent_watch --latency 0.1 /Users/merhard/Documents/personal/rails/actionview/lib/action_view/locale
  501  4947     1   0 12:48PM ttys004    0:00.01 /Users/merhard/.rvm/gems/ruby-2.2.3/gems/rb-fsevent-0.9.6/bin/fsevent_watch --latency 0.1 /private/var/folders/jp/p3kqqkvx66b784y8d9vl3npc0000gn/T/d20151116-4942-9mauyj/app/config/locales
  501  4948     1   0 12:48PM ttys004    0:00.01 /Users/merhard/.rvm/gems/ruby-2.2.3/gems/rb-fsevent-0.9.6/bin/fsevent_watch --latency 0.1 /private/var/folders/jp/p3kqqkvx66b784y8d9vl3npc0000gn/T/d20151116-4942-9mauyj/app/random/bukkits/config
  501  4949     1   0 12:48PM ttys004    0:00.01 /Users/merhard/.rvm/gems/ruby-2.2.3/gems/rb-fsevent-0.9.6/bin/fsevent_watch --latency 0.1 /Users/merhard/.rvm/gems/ruby-2.2.3/bundler/gems/jquery-rails-04fcfa29b859
  501  4950     1   0 12:48PM ttys004    0:00.01 /Users/merhard/.rvm/gems/ruby-2.2.3/gems/rb-fsevent-0.9.6/bin/fsevent_watch --latency 0.1 /Users/merhard/.rvm/gems/ruby-2.2.3/gems/coffee-rails-4.1.0
  501  4951     1   0 12:48PM ttys004    0:00.01 /Users/merhard/.rvm/gems/ruby-2.2.3/gems/rb-fsevent-0.9.6/bin/fsevent_watch --latency 0.1 /Users/merhard/.rvm/gems/ruby-2.2.3/bundler/gems/turbolinks-83d4b3d2c52a
  501  4953     1   0 12:48PM ttys004    0:00.01 /Users/merhard/.rvm/gems/ruby-2.2.3/gems/rb-fsevent-0.9.6/bin/fsevent_watch --latency 0.1 /private/var/folders/jp/p3kqqkvx66b784y8d9vl3npc0000gn/T/d20151116-4942-9mauyj/app/app/assets
  501  4954     1   0 12:48PM ttys004    0:00.01 /Users/merhard/.rvm/gems/ruby-2.2.3/gems/rb-fsevent-0.9.6/bin/fsevent_watch --latency 0.1 /private/var/folders/jp/p3kqqkvx66b784y8d9vl3npc0000gn/T/d20151116-4942-9mauyj/app/app/controllers
  501  4955     1   0 12:48PM ttys004    0:00.01 /Users/merhard/.rvm/gems/ruby-2.2.3/gems/rb-fsevent-0.9.6/bin/fsevent_watch --latency 0.1 /private/var/folders/jp/p3kqqkvx66b784y8d9vl3npc0000gn/T/d20151116-4942-9mauyj/app/app/helpers
  501  4956     1   0 12:48PM ttys004    0:00.01 /Users/merhard/.rvm/gems/ruby-2.2.3/gems/rb-fsevent-0.9.6/bin/fsevent_watch --latency 0.1 /private/var/folders/jp/p3kqqkvx66b784y8d9vl3npc0000gn/T/d20151116-4942-9mauyj/app/app/jobs
  501  4957     1   0 12:48PM ttys004    0:00.01 /Users/merhard/.rvm/gems/ruby-2.2.3/gems/rb-fsevent-0.9.6/bin/fsevent_watch --latency 0.1 /private/var/folders/jp/p3kqqkvx66b784y8d9vl3npc0000gn/T/d20151116-4942-9mauyj/app/app/mailers
  501  4958     1   0 12:48PM ttys004    0:00.01 /Users/merhard/.rvm/gems/ruby-2.2.3/gems/rb-fsevent-0.9.6/bin/fsevent_watch --latency 0.1 /private/var/folders/jp/p3kqqkvx66b784y8d9vl3npc0000gn/T/d20151116-4942-9mauyj/app/app/models
  501  4959     1   0 12:48PM ttys004    0:00.01 /Users/merhard/.rvm/gems/ruby-2.2.3/gems/rb-fsevent-0.9.6/bin/fsevent_watch --latency 0.1 /private/var/folders/jp/p3kqqkvx66b784y8d9vl3npc0000gn/T/d20151116-4942-9mauyj/app/random/bukkits/app/controllers
  501  4960     1   0 12:48PM ttys004    0:00.01 /Users/merhard/.rvm/gems/ruby-2.2.3/gems/rb-fsevent-0.9.6/bin/fsevent_watch --latency 0.1 /private/var/folders/jp/p3kqqkvx66b784y8d9vl3npc0000gn/T/d20151116-4942-9mauyj/app/test/mailers
```

Shouldn't these processes be killed during test teardown? They currently run forever and slowly grow until I restart my computer. Should `Listen.stop` be called somewhere?

Since this appears to be related to the new evented file system monitor, /cc @fxn

**Comment by fxn** [comment]
The monitor lives in AS. I wonder which tests in railties may be launching a monitor, sounds strange at first sight, have you investigated this further?

**Comment by merhard** [comment]
[This is the test I was running.](https://github.com/rails/rails/blob/788d7bce3dc60fde5588df70b5131716b99680a1/railties/test/railties/engine_test.rb#L1307..L1354) It is not the only test that causes this, just an example of one that I know definitely reproduces the issue. It can be run with the following command:
```shell
$> bundle exec ruby -w -Itest test/railties/engine_test.rb -n "test_paths_are_properly_generated_when_application_is_mounted_at_sub-path_and_relative_url_root_is_set"
```


In this type of test, a new rails app is generated in the file system's tmpdir (`/private/var/...`, not `#{Rails.root}/tmp/...`). This app is then loaded, integration test http requests are sent, and assertions are made about the responses. The generated app is only used for this test and never used again. Each test generates its own new app.

My thought is the new evented file system monitor starts watching the files of this generated temporary app when it is booted. When the app is discarded at the end of the test, the file system monitor continues watching. I tried digging through the code but I do not understand how the file watchers are ever stopped. When a rails server or console is exited, how are the file watchers stopped?

**Comment by fxn** [comment]
Is this still an issue after 14b20ce9b38314943dcaf73b8dab7508b70ba487?

**Comment by merhard** [comment]
@fxn I just ran the tests against master as of 11/30/15 (b83c097) and am still seeing this issue.

**Comment by fxn** [comment]
Thanks @merhard it's strange because the generated application `Gemfile` by default has the `listen` gem commented out... I'll dig into this.

**Comment by merhard** [comment]
@fxn Perhaps the generated application is picking up the `Listen` constant from `Rails`' `Gemfile`?

If I add `config.file_watcher = ActiveSupport::FileUpdateChecker` to https://github.com/rails/rails/blob/208911e4c007b2dc1c1a9d6175abaf95522d00b4/railties/test/isolation/abstract_unit.rb#L147-L154 the issue is resolved.

Should I open a pull request with this change?

**Comment by fxn** [comment]
Let me study the problem a bit.

**Comment by fxn** [comment]
Your hypothesis was correct, the application runs in the same process `boot_rails` does and thus it has the `Listen` constant defined.

But there was something strange. These tests run in their own forked process and  AFAICT applications need no explicit cleanup in modern versions of `listen`. If you run a hello world example like this:

```ruby
require 'listen'
Listen.to(__dir__) {}.start
sleep 10
```

and check

```
ps -xf | grep fsevent
```

in another console, you'll see the subprocess disappears when the script finishes. Why then this didn't happen here? You see what I mean, I would expect `listen` to run because of the presence of the constant (debatable, but bear with me), why does the suite leave orphan processes at all? Those forked processes eventually die, what's going on?

The key is that if the script above exits with `exit!`:

```ruby
require 'listen'
Listen.to(__dir__) {}.start
sleep 10
exit!
```

you'll see the child process remains orphan. That `exit!` is [the way isolated tests finish](https://github.com/rails/rails/blob/eb0e8e216fcf535a1e6b82720dfb7639fcc20ff2/activesupport/lib/active_support/testing/isolation.rb#L61).

I have grepped the `listen` tree for `\btrap\b` and `at_exit` and didn't find anything. The [documentation about `exit!`](http://ruby-doc.org/core-2.2.3/Kernel.html#method-i-exit-21) says no exit handlers are run but... don't know what exit handlers prevent orphan processes in a regular exit. In any case, there must be *something* that does not perform the regular cleanup, maybe in Ruby itself. @e2 do you know?

Currently Rails no longer uses the evented monitor based on the presence of the constant and this issue won't show up as a side-effect. If we needed to, we could investigate what to do regarding that `exit!` call, but since we do not plan to use the evented monitor in these tests I think we can just leave it as is and close.

**Comment by merhard** [comment]
Thank you for looking into this. I agree that the issue is no longer present after a75496b, but I worry that this will pop up again when the evented file update checker is added back.

Why do we call `exit!` at the end of isolated tests and not just `exit`? It comes from commit eea7b5d titled: "Crazy hacks to get the Isolation testing module to work on non forking environments"

**Comment by fxn** [comment]
Can answer the question about `exit!`, but the monitor has not been removed, we only removed its automatic activation based on the `Listen` constant, you'll need to opt-in using configuration.

That's why I closed, this monitor has no chance to become the default any time soon.

**Comment by merqlove** [comment]
Same problem with beta 3.

**Comment by jeremy** [comment]
@merhard That commit just has `exit!` in the diff. It's moving around. The original commit used `exit!`: https://github.com/rails/rails/commit/575b95ea0bf3d3fff6f47dddad23c754fb294604#diff-b32e7453f375bf4450424307c9eb53c7R30

The usual reason is to bypass `at_exit` hooks. Like a test runner's `at_exit`, for example.

Switch to `exit` and give it a shot 😁

**Comment by merhard** [comment]
@jeremy Not sure how I missed that `exit!` came from a different commit 😕 . Thanks for the heads up.

@merqlove I just ran all of the `railties` tests using `v5.0.0.beta3` and `master` (took ~50min each) and did not experience any orphaned processes (Ruby 2.3.0, OSX El Capitan).

Can you provide a specific example test that does leave orphaned processes (easier to run one test than the entire suite when debugging)? Also some information about the environment you are running the tests from?

**Comment by merqlove** [comment]
@merhard Hi, yeah, i did OSS app for the test, and found current "bug" during the test.
[Mysterious app repo](https://bitbucket.org/merqlove/mysterious_api/src/f2a73ec51a8536d10ac868b998d3d69b3b0feaea/?at=prmd)
```
minidesk:mysterious merqlove$ ps aux | grep ruby
merqlove            88902   0.0  0.0  2434840    784 s003  S+   10:39AM   0:00.00 grep ruby
minidesk:mysterious merqlove$ rails s
=> Booting Puma
=> Rails 5.0.0.beta3 application starting in development on http://localhost:3000
=> Run `rails server -h` for more startup options
=> Ctrl-C to shutdown server
[88906] Puma starting in cluster mode...
[88906] * Version 3.4.0 (ruby 2.3.0-p0), codename: Owl Bowl Brawl
[88906] * Min threads: 5, max threads: 5
[88906] * Environment: development
[88906] * Process workers: 2
[88906] * Preloading application
[88906] * Listening on tcp://localhost:3000
[88906] Use Ctrl-C to stop
^C
minidesk:mysterious merqlove$ ps aux | grep ruby
merqlove            88947   0.0  0.0  2444056    808 s003  S+   10:40AM   0:00.00 grep ruby
minidesk:mysterious merqlove$ rails console
Running via Spring preloader in process 89035
Loading development environment (Rails 5.0.0.beta3)
Ruby 2.3.0-p0 (2015-12-25) x86_64-darwin15
>> exit
minidesk:mysterious merqlove$ ps aux | grep ruby
merqlove            89050   0.0  0.0  2434840    784 s003  S+   10:41AM   0:00.00 grep ruby
merqlove            89045   0.0  0.0  2491752   3140   ??  S    10:41AM   0:00.01 /Users/merqlove/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/rb-fsevent-0.9.7/bin/fsevent_watch --latency 0.1 /Users/merqlove/Repo/merqlove/src/mysterious/app/services
merqlove            89044   0.0  0.0  2481512   3092   ??  S    10:41AM   0:00.01 /Users/merqlove/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/rb-fsevent-0.9.7/bin/fsevent_watch --latency 0.1 /Users/merqlove/Repo/merqlove/src/mysterious/spec/mailers/previews
merqlove            89043   0.0  0.0  2480488   3100   ??  S    10:41AM   0:00.01 /Users/merqlove/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/rb-fsevent-0.9.7/bin/fsevent_watch --latency 0.1 /Users/merqlove/Repo/merqlove/src/mysterious/app/serializers
merqlove            89042   0.0  0.0  2480488   3088   ??  S    10:41AM   0:00.01 /Users/merqlove/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/rb-fsevent-0.9.7/bin/fsevent_watch --latency 0.1 /Users/merqlove/Repo/merqlove/src/mysterious/app/policies
merqlove            89041   0.0  0.0  2471272   3072   ??  S    10:41AM   0:00.01 /Users/merqlove/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/rb-fsevent-0.9.7/bin/fsevent_watch --latency 0.1 /Users/merqlove/Repo/merqlove/src/mysterious/app/models
merqlove            89040   0.0  0.0  2470248   3068   ??  S    10:41AM   0:00.01 /Users/merqlove/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/rb-fsevent-0.9.7/bin/fsevent_watch --latency 0.1 /Users/merqlove/Repo/merqlove/src/mysterious/app/mailers
merqlove            89039   0.0  0.0  2481512   3104   ??  S    10:41AM   0:00.01 /Users/merqlove/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/rb-fsevent-0.9.7/bin/fsevent_watch --latency 0.1 /Users/merqlove/Repo/merqlove/src/mysterious/app/jobs
merqlove            89038   0.0  0.0  2473320   3100   ??  S    10:41AM   0:00.01 /Users/merqlove/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/rb-fsevent-0.9.7/bin/fsevent_watch --latency 0.1 /Users/merqlove/Repo/merqlove/src/mysterious/app/controllers
merqlove            89037   0.0  0.0  2463080   3064   ??  S    10:41AM   0:00.01 /Users/merqlove/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/rb-fsevent-0.9.7/bin/fsevent_watch --latency 0.1 /Users/merqlove/Repo/merqlove/src/mysterious/lib
merqlove            89036   0.0  0.0  2471272   3068   ??  S    10:41AM   0:00.01 /Users/merqlove/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/rb-fsevent-0.9.7/bin/fsevent_watch --latency 0.1 /Users/merqlove/Repo/merqlove/src/mysterious/db
merqlove            89034   0.0  0.0  2473320   3088   ??  S    10:41AM   0:00.01 /Users/merqlove/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/rb-fsevent-0.9.7/bin/fsevent_watch --latency 0.1 /Users/merqlove/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/kaminari-0.16.3/config/locales
merqlove            89033   0.0  0.0  2470248   3032   ??  S    10:41AM   0:00.01 /Users/merqlove/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/rb-fsevent-0.9.7/bin/fsevent_watch --latency 0.1 /Users/merqlove/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/actionview-5.0.0.beta3/lib/action_view/locale
merqlove            89032   0.0  0.0  2481512   3088   ??  S    10:41AM   0:00.01 /Users/merqlove/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/rb-fsevent-0.9.7/bin/fsevent_watch --latency 0.1 /Users/merqlove/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/activerecord-5.0.0.beta3/lib/active_record/locale
merqlove            89031   0.0  0.0  2481512   3092   ??  S    10:41AM   0:00.01 /Users/merqlove/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/rb-fsevent-0.9.7/bin/fsevent_watch --latency 0.1 /Users/merqlove/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/activemodel-5.0.0.beta3/lib/active_model/locale
merqlove            89030   0.0  0.0  2479464   3064   ??  S    10:41AM   0:00.01 /Users/merqlove/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/rb-fsevent-0.9.7/bin/fsevent_watch --latency 0.1 /Users/merqlove/Repo/merqlove/src/mysterious/config/locales
merqlove            89029   0.0  0.0  2462056   3032   ??  S    10:41AM   0:00.01 /Users/merqlove/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/rb-fsevent-0.9.7/bin/fsevent_watch --latency 0.1 /Users/merqlove/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/activesupport-5.0.0.beta3/lib/active_support/locale
merqlove            89028   0.0  0.0  2462056   3052   ??  S    10:41AM   0:00.01 /Users/merqlove/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/rb-fsevent-0.9.7/bin/fsevent_watch --latency 0.2 /Users/merqlove/Repo/merqlove/src/mysterious
```

**Comment by merqlove** [comment]
I have too Ruby 2.3.0 & OS X El'Capitan :) So i think maybe i need to drop some gem or it is really rails bug?
Also i did another branch where i have to `require:false` for all bin gems, & stuck with listener problem twice.
Bug can be easily found if you run app with `foreman start`.

**Comment by merqlove** [comment]
[Branch with cleanup & foreman](https://bitbucket.org/merqlove/mysterious_api/src/d7d273a5521dd106585f5972083f2e279634d5fe?at=rails-listener-stuck)

**Comment by merhard** [comment]
@merqlove The processes you see are there by design and are not orphaned. You are using the new `ActiveSupport::EventedFileUpdateChecker`. This uses the [listen gem](https://github.com/guard/listen) to watch your application files for changes to trigger code reloading in development. They are left running by [spring](https://github.com/rails/spring), the application preloader you are using that is running in the background after starting the Rails console. You can verify this by running `$ spring stop`. This should kill the 18 processes you see.

This closed issue was about orphaned processes when running the tests of the `railties` gem (an issue that has not been present since a75496b).

@jeremy I see no need to switch `exit!` to `exit` at this time (no matter how much I would like more Rails commits to my name 😉 ).

**Comment by merqlove** [comment]
Matthew, the problem, that they are not gone after i have to run `spring stop`. These processes is really stuck. I able to kill them only by: `sudo killall fsevent_watch`.
They stay always with `foreman start` (which have `bin/puma ..`...)

Ok, i will look on this later, seems that this trouble in for dev-env.

--
Best regards,
Alexander Merkulov

**Comment by e2** [comment]
> Matthew, the problem, that they are not gone after i have to run `spring stop`. These processes is really stuck.

That's probably because for OSX Listen uses a process for reporting filesystem changes. On Linux, it's just calls through the FFI.

On OSX, Listen opens a pipe with the fsevent_watch process. Probably Listen is killed without a chance to close those pipes: https://github.com/thibaudgg/rb-fsevent/blob/d803637/lib/rb-fsevent/fsevent.rb#L55

I don't use OSX, but Listen does have an API for stopping processes:

https://github.com/guard/listen/blob/master/lib/listen.rb#L44

I don't want to make any guesses here, so just ask me for any details about the above.

**Comment by merhard** [comment]
@merqlove It looks like the issue you are experiencing is coming from the `foreman` gem: https://github.com/ddollar/foreman/issues/618

Running `$ bundle update foreman` and verifying version `0.81.0` (released earlier today) should fix this for you.

**Comment by merqlove** [comment]
@merhard Yeah, it's too, but i also had current bug without the `foreman`. Foreman just easier to demonstrate 👍

**Comment by merhard** [comment]
Interesting. After upgrading foreman I could no longer produce any orphaned child processes.

Do you have another command to run to reproduce this? A list of commands?

**Comment by merqlove** [comment]
@merhard, yeah, in `foreman` its gone, just notfication about myriad of sub streams.
You can try `rails console`. It did the trick some time.
Make some seed by `make seed` & do  something in console, like `Post.all`

--
Best regards,
Alexander Merkulov

**Comment by merhard** [comment]
@merqlove I tried every command I could think of (make, rails, rake, puma, foreman). A total of 17 processes were started. None of the processes were orphaned. They all died when I stopped the spring server.

Now that foreman has been updated, are you sure `$ bin/spring stop` does not work?

If you are still having issues, you can always comment-out the line that reads `config.file_watcher = ActiveSupport::EventedFileUpdateChecker` in `config/environments/development.rb` along with removing the `listen` and `spring-watcher-listen` gems from the `Gemfile`.

Sorry I could not be of more help. 😞

**Comment by merqlove** [comment]
@merhard just tried again., seems that spring stop now working. thanks for your time. 
Nevermind. I will look into code if it up again.
Cheers! 👍

**Comment by lastobelus** [comment]
I think this is a more general problem, see  https://github.com/rails/rails/issues/26158

What I have done is add 
```
if [ `/usr/bin/pgrep fsevent_wat | wc -l` -ge 100 ] ; then
  pkill -9 fsevent_wat*
fi

```
to the start of the script I use to spin up foreman etal.

What I also noticed is that when the number of fsevent_watch processes started to the ulimit on processes, code reloading would stop working reliably, even through spring stop/start.
