### ISSUE TITLE
Missing Rails 4.2.5 announcement?

### ISSUE THREAD

**Issue by marutosi** [rails/rails#22314]
There is no Rails 4.2.5 release announcement at blog and [ML](https://groups.google.com/forum/#!forum/rubyonrails-talk) .
Is Rails 4.2.5 released?

**Comment by kaspth** [comment]
It is. @rafaelfranca was sick, so he couldn't publish the posts. They should be published this week.

**Comment by loed-idzinga** [comment]
Great, thanks! :+1:
