### ISSUE TITLE
ActiveSupport::PerThreadRegistry - undefined method `delegate'

### ISSUE THREAD

**Issue by mikeantonelli** [rails/rails#22311]
https://github.com/rails/rails/issues/21921 introduced a change to `ActiveSupport::PerThreadRegistry` in 4.2-stable (and 4.2.5) via https://github.com/rails/rails/commit/599c31cf7d617955ea727358bf9878b365252f51. The [previously stable implementation](https://github.com/rails/rails/blob/v4.2.4/activesupport/lib/active_support/per_thread_registry.rb#L44-L51) of `method_missing` did not require [delegation](https://github.com/rails/rails/blob/master/activesupport/lib/active_support/core_ext/module/delegation.rb), but the [new implementation](https://github.com/rails/rails/blob/v4.2.5/activesupport/lib/active_support/per_thread_registry.rb#L48) throws `NoMethodError: undefined method 'delegate'` when attributes have not been delegated. 

I am using the `PerThreadRegistry` to front a `Hash` of arbitrary runtime keys, making delegation challenging. The previous implementation of `method_missing` forwarded to `instance`, but I'm having trouble determining how to support 4.2-stable without overriding `method_missing` to address this change.

Here is a reference project: https://github.com/mikeantonelli/request_store_registry - any advice would be greatly appreciated.

**Comment by matthewd** [comment]
Backported to 4-2-stable in 5f967b57fc5e8e933b8df2d44bb8eabaed9d6222.

@mikeantonelli the simplest work-around for 4.2.5 is probably to directly do that require yourself.

**Comment by mikeantonelli** [comment]
@matthewd That will expose the correct interface but how would I go about forwarding all calls to instance without overriding method_missing?

```
Delegation needs a target. Supply an options hash with a :to key as the last argument (e.g. delegate :hello, to: :greeter).
```

**Comment by matthewd** [comment]
@mikeantonelli is `delegate` not being passed a `:to` option? [It seems to be](https://github.com/rails/rails/blob/v4.2.5/activesupport/lib/active_support/per_thread_registry.rb#L48).

That require appears sufficient to get things working for me...

before:

```
% be irb -ractive_support -ractive_support/per_thread_registry
irb(main):001:0> class Foo; extend ActiveSupport::PerThreadRegistry; def x; self; end; end; Foo.x
NoMethodError: undefined method `delegate' for #<Class:Foo>
```

after:

```
% be irb -ractive_support -ractive_support/per_thread_registry
irb(main):001:0> class Foo; extend ActiveSupport::PerThreadRegistry; def x; self; end; end; Foo.x
=> #<Foo:0x007fd97b755bf0>
```

on 4.2.5:

```
% be irb -ractive_support -ractive_support/per_thread_registry
irb(main):001:0> class Foo; extend ActiveSupport::PerThreadRegistry; def x; self; end; end; Foo.x
NoMethodError: undefined method `delegate' for #<Class:Foo>
irb(main):002:0> require 'active_support/core_ext/module/delegation'
=> true
irb(main):003:0> Foo.x
=> #<Foo:0x007ff9a2a31fa8>
```
