### ISSUE TITLE
RouteProxy UrlHelpers became really slow in 4.2.5

### ISSUE THREAD

**Issue by krishan** [rails/rails#22320]
In Rails 4.2.5, the Url Helper Cache was removed, so each time `RouteSet#url_helpers` is invoked, a new `Module` is built. See: https://github.com/rails/rails/commit/07dfd2ea097706ef0240f1dda5236cdc5f2c8843

Unfortunately, `RouteProxy` invokes `RouteSet#url_helpers` _every single time_ a route helper is called, see: https://github.com/rails/rails/blob/v4.2.5/actionpack/lib/action_dispatch/routing/routes_proxy.rb#L31

So now `RouteProxy` is really slow, which is bad since `RouteProxy` is widely used, for example when writing `main_app.my_route_helper` as recommended in http://guides.rubyonrails.org/engines.html#routes.

**Comment by rafaelfranca** [comment]
cc @eileencodes

**Comment by krishan** [comment]
I cherry-picked a fix for this issue from `master`, see: #22322
