### ISSUE TITLE
select & time_zone_select don't select current object value

### ISSUE THREAD

**Issue by ifightcrime** [rails/rails#22324]
When using select & time_zone_select without form_for, passing in the object as the first argument doesn't mark the object's current value as selected.

When using `form_for`, the object is passed in via `objectify_options`:

https://github.com/rails/rails/blob/master/actionview/lib/action_view/helpers/form_options_helper.rb#L852

When NOT using `form_for`, the object is never passed in:

https://github.com/rails/rails/blob/master/actionview/lib/action_view/helpers/form_options_helper.rb#L291

I'm assuming this was originally done because it's asking for a string `object_name`, which then falls back to looking for an instance variable (https://github.com/rails/rails/blob/master/actionview/lib/action_view/helpers/tags/base.rb#L51). However, it seems to me that it would be much more convenient to do this:

`time_zone_select(current_user, :TimeZone)`

Instead of the workaround I am using now:

`time_zone_select(current_user, :TimeZone, { object: current_user })`

For a fix we could modify https://github.com/rails/rails/blob/master/actionview/lib/action_view/helpers/form_options_helper.rb#L290-L292 to be something like:

``` ruby
def time_zone_select(object, method, priority_zones = nil, options = {}, html_options = {})
  options[:object] = object if object.respond_to?(method)
  Tags::TimeZoneSelect.new(object, method, self, priority_zones, options, html_options).render
end
```

That seems kind of dirty though. Either way I can submit a pull request with the proposed solution (or maybe none at all!!)

**Comment by maclover7** [comment]
Feel free to open up a PR with a possible solution.
