### ISSUE TITLE
Remove reference to scaffolding in Testing Guide

### ISSUE THREAD

**Issue by nicholaide** [rails/rails#22337]
The Testing guide references the Getting Started guide when introducing scaffolding. However, Getting Started no longer has scaffolding examples.

**Comment by rafaelfranca** [comment]
@senny I remember you were working in that guide, could you take a look?

**Comment by senny** [comment]
@rafaelfranca yes.

**Comment by senny** [comment]
I changed the wording to match what we use in the "Getting Started" guide.

@nicholaide thank you for reporting :yellow_heart:
