### ISSUE TITLE
ActiveRecord::Base.connection.execute() leaks with Postgres

### ISSUE THREAD

**Issue by jcoleman** [rails/rails#22331]
When someone wants to execute arbitrary SQL and goes looking in the docs, the relevant (and most generic) method on the abstract module `ActiveRecord::ConnectionAdapters::DatabaseStatements` seems to be `execute`. This is reinforced all over the web in places like http://stackoverflow.com/questions/15408285/rails-3-execute-custom-sql-query-without-a-model/15408419

However, in the Postgres implementation, `execute` invokes `async_exec` on the underlying PG connection, which returns an object which includes manually managed C allocated memory. If you don't call `clear` on the result set that is returned, then that memory is never freed, and your app will leak memory. You can see the code here: https://github.com/rails/rails/blob/799aedc6437aad61a6355917f625da6fd7868d24/activerecord/lib/active_record/connection_adapters/postgresql/database_statements.rb#L155

The proper interface on the module `ActiveRecord::ConnectionAdapters:: PostgreSQL ::DatabaseStatements` is `execute_and_clear` which takes a block and automatically clears the result set from the PG gem after the block is executed. This method is used internally by methods like `exec_query`, `exec_delete` and so on, but is not clear in documentation that it's available (or even more importantly, necessary.)

Ideally I'd like to see `execute` be made private (and perhaps even renamed so that a method of the same name could actually invoke the block-based behavior), but at the very least I'd like to update the documentation to make this obvious.

Incidentally, I only discovered this issue based on an off-hand comment made on this podcast: http://bikeshed.fm/30 -- and then went looking through the AR and PG code to confirm that this was indeed an issue.

**Comment by matthewd** [comment]
> that memory is never freed, and your app will leak memory

[I'm not sure that's true](https://github.com/ged/ruby-pg/blob/6e6a44b5bfc1ff5c4147dcf45448067e0fe07567/ext/pg_result.c#L212).

**Comment by tenderlove** [comment]
Agree with @matthewd. @jcoleman can you prove there is actually a leak? If so the it seems like a bug in the pg gem.

**Comment by jcoleman** [comment]
@tenderlove I've confirmed that it doesn't "leak" per se, but the problem is that since the memory is out-of-band, large result sets can hang around and never be GC'd as they don't create GC pressure in Ruby's VM.

To trivially demonstrate, running

    1000.times { r = ActiveRecord::Base.connection.execute "select * from generate_series(1, 200000)" }

on Rails console leads to well over a GB extra of memory being used by the ruby process, but without running `GC.start` manually, it will never be freed.

**Comment by sgrif** [comment]
`execute` returns the result object of the underlying driver. As per the PG docs, the object leaks unless `autoclear?` returns true. The documentation for `execute` specifically states that we return a PG result object. Making this a private method would be a breaking change. I don't think there's anything actionable here.

**Comment by jcoleman** [comment]
@sgrif Noting that it returns a `PG::Result` object in the docs doesn't give you any indication though that you need to look further to know that memory performance might suffer. Basically you're saying that people should be experts on the internal workings of the PG gem.

At the very least I'd like to see the docs improved (on both the abstract module and the PG specific module) to clarify that the behavior might not be as you'd expect; and perhaps that you might want to give preference to `exec_query` and friends.

**Comment by sgrif** [comment]
I'd be fine with improving the docs. Feel free to open a PR if you have
some specific improvements.

**Comment by jcoleman** [comment]
@sgrif One other thing: what would you think about making `execute_and_clear` on the PG adapter available publicly instead of privately?

**Comment by matthewd** [comment]
@jcoleman I guess I'd like to understand more about the use case. We have `select_all` and `exec_query` for ordinary ORM-bypassing result-set-fetching purposes, and then we offer direct access to `execute` if you really want the raw `PG::Result` (at which point, yes, I absolutely think it's reasonable to expect you to treat it as the `pg` gem instructs you).

I'm struggling to picture the niche for "I definitely need the raw adapter result, but I don't [want to] know how it works"; perhaps an example would help?

**Comment by jcoleman** [comment]
@matthewd It's not necessarily that I want the raw `PG::Result` so much as just having a fully generic interface to pass SQL. For example, if you want to execute multiple SQL commands in one DB roundtrip, then the only option is `execute`; the other wrappers error on multiple statements.

Here's a (obviously contrived SQL) example:

    irb(main):001:0> ActiveRecord::Base.connection.execute <<-eos
    irb(main):002:0" select 1;
    irb(main):003:0" select 2;
    irb(main):004:0" eos
       (0.2ms)  select 1;
    select 2;

    => #<PG::Result:0x00000119b13f18 @connection=#<PG::Connection:0x00000119c35f18 @socket_io=nil, @notice_receiver=nil, @notice_processor=nil>>
    irb(main):005:0> ActiveRecord::Base.connection.exec_query <<-eos
    irb(main):006:0" select 1;
    irb(main):007:0" select 2;
    irb(main):008:0" eos
      SQL (0.4ms)  select 1;
    select 2;

    PG::SyntaxError: ERROR:  cannot insert multiple commands into a prepared statement
    : select 1;
    select 2;

    ActiveRecord::StatementInvalid: PG::SyntaxError: ERROR:  cannot insert multiple commands into a prepared statement
    : select 1;
    select 2;

Incidentally, I think one issue here (and why `execute` gets incorrectly recommended to many people) is that the naming is unfortunate...ideally `execute` would be something like `execute_raw`. But I recognize that that deprecation/API change isn't likely to happen giving the breakage it would cause.

**Comment by meetme2meat** [comment]
@jcoleman  We are using execute all across our Ruby application. If I'm correct what you are saying is that using `execute` cause memory to bloat indefinitely.

If yes, I still don't get this part.

> 1000.times { r = ActiveRecord::Base.connection.execute "select * from generate_series(1, 200000)" }
> 
> on Rails console leads to well over a GB extra of memory being used by the ruby process, but without running GC.start manually, it will never be freed.

So eventually GC (whether run manually or invoked by Ruby itself) would clean up the extra memory right?

**Comment by jcoleman** [comment]
@meetme2meat Yes a GC run would clean it up, but in that example case a GC run is never initiated automatically because the memory that is used is outside of the GC's knowledge, so the GC never sees any memory pressure.

**Comment by jrochkind** [comment]
Anyone know if this remains the same in Rails 5.2, some unusual memory pressure to using `execute`?

**Comment by P9GIT** [comment]
@jrochkind, @jcoleman 

According to PG docs the memory info should be given to the GC from PG gem 1.1:

https://deveiate.org/code/pg/PG/Result.html

https://bitbucket.org/ged/ruby-pg/src/fddea15f846d3f900665fbe8760fcd4e90bc9b70/History.rdoc?at=default&fileviewer=file-view-default

> - Estimate PG::Result size allocated by libpq and notify the garbage collector about it when running on Ruby-2.4 or newer.
> - Make the estimated PG::Result size available to ObjectSpace.memsize_of(result) .

So I guess this problem is no longer an issue...?
