### ISSUE TITLE
New shortcut: render_partial

### ISSUE THREAD

**Issue by eiked** [rails/rails#22334]
I'd like to suggest a new shortcut:
    render_partial(partial_name, locals_hash={})

This shall be a shortcut for:
    render partial:partial_name, locals:locals_hash

This obviously does not add much on the first sight.
But rendering partials is one of the key uses of using the render method
and this makes rendering partials feel much more like invoking a simple method.

It actually removes some clutter and makes the code more concise.

compare:
    render partial:'ui/pagination', locals:{result:foo}
to:
    render_partial 'ui/pagination', result:foo

This would be mostly compatible
- except for the layout: and collection: arguments,
   which might go into a third options argument, making it:
      render_partial(partial_name, locals_hash={}, options_hash={})

I've been using this shortcut in my code for some years now,
making it so much more pleasant to use partials.

In my partials I now write as a signature (in haml):
    - foo ||=[]
    - bar

which nicely defaults foo if not given,
but raises if bar was not given in the locals_hash

combined with render_partial()
this makes partials feel a lot more like invoking functions.

I believe this enhancement will be compatible with most existing code.
(execept where someone else also came up with render_partial)

**Comment by mehdi-farsi** [comment]
I agree with you. This should be a great improvement !

The `:partial` option is definitely the most called option in all of my apps.

However, if you do it for one option, why not doing it for all of them ?

I wonder if it would be a good idea to create a `RenderingHelper` method for each available option..

**Comment by matthewd** [comment]
Thanks, but we don't take feature requests on the issue tracker.
