### ISSUE TITLE
ActiveRecord::Associations::JoinDependency::JoinBase#name crashing with undefined local variable or method `reflection'

### ISSUE THREAD

**Issue by bhaak** [rails/rails#22341]
When calling the method name of an instance of ActiveRecord::Associations::JoinDependency::JoinBase, it crashes with "undefined local variable or method `reflection' for #<ActiveRecord::Associations::JoinDependency::JoinBase:>" in lib/active_record/associations/join_dependency/join_part.rb:26:in`name'.

The method name is defined in JoinPart and is thus inherited by JoinBase and JoinAssociation but in JoinBase the reflection variable is never set (and from what I gather, doesn't need to be set). It would therefore be sensible to move the name method into JoinAssociation.

**Comment by arthurnn** [comment]
@bhaak can you write a self contained script that simulates to problem? that would help us on the fix.
thanks
