### ISSUE TITLE
Support for DelayedJob reschedule_at and max_attempts

### ISSUE THREAD

**Issue by jtmarmon** [rails/rails#22359]
These methods are not implemented in `ActiveJob::QueueAdapters::DelayedJobAdapter::JobWrapper` which means that a significant portion of functionality from DelayedJob is missing when using ActiveJob.

The original solution I was playing with was adding class methods to my ActiveJob descendant - `self.max_attempts` and `self.reschedule_at` - and proxying to them through the `JobWrapper`. However, for some reason when added I get a `NoMethodError`.

Instance methods seem to work but because `JobWrapper` is passed `job_data` rather than the `job` itself, you'd have to either modify the code to pass the job, or instantiate a new job like:

```rb
job_data['job_class'].constantize.new(job_data['arguments']).reschedule_at
```

Which seems like a bad solution because of unintended side effects.

The best solution to me seems to be to change `JobWrapper`'s initializer to accept a `job` instead of its data and store a reference to the job instance itself, allowing proxies directly to the job instance. I'd go ahead with a PR but it seems like you're actively trying to avoid passing around references to the job (maybe for thread safety...?) so I wanted to get some feedback first.

**Comment by ajporterfield** [comment]
Hey @jtmarmon.  I wrote something very similar to what you're describing in a forked version of Rails I was playing with (see below).  It seemed to work ok, but ultimately I felt like this was a step backwards as it goes against Active Job's "one interface for all adaptors" thing.  

I definitely agree with you, though.  We shouldn't have to sacrifice per-job overrides when using delayed_job through Active Job.  Maybe it's just an options method (like queue_as) that we can pass a hash of key/value pairs that can be picked up by the adaptor clases.  Thoughts?

    class JobWrapper #:nodoc:
      attr_accessor :job_data

      def initialize(job_data)
        @job_data = job_data
      end

      def perform
        define_per_job_overrides
        Base.execute(job_data)
      end

      private
        def job
          @job ||= Base.deserialize(job_data)
        end

        def define_per_job_overrides
          available_overrides.each do |override|
            if job.respond_to? override
              define_singleton_method(override) { job.send(override) }
            end
          end
        end

        def available_overrides
          %w(max_attempts destroy_failed_jobs?)
        end
    end

    class TestJob < ActiveJob::Base
      queue_as :default

      def perform
        nil > 0
      end

      def max_attempts
        2
      end

      def destroy_failed_jobs?
        false
      end
    end

**Comment by ajporterfield** [comment]
An alternative solution (instead of using define_singleton_method), could be...

    def max_attempts
      job.max_attempts rescue Delayed::Worker.max_attempts
    end

**Comment by ajporterfield** [comment]
I published a gem that over the weekend that you can use to get per-job overrides back when using Active Job + delayed_job - https://github.com/ajporterfield/activejob_dj_overrides.

**Comment by rafaelfranca** [comment]
I prefer to not have adapter specific code in Active Job. So a gem is a good way to start. Well done @ajporterfield
