### ISSUE TITLE
bad interaction with has_many, accepts_nested_attributes_for, and validates_presence_of

### ISSUE THREAD

**Issue by burnt43** [rails/rails#22358]
Hello, I think I have found a bug with Rails. I have tested this with version 4.2.0, 4.2.3, 4.2.4, and 4.2.5 and the issue appears in all those versions.

I have a reproduction program in a gist https://gist.github.com/burnt43/67d03704cb67bfadfa1a.

The problem happens with the following conditions
1. Model A that has many of Model B
2. Model B belongs to Model A.
3. Model A accepts nested attributes for Model B
4. Model B validates presence of Model A

When you do what I think is called an 'inline save' like below

``` ruby
ModelA.new({
  field1: 'whatever',
  model_bs: [
    ModelB.new( field1: 'whatever' )
  ]
}).save
```

The save will fail and return false because ModelB is validating the presence of ModelA for some reason it is not setting model_a_id.

However, if I comment out the accepts_nested_attributes_for in ModelA then the save works as intended.

You can see in my reproduction program that `Bar` and `Qux` are identical and I save a new `Foo` in the exact same way, but the only different is `Foo` `accepts_nested_attributes_for :quxes`, but does not for `:bars`. The second assertion in my test fails, but the first will pass.

**Comment by sgrif** [comment]
Can you see if this issue is still present on master? I'm almost positive I've fixed this.

**Comment by burnt43** [comment]
@sgrif, I updated the gist and set the gems to use the master branch. I reran the program and I can still reproduce the issue.

**Comment by sgrif** [comment]
Well shit... I'll look into it on Monday.

**Comment by mrageh** [comment]
@sgrif I think I may have a PR for this issue, let me know if you'd like me to push it up

**Comment by sgrif** [comment]
Go for it.

**Comment by mrageh** [comment]
@sgrif my pr is done, let me sleep on it, then I'll review it and open it tomorrow

**Comment by mrageh** [comment]
@sgrif I've opened the PR feel free to take a look when you next can

**Comment by samphilipd** [comment]
This is getting stale, but I'm still seeing it on latest master. Not sure what the blocker is on my PR that fixes this.

**Comment by maclover7** [comment]
@samphilipd There are over 500 PRs open on Rails (and about 400 issues), so that's a lot to be managing and coordinating, no less as a free OSS project :)

**Comment by samphilipd** [comment]
@maclover7 understood man. What can I do to help?

**Comment by maclover7** [comment]
At this point, patience is the most important thing, and just to sit tight. There's a ton of PRs and issues to review and go over. :)

**Comment by maclover7** [comment]
Closing since https://github.com/rails/rails/pull/23197 / https://github.com/rails/rails/commit/c7adc610f0233b9afd51a6d68aa9061cdb250fad were merged to master.
