### ISSUE TITLE
config.assets.debug = true still compiles everything into single CSS/JS files?

### ISSUE THREAD

**Issue by cannikin** [rails/rails#22357]
I'm trying to enable the good old fashioned behavior of having Rails 5 include all actual CSS and JS files for development. This makes it very easy to see where a style is defined and edit it if necessary.

I'm running Rails edge and setting `config.assets.debug = true` in `config/environments/development.rb` It still creates a single application.css file, but it has a source map appended to the very end:

`/*# sourceMappingURL=application.css-05797752b7560f1ce60cdc4567ddf1a69d8b436624cf5f7e753c60509eb2f670.map */`

But all that does in Chrome devtools is show that a style is defined in application.css and when you view the source it's just literally the application.css file with all the commented `/* require */` directives, not a map to the *real* CSS file containing the style (in my case that's `assets/stylesheets/pages/index.sass`):

![nqplfhaef5](https://cloud.githubusercontent.com/assets/300/11311536/5ce7016e-8f85-11e5-88b5-c89dd686258b.gif)

(It's tough to tell but I'm clicking the file name above the h1 style in the GIF above.) I can manually browse to http://localhost:3000/assets/pages/index.css and the file comes up fine.

Is this the expected behavior? It seems like the old behavior of actually including each and every asset individually was *much* more helpful in development. Maybe it has something to do with my stylesheet being in a subdirectory and not adjacent to application.css in the file structure?

Here's my Gemfile: https://gist.github.com/cannikin/a19a98898aecc017475c

**Comment by rafaelfranca** [comment]
This is a bug with source map generation, but the idea is to generate only one asset in development with source maps pointing to the right source.

**Comment by rafaelfranca** [comment]
This issue was moved to rails/sprockets#162
