### ISSUE TITLE
Column spacing in schema.rb leads to superfluous line changes in diffs between versions

### ISSUE THREAD

**Issue by thesmart** [rails/rails#22356]
The automatic column formatting of `schema.rb` means that git diffs are often inaccurate and lead to false alarms all the time.  I don't think the readability improvements outweigh the false-positives when there are line changes in diffs due to column spacing changing across schema.rb version.

**Comment by rafaelfranca** [comment]
Thank you so much for the issue but we don't take feature request on the issue tracker. We recommend you to try to implement the feature and send us a pull request or if you are in doubt if the feature will be accepts ask in Rails Core mailing list for feedback.

**Comment by brodock** [comment]
For anyone whiling to contribute here, someone already made a gem that monkey patches rails to do that: https://github.com/mirego/activerecord_sane_schema_dumper
