### ISSUE TITLE
Error installing development environment: Cannot exclude db group

### ISSUE THREAD

**Issue by randoum** [rails/rails#22364]
Following http://edgeguides.rubyonrails.org/development_dependencies_install.html
Chapter *2.3 Set up and Run the Tests*
Said to run `$ bundle install --without db`

This does not exclude the installation and compilation of db drivers :
> Installing pg 0.18.3 with native extensions
> Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

Tried to comment the content of `group :db` in the Gemfile. Same result.
Platform: Ubuntu, RBenv, Ruby 2.2.2p95, last version of Rail from master

Thanks

**Comment by arthurnn** [comment]
do you have a stacktrace? where is that installing coming from? if you commented that out from your gemfile , I am curious to see why it is still trying to install that.

**Comment by randoum** [comment]
It was a clone from master. I am curious to see why too, and that's why I posted this message for your information. Off course I worked around by installing PG in the system. Now if you don't feel like working on this, we just close it. You seem to be a bit upset by my question and I don't want to bother you with it.
Thanks anyway.
