### ISSUE TITLE
Inflections - override translations

### ISSUE THREAD

**Issue by Javix** [rails/rails#22360]
I tried to override the default rules by specifing it in ` initializers/inflections.rb`as follows:
```
ActiveSupport::Inflector.inflections(:fr) do |inflect|
   #inflect.plural '/Niveau$/i', 'Niveaux'
   inflect.irregular 'Niveau', 'Niveaux'
end
```
I tried it in the console:
```
Level.model_name.human
=> "Niveau"
[2] pry(main)> Level.model_name.human.pluralize
=> "Niveaus"
```
Any idea on what is wrong here  ? Thank you.
Reproduced on Rails 4.2.4., OS 10.11.1, Ruby 2.2.2

**Comment by egilburg** [comment]
Your current locale could still be english.

Try:

```ruby
Level.model_name.human.pluralize(:fr)

or 

```ruby
I18n.locale = :fr

Level.model_name.human.pluralize
```

**Comment by Javix** [comment]
I set the default locale to :fr, rails console should be aware or not?

**Comment by nofxx** [comment]
@Javix , that's strange. Inflector should work as #human will return a String.

Another way:  http://stackoverflow.com/questions/22730559/rails-4-pluralizing-model-name-human-using-count-123-doesnt-work

This will then work: `Level.model_name.human count: :many`  or `count: 2` anything.. it tests for zero.

Couldn't we have a `Model.model_name.human_many`  or `human_plural` ?

**Comment by nofxx** [comment]
Just tried using inflectors, just like Javix.


```
ActiveSupport::Inflector.inflections(:pt) do |inflect|
  inflect.irregular 'Assistência', 'Assistências'
end

MyNiceModel.model_name.human
# Assistência
MyNiceModel.model_name.human.pluralize
# Assistência
MyNiceModel.model_name.human.pluralize(I18n.locale)
# Assistências
```

This gotta be a bug. Why #pluralize isn't using the locale???

**Comment by matthewd** [comment]
This is by design; otherwise changing the current locale would break Rails's ability to turn the model name into a table name, for example.

**Comment by nofxx** [comment]
@matthewd ty. That explains it. Thank you.
To make it more intuitive, if we have `human` using locale, we could have `human_plural` or something like.
What do you think?
