### ISSUE TITLE
Running tests within an engine with pending migrations throws a wrong message

### ISSUE THREAD

**Issue by karloxyz** [rails/rails#22378]
To reproduce:

1. Create a new rails engine `rails plugin new blorgh --mountable`
2. Create a new migration `rails g CreateBlorghUsers username:string`
3. Run the migration using `rake db:migrate`
4. Create another migration `rails g CreateBlorghAnimals name:string`
5. Try running a test `ruby -Itest test/blorgh_test.rb`

The error is that the message instructs you to use `bin/rake db:migrate RAILS_ENV=test` but in your current directory `bin/rake` isn't available. I know this is a bit nitpicky since the initial migration was ran without the `rake` prefix, but this might just be a small fix. I'm looking into this now. I'm also opening this issue in hope of any suggestions or do we just not fix this?

**Comment by rafaelfranca** [comment]
Feel free to send a PR. I believe the best way to fix it is generating a `bin` folder for an engine too.

**Comment by chrisarcand** [comment]
This is no longer an issue as `./bin/rails` is created now; can be closed.
