### ISSUE TITLE
Improve subclasses/descendants performance by using JRuby ext

### ISSUE THREAD

**Issue by headius** [rails/rails#22376]
JRuby has for many years shipped with a JRuby-specific extension that adds a `Class#subclasses`. It's far more efficient than using `ObjectSpace` because JRuby tracks all child classes via a weak set.

The behavior of our `Class#subclasses` appears to match ActiveSupport's version (ignoring ordering differences):

```
[] ~/projects/jruby $ jruby -ractive_support -ractive_support/core_ext -e "puts Numeric.subclasses"
Integer
Complex
Rational
Float
Date::Infinity
BigDecimal

[] ~/projects/jruby $ jruby -rjruby/core_ext -rbigdecimal -rdate -e "puts Numeric.subclasses"
Float
BigDecimal
Integer
Rational
Date::Infinity
Complex
```

However, the JRuby extension is two orders of magnitude faster than the `ObjectSpace` version:

```
[] ~/projects/jruby $ jruby -ractive_support -ractive_support/core_ext -rbenchmark -e "5.times { puts Benchmark.measure { 100_000.times { Numeric.subclasses } } }"
 16.940000   0.170000  17.110000 ( 14.870510)
 14.730000   0.050000  14.780000 ( 14.675306)
 15.360000   0.060000  15.420000 ( 15.284996)
 14.690000   0.050000  14.740000 ( 14.579782)
 14.660000   0.050000  14.710000 ( 14.507709)

[] ~/projects/jruby $ jruby -rjruby/core_ext -rbigdecimal -rdate -rbenchmark -e "5.times { puts Benchmark.measure { 100_000.times { Numeric.subclasses } } }"
  1.440000   0.050000   1.490000 (  0.390534)
  0.210000   0.000000   0.210000 (  0.133651)
  0.220000   0.010000   0.230000 (  0.139908)
  0.130000   0.000000   0.130000 (  0.133102)
  0.180000   0.020000   0.200000 (  0.142007)
```

**Comment by headius** [comment]
cc @sgrif

**Comment by headius** [comment]
Note that JRuby does not ship a `Class#descendants` but it can be implemented by recursively calling `Class#subclasses`.

**Comment by rafaelfranca** [comment]
Hey @headius, thank you for the issue. I'm havving trouble to understand what is being proposed here. If people is using JRuby and they want to load JRuby extensions don't them just need to require the correct files? Is there something on Rails side that needs to be done?

**Comment by headius** [comment]
Rails uses ObjectSpace internally to implement `Class#subclasses` and `Class#descendants`, here: https://github.com/rails/rails/blob/master/activesupport/lib/active_support/core_ext/class/subclasses.rb

This may be the only way to do it on MRI, but JRuby provides a much faster way via a JRuby-specific ext. If this code is used in any hot path (reloading in dev? anything in production?) it would be much less overhead to use the JRuby extension.

**Comment by headius** [comment]
Note also that this could be moved out to some external dependency (e.g. a "subclasses" gem) but I don't think we want to do that for such a tiny feature.

MRI could also add its own `#subclasses` but it would probably not show up until 2.4.

**Comment by headius** [comment]
This came up due to a question from @sgrif here: https://twitter.com/sgrif/status/667857751666626560

**Comment by rafaelfranca** [comment]
Right. So, if I got it right, we basically need a way to conditionally require the JRuby extensions on that file and use its implementation instead of the the current implementation. Do you think that is a good plan?

**Comment by headius** [comment]
@rafaelfranca Yeah that's the plan I'd follow.

I'm actually also modifying JRuby 9.0.5.0 to support the singleton_class mechanism you currently use, but it would still need a Rails PR to change https://github.com/rails/rails/blob/master/activesupport/lib/active_support/core_ext/class/subclasses.rb#L6 to attempt a singleton_class walk rather than a plain class walk (my patch special-cases each_object(singleton) because we know it's just a walk of descendants).

So if using a JRuby ext is acceptable, that's the change I can PR.

If using a JRuby ext is not acceptable, I will fix the each_object check and it will be fast from JRuby 9.0.5.0 forward.

**Comment by headius** [comment]
There's also a way to do it without requiring anything additional on JRuby:

```ruby
JRuby.reference(self).subclasses(recursive).to_a
```

This can be used on stock JRuby.

**Comment by sgrif** [comment]
So are we thinking something like this?

```ruby
begin
  Object.each_object(some_random_singleton_class) {}

  def descendants
    # what we have now
  end
rescue StandardError # older JRuby versions
  require "jruby/core_ext/class"
end
```

**Comment by headius** [comment]
@sgrif @rafaelfranca I just submitted two alternate PRs for the two possible solutions. Pick whichever you prefer :-)

The each_object version is slightly faster because it doesn't have the overhead of calling through our Java integration layer.

**Comment by sgrif** [comment]
Definitely in favor of the first one. @rafaelfranca Do we have an official policy for supported JRuby versions? Would it make sense to just drop the `rescue` clause and only support 9k since we're also dropping support for < 2.2 on MRI?

**Comment by headius** [comment]
Note that JRuby 9.0.4.0 and lower do *not* support `each_object(singleton_class)` so if that's the only option they won't be able to run this code. The subclasses fix is in JRuby 9.0.5.0 and above, from jruby/jruby@ed1773b (and in JRuby 1.7.23 and up, but Rails won't work on JRuby 1.7 anyway).

**Comment by sgrif** [comment]
Right. I'm just wondering if it'd be worth taking the opportunity to only support recent stuff and drop some of the hacky workarounds, since we're doing the same on MRI. Either way I suppose it's not hurting anything for the time being.

**Comment by rafaelfranca** [comment]
> Do we have an official policy for supported JRuby versions?

Right now it is none. Neither JRuby or Rubinius are officially supported unfortunately :cry:, our test suite was never green with these projects.

**Comment by headius** [comment]
We and others have been working to get the suite green with JRuby. Most everything except ActiveRecord is there, and I think AR is close.
