### ISSUE TITLE
Nested relations builds incorrect SQL

### ISSUE THREAD

**Issue by svoop** [rails/rails#22384]
During the migration of a Rails 4.1 app to Rails 4.2, I stumbled over the following oddity in a scope with a nested relation which does some postgis stuff:

    scope :inside, ->(area_id) { where(Area.where(id: area_id).where("ST_Intersects(locations.geography, geography)").exists) }

The `area_id` is not passed correctly with AR 4.2 whereas it works fine with AR 4.1. Here's a simplified (yet nonsensical) query to showcase the problem (see the very end of the built SQL):
    
    # AR 4.1.13
    Post.where(Comment.where(id: 123).exists).to_sql
    => SELECT "posts".* FROM "posts"  WHERE (EXISTS (SELECT "comments".* FROM "comments"  WHERE "comments"."id" = 123))

    # AR 4.2.5
    Post.where(Comment.where(id: 123).exists).to_sql
    => SELECT "posts".* FROM "posts" WHERE (EXISTS (SELECT "comments".* FROM "comments" WHERE "comments"."id" = ))

When using an inexistent attribute, the query is built correctly:

    # Rails 4.2.5
    Post.where(Comment.where(inexistent_attribute: 123).exists).to_sql
    => SELECT "posts".* FROM "posts" WHERE (EXISTS (SELECT "comments".* FROM "comments" WHERE "comments"."inexistent_attribute" = 123))

Here is a test case which shows the different behaviour on the different versions of AR. Both tests pass on 4.1, one fails on 4.2:

```ruby
begin
  require 'bundler/inline'
rescue LoadError => e
  $stderr.puts 'Bundler version 1.10 or later is required. Please update your Bundler'
  raise e
end

gemfile(true) do
  source 'https://rubygems.org'
  # Activate the gem you are reporting the issue against.
  gem 'activerecord', '4.2.5'
  gem 'sqlite3'
end

require 'active_record'
require 'minitest/autorun'
require 'logger'

# Ensure backward compatibility with Minitest 4
Minitest::Test = MiniTest::Unit::TestCase unless defined?(Minitest::Test)

# This connection will do for database-independent bug reports.
ActiveRecord::Base.establish_connection(adapter: 'sqlite3', database: ':memory:')
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :posts, force: true do |t|
  end

  create_table :comments, force: true do |t|
    t.integer :post_id
  end
end

class Post < ActiveRecord::Base
  has_many :comments
end

class Comment < ActiveRecord::Base
  belongs_to :post
end

class BugTest < Minitest::Test
  def test_nested_relation_with_existant_attribute
    sql = Post.where(Comment.where(id: 123).exists).to_sql
    sql.gsub!(/ +/, ' ')   # needed to collapse double spaces by AR 4.1
    assert_equal %q{SELECT "posts".* FROM "posts" WHERE (EXISTS (SELECT "comments".* FROM "comments" WHERE "comments"."id" = 123))}, sql
  end

  def test_nested_relation_with_inexistent_attribute
    sql = Post.where(Comment.where(inexistent_attribute: 123).exists).to_sql
    sql.gsub!(/ +/, ' ')   # needed to collapse double spaces by AR 4.1
    assert_equal %q{SELECT "posts".* FROM "posts" WHERE (EXISTS (SELECT "comments".* FROM "comments" WHERE "comments"."inexistent_attribute" = 123))}, sql
  end
end
```

**Comment by sgrif** [comment]
There is no `Relation#exists` in the public API, and is an internal method that's delegating to Arel. As such, this is not supported usage, and as with any internal APIs, may break between versions without deprecation.

**Comment by svoop** [comment]
@sgrif Gosh, I didn't see that, thanks for your reply and sorry for the noise. Too bad though, I really liked this syntax for subqueries. Maybe, one day, it'll make it to the public API. (Or is there another nice way to write EXISTS subqueries without raw SQL?)

**Comment by sgrif** [comment]
We've discussed supporting `where.exists(other_relation)` at some point in the future.

**Comment by svoop** [comment]
Nice, thanks for the hint. (Duplicate of #16959.)
