### ISSUE TITLE
Schema.rb generated incorrectly for columns with default of Infinity

### ISSUE THREAD

**Issue by pehrlich** [rails/rails#22396]
Using postgres.  With this as our migration:

```ruby
add_column :my_table, :score, :float, default: Float::INFINITY
```

When I run `bin/rake db:schema:dump`, the column is dumped as this:

```ruby
 t.float    "score",         default: Infinity
```

This is, of course, results in "uninitialized constant Infinity".  See [this thread](http://stackoverflow.com/questions/18460785/what-are-the-types-of-infinity-and-nan).

This is a problem because it makes schema.rb unusable if the changes are actually checked in :-/

**Comment by raimo** [comment]
I'm seeing the following Infinity -> ::Float::INFINITY replacement in range.rb:

https://github.com/rails/rails/blob/master/activerecord/lib/active_record/connection_adapters/postgresql/oid/range.rb#L16

Maybe this can be used for float columns too?

**Comment by RecursiveCptHook** [comment]
:+1:

**Comment by jeremy** [comment]
#24571
