### ISSUE TITLE
counter_cache breaks relation extension (doc update?)

### ISSUE THREAD

**Issue by muichkine** [rails/rails#22392]
Hello,

Such a setup works just fine:

```
# transaction.rb
class Transaction < ActiveRecord::Base
  has_many    :events, :dependent => :destroy do
    Event.descendants.each do |klass|
      define_method klass.to_relation do
        proxy_association.select{ |ev| ev.kind_of? klass }
      end
    end
  end
end

# event.rb
class Event < ActiveRecord::Base
   belongs_to :transac, :class_name => 'Transaction', :inverse_of => :events, :foreign_key => :transaction_id
end
Dir[Rails.root.join('app', 'models', '*_event.rb')].each { |f| require_dependency f } #Make sure to have all Event's descendants loaded
```

now, adding `:counter_cache => true` to the `belongs_to :transac` removes all the `has_many` relation extensions (undefined method). Breakpointing the code, no `define_method` is called to extend the `has_many` relation. Just like if `require_dependency` was missing.

Would that be an undocumented usage limitation / incompatibility between counter_cache and relation extensions?

Rails 4.2.5

**Comment by rafaelfranca** [comment]
Could you create a reproduction script with this template https://github.com/rails/rails/blob/master/guides/bug_report_templates/active_record_master.rb?

**Comment by muichkine** [comment]
Hmm. This seems to work: https://gist.github.com/muichkine/2468a74c4dae4db6995c

Three possibilities I could see:

 1 - It really is linked to `require_dependancy` but that seems really far fetched
 2 - This fails due to some reason linked to the fact that my class is called Transaction (also far fetched)
 3 - This is linked to my underlying adapter (activerecord-sqlserver-adapter)

I'll see if I can narrow that.
