### ISSUE TITLE
ActionController::TestCase#process(action, *args) throwing TypeError:  no implicit conversion of Symbol into Integer when passing a JSON string as request body and specifying :format as :json

### ISSUE THREAD

**Issue by jiggneshhgohel** [rails/rails#22393]
I am working on making my Rails 4.2.0/Ruby 2.2.1 app ready for Rails 5/Ruby 2.2.3 and for which I am using the Rails 5 edge version. My `Gemfile.lock` has following entry for Rails 

```
GIT
  remote: https://github.com/rails/rails.git
  revision: 58df2f4b4abcce0b698c2540da215a565c24cbc9
```

I have a controller spec in my app

      it "responds with 201 success" do
        ....
        post :create, params: params # params is a hash and one of the param holds a deep-nested structure

        expect(response).to have_http_status(201)
        ....
     end

One of the param holds an Array of hashes as shown below:

```
[
   {
      pref: {
      },
      another_pref: [
         {
            hash contents
         },
        {
           another hash contents
        }
      ]
   },
   {
      pref: {
      },
      another_pref: [
         {
            hash contents
         }
      ]
   },
   {
      pref: {
      },
      another_pref: [
         {
            hash contents
         },
         {
            another hash contents
         },
         {
            one more hash contents
         },
      ]
   }
]
```

The problem is that till the params reaches the controller's action logic the deeply nested structure param gets mingled up. I guess its happening because of some parse level limitation on parameters parsing. Thus I thought to pass the params in JSON format and pass a content-type in the request as :json as shown below:

```
      it "responds with 201 success" do
        ....
        post :create, params: params.to_json, format: :json

        expect(response).to have_http_status(201)
        ....
     end
```

But after this change when I run the example I get following error:

```
     Failure/Error: post :create, params: params.to_json, format: :json
     TypeError:
       no implicit conversion of Symbol into Integer
     # /home/jignesh/.rvm/gems/ruby-2.2.3@myapp-on-rails-5/bundler/gems/rails-58df2f4b4abc/actionpack/lib/action_controller/test_case.rb:473:in `[]='
     # /home/jignesh/.rvm/gems/ruby-2.2.3@myapp-on-rails-5/bundler/gems/rails-58df2f4b4abc/actionpack/lib/action_controller/test_case.rb:473:in `process'
     # /home/jignesh/.rvm/gems/ruby-2.2.3@myapp-on-rails-5/bundler/gems/devise-cce8cf676e39/lib/devise/test_helpers.rb:19:in `block in process'
     # /home/jignesh/.rvm/gems/ruby-2.2.3@myapp-on-rails-5/bundler/gems/devise-cce8cf676e39/lib/devise/test_helpers.rb:75:in `catch'
     # /home/jignesh/.rvm/gems/ruby-2.2.3@myapp-on-rails-5/bundler/gems/devise-cce8cf676e39/lib/devise/test_helpers.rb:75:in `_catch_warden'
     # /home/jignesh/.rvm/gems/ruby-2.2.3@myapp-on-rails-5/bundler/gems/devise-cce8cf676e39/lib/devise/test_helpers.rb:19:in `process'
     # /home/jignesh/.rvm/gems/ruby-2.2.3@myapp-on-rails-5/bundler/gems/rails-58df2f4b4abc/actionpack/lib/action_controller/test_case.rb:614:in `process_with_kwargs'
     # /home/jignesh/.rvm/gems/ruby-2.2.3@myapp-on-rails-5/bundler/gems/rails-58df2f4b4abc/actionpack/lib/action_controller/test_case.rb:373:in `post'
```

I checked the code at [L473](https://github.com/rails/rails/blob/58df2f4b4abcce0b698c2540da215a565c24cbc9/actionpack/lib/action_controller/test_case.rb#L473)  and found this code

```
        parameters ||= {}

        if format.present?
          parameters[:format] = format
        end
```

That looks like a bug to me because `parameters` is holding a String (because of params.to_json) and the code tries to assign `:format` key on a String, instead of a Hash.

Thanks.

**Comment by jiggneshhgohel** [comment]
My bad. `body`, instead of `params` is what supposed to be used:

```
      it "responds with 201 success" do
        ....
        post :create, body: params.to_json, format: :json

        expect(response).to have_http_status(201)
        ....
     end
```

I tried that but that still returns `content_mime_type: url_encoded_form` and not `:json`. As an alternative I tried following:

```
        request.content_type = 'application/json'
        post :create, body: params.to_json
```

and the params are being received at controller end in the structure I am expecting them to.

That brings up one question: Is `format` not usable when using `body`?

**Comment by rafaelfranca** [comment]
Please use the mailing list or StackOverflow for questions/help, where a wider community will be able to help you. We reserve the issues tracker for issues only.
