### ISSUE TITLE
ActiveRecord 4.2.5 issue with Ruby 1.9.3 (Psych::Coder)

### ISSUE THREAD

**Issue by CarlosCD** [rails/rails#22397]
I was running Rails 4.2.4 on Ruby 1.9.3-p448 (production, staging... all of it). I've just tried to upgrade to 4.2.5, and it seems that includes a breaking change (breaking with Ruby 1.9.3). On `lib/active_record/legacy_yaml_adapter.rb`.

The line is:

    module ActiveRecord
      module LegacyYamlAdapter
        def self.convert(klass, coder)
          return coder unless coder.is_a?(Psych::Coder)
          ...

Which gives me an exception: `NameError: uninitialized constant Psych::Coder`.

I am not sure if this was a decision to remove compatibility with 1.9.3 in Rails 4.2.

I know, I know, need to upgrade to ruby 2... when my IT department allows it...

Thanks guys!

**Comment by CarlosCD** [comment]
This problem showed just after the upgrade, during a deployment to staging, while it run `rake db:migrate`.

I did make it work by adding the last version of psych to the Gemfile, not other issues found so far:

    gem 'rails', '4.2.5'
    gem 'psych', '2.0.15'

**Comment by CarlosCD** [comment]
What I meant, is that psych is not an active record explicit dependency. I am not sure if it would make sense to add it to the gemspec. Does it make any sense?

**Comment by sgrif** [comment]
Can you give a full stack trace? This definitely shouldn't be an issue on 1.9.3, as Psych has been included in the stdlib since 1.9.2, and has been the default yaml encoder in MRI since 1.9.3

**Comment by CarlosCD** [comment]
I was about to send the trace to you, and looked a bit further. I wasn't aware, but it looks like libyaml is not installed in our servers (Red Hat 6), which have been running different versions of Rails for a very long time. I believe that is the issue. By adding psych gem it gets over the problem by adding the native support.  So you can consider this a non issue and close it, as a deficiency in my ruby installation :(

I couldn't reproduce it in my laptop either (OS X, with RVM, psych as part of it), but it consistently happened in the server (Red Hat) during the deployment (Capistrano), unless I add the psych gem. This is the deployment stack trace after `RAILS_ENV=staging bundle exec rake db:migrate` (when the script explodes):

    rake stderr: rake aborted!
    NameError: uninitialized constant Psych::Coder
    shared/bundle/ruby/1.9.1/gems/activerecord-4.2.5/lib/active_record/legacy_yaml_adapter.rb:4:in `convert'
    shared/bundle/ruby/1.9.1/gems/activerecord-4.2.5/lib/active_record/core.rb:302:in `init_with'
    shared/bundle/ruby/1.9.1/gems/activerecord-4.2.5/lib/active_record/persistence.rb:69:in `instantiate'
    shared/bundle/ruby/1.9.1/gems/activerecord-4.2.5/lib/active_record/querying.rb:50:in `block (2 levels) in find_by_sql'
    shared/bundle/ruby/1.9.1/gems/activerecord-4.2.5/lib/active_record/result.rb:51:in `block in each'
    shared/bundle/ruby/1.9.1/gems/activerecord-4.2.5/lib/active_record/result.rb:51:in `each'
    shared/bundle/ruby/1.9.1/gems/activerecord-4.2.5/lib/active_record/result.rb:51:in `each'
    shared/bundle/ruby/1.9.1/gems/activerecord-4.2.5/lib/active_record/querying.rb:50:in `map'
    shared/bundle/ruby/1.9.1/gems/activerecord-4.2.5/lib/active_record/querying.rb:50:in `block in find_by_sql'
    shared/bundle/ruby/1.9.1/gems/activesupport-4.2.5/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
    shared/bundle/ruby/1.9.1/gems/activerecord-4.2.5/lib/active_record/querying.rb:49:in `find_by_sql'
    shared/bundle/ruby/1.9.1/gems/activerecord-4.2.5/lib/active_record/relation.rb:639:in `exec_queries'
    shared/bundle/ruby/1.9.1/gems/activerecord-4.2.5/lib/active_record/relation.rb:515:in `load'
    shared/bundle/ruby/1.9.1/gems/activerecord-4.2.5/lib/active_record/relation.rb:243:in `to_a'
    shared/bundle/ruby/1.9.1/gems/activerecord-4.2.5/lib/active_record/relation/delegation.rb:46:in `map'
    shared/bundle/ruby/1.9.1/gems/activerecord-4.2.5/lib/active_record/migration.rb:847:in `get_all_versions'
    shared/bundle/ruby/1.9.1/gems/activerecord-4.2.5/lib/active_record/migration.rb:988:in `migrated'
    shared/bundle/ruby/1.9.1/gems/activerecord-4.2.5/lib/active_record/migration.rb:993:in `ran?'
    shared/bundle/ruby/1.9.1/gems/activerecord-4.2.5/lib/active_record/migration.rb:970:in `block in runnable'
    shared/bundle/ruby/1.9.1/gems/activerecord-4.2.5/lib/active_record/migration.rb:970:in `reject'
    shared/bundle/ruby/1.9.1/gems/activerecord-4.2.5/lib/active_record/migration.rb:970:in `runnable'
    shared/bundle/ruby/1.9.1/gems/activerecord-4.2.5/lib/active_record/migration.rb:955:in `migrate'
    shared/bundle/ruby/1.9.1/gems/activerecord-4.2.5/lib/active_record/migration.rb:823:in `up'
    shared/bundle/ruby/1.9.1/gems/activerecord-4.2.5/lib/active_record/migration.rb:801:in `migrate'
    shared/bundle/ruby/1.9.1/gems/activerecord-4.2.5/lib/active_record/tasks/database_tasks.rb:137:in `migrate'
    shared/bundle/ruby/1.9.1/gems/activerecord-4.2.5/lib/active_record/railties/databases.rake:44:in `block (2 levels) in <top (required)>'
    Tasks: TOP => db:migrate

I've tried to deploy again, after removing psych form the gemfile, same exception.

I'll try to convince IT to install libyaml, or if they refuse, keep the gem there.

Thanks for pushing back Sean! :)

Best,
Carlos

**Comment by sgrif** [comment]
Thanks for following up.
