### ISSUE TITLE
If DuplicatePstatement will happen once, activerecord goes into DuplicatePstatement loop

### ISSUE THREAD

**Issue by stenver** [rails/rails#22408]
We started seeing this issue in the logs:

```
#<ActiveRecord::StatementInvalid: PG::DuplicatePstatement: ERROR:  prepared statement "a22092" already exists
: INSERT INTO "locations" ("city", "country_code", "country", "state", "visit_id") VALUES ($1, $2, $3, $4, $5) RETURNING "id">
/home/deployer/services/visit_registry/shared/bundle/ruby/2.2.0/gems/activerecord-4.2.0/lib/active_record/connection_adapters/postgresql_adapter.rb:637:in `prepare'
/home/deployer/services/visit_registry/shared/bundle/ruby/2.2.0/gems/activerecord-4.2.0/lib/active_record/connection_adapters/postgresql_adapter.rb:637:in `prepare_statement'
```

Digging deeper, I found this piece of code:

https://github.com/rails/rails/blob/master/activerecord/lib/active_record/connection_adapters/postgresql_adapter.rb#L625

Basically, if the `@connection.prepare nextkey, sql` fails for some reason, then the `nextkey` will not get saved. 

If the failure was because of `DuplicatePstatement`, this will become a problem, as subsequent prepared statement to also fail due to having an existing statement name.

**Comment by liangchen2000** [comment]
A nice issue

**Comment by LcpMarvel** [comment]
+1

**Comment by ivanreese** [comment]
If I understand correctly, this was explored in depth in #17607. The outcome seems to be that issue is most commonly caused by the `rack-timeout` gem, which is pretty nasty in that it can raise an exception at nearly any time. The Rails core team don't seem inclined to code the framework to defend against having the carpet pulled out from under them at any moment, which is totally reasonable.

I don't think there's a clean solution to this problem at this time, based on all my reading so far.

**Comment by ricardovj** [comment]
Hey guys, is anyone else experiencing this issue? We're running into this exact error every couple of weeks, we're on rails 6, ruby 2.7.
![image](https://user-images.githubusercontent.com/1091686/76860466-75f68d80-6831-11ea-8a5c-20e3e2da673b.png)

**Comment by ko-lem** [comment]
> Hey guys, is anyone else experiencing this issue? We're running into this exact error every couple of weeks, we're on rails 6, ruby 2.7.

Same here. I just restart dynos if I'm up when it happens, like now. Don't know what else to do.

**Comment by rafaelfranca** [comment]
This is now fixed in 6-1-stable

**Comment by kbighorse** [comment]
I have seen this issue on Rails 5.2.x, was the 6.1 fix backported to Rails 5?

**Comment by seanlinsley** [comment]
I'm guessing https://github.com/rails/rails/pull/41356 is the change that fixed this issue. (just linking them together – I haven't confirmed yet)
