### ISSUE TITLE
collection_check_boxes does not produce the correct check box name property

### ISSUE THREAD

**Issue by NeilBetham** [rails/rails#22405]
When using the collection_check_boxes form helper the name property on the rendered check boxes is not correct in some cases. For my case specifically I have a form which contains multiple sets of fields for a array of models. Each of those models then has a relationship collection to another model. 

For example using a `collection_select` with `multiple: true` would result in a select tag name of `models[][relationship_ids][]` which is what I would expect. However when using `collection_check_boxes` the resulting check box tags have a name of `models[relationship_ids][]` which, correct me if i'm wrong, I don't think is the intended result. For reference here is a snippet of the form setup I have generalized a bit:
##### Produces the incorrect tag name

```
= form_for :models, url: models_path do |f|
  - @models.each do |model|
    = fields_for 'models[]', model do |model_form|
      = model_form.collection_check_boxes :relationship_ids, Collection.all, :id, :name
```
##### Produces the correct tag name

```
= form_for :models, url: models_path do |f|
  - @models.each do |model|
    = fields_for 'models[]', model do |model_form|
      = model_form.collection_select :relationship_ids, Collection.all, :id, :name, {}, {multiple: true}
```

**Comment by maclover7** [comment]
What solution do you think would be appropriate for this?

**Comment by NeilBetham** [comment]
I don't have a solution yet. I have got a work around which produces what I would expect given how the other collection selects work. Adding `index: ''` to the options for `collection_check_boxes` prevents it from collapsing the intermediate array in the name.
