### ISSUE TITLE
Destroy with permanent_records is broken

### ISSUE THREAD

**Issue by gsmetal** [rails/rails#22417]
Hello. I'm using permanent_records gem and it's broken (https://github.com/JackDanger/permanent_records/issues/53) since 4.2.5 because of this change in attribute_set.rb of activerecord:
```ruby
    def ==(other)
      attributes == other.attributes
    end
```
So the question is: Is it  permament_records' problem working with `@attributes` in incorrect way or attribute_set's problem assuming that `other` is always respond to `attributes` method?

**Comment by sgrif** [comment]
`permanent_records` shouldn't be accessing `@attributes`, or other AR internals.
