### ISSUE TITLE
ActiveJob perform_now and perform_later should accept the same arguments

### ISSUE THREAD

**Issue by jtmarmon** [rails/rails#22413]
As mentioned in #18519 

> There should be a symmetry between deliver_now and deliver_later. If parameters are accepted in one, they should be accepted in the other.

It doesn't make sense that `perform_now` accepts a BigDecimal and `perform_later` does.

**Comment by sivagollapalli** [comment]
@jtmarmon Could  you provide an example so that I would give a shot?

**Comment by jtmarmon** [comment]
```rb
class FooJob < ActiveJob::Base
   def perform(args)
   end
end
```

```rb
>  FooJob.perform_now(bar: BigDecimal(5))
=> nil
>  FooJob.perform_later(bar: BigDecimal(5))
=> ActiveJob::SerializationError: Unsupported argument type: BigDecimal
```

This is using Sidekiq as an adapter. I think this bug won't surface without one because `perform_later` is the same as `perform_now` without one.
