### ISSUE TITLE
db:structure:dump with MySQL includes current timestamp

### ISSUE THREAD

**Issue by atsheehan** [rails/rails#22412]
When running `rake db:structure:dump` in an application with MySQL configured, the generated `db/structure.sql` file contains the timestamp for when the dump was completed. Even if the underlying database does not change, running `rake db:structure:dump` will produce a different output each time. Because `db/structure.sql` is often version controlled, this timestamp will generate a lot of noise if each change is committed.

If the `config.active_record.schema_format = :sql` option is set, this command is also run after `rake db:migrate`, updating the `db/structure.sql` file even if no new migrations are run.

A test case has been included at [https://gist.github.com/atsheehan/3477a1659b97741de4ae](https://gist.github.com/atsheehan/3477a1659b97741de4ae). It creates a new MySQL database, performs two structure dumps within a few seconds of each other, and checks if they differ. This test requires MySQL to be installed and running locally.

This behavior of `mysqldump` is also described at [https://bugs.mysql.com/bug.php?id=31077](https://bugs.mysql.com/bug.php?id=31077). It appears that a `--skip-dump-date` flag has been added around 2007 that avoids this issue.

If this sounds like a valid issue, I believe the fix would be to include the `--skip-dump-date` option [here](https://github.com/rails/rails/blob/master/activerecord/lib/active_record/tasks/mysql_database_tasks.rb#L58-L61). Adding an extra flag when calling an external program might break old versions of `mysqldump`, but since the patch to include it was from 2007 I would assume most clients support it by now.

**Comment by atsheehan** [comment]
Here's an example of a `git diff` after running `rake db:migrate` without any modifications to the database:

```
diff --git a/db/structure.sql b/db/structure.sql
index cc5f1a1..0e993be 100644
--- a/db/structure.sql
+++ b/db/structure.sql
@@ -1034,6 +1034,6 @@ CREATE TABLE `users` (
 /*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
 /*!40111 SET SQL_NOTES=@OLD_SQL_NOTES */;

--- Dump completed on 2015-11-25 13:42:22
+-- Dump completed on 2015-11-25 15:09:07
```

**Comment by rishav** [comment]
Seems like a valid issue, can you create a Pull Request ? I can do it if you want me to

**Comment by datashaman** [comment]
an observation from the sidelines: that dump date is very useful for resolving merge conflicts (and they happen often with this file during project creation).
