### ISSUE TITLE
Decimal: Check attribute has value (with attrname?)

### ISSUE THREAD

**Issue by Sega100500** [rails/rails#22424]
I use RoR 4.2.5

in migration:
```
t.decimal :price, precision: 12, scale: 2
```

Convenient to use `@value.price?` to check for the value of any. Check for is not nil and not zero.

```
@value.price = nil
@value.price? #=> false

@value.price = 0
@value.price? #=> false
```

All Ok!

But!
```
@value.price = 0.01
@value.price? #=> false

@value.price = 0.9
@value.price? #=> false

@value.price = -0.9
@value.price? #=> false

@value.price = 1.0
@value.price? #=> true

@value.price = -1.0
@value.price? #=> true
```

WHY?

**Comment by anujaware** [comment]
@Sega100500 Can you print what value it assigns to price when you assign "0.9"? i.e. 

```ruby 
  @value.price = 0.9
  p @value.price
```
and paste the output here.
I tried above code and its working. I have doubt if it assigns 0 (floors the number) when you try to assign some decimal number.

**Comment by Sega100500** [comment]
@anujaware 

```
0.9
```

What are you expecting something else?

**Comment by anujaware** [comment]
Then it should return true. I was thinking if its assigning 0 in your case. I am not able to reproduce this error.

**Comment by Sega100500** [comment]
@anujaware 

Web console:

```
>> p @product.price
=> 0.9
>> p @product.price?
=> false
```

**Comment by Sega100500** [comment]
@anujaware 

Exactly!

"Then it should return true"

But it return false

**Comment by anujaware** [comment]
@Sega100500 You can debug this in lib/active_record/attribute_methods/query.rb#query_attribute(attr_name) in activerecord gem.

**Comment by Sega100500** [comment]
@anujaware 
Web console:
```
>> @product.price = 0
=> 0
>> p @product.price?
=> false
>> @product.price = 1.0
=> 1.0
>> p @product.price?
=> true
>> @product.price = 0.9
=> 0.9
>> p @product.price?
=> false
```

**Comment by Sega100500** [comment]
@anujaware 
ruby -v
ruby 2.2.3p173 (2015-08-18 revision 51636) [x86_64-linux]

RoR 4.2.5

May be it help ?

**Comment by Sega100500** [comment]
@anujaware 

BUG!!! in `query_attribute(attr_name)`

```
          if column.nil?
            if Numeric === value || value !~ /[^0-9]/
              !value.to_i.zero?
            else
              return false if ActiveRecord::ConnectionAdapters::Column::FALSE_VALUES.include?(value)
              !value.blank?
            end
          elsif column.number?
            !value.zero?
          else
            !value.blank?
          end
```

Steps:

```
>> @product.price = 0.9
=> 0.9
>> @product.price.zero?
=> false
>> @product.class.columns_hash['price']
=> nil
>> @product.class.columns_hash[:price]
=> nil
>> p @product[:price]
=> 0.9
>> 0.9 === Numeric
=> false
>> Numeric === 0.9 || 0.9 !~ /[^0-9]/
=> true
>> 0.9.to_i
=> 0
>> 0.9.to_i.zero?
=> true

**Comment by sivagollapalli** [comment]
I think this line `Numeric === 0.9 || 0.9 !~ /[^0-9]/` creating the issue. As `===` checks the case equality so when we compare `Numeric === 0.9` it returns `true` as `Numeric` is an ancestor for `Float` numbers. I think the fix would be something like this:

```
if column.nil?
    if Numeric === value || value !~ /[^0-9]/
         return !value.to_f.zero? if Float == value
         !value.to_i.zero?
      else
          return false if ActiveRecord::ConnectionAdapters::Column::FALSE_VALUES.include?(value)
           !value.blank?
       end
    elsif column.number?
         !value.zero?
    else
         !value.blank?
     end
```

**Comment by Sega100500** [comment]
@sivagollapalli 
Not the most elegant solution. But even so.

PLEASE FIX it

**Comment by Sega100500** [comment]
@sivagollapalli 
"As === checks the case equality so when we compare Numeric === 0.9 it returns true as Numeric is an ancestor for Float numbers."

```
>> 0.9 === Numeric
=> false
```

**Comment by anujaware** [comment]
Still I am not able to reproduce this issue with ruby 2.2.3p173 (2015-08-18 revision 51636) [x86_64-linux] and rails 4.2.5. Before having solution. I am not getting why you are not getting that column in column_hash. And why we have Numericality check. 
Which database are you using?

**Comment by adityashedge** [comment]
@Sega100500 I am not able to reproduce this issue.
I have tried both Ruby 2.2.2 and 2.2.3. Also I double checked with Sqlite3 and Postgresql on both Ruby versions.
```
$ ruby -v
ruby 2.2.3p173 (2015-08-18 revision 51636) [x86_64-darwin14]

$ rails -v
Rails 4.2.5
```

```ruby
2.2.3 :003 > pr
 => #<Product id: nil, price: nil, created_at: nil, updated_at: nil>
2.2.3 :004 > pr.price
 => nil
2.2.3 :005 > pr.price?
 => false
2.2.3 :006 > pr.price = 0
 => 0
2.2.3 :007 > pr.price?
 => false
2.2.3 :008 > pr.price = 0.01
 => 0.01
2.2.3 :009 > pr.price?
 => true
2.2.3 :010 > pr.price = 0.09
 => 0.09
2.2.3 :011 > pr.price?
 => true
2.2.3 :012 > pr.price = -0.09
 => -0.09
2.2.3 :013 > pr.price?
 => true
```

Can you create a new Github repo to reproduce this error?

**Comment by Sega100500** [comment]
@anujaware 
"Which database are you using?"
MySQL

**Comment by Sega100500** [comment]
@anujaware 
"I am not getting why you are not getting that column in column_hash"

Because this SQL:
```
SELECT products.*, contents.*, products.id AS product_id FROM `contents` INNER JOIN products ON products.content_id = contents.id WHERE (contents.visible != 0) AND `contents`.`visible` = 1 AND `contents`.`furl` = 'apple-iphone-5s-16gb' AND `products`.`id` = 191 AND `products`.`category_id` = 312 GROUP BY contents.id
```
to get with related content-page

```
>> @product.class.columns_hash.keys
=> ["id", "parent_id", "level", "position", "node_type", "user_id", "group_id", "restrictive_group_id", "visible", "system", "list", "no_children", "no_images", "no_files", "key_lock", "key", "url", "furl", "alias", "name", "brief", "text", "title", "seo", "keywords", "description", "special", "content_parameter", "content_date", "created_at", "updated_at"]
```

```
>> @product.price = 0.9
=> 0.9
>> @product[:price]
=> 0.9
```

It is VALID COE! But you have not considered this possibility.
columns_hash NOT contain joined columns but access to they - it possible!

**Comment by Sega100500** [comment]
@adityashedge 
Too simple example of ALL possible usages.

**Comment by Sega100500** [comment]
@anujaware 
Anyway
the code
```
            if Numeric === value || value !~ /[^0-9]/
              !value.to_i.zero?
            else
```
It is BUG! Not correct to check Float numbers.

**Comment by sivagollapalli** [comment]
@Sega100500 

Looks like there is no issue. Just now I have checked with `mysql` and `sqlite3` with `4.2.5` and `ruby-2.2.3`.  All my tests are passing. If you still face please update below template and submit so that we can check.

Please ignore my previous comments. 

```
begin
  require 'bundler/inline'
rescue LoadError => e
  $stderr.puts 'Bundler version 1.10 or later is required. Please update your Bundler'
  raise e
end

gemfile(true) do
  source 'https://rubygems.org'
  gem 'rails', '4.2.5' 
  #gem 'sqlite3'
  gem 'mysql'
end

require 'active_record'
require 'minitest/autorun'
require 'logger'

ActiveRecord::Base.establish_connection(adapter: 'mysql', database: 'bug_test')
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :products do |t| 
    t.string :price
  end 
end

class Product < ActiveRecord::Base
end

class BugTest < Minitest::Test
  def test_price
    p = Product.new
    p.price = 0.9
    assert_equal true, p.price?

    p.price = 0.01
    assert_equal true, p.price?

    p.price = -0.9
    assert_equal true, p.price?

    p.price = 1.0
    assert_equal true, p.price?

    p.price = -1.0
    assert_equal true, p.price?
  end
end

```

**Comment by Sega100500** [comment]
@sivagollapalli 
See above
1. joined tables
2. bug code for check Float is:
```
            if Numeric === value || value !~ /[^0-9]/
              !value.to_i.zero?
            else
```
Also any questions?

**Comment by Sega100500** [comment]
@sivagollapalli 
Are you crazy?
```
  create_table :products do |t| 
    t.string :price
  end 
```

At BEGIN
```
t.decimal :price, precision: 12, scale: 2
```

**Comment by Sega100500** [comment]
The code in `lib/active_record/attribute_methods/query.rb#query_attribute(attr_name)` is incorrect to check Float value! Why are you trying to prove the opposite in every way?

**Comment by sivagollapalli** [comment]
@Sega100500 oops, that's my bad. Now I modified column to `decimal` but it didn't change my result. Still my tests are passing. Could you please paste exact code snippets of your project so that it easy to debug?

**Comment by Sega100500** [comment]
@sivagollapalli
Oooooohhhh!
SEE ABOVE!!!
1. joined table
```
SELECT products.*, contents.*, products.id AS product_id FROM `contents` INNER JOIN products ON products.content_id = contents.id WHERE (contents.visible != 0) AND `contents`.`visible` = 1 AND `contents`.`furl` = 'apple-iphone-5s-16gb' AND `products`.`id` = 191 AND `products`.`category_id` = 312 GROUP BY contents.id
```
2. Then `columns_hash` not contains `price` column
3. Then code:
```
            if Numeric === value || value !~ /[^0-9]/
              !value.to_i.zero?
            else
```
Is BUG!

This can be understood?

See the sources, Luk!
`lib/active_record/attribute_methods/query.rb#query_attribute(attr_name)`

**Comment by adityashedge** [comment]
@Sega100500 You can use this repo to reproduce the exact error. It does not occur for a single table(model). What I understand from your comments is that it occurs when you join multiple tables.

https://github.com/adityashedge/test-2.2.3-22424.git

**Comment by Sega100500** [comment]
@anujaware 
"when you join multiple tables"
Not only that!

In case when
```
          if column.nil?
            if Numeric === value || value !~ /[^0-9]/
              !value.to_i.zero?
            else
              return false if ActiveRecord::ConnectionAdapters::Column::FALSE_VALUES.include?(value)
              !value.blank?
            end
```
if column.nil? - if true
The code:
```
            if Numeric === value || value !~ /[^0-9]/
              !value.to_i.zero?
            else
```
is BUG to check Float number

**Comment by matthewd** [comment]
@Sega100500 less yelling please.

http://edgeguides.rubyonrails.org/contributing_to_ruby_on_rails.html#create-an-executable-test-case

**Comment by Sega100500** [comment]
@anujaware 

Pure Ruby code:
```
p (0.9 === Numeric)
p (0.9 !~ /[^0-9]/)
p (0.9).to_i.zero?
```

result:
```
false
true
true
```

And now turn on the brain!

**Comment by Sega100500** [comment]
@matthewd 
No yelling.

I just point to bug.

Why do I still have to prove anything? Why do I have to write some other tests?
It seems pretty clear, I explained the situation.

**Comment by matthewd** [comment]
@Sega100500 https://github.com/rails/rails/issues/22424#issuecomment-160188274 is the end of this conversation.

**Comment by Sega100500** [comment]
@matthewd

Your point is - only you decide RoR will work correctly or incorrectly.

**Comment by adityashedge** [comment]
Well apart from the unrelated things, is this really an issue? Need some solid confirmation.

**Comment by rafaelfranca** [comment]
> Your point is - only you decide RoR will work correctly or incorrectly.

@Sega100500 pretty much yes. He is part of the core team and he is more than able to decide how Ruby on Rails will work.

But he didn't closed the issue because you are wrong or not. Let me explain why.

[By our licence](https://github.com/rails/rails/blob/master/railties/MIT-LICENSE):

> THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND

which means that nobody, again nobody, has obligation to fix your issues, no matter how wrong they are. We do because we want to, and you removed all the our desire to help you with comments like:

> PLEASE FIX it
> Are you crazy?
> And now turn on the brain!

At this point I may point you to our code of conduct http://rubyonrails.org/conduct. We believe you are not respecting it and we will not accept you behavior here.

@adityashedge I believe it is an issue but I don't care if it will fixed anymore. If you want to fix it please open a PR, otherwise we will fix when we think it is time.

**Comment by pixeltrix** [comment]
@Sega10050 your report which had virtually no context and then you take people to task for not being able to reproduce the problem - even the variable name you use `@product` would tend to make people think that you were using a `Product` model. It's only 12 messages in where you provide the SQL which you have to read closely to infer that you're actually using the `Content` model and then `select`-ing the product columns onto that model. In fact you never even mention `select` anywhere in this thread. 

When you fail to provide the single piece of information that would allow people to reproduce the issue is it any wonder that the issue would be closed? When you were politely asked to provide exact code examples you just dismissively directed @sivagollapalli back to previous messages - at no point did you ever provide a model definition.

It's only when you provide a bug test example in #22434 that it's immediately obvious what the problem is - this is why we always suggest doing one as it helps both you and us by focussing on the core problem and removing extraneous factors like gems, etc.

On, one other thing - the code is `Numeric === value` not `value === Numeric` - you should check whether something is commutative before abusing them, e.g:

``` irb
>> Numeric === 0.9
=> true 
```
