### ISSUE TITLE
Feature: improve includes(), sister fetch

### ISSUE THREAD

**Issue by eiked** [rails/rails#22423]
There are currently a lot problems with the include(), see my previous bug report
(we'll solve this)

But I believe, ones we're working on that,
includes() can even be improved in a big way.

As of rails 4.2.5 includes are resolved upon first query time.
I'd like to suggest instead that includes should be resolved on first access.

Let me explain:
includes() are here to avoid the n x m query problem.
So if you includes() another table, that would be prefetched with a query by id.

But there actually is no reason to fetch a related table, until we need it.

Therefor we have proxies. They tell us, ok this is not yet fetched: fetch it upon first access.

I believe that this mechanism is not yet used for includes, but it should.
But we need a twist here.
Currently the proxies are used to resolve a reference to a single related object.
So this obviously does not help in the nxm problem.

But maybe we could enhance the proxy,
so that the first access to any one proxied object,
would load all of them for the whole collection in one query.

I fear it's not that easy like this -- we might get into transaction trouble.
And fetching two step related tables might also pose some fun.
(so we might only use this for queries that we declared as readonly)
[It might also be useful to explicitely declare queries as #volatile,
 thereby explicitely declaring that a result of that query would not be transaction safe]

But thinking from a very naive read only perspective,
this could be done.

I'd imagine to enhance the proxies with a hint
so if that individual proxy is accessed,
than we should load all of the proxies in one turn,
repecting the original query.

So we need to save per object retrieved:
- the sisters objects coming from the same query
- the original query

We would then resolve on the first access to any of the sistser objects proxies
the queries includes clause and replace all sisters unresolved proxies.

This obviously brakes any notion of fetching them all together in one transaction.
Because you would then have an object tree from queries not bound in one transaction.
But who cares?  This is just the very same thing that happens with single query proxies today.

Thinking of two, three level prefetches: This can also be done, think proxy.

say you'd ask for disk.tracks.artists,
- tracks would be a sisters proxy that needs to be resolved first
- and then it's just easy to resolve artists upon that
- not sure if this should resolve all tracks.artists for all fetched disks?

But such things can be solve by enhancing the DSL,
by adding more fetch hints for deep sister fetches.

---
Woriking with ORM has never been easy.
But there's still room to improve, and we got quite far.
I love Postgres. If you get your queries right, it just flyes!
Thank you Tom.

**Comment by eiked** [comment]
Sorry, this might have been a bit above the head of the average reader.
But you bros working on the engine might get it.

The includes()n are really a very big problem.
They beat me every day.
I should look it up and fix the problem myself,
but I've not yet been that deep in rails, yet.

It looks to me like operating at a beating heart,
so i fear such changes should not be done at rails 4,
But they should be done for rails 5 (which is lurking around the door)

again: I believe the includes() is seriously broken.
This is a show stopper.

When working with ORM mapping, it is so important to get the fetches right.
This is where we need the hints.

I believe this is currently severly broken in rails.
Let's find this false optimization. It just breaks everything.
It makes a lot of trouble when I try to stack scopes.
But composibility is the single best strength of rails.
includes() breaks this.

It somehow feels like back at WebObjects,
which had so many great concepts,
but more than once failed on a detail.

But this is something completely different with rails.
Because we can improve it every day.

Looks to me, that we need some help from theory
How does late loading interact with transactions?
This should actually not be a problem with rails.
Because we're optimists.

As far as I know,
there is no promise that any object graph fetched
via ActiveRecors holds a premise to be transactional consistent?

I don't care. For that 99% reads this is just fine.
I'll have to take care of that 1% writes anyway.
We're not in banking here.

I'd like to suggest to relax the promise of the consistency of the fetches.
This shall not break any existing code.

Therefor we need mark queries.
I'd say that would be #volatile 

This would mark a query as being a one shot,
and open for additional fetches which would not be part of the initial transaction.

And all further objects retrieved from such query would also be marked as volatile.
(aka: don't believe them, this was only a shot in time, with no transaction involved)

I hear you crying, this is again one more field for every ActiveRecord object.
Please stop whyning. This is just another bit.

**Comment by maclover7** [comment]
Thank you for the issue but we don't take feature request in the issue tracker. Please read the contributing guides about which is the best channel for them.
