### ISSUE TITLE
Decimal attribute has value check differs in joined table.

### ISSUE THREAD

**Issue by simi** [rails/rails#22429]
follow up of #22424

I think this is the problem original author was thinking about.

[gist](https://gist.github.com/simi/e47d0257dde5fc242577)

``` ruby
begin
  require 'bundler/inline'
rescue LoadError => e
  $stderr.puts 'Bundler version 1.10 or later is required. Please update your Bundler'
  raise e
end

gemfile(true) do
  source 'https://rubygems.org'
  gem 'rails', '4.2.5'
  gem 'sqlite3'
end

require 'active_record'
require 'minitest/autorun'
require 'logger'

ActiveRecord::Base.establish_connection(adapter: 'sqlite3', database: ':memory:')
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :products do |t|
    t.decimal :price, precision: 12, scale: 2
    t.references :content
  end

  create_table :contents do |t|
  end
end

class Product < ActiveRecord::Base
  belongs_to :content
end

class Content < ActiveRecord::Base
  has_one :product
end

class BugTest < Minitest::Test
  def setup
    Content.delete_all; Product.delete_all;
  end

  def test_negative_price
    Content.create(product: Product.create(price: -0.9))
    joined_product = Content.joins(:product).select('products.*').first
    product = Product.first
    assert_equal product.price?, joined_product.price?
  end

  def test_positive_price
    Content.create(product: Product.create(price: 0.9))
    joined_product = Content.joins(:product).select('products.*').first
    product = Product.first
    assert_equal product.price?, joined_product.price?
  end

  def test_nil_price
    Content.create(product: Product.create)
    joined_product = Content.joins(:product).select('products.*').first
    product = Product.first
    assert_equal product.price?, joined_product.price?
  end

  def test_zero_price
    Content.create(product: Product.create(price: 0))
    joined_product = Content.joins(:product).select('products.*').first
    product = Product.first
    assert_equal product.price?, joined_product.price?
  end
end
```

```
Finished in 0.060232s, 66.4101 runs/s, 66.4101 assertions/s.

  1) Failure:
BugTest#test_negative_price [test.rb:48]:
Expected: true
  Actual: false


  2) Failure:
BugTest#test_positive_price [test.rb:55]:
Expected: true
  Actual: false
```

If anyone can decide if this is real issue, I can submit patch to fix this.

/cc @adityashedge

**Comment by Sega100500** [comment]
@anujaware
MANY THANKS! Really!
I was point to that string in code several times in https://github.com/rails/rails/issues/22424
But my messages was ignored.

**Comment by pixeltrix** [comment]
The problem is that you're creating virtual attributes which don't appear in the `columns_hash` - doing something like `Content.joins(:product).select('products.*').first` is very much an edge case. Because of the failure to find a column the code assumes that the data is a string and tries to interpret it as best it can. There is a problem with decimals less that one but given the inherent accuracy problems with floats doing `to_f.zero?` isn't the right answer - do we say that it's false if it's within a small fraction of zero?

**Comment by Sega100500** [comment]
@anujaware

Once again about `lib/active_record/attribute_methods/query.rb#query_attribute(attr_name)`

code (line 19 in 4.2.5):
```
if Numeric === value || value !~ /[^0-9]/
```
is check for **Integer** only. If **Float** is represents as **String** this check is wrong.
```
v1 = 0.9
v2 = '0.9'

p (Numeric === v1 || v1 !~ /[^0-9]/)
p (Numeric === v2 || v2 !~ /[^0-9]/)

=> true
=> false
```

@pixeltrix
Sometimes mistakes (like a `0.9 === Numeric` is not same 'Numeric === 0.9`) are can detect other errors like this above. (About your answer to me in https://github.com/rails/rails/issues/22424 which is locked for me).
Secondly. "It's only 12 messages in where you provide the SQL"
If I just knew where to look, what exactly is checked attribute value, then there would be the 12 posts prior to provide the SQL.
Once prompted me exactly **where to look** (`lib/active_record/attribute_methods/query.rb#query_attribute(attr_name)`), I've found the problem and reported it.
