### ISSUE TITLE
Default scopes and STI conditions don't get along

### ISSUE THREAD

**Issue by matthewd** [rails/rails#22426]
This is a regression on master, from 4.2.

https://gist.github.com/matthewd/9d04c50cefa82729fa21

1. The subclass is persisted with `type` as the superclass that has a `default_scope`
2. When querying for the subclass, the `type` condition allows all children of the `default_scope` class

**Comment by kuldeepaggarwal** [comment]
3. Default scope is getting multiplied in the inheriting chain.

**Comment by matthewd** [comment]
Bisect says this broke in 5e0b555b453ea2ca36986c111512627d806101e7

/cc @sgrif
