### ISSUE TITLE
ActiveRecord::first method does not always apply `ORDER BY PRIMARY_KEY` sql

### ISSUE THREAD

**Issue by ziomio** [rails/rails#22438]
See `ADDED LATER` section from my SO question:
http://stackoverflow.com/questions/33917763/does-activerecordfirst-method-always-return-record-with-minimal-id

In short, when applying `first` method on already `loaded` records - `first` method simply returns @record[index] record without applying `order by' to SQL.

But Ruby on Rails documentation
http://guides.rubyonrails.org/active_record_querying.html
 on the other hand explicitly specifies that `first` orders records:

> 1.1.3 first
> The first method finds the first record ordered by the primary key. 

So either documentation or method need to be corrected.

**Comment by rishav** [comment]
The resulting fix may create more confusing behaviour. 

For me 
<code>
   records =  YourModel.where(" some condition ").order ("some_column DESC") 
</code>

In the above collection of records, it expectation can also be to list the first object in the ActiveRecord::Relation collection, not anything to do with the order.

**Comment by RochesterinNYC** [comment]
@ziomio Regarding your StackOverflow post, for the code:
```ruby
a = Account.where('free_days > 1') # False, No ordering
a.first # False, no ordering, record simply returned by @records[index]
```

Are you saying that with the same data/tables, in different runs of this snippet, `a.first` can return different records and not the Account record with the lowest id # that has `> 1 free days`? And this is because of the following in the `find_nth` method?

```ruby
if loaded?
    @records[index]
```

`@records` are the records returned from Postgres which are returned in a non-deterministic fashion?

Just trying to get a full handle on the issue to understand what needs to be done, thanks!

**Comment by ziomio** [comment]
@RochesterinNYC 

>Are you saying that with the same data/tables, in different runs of this snippet, a.first can return different records and not the Account record with the lowest id # that has > 1 free days?
Yes

>And this is because of the following in the find_nth method?
I believe so

>@records are the records returned from Postgres which are returned in a non-deterministic fashion?
Yes

The main problem for me (and other non super experienced Rails devs) is 'incorrect' behaviour of `first` and `last` methods applied to `where` method. I assumed that `where(CONDITION).first` will always return first record with LOWEST id and I built my app relying on this *wrong* assumption. 

Now, when I know how `first` really behaves - it's a no problem for me anymore - I will just always use `where(CONDITION).order(ORDER)` form of statement but I strongly believe that many other devs do not know about NEED to apply `order` and assume that even for simple `where(CONDITION)` records are sorted by ID...
