### ISSUE TITLE
Race condition saving belongs_to records in 4.2

### ISSUE THREAD

**Issue by mohamedhafez** [rails/rails#22431]
Let's say we have a normal has_many belongs_to relationship:

```ruby
class Papa < ActiveRecord::Base
	has_many :kids
end

class Kid < ActiveRecord::Base
	belongs_to :papa
end
```

If we `update` a `Papa` instance, and then take each of its `kids` in a separate thread to do some processing on them and then try to `save` them: 

```ruby
papa = Papa.first
papa.update first_name: "Bob"

threads = []
papa.kids.each {|kid|
	threads << Thread.new {
		#Do some processing
		kid.save!
	}
}

threads.each {|t| t.join}
```

when `kid.save!` gets called from the different threads, they'll each end up calling the same `papa` instance's `clear_transaction_record_state` method [(activerecord-4.2.5/lib/active_record/transactions.rb:380)](https://github.com/rails/rails/blob/4-2-stable/activerecord/lib/active_record/transactions.rb#L380), and we'll get a race condition trying to clear `papa`'s `@_start_transaction_state`, and we'll eventually get `NoMethodError: undefined method '<' for nil:NilClass` errors at [line 382](https://github.com/rails/rails/blob/4-2-stable/activerecord/lib/active_record/transactions.rb#L382), since all the `kids` will be trying to call `clear_transaction_record_state` on `papa` simultaneously. 

This was not the case in Rails 4.1 or previous, since in those versions, after the `papa.update` call, `papa`'s `@transaction_record` instance variable gets set to nil, and `kid.save!` would never have to call `clear_transaction_record_state` in the first place. However in 4.2 `@transaction_record` doesn't get cleared after `papa.update`, leading to this race condition.

(FWIW I do this all the time in my app and I'm encountering the race condition in production, and its keeping me from updating to 4.2:)

**Comment by al2o3cr** [comment]
Is sharing AR objects across threads like this actually supported, or has it just worked by accident in the past?

The quick workaround would be to iterate over `kid_ids` and hydrate the individual `Kid` objects inside the threads that use them. There's a slight overhead with that, but presumably the `# Do some processing` step is somewhat long-running or threads wouldn't be helpful.

**Comment by sgrif** [comment]
Sharing AR objects across threads is definitely not supported.

**Comment by mohamedhafez** [comment]
so just to clarify, i'm taking each `kid` AR object and handling it *individually* in a separate thread, and they don't reference the object they `belong_to` at all, except for perhaps reading values. If Rails is serious about supporting multi-threading, I'd imagine this would be a fairly common pattern... and unless there is some reason why an AR object's `@transaction_record` can't be cleared after an `update

**Comment by mohamedhafez** [comment]
Reading an AR object across threads should be supported, correct? 

I guess what I'm saying is this is a situation where you would reasonably expect that you would only be reading from the shared parent AR object, and that indeed has been before 4.2

**Comment by sgrif** [comment]
No, sharing an AR object across threads is not supported, as the connection
is not thread safe.

**Comment by mohamedhafez** [comment]
Each thread ends up checking out its own connection to perform the `save!` though. I'm just talking about reading attribute values from an already-loaded AR object.

**Comment by thedarkone** [comment]
@mohamedhafez I get what you are saying, but the problem stems not from your `kids` AR objects, but from the `papa` instance. As you point out, you end up calling `papa.clear_transaction_record_state`, this is clearly not a read-only method.

Furthermore I have to say, as @sgrif pointed out, even pure read-only concurrent usage of AR records is not supported by Rails. What may seem like a "just" normal attribute read, might involve a state change in that AR instance. For example some data structures/caches might be lazily initialized, serialized values de-serialized on demand etc. (PS: I know that this, unfortunately, makes your described use case almost impossible.)

**Comment by mohamedhafez** [comment]
@thedarkone ah i see, thanks for the explanation, I appreciate it. guess there's no avoiding it I'll just get down to refactoring then:)
