### ISSUE TITLE
add_index falsely quoting expressions/functions of columns

### ISSUE THREAD

**Issue by maia** [rails/rails#22430]
Rails (up to 4.2.5) using Postgres (9.4) wraps quotes around passed columns, therefor breaking attempts to create an index on an expression / function. E.g.
```ruby
add_index :orders, "cast(created_at AT TIME ZONE 'UTC' AS time)", name: "index_test"
```
will create the following SQL:
```SQL
CREATE INDEX "index_test" ON "orders" ("cast(created_at AT TIME ZONE 'UTC' AS time)")
```
instead of 
```SQL
CREATE INDEX "index_test" ON "orders" (cast(created_at AT TIME ZONE 'UTC' AS time))
```
which will lead to an error during migration:
```
PG::UndefinedColumn: ERROR:  column "cast(created_at AT TIME ZONE 'UTC' AS time)" does not exist
```
As a use case, I was interested in comparing the total of orders in the past hour to the same time interval of previous weeks/months. I obviously could add another column to the db casting the datetime created_at to time, but it feels wrong to add a column for something that can easily be computed by the database from an existing column. Also, there are a lot of expressions/functions that might have their specific use cases and should not be broken by the safeguards that always try to quote the columns.

**Comment by al2o3cr** [comment]
AFAIK `add_index` doesn't support this at present - implementation discussion in #13684.

You can use `ActiveRecord::Base.connection.execute` as a workaround, but you will also need to switch the schema dumper to SQL mode since the Ruby schema dumper can't represent those indexes correctly.

**Comment by sgrif** [comment]
This looks like it's more of a feature request than a bug. We don't accept feature requests on the issues tracker. Feel free to ask around the Rails core mailing list.
