### ISSUE TITLE
UTC-12:00 and UTC+14:00 are missing from ActiveSupport::TimeZone

### ISSUE THREAD

**Issue by vitorbaptista** [rails/rails#22440]
According to https://en.wikipedia.org/wiki/List_of_UTC_time_offsets, there are the UTC time offsets range from -12:00 to +14:00. On -12:00, it lists "Baker Island" and "Howland Island", and on +14:00 it lists "Line Islands". Listing the recognized timezones in Rails, we get:

```
irb(main):060:0> ActiveSupport::TimeZone.all.map { |x| ActiveSupport::TimeZone.seconds_to_utc_offset(x.utc_offset) }
=> ["-11:00", "-11:00", "-11:00", "-11:00", "-10:00", "-09:00", "-08:00", "-08:00", "-07:00", "-07:00", "-07:00", "-07:00", "-06:00", "-06:00", "-06:00", "-06:00", "-06:00", "-06:00", "-05:00", "-05:00", "-05:00", "-05:00", "-05:00", "-04:30", "-04:00", "-04:00", "-04:00", "-03:30", "-03:00", "-03:00", "-03:00", "-03:00", "-03:00", "-02:00", "-01:00", "-01:00", "+00:00", "+00:00", "+00:00", "+00:00", "+00:00", "+00:00", "+00:00", "+01:00", "+01:00", "+01:00", "+01:00", "+01:00", "+01:00", "+01:00", "+01:00", "+01:00", "+01:00", "+01:00", "+01:00", "+01:00", "+01:00", "+01:00", "+01:00", "+01:00", "+01:00", "+01:00", "+01:00", "+02:00", "+02:00", "+02:00", "+02:00", "+02:00", "+02:00", "+02:00", "+02:00", "+02:00", "+02:00", "+02:00", "+02:00", "+02:00", "+02:00", "+03:00", "+03:00", "+03:00", "+03:00", "+03:00", "+03:00", "+03:00", "+03:00", "+03:30", "+04:00", "+04:00", "+04:00", "+04:00", "+04:00", "+04:00", "+04:30", "+05:00", "+05:00", "+05:00", "+05:00", "+05:30", "+05:30", "+05:30", "+05:30", "+05:30", "+05:45", "+06:00", "+06:00", "+06:00", "+06:00", "+06:00", "+06:30", "+07:00", "+07:00", "+07:00", "+07:00", "+08:00", "+08:00", "+08:00", "+08:00", "+08:00", "+08:00", "+08:00", "+08:00", "+08:00", "+09:00", "+09:00", "+09:00", "+09:00", "+09:00", "+09:30", "+09:30", "+10:00", "+10:00", "+10:00", "+10:00", "+10:00", "+10:00", "+10:00", "+10:00", "+10:00", "+11:00", "+11:00", "+11:00", "+12:00", "+12:00", "+12:00", "+12:00", "+12:00", "+12:45", "+13:00", "+13:00"]
```

This goes from "-11:00" to "+13:00", so the two extremes are missing. If useful, I'd be happy submit a pull request adding them.

**Comment by arthurnn** [comment]
I've saw other PRs updating our list of TZ. But AFAIK this list is frozen.
@pixeltrix @rafaelfranca Thoughts?

**Comment by pixeltrix** [comment]
@vitorbaptista thanks for the offer, but `ActiveSupport::TimeZone::MAPPING` is not meant to be a definitive list of all time zone offsets, just a convenient short list of the major cities, etc.

**Comment by vitorbaptista** [comment]
@pixeltrix Yeah, after @arthurnn's comment, I saw there were some big discussions around adding timezones. I agree with your position on it, but I think this issue is a bit different.

As a user, even if my city isn't in the timezones list, I just need to pick another one in the same timezone. With this issue, though, there's no other city in my timezone, so I'm stuck.

I understand that if a dev needs a complete list of timezones, she should use a gem like [timezone](https://github.com/panthomakos/timezone). However, given that the number of offsets is small (40) and quite stable, it might be valuable to keep it updated in Rails as well.

What do you think?

**Comment by guycall** [comment]
@vitorbaptista I hit the same problem with a production system. We get the UTC offset (in seconds) from a users mobile device. This is then passed to a Rails API endpoint to check and save in a database. 

We get errors because ActiveSupport::TimeZone::MAPPING is missing  perfectly valid (although rare) offsets. I submitted a PR - https://github.com/rails/rails/pull/37811

**Comment by vitorbaptista** [comment]
Hi @guycall, it's been a while since I worked on this PR and I haven't used Rails ever since, so I can't help much :/
