### ISSUE TITLE
MessageEncryptor API can lead to accidental vulnerabilities

### ISSUE THREAD

**Issue by al2o3cr** [rails/rails#22441]
`ActiveSupport::MessageEncryptor` has an API that is easy to get wrong in ways that make an application insecure. I encountered this issue in [this writeup](https://github.com/mastahyeti/the-blog/blob/master/solution.md) from a CTF contest.

The issue is that the _undocumented_ optional second positional argument (`sign_secret`) can be misinterpreted and does not indicate its purpose clearly. For instance, the vulnerable code from the CTF:

``` ruby
ActiveSupport::MessageEncryptor.new(
  Rails.application.config.crypto_key,
  'aes-256-cbc',
  serializer: JSON
)
```

uses a hard-coded `sign_secret` of `'aes-256-cbc'` - more than likely not the intent of the author.

My thought is to improve this API by making `sign_secret` an explicitly named option:

``` ruby
ActiveSupport::MessageEncryptor.new(
  Rails.application.config.crypto_key,
  sign_secret: 'aes-256-cbc',
  serializer: JSON
)
```

IMO, it's much clearer here that an important piece of cryptographic data has been hard-coded.

This would require a deprecation cycle to avoid problems with third-party code that creates `MessageEncryptor` objects with two positional arguments.

I'm working on a PR for this, but wanted to open discussion on it to verify the new approach makes sense.

**Comment by maclover7** [comment]
cc @kaspth

**Comment by kaspth** [comment]
Sounds good to me, switching to keyword arguments would also be good there 👍

I remember @matthewd saying he was the one who added that arg, so he might have more to say.
