### ISSUE TITLE
ActiveRecord#where method produces wrong dates range

### ISSUE THREAD

**Issue by ziomio** [rails/rails#22454]
To fetch records for particular day (e.g. Mon, 30 Nov 2015)  I use the following code which returns a range starting from 00:00:00 to 23:59:59:

    date_to_check = DateTime.now
    # => Mon, 30 Nov 2015 17:14:12 +0200

    date_to_check.beginning_of_day..date_to_check.end_of_day
    # => Mon, 30 Nov 2015 00:00:00 +0200..Mon, 30 Nov 2015 23:59:59 +0200

But when I provide the same range to `where` method it produces SQL with **different** date range (from 2015-11-**29 22:00**:00 to 2015-11-30 **21:59:59**). As a result – `where` fetches  records from *previous day* and did not fetch records from current day after 22:00...

    DailyDiagramsLog.where(day: date_to_check.beginning_of_day..date_to_check.end_of_day)
    # => SELECT "daily_diagrams_logs".* 
         FROM "daily_diagrams_logs" 
         WHERE ("daily_diagrams_logs"."day" 
         BETWEEN '2015-11-29 22:00:00.000000' AND '2015-11-30 21:59:59.000000')

**DailyDiagramsLog model**:

    #  day                   :date
    class DailyDiagramsLog < ActiveRecord::Base; end

**Comment by sgrif** [comment]
You are passing us datetimes in your local time zone, they are being converted to utc. Use utc times if you don't want conversion.
