### ISSUE TITLE
hidden guides?

### ISSUE THREAD

**Issue by masciugo** [rails/rails#22465]
There are some guides like [this](http://edgeguides.rubyonrails.org/engines.html) that are not visible in the index popup menu and some other that are not even visible in the guides home page like [this](http://guides.rubyonrails.org/rails_application_templates.html).

I just wonder if it has anything to do with their reliability

**Comment by rafaelfranca** [comment]
Work in progress guides like the first one are not visible in the navigation. Others guides that need a full review are not included in the guides home page.

Also, please don't ask questions in the issue tracker, use the Rails core mailing list for that.
