### ISSUE TITLE
Failed callbacks

### ISSUE THREAD

**Issue by timmyArch** [rails/rails#22466]
Hiho,

i had a question which is related to AR::Callbacks. 
I was able to register callbacks, but what should a do if a callback fails. I would integrate my workflow transparently. I'd like to call e.g a http api to get required information after_commit.  So could anyone help me in this case. I would like to use the AR::Error's built in error handling as it is in validators. Is there any possibility to do so?

regards 
tim

**Comment by matthewd** [comment]
Please use the mailing list or StackOverflow for questions/help, where a wider community will be able to help you. We reserve the issues tracker for issues only.
