### ISSUE TITLE
number_to_human_size computation error

### ISSUE THREAD

**Issue by majewsky** [rails/rails#22467]
```
$ bundle exec rails console
...
Loading development environment (Rails 4.2.4)
[1] pry(main)> helper.number_to_human_size(1024*1024)
=> "1 MB"
[2] pry(main)> helper.number_to_human_size(1024*1024 - 1)
=> "1020 KB"
```

The second one is off by 4 KB.

**Comment by sgrif** [comment]
[As documented](http://api.rubyonrails.org/classes/ActionView/Helpers/NumberHelper.html#method-i-number_to_human_size), the default precision of `number_to_human_size` is 3. You can pass a `precision` option if you need a higher precision.
