### ISSUE TITLE
#21631 changed the order of the notifications published by @cache.fetch 

### ISSUE THREAD

**Issue by claudiob** [rails/rails#22477]
In Rails 4.2, if you subscribe to the notifications published by an `ActiveSupport::Cache` store and then invoke `.fetch` on a missed key, you see the notifications appearing in this order:

1. cache_read.active_support
1. cache_generate.active_support
1. cache_write.active_support

This sounds like the correct order (read if they key exists, generate a new key because of the miss, write the new key).

However, in master, the order of the notifications has changed. After #21631, the same method above returns the notifications in this order:

1. cache_generate.active_support
1. cache_write.active_support
1. cache_read.active_support

I believe this is a bug, caused by [this line of code](https://github.com/RobinClowers/rails/commit/edd33c08d98723ae9bb89cf7f019277117ed6414#diff-438394335b9c1ce6ec4f67a407f50a42R280) that wraps the entire `fetch` inside `instrument(:read)`, therefore causing the `cache_read.active_support` notifications to be published last.

I have created a [Gist to reproduce the error](https://gist.github.com/claudiob/37079cf529f80008d022) with a test that passes on Rails 4.2 and that fails on master (or on any commit after edd33c08d987).

Please let me know if you consider this a bug or not, because at least [one third-party cache store](https://github.com/redis-store/redis-activesupport/blob/master/test/active_support/cache/redis_store_test.rb#L343-L358) expects the notifications to appear in the original order.

**Comment by claudiob** [comment]
cc/ the original author/merger of #21631 : @jeremy and @RobinClowers

**Comment by RobinClowers** [comment]
@claudiob Looks like you are right, I'll look into a fix.

**Comment by claudiob** [comment]
@RobinClowers Thanks!! :ribbon:

**Comment by RobinClowers** [comment]
@claudiob I submitted a fix, but as an aside, I wasn't able to get your failing test to run? I get this error about rails not being checked out:

```
/Users/robin/.rvm/gems/ruby-2.2.3@global/gems/bundler-1.10.6/lib/bundler/source/git/git_proxy.rb:155:in `allowed_in_path': The git source git://github.com/rails/rails.git is not yet checked out. Please run `bundle install` before trying to start your application (Bundler::GitError)
```

**Comment by claudiob** [comment]
@RobinClowers mmmh… it works for me… can you try running `ruby -e "$(curl -fsSL http://git.io/vRYIj)"` and printing your output? This is what I see.

```sh
$ ruby -v

ruby 2.2.3p173 (2015-08-18 revision 51636) [x86_64-darwin14]

$ ruby -e "$(curl -fsSL http://git.io/vRYIj)"

Updating git://github.com/rails/rails.git
Updating git://github.com/rails/arel.git
Updating git://github.com/rack/rack.git
Updating git://github.com/rails/sprockets.git
Updating git://github.com/rails/sprockets-rails.git
Updating git://github.com/rails/sass-rails.git
Fetching gem metadata from https://rubygems.org/...........
Fetching version metadata from https://rubygems.org/...
Fetching dependency metadata from https://rubygems.org/..
Resolving dependencies...
Using rake 10.4.2
Using concurrent-ruby 1.0.0
Using i18n 0.7.0
Using json 1.8.3
Using method_source 0.8.2
Using minitest 5.8.3
Using thread_safe 0.3.5
Using tzinfo 1.2.2
Using activesupport 5.0.0.alpha from git://github.com/rails/rails.git (at master)
Using builder 3.2.2
Using erubis 2.7.0
Using mini_portile2 2.0.0
Using nokogiri 1.6.7
Using rails-deprecated_sanitizer 1.0.3
Using rails-dom-testing 1.0.7
Using loofah 2.0.3
Using rails-html-sanitizer 1.0.2
Using actionview 5.0.0.alpha from git://github.com/rails/rails.git (at master)
Using rack 2.0.0.alpha from git://github.com/rack/rack.git (at master)
Using rack-test 0.6.3
Using actionpack 5.0.0.alpha from git://github.com/rails/rails.git (at master)
Using globalid 0.3.6
Using activejob 5.0.0.alpha from git://github.com/rails/rails.git (at master)
Using mime-types 2.99
Using mail 2.6.3
Using actionmailer 5.0.0.alpha from git://github.com/rails/rails.git (at master)
Using activemodel 5.0.0.alpha from git://github.com/rails/rails.git (at master)
Using arel 7.0.0.alpha from git://github.com/rails/arel.git (at master)
Using activerecord 5.0.0.alpha from git://github.com/rails/rails.git (at master)
Using bundler 1.10.6
Using thor 0.19.1
Using railties 5.0.0.alpha from git://github.com/rails/rails.git (at master)
Using sprockets 4.0.0 from git://github.com/rails/sprockets.git (at master)
Using sprockets-rails 3.0.0.beta3 from git://github.com/rails/sprockets-rails.git (at master)
Using rails 5.0.0.alpha from git://github.com/rails/rails.git (at master)
Using sass 3.4.19
Using sass-rails 6.0.0 from git://github.com/rails/sass-rails.git (at master)
Run options: --seed 17114

# Running:

F

Finished in 0.024935s, 40.1039 runs/s, 40.1039 assertions/s.

  1) Failure:
CacheNotificationOrderTest#test_that_works_on_rails42_and_fails_on_master [-e:38]:
--- expected
+++ actual
@@ -1 +1 @@
-"cache_generate.active_support"
+"cache_read.active_support"


1 runs, 1 assertions, 1 failures, 0 errors, 0 skips
```

**Comment by RobinClowers** [comment]
Turns out I had a corrupted install of the gem due to flakey internet, it works in a new gemset. Thanks!
