### ISSUE TITLE
HasOneAssociation `build` nullifies existing association.

### ISSUE THREAD

**Issue by stephenprater** [rails/rails#22474]
Given the following setup:

```
class Car < ActiveRecord::Base
  has_one :engine
end

class Engine < ActiveRecord::Base
  belongs_to :car
end
```

If there is a Engine -> Car relation, then calling `car.build_engine` actually modifies the **Engine** record by nullifying it's `car_id` column.   This happens [here](https://github.com/rails/rails/blob/master/activerecord/lib/active_record/associations/has_one_association.rb#L39)

This seems like a behavior that differs from the normal behavior of `___Association#build` - which is generally to not modify the database.  Am I missing something, or is this surprising behavior?

**Comment by denniss** [comment]
Are you saying that there is already an `engine` record persisted before calling `car.build_engine`?

**Comment by stephenprater** [comment]
Yes.

**Comment by rafaelfranca** [comment]
Could you create a reproduction script with this template https://github.com/rails/rails/blob/master/guides/bug_report_templates/active_record_master.rb?

**Comment by jaredhoyt** [comment]
@rafaelfranca @stephenprater Here is a reproduction script based on the Car/Engine example:

https://gist.github.com/jaredhoyt/c774c051ca425178f308

**Comment by denniss** [comment]
I may be repeating what's already been said here. So it looks like the current behavior **creates** a new engine and orphans the old engine record.

`assert_equal car.engine, engine  #Fails`

```
BugTest#test_build_association [test/cases/22474_test.rb:36]:
Expected: #<Engine id: nil, car_id: 1>
  Actual: #<Engine id: 1, car_id: nil>

1 runs, 2 assertions, 1 failures, 0 errors, 0 skips
```

I am guessing that `build_engine` should not persist to according to the documentation of has one build association
```
Returns a new object of the associated type that has been instantiated with attributes and linked to this object through a foreign key, but has not yet been saved.
```

**Comment by stephenprater** [comment]
No, that's pretty much it.  The problem as I see it is not that the new engine should be saved, or that I should have two engines on the car - it's that there is no way to get the old engine _back_.  So if I build a new Engine - and then the engine is invalid, or can't be persisted for some reason, the old engine can't be re-associated to the car.  It doesn't even happen in a transaction you can roll back, because the call to `build_engine` finishes successfully.

The database state shouldn't change I don't think, no - but it **definitely** should not put the association in an unrecoverable state.

**Comment by the-undefined** [comment]
Hi!

It doesn’t seem right to update the database when only calling build_* methods I agree. I’ve dived into the active record code to see why this behavior is happening and have a potential patch.

Within the `SingularAssociation` class is the build method that calls `set_new_record(record)`:

```
[32, 41] in /vagrant/rails/activerecord/lib/active_record/associations/singular_association.rb
   32:       end
   33:
   34:       def build(attributes = {})
   35:         record = build_record(attributes)
   36:         yield(record) if block_given?
=> 37:         set_new_record(record)
   38:         record
   39:       end
```

This in turn calls `replace` but importantly with the argument `false`, to signify *not* to save the record to the database:

```
   80:         def set_new_record(record)
=> 81:           replace(record, false)
   82:         end
```

However inside of the `replace` method rails assertions that the _built_ record does not match the existing association:

```
[33, 42] in /vagrant/rails/activerecord/lib/active_record/associations/has_one_association.rb
   33:         load_target
   34:
=> 35:         return self.target if !(target || record)
   36:
   37:         assigning_another_record = target != record
=> 38:         if assigning_another_record || record.changed?
   39:           save &&= owner.persisted?
   40:
   41:           transaction_if(save) do
   42:             remove_target!(options[:dependent]) if target && !target.destroyed? && assigning_another_record
(byebug) target
#<Engine id: 1, car_id: 1>
(byebug) record
#<Engine id: nil, car_id: 1>
(byebug) assigning_another_record
true
```

So it then proceeds to commit the `nil` association to the database, ignoring the *save* argument even though it was set to `false`.

```
[36, 45] in /vagrant/rails/activerecord/lib/active_record/associations/has_one_association.rb
   36:
   37:         assigning_another_record = target != record
   38:         if assigning_another_record || record.changed?
   39:           save &&= owner.persisted?
   40:
=> 41:           transaction_if(save) do
   42:             remove_target!(options[:dependent]) if target && !target.destroyed? && assigning_another_record
   43:
   44:             if record
   45:               set_owner_attributes(record)
(byebug) p save
false
```
(`transaction_if` will commit to the database whether `save` is set to `true` or `false` at this point).

The potential patch is to return the `record` if `save` is set to `false`:

```
[31, 40] in /vagrant/rails/activerecord/lib/active_record/associations/has_one_association.rb
   31:       def replace(record, save = true)
   32:         raise_on_type_mismatch!(record) if record
   33:         load_target
   34:
   35:         return self.target if !(target || record)
=> 36:         return record unless save
   37:
   38:         assigning_another_record = target != record
   39:         if assigning_another_record || record.changed?
   40:           save &&= owner.persisted?
(byebug) record
#<Engine id: nil, car_id: 1>
```

And then we have a passing test wahoo(!), but I don’t know what else this might break in rails. I'll put a PR together to start a conversation around a fix for this. Good find @stephenprater!

**Comment by denniss** [comment]
What should the value of `car.engine` be AFTER calling `car.build_engine` when the newly built engine is invalid? Should it be the instance of the old engine or the newly invalid engine?

It sounds to me that we need a new method.... something like `previous_engine`?

**Comment by stephenprater** [comment]
I think `car.engine` would be the new instance as long as you're talking to the same `car` instance.  So:

```
car.engine #=> #<Engine id: 1, car_id: 1>
car.build_engine #=> #<Engine id: nil, car_id: 1>
car.engine #=> #<Engine id:nil, car_id: 1>

Car.find(1).engine #=> #<Engine id:1, car_id:1>
```

So if `car.engine` is not valid at some point, I would just not call `car.save` and then on reload `car.engine` would still be the old engine.

**Comment by StefanoOrdine** [comment]
If `car.save` fails because of associated `engine` is not valid, you should still still be able to retrieve the previous stored `engine` by doing:
```
car.reload
car.engine
```
Isn't it?

**Comment by jaredhoyt** [comment]
@StefanoOrdine No, because `car.build_engine` actually updates the associated record in the database and sets the foreign_key field to `null` so the records are no longer associated in the db.

**Comment by StefanoOrdine** [comment]
Right! so you @jaredhoyt and @stephenprater are proposing to modify #build_association in order to take into account the association that was previously bound with the model that is going to be saved?
+1 for this solution
>So if car.engine is not valid at some point, I would just not call car.save and then on reload car.engine would still be the old engine.
