### ISSUE TITLE
ActiveRecord (rails 4.2.5) no superclass method 'attribute=' when called from inherited class.

### ISSUE THREAD

**Issue by cmrd-senya** [rails/rails#22489]
Hi!
I was trying to patch AR attributes call in order to do some read/write logging. I faced a problem that for some objects, when attribute= gets called it raises "no superclass method". It happes when object is not a direct child of ActiveRecord::Base, but has an intermediate parent, which in its turn is the direct child of ActiveRecord::Base.

I discovered similar issues that were closed in 4.2.1: #18339 #18986

I picked a testcase from #18986 and modified it according to my case.

Here is a resulting testcase: https://gist.github.com/cmrd-senya/1db9e1829ec030349280

Here, ```test_first_or_create```, a case of direct inheriting, passes and ```test_first_or_create2```, a case of indirect inheriting fails.

I'm not sure if it is a bug or just my misuse of Rails and Ruby so I need some assistance.

**Comment by cmrd-senya** [comment]
[Here](https://gist.github.com/cmrd-senya/ccf73c1891845ef213f1) is the testcase output.

**Comment by matthewd** [comment]
`abstract_class` means `Parent` doesn't have any columns (and thus attribute methods). This sounds like expected behaviour to me.

**Comment by cmrd-senya** [comment]
But ```Person``` should have columns, shouldn't it?

**Comment by cmrd-senya** [comment]
Can't you please then advice how should I write it so ```email=``` works for ```Person```?

**Comment by matthewd** [comment]
You can't override a subclass's method from its superclass.

Please use the mailing list or StackOverflow for further questions/help, where a wider community will be able to help you. We reserve the issues tracker for issues only.
