### ISSUE TITLE
Mysql as method, and group

### ISSUE THREAD

**Issue by tilhoft** [rails/rails#22484]
This query string :

data = Outlay.select("DATE_FORMAT(date, '%Y-%m-01') as month, sum(amount) as am_sum").group(:month).inspect

runs this in mysql:

SELECT DATE_FORMAT(date, '%Y-%m-01') as month, sum(amount) as am_sum FROM `outlays` GROUP BY month;
which is good and returns this: (if i run directly on mysql console)

+------------+--------+
| month      | am_sum |
+------------+--------+
| 2015-11-01 |     46 |
| 2015-12-01 |     26 |
+------------+--------+

but when i inspect the data variable i get this:
ActiveRecord::Relation [Outlay id: nil, Outlay id: nil]

**Comment by rafaelfranca** [comment]
Could you create a reproduction script with this template https://github.com/rails/rails/blob/master/guides/bug_report_templates/active_record_master.rb?

**Comment by tilhoft** [comment]
here it is :) this was the simpliest way to attach sorry for the docx format :)
[issue22484.docx](https://github.com/rails/rails/files/50986/issue22484.docx)

**Comment by rafaelfranca** [comment]
Can you upload it to a gist? https://gist.github.com/

I don't have a program to open docx documents.

**Comment by tilhoft** [comment]
https://gist.github.com/tilhoft/f2abb29bee76214a119c

**Comment by denniss** [comment]
@tilhoft Can you make your test fail (i.e. add some assertions)?

Here's an example of a failing test: 
https://gist.github.com/jaredhoyt/c774c051ca425178f308

**Comment by nwjsmith** [comment]
@tilhoft as you can see in [this passing test][1], although calling `#inspect` on the relation will not show the value of `as_sum` or `month`, calling those methods will return the correct values.

[1]: https://gist.github.com/nwjsmith/96a7452be17b4d7712f8

**Comment by tilhoft** [comment]
Hi Nate! Jeah i figured it out. Sorry that i not wrote the test, but i haven't got much time recently, thanks for the support!

----- Eredeti üzenet -----
Feladó: "Nate Smith" <notifications@github.com>
Feladva: ‎2015.‎12.‎15. 18:17
Címzett: "rails/rails" <rails@noreply.github.com>
Másolat: "Tobias Tilhof" <tobias.tilhof@p92.hu>
Tárgy: Re: [rails] Mysql as method, and group (#22484)

@tilhoft as you can see in this passing test, although calling #inspect on the relation will not show the value of as_sum or month, calling those methods will return the correct values.

**Comment by nwjsmith** [comment]
@rafaelfranca this can be closed
