### ISSUE TITLE
has_one with dependent nullify fails destruction with an inverse relation specifying dependent destroy

### ISSUE THREAD

**Issue by maletor** [rails/rails#22498]
Rails tries to set the column as `NULL` too late in the sequence of events for a destruction.

``` ruby
class Account
  has_one :user, dependent: :nullify
end

class User
  belongs_to :account, dependent: :destroy
end

User.joins(:account).first.destroy # ActiveRecordError: cannot update a destroyed record
```

ActiveRecord is trying to set the user's attributes with `{ account_id: nil }`. [ActiveRecord::Persistence](https://github.com/rails/rails/blob/v4.2.5/activerecord/lib/active_record/persistence.rb#L293) contains the offending code.

I'm curious what you think the right course is to take with this.

**Comment by sgrif** [comment]
You can certainly shoot yourself in the foot with circular `dependent` chains if you want to, but it is not a bug.

**Comment by maletor** [comment]
It's a change in behavior from 4.1 to 4.2. If you don't think it's an issue, I can somewhat work around it with a different approach.

```ruby
after_destroy { user.update_columns(account_id: nil) unless user.destroyed? }
```
Ideally, this is sorted out by the framework though as a "convention".

**Comment by sgrif** [comment]
Please provide an executable test case which demonstrates the issue, using our standard bug report template. https://github.com/rails/rails/blob/master/guides/bug_report_templates/active_record_gem.rb

**Comment by maletor** [comment]
@sgrif, [I posted a failing test case](https://gist.github.com/maletor/f07dd9a04b15028c5d8f).

**Comment by lsylvester** [comment]
I think that this has been fixed in 19b168e611fb8fb547981c4535130c29856efd3a. Do you still get this issue if running against edge rails?

**Comment by maletor** [comment]
Any chance we can see that backported to `4-2-stable`?

**Comment by maletor** [comment]
@lsylvester you're right. That is the fix.
