### ISSUE TITLE
Join + Select + Group = error when trying to count rows..

### ISSUE THREAD

**Issue by dyatlov** [rails/rails#22491]
Given this statement:

```ruby
@items = DailyList.joins(:bar).select("daily_lists.*, (point(12, 34) <@> bars.coords) as bar_distance").order("bar_distance ASC").group('bars.id, daily_lists.id').limit(3)
```

it produces the following SQL:

```sql
SELECT  daily_lists.*, (point(12, 34) <@> bars.coords) bar_distance
FROM "daily_lists"
INNER JOIN "bars" ON "bars"."id" = "daily_lists"."bar_id"
GROUP BY bars.id, daily_lists.id 
ORDER BY bar_distance ASC
LIMIT 3
```

Now we want to check how much records we've got, `@items.count`:

```sql
SELECT  COUNT(daily_lists.*, (point(12, 34) <@> bars.coords) as bar_distance) AS count_daily_lists_all_point_12_34_bars_coords_as_bar_distance, bars.id, daily_lists.id AS bars_id_daily_lists_id
FROM "daily_lists"
INNER JOIN "bars" ON "bars"."id" = "daily_lists"."bar_id"
GROUP BY bars.id, daily_lists.id 
ORDER BY bar_distance ASC
LIMIT 3
```

```
ActiveRecord::StatementInvalid: PG::SyntaxError: ERROR:  syntax error at or near "as"
LINE 1: ...NT(daily_lists.*, (point(12, 34) <@> bars.coords) as bar_dis...
```

Now I'm trying to use `:all`  as a workaround, `@items.count(:all)`:

```sql
SELECT  COUNT(*) AS count_all, bars.id, daily_lists.id AS bars_id_daily_lists_id
FROM "daily_lists"
INNER JOIN "bars" ON "bars"."id" = "daily_lists"."bar_id"
GROUP BY bars.id, daily_lists.id 
ORDER BY bar_distance ASC
LIMIT 3
```

```
PG::UndefinedColumn: ERROR:  column "bar_distance" does not exist
```

Guys... what to do?

**Comment by rafaelfranca** [comment]
Please use the mailing list or StackOverflow for questions/help, where a wider community will be able to help you. We reserve the issues tracker for issues only.

**Comment by dyatlov** [comment]
@rafaelfranca are you crazy maan?
it's clearly an issue with rails activerecord

**Comment by rafaelfranca** [comment]
> @rafaelfranca are you crazy maan?

No I'm not. It is not an issue with Rails Active Record and I could answer why, but since you asked in that way I'll not, sorry.

**Comment by dyatlov** [comment]
@rafaelfranca you definitely crazy

**Comment by jeremy** [comment]
Crazy like a fox

**Comment by StanisLove** [comment]
> > @rafaelfranca are you crazy maan?
> 
> No I'm not. It is not an issue with Rails Active Record and I could answer why, but since you asked in that way I'll not, sorry.

And why?
