### ISSUE TITLE
Deprecate ActionController::TestCase in favor of ActionDispatch::IntegrationTest

### ISSUE THREAD

**Issue by dhh** [rails/rails#22496]
With the speed increase we achieved for ActionDispatch::IntegrationTest in Rails 5, there's no longer a need to also have ActionController::TestCase around. We're changing the scaffolds in #22076 but we should also get the message out that ActionController::TestCase is deprecated and will be made into a gem from Rails 5.1.

**Comment by rishav** [comment]
@dhh, is there going to be no further development on ActionController::TestCase or until it becomes a gem ?

**Comment by dhh** [comment]
No intention of doing anything further with ActionController::TestCase.
It's been superseeded by the speed-ups in integration tests.

**Comment by eileencodes** [comment]
Fixed in 4414c5d - let me know if I missed anything :smile:

**Comment by fguillen** [comment]
I had a nasty non-thread-safe problem in my app because I was using `ActionController::TestCase`:

- https://stackoverflow.com/questions/78465423/activerecordstatementinvalid-mysql2error-this-connection-is-in-use-by-f/78465424#78465424
