### ISSUE TITLE
Appending multiple line numbers to run multiple tests

### ISSUE THREAD

**Issue by sivagollapalli** [rails/rails#22501]
In `rspec` we can run multiple specs as `rspec spe/models/user_spec.rb:4:8` . So it would run specs defined at line number `4` and `8`. But currently `rails` testing didn't support this feature. Could we add it to rails. Thoughts please?

**Comment by kaspth** [comment]
We don't take feature requests on the issue tracker. We recommend asking on the Rails core mailing list or try to write a pull request yourself. Thanks :heart:
