### ISSUE TITLE
[Meta] Convert Rake tasks to `Rails::Commands::Command`

### ISSUE THREAD

**Issue by maclover7** [rails/rails#22503]
Here is a master list of all Rails (and associated libraries) Rake tasks that will need to be converted to `Rails::Commands::Command` subclasses. This issue should serve as a home base for coordinating work to convert these Rake tasks before v5.0.0 lands. cc @kaspth @ccallebs 

# ActionView
- [actionview/lib/action_view/tasks/dependencies.rake](https://github.com/rails/rails/blob/master/actionview/lib/action_view/tasks/dependencies.rake)
  - `rake cache_digests:nested_dependencies`
  - `rake cache_digests:dependencies`

# ActiveRecord
- [activerecord/lib/active_record/railties/databases.rake](https://github.com/rails/rails/blob/master/activerecord/lib/active_record/railties/databases.rake)
  - `rake db:load_config`
  - `rake db:create`
  - `rake db:create:all`
  - `rake db:drop`
  - `rake db:drop:all`
  - `rake db:purge`
  - `rake db:purge:all`
  - `rake db:migrate`
  - `rake db:migrate:redo`
  - `rake db:migrate:reset`
  - `rake db:migrate:up`
  - `rake db:migrate:down`
  - `rake db:migrate:status`
  - `rake db:rollback`
  - `rake db:forward`
  - `rake db:reset`
  - `rake db:charset`
  - `rake db:collation`
  - `rake db:version`
  - `rake db:abort_if_pending_migrations`
  - `rake db:setup`
  - `rake db:seed`
  - `rake db:fixtures:load`
  - `rake db:fixtures:identify`
  - `rake db:schema:dump`
  - `rake db:schema:load`
  - `rake db:schema:load_if_ruby`
  - `rake db:cache:dump`
  - `rake db:cache:clear`
  - `rake db:structure:dump`
  - `rake db:structure:load`
  - `rake db:structure:load_if_sql`
  - `rake db:test:load`
  - `rake db:test:load_schema`
  - `rake db:test:load_structure`
  - `rake db:test:clone`
  - `rake db:test:clone_schema`
  - `rake db:test:clone_structure`
  - `rake db:test:purge`
  - `rake db:test:prepare`
  - `rake db:railties:install:migrations`

# Railties

- [railties/lib/rails/tasks/annotations.rake](https://github.com/rails/rails/blob/master/railties/lib/rails/tasks/annotations.rake)
  - `rake notes`
  - `rake notes:custom`
  - `rake notes:fixme`
  - `rake notes:optimize`
  - `rake notes:todo`
- [railties/lib/rails/tasks/engine.rake](https://github.com/rails/rails/blob/master/railties/lib/rails/tasks/engine.rake)
- [railties/lib/rails/tasks/framework.rake](https://github.com/rails/rails/blob/master/railties/lib/rails/tasks/framework.rake)
- [railties/lib/rails/tasks/initializers.rake](https://github.com/rails/rails/blob/master/railties/lib/rails/tasks/initializers.rake)
  - `rake initializers`
- [railties/lib/rails/tasks/log.rake](https://github.com/rails/rails/blob/master/railties/lib/rails/tasks/log.rake)
  - `rake log:clear`
- [railties/lib/rails/tasks/middleware.rake](https://github.com/rails/rails/blob/master/railties/lib/rails/tasks/middleware.rake)
  - `rake middleware`
- [railties/lib/rails/tasks/misc.rake](https://github.com/rails/rails/blob/master/railties/lib/rails/tasks/misc.rake)
  - `rake secret`
  - `rake about`
  - `rake time:zones`
  - `rake time:us`
  - `rake time:local`
- [railties/lib/rails/tasks/restart.rake](https://github.com/rails/rails/blob/master/railties/lib/rails/tasks/restart.rake)
  - `rake restart`
- [railties/lib/rails/tasks/routes.rake](https://github.com/rails/rails/blob/master/railties/lib/rails/tasks/routes.rake)
  - `rake routes`
- [railties/lib/rails/tasks/statistics.rake](https://github.com/rails/rails/blob/master/railties/lib/rails/tasks/statistics.rake) 
  - `rake stats`
- [railties/lib/rails/tasks/tmp.rake](https://github.com/rails/rails/blob/master/railties/lib/rails/tasks/tmp.rake)
  - `rake tmp:clear`
  - `rake tmp:create`
  - `rake tmp:cache:clear`
  - `rake tmp:sockets:clear`
  - `rake tmp:pids:clear`

**Comment by RochesterinNYC** [comment]
If we want to help contribute in converting some of these to the appropriate rails commands, what's the procedure/coordination game plan?

**Comment by kaspth** [comment]
Don't think this is the exact road map we're looking for. A 1-1 mapping like this is a lot of churn and costly, especially when this is one of the things blocking Rails from going into beta.

I'd rather we prioritized converting a task to a command like this:

1. Already run with `rails`.
2. Uses ENV variables as parameters.

Then, for quicker complete coverage, the tasks that have dependencies or hooks we still delegate to Rake, but make runnable through `bin/rails`.

As for the library split, I think we're be better off letting Active Record just being funneled through `bin/rails` and then focusing our energy on Active Support and Railties.

**Comment by ccallebs** [comment]
@kaspth In that case, should I add back the `rake_delegate` command and create a separate class with all of those delegations? Having all the rake delegations in one place would prevent the kind of churn we saw in the last attempt.

**Comment by kaspth** [comment]
@ccallebs let's hold off on that a bit, I'd like to explore alternatives to the `rake_delegate` attempt first.

My thinking is we can avoid adding that method altogether, if we, attempt to run a rails command, then if there is none, a) load the Rake environment, and b) run `Rake::Task[task_name].invoke`.

Feel free to take a stab at that, or come up with a better solution :smile:

**Comment by maclover7** [comment]
I understand why it would be better to not do a big bang conversion at once, but as you mentioned, Rails 5.0 will be landing soon. This also means that the window to get done this Rake --> Thor CLI conversion project only has a small amount of time to get done -- if the conversion doesn't happen before 5.0, then it can't happen before 6.0, because that's a SemVer breaking change (big no-no). That's my only reason for thinking we should just bang these out now.

**Comment by kaspth** [comment]
Rails follows a shifted SemVer structure, so 5.1 is just as fine :grin:

Besides I don't want to break backwards compatibility here in any way. The tasks you were able to run with Rake in 4.2, should still be able to run with Rake in 5.0 — albeit with a deprecation warning.

By the way `rake dev:cache` has never been in a public release, so it doesn't have to be able to be run with `rake`. Same goes for `rake restart`.

> we should just bang these out now

And who on the Rails team has to maintain those banged out commands? :wink:

**Comment by maclover7** [comment]
So the plan is to port everything over to the main Rails CLI, but leave intact the Rake tasks in place with a deprecation notice? And then on 5.1 remove deprecation notices + Rake tasks in favor of just the main Rails CLI?

**Comment by kaspth** [comment]
> port everything over to the main Rails CLI

Well, by priority. The more complex ones to port, I'd be more inclined to just wrap, so they can be run with `bin/rails`.

The goal here is to make the interface nicer, even if we use rake to run tasks internally. You can check out more of the impetus here: https://github.com/rails/rails/issues/18878

**Comment by kaspth** [comment]
This was more complex than we realized at first. We're backing off a bit and regrouping later. Thanks, Jon!
