### ISSUE TITLE
The klass ivar can be nil in active_record/table_metadata.rb

### ISSUE THREAD

**Issue by jhaungs** [rails/rails#22507]
I don't know much about the semantics of klass being nil in this code, but this fix made my Rails 4.2.5 code work in Rails 5.

It seems that line 43 should read:

`association = klass && klass._reflect_on_association(table_name)`

Elsewhere in this module (lines 29 & 37), it is assumed that klass can be nil, and on line 54, nil can be passed as `@klass` to the constructor.

**Comment by sgrif** [comment]
Please provide an executable test case that demonstrates the issue, using out standard template. https://github.com/rails/rails/blob/master/guides/bug_report_templates/active_record_master.rb
