### ISSUE TITLE
Left outer join not working

### ISSUE THREAD

**Issue by victorhazbun87** [rails/rails#22528]
Hello,

I have 2 tables: appointments and doors. Door has one appointment and appointment belongs to a door. The appointments table have the door_id.

The query I wrote is:

    scope :not_in_appointments, -> { joins("left outer join appointments on appointments.door_id = doors.id") }

ISSUE: The scope is still returning the doors that are in the appointments table.

GOAL: We want to get doors that are NOT in the appointments table.

The left outer join is suppose to do that. Can someone please let us know why this query is not working?

Thanks.

**Comment by matthewd** [comment]
Please use the mailing list or StackOverflow for questions/help, where a wider community will be able to help you. We reserve the issues tracker for issues only.
