### ISSUE TITLE
ActiveRecord objects destroying themselves immediately after_save

### ISSUE THREAD

**Issue by braindeaf** [rails/rails#22532]
I discovered a problem when upgrading to Rails 4, in particular with a model with a Paperclip attachment. Whereby my Object is created and almost immediately deleted. I wanted to bounce this past a few eyes here.

Paperclip adds a pretty standard after_commit to a Model

      @klass.send(:after_commit, :on => :destroy) { send(name).send(:flush_deletes) }

ActiveRecord transactions appends an if option to the callback

https://github.com/rails/rails/blame/master/activerecord/lib/active_record/transactions.rb

      def set_options_for_callbacks!(args)
        options = args.last
        if options.is_a?(Hash) && options[:on]
          fire_on = Array(options[:on])
          assert_valid_transaction_action(fire_on)
          options[:if] = Array(options[:if])
          options[:if] << "transaction_include_any_action?(#{fire_on})"
        end
      end

options[:if] in this case would be 'transaction_include_any_action?(destroy)', note that 'destroy' is not passed as a string or a symbol to the method here.

Which is subsequently passed to make_lambda as 'filter'.

https://github.com/rails/rails/blob/master/activesupport/lib/active_support/callbacks.rb

    def make_lambda(filter)
        case filter
        when Symbol
          lambda { |target, _, &blk| target.send filter, &blk }
        when String
          l = eval "lambda { |value| #{filter} }"
          lambda { |target, value| target.instance_exec(value, &l) }
        when Conditionals::Value then filter
        when ::Proc
          if filter.arity > 1
            return lambda { |target, _, &block|
              raise ArgumentError unless block
              target.instance_exec(target, block, &filter)
            }
          end

          if filter.arity <= 0
            lambda { |target, _| target.instance_exec(&filter) }
          else
            lambda { |target, _| target.instance_exec(target, &filter) }
          end
        else
          scopes = Array(chain_config[:scope])
          method_to_call = scopes.map{ |s| public_send(s) }.join("_")

          lambda { |target, _, &blk|
            filter.public_send method_to_call, target, &blk
          }
        end
      end

If as we see the filter is evalled as a lambda, and that is then eventually called in within the context of the Model object so...

'transaction_include_any_action?(destroy)'

actually calls 'destroy' when it should in fact be passing ':destroy' to the transaction_include_any_action? method. Not really sure how this should be tackled.

**Comment by braindeaf** [comment]
'transaction_include_any_action?(destroy)'

should actually be

'transaction_include_any_action?([:destroy])'

So this is more about expecting Array#to_s to return the string representation of Array.

    def transaction_include_any_action?(actions) #:nodoc:
      actions.any? do |action|
        case action
        when :create
          transaction_record_state(:new_record)
        when :destroy
          destroyed?
        when :update
          !(transaction_record_state(:new_record) || destroyed?)
        end
      end
    end

I can demonstrate.

    Robs-MBP:rl$ irb
    2.2.2 :001 > options = { on: :destroy }
     => {:on=>:destroy} 
    2.2.2 :003 > fire_on = Array(options[:on])
     => [:destroy] 
    2.2.2 :004 > "transaction_include_any_action?(#{fire_on})"
     => "transaction_include_any_action?([:destroy])" 

    Robs-MBP: rl$ rails c
    Loading development environment (Rails 4.2.5)
    2.2.2 :001 > options = { on: :destroy }
     => {:on=>:destroy} 
    2.2.2 :002 > fire_on = Array(options[:on])
     => [:destroy] 
    2.2.2 :003 >  "transaction_include_any_action?(#{fire_on})"
     => "transaction_include_any_action?(destroy)"

**Comment by rafaelfranca** [comment]
Could you create a reproduction script with this template https://github.com/rails/rails/blob/master/guides/bug_report_templates/active_record_master.rb?

**Comment by braindeaf** [comment]
I will give it a whirl

**Comment by braindeaf** [comment]
Ok, I've given it a whirl and this it worked fine. It appears the issue was ours we'd overridden Array#to_s in order to keep it behaving like 1.8.7. so calling to_s on [:destroy] resulted in sending 'destroy' as an argument which was subsequently called. Sorry for the unnecessary report.
