### ISSUE TITLE
Entry in Mac's hosts file causes server error with no stacktrace

### ISSUE THREAD

**Issue by DaniG2k** [rails/rails#22536]
Hello all,

Not sure this is the right place to put this but I spent a good 40 minutes trying to understand why I was getting an error when accessing my Rails server. There was absolutely no error message or stacktrace which made it even harder to understand what was going on.

Turns out that I magically got the following line in my /etc/hosts file on my Macbook Pro:

`fe80::1%lo0	localhost`

`fe80::1%lo0` is the IPv6 version for `127.0.0.1` which apparently doesn't work nicely with Rails.
Is there an official workaround for this? For now I've just commented the entry out in /etc/hosts.

Thanks!

**Comment by rafaelfranca** [comment]
Please use the mailing list or StackOverflow for questions/help, where a wider community will be able to help you. We reserve the issues tracker for issues only.
