### ISSUE TITLE
Warning: Circular Argument Reference - Now

### ISSUE THREAD

**Issue by jdlam** [rails/rails#22537]
I have a pretty vanilla rails app. No compass as other stackoverflow threads have suggested causes this warning. The circular argument reference warning pops up whenever i run `rails s` to start my rails server.

I found [this topic](https://www.ruby-forum.com/topic/6873211) which has a similar issue, but is caused by a different action. Hopefully someone can help me figure out what is going on with my app...

**Comment by rafaelfranca** [comment]
You need to give us more information on how to reproduce this issue, otherwise there is nothing we can do. Please read CONTRIBUTING.md file for more information about creating bug reports. Thanks!
