### ISSUE TITLE
Activerecord: strange behavior with enum in where() method

### ISSUE THREAD

**Issue by CannyFoxx** [rails/rails#22545]
Hi! I tried to get a array of associated (self HABTM) items and found strange behavior of Activerecord.
I call next code:

    @friends = current_user.friends.where(friends: {:status => :requested})

He created next SQL (postgres) query:

    User Load (0.2ms)  SELECT "users".* FROM "users" INNER JOIN "friends" ON "users"."id" = "friends"."friend_id" WHERE "friends"."user_id" = $1 AND "friends"."status" = NULL  [["user_id", 2]]

You can see, what status set to NULL. Ok, i tried to add enum index manually:

    @friends = current_user.friends.where(friends: {:status => 0})

This work fine:

    SELECT "users".* FROM "users" INNER JOIN "friends" ON "users"."id" = "friends"."friend_id" WHERE "friends"."user_id" = $1 AND "friends"."status" = 0  [["user_id", 2]]

Bug or a feature?

**Comment by rafaelfranca** [comment]
It is how it works. See the last line of the documention. http://api.rubyonrails.org/classes/ActiveRecord/Enum.html
