### ISSUE TITLE
rake log:clear - truncates custom log files from log

### ISSUE THREAD

**Issue by pramodshinde** [rails/rails#22544]
The task `rake log:clear`from [log.rake] (https://github.com/rails/rails/blob/7f18ea14c893cb5c9f04d4fda9661126758332b5/railties/lib/rails/tasks/log.rake) truncates all files from `log/*.log` by default if no EVN['LOGS'] specified, this is very unintentional if there is custom logger file/s like log/custom.log and I run `rake log:clear`, log/custom.log is getting truncated. 

However, I can specify file names by `EVN['LOGS'] = 'test,development'` to truncate specific files but this not handy to specify each environment/s file name to avoid truncation of custom logger files. 

I have adding `EVN['LOGS']=all`, with 'all' argument task will  truncate all files from `log/*.log`
along with this, task will continue take specific names as well. 

if no argument given by default it should truncate only standard environment log files i.e.`'development,test,staging,production' `

Thoughts? will send PR if all looks fine with this [commit](https://github.com/joshsoftware/rails/commit/2adc05fd9c41bee6c2f8e29bc072d953b6e9b3be).

**Comment by iron-man** [comment]
This looks good to me, seems like a much better default than just wiping out all the logs, as I also have custom logs that I don't want cleared.

**Comment by kaspth** [comment]
Fixed @ https://github.com/rails/rails/pull/22703
