### ISSUE TITLE
Rails 4.2/4.2.5 Guide - rails command output from rails console not correct

### ISSUE THREAD

**Issue by atul-shimpi** [rails/rails#22558]
Rails guide http://guides.rubyo nrails.org/initialization.html says below
=======================================================================
1.1 railties/bin/rails
The rails in the command rails server is a ruby executable in your load path. This executable contains the following lines:

version = ">= 0"
load Gem.bin_path('railties', 'rails', version)
If you try out this command in a Rails console, you would see that this loads railties/bin/rails. A part of the file railties/bin/rails.rb has the following code:

require "rails/cli"
=================================================
I tried the rails command in rails console. But it does gives output as shown in the guide.
I am using rvm and rails version is Rails 4.2.4. Instead a long list of errors is shown.

**Comment by rishav** [comment]
Can you change the title ? This is not from the Rails 4.0 guide, thats the Rails 4.2.5 guide.

**Comment by prathamesh-sonpatki** [comment]
It works for me

```
>> version = ">= 0"
=> ">= 0"
>> load Gem.bin_path('railties', 'rails', version)
Usage: rails COMMAND [ARGS]

The most common rails commands are:
 generate    Generate new code (short-cut alias: "g")
 console     Start the Rails console (short-cut alias: "c")
 server      Start the Rails server (short-cut alias: "s")
 dbconsole   Start a console for the database specified in config/database.yml
             (short-cut alias: "db")
 new         Create a new Rails application. "rails new my_app" creates a
             new application called MyApp in "./my_app"

In addition to those, there are:
 destroy      Undo code generated with "generate" (short-cut alias: "d")
 plugin new   Generates skeleton for developing a Rails plugin
 runner       Run a piece of code in the application environment (short-cut alias: "r")

All commands can be run with -h (or --help) for more information.
```

@atul-shimpi Can you post the error you get?

**Comment by arthurnn** [comment]
I am not sure this is a bug.
thanks @prathamesh-sonpatki for testing this out.
Please re-open the issue with more info if it is still an issue.
