### ISSUE TITLE
include? returns wrong value when using to_datetime to compare 2 time ranges

### ISSUE THREAD

**Issue by kenzan100** [rails/rails#22565]
I'm on **Rails 4.2.5, Ruby 2.2.3p173** on Mac OS X 10.10.5

When comparing 2 time ranges, `include?` returns the right value as long as the first time-ish value isn't `DateTime` class.
But when the first value is something like `Time.now.to_datetime`, it suddenly gives me `false`.

```
irb(main):001:0> (Time.now..Time.now.end_of_day)
=> 2015-12-12 20:50:50 +0900..2015-12-12 23:59:59 +0900
irb(main):002:0> (Time.now..Time.now.end_of_day).include?((Time.now+1.hour)..(Time.now+2.hour))
=> true
irb(main):003:0> (Time.now..Time.now.end_of_day).include?((Time.now+1.hour).to_datetime..(Time.now+2.hour))
=> true
irb(main):004:0> (Time.now..Time.now.end_of_day).include?((Time.now+1.hour).to_datetime..(Time.now+2.hour).to_datetime)
=> true
irb(main):005:0> (Time.now..Time.now.end_of_day.to_datetime).include?((Time.now+1.hour).to_datetime..(Time.now+2.hour).to_datetime)
=> true
irb(main):006:0> (Time.now.to_datetime..Time.now.end_of_day.to_datetime).include?((Time.now+1.hour).to_datetime..(Time.now+2.hour).to_datetime)
=> false
```

**Comment by rajcybage** [comment]
@kenzan100 

As per your range it is showing wrong array for that range

```
irb(main):017:0> Array(Time.now.to_datetime..Time.now.end_of_day.to_datetime)
=> [Sun, 13 Dec 2015 13:01:18 +0530]

```

**Comment by kenzan100** [comment]
@rajcybage I now see what's happening under the hood, thanks :smiley: 
Still, I think it's misleading for them to work differently when given slightly different Time-ish objects?

maybe related
https://github.com/rails/rails/pull/21192

**Comment by kenzan100** [comment]
I ended up defining `cover_with_range?` in lib/core_ext/range.rb, much like `include_with_range?`

https://github.com/rails/rails/blob/b2de3f729496a223d64f9b55192d1b19bda4fc25/activesupport/lib/active_support/core_ext/range/include_range.rb#L12

I'm not sure this is the way to go, so if you have any opinion, I'd love to hear :smiley:
