### ISSUE TITLE
use key arguments in `alias_attribute` for passing `new_name` and `old_name`?

### ISSUE THREAD

**Issue by cantonic** [rails/rails#22577]
`alias_attribute :foo, :bar` doesn't make necessarily clear to me, which of the arguments is the new/old name.

```ruby
# File activesupport/lib/active_support/core_ext/module/aliasing.rb, line 62
  def alias_attribute(new_name, old_name)
    module_eval       def #{new_name}; self.#{old_name}; end          # def subject; self.title; end      def #{new_name}?; self.#{old_name}?; end        # def subject?; self.title?; end      def #{new_name}=(v); self.#{old_name} = v; end  # def subject=(v); self.title = v; end, __FILE__, __LINE__ + 1
  end
```

A more readable approach would be to use key arguments that illustrate a `:from => :to` direction to imply that the first argument is the `new_name`.
```ruby
# alias attribute :foo to :bar
  alias_attribute :foo => :bar
```

Maybe allow both and even a third one like in delegate?
```ruby
delegate :foo, to: :bar 
alias_attribute :foo, to: :bar
```
if you have a `delegate` line in your model and want to add an `alias_attribute` under it, one could tend to use the same `to` syntax.

**Comment by matthewd** [comment]
Thanks, but we don't take feature requests on the issue tracker. Please post to the rails-core mailing list to discuss suggestions.

(IMO, though, it's more important that we keep `alias_attribute` matching `alias_method`.)

**Comment by cantonic** [comment]
I have read http://edgeguides.rubyonrails.org/contributing_to_ruby_on_rails.html#what-about-feature-requests-questionmark before posting and have chosen to post it here instead of the mailing list, because for me it is more of a "style flaw" than a feature request, isn't it?
