### ISSUE TITLE
ActiveModel::Errors acting as a Hash

### ISSUE THREAD

**Issue by Bartuz** [rails/rails#22583]
Unless I looked into `#ancestors` I didn't know that ActieModel::Error is not inheriting from `Hash`. it feels like it's hash - `#[](:key)`, `#has_key?`, `#keys`, `#values` but it misses methods like `#fetch`, `#each` which would return new hash (not an array like now) or ActiveSupport monkeypatches to Hash like [#transform_values](http://apidock.com/rails/Hash/transform_values). 

Would it make sense to make ActiveModel::Errors inheriting from Hash? What do you think?

**Comment by sgrif** [comment]
No, we avoid inheriting from `Hash` or other built in types, and implement the needed methods.

**Comment by rafaelfranca** [comment]
@Bartuz see why it is usually a bad idea http://tenderlovemaking.com/2014/06/02/yagni-methods-are-killing-me.html
