### ISSUE TITLE
After upgrading from 4.2.4 to 4.2.5, getting "ActiveRecord::Fixture::FixtureError table "table" has no column named "column" when loading fixture.

### ISSUE THREAD

**Issue by dmagliola** [rails/rails#22584]
We're trying to upgrade from 4.2.4 and we're getting the error mentioned above when loading one of our fixture files.

I think I've narrowed it down to this commit in ActiveRecord: https://github.com/rails/rails/commit/e50fe85180648be0c4216bd0111f05be1df0988a

Which solves issue #21201

For some reason, for this particular column, this code fails:

```
if column = columns[name]
  key_list << quote_column_name(name) 
  quote(value, column)
else
  raise Fixture::FixtureError, %(table "#{table_name}" has no column named "#{name}".)
end
```

because `name` is a symbol, and `columns` is keyed by strings. 

I'm not sure why this happens for this fixture and not the others, presumably this failure here is indicative of a bug somewhere else, but this is as far as I've been able to drill down.

------

The exact error i'm getting is:

`ActiveRecord::Fixture::FixtureError: table "space_categories_spaces" has no column named "space_category_id".`

I believe this particular fixture is failing because it has a HABTM relationship:

### Models
```
class Space::Category < ActiveRecord::Base
end

class Space < ActiveRecord::Base
  has_and_belongs_to_many :categories, class_name: 'Space::Category', association_foreign_key: :space_category_id
end
```

### categories.yml
```
DEFAULTS: &DEFAULTS
  created_at: <%= Time.now %>
retail:
  <<: *DEFAULTS
  slug: retail

event:
  <<: *DEFAULTS
  slug: event
```

### spaces.yml
```
a_shop: &default
  slug: a_shop
  name: Shop Name
  categories: event,retail
```

If I remove this line: `categories: event,retail` from the fixture, it loads fine. Also, this fixture works well in 4.2.4.

Any help would be greatly appreciated!

**Comment by senny** [comment]
@dmagliola I'll have a look.

**Comment by Elektron1c97** [comment]
@dmagliola What db are you using?

Can you upload a mini rails project which produces the error?

Thank you very much

**Comment by dmagliola** [comment]
I'm using Postgres. 

I'll try to make a mini rails project to reproduce. 

Thank you 
Daniel

**Comment by cluesque** [comment]
Putting this in `config/initializers` makes the problem go away for me:

```
module RailsPatch22584
  def insert_fixture(fixture, table_name)
    # A regression with rails 4.2.5 breaks fixtures with symbol keys, specifically this one method.
    # So, stringify keys in the fixture hash being sent to this method.
    super(fixture.stringify_keys, table_name)
  end
end

ActiveRecord::ConnectionAdapters::PostgreSQLAdapter.include(RailsPatch22584)
```

**Comment by senny** [comment]
@cluesque can you upload an app that showcases the issue without the patch above?

**Comment by cluesque** [comment]
Sure @senny, [this project](cluesque/rails_22584) demonstrates the problem and the fix, in multiple commits.

**Comment by senny** [comment]
@cluesque what are the steps to reproduce? I end up with:

```
ActiveRecord::StatementInvalid: PG::UndefinedTable: ERROR:  relation "posts" does not exist
LINE 5:                WHERE a.attrelid = '"posts"'::regclass
                                          ^
:               SELECT a.attname, format_type(a.atttypid, a.atttypmod),
                     pg_get_expr(d.adbin, d.adrelid), a.attnotnull, a.atttypid, a.atttypmod
                FROM pg_attribute a LEFT JOIN pg_attrdef d
                  ON a.attrelid = d.adrelid AND a.attnum = d.adnum
               WHERE a.attrelid = '"posts"'::regclass
                 AND a.attnum > 0 AND NOT a.attisdropped
               ORDER BY a.attnum
```

and there are no migrations or schema files checked into the repository.

**Comment by cluesque** [comment]
@senny Whoops.  I failed to checkin the migration.  Should be clearer now.

You should be able to `rake db:setup`, `rake db:migrate`, and then just `rake` at each commit to see changes.

There are three interesting commits:
 - `Symbol keys are fine in fixtures in 4.2.4` - shows that as of 4.2.4 a fixture with symbols for attribute keys is supported.
 - `Rails 4.2.5 makes tests sad` - just bumping the rails version causes the test to fail
 - `Workaround for fixture loading` - shows the workaround making the fixtures work with 4.2.5

Sorry for the confusion.

**Comment by senny** [comment]
I pushed a fix to `master` and a backport to `4-2-stable`.

@dmagliola thank you for reporting :yellow_heart:

**Comment by dmagliola** [comment]
Thank you very much for the fix!
Sorry if this is a dumb question, but... How do I get this fix? How do I actually upgrade to 4.2.5 with this fix?
Thanks!

**Comment by senny** [comment]
@dmagliola you'll have to wait for `4.2.6` or `5.0.0` until the fix will be part of an official release. Another approach would be to pin your rails dependency to `4-2-stable`. A more pragmatic approach is to use a monkey patch, like to one from @cluesque. Once you upgrade to a version mentioned above you'll be able to remove that.

**Comment by dmagliola** [comment]
Excellent, thank you!

**Comment by fgbreel** [comment]
Hi, I'm not sure if this is related, but I'm receiving an error trying to load a fixture with `code` column with rails edge:

```
ActiveRecord::StatementInvalid: Mysql2::Error: Field 'name' doesn't have a default value: INSERT INTO `user` (`id`) VALUES (298486374)
```
```
one:
  name: foo
  code: asdcasd123
```

removing the `code` column from fixture the insert occurs.

Using the `safe_attributes` does't help, so I think this _may_ be related to this issue.

**Comment by senny** [comment]
@fgbreel can you upload a sample application to GitHub that reproduces the issue?

**Comment by fgbreel** [comment]
@senny I realized that I'm using the `code` column after a `anotherfield: 0`, and changing to `anotherfield: false` fixed the problem.
