### ISSUE TITLE
ActionMailer defines Rails module

### ISSUE THREAD

**Issue by dreyks** [rails/rails#22587]
```
$ irb
2.2.3 :001 > defined? Rails
 => nil
2.2.3 :002 > require 'action_mailer'
 => true
2.2.3 :003 > defined? Rails
 => nil
2.2.3 :004 > ActionMailer::Base
 => ActionMailer::Base
2.2.3 :005 > defined? Rails
 => "constant"
```
Module is actually defined in `rails-html-sanitizer` gem, which in turn is required by `ActionView::Helpers::SanitizeHelper`

Is this behavior intended? Cause if for example I want to use `ActionMailer` without Rails and I use some gem that can also work without rails, but has a usual `require 'some_gem/railtie' if defined? Rails` mantra in it, this breaks things, as `Rails` is defined, but actually not present

**Comment by rafaelfranca** [comment]
It is a dup of https://github.com/rails/rails-html-sanitizer/issues/26
