### ISSUE TITLE
SQLite primary keys are 64 bit but AR treats them as 32 bit

### ISSUE THREAD

**Issue by p** [rails/rails#22594]
SQLite documentation for an autoincrement column states:

" In SQLite, a column with type INTEGER PRIMARY KEY is an alias for the ROWID (except in WITHOUT ROWID tables) which is always a 64-bit signed integer. "

https://www.sqlite.org/autoinc.html

I can then do:

<pre>
sqlite> create table tests (a integer primary key);
sqlite> insert into tests (a) values (1311016998372151528);
sqlite> select * from tests;
1311016998372151528
</pre>

However, trying to set the same field in an active record model fails:

<pre>
irb(main):002:0> class Test < ActiveRecord::Base; end
=> nil
irb(main):003:0> Test.new(a: 1311016998372151528).save!
   (0.1ms)  begin transaction
   (0.1ms)  rollback transaction
RangeError: 1311016998372151528 is out of range for ActiveRecord::Type::Integer with limit 4
...
</pre>

I initially ran into this issue while trying to use https://github.com/caboteria/rails-bigint-pk.

**Comment by p** [comment]
I fixed by setting limit to 8 thusly: https://gist.github.com/p/2d1c26560e63e8850d40

**Comment by southwolf** [comment]
There's a "default limit" in `activemodel/lib/active_model/type/integer.rb`. Comments imply that changing it might cause problems in MySQL or Postgres. Any ideas?

```
# Column storage size in bytes.
# 4 bytes means a MySQL int or Postgres integer as opposed to smallint etc.
DEFAULT_LIMIT = 4
```

**Comment by p** [comment]
Default limit should take into account the datatype and the database engine.

**Comment by p** [comment]
Thanks!
