### ISSUE TITLE
#all_day excludes times within last second of the day

### ISSUE THREAD

**Issue by stevecj** [rails/rails#22597]
Instead of `(time.beginning_of_day..time.end_of_day)`, the range returned by `#all_day` should be `(time.beginning_of_day...(time.beginning_of_day + 1.day))`.

Note the use of triple-dot, so as to exclude the beginning of the next day but include values within the day no matter how small of a fraction of a second before the next day they happen to be.

**Comment by shakycode** [comment]
I like the precision on this.  And agree. PR?

**Comment by nateberkopec** [comment]
#all_day already behaves like you propose, [see the test](https://github.com/rails/rails/blob/6c3db3652faaa54e4e0b052e4042717c73f0d2f8/activesupport/test/core_ext/time_ext_test.rb#L872)

If I'm reading the fraction correctly, the time 11:59:59 and 999999.999 microseconds is included in #all_day's range.

**Comment by shakycode** [comment]
@nateberkopec You're right, I missed this.  Sorry

**Comment by stevecj** [comment]
@nateberkopec How are you getting that?

My experiment was…

    Time.current.all_day.end.usec
    => 0

**Comment by stevecj** [comment]
Perhaps, that was changed subsequent to Rails 3.2.22 where I am seeing it?

In any case, doesn't it seem more correct to use an exclusive range rather than try to represent the end of the day to the smallest currently applicable unit?

**Comment by stevecj** [comment]
Perhaps that change (dcdde7d on May 18, 2012) was only on the Rails 4 branch.

**Comment by nateberkopec** [comment]
@stevecj *shrug* Since the smallest unit Ruby understands is nanoseconds, I don't see the difference. `time.beginning_of_day..time.end_of_day` is more readable and easier to understand, and will perform better than your proposal (fewer objects created). [My benchmark shows that the current implementation is about twice as fast](https://gist.github.com/nateberkopec/f76e9a18edd3a33e29d4).

**Comment by stevecj** [comment]
I do think it's cleaner to not have this code depend on what the smallest unit of time happens to be, but the performance argument is compelling.

I suppose, my ideal would be to add a `#beginning_of_next_day` method and then have `#all_day` be implemented as `((time.beginning_of_day)...(time.beginning_of_next_day))`. I agree that my issue should be closed/dropped though.
