### ISSUE TITLE
Active Record Infinite range in where clause for DateTime causes StatementInvalid error

### ISSUE THREAD

**Issue by antek-drzewiecki** [rails/rails#22599]
Hi,

I am using Rails 4.2.5 with Ruby 2.2.3 and the MySQL 2 gem. I know Active Records supports ranges to get an between statement for the where clauses. It seems Active Record supports infinite ranges to get an greater or smaller statement for the where clauses.

Having the following examples:

``` ruby
2.2.3 :010 > User.where(id: 1..4)
SELECT `users`.* FROM `users` WHERE (`users`.`id` BETWEEN 1 AND 4)
```

I can also do and infinite range to get an greater then statement.

``` ruby
User.where(id: 1..Float::INFINITY)
SELECT `users`.* FROM `users` WHERE (`users`.`id` >= 1)
```

I can do the same with dates

``` ruby
User.where(created_at: DateTime.now..DateTime.now.at_end_of_day)
SELECT `users`.* FROM `users` WHERE (`users`.`created_at` BETWEEN '2015-12-15 13:07:22' AND '2015-12-15 22:59:59')
```

But I can't do

``` ruby
User.where(created_at: DateTime.now..DateTime::Infinity.new)
SELECT `users`.* FROM `users` WHERE (`users`.`created_at` BETWEEN '2015-12-15 13:09:34' AND #<Date::Infinity:0x007fe9b605b138>)

ActiveRecord::StatementInvalid: Mysql2::Error: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '' at line 1: SELECT `users`.* FROM `users` WHERE (`users`.`created_at` BETWEEN '2015-12-15 13:09:34' AND #<Date::Infinity:0x007fe9b605b138>)
```

First of all, is this a bug or a feature request? 
The range seems to be an valid range. But this wont result in a greater and equals then statement as I would expect.

**Comment by sblackstone** [comment]
Why not just use greater than instead of between if you don't care about the end of the date range?

**Comment by matthewd** [comment]
`Date::Infinity` has always been explicitly undocumented, and has been [considered deprecated since 1.9.3](https://github.com/ruby/ruby/commit/c70988cbe93359c9f9f423f88717e329f2c088d0#diff-4574f59a5e8bb1449b78608685f33335R240).

On the other hand, people do keep finding it and using it -- and it continues to implement everything necessary to work in normal comparisons, so maybe we should just give in and properly support it as long as it exists. ¯\\\_(ツ)\_/¯

**Comment by tadeusrox** [comment]
I opened a PR on rails/arel, not sure if exist somewhere here I need to change...
