### ISSUE TITLE
filter chain halted as rendered or redirected

### ISSUE THREAD

**Issue by EdwinRozario** [rails/rails#22603]
I have a RoR app that consumes a RoR API. The API has a before_filter :authenticate_user! in the application controller. I am getting this error `filter chain halted as rendered or redirected` only when on a create action at the API when posted from the app, every thing else works fine with the API. I cant avoid that filter for that create action.

The weird  thing is that no one changed anything and the we never had this issue before until this appeared from no where one day. Among the 3 servers this happens only on 2 of them. Same code works fine in staging as well.

Rails version '~> 4.1.4'
ruby 1.9.3p385

Can anyone help!

**Comment by rafaelfranca** [comment]
You need to give us more information on how to reproduce this issue, otherwise there is nothing we can do. Please read CONTRIBUTING.md file for more information about creating bug reports. Thanks!
