### ISSUE TITLE
`config.action_view.field_error_proc` does not work when it was declared in initializer

### ISSUE THREAD

**Issue by vladimirsazhin** [rails/rails#22606]
I tried to define proc in the `config/initializers/action_view.rb` file with no effect:
```ruby
Rails.application.configure do
  # Specify the proc used to decorate input tags that refer to attributes with errors.
  config.action_view.field_error_proc = ->(html_tag, instance) { html_tag }
end
```

It works fine when declared inside `Application` class.
```ruby
module Foo
  class Application < Rails::Application
     # Specify the proc used to decorate input tags that refer to attributes with errors.
    config.action_view.field_error_proc = ->(html_tag, instance) { html_tag }
  end
end
```

I use edge Rails (revision 89f7764).

**Comment by kuldeepaggarwal** [comment]
@vladimirsazhin: I am using the configuration in the `config/initializers/inline_error.rb` file and it's working.

```rb
ActionView::Base.field_error_proc = Proc.new do |html_tag, instance|
  if html_tag !~ /^\<label/
    %(#{ html_tag }
      <span class="error-msg red">
        #{ instance.error_message.join(',') }
      </span>
    ).html_safe
  else
    html_tag
  end
end
```

**Comment by rafaelfranca** [comment]
Does it work like that in Rails 4.2?

**Comment by herminiotorres** [comment]
hi @vladimirsazhin maybe that is your problem by `web-console` change `ActionView`, now has a fix on the `web-console` that uses the `autoload` instead `require` to `boot` and might not come to have more trouble. cc/ @rafaelfranca
