### ISSUE TITLE
Option to turn off enforced automatic "include_blank"

### ISSUE THREAD

**Issue by kikonen** [rails/rails#22607]
It seems that rails is trying to enforce inclusion of blank value into select options based into inapproriate heuristics. Problem is that turning off this heuristics is not possible, since saying "include_blank: false" is ignored due to logic.

````ruby
        def select_content_tag(option_tags, options, html_options)
          html_options = html_options.stringify_keys
          add_default_name_and_id(html_options)
          options[:include_blank] ||= true unless options[:prompt] || select_not_required?(html_options)
...      
````
=> thus not possible to turn off auto inclusion of blank, due to how false and "||=" co-op together.

Reason: This enforced auto inclusion of blank in rendering causes problems, for example, when JS libraries with their own concept of "optional blank" exist. This rails logic conflicts with them, causing select options to contain  two different blank values.

Suggestion:
````ruby
        def select_content_tag(option_tags, options, html_options)
          html_options = html_options.stringify_keys
          add_default_name_and_id(html_options)
          if !options.has_key?(:include_blank)
            options[:include_blank] ||= true unless options[:prompt] || select_not_required?(html_options)
          end
...      
````

**Comment by greysteil** [comment]
Hey @kikonen, there's a history on this one in https://github.com/rails/rails/pull/20124, and the code's since been updated from your pasted version to be more explicit.

FWIW, my personal view is that the HTML spec that mandates required select boxes to have a placeholder option is unhelpful, but I can see the argument for Rails honouring it.

**Comment by kikonen** [comment]
Would it hurt to allow false to work as false, meaning that "I know what I'm doing and I'm handling this in appropriate manner via some other framework, ex. some JS widget". I.e. problem is not that rails shouldn't have some support for for sane logic, but rather that logic shouldn't be enforced so that co-operation with other frameworks/libraries/widgets can be managed in sensible manner.

**Comment by matthewd** [comment]
@kikonen we generate HTML. If you want to produce something that's *not* HTML, I think it's fine to leave you to implement it yourself.

**Comment by kikonen** [comment]
So you are saying that passing options array to select_tag, where first entry is blank value is not html? I guess it is "rails way or the highway", since rails enforcedly adds its own blank value and generated content has nicely rails' dummy blank value and desired blank. Took some reverse engineering to find what caused such strange bug.
