### ISSUE TITLE
Hash#transform_keys! overwrites keys

### ISSUE THREAD

**Issue by majewsky** [rails/rails#22608]
`Hash#transform_keys!` may break when the transformation function produces keys that also exist in the original hash. Mathematically speaking, there is a problem when the pre-image and the image of the transformation function have a non-empty intersection.

To reproduce,
```ruby
a = {}
(1..10).each { |x| a[x] = x * x }
expect(a.size) to be(10) # success

a.transform_keys! { |x| x + 1}
expect(a.size) to be(10) # fails, a.size == 1
```

This is a more general case of #18515.

**Comment by kaspth** [comment]
See https://github.com/rails/rails/pull/18598#issuecomment-73537978 - thanks though! :grin:
