### ISSUE TITLE
`has_secure_password` limits password to 72 characters, while the limitation is actually in bytes

### ISSUE THREAD

**Issue by jokester** [rails/rails#22617]
BCrypt actually uses the first 72 bytes in password, as shown in this [gist](https://gist.github.com/jokester/da75e217f1653e125c40). While [rails](https://github.com/rails/rails/blob/master/activemodel/lib/active_model/secure_password.rb#L77) is validating the length in characters instead of bytes.

I suppose this differs when password contains multibyte characters, and propose to validate the size in `to_s.bytes.length`, or at least mention this difference in document.

**Comment by jokester** [comment]
I'm happy to prepare a PR if you also think this should be fixed.

**Comment by rafaelfranca** [comment]
@jokester please send the PR.

**Comment by chzbryn** [comment]
The character encoding in Java is UTF-16, but UTF-8 actually allows for a larger code point (cost) of encoding. Granted the encoding that will actually be used by JRuby can be changed based on the local env variables, would the potential validation gap between the 2 point UTF-16 encoding & the potential 4 point UTF-8 encoding warrant including that in the byte validation using forced encoding for UTF-8?

**Comment by arthurnn** [comment]
closing this , as https://github.com/rails/rails/pull/22870 was closed.
