### ISSUE TITLE
config.action_dispatch.rescue_responses being cleared

### ISSUE THREAD

**Issue by obduk** [rails/rails#22613]
According to https://github.com/rails/rails/blob/master/guides/source/configuring.md `config.action_dispatch.rescue_responses` is set a number of values which are defined in https://github.com/rails/rails/blob/master/actionpack/lib/action_dispatch/middleware/exception_wrapper.rb#L9

However if I create a new rails app `config.action_dispatch.rescue_responses` is set to [].

I cannot quite follow the code through to work out if the documentation is wrong, or something is overriding it.

Thanks

**Comment by rafaelfranca** [comment]
Try to get `ActionDispatch::ExceptionWrapper.rescue_responses`. The config is empty indeed because it is not were the value is stored.

**Comment by obduk** [comment]
But in the configuring.md it says:

config.action_dispatch.rescue_responses configures what exceptions are assigned to an HTTP status. It accepts a hash and you can specify pairs of exception/status. By default, this is defined as:
```
config.action_dispatch.rescue_responses = {
  'ActionController::RoutingError'              => :not_found,
  'AbstractController::ActionNotFound'          => :not_found,
  'ActionController::MethodNotAllowed'          => :method_not_allowed,
  'ActionController::UnknownHttpMethod'         => :method_not_allowed,
  'ActionController::NotImplemented'            => :not_implemented,
  'ActionController::UnknownFormat'             => :not_acceptable,
  'ActionController::InvalidAuthenticityToken'  => :unprocessable_entity,
  'ActionController::InvalidCrossOriginRequest' => :unprocessable_entity,
  'ActionDispatch::ParamsParser::ParseError'    => :bad_request,
  'ActionController::BadRequest'                => :bad_request,
  'ActionController::ParameterMissing'          => :bad_request,
  'ActiveRecord::RecordNotFound'                => :not_found,
  'ActiveRecord::StaleObjectError'              => :conflict,
  'ActiveRecord::RecordInvalid'                 => :unprocessable_entity,
  'ActiveRecord::RecordNotSaved'                => :unprocessable_entity
}
```
So is the doc wrong then?

**Comment by rafaelfranca** [comment]
No, it is not wrong. The default values are those just not stored in the config. The configuration is only a transient place to put these values.
