### ISSUE TITLE
sprockets-rails 3.0.0 release: undefined method `register_preprocessor' for nil:NilClass

### ISSUE THREAD

**Issue by mikeantonelli** [rails/rails#22647]
With the release of [sprockets-rails 3.0.0](https://github.com/rails/sprockets-rails/releases/tag/v3.0.0) today, my Ruby on Rails Engines started failing to initialize during continuous integration with:

```
less-rails-2.7.0/lib/less/rails/railtie.rb:23:in `block in <class:Railtie>': undefined method `register_preprocessor' for nil:NilClass (NoMethodError)
```

[Rails trusts sprockets-rails >= 2.0.0](https://github.com/rails/rails/blob/master/rails.gemspec#L32). I'm still working through the exact error but locking to `~> 2.3` resolved the problem - should this dependency's version lock differently?

**Comment by matthewd** [comment]
That error doesn't seem to be coming from Rails.

**Comment by u007** [comment]
its still happening, due to sprocket-rails 3.0 relying on sprocket 3

**Comment by u007** [comment]
can this issue be reopen?

**Comment by matthewd** [comment]
@u007 the backtrace in this issue shows the exception is coming from `less-rails`. This is not a Rails issue.
