### ISSUE TITLE
Action Cable channel generator should not create JS assets in --api mode

### ISSUE THREAD

**Issue by dhh** [rails/rails#22669]
If you've created your app as --api, the Action Cable channel generator should not create the corresponding channel JS stub.

**Comment by jeyb** [comment]
Thoughts on https://github.com/rails/rails/pull/22685 @dhh?

I wasn't sure if setting `skip_action_cable: true` when `options[:api]` is appropriate as I'm still wrapping my head around Action Cable. I don't see much purpose to it when the application is meant to be an API, but I might be missing something.

**Comment by guilleiguaran** [comment]
@jeyb I've seen a couple of API + Cable apps so I'm not sure that we should set `skip_action_cable: true` when API flag is used.

Think for example in apps that provide HTTP API to clients but want to offer also some resources that are created/updated in real-time through WebSockets API.

**Comment by dhh** [comment]
Definitely don't want to turn off cable for api. Only want to turn off the
asset part of the channel generator. Everything else should stay the same.

On Sat, Dec 19, 2015 at 5:40 AM, Guillermo Iguaran <notifications@github.com

**Comment by habermann24** [comment]
Hey @rafaelfranca, I'm afraid the merge request you picked fails sometimes.

```
ruby -I test test/generators/channel_generator_test.rb
Run options: --seed 18568

# Running:

.F

Finished in 0.006424s, 311.3325 runs/s, 1245.3300 assertions/s.

  1) Failure:
ChannelGeneratorTest#test_channel_is_created [test/generators/channel_generator_test.rb:15]:
Expected file "app/assets/javascripts/channels/chat.coffee" to exist, but does not

2 runs, 8 assertions, 1 failures, 0 errors, 0 skips
```

My guess is that some other test might set the options[:assets], so that the test order is important.


I created another pull-request to fix this: https://github.com/rails/rails/pull/22737

**Comment by rafaelfranca** [comment]
yeah, the implementation can be also improved. I'll do it myself.

**Comment by rafaelfranca** [comment]
Done https://github.com/rails/rails/commit/f51a30c66692a5da2d5152d5e7e6130d88480c03
