### ISSUE TITLE
Websocket messages have surprising escaping

### ISSUE THREAD

**Issue by rafaelfranca** [rails/rails#22675]
_From @KevinMcHugh on August 20, 2015 19:33_

I've got ActionCable running in a Rails 4 app and it's wonderful, it feels very rails-y already. Thank you to everyone for your hard work.

In writing my client of the ActionCable websockets, I was surprised that the messages to subscribe and follow channels are as following:
`{"command":"subscribe","identifier":"{\"channel\":\"CommentsChannel\"}"}`
and
`{"command":"message","identifier":"{\"channel\":\"CommentsChannel\"}","data":"{\"message_id\":1,\"action\":\"follow\"}"}`
(pulled from the example app in [rails/actioncable-examples](https://github.com/rails/actioncable-examples)).

Generating those messages in my client (a rails-agnostic ReactJS app) was more complicated than it could have been. I was surprised that those messages weren't:
`{"command":"subscribe","identifier": {"channel": "CommentsChannel"}}`
and
`{"command":"message","identifier": {"channel":"CommentsChannel"}",
  "data":"{"message_id":1,"action":"follow"}"}`
 
The latter is more easily serialized and easier to generate. I think I'm missing some aspect that makes the escaped `identity` and `data` values superior. Is there a principle or detail here that I should know about for continuing to develop code against ActionCable?

(This isn't a bug, but it made developing JS against ActionCable painful in a surprising way. If this isn't the correct place for me to ask my question, I apologize and would be happy to know where I should be asking this sort of thing.)

_Copied from original issue: rails/actioncable#64_

**Comment by rafaelfranca** [comment]
_From @CraigSnowden on October 28, 2015 12:23_

This is quite annoying for me too

**Comment by twairball** [comment]
I notice that in `ActiveSupport::JSON.decode` is called again in `ActionCable::Connection::Subscriptions`, even though `data` passed to `subscriptions.execute_command` is already json decoded in `ActionCable::Connection::Base`. 

I've dug around related issues and the actioncable example app, I think I'm missing some principle or rationale for this to be decoded twice? 

Would it be safe for `Connection::Subscriptions` to assume all data passed to it from `Connection::Base` is already json decoded ?

**Comment by maclover7** [comment]
Where do you see this on master? I'm not seeing anything being decoded twice here: https://github.com/rails/rails/blob/master/actioncable/lib/action_cable/connection/subscriptions.rb

**Comment by acwright** [comment]
+1

**Comment by acwright** [comment]
The following monkey patch on `ActionCable::Connection::Subscriptions` solved this issue for me:

```
module ActionCable
  module Connection
    class Subscriptions
      def add(data)
        id_key = data['identifier']
        #id_options = ActiveSupport::JSON.decode(id_key).with_indifferent_access
        id_options = data['identifier']

        #subscription_klass = connection.server.channel_classes[id_options[:channel]]
        subscription_klass = connection.server.channel_classes[id_options['channel']]

        if subscription_klass
          subscriptions[id_key] ||= subscription_klass.new(connection, id_key, id_options)
        else
          logger.error "Subscription class not found (#{data.inspect})"
        end
      end

      def perform_action(data)
        #find(data).perform_action ActiveSupport::JSON.decode(data['data'])
        find(data).perform_action data['data']
      end
    end
  end
end
```

Here is the resulting message log with properly decoded messages from my client application after above patch:

```
websocket is connected
got some text: {"identifier":"_ping","message":1454021909}
got some text: {"identifier":{"channel":"ChangesChannel"},"type":"confirm_subscription"}
got some text: {"identifier":"_ping","message":1454021912}
got some text: {"identifier":"_ping","message":1454021915}
got some text: {"identifier":"_ping","message":1454021918}
got some text: {"identifier":{"channel":"ChangesChannel"},"message":{"data":{"id":"2818","type":"changes","attributes":{"item-id":1,"item-type":"Account","event":"update","whodunnit":null,"changes":{"updated-at":{"from":"2016-01-28T22:56:33.187Z","to":"2016-01-28T22:58:40.691Z"},"first-name":{"from":"Bob","to":"Joe"}},"created-at":"2016-01-28T22:58:40.691Z"}}}}
got some text: {"identifier":"_ping","message":1454021921}
got some text: {"identifier":"_ping","message":1454021924}
```

As you can see the `identifier` and `data` values are **not escaped** which in my opinion should be the correct response from the ActionCable server.

And the following code now works correctly as I would expect from my client application (which in my case is an iOS client):

```
...
        let dict: [String: AnyObject] = [
            "command": "subscribe",
            // This code was needed before patch in order to subscribe!!
            // "identifier": "{\"channel\":\"ChangesChannel\"}"
            // This is what I was expecting to work before patch, and now does after patch
            "identifier": [
                "channel": "ChangesChannel"
            ]
        ]
        do {
            let data = try NSJSONSerialization.dataWithJSONObject(dict, options: NSJSONWritingOptions(rawValue: 0))
            self.socket?.writeString(NSString(data: data, encoding: NSUTF8StringEncoding)! as String)
        } catch {
            print("encoding error")
        }
...
```

Hope this helps out or clarifies the discussion!

**Comment by maclover7** [comment]
I can understand that the JSON might be a bit tough to read through, but I tried using your monkey patch on ActionCable on Rails master, and this actually breaks a bunch of the tests. I think the system is fine the way we have it, but if you're looking to make any changes, you can check out the `ActiveSupport::JSON` code [here](https://github.com/rails/rails/tree/master/activesupport/lib/active_support/json).

**Comment by acwright** [comment]
I do understand that this patch would break some tests. That is not surprising to me. But the original issue I believe is still relevant and shouldn't be closed.

The following JSON sent to the server should succeed:

`{"command": "subscribe","identifier":{"channel":"ChangesChannel"}}`

It does not! Instead you must send this:

`{"command": "subscribe","identifier":"{\"channel\":\"ChangesChannel\"}"}`

Why would the `identifier` or `data` fields need to be encoded in this manner? What is the purpose of this? I think this is still an issue... please reconsider.

**Comment by maclover7** [comment]
If you are willing to submit a PR with a change to support this and have the tests pass, I'm all ears to have this be changes! :smile:

**Comment by acwright** [comment]
I can certainly give it a go! :smile:

In order to understand this better, can you clarify as to why the `identifier` and `data` fields are being encoded in this manner? Is this due to how the ActionCable javascript client encodes or wants the data to be passed to the server? I guess what I really need to know is if this formatting is intentional for any reason?

To be clear, I am not using the javascript client provided by ActionCable and have no plans to do so in my current project. I want to utilize only the server-side functionality of ActionCable and I suspect others may as well. This is why I think this issue needs further discussion.

It seems like the expectation from a client-side perspective is that you would simply pass properly formatted JSON messages to the server, but needing to specially format them with escaped JSON in the `identifier` and `data` as discussed above would break that expectation. Is this valid?

**Comment by maclover7** [comment]
Not very familiar with the client side parts of ActionCable that are sending the JSON to the server -- cc @javan.

**Comment by twairball** [comment]
@acwright we have nearly the same patch :) Having gone through the tests, I see this pattern appears in other places also, e.g. `ActionCable::Connection::InternalChannel`, so my patch needs a little more work before it can be a proper PR.

@maclover7 the methods `add` and `perform` in `ActionCable::Connection::Subscription` call `ActiveSupport::JSON.decode`. The problem we are seeing from this is: 

- They receive the json from `execute_command`. 

- All json passed to `execute_command` in `ActionCable::Connection::Subscription` is already json decoded from `ActionCable::Connection::Base`  


https://github.com/rails/rails/blob/master/actioncable/lib/action_cable/connection/subscriptions.rb
````
      def execute_command(data)
        case data['command']
        when 'subscribe'   then add data
        when 'unsubscribe' then remove data
        when 'message'     then perform_action data
        ....
      end

      def add(data)
        ...
            id_options = ActiveSupport::JSON.decode(id_key).with_indifferent_access
        ...
      end

      def perform_action(data)
        find(data).perform_action ActiveSupport::JSON.decode(data['data'])
      end
````


https://github.com/rails/rails/blob/master/actioncable/lib/action_cable/connection/base.rb
````
      # Data received over the cable is handled by this method. It's expected that everything inbound is JSON encoded.
      # The data is routed to the proper channel that the connection has subscribed to.
      def receive(data_in_json)
        if websocket.alive?
          subscriptions.execute_command ActiveSupport::JSON.decode(data_in_json)
        else
          logger.error "Received data without a live WebSocket (#{data_in_json.inspect})"
        end
      end
````

**Comment by dhh** [comment]
@javan @lifo Was there any reason we were escaping before?

**Comment by javan** [comment]
@lifo would know best. It was already that way when I started reworking the client-side code.

**Comment by maclover7** [comment]
I opened up PR #23649 to solve this issue. Also, previously, subscriptions were identified by their un-decoded JSON string (for example: `"{\"channel\":\"RoomChannel\"}"`), but I've fixed this as well, to allow for the un-backslashed version to also be accepted. I believe that this should fix any errors with non-backslashed-JSON being received.

**Comment by twairball** [comment]
Thanks @maclover7 for the awesome changes! I am new to contributing, so I have a quick question for you: is changing tests kosher for PRs ? I've been working on a PR but i would need to change how global subscriptions hash is done. 

I believe `data['data']` needs to be escaped also, this is the hash key that cables use to handle actions.

**Comment by maclover7** [comment]
I'd appreciate it if you made comments on my PR instead of opening up a new one...

**Comment by twairball** [comment]
Sorry about that! I did not know the correct protocol/etiquette. The PR fixes the issue from iOS clients, thanks so much for your work.

**Comment by maclover7** [comment]
No problem. :)

**Comment by jeremy** [comment]
#24233 will revert the changes in #23649. Making ad hoc changes to the cable message format is going to sting us, introducing errors and confusion about the proper protocol. Once we can version the protocol, we can make a case for removing the unnecessary JSON encoding for identifier and data values.

**Comment by TAiS46** [comment]
is there any update on this?

**Comment by jeremy** [comment]
@TAiS46, anything in particular you're looking for an update on? (There is no separate information repository where updates are gathered, so this page reflects all current knowledge and discussion on the topic.)

**Comment by TAiS46** [comment]
Jut the escaping:
```{"command":"subscribe","identifier":"{\"channel\":\"CommentsChannel\"}"}```

to
```{"command":"subscribe","identifier": {"channel": "CommentsChannel"}}```

**Comment by jeremy** [comment]
Gotcha! There are no efforts in progress to change the message format. 👍

**Comment by TAiS46** [comment]
why is that? We are using action cable as a public endpoint and our users don't understand why they need to escape the identifier.

**Comment by jeremy** [comment]
It is confusing, yes! For developers too.

The short story: the cable message `identifier` and `data` values are *arbitrary data* that happen to be encoded as JSON, which gives the confusing result of "why is this 'escaped' (really, encoded) JSON in my JSON???" as if it's a bug, when the reality is a bit simpler, if a bit convoluted:

1. Cable messages are encoded as JSON transported over WebSocket data frames;
2. Cable messages include `identifier` (a unique, comparable string) and `data` (arbitrary string payload) fields;
3. Cable channels happen to create the identifier by encoding a JSON object, resulting in a unique, comparable *string* for the cable message;
4. Cable channels happen to provide a payload string as an encoded JSON object;
5. The result is this "escaped JSON within JSON" situation.

More on this: https://github.com/rails/rails/pull/24040#issuecomment-194490769
And the outcome of it: https://github.com/rails/rails/pull/24233

(Thought experiment: What if Cable messages used MessagePack instead of JSON, but channels still used JSON? What if `identifier`s were URLs (strings), not JSON? What if `data` was Marshal.dumped binary data? In these cases, it's clear that double encoding is necessary.)
