### ISSUE TITLE
libc++abi.dylib: terminating with uncaught exception of type std::runtime_error

### ISSUE THREAD

**Issue by rafaelfranca** [rails/rails#22676]
_From @huetsch on October 24, 2015 2:29_

After running "bundle exec puma -p 28080  cable/config.ru" for a while, it always dies with the following error:

libc++abi.dylib: terminating with uncaught exception of type std::runtime_error: adding existing descriptor
Abort trap: 6

I believe it may be related to this faye-websocket-ruby bug:

https://github.com/faye/faye-websocket-ruby/issues/35

The server randomly dying all the time is a pretty big issue for using actioncable smoothly in production.

_Copied from original issue: rails/actioncable#104_

**Comment by rafaelfranca** [comment]
_From @nflorentin on November 5, 2015 8:12_

+1
I'm facing the same issue and a bit worried about putting this into production

**Comment by rafaelfranca** [comment]
_From @mikecarroll on December 2, 2015 15:50_

+1 Seems to happen with us only when people try to run the cable on certain IE versions.

**Comment by rafaelfranca** [comment]
_From @dhh on December 11, 2015 15:53_

Odd. We've not seen any of these issues in production. At least that I'm aware of! And we have many tens of thousands of daily active users on Basecamp 3.

**Comment by rafaelfranca** [comment]
_From @mikecarroll on December 11, 2015 16:1_

It seems to be happening to us only when running locally, not in production. Our servers are Linux but we use OSX for dev, so maybe it's an OSX issue?

**Comment by rafaelfranca** [comment]
_From @nflorentin on December 11, 2015 16:18_

Same case for us, described by @mikecarroll, Linux servers in prod and OS X for dev.

**Comment by rafaelfranca** [comment]
_From @dhh on December 11, 2015 16:28_

Maybe we can just start by saying this is a problem on OSX in the readme for now? Don't think anyone is actually deploying on OSX. I don't know if this is really something we can solve in AC anyway?

**Comment by maclover7** [comment]
Is this still an issue?
