### ISSUE TITLE
Upgrading to 2.2.4 causes syntax errors for create_view in schema.rb

### ISSUE THREAD

**Issue by chrisnicola** [rails/rails#22680]
Views specified in schema.rb seem to have a syntax issue as of Ruby 2.2.4. This is possibly related to some label syntax changes that they snuck into this patch (http://svn.ruby-lang.org/repos/ruby/tags/v2_2_4/ChangeLog)

Essentially with Ruby 2.2.4 this code is ok

```
{
  label: <<-DOC
Some text for a heredoc goes here
  DOC
}
```

But this is invalid:

```
{
  label:<<-DOC
Some text for a heredoc goes here
  DOC
}
```

However, both were valid in 2.2.3.

Note that the latter merely lacks a space between the label colon and the beginning of the heredoc. The schema file writing `create_view` without a space between `sql_definition:` and the heredoc value.

**Comment by matthewd** [comment]
This is not a Rails issue.

**Comment by chrisnicola** [comment]
Sorry about that, you are right, I realize this is happening in thoughtbot/scenic. My mistake.
