### ISSUE TITLE
Cruft? ActiveSupport::OrderedHash

### ISSUE THREAD

**Issue by cdale77** [rails/rails#22681]
A friend and I were looking at ActiveSupport::OrderedHash, and noticed some odd things. First, there's a test for it:
https://github.com/rails/rails/blob/7f18ea14c893cb5c9f04d4fda9661126758332b5/activesupport/test/ordered_hash_test.rb

But Rails doesn't seem to be actually using OrderedHash:
https://github.com/rails/rails/search?utf8=%E2%9C%93&q=OrderedHash

Interestingly, ActiveSupport::OrderedOptions seems to depend on inherent Hash ordering, and doesn't use OrderedHash. Why does ActiveSupport provides this class, but doesn't actually use it itself? Is this left over from Ruby pre 1.9, which did not provide ordered Hashes?

**Comment by rafaelfranca** [comment]
> Why does ActiveSupport provides this class, but doesn't actually use it itself?

It is for backward compatibility. OrderedHash is [serialized differently in YAML](https://github.com/rails/rails/blob/043660249bd8587194202cf4440fb1fd9db109a4/activesupport/lib/active_support/ordered_hash.rb#L16-L18) and if you have it stored in your database as yaml and we removed the class you application will break.

That class is deprecated and we don't recommend people to use. This is why we are not using it in `OrderedOptions`. But we have to keep its code inside Rails for a while.
