### ISSUE TITLE
"--skip-keeps" option breaks cable.coffee

### ISSUE THREAD

**Issue by atsheehan** [rails/rails#22708]
When generating a new project without the `.keep` files (i.e. `--skip-keeps` option for `rails new`), the autogenerated `app/assets/javascripts/cable.coffee` file breaks when attempting to load the missing `channels` directory:

```
#= require_tree ./channels
```

## Steps to Reproduce

The following commands can be used to reproduce this error:

```
$ rails _5.0.0.beta1_ new missing_channels --skip-keeps
$ cd missing_channels
$ rails generate scaffold message body:string
$ rails db:migrate
$ rails server
```

Visiting [http://localhost:3000/messages](http://localhost:3000/messages) will attempt to load the assets, generating the following error:

```
Started GET "/messages" for ::1 at 2015-12-20 10:52:42 -0500
Processing by MessagesController#index as HTML
  Message Load (0.2ms)  SELECT "messages".* FROM "messages"
  Rendered messages/index.html.erb within layouts/application (5.6ms)
Completed 500 Internal Server Error in 1069ms (ActiveRecord: 0.5ms)

ActionView::Template::Error (require_tree argument must be a directory):
     5:     <%= csrf_meta_tags %>
     6:     <%= action_cable_meta_tag %>
     7:
     8:     <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
     9:     <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    10:   </head>
    11:
  app/assets/javascripts/cable.coffee:8
  app/views/layouts/application.html.erb:8:in `_app_views_layouts_application_html_erb__2766907892982517921_70110278478220'
```

## Possible Solutions

I can think of a few possible solutions:

* Remove the `require_tree ./channels` line from `cable.coffee`. This avoids having to create the `channels` directory until it's needed.
* Force the `.keep` file, even if the `--skip-keeps` option is enabled. The reasoning here would be that the directory is required by `cable.coffee` and would not function without it.
* Keep the error as-is. Although not a great developer experience, it forces them to consider whether they want to use this convention.

Not sure which approach is best here.

**Comment by eileencodes** [comment]
What do other generators do when you do `--skip-keeps`? We should follow convention and change Action Cable files to behave the same way.

**Comment by gwincr11** [comment]
@eileencodes I maybe mis-reading this or missing something. But I think this is likely only an issue for activecable, as it is broken in the asset pipeline. I am not aware of another generator that builds folders in the assets folder.

**Comment by gwincr11** [comment]
I am wondering if cable.coffee should be built by default? Seems like there is overhead being loaded to the browser that more often than not will be unnecessary. Should this generator be skipped by default?

**Comment by matthewd** [comment]
The generator should be using `empty_directory_with_keep_file` instead of plain `keep_file`.
