### ISSUE TITLE
Activerecord scope chaining error when using same columns

### ISSUE THREAD

**Issue by valgayres** [rails/rails#22723]
Hi, 

I've encountered a strange behavior when chaining scopes that act on the same columns after migrating from rails 4.0.0 to 4.2.4.

Let's consider the following class

```
class  Car < ActiveRecord::Base
  scope :electric_car, -> { where(electric: true, sold: false) }
  scope :for_owner, ->(owner_id) { where(owner_id: owner_id, sold: false) }
end
```

Now, theoretically, doing `Car.for_owner(1).electric_car` and `Car.electric_car.for_owner(1)` should give the same answer.

The problem is that looking at the sql query we see the following issue:

```
Car.for_owner(1).electric_car.to_sql
=> "Select \"cars\".* FROM \"cars\" WHERE \"cars\".\"owner_id\" = 1 AND \"cars\".\"sold\" = 'f' AND \"cars\".\"sold\" = 't' AND \"cars\".\"electric\" = 'f'"

Car.electric_car.for_owner(1).to_sql
=> Select \"cars\".* FROM \"cars\" WHERE\"cars\".\"electric\" = 't' AND \"cars\".\"sold\" = 'f' AND \"cars\".\"sold\" = 'f' AND  \"cars\".\"owner_id\" = 1"
```

As we can see, In the first case, the second filter on the "sold" column and the filter on the "electric" column are switched. 
Analysing a bit the sql queries, we understood that the issue is that parameters of the query are reordered, but not the values asked. For example, running real queries in development, we see this:

```
Car.for_owner(1).electric_car
Car load (2.0ms) Select "cars".* FROM "cars" WHERE "cars"."owner_id" = 1 AND "cars"."sold" = $1 AND "cars"."sold" = $2 AND "cars"."electric" = $3 [["sold", "f"], ["electric", "t"], ["sold", "false"]]
=> #<ActiveRecord::Relation []>
```

Has anyone ever seen this? Or have a fix?

Thanks a lot!

**Comment by eileencodes** [comment]
Hi @valgayres, thanks for the report! Can you reproduce the issue using one of the Active Record script templates https://github.com/rails/rails/blob/master/guides/bug_report_templates/active_record_gem.rb?

That will help us track down the issue. Thanks!

**Comment by claptimes5** [comment]
I've found the same issue when upgrading from 4.1.14 to 4.2.5 and have included a gist using the bug report template: https://gist.github.com/claptimes5/f47502ccc378a748f861

**Comment by sevaorlov** [comment]
@valgayres, I've created this script and switching doesn't happen for me in Rails 4.2.4. What am I doing wrong?

```ruby
begin
  require 'bundler/inline'
rescue LoadError => e
  $stderr.puts 'Bundler version 1.10 or later is required. Please update your Bundler'
  raise e
end

gemfile(true) do
  source 'https://rubygems.org'
  gem 'rails', '4.2.4'
  gem 'sqlite3'
end

require 'active_record'
require 'minitest/autorun'
require 'logger'

# Ensure backward compatibility with Minitest 4
Minitest::Test = MiniTest::Unit::TestCase unless defined?(Minitest::Test)

# This connection will do for database-independent bug reports.
ActiveRecord::Base.establish_connection(adapter: 'sqlite3', database: ':memory:')
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :cars, force: true do |t|
    t.boolean :sold
    t.boolean :electric
    t.integer :owner_id
  end
end

class Car < ActiveRecord::Base
  scope :electric_car, -> { where(electric: true, sold: false) }
  scope :for_owner, ->(owner_id) { where(owner_id: owner_id, sold: false) }
end

class BugTest < Minitest::Test
  def test_scope_chaining
    # "SELECT \"cars\".* FROM \"cars\" WHERE \"cars\".\"owner_id\" = 1 AND \"cars\".\"sold\" = 'f' AND
    # \"cars\".\"electric\" = 't' AND \"cars\".\"sold\" = 'f'"
    p Car.for_owner(1).electric_car.to_sql

    # "SELECT \"cars\".* FROM \"cars\" WHERE \"cars\".\"electric\" = 't' AND \"cars\".\"sold\" = 'f' AND
    #\"cars\".\"owner_id\" = 1 AND \"cars\".\"sold\" = 'f'"
    p Car.electric_car.for_owner(1).to_sql
  end
end
```

**Comment by claptimes5** [comment]
This issue still exists in 5.0.1. I've updated the bug report to use the right version. https://gist.github.com/claptimes5/c815bf0a55858269ce1266e2db15861c

**Comment by roooodcastro** [comment]
This is still an issue with Rails 5.0.3
