### ISSUE TITLE
Deal gracefully with Windows and Action Cable

### ISSUE THREAD

**Issue by dhh** [rails/rails#22725]
It's been mentioned that Action Cable, and in particular EventMachine or Celluloid, might be producing problems on Windows. In the short term, we may well not be able to replace either of these technical underpinnings with a Windows-compatible alternative. So while this may be the case, let's make Action Cable restrict itself gracefully when triggered on Windows. This can be something as simple as showing an error message like "Action Cable is currently not compatible with Windows. Development using this framework needs a OS X or *nix platform" or the like.

**Comment by sgrif** [comment]
EventMachine will install fine with DevKit, though I'm hoping we can drop the need for that soon as it causes issues w/ new devs. It appears that hiredis just flat out doesn't work on Windows.

I do not think showing an error message is sufficient here. I've been doing a lot of work to get the test suite running on Windows, and getting CI set up, etc. Our default stack should "just work" on Windows as well as *nix.

**Comment by dhh** [comment]
"Our default stack should "just work" on Windows as well as *nix." – that's definitely the best outcome. If you're interested in making that so, I'm big 👍 on that.

**Comment by richpeck** [comment]
Can confirm incompatibility with `eventmachine` (due to reliance on `hiredis-rb`) on Windows:

![untitled](https://cloud.githubusercontent.com/assets/1104431/11955062/28bf1e50-a8a6-11e5-92f3-c873334882af.png)

**Comment by dhh** [comment]
Sean just made a fix for that. We're trying to get that into hiredis-rb at
the moment.

**Comment by richpeck** [comment]
Thanks @dhh, do you want me to test any other Windows-compatibility issues?

**Comment by dhh** [comment]
Sean can probably better answer that question. He's motivated to making
Rails 5 a great experience on Windows, and I'm sure he'd love to have help.
Thanks for volunteering!

**Comment by francesco-loreti** [comment]
Any news about this problem?

**Comment by Eric-Guo** [comment]
@francesco-loreti In order to using [hiredis](https://github.com/redis/hiredis-rb) in windows, need c lib [hiredis](https://github.com/redis/hiredis) compile in windows, seems [Relative PR](https://github.com/redis/hiredis/pull/352) is available.

**Comment by francesco-loreti** [comment]
Few minutes ago I can install Hiredis 0.6.1(a new gem version) on windows but rails 5 require 0.5.2 :-(

**Comment by richpeck** [comment]
![untitled](https://cloud.githubusercontent.com/assets/1104431/12038002/3900576a-ae4c-11e5-9d7b-bb06d5c5322c.png)

**Comment by francesco-loreti** [comment]
Yes but you can try "gem install rails --pre" then you have hiredis 0.5.2 error...

**Comment by marcomd** [comment]
Hello Francesco,

you can complete the rails 5 installation in several ways, I just forced the hiredis dependency as I mentioned in the #22914 

A downside is showed when you run the server:

C:\>rails s => Booting Puma
=> Rails 5.0.0.beta1 application starting in development on http://localhost:3000
=> Run `rails server -h` for more startup options
=> Ctrl-C to shutdown server
I, [...]  INFO -- : Celluloid 0.17.2 is running in BACKPORTED mode. [ ... ]
**WARNING: could not load hiredis extension, using (slower) pure Ruby implementation.**
Puma 2.15.3 starting...
...

However, at the moment I still cannot test actionable test due to [a problem with the library libv8](https://github.com/cowboyd/libv8/issues/203)

**Comment by marcomd** [comment]
@dhh 
Often the operating system is imposed without the possibility to choose. I know that windows is not the development platform but I hope you will always get a working version so I hope in the help of the willing as @sgrif.

**Comment by arthurnn** [comment]
Can this be closed now, that we dont depend on event-machine and/or Celluloid?
@matthewd

**Comment by Eric-Guo** [comment]
@arthurnn Yes, I can confirm now Windows platform can developing [Rails 5 chat demo](https://github.com/Eric-Guo/pgac_demo) without problem using PG as backend. Thanks all, you are awesome!

**Comment by marcomd** [comment]
Yes, now it works great!
Just force coffee-script-source to the 1.8.0 version.
