### ISSUE TITLE
On Postgres, values set by triggers are ignored, could be fixed with RETURNING *

### ISSUE THREAD

**Issue by danielalves** [rails/rails#22728]
We use a database first approach, so we have a `structure.sql` that creates the database for us. We also use Postgres' database triggers to set the `created_at` and `updated_at` columns' values (we could use the Rails feature that does so, but since this issue applies for every trigger, please continue reading). So we have something like this:
```sql
-- This method allows the user to set created_at and updated_at by hand if he/she 
-- really needs to do so
CREATE FUNCTION set_timestamps() RETURNS TRIGGER AS $$
    BEGIN
        IF (TG_OP = 'DELETE') THEN
            -- As noted in the postgres docs: "In the case of a before-trigger on DELETE,
            -- the returned value has no direct effect, but it has to be nonnull to allow
            -- the trigger action to proceed. Note that NEW is null in DELETE triggers, so
            -- returning that is usually not sensible. The usual idiom in DELETE triggers is
            -- to return OLD."
            -- See: http://www.postgresql.org/docs/9.4/static/plpgsql-trigger.html
            RETURN OLD;
        END IF;

        IF (TG_OP = 'UPDATE') THEN

            -- MUST NOT update 'created_at'
            NEW.created_at := OLD.created_at;

            IF (NEW.updated_at IS NULL) OR (NEW.updated_at = OLD.updated_at) THEN
                NEW.updated_at := CURRENT_TIMESTAMP;
            ELSIF (NEW.updated_at < OLD.created_at) THEN
                RAISE EXCEPTION '"updated_at" must be equal to or greater than "created_at", but it wasn''t: ''%'' (created_at) - ''%'' (updated_at)', NEW.created_at, NEW.updated_at;
            ELSIF (NEW.updated_at < OLD.updated_at) THEN
                RAISE EXCEPTION 'The new value of "updated_at" must be greater than its old value, but it wasn''t: ''%'' (old) - ''%'' (new)', OLD.updated_at, NEW.updated_at;
            END IF;

        ELSIF (TG_OP = 'INSERT') THEN

            IF (NEW.created_at IS NULL) THEN
                NEW.created_at := CURRENT_TIMESTAMP;
            END IF;

            -- Only when inserting, 'updated_at' MUST equal 'created_at'
            -- After that, it'll always be greater
            NEW.updated_at := NEW.created_at;

        END IF;

        RETURN NEW;
    END;
$$ LANGUAGE plpgsql;

-- Example table
CREATE TABLE games (
    id SERIAL PRIMARY KEY,
    name VARCHAR(64),
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT chk_is_valid_updated_at_timestamp CHECK(updated_at >= created_at)
);
CREATE TRIGGER games_set_timestamp BEFORE INSERT OR UPDATE ON games FOR EACH ROW EXECUTE PROCEDURE set_timestamps();
```
And it works great, as one could verify with `psql`:
```sql
INSERT INTO games(name) VALUES("Fallout 4") RETURNING *;

 id | name       |          created_at          |          updated_at
----+------------+------------------------------+---------------------------------------------
  2 | Fallout 4  | 2015-12-21 16:10:11.84404+00 | 2015-12-21 16:10:11.84404+00
(1 row)
```
But, when using Rails, we do not get these values back after an `INSERT`. This happens because Rails uses the following sql to create an insert:
```
Game.create(name: 'Fallout 4')
   (0.4ms)  BEGIN
  SQL (2.6ms)  INSERT INTO "games" ("name") VALUES ($1) RETURNING "id"  [["name", "Fallout 4"]]
   (1.6ms)  COMMIT
```
And the result object is:
```
#<Game id: 4, name: "Fallout 4", created_at: nil, updated_at: nil>
```
So, it looks like Rails creates an object with the values used in the `create` hash and uses the returned `id`. If instead of using `RETURNING "id"` we started using `RETURNING *`, everything would be fixed. In fact, this result is already achievable if we use this:
```
res = Game.connection.execute("INSERT INTO games(name) VALUES('Fallout 4') RETURNING *;")
Game.new(res[0])
```
So, is this feasible? Does it make sense? I think this approach is better than making an `INSERT` and then a `SELECT` to get the auto generated values.

Thanks in advance.

**Comment by sgrif** [comment]
> Returning a row value different from the original value of NEW alters the row that will be inserted or updated.

PG's docs make no mention of `RETURNING` having any affect on this. Sounds like a bug in Postgres, not Rails. (Also just use a database default for this case?)

**Comment by danielalves** [comment]
@sgrif Sometimes triggers compute values on the fly. In the example I gave, default values would be fine. But, for some triggers, they would not fix the problem. And I don't think it's a bug in neither on them. I think this is just a feature request :smile:

**Comment by sgrif** [comment]
This would increase the memory usage on insert for all Rails apps, so this is not a feature request that we would accept. We also don't take feature requests on the issues tracker, as it's reserved only for bugs. In the future you can post feature requests on the rails-core mailing list.

**Comment by danielalves** [comment]
@sgrif Ok, thanks! I'll just ask about it there :+1:

**Comment by sgrif** [comment]
You don't need to re-raise this specific feature request, as it will not be accepted.

**Comment by danielalves** [comment]
@sgrif Ok, I won't. My only concern was that ActiveRecord is returning values that can be not reflecting what is actually in the DB. From the Postgres docs: `The optional RETURNING clause causes INSERT to compute and return value(s) based on each row actually inserted.`. So, the only way to know the actual column value, is to use `RETURNING *` or to use a `SELECT` after the `INSERT`/`UPDATE`. Of course I understand the memory concern, but I thought there could be a flag for that. Anyway, as I noted, it's easy to workaround that where needed. Again, thanks anyway. :smile:

**Comment by sgrif** [comment]
Yes, I fully understand your point (and [this is the approach diesel takes](https://github.com/sgrif/diesel/blob/master/diesel/src/query_builder/insert_statement.rs#L79-L88)). However, Rails was not designed with triggers in mind, and this would be a decent performance regression on all apps not using triggers in this way.

**Comment by danielalves** [comment]
:+1:
