### ISSUE TITLE
Correct size units in number_to_human_size helper

### ISSUE THREAD

**Issue by avongluck-r1soft** [rails/rails#22733]
This is a continuation of #810 .  number_to_human_size is 1024-base but outputs MB, KB, GB, TB  instead of MiB, KiB, GiB, TiB

**Comment by rafaelfranca** [comment]
It is by design. If you want different units just change in your I18n configuration

**Comment by mystdeim** [comment]
Please what does mean 'by design'. This is wrong according standards!
