### ISSUE TITLE
ActionDispatch::MiddlewareStack equality regression in Rails 5

### ISSUE THREAD

**Issue by nateberkopec** [rails/rails#22738]
The following test passes under Rails 4 and lower, but fails on Rails 5:

```ruby
require 'test_helper'

class WeirdMiddlewareTest < ActiveSupport::TestCase
  def test_what_is_this
    assert_includes  WeirdMiddleware::Application.middleware, Rack::Sendfile
  end
end
```

[Here's the relevant bug report script](https://gist.github.com/nateberkopec/814d8238fdf44d493b6e). It appears the Middleware instance's `klass` is not being set correctly.

**Comment by nateberkopec** [comment]
Hm, I think I may be misunderstanding the cause here, but setting the inline Gemfile to the following *does* make the main test pass:

```ruby
gemfile(true) do
  source 'https://rubygems.org'
  gem 'rails', github: 'rails/rails', branch: "4-2-stable"
  gem 'arel'
  gem 'rack'
  gem 'sprockets'
  gem 'sprockets-rails'
  gem 'sass-rails'
end
```

**Comment by maclover7** [comment]
@nateberkopec Quick question -- are you sure this test
```ruby
def test_is_klass_correct
  assert_equal TestApp.middleware.first.klass, Rack::Sendfile.class
end
```
is accurately testing the functionality? On 4-2-stable for me, this test fails with the error message:

```
  1) Failure:
BugTest#test_is_klass_correct [(irb):42]:
Expected: Rack::Sendfile
  Actual: Class
```

I think the test should be rephrased to look like:
```ruby
def test_is_klass_correct
  assert_equal TestApp.middleware.first.klass, Rack::Sendfile
end
```

Thoughts?

**Comment by rafaelfranca** [comment]
I already have a fix to it. I'll push later

**Comment by nateberkopec** [comment]
@maclover7 Yeah that test was just me trying to figure out what was going wrong, not any statement that it *should* pass on Rails master. I think your rephrase was correct.

**Comment by maclover7** [comment]
@nateberkopec- :+1: 
@rafaelfranca- I ran through git bisect, and found that commit 2a3c47ff5d4ed7391d8a2d02a6baa1f1f55a8df3 introduced the bad behavior, is this where you ended up too?

**Comment by rafaelfranca** [comment]
Fixed
