### ISSUE TITLE
ActiveSupport::Inflector#singularize thinks that the singular of 'slaves' is 'slafe'

### ISSUE THREAD

**Issue by pclalv** [rails/rails#22731]
```
[1] pry(main)> ActiveSupport.version
=> Gem::Version.new("4.2.5")
[2] pry(main)> 'slaves'.singularize
=> "slafe"
```

**Comment by matthewd** [comment]
The inflector is frozen, for backwards compatibility.

You can define a custom inflection in `config/initializers/inflections.rb`.

**Comment by seanhandley** [comment]
@matthewd Do the Rails team have any plans to extract the inflector code out into its own gem?

That way people will be able to pin their inflector gem version in their Gemfiles to preserve compatibility until they can fix their client code.

**Comment by rafaelfranca** [comment]
No. There is no plans for that. Even more that you can define your own inflections rules in your applications.
