### ISSUE TITLE
bin/rake test sets the environment to development

### ISSUE THREAD

**Issue by Speakus** [rails/rails#22741]
Although `bundle exec rake test` - set to test
and `bundle exec rake -v test` - set to test
and `rake test` - also set to test
and `rake -v test` - also set to test
But `bin/rake -v test` sets the environment to development
NB! `bin/rake test` - also sets the environment to test

bin/rake --version == 10.4.2
rake --version == 10.4.2
bundle exec rake --version == 10.4.2
app was created with cmd: `rails new testapp` with rails v.4.2.5

Issue related with #7175 ?

**Comment by rafaelfranca** [comment]
Can you please provide a sample application that reproduces the error?

**Comment by Speakus** [comment]
code to create app:

mkdir tmp
cd tmp
echo 'gem "rails", "4.2.5"' > ./Gemfile
echo '2.2.3' > ./.ruby-version
bundle install
rbenv rehash
bundle exec rails new . --force
bin/rails g scaffold a
bin/rake db:migrate RAILS_ENV=test
sed -i.orig 's+protect_from_forgery with: :exception+puts Rails.env+' ./app/controllers/application_controller.rb

**Comment by Speakus** [comment]
But... i have found one additional important notice:
`bin/rake -v test` - set env to development
but `bin/rake test` - set env to test!
Issue updated

**Comment by rafaelfranca** [comment]
Could you remove spring from your Gemfile? And try it?

**Comment by rafaelfranca** [comment]
(also don't forget to stop it)

**Comment by Speakus** [comment]
commenting gem spring + cmd `spring stop` - solved the issue... Although i can not understand this issue and how can i prevent it in the future...

**Comment by rafaelfranca** [comment]
It is not an issue. Spring preloads you application. You are printing the environment when the application is loaded not when the test is run. At the time the application is loaded spring doesn't know if what you are running is `test` or a `console` command. If you print the environment in any test file you will always see test.

**Comment by Speakus** [comment]
"If you print the environment in any test file you will always see test" - it's not true. I see 'development' in test file same as in application_controller file. But anyway thanx.
