### ISSUE TITLE
Numericality validator broken for string attributes

### ISSUE THREAD

**Issue by twalpole** [rails/rails#22744]
A change to the numerically validator - https://github.com/rails/rails/commit/7500daec69499e4f2da2fc06cd816c754cf59504#diff-58f66170fe2bce77e8a8b3c69b77a0d6L32 - has broken limits checking (greater_than, etc) for string attributes. This happens because the string is no longer cast to a numeric class before being compared - so if we have an attribute with the value "12" and we use greater_than: 1 option we get an "*** ArgumentError Exception: comparison of String with 1 failed" error

**Comment by repinel** [comment]
@twalpole Thanks for finding this
