### ISSUE TITLE
ConnectionSpecification#spec accepts hashes with symbol keys, but #resolve_hash_connection doesn't

### ISSUE THREAD

**Issue by dmolesUC3** [rails/rails#22765]
In [`ConnectionSpecification`](https://github.com/rails/rails/blob/master/activerecord/lib/active_record/connection_adapters/connection_specification.rb), the `spec` method uses `symbolize_keys` to transform string keys to symbols:

```ruby
# lines 167-168
def spec(config)
  spec = resolve(config).symbolize_keys 
```

However, when `config` is a hash argument, `resolve` here calls `resolve_hash_connection`, which expects a string `'url'` key:

```ruby
# lines 237-238
def resolve_hash_connection(spec)
  if spec["url"] && spec["url"] !~ /^jdbc:/
```

This has the effect that `ConnectionHandling#establish_connection`, though documented to take a hash with string keys, will work correctly if passed a hash with symbol keys, *except where* one of those keys is `:url`. This would appear to violate the principle of least surprise.

The ability to accept a symbol-keyed hash is convenient, especially given the simplified Ruby 1.9+ syntax for symbol-keyed hashes. It would be nice if `resolve_hash_connection` was clever enough to handle `{url: 'postgresql://localhost/foo'}` as well as `{'url' => 'postgresql://localhost/foo'}`.

(Noticed in activerecord-4.2.5, but still present in master as of commit fb24d0e.)

**Comment by maclover7** [comment]
Am able to replicate this error -- working on a fix :)

**Comment by maclover7** [comment]
Opened a PR to fix the error here: #22766.

**Comment by rafaelfranca** [comment]
That API only accepts hashes with string keys. If it calls `symbolize_keys` it is a implementation detail of the `spec` method.

**Comment by dmolesUC3** [comment]
@rafaelfranca the API's *documented* to accept hashes with string keys, but what it actually accepts is another matter.

**Comment by rafaelfranca** [comment]
It is hashes with string keys, feel free to make that explicit in the documentation with a PR.
