### ISSUE TITLE
Rails won't work with 3rd party generators

### ISSUE THREAD

**Issue by harisb2012** [rails/rails#22761]
When I run rails g react:install I get Could not find generator react:install. Probably rails5 issue as everything works with rails 4.2.5

**Comment by rafaelfranca** [comment]
Can you please provide a sample application that reproduces the error?

**Comment by harisb2012** [comment]
Just add

gem 'react-rails', '~> 1.5.0'

to gemfile and run

rails g react:install

You will see the error.

**Comment by seuros** [comment]
i can't reproduce it
```
bin/rails g react:install
      create  app/assets/javascripts/components
      create  app/assets/javascripts/components/.gitkeep
      insert  app/assets/javascripts/application.js
      insert  app/assets/javascripts/application.js
      insert  app/assets/javascripts/application.js
      create  app/assets/javascripts/components.js
bin/rails -v
Rails 5.0.0.beta1

**Comment by harisb2012** [comment]
Weird, I'm getting that error constantly

**Comment by rafaelfranca** [comment]
try to stop spring.

**Comment by harisb2012** [comment]
Works without spring! :) Thanks
