### ISSUE TITLE
Heroku slug size changes based on asset_host

### ISSUE THREAD

**Issue by Tonkpils** [rails/rails#22768]
In Rails 4.2.1, when pushing to Heroku, I ran into an issue where removing:

```ruby
config.action_mailer.asset_host = "http://#{DOMAIN}"
config.action_controller.asset_host = '//example.cloudfront.net'
```

causes the slug size to increase, in my case past the limit of 300MB for Heroku.

I tried updating the code to define `config.asset_host = "//example.cloudfront.net"` and the slug size was still over the limit. It seems as if the only configuration that works is the original

Is this expected? What causes this increase if an `asset_host` is not defined?

**Comment by matthewd** [comment]
This sounds like a question for Heroku support.

Otherwise, please use the mailing list or StackOverflow for questions/help, where a wider community will be able to help you. We reserve the issues tracker for issues only.
