### ISSUE TITLE
Timing attack vulnerability in http_basic_authenticate_with

### ISSUE THREAD

**Issue by awgithubuname** [rails/rails#22779]
This block of code will return at different times depending on what you give it for username and password.

```ruby
       module ClassMethods
          def http_basic_authenticate_with(options = {})
            before_action(options.except(:name, :password, :realm)) do
              authenticate_or_request_with_http_basic(options[:realm] || "Application") do |name, password|
                name == options[:name] && password == options[:password]
              end
            end
          end
        end
```

**Comment by schneems** [comment]
Sure it will tell you if you have a valid username but it won't help you figure out the password. In Ruby == does not use a per char comparison so it's not vulnerable to timing attacks. If you're implementing auth you should probably use a secure compare algorithm just incase.

**Comment by simi** [comment]
There's also stale PR https://github.com/rails/rails/pull/16457 for this.
