### ISSUE TITLE
ActiveRecord:Enum scopes don't work when values are assigned

### ISSUE THREAD

**Issue by oguzbilgic** [rails/rails#22774]
When you have an enum with values, such as:
```ruby
class User < ActiveRecord::Base
  enum status: { active: 0, archived: 1, banned: 2 }
end
```

This is suppose to work based on the example on docs:
```ruby
# This queries with status == NULL
User.where.not(status: :banned)
```

This works but very tedious and repetitive:
```ruby
User.where.not(status: User.statuses[:banned])
```

ruby: `2.1.3p242`
rails: `4.2.4`

Thank you

**Comment by rafaelfranca** [comment]
It is how it works in Rails 4.2. In Rails 5 this changed.

**Comment by jameslafa** [comment]
Had the same problem. 

In case you need to filter multiple values, here is a simple solution:
```ruby
User.where.not(status: User.statuses.values_at(:banned, :deleted))
```
