### ISSUE TITLE
Referring attribute x.spec throws error - no implicit conversion of Workflow::Specification into String

### ISSUE THREAD

**Issue by emclab** [rails/rails#22782]
In our Rails 4.2.0/ruby 2.0.0 app with geekq/workflow 1.2.0, there are 2 models order and order_items. order has_many order_items. There is a workflow defined in model order. In order_item table there is a spec attribute which stores product specification (in text) . 

  class Order < ActiveRecord::Base
      include Workflow
      has_many :order_items
  end

  class Order_Item < ActiveRecord::Base
      belong_to :order
  end

Given an order in @order, we did the following in view:

   @order.order_items.map {|x| [x.name + x.spec, x.item_num]}

which should return an array. However the x.spec causes the error below:

   no implicit conversion of Workflow::Specification into String

In debug, here is what it returns for @order.order_items.first.spec

@order.order_items.first.spec = #<Workflow::Specification:0x6a96530>
@order.order_items.first.name = 'Sensor'

It seems that x.spec did not refer the attribute in order_item table but trigger workflow in model order and tried to return Workflow::Specification. In debug we examine the value in order_item and there is a valid text value for spec attribute. 

Why x.spec (x is an order_item) tries to return workflow specification in @order? Is it a bug in rails? I verified that spec is not a keyword in geekq/workflow engine (it is workflow_spec used in workflow engine).

**Comment by rafaelfranca** [comment]
This doesn't look like a rails issue. Please report in the workflow gem

**Comment by emclab** [comment]
The issue was reported in both rails and workflow engine. There is no response from workflow engine yet so far.
