### ISSUE TITLE
Bug - action_view helper sanitize give an extra \n

### ISSUE THREAD

**Issue by longkt90** [rails/rails#22799]
Hi, I have this strange error come up when upgrade from rails 4.1 to 4.2.5 

Do this in rails 4.2.5 console with ruby 2.3.0 
`ActionController::Base.helpers.sanitize("<ul>Test Answer.<li>Item 1</li></ul>", tags: ["ul", "ol", "li", "br", "i", "em", "strike", "p"])`

results:
`"<ul>Test Answer.<li>Item 1</li>\n</ul>"`

frequently: 100%

**Comment by sgrif** [comment]
Since newlines have no affect in HTML, I don't think this is an issue that we need to address.

**Comment by CarlosCD** [comment]
There is still a problem if you are using simple_format (which sanitizes). Those \n characters are transformed into `<br />` and mess up the HTML:

    ActionController::Base.helpers.simple_format("<ul>Test Answer.<li>Item 1</li></ul>")
    => "<p><ul>Test Answer.<li>Item 1</li>\n<br /></ul></p>"

This gets easily out of hand as the amount of HTML you pass to simple_format increases. A test would be:

    ActionController::Base.helpers.simple_format("<ul>Test Answer.<li>Item 1</li><li>Item 2</li></ul>")
    => "<p><ul>Test Answer.<li>Item 1</li>\n<br /><li>Item 2</li>\n<br /></ul></p>"

The `<p>`, `</p>` are the only expected changes.

---
<ul>Test Answer.<li>Item 1</li><li>Item 2</li></ul>
---
versus:

---
<p><ul>Test Answer.<li>Item 1</li><br /><li>Item 2</li><br /></ul></p>
---

**Comment by louiswdavis** [comment]
I am still having this problem:

```
test = "<div>Text 1<br><br>Text 2<br><br></div><ul><li>Item 1</li><li>Item 2</li></ul>"

ActionController::Base.helpers.simple_format(test)
"<p><div>Text 1<br><br>Text 2<br><br>\n<br /></div><ul>\n<br /><li>Item 1</li>\n<br /><li>Item 2</li>\n<br /></ul></p>"
```

And as previously mentioned those "\n" characters are transformed into <br> tags creating extra line breaks

**System configuration**

Rails version: 7.0.1
Ruby version: 3.1.3

**Comment by skipkayhil** [comment]
Can you open a new issue if you are still having a problem?
