### ISSUE TITLE
Why can't we use cache in email templates?

### ISSUE THREAD

**Issue by st0012** [rails/rails#22798]
Hi, I notice that we can't use fragment cache in `ActionMailer`'s email template. I am curious about the reason that Rails doesn't implement this feature.
Is it because nobody needs this feature (actually I quite need it)? Or is because the cache implementation is coupled too deep with `ActionController` and it's hard to move it to `AbstractController` which `ActionMailer` uses?

**Comment by sgrif** [comment]
This kind of question should probably go on the Rails Core mailing list. We reserve the issues tracker for bugs only (e.g. something used to work in Rails 4 but is broken in Rails 5)
