### ISSUE TITLE
Rails server error

### ISSUE THREAD

**Issue by luispaulobrito** [rails/rails#22793]
When I'm trying run the server to programmingin Rails I have this result and the server dont run.

$ rails s
c:/RailsInstaller/Ruby2.1.0/lib/ruby/gems/2.1.0/gems/actionpack-4.1.8/lib/action
_controller/metal/strong_parameters.rb:106: warning: already initialized constan
t ActionController::Parameters::NEVER_UNPERMITTED_PARAMS
c:/RailsInstaller/Ruby2.1.0/lib/ruby/gems/2.1.0/gems/actionpack-4.1.8/lib/action
_controller/metal/strong_parameters.rb:106: warning: previous definition of NEVE
R_UNPERMITTED_PARAMS was here
c:/RailsInstaller/Ruby2.1.0/lib/ruby/gems/2.1.0/gems/actionpack-4.1.8/lib/action
_controller/metal/strong_parameters.rb:106: warning: already initialized constan
t ActionController::Parameters::NEVER_UNPERMITTED_PARAMS
c:/RailsInstaller/Ruby2.1.0/lib/ruby/gems/2.1.0/gems/actionpack-4.1.8/lib/action
_controller/metal/strong_parameters.rb:106: warning: previous definition of NEVE
R_UNPERMITTED_PARAMS was here
c:/Users/LuÃ­sPaulo/Desktop/sample_app/config/application.rb:7:in `<top (require
d)>': uninitialized constant Bundler (NameError)
        from c:/RailsInstaller/Ruby2.1.0/lib/ruby/site_ruby/2.1.0/rubygems/core_
ext/kernel_require.rb:126:in `require'
        from c:/RailsInstaller/Ruby2.1.0/lib/ruby/site_ruby/2.1.0/rubygems/core_
ext/kernel_require.rb:126:in `require'
        from c:/RailsInstaller/Ruby2.1.0/lib/ruby/gems/2.1.0/gems/railties-4.1.8
/lib/rails/commands/commands_tasks.rb:79:in `block in server'
        from c:/RailsInstaller/Ruby2.1.0/lib/ruby/gems/2.1.0/gems/railties-4.1.8
/lib/rails/commands/commands_tasks.rb:76:in `tap'
        from c:/RailsInstaller/Ruby2.1.0/lib/ruby/gems/2.1.0/gems/railties-4.1.8
/lib/rails/commands/commands_tasks.rb:76:in `server'
        from c:/RailsInstaller/Ruby2.1.0/lib/ruby/gems/2.1.0/gems/railties-4.1.8
/lib/rails/commands/commands_tasks.rb:40:in `run_command!'
        from c:/RailsInstaller/Ruby2.1.0/lib/ruby/gems/2.1.0/gems/railties-4.1.8
/lib/rails/commands.rb:17:in `<top (required)>'
        from c:/RailsInstaller/Ruby2.1.0/lib/ruby/site_ruby/2.1.0/rubygems/core_
ext/kernel_require.rb:135:in `require'
        from c:/RailsInstaller/Ruby2.1.0/lib/ruby/site_ruby/2.1.0/rubygems/core_
ext/kernel_require.rb:135:in `rescue in require'
        from c:/RailsInstaller/Ruby2.1.0/lib/ruby/site_ruby/2.1.0/rubygems/core_
ext/kernel_require.rb:144:in `require'
        from bin/rails:4:in `<main>'

**Comment by eileencodes** [comment]
Hi @luispaulobrito I think you need to install bundler first since you have the error `uninitialized constant Bundler (NameError)`.
