### ISSUE TITLE
Session : Symbols hash keys getting converted to literals keys in next request (Rails 4.2.3

### ISSUE THREAD

**Issue by atul-shimpi** [rails/rails#22796]
Steps
1] Request 1 - i am storing hash in session
session[:links_history] << { title: 'All Buckets', url: request.original_url }
inspect : [{:title=>"All Buckets", :url=>"http://0.0.0.0:3000/buckets/src-ruby"}]

2] Request 2 
inspect = [{"title"=>"All Buckets", "url"=>"http://0.0.0.0:3000/buckets"}]

As you can see, symbols keys are getting converted to literals keys.

I guess, this may not be issue with rails, but the way data is stored in session.
If so, we should have some way to inform user about not storing symbols in session.

**Comment by dmitry** [comment]
https://github.com/rails/rails/blob/ea4f0e2baba8653b03fba154357842933cf7b778/actionpack/lib/action_dispatch/middleware/session/cookie_store.rb#L97

**Comment by sgrif** [comment]
This is the expected behavior

**Comment by atul-shimpi** [comment]
If this is expected behavior, then it should be consistent. Its having different behaviour in the same request and different is next request.

**Comment by rafaelfranca** [comment]
The session object is stored in the cookies as JSON objects and JSON don't
know what is a symbol, only string. In the same request your session object
was not yet serialized, and this is why you get the symbols in the hash. As
soon your session is sent to the browser and return back it only know about
JSON compatible types.
