### ISSUE TITLE
Undefined method 'deprecate' for ActiveSupport::NumericWithFormat:Module

### ISSUE THREAD

**Issue by jasnow** [rails/rails#22805]
Undefined method 'deprecate' for ActiveSupport::NumericWithFormat:Module

Steps to reproduce:
 1. Using repo https://github.com/jasnow/photish5 (with .rvmrc's Ruby
    set to 2.3.0 and Rails 5 (beta1), run "bundle" then run "rake" and you get this:
```
       ".../.rvm/gems/ruby-2.3.0@ruby2.3.0-rails4.2/gems/
       activesupport-5.0.0.beta1/lib/active_support/core_ext/
       numeric/conversions.rb:127:in `<module:NumericWithFormat>':
       undefined method `deprecate' for
       ActiveSupport::NumericWithFormat:Module (NoMethodError)
       Did you mean?  deprecate_constant
         delegate
       from .../.rvm/gems/ruby-2.3.0@ruby2.3.0-rails4.2/gems/
       activesupport-5.0.0.beta1/lib/active_support/core_ext/
       numeric/conversions.rb:4:in `<top (required)>'
       from /home/jasnow/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/
       rubygems/core_ext/kernel_require.rb:55:in `require'
```
 2. When you can change .rvmrc from 2.3.0 to 2.2.4 and Rails 5 (beta1) and repeat step 1, "rake" works (no error).

**Comment by prathamesh-sonpatki** [comment]
Not able to reproduce it with given steps. `rake` command works for me. Am I missing something?

**Comment by jasnow** [comment]
Yes, I can't reproduce it now either. I see that I use "activesupport-5.0.0.beta1" above but can't get that to occur so I will close this ticket for now. Thanks @prathamesh-sonpatki

**Comment by jasnow** [comment]
@prathamesh-sonpatki - Copied repo to https://github.com/jasnow/photish5
and changed gemfile and .rvmrc to Rails 5 and now I see the error again.
Can you check this? If you can reproduce it, then we can reopen this issue.
Thanks.

**Comment by jasnow** [comment]
Changed copied repo (using Rails 5 and Ruby 2.3.0) and modified above description.

**Comment by maclover7** [comment]
I feel like the issue is that [`active_support/core_ext/module/deprecation.rb`](https://github.com/rails/rails/blob/master/activesupport/lib/active_support/core_ext/module/deprecation.rb) is not being required, so that makes the `deprecate` method undefined. Thoughts?

**Comment by rafaelfranca** [comment]
@maclover7 that is true. Could you send a pull request?

**Comment by maclover7** [comment]
Opened up #228222.

**Comment by jasnow** [comment]
How to I specify edge activesupport so I can verify this in above project (https://github.com/jasnow/photish5)? PR is welcome. Thanks.
