### ISSUE TITLE
Generate an specified version of rails.

### ISSUE THREAD

**Issue by jcoyne** [rails/rails#22816]
It seems odd that when I use a specific version of `bin/rails`, it generates rails for the newest available rails rather than the version I have specified.

```
$ gem list rails

*** LOCAL GEMS ***

rails (5.0.0.beta1, 4.2.5)
$ /Users/justin/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/railties-4.2.5/bin/rails new my_app
```

```
$ head -5 my_app/Gemfile
source 'https://rubygems.org'


# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '>= 5.0.0.beta1', '< 5.1'
```

**Comment by rafaelfranca** [comment]
I could not reproduce using the right API to ask for an specific version in rubygems:

```
$ gem list rails

*** LOCAL GEMS ***
rails (5.0.0.beta1, 4.2.5, 4.2.2)
```

```
$ rails _4.2.5_ new ~/foo

$ head -5 ~/foo/Gemfile
source 'https://rubygems.org'


# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '4.2.5'
```

**Comment by jcoyne** [comment]
@rafaelfranca that's not documented in the usage message. Should it be?

```
$ rails --help
Usage:
  rails new APP_PATH [options]
...
```

**Comment by rafaelfranca** [comment]
That is from RubyGems, so I think it should be documented there https://github.com/rubygems/rubygems/blob/abf89e04954b8a2ddfb6948d0860111990a6efa2/lib/rubygems/installer.rb#L669
