### ISSUE TITLE
Regression? ActionController::Parameters no longer responds to `#include?` or `#collect`

### ISSUE THREAD

**Issue by jcoyne** [rails/rails#22818]
Also `#except!`
Due to https://github.com/rails/rails/commit/14a3bd520dd4bbf1247fd3e0071b59c02c115ce0

Was it necessary to remove these read-only methods?  I have gems depending on them.

**Comment by rafaelfranca** [comment]
I don't think we need to support all hash methods in `Parameters` I want to keep the API surface small. It is a bad idea to implement `except!` since it is a mutating method and I don't see any usage for `map`/`collect` that can't be handled getting the unsafe hash. I'm fine with `include?` though.

**Comment by jcoyne** [comment]
@rafaelfranca isn't `except!` just a subcase of `extract!`?  We have the latter, why not the former?

**Comment by rafaelfranca** [comment]
Mainly because of is a whitelist (`extract!`) and other is a blacklist. Blacklisting in `Parameters` is a bad idea security-wise.

**Comment by jcoyne** [comment]
@rafaelfranca `extract!` is a whitelist in it's return value, but a blacklist in its side effect (remove the keys from the original)
