### ISSUE TITLE
AC::Parameters doesn't compare (==) in a sane way

### ISSUE THREAD

**Issue by jcoyne** [rails/rails#22820]
```
ActionController::Parameters.new(foo: 'bar') == ActionController::Parameters.new(foo: 'bar')
=> false
```

Compare to:

```
{ foo: 'bar' } == { foo: 'bar' }
=> true
```

Why is this behavior different?

**Comment by eileencodes** [comment]
This looks like a dup of #21032. Closing in favor of that one.

**Comment by jcoyne** [comment]
:+1:

**Comment by jacobat** [comment]
This bug is still relevant and not a dupe of #21032 which was closed via #23167 which in turn makes it possible to do `params == hash` but not `params == params`. Please reopen.

**Comment by eileencodes** [comment]
You're right, thanks for pointing out the difference. cc/ @sikachu is this a known issue with the parameters changes? 

```
>> ActionController::Parameters.new(foo: 'bar') == ActionController::Parameters.new(foo: 'bar')
=> false
```

**Comment by sikachu** [comment]
Looks like @bquorning is about to fix that in #23733, so I'm going to close this. Thank you for reporting in.

**Comment by eileencodes** [comment]
@sikachu isn't that different? That's for comparing to a hash, this is for comparing a parameter to a parameter.

**Comment by sikachu** [comment]
@eileencodes: @bquorning found a bug on comparing Parameters as well, and he'll address that in his PR (with proper failing test case!)

**Comment by eileencodes** [comment]
Ah ok thanks for clarifying

**Comment by bquorning** [comment]
Yeah, I should probably have made two separate pull requests. But with Rails 5 rc1 right around the corner, I had to move fast :-)
