### ISSUE TITLE
Deprecation warning for time_zone_aware_types (<<)

### ISSUE THREAD

**Issue by cllns** [rails/rails#22839]
In [time_zone_conversion.rb](https://github.com/rails/rails/blob/08780eff79f93f5741dc80fb1fb1a091b9a9c94e/activerecord/lib/active_record/attribute_methods/time_zone_conversion.rb) it says:
```
To silence this deprecation warning, add the following:

    config.active_record.time_zone_aware_types << :time
```
Which is something that all users who have a `time` field will see.

If you do this, you get an error:
```
NoMethodError: undefined method `<<' for nil:NilClass
```
Because that key doesn't exist by default in the base `application.rb` config.

One easy solution is changing that line to use `=` instead of `<<`
```
    config.active_record.time_zone_aware_types = [:time, :datetime]
```

But savvy users might try to use `<< :time` anyway, and be surprised it doesn't work? Not sure if that use-case is worth considering. If it is...

The more involved solution would be setting that value in the base config: `application.rb`.
( I think that might happen [here](https://github.com/rails/rails/blob/master/activerecord/lib/active_record/railtie.rb)?)  But then you still have to signify `not explicitly configured` somehow, which would be a weird symbol to see in the array if people pushed things onto the end. I guess you could just use `[nil]` to signify that, but that feels weird too.

I wonder if it might be easier to switch from using a single array to using two booleans? This would be a breaking change, but it might be more elegant.

So, by default:
```
  config.active_record.time_zone_aware_time_type: nil
  config.active_record.time_zone_aware_datetime_type: true
```
That way you can leverage three-state logic (and `.nil?` on the first boolean) rather than dealing with arrays. The code for `time_zone_aware_attributes` will have to be update as well.

Thoughts? @sgrif

**Comment by prathamesh-sonpatki** [comment]
I think according to current code 

```ruby
              To keep the old behavior, you must add the following to your initializer:

                  config.active_record.time_zone_aware_types = [:datetime]

              To silence this deprecation warning, add the following:

                  config.active_record.time_zone_aware_types << :time
```

Should be changed to 

``` ruby
              To keep the old behavior, you must add the following to your initializer:

                 ActiveRecord::Base.time_zone_aware_types = [:datetime]

              To silence this deprecation warning, add the following:

                 ActiveRecord::Base.time_zone_aware_types << :time
```

But it might not be original intent as we want to allow user to handle this situation using `config.active_record.time_zone_aware_types`.

**Comment by matthewd** [comment]
The warning should be corrected to use an assignment. AFAICS, even if you could do the append, it wouldn't make the message go away.
