### ISSUE TITLE
table name error

### ISSUE THREAD

**Issue by zerobatu** [rails/rails#22838]
Hi
I have this model:

class ConsultantInterview::Report < ActiveRecord::Base
  mount_uploader :document, GenericReportStageUploader

  after_commit :touch_enrollment, on: [:create, :update]
  belongs_to :consultant_interview_stage,
             class_name: ConsultantInterview::Stage,
             foreign_key: :consultant_interview_stage_id

  validates :document, presence: true
  validates :observations, presence: true
  validates :consultant_interview_stage, presence: true

  def touch_enrollment
    self.consultant_interview_stage.touch_enrollment
  end
end

and when I try to create a new instance return this error:

PG::UndefinedTable: ERROR: relation "reports" does not exist LINE 5: WHERE a.attrelid = '"reports"'::regclass ^ : SELECT a.attname, format_type(a.atttypid, a.atttypmod), pg_get_expr(d.adbin, d.adrelid), a.attnotnull, a.atttypid, a.atttypmod FROM pg_attribute a LEFT JOIN pg_attrdef d ON a.attrelid = d.adrelid AND a.attnum = d.adnum WHERE a.attrelid = '"reports"'::regclass AND a.attnum > 0 AND NOT a.attisdropped ORDER BY a.attnum

I test this in the console:

2.2.2 :024 > ConsultantInterview::Report.table_name
 => "reports"

I can solved this adding this in the model:

class ConsultantInterview::Report < ActiveRecord::Base
  self.table_name = "consultant_interview_reports"

But don't know why is this happening

**Comment by maclover7** [comment]
Can reproduce this locally. I think the issue here is that ActiveRecord is getting the table name `reports` from the ConsultantInterview::**Report** part of ConsultantInterview::Report. Not sure if this is intended behavior or not. If you want to investigate further it looks like the table_name method is defined [here](https://github.com/rails/rails/blob/master/activerecord/lib/active_record/model_schema.rb#L121). cc @sgrif

**Comment by rafaelfranca** [comment]
That is the expected behavior. The table name doesn't take the module namespacing in consideration.

**Comment by rafaelfranca** [comment]
You can find about that in the `table_name` documentation. http://api.rubyonrails.org/classes/ActiveRecord/ModelSchema/ClassMethods.html#method-i-table_name
