### ISSUE TITLE
AC::Parameters should be mergeable with another AC::Parameters

### ISSUE THREAD

**Issue by jcoyne** [rails/rails#22835]
```ruby
ActionController::Parameters.new.merge(ActionController::Parameters.new)
*** NoMethodError Exception: undefined method `to_hash' for {}:ActionController::Parameters
```

For context, this occurs here in Kaminari:
https://github.com/amatsuda/kaminari/blob/0dce6b609642c5ab505a5472a6215519c1685f74/lib/kaminari/helpers/tags.rb#L23

**Comment by rafaelfranca** [comment]
I don't think it is a good idea. What should be the behavior? If the original parameter is already permitted should the permit flag be maintained or should it be set to false so users should permit again?

If it is the former we may introduce security problems.

**Comment by jcoyne** [comment]
Okay, It does work if I pass `params: params.to_unsafe_h`, I was just hoping there'd be a way to write this so that it would work for Rails 4 and 5.
