### ISSUE TITLE
New Rails 5 app won't "Welcome Aboard!"; 500's instead

### ISSUE THREAD

**Issue by dcromer** [rails/rails#22837]
I'm excited about Rails 5 and want to play around with it, but I'm unable to even view the "Welcome Aboard!" page you should see when generating a new rails app.  Instead, I get a 500 error, and the only line in the logs is:

`Started GET "/" for 127.0.0.1 at 2015-12-29 15:21:01 -0800`

There are no other log messages whatsoever.

**Reproduce**

I am on OSX El Capitan, and have tried on Ruby 2.2.2.  I regularly work with Rails 4.2.x

1) Generate a new rails app
`gem install rails -v 5.0.0.beta1`
`rails new myapp`
`cd myapp`

2) Edit the gemfile; `gem 'rails', '5.0.0.beta1'`

3) Hit the server
```
› curl -I localhost:3000
HTTP/1.1 500 Internal Server Error
Content-Type: text/html; charset=utf-8
Content-Length: 1477
...
```

As mentioned above, there is no detail about the error in the server console nor logs.  Running the server in production mode produces the same problem with no additional detail.

For thrills I've tried both bundler 1.10.6 and 1.11.2, as well as WEBrick, puma, and thin.

**Related Issues**

I've seen this posted on [the Ruby On Rails: Talk Google Group](https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/rubyonrails-talk/Ouccsxuw7q4/YeIk6izKDQAJ) but there was no resolution, yet.

**Comment by maclover7** [comment]
Weird -- just ran the following commands and didn't get any errors when going to '/':

```
gem install rails -v 5.0.0.beta1
rails _5.0.0.beta1_ new myapp
cd myapp
bundle exec rails s
```

It's possible that when you were generating a Rails app, that you didn't add the `_5.0.0.beta1` to the command. This specifies that you want to use the Rails 5.0.0.beta1 command line interface.

**Comment by rafaelfranca** [comment]
Yes, exactly that. RubyGems doesn't let you activate a pre release unless you explicitly ask to. And to do so you need to use the `_VERSION_` in the command.

**Comment by dcromer** [comment]
Excellent!  Thank you, @maclover7 @rafaelfranca
