### ISSUE TITLE
AC::Parameters#to_unsafe_h does not deep dup 

### ISSUE THREAD

**Issue by jcoyne** [rails/rails#22841]
```ruby
foo = ActionController::Parameters.new("f"=>{"language_facet"=>["Tibetan"]})
{"f"=>{"language_facet"=>["Tibetan"]}}
foo['f'].class
ActionController::Parameters
foo.to_unsafe_h
{"f"=>{}}
```

I would think you'd get back `{'"f"=>{"language_facet"=>["Tibetan"]}}`, right?

**Comment by prathamesh-sonpatki** [comment]
I think it is happening because we have not `permitted` any params

``` ruby
$ rails c
Loading development environment (Rails 5.0.0.beta1)
>> foo = ActionController::Parameters.new("f"=>{"language_facet"=>["Tibetan"]})
=> {"f"=>{"language_facet"=>["Tibetan"]}}
>> foo['f'].class
=> ActionController::Parameters
>> foo.to_unsafe_h
=> {"f"=>{}}
>> foo.permit!.to_unsafe_h
=> {"f"=>{"language_facet"=>["Tibetan"]}}
>> 

```

This works when we permit the params.

**Comment by prathamesh-sonpatki** [comment]
Another interesting thing that I observed was

``` ruby
>> foo = ActionController::Parameters.new("f"=>{"language_facet"=>["Tibetan"]})
=> {"f"=>{"language_facet"=>["Tibetan"]}}
>> foo.to_unsafe_h
=> {"f"=>{"language_facet"=>["Tibetan"]}}
>> 
```

And when we access `foo['f']` then we start seeing empty hash as return value. Check below sequence -

``` ruby
>> foo = ActionController::Parameters.new("f"=>{"language_facet"=>["Tibetan"]})
=> {"f"=>{"language_facet"=>["Tibetan"]}}
>> foo.to_unsafe_h
=> {"f"=>{"language_facet"=>["Tibetan"]}}
>> foo['f']
=> {"language_facet"=>["Tibetan"]}
>> foo.to_unsafe_h
=> {"f"=>{}}
>> 
```

I did not get why it's working like that :)

**Comment by jcoyne** [comment]
@prathamesh-sonpatki  you are right. If you permit the params they are returned from `to_unsafe_h` I assumed the method would return *all* params even those that are not permitted because the method documentation says:

> Returns an unsafe, unfiltered ActiveSupport::HashWithIndifferentAccess representation of this parameter.

whereas the documentation for AC::Parameters#to_h says:

> Returns a safe ActiveSupport::HashWithIndifferentAccess representation of this parameter with all unpermitted keys removed.

In any case, accessing the values should not change the output of `to_unsafe_h`

**Comment by prathamesh-sonpatki** [comment]
@jcoyne I think we will have to fix documentation of `to_unsafe_h`. Let somebody from core team confirm.

**Comment by jcoyne** [comment]
@prathamesh-sonpatki negative. I really need a way to get at *all* parameters. My inclination is to fix to_unsafe_h to match the documentation.

**Comment by prathamesh-sonpatki** [comment]
oh ok. I got what you are trying to say. `unfiltered & unsafe` :)

**Comment by prathamesh-sonpatki** [comment]
> In any case, accessing the values should not change the output of to_unsafe_h

We need to fix this case. Otherwise `to_unsafe_h` works as expected.
