### ISSUE TITLE
quoted_id failing

### ISSUE THREAD

**Issue by ffmike** [rails/rails#22847]
Rails 4.2.5:
[1] pry(main)> r = Restaurant.first
[2] pry(main)> r.quoted_id
=> "2"

Rails 5.0:
[1] pry(main)> r = Restaurant.first
[2] pry(main)> r.quoted_id
NoMethodError: private method `quote_value' called for #<Class:0x007f801cb24ca8>
Did you mean?  quote_bound_value

quoted_id is marked "# TODO: Deprecate this" in sanitization.rb, but it's still called internally in connection_adapters/abstract/quoting.rb

I can "fix" by patching the definition of quoted_id:

    def quoted_id
      self.class.send(:quote_value, @attributes[self.class.primary_key].value_for_database)
    end

But I doubt that's the right fix given the underlying changes in arel.

**Comment by maclover7** [comment]
Am not able to reproduce on master -- here's a script I used:

```ruby
begin
  require 'bundler/inline'
rescue LoadError => e
  $stderr.puts 'Bundler version 1.10 or later is required. Please update your Bundler'
  raise e
end

gemfile(true) do
  source 'https://rubygems.org'
  gem 'rails', github: 'rails/rails'
  gem 'arel', github: 'rails/arel'
  gem 'rack', github: 'rack/rack'
  gem 'sprockets', github: 'rails/sprockets'
  gem 'sprockets-rails', github: 'rails/sprockets-rails'
  gem 'sass-rails', github: 'rails/sass-rails'
end

require 'action_controller/railtie'
require 'minitest/autorun'

class TestApp < Rails::Application
  config.root = File.dirname(__FILE__)
  config.session_store :cookie_store, key: 'cookie_store_key'
  secrets.secret_token    = 'secret_token'
  secrets.secret_key_base = 'secret_key_base'

  config.logger = Logger.new($stdout)
  Rails.logger  = config.logger
end

ActiveRecord::Base.establish_connection(adapter: 'sqlite3', database: ':memory:')
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :restaurants, force: true do |t|
    t.string :name
  end
end


class Restaurant < ActiveRecord::Base
end

class BugTest < Minitest::Test
  def test_stuff
    Restaurant.create!(name: 'hi')
    r = Restaurant.first
    assert_equal "1", r.quoted_id
    end
end
```

**Comment by ffmike** [comment]
False alarm. The actual issue, for anyone else who hits this, is in acts_as_taggable_on. I'll take it up with them.

**Comment by rafaelfranca** [comment]
Thank you for confirming.

**Comment by rafaelfranca** [comment]
BTW, that method is not public API. It was made public API by mistake in https://github.com/rails/rails/commit/539b69e0. Due to it being dangerous I don't recommend to override it.

**Comment by ffmike** [comment]
Yeah, I wasn't. The problem is that the current acts_as_taggable_on alpha overrides quote_value to be private so that the call from quoted_id, which is called from elsewhere in activerecord, fails.

**Comment by rafaelfranca** [comment]
I see. Yeah, that is fine :+1:
