### ISSUE TITLE
respond_to with empty block should raise MissingTemplateError if no template exists for that format.

### ISSUE THREAD

**Issue by jcoyne** [rails/rails#22852]
In Rails 4.2.5 if I do nothing in a respond to block and there is no template for that format, I get a `ActionView::MissingTemplate` error.  In Rails 5.0.0.beta1, no error is thrown, and the server returns a 500 error.  No stacktrace is in the log.

## Setup
```ruby
class PiratesController < ApplicationController
  def show
    respond_to do |format|
      format.yaml { }
    end
  end
end
```

## Test
In Rails 5.0.0.beta1
```
$ curl http://localhost:3000/pirates/1.yaml
---
:status: 500
:error: Internal Server Error
```
No HTML page is returned.

In Rails 4.2.5
```
curl http://localhost:3000/pirates/1.yml
<!DOCTYPE html>
<html>
<head>
  <title>We're sorry, but something went wrong (500)</title>
...
```
This HTML shows the error and the stack trace. This message is in the log: https://gist.github.com/jcoyne/22c430b459467039b8e5

**Comment by rafaelfranca** [comment]
As far I remember this is by design (see https://github.com/rails/rails/pull/20831). The error page is now presented in the same format that it was requested if you are using Rails API. But, the exception should in the log, so that is a bug indeed

**Comment by jcoyne** [comment]
It looks like requesting the HTML page in Rails 5.0.0.beta1 also doesn't give an error message.  The HTML that is rendered says simply:

> We're sorry, but something went wrong. If you are the application owner check the logs for more information.

Nothing useful is in the logs indicating a missing template.

**Comment by shakycode** [comment]
@jcoyne I am able to duplicate the same behavior with 5.0.0.beta1 and Ruby 2.2.3 in development.

**Comment by jcoyne** [comment]
I did some further testing and this particular error only shows up when I upgrade a 4.2.5 app to 5.0.0.beta1.

In an application generated by `rails _5.0.0.beta1 new` I get this in the logs:

```
Started GET "/pirates/1.yaml" for ::1 at 2015-12-30 11:26:33 -0600
Processing by PiratesController#show as YAML
  Parameters: {"id"=>"1"}
No template found for PiratesController#show, rendering head :no_content
Completed 204 No Content in 2ms (ActiveRecord: 0.0ms)
```

But shouldn't this raise an error? Rather than very quietly succeeding?

**Comment by jcoyne** [comment]
I guess this is the expected behavior per https://github.com/rails/rails/commit/6c165773117dc7e60f5bb4762e58c7c522d69fcc
