### ISSUE TITLE
Unknown format should return 404 rather than 204

### ISSUE THREAD

**Issue by jcoyne** [rails/rails#22853]
In Rails 5.0.0.beta1.  When I have a PiratesController, with a show action and I run:
```
$ curl -I http://localhost:3000/pirates/1.foobar
HTTP/1.1 204 No Content
```
It seems that a 404 response is more appropriate in this case.

**Comment by jcoyne** [comment]
@spastorino I think this was changed as a result of your changes in #19832.  Would you care to comment on the desired behavior?

**Comment by rafaelfranca** [comment]
Actually this is due to https://github.com/rails/rails/issues/19036 and this is a dup of https://github.com/rails/rails/issues/20666
