### ISSUE TITLE
Missing documentation on manifest.js

### ISSUE THREAD

**Issue by jeroenvisser101** [rails/rails#22867]
As far as I can see, documentation is missing on the `config/initializers/assets.rb` file, since this part:

``` ruby
# Precompile additional assets.
# application.js, application.css, and all non-JS/CSS in app/assets folder are already added.
# Rails.application.config.assets.precompile += %w( search.js )
```

seems obsolete by the introduction of Sprockets 4 and `manifest.js`.

**Comment by maclover7** [comment]
cc @schneems

**Comment by schneems** [comment]
Rails 5 uses Sprockets 3.

**Comment by jeroenvisser101** [comment]
@schneems I'm sorry, I meant that. I've updated the issue, but the issue still persists, that it seems obsolete since we now use `manifest.js` for these paths.

**Comment by schneems** [comment]
Are you running sprockets from master?

**Comment by k0kubun** [comment]
> Rails 5 uses Sprockets 3.

@schneems While @eileencodes said "When Rails 5 is released it will require that you upgrade to Sprockets 4" in http://eileencodes.com/posts/the-sprockets-4-manifest/, will Rails 5.0.0 be allowed to be installed with Sprockets 3.x?

**Comment by schneems** [comment]
Yes you should still be able to use sprockets 3.

**Comment by k0kubun** [comment]
> Yes you should still be able to use sprockets 3.

I see. Thank you!
