### ISSUE TITLE
Guide issue: 'Functional Tests for your Controllers'

### ISSUE THREAD

**Issue by cllns** [rails/rails#22862]
The section for ['Functional Tests for your Controllers'](http://edgeguides.rubyonrails.org/testing.html#functional-tests-for-your-controllers) contains an issue if the user is working with their code from the 'Getting Started' guide.

The text supports creating the tests from:
1. the `scaffold_controller` generator
2. the `test_unit:scaffold` generator, which adds only testing scaffold. 

Case **1** is fine. The problem is with **2**.
Specifically, if the user is using their code from 'Getting Started' and they went through until the last section, where HTTP Basic authentication (and authorization) is added.

The end of this section says, if you follow the step to modify one test, then **'you can try running all the tests and they should pass.'** but that's not true if they set up authentication.

Possible solutions:

**A**) Add a note after `test_unit:scaffold` command about removing the `http_basic_authenticate_with name: "dhh", password: "secret"` lines from ArticlesController and CommentsController.

**B**) Add a note about adding the following to the `setup` block:

```
request.headers['Authorization'] = ActionController::HttpAuthentication::Basic.
  encode_credentials('dhh', 'secret')
```

| Solutions | Pro | Con |
| --- | --- | --- |
| **A** | simpler | might give impression that testing can't deal with authentication |
| **B** | more complete, retains security | not sure where it would go, since it only affects some readers |

I'd be happy to implement do either. Just let me know which approach you think is better.

**Comment by vipulnsward** [comment]
Option B, may look out of the way, but it completes the context. So :+1: for it.

**Comment by kaspth** [comment]
Fat fingered, sorry!

**Comment by vtorves** [comment]
@cllns I think the X option is the best way.

**Comment by vipulnsward** [comment]
@cllns would you like to open a PR with suggest change?

**Comment by prathamesh-sonpatki** [comment]
@cllns Hey, still interested in sending PR to fix this? Thanks!

**Comment by maclover7** [comment]
Closing since #27204 was merged.
