### ISSUE TITLE
raise_in_transactional_callbacks = true does not work in rspec and rails c --sandbox

### ISSUE THREAD

**Issue by elpdspec** [rails/rails#22865]
Just added the option `raise_in_transactional_callbacks = true` and it is working in the rails c. But in rails c --sandbox and also when running a spec with rspec, I don't get an expection. Is that the expected behavior ?

**Comment by rafaelfranca** [comment]
Yes, it is. You `after_commit` callbacks never run in sandbox (because all commands are wrapped in a transaction) and in rspec too (since every test is wrapped in a transaction).
