### ISSUE TITLE
Rails 5.0.0.beta1 exiting rails console issue

### ISSUE THREAD

**Issue by lohqua** [rails/rails#22879]
ctrl-c looks like it exited to bash but did not. Any bash command throw rails errors.

Typing exit works after 10 seconds(not always) with this message ERROR -- : Couldn't cleanly terminate all actors in 10 seconds!

Also, rails console doesn't automatically make a connect to postgres. I have to type ModelName.connection to force it to connect.

**Comment by maclover7** [comment]
Can you please provide a sample application that reproduces the error?

**Comment by rafaelfranca** [comment]
> Also, rails console doesn't automatically make a connect to postgres. I have to type ModelName.connection to force it to connect.

That is expected. It doesn't connect until you explicitly ask to, or you do any database operation.

**Comment by lohqua** [comment]
> That is expected. It doesn't connect until you explicitly ask to, or you do any database operation.

Been using Rails since 1.2 and that has *never* been the case. I could just do ModelName.find 2 and it would work.

**Comment by rafaelfranca** [comment]
> I could just do ModelName.find 2 and it would work.

That is still true.

**Comment by lohqua** [comment]
>Can you please provide a sample application that reproduces the error?

rails new my_app
cd my_app
rails c
ctrl-c
type anything, say ls

This with Linux, more specifically open suse 42

**Comment by gokulnath** [comment]
Rails console doesn't exit on typing ctrl-c normally.
In my ubuntu 14.04 using 5.0.0.beta1 it doesn't exit (same as for 4.2.5). And I saw the same behavior in SUSE Linux Enterprise Server 12 in AWS.

Or did you use ctrl-z, which is supposed to push console into background, but have the issues you just raised.

**Comment by unfunco** [comment]
@lohqua – both Rails 4.2.5 and 5.0.0 exhibit the same behaviour with `ctrl-c` in `rails console`, you can use `ctrl-d` to send an an end of input signal and return to your prompt.

**Comment by lohqua** [comment]
Yes Rails console does exit on ctrl-c, again a longstanding thing. It does not close properly in beta1.

  >That is still true.

No, it is not true in beta1.

ModelName.find 2 returns an error saying I need to make a connection.

**Comment by rafaelfranca** [comment]
As you can see Rails console doesn't exit with ctrl-c, even in Rails 3.2, so no it is not a longstanding thing.

```
$ rails c
Loading development environment (Rails 3.2.22)
>> ^C
>> ^C
>> ^C
>> ^C
>>
```

Also, as you can see `ModelName.find 2` doesn't return an error saying you need to make a connection in Rails 5.0.0.beta1.

```
$ rails c
Loading development environment (Rails 5.0.0.beta1)
>> User.find(1)
  User Load (0.4ms)  SELECT  "users".* FROM "users" WHERE "users"."id" = ? LIMIT ?  [["id", 1], ["LIMIT", 1]]
ActiveRecord::RecordNotFound: Couldn't find User with 'id'=1
```

If you still think that is not the case please provide an example application reproducing the issues that you are having.
