### ISSUE TITLE
error when deployed: "Error during WebSocket handshake: Unexpected response code: 404"

### ISSUE THREAD

**Issue by KeithP** [rails/rails#22871]
When attempting to deploy the simple chat example https://github.com/HectorPerez/chat-in-rails5
to a single EC2 instance on AWS we get 'Error during WebSocket handshake: Unexpected response code: 404'. This works locally with RAILS_ENV=production but fails when deployed.

<strong>Steps to reproduce:</strong>

1) Clone https://github.com/HectorPerez/chat-in-rails5

2) Add redis install script by adding .ebextensions/ruby.config like this: https://gist.github.com/KeithP/08b38189372b7fd241e5#file-ebextensions-redis-config ; Git commit and deploy. 

3) Use Elastic Beanstalk to spin up a single instance thus:

    eb create dev-env -p “64bit Amazon Linux 2015.09 v2.0.4 running Ruby
    2.2 (Puma)” –single -i t2.micro --envvars
    SECRET_KEY_BASE=g5dh9cg614a37d4bdece9126b42d50d0ab8b2fc785daa1e0dac0383d6387f36b

4) Open in a browser, inspect and see this repeating error in the console:

    application-a57354de3399cd895ca366df9bd7316ab69e81d266b63be7d7be563ebc78ab9d.js:27 
    WebSocket connection to ‘ws://dev-env-y2e5dcrxqk.elasticbeanstalk.com/cable’ failed: 
    Error during WebSocket handshake: Unexpected response code: 404

![chatroom2](https://cloud.githubusercontent.com/assets/265490/12064677/6b29d826-afc1-11e5-8fbb-6439dfeed1ab.JPG)

Check the logs and verify redis installed and started ok

This is also asked on stackoverflow: http://stackoverflow.com/questions/34536926/rails-5-0-0-beta1-activecable-error-during-websocket-handshake-unexpected-resp

**Comment by rafaelfranca** [comment]
Is not this Elastic Beanstalk rejecting `ws://` requests?

**Comment by KeithP** [comment]
@rafaelfranca not sure. Someone had success deploying to a single instance hosted on Cloud9, so probably AWS specific.
We tried adding proxy config for NGINX (https://gist.github.com/aku/5466527) but no joy.  

The server production.log shows two "Started GET /cable" for every one "Finished /cable" call (strange?).
There are no DEBUG messages from ActionCable, so no clues. Normally we see lots of DEBUG messages for a 404 (can we have more logging?):

/var/app/containerfiles/logs/production.log

...
INFO -- : Processing by RoomsController#show as HTML
DEBUG -- :   [1m[36mMessage Load (0.1ms)[0m  [1m[34mSELECT "messages".* FROM "messages"[0m
INFO -- :   Rendered collection (0.0ms)
INFO -- :   Rendered rooms/show.html.erb within layouts/application (0.5ms)
INFO -- : Completed 200 OK in 2ms (Views: 1.2ms | ActiveRecord: 0.1ms)
INFO -- : Started GET "/cable" for xxx.xxx.xxx at 2016-01-01 17:28:26 +0000
INFO -- : Started GET "/cable/" for xxx.xxx.xxx at 2016-01-01 17:28:26 +0000
INFO -- : Finished "/cable/" for xxx.xxx.xxx at 2016-01-01 17:28:26 +0000
...

**Comment by KeithP** [comment]
We got this working using this proxy config for NGINX : https://gist.github.com/KeithP/f8534c04d20c2b4e4b1d. In future to make this easier to troubleshoot can we add to the documentation and / or add more logging?

**Comment by maclover7** [comment]
Feel free to submit a PR adding more error logging. I do think the source of error though is AWS' handling of websockets.

**Comment by KeithP** [comment]
Thanks, PR #23274 is submitted for this

**Comment by maclover7** [comment]
Closing due to #23274 being merged.
