### ISSUE TITLE
Rails 5.0.0.beta1 When creating a new app, Spring can't be executed

### ISSUE THREAD

**Issue by lohqua** [rails/rails#22878]
rails new my_app
    ...
    run  bundle exec spring binstub --all
    bundler: command not found: spring

I manually ran it

    > bundle exec spring binstub --all
      bundler: command not found: spring
      Install missing gem executables with `bundle install`

The spring file is in ruby/bin/. 

It worked when I manually ran it with the full path

    > bundle exec /home/me/sdk/ruby/bin/spring binstub --all 
      * bin/rake: spring inserted
      * bin/rails: spring inserted

**Comment by herminiotorres** [comment]
Just tested here installing rails 5 and the usual spring work.
Maybe your ruby or some version manager is not working properly.

**Comment by lohqua** [comment]
I don't use any version manager

**Comment by MattMS** [comment]
I seem to have had this issue as well but my fix involved installing `sqlite-dev`.

Running in Docker, using the [official Ruby Alpine Image](https://hub.docker.com/_/ruby/), I ran `apk --update add sqlite-dev`.

**Comment by ThreeWest** [comment]
I have the same issue. Using what the 2 others did to fix it doesn't work for me.
