### ISSUE TITLE
After Changing  Columns of Model, Fixture Is Not Working Well

### ISSUE THREAD

**Issue by lo-tp** [rails/rails#22886]
**Environment**
- ruby 2.2.3p173
- Rails 4.2.4

**Description**

We can use `rails g migration ...` to change columns of a model.
However, fixture is not updated properly in accordance with this kind of change.

This will lead to errors that would be very hard to track.

**How to replicate this kind of problem**

1. `rails g model food name:string number:integer`.
1. `rake db:migrate`.
1. `rake db:test`.
1. `rails g migration  RemoveNameFromFood name:string`.
1. `rake db:migrate`.
1. `rake test`.

Apart from removing, this problem will also show up if you change the name of a column of a model.

**Comment by sevenseacat** [comment]
I think that's to be expected. if you change your table structure, you have to then change everywhere else that uses that table structure.

**Comment by lo-tp** [comment]
@sevenseacat , your point is reasonable. However, I think the better way is to let rails tackle all these tasks automatically. There're two reasons for my argument

**Firstly, It's very achievable**
What we need to do is just to add two callback to the `rails g migration` command when it is used to rename or delete a column, then change the fixture file properly. It's not a hard job.
**Secondly, It will add so many conveniences to our life **
To edit the fixture file manually is such a moil that it will take so much time especially when the fixture data is too large. More significantly, it's a little bit tricky to track down this problem when we change table structure using *migration* for the first time.

**Comment by sevenseacat** [comment]
It's not very achievable. Because once you start changing fixture files based on migrations, then you'll want to change model files, and view files, and controller files, and everything else that may reference the old field name too.

**Comment by rafaelfranca** [comment]
@sevenseacat is right. Even if achievable we don't plan to add this level of complexity in generators.
