### ISSUE TITLE
Data send using actioncable is only accessible on page reload

### ISSUE THREAD

**Issue by oleander** [rails/rails#22897]
**Complete example:** I've create a failing example here with instructions on how the bug (?) can be reproduced and how the server is set up: https://github.com/oleander/rails-5-action-cable-fail

**Problem:** When data is pushed to the client at the same time the user loads a page, no data is received right away. Instead the data appears when the page reloads. 

**Short example:** Here we first push some data to a background job which publishes everything it receives back to the websocket connection. The client is then waiting for the data to come back and once it does appends it to the page.

``` erb
<% LaterOnJob.perform_later("This is a background job") %>

<script type="text/javascript">
  var cabel = ActionCable.createConsumer("ws://localhost:3000/cable")
  cabel.subscriptions.create("LaterOnChannel", {
    received: function(data) {
      $(".data").replaceWith(data.data);
    }
  });
</script>

<h1>Waiting for data</h1>
<div class="data"></div>
```

``` ruby
class LaterOnChannel < ApplicationCable::Channel
  def subscribed
    stop_all_streams
    stream_from "messages:key"
  end
end
```

``` ruby
class LaterOnJob < ApplicationJob
  def perform(data)
    ActionCable.server.broadcast("messages:key", data: data)
  end
end
```

I'm expecting the text `This is a background job` to show up on the page. Instead nothing happens until the page later is reloaded. Right after the reload button is pressed the above text appears. Take a look at the link posted above for a complete failing example.

**System:** Rails 5 beta (4d98b0d), Ruby 2.2.4, Chrome 46.0.2490.80

**Comment by rafaelfranca** [comment]
cc @javan @dhh

**Comment by javan** [comment]
You need to wait until your subscription is connected before sending data to it. In your example, you're kicking of a background job and *then* creating a subscription. If the job finishes before the subscription is active (which is pretty likely when running locally with no queue of jobs), you'll miss the data.

Try moving the job initiation from your view and into your channel's `subscribed` callback.
```ruby
class LaterOnChannel < ApplicationCable::Channel
  def subscribed
    stop_all_streams
    stream_from "messages:key"
    LaterOnJob.perform_later("This is a background job")
  end
end
```

**Comment by oleander** [comment]
@javan How come the data is actually received on the client but only shown when the page is about to be reloaded? I'm aware of the race condition that might occur, but in this case the data is actually received, its just not shown until the page is reloaded. Did you try my example?

**Comment by javan** [comment]
I did, here's the logs from hitting refresh:
```
Started GET "/pages/index" for 127.0.0.1 at 2016-01-06 22:44:01 -0500
Processing by PagesController#index as HTML
[ActiveJob] Enqueued LaterOnJob (Job ID: b9400c4b-2557-40dc-9cea-973b8ba83b96) to SuckerPunch(default) with arguments: "This is a background job"
  Rendered pages/index.html.erb within layouts/application (1.7ms)
[ActiveJob] [LaterOnJob] [b9400c4b-2557-40dc-9cea-973b8ba83b96] Performing LaterOnJob from SuckerPunch(default) with arguments: "This is a background job"
[ActiveJob] [LaterOnJob] [b9400c4b-2557-40dc-9cea-973b8ba83b96] [ActionCable] Broadcasting to messages:key: {:data=>"This is a background job"}
LaterOnChannel transmitting {"data"=>"This is a background job"} (via streamed from messages:key)
[ActiveJob] [LaterOnJob] [b9400c4b-2557-40dc-9cea-973b8ba83b96] Performed LaterOnJob from SuckerPunch(default) in 1.81ms
LaterOnChannel transmitting {"data"=>"This is a background job"} (via streamed from messages:key)
Completed 200 OK in 30ms (Views: 29.3ms | ActiveRecord: 0.0ms)
Finished "/cable/" [WebSocket] for 127.0.0.1 at 2016-01-06 22:44:01 -0500
LaterOnChannel stopped streaming from messages:key
...
Started GET "/assets/action_cable/consumer.self-d0a6518de32602abb57c66be88b1fd0445527abfb6d8fad3a0be0c59eb6b7fd1.js?body=1" for 127.0.0.1 at 2016-01-06 22:44:02 -0500
Started GET "/assets/application.self-b89234cf2659d7fedea75bca0b8d231ad7dfc2f3f57fcbaf5f44ed9dc384137b.js?body=1" for 127.0.0.1 at 2016-01-06 22:44:02 -0500
...
Started GET "/cable" for 127.0.0.1 at 2016-01-06 22:44:02 -0500
Started GET "/cable/" [WebSocket] for 127.0.0.1 at 2016-01-06 22:44:02 -0500
LaterOnChannel is transmitting the subscription confirmation
LaterOnChannel is streaming from messages:key
```
It looks like the background job finishes before rendering is complete, which means the browser hasn't painted the new page yet. So the old page receives the data and displays it right before getting replaced with the refreshed page.

**Comment by javan** [comment]
There's no bug here. Just the result of an unconventional setup with a background job that finishes before rendering is complete.

**Comment by oleander** [comment]
Is there a way for the channel to push out old data (a couple of seconds) to newly connected clients? I guess that would solve the problem.

**Comment by januszm** [comment]
Another weird edge case of race condition with ActionCable that you may find yourself in: Test/RSpec (doesn't matter `feature` or `system` test) + Capybara:

```ruby
# test if page updates with ActionCable/Websockets when Job is done
# background job calls ActionCable.server.broadcast...
visit "/some_stuff/#{uuid}"
perform_enqueued_jobs do
  ProcessSomeOtherStuffJob.perform_later(data)
end
expect(page) # ... to have status element updated
```
🔴 

Sometimes the above will cause the following:
`Job#perform` which calls `ActionCable.server.broadcast` happens BEFORE `...Channel#subscribed` , it means that when we verify that page element is updated, we already executed the Job but we haven't finished loading page.

The solution to this problem is to do something that will force Capybara to wait for the page to load, e.g.:

```ruby
visit "/some_stuff/#{uuid}"
expect(page).to have_selector ".status-element-before-update" # <<< this `expect` forces Capybara to wait
perform_enqueued_jobs do
  ProcessSomeOtherStuffJob.perform_later(data)
end
expect(page) # ... to have status element updated
```
✅
