### ISSUE TITLE
Validating doesn't stop even if  one validation failed

### ISSUE THREAD

**Issue by lo-tp** [rails/rails#22902]
In the validatng process of Model, rails will run every validation even if the previous validation failed.

That's not the expected behavioral. Rails should stop validating the data when one validation failed.

**How to Replicate**

- Run `rails g Model test time_record:datetime`
- Run `rake db:migrate`
- Edit app/models/test.rb to add two validations like this
```ruby
class Test < ActiveRecord::Base
        validates :time_record, presence:true
        validate :time_should_be_after_2015

        def time_should_be_after_2015
                dt2015 = DateTime.new(2015,1,1,0,0,0)
                errors.add(:time_record,'Time is earlier than 2015') unless self.time_record > dt2015
        end
end
```
- Edit test/models/test_test.rb 
```ruby
require 'test_helper'

class TestTest < ActiveSupport::TestCase
  test "the existence of time_record" do
          t=Test.new()
          assert_not t.save
  end
end
```
- Run `rake test`

**What's Wrong**

During the validation, rails should stop when the first validation failed.

Otherwise, strange exception would be raised.

**Comment by sevenseacat** [comment]
No, that's not expected behaviour. You should write your validations to only run if applicable, eg. don't run the "after 2015" validation if there is no time present at all.

**Comment by lo-tp** [comment]
@sevenseacat 
You mean change *time_should_be_after_2015* in this way?

`errors.add(:time_record,'Time is earlier than 2015') unless self.time_record&&self.time_record > dt2015`

This is to merge two separate validations to a single one. I don't think this is a good way to do the validation

**Comment by sevenseacat** [comment]
It doesn't merge two validations into one. If there is no time present, your `time_should_be_after_2015` would not add a validation error to the record.

Think of filling out a form and getting multiple validation failures. Would you want to be shown them one at a time, or all at once?

**Comment by lo-tp** [comment]
@sevenseacat 
I have to confess that under the circumstance of the absence of time_record,`time_should_be_after_2015` wouldn't add a another validation error.

Maybe you are right...LOL.
