### ISSUE TITLE
config.assets.precompile array and ruby 2.3.0

### ISSUE THREAD

**Issue by fschwan** [rails/rails#22905]
I've just tried to create a new rails 4.2.5 project with ruby 2.3.0.
The behaviour of the
```
Rails.application.config.assets.precompile
```
array changed somehow. Before Ruby 2.3.0 I used this one
```
Rails.application.config.assets.precompile = %w( pages/* )
```
to include all assets that I place in the pages subfolder (to use one asset file per page).
When I try to use this with Ruby 2.3.0, Sprockets complains about a
```
Sprockets::Rails::Helper::AssetNotPrecompiled
```
error which says, that assets in the pages subfolder were not being precompiled. 

To reproduce this, take ruby 2.3.0 and rails 4.2.5 and create a new project with additional haml gem (should not be related to this bug). Generate a controller and a view, include this in your application.html.haml
```
= stylesheet_link_tag    "pages/#{params[:controller]}", media: 'all', 'data-turbolinks-track' => true
```
and create a scss file in the pages subfolder. Now try to access the generated page.

I am quiet familiar with rails development but my skills are limited when it comes to framework debugging. I appreciate any help.

**Comment by maclover7** [comment]
cc @schneems

**Comment by schneems** [comment]
Can you give me a small example app that reproduces the problem?

**Comment by rafaelfranca** [comment]
This issue was moved to rails/sprockets-rails#303
