### ISSUE TITLE
ActionCable and posting to channel from ClientSide

### ISSUE THREAD

**Issue by mityaz** [rails/rails#22908]
Hi,

While investigating the codebase for ActionCable I spotted a method [#send](https://github.com/rails/rails/blob/master/actioncable/lib/assets/javascripts/action_cable/connection.coffee#L11]). It wraps websocket's `send` method. Does that mean that we are able to post to channel from the client side as well, not only through the server side? Can it be a potential security abuse?
I could not find a correct answer for this question and while trying to post to my test message channel from the browser, I got an error on my server side:

`Unable to process MessagesChannel#receive({"body"=>"Hello from the browser"})`

**Comment by javan** [comment]
You can send data over the web socket via a client-side subscription's `#perform` method, which takes care to properly format the message. [This section of the README](https://github.com/rails/rails/tree/master/actioncable#channel-example-1-user-appearances) has an example.

**Comment by kswope** [comment]
This is in the documentation but I also get the same error as the OP.  Something is wrong somewhere.

https://github.com/rails/rails/tree/master/actioncable

```
# Client-side, which assumes you've already requested the right to send web notifications
App.chatChannel = App.cable.subscriptions.create { channel: "ChatChannel", room: "Best Room" },
  received: (data) ->
    # data => { sent_by: "Paul", body: "This is a cool chat app." }

App.chatChannel.send({ sent_by: "Paul", body: "This is a cool chat app." })

```

**Comment by VitaliyKovtun** [comment]
same trouble here
Completed 201
Unable to process MessagesChannel#receive({"body"=>"s"})

**Comment by RailsCod3rFuture** [comment]
Anyone know what the root cause of this is? Having issues with web sockets in Docker.

**Comment by RailsCod3rFuture** [comment]
This doesn't happen locally, but it does happen when its running the app in docker with webpack-dev-server enabled. I was getting web socket errors before, now there are none....Yet, this message is still showing in the console.

**Comment by dchacke** [comment]
@RailsCod3rFuture I ended up being able to fix this issue by adding a `receive` instance method to the channel class.

**Comment by RailsCod3rFuture** [comment]
@dchacke Testing this approach out now -- thanks.

**Comment by Gibbo3771** [comment]
If you are using docker and action cable with redis, changes to your channel class will not reflect unless you restart your containers.
