### ISSUE TITLE
em-hiredis dependency conflict with ActionCable

### ISSUE THREAD

**Issue by jlecour** [rails/rails#22907]
Hi,

Thanks to the Rails team for the huge work on this `5.0.0.beta1`. It looks awesome and I can't wait to use it. Being a beta, it has some rough spots and here is one that is bothering me.

* Rails 5 depends on ActionCable, which depends on `em-hiredis (~> 0.3.0)` which depends on `hiredis (~> 0.5.0)` which is kind of old (a `0.6.x` has been released on February 8, 2015).
* I've been using `hiredis` for a while and I depend on the `0.6.x` version in my app.
* Now that Rails forces me to install ActionCable (which I don't intend to use), I'm blocked.

There is an open issue (https://github.com/mloughran/em-hiredis/issues/39) for `em-hiredis` but it seems a bit stale.

NB : I still don't understand why ActionCable is a hard dependency of rails and not in the default gemfile. I looks like unnecessary burden.

**Comment by francesco-loreti** [comment]
For now, you can auto generate the gem of em-hiredis cloning the project using the local branch ' master ' (that is already compatible with the hiredis ' ~ > 0.6.0 ' but not yet released) . You can use ' gem build em-hiredis.gemspec ' and then ' gem install em-hiredis-0.3.1.gem ' and you can try to install rails. Check if it works .

**Comment by jlecour** [comment]
@francesco-loreti Hey, thanks for the tip.

I've tried that (and also depending on the master branch `gem "em-hiredis", "~> 0.3.1", github: "mloughran/em-hiredis", branch: "master"`) but I'm stuck in a loop when Bundler resolves the dependencies.

I'll try to debug that.

**Comment by francesco-loreti** [comment]
No no... It's not correct...
1) On console(or cmd) go to Ruby gems path(example cd 'Ruby22/lib/ruby/gems/2.2.0/gems');
2) git clone https://github.com/mloughran/em-hiredis.git
3) cd em-hiredis
4) gem build em-hiredis.gemspec
5) gem install em-hiredis-0.3.1.gem

Try again

**Comment by jlecour** [comment]
Hi @francesco-loreti 

both solutions are working for me : the manually-built-and-installed gem *and* using the github branch via the Gemfile.

My dependency problem was because of other gems that depend on Rails 4 or an old sprockets. But this is irrelevant to the current issue.

Also, I don't want to create a new Rails app (which would most probably work) but update an existing one, which depends on a later version of `hiredis`.

Anyway, thanks for the help.

**Comment by jcoyne** [comment]
Is the Rails core team sure that em-hiredis is the way to go?  It seems pretty stale.  Has anyone considered requesting a transfer of ownership to the Rails organization? https://github.com/mloughran/em-hiredis/graphs/contributors

**Comment by rafaelfranca** [comment]
> Has anyone considered requesting a transfer of ownership to the Rails organization?

No please!

> Is the Rails core team sure that em-hiredis is the way to go?

For the final release I expect to us remove all hard dependencies we have with Action Cable right now. But no one is working on that.

**Comment by jcoyne** [comment]
> For the final release I expect to us remove all hard dependencies we have with Action Cable

:relieved: Excellent. That seems like it would alleviate a number of issues.

**Comment by rafaelfranca** [comment]
That is just my expectation, but like I said no one is working on that. We need someone to do the work so that expectation becomes reality.

**Comment by jlecour** [comment]
@rafaelfranca Thanks for your input on this one.

The problem, in my opinion, is that the current situation is forcing stuff down on users who don't care a bit about ActionCable.

I have a huge amount of respect for David's vision and sometimes one has to push things a bit for progress. Pushing for realtime communication between clients and servers is great. A lot of apps will benefit from a way paved by the Rails team. In this case I think it's too much.

I would be happy to do some work on this, but I would have to learn a lot of stuff, do a lot of testing… in order to be able to not use a feature. Sadly, I'm not that dedicated.

With previously controversial features, like TurboLinks, at least it was very easy to remove them. I wish it was the case with ActionCable.

**Comment by rafaelfranca** [comment]
> The problem, in my opinion, is that the current situation is forcing stuff down on users who don't care a bit about ActionCable.

Yes, we all agree with it. This is why I said that my expectation is to drop all the hard dependencies of Action Cable. It includes celluloid, eventmachine, em-redis, hiredis. Given how much I know of this team I believe my expectation will be met in the final release. That way, we all can share the David's vision while not forcing stuff down on users.

**Comment by jlecour** [comment]
@rafaelfranca Do you have a link to an issue, a PR or something about the work to be done about that ? I'd be happy to help if I can.

**Comment by rafaelfranca** [comment]
I don't. We only had internal discussions so far.

**Comment by jcoyne** [comment]
See PR #22907 for work on removing ActionCable.

**Comment by jlecour** [comment]
Hey @sgrif, the latest Bikeshed episode made me think that in case you don't already have enough of this AC thing, this particular issue might be interesting to you :)

**Comment by rafaelfranca** [comment]
I'm closing since this is no a Rails issue. em-hiredis already [bumped the dependency](https://github.com/mloughran/em-hiredis/commit/7ebf358891ed08b8926737b1e5bee0b8c3875429) so one possible solution is to ask them to release that commit.
