### ISSUE TITLE
new "no content" response when a template is missing creates unintuitive errors

### ISSUE THREAD

**Issue by georgemillo** [rails/rails#22910]
I'm creating a new, simple CRUD app and thought I'd take the opportunity to try out rails-5.0.0.beta1. And I just wasted fifteen minutes trying to figure out why my extremely simple page wasn't working. I have a resource called `Card`, and in one of my views I have `link_to "new card", new_card_path` - but when I clicked the link, nothing happened. Nothing changed in my browser, not even the URL, and when I looked in the server log (this is using Puma), there was no indication that the server had even received a request.

Eventually, I figured out that my mistake was a very simple one - I'd forgotten that I hadn't created the `cards/new.html.erb` view yet - and the new Rails 5 way of doing things seems to be to return `204 - no content` when it can't find the template, rather than raising the error.

I suppose I see the logic in returning 204 when this is the case, but this also gave me an extremely unintuitive error for what should be a very simple error, and it took me 15 minutes to spot a problem something that in Rails 4 would have taken me 2 seconds. Is there any way we can avoid this? Maybe only return `204` in production mode, not dev, or include a config option like `return_204_when_template_missing` that's default `true` in prod but `false` in dev?

At the very least, can we change things so that "no template > 204" responses actually appear in the server logs? At the moment literally nothing appears whatsoever when I click a link which leads to a path with no template; it's as if nothing has been clicked at all.

**Comment by matthewd** [comment]
> At the very least, can we change things so that "no template > 204" responses actually appear in the server logs?

Yeah, that sounds like a bug. The rest is expected.

We can't behave differently between development and production, because the designed intent is that it can be relied upon: it's a feature, not just a change in error handling behaviour.

**Comment by georgemillo** [comment]
On closer inspection, this seems to be a bug with the [`quiet_assets`](https://github.com/evrone/quiet_assets) gem - when I remove it, the messages appear in my server log as they should. I'll open an issue over there.
