### ISSUE TITLE
CodeStatisticCalculator raises exception when there is binary file

### ISSUE THREAD

**Issue by Edouard-chin** [rails/rails#22919]
I'm not sure if this is something rails should take care of, sorry in advance if it's not the case.
`rake stats` will raise a `ArgumentError: invalid byte sequence in UTF-8` if there is a binary file inside a directory.
The most common reason of having binary files inside directories would be because of temporary files.

An easy solution would be to not process if it's an hidden file (starting by `.`)

**Comment by pixeltrix** [comment]
@Edouard-chin is that a binary file ending in `.rb`, `.js`, `.coffee` or `.rake` ? It's just that `CodeStatisticsCalculator#add` takes a pattern that filters the files to one of those 4 types. If something is creating binary files with those file extensions then I'd suggest that whatever's doing that is the source of the problem.

**Comment by Edouard-chin** [comment]
Indeed, in my case files were endind in `.rb`.
Avoiding having this kind of files created automatically is tricky, especially on mac (those famous `._*` files). I usually don't care about them as they are globally git ignored, but in the case where I need to run `rake stats`, it would mean that I should first remove them. IMHO it's not super convenient. Is there a particular reason of why we would calculate stats of hidden files?

**Comment by matthewd** [comment]
Ignoring hidden files sounds reasonable
