### ISSUE TITLE
Model.first / Model.last aliases

### ISSUE THREAD

**Issue by Bartuz** [rails/rails#22928]
Every time I promise myself I'll remember that `.last` is the newest and `.first` is the oldest one but no. My brain just can't accept it and I always forget and mix up these two.

What do you think about aliasing `.last` as `.newest` and `.first` as `.oldest` ? Anyone else also feel confused about them?

**Comment by aliibrahim** [comment]
Not really. This has been a convention for a long time and it makes perfect sense!

**Comment by nateberkopec** [comment]
Feature requests are generally not accepted here in Github issues, [try the rails core mailing list for that](https://groups.google.com/forum/#!forum/rubyonrails-core).

**Comment by Drenmi** [comment]
> Every time I promise myself I'll remember that .last is the newest and .first is the oldest one but no. 

This assumption is incorrect. `#last` is the last and `#first` is the first. Whether they are *incidentally* also the oldest and newest depends on what ordering is applied. 🙂
