### ISSUE TITLE
Ruby intepreter was crash with Rails 5

### ISSUE THREAD

**Issue by hoahm** [rails/rails#22937]
Doesn't know whether I submit report about Ruby intepreter or extension libraries or not? But sometimes I got these exception when trying to refresh web page on browser.

I'm using Ruby 2.3.0, Rails 5.0.0beta1, and bellow is my Gemfile

    source 'https://rubygems.org'
    ruby '2.3.0'

    # Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
    gem 'rails', '>= 5.0.0.beta1', '< 5.1'
    # Use postgresql as the database for Active Record
    gem 'pg', '~> 0.18'
    # Use Uglifier as compressor for JavaScript assets
    gem 'uglifier', '>= 1.3.0'
    # Use CoffeeScript for .coffee assets and views
    gem 'coffee-rails', '~> 4.1.0'
    # See https://github.com/rails/execjs#readme for more supported runtimes
    # gem 'therubyracer', platforms: :ruby

    # Use jquery as the JavaScript library
    gem 'jquery-rails'
    # Turbolinks makes following links in your web application faster. Read more: https://github.com/rails/turbolinks
    gem 'turbolinks'
    # Build JSON APIs with ease. Read more: https://github.com/rails/jbuilder
    gem 'jbuilder', '~> 2.0'
    # Use Puma as the app server
    gem 'puma'

    # Use ActiveModel has_secure_password
    # gem 'bcrypt', '~> 3.1.7'

    # Use Capistrano for deployment
    # gem 'capistrano-rails', group: :development

    group :development, :test do
      # Call 'byebug' anywhere in the code to stop execution and get a debugger console
      gem 'byebug'
    end

    group :development do
      # Access an IRB console on exception pages or by using <%= console %> in views
      gem 'web-console', '~> 3.0'
      # Spring speeds up development by keeping your application running in the background. Read more: https://github.com/rails/spring
      gem 'spring'

      gem 'better_errors'
      gem 'quiet_assets'
      gem 'pry-rails'
    end

    # Windows does not include zoneinfo files, so bundle the tzinfo-data gem
    gem 'tzinfo-data', platforms: [:mingw, :mswin, :x64_mingw, :jruby]

    ##
    # ------------------------------
    # FRONT END
    # ------------------------------
    #
    # twitter bootstrap
    gem 'bootstrap-sass'

    # Jquery UI
    gem 'jquery-ui-rails'

    # auto prefixer
    gem 'autoprefixer-rails'

    # modernizr
    gem 'modernizr-rails', '~> 2.7.1'

    # font awesome
    gem 'font-awesome-rails'

    # template generator
    gem 'slim-rails'

    # breadcrumb
    gem 'breadcrumbs_on_rails', git: 'https://github.com/hoahm/breadcrumbs_on_rails.git'

    ##
    # ------------------------------
    # RAILS FORM AND PAGINATION
    # ------------------------------
    gem 'simple_form'
    gem 'nested_form'
    gem 'kaminari', git: 'https://github.com/amatsuda/kaminari.git', branch: :master
    gem 'bootstrap-kaminari-views'
    gem 'has_scope', git: 'https://github.com/plataformatec/has_scope.git', branch: :master

    ##
    # ------------------------------
    # AUTHENTICATION
    # ------------------------------
    gem 'devise', git: 'https://github.com/plataformatec/devise.git', branch: :master

    ##
    # ------------------------------
    # OTHERS
    # ------------------------------
    # Load environment variables from .env file
    gem 'dotenv-rails'

    # Preview email in the default browser instead of sending it
    gem 'letter_opener'

    # Build ActiveRecord named scopes that take advantage of PostgreSQL's full text search
    gem 'pg_search'

    # Enumerated attributes with I18n and ActiveRecord
    gem 'enumerize'

    # Easy file attachment management for ActiveRecord
    gem "paperclip", "~> 4.3"

    # Serialize model object
    gem 'active_model_serializers'

    # Generates swagger-ui json files for Rails APIs with a simple DSL
    gem 'swagger-docs'

    # Swagger-ui asset gem
    gem 'swagger-ui_rails'

    # Ruby gem for reporting errors to honeybadger.io
    gem 'honeybadger'

    # An implementation of the nested set pattern for ActiveRecord models
    gem 'awesome_nested_set'

    # Nested Set + Drag&Drop GUI
    gem "the_sortable_tree", "~> 2.5.0"

[Uploading crash_report.log.zip…]()

**Comment by rafaelfranca** [comment]
Can you please provide a sample application that reproduces the error?

**Comment by renanoronfle** [comment]
i create new project with equals Gemfile and working.
