### ISSUE TITLE
Associate new record with existing through has_one

### ISSUE THREAD

**Issue by evheny0** [rails/rails#22944]
let see we have two models with belong_to/has_one association:

``` ruby
class Banner < ActiveRecord::Base
  has_one :image
  accepts_nested_attributes_for :image
end

class Image < ActiveRecord::Base
  belongs_to :imageable, polymorphic: true
end
```

then we create model with belongs_to:

``` ruby
image_id = Image.create.id
```

and then:

``` ruby
Banner.create(image_attributes: { id: image_id })
```

The last piece will give an error:

``` text
ActiveRecord::RecordNotFound: Couldn't find Image with ID=1 for Banner with ID=
```

which is kinda confusing. `assign_nested_attributes_for_one_to_one_association` is actually not even search for models, it's just looks for the presence of association in object, even though id is passed.

For example in has_many relation there is an approach for passing ids like this:

``` ruby
SomeModel.create(other_model_ids: [1, 2, 3])
```

which is pretty much the same thing, that I'm trying to get from has_one

I think good solution for this would be a searching for record if id has been passed and model not preloaded.

**Comment by pauloancheta** [comment]
Wasn't this an expected behaviour? With one to one association, passing the `id` is only used for the `#update`.

**Comment by evheny0** [comment]
But why I can update other models reference with `create` in has_many and can't in one to one?

Also there is a possibility to link models by id through model with `belongs_to` and no through model with `has_one`. It's seems logical to have this possibility for each side of one to one.
