### ISSUE TITLE
after_callback is not called on nested resources

### ISSUE THREAD

**Issue by xdmx** [rails/rails#22943]
I'm using rails 4.2.5 and I've noticed that after_callback is not called on nested resources

```
class Post < ActiveRecord::Base
  belongs_to :user
  after_rollback { puts 'nested' }
end 

class User < ActiveRecord::Base
  has_many :posts
  accepts_nested_attributes_for :posts
  after_rollback { puts 'top level' }
end
```

When a user is created passing posts_attributes, it only puts `top level`, but not `nested`

In my opinion it should also call the nested rollback, since it could be do something important

**Comment by pixeltrix** [comment]
@xdmx can you check whether the records have been saved to the database before the rollback occurs. I think what's happening is that the nested records are only in memory and so haven't been added to the transaction yet.

**Comment by xdmx** [comment]
@pixeltrix from the rails log I see only SELECT queries called by validations before and after the ROLLBACK, but none with INSERT or UPDATE

So far I've solved it with the following:
```
class Post < ActiveRecord::Base
  belongs_to :user
  def manual_rollback
    puts 'nested'
  end
end 

class User < ActiveRecord::Base
  has_many :posts
  accepts_nested_attributes_for :posts
  after_rollback { posts.each(&:manual_rollback) }
end
```

Which is not the best way but it does the work

**Comment by pixeltrix** [comment]
@xdmx was there an insert/update for the top level model?

**Comment by xdmx** [comment]
nope, only selects

**Comment by pixeltrix** [comment]
@xdmx can you make it so the top level model passes validation and then the transaction fails because of a validation failure on a nested model. Also what database are you using?

**Comment by xdmx** [comment]
Yup, it was already like that, the top level model (user) was valid, and the nested model (post) was not

I'm using postgresql 9.4.5 under Arch linux
