### ISSUE TITLE
String#to_time and String#to_datetime return different dates for certain input.

### ISSUE THREAD

**Issue by sliiser** [rails/rails#22958]
For some certain inputs, `String#to_time` cannot parse the date correctly, but returns the current date at midnight instead of nil.
Take a look at the following example

    'gibberish'.to_time
    # => nil
    '010'.to_time
    # => 2016-01-07 00:00:00 +0200 # current date at the time of writing
    '010'.to_datetime
    # => Sun, 10 Jan 2016 00:00:00 +0000

According to `Date._parse` the string 010 represents the 10. day of the year. However, `String#to_time` does not use the `:yday` parameter returned by `Date._parse` and just uses the default according to the documentation instead.

Expected behaviour would be to use all parameters returned by `Date._parse` to build the `Time` object or return `nil` if the hash returned by `Date._parse` does not contain any parameters that are used in the construction of the `Time` object.

Tested with both Rails 4.2.1 and Rails 5.0.0.beta1.

**Comment by pixeltrix** [comment]
This is reflected in Ruby itself, e.g:

``` irb
>> Time.parse('010')
ArgumentError: no time information in "010"
>> DateTime.parse('010')
=> #<DateTime: 2016-01-10T00:00:00+00:00 ((2457398j,0s,0n),+0s,2299161j)> 
```

given that I think it's probably best to return `nil` from `String#to_time` if there's nothing in the hash that is used as that would follow Ruby's behaviour.
