### ISSUE TITLE
Serialized attributes are not read-consistent in Rails 4.2+ (i.e. not the same object instance after assignment)

### ISSUE THREAD

**Issue by mattcross** [rails/rails#22964]
This problem is present in of Rails 4.2 and 5.0.0.beta1 but behaves as I expect it to in 4.1.x

[Here is a gist](https://gist.github.com/mattcross/03052937654b601cf38f) that demonstrates the problem. 

When I assign an object to a serialized attribute of a model I expect to be able to get the exact same object when I read the attribute, but that is not the case.

````ruby
class Thing
  attr_accessor :transient

  def initialize(name)
    @name = name
  end

  def as_json(options={})
    {
        name: @name
    }
  end
end

class ThingOwner < ActiveRecord::Base
  serialize :thing, JSON
end

owner = ThingOwner.new
thing = Thing.new("hello")
owner.thing = thing
thing.object_id == owner.thing.object_id #false
````

The problem for me is that, you may want to set properties on the serialized attribute that are not written to the database but are necessary while in memory, the assignment loses these values. This was not the case in 4.1 and think the 4.1 behavior was more intuitive and correct.

Here is an example:
````ruby

thing = Thing.new("hello")
thing.transient = "world"
owner.thing = thing
# Unexpected result
thing.transient #world
owner.thing.transient #nil


````

**Comment by kaspth** [comment]
r? @sgrif

As far as I understand it Rails 4.2 increased correctness by going through a load and dump when assigning attributes, so you know the values are correctly deserialized after a database roundtrip (symbol keys being strings for instance).

**Comment by sgrif** [comment]
This is the expected behavior. We do not guarantee the following in any case:

```ruby
model.attr = value
model.attr.equal?(value)
```

(In fact, in most cases we explicitly guarantee that it is not true)

**Comment by mattcross** [comment]
A couple of questions...

@sgrif I appreciate the quick response but I have a couple questions.

1. Why was the 4.1 behavior incorrect?
2. Why is it desirable to make serialized attributes essentially copy on write? It is common to have state on a ruby class that is not persisted to the database and it is pretty inconvenient for that state to be lost upon assignment to an attribute of an active record model. 

But more importantly any updates you make to an object assigned to a serialized attribute after you assign it are now lost.
This code, for instance, does not work and it is surprising behavior. If I was assigning a relation instead of a serialized value this code would work as expected.

````ruby
model.thing = thing
thing.property = "new value"

model.thing.property == "new value" #false
````

**Comment by sgrif** [comment]
The answer to both of your questions is because we track mutations. Once you assign a property to an AR object, you're transferring ownership to AR, and should access it accordingly.

```ruby
model.thing = thing
model.thing.property = "new value"

model.thing.property == "new value" #true
```
