### ISSUE TITLE
Request origin does not match request base_url

### ISSUE THREAD

**Issue by tpbowden** [rails/rails#22965]
I am running the Rails 5.0.0 beta1 and after deploying to production have noticed something odd. My application is running being an Nginx reverse proxy which decrypts SSL.

Every time I try to submit a form, a ActionController::InvalidAuthenticityToken is raised. I have managed to narrow this down to [line 399](https://github.com/rails/rails/blob/master/actionpack/lib/action_controller/metal/request_forgery_protection.rb#L399) in ActionController. The problem is that the request origin has `https://` as the protocol and the request base_url has `http://` as the protocol. 

I have tried setting the `X-Forwarded-Proto` header and using `config.force_ssl = true` but neither made any difference. 

I have not yet figured out a way to isolate a failing test case but am happy to look into it if anyone has any suggestions.

**Comment by tpbowden** [comment]
Fix by adding more headers in Nginx (X-Forwarded-Ssl on, X-Forwarded-Port 443 and X-Forwarded-Host hostname)

**Comment by afair** [comment]
I also ran into this issue. I'll describe it differently to help with future searches.

Submission of any form to Nginx proxying to a Puma unix socket running a Rails 5.0.0.beta1 app responds with:

    Can't verify CSRF token authenticity

and throws:

    ActionController::InvalidAuthenticityToken (ActionController::InvalidAuthenticityToken)

even though the App's CSRF is set up correctly. The app works in development (puma or thin, without Nginx), and worked in Nginx/Puma/Rails-4.2. I don't know if this is specific to using Puma, but seems like the same problem could exist with other servers (unicorn, passenger, etc.)

I don't know if this behavior change is an error or intended.

I can confirm @tpbowden's solution worked for me as well.  In my nginx configuration, I setup the app to proxy to puma listening on a unix socket. Here are the relevant parts of the configuration.

    upstream myapp {
      server              unix:///path/to/puma.sock;
    }
    ...
    location / {
      proxy_pass        http://myapp;
      proxy_set_header  Host $host;
      proxy_set_header  X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header  X-Forwarded-Proto $scheme;
      proxy_set_header  X-Forwarded-Ssl on; # Optional
      proxy_set_header  X-Forwarded-Port $server_port;
      proxy_set_header  X-Forwarded-Host $host;
    }

**Comment by tpbowden** [comment]
The issue isn't related to Puma and would happen to any web server running behind a web proxy which isn't passing the correct headers through. The way I managed to figure out how this issue was being caused was by following the error down the stack trace.

The root of the issue is the code in `request.origin == request.base_url`, which compares the `Origin` header's value against the base_url which is build up by a `Rack::Response`. There are 3 parts to this value, the `scheme`, the `host` and the `port`. All three of these are calculated based on a series of headers which are all stripped by default when using a reverse proxy.

You can follow the source for `Rack::Request#base_url` [here](https://github.com/rack/rack/blob/master/lib/rack/request.rb#L409) and it will become clear by looking in your web logs which headers are missing.

**Comment by tpbowden** [comment]
I've just done a bit more research and it is definitely the intended behaviour. It can be disabled in your app config using `config.action_controller.forgery_protection_origin_check = false`. It is enabled by default however.

**Comment by jonnyparris** [comment]
@tpbowden Did you find a solution that doesn't disable forgery protection in the end? I think I'm facing the same problem and really struggling to make 'clean' progress.

**Comment by tpbowden** [comment]
Yes the problem was not passing enough headers through my reverse proxy (nginx) for Rails/Rack to determine whether the request was originally made using https or not (since it was already decrypted by the time it hit Rails)

**Comment by jonnyparris** [comment]
ahh, so how did you find out what was missing...and how did you add the missing headers? Thanks so much for the quick reply!

**Comment by tpbowden** [comment]
If you look at @afair's comment above he was referenced a correct Nginx config, you just need to add the x-forwarded headers related to ssl. I figured out which ones were missing by digging though the source code of Rack's request object to find out how it determine's the protocol of the request.

**Comment by jonnyparris** [comment]
Alas @afair's config doesn't work for me. Moreover, my logs have been annoyingly sparse since adding my Puma config (but that's another story.)
Thanks anyway, I'll think on it.

**Comment by jonnyparris** [comment]
I narrowed my issue down to nginx not playing well with 2 virtual hosts running at the same time. I'm trying to run a staging VPS and a production VPS using [jwilder's nginx-proxy](https://github.com/jwilder/nginx-proxy/). 
Everything works fine using the standard generated conf file when only staging OR production is running. However I run into the `ActionController::InvalidAuthenticityToken` errors on form submissions when both are running at once.
I haven't solved it yet, but thought I'd leave this here in case anyone else follows a similar trail of blunders.

**Comment by straight-shoota** [comment]
Thanks @tpbowden and @afair I was desperatly trying to make any sense of this oddly failing CSRF protection... then I found this issue 👍

**Comment by tripitakit** [comment]
Many thanks @tpbowden and @afair, you've made my day!

**Comment by steady-daddy** [comment]
@afair You, Sir,  has saved a lot of my time. Thank you.

**Comment by marisveide** [comment]
Thanks @tpbowden! You made my day!
This helped! Yeah! ;)

**Comment by stefan694** [comment]
Thanks so much :
I was missing this line : 
`proxy_set_header  X-Forwarded-Proto $scheme;`

**Comment by 1c7** [comment]
@afair  fixed my problem! thank you!

**Comment by Onumis** [comment]
My problem was similar, using heroku and cloudflare, solution was:

> Make sure you have working SSL and HTTPS on Heroku (or wherever you're serving your Rails application.) Turn Cloudflare SSL to Full mode. Problem solved.

from: http://til.obiefernandez.com/posts/875a2a69af-cloudflare-flexible-ssl-mode-breaks-rails-5-csrf

**Comment by nicobobb** [comment]
@Onumis Thank so much! I turn Cloudflare SSL to Full mode and fixed the problem.

**Comment by dchandekstark** [comment]
For those using Apache, this worked for me:

    RequestHeader set X-Forwarded-Proto "https"

**Comment by kkolotyuk** [comment]
This config helped me:
```
  location @app {
    proxy_pass http://127.0.0.1:3000;
    proxy_set_header Host $http_host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_set_header X-SSL-Client-Cert $ssl_client_cert;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_redirect  off;
  }
```

**Comment by voordev** [comment]
> I also ran into this issue. I'll describe it differently to help with future searches.
> 
> Submission of any form to Nginx proxying to a Puma unix socket running a Rails 5.0.0.beta1 app responds with:
> 
> ```
> Can't verify CSRF token authenticity
> ```
> and throws:
> 
> ```
> ActionController::InvalidAuthenticityToken (ActionController::InvalidAuthenticityToken)
> ```
> even though the App's CSRF is set up correctly. The app works in development (puma or thin, without Nginx), and worked in Nginx/Puma/Rails-4.2. I don't know if this is specific to using Puma, but seems like the same problem could exist with other servers (unicorn, passenger, etc.)
> 
> I don't know if this behavior change is an error or intended.
> 
> I can confirm @tpbowden's solution worked for me as well. In my nginx configuration, I setup the app to proxy to puma listening on a unix socket. Here are the relevant parts of the configuration.
> 
> ```
> upstream myapp {
>   server              unix:///path/to/puma.sock;
> }
> ...
> location / {
>   proxy_pass        http://myapp;
>   proxy_set_header  Host $host;
>   proxy_set_header  X-Forwarded-For $proxy_add_x_forwarded_for;
>   proxy_set_header  X-Forwarded-Proto $scheme;
>   proxy_set_header  X-Forwarded-Ssl on; # Optional
>   proxy_set_header  X-Forwarded-Port $server_port;
>   proxy_set_header  X-Forwarded-Host $host;
> }
> ```

I tried this suggestions and still the error persist. 
I restarted all my services. 

Is there any way to debug this? I have spend 3 hours trying to get a solution and not getting a single inch closer to a solution.

**Comment by chris-ritsen** [comment]
Ran into this today. What worked for me to get both http -> http and https -> https was to leave out the `proxy_set_header X-Forwarded-Ssl on` line and rely on `proxy_set_header X-Forwarded-Scheme $scheme;` instead.

**Comment by sekmo** [comment]
> Thanks so much :
> I was missing this line :
> `proxy_set_header X-Forwarded-Proto $scheme;`

Thanks so much! I was missing that as well :-)

**Comment by eloyesp** [comment]
I've just found this issue while using browser-sync as a proxy, fixed it with the following config:

``` js
module.exports = {
  "files": 'app',
  "proxy": {
    "target": "localhost:3005",
    "proxyReq": [
      function (proxyReq) {
        proxyReq.setHeader('Host', 'localhost:3005')
        proxyReq.setHeader('Origin', 'http://localhost:3005')
      }
    ]
  },
  "open": false,
  "reloadDebounce": 500
}
```

This made the trick for me.

**Comment by woooooojianjie** [comment]
Thanks @tpbowden! This helped me !

**Comment by tonytonyjan** [comment]
It might not be related but just for your information.

I recently encountered the same issue. For those who do not use Nginx reverse proxy, you can create a middleware to rewrite `X-Forwarded-Proto` based on Cloudflare `CF-VISITOR` header, here is my solution:

```
# frozen_string_literal: true

require 'json'

class CloudflareProxy
  def initialize(app)
    @app = app
  end

  def call(env)
    return @app.call(env) unless env['HTTP_CF_VISITOR']

    env['HTTP_X_FORWARDED_PROTO'] = JSON.parse(env['HTTP_CF_VISITOR'])['scheme']
    @app.call(env)
  end
end
```

In `config/application.rb`:

```
config.middleware.use CloudflareProxy
```
You can also rewrite `X-Forwarded-Port` and `X-Forwarded-Ssl` and `X-Forwarded-Host` by the same technique. In my case, rewrote only `X-Forwarded-Proto` solved my problem.

A reference for `CF-Visitor` header:

https://support.cloudflare.com/hc/en-us/articles/200170986-How-does-Cloudflare-handle-HTTP-Request-headers-

> CF-Visitor
>
> A JSON object containing only one key called scheme. The value is identical to that of X-Forwarded-Proto (either HTTP or HTTPS). CF-Visitor is only relevant if using Flexible SSL.

**Comment by canriquez** [comment]
> I also ran into this issue. I'll describe it differently to help with future searches.
> 
> Submission of any form to Nginx proxying to a Puma unix socket running a Rails 5.0.0.beta1 app responds with:
> 
> ```
> Can't verify CSRF token authenticity
> ```
> 
> and throws:
> 
> ```
> ActionController::InvalidAuthenticityToken (ActionController::InvalidAuthenticityToken)
> ```
> 
> even though the App's CSRF is set up correctly. The app works in development (puma or thin, without Nginx), and worked in Nginx/Puma/Rails-4.2. I don't know if this is specific to using Puma, but seems like the same problem could exist with other servers (unicorn, passenger, etc.)
> 
> I don't know if this behavior change is an error or intended.
> 
> I can confirm @tpbowden's solution worked for me as well. In my nginx configuration, I setup the app to proxy to puma listening on a unix socket. Here are the relevant parts of the configuration.
> 
> ```
> upstream myapp {
>   server              unix:///path/to/puma.sock;
> }
> ...
> location / {
>   proxy_pass        http://myapp;
>   proxy_set_header  Host $host;
>   proxy_set_header  X-Forwarded-For $proxy_add_x_forwarded_for;
>   proxy_set_header  X-Forwarded-Proto $scheme;
>   proxy_set_header  X-Forwarded-Ssl on; # Optional
>   proxy_set_header  X-Forwarded-Port $server_port;
>   proxy_set_header  X-Forwarded-Host $host;
> }
> ```

This worked great. thanks!

**Comment by ufukayyildiz** [comment]
> I also ran into this issue. I'll describe it differently to help with future searches.
> 
> Submission of any form to Nginx proxying to a Puma unix socket running a Rails 5.0.0.beta1 app responds with:
> 
> ```
> Can't verify CSRF token authenticity
> ```
> 
> and throws:
> 
> ```
> ActionController::InvalidAuthenticityToken (ActionController::InvalidAuthenticityToken)
> ```
> 
> even though the App's CSRF is set up correctly. The app works in development (puma or thin, without Nginx), and worked in Nginx/Puma/Rails-4.2. I don't know if this is specific to using Puma, but seems like the same problem could exist with other servers (unicorn, passenger, etc.)
> 
> I don't know if this behavior change is an error or intended.
> 
> I can confirm @tpbowden's solution worked for me as well. In my nginx configuration, I setup the app to proxy to puma listening on a unix socket. Here are the relevant parts of the configuration.
> 
> ```
> upstream myapp {
>   server              unix:///path/to/puma.sock;
> }
> ...
> location / {
>   proxy_pass        http://myapp;
>   proxy_set_header  Host $host;
>   proxy_set_header  X-Forwarded-For $proxy_add_x_forwarded_for;
>   proxy_set_header  X-Forwarded-Proto $scheme;
>   proxy_set_header  X-Forwarded-Ssl on; # Optional
>   proxy_set_header  X-Forwarded-Port $server_port;
>   proxy_set_header  X-Forwarded-Host $host;
> }
> ```

Thank you so much. Worked for me too.

**Comment by fguillen** [comment]
> Thanks so much :
> I was missing this line :
> `proxy_set_header X-Forwarded-Proto $scheme;`

Also works without the socket thing: 

```
upstream rails_app {
  server app:3000;
}

...
server {
  ...
  location @rails {
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_set_header X-Real-IP  $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header Host $http_host;
    proxy_redirect off;
    proxy_pass http://rails_app;
  }
}
```

**Comment by Furqanameen** [comment]
Thank you so much buddy it's worked for me.
`  location @rails {
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_set_header X-Real-IP  $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header Host $http_host;
    proxy_redirect off;
    proxy_pass http://rails_app;
  }`

**Comment by doughtyorg** [comment]
> My problem was similar, using heroku and cloudflare, solution was:
> 
> > Make sure you have working SSL and HTTPS on Heroku (or wherever you're serving your Rails application.) Turn Cloudflare SSL to Full mode. Problem solved.
> 
> from: http://til.obiefernandez.com/posts/875a2a69af-cloudflare-flexible-ssl-mode-breaks-rails-5-csrf

Thank you, I love you :)

**Comment by Kledal** [comment]
If you are using Dokku and facing this problem, check out this awesome guide https://okhlopkov.com/cloudflare-certificates-dokku/

**Comment by hiveer** [comment]
I'm using Aliyun load balance which is called SLB for my two other application servers. My application servers started at port 3000 and the application server didn't set up ssl.

When the user access my website by https, SLB redirect the request to application server with http. So now we have the issue:
the origin is https, but the request base url is http

The solution for this is to make sure when SLB redirect request to application server we should provided the proxy header: X-Forwarded-Proto

I think the header missing is the root cause for this case.

**Comment by krishnadiamesso** [comment]
> My problem was similar, using heroku and cloudflare, solution was:
> 
> > Make sure you have working SSL and HTTPS on Heroku (or wherever you're serving your Rails application.) Turn Cloudflare SSL to Full mode. Problem solved.
> 
> from: http://til.obiefernandez.com/posts/875a2a69af-cloudflare-flexible-ssl-mode-breaks-rails-5-csrf

Thank you. this solved the issue for me as well 🙏
