### ISSUE TITLE
Documentation for presence validation on boolean field

### ISSUE THREAD

**Issue by flyingL123** [rails/rails#22962]
At the end of the Presence section for active record validations there are examples given of how to deal with the fact that `false.blank?` is true.

http://guides.rubyonrails.org/active_record_validations.html#presence

> Since false.blank? is true, if you want to validate the presence of a boolean field you should use one of  the following validations:

>     validates :boolean_field_name, presence: true
>     validates :boolean_field_name, inclusion: { in: [true, false] }
>     validates :boolean_field_name, exclusion: { in: [nil] }

I think the first example is incorrect. If you use this validation, your validations will fail if `:boolean_field_name` is `false`, which is exactly what the documentation is trying to tell you how to avoid.

**Comment by squaresurf** [comment]
`validates :boolean_field_name, presence: true` will pass if `:boolean_field_name` is `false` due to the fact that `false.blank?` is true.

**Comment by flyingL123** [comment]
Isn't that backwards?

If `:boolean_field_name = false`, and `false.blank? = true`, then the presence validation will fail because it thinks the field is `blank` even though it's not, it's `false`.

**Comment by squaresurf** [comment]
@flyingL123 you're right. I got it backwards.

**Comment by squaresurf** [comment]
I got it in my head the `presense: true` will pass if `object.blank?` is `true`, when in fact it is looking for `!object.blank?`.

**Comment by flyingL123** [comment]
Yea, I think that line should be removed from the docs. It doesn't make any sense.

**Comment by squaresurf** [comment]
@flyingL123 it is fixed on master - https://github.com/rails/rails/blob/master/guides/source/active_record_validations.md#presence

:smile:

**Comment by sgrif** [comment]
Yeah, the documentation on master is correct. Normally I'd backport something like that but given that we're pretty close to master being what's on the site, it's fine.
