### ISSUE TITLE
CSRF validation is not done server side

### ISSUE THREAD

**Issue by lalithr95** [rails/rails#22974]
For rails version 4.1.2 and jquery-rails 2.1.3 setting CSRF header for the ajax requests doesn't validate the token on the server side. 

Following are the manual tests performed.
1. Intercepting request and removing token value - no validation done at server
2. Intercepting request and completely removing token and value - no validation done at server
3. Changing CSRF token value to a new value - no validation done

CSRF token is set beforeSend callback in jquery ajax by setting csrf meta tag content attr.

Only configuration done in rails ApplicationController is protect_from_forgery

**Comment by rafaelfranca** [comment]
Can you please provide a sample application that reproduces the error?

**Comment by victorsosa** [comment]
Quote from Documentation

```
  # GET requests are not protected since they don't have side effects like writing
  # to the database and don't leak sensitive information. JavaScript requests are
  # an exception: a third-party site can use a <script> tag to reference a JavaScript
  # URL on your site. When your JavaScript response loads on their site, it executes.
  # With carefully crafted JavaScript on their end, sensitive data in your JavaScript
  # response may be extracted. To prevent this, only XmlHttpRequest (known as XHR or
  # Ajax) requests are allowed to make GET requests for JavaScript responses.
```
