### ISSUE TITLE
Database migration redo / undo operation should be restricted

### ISSUE THREAD

**Issue by msg7086** [rails/rails#22970]
Accidentally executed migrate:db:redo STEP=2015xxxxxx instead of VERSION=2015xxxxxx and wiped my production database, and following a re-creation, which also eliminates the possible to recover the lost files thereafter.

From my point of view, Rails should refuse to execute such operation if STEP is apparently not correct, especially under **production** environment.

**Comment by rafaelfranca** [comment]
I image that you are frustrated but we don't get feature requests in the issue tracker, so I'm closing this issue. If you interested in working on this please go ahead.

**Comment by schneems** [comment]
If this was on Heroku there is a chance the data can still be recovered. Open a support ticket.

**Comment by msg7086** [comment]
@schneems Thanks, but unfortunately it's not. And I've tried bunch of tools like ext4magic and they could only find the empty table files, not the previous couple gigabytes one. So I guess it's hopeless.
