### ISSUE TITLE
Deprecation warnings not showing the correct location

### ISSUE THREAD

**Issue by bronson** [rails/rails#22982]
While converting my app to rails 5, I see two deprecation warnings showing the wrong 'called from' location.

render :text warning:

> DEPRECATION WARNING: `render :text` is deprecated because it does not actually render a `text/plain` response. Switch to `render plain: 'plain text'` to render as `text/plain`, `render html: '<strong>HTML</strong>'` to render as `text/html`, or `render body: 'raw'` to match the deprecated behavior and render with the default Content-Type, which is `text/plain`. (called from realtime at /Users/bronson/.rubies/ruby-2.2.2/lib/ruby/2.2.0/benchmark.rb:303)

and the kwargs warning:

> DEPRECATION WARNING: ActionController::TestCase HTTP request methods will accept only
keyword arguments in future Rails versions.
>
> Examples:
>
> get :show, params: { id: 1 }, session: { user_id: 1 }
> process :update, method: :post, params: { id: 1 }
> (called from block (2 levels) in <module:Integration> at /Users/bronson/.gem/ruby/2.2.2/gems/rails-controller-testing-0.0.3/lib/rails/controller/testing/integration.rb:12)

and

> DEPRECATION WARNING: ActionController::TestCase HTTP request methods will accept only
keyword arguments in future Rails versions.

> Examples:

> get :show, params: { id: 1 }, session: { user_id: 1 }
> process :update, method: :post, params: { id: 1 }
>  (called from process at /Users/bronson/.gem/ruby/2.2.2/gems/rails-controller-testing-0.0.3/lib/rails/controller/testing/template_assertions.rb:61)

(I suspect that this warning is being printed twice...  can investigate)

Those are the only ones I've noticed, other deprecation warnings work just fine:

> DEPRECATION WARNING: uniq is deprecated and will be removed from Rails 5.1 (use distinct instead). (called from rebuild_relationships at /Users/bronson/propertysearch/app/importers/combined_geography_importer.rb:67)

**Comment by maclover7** [comment]
Can you please provide a sample application that reproduces the error?

**Comment by rafaelfranca** [comment]
The first one is weird but the second is a bug in the `rails-controller-testing` gem. I'll assign the 5.0.0 tag because we need to investigate the first deprecation warning.

**Comment by vipulnsward** [comment]
This seems to be the behaviour since it was first introduced  in https://rails.lighthouseapp.com/projects/8994-ruby-on-rails/tickets/5231-print-stack-traces-with-deprecation-warnings and is being caused by https://github.com/vipulnsward/rails/blob/d47438745e34d75e03347b54b604b71b7a92c3ac/actionpack/lib/action_controller/metal/instrumentation.rb#L43

Perhaps hackishly ignore frame with label  `'realtime'` to ignore this method maybe?

**Comment by dhh** [comment]
@rafaelfranca Is this in or out for 5.0? And if it's in, are you handling it?

**Comment by rafaelfranca** [comment]
Yes, I already have a patch for it. I'll push in a few minutes.
