### ISSUE TITLE
rails console should catch control-c

### ISSUE THREAD

**Issue by eiked** [rails/rails#22995]
I'd like to suggest a change to the rails console.

When I hit Control-C in the rails console, the app goes down.

I'd like to suggest that the rails console should not abort the app on ^C
but instead just return a fresh prompt.

I believe that the rails console repl should behave like a shell.

I believe that ^C (aka intr) when typed in the console should not exit from the repl (or abort the app)
but instead should just return to a fresh input prompt.

For me as a unix worker, ^c means: abort the current action, but I still want to stay in the current shell.
I actually use ^c in my daily live whenever I screwed up an input line, to get a fresh start.
But then when using that in the rails console, I shoot the app.

There obviously needs to be a way to cancel a runaway loop in development mode.
But even then, just exiting the app is not really helpful.

First of all, I'd like to modify the console behavior so that ^c would just clear the last input line instead of exiting from the app (all development mode only)

I'm not so sure what should happen when ^c is hit while the app is not in the repl, but hung in a loop?
have you ever heard about the status signal? (usually bound on ^t) try that with dd

In the console, when in development modus: ^t (aka status) should give a stack backtrace.

^c should bring us back to some known state.

I could even imagine to add binding.intr to mark places in code for debugging.
I believe this could be done:
If a loop is lost you would be thrown back on ^c to a console where the last binding.intr  was set.

I pry

**Comment by eiked** [comment]
http://www.bytecellar.com/wp-content/uploads/2014/06/VisionInBlack_NeXT.mp3

**Comment by rafaelfranca** [comment]
Thank you for the issue but we don't take feature request in the issue tracker. Please read the contributing guides about which is the best channel for them.
