### ISSUE TITLE
Association scope from customization broken in Rails 5

### ISSUE THREAD

**Issue by jturkel** [rails/rails#22996]
Association scope `from` customizations no longer work in Rails 5. Consider the following model:

```ruby
# A contrived example that could be easily represented with a "where" instead
class Blog < ActiveRecord::Base
  has_many :filtered_posts, -> do 
    from("(select * from posts where title like '%post2') as posts") 
  end, class_name: 'Post'
end
``` 
When traversing the `filtered_posts` association the `from` customization is completely ignored and the following SQL is run:

```sql
SELECT "posts".* FROM "posts" WHERE "posts"."blog_id" = ?
```
Previous versions of Rails correctly ran the following SQL:
```sql
SELECT "posts".* FROM (select * from posts where title like '%post2') as posts WHERE "posts"."blog_id" = ?
``` 
[Here](https://gist.github.com/jturkel/09beb87f273453d7639f) is a full executable test case

**Comment by maclover7** [comment]
Can confirm that the test script fails.

**Comment by jturkel** [comment]
It works in 4.2.5.

**Comment by maclover7** [comment]
Would you be able to try and bisect and find out where the error was introduced into the codebase?

**Comment by maclover7** [comment]
Did a `git bisect` and traced error to being introduced in [this commit](https://github.com/rails/rails/commit/bdc5141652770fd227455681cde1f9899f55b0b9). @sgrif, would you be willing to investigate this?

**Comment by idrozd** [comment]
@maclover7 , @jturkel , but it only works when association directly called;
**preload** / **includes** / **joins** / **eager_load** all ignore **from** in has_many in 4.2.7, 4.2.5, 4.1.6, 4.1.16

Is it even possible to make it work this way?

```ruby
class ReleaseDelta < ActiveRecord::Base
  ...
  has_many :dynamic_route_tips, -> do
    from(DynamicRoute.tips, :dynamic_routes)
  end,
  class_name: 'DynamicRoute'
...
```


```ruby
class DynamicRoute < ActiverRcord::Base
  ...
  scope :tips, -> do
    from(select(%[*, RANK() OVER (PARTITION BY identifier, release_delta_id ORDER BY created_at DESC) recency]), table_name).where(recency: 1)
  end
...
```

```ruby
```
