### ISSUE TITLE
Rails new ignores $BUNDLE_PATH

### ISSUE THREAD

**Issue by starkovv** [rails/rails#22991]
Ruby 2.3.0
Rails 4.2.5
Bundler 1.11.2

Given:

```
$GEM_HOME=/home/app/.rvm/gems/ruby-2.3.0
$BUNDLE_PATH=/srv/bundle
```

When I run `rails new my_app` then `bundle install` launches automatically. This way `bundle install`, for some reason, ignores $BUNDLE_PATH variable and installs all the gems to `/home/app/.rvm/gems/ruby-2.3.0`.

**AND**

When I run `rails new -B my_app` then `bundle install` DOES NOT launch automatically. After that I run `bundle install` explicitly, and everything goes fine, $BUNDLE_PATH worked and all the gems has been installed to `/srv/bundle`.

Is it kinda bug or something?

**Comment by rhizome** [comment]
This appears to be due to Rails' invocation of Bundler#with_clean_env

https://github.com/rails/rails/blob/master/railties/lib/rails/generators/app_base.rb#L355-L356

...which throws away BUNDLE_* environment variables:

https://github.com/bundler/bundler/blob/master/lib/bundler.rb#L210

**Comment by starkovv** [comment]
@rhizome Your're right.

Why is they doing this?

**Comment by rhizome** [comment]
I don't know.

**Comment by arthurnn** [comment]
@indirect any clue on this? Is it the right thing to call `Bundler.with_clean_env` in our generator?

**Comment by Anagha22** [comment]
I need to point out one thing.Even if we are using $rails new app_name, bundle install won't  launch automatically.We need to run it explicitly. (Ruby version: 2.1.5, Rails version:  4.2.5 ).I guess gems are installed to the path " /srv/bundle " itself.

**Comment by arthurnn** [comment]
seems like this is a 5 years code we have in our generators: 
https://github.com/rails/rails/commit/aed906af97cfa86801951a6a97251084fac6dc57
https://github.com/rails/rails/commit/7fc4b4681b83b86d5871f0726460ea808bd76f1b

That seem like it was there to prevent some old bundler failures. I wonder if we can remove that `with_clean_env` call now?

cc @drogus @mpapis

**Comment by mpapis** [comment]
`with_clean_env` is required to prevent running `bundler` in wrong context, obviously it does not take into account environment had an earlier state -  this most likely can be fixed in bundler - @indirect?
