### ISSUE TITLE
Confusion between translate in controller and view

### ISSUE THREAD

**Issue by nartz** [rails/rails#22994]
This is just a suggestion:

Currently, calling the translate method in a controller versus a view leads to different rendering of strings, for instance:

... controller ....
@myvar = t(:some_message)

....view....
<p><%= t(:some_message) %></p>
<p><%= @myvar %></p>

....rendered view:
Some Message
translation missing: en.some_message

Both action controller and action view seem to wrap and apply their own notions of what translate() should do, and it makes it very confusing, especially for newcomers. The main options are to call the I18n.translate directly in all cases ( to get consistent behavior no matter where calling it) - but this seems like a workaround to get 'consistency'.

Maybe it would be better simply to have the method in the view that adds additional logic called something different, for instance, pretty_translate() so it isn't confused or something along those lines.

Just a suggestion for improvement.

**Comment by matthewd** [comment]
Thanks, but we don't take feature requests on the issue tracker.

**Comment by nartz** [comment]
where is the right place to suggest something like this? Wouldn't you say that having the same method name have different functionality in different contexts is extremely confusing and non-intuitive, violating the 'principle of least suprises' ?
