### ISSUE TITLE
Can rails generate scaffold with namespace Controller and non-namespace Model?

### ISSUE THREAD

**Issue by tuanminh20** [rails/rails#23002]
Something like using several controllers in namespace:
> 'controllers/zoo/cats_controller.rb'
> 'controllers/home/cats_controller.rb'
> 'controllers/wild/cats_controller.rb'

but only one Model
> 'models/cat.rb'

I tried 
> rails g model cat name
> rails g scaffold_controller zoo/cat name --model-name=cat
> (OR --model-name=zoo/cat)
> then edit routes file, even edit Model to Zoo::Cat

But nothing works, with errors like:
> unknown method cat_path
> Unsuccessfully autoload contants
> form helper doesn't work

I've just asked a question on [stackoverflow](http://stackoverflow.com/questions/34706572/rails-4-generate-scaffold-controller-with-existed-model-it-only-works-after-re), please read.

**Comment by maclover7** [comment]
Please use the mailing list or StackOverflow for questions/help, where a wider community will be able to help you. We reserve the issues tracker for issues only.
