### ISSUE TITLE
Asset not precompiled in manifest.js Rails 5.0.0.beta1

### ISSUE THREAD

**Issue by msroot** [rails/rails#23000]
the default `manifest.js` is 

`//= link_tree ./images
//= link ./javascripts/application.js
//= link ./stylesheets/application.css
`

but when i run the server i get an error

Sprockets::Rails::Helper::AssetNotPrecompiled at /pages
Asset `application.css` was not declared to be precompiled in production.
Declare links to your assets in `assets/config/manifest.js`.
Examples:
`//= link ../javascripts/application.js`
`//= link_directory ../javascripts .js`
`//= link_directory ../stylesheets .css`
`//= link_tree ../javascripts .js`
`//= link_tree ../images`
and restart your server

2 things to consider here: 

 - Why do i get the error?
 - The default links in `manifest.js` are with one `.` and in the exeption with `..`

My `Gemfile`

```ruby 
source 'https://rubygems.org'

ruby "2.2.3"

group :production do
  gem 'pg'
  gem 'rails_12factor'
end

gem 'rails', github: "rails/rails"
gem 'sprockets-rails', github: "rails/sprockets-rails"
gem 'sprockets', github: "rails/sprockets"
gem 'sass-rails', github: "rails/sass-rails"
gem 'arel', github: "rails/arel"
gem 'rack', github: "rack/rack"
gem 'rails_serve_static_assets', github: "heroku/rails_serve_static_assets"
gem 'puma'

gem 'simple_form'
# Use sqlite3 as the database for Active Record
# Use Uglifier as compressor for JavaScript assets
gem 'uglifier', '>= 1.3.0'
# Use CoffeeScript for .coffee assets and views
# gem 'coffee-rails', github: "rails/coffee-rails"

# See https://github.com/rails/execjs#readme for more supported runtimes
# gem 'therubyracer', platforms: :ruby

# Use jquery as the JavaScript library
gem 'jquery-rails'
# Turbolinks makes following links in your web application faster. Read more: https://github.com/rails/turbolinks
gem 'turbolinks'
# Build JSON APIs with ease. Read more: https://github.com/rails/jbuilder
gem 'jbuilder', '~> 2.0'
# Use ActiveModel has_secure_password
# gem 'bcrypt', '~> 3.1.7'

# Use Unicorn as the app server
# gem 'unicorn'

# Use Capistrano for deployment
# gem 'capistrano-rails', group: :development

group :development do
  # Access an IRB console on exception pages or by using <%= console %> in views
  gem 'web-console', github: 'rails/web-console'
  gem 'spring'
  gem 'byebug'
  gem "better_errors"
  gem "binding_of_caller"
  gem 'pry'
  gem 'sqlite3'
end
```

Using: `Rails 5.0.0.beta1`

**Comment by maclover7** [comment]
I think your config/manifest.js is just supposed to have this:
`//= link_directory ../stylesheets .css`

while yours has this: `//= link ./stylesheets/application.css`

Is this correct?

**Comment by msroot** [comment]
yes it should have this `//= link_directory ../stylesheets .css`
but i dont know how this generated `//= link ./stylesheets/application.css` 

I make  a new app and it has this now `//= link_directory ../stylesheets .css` and it works fine

**Comment by msroot** [comment]
So please @maclover7  you can close it! Thanks anyway. No idea how the first file generated

**Comment by maclover7** [comment]
No problem!
