### ISSUE TITLE
Json gem not installing in mac osx. 

### ISSUE THREAD

**Issue by kirubaebe** [rails/rails#23016]
I am having Mac os x 10.11... But when i am trying to install the json gem then it is showing like this...

---------------------------------------------------------------------------------
Installing json 1.7.7 with native extensions

Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

    /Users/kirubaebenezerramanathan/.rbenv/versions/2.2.3/bin/ruby -r ./siteconf20160111-86468-143vkc3.rb extconf.rb
creating Makefile

make "DESTDIR=" clean

make "DESTDIR="
compiling generator.c
In file included from generator.c:1:
./../fbuffer/fbuffer.h:175:47: error: too few arguments provided to function-like macro invocation
    VALUE result = rb_str_new(FBUFFER_PAIR(fb));
                                              ^
/Users/kirubaebenezerramanathan/.rbenv/versions/2.2.3/include/ruby-2.2.0/ruby/intern.h:793:9: note: macro 'rb_str_new' defined here
#define rb_str_new(str, len) __extension__ (    \
        ^
In file included from generator.c:1:
./../fbuffer/fbuffer.h:175:11: warning: incompatible pointer to integer conversion initializing 'VALUE' (aka 'unsigned long') with an expression of type 'VALUE (const char *, long)' [-Wint-conversion]
    VALUE result = rb_str_new(FBUFFER_PAIR(fb));
          ^        ~~~~~~~~~~
1 warning and 1 error generated.
make: *** [generator.o] Error 1

make failed, exit code 2

---------------------------------------------------------------------------------------------------------------------------

I have googled and updated the version of json 1.7.7 to 1.8.1 again it is showing the same...

Also it is showing incompatible version with Ruby 2.x....

**Comment by Strnadj** [comment]
@kirubaebe Please check: https://github.com/flori/json/issues/229 They fixed your issue in 1.8.2. This is not an rails issue actually

**Comment by medicsmarket** [comment]
**First, check if you have Xcode installed**  
**Second, if you already have Xcode in your Mac, use this command**  

    CC=gcc rvm install-version
**Example**  

    CC=gcc rvm install-1.9.3


**Reason for this error in Mac OS is that your Ruby is not able to get the C header files**  

Hope, this works on all the Macbook's.  
**Its working on El Capitan, ruby 1.9.3, rails 3.2, mysql 5.7**

**Comment by danman01** [comment]
Seems json 1.8.3 does the trick http://fuzzyblog.io/blog/ruby/2016/10/11/what-to-do-when-bundle-install-fails-with-json-1-8-1.html
