### ISSUE TITLE
Migration versioning not mentioned in ActiveRecord changelog

### ISSUE THREAD

**Issue by radar** [rails/rails#23021]
[The edge migration guide](http://edgeguides.rubyonrails.org/active_record_migrations.html) shows a new syntax for migrations, specifically: `ActiveRecord::Migration[5.0]`. It looks like this was added by @matthewd in 6940dc860c4b25bff2eded370f2af4316de15a30, but it wasn't documented in the CHANGELOG for AR.

**Comment by senny** [comment]
@radar I've added an example to the existing entry in the changelog. If there is something that needs to be performed when upgrading to Rails 5.0 it will be mentioned in the [Upgrading Guide](http://edgeguides.rubyonrails.org/upgrading_ruby_on_rails.html#upgrading-from-rails-4-2-to-rails-5-0) once Rails 5.0 is released.

Thanks for reporting :yellow_heart:
