### ISSUE TITLE
ActionController::Parameters#as_json has changed format

### ISSUE THREAD

**Issue by claudiob** [rails/rails#23026]
`ActionController::Parameters#as_json` does not behave in the same way under Rails 4.2 and under Rails 5.0.0.beta1.

In my opinion, this is a regression and can easily be fixed, but before submitting a patch, I would like to know the opinion of @sikachu who worked on having AC::Parameters not inherit from Hash https://github.com/rails/rails/pull/14384.

Reproducing the issue is really easy: just run `ActionController::Parameters.new(hello: :world).as_json`.

```ruby
# under Rails 4.2
ActionController::Parameters.new(hello: :world).as_json
# {"hello"=>"world"}

# under Rails 5.0.0.beta1
ActionController::Parameters.new(hello: :world).as_json
# => {"parameters"=>{"hello"=>"world"}, "permitted"=>false} 
```

The reason is that [Object#as_json](https://github.com/rails/rails/blame/f718e52bcce02bc137263ead3a9d9f5df1c42c37/activesupport/lib/active_support/core_ext/object/json.rb#L49) checks whether the object `respond_to?(:to_hash)` and, [as already commented](https://github.com/rails/rails/pull/18006#issue-51798294), `ActionController::Parameters#to_hash` will no longer work in Rails 5.0+ as we stop inheriting Parameters from Hash.

**Comment by maclover7** [comment]
Is the solution to use `ActionController::Parameters#to_unsafe_hash`? Not a fan of the idea that we would have to possibly write over the existing `Object#as_json` monkey patch with another monkey patch, to change it to use `to_unsafe_hash` instead of `to_hash`...

**Comment by sikachu** [comment]
I think it's just a side-effect that was overlooked when I disconnected the Hash. I think the expected result should be a linear-ish Hash, as in Rails 4.2, a la  `{"hello"=>"world"}` should be the expected result.

Regarding the other issue, I think it's better to keep using `to_h`. If user want to print out the whole params without caring about the whitelisting they can already do `to_unsafe_h`. I don't feel like exposing the unsafe hash by default is a great idea.

**Comment by claudiob** [comment]
@sikachu If I understand correctly, you propose to add an `as_json` method to the `ActionController::Parameters` class defined like this?

```ruby
def as_json(options = nil)
  to_h.as_json(options)
end
```

**Comment by sikachu** [comment]
@claudiob that's correct, or you can just use `delegate` as well.

**Comment by claudiob** [comment]
Ok, I'll write that!
