### ISSUE TITLE
Rails installation Invalid gem : package is Corrupt-nokogiri 

### ISSUE THREAD

**Issue by vigneshblue** [rails/rails#23029]
I was trying to install rails in ubuntu 14.04 but I am getting the following error.

$gem install rails
ERROR:  Error installing rails:
    invalid gem: package is corrupt, exception while verifying: undefined method `size' for nil:NilClass (NoMethodError) in /home/usr/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/cache/nokogiri-1.6.7.1.gem

Please Help with this.
Thank You.

**Comment by rafaelfranca** [comment]
Please use the mailing list or StackOverflow for questions/help, where a wider community will be able to help you. We reserve the issues tracker for issues only.

**Comment by vigneshblue** [comment]
Thank you very much dude.
