### ISSUE TITLE
Wrong Julian Date returned from `strftime` on `TimeWithZone` at end of year

### ISSUE THREAD

**Issue by agfor** [rails/rails#23033]
Since https://github.com/rails/rails/commit/1897d3a5d240a962dc89d2cab1d36bedb08974f7 (in 4.2.0beta4), the wrong Julian Day is being returned from `strftime` for `TimeWithZone` objects with nonzero UTC offsets during the period between midnight in the given time zone and midnight UTC on the last day of the year.

My current solution is to revert that commit.

Failing test:

```
diff --git a/activesupport/test/core_ext/time_with_zone_test.rb b/activesupport/test/core_ext/time_with_zone_test.rb
index 7acada0..af5562a 100644
--- a/activesupport/test/core_ext/time_with_zone_test.rb
+++ b/activesupport/test/core_ext/time_with_zone_test.rb
@@ -13,6 +13,10 @@ class TimeWithZoneTest < ActiveSupport::TestCase
     @twz = ActiveSupport::TimeWithZone.new(@utc, @time_zone)
   end

+  def test_julian_day
+    assert_equal "365", @utc.in_time_zone(@time_zone).strftime("%j")
+  end
+
   def test_utc
     assert_equal @utc, @twz.utc
   end

```

`"364"` is returned instead of `"365"` between midnight UTC and midnight in Eastern time. After midnight Eastern time, `"001"` is correctly returned, and before midnight UTC `"365"` is correctly returned. I haven't tested time zones ahead of UTC, only behind.

**Comment by pixeltrix** [comment]
@agfor I can reproduce this - it only appears to be a problem for negative UTC offsets - positive offsets return 365 all day. I'm investigating it further.

**Comment by pixeltrix** [comment]
@agfor looks like this maybe an underlying bug in Ruby:

``` bash
$ irb
>> t = Time.new(2015, 12, 31, 22, 0, 0, "-05:00")
=> 2015-12-31 22:00:00 -0500 
>> t.strftime('%j')
=> "364" 
```

We'll have to raise it on the Ruby bug tracker.

**Comment by agfor** [comment]
@pixeltrix Interesting.

**Comment by pixeltrix** [comment]
Bug filed: https://bugs.ruby-lang.org/issues/11994

**Comment by agfor** [comment]
Great!

**Comment by agfor** [comment]
I think this still needs a Rails-level fix as it's broken in all current versions of Ruby.

**Comment by pixeltrix** [comment]
@agfor I will try to get the Ruby issue re-raised - I think it got missed with the kerfuffle over the CoC issue.

**Comment by pixeltrix** [comment]
@agfor the Ruby bug has been fixed! 🎉
