### ISSUE TITLE
After upgrade to Postgres 9.5, rake db:migrate fails with "pg_dump: invalid option -- i"

### ISSUE THREAD

**Issue by ianhall** [rails/rails#23039]
The error comes from `activerecord-4.2.1/lib/active_record/tasks/postgresql_database_tasks.rb:55`

The Postgres 9.4 docs (http://www.postgresql.org/docs/9.4/static/app-pgdump.html) say:
`-i
--ignore-version
A deprecated option that is now ignored.`

The 9.5 docs do not mention this option at all.

**Comment by matthewd** [comment]
https://github.com/rails/rails/issues/23030#issuecomment-171084067
