### ISSUE TITLE
Convert Foo::Bar to foo_bars

### ISSUE THREAD

**Issue by jarosluv** [rails/rails#23044]
I think that is must be method for convert class name to path name (or method name), like `tableize`, but with correct handling of modules.

I want to convert `Foo::Bar` to `foo_bars` (or `foo_bar`), not `foo/bar`.
It is standard purpose and I think its must be standardise in API, because this is bad piece of code 
```
klass.to_s.tableize.gsub("/", "_")
```
Sample of this issue in popular repository https://github.com/activeadmin/activeadmin/blob/5f190fba809a20f3cae83cc547d1a9003e91193f/lib/generators/active_admin/install/install_generator.rb#L14

**Comment by maclover7** [comment]
Thank you for the issue but we don't take feature request in the issue tracker. Please read the contributing guides about which is the best channel for them.
