### ISSUE TITLE
Unable to access `rails console` or see `rails -v` on production server [rails 4.2.x]

### ISSUE THREAD

**Issue by marvindanig** [rails/rails#23053]
Hello,

I have a `rails 4.2.3` application on production `rbenv 0.4.0` / `ruby 2.2.2p95 (2015-04-13 revision 50295) [x86_64-linux]` and everything is working just about fine. The site is live, everything is functional as expected. But I'm not able to open the rails console on production server. 

`$ rails c production` returns the following:

```
The program 'rails' can be found in the following packages:
 * ruby-railties-3.2
 * ruby-railties-4.0
Ask your administrator to install one of them
```

`$ rails -v ` also returns the same message. Came across the following [question/discussion](http://stackoverflow.com/questions/28243043/cannot-start-rails-4-console-on-production-server) on stackoverflow, but it doesn't solve the issue for me. 

Is everyone else able to access the console? Am I missing something?

**Comment by GRoguelon** [comment]
Hi,

Have you tried this command at the root of your project: 

```ruby
./bin/rails c production
```

For your version of Rails, you have a binary folder containing a `rails` binary.

**Comment by prathamesh-sonpatki** [comment]
@marvindanig Hi, We reserve the issue tracker only for bug reports. Please post your question to mailing list/Stackoverflow where a wider community can help you.

Thanks.

**Comment by marvindanig** [comment]
@GRoguelon I do have the ruby sh script `.bin/rails` that requires `rails/commands` in there. 

```
#!/usr/bin/env ruby
APP_PATH = File.expand_path('../../config/application', __FILE__)
require_relative '../config/boot'
require 'rails/commands'
```

Given that `rails -v` isn't returning the version of rails installed I suppose what's missing here is 'rails/commands'. `$ which rails` doesn't return with anything though.

**Comment by marvindanig** [comment]
@prathamesh-sonpatki Github says 'Issues' pretty clearly on the tab of every repository up here. 

It is inappropriate (not just rude) to change the meaning of 'whatever' is tracked over here and then close the issue prematurely; even when the discussion is hot. I request to reopen the ticket, and wait until it is clear that the issue you see as only "mine" is also a bug that you seek.

**Comment by kaspth** [comment]
@marvindanig every repository is free to tune the meaning of "Issues" to what we describe in our contributing guidelines.

We also prefer to keep issues we know are actual bugs open. The onus is on you to prove it's a bug. You will find more help in doing so by writing about the usage problem on the Rails Talk mailing list. Please do investigate 😁

**Comment by prathamesh-sonpatki** [comment]
@marvindanig It looks like the issue is with how rails is setup on the server as it is not able to find the `rails` binary based on the messages for `rails -v` and `rails console production`.  That's why I closed it :)

**Comment by marvindanig** [comment]
Peace :+1:
