### ISSUE TITLE
set_backtrace is called with the wrong arguments

### ISSUE THREAD

**Issue by afn** [rails/rails#23058]
With activesupport-5.0.0.beta1 and ruby 2.3.0, I get the following error if I set `config.active_support.deprecation = :raise` (and I have deprecations in my app):

```
.../activesupport-5.0.0.beta1/lib/active_support/deprecation/behaviors.rb:16:in `set_backtrace': backtrace must be Array of String (TypeError)
```

The reason is that `set_backtrace` is [being called](https://github.com/rails/rails/blob/27eccc27cbe987be04bb97b49aff1d7fd118634c/activesupport/lib/active_support/deprecation/behaviors.rb#L12) with the [return value of `caller_locations`](https://github.com/rails/rails/blob/491f488f5ac4e50abfbd1a434971e41e48aa2f15/activesupport/lib/active_support/deprecation/reporting.rb#L17-L20), which is an array of `Thread::Backtrace::Location`.

I guess the fix would be to modify `behaviors.rb`:

```ruby
e.set_backtrace(callstack.map(&:to_s))
```

although it seems silly to me that `set_backtrace` can't be called with `caller_locations` directly, so maybe a Ruby bug would be in order too.

**Comment by rafaelfranca** [comment]
@tenderlove what do you think?

**Comment by tenderlove** [comment]
Ya, I think just converting to strings would be the easiest for now.  IIRC, using caller locations was an optimization.  If you're opting in to `raise`, then you're opting out of some speed improvement.  But, presumably you're going to fix the warnings, so you wouldn't go down this codepath anyway.

:+1:

**Comment by maclover7** [comment]
@afn Can you open up a PR for this?
