### ISSUE TITLE
Rails 5 routing issue with prefixed optionals

### ISSUE THREAD

**Issue by tagliala** [rails/rails#23069]
Hi,

I'm experiencing an issue with rails 5.0.0.beta1 also present on the master branch

It's about paths with prefixed optionals, like:

```rb
get 'prefixed_optional(/p-:page)', to: 'test#prefixed_optional', as: :prefixed_optional
```

Executable test cases:

### Master
https://gist.github.com/tagliala/99239dd2ab599cec5e41#file-test_master-rb

```
# Running:

D, [2016-01-15T14:33:44.437701 #57966] DEBUG -- : 
D, [2016-01-15T14:33:44.437808 #57966] DEBUG -- : 
I, [2016-01-15T14:33:44.438191 #57966]  INFO -- : Started GET "/prefixed_optional/p-12" for 127.0.0.1 at 2016-01-15 14:33:44 +0100
F, [2016-01-15T14:33:44.439684 #57966] FATAL -- : 
ActionController::RoutingError (No route matches [GET] "/prefixed_optional/p-12"):
  test.rb:49:in `test_returns_success'


F

Finished in 0.041807s, 23.9193 runs/s, 23.9193 assertions/s.

  1) Failure:
BugTest#test_returns_success [test.rb:50]:
Failed assertion, no message given.

1 runs, 1 assertions, 1 failures, 0 errors, 0 skips
```
### 4.2.5
https://gist.github.com/tagliala/99239dd2ab599cec5e41#file-test_425-rb

```
# Running:

D, [2016-01-15T14:33:27.352895 #57954] DEBUG -- : 
D, [2016-01-15T14:33:27.352964 #57954] DEBUG -- : 
I, [2016-01-15T14:33:27.353285 #57954]  INFO -- : Started GET "/prefixed_optional/p-12" for 127.0.0.1 at 2016-01-15 14:33:27 +0100
.

Finished in 0.041603s, 24.0369 runs/s, 24.0369 assertions/s.

1 runs, 1 assertions, 0 failures, 0 errors, 0 skips
```

**Comment by maclover7** [comment]
Thank you for reporting! Would you be will to do a Git bisect to try and find where the errant behavior was introduced?

**Comment by tagliala** [comment]
@maclover7 you're welcome!

It should be this commit: https://github.com/rails/rails/commit/d993cb362969caa2cb3b3f2f86ddf653d34dfb1b

**Comment by maclover7** [comment]
^ ping @tenderlove

**Comment by eileencodes** [comment]
@tagliala this should be fixed now. Thanks for your help with the script and bisect :smile_cat:

**Comment by tagliala** [comment]
Thank you all!

**Comment by tagliala** [comment]
My test is still failing, is this normal?

**Comment by maclover7** [comment]
Can confirm that it's still failing :(. ping @eileencodes

**Comment by eileencodes** [comment]
Ah my test was flawed. I have a fix but it adds more allocations back so going to work on this a bit more. Will let you know when it's fixed, possibly not til next week.

**Comment by pixeltrix** [comment]
It's because the preceding path segment is static but @eileencodes's test has a dynamic segment, e.g. `artist` vs. `:artist`.

I may be mistaken but from what I can determine the `-` we are adding to the regexp is actually irrelevant, the important change is that the regexp is changed from the default and so goes from anchored routes into custom routes internally inside of Journey. I think we need have a rethink what we're doing in this section of mapper.rb.
