### ISSUE TITLE
rake minitest fails with rake task including url_helpers

### ISSUE THREAD

**Issue by erpe** [rails/rails#23066]
When creating a custom rake task below lib/tasks which includes Rails.application.routes.url_helpers
Then 'rake test' errors - (tested with 4.2.4 and 4.2.5)
e.g.:

```
# lib/tasks/foo.rake
include Rails.application.routes.url_helpers
require "#{Rails.root}/app/helpers/tools_helper"      
include ToolsHelper

desc "this task makes use of route_helpers"
task do_something: :environment do
  Rake::Task['smthng:create_tools'].invoke
  Rake::Task['smthng:collect_urls'].invoke
  @myurls.each_pair do |k,v|
    puts "#{k} -> #{v}"
  end
end
```
works:
```
rake do_something
```
errors: 
```
rake test
```
produces
```
 1) Error:
 ToolsControllerTest#test_should_get_edit:
 ActionView::Template::Error: arguments passed to url_for can't be handled. Please require routes or  provide your own implementation
   app/views/tools/edit.html.erb:5:in `_app_views_tools_edit_html_erb___1103415953847731251_37693160'
   test/controllers/tools_controller_test.rb:33:in `block in <class:ToolsControllerTest>'
```
see proof: https://github.com/erpe/rails-minitest-fails-with-task

@zenspider @tenderlove

**Comment by rafaelfranca** [comment]
When you call `url_helpers` you are memoizing its value. When you run the tests you memoized the routes without the proper information so its don't know how to handle correctly the options in your view. You should not include `url_helpers` in main context. Unfortunately there is nothing what we can do here.
