### ISSUE TITLE
Document "bang" version for query methods

### ISSUE THREAD

**Issue by jlecour** [rails/rails#23064]
Hi,

Here is a basic example of using query methods sequentially, depending on conditions : 

```ruby
# start with an unscoped Relation for the User model
users_rel = User.all
# conditionally add query methods
users_rel = users_rel.limit(params[:limit]) if params[:limit]
users_rel = users_rel.includes(:profile) if params[:include_profile]
# fetch the records
users = users_rel.all
```

Using the bang versions of those query methods we can have this : 

```ruby
# start with an unscoped Relation for the User model
users_rel = User.all
# conditionally add query methods
users_rel.limit!(params[:limit]) if params[:limit]
users_rel.includes!(:profile) if params[:include_profile]
# fetch the records
users = users_rel.all
```

Whether or not it's more readable might be discussed, but I wonder why those methods are not documented.

Here is link to an example : https://github.com/rails/rails/blob/master/activerecord/lib/active_record/relation/query_methods.rb#L165

**Comment by rafaelfranca** [comment]
These methods are private API of the framework are should not be used in applications. This is exactly the reason that they are not documented. We only document public API methods.
