### ISSUE TITLE
ActiveJob around_perform is called twice when defined on superclass

### ISSUE THREAD

**Issue by joelpresence** [rails/rails#23061]
Hi,

Thanks for all of your hard work on Rails!  :-)

Suppose I have the following:

```
# In app/jobs/my_base_job.rb
class MyBaseJob < ActiveJob::Base
  around_perform do |job, block|
    puts "Hello, from around_perform!"

    # Do some common stuff like setup timing

    block.call

    # Do some common stuff like finalize timing and report metrics to external service
  end
end

# In app/jobs/my_extended_job.rb
class MyExtendedJob < MyBaseJob
  # NOTE: I do NOT define or refer to around_perform here in any way
end
```

Now, if I enqueue a job as in `MyExtendedJob.perform_later` then the around_perform block, defined in `MyBaseJob` is called twice.  This is unexpected and a bug.  It also makes it hard to extend our own tree of ActiveJob classes and share common callbacks with the superclass.

I am using rails 4.2.5, resque 1.25.2 and ruby 2.2.2p95 on OS X 10.10.5.

I know that I _could_ do something like the following:

```
# In app/jobs/my_base_job.rb
def common_stuff(job, block)
    puts "Hello, from around_perform!"

    # Do some common stuff like setup timing

    block.call

    # Do some common stuff like finalize timing and report metrics to external service
end

class MyBaseJob < ActiveJob::Base
  # No longer invoke around_perform here
end

# In app/jobs/my_extended_job.rb
class MyExtendedJob < MyBaseJob
  # Moved around_perform
  around_perform do |job, block|
    common_stuff job, block
  end
end
```

However, that approach has two very serious problems:
1. If I create a class `MyReallyExtendedJob < MyExtendedJob` then the double-invocation of `around_perform` would just return.
2. Now I need documentation that each subclass of `MyExtendedJob` needs to define its `around_perform` in the way shown above and that's prone to omission and error and adds considerable overhead to and considerably reduces the convenience of, subclassing `MyExtendedJob`.

I also tried rails concerns but that got Rails stuck in some infinite loop.

This is definitely a bug - it violates the principle of least surprise, it is not the expected behavior and it makes it much harder to usefully extend ActiveJob::Base.

What can we do to fix this?  :-)

**Comment by maclover7** [comment]
I think the issue here is that the `around_perform` is being called when the job is created/being first put into the queue, and then again when the job is actually being executed. Thank you for reporting! Would you be able to confirm that this is still a bug on Rails master?

**Comment by joelpresence** [comment]
Thanks @maclover7 !  To check on Rails master, would you suggest I just `git clone` the HEAD of rails on the master branch and create a test project or refer to the git repo in my Gemfile?

**Comment by maclover7** [comment]
Either would work fine. Might be easier to just create a test project. You could also try and use one of the [test scripts](https://github.com/rails/rails/tree/master/guides/bug_report_templates) if you want to, to avoid creating an entire application.

**Comment by piotrj** [comment]
I tried to reproduce but couldn't reproduce. I tried both on master rails and on '4.2.5'. Maybe there is something specific in resque configuration.

Here is the script I used: https://gist.github.com/piotrj/fb640c59707fc7387237

@joelpresence can you try and modify that script so that you get the broken behavior.
