### ISSUE TITLE
Setting connection pool size to zero behaves as a pool of size one

### ISSUE THREAD

**Issue by johnkolen** [rails/rails#23073]
Setting a pool size of zero should force a new connection for each request. When a connection is checked back in, it is always added to the queue of available connections. The first action of acquire_connection is to pull from the available queue. Even when size is zero, the second pool checkout will return the connection returned after the first checkout.

One possible solution is to maintain the size invariant on @available in addition to @connections during check in. 

We have an external DB where we need to close connections after use, so we really don't want to reuse connections.

**Comment by schneems** [comment]
i don't think active record was designed to be used like that, this is more of a feature request than a bug report

**Comment by yahonda** [comment]
I also think this is kind of a feature request to Rails. I recall there is a gem which may satisfy your requirement. https://github.com/sonots/activerecord-refresh_connection

**Comment by maclover7** [comment]
Thank you for the issue but we don't take feature request in the issue tracker. Please read the contributing guides about which is the best channel for them.
