### ISSUE TITLE
Module Constants Inconsistencies 4.2.5

### ISSUE THREAD

**Issue by eman8519** [rails/rails#23072]
First timer here with opening issues, so hopefully this goes well.

I'm seeing issues with module constants in **Rails 4.2.5** which also seem to be causing issues with inherited `before_action` as well.  The problem is completely erratic, sometimes everything works as expected, other times it doesn't work.  The worst part is the behavior changes without any changes to the source code, but rather simply an auto-reload (see below for more info on this).

There are two issues I'm seeing.  One is with `before_action`, and the other is with constants look up.

Inherited `before_action` seems be skipped for subclasses of `Api::V2::ApiController` which result in: 

```
Started GET "/api/v2/tickets" for 127.0.0.1 at 2016-01-15 12:20:11 -0500
Processing by Api::V2::TicketsController#index as JSON
Geokit is using the domain: localhost
Completed 500 Internal Server Error in 1ms (ActiveRecord: 0.0ms)

NoMethodError - undefined method `id' for nil:NilClass:
```

The other issue I'm seeing is with constant lookups within the same module which result in errors like below (this example is from me trying to make a payment on a closed ticket, see relevant files below):

```
Started POST "/api/v2/tickets/940/payments/" for 127.0.0.1 at 2016-01-15 12:00:41 -0500

Processing by Api::V2::Tickets::PaymentsController#create as JSON
  Parameters: {"ticket_id"=>940, "payment"=>{"payment_amount"=>2.4, "total_amount"=>2.76, "rating"=>5, "tip_amount"=>0.36}}
...
Completed 500 Internal Server Error in 8ms (ActiveRecord: 1.0ms)

NameError - uninitialized constant Api::V2::UnprocessableEntityError:
```

Now here is the kicker!  When I edit the source code while the rails sever is running in development environment (trying to highlight the fact that controller files are reloaded in development env), I get the result you would expect for both requests. Even if all I change is adding a newline and saving then remove the same newline and saving again:

Response given when before_action runs as expected:

```
Started GET "/api/v2/tickets" for 127.0.0.1 at 2016-01-15 12:37:42 -0500
Processing by Api::V2::TicketsController#index as JSON
Geokit is using the domain: localhost
Completed 401 Unauthorized in 2ms (Views: 0.2ms | ActiveRecord: 0.0ms)
```

Response given when constant lookups work as expected:

```
Started POST "/api/v2/tickets/940/payments" for 127.0.0.1 at 2016-01-15 12:40:02 -0500
Processing by Api::V2::Tickets::PaymentsController#create as JSON
  Parameters: {"ticket_id"=>940, "payment"=>{"payment_amount"=>2.4, "total_amount"=>2.76, "rating"=>5, "tip_amount"=>0.36}}
...
Completed 422 Unprocessable Entity in 6ms (Views: 0.3ms | ActiveRecord: 1.0ms)
```

Here are the relevant files showing the issue:

``` ruby
config/routes.rb

MyApp::Application.routes.draw do
  ...
  namespace :api, :constraints => {:format => /(json)/}, :defaults => { :format => 'json' } do
    namespace :v2 do
      resources :tickets, module: 'tickets', only: [:index, :show] do
        resources :payments, only: [:index, :create]
      end

      resources :payments, only: [:show]

    end
  end
  ...
end

app/controllers/application_controller.rb

class ApplicationController < ActionController::Base
    prepend_before_action :check_access
    ...
    private

    def check_access
      @user = User.find_by_session_id(session[:user_session_id]) if session[:user_session_id]
      if @user
        session[:user_session_id] = @user.session_id
      end
    end
end


app/controllers/api/v2/api_controller.rb

module Api::V2
  class NotFound < StandardError; end
  class InvalidRequestError < StandardError; end
  class UnprocessableEntityError < StandardError; end
  class ResourceConflict < StandardError; end
  class Unauthorized < StandardError; end

  class ApiController < ApplicationController
    before_action :check_user_authorized
    ...
    def check_user_authorized
      unless @user
        raise Api::V2 Unauthorized
      end
    end
  end
end

app/controller/api/v2/tickets_controller.rb

module Api::V2
  class TicketsController < ApiController
    TICKET_STATE_FILTER_ALL = 'all'
    TICKET_STATE_FILTER_OPEN = 'open'
    TICKET_STATE_FILTER_CLOSED = 'closed'

    def index
      @tickets
      state_filter = params['state'] ||= TICKET_STATE_FILTER_ALL

      case state_filter
      when TICKET_STATE_FILTER_ALL
        @tickets = Ticket.where(user_id: @user.id)
      when TICKET_STATE_FILTER_OPEN
        @tickets = Ticket.where(user_id: @user.id, closed_date: nil)
      when TICKET_STATE_FILTER_CLOSED
        @tickets = Ticket.where(user_id: @user.id).where.not(closed_date: nil)
      end
    end
    ...
  end
end

app/controller/api/v2/tickets/payments_controller.rb

module Api::V2
  class Tickets::PaymentsController < ApiController
    ...
    def create    
      @ticket = Ticket.where(id: params[:ticket_id]).first

      unless @ticket
        raise Api::V2::NotFound
      end

      if @ticket.is_closed
        raise Api::V2::UnprocessableEntityError, "Ticket closed"
      end
    end
  end
end
```

**Comment by pixeltrix** [comment]
@eman8519 can you expand the `Api::V2` definitions to fully nested ones and see if you're still having problems? e.g:

```
module Api
  module V2
    # rest of your code
  end
end
```

When you define things inline like `Api::V2` versus nested it affects how Ruby searches for constants so I want to eliminate this as a cause first - thanks.

**Comment by eman8519** [comment]
@pixeltrix I have confirmed that the issue remains even after replacing `Api::V2` with a nested modules structure as you have recommended.

It may be worth mentioning that nested modules is the way I originally constructed my `Api::V2` classes, and only recently changed it in an attempt to workaround this issue.  Let me know anything else I can do to help track this down.

**Comment by pixeltrix** [comment]
@eman8519 a git repo with a bare bones app that demonstrates the problem would be most helpful - thanks.

**Comment by eman8519** [comment]
@pixeltrix I've been working on getting the requested bare bones app together, but since this issue isn't consistent it is tough to reproduce it reliably.  I'm trying to find a way to show the issue reliably.  I suppose it could be a configuration issue, or a gem doing something weird, but so far I'm just not sure.

**Comment by schristm** [comment]
I'm having the same problem.

**Comment by xn** [comment]
I am as well.

**Comment by ktdmedia** [comment]
Also running into this problem with 5.0.0.rc1 

Just like @eman8519 described:

> ...When I edit the source code while the rails sever is running in development environment (trying to highlight the fact that controller files are reloaded in development env), I get the result you would expect for both requests. Even if all I change is adding a newline and saving then remove the same newline and saving again

**Comment by xn** [comment]
I've had issues like this in the past. For me, it was resolved by removing unneeded autopath includes
like:

```
config.autoload_paths += Dir[Rails.root.join('app', 'services', '*')]
```
