### ISSUE TITLE
Support CHECK constraints in migrations and schema.rb

### ISSUE THREAD

**Issue by mpartel** [rails/rails#23083]
As mentioned at the bottom of [this RailsGuide section](http://edgeguides.rubyonrails.org/active_record_migrations.html#reverting-previous-migrations), CHECK constraints cannot be expressed in `schema.rb`. Please support them.

A syntax suggestion:
```ruby
    add_check 'my_table', 'a < b', name: 'a_less_than_b'
    remove_check 'my_table', 'a_less_than_b'
```

**Comment by prathamesh-sonpatki** [comment]
@mpartel Thanks but this is a feature request and we don't take feature requests on Github. It is only reserved for bug reports. Please use the rubyonrails-core mailing list to suggest features where you will also get feedback from others.

Thanks.
