### ISSUE TITLE
Join table regression in 4.2.5

### ISSUE THREAD

**Issue by wtn** [rails/rails#23108]
Duplicate of issue #22584: the change was introduced to 4-2-stable at 799aedc6437aad61a6355917f625da6fd7868d24 and fixed at a6c3376ad0c5dbaf407d332994d07ebc8c91f592.

**Comment by maclover7** [comment]
Would you be willing to do a git bisect to figure out where the errant behavior was introduced? Also, can you create an executable test script to reproduce the error, using one of the templates [here](https://github.com/rails/rails/tree/master/guides/bug_report_templates)? Finally, is this an issue on Rails master currently?

**Comment by wtn** [comment]
The change was introduced to 4-2-stable at 799aedc6437aad61a6355917f625da6fd7868d24 (cc @senny).

**Comment by maclover7** [comment]
Ok, can you check and see if this error occurs on Rails master, or if it's only introduced for 4.2.5?

**Comment by wtn** [comment]
The issue is only in 4-2-stable. Here's a test script with fixtures that demonstrates the error: [wtn/active_record_fixtures_bug](https://github.com/wtn/active_record_fixtures_bug)

**Comment by maclover7** [comment]
Ok. Would you be willing to send in a PR with a regression test to fix this bug?

**Comment by wtn** [comment]
This was fixed in a6c3376ad0c5dbaf407d332994d07ebc8c91f592.

**Comment by maclover7** [comment]
Why did you close the issue?

**Comment by wtn** [comment]
This issue was fixed by a6c3376ad0c5dbaf407d332994d07ebc8c91f592.
