### ISSUE TITLE
Cannot load 'guard' (LoadError) for Rails 4.2.4

### ISSUE THREAD

**Issue by alexrois** [rails/rails#23105]
When running `bundle exec rake test` for Rails 4.2.4 application it has an error: *cannot load such file -- guard (LoadError)*:
![rails-bug](https://cloud.githubusercontent.com/assets/16092409/12400528/46258dec-be29-11e5-8b5f-f9c4bfa7abd8.jpg)

**Comment by maclover7** [comment]
It sounds like this is a third party issue, and not something wrong with the internals of Rails -- check your Gemfile and test_helper.rb to make sure that guard is being properly required.
