### ISSUE TITLE
scaffold generator uses fixture replacement for model tests but not for controller tests

### ISSUE THREAD

**Issue by bluehallu** [rails/rails#23133]
Using Rails 5 beta 1, factory_girl_rails 4.5
Steps to reproduce:

generate scaffold, the controller test that is generated will have a setup method that relies on fixtures

**Comment by maclover7** [comment]
Can you please provide a sample app to replicate the error?

**Comment by haydenmellins** [comment]
Hi,

Please share your more details so that I can able to give you an understanding like app detail. You can msg me.

Thanks,
Hayden

**Comment by AndrewHendrie** [comment]
This appears to be an issue with the factory_girl_rails gem and not the Rails 5 beta, no?

**Comment by prathamesh-sonpatki** [comment]
I created a Rails 4.2.5 app and created todo scaffold, it also generated `setup` method with fixtures. This looks like an issue on factory_girl_rails side rather than rails side. Please create an issue on factory_girl_rails repo. I am closing this one.

Thanks everyone!
