### ISSUE TITLE
5.0.0.beta1 --api rendering does not follow `status:` on certain content types

### ISSUE THREAD

**Issue by bbonamin** [rails/rails#23142]
Sample repo: https://github.com/bbonamin/render-content-type-status-api
(app generated with `rails new --api`)

In https://github.com/bbonamin/render-content-type-status-api/blob/master/app/controllers/status_controller.rb

`render json: {what: 'oops!'}, status: 500`
Renders with 500 Internal Server Error √

`render plain: 'oops!', status: 500`
Renders with status 200 OK (500 is expected)

This also happens with `render text: 'foo', status: 500`

An app created without `--api` works as expected, I suspect this behavior might be coming from somewhere related to `ActionController::API`

Thanks :smile:

**Comment by maclover7** [comment]
Failing reproduction script:

```ruby
require 'action_controller/railtie'
require 'minitest/autorun'
require 'rack/test'

class TestApp < Rails::Application
  config.root = File.dirname(__FILE__)
  config.session_store :cookie_store, key: 'cookie_store_key'
  secrets.secret_token    = 'secret_token'
  secrets.secret_key_base = 'secret_key_base'

  config.logger = Logger.new($stdout)
  Rails.logger  = config.logger

  routes.draw do
    get '/test500_plain' => 'test#plain'
    get '/test500_text' => 'test#text'
  end
end

ActiveRecord::Base.establish_connection(adapter: 'sqlite3', database: ':memory:')
ActiveRecord::Base.logger = Logger.new(STDOUT)

class TestController < ActionController::API
  include Rails.application.routes.url_helpers

  def plain
    render plain: 'Home', status: 500
  end
  
  def text
    render text: 'Home', status: 500
  end
end

class BugTest < Minitest::Test
  include Rack::Test::Methods

  def test_plain
    get '/test500_plain'
    assert_equal(500, last_response.status)
  end
  
  def test_text
    get '/test500_text'
    assert_equal(500, last_response.status)
  end

  private
    def app
      Rails.application
    end
end
```

**Comment by maclover7** [comment]
Ran a git bisect, broken commit is https://github.com/rails/rails/commit/38818c93a9959118a87bbdeda16e0766adc67598.

**Comment by maclover7** [comment]
Opened PR to try and solve.
