### ISSUE TITLE
Docs and guides update for #17573

### ISSUE THREAD

**Issue by chancancode** [rails/rails#23148]
With #17573, Rails will only generate "weak" etags. We need the following changes to go with that PR:

- [x] Mention this as a (minor) breaking change in the 5.0 release notes (and upgrade guides?)
- [x] Go through the guides and docs to see if anything needs to be updated
- [x] Document how to override this behavior (and add a test, probably)
- [x] Nice to have: briefly explain the difference between strong and weak etags (probably just a sentence or two with links to external resources), any gotchas and how to customize this behavior

Most of these are fairly easy; please feel free to grab and work on these items!

**Comment by maclover7** [comment]
- Opened PR #23151 to solve 1 and 4.
- Regarding 2, I went through docs, and AD's ETag behavior is not in any of the Rails guides or any other documentation that I could find.
- Regarding 3, do we want to have Another Configuration Option, maybe `config.action_controller.weak_etags = false`, to override this behavior?

**Comment by zerothabhishek** [comment]
@maclover7 Hey there's a section about Conditional Get support in the [caching guide](http://guides.rubyonrails.org/caching_with_rails.html#conditional-get-support). Should that be a good place to describe Etags in more detail? (I can write a paragraph or so if that's okay with you?)

**Comment by maclover7** [comment]
Sure, seems like a good place to put an explanation about Rails' new ETags behavior. :+1:

**Comment by chancancode** [comment]
I will wrap this up tonight

**Comment by zerothabhishek** [comment]
Hey @chancancode if you have not already started on this, let me come up with something in maybe a few hours ?

**Comment by zerothabhishek** [comment]
As of now, there is no way to configure strong Etag generation. Both Rails and Rack generate only weak ETags. If needed, strong ETags can be generated 'manually' and be set to the ETag header.

**Comment by prathamesh-sonpatki** [comment]
Checked all guides. We have added a note on weak tags in caching guide - https://github.com/rails/rails/issues/23860
^ Also explains what are weak etags briefly.

Added a test case for strong etags  - https://github.com/rails/rails/issues/23862

It's also mentioned in release notes. 

@chancancode This issue can be closed now.

**Comment by chancancode** [comment]
:clap: thank you everyone!
