### ISSUE TITLE
numericality validator should respect allow_blank when only_integer is set

### ISSUE THREAD

**Issue by nathansamson** [rails/rails#23158]
Reasoning: I will only accept integers, but when users enters nothing it should be accepted as well.
So acceptable values are
* '' (empty)
* 5
Not acceptable values are
* 15.5 (float)
* foo (text)
* 5foo (combination)

when using `validates :a_field, numericality: { allow_blank: true, only_integer: true }` will not accept the empty value because its not an integer. only_integer seems to be too strict to me.

I understand that changing this might break existing applications which rely on this (semi-documented) behaviour, so I am happy as well with a new flag "no_floats" or something similar.

Why do I say semi-documented:

     To specify that only integral numbers are allowed set :only_integer to true.

Combined with the allow_blank this makes me believes empty values are accepted as well

But it also says (at the same place)
   
    If you set :only_integer to true, then it will use the  `/\A[+-]?\d+\Z/` regular expression

So if you read the regular expression in detail, you see that at least one digit is needed. So you could argue that the empty value is not accepted. (You could also argue that the regular expression is exposing an implementation detail, but that is nitpicking)

On the other hand it also in the allow_blank documentation.

    The :allow_blank option is similar to the :allow_nil option. This option will let validation pass if the attribute's value is blank?, like nil or an empty string for example.

This does not have any limitations so it should pass the validation in all cases, or it should be pointed out very clearly that there are exceptions to this + where appropriate state that the validator ignores the allow_blank option. (eg the greater_or_equal than can be set and it will happily accept empty values)

**Comment by egilburg** [comment]
Would it be different if written as:

`validates :a_field, numericality: { only_integer: true }, allow_blank: true`

Or as this?

`validates :a_field, numericality: { only_integer: true }, unless: :blank?`

**Comment by vipulnsward** [comment]
As @egilburg mentioned, `allow_blank` is not an option on `:numericality`. All allowed options [here](https://github.com/vipulnsward/rails/blob/2067fff9e38df4e37bdbfc021cd6bb0c2d393a2a/guides/source/active_record_validations.md#numericality). 
For example, this works for me-

```ruby
Person.validates :salary, numericality: { only_integer: true  }, allow_blank: true
person = Person.new
person.salary= "" # or setting person.salary.to nil
assert person.valid?
```

**Comment by prathamesh-sonpatki** [comment]
Closing this as it's already possible to have `blank` values with numericality validator as mentioned above.

Thanks all!
