### ISSUE TITLE
Cannot validate presence of parent object when children are created using accepts_nested_attributes_for

### ISSUE THREAD

**Issue by samphilipd** [rails/rails#23163]
EDIT: < removed reference to closed PR, see test case below >

Basically the problem comes because we are setting `@automatic_inverse_of = false` in `MacroReflection#autosave=`.

I think this may have been intended as an optimization, but it causes the inverse lookup to fail when saving associated records on an un-persisted parent, and leads to a failure of the included test case.

I wanted to generate some discussion about this - namely, is it safe to remove this line? I guess it might cause a small performance hit but are the performance savings worth the cost of incorrect behavior?

NOTE: I think this might be similar (or identical to?) this issue: https://github.com/rails/rails/pull/22391

**Comment by maclover7** [comment]
If you're just trying to demonstrate a bug, please create an executable test script using one of the templates found [here](https://github.com/rails/rails/tree/master/guides/bug_report_templates).

**Comment by samphilipd** [comment]
@maclover7 Oops, I meant to create the diff into my own master branch, not as a PR into rails master.

Anyway, here is the test script:

```ruby
begin
  require 'bundler/inline'
rescue LoadError => e
  $stderr.puts 'Bundler version 1.10 or later is required. Please update your Bundler'
  raise e
end

gemfile(true) do
  source 'https://rubygems.org'
  # Activate the gem you are reporting the issue against.
  gem 'activerecord', github: 'rails/rails', branch: 'master'
  gem 'sqlite3'
end

require 'active_record'
require 'minitest/autorun'
require 'logger'

# Ensure backward compatibility with Minitest 4
Minitest::Test = MiniTest::Unit::TestCase unless defined?(Minitest::Test)

# This connection will do for database-independent bug reports.
ActiveRecord::Base.establish_connection(adapter: 'sqlite3', database: ':memory:')
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :posts, force: true do |t|
  end

  create_table :comments, force: true do |t|
    t.string :body
    t.integer :post_id
  end
end

class Post < ActiveRecord::Base
  has_many :comments # , inverse_of: :post # <- works if you uncomment this
  accepts_nested_attributes_for :comments
end

class Comment < ActiveRecord::Base
  belongs_to :post
  validates :post, presence: true
end

class TestModelsInstantiatedViaNestedAttributesValidateParent < MiniTest::Test
  def test_accepts_nested_attributes_and_has_one_work_with_validate_presence_of
    assert Post.new.update( comments_attributes: [{ body: "I require a post!" }] )
  end
end
```

**Comment by maclover7** [comment]
Closing since https://github.com/rails/rails/pull/23197 / https://github.com/rails/rails/commit/c7adc610f0233b9afd51a6d68aa9061cdb250fad were merged to master.
