### ISSUE TITLE
Need to specify exact version when installing local gems(Rails Guide)

### ISSUE THREAD

**Issue by Humacsson** [rails/rails#23184]
In http://guides.rubyonrails.org/engines.html section 2.1.1 and 4.1 we are told to install the engine/gem with the following line in the host projects gem file:

`gem 'blorgh', path: "/path/to/blorgh"`

This line does not work for local gems however, and returns the following error:

```
Could not find gem 'blorgh' in source at `/path/to/blorgh`.
Source does not contain any versions of 'blorgh'
```
The gem will not be found unless you also specify the exact version of the gem as well like this:

`gem 'blorgh', '0.0.1', path: "/path/to/blorgh"`

See this stackoverflow question for reference:
http://stackoverflow.com/questions/5381681/in-rails-3s-bundle-install-of-local-gem-frozen-gem-keep-getting-source-do

Since I am still a beginner when it comes to using Rails I do not feel confident that this is an error in the guide or with my implementation of it. I am also unsure of how to update the guide if it actually is an error.

**Comment by renanoronfle** [comment]
the guide is correct, i create a project and not get error without versions
for example: gem 'rulers', path: '/home/renanoronfle/projects/rulers'   
It's working fine

**Comment by chrisarcand** [comment]
@Humacsson Welcome! :) 

Indeed, the feature mentioned here is actually a part of Bundler ([documentation](http://bundler.io/v1.11/man/gemfile.5.html#PATH-path-]), not Rails specifically. You do not need to specify the version, so two things you might check are...

* Are you sure you have the right file path?
* A `blorgh.gemspec` file needs to exist, and should have been created with your `rails plugin new blorgh --mountable` command. Can you check to make sure it's still there, and with a version specified within? Without a gemspec file the path option will not work and give the error you specified.

**Comment by prathamesh-sonpatki** [comment]
I just tried with creating an engine and app based on [egine guides](http://edgeguides.rubyonrails.org/engines.html) and including `blorgh` worked. For example locally I had to do `gem 'blorgh', path: './../blorgh/` in my app.


I am closing this is as it's not related to Rails. Thanks everyone!

**Comment by Humacsson** [comment]
Thanks everyone! It is probably something in my environment causing this then.

**Comment by perceptec** [comment]
Note that an invalid `blorgh.gemspec` will also generate this error.

I don't believe the [guide](http://edgeguides.rubyonrails.org/engines.html) covers updating the gemspec with relevant values, but if you're seeing errors like `The gemspec at blorgh/blorgh.gemspec is not valid.`, those need to be addressed to correct the problem.
