### ISSUE TITLE
Setting enum default via ':default' on DB field is broken [bisected] 

### ISSUE THREAD

**Issue by ojab** [rails/rails#23187]
[Testcase](https://gist.github.com/ojab/6a5c0853fda1cc37f20b).
If column for enum is created with default value:
in rails master: Model instance is built with field == nil
in rails-before-bad-commit: Model is built with filed == default value.

```
991c7b8cd69d7ba5e221a19e5f386e3ba02eb9d is the first bad commit
commit e991c7b8cd69d7ba5e221a19e5f386e3ba02eb9d
Author: Santiago Pastorino <santiago@wyeworks.com>
Date:   Thu Dec 31 19:45:47 2015 -0300

    value has the right type here

    using `enum kind: [ :any, :income, :expense ]` syntax, value is already an
    integer and using `enum kind: { any: 'any', income: 'income', expense:
    'expense' }` syntax value is a string.

    This allows us to define the mapping in the enum definition.

    This reverts commit 933decceaf6092020ba7ba768b51b2db9d5b882f.

:040000 040000 9d5c346b7de41f9b6cb0b9d23fd2ac5787fc0cbb 7a8f8fd4d6faaa43b779102fae172a874ce5b644 M	activerecord
bisect run success
```
ping @spastorino

**Comment by maclover7** [comment]
Haha @ojab, looks like we both opened up PRs to try and solve this issue. Do you want me to close mine?

**Comment by ojab** [comment]
Yep, since there are basically the same and mine was first.

**Comment by sgrif** [comment]
Fixed by https://github.com/rails/rails/commit/67c1719012506c3387df067961252b5df50a97ce
