### ISSUE TITLE
When psql is missing "rake db:structure:load" should show some error

### ISSUE THREAD

**Issue by gudata** [rails/rails#23186]
The problem might be 
https://github.com/rails/rails/blob/master/activerecord/lib/active_record/tasks/postgresql_database_tasks.rb#L99
when invoking or passing Kernel.system(cmd, *args) as param.

```
# rake db:structure:load --trace
** Invoke db:structure:load (first_time)
** Invoke environment (first_time)
** Execute environment
[AIRBRAKE] You can't use the default async handler without sucker_punch or girl_friday. Please make sure you have sucker_punch or girl_friday installed (sucker_punch is recommended).
** Invoke db:load_config (first_time)
** Execute db:load_config
** Execute db:structure:load
```

**Comment by vipulnsward** [comment]
I see this error.(I manually changed the command from psql to psqls)
```ruby
  1) Error:
ActiveRecord::PostgreSQLStructureLoadTest#test_structure_load:
RuntimeError: failed to execute:
psqls -q -f awesome-file.sql my-app-db

Please check the output above for any errors and make sure that `psqls` is installed in your PATH and has proper permissions.


    /Users/sward/work/rails/activerecord/lib/active_record/tasks/postgresql_database_tasks.rb:99:in `run_cmd'
    /Users/sward/work/rails/activerecord/lib/active_record/tasks/postgresql_database_tasks.rb:71:in `structure_load'
    /Users/sward/work/rails/activerecord/lib/active_record/tasks/database_tasks.rb:206:in `structure_load'
    /Users/sward/work/rails/activerecord/test/cases/tasks/postgresql_rake_test.rb:266:in `test_structure_load'

```

@gudata are you sure you ended up in some error? How did you incur it failed.

**Comment by gudata** [comment]
I renamed the psql executable to psqls 

```
# mv /usr/bin/psql /usr/bin/psqls
# which psql
# 
```

Then just run  rake db:structure:load and there is no error. Maybe this is ruby problem? Which version of ruby you are trying on?

```
# ruby -v
ruby 2.0.0p481 (2014-05-08 revision 45883) [x86_64-linux]
# rails -v
Rails 4.1.11
```

**Comment by vipulnsward** [comment]
I was on ruby 2.3. Can you ruby 2.2 or something later. 
Although I dont see that would affect it.

**Comment by gudata** [comment]
It also happens with Ruby on Rails in Docker container FROM ruby:2.2.3 

I also tried on ruby 2.2.2p95 (2015-04-13 revision 50295) [x86_64-linux]  and on some other computer with ruby 2.0.

**Comment by gudata** [comment]
Here is a how to reproduce with Docker
Get the [Dockerfile](https://gist.github.com/gudata/0ef1cb87e30c365f508b)
buld with

    docker build --rm=true --tag=psql_missing .

run some postgres container

    docker run --name psql_missing_postgres -e POSTGRES_PASSWORD='' -d postgres

run the rails app with set to use pg gem and structure.sql

    docker run -t -i --rm=true  --link psql_missing_postgres:postgres psql_missing


no psql - no error 

    bundle exec rake db:structure:load --trace
