### ISSUE TITLE
 [Rails-5] uninitialized constant ApplicationCable::ActionCable

### ISSUE THREAD

**Issue by anilmaurya** [rails/rails#23183]
When I create new rails application without active-record

```
rails new app-name --skip-active-record
```

And start server (`rails s`) then I get this error

```
`<module:ApplicationCable>': uninitialized constant ApplicationCable::ActionCable (NameError)
from ../../app/channels/application_cable/channel.rb:2:in `<top (required)>
```

Reason: 

In `config/application.rb` action_cable is not required 

Solution:

In `config/application.rb`

I added
```
require "action_cable"
```

Let me know If this is correct solution and you are willing to accept a PR to fix this issue.

**Comment by prathamesh-sonpatki** [comment]
@anilmaurya Are you trying Rails 5.0.0.beta1? This issue is not present in master. Here is application.rb generated by skipping `--active-record` on master - https://gist.github.com/prathamesh-sonpatki/e7acee0a02b060209ddf#file-application-rb-L11

**Comment by anilmaurya** [comment]
@prathamesh-sonpatki Thank you. I checked and found out that it was `'rails', '4.2.5'`
