### ISSUE TITLE
NoMemoryError: failed to allocate memory using BigDecimal .to_s method

### ISSUE THREAD

**Issue by phlegx** [rails/rails#23196]
I use **Ruby 2.2.3** and **Rails 4.2.3**. I get an ```NoMemoryError: failed to allocate memory``` using the following code in *irb* console:

```ruby
    # Using 123e+1000000000000000000
    BigDecimal('123e+1000000000000000000').to_s
    #=> NoMemoryError: failed to allocate memory
```

But this example with a more bigger number works:

```ruby
    # Using 123e+1000000000000000000000000000000000
    BigDecimal('123e+1000000000000000000000000000000000').to_s
    #=> "Infinity"
```

Here my question on Stackoverflow: http://stackoverflow.com/questions/34952833/nomemoryerror-failed-to-allocate-memory-using-bigdecimal-to-s-method

**Comment by maclover7** [comment]
Please use the mailing list or StackOverflow for questions/help, where a wider community will be able to help you. We reserve the issues tracker for issues only.
