### ISSUE TITLE
structure.sql does not preserve permissions for schemas

### ISSUE THREAD

**Issue by nbrustein** [rails/rails#23202]
My rails project uses two different schemas.  Some activerecord models use the default connection and connect to one of the schemas.  Some other models use a different connection and connect to a different schema using a different user.

All this works fine, except when I run `rake spec`. The reason for that is that `rake spec` uses the structure.sql file to build the database, and that file does not preserver the proper ownership rules from the db.  I have tried doing the permissions by setting ownership of the schema and by granting permissions, but both are blown away in structure.sql.

Right now, all I can do is turn of rake db:prepare, as described in http://stackoverflow.com/questions/8112074/overriding-rails-default-rake-tasks.

I guess the solution would be for whoever writes structure.sql to also write in info about the ownership and permissions?

**Comment by sgrif** [comment]
Unfortunately, `structure.sql` relies on the backend for this information. Unless there is an option we can pass to `pg_dump` to enable this that we aren't already doing, this is a problem that would require a fix there.

**Comment by nbrustein** [comment]
How about the a feature request to have a configuration option for turning off rake db:prepare so that we could still run rake spec?  Would that make sense?

**Comment by pixeltrix** [comment]
@sgrif I think the problem is that we pass `-O` to pg_dump:

```
-O
--no-owner
    Do not output commands to set ownership of objects to match the
    original database. By default, pg_dump issues ALTER OWNER or SET
    SESSION AUTHORIZATION statements to set ownership of created
    database objects. These statements will fail when the script is run
    unless it is started by a superuser (or the same user that owns all
    of the objects in the script). To make a script that can be
    restored by any user, but will give that user ownership of all the
    objects, specify -O.

    This option is only meaningful for the plain-text format. For the
    archive formats, you can specify the option when you call
    pg_restore.
```

We've done this forever AFAICS and with good reason - by default PostgreSQL connects as the current user so you'd end up with constant merge conflicts and/or unknown user errors when loading the structure.sql file. However maybe there's a way we could expose args to `pg_dump` via database.yml?

**Comment by nbrustein** [comment]
Ah tricky.  But in my case I would still have the problem you describe for the primary connection.  I would only want the ownership info for SOME stuff.  That's probably too much to ask.

But I still don't see why there is no option to just not use the structure.sql at all.  What is it getting me?  If I just run migrations against my test db then it is all set up and good to go.

**Comment by pixeltrix** [comment]
> Ah tricky. But in my case I would still have the problem you describe for the primary connection. I would only want the ownership info for SOME stuff. That's probably too much to ask.

Do you have two different structure.sql files? One for each connection?

**Comment by nbrustein** [comment]
I don't have two different structure.sql files.  What I meant by my comment was, just like in the normal rails case, I would not want to include ownership information for the stuff n the 'public' schema.  If I did, then we would run into conflicts between different developers, like you described (though I guess we could solve that by all setting up a special user and using that rather than our local users for local development).

So removing the -O would fix our ownership issues for the extra schema we're creating, but create ownership issue for the connection that uses the local user.
