### ISSUE TITLE
[actioncable, activejob] How do I stop a while loop ?

### ISSUE THREAD

**Issue by chrisvel** [rails/rails#23214]
I am creating a channel that executes an infinite loop and an ActiveJob which prints a message. I want to stop this loop but it seems that it gets its own "thread" and I am not able to, ending in letting it run forever. How do I break this ?

```
class DeviceChannel < ApplicationCable::Channel
  def subscribed
    stream_from "device_channel"
  end

  def unsubscribed
    # Any cleanup needed when channel is unsubscribed
  end

  def speak(data)
    while true do
      if data['state'] == "stop"
        break
      end
      MessageBroadcastJob.perform_later data['message']
    end
  end

end
```

**Comment by matthewd** [comment]
Please use the mailing list or StackOverflow for questions/help, where a wider community will be able to help you. We reserve the issues tracker for issues only.
