### ISSUE TITLE
Numercality validator only_integer is not reliable with decimal storage

### ISSUE THREAD

**Issue by nathansamson** [rails/rails#23224]
For example look in this gist: https://gist.github.com/nathansamson/d06bd374a6e8ede168ac

Background: I have a field and depending on some other situations the input needs to be an integer, or a floating number.
So I use the only_integer option with a proc checking for this condition.

Saving this once to the database works (as the raw input is validated).
Opening the form again, and saving a second time fails. It seem that the input is then read from the database as "15.0" (for example) and validated against the regex.
Working around the problem is relatively simple but I feel this needs to be mentioned in the guides and documentation.
Note that when the form is being displayed the actual value shown is "15".

This can also be reproduced with current 4.2.5 and seems database independant (as behaviour was discovered with a postgresql database)

**Comment by southwolf** [comment]
https://github.com/rails/rails/blob/master/activemodel/lib/active_model/validations/numericality.rb#L79

What the `only_integer ` validation does: **convert the value to string, and check if there is anything other than 0-9**
So it will reject numbers like "15.0", "15.0000000000000", no matter how precisely they equals to "15".

[BigDecimal#frac](http://ruby-doc.org/stdlib-2.3.0/libdoc/bigdecimal/rdoc/BigDecimal.html#method-i-frac) might be a feasible solution, but it will be a little slower.

https://gist.github.com/southwolf/b6ae3c8ff82e959548ac

**Comment by nathansamson** [comment]
Note that I believe it should reject the number "15.0" (or at least my testing lead believes so) so in that matter the current validation works well...

What the problem is that the user sees the input 15, which is send through the form. But since "15" == 15.0 coming from the database it validates based on the value from the database (which is 15.0 the decimal) which is converted to "15.0" which does not match the current regex (where you can discuss if current behaviour is correct, which seems to be the case).

**Comment by jamesmoriarty** [comment]
Having issues with decimal: broken in 4.2.5(1) upgrading from 4.2.1. Values are being coerced / truncated? Still trying to track down the code change.

```
[1] pry(XXX)> payment.total = 12321.123
=> 12321.123
[2] pry(XXX)> payment.total            
=> #<BigDecimal:562364e0c030,'0.1232112E5',18(27)>
[3] pry(XXX)> payment.total.to_f
=> 12321.12
```

```
  create_table "payments", force: :cascade do |t|
    # ...
    t.decimal  "total",            precision: 8, scale: 2,             null: false
 end
```

**Comment by southwolf** [comment]
@jamesmoriarty  Have you noticed that there is a `scale: 2`? This means database will only store 2 decimal places.

**Comment by vipulnsward** [comment]
@southwolf since you worked on https://github.com/rails/rails/pull/23238#issuecomment-178109289, would you like to enhance docs to specify this?

**Comment by jpcfernandes** [comment]
This change on specification causes a bug on a application I'm working. Users are required to input a price with 2, and the application should display an error if they put in more digits. Now, I'm not sure how should I do to display an error. IMHO, this is a case of just too much magic.

**Comment by rafaelfranca** [comment]
@jpcfernandes use the `foo_before_type_cast` to check the number of decimals.

**Comment by jpcfernandes** [comment]
@rafaelfranca Thanks a lot for the hint! I'll try to hack something around it.
