### ISSUE TITLE
``reset_column_information`` does not reset ``ActiveRecord::Base#find``

### ISSUE THREAD

**Issue by shicholas** [rails/rails#23227]
I am trying to change my primary key from an integer to a uuid, like:

```
remove_column :users, :id                                                                    
rename_column :users, :uuid, :id                                                             
execute 'ALTER TABLE users ADD PRIMARY KEY (id);' 
```

when I call ``User.reset_column_information`` afterward in a migration and then try using ``User.find("a-uuid")``, I get a database error b/c ``ActiveRecord::Base#find`` is still trying to coerce my uuid string as an integer, e.g. ``PG::InvalidTextRepresentation: ERROR:  invalid input syntax for uuid: "0"``

The migration does, however, work fine if ran again (presumably some type of active record cache is cleared)

Is there some other method (public or private) that I can call to remedy this?

Thank you,

**Comment by prathamesh-sonpatki** [comment]
Can you please provide a sample application that reproduces the error?

**Comment by shicholas** [comment]
sorry about the spam/poor explanation, I was able to debug this, and will try to write a blog post on this soon.
