### ISSUE TITLE
Implement new welcome page for localhost:3000

### ISSUE THREAD

**Issue by dhh** [rails/rails#23233]
Implement new welcome page for localhost:3000:

![image](https://cloud.githubusercontent.com/assets/2741/12555860/78082310-c383-11e5-9bfd-b76607d32b3f.png)

We're cutting away needless links and extra data. Just keep it simple. Purpose is just to reflect that Things Work.

Here are the files:

[rails-localhost.zip](https://github.com/rails/rails/files/103431/rails-localhost.zip)

**Comment by gsamokovarov** [comment]
I'm around, I can take a stab at this. :-)

**Comment by shakycode** [comment]
Beat me to it :+1: Looks good (the landing page)

**Comment by trimentor** [comment]
:+1:

**Comment by a4652097** [comment]
:+1:

**Comment by prathamesh-sonpatki** [comment]
Closed by https://github.com/rails/rails/issues/23237
