### ISSUE TITLE
DateHelper add square brackets in input names (non RFC compliant URLs)

### ISSUE THREAD

**Issue by dahu33** [rails/rails#23231]
The DateHelper class creates `<select>` tags with names containing `[` and `]` characters. As per my understanding of the [rfc2396](http://tools.ietf.org/html/rfc2396) this is not allowed and these characters must be encoded.

This issue is causing some troubles with some application firewall that blocks non RFC compliant URLs.

Would the right place to fix this issue be here?

https://github.com/rails/rails/blob/4-2-stable/actionview/lib/action_view/helpers/date_helper.rb#L1012
```ruby
        def input_name_from_type(type)
          prefix = @options[:prefix] || ActionView::Helpers::DateTimeSelector::DEFAULT_PREFIX
          prefix += "[#{@options[:index]}]" if @options.has_key?(:index)

          field_name = @options[:field_name] || type
          if @options[:include_position]
            field_name += "(#{ActionView::Helpers::DateTimeSelector::POSITION[type]}i)"
          end

          @options[:discard_type] ? prefix : "#{prefix}[#{field_name}]"
        end
```

**Comment by sblackstone** [comment]
They aren't illegal characters as far as the forms go.  If you're using <form method="POST"> they would end up in the POST data rather than the URL.  If you're doing <form method="GET"> the browser should escape them for you.  If you're handling them in AJAX then you'll need to take a look at your code and see why they aren't being escaped or escape them yourself.

**Comment by pixeltrix** [comment]
@dahu33 what @sblackstone says is correct - they even get escaped by the Rails route helpers, e.g:

``` irb
>> app.root_path('date[year]' => '2016')
=> "/?date%5Byear%5D=2016" 
```

Please can you demonstrate in what context that they become unescaped.

**Comment by dahu33** [comment]
Thanks for your feedback. Indeed what @sblackstone says is correct. After reviewing the code I've found that the bug wasn't in rails but in our application... Sorry for the false alarm!
