### ISSUE TITLE
saving an association causes all unsaved associations to be saved

### ISSUE THREAD

**Issue by tommiller1** [rails/rails#23240]
Hello,

I have the following:
class Link has_many :uploads...
class Upload belongs_to :link...
@upload1 = @link.uploads.new file: File.open(Rails.root.join("test/files/test.jpg"))
@upload2 = @link.uploads.new file: File.open(Rails.root.join("test/files/test2.jpg"))

I am calling 'new' on the @link.uploads so I dont have to set 'link_id' manually however it seems to cause 2 issues:

1. @link.uploads now contains 2 unsaved associations, which causes issues with my models as they dont expect @link.uploads to contain unsaved data.
2. Doing @upload1.save will save both associations to the database insead of just @upload1.

Is this the intended behaviour or am I doing something wrong?

Thanks

**Comment by maclover7** [comment]
I believe the proper syntax is `@link.uploads.build`. For a full list of methods provided by Active Record regarding associations, you can go [here](http://guides.rubyonrails.org/association_basics.html#has-many-association-reference).

**Comment by tommiller1** [comment]
Just tried it with build instead of new. Same issues, is it supposed to be like this?

**Comment by maclover7** [comment]
No, I believe this is the intended behavior. The only way to persist data to the DB to call `save`, `update`, etc. Calling `.new` and `.build` will just "build" your data.

**Comment by kaspth** [comment]
`build` is an alias of `new` :)

Yes, there's a catch. If an unpersisted record is saved then any unpersisted associations are persisted too. But it is the intended behavior.

**Comment by tommiller1** [comment]
`class Hotel
	has_many :rooms
end

class Room
	belongs_to :hotel
end

test "FAILS calling save on an object should only save that object to the db"
	@hotel = hotels(:first)
	@room1 = @hotel.rooms.build number: 101
	@room2 = @hotel.rooms.build number: 102
	
	assert @hotel.rooms.count == 0
	assert @room1.save
	assert @hotel.rooms.count == 1	# this is failing cus both @room1 and @room2 get saved so count == 2
end

test "SUCCEEDS calling save on an object should only save that object to the db"
	@hotel = hotels(:first)
	@room1 = Image.new number: 101, hotel_id: @hotel.id
	@room2 = Image.new number: 101, hotel_id: @hotel.id
	
	assert @hotel.rooms.count == 0
	assert @room1.save
	assert @hotel.rooms.count == 1	# success!
end`

Why is this the intended behavior? Sounds like a bug tbh.

**Comment by kaspth** [comment]
There's more info for you here: http://guides.rubyonrails.org/association_basics.html — see the When are Objects Saved? sections.

**Comment by tommiller1** [comment]
Thanks but thats not my issue, I know 'build' is not supposed to save the associated object (I dont expect it to either). My issue is, as you said previously, that ALL unpersisted objects are saved if you call 'save' on any ONE of them. I dont think this should be the intended behavior as its quite misleading. Anyway this can be closed, doing Object.new and setting the id for the belongs_to object manually for now.
