### ISSUE TITLE
Rails 4.2.5.1 and ActionView::Resolver sub-class - ArgumentError: wrong number of arguments (5 for 4)

### ISSUE THREAD

**Issue by erikse** [rails/rails#23243]
I'm seeing this exception since bumping to Rails 4.2.5.1. 

Seems like this [call](https://github.com/rails/rails/blob/4-2-stable/actionview/lib/action_view/template/resolver.rb#L116) and [here](https://github.com/rails/rails/blob/4-2-stable/actionview/lib/action_view/template/resolver.rb#L122) are passing 5 args, but the method arg list is still [4](https://github.com/rails/rails/blob/4-2-stable/actionview/lib/action_view/template/resolver.rb#L133)

```ruby
    # Normalizes the arguments and passes it on to find_templates.
    def find_all(name, prefix=nil, partial=false, details={}, key=nil, locals=[])
      cached(key, [name, prefix, partial], details, locals) do
        find_templates(name, prefix, partial, details, false)
      end
    end

    def find_all_anywhere(name, prefix, partial=false, details={}, key=nil, locals=[])
      cached(key, [name, prefix, partial], details, locals) do
        find_templates(name, prefix, partial, details, true)
      end
    end

  private

    delegate :caching?, to: :class

    # This is what child classes implement. No defaults are needed
    # because Resolver guarantees that the arguments are present and
    # normalized.
    def find_templates(name, prefix, partial, details)
      raise NotImplementedError, "Subclasses must implement a find_templates(name, prefix, partial, details) method"
    end
```

**Comment by maclover7** [comment]
I believe it's setup so that way subclasses can override the `find_templates` method, and provide the request behavior. cc @tenderlove

**Comment by erikse** [comment]
Ok, I can see further down in the file in PathResolver what the extra arg does - thanks!

**Comment by maclover7** [comment]
Cool - do you mind if I close this ticket?

**Comment by erikse** [comment]
Not at all

**Comment by marten** [comment]
Actually, I would really appreciate it if a security patch release would not break this. Or at the very least the `find_templates` method in Resolver should probably be adjusted to take 5 args so that it's even able to raise it's own NotImplmented exception.

**Comment by maclover7** [comment]
@marten - I think the only reason why this wasn't caught sooner, is because the tests we have in our test suite didn't have picked this up. Feel free to submit a PR to work on this!
