### ISSUE TITLE
Rails generate incorrect asset path with 'config.assets.compile = false'

### ISSUE THREAD

**Issue by TangMonk** [rails/rails#23257]
I generate a new rails 4.2.4 application, and run it in production, but the assets path generate incorrect. Please notice the follow picture.

I am create an empty project with rails_admin for test:
![afab6934-cc48-4f91-836c-ac92b6179f89](https://cloud.githubusercontent.com/assets/3498786/12573040/f05088e8-c42e-11e5-884e-62769c557201.png)

it not generate assert prefix with '/assets' and even though set config.assets.prefix = '/assets' not work too

I am using rails 4.2.4 and there is the demo project on [github](https://github.com/TangMonk/rails_asset_bug)

**Comment by rafaelfranca** [comment]
If the assets was not precompiled in the precompile phase that is the correct path of the asset. Make sure this asset is being precompiled.
