### ISSUE TITLE
Updating Rails to 4.1.14.1 introduces the concurrent-ruby gem into my Gemfile.lock and seems to break my app

### ISSUE THREAD

**Issue by tolgap** [rails/rails#23263]
I am using JRuby `1.7.12` in `1.9.3` mode, running a Rails app on version `4.1.13`. With the recent security vulnerabilities I set out to upgrade the app to `4.1.14.1`. All of my specs are green before upgrading.

I increment the `rails` version in my Gemfile

```
  -gem 'rails', '4.1.13'
  +gem 'rails', '4.1.14.1'
```

And I run `jruby -S bundle update rails`. Out comes this diff from my Gemfile.lock:

```
diff --git a/Gemfile.lock b/Gemfile.lock
index 6b2596b..5e2153d 100644
--- a/Gemfile.lock
+++ b/Gemfile.lock
@@ -2,25 +2,25 @@ GEM
   remote: https://rubygems.org/
   remote: http://rails-assets.org/
   specs:
-    actionmailer (4.1.13)
-      actionpack (= 4.1.13)
-      actionview (= 4.1.13)
+    actionmailer (4.1.14.1)
+      actionpack (= 4.1.14.1)
+      actionview (= 4.1.14.1)
       mail (~> 2.5, >= 2.5.4)
-    actionpack (4.1.13)
-      actionview (= 4.1.13)
-      activesupport (= 4.1.13)
+    actionpack (4.1.14.1)
+      actionview (= 4.1.14.1)
+      activesupport (= 4.1.14.1)
       rack (~> 1.5.2)
       rack-test (~> 0.6.2)
-    actionview (4.1.13)
-      activesupport (= 4.1.13)
+    actionview (4.1.14.1)
+      activesupport (= 4.1.14.1)
       builder (~> 3.1)
       erubis (~> 2.7.0)
-    activemodel (4.1.13)
-      activesupport (= 4.1.13)
+    activemodel (4.1.14.1)
+      activesupport (= 4.1.14.1)
       builder (~> 3.1)
-    activerecord (4.1.13)
-      activemodel (= 4.1.13)
-      activesupport (= 4.1.13)
+    activerecord (4.1.14.1)
+      activemodel (= 4.1.14.1)
+      activesupport (= 4.1.14.1)
       arel (~> 5.0.0)
     activerecord-jdbc-adapter (1.3.16)
       activerecord (>= 2.2)
@@ -28,7 +28,7 @@ GEM
       activerecord-jdbc-adapter (~> 1.3.16)
       jdbc-mysql (>= 5.1.22)
     activerecord-oracle_enhanced-adapter (1.5.6)
-    activesupport (4.1.13)
+    activesupport (4.1.14.1)
       i18n (~> 0.6, >= 0.6.9)
       json (~> 1.7, >= 1.7.7)
       minitest (~> 5.1)
@@ -98,6 +98,7 @@ GEM
       compass (~> 1.0.0)
       sass-rails (<= 5.0.1)
       sprockets (< 2.13)
+    concurrent-ruby (1.0.0-java)   <<<<<<<<<<---- NOTE THIS
     database_cleaner (1.4.1)
     diff-lcs (1.2.5)
     docile (1.1.5)
@@ -148,8 +149,8 @@ GEM
     mail (2.6.3)
       mime-types (>= 1.16, < 3)
     method_source (0.8.2)
-    mime-types (2.6.2)
-    minitest (5.8.2)
+    mime-types (2.99)
+    minitest (5.8.4)
     multi_json (1.11.2)
     nav_lynx (1.1.1)
       rails (>= 3.1.0)
@@ -181,15 +182,15 @@ GEM
     rack (1.5.5)
     rack-test (0.6.3)
       rack (>= 1.0)
-    rails (4.1.13)
-      actionmailer (= 4.1.13)
-      actionpack (= 4.1.13)
-      actionview (= 4.1.13)
-      activemodel (= 4.1.13)
-      activerecord (= 4.1.13)
-      activesupport (= 4.1.13)
+    rails (4.1.14.1)
+      actionmailer (= 4.1.14.1)
+      actionpack (= 4.1.14.1)
+      actionview (= 4.1.14.1)
+      activemodel (= 4.1.14.1)
+      activerecord (= 4.1.14.1)
+      activesupport (= 4.1.14.1)
       bundler (>= 1.3.0, < 2.0)
-      railties (= 4.1.13)
+      railties (= 4.1.14.1)
       sprockets-rails (~> 2.0)
@@ -204,13 +205,13 @@ GEM
       activesupport (>= 3.0)
     rails_serve_static_assets (0.0.4)
     rails_stdout_logging (0.0.3)
-    railties (4.1.13)
-      actionpack (= 4.1.13)
-      activesupport (= 4.1.13)
+    railties (4.1.14.1)
+      actionpack (= 4.1.14.1)
+      activesupport (= 4.1.14.1)
       rake (>= 0.8.7)
       thor (>= 0.18.1, < 2.0)
     rainbow (2.0.0)
-    rake (10.4.2)
+    rake (10.5.0)
     rb-fsevent (0.9.5)
     rb-inotify (0.9.5)
       ffi (>= 0.5.0)
@@ -346,7 +347,7 @@ DEPENDENCIES
   pry-rails
   puma
   pundit
-  rails (= 4.1.13)
+  rails (= 4.1.14.1)
```

As you can see, I suddenly have the `concurrent-ruby` gem in my lock file. When I run my specs, few controller integration tests fail with the following error:

```
     Failure/Error: post :cast_vote, slug: poll.slug
     NoMethodError:
       undefined method `cache' for nil:NilClass
```

I set out to check what introduced that gem, but I can't find any references to it inside the `rails/rails` repo tag `4.1.14.1`. The branch I see using `concurrent-ruby` is `rails, ~> 5.0.0` alphas and betas.

I dont know if the sudden appearance of `concurrent-ruby` in my lock file has to do anything with this, but I don't think upgrading Rails to `4.1.14.1` should be introducing that dependency, nor breaking my specs.

I can't provide actual source code, but I could answer certain questions about it.

**Comment by maclover7** [comment]
I think this is related to this RSpec bug and pull request, closing https://github.com/rspec/rspec-rails/pull/1533. Not sure why concurrent-ruby was introduced here for the first time, cc @tenderlove

**Comment by tolgap** [comment]
@maclover7 thanks for the speedy response, and a solution for the spec failure :+1: Glad that issue is on Rails' side.

**Comment by maclover7** [comment]
It looks to me like somehow some changes from the 4-2-stable got included in the release, by the looks of it. Investigating...

**Comment by maclover7** [comment]
@tolgap Just checked on the [version page for 4.1.14.1 on Rubygems.org](https://rubygems.org/gems/rails/versions/4.1.14.1), and looks like concurrent-ruby is not a declared dependency of rails, or activesupport, etc. I'm thinking about marking this as a third party issue, since I'm not really sure where the concurrent-ruby dependency is being introduced... Can you try and look at the gems in your Gemfile, and see if maybe they introduced new dependencies?

**Comment by tolgap** [comment]
@maclover7 I upgraded to `4.1.14.1` and committed to VCS without including `concurrent-ruby`. Then I removed the project from my disk. After removing the project completely from my disk, and re-cloning it from VCS, running `jruby -S bundle install`, I do not see `concurrent-ruby` showing up.

I checked which dependencies could depend on `concurrent-ruby`, I found the following two: `rack 2.0.0-alpha`, and `sprockets ~> 3.5.0`. I have these dependencies with Rails, of course, but I'm not matching these versions. I used the reverse dependency API from rubygems: https://rubygems.org/api/v1/versions/concurrent-ruby/reverse_dependencies.json

Could it be something with my jruby bundler cache? Anyway, I can't reproduce it with `bundle install`, but running `bundle update rails` does bring it back.

**Comment by maclover7** [comment]
I'd say to try and create a new vanilla Rails app using the version you were on before the sec version, commit thar, and then try the sec upgrade. If it doesn't show concurrent-ruby at that point, I'm not sure what's up.

**Comment by pixeltrix** [comment]
@tolgap Sprockets 3.5.0 introduces concurrent-ruby as a dependency - you should be able to stick to Sprockets 3.4.1 if you don't want to add it to your bundle.

**Comment by tolgap** [comment]
@pixeltrix I have sprockets 2.1.14 in my lock, not sprockets 3.5.0. I mentioned not matching the version constraints.

**Comment by matthewd** [comment]
@tolgap could you gist your entire Gemfile.lock? It does seem strange that a gem is appearing there without any stated dependency.

**Comment by Marthyn** [comment]
I got the same issue recently on a Rails project, i ignored it because it didn't seem to break anything. The weird thing was that it keeps showing up in my git diff as a removed line in the Gemfile.lock, so i have to stash everytime i change branches.

**Comment by Marthyn** [comment]
And again with another project, concurrent-ruby shows up

```
~/C/H/citylab010 git:feature/upgrade-rails ❯❯❯ git diff                                                                                                                                                                                                                   ⏎ ✖ ✱
diff --git a/Gemfile b/Gemfile
index 7316d14..1b34137 100644
--- a/Gemfile
+++ b/Gemfile
@@ -4,7 +4,7 @@ source 'https://rails-assets.org'
 ruby '2.2.3'

 # Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
-gem 'rails', '4.2.4'
+gem 'rails', '4.2.5.1'
 # Use mysql as the database for Active Record
 gem 'mysql2', '0.3.18'
 # Use HAML for html templates
diff --git a/Gemfile.lock b/Gemfile.lock
index 5355590..866baef 100644
--- a/Gemfile.lock
+++ b/Gemfile.lock
@@ -12,36 +12,36 @@ GEM
   remote: https://rails-assets.org/
   specs:
     aasm (4.1.1)
-    actionmailer (4.2.4)
-      actionpack (= 4.2.4)
-      actionview (= 4.2.4)
-      activejob (= 4.2.4)
+    actionmailer (4.2.5.1)
+      actionpack (= 4.2.5.1)
+      actionview (= 4.2.5.1)
+      activejob (= 4.2.5.1)
       mail (~> 2.5, >= 2.5.4)
       rails-dom-testing (~> 1.0, >= 1.0.5)
-    actionpack (4.2.4)
-      actionview (= 4.2.4)
-      activesupport (= 4.2.4)
+    actionpack (4.2.5.1)
+      actionview (= 4.2.5.1)
+      activesupport (= 4.2.5.1)
       rack (~> 1.6)
       rack-test (~> 0.6.2)
       rails-dom-testing (~> 1.0, >= 1.0.5)
       rails-html-sanitizer (~> 1.0, >= 1.0.2)
-    actionview (4.2.4)
-      activesupport (= 4.2.4)
+    actionview (4.2.5.1)
+      activesupport (= 4.2.5.1)
       builder (~> 3.1)
       erubis (~> 2.7.0)
       rails-dom-testing (~> 1.0, >= 1.0.5)
       rails-html-sanitizer (~> 1.0, >= 1.0.2)
-    activejob (4.2.4)
-      activesupport (= 4.2.4)
+    activejob (4.2.5.1)
+      activesupport (= 4.2.5.1)
       globalid (>= 0.3.0)
-    activemodel (4.2.4)
-      activesupport (= 4.2.4)
+    activemodel (4.2.5.1)
+      activesupport (= 4.2.5.1)
       builder (~> 3.1)
-    activerecord (4.2.4)
-      activemodel (= 4.2.4)
-      activesupport (= 4.2.4)
+    activerecord (4.2.5.1)
+      activemodel (= 4.2.5.1)
+      activesupport (= 4.2.5.1)
       arel (~> 6.0)
-    activesupport (4.2.4)
+    activesupport (4.2.5.1)
       i18n (~> 0.7)
       json (~> 1.7, >= 1.7.7)
       minitest (~> 5.1)
@@ -98,6 +98,7 @@ GEM
       execjs
     coffee-script-source (1.9.1.1)
     colorize (0.7.7)
+    concurrent-ruby (1.0.0)
```

**Comment by tolgap** [comment]
@matthewd I consulted with someone, and we saw no issue in posting the lock file here. So here it is: https://gist.github.com/tolgap/46e5ffabd099a7b08c4c

This is the lockfile as it is in my VCS **with** the Rails update done, but the `concurrent-ruby` line I had manually removed.

If I run `bundle update rails`, then `concurrent-ruby` is added again to the Gemfile as you can see in the first post.

Hope this helps :)

**Comment by rafaelfranca** [comment]
When you run `bundle update rails` does sprockets version is upgrade with `rails`?

**Comment by tolgap** [comment]
@rafaelfranca It does not. It stays at its version. The patch gist in the OP is the exact `git diff` I had after running `bundle update rails` from `4.1.13` to `4.1.14.1`.

**Comment by matthewd** [comment]
@indirect could this be a bundler thing? :confused:

I don't know enough to be certain, but I *thought* the only way a gem would show up in the top level GEM/specs was if it was explicitly pulled in by the Gemfile (so in DEPENDENCIES), or appeared as a dependency of something else. Yet I can only find that lone mention of `concurrent-ruby` in https://gist.github.com/Marthyn/0ba07e0649e84c6d2e42.

**Comment by ylansegal** [comment]
For the benefits of others that stumble upon the same issue: I had the same issue described by the OP when updating rails: `concurrent-ruby` is added as a dependency, even though it's not required. The interesting part, is that if I run bundle install again, it disappears:

``` bash
$ bundle update rails 
# concurrent-ruby is added to Gemfile.lock
$ bundle install 
# concurrent-ruby is removed
```

This happens in jruby-1.7.24 and MRI 2.1.8, both running bundler 1.11.2.
