### ISSUE TITLE
mysql2 Adapter always adds DateTime precision to queries.

### ISSUE THREAD

**Issue by rubiii** [rails/rails#23264]
Not sure if I’m right, but I think the mysql2 adapter should check whether DateTime fields have any precision instead of just [always adding it](https://github.com/rails/rails/blob/v4.2.5.1/activerecord/lib/active_record/connection_adapters/mysql2_adapter.rb#L79). Or maybe it doesn’t even need to, because [ActiveType already handles this](https://github.com/rails/rails/blob/v4.2.5.1/activerecord/lib/active_record/type/date_time.rb#L22)?

This seems to be related to #17239 and #18850.

Please let me know if you need any more details.
The following testcase fails both with Rails 4.2 and 5.x.beta.

``` ruby
begin
  require 'bundler/inline'
rescue LoadError => e
  $stderr.puts 'Bundler version 1.10 or later is required. Please update your Bundler'
  raise e
end

gemfile(true) do
  source 'https://rubygems.org'
  gem 'rails', '4.2.5.1' # '5.0.0.beta1.1'
  gem 'mysql2'
end

require 'active_record'
require 'minitest/autorun'
require 'logger'

# Connection for mysql2 adapter.
ActiveRecord::Base.establish_connection(
  adapter:  'mysql2',
  database: 'rails_bug_test',
  host:     'localhost',
  port:     3306,
  pool:     16,
  encoding: 'utf8',
  username: 'root',
  password: 'password'
)
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :posts, force: true do |t|
    t.datetime :datetime_with_precision, limit: 6
    t.datetime :datetime_without_precision
  end
end

class Post < ActiveRecord::Base
end

class BugTest < Minitest::Test
  def test_datetime_precision
    date = 10.minutes.ago

    Post.create(
      datetime_with_precision: date,
      datetime_without_precision: date
    )

    assert_equal 0, Post.where("datetime_with_precision < ?", date).count     # Passes
    assert_equal 0, Post.where("datetime_without_precision < ?", date).count  # Fails
  end
end
```

**Comment by rubiii** [comment]
Just tried using Arel and noticed you can work around the problem via:

``` ruby
Post.where(Post.arel_table[:datetime_without_precision].lt(date))
```

I think this is still a problem though. At least it’s not working as expected.

**Comment by maclover7** [comment]
What would a patch for this look like?

**Comment by rubiii** [comment]
Good question. I don’t know much about AR at the adapter level. Does the adapter know about the precision from the database field? If so, it could be used to add the proper precision length like ActiveType [seems to be doing](https://github.com/rails/rails/blob/v4.2.5.1/activerecord/lib/active_record/type/date_time.rb#L22).

**Comment by maclover7** [comment]
cc @sgrif

**Comment by sgrif** [comment]
There is no way that we can apply type specific information when you are running a string query. You'll need to ensure your input is valid manually in that case. (Also please don't call it ActiveType. T_T)
