### ISSUE TITLE
UrlGenerationError when new route doesn't handle parameter from _recall

### ISSUE THREAD

**Issue by jcoyne** [rails/rails#23268]
When I call `ActionDispatch::Routing::RouteSet#url_for` with a hash that looks like this:
```
{:host=>"test.host", :port=>nil, :protocol=>"http://", :_recall=>{:etd_id=>"123", :controller=>"curation_concerns/access", :action=>"update"}, :controller=>"catalog", :action=>"show", :id=>"123"}
```
and the second argument is the helper name, in my case `"solr_document"`. And the third argument is the default proc (`url_strategy`, from lib/action_dispatch/routing/route_set.rb:357)

Then I get:

```
     ActionController::UrlGenerationError:
       No route matches {:action=>"show", :controller=>"catalog", :etd_id=>"123", :id=>"123"}
     # /Users/justin/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/actionpack-4.2.5/lib/action_dispatch/journey/formatter.rb:46:in `generate'
     # /Users/justin/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/actionpack-4.2.5/lib/action_dispatch/routing/route_set.rb:721:in `generate'
     # /Users/justin/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/actionpack-4.2.5/lib/action_dispatch/routing/route_set.rb:752:in `generate'
     # /Users/justin/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/actionpack-4.2.5/lib/action_dispatch/routing/route_set.rb:799:in `url_for'
     # /Users/justin/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/actionpack-4.2.5/lib/action_dispatch/routing/route_set.rb:282:in `call'
     # /Users/justin/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/actionpack-4.2.5/lib/action_dispatch/routing/route_set.rb:225:in `call'
     # /Users/justin/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/actionpack-4.2.5/lib/action_dispatch/routing/route_set.rb:347:in `block (2 levels) in define_url_helper'
```

There is a route for solr_document:
```
                       solr_document GET      /catalog/:id(.:format)                                catalog#show
```

It appears it's trying to find a route that has the `etd_id`, even though I haven't asked for that.

**Comment by maclover7** [comment]
I think the issue is that you are passing in too many parameters -- only pass in the ones you need to find the route.

**Comment by jcoyne** [comment]
I'm only passing in a single parameter:

```
solr_document_path('123')
```

**Comment by jcoyne** [comment]
@maclover7 the hash I'm showing is from stepping through with a debugger.

**Comment by maclover7** [comment]
ohh, I apologize - I thought that's what you were sending into the url generating method. Would you be able to create an executable test script to better demonstrate the issue you are seeing?

**Comment by maclover7** [comment]
Can you create an executable test script using one of the templates [here](https://github.com/rails/rails/tree/master/guides/bug_report_templates)?

**Comment by jcoyne** [comment]
I think the problem occurs here:

https://github.com/rails/rails/blob/master/actionpack/lib/action_dispatch/journey/formatter.rb#L16

where options is `{:controller=>"catalog", :action=>"show", :id=>"99"}`
and path_parameters is `{:etd_id=>"123", :controller=>"curation_concerns/access", :action=>"update"}`

**Comment by jcoyne** [comment]
This was my mistake.  The controller was using an engine route set. The route I was looking for was in the main_app.

**Comment by maclover7** [comment]
:+1:
