### ISSUE TITLE
undefined method `cache' for nil:NilClass for Rails 4.1.14.1

### ISSUE THREAD

**Issue by Azdaroth** [rails/rails#23262]
I've just update update Rails version from `4.1.14` to `4.1.14.1` and have an error in controller:
```
 NoMethodError:
       undefined method `cache' for nil:NilClass
``` 
In controller I render some file:
```
render file: "some/file"
```
and the path to this file is `Rails.root/app/views/some/file.html.erb`

I think it may have been caused by this commit, but I'm not entirely sure: https://github.com/rails/rails/commit/be543e8e18246d5c2faa336eb3c0a03b797f3517.

Any ideas?

**Comment by vipulnsward** [comment]
Hi @Azdaroth thanks for reporting. This is related to https://github.com/rails/rails/issues/23254 , https://github.com/rails/rails/issues/23258, https://github.com/rails/rails/issues/23245 etc.
This is an rspec specific issue. Please refer to https://github.com/rspec/rspec-rails/issues/1532#issuecomment-174679485 for resolution.

**Comment by Azdaroth** [comment]
Awesome, thanks for such fast response!
