### ISSUE TITLE
link_to supports method: :patch but data: doesn't work with it

### ISSUE THREAD

**Issue by aguynamedben** [rails/rails#23270]
I'm not sure if this is a bug, me doing it wrong, an oversight in what's supported, or if it's simply not supported yet.

The documentation for `link_to` says that `method: :patch` is supported, but when I pass `data:` along to `link_to`, the values in the `data:` hash don't make it into `params` hash received on the server side.

Example:

Attempting to provide a 1-click status update for a Lead:

```erb
<li><%= link_to "Activate", lead_path(lead), remote: true, method: :patch, data: { status: "activate" } %></li>
```

Action in the controller

```rb
class LeadsController < ApplicationController
  def update
    logger.info(params)
    @lead = Lead.find(params[:id])

    respond_to do |format|
      format.js {}
    end
  end
end
```

Log output:

```
{"controller"=>"leads", "action"=>"update", "id"=>"2591"}
```

Given the `data:` passed to `link_to`, I'd expect the server to receive these params:

```
{"controller"=>"leads", "action"=>"update", "id"=>"2591", "status"=>"activate"}
```

As a workaround, I'm passing the data as a query parameter in the PATCH...

```erb
<li><%= link_to "Activate", lead_path(lead), remote: true, method: :patch, data: { status: "activate" } %></li>
```

...but from what I understand that's not really how PATCH should be used. Shouldn't the data values go into the request body of the PATCH and in-turn come in on params? This seems like a bug to me. Apologies in advance if this is not a bug. I looked at the `link_to` documentation closely and couldn't figure out what might be happening here. I'm happy to help update the documentation if the error is on my side.

Thanks for the time you dedicate to Rails, I love it.

–Ben

**Comment by maclover7** [comment]
That does seem like it should be working to me... Can you create an executable test script using one of the templates [here](https://github.com/rails/rails/tree/master/guides/bug_report_templates) to reproduce the error?

**Comment by georgeclaghorn** [comment]
This behavior seems correct. The `:data` option for `link_to` is used to specify `data-*` attributes on the resulting `<a>` tag.

**Comment by aguynamedben** [comment]
@maclover7 yes, will do.

@georgeclaghorn I was wondering that. Is `:data` just for UJS? I guess my question is... link_to documentation says it support PATCH, but how (if at all?) should I populate the PATCH body? The only way I can figure based on the docs/trying things out is putting data as querystring parameters.

Thanks both for your time.

**Comment by rafaelfranca** [comment]
See https://github.com/rails/jquery-ujs/wiki/Unobtrusive-scripting-support-for-jQuery#data-params-add-additional-parameters-to-the-request
