### ISSUE TITLE
STI with default on type raises an error with master / Rails 5.0.0.beta1

### ISSUE THREAD

**Issue by claudiob** [rails/rails#23285]
Here is the gist to repeat: https://gist.github.com/claudiob/7ba25b10713673fbb537

And here is the explanation. 

I have a polymorphic `Resource < ActiveRecord::Base` class with different classes that inherit from it, for instance `Channel < Resource`.

The `create_table` of the resources table looks like this:

```ruby
ActiveRecord::Schema.define do
  create_table :resources, force: :cascade do |t|
    t.string   :type,       null: false, default: 'Resource'
    t.datetime :created_at, null: false
    t.datetime :updated_at, null: false

  end
end
```

The main thing to notice is **if the type is not specified, I default to `Resource`, the base class**.

The problem is that this works perfectly with Rails 4, but breaks under Rails 5.0.0.beta1 and the current master:

```ruby
# with Rails 4
Channel.new 
# => #<Channel:0x007fde4f3516e8 id: nil...>

# with Rails 5.0.0.beta1 or master
Channel.new 
# => ActiveRecord::SubclassNotFound: Invalid single-table inheritance type: Resource is not a subclass of Channel
# => from ~/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/bundler/gems/rails-9864bcee8cfd/activerecord/lib/active_record/inheritance.rb:185:in `find_sti_class'
```

Note that removing the `default: 'Resource'` solves the issue. But since this was not a problem on Rails 4, I'm filing this as a regression issue.

**Comment by maclover7** [comment]
@claudiob - will bisect this.

**Comment by maclover7** [comment]
This bug was introduced via https://github.com/rails/rails/commit/6b18bdd00ce1e8eb4a5a30f0f6152e47da9bec42.

**Comment by maclover7** [comment]
Working on a fix for this.

**Comment by claudiob** [comment]
OMG @sgrif you are THE BEST! :tada:  :tada:  :tada:  :tada:

**Comment by sgrif** [comment]
The bisect helped a lot. Thank you @maclover7

**Comment by maclover7** [comment]
:metal:
