### ISSUE TITLE
Error raised inside the event loop: no implicit conversion of Puma::MiniSSL::Socket into Integer

### ISSUE THREAD

**Issue by rda1902** [rails/rails#23280]
I use actioncable, which include puma. Trying to make puma to work with ssl. 
I run command
"bundle exec puma -b 'ssl://0.0.0.0:28080?key=/var/ssl/exams-st.key&cert=/var/ssl/exams-st.crt' /home/deployer/exams/current/cable/config.ru"

and get error

Puma starting in single mode...
Version 2.15.3 (ruby 2.2.1-p85), codename: Autumn Arbor Airbrush
Min threads: 0, max threads: 16
Environment: development
Listening on ssl://0.0.0.0:28080?key=/var/ssl/exams-st.key&cert=/var/ssl/exams-st.crt
Use Ctrl-C to stop
Error raised inside the event loop: no implicit conversion of Puma::MiniSSL::Socket into Integer
/home/deployer/exams/shared/bundle/ruby/2.2.0/gems/eventmachine-1.0.9.1/lib/eventmachine.rb:767:in attach_fd' /home/deployer/exams/shared/bundle/ruby/2.2.0/gems/eventmachine-1.0.9.1/lib/eventmachine.rb:767:inattach_io'
/home/deployer/exams/shared/bundle/ruby/2.2.0/gems/eventmachine-1.0.9.1/lib/eventmachine.rb:745:in attach' /home/deployer/exams/shared/bundle/ruby/2.2.0/gems/faye-websocket-0.10.2/lib/faye/rack_stream.rb:37:inblock in hijack_rack_socket'
/home/deployer/exams/shared/bundle/ruby/2.2.0/gems/eventmachine-1.0.9.1/lib/eventmachine.rb:258:in call' /home/deployer/exams/shared/bundle/ruby/2.2.0/gems/eventmachine-1.0.9.1/lib/eventmachine.rb:258:inblock in schedule'
/home/deployer/exams/shared/bundle/ruby/2.2.0/gems/eventmachine-1.0.9.1/lib/eventmachine.rb:981:in call' /home/deployer/exams/shared/bundle/ruby/2.2.0/gems/eventmachine-1.0.9.1/lib/eventmachine.rb:981:inblock in run_deferred_callbacks'
/home/deployer/exams/shared/bundle/ruby/2.2.0/gems/eventmachine-1.0.9.1/lib/eventmachine.rb:978:in times' /home/deployer/exams/shared/bundle/ruby/2.2.0/gems/eventmachine-1.0.9.1/lib/eventmachine.rb:978:inrun_deferred_callbacks'
/home/deployer/exams/shared/bundle/ruby/2.2.0/gems/eventmachine-1.0.9.1/lib/eventmachine.rb:193:in run_machine' /home/deployer/exams/shared/bundle/ruby/2.2.0/gems/eventmachine-1.0.9.1/lib/eventmachine.rb:193:inrun'
/home/deployer/exams/shared/bundle/ruby/2.2.0/gems/faye-websocket-0.10.2/lib/faye/websocket.rb:36:in `block in ensure_reactor_running'

/home/deployer/exams/current/cable/config.ru
require ::File.expand_path('../../config/environment', FILE)

Rails.application.eager_load!
require 'action_cable/process/logging'
ActionCable.server.config.allowed_request_origins = ["https://mydomain"]

run ActionCable.server

When i changed puma on thin, everything was great )))

**Comment by maclover7** [comment]
cc @evanphx

**Comment by rda1902** [comment]
Eventmachine and Puma + SSL are not compatible.
https://github.com/puma/puma/issues/865

**Comment by maclover7** [comment]
cc @matthewd - I think you are working on removing EM from ActionCable, right?

**Comment by matthewd** [comment]
https://github.com/rails/rails/pull/23305

**Comment by maclover7** [comment]
Closing since EM is now optional when using Action Cable.
