### ISSUE TITLE
first_or_create! fails if current scope searches an enum field for several values

### ISSUE THREAD

**Issue by RST-J** [rails/rails#23286]
Hello,

I recently found a problem (bug? intentional behavior?) while using `first_or_create!`.
Consider the following scenario:
```ruby
class Cat < ActiveRecord::Base
  enum status: {dead_and_alive: 0, alive: 1, dead: 2}

  scope :possibly_alive, -> { where(status: statuses.values_at('alive', 'dead_and_alive')) }
end
```
If I now do `Cat.possibly_alive.first_or_create! status: :alive` in the rails console, I'll get
> ArgumentError: '[1, 0]' is not a valid status

So, it seems that ActiveRecord (or ActiveModel?) first initializes a new record with whatever value is prepared for the query which for an enum field results in the exception above as `[1, 0]` is no valid status. But as I pass a valid value for the creation-case I don't see the necessity to do so.

Is this a bug or do I have to work around it (which of course would be easy but `first_or_create!` seems to be the convenient shortcut meant for exactly such cases)?

**Comment by sgrif** [comment]
Can you confirm the version you are using?

**Comment by danielterega** [comment]
reproduced on 5.0.0.beta1.1 and 4.1
https://gist.github.com/danielterega/df3ac7a3eaad3bb295c5

since 4.1 EnumType do not know how to trade with array
`def cast(value)
        return if value.blank?

        if mapping.has_key?(value)
          value.to_s
        elsif mapping.has_value?(value)
          mapping.key(value)
        else
          assert_valid_value(value)
        end
      end`

**Comment by pauloancheta** [comment]
Tried using both latest master and `4.2.5.1` and got the same result.

**Comment by RST-J** [comment]
I'am using `4.1.14`

**Comment by maclover7** [comment]
Replication script that is failing on master --> https://gist.github.com/maclover7/7b991b33d4380b074673

**Comment by sgrif** [comment]
`first_or_create` is not part of the public API. `find_or_create_by` is, but has different semantics (for cases like this).
