### ISSUE TITLE
env is deprecated and will be removed from Rails 5.1

### ISSUE THREAD

**Issue by ianks** [rails/rails#23294]
It seems `env` is finally being deprecated in 5.1

What is the best way to access fields that I would have previously needed from `env`? For example, an `Authorization` header that does not exist on the `headers` hash?

**Comment by maclover7** [comment]
Please use the mailing list or StackOverflow for questions/help, where a wider community will be able to help you. We reserve the issues tracker for issues only.

**Comment by ianks** [comment]
To those wondering, using `request.env` seems to be the way to go.

**Comment by richpeck** [comment]
Thanks!
