### ISSUE TITLE
attachments.inline returns a nil error in the image_tag call if there is a space or a hyphen in the filename

### ISSUE THREAD

**Issue by jimknight** [rails/rails#23295]
From the Rails guide
http://guides.rubyonrails.org/action_mailer_basics.html
2.3.2 Making Inline Attachments
Action Mailer 3.0 makes inline attachments, which involved a lot of hacking in pre 3.0 versions, much simpler and trivial as they should be.
First, to tell Mail to turn an attachment into an inline attachment, you just call #inline on the attachments method within your Mailer:
```
def welcome
  attachments.inline['image.jpg'] = File.read('/path/to/image.jpg')
end
```
Then in your view, you can just reference attachments as a hash and specify which attachment you want to show, calling url on it and then passing the result into the image_tag method:
```
<p>Hello there, this is our image</p>
<%= image_tag attachments['image.jpg'].url %>
```
As this is a standard call to image_tag you can pass in an options hash after the attachment URL as you could for any other image:
```
<p>Hello there, this is our image</p>
<%= image_tag attachments['image.jpg'].url, alt: 'My Photo', class: 'photos' %>
```

But if the 'image.jpg' is 'an image.jpg' or 'an-image.jpg', the call to image_tag attachments['an-image.jpg'].url returns a nil error. I'm allowing users to upload the images into a wysiwig editor which is why I faced this problem to begin with. I'm using the refile gem which is why the ea.file_filename is in there.

In my code I had to replace the spaces or hyphens with underscores to get it to work:

```
def welcome
  attachments.inline[ea.file_filename.gsub(' ','_').gsub('-','_')] = File.read('/path/to/an-image.jpg')
end
```

And in my mailer view:

`<= image_tag attachments[ea.file_filename.gsub(' ','_').gsub('-','_')].url %>`

**Comment by Edouard-chin** [comment]
Could not reproduce the bug on master. Here is the template I used https://gist.github.com/Edouard-chin/20cff74c7ea2fdc832d5

**Comment by maclover7** [comment]
Ok. As long as the issue is solved on master, that's fine. Read through your issue description again, but it looks like you're using Action Mailer 3.0 which is unsupported and only receives severe security fixes, not bug fixes.
