### ISSUE TITLE
"rake doc:rails" failed on Windows 7

### ISSUE THREAD

**Issue by johnnytemp** [rails/rails#23304]
Info: Windows 7 64-bit.  ruby 2.2.3, gem 2.4.5.1, rails 4.2.5, all these commands in PATH.

$ rake doc:rails
Parsing sources...
  0% [ 1/824]  c:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/actionmailer-4.2.5/README.rdoc
...
100% [824/824]  ...uby22-x64/lib/ruby/gems/2.2.0/gems/railties-4.2.5/lib/rails/welcome_controller.rb

Generating SDoc format into d:/dev/rails6/doc/api...
rake aborted!
Errno::EINVAL: Invalid argument @ dir_s_mkdir - d:/dev/rails6/doc/api/files/c:

Tasks: TOP => doc:rails => html/created.rid
(See full trace by running task with --trace)

$ rake doc:rails --trace

...
100% [824/824]  ...uby22-x64/lib/ruby/gems/2.2.0/gems/railties-4.2.5/lib/rails/welcome_controller.rb

Generating SDoc format into d:/dev/rails6/doc/api...
rake aborted!
Errno::EINVAL: Invalid argument @ dir_s_mkdir - d:/dev/rails6/doc/api/files/c:
c:/Ruby22-x64/lib/ruby/2.2.0/fileutils.rb:252:in `mkdir'
c:/Ruby22-x64/lib/ruby/2.2.0/fileutils.rb:252:in `fu_mkdir'
c:/Ruby22-x64/lib/ruby/2.2.0/fileutils.rb:226:in `block (2 levels) in mkdir_p'
c:/Ruby22-x64/lib/ruby/2.2.0/fileutils.rb:224:in `reverse_each'
c:/Ruby22-x64/lib/ruby/2.2.0/fileutils.rb:224:in `block in mkdir_p'
c:/Ruby22-x64/lib/ruby/2.2.0/fileutils.rb:210:in `each'
c:/Ruby22-x64/lib/ruby/2.2.0/fileutils.rb:210:in `mkdir_p'
c:/Ruby22-x64/lib/ruby/2.2.0/pathname.rb:564:in `mkpath'
c:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/sdoc-0.4.1/lib/sdoc/templatable.rb:51:in `render_template'
c:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/sdoc-0.4.1/lib/sdoc/generator.rb:331:in `block in generate_file_files'
c:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/sdoc-0.4.1/lib/sdoc/generator.rb:325:in `each'
c:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/sdoc-0.4.1/lib/sdoc/generator.rb:325:in `generate_file_files'
c:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/sdoc-0.4.1/lib/sdoc/generator.rb:180:in `generate'
c:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/rdoc-4.2.1/lib/rdoc/rdoc.rb:534:in `block in generate'
c:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/rdoc-4.2.1/lib/rdoc/rdoc.rb:529:in `chdir'
c:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/rdoc-4.2.1/lib/rdoc/rdoc.rb:529:in `generate'
c:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/rdoc-4.2.1/lib/rdoc/rdoc.rb:512:in `document'
c:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/rdoc-4.2.1/lib/rdoc/task.rb:248:in `block in define'
c:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/rake-10.5.0/lib/rake/task.rb:240:in `call'
c:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/rake-10.5.0/lib/rake/task.rb:240:in `block in execute'
c:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/rake-10.5.0/lib/rake/task.rb:235:in `each'
c:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/rake-10.5.0/lib/rake/task.rb:235:in `execute'
c:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/rake-10.5.0/lib/rake/task.rb:179:in `block in invoke_with_call_chain'
c:/Ruby22-x64/lib/ruby/2.2.0/monitor.rb:211:in `mon_synchronize'
c:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/rake-10.5.0/lib/rake/task.rb:172:in `invoke_with_call_chain'
c:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/rake-10.5.0/lib/rake/task.rb:201:in `block in invoke_prerequisites'
c:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/rake-10.5.0/lib/rake/task.rb:199:in `each'
c:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/rake-10.5.0/lib/rake/task.rb:199:in `invoke_prerequisites'
c:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/rake-10.5.0/lib/rake/task.rb:178:in `block in invoke_with_call_chain'
c:/Ruby22-x64/lib/ruby/2.2.0/monitor.rb:211:in `mon_synchronize'
c:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/rake-10.5.0/lib/rake/task.rb:172:in `invoke_with_call_chain'
c:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/rake-10.5.0/lib/rake/task.rb:165:in `invoke'
c:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/rake-10.5.0/lib/rake/application.rb:150:in `invoke_task'
c:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/rake-10.5.0/lib/rake/application.rb:106:in `block (2 levels) in top_level'
c:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/rake-10.5.0/lib/rake/application.rb:106:in `each'
c:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/rake-10.5.0/lib/rake/application.rb:106:in `block in top_level'
c:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/rake-10.5.0/lib/rake/application.rb:115:in `run_with_threads'
c:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/rake-10.5.0/lib/rake/application.rb:100:in `top_level'
c:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/rake-10.5.0/lib/rake/application.rb:78:in `block in run'
c:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/rake-10.5.0/lib/rake/application.rb:176:in `standard_exception_handling'
c:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/rake-10.5.0/lib/rake/application.rb:75:in `run'
c:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/rake-10.5.0/bin/rake:33:in `<top (required)>'
c:/Ruby22-x64/bin/rake:23:in `load'
c:/Ruby22-x64/bin/rake:23:in `<main>'
Tasks: TOP => doc:rails => html/created.rid

**Comment by johnnytemp** [comment]
**Note: Important hint, that if the rails project is on C: ( instead of D: ), the command works.**

$ rake doc:rails

...
100% [824/824]  ...uby22-x64/lib/ruby/gems/2.2.0/gems/railties-4.2.5/lib/rails/welcome_controller.rb

Generating SDoc format into c:/Users/xxx/Desktop/yyy/rails1/doc/api...


  Files:       824

  Classes:     350 ( 160 undocumented)
  Modules:     414 ( 261 undocumented)
  Constants:   296 ( 268 undocumented)
  Attributes:  303 ( 269 undocumented)
  Methods:    3622 (1443 undocumented)

  Total:      4985 (2401 undocumented)
   51.84% documented

  Elapsed: 48.1s

**Comment by rafaelfranca** [comment]
This seems to be a bug in sdoc since it is what generates the documentation. Could you open an issue  there? Thanks

**Comment by johnnytemp** [comment]
Could you move/issue this report there for me?  Since I do not know about sdoc.  Thanks a lot.
