### ISSUE TITLE
Eager loading using 'includes' can mess up polymorphic 'has_many :through' relationships

### ISSUE THREAD

**Issue by oneiros** [rails/rails#23308]
In one of my client projects we have a rather complex relationship between a couple of models that always worked fine until we had to introduce a little polymorphism. Suddenly, accessing relationships of an object returned not only the records we wanted and expected, but also records of a different type that were not even associated with our object.

We tracked this down to eager loading and found a simple workaround: Changing the order of relationships passed to `includes` "fixed" the problem.

Still, I suspect this might be a bug in ActiveRecord, so I wanted to leave this here.

I created a dumbed down version of our more complex real example. Say you want to create menus consisting of one or more longdrinks. Every longdrink is a combination of a liquor with a mixer. For whatever reason we must distinguish between sodas and juices used as mixers:

``` ruby
begin
  require 'bundler/inline'
rescue LoadError => e
  $stderr.puts 'Bundler version 1.10 or later is required. Please update your Bundler'
  raise e
end

gemfile(true) do
  source 'https://rubygems.org'
  gem 'activerecord', '4.2.5.1'
  gem 'sqlite3'
end

require 'active_record'
require 'minitest/autorun'
require 'logger'

# Ensure backward compatibility with Minitest 4
Minitest::Test = MiniTest::Unit::TestCase unless defined?(Minitest::Test)

# This connection will do for database-independent bug reports.
ActiveRecord::Base.establish_connection(adapter: 'sqlite3', database: ':memory:')
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :juices, force: true do |t|
  end
  create_table :sodas, force: true do |t|
  end
  create_table :menus, force: true do |t|
  end
  create_table :liquors, force: true do |t|
  end
  create_table :longdrinks, force: true do |t|
    t.integer :menu_id
    t.integer :mixer_id
    t.string :mixer_type
    t.integer :liquor_id
  end
end

class Juice < ActiveRecord::Base
  has_many :longdrinks, as: :mixer
end

class Soda < ActiveRecord::Base
  has_many :longdrinks, as: :mixer
end

class Liquor < ActiveRecord::Base
  has_many :longdrinks
end

class Longdrink < ActiveRecord::Base
  belongs_to :menu
  belongs_to :mixer, polymorphic: true
  belongs_to :liquor
end

class Menu < ActiveRecord::Base
  has_many :longdrinks
  has_many :sodas, through: :longdrinks, source: :mixer, source_type: 'Soda'
  has_many :juices, through: :longdrinks, source: :mixer, source_type: 'Juice'
  has_many :liquors, through: :longdrinks
end

class BugTest < Minitest::Test
  def test_association_stuff
    menu = Menu.create!
    whiskey = Liquor.create!
    vodka = Liquor.create!
    cola = Soda.create!
    orange_juice = Juice.create!
    Longdrink.create!(menu: menu, liquor: whiskey, mixer: cola)
    Longdrink.create!(menu: menu, liquor: vodka, mixer: orange_juice)

    # Case 1: Including liquors last
    # This currently works as expected
    menus = Menu.includes(:sodas, :juices, :liquors).to_a

    menus.first.sodas.each do |soda|
      assert_instance_of Soda, soda
    end
    menus.first.juices.each do |juice|
      assert_instance_of Juice, juice
    end

    # Case 2: Including liquors first
    # This currently fails. sodas suddenly include juices and vice versa
    menus = Menu.includes(:liquors, :sodas, :juices).to_a

    menus.first.sodas.each do |soda|
      assert_instance_of Soda, soda
    end
    menus.first.juices.each do |juice|
      assert_instance_of Juice, juice
    end
  end
end
```

The above test case is for the latest stable version of AR but I confirmed it also fails for 5.0.0.beta1.1.

If this behavior really is a bug (and not just a misunderstanding on our part) I would be happy to collaborate on a PR. I would just need some pointers where to look, as frankly, I have no idea :smile: 

Also, please let me know if you need anything else from me. And thanks for your hard work!

**Comment by maclover7** [comment]
Are you sure this passes for you on 4-2-stable? It is failing for me.

**Comment by oneiros** [comment]
> It is failing for me.

I am confused. Is this not the point of providing a test case with a bug report? It should fail, should it not?

Sorry if I have not been 100% clear before. We encountered this problem with 4.2. Before reporting, I made sure it is still present in 5.0.0.beta1 as to not produce unnecessary noise.

Also, this is not a regression (I also checked with 4.0 and 4.1). I think this is a very rare edge case or some kind of misunderstanding on our part.

Please let me know if I can be of any further assistance.

**Comment by CollinGraves** [comment]
Glanced over implementation, and all seems very normal to me. 

One interesting thing to note for future reference during fix: the order of soda and juice matters, independent of liquor. Here are the results of every combination I could think of, along with their line of failure in the test, as well as the "expected vs. actual" printout: 
```
    liquor, juice, soda = 98, expected juice, not soda
    juice, soda, liquor = PASS
    soda, liquor, juice = 98 expected juice, not soda
    liquor, soda, juice = 94 expected soda, not juice
    juice, liquor, soda = 94 expected soda, not juice
```

**Comment by Uelb** [comment]
I actually have the same problem on my Rails project. 

ruby 2.3.0p0 (2015-12-25 revision 53290) [x86_64-darwin15]
Rails 4.2.6

Basically :
```ruby
class User < ActiveRecord::Base
    has_many :user_sports
    has_many :sports, through: :user_sports
    ...
end

class UserSport  < ActiveRecord::Base
    belongs_to :user
    belongs_to :sport
    ....
end

class Attribute < ActiveRecord::Base
end

class Sport < Attribute
    has_many :user_sports
    has_many :users, through: :user_sports
    ...
end
```

I use Single table inheritance for different types of attributes of my user. And When I try to eager load the sports of a user

````ruby
a = User.eager_load(:pictures, :marital, :personality, :sports)
a[0].sports #=> #<ActiveRecord::Associations::CollectionProxy []> An empty collection
a[0].sports.reload #=> A collection of 3 sports
````

But : 
```ruby
a = User.eager_load(:sports, :pictures, :marital, :personality)
a[0].sports #=> A collection of 3 sports
```

All other attributes are correctly eager loaded

**Comment by oneiros** [comment]
I just confirmed this is still an issue on the 5-1-stable branch.
