### ISSUE TITLE
Template resolver @cache nil v4.2.5.1 calling render file:

### ISSUE THREAD

**Issue by kjbkjb** [rails/rails#23318]
This busts our spec between v4.2.5 and v4.2.5.1

 ```
 rescue_from Exceptions::InvalidParameterError do |exception|
    render file: '/public/400.html', status: 400
  end
```

Raised on this line:
https://github.com/rails/rails/blob/4-2-stable/actionview/lib/action_view/template/resolver.rb#L151

    Failure/Error: post 'index', params
     NoMethodError:
       undefined method `cache' for nil:NilClass
     # /Users/username/.rvm/gems/ruby-2.2.3@gh/gems/actionview-4.2.5.1/lib/action_view/template/resolver.rb:151:in `cached'
     # /Users/username/.rvm/gems/ruby-2.2.3@gh/gems/actionview-4.2.5.1/lib/action_view/template/resolver.rb:121:in `find_all_anywhere'
     # /Users/username/.rvm/gems/ruby-2.2.3@gh/gems/actionview-4.2.5.1/lib/action_view/path_set.rb:68:in `block (2 levels) in _find_all'
     # /Users/username/.rvm/gems/ruby-2.2.3@gh/gems/actionview-4.2.5.1/lib/action_view/path_set.rb:66:in `each'
     # /Users/username/.rvm/gems/ruby-2.2.3@gh/gems/actionview-4.2.5.1/lib/action_view/path_set.rb:66:in `block in _find_all'
     # /Users/username/.rvm/gems/ruby-2.2.3@gh/gems/actionview-4.2.5.1/lib/action_view/path_set.rb:65:in `each'
     # /Users/username/.rvm/gems/ruby-2.2.3@gh/gems/actionview-4.2.5.1/lib/action_view/path_set.rb:65:in `_find_all'
     # /Users/username/.rvm/gems/ruby-2.2.3@gh/gems/actionview-4.2.5.1/lib/action_view/path_set.rb:50:in `find_file'
     # /Users/username/.rvm/gems/ruby-2.2.3@gh/gems/actionview-4.2.5.1/lib/action_view/lookup_context.rb:126:in `find_file'
     # /Users/username/.rvm/gems/ruby-2.2.3@gh/gems/actionview-4.2.5.1/lib/action_view/renderer/abstract_renderer.rb:18:in `find_file'
     # /Users/username/.rvm/gems/ruby-2.2.3@gh/gems/actionview-4.2.5.1/lib/action_view/renderer/template_renderer.rb:32:in `block in determine_template'
     # /Users/username/.rvm/gems/ruby-2.2.3@gh/gems/actionview-4.2.5.1/lib/action_view/lookup_context.rb:147:in `with_fallbacks'
     # /Users/username/.rvm/gems/ruby-2.2.3@gh/gems/actionview-4.2.5.1/lib/action_view/renderer/abstract_renderer.rb:18:in `with_fallbacks'
     # /Users/username/.rvm/gems/ruby-2.2.3@gh/gems/actionview-4.2.5.1/lib/action_view/renderer/template_renderer.rb:32:in `determine_template'
     # /Users/username/.rvm/gems/ruby-2.2.3@gh/gems/actionview-4.2.5.1/lib/action_view/renderer/template_renderer.rb:8:in `render'
     # /Users/username/.rvm/gems/ruby-2.2.3@gh/gems/actionview-4.2.5.1/lib/action_view/renderer/renderer.rb:42:in `render_template'
     # /Users/username/.rvm/gems/ruby-2.2.3@gh/gems/actionview-4.2.5.1/lib/action_view/renderer/renderer.rb:23:in `render'
     # /Users/username/.rvm/gems/ruby-2.2.3@gh/gems/actionview-4.2.5.1/lib/action_view/rendering.rb:100:in `_render_template'
     # /Users/username/.rvm/gems/ruby-2.2.3@gh/gems/actionpack-4.2.5.1/lib/action_controller/metal/streaming.rb:217:in `_render_template'
     # /Users/username/.rvm/gems/ruby-2.2.3@gh/gems/actionview-4.2.5.1/lib/action_view/rendering.rb:83:in `render_to_body'
     # /Users/username/.rvm/gems/ruby-2.2.3@gh/gems/actionpack-4.2.5.1/lib/action_controller/metal/rendering.rb:32:in `render_to_body'
     # /Users/username/.rvm/gems/ruby-2.2.3@gh/gems/actionpack-4.2.5.1/lib/action_controller/metal/renderers.rb:37:in `render_to_body'
     # /Users/username/.rvm/gems/ruby-2.2.3@gh/gems/actionpack-4.2.5.1/lib/abstract_controller/rendering.rb:25:in `render'
     # /Users/username/.rvm/gems/ruby-2.2.3@gh/gems/actionpack-4.2.5.1/lib/action_controller/metal/rendering.rb:16:in `render'
     # /Users/username/.rvm/gems/ruby-2.2.3@gh/gems/actionpack-4.2.5.1/lib/action_controller/metal/instrumentation.rb:44:in `block (2 levels) in render'
     # /Users/username/.rvm/gems/ruby-2.2.3@gh/gems/activesupport-4.2.5.1/lib/active_support/core_ext/benchmark.rb:12:in `block in ms'
     # /Users/username/.rvm/gems/ruby-2.2.3@gh/gems/activesupport-4.2.5.1/lib/active_support/core_ext/benchmark.rb:12:in `ms'
     # /Users/username/.rvm/gems/ruby-2.2.3@gh/gems/actionpack-4.2.5.1/lib/action_controller/metal/instrumentation.rb:44:in `block in render'
     # /Users/username/.rvm/gems/ruby-2.2.3@gh/gems/actionpack-4.2.5.1/lib/action_controller/metal/instrumentation.rb:87:in `cleanup_view_runtime'
     # /Users/username/.rvm/gems/ruby-2.2.3@gh/gems/activerecord-4.2.5.1/lib/active_record/railties/controller_runtime.rb:25:in `cleanup_view_runtime'
     # /Users/username/.rvm/gems/ruby-2.2.3@gh/gems/actionpack-4.2.5.1/lib/action_controller/metal/instrumentation.rb:43:in `render'
     # ./app/controllers/application_controller.rb:57:in `block in <class:ApplicationController>'
     # /Users/username/.rvm/gems/ruby-2.2.3@gh/gems/activesupport-4.2.5.1/lib/active_support/rescuable.rb:114:in `instance_exec'
     # /Users/username/.rvm/gems/ruby-2.2.3@gh/gems/activesupport-4.2.5.1/lib/active_support/rescuable.rb:114:in `block in handler_for_rescue'
     # /Users/username/.rvm/gems/ruby-2.2.3@gh/gems/activesupport-4.2.5.1/lib/active_support/rescuable.rb:80:in `call'
     # /Users/username/.rvm/gems/ruby-2.2.3@gh/gems/activesupport-4.2.5.1/lib/active_support/rescuable.rb:80:in `rescue_with_handler'
     # /Users/username/.rvm/gems/ruby-2.2.3@gh/gems/actionpack-4.2.5.1/lib/action_controller/metal/rescue.rb:15:in `rescue_with_handler'
     # /Users/username/.rvm/gems/ruby-2.2.3@gh/gems/actionpack-4.2.5.1/lib/action_controller/metal/rescue.rb:32:in `rescue in process_action'
     # /Users/username/.rvm/gems/ruby-2.2.3@gh/gems/actionpack-4.2.5.1/lib/action_controller/metal/rescue.rb:29:in `process_action'
     # /Users/username/.rvm/gems/ruby-2.2.3@gh/gems/actionpack-4.2.5.1/lib/action_controller/metal/instrumentation.rb:32:in `block in process_action'
     # /Users/username/.rvm/gems/ruby-2.2.3@gh/gems/activesupport-4.2.5.1/lib/active_support/notifications.rb:164:in `block in instrument'
     # /Users/username/.rvm/gems/ruby-2.2.3@gh/gems/activesupport-4.2.5.1/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
     # /Users/username/.rvm/gems/ruby-2.2.3@gh/gems/activesupport-4.2.5.1/lib/active_support/notifications.rb:164:in `instrument'
     # /Users/username/.rvm/gems/ruby-2.2.3@gh/gems/actionpack-4.2.5.1/lib/action_controller/metal/instrumentation.rb:30:in `process_action'
     # /Users/username/.rvm/gems/ruby-2.2.3@gh/gems/actionpack-4.2.5.1/lib/action_controller/metal/params_wrapper.rb:250:in `process_action'
     # /Users/username/.rvm/gems/ruby-2.2.3@gh/gems/activerecord-4.2.5.1/lib/active_record/railties/controller_runtime.rb:18:in `process_action'
     # /Users/username/.rvm/gems/ruby-2.2.3@gh/gems/actionpack-4.2.5.1/lib/abstract_controller/base.rb:137:in `process'
     # /Users/username/.rvm/gems/ruby-2.2.3@gh/gems/actionview-4.2.5.1/lib/action_view/rendering.rb:30:in `process'
     # /Users/username/.rvm/gems/ruby-2.2.3@gh/gems/actionpack-4.2.5.1/lib/action_controller/test_case.rb:639:in `process'
     # /Users/username/.rvm/gems/ruby-2.2.3@gh/gems/actionpack-4.2.5.1/lib/action_controller/test_case.rb:67:in `process'
     # /Users/username/.rvm/gems/ruby-2.2.3@gh/gems/actionpack-4.2.5.1/lib/action_controller/test_

**Comment by kjbkjb** [comment]
As a workaround, I'm moving my html error files to the /views/ folder instead of the /public/ folder. I believe this makes rails resolve them via a different renderer that is properly initialized

**Comment by kjbkjb** [comment]
This duplicates https://github.com/rails/rails/issues/23244

**Comment by maclover7** [comment]
Closing since you said this is a dup of #23244, and an RSpec bug.

**Comment by chrisarcand** [comment]
@kjbkjb Just FYI and for posterity of closing this issue, the RSpec bug was indeed fixed and released in [rspec-rails v3.4.1](https://github.com/rspec/rspec-rails/releases/tag/v3.4.1) :+1:

**Comment by kjbkjb** [comment]
Thanks @chrisarcand and the rails and rspec teams!

**Comment by gregory** [comment]
Ran into the same issue when bumping from `3.2.22.1 to 3.2.22.2` - Bumping rspec-rails did the trick.
