### ISSUE TITLE
Rails 5 is inserting null into fixture's timestamp column when loading test db

### ISSUE THREAD

**Issue by sachse** [rails/rails#23316]
Rails 5.0.0.beta1.1

When running a test where a fixture is loaded into my test db, I get the following error:
```
ActiveRecord::StatementInvalid: PG::NotNullViolation: ERROR:  null value in column "created_at" violates not-null constraint
DETAIL:  Failing row contains (11, 1, 1, 1, 2016-01-28, 2016-01-28, MyText, null, null).
: INSERT INTO "comics" ("reads", "status", "chapters", "start_date", "end_date", "description") VALUES (1, 1, 1, '2016-01-28', '2016-01-28', `'MyText')
```
I haven't changed the value of `record_timestamps` anywhere.

The fixture looks like the following:
```yaml
one:
  reads: 1
  status: 1
  chapters: 1
  start_date: 2016-01-28
  end_date: 2016-01-28
  description: MyText
```

And this is the model:
```ruby
module V1
  class Comic < ApplicationRecord
    enum status: { unknown: 0, ongoing: 1, ended: 2 }

    validates :reads, numericality: { only_integer: true }
    validates :status, presence: true, inclusion: { in: %w(unknown ongoing ended) }
    validates :chapters, numericality: { only_integer: true }, allow_nil: true
    validates :start_date, date: { before_or_equal_to: Proc.new { Time.now } }, allow_nil: true
    validates :end_date, date: { after_or_equal_to: :start_date }, allow_nil: true
  end
end
```

**Comment by maclover7** [comment]
Would you be able to provide a sample application to reproduce the error, or create a test script using one of the templates [here](https://github.com/rails/rails/tree/master/guides/bug_report_templates)?

**Comment by sachse** [comment]
Turns out this was happening because Rails couldn't locate the file for my model, so this was my own fault. Some sort of error message might be useful?

**Comment by maclover7** [comment]
A sample application or test script to reproduce the error would be helpful in determining where to raise an appropriate error. :blush:

**Comment by sachse** [comment]
Try running the test on this: https://github.com/sachse/rails-fixture-error

**Comment by emptyflask** [comment]
I'm having the same problem with Rails 5.0.0.
```
rake db:fixtures:load RAILS_ENV=test

ActiveRecord::StatementInvalid: PG::NotNullViolation: ERROR:  null value in column "created_at" violates not-null constraint
DETAIL:  Failing row contains (1, 223486541, 383778367, null, null).
: INSERT INTO "conference_events" ("event_id", "conference_id") VALUES ('383778367', 223486541)
```

@sachese: do you recall what exactly you did to fix the problem?

**Comment by chrisnicola** [comment]
Seeing this as well. It seems that Rails 5 migrations set the timestamp fields to `null: false` whereas Rails 4.0 did not have this constraint. As well, the fixtures do not appear to be setting a created_at/updated_at value unless one is specified.

**Comment by chrisnicola** [comment]
Nope sorry this was also my fault, the model file was missing. I agree with @sachse though a error message from the fixture loader might make sense here. Not sure, you might want to load a fixture you don't have a model for. Not sure why though.

**Comment by jeantristan** [comment]
@chrisnicola Hello, I have the same problem, what do you mean by "model file was missing" ?

**Comment by chrisnicola** [comment]
@jeantristan iirc the `/models` active record class for that table was missing, so the fixture did not work.
