### ISSUE TITLE
Shoryuken adapter?

### ISSUE THREAD

**Issue by phstc** [rails/rails#23311]
Hi

What's the process to add a new Active Job adapter to Rails? I would like know what are the criteria before attempting to create a pull request for a Shoryuken Queue Adapter.

[Shoryuken](https://github.com/phstc/shoryuken) is very similar to Sidekiq, but for [AWS SQS](https://aws.amazon.com/sqs/). For SQS, you can also use [aws-sdk-ruby](https://github.com/aws/aws-sdk-ruby) directly, but Shoryuken offers workers, multi-threading, long running process etc that are not available on the official SDK. Based on a [search for SQS on RubyGems](https://rubygems.org/search?utf8=%E2%9C%93&query=sqs), I believe Shoryuken [is the most popular message processor for SQS](https://rubygems.org/search?utf8=%E2%9C%93&query=shoryuken).

This issue is inspired by the comment below from @avokhmin.

> PS: maybe try to add the shoryuken adapter to the rails?
> https://github.com/phstc/shoryuken/pull/174#issuecomment-176129041

I have two posts related to Shoryuken, Sidekiq and SQS that might motivate the acceptance of this request:

- [Sidekiq (Redis) vs Shoryuken (AWS SQS)
](http://www.pablocantero.com/blog/2015/03/14/sidekiq-redis-vs-shoryuken-aws-sqs/)
- [SQS to the rescue](http://www.pablocantero.com/blog/2014/11/29/sqs-to-the-rescue/)

**Comment by optimisticanshul** [comment]
@phstc https://github.com/rails/rails/pull/21406

**Comment by maclover7** [comment]
@rafaelfranca Do we want to ad more adapters? I am personally against this, I believe you are as well.

**Comment by phstc** [comment]
> @phstc #21406

hm thanks @optimisticanshul 

> @rafaelfranca Do we want to ad more adapters? I am personally against this, I believe you are as well.

I'm kind of against of it as well ^ and I also agree with:

> I really believe we should stop including new adapters and encourage library author to maintain their adapters.
> https://github.com/rails/rails/pull/21406#issuecomment-138813484

For me it's easier to update an adapter on shoryuken repo than in Rails. I believe that the responsibility of maintaining the adapter should belong to library not to Rails.

So why not removing [all these adapters](http://api.rubyonrails.org/classes/ActiveJob/QueueAdapters.html) to avoid confusion, also reducing dependencies on Rails.

**Comment by maclover7** [comment]
I'd say for now to go ahead and add an ActiveJob adapter to shoryuken directly, but adding to ActiveJob itself is up in the air.

**Comment by phstc** [comment]
> I'd say for now to go ahead and add an ActiveJob adapter to shoryuken directly

@maclover7 it's already in there:

- https://github.com/phstc/shoryuken/blob/master/lib/shoryuken/extensions/active_job_adapter.rb
- https://github.com/phstc/shoryuken/wiki/Rails-Integration-Active-Job

I believe the current question is more like asking for the Rails way of doing that. Because currently it seems to be mixed. Some libraries have the adapters inside themselves and others on Rails.

Maybe we can assume that the ones that are on Rails is for backwards compatibility and they will be deprecated in future releases. Because I do agree, that those adapters shouldn't be on Rails itself, unless it's the Rails way.

**Comment by rafaelfranca** [comment]
We are not accepting new adapters. What are already here we don't need to remove but we also don't need to add more. Also, please use the Rails core mailing list to ask questions.
