### ISSUE TITLE
asset/images folder not precompiled by default.

### ISSUE THREAD

**Issue by marcelokanzaki** [rails/rails#23313]
Trying to generate an image tag...

`<%= image_tag 'foo.png' %>`

...for an image placed in:

`assets/images/foo.png`

I get the following:

```
Asset was not declared to be precompiled in production.
Add `Rails.application.config.assets.precompile += %w( foo.png )` to `config/initializers/assets.rb` and restart your server
```

Now I don't if this was supposed to happen but IMHO its not a very good experience for such a basic task.

**Comment by vipulnsward** [comment]
Related https://github.com/rails/sprockets-rails/issues/321
We can continue discussion there.
