### ISSUE TITLE
Rails 4.2 added support for after_bundle to app generation but not for plugin generation

### ISSUE THREAD

**Issue by rfmanuel** [rails/rails#23315]
#16359 added support for after_bundle to app generation, but did not for plugin generation.  This prevents certain actions from occurring that may be dependent upon bundle install (e.g. rspec test generation).  It is somewhat misleading as the developer guide makes it seem like after_bundle should work in both kinds of generation.

**Comment by rafaelfranca** [comment]
Closed because we don't take feature requests in the issue tracker and the PR is already open.
