### ISSUE TITLE
number_to_currency should not return negative zero

### ISSUE THREAD

**Issue by keredson** [rails/rails#23320]
```
[17] pry(main)> helper.number_to_currency BigDecimal('0')*-1
=> "$-0.00"
```

negative zero is not a humanized money amount, so it should never be returned by this function.

**Comment by prathamesh-sonpatki** [comment]
@rafaelfranca Thoughts about this issue? Similar to https://github.com/rails/rails/issues/23321#issuecomment-176517342 ?

**Comment by rafaelfranca** [comment]
This is surprising indeed.

**Comment by pcai** [comment]
Some interesting behavior in [Float#phase](http://ruby-doc.org/core-2.3.0/Float.html#method-i-phase):
```
2.3.0 :026 > (-0.0).phase
 => 3.141592653589793 
2.3.0 :027 > (0.0).phase
 => 0
```
It returns pi on `-0.0`

**Comment by keredson** [comment]
Thanks!
