### ISSUE TITLE
Range#include? override breaks edge case

### ISSUE THREAD

**Issue by baburdick** [rails/rails#23339]
See comment here: https://github.com/rails/rails/commit/d3684c4154df66059ba77d022eca285563b8f506#commitcomment-15772711

**Comment by baburdick** [comment]
This is the only other issue I could find that appears similar: rails/rails#22599 . Not sure if they're related. But mentioning just in case.

**Comment by nathell** [comment]
Per the [discussion in original commit](https://github.com/rails/rails/commit/d3684c4154df66059ba77d022eca285563b8f506#commitcomment-15772711), this is not a bug in Rails and so this issue should be closed.

**Comment by baburdick** [comment]
Closing.
