### ISSUE TITLE
ActiveRecord::Migration.maintain_test_schema! without rails

### ISSUE THREAD

**Issue by yairgo** [rails/rails#23341]
ActiveRecord::Migration.maintain_test_schema! does not work out of the box without rails. 
The code below makes two assumptions that I think should be addressed:
1. You have to have Rails defined for this to work. 
2. You have to have binstubs for this to work.
lib/active_record/migration.rb:581 
```ruby   
def load_schema_if_pending!
  if ActiveRecord::Migrator.needs_migration? || !ActiveRecord::Migrator.any_migrations?
  # Roundtrip to Rake to allow plugins to hook into database initialization.
    FileUtils.cd Rails.root do
      current_config = Base.connection_config
      Base.clear_all_connections!
      system("bin/rails db:test:prepare")
      # Establish a new connection, the old database may be gone (db:test:prepare uses purge)
      Base.establish_connection(current_config)
    end
    check_pending!
  end
end
```

I monkey patched my spec_helper file with the following to get around the first issue
```ruby
module Rails
  def self.root
    MyApp.root
  end
  def self.env
    MyApp.env
  end
end
```
I don't have a better solution but it could at least be documented somewhere.

I also don't have a better solution for the 2nd item, but if you are running without binstubs then the system call to `bin/rake db:test:prepare` fails silently.

**Comment by maclover7** [comment]
@sgrif Do we want to to provide an `ActiveRecord.root` or an environment variable or something to allow users to customize the location? Assuming that we also want to change that `rails` command back to `rake`, since we can't guarantee all AR users are also using Rails.

**Comment by yairgo** [comment]
I didn't want to force my opinion on the topic, but I thought the way to use bin stubs properly was to ensure that your application root/bin was on the front of your path that way your bin stubs are used. I think changing it back to just rake should be fine.

I don't like the idea of ActiveRecord.root, makes it seem like ActiveRecord should have a root, maybe just change the wording, ActiveRecord.application_root ? 

Or, since the code also needs to know the env, and currently it uses Rails.env, maybe for this to work you could specify ActiveRecord.app = MyApp and then I could have MyApp.root and MyApp.env defined.

I don't know how this would work for Rails apps that have multiple engines and what not though.

**Comment by sgrif** [comment]
I don't think it's a reasonable assumption that this should work without Rails. This is meant to be used as part of the test setup provided by a full Rails app.

**Comment by yairgo** [comment]
I've been working with Rails since 2006. At one point in time everything was just rails. Now things have been split out into separate module so that you can pull them in separately.

And your answer to ActiveRecord failing because I'm not using Rails is that it isn't supposed to work without Rails?

If that is your opinion then that is fine, I'll just add Rails.root and Rails.env to my applications. 

Can I at least put in a pull request to change 'bin/rails db:test:prepare' to 'rake db:test:prepare'?

**Comment by sgrif** [comment]
> And your answer to ActiveRecord failing because I'm not using Rails is that it isn't supposed to work without Rails?

Active Record isn't failing. One feature that exists as part of a Rails app's test suite is failing.

> Can I at least put in a pull request to change 'bin/rails db:test:prepare' to 'rake db:test:prepare'?

The intention is to migrate all rake commands to the Rails CLI.

**Comment by rafaelfranca** [comment]
Agree with @sgrif here.

**Comment by yairgo** [comment]
Allright, so if the rake commands are all moving to the Rails CLI, what are the implications of that going to be moving forward using active record without Rails? Is there a link somewhere documenting what these changes will mean?

**Comment by sgrif** [comment]
Short version: There are no implications for using Active Record, the library for querying the database from Ruby. The CLI tool which brings things like migrations and generators is part of `railties`, not `active_record`.
