### ISSUE TITLE
Websocket request being sent multiple times and then not recieving due to disconnecting

### ISSUE THREAD

**Issue by Sexual** [rails/rails#23340]
![network](https://slut.io/i/5KpBRYF4t.png "Chrome network requests")
![network-2](https://slut.io/i/dtrleuwBN.png "")

Just a `regular rails g channel` and using @dhh 's tutorial

```ruby
# Be sure to restart your server when you modify this file. Action Cable runs in an EventMachine loop that does not support auto reloading.
class TicketChannel < ApplicationCable::Channel
  def subscribed
    # stream_from "some_channel"
    stream_from 'tickets'
  end

  def unsubscribed
    # Any cleanup needed when channel is unsubscribed
  end

  def speak(data)
    ActionCable.server.broadcast('tickets', message: render_message(data['message']))
  end

  private

  def render_message(message)
    ApplicationController.render(partial: 'tickets/message', locals: { message: message })
  end
end

```

```coffee
App.ticket = App.cable.subscriptions.create "TicketChannel",
  connected: ->
    # Called when the subscription is ready for use on the server

  disconnected: ->
    # Called when the subscription has been terminated by the server

  received: (data) ->
    $('.chat-box').prepend(data.message)
    # Called when there's incoming data on the websocket for this channel

  speak: ->
    @perform 'speak'


$(document).on 'keypress', '#ticket_message_message', (event) ->
  if event.keyCode is 13
    App.ticket.speak(event.target.value)
    event.target.value = ""
    event.preventDefault()

```
Even if attempting to `speak` via the console on the first websocket request, it still isn't recieved.

**Comment by maclover7** [comment]
Could you provide a sample application to reproduce the error?

**Comment by Sexual** [comment]
@maclover7 I cannot as it's implemented into my private application, in which i cannot release the source. But pretty much everything i provided is what is related to actioncable.

**Comment by maclover7** [comment]
I will try and create a small application to model this behavior. Keep in mind that these errors could be issues within your own application.

**Comment by matthewd** [comment]
This is exactly how it behaves if nothing's being sent across the socket after the initial connect (so, the pings aren't arriving). You should be able to confirm that's what's happening by examining one of those connections.

Is this beta1(.1), or master? If master, which revision?

**Comment by Sexual** [comment]
@matthewd 1.1. And if that's the case how come nothing is ever received when sent. From what i've been able to comprehend, a new connection is being created overriding the past connection where it should be received (assuming that's not how it works now).

**Comment by Sexual** [comment]
I believe this may just be a issue of laccking documentation due to the nature of this obviously being a beta.
![progress](http://i.imgur.com/QUMJ4YV.png "Progress")
http://stackoverflow.com/a/34686305/4778326 Although not completely relevant, it does mention this error and i'm assuming something with the configuration is wrong vs what documentation has been stated.

```yaml
development: &development
  :url: redis://password@127.0.0.1:6379/15
  :host: 127.0.0.1
  :password: 'password'
  :port: 6379
  :inline: true
  :timeout: 1
```
This is how it currently is, and i know it works as i use it for sidekiq. Which leads me to believe a possible conflict between the two?

**Comment by maclover7** [comment]
What you have posted above is not the correct way to configure ActionCable. Below is how you should structure your `config/cable.yml` correctly:

```yaml
development:
  adapter: redis
  url: redis://password@127.0.0.1:6379/15
```

**Comment by Sexual** [comment]
@maclover7 Structuring like that yields the same results.

**Comment by Sexual** [comment]
```
Started GET "/cable/" [WebSocket] for --------- at 2016-01-30 07:22:20 -0500
Error raised inside the event loop: undefined method `[]' for nil:NilClass
/usr/local/rvm/gems/ruby-2.3.0@rails5.0/gems/actioncable-5.0.0.beta1.1/lib/action_cable/server/base.rb:60:in `redis'
/usr/local/rvm/gems/ruby-2.3.0@rails5.0/gems/actioncable-5.0.0.beta1.1/lib/action_cable/server/base.rb:55:in `pubsub'
/usr/local/rvm/gems/ruby-2.3.0@rails5.0/gems/actioncable-5.0.0.beta1.1/lib/action_cable/connection/base.rb:52:in `pubsub'
/usr/local/rvm/gems/ruby-2.3.0@rails5.0/gems/actioncable-5.0.0.beta1.1/lib/action_cable/channel/streams.rb:101:in `pubsub'
/usr/local/rvm/gems/ruby-2.3.0@rails5.0/gems/actioncable-5.0.0.beta1.1/lib/action_cable/channel/streams.rb:79:in `block in stream_from'
/usr/local/rvm/gems/ruby-2.3.0@rails5.0/gems/eventmachine-1.0.9.1/lib/eventmachine.rb:981:in `block in run_deferred_callbacks'
/usr/local/rvm/gems/ruby-2.3.0@rails5.0/gems/eventmachine-1.0.9.1/lib/eventmachine.rb:978:in `times'
/usr/local/rvm/gems/ruby-2.3.0@rails5.0/gems/eventmachine-1.0.9.1/lib/eventmachine.rb:978:in `run_deferred_callbacks'
/usr/local/rvm/gems/ruby-2.3.0@rails5.0/gems/eventmachine-1.0.9.1/lib/eventmachine.rb:193:in `run_machine'
/usr/local/rvm/gems/ruby-2.3.0@rails5.0/gems/eventmachine-1.0.9.1/lib/eventmachine.rb:193:in `run'
/usr/local/rvm/gems/ruby-2.3.0@rails5.0/gems/faye-websocket-0.10.2/lib/faye/websocket.rb:36:in `block in ensure_reactor_running'

```

**Comment by maclover7** [comment]
I'm sorry, but without further information we're not going to be able to provide anymore assistance. My thought is that you do not have something configured correctly in your `config/cable.yml`, because that is what the error log above is showing. Feel free to reopen if you are able to provide or create a demo application that can reproduce this error.
