### ISSUE TITLE
rails5 generate scaffold with only ref fields generates a broken controller test

### ISSUE THREAD

**Issue by rubys** [rails/rails#23384]
Reproduction scenario:

    rm -rf throwaway
    rails new throwaway 
    cd throwaway
    rails generate scaffold Product title
    rails generate scaffold Cart title
    rails generate scaffold LineItem product:references cart:belongs_to
    rails db:migrate
    rails test

Test results: [throwaway.txt](https://github.com/rails/rails/files/111405/throwaway.txt)

[this is with rails master]

**Comment by sgrif** [comment]
Would probably be helpful to post the test it generates here, as well.

**Comment by rubys** [comment]
Generated test that fails:

    test "should create line_item" do
      assert_difference('LineItem.count') do
        post line_items_url, params: { line_item: { cart_id: @line_item.cart_id, product_id: @line_item.product_id } }
      end

      assert_redirected_to line_item_path(LineItem.last)
    end

**Comment by rubys** [comment]
More importantly here is the generated fixture:

    one:
      product:
      cart:

    two:
      product:
      cart:

Here is a modified fixture that works:

    one:
      product: one
      cart: one

    two:
      product: two
      cart: two
