### ISSUE TITLE
Test DB wont update on migration

### ISSUE THREAD

**Issue by avdept** [rails/rails#23397]
Scenario: 
- Create migration(add new column)
- Run it.
- Change column type(string -> int)
- Rollback
- Run again.

End up with having int column in dev db, and string in test

**Comment by rafaelfranca** [comment]
You need to run `db:test:prepare` task. The automatic schema migration doesn't have how to know that you changed a existent migration.

**Comment by avdept** [comment]
But i did rollback, shouldnt that remove that column from test db aswell?

**Comment by rafaelfranca** [comment]
No, it doesn't. Any migration only run in development database, same with rollbacks.

**Comment by avdept** [comment]
Then whats the reason for `The Rails test helper now maintains your test schema automatically, see the release notes for details.` message while doing rake db:test:clone ?

**Comment by rafaelfranca** [comment]
About that, see https://github.com/rails/rails/commit/fc9c6c9468040e0bb85c643ba84807c41500724f

**Comment by avdept** [comment]
Thanks. Explains alot
