### ISSUE TITLE
Waves changed to Wafe

### ISSUE THREAD

**Issue by lettergram** [rails/rails#23392]
I had an issue where I tried creating a scaffold called brainwave and it converted brainwaves to brainwafe, but brainwave was used when singular. This was fine, I changed everything to wave when it should be singular and it appeared to work. 

Then, when I tried adding it to users, i.e. adding `has_many :brainwaves` and using it, I received an error that `brainwafe is uninitialized`.

Any solutions would be helpful.

![brainwafe](https://cloud.githubusercontent.com/assets/1498748/12708990/a9c31d92-c85b-11e5-92f3-7082634e9202.png)

**Comment by rafaelfranca** [comment]
This is one of the default inflection rules. You can change this rule in your application. See http://api.rubyonrails.org/classes/ActiveSupport/Inflector/Inflections.html and https://github.com/rails/rails/blob/master/activesupport/lib/active_support/inflections.rb. Also check the file inside `config/initializer/inflections.rb` inside you application to see examples

**Comment by lettergram** [comment]
Thanks
