### ISSUE TITLE
Comment out examples in fixtures.yml to stop hurting newbies

### ISSUE THREAD

**Issue by greyman888** [rails/rails#23409]
When installing devise and creating a User model with:

    rails generate devise User
    rake db:migrate
A User model is created with a validation on unique email addresses.
If you already had some tests in place, every test (even those not related to users) will now throw an error:

    ActiveRecord::RecordNotUnique: SQLite3::ConstraintException: UNIQUE constraint failed: users.email: INSERT INTO "users" ("created_at", "updated_at", "id") VALUES ('2016-02-01 22:03:10.726289', '2016-02-01 22:03:10.726289', 298486374)
When you’re new this is pretty confusing because up to this point all you’ve probably done is create a few static pages, write some tests and install devise by following the docs.
The cause is that when rails generates the `user.yml` file it contains :

    one: {}
    # column: value
    #
    two: {}
    # column: value
If you comment out these lines the errors go away but it could take a newbie (like me) a while to figure out what’s wrong.
Here’s an examples in stackoverflow that has been viewed nearly 4000 times:
http://stackoverflow.com/questions/5769758/adding-index-to-email-column-culprit-for-unit-tests-failing
and another one:
http://stackoverflow.com/questions/8279403/rails-strange-unit-test-fails
A quick and simple fix would be to comment out all the lines in:
`rails/railties/lib/rails/generators/test_unit/model/templates/fixtures.yml`

Sorry I didn’t make a PR but I’m pretty new and didn’t want to screw anything up to just comment out two lines of code.

Thanks.

**Comment by claudiob** [comment]
Hello @greyman888 and thanks for stopping by.

From what you describe, this sounds more like an issue with devise than with rails itself.
Have you tried submitting an issue to devise?

**Comment by greyman888** [comment]
Hi, thanks for the reply.

Potential for the problem occurs any time you generate a new model because two empty fixtures with useless names are created by default in the *.yml file. These empty fixtures serve no purpose and the first thing that anyone would do is delete or replace them.

Here is another example from @mhartl in his rails tutorial (not using devise). He explains to the reader that all their tests have gone red after adding a uniqueness constraint to the User email due to the default content of the `users.yml` file. His instruction is to remove the fixtures from `users.yml`.

https://www.railstutorial.org/book/_single-page#code-default_fixtures

As a new person to rails it feels weird that you should need to delete some useless lines of code from an automatically created file to make your tests work. I like the idea of providing examples but they should be helpful and commented out.

**Comment by sgrif** [comment]
Regardless of whether this is the right change or not, this is not a bug. We reserve the issue tracker for bugs only (e.g. X used to work in 4.2 but is broken in 5). Feel free to submit a pull request, or open a thread on the Rails core mailing list for feature requests.
