### ISSUE TITLE
Active Record .find method cannot simultaneously search post tags and content. 

### ISSUE THREAD

**Issue by maecapozzi** [rails/rails#23403]
When building a custom search bar, I was unable to use Active Record to search for both relevant tags and content. I wrote a raw SQL statement to do this. 

```
def self.search(search_query)
  find_by_sql("SELECT DISTINCT posts.* FROM posts LEFT JOIN taggeds ON posts.id =     
  taggeds.post_id LEFT JOIN tags ON tags.id = taggeds.tag_id WHERE (upper(posts.title) LIKE '%#
  {search.upcase}%' OR upper(tags.name) LIKE '%#{search.upcase}%') ORDER BY posts.created_at 
  DESC;")
end 
```

**Comment by rafaelfranca** [comment]
Please use the mailing list or StackOverflow for questions/help, where a wider community will be able to help you. We reserve the issues tracker for issues only.
