### ISSUE TITLE
Typecasting Array value in where query possible?

### ISSUE THREAD

**Issue by doits** [rails/rails#23405]
I'm currently looking to implement a custom type with [ActiveRecord::Type::Value](https://github.com/rails/rails/blob/master/activemodel/lib/active_model/type/value.rb) following [the enum implementation](https://github.com/rails/rails/blob/master/activerecord/lib/active_record/enum.rb), using Rails 5.0.0.beta1.1.

So far I have I got it working to cast everything from and to database correctly.

```
class BitFieldType < ActiveRecord::Type::Value
  def initialize(name, mapping, subtype)
    @name = name
    @mapping = mapping
    @subtype = subtype
  end

  def cast(value)
    [...]
  end

  def deserialize(value)
    [...]
  end

  def serialize(value)
    [...]
  end

  def assert_valid_value(value)
    [...]
  end

  protected

  attr_reader :name, :mapping, :subtype
end

class SomeModel < ActiveRecord::Base
  decorate_attribute_type(:my_attribute_name, :bit_field) do |subtype|
    BitFieldType.new(:my_attribute_name, [...], subtype)
  end
end
```

Only problem I have: I want to cast a array as a whole in `where()` calls, not each value.

Now, when I call for example:

    SomeModel.where(my_attribute_name: [1, 2, 3])

... it passes each value (`1`, `2`, `3`) to my `serialize` method and then builds a query like

    [...] where my_attribute_name IN (<serialized 1>, <serialized 2>, <serialized 3>)

I'd rather want to decide how that call turns out, so basically that the array `[1, 2, 3]` is passed to my `serialize` method, not each value of it. Then I could `serialize` it to an value which should simply be compared with `=`:

    [...] where my_attribute_name = <serialized [1, 2 3]>

Is this possible?

**Comment by rafaelfranca** [comment]
Please use the mailing list or StackOverflow for questions/help, where a wider community will be able to help you. We reserve the issues tracker for issues only.
