### ISSUE TITLE
Rails 5 Migration timestamp null option

### ISSUE THREAD

**Issue by JuanitoFatas** [rails/rails#23418]
In Rails 4.2 release notes:

<img width="584" alt="screenshot 2016-02-02 14 05 04" src="https://cloud.githubusercontent.com/assets/1000669/12741327/43c2025e-c9b6-11e5-91a5-289899d14d9a.png">

It says we need to pass in `:null` option otherwise a deprecation warning will be thrown. 

Today I tried Rails 5, both beta1 & beta2 does not emit this option in migration file.

What is the correct behaviour?

Related:

- [In 4.2 migrations, `timestamps` defaulted to `null: true`](https://github.com/matthewd/rails/commit/badaf353ba4591ce78fa0c305b656f7cae56992b)
- [Change the default `null` value for timestamps #16481](https://github.com/rails/rails/pull/16481)

**Comment by prathamesh-sonpatki** [comment]
@JuanitoFatas Rails 5 has added compatibility layer for older migrations. So if you have a migration created in Rails 4.2 version which does not specify `null: true` or `null: false` on timestamps columns it will be treated as `null: true` while running the migrations in Rails 5 so as to not cause backward incompatibilities. 

As the compatibility layer takes care of older migrations we do not need deprecation warning, because there is no change in behaviour for older migrations.

If you generate a new migration in Rails 5, the default behaviour will be - timestamps have `null: false`

**Comment by JuanitoFatas** [comment]
> If you generate a new migration in Rails 5, the default behaviour will be - timestamps have null: false

Exactly. But I did not see this option being generated with Rails 5.0.0.beta1 & 5.0.0.beta2.

**Comment by vipulnsward** [comment]
@JuanitoFatas can you post example migration that you get on Rails 5?

**Comment by prathamesh-sonpatki** [comment]
@JuanitoFatas there is no option listed in the migration, but it's `null: false` by default.

**Comment by prathamesh-sonpatki** [comment]
For eg.

This is migration in Rails 5 - 

```
$ cat db/migrate/20160203080031_create_posts.rb 
class CreatePosts < ActiveRecord::Migration[5.0]
  def change
    create_table :posts do |t|
      t.string :name
      t.text :body

      t.timestamps
    end
  end
end
```

And this is underlying table - 

```
cache_key_app_development=# \d posts;
                                     Table "public.posts"
   Column   |            Type             |                     Modifiers                      
------------+-----------------------------+----------------------------------------------------
 id         | integer                     | not null default nextval('posts_id_seq'::regclass)
 name       | character varying           | 
 body       | text                        | 
 created_at | timestamp without time zone | not null
 updated_at | timestamp without time zone | not null
Indexes:
    "posts_pkey" PRIMARY KEY, btree (id)

cache_key_app_development=# 

```

**Comment by JuanitoFatas** [comment]
> @JuanitoFatas there is no option listed in the migration, but it's null: false by default.

Oh nice! I was expected there is a `null: false`. Thank you, close this issue.
