### ISSUE TITLE
Suggestion for performance improvement: lazy type conversion

### ISSUE THREAD

**Issue by eiked** [rails/rails#23415]
Hi on the rails road,
I'd like to make a suggestion that could improve performance.

I'd like to suggest that type conversion of attributes loaded from the database should not happen upfront (on load), but instead should be performed on the first access to the respective attribute (aka lazy).

I have not yet looked into this deeply nor did I perform any benchmarks yet.

My current understanding is:
- the database adapter delivers rows as as hashes of strings
- that hashes values get converted to the proper types to populate the ActiveRecord objects attributes
- the objects are ready for use

I'd like to suggest that the type conversion step should not be done at load time, but should instead be lazy and only be done on the first access to the respective attribute.

I have been working with date parsing and found that to be slow.
(some tables might at least have created_at and updated_at, this sums up)

I have pretty wide tables and joining in more tables makes them even wider.
(you guess it: they might have the two date fields attached as well)

So a lot of effort is spent up front on type conversion of these fields, even if they are never used.
(I'm pretty much aware that I could only select the fields in question)

I want to suggest, that the type conversion should be postponed to the first access of a field.

- he'd need to carry around the row's hash from the database adapter.
- we'd need to mark the not yet converted attributes
- we'd need to modify the read accessors to do the conversion on the first access (lazy)

That should make it work for read only access.
Some more work might be needed for write back.
Maybe some parts of the code do not yet go through the read accessors.
(like was_modified or such)

But it would be ok for that part of AR as well,
once we get them to access the attributes through the read accessors.

Last but not least, my rationale:
- queries are fast
- rendering is fast (take on that next ...)
- so where does this time get lost?
-> correct if I'm wrong, but quite some time is spent in type conversion.

I have not yet looked deeply into this,
so I might be completely wrong.

As mentioned before, another option is to only select the columns that one needs,
but this fails when you need to guess the column names of the joins.
and it leaves you with uninitialized columns (and that would not be rails style anyway)

I believe that lazy type conversion can be implemented into AR,
possibly without even breaking any client code.

I'd expect that to speed up some of our most used pages at least three fold.
(that's a gain to run for)

I've also been thinking of memory usage.
We'd need to take the not yet typed columns around.
but we could delete them from the adapters hash when they got converted.

Again, I've not yet benchmarked this.
Your mileage may vary.

**Comment by maclover7** [comment]
Please use the mailing list for feature requests, where a wider community will be able to help you. We reserve the issues tracker for issues only.

**Comment by rafaelfranca** [comment]
cc @sgrif I think you already looked on this, so maybe you want to reply.

**Comment by sgrif** [comment]
> I'd like to suggest that type conversion of attributes loaded from the database should not happen upfront (on load), but instead should be performed on the first access to the respective attribute (aka lazy).

This is our behavior today.

**Comment by sgrif** [comment]
Just finished reading through the whole thing. You've described our current setup. So... Feature request accepted, I guess?

**Comment by eiked** [comment]
Hi maclover7,
you you please reopen this.
Improving rails speed is an issue for me.
(as it must be for some other people around)

I believe this could speed up rails a three fold.
It's just not fair to close this within 3 seconds.

Please open this up again,
give it three days, so that people have a chance to read my suggestions.

**Comment by eiked** [comment]
Hi sgrif,

this is rails: it is done already.
please excuse me for suggesting that.
but then my suggestion was not that bad?


but I'm still looking for performance improvements.
I had a look at https://github.com/mezis/viscacha
This is shared memory caching on the local host.

We could then cache even smaller snippets,
because a cache request would not involve ip,
but just only be an in memory request.

Take a look at rockers.de
(it's the list view that's not yet as fast as I want it to be)
