### ISSUE TITLE
Suggestion: a new cache level

### ISSUE THREAD

**Issue by eiked** [rails/rails#23416]
Hi on the rails road,
I'd like to suggest a new level of caching for rails apps,
aka local host caching (in memory)

Caching is built into rails.
You might know doll caching.
We currently use memcached as backend.

But this involves ip traffic.
So there is some price to pay if you need the cache.

I stumbled upon https://github.com/mezis/viscacha
That is a shared in-memory cache.

We could use that to share even smaller snippets.
within the instances running on one machine.

**Comment by rafaelfranca** [comment]
Thank you so much for the issue but we don't take feature request on the issue tracker. We recommend you to try to implement the feature and send us a pull request or if you are in doubt if the feature will be accepts ask in Rails Core mailing list for feedback.
