### ISSUE TITLE
Better spacing with the default logger on Puma

### ISSUE THREAD

**Issue by dhh** [rails/rails#23428]
The default logger needs to send a CR after the request is over. Right now it's all smushed together like:

```
Processing by PostsController#show as HTML
  Parameters: {"id"=>"1"}
  Post Load (0.1ms)  SELECT  "posts".* FROM "posts" WHERE "posts"."id" = ? LIMIT ?  [["id", 1], ["LIMIT", 1]]
  Rendered posts/show.html.erb within layouts/application (0.6ms)
Completed 200 OK in 22ms (Views: 18.2ms | ActiveRecord: 0.1ms)
Started GET "/posts" for ::1 at 2016-02-02 16:06:30 +0100
Processing by PostsController#index as HTML
  Post Load (0.2ms)  SELECT "posts".* FROM "posts"
  Rendered posts/index.html.erb within layouts/application (1.9ms)
Completed 200 OK in 26ms (Views: 24.6ms | ActiveRecord: 0.2ms)
```

Should be:

```
Processing by PostsController#show as HTML
  Parameters: {"id"=>"1"}
  Post Load (0.1ms)  SELECT  "posts".* FROM "posts" WHERE "posts"."id" = ? LIMIT ?  [["id", 1], ["LIMIT", 1]]
  Rendered posts/show.html.erb within layouts/application (0.6ms)
Completed 200 OK in 22ms (Views: 18.2ms | ActiveRecord: 0.1ms)

Started GET "/posts" for ::1 at 2016-02-02 16:06:30 +0100
Processing by PostsController#index as HTML
  Post Load (0.2ms)  SELECT "posts".* FROM "posts"
  Rendered posts/index.html.erb within layouts/application (1.9ms)
Completed 200 OK in 26ms (Views: 24.6ms | ActiveRecord: 0.2ms)
```

**Comment by vipulnsward** [comment]
This is due to https://github.com/rails/rails/pull/23220 and having a newline causes https://github.com/rails/rails/issues/23215

**Comment by dhh** [comment]
Well, we're going to have to come up with something better. Because having the requests smushed together like this is a regression for developing with the log running.

**Comment by vipulnsward** [comment]
I think its ok to have a single newline, since this space issue will be fixed with sprockets 4 cc @schneems

**Comment by syamilmj** [comment]
Is `#development?` still going to be useful there?

**Comment by schneems** [comment]
Im fine putting the spaces back in. We will still get double or triple newlines sometimes since we are serving the requests concurrently with Puma. We could maybe implement some kind of locking as MD mentioned but I'm wary of introducing too much complexity and creating new problems in the process. We could make puma default to 1 thread in development but then it might hide threading bugs and slow down the development rendering experience.

**Comment by dhh** [comment]
I think definitely we should keep Puma to multi threads but let's only send the line clears together with the line for completing a Rails request (the line reporting status code and timing). Don't want to send it together with assets etc.
