### ISSUE TITLE
Add prepared statement support for Mysql2 adapter

### ISSUE THREAD

**Issue by npepinpe** [rails/rails#23421]
The mysql2 gem supports prepared statements since version 0.4. Should possible for applications which can upgrade to 0.4 to use prepared statements. Useful case is when doing bulk insert and fetching inserted IDs afterwards, prepared statements offer great performance with little added complexity (i.e. prepare statement, execute insert, get last inserted ID, rinse and repeat, with comparable performance to prepared mass insert statement).

**Comment by kaspth** [comment]
Thanks, but we don't accept feature requests on the issues tracker. Please ask this on the Rails core mailing list.
