### ISSUE TITLE
rails --skip-sprockets option creates many undocumented issues for the unwary 

### ISSUE THREAD

**Issue by coldnebo** [rails/rails#23431]
Sprockets integration is systemic starting with Rails 3 and cannot be trivially disabled without introducing other issues.  [The Asset Pipeline](https://github.com/rails/rails/blob/8b2c618cefef1ccd83d270cbacdd19abf4be9b2f/guides/source/asset_pipeline.md#L32) guide makes it appear easy to disable sprockets by using `--skip-sprockets` without any warnings or caveats.

One caveat is that using `--skip-sprockets` leaves `jquery-rails` in the generated Gemfile.  But `jquery-rails` relies on vendor/assets/javascripts in order to work. Most Rails devs would expect that app/assets wouldn't work after disabling the pipeline, but many others I've talked to are surprised that jquery-rails doesn't work because 1) the official rails generator includes it and 2) they may be less familiar with how the asset pipeline functions.

Other caveats:
* some Rails Engines don't work properly, such as [bootstrap-rails-engine](https://github.com/yjchen/bootstrap-rails-engine)
* gems such as [active_scaffold](https://github.com/activescaffold/active_scaffold) and [cells](https://github.com/apotonick/cells) don't work properly
* `remote: true` no longer functions -- this particularly affects constructs using `form_for` and ajax. Notice that the [Working with Javascript in Rails](http://edgeguides.rubyonrails.org/working_with_javascript_in_rails.html) guide does not mention that this feature is dependent on `jquery-ujs` (located in the `jquery-rails` gem, which is broken by disabling the asset pipeline).

Many junior (and even some senior) Rails developers are confused by these issues because it isn't obvious how the asset pipeline is involved and the integration errors arising from these situations can be difficult to diagnose.

There should be some warning about the extended consequences so that Rails developers can make an informed decision about whether to disable the asset pipeline or not.

**Comment by matthewd** [comment]
Maybe `--skip-sprockets` should remove `jquery-rails`?

I'm not sure how much we can do about the rest... to me, it seems little different than being unable to access a database after using `--skip-active-record`. Like Active Record, Sprockets *is there for a reason*; if you don't know what it does, you probably shouldn't be turning it off.

**Comment by rafaelfranca** [comment]
> Maybe --skip-sprockets should remove jquery-rails?
> 
> I'm not sure how much we can do about the rest... to me, it seems little different than being unable to access a database after using --skip-active-record. Like Active Record, Sprockets is there for a reason; if you don't know what it does, you probably shouldn't be turning it off.

:+1:

**Comment by coldnebo** [comment]
> Maybe --skip-sprockets should remove jquery-rails?

I agree.

In a perfect world, gem authors using assets would test for the asset pipeline being enabled and raise an error if it's not present (i.e. from their railties).

> if you don't know what it does, you probably shouldn't be turning it off.

But the guide claims to tell people what the pipeline does:

> The asset pipeline provides a framework to concatenate and minify or compress JavaScript and CSS assets. It also adds the ability to write these assets in other languages and pre-processors such as CoffeeScript, Sass and ERB.

Based on that description, I might decide that I don't really need it, without understanding the other ramifications.  Maybe the description could be expanded to explain how it unifies assets from various locations (such as gems, engines, etc) and is required for rails ujs functions (including turbolinks).

Another fix might be to change the [Working with Javascript in Rails](http://guides.rubyonrails.org/working_with_javascript_in_rails.html) guide to match the style of [Layouts and Rendering](http://guides.rubyonrails.org/layouts_and_rendering.html) guide which says:

> If you are using Rails with the Asset Pipeline enabled, this helper will generate a link to /assets/javascripts/ rather than public/javascripts which was used in earlier versions of Rails. This link is then served by the asset pipeline.

This way, people reading about a specific feature, say `remote: true` would see mention of the asset pipeline and know the requirements.  

_Notice that `javascripts_include_tag` falls back gracefully to `/public/javascripts` when the asset pipeline is disabled, while `remote` ujs simply breaks without warning._

**Comment by coldnebo** [comment]
I can work on a pull request to flesh some of these ideas out this weekend as a starting point.

**Comment by rafaelfranca** [comment]
That is great! Please go ahead.
