### ISSUE TITLE
ActiveRecord 4.2 clones all strings/arrays during typecast on default setters

### ISSUE THREAD

**Issue by MartinKoerner** [rails/rails#23430]
Hi,

consider following simple project:

```ruby
rails new testproject
rails g model Building name:string
rails db:migrate
rails console
  >> building = Building.new
  >> name = "Testname"
  >> building.name = name
  >>
  >> puts name.object_id # => 70199493308960
  >> puts building.name.object_id # => 70199493278780  <= new object!
  >> puts building.attributes_before_type_cast['name'].object_id # => 70199493308960
```

If I have a serialized attribute with arrays, the array including all (string) elements will be cloned.
This started with Rails 4.2.0, while in 4.1.14 all three object_id outputs are the same.

Tested with Ruby 2.2.2, 2.2.3 and JRuby 9.0.4.0

**Comment by sgrif** [comment]
This is by design, in order to detect mutations.

**Comment by sgrif** [comment]
In Rails 5 you can opt into an immutable string type which does not `dup` its values. https://github.com/rails/rails/commit/34321e4a

**Comment by MartinKoerner** [comment]
Thanks for the fast answer.

I wonder, if such a rather big change would have been worth noting in the release notes. The "notable changes" section of ActiveRecord mentions the mutation detection, but I didn't realize, that my objects will be cloned for that.

Would it be useful to add a rails option to `.freeze` all params after request parsing and, at the same time, prevent ActiveRecord from calling `dup` for `.frozen?` strings?

**Comment by sgrif** [comment]
No, this only matters for strings and we've now given you that option
