### ISSUE TITLE
Instance dependent association preloading which was removed has valid use cases

### ISSUE THREAD

**Issue by agios** [rails/rails#23435]
4ed97979d14c5e92eb212b1a629da0a214084078 removed support for preloading instance-dependent associations.

While it is understandable that they might have been a source of confusion, associations such as the one presented in #15024 which this addressed, can be properly preloaded in this manner:

```ruby
class User < ActiveRecord::Base
  has_many :posts, ->(sender) {
    title_condition =
      if sender.is_a? User
        sender.name
      else # Relation
        User.arel_table[:name]
      end
    where(arel_table[:title].eq(title_condition))
  }
end
```
This code results in an association that can both be called on an instance as well as preloaded in another query. Removing this feature actually breaks working code.

What do you think @senny, @rafaelfranca?

**Comment by rafaelfranca** [comment]
It was already removed and we don't plan to add it back. Even that you can make it work it still have to check if you are in a instance. Also to make it work you are relying in private API of the framework `arel_table`.

**Comment by rafaelfranca** [comment]
This is a dup of https://github.com/rails/rails/issues/22560
