### ISSUE TITLE
number_to_currency prints $Inf when passed infinity

### ISSUE THREAD

**Issue by smtheard** [rails/rails#23441]
```bash
irb(main):004:0> helper.number_to_currency(Float::INFINITY)
=> "$Inf"
```
This isn't human readable, and makes no sense for this view helper method to return. I propose throwing an error instead of returning $Inf.

**Comment by rafaelfranca** [comment]
What is the use case? Why `Float::INFINITY` end up as an argument to this method?

**Comment by smtheard** [comment]
this came up when grabbing numeric values from an external source and doing some invalid arithmetic to them. I agree it should not generally be called with infinity, but it should throw an error if it does I would think.

**Comment by rafaelfranca** [comment]
While I can get your argument I don't think we should have special case for that is a programming error. `Float::INFITITY` is a valid numeric value and this method work as expected for a valid numeric value.
