### ISSUE TITLE
rails 5 beta2 still eager loads model based on old EventMachine dependency

### ISSUE THREAD

**Issue by bluehallu** [rails/rails#23445]
Since rails 5 beta 2 dropped the dependency on EventMachine, config.ru on a newly generate project (rails new...) shouldn't contain these lines;
```

# Action Cable uses EventMachine which requires that all classes are loaded in advance
Rails.application.eager_load!
```

**Comment by matthewd** [comment]
beta2 shouldn't be mentioning EventMachine: https://github.com/rails/rails/blob/v5.0.0.beta2/railties/lib/rails/generators/rails/app/templates/config.ru.tt#L6

The eager load is (currently) still required.
