### ISSUE TITLE
after_filter not executing when ActionController::Live is included in controller

### ISSUE THREAD

**Issue by jtmkrueger** [rails/rails#23454]
In my controller, I have an `include ActionController::Live` line at the top of the file. One of my methods has an `after_filter` which will only fire when I comment out the aforementioned include line. My first intuition was to move the `after_filter` method body after the render call in the controller, but this didn't solve the problem. It appears that anything after `render` in the controller will not execute if `ActionController::Live` is included. If this is intended, or expected, then maybe let's find a place to document it so others aren't as confused as I was.

**Comment by sgrif** [comment]
Code is executed after `render` just fine. Was unable to reproduce by doing the following:

```shell
rails new foo && cd foo
echo "Rails.application.routes.draw { resources :foos }" > config/routes.rb
echo "class FoosController < ApplicationController
  include ActionController::Live

  after_action { puts 'LOL' }

  def index
    render :index
  end
end" > app/controllers/foos_controller.rb
mkdir app/views/foos
touch app/views/foos.html.erb
rails s &
curl localhost:3000/foos
```

You will see `LOL` printed to the console as expected. You of course cannot modify the response after you've streamed it, which is fully documented. This is likely a problem in your application, not Rails. If you think there is a bug in Rails, please provide an executable test case which demonstrates the issue using our standard bug report template (https://github.com/rails/rails/blob/master/guides/bug_report_templates/action_controller_master.rb), or provide a minimal rails app which reproduces the issue.

**Comment by jtmkrueger** [comment]
You're right! It's probably an interaction with a gem or maybe something related to our network setup. Thanks for clarifying that.
