### ISSUE TITLE
rake rails:update doesn't update config.ru

### ISSUE THREAD

**Issue by dudo** [rails/rails#23450]
Not sure if this is intentional, but I had to remove the eventmachine stuff from config.ru when updating from beta1 to beta2.

```
# This file is used by Rack-based servers to start the application.

require ::File.expand_path('../config/environment', __FILE__)

# Action Cable uses EventMachine which requires that all classes are loaded in advance
Rails.application.eager_load!
require 'action_cable/process/logging'

run Rails.application
```

logging had to go. Looks like the comment changed too. https://github.com/rails/rails/blob/25a42755403ba4a8d9a4128d5ff6483ca2fd9252/railties/lib/rails/generators/rails/app/templates/config.ru.tt

**Comment by maclover7** [comment]
cc @matthewd

**Comment by maclover7** [comment]
I believe that this is a dup of #23367.

**Comment by matthewd** [comment]
I don't think `rails:update` officially/deliberately supports updates within the beta series.. @rafaelfranca?

**Comment by rafaelfranca** [comment]
It doesn't.
