### ISSUE TITLE
The asset pipeline is compiling sass files separately

### ISSUE THREAD

**Issue by sergio-bobillier** [rails/rails#23463]
I'm experiencing a really weird behavior in the Assets Pipeline after updating to Rails 4.2.5.1.

I changed the Gemfile and did `bundle update`. I did not change anything else but now when I try to load my development environment the application won't start. The browser receives an HTTP 500 error with no content. In the logs I can see the error is related to a undefined mixin in one of my sass files:

    ActionView::Template::Error (Undefined mixin 'transition'.):
    app/assets/stylesheets/admin/fixes/_fixes-foundation.scss:17:in `transition'

The mixin is undefined in the _fixes-foundation.scss files because it is defined in another file called _mixins.scss (which is included before the fixes file).

I tried to pin point the cause of the error and after a couple of hours messing around I found that the asset pipeline is compiling any sass file it finds under the app/assets/stylesheets folder, including those that should not be compiled separately (which usually you prefix with an underscore).

To test if my theory was correct I created another file and put it somewhere within my app/assets/stylesheets directory. I called the file _test.scss and did not `@include` the file in any other sass file and still rails raises an error about it:

    ActionView::Template::Error (Undefined mixin 'mymixin'.):
    app/assets/stylesheets/admin/testing/foo/bar/_test.scss:4:in `mymixin'

This did not happen with Rails 4.2.3.

Something that bothers me is the fact that these files are not directly in the app/assets/stylesheets directory but actually four levels down. If the Asset Pipeline behavior changed and now it scans the stylesheets directory and sub directories then where should I put the files I don't want compiled separately?

**Comment by sgrif** [comment]
Please provide a minimal rails app which demonstrates this issue. The details as provided are not sufficient for us to reproduce.

**Comment by sergio-bobillier** [comment]
When creating the minimal application I realized that what was causing the issue was the standard application.css file. It seems like this was causing the strange behavior. Once I removed the file everything worked fine again.

It is weird that I had that file in my development environment but never used it and until now the error never popped up.
