### ISSUE TITLE
rails command gives inconsistent results for errors

### ISSUE THREAD

**Issue by repinel** [rails/rails#23467]
Because of how [this line](https://github.com/rails/rails/blob/e22404a8b2f258ca657fc54f0f3700b75db0c05b/railties/lib/rails/command.rb#L66) checks for available commands, something like `rails class` would silently fail. `echo $?` would be `0`.

On the other hand, something like `rails foobar` would fail with:
```
rails aborted!
Don't know how to build task 'foobar' (see --tasks)
railties/lib/rails/commands/rake_proxy.rb:13:in `block in run_rake_task'
railties/lib/rails/commands/rake_proxy.rb:10:in `run_rake_task'
railties/lib/rails/commands/commands_tasks.rb:51:in `run_command!'
railties/lib/rails/command.rb:20:in `run'
railties/lib/rails/commands.rb:19:in `<top (required)>'
bin/rails:4:in `require'
bin/rails:4:in `<main>'
(See full trace by running task with --trace)
```

By defining a better way to check available commands, those that inherit from `Rails::Command`, #23410 could be fixed by dynamic generating that additional piece of the help.

@kaspth What do you think?

**Comment by bronson** [comment]
Loosely related to #23410.  A fix to one might affect the other.

**Comment by kaspth** [comment]
Thanks! Pursuing the command stuff in time for 5.0 is slim. Instead: https://github.com/rails/rails/issues/23410#issuecomment-181058488 :heart:

**Comment by bronson** [comment]
Not sure I agree with closing this one since the oddball behavior it notes (`rails class`) is still an issue.

Maybe it would be worth opening a new issue to collect Rails command requirements?

Another item for that collection would be making the commands self-documenting.  Another would be converting existing commands (and doing it right: fix the architecture, no workarounds).

**Comment by repinel** [comment]
@bronson Agreed. I kind of meant this [here](https://github.com/rails/rails/pull/23552#issuecomment-181423248).

**Comment by kaspth** [comment]
It isn't an issue anymore, because no tasks inherit from `Rails::Command` at the moment. I'm working on the next step of what commands will be. Thanks! :heart:
