### ISSUE TITLE
ActiveModel#Errors creates key in messages hash if there are any errors for that given key

### ISSUE THREAD

**Issue by meinac** [rails/rails#23468]
If you want to access an error for an attribute with `model.errors[:foo]` if there are any error on that attribute, it creates an entry on messages hash with this attribute name. So after try to access errors of an attribute if you want to get all error keys from the `ActiveModel::Errors` instance it will return wrong keys. Lets look at the example;

``` ruby
  post = Post.new
  post.errors.keys # => []
  post.errors[:foo] # => []
  post.errors.keys # => [:foo]
```

I think this is intended behaviour but it's weird and error prone. Is there any reason to create a key on messages hash for given attribute name if there are any errors on that attribute?

**Comment by vipulnsward** [comment]
Thanks, for reporting.

We initialize the errors using 
`@messages = Hash.new { |messages, attribute| messages[attribute] = [] }`
for errors, so as to easily allow-

`model.errors[:field] << some_value`

This behaviour is intentional, and cannot be bypassed without unnecessary conditions.

If are relying on `errors` object, you can reject blank values in this hash.

**Comment by meinac** [comment]
@vipulnsward thank you for your response. I know this is intended because I've looked at history of this class. I understand that you are doing this to handle adding new error into given key easily but we can handle this internally without introducing an abnormal behaviour. Even if you don't want to fix this, we have to add this behaviour into the documentation but I would love to see that this behaviour changed because it's really abnormal behaviour.

**Comment by vipulnsward** [comment]
I don't think its worth the complexity, leaving open if anyone has opinions, or for doc updates.

**Comment by maclover7** [comment]
@meinac I feel like a solution to this could be to freeze the hash we are sending back to the users through `post.errors`, so that way the hash can't be changed by the end users.

**Comment by maclover7** [comment]
Dug into this a bit more, looks like `ActiveModel::Errors#[]=` is being deprecated in Rails 5.1 anyway. Not sure if it's worth the documentation change, since the method is being deprecated fairly soon. https://github.com/rails/rails/blob/master/activemodel/lib/active_model/errors.rb#L167-L179

**Comment by meinac** [comment]
@maclover7 the issue is not about adding errors into `ActiveModel::Errors`. I saw that `[]=` method has been deprecated but `[]` method is not so if you try to access errors with a key like `errors[:foo]` it will instantiate this key into messages hash with empty array. After that if you try to access keys of errors with `errors.keys` it will return wrong keys. The abnormal behaviour is that I'm just trying to access errors of a key and Rails instantiates it with an empty array and as a result of this behaviour I'm getting wrong list of keys from `errors.keys`.

**Comment by maclover7** [comment]
I have a patch for this locally. PR imminent.

**Comment by rafaelfranca** [comment]
I already have said this many time in many tickets. This behavior is intentional and we don't plan to change. We can improve the documentation though. Feel free to open a PR.

**Comment by AlexVPopov** [comment]
@vipulnsward @rafaelfranca I understand the rational for this (having it easy to add errors like this: `model.errors[:field] << some_value`), but what about `errors.details`? Accessing a key via `errors[:foo]` only adds it to `messages`, not to `details`. That's confusing.

**Comment by rafaelfranca** [comment]
It should not matter if an empty array was added to `messages` or `details` since it is just an empty array and there is no errors there.

**Comment by AlexVPopov** [comment]
This means one cannot reliably call `errors.keys` or `errors.messages.keys` and be sure that all the contained keys are actual errors. One has to get used to always rejecting empty values first: `errors.messages.reject { |attribute, error_messages| error_messages.empty? }`. That's kind of odd behavior...

**Comment by meinac** [comment]
> This means one cannot reliably call errors.keys or errors.messages.keys and be sure that all the contained keys are actual errors.

Exactly. But this behaviour is documented [here](https://github.com/rails/rails/blob/master/activemodel/lib/active_model/errors.rb#L136). I know that it's utterly weird to have **side effect** for a **reader** method but **at least** we have documentation about it.

One solution might be using a wrapper class around array or a class which is extended from array to store error messages which acts like falsy if it is empty.

**Comment by rafaelfranca** [comment]
We could also change `keys` and `values` to only return the keys that don't have empty messages.

**Comment by AlexVPopov** [comment]
@rafaelfranca That would be a good solution to the problem.

**Comment by meinac** [comment]
@rafaelfranca, this will solve lots of problems.

**Comment by maclover7** [comment]
Reopening the issue since there is a PR attached for it.

**Comment by sekmo** [comment]
For posterity: now we can use `errors.include?` / `errors.has_key?` / `errors.key?`
