### ISSUE TITLE
"bin/rails rails:update" does not respect API mode

### ISSUE THREAD

**Issue by makabde** [rails/rails#23470]
With the recent release of Rails 5.0.0.beta2, I tried to upgrade my new app (on 5.0.0.beta1.1) using the `bin/rails rails:update` command.
While looking at the diff for `config/application.rb` at least, I noticed that the generator tried to replace this previous file content content without keeping the API configuration line.

```
- require "rails"
+ require 'rails/all'
- # Pick the frameworks you want:
- require "active_model/railtie"
- require "active_job/railtie"
- require "active_record/railtie"
- require "action_controller/railtie"
- require "action_mailer/railtie"
- require "action_view/railtie"
- require "action_cable/engine"
- # require "sprockets/railtie"
- # require "rails/test_unit/railtie"

  # Require the gems listed in Gemfile, including any gems
  # you've limited to :test, :development, or :production.
  Bundler.require(*Rails.groups)

  module Tapp
    class Application < Rails::Application
-     config.generators do |generate|
-       generate.request_specs true
-       generate.routing_specs false
-       generate.test_framework :rspec, fixture: true
-       generate.fixture_replacement :factory_girl, dir: 'spec/factories'
-     end
      # Settings in config/environments/* take precedence over those specified here.
      # Application configuration should go into files in config/initializers
      # -- all .rb files in that directory are automatically loaded.
-
-     # Custom directories with classes and modules we want to be autoloadable
-     config.autoload_paths.push(*%W(#{config.root}/lib))
-
-     # Set Time.zone default to the specified zone and make Active Record auto-convert to this zone.
-     # Run "rake time:zones:all" for a time zone names list. Default is UTC.
-     config.time_zone = 'Zurich'
-     config.active_record_default_timezone = 'Zurich'
-
-     # Only loads a smaller set of middleware suitable for API only apps.
-     # Middleware like session, flash, cookies can be added back manually.
-     # Skip views, helpers and assets when generating a new resource.
-     config.api_only = true
    end
  end

**Comment by greyder** [comment]
Hi, I tried updating an **API only Rails 5.0.0.beta2** to **Rails 5.0.0.beta3**, and I suddenly can't get my tests to run. It displays this error:

`railties-5.0.0.beta3/lib/rails/railtie/configuration.rb:95:in `method_missing': undefined method `assets' for #<Rails::Application::Configuration:0x007f80066191e8> (NoMethodError)`

I was able to solve the issue by removing the ff. generated files:

-  config/initializers/assets.rb
- config/initializers/cookies_serializer.rb
- config/initializers/per_form_csrf_tokens.rb
- config/initializers/request_forgery_protection.rb
- config/initializers/session_store.rb

I've checked the `rails --tasks` to see if there's an available API-only option for `rails:update`, so it will only generate the necessary files, but there seems to be none as of this moment.
