### ISSUE TITLE
Standardize ActionCable config.ru location

### ISSUE THREAD

**Issue by FooBarWidget** [rails/rails#23474]
The ActionCable config.ru location is not standardized. Although the README and all the current tutorials suggest making a cable/config.ru, this is only a suggestion, not a recommended default location.

A standardized ActionCable config.ru location will make it much easier for Passenger to autodetect whether the application uses ActionCable, and if so, determine how to start the ActionCable server.

**Comment by dhh** [comment]
We default to running cable in-process via the mount in routes.rb. Running cable as a separate process is a more advanced, optional deployment technique. It should not be used to determine whether an app is using cable or not.

**Comment by FooBarWidget** [comment]
If it defaults to in-process then standardizing the location won't be necessary.
