### ISSUE TITLE
Could not find "api_controller.rb" in any of your source paths.

### ISSUE THREAD

**Issue by kirantpatil** [rails/rails#23476]
Hi,

I am trying to create a Rails 5 api app using http://alessiofanelli.com/blog/building-a-rails-5-and-ember-js-app.

I get the "could not find api_controller.rb" error while executing the scaffold command as below.

**$ rails g scaffold team name:string city:string championships:integer**
Running via Spring preloader in process 32480
      invoke  active_record
   identical    db/migrate/20160204101609_create_teams.rb
   identical    app/models/team.rb
      invoke    test_unit
   identical      test/models/team_test.rb
   identical      test/fixtures/teams.yml
      invoke  resource_route
       route    resources :teams
   identical  app/serializers/team_serializer.rb
      invoke  scaffold_controller
**Could not find "api_controller.rb" in any of your source paths. Your current source paths are: 
/home/kpatil/.gem/ruby/gems/active_model_serializers-0.9.4/lib/active_model/serializer/generators/serializer/templates**

I think because of it I could not execute the command.
**$ curl -H "Content-Type:application/json; charset=utf-8" -d '{"name":"Lakers","city": "Los Angeles","championships": 16}' http://localhost:3000/teams**

> <!DOCTYPE html>
> <html>
> <head>
>   <title>The page you were looking for doesn't exist (404)</title>
>   <meta name="viewport" content="width=device-width,initial-scale=1">
>   <style>
>   body {
>     background-color: #EFEFEF;
>     color: #2E2F30;
>     text-align: center;
>     font-family: arial, sans-serif;
>     margin: 0;
>   }
> 
>   div.dialog {
>     width: 95%;
>     max-width: 33em;
>     margin: 4em auto 0;
>   }
> 
>   div.dialog > div {
>     border: 1px solid #CCC;
>     border-right-color: #999;
>     border-left-color: #999;
>     border-bottom-color: #BBB;
>     border-top: #B00100 solid 4px;
>     border-top-left-radius: 9px;
>     border-top-right-radius: 9px;
>     background-color: white;
>     padding: 7px 12% 0;
>     box-shadow: 0 3px 8px rgba(50, 50, 50, 0.17);
>   }
> 
>   h1 {
>     font-size: 100%;
>     color: #730E15;
>     line-height: 1.5em;
>   }
> 
>   div.dialog > p {
>     margin: 0 0 1em;
>     padding: 1em;
>     background-color: #F7F7F7;
>     border: 1px solid #CCC;
>     border-right-color: #999;
>     border-left-color: #999;
>     border-bottom-color: #999;
>     border-bottom-left-radius: 4px;
>     border-bottom-right-radius: 4px;
>     border-top-color: #DADADA;
>     color: #666;
>     box-shadow: 0 3px 8px rgba(50, 50, 50, 0.17);
>   }
>   </style>
> </head>
> 
> <body>
>   
>   <div class="dialog">
>     <div>
>       <h1>The page you were looking for doesn't exist.</h1>
>       <p>You may have mistyped the address or the page may have moved.</p>
>     </div>
>     <p>If you are the application owner check the logs for more information.</p>
>   </div>
> </body>
> </html>

Which shows below message in terminal
$ rails s
=> Booting Puma
=> Rails 5.0.0.beta2 application starting in development on http://localhost:3000
=> Run `rails server -h` for more startup options
=> Ctrl-C to shutdown server
Puma 2.16.0 starting...
* Min threads: 0, max threads: 16
* Environment: development
* Listening on tcp://localhost:3000
Started POST "/teams" for 127.0.0.1 at 2016-02-04 16:25:06 +0530
  ActiveRecord::SchemaMigration Load (0.2ms)  SELECT "schema_migrations".* FROM "schema_migrations"

**ActionController::RoutingError (uninitialized constant TeamsController):**
  activesupport (5.0.0.beta2) lib/active_support/inflector/methods.rb:259:in `const_get'
  activesupport (5.0.0.beta2) lib/active_support/inflector/methods.rb:259:in `block in constantize'
  activesupport (5.0.0.beta2) lib/active_support/inflector/methods.rb:257:in `each'
  activesupport (5.0.0.beta2) lib/active_support/inflector/methods.rb:257:in `inject'
  activesupport (5.0.0.beta2) lib/active_support/inflector/methods.rb:257:in `constantize'
  actionpack (5.0.0.beta2) lib/action_dispatch/http/request.rb:93:in `controller_class'
  actionpack (5.0.0.beta2) lib/action_dispatch/routing/route_set.rb:44:in `controller'
  actionpack (5.0.0.beta2) lib/action_dispatch/routing/route_set.rb:30:in `serve'
  actionpack (5.0.0.beta2) lib/action_dispatch/journey/router.rb:42:in `block in serve'
  actionpack (5.0.0.beta2) lib/action_dispatch/journey/router.rb:29:in `each'
  actionpack (5.0.0.beta2) lib/action_dispatch/journey/router.rb:29:in `serve'
  actionpack (5.0.0.beta2) lib/action_dispatch/routing/route_set.rb:724:in `call'
  rack (2.0.0.alpha) lib/rack/etag.rb:25:in `call'
  rack (2.0.0.alpha) lib/rack/conditional_get.rb:38:in `call'
  rack (2.0.0.alpha) lib/rack/head.rb:12:in `

**Comment by matthewd** [comment]
Please use the mailing list or StackOverflow for questions/help, where a wider community will be able to help you. We reserve the issues tracker for issues only.
