### ISSUE TITLE
rails5 ActionController::Live locks database

### ISSUE THREAD

**Issue by rubys** [rails/rails#23483]
Adding the following to any controller:

```ruby
include ActionController::Live
```

Causes tests to fail:

```
Error:
CustomersControllerTest#test_should_create_customer:
ActiveRecord::StatementInvalid: SQLite3::BusyException: database is locked: commit transaction
    app/controllers/customers_controller.rb:31:in `block in create'
    app/controllers/customers_controller.rb:30:in `create'

Error:
CustomersControllerTest#test_should_destroy_customer:
ActiveRecord::StatementInvalid: SQLite3::BusyException: database is locked: commit transaction
    app/controllers/customers_controller.rb:58:in `destroy'
```

Full scenario: https://intertwingly.net/tmp/live_lock.html#create_model

**Comment by maclover7** [comment]
cc @tenderlove

**Comment by maclover7** [comment]
Is this error present on 4-2-stable? Also, could you create a test script using one of the templates [here](https://github.com/rails/rails/tree/master/guides/bug_report_templates), that will reproduce the error you are seeing? I'm happy to do a bisect on this, once the test script is ready to go. :)

**Comment by rubys** [comment]
This error is *not* present on 4-2-stable.  And it is quite possible that this specific type of test which involves running rails commands as a user would can't be easily reproduced using those templates.  For Rails 4.2, it involves installing puma as a gem.

Overall background on these tests (which are open source, and you are welcome to contribute to them) can be found in the [Releasing Rails](https://github.com/rails/rails/blob/master/RELEASING_RAILS.md#is-sam-ruby-happy--if-not-make-him-happy) document.

Meanwhile, here is the actual test that was used to produce the results I posted:

```ruby
require 'gorp/test'

class LiveLock < Gorp::TestCase

  test "including ActionController::Live" do
    overview <<-EOF
      Any attempt to use ActionController::Live locks the database.
    EOF

    rails 'demo'

    desc 'Create a model', id: 'create_model'
    generate 'scaffold Customer name:string'

    desc 'Run the migration'
    db :migrate

    desc 'Run the tests - this passes'
    test

    desc "Include ActionController::Live"
    edit 'app/controllers/customers_controller.rb' do
      msub /class.*\n()/, "  include ActionController::Live\n"
    end

    desc 'Run the tests'
    rake 'test' do
      assert_select '.stdout', /0 failures/
      assert_select '.stdout', /0 errors/
    end
  end
end
```

If that test had passed in the recent past, `git bisect` could be used with it; but it has been such a long time since anybody (including myself) has paid attention to the AWDwR tests that I fear that changes in gem dependencies would thwart any use of `git bisect`.

Recent test results for this part of the scenario:
 *  [Rails 4-2-stable](http://intertwingly.net/projects/AWDwR4/checkdepot-215-42/section-12.3.html#cmd16)
 * [Rails master](http://intertwingly.net/projects/AWDwR4/checkdepot/section-12.3.html#cmd14)

**Comment by rubys** [comment]
@tenderlove thanks for the fix!  Now curl requests hang.  I'll see if I can isolate a test case.

**Comment by rubys** [comment]
Opened as https://github.com/rails/rails/issues/23503
