### ISSUE TITLE
Strange routing bug

### ISSUE THREAD

**Issue by colepanike** [rails/rails#23487]
I have a mailer called `ContactMailer` and a controller called `ContactController`, both are generated with rails.

The routing for this looks like this:

    get '/contact' => 'contact#index'
    post '/contact' => 'contact#send'

No matter what I do, the GET request goes to the `send` action. The `rake routes` looks fine, and the controller is dead simple:

     def index
     end

     def send (email) # Had to add param due to 'Wrong number of arguments' error
       render text: "Hello " + email # Returns "Hello _run_process_action_callbacks"
       # redirect_to({ action: :form }, success: true)
     end

So I know that's not wrong.

The only way I can fix this is to change the `send` to `send_email`.

Not sure if it's a conflict with the mailer or what. Just thought I'd let you know. Let me know if you need more information.

**Comment by kipcole9** [comment]
#send is a pretty fundamental method in Ruby for sending messages to objects and probably best avoided.  I might not be the underlying cause of the issue here, but it would seem likely.  Best to change your action name to something that doesn't conflict with Ruby's intrinsic methods.
