### ISSUE TITLE
Docs for first_or_create and similar methods

### ISSUE THREAD

**Issue by oesgalha** [rails/rails#23495]
Hi,

The `first_or_create`, `first_or_create!` and the `first_or_initialize` methods were nodoc'ed a while ago (october 2012):
rails/rails@0096f53b25e68c3fc79429253f816fff4a4ee596

So, despite those being public methods, they don't appear in the [API Docs](http://api.rubyonrails.org/) but they aren't deprecated either.

Is there a plan to deprecate those? If not we could add the docs back to them, so that new users can find those methods in the API Docs (or even in the guides).

Thanks for your time.

**Comment by maclover7** [comment]
cc @sgrif

**Comment by sgrif** [comment]
Those method are not part of the public API.

**Comment by oesgalha** [comment]
Are they not?

They don't have docs for themselves, but there are some use examples of them in the docs for the `find` method. See the "Variations of find" session here:
http://api.rubyonrails.org/classes/ActiveRecord/FinderMethods.html#method-i-find

Copy and paste of the examples:
```ruby
Person.where(name: 'Spartacus', rating: 4).first_or_initialize
# returns the first item or returns a new instance (requires you call .save to persist against the database).

Person.where(name: 'Spartacus', rating: 4).first_or_create
# returns the first item or creates it and returns it, available since Rails 3.2.1.
```

Should those be removed then?

**Comment by rafaelfranca** [comment]
> Should those be removed then?

Yes.

**Comment by oesgalha** [comment]
Ok.

Can I make a PR with a reference to this issue that remove those examples?

And how about a deprecation warning?

Thanks for the quick answers. :)

**Comment by sgrif** [comment]
Why would we deprecate these methods? They're part of our internal API. We are allowed to have methods that aren't public.

**Comment by oesgalha** [comment]
My concern is that those method are used in the wild like it's part of the public API. (Don't know why)
I've seen it in some projects I worked on, in some open source rails apps and gems. The most popular gem I've seen using it is Spree.
And since it's part of the internal API, there's no guarantee that any of those method will be available in future releases, right?
I thought deprecation looked like a good way to prevent users from writing code that can break in the future (it was a suggestion), but you're right: it doesn't make sense to deprecate internal API.
