### ISSUE TITLE
Have link_to add rel="nofollow' to GET links with remote: true

### ISSUE THREAD

**Issue by yourtallness** [rails/rails#23492]
It is my understanding that the link_to helper adds rel="nofollow" to non-GET links so that they are not crawled by (well-behaved) bots.

However wouldn't it be useful if this also applied to GET links with remote: true?
We are having issues with bots crawling our site accessing remote GET links for which no html response format is available, leading to an ActionView::MissingTemplate error.

While it could be argued that there are other workarounds (e.g. custom js, using button_to instead of link_to, etc.) sometimes this is not very practical (for instance when the link is already within a form).

Since remote GET links should not really be crawlable, would you consider the aforementioned functionality?

Thank you in advance

**Comment by rafaelfranca** [comment]
Thank you so much for the issue but we don't take feature request on the issue tracker. We recommend you to try to implement the feature and send us a pull request or if you are in doubt if the feature will be accepts ask in Rails Core mailing list for feedback.

**Comment by yourtallness** [comment]
Thanks for the feedback, will look into it.
