### ISSUE TITLE
action_cable.url have no impact on action_cable_meta_tag

### ISSUE THREAD

**Issue by Nekromancer** [rails/rails#23506]
I set `config.action_cable.url = 'ws://localhost:3000/cable'` on my `development.rb` to use ActionCable while using BrowserSync. But `action_cable_meta_tag` returns `<meta name="action-cable-url" content="ws://localhost:4000/cable">`

I have BrowserSync on 4000 port. I've used before rails 5.0.0.beta1 so i had to change some configs for ActionCable to work. Am i doing something wrong?

**Comment by maclover7** [comment]
Can you post a sample app to reproduce the error? Based on Action Cable's [source](https://github.com/rails/rails/blob/master/actioncable/lib/action_cable/helpers/action_cable_helper.rb#L25), this shouldn't be happening.

**Comment by Nekromancer** [comment]
Unfortunetely i cannot reproduce that error on a new project template.

My project started with rails5.0.0.beta1 and now it's upgraded to rails5.0.0.beta2. Maybe there is something missing in gemfile or config? Is there any diff on rails beta1 vs rails beta2?

**Comment by maclover7** [comment]
I'd say that as long as the error is solved in version 5.0.0beta2, then we can close this out. Weird that the bug was both introduced and then solved.
