### ISSUE TITLE
rails5 ActionController::Live causes requests to hang

### ISSUE THREAD

**Issue by rubys** [rails/rails#23503]
Adding the following to any controller:

```ruby
include ActionController::Live
```

causes all requests to hang.

Full scenario: http://intertwingly.net/tmp/live_hang.html#create_company

**Comment by tenderlove** [comment]
Thanks @rubys.  I think this is a deadlock with the const missing / interlock stuff that @matthewd added.  I am able to reproduce and get stack traces, but I'm not sure why we're deadlocking.

**Comment by matthewd** [comment]
Yeah, this is my fault. I'll do a thing.

**Comment by rubys** [comment]
:+1:
