### ISSUE TITLE
Speed up ActionDispatch::Reloader for static assets 10x

### ISSUE THREAD

**Issue by mikhailov** [rails/rails#23510]
Given a dummy Rails app with large number of scaffold-generated objects (Code LOC: 18849) and hundred gems (sample taken from https://github.com/discourse/discourse/blob/master/Gemfile) tried to measure performance hit for static assets. Newelic in development mode helped to figure it out thoroughly.

The problem is a middleware responsible for [Ruby classes reload](https://github.com/rails/rails/blob/857263445035404786e1f9785b76f3f4ddb7ca12/railties/lib/rails/application/default_middleware_stack.rb#L63-L65) slows serving static assets down. Profiling with Newrelic shows the following results (88% spent on Reloader middleware):

![screen shot 2016-02-06 at 01 08 48](https://cloud.githubusercontent.com/assets/14601/12863468/5ecfdcb4-cc6e-11e5-8c38-2afed69d1023.png)

siege benchmark results (siege -b http://localhost:3000/assets/application.js):
```
Transaction rate:	        2.60 trans/sec
Concurrency:		       11.87
```

I tried to skip this middleware for static assets based on condition expression (correct me if I'm wrong) *env['PATH_INFO'].include?(Rails.application.config.assets.prefix)* the results suprised me a bit:

![screen shot 2016-02-06 at 01 09 30](https://cloud.githubusercontent.com/assets/14601/12863470/62b71612-cc6e-11e5-8ad1-bae964ad4e59.png)

siege benchmark results (siege -b http://localhost:3000/assets/application.js):
```
Transaction rate:	       16.13 trans/sec
Concurrency:		       11.82
```

Having some change in application.js doesn't require rails server to restart, changes reloaded on-fly as usual, the difference is no callbacks chain and no clears dependencies for static assets anymore.

This change makes a diffference in development mode when serve static assets without Nginx. Please let me know what you think, patch is available as gist for a moment: https://gist.github.com/mikhailov/7e6d925044327a87db4f

Increase LOC from 18K to 27K followed by slowness of response for non-patched middleware. It seems the complexity is O(n) compare to O(1) for code with the patch.

**Comment by schneems** [comment]
Static assets can be rendered outside of the asset pipeline. A GET to "/" could render public/index.html. We have to make sure we handle that case.

**Comment by schneems** [comment]
Sorry just saw the patch. Ignore that last comment I see what you mean.

**Comment by mikhailov** [comment]
@schneems right, files from /public served via *ActionDispatch::Static* directly, but any assets (non-Ruby classes) goes through the Reloader middleware which can be redundant.

**Comment by maclover7** [comment]
This makes sense to me, for performance reasons. Would you be willing to open up a PR for this, so other people could comment on the code?

**Comment by mikhailov** [comment]
@maclover7 please take a look the PR, Thanks!

**Comment by kirs** [comment]
Here is the link to PR: https://github.com/rails/rails/pull/23518

**Comment by matthewd** [comment]
Closing in favour of the PR
