### ISSUE TITLE
Mailer missing template in Rails 5 api_only

### ISSUE THREAD

**Issue by louisscruz** [rails/rails#23526]
I am currently trying to set up a mailer on my Rails 5 api_only server. I get the following error:

```
(Missing template user_mailer/welcome_email with "mailer". Searched in:
  * "user_mailer"
):
```

The mailer looks as follows:

```
class UserMailer < ApplicationMailer
  default from: 'xx@xxx.com'

  def welcome_email(user)
    @user = user
    @url  = 'http://0.0.0.0:3000/login'
    mail(to: 'xxx@xxxxx.com', subject: 'Welcome to the site')
  end
end
```
There are indeed views located at `views/user_mailer/welcome_email.html.erb` and `views/user_mailer/welcome_email.text.erb`.

The mailer is temporarily being called in the controller's show method:

```
def show
   UserMailer.welcome_email(@user).deliver_now
   render json: @user
end
```

I have tried setting `config.api_only = false` and I've also stopped Spring several times. I am using Rails 5.0.0.beta1.

**Comment by maclover7** [comment]
Can you provide a sample application to reproduce the error you are seeing? If you change `config.api_only = false` to `config.api_only = true`, does this resolve the error?

**Comment by louisscruz** [comment]
Here is a fresh project with the same error:

https://github.com/louisscruz/test_api

Changing config is no help.

**Comment by maclover7** [comment]
Ok - found the error. You have the views stored in `views/user_mailer/*`, instead of `app/views/user_mailer/*`. This should solve the issue.

**Comment by louisscruz** [comment]
Such a stupid mistake... Always thankful for an extra set of eyes!

In case it will help anyone else, I couldn't get the mailer to retrieve the views without specifically indicating both a `template_path` and `template_name`, as well as a `do |format|` block. For me, the block did not need to include anything at all – it just needed to exist.

Thanks for the help!

**Comment by i2chris** [comment]
Adding template_path and template_name with an empty block worked for me in Rails 6. That is bizzare
