### ISSUE TITLE
rails5 form authenticity_tokens don't work

### ISSUE THREAD

**Issue by rubys** [rails/rails#23524]
This will cause problems for automation tools like mechanize.

Reproduction instructions: view source on any page that uses `form_for`.  Any edit page generated by scaffolding will do.  What you will see will be something like:

```
<!DOCTYPE html>
<html>
  <head>
    <title>Demo</title>
    <meta name="csrf-param" content="authenticity_token" />
<meta name="csrf-token" content="R/+8o7qCIsdpxYv0X/fxuZg8Tq5At6st3wmNM5vHgr7qdo29rBsTIE4mtxOFbGYTfcXTTI+Da88GirnPQUDkKQ==" />
    <meta name="action-cable-url" content="/cable" />

    <link rel="stylesheet" media="all" href="/assets/companies.self-e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855.css?body=1" data-turbolinks-track="true" />
<link rel="stylesheet" media="all" href="/assets/scaffolds.self-13e017ed781aee5641573fc553cae1177b6eb2ae02ee29ba9a3927350998c06d.css?body=1" data-turbolinks-track="true" />
<link rel="stylesheet" media="all" href="/assets/application.self-af04b226fd7202dfc532ce7aedb95a0128277937e90d3b3a3d35e1cce9e16886.css?body=1" data-turbolinks-track="true" />
    <script src="/assets/jquery.self-c64a74367bda6ef8b860f19e74df08927ca99d2be2ac934e9e92d5fd361e0da4.js?body=1" data-turbolinks-track="true"></script>
<script src="/assets/jquery_ujs.self-d602bdfe68ffc63b9f9cc512872aa3cfff046228a0a36e90dd476e8ef54c1b09.js?body=1" data-turbolinks-track="true"></script>
<script src="/assets/turbolinks.self-088c452541bc2cb3c0ff28ae33e5c6516d309f7e097363b1d7d062f9cbe5a947.js?body=1" data-turbolinks-track="true"></script>
<script src="/assets/action_cable.self-8fc7cfd5b796d0299c89a57dbf5b046051f42ce410f160fd7f1e677c8dc07def.js?body=1" data-turbolinks-track="true"></script>
<script src="/assets/action_cable/connection.self-5625494ff511c0f78cd0746ef7e14909f3d517ceb45f989511e4b216c1862593.js?body=1" data-turbolinks-track="true"></script>
<script src="/assets/action_cable/connection_monitor.self-ca8bfd8bf7c622d03bf8314cbde2cf77e5a7732c8082e2fc50828a14175f6b53.js?body=1" data-turbolinks-track="true"></script>
<script src="/assets/action_cable/subscriptions.self-156d38d6efaf3f6139b95c7fc9fcfc44a62d77f2c13108a2d58c33b0017eec10.js?body=1" data-turbolinks-track="true"></script>
<script src="/assets/action_cable/subscription.self-63bb8fcaf3e18e3bb4b849c831819921afe52d3e48e77f3c0d2d50fdf43a9b0c.js?body=1" data-turbolinks-track="true"></script>
<script src="/assets/action_cable/consumer.self-d0a6518de32602abb57c66be88b1fd0445527abfb6d8fad3a0be0c59eb6b7fd1.js?body=1" data-turbolinks-track="true"></script>
<script src="/assets/cable.self-877aef30ae1b040ab8a3aba4e3e309a11d7f2612f44dde450b5c157aa5f95c05.js?body=1" data-turbolinks-track="true"></script>
<script src="/assets/companies.self-877aef30ae1b040ab8a3aba4e3e309a11d7f2612f44dde450b5c157aa5f95c05.js?body=1" data-turbolinks-track="true"></script>
<script src="/assets/application.self-b89234cf2659d7fedea75bca0b8d231ad7dfc2f3f57fcbaf5f44ed9dc384137b.js?body=1" data-turbolinks-track="true"></script>
  </head>

  <body>
    <h1>Editing Company</h1>

<form class="edit_company" id="edit_company_2" action="/companies/2" accept-charset="UTF-8" method="post"><input name="utf8" type="hidden" value="&#x2713;" /><input type="hidden" name="_method" value="patch" /><input type="hidden" name="authenticity_token" value="1HxW3jw7tINiIbD8X25t15MukXOFV4g6sXD666f1oCt2BqGlZ1xGPHZ3w9NHuoISBFCynd63mETK8MHETZCTYw==" />

  <div class="field">
    <label for="company_name">Name</label>
    <input type="text" value="asdf" name="company[name]" id="company_name" />
  </div>

  <div class="actions">
    <input type="submit" name="commit" value="Update company" data-disable-with="Update company" />
  </div>
</form>

<a href="/companies/2">Show</a> |
<a href="/companies">Back</a>

  </body>
</html>
```

The important lines are:

```
<meta name="csrf-token" content="R/+8o7qCIsdpxYv0X/fxuZg8Tq5At6st3wmNM5vHgr7qdo29rBsTIE4mtxOFbGYTfcXTTI+Da88GirnPQUDkKQ==" />
```

and

```
<input type="hidden" name="authenticity_token" value="1HxW3jw7tINiIbD8X25t15MukXOFV4g6sXD666f1oCt2BqGlZ1xGPHZ3w9NHuoISBFCynd63mETK8MHETZCTYw==" />
```

Note that the values don't match.  They do with Rails 4.x releases.

**Comment by maclover7** [comment]
Not sure about this, but could be related to #22275

**Comment by rubys** [comment]
@maclover good catch!  It would be OK for them to intentionally not match, but only if the authenticity token in the form "overrode" the csrf token in the meta tag.

To put it another way, what now is implemented is indeed a per form authentication token on the client side, but any attempt to use that token will be rejected as the server is specifically looking for the csrf token that was placed in the metadata.

**Comment by rafaelfranca** [comment]
Let me understand better your problem, when you submit the form are you using the form token or the meta token?

They intentionally don't match but it is because the form token have the information about the action and the meta doesn't. But both should be valid.

**Comment by rubys** [comment]
I'm still researching what releases prior to 5.0 did, but I can say that with 5.0 any attempt to submit using the form token is rejected.  That clearly is a bug.  Substituting the CSRF token works, at least with 5.0.  I've [temporarily added code to prefer the CSRF token](https://github.com/rubys/gorp/blob/3082e993ae1e25eecb1565ad85be90f078ea3ec0/lib/gorp/net.rb#L241), but I'm likely to revert it.  But you can see the difference (at least until these jobs run again): with [form token](http://intertwingly.net/projects/AWDwR4/checkdepot-223/section-10.3.html#cmd4) vs [csrf token](http://intertwingly.net/projects/AWDwR4/checkdepot/section-10.3.html#cmd4). 

I now see cases where the tokens differed in prior releases, and in the cases I've looked at so far, either token works.  Running more tests.

**Comment by rubys** [comment]
OK, here is what I'm seeing.

With 4.0 and 4.1, CSRF and form tokens are constant within a session, and always match one another.

With 4.2, CSRF and form tokens are different, both from each other and on every request.  Both work.

With 5.0, CSRF and form tokens are different, both from each other and on every request, but only the CSRF token works.

**Comment by rafaelfranca** [comment]
To the form token work in Rails 5 the request's action and request's method need to be the same as the form's action and form's method.

**Comment by rubys** [comment]
@rafaelfranca can you explain what I should be doing differently in the following scenario:

http://intertwingly.net/projects/AWDwR4/checkdepot-223/section-10.3.html#cmd3

In the above link, you can see the form.  Based on that form, I send an HTTP POST request with the following values urlencoded:

    _method=delete&authenticity_token=ybobEK1Hiov0cpTRHypFmP/0P6r2TnRHUd2uzOxXJ4XdLYmnG1oyIx36xIOH4LC5yp2sTAKjW3v/eRl4vZHuEg==

**Comment by rafaelfranca** [comment]
Ok, I found the bug! \o/ It only happens with `delete` method in a `button_to`. In this line we are sending `post` instead of `delete` to the `token_tag` helper https://github.com/rails/rails/pull/22275/files#diff-26e33d6e883deb07332ac9c1922eadc0R310.

I'll work in a fix.

**Comment by rubys** [comment]
Cool!

My tracing and workaround have served their purpose. I'm now turning them both off by default so we can immediately see your future fix working :-)

If needed in the future, I can reenable either or both of them again.
