### ISSUE TITLE
accepts_nested_attributes_for  in STI

### ISSUE THREAD

**Issue by jbmyid** [rails/rails#23538]
I am facing Issue when trying to destroy using nested attribute for STI classes in rails 4. eg:

```
class A < ActiveRecord::Base
end

class B < A
  has_many :options
  accepts_nested_attributes_for :options, :allow_destroy => true
end
```
When I try to delete the options its not being deleted event it is has marked_for_destruction? as true, but the option is not being deleted.

I have all correct paramaters accessible like `:id, :name, :_destroy.`

I made it working by moving nested attributes code and has_many to base class.

```
class A < ActiveRecord::Base
  has_many :options
  accepts_nested_attributes_for :options, :allow_destroy => true
end

class B < A

end
```
I think its issue with STI in rails same as you can not update the type of the STI class object(there is workaround fix for that).

**Comment by vipulnsward** [comment]
Thanks for reporting @jbmyid. Can you create a reproduction script using this sample script - https://github.com/rails/rails/blob/master/guides/bug_report_templates/active_record_gem.rb

**Comment by pauloancheta** [comment]
It passes with this test case. Let me know if there is something I can improve with the test.
https://gist.github.com/pauloancheta/fcba7ca7417758a4e11c

**Comment by jbmyid** [comment]
I have also tried with script but could not reproduce it there.
But in my current project its the issue. rails 4.2.4

**Comment by meinac** [comment]
I can confirm that this is working with Active Record `4.2.6` and also with `4.2.4`. I think the issue is project specific, it's not about Rails.

**Comment by jbmyid** [comment]
Yes looks like it is project specific but still couldn't figure it out.

**Comment by fringify** [comment]
I think test provided by @pauloancheta isn't STI just normal association
