### ISSUE TITLE
Guide "Rails Routing from the Outside In" - :namespace

### ISSUE THREAD

**Issue by xzo** [rails/rails#23550]
http://edgeguides.rubyonrails.org/routing.html#dynamic-segments
> You can't use _:namespace_ or :module with a :controller path segment. If you need to do this then use a constraint on :controller that matches the namespace you require

What does “:namespace” mean here?

**Comment by maclover7** [comment]
This is referring to namespaces and modules that can be used to define routes. See [here](http://edgeguides.rubyonrails.org/routing.html#controller-namespaces-and-routing) for more info.

**Comment by xzo** [comment]
@maclover7 colon before :namespace is confusing

**Comment by mparodi** [comment]
Guys, this is not working. Was it deprecated or something? This is the route I need:

```ruby
 match '/:controller(.:format)', controller: /[^\/]+\/[^\/]+/, action: "handle", via: [:get, :post]
```

This is the error I'm getting: http://i.imgur.com/JX5hA10.png. As you can see, the path matches on the debug input.

Is it a bug? What am I doing wrong?
