### ISSUE TITLE
unprepared_statement doesn't work on Arel::Nodes::TableAlias

### ISSUE THREAD

**Issue by ClayShentrup** [rails/rails#23555]
I don't know whether this is intended or constitutes a bug. Trivial example using an enum called `gap`.

```ruby
PatientMeasureStatus.gap.to_sql
```

```sql
SELECT "patient_measure_statuses".* FROM "patient_measure_statuses"
WHERE "patient_measure_statuses"."status" = 1
```

Whereas:

```ruby
PatientMeasureStatus.gap.as('gap').to_sql
```

```sql
(SELECT "patient_measure_statuses".* FROM "patient_measure_statuses"
WHERE "patient_measure_statuses"."status" = $1) gap
```

Now, I use `unprepared_statement` in an attempt to get that latter statement as a SQL string that I can modify and execute.

```ruby
PatientMeasureStatus.connection.unprepared_statement do
  PatientMeasureStatus.gap.as('gap').to_sql
end
```

I get the exact same SQL, with the `$1` not replaced.

Thank you.

**Comment by vipulnsward** [comment]
Hi @ClayShentrup can you create an executable script based on https://github.com/rails/rails/blob/master/guides/bug_report_templates/active_record_gem.rb to help reproduce this assertion?

**Comment by matthewd** [comment]
> I don't know whether this is intended or constitutes a bug

It's neither; Arel is private API, and you're consequently calling two very different `to_sql` methods.
