### ISSUE TITLE
Incorrect error message with accepts_nested_attributes_for / has_many

### ISSUE THREAD

**Issue by rthbound** [rails/rails#23568]
Proof I have accepts_nested_attributes_for configured properly:
```ruby
Dashboard.new(measures_attributes: [{name_of_measure: "Height"}])
#=> #<Dashboard id: nil, guid: nil, position: nil, display_label: nil, created_at: nil, updated_at: nil>
```
The incorrect error message:
```ruby
Dashboard.new(measures_attributes: [{stinky: "yup"}])
#=> ActiveModel::UnknownAttributeError: unknown attribute 'measures_attributes' for Dashboard.
```
What the error should be:
```ruby
Dashboard.new.measures_attributes = [{stinky: "yup"}]
#=> ActiveModel::UnknownAttributeError: unknown attribute 'stinky' for Measure.
```

**Comment by maclover7** [comment]
Would you be willing to work on a PR for this?

**Comment by rthbound** [comment]
Willing, I was just about to dig into the code...

**Comment by maclover7** [comment]
Awesome!

**Comment by rthbound** [comment]
@maclover7 : The reason this is happening appears to have to do with this line: https://github.com/rails/rails/blob/master/activerecord/lib/active_record/attribute_assignment.rb#L37

```ruby
def _assign_attribute(k, v) # :nodoc:
  super
rescue ActiveModel::UnknownAttributeError => e
  raise UnknownAttributeError.new(self, k) #here
end
```

From there, `e` is still the expected error:
> `#<ActiveModel::UnknownAttributeError: unknown attribute 'stinky' for Measure.>`

However, the error re-raised by `UnknownAttributeError.new(self, k)` is the misleading message noted in this issue:
> `#<ActiveModel::UnknownAttributeError: unknown attribute 'measures_attributes' for Dashboard.>`

The re-raising behavior appears to have been introduced in #19077. I'm not sure there's a reason to rescue and re-raise, stripping information along the way. Removing the behavior doesn't appear to break any tests for me, so I'll submit a PR () to remove those two lines.

**Comment by rthbound** [comment]
Come think of it, if we don't need to rescue and re-raise, there's no reason to redefine that method at all.
