### ISSUE TITLE
Long arguments to rails routes are not respected

### ISSUE THREAD

**Issue by vipulnsward** [rails/rails#23561]
```
rails routes --c controller_name
```
works, but

```
rails routes --controller controller_name
```
results in `invalid option: --controller=cart`

Would be probably a good idea to scan other rake tasks support long options.

**Comment by kaspth** [comment]
Surprised we didn't have a test for it in https://github.com/rails/rails/commit/8a436fdd98c63cc0a7a6d2c642c18d33421dc6ad 😁

r? @vipulnsward

**Comment by maclover7** [comment]
I have a fix for this in a plain OptionParse program, but when I introduce it into Rails it breaks for some reason... investigating.

**Comment by vipulnsward** [comment]
@maclover7 I have been working on this as well. The options in the rake task are not being parsed as they should on normal ruby programs.

**Comment by kaspth** [comment]
What does `ARGV` look like when we reach https://github.com/rails/rails/blob/3b693dfb9384d15fcd3bbaa5f47da69019b2bf51/railties/lib/rails/tasks/routes.rake#L30? That's how Rake runs itself, so that might interfere :smile:
