### ISSUE TITLE
Using unscoped on an STI base class breaks queries for subclass entities

### ISSUE THREAD

**Issue by dougbarth** [rails/rails#23576]
We hit an interesting gotcha with STI models where one queries the base model using the `unscoped` relation.

The problem is that any queries for subclass models will not include the `type` condition if those queries occur in a stack frame that is beneath the call to `unscoped`.

Here's a gist with a test case that recreates the issue: https://gist.github.com/dougbarth/44eb4adc28f8d6026322

To explain the problem a bit more clearly, consider the case where we have the following STI hierarchy: `SubPost < Post < ActiveRecord::Base`. `SubPost` includes an `after_save` callback that queries the database for `SubPost` records

Code like this will work as expected:

``` ruby
class SubPost < Post
  after_save :query_subposts

  def query_subposts
    SubPost.all
  end
end

post = Post.unscoped.find(some_id)  # This ID references a SubPost row
post.touch
post.save!    # query_subposts callback includes a condition on type = 'SubPost'
```

However, if we refactor the logic to move the find and modifying logic onto the `Post` class, the callback's query drops the `type` condition.

``` ruby
class Post
  def self.find_and_touch(some_id)
    p = find(some_id)
    p.touch
    p.save!   # query_subposts skips the type condition
  end
end

Post.unscoped.find_and_touch(some_id) # Loading a SubPost row
```

We're happy to try to fix this, but we wanted to get some feedback on whether code like this should work. From our perspective, having callback code that dramatically changes its query based on the calling frame is very surprising.

/cc @DavidRagone

**Comment by sevaorlov** [comment]
Simpler reproduction script, that shows the problem better, although hides business rationale behind it.

```ruby
begin
  require 'bundler/inline'
rescue LoadError => e
  $stderr.puts 'Bundler version 1.10 or later is required. Please update your Bundler'
  raise e
end

gemfile(true) do
  source 'https://rubygems.org'
  gem 'rails', github: 'rails/rails'
  gem 'sqlite3'
end

require 'active_record'
require 'minitest/autorun'
require 'logger'

# This connection will do for database-independent bug reports.
ActiveRecord::Base.establish_connection(adapter: 'sqlite3', database: ':memory:')
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :posts, force: true  do |t|
    t.string :type
  end
end

class Post < ActiveRecord::Base
  def self.all_subposts
    SubPost.all
  end
end

class SubPost < Post
end

class BugTest < Minitest::Test
  def test_sti_query_in_a_scope
    # require 'byebug'
    # byebug
    query_sql = Post.unscoped.all_subposts.to_sql
    p query_sql # "SELECT \"posts\".* FROM \"posts\""

    unless query_sql.include?(%|"posts"."type" IN ('SubPost')|)
      raise "Expected query to scope by type: #{query_sql}"
    end
  end
end
```

This happens because calling `all_subposts` method on an unscoped Post is implemented through `method_missing` and is wrapped in `scoping`, which takes scope from `Post` model.
https://github.com/rails/rails/blob/8afea8ebe715ee5c94e64d4f45a742dfe4d514fa/activerecord/lib/active_record/relation/delegation.rb#L88

I actually do not think it is worth spending time on this problem. It is better to do `find_and_modify` in some form or service object, than in an unscoped model class method (`Post.unscoped.find_and_modify`), or even just do it without `unscoped`, with just `Post.find_and_modify`.

**Comment by DavidRagone** [comment]
@jonabrams didn't we just run into this again last week?

**Comment by kamipo** [comment]
#29199 will fix the issue.
