### ISSUE TITLE
send_data w content_type gets charset appended.

### ISSUE THREAD

**Issue by troelskn** [rails/rails#23573]
I have the following code (simplified):

```
class DocumentsController < ApplicationController
  # GET /documents/:id
  def download
    document = Document.find(params[:id])
    send_data document.to_io, content_type: 'application/pdf', filename: "document-#{document.id}.pdf"
  end
end
```

And this test case:

```
class DocumentsControllerTest < ActionDispatch::IntegrationTest
  test "can download a document" do
    get document_url(documents(:one))
    assert_response :success
    assert_equal 'application/pdf', headers['Content-Type']
  end
end
```

In Rails `5.0.0beta1` it passed, but now (`5.0.0beta2`) it fails with:

```
Failure:
DocumentsControllerTest#test_can_download_a_document:
--- expected
+++ actual
@@ -1 +1 @@
-"application/pdf"
+"application/pdf; charset=utf-8"
```

Since the document is binary data, adding charset information to the content-type is wrong.

**Comment by maclover7** [comment]
Can you provide a sample application or create an executable test script using one of the templates [here](https://github.com/rails/rails/tree/master/guides/bug_report_templates), that would demonstrate the problem you are seeing?

**Comment by troelskn** [comment]
I should note that passing `charset: 'binary'` resolves the issue, so the main problem is that behaviour changed between versions. (And that the default behaviour is now a bit strange)

**Comment by vipulnsward** [comment]
@troelskn what does setting `type` instead of `content_type` do?
Ref: https://github.com/vipulnsward/rails/blob/69009f4473637a44ade26d954ef5ddea6ff903f2/actionpack/lib/action_controller/metal/data_streaming.rb#L54-L54

**Comment by troelskn** [comment]
Here's a test case: https://github.com/troelskn/rails-issue-23573

**Comment by troelskn** [comment]
@vipulnsward yes, that works as expected.

**Comment by maclover7** [comment]
Based on what was [posted above](https://github.com/rails/rails/blob/master/actionpack/lib/action_controller/metal/data_streaming.rb#L54), it looks like using `content_type` instead of `type` is unsupported. Feel free to submit a documentation PR if you think anything needs updating.
