### ISSUE TITLE
Rails 4.2.1: db:migrate creating duplicate definitions.

### ISSUE THREAD

**Issue by marvdm** [rails/rails#23588]
Context: Multi-tenant app (implementation based on RailsCasts' "Multitenancy with PostgreSQL"); Rails 4.2.x; Ruby 2.2.

Running rake db:migrate is now behaving differently after upgrading some gems: it's now dumping the schema definition with duplicate entries:
![schema](https://cloud.githubusercontent.com/assets/228739/12941622/3f2741fa-d00f-11e5-9453-f70c1bf3f516.png)

Running rake db:schema:dump fixes the schema.rb.

Related gems that got updated:
- rails (4.2.1) to (4.2.5.1)
- rake (10.4.2) to rake (10.5.0)
- pg (0.18.2) to (0.18.3)

I'm using rbenv 1.0.0, if that's relevant, and here is a trace of db:migrate:
![db migrate trace](https://cloud.githubusercontent.com/assets/228739/12941914/fd4b1ee8-d011-11e5-89b5-e55633f2db47.png)

**Comment by marvdm** [comment]
Sorry, it's apparently not a bug.

The issue happens when a migration does not complete the creation of the tables on a new schema due to an error so when db:migrate is executed, its dump is based on that schema's incomplete state. Then the missing tables' definitions are duplicated in schema.rb.

**Comment by kirykr** [comment]
@marvdm i ran into the same issue after upgrading rails 4 to 5.x. Just wonder how to solve this problem. Thanks

**Comment by marvdm** [comment]
@kirykr As far as I can remember, this is what you need to look for:

> Sorry, it's apparently not a bug.
> 
> The issue happens when a migration does not complete the creation of the tables on a new schema due to an error so when db:migrate is executed, its dump is based on that schema's incomplete state. Then the missing tables' definitions are duplicated in schema.rb.

**Comment by kirykr** [comment]
@marvdm I have read that. but i don't understand. 
> its dump is based on that schema's incomplete state.

I even drop the entire database, create a new database, and rerun migration. The migration ran successfully but the duplicates in the schema are still reoccurred.
