### ISSUE TITLE
rake db:structure:load silently fails if dependencies aren't installed

### ISSUE THREAD

**Issue by thesmart** [rails/rails#23585]
My team runs PostgreSQL, and with it comes shell utilities such as psql, pg_dump and pg_restore.  We ran into an silent failure where `rake db:structure:load` is silently failing but appears to succeed.  This happens because calls to `ActiveRecord::Tasks::DatabaseTasks.structure_load` invoke `PostgreSQLDatabaseTasks::structure_load` which calls `Kernel.system("psql -q -f #{Shellwords.escape(filename)} #{configuration['database']}")`.

The scrypt `psql` wasn't included in our PATH environment variable, and this failed the above `Kernel.system` call.  However The exit status of Kernel.system is not checked by `ActiveRecord::Tasks::DatabaseTasks.structure_load`, so everything appeared to be A-OK.

A migration system should HARD FAIL when a dependency is missing or a command fails.

**Comment by diego-silva** [comment]
It should already be fixed in 4.2.5: #22000

https://github.com/rails/rails/blame/v4.2.5/activerecord/lib/active_record/tasks/postgresql_database_tasks.rb#L90

**Comment by thesmart** [comment]
@diego-silva Thanks for the quick reply.  I believe there is still a silent error in this code: https://github.com/rails/rails/issues/23818

**Comment by futbolpal** [comment]
@diego-silva I'm curious why psql is leveraged as opposed to something like "ActiveRecord::Base.connection.execute(IO.read("db/structure.sql"))".

Would this remove the psql dependency?

Thanks!

**Comment by thesmart** [comment]
@futbolpal No, output of `structure.sql` requires `pg_dump`.  Personally I much prefer using a SQL representation of code than a ruby one, but I know that's not the rails way. 🎱
