### ISSUE TITLE
AC::Parameters `transform_keys` does not work as a substitute for deprecated `symbolize_keys`

### ISSUE THREAD

**Issue by why-el** [rails/rails#23599]
Hey,

I am in the middle of an update to Rails 5. In my app I am passing params to a path helper and I needed to call `symbolize_keys` (since now they keys must be symbols, per https://github.com/rails/rails/issues/20353). Since `symbolize_keys` is deprecated, I figured `transform_keys` would be perfect substitute, but this does not work for `AC::Parameters` because it is still relaying on a `HashWithIndifferentAccess` instance under the hood. 

Is any of this intended behavior? I understand it might be tricky, since moving away from `HashWithIndifferentAccess` would be a far bigger change than simply moving away from `Hash` like `AC::Parameters` already did. However, and since the initial reasoning for the move away was security issues, wouldn't the same apply to `HashWithIndifferentAccess`? Or are we operating under the assumption that the underlying `HashWithIndifferentAccess` should be private state of `params`? 

Reproduction script:

```
begin
  require 'bundler/inline'
rescue LoadError => e
  $stderr.puts 'Bundler version 1.10 or later is required. Please update your Bundler'
  raise e
end

gemfile(true) do
  source 'https://rubygems.org'
  gem 'rails', github: 'rails/rails'
  gem 'arel', github: 'rails/arel'
  gem 'rack', github: 'rack/rack'
  gem 'sprockets', github: 'rails/sprockets'
  gem 'sprockets-rails', github: 'rails/sprockets-rails'
  gem 'sass-rails', github: 'rails/sass-rails'
end

require 'action_controller/railtie'

class TestApp < Rails::Application
  config.root = File.dirname(__FILE__)
  config.logger = Logger.new($stdout)
  Rails.logger  = config.logger
end


require 'minitest/autorun'
require 'rack/test'

class BugTest < Minitest::Test
  include Rack::Test::Methods

  def test_params_transform_keys
    # Works for a regular hash.
    params = {"a" => "b"}
    assert params.transform_keys(&:to_sym).keys.first.is_a? Symbol

    # Does not work for AC::Params.
    params = ActionController::Parameters.new("a" => "b")
    assert params.transform_keys(&:to_sym).keys.first.is_a? Symbol
  end

  private
    def app
      Rails.application
    end
end
```

**Comment by rafaelfranca** [comment]
If you need the hash access the Hash directly. `params.to_a.symbolize_keys `. Params is not an Hash anymore.

**Comment by rafaelfranca** [comment]
> Or are we operating under the assumption that the underlying HashWithIndifferentAccess should be private state of params?

Yes. That is the correct assumption to do.

**Comment by why-el** [comment]
Ok, great. Thanks Rafael.
