### ISSUE TITLE
Provide @response.parsed_body to work together with post ..., as: :json for testing

### ISSUE THREAD

**Issue by dhh** [rails/rails#23594]
If you post JSON in testing, it's likely you want to test JSON coming back too. Providing @response.parsed_body will save everyone from having to do `JSON.parse @response.body` over and over again.

**Comment by maclover7** [comment]
Opened #23595 to solve this. :)

**Comment by kaspth** [comment]
Asked @maclover7 to let me take over in #23597, thanks!
