### ISSUE TITLE
Action View Digests for wildcard declarations aren't deterministic

### ISSUE THREAD

**Issue by dhh** [rails/rails#23592]
When you declare a wildcard template dependency like `Template Dependency: events/*`, the digest differs from machine to machine. This suggests that something in the wildcard dependency walker is non-deterministic. Basically, it means that each app server generates a different digest for the same dependency tree, which renders the feature broken, as each server creates their own cache for the same content.

**Comment by kaspth** [comment]
Referencing the original issue where this was reported here: https://github.com/rails/rails/pull/20904#issuecomment-182427689.

Looking into it 👍

**Comment by kaspth** [comment]
https://github.com/rails/rails/pull/23604#issuecomment-184295355 😁
