### ISSUE TITLE
Rails 5 beta2 link_to with post or put do not work

### ISSUE THREAD

**Issue by lohqua** [rails/rails#23602]
resources :smiley_images do member do ... post :random_add_to_default end end

which produces this route: random_add_to_default_smiley_image POST /smiley_images/:id/random_add_to_default(.:format)

<%= link_to 'Random smiley collection', random_add_to_default_smiley_image_path(@sc.id), method: :post, class: 'link' %>

Generates: <a class="link" rel="nofollow" data-method="post" href="/smiley_images/1/random_add_to_default">Random smiley collection</a>

Which produces:

ActionController::RoutingError (No route matches [GET] "/smiley_images/1/random_add_to_default")

I have <%= javascript_include_tag 'application' %> no turbolinks since it blows up on multiple layouts and themes, at least it did in Rails 4.

YES, I HAVE THE JQUERY_UJS file loaded.

`  <script src="/assets/jquery.self-c64a74367bda6ef8b860f19e74df08927ca99d2be2ac934e9e92d5fd361e0da4.js?body=1"></script>
<script src="/assets/jquery_ujs.self-d602bdfe68ffc63b9f9cc512872aa3cfff046228a0a36e90dd476e8ef54c1b09.js?body=1"></script>`

No, button_to is not an option in the few cases I need links and post and put not working in link_to is an actual bug.

I am not sure what else is needed to hunt down this bug.

**Comment by rafaelfranca** [comment]
It is missing `remote: true`. Without that the browser will use the default link handler that is a GET request.

**Comment by lohqua** [comment]
No, the link doesn't need a remote attribute because it is not an ajax request.

Please note that this is a working app in Rails 4.

**Comment by lohqua** [comment]
Why are you closing valid bugs?????

What part of these link_to's worked in Rails 4 is eluding you?

**Comment by rafaelfranca** [comment]
Yes. It is. There is no way to a link do a POST request if it is not using Ajax.

**Comment by lohqua** [comment]
Then explain why the above works in Rails 4?

**Comment by rafaelfranca** [comment]
That is what I'm going to see right now :smile:

**Comment by rafaelfranca** [comment]
Could you confirm that there is no JavaScript error in your page?

**Comment by rafaelfranca** [comment]
I just tested this behavior in a new Rails 5.0.0.beta2 application and could not reproduce. The request was made as POST instead of GET as you expect.

**Comment by lohqua** [comment]
No JS errors.

**Comment by rafaelfranca** [comment]
Can you please provide a sample application that reproduces the error?

**Comment by rafaelfranca** [comment]
Yes. I didn't. My call was `<%= link_to 'New User', new_user_path, method: :post %>`

**Comment by lohqua** [comment]
Okay, I will try it with a sample application.

**Comment by lohqua** [comment]
That is just weird and makes no sense. 

It worked in the test application.

I started the Rails 5 migration in my app by starting with a clean `rails new`, removing turbolinks, adding routes and mailer config and then just moving files over.  I am not sure what is off. 

It loads jquery v1.12.0 and the jquery_ujs doesn't have a version but it is loaded.

**Comment by amed** [comment]
Forgot to load `jquery_ujs` in Application.js 🤓
