### ISSUE TITLE
Rails 5.0.0beta2 When creating a new app spring is not found.

### ISSUE THREAD

**Issue by lohqua** [rails/rails#23601]
No, I am not using RVM or any other pointless and worthless version manager.

I have ruby installed at /home/me/sdk/.

```
run  bundle exec spring binstub --all
bundler: command not found: spring
Install missing gem executables with `bundle install
```

running `bundle exec /home/me/sdk/ruby/binspring binstub --all` works. I am not sure if it is a rails issue or bundler.

**Comment by rafaelfranca** [comment]
Does `bundle exec spring binstub --all` works?

**Comment by jeremy** [comment]
Sounds like spring isn't in your Gemfile so bundler doesn't know about it. If you're using spring installed as a system gem, you don't need to bundle exec it.
