### ISSUE TITLE
Model.limit(1).first orders on primary key, but Model.limit(1).last does not

### ISSUE THREAD

**Issue by brchristian** [rails/rails#23607]
I noticed today that in some ways the ActiveRecord methods`first` and `last` are not fully symmetrical.

For instance, on their own they produce parallel queries:

```
Unit.first
  > SELECT  "units".* FROM "units" ORDER BY "units"."id" ASC LIMIT $1  [["LIMIT", 1]]

Unit.last
  > SELECT  "units".* FROM "units" ORDER BY "units"."id" DESC LIMIT $1  [["LIMIT", 1]]
```

But chain a `limit` relation, and they no longer behave the same:

```
Unit.limit(1).first
  > SELECT  "units".* FROM "units" ORDER BY "units"."id" ASC LIMIT $1  [["LIMIT", 1]]

Unit.limit(1).last
  > SELECT  "units".* FROM "units" LIMIT $1  [["LIMIT", 1]]
```

This results in the fact that:
`Unit.limit(1).first == Unit.first`
but:
`Unit.limit(1).last != Unit.last`.

**Comment by maclover7** [comment]
Can you create an executable test script using one of the templates [here](https://github.com/rails/rails/tree/master/guides/bug_report_templates), that would demonstrate the problem you are seeing?

**Comment by brchristian** [comment]
@maclover7 No problem. I'm new to getting the test suite to work, so I don't know exactly what I'm doing yet, but the test would be very simple, like this: https://gist.github.com/brchristian/93c58db70aa10fa0bdca#file-limit_last_test-rb-L35-L42

**Comment by hackerkid** [comment]
When I ran the script I got the following output

```
Finished in 0.000918s, 0.0000 runs/s, 0.0000 assertions/s.

0 runs, 0 assertions, 0 failures, 0 errors, 0 skips
```

Why is it showing 0 assertions? I am sorry if i am missing something. I am new to rails testing.

**Comment by brchristian** [comment]
@maclover7 @hackerkid There has been a recent refactor of some of this code in the `master` branch in https://github.com/rails/rails/commit/b67991614349d68e0d8ad489c8c84c3254ac847b, but it appears that this issue persists.

The critical line appears to be in `def find_last(limit)`, [here](https://github.com/rails/rails/blob/master/activerecord/lib/active_record/relation/finder_methods.rb#L575-L577):

    def find_last(limit)
      limit ? to_a.last(limit) : to_a.last
    end

My assessment is that it's failing to apply the default ordering. The `first(limit)` method will apply the default scope [here](https://github.com/rails/rails/blob/master/activerecord/lib/active_record/relation/finder_methods.rb#L554-L558):

    relation = if order_values.empty? && primary_key
                 order(arel_attribute(primary_key).asc)
               else
                 self
               end

I have created a PR that I believe addresses this at https://github.com/rails/rails/pull/23786.

**Comment by eileencodes** [comment]
cc/ @bogdan looks like there are some new issues with your changes to last. Can you take a look?

**Comment by eileencodes** [comment]
Sorry @bogdan I didn't realize this was an issue previous to your changes.

**Comment by bogdan** [comment]
@eileencodes I saw this issue when worked on a patch: it is tested so my patch left this behavior as is.

 I think this behavior is right: `relation.last` tries to act in the same way as `relation.to_a.last`. I like this concept it feels convenient. So, I consider any step away from that concept as bad one.

**Comment by brchristian** [comment]
@maclover7 @hackerkid @eileencodes @bogdan 

(+ @matthewd because https://github.com/rails/rails/pull/23794 touched this)

If the intention is for `relation.last` to act like `relation.to_a.last` (which is okay IMO, and consistent with the [existing tests](https://github.com/rails/rails/blob/master/activerecord/test/cases/finder_test.rb#L549-L551)), then actually the problem would seem to be with `relation.first` failing to act like `relation.to_a.first`.

Observe:

    Value.limit(1).to_a.first
     Value Load (0.4ms)  SELECT  "values".* FROM "values" LIMIT $1  [["LIMIT", 1]]

    Value.limit(1).first
     Value Load (0.4ms)  SELECT  "values".* FROM "values" ORDER BY "values"."id" ASC LIMIT $1  [["LIMIT", 1]]

The SQL is _not_ the same! The records returned with _usually_ be the same, but only because most SQL databases will return records sorted by primary key by default.

This is a very subtle issue, because it will only come up in Postgres, I believe, which does _not_ enforce primary key ordering by default. And Postgres isn't consistent, I don't think, in how it does or doesn't order records. As a result I'm not 100% sure how to reproduce this issue in a test case.

There should be a way to make a test that shows that

    assert_equal comments.limit(2).to_a.first(2), comments.limit(2).first(2)

fails (or at least _can_ fail) in Postgres. 

I believe the simplest solution is removing [these lines that add primary_key ordering to the `find_nth_with_limit` method](https://github.com/rails/rails/blob/master/activerecord/lib/active_record/relation/finder_methods.rb#L554-L558). Note that doing so is against some of the spirit of https://github.com/rails/rails/commit/cafe31a078276dbf941bd8b30f0caddc878c0830 -- however this seems necessary if we do indeed want `comments.limit(2).to_a.first(2)` to produce the same behavior as `comments.limit(2).first(2)`.

But first: how do we make a test that uses Postgres's ability/tendency not to return records ordered by primary key? I am open to ideas here!

**Comment by brchristian** [comment]
Update: Here is a test (I have added it locally to `activerecord/test/cases/finder_test.rb`) that shows the issue.

	  def test_first_on_relation_with_limit
	    topics(:first).touch # PostgreSQL changes the default order if no order clause is used
	    assert_equal Topic.limit(2).to_a.first, Topic.limit(2).first
	    assert_equal Topic.limit(2).to_a.first(2), Topic.limit(2).first(2)
	    assert_equal Topic.limit(2).to_a.first(3), Topic.limit(2).first(3)
	  end

The first two assertions fail in Postgres. The third assertion fails in all SQL dbs.

Note that if the `last` method is used rather than the `first` method, all of these assertions do hold.

**Comment by mechanicles** [comment]
I have sent PR for this fix here #24000

**Comment by schneems** [comment]
The attached PR is closed. Can you tell me if this issue needs to stay open?

**Comment by brchristian** [comment]
Hi @schneems, it is still the case that this issue exists as of the most recent `master` commit. My PR is https://github.com/rails/rails/pull/24131 originally submitted on 3/9/16, I believe it was reviewed on 3/11/16. On 10/3/16 I was asked to rebase to current master, which I did, but it was never merged. The PR is still open. If you’d like to move it towards merging, I’m happy to rebase again.

**Comment by brchristian** [comment]
@schneems Btw, just rebased to the current `master` 👍
