### ISSUE TITLE
Ambiguity between `Array#first` and `ActiveRecord#first`

### ISSUE THREAD

**Issue by brchristian** [rails/rails#23603]
I'm using Postgres, which does not order my query data by primary key by default, so for instance:

	Unit.pluck(:id)
	   (0.5ms)  SELECT "units"."id" FROM "units"
	=> [5, 6, 7, 8, 9, 10, 2, 3, 12, 4, 1, 13]

This has led me to discover something very surprising:

	a = Unit.limit(1)
	a = a.first
	b = Unit.limit(1).first
	a == b
	=>  false

Whoa!

This was very surprising to me.

The line `a = a.first` is ambiguous -- the user could be trying to get the first element of the ActiveRecord Relation, _or_ are they could be trying to chain that relation. Rails appears to default to using the Array method of `first`, and not the ActiveRecord method `first`.

Is this the desired behavior?

Note that in other cases, Rails has no problem "going back" and revising a Relation, even if it means making a second query:

	c = Unit.limit(1)
	c = c.where(id: 3) # second SQL query is executed that overrides the first one
	d = Unit.limit(1).where(id: 3)
	c == d
	=>  true

So, going back to the `a == b` example, is that the desired behavior?

If not, we can potentially rethink which of the `#first` methods is being called there.

If so, we might want to articulate in the documentation the basis on which Rails will resolve these ambiguous `#first` calls.

Note that all of this would be moot if `Unit.limit` defaulted to ordering by the primary key, which I actually think might be a good idea.

**Comment by rafaelfranca** [comment]
Yes. It is, but it only happen because you are calling `Unit.limit(1)` in the console and it does print the result of that query. That loads the relation and when you call `first` in the relation it will use `Array#first`. That doesn't happen in production environment.

**Comment by brchristian** [comment]
:+1: Makes sense. Thanks!
