### ISSUE TITLE
Mailer generator doesn't generate view in Rails 5 in API mode

### ISSUE THREAD

**Issue by thecodethinker** [rails/rails#23617]
I'm not sure if this was intended but it does seem odd. 
If you're app was made with the `--api` flag then the mailer generator doesn't make any views. It probably should because even in an API only backend the emails being sent should have html. 
It seems a little odd to have the mailer active by default but have the generator not make any views.

**Comment by diego-silva** [comment]
One could use the option `-e=erb` or `--template-engine=erb`

But it might make sense to have erb as default and always generate views for mailers even in api mode...

**Comment by dhh** [comment]
This is not intended. The mailer should definitely generate a view even in API mode.
