### ISSUE TITLE
counter_cache on has_many associations is broken in rails 4.1 and 4.2

### ISSUE THREAD

**Issue by datanoise** [rails/rails#23615]
``` ruby
gem 'activerecord', '4.2.5.1'
require 'active_record'
require 'minitest/autorun'
require 'logger'

ActiveRecord::Base.establish_connection(adapter: 'sqlite3', database: ':memory:')
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :posts, force: true do |t|
    t.integer :comments_count, default: 0
  end

  create_table :comments, force: true do |t|
    t.integer :post_id
  end
end

class Post < ActiveRecord::Base
  has_many :comments, counter_cache: true
end

class Comment < ActiveRecord::Base
  belongs_to :post
end

class BugTest < Minitest::Test
  def test_association_stuff
    post = Post.create!
    assert_equal 0, post.comments_count

    post.comments << Comment.create!
    assert_equal 1, post.comments.count
    assert_equal 1, post.comments_count # => returns 0
  end
end
```

Finished in 0.026235s, 38.1171 runs/s, 114.3514 assertions/s.

  1) Failure:
BugTest#test_association_stuff [test.rb:34]:
Expected: 1
  Actual: 0

1 runs, 3 assertions, 1 failures, 0 errors, 0 skips

**Comment by maclover7** [comment]
Is this still an issue on Rails master?

**Comment by felixbuenemann** [comment]
Yes, the `counter_cache` should be on the `belong_to :post`. Rails is strange here, because it doesn't give an error if it is specified on the has many and it's even possible to specify it on the remote side of a has_many through association, but it will fail in ways not even described in #23739.

**Comment by datanoise** [comment]
Have you tried it? You don't have to use `counter_cache` at all as long as your schema has an appropriate column. So it doesn't matter if you specify it on `belong_to` or `has_many` end, it just doesn't work. In fact, if you looks at the code of has_many association, you won't see any call to update counters while inserting a new object into `has_many` collection. Surprisingly, it's handled correctly for `has_many_through` associations.

**Comment by maclover7** [comment]
@felixbuenemann Would you be willing to copy a summary of this issue and its test case, and add it to the main `counter_cache` issue you have created? We can then close out this ticket, and combine efforts.

**Comment by felixbuenemann** [comment]
If I move the counter_cache to the belong_to, I get wrong counts prior to reload which might be related to my issue, although it doesn't use has_many through.

If I leave the test case as it is, it fails on rails master with:

```
ActiveModel::MissingAttributeError: can't write unknown attribute `true`
```

On 4.2.5.1 the count is correct after reload.

According to the docs the `counter_cache` option on has_many should only be used, if a custom named was used on the belongs_to. So it should be used in addition to the counter_cache on the belongs_to.

Interestingly the count is correct before reload on 4.2.5.1, if the counter cache is specified on both ends of the association:

```ruby
class Post < ActiveRecord::Base
  has_many :comments, counter_cache: :comments_count
end

class Comment < ActiveRecord::Base
  belongs_to :post, counter_cache: :comments_count
end
```

On rails master the count is still incorrect until reload.

The only cases for that in the unit tests was usage to customize the name on a has_many through association (`test/models/post.rb` on `has_many :taggings, :counter_cache => :tags_count`), so it's hard to say what the intended behavior is.

The slim test coverage around this is probably the reason that there are so many different bugs.

I'd be hesitant to add this exact test case without knowing that it's actually supposed to work this way.

**Comment by felixbuenemann** [comment]
@datanoise I think the automatic behavior useful for reading, eg. by using a join and select to add a counter column to a query on the fly, but I wouldn't rely on it for updating, especially since all documentation for counter_cache only uses the explicit specification (see [Association Rails Guide](http://guides.rubyonrails.org/association_basics.html#counter-cache) and [belongs_to](http://api.rubyonrails.org/classes/ActiveRecord/Associations/ClassMethods.html#method-i-belongs_to) documentation). If you find any rails docs on the automatic behavior, please post a link.

**Comment by datanoise** [comment]
@felixbuenemann you are absolutely right. I'm not sure why I thought that no explicit declaration is required.

**Comment by webzorg** [comment]
I have this this in Quiz model 'belongs_to :professor, counter_cache: true' and I am adding quizzes_count field to Quiz model like this add_column :quizzes, :quizzes_count, :integer. The name of the field in the DB is quizzes_count, I checked. So this error is a bug I assume because I have everything required in the guide here http://guides.rubyonrails.org/association_basics.html under :counter_cache.

**Comment by felixbuenemann** [comment]
@webzorg Sounds like you should add the quizzes_count column to the professors table and add the counter_cache: true to the has_many quizzes.
