### ISSUE TITLE
ActionCable in app conflicts with force_ssl 

### ISSUE THREAD

**Issue by twalpole** [rails/rails#23620]
If running actioncable in app when the app is configured with force_ssl = true the SSL middleware 301s the wss requests to https which prevents the web socket communications from connecting

**Comment by maclover7** [comment]
Can you provide a sample application to reproduce the error?

**Comment by twalpole** [comment]
Not immediately, but it's a pretty basic thing -  https://github.com/rails/rails/blob/master/actionpack/lib/action_dispatch/middleware/ssl.rb#L66  checks for request.ssl? (which is false if the requests scheme is wss) so it redirects wss requests which it probably shouldn't be doing

**Comment by maclover7** [comment]
Working on a fix right now. :)

**Comment by maclover7** [comment]
I have the changes I think need to make this work, ready to go locally, but before I push up, can you try and run your app on Rails master and make sure this still fails?

**Comment by maclover7** [comment]
cc @dhh @jeremy - do you guys use SSL with Action Cable at Basecamp? Have you run into this error before?

**Comment by twalpole** [comment]
@maclover7 Yes - I still get errors with master -- I would assume Basecamp doesn't get errors because they're not running Action Cable in app.

**Comment by dhh** [comment]
We are not running cable in-app. We use separate processes at Basecamp. But certainly it should be possible for those to work together so would be great to have someone investigate.

**Comment by maclover7** [comment]
Pushing up PR.

**Comment by matthewd** [comment]
@twalpole can you please clarify what's actually happening here?

AIUI, `ssl?` is checking that `rack.url_scheme` is `https`, which it should be for a WSS request. :confused:

**Comment by twalpole** [comment]
@matthewd  the scheme for a wss://example.com/cable request is wss - not https - however both are ssl encrypted.  The issue here is that when force_ssl is true it only checks for the https scheme and then incorrectly redirects wss requests.

**Comment by matthewd** [comment]
@twalpole that's the "true" scheme... but at the rack end, `rack.url_scheme` should still be `https`, as far as I can see.

I only went as far as a code search in puma and thin, but they both seem to only ever set one of those two values.. which stands to reason: any other value would violate ["`rack.url_scheme` must either be `http` or `https`"](https://github.com/rack/rack/blob/master/SPEC#L127).

**Comment by twalpole** [comment]
@matthewd  Hmmm -- it may be X-Forwarded-Proto getting set to 'wss' which overrides rack.url_scheme in https://github.com/rack/rack/blob/master/lib/rack/request.rb#L210  -- forcing the ssl? check to fail  - I need to check further to confirm that, probably won't be able to get to it until tomorrow some time

**Comment by matthewd** [comment]
Ah... hmmm indeed.

I *think* I'd argue that whoever's setting that header is lying to the rack server: the protocol the current request arrived on was https. The request happens to be an upgrade request to switch to a different protocol, but that hasn't happened yet.

**Comment by twalpole** [comment]
@matthewd An nginx config `proxy_set_header X-Forwarded-Proto $scheme;` was setting X-Forwarded-Proto to `wss` which was causing the `ssl?` to fail. 

I'm not fully convinced X-Forwarded-Proto being set to 'wss' is wrong, since the connection is using the wss protocol where the handshake is designed to be interpreted by http(s) servers as an upgrade request - however this doesn't appear to be an issue with rails, as much as an issue with rack (if it's a valid issue at all).  Closing.
