### ISSUE TITLE
Misleading section in the guide "Getting Started with Rails"

### ISSUE THREAD

**Issue by esquinas** [rails/rails#23623]
In section **[5.12 Using partials to clean up duplication in views](http://guides.rubyonrails.org/getting_started.html#using-partials-to-clean-up-duplication-in-views)** the guide states: 
> Our edit page looks very similar to the new page; in fact, they both share the same code for displaying the form. Let's remove this duplication by using a view partial. [...]

~~This is wrong, if you follow the guide, at that moment the code for "new.html.erb" starts with:~~
```ruby
<%= form_for :article, url: articles_path do |f| %>
``` 
Whereas code for "edit.html.erb" starts with: 
```ruby
<%= form_for :article, url: article_path(@article), method: :patch do |f| %>
``` 
~~Then the guide suggest to join the code in a partial called "_form.html.erb". Which creates the bug. The resulting rails application example is unable to edit any blog article. It duplicates articles instead of updating.~~

This could be a put off for many students considering Ruby on Rails.

~~My solution was to create two partials, "_edit_form.html.erb" and "_new_form.html.erb", then, for the code in common, each partial render another partial called "_form.html.erb".~~

~~But instead of my improvised solution as I moved on with the guide, maybe, for the sake of simplicity, this duplication removal part should be erased. Nothing would be lost because, later on, the guide explains partials and DRY principles in the [7 Refactoring](http://guides.rubyonrails.org/getting_started.html#refactoring) section.~~

Thanks.

**Comment by maclover7** [comment]
Can you open a PR to actually remove the `url: article_path(@article), method: :patch` and `url: articles_path`? We should be using `@article`, `:article` might work, but not positive on that. `@article` is what the generators use.

**Comment by vipulnsward** [comment]
Actually, we specify to create a new file with new contents here- http://take.ms/UgUow
We then go on to explain how we have changed to make use of new route helper- http://take.ms/fMKAp

The initial use of `:article`, and `method: :patch` serve their purpose, ie- to define simple forms without this helper and introduce us with POST/PATCH on resource.

:-1: on any changes here.

**Comment by esquinas** [comment]
@vipulnsward I'm sorry, you're right. My mistake. 
However I think the writing is put in a way that is a bit confusing. When it says:
> Everything except for the `form_for` declaration remained the same. The reason we can use this shorter, simpler `form_for` declaration to stand in for either of the other forms...

I thought it meant "simpler" just because of the partial, not because of changes in the `form_for` arguments. Changes I was not aware of. As it is, it makes you create the partial before there is even real duplication. It would be clearer and more educational if it were to address one issue, then the other; like: 
+ First, explain  how to make a simpler `form_for` declaration in both `edit.html.erb` and `new.html.erb`. Explain why it works.
+ Second, remove the **exact duplication** you just wrote and paste it into a partial `_form.html.erb`. Explain the DRY principles.

**Comment by vipulnsward** [comment]
Hmm, that would be even more duplication. If you'd like, you can take a stab at improving http://take.ms/fMKAp and making it simpler.

Going to close this. Thanks for reporting!
