### ISSUE TITLE
tag data attributes has different behavior dependent on declaration

### ISSUE THREAD

**Issue by pluff** [rails/rails#23634]
Rails helper converts attributes differently based on declaration.
```
> link_to 'aaa', '#', 'class' => nil, 'data-tooltip' => nil
=> "<a href=\"#\">aaa</a>"
> link_to 'aaa', '#', class: nil, data: {tooltip: nil}
=> "<a data-tooltip=\"null\" href=\"#\">aaa</a>"
```
I'd expect output to have no attributes with "null" value in both ways.
https://github.com/rails/rails/blob/master/actionview/lib/action_view/helpers/tag_helper.rb#L173-L179

**Comment by xw19** [comment]
One probable solution can be deleting all values with nil keys from hash_options

**Comment by xw19** [comment]
I think in this method
https://github.com/rails/rails/blob/07e6f5327cc54faaf3fc350a77cef43e8c3860d8/actionview/lib/action_view/helpers/url_helper.rb#L175
if we modify the private method convert_options_to_data_attributes and delete keys with null values this small inconsistency can be removed

**Comment by xw19** [comment]
I have created a PR which solves this issue  #23644

**Comment by senny** [comment]
Closed by 23648
