### ISSUE TITLE
Presence validation of virtual attribute not firing appropriately

### ISSUE THREAD

**Issue by derekprior** [rails/rails#23645]
In [Clearance](https://github.com/thoughtbot.clearance) we use a conditional validation on the virtual `password` attribute to determine whether the password field needs to be validated. We only need to validate it when the underlying database row's `encrypted_password` is not set or if the user is changing the password.

I found that when testing against rails 5, the conditional validation does not behave as expected. The method that guards the validation returns as it did under 4.2, but calls to `valid?` return `true` when they should return `false`. Interestingly, the call to `save` inside the `valid?` conditional *does* fire the validation appropriately.

It seems `valid?` is short circuiting, maybe because no active-record level changes have been detected? Yet `save` does not short circuit?

Here's a test case:

```ruby
begin
  require 'bundler/inline'
rescue LoadError => e
  $stderr.puts 'Bundler version 1.10 or later is required. Please update your Bundler'
  raise e
end

gemfile(true) do
  source 'https://rubygems.org'
  gem 'rails', github: 'rails/rails'
  gem 'arel', github: 'rails/arel'
  gem 'rack', github: 'rack/rack'
  gem 'sprockets', github: 'rails/sprockets'
  gem 'sprockets-rails', github: 'rails/sprockets-rails'
  gem 'sass-rails', github: 'rails/sass-rails'

  # gem 'activerecord', '~> 4.2.0'
  gem 'sqlite3'
  gem 'pry'
end

require 'active_record'
require 'minitest/autorun'
require 'logger'

# This connection will do for database-independent bug reports.
ActiveRecord::Base.establish_connection(adapter: 'sqlite3', database: ':memory:')
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :users, force: true  do |t|
    t.string :email, null: false
    t.string :encrypted_password, null: false
    t.timestamp :password_updated_at
  end
end

class User < ActiveRecord::Base
  attr_accessor :password_changing
  attr_reader :password
  validates :email, presence: true
  validates :password, presence: true, unless: :skip_password_validation?

  def update_password(new_password)
    self.password_changing = true
    self.password = new_password

    puts "skip_password_validation?    #{skip_password_validation?}"
    puts "password.blank?              #{password.blank?}"
    puts "valid?                       #{valid?}"

    if valid?
      self.password_updated_at = Time.now
      save # Interestingly, this does fail with password can't be blank...
    end
  end

  private

  def password=(new_password)
    @password = new_password

    if new_password.present?
      self.encrypted_password = new_password.reverse
    end
  end

  def skip_password_validation?
    encrypted_password.present? && !password_changing
  end
end

class BugTest < Minitest::Test
  def test_validation
    user = User.create!(email: 'foo@bar.com', encrypted_password: 'olleh')

    user.update_password("")

    assert user.password_updated_at == nil
  end
end
```

**Comment by derekprior** [comment]
With that knowledge, here's a smaller test case:

```ruby
begin
  require 'bundler/inline'
rescue LoadError => e
  $stderr.puts 'Bundler version 1.10 or later is required. Please update your Bundler'
  raise e
end

gemfile(true) do
  source 'https://rubygems.org'
  gem 'rails', github: 'rails/rails'
  gem 'arel', github: 'rails/arel'
  gem 'rack', github: 'rack/rack'
  gem 'sprockets', github: 'rails/sprockets'
  gem 'sprockets-rails', github: 'rails/sprockets-rails'
  gem 'sass-rails', github: 'rails/sass-rails'

  # gem 'activerecord', '~> 4.2.0'
  gem 'sqlite3'
  gem 'pry'
end

require 'active_record'
require 'minitest/autorun'
require 'logger'

# This connection will do for database-independent bug reports.
ActiveRecord::Base.establish_connection(adapter: 'sqlite3', database: ':memory:')
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :users, force: true  do |t|
    t.string :email, null: false
  end
end

class User < ActiveRecord::Base
  attr_accessor :password
  validates :email, presence: true
  validates :password, presence: true
end

class BugTest < Minitest::Test
  def test_validation
    user = User.create!(email: 'foo@bar.com', password: 'foo')

    user.password = ''
    # user.email_will_change!

    assert user.invalid?
  end
end
```

If I uncomment the `email_will_change!` line, the test passes. I've updated the title of this issue as it can be reproduced without the validation being conditional.

**Comment by eileencodes** [comment]
@derekprior I'm confused. You said if you uncomment `email_will_change!` the test passes. I'm getting the opposite. Commented out, test passes. Uncommented, test fails.

Which is the behavior that should fail?

**Comment by eileencodes** [comment]
Nevermind, I need more :coffee: :flushed:

**Comment by eileencodes** [comment]
I've investigated a bit and understand why this is happening but not sure yet how to fix it. The problem is with any non-db attribute. So because `password` is an `attr_accessor` and not an attribute of the record `record.changed?` is returning `false`, whereas if it were a db attribute then it would return `true` for `changed?`.

If the record was considered dirty and the attributes changed this would not have changed behavior. The reason `email_will_change!` works is because it's marking the record as `changed?`. 

I'm not sure the best way to fix this yet.

**Comment by eileencodes** [comment]
Ok this is fixed in master. There is no way for Rails to know that the record was `record.changed?` or dirty when using a virtual attribute like this. I think we should eventually deprecate this behavior but I talked about it with Aaron and it's not super easy to do that.

What I did to fix the issue was check if the changed attribute was in the `record.attributes` hash. If it's not then it's a virtual attribute and we can say always check this record if we don't know about the attribute in the database.

If you do want to mark your record as dirty when setting a virtual attribute you can use the following code:

```ruby
def password=(value)
  attribute_will_change!(:password)
  @password = value
end
```

**Comment by derekprior** [comment]
Thank you @eileencodes !
