### ISSUE TITLE
ActionController::Streaming doesnt work in Rails 5

### ISSUE THREAD

**Issue by AndreasWurm** [rails/rails#23659]
Streaming doenst work in 5.0.0.beta2.
The response is sent with Transfer-Encoding:chunked but waits for the view to finish rendering.

I encountered this while upgrading a Rails 4.2.5.1 app with slim as templating engine.
Tested with unicorn and passenger standalone.

Created a new Rails 5 App with erb views. Same result.

```
def index
  render stream: true
end
```

application.html.erb
```
<!DOCTYPE html>
<html>
  <head>
    <title>Streaming Test</title>
  </head>
  <body>
    <%= yield %>
  </body>
</html>
```
index.html.erb
```
<%- sleep 3 %>
some text
```

**Comment by maclover7** [comment]
Will try and bisect when I get a chance.

cc @tenderlove

**Comment by diego-silva** [comment]
This issue was caused by the commit https://github.com/rails/rails/commit/69009f4473637a44ade26d954ef5ddea6ff903f2.
