### ISSUE TITLE
Can't eagerload classes

### ISSUE THREAD

**Issue by schnmudgal** [rails/rails#23673]
**Rails: 4.2.5**
I'm doing following in development mode
`ActionDispatch::Reloader.to_prepare do`
`  Rails.application.eager_load!`
`end`

And it's throwing following exception.
`.rvm/gems/ruby-2.2.3/gems/activemodel-4.2.5/lib/active_model/validations/validates.rb:120:in rescue in block in validates': Unknown validator: 'PersenceValidator' (ArgumentError)`

PS: Needed to eagerload classes to get **subclasses** of my **STI** model.

**Comment by maclover7** [comment]
Can you please provide a sample application to replicate this error? Also, does this error appear on Rails master, or the latest beta?

**Comment by schnmudgal** [comment]
Yes, that was a typo itself. Pardon for bothering much.

**Comment by fxn** [comment]
Eager loading for STI is going to an unnecesary extreme, please have a look at the autoloading guide more specific ways to support them.

**Comment by schnmudgal** [comment]
@fxn : Then you mean Hardcoding the Children in any array or something would be a better solution? What overhead does it make to eagerload?
