### ISSUE TITLE
Rails 5 ActionCable doesn't work with Cygwin

### ISSUE THREAD

**Issue by panyamin** [rails/rails#23680]
Hello,

I post this issue in order to help me investigate on why ActionCable doesn't work with Cygwin.
I created a very simple project with only a RoomChannel, which work on linux.

Only `Registered connection` notification is called on Cygwin. The websocket or backend seem to fail at some point.

I will run a couple of tests in order to find which dependencies are involved. It can be: `websocket-driver`, `ruby-concurrency`, `nio4r` or `puma`.

I'm starting tests with `websocket-driver`.

Maybe it's related to the fact that Cygwin can't handle multiple threads/forks?

Rails `v5.0.0.beta2`
Ruby tested versions `2.2.x-2.3.0`

**Comment by maclover7** [comment]
Thank you for the bug report -- would you be able to post the code for the sample app that is causing you the problem?

cc @sgrif, since I believe you were trying to get Rails and Windows working together more smoothly

**Comment by panyamin** [comment]
Here's the sample app, you'll see, it's a very simple app: https://github.com/panyamin/rails5

**Comment by panyamin** [comment]
Well, I've tested individually each dependencies `websocket-driver`, `puma`, `faye-websocket-ruby`, even with `rack2.0.0.alpha`.. and it's working, WebSockets are connecting.

I'm still looking...
