### ISSUE TITLE
ActiveSupport's since operations returns wrong date and time.

### ISSUE THREAD

**Issue by matsubo** [rails/rails#23685]
Datetime calculation returns wrong result if timezone is `Wellington` (+13:00).

Test code
===

https://gist.github.com/matsubo/7b3c7fbe6e613d515158
```
 require 'active_support'
 require 'active_support/core_ext'

# Wrong
# 2014-04-06 00:59:59 UTC
# should be 2014-04-05 23:59:59 UTC
puts 37.days.since(Time.utc(2014, 2, 27, 23, 59, 59).in_time_zone('Wellington')).utc

# OK
# 2014-04-05 23:59:59 UTC
puts 37.days.since(Time.utc(2014, 2, 27, 23, 59, 59).in_time_zone('Wellington').utc)

# OK
# 2014-04-04 23:59:59 UTC
puts 36.days.since(Time.utc(2014, 2, 27, 23, 59, 59).in_time_zone('Wellington')).utc

# OK
# 2014-04-04 23:59:59 UTC
puts 36.days.since(Time.utc(2014, 2, 27, 23, 59, 59).in_time_zone('Wellington').utc)

```

Ruby version
---

It can be reproduced on these environment
- ruby 2.2.0p0 (2014-12-25 revision 49005) [x86_64-darwin13]
- ruby 2.3.0p0 (2015-12-25 revision 53290) [x86_64-darwin15]
- ruby 2.3.0p0 (2015-12-25 revision 53290) [x86_64-linux]

Gem version
---
- activesupport (4.2.5.1)

**Comment by simi** [comment]
probably related to https://github.com/Shopify/active_utils

**Comment by matsubo** [comment]
I'll close and move to Shopify's repo. thx.

**Comment by simi** [comment]
Sorry, but this is not active utils problem actually. I can get same results with active support only.

**Comment by matsubo** [comment]
@syamilmj Could you tell me where is the best place to post?

**Comment by simi** [comment]
Since `since`, `in_time_zone` and `utc` are ActiveSupport methods, I think this is good place.

**Comment by matsubo** [comment]
@simi Thanks. Updated title and descriptions and reopen this issue.

**Comment by matthewd** [comment]
The described behaviour seems correct to me.

On the day in question (Sun, 06 Apr 2014), Wellington had finished DST, and its offset reverted to +12:00.

**Comment by matsubo** [comment]
@matthewd Oh. Thanks. now understood that DST is different from each country.
http://www.timeanddate.com/time/dst/2014.html
