### ISSUE TITLE
[ActionPack] Nested routes make 'widgets#show' resolve before 'widgets#new'

### ISSUE THREAD

**Issue by TheLonelyGhost** [rails/rails#23689]
**Problem:**

The resource route for `/projects/new` resolves to `projects#show` instead of `projects#new`.

**To Duplicate:**

- `ruby 2.3.0p0 (2015-12-25 revision 53290) [x86_64-darwin15]` (rbenv)
- Rails 4.2.5, 5.0.0.beta2, and master@7c3dc96
- Per the guidelines for ActionPack bugs, see [example gist](https://gist.github.com/TheLonelyGhost/7e49eccf468a61e26c63) for self-contained executable test.

I've narrowed it down to when shallow, nested routing was introduced to my project. Bad code:

```ruby
Rails.application.routes.draw do
  root to: 'projects#index'

  resources :clients, shallow: true do
    resources :projects
  end

  resources :projects

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  # Serve websocket cable requests in-process
  # mount ActionCable.server => '/cable'
end
```

**Workaround:**

Reorder the occurrence of resources. Changing the above routes to the following makes all tests pass.

```ruby
Rails.application.routes.draw do
  root to: 'projects#index'

  resources :projects
 
  resources :clients, shallow: true do
    resources :projects
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  # Serve websocket cable requests in-process
  # mount ActionCable.server => '/cable'
end
```

**Comment by maclover7** [comment]
To me, this seems like expected behavior. When a request comes through, routes at the top of your `config/routes.rb` file have a higher precedence (they get checked first) before routes at the bottom of your `config/routes.rb` file.

**Comment by TheLonelyGhost** [comment]
@maclover7 The problem is that the nested projects resource within the clients resource evaluates to `/clients/:client_id/projects/:id`. The shallow nesting option on the nested version of projects resource apparently carries over to the full-blown version of the same resource when not nested.

**Comment by TheLonelyGhost** [comment]
Additionally, I've confirmed this seems to specifically happen when the `shallow: true` option is given. When removed, the bug disappears.

**Comment by vipulnsward** [comment]
This is expected. When you do shallow: true, it creates routes like- 

        #     resources :posts, shallow: true do
        #       resources :comments
        #     end

becomes 

        #     resources :posts do
        #       resources :comments, except: [:show, :edit, :update, :destroy]
        #     end
        #     resources :comments, only: [:show, :edit, :update, :destroy]
        #

So you second definition of resources :projects, is clashing with 

`resources :projects, only: [:show, :edit, :update, :destroy] `

This is what I get with your definition of routes - https://gist.github.com/vipulnsward/731f164b10f99819e99a

Notice, there is no `new` route defined at all, due to shallow.

**Comment by TheLonelyGhost** [comment]
I see now. It seems I misunderstood what [the routing guide](http://edgeguides.rubyonrails.org/routing.html) says about [shallow nesting](http://edgeguides.rubyonrails.org/routing.html#shallow-nesting). @vipulnsward's example using `except` and `only` to show what shallow aliases makes things much clearer. Thank you.

Apparently the `shallow: true` option transplants the `:create`, `:new`, and `:index` actions of resource CRUD from the version that isn't nested to the version that is. The purpose seems to be for requiring hierarchical dependencies between resources, e.g. all projects needing to be assigned to a client.

**Comment by maclover7** [comment]
@TheLonelyGhost - If there's anything that could be added to the docs to make it more clear about what shallow nesting provides, feel free to send a PR to update the docs!

**Comment by TheLonelyGhost** [comment]
Thanks, @maclover7. I was about to draft a PR. Where's the repo for rails guides?

**Comment by maclover7** [comment]
haha, yep! :+1:
