### ISSUE TITLE
undefined method cache on 4.2.5.1 when rescue_from

### ISSUE THREAD

**Issue by jandudulski** [rails/rails#23691]
I've got such code:

```ruby
class ApplicationController < ActionController::Base
  rescue_from ActiveRecord::RecordNotFound, with: :record_not_found

  def record_not_found
    render "something"
  end
end

class PostsController < ApplicationController
  caches_page :show # from actionpack-page_caching

  def show
    @post = Post.find_by(slug: params[:slug])
  end
end
```

And it works for `4.2.5` when post is missing. After upgrade to `4.2.5.1` I've got an error:

```ruby
NoMethodError:
  undefined method `cache` for nil:NilClass
```

In the line with `render_not_found` method on `render` call.

**Comment by vipulnsward** [comment]
Thanks @jandudulski for reporting. Can you help reproduce this with this [script] (https://github.com/rails/rails/blob/master/guides/bug_report_templates/action_controller_gem.rb)

**Comment by jandudulski** [comment]
I'm not able to reproduce this bug with the script so far, maybe it is related with other third party :/ Will try tomorrow again.

**Comment by jandudulski** [comment]
After some debugging it seems that it is related to `render file: "path/to/file"`. It goes to [this place](https://github.com/rails/rails/compare/v4.2.5...v4.2.5.1#diff-40f2a5bcf9edfd65a8efe42a05c53736R151) but `@cache` is `nil`.

**Comment by jandudulski** [comment]
Ech, that was an [rspec issue](https://github.com/rspec/rspec-rails/pull/1535), that's why I wasn't able to reproduce this with minitest :smile:
