### ISSUE TITLE
ActionDispatch::Journey::Router NoMethodError (undefined method `names' for nil:NilClass)

### ISSUE THREAD

**Issue by brianstien** [rails/rails#23699]
When running a multithreaded rails server (JRuby + Puma), occasionally when the rails app starts and several incoming  requests hit different routes at the same time, a route might become corrupted and throw this error.

Any subsequent requests to the corrupted route to fail with this error for the lifetime of the application.  Only a restart of the application will fix this once it has been corrupted.
##### Root Cause
- The backtrace points to [here](https://github.com/rails/rails/blob/master/actionpack/lib/action_dispatch/journey/router.rb#L115) which is because match_data is nil
- `match_data` is nil because the `route.path.match` returns nil
- `route.path.match` returns nil because the routes `@re` instance variable is set incorrectly
- `@re` is lazily evaluated, and in a multi-threaded application this is not safe
##### Replication

I created an app that replicates this issue [here](https://github.com/brianstien/hacktime#replication).  I apologize for the difficult replication, but since this is a threading related bug it is naturally difficult.  I spent several hours trying to get a simple-ish replication, but if we need a better one I can spend some more time on it.
##### Potential Fix

[Here](https://github.com/rails/rails/compare/master...brianstien:master) is a potential fix for this issue.   I am happy to send a pull request if you want.
##### Backtrace Attached

[rails_backtrace.txt](https://github.com/rails/rails/files/131627/rails_backtrace.txt)

Thanks for looking at this issue :)

**Comment by maclover7** [comment]
Feel free to send a PR.

**Comment by maclover7** [comment]
cc @tenderlove

**Comment by pixeltrix** [comment]
Looks like there's a bunch of instance variablea in `ActionDispatch::Journey::Path::Pattern` that could cause similar problems - I'd rather we fixed them all in one go than play whack-a-mole.

**Comment by cavneb** [comment]
:+1: We are also running into this issue (jruby 9.0.4.0) / Rails 4.2.3

**Comment by daneshd** [comment]
:+1: running into this with jruby 9.0.5.0 and rails 3.2.22 as well

**Comment by uhomira** [comment]
:+1: We are also running into this issue (jruby 9.1.0.0 / Rails 4.2.6)

**Comment by nadavshatz** [comment]
👍  We too :(

**Comment by cha55son** [comment]
👍 Hitting this issue (jruby 9.1.2.0 / Rails 4.1.16)

**Comment by prcongithub** [comment]
Same issue with JRuby-9.1.7.0 and Puma-3.7.0-java and Rails-4.2.5.1

**Comment by alaz** [comment]
Same issue. JRuby 9.1.15.0, Rails 5.1.4, Puma 3.11.0-java

**Comment by tomilaine** [comment]
@alaz Are you sure it's the same issue?
I'm experiencing this with JRuby: 9.1.15.0, Rails 4.2.8 and I was hoping for Rails upgrade to fix this.

To be more precise... I was hoping this would fix it:
https://github.com/rails/rails/commit/ce97c79445f9ac4b056e34deaaaaf25cadc08b72
https://github.com/rails/rails/pull/27647

**Comment by alaz** [comment]
@tomilaine Ah, pity I didn't provide a stack trace. Sorry about that. At least I can recall I've occasionally seen exactly `NoMethodError` on startup and the app was unresponsive after that.

---

I've mitigated the issue w/ one extra Ansible step that warms up an instance before serving requests to it.

**Comment by jboler** [comment]
I have the same issue (ActionDispatch::Journey::Router NoMethodError (undefined method `names' for nil:NilClass)) with jRuby 9.1.17.0, Puma 3.11.4-java and Rails 5.1.5. 

@alaz How are you warming up your instances and does it consistently prevent this issue?

**Comment by alaz** [comment]
@jboler I have a load balancer (Nginx) that automatically pulls an instance out of rotation during redeployment and tries again in 5 seconds. I created a trivial Rails API controller doing nothing, it just returns `204 No Content`. The last step in my Ansible script is to request this route. Since this call happens within that 5 second window when the node has no requests from the load balancer, it's the first and only request coming into that JRuby/Rails instance. I've never seen this issue since then.

**Comment by TDA** [comment]
Facing the same issue on jRuby 9.1.7, Rails 4.2.7. Is the proposed fix going to be merged?

**Comment by JasonLunn** [comment]
Still seeing this issue on rails 5.1.6 / JRuby 9.1.17.0

**Comment by guizmaii** [comment]
Hey, 

Still seeing this bug with JRuby 9.2.7.0 and Rails 4.2.11.1

**Comment by jboler** [comment]
@guizmaii This was fixed in Rails 5.2.1 #33054

**Comment by JasonLunn** [comment]
I think you mean 6, rather than 5.2.1?

**Comment by jboler** [comment]
@JasonLunn The fix is on `5-2-stable`: https://github.com/rails/rails/commit/2edd67eec55d5f8dfde0af6fdb7ce166135f8526

**Comment by JasonLunn** [comment]
Ah, well, in that case there are probably other ways to trigger this issue (or adjacent ones that manifest similarly) as we were continue to see the same exception under Rails 5.1 in our production environment. I saw the original commits merge to `master` and see them appear in the 6.0 RC's, but you're correct that they were also cherry picked into 5.1 and 5.2.

**Comment by jboler** [comment]
Can you share a stack trace?

**Comment by guizmaii** [comment]
@jboler Good to know! But we're using Rails 4.2. 😕

Do you have an idea how we can fix that problem without upgrading our app to Rails 5 ?

**Comment by JasonLunn** [comment]
@guizmaii - I think 4.x is deprecated at this point and no longer receiving fixes for anything other than critical security vulnerabilities...

**Comment by guizmaii** [comment]
@JasonLunn Yes, I know but maybe I can monkey patch some Rails classes ? 

A quick & dirty fix is better to me for now than taking the time to upgrade to Rails 5. That's why I asked for a solution to fix that in Rails 4.2 🙂

**Comment by tomdepplito** [comment]
@jboler, here is the stack trace to which @JasonLunn is referring:
[router_error_stack_trace.txt](https://github.com/rails/rails/files/3131270/router_error_stack_trace.txt)

**Comment by prcongithub** [comment]
Is this fix available on 5.2.0? I am getting this same error on JRuby-9.2.6.0, Rails-5.2.0, Puma 3.11.2

**Comment by JasonLunn** [comment]
I believe 5.2.1 was the first release after the fix landed.

**Comment by gerhardgruber** [comment]
I still get this error with JRuby 9.2.8.0, Rails 5.2.3 and Puma 4.2.1
```
NoMethodError (undefined method `names' for nil:NilClass):

actionpack (5.2.3) lib/action_dispatch/journey/router.rb:128:in `block in find_routes'
org/jruby/RubyArray.java:2616:in `map!'
actionpack (5.2.3) lib/action_dispatch/journey/router.rb:125:in `find_routes'
actionpack (5.2.3) lib/action_dispatch/journey/router.rb:35:in `serve'
actionpack (5.2.3) lib/action_dispatch/routing/route_set.rb:840:in `call'
apipie-rails (0.5.16) lib/apipie/static_dispatcher.rb:66:in `call'
apipie-rails (0.5.16) lib/apipie/extractor/recorder.rb:137:in `call'
rack (2.0.7) lib/rack/tempfile_reaper.rb:15:in `call'
rack (2.0.7) lib/rack/etag.rb:25:in `call'
rack (2.0.7) lib/rack/conditional_get.rb:25:in `call'
rack (2.0.7) lib/rack/head.rb:12:in `call'
actionpack (5.2.3) lib/action_dispatch/http/content_security_policy.rb:18:in `call'
rack (2.0.7) lib/rack/session/abstract/id.rb:232:in `context'
rack (2.0.7) lib/rack/session/abstract/id.rb:226:in `call'
actionpack (5.2.3) lib/action_dispatch/middleware/cookies.rb:670:in `call'
actionpack (5.2.3) lib/action_dispatch/middleware/callbacks.rb:28:in `block in call'
activesupport (5.2.3) lib/active_support/callbacks.rb:98:in `run_callbacks'
actionpack (5.2.3) lib/action_dispatch/middleware/callbacks.rb:26:in `call'
actionpack (5.2.3) lib/action_dispatch/middleware/executor.rb:14:in `call'
app/middleware/check_referer.rb:25:in `call'
app/middleware/add_security_headers.rb:8:in `call'
actionpack (5.2.3) lib/action_dispatch/middleware/debug_exceptions.rb:61:in `call'
actionpack (5.2.3) lib/action_dispatch/middleware/show_exceptions.rb:33:in `call'
railties (5.2.3) lib/rails/rack/logger.rb:38:in `call_app'
railties (5.2.3) lib/rails/rack/logger.rb:26:in `block in call'
activesupport (5.2.3) lib/active_support/tagged_logging.rb:71:in `block in tagged'
activesupport (5.2.3) lib/active_support/tagged_logging.rb:28:in `tagged'
activesupport (5.2.3) lib/active_support/tagged_logging.rb:71:in `tagged'
railties (5.2.3) lib/rails/rack/logger.rb:26:in `call'
actionpack (5.2.3) lib/action_dispatch/middleware/remote_ip.rb:81:in `call'
actionpack (5.2.3) lib/action_dispatch/middleware/request_id.rb:27:in `call'
rack (2.0.7) lib/rack/method_override.rb:22:in `call'
rack (2.0.7) lib/rack/runtime.rb:22:in `call'
activesupport (5.2.3) lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'
actionpack (5.2.3) lib/action_dispatch/middleware/executor.rb:14:in `call'
actionpack (5.2.3) lib/action_dispatch/middleware/static.rb:127:in `call'
rack (2.0.7) lib/rack/sendfile.rb:111:in `call'
rack-cors (1.0.3) lib/rack/cors.rb:95:in `call'
railties (5.2.3) lib/rails/engine.rb:524:in `call'
org/jruby/RubyKernel.java:1953:in `public_send'
railties (5.2.3) lib/rails/railtie.rb:190:in `method_missing'
rack (2.0.7) lib/rack/urlmap.rb:68:in `block in call'
org/jruby/RubyArray.java:1800:in `each'
rack (2.0.7) lib/rack/urlmap.rb:53:in `call'
puma-4.2.1 (java) lib/puma/configuration.rb:228:in `call'
puma-4.2.1 (java) lib/puma/server.rb:667:in `handle_request'
puma-4.2.1 (java) lib/puma/server.rb:470:in `process_client'
puma-4.2.1 (java) lib/puma/server.rb:328:in `block in run'
puma-4.2.1 (java) lib/puma/thread_pool.rb:134:in `block in spawn_thread'
```

**Comment by jboler** [comment]
Do you have `config.eager_load = true` in `config/environments/production.rb` ?

**Comment by papricek** [comment]
Experiencing the same thing, with jRuby 9.2.5.0 and Rails 5.2.3 and eager_load = true. Anyone knowing what is this about? 5.2.3 seems to have the above mentioned fix...

```
[2019-11-18 10:05:29,235] INFO  [ajp-nio-10.111.105.154-8009-exec-1] {org.apache.catalina.core.ContainerBase.[Catalina].[uscxypl6g0h].[/neu]} F, [2019-11-18T10:05:29.235565 #13036] FATAL -- : [02863b94-c844-4634-af7a-012604fb142a] gems/gems/actionpack-5.2.3/lib/action_dispatch/journey/router.rb:128:in `block in find_routes'
[02863b94-c844-4634-af7a-012604fb142a] org/jruby/RubyArray.java:2609:in `map!'
[02863b94-c844-4634-af7a-012604fb142a] gems/gems/actionpack-5.2.3/lib/action_dispatch/journey/router.rb:125:in `find_routes'
[02863b94-c844-4634-af7a-012604fb142a] gems/gems/actionpack-5.2.3/lib/action_dispatch/journey/router.rb:35:in `serve'
[02863b94-c844-4634-af7a-012604fb142a] gems/gems/actionpack-5.2.3/lib/action_dispatch/routing/route_set.rb:840:in `call'
[02863b94-c844-4634-af7a-012604fb142a] gems/gems/rack-2.0.7/lib/rack/tempfile_reaper.rb:15:in `call'
[02863b94-c844-4634-af7a-012604fb142a] gems/gems/rack-2.0.7/lib/rack/etag.rb:25:in `call'
[02863b94-c844-4634-af7a-012604fb142a] gems/gems/rack-2.0.7/lib/rack/conditional_get.rb:25:in `call'
[02863b94-c844-4634-af7a-012604fb142a] gems/gems/rack-2.0.7/lib/rack/head.rb:12:in `call'
[02863b94-c844-4634-af7a-012604fb142a] gems/gems/actionpack-5.2.3/lib/action_dispatch/http/content_security_policy.rb:18:in `call'
[02863b94-c844-4634-af7a-012604fb142a] gems/gems/rack-2.0.7/lib/rack/session/abstract/id.rb:232:in `context'
[02863b94-c844-4634-af7a-012604fb142a] gems/gems/rack-2.0.7/lib/rack/session/abstract/id.rb:226:in `call'
[02863b94-c844-4634-af7a-012604fb142a] gems/gems/actionpack-5.2.3/lib/action_dispatch/middleware/cookies.rb:670:in `call'
[02863b94-c844-4634-af7a-012604fb142a] gems/gems/actionpack-5.2.3/lib/action_dispatch/middleware/callbacks.rb:28:in `block in call'
[02863b94-c844-4634-af7a-012604fb142a] gems/gems/activesupport-5.2.3/lib/active_support/callbacks.rb:98:in `run_callbacks'
[02863b94-c844-4634-af7a-012604fb142a] gems/gems/actionpack-5.2.3/lib/action_dispatch/middleware/callbacks.rb:26:in `call'
[02863b94-c844-4634-af7a-012604fb142a] gems/gems/actionpack-5.2.3/lib/action_dispatch/middleware/debug_exceptions.rb:61:in `call'
[02863b94-c844-4634-af7a-012604fb142a] gems/gems/actionpack-5.2.3/lib/action_dispatch/middleware/show_exceptions.rb:33:in `call'
[02863b94-c844-4634-af7a-012604fb142a] gems/gems/railties-5.2.3/lib/rails/rack/logger.rb:38:in `call_app'
[02863b94-c844-4634-af7a-012604fb142a] gems/gems/railties-5.2.3/lib/rails/rack/logger.rb:26:in `block in call'
[02863b94-c844-4634-af7a-012604fb142a] gems/gems/activesupport-5.2.3/lib/active_support/tagged_logging.rb:71:in `block in tagged'
[02863b94-c844-4634-af7a-012604fb142a] gems/gems/activesupport-5.2.3/lib/active_support/tagged_logging.rb:28:in `tagged'
[02863b94-c844-4634-af7a-012604fb142a] gems/gems/activesupport-5.2.3/lib/active_support/tagged_logging.rb:71:in `tagged'
```

**Comment by jboler** [comment]
@gerhardgruber @papricek Do you have a reliable way to reproduce the error?

**Comment by papricek** [comment]
Unfortunately no, its random :(

**Comment by gerhardgruber** [comment]
No.

**Comment by gerhardgruber** [comment]
And eager_load is set to true

**Comment by jboler** [comment]
It might be worth trying puma v3.12.x

I've been experiencing various strange Rails crashes in puma v4.x on `jRuby` and I filed this bug: https://github.com/puma/puma/issues/2060 . puma v4.x switched to `nio4r` for concurrency and the `nio4r` developer has confirmed that there are jRuby bugs which aren't a priority to fix just now. I have switched our project to use puma v3.12.x because that's been rock solid for a while for us.

**Comment by jboler** [comment]
Oh and use jRuby v9.2.9.0 because it has some important concurrency fixes.

**Comment by qisantanu** [comment]
I am using jruby 9.2.19.0 and rails 6.0.3.7. My puma version is 5.4.0
I am getting the error:

```
NoMethodError (undefined method `names' for nil:NilClass):
  
actionpack (6.0.3.7) lib/action_dispatch/journey/router.rb:124:in `block in find_routes'
```
Unfortunately, the error is not consistent. It is random. Do I need to update the puma version?

**Comment by jboler** [comment]
@qisantanu It's definitely worth upgrading to the latest jRuby, Rails & puma. I'm using jRuby 9.3.3.0, puma 5.5.2 and Rails 6.1.4 and no problems. Also, I found that using tcp sockets for nginx => puma is much more stable that using unix sockets.
