### ISSUE TITLE
ActionCable disconnect client

### ISSUE THREAD

**Issue by Nekromancer** [rails/rails#23708]
I'm not if this is an issue or get something wrong. I'm using ActionCable.beta2 and i'm trying to do kind of "available online" chat feature. It's obvious that `subscribed` method is called when user is connected to channel, but `unsubscribed` is never called. I tried waiting for few hours, turning off browser or even computer. Every page refresh adds new subscriber to list, but there is no event to unsubscribe one. This leads to strange behaviour when message is broadcasted to huge amount of subscribers even when they are not really connected.

So my question is - what are the requirements to user get properly disconnected (on tab close, browser close or just navigate to subpage that don't have this channel subscription)?

PS. I set logger on disconnect in Connection too, it's just.. never called. I'm using Puma server and async adapter on development environment.

**Comment by maclover7** [comment]
Looking into this.

**Comment by maclover7** [comment]
@Nekromancer - thanks for opening up this issue! Can you provide some more context to the situation -- is the unsubscribed JS callback not being triggered when people close the tab, or physically aren't on the site anymore? Since Action Cable runs off of WebSockets, this means that the connection between the user and the server is always kept open, and all of your Action Cable channels communicate through that one connection. I think if anything's going wonky, it would likely be something funky with the [`ConnectionMonitor`](https://github.com/rails/rails/blob/master/actioncable/app/assets/javascripts/action_cable/connection_monitor.coffee) which is responsible for managing and maintaining connections.

**Comment by aasare** [comment]
I got the same issue. @maclover7 shouldn't the `unsubscribe` method be called automatically after the tab is closed ? The Logger denotes nothing about unsubscription. I also put a simple `p` statement inside `unsubscribe` and it's not called.

**Comment by Nekromancer** [comment]
@maclover7 I'm talking about server side. I have overwritten `unsubscribe` method in my channel class that isn't called like.. ever. I suspected it will be called right after user closes tab, browser etc. Maybe i'm wrong, couse i didn't find any example of this anywhere

**Comment by maclover7** [comment]
I'm thinking the issue here is something to do with the client side JavaScript, because unless `unsubscribed` is called from there, then the server won't get `unsubscribed` called on itself, either.

**Comment by Nekromancer** [comment]
Hmm so it's not called when websocket connection is just cut?

**Comment by maclover7** [comment]
No -- it seems like there's no calling of `unsubscribe` with in the Action Cable JS. Only `disconnected` is ever called. Working on a PR to call `unsubscribe` if `disconnected` is called.

**Comment by Nekromancer** [comment]
Couse my client side code is simple as it gets:

```
App.shoutbox = App.cable.subscriptions.create "ShoutboxChannel",
  connected: ->
    # Called when the subscription is ready for use on the server
    console.log("Connected to shoutbox")

  disconnected: ->
    # Called when the subscription has been terminated by the server
    console.log("Disconnected from shoutbox")

  received: (data) ->
    console.log(data)

  speak: (msg) ->
    @perform 'speak', message: msg
```

**Comment by maclover7** [comment]
Yep - I don't think you're doing anything wrong. Something in the internals is busted here. :(

**Comment by Nekromancer** [comment]
Ok, that's actually good to know. I was confused a bit :)

**Comment by maclover7** [comment]
I have a working fix for this -- the issue was that subscriptions to Action Cable channels were not properly disconnected from the server side -- turns out there was nothing wrong with the client side.

**Comment by maclover7** [comment]
Opened PR #23715.
