### ISSUE TITLE
Excess spaces while rendering multiline string

### ISSUE THREAD

**Issue by atomAltera** [rails/rails#23707]
Hello, today I end up with strange issue in Rails 5:

Here is how a simple _text.html.erb_ file looks like:
`<textarea><%= "a\nb\nc" %></textarea>`
And here is what it produce:
[![enter image description here][1]][1] [![enter image description here][2]][2]

I'm talking about these leading spaces before second and third strings.

In my code I have a form with textarea: 

    .form
      =form_for article do |f|
        .form-group
          =field_label f, :text, true
          =f.text_area :text, class: %w(form-control), rows: 20, placeholder: t('placeholder.article_text')

And the same issue happens there on Edit action

  [1]: http://i.stack.imgur.com/qzTx4.png
  [2]: http://i.stack.imgur.com/Z09F4.png

**Comment by leonardoprg** [comment]
@atomAltera 

I tried it locally with rails 5.0.0.beta2 and it works fine to me,

can you create a script test to reproduce it?

examples [here](https://github.com/rails/rails/tree/master/guides/bug_report_templates)

**Comment by matthewd** [comment]
This seems very likely to be the result of an overzealous post-processor, attempting to nicely format your generated HTML. I don't know of anywhere we do such a thing internally.

If you can reproduce it without other gems loaded, let us know, and we can reopen. Thanks. :yellow_heart:

**Comment by atomAltera** [comment]
@matthewd, well you are right. I found the gem, that leads to the issue, it is _gem 'haml-rails', '~> 0.9.0'_
And I have the another one project that uses the same version of haml-rails gem, but there I use rails 4.2

It looks like this is the haml-rails fault, but can you just add it to your test project and test it yourself?

**Comment by droptheplot** [comment]
@atomAltera I had the same issue. Fixed it by setting haml `ugly` option to `true`.
```ruby
# config/initializers/haml.rb
require 'haml/template'

Haml::Template.options[:ugly] = true
```

**Comment by atomAltera** [comment]
@droptheplot oh, thank you. You had really rescued me :)
