### ISSUE TITLE
#or triggers an error " undefined method `limit_value' "

### ISSUE THREAD

**Issue by urielhdz** [rails/rails#23714]
Here's my code:

```ruby
class Friendship < ApplicationRecord
  belongs_to :user
  belongs_to :friend,class_name:"User"
  validates :user_id, uniqueness: {scope: :friend_id}

  def self.are_friends?(user,friend)
  	Friendship.where(user:user,friend:friend_id).or(' id=2 ')
  end
end

```

Here's the error:
```ruby
undefined method `limit_value' for " id=2 ":String
```

I've tried changing the or argument to a Hash without positive results.

```ruby
class Friendship < ApplicationRecord
  belongs_to :user
  belongs_to :friend,class_name:"User"
  validates :user_id, uniqueness: {scope: :friend_id}

  def self.are_friends?(user,friend)
       #This is the actual query I'm trying to archive
  	Friendship.where(user:user,friend:friend_id).or(user:friend,friend:user)
  end
end
```

In this case the error is:

```ruby
undefined method `limit_value' for #<Hash:0x007ff34cb34830>
```

The framework trace points to this line: https://github.com/rails/rails/blob/master/activerecord/lib/active_record/relation/query_methods.rb#L1209

I'm using rails 5.0.0.beta2 and activerecord 5.0.0.beta2

**Comment by rafaelfranca** [comment]
This is the wrong usage of `#or` but we should have a better error message.

The right usage is:

```ruby
Friendship.where(user:user,friend:friend_id).or(Friendship.where(user:friend,friend:user))
```

**Comment by urielhdz** [comment]
Oh god, I just revisited the example I was following and see my mistake. Sorry.

**Comment by prathamesh-sonpatki** [comment]
Working on it to provide better error message. r? @prathamesh-sonpatki

**Comment by prathamesh-sonpatki** [comment]
@rafaelfranca I could not find any docs related to `#or` method on http://edgeguides.rubyonrails.org/active_record_querying.html. Was it done intentionally, if not I will add them.

**Comment by rafaelfranca** [comment]
Yes, it is intentional. We don't need to have section about every method of Rails in the guides. That is what the API website is. Guides are more a walkthrough of features and I don't think `or` deserves a section just for it.

**Comment by prathamesh-sonpatki** [comment]
:+1:
