### ISSUE TITLE
Repository Information Pointing to an HTTP Website

### ISSUE THREAD

**Issue by schmijos** [rails/rails#23719]
I'm "security-concerned" about this *http* link in the github repository info: 

<img width="338" alt="Ruby on Rails http://rubyonrails.org" src="https://cloud.githubusercontent.com/assets/245443/13088874/61243158-d4ee-11e5-971e-4e43d84939fd.png">

Would it be possible to remove it? Or even better: serve *rubyonrails.org* per *HTTPS* and change the link to `https://rubyonrails.org`?

**Comment by connorshea** [comment]
A relevant issue has already been opened [in the homepage repository](https://github.com/rails/homepage/issues/37) if you want more info.
