### ISSUE TITLE
Intermittent error Cannot visit ThreadSafe::Array

### ISSUE THREAD

**Issue by cloxure** [rails/rails#23720]
I am receiving this error on an intermittent when trying to get a simple value from active record.

This is the line that is getting the issue:

```erb
<h5>Pool:  <%= number_to_currency Bet.where(:nominee_id => Nominee.where(:category_id => Category.where(:award_id =>award.id).pluck(:id)).pluck(:id)).sum(:amount).round(2)%></h5>
```

I am using sqlite with just a couple of records. Any ideas?

**Comment by maclover7** [comment]
Can you please provide a sample application to reproduce the error, or can you create a reproducible test script using one of the templates [here](https://github.com/rails/rails/tree/master/guides/bug_report_templates)?

**Comment by cloxure** [comment]
Ok, I will try to reproduce the error.

**Comment by cloxure** [comment]
[here is the file](https://gist.githubusercontent.com/cloxure/7c8d3a54ff501a0b989d/raw/af5bbcdf42177f1c4dc34082a54edd9032170783/thread_safe_array_error.rb)

However I was not able to reproduce the error, I think the issue is within ERB interpreter. How can I reproduce the same error in an script that tests the same active record query on ERB so I can reproduce the error?

**Comment by cloxure** [comment]
Take a look at the error:
![screen shot 2016-02-16 at 10 40 55 pm](https://cloud.githubusercontent.com/assets/2006175/13098249/8f81c8fc-d4fe-11e5-970a-2b2c1843dff7.png)

**Comment by maclover7** [comment]
@tenderlove, I feel like I remember you tweeting about this a few days/weeks ago?

**Comment by matthewd** [comment]
@tenderlove was hitting a bug in ruby trunk.

@cloxure you're presumably running a released ruby version.. which one? And which Rails version?

Do you get the error if this is the first page you load after starting the server?

**Comment by cloxure** [comment]
@matthewd:

- Rails 4.2.5
- ruby 2.4.0dev (2016-01-11 trunk 53499) [x86_64-linux]

**Comment by matthewd** [comment]
> ruby 2.4.0dev (2016-01-11 trunk 53499) [x86_64-linux]

Oh. Well, stop doing that, then. :smile:

**Comment by cloxure** [comment]
@matthewd, ok I will try with another ruby version and let you know. :disappointed:

**Comment by cloxure** [comment]
@matthewd, @tenderlove, @maclover7 I've change to ruby 2.2.1 and it worked !!!!! :smile: .

It was my bad I was using ruby-head from rvm.... you can close the issue now.

And thanks.
