### ISSUE TITLE
ActiveModel::MissingAttributeError: - error with concat on CollectionProxy.

### ISSUE THREAD

**Issue by mokhan** [rails/rails#23745]
We recently upgraded to rails 4.2.5 and with that some of the our queries started raising errors. 

We have provided a repo that reproduces the error here:
* https://github.com/mokhan/rails-4-2-missing-attribute-error

[These](https://github.com/mokhan/rails-4-2-missing-attribute-error/blob/master/spec/models/business_spec.rb#L11-L17) two tests demonstrate the issue.

```bash
λ bundle exec rspec
F.

Failures:

  1) Business when silly things happen does not work
     Failure/Error: matching_ids = (internal_ips.concat(external_ips)).uniq

     ActiveModel::MissingAttributeError:
       missing attribute: computer_id
     # ./app/models/agent.rb:8:in `block in <class:Agent>'
     # ./spec/models/business_spec.rb:12:in `block (3 levels) in <top (required)>'

Finished in 0.05113 seconds (files took 1.37 seconds to load)
2 examples, 1 failure

Failed examples:

rspec ./spec/models/business_spec.rb:11 # Business when silly things happen does not work
```

The below code demonstrates the error. It seems to only occur when you use `includes`.

```ruby
class Agent < ActiveRecord::Base
  belongs_to :computer
  scope :by_external_ip, ->(ips) { joins(:computer).where('computers.ip_external IN (?)', ips) }
  scope :by_internal_ip, ->(ips) { joins(computer: :nics).where('nics.ip IN (?)', ips) }
  scope :by_ip_with_failure, ->(ips) do
    internal_ips = by_internal_ip(ips).select(:id)
    external_ips = by_external_ip(ips).select(:id)
    matching_ids = (internal_ips.concat(external_ips)).uniq
    where { id.in(matching_ids) }
  end

  scope :by_ip, ->(ips) do
    internal_ips = by_internal_ip(ips).pluck(:id)
    external_ips = by_external_ip(ips).pluck(:id)
    matching_ids = (internal_ips.concat(external_ips)).uniq
    where { id.in(matching_ids) }
  end
end
```

The implementation in by_ip uses pluck which seems to work because it's returning an Array of ids. When using select, I believe it's returning a CollectionProxy. Our original implementation was using the `+` operation like so.

```ruby
    matching_ids = (internal_ips + external_ips).uniq
```

After looking at ri for Array it seemed to suggest that + is an alias for concat which lead to looking at this code: https://github.com/rails/rails/blob/4-2-5/activerecord/lib/active_record/associations/collection_proxy.rb#L969-L973

We can use pluck, since it's probably a better solution anyways. But I am curious as to why the behaviour is that different between using pluck and select.

:heart:

**Comment by egilburg** [comment]
`select` returns a set of active records but only with specified fields loading (eg. `"SELECT id FROM ..."` as opposed to `"SELECT * FROM ..."`). It's not returning the actual fields. You can do `by_internal_ips(ips).select(:id).map(&:id)`, or `by_internal_ips(ips).pluck(&:id)`
