### ISSUE TITLE
Options are not propagated correctly

### ISSUE THREAD

**Issue by ablancag** [rails/rails#23741]
Hi.

Looking at line 93 of lib/active_support/json/encoding.rb, I see that the call to "as_json" is missing the options in the context. As a reference, the same call in method encode(value) is done with the options.

This is causing my custom serialization to be incorrect: I'm serializing an object nested in another one. I'm manually instantiating (.new(object, options)) the serializer for the internal data.

Could you please validate my understanding?

Regards,

Alex B.

**Comment by maclover7** [comment]
Can you create an executable test script using one of the templates [here](https://github.com/rails/rails/tree/master/guides/bug_report_templates), that would demonstrate the problem you are seeing?

**Comment by ablancag** [comment]
Where can I find instructions on how to?

The thing is, as of now, it's being called with an empty default options. So, it's already using given parameter. 

I'm using by the way, Active Model Serializers.

**Comment by maclover7** [comment]
Unless you provide a sample application or a test script using one of the templates linked above, we can't help you in determining if this is a bug or not. :-(

**Comment by ablancag** [comment]
Can you point me to the templates reference, please?

I'll try to build something. I do know the scenario.

**Comment by ablancag** [comment]
By reference I mean a wiki, for example, that can guide me around your templates.

Regards,

**Comment by maclover7** [comment]
Here's a link to some general information --> http://edgeguides.rubyonrails.org/contributing_to_ruby_on_rails.html#reporting-an-issue

**Comment by ablancag** [comment]
Excellent.

Thanks. I'll try to build something up.

Don't close this yet.

**Comment by ablancag** [comment]
Here's the test script. Please do let me know of any questions. 
[action_controller_gem.rb.zip](https://github.com/rails/rails/files/135237/action_controller_gem.rb.zip)

**Comment by ablancag** [comment]
Check my comments in the script please.

**Comment by ablancag** [comment]
Forgot to mention: there's another way of chaining the serialization that works, so I do have a workaround. I believe this other path (the own shown in the script) should work too.

**Comment by maclover7** [comment]
Based on your test script, I'd say it'd be more useful to open up a ticket at https://github.com/rails-api/active_model_serializers.
