### ISSUE TITLE
[Guides] Misplacement of Dynamic Finders 'Tip' block in active_record_querying guide

### ISSUE THREAD

**Issue by bvsatyaram** [rails/rails#23749]
![rails guides issue](https://cloud.githubusercontent.com/assets/166072/13135507/2c078b92-d637-11e5-844e-849638ab7ab5.png)

**Comment by bvsatyaram** [comment]
Never mind, this is in the stable version of the guides, but not in the edge guides.
I am closing the issue. Sorry to bother.

**Comment by vipulnsward** [comment]
Thanks for confirming!
