### ISSUE TITLE
Why it's possible to invoke channel actions after subscription was rejected?

### ISSUE THREAD

**Issue by nateless** [rails/rails#23757]
Let's assume we called `reject` in `channel#subscribed`, then client ignores rejection and makes a call to some action in that channel, which is being successfully processed ignoring the fact that it was rejected. So each action should check for `subscription_rejected?` ?

**Comment by maclover7** [comment]
To summarize, you're saying that:
- Incoming connection has been `rejected` in the `subscribed` method on your channel
- Client ignores this, and continues to act and process events normally

Is this a correct summary?

**Comment by nateless** [comment]
Yea, here's code example:

```
class PostChannel < ApplicationCable::Channel
	def subscribed
		reject if user_from_blocked_countries?
	end

	def post(data)
		return if subscription_rejected? # need to check for rejection
		PostService.new(data, self).post
	end
end
```

**Comment by maclover7** [comment]
Working on a solution for this.

**Comment by maclover7** [comment]
Opened PR #23759.
