### ISSUE TITLE
Error page in development

### ISSUE THREAD

**Issue by dvisockas** [rails/rails#23758]
Hey,

I've been developing a new app that is using Rails 5beta2 and one thing I am missing the most is the error screen. Where errors were shown, like migrations missing or any other error. It just outputs a simple text "Internal server error" and then I need to go to the terminal and lookup the error.

Will it be back? :)

**Comment by rafaelfranca** [comment]
How can we reproduce this problem? I just created a new application and it show the correct error page.

**Comment by dvisockas** [comment]
Aaah, sorry, that I didn't mention the main point. The project was created using `rails new` and then bumped to version 5. Is this expected?

**Comment by rafaelfranca** [comment]
No it is not.  Can you please provide a sample application that reproduces the error?

**Comment by dvisockas** [comment]
I just copied a directory and removed all project-specific files.

There is only one problem if you want to try it out, you'll have to change the database.yml that somehow isn't in .gitignore :(

Link to the repo: https://github.com/dvisockas/no-error-page-sample

**Comment by mdoza** [comment]
Your issue appears to be the raven-ruby gem. Replace the following in your Gemfile and your app should be working as desired:

`gem "raven-ruby", github: "getsentry/raven-ruby"`

**Comment by dvisockas** [comment]
Thank you, guys :heart:
