### ISSUE TITLE
Add `null_store` to `test.rb`

### ISSUE THREAD

**Issue by maletor** [rails/rails#23763]
> By default, caching is only enabled in your production environment.

I have found this statement in the [guides](http://edgeguides.rubyonrails.org/caching_with_rails.html) but it is false. 

Yes, it is true, in Rails master `development.rb` sets the strategy to `null_store` **however** `test.rb` contains no such configuration. Therefore, it defaults to `file_store` if the `tmp/cache` directory is present and `memory_store` if it is not.

Ideally, should the documentation be changed or should `null_store` be added to `test.rb`?

**Comment by rafaelfranca** [comment]
Please open a PR updating the documentation. But be aware that that sentence is talking about Action Controller cache strategies and it is indeed only enabled in production.
