### ISSUE TITLE
Params not processed properly when content type is "application/vnd.api+json" as of c4d90b7 

### ISSUE THREAD

**Issue by rthbound** [rails/rails#23766]
Oddly, [this bug report script](https://gist.github.com/rthbound/09463c89a243d00a5ab8) does not fail, even though "application/vnd.api+json" is not registered as a mime type. I really hoped to produce a failure with the bug report template.

I can show this bug by generating a fresh rails app as follows:
```
mkdir recreate_bug
echo "2.3.0" >> recreate_bug/.ruby-version
cd recreate_bug
echo "source 'https://rubygems.org'" >> Gemfile
echo "gem 'rails', github: 'rails/rails'"  >> Gemfile
gem install bundler --no-ri --no-rdoc
bundle
rails new --api --force .
sed -i "s/gem 'rails.*$/gem 'rails', github: 'rails\/rails'/g" Gemfile
bundle
spring stop
rails g scaffold Bug
rake db:migrate
echo "Mime::Type.unregister :json" >> config/initializers/mime_types.rb
echo "Mime::Type.register 'application/json', :json, %w( text/x-json application/jsonrequest application/vnd.api+json )" >> config/initializers/mime_types.rb
rails s
```

Now just curl:
```
curl -XPOST -H 'Content-Type: application/vnd.api+json' http://localhost:3000/bugs -d '{"maybe_a_bug": true}'
```

Your server window should show that it wasn't processed properly:
```
Processing by BugsController#create as */*
  Parameters: {"bug"=>{}}
```

I pushed an app created this way (includes a test case) to: https://github.com/rthbound/una-otra ...

**Comment by rthbound** [comment]
I did try recreating this with a bug report template. The thing passed my test case even though `application/vnd.api+json` isn't registered as a mime type: https://gist.github.com/rthbound/09463c89a243d00a5ab8

**Comment by rthbound** [comment]
In rack's [Rack::Request#POST](https://github.com/rack/rack/blob/master/lib/rack/request.rb#L346-L369) method, execution is running into the `else` and is returning `{}` as the "data received in the post body". If I force it into the part that runs when `form_data? || parseable_data?` returns true, the params parse.

Without intervention, `parseable_data?` returns false because `application/json` is not in ` ["multipart/related", "multipart/mixed"]`

> [11] pry(#<ActionDispatch::Request>)> PARSEABLE_DATA_MEDIA_TYPES
> => ["multipart/related", "multipart/mixed"]
> [12] pry(#<ActionDispatch::Request>)> media_type
> => "application/json"

**Comment by prathamesh-sonpatki** [comment]
On Rails 4.2.5.1, we get the passed data in params.

```
Started POST "/bugs" for ::1 at 2016-02-20 10:59:45 +0530
  ActiveRecord::SchemaMigration Load (0.1ms)  SELECT "schema_migrations".* FROM "schema_migrations"
Processing by BugsController#create as */*
  Parameters: {"maybe_a_bug"=>true, "bug"=>{}}
```

will be debugging more.

**Comment by meinac** [comment]
I've found the problem and created a pr for this with test coverage.

**Comment by rthbound** [comment]
@meinac I've confirmed your fix is in fact a fix :) thank you

**Comment by rafaelfranca** [comment]
Fixed by @meinac PR. Thank you for reporting.
