### ISSUE TITLE
Could not find gem 'actioncable' in git://github.com/rails/actioncable.git (at master@58fdac9).

### ISSUE THREAD

**Issue by rda1902** [rails/rails#23768]
When i try install actioncable gem, i get bundle error
Could not find gem 'actioncable' in git://github.com/rails/actioncable.git (at master@58fdac9).
Source does not contain any versions of 'actioncable'

my Gemfile
```
gem 'rails', '4.2.5.1'
gem 'actioncable', github: 'rails/actioncable'
gem 'puma'
```

Two month ago I have successfully used this combination.

**Comment by rafaelfranca** [comment]
Action cable is not integrated inside Rails. Please read the README on that repository https://github.com/rails/actioncable/blob/master/README.md

**Comment by rda1902** [comment]
This solved my problem
`gem 'actioncable', github: 'rails/actioncable', branch: 'archive'`
