### ISSUE TITLE
Test case use RAW_POST_DATA but it is not used anywhere

### ISSUE THREAD

**Issue by leonardoprg** [rails/rails#23779]
Hello guys,

Using rspec-rails on my project, I noticed a strange behavior, 

When I make a post sending a hash object like:

`{id: 1}`

the number 1 will be converted to String.

It doesnt happens with Minitest only on RSpec.

please consider this script:

[https://gist.github.com/leonardoprg/d667920604659294b42f](https://gist.github.com/leonardoprg/d667920604659294b42f)

If you guys take a look on the line 50, when using .to_json and sending a string as parameter to post method, it will works correctly.

Swimming in the code I noted that:

1. The problem is at `actionpack/lib/test_case.rb`
2. RSpec use the method post at [test_case.rb#L519](https://github.com/rails/rails/blob/4-2-stable/actionpack/lib/action_controller/test_case.rb#L519)

3. minitest doesn't use it.

The problem here is 
[test_case.rb#L598](https://github.com/rails/rails/blob/4-2-stable/actionpack/lib/action_controller/test_case.rb#L598
)

If RSpec try to send a string, it assume it will be a raw data (like an json object)  and set it to request env `RAW_POST_DATA`, Which is correctly.
but, the code that take care with this env var, is a middleware at:
[params_parser.rb#L42](https://github.com/rails/rails/blob/4-2-stable/actionpack/lib/action_dispatch/middleware/params_parser.rb#L42)

and it is never called, because the method on test_case just call the controller method as an plain object.

I will open a PR to correct this behaviour.

Regards,

**Comment by rafaelfranca** [comment]
See the liked PRs to the reason it was closed
