### ISSUE TITLE
STI with abstract base class not working

### ISSUE THREAD

**Issue by ravinggenius** [rails/rails#23783]
On Rails `v4.2.5.1` single table inheritance doesn't work when the base class is marked abstract. See failing code below:

```ruby
class CreateTables < ActiveRecord::Migration
  def change
    create_table :mapping_records do |t|
      t.string :type, null: false
      t.string :name, null: false
      t.timestamps null: false
    end
  end
end

class MappingRecord < ActiveRecord::Base
  self.abstract_class = true
end

class Attendee < MappingRecord
end

Attendee.table_name #=> "attendees"
Attendee.new.changes #=> {}
Attendee.all.to_sql #=> "SELECT \"attendees\".* FROM \"attendees\""
```

If I remove `self.abstract_class = true` from `MappingRecord`, everything works as expected.

```ruby
Attendee.table_name #=> "mapping_records"
Attendee.new.changes #=> {"type"=>[nil, "Attendee"]}
Attendee.all.to_sql #=> "SELECT \"mapping_records\".* FROM \"mapping_records\" WHERE \"mapping_records\".\"type\" IN ('Attendee')"
```

**Comment by matthewd** [comment]
This seems to be working as expected; STI only gets involved when multiple classes live in the same table.

**Comment by ravinggenius** [comment]
Sorry, I must have over-simplified my example. In my real code, I have multiple classes, and it definitely doesn't work.

**Comment by jrochkind** [comment]
`abstract_class = true` is actually telling ActiveRecord _not_ to use Single-Table Inheritance, but to put all subclasses in their own tables.  The name is a bit confusing, but it is incompatible with single-table inheritance, if you want single-table inheritance do _not_ set abstract_class. Set abstract_class if and only if you _don't_ want STI.
