### ISSUE TITLE
AR class level scopes leaking into associations defined on other AR classes

### ISSUE THREAD

**Issue by Enders** [rails/rails#23798]
Hi there!

I was working on a Rails 4.2.5.1 app and I found a surprising behavior. I think it's fair to call it a bug or at least an undocumented surprising behavior. It's a bit difficult to explain, but easy to showcase, so I have setup below a basic test case, for rails master (Rails 5 beta), and the issue still exists. I'm not sure when this was introduced, I have been using Rails for many years and it's the first time I encounter this, but it could just be dumb luck.

Please compare the two test cases, one is passing, one is failing. When looking at the SQL for the failing case:

```
Stuff Load (0.1ms)  SELECT  "stuffs".* FROM "stuffs" WHERE "stuffs"."public" = ? AND "stuffs"."user_id" = ? LIMIT ?  [["public", true], ["user_id", 2], ["LIMIT", 1]]
```

It's clear that the `public_stuff` scope has somehow leaked into the User.favorite_stuff association. I do not think this is intended/expected and can obviously lead to very hard to trace bugs.  

Note that if you change the methods just a bit, and instead give `user.favorite_stuff.category` as a parameter to the `Stuff.similar_stuffs`, then it obviously work, just like when you preload the `favorite_stuff` association as in the baseline test.

Thanks and I apologize if this has been documented somewhere and I just missed the memo :) 

```ruby
begin
  require 'bundler/inline'
rescue LoadError => e
  $stderr.puts 'Bundler version 1.10 or later is required. Please update your Bundler'
  raise e
end

gemfile(true) do
  source 'https://rubygems.org'
  gem 'rails', github: 'rails/rails'
  gem 'sqlite3'
end

require 'active_record'
require 'minitest/autorun'
require 'logger'

# This connection will do for database-independent bug reports.
ActiveRecord::Base.establish_connection(adapter: 'sqlite3', database: ':memory:')
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :users, force: true  do |t|
    t.integer :favorite_stuff_id
  end

  create_table :stuffs, force: true  do |t|
    t.integer :user_id
    t.boolean :public
    t.integer :category
  end
end

class User < ActiveRecord::Base
  has_many :stuffs
  has_one :favorite_stuff, class_name: "Stuff"
end

class Stuff < ActiveRecord::Base
  belongs_to :user

  enum category: [:useful, :useless, :undecided]

  def self.public_stuff
    where public: true
  end

  #This is where the magic happens
  #as_user.favorite_stuff should load the correct object regardless of where it's called...
  #but if you are currently chaining scopes of Stuff, it'll leak into the SQL Load query and it may lead
  #to not being able to retrieve that association on the object.
  def self.similar_stuffs(as_user)
    where(category: as_user.favorite_stuff.category)
  end
end

class BugTest < Minitest::Test
  def setup
    @favorite_stuff = Stuff.create! public: false, category: :useful
    @user = User.create! favorite_stuff: @favorite_stuff
    @other_stuff = Stuff.create! public: true, category: :useful
  end

  def test_association_stuff_failing
    #This doesn't work, user.favorite_stuff needs a SQL load and the `public_stuff` scope
    #interfers (this specific user favorite_stuff is private).
    assert_equal Stuff.public_stuff.similar_stuffs(User.find(@user.id)), [@other_stuff]
  end

  def test_association_stuff_baseline
    #This works, because @user.favorite_stuff association is already loaded
    assert_equal Stuff.public_stuff.similar_stuffs(@user), [@other_stuff]
  end
end
```

**Comment by maclover7** [comment]
Confirmed on master, that's pretty weird that the `Stuff.similar_stuffs` would bleed into the `User.find()`.

**Comment by pixeltrix** [comment]
This is a known effect of how scopes work - they get applied as the current scope to the class. To work around this you can use `unscoped` like this:

``` ruby
def self.similar_stuff(user)
  unscoped { where(category: user.favourite_stuff.category) }
end
```

Whilst this is a little counter-intuitive I think the feeling is that trying to change it now would break too many applications. There's a bunch of previous issues about this behaviour if you want some background - #14003 is a good starting point and has links to many other issues and PRs.
