### ISSUE TITLE
How to validate saved record?

### ISSUE THREAD

**Issue by alpaca-tc** [rails/rails#23790]
In Rails5, a few of validations check [`record.persisted?`](https://github.com/rails/rails/blob/2df891dccdcfbdfb176c55297589712ac379f87d/activemodel/lib/active_model/validator.rb#L167) to skip validation.
After save, `record.valid?` returns `true` even if the context is changed.

In Rails4.2, it returns `false`.

Is this intentional?

```
begin
  require 'bundler/inline'
rescue LoadError
  $stderr.puts 'Bundler version 1.10 or later is required. Please update your Bundler'
  raise
end

gemfile(true) do
  source 'https://rubygems.org'
  # Activate the gem you are reporting the issue against.
  gem 'activerecord', '5.0.0.beta2'
  gem 'sqlite3'
end

require 'active_record'
require 'minitest/autorun'
require 'logger'

# Ensure backward compatibility with Minitest 4
Minitest::Test = MiniTest::Unit::TestCase unless defined?(Minitest::Test)

# This connection will do for database-independent bug reports.
ActiveRecord::Base.establish_connection(adapter: 'sqlite3', database: ':memory:')
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :posts, force: true do |t|
    t.string :body
  end
end

class Post < ActiveRecord::Base; end

class BugTest < Minitest::Test
  def test_validates_presence_on_context
    Post.validates_presence_of(:body, on: :required_name)
    post = Post.new
    post.save!

    assert post.invalid?(:required_name) # Fail
  end
end
```

**Comment by prathamesh-sonpatki** [comment]
``` ruby
!record.persisted? || record.changed? || record.marked_for_destruction?
```

`record.changed?` will get used for persisted records right?  

Please use the bug report template https://github.com/rails/rails/blob/master/guides/bug_report_templates/active_record_gem.rb and upload it here with test case to reproduce the issue.

Thanks.

**Comment by alpaca-tc** [comment]
Thank you for replying.
I.c
maybe it is intentional.

**Comment by alpaca-tc** [comment]
IMO, `valid?` should always check saved record.

```
class User < ActiveRecord::Base
  validates :email, presence: true, on: :admin
end

user = User.create! # without email
user.valid?(:admin) #=> expected `false` but `true`
```

@eileencodes  Is this intentional?

**Comment by rrsilver** [comment]
IMO that doesn't make any sense to validate persisted records, since you only want to have valid values on database. If you need a way to validate the data afterwards, it's better to put on a queue and schedule a job.

**Comment by eileencodes** [comment]
No it's not intentional. I'll work on getting this fixed up. Thanks!

**Comment by eileencodes** [comment]
Ok I fixed this by reverting the original change because this is a big issue and not worth blocking the RC for. Thanks for pointing it out!
