### ISSUE TITLE
db:structure:load silently fails on SQL error

### ISSUE THREAD

**Issue by thesmart** [rails/rails#23818]
While I love psql for fun and profit, it fails without warning in Rails.  When loading a file using -f, psql returns a zero code (aka: no error) on error, preventing pstgresql_database_tasks from signaling that there is an error.  This hides bad things in structure.sql.

https://github.com/rails/rails/blame/v4.2.5/activerecord/lib/active_record/tasks/postgresql_database_tasks.rb#L62

That command needs to include `-v ON_ERROR_STOP=1` as an argument to psql so that the db rake tasks using psql with the -f flag will fail on non-zero return codes.

**Comment by arthurnn** [comment]
@thesmart do you wanna try to implement that and send a PR? cc me on it, so i will take a look.
Thanks
