### ISSUE TITLE
scope in routes

### ISSUE THREAD

**Issue by ulugbekov** [rails/rails#23817]
Does this generates correct path?
Generated: 
  /admin/api/users/:user_id/profile(.:format) 
I was expecting:
  /admin/users/:user_id/api/profile(.:format)

namespace :admin do
    resources :users do
      scope :api do
        resources :profile
      end
    end
  end

**Comment by mdoza** [comment]
@ulugbekov try using nested :smile:

```ruby
namespace :admin do
  resources :users do
    nested do
      scope :api do
        resources :profile
      end
    end
  end
end
```

**Comment by ulugbekov** [comment]
Hey thanks for advice,

But I am not looking for solution. I am just wondering is that a bug in rails.
If I change scope to namespace, routes are correctly configured. 
I wonder why scope changes routes. It should be very similar to namespace logic with exceptions on path helpers and controller reference.

**Comment by mdoza** [comment]
@ulugbekov not a bug, when you use the `resources` method the `nested` block is automatically used.
