### ISSUE TITLE
has_many through a self referential join on single table inheritance does not produce correct SQL

### ISSUE THREAD

**Issue by xcskier56** [rails/rails#23812]
I'm attempting to create a has_many through on a self referential single table inheritance. When active record creates the query, it aliases the tables on the `INNER JOIN`, but does not alias the table on the `AND` statement. This leads the query to not return anything. 

Heres a git to [reproduce](https://gist.github.com/xcskier56/f30784e4d07b1447d7ea).
Using activerecord 4.2

The issue can be seen below in the 2 `IN` clause. The first `IN` should be aliased to `user_challenge_enrollments_team_challenge_enrollments_join.type` instead of `challenge_enrollments.type`

```
SELECT "challenge_enrollments".* FROM "challenge_enrollments" 
  INNER JOIN "challenge_enrollments" "user_challenge_enrollments_team_challenge_enrollments_join" 
    ON "challenge_enrollments"."id" = "user_challenge_enrollments_team_challenge_enrollments_join"."team_challenge_enrollment_id" 
  WHERE "challenge_enrollments"."type" IN ('UserChallengeEnrollment') 
    AND "challenge_enrollments"."type" IN ('TeamChallengeEnrollment') 
    AND "user_challenge_enrollments_team_challenge_enrollments_join"."enrollee_id" = 1
```

**Comment by maclover7** [comment]
Does this error appear on master?

**Comment by xcskier56** [comment]
No it doesn't appear to be broken on master. The difference is in the sql output by the two.

Master (working):

    SELECT "challenge_enrollments".* FROM "challenge_enrollments" 
      INNER JOIN "challenge_enrollments" "user_challenge_enrollments_team_challenge_enrollments" 
        ON "challenge_enrollments"."id" = "user_challenge_enrollments_team_challenge_enrollments"."team_challenge_enrollment_id" 
      WHERE "challenge_enrollments"."type" IN ('TeamChallengeEnrollment') 
      AND "user_challenge_enrollments_team_challenge_enrollments"."enrollee_id" = 1

4.2 (not working):

    SELECT "challenge_enrollments".* FROM "challenge_enrollments" 
      INNER JOIN "challenge_enrollments" "user_challenge_enrollments_team_challenge_enrollments_join" 
        ON "challenge_enrollments"."id" = "user_challenge_enrollments_team_challenge_enrollments_join"."team_challenge_enrollment_id" 
      WHERE "challenge_enrollments"."type" IN ('UserChallengeEnrollment') 
        AND "challenge_enrollments"."type" IN ('TeamChallengeEnrollment') 
        AND "user_challenge_enrollments_team_challenge_enrollments_join"."enrollee_id" = 1

The SQL from master does not have the first statement `challenge_enrollments.type IN ('UserChallengeEnrollment')`
