### ISSUE TITLE
Rails 5 Strong Parameters

### ISSUE THREAD

**Issue by ralphking** [rails/rails#23823]
It seems using a HABTM relationship, strong parameters will not allow an array of ids.

For instance with the following: 

`params.require(:request).permit(:sort_code, :number_cheques, :number_books, :start_cheque, :sent, :batch, { account_ids: [] } )`

... I am getting an unpermitted parameter 'account_ids' error in the controller and it won't save.

I can brute force it with 

`params.require(:request).permit!()`

... and it works fine, which tells me that the rest of the code (forms etc) is working fine. I've searched the issues and can't seem to find anything. Wondering if anyone else is having the same problem, or there has been a syntax change that is not showing in the edge docs yet?

**Comment by maclover7** [comment]
Can you create an executable test script using one of the templates [here](https://github.com/rails/rails/tree/master/guides/bug_report_templates), that would demonstrate the problem you are seeing?

**Comment by ralphking** [comment]
Sorry, close this. My brain is fried today.
