### ISSUE TITLE
AC::Parameters#inspect doesn’t reveal what’s permitted

### ISSUE THREAD

**Issue by bquorning** [rails/rails#23822]
```rb
a = ActionController::Parameters.new(foo: 'bar')
#=> <ActionController::Parameters {"foo"=>"bar"}>
b = ActionController::Parameters.new(foo: 'bar').permit(:foo)
#=> <ActionController::Parameters {"foo"=>"bar"}>
a == b
#=> false
a.inspect == b.inspect
#=> true
```
This makes it hard to debug failing specs (here, a snippet from RSpec output):

```
expected: (<ActionController::Parameters {foo: "bar"}>)
     got: (<ActionController::Parameters {foo: "bar"}>)
```

**Comment by rafaelfranca** [comment]
Why are you asserting that two parameters are equal? You should be using `to_h` and comparing with a normal hash.

`expect(params.to_h).to eq foo: 'bar'`

**Comment by bquorning** [comment]
In a typical controller spec, I might call:
```rb
expect(article).to have_received(:update_attributes).with(
  ActionController::Parameters.new(foo: 42).permit!
)
```
It wasn't quite as ugly back when I could just pass a Hash to `with`.

**Comment by rafaelfranca** [comment]
I see. So yeah, make sense to fix inspect to show the permitted flag.
