### ISSUE TITLE
Eager loading nested objects with conditions not working as expected, duplicates objects

### ISSUE THREAD

**Issue by rthbound** [rails/rails#23832]
Queries like `Parent.includes(:kiddos).where(kiddos: { gender: ["F", "MF"] })` and `Parent.includes(:kiddos).joins(:kiddos).where(kiddos: { gender: ["F", "MF"] })` both will result in duplicate objects in the included relation.

Reproduction: https://gist.github.com/rthbound/733e8503891f756ab3de

**EDIT to add SQL output**
*#joins sql*:
```sql
SELECT "parents"."id" AS t0_r0, "kiddos"."id" AS t1_r0, "kiddos"."parent_id" AS t1_r1, "kiddos"."gender" AS t1_r2 FROM "parents" INNER JOIN "kiddos" ON "kiddos"."parent_id" = "parents"."id" WHERE "kiddos"."gender" IN ('F', 'MF')
```

*without #joins sql*:
```sql
SELECT "parents"."id" AS t0_r0, "kiddos"."id" AS t1_r0, "kiddos"."parent_id" AS t1_r1, "kiddos"."gender" AS t1_r2 FROM "parents" LEFT OUTER JOIN "kiddos" ON "kiddos"."parent_id" = "parents"."id" WHERE "kiddos"."gender" IN ('F', 'MF')
```

**Comment by chashmeetsingh** [comment]
can u give a sample for the code run and output
Also check if there are multiple entries in your tables

**Comment by rthbound** [comment]
@chashmeetsingh what do you mean? That information is all clearly provided in the reproduction script above. Just copy the script, be sure you're running ruby 2.3.0, and run the script with `ruby the_script.rb`.

**Comment by chashmeetsingh** [comment]
check this http://pastebin.com/ejsad3av

**Comment by rthbound** [comment]
@chashmeetsingh you're right. There's no problem with eager loading, it's just that the behavior of `#count` there is a bit unexpected.

```
query_result.kiddos.length == query_result.kiddos.count
# SQL: SELECT COUNT(*) FROM "kiddos" WHERE "kiddos"."parent_id" = ?  [["parent_id", 1]]
#=> false
```

This behaves the same now on edge as it does in the latest 4.1.13 and 4.2.5 releases.

@maclover7 I think we can close this issue, but can you comment as to whether an issue should be opened regarding the behavior of `#count` here?

/cc @matthewd

**Comment by chashmeetsingh** [comment]
Yes it would be great to here on the behaviour of count as in the sample file  http://pastebin.com/ejsad3av @matthewd
