### ISSUE TITLE
JSON.pretty_generate throws a TypeError when there is a BigDecimal object as a value

### ISSUE THREAD

**Issue by AdnanTheExcellent** [rails/rails#23839]
As the title states, JSON.pretty_generate throws a TypeError when there is a BigDecimal object as a value. This used to work in ruby 2.0 and rails 4.0 before upgrading in development.

Example console log of how to replicate:

```
[17] pry(main)> hash = {"x" => BigDecimal('50.0')}
=> {"x"=>#<BigDecimal:1befe50,'0.5E2',9(18)>}
[18] pry(main)> JSON.pretty_generate(hash)
TypeError: wrong argument type Float (expected String)
from /home/adnan/.rvm/gems/ruby-2.3.0/gems/activesupport-4.2.5/lib/active_support/core_ext/object/json.rb:34:in `to_json'
[19] pry(main)> hash.to_json
=> "{\"x\":50.0}"
```

Not sure if this is a ruby 2.3.0 bug or a rails bug. Either way, this definitely seems to be a bug.

**Comment by Edouard-chin** [comment]
Can't reproduce the bug using either ruby 2.2.4 or ruby 2.3.0 in a irb shell, I also tried using a rails 4 and rails 5 console
```shell
vagrant@vagrant ~ % ruby -v
ruby 2.3.0p0 (2015-12-25 revision 53290) [x86_64-linux]
vagrant@vagrant ~ % irb
irb(main):001:0> require 'bigdecimal'
=> true
irb(main):002:0> require 'json'
=> true
irb(main):003:0> hash = {"x" => BigDecimal('50.0')}
=> {"x"=>#<BigDecimal:7f72678c3260,'0.5E2',9(18)>}
irb(main):004:0> JSON.pretty_generate(hash)
=> "{\n  \"x\": \"0.5E2\"\n}"
```

Could you post the reproduction steps?

**Comment by chashmeetsingh** [comment]
Seems to work on ruby 2.2.3 and rails 4.2.5.1

**Comment by AdnanTheExcellent** [comment]
OK, i'm going to see if its possibly some gem i have that's causing it. Will close for now until i investigate and find the problem.
