### ISSUE TITLE
Relation#include? loads all and delegates to the array; should do exists? as associations do

### ISSUE THREAD

**Issue by bughit** [rails/rails#23831]
CollectionAssociation#include?
```ruby
      def include?(record)
        if record.is_a?(reflection.klass)
          if record.new_record?
            include_in_memory?(record)
          else
            loaded? ? target.include?(record) : scope.exists?(record.id)
          end
        else
          false
        end
      end
```

**Comment by maclover7** [comment]
Can you please provide a description of the problem you are trying to solve?

**Comment by bughit** [comment]
The problem of `Relation#include?` needless loading the relation just to check for membership.  This problem was already solved for associations.

There is of course a workaround (`#exists?`) but `#include?` is the canonical ruby/rails way to check for membership, so it should work as well as `#exists?`

**Comment by maclover7** [comment]
Can you create an executable test script using one of the templates [here](https://github.com/rails/rails/tree/master/guides/bug_report_templates), that would demonstrate the problem you are seeing?

**Comment by bughit** [comment]
that `Relation#include?` loads the relation is not a controversial claim and it doe not require a test, just one line:

`ActiveRecord::Relation.instance_method(:include?).source_location`

points to line 46 of `lib/active_record/relation/delegation.rb` which is
 
```ruby
delegate :to_xml, :to_yaml, :length, :collect, :map, :each, :all?, :include?, :to_ary, :join, to: :to_a
```
It delegates to_a, which loads the relation.

**Comment by rafaelfranca** [comment]
Thank you so much for the issue but we don't take feature request on the issue tracker. We recommend you to try to implement the feature and send us a pull request or if you are in doubt if the feature will be accepts ask in Rails Core mailing list for feedback.

**Comment by bughit** [comment]
You don't consider bad performance a bug?  Calling `Relation#include?` without potentially exhausting memory (needlessly) is feature?

**Comment by rafaelfranca** [comment]
It is a change in the behavior, so yeah, it is a feature. Unless it had a regression. In that case it is a bug.

**Comment by bughit** [comment]
If include? crashed with say an ArgumentError, it would be a bug.  And the change in behavior from crashing to returning the result would be a bug fix. 

But if it crashes with a NoMemoryError which it caused and could easily avoid, that's not a bug.  And the change in behavior from crashing to returning the result would be a feature.

Ok, I think I got it.
