### ISSUE TITLE
(erb) .rb generator files should be renamed to .rb.erb

### ISSUE THREAD

**Issue by kares** [rails/rails#23847]
assuming they do not contain valid ruby code they **should not be named .rb**
this would not only be cleaner but allow tools such as Warbler pre-compiling .rb files [without hustle](https://github.com/jruby/warbler/issues/287)

each sub-gem seems to have these under _lib/rails/generators_ e.g. with _active_record_ : 

https://github.com/rails/rails/tree/master/activerecord/lib/rails/generators/active_record/model/templates

_lib/rails/generators/active_record/model/templates/model.rb_ -> **.../model.rb.erb**
_lib/rails/generators/active_record/model/templates/module.rb_ -> **.../module.rb.erb**

proposing to rename those and update the related files, would this be acceptable by the team?

**Comment by chashmeetsingh** [comment]
.erb files are for layouts mate 
.rb for ruby 
I guess its a bad idea renaming them to .rb.erb

**Comment by rafaelfranca** [comment]
I don't see any problem of using the `tt` extension (which is the one
recommend by Thor) but first I want to understand better the problem. Which
problem does these files cause? Would not the same problem happen with erb?
Does it happen because people try to compile the entire lib folder?

**Comment by kares** [comment]
@chashmeetsingh thanks, but I thought that a file that doesn't load by Ruby "should not" be named `.rb`

@rafaelfranca assume you have a Rails app and you'd like to pre-compile your `.rb` files (including gems). a simplest way to do this is to walk all of the gemspec.lib `**/*.rb` files.
users of such scenarios (with Warbler under JRuby) bump into an issue with some `.rb` files not being "really" Ruby and thus require careful excludes ... all of these files are seen from Rails' gems (at least reports only mentioned them so far) and it seem that they might need to have the `.rb` extension

e.g. `lib/rails/generators/active_record/model/templates/model.rb` :
```
<% module_namespacing do -%>
module <%= class_path.map(&:camelize).join('::') %>
  def self.table_name_prefix
    '<%= namespaced? ? namespaced_class_path.join('_') : class_path.join('_') %>_'
  end
end
<% end -%>
```
have mostly used `.rb.erb` extension for such files, but I do not insist on having that extension

**Comment by rafaelfranca** [comment]
I see. I'm fine with renaming them.

**Comment by kares** [comment]
OK thanks, will setup a PR - this affects several gems. is it acceptable if I use the `.rb.erb` name then?

**Comment by rafaelfranca** [comment]
`.rb.tt` is our preferred way.

**Comment by kares** [comment]
OK
