### ISSUE TITLE
Inconsistent rounding of #sum method 

### ISSUE THREAD

**Issue by mengxi-liao** [rails/rails#23841]
Hi, we are doing a Rails upgrade from 4.2.2 to 4.2.5.1 which made several test cases fail. 

In one case, it failed because the rounding of the result is not correct. After some investigation, I found for some reason the following two lines of code return different results on Rails 4.2.5.1

```
(byebug) sum("CEIL(`activities`.quantity/60) * 60 / 3600 * `activities`.price").to_s
"58.81"
(byebug) sum("CEIL(`activities`.quantity/60) * 60 / 3600 * (`activities`.price)").to_s
"58.806"
```

The activities table only have one record with price 3.63 and quantity 16.19, the result should be 58.806

I try to run the generated sql and both return the correct result 58.806. How #sum handles rounding?

Thanks

**Comment by maclover7** [comment]
Can you create an executable test script using one of the templates [here](https://github.com/rails/rails/tree/master/guides/bug_report_templates), that would demonstrate the problem you are seeing?

**Comment by pixeltrix** [comment]
@mengxi-liao I assume that in 4.2.2 that the answer was `58.806` and in 4.2.5.1 it was `58.81`? If so then 0b94384 may be the cause but only if you are aliasing the result to the same name as a column with a scale of 2 - is this the case?

**Comment by chashmeetsingh** [comment]
You can use the round function to get accurate results

**Comment by mengxi-liao** [comment]
```
sum("16.25*`activities`.price").to_s
"150.96"
sum("16.251*`activities`.price").to_s
"150.97"
sum("16.251*(`activities`.price)").to_s
"150.97179"
sum("16.25*(`activities`.price)").to_s
"150.9625"
```

So the price column has a scale 2. The method looks for the scale of the column and rounds the result. I assume it's expected in the new version... But for any reason?

**Comment by pixeltrix** [comment]
@mengxi-liao interesting results - it seems like the pg adapter is returning the price column as the column type for the first two results and adding the parentheses around it changes it to decimal type without a scale. I wonder what happens when you explicitly cast the first number to various scales?

**Comment by mengxi-liao** [comment]
@pixeltrix Ok I could confirm this comes from [0b94384](https://github.com/rails/rails/commit/0b94384bef44535a408b034e44b90d08318e258a).

As I have patched the Decimal class back to the previous version...(Yes we need the behaviour that you guys think it is a bug). And the sum method returns consistent results now.

**Comment by pixeltrix** [comment]
@mengxi-liao I think the pg gem is returning the price column as the type for that column in the results even though it's been multiplied by a scalar value, so I'm not sure whether the bug is in Rails or with the pg gem. I'll have to do some more investigation.

**Comment by mengxi-liao** [comment]
@pixeltrix For pg gem are you talking about the gem supporting PostgreSQL? We are using Mysql as db so the gem should be mysql2 and the version is  0.3.18.

Having that said, I don't think the problem is from the gem. Since I try to run the query by ctiveRecord::Base.connection.execute and it returns the result without rounding for both with and without the brackets.

**Comment by pixeltrix** [comment]
@mengxi-liao sorry, just assume pg these days :smile:

Active Record will try to determine the column type returned from the adapter so I think the mysql2 gem is reporting the column as scale 2 - now that I know you're on MySQL I may have more luck in reproducing the problem.
