### ISSUE TITLE
"gem install rails" won't install bundler

### ISSUE THREAD

**Issue by afunix** [rails/rails#23848]
I'm trying to follow "Getting Started" guide ( http://guides.rubyonrails.org/getting_started.html ) and stuck in the very beginning.

I've create clean vagrant box with Ubuntu 15.10.
Installed sqlite and executed `sudo gem install rails`.

gem reported 27 packages installed, but it didn't install bundler.

So when I executed `rail new blog` it reported at the very end:
```
         run  bundle install
/usr/bin/ruby2.1: No such file or directory -- /usr/share/rubygems-integration/all/gems/bundler-1.10.6/bin/bundle (LoadError)
         run  bundle exec spring binstub --all
/usr/bin/ruby2.1: No such file or directory -- /usr/share/rubygems-integration/all/gems/bundler-1.10.6/bin/bundle (LoadError)
```

ruby 2.1.5p273 (2014-11-13) [x86_64-linux-gnu]
gem 2.2.2
Rails 4.2.5.1

[rails-bundler-console.txt](https://github.com/rails/rails/files/144010/rails-bundler-console.txt)

**Comment by afunix** [comment]
Btw, when I install bundler manually (`gem install bundler`) project generation still fails when trying to install native plugin for nokogiri due to lack of development tools (gcc, make, etc).
I believe it should be stated in the requirements of the tutorial that dev tools should be installed.

**Comment by sevenseacat** [comment]
That's odd... bundler is definitely a dependency of Rails.

https://github.com/rails/rails/blob/v4.2.5.1/rails.gemspec#L30

**Comment by pixeltrix** [comment]
@afunix looking at your console output it seems that rubygems thinks that bundler was already installed - perhaps it was corrupt or it's something to do with Ubuntu's packaging? Either way I don't think there's a bug here.

As for needing a compiler, I think adding it to that guide's section on assumptions would be useful if someone wants to make a PR.

**Comment by chashmeetsingh** [comment]
try installing bundler with sudo
sudo gem install bundler

**Comment by afunix** [comment]
@chashmeetsingh sure, I can install bundler with `sudo gem install bundler`.
Somehow it wasn't installed automatically when I executed `sudo gem install rails`. This is the problem number 1.
Not sure, maybe I've done something wrong. But again, I took a clean Ubuntu installation and just followed the tutorial. I expect that tutorial is something simple which anyone can follow without significant background in language or OS management.

Also even `sudo gem install bundler` won't work on clean Ubuntu installation, because `nokogiri` requires lots of OS packages.
For Ubuntu 15.10: `build-essential`, `patch`, `ruby-dev`, `zlib1g-dev`, `liblzma-dev`, `libsqlite3-dev`.
Tutorial does not state I need to install any dev package in requirements. Basically, it says ruby and sqlite3 are enough. 
This is the problem number 2.

**Comment by chashmeetsingh** [comment]
@afunix try this link http://railsapps.github.io/installrubyonrails-ubuntu.html

**Comment by aj07** [comment]
@afunix **gem install rails** will help you to get latest stable version of rails. As told by sevenseacat bundler is the dependency of rails.  However if you are still getting some problem then i think it might be some network error. Try to do it again. Also mention the way you followed for installing rails.

**Comment by afunix** [comment]
@aj07 I've tried several times and result is always the same.
I've attached console output with the specific commands and their output, so anyone can reproduce.


All, I've managed to install rails, it's not a rocket sience and I'm not looking for help here. 
This is a bug report with steps go reproduce, as I believe there is something wrong, that needs to be fixed or documented.

**Comment by chashmeetsingh** [comment]
@afunix tried the tutorial I gave?

**Comment by afunix** [comment]
@chashmeetsingh Yes, and found lots of issues there too. The first one installing rvm+ruby: GPG verification fails due to key not installed.
It doesn't specify to install development packages to build nokogiri too and there are strange things even in the workflow.

But this is another tutorial.

**Comment by chashmeetsingh** [comment]
Mate there is a link for the gpg link in the tutorial try that too

**Comment by sevenseacat** [comment]
@chashmeetsingh their point is that the official instructions in the Getting Started guide need to improved, not that they can't get it working by themselves.

**Comment by chashmeetsingh** [comment]
I tried the guide from the starting and it seems that bundler is installed automatically at the time of bundle install

**Comment by sevenseacat** [comment]
Without bundler installed, you cannot `bundle install` to begin with.

**Comment by chashmeetsingh** [comment]
gem install rails -v 5.0.0.beta3
Fetching: bundler-1.11.2.gem (100%)
Successfully installed bundler-1.11.2
Successfully installed rails-5.0.0.beta3
Parsing documentation for bundler-1.11.2
Installing ri documentation for bundler-1.11.2
Parsing documentation for rails-5.0.0.beta3
Done installing documentation for bundler, rails after 3 seconds
2 gems installed

it is installed

**Comment by rafaelfranca** [comment]
This seems like a problem in your environment. Closing since it is not a Rails bug.

Thank you so much for reporting it.

**Comment by fiftin** [comment]
I uninstalled bundler by apt: `sudo apt remove ruby-bundler`. In my case this helps.
