### ISSUE TITLE
Enable rails restart to work in development mode

### ISSUE THREAD

**Issue by rubys** [rails/rails#23855]
add `plugin :tmp_restart` to `config/puma.rb` to enable `rails restart` to work in development.

File to change: `railties/lib/rails/generators/rails/app/templates/config/puma.rb`.

**Comment by Eric-Guo** [comment]
@evanphx but seems not working on puma 3 now?

**Comment by rubys** [comment]
@Eric-Guo there definitely is a bug and both the rails and puma teams are looking into it.  For now, it only works if puma is started via `puma`, not `rails server`.

**Comment by Eric-Guo** [comment]
Thanks, I already see puma master revert [puma PR 884](https://github.com/puma/puma/pull/884), which cause this problem.

**Comment by Eric-Guo** [comment]
Oh, it's not relative with puma PR 884, but only windows path problem, propose [puma PR 905] (https://github.com/puma/puma/pull/905)
