### ISSUE TITLE
Adding a hot restart (no need to open new terminal)

### ISSUE THREAD

**Issue by chashmeetsingh** [rails/rails#23876]
just a suggestion can a hot restart be implemented 
by this there will be no use of opening another terminal 
just type restart in the present console where server is running 
and then it restarts no use of another terminal to execute this

**Comment by prathamesh-sonpatki** [comment]
@chashmeetsingh Thanks but we don't discuss feature requests on Github. Please use rails-core mailing list to suggest features.
