### ISSUE TITLE
CollectionProxy <</append/push unexpected behaviour

### ISSUE THREAD

**Issue by bluehallu** [rails/rails#23886]
Given A has_many B, will the following code trigger a database insertion?

`a << B.new`

The answer is that it depends on wether a is persisted or not. I'm unsure if this is intended or not but I can't seem to find anything mentioned in the documentation.

**Comment by maclover7** [comment]
Please use the mailing list or StackOverflow for questions/help, where a wider community will be able to help you. We reserve the issues tracker for issues only.

**Comment by bluehallu** [comment]
@maclover7 It's not a question nor a request for help. I don't think this is the intended behaviour.

**Comment by rafaelfranca** [comment]
Yes, it is. If autosave is enabled in the association it will have that behavior.

**Comment by bluehallu** [comment]
@rafaelfranca I can't find any reference on the docs that hints of that behaviour. Autosave says it will save associations when parent is saved, but in my example I'm never saving the parent. I'm not saying this is the wrong thing to do, just that nowhere in the docs is it explained.

**Comment by bluehallu** [comment]
@rafaelfranca I've managed to find a reference to this behaviour in the guides (though still no mention in the docs):

> When you assign an object to a has_many association, that object is automatically saved (in order to update its foreign key). If you assign multiple objects in one statement, then they are all saved.

> If the parent object (the one declaring the has_many association) is unsaved (that is, new_record? returns true) then the child objects are not saved when they are added. All unsaved members of the association will automatically be saved when the parent is saved.

Seems to have nothing to do with autosave.
