### ISSUE TITLE
Postgresql 9.5 breaking rake db:migrate

### ISSUE THREAD

**Issue by hahcho** [rails/rails#23882]
I have upgraded my postgresql to 9.5.1. Currently the `rake db:migrate` task breaks with error about the `pg_dump` command saying: `-i is an invalid option`. I saw that in postgres 9.5 `pg_dump` `-i` option was deprecated. I am using `3.2.19` version of the active-record gem but i see that even in the [current](https://github.com/rails/rails/blob/3-2-stable/activerecord/lib/active_record/railties/databases.rake#L428) stable branch this is still an issue.

Currently I "fixed" the issue by removing the option but I am not sure about the purpose that is serving.

**Comment by rafaelfranca** [comment]
Rails 3 is not supported anymore.

**Comment by dervus** [comment]
@rafaelfranca I can confirm this affects ActiveRecord 4.1.10 as well.
