### ISSUE TITLE
Rails 5.0.0.beta3 breaks sessions

### ISSUE THREAD

**Issue by jcoyne** [rails/rails#23884]
I'm still investigating how this happened, but the session code in my application worked with beta 1 and beta 2 as well as all versions of rails 4.  It stopped working at beta3:

https://travis-ci.org/projectblacklight/blacklight/jobs/111742726#L1897

More to follow.

**Comment by maclover7** [comment]
Could be related to #20851.

**Comment by jcoyne** [comment]
@maclover7 yes, I suspect it has something to do with 22db455dbe9c26fe6d723cac0758705d9943ea4b and storing hashes in the session.

I'm writing a test case.

**Comment by jcoyne** [comment]
Here's the problem.

```
session[:bar]
=> nil
(session[:bar] ||= {}).object_id
=> 70157799499460
session[:bar].object_id
=> 70157799499280
```

I don't know if this should be a bug, but it certainly was unexpected.

**Comment by jcoyne** [comment]
Maybe the `#[]=` method should return the correct value?

**Comment by matthewd** [comment]
We can't control the result of an assignment; ruby always returns the RHS.

**Comment by jcoyne** [comment]
@matthewd couldn't we change the return value from https://github.com/rails/rails/commit/22db455dbe9c26fe6d723cac0758705d9943ea4b#diff-0dd82841c763273551965fc0ea292a1bR113

**Comment by matthewd** [comment]
We can make it whatever we like; won't affect the result of your expression though

**Comment by jcoyne** [comment]
Ah, I see that now.

**Comment by jcoyne** [comment]
So #wontfix?

**Comment by kaspth** [comment]
#cantfix: "We can't control the result of an assignment"

**Comment by matthewd** [comment]
https://github.com/rails/rails/pull/20851#issuecomment-188530181

**Comment by tomprats** [comment]
@matthewd What's going on here? How come my pull request was reverted? It seems odd to put something into the session and expecting it to come back with the same object id. When you put something into a db, it wouldn't really come back with the same object id. I may be missing the point here though...
