### ISSUE TITLE
Nested routes: shallow: false doesn't work

### ISSUE THREAD

**Issue by bluehallu** [rails/rails#23890]
Defining the following routes:

```
Rails.application.routes.draw do
resources :stores, only: [:index], param: :code, shallow: true do
    resources :areas, only: [:index, :show] do
      resources :checks, only: [:show, :create], param: :date, shallow: false
    end
  end
end 
```

Results in the show action for check being:

>  /checks/:date

Essentially, `shallow: false` doesn't make any difference, even if defined both on areas and checks in my example. 

My use case: a check date is unique per area, and that's how I want to refer to them "Today's check for area X". The route I'd like to see would be:

> /areas/:id/checks/:date

There seems to be no way to do this as once you define a shallow route, everything nested under it (no matter how many levels) is shallow and there seems to be no way to disable the behaviour. I've worked around it by defining the route manually in the areas block like:

`get 'checks/:date', to: 'checks#show', as: 'check'`

But it would be nice to have native support!

**Comment by pixeltrix** [comment]
@bluehallu the only question is what would the non-shallow routes become - `store_area_checks_path` or `area_checks_path` ?

**Comment by bluehallu** [comment]
@pixeltrix since no store is involved, I would expect 

> area_checks_path

**Comment by waits** [comment]
I threw this together in #24405 if you want to try it out. I added tests for the cases listed above; can you think of any edge cases or other scenarios to test? It shouldn't break any existing functionality.
