### ISSUE TITLE
Activerecord first and last method get same result when order null column

### ISSUE THREAD

**Issue by TangMonk** [rails/rails#23896]
I have `qiandaos` records as following:

![image](https://cloud.githubusercontent.com/assets/3498786/13341156/0d5a41ae-dc71-11e5-8772-a61c7310a9a0.png)

Then I type following command in console:

```
> Qiandao.order(:position).last
> Qiandao.order(:position).first
```
But get same result , always first record with id 1, like following image:

![image](https://cloud.githubusercontent.com/assets/3498786/13341188/6ac81c4e-dc71-11e5-9dc0-f695538f8ca8.png)

But when I use array index to get last record will work:

```
> Qiandao.order(:position)[-1]
```

Image:
![image](https://cloud.githubusercontent.com/assets/3498786/13341202/847f2f7e-dc71-11e5-9966-207a8dd83049.png)

**Comment by rafaelfranca** [comment]
`last` revert the order `first` and gets the `first` record. So the query would be `ORDER BY position DESC LIMIT 1` that will give you the same record. As all values in that column is NULL, the first element in the query `ORDER BY position ASC LIMIT 1` is the same as in the query `ORDER BY position DESC LIMIT 1`.

It is an optimization that we have to do to avoid memory consuption but in some cases it doesn't work as expected as you can see. There is no way to fix it without reintroducing the memory problem.
