### ISSUE TITLE
Action cable bug

### ISSUE THREAD

**Issue by chashmeetsingh** [rails/rails#23891]
So i have made a chat app to check the functionality of action cable 
Now the bug is the function in the channel is never called until I explicitly call it from console like App.room.speak('yes') . After I run this from the console it is functional from the UI also . But otherwise nothing happens

Made a sample repo for the app https://github.com/chashmeetsingh/WebsocketSample
Please let me know if I made a mistake implementing this 
Thanks!

**Comment by maclover7** [comment]
Can you provide a little more information regarding the error you are seeing?

**Comment by chashmeetsingh** [comment]
I am not getting any error not in js neither in rails console 
just the thing that the speak function is not being called when I try to submit a form which is in the channel 
But if I explicitly run from browser console it works then it also starts working from the UI

**Comment by maclover7** [comment]
This is a CoffeeScript indentation issue -- you need to make [your code](https://github.com/chashmeetsingh/WebsocketSample/blob/master/app/assets/javascripts/channels/room.coffee#L14-L18) look [like this](https://github.com/maclover7/ac-test/blob/master/app/assets/javascripts/channels/room.coffee#L14-L18).

Currently, you have the DOM listener inside of the `speak` function.

**Comment by chashmeetsingh** [comment]
Indentation? 
Thanks ..

**Comment by maclover7** [comment]
I'm sorry -- to me this seems like the issue is not within Action Cable. If you are looking for a typed up version of the code from DHH's Action Cable video, I have a repo on GitHub which has that, available [here](https://github.com/maclover7/ac-test).

**Comment by chashmeetsingh** [comment]
getting timeout for that when using postgres should I raise an issue? @maclover7
