### ISSUE TITLE
Add config/ to spring + rails server restart watcher

### ISSUE THREAD

**Issue by dhh** [rails/rails#23908]
We have a bunch of files in config/ that say "# Be sure to restart your server when you modify this file". How about we just do that for people? We should have the power to watch directories now such that both Spring and rails server is restarted when these are touched.

**Comment by dhh** [comment]
@fxn Something that's realistic for 5.0 or should we bump to 5.1?

**Comment by fxn** [comment]
@dhh Too tight for RC due to my availability these days. If this could be a little addition post-RC (seems quite orthogonal, defining a new watcher probably), one option could be to postpone the decision until final is more imminent. Otherwise I'd say 5.1.

**Comment by chashmeetsingh** [comment]
is it possible to take input from the same terminal while a rails server is running ?
Also would it be good restarting the server again and again if any file is touched ?
@dhh

**Comment by st0012** [comment]
Is there anyone want to do this? I want to give it a shot 😀

**Comment by fxn** [comment]
@st0012 sure, go ahead!

**Comment by dhh** [comment]
@st0012 did you make any progress? If not, @fxn, do you want to take a stab?

**Comment by st0012** [comment]
Sorry that I haven't made any meaningful progress. But I agree with @chashmeetsingh's questions. Especially I can't find a way to passing server options elegantly. Maybe @fxn will have some ideas

**Comment by natetech333** [comment]
Since this relates to Spring... I vote that we remove Spring from the gemfile for all new rails projects. 99% of the time, all my Rails friends remove the gem. Spring causes so many problems with Rails and hidden errors. If someone wants to add Spring, they can. But it's going to turn a lot of people off from Rails if they spend days trying to figure out why their server isn't running. And it was a Spring failure.

**Comment by kaspth** [comment]
@natetech333 consider opening a bug report to Spring with the things you find. Open source is usually only as good as people help to make it, and having a library be maligned is a great to let it continue to have bugs because no one wants to touch it 😊❤️

**Comment by natetech333** [comment]
I will open a bug report for Spring Gem. But I still think it needs removed
from Rails. Rails is suffering from dependency maintenance fatigue. I spent
all day yesterday on fixing incompatible gem versions. It has been a big
complaint from CTO's who are using Rails in their ecosystems. If 1 gem
fails, especially on a newly generated project, it is not good. Is there a
reason that Spring is needed? It is a nice gem. I am only wondering why it
is in the core.

I would build a testing server that automates hundreds of Rails builds on
different platforms. We need to catch these issues before new Rails
developers spend days trying to generate a new project.

Kindly, Nathan

**Comment by dhh** [comment]
Do better still: Track down the bug and open a PR with a fix. 

We use Spring in all our projects, and it’s a massive boost to productivity when every test run or every console start doesn’t have to carry the weight of instantiating the entire framework every time.

Anyway, thanks for taking the time to track down bugs and working on patches to fix them. That’s a great way to participate in a community 👍

**Comment by natetech333** [comment]
Ok. I will offer them some testing ideas too. Since Spring is very
important to Rails core.

**Comment by morgoth** [comment]
I believe this can be closed as spring is no longer in the default stack
