### ISSUE TITLE
Wrong statement regarding CSRF protection for APIs in ActionController documentation 

### ISSUE THREAD

**Issue by jesuspc** [rails/rails#23905]
The documentation present for protect_from_forgery both [here](http://api.rubyonrails.org/classes/ActionController/RequestForgeryProtection.html) and [here](https://github.com/rails/rails/blob/e7bf9f9ab0fc39d91e68a11efc89d8485e36df43/actionpack/lib/action_controller/metal/request_forgery_protection.rb) states that a json API should be protected by disallowing any request with an invalid csrf token for which the request format is not json:

``` ruby
  # It's important to remember that XML or JSON requests are also affected and if
  # you're building an API you should change forgery protection method in
  # <tt>ApplicationController</tt> (by default: <tt>:exception</tt>):
  #
  #   class ApplicationController < ActionController::Base
  #     protect_from_forgery unless: -> { request.format.json? }
  #   end
  #
```

My understanding is that request.format parses the Accept header or the format inferred from the route declaration (the later takes priority). In this situation though what we care about is not the Accept header but the request's Content-Type (that if coming from a form would be application/x-www-form-urlencoded or multipart/form-data). Therefore the protection suggested by the documentation is not such: for instance, even if applied, a web form from a different domain pointing to any supposedly protected api endpoint (including the .json suffix so we force the request format without using headers) can be maliciously submitted and the request sent will be accepted by the rails app.

**Comment by rafaelfranca** [comment]
cc @jeremy
