### ISSUE TITLE
Rails Commands Not Work

### ISSUE THREAD

**Issue by sai43** [rails/rails#23907]
% bundle install                                                                         
Fetching gem metadata from https://rubygems.org/.........
Fetching version metadata from https://rubygems.org/...
Fetching dependency metadata from https://rubygems.org/..
Using rake 10.4.2
Using i18n 0.7.0
Using json 1.8.3
Using minitest 5.8.3
Using thread_safe 0.3.5
Using builder 3.2.2
Using erubis 2.7.0
Using mini_portile2 2.0.0
Using rack 1.6.4
Using mime-types 2.99
Using arel 6.0.3
Using ansi 1.5.0
Using awesome_print 1.6.1
Using bcrypt 3.1.10
Using debug_inspector 0.0.2
Using byebug 8.2.1
Using ffi 1.9.10
Using coderay 1.1.0
Using coffee-script-source 1.10.0
Using execjs 2.6.0
Using thor 0.19.1
Using commonjs 0.2.7
Using commonwatir 4.0.0
Using concurrent-ruby 1.0.0
Using deep_merge 1.0.1
Using connection_pool 2.2.0
Using database_cleaner 1.5.1
Using diff-lcs 1.2.5
Using docile 1.1.5
Using unf_ext 0.0.7.1
Using eventmachine 1.0.8
Using excon 0.45.4
Using fastercsv 1.5.5
Using ffaker 2.1.0
Using multi_xml 0.5.5
Using grocer 0.6.1
Using guard-compat 1.2.1
Using power_assert 0.2.6
Using hashdiff 0.2.3
Using multi_json 1.11.2
Using jwt 1.5.2
Using tilt 2.0.1
Using metaclass 0.0.4
Using mysql2 0.3.20
Using net-http-persistent 2.9.4
Using netrc 0.11.0
Using pg 0.18.4
Using phonelib 0.5.4
Using puma 2.15.3
Using ruby-openid 2.7.0
Using bundler 1.11.2
Using rails-perftest 0.0.6
Using rails_serve_static_assets 0.0.4
Using rails_stdout_logging 0.0.4
Using rdoc 4.2.0
Using redis 3.2.2
Using rubyzip 1.1.7
Using rspec-support 3.4.1
Using ruby-prof 0.15.9
Using sass 3.4.20
Using websocket 1.2.2
Using simplecov-html 0.10.0
Using smarter_csv 1.1.0
Using spring 1.5.0
Using sqlite3 1.3.11
Using uuidtools 2.1.5
Using tzinfo 1.2.2
Using ruby-push-notifications 0.3.1
Using nokogiri 1.6.7
Using rack-test 0.6.3
Using mail 2.6.3
Using binding_of_caller 0.7.2
Using childprocess 0.5.8
Using coffee-script 2.4.1
Using uglifier 2.7.2
Using less 2.6.0
Using sprockets 3.5.2
Using unf 0.1.4
Installing mandrill-api 1.0.53
Installing httparty 0.13.7
Installing test-unit 3.1.5
Installing twilio-ruby 4.2.1
Installing mocha 0.14.0
Installing pubnub 3.7.9
Installing rack-openid 1.4.2
Installing rails_12factor 0.0.3
Installing sdoc 0.4.1
Installing sidekiq 4.0.1
Installing rspec-core 3.4.1
Installing rspec-expectations 3.4.0
Installing rspec-mocks 3.4.0
Installing simplecov 0.11.1
Installing activesupport 4.2.4
Using loofah 2.0.3
Installing roo 2.3.0
Installing selenium-webdriver 2.48.1
Installing domain_name 0.5.25
Installing googl 0.7.1
Installing pushmeup 0.3.0
Installing guard-test 2.0.6
Installing rspec 3.4.0
Using rails-deprecated_sanitizer 1.0.3
Using globalid 0.3.6
Installing activemodel 4.2.4
Installing config 1.0.0
Installing factory_girl 4.5.0
Installing jbuilder 2.3.2
Installing rails-html-sanitizer 1.0.2
Installing watir-webdriver 0.9.1
Installing http-cookie 1.0.2
Using rails-dom-testing 1.0.7
Installing activejob 4.2.4
Installing activerecord 4.2.4
Installing watir 5.0.0
 % rails -v
/Users/kvanadev6/.rbenv/versions/2.2.3/lib/ruby/site_ruby/2.2.0/rubygems/path_support.rb:50:in `split_gem_path': undefined method `split' for #<Array:0x007fa4289a2300> (NoMethodError)
        from /Users/kvanadev6/.rbenv/versions/2.2.3/lib/ruby/site_ruby/2.2.0/rubygems/path_support.rb:32:in `initialize'
        from /Users/kvanadev6/.rbenv/versions/2.2.3/lib/ruby/site_ruby/2.2.0/rubygems.rb:351:in `new'
        from /Users/kvanadev6/.rbenv/versions/2.2.3/lib/ruby/site_ruby/2.2.0/rubygems.rb:351:in `paths='
        from /Users/kvanadev6/Developer/rails/new-sikka/humos-web/bin/spring:11:in `<top (required)>'
        from bin/rails:3:in `load'
        from bin/rails:3:in `<main>'

 % ruby -v
ruby 2.2.3p173 (2015-08-18 revision 51636) [x86_64-darwin15]

% which ruby
/Users/kvanadev6/.rbenv/shims/ruby

% which rails
/Users/kvanadev6/.rbenv/shims/rails

% gem env
RubyGems Environment:
  - RUBYGEMS VERSION: 2.6.0
  - RUBY VERSION: 2.2.3 (2015-08-18 patchlevel 173) [x86_64-darwin15]
  - INSTALLATION DIRECTORY: /Users/kvanadev6/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0
  - USER INSTALLATION DIRECTORY: /Users/kvanadev6/.gem/ruby/2.2.0
  - RUBY EXECUTABLE: /Users/kvanadev6/.rbenv/versions/2.2.3/bin/ruby
  - EXECUTABLE DIRECTORY: /Users/kvanadev6/.rbenv/versions/2.2.3/bin
  - SPEC CACHE DIRECTORY: /Users/kvanadev6/.gem/specs
  - SYSTEM CONFIGURATION DIRECTORY: /Users/kvanadev6/.rbenv/versions/2.2.3/etc
  - RUBYGEMS PLATFORMS:
    - ruby
    - x86_64-darwin-15
  - GEM PATHS:
     - /Users/kvanadev6/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0
  - GEM CONFIGURATION:
     - :update_sources => true
     - :verbose => true
     - :backtrace => false
     - :bulk_threshold => 1000
     - "gem" => "--no-document"
  - REMOTE SOURCES:
     - https://rubygems.org/
  - SHELL PATH:
     - /Users/kvanadev6/.rbenv/versions/2.2.3/bin
     - /usr/local/Cellar/rbenv/1.0.0/libexec
     - /Users/kvanadev6/.rbenv/shims
     - /Users/kvanadev6/.rbenv/bin
     - /usr/local/heroku/bin
     - /usr/bin
     - /bin
     - /usr/sbin
     - /sbin
     - /usr/local/bin
     - .git/safe/../../bin
     - /Users/kvanadev6/.bin
     - /usr/local/sbin

**Comment by rafaelfranca** [comment]
Thank you for the report. This is a issue in spring that is already fixed in master branch. I'll release a new version.

**Comment by sai43** [comment]
Yes @rafaelfranca ,
After remove 'Spring' gem from Gemfile , my app working fine without any issues.
Thanks
