### ISSUE TITLE
ActionCable feature request: before_action

### ISSUE THREAD

**Issue by kesha-antonov** [rails/rails#23900]
Hey guys!

It would be awesome to have `before_action` for ActionCable as well as we have in Controllers.

I need to set user online on any action when he uses websockets. So it would be great to set `before_action` in `action_cable/channel.rb` and thus it would fire on every action in channels.

What do you think?

**Comment by rafaelfranca** [comment]
Thank you for the issue but we don't take feature request in the issue tracker. I recommend you to ask in the Rails core mailing list.
