### ISSUE TITLE
Default Gemfile places web-console in the test group

### ISSUE THREAD

**Issue by prophittcorey** [rails/rails#23918]
### Steps to reproduce

Create a new rails app, generate a model and uncomment the model's example test. When you run the test you will be given the error: 

> Web Console is activated in the test environment, which is
> usually a mistake. To ensure it's only activated in development
> mode, move it to the development group of your Gemfile:
> 
>     gem 'web-console', group: :development
> 
> If you still want to run it the test environment (and know
> what you are doing), put this in your Rails application
> configuration:
> 
>     config.web_console.development_only = false

I assume my expectation is the same as other's-- I expect it to run my tests without modifying the Gemfile. The clear fix is to move the `web-console` gem into a `:development` group block and outside the `:development, :test` group. 

Is this intended behavior? I cannot imagine so. It appears like a bug to me.

**Comment by matthewd** [comment]
cc @gsamokovarov

**Comment by rafaelfranca** [comment]
It is already true. https://github.com/rails/rails/blob/master/railties/lib/rails/generators/rails/app/templates/Gemfile#L38 https://github.com/rails/rails/blob/4-2-stable/railties/lib/rails/generators/rails/app/templates/Gemfile#L37

**Comment by mwoller1234** [comment]
In the Gem file if you have this line   

gem 'web-console', '~> 2.0' 

Remove it. 

Then run 
gem install bundler
bundle install --without production
