### ISSUE TITLE
Rails 5 and :locale is unpermitted parameter

### ISSUE THREAD

**Issue by francesco-loreti** [rails/rails#23912]
I want translate my application with rails 5 but I can't do that because the ":locale" params is not permitted. I have tried to permit params on ApplicationController with
`before_action :set_locale def set_locale params.permit(:locale) I18n.locale = params[:locale] || I18n.default_locale puts I18n.locale end`
But It's not ok because everytime is set only I18n.default_locale value (for me it's :en). If I try to set other language into link on browser I don't have any result.
Into routes I have set:
`scope "(:locale)", :locale => /#{I18n.available_locales.join('|')}/, defaults: {locale: "#{I18n.locale == I18n.default_locale ? 'en' : I18n.locale}"} do .... end`
There are other params that not permitted: "_, format" What can I do?

**Comment by maclover7** [comment]
Can you create an executable test script using one of the templates [here](https://github.com/rails/rails/tree/master/guides/bug_report_templates), that would demonstrate the problem you are seeing?

**Comment by eileencodes** [comment]
Hey @sikachu do you know a workaround for using `:locale` with the changes to parameters?

**Comment by rafaelfranca** [comment]
What is the problem with `:locale`? It is a scalar value, you don't even need to permit it.

I don't see why this doesn't work:

```
I18n.locale = params[:locale] || I18n.default_locale
```

**Comment by sikachu** [comment]
This shouldn't be related to parameters change.

* Permitted or not, you should be able to read the `params` using `[]`, so `params[:locale]` should have some value coming in if you set it right.
* `#permit` method actually _does not_ mutate the params object. If you call `params.permit(:a_key)`, you aren't actually changing anything in `params`. Instead, you filter out unpermitted parameters out of it, then it'll return a new `Parameters` object which unpermitted keys removed. However, in this case, it doesn't matter per the first bullet point.

Are you sure that there's nothing else mutating/clearing out that parameter from the `params` object?

**Comment by francesco-loreti** [comment]
> Are you sure that there's nothing else mutating/clearing out that parameter from the params object?

I 've changed the permissions because I was generating an error sanitize the url . I had read on the internet that could be an issue of permits and I changed the permissions . Now I removed the permit and I solved the problem on the sanitize . Sorry for the incorrect reporting .

**Comment by rafaelfranca** [comment]
Not problem. Is your issue solved? Can I close this?

**Comment by francesco-loreti** [comment]
Yes and Thanks

**Comment by rafaelfranca** [comment]
Awesome! Thank you for reporting it.

**Comment by obie** [comment]
This is definitely broken behavior in Rails 5--just putting any sort of parameter into a scope block definition in your routing file causes Unpermitted parameter message. It's a big deal because pretty much every I18n example code out there says this is how you implement locale parameter as part of the URL.

I'm going to create an executable test script so that this ticket can be reopened.
