### ISSUE TITLE
rails restart doesn't work with puma3

### ISSUE THREAD

**Issue by rubys** [rails/rails#23910]
### Steps to reproduce

    rails new foo
    cd foo
    rails server
    rails restart

### Expected behavior
Server should restart.

### Actual behavior
Puma notices the change to `tmp/restart.txt`, stops the server, and attempts to restart the server with its own ideas of what ARGV should look like.  Rails doesn't like what it sees in ARGV, and spits out usage instructions.  At that point, the server is down.

The problem also occurs with `rails dev:cache`.

### System configuration
**Rails version**: Rails 5.0.0.beta3 (`master`)

**Ruby version**: ruby 2.3.0p0 (2015-12-25 revision 53290) [x86_64-darwin15]

**Comment by chashmeetsingh** [comment]
@sikachu can you tell the flow when rails restart is run ? 
I want to try to fix this

**Comment by sikachu** [comment]
@chashmeetsingh I'm currently working on this as well, digging through Puma source code.

It seems like we can specify `restart_command` but then it feels hackish and Rails still refuses to start because `tmp/pids/server.pid` is still there.

**Comment by chashmeetsingh** [comment]
Need help just want to know is it possible that while the server is running and logs bring printed we type some text there and somewhere we can access its value ?

**Comment by rubys** [comment]
Just a reminder, the following code is also problematic (and is the problem I first saw):

  https://github.com/rails/rails/blob/master/railties/lib/rails/tasks/dev.rake#L12

**Comment by chashmeetsingh** [comment]
@rubys Issue because of the restart command being used

**Comment by sikachu** [comment]
@chashmeetsingh I assume that `rails restart` just `touch tmp/restart.txt`?

The big problem that we need to fix is that we have to restart the Rack server again with correct arguments. We can tell Puma which command it should use for starting up the server when it restarting. Maybe that's the way to do it?

**Comment by chashmeetsingh** [comment]
@sikachu can't we restart from the same terminal without opening another one?

**Comment by sikachu** [comment]
@chashmeetsingh I guess you can make `rails server` listen to a signal, but that's not the issue we are trying to fix here ...

**Comment by chashmeetsingh** [comment]
https://github.com/rails/rails/blob/685203917378dbdf8c836d5bdaabccd31f4e5f98/railties/lib/rails/generators/rails/app/templates/config/puma.rb#L47 what does this do ?

**Comment by rubys** [comment]
@chashmeetsingh that causes this plugin to be loaded: https://github.com/puma/puma/blob/master/lib/puma/plugin/tmp_restart.rb

@sikachu an alternative solution would be to use `tmp/pids/server.pid`.  Kill that process and kick off a new one.  There is no need for graceful restart in development mode.

**Comment by chashmeetsingh** [comment]
@sikachu @rubys is right that's also a good solution

**Comment by sikachu** [comment]
@rubys just tried that solution. Rails server was killed, nothing started back up.

I'll need to dig deeper into this.

**Comment by chashmeetsingh** [comment]
hey @sikachu @rubys try this https://github.com/chashmeetsingh/rails/blob/master/railties/lib/rails/tasks/restart.rake
I got it working voohoo

**Comment by sikachu** [comment]
Please feel free to work on the fix. :)

**Comment by chashmeetsingh** [comment]
@sikachu by the way is it fine?

**Comment by chashmeetsingh** [comment]
@sikachu this is a work around but getting no such file or directory 'pkill' on osx works well when in irb
[may work](https://github.com/chashmeetsingh/puma/blob/master/lib/puma/launcher.rb#L225)

**Comment by rubys** [comment]
If I add the following to the end of `config/puma.rb`

    restart_command 'rails server'
    pidfile 'tmp/pids/server.pid'

And add the following code to puma itself:

```
diff --git a/lib/puma/launcher.rb b/lib/puma/launcher.rb
index 7667bbe..4042fde 100644
--- a/lib/puma/launcher.rb
+++ b/lib/puma/launcher.rb
@@ -200,6 +200,10 @@ module Puma
     def restart!
       @config.run_hooks :on_restart, self
 
+      if @options[:pidfile]
+        File.unlink @options[:pidfile]
+      end
+
       if Puma.jruby?
         close_binder_listeners
```

I get further:

```
* Restarting...
=> Booting Puma
=> Rails 5.0.0.beta3 application starting in development on http://localhost:3000
=> Run `rails server -h` for more startup options
=> Ctrl-C to shutdown server
Puma starting in single mode...
* Version 3.0.2 (ruby 2.3.0-p0), codename: Plethora of Penguin Pinatas
* Min threads: 5, max threads: 5
* Environment: development
* Inherited tcp://localhost:3000
Exiting
/Users/rubys/git/puma/lib/puma/binder.rb:258:in `for_fd': Bad file descriptor - fstat(2) (Errno::EBADF)
	from /Users/rubys/git/puma/lib/puma/binder.rb:258:in `inherit_tcp_listener'
	from /Users/rubys/git/puma/lib/puma/binder.rb:91:in `block in parse'
	from /Users/rubys/git/puma/lib/puma/binder.rb:85:in `each'
	from /Users/rubys/git/puma/lib/puma/binder.rb:85:in `parse'
	from /Users/rubys/git/puma/lib/puma/runner.rb:125:in `load_and_bind'
	from /Users/rubys/git/puma/lib/puma/single.rb:84:in `run'
	from /Users/rubys/git/puma/lib/puma/launcher.rb:173:in `run'
	from /Users/rubys/git/puma/lib/rack/handler/puma.rb:51:in `run'
	from /Users/rubys/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/rack-2.0.0.alpha/lib/rack/server.rb:296:in `start'
	from /Users/rubys/git/rails/railties/lib/rails/commands/server.rb:78:in `start'
	from /Users/rubys/git/rails/railties/lib/rails/commands/commands_tasks.rb:90:in `block in server'
	from /Users/rubys/git/rails/railties/lib/rails/commands/commands_tasks.rb:85:in `tap'
	from /Users/rubys/git/rails/railties/lib/rails/commands/commands_tasks.rb:85:in `server'
	from /Users/rubys/git/rails/railties/lib/rails/commands/commands_tasks.rb:49:in `run_command!'
	from /Users/rubys/git/rails/railties/lib/rails/command.rb:20:in `run'
	from /Users/rubys/git/rails/railties/lib/rails/commands.rb:18:in `<top (required)>'
	from bin/rails:4:in `require'
	from bin/rails:4:in `<main>'
```

@evanphx: thoughts?

**Comment by chashmeetsingh** [comment]
@rubys This is because the port is already being occupied

**Comment by rubys** [comment]
From the messages, it appears that the port is being inherited.

More generally:

   * From a rails development perspective, the user starts the server in one terminal window and may return to that window occasionally to see status messages.  It would be a desirable feature for the server to be restarted in that window.
   * Puma has support for features like phased restart that are not needed in a Rails development environment.  Given that Evan seems motivated to support this scenario, I would suggest that if additional functionality is required to make this work, that such be added to puma, perhaps as a configuration option.

I've opened a separate issue to track the puma changes required:  https://github.com/puma/puma/issues/907

**Comment by chashmeetsingh** [comment]
`def restart!
      @config.run_hooks :on_restart, self

      if Puma.jruby?
        close_binder_listeners

        require 'puma/jruby_restart'
        JRubyRestart.chdir_exec(@restart_dir, restart_args)
      elsif Puma.windows?
        close_binder_listeners

        argv = restart_args
        Dir.chdir(@restart_dir)
        Kernel.exec(*argv)
      else
        redirects = {:close_others => true}
        @binder.listeners.each_with_index do |(l, io), i|
        ENV["PUMA_INHERIT_#{i}"] = "#{io.to_i}:#{l}"
        redirects[io.to_i] = io.to_i
        end

        argv = restart_args
        Dir.chdir(@restart_dir)
        argv += [redirects] if RUBY_VERSION >= '1.9'
        
        #--------------
        pid = File.read('tmp/pids/server.pid')
        system("kill -9 #{pid} && sleep 10 && rails dev:cache && sleep 5 && rails tmp:clear && rails s")
        #--------------
      end
    end`

I did this still get the same error as rubys :(

**Comment by rubys** [comment]
Should this not be fixed in Puma in time for Rails 5, the following line should be removed or commented out prior to the release:

https://github.com/rails/rails/blob/master/railties/lib/rails/generators/rails/app/templates/config/puma.rb#L47

(To be clear, I think it would be a very nice thing to have this working, and would prefer that this bug remain open while there are other blockers)

**Comment by prathamesh-sonpatki** [comment]
I made some progress on this. 

We need to provide a restart command to Puma which it will use while restarting the server. The command will be `bin/rails s`. 

Even after this, there is an issue with existing `pid` file present in `tmp/pids/server.pid` file. I think it's *okey* to remove that file manually from Rails side when doing `rails restart` or `rails dev:cache`. But would like to hear more opinions if I am missing something. (cc @rafaelfranca, @kaspth )

I think we will need to make some changes to Puma also to correctly accept the restart command from Rails. I got it working locally and will make a PR shortly to Puma.

```
$ rails s
=> Booting Puma
=> Rails 5.0.0.beta3 application starting in development on http://localhost:3000
=> Run `rails server -h` for more startup options
"conf options"
Puma starting in single mode...
* Version 3.2.0 (ruby 2.3.0-p0), codename: Spring Is A Heliocentric Viewpoint
* Min threads: 5, max threads: 5
* Environment: development
* Listening on tcp://localhost:3000
Use Ctrl-C to stop
* Restarting...
["bin/rails", "s", {:close_others=>true, 31=>31}]
"----------"
=> Booting Puma
=> Rails 5.0.0.beta3 application starting in development on http://localhost:3000
=> Run `rails server -h` for more startup options
"conf options"
Puma starting in single mode...
* Version 3.2.0 (ruby 2.3.0-p0), codename: Spring Is A Heliocentric Viewpoint
* Min threads: 5, max threads: 5
* Environment: development
* Inherited tcp://localhost:3000
Use Ctrl-C to stop
```
