### ISSUE TITLE
Change cable.coffee to cable.js instead?

### ISSUE THREAD

**Issue by sanford** [rails/rails#23931]
Issue: 

inconsistent default files in 'app/javascripts' directory

To reproduce:

rails new appname

Results:

application.js
cable.coffee

Either application.js goes coffeescript or make the cable.coffee file a .js file.  I'd vote for cable.js given that coffeescript is probably going to be used less and less due to ES6+ adoption.

Background:

Now that ES6 is here, there's a growing body of people moving away from coffeescript.  Perhaps someday 'rails new appname --default-coffeescript' and 'rails new appname --default-javascript' or the like could be a thing and those could create all default .coffee files or default .js files.  Until then, lets go .js?

**Comment by maclover7** [comment]
@javan @lifo @dhh thoughts?

**Comment by javan** [comment]
:+1:

**Comment by dhh** [comment]
One thing to note here is that the cable generators will generate CS files. But still fine to convert this. As long as we keep the generator a

**Comment by sanford** [comment]
@dhh did your message get cut off?  (the trailing 'a')

**Comment by dhh** [comment]
That was just a stray. As long as we keep the generator generating CS, then
I'm fine with the initializer being JS.

**Comment by sanford** [comment]
Sure, but if coffeescript is becoming a must-have for Rails, then maybe its a better idea to make javascript and coffeescript live side-by-side easier without relying on gem include side-effects.  

From what I understand, the recommended way to disable coffeescript in generators is to remove 'coffee-rails' from the Gemfile.  That is at odds with .coffee being a must have requirement for action cable.  

So, lets keep actioncable's .coffee and just make switching to generated .js by default not disable coffeescript support.

```
coffee-rails/lib/coffee/rails/engine.rb
....
  class Engine < ::Rails::Engine
    config.app_generators.javascript_engine :coffee

    if config.respond_to?(:annotations)
      config.annotations.register_extensions("coffee") { |annotation| /#\s*(#{annotation}):?\s*(.*)$/ }
    end
  end
```

Perhaps we can remove the config.app_generators.javascript_engine line from the gem and put it in the generated config/application.rb:

```
# uncomment to use javascript by default in generators
# config.generators.javascript_engine = :js

# uncomment to use coffeescript by default in generators
config.generators.javascript_engine = :coffee
```

And perhaps someday a rails command flag like:

`rails new appname --default-javascript `

could uncomment the right line by default on a new app.

Coffeescript would still be the default, but switching to .js as a generator default without breaking coffeescript support would be easy and wouldn't rely on side-effects.

Thoughts?

**Comment by dhh** [comment]
Not sure I follow. If you disable coffee script, what is the cable
generators going to generate? You'll write another set of generators for
Cable that outputs vanilla JS?

**Comment by sanford** [comment]
Can we just have the cable generators pass the .coffee through the coffeescript compiler if .js is set as the default?  No need for two sets of generators.

**Comment by dhh** [comment]
Do give that a try. Like that idea.

**Comment by rafaelfranca** [comment]
Closed by https://github.com/rails/rails/pull/23935
