### ISSUE TITLE
Cannot preload assocation with an extension block

### ISSUE THREAD

**Issue by daniel-rikowski** [rails/rails#23934]
It is not possible to preload a scoped association which has an extension block. 
This is because the association scope - which is *not* instance dependant - is wrapped in a proc with parameters.
It looks like the fix from #18467 is not present in the Rails 5/master branch.

### Runnable test

```ruby
gem 'activerecord', '5.0.0.beta3'
require 'active_record'
require 'minitest/autorun'

ActiveRecord::Base.establish_connection(adapter: 'sqlite3', database: ':memory:')
ActiveRecord::Base.default_timezone = :local

ActiveRecord::Schema.define do
  create_table(:parents)
  create_table(:children) { |t| t.integer :parent_id }
end

class Parent < ActiveRecord::Base
  has_many :children, ->() { order('id DESC') }, dependent: :destroy do
  end
end

class Child < ActiveRecord::Base
end

class Bug < Minitest::Test
  def test_preloading_of_associations
    Parent.create!
    Parent.create!
    Parent.includes(:children).to_a
  end
end
```

### Expected behavior
There should be no runtime error.

### Actual behavior
`Parent.includes(:children).to_a` triggers a runtime error:

> ArgumentError: The association scope 'children' is instance dependent (the scope block takes an argument). Preloading instance dependent scopes is not supported.

### System configuration
**Rails version**: 5.0.0.beta3

**Ruby version**: 2.2.4

**Comment by maclover7** [comment]
cc @senny since you did the 4-2-stable patch

**Comment by senny** [comment]
I'll have a look.

**Comment by senny** [comment]
Pushed a forward port of ac832a43b4d026dbad28fed196d2de69ec9928ac

@daniel-rikowski thanks for reporting :yellow_heart:

**Comment by daniel-rikowski** [comment]
My pleasure. Thanks for fixing this :+1:

**Comment by ckmorris** [comment]
This error is still in play due to the `raise` on line 409 of `lib/active_record/reflection.rb`
