### ISSUE TITLE
Updating an ActiveRecord datetime attribute using a float is set to nil

### ISSUE THREAD

**Issue by jeffblake** [rails/rails#23949]
### Steps to reproduce

consider `Ticket` model with `checkin_at` `datetime` attribute

`ticket.update_attributes checkin_at: 1456652070.155761`

Nothing happens.
### Expected behavior

`Time.at(1456652070.155761)` is used to update the attribute 
### Actual behavior

Attribute is updated to nil
### System configuration

**Rails version**: 4.2.5.1

**Ruby version**: 2.3.0

**Comment by maclover7** [comment]
Is an error raised?

**Comment by maclover7** [comment]
Can you create an executable test script using one of the templates [here](https://github.com/rails/rails/tree/master/guides/bug_report_templates), that would demonstrate the problem you are seeing?

**Comment by jeffblake** [comment]
I'm not receiving an error on my development/staging app (the timestamp is silently ignored).

I created a test on AR 4.2 and 5.0 using the provided  sqlite templates and could not reproduce the problem.

Then I created one for postgres (which I use in my app) and I get the error:

```
BugTest#test_association_stuff:
ActiveRecord::StatementInvalid: PG::InvalidDatetimeFormat: ERROR:  invalid input syntax for type timestamp: "1456652070.155761"
```

```
begin
  require 'bundler/inline'
rescue LoadError => e
  $stderr.puts 'Bundler version 1.10 or later is required. Please update your Bundler'
  raise e
end

gemfile(true) do
  source 'https://rubygems.org'
  # Activate the gem you are reporting the issue against.
  gem 'activerecord', '4.2.0'
  gem 'pg'
end

require 'active_record'
require 'minitest/autorun'
require 'logger'

# This connection will do for database-independent bug reports.
ActiveRecord::Base.establish_connection(adapter: 'postgresql', database: 'test2')
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :posts, force: true  do |t|
    t.datetime :published_at
  end

  create_table :comments, force: true  do |t|
    t.integer :post_id
  end
end

class Post < ActiveRecord::Base
  has_many :comments
end

class Comment < ActiveRecord::Base
  belongs_to :post
end

class BugTest < Minitest::Test
  def test_association_stuff
    post = Post.create!

    float = 1456652070.155761

    post.update_attributes published_at: float
    post.reload
    assert_equal float, post.published_at
  end
end
```

**Comment by fillman** [comment]
@jeffblake I have only one question:
Why you consider that **actual** behaviour should use `Time.at`?

**Comment by jeffblake** [comment]
JSON API... The client sends the timestamp as a float. When this happens across many different models, and in arrays, it's tedious to convert them all. I'd rather not monkey patch either. And I can't think of a reason why rails shouldn't do this by default. And it works with sqlite so it should be consistent regardless of the database adapter.

**Comment by fillman** [comment]
@jeffblake I understand, you're correct about same behaviour across different adapters:
```ruby
[3] pry(#<BugTest>)> post.reload
D, [2016-02-29T06:31:49.575515 #29457] DEBUG -- :   Post Load (1.4ms)  SELECT  "posts".* FROM "posts" WHERE "posts"."id" = ? LIMIT ?  [["id", 1], ["LIMIT", 1]]
=> #<Post:0x000000038572f0 id: 1, published_at: 1456652070.155761>
[4] pry(#<BugTest>)> post.published_at
=> 1456652070.155761
[5] pry(#<BugTest>)> post.published_at.class
=> Float
[6] pry(#<BugTest>)>
```

But this is what I get with sqlite3. It doesn't convert to `datetime` passed `float`.
Strange thing it doesn't respect the type casting and simply stores float in that column.
While postgres and mysql throws an error.

Not sure if that's a bug or simply sqlite3 implementation. But typecasting for datetime works in same way for postgres/mysql/sqlite3 adapters. Simply by not converting `float` into anything else.

**Comment by pixeltrix** [comment]
@jeffblake it's because both `Fixnum` and `Float` don't respond to `in_time_zone`. Whether we want to add those methods is debatable but if you want to add them for your app the easiest solution is to add them in an initializer like this:

``` ruby
class Float
  def in_time_zone(zone = Time.zone)
    Time.at(self).in_time_zone(zone)
  end
end

class Fixnum
  def in_time_zone(zone = Time.zone)
    Time.at(self).in_time_zone(zone)
  end
end
```

I'm leaning towards adding them but I know a lot of people object to Active Support extending core classes so I'm open to being persuaded not to. :smile:

**Comment by jeffblake** [comment]
Thanks for the solution. Adding it now.

I think its a good idea to add it in :)
