### ISSUE TITLE
Brittle test sometimes causing build failures on master

### ISSUE THREAD

**Issue by ValMai** [rails/rails#23942]
Hello Rails community! 
I am a new contributor and I am very enthusiastic about contributing to this fascinating project.

I was looking into what I could do when I saw the master had a build failure. I went into the CI log and found the following:
```
Failure:
QueuingTest#test_should_run_job_with_higher_priority_first [/home/travis/build/rails/rails/activejob/test/integration/queuing_test.rb:95]:
Failed assertion, no message given.

bin/rails test /home/travis/build/rails/rails/activejob/test/integration/queuing_test.rb:88
```

Looking into the test itself, I noticed it was a brittle test which can sometimes fail because it relies on time passed to make an assertion. 
This is the test:
```
test 'should run job with higher priority first' do
    skip unless adapter_is?(:delayed_job, :que)

    wait_until = Time.now + 3.seconds
    TestJob.set(wait_until: wait_until, priority: 20).perform_later "#{@id}.1"
    TestJob.set(wait_until: wait_until, priority: 10).perform_later "#{@id}.2"
    wait_for_jobs_to_finish_for(10.seconds)
    assert job_executed "#{@id}.1"
    assert job_executed "#{@id}.2"
    assert job_executed_at("#{@id}.2") < job_executed_at("#{@id}.1")
  end
```

If I have your green light, I would really like to work on fixing the test.

Thank you all!

**Comment by perceptec** [comment]
In the absence of feedback, I'd say have at it, and post any meaningful findings here.

If you haven't done so already, check out [Contributing to Ruby on Rails](http://edgeguides.rubyonrails.org/contributing_to_ruby_on_rails.html) for tips.

And welcome!

**Comment by kaspth** [comment]
Welcome @ValMai! By all means do dig in :heart:

I'll go ahead and close this because we don't need this open to evaluate any pull request. Thanks!
