### ISSUE TITLE
Confusion about whether ActionCable supports Unicorn or not

### ISSUE THREAD

**Issue by bouk** [rails/rails#23950]
The ActionCable README is a bit confusing because in one segment it tells me that I need a threaded server, but in another it tells me that I can use unicorn.

The parts I'm referring to are [Deployment](https://github.com/rails/rails/blob/a0d6209479bee220b43061d8ffa6a8d732ffd20d/actioncable/README.md#deployment):

> The Action Cable server does not need to be a multi-threaded application server. This is because Action Cable uses the Rack socket hijacking API to take over control of connections from the application server. Action Cable then manages connections internally, in a multithreaded manner, regardless of whether the application server is multi-threaded or not. So Action Cable works with all the popular application servers -- Unicorn, Puma and Passenger.

And [in-app](https://github.com/rails/rails/blob/a0d6209479bee220b43061d8ffa6a8d732ffd20d/actioncable/README.md#in-app)

> If you are using a threaded server like Puma or Thin, the current implementation of Action Cable can run side-along with your Rails application.

Maybe I am misunderstanding why you can't use Unicorn for the application and websocket server at the same time, but it might be worth clearing this up

@FooBarWidget you added the part about Unicorn being supported, maybe this is just an inconsistency?

**Comment by maclover7** [comment]
@matthewd, I believe we support Unicorn?

**Comment by FooBarWidget** [comment]
That is an inconsistency. In-app Action Cable works fine on Unicorn, Passenger open source and any other single-threaded app servers. The only requirement is Rack socket hijacking, which all app servers nowadays support except WEBrick.
