### ISSUE TITLE
Guides for v3.2 don't work

### ISSUE THREAD

**Issue by Kapeli** [rails/rails#23984]
### Steps to reproduce

Go to http://guides.rubyonrails.org/v3.2/

### Expected behavior

Guides work

### Actual behavior

Guides don't work: 403 Forbidden

**Comment by fxn** [comment]
The generation for 3.2.22.2 failed due to some AV stuff I have to investigate. Have linked to 3.2.22.1 meanwhile.

**Comment by Kapeli** [comment]
3.2.22.2 are the docs I need. Should I open a separate issue about that or there's no need?

**Comment by rafaelfranca** [comment]
@Kapeli we are going to fix it and publish with to `v3.2`

**Comment by fxn** [comment]
@Kapeli We'll fix somehow, but 3.2.22.2 and 3.2.22.1 have no difference in the guides (https://github.com/rails/rails/compare/v3.2.22.1...v3.2.22.2).
