### ISSUE TITLE
inconsistency in time_ago_in_words when being in March

### ISSUE THREAD

**Issue by joker-777** [rails/rails#23982]
### Steps to reproduce

It is right now the 1st of March and usually I get "about 1 month" when I call `time_ago_in_words(1.month.ago)`. But today I get "29 days" because the February is shorter then the other months.

### Expected behavior
I would expect to get "about 1 month" too even though the February is shorter then the other months.

### System configuration
Rails 4.2.5.1
ruby 2.2.0p0 (2014-12-25 revision 49005) [x86_64-linux]

**Comment by ValMai** [comment]
Sorry for barging in, but do you mean `It is right now the 1st of March` instead of `1st of February`?

**Comment by chrisarcand** [comment]
Seems logical. I'll correct this if a committer can confirm such a change would be welcome.

**Comment by joker-777** [comment]
@ValMai You are totally right. I changed it now to March :-)

**Comment by vsorlov** [comment]
https://github.com/rails/rails/blob/master/actionview/lib/action_view/helpers/date_helper.rb#L127
need to treat 28-29 days as "about 1 month" or look back on amount of days in the last month and treat (amount of days in the last month) - 60 days as "about 1 month". I think it is better to go with first approach. I don't see a reason why 28 days can't be treated as "about 1 month" and 58 days can.

I can create a fix for it if someone suggest what approach to choose.

**Comment by sgrif** [comment]
I'm not sure there's anything that can be done about this issue without causing an unacceptable backwards incompatibility. @rafaelfranca WDYT?

**Comment by chrisarcand** [comment]
The 28-30 days == about 1 month option seems like very reasonable (and better) behavior but admittedly backwards incompatible.

I believe you can introduce similar logic to the calculations in years w/ leap years on a monthly level to make a perfectly backwards compatible solution (except for those few days); however, the amount of complexity added to this calculation for something that might only occur for a day or two every 4 years might not really be worth caring about.

**Comment by rafaelfranca** [comment]
> however, the amount of complexity added to this calculation for something that might only occur for a day or two every 4 years might not really be worth caring about.

:+1: Agree that implementing this backward incompatible change just for one day is not worth.

**Comment by vsorlov** [comment]
@chrisarcand, @rafaelfranca, it actually has nothing to do with a leap year, it occurs every year after february. Each year from 1 of match till 28 of march `distance_of_time_in_words` returns `28 days` when it is reasonable to return `about 1 month`.
