### ISSUE TITLE
ActionMailer does not quote the label portion of the address in the From header

### ISSUE THREAD

**Issue by walterdavis** [rails/rails#23988]
### Steps to reproduce

1. Create a mailer, set it to use a From address containing a comma: `from: 'Sammy Davis, Jr. <sammy@example.com>'`.
2. Send through SMTP.
3. (result) `501 5.1.7 Bad sender address syntax`

### Expected behavior
If you format such a From: header in a desktop mail client, it will wrap the Sammy Davis, Jr. portion in double-quotes, and the mail will go through correctly.

### Actual behavior
ActionMailer does nothing, so garbage in becomes a 501 error.

### System configuration
**Rails version**: 4.2.5.1

**Ruby version**: 2.3.0

I would very much like to contribute to Rails by adding this behavior to ActionMailer. If you agree that this is worthwhile, please let me know, and if you can suggest an entry point for this, I would appreciate it.

**Comment by jeremy** [comment]
You're expected to provide a valid email address, including proper quoting. Determining how to correctly quote a misquoted address isn't straightforward.

Using the (mail)[https://github.com/mikel/mail] lib to demonstrate:
```ruby
>> Mail::Address.new('Sammy Davis, Jr. <sammy@example.com>')
Mail::Field::ParseError: Mail::AddressList can not parse |Sammy Davis, Jr. <sammy@example.com>|
Reason was: Only able to parse up to Sammy Davis,
>> Mail::Address.new('"Sammy Davis, Jr." <sammy@example.com>')
=> #<Mail::Address:70134702480860 Address: |"Sammy Davis, Jr." <sammy@example.com>| >
```

We could fail earlier, though, before delivery.
