### ISSUE TITLE
Rails test does not recognize the `--pride` flag

### ISSUE THREAD

**Issue by ssaunier** [rails/rails#23994]
Hi everyone, minor issue here.

### Steps to reproduce

When running :
```bash
bin/rails test --help
```

It says:

```bash
# [...]
Known extensions: pride, rails
    -p, --pride                      Pride. Show your testing pride!
# [...]
```

Launch the command:
```bash
bin/rails test --pride
```

### Expected behavior
Rails test should output with pride!

### Actual behavior
It seems that `--pride` has no action on the output. Running `rails test` with or without gives the same output on stout.

### System configuration
**Rails version**: 5.0.0.beta3

**Ruby version**: 2.3.0

**Comment by maclover7** [comment]
cc @kaspth

**Comment by kaspth** [comment]
Should be fixed with https://github.com/rails/rails/pull/24007#issuecomment-200458339. Thanks for the report!
