### ISSUE TITLE
Turbolinks 5 Upgrade Guide for Rails 5 Release Notes

### ISSUE THREAD

**Issue by connorshea** [rails/rails#24018]
Turbolinks 5 upgrade notes should be mentioned in [the Rails 5.0.0 Release Notes Guide](https://github.com/rails/rails/blob/master/guides/source/5_0_release_notes.md). Currently there are no directions in the Release Notes for changes between Turbolinks classic and Turbolinks 5. In my opinion, this is a pretty big oversight.

The Rails Guide Release Notes already have Turbolinks 5.0 as a major "point" of the Rails 5 release, but have no guide for them anywhere in the document.

**Comment by maclover7** [comment]
Big :+1: to this -- cc @dhh @sstephenson

**Comment by dhh** [comment]
Happy to see a guide for this but TL5 isn't a required upgrade for any existing app. New apps will get it by default but existing apps should probably just stick with TL2 for starters. 

Anyway, would be nice to see someone take this on. I don't think either Sam or me will have the time. So let's open it up to the community to tackle.

**Comment by rafaelfranca** [comment]
Agree with @dhh. Let's move the discussion to https://github.com/turbolinks/turbolinks-rails/issues/4

**Comment by connorshea** [comment]
@dhh @rafaelfranca my only concern with this would be that I'm getting depreciation warnings for the use of `before_filter` in Turbolinks 2 on Rails 5. If people don't upgrade, there's a chance 5.1 or a future update could break Turbolinks compatibility.

Plus, I don't like having deprecation warnings everywhere in my logs :)

**Comment by dhh** [comment]
We can release a new TL2 that doesn't give those warnings.

**Comment by jhubert** [comment]
@dhh It would be great to release a TL2 without those warnings. The [fix has been merged into the turbolinks-classic repo](https://github.com/turbolinks/turbolinks-classic/pull/679), but it's on TL3 so current master isn't usable as a minor upgrade to TL2. 

We're evaluating whether or not to fork / patch TL2.5.3 or undergo the upgrade to TL5. Any thoughts on whether a TL2.5.4 gem release would be feasible that includes the fix?

**Comment by dhh** [comment]
Sounds like @rafaelfranca is on the release 👍

**Comment by mmoll** [comment]
https://github.com/turbolinks/turbolinks-classic/pull/679 - if anybody could get that gem release out of the door, it would really help... 💟
