### ISSUE TITLE
formated (postgre)sql  query is 14 times slower than an "minified" query

### ISSUE THREAD

**Issue by Elux91** [rails/rails#24010]
I'm using Rails 5.0.0.beta2 in --api mode. ruby -v 2.3.0p0
I created a custom sql query and executed it using find_by_sql.
I encoutered that an sql query that is formatted nicely is 14 times slower than the same query that is stripped of all it's unnecessary spaces.

You can find my example [here](https://github.com/Elux91/shift-planner/blob/6cfe1bbf4880f4be4741d9cc3e3db49a53450ce8/app/models/person.rb)
The relevant queries are inside the detailed_info_for_people_in_dept method.

The fast_query takes about 165ms and the slow one 2300ms

fast:

    Completed 200 OK in 157ms (Views: 16.4ms | ActiveRecord: 69.4ms)

slow:

    Completed 200 OK in 2307ms (Views: 13.2ms | ActiveRecord: 67.8ms)

I ran both queries directly in psql and couldn't find any time differences.

To reproduce the issue clone the repository and seed the db (might take some time, it creates 400.000 entries)

**Comment by rafaelfranca** [comment]
Could you check it with the master branch?

**Comment by Elux91** [comment]
updated my gemfile to:

    gem 'rails', git: 'https://github.com/rails/rails.git', branch: "master"

ran bundle rails -v is now Rails 5.0.0.beta3
and confirmed that the problem is still present

**Comment by meinac** [comment]
I can confirm that this is fixed with #23948. Thanks to @ctm.

**Comment by rafaelfranca** [comment]
:+1: thank you for confirming.
