### ISSUE TITLE
Getting Started with Rails Guide has an issue?

### ISSUE THREAD

**Issue by connorshea** [rails/rails#24019]
### Steps to reproduce
We discovered this issue in #24017.
- Create a new Rails app (I've only tested 4.2.5.2, not sure about Rails 5)
- Follow [the Getting Started with Rails guide](http://guides.rubyonrails.org/getting_started.html)
- Once you get to the [Deleting Comments](http://guides.rubyonrails.org/getting_started.html#deleting-comments) section you're told to add the following code to the view:

```erb
<%= link_to 'Destroy Comment', [comment.article, comment],
               method: :delete,
               data: { confirm: 'Are you sure?' } %>
```

### Expected behavior
The delete comment button will display.

### Actual behavior
The delete comment button does not display, and throws the following error:

```
NoMethodError in Articles#show
Showing /Users/eiyasushiki/Desktop/Cameo/app/views/comments/_comment.html.erb where line #12 raised:

undefined method `article_comment_path' for #<#<Class:0x007f8b15174f88>:0x007f8b19170f60>
Extracted source (around line #12):              

<p>
  <%= link_to 'Destroy Comment',
              [ comment.article, comment ],
              method: :delete,
              data: { confirm: 'Are you sure?' } %>

Trace of template inclusion: app/views/articles/show.html.erb

Rails.root: /Users/eiyasushiki/Desktop/Cameo

Application Trace | Framework Trace | Full Trace
app/views/comments/_comment.html.erb:12:in `_app_views_comments__comment_html_erb___1475545422721524329_70117699327520'
app/views/articles/show.html.erb:12:in `_app_views_articles_show_html_erb___1983865233824308479_70117665664900'
Request

Parameters:

{"data"=>{"confirm"=>"Are you sure?"},
 "method"=>"delete",
 "id"=>"7"}
```

If you replace the aforementioned HTML ERB code with this, it works:

```erb
<%= link_to 'Destroy Comment',
              article_comments_path(comment),
              method: :delete,
              data: { confirm: 'Are you sure?' } %>
```

I've never actually seen the `[comment.article, comment]` syntax before, is there any reason we're specifically using it here?

### System configuration
**Rails version**: 4.2.5.2

**Ruby version**: 2.3.0

**Comment by connorshea** [comment]
[Here's the specific commit in a new Rails app where the issue occured](https://github.com/Mr-DwZ/Cameo/commit/a70eeb380d4ebaa74792c8a12fe1e4c8db953f6a).

**Comment by matthewd** [comment]
https://github.com/Mr-DwZ/Cameo/commit/a70eeb380d4ebaa74792c8a12fe1e4c8db953f6a#diff-21497849d8f00507c9c8dcaf6288b136R9
!=
http://guides.rubyonrails.org/getting_started.html#adding-a-route-for-comments

**Comment by connorshea** [comment]
D'oh
