### ISSUE TITLE
Unable to follow the Delete Comment chapter of Getting Started

### ISSUE THREAD

**Issue by Mr-DwZ** [rails/rails#24017]
Hey guys.

I'm a novice in Rails, and trying to follow [Getting Started with Rails](http://edgeguides.rubyonrails.org/getting_started.html). The learning experience is quite smooth until I finished mimic the code shows in chapter 8 Deleting Comments. Although I cannot definitely sure  that I didn't missed any crucial content, so far I can't find any difference between my code and tutorial's version.

Here is the pertinent code:
~~~
<p>
  <strong>Commenter:</strong>
  <%= comment.commenter %>
</p>
 
<p>
  <strong>Comment:</strong>
  <%= comment.body %>
</p>
 
<p>
  <%= link_to 'Destroy Comment', [comment.article, comment],
               method: :delete,
               data: { confirm: 'Are you sure?' } %>
</p>
~~~

Here is the error message I got:
~~~
NoMethodError in Articles#show
Showing /Users/eiyasushiki/Desktop/Cameo/app/views/comments/_comment.html.erb where line #12 raised:

undefined method `article_comment_path' for #<#<Class:0x007f8b15174f88>:0x007f8b19170f60>
Extracted source (around line #12):              

<p>
  <%= link_to 'Destroy Comment',
              [ comment.article, comment ],
              method: :delete,
              data: { confirm: 'Are you sure?' } %>

Trace of template inclusion: app/views/articles/show.html.erb

Rails.root: /Users/eiyasushiki/Desktop/Cameo

Application Trace | Framework Trace | Full Trace
app/views/comments/_comment.html.erb:12:in `_app_views_comments__comment_html_erb___1475545422721524329_70117699327520'
app/views/articles/show.html.erb:12:in `_app_views_articles_show_html_erb___1983865233824308479_70117665664900'
Request

Parameters:

{"data"=>{"confirm"=>"Are you sure?"},
 "method"=>"delete",
 "id"=>"7"}
~~~

Thanks!

**Comment by connorshea** [comment]
Right below the HTML is some controller code:

```
def destroy
    @article = Article.find(params[:article_id])
    @comment = @article.comments.find(params[:id])
    @comment.destroy
    redirect_to article_path(@article)
end
```

Do you have this in there? It's necessary for Rails to understand what delete is supposed to do for a comment.

Hopefully that helps, good luck learning Rails! :D

**Comment by connorshea** [comment]
@Mr-DwZ Also, I looked at Cameo. I'm assuming that's the app you're building? If so, you're using Rails 4.2.5.2, which is the latest stable version. However, the guides you linked are the "edge guides", meaning you're viewing the guides for the Rails 5.0.0 Beta. This shouldn't cause any major issues, but I'd probably recommend using [the normal guides site](http://guides.rubyonrails.org/getting_started.html).

I don't think that's communicated clearly enough by the guides, so I wanted to point it out :)

**Comment by Mr-DwZ** [comment]
@connorshea Ruby community is fabulous! 

Yes, I've already added those code in comments_controller.rb, and I pushed the exactly version I test to my github corresponding repo just now.

**Comment by connorshea** [comment]
I just pulled down your repo and tried it out, this is the error I'm getting:

![screen shot 2016-03-02 at 9 18 33 pm](https://cloud.githubusercontent.com/assets/2977353/13484568/6556bf14-e0bc-11e5-9ee4-a129c0268187.png)

Is this the same as you're seeing?

**Comment by connorshea** [comment]
Oh, I figured it out!

If you use this it'll work:

```erb
<%= link_to 'Destroy Comment',
              article_comments_path(comment),
              method: :delete,
              data: { confirm: 'Are you sure?' } %>
```

**Comment by Mr-DwZ** [comment]
@connorshea 
Thanks a lot!
Could I know the reason for this change?

**Comment by connorshea** [comment]
I'm not sure why the guide says to use `[ comment.article, comment ]`, I can't seem to get that or any variation of it to work. And that section of the guide seems the same between Rails 4.2.5 and 5.0.0. Maybe something else changed in the guide that caused this?

Anyway, @Mr-DwZ hopefully that should work!

**Comment by connorshea** [comment]
@Mr-DwZ per my screenshot, it says "Did you mean? `article_comments_path`". In Rails' `link_to` helper you pass it like this: `<%= link_to "Link text here", whatever_path %>`.

So I did:

```
<%= link_to 'Destroy Comment',
          article_comments_path,
          method: :delete,
          data: { confirm: 'Are you sure?' } %>
```

That told me I didn't pass in a specific comment to delete, so I added that as an argument for the path, e.g. `article_comments_path(comment)`.

Unfortunately that's probably not that great of an explanation, I'd recommend checking out [the Routes guide](http://guides.rubyonrails.org/routing.html) if you want to learn more.

I'll open a bug about the guide being potentially incorrect and see if we can fix it. Thank you for reporting your issue!

**Comment by Mr-DwZ** [comment]
@connorshea 
It's pleasant to see that previous problems solved. But I got another error message, suggest that the controller's part also need some modification.

![](http://7xo6vj.com1.z0.glb.clouddn.com/16-3-3/11214007.jpg)

**Comment by connorshea** [comment]
@Mr-DwZ that's the issue I was talking about with the `article_comments_path` not having an argument, so it doesn't know what comment to delete.

Are you using `article_comments_path` instead of `article_comments_path(comment)`, or something like that?

**Comment by connorshea** [comment]
@Mr-DwZ so apparently I was wrong, see [here](https://github.com/rails/rails/issues/24019#issuecomment-191582544). `resource :comments` should be `resources :comments`.

**Comment by Mr-DwZ** [comment]
@connorshea 
:-P So embarrassing.

Thanks a lot anyway :-D

**Comment by prathamesh-sonpatki** [comment]
@connorshea @Mr-DwZ Thanks! Can this issue be closed now :smile: ?

**Comment by basicfeatures** [comment]
It's 2021 -- why is this problem still here? @connorshea thanks for the fix!
