### ISSUE TITLE
In production, custom autoload_paths are not respected

### ISSUE THREAD

**Issue by tmorton** [rails/rails#24012]
When both `config.cache_classes` and `config.eager_load` are set to `true` (as in the default production environment), custom paths added to `config.autoload_paths` are not respected.  

This can be fixed by any of these workarounds:
- Add the path to `config.eager_load_paths`
- Set `config.cache_classes` to false
- Set `config.eager_load` to false

### Steps to reproduce

-  In `application.rb` add a custom autoload path: 
```ruby
config.autoload_paths << Rails.root.join('lib')
```
- Put a ruby file in that class
```ruby
#lib/foo.rb
class Foo
end
```
-  Open a console in the production environment, and try to use the class
```
Loading production environment (Rails 5.0.0.beta3)
irb(main):001:0> Foo
NameError: uninitialized constant Foo
```

### Expected behavior
The `Foo` constant should be evaluated to the `Foo` class defined in the autoloaded path.

### Actual behavior
NameError is raised.

### System configuration
**Rails version**:
5.0.0.beta3

**Ruby version**:
ruby 2.3.0p0 (2015-12-25 revision 53290) [x86_64-darwin15]

**Comment by rafaelfranca** [comment]
That is expected. You should be using `eager_load_paths`. See https://github.com/rails/rails/commit/212ef5278b673aee304519d886d5db86a87b1437

**Comment by pixeltrix** [comment]
Related: a71350cae0082193ad8c66d65ab62e8bb0b7853b

**Comment by mustmodify** [comment]
I realize POLS only applies to Matz. Still, it's a good principle... as a developer, I find it rather surprising that an option that is not environment-specific works in some environments and not in others. It allows a developer to go on thinking they have a valid solution, only to be confused by a NameError in production.

Personally I would be OK with continuing to load constants on demand. But if that isn't acceptable for whatever reason, shouldn't we get rid of config.autoload_paths, rather than forcing people to hunt down this ticket?

**Comment by mustmodify** [comment]
Or maybe just ... `load_paths` which would append to autoload in dev and eager_load in production? If there is support for this I'd be happy to put together a PR.

**Comment by pixeltrix** [comment]
@mustmodify we already looked at merging them for Rails 4.0 but after a long discussion it was decided that it wasn't possible to merge them - there are Rails apps out there that have so many models that eager loading them in production uses too much memory so making an assumption of eager loading in production doesn't work.

**Comment by mustmodify** [comment]
I see. I noticed there was a configuration option to eager load in production -- would that not solve the issue you mentioned?

Pseudo-code:

```
if( production && !eager_load_in_production )
  eagerload_paths += custom_load_paths
else
  autoload_paths += custom_load_paths
end
```
