### ISSUE TITLE
Concerns with deferred Action Cable connection opening

### ISSUE THREAD

**Issue by javan** [rails/rails#24026]
https://github.com/rails/rails/commit/1afd414488fe73c927242e072af0ff9ab21d2599 introduced a change that defers opening a WebSocket connection until data is sent, which could be problematic. I outlined some concerns in https://github.com/rails/rails/commit/1afd414488fe73c927242e072af0ff9ab21d2599#commitcomment-16450672. It's not clear why this change was needed to implement https://github.com/rails/rails/pull/23488 and the commit message doesn't help clarify.

Even if it works, I don't think the logic is quite right. Every call to `send` when the WebSocket's state isn't `OPEN` will attempt to open a connection ignoring the possibility that the state is `CONNECTING`.

@maclover7, can you explain the purpose of the change? And please consider revising or reverting before another Rails release goes out.

/cc @dhh

**Comment by javan** [comment]
To illustrate the problem, create an app with two channels. I added console logging to each channel's .js file:

<img width="434" alt="screen shot 2016-03-03 at 9 42 57 am" src="https://cloud.githubusercontent.com/assets/5355/13497652/9232178c-e124-11e5-81ca-80f5e76f1a9f.png">

**Comment by dhh** [comment]
I haven't dug into the implementation, but the point was that createConsumer should be lazy loaded. Such that all new apps could start with a call to that, but that a consumer wouldn't actually establish the WS connection until the first subscription call was made.

**Comment by matthewd** [comment]
It was necessary in order to enable Action Cable routes by default *without suddenly forcing apps to auto-connect for no reason*.

When @dhh and I discussed it, we concluded there was no need to be able to receive data if you haven't subscribed to anything -- because, what would you get?

> Every call to send when the WebSocket's state isn't OPEN will attempt to open a connection ignoring the possibility that the state is CONNECTING.

Ah, I think I missed the fact that CONNECTING counts as isAlive().

> Opening a WebSocket connection is asynchronous so calling open and then immediately calling send will probably fail. isOpen will return false and the data won't be sent.

Right.. at which point the application should handle it as a retry, just as it must for any other failed send.. no?

We considered queuing such messages and sending them once we'd connected, but that seemed against the spirit of the existing "fail if not currently open" logic.

**Comment by matthewd** [comment]
Incidentally, I believe there's an issue with the current behaviour anyway: it still seems to connect without any subscription defined / data sent. I'm guessing the auto-reconnect behaviour in the connection manager is still kicking in.

**Comment by javan** [comment]
> Such that all new apps could start with a call to that, but that a consumer wouldn't actually establish the WS connection until the first subscription call was made.

In that case, I think the subscription manager should ensure a connection when adding a subscription instead of overloading Connection#send with that responsibility. Something like:

```diff
--- a/actioncable/app/assets/javascripts/action_cable/subscriptions.coffee
+++ b/actioncable/app/assets/javascripts/action_cable/subscriptions.coffee
@@ -19,6 +19,7 @@ class ActionCable.Subscriptions
 
   add: (subscription) ->
     @subscriptions.push(subscription)
+    @ensureConnection()
     @notify(subscription, "initialized")
     @sendCommand(subscription, "subscribe")
 
@@ -62,3 +63,7 @@ class ActionCable.Subscriptions
       @consumer.connection.isOpen()
     else
       @consumer.send({command, identifier})
+
+  ensureConnection: ->
+    unless @consumer.connection.isAlive()
+      @consumer.connection.open()
```

**Comment by dhh** [comment]
Yup, sounds better to me!

**Comment by javan** [comment]
Opened a PR to do that: https://github.com/rails/rails/pull/24036
