### ISSUE TITLE
Duplicate insert on autosave for specific HABTM-has_one combo

### ISSUE THREAD

**Issue by nbekirov** [rails/rails#24032]
### Steps to reproduce

``` ruby
class Organisation < ActiveRecord::Base
  has_one :user
end

class User < ActiveRecord::Base
  has_and_belongs_to_many :roles
  belongs_to :organisation
end

class Role < ActiveRecord::Base
  has_and_belongs_to_many :users
end

user = User.new
user.organisation = Organisation.new
user.roles << Role.new
user.save!
```

Here is my [Active Record Executable Test Case](https://gist.github.com/nbekirov/01c34d2b99ed5bcf9154)

This issue is related to [Rolify: Duplicate Roles #228](https://github.com/RolifyCommunity/rolify/issues/228)

Some observations:
- If I change the order of `has_and_belongs_to_many` and `belongs_to` in `User` there is no issue
- If I add `autosave: false` to `has_and_belongs_to_many` in `User` there is no issue

Here is an issue I've found that seems related but I don't think is quite the same: [has_and_belongs_to_many autosaves duplicate records](https://github.com/rails/rails/issues/3639)
### Expected behavior

One `User` with one `Organisation` and one `Role` saved

``` sql
INSERT INTO "organisations" DEFAULT VALUES
INSERT INTO "users" ("organisation_id") VALUES (?)  [["organisation_id", 1]]
INSERT INTO "roles" DEFAULT VALUES
INSERT INTO "roles_users" ("user_id", "role_id") VALUES (?, ?)  [["user_id", 1], ["role_id", 1]]
```
### Actual behavior

One `User` with one `Organisation` and **two** `Role`-s saved

``` sql
INSERT INTO "organisations" DEFAULT VALUES
INSERT INTO "users" ("organisation_id") VALUES (?)  [["organisation_id", 1]]
INSERT INTO "roles" DEFAULT VALUES
INSERT INTO "roles_users" ("user_id", "role_id") VALUES (?, ?)  [["user_id", 1], ["role_id", 1]]
INSERT INTO "roles_users" ("user_id", "role_id") VALUES (?, ?)  [["user_id", 1], ["role_id", 1]]
```
### System configuration

**Rails version**:
N/A

**Ruby version**:

``` bash
$ ruby -v
ruby 2.3.0p0 (2015-12-25 revision 53290) [x86_64-linux-gnu]
```

**Comment by meinac** [comment]
Also If you change `has_one :user` to `has_many :users` or ?`has_one :users`? it works as expected, interesting :confused:

**Comment by betesh** [comment]
Introduced in c7adc610f0

**Comment by meinac** [comment]
@rafaelfranca I see that this has been added into 5.1 milestone, do you want to go with the existing pr or do you think something different.

**Comment by rafaelfranca** [comment]
Oh, I thought it was caused by a commit only present in 5.1, but seems this bug is also present in 4.2. I'm removing the milestone and I'll leave the PR review with @sgrif

**Comment by betesh** [comment]
There's definitely a regression from 5.0.2 to 5.1.0.  Is @nbekirov's test case is failing on 4.2?  If so, I'll try to put together another test case that demonstrates the issue.

Basically, what I'm seeing is that when upgrading from 5.0.2 to 5.1.0.beta1, I get `ActiveRecord::StatementInvalid` from a `has_and_belongs_to_many` with a unique index on the join table.  `autosave: false` fixes it, as does moving the `has_and_belongs_to_many` to after all the `belongs_to`'s.

**Comment by rafaelfranca** [comment]
Yes, it is failing in 4.2 https://gist.github.com/nbekirov/01c34d2b99ed5bcf9154#file-rolif_test-rb-L11.

**Comment by betesh** [comment]
Here's the regression:

```
begin
  require 'bundler/inline'
rescue LoadError => e
  $stderr.puts 'Bundler version 1.10 or later is required. Please update your Bundler'
  raise e
end

gemfile(true) do
  source 'https://rubygems.org'
  # Activate the gem you are reporting the issue against.
  # gem 'activerecord', '5.1.0.beta1' # FAILS with this uncommented
  gem 'activerecord', '5.0.2' # PASSES with this uncommented
  gem 'sqlite3'
end

require 'active_record'
require 'minitest/autorun'
require 'logger'

# This connection will do for database-independent bug reports.
ActiveRecord::Base.establish_connection(adapter: 'sqlite3', database: ':memory:')
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :organisations, force: true do |t|
  end

  create_table :users, force: true do |t|
    t.references :organisation, index: true
  end

  create_table :roles, force: true do |t|
  end

  create_join_table :roles, :users, force: true do |t|
    t.index [:user_id, :role_id], unique: true
  end
end

class Organisation < ActiveRecord::Base
  has_one :user
end

class User < ActiveRecord::Base
  has_and_belongs_to_many :roles
  belongs_to :organisation
  accepts_nested_attributes_for :organisation
end

class Role < ActiveRecord::Base
  has_and_belongs_to_many :users
end

class BugTest < ActiveSupport::TestCase
  def test_association
    assert_nothing_raised { User.create! organisation: Organisation.new, roles: [Role.new] }
  end
end
```

I do remember reading a bug report about using accepts_nested_attributes for a has_one relationship--I'll see if I can find the ticket.

**Comment by betesh** [comment]
I opened PR #28596 for this.  So far, it's just a failing test case.

**Comment by betesh** [comment]
PR #28596 is ready
