### ISSUE TITLE
Rails 5.0.0.beta3: Development environment: Assets not (re-)loaded with HTTP requests (javascript not working)

### ISSUE THREAD

**Issue by john-999** [rails/rails#24033]
Using Rails 5.0.0.beta3, I render a typical full "edit profile" page using a GET request.

The problem: The javascript/jQuery features do not work on this page anymore, once the page has loaded. (However, if I hit "reload", these features do work again.)

The page structure looks like this:

    <section class="users" id="registrations_edit">

      <%= link_to 'Change password', '#void', id: 'change_password' %>

      <div id="password_modification">
	
		[...some form fields here...]

      </div>

    </section>

The JS code looks like this:

    $(function() {

      // The below click only works when the page is manually reloaded:

      $('section.users#registrations_edit').on('click', 'a#change_password', function(e) {
        e.preventDefault();
        $('div#password_modification').toggle();
      });
  
  
      // The below alert message only appears when the page is manually reloaded:
	
      if ($('section.users#registrations_edit').length) {
        alert('Hey there.');
      }
  
    });

My gems that could be the source of the problem:
- Rails 5.0.0.beta3
- jquery-rails (4.1.0)
- jquery-turbolinks (2.1.0)
- turbolinks (5.0.0.beta2)

EDIT:
I just noticed that while browsing the site in question (still in dev mode), I see in the server logs that the assets are not loaded again, when the next page is loaded. Is this the reason for my issue? What's the best way to deal with this? (This behavior is new, right?)

EDIT 2:
Added demo app: https://github.com/john-999/javascript_not_working

**Comment by maclover7** [comment]
cc @schneems

**Comment by schneems** [comment]
I think this is a turbolinks issue

**Comment by schneems** [comment]
Can you give us a small app that reproduces the problem?

**Comment by rafaelfranca** [comment]
Yes, this looks like the turbolinks behavior.

**Comment by john-999** [comment]
@schneems @rafaelfranca  - I have added a demo app.

**Comment by HardieBoeve** [comment]
I made a pull request on your demo app, with a fix for your problem.

The fix is very simple, you are listening for the jQuery ready event, and this is only triggered in the initial page load. Instead you should listen for the turbolinks:load event, [more info](https://github.com/turbolinks/turbolinks)

```js
document.addEventListener("turbolinks:load", function() {
  // Toggle visibility of password fields
  $('section.users#registrations_edit').on('click', 'a#change_password', function(e) {
    e.preventDefault();
    $('div#password_modification').toggle();
  });

  if ($('section.users#registrations_edit').length) {
    alert('Hey there.');
  }  
});
```

**Comment by john-999** [comment]
Thanks a lot @HardieBoeve ! (I assume lots of folks will run into this change when Rails 5 is released.)

**Comment by prathamesh-sonpatki** [comment]
It's mentioned in the edge guides - http://edgeguides.rubyonrails.org/working_with_javascript_in_rails.html#page-change-events
