### ISSUE TITLE
Rails 5 respond_to unexpected behaviour

### ISSUE THREAD

**Issue by petermumford** [rails/rails#24035]
### Steps to reproduce
I have a simple **link_to** method and in my controller I have a **respond_to** block if I add a `format.xml` it will always use this instead of the `format.any` call. See my code below:

**.html.erb**
`<%= link_to 'Edit', edit_car_path(car) %>`

**controller.rb**
``` Ruby
  def edit
    respond_to do |format|
      # format.any(:js, :json, :xml) { head(401) }
      format.xml { head(401) }
      format.any { redirect_to root_url }
    end
  end
```

**output from console**
```
Started GET "/cars/1/edit" for ::1 at 2016-03-04 08:14:35 +0000
Processing by CarsController#edit as HTML
  Parameters: {"id"=>"1"}
  Organiser Load (0.6ms)  SELECT  "cars".* FROM "cars" WHERE "cars"."id" = $1 LIMIT $2  [["id", 1], ["LIMIT", 1]]
Completed 401 Unauthorized in 4ms (ActiveRecord: 1.0ms)
```
### Expected behavior
Should ignore `format.xml` and redirect to the home page

### Actual behavior
`format.any` is never used and always uses `format.xml`

### System configuration
**Rails version**: 5.0.0.beta3
**Ruby version**: 2.2.3

**Comment by bronson** [comment]
r? @chancancode

Sounds related to https://github.com/rails/rails/issues/23881

**Comment by sikachu** [comment]
This is not related to #23881. It's an issue with Turbolinks.

I've tried to generate the test app, create the scaffold (`rails g scaffold car name:string`), edit the generated controller to include the snippet similar to above.

If I access the page directly (http://localhost:3000/cars/1/edit) then I got this in log:

> Started GET "/cars/1/edit" for ::1 at 2016-03-04 13:31:15 -0500
> Processing by CarsController#edit as HTML
>   Parameters: {"id"=>"1"}
>   Car Load (0.2ms)  SELECT  "cars".* FROM "cars" WHERE "cars"."id" = ? LIMIT ?  [["id", 1], ["LIMIT", 1]]
> Redirected to http://localhost:3000/cars
> Completed 302 Found in 2ms (ActiveRecord: 0.2ms)

If I click the link from the page (which triggers Turbolink), then I get this in log:

> Processing by CarsController#edit as HTML
>   Parameters: {"id"=>"1"}
>   Car Load (0.2ms)  SELECT  "cars".* FROM "cars" WHERE "cars"."id" = ? LIMIT ?  [["id", 1], ["LIMIT", 1]]
> Completed 401 Unauthorized in 2ms (ActiveRecord: 0.2ms)

And this is in Chrome Inspector:

<img width="915" alt="screen shot 2016-03-04 at 1 34 02 pm" src="https://cloud.githubusercontent.com/assets/4912/13536443/e2de2bf0-e20d-11e5-859e-67478adf68a7.png">

I think we need to figure out why it's acting that way for Turbolinks requests.

**Comment by sikachu** [comment]
Oh, and this is the log for the direct request to `/cars/1/edit`:

<img width="932" alt="screen shot 2016-03-04 at 1 45 27 pm" src="https://cloud.githubusercontent.com/assets/4912/13536723/6f08ea2e-e20f-11e5-863b-6541e47d8a1c.png">

**Comment by petermumford** [comment]
I can confirm this is exactly what I am getting as well. Also, if you add `data: {turbolinks: false}` to the **link_to** method it will also work as expected, hinting towards Turbolinks again.

```ruby
<%= link_to 'Edit', edit_car_path(car), data: {turbolinks: false} %>
```

**Comment by maclover7** [comment]
Can you open up an issue at [https://github.com/turoblinks/turbolinks](https://github.com/turoblinks/turbolinks)?

**Comment by petermumford** [comment]
@maclover7 I've just done this for you.

**Comment by kaspth** [comment]
Closing because the issue seems to be with Turbolinks.
