### ISSUE TITLE
PG::ConnectionBad: PQconsumeInput() : SELECT.....

### ISSUE THREAD

**Issue by mwangm** [rails/rails#24041]
Use Active Record to access postgreSQL DB in our app,  Then we get a error in prod is like this 

```
PG::ConnectionBad: PQconsumeInput() : SELECT...
PG::ConnectionBad: PQsocket() can't get socket descriptor: SELECT...
PG::ConnectionBad: PQsocket() can't get socket descriptor: SELECT...
```

 The reason it happend beacuse the db connection got stopped or killed by database for some reason(maybe network problem). But the active record connection poll will not repair this connection and keep it in the pool. That's bad.
### Steps to reproduce
1. connect your app to postgreSQL DB, loop to query something from db table.  
2. run a sql in db to kill the connection, then you got the error  
### Expected behavior

  the connection could be repaired 
### Actual behavior

   the broken connection stay there,  the app keep get the error
     `PG::ConnectionBad: PQsocket() can't get socket descriptor: SELECT...`
#### Rails version:

 N/A
#### Ruby version:

 2.1.5

**Comment by maclover7** [comment]
Can you create an executable test script using one of the templates [here](https://github.com/rails/rails/tree/master/guides/bug_report_templates), that would demonstrate the problem you are seeing?

**Comment by mwangm** [comment]
@maclover7 could you check [this one](https://gist.github.com/mwangm/f302aa310ea24f2ca5d9)

**Comment by yawboakye** [comment]
@mwangm Can you help me understand why the connection should be repaired? Since `pg_terminate_backend` is a deliberate action to terminate a connection to the database, and not run by the database server itself, it appears to me that that should be respected. You can always re-connect by restarting your server.

**Comment by mwangm** [comment]
@yawboakye It happened when db server had some accidents and restart to recovery, That's how we got this error.
