### ISSUE TITLE
4.2.5.2 breaks backward compatibility with 4.2.5 due to attempted performance tweak

### ISSUE THREAD

**Issue by belucid** [rails/rails#24048]
### Steps to reproduce

Run your working 4.5.2 project (that uses less-rails 2.7) on 4.2.5.2

### Expected behavior

It works.

### Actual behavior

It doesn't work.

Comes from this commit:

https://github.com/rails/rails/commit/25f1d5da37811644c81127e9219fc070953776e0

Problem with this change is that tsort_each returns nil whereas tsort.each returns an empty array. So this breaks backwards compatibility with 4.2.5 at a security fix (4.2.5.2) which is... bad.

```
Users/sean/.rvm/gems/ruby-2.2.4@hex/gems/less-rails-2.7.0/lib/less/rails/railtie.rb:19:in `block in <class:Railtie>': undefined method `register_preprocessor' for nil:NilClass (NoMethodError)
	from /Users/sean/.rvm/gems/ruby-2.2.4@hex/gems/railties-4.2.5.2/lib/rails/initializable.rb:30:in `instance_exec'
	from /Users/sean/.rvm/gems/ruby-2.2.4@hex/gems/railties-4.2.5.2/lib/rails/initializable.rb:30:in `run'
	from /Users/sean/.rvm/gems/ruby-2.2.4@hex/gems/railties-4.2.5.2/lib/rails/initializable.rb:55:in `block in run_initializers'
	from /Users/sean/.rvm/rubies/ruby-2.2.4/lib/ruby/2.2.0/tsort.rb:226:in `block in tsort_each'
```
### System configuration

**Rails version**:

4.2.5.2

**Ruby version**:

2.2.4

**Comment by belucid** [comment]
In case anyone runs into this exact same error, I resolved it by upgrading to less-rails 2.7.1.

**Comment by matthewd** [comment]
It sounds like you updated other gems (namely, sprockets and/or sprockets-rails). I doubt a commit from 2012 that's been present since Rails 4.0 was particularly involved.

**Comment by belucid** [comment]
Yup. My bad. Saw that was the last commit, but didn't notice the date was 2012.
