### ISSUE TITLE
Rails 5.0.0beta3 cannot load such file -- listen

### ISSUE THREAD

**Issue by sadinie** [rails/rails#24063]
### Steps to reproduce

Updated gemfile to beta3
ran bundle update rails
ran rake rails:update
started my app in dev mode
### Expected behavior

Rails should start up
### Actual behavior

Crashed
/home/sadinie/dev/ruby/lib64/ruby/gems/2.3.0/gems/activesupport-5.0.0.beta3/lib/active_support/dependencies.rb:302:in `require': cannot load such file -- listen (LoadError)
### System configuration

**Rails version**: 5.0.0.beta3

**Ruby version**: ruby 2.3.0p0 (2015-12-25 revision 53290) [x86_64-linux]

I commented out the block in activesupport-5.0.0.beta3/lib/active_support/evented_file_update_checker.rb:24 just so it runs, but seems to be causing the server to need
to be restarted after any change, like in controllers or models.

Full stack trace

/home/sadinie/dev/ruby/lib64/ruby/gems/2.3.0/gems/activesupport-5.0.0.beta3/lib/active_support/dependencies.rb:302:in `require': cannot load such file -- listen (LoadError)
    from /home/sadinie/dev/ruby/lib64/ruby/gems/2.3.0/gems/activesupport-5.0.0.beta3/lib/active_support/dependencies.rb:302:in`block in require'
    from /home/sadinie/dev/ruby/lib64/ruby/gems/2.3.0/gems/activesupport-5.0.0.beta3/lib/active_support/dependencies.rb:268:in `load_dependency'
    from /home/sadinie/dev/ruby/lib64/ruby/gems/2.3.0/gems/activesupport-5.0.0.beta3/lib/active_support/dependencies.rb:302:in`require'
    from /home/sadinie/dev/ruby/lib64/ruby/gems/2.3.0/gems/activesupport-5.0.0.beta3/lib/active_support/evented_file_update_checker.rb:24:in `block in initialize'
    from /home/sadinie/dev/ruby/lib64/ruby/gems/2.3.0/gems/activesupport-5.0.0.beta3/lib/active_support/core_ext/kernel/reporting.rb:13:in`block in silence_warnings'
    from /home/sadinie/dev/ruby/lib64/ruby/gems/2.3.0/gems/activesupport-5.0.0.beta3/lib/active_support/core_ext/kernel/reporting.rb:26:in `with_warnings'
    from /home/sadinie/dev/ruby/lib64/ruby/gems/2.3.0/gems/activesupport-5.0.0.beta3/lib/active_support/core_ext/kernel/reporting.rb:13:in`silence_warnings'
    from /home/sadinie/dev/ruby/lib64/ruby/gems/2.3.0/gems/activesupport-5.0.0.beta3/lib/active_support/evented_file_update_checker.rb:24:in `initialize'
    from /home/sadinie/dev/ruby/lib64/ruby/gems/2.3.0/gems/activesupport-5.0.0.beta3/lib/active_support/i18n_railtie.rb:59:in`new'
    from /home/sadinie/dev/ruby/lib64/ruby/gems/2.3.0/gems/activesupport-5.0.0.beta3/lib/active_support/i18n_railtie.rb:59:in `initialize_i18n'
    from /home/sadinie/dev/ruby/lib64/ruby/gems/2.3.0/gems/activesupport-5.0.0.beta3/lib/active_support/i18n_railtie.rb:15:in`block in class:Railtie'
    from /home/sadinie/dev/ruby/lib64/ruby/gems/2.3.0/gems/activesupport-5.0.0.beta3/lib/active_support/lazy_load_hooks.rb:36:in `execute_hook'
    from /home/sadinie/dev/ruby/lib64/ruby/gems/2.3.0/gems/activesupport-5.0.0.beta3/lib/active_support/lazy_load_hooks.rb:45:in`block in run_load_hooks'
    from /home/sadinie/dev/ruby/lib64/ruby/gems/2.3.0/gems/activesupport-5.0.0.beta3/lib/active_support/lazy_load_hooks.rb:44:in `each'
    from /home/sadinie/dev/ruby/lib64/ruby/gems/2.3.0/gems/activesupport-5.0.0.beta3/lib/active_support/lazy_load_hooks.rb:44:in`run_load_hooks'
    from /home/sadinie/dev/ruby/lib64/ruby/gems/2.3.0/gems/railties-5.0.0.beta3/lib/rails/application/finisher.rb:62:in `block in <module:Finisher>'
    from /home/sadinie/dev/ruby/lib64/ruby/gems/2.3.0/gems/railties-5.0.0.beta3/lib/rails/initializable.rb:30:in`instance_exec'
    from /home/sadinie/dev/ruby/lib64/ruby/gems/2.3.0/gems/railties-5.0.0.beta3/lib/rails/initializable.rb:30:in `run'
    from /home/sadinie/dev/ruby/lib64/ruby/gems/2.3.0/gems/railties-5.0.0.beta3/lib/rails/initializable.rb:55:in`block in run_initializers'
    from /home/sadinie/dev/ruby/lib64/ruby/2.3.0/tsort.rb:228:in `block in tsort_each'
    from /home/sadinie/dev/ruby/lib64/ruby/2.3.0/tsort.rb:350:in`block (2 levels) in each_strongly_connected_component'
    from /home/sadinie/dev/ruby/lib64/ruby/2.3.0/tsort.rb:431:in `each_strongly_connected_component_from'
    from /home/sadinie/dev/ruby/lib64/ruby/2.3.0/tsort.rb:349:in`block in each_strongly_connected_component'
    from /home/sadinie/dev/ruby/lib64/ruby/2.3.0/tsort.rb:347:in `each'
    from /home/sadinie/dev/ruby/lib64/ruby/2.3.0/tsort.rb:347:in`call'
    from /home/sadinie/dev/ruby/lib64/ruby/2.3.0/tsort.rb:347:in `each_strongly_connected_component'
    from /home/sadinie/dev/ruby/lib64/ruby/2.3.0/tsort.rb:226:in`tsort_each'
    from /home/sadinie/dev/ruby/lib64/ruby/2.3.0/tsort.rb:205:in `tsort_each'
    from /home/sadinie/dev/ruby/lib64/ruby/gems/2.3.0/gems/railties-5.0.0.beta3/lib/rails/initializable.rb:54:in`run_initializers'
    from /home/sadinie/dev/ruby/lib64/ruby/gems/2.3.0/gems/railties-5.0.0.beta3/lib/rails/application.rb:350:in `initialize!'
    from /home/sadinie/projects/jade-projects/jade/config/environment.rb:5:in`<top (required)>'
    from /home/sadinie/dev/ruby/lib64/ruby/gems/2.3.0/gems/activesupport-5.0.0.beta3/lib/active_support/dependencies.rb:302:in `require'
    from /home/sadinie/dev/ruby/lib64/ruby/gems/2.3.0/gems/activesupport-5.0.0.beta3/lib/active_support/dependencies.rb:302:in`block in require'
    from /home/sadinie/dev/ruby/lib64/ruby/gems/2.3.0/gems/activesupport-5.0.0.beta3/lib/active_support/dependencies.rb:268:in `load_dependency'
    from /home/sadinie/dev/ruby/lib64/ruby/gems/2.3.0/gems/activesupport-5.0.0.beta3/lib/active_support/dependencies.rb:302:in`require'
    from /home/sadinie/projects/jade-projects/jade/config.ru:3:in `block in <main>'
    from /home/sadinie/dev/ruby/lib64/ruby/gems/2.3.0/gems/rack-2.0.0.alpha/lib/rack/builder.rb:55:in`instance_eval'
    from /home/sadinie/dev/ruby/lib64/ruby/gems/2.3.0/gems/rack-2.0.0.alpha/lib/rack/builder.rb:55:in `initialize'
    from /home/sadinie/projects/jade-projects/jade/config.ru:in`new'
    from /home/sadinie/projects/jade-projects/jade/config.ru:in `<main>'
    from /home/sadinie/dev/ruby/lib64/ruby/gems/2.3.0/gems/rack-2.0.0.alpha/lib/rack/builder.rb:49:in`eval'
    from /home/sadinie/dev/ruby/lib64/ruby/gems/2.3.0/gems/rack-2.0.0.alpha/lib/rack/builder.rb:49:in `new_from_string'
    from /home/sadinie/dev/ruby/lib64/ruby/gems/2.3.0/gems/rack-2.0.0.alpha/lib/rack/builder.rb:40:in`parse_file'
    from /home/sadinie/dev/ruby/lib64/ruby/gems/2.3.0/gems/rack-2.0.0.alpha/lib/rack/server.rb:318:in `build_app_and_options_from_config'
    from /home/sadinie/dev/ruby/lib64/ruby/gems/2.3.0/gems/rack-2.0.0.alpha/lib/rack/server.rb:218:in`app'
    from /home/sadinie/dev/ruby/lib64/ruby/gems/2.3.0/gems/railties-5.0.0.beta3/lib/rails/commands/server.rb:58:in `app'
    from /home/sadinie/dev/ruby/lib64/ruby/gems/2.3.0/gems/rack-2.0.0.alpha/lib/rack/server.rb:353:in`wrapped_app'
    from /home/sadinie/dev/ruby/lib64/ruby/gems/2.3.0/gems/railties-5.0.0.beta3/lib/rails/commands/server.rb:136:in `log_to_stdout'
    from /home/sadinie/dev/ruby/lib64/ruby/gems/2.3.0/gems/railties-5.0.0.beta3/lib/rails/commands/server.rb:76:in`start'
    from /home/sadinie/dev/ruby/lib64/ruby/gems/2.3.0/gems/railties-5.0.0.beta3/lib/rails/commands/commands_tasks.rb:90:in `block in server'
    from /home/sadinie/dev/ruby/lib64/ruby/gems/2.3.0/gems/railties-5.0.0.beta3/lib/rails/commands/commands_tasks.rb:85:in`tap'
    from /home/sadinie/dev/ruby/lib64/ruby/gems/2.3.0/gems/railties-5.0.0.beta3/lib/rails/commands/commands_tasks.rb:85:in `server'
    from /home/sadinie/dev/ruby/lib64/ruby/gems/2.3.0/gems/railties-5.0.0.beta3/lib/rails/commands/commands_tasks.rb:49:in`run_command!'
    from /home/sadinie/dev/ruby/lib64/ruby/gems/2.3.0/gems/railties-5.0.0.beta3/lib/rails/command.rb:20:in `run'
    from /home/sadinie/dev/ruby/lib64/ruby/gems/2.3.0/gems/railties-5.0.0.beta3/lib/rails/commands.rb:18:in`<top (required)>'
    from /home/sadinie/projects/jade-projects/jade/bin/rails:4:in `require'
    from /home/sadinie/projects/jade-projects/jade/bin/rails:4:in`<top (required)>'
    from -e:1:in `load'
    from -e:1:in`<main>'

Process finished with exit code 1

**Comment by maclover7** [comment]
cc @fxn

**Comment by rizidoro** [comment]
You should add the `listen` gem in the `development` group

**Comment by fxn** [comment]
As per your application you can either comment out the evented monitor in *config/environments/development.rb* to disable it, or add the listen gem to the *Gemfile* if you'd like to use the monitor.

As per the issue itself, goint to close because we are talking about what to do in https://github.com/rails/rails/pull/24066.

**Comment by rajeev-khangar** [comment]
Hello,

I am still getting issue like
00:45 deploy:assets:precompile
      01 ~/.rvm/bin/rvm default do bundle exec rake assets:precompile
      01 rake aborted!
      01 LoadError: Could not load the 'listen' gem. Add `gem 'listen'` to the development group of your Gemfile


------------------
while I have added gem in my gemfile like
group :development do
  # Access an IRB console on exception pages or by using <%= console %> anywhere in the code.
  gem 'web-console'
  gem 'listen'
end

------------
Please suggest to me what should I do.
I am using Rails 5 and ruby 2.3.1

**Comment by pitops** [comment]
i came across the same situation as @rajeev-khangar

**Comment by wicky-info** [comment]
same here, problem in rails 5

**Comment by pitops** [comment]
A temporary solution i found is to move it outside of development group.

**Comment by wicky-info** [comment]
thank you @pitops , I move outside.
![screenshot from 2016-10-22 09 35 46](https://cloud.githubusercontent.com/assets/8560064/19889906/4162d9a8-a06a-11e6-9a26-0246876e7508.png)

**Comment by pierrediderot** [comment]
+1

**Comment by teaearlgraycold** [comment]
Same problem, was solved by moving listen gem outside of the dev group.

Rails 5.0.1

**Comment by acandael** [comment]
had the same issue in Rails 5.0.0.1 and Ruby 2.3.1. Fixed it by putting listen gem outside of production group

**Comment by IlkhamGaysin** [comment]
I had the same trouble in Rails 5.0.1 and Ruby 2.3.1. The fix by putting outside of dev group has helped. :+1:

**Comment by atstockland** [comment]
Ruby 2.5.0, rails 5.2.0.beta2 --- listen gem still needs to be outside the development group even though the error message states: "Add `gem 'listen'` to the development group of your Gemfile".

**Comment by DanielJoyce** [comment]
Same bug here. In production mode, shouldn't need this gem

**Comment by fxn** [comment]
I reopened the issue, will investigate.

**Comment by stevensona** [comment]
@atstockland @DanielJoyce are you by chance attemping to precompile assets in *development* in an environment with *only production* gems installed? If you are, that error message makes sense.

**Comment by atstockland** [comment]
@stevensona no sir

**Comment by DanielJoyce** [comment]
@stevensona Looks like that might be the problem.

**Comment by jtopgi** [comment]
I accidentally used `rails_env=staging` instead of `RAILS_ENV=staging`.

**Comment by byroot** [comment]
Probably not worth keeping this open anymore.
