### ISSUE TITLE
enhancement: render(file:) should handle File

### ISSUE THREAD

**Issue by eiked** [rails/rails#24077]
The render(file:) option currently accepts strings (aka path names)

I'd like to suggest that the file: option should also accept File objects.

I use this with dynamically generated jpgs.
I put them into a Tempfile.

I currently need to do:
   render(file:tempfile.path)
but it would be more natural to just say:
   render(file:tempfile)

I'd like to suggest that the file: option should be enhanced to accept kind_of?(File) arguments.
And further more, the file: option should really be more strict on arguments checking.
I believe it currently does some kind of #to_s down there, which could become a security hole.

I'd like to suggest:
- improve checking of the file: argument
- if it's a String? then it needs to be sanitized (avoid '../../..' or '/' problems)
- if it's a File -- the same does apply.

back thought:
Like sanitizing parameters, we should also sanitize all file names.

**Comment by rafaelfranca** [comment]
Thank you so much for the issue but we don't take feature request on the issue tracker. We recommend you to try to implement the feature and send us a pull request or if you are in doubt if the feature will be accepts ask in Rails Core mailing list for feedback.

**Comment by kaspth** [comment]
@eiked 👋, just a friendly reminder that this is the ~3rd time we've asked you to submit feature requests to the Rails Core mailing list. Will you please do so in the future? Thanks ❤️
