### ISSUE TITLE
Eager loaded belongs_to associations are always readonly

### ISSUE THREAD

**Issue by bquorning** [rails/rails#24093]
### Steps to reproduce

https://gist.github.com/bquorning/0ac738564824aa8ce57b

### Expected behavior

Eager loaded belongs_to associations should not be readonly.

### Actual behavior

Eager loaded belongs_to associations are always readonly.

### System configuration
**Rails version**: v5.0.0.beta1 and up, including latest master

**Ruby version**: All.

### Extra

It seems the issue was introduced in #18097.

**Comment by madmax** [comment]
Any news on merge fix into 5.x?

**Comment by bquorning** [comment]
@madmax #24099 is in the 5.0.1 milestone. So I don’t imagine 5.0.1 will be released without this bug being fixed.

**Comment by madmax** [comment]
@bquorning thanks :)
