### ISSUE TITLE
ActionCable having troubles parsing JSON

### ISSUE THREAD

**Issue by nowakov** [rails/rails#24092]
### Steps to reproduce

I'm trying to connect with ActionCable, not using JS, but with websocket-client on raspi. So my simplified client-side example looks like this:
```
require 'websocket-client-simple'
require 'eventmachine'
require 'json'

subscribe_cmd = {
  command: 'subscribe',
  identifier: { channel: 'PrintersChannel' }
}
EM.run {
  url = 'ws://localhost:28080/cable'
  ws = WebSocket::Client::Simple.connect(url, headers: { printer_token: 'test-printer' })

  ws.on :open do |event|
    ws.send(JSON.generate(subscribe_cmd))
  end
}
```
and my connection.rb:
```
module ApplicationCable
  class Connection < ActionCable::Connection::Base
    identified_by :printer

    def connect
      self.printer = fetch_printer
    end

    protected

    def fetch_printer
      Printer.find_by_token(env['HTTP_PRINTER_TOKEN']) || reject_unauthorized_connection
    end

  end
end
```

### Expected behavior
If I use this hardcoded json string: `'{"command":"subscribe","identifier":"{\"channel\":\"PrintersChannel\"}"}'` it just works fine and I'd expect the same from generated JSON's

### Actual behavior
but instead I get this:
```
Registered connection (Z2lkOi8vc2tyaW1hcmtldC9QcmludGVyLzE)
Could not execute command from {"command"=>"subscribe", "identifier"=>{"channel"=>"PrintersChannel"}}) [TypeError - no implicit conversion of Hash into String]
```
There's actually not much information about non-JS actioncable connections so maybe I'm just doing it wrong? If that's the case what is the best way to communicate with actioncable from external devices? I'm planning to use it with python script on raspi and iOS devices.

### System configuration
**Rails version**: 5.0.0.beta3

**Ruby version**: 2.3.0

**Comment by nowakov** [comment]
So actually when I generate json for identifier separately and then generate json from whole hash it works, but I'm not sure if that's desired behavior.
```
id = { channel: 'PrintersChannel' }
sub_cmd = {
  command: 'subscribe',
  identifier: JSON.generate(id)
}

EM.run {
  url = 'ws://localhost:28080/cable'

  ws = WebSocket::Client::Simple.connect(url, headers: { printer_token: printer.token })

  ws.on :open do |event|
    ws.send(JSON.generate(sub_cmd))
  end
}
```

**Comment by maclover7** [comment]
I think this is the desired behavior, since people should be able to store more than just the channel name within the identifier.

**Comment by bestori** [comment]
:+1: @maclover7 . Why limit channel names...?

**Comment by jeremy** [comment]
The subscribe command is a bit awkward it's working as intended. The identifier does double duty to encode both the channel to subscribe and the other options to pass to the new subscription.

**Comment by felixletkemann** [comment]
I have got a very similar issue - it might even be the same. 
When I use "Simple Web Socket Client" (Chrome Extension) to communicate with ActionCable. 
When I use the following JSON, I get the error mentioned above. 
`{"command":"subscribe","identifier": {"channel":"CoapChannel"} }`

`Could not execute command from ({"command"=>"subscribe", "identifier"=>{"channel"=>"CoapChannel"}}) [TypeError - no implicit conversion of Hash into String]`

When I use this string instead, it works: 
`{"command":"subscribe","identifier":"{\"channel\":\"CoapChannel\"}"}`

Unfortunately, this looks like an escaped JSON inside a JSON string. I can not imagine, that this is desired behaviour. If the indentation level gets higher, it would result in some kind of escape sequence hell. 
Are you sure, this is correct @jeremy ?

**Comment by namiwang** [comment]
I'm trying to communicate with a rails websocket server outside the browser world, using plain websocket client libs, and this issue is really annoying.
