### ISSUE TITLE
Inconsistent restful route names when using the :only option

### ISSUE THREAD

**Issue by liquid** [rails/rails#24096]
When generating restful routes using the `:only` option in `routes.rb` the route name for the index action differs from the route name it is assigned when using all actions. Initially I thought this was due to some gem that does something 'fancy" to the rails routes but having generated a brand new Rails app it turns out the issue persists.

### Steps to reproduce

* Create a new Rails application
* Optionally generate a NewsController with a single index action
* Add a restful route to a new Rails application:

```ruby
resources :news, only: [:index]
```

* Invoke `rake routes`:

```
$ rake routes
    Prefix Verb URI Pattern     Controller#Action
news_index GET  /news(.:format) news#index
```

When using a simple `resources :news` without the `:only` option, the route name for the index action matches the old behaviour:

```
$ rake routes
    Prefix Verb   URI Pattern              Controller#Action
news_index GET    /news(.:format)          news#index
           POST   /news(.:format)          news#create
  new_news GET    /news/new(.:format)      news#new
 edit_news GET    /news/:id/edit(.:format) news#edit
      news GET    /news/:id(.:format)      news#show
           PATCH  /news/:id(.:format)      news#update
           PUT    /news/:id(.:format)      news#update
           DELETE /news/:id(.:format)      news#destroy
```

### Expected behaviour
I'd expect the path and URL helpers to be consistent regardless of action constraints. Ie still having `news_path` and `news_url` without the `_index` suffix. In case this an intended change to the rails routing system, then I guess the [Guides](http://guides.rubyonrails.org/routing.html) are outdated. (But please tell me this is not the case!)

### System configuration
**Rails version**: 4.2.5.1 and 4.2.5.2 (these are the only 2 I've looked at)

**Ruby version**: ruby 2.2.3p173 (2015-08-18 revision 51636) [x86_64-darwin13]

**Comment by liquid** [comment]
I was curious what happens when using `:except` instead of `:only` and I'm getting the same unusual behaviour with the following example:

```ruby
resources :news, except: [:create, :new, :edit, :show, :update, :update, :destroy]
```

```
$ rake routes
    Prefix Verb URI Pattern     Controller#Action
news_index GET  /news(.:format) news#index
```

**Comment by rafaelfranca** [comment]
I'm also seeing `news_index` in the routes without `:except` and `:only` too:

```
$ rake routes
    Prefix Verb   URI Pattern              Controller#Action
news_index GET    /news(.:format)          news#index
           POST   /news(.:format)          news#create
```

And it is specific to `news` since there is no way to singularized it. This is the expected behavior.
