### ISSUE TITLE
find_by_mysql works very slowly with large queries

### ISSUE THREAD

**Issue by stbarrientos** [rails/rails#24110]
### Steps to reproduce
I am running a large sql query (258 lines) that results in 2 rows with 128 columns. It does have a nested select. Unfortunately I am not able to paste the exact query here.

This is the way I am running the sql query
```
query = <<-SQL
  # Massive sql query here
SQL

result = MyModel.find_by_sql query
```

### Expected behavior
Running the exact same query using find_by_sql in Rails 4 finishes in less than a second, which is what I expected to happen in 5.0.0.beta3.

### Actual behavior
Instead, it takes on average around 6 seconds to finish the query.

After digging through the source and debugging a little bit, I realized that the problem occurs when ```find_by_mysql``` calls ```connection.select_all```, so it would seem as though ```connection.select_all``` is at fault.

Here is the code I used to come to that conclusion:

```
  # I'm creating an exact copy of the find_by_sql method in my model so that I can time
  # how long it takes for select_all to finish
  def self.find_by_sql(sql, binds = [])
    result_set = []
    t = Benchmark.measure do
      result_set = connection.select_all(sanitize_sql(sql), "#{name} Load", binds)
    end

    # t.real will equal 5.80009879602585
    puts "\n\n\n\n#{t.real}\n\n\n\n"
    column_types = result_set.column_types.dup
    columns_hash.each_key { |k| column_types.delete k }
    message_bus = ActiveSupport::Notifications.instrumenter

    payload = {
      record_count: result_set.length,
      class_name: name
    }

    message_bus.instrument('instantiation.active_record', payload) do
      result_set.map { |record| instantiate(record, column_types) }
    end
  end
```
I've been reading through the source for the ```connection.select_all``` but I cannot see any reason why this would be taking so long

### System configuration
**Rails version**: 5.0.0.beta3

**Ruby version**: 2.2.3p173

**Comment by shakycode** [comment]
Do you have a sample script/query that one of the community can use to replicate?  Maybe this is a regression?  I'm using find_by_sql i 5b3 but probably not as lengthy of a query and it performs ok for me.

**Comment by stbarrientos** [comment]
@shakycode Yes it is working on my smaller queries as well. It must be failing on some aspect of this larger query. Here is the structure of the query I'm working with:

```
SELECT foo, bar, etc x 128 # There's actually 128 of these columns
FROM (
  SELECT other_foo, other_bar # There's a lot of these columns as well, too many for a quick count
  FROM foos_table as foos
)
JOIN table1 USING (some_id)
LEFT JOIN table2 USING (other_id)
LEFT JOIN last_table ON last_table.id = table1.id
WHERE ...
GROUP BY...
ORDER BY...
```

I'm thinking there may be some aspect of this query that is causing the select_all to do extra work, maybe the nested select statements? Maybe the number of columns? What is really confusing is that it works fine in Rails 4, the exact same query.
Thanks for the quick response by the way.

**Comment by jeremy** [comment]
Possibly related: #23948 

Could you try on current master, @stbarrientos ?

**Comment by stbarrientos** [comment]
@jeremy That did it, its finishing in ```0.004496803041547537 ms``` now. Thanks for your help!

**Comment by jeremy** [comment]
👍
