### ISSUE TITLE
Has many through polymorphic source ignores source_type when deletes records

### ISSUE THREAD

**Issue by heaven** [rails/rails#24116]
I have the next STI:

``` ruby
class ListItem < ActiveRecord::Base; end
class Feeling < ListItem; end
```

The :through association:

``` ruby
class ListItemRelationship < ActiveRecord::Base
  belongs_to :list_item, :polymorphic => true
  belongs_to :listable, :polymorphic => true
end
```

And the next model where I need to add a `has_many` association:

``` ruby
class StressTest < ActiveRecord::Base
  has_many :list_item_relationships, :as => :listable
  has_many :feelings, :through => :list_item_relationships, :source => :list_item, :source_type => "Feeling"
end
```

The issue with insertions was fixed in #23209 
But deletion still doesn't work properly, both these examples do fail:

``` ruby
test.feelings = []
test.feeling_ids = []
```

Rails 4-2-stable
To reproduce: https://gist.github.com/heaven/55416bc2d2d51dfdb511

**Comment by vipulnsward** [comment]
I can reproduce this on master. Checking.

**Comment by vipulnsward** [comment]
This is going to take some to fix for me to take a look, there are issues at two places in query generation, unlike previous one.

**Comment by LeKristapino** [comment]
hey, I have the same issue. 

I tracked down the problem here:

For inserting records:
```ruby
def build_through_record(record)
...
  if options[:source_type]
    through_record.send("#{source_reflection.foreign_type}=", options[:source_type])
  end
   through_record
end
```

For deleting records:
```ruby
def construct_join_attributes(*records)
 ...
   if options[:source_type]
     join_attributes[source_reflection.foreign_type] =
       records.map { |record| record.class.base_class.name }
  end
...
end
```

This creates an inconsistency when `options[:source_type] != record.class.base_class.name`

If substituting the current delete method with the insert method is an option, I can submit a PR (I hope this removes `stale` tag from this issue

**Comment by heaven** [comment]
This is still reproducible in rails 5.1

**Comment by krtschmr** [comment]
is this still a thing?
