### ISSUE TITLE
Redirect code in routes.rb is not working fine

### ISSUE THREAD

**Issue by faisalejaz786** [rails/rails#24139]
### Steps to reproduce

I have routes something like in routes.rb

resources :biographies, to: redirect { |params, req| 
   path = 'some path related code'
  "http://mywebsite.com/client"
}

Instead of redirecting, it is passing redirection code in params

Parameters: {"to"=>redirect(301), "client_id"=>"peak"}

It was redirecting properly in Rails 4. 

### System configuration
**Rails version**:
  5.0.0.beta3
**Ruby version**:
ruby 2.3.0p0

**Comment by jyunderwood** [comment]
I don't think it's suppose to work like that. There is no `:to` parameter for `resources` in the API guide for v4 or v5.

http://api.rubyonrails.org/classes/ActionDispatch/Routing/Mapper/Resources.html#method-i-resources

There is for `match`, though.

http://edgeapi.rubyonrails.org/classes/ActionDispatch/Routing/Mapper/Base.html#method-i-match

**Comment by maclover7** [comment]
Can you create an executable test script using one of the templates [here](https://github.com/rails/rails/tree/master/guides/bug_report_templates), that would demonstrate the problem you are seeing?

**Comment by rafaelfranca** [comment]
> I don't think it's suppose to work like that. There is no :to parameter for resources in the API guide for v4 or v5.

This
