### ISSUE TITLE
Rails 5 controller test get :index not working but works on Rails 4

### ISSUE THREAD

**Issue by chewedon** [rails/rails#24141]
### Steps to reproduce

(Side note: Sorry if this issue has been identified before, I skimmed through the open and closed issue and didn't see anything resembling it so I am opening this one. Please close if this is a duplicate. As much as it pains me, I really don't want to contribute to increasing the Rails 5 countdown clock: http://rails5countdown.com/ but it looks like I will have to for the sake of making Rails 5 solid :P)

Created a gemset rails500

Freshly installed Rails 5.0.0beta3 using RVM.

I generated a new --api app called Neko using Rails 5.0.0beta3.

I have a cats_controller.rb

```ruby
class CatsController < ApplicationController
  def index
    data = [
      {
        name: "Milkshake",
        breed: "siamese",
        color: "white",
        eye_color: "blue"
      },
      {
        name: "Biscuit",
        breed: "tuxedo",
        color: "black and white",
        eye_color: "green"
      },
      {
        name: "Muffin",
        breed: "havana",
        color: "brown",
        eye_color: "yellow"
      }
    ]

    render json: data
  end
end
```

My router.rb file looks like so:

```ruby
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  # Serve websocket cable requests in-process
  # mount ActionCable.server => '/cable'
  resources :cats
end
```

And my `cats_controller_test.rb` looks like

```ruby
require 'test_helper'

class CatsControllerTest < ActionDispatch::IntegrationTest
  # test "the truth" do
  #   assert true
  # end

  test "should get index" do
    get :index
    assert_response :success
  end
end
```

### Expected behavior
Running `rails test` should theoretically run the tests and pass.

NOTE:

Using Rails 4.2.5.1 however, the same procedure actually works, the test pass as expected.

But Rails 5 beta seems to have some sort of problem, I don't know if I'm doing something wrong or what. I'm just a noob, I wouldn't be surprised if I set something wrong.

### Actual behavior
My Mac terminal gives the following error:

```bash
Error:
CatsControllerTest#test_should_get_index:
URI::InvalidURIError: bad URI(is not URI?): http://www.example.com:80index
    test/controllers/cats_controller_test.rb:9:in `block in <class:CatsControllerTest>'


bin/rails test test/controllers/cats_controller_test.rb:8
```

### System configuration
**Rails version**: Rails 5.0.0.beta3

**Ruby version**: ruby 2.3.0p0 (2015-12-25 revision 53290) [x86_64-darwin15]

**Comment by kaspth** [comment]
Your integration test is wrong. It should use a url helper (e.g. `cats_url`). Read more here: http://api.rubyonrails.org/classes/ActionDispatch/IntegrationTest.html

Thanks :heart:

**Comment by chewedon** [comment]
But...kaspth..the official Rails documentation gave the example:

```ruby
class ArticlesControllerTest < ActionController::TestCase
  test "should get index" do
    get :index
    assert_response :success
    assert_not_nil assigns(:articles)
  end
end
```

http://guides.rubyonrails.org/testing.html#functional-tests-for-your-controllers

Also, when I tried the same code on Rails 4.2.5.1 instead or Rails 5 there was no errors, the test passes. Is this a Rails 5 change ?

**Comment by chewedon** [comment]
In that case, shouldn't Rails 5 generate the integration test file inside the `/test/integration` folder instead of `/test/controllers` folder ?

I generated a new controller in Rails 5 called "dogs" and it created the dogs_controller_test.rb, an integration test as you have pointed out, inside the `/test/controllers` folder:

```bash
$ rails generate controller dogs
Running via Spring preloader in process 1351
      create  app/controllers/dogs_controller.rb
      invoke  test_unit
      create    test/controllers/dogs_controller_test.rb
```

Kinda confusing don't you think ? :smile:

**Comment by kaspth** [comment]
For a beta where the docs aren't always up to date? Maybe. But integration tests per controller (which explains the directory position) are the new default in Rails 5 and not at all odd 😁

Let's retire the discussion here. This underlying behavior is settled 👍

**Comment by Ardena** [comment]
I'm getting the same problem with one out of 49 other tests in a file that all use the same syntax.  And I don't believe this one test is an integration test.

Failures:

  1) ScoringRangesController POST create creates with assignments
     Failure/Error: post :create, params: @attrs

     URI::InvalidURIError:
       bad URI(is not URI?): http://www.example.com:80create
     # /home/docker/.gem/ruby/2.3.0/gems/rack-test-0.6.3/lib/rack/test.rb:193:in `env_for'
     # /home/docker/.gem/ruby/2.3.0/gems/rack-test-0.6.3/lib/rack/test.rb:123:in `request'
     # /home/docker/.gem/ruby/2.3.0/gems/actionpack-5.0.7/lib/action_dispatch/testing/integration.rb:334:in `process'
     # /home/docker/.gem/ruby/2.3.0/gems/actionpack-5.0.7/lib/action_dispatch/testing/integration.rb:361:in `process_with_kwargs'
     # /home/docker/.gem/ruby/2.3.0/gems/actionpack-5.0.7/lib/action_dispatch/testing/integration.rb:21:in `post'
     # /home/docker/.gem/ruby/2.3.0/gems/actionpack-5.0.7/lib/action_dispatch/testing/integration.rb:442:in `block (2 levels) in <module:Runner>'
     # ./spec/controllers/scoring_ranges_controller_spec.rb:136:in `block (3 levels) in <top (required)>'

Finished in 7.21 seconds (files took 5.95 seconds to load)
49 examples, 1 failure

Failed examples:

rspec ./spec/controllers/scoring_ranges_controller_spec.rb:129 # ScoringRangesController POST create creates with assignments
