### ISSUE TITLE
Upgrade to Rails 4.2.6 raises active_support/logger_silence.rb:23 exception

### ISSUE THREAD

**Issue by arturoherrero** [rails/rails#24142]
I just upgrade from Rails 4.2.5.2 to 4.2.6.

I'm using a config initializer to configure the [PayPal REST API Ruby SDK][1] gem.

So, I have this line of code in `config/initializers/paypal.rb` that it's now failing when I compile all the assets:
```ruby
PayPal::SDK.logger = Rails.logger
```

This is related with this commit https://github.com/rails/rails/commit/a2a652a512d6ee5488eb5e2d9dea310ec34e5b59 from @rabbitt.

My error message:

```ruby
$ RAILS_ENV=production rake assets:precompile

[3] pry(main)> PayPal::SDK.logger = Rails.logger
NoMethodError: undefined method `[]' for nil:NilClass
from /.../versions/2.3.0/lib/ruby/gems/2.3.0/gems/activesupport-4.2.6/lib/active_support/logger_silence.rb:23:in `level'
```

It looks that `local_levels` is not set at this point.

#### System configuration
**Rails version**: 4.2.6
**Ruby version**: 2.3.0

[1]: https://github.com/paypal/PayPal-Ruby-SDK

**Comment by rafaelfranca** [comment]
Can you please provide a sample application that reproduces the error?

**Comment by batizhevsky** [comment]
I faced with the same problem after update, but after a little research, I found that I had monkeypatched ActiveSupport logger class (a legacy from rails 3 app). After removing it all works fine for me.

**Comment by rovr** [comment]
Seeing the same issue, except that I don't have any custom logic related to logger. The app just fails to boot:

    rails s

    => Booting WEBrick
    => Rails 4.2.6 application starting in development on http://localhost:3000
    => Run `rails server -h` for more startup options
    => Ctrl-C to shutdown server
    Exiting

    /Users/test/.rvm/gems/ruby-2.3.0/gems/activesupport-4.2.6/lib/active_support/logger_silence.rb:23:in `level': undefined method `[]' for nil:NilClass (NoMethodError)
    from /Users/test/.rvm/gems/ruby-2.3.0/gems/railties-4.2.6/lib/rails/commands/server.rb:143:in `log_to_stdout'
    from /Users/test/.rvm/gems/ruby-2.3.0/gems/railties-4.2.6/lib/rails/commands/server.rb:78:in `start'
    from /Users/test/.rvm/gems/ruby-2.3.0/gems/railties-4.2.6/lib/rails/commands/commands_tasks.rb:80:in `block in server'
    from /Users/test/.rvm/gems/ruby-2.3.0/gems/railties-4.2.6/lib/rails/commands/commands_tasks.rb:75:in `tap'
    from /Users/test/.rvm/gems/ruby-2.3.0/gems/railties-4.2.6/lib/rails/commands/commands_tasks.rb:75:in `server'
    from /Users/test/.rvm/gems/ruby-2.3.0/gems/railties-4.2.6/lib/rails/commands/commands_tasks.rb:39:in `run_command!'
    from /Users/test/.rvm/gems/ruby-2.3.0/gems/railties-4.2.6/lib/rails/commands.rb:17:in `<top (required)>'
    from bin/rails:8:in `require'
    from bin/rails:8:in `<main>'

**Comment by rafaelfranca** [comment]
Can you please provide a sample application that reproduces the error?

**Comment by arturoherrero** [comment]
I think the error could be related with the [rails_12factor][1] gem, it was also referred in #23566. I'm still investigating.


[1]: https://github.com/heroku/rails_12factor

**Comment by rovr** [comment]
@arturoherrero You're right. Not seeing the error anymore after removing rails_12factor from the Gemfile.

**Comment by rovr** [comment]
@rafaelfranca You can reproduce the error on a blank rails app. If you add `gem 'rails_12factor'`, the app won't start.

**Comment by rabbitt** [comment]
@rovr that's a bug in `rails_12factor`, or more specifically `rails_stdout_logging` which has a PR (heroku/rails_stdout_logging#22) to address it.

**Comment by jasper-lyons** [comment]
Started having exactly the same issue today, my issue was with both:

`rails_12factor` and `ahoy_matey` see [here](https://github.com/ankane/ahoy/pull/144)

To recreate:

```
rails new testapp
cd testapp
```
add `gem "rails_12factor"` to Gemfile
```
bundle install
rails s
```

**Comment by arturoherrero** [comment]
I just found the same pull request @rabbitt. @rafaelfranca probably we can close this issue. Thanks!
