### ISSUE TITLE
Empty body for JSON requests with status codes 4xx and 5xx

### ISSUE THREAD

**Issue by haslinger** [rails/rails#24147]
### Steps to reproduce

Creating a minimalist app with a routes.rb :
```
Rails.application.routes.draw do
  get 'error' => 'application#test', defaults: { format: :json }
  get 'working' => 'application#test2', defaults: { format: :json }
end
```

and an application_controller.rb :
```
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  skip_before_action :verify_authenticity_token

  def test
    render json: {error: "i wont show up"} , status: 422
  end

  def test2
    render json: {fine: "i do show ap"} , status: 200
  end
end
```

### Expected behavior
Get requests to /error and /working should result in responses with an existing body.

### Actual behavior
While /working works fine, /error only responds with the correct error code, but with an empty body in development as well as in production.
Setting   `config.debug_exception_response_format = :api` doesn't change this behavior.

### System configuration
**Rails version**: 5.0.0.beta3

**Ruby version**: 2.3.0p0

**Comment by maclover7** [comment]
Can you create an executable test script using one of the templates [here](https://github.com/rails/rails/tree/master/guides/bug_report_templates), that would demonstrate the problem you are seeing?

**Comment by haslinger** [comment]
@maclover7 Thank you for response, you helped me debugging and solved my issue.
I created a [gist](https://gist.github.com/haslinger/b08b473e63574ba33196), that proved me wrong. The response is correct.

What misled me was, that I was using wget for testing the response, that doesn't load the body for the status 422 case, while curl does it correctly.

Thank you for your time!
