### ISSUE TITLE
application_mailer.rb not being created when using generator

### ISSUE THREAD

**Issue by marklocklear** [rails/rails#24160]
### Steps to reproduce
Run the command `rails generate mailer StudentsMailer`

The output is:

```  
      create  app/mailers/students_mailer.rb
      invoke  erb
      create    app/views/students_mailer
      invoke  test_unit
      create    test/mailers/students_mailer_test.rb
      create    test/mailers/previews/students_mailer_preview.rb
```

The contents of students_mailer.rb are:

```
class AwardMailer < ApplicationMailer
end
```

### Expected behavior
I would expect for the file app/mailers/application_mailer.rb to be created

### Actual behavior
File app/mailers/application_mailer.rb is not created. When you try to send mail you get the error `uninitialized constant ApplicationMailer`. This is because there is no  app/mailers/application_mailer.rb which would look like:

```
class ApplicationMailer < ActionMailer::Base
  default from: "from@example.com"
  layout 'mailer'
end
```

### System configuration
**Rails version**:
Rails 5.0.0.beta3
**Ruby version**:
2.2.2p95

**Comment by rafaelfranca** [comment]
Was not that file created when you created the application?

**Comment by marklocklear** [comment]
You are correct! Thank you. I was running the generator on an older code base. Wondering if there should be a check to see if it is there, and create if not?

**Comment by rafaelfranca** [comment]
Yeah, we should do that check. I'll keep this open to fix it.

**Comment by Sen-Zhang** [comment]
revert this change? https://github.com/rails/rails/commit/293d35e256d282e3ea9d4d6277611e1e4d50dc96

**Comment by rafaelfranca** [comment]
Fixed. Thank you for reporting.

**Comment by marklocklear** [comment]
Thanks all!
