### ISSUE TITLE
Actioncable emit and broadcast with in single channel.

### ISSUE THREAD

**Issue by devilankur18** [rails/rails#24173]
### Steps to reproduce

Current version of actioncable supports the broadcast functionality well, but many times, need to emit data in channel, to single subscriber only.

Lets take a simple usecase of a chat:

A chat room with 10 users, and 200 messages already created by these users. 

- Upon new message, broadcast it to all subscribers.
- Now first time when page load, it make sense to lazy load messages as user keep scrolling down.

### Expected behaviour

It make more sense to have a function, which just emit back to single subscriber only or  emulate request / response behaviour over ChatChannel.

I have aggressively used these feature in socket.io, it a life saver.

### Actual behavior
Using Actioncable, create a ChatChannel with a chat_id. 

- Upon new message, broadcast new chat messages to ChatChannel with chat_id. 
- While lazyload next 20 messages via the ChatChannel, there is no way to send it to one user, without broadcasting it to all. Currently for implementing this, need to create a dedicated channel for user, for loading such data. 

### System configuration
5.0.0.beta1

**Ruby version**:
ruby-2.2.2

**Comment by maclover7** [comment]
Please use the mailing list for feature requests, where a wider community will be able to help you. We reserve the issues tracker for issues only.
