### ISSUE TITLE
Route's `as: false` defines a route named `false`

### ISSUE THREAD

**Issue by fnando** [rails/rails#24172]
### Steps to reproduce

Create a route like the following:

```ruby
get "/foo" => "foo#bar", as: false
```

### Expected behavior

The route must be generated without a name. That's how it works up to Rails 4.2. Using `as: nil` has the expected behavior in Rails 5.0.0.beta3.

### Actual behavior

The `false` route is defined.

```
$ rails routes
Prefix Verb URI Pattern    Controller#Action
 false GET  /foo(.:format) foo#bar
```

### System configuration

- **Rails version**: 5.0.0.beta3
- **Ruby version**: 2.3.0

**Comment by maclover7** [comment]
Investigating.

**Comment by sgrif** [comment]
Passing anything other than a string to that option is undocumented, and considered undefined behavior.
