### ISSUE TITLE
Relation#empty? (which is used by #any?) does a count which is needlessly more expensive than #exists?

### ISSUE THREAD

**Issue by bughit** [rails/rails#24181]
```ruby
def empty?
  return @records.empty? if loaded?

  if limit_value == 0
    true
  else
    c = count(:all)
    c.respond_to?(:zero?) ? c.zero? : c.empty?
  end
end
```

it should only care about a single matched row, anything beyond that is a potentially expensive waste

**Comment by sgrif** [comment]
This is a known issue, but not a bug.

**Comment by bughit** [comment]
Ok so it's an "issue", so why shouldn't this "issue" remain open in the rails issues database until it's no longer an issue?

**Comment by bughit** [comment]
Since issues need to be tracked somehow is there an alternative issue tracker?  Where is it?  I'd like to subscribe to this issue.
