### ISSUE TITLE
self referential has_many through joins doesn't use table alias on where conditions

### ISSUE THREAD

**Issue by sanderhahn** [rails/rails#24189]
### Steps to reproduce

The default_scope conditions don't use the table alias name when joined:
https://gist.github.com/sanderhahn/2e98c2b6d3441dc40909

Working reproduction script from @meinac that triggers the same problem on self referential STI:
https://gist.github.com/meinac/fef74b76a04989f9927d
### Expected behavior

The default_scope where should use the table alias in the where condition.
### Actual behavior

The default_scope where uses the table_name instead of the join alias which gives invalid SQL if the same table is joined.
### System configuration

**Rails version**:
Rails 4.2.6 and Rails Edge

**Ruby version**:
ruby 2.3.0p0 (2015-12-25 revision 53290) [x86_64-darwin14]

**Comment by meinac** [comment]
For someone who is interested with this issue, [here](https://gist.github.com/meinac/fef74b76a04989f9927d) is a reproduction script to work with(The original one is not ready to go).
@sanderhahn can you verify that this is a similar scenario with yours.

**Comment by sanderhahn** [comment]
@meinac Thanks! Your reproduction script seems to have the same problem on the type condition. So the problem may not default scope specific.

**Comment by Crunch09** [comment]
It seems at least on rails master this issue is fixed. I could only reproduce it with 4.2.6

**Comment by sanderhahn** [comment]
The repro script seems to work also using 5.1. The original script using default scope seems to misbehave, but i will close because it is not a very normal way of using ActiveRecord anyways :) Thanks all!
