### ISSUE TITLE
Test the validity of each attribute independently?

### ISSUE THREAD

**Issue by KevinBongart** [rails/rails#24191]
I made [a small gem to run specific validator on specific attributes of an object independently](https://github.com/KevinBongart/valid_attribute), any interest in getting this into Rails? Happy to turn it into a PR!

Here's the full implementation, which can be refactored and modernized for Rails 5: https://github.com/KevinBongart/valid_attribute/blob/master/lib/valid_attribute.rb

### Steps to reproduce

Let's say you have:

```ruby
class Product < ActiveRecord::Base
  belongs_to :company

  validates :company, presence: true
  validates :name, format: { with: /\A[a-zA-Z]+\z/ }
  validates :name, uniqueness: { scope: :company }
  validates :legacy_code, format: { with: /\A[a-zA-Z]+\z/ }
end
```

### Expected behavior

```ruby
company = Company.new
product = Product.new(company: company, name: "hey")

# Test only one attribute:
product.valid_attribute?(:company)      # => true
product.valid_attribute?(:name)         # => true
product.valid_attribute?(:legacy_code)  # => false

# Test several attributes at once, like a boss:
product.valid_attribute?(:company, :name)               # => true
product.valid_attribute?(:company, :name, :legacy_code) # => false

# Wow, you can even filter down to a specific validator:
product.valid_attribute?(name: :format)                     # => true
product.valid_attribute?(name: [:format, :uniqueness])      # => true
product.valid_attribute?(name: :format, company: :presence) # => true
```

### Actual behavior

```ruby
product.valid? # runs all validators on all attributes, including DB queries, builds full error hash
# => false
```

### System configuration
**Rails version**: 4.2.5.2

**Ruby version**: 2.3

(apologies if this was already proposed or discussed, I didn't find anything about it in the repo)

**Comment by rafaelfranca** [comment]
Thank you for the suggestion. Validations are not tied to only one attribute neither to attributes so I don't think it is a good idea to check the validity of only one attribute.

**Comment by KevinBongart** [comment]
@rafaelfranca Fair enough, though I'd love to know more about what you mean by "Validations are not tied to only one attribute", since I wrote this gem specifically because I needed to run one validator on one attribute.

My guess is it depends on the context, and for most people this `valid_attribute?` method has no value, so I'm perfectly fine keeping it as a gem.

**Comment by rafaelfranca** [comment]
Validations can happen in any aspect of the model not just attribute. One
validation may need a combination of two attributes to pass, it may depend
in a existent pre condition in the database, or in a configuration. A
validation can also only run if a validation in other attribute already
ran. Because of these cases I believe validating only one attribute can be
misleading.

**Comment by KevinBongart** [comment]
Ah, I see. Makes sense. Thanks for the explanation!
