### ISSUE TITLE
Rolling back add_index should use the same concurrently algorithm

### ISSUE THREAD

**Issue by jturkel** [rails/rails#24190]
### Steps to reproduce
- Create and run the following migrations to create a `products` table with an index:

``` ruby
class CreateProducts < ActiveRecord::Migration[5.0]
  def change
    create_table :products do |t|
      t.string :name
    end
  end
end
```

``` ruby
class AddProductNameIndex < ActiveRecord::Migration[5.0]
  disable_ddl_transaction!

  def change
    add_index(:products, :name, algorithm: :concurrently)
  end
end
```
- Run `rake db:migrate` to run the migrations
- Run `rake db:rollback` to undo the index migration
### Expected behavior

Since the migration created the index concurrently, I would expect undoing it to drop the index concurrently i.e. run the following SQL:

``` sql
DROP INDEX CONCURRENTLY "index_products_on_name"
```
### Actual behavior

Currently undoing the migration does not drop the index concurrently i.e. it runs the following SQL:

``` sql
DROP INDEX "index_products_on_name"
```
### System configuration

**Rails version**: 5.0.0.beta3

**Ruby version**: ruby-2.2.2

**Comment by jturkel** [comment]
I've confirmed this is still an issue on `master`.

**Comment by tibbon** [comment]
Still an open issue? I might tackle this one this week or so.

**Comment by jturkel** [comment]
It is still an issue. There does seem to be an open PR for it though: https://github.com/rails/rails/pull/24199
