### ISSUE TITLE
ActiveJob. What do you think of adding sidekiq options support?

### ISSUE THREAD

**Issue by vsorlov** [rails/rails#24209]
Hi, sidekiq have pretty crucial feature - sidekiq_options, what do you think of adding options class setter to ActiveJob, that all other adapters can use?

**Comment by rafaelfranca** [comment]
Thank you so much for the issue but we don't take feature request on the issue tracker. We recommend you to try to implement the feature and send us a pull request or if you are in doubt if the feature will be accepts ask in Rails Core mailing list for feedback.
