### ISSUE TITLE
alias_attribute in a PORO crashes unintuitively when the first argument ends in a question mark.

### ISSUE THREAD

**Issue by georgemillo** [rails/rails#24208]
As stated in the title: when I use `alias_attribute` in a PORO for the common use case of creating a "ends in question mark" alias for an attribute that should be boolean (just like AR automatically does for boolean columns), I get a syntax error:

```
class Widget
  attr_accessor :active
  alias_attribute :active?, :active
end
# => syntax error, unexpected '?', expecting ';' or '\n'
#    def active??; self.active?; end 
```

After some confusion, I realise that this is actually probably the intended behaviour, because *attribute* names shouldn't end in `?`; I should use `alias_method` rather than `alias_attribute`.

But the error message is extremely unintuitive and confusing, as it raises a `SyntaxError` when (from my perspective looking only at the `Widget` class), there's no syntax error in the Ruby I've written.

When I try to create an invalid attribute name with `attr_accesor`, Ruby is much clearer:

```
class Widget
  attr_accessor :active?
end
# => NameError: invalid attribute name `active?'
```

Would it be possible to patch `alias_attribute` so it behaves identical to plain old Ruby `attr_*` methods when passed an invalid attribute name? I'm happy to make this change myself, I just wanted to make sure it's something you guys would accept before I put the time in.

(PS if I'm not mistaken, valid attribute names in Ruby are those that match the regex `/\A[_a-zA-Z][_a-zA-Z0-9]*\z/`, amirite?)

**Comment by eliasjpr** [comment]
Hey @georgemillo I have created a gist for your test case https://gist.github.com/eliasjpr/905a9ece5534cac57b90.

**Comment by kaspth** [comment]
Thanks, we don't accept feature requests on the issue tracker. Generally we'd recommend writing to the Rails-core mailing list, but since there's already a PR for this. Let's move the discussion there. :heart:
