### ISSUE TITLE
Set value jQuery issue

### ISSUE THREAD

**Issue by chashmeetsingh** [rails/rails#24211]
### Steps to reproduce

- Create a form
- make an input field
- submit button on click call function
- set value in the form field using jQuery 

### Expected behaviour
Value persists until page refresh

### Actual behaviour
When the button is clicked it does set the value in the form input field but also sends a get request which causes the page to refresh removing the value

### System configuration
**Rails version**:
2.2.3
**Ruby version**:
4.2.6

**Comment by rafaelfranca** [comment]
This is the expected behavior, it is how browser works. Even if you think it is an issue it is not a Rails issue because we don't have any javascript code.
