### ISSUE TITLE
to_json include option doesn't call as_json/to_json recursively

### ISSUE THREAD

**Issue by leonardoprg** [rails/rails#24216]
Hello guys, 

When I tried to call `to_json` passing include options (and it's a association),
`to_json` is only called for the root model.

how you can guys can see [here](https://github.com/rails/rails/blob/master/activemodel/lib/active_model/serialization.rb#L124)

for the associations it just call the `raw method name`.

On my understand, once I defined on the model, how the model should render `as a json`, I expect that all call's for render the model as json, respect it.

What do you guys think? is it correct?

please follow the example to reproduce and get a better understand.

### Steps to reproduce

https://gist.github.com/leonardoprg/7dfd6bc1f02c2d91695b

### Expected behavior
Once I defined how the model should be render as json, I think the `render json`, should respect that.

### Actual behavior
to_json include option doesn't call as_json/to_json recursively

### System configuration
**Rails version**:
4.2-stable

**Ruby version**:
2.2

**Comment by alvarocantador** [comment]
+1

**Comment by maclover7** [comment]
To me, this seems like expected behavior -- you are merging in extra parameters on `Comment`s.

**Comment by leonardoprg** [comment]
@maclover7  

Yes, I am,

so, for that reason when I call 


`post.to_json(include: :comments)`

it should return a json with comments **and "test" attribute** 
 
but, if you execute the test, it return just

`{"id"=>1, "comments"=>[{"id"=>1, "post_id"=>1}]}`

**Comment by CarlosSoares** [comment]
+1

**Comment by EdDeAlmeidaJr** [comment]
+1

**Comment by theAJFM** [comment]
I think this has been discussed before.

See [https://github.com/rails/rails/issues/576](url) or/and [https://github.com/rails/rails/pull/2200](url)

**Comment by VobyD** [comment]
+1

**Comment by rafaelfranca** [comment]
Yes this is a not an issue. See https://github.com/rails/rails/pull/2200#discussion_r2304611
