### ISSUE TITLE
Versioning/Vulnerability issue with mail gem

### ISSUE THREAD

**Issue by mearleycf** [rails/rails#24217]
### Steps to reproduce

- Set your Gemfile to call for mail ~>2.6.0 (Or gemfile.lock, whatever you prefer)
- Run bundle install

### Expected behavior
I want to be able to use the non-vulnerable version of the mail gem, which is a dependent of action mailer.

### Actual behavior
```
Bundler could not find compatible versions for gem "mail":
  In Gemfile:
    mail (~> 2.6.0)

    rails (~> 3.2.22.1) was resolved to 3.2.22.1, which depends on
      actionmailer (= 3.2.22.1) was resolved to 3.2.22.1, which depends on
        mail (~> 2.5.4)

    mailman (~> 0.5.1) was resolved to 0.5.1, which depends on
      mail (>= 2.0.3)
```
```
Name: mail
Version: 2.5.4
Advisory: 131677
Criticality: Unknown
URL: http://www.mbsd.jp/Whitepaper/smtpi.pdf
Title: Mail Gem for Ruby vulnerable to SMTP Injection via recipient email addresses
Solution: upgrade to >= 2.6.0

Vulnerabilities found!
```

### System configuration
**Rails version**: 3.2.22.1

**Ruby version**: ruby 2.0.0p645 (2015-04-13) [x86_64-linux]

**Comment by rafaelfranca** [comment]
Rails 3 is not supported anymore.
