### ISSUE TITLE
ActiveModel::Dirty #{attribute_name}_changed? returning nil instead of false

### ISSUE THREAD

**Issue by batter** [rails/rails#24220]
### Steps to reproduce
[Here's a gist using the ActiveRecord bug template demonstrating the issue](https://gist.github.com/batter/6947876631e7d72144c9)

### Expected behavior
I would expect that calling `ModelKlass.new.attribute_name_changed?` to always return `true` or `false`. Specifically in this case it should return `false` if the attribute has yet to changed, since it is a method with a question mark appended to the end of it.

### Actual behavior
It returns `nil` in these cases. This is a departure from the behavior in the rest of the Rails 4.2 releases

### System configuration
**Rails version**:
4.2.6

**Ruby version**:
I saw it happen on 2.2.1 and 2.3.0

**Comment by maclover7** [comment]
This was caused by c7802dccba69517083000261477f7e1d410e1cca -- cc @sgrif

**Comment by jeremy** [comment]
We generally treat treat `?` methods as truthy, not literally boolean. But I think it's reasonable to be flexible, particularly when it's an otherwise-boolean value changing on a stable release line.

**Comment by sgrif** [comment]
`attribute_changed?` doesn't even show up in the documentation, but `changed?` is documented as returning a boolean, so I'm willing to call this one a bug as it implies that `attribute_changed?` would return a boolean as well. http://api.rubyonrails.org/classes/ActiveModel/Dirty.html#method-i-changed-3F

**Comment by Sen-Zhang** [comment]
Integer type attributes have the same problem too.

**Comment by batter** [comment]
@Sen-Zhang as per my understanding, the attribute type does not matter for this

**Comment by Sen-Zhang** [comment]
@batter I agree

**Comment by maclover7** [comment]
Closed via #24515.
