### ISSUE TITLE
Scope with enum doesn't accept symbols

### ISSUE THREAD

**Issue by ReganRyanNZ** [rails/rails#24232]
### Steps to reproduce
Migration:
```
class AddApprovalStatusToUser < ActiveRecord::Migration
  def change
    add_column :users, :approval_status, :integer, limit: 1, default: 0
  end
end
```

Model:
`enum approval_status: [:pending, :approved, :declined]
`
Console:
```
User.first.approval_status = :declined # works
User.first.approval_status = 'declined' # works

User.where(approval_status: 'pending') # works
User.where(approval_status: :pending) # breaks

```
SQL statement on broken code:
`User Load (0.4ms)  SELECT `users`.* FROM `users` WHERE `users`.`approval_status` = NULL
`
Any symbol turns into NULL in the SQL code.

(Guidelines for creating a bug report are [available
here](http://guides.rubyonrails.org/contributing_to_ruby_on_rails.html#creating-a-bug-report))

### Expected behavior
`User Load (0.4ms)  SELECT `users`.* FROM `users` WHERE `users`.`approval_status` = NULL
`
### Actual behavior
`User Load (0.4ms)  SELECT `users`.* FROM `users` WHERE `users`.`approval_status` = 0
`
### System configuration
**Rails version**: 4.2.3

**Ruby version**: 2.2.2

**Comment by willnet** [comment]
I created a [executable test case](https://gist.github.com/willnet/849307d14cc39ef3b11b) for this issue :smiley:

**Comment by willnet** [comment]
It also doesn't work with 4.2.6 and 4-2-stable, but works with 5.0.0.beta3 and master

**Comment by rafaelfranca** [comment]
Yes. It is only fixed in rails 5.

**Comment by voltechs** [comment]
For posterity, this is the commit for the feature :) https://github.com/rails/rails/commit/c51f9b61ce1e167f5f58f07441adcfa117694301
