### ISSUE TITLE
PostgreSQL json PG::InvalidTextRepresentation

### ISSUE THREAD

**Issue by dungdm93** [rails/rails#24234]
### Steps to reproduce

Migration:
```shell
rails generate model Foobar attr:jsonb
```

Console:
```ruby
f = Foobar.new
f.attr = "PostgreSQL JSON"          # try to assign attr with value "PostgreSQL JSON" but f.attr = nil
f.attr = "PostgreSQL JSON".to_json  # Now, f.attr = "PostgreSQL JSON". OK!
f.save                              # ActiveRecord::StatementInvalid: PG::InvalidTextRepresentation: ERROR:  invalid input syntax for type json
```
**Note**: errors is raised with both `json` n' `jsonb` data type.
### Expected behavior

New `foobars` record with column `attr` value = `"PostgreSQL JSON"`

### Actual behavior
```ruby
ActiveRecord::StatementInvalid: PG::InvalidTextRepresentation: ERROR:  invalid input syntax for type json
```
### System configuration
**Rails version**: 4.2.4
**Ruby version**: MRI 2.2.3p173

**Comment by dungdm93** [comment]
I have tried assign ```Foobar.attr``` with other data types:
Here is summary:

- `String`:
    - Raw string:

        ```ruby
        f.attr = "Some value"  # f.attr = nil
        ```

    - JSON string

        ```ruby
        f.attr = "Some value".to_json  # f.save raise PG::InvalidTextRepresentation
        f.attr = 13.to_json            # works
        f.attr = 123.456.to_json       # works
        f.attr = true.to_json          # f.save raise PG::InvalidTextRepresentation
        f.attr = nil.to_json           # works
        ```

- `Number`, `Boolean`, `Nil`, `Array`, `Hash`:

    ```ruby
f.attr = 13            # works
f.attr = 123.456       # works
f.attr = true          # f.save raise PG::InvalidTextRepresentation
f.attr = nil           # works
f.attr = array         # works
f.attr = hash          # works
    ```

- Serializable Object

    ```ruby
class Address
  attr_accessor :street, :city, :country
end

a = Address.new "street":"282 Kevin Brook","city":"Imogeneborough","country":"French Guiana"
f.attr = a
f.save          #=> TypeError: can't cast Address to jsonb
    ````

**Comment by sevaorlov** [comment]
@dungdm93, what do you expect from `"PostgreSQL JSON".to_json` ? it is just `"PostgreSQL JSON"` and on save the query is the following `INSERT INTO "foobars" ("attr") VALUES ($1) RETURNING "id"  [["attr", "PostgreSQL JSON"]]`, so it is not a valid json.
the same for `false.to_json`, it is just `"false"`

**Comment by meinac** [comment]
I believe that, this is not an issue on Rails.
Please have a look at the documentation about ruby's json library [here](http://ruby-doc.org/stdlib-2.0.0/libdoc/json/rdoc/JSON.html#module-JSON-label-Generating+JSON). As you can see on the section linked above, the documentation says;
> JSON.generate only allows objects or arrays to be converted to JSON syntax. to_json, however, accepts many Ruby classes even though it acts only as a method for serialization: 
```
require 'json'
1.to_json => "1"
```

The documentation about `to_json` method you are using in this case can be found [here](http://ruby-doc.org/stdlib-2.0.0/libdoc/json/rdoc/JSON/Ext/Generator/GeneratorMethods/String.html#method-i-to_json).
So as documentation said, the purpose of the to_json method in this case is just serialization! It does not guarantee the returning value to be valid JSON.

**Comment by sgrif** [comment]
@meinac This is an issue in Rails.

**Comment by meinac** [comment]
@sgrif what is the issue with Rails here? Do you mean, Rails should cover bad inputs?

**Comment by sgrif** [comment]
The inputs aren't bad.

**Comment by sgrif** [comment]
And yes, if they were than we should be handling it. We should never be
getting that sort of error from PG

**Comment by meinac** [comment]
So you say `"PostgreSQL JSON"` is valid JSON right?

And yes, robust programming is a good practice but how can you cover this case? Are you planning to ignore bad values silently or are you going to raise an ActiveRecord exception instead of PostgreSQL one or are you going to add an error into the record which says attribute is invalid?

**Comment by sgrif** [comment]
No, you don't assign json to a field, you assign a Ruby type that can be
serialized to json. And yes, a string is a valid json primitive. If it were
invalid we would treat it the same as invalid input in other types, which
is casting to nil.

**Comment by meinac** [comment]
Yes you were right, I've checked the [**recent** rfc](http://rfc7159.net/rfc7159) and this is completely valid JSON. Thank you for the quick tutorial @sgrif :smile:

**Comment by dungdm93** [comment]
@sevaorlov string is a valid json primitive type, but I can't assign:
`f.attr = "PostgreSQL JSON"`, so I must use `f.attr = "PostgreSQL JSON".to_json`
Even that, I can't save it to database.

**Comment by dungdm93** [comment]
I think, the problem is that when you assign a string to JSON attribute, Rails try to convert that string to json, but forget that string is JSON primitive type.
To completely resolve this problem, I suggest that if input is one of JSON data type (`string`, `number`, `boolean`, `nil`, `Hash` and `Array`), keep its original, otherwise, convert it to JSON. So now, use have to control input is JSON string or raw value. For example:
```ruby
f.attr = JSON.parse "{\"string\": \"Hello World\"}"
```
------
Problem of `Boolean` type is different, `true` and `false` value mapping to `t` and `f` in insert query.

**Comment by sevaorlov** [comment]
@meinac, @sgrif, so then there are two problems?
1) PostgreSQL doesn't treat it as a valid JSON 
2) Rails doesn't treat string as a valid json because  `f.attr = "PostgreSQL JSON"` set f.attr to nil

**Comment by rhymes** [comment]
@sgrif is there a chance it might be backported to Rails 4.2 :-) ? 

In the meantime I patched it in an initializer like this:

```ruby
module ActiveRecord
  module ConnectionAdapters
    module PostgreSQL
      module OID
        class Json < Type::Value
          def type_cast_for_database(value)
            ActiveSupport::JSON.encode(value)
          end
        end
      end
    end
  end
end
```

adapter from https://github.com/rails/rails/blob/v4.2.7/activerecord/lib/active_record/connection_adapters/postgresql/oid/json.rb

I can submit a PR if you think it'll get considered.

**Comment by rhymes** [comment]
Unfortunately the above hack breaks a bunch of other code in my Rails 4.2 app misteriously, like a lot of JSON based Arel queries.

**Comment by sgrif** [comment]
No, it won't be back ported to 4.2
