### ISSUE TITLE
TypeError (can't dump Socket): with mongoid 5 on Rails 4.2.3

### ISSUE THREAD

**Issue by poc7667** [rails/rails#24237]
TypeError (can't dump Socket): with mongoid 5 on Rails 4.2.3

I tried to cache the controller method,

However, I ran into confuse exception.

# app/controllers/api/v1/comments_controller.rb

      def load_comments
        @og_url = params["og_url"]
        @preloaded_comments = Rails.cache.fetch(@og_url, expires_in: 2.seconds) do
            Comment.find_with_celebrity_profile(@og_url)
        end
      end

# Comment.rb

      def self.find_with_celebrity_profile(og_url)
        matchs_og_url = {normalized_link: /.*#{og_url}.*/}
        collection.aggregate(
          [
            ....
          ]
         )
      end

# Exception

    TypeError (can't dump Socket):
      app/controllers/api/v1/comments_controller.rb:76:in `load_comments'

      Rendered /..../gems/actionpack-4.2.0/lib/action_dispatch/middleware/templates/rescues/_source.erb (5.1ms)
      Rendered /..../gems/actionpack-4.2.0/lib/action_dispatch/middleware/templates/rescues/_trace.html.erb (2.4ms)
      Rendered /..../gems/actionpack-4.2.0/lib/action_dispatch/middleware/templates/rescues/_request_and_response.html.erb (0.8ms)
      Rendered /..../gems/actionpack-4.2.0/lib/action_dispatch/middleware/templates/rescues/diagnostics.html.erb within rescues/layout (58.8ms)
      Rendered /..../gems/web-console-2.2.1/lib/web_console/templates/_markup.html.erb (0.3ms)
      Rendered /..../gems/web-console-2.2.1/lib/web_console/templates/_inner_console_markup.html.erb within layouts/inlined_string (0.3ms)
      Rendered /..../gems/web-console-2.2.1/lib/web_console/templates/_prompt_box_markup.html.erb within layouts/inlined_string (0.2ms)

**Comment by robrace** [comment]
What is the type of the response from `collection.aggregate`? My guess would be that it is not returning an array, even if it has previously, thus Rails.cache.fetch can't dump and store it.

**Comment by poc7667** [comment]
In mongoid 5,  it should be ` #<Mongo::Collection::View::Aggregation:0x007fbb95e5d938`

**Comment by robrace** [comment]
You can see in the Ruby documentation that Marshal.dump can't serialize your object:

[Ruby Doc Marshal.dump](http://ruby-doc.org/core-2.3.0/Marshal.html#method-c-dump)

I would imagine, just adding a `.to_a` to your `Mongo::Collection::View::Aggregation` should allow it to be serializable and thus storable in `Rails.cache.fetch` block.

**Comment by maclover7** [comment]
I think this is a third party issue, specifically a problem related to your Mongoid usage.
