### ISSUE TITLE
Incorrect rounding in decimal columns

### ISSUE THREAD

**Issue by threedaymonk** [rails/rails#24235]
When assigning certain floating-point values to a PostgreSQL decimal column, the least significant digit is off by one. This happens on a new record, before any database writes occur.

### Steps to reproduce

The following code will demonstrate this:

### `Gemfile`

```ruby
source 'https://rubygems.org'
ruby '2.3.0'
gem 'activerecord', '4.2.6'
gem 'pg'
```

### `test.rb`

```ruby
require 'bundler/setup'
require 'active_record'

class Thing < ActiveRecord::Base
end

ActiveRecord::Base.establish_connection

ActiveRecord::Base.connection.execute <<-SQL
  CREATE TABLE IF NOT EXISTS things (
    decimal_5_3 DECIMAL(5, 3)
  )
SQL

thing = Thing.new(decimal_5_3: 1.250473853637869)
expected = BigDecimal.new('1.250')
actual = thing.decimal_5_3
delta = actual - expected
epsilon = BigDecimal.new('0.0001')

if delta.abs > epsilon
  puts 'Expected    %s' % expected.inspect
  puts 'But got     %s' % actual.inspect
  puts 'Difference  %s' % delta.inspect
  exit 1
else
  puts 'OK'
end
```

Running with an appropriate `DATABASE_URL` for an existing database, e.g.

```sh
$ DATABASE_URL=postgresql:///ar_decimal_bug bundle exec ruby test.rb
```

yields this output:

```
Expected    #<BigDecimal:7f4d61c86ee0,'0.125E1',18(18)>
But got     #<BigDecimal:7f4d61c870c0,'0.1251E1',18(27)>
Difference  #<BigDecimal:7f4d61c86e68,'0.1E-2',9(27)>
```

### Expected behavior

The floating-point value `1.250473853637869`, when assigned to a field of type `DECIMAL(5, 3)` (i.e. `NN.NNN`) should be rounded to `BigDecimal('1.250')`.

### Actual behavior

ActiveRecord sets the field to `BigDecimal('1.251')`.

### System configuration

**Rails version**: ActiveRecord 4.2.5.1 and 4.2.6

**Ruby version**: 2.3.0

**PostgreSQL version**: 9.4.6 and 9.5.1

### Notes

It appears that the value is being rounded twice within ActiveRecord. This does not happen when a value which uses all the integer digits is used (e.g. `11.250473853637869`), so I believe that it is ultimately related to a mismatch between decimal fields (fixed digit positions) and `BigDecimal` (fixed number of digits) meaning that the field is initially assigned to too-wide a BigDecimal.

Thus:

    1.25047... → BigDecimal('1.2505') → BigDecimal('1.251')

but:

    11.25047... → BigDecimal('11.250') → BigDecimal('11.250')

**Comment by qwerty2323** [comment]
in line:7 you forgot (spec = ENV["DATABASE_URL"])
```ruby
ActiveRecord::Base.establish_connection(adapter: 'sqlite3', database: ':memory:')
```
Also, what BigDecimal round mode are you using?
Maybe you would like to check the link below:

http://ruby-doc.org/stdlib-2.3.0/libdoc/bigdecimal/rdoc/BigDecimal.html#method-c-mode

**Comment by qwerty2323** [comment]
I reproduced your issue.

I suggest you add to your code lines below:
```ruby

BigDecimal.mode(BigDecimal::ROUND_MODE, BigDecimal::ROUND_HALF_EVEN)
BigDecimal.limit(20)

ActiveRecord::Base.establish_connection adapter: 'postgresql',
                                        database: 'name_of_the_database'
```
Or choose another BigDecimal round mode
