### ISSUE TITLE
Method missing when including ActionController::Cookies in Rails 5.0 API

### ISSUE THREAD

**Issue by tenshilg** [rails/rails#24239]
### Steps to reproduce
Hello guys,
Can't include **ActionController::Cookies** into controller inherited from **ActionController::API**
[Here is a gist reproducing the bug] (https://gist.github.com/tenshilg/056076c0507709c587b7) 

### Expected behavior
Successfully included **ActionController::Cookies** into **ApplicationController** inherited from **ActionController::API**

### Actual behavior
Can't include module due to method missing in **ActionController::API**

### System configuration
**Rails version**: all since 5.0.0 beta1

**Ruby version**: 2.2.3, 2.3.0

**Comment by sonianand11** [comment]
Hi @tenshilg , I new to contribute in Rails, but I tried to resolve your issue. I got your code working when I  add `AbstractController::Helpers` in `ActionController::API` modules at here https://github.com/rails/rails/blob/master/actionpack/lib/action_controller/api.rb#L112

Here is how it looks like :
```
    MODULES = [
      AbstractController::Rendering,
      AbstractController::Helpers,
      UrlFor,
      Redirecting,
      ApiRendering,
      Renderers::All,
      ConditionalGet,
      BasicImplicitRender,
      StrongParameters,

      ForceSSL,
      DataStreaming,

      # Before callbacks should also be executed as early as possible, so
      # also include them at the bottom.
      AbstractController::Callbacks,

      # Append rescue at the bottom to wrap as much as possible.
      Rescue,

      # Add instrumentations hooks at the bottom, to ensure they instrument
      # all the methods properly.
      Instrumentation,

      # Params wrapper should come before instrumentation so they are
      # properly showed in logs
      ParamsWrapper
    ]
```

**Comment by tenshilg** [comment]
@sonianand11, I've already made a pull request couple of hours ago with almost the same solution you've written here

**Comment by sonianand11** [comment]
oh, my mistake.

**Comment by rthbound** [comment]
@tenshilg I'm not sure this is a bug. The middleware stack for an API application is intentionally trimmed down. Cookies are a browser thing.  Requests bound for an API could come from browsers, but they could also come from anywhere else.

I'm assuming your goal is to **read** (_not_ write) the value of a cookie inside your API controller. I'm also assuming the content of that cookie represents some auth-related information. Personally, I'd require my API clients to convey that info (I'm guessing an auth token) in the request headers/body.

**Comment by tenshilg** [comment]
@rthbound, I'm not sure that we are on the same page with you. I don't want to add the cookies middleware into the default middleware stack in API mode. I want to fix an ability to include cookies into your controller if you need it. At least the ability to do so is mentioned in [rails guides](http://edgeguides.rubyonrails.org/api_app.html#choosing-controller-modules)

**Comment by spastorino** [comment]
Unfortunately this is the way all this stuff works. If you need cookies you need the middleware and the module. You can't add the module for one controller.

It could be nice at some point to have some controllers working with a middleware stack and other controllers working with a different one but not possible now.

I'm closing this but this remains as future work.

**Comment by spastorino** [comment]
Sorry, I didn't read the issue carefully enough.

The idea though is to avoid adding stuff not needed when you use Rails as an API and cookies is one example of something to avoid.
Anyway you should be able to add that back if you want.
Let me check it and I will paste a way to get that working.

**Comment by spastorino** [comment]
Ok, as you can see here https://github.com/rails/rails/blob/07f3ae8f35d2c422b0fd8d794af0f781aad9a96e/actionpack/lib/action_controller/metal/cookies.rb#L6 ActionController::Cookies depends on helper_method which is defined here https://github.com/rails/rails/blob/07f3ae8f35d2c422b0fd8d794af0f781aad9a96e/actionpack/lib/abstract_controller/helpers.rb#L61

So you need to do ...

```ruby
class TestController < ActionController::API
  include AbstractController::Helpers
  include Rails.application.routes.url_helpers
  include ActionController::Cookies

  def index
    render plain: 'Home'
  end
end
```

**Comment by tenshilg** [comment]
@spastorino, thank you for the detailed explanation. I think then it is worth mentioning in [rails guides](http://edgeguides.rubyonrails.org/api_app.html#choosing-controller-modules) because it has missleading sentence:

> All Action Controller modules know about their dependent modules, so you can feel free to include any modules into your controllers, and all dependencies will be included and set up as well.

**Comment by spastorino** [comment]
@tenshilg :+1: can you provide a PR explaining all this?.

**Comment by tenshilg** [comment]
@spastorino, sure, will do it on a weekend

**Comment by matthewd** [comment]
I think this is a bug we should fix... I see no reason that sentence can't be true.

**Comment by spastorino** [comment]
@matthewd the solution involves a huge refactor of how AP works. I think we should fix it, but nothing that a simple include solves.

**Comment by spastorino** [comment]
@matthewd well maybe we are talking about different issues :/
