### ISSUE TITLE
TypeError: no implicit conversion of Hash into String when action_mailer.default is set

### ISSUE THREAD

**Issue by Unknown-Guy** [rails/rails#24241]
### Steps to reproduce
```
rails plugin new dummy_engine --mountable
```
Set ``action_mailer.default`` in ``config/environments/development.rb``
```ruby
config.action_mailer.default = { from: 'no@reply.me' }
```
Start console and try including non existing module

### Expected behavior
Should get ``NameError: uninitialized constant``

### Actual behavior
```
TypeError: no implicit conversion of Hash into String
	from /Users/me/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/activesupport-5.0.0.beta3/lib/active_support/dependencies.rb:442:in `join'
	from /Users/me/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/activesupport-5.0.0.beta3/lib/active_support/dependencies.rb:442:in `block in search_for_file'
```
I added dumb output in ``search_for_file`` method and it seems ``config.action_mailer.default`` has somehow been added to ``autoload_paths``

```
/Users/Me/Projects/dummy_engine/test/dummy/app/assets
/Users/Me/Projects/dummy_engine/test/dummy/app/channels
/Users/Me/Projects/dummy_engine/test/dummy/app/controllers
/Users/Me/Projects/dummy_engine/test/dummy/app/controllers/concerns
/Users/Me/Projects/dummy_engine/test/dummy/app/helpers
/Users/Me/Projects/dummy_engine/test/dummy/app/jobs
/Users/Me/Projects/dummy_engine/test/dummy/app/mailers
/Users/Me/Projects/dummy_engine/test/dummy/app/models
/Users/Me/Projects/dummy_engine/test/dummy/app/models/concerns
/Users/Me/Projects/dummy_engine/app/assets
/Users/Me/Projects/dummy_engine/app/controllers
/Users/Me/Projects/dummy_engine/app/helpers
/Users/Me/Projects/dummy_engine/app/jobs
/Users/Me/Projects/dummy_engine/app/mailers
/Users/Me/Projects/dummy_engine/app/models
{:from=>"no@reply.me"}
```

As a workaround changing to ``config.action_mailer.default_options`` seems fix the issue.

### System configuration
**Rails version**: Rails 5.0.0.beta3

**Ruby version**: ruby 2.3.0p0 (2015-12-25 revision 53290) [x86_64-darwin15]

**Comment by maclover7** [comment]
Can you create an executable test script using one of the templates [here](https://github.com/rails/rails/tree/master/guides/bug_report_templates), that would demonstrate the problem you are seeing?

**Comment by Unknown-Guy** [comment]
This line https://github.com/rails/rails/blob/master/actionmailer/lib/action_mailer/railtie.rb#L69 adds ``config.action_mailer.default`` to path. 

It seems setting ``default`` on ``ActiveSupport::OrderedOptions`` instance will return this default for any option that's not set explicitly. In a nutshell this is what happens:
```ruby
begin
  require 'bundler/inline'
rescue LoadError => e
  $stderr.puts 'Bundler version 1.10 or later is required. Please update your Bundler'
  raise e
end

gemfile(true) do
  source 'https://rubygems.org'
  gem 'rails', github: 'rails/rails'
end

require 'active_support'
require 'active_support/core_ext/object/blank'
require 'minitest/autorun'

class BugTest < Minitest::Test
  def test_stuff
    options = ActiveSupport::OrderedOptions.new
    options.default = 'something'
    assert_equal nil, options.preview_path
  end
end
```

Is this intended behaviour?

**Comment by rafaelfranca** [comment]
`default` is not a valid option. What you are looking for is `default_options`. The behavior you are seeing is a consequence of `OrderedOptions` inheriting from `Hash` and because of that it has a `#default=` method.

**Comment by Unknown-Guy** [comment]
Yes, but this was OK way to set options in previous rails versions. And it is still mentioned here https://github.com/rails/rails/blob/master/actionmailer/lib/action_mailer/base.rb#L499

This might bite quite a lot of people upgrading rails.

**Comment by rafaelfranca** [comment]
And it still is. The documented method is `#default` but you are using the `#default=` method, and that method is from Hash.

**Comment by Unknown-Guy** [comment]
Now it's clear, if it was never intended to be used like that so closing.
