### ISSUE TITLE
text_field doesn't display correctly with attribute default value of Proc

### ISSUE THREAD

**Issue by willnet** [rails/rails#24249]
### Steps to reproduce

[executable test case](https://gist.github.com/willnet/ad7051680a340624b72c)

- create new rails project
- rails g scaffold post title
- rails db:migrate
- modify post model like following

```ruby
class Post < ApplicationRecord
  attribute :title, :string, default: -> { 'hello' }
end
```

- rails s
- visit http://localhost:3000/posts/new

### Expected behavior

![image](https://cloud.githubusercontent.com/assets/82371/13899309/5948ba04-ee2e-11e5-937a-0dbe272f5503.png)

### Actual behavior

![image](https://cloud.githubusercontent.com/assets/82371/13899295/0446ee90-ee2e-11e5-9625-c82859032751.png)

### System configuration
**Rails version**:
5.0.0.beta3 and master

**Ruby version**:
2.3.0

**Comment by maclover7** [comment]
Is passing a `Proc` supported, as per the documentation?

**Comment by prathamesh-sonpatki** [comment]
cc @sgrif

**Comment by willnet** [comment]
@maclover7 

[This example](https://github.com/rails/rails/blob/55a205c552a4815c692355ca6bcf087524ebae92/activerecord/lib/active_record/attributes.rb#L82-L88) seems to say that we can use Proc.

**Comment by sgrif** [comment]
@tessgriffin is going to take a look at this w/ my supervision

**Comment by Sen-Zhang** [comment]
Replace the old solution with a new one.
