### ISSUE TITLE
`attribute` not backed by a db column crashes when `partial_writes` is set to false

### ISSUE THREAD

**Issue by Edouard-chin** [rails/rails#24246]
Not sure if this is a legit issue or an undocumented side effect of using both `attribute` and setting `partial_writes = false` at the same time. 

### Steps to reproduce

Please find this gist reproducing the bug: https://gist.github.com/Edouard-chin/b0233d159d6132662309

### Expected behavior
From rails doc [Attributes do not need to be backed by a database column](http://edgeapi.rubyonrails.org/classes/ActiveRecord/Attributes/ClassMethods.html#method-i-attribute).
This is working fine and we should be able to override/define the desired type for an attribute on the model
```ruby
attribute :unexisting_column, ActiveRecord::Type::Date
```

### Actual behavior
Setting [partial_writes](https://github.com/rails/rails/blob/master/activerecord/lib/active_record/attribute_methods/dirty.rb#L16) to false as well as using `attribute` on a non db backed column raises a `ActiveRecord::StatementInvalid` as ActiveRecord will try to persist every attributes defined in the model and not only the ones that are persistable. https://github.com/rails/rails/blob/master/activerecord/lib/active_record/attribute_methods/dirty.rb#L118-L124 
### System configuration
**Rails version**:
Both rails gem 4.2.6 and master is affected
**Ruby version**:
2.2.4

I would be glad to fix the issue (if it appears it's a real issue) based on your advices. Thanks!

**Comment by Edouard-chin** [comment]
Still new to rails and actively reading the codebase, I was wondering in what circumstances would we want [arel_attributes_with_values] (https://github.com/rails/rails/blob/master/activerecord/lib/active_record/attribute_methods.rb#L427) method to return a un-persistable `Arel::Attributes::Attribute`?

**Comment by sgrif** [comment]
This feature is not intended to work without partial writes.
