### ISSUE TITLE
Development logging is inconsistent in Rails 5 beta 3

### ISSUE THREAD

**Issue by codeodor** [rails/rails#24251]
### Steps to reproduce

Upgrade 4.2.6 app to 5.0.beta3
Try to load a page.
View the development.log file.

### Expected behavior
The development.log file and console screen should be written to.

### Actual behavior
Sometimes it writes, sometimes it doesn't.

### System configuration
**Rails version**: 5.0.beta3

**Ruby version**: 2.3.0

**Comment by rafaelfranca** [comment]
Can you please provide a sample application that reproduces the error?

**Comment by codeodor** [comment]
@rafaelfranca when I switched to thin from Webrick, the problem went away. Maybe the issue is in Webrick. I'll close for now.

**Comment by shakycode** [comment]
@codeodor I had the exact same problem with webrick.  I used thin and had no problems.

**Comment by alexshk** [comment]
@codeodor Thanks! Had same problem.
