### ISSUE TITLE
ActiveSupport::LoggerThreadSafeLevel does not work with stdlib ::Logger without monkeypatching

### ISSUE THREAD

**Issue by schneems** [rails/rails#24263]
In https://github.com/rails/rails/pull/20507 thread safety was introduced but requires the target class to implement code to call an `after_initialize` method if it exists. This means that if you are setting the Rails logger to 

```
config.logger = ::Logger.new(STDOUT)
config.logger.extend(ActiveSupport::LoggerThreadSafeLevel)
```

Then you cannot use logger silencing with your logger. It was discussed in the contributor room. It was decided that we should implement this behavior automatically and that loggers should not have to implement custom initializers with boilerplate to get this behavior to work. cc/ @carlosantoniodasilva

**Comment by schneems** [comment]
I tried to auto prepend a module in an included block but it didn't work

```ruby
require 'active_support/concern'

module Bar
  extend ActiveSupport::Concern

  included do |base|
    puts "== included block called"
    Foo.prepend Bar
  end

  def initialize
    super
    puts "bar"
  end
end

class Foo
  include Bar

  def initialize
    puts "foo"
  end
end


Foo.new
# => == included block called
# => foo
```

**Comment by rafaelfranca** [comment]
For the stable releases it is also possible to revert that change, but it will be still broken in Rails 5.

**Comment by schneems** [comment]
I would prefer a backwards compatible fix over reverting the commit if possible.

**Comment by carlosantoniodasilva** [comment]
@schneems thanks for opening the issue about this. As for include + auto prepend, I think it's because you can't do it with _the same_ module, similarly as including it twice yields in a single ancestor. If you print Foo's ancestors at the end of your test script, you'll get this:

```
== included block called
[Foo, Bar, Object, Kernel, BasicObject]
foo
```

However, prepending _another_ module seems to work:

```ruby
require 'active_support/concern'

module Baz
  def initialize
    super
    puts 'baz'
  end
end

module Bar
  extend ActiveSupport::Concern

  included do |base|
    puts "== included block called"
    base.prepend Baz
  end
end

class Foo
  include Bar

  def initialize
    puts "foo"
  end
end

puts Foo.ancestors.inspect
Foo.new

=begin
== included block called
[Baz, Foo, Bar, Object, Kernel, BasicObject]
foo
baz
=end
```

I'll investigate a fix for this.

**Comment by carlosantoniodasilva** [comment]
@schneems @rafaelfranca here are some changes that seem to do the trick for master: https://github.com/rails/rails/compare/master...carlosantoniodasilva:as-logger-level-api, let me know what you think.

I'll open a pull request later if it's all good, and work on similar changes for 4.x stable.

**Comment by schneems** [comment]
Can we do it and keep the exact same include api? something like

```
module ActiveSupport::LoggerThreadSafeLevel
  extend ActiveSupport::Concern

  include do |base|
    base.prepend(ActiveSupport::LoggerThreadSafeLevel::Prepend)
  end


  module Prepend
    # put logic here
  end
end
```

That way anyone doing an include on the old module does not have to change, otherwise we would need to detect and deprecate.

**Comment by carlosantoniodasilva** [comment]
Yeah we may be able to, but I don't think anyone should be using that module directly as it's nodoc'ed and was just recently introduced. And if they are, I guess as "beta" it's an allowed change still. But I'd be fine trying to keep the "include" path the default if we wanted that for this module.

**Comment by schneems** [comment]
It's up to you, i'm playing catch up here, I added docs for the module in https://github.com/rails/rails/pull/24218 but I do not know how many people are using it. The change was also backported right?

**Comment by carlosantoniodasilva** [comment]
Yes it was backported... I think the better API would be to only have to include the `LoggerSilence` module (which my changes do), so people wouldn't have to remember/care about the thread safety one (it's like an implementation detail to me).

I'll see what can be done about the backports. Thanks!

**Comment by schneems** [comment]
I'm also wondering if we could detect correct logging compliance and warn when it isn't presence. I.e. see if the logger passed in has been extended by TaggedLogging and has silent logging included and give out a warning when those things aren't implemented correctly. I listed out some other ideas we could maybe implement in that PR that might make logging a bit easier.

**Comment by schneems** [comment]
Any progress here?

**Comment by rafaelfranca** [comment]
@carlosantoniodasilva that changes looks good to me. :truck: :candy:

**Comment by schneems** [comment]
We good here? Can we close this issue?

**Comment by rafaelfranca** [comment]
I think so. I backported a commit to 4-2-stable that should take care of this.

**Comment by dwbutler** [comment]
This is still a problem in Rails 5.0.0. [ActiveSupport:: LoggerThreadSafeLevel](https://github.com/rails/rails/blob/v5.0.0/activesupport/lib/active_support/logger_thread_safe_level.rb) doesn't work with Ruby stdlib's `Logger` class unless it is overridden to call `after_initialize`.

**Comment by dwbutler** [comment]
The same issue is probably affecting [Rails 4.2.7](https://github.com/rails/rails/blob/v4.2.7/activesupport/lib/active_support/logger_thread_safe_level.rb) since the fix was backported. (But I haven't verified this.)
