### ISSUE TITLE
Client-side memory leak in 5.0.0beta3 when calling "return false" in a controller

### ISSUE THREAD

**Issue by MaxPleaner** [rails/rails#24265]
### Steps to reproduce

Clone [this repo](https://github.com/maxpleaner/prototypical) and checkout the `rails-bug` branch.
1. `bundle install`
2. run `db_setup.sh` which creates the database and runs migrations (uses postgres)
3. run `rails server`.
  1. Using Chrome, go to [http://localhost:3000/company_search](http://localhost:3000/company_search). The action is in `PagesController`, and it is empty except for a single `render` and `return`. Open the Chrome process manager with `shift+esc`. Since this controller action calls `render` before `return`, there is no memory leak.
  2. go to [http://localhost:3000/company_search2](http://localhost:3000/company_search2). The Chrome process manager will show this tab gradually increasing in memory. I let it get as high as 1GB before I closed it. The only difference between this route and the other is is the order in which `render` and `return` are called. 

There is no console output relating to this bug. The rails console shows that the response is successfully sent with a no-content status code

Not sure if it is relevant but I have `ActiveSupport.halt_callback_chains_on_return_false = false`

### Expected behavior

Calling `return false` in a controller action should cause an immediate no-content response if `render`
has not already been called. The  browser should display the page load as finished.

### Actual behavior

The console says that the request has successfully completed with No-Content. 
The browser renders no content, but the page load is not indicated as finished. The memory of the tab gradually increases to 1GB+

### System configuration

**Rails version**:

Rails 5.0.0.beta3

**Ruby version**:

ruby 2.4.0dev (2015-12-26 trunk 53314) [x86_64-linux]

**Comment by maclover7** [comment]
Can you create an executable test script using one of the templates [here](https://github.com/rails/rails/tree/master/guides/bug_report_templates), that would demonstrate the problem you are seeing?

**Comment by MaxPleaner** [comment]
@maclover7 I actually had tried that, but the problem only manifests itself on the client side. I am looking at Capybara's Poltergeist driver now, but I'm not very fluent in headless-browser testing.

**Comment by fxn** [comment]
Returning false in an action is not a way to halt execution. In the past it was a way to halt a filter, but that is not even the case today, you need to render or redirect.

Same in the action, at least `head :ok`. See http://guides.rubyonrails.org/layouts_and_rendering.html#creating-responses.

**Comment by rafaelfranca** [comment]
If the Rails application sent the `no-content` status code so Rails did what is its responsibility to do. But like @fxn explained `return false` is not the way to finish the execution of an action. What the browser console tell about the request? Is it finished?

**Comment by fxn** [comment]
Returning false is no different than doing

```ruby
def index
  @is_admin = current_user.is_admin?
end
```

When the action does not render or redirect explictly Rails has a fallback to the action template. If the action template does not exist you get an error. `company_search2` does not raise because the view in https://github.com/MaxPleaner/prototypical/blob/master/app/views/pages/company_search2.html.erb is rendered and guess the JavaScript at the bottom is producing the leak.

I have not run the application, but I am pretty sure that's what's going on. There seems to be no Rails bug here.

**Comment by MaxPleaner** [comment]
Oh drat. Sorry to bother you with that.

**Comment by fxn** [comment]
No prob at all! If you think there's a bug indeed it's great that you take the time to report it. You had an app and filled the template, etc. Good bug report. If it turns to be something else, all is good. Thanks anyway.
