### ISSUE TITLE
Default option missing for an attribute in NumberHelper API Documentation

### ISSUE THREAD

**Issue by Dusht** [rails/rails#24262]
### Steps to reproduce

http://api.rubyonrails.org/classes/ActionView/Helpers/NumberHelper.html#method-i-number_to_human

### Expected behavior
Default value should be there i.e. `,`

### Actual behavior
See this screenshot
![actionview helpers numberhelper](https://cloud.githubusercontent.com/assets/1715709/13915311/f10405d2-ef79-11e5-91ab-9c99d76f5c53.png)

**Comment by AndreasWurm** [comment]
why should "," be default over empty string? i think no delimiter is a very reasonable default.

**Comment by Dusht** [comment]
@AndreasWurm But with that logic, all the remaining defaults should be removed too. ?

**Comment by AndreasWurm** [comment]
i dont get it. nobody is talking about removing defaults, and as i said earlier it has a default, an empty string.

**Comment by vipulnsward** [comment]
Thanks for reporting, but this correct and as documented.
