### ISSUE TITLE
Routing Specs don't set query_parameters on request

### ISSUE THREAD

**Issue by dkolath** [rails/rails#24277]
### Steps to reproduce
In order to support legacy routes, I have a constraint that keys off query_parameters to decide which action/controller to route to. Previously, delete and create were being passed to the same legacy route.

Both legacy routes are being called as get requests.

```
class SomeObjectLegacyConstraint
  def self.matches?(request)
    request.query_parameters.fetch(:options, {})[:destroy]
  end
end
```
In the routes:

```
  get '/update/some_object', controller: :some_object, action: :destroy_object, constraints: SomeObjectLegacyConstraint
  get '/update/some_object', controller: :some_object, action: :create_object
```

spec_file

```
      it 'should route and recognize create or destroy some_object' do
        expect({get: '/update/some_object?options[destroy]=true'}).to route_to(controller: 'some_object', action: 'destroy_object', options: {'destroy'=>'true'})
      end
```
### Expected behavior
Expect the test to pass

### Actual behavior
The functionality works via the browser, but when running specs it fails. After tracing the code, it doesn't look like query_parameters are getting set on the ActionController::TestRequest

### System configuration
**Rails version**: 4.2

**Ruby version**: 2.2.3

**Comment by maclover7** [comment]
Can you create an executable test script using one of the templates [here](https://github.com/rails/rails/tree/master/guides/bug_report_templates), that would demonstrate the problem you are seeing?

**Comment by pixeltrix** [comment]
@dkolath routing specs in rspec-rails are essentially controller specs and as such they are similar to `ActionController::TestCase` in that they don't go through the full request stack. To check routing constraints use a request spec instead.
