### ISSUE TITLE
ActiveModel::Errors#include? adding a key to @messages hash

### ISSUE THREAD

**Issue by kitop** [rails/rails#24279]
### Steps to reproduce
```ruby
class Dummy
  include ActiveModel::Model
  attr_accessor :name
end

record = Dummy.new

record.errors # => #<ActiveModel::Errors, @messages={}, @details={}>

record.errors.include? :foo # => false

record.errors # => #<ActiveModel::Errors @messages={:foo=>[]}, @details={}>
```

### Expected behavior
Checking if ActiveModel::Errors has a value, shouldn't add that key to the `@messages` hash.

### Actual behavior
By doing `record.errors.include? :foo`, it actually adds a new key to the `@messages` hash that defaults to an empty array.

This happens because of a combination of these 2 commits:
https://github.com/rails/rails/commit/b97035df64f5b2f912425c4a7fcb6e6bb3ddab8d (Added in Rails 4.1)
and
https://github.com/rails/rails/commit/6ec8ba16d85d5feaccb993c9756c1edcbbf0ba13#diff-fdcf8b65b5fb954372c6fe1ddf284c78R76 (Rails 5.0)

By adding the default proc that returns an array for non-existing keys, ruby adds that key to the hash.

Ideally, `#include?` should do check with `has_key?` and then check if that value is `present?`.

What do you think?
More than happy to send a PR if you think this is correct. Is it worth to add a test case?

### System configuration
**Rails version**: 5.0.0.beta3

**Ruby version**: 2.2.4, 2.3.0

**Comment by maclover7** [comment]
Related to #23468.

**Comment by prathamesh-sonpatki** [comment]
> Ideally, #include? should do check with has_key? and then check if that value is present?.

:+1: @kitop Please send PR

**Comment by kitop** [comment]
@prathamesh-sonpatki Sure!
Working on it right now.

**Comment by kaspth** [comment]
Fixed in https://github.com/rails/rails/pull/24299 👍
