### ISSUE TITLE
Engine routes scope issue

### ISSUE THREAD

**Issue by lucaspiller** [rails/rails#24272]
### Steps to reproduce

I'm in the process of upgrading an old Rails application, and when upgrading from Rails 4.1.5 to 4.2.6 a weird issues with engine routing appeared.

The application is mounted under a subdirectory and we have a scope in `config/routes.rb` which wraps everything under `ENV['RAILS_RELATIVE_URL_ROOT']`. So if you set `RAILS_RELATIVE_URL_ROOT=app`, the app is available at `http://example.com/app/`. We also have an engine mounted at `/`, which has it's own routes.

The full `config/routes.rb` is as follows:

``` ruby
scope ENV['RAILS_RELATIVE_URL_ROOT'] || '' do
  mount Authentication::Engine => '/'
  root 'application#test'
end
```

And of the engine:

``` ruby
get '/login', to: 'application#login'
```

So together, these translate to:

http://example.com/app -> ApplicationController#test
http://example.com/app/login -> Authentication::ApplicationController#login

In the test action, we redirect to the engine:

``` ruby
redirect_to authentication.login_url
```

Instead of a redirect to `http://example.com/app/login`, this redirects to `http://example.com/login` which results in a 404 and hours of debugging.

This fix it seems is easy, switch around the the order of `root` and `mount` in the routes definition. In 4.1.5 it doesn't matter what order they are in.

I've created a sample application to demonstrate the issue: https://github.com/lucaspiller/rails-engine-routing-bug (see the commit messages for example commands / commentary)
### Expected behavior

The order of entries in `config/routes.rb` shouldn't matter.
### Actual behavior

The order of entries in `config/routes.rb` does matter.
### System configuration

**Rails version**: 4.2.6

**Ruby version**: 2.3.0 and 2.2.2

**Comment by brad-werth** [comment]
This just bit us, as well. Thanks for pointing out the re-ording hack, you saved me a ton of time. Not an ideal solution, but it will work for now.

**Comment by maclover7** [comment]
Hmm, this sounds like a possible bug. Can you simplify your test application, and create an executable test script using one of the templates [here](https://github.com/rails/rails/tree/master/guides/bug_report_templates), that would demonstrate the problem you are seeing? Also, does this appear on Rails master?

**Comment by brad-werth** [comment]
@maclover7 Did you ever get a simplified test application and bug template? If not, I can try to put something together, although this is difficult to demonstrate with a simple example.

**Comment by zspoelstra** [comment]
Seeing the same issue here as well. I haven't been able to pinpoint the exact cause yet, but it seems to revolve around a namespace or resource with the same name as the mount point. I haven't figure out which one yet.

One thing I noticed is that the path helper only stops working when I am in a view within the namespace or resource. It works fine everywhere else. Moving the mount after the namespace definition fixes it

I'll try to get a simple test application that demonstrates this.

**Comment by soupmatt** [comment]
I just ran in to this with an application that doesn't have a root directive in the routes file. It works fine on rails 4.2.4, but breaks under 4.2.5 and later.
