### ISSUE TITLE
Controller variables not visible in json.erb file

### ISSUE THREAD

**Issue by sadinie** [rails/rails#24280]
I don't know if this is a bug, I have never had to use json before in Rails. But searching for a solution found nothing to fix it.
### Steps to reproduce

I am using Fine Uploader to asynchronously upload a file since Remotipart is broken with Rails 5.

The file uploads fine but I need to return the id of the uploaded file back with the success json.

{"success": true,"image_id": "<%= raw @file_id %>"}

@file_id has the correct value in the controller action but is nil in the json.erb file.

(Guidelines for creating a bug report are [available
here](http://guides.rubyonrails.org/contributing_to_ruby_on_rails.html#creating-a-bug-report))
### Expected behavior

@file_id should have a value.
### Actual behavior

The value sent to the browser is nil for @file_id
### System configuration

**Rails version**: 5.0.0beta3

**Ruby version**: 2.3.0p0

**Comment by rafaelfranca** [comment]
You need to give us more information on how to reproduce this issue, otherwise there is nothing we can do. Please read CONTRIBUTING.md file for more information about creating bug reports. Thanks!

**Comment by sadinie** [comment]
I gave everything I did to get to that point.

There are no errors in the logs to post.

It is really simple:

@file_id has a valid value in the action. It is null in that actions json.erb file.

How to reproduce it? send a json request to an action and try to pass a instance variable to that actions json.erb?

What is confusing about that?

**Comment by rafaelfranca** [comment]
It is missing some key information like what is `@file_id`? What is the controller code of that action? Without this there is no way to us to understand if the problem is in the framework on in your application code.

**Comment by sadinie** [comment]
class Image
...

def upload
unless params[:image].nil?
      gi = GalleryImage.new
      gi.picture=params[:image]
      gi.save #image properly uploads and saves
     @file_id=gi.id #not null here
    end
end

in upload.json.erb file
{"success": true,"image_id": "<%= raw @file_id %>"}

**Comment by rafaelfranca** [comment]
Can you please provide a sample application that reproduces the error?

**Comment by rafaelfranca** [comment]
For what I could see in this code `@file_id` can be `nil` if `params[:image]` is `nil`.

**Comment by rafaelfranca** [comment]
Also if `gi.id` is `nil`

**Comment by sadinie** [comment]
params[:image] is NOT nil. It could be if things went wrong, but as I noted _numerous_ times that the file uploads correctly so gi is not nil, and since it saves without error gi.id is _not_ nil.

I omitted the error checking code to make things clearer.

The ONLY thing that is wrong is that @file_id is nil in the json.erb file.

def upload
unless params[:image].nil?
gi = GalleryImage.new
gi.picture=params[:image]
gi.save #image properly uploads and saves
@file_id=gi.id #not null here
**_puts @file_id #prints 12, not nil_**
end

I gave you everything you asked for but now want an entire app to reproduce it?

**Comment by rafaelfranca** [comment]
Yes, we have test to make sure that this behavior works and none of them are failing so it would help us if you could provide an easy way to reproduce your problem.

**Comment by rafaelfranca** [comment]
I also tried to reproduce your problem in a new application and I could not. Instance variables are available in the `json.erb` files.

**Comment by sadinie** [comment]
I will try to get at that this afternoon.

As an aside, a built in way to handle async uploads would be great.

**Comment by sadinie** [comment]
I created a new app and just used basic JQuery ajax request and it worked. 

The app having the problem is an existing app that is being migrated from Rails 4 to 5. This isn't the first weird issue like this in Rails 5 beta. I guess I will create a new app first before posting a bug report. Sorry about that. 

I have no idea where the problem in my app could be or even where to start.
