### ISSUE TITLE
as_json works differently for preload and eagerload

### ISSUE THREAD

**Issue by salmanasiddiqui** [rails/rails#24314]
### Steps to reproduce
```
class Portfolio < ActiveRecord::Base
  has_many :tickets
end
class Ticket < ActiveRecord::Base
  belongs_to :portfolio
end

@tickets = Ticket.includes(:portfolio).select('tickets.*', 'SUBSTRING(tickets.title,1,4) as code')
@tickets.first.as_json
@tickets.references(:portfolio).first.as_json
```

### Expected behavior
`@tickets.first.as_json` should be equal to `@tickets.references(:portfolios).first.as_json`

### Actual behavior
`@tickets.first.as_json` includes the **code** (alias column defined in the `select`)
`@tickets.references(:portfolios).first.as_json` does not include the **code** (alias column defined in the `select`)

### Note
The problem arises only when `eager_load` is called by `includes`, `preload` works fine. More to that, using `joins` works fine aswell. 

### System configuration
**Rails version**: 4.2.6

**Ruby version**: 2.1.8

**Comment by vipulnsward** [comment]
@salmanasiddiqui I did not get the use of `references` in this context? Its not being used.
The result of references vs includes is a bit different. In the former we need to construct results based on aliases, and don't happen to use select clauses, unlike includes, which is causing the difference.

**Comment by salmanasiddiqui** [comment]
I just wanted to show that `eager_load` and `preload` are producing different results. If we dont use `references`, instead use `where(portfolios: {id: [3,2]})` the result will be same. As Rails will also use the `eager_load` instead of `preload` in that case.
are you saying that this is the correct behavior? Is `select `ignored incase when `includes` results in `LEFT JOIN`? Is this documented somewhere?

**Comment by vipulnsward** [comment]
Hi @salmanasiddiqui this isn't documented, but a known limitation. Going to mark this as a documentation issue.

**Comment by salmanasiddiqui** [comment]
Known limitation, u mean that this cant be fixed and there isnt any workaround aswell?

I don't think that documenting it, is enough. It should also log a warning that select is being ignored in such scenarios.

**Comment by sgrif** [comment]
This isn't even a limitation. This is the expected behavior. When you put an additional field in the select column, it is accessible through the record. I don't think this warrants a mention explicitly on `as_json`, and the behavior of `select` is thoroughly documented.

**Comment by vipulnsward** [comment]
@sgrif the issue is that select isn't returning extra selected values in case of eager load.

**Comment by sgrif** [comment]
Ah, I see now. It's a very confusingly set up report...

**Comment by salmanasiddiqui** [comment]
workaround for anyone else facing this issue

replace `includes` with `preload` and use `joins`

example:
`@tickets = Ticket.preload(:portfolio).joins('LEFT JOIN portfolios on portfolios.id = tickets.portfolio_id').select('tickets.*', 'SUBSTRING(tickets.title,1,4) as code').order('portfolios.name')`

**Comment by al2o3cr** [comment]
@sgrif Is this the same issue seen in #12423 and #15185?

**Comment by sgrif** [comment]
Looks like it, yes.
