### ISSUE TITLE
ApplicationMailer.some_method(some_ar_object).deliver_later hanging onto DB connections in default config

### ISSUE THREAD

**Issue by erikse** [rails/rails#24316]
I have a controller action that calls `deliver_later` on a mailer method that receives an AR object, which I thought would be run immediately by the [default active job handler - immediate runner](http://edgeguides.rubyonrails.org/active_job_basics.html) and release the database connection back to the pool.

### Steps to reproduce

I've pushed a sample app to www.github.com/erikse/deliver_later

Error occurs with no special setup, just `bundle` & `rails s`, and visiting localhost:3000 5 to 6 times.

### Expected behaviour

To see the home page.

### Actual behaviour

On the 5th or 6th visit, I'm seeing ActiveRecord::ConnectionTimeoutError
could not obtain a connection from the pool within 5.000 seconds (waited 5.005 seconds); all pooled connections were in use.

If I change the mailer method so it doesn't receive an active record `user` object, no error occurs.

### System configuration
**Rails version**:
5.0.0.beta3
**Ruby version**:
2.3.0

**Comment by maclover7** [comment]
@matthewd, looks like this is related to #24028 / #23989.

**Comment by vipulnsward** [comment]
@erikse this doesn't seem to fail for me on master with the App you provided(It does fail on Rails beta3).
Can you give it a try as well?

**Comment by erikse** [comment]
@vipulnsward it's not failing for me either [on master branch](https://github.com/erikse/deliver_later/tree/uprade_to_rails_edge), thanks!

**Comment by vipulnsward** [comment]
Thanks for confirming. Closing for now.
