### ISSUE TITLE
ActiveRecord::Schema Default Value

### ISSUE THREAD

**Issue by jwgoh** [rails/rails#24311]
### Steps to reproduce
1. Pull latest changes from remote repo
2. Run `rake db:migrate`

### Expected behaviour
Integer column to have default value of -1

### Actual behaviour
Integer column does not having default value (Notice that it seems to a problem for negative integer values only)

<img width="324" alt="screen shot 2016-03-25 at 12 06 32 pm" src="https://cloud.githubusercontent.com/assets/6704206/14037724/4740fde6-f282-11e5-82cf-8fa80bb9e15f.png">
- `git diff` after running `rake db:migrate`

<img width="487" alt="screen shot 2016-03-25 at 12 07 14 pm" src="https://cloud.githubusercontent.com/assets/6704206/14037725/474191c0-f282-11e5-8747-64dee107b394.png">

- Table schema from `psql` CLI

I think I might have an explanation as to why this is happening.
```ruby
when /\A\(?(-?\d+(\.\d*)?\)?(::bigint)?)\z/
```
The [regex](https://github.com/rails/rails/blob/9be9597e510d185ca7964d0a05b4ea2a7f2d50d1/activerecord/lib/active_record/connection_adapters/postgresql_adapter.rb#L95) above does not take into account inverted commas `'` when extracting default value from the columns.

I believe this is something new to PostgreSQL 9.5. The same table schema with PostgreSQL 9.3 (on Ubuntu 14.04 machine but I don't think it makes a difference).
![screenshot from 2016-03-25 12_18_52](https://cloud.githubusercontent.com/assets/6704206/14037885/08ed0a06-f284-11e5-8a49-8eccd40fdce6.png)

### System configuration
**Rails version**: 4.0.12

**Ruby version**: 2.0.0

**Mac OS X**: v10.11.3

**PostgreSQL**: 9.5.1

**Comment by sevaorlov** [comment]
@jwgoh, sorry, I couldn't reproduce it with this code https://gist.github.com/sevaorlov/042266fdb3b8c4f53ccb775bc3e058fb
on Rails 4.0.12, PostgreSQL 9.5.1

`default: -1` is exported to schema for me. am I doing something wrong?

**Comment by jwgoh** [comment]
Wow, thanks for the bug report template @sevaorlov 

I ran your script (added version for `pg` gem) and it fails. My modified [script](https://gist.github.com/jwgoh/ecf4b5af925e8a97413b4089d0e37a34)

Additionally, I dumped the output of the schema into a file and here is what I got.
![screen shot 2016-04-03 at 5 55 20 pm](https://cloud.githubusercontent.com/assets/6704206/14231846/695cad9a-f9c5-11e5-804e-b5117bdf0d6b.png)

**Comment by sevaorlov** [comment]
hm, strange, 0.18.4 is the last version, so I was using it. your script doesn't fail for me and the dump includes `default: -1`.
either default value is not created or not exported in a dump for you. can you check if default value is created in database? if not, then try to execute `ALTER TABLE \"users\" ADD COLUMN \"other_column\" integer DEFAULT -1` and see what happens?

if default value is created - what is the output of the following query? rails use it to fetch columns information.
```sql
SELECT a.attname, format_type(a.atttypid, a.atttypmod), pg_get_expr(d.adbin, d.adrelid), a.attnotnull, a.atttypid, a.atttypmod,
  (SELECT c.collname
   FROM pg_collation c,
        pg_type t
   WHERE c.oid = a.attcollation
     AND t.oid = a.atttypid
     AND a.attcollation <> t.typcollation)
FROM pg_attribute a
LEFT JOIN pg_attrdef d ON a.attrelid = d.adrelid
AND a.attnum = d.adnum
WHERE a.attrelid = 'users'::regclass
  AND a.attnum > 0
  AND NOT a.attisdropped
ORDER BY a.attnum
```

**Comment by sevaorlov** [comment]
rails 4.0.12 actually use this query
```sql
SELECT a.attname,
       format_type(a.atttypid, a.atttypmod),
       pg_get_expr(d.adbin, d.adrelid),
       a.attnotnull,
       a.atttypid,
       a.atttypmod
FROM pg_attribute a
LEFT JOIN pg_attrdef d ON a.attrelid = d.adrelid
AND a.attnum = d.adnum
WHERE a.attrelid = 'users'::regclass
  AND a.attnum > 0
  AND NOT a.attisdropped
ORDER BY a.attnum
```

**Comment by jwgoh** [comment]
![screen shot 2016-04-03 at 9 36 00 pm](https://cloud.githubusercontent.com/assets/6704206/14232662/3489e226-f9e4-11e5-86b2-f0e472962fcc.png)
Yes the default value is being created.

![screen shot 2016-04-03 at 9 36 16 pm](https://cloud.githubusercontent.com/assets/6704206/14232663/3497ceb8-f9e4-11e5-85be-ea36bb5900df.png)
If I run this [SQL Query](https://github.com/rails/rails/blob/1e92fe73522b58c353746aef30c395574ec1cdaf/activerecord/lib/active_record/connection_adapters/postgresql_adapter.rb#L730), the default value is there.

So I modified the script to add a column with **positive** default value, and it is being dumped into the schema correctly.
![screen shot 2016-04-03 at 9 42 09 pm](https://cloud.githubusercontent.com/assets/6704206/14232689/ff6b8b02-f9e4-11e5-8cb6-40b34492878b.png)

![screen shot 2016-04-03 at 9 44 19 pm](https://cloud.githubusercontent.com/assets/6704206/14232704/62d48d60-f9e5-11e5-842e-862f4216d147.png)

![screen shot 2016-04-03 at 9 44 42 pm](https://cloud.githubusercontent.com/assets/6704206/14232705/62d8a83c-f9e5-11e5-9432-06eeaec0b225.png)

None of the regex in the method `extract_value_from_default` (see [here](https://github.com/rails/rails/blob/9be9597e510d185ca7964d0a05b4ea2a7f2d50d1/activerecord/lib/active_record/connection_adapters/postgresql_adapter.rb#L82)) matches `'-1'::integer`.

**Comment by sevaorlov** [comment]
not sure why, but I have `default (-1)` in my `value` column, that is why it is working for me
try to update to Rails 4.2, there were changes in that method https://github.com/rails/rails/commit/405fd22e70e4c2d1117ace0a834cbcc438ea8ca9

**Comment by rafaelfranca** [comment]
Rails 4.0 is not supported anymore. Could you reproduce it in Rails 4.1+?

**Comment by jwgoh** [comment]
@rafaelfranca 
Yes, I am able to reproduce problem with Rails ~> 4.1.0. All working well on Rails 4.2+

**Comment by sevaorlov** [comment]
That is because that method was changed in rails 4.2. 
@rafaelfranca, do you want me port these changes https://github.com/rails/rails/commit/405fd22e70e4c2d1117ace0a834cbcc438ea8ca9 to Rails 4.1+?

**Comment by rafaelfranca** [comment]
At this point I'm not sure if it worth to backport a change to 4.1. We are really close to the Rails 5 release and when it is release 4.1 will not be maintained for bug fixes anymore. Because of that I'm closing this issue.

**Comment by jwgoh** [comment]
Hey guys, appreciate your time and discussion on this matter. @sevaorlov @rafaelfranca 

I will upgrade my Rails project to Rails 4.2, and looking forward to the release of Rails 5. :smiley:

**Comment by AlexCppns** [comment]
Hi, we are having this problem on Rails 3.2.22, do you guys know if this was patched in 3.x?

**Comment by mordecaijsdoc39** [comment]
> ![screen shot 2016-04-03 at 9 36 00 pm](https://cloud.githubusercontent.com/assets/6704206/14232662/3489e226-f9e4-11e5-86b2-f0e472962fcc.png) Yes the default value is being created.
> 
> ![screen shot 2016-04-03 at 9 36 16 pm](https://cloud.githubusercontent.com/assets/6704206/14232663/3497ceb8-f9e4-11e5-85be-ea36bb5900df.png) If I run this [SQL Query](https://github.com/rails/rails/blob/1e92fe73522b58c353746aef30c395574ec1cdaf/activerecord/lib/active_record/connection_adapters/postgresql_adapter.rb#L730), the default value is there.
> 
> So I modified the script to add a column with **positive** default value, and it is being dumped into the schema correctly. ![screen shot 2016-04-03 at 9 42 09 pm](https://cloud.githubusercontent.com/assets/6704206/14232689/ff6b8b02-f9e4-11e5-8cb6-40b34492878b.png)
> 
> ![screen shot 2016-04-03 at 9 44 19 pm](https://cloud.githubusercontent.com/assets/6704206/14232704/62d48d60-f9e5-11e5-842e-862f4216d147.png)
> 
> ![screen shot 2016-04-03 at 9 44 42 pm](https://cloud.githubusercontent.com/assets/6704206/14232705/62d8a83c-f9e5-11e5-9432-06eeaec0b225.png)
> 
> None of the regex in the method `extract_value_from_default` (see [here](https://github.com/rails/rails/blob/9be9597e510d185ca7964d0a05b4ea2a7f2d50d1/activerecord/lib/active_record/connection_adapters/postgresql_adapter.rb#L82)) matches `'-1'::integer`.
> 
> Interesting that it is working for you and not for me 😕





https://academic5.github.io/bkSZ7HzaCHoB4QuEsDy9jwM4crIKrR7xRlJRa/
