### ISSUE TITLE
Default submit button text casing changed in Rails 5

### ISSUE THREAD

**Issue by derekprior** [rails/rails#24319]
### Steps to reproduce

1. Run `rails generate scaffold post title:string`
2. Run `rails db:migrate`
3. Start up your server and go to http://localhost:3000/posts/new

### Expected behavior

Button should say "Create Post" as it did in Rails 4.

### Actual behavior

Button says "Create post"

### Impact

This changes the user interface of all users that upgrade to 5.0 in a subtle way. If you have tests that catch such things (by clicking on the "Update Post" button), changing the tests so that they pass (downcasing the model name) is tedious. Keeping the old behavior requires either using i18n for the value or creating your own submit helper.

This is a areally small thing, but if it matters to you it's not trivial to fix in larger apps. I couldn't find the original change for this, only PRs or issues that claim to ultimately have left the functionality intact. If this change is by design, it should appear in the changelog, I think.

**Comment by vipulnsward** [comment]
This has been fixed on master. https://github.com/rails/rails/commit/ddf4c953ae8d10489e0bfd6008bd76395f6e1267
