### ISSUE TITLE
Rails 5 Beta 3 Performance is Degraded Severely in one of my apps

### ISSUE THREAD

**Issue by codeodor** [rails/rails#24330]
### Steps to reproduce

I'm working on narrowing down the cause. Essentially, what happens is:

I load an action that takes less than 1 second in Rails 4.2.6 after upgrading to Rails 5.0.0.beta3, and the same action takes 7 seconds. It also appears to grow linearly: one section of code that runs in 3 seconds would take 21 seconds.

### System configuration
**Rails version**:  5.0.0.beta3 vs 4.2.6

**Ruby version**: MRI 2.3.0 on both

### Profiling comparison
I put a bunch of timing statements throughout the view on my app, and in most places there is a large increase in time in the Rails 5 version. I narrowed down further to a particularly bad spot (0.007 seconds in Rails 4, up to 0.12 seconds in Rails 5) and performed a profile of the code.

These are the top lines: 

#### Rails 4
```
 %self      total      self      wait     child     calls  name
  4.47      0.034     0.007     0.000     0.028      384  *Array#map
  3.20      0.005     0.005     0.000     0.000     1434   String#to_s
  3.02      0.015     0.004     0.000     0.011     1069  *Class#new
  1.77      0.003     0.003     0.000     0.000     1224   Kernel#hash
  1.67      0.002     0.002     0.000     0.000       42   Array#&
  1.49      0.013     0.002     0.000     0.011      220   ActiveRecord::AttributeMethods#attribute_for_inspect
```

#### Rails 5
```
%self      total      self      wait     child     calls  name
 79.38      0.617     0.617     0.000     0.000       56   Regexp#===
  0.87      0.039     0.007     0.000     0.032      413  *Array#map
  0.75      0.006     0.006     0.000     0.000     1881   String#to_s
  0.70      0.022     0.005     0.000     0.016     1425  *Class#new
  0.32      0.002     0.002     0.000     0.000     1222   Kernel#hash
  0.31      0.004     0.002     0.000     0.001      221   ActiveSupport::NumericWithFormat#to_s
```

The big thing that jumps out in Rails 5 is `Regexp#===`

It does make its way into the Rails 4 profiling results, but *way* down:
```
  0.07      0.000     0.000     0.000     0.000       25   Regexp#===
```

I also checked the `CallTreePrinter` to see what was calling it.

In Rails 4, only `String#blank?` appears. In Rails 5, it shows up in:

```
ActiveRecord::LogSubscriber#sql_color
String#sub!
String#blank?
Array#any?
```

Though I'm only looking at the text output for the moment, so I might have misinterpreted it.

I'll try to do some more investigation, but before I get to far into it, I thought I'd ask if anyone had any ideas?

Thanks!

**Comment by sevenseacat** [comment]
`Regexp#===` is a Ruby method, not a Rails one. That's all I have so far >_>

**Comment by shakycode** [comment]
@codeodor Thanks for opening this issue, I thought I was the only one and was banging my head against the wall.

**Comment by rafaelfranca** [comment]
Could you try the master version? I think we already fixed this

**Comment by codeodor** [comment]
@rafaelfranca Thanks for the tip. Updating to master solved the issue.

It's still a little slower in my tests-by-hand, but not like what I was seeing before. If I run some proper benchmarks that indicate a problem, I'll reopen, but I think we're good.

:heart:

**Comment by shakycode** [comment]
@rafaelfranca @codeodor I just pulled latest master and it's good.  Thanks so much!
