### ISSUE TITLE
ActionCable: No documentation on unsubscribing from a channel

### ISSUE THREAD

**Issue by ZeroFries** [rails/rails#24348]
It's unclear from the documentation how a client can unsubscribe to a channel. Calling @unsubscribe calls the unsubscribe method in the Rails channel, but does not seem to actually unsubscribe, nor is there documentation on what should go in the unsubscribe method to achieve it.

**Comment by maclover7** [comment]
By a client, do you mean the JS infrastructure that ships with Action Cable?

**Comment by ZeroFries** [comment]
Yes

**Comment by maclover7** [comment]
Not super familiar with how the JS side of things work, but it looks like calling [`unsubscribe`](https://github.com/rails/rails/blob/master/actioncable/app/assets/javascripts/action_cable/subscription.coffee#L59) on a subscription should do the trick -- cc @javan

**Comment by ZeroFries** [comment]
Calling unsubscribe does indeed call <RailsChannel>#unsubscribe, but does not actually unsubscribe the client from the channel. What should be inside <RailsChannel>#unsubscribe?

**Comment by javan** [comment]
Yeah `Subscription#unsubscribe` should do the trick.

> but does not actually unsubscribe the client from the channel

How are you determining that?

**Comment by ZeroFries** [comment]
When the server broadcasts a message to the channel, the client will still be listening, despite calling `Subscription#unsubscribe`

**Comment by javan** [comment]
I can't reproduce. Tested by closing a client-side subscription and then broadcasting to its channel on the server. No data received by the subscription.

Are you perhaps reloading your assets sometime after unsubscribing? By navigating to another page, for example. If so, that would likely create the subscription again.

**Comment by ZeroFries** [comment]
In server:
```100.times {
      ActionCable.server.broadcast "hello_world", message: "Hello World! #{@a}"
      sleep 1
    }```

In clie

**Comment by shubhamsharma4587** [comment]
have you got a way to unsubscribe a channel?
