### ISSUE TITLE
Scaffold model, destroy link depends on JS. ( Rails5.0.0.beta3 )

### ISSUE THREAD

**Issue by maks-us** [rails/rails#24342]
### Steps to reproduce  
1) create new rails5 application  (Ruby 2.3 and Rails 5.0.0.beta3)
``rails new todo`` and ``bundle install``

2) generate model
``rails g scaffold task name done:boolean``
3) apply migration as production environment
``RAILS_ENV=production bundle exec rails db:migrate``

4) add secret key and start server 
``export SECRET_KEY_BASE='aslkdjf;alskdjf;'``
``RAILS_ENV=production rails s``

5) Open tasks page ``http://localhost:3000/tasks`` As I expected to see page without CSS and JS. 

6) Add some tasks there.

7) The issue:
Destroy button doesn't work because it depends on JS.

(Guidelines for creating a bug report are [available
here](http://guides.rubyonrails.org/contributing_to_ruby_on_rails.html#creating-a-bug-report))

### Expected behavior
I expect to have functional button destroy without JS and CSS

### Actual behavior
"Destroy" link lead to show page without JS. 

### System configuration
**Rails version**: 2.3

**Ruby version**: 5.0.0.beta3

**Comment by maclover7** [comment]
Isn't it part of a normal production deploy workflow to run `rake assets:precompile` when deploying to production?

**Comment by sevenseacat** [comment]
Yes, and these links have relied on JS for many years.

**Comment by rafaelfranca** [comment]
Exactly that. And we don't plan to support these links without javascript by default. If you want progressive enhancement it is your application responsibility to have it.
