### ISSUE TITLE
More precise Filter Parameters pattern matching

### ISSUE THREAD

**Issue by Tensho** [rails/rails#24346]
### General description

`ActionDispatch::Http::ParameterFilter` [compiles](https://github.com/rails/rails/blob/4-2-stable/actionpack/lib/action_dispatch/http/parameter_filter.rb#L21) filters from blocks, regexps and strings ducks. Particularly, the module joins strings to the one global regexp with ONLY pipe and performs alternation this way.
I've found this strange behaviour with [doorkeeper](https://github.com/doorkeeper-gem/doorkeeper) gem help. Doorkeeper's engine [initializes](https://github.com/doorkeeper-gem/doorkeeper/blob/master/lib/doorkeeper/engine.rb#L4) `[:client_secret, :code, :token]` filter parameters and they are compiled further to `/client_secret|code|secret|password/` regexp inside ParameterFilter module (`password` is Rails default). That means application specific parameters, like `postcode`, `codebase`, `tokenization`, etc., will be filtered out.

This issue crosses with exactly the same [question from Stackoverflow](http://stackoverflow.com/questions/28885684/rails-filter-parameters-filtering-too-much).

### Steps to reproduce
```
f = ActionDispatch::Http::ParameterFilter.new(Rails.application.config.filter_parameters)
f.filter(password: 'something',  super_password: 'nothing')
```
### Expected behavior
`{ password: '[FILTERED]', super_password: 'nothing' }`

### Actual behavior
`{ password: '[FILTERED]', super_password: '[FILTERED]' }`

### Testcase
```
begin
  require 'bundler/inline'
rescue LoadError => e
  $stderr.puts 'Bundler version 1.10 or later is required. Please update your Bundler'
  raise e
end

gemfile(true) do
  source 'https://rubygems.org'
  # Activate the gem you are reporting the issue against.
  gem 'actionpack', '4.2.1'
end

require 'action_dispatch/http/parameter_filter'
require 'minitest/autorun'

# Ensure backward compatibility with Minitest 4
Minitest::Test = MiniTest::Unit::TestCase unless defined?(Minitest::Test)

class FilterParameterTest < Minitest::Test
  def test_filter_exact_match
    f = ActionDispatch::Http::ParameterFilter.new([:password])
    assert_equal f.filter(password: 'something',  super_password: 'nothing'), { password: '[FILTERED]', super_password: 'nothing' }
  end
end
```
### System configuration

**Rails version**: 4.2.1
**Ruby version**: 2.2.2

Please give me a feedback according to the report, because it's my first time. If everything described above is reasonable I'd like to provide PR with changes.

**Comment by pixeltrix** [comment]
Typically an application would have a `password` and a `password_confirmation` field - that's why the regexps aren't anchored. If you need to be stricter with your matches you can pass a regexp explicitly. Any attempt to tighten up the defaults might result in a password related field not being filtered so I'm not really leaning towards changing it, sorry.

**Comment by pixeltrix** [comment]
However the API documentation and guides could do with a note that explains clearly that it's a partial match and that you should use anchored regexps for explicit matches if you want to submit a PR - thanks.
