### ISSUE TITLE
Activerecord 5: undefined method `_reflect_on_association' for nil:NilClass

### ISSUE THREAD

**Issue by francesco-loreti** [rails/rails#24367]
### System configuration
**Rails version**: 4.2.6 and 5.0.0.beta3( and master)
**Ruby version**: 2.2.4
**Database**: Postgresql 9.3
**Webserver**: Sinatra
**Gemfile:**
- gem  'sinatra'
- # gem 'activerecord', '< 5.0'
- gem 'activerecord', github: 'rails/rails', branch: 'master'
- gem 'pg'

**Active record 4.2.6**: no problem;
**Last beta version and master version**: I have this error: undefined method `_reflect_on_association' for nil:NilClass

My models are linked to exist tables on remote database and I read a view and write into a table.

`
class User < ActiveRecord::Base
  # id, code, body, date_created
  self.table_name = 'view_users'
  self.primary_key = 'id'
  has_many :histories, :class_name => "UserHistory", :foreign_key => "users_id"
end
`

`
class UserHistory < ActiveRecord::Base
  # id, users_id, body, date_created
  self.table_name = 'giri.users_history'
  belongs_to :user, :class_name => "User", :foreign_key => "users_id"
end
`

If I try:
u = User.first
h = user.histories
I have the error **undefined method `_reflect_on_association' for nil:NilClass** on Activerecord 5 but not on Activerecord 4.2.6

Any suggestions?

**Comment by francesco-loreti** [comment]
Same problem previous Issue #24367

**Comment by rafaelfranca** [comment]
Could you create a reproduction script with this template https://github.com/rails/rails/blob/master/guides/bug_report_templates/active_record_master.rb?

**Comment by francesco-loreti** [comment]
Please explain to me how I should do because I've never done before

**Comment by rafaelfranca** [comment]
Just use that script that I posted above to reproduce the issue and paste the result script here.

**Comment by rafaelfranca** [comment]
Also a full backtrace of the exception that you are having would also help.

**Comment by kuldeepaggarwal** [comment]
@francesco-loreti What is the database name for your configuration?

**Comment by kuldeepaggarwal** [comment]
@francesco-loreti Why is the purpose of using table name as `giri.users_history`?

**Comment by kuldeepaggarwal** [comment]
This [commit](c80487eb) creates problem for above issue, because code never assumed that the table name would contain dot(`.`)

here is the script that describes the failure:

```rb
begin
  require 'bundler/inline'
rescue LoadError => e
  $stderr.puts 'Bundler version 1.10 or later is required. Please update your Bundler'
  raise e
end

gemfile(true) do
  source 'https://rubygems.org'
  gem 'rails', path: '/Users/kuldeepaggarwal/projects/kd-rails'
  gem 'sqlite3'
end

require 'active_record'
require 'minitest/autorun'
require 'logger'

# This connection will do for database-independent bug reports.
ActiveRecord::Base.establish_connection(adapter: 'sqlite3', database: ':memory:')
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :view_users, force: true  do |t|
    t.string :code
    t.text :body
    t.datetime :date_created
  end

  create_table :'giri.users_history', force: true  do |t|
    t.references :user
    t.datetime :date_created
  end
end

class User < ActiveRecord::Base
 # id, code, body, date_created
 self.table_name = 'view_users'
 self.primary_key = 'id'

 has_many :histories, :class_name => "UserHistory", :foreign_key => "users_id"
end

class UserHistory < ActiveRecord::Base
  # id, users_id, body, date_created
  self.table_name = 'giri.users_history'

  belongs_to :user, :class_name => "User", :foreign_key => "users_id"
end


class BugTest < Minitest::Test
  def test_association_stuff
    u = User.create
    h = u.histories
  end
end
```


and here is the backtrace:

```sh

  1) Error:
BugTest#test_association_stuff:
NoMethodError: undefined method `_reflect_on_association' for nil:NilClass
    /Users/kuldeepaggarwal/projects/kd-rails/activerecord/lib/active_record/table_metadata.rb:47:in `associated_table'
    /Users/kuldeepaggarwal/projects/kd-rails/activerecord/lib/active_record/relation/predicate_builder.rb:135:in `associated_predicate_builder'
    /Users/kuldeepaggarwal/projects/kd-rails/activerecord/lib/active_record/relation/predicate_builder.rb:103:in `block in create_binds_for_hash'
    /Users/kuldeepaggarwal/projects/kd-rails/activerecord/lib/active_record/relation/predicate_builder.rb:100:in `each'
    /Users/kuldeepaggarwal/projects/kd-rails/activerecord/lib/active_record/relation/predicate_builder.rb:100:in `create_binds_for_hash'
    /Users/kuldeepaggarwal/projects/kd-rails/activerecord/lib/active_record/relation/predicate_builder.rb:103:in `block in create_binds_for_hash'
    /Users/kuldeepaggarwal/projects/kd-rails/activerecord/lib/active_record/relation/predicate_builder.rb:100:in `each'
    /Users/kuldeepaggarwal/projects/kd-rails/activerecord/lib/active_record/relation/predicate_builder.rb:100:in `create_binds_for_hash'
    /Users/kuldeepaggarwal/projects/kd-rails/activerecord/lib/active_record/relation/predicate_builder.rb:36:in `create_binds'
    /Users/kuldeepaggarwal/projects/kd-rails/activerecord/lib/active_record/relation/where_clause_factory.rb:20:in `build'
    /Users/kuldeepaggarwal/projects/kd-rails/activerecord/lib/active_record/relation/query_methods.rb:626:in `where!'
    /Users/kuldeepaggarwal/projects/kd-rails/activerecord/lib/active_record/relation/query_methods.rb:619:in `where'
    /Users/kuldeepaggarwal/projects/kd-rails/activerecord/lib/active_record/associations/association_scope.rb:67:in `last_chain_scope'
    /Users/kuldeepaggarwal/projects/kd-rails/activerecord/lib/active_record/associations/association_scope.rb:124:in `add_constraints'
    /Users/kuldeepaggarwal/projects/kd-rails/activerecord/lib/active_record/associations/association_scope.rb:28:in `scope'
    /Users/kuldeepaggarwal/projects/kd-rails/activerecord/lib/active_record/associations/association_scope.rb:5:in `scope'
    /Users/kuldeepaggarwal/projects/kd-rails/activerecord/lib/active_record/associations/association.rb:97:in `association_scope'
    /Users/kuldeepaggarwal/projects/kd-rails/activerecord/lib/active_record/associations/association.rb:86:in `scope'
    /Users/kuldeepaggarwal/projects/kd-rails/activerecord/lib/active_record/associations/collection_association.rb:447:in `scope'
    /Users/kuldeepaggarwal/projects/kd-rails/activerecord/lib/active_record/associations/collection_proxy.rb:37:in `initialize'
    /Users/kuldeepaggarwal/projects/kd-rails/activerecord/lib/active_record/relation/delegation.rb:101:in `new'
    /Users/kuldeepaggarwal/projects/kd-rails/activerecord/lib/active_record/relation/delegation.rb:101:in `create'
    /Users/kuldeepaggarwal/projects/kd-rails/activerecord/lib/active_record/associations/collection_association.rb:47:in `reader'
    /Users/kuldeepaggarwal/projects/kd-rails/activerecord/lib/active_record/associations/builder/association.rb:111:in `histories'
    #24367.rb:54:in `test_association_stuff'

1 runs, 0 assertions, 0 failures, 1 errors, 0 skips
```

**Comment by francesco-loreti** [comment]
Sorry but I think the solution is not good for postgresql. The point divide the schema name with the table name. In postgresql the sche is always present but when the tables are into the public standard schema is not necessary explain it into the request. For example if I write "select * from public.users" or "select * from users" I receive same result. But if I create a different schema for example in my case "giri" and I put in restricted tables o views or procedure, in this case I need to explain the name of restricted area with "giri.view_users" or other tables. So if this is not provided in the rails 5 or into future version it's a problem because schema it's a structural function into postgresql. You can read about schema on http://www.postgresql.org/docs/current/static/ddl-schemas.html

**Comment by djvs** [comment]
+1 for what francesco said, current solution is unacceptable for PostgreSQL -  see https://github.com/influitive/apartment/issues/300#issuecomment-193303974

**Comment by sgrif** [comment]
Maybe look at what the code is doing on master before chiming in on an issue closed over a month ago? https://github.com/rails/rails/commit/714ab8cb5976587470c8487720094c1efb2ba9a2
https://github.com/rails/rails/commit/7fd72fa4b779c812c98cfb748287554ba5090f6b
