### ISSUE TITLE
fields_for method printing unexpected tag when using nested form

### ISSUE THREAD

**Issue by rplaurindo** [rails/rails#24378]
The expected behavior is a renderization partial that contains

``` erb
<%= form_parent.fields_for :juice_ingredients, @juice_ingredient do |juice_ingredient_f| %>
  <div class="field new">
    <div class="inline">
      <%= juice_ingredient_f.label "Ingredient" %>
      <%= juice_ingredient_f.select(:ingredient_id, options_for_select( ingredients.map{ |s| [s.name, s.id] }, selected: juice_ingredient_f.object.try(:ingredient_id))) %>
    </div>

    <div class="inline">
      <%= juice_ingredient_f.label "Amount" %>
      <%= juice_ingredient_f.text_field :amount %>
    </div>

    <div class="inline">
      <%= link_for "Remove", juice_ingredient_f, class: "remove-field" %>
    </div>
  </div>
<% end %>
```

**Obs.**: `form_parent` is a helper method.

``` ruby
def form_parent
  @@form_parent
end

def store_form object
  @@form_parent = object
end
helper_method :form_parent, :store_form
```

But Rails render

``` html
 <div class="inline">
    <label for="juice_juice_ingredients_attributes_1_Ingredient">Ingredient</label>
    <select name="juice[juice_ingredients_attributes][0][ingredient_id]" id="juice_juice_ingredients_attributes_1_ingredient_id">
        <option value="1">Water</option>
        <option value="2">Sugar</option>
    </select>
</div>

<div class="inline">
    <label for="juice_juice_ingredients_attributes_1_Amount">Amount</label>
    <input name="juice[juice_ingredients_attributes][1][amount]" id="juice_juice_ingredients_attributes_1_amount" type="text">
</div>

<div class="inline">
    <a class="remove-field" href="javascript:void(0)">Remove</a>
</div>
</div> </div>
```

With an unexpected `</div> </div>` after the last tag.

**Rails version:** 4.2.6:

**Ruby version:** 2.2.3p173 (2015-08-18 revision 51636) [x86_64-linux]:

**Comment by sgrif** [comment]
Please provide a minimal Rails app which demonstrates the issue.

**Comment by tomash** [comment]
What is `link_for`? It's not a Rails helper.

**Comment by rplaurindo** [comment]
@tomash ```link_for``` is a helper method. I going to update the post providing the minimal Rails app now.

**Comment by rplaurindo** [comment]
@sgrif that app is to you do make fork it?

**Comment by rplaurindo** [comment]
@sgrif i did a little [app](https://github.com/rplaurindo/nested_attributes_example) to example. Just to clone, to run ```bundle``` and after ```rails s```. Has no database.

**Comment by al2o3cr** [comment]
@rplaurindo I was able to reproduce the issue. It appears that whatever is between the last ERB tag inside `fields_for` and the end of the `fields_for` block winds up repeated & escaped.

However, I could make the bug disappear by removing the caching of the `FormBuilder` object in `form_parent`. I could also make the app fail completely by restarting the Rails server and then clicking "Add Ingredient", or by editing `app/controllers/ApplicationController` to trigger a reload of that class.

I'm going to continue chasing this out of curiosity, but I don't believe that reusing objects from one request in another is a supported use case - it breaches a number of key assumptions about the lifecycle of objects in a Rails request.

**Comment by rplaurindo** [comment]
@al2o3cr you make me think. My implementation to dinamically render parts of a form (because of nested attributes in this case) was wrong. The solutions that you show to fix bug and the information about the object lifecycle show me that to use a static variable to persist the form object between requests isn't safe. I will change the implementation. I will create a different files to new and edit case. The file of the new case will contain only ```fields_for```, without ```form_parent```helper.

```erb
<%= fields_for 'juice[juice_ingredients_attributes][]', @juice_ingredient do |juice_ingredient_f| %>
      #...
```
