### ISSUE TITLE
Valid rake command line arguments reported as invalid on running 'test' task

### ISSUE THREAD

**Issue by VladRassokhin** [rails/rails#24372]
### Steps to reproduce
```bash
rbenv shell 2.3.0
gem install rails -v '5.0.0.beta3'
rails new test-a
cd test-a
echo "gem 'therubyracer', platforms: :ruby" >> Gemfile
bundle install && bundle update
which rake
bundle exec which rake
#Next two lines works fine
rake --rakefile "`pwd`/Rakefile" about
rake --rakefile "`pwd`/Rakefile" --tasks
# Next two lines would fail with output: "invalid option: --rakefile"
rake --rakefile "`pwd`/Rakefile" test
bundle exec rake --rakefile "`pwd`/Rakefile" test
```
### Expected behavior
It should work ;)
Rake arguments should be passed to rake.

### Actual behavior
Got exit code 1 and "invalid option: --rakefile" output

After some 'debugging' I've next stacktrace:
```text
invalid option: --rakefile
/home/vlad/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/railties-5.0.0.beta3/lib/rails/test_unit/minitest_plugin.rb:57:in `plugin_rails_options'
/home/vlad/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/minitest-5.8.4/lib/minitest.rb:190:in `block (2 levels) in process_args'
/home/vlad/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/minitest-5.8.4/lib/minitest.rb:188:in `each'
/home/vlad/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/minitest-5.8.4/lib/minitest.rb:188:in `block in process_args'
/home/vlad/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/minitest-5.8.4/lib/minitest.rb:162:in `new'
/home/vlad/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/minitest-5.8.4/lib/minitest.rb:162:in `process_args'
/home/vlad/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/minitest-5.8.4/lib/minitest.rb:116:in `run'
/home/vlad/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/railties-5.0.0.beta3/lib/rails/test_unit/minitest_plugin.rb:64:in `rake_run'
/home/vlad/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/railties-5.0.0.beta3/lib/rails/test_unit/testing.rake:15:in `block in <top (required)>'
/home/vlad/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/rake-11.1.2/lib/rake/task.rb:248:in `block in execute'
/home/vlad/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/rake-11.1.2/lib/rake/task.rb:243:in `each'
/home/vlad/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/rake-11.1.2/lib/rake/task.rb:243:in `execute'
```
It seems test framework tries to parse all rake cli arguments

### System configuration
**Rails version**:
5.0.0.beta3

**Ruby version**:
2.3.0 by rbenv

**Comment by VladRassokhin** [comment]
@maclover7 
Yes, it works fine with rails 4.2.6
```log
$ bundle exec rake --rakefile "`pwd`/Rakefile" test
$ bundle exec rake --rakefile "`pwd`/Rakefile" --trace test
** Invoke test (first_time)
** Execute test
** Invoke test:run (first_time)
** Execute test:run
```
[Here's](https://gist.github.com/VladRassokhin/0a0e59596456f360a75a35d83a71622f) Gemfile and Gemfile.lock if you need them.

**Comment by mchristen** [comment]
I am also experiencing this behavior, but on 4.2.6 with ruby 2.2.3p173. I also confirmed that this happens is present in 4.2.5.1 as well.

Any other rake task I've tried but 'test' seems to work just fine.

```
    rails (4.2.6)
      actionmailer (= 4.2.6)
      actionpack (= 4.2.6)
      actionview (= 4.2.6)
      activejob (= 4.2.6)
      activemodel (= 4.2.6)
      activerecord (= 4.2.6)
      activesupport (= 4.2.6)
      bundler (>= 1.3.0, < 2.0)
      railties (= 4.2.6)
      sprockets-rails
```

```
$ bundle exec rake -t test
** Invoke test (first_time)
** Execute test
** Invoke test:run (first_time)
** Execute test:run

invalid option: -t

minitest options:
    -h, --help                       Display this help.
    -s, --seed SEED                  Sets random seed. Also via env. Eg: SEED=n rake
    -v, --verbose                    Verbose. Show progress processing files.
    -n, --name PATTERN               Filter run on /regexp/ or string.


```

**Comment by maclover7** [comment]
Can you try to do a git bisect to find where the erroneous behavior was introduced?

**Comment by kaspth** [comment]
This is because of the new test runner in Rails 5. `rake test` is basically just a shim for that. As you've noticed we just pass every option on to our internal Minitest plugin.

What's the point of the `--rakefile` in your example? To enrich the default test task with more behavior?

Not sure what to do about this. @senny, @arthurnn any of you have any ideas?

**Comment by mchristen** [comment]
It appears that this behavior has existed since day one on this project, it is only a few months old.

I was able to re-produce the problem with the following

```
rails -v #Rails 4.2.6
rails new test_fail
cd test_fail/
bundle exec rake -t test #works OK
bundle exec rake -t test:models  #works OK
bundle exec rake -t test:controllers  #works OK
rails g controller fake
bundle exec rake -t test:controllers #fails now that an actual test file is present

```

**Comment by kaspth** [comment]
@mchristen are you sure `-t` is a supported Rake option? Doesn't it confuse with `-T` (list all tasks)?

**Comment by mchristen** [comment]
Yes, it is the 'trace' option.

```    -t, --trace=[OUT]                Turn on invoke/execute tracing, enable full backtrace. OUT can be stderr (default) or stdout.```

**Comment by kaspth** [comment]
@VladRassokhin seems to work on master for me. Can you verify in your app?

**Comment by mchristen** [comment]
Should I open another Issue for this since it happens on 4.2.X?

**Comment by mchristen** [comment]
I just created a new rails app using the current rails master and this problem still exists. Note that the '-t' options works fine for the db:migrate task, but not for the test:controllers task

```
$ bundle exec rake -t test:controllers
** Invoke test:controllers (first_time)
** Invoke test:prepare (first_time)
** Execute test:prepare
** Execute test:controllers
invalid option: -t

[matt@crusty-debian:~/work/test_fail]
$ bundle exec rake -t db:migrate
** Invoke db:migrate (first_time)
** Invoke environment (first_time)
** Execute environment
** Invoke db:load_config (first_time)
** Execute db:load_config
** Execute db:migrate
** Invoke db:_dump (first_time)
** Execute db:_dump
** Invoke db:schema:dump (first_time)
** Invoke environment
** Invoke db:load_config
** Execute db:schema:dump
```

**Comment by VladRassokhin** [comment]
My app is just simple `rails new test-x` and there nothing special in it.
It seems there's something else here since it work for someone and works not for another. Maybe there's some difference in our RUBYLIB paths or other hidden parameters?

**Comment by VladRassokhin** [comment]
Problem is still there:
```log
vlad@unit-421 /tmp/tmp.e4OzBfz5Uv/test-x $ bundle exec rake --rakefile Rakefile --trace test
** Invoke test (first_time)
** Execute test
invalid option: --rakefile
```
[Gemfile.lock and `bundle install` output](https://gist.github.com/VladRassokhin/e6d078c15d728c6f7d0eb659ab9861f7).

**Comment by VladRassokhin** [comment]
@kaspth any updates on issue? It still reproduces (see above)

**Comment by kaspth** [comment]
@VladRassokhin yep, I see it now. Got led astray by other comments and didn't check the `test` command. Doing so, I can reproduce this.

Thanks for your patience! :heart:

**Comment by jeremy** [comment]
This needn't block 5.0.0 release candidate, though we would like to address it for final release. Removing milestone.

**Comment by VladRassokhin** [comment]
Verified. It's fixed. Thanks! :+1:

**Comment by sebbean** [comment]
@VladRassokhin fixed in which version? having issue in rails 4.2.7

**Comment by sebbean** [comment]
this is stopping my deploy to heroku (just upgraded to 4.2.7) having no luck getting rake -P to not exit successfully

**Comment by sebbean** [comment]
Just blew away a day on it. Ended up just modifying the heroku buildpack to ignore the error status code for `bundle exec rake -P --trace` https://github.com/heroku/heroku-buildpack-ruby/compare/master...sebbean:sebbean-patch-1

**Comment by sebbean** [comment]
My Gemfile: https://gist.github.com/sebbean/b96e964622b7b268bab23259e279d8cd
Gemfile.lock: https://gist.github.com/sebbean/3fcbae6d599b6f1d70549b924afce9d0
for reference.

**Comment by kaspth** [comment]
@sebbean this issue was only in the Rails 5 beta. The thing you're seeing in 4.2.7 is not caused by this. Though I hope you figure your issue out ❤️

**Comment by sebbean** [comment]
@kaspth seems like this thread confirms it is happening in 4.2.x
from this comment on:
https://github.com/rails/rails/issues/24372#issuecomment-204038417

You're saying it is an issue just not *this* specific issue?

**Comment by sebbean** [comment]
@kaspth actually to clarify I'm getting the problem when calling `rake -P` but it occurs with any many arguments I send to `rake`

**Comment by kaspth** [comment]
I don't think I fully understand your issue. Seems to me `bundle exec rake -P --trace` failing is a Rake and not one with Rails 😊

**Comment by sebbean** [comment]
came here by searching the errors. looks to be the same exact issue. 
lemme compare the stack traces
