### ISSUE TITLE
Nested model validation errors has useless format in json

### ISSUE THREAD

**Issue by justedd** [rails/rails#24380]
Hi everyone.
I have class Order, that can content Entries. And each Entry can be complex type, and consist from another entries(associated as Members).
```
class Order < ActiveRecord::Base
  accepts_nested_attributes_for :entries
end

class Entry < ActiveRecord::Base
  accepts_nested_attributes_for :members, allow_destroy: true
end
```
In form i have rails generated fields in form, using(/like a) fields_for, like this
```
<input autocomplete="off" class="string required form-control" id="order_entries_attributes_1459329286687_members_attributes_1459329286739_title" name="order[entries_attributes][1459329286687][members_attributes][1459329286739][title]" placeholder="title" type="text">
```
So, i submit a form of order, for example with 2 entries, and 15 members with some validation errors ( 2 members without title ) and it passes to standard controller
```
class OrdersController < ApplicationController
  def update
    if @order.update(order_params)
      render json: @order
    else
      render json: @order.errors, status: :unprocessable_entity
    end
  end
end
```
And it returns me this
```
{"entries.members.title":["cant be blank"]}
```
Problem is that i cant find which entry and which member in it, has a validation error, and that's why i cant for example highlight this field. Moreover it merges similar errors. And this is problem.

On submit i pass unique index(in name attributes), and rails correctly use it for creating nested models, it would be nice if error response contained this index.

In update, I can create custom error response, and back ID for existing entry/member with error, but it still not solves problem with 50 new nested Entries, and 2 validation problems, i just cant identify it in response.

Is there any other way to return nice indexed errors from server, and use rails as api for json without any pain?

Rails 4.2.6

**Comment by morgoth** [comment]
@justedd It's already improved in Rails 5 - you can take a look at PR https://github.com/rails/rails/pull/19686
