### ISSUE TITLE
Rails 5 migration/schema dump issue/question with postgres and OracleEnhancedAdaptor

### ISSUE THREAD

**Issue by landesjm** [rails/rails#24384]
I'm using Rails5.0.0.beta3 with multiple database connections, one to postgres and one to Oracle. When I execute rake db:migrate or rake db:schema:dump, an error is generated which appears that the OEA is asking the Postgres adaptor for a listing of it's materialized views. I'm not sure if this is a AR issue or an OEA issue or maybe both? 

$ rake db:schema:dump
rake aborted!
NoMethodError: undefined method `materialized_views' for #<ActiveRecord::ConnectionAdapters::PostgreSQLAdapter:0x007ff33b5a9110>
Dev/projects/Storeburst/vendor/ruby/2.3.0/bundler/gems/oracle-enhanced-3f31fcc86f06/lib/active_record/connection_adapters/oracle_enhanced/schema_dumper.rb:30:in `tables'
Dev/projects/Storeburst/vendor/ruby/2.3.0/gems/activerecord-5.0.0.beta3/lib/active_record/schema_dumper.rb:37:in `dump'
Dev/projects/Storeburst/vendor/ruby/2.3.0/gems/activerecord-5.0.0.beta3/lib/active_record/schema_dumper.rb:21:in `dump'
Dev/projects/Storeburst/vendor/ruby/2.3.0/gems/activerecord-5.0.0.beta3/lib/active_record/railties/databases.rake:253:in `block (4 levels) in <top (required)>'
Dev/projects/Storeburst/vendor/ruby/2.3.0/gems/activerecord-5.0.0.beta3/lib/active_record/railties/databases.rake:252:in `open'
Dev/projects/Storeburst/vendor/ruby/2.3.0/gems/activerecord-5.0.0.beta3/lib/active_record/railties/databases.rake:252:in `block (3 levels) in <top (required)>'
.rvm/gems/ruby-2.3.0/bin/ruby_executable_hooks:15:in `eval'
.rvm/gems/ruby-2.3.0/bin/ruby_executable_hooks:15:in `<main>'
Tasks: TOP => db:schema:dump

If I comment out the OEA gem in the Gemfile, the db:migrate and db:schema:dump work as expected. The OEA gem is from the rails5 branch - 
      gem 'activerecord-oracle_enhanced-adapter', :git => 'https://github.com/rsim/oracle-enhanced.git', :branch => 'rails5'

**Comment by rafaelfranca** [comment]
It seems to be an activerecord-oracle_enhanced-adapter's issue
