### ISSUE TITLE
(Sometimes) Crash in query_methods

### ISSUE THREAD

**Issue by fero46** [rails/rails#24394]
Hi,

I've build an Importer to import Product Data from various sources like Zanox, Affiliate, CJ Affiliate etc. Now the problem is, after parsing the data sometimes( yes sometimes not everytime) its crash. I am not sure how to reproduce. Maybe you have seen this error before, so i put my CrashReport from 
Terminal an Ruby Crash Report:

**Rails version**: 4.2.6
**Ruby version**:  ruby 2.2.3p173 (2015-08-18 revision 51636) [x86_64-darwin14]

[active_record_crash.txt](https://github.com/rails/rails/files/200076/active_record_crash.txt)
[ruby_2016-04-01-185813_MacBook-Pro.txt](https://github.com/rails/rails/files/200067/ruby_2016-04-01-185813_MacBook-Pro.txt)

**Comment by rafaelfranca** [comment]
This is a bug in Ruby. Rails doesn't causes segfault.
