### ISSUE TITLE
Unable to use a dot at the base of the route path

### ISSUE THREAD

**Issue by volkanunsal** [rails/rails#24395]
### Steps to reproduce

Add this route at the top of your routes.rb

```ruby
get ':my_root', to: 'pages#home', my_root: /.+/
```

(Make sure there is a Pages#home action.)

Start your server
Visit the following url: `localhost:3000/.well-known`

### Expected behavior

The app should render the page at pages#home.

### Actual behavior

You get a 404 response. 

### System configuration
**Rails version**: 4.2.5

**Ruby version**: 2.2.2

**Comment by maclover7** [comment]
I don't think `my_root` is an accepted option for routing configuration...?

**Comment by volkanunsal** [comment]
@maclover7 I thought that was a shortcut for a constraint. I saw it in the doc. But anyway you can see the same effect with the `constraint` option.

```ruby
get ':my_root', to: 'pages#home', constraints: {my_root: /.+/}
```

**Comment by maclover7** [comment]
Can you point me to where you see `my_root` mentioned in the documentation? A search on Github is showing that it isn't listed anywhere in the [`rails/rails` repo](https://github.com/rails/rails/search?utf8=%E2%9C%93&q=my_root).

**Comment by volkanunsal** [comment]
My intention was to use `: my_root ` as a dynamic route segment. It's not a Rails convention.

**Comment by volkanunsal** [comment]
Also, that's not the main issue. The issue is that route constraints does not work with a dot at the base of the path.
