### ISSUE TITLE
It should be the type of time argument that decides the generated sql

### ISSUE THREAD

**Issue by LcpMarvel** [rails/rails#24402]
### Steps to reproduce

rails g model post
```ruby
create_table :posts do |t|
  t.date :created_at_date

  t.timestamps null: false
end
```

 `date` vs `datetime`
```ruby
Time.zone = "Beijing"
beginning_of_month = Time.zone.now.beginning_of_month

# date
Post.where("created_at_date >= ?", beginning_of_month.to_date).to_sql
# "SELECT \"posts\".* FROM \"posts\" WHERE (created_at_date >= '2016-04-01')"

# datetime
Post.where("created_at_date >= ?", beginning_of_month).to_sql
#"SELECT \"posts\".* FROM \"posts\" WHERE (created_at_date >= '2016-03-31 16:00:00.000000')"
```

### Expected behavior

```ruby
# the type of argument is datetime
Post.where("created_at_date >= ?", beginning_of_month).to_sql
```

I think the result should be equal to `SELECT \"posts\".* FROM \"posts\" WHERE (created_at_date >= '2016-04-01')` because the type of `created_at_date` is `date`
### Actual behavior

```ruby
`Post.where("created_at_date >= ?", beginning_of_month).to_sql`
# SELECT \"posts\".* FROM \"posts\" WHERE (created_at_date >= '2016-03-31 16:00:00.000000')
```

### System configuration
**Rails version**:
`Rails 4.2.5.1`
**Ruby version**:
`ruby 2.2.4p230`

**Comment by maclover7** [comment]
Can you create an executable test script using one of the templates [here](https://github.com/rails/rails/tree/master/guides/bug_report_templates), that would demonstrate the problem you are seeing?

**Comment by sevaorlov** [comment]
I've created an executable test. https://gist.github.com/sevaorlov/21b2c4d634e57f9006db26c4f579abee
@maclover7, do you think rails needs to convert users input to date?

**Comment by sgrif** [comment]
We cannot ever under the type of the column when you are passing a SQL string. You need to ensure the value is of the correct type in these cases.
