### ISSUE TITLE
Render JSON doesn't work with ActionController::API ( Rails 5.0.0.beta )

### ISSUE THREAD

**Issue by nusdon** [rails/rails#24407]
### Steps to reproduce

Example:

```
class RootController < ActionController::API
  def index
    render :json => {success: true}, :status => 200
  end
end
```

Get an error:

`ActionView::MissingTemplate - Missing template root/index, application/index with {:locale=>[:en], :formats=>[:html, :text, :js, :css, :ics, :csv, :vcf, :png, :jpeg, :gif, :bmp, :tiff, :svg, :mpeg, :xml, :rss, :atom, :yaml, :multipart_form, :url_encoded_form, :json, :pdf, :zip, :gzip], :variants=>[], :handlers=>[:raw, :erb, :html, :builder, :ruby, :jbuilder]}. Searched in:`

### If to inherit from: ActionController::Base

```
class RootController < ActionController::Base
  def index
    render :json => {success: true}, :status => 200
  end
end
```
Get response:

```
{
  "success": true
}
```

### System configuration
**Rails version**:
5.0.0.beta
**Ruby version**:
ruby:2.3

Does anyone have any idea?

**Comment by maclover7** [comment]
Can you create an executable test script using one of the templates [here](https://github.com/rails/rails/tree/master/guides/bug_report_templates), that would demonstrate the problem you are seeing?

**Comment by nusdon** [comment]
This issue related to gem 'jbuilder' I added. Thanks for support.

**Comment by rlugge** [comment]
@nusdon any chance you could provide more details, since I just ran into the exact same issue?

**Comment by rlugge** [comment]
For those -- like me -- trying to track this issue down, the following link may be of use.

https://github.com/rails/jbuilder/issues/317
