### ISSUE TITLE
Rails 5 beta 3: Cannot read property 'subscriptions' of undefined

### ISSUE THREAD

**Issue by SylarRuby** [rails/rails#24418]
Ruby 2.2.3

`rails g channel foo_bar speak`

Enabled cable in router, then restart server. Now got:

>Cannot read property 'subscriptions' of undefined

which point to:

```
(function() {
  App.foo_bar = App.cable.subscriptions.create("FooBarChannel", {
    connected: function() {},
    disconnected: function() {},
    received: function(data) {},
    request: function() {
      return this.perform('speak');
    }
  });

}).call(this);
```

And:

>Uncaught SyntaxError: Failed to construct

    this.webSocket = new WebSocket(this.consumer.url);

**Comment by jeremy** [comment]
Looks like the channel generator doesn't generate `app/assets/javascripts/cable.js` for you if it doesn't exist. The app generator does.

Check out https://github.com/rails/rails/blob/master/railties/lib/rails/generators/rails/app/templates/app/assets/javascripts/cable.js

**Comment by SylarRuby** [comment]
@jeremy it does:

```
// Action Cable provides the framework to deal with WebSockets in Rails.
// You can generate new channels where WebSocket features live using the rails generate channel command.
//
//= require action_cable
//= require_self
//= require_tree ./channels

(function() {
  this.App || (this.App = {});

  App.cable = ActionCable.createConsumer();

}).call(this);
```

**Comment by maclover7** [comment]
Can you please provide a sample application that replicates the error you are seeing?

**Comment by SylarRuby** [comment]
Well ive only installed rails 5 beta 3. Nothing fancy going on

**Comment by jeremy** [comment]
> Cannot read property 'subscriptions' of undefined

App.cable is undefined, so your cable.js hasn't loaded. Take a look in web inspector to track it down!

**Comment by SylarRuby** [comment]
@jeremy What is the load order or cable.js?

<img width="605" alt="screen shot 2016-04-05 at 05 18 18" src="https://cloud.githubusercontent.com/assets/7381195/14271171/f3287274-faed-11e5-8713-e918cf3f5f93.png">

**Comment by vipulnsward** [comment]
Hi @SylarRuby it would be helpful if you post the order of requires, etc. and where App.cable is being used(is this App.cable being called from components?).

I see you are doing 
```
//= require components
```
before 
```
//= require cable
```
Its best to load all libraries/dependencies before loading components. 

If that's not the issue, then it will need more debugging info, like and example App as mentioned before.

**Comment by SylarRuby** [comment]
@vipulnsward I dont believe that's an issue. My assumption is that `App.cable = ActionCable.createConsumer(');` should work without setting the `/cable` path. No? It works when I set the path:

    App.cable = ActionCable.createConsumer('ws://localhost:3000/cable');

**Comment by prathamesh-sonpatki** [comment]
@SylarRuby Do you have action cable meta tag rendered into some layout like

```
<%= action_cable_meta_tag %>
```

Because it's used to connect to Action Cable without needing to specify the URL - https://github.com/rails/rails/blob/master/actioncable/lib/action_cable/helpers/action_cable_helper.rb#L13-L14

I verified that it is present for newly generated apps from Rails 5.0.0.beta3 and master.

**Comment by SylarRuby** [comment]
@prathamesh-sonpatki 

>I verified that it is present for newly generated apps from Rails 5.0.0.beta3 and master.

No. I have just generated a new app and nothing is there. When I added the meta tag I still get the error. I have to specify the url for the app to work.

**Comment by prathamesh-sonpatki** [comment]
Pushed the sample Rails 5.0.0.beta3 app here - https://github.com/prathamesh-sonpatki/action_cable_demo_app

The `action_cable_meta_tag` is present by default - https://github.com/prathamesh-sonpatki/action_cable_demo_app/blob/master/app/views/layouts/application.html.erb#L6

**Comment by prathamesh-sonpatki** [comment]
> When I added the meta tag I still get the error. I have to specify the url for the app to work.

Just to make sure :smile: are you using same layout where this tag is added?

**Comment by SylarRuby** [comment]
It was added to application.html.erb. There?

**Comment by prathamesh-sonpatki** [comment]
Yes. By default the `action_cable_meta_tag` is present in `application.html.erb`. If you are using that layout then the page source should contain the meta tag as follows - 

![actioncablejsapp 2016-04-05 17-30-34](https://cloud.githubusercontent.com/assets/621238/14281020/2a39beec-fb54-11e5-9ae6-499656f7cf6f.jpg)

**Comment by SylarRuby** [comment]
I MAY have overwritten it when installing foundation lol.

**Comment by vipulnsward** [comment]
:smile:  Thanks for confirming.

**Comment by SylarRuby** [comment]
LOL All green lights. Damn you foundation!
