### ISSUE TITLE
Possible bug with fields_for in combination with multipart forms

### ISSUE THREAD

**Issue by koenpunt** [rails/rails#24417]
I've ran into a problem with a form not rendering correctly after submitting with validation validation errors.

While setting up a sample application, I couldn't demonstrate my exact issue, but found something else.

In my real-world setup I was using Devise, with a linked resource (`has_one`) being created on sign up.
At the time I'd added a file field to this linked resource as part of the `fields_for` block, form redisplays were omitting the fields inside the `fields_for` block.

In my [sample application](https://still-reaches-10781.herokuapp.com/users) there a 2 options for adding users. One with a linked restaurant and one with a linked restaurant with a file field.

When you go to [the first](https://still-reaches-10781.herokuapp.com/users/new), and you submit without entering anything, you will see a validation messages for both the users email and the name of the restaurant. When you enter an invalid value for email, the same happens. Which is all good.

Now when you go to [the second](https://still-reaches-10781.herokuapp.com/users/new?with_file=1), and you submit without entering anything, you will get an error message for missing params. This probably has to do with the fact that the form is set to multipart when a file field is added, but it is inconsistent nonetheless. And also, when you enter an invalid value for email, the form redisplays, but with the fields for the restaurant missing.

**Edit:** I've managed to set-up a test visualizing the difference between regular and multipart requests:
https://github.com/koenpunt/nested-form-file-field/blob/master/test/integration/create_user_test.rb

---

Source of this sample application is here:
https://github.com/koenpunt/nested-form-file-field

**Comment by maclover7** [comment]
Can you extract that integration test and create an executable test script using one of the templates [here](https://github.com/rails/rails/tree/master/guides/bug_report_templates), that would demonstrate the problem you are seeing?

**Comment by koenpunt** [comment]
@maclover7 creating a self contained test was harder than I expected. But I got it now, and can be found here: https://github.com/koenpunt/nested-form-file-field/blob/master/selfcontained.rb

It can be run with an extra argument `rebuild`, to "build" the association again in the create method, which you will see will result in quite a different outcome.

So, 

```
$ ruby ./selfcontained.rb
```

And

````
$ ruby ./selfcontained.rb rebuild
````

**Comment by koenpunt** [comment]
Some further investigation made me realize that this probably has to with how Rack processes multipart requests, as it discards empty fields..

**Comment by vipulnsward** [comment]
@koenpunt hope its not https://github.com/rack/rack/issues/761 ?
https://github.com/rack/rack/pull/1009 was fixed. Can you try running this against rack master?

**Comment by koenpunt** [comment]
Haha, oh well I was just about to post about that PR, because rack master works just fine indeed!

**Comment by vipulnsward** [comment]
Thanks, going to close in favour of https://github.com/rails/rails/issues/23438
