### ISSUE TITLE
Puma worker config breaks spring reloading for helpers

### ISSUE THREAD

**Issue by jeroenvisser101** [rails/rails#24414]
### Steps to reproduce
1. `rails new <app name>`
2. `rails g controller Home index`
3. [Edit `config/puma.rb` to use workers](https://github.com/jeroenvisser101/rails-puma-workers-helpers-spring/commit/768eb082070c7399a0992af6da4eaf3396ce06f1), without that, the bug doesn't occur
4. Create a dummy helper and use it in the view
5. `rails server`
6. Edit the helper
7. Refresh

[A minimal example can be found here](https://github.com/jeroenvisser101/rails-puma-workers-helpers-spring)

### Expected behavior
The result should change because Spring should reload the app.

### Actual behavior
Spring doesn't reload the app, old version is executed instead.

### System configuration
**Rails version**: 5.0.0.beta3
**Ruby version**: 2.3.0-p0
**Puma version**: 3.2.0

**Comment by rafaelfranca** [comment]
Spring is expecting that you application have only one process so I'm not sure if this is a bug or a limitation of spring. Either way I'm moving this issue to the spring repository.

**Comment by rafaelfranca** [comment]
This issue was moved to rails/spring#477
