### ISSUE TITLE
Use coffeescript compiler to convert ActionCable .coffee files to .js when javascript_engine = :js set

### ISSUE THREAD

**Issue by sanford** [rails/rails#24411]
### Steps to reproduce

in config/application.rb add:

`config.generators.javascript_engine = :js
`

Then run:

`rails generate channel Chat speak
`

### Expected behavior

`app/assets/javascripts/channels/chat.js
`

### Actual behavior

`app/assets/javascripts/channels/chat.coffee
`

### Suggested fix

If config.generators.javascript_engine = :js is set, feed the output of the channel generator into the coffeescript compiler and write the resulting javascript into a .js file (don't write out the intermediate .coffee file).

Benefit?  Lets the core team keep writing generators in .coffee but still lets developers use only javascript if they set it as a preference.

### Why?

Rails always gave developers the option to generate plain javascript before.  Is there a good reason to start forcing coffeescript-only on generator users today?

**Comment by maclover7** [comment]
Dup of #24245.
