### ISSUE TITLE
Rails5 beta3 using ActionDispatch::Http::UploadedFile in tests

### ISSUE THREAD

**Issue by mfazekas** [rails/rails#24432]
### Steps to reproduce

Some of our test uses ActionDispatch::Http::UploadedFile for upload. In rails 5 we get:

```
 NoMethodError:
   undefined method `path' for "#<ActionDispatch::Http::UploadedFile:0x007fdbf3b06e28>":String
```

It might have been an undocumented feature of rails to allow passing of ActionDispatch::Http::UploadedFile in testcases (i think only fixture_file_upload is documented). It was implemented in this PR in 2012:
https://github.com/rails/rails/pull/6805
I assume it was dropped in rails 5 with this change: https://github.com/rails/rails/commit/c546a2b045600b6d700140adf2a4df666d6e08ce

fixture_file_upload should be still working fine.
### Expected behavior

Deprecation warning, or at least mention in migration/change notes
### Actual behavior

```
     NoMethodError:
       undefined method `path' for "#<ActionDispatch::Http::UploadedFile:0x007fdbf3b06e28>":String
```
### System configuration

**Rails version**:5.0.0.beta3
**Ruby version**:2.3.0

**Comment by mfazekas** [comment]
I guess not end of the world, not sure if it warrants a note in http://edgeguides.rubyonrails.org/upgrading_ruby_on_rails.html or just in https://github.com/rails/rails/blob/master/guides/source/5_0_release_notes.md?

**Comment by vipulnsward** [comment]
@tenderlove can you confirm if we need to continue supporting it?

**Comment by rushingfitness** [comment]
Running into a similar situation. But also with `.read` as well as `path`. Is there a solution to this?

**Comment by mfazekas** [comment]
@rushingfitness i think for use we're just using `fixture_file_upload` and that works with rails5 just fine.
