### ISSUE TITLE
Rails.backtrace_cleaner.add_silencer doesn't work, but filters do

### ISSUE THREAD

**Issue by k2m30** [rails/rails#24434]
### Steps to reproduce

in initializers/backtrace_silencers.rb

`Rails.backtrace_cleaner.add_silencer { |line| line =~ /lib/ }`

and restart the server
### Expected behavior

I expect to see in log file only

`ActionController::RoutingError (No route matches [GET] "/admin/roles")`

 but
### Actual behaviour

```
  ActionController::RoutingError (No route matches [GET] "/admin/roles"):
  actionpack (4.1.8) lib/action_dispatch/middleware/debug_exceptions.rb:21:in 'call'
  actionpack (4.1.8) lib/action_dispatch/middleware/show_exceptions.rb:30:in 'call'
  railties (4.1.8) lib/rails/rack/logger.rb:38:in 'call_app'
  railties (4.1.8) lib/rails/rack/logger.rb:20:in 'block in call'
  activesupport (4.1.8) lib/active_support/tagged_logging.rb:68:in 'block in tagged'
  activesupport (4.1.8) lib/active_support/tagged_logging.rb:26:in 'tagged'
  activesupport (4.1.8) lib/active_support/tagged_logging.rb:68:in 'tagged'
  railties (4.1.8) lib/rails/rack/logger.rb:20:in 'call'
```

In the same time `Rails.backtrace_cleaner.add_filter { |line| line.sub('lib', '') }` works exactly as expected.

It seems I am not alone:

http://stackoverflow.com/questions/28836767/backtrace-silencer-not-working
http://stackoverflow.com/questions/35879335/how-to-prevent-logging-rails-stack-trace/
http://stackoverflow.com/questions/29169059/rails-backtrace-silencers-do-not-work-while-filters-do
### System configuration

**Rails version - 4.1.8, 4.2.6**:

**Ruby version - 2.2.1**:

**Comment by vipulnsward** [comment]
This is because of https://github.com/vipulnsward/rails/blob/ecc8f283cfc1b002b5141c527a827e74b770f2f0/actionpack/lib/action_dispatch/middleware/debug_exceptions.rb#L155-L156

Since `application_trace` is empty(This is because error is not from user code but route error), we are falling back to `framework_trace`, which does not filter it(It filters only noise).

For me, I would expect this to be reported and expected behaviour, since this error was not from some code user wrote.

**Comment by k2m30** [comment]
Well, I would accept this as an expected behaviour if:

-  `add_silencer` and `add_filter` both affect only `application_trace` which is not true at the moment
- the method is called something like `Rails.application_backtrace_cleaner`, not `Rails.backtrace_cleaner`

The real task behind it is to have only application trace by default. Which is enough for 99% of all bugs. Especially in production mode.
As I understand there is no default method to implement it without monkey-patching. 

Here is description from http://api.rubyonrails.org 

### add_silencer(&block)
Adds a silencer from the block provided. If the silencer returns true for a given line, it will be excluded from the clean backtrace.

```Ruby
# Will reject all lines that include the word "mongrel", like "/gems/mongrel/server.rb" or 
"/app/my_mongrel_server/rb"
backtrace_cleaner.add_silencer { |line| line =~ /mongrel/ }
```
I cannot imagine `line =~ /mongrel/` would affect application trace.

**Comment by vipulnsward** [comment]
@k2m30 I am not 100% sure of this issue either :smile: , hence waiting for others to comment. This behaviour has been so since the beginning.

**Comment by vipulnsward** [comment]
This was an intentional change to handle the edge-case I mentioned- https://github.com/rails/rails/pull/3970

**Comment by rafaelfranca** [comment]
Yeah, it is expected but we should probably fix the documentation.

**Comment by JeffCohen** [comment]
Maybe when the docs are changed I'll understand this better, but I wouldn't have guessed any difference between a "silencer" and a "filter".  I've rarely found the framework trace to be helpful.  

I personally think backtraces in the log files should only show application traces by default.  Any additional silencer/filters would only be to help further filter out noise from gems that I have included in my Gemfile. If others agree, I'd be happy to try to research how the silencers/filters currently work, and change them to achieve this behavior.  

But like I said at the beginning, maybe I simply misunderstand the value of the silencers vs filters, and simply improving the docs will help me understand the current behavior.

**Comment by k2m30** [comment]
@JeffCohen 

> log files should only show application traces by default

Completely agree. At least possibility to enable this functionality should present in Rails.

Regarding your question – silencers wipe out backtrace lines, filters modify them according to block given. At least it works so at the moment.

**Comment by arthurnn** [comment]
@vipulnsward have you fixed the issue in master? should we close this ?

**Comment by vipulnsward** [comment]
We have not fixed this yet. We fixed something similar but for the rails console.

**Comment by gkop** [comment]
I ran into this when inserting my custom middleware early in the middleware stack. My ultimate easy solution was moving my middleware to `vendor/middleware/` and manually requiring it with `require_relative`, which successfully tricked Rails into suppressing it from the backtrace.
