### ISSUE TITLE
Question: Pass more than one param to Action Cable server?

### ISSUE THREAD

**Issue by SylarRuby** [rails/rails#24446]
Could you change this to a question?

[Based on my StackOverflow question](http://stackoverflow.com/questions/36420246/more-than-one-params-with-rails-5-action-cable?noredirect=1#comment60456495_36420246), is it possible to pass more than one param to the Action Cable (AC), server? Is AC purpose to operate as a chat app where only one param is passed?

```
App.room.speak(
    {
      english: "Hello",
      french: "Bonjour"
    }
  )
```

I should be able to receive both params in the `speak` method:

```
def speak(english, french)
 # do something with english and french
end
```

**Comment by SylarRuby** [comment]
Never mind. I have solved it.

**Comment by NullVoxPopuli** [comment]
For others who may be passing through, I have a ruby-based client for action cable that uses EventMachine. https://github.com/NullVoxPopuli/action_cable_client

You'd basically just do this:
```ruby
 client.perform('speak', { message: 'hello from amc', parameter_two: 'something else' })
```

@SylarRuby can you post how your solved your problem? in case someone has the same setup as you?

**Comment by SylarRuby** [comment]
@NullVoxPopuli My answer is on stackoverflow. See the link above.
