### ISSUE TITLE
Add the option to preserve original SELECT clause

### ISSUE THREAD

**Issue by odedniv** [rails/rails#24447]
When using `select` method on ActiveRecord it replaces the default SELECT clause. Sometimes you want to only add custom values (such as subquery from related tables), and restoring the original clause (`table.*`) is painful. As a squeel user, I don't really like using custom SQL and I don't want to have to specify the table name (which can also be aliased, or in a different database type).

There needs to be an option to either not replace the SELECT clause or to restore it, for example with this scope on `ActiveRecord::Base`:

```ruby
# after a long time I just found out you can do that, doesn't feel right in app though
scope :select_all, -> { select(arel_table[Arel.star])) }
```

### Steps to reproduce
```ruby
class User < ActiveRecord::Base
end

users = User.select("5 AS custom")
```

### Expected behavior
Original SELECT clause is kept (or ability to restore).

```ruby
User.select("5 AS custom").to_sql
# => SELECT `users`.*, 5 AS custom FROM `users`
```

### Actual behavior
Original SELECT clause is replaced with a new one.

```ruby
User.select("5 AS custom").to_sql
# => SELECT 5 AS custom FROM `users`
```

### System configuration
**Rails version**: 4.2.5.1

**Ruby version**: 2.2.3

**Comment by vipulnsward** [comment]
See https://github.com/rails/rails/blob/master/guides/source/active_record_querying.md#selecting-specific-fields. The purpose of select is to retrieve a subset, which is expected behaviour here.

Here is how you can achieve the above behaviour with `default_scope` if needed in your case- https://gist.github.com/vipulnsward/c3b69cb2b145bf95135569031d8f76ea

**Comment by odedniv** [comment]
@vipulnsward I understand that this is the expected behavior, I'm just stating the ActiveRecord is missing a common functionality, and for some reason chose one over the other arbitrarily.

Back ticks are MySQL specific, and the table name can be aliased (in a joins for example). These are only 2 examples why custom SQL in the app is not a proper solution for the problem... This cannot be done in a gem for example.

As I wrote, there is the option to use `arel_table[Arel.star]` which solves the back ticks problems, but still. I think this is not just "my" use case, adding to the select clause is a very common requirement.

**Comment by vipulnsward** [comment]
Hi @odedniv I am not able to think what's best way to achieve this, on top of my head. `arel_table` is not public API and as such not advisable to use it directly as well.

As regards to above issue, this is more of a feature request(enhancement) and not a bug, and this tracker is reserved for issues. You can post about it to the rubyonrails-core@googlegroups.com mailing list, for further discussion.

Thanks for providing the rationale of why you need it! :green_heart:

**Comment by odedniv** [comment]
Yes, that's why I didn't want to use Arel.

Sorry, I guess I missed that! Will post there, thank you :smiley:
