### ISSUE TITLE
Pluck Method Issue

### ISSUE THREAD

**Issue by mukeshrj** [rails/rails#24452]
### Steps to reproduce
   
  As per this page http://guides.rubyonrails.org/active_record_querying.html#pluck
  
  I am trying to use => Client.pluck(:id, :name)
  
  But it is giving following error
     ArgumentError: wrong number of arguments (2 for 1) 

  Ruby Version : ruby-2.0.0-p247
  
  Rails Version:  Rails 3.2.14

let me know if mistake from my side

**Comment by sevenseacat** [comment]
That guide is for the current version of Rails - Rails 3.2.14 does not have that functionality.

http://guides.rubyonrails.org/v3.2.14/active_record_querying.html#pluck

**Comment by mukeshrj** [comment]
Thanks Dude...I didn't notice that.
