### ISSUE TITLE
Generated ApplicationMailer is not namespaced when generating within mountable engine.

### ISSUE THREAD

**Issue by dtognazzini** [rails/rails#24456]
### Steps to reproduce
Follow the [Rails Guide](http://guides.rubyonrails.org/engines.html) to generate an engine:

```
$ rails plugin new blorgh --mountable
```

Generate a mailer in the generated engine:
```
$ cd blorgh
$ rails g mailer user
      create  app/mailers/blorgh/user.rb
      create  app/mailers/application_mailer.rb
      ...
```
Look at the generated `ApplicationMailer`:
```
$ cat app/mailers/application_mailer.rb
```
```ruby
class ApplicationMailer < ActionMailer::Base
  default from: "from@example.com"
  layout 'mailer'
end
```

### Expected behavior
`ApplicationMailer` should be nested under `Blorgh`.

```
$ rails g mailer user
      create  app/mailers/blorgh/user.rb
      create  app/mailers/blorgh/application_mailer.rb
      ...
```

```
$ cat app/mailers/blorgh/application_mailer.rb
```
```ruby
module Blorgh
  class ApplicationMailer < ActionMailer::Base
    default from: "from@example.com"
    layout 'mailer'
  end
end
```

### Actual behavior
Covered in [Steps to reproduce](#steps-to-reproduce)

### System configuration
**Rails version**:  4.2.5.2

**Ruby version**: 2.2.3

**Comment by rafaelfranca** [comment]
Could you try the master branch?

**Comment by dtognazzini** [comment]
Working on master. Duplicate of https://github.com/rails/rails/pull/24164.
