### ISSUE TITLE
pluck does not work with pg array type

### ISSUE THREAD

**Issue by andreydeineko** [rails/rails#24466]
### Steps to reproduce

```
rails new pluck_with_pg_array
rails g migration create_users
```
```
rails g migration create_departments
  def change
    create_table :departments do |t|
      t.integer    :account_ids, array:true, default: []
      t.timestamps null: false
    end
  end
```
```
rails g migration create_department_users references:user references:department
```
```
rake db:migrate
```

Then create some user, some department with few linked_accounts.
Then associate user with department.

```
user = User.create!
department = Department.create!(account_ids: [1,2,3])
user.departments << department
```

### Expected behavior
When I do
```ruby
user.departments.pluck(:account_ids)
```

I would expect to have an array of arrays of `department`s `account_ids`.

### Actual behavior
Instead I get array of empty arrays.

### System configuration
**Rails version**: 4.2.3

**Ruby version**: 2.3.0

**Comment by arktisklada** [comment]
I'm not experiencing the same error... Here's a test setup: https://gist.github.com/arktisklada/48b8d606cffe8b5ad41d3e156752eb91.  Are there any differences between what you have and this gist?

**Comment by vipulnsward** [comment]
I am not able to replicate either, @arktisklada's script passes for me.

@andreydeineko can you check if there's something different from this script?

**Comment by andreydeineko** [comment]
@arktisklada, @vipulnsward  Strange, but in newly generated app I do not experience the issue.
There must be something I am missing in my real application. Sorry for bothering you guys..

**Comment by vipulnsward** [comment]
Thanks for confirming, please re-open if you notice this issue.
