### ISSUE TITLE
ActionMailer::Preview uses different execution of mailer for email info bar and email content

### ISSUE THREAD

**Issue by barnett** [rails/rails#24460]
### Steps to reproduce

Create a mailer:

``` ruby
class ObjectMailer < ApplicationMailer
  def event_happened
    @object = Object.new
    mail to: 'test@gmail.com', subject: "#{@object} Happened!"
  end
end
```

Create a preview:

``` ruby
# Preview all emails at http://localhost:3000/rails/mailers/account_mailer
class ObjectMailerPreview < ActionMailer::Preview
  def event_happened
    ObjectMailer.event_happened
  end
end
```

And in `apps/views/object_mailer/event_happened.html.erb`:

``` erb
<p>@object</p>
```

The object will differ.

[Example Repo](https://github.com/barnett/action_mailer_bug)
1. Start server
2. Go to `/rails/mailers/object_mailer/event_updated`
3. :boom:
### Expected behavior

I would expect the render for the email and email info bar use the same execution.  Thus the `Object#id` in the `subject` and within the email would be the same.
### Actual behavior

They render with different instances.
### System configuration

**Rails version**: `5.0.0.beta1`
**Ruby version**: `2.3.0`

**Comment by vipulnsward** [comment]
The email content is displayed in an iframe and fetched in a separate request(based on whether html or text is selected in dropdown).

cc @pixeltrix if we are interested to update this header info as well. It would need a full-page reload/or not using this iframe though.

**Comment by pixeltrix** [comment]
Yeah, we'd need to redesign the page so that the whole page would be re-rendered at the same time.

@barnett your example is very contrived - do you have a real-world example where this has affected you?

**Comment by barnett** [comment]
@pixeltrix sure!

In a PreviewMailer I am using `Array#sample` to select an `Account` instance that's in a specific state.  The issue is, the `body` of the mailer will mention one `Account`, when the `subject` will mention another (since I have dynamic content in those areas based on the `Account`).

code sample:
```ruby
class AccountMailerPreview < ActionMailer::Preview
  def upcoming_surveys
    accounts = Account.active.with_upcoming_surveys
    AccountMailer.upcoming_surveys(accounts.sample.id)
  end
end
```

**Comment by dmytro-spivakov** [comment]
Reproduced on Rails 7.0.4
