### ISSUE TITLE
No link to "About your application's environment" in Welcome page

### ISSUE THREAD

**Issue by djunzu** [rails/rails#24469]
The last paragraph in section 4.1 of the edge version of Rails Guides, Getting Started with Rails chapter, states:

> The "Welcome aboard" page is the smoke test for a new Rails application: it makes sure that you have your software configured correctly enough to serve a page. You can also click on the About your application's environment link to see a summary of your application's environment.

Launching a new app (beta 3), I can't see such link. Inspecting `railties-5.0.0.beta3/lib/rails/templates/rails/welcome/index.html.erb`, I can't see such link too.

I think docs should be updated. Or better, I would like to see the link in the welcome page!

**Comment by vipulnsward** [comment]
Thanks for reporting @djunzu . Would you like to send a PR to update this section in docs with this change?

**Comment by djunzu** [comment]
Well, I could give it a try.

Just to make it clear: There won't be such link and the docs should not state about it. Right?

**Comment by vipulnsward** [comment]
Yes.
