### ISSUE TITLE
Assets with mixed line returns get corrupted

### ISSUE THREAD

**Issue by TeknoFiend** [rails/rails#24472]
### Steps to reproduce

Include a Javascript file with mixed line returns (specifically CRLF at the beginning of the file and just LF later). Run rails server and load a page in browser (we used Chrome). 
### Expected behavior

The JS file should be identical to the one in the file system and parse & execute properly.
### Actual behavior

When looking at the JS file in the dev tools in the browser there are extra (random) characters added next to the bare LF characters. Seems like some file processor somewhere in the stack is expecting two character everywhere there is a line return even if the line return is just an LF. Because the file is corrupted it does not parse and/or execute properly.

This happens with `config.assets.debug` set to `true` _or_ `false`.
### System configuration

**Rails version**:   rails (= 4.1.14.2)

**Ruby version**: jruby-1.7.22

**Comment by TeknoFiend** [comment]
I should have mentioned that this is a problem because of third-party assets. It's not desirable to have mixed line returns in files but it is sometimes beyond our control.

**Comment by vipulnsward** [comment]
Hi @TeknoFiend can you create a sample App replicating this behaviour?
