### ISSUE TITLE
Possible bug with enabling caching on dev environment 

### ISSUE THREAD

**Issue by psantos10** [rails/rails#24470]
### Steps to reproduce

When I run the following command for the first time:

$ bin/rails dev:cache

I got the following feedback:

> Development mode is now being cached.

And the file `tmp/caching-dev.txt` is created.

From this point, I expect  to, when I run the server (`bin/rails server`), to be running with caching on dev enabled. 

But it is not happing that way. After run `bin/rails dev:cache` followed by the command `bin/rails server`, the caching on dev mode is disabled and the file `tmp/caching-dev.txt` deleted.

The only way is to run `bin/rails server -C`.

And the `bin/rails server -C` command can be executed without previously execute the `bin/rails dev:cache` command. In this case my question is:

- Is this supposed to run this way?

- If yes, why do I need the `bin/rails dev:cache` command?

### System configuration
**Rails version**: 5.0.0.beta3

**Ruby version**:  2.3.0p0 (2015-12-25 revision 53290) [x86_64-linux]

**Comment by vipulnsward** [comment]
@psantos10 all newly generated Apps contain https://github.com/vipulnsward/rails/blob/722227a6f63b0a2fc45bd150a0dd6de3b7878c46/railties/lib/rails/generators/rails/app/templates/config/environments/development.rb.tt#L16-L27 that takes care of this.

Can you confirm if your development config has this?

**Comment by psantos10** [comment]
@vipulnsward this is the content of my generated file (`config/environments/development.rb`):

```
# Enable/disable caching. By default caching is disabled.
  if Rails.root.join('tmp/caching-dev.txt').exist?
    config.action_controller.perform_caching = true

    config.action_mailer.perform_caching = false

    config.cache_store = :memory_store
    config.public_file_server.headers = {
      'Cache-Control' => 'public, max-age=172800'
    }
  else
    config.action_controller.perform_caching = false

    config.action_mailer.perform_caching = false

    config.cache_store = :null_store
  end
````
This demo application was generated today.

**Comment by vipulnsward** [comment]
This has now been fixed by https://github.com/rails/rails/pull/24331 on master.

Example log: https://gist.github.com/vipulnsward/822946ccc4dcf2263b8663764f0d9e4d

Log with caching, read fragment call- https://gist.github.com/vipulnsward/822946ccc4dcf2263b8663764f0d9e4d#file-restart-log-L4

Log after running dev:cache again- https://gist.github.com/vipulnsward/822946ccc4dcf2263b8663764f0d9e4d#file-restart-log-L34-L37

Thanks for reporting @psantos10 . The fix should be out in new release.
