### ISSUE TITLE
Support for Float.years

### ISSUE THREAD

**Issue by brchristian** [rails/rails#24473]
There are some scientific data sets that use floating-point numbers for years.

For instance, the ice core CO2 measurements [here](http://www1.ncdc.noaa.gov/pub/data/paleo/icecore/antarctica/antarctica2015co2composite.txt) uses the standard “Years Before Present” unit, which is floating point by default.

At present there is no way (to my knowledge) to ingest these values cleanly into Rails.

If there is interest in merging something to adapt the `.years` method for use with `Float`s so that scientific data sets like these can be more easily handled in Rails, I can prepare a PR.

**Comment by vipulnsward** [comment]
Hello @brchristian . This is more of a feature request(enhancement) and not a bug, and this tracker is reserved for issues. You can post about it to the rubyonrails-core@googlegroups.com mailing list, for further discussion.

Thanks!

**Comment by brchristian** [comment]
Thanks, will do! :+1:
