### ISSUE TITLE
Overridden accessor methods fail numericality validation

### ISSUE THREAD

**Issue by sigvei** [rails/rails#24478]
### Steps to reproduce

When all of the following is true:
* An integer field's accessor method is overridden with a custom method
* The field is passed a params hash with a blank string, which is then translated to nil
* A NumericalityValidator with allow_nil: true is set for the field

The validation fails with `:not_a_number`, even though the field resolves to `nil`.

### Expected behavior
The validation should succeed

### System configuration
**Rails version**: 4.2.6

**Ruby version**: 2.2.3

### Executable test case

[Here's an executable test case for the issue](https://gist.github.com/sigvei/484ba0624cd1c5a9118a6eb98d57d161).

**Comment by vipulnsward** [comment]
@sigvei https://gist.github.com/sigvei/484ba0624cd1c5a9118a6eb98d57d161 doesn't contain the issue you have mentioned. Can you update it to replicate this issue?

**Comment by sigvei** [comment]
Oops, sorry. Now updated.

**Comment by meinac** [comment]
To demonstrate the issue we don't need that complex scenarios. Here is a *simple* test case which reproduces the bug.
```ruby
begin
  require 'bundler/inline'
rescue LoadError => e
  $stderr.puts 'Bundler version 1.10 or later is required. Please update your Bundler'
  raise e
end

gemfile(false) do
  source 'https://rubygems.org'
  gem 'activerecord', '5.0.0.beta3'
  gem 'sqlite3'
  gem 'pry'
end

require 'active_record'
require 'minitest/autorun'
require 'logger'
require 'pry'

ActiveRecord::Base.establish_connection(adapter: 'sqlite3', database: ':memory:')
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :foos, force: true do |t|
    t.integer :column
  end
end

class Foo < ActiveRecord::Base
  validates :column, numericality: { allow_nil: true }

  def column
    read_attribute(:column) || 0
  end
end

class BugTest < Minitest::Test
  def test_not_working_validation
    foo = Foo.new(column: '')

    assert_equal 0, foo.column
    assert_predicate foo, :valid?
  end
end
```
Test fails because at initial step of numericality validation, it looks whether `type casted`! attribute is nil or not and the value of allow_nil option. This check passes because we return 0 if attribute is nil. But after than this it tries to validate numericality of the attribute without type cast. As a result of this, it tries to validate empty string as number and it fails.

**Comment by vipulnsward** [comment]
> The validation fails with `:not_a_number`, even though the field resolves to nil.

As mentioned above, the numericality validation works on value before type cast(user supplied value) unless it is `nil`, and not the one that is typecasted(based on db). That `read_attribute` typecasts values has been documented [here](https://github.com/rails/rails/blob/e944e67001a1bebd1f7305f5b30f5ae9361ecb28/activerecord/lib/active_record/attribute_methods/read.rb#L47-L49)

Going to give this is a close, paging @sgrif  as well
