### ISSUE TITLE
update to 4.2.6 broke getting my assets

### ISSUE THREAD

**Issue by BrennerSpear** [rails/rails#24482]
### Steps to reproduce

update to Rails 4.2.6
visit my app's homepage

### Expected behavior
It should return 200 OKs for all my assets

### Actual behavior
it returns 500 ERRORs and this error for each asset:

```2016-04-09 12:55:19 -0700: Rack app error: #<NoMethodError: undefined method `[]' for nil:NilClass>
12:55:19 web.1    | /Users/BrennerSpear/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/activesupport-4.2.6/lib/active_support/logger_silence.rb:23:in `level'
12:55:19 web.1    | /Users/BrennerSpear/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/quiet_assets-1.1.0/lib/quiet_assets.rb:24:in `call_with_quiet_assets'
12:55:19 web.1    | /Users/BrennerSpear/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/newrelic_rpm-3.15.0.314/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
12:55:19 web.1    | /Users/BrennerSpear/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/actionpack-4.2.6/lib/action_dispatch/middleware/request_id.rb:21:in `call'
12:55:19 web.1    | /Users/BrennerSpear/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/newrelic_rpm-3.15.0.314/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
12:55:19 web.1    | /Users/BrennerSpear/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/rack-1.6.4/lib/rack/methodoverride.rb:22:in `call'
12:55:19 web.1    | /Users/BrennerSpear/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/newrelic_rpm-3.15.0.314/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
12:55:19 web.1    | /Users/BrennerSpear/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/rack-1.6.4/lib/rack/runtime.rb:18:in `call'
12:55:19 web.1    | /Users/BrennerSpear/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/newrelic_rpm-3.15.0.314/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
12:55:19 web.1    | /Users/BrennerSpear/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/rack-timeout-0.3.2/lib/rack/timeout/core.rb:125:in `block in call'
12:55:19 web.1    | /Users/BrennerSpear/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/rack-timeout-0.3.2/lib/rack/timeout/support/timeout.rb:19:in `call'
12:55:19 web.1    | /Users/BrennerSpear/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/rack-timeout-0.3.2/lib/rack/timeout/support/timeout.rb:19:in `timeout'
12:55:19 web.1    | /Users/BrennerSpear/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/rack-timeout-0.3.2/lib/rack/timeout/core.rb:124:in `call'
12:55:19 web.1    | /Users/BrennerSpear/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/newrelic_rpm-3.15.0.314/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
12:55:19 web.1    | /Users/BrennerSpear/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/activesupport-4.2.6/lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
12:55:19 web.1    | /Users/BrennerSpear/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/newrelic_rpm-3.15.0.314/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
12:55:19 web.1    | /Users/BrennerSpear/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/rack-1.6.4/lib/rack/lock.rb:17:in `call'
12:55:19 web.1    | /Users/BrennerSpear/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/newrelic_rpm-3.15.0.314/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
12:55:19 web.1    | /Users/BrennerSpear/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/actionpack-4.2.6/lib/action_dispatch/middleware/static.rb:120:in `call'
12:55:19 web.1    | /Users/BrennerSpear/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/newrelic_rpm-3.15.0.314/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
12:55:19 web.1    | /Users/BrennerSpear/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/rack-1.6.4/lib/rack/sendfile.rb:113:in `call'
12:55:19 web.1    | /Users/BrennerSpear/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/newrelic_rpm-3.15.0.314/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
12:55:19 web.1    | /Users/BrennerSpear/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/railties-4.2.6/lib/rails/engine.rb:518:in `call'
12:55:19 web.1    | /Users/BrennerSpear/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/railties-4.2.6/lib/rails/application.rb:165:in `call'
12:55:19 web.1    | /Users/BrennerSpear/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/newrelic_rpm-3.15.0.314/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
12:55:19 web.1    | /Users/BrennerSpear/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/puma-2.16.0/lib/puma/commonlogger.rb:31:in `call'
12:55:19 web.1    | /Users/BrennerSpear/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/puma-2.16.0/lib/puma/configuration.rb:81:in `call'
12:55:19 web.1    | /Users/BrennerSpear/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/puma-2.16.0/lib/puma/server.rb:557:in `handle_request'
12:55:19 web.1    | /Users/BrennerSpear/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/puma-2.16.0/lib/puma/server.rb:404:in `process_client'
12:55:19 web.1    | /Users/BrennerSpear/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/puma-2.16.0/lib/puma/server.rb:270:in `block in run'
12:55:19 web.1    | /Users/BrennerSpear/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/puma-2.16.0/lib/puma/thread_pool.rb:106:in `call'
12:55:19 web.1    | /Users/BrennerSpear/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/puma-2.16.0/lib/puma/thread_pool.rb:106:in `block in spawn_thread'```

 
### System configuration
**Rails version**: 4.2.6

**Ruby version**: 2.2.2

**Comment by rafaelfranca** [comment]
This seems a bug in quite_assets by the backtrace you provided. Since we don't support quite_assets I recommend you to report the issue there.

**Comment by BrennerSpear** [comment]
Will do - thanks.
