### ISSUE TITLE
Transaction deadlock with rails 5 beta 3

### ISSUE THREAD

**Issue by mfazekas** [rails/rails#24491]
### Steps to reproduce

We have a complex test with rspec, database cleaner, factorygirl. Some runs are deadlocking. Debugging showed that there is a transaction started but not finished.

A simplified case:
https://gist.github.com/mfazekas/ccf9bee10dc4fe23f39d1da1b914993b

### Expected behavior
Pass or error, but not a deadlock

### Actual behavior

Deadlock. Test doesn't finish

### System configuration
**Rails version**: 5.0.0.beta3
**Ruby version**: 2.3.0

cannot repro in 4.2.0

**Comment by mfazekas** [comment]
This test invokes controller action inside a transaction.
Rails seems to give back that connection to the pool here, with the transaction opened:
https://github.com/rails/rails/blob/master/activerecord/lib/active_record/query_cache.rb#L48

If some thread grabs the connection just after, or returns connection before then the the we'll have a split head scenario. Where the connection where we started the transaction is now somewhere else and we're working with another connection without the transaction.

**Comment by mfazekas** [comment]
I'd propos 2 fix: 

1. raise an exception when a connection with and opened transaction tried to retired. This is just asking for trouble.
2. as indicated by comment do no remove the connection when we're running a test

**Comment by arthurnn** [comment]
regarding number 2.
I wonder why the regression test on https://github.com/rails/rails/commit/c7b7c6ad1c773102753f1a11b857d0e37ceb6a21 was not failing .

**Comment by arthurnn** [comment]
NVM, seems like the test was removed in the PR https://github.com/rails/rails/commit/d3c9d808e3e242155a44fd2a89ef272cfade8fe8?diff=split#diff-4836275ce5b6432a15ca07c1a15593d5L69

cc @matthewd

**Comment by mfazekas** [comment]
The reported case fixed, but there is still an edge case with multiple connection: https://gist.github.com/mfazekas/55ba95e52d4959bfca94787481313ca7
