### ISSUE TITLE
Unable to skip default unit test while generating new rails application

### ISSUE THREAD

**Issue by shivashankar-ror** [rails/rails#24496]
### Steps to reproduce
`rails new myapp --database=mysql --skip-test-unit`

### Expected behavior
The rails application should not have default test framework installed

### Actual behavior
Currently it has 'test' folder created 

### System configuration
**Rails version**:
Rails 5.0.0.beta3

**Ruby version**:
ruby 2.2.2p95

**Comment by vipulnsward** [comment]
This has now changed to `----skip-test`. Can you confirm if that works ok for you.

**Comment by vipulnsward** [comment]
Going to close, since we also list it in the command help.

**Comment by shivashankar-ror** [comment]
The command is  `--skip-test` instead of `----skip-test`

**Comment by vipulnsward** [comment]
Yup, I had updated the typo. Thanks for reporting @shivashankar-ror .

**Comment by KaraAJC** [comment]
Can someone help me find the point at which it changed from `--skip-test-unit` to `--skip-test`
