### ISSUE TITLE
is there a way to re-render?

### ISSUE THREAD

**Issue by salmanasiddiqui** [rails/rails#24498]
I have written an API in which I am rescuing from all StandardError. Incase of any StandardError, I send an exception email and render json with error message.
This works great except when the exception is raised from views (i am using jbuilder for json responses). As then when I render json with error message, it raises double render exception cause render has already been called in controller.
Is there a way to override the initial render call?

ruby 2.1.8
rails 4.2.6

**Comment by maclover7** [comment]
Please use the mailing list or StackOverflow for questions/help, where a wider community will be able to help you. We reserve the issues tracker for issues only.
