### ISSUE TITLE
Rails 5 not showing error page when template is not found

### ISSUE THREAD

**Issue by psantos10** [rails/rails#24505]
### Steps to reproduce

I have a controller `PagesController` with an action `index`.

```
class PagesController < ApplicationController
   def index
   end
end
```
And try to access: http://localhost:3000/pages . At this step, deliberately I dont create the view `app/views/pages/index.html.erb`

### Expected behavior

Not creating the view, on development machine, I expect to have an error page like: 

> Missing template pages/index, application/index with {:locale=>[:en], :formats=>[:html], :variants=>[], :handlers=>[:erb, :builder, :raw, :ruby, :coffee, :jbuilder]}. Searched in: * "/Users/psantos/Workspace/demos/demo15/app/views"

As it happens this way on other Rails versions.

### Actual behavior

But, instead this, it redirect to the root_path (`http://localhost:3000/`).

Checking the logs, I found this:

> Started GET "/pages" for ::1 at 2016-04-11 14:25:34 +0100
> Processing by PagesController#index as HTML
> No template found for PagesController#index, rendering head :no_content
> Completed 204 No Content in 3ms (ActiveRecord: 0.0ms) 

This was changed on Rails 5? Is it supposed to redirect instead of showing the error page?  

I did not find any reference about this change on the Internet.

### System configuration
**Rails version**: 5.0.0.beta3

**Ruby version**: 2.3.0

**Comment by maclover7** [comment]
Yep, this is a thing that has changed for Rails 5... @chancancode did we add this to the upgrade notes :grimacing:

**Comment by vipulnsward** [comment]
Its in the release notes- https://github.com/rails/rails/blob/d03c90e8aa011cbf4244bfc5e622492dcdb52ee2/guides/source/5_0_release_notes.md#notable-changes-1
I don't think we need to add this to upgrading guide.

**Comment by vipulnsward** [comment]
Closing, thanks @psantos10 !
