### ISSUE TITLE
ActiveRecord::RecordInvalid: Validation failed: XXX must exist

### ISSUE THREAD

**Issue by RyanYang1221** [rails/rails#24518]
### Steps to reproduce
My rails version is 5.0.0beta3.
I want to do self join today.
My model is Person. Person can be separated to parent and child. 
My person.rb:
```
class Person < ApplicationRecord
 has_many :children, class_name: "Person",
                     foreign_key: "parent_id"
 belongs_to :parent, class_name: "Person"
end
```
The migration file:
```
class CreatePeople < ActiveRecord::Migration[5.0]
 def change
   create_table :people do |t|
     t.string :name
     t.references :parent
     t.timestamps null: false
   end
 end
end
```
When I use the rails console to create Person like `Person.create!(name: "ABC")`
I got  `ActiveRecord::RecordInvalid: Validation failed: Parent must exist`

However, in Rails 4, there is no such validation.
Does Rails 5 add the validation? Is it possible to create without validation?
In this scenario, I cannot create any people. How can I assign the parent when creating a person?

### Expected behavior
Creating person without assigning a parent.

### Actual behavior
A error "ActiveRecord::RecordInvalid: Validation failed: parent must exist" is shown.  

### System configuration
**Rails version**: 5.0.0beta3

Thanks.
BRs,
Ryan

**Comment by prathamesh-sonpatki** [comment]
@RyanYang1221  This change was added in https://github.com/rails/rails/pull/18937.

Now it is the associated record needs to be present for `belongs_to` association by default. To opt out,

you can have 

``` ruby
belongs_to :parent, class_name: "Person", optional: true
```


You can also make this change application wide by using following configuration option - 

```
config.active_record.belongs_to_requred_by_default
```

If you have generated the Rails 5 app from scratch, this option must be present in one of the initializers - 
`config/initializers/active_record_belongs_to_required_by_default.rb`.

Otherwise you can add it manually too.

Giving it a close as it's not really an issue. Thanks for reporting!

**Comment by RyanYang1221** [comment]
Hi,

Thanks for your response!
One more question, how can I know that  belongs_to has the option ` optional ` in Rails 5?
Is there any release notes or pages?

Thank you.

**Comment by prathamesh-sonpatki** [comment]
It's here as of now - http://edgeguides.rubyonrails.org/5_0_release_notes.html#active-record-notable-changes.

Once Rails 5 is releases then it will be available at guides.rubyonrails.org/5_0_release_notes.html#active-record-notable-changes :)

**Comment by RyanYang1221** [comment]
Got it!
Thank u so much! :)

**Comment by shreyakapadia10** [comment]
> @RyanYang1221 This change was added in #18937.
> 
> Now the associated record needs to be present for `belongs_to` association by default. To opt out,
> 
> you can have
> 
> ```ruby
> belongs_to :parent, class_name: "Person", optional: true
> ```
> 
> You can also make this change application wide by using following configuration option -
> 
> ```
> config.active_record.belongs_to_requred_by_default
> ```
> 
> If you have generated the Rails 5 app from scratch, this option must be present in one of the initializers -
> `config/initializers/active_record_belongs_to_required_by_default.rb`.
> 
> Otherwise you can add it manually too.
> 
> Giving it a close as it's not really an issue. Thanks for reporting!

Thank you

**Comment by xero-lib** [comment]
> @RyanYang1221 This change was added in #18937.
> 
> Now the associated record needs to be present for `belongs_to` association by default. To opt out,
> 
> you can have
> 
> ```ruby
> belongs_to :parent, class_name: "Person", optional: true
> ```
> 
> You can also make this change application wide by using following configuration option -
> 
> ```
> config.active_record.belongs_to_requred_by_default
> ```
> 
> If you have generated the Rails 5 app from scratch, this option must be present in one of the initializers -
> `config/initializers/active_record_belongs_to_required_by_default.rb`.
> 
> Otherwise you can add it manually too.
> 
> Giving it a close as it's not really an issue. Thanks for reporting!

I just got syntax errors, and assignment errors.
![image](https://user-images.githubusercontent.com/54485853/108748799-9d0b1400-7504-11eb-9655-db4c30319b19.png)
