### ISSUE TITLE
confusing usage of capitalized first letter in 'Getting Started with Rail' documentation

### ISSUE THREAD

**Issue by martinmoreau** [rails/rails#24530]
# Steps to reproduce
Go to chapter 6.4 'Generating a Controller' of the 'Getting Started with Rails' guide where the following  is stated: '$ bin/rails generate controller Comments'

# Expected behavior
It's confusing that the first letter of the controller name is capitalized, because only Model names have a capitalized first letter. Also throughout the guide the generation of the article controller is written with a lower case first letter for the controller name.
It's true that the rails generate command ignores the capital letter and generates the controller with a lower case first letter, but I find this confusing for the reader.

# Suggestion
I suggest to use a lower case first letter like so: '$ bin/rails generate controller comments'.
Then add a information box where there is stated that rails always generates controllers with lower case first letters despite the use of capital letters in de generate command.

**Comment by prathamesh-sonpatki** [comment]
@martinmoreau Would you like to open a PR to fix the documentation?

**Comment by martinmoreau** [comment]
I will open a PR

**Comment by martinmoreau** [comment]
I'm a newby on rails and on github and  I'm a bit unsure on how the create a pull request for changing the documentation. Can anybody assist me with this?

**Comment by vipulnsward** [comment]
We should do the opposite and capitalize where its not, to match generator documentation.
Its also confusing that we are doing model capitalization and not controller.
Ideally we would refer to a controller as `Article`'s controller , and not not `article`s controller.

**Comment by vipulnsward** [comment]
In terms on readability this is better-

```ruby
rails generate controller Comment
```

than

```ruby
rails generate controller comment
```
since it highlights our intent of creating `Comments.`

@martinmoreau see http://guides.rubyonrails.org/contributing_to_ruby_on_rails.html#issue-a-pull-request for a guide about this.

**Comment by Elektron1c97** [comment]
(ignore my commits)

**Comment by gartha1** [comment]
vipulnsward's comment has gone against convention and, if trying to quote the guide, has misquoted the guide as well. 

The guide has rails generate controller Comments i.e. plural.
