### ISSUE TITLE
Relations validate: true only runs on create

### ISSUE THREAD

**Issue by jhaesus** [rails/rails#24532]
### Steps to reproduce
```ruby
class Parent < ApplicationRecord
  has_many :items, validate: true
end

class Item < ApplicationRecord
  belongs_to :parent
  validates :name, presence: true
end
```

### Expected behavior

```ruby
item1 = Item.new
parent1 = Parent.new
parent1.items << item1
parent1.save! => Validation error

item2 = Item.new(name: "bla")
parent2 = Parent.new
parent2.items << item2
parent2.save! => true
item2.name = nil
item2.save(validate: false)
parent2.reload.save! => true
```

### Actual behavior

items are not validated on update

### System configuration
**Rails version**: 5.0.0.beta3

**Ruby version**: 2.3.0

**Comment by tomash** [comment]
I don't think it's a bug. From what I see in the code, `validate` option only ensures validation when **inserting new record into association**:
https://github.com/rails/rails/blob/52ce6ece8c8f74064bb64e0a0b1ddd83092718e1/activerecord/lib/active_record/associations/has_many_association.rb#L41
https://github.com/rails/rails/blob/52ce6ece8c8f74064bb64e0a0b1ddd83092718e1/activerecord/lib/active_record/associations/has_many_through_association.rb#L38

If you want to ensure all associated records are revalidated on every update, you should use `validates_associated`. Here, I've added test cases demonstrating what you expect (and that they fail if `validates_associated` is not used:

https://github.com/tomash/rails/commit/b701d92ba3d007087883360cd6b1356693f3afd6

**Comment by tomash** [comment]
My personal suggestion: update the docs to reflect that `validate: true` causes validation only on inserting new member of association, not that it's the same as `validated_associated`. Current description "If false, don't validate the associated objects when saving the parent object. true by default." can lead to confusion. I can file a docs pull request if maintainers are OK with this idea?

**Comment by vipulnsward** [comment]
Even validated_associated doesn't work.

**Comment by tomash** [comment]
@vipulnsward works for the test cases I've written. Is there a case that fails?

**Comment by sgrif** [comment]
I'd be fine with changing the docs to clarify this. Even if this was considered a bug, it would be extremely difficult to change. Since `validate: true` is the default for collection associations, changing the behavior of that option would be a massive breaking change.
