### ISSUE TITLE
possibly licence violation in ActiveSupport up to 4.6

### ISSUE THREAD

**Issue by lksv** [rails/rails#24548]
All ActiveSupport (and other rails parts until the recent) uses gem `json`.
E.g. https://github.com/rails/rails/blob/v4.2.6/activesupport/activesupport.gemspec#L24

As I understand this gem (https://rubygems.org/gems/json) is under Ruby license, but the old, the copy left one:

> Ruby License, see the COPYING file included in the source distribution. The Ruby License includes the GNU General Public License (GPL), Version 2, so see the file GPL as well.

(e.g. version which ruby used up to 1.9.2).

Therefore my opinion is that it is copyleft license and cannot be included in MIT projects (I am not a lawyer). Personally I hope I am wrong. I searched similar questions, but it seams that nobody found/checked it.

**Comment by lksv** [comment]
linking with flori/json#280

**Comment by rafaelfranca** [comment]
As far as I know, Rails only use json as dependency, it doesn't include any copy or distribute the source or the binary with it, so there is no copyright problem with the current licence of JSON even that it is a copy-left licence.

**Comment by sgrif** [comment]
That is my understanding as well, there is no license conflict for using something as a dependency. If any lawyers would like to chime in, we can reopen.

**Comment by lksv** [comment]
@rafaelfranca @sgrif 
If I understand you correctly, you say that Rails could be MIT, but if I use Rails in my commercial project then I'm violating the json's licence? 

In other words, when the end product requires Rails gem and needs `bundle install` to be done to work then am I violating the license?

Does It mean I cannot use rails in commercial product with closed license?

Personally I have a different opinion: Rails (versions up to 4.6) links json (gem) library and there is clearly written in [Readme](https://github.com/flori/json/tree/v1.8.3):
> Ruby License, see the COPYING file included in the source distribution. The Ruby License includes the GNU General Public License (GPL), Version 2, so see the file GPL as well.

and [GPL file](https://github.com/flori/json/tree/v1.8.3)

Therefore no MIT/Apache license gem could allow to be dependent on it.

**Comment by jeremy** [comment]
@lksv Please follow up on the JSON gem: https://github.com/flori/json/search?q=license. It has a history of license confusion, despite a clear intent to follow Ruby license.
