### ISSUE TITLE
Enums on rails 5 (PostgreSQL)

### ISSUE THREAD

**Issue by waghanza** [rails/rails#24550]
Hi all,

I'm using new `rails` **5** (`beta3`).

I want to create an **enum** type in database (`postgresql`).

This is my migration

~~~ruby
class Vehicule < ActiveRecord::Migration[5.0]
  def change
    create_table :vehicules do |t|
      t.enum type_of: ["car","bus"]

      t.timestamps
    end
  end
end
~~~

I have the following error

`undefined method `enum' for #<ActiveRecord::ConnectionAdapters::PostgreSQL::TableDefinition:0x00563ff5ae7320>`

is there any change with `rails` **4**  ?

* Ruby `ruby 2.2.4p230 (2015-12-16 revision 53155) [x86_64-linux]`
* Rails `Rails 5.0.0.beta3`

Regards,

**Comment by vipulnsward** [comment]
Hi @waghanza this is not supported even on 4.2. I believe what you are trying to achieve is provided here- http://edgeguides.rubyonrails.org/active_record_postgresql.html(Enumerated Types).

Closing since not an issue, but more of a feature request right now. Thanks for reporting.

**Comment by kp666** [comment]
Adding direct url http://edgeguides.rubyonrails.org/active_record_postgresql.html#enumerated-types

**Comment by waghanza** [comment]
@kp666 Thanks

unfortunately, this not fit my needs -> it could not be dropped (modified ?)
