### ISSUE TITLE
Controller instance variables aren't cleared between successive calls from a single test.

### ISSUE THREAD

**Issue by z5h** [rails/rails#24566]
### Steps to reproduce

Create a controller that lazily initializes an instance variable.

```
def index
  @items = some_data.limit(10)
end

def some_data
 @data ||= get_data(params[:data_param])
end

```
Create a test that makes 2 calls to a controller.
The controller will not have had it's instance variables cleared between requests.

```
def test_controller
  get :index, data_param: "good_param"
  get :index, data_param: "bad_param_should_cause_excetpion" // get_data never called with this param 
end

```
### Expected behavior
I expect a controller to have no instance variables set upon each call.

### Actual behavior
Instance variables stay set between calls to a controller when called from a test.

### System configuration
**Rails version**:
4.1.14.2

**Ruby version**:
2.1.2p95

**Comment by maclover7** [comment]
Can you create an executable test script using one of the templates [here](https://github.com/rails/rails/tree/master/guides/bug_report_templates), that would demonstrate the problem you are seeing? Also, does this issue still exist on Rails master?

**Comment by sngeth** [comment]
From the doc description for ActionController::TestCase :
Superclass for ActionController functional tests. Functional tests allow you to** test a single controller action per test method**.

So this may be the intended behavior? Looks like it's recycling the test controller and not resetting any instance variables. Seems like before each call to process a HTTP request, controller instance variables set by the user would need to be reset then.

**Comment by rafaelfranca** [comment]
That is expected. The instance of the controller is only one inside each test case.

**Comment by shaokun** [comment]
I met this issue several times, and spend me a lot of time to figure out why. This behavior totally break the basic pricinple that HTTP doesn't remember status among requests.
@rafaelfranca, do you mean that never write more than 1 requests per test case?

**Comment by rafaelfranca** [comment]
If it is a controller test yes. It doesn't make a HTTP request, it call a method in the controller. If you use a integration test you will not have this problem.

**Comment by bogdan** [comment]
I think it is a good idea to have a method like `reset_controller` to allow multiple independent requests inside the same test.
