### ISSUE TITLE
Rails 5 master branch: Mysql2::Result#each segfaults, array size too big, and negative array size

### ISSUE THREAD

**Issue by codeodor** [rails/rails#24569]
### Steps to reproduce

I have not been able to reproduce this outside my application yet. So far, I can only get it to happen in a test -- not even in console during test mode -- and have not been able to isolate where it's happening inside Rails.

It comes about often when using `ActiveRecord::Base.connection.execute(query).each(:as=>:hash, :symbolize_keys => true)` ... but not always.

In the test, the actual result is an empty array.  And if I print the whole stacktrace, Rails does not show up: "myfile.rb:45:in `each'" is the first line, but I don't define each, and it doesn't make it to the 1st line inside the block.

### Expected behavior
Iterate over each row of the result set with the row as a hash using symbolized keys.

### Actual behavior
segfaults, array size too big, and negative array size

### System configuration
**Rails version**:  5.0 on master

**Ruby version**: 2.3.0

mysql2 0.4.3 is the adapter in use.

**Comment by codeodor** [comment]
I guess the first thing I'm looking for, is if anyone can give me some direction on how to improve what I'm reporting here.

**Comment by codeodor** [comment]
Removing the `as: :hash` I see this sometimes now:

```
ruby(15829,0x7fff7bb11000) malloc: *** mach_vm_map(size=1123123677409280) failed (error code=3)
*** error: can't allocate region
*** set a breakpoint in malloc_error_break to debug
ruby(15829,0x7fff7bb11000) malloc: *** mach_vm_map(size=1123123677409280) failed (error code=3)
*** error: can't allocate region
*** set a breakpoint in malloc_error_break to debug
```

But since it's an empty array, I don't think it should be having trouble running out of RAM. 

Just in case, here's what my usage looks like at the time:

![image](https://cloud.githubusercontent.com/assets/23479/14572995/b1671d22-0317-11e6-9867-53af750b0b12.png)

**Comment by codeodor** [comment]
Ok, I downgraded mysql2 to 0.4.2 and have run it 5 times with no errors. On the other hand, I have run it several dozen times on 0.4.3 and it has only given me no errors one time, so I guess I should close this and open it in mysql2's project.

**Comment by sodabrew** [comment]
I've just posted mysql2 version 0.4.4 that should resolve this problem. Please update and test to confirm!

**Comment by codeodor** [comment]
Confirmed that 0.4.4 fixes the issue. Thanks!
