### ISSUE TITLE
How to debug on rails 5

### ISSUE THREAD

**Issue by waghanza** [rails/rails#24563]
Hi,

I'm starting with a new app with

~~~ruby
gem "rails", "~> 5.0.0.beta3"
~~~

I wonder how to debug on this release.

In fact just print on a console is sufficient, but `puma` does not show it to me.

Has anyone already debug on rails 5 ?

Regards,

**Comment by maclover7** [comment]
Please use the mailing list or StackOverflow for questions/help, where a wider community will be able to help you. We reserve the issues tracker for issues only.
