### ISSUE TITLE
created_at have unexpected behavior

### ISSUE THREAD

**Issue by ShallmentMo** [rails/rails#24575]
### Steps to reproduce
When you create a model in console ( I'm using blog as an example ).

### Expected behavior
```
> p = Post.new
 => #<Post id: nil, title: nil, content: nil, created_at: nil, updated_at: nil>
 > p.save
   (0.1ms)  begin transaction
  SQL (1.1ms)  INSERT INTO "posts" ("created_at", "updated_at") VALUES (?, ?)  [["created_at", "2016-04-16 06:20:35.606603"], ["updated_at", "2016-04-16 06:20:35.606603"]]
   (0.5ms)  commit transaction
 => true
 > p.created_at.to_f
 => 1460787635.606603
2.2.1 :006 > p.reload.created_at.to_f
 => 1460787635.606603
```
### Actual behavior
```
 > p = Post.new
 => #<Post id: nil, title: nil, content: nil, created_at: nil, updated_at: nil>
> p.save
   (0.1ms)  begin transaction
  SQL (0.3ms)  INSERT INTO "posts" ("created_at", "updated_at") VALUES (?, ?)  [["created_at", "2016-04-16 06:25:37.872714"], ["updated_at", "2016-04-16 06:25:37.872714"]]
   (4.0ms)  commit transaction
 => true
 > p.created_at.to_f
 => 1460787937.8727148
 > p.reload.created_at.to_f
  Post Load (0.2ms)  SELECT  "posts".* FROM "posts" WHERE "posts"."id" = ? LIMIT 1  [["id", 1]]
 => 1460787937.872714
```

### System configuration
**Rails version**:
4.2.6
**Ruby version**:
2.2.3

Actually, the expected behavior happened in my mac, the actual behavior happened in my ubuntu server.  Is it system related? I still think it should be the same, as I use created_at to do the md5 thing.

**Comment by tak1n** [comment]
@ShallmentMo I think this has to do with the precision of the database field.
Which database do u use on both systems?

**Comment by ShallmentMo** [comment]
They are all sqlite3. The one on mac is  `3.9.2 2015-11-02 18:31:45 bda77dda9697c463c3d0704014d51627fceee328`. The other one on ubuntu is `3.8.2 2013-12-06 14:53:30 27392118af4c38c5203a04b8013e1afdb1cebd0d`.

**Comment by ShallmentMo** [comment]
It also happened in my ubuntu when I used  `postgres` .

**Comment by tak1n** [comment]
I'm honestly not a db expert in that regard and I don't know if there is a way to configure that properly, but I also had such cases where fractions got cut off because of the precision of a db field.
Maybe someone more experienced than me could kick in and help out :smile:

**Comment by ShallmentMo** [comment]
I'm not using created_at.to_f to do this now. I guess using created_at.to_f is quite rare here.

**Comment by vipulnsward** [comment]
I don't see this behaviour on 4.2 or master- https://gist.github.com/vipulnsward/726c2c29a9ac5d5fb5ffa62a110f667c
@ShallmentMo can you confirm with above script what behaviour you see.

**Comment by ShallmentMo** [comment]
I change `gem 'activerecord', '4.2'` to `gem 'activerecord', '~> 4.2'`, then I run this code in ubuntu. I got this:
```
-- create_table("users", {:force=>:cascade})
D, [2016-04-17T00:14:18.539757 #1199] DEBUG -- :    (0.3ms)  CREATE TABLE "users" ("id" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, "created_at" datetime NOT NULL, "updated_at" datetime NOT NULL)
   -> 0.0042s
Run options: --seed 60041

# Running:

D, [2016-04-17T00:14:18.564234 #1199] DEBUG -- :    (0.1ms)  begin transaction
D, [2016-04-17T00:14:18.570255 #1199] DEBUG -- :   SQL (0.3ms)  INSERT INTO "users" ("created_at", "updated_at") VALUES (?, ?)  [["created_at", "2016-04-16 16:14:18.567662"], ["updated_at", "2016-04-16 16:14:18.567662"]]
D, [2016-04-17T00:14:18.571251 #1199] DEBUG -- :    (0.1ms)  commit transaction
D, [2016-04-17T00:14:18.573443 #1199] DEBUG -- :   User Load (0.1ms)  SELECT  "users".* FROM "users"  ORDER BY "users"."id" ASC LIMIT 1
.

Finished in 0.019070s, 52.4396 runs/s, 52.4396 assertions/s.

1 runs, 1 assertions, 0 failures, 0 errors, 0 skips
```
and this
```
-- create_table("users", {:force=>:cascade})
D, [2016-04-17T00:14:16.807095 #1195] DEBUG -- :    (0.4ms)  CREATE TABLE "users" ("id" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, "created_at" datetime NOT NULL, "updated_at" datetime NOT NULL)
   -> 0.0062s
Run options: --seed 17021


▽
# Running:

D, [2016-04-17T00:14:16.833256 #1195] DEBUG -- :    (0.1ms)  begin transaction
D, [2016-04-17T00:14:16.837119 #1195] DEBUG -- :   SQL (0.1ms)  INSERT INTO "users" ("created_at", "updated_at") VALUES (?, ?)  [["created_at", "2016-04-16 16:14:16.834907"], ["updated_at", "2016-04-16 16:14:16.834907"]]
D, [2016-04-17T00:14:16.837990 #1195] DEBUG -- :    (0.1ms)  commit transaction
D, [2016-04-17T00:14:16.840073 #1195] DEBUG -- :   User Load (0.1ms)  SELECT  "users".* FROM "users"  ORDER BY "users"."id" ASC LIMIT 1
F

Finished in 0.016087s, 62.1601 runs/s, 62.1601 assertions/s.

  1) Failure:
BugTest#test_association_stuff [test.rb:42]:
Expected: 1460823256.834907
  Actual: 1460823256.8349068

1 runs, 1 assertions, 1 failures, 0 errors, 0 skips
```
Sometime it is ok, sometime it's not. My ubuntu is `Ubuntu 14.04.3 LTS \n \l` runing on Virtualbox.

**Comment by maclover7** [comment]
Agree with @tak1n -- this is a database precision issue.

**Comment by jeremy** [comment]
Check out the SQLite docs. DATETIME fields are mapped to NUMERIC and are exact precision.

You're likely getting different results because you're converting the resulting Time object to a Float, which has inexact precision: http://ruby-doc.org/core-2.3.0/Float.html
