### ISSUE TITLE
Has one through autosave bug

### ISSUE THREAD

**Issue by jbcden** [rails/rails#24583]
### Steps to reproduce
You can see the failing example [here](https://gist.github.com/jbcden/2e1e83c716423c641afc4c611bc03ac7).
### Expected behavior
In `4-1-stable`, the given example would persist the changes to the `AccountManager`. Adding `autosave` to the `Account` and `UserAccount` on the `User` model fixes it but I am wondering if this is what should be happening?
### Actual behavior
In previous versions the changes to the `AccountManager` would also be saved.

### System configuration
**Rails version**:
`4.2.6`
**Ruby version**:
`2.3.0`

**Comment by maclover7** [comment]
Can you see if this is reproducible on Rails master?

**Comment by jbcden** [comment]
This does occur on Rails master too.

**Comment by maclover7** [comment]
First off, it looks like you have a `belongs_to` association call on both `AccountManager` and `Account` -- not sure if that contributes to the error(s) you are seeing :grimacing:

**Comment by jbcden** [comment]
Oops. The `AccountManager` should have a `has_many :accounts`. Changing that unfortunately does not solve the issue.

**Comment by jbcden** [comment]
I just updated the gist to reflect those changes!

**Comment by vipulnsward** [comment]
> Changing that unfortunately does not solve the issue.

You mean fortunately. :wink:

**Comment by vipulnsward** [comment]
Too quick to comment. Read it was solved :disappointed:

**Comment by jbcden** [comment]
If only 😞

**Comment by maclover7** [comment]
I think the issue is that you are

```ruby
  user.account.account_manager = manager2
  user.save
  user.reload
```

... when you should be...

```ruby
  user.account.account_manager = manager2
  user.account.save
  user.account.reload
```

Thoughts?

**Comment by jbcden** [comment]
That would indeed work. I suppose my real question is, was this an intentional change or a regression?

**Comment by vipulnsward** [comment]
This looks like a side effect of https://github.com/rails/rails/pull/16875 
Notice that: `user.account.changed?` is false, so it doesn't need to save, but was previously saving due to this bug.
