### ISSUE TITLE
has_one through self-referential join generates incorrect query when both models have a default_scope

### ISSUE THREAD

**Issue by ozydingo** [rails/rails#24588]
### Steps to reproduce

self-contained gist here:
https://gist.github.com/ozydingo/f946313aec00c25f82447c70428ba138

Description:
Foo has_one :bar, Bar belongs_to :foo
Foo has_one parent_foo and has_many child_foos
Bar has_one parent_foo through :foo
Bar has_one parent_bar through :parent_foo

Bar.last.parent_bar produces an incorrect query. In sqllite this simply fails to find the correct row. In MySQL it produces a syntax error. For example, the query generated in the attached gist by the line `Bar.find(2).parent_bar` is:

`SELECT  `bars`.* FROM `bars` INNER JOIN `foos` ON `bars`.`foo_id` = `foos`.`id` INNER JOIN `foo_relationships` ON `foos`.`id` = `foo_relationships`.`parent_foo_id` INNER JOIN `foos` `foos_parent_bar_join` ON `foo_relationships`.`child_foo_id` = `foos_parent_bar_join`.`id` WHERE `bars`.`deleted` = 0 AND `foos`.`deleted` = 2 AND `foos_parent_bar_join`.`id` =  LIMIT 1`

We can see this query is missing a value on the final parameter ``foos_parent_bar_join`.`id``, and incorrectly applies the value `2`, which should have been used there, to ``foos`.`deleted``.

This error can be worked around by using a String SQL gfragment instead of a Hash; i.e., changing

`default_scope ->{where deleted: false}`

to

`default_scope ->{where "foos.deleted = 'f'"}`

on either or both models (substituting the correct table name, of course). This might be problematic if the model is ever used in a condition where the table name is aliased. I believe this workaround points to a possible overwriting of a Hash key or deletion or missing value in an Array used to generate the final query.
### Expected behavior

1) The query should not result in a syntax error in MySQL
2) Independent of database adapter, `Bar.find(2).parent_bar` should result in the `Bar` with id 1. This occurs when using SQL fragments in the default_scope, or if there is no default scope. 
### Actual behavior

1) The query produces a syntax error in MySQL
2) `Bar.find(2).parent_bar` return `nil` if using sqllite as the node values are applies to the incorrect fields.
### System configuration

**Rails version**: 4.2.3

**Ruby version**: 2.2.2

**Comment by vipulnsward** [comment]
Looks like we are generating wrong binds.

**Comment by vipulnsward** [comment]
Ok, tracked this to - https://github.com/rails/rails/commit/b64b7545106db0744c054ef615a952fa1e962e60

cc @sgrif

**Comment by ozydingo** [comment]
@vipulnsward I tried to look into this today. Forgive me as I'm pretty new to navigating the deeper Rails ecosystem. I'm a little confused though because it seems like commit b64b754 is later than 4.2.3; in fact, v4.2.3 does not even have where_clause.rb. Did I misinterpret what you meant? I can also dig into it again later to try to do further tracking down of this behavior, I just wasn't prepared at this time to set myself up to test anything with Rails 5.

What would be the procedure going forward: does a PR get generated only into edge Rails, or is there still hope for Rails 4?

**Comment by vipulnsward** [comment]
Its related to https://github.com/rails/rails/pull/22823. This issue was fixed in https://github.com/rails/rails/commit/5d41cb3bfd6b19833261622ce5d339b1e580bd8b .
https://github.com/rails/rails/commit/b64b7545106db0744c054ef615a952fa1e962e60 reverted it, because @sgrif had concerns over it. I believe he will have a look soon.

**Comment by amysutedja** [comment]
I believe that this is likely related to an issue that I found and is reproable in this repo: https://github.com/amysutedja/mutable_default_scope_demo

**Comment by ozydingo** [comment]
@vipulnsward can you point me to any reference on bind_values? I believe this is likely related to another problem I am coming up against, asked [here](http://stackoverflow.com/questions/39629098/how-to-use-bind-values-in-arel), where i am stuck because I do not know much about how to use bind values, have come up against a wall in poking around code, and cannot find any good references. Any help you can offer would be appreicated, and once I know more I can likely take a look at this at some point and make suggestions on this issue too.

**Comment by kamipo** [comment]
Fixed by 213796fb4936dce1da2f0c097a054e1af5c25c2c.
