### ISSUE TITLE
Ruby 2.4 #to_time incompatibility

### ISSUE THREAD

**Issue by jeremy** [rails/rails#24617]
Ruby 2.4 changes `Time#to_time` and `DateTime#to_time` to preserve timezone. This is a good thing, but it breaks Active Support's scheme to harmonize `#to_time` behavior.

Example build failures:
- https://github.com/rails/rails/blob/master/activesupport/test/core_ext/date_time_ext_test.rb#L55
- https://github.com/rails/rails/blob/master/activesupport/test/core_ext/time_with_zone_test.rb#L423
- https://travis-ci.org/rails/rails/jobs/124101215#L533-L542

Ruby changes:
- DateTime: https://bugs.ruby-lang.org/issues/12189
- Time: https://bugs.ruby-lang.org/issues/12271

We'll need to update our `#to_time` to feature-detect the new versions and behave consistently on Ruby 2.3.0 and 2.4.0.

**Comment by yui-knk** [comment]
On Ruby 2.3.0, `#to_time` uses system timezone of `#to_time` is called (this precedes timezone of a receiver object).
On Ruby 2.4.0, will use timezone of a receiver object.

> behave consistently on Ruby 2.3.0 and 2.4.0

means "using system timezone of `#to_time` is called" on both Ruby 2.3.0 and 2.4.0 ?

**Comment by jeremy** [comment]
@yui-knk Yes, use local (system tz). We had to compromise when our only options were local tz or utc. I wish we could have preserved tz of the receiver all along!

This is an unfortunate situation, then, since changing `#to_time` behavior will require a major Rails change (5.0.0) and will need a configuration flag to enable. Plus we'll need to emulate Ruby 2.4 `#to_time` for Date/Time/DateTime on Ruby 2.2 and 2.3, which I'm not sure is possible due to internal API usage.

**Comment by jeremy** [comment]
(Ref https://github.com/ruby/ruby/pull/1295)

**Comment by pixeltrix** [comment]
Ugh, will have a look at this today

**Comment by jeremy** [comment]
🤘

**Comment by gshutler** [comment]
The fix for this appears to be a breaking change for reasons I don't understand.

The simplest reproduction is this:

```
irb(main):001:0> frozen_time = Time.now.freeze
=> 2017-03-09 09:07:41 +0000
irb(main):002:0> Time.now >= frozen_time
RuntimeError: can't modify frozen Time
	from .../vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.8/lib/active_support/core_ext/date_and_time/compatibility.rb:23:in `to_time'
	from .../vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.8/lib/active_support/core_ext/time/calculations.rb:261:in `compare_with_coercion'
	from (irb):2:in `>='
        ...
```

**Comment by pixeltrix** [comment]
@gshutler yes, we're aware of it - see #28147

**Comment by gshutler** [comment]
Ah, my apologies, that didn't come back for my searches.

**Comment by kalmanh** [comment]
This was backported to 4.2.8 and now 4.2.8 creates an initializer during the creation of the app called to_time_preserves_timezone.rb whose whole purpose in life is to call 

`ActiveSupport.to_time_preserves_timezone = true`

which is fine if... you are going to run your app using Rails 4.2.8. If for whatever reason you need to go back to 4.2.3 and run the app - you won't be able to, because `ActiveSupport` in 4.2.3 does not have the method `to_time_preserves_timezone =`

Does it make sense to surround this with exception handling or something similar so that even apps created using Rails 4.2.8 can be run in Rails 4.2.3?

**Comment by pixeltrix** [comment]
@kalmanh given that you only get that initializer when you generate a new app I don't think it does and the general rule is we support forwards compatibility only.
