### ISSUE TITLE
ActiveRecord finder .last behave unexpectedly with previous use of present? or blank?

### ISSUE THREAD

**Issue by slowjack2k** [rails/rails#24624]
Hi,

I have some issues when I call `#present?` or `#blank?` (ok, this is not efficient, but a valid call) on a scope before I call `#last` .
In this case the order is "random".

For example the following calls:

```ruby
 user_sope = User.where('created_at > ?', 100.days.ago)
 user_scope.present?
 user_scope.last
```

I expect that the returned value is the last record ordered by primary key. With Rails 3 I did get the
last record but with rails 4 it returns a "random" record.

I think this happens because `#present?` simply calls `#to_a` and does not respect
the default order by primary key. After this call `#last` checks if the records are `#loaded?`.

In this case `#loaded?` is `true` because of the previous `#to_a` call, but the order of the records is wrong. 

Maybe `#present?` should act like `#exsits?`without an argument.

activerecord-4.2.6
rails-4.2.6
ruby 2.3.0p0

regards
dieter

**Comment by maclover7** [comment]
Looking into this.

**Comment by vipulnsward** [comment]
@maclover7 just for ref: https://gist.github.com/vipulnsward/390c54f617035a7f93a7d5116fc87228 
This is passing for me.
@slowjack2k can you also specify your DB? Or better yet, use above script to recreate the issue.

**Comment by mayurkhatri** [comment]
@slowjack2k  I was not able to replicate this.
I am using 
ruby 2.3.0-preview1
activerecord (4.2.6)
rails (4.2.6)

I executed the queries you gave me directly in rails console without a scope in model(Could not replicate it)
And executed it with a scope and called the queries on it.(Could not replicate the issue).

Just a mistake i noted in your post queries 
The variable spelling differ in first and remaining two lines.user_sope( 'c' is missing ) and user_scope.

**Comment by slowjack2k** [comment]
@mayurkhatri 
I use postgres with pg-0.18.4.

Yes, there is a typo, I'm sorry. You'r right it should be `user_scope = User.where('created_at > ?', 100.days.ago)`
You can't see this issue directly. It depends on the amount of records within your database and which order your database uses to return values.

But when you execute `user_scope.present?`
the generated SQL looks like this whitin the logfile

`SELECT "users".* FROM "users" WHERE (created_at > '2016-01-10 15:17:30.403148')`

The order by clause is missing. And when you call `#last` you will see that there is no more db call after the first one.

When you take a look [here](https://github.com/rails/rails/blob/v4.2.6/activerecord/lib/active_record/relation/finder_methods.rb#L152) you can see that `#last` without an argument uses `#find_last` and [find_last](https://github.com/rails/rails/blob/v4.2.6/activerecord/lib/active_record/relation/finder_methods.rb#L503) does not reload records when they are already loaded.

I hope my analysis is right.

**Comment by maclover7** [comment]
Not able to reproduce this on master using the following script: https://gist.github.com/maclover7/a3380380e429309ea5f6ac621a6eb468. 
Can you create an executable test script using one of the templates [here](https://github.com/rails/rails/tree/master/guides/bug_report_templates), that would demonstrate the problem you are seeing?

**Comment by slowjack2k** [comment]
I did anotate vipulsnwards gist. Does this help?

**Comment by maclover7** [comment]
@slowjack2k I updated my gist to incorporate your annotations, but it fails for me, due to a syntax error (`ActiveRecord::StatementInvalid: SQLite3::SQLException: near "(": syntax error: VACUUM (VERBOSE, ANALYZE) users`). Can you please provide a reproduction script that shows the error you are seeing?

**Comment by vipulnsward** [comment]
```
...snip..
INFO:  vacuuming "public.users"
INFO:  index "users_pkey" now contains 19100 row versions in 57 pages
DETAIL:  0 index row versions were removed.
2 index pages have been deleted, 2 are currently reusable.
CPU 0.00s/0.00u sec elapsed 0.00 sec.
INFO:  "users": found 0 removable, 100 nonremovable row versions in 1 out of 128 pages
DETAIL:  0 dead row versions cannot be removed yet.
There were 57 unused item pointers.
0 pages are entirely empty.
CPU 0.00s/0.00u sec elapsed 0.00 sec.
INFO:  analyzing "public.users"
INFO:  "users": scanned 128 of 128 pages, containing 19100 live rows and 0 dead rows; 19100 rows in sample, 19100 estimated total rows
D, [2016-04-20T03:47:16.674468 #75138] DEBUG -- :    (11.5ms)  VACUUM (VERBOSE, ANALYZE) users
D, [2016-04-20T03:47:16.675499 #75138] DEBUG -- :   User Load (0.4ms)  SELECT  "users".* FROM "users" WHERE (created_at > '1961-07-17 22:17:16.674625')  ORDER BY "users"."id" DESC LIMIT 1
I, [2016-04-20T03:47:16.675779 #75138]  INFO -- : Start test
D, [2016-04-20T03:47:16.705092 #75138] DEBUG -- :   User Load (29.2ms)  SELECT "users".* FROM "users" WHERE (created_at > '1961-07-17 22:17:16.675641')
F

Finished in 33.700752s, 0.0297 runs/s, 0.0593 assertions/s.

  1) Failure:
BugTest#test_failing_stuff [24624.rb:65]:
Expected: 20000
  Actual: 20100

1 runs, 2 assertions, 1 failures, 0 errors, 0 skips
```

The main issue is that we don't use sorting based on id when we do `to_a`/`all` and that is intentional.
(I don't think this is going to change and it will just break things cc @rafaelfranca )

You are seeing this issue, because PG doesn't honour sorting by default. http://www.postgresql.org/docs/9.1/static/queries-order.html
For now you can overcome this by adding sort on id for your `default_scope`

```ruby
class User < ActiveRecord::Base
  default_scope -> {order(:id)}
end
```
which passes successfully.

**Comment by rafaelfranca** [comment]
Yes, it is intentional. Also I think `present?` should not do the same thing that `exists?` if the behavior you want is to not load the collection use `exists?`. If you want to `all` or `to_a` have an order set it.

**Comment by slowjack2k** [comment]
@vipulnsward SQL does not guarantees that your data will come back in a certain order. postgres is no a exception. Most RDBMS do it this way even mysql. 

@rafaelfranca please reconsider your decission or update the docs. This is a totaly unexpected site effect, I think. This effect is not restricted to `#.present?`. It is also active when I call first `#to_a`  on a relation. Or better said every method call, that loads records and change `#loaded?` to true will create this bug. Why should this code behave different?

```
relation1 = User.where(id: [1,2,3,5])
# some more code
relation1.to_a
# some more code
last1 = relation1.last

relation2 = User.where(id: [1,2,3,5])
# some more code
relation2.to_a
#some more code
last2 = relation2.last

last1 != last2  # some times
last1 == last2 # some times

relation3 = User.where(id: [1,2,3,5])
# some more code
relation1.all
# some more code
last3 = relation3.last

relation4 = User.where(id: [1,2,3,5])
# some more code
relation4.all
#some more code
last4 = relation4.last

last1 == last2 # every time true
```

When you read the docs, you don't expect this behavior.
The docs for `#last` say "If no order is defined it will order by primary key." and
thats not true. That relations can have this kind of site effect, is also not explained. 

Furthor more this creates a random bug, which is very difficult to track down.

In may special case it failed randomly, only on production and even with a db dump 
from production I was not able to reproduce this error.

**Comment by rafaelfranca** [comment]
Once loaded the relation behaves differently from not loaded relations.
This is already know behavior and we don't have plans to change it. I agree
with documenting this behavior in the methods that are sensitive to the
loaded attribute. Could you open a pull request with this documentation
patch?

**Comment by slowjack2k** [comment]
What means "this is known behavior"? I haven't read any hint within the docs or guidelines. I think this is only known behavior for rails contributors.

Sorry, I can't provide a good documentation patch. I don't know all your guidelines for submitting a PR and your style guides for documentation. Furthor more, to do it right, you have to mark every method which behaves different after relation loading as "special".

**Comment by slowjack2k** [comment]
@prathamesh-sonpatki Thank you very much!
