### ISSUE TITLE
IOError: not modifiable string thrown by Hash.from_xml

### ISSUE THREAD

**Issue by gleseur** [rails/rails#24647]
### Steps to reproduce

     Hash.from_xml "<?xml version=\"1.0\"?><a></a>".freeze

IOError: not modifiable string
from .../activesupport-4.2.6/lib/active_support/xml_mini/rexml.rb:27:in `ungetc'

### Expected behavior
I would expect Hash.from_xml not to fail on frozen strings

### Actual behavior
Error raised

### System configuration
Rails 4.2.6
Ruby 2.3.0

**Comment by mayurkhatri** [comment]
@gleseur I could reproduce this

**Comment by mayurkhatri** [comment]
@gleseur but according to definition of [freeze](http://ruby-doc.org/core-2.2.3/Object.html#method-i-freeze) it prevents further modification of object.So, the behavior we see is correct according to me.

**Comment by gleseur** [comment]
@mayurkhatri Hash.from_xml parses the string to build a hash, I don't see why the parser should modify the parsed string. I would even say that I expect the parser to never modify the string being parsed.

**Comment by marekkirejczyk** [comment]
I agree with @gleseur. 
@vipulnsward: your solution will force to copy the whole input before parsing. It is inefficient for long xml inputs. 
The error message leave us with the clear clue: Rexml parser uses ungetc on the passed string.
So the solution can be made there. If you look at the code of the Rexml parser you can see:

`
    char = data.getc
      if char.nil?
        {}
      else
        data.ungetc(char)
        # (...) do actual parsing
      end
`

So the getc/ungetc is only used to check for the EOF.
So it seems to me that all we need to do use eof? instead:
`
    char = data.getc
      if char.nil?
        {}
      else
        data.ungetc(char)
        # (...) do actual parsing
      end
`
