### ISSUE TITLE
has_many through tries to write a readonly model

### ISSUE THREAD

**Issue by bquorning** [rails/rails#24649]
When I have a “has_many through” association where the “has_many” class is readonly, I get an error when replacing or adding to the collection – that the collection class “is marked as readonly”.

I believe d849f42b4ecf687ed5350f5a2402fb795aa33aac is the first offending commit. It should probably have replaced `if record.new_record?` with `if !record.readonly?` instead of removing the condition.

Gist in https://gist.github.com/bquorning/55dffab8e8038fbe0119ef6d854a5090

### System configuration
**Rails version**: v5.0.0.beta1 and later. Master branch since commit d849f42b4ecf687ed5350f5a2402fb795aa33aac.

**Ruby version**: Tested with 2.3.0

**Comment by bquorning** [comment]
PR: #24651.

**Comment by sgrif** [comment]
Sorry, but I think the current behavior is correct. If a record is read only, we should be blowing up loudly not silently changing behavior.

**Comment by bquorning** [comment]
Sorry, but I disagree.

Given the test case setup from #24651:
```rb
club = Club.create!
member = Member.create!
member.readonly!
```

Why shouldn’t it be possible to add `member` to `club`s collection of `membership`s?

Why should we even try to call `#save` on `member`? It actually only makes sense if `member` is a new record – which is the behavior that we had since at least Rails 2.1 (f6b12c11cd3a6df8525dd16ec093ec473813489e) until it was changed in Rails 5.0.0.beta1 (d849f42b4ecf687ed5350f5a2402fb795aa33aac).

**Comment by bquorning** [comment]
I’d love to see this issue re-opened.

**Comment by bquorning** [comment]
@maclover7 Sorry for being pushy, but would it be possible to re-open this PR? I believe it was closed a bit too fast, and nobody joins the discussing on a closed issue :-/

I got some valuable feedback on my PR #24651, but since that was closed, too, GitHub didn’t show when I pushed updates to the branch.

So I opened a new PR #24670 which I believe addresses the concern Sean had in the d849f42b4ecf687ed5350f5a2402fb795aa33aac commit message: “To me it seems like this should only be the case if `autosave: true` is set on the association.”

**Comment by maclover7** [comment]
Sorry @bquorning, I think it's @sgrif's decision about what gets accepted or not, since he's one of the lead contributors to Active Record 😬
