### ISSUE TITLE
Couldn't find template for digesting: #{name},  a ActionView::DependencyTracker::ERBTracker#render_dependencies accuracy problem

### ISSUE THREAD

**Issue by TheNotary** [rails/rails#24643]
### Steps to reproduce

Cook up a view that looks something like this (contains a commented out line that includes the word 'render')
```
<% cache(Digest::MD5.hexdigest(cache_horoscope)) do %>
  <%# If this is a runner up, don't render them here, add them to the runners list %>
  <%= render user %>
<% end %>
```
start rails server in production, and navigate to hit the view.  

### Expected behavior
I shouldn't see an error `Couldn't find template for digesting:`

### Actual behavior
I see an error `Couldn't find template for digesting: thems/them`

### System configuration
**Rails version**:  4.2.6

### Solution-ish
Note: line numbers based on 4.2.5.2

The easy way out of it is to not use the word `render` in comments within erb templates.  

The issue is that `ActionView::DependencyTracker::ERBTracker#render_dependencies` is inaccurate, and out of paranoia it was registering my commented out line as a rails render invocation (which it isn't really of course):

```
<%# If this is a runner up, don't render them here, add them to the runners list %>
```

See the word `render` in there?  Lol, that'll do it I guess.  The function looks a little different in master now, is the accuracy of this function being improved already?  I just tried with rails-4.2.6 and it has an inaccurate render_dependencies function in it.  

see actionview-4.2.5.2/lib/action_view/digestor.rb:105` wherein my index template has a dependency named 'them/thems'... because of the above comment line.

**Comment by vipulnsward** [comment]
@TheNotary do you see this on master as well?

**Comment by vipulnsward** [comment]
Hmm, I see it.

**Comment by vipulnsward** [comment]
Closing based on discussion in https://github.com/rails/rails/pull/13414 . This has been a know limitation.

**Comment by TheNotary** [comment]
Ah, good find @vipulnsward.  Two thoughts come to mind still, 

1)  It's a console message that comes up when devs are using caching, which I'm sure you can understand raises the hair on the back of ones neck.  What about a modification to the error message to indicate that this could have been a false positive when regexing the template for the word render?  

eg

```
      logger.try :error, "  Couldn't find template for digesting: #{name}, possible false possitive while scanning template with regex"

      # Can become...

      template_root_dir = finder.view_paths.first.to_s
      error_message_clue = caller.select {|e| e.include?(template_root_dir) }.first.partition(":").first
      logger.try :error, "  Couldn't find template for digesting: #{name}, possible false positive while scanning template for 'render' with regex.\n    Check #{error_message_clue}"
```

That would leave the developer with a stronger understanding as to why they're getting a error message periodically in their console, and still leave the error in tact in case something funky happens to ActionView::Digestor.  

2)  I don't wanna slow rails down, and don't know the exact performance implications of this suggestion, but what about changing the regex to ignore the line if it's preceded with a `#`.  On 4.2.5.2 this looks like:

```
# Old way
render_calls = source.split(/\brender\b/).drop(1)

# Slightly better way
render_calls = source.split(/^(?!.*\#).*\b+render\b/).drop(1)
```

I feel kind of meh about this because the function isn't going from inaccurate to accurate it's just gonig from inaccurate to more accurate in this one particular case =/
