### ISSUE TITLE
ActiveSupport::TimeZone#utc_offset gets stale during timezone transition

### ISSUE THREAD

**Issue by conf** [rails/rails#24659]
### Steps to reproduce

During time zone transition, when current time zone changes its `utc_offset`, `ActiveSupport::TimeZone` caches this information and it becomes stale.

This can be an issue when `TZInfo::TimeZone#current_period` is refreshed
due to time zone period transition, but it's not reflected in
`ActiveSupport::TimeZone` object.

 For example, on `Sun, 26 Oct 2014 22:00 UTC`, [Moscow changed](http://www.timeanddate.com/time/zone/russia/moscow) its `TZ` from
 `MSK +04:00` to `MSK +03:00` (-1 hour). If `ActiveSupport::TimeZone['Moscow']`
 happens to be initialized just before the time zone transition, it will
 cache its stale `utc_offset` even after the time zone transition.

### Test case 
```ruby 
  def test_utc_offset_is_not_cached_when_current_period_gets_stale
    tz = ActiveSupport::TimeZone.create('Moscow')
    travel_to(Time.utc(2014, 10, 25, 21)) do # 1 hour before TZ change
      assert_equal 14400, tz.utc_offset, 'utc_offset should be initialized according to current_period'
    end

    travel_to(Time.utc(2014, 10, 25, 22)) do # after TZ change
      # fails here
      assert_equal 10800, tz.utc_offset, 'utc_offset should not be cached when current_period gets stale'
    end
  end
```

### Expected behavior
Test passes.
`ActiveSupport::TimeZone#utc_offset` should be up-to-date even after timezone transition.

### Actual behavior
```bash
  1) Failure:
TimeZoneTest#test_utc_offset_is_not_cached_when_current_period_gets_stale [test/time_zone_test.rb:328]:
utc_offset should not be cached when current_period gets stale.
Expected: 10800
  Actual: 14400
```
`ActiveSupport::TimeZone#utc_offset` caches its initial value.

### System configuration
**Rails version**: 5.0.0.alpha

**Ruby version**: ruby 2.3.0p0 (2015-12-25 revision 53290) [x86_64-linux-gnu]

**Comment by jeremy** [comment]
Moving to PR.
