### ISSUE TITLE
Specify both coder and class in serialized attributes

### ISSUE THREAD

**Issue by dungdm93** [rails/rails#24655]
### Steps to reproduce
Setup db:
```
rails generate model Movie name:string info:string
```
`ActiveRecord#serialize` is a cool feature allows to marshal and store arbitrary data as a value in a table column, like:
```ruby
serialize :info             # coder = YAML, class = any
serialize :info, JSON       # coder = JSON, class = any
serialize :info, MovieInfo  # coder = YAML, class = MovieInfo
```
But if I want to specify both `coder = JSON` and `class = MovieInfo`, now, the only way to do this is define `MovieInfo` class like:
```ruby
class MovieInfo
  def self.dump(obj)
    ActiveSupport::JSON.encode(obj)
  end

  def self.load(json)
    attr = ActiveSupport::JSON.decode(json) unless json.nil?
    mi = MovieInfo.new
    mi.attributes = attr
    mi
  end

  def attributes=(attr)
    ...
  end
end
```
### Expected behavior
Above syntax is not clear and sometimes misleading.
I suggest new API:
```ruby
serialize :info, coder: :xml, type: MovieInfo
```
Furthermore, we can custom coder
```ruby
serialize :info, coder: XYZCoder, type: MovieInfo

# Or register new coder
ActiveRecord::Coders.register :xyz, XYZCoder
# and use it later
serialize :info, coder: :xyz, type: MovieInfo
```
### System configuration
**Rails version**:  4.2.6
**Ruby version**: 2.2.2

**Comment by rafaelfranca** [comment]
Please use the mailing list or StackOverflow for questions/help, where a wider community will be able to help you. We reserve the issues tracker for issues only.

**Comment by rafaelfranca** [comment]
Thank you so much for the issue but we don't take feature request on the issue tracker. We recommend you to try to implement the feature and send us a pull request or if you are in doubt if the feature will be accepts ask in Rails Core mailing list for feedback.
