### ISSUE TITLE
Rails 5 beta3: db:reset with 3+ migrations triggers ActiveRecord::StatementInvalid: SQLite3::SQLException

### ISSUE THREAD

**Issue by xHire** [rails/rails#24677]
I ran into issues with migrations (either SQLite3 exception, see below, or an error saying I have some pending migrations, but then it would throw an error that tables already exist...) and figured out that the problem appears whenever I have 3+ migrations. IIRC `db:reset` task is not the only one way for triggering this bug---I think ran into this also when redoing migrations (in development I often modify my migrations, remigrate them and rerun tests).

### Steps to reproduce
Minimal demo here: https://github.com/xHire/ror5-db_reset Simply run:

    $ bin/rails db:migrate
    $ bin/rails db:reset

### Expected behavior
Successful execution of the `db:reset` task.

### Actual behavior
    $ bin/rails db:reset
    Dropped database 'db/development.sqlite3'
    Dropped database 'db/test.sqlite3'
    Created database 'db/development.sqlite3'
    Created database 'db/test.sqlite3'
    -- create_table("authors", {:force=>:cascade})
       -> 0.1721s
    -- create_table("books", {:force=>:cascade})
       -> 0.3224s
    -- create_table("chapters", {:force=>:cascade})
       -> 0.4233s
    -- initialize_schema_migrations_table()
       -> 0.1574s
    rails aborted!
    ActiveRecord::StatementInvalid: SQLite3::SQLException: near ",": syntax error: INSERT INTO "schema_migrations" (version) VALUES ('20160421154718'), ('20160421154709')
    /home/xhire/.bundler/ruby/2.2.0/rails-81f4a7dce42e/activerecord/lib/active_record/connection_adapters/sqlite3_adapter.rb:225:in `block in execute'
    /home/xhire/.bundler/ruby/2.2.0/rails-81f4a7dce42e/activerecord/lib/active_record/connection_adapters/abstract_adapter.rb:547:in `block in log'
    /home/xhire/.bundler/ruby/2.2.0/rails-81f4a7dce42e/activesupport/lib/active_support/notifications/instrumenter.rb:21:in `instrument'
    /home/xhire/.bundler/ruby/2.2.0/rails-81f4a7dce42e/activerecord/lib/active_record/connection_adapters/abstract_adapter.rb:541:in `log'
    /home/xhire/.bundler/ruby/2.2.0/rails-81f4a7dce42e/activerecord/lib/active_record/connection_adapters/sqlite3_adapter.rb:225:in `execute'
    /home/xhire/.bundler/ruby/2.2.0/rails-81f4a7dce42e/activerecord/lib/active_record/connection_adapters/abstract/schema_statements.rb:1029:in `assume_migrated_upto_version'
    /home/xhire/.bundler/ruby/2.2.0/rails-81f4a7dce42e/activerecord/lib/active_record/schema.rb:52:in `define'
    /home/xhire/.bundler/ruby/2.2.0/rails-81f4a7dce42e/activerecord/lib/active_record/schema.rb:44:in `define'
    /home/xhire/tmp/ror5-db_failures/db/schema.rb:14:in `<top (required)>'
    /home/xhire/.bundler/ruby/2.2.0/rails-81f4a7dce42e/activesupport/lib/active_support/dependencies.rb:287:in `load'
    /home/xhire/.bundler/ruby/2.2.0/rails-81f4a7dce42e/activesupport/lib/active_support/dependencies.rb:287:in `block in load'
    /home/xhire/.bundler/ruby/2.2.0/rails-81f4a7dce42e/activesupport/lib/active_support/dependencies.rb:259:in `load_dependency'
    /home/xhire/.bundler/ruby/2.2.0/rails-81f4a7dce42e/activesupport/lib/active_support/dependencies.rb:287:in `load'
    /home/xhire/.bundler/ruby/2.2.0/rails-81f4a7dce42e/activerecord/lib/active_record/tasks/database_tasks.rb:223:in `load_schema'
    /home/xhire/.bundler/ruby/2.2.0/rails-81f4a7dce42e/activerecord/lib/active_record/tasks/database_tasks.rb:253:in `block in load_schema_current'
    /home/xhire/.bundler/ruby/2.2.0/rails-81f4a7dce42e/activerecord/lib/active_record/tasks/database_tasks.rb:292:in `block in each_current_configuration'
    /home/xhire/.bundler/ruby/2.2.0/rails-81f4a7dce42e/activerecord/lib/active_record/tasks/database_tasks.rb:291:in `each'
    /home/xhire/.bundler/ruby/2.2.0/rails-81f4a7dce42e/activerecord/lib/active_record/tasks/database_tasks.rb:291:in `each_current_configuration'
    /home/xhire/.bundler/ruby/2.2.0/rails-81f4a7dce42e/activerecord/lib/active_record/tasks/database_tasks.rb:252:in `load_schema_current'
    /home/xhire/.bundler/ruby/2.2.0/rails-81f4a7dce42e/activerecord/lib/active_record/railties/databases.rake:260:in `block (3 levels) in <top (required)>'
    /home/xhire/.bundler/ruby/2.2.0/rails-81f4a7dce42e/activerecord/lib/active_record/railties/databases.rake:264:in `block (3 levels) in <top (required)>'
    /home/xhire/.bundler/ruby/2.2.0/rails-81f4a7dce42e/railties/lib/rails/commands/rake_proxy.rb:13:in `block in run_rake_task'
    /home/xhire/.bundler/ruby/2.2.0/rails-81f4a7dce42e/railties/lib/rails/commands/rake_proxy.rb:10:in `run_rake_task'
    /home/xhire/.bundler/ruby/2.2.0/rails-81f4a7dce42e/railties/lib/rails/commands/commands_tasks.rb:51:in `run_command!'
    /home/xhire/.bundler/ruby/2.2.0/rails-81f4a7dce42e/railties/lib/rails/commands.rb:18:in `<top (required)>'
    bin/rails:4:in `require'
    bin/rails:4:in `<main>'
    SQLite3::SQLException: near ",": syntax error
    /home/xhire/.bundler/ruby/2.2.0/rails-81f4a7dce42e/activerecord/lib/active_record/connection_adapters/sqlite3_adapter.rb:225:in `block in execute'
    /home/xhire/.bundler/ruby/2.2.0/rails-81f4a7dce42e/activerecord/lib/active_record/connection_adapters/abstract_adapter.rb:547:in `block in log'
    /home/xhire/.bundler/ruby/2.2.0/rails-81f4a7dce42e/activesupport/lib/active_support/notifications/instrumenter.rb:21:in `instrument'
    /home/xhire/.bundler/ruby/2.2.0/rails-81f4a7dce42e/activerecord/lib/active_record/connection_adapters/abstract_adapter.rb:541:in `log'
    /home/xhire/.bundler/ruby/2.2.0/rails-81f4a7dce42e/activerecord/lib/active_record/connection_adapters/sqlite3_adapter.rb:225:in `execute'
    /home/xhire/.bundler/ruby/2.2.0/rails-81f4a7dce42e/activerecord/lib/active_record/connection_adapters/abstract/schema_statements.rb:1029:in `assume_migrated_upto_version'
    /home/xhire/.bundler/ruby/2.2.0/rails-81f4a7dce42e/activerecord/lib/active_record/schema.rb:52:in `define'
    /home/xhire/.bundler/ruby/2.2.0/rails-81f4a7dce42e/activerecord/lib/active_record/schema.rb:44:in `define'
    /home/xhire/tmp/ror5-db_failures/db/schema.rb:14:in `<top (required)>'
    /home/xhire/.bundler/ruby/2.2.0/rails-81f4a7dce42e/activesupport/lib/active_support/dependencies.rb:287:in `load'
    /home/xhire/.bundler/ruby/2.2.0/rails-81f4a7dce42e/activesupport/lib/active_support/dependencies.rb:287:in `block in load'
    /home/xhire/.bundler/ruby/2.2.0/rails-81f4a7dce42e/activesupport/lib/active_support/dependencies.rb:259:in `load_dependency'
    /home/xhire/.bundler/ruby/2.2.0/rails-81f4a7dce42e/activesupport/lib/active_support/dependencies.rb:287:in `load'
    /home/xhire/.bundler/ruby/2.2.0/rails-81f4a7dce42e/activerecord/lib/active_record/tasks/database_tasks.rb:223:in `load_schema'
    /home/xhire/.bundler/ruby/2.2.0/rails-81f4a7dce42e/activerecord/lib/active_record/tasks/database_tasks.rb:253:in `block in load_schema_current'
    /home/xhire/.bundler/ruby/2.2.0/rails-81f4a7dce42e/activerecord/lib/active_record/tasks/database_tasks.rb:292:in `block in each_current_configuration'
    /home/xhire/.bundler/ruby/2.2.0/rails-81f4a7dce42e/activerecord/lib/active_record/tasks/database_tasks.rb:291:in `each'
    /home/xhire/.bundler/ruby/2.2.0/rails-81f4a7dce42e/activerecord/lib/active_record/tasks/database_tasks.rb:291:in `each_current_configuration'
    /home/xhire/.bundler/ruby/2.2.0/rails-81f4a7dce42e/activerecord/lib/active_record/tasks/database_tasks.rb:252:in `load_schema_current'
    /home/xhire/.bundler/ruby/2.2.0/rails-81f4a7dce42e/activerecord/lib/active_record/railties/databases.rake:260:in `block (3 levels) in <top (required)>'
    /home/xhire/.bundler/ruby/2.2.0/rails-81f4a7dce42e/activerecord/lib/active_record/railties/databases.rake:264:in `block (3 levels) in <top (required)>'
    /home/xhire/.bundler/ruby/2.2.0/rails-81f4a7dce42e/railties/lib/rails/commands/rake_proxy.rb:13:in `block in run_rake_task'
    /home/xhire/.bundler/ruby/2.2.0/rails-81f4a7dce42e/railties/lib/rails/commands/rake_proxy.rb:10:in `run_rake_task'
    /home/xhire/.bundler/ruby/2.2.0/rails-81f4a7dce42e/railties/lib/rails/commands/commands_tasks.rb:51:in `run_command!'
    /home/xhire/.bundler/ruby/2.2.0/rails-81f4a7dce42e/railties/lib/rails/commands.rb:18:in `<top (required)>'
    bin/rails:4:in `require'
    bin/rails:4:in `<main>'
    Tasks: TOP => db:schema:load
    (See full trace by running task with --trace)

### System configuration
**Rails version**: beta3/edge (81f4a7d)

**Ruby version**: 2.2.3p173

I've tested it with Rails 4.2.6 too, but everything works fine there.

**Comment by yahonda** [comment]
I think you need to use  SQLite3 3.7.11 or higher. Refer #24288

**Comment by vipulnsward** [comment]
Closing as per https://github.com/rails/rails/issues/24677#issuecomment-213034090 
as this needs SQLite  3.7.11+ . See also- http://www.sqlite.org/releaselog/3_7_11.html

**Comment by xHire** [comment]
Oh, good to know. Thank you both!
