### ISSUE TITLE
Adding includes to a scoped has_many through produces SQL missing table in FROM clause

### ISSUE THREAD

**Issue by speckins** [rails/rails#24674]
Test case available [here](https://gist.github.com/speckins/b27e112d0062039778f7772905b96559).

### Steps to reproduce
I ran across this behavior when attempting to create a scoped has_many through association.  The association itself works as expected when called on an instance.  However, if I attempt to eager load the scoped association using includes, the produced SQL references a table in the WHERE clause that is not present in the FROM clause.

```ruby
# User <- Post <- Comment -> CommentType

class User < ActiveRecord::Base
  has_many :posts

  has_many :comments, :through => :posts
  # This is the problem association:
  has_many :funny_comments, -> { funny }, :through => :posts, :source => :comments
end

class Post < ActiveRecord::Base
  has_many :comments
end

class Comment < ActiveRecord::Base
  belongs_to :comment_type

  scope :funny, -> { joins(:comment_type).merge(CommentType.funny) }
  # This fails, too, btw:
  #scope :funny, -> { joins(:comment_type).where comment_types: {comment_type: 'funny'} }
end

class CommentType < ActiveRecord::Base
  scope :funny, -> { where :comment_type => 'funny' }
end
```

```ruby
user = User.first
user.funny_comments # This works
User.includes(:funny_comments).limit(2) # This fails
```

**ActiveRecord::StatementInvalid: SQLite3::SQLException: no such column: comment_types.comment_type: SELECT "posts".*, "posts"."id" AS t0_r0, "posts"."user_id" AS t0_r1, "comments"."id" AS t1_r0, "comments"."post_id" AS t1_r1, "comments"."comment_type_id" AS t1_r2 FROM "posts" LEFT OUTER JOIN "comments" ON "comments"."post_id" = "posts"."id" WHERE "comment_types"."comment_type" = ? AND "posts"."user_id" IN (1)**

### System configuration
**Rails version**:  4.2.6, 5.0.0-beta3

**Ruby version**: 2.2.1, 2.2.4
**Databases**: Postgres, SQLite3

If anyone can suggest a workaround in the meantime, I'd appreciate it.

**Comment by vipulnsward** [comment]
See references on http://guides.rubyonrails.org/active_record_querying.html

You need to make use of references to achieve these kind of queries.
Here's how you could do it https://gist.github.com/vipulnsward/c328295040160ac4e0a6842128cde0fc

**Comment by speckins** [comment]
Sorry if this was a non-issue.  I actually did try #references before reporting this, but I must not have used it correctly (the documentation leaves something to be desired for anything more than the trivial case).

@vipulnsward Thanks for the example, but you've changed the schema.  Your modified scope still doesn't work with the schema I originally posted.  These are not my real classes, but the relationships are preserved.  Assume that "comment_types" is a reference table with a small number of rows.

I still can't get eager loading working with this scoped association.

**Comment by vipulnsward** [comment]
`has_many :funny_comments, -> { funny }, :through => :posts, :source => :comments` will evaluate comment_types(through funny scope) on posts model. Unless you have relation setup it will fail.

**Comment by speckins** [comment]
@vipulnsward The Post model shouldn't be associated with comment_types; only Comment has a comment_type_id.

Like this:

    User <- Post <- Comment -> CommentType

Not this:

    User <- Post <- Comment
                 <- CommentType


Eager loading kind of works if I add #includes to the scope, but it doesn't require #references.

```ruby
class User
  has_many :funny_comments, -> {
    funny.includes(:comments => :comment_type)
  }, :through => :posts, :source => :comments
  # ...
end

# This would no longer raise an error
User.includes(:funny_comments)
```
I say "kind of works" because it's loading `:comment_type`, which I don't really want because I'm not going to use it, and I already know what it is because that's the point of the scope.  In my actual application, this is going to load a lot of extra data which I don't need.

Is #references useful for tables you don't actually want eager loaded?
