### ISSUE TITLE
installing rails on kubuntu 16.04 problem

### ISSUE THREAD

**Issue by ddpdevang** [rails/rails#24691]
devang@devang-Presario-CQ57-Notebook-PC:~$ sudo gem install rails
Building native extensions.  This could take a while...
ERROR:  Error installing rails:
        ERROR: Failed to build gem native extension.

    current directory: /var/lib/gems/2.3.0/gems/nokogiri-1.6.7.2/ext/nokogiri
/usr/bin/ruby2.3 -r ./siteconf20160423-17360-1iu6t3v.rb extconf.rb
mkmf.rb can't find header files for ruby at /usr/lib/ruby/include/ruby.h

extconf failed, exit code 1

Gem files will remain installed in /var/lib/gems/2.3.0/gems/nokogiri-1.6.7.2 for inspection.
Results logged to /var/lib/gems/2.3.0/extensions/x86_64-linux/2.3.0/nokogiri-1.6.7.2/gem_make.out

**Comment by jeremy** [comment]
```bash
sudo apt-get install ruby2.3-dev
```
