### ISSUE TITLE
(Rails 5.0.0.beta3) Collection caching showing weird behavior (no read_multi in some cases, NoMethodError in others)

### ISSUE THREAD

**Issue by cannikin** [rails/rails#24692]
Tried to enable the read_multi function of collection rendering:

```erb
# index.html.erb
...
<%= render 'items', :items => @list.items %>
...

# _items.html.erb
<%= render items, :cached => true %>

# _item.html.erb
<% cache item do %>
  ...
<% end %>
```

The page renders correctly but I'm not seeing any read_multi in the logs, just individual cache hits (file paths are different in this app than the example code above):

      Cache digest for app/views/application/_page_tile_toolbox.html.erb: afb213b860619a6f79ed4fc49b2a76d8
      Cache digest for app/views/dashboard/profiles/_creative.html.erb: a7eaee609655c2793c5c5cf0ccf93ad9
    Cache read: views/profile/creatives/5-20160422171844051161/a7eaee609655c2793c5c5cf0ccf93ad9
    Read fragment views/profile/creatives/5-20160422171844051161/a7eaee609655c2793c5c5cf0ccf93ad9 (0.7ms)
    Cache read: views/profile/creatives/11-20160422171906464954/a7eaee609655c2793c5c5cf0ccf93ad9
    Read fragment views/profile/creatives/11-20160422171906464954/a7eaee609655c2793c5c5cf0ccf93ad9 (0.6ms)
    Cache read: views/profile/creatives/15-20160422171918382337/a7eaee609655c2793c5c5cf0ccf93ad9
    Read fragment views/profile/creatives/15-20160422171918382337/a7eaee609655c2793c5c5cf0ccf93ad9 (0.6ms)

The bigger problem occurs when specifying the partial location to use for rendering the collection:

```erb
# index.html.erb
...
<%= render :partial => 'shared/items', :collection => @list.items, :cached => true %>
...
```

Now I get:

    NoMethodError - undefined method `read_multi' for nil:NilClass
    Did you mean?  readline:
      actionview (5.0.0.beta3) lib/action_view/renderer/partial_renderer/collection_caching.rb:16:in `cache_collection_render'
      actionview (5.0.0.beta3) lib/action_view/renderer/partial_renderer.rb:326:in `block in render_collection'
      actionview (5.0.0.beta3) lib/action_view/renderer/abstract_renderer.rb:42:in `block in instrument'

I was able to fix this one with the following initializer:

```ruby
# config/initializers/collection_cache.rb
if Rails.application.config.action_controller.perform_caching
  ActionView::PartialRenderer.collection_cache = Rails.cache
else
  ActionView::PartialRenderer.collection_cache = ActiveSupport::Cache::NullStore.new
end
```

      Cache digest for app/views/dashboard/profiles/_creative.html.erb: c822e2dfacd675928f390bd337eb91af
    Cache read_multi: ["views/profile/creatives/5-20160422171844051161/c822e2dfacd675928f390bd337eb91af", "views/profile/creatives/11-20160422171906464954/c822e2dfacd675928f390bd337eb91af", "views/profile/creatives/15-20160422171918382337/c822e2dfacd675928f390bd337eb91af"]

But according to the comment at the top of https://github.com/rails/rails/blob/master/actionview/lib/action_view/renderer/partial_renderer/collection_caching.rb#L7 something similar should be happening in a Railtie somewhere?

This does NOT fix the first case (standard `render @collection` syntax): it still performs multiple reads every time.

**Comment by prathamesh-sonpatki** [comment]
This seems to be same issue as https://github.com/rails/rails/issues/24132. Taking a look at it.

**Comment by prathamesh-sonpatki** [comment]
@cannikin Related to the error ` undefined method `read_multi' for nil:NilClass`, are you using `rails-controller-testing` gem? If yes, can you put what version you are using.

**Comment by cannikin** [comment]
@prathamesh-sonpatki Nope, full Gemfile here: https://gist.github.com/cannikin/12ad10d1fb1a3eec74c8929c1adf08e7

**Comment by kaspth** [comment]
Collection caching only works with the expanded render form, so that's why it worked with:

```ruby
<%= render partial: 'shared/items', collection: @list.items, cached: true %>
```

(The is a reason for that though I can't remember at the moment.)

There's got to be some gem that's not using load hooks properly. Can you try removing a gem one at a time and suss out which one is the culprit? Thanks for the detailed report! 😁

**Comment by kaspth** [comment]
Should be fixed at https://github.com/rails/rails/pull/24752. Thanks!
