### ISSUE TITLE
FlashHash#delete returns self

### ISSUE THREAD

**Issue by printercu** [rails/rails#24738]
Should it be fixed to be more Hash-like and return deleted value?

https://github.com/rails/rails/blob/master/actionpack/lib/action_dispatch/middleware/flash.rb#L181

**Comment by maclover7** [comment]
👍 This makes sense to me -- if the class is called `FlashHash` (`Hash` is in the name!) and attempts to imitate `Hash`'s behavior, then it should close the loop and return the deleted value. Working on a PR for this.

**Comment by maclover7** [comment]
Opened #24744

**Comment by rafaelfranca** [comment]
I don't think we need to change this. The FlashHash API doesn't needs to be compatible with Hash API.

**Comment by printercu** [comment]
This is what everybody expect. Returning `self` is useless in this place.

**Comment by rafaelfranca** [comment]
It may be useless but it is what we have now and changing that may break people application and I prefer stability in this case

**Comment by printercu** [comment]
:( I've reported before 5.0 was released. Should we add it to 6.0 wishlist?

**Comment by rafaelfranca** [comment]
I mean, I'd not change this behavior at all in any release. I don't think it is worth.
