### ISSUE TITLE
redirect_to with turbolinks option failing

### ISSUE THREAD

**Issue by micpringle** [rails/rails#24740]
I have an issue with cross domain redirects and Turbolinks not working as expected. 

If I add `'data-turbolinks' => false` to the HTML link that triggers the redirect, then the redirection happens fine and no errors are printed to the JavaScript console. However, if I remove that data tag, and instead add the `turbolinks: false` option to `redirect_to`, then I get the initial XHR request, followed by the `No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin ... is therefore not allowed access.` printed to the JavaScript console, followed by the HTML redirection request.

I was under the impression (_from reading the docs_) that adding `turbolinks: false` to a `redirect_to` call would cause the browser to redirect normally, and therefore not print the `Access-Control-Allow-Origin` error to the log.

### Steps to reproduce

```ruby
class Controller < ApplicationController
  def new
    redirect_to('http://google.com', turbolinks: false)
  end
end
```

### Expected behavior

The response served to the browser would cause it to redirect normally and not attempt to load the contents of the redirection via XHR.

### Actual behavior

An attempt to redirect via XHR is triggered, followed by...

```
No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin ... is therefore not allowed access.
```

...followed by a normal redirection.

### System configuration
**Rails version**: Rails 5.0.0.beta3

**Ruby version**: ruby 2.3.0p0 (2015-12-25 revision 53290) [x86_64-darwin15]

**Comment by maclover7** [comment]
Where do you see this in the docs? Also, it might be better to open up this issue directly on Turbolinks' issue tracker (https://github.com/turbolinks/turbolinks-rails/issues/new)

**Comment by micpringle** [comment]
@maclover7,

Apologies as I should have been clearer. As there is no README over on [turbolinks/turbolinks-rails](https://github.com/turbolinks/turbolinks-rails), I've been using the README on [turbolinks/turbolinks-classic](https://github.com/turbolinks/turbolinks-classic/blob/master/README.md), specifically the section titled **Server-side partial replacement**.

I fully appreciate this README is from an older version than the one bundled with Rails 5, but since the new version doesn't have a README there's not much else to go on. :]

I'll raise an issue over on [turbolinks/turbolinks-rails](https://github.com/turbolinks/turbolinks-rails).

**Comment by micpringle** [comment]
https://github.com/turbolinks/turbolinks-rails/issues/7

I've also added a little more context.

**Comment by jeffperrin** [comment]
The main repo (and readme) for Turbolinks is located here: https://github.com/turbolinks/turbolinks

I'm fairly sure that server side partial replacement is *not* in turbolinks 5, which is included with the rails 5 betas.

**Comment by jeremy** [comment]
https://github.com/turbolinks/turbolinks-rails/issues/7#issuecomment-215890158

(This is expected: using `turbolinks: false` in a redirect for an XHR request redirects the _XHR response_, not the browser.)
