### ISSUE TITLE
ActiveRecord::RecordInvalid: Validation failed when running rake db:seed instead of rails db:seed

### ISSUE THREAD

**Issue by ctilley83** [rails/rails#24757]
### Steps to reproduce

Supposedly in Rails 5 you can run either rake or rails to perform db: operations. For some reason when you do `rake db:seed` it throws the error below. However if you do `rails db:seed` it works. This seems to only affect nested attributes

using `rake db:drop`, `rake db:create`, or `rake db:migrate` WORKS

using `rake db:seed`, `rake db:reset`, or `rake db:setup` FAILS

Assuming the above 3 failing commands also run `rake db:seed` at some point in their execution
### Expected behavior

`rake db:seed` would populate database
### Actual behavior

`ActiveRecord::RecordInvalid: Validation failed: Website statistics websites must exist #`
### System configuration

**Rails version**: rails 5.0 beta 3

**Ruby version**: ruby-2.3.0

**Comment by ctilley83** [comment]
more unexpected behavior.  Now `rails db:reset` works. `rails db:seed` fails, `rake db:seed` fails

I tried dropping the database, creating the database, migrating the database, and then seeding the database.  Still getting the inconsistent errors where only `rails db:reset` works now.

The randomness is making it hard to troubleshoot.  Are there caches I need to clear?

**Comment by ctilley83** [comment]
ActiveRecord::RecordInvalid: Validation failed: Website statistics websites must exist
/Users/ctilley/.rvm/gems/ruby-2.3.0/gems/activerecord-5.0.0.beta3/lib/active_record/validations.rb:78:in `raise_validation_error'
/Users/ctilley/.rvm/gems/ruby-2.3.0/gems/activerecord-5.0.0.beta3/lib/active_record/validations.rb:50:in `save!'
/Users/ctilley/.rvm/gems/ruby-2.3.0/gems/activerecord-5.0.0.beta3/lib/active_record/attribute_methods/dirty.rb:30:in `save!'
/Users/ctilley/.rvm/gems/ruby-2.3.0/gems/activerecord-5.0.0.beta3/lib/active_record/transactions.rb:324:in `block in save!'
/Users/ctilley/.rvm/gems/ruby-2.3.0/gems/activerecord-5.0.0.beta3/lib/active_record/transactions.rb:395:in `block in with_transaction_returning_status'
/Users/ctilley/.rvm/gems/ruby-2.3.0/gems/activerecord-5.0.0.beta3/lib/active_record/connection_adapters/abstract/database_statements.rb:230:in `block in transaction'
/Users/ctilley/.rvm/gems/ruby-2.3.0/gems/activerecord-5.0.0.beta3/lib/active_record/connection_adapters/abstract/transaction.rb:189:in `within_new_transaction'
/Users/ctilley/.rvm/gems/ruby-2.3.0/gems/activerecord-5.0.0.beta3/lib/active_record/connection_adapters/abstract/database_statements.rb:230:in `transaction'
/Users/ctilley/.rvm/gems/ruby-2.3.0/gems/activerecord-5.0.0.beta3/lib/active_record/transactions.rb:211:in `transaction'
/Users/ctilley/.rvm/gems/ruby-2.3.0/gems/activerecord-5.0.0.beta3/lib/active_record/transactions.rb:392:in `with_transaction_returning_status'
/Users/ctilley/.rvm/gems/ruby-2.3.0/gems/activerecord-5.0.0.beta3/lib/active_record/transactions.rb:324:in `save!'
/Users/ctilley/.rvm/gems/ruby-2.3.0/gems/activerecord-5.0.0.beta3/lib/active_record/persistence.rb:51:in `create!'
/Users/ctilley/Development/website_test_site/db/seeds.rb:71:in `block in <top (required)>'
/Users/ctilley/.rvm/gems/ruby-2.3.0/gems/nokogiri-1.6.7.2/lib/nokogiri/xml/node_set.rb:187:in `block in each'
/Users/ctilley/.rvm/gems/ruby-2.3.0/gems/nokogiri-1.6.7.2/lib/nokogiri/xml/node_set.rb:186:in `upto'
/Users/ctilley/.rvm/gems/ruby-2.3.0/gems/nokogiri-1.6.7.2/lib/nokogiri/xml/node_set.rb:186:in `each'
/Users/ctilley/Development/website_test_site/db/seeds.rb:21:in `<top (required)>'
/Users/ctilley/.rvm/gems/ruby-2.3.0/gems/activesupport-5.0.0.beta3/lib/active_support/dependencies.rb:296:in `load'
/Users/ctilley/.rvm/gems/ruby-2.3.0/gems/activesupport-5.0.0.beta3/lib/active_support/dependencies.rb:296:in `block in load'
/Users/ctilley/.rvm/gems/ruby-2.3.0/gems/activesupport-5.0.0.beta3/lib/active_support/dependencies.rb:268:in `load_dependency'
/Users/ctilley/.rvm/gems/ruby-2.3.0/gems/activesupport-5.0.0.beta3/lib/active_support/dependencies.rb:296:in `load'
/Users/ctilley/.rvm/gems/ruby-2.3.0/gems/railties-5.0.0.beta3/lib/rails/engine.rb:549:in `load_seed'
/Users/ctilley/.rvm/gems/ruby-2.3.0/gems/activerecord-5.0.0.beta3/lib/active_record/tasks/database_tasks.rb:265:in `load_seed'
/Users/ctilley/.rvm/gems/ruby-2.3.0/gems/activerecord-5.0.0.beta3/lib/active_record/railties/databases.rake:196:in `block (2 levels) in <top (required)>'
/Users/ctilley/.rvm/gems/ruby-2.3.0/gems/railties-5.0.0.beta3/lib/rails/commands/rake_proxy.rb:13:in `block in run_rake_task'
/Users/ctilley/.rvm/gems/ruby-2.3.0/gems/railties-5.0.0.beta3/lib/rails/commands/rake_proxy.rb:10:in `run_rake_task'
/Users/ctilley/.rvm/gems/ruby-2.3.0/gems/railties-5.0.0.beta3/lib/rails/commands/commands_tasks.rb:51:in `run_command!'
/Users/ctilley/.rvm/gems/ruby-2.3.0/gems/railties-5.0.0.beta3/lib/rails/command.rb:20:in `run'
/Users/ctilley/.rvm/gems/ruby-2.3.0/gems/railties-5.0.0.beta3/lib/rails/commands.rb:18:in `<top (required)>'
/Users/ctilley/Development/website_test_site/bin/rails:9:in `require'
/Users/ctilley/Development/website_test_site/bin/rails:9:in `<top (required)>'
/Users/ctilley/.rvm/gems/ruby-2.3.0/gems/spring-1.7.1/lib/spring/client/rails.rb:28:in `load'
/Users/ctilley/.rvm/gems/ruby-2.3.0/gems/spring-1.7.1/lib/spring/client/rails.rb:28:in `call'
/Users/ctilley/.rvm/gems/ruby-2.3.0/gems/spring-1.7.1/lib/spring/client/command.rb:7:in `call'
/Users/ctilley/.rvm/gems/ruby-2.3.0/gems/spring-1.7.1/lib/spring/client.rb:30:in `run'
/Users/ctilley/.rvm/gems/ruby-2.3.0/gems/spring-1.7.1/bin/spring:49:in `<top (required)>'
/Users/ctilley/.rvm/gems/ruby-2.3.0/gems/spring-1.7.1/lib/spring/binstub.rb:11:in `load'
/Users/ctilley/.rvm/gems/ruby-2.3.0/gems/spring-1.7.1/lib/spring/binstub.rb:11:in `<top (required)>'
/Users/ctilley/Development/website_test_site/bin/spring:13:in `require'
/Users/ctilley/Development/website_test_site/bin/spring:13:in `<top (required)>'
bin/rails:3:in `load'
bin/rails:3:in `<main>'
Tasks: TOP => db:seed

**Comment by maclover7** [comment]
Can you please provide a sample application that replicates the error you are seeing?

**Comment by ctilley83** [comment]
It might take me a day.  This is from a production app I'm writing.  I'll write a simple one soon.

**Comment by akostadinov** [comment]
@ctilley83 , did you figure it out? For me seeding fails with validation error if I have `config.load_defaults 5.1` in `application.rb` and works otherwise. And comparing config values yields no related differences in fact. So it is very strange for me.
