### ISSUE TITLE
Add config.assets.digest_exclusions

### ISSUE THREAD

**Issue by 3den** [rails/rails#24750]
### Steps to reproduce

This problem was solved a long time ago https://github.com/rails/rails/issues/2294 but seems like the fix have been removed.

I am installing frontend libs with bower under `vendor/assets/bower_components` so moving stuff to public would be very hacky.  Is there anyway that we can skip fingerprinting just on selected assets?

```ruby
# I tried setting the setting `digest_exclusions` but this config is no longer available.
config.assets.digest_exclusions += %w(
   salesforce-lightning-design-system/assets/**/*
);
```

### Expected behavior

We should be able to skip the digest fingerprinting for selected assets.

### Actual behavior

Currently the digest setting can only be all or nothing (`config.assets.digest = true | false`).

### System configuration
**Rails version: 5.0beta

**Ruby version: 2.2

**Comment by vipulnsward** [comment]
Closing in favour of https://github.com/rails/sprockets-rails/issues/49#issuecomment-46010763 which has detailed discussion over this.
