### ISSUE TITLE
Custom fonts exist in production buts says "not found"

### ISSUE THREAD

**Issue by Faisal-nfl** [rails/rails#24754]
I deployed an rails(4.2.4) app on Digital Ocean which was working fine in development mode.
But on server everything work except fonts, it says 
`Failed to load resource: the server responded with a status of 404 (Not Found)`
the path it searches for is 
`http://Server_IP/assets/raleway-bold.woff2` 
but when I actual click on the path it open the fonts file at exactly same path its pointing with "not found " error
Whats wrong with it

**Comment by maclover7** [comment]
Can you please provide a sample application that replicates the error you are seeing?

**Comment by rafaelfranca** [comment]
Please use the mailing list or StackOverflow for questions/help, where a wider community will be able to help you. We reserve the issues tracker for issues only.
