### ISSUE TITLE
Timeout parameter not working for oracle database

### ISSUE THREAD

**Issue by KKirad** [rails/rails#24768]
Below is the configuration in the database.yml file:
development:
  adapter: oracle_enhanced
  host: 10.10.10.58
  port: 1521
  database: TUTSDB
  username: tutsadmin
  password: Tuts1234
  encoding: utf8
  timeout: 15000

**Rails version**: 4.2.5
**Ruby version** :  ruby 2.0.0p648

**Actual Result** :
We get the below error:
**(ActiveRecord::ConnectionTimeoutError) "could not obtain a database connection within 5 seconds (waited 5.000144774 seconds)**

**Expected Result** : 
It should wait for 15 sec and then throw the above error.

We have used the gem activerecord-oracle_enhanced-adapter (1.6.6) to connect to the DB.

**Comment by maclover7** [comment]
Can you please provide a sample application that replicates the error you are seeing?

Also, it might be better to file an issue with the adapter you are using with your application.

**Comment by rafaelfranca** [comment]
Rails don't have support to oracle out of the box. You should open an issue in the activerecord-oracle_enhanced-adapter gem.
