### ISSUE TITLE
Send array over ActionCable channel

### ISSUE THREAD

**Issue by kayakyakr** [rails/rails#24763]
### Problem

This has never worked: if you want to send an array back to the default receive method of a channel, you wind up throwing a cannot convert to int error.

#### Channel

```Ruby
class NotificationsChannel < ApplicationCable::Channel
  def subscribed
    stream_from params[:id]
  end

  def receive(data)
    ActionCable.server.broadcast params[:id], data
  end
end
```

#### Client
```Javascript
var channel = socket.subscriptions.create({channel: channel_id, id: notifier_id});
channel.send([{message: "this errors!"}, {message: "another message!"])
```

The error is `[TypeError - no implicit conversion of String into Integer]: /lib/action_cable/channel/base.rb:230`

### Proposed fix

```Ruby
module ActionCable
  module Channel
    class Base

      #line 229
      def extract_action(data)
        (data.is_a?(Hash) && data['action'].presence || :receive).to_sym
      end

      #line 247
      def action_signature(action, data)
        "#{self.class.name}##{action}".tap do |signature|
          if (arguments = data.is_a?(Hash) ? data.except('action') : data).any?
            signature << "(#{arguments.inspect})"
          end
        end
      end
    end
  end
end
```

Clean up how you like, this was quick-and-dirty monkey patching on my end.

**Comment by vipulnsward** [comment]
Would you like to convert this to a PR, and add tests to it?

**Comment by kayakyakr** [comment]
I'll see if I can carve out a bit of time to do a PR.

**Comment by maclover7** [comment]
Can you post more of the backtrace for the error? This would help to aid in figuring out what is causing this bug. :)

**Comment by jeremy** [comment]
The message data is expected to be a JSON Object. Supporting Arrays would be welcome, too, but it's not a bug. PR + tests welcome to turn this into a full-fledged feature 😊

**Comment by kayakyakr** [comment]
I expected it to accept valid JSON, not just a JSON object.

Never really called it a bug on my end, but will submit a PR for this if I can pull out some time this weekend.

**Comment by jeremy** [comment]
Thanks @kayakyakr!
