### ISSUE TITLE
bound_attributes needs support to change limit and offset orders

### ISSUE THREAD

**Issue by yahonda** [rails/rails#24775]
### Steps to reproduce
* Update Gemfile to support https://github.com/rails/arel/pull/422
```ruby
gem 'arel', github: 'yahonda/arel', branch: 'v700_oracle12'
```
* Execute this ActiveRecord unit test
```ruby
$ cd activerecord
$ ARCONN=oracle bundle exec ruby -W -w -Ilib:test test/cases/calculations_test.rb -n test_should_limit_calculation_with_offset
... snip ...

  1) Failure:
CalculationsTest#test_should_limit_calculation_with_offset [test/cases/calculations_test.rb:164]:
Expected: [2, 6]
  Actual: [6]

1 runs, 1 assertions, 1 failures, 0 errors, 0 skips
```

### Expected behavior
This unit test should finish successfully. 

### Actual behavior
Got an failure as shown above.

This is due to incorrect bind value order for Oracle database. Taking a look at `debug.log` for this sql statement, showing  `OFFSET :a1 ROWS FETCH FIRST :a2 ROWS ONLY`. It expects a bind value for `offset` comes first then `limit` next. Actually `limit` comes first then `offset` as it shows `[["LIMIT", 2], ["OFFSET", 1]`.

- Oracle
```sql
SELECT  SUM("ACCOUNTS"."CREDIT_LIMIT") AS sum_credit_limit, "ACCOUNTS"."FIRM_ID" AS accounts_firm_id FROM "ACCOUNTS" WHERE (firm_id IS NOT NULL) GROUP BY "ACCOUNTS"."FIRM_ID" ORDER BY firm_id OFFSET :a1 ROWS FETCH FIRST :a2 ROWS ONLY  [["LIMIT", 2], ["OFFSET", 1]]
```
For other databases such as PostgreSQL, this order works.
- PostgreSQL
```sql
SELECT  SUM("accounts"."credit_limit") AS sum_credit_limit, "accounts"."firm_id" AS accounts_firm_id FROM "accounts" WHERE (firm_id IS NOT NULL) GROUP BY "accounts"."firm_id" ORDER BY firm_id LIMIT $1 OFFSET $2  [["LIMIT", 2], ["OFFSET", 1]]
```

### Reference
- [Use a bind param for `LIMIT` and `OFFSET`] (https://github.com/rails/rails/commit/574f255629a45cd67babcfb9bb8e163e091a53b8) introduces this behavior. In `bound_attributes` method limit comes first then offset next.

- [Support Oracle 12c top-N query](https://github.com/rails/arel/pull/337)
This pull request has two commits, [the first one](https://github.com/rails/arel/pull/337/commits/8d04c28b619212f99e6ce534f75ebda59bb200a1) introduces `visit_Arel_Nodes_SelectOptions` to allow each visitor have their own `limit`, `offset`.  [the second one](https://github.com/rails/arel/pull/337/commits/0e1427e917a4e47dce9f02ad9309600073622c73) implements `Oracle12` visitor whose `visit_Arel_Nodes_SelectOptions` executes `offset` comes first then `limit` next

* Diag commit
https://github.com/yahonda/rails/commit/a22ee338d302d47c2f9b4c691b4254bb4b4e96d7
This commit just works for Oracle database, it breaks other database adapter behavior. As of right now I do not have good idea how to handle this.

### System configuration
**Rails version**:
- Rails master branch
- Arel 7.0.0 + https://github.com/rails/arel/pull/422
- Oracle enhanced adapter rails5 branch
- Oracle database 12c 12.1.0.2

**Ruby version**:
```
ruby 2.3.1p112 (2016-04-26 revision 54768) [x86_64-linux]
```

**Comment by maclover7** [comment]
Do any of the other databases (MySQL, SQLite3) have errors if you change the behavior?

**Comment by yahonda** [comment]
Unfortunately it causes failure for all bundled adapters, sqlite3, mysql2 and postgresql all failures are same.
Here is the output of postgresql adapter test result including the sql statement executed.
```ruby
$ ARCONN=postgresql bundle exec ruby -W -w -Ilib:test test/cases/calculations_test.rb -n test_should_limit_calculation_with_offset
Using postgresql
Run options: -n test_should_limit_calculation_with_offset --seed 52209

# Running:

F

Finished in 0.145462s, 6.8747 runs/s, 6.8747 assertions/s.

  1) Failure:
CalculationsTest#test_should_limit_calculation_with_offset [test/cases/calculations_test.rb:164]:
Expected: [2, 6]
  Actual: [6]

1 runs, 1 assertions, 1 failures, 0 errors, 0 skips
$
```


```sql
SELECT  SUM("accounts"."credit_limit") AS sum_credit_limit, "accounts"."firm_id" AS accounts_firm_id FROM "accounts" WHERE (firm_id IS NOT NULL) GROUP BY "accounts"."firm_id" ORDER BY firm_id LIMIT $1 OFFSET $2  [["OFFSET", 1], ["LIMIT", 2]]
```

PostgreSQL (and all other bundled adapter databases) expectes `limit` comes first, then `offset` but bind value orders are not.

**Comment by maclover7** [comment]
Hmm, I'd say that it would be better for the Oracle adapter to adopt to the way things are right now -- rather have one broken adapter than have all of Active Record's in tree adapters broken. Marking this as `needs feedback`

**Comment by sgrif** [comment]
Lol a 20 year old RBDMS is not going to change its SQL syntax to support Rails. This is a bug we need to address. I am currently packing up my house and moving but I will deal with this during RailsConf.

**Comment by yahonda** [comment]
Thanks for the feedback. I'm also attending RailsConf!

**Comment by metaskills** [comment]
Hey Sean, thanks for asking! 

I've yet to start the Rails 5 work so not too sure so I just did a grok of 574f255 and this pull request. I do think we would have hit the same issue since our windowing is with the same SQL and hence we OFFSET and LIMIT. Should we just implement `bound_attributes` in our adapters and call `super.reverse`?

**Comment by jeremy** [comment]
(Shifting milestone a tad. High priority, but we haven't looked and core adapters are good to go for release candidate.)

**Comment by yahonda** [comment]
No problem about changing milestone to 5.0.1. Thanks for the update.
