### ISSUE TITLE
Rails 5 beta4. Can't start 2 servers actioncable and rails server.

### ISSUE THREAD

**Issue by fellz** [rails/rails#24789]
Hi 
Got this error "A server is already running" when trying to run **bin/cable** and **rails server**. I guess i can't run 2 versions of puma. Rails 5 beta4, Ruby 2.3.0, Ubuntu 14.04. 

``` bin/cable ```

and then

```
rails s
=> Booting Puma
=> Rails 5.0.0.beta4 application starting in development on http://localhost:3000
=> Run `rails server -h` for more startup options
Puma starting in single mode...
* Version 3.4.0 (ruby 2.3.0-p0), codename: Owl Bowl Brawl
* Min threads: 5, max threads: 5
* Environment: development
* Listening on tcp://localhost:3000
Use Ctrl-C to stop
* Restarting...
=> Booting Puma
=> Rails 5.0.0.beta4 application starting in development on http://localhost:3000
=> Run `rails server -h` for more startup options
A server is already running. Check /home/goracio/code/rails/trambo/tmp/pids/server.pid.
Exiting
```

**Comment by vipulnsward** [comment]
What are the contents of your `bin/cable`, something like https://github.com/rails/rails/tree/master/actioncable#running-the-cable-server ?

**Comment by jeremy** [comment]
You're running the servers on the same port.

The cable server can run on the same server as your app now, so no need for separate servers in dev. Check it out: https://github.com/rails/rails/tree/master/actioncable#in-app

**Comment by fellz** [comment]
@vipulnsward Yep i took cable config there. 

```
# cable/config.ru
require ::File.expand_path('../../config/environment', __FILE__)
Rails.application.eager_load!

run ActionCable.server
```

**Comment by vipulnsward** [comment]
@fellz I believe as Jeremy mentioned your config.ru has the same port.

**Comment by fellz** [comment]
@vipulnsward no, this is not the case 

```
#!/bin/bash
bundle exec puma -p 28080 cable/config.ru

```

**Comment by vipulnsward** [comment]
Cool, can you create a sample application to recreate this issue?

**Comment by fellz** [comment]
nothing special here, ```rails new myapp```, make ```cable/config.ru``` and then cable in bin and problem still the same...

**Comment by fellz** [comment]
@vipulnsward if i run ```bundle exec puma -p 3000```
server is running after couple of restarts !

```
bundle exec puma -p 3000
Puma starting in single mode...
* Version 3.4.0 (ruby 2.3.0-p0), codename: Owl Bowl Brawl
* Min threads: 5, max threads: 5
* Environment: development
* Listening on tcp://0.0.0.0:3000
Use Ctrl-C to stop
* Restarting...
Puma starting in single mode...
* Version 3.4.0 (ruby 2.3.0-p0), codename: Owl Bowl Brawl
* Min threads: 5, max threads: 5
* Environment: development
* Inherited tcp://0.0.0.0:3000
Use Ctrl-C to stop
```

**Comment by jeremy** [comment]
Using the same pidfile, then? Troubleshooting your local config is tough without an exact reproduction of what you're doing, however simple it seems.

And again, you don't need to run a separate cable server for local dev.

**Comment by mathieujobin** [comment]
i noticed in beta1, `config/routes.rb` contain those lines commented out
```
# Serve websocket cable requests in-process
#mount ActionCable.server => '/cable'
```

and in the tutorial @dhh made, he uncommented it out.
but in beta4 those two lines are no longer present
and I tried without, and everything works...

so maybe they are no longer no necessary?
this may not be the issue here. but I thought about it when I saw the line above...

**Comment by mathieujobin** [comment]
@fellz see that line at the end of your description

`A server is already running. Check /home/goracio/code/rails/trambo/tmp/pids/server.pid.`

try running your 2nd one like this `rails s -p 3001 -P tmp/pids/server2.pid`

worked for me

**Comment by mathieujobin** [comment]
@fellz not sure why you wanted to do this. if you have 2 separate apps, or just wanted to run the same app twice. but out of curiosity, I wanted to give this a try. and specifying the pidfile was not enough... I had to make a copy of the app (or have a second app) and for some reason, on the second one, I am getting these lines repeatedly and the demo is not working.

```
Request origin not allowed: http://localhost:3001
Failed to upgrade to WebSocket (REQUEST_METHOD: GET, HTTP_CONNECTION: keep-alive, Upgrade, HTTP_UPGRADE: websocket)
Finished "/cable/" [WebSocket] for ::1 at 2016-04-30 19:44:26 -0400
Started GET "/cable" for ::1 at 2016-04-30 19:44:34 -0400
Started GET "/cable/" [WebSocket] for ::1 at 2016-04-30 19:44:34 -0400
Request origin not allowed: http://localhost:3001
Failed to upgrade to WebSocket (REQUEST_METHOD: GET, HTTP_CONNECTION: keep-alive, Upgrade, HTTP_UPGRADE: websocket)
Finished "/cable/" [WebSocket] for ::1 at 2016-04-30 19:44:34 -0400
```

**Comment by fellz** [comment]
Well really it is in beta4 ```rails s``` do the job no need to run **ActionCable** server

**Comment by fellz** [comment]
@jeremy Hi, do we need to write config.ru for ActionCable ? or how ActionCable works without explicitly running bin/cable ?

**Comment by jeremy** [comment]
@fellz Check out David's demo @ https://medium.com/@dhh/rails-5-action-cable-demo-8bba4ccfc55e for a full run-through. You can mount the cable server in your config/routes.rb.

@mathieujobin To run a cable server on a different host:port, you must add it to the list of allowed origins. These is a whitelist of `https://host:port` that are allowed to connect. When you see "Request origin not allowed" it means the origin is not in your whitelist.
