### ISSUE TITLE
Rails Server Segfaults when running with ObjectSpace

### ISSUE THREAD

**Issue by pik** [rails/rails#24794]
### Steps to reproduce
I'm running rails server with `objspace` to try and identify a memory leak. I have added the following to `config/environment.rb`: 
 
```
require 'objspace'
ObjectSpace.trace_object_allocations_start
```
I am then reloading the index page to force memory-allocations (which I suppose to leak -- but do not segfault without objectspace).  

### Expected behavior
Rails Server not to segfault. 

### Actual behavior
Rails Server segfaults the traceback starts somewhere in sprockets:
https://gist.github.com/pik/07fdd550bb326bb7ef9fcf0f6f6108ab

### System configuration
`Linux l-pc 4.5.0-1-ARCH #1 SMP PREEMPT Tue Mar 15 09:41:03 CET 2016 x86_64 GNU/Linux`
**Rails version**:
`Rails 4.2.6`
**Ruby version**:
`ruby 2.2.4p230 (2015-12-16 revision 53155) [x86_64-linux]`

**Comment by prathamesh-sonpatki** [comment]
Can you upload a sample application to Github which reproduces this issue?

**Comment by jeremy** [comment]
See the C level backtrace information. Ruby did a GC during tracing and
segfaulted. Check out recent Ruby changelogs for bugfixes and search
bugs.ruby-lang.org for similar issues. (It's a Ruby bug, unrelated to Rails
or Sprockets.)
