### ISSUE TITLE
AR::Calculations.count does not expand Arel attribute

### ISSUE THREAD

**Issue by joanblake** [rails/rails#24809]
- Steps to reproduce
```ruby
Spree::Product < ActiveRecord::Base
end

prod_at = Spree::Product.arel_table

Spree::Product.select(prod_at[:id]).count
# ActiveRecord::StatementInvalid: PG::SyntaxError: ERROR:  syntax error
# at or near "Arel"
# LINE 1: SELECT COUNT(#<struct Arel::Attributes::Attribute relation=#...
#                               ^
# : SELECT COUNT(#<struct Arel::Attributes::Attribute relation=#<
# Arel::Table:0x00000007553f50 @name="spree_products",
# @engine=Spree::Product(id: integer, …
```
 - Expected behavior
```ruby
Spree::Product.select(prod_at[:id]).count
# SELECT COUNT("spree_products"."id") FROM "spree_products" WHERE
# "spree_products"."deleted_at" IS NULL
#  => 1253
```
 - System configuration

Rails version: 4.2.6
Ruby version: 2.3.1

There is also a question to the issue on [StackOverflow.com](http://stackoverflow.com/questions/36981884/arel-and-activerecords-count-throws-error) .

**Comment by maclover7** [comment]
Arel is private / internal API, and should not be used by end users 😬

**Comment by joanblake** [comment]
Weird decision close the issue and leave the bug unfixed, but each to his own.

Btw. there is a similar stalled bug report [#15138](https://github.com/rails/rails/issues/15138).

Good luck …
