### ISSUE TITLE
Rails 5 beta 4 stats includes tasks LOC twice

### ISSUE THREAD

**Issue by cover** [rails/rails#24811]
When you run `rails stats` it counts the tasks under `libs` two times (once under `libs` and once under `tasks`), increasing the number of the actual lines of code
### Steps to reproduce

```
rails new abc -d postgresql -B
cd abc
echo "class Foo\nend" > lib/tasks/foo.rake
rails stats
```
### Expected behavior

```
[...]
| Libraries            |      0 |      0 |       0 |       0 |   0 |     0 |
| Tasks                |      2 |      2 |       0 |       1 |   0 |     0 |
[...]

  Code LOC: 28     Test LOC: 0     Code to Test Ratio: 1:0.0
```
### Actual behavior

```
[...]
| Libraries            |      2 |      2 |       0 |       1 |   0 |     0 |
| Tasks                |      2 |      2 |       0 |       1 |   0 |     0 |
[...]

  Code LOC: 30     Test LOC: 0     Code to Test Ratio: 1:0.0
```
### System configuration

**Rails version**: 5 beta 4

**Ruby version**: 2.3.0

**Comment by vipulnsward** [comment]
Ref: https://github.com/vipulnsward/rails/commit/3e3f3563b826bc934448c9a6c25d940df4ba073a
