### ISSUE TITLE
Rails console reload! does not eager load when told to

### ISSUE THREAD

**Issue by sirwolfgang** [rails/rails#24819]
### Steps to reproduce

Using the following STI class structure, with eager loading on.

``` ruby
# config/development.rb
config.eager_load = true

# app/models/class_a.rb
class ClassA < ActiveRecord::Base
  def self.types
    descendants.map(&:name)
  end
end

# app/models/class_b.rb
class ClassB < ClassA
end
```

``` bash
rails c
Loading development environment (Rails 4.2.6)
irb(main):001:0> ClassA.types
=> ["ClassB"]
irb(main):002:0> reload!
Reloading...
=> true
irb(main):004:0> ClassA.types
=> []
```
### Expected behavior

The `reload!` command should of reloaded all of the eager loaded content.
### Actual behavior

The `reload!` command does not seem to reload all the eager loaded content.
### System configuration

**Rails version**: Rails 4.2.6
**Ruby version**: ruby 2.3.0p0 (2015-12-25 revision 53290) [x86_64-darwin15]

**Comment by maclover7** [comment]
Can you create an executable test script using one of the templates [here](https://github.com/rails/rails/tree/master/guides/bug_report_templates), that would demonstrate the problem you are seeing? I think there are some configuration switches you have on, that we can't see :)

**Comment by alextaylor000** [comment]
I'm able to reproduce this issue on a new Rails 4.2.6 project following the steps above. (Although I'm not sure how to write an isolated test for it since it seems to rely on having loading a whole Rails app).

**Comment by maclover7** [comment]
cc @fxn, this probably has to do with `active_support/dependencies`

**Comment by sgrif** [comment]
I don't think we support using `reload!` in the console if `eager_load` is set to true.

**Comment by matthewd** [comment]
As long as `cache_classes` is false, it should *work*... but it does sound plausible that it'll ignore `eager_load`, and just unload things, leaving them to autoload when mentioned.

If that's the case, it should be fairly straight-forward to plug the desired behaviour into the Reloader. PRs welcome. :smile:

**Comment by davidakachaos** [comment]
ping @fxn did you have a chance to look at this?

**Comment by fxn** [comment]
What @matthewd said.

Have you had a look at http://guides.rubyonrails.org/autoloading_and_reloading_constants.html#autoloading-and-sti?

**Comment by davidakachaos** [comment]
@sirwolfgang Do you have enough info?

**Comment by longtengz** [comment]
anyone knows if `reload!` doesn't load the eager-loaded stuff, what does it actually do?

**Comment by xathanex** [comment]
Digging through `ActiveSupport::Reloader` docs and _Autoloading and Reloading Constants_ guide, I've ended up with the following:
```ruby
# config/initializers/eager_reloading.rb
Rails.application.reloader.after_class_unload do  
    Rails.application.eager_load! if Rails.application.config.eager_load
end
```
Seems to work like a charm for me - both for console `reload!` and development code reloading.
Rails 5.2.1 / Ruby 2.5.1-p57

**Comment by quentindemetz** [comment]
I am still able to reproduce on 6.1.4.6

**Comment by fxn** [comment]
This is fixed by https://github.com/rails/rails/commit/9971f77463a154dcb6cdb5625a3b8073fef9ec42.

I recall this was not possible in `classic` because eager loading was a recursive `require`, but in Zeitwerk eager loading is a recursive autoloading, so to speak, so you can eager load again after reload.

**Comment by fxn** [comment]
> I recall this was not possible in `classic` because eager loading was a recursive require

No, I was mistaken, it used `require_dependency`.

**Comment by fxn** [comment]
This patch was unfortunate. Normally I work on a branch and wait for CI, I believed I was working on a branch as usual, but wasn't and pushed directly. And then, missed CI was red.

It's fixed in `main` now. CI remains red, but failure seems unrelated to this patch. I'll update `7-0-stable` now, thanks for the message @eileencodes.
