### ISSUE TITLE
`select_tag` with `include_blank: true` generates invalid HTML

### ISSUE THREAD

**Issue by paulmenzel** [rails/rails#24816]
In at least Rails 4.2.5.2, [select_tag](http://apidock.com/rails/ActionView/Helpers/FormTagHelper/select_tag) called with `include_blank: true` creates invalid HTML. From the documentation.

> ```
> select_tag "people", options_from_collection_for_select(@people, "id", "name"), include_blank: true
> # => <select id="people" name="people"><option value=""></option><option value="1">David</option></select>
> ```

From the [HTML 5 specification](https://www.w3.org/TR/html5/forms.html#the-option-element).

> If the element has no label attribute: Text that is not inter-element whitespace.

So for a blank text of the option element is empty, the label attribute has to be set.

PS: There is an extension(?) [`options_for_select_with_attributes`](https://github.com/ddonahue99/options_for_select_with_attributes) which allows to set the HTML attributes.

**Comment by smathy** [comment]
Make it `&nbsp;` instead.

**Comment by paulmenzel** [comment]
Should the option `true` be deprecated then, and the documentation be updated to use `include_blank: "&nbsp;"`?

**Comment by smathy** [comment]
That'd make it the same as the existing `:prompt` option then.

**Comment by paulmenzel** [comment]
@vipulnsward, thank you very much!

Should I backport this to Rails 4.2?

**Comment by rafaelfranca** [comment]
It is already backported to all stable branches that we want to apply it.
Thank you for volunteering.
