### ISSUE TITLE
beta4 fails to upgrade websocket when running on a different port than 3000

### ISSUE THREAD

**Issue by mathieujobin** [rails/rails#24817]
### Steps to reproduce

run rails 5.0 beta4 on a different port

i tried 3333 and 3001, works fine using 3000

* rails s -p 3333
* visit the app

### Expected behavior

/cable/ websocket should work
Started GET "/cable" for ::1 at 2016-05-02 15:56:21 -0400
Started GET "/cable/" [WebSocket] for ::1 at 2016-05-02 15:56:21 -0400
Successfully upgraded to WebSocket (REQUEST_METHOD: GET, HTTP_CONNECTION: keep-alive, Upgrade, HTTP_UPGRADE: websocket)
SettingsChannel is transmitting the subscription confirmation
RoomChannel is transmitting the subscription confirmation
RoomChannel is streaming from room_channel

### Actual behavior
Tell us what happens instead

getting this error repeatidly

"Failed to upgrade to WebSocket (REQUEST_METHOD: GET, HTTP_CONNECTION: keep-alive, Upgrade, HTTP_UPGRADE: websocket)"

Started GET "/cable" for ::1 at 2016-05-02 15:55:47 -0400
Started GET "/cable/" [WebSocket] for ::1 at 2016-05-02 15:55:47 -0400
Request origin not allowed: http://localhost:3001
Failed to upgrade to WebSocket (REQUEST_METHOD: GET, HTTP_CONNECTION: keep-alive, Upgrade, HTTP_UPGRADE: websocket)
Finished "/cable/" [WebSocket] for ::1 at 2016-05-02 15:55:47 -0400
Started GET "/cable" for ::1 at 2016-05-02 15:55:53 -0400
Started GET "/cable/" [WebSocket] for ::1 at 2016-05-02 15:55:53 -0400
Request origin not allowed: http://localhost:3001
Failed to upgrade to WebSocket (REQUEST_METHOD: GET, HTTP_CONNECTION: keep-alive, Upgrade, HTTP_UPGRADE: websocket)
Finished "/cable/" [WebSocket] for ::1 at 2016-05-02 15:55:53 -0400
Started GET "/cable" for ::1 at 2016-05-02 15:55:56 -0400
Started GET "/cable/" [WebSocket] for ::1 at 2016-05-02 15:55:56 -0400
Request origin not allowed: http://localhost:3001
Failed to upgrade to WebSocket (REQUEST_METHOD: GET, HTTP_CONNECTION: keep-alive, Upgrade, HTTP_UPGRADE: websocket)
Finished "/cable/" [WebSocket] for ::1 at 2016-05-02 15:55:56 -0400

### System configuration
**Rails version**:
5.0.0.beta4
**Ruby version**:
2.3.1

**Comment by maclover7** [comment]
ActionCable's default server URL is `http://localhost:3000`, if the server is running in development. If you aren't using that URL for your application in development, you have to edit the configuration :)

https://github.com/rails/rails/blob/master/actioncable/lib/action_cable/engine.rb#L25

**Comment by mathieujobin** [comment]
thanks

**Comment by mathieujobin** [comment]
thanks @maclover7 that explains it.
