### ISSUE TITLE
has_secure_password allow different name instead of password_digest ?

### ISSUE THREAD

**Issue by 1c7** [rails/rails#24828]
I searched on Google, Stackoverflow and This Git Repo,
Can't find any document about this,
is this support by Rails? or its impossible to do by now?

(if I got grammar error please point out, help me improve, thank you!)

**Comment by Erol** [comment]
Looking at `ActiveModel::SecurePassword`, it doesn't look like this is supported. If it's a worthy use case I think I can come up with a PR.

For the meantime, maybe you can try aliasing `password_digest` and `password_digest=`?

**Comment by prathamesh-sonpatki** [comment]
@1c7 Curious, but why do you need the name of the this attribute other than `password_digest`?

**Comment by 1c7** [comment]
@prathamesh-sonpatki 
I am ok with the name "password_digest"
I am not insist using some other name, like "pwd" or something
I just want know if it is possible to use other name.

@Erol 
aliasing?  how?  I just start leaning Rails.

**Comment by prathamesh-sonpatki** [comment]
Thanks @1c7 for clarifying!  It is not supported as of now.

We reserve the issue tracker for bug reports only. The change in the name of attribute is sort of a feature request and should be discussed on rubyonrails core mailing list.


Also regarding questions about aliasing, I think you will get lot of help on Stackoverflow and such tools.

Thanks again 💚

**Comment by 1c7** [comment]
@prathamesh-sonpatki  Thank you!
