### ISSUE TITLE
Outdated doc in `Active Record Query Interface'

### ISSUE THREAD

**Issue by zhengpd** [rails/rails#24830]
The `2.3.1 Equality Conditions` doc in `Active Record Query Interface` page says:

> The values cannot be symbols. For example, you cannot do Client.where(status: :active).

But actually the symbols used in where conditions will be converted to strings for querying.

**Comment by prathamesh-sonpatki** [comment]
> But actually the symbols used in where conditions will be converted to strings for querying.

It does not seem so.

``` sh
$ rails c
Loading development environment (Rails 5.0.0.beta4)
>> Post.where(name: :title)
  Post Load (0.5ms)  SELECT "posts".* FROM "posts" WHERE "posts"."name" = ?  [["name", :title]]
=> #<ActiveRecord::Relation []>
>> Post
=> Post(id: integer, name: string, content: text, created_at: datetime, updated_at: datetime, member_id: integer, user_id: integer)
>> Post.where(name: :text)
  Post Load (0.1ms)  SELECT "posts".* FROM "posts" WHERE "posts"."name" = ?  [["name", :text]]
=> #<ActiveRecord::Relation []>
>> 
```

**Comment by zhengpd** [comment]
I saw the doc at http://guides.rubyonrails.org/active_record_querying.html#hash-conditions , which is for v4.2.6 right now. 

```sh
$ rails c
Loading development environment (Rails 4.2.6)
irb(main):001:0> User.where(name: :test_name)
  User Load (0.2ms)  SELECT "users".* FROM "users" WHERE "users"."name" = ?  [["name", "test_name"]]
=> #<ActiveRecord::Relation []>
irb(main):002:0> 
```

**Comment by vipulnsward** [comment]
This is intentional: https://github.com/activerecord-hackery/squeel/issues/67#issuecomment-5270896
Its not officially supported, and on master, actually leads to pass symbol, but strings on some previous versions.
