### ISSUE TITLE
ActionCable JS: Uncaught TypeError: Cannot read property 'received' of undefinedActionCable.Subscriptions.Subscriptions.notify

### ISSUE THREAD

**Issue by djvs** [rails/rails#24841]
### Steps to reproduce
1) Mount ActionCable in Rails 5 app on Rails server at /cable, port 3000 on development
2) Run independent Node frontend app at port 8080 (could be anything I imagine)
3) Include any version of action-cable/actioncable.js (bower or node npm - written 5 to 2 months ago - presumably issue has not changed since hten) in frontend app
4) Call `cable = ActionCable.createConsumer('ws://localhost:3000/cable')`
5) Receive following error in JS console (Chrome):

`actioncable.js:436 Uncaught TypeError: Cannot read property 'received' of undefinedActionCable.Subscriptions.Subscriptions.notify @ actioncable.js:436ActionCable.Connection.Connection.events.message @ actioncable.js:173
`
If I further add this line to the "default" inside the switch/case in Connection.prototype.events:

`console.log("cs subscriptions", [this.consumer.subscriptions[0], JSON.stringify(message_types), identifier, message]);`
I intermittently either get:

`cs subscriptions [undefined, "{"confirmation":"confirm_subscription","rejection":"reject_subscription"}", undefined, undefined]`

or:

`cs subscriptions [undefined, "{"confirmation":"confirm_subscription","rejection":"reject_subscription"}", undefined, 1462329058]`

or with some other timestamp at the end.

Likewise, in the `rails server` console output, you see repeated connection attempts, which seem to succeed (but apparently don't):

      Finished "/cable/" [WebSocket] for 127.0.0.1 at 2016-05-03 22:31:24 -0400
      Started GET "/cable" for 127.0.0.1 at 2016-05-03 22:31:25 -0400
      subdomain: 
      Started GET "/cable/" [WebSocket] for 127.0.0.1 at 2016-05-03 22:31:25 -0400
      Successfully upgraded to WebSocket (REQUEST_METHOD: GET, HTTP_CONNECTION: Upgrade, HTTP_UPGRADE: websocket)
      Finished "/cable/" [WebSocket] for 127.0.0.1 at 2016-05-03 22:31:35 -0400
      Started GET "/cable" for 127.0.0.1 at 2016-05-03 22:31:36 -0400
      subdomain: 
      Started GET "/cable/" [WebSocket] for 127.0.0.1 at 2016-05-03 22:31:36 -0400
      Successfully upgraded to WebSocket (REQUEST_METHOD: GET, HTTP_CONNECTION: Upgrade, HTTP_UPGRADE: websocket)
      Finished "/cable/" [WebSocket] for 127.0.0.1 at 2016-05-03 22:31:47 -0400
      Started GET "/cable" for 127.0.0.1 at 2016-05-03 22:31:48 -0400
      subdomain: 
      Started GET "/cable/" [WebSocket] for 127.0.0.1 at 2016-05-03 22:31:48 -0400
      Successfully upgraded to WebSocket (REQUEST_METHOD: GET, HTTP_CONNECTION: Upgrade, HTTP_UPGRADE: websocket)`

I dug through the code for a while, but I'm pretty stumped.  Apologies if this isn't supposed to be supported behavior (though I can't imagine why not).

**Expected behavior**
Persistent connection forms without error

**Rails version**:
Rails 5.0.0.beta4

**Ruby version**:
ruby 2.3.0p0 (2015-12-25 revision 53290) [x86_64-linux]

**Comment by maclover7** [comment]
I believe the only official Action Cable JS library that is out there is via the `actioncable` gem itself (don't use any third party libraries -- no guaranteed compatibility, and they aren't supported by the Rails team). Try again using the official JS library, and let me know how it goes?

**Comment by djvs** [comment]
The bower/npm libs are just repacks of the official action-cable - different authors, 3 months apart, same issue.  I can compile this whole tree with Sprockets if I really have to, but it's turning into a real pain:

https://github.com/rails/rails/tree/master/actioncable/app/assets/javascripts

**Comment by jeremy** [comment]
Lots has changed in the last three months, @djvs. Are the npm/bower packages automated? They'll drift quickly if not, considering Action Cable is under active dev.

Please give it a shot with current JS.

**Comment by djvs** [comment]
Go figure, it works.
