### ISSUE TITLE
Preloader gives undefined method `each' for nil:NilClass

### ISSUE THREAD

**Issue by josercruz01** [rails/rails#24848]
I'm hitting this error randomly on production, but the cause is a bit obscure. Below I add a detailed debugging information as to what's failing, but can't figure out why.
### Similar issues

First I should mention that I looked if this was related https://github.com/rails/rails/issues/19891 but after reading it and going over the code it seems that it's not the same underlying cause. In that Github Issue the problem is that the owner field and association field are different data types, but in my case the fields are the same type.
### Error

Error: undefined method `each' for nil:NilClass
### Trace

```
[GEM_ROOT]/gems/activerecord-4.2.5.1/lib/active_record/associations/preloader/association.rb:93 :in `block in associated_records_by_owner`
[GEM_ROOT]/gems/activerecord-4.2.5.1/lib/active_record/associations/preloader/association.rb:92 :in `each`
[GEM_ROOT]/gems/activerecord-4.2.5.1/lib/active_record/associations/preloader/association.rb:92 :in `associated_records_by_owner`
[GEM_ROOT]/gems/activerecord-4.2.5.1/lib/active_record/associations/preloader/collection_association.rb:13 :in `preload`
[GEM_ROOT]/gems/activerecord-4.2.5.1/lib/active_record/associations/preloader/association.rb:20 :in `run`
[GEM_ROOT]/gems/activerecord-4.2.5.1/lib/active_record/associations/preloader.rb:146 :in `block (2 levels) in preloaders_for_one`

... MORE TRACE
```
### Debugging logs

Since I can't reproduce it locally (or in production) I added debugging statements and we got an insight on what's happening, but don't understand why. We are using Postgres 9.4 and rails 4.2.5.2.

Issue looks like the associated AR model retrieved from the database has either an `ID == 0`, or an `ID == nil` (sometimes one, sometimes the other), and this makes the code blow up when indexing into the `owners_keys` because the has has no entry for 0, that's what throws the `undefined method`each' for nil:NilClass` exception.

Here are some of the context we logged to debug this problem.
#### First context

In this first context you can see that both fields (association_key and owner_key) are _integer_. Note that the association_record has the `id == 0` which is not correct.

```
{
  "key_conversion_required" => false,
  "association_key_type" => "integer",
  "association_key_name" => "id",
  "association_class" => "Company",
  "association_record" => "#<Company id: 0, name: \"Google Inc.\", listed: nil, ... MORE FIELDS>",
  "owner_key_type" => "integer",
  "owner_key_name" => "company_id",
  "owner_key" => 0,
  "owner_class" => "Job",
  "available_owner_keys" => "[3531, 2831,  ...]",
  "klass" => "Company"
}
```
#### Second context

```
{
  "key_conversion_required" => false,
  "association_key_type" => "integer",
  "association_key_name" => "advisorship_id",
  "association_class" => "Precondition",
  "association_record" => "#<Precondition id: nil, name: nil, advisorship_id: nil, ... MORE FIELDS>",
  "owner_key_type" => "integer",
  "owner_key_name" => "id",
  "owner_key" => nil,
  "owner_class" => "Advisorship",
  "available_owner_keys" => "[23312274, 33347906, 33122455, ... MORE KEYS]",
  "klass" => "Precondition"
}
```

In this second context the association record has _all the fields_ `nil` after it's loaded from the database into memory.

Any ideas on why does the AR model loads with incorrect data? At this point in the code the AR model was loaded from the database so it should have a valid ID (not zero).

Tracing the code it looks like the problem might be inside the `records_for(ids)` method which returns the incorrect records.
### Expected behavior

The preloader should load all the associated record correctly.
### Actual behavior

undefined method `each' for nil:NilClass exception is raised.
### Final notes

We've tried to reproduce with no luck, we get a lot of requests on the application and this happens 3 to 4 times a day.

Would appreciate any help on this.

Thanks
### System configuration

**Rails version**:
4.2.5.2.

**Ruby version**:
ruby '2.2.3'

**Comment by vipulnsward** [comment]
@josercruz01 Do you happen to log queries, before this, during the request? 
What are differences between them? 
I know its hard to reproduce, but you can probably give it a try to reproduce with https://github.com/rails/rails/blob/master/guides/bug_report_templates/active_record_gem.rb

**Comment by brianstorti** [comment]
@vipulnsward Not sure how helpful this is, as I had to add a `reload` in the rails code to reproduce the issue, but maybe this can give some insight of what could be causing the problem.

The gist with the template: https://gist.github.com/brianstorti/a9b3121400f6d61f10ebcd91feadff65

And the rails change to trigger the failure (`sleep` added to simulate a Thread stop):
```diff
diff --git activerecord/lib/active_record/associations/preloader/association.rb activerecord/lib/active_record/associations/preloader/association.rb
index 41c4630..f0bc4e8 100644
--- activerecord/lib/active_record/associations/preloader/association.rb
+++ activerecord/lib/active_record/associations/preloader/association.rb
@@ -116,7 +116,9 @@ module ActiveRecord
             records_for(slice)
           }
 
+          sleep 0.2
           @preloaded_records.map { |record|
+            record.reload
             key = record[association_key_name]
             key = key.to_s if key_conversion_required?
```
