### ISSUE TITLE
ActiveRecord reads `id` as `null` if table has no primary key

### ISSUE THREAD

**Issue by MOZGIII** [rails/rails#24857]
### Steps to reproduce

1. Create a rails app with Rails 4.2 with PostgreSQL database.
2. Configure a PostgreSQL database and enable `uuid-ossp`.
2. Create a `books` table with `id` being a UUID. Create some records manually.
3. `rails g model book`
4. In `rails c`.
```
[vagrant@localhost vagrant]$ rails c
Loading development environment (Rails 4.2.6)
[1] pry(main)> b = Book.first
  Book Load (13.2ms)  SELECT  "books".* FROM "books" LIMIT 1
=> #<Book:0x007fd5a13d4068
 id: nil,
 ...>
[2] pry(main)> b.attributes
=> {"id"=>"bfaae356-3f40-7ffc-30cc-bf5d9c95ffab",
...}
[3] pry(main)> 
```

### Expected behavior
`b.id` to be equal to `bfaae356-3f40-7ffc-30cc-bf5d9c95ffab`

### Actual behavior
`b.id` is `null`
But `attributes['id']` has the correct value.

### System configuration
**Rails version**: 
4.2.6 (also happens with 5.0.0.beta4)
**Ruby version**: 
2.3.1

**Comment by MOZGIII** [comment]
Database dump (user `vagrant`, db `vagrant`):

```sql
--
-- PostgreSQL database dump
--

SET statement_timeout = 0;
SET lock_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SET check_function_bodies = false;
SET client_min_messages = warning;

--
-- Name: book_view; Type: SCHEMA; Schema: -; Owner: vagrant
--

CREATE SCHEMA book_view;


ALTER SCHEMA book_view OWNER TO vagrant;

--
-- Name: plpgsql; Type: EXTENSION; Schema: -; Owner: 
--

CREATE EXTENSION IF NOT EXISTS plpgsql WITH SCHEMA pg_catalog;


--
-- Name: EXTENSION plpgsql; Type: COMMENT; Schema: -; Owner: 
--

COMMENT ON EXTENSION plpgsql IS 'PL/pgSQL procedural language';


--
-- Name: uuid-ossp; Type: EXTENSION; Schema: -; Owner: 
--

CREATE EXTENSION IF NOT EXISTS "uuid-ossp" WITH SCHEMA public;


--
-- Name: EXTENSION "uuid-ossp"; Type: COMMENT; Schema: -; Owner: 
--

COMMENT ON EXTENSION "uuid-ossp" IS 'generate universally unique identifiers (UUIDs)';


SET search_path = book_view, pg_catalog;

SET default_tablespace = '';

SET default_with_oids = false;

--
-- Name: books; Type: TABLE; Schema: book_view; Owner: vagrant; Tablespace: 
--

CREATE TABLE books (
    id uuid,
    text text
);


ALTER TABLE books OWNER TO vagrant;

--
-- Data for Name: books; Type: TABLE DATA; Schema: book_view; Owner: vagrant
--

COPY books (id, text) FROM stdin;
41f14a39-198b-4b71-90e6-3c19e1c6eaaa	214234
dd134b5a-9bb7-443c-a1a5-939c64a65245	214234
4989ab6a-27e4-4c62-a198-872cded13a99	214234
\.


--
-- Name: public; Type: ACL; Schema: -; Owner: postgres
--

REVOKE ALL ON SCHEMA public FROM PUBLIC;
REVOKE ALL ON SCHEMA public FROM postgres;
GRANT ALL ON SCHEMA public TO postgres;
GRANT ALL ON SCHEMA public TO PUBLIC;


--
-- PostgreSQL database dump complete
--
```

**Comment by MOZGIII** [comment]
I assume this is because of some bug at the `Book#id` accessor that is generated by Active Record.

**Comment by MOZGIII** [comment]
I found this workaround:
```ruby
class Book < ActiveRecord::Base
  self.primary_key = 'id'
end
```

**Comment by MOZGIII** [comment]
For those who need a better workaround:

Make your `ApplicationRecord` fix `primary_key` for all child models for you.
```ruby
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true

  def self.inherited(subclass)
    super
    subclass.primary_key = 'id'
  end
end
```

**Comment by maclover7** [comment]
Can you create an executable test script using one of the templates [here](https://github.com/rails/rails/tree/master/guides/bug_report_templates), that would demonstrate the problem you are seeing?

**Comment by MOZGIII** [comment]
I don't think I will. I have a very limited amount of time.
Did some research, and now I recognise this problem was already reported, and is related to absence of primary key in the database table. I am actually using a database view, instead of a real table, and primary keys are simply not supported in my case. Though, that is a rare edge case, and there is a working workaround, so I don't think there is value in exploring further.

I'll close it fot now, and reopen if I manage to put test script together.

**Comment by eugeneius** [comment]
I had this problem recently, and setting the primary key manually worked great. Thanks @MOZGIII!

It looks like https://github.com/rails/rails/pull/27935 fixed the bug here, by making `read_attribute` return the value of the `id` column instead of `nil` if the model has no primary key.
