### ISSUE TITLE
5.0.0.beta4 ActiveRecord references polymorphic: true creates schema with id/type column order swapped

### ISSUE THREAD

**Issue by jrafanie** [rails/rails#24863]
### Steps to reproduce

Given, you define a schema with a `t.references XXX, polymorphic: true`:
```ruby
  create_table :comments, force: true  do |t|
    t.references :resource, :polymorphic => true
  end
```

If you migrate your database on rails 5.0.0.beta4 vs. 4.0, 4.1, 4.2, the schemas, specifically, the column order, are different.

See [recreation gist here](https://gist.github.com/jrafanie/553e35f560c18ab0c80857b96f7bbde3).

It seems to be have been caused by this commit: d26704a15f88d384dd2824 and it's not clear that this change was intentional.  If this was not intentional, the `unshift` could be changed to append to the array instead of prepending it.  If this is ok, I can open a PR to do this.

### Expected behavior

With Rails 4.0, 4.1, 4.2, `t.references :resource, :polymorphic => true` will create a schema where resource_id comes first:

```ruby
  create_table "comments", force: :cascade do |t|
    t.integer "resource_id"
    t.string  "resource_type"
  end
```

### Actual behavior

With rails 5.0.0.beta4, the resource_type column is created first:

```ruby
  create_table "comments", force: :cascade do |t|
    t.string  "resource_type"
    t.integer "resource_id"
    t.index ["resource_type", "resource_id"], name: "index_comments_on_resource_type_and_resource_id"
  end
```

### System configuration
**Rails version**: 5.0.0.beta4

**Ruby version**: 2.2.5

**Comment by maclover7** [comment]
👍 I think this may have been an unintended consequence. +1 for opening up a PR.

**Comment by jrafanie** [comment]
Thanks @maclover7, I'll try to find a place for a regression test and submit a PR.

**Comment by rafaelfranca** [comment]
@maclover7 yeah, it was not expected.

**Comment by jeremy** [comment]
Changing the column order, no big deal. Changing the _index_ order, release blocker.

**Comment by sgrif** [comment]
So the index hasn't been changed from 4.2. The type comes first in the index after https://github.com/rails/rails/pull/14143 was merged. It looks like the order of the columns was a side effect of the refactoring, but it was intentional as the same code is used for both the index and the column definitions.

**Comment by jrafanie** [comment]
@jeremy Note, 4.x doesn't generate the indexes for t.references by default until rails 5, so I ran them all again with index creation to verify the behavior.  Sadly, the results are inconsistent.

**Given**

```ruby
  create_table :comments, force: true  do |t|
    t.references :resource, polymorphic: true, index: true
  end
```

Here's a table to help visualize it.  Note, that 4.2.6 creates columns in id/type order but with index in type/id order.  The tl;dr is if I patch 5.0.0beta4 to fix column order to be like 4.x, it will swap the index order from 4.2.6.

**Column order:**

| 4.0.13  | 4.1.15  | 4.2.6 | 5.0.0.beta4 | 5.0.0.beta4patched |
| ------------- |:-------------:| -----:| --- | --- |
| id | id | id | _type_ | id |
| type | type | type | _id_ | type |


**index order:**

| 4.0.13  | 4.1.15  | 4.2.6 | 5.0.0.beta4 | 5.0.0.beta4patched |
| ------------- |:-------------:| -----:| --- | --- |
| id | id | _type_| _type_ | id |
| type | type | _id_ | _id_ | type |

See gist here for the full details: https://gist.github.com/jrafanie/91e1e99a2e64e4606dcbd9ebf3683456

**Comment by jrafanie** [comment]
Thanks all, I agree with Sean, it's unfortunate that column order has changed from 4.2 to 5 but fixing that is not worth changing the column order of the index.
