### ISSUE TITLE
Cable: Subscribe shouldn't block the event loop

### ISSUE THREAD

**Issue by jeremy** [rails/rails#24876]
Subscribing to a channel is done on the main thread since we want to give an immediate response: is the subscription rejected?

But this means that the `Channel#subscribed` hook and `subscribe` callbacks are all run on the main thread!

We can redesign the subscription lifecycle to behave async: subscribe to a channel, immediately acknowledge the subscription request, perform subscription on worker pool, then confirm/reject the subscription.

**Comment by maclover7** [comment]
👍  we can probably reuse / repurpose the concurrent-ruby infrastructure that's already in Action Cable, that's being used with the workers

**Comment by jeremy** [comment]
Right. We run all other actions and callbacks on the worker pool already. We specifically _don't_ run these on the worker pool because we want a synchronous response. By redesigning the lifecycle, we can make the entire flow async and get subscription handling off the main thread.

**Comment by maclover7** [comment]
Very, very early implementation PR is available at #24879.

**Comment by djvs** [comment]
I've been trying to debug some inexplicable response lag since upgrading to Rails 5 and implementing ActionCable, is this potentially the cause for that?

**Comment by jeremy** [comment]
@djvs By response lag do you mean that traffic on the WebSocket seems slow or is stalling? Have you troubleshooted in dev tools or wireshark?

**Comment by djvs** [comment]
I mean ordinary HTTP back and forth traffic stalls.  The request gets sent but doesn't go through (e.g. reflect in console output) for a good 10 seconds.

**Comment by jeremy** [comment]
@djvs Browsers have a limit on max connections per host that you may be hitting. You'll need to dig into web inspector to see what's happening with your network connections with greater precision. This is unrelated to this issue, however 😊

**Comment by djvs** [comment]
Isn't AC one persistent connection?   That's the only thing that provoked this new behavior, the upgrade to 5.0.0.beta4 and addition of AC connections. (one subscription app-wide).  And see above about AC output right after the lag ends - if I see it again I'll post that output here, I'm pretty sure it's the cable subscription stuff itself.

**Comment by jeremy** [comment]
@djvs Please post in a separate GitHub issue once you've gathered clear specifics about the behavior you're seeing! This issue is exclusively for tracking feature development, not for app troubleshooting.

**Comment by matthewd** [comment]
@jeremy the very concept of a "main thread" is an EM-ism, right?
