### ISSUE TITLE
Cable: JavaScript integration tests

### ISSUE THREAD

**Issue by jeremy** [rails/rails#24878]
We test the Action Cable server components. We don't test the JavaScript client.

Let's set up a test suite like [Trix runs](https://github.com/basecamp/trix/blob/master/bin/ci) with [Blade](https://github.com/javan/blade) and build out the beginnings of an integration test suite.

**Comment by vipulnsward** [comment]
👍🏻. This is both for testing AC itself and others to test as well?

**Comment by jeremy** [comment]
@vipulnsward For testing AC itself. Apps can do integration tests already 😁

**Comment by vipulnsward** [comment]
👍🏻 let me take a look at it

On Thursday 5 May 2016, Jeremy Daer <notifications@github.com> wrote:

> @vipulnsward <https://github.com/vipulnsward> For testing AC itself. Apps
> can do integration tests already 😁
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/rails/rails/issues/24878#issuecomment-217334054>
>


-- 
Vipul A.M.
+91-8149-204995

**Comment by javan** [comment]
Feel free to assign this one to me
