### ISSUE TITLE
Cable: Separate subscription confirmation from stream confirmation

### ISSUE THREAD

**Issue by jeremy** [rails/rails#24877]
We have a special case for subscription confirmation. Normally, we'd return the confirmation immediately after calling `#subscribed` and `subscribe` callbacks, but `stream_from` needs to establish a pubsub subscription with e.g. Redis before it can start streaming AND we don't want the client to think the subscription is REALLY connected yet. So, we added a workaround where we explicitly defer confirmation before establishing the pubsub subscription then explicitly send confirmation after it succeeds.

This is awkward, and these are separate concerns. Whether we've subscribed = whether the server has record of the channel and knows that it's open. Whether we're streaming for a broadcasting = whether the server has successfully initiated pubsub subscription.

Let's look at decoupling the two and getting rid of the streaming-only deferral management. We really want a stream confirmation here. The client can know that the server subscription went through and can later know that streaming has begun on a broadcasting.

**Comment by maclover7** [comment]
👍  Basically we're splitting this up into an "acknowledge" response that we received the request to create a subscription, and then send another message later, which is an actual confirmation message about whether the subscription was created?

**Comment by maclover7** [comment]
Should this be combined with #24876? -- I think they both flow together.

**Comment by jeremy** [comment]
We separate orthogonal changes so we can work on, test, merge, and revert
them independently of each other—so they can flow together :)
