### ISSUE TITLE
Redirect_to with turbolinks action 'change' renders {"action":"replace"} instead of { change: [...] }

### ISSUE THREAD

**Issue by doerfli** [rails/rails#24898]
### Steps to reproduce

I have this view with turbolinks and would like to have a partial update of the div `#result`. 

```
<div id="result" data-turbolinks-temporary>
  <% if flash[:new] %>
      Created new mock. Send your requests to <%= link_to flash[:new] %>.
  <% end %>
</div>
<div>
  <%= form_for @new_mock, :remote => true do |f| %>
      <%= f.label :statuscode %>:
      <%= f.text_field :statuscode %><br />
...
      <%= f.submit %>
  <% end %>
</div>
```

And its backed by this controller 

```
class MocksController < ApplicationController

  def index
    @new_mock = Mock.new
  end

  def create
    mock = Mock.new(mock_params)
    mock.save
    flash[:new] = mock

    redirect_to mocks_path, change: ['result']
  end

  private
...
end
```

### Expected behavior
When submitting the form, i would expect the response of the POST to be 

```
Turbolinks.clearCache()
Turbolinks.visit("http://localhost:3000/mocks", { change: ['result'] })
```

### Actual behavior
But i get
```
Turbolinks.clearCache()
Turbolinks.visit("http://localhost:3000/mocks", {"action":"replace"})
```

### System configuration
**Rails version**: 5.0.0.beta4

**Ruby version**: 2.3.0

**Comment by maclover7** [comment]
I think this is a Turoblinks specific issue -- please open up an issue with them at https://github.com/turbolinks/turbolinks-rails/issues/new. Thanks! :)

**Comment by doerfli** [comment]
I disagress, i think the problem is in the rails controller which renders incorrect javascript.
It renders the Javascript when encountering a NON-GET + XHR request for partial updates (new Rails 5 feature).
