### ISSUE TITLE
NameError - uninitialized constant - Rails 5.0.0.rc1

### ISSUE THREAD

**Issue by herminiotorres** [rails/rails#24922]
### Steps to reproduce

(Guidelines for creating a bug report are [available
here](http://guides.rubyonrails.org/contributing_to_ruby_on_rails.html#creating-a-bug-report))

### Expected behavior
Today I tried to use rails 5 rc1. I installed the newest ruby version and rails version, generate a default application, `rails new test`, switch for folder `cd test`, run `bundle install` and next up the server `rails server`. I expected run the server ok.

### Actual behavior
But when I tried to run the server, I got this:
```shell
/Users/herminiotorres/src/test/config/application.rb:10:in `<module:Test>': uninitialized constant Test::Rails::Application (NameError)
	from /Users/herminiotorres/src/test/config/application.rb:9:in `<top (required)>'
	from /Users/herminiotorres/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/railties-5.0.0.rc1/lib/rails/commands/commands_tasks.rb:88:in `require'
	from /Users/herminiotorres/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/railties-5.0.0.rc1/lib/rails/commands/commands_tasks.rb:88:in `block in server'
	from /Users/herminiotorres/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/railties-5.0.0.rc1/lib/rails/commands/commands_tasks.rb:85:in `tap'
	from /Users/herminiotorres/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/railties-5.0.0.rc1/lib/rails/commands/commands_tasks.rb:85:in `server'
	from /Users/herminiotorres/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/railties-5.0.0.rc1/lib/rails/commands/commands_tasks.rb:49:in `run_command!'
	from /Users/herminiotorres/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/railties-5.0.0.rc1/lib/rails/commands.rb:18:in `<top (required)>'
	from bin/rails:4:in `require'
	from bin/rails:4:in `<main>'
```

### System configuration
**Rails version**: 5.0.0.rc1

**Ruby version**: 2.3.1p112

**Comment by maclover7** [comment]
Hmm, how did you generate your application? `test` is part of the application name "blacklist" :-(

```
Jonathans-MacBook-Pro:PLAY_ONLY jon$ rails _5.0.0.rc1_ new test
Invalid application name test. Please give a name which does not match one of the reserved rails words: application, destroy, plugin, runner, test
```

**Comment by herminiotorres** [comment]
@maclover7 I didn't use the name `test` for my app.

**Comment by herminiotorres** [comment]
for real I used `coffee` name for my app,

**Comment by herminiotorres** [comment]
```shell
[2.3.1 src]$ rails new coffee
Using --skip-bundle from /Users/herminiotorres/.railsrc
      create
...
2.3.1 src]$ cd coffee/
[2.3.1 coffee]$ bi
Fetching gem metadata from https://rubygems.org/
...
Bundle complete! 15 Gemfile dependencies, 64 gems now installed.
Use `bundle show [gemname]` to see where a bundled gem is installed.
[2.3.1 coffee]$ rails s
/Users/herminiotorres/src/coffee/config/application.rb:10:in `<module:Coffee>': uninitialized constant Coffee::Rails::Application (NameError)
...
```

**Comment by herminiotorres** [comment]
Interesting fact when I used the `example` name for my app, thus work fine.

**Comment by rafaelfranca** [comment]
Coffee is conflicting with the coffee-rails constant namespace.

**Comment by maclover7** [comment]
^^ yep, that would be the issue. I was using `test` as the app name, because that's what you said in your original bug report :)

**Comment by herminiotorres** [comment]
Thank you both for clarify my doubts.

**Comment by herminiotorres** [comment]
Ok, about the `coffee` constant namespace.

The `coffee-rails` shouldn't is in an isolated context?

Because the `test` name I received the message about it  or put on the `coffee` name in this list too.

Make sense?

**Comment by rafaelfranca** [comment]
Unfortunately there is no way to fix this issue other than rejecting coffee
as an application name. You would have the same problem if you create a
model called Coffee. It is how constants in Ruby works, if you have the
same name of constant you will reopen the constant and all constants and
methods available inside it will be available in your application.

I don't think we should do the same thing as `test` for this case though.
This would happen with a lot of different cases depending in your Gemfile.
Sass is other example that this error would happen but the generator would
not warn. Same with Sprockets, RSpec, Bootstrap, or any other gem that is
called `something-rails`. I don't think we should handle all these cases.

So, depending of your gemfile the application name can be valid or invalid.
You application name can even become invalid after some that if you add a
gem that conflicts with its name. That said, I don't think we can fix this
problem and it is not a common case that requires a new entry in the
blacklist entry. All the entries in the blacklist now are `rails`
subcommands.

**Comment by vipulnsward** [comment]
Closing based on https://github.com/rails/rails/issues/24922#issuecomment-217747978

**Comment by haggen** [comment]
Rails `new` command API says the first argument is the application path. Incidentally it used to accept `.` as valid argument, now I get the error mentioned in this issue:

```
root@bf26b30529eb:/# rails new .
/usr/local/bundle/gems/railties-5.0.0.rc1/lib/rails/generators/rails/app/app_generator.rb:416:in `const_defined?': wrong constant name  (NameError)
	from /usr/local/bundle/gems/railties-5.0.0.rc1/lib/rails/generators/rails/app/app_generator.rb:416:in `valid_const?'
	from /usr/local/bundle/gems/railties-5.0.0.rc1/lib/rails/generators/app_base.rb:151:in `create_root'
	from (eval):1:in `create_root'
	from /usr/local/bundle/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
	from /usr/local/bundle/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
	from /usr/local/bundle/gems/thor-0.19.1/lib/thor/invocation.rb:133:in `block in invoke_all'
	from /usr/local/bundle/gems/thor-0.19.1/lib/thor/invocation.rb:133:in `each'
	from /usr/local/bundle/gems/thor-0.19.1/lib/thor/invocation.rb:133:in `map'
	from /usr/local/bundle/gems/thor-0.19.1/lib/thor/invocation.rb:133:in `invoke_all'
	from /usr/local/bundle/gems/thor-0.19.1/lib/thor/group.rb:232:in `dispatch'
	from /usr/local/bundle/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
	from /usr/local/bundle/gems/railties-5.0.0.rc1/lib/rails/commands/application.rb:17:in `<top (required)>'
	from /usr/local/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/local/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/local/bundle/gems/railties-5.0.0.rc1/lib/rails/cli.rb:14:in `<top (required)>'
	from /usr/local/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/local/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/local/bundle/gems/railties-5.0.0.rc1/exe/rails:9:in `<top (required)>'
	from /usr/local/bundle/bin/rails:23:in `load'
	from /usr/local/bundle/bin/rails:23:in `<main>'
```

Creating an unnamed application in the current directory is deprecated?

**Comment by KaraAJC** [comment]
thank goodness for this issue, Just had a few folks run into this problem!

@rafaelfranca You mentioned a blacklist entry, is this where protected names are listed? Could you tell me where I could see this list? Thank you!
