### ISSUE TITLE
Update rails-dom-testing

### ISSUE THREAD

**Issue by connorshea** [rails/rails#24924]
It's weird that this isn't causing problems yet, but rails-dom-testing 1.x shouldn't work with Rails 5.

The gemspecs of actionview, actionmailer, and actionpack have a dependency on `rails-dom-testing (~> 1.0, >= 1.0.5)`. As of [rails-dom-testing 1.0.7](https://rubygems.org/gems/rails-dom-testing/versions/1.0.7), the gem has a dependency on `activesupport < 5.0, >= 4.2.0.beta`, meaning it shouldn't work with 5.0 (I guess 5.0.0.rc1 is considered `< 5.0` by Bundler?).

[rails-dom-testing 2.0.0](https://rubygems.org/gems/rails-dom-testing/versions/2.0.0) supports `activesupport < 6.0, >= 4.2.0`, however, so it *will* work with Rails 5.0.0.

Files to update:
- [actionmailer.gemspec](https://github.com/rails/rails/blob/master/actionmailer/actionmailer.gemspec)
- [actionpack.gemspec](https://github.com/rails/rails/blob/master/actionpack/actionpack.gemspec)
- [actionview.gemspec](https://github.com/rails/rails/blob/master/actionview/actionview.gemspec)

Should probably fix that before 5.0.0 stable drops and stuff breaks :)

cc: @kaspth (https://github.com/rails/rails-dom-testing/issues/49)

**Comment by connorshea** [comment]
If you can tell me what the gemspec's should depend on (e.g. should it be `~> 2.0` or `>= 1.0, < 3`?) I can open a PR for this.

**Comment by prathamesh-sonpatki** [comment]
@connorshea I think it should be `~> 2.0 `

**Comment by md5** [comment]
@rafaelfranca It looks like this changes didn't make it into the 5.0.0.rc2 release. Since this has the 5.0.0 milestone, that seems like an oversight.

**Comment by rafaelfranca** [comment]
Urh. That is true. I'll backport now. Thanks.
