### ISSUE TITLE
Could not find proper version of railties (4.2.5.1) in any of the sources

### ISSUE THREAD

**Issue by DrSayre** [rails/rails#24926]
### Steps to reproduce

(Guidelines for creating a bug report are [available
here](http://guides.rubyonrails.org/contributing_to_ruby_on_rails.html#creating-a-bug-report))

### Expected behavior
Tell us what should happen
I installed the newest ruby version and rails version. I was expecting to do something like this to create a new rails application:
```
rails new foo
```

### Actual behavior
Tell us what happens instead
Instead I get this error message:
```
Could not find proper version of railties (4.2.5.1) in any of the sources
Run `bundle install` to install missing gems.
```
I did a gem list to verify that the only rails I have installed is 5.0.0.rc1.  I am using rvm which I am wondering if that has something to do with it.

### System configuration
**Rails version**: 5.0.0.rc1

**Ruby version**: 2.3.1p112

**Comment by maclover7** [comment]
Hmm, can you run `rails -v` from your home directory? From a first glance, it looks something might be up with your local gem setup. Also, if you can cause the error to happen again, can you post the full backtrace? That might help in locating the source of the bug 😄

**Comment by DrSayre** [comment]
From home I get 5.0.0.rc1, from my programming directory I get the error.
```
 ➜  ~  rails -v
Rails 5.0.0.rc1
 ➜  ~  cd Documents/Programming
 ➜  ~/Documents/Programming  rails -v
Could not find proper version of railties (4.2.5.1) in any of the sources
Run `bundle install` to install missing gems.
 ➜  ~/Documents/Programming  rails new foo
Could not find proper version of railties (4.2.5.1) in any of the sources
Run `bundle install` to install missing gems.
```

**Comment by maclover7** [comment]
Do you know what the original command was that you used to install Rails? It's possible your `rvm` gem setup might have gotten messed up 😬 

If you'd like to, you can start over with a blank slate of rails versions:
```
gem uninstall railties
gem uninstall rails

gem install rails -v '5.0.0.rc1'
```

**Comment by DrSayre** [comment]
Nothing out of the ordinary.  I did have an issue installing nokogiri (libxml2 is missing) which I was able to install by doing this:
```
gem install nokogiri -- --use-system-libraries
```

**Comment by DrSayre** [comment]
Tried uninstalling and reinstalling rails, got the same error.

**Comment by maclover7** [comment]
Hmm, I'm really not sure at this point what's up 😢. Maybe some other people on the issue tracker will chime in about some possible fixes, but I'd say you should consider opening up a ticket with Rubygems at their [Github repo](https://github.com/rubygems/rubygems), since I don't think this is a bug within Rails itself. Sorry we weren't able to directly diagnose the problem :-(

**Comment by DrSayre** [comment]
Thanks @maclover7, I wasnt 100% sure this would be a Rails thing or Rubygems or RVM.  I will check out the Rubgems repo.

**Comment by DrSayre** [comment]
Ahh... I found a Gemfile and Gemfile.lock file in my programming directory that was messing things up. Deleted those and now Im good. Im surprised I had not ran into this before.

**Comment by maclover7** [comment]
👍

**Comment by cosky5** [comment]
Have you try updating bundle?
<code>bundle update
</code>
