### ISSUE TITLE
Is it possible to have multiple actioncable servers speak to eachother?

### ISSUE THREAD

**Issue by NullVoxPopuli** [rails/rails#24931]
Here is the scenario I'm envisioning:
 - client sends a message to server A.
 - server A finds out that the message from the client is actually intended for server B
 - server A forwards the message from the client to server B

I guess, short of going back to communicating over HTTP/S, is there a way to (maybe on server boot), open a cable between server A and server B? Or would I need to start action_cable_client in a thread (or fiber or something), and use that to send to the other server when I need to?

**Comment by jeremy** [comment]
This is a scenario we've tried to rule out by design. Getting into proxying/forwarding cable messages themselves adds a lot of complexity to the server without proportionate payoff. If you need to dispatch a cable message elsewhere, odds are it's to a job to be processed, not to another server to be processed.

Let's take a closer look at this if you hit a concrete case that falls out of the sweet-spot design.

**Comment by NullVoxPopuli** [comment]
Makes sense.

The the exact scenario has to do with this instant messaging networking I'm building.

Client A knows about Client B and Server A
Client B knows about Client A and Server B

Client A wants to communicate with Client B, but the Server Client A is connected to doesn't know about Client B. Server A (hopefully) would be able to forward the message to Server B, which does know about Client B.

This is a really small example, and sounds kinda silly when there are only 2 clients and 2 servers.

But if there are a lot of clients, I was thinking the various servers could be used to kind of load-balance the overall network (especially if using the free-tier on heroku / other paas)

![image](https://cloud.githubusercontent.com/assets/199018/15119696/233827d6-15e0-11e6-993a-09a134e9ad76.png)

here is a _slightly_ more realistic representation of what I'm thinking the full network would look like, with the capital letters as ActionCable servers, and the lowercase letters as ActionCable clients. 
In the graph, all clients should be able to communicate with all the other clients, even if they aren't connected to the same server.

Does that kinda give a better picture of what I'm trying to achieve?
so, for load-balanced apps -- with multiple servers, how would you sync things between people there?

**Comment by jeremy** [comment]
Add a pubsub tier behind your cable servers. Use Redis or PostgreSQL as the pubsub message bus. Now it doesn't matter which server your clients are connected to and forwarding/proxying is a non-issue :)

**Comment by NullVoxPopuli** [comment]
Hmm, wouldn't that create a single point of failure though?

The main goal of all this is to have high reliability, so in the event one part of the system breaks, the whole system can continue function. (so, using the example in the picture, each client, would actually have 2-3 connections to various servers)

**Comment by jeremy** [comment]
You'd be recreating a highly available pubsub system using WebSockets servers. Consider using "dumb" WebSockets servers that don't need to track state and using an existing highly available pubsub system instead (Redis cluster, PostgreSQL cluster, RabbitMQ, Kafka, Google/AWS/Azure pubsub, …)
