### ISSUE TITLE
ActionController::TestCase#process method not reading current value in @request.env

### ISSUE THREAD

**Issue by andrewarrow** [rails/rails#24933]
### Steps to reproduce
@request.env["HTTP_AUTHORIZATION"] = 'Bearer abc'
post(:create)
@request.env["HTTP_AUTHORIZATION"] = 'Bearer xyz'
post(:create)

### Expected behavior
2nd post should have xyz

### Actual behavior
2nd post still has abc

### System configuration
4.2.0

**Ruby version**:
2.2.2

**Comment by maclover7** [comment]
I think this is because you are reaching directly into the `@request` object, and its `env`, and if I remember correctly (could be wrong here) either the request or env is cleared every time you make a web request, so I think this is unsupported behavior 😬

**Comment by vipulnsward** [comment]
```ruby
  def test_index_success
    @request.env["HTTP_AUTHORIZATION"] = 'Bearer abc'
    get :index
    puts @request.env["HTTP_AUTHORIZATION"]
    @request.env["HTTP_AUTHORIZATION"] = 'Bearer xyz'
    get :index
    puts @request.env["HTTP_AUTHORIZATION"]

    assert_response :success
  end
```

With this test, I see 

```
Bearer abc
Bearer xyz
```

in the logs. So its assigning as expected. Can you share an simple example App with this issue?

**Comment by andrewarrow** [comment]
good point. I tried a simple example and got same result as you. It must be something to do with https://github.com/doorkeeper-gem/doorkeeper gem I'm using in a more complex project. I'll close issue. Thanks.
