### ISSUE TITLE
AR::Base.find_in_batches version for relations

### ISSUE THREAD

**Issue by rwz** [rails/rails#24934]
In real-world application there're times when you have to migrate a column in a really big table from one value to another. Performing a single update is not really an option because it'll lock the whole table and will take forever, and iterating over each row is just too slow.

The ideal approach would be to do update in batches. Set a relation with some offsets/limits, perform an update to all records in it, move to the next one.

This code illustrates this approach (but doesn't actually work):

```ruby
MyModel.where(my_column: "old value").find_in_batches(batch_size: 5000) do |batch|
  # assuming batch is an AR::Relation here, which is not true
  batch.update_all my_column: "new value"
end
```

This code doesn't work because `find_in_batches explicitly` casts `to_a` on the relation before returning it.

It seems like a bit lower-level abstraction that returns AR::Relations instead of arrays would be very useful for cases similar to the one described above.

Obviously changing the behavior of the existing method won't do, but maybe adding a new method (someling like `AR::Relation#split_into_batches`) and extracting 90% of `find_in_batches` code into it would work nicely?

**Comment by rafaelfranca** [comment]
http://edgeapi.rubyonrails.org/classes/ActiveRecord/Batches.html#method-i-in_batches

**Comment by rwz** [comment]
Oh, wonderful. I wonder why `find_in_batches` doesn't use `in_batches` though and implements everything from scratch.

**Comment by rwz** [comment]
Nevermind, seems like it was only recently extracted and hasn't made its way to any of the stable releases yet.
