### ISSUE TITLE
belongs_to presence validation failing

### ISSUE THREAD

**Issue by rockertux** [rails/rails#24957]
This breaks custom setter methods that need `write_attribute` to be sent during spec testing.

### Steps to reproduce
```ruby
class ClassA < ApplicationRecord
  has_many :class_b
end

class ClassB < ApplicationRecord
  belongs_to :class_a
  
  def class_a_id=(class_a_id)
    return unless class_a_id.nil?
    write_attribute(:class_a_id, class_a_id)
  end
end

a = ClassA.create
b = ClassB.create({ class_a: a })

b.send(:write_attribute, :class_a_id, nil)
b.valid?
```

### Expected behavior
```ruby
b.valid? => false
```

### Actual behavior
```ruby
b.valid? => true
```

### System configuration
**Rails version**: 5.0.0.beta4

**Ruby version**: 2.2.3

**Comment by sblackstone** [comment]
Try

`belongs_to :class_a, required: false`

**Comment by maclover7** [comment]
Hmm, it looks like you are monkey patching `class_a_id=`, which I don't believe is supported by Rails / Active Record. In Active Record, a huge suite of validations helpers are provided that you can use in your models, which you can check out [here](http://guides.rubyonrails.org/active_record_validations.html).
