### ISSUE TITLE
ActionCable: Is there any option to defer call from client before subscription is finalized?

### ISSUE THREAD

**Issue by nateless** [rails/rails#24953]
Currently if we do any calls right after we made a subscription call, it just being silently ignored and no messages is being passed to websocket. DHH have used a [timeout call](https://github.com/rails/actioncable-examples/blob/master/app/assets/javascripts/channels/comments.coffee#L6), which I believe was used during developement, but now we need normal methosd to defer calls and process them ASAP after subscription was finalized.

**Comment by maclover7** [comment]
Hmm, this is definitely something we should take into account. Do you think it is best to account for this on the clientside or the backend? If the clientside, we should probably create an "official" API for people to use.

**Comment by nateless** [comment]
On the client, as backend doesn't know about any calls before connection\subscription thus we should create some message queue which will be dispatched after used subscription will be finalized ( subscribed and confirmed )

**Comment by jeremy** [comment]
Agree, @nateless. Please do pursue a PR!

For starters, we could disallow actions initiated before the channel is subscribed. That'd reflect the current behavior properly and fail fast rather than dropping on the floor.

Then we can follow up by buffering actions until subscription is confirmed and flushing them thereafter. Getting error feedback here is a challenge, though. Forcing the caller to be aware of subscription state and cope with non-active channels may turn out to be a better experience.

**Comment by jeremy** [comment]
Yes indeed!

**Comment by danielrhodes** [comment]
I never understood the need to subscribe to a channel before being able to send an action to a channel. It makes sense that you would want to subscribe before receiving data from a channel. Perhaps that is the change that should be made, then we don't have to think about buffering, etc.

**Comment by hmspider** [comment]
@danielrhodes, an obvious need IMHO is for server to check whether it should accept the subscription at all. Think channel reserved for some user profiles only.
So far there seems to have been a focus on user-unique channels, even in example code, but the  publish in pubsub is actually a broadcast concept.

**Comment by danielrhodes** [comment]
Yes agreed. There should be a mechanism to reject a channel subscription.

Personally I don't think a subscription ought to be required to interact with a channel. It would be better if you could send a message to a channel without a subscription and only if you want to receive broadcasts should it be necessary to subscribe.

**Comment by hmspider** [comment]
That would be a publisher in pubsub parlance. Pubsub is highly assymetric, inasmuch subscribers themselves only receive broadcast messages. ActionCable doesn't distinguish those roles, though. You'd have to implement that behaviour server-side if need be.

@jeremy, I guess Promises could be a nice fit here. No buffering and flushing needed, error handling is builtin. Granted, Browser support is an issue here.
