### ISSUE TITLE
5.0.0.rc1: Regression: Unable swap to a custom connection pool and back to AR::Base pool after #24844

### ISSUE THREAD

**Issue by jrafanie** [rails/rails#24959]
### Steps to reproduce

See [the failing AR test case and output](https://gist.github.com/jrafanie/a27f713e791875a45a007aebb013e539#file-test_for_swapping_connection_pools-diff-L31).  I wasn't sure where the fix/test for this should live but I believe the test case is valid in terms of testing how `remove_connection` should undo what `establish_connection` does.

### Expected behavior
`klass2.remove_connection` should remove any custom connection pool and allow the superclass's pool to be used by resetting caches/ivars indicating a custom pool is to be used.

### Actual behavior
#24844's refactoring changed behavior when you configure a custom connection and remove it.  Any subsequent calls to `connection` from that model will fail to find a pool and NOT fallback to the superclass' pool. 

```ruby
klass2.establish_connection(custom_config)
# code
klass2.remove_connection
klass2.connection  # raises ActiveRecord::ConnectionNotEstablished: No connection pool with id klass2 found
```

#### Workaround 1

```ruby
klass2.establish_connection(custom_config)
# code
klass2.remove_connection
klass2.connection_specification_name = "primary" # this gets us back the primary pool
klass2.connection
```

#### Workaround 2
```ruby
klass2.establish_connection(custom_config)
# code
klass2.remove_connection
klass2.establish_connection # this gets us back the primary pool
klass2.connection
```

Neither of these changes were needed prior to #24844.

### System configuration
**Rails version**: 5.0.0.rc1

**Ruby version**: 2.2.4

**Comment by arthurnn** [comment]
https://github.com/rails/rails/commit/d6f3ad7ce7066b8815b4bda4a1e843b2c72c2ad3 should fix the issue..
thanks for reporting , and let me know if it works.

**Comment by arthurnn** [comment]
backported to 5-0-stable 6458610d0b95049bbc847cbc1039d6f5be8cc30c
