### ISSUE TITLE
AR associations and scopes behave totally different

### ISSUE THREAD

**Issue by rwz** [rails/rails#24960]
Using ActiveRecord 4.2.6

Example 1:

```ruby
class User < ActiveRecord::Base
  has_many :authorizations
  has_many :access_tokens, through: :authorizations
end

class Authorization < ActiveRecord::Base
  belongs_to :user
  has_many :access_tokens
end

class AccessToken < ActiveRecord::Base
  belongs_to :authorization
end
```

Trying to delete all user tokens:

```ruby
user = User.find(123)

user.access_tokens.delete_all
# exception
# => ActiveRecord::HasManyThroughCantAssociateThroughHasOneOrManyReflection: Cannot modify association 'User#access_tokens' because the source reflection class 'AccessToken' is associated to 'Oauth::Authorization' via :has_many.

user.access_tokens.scope.delete_all
# as expected
# (SQL) DELETE FROM "access_tokens" WHERE "access_tokens"."id" IN (SELECT "access_tokens"."id" FROM "access_tokens" INNER JOIN "authorizations" ON "access_tokens"."authorization_id" = "authorizations"."id" WHERE "authorizations"."user_id" = 123)
```

The first call to `delete_all` on Associations CollectionProxy does something completely unexpected and tries to update the collection failing the mutability check, while calling the same method on a AssociationRelation does exactly what is expected, deletes the records.

Example 2:

```ruby
class User < ActiveRecord::Base
  has_many :sessions
end

class Session < ActiveRecord::Base
  belongs_to :user
end

user.sessions.delete_all
# (SQL) UPDATE "sessions" SET "user_id" = NULL WHERE "sessions"."user_id" = 123

user.sessions.scope.delete_all
# (SQL) DELETE FROM "sessions" WHERE "sessions"."user_id" = 123
```

Here again, `delete_all` on a CollectionProxy nullifies the foreign key for some reason, while same method on a AssociationRelation scope does exactly what is expected, deletes the records.

All documentation kind of makes it look like scopes and associations behave the same and should be interchangeable most of the time. You can even specify conditions on the association the same way you can do it on scopes. But this example shows that this is not true.

Is that intended? What's the reason for making similar things produce such drastically different results?

I have many years of Rails experience but this completely caught me off guard.

**Comment by sgrif** [comment]
Yes, this is the intended behavior. Associations have different semantics for deletion than the underlying query that it may perform.

**Comment by rwz** [comment]
> Associations have different semantics for deletion than the underlying query that it may perform.

What's the reasoning behind that? Is there any documentation you could point to that describes those differences?
