### ISSUE TITLE
Can't serve assets with numbers in the filename

### ISSUE THREAD

**Issue by rstacruz** [rails/rails#24970]
It seems assets in the format `<letters>-<7 digits or more>.jpg` can't be served in development. I've tried it with variations of this format:
- `i-0000000.jpg`
- `abc/i-0000000.jpg`
- `abc/i-1234567.jpg`
- `abc/defghi-1234567.jpg`
- `abc/image-123456789.jpg`
- `abc/def/image-123456789.jpg`
- _and so on..._
### Steps to reproduce
- Start with a Rails app in v4.2.6
- Make sure that `config.serve_static_files = true` in development mode
- Run its development server
- Create an image file `app/assets/images/i-123456789.jpg`
- Run: `curl http://localhost:3000/assets/i-123456789.jpg`
### Expected behavior
- It should serve the image.
### Actual behavior
- I get a `No route matches /assets/i-123456789.jpg` error.
- I made sure `/public/assets` is not present.
- I've also tried using `image_tag`, `asset_path` and `asset_url` helpers, but they don't seem to help.
- I've tried using underscores instead (`abc_123456789.jpg`), that works.

![image](https://cloud.githubusercontent.com/assets/74385/15176479/d8a925ac-179d-11e6-9454-9fc1ff6ae5e1.png)
### System configuration

**Rails version**: observed on 4.2.5, 4.2.6, and 5.0.0-rc1.

**Ruby version**: 2.3.0

**Comment by prathamesh-sonpatki** [comment]
@rstacruz Will it be possible for you to upload a sample app to github reproducing the issue?

Thanks for the bug report.

**Comment by sblackstone** [comment]
If you create the image in app/assets/images and then do something like -

image_tag('i-0000000') - you should end up seeing the generated url with the sprockets suffix - worked ok here in RC1...

**Comment by rstacruz** [comment]
Hmm, I'm having trouble reproducing the issue now.. The image_tag helper
seems to be fine in a fresh app. I'll try to isolate it.
On May 12, 2016 3:00 AM, "Stephen Blackstone" <notifications@github.com>
wrote:

If you create the image in app/assets/images and then do something like -

image_tag('i-0000000') - you should end up seeing the generated url with
the sprockets suffix - worked ok here in RC1...

—
You are receiving this because you were mentioned.
Reply to this email directly or view it on GitHub
<https://github.com/rails/rails/issues/24970#issuecomment-218556574>

**Comment by notrab** [comment]
Also unable to replicate in 4.2.6 and RC1.
