### ISSUE TITLE
How to make state consistency while using Action Cable.

### ISSUE THREAD

**Issue by nateless** [rails/rails#24976]
Hey,

I've tried to ask in rails core group and on [stackoverflow](http://stackoverflow.com/questions/37147593/how-to-make-state-consistency-while-using-action-cable) but haven't got any replies within two days. It might be not a good place for such question, but we can also use it to improve documentation to describe such use cases which is not clear for new users.

Let's assume we use something like current_user which is an instance of a ServiceClass which holds user model, session params and other info. The thing is that variable is being set during connection with websocket and being reused for all AC calls on **different** subscriptions.

Then, at some point user decides to update his username, we make a call to some channel, let's say `SettingsChannel#update` and update user data `current_user.update(new_username)` and it works okay for that channel.

But other AC subscriptions under that user still use old user model. I suppose as each subscription works under their own thread, thus updating user model under one thread will not update them under other threads.

So the question is how should we process with variables which can be used across many subscriptions for subscribed user?

```ruby
module ApplicationCable
    class Channel < ActionCable::Channel::Base
      def current_user
        @current_user ||= ServiceClass.new(request_data, user_data)
      end
    end
end

class ServiceClass

def initialize(session,...)
  @session = session
  @user = current_user
end

 def update!(username)
  @user.username = username
  @user.save!
 end

 ...
end
```

**Comment by jeremy** [comment]
Simplest option is to disconnect existing Cable connections when user data is changed:
```ruby
ActionCable.server.remote_connections.where(current_user: User.find(1)).disconnect
```
That'll cause the user to automatically reconnect and pull fresh user/service data.

**Comment by nateless** [comment]
@jeremy, well, we can also make a refresh on the client as well. Aren't we have any better option?

**Comment by jeremy** [comment]
@nateless Better in what sense? When state changes, you need to broadcast it out to everyone who has stale state. You can built a sophisticated state syncing mechanism, or you can invalidate stale state and start fresh. One system is probably going to be easier to build, debug, and reason about than the other 😊

**Comment by nateless** [comment]
@jeremy better in sense of not restarting like 10+ subscriptions with reinitialization because we need to update one variable (which is going to be on the client too, when he might be in the middle of something). It's a hack not a solution. And we will see more questions like this one for sure as soon as big projects will start to move to WS. 

How you guys handle such thing in Basecamp, don't you have any global service layer which holds some state to prevent regular model fetch from database or from identity_cache or other caching methods?

**Comment by jeremy** [comment]
I get why reconnection feels like a hack to you. To me, the hack is
designing a system that encourages stale state and then designing a
sophisticated state sync mechanism to address it.

Action Cable is responsible for implicitly suggesting this by hanging on to
user/account/etc from when the connection was initiated. Apps are
responding by using connection/channel state without regard for their
staleness.

For most apps in this boat, the path is straightforward. If you have
frequently changing state, fetch from an authoritative source when you need
it. Don't cache a stale copy. Push that responsibility out; fetch a fresh
record from a db replica, from your own cache, wherever.

The most common case for this is authorization changes. A user can now
access other data in the app, or their access has been revoked. If you
check against local state… you're gonna have a bad time. If you try to
coordinate distributed state sync/updates… you're gonna be eating bug after
bug. Revalidating state eliminates these classes of problems wholesale.
