### ISSUE TITLE
has_many / has_one polymorphic associations generate error on join

### ISSUE THREAD

**Issue by pihman** [rails/rails#24987]
After upgrading from Ruby 2.2.4 => 2.3.1 (Rails 3.2.22) , ActiveQuery joins between polymorphic has_one/has_many associations raise errors.
### Steps to reproduce

```
class Address < ActiveRecord::Base
  belongs_to :addressable, polymorphic: true
end

class User < ActiveRecord::Base
  has_many :addresses, as: :addressable, dependent: :destroy
end
```

The polymorphic association works fine when invoked from a single instance:

```
User.find(1234).addresses
=> [ list of user addresses ]
```

But fails when invoked via an ActiveRecord query:

```
User.joins(:addresses).where(id: 1234)
=> (pry) output error: #<TypeError: no implicit conversion of nil into String>
```
### Expected behavior

The ActiveQuery should run a query and return a list of Addresses.
### Actual behavior

A vague TypeError is raised.
### System configuration

**Rails version**: 3.2.22, 3.2.22.2

**Ruby version**: 2.3.1

OSX El Capitan

I know Rails 3.2.22 isn't certified for Ruby 2.3 yet.  Here's hoping...

**Comment by maclover7** [comment]
Rails 3.2 is no longer supported for bug fixes. Does this error occur on Rails master?

**Comment by al2o3cr** [comment]
@pihman Can you paste a complete stack trace? That `TypeError` could be coming from lots of places, and it's difficult to troubleshoot without a trace.

**Comment by jhanggi** [comment]
Take a look over at https://github.com/rails/rails/issues/25010 They have a good explanation about what is likely the same problem and a workaround.
