### ISSUE TITLE
redirect_to ignores cache and destination url is still stale.

### ISSUE THREAD

**Issue by phlegx** [rails/rails#24985]
### Steps to reproduce

`redirect_to` ignores cache and destination url is still stale. I have a post action that redirects to another path on success. The problem is, that the destination path always has set the cache control to no-cache even if the cache control is set in the destination path controller action.

### Expected behavior
`redirect_to` in controller action redirects like expected but the destination should use the cache control set in controller:

```ruby
class ProjectsController < ApplicationController
    etag { current_user.id }

    def index
        redirect_to project_path(Project.first)
    end

    def show
        @project = Project.first
        expires_in 1.hour.to_i, public: true
        if stale?(@project, public: true)
            # do some work here and render view
        end
    end
end
```

### Actual behavior
`redirect_to` in controller action redirects like expected but the destination has the cache control in the response headers set to no-cache and is still stale:

```log
Cache-Control: no-cache, no-store
Etag	"2d34e3b540464e0267323de3819e3ccb"
```

### System configuration
**Rails version**: 4.2.3
**Ruby version**: 2.2.3

**Comment by maclover7** [comment]
Can you create an executable test script using one of the templates [here](https://github.com/rails/rails/tree/master/guides/bug_report_templates), that would demonstrate the problem you are seeing?

**Comment by phlegx** [comment]
@maclover7 please delete this issue. **It is invalid!** Sorry.
