### ISSUE TITLE
Rails g controller  Access denied  (Mysql2::Error)

### ISSUE THREAD

**Issue by RTJ** [rails/rails#24995]
### Steps to reproduce
`rails db:create # ( OK )
rails db:migrate # ( OK )

 Created database 'test_development'
 Created database 'test_test'`

### **`rails g controller Demos new create destroy`**

`/home/vagrant/.rvm/gems/ruby-2.3.1/gems/mysql2-0.4.4/lib/mysql2/client.rb:87:in `connect': Access denied for user 'root'@'localhost' (using password: NO) (Mysql2::Error)
        from /home/vagrant/.rvm/gems/ruby-2.3.1/gems/mysql2-0.4.4/lib/mysql2/client.rb:87:in `initialize'
        from /home/vagrant/.rvm/gems/ruby-2.3.1/gems/activerecord-5.0.0.rc1/lib/active_record/connection_adapters/mysql2_adapter.rb:25:in `new'
        from /home/vagrant/.rvm/gems/ruby-2.3.1/gems/activerecord-5.0.0.rc1/lib/active_record/connection_adapters/mysql2_adapter.rb:25:in `mysql2_connection'
        from /home/vagrant/.rvm/gems/ruby-2.3.1/gems/activerecord-5.0.0.rc1/lib/active_record/connection_adapters/abstract/connection_pool.rb:721:in `new_connection'
        from /home/vagrant/.rvm/gems/ruby-2.3.1/gems/activerecord-5.0.0.rc1/lib/active_record/connection_adapters/abstract/connection_pool.rb:765:in `checkout_new_connection'
        from /home/vagrant/.rvm/gems/ruby-2.3.1/gems/activerecord-5.0.0.rc1/lib/active_record/connection_adapters/abstract/connection_pool.rb:744:in `try_to_checkout_new_connection'
        from /home/vagrant/.rvm/gems/ruby-2.3.1/gems/activerecord-5.0.0.rc1/lib/active_record/connection_adapters/abstract/connection_pool.rb:705:in `acquire_connection'
        from /home/vagrant/.rvm/gems/ruby-2.3.1/gems/activerecord-5.0.0.rc1/lib/active_record/connection_adapters/abstract/connection_pool.rb:501:in `checkout'
        from /home/vagrant/.rvm/gems/ruby-2.3.1/gems/activerecord-5.0.0.rc1/lib/active_record/connection_adapters/abstract/connection_pool.rb:364:in `connection'
        from /home/vagrant/.rvm/gems/ruby-2.3.1/gems/activerecord-5.0.0.rc1/lib/active_record/connection_adapters/abstract/connection_pool.rb:877:in `retrieve_connection'
        from /home/vagrant/.rvm/gems/ruby-2.3.1/gems/activerecord-5.0.0.rc1/lib/active_record/connection_handling.rb:128:in `retrieve_connection'
        from /home/vagrant/.rvm/gems/ruby-2.3.1/gems/activerecord-5.0.0.rc1/lib/active_record/connection_handling.rb:91:in `connection'
        from /home/vagrant/.rvm/gems/ruby-2.3.1/gems/activerecord-5.0.0.rc1/lib/active_record/query_cache.rb:47:in `block in install_executor_hooks'
        from /home/vagrant/.rvm/gems/ruby-2.3.1/gems/activesupport-5.0.0.rc1/lib/active_support/callbacks.rb:396:in `instance_exec'
        from /home/vagrant/.rvm/gems/ruby-2.3.1/gems/activesupport-5.0.0.rc1/lib/active_support/callbacks.rb:396:in `block in make_lambda'
        from /home/vagrant/.rvm/gems/ruby-2.3.1/gems/activesupport-5.0.0.rc1/lib/active_support/callbacks.rb:169:in `block (2 levels) in halting'
        from /home/vagrant/.rvm/gems/ruby-2.3.1/gems/activesupport-5.0.0.rc1/lib/active_support/callbacks.rb:547:in `block (2 levels) in default_terminator'
        from /home/vagrant/.rvm/gems/ruby-2.3.1/gems/activesupport-5.0.0.rc1/lib/active_support/callbacks.rb:546:in `catch'
        from /home/vagrant/.rvm/gems/ruby-2.3.1/gems/activesupport-5.0.0.rc1/lib/active_support/callbacks.rb:546:in `block in default_terminator'
        from /home/vagrant/.rvm/gems/ruby-2.3.1/gems/activesupport-5.0.0.rc1/lib/active_support/callbacks.rb:170:in `block in halting'
        from /home/vagrant/.rvm/gems/ruby-2.3.1/gems/activesupport-5.0.0.rc1/lib/active_support/callbacks.rb:454:in `block in call'
        from /home/vagrant/.rvm/gems/ruby-2.3.1/gems/activesupport-5.0.0.rc1/lib/active_support/callbacks.rb:454:in `each'
        from /home/vagrant/.rvm/gems/ruby-2.3.1/gems/activesupport-5.0.0.rc1/lib/active_support/callbacks.rb:454:in `call'
        from /home/vagrant/.rvm/gems/ruby-2.3.1/gems/activesupport-5.0.0.rc1/lib/active_support/callbacks.rb:101:in `__run_callbacks__'
        from /home/vagrant/.rvm/gems/ruby-2.3.1/gems/activesupport-5.0.0.rc1/lib/active_support/callbacks.rb:750:in `_run_complete_callbacks'
        from /home/vagrant/.rvm/gems/ruby-2.3.1/gems/activesupport-5.0.0.rc1/lib/active_support/callbacks.rb:90:in `run_callbacks'
        from /home/vagrant/.rvm/gems/ruby-2.3.1/gems/activesupport-5.0.0.rc1/lib/active_support/execution_wrapper.rb:107:in `complete!'
        from /home/vagrant/.rvm/gems/ruby-2.3.1/gems/activesupport-5.0.0.rc1/lib/active_support/execution_wrapper.rb:64:in `ensure in block in run!'
        from /home/vagrant/.rvm/gems/ruby-2.3.1/gems/activesupport-5.0.0.rc1/lib/active_support/execution_wrapper.rb:64:in `block in run!'
        from /home/vagrant/.rvm/gems/ruby-2.3.1/gems/activesupport-5.0.0.rc1/lib/active_support/execution_wrapper.rb:58:in `tap'
        from /home/vagrant/.rvm/gems/ruby-2.3.1/gems/activesupport-5.0.0.rc1/lib/active_support/execution_wrapper.rb:58:in `run!'
        from /home/vagrant/.rvm/gems/ruby-2.3.1/gems/activesupport-5.0.0.rc1/lib/active_support/execution_wrapper.rb:74:in `wrap'
        from /home/vagrant/.rvm/gems/ruby-2.3.1/gems/activesupport-5.0.0.rc1/lib/active_support/reloader.rb:45:in `reload!'
        from /home/vagrant/.rvm/gems/ruby-2.3.1/gems/spring-1.7.1/lib/spring/application.rb:154:in `serve'
        from /home/vagrant/.rvm/gems/ruby-2.3.1/gems/spring-1.7.1/lib/spring/application.rb:131:in `block in run'
        from /home/vagrant/.rvm/gems/ruby-2.3.1/gems/spring-1.7.1/lib/spring/application.rb:125:in `loop'
        from /home/vagrant/.rvm/gems/ruby-2.3.1/gems/spring-1.7.1/lib/spring/application.rb:125:in `run'
        from /home/vagrant/.rvm/gems/ruby-2.3.1/gems/spring-1.7.1/lib/spring/application/boot.rb:19:in `<top (required)>'
        from /home/vagrant/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /home/vagrant/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'`

### System configuration
**Rails version**: 5.0.0.rc1

**Ruby version**: ruby 2.3.1p112 (2016-04-26 revision 54768) [x86_64-linux]

**the database works well from rails if I use a controller created by hand.**

**Comment by rafaelfranca** [comment]
Can you please provide a sample application that reproduces the error?

**Comment by RTJ** [comment]
Hi, it was new app created with rails 5 rc1 and mysql db, i tried to create first controller.
For now i solved this problem removing root password in mysql.

**Comment by rafaelfranca** [comment]
I tried to reproduce and could not so I think it is something in your environment. Let me know if you know a way to reproduce this and I'll reopen the issue.
