### ISSUE TITLE
Controllers and models don't reload in dev with Puma Workers enabled

### ISSUE THREAD

**Issue by mgomes** [rails/rails#24990]
### Steps to reproduce

1. Create a new Rails 5.0.0rc1 app
2. Create a dummy route, controller, and controller action
3. Uncomment the `workers ENV.fetch("WEB_CONCURRENCY") { 2 }` line from `puma.rb`
4. `rails server`
5. Visit your action
6. Introduce an exception into the action
7. Re-visit the action

### Expected behavior
The new exception that was introduced should be raised.

### Actual behavior
The page loads fine and the new code added to the action is ignored.

### System configuration
**Rails version**: 5.0.0rc1

**Ruby version**: 2.3.1

**Comment by tyler6699** [comment]
I have experienced a similar issue with Docker and my Rails 5 app, classes appear to cache, restarting the app multiple times eventually fixes the issue. So I am not using Docker in dev at the moment.

I uncommented the line of code (point 3.) and I get the same issue I had using Docker. Not sure if this is related to my issue in Docker or not but will keep an eye on this issue.

**Comment by maclover7** [comment]
cc @schneems @evanphx

**Comment by prathamesh-sonpatki** [comment]
@mgomes Can you also post the version of Puma gem that you are using?

**Comment by mgomes** [comment]
Puma 3.4.0.

**Comment by PiotrMisiurek** [comment]
We also have this issue with puma 3.4.0

**Comment by toobulkeh** [comment]
Have you tried a `spring stop` command in another terminal?

**Comment by Fudoshiki** [comment]
rails 5.0.rc1, ruby 2.3.1, same issue with uncommented workers `ENV.fetch("WEB_CONCURRENCY") { 2 }`, with `workers ENV.fetch("WEB_CONCURRENCY") { 1 }` don't work too

**Comment by MSchmidt** [comment]
I've worked around this by disabling multiple workers in ``development``:

```ruby
if ENV.fetch("RAILS_ENV") { "development" } != 'development'
  workers ENV.fetch("WEB_CONCURRENCY") { 2 }
  
  preload_app!
  
  on_worker_boot do
    ActiveRecord::Base.establish_connection if defined?(ActiveRecord)
  end
end
```

**Comment by schneems** [comment]
This is a bug. I can confirm i'm able to reproduce. We need to fix this. 

When I boot through the `$ puma` command the problem does not happen, when I boot through `$ rails server` it does.

Hey @evanphx. I haven't dug in much. I'm guessing this has something to do with the way that code is reloaded in the rack handler versus the `puma` CLI. If you have any tips on places to start looking would appreciate a jumping off point.

**Comment by maqen** [comment]
Seeing in console that puma runs in single mode versus clustered mode when workers is not explicitly set as per @MSchmidt for example.

My guess is that puma setting `threadsafe` when running in clustered mode and therefore setting `cache_classes=true` as per rails default.

**Comment by schneems** [comment]
Looks like there's a pretty big difference between what gets passed to the Puma::Launcher from `rails s` versus `puma` commands https://www.diffchecker.com/qsa3thos. 

This is from debug added to Puma::Launcher

```
    def initialize(conf, launcher_args={})
      puts "==========================="
      puts conf.inspect
      puts launcher_args.inspect
      puts caller
```

It's weird that the errors get cached for models and controllers but not in views.

**Comment by schneems** [comment]
It looks like https://github.com/rails/rails/blob/master/railties/lib/rails/application/finisher.rb#L135 is being called when we boot via `$ puma` but not when we boot via `$ rails s`. @matthewd looks like you touched that reloader code recently, any theories or ideas on  what is causing it to not get called when booted with one command?

**Comment by schneems** [comment]
Little more progress. It looks like what is happening is that initialization code is being run in each process when we boot via `puma` but it is being run in a different process (not in a puma worker) when we boot via `rails s`

Here's some debug output, note the PID

PID of that hook is different than any of the puma worker PIDs:

```
$ rails s
=> Booting Puma
=> Rails 5.0.0.rc1 application starting in development on http://localhost:3000
=> Run `rails server -h` for more startup options
=======================
PID: 62608
[62608] Puma starting in cluster mode...
[62608] * Version 3.4.0 (ruby 2.3.1-p112), codename: Owl Bowl Brawl
[62608] * Min threads: 5, max threads: 5
[62608] * Environment: development
[62608] * Process workers: 2
[62608] * Phased restart available
[62608] * Listening on tcp://localhost:3000
[62608] Use Ctrl-C to stop
[62608] - Worker 0 (pid: 62634) booted, phase: 0
[62608] - Worker 1 (pid: 62635) booted, phase: 0
```

PID that is executed in that hook is same as puma worker process PID:

```
$ puma
[62677] Puma starting in cluster mode...
[62677] * Version 3.4.0 (ruby 2.3.1-p112), codename: Owl Bowl Brawl
[62677] * Min threads: 5, max threads: 5
[62677] * Environment: development
[62677] * Process workers: 2
[62677] * Phased restart available
[62677] * Listening on tcp://0.0.0.0:3000
[62677] Use Ctrl-C to stop
[62678] + Gemfile in context: /private/tmp/example-24990/Gemfile
[62679] + Gemfile in context: /private/tmp/example-24990/Gemfile
WARN: Unresolved specs during Gem::Specification.reset:
      json (>= 0)
WARN: Clearing out unresolved specs.
Please report a bug if this causes problems.
WARN: Unresolved specs during Gem::Specification.reset:
      json (>= 0)
WARN: Clearing out unresolved specs.
Please report a bug if this causes problems.
=======================
PID: 62678
[62677] - Worker 0 (pid: 62678) booted, phase: 0
=======================
PID: 62679
[62677] - Worker 1 (pid: 62679) booted, phase: 0
```

**Comment by schneems** [comment]
In related news it looks like if you turn on `preload_app!` in the `puma.rb` then controller reloading fails even when you run the `$ puma` command cc/ @fxn.

We need these code reloading hooks to be valid even when the process running the original hook is not the same process that will (should) reload the code.

**Comment by matthewd** [comment]
@schneems does switching off `listen` & using the polling filesystem watcher change things?

**Comment by schneems** [comment]
Yes, commenting out this line makes the problem go away:

```ruby
  # config.file_watcher = ActiveSupport::EventedFileUpdateChecker
```

I'm able to load `$ rails server`, add `raise "foo"` to a controller, load the page. Then remove the exception and reload the page, and the exception goes away.

Shooting in the dark here, maybe listen has a connection to something that cannot be shared between processes. Not really sure.

**Comment by schneems** [comment]
I think that was a totally wrong hypothesis, this block does not get called when using the evented file checker https://github.com/rails/rails/blob/99d8d45e42ef61893171eb2dbf8ff1e6aa9f4c77/railties/lib/rails/application/finisher.rb#L158 but it does when using the older file checker. So maybe something is aborting the callback chain with the evented file checker

**Comment by schneems** [comment]
Okay, going back to original hypothesis. The callback code in that line isn't being called because `@updated` in the listener is never set to `true`. I'm leaning towards this happening because something to do with connections and forking so the listen gem isn't behaving quite like we expect it to.

**Comment by schneems** [comment]
So https://github.com/rails/rails/blob/755f6bf3d3d568bc0af2c636be2f6df16c651eb1/activesupport/lib/active_support/evented_file_update_checker.rb#L54-L58 is getting called but not in a process that is running any code. When this happens it updates the `@updated` variable but that variable isn't shared with the child processes which are handling the web requests.

In the code reloading executor gets called we could store all the PID numbers of all processes that are booted with `Listen` code and then compare that to the current process PID, if they don't match spawn a new listen process. I'm not sure the best/cleanest way to do that. It would add a PID check to each request.

**Comment by e2** [comment]
> if they don't match spawn a new listen process

Calling fork() doesn't clone threads, so a new Listen process is necessary.

> store all the PID numbers of all processes that are booted with Listen code and then compare that to the current process PID, if they don't match spawn a new listen process. I'm not sure the best/cleanest way to do that.

The alternative would be to run Listen on a socket. 

That can save some overhead and threads, especially on OSX (were there's 1 thread per watched directory - which isn't a technical constraint per say). If the socket isn't connected you can just reconnect in the forks, or start the listener "server" if it isn't started already.

**Comment by schneems** [comment]
> The alternative would be to run Listen on a socket.

I've never done that before. What exactly would that look like? You spin up the listen code in a different process and connect to a socket with some code to write to the socket when an event is triggerd, then the other processes listen on the socket and register a change when it's written? Genuinely curious of what that architecture would look like?

Right now I'm thinking that we move the code that boots listen to a middleware. That way we don't spawn 21+ threads on OSX and each process can get it's own listener.

**Comment by e2** [comment]
> Genuinely curious of what that architecture would look like?

Pretty much like you describe it. It would just save some overhead but add more code, so I don't think it's worth any time. Maybe if Listen provided this itself (which I was considering).

Still, the best solution would be to prevent the need for so many threads in the first place, see my comment here: https://github.com/rails/rails/issues/25259#issuecomment-223966052

**Comment by vovimayhem** [comment]
Ain't running more than one thread/instance something undesireable for a development flow? What's your use case for running 2+ puma workers on development?

Debugging gets pretty difficult - There's a chance that the logs might mislead you, as something happening on one worker won't prevent another worker to process another request... I've seen it happen pretty regularly on a project I'm stuck with this same situation.

The only use case I can come up with is for benchmarking concurrency on the developer's workstation... but for that I prefer to launch the app in "production" mode - not "development" - anyways...

**Comment by TJamesCorcoran** [comment]
This bug seems to exist in Puma v. 3.9.1

Is there some other version I should get, or some workaround?  Nothing mentioned above works for me. 

(This is my first experience w Puma - I discovered it a few hours ago and am trying to transition a client over to it.)

**Comment by PeteMichaud** [comment]
Still having this issue, Rails 5.1.4, puma 3.10. Contrary to what @schneems said above, running `puma` instead of `rails s` does not fix the issue. Any updates?

**Comment by igiz0l** [comment]
Was struggling from this issue last couple of months, reproducible on puma 3.2/rails 5.0.1. Setting RAILS_MAX_THREADS to 1 with puma 3.10/rails 5.1.4 helped. (OSX)

**Comment by Glutexo** [comment]
Just to say, with Rails (5.1.5) and Puma (3.11.2), it is still necessary to comment out the `config.file_watcher = ActiveSupport::EventedFileUpdateChecker` config to have controllers reloaded.

**Comment by michaeldever** [comment]
@Glutexo This that doesn't resolve the issue for me unfortunately.

**Comment by Backoo** [comment]
@Glutexo This doesn't work for me too.
I'm using rails 5.2.2 and puma 3.12

**Comment by Glutexo** [comment]
So it looks like the hack stopped working, or simply doesn’t work in every environment. Sorry, guys. :(

**Comment by patricksimpson** [comment]
Just experienced this today:
Rails 6.0.3
ruby 2.6.5p114 (2019-10-01 revision 67812) [x86_64-linux]

Commenting out: `config.file_watcher = ActiveSupport::EventedFileUpdateChecker` in `config/environments/development.rb` helped with this issue, thanks for that :tada:. 

It may be useful to point out, this was only a problem with namespace routes for some reason for me. Changing view files would not render the changes unless I stopped and restarted the rails server. Spent an hour debugging before stumbling (googling) on this.

**Comment by lucas-pitta** [comment]
Just experienced this today:
Rails 6.0.3
ruby 2.7.1

Commenting out: config.file_watcher = ActiveSupport::EventedFileUpdateChecker in config/environments/development.rb "solve" the issue for me.

Also using namespace routes as patrick :D
