### ISSUE TITLE
Request format not set when Content-Type is application/json

### ISSUE THREAD

**Issue by nicohvi** [rails/rails#25005]
### Steps to reproduce

Simply create a new rails project `rails new demo`, create a random controller, and call it using f.ex. Postman.

### Expected behavior

I'd expect the request.format to be `json`, but instead it's nil.

### Actual behavior

The format is `nil`

![screen shot 2016-05-13 at 08 53 51](https://cloud.githubusercontent.com/assets/430875/15240201/43a595d4-18e8-11e6-874d-ad2183c0ed3f.png)

![screen shot 2016-05-13 at 08 54 48](https://cloud.githubusercontent.com/assets/430875/15240215/5f0498d4-18e8-11e6-984c-ed0a9c12f2a6.png)

There might just be something I've misunderstood, or configured incorrectly, but for now this seems strange to me.

### System configuration
**Rails version**: 5.0.0.rc1

**Ruby version**: 2.3.1

**Comment by maclover7** [comment]
I think the header you are looking for here is `Content-Type`, not format 😬 https://gist.github.com/maclover7/053b466181f3ec3e9954b9a016f3aed9

**Comment by nicohvi** [comment]
Hi Jon, thanks for answering!
 
> I think the header you are looking for here is Content-Type, not format

That might very well be, but the controller still interprets the request wrong, no? Shouldn't it say `Processing by ItemsController as JSON` or something like that?

**Comment by nicohvi** [comment]
I think the problem is that I'm simply using the wrong header. If I change the header to be `Accept`, then Rails sets the mime type correctly. I suppose this is line with the HTTP [spec](https://developer.mozilla.org/en-US/docs/Web/HTTP/Content_negotiation).

**Comment by maclover7** [comment]
👍 not a bug in Rails?

**Comment by nicohvi** [comment]
Correct, Jon! 

I had misinterpreted the use of the `Content-Type` header, which is a header of the **content** and **not** the request itself. To specify what the client wants received from the server the `Accept` header is the correct choice.

**Comment by maclover7** [comment]
👍
