### ISSUE TITLE
`dependent: :destroy` may not work with default_scope

### ISSUE THREAD

**Issue by qsona** [rails/rails#25014]
Hello. I appreciate your work.
This is not a bug report, but I wonder the current behavior is desirable, so I'd like to ask you.

### Summary
I faced to a problem that I could not destroy an ActiveRecord object. The model of that object had a foreign_key constraint, and was specified `has_many xxx, dependent: :destroy`. The error was `Mysql2::Error: Cannot delete or update a parent row: a foreign key constraint fails ...`. I wondered why it occurred despite of `dependent: :destroy` .

Finally I found that the model of belonging table had `default_scope` and the problem didn't occur if I commented it out. The associated model was not found because of that default_scope so it couldn't be deleted on rails, and it failed by the constraint on database.

I can't tell whether it's a desirable behavior or not, but it was so undetectable for me to fail to destroy because of default_scope. 

Sorry, I can't describe it well, so I write whole of the steps to reproduce.

### Steps to reproduce
1 create new rails project, use `mysql2` adapter
2 shell
```
$ rails g model item
$ rails g model belong_item item:references
$ rake db:migrate
```
3 add following line to app/model/item.rb
`has_one :belong_item, dependent: :destroy`

4 rails console
```
Item.create(id: 1)
BelongItem.create(id: 1, item_id: 1)
# Item.find(1).destroy succeeds at this time
```

5 add following line to app/model/belong_item.rb
`default_scope { where(id: 10000) }`

6 rails console

```
Item.find(1).destroy
```
### Expected behavior
succeeds, both Item and BelongItem are deleted from database ?
### Actual behavior
```
ActiveRecord::StatementInvalid: Mysql2::Error: Cannot delete or update a parent row: a foreign key constraint fails (`ex_rails5`.`belong_items`, CONSTRAINT `fk_rails_163f57beae` FOREIGN KEY (`item_id`) REFERENCES `items` (`id`)): DELETE FROM `items` WHERE `items`.`id` = 1
```
### System configuration
**Rails version**: 4.2 / edge

**Ruby version**: 2.3

**Comment by maclover7** [comment]
To me this seems like expected behavior -- the end user is responsible for keeping track of how `default_scope`s influence queries. 😬

**Comment by qsona** [comment]
Thank you. We should be careful of it - or avoid using default_scope 😭
