### ISSUE TITLE
Rails 3.2.22.2 - Ruby 2.3 - Hash now responds to `to_proc` and `interpolate` blows up

### ISSUE THREAD

**Issue by tlrdstd** [rails/rails#25010]
### Background

As of Ruby 2.3, [Hash responds to `to_proc`](http://ruby-doc.org/core-2.3.0/Hash.html#method-i-to_proc) This is [a change from Ruby 2.2](http://ruby-doc.org/core-2.2.0/Hash.html).

In ActiveRecord 3.2.22.2, the `interpolate` method (duplicated across [ActiveRecord::Associations::JoinDependency::JoinAssociation](https://github.com/rails/rails/blob/3-2-stable/activerecord/lib/active_record/associations/join_dependency/join_association.rb#L148), [ActiveRecord::Associations::Association](https://github.com/rails/rails/blob/3-2-stable/activerecord/lib/active_record/associations/association.rb#L160), and [ActiveRecord::Associations::Preloader::Association](https://github.com/rails/rails/blob/3-2-stable/activerecord/lib/active_record/associations/preloader/association.rb#L115)) checks its input to see if it responds to `to_proc`.

I've seen a few bug reports on other projects that seem to be caused by this issue, but Casecommons/pg_search/issues/297 is the clearest.

### Steps to reproduce

```ruby
class Document < ActiveRecord::Base
  has_many :images, as: :parent
end
```

Calling `Document.joins(:images).count` triggers the error.

### Expected behavior
In Ruby 2.2, if passed a `Hash`, this check returned `false`, and all was well - the query returns a count.

### Actual behavior
In Ruby 2.3, if passed a `Hash`, this check returns `true`, and `interpolate` returns `nil`. This `nil` eventually gets passed to `Arel.sql()` and you get a `no implicit conversion of nil into String` error.

### System configuration
**Rails version**: 3.2.22.2

**Ruby version**: 2.3.0

### Temporary workaround

I've undefined `to_proc` on Hash, as I'm quite certain I have no code that relies on that:

```ruby
class Hash
  undef_method :to_proc if self.method_defined?(:to_proc)
end
```

**Comment by arthurnn** [comment]
@tlrdstd thanks for letting us know.
We dont support rails 3.2 anymore. But i've been responsible for patching security level concerns there.
This is not a security issue, so we probably wont release a new version for it, however if you wanna work in a PR to fix it, i would be glad to merge it to 3-2-stable branch.

Thanks

**Comment by jhanggi** [comment]
I was running into a similar issue when testing against Ruby 2.3/Rails 3.2.22.2. 

I have an association that could be soft-deleted, but when upgrading to 2.3, the conditions were no longer being respected and deleted items were being returned.

Essentially:
```ruby
class Product < ActiveRecord::Base
  has_many   :accessories, conditions: { deleted_at: nil }, dependent: :destroy
end
```

Thanks for digging in and finding out why. Your temporary workaround solves the problem for me as well.

**Comment by tlrdstd** [comment]
I've started working on a patch for this. Ran out of time this weekend, but at a quick glance, it does appear that several of the sqlite3 tests for ActiveRecord pass under Ruby 2.2 but fail under Ruby 2.3, which gives me hope for uncovering all the places affected by `Hash.to_proc`. I'll keep working on it this week.

**Comment by nodanaonlyzuul** [comment]
I just want to say thanks to @tlrdstd.
This ticket (and your PR!) just saved me a night of head scratching.
