### ISSUE TITLE
Documentation of how to contribute to documentation is out of date

### ISSUE THREAD

**Issue by dschweisguth** [rails/rails#25012]
http://edgeguides.rubyonrails.org/contributing_to_ruby_on_rails.html section 3, "Contributing to the Rails Documentation" discusses docrails. I believe, based on a little searching around just now that docrails is no longer available. I believe the only current way of updating documentation is to open a PR on rails/rails. That section should be updated to only suggest opening a PR.

I would be happy to open a PR on this, but I'd like confirmation that my understanding of the current process is correct.

**Comment by maclover7** [comment]
@rafaelfranca @vijaydev thoughts? I think we only use docrails internally now.

**Comment by rafaelfranca** [comment]
That section is still correct. It say "You can either open a pull request to Rails or ask the Rails core team for commit access on docrails if you contribute regularly.", so if you ask the core team commit access to docrails you will get it.
