### ISSUE TITLE
Misleading minimal version in "Getting started" for 4.2.6 (or compatibility of 4.2.6 Rails with Ruby 1.9.3 was unintentionally broken)

### ISSUE THREAD

**Issue by matkoniecz** [rails/rails#25019]
### Steps to reproduce

Open http://guides.rubyonrails.org/
Select http://guides.rubyonrails.org/getting_started.html
Run `rails new blog`
It results in

> Gem::InstallError: mime-types-data requires Ruby version >= 2.0.

full gist: https://gist.github.com/matkoniecz/6fc20378d7c74d0529b677d3d8499cb6

### Expected behavior
Following http://guides.rubyonrails.org/getting_started.html is possible on systems with minimal listed requirements (including `The Ruby language version 1.9.3 or newer.`)

### Actual behavior

> Gem::InstallError: mime-types-data requires Ruby version >= 2.0.

### System configuration
**Rails version**: 4.2.6

**Ruby version**: 1.9.3

**Comment by tvanderpol** [comment]
I'm trying to get a handle on some Rails issues and had a brief look into this. As per https://github.com/mime-types/mime-types-data/issues/1 The last version anyone needing to use ruby 1.9.x should depend on is 2.6.2 . Any higher and it'll require ruby 2.

What I can't work out is where the mime-type dependency comes from, it's clearly not a direct dependency for rails. I checked `rack-test` and `rack` but no mention there either.

**Comment by sevenseacat** [comment]
It comes from the `mail` gem, which is a dependency of ActionMailer.

**Comment by tvanderpol** [comment]
In that case https://github.com/mikel/mail/commit/0277b8ee3204a3971fdfd6d92fd65ef80e9e9879 fixes it

**Comment by matkoniecz** [comment]
And in that case I reported duplicate of #24749
