### ISSUE TITLE
ActiveModel::Errors[5.0.0.rc1] - difference between messages and details attributes

### ISSUE THREAD

**Issue by GRoguelon** [rails/rails#25025]
Hi,

I identified a weird behavior and I think it could be a bug. The problem is located on the validation of a record and a belongs_to association with required option to true.

### Steps to reproduce

```ruby
#!/usr/bin/env ruby

begin
  require 'bundler/inline'
rescue LoadError => e
  $stderr.puts 'Bundler version 1.10 or later is required. Please update your Bundler'
  raise e
end

gemfile(true) do
  source 'https://rubygems.org'
  gem 'rails', '>= 5.0.0.rc1', '< 5.1.0'
  gem 'sqlite3'
end

require 'active_record'
require 'minitest/autorun'
require 'logger'

# This connection will do for database-independent bug reports.
ActiveRecord::Base.establish_connection(adapter: 'sqlite3', database: ':memory:')
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :posts, force: true do |t|
  end

  create_table :comments, force: true do |t|
    t.integer :post_id
  end
end

class Post < ActiveRecord::Base
  has_many :comments
end

class Comment < ActiveRecord::Base
  belongs_to :post, required: true
end

class BugTest < Minitest::Test
  def test_association_stuff
    comment = Comment.new.tap(&:valid?)
    assert comment.errors.added?(:post, :required)
    assert(comment.errors.details[:post].one? { |error|
      error[:error] == :required
    })
  end
end
```

### Expected behavior
I saw the belongs_to instruction adds a required presence with the message `required`, I guess by consistency, the details hash should contain an error `required`.

### Actual behavior
But in the details hash, we get a `blank` message whereas the `#added?` method takes a `required` message.

### System configuration
**Rails version**:
Rails 5.0.0.rc1, I couldn't test with the master branch and the template provided above, I think the `bundler/inline` feature doesn't work with Git source.

**Ruby version**:
Ruby 2.3.1

I tried to look for the origin of the problem but i didn't have enough time to understand the whole process.

**Comment by maclover7** [comment]
I think the `details` hash contains "what happened" that caused the error -- in this case the post for the comment was `blank`. If more documentation could be added here to make this clearer, please do send in a PR!

Lightly edited reproduction script available here --> https://gist.github.com/maclover7/7ffbee848b2ca84dc4ff66331716bcf9, as well as documentation available here --> http://edgeguides.rubyonrails.org/active_record_validations.html#validations-overview-errors-details

**Comment by morgoth** [comment]
This is because presence validator is used https://github.com/rails/rails/blob/a4b3c78e8619ba84625ceb83118915ef36ec2cfc/activerecord/lib/active_record/associations/builder/belongs_to.rb#L137
Not sure if this is a bug. It might be a little confusing as generated message is different than in presence validator by default

**Comment by rafaelfranca** [comment]
Yes, it is not a bug. `:required` is a message, like `"Something is required"`. It is a free text that in this case it was chosen to use the i18n feature. details is about the cause of the error, not the message. The cause is the attribute being blank and that is correctly set in the details hash.

**Comment by GRoguelon** [comment]
Ok, thanks a lot for your answers. Effectively, maybe a few of documentation could be added. I will see if the guide can be improved on that.
