### ISSUE TITLE
Rails 5.0.0.rc1 image_tag issue on Heroku

### ISSUE THREAD

**Issue by SylarRuby** [rails/rails#25021]
Ruby 2.3.0

Whenever I have added a new image then the code `<%= image_tag("o-section/mascot.svg") %>` I get an error in the heroku logs:

> ActionView::Template::Error (Unexpected token punc «(», expected punc «:» (line: 23041, col: 10, pos: 685332) error

This is due to the `image_tag`. Remove this line the website loads. I can confirm that the image is uploaded to heroku.

Any help? Works ok with Rails 4.2.6

**Comment by schneems** [comment]
I'm guessing one of those characters is not what it seems. Maybe a mismatched quote perhaps? Try deleting the string and re typing it. Does the problem happen locally? Can you give us an example app that reproduces the problem?

**Comment by SylarRuby** [comment]
@schneems All green lights locally. If I remove `image_tag`, the website loads, I dont understand.

**Comment by schneems** [comment]
Try deleting the string and re typing it. Can you give us an example app that reproduces the problem?

**Comment by SylarRuby** [comment]
@schneems not sure what you mean by giving an example. A gist? Deleting/re typing still no difference.

**Comment by schneems** [comment]
Go into a new directory run `rails new example_app` add that line to a view and make sure the problem reproduces on Heroku. If it does upload it to github and link to it on this thread.

**Comment by SylarRuby** [comment]
@schneems Turns out it was triggered by a js function:

```
foo() {
 ...
}

```

instead I should of had:

```
foo: function() {
 ...
}

```

White this solved the issue, new changed were not compiling. With Rails 4+, it was. Since I'm using Rails 5, I had to `rake assets:precompile`, then push to heroku. All is well now.
