### ISSUE TITLE
Documentation on engine decorators

### ISSUE THREAD

**Issue by Nondv** [rails/rails#25027]
Hello everyone!

[link](http://edgeguides.rubyonrails.org/engines.html#overriding-models-and-controllers)

I think it would be good to add advice to add decorators directory to `Spring.watch`.
Today I was facing some problems with it and at last I realized that problem was that Spring does not watch decorators.

It is not related to engines or decorators directly, but it would be nice and confy to have this advice there (and in all places where custom directories are being referenced), imho.

Sorry for my english.

**Comment by rafaelfranca** [comment]
Thank you for reporting. Feel free to submit a pull request. That guide is work in progress and may have incomplete/incorrect information so we can't consider it a bug.
