### ISSUE TITLE
Rake should not be loaded when I start a server/console/runner

### ISSUE THREAD

**Issue by grosser** [rails/rails#25029]
In rails 4.2.6 rake is not loaded which saves ~100ms of startup time ... in rails 5 it is loaded by https://github.com/rails/rails/blob/master/railties/lib/rails/commands/rake_proxy.rb#L1

Removing it keeps runner/console/server working ... 
using `autoload :Rake` does not solve it since during the boot process `module Rake` is used which triggers the autoload ... alternatively make rake require lazy ... not sure if that is an option though ...

Not a high priority issue, but wanted to bring that to attention / make it findable ...

### Steps to reproduce

`rails runner "puts defined?(Rake)"`

### Expected behavior
Not defined

### Actual behavior
Defined

### System configuration
**Rails version**: 5.0.0.rc1

**Comment by rafaelfranca** [comment]
cc @kaspth if you want to fix. Otherwise I'll have a look when I can.

**Comment by kaspth** [comment]
Sure, I can take a look at it ❤️

r? @kaspth

**Comment by kaspth** [comment]
Backported to 5-0-stable in 3435a36

**Comment by kaspth** [comment]
Thanks for the issue, @grosser! I think I got this bug squashed and you can look forward to this in 5.0.1 when it ships.
