### ISSUE TITLE
http://guides.rubyonrails.org/security.html - "To date MD5 is uncompromised"

### ISSUE THREAD

**Issue by matkoniecz** [rails/rails#25032]
### Steps to reproduce

visit http://guides.rubyonrails.org/security.html

### Expected behavior

http://guides.rubyonrails.org/security.html contains up to date information

### Actual behavior

http://guides.rubyonrails.org/security.html contains claim that MD5 is uncompromised

### System configuration

**Rails version**: 4.2.6

**Ruby version**: not relevant

According http://stackoverflow.com/questions/25588133/does-rails-use-compromised-md5-for-sessions problems is that 

> Bits of that guide are very out of date (eg the xss section hasn't caught up with the fact that rails considers all strings as needing escaping unless told otherwise) - it could certainly do with some love. It looks like that section hasn't been touched since at least 2009

> Rails hasn't used the method you describe for generating session ids for a long time. If I'm reading the runes correctly, since rails 2.3 the session id has been generated with SecureRandom which provides cryptographically secure random numbers (either using Ruby's builtin support on 1.8.7, or using platform specific methods such as openssl, /dev/urandom, win32 apis)

> In addition since rails 2.0, the default session store has been the cookie store which doesn't use session id in the first place (or rather the value of the session cookie is the session, rather than a key used to read the session from elsewhere)

so it is merely severe documentation problem, not a severe security problem.

Note that http://guides.rubyonrails.org/security.html is linked from http://guides.rubyonrails.org/getting_started.html#other-security-considerations

**Comment by vipulnsward** [comment]
@matkoniecz would you like to work on updating it?

**Comment by matkoniecz** [comment]
@vipulnsward I was reading http://guides.rubyonrails.org/security.html because I know nothing about this topic. O would be a able to make something but I would need to base it on other up to date guide on matching license. Can you point me to something like that?
