### ISSUE TITLE
Highlight test success/failure with colors

### ISSUE THREAD

**Issue by grosser** [rails/rails#25047]
Detecting scripts / real users is pretty easy ($stdout.tty?) and done by many libraries, it would be a nice / helpful / shiny feature to show red/green test output by default ... there can be an opt-out for the x% that either love gray or have some strange config that is pty but does not support colors, but for everyone else that should be a great addition ...

### Steps to reproduce
Run a test

### Expected behavior
Red/green

### Actual behavior
Boring / unhelpful Gray

### System configuration
**Rails version**: 5.0.0.rc1

**Comment by prathamesh-sonpatki** [comment]
@grosser It should show the colors. This feature is present from beta 1.

Please check https://monosnap.com/file/NYDnixRpYVivqqlQaID86oVp3RmE50.

Are you using any other reporters with default test runner?

**Comment by grosser** [comment]
Yes! Had minitest-color installed ... now seeing some color, but the final result is still gray:

`2 runs, 1 assertions, 0 failures, 0 errors, 0 skips` ... how about making that green/red too ? :)

**Comment by prathamesh-sonpatki** [comment]
I will try to reproduce with minitest-runner in my app. It might be getting in conflict with default reporter.

**Comment by prathamesh-sonpatki** [comment]
@grosser Tested with minitest-color on older version of Rails and it does not show colors for last line.

https://monosnap.com/file/PEbpNstaVB5CH8nfxvrVQWQu5ue98E

Or are you suggesting to add it in Rails test reporter?

**Comment by grosser** [comment]
ah yes it's minitest/rg ... I got many gems ... 
But yes, I'm suggesting to color the last line for an way to easily spot success or failure

**Comment by prathamesh-sonpatki** [comment]
Sounds like a good idea. @kaspth Thoughts?

**Comment by kaspth** [comment]
> color the last line for an way to easily spot success or failure

Isn't the fact that there are failures output enough to spot that?

<img width="454" alt="skaermbillede 2016-05-17 kl 14 39 10" src="https://cloud.githubusercontent.com/assets/350807/15322430/25d0b2e8-1c3d-11e6-9ef1-aa8292b12d22.PNG">

I'm fine with the last lines being white because some are about the run itself and doesn't really make sense to color.

Besides all that, this is really a feature request. So please do take a swing at it in a pull request :smile:

**Comment by grosser** [comment]
Yeah true, it's kind of obvious ... just got used to it :D
I might try a PR, thanks for the quick reply!
