### ISSUE TITLE
has_secure_password should check bytesize, not length

### ISSUE THREAD

**Issue by Freaky** [rails/rails#25045]
[active_model/secure_password.rb](https://github.com/rails/rails/blob/869a90512f36b04914d73cbf58317d953caea7c5/activemodel/lib/active_model/secure_password.rb#L77):

```
validates_length_of :password, maximum: ActiveModel::SecurePassword::MAX_PASSWORD_LENGTH_ALLOWED
```

BCrypt's length limit is 72 _bytes_, not codepoints.  This should be a `#bytesize` check, not a `#length` check.

Additionally, BCrypt also truncates after null bytes, allowing for an easy bypass of minimum/blank password checks.

**Comment by simi** [comment]
Is this followup or dupe of https://github.com/rails/rails/issues/22617 and https://github.com/rails/rails/pull/22870?

**Comment by Freaky** [comment]
Bah, I searched but evidently neglected to delete `is:open`.  It was 4am, in my defence.

Neither mention the NULL byte thing.  `BCrypt::Password.create("\u0000super secure password") == "" # => true`.  Rails should strip any characters after NULL to guarantee its idea of what the password will be matches, er, what the password will be.

As for the error message, I agree "72 bytes" is going to be confusing - the user thinks in characters, not bytes.  Luckily, we have both, so we can simply work out how many characters the password went over by and tell the user "password is 5 characters too long".

A better fix would be to eliminate both issues by taking a hexdigest of the password.  Then the maximum length can be dropped and NULL bytes stop doing anything special.  Backward compatibility can be maintained by a configuration flag and falling back to the raw password.  This may be more effort than it's worth, though.

Failing any of this, I would at least include a comment mentioning the issue in the code so people reading it don't have to go digging to find whether it's been reported or not.

**Comment by pthomas551** [comment]
I think @Freaky's proposed solution addresses some of the concerns that resulted in [#22870](https://github.com/rails/rails/pull/22870) being closed, I'll work on it.
