### ISSUE TITLE
link_to with method and confirm ignores method

### ISSUE THREAD

**Issue by jaredmoody** [rails/rails#25049]
I'm having an issue in 5.0.0.rc1 where if I have both a method and specify confirm in a link to call, the method is ignored and a get request is sent instead of a delete.

For example, here's my erb and generated html:

```
<%= link_to icon('trash'), admin_user_path(user), method: :delete, data: { confirm: "Are you sure you want to delete #{user.full_name}?" } %>
```

```
<a data-confirm="Are you sure you want to delete Jared Moody?" rel="nofollow" data-method="delete" href="/admin/users/10"><i class="fa fa-trash"></i></a>
```

If I remove the confirm, it works properly.

### System configuration
**Rails version**:
5.0.0.rc1
**Ruby version**:
2.3.0

**Comment by sikachu** [comment]
This seems like `jquery-rails` issue. Do you mind opening up an issue there? https://github.com/rails/jquery-rails/issues/new

**Comment by jaredmoody** [comment]
Will do, thanks.
