### ISSUE TITLE
"The Live Http Headers plugin" is dead

### ISSUE THREAD

**Issue by matkoniecz** [rails/rails#25058]
### Steps to reproduce

visit http://edgeguides.rubyonrails.org/security.html

### Expected behavior

http://edgeguides.rubyonrails.org/security.html  contains up to date information

### Actual behavior

> The Live Http Headers plugin for Mozilla Firefox logs every request and may repeat and change them

Note that this project appears to be dead - see https://www.mozdev.org/bugs/show_bug.cgi?id=25944

Some currently used project may be mentioned.

### System configuration
**Rails version**: master

**Ruby version**: Not relevant

**Comment by matkoniecz** [comment]
According to http://alternativeto.net/software/live-http-headers/ Firebug may be considered as a replacement. Is it correct?

**Comment by maclover7** [comment]
Wasn't your PR (#25052) just merged in, and the reference to this was removed?

**Comment by matkoniecz** [comment]
I noticed that there is an additional reference.

> Don't be fooled by security by obfuscation and JavaScript security. The Web Developer Toolbar for Mozilla Firefox lets you review and change every form's hidden fields. JavaScript can be used to validate user input data, but certainly not to prevent attackers from sending malicious requests with unexpected values. The Live Http Headers plugin for Mozilla Firefox logs every request and may repeat and change them. That is an easy way to bypass any JavaScript validations. And there are even client-side proxies that allow you to intercept any request and response from and to the Internet.

in https://github.com/rails/rails/blob/master/guides/source/security.md

**Comment by maclover7** [comment]
Ok, I will push a patch to rails/docrails with a fix for this.

**Comment by matkoniecz** [comment]
@maclover7 Yes, should I mention Firebug or something else?

**Comment by maclover7** [comment]
Yeah, sure. You can also rephrase the "web developer toolbar" part of the paragraph to talk about "developer tools" which are in most modern browsers now.
