### ISSUE TITLE
ActiveRecord does not serialize properly with custom class

### ISSUE THREAD

**Issue by rsov** [rails/rails#25057]
### Steps to reproduce

1. Create a table with a integer column
2. Add `CustomDateSerialize` to the model to convert Date to integer (yyyymmdd)
``` ruby
class CustomDateSerialize

  def self.dump(value)
    if value.respond_to? 'strftime'
      value.strftime('%Y%0m%0d').to_i
    else
      value
    end
  end

  def self.load(value)
    Date.strptime(value.to_s, '%Y%m%d') rescue nil
  end

end
```

### Expected behavior
Serializer should convert date to integer when writing to DB and then back to Date object when reading.
When doing:
``` ruby
m = TestTable.first
m.date_field = Date.new(2016, 1, 1)
m.save
```
Generated SQL should be:
``` SQL
UPDATE TEST_TABLE SET DATE_FIELD = 20160101 WHERE ID = 1
```

### Actual behavior
Actual SQL is:
``` SQL
UPDATE TEST_TABLE SET DATE_FIELD = 2016-01-01 WHERE ID = 1
```
So the saved value ends up being: `2014`

### System configuration
**Rails version**:
`4.2.6`
**Ruby version**:
`jruby 9.1.0.0 (2.3.0)`

Active Record - 4.2
ArJdbc - 1.3.20
JRuby - 9.1.0.0
Database - DB2/As400

This worked on AR-3.2 before updating to 4.2

We played around for couple days and got the `UPDATE` to work by returning the value in load:
``` ruby
def self.load(value)
  value
end
```
But then it does not convert it back to Date object on load.

Only way around this is to override the getter and setter for each date field in the application

**Comment by maclover7** [comment]
Can you condense your reproduction code, and create an executable test script using one of the templates [here](https://github.com/rails/rails/tree/master/guides/bug_report_templates), that would demonstrate the problem you are seeing?

**Comment by rsov** [comment]
@maclover7 sure, i'll give it a try

**Comment by rsov** [comment]
This seems to be an issue with the adapter
