### ISSUE TITLE
Rails 4 -- cannot drop all tables; disable_referential_integrity seems to be ignored

### ISSUE THREAD

**Issue by istrasci** [rails/rails#25062]
### Steps to reproduce

Run the following code in either a rake task or in the Rails console.
```
ActiveRecord::Base.connection.tables.each do |table|
  ActiveRecord::Migration.suppress_messages do
    ActiveRecord::Base.connection.disable_referential_integrity do
      ActiveRecord::Migration.drop_table table
    end
  end
end
```

### Expected behavior
Should drop all tables in the database specified for the current RAILS_ENV (`development` by default).

### Actual behavior
Errors out with message out dependencies, so `disable_referential_integrity` appears to not be working.
```
ActiveRecord::StatementInvalid: PG::Error: ERROR:  cannot drop table pricing_modes because other objects depend on it
DETAIL:  constraint fk_rails_89055a5717 on table pricing_mode_details depends on table pricing_modes
HINT:  Use DROP ... CASCADE to drop the dependent objects too.
: DROP TABLE "pricing_modes"
```

### System configuration
**Rails version**: 4.2.6
**Ruby version**: 2.3.0
**Database**: PostgreSQL

**Comment by matthewd** [comment]
This isn't a Rails issue; that's not what disable referential integrity does.
