### ISSUE TITLE
[Docs] [Rails 4/Guides] Documentation on association option validate incorrect

### ISSUE THREAD

**Issue by ghost** [rails/rails#25060]
I started creating a pull request for this but couldn't decide on wording that I liked so i'm opening this instead.

In both the guides and in the rails 4 branch in activerecord/lib/active_record/associations.rb comments the validate association documentation says:

> If you set the :validate option to true, then associated objects will be validated whenever you save this object. 

I would call this completely incorrect, though I could see people simply calling it misleading.

The new comments in activerecord/lib/active_record/associations.rb in master say:

>  # When set to +true+, validates new objects added to association when saving the parent object. +true+ by default.
>       #   If you want to ensure associated objects are revalidated on every update, use +validates_associated+.

I feel this is better but still may not be perfectly clear to newcomers. In addition, this wording change did not make it into http://guides.rubyonrails.org/association_basics.html.

**Comment by maclover7** [comment]
Can you open up a PR, so people can make comments and review any changes directly there?

**Comment by mordocai** [comment]
@maclover7 Yeah, I can do that later today

**Comment by vipulnsward** [comment]
Wording changes make it to http://guides.rubyonrails.org/association_basics.html after a release.

**Comment by prathamesh-sonpatki** [comment]
@mordocai  Hey, still interested in sending PR to fix this? Thanks!
