### ISSUE TITLE
5.0.0.rc1 weird performance issues

### ISSUE THREAD

**Issue by dreyks** [rails/rails#25073]
I may be a little vague, but this is due to not fully understanding where to look. Maybe someone can provide me clues on that.

I have an app which I slowly move into ~> 5.0 state. Everything is going fine, but upon testing the app in semi-production environment I noticed, that rendering `application.html.erb` takes 30 to 50ms, while on 4.2.6 it takes 3ms. And overall the app is slower.

To measure the time I use rack-mini-profiler gem, and the time reported is said to be 'without children duration'.

So I began hacking out parts of layout to see where it changes. Assets pipeline was the first to go, but that didn't yield any visible change. After some time I discovered that if I remove all the `render` calls from the layout (but leave the actual `yield` and page content at place), the application.html.erb time actually drops back down to 3ms. 

Let me state this again: rack-mini-profiler reports the time of layout without actual time spent rendering partials, so it looks like something to do with `render` method itself (be it template resolution or whatever).

Also, my application consists of several engines (6-7), so the partial lookup paths array is longer than in a usual Rails-app

Any thoughts?

### System configuration
**Rails version**: 5.0.0.rc1

**Ruby version**: 2.3.1

**Comment by jeremy** [comment]
Sounds like template lookup cache is getting expired.

Are your engines changing the view paths per request? You may be inadvertently blowing the cache.

Try stackprof to take a more detailed look: http://blog.scoutapp.com/articles/2015/09/16/profiling-rails-with-stackprof

**Comment by dreyks** [comment]
Just a while ago, by adding some more profiling points I see that all that time is indeed lost to locating partials. Something like Lokating 10ms, actual rendering 0.5ms

The thing is, I didn't change anything except Rails5-specific things

The engines do not modify view paths, at least it's not intended. I'll give stackprof a try, thanks

**Comment by jeremy** [comment]
> The engines do not modify view paths, at least it's not intended.

This is something to verify since it's the most likely culprit.

> seems that rack-mini-profiler does a descent job for me too

rack-mini-profiler does an excellent job of application-level perf profiling, for sure. StackProf is a bit lower level. It'll help identify exactly where the additional time is spent.

**Comment by dreyks** [comment]
Got you. Thanks, will try to find something

On 19 May 2016, at 18:39, Jeremy Daer <notifications@github.com> wrote:

The engines do not modify view paths, at least it's not intended.

This is something to verify since it's the most likely culprit.

seems that rack-mini-profiler does a descent job for me too

rack-mini-profiler does an excellent job of application-level perf
profiling, for sure. StackProf is a bit lower level. It'll help identify
exactly where the additional time is spent.

—
You are receiving this because you authored the thread.
Reply to this email directly or view it on GitHub
<https://github.com/rails/rails/issues/25073#issuecomment-220363411>

**Comment by dreyks** [comment]
Yeah, this is the template location. Top line from stackprof

TOTAL | (pct) | SAMPLES | (pct) | FRAME
--------- | ------ | ------------- | ------- | ---------
1172  | (11.2%) | 1009 | (9.7%) | ActionView::PathResolver#find_template_paths

Will dive deeper with the debugger to figure out where the difference is

**Comment by dreyks** [comment]
So far it seems that the `DetailsKey` is changed per request

```
From: /bundle/gems/actionview-5.0.0.rc1/lib/action_view/path_set.rb @ line 73 ActionView::PathSet#_find_all:

    72: def _find_all(path, prefixes, args, outside_app)
 => 73:   prefixes = [prefixes] if String === prefixes
    74:   prefixes.each do |prefix|
    75:     paths.each do |resolver|
    76:       if outside_app
    77:         templates = resolver.find_all_anywhere(path, prefix, *args)
    78:       else
    79:         templates = resolver.find_all(path, prefix, *args)
    80:       end
    81:       return templates unless templates.empty?
    82:     end
    83:   end
    84:   []
    85: end

2.3.0(#<ActionView::PathSet>)> paths[4].instance_variable_get(:@cache).instance_variable_get(:@data).keys
=> [
  [0] #<ActionView::LookupContext::DetailsKey:0x00555a2d8e8258 @digest_cache=#<Concurrent::Map:0x00555a2d8e8230 entries=4 default_proc=nil>>,
  [1] #<ActionView::LookupContext::DetailsKey:0x00555a2d630a60 @digest_cache=#<Concurrent::Map:0x00555a2d630a10 entries=4 default_proc=nil>>,
  [2] #<ActionView::LookupContext::DetailsKey:0x007f89cd0f0bf0 @digest_cache=#<Concurrent::Map:0x007f89cd0f0bc8 entries=4 default_proc=nil>>,
  [3] #<ActionView::LookupContext::DetailsKey:0x007f89cf585100 @digest_cache=#<Concurrent::Map:0x007f89cf5850d8 entries=0 default_proc=nil>>

]
```
And this array grows and grows with each request served

This is due to
https://github.com/rails/rails/blob/v5.0.0.rc1/actionview/lib/action_view/digestor.rb#L11 which calls `ActionView::LookupContext::DetailsKey.clear`, and which is absent in 4.2.6

**Comment by dreyks** [comment]
Ok, mystery solved

Our staging environment has `config.consider_all_requests_local       = true` to be able to see full errors. And `PerRequestDigestCacheExpiry` depends on this exact option
```ruby
if app.config.consider_all_requests_local
  app.middleware.use ActionView::Digestor::PerRequestDigestCacheExpiry
end
```

"Staging environment must be as identical to production as it is humanly possible"
Case closed

**Comment by jeremy** [comment]
🙌
