### ISSUE TITLE
in `===': invalid byte sequence in UTF-8 (ArgumentError)

### ISSUE THREAD

**Issue by Javix** [rails/rails#25074]
I was processing DB records and got a weird value:
https://drive.google.com/open?id=0B9xwV2TklOdaRjNoYjNlZ3hKSFk

When calling `blank?` on the above String, I get the below error:
```
C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/activesupport-4.2.6/lib/active_support/core_ext/object/blank.rb:117:in `===': invalid byte sequence i
n UTF-8 (ArgumentError)
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/activesupport-4.2.6/lib/active_support/core_ext/object/blank.rb:117:in `blank?'
```

Reproduced on:
- Windows 7 x64
- Ruby `ruby 2.3.0p0 (2015-12-25 revision 53290) [x64-mingw32]`
- `activesupport-4.2.6`

Any idea on how to fix that ? Or it would be better to `gsub` all non-printable characters ?

Thank you.

**Comment by maclover7** [comment]
Can you create an executable test script using one of the templates [here](https://github.com/rails/rails/tree/master/guides/bug_report_templates), that would demonstrate the problem you are seeing?

**Comment by Javix** [comment]
The problem is that when I copy-paste the weird character, it changes from square symbol and becomes `�, �`.
So I'll have to either find a way to enter this character with a special keyboard combination (some kind of ALT + some key) or to find the its ASCII code.

**Comment by Javix** [comment]
It seems like a [North Indic rupee mark](http://graphemica.com/꠸), Unicode `a839` or `a837`.
I'll have to test in a Windows PC console. In Mac terminal a simple IRB test passes:
```
2.3.0 :011 > puts "\ua837".encode('utf-8')
꠷
 => nil 
2.3.0 :012 > puts "\ua837"
꠷
 => nil 
2.3.0 :013 > puts "\ua839".encode('utf-8')
꠹
 => nil 
2.3.0 :014 > irb
2.3.0 :001 > require 'active_support/all'
 => true 
2.3.0 :002 > "\ua839".blank?
 => false 
```

**Comment by Javix** [comment]
I've just retried to run the same DB extraction data ruby script and it worked without problems, as via Windows command prompt terminal (cmd prompt) as via Git Bash terminal. So, taking into account that I can't reproduce it again and can't find a way post a test template as described, I'll close the issue. Theoretically, it can't be an encoding problem (the active suppport `blank.rb` file already has it defined # encoding: utf-8`. More of that, all the rest extracted data containing text in Chineese, Russian, and other languages, were written correctly.

**Comment by JamesBalazs** [comment]
> Can you create an executable test script using one of the templates [here](https://github.com/rails/rails/tree/master/guides/bug_report_templates), that would demonstrate the problem you are seeing?

I think this is still an issue - `blank?` called on a string with a non-UTF-8 character raises an `ArgumentError`

This can be reproduced using a test script as follows:
```
# frozen_string_literal: true

require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  gem "rails", github: "rails/rails", branch: "main"
end

require "active_support"
require "active_support/core_ext/object/blank"
require "minitest/autorun"

class BugTest < Minitest::Test
  def test_stuff
    refute "\xBF".blank?
  end
end
```

 I can't think of an easy way to fix that without potentially unnecessarily calling `scrub` before `match?` in every call to `blank?`

Is it possible to reopen this issue?
