### ISSUE TITLE
3.2.22.2 broke actionmailer

### ISSUE THREAD

**Issue by jesperrojestal** [rails/rails#25081]
### Steps to reproduce
simple [application](https://gist.github.com/jesperrojestal/c575ecdd8c50efde448014b00230c165)

Gemfile contains:
```ruby
source 'https://rubygems.org'
gem 'rails', '3.2.22.2'
```

```shellsession
 $ bundler exec ruby test_mail.rb
```
### Expected behavior
Should receive a mail to the specified address which works with 3.2.22.1

### Actual behavior
/Users/rk/tmp/bundler/ruby/2.2.0/gems/actionpack-3.2.22.2/lib/action_view/renderer/renderer.rb:14:in `render': uninitialized constant ActionView::Renderer::HashWithIndifferentAccess (NameError)

even require 'rails/all' doesn't solve the problem

### System configuration
Rails 3.2.22.2
ruby 2.2.3p173 (2015-08-18 revision 51636) [x86_64-darwin15]

**Comment by maclover7** [comment]
Rails 3.2.x is no longer supported -- can you reproduce this on Rails master or other versions of Rails? 😬

**Comment by rafaelfranca** [comment]
Oh. This is a valid issue. r? @arthurnn

**Comment by prathamesh-sonpatki** [comment]
This is fixed by https://github.com/rails/rails/commit/68c76c6b09135f25d94d3. 

@jesperrojestal Can you check `3-2-stable` branch and see if it resolves the error?

**Comment by rafaelfranca** [comment]
OMG! Thanks I forgot about it

**Comment by jesperrojestal** [comment]
@prathamesh-sonpatki yes 3-2-stable works.
