### ISSUE TITLE
redirect route is unescaping encoded slashes.

### ISSUE THREAD

**Issue by jcoyne** [rails/rails#25087]
### Steps to reproduce

In `config/routes.rb`

``` ruby
get "/:id", to: redirect("/other_place/%{id}")
```

Now If I request `/abcd%2F1234` it redirects to `/other_place/abcd/1234` rather than the expected `/other_place/abcd%2F1234`
### Expected behavior

When I request `/abcd%2F1234` it should redirect to `/other_place/abcd%2F1234`
### Actual behavior

When I request `/abcd%2F1234` it redirects to `/other_place/abcd/1234`
### System configuration

**Rails version**: 4.2.6

**Ruby version**: 2.3.0

**Comment by jcoyne** [comment]
I can work around this for now by changing the route to:
```ruby
        get "#{route_prefix}/:id" => 'first_place#redirect'
```
And adding a method to FirstPlaceController:
```
def redirect
  redirect_to other_place_path(param[:id])
end
```
Then it redirects without unescaping the slashes in the id.

**Comment by sblackstone** [comment]
Was taking a look at this, here's a failing test case for HEAD 

96fc81eb18ecd3bd663eb307328284fdf8d6b3ed

**Comment by sblackstone** [comment]
It seems that the current behavior is expected - if I "fix" this issue, other test cases fail that that expect it to work the other way.   At first glance it makes sense to me that it should pass through the slash escaped - but I suspect there are other use cases for this function. (escape_path in journey/router/utils.rb)

```
  1) Failure:
TestRoutingMapper#test_url_generator_for_namespaced_generic_route [/Users/sblackstone/code/github/rails/actionpack/test/dispatch/routing_test.rb:1888]:
--- expected
+++ actual
@@ -1 +1 @@
-"http://www.example.com/whatever/foo/bar/show"
+"http://www.example.com/whatever/foo%2Fbar/show"



  2) Failure:
TestRoutingMapper#test_redirect_hash_path_substitution_with_catch_all [/Users/sblackstone/code/github/rails/actionpack/test/dispatch/routing_test.rb:3671]:
--- expected
+++ actual
@@ -1 +1 @@
-"http://stores.example.com/iernest/products"
+"http://stores.example.com/iernest%2Fproducts"



  3) Failure:
TestUriPathEscaping#test_does_not_escape_slash_in_generated_path_splat [/Users/sblackstone/code/github/rails/actionpack/test/dispatch/routing_test.rb:3975]:
Expected: "/a%20b/c+d"
  Actual: "/a%20b%2Fc+d"


  4) Failure:
TestOptimizedNamedRoutes#test_glob_segments_with_slashes_are_not_escaped [/Users/sblackstone/code/github/rails/actionpack/test/dispatch/routing_test.rb:4222]:
Expected: "/wiki/foo/bar"
  Actual: "/wiki/foo%2Fbar"
```

**Comment by dancinglightning** [comment]
on 5.0.0.1 (and ruby 2.3.1) the whole % syntax does not seem to work (as the guide http://guides.rubyonrails.org/routing.html#redirection says it should)

config/routes.rb:
  get '/laser_gem/:id',   to: redirect( "/gem/%{:id}" ) 

when testing (accessing) 
 URI::InvalidURIError:
       bad URI(is not URI?): /gem/%{:id}

(just fyi, i have worked around the issue with the block syntax)
