### ISSUE TITLE
ActionCable running without mount

### ISSUE THREAD

**Issue by djvs** [rails/rails#25082]
### Steps to reproduce
Create Rails app with functional channels, actioncable accepted origins, etc..  Omit `mount ActionCable.server => '/cable'` from config/routes.rb.  Observed in development environment.

### Expected behavior
No ActionCable server mounts

### Actual behavior
ActionCable server mounts

### System configuration
**Rails version**:
5.0.0.beta4

**Ruby version**:
ruby 2.3.0p0 (2015-12-25 revision 53290) [x86_64-linux]

Is there something I'm missing here?  Auto-mount?

**Comment by rglyall** [comment]
Have you set `config.action_cable.mount_path` anywhere in your application?

**Comment by rafaelfranca** [comment]
Action Cable auto mounts unless you set `config.action_cable.mount_path` to `nil`

**Comment by djvs** [comment]
Perfect, thank you

**Comment by djvs** [comment]
One question I do need to ask - if I want to run two copies of A.C., ala this article (section "Running the Action Cable server on a different host or port") - is there a way to circumvent this and disable it for the main app, while other AC processes will still work?

https://www.phusionpassenger.com/library/config/nginx/action_cable_integration/

**Comment by matthewd** [comment]
Everything else in that document remains true; the explicit mount will still work fine after you opt-out of the automatic mount.

cc @FooBarWidget
