### ISSUE TITLE
[ActionCable] No way to filter out any sensitive data which may be passed as an argument to the remote procedure over ws protocol..

### ISSUE THREAD

**Issue by Anuragjain89** [rails/rails#25088]
### Steps to reproduce

Just followed the action cable demo from DHH on [rails homepage](http://rubyonrails.org/).

You would notice that whenever the RoomChannel#speak is invoked over websocket protocol, the server logs show the arguments which are passed.  

```
RoomChannel#speak({"message"=>"test"})
```

For HTTP requests, we have `filter_parameters` to filter out any sensitive data from the logs.
However, for these RPCs, I could not find any way to filter out any sensitive data which may be passed as an argument to the remote procedure.
### Expected behavior

I expected some mechanism to filter out logs for any arbitrary arguments which are passed over ws protocol.
### Actual behavior

I could not find a way to filter out logs for data transmitted over ws protocol.
**Please advise** if this behavior is on purpose.

Below is the related code which I am referring to

``` ruby
#actioncable-5.0.0.rc1/lib/action_cable/channel/base.rb
def dispatch_action(action, data)
  # What if we do not want this to be logged.
  logger.info action_signature(action, data)

  if method(action).arity == 1
    public_send action, data
  else
    public_send action
  end
end

def action_signature(action, data)
  "#{self.class.name}##{action}".tap do |signature|
    if (arguments = data.except('action')).any?
      signature << "(#{arguments.inspect})"
    end
  end
end
```
### System configuration

**Rails version**: 5.0.0.rc1

**Ruby version**: ruby 2.2.4p230 (2015-12-16 revision 53155) [x86_64-linux]

**Comment by maclover7** [comment]
Hmm, we should be able to just `include` the proper module from `ActionDispatch`. Looking into this.

**Comment by maclover7** [comment]
Opened #25090.

**Comment by mulander** [comment]
I would like to add, that apart from filtering it would be extremely nice to be able to disable logging completely for selected channels (to avoid log spam from extremely chatty connections whose payload or the fact that a transmission happened is not interesting).

In essence, I would rather disable logging for `RoomChannel` than have it filled with
useless information.

```
RoomChannel#speak({"message"=>"{filtered}"})
RoomChannel#speak({"message"=>"{filtered}"})
RoomChannel#speak({"message"=>"{filtered}"})
```

I have a real world use-case in our product, where automation generates some actioncable chatter that is of no benefit and just fills the logs.

**Comment by Anuragjain89** [comment]
@oniofchaos 
There's an [open PR](https://github.com/rails/rails/pull/25090) for the same where one may find some of the ways (not necessarily the best ways, but still, it gets the work done) of addressing this.

**Comment by Anle90** [comment]
that PR is closed

**Comment by mahfuz10** [comment]
This is how I am filtering specific field from `dispatch_action` method.

- I created a `config/initializers/actioncable.rb`, and
- Override the `dispatch_action` method

``` ruby
# config/initializers/actioncable.rb

ActionCable::Channel::Base.class_eval do
  def dispatch_action(action, data)
    # logger.info action_signature(action, data)
   
    # .......... filter data start ..........
    filtered_data = data
    filtered_data['audio_ch'] = '{filtered}' if filtered_data['audio_ch'].present?
    logger.info action_signature(action, filtered_data)
    # .......... ./filter data end ..........

    if method(action).arity == 1
      public_send action, data
    else
      public_send action
    end
  rescue Exception => exception
    rescue_with_handler(exception) || raise
  end
end
```

This monkey patch also works in specific channel.

``` ruby
# app/channels/app_online_channel.rb

class AppOnlineChannel < ApplicationCable::Channel
  def dispatch_action(action, data)
     # logger.info action_signature(action, data)
   
     # .......... filter data start ..........
     filtered_data = data
     filtered_data['audio_ch'] = '{filtered}' if filtered_data['audio_ch'].present?
     logger.info action_signature(action, filtered_data)
     # .......... ./filter data end ..........

     if method(action).arity == 1
       public_send action, data
     else
       public_send action
     end
   rescue Exception => exception
     rescue_with_handler(exception) || raise
   end
```

**Comment by dchacke** [comment]
@mahfuz10 I tried both your approaches and the code never runs (`byebug` never showed a prompt). Rails 6.1.4.6, Ruby 2.7.2.

**Comment by mahfuz10** [comment]
@dchacke I tested with your specified Rails and Ruby version. And it perfectly works.
You can check this repo: https://github.com/mahfuz10/cable_in_six

**Comment by dchacke** [comment]
@mahfuz10 Indeed, runs fine now. Not sure why it wasn't running before. Thanks.

**Comment by dchacke** [comment]
@mahfuz10 You may wish to change

```rb
filtered_data = data
```

to

```rb
filtered_data = data.clone
```

or else changes to `filtered_data` are applied to `data` as well, meaning the message that gets sent over the wire will be filtered, too, not just the log.

**Comment by mahfuz10** [comment]
@dchacke Thanks for your suggestion :+1:
