### ISSUE TITLE
Logging mismatch when Rack::Cache activates

### ISSUE THREAD

**Issue by hammerdr** [rails/rails#25109]
Tracked down an issue where responses cached by Rack::Cache are being reported wrong in the logs. Whereas the server ultimately returns a 304 response code, we're seeing a 200 response code in the logs. I tried to write a test to prove it out, but none of the tests in the rails repo seem to test the entire Rack middleware stack together (there actually probably is, I'm just not well versed enough to know where it is).

Anyway, I created a reduction instead. I hope that's okay.

From my investigation, it looks like ActionController::LogSubscriber is where all of these logs are being written. Unfortunately, at the point the response gets to the log subscriber, Rack::Cache hasn't had a chance to inspect and maybe 304 the 200 response.
### Steps to reproduce
- [Reduction of the bug](https://github.com/hammerdr/etag_bug)
- [The test is test.sh](https://github.com/hammerdr/etag_bug/blob/master/test.sh)  
- [Output](https://github.com/hammerdr/etag_bug/blob/master/output.txt)
### Expected behavior

The logs should output the correct response information. In this case, I am expecting a 304 Not Modified but the logs display a 200 OK.
### Actual behavior

The logs show a 200 OK.
### System configuration

**Rails version**:
4.2.6

**Ruby version**:
2.3.1p112

**Comment by maclover7** [comment]
Would you be able to simplify your test application and create an executable test script using one of the templates [here](https://github.com/rails/rails/tree/master/guides/bug_report_templates), that would demonstrate the problem you are seeing?

**Comment by hammerdr** [comment]
Hey, I've tried to recreate it with the `action_controller_*.rb` and those do not exhibit the behavior. I'm not sure why other than to guess that `Rack::Cache` is not being executed by the tests.

The rails app I linked is super vanilla. Nothing special going on in it.
