### ISSUE TITLE
Raise on missing translations does not include controllers

### ISSUE THREAD

**Issue by KevinSjoberg** [rails/rails#25116]
The option `raise_on_missing_translations` is scoped to `ActionView`. Since `AbstractController` provides its own implementation of `translate` and `localize` it does not include the "raise on missing" behaviour.

This is problematic, I can't think of a use case where you'd want to only raise exceptions in either views or controllers. Usually, if you want to raise errors, you want the behaviour everywhere.

There was another issue addressing the issue (https://github.com/rails/rails/issues/24138) but it was closed and no pull request have emerged.

I'd be happy to create a pull request addressing the issue, but I think it's important that we decide how we want to go about implementing this.

I think the option should be moved out of `config.action_view` and instead be moved into `config.i18n.raise_on_missing_translation`. `AbstractionController` and `TranslationHelper` can then utilize this option in their implementation. Doing this would also mean deprecating `config.action_view.raise_on_missing_translations`.

**Comment by rafaelfranca** [comment]
Thank you so much for the issue but we don't take feature request on the issue tracker. We recommend you to try to implement the feature and send us a pull request or if you are in doubt if the feature will be accepts ask in Rails Core mailing list for feedback.

**Comment by KevinSjoberg** [comment]
@rafaelfranca I'm not asking anyone to implement this, I'm willing to do the work. But before making a pull request I think it's important to discuss how we want to tackle the problem. There are plenty of contributors with more experience than me and I think it's wise to ask for their input before hacking away.

If GitHub isn't the place for this, where is?

**Comment by rafaelfranca** [comment]
Hey @KevinSjoberg I saw you sent a comment and later deleted it. Have you found your answer? If not I'm willing to explain better.

**Comment by KevinSjoberg** [comment]
@rafaelfranca you're right. I think the mailing list, as you suggested, is better suited for the discussion I like to have. Thank you for pointing me in the right direction. 😃
