### ISSUE TITLE
Getting an stack level too deep when testing on 2.4

### ISSUE THREAD

**Issue by SamSaffron** [rails/rails#25125]
Rails 4.2.6, booting Discourse on Ruby head. 

```
! Unable to load application: SystemStackError: stack level too deep
/Users/sam/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/activesupport-4.2.6/lib/active_support/core_ext/numeric/conversions.rb:124:in `block (2 levels) in <class:Numeric>': stack level too deep (SystemStackError)
	from /Users/sam/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/activesupport-4.2.6/lib/active_support/core_ext/numeric/conversions.rb:131:in `block (2 levels) in <class:Numeric>'
	from /Users/sam/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/activesupport-4.2.6/lib/active_support/core_ext/numeric/conversions.rb:131:in `block (2 levels) in <class:Numeric>'
	from /Users/sam/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/activesupport-4.2.6/lib/active_support/core_ext/numeric/conversions.rb:131:in `block (2 levels) in <class:Numeric>'
	from /Users/sam/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/activesupport-4.2.6/lib/active_support/core_ext/numeric/conversions.rb:131:in `block (2 levels) in <class:Numeric>'
	from /Users/sam/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/activesupport-4.2.6/lib/active_support/core_ext/numeric/conversions.rb:131:in `block (2 levels) in <class:Numeric>'
	from /Users/sam/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/activesupport-4.2.6/lib/active_support/core_ext/numeric/conversions.rb:131:in `block (2 levels) in <class:Numeric>'
	from /Users/sam/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/activesupport-4.2.6/lib/active_support/core_ext/numeric/conversions.rb:131:in `block (2 levels) in <class:Numeric>'
	from /Users/sam/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/activesupport-4.2.6/lib/active_support/core_ext/numeric/conversions.rb:131:in `block (2 levels) in <class:Numeric>'
	 ... 5725 levels...
```

**Comment by vipulnsward** [comment]
cc @jeremy

**Comment by vipulnsward** [comment]
@SamSaffron what revision of ruby does this occur on?

**Comment by SamSaffron** [comment]
On trunk 2.4.0.dev

**Comment by jeremy** [comment]
Due to Fixnum/Bignum unification. They're the same class now (Integer) so we're aliasing to_s twice!

We're gonna have a neat day.

**Comment by koic** [comment]
Maybe it will resolved by https://github.com/rails/rails/pull/25161.

**Comment by jeremy** [comment]
#25161 backports support to 4-2-stable.

**Comment by alexch** [comment]
I'm getting this error using rails 4.2.7 and 4.2.7.1 under Ruby 2.4.0. Is there a released version of Rails 4.2 that fixes it?

**Comment by alexch** [comment]
in case someone else finds this helpful, here's my fix:

*   `mkdir vendor/gems`
*   `cp -r ~/.rvm/gems/ruby-2.4.0/gems/activesupport-4.2.7.1 vendor/gems`
* edit `lib/active_support/core_ext/numeric/conversions.rb` with the one line inside https://github.com/rails/rails/pull/25737/commits/6698a6493b45c88d894ca6ae19df8719fc9abe7a
* put https://github.com/rails/rails/blob/4-2-stable/activesupport/activesupport.gemspec inside `vendor/gems/activesupport-4.2.7.1`
* replaced the first line of the gemspec with `version = '4.2.7.1'`
* put `gem 'activesupport', :path => File.join(File.dirname(__FILE__), '/vendor/gems/activesupport-4.2.7.1')` in my Gemfile, *before* the `gem 'rails'` line

**Comment by dcarral** [comment]
Hi @jeremy, I'd like to know if we should expect a Rails release > v4.2.7.1 compatible with Ruby v2.4.0.

**Comment by rafaelfranca** [comment]
Yes

**Comment by bradseefeld** [comment]
@jeremy @rafaelfranca, I am confused on the status of this. The PR was merged on Aug 16, 2016 to the 4.2-stable branch, but it does not look like a new 4.2.x rails gem has been released yet. Is there an ETA for releasing the new version, or something that one of us can help with to facilitate that?

**Comment by rafaelfranca** [comment]
There is no ETA for it.

**Comment by bradseefeld** [comment]
You say that, but then today 4.2.8.rc1 is released... http://weblog.rubyonrails.org/2017/2/10/Rails-4-2-8-rc1-has-been-released/

> If no regressions are found, expect the final release on Wednesday, February 15, 2017.

So ETA is Feb 15.

**Comment by bradseefeld** [comment]
@rafaelfranca, also noticed that you are the one that did the build, or at least the announcement, so thank you!!

**Comment by duhaime** [comment]
I updated the version of Rails in my gemfile to 4.2.10:

```
gem 'rails', '~> 4.2.10'
```

Then ran `bundle update rails` and all was well.
