### ISSUE TITLE
Unexpected transaction behaviour

### ISSUE THREAD

**Issue by tony-milne** [rails/rails#25129]
I think I may have run into some odd behaviour with transactions in rails. I am use postgres as my database, but the issue also occurs using sqlite in the gist below.

### Steps to reproduce
https://gist.github.com/tony-milne/1fb400c3c71abb86b10d94b33fd3b407

Create a new record when in a transaction block and make further changes to the record and save it again.

### Expected behavior
Record should not be persisted in the database and the active record object should not have an ID and #persisted? should be false.

### Actual behavior
Record is not persisted in the database, but the active record object maintains an ID and #persisted? is true.

### System configuration
**Rails version**: 4.2.6

**Ruby version**: 2.2.4p230

**Comment by danielterega** [comment]
I could be wrong, but is seem to be an expected behaviour. 

> Exceptions will force a ROLLBACK that returns the database to the state before the transaction began. Be aware, though, that the objects will not have their instance data returned to their pre-transactional state.

[ActiveRecord::Transactions::ClassMethods](http://api.rubyonrails.org/classes/ActiveRecord/Transactions/ClassMethods.html)

**Comment by vipulnsward** [comment]
That is true. This is expected behaviour. 
Closing based on https://github.com/rails/rails/issues/25129#issuecomment-221326612

**Comment by tony-milne** [comment]
Ah, I didn't spot that, despite reading that page a few times!

I still find it a bit odd given that state is tracked and even reverted under certain circumstances e.g. https://github.com/rails/rails/blob/v4.2.6/activerecord/lib/active_record/transactions.rb#L368

**Comment by jrochkind** [comment]
I am not sure whether this behavior should be considered expected, but I think it's pretty terrible.

To have an object that says `persisted? # => true` when it is not in fact persisted is a pretty huge problem for ActiveRecord, that messes things up all over the place. It makes transactions very very dangerous to use. 

There is actually an open PR to fix this behavior specifically with regard to `persisted?` and pk here: https://github.com/rails/rails/pull/21020

I wish it would get some attention!
