### ISSUE TITLE
has_many :through validate=>false not being obeyed.

### ISSUE THREAD

**Issue by marcalc** [rails/rails#25135]
### Steps to reproduce
```
class User < ApplicationRecord
  has_many :user_roles, :dependent => :destroy
  has_many :roles, :through => :user_roles, :validate => false
end
```

```
def insert_record(record, validate = true, raise = false)
  ensure_not_nested
  if raise
    record.save!(:validate => validate)
  else
    return unless record.save(:validate => validate)
  end

  save_through_record(record)

  record
end
```
at ActiveRecord::Associations::HasManyThroughAssociation.insert_record(record#Role, validate#TrueClass, raise#TrueClass) at /Users/marcalc/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activerecord-5.0.0.rc1/lib/active_record/associations/has_many_through_association.rb:41

```
def concat_records(records, should_raise = false)
  result = true

  records.each do |record|
    raise_on_type_mismatch!(record)
    add_to_target(record) do |rec|
      result &&= insert_record(rec, true, should_raise) unless owner.new_record?
    end
  end

  result && records
end
```

at concat_records(records#Array) at /Users/marcalc/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activerecord-5.0.0.rc1/lib/active_record/associations/collection_association.rb:587

Apparently, the method `insert_record` is always being called with the arg `validate = true`, not obeying the relation's option `validate: false`.

Maybe this should this be: `result &&= insert_record(rec, reflection.validate?, should_raise) unless owner.new_record?` ?

### Expected behavior
When posting a User.new(params[:user]) with role_ids checkboxes, it should ignore roles validation, per :validate => false.

### Actual behavior
When posting a User.new(params[:user]) with role_ids checkboxes, I'm receiving a role related validation error.

### System configuration
**Rails version**: 5.0.0.rc1

**Ruby version**: MRI 2.3.1

**Comment by maclover7** [comment]
Can you create an executable test script using one of the templates [here](https://github.com/rails/rails/tree/master/guides/bug_report_templates), that would demonstrate the problem you are seeing?

**Comment by marcalc** [comment]
Sure.

```
begin
  require 'bundler/inline'
rescue LoadError => e
  $stderr.puts 'Bundler version 1.10 or later is required. Please update your Bundler'
  raise e
end

gemfile(true) do
  source 'https://rubygems.org'
  # Activate the gem you are reporting the issue against.
  gem 'activerecord', '5.0.0.rc1'
  gem 'sqlite3'
end

require 'active_record'
require 'minitest/autorun'
require 'logger'

# Ensure backward compatibility with Minitest 4
Minitest::Test = MiniTest::Unit::TestCase unless defined?(Minitest::Test)

# This connection will do for database-independent bug reports.
ActiveRecord::Base.establish_connection(adapter: 'sqlite3', database: ':memory:')
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table "roles", force: :cascade do |t|
    t.string   "name"
    t.datetime "created_at", null: false
    t.datetime "updated_at", null: false
  end

  create_table "user_roles", force: :cascade do |t|
    t.integer  "user_id"
    t.integer  "role_id"
    t.datetime "created_at", null: false
    t.datetime "updated_at", null: false
    t.index ["role_id"], name: "index_user_roles_on_role_id"
    t.index ["user_id"], name: "index_user_roles_on_user_id"
  end

  create_table "users", force: :cascade do |t|
    t.string   "name"
    t.datetime "created_at", null: false
    t.datetime "updated_at", null: false
  end
end

class Role < ActiveRecord::Base
  attr_accessor :audit_comment
  validates_presence_of :audit_comment
end

class User < ActiveRecord::Base
  has_many :user_roles
  has_many :roles, through: :user_roles, validate: false
end

class UserRole < ActiveRecord::Base
  belongs_to :user
  belongs_to :role
end

class BugTest < Minitest::Test
  def test_association_stuff
    Role.create!(audit_comment: "testing")
    
    puts "Creating user with role_ids. Ok."
    user = User.create!(role_ids: ["1"])
    
    
    puts "Setting user roles to nil. Ok."
    user.assign_attributes(role_ids: nil)
    
    puts "Setting user roles again. This will fail."
    user.assign_attributes(role_ids: ["1"]) # this will fail
  end
end
```

**Comment by maclover7** [comment]
So, a few things (all of these are in terms of the current code on Rails master, not RC1 😬):

1. the `validates_presence_of :audit_comment` appears to be failing right now, but I'm going to ✂️ that, since it isn't really related to the thing we are testing here 😬

2. Your test script [with some removal of some extraneous information](https://gist.github.com/maclover7/45349253b50d2b54b57bbcb75a7b737d) appears to be passing on both v5.0.0.rc1 and on Rails master for me...

Can you create another bug script to reproduce the error you are seeing, and can you also post the backtrace? Thanks! ❤️

**Comment by marcalc** [comment]
Well, I agree with some removals, although the validation inside the Role class represents the problem. As I'm not touching Role by setting user#role_ids=, it shouldn't get validated.

**Comment by marcalc** [comment]
Hi, John. Thanks for your attention yesterday.

I created a new bug script which fits exactly in the situation I'm reporting. The `validates :comment, presence: true` is absolutely necessary for the bug to happen, as when specifying `has_many :roles, through: :user_roles, validate: false` the Role object shouldn't be validated.

```
require 'active_record'
require 'minitest/autorun'
require 'logger'

# Ensure backward compatibility with Minitest 4
Minitest::Test = MiniTest::Unit::TestCase unless defined?(Minitest::Test)

# This connection will do for database-independent bug reports.
ActiveRecord::Base.establish_connection(adapter: 'sqlite3', database: ':memory:')
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table "roles", force: :cascade do |t|
  end

  create_table "user_roles", force: :cascade do |t|
    t.integer  "user_id"
    t.integer  "role_id"
  end

  create_table "users", force: :cascade do |t|
  end
end

class Role < ActiveRecord::Base
  attr_accessor :comment
  validates :comment, presence: true
end

class User < ActiveRecord::Base
  has_many :user_roles
  has_many :roles, through: :user_roles, validate: false
end

class UserRole < ActiveRecord::Base
  belongs_to :user
  belongs_to :role
end

class BugTest < Minitest::Test
  def test_association_stuff
    Role.create!(comment: "testing")

    puts "Creating user with role_ids. Ok."
    user = User.create!(role_ids: ["1"])

    puts "Setting user roles to nil. Ok."
    user.assign_attributes(role_ids: nil)

    puts "Setting user roles again. This will fail."
    user.assign_attributes(role_ids: ["1"]) # this will fail.
  end
end
```

Thank you in advance!

**Comment by sgrif** [comment]
> as when specifying has_many :roles, through: :user_roles, validate: false the Role object shouldn't be validated when setting user#role_ids=

This is not what you're specifying. As per the docs:

> If false, don't validate the associated objects when saving the parent object.

This means that an invalid child wouldn't prevent `user.save` from succeeding if one of the children were invalid. This does not mean that we will persist the children without validating them however. The behavior is working as intended.

**Comment by marcalc** [comment]
Sean, thanks for your answer. Although I think there is a regression here. I'm migrating a Rails 3.2 application and this was the correct behavior back then. I'm not creating a Role object, thus I don't need the Role object to be validated when I'm simply assigning roles to the user via User#role_ids. If you could please review the test script I would be very glad. Thanks

**Comment by marcalc** [comment]
@sgrif Excuse me for maybe being repetitive, but would you be kind to follow up in this?

**Comment by marcalc** [comment]
@sgrif I'm still having this problem. Would you be so kind to follow up on this?

**Comment by jeppeliisberg** [comment]
@sgrif +1 on this one. I'm having the same issue. I cannot assign `list#user_ids` from checkboxes in a form if one of the users is invalid (which would be true for e.g. invites that haven't chosen a pwd yet). I'm getting a `ActiveRecord::RecordInvalid` error thrown at me.

I understand that the docs doesn't specifically mention the `model#association_ids=` as being influenced by `validates: false` - but the docs doesn't mention `model#association_ids=` with regards to validations at all AFAIK and I still lack the explanation why it changed with rails 5. I think it should work like older rails versions as @marcalc mentions.

**Comment by jeppeliisberg** [comment]
Sorry, only saw https://github.com/rails/rails/issues/25718 now - added my +1 there as well.
