### ISSUE TITLE
AR objects serialized are much larger in Rails 5

### ISSUE THREAD

**Issue by Fryguy** [rails/rails#25145]
It seems when yaml-serializing AR objects, a lot of extra stuff is included in the dump that may not be necessary for reconstituting the objects, resulting in very large dumps.  I don't recall this much stuff prior to the attributes API rewrite

We are leveraging the attributes API and have a LOT of extra attributes.  I think the parts that directly references those attributes are ok, (like perhaps `raw_attributes` and/or `values`), but all of the metadata about the attributes (like the `AttributeSet` and `delegate_hash`) seem unnecessary.  Here is a gist of a particular class in ManageIQ where I just called `EmsCluster.first.to_yaml`: https://gist.github.com/Fryguy/63bc771798edaef1f10b8cc231bfe815  The "real" columns are everything you see in `values`, the rest are the "virtual attributes".

@matthewd This is what we had discussed.  If you need any more info let me know.  I'm still trying to go back to an old version of our code where AttributeSet wasn't in the output, but it's even there in Rails 4.2.

**Comment by rafaelfranca** [comment]
This change is what made us [stop using YAML serializing of AR object in identity_cache](https://github.com/Shopify/identity_cache/pull/242).

**Comment by Fryguy** [comment]
I updated the gist to include output from Rails 4.2 where we don't use the attributes API, but it still has the `AttributeSet` and the `delegate_hash`

**Comment by sgrif** [comment]
This wasn't just the result of the attributes API rewrite, it came from fixing real bugs that came from not including this information. I have some ideas on how we can reduce the size, but it hasn't been super high on the priority list for 5.0

**Comment by Fryguy** [comment]
Ah ok...thanks for the clarification @sgrif .

**Comment by Fryguy** [comment]
Thank you @sgrif ! 👏

**Comment by sgrif** [comment]
No problem. For the record, we could make them more compact if we really wanted, but this felt like a good 80/20 point for YAML size vs code complexity. At the point we're at now, if it's still too large, I would argue that YAML is the wrong format for that use case.
