### ISSUE TITLE
has_many :through does not initialize the through record with both associations

### ISSUE THREAD

**Issue by rrosenblum** [rails/rails#25140]
Given a `has_many :through` relationship. When trying to add an associated record, the record in the `through` table is not initialized with both records.

I have seen similar issues reported, but I could not find any record of this actual issue.

``` ruby
class Physician < ActiveRecord::Base
  has_many :appointments
  has_many :patients, -> { uniq }, through: :appointments
end

class Appointment < ActiveRecord::Base
  belongs_to :physician
  belongs_to :patient

  after_initialize do
    patient.id # or anything related to the patient. This will fail because patient is not associated yet
  end
end

class Patient < ActiveRecord::Base
  has_many :appointments
  has_many :physicians, through: :appointments
end

physician = Physician.create
patient = Patient.create

# Try adding a patient to the physician
physician.patients = [patient]
# or
physician.patients << patient
# NoMethodError: undefined method `id' for nil:NilClass
```
### Expected behavior

The through record is initialized with records to both associations. The `appointment` record should be initialized with both the `patient` and the `physician`.
### Actual behavior

The through record is not initialized with both associations. The `appointment` record that is created when adding a `patient` to `physician` is initialized with `physician`, but it does not have access to the `patient`. 
### System configuration

**Rails version**:
Tested against 3.2.22.2 and 4.2.6

**Ruby version**:
2.2.4

Digging through `ActiveRecord`, I believe that the issue comes from `ActiveRecord::Associations::HasManyThroughAssociation#build_through_record`. I have not tested back this far, but [looking at the source](http://apidock.com/rails/v3.2.3/ActiveRecord/Associations/HasManyThroughAssociation/build_through_record), it seems like this has been broken since 3.2.3.

``` ruby
def build_through_record(record)
  @through_records[record.object_id] ||= begin
    ensure_mutable

    through_record = through_association.build(*options_for_through_record)
    through_record.send("#{source_reflection.name}=", record)
    through_record
  end
end
```

The code fails during `through_record = through_association.build(*options_for_through_record)`.

Without the `after_initialize` hook, the `through_record` is built as `#<Appointment: id: nil, patient_id: nil, physician_id: 1, created_on: nil, updated_on: nil>`. The next line winds up adding the other association (`patient`) to the `through_record` (`appointment`), but this happens after the `appointment` has already been initialized and after the callbacks have finished.

**Comment by maclover7** [comment]
Can [reproduce the error](https://gist.github.com/maclover7/e057c925ec7323f01e7e0d4814b52c58) you are seeing, but not sure if this is a bug or expected behavior 😬

**Comment by rrosenblum** [comment]
Thanks for throwing together an executable example. Seeing has this has been around for as long as it has, I was fearful that this was expected behavior. If it is expected behavior, and not a bug, I am curious why this is the expected behavior. If we have access to both association records, why would the through record not be initialized with knowledge of both records?

**Comment by sevaorlov** [comment]
I guess that is because of inverse of association is not set automatically for associations with `through` option 
http://guides.rubyonrails.org/association_basics.html#bi-directional-associations

There is the same problem with associations with `foreign_key`

**Comment by al2o3cr** [comment]
Accessing associations in `after_initialize` is going to cause odd behavior. That callback executes as part of doing `Appointment.new`, before any of the associations have been set. See #13156 and #15296 for additional examples.

**Comment by rrosenblum** [comment]
Does `inverse_of` apply to this situation? If my understanding of the docs and the code is correct, then `inverse_of` doesn't come into play here. `inverse_of` does not work with `:through` associations. `has_many`, `belongs_to`, and `has_many :through` are all initialized in different ways.

**Comment by sevaorlov** [comment]
@rrosenblum, it applies, because when record is building - AR tries to find and set inverse association
https://github.com/rails/rails/blob/0991c4c6fc0c04764f34c6b65a42adce190440c3/activerecord/lib/active_record/associations/association.rb#L173

**Comment by rrosenblum** [comment]
> Accessing associations in after_initialize is going to cause odd behavior. That callback executes as part of doing `Appointment.new`, before any of the associations have been set. 

This is basically the exact issue that I am referring to. It is a problem because of how Rails is handling the initialization and the setting of the associations. I agree that running `Appointment.new` would not work because it does not know about either association. In the use case that I presented, we know about both associations so it should not be a problem. I am not trying to preload any associations. We should already have access to both of the associations. Running 
```ruby
physician = Physician.create
patient = Patient.create
Appointment.new(physician: physician, patient: patient)
```
works just fine. Both of the associations are set before the `after_initialize` callback is called. 

From the source code of `build_through_record`, what would be the issue of passing the association to the `build` method?

4.2.6 source
```ruby
through_record = through_association.build(*options_for_through_record) # after_initialize is called here
through_record.send("#{source_reflection.name}=", record) # here is where patient is set
```
Modification:
```ruby
through_record = through_association.build(through_scope_attributes.merge(source_reflection.name => record)
```
This way the association is set before the `after_initialize` callback.

I read through the linked issues. I can see where there are scenarios where `after_initialize` isn't the best choice, but it feels like the only suggested solution in every scenario was don't use `after_initialize`. If the community recommends against the use of `after_initialize`, then why is `after_initialize` still a supported feature?

**Comment by bverem** [comment]
By following the example above, I believe that this is still an issue in Rails 5.1.4.
