### ISSUE TITLE
[Document] Write Rails Guide about Deployment?

### ISSUE THREAD

**Issue by 1c7** [rails/rails#25149]
Can you guys write a new guide about the __Basic of Rails Deployment__?
I can't find any on http://guides.rubyonrails.org/ 
I know there are many tutorial on Google.
but I hope just official guide can have a  short intro about how many web server there are,
like puma, unicorn, passanger, rainbow.., maybe a bit of history, like Mongrel 
and thing like that.

would that be nice?

**Comment by prathamesh-sonpatki** [comment]
@1c7 That is good idea but the Github issue tracker is not the best place for it. We reserve the issue tracker for bug reports only. 

Please start the discussion on https://groups.google.com/forum/#!forum/rubyonrails-docs and see if there is enough interest in it.

Thanks again.

**Comment by 1c7** [comment]
got it. thanks
