### ISSUE TITLE
Class.subclasses returns unreachable classes

### ISSUE THREAD

**Issue by durandom** [rails/rails#25141]
When I remove a Class constant with `remove_const` it still is listed as a subclass.

```ruby
module A
  class Arghh
  end
end

p Object.subclasses.map(&:to_s).grep /Arghh/ #  => ["A::Arghh"]
A.send(:remove_const, :Arghh)
p Object.subclasses.map(&:to_s).grep /Arghh/ #  => ["A::Arghh"]
p Object.const_defined? :Arghh               #  => false
```

Is this the intended behavior?
It could be changed by appending `or !k.reachable?` to [this line](https://github.com/rails/rails/blob/89e2f7e722e06f900bdb1c14db33073c90d7cdea/activesupport/lib/active_support/core_ext/class/subclasses.rb#L37)
If that makes sense, I can open a PR with tests.

This is on rails master / ruby 2.2.4

Oh, the `module A` sneaked in from my original use case. This happens also with classes in top level namespace.

**Comment by matthewd** [comment]
> Is this the intended behavior?

Yes; the class still exists, regardless of whether it's ever been assigned to a constant.

**Comment by durandom** [comment]
Ok, fair enough.

Do you happen to know off your head a way to temporary define a class? Or remove it from ObjectSpace?

I'd need it in tests and that temporary class should not leak into other tests.
