### ISSUE TITLE
ActiveSupport silence undefined method `reopen' for nil:NilClass

### ISSUE THREAD

**Issue by Saidbek** [rails/rails#25151]
`silence` method described [here](http://guides.rubyonrails.org/active_support_core_extensions.html#silence) throws an error:

### Steps to reproduce

```
logger = Logger.new("log/development.log")
logger.silence(Logger::INFO) do
  logger.debug("In space, no one can hear you scream.")
  logger.info("Scream all you want, small mailman!")
end
```

getting an error:

```
DEPRECATION WARNING: `#capture(stream)` is deprecated and will be removed in the next release. (called from irb_binding at (irb):2)
NoMethodError: undefined method `reopen' for nil:NilClass
```

### System configuration
**Rails version**:
4.2.6
**Ruby version**:
ruby 2.1.5p273

**Comment by Edouard-chin** [comment]
The documentation is wrong:
`logger = Logger.new("log/development.log")`,
it should be `logger = ActiveSupport::Logger.new("log/development.log")`

Calling `silence` on the base ruby Logger object actually calls the capture method rails defined in the kernel module https://github.com/rails/rails/blob/4-2-stable/activesupport/lib/active_support/core_ext/kernel/reporting.rb#L108

**Comment by vipulnsward** [comment]
Going to give this a close, since this method is deprecated and removed from documentation in the latest docs -  http://edgeguides.rubyonrails.org/active_support_core_extensions.html .
