### ISSUE TITLE
Mashal.dump raises a TypeError since model.errors.details

### ISSUE THREAD

**Issue by jvenezia** [rails/rails#25165]
Rails 5 introduces `model.errors.details` https://github.com/rails/rails/pull/18322.

Since then, model instances can't be dumped:

```ruby
Marshal.dump User.create!
# => TypeError: can't dump hash with default proc
```

You can reproduce this with Rails 3&4 with this gem https://github.com/cowbell/active_model-errors_details.

Without this feature, it works fine.

**Comment by maclover7** [comment]
Reproduction script --> https://gist.github.com/maclover7/25fc448787724da6ff0cd46a9bec28fc

**Comment by vipulnsward** [comment]
Can't reproduce this on master. Is this that gem specific?

**Comment by sgrif** [comment]
No, the reproduction script posted is asserting that the error is raised for some reason. If you just do `Marshal.dump` it'll fail
