### ISSUE TITLE
Move new default initializers into their own directory

### ISSUE THREAD

**Issue by dhh** [rails/rails#25181]
We have a number of new initializers that are generated for new apps to prevent old apps from hitting breaking changes. They are:

```
active_record_belongs_to_required_by_default.rb
callback_terminator.rb
to_time_preserves_timezone.rb
per_form_csrf_tokens.rb
cookies_serializer.rb
request_forgery_protection.rb
session_store.rb
```

These are not files that anyone is likely to edit by hand on a new app, so they shouldn't litter the top initializers directory. Let's move all these into `config/initializers/new_framework_defaults/*`.

**Comment by dhh** [comment]
@prathamesh-sonpatki Found a bunch more default value initializers when running in normal mode (first saw this from API mode).

**Comment by dhh** [comment]
Oh, why would we be setting values in those that are different from framework defaults? Maybe those were new defaults for 4.2 and we actually should update 5.0 to have those be framework defaults without initializer files.

**Comment by prathamesh-sonpatki** [comment]
Cookies serializer initializer was provided as upgrade path while upgrading to 4.1 - http://edgeguides.rubyonrails.org/upgrading_ruby_on_rails.html#cookies-serializer.

Session store existed from a long time - https://github.com/rails/rails/blob/720aceeea9083e8139e06be5aaaa3b9db98f344d/railties/lib/generator/templates/app/config/initializers/session_store.rb.tt

I think new Rails 5 apps can set the cookies serializer to JSON by default and older upgraded apps will have the initializer which got generated when they upgraded to 4.1. But I am not sure about deprecation cycle for this change.

**Comment by dhh** [comment]
Ah yes, that's great. Let's go with that then kill the cookie serializer initializer. By the same token, we should be be able to set session store as the defaults and kill that initializer too. Changing from the encrypted cookie store is now an extremely uncommon specialization we don't need to call default attention to.

**Comment by dhh** [comment]
But we can treat that as a separate PR 👍
