### ISSUE TITLE
Provide HTML tag dynamic proxy

### ISSUE THREAD

**Issue by dhh** [rails/rails#25195]
`ActionView::Helpers::TagHelper` provides `#tag` and `#content_tag` for generating HTML tags, but feel outmodded with both lots of positional parameters and assuming XHTML as the default. I think we can fix both problems and reduce the API to a single proxy object in the vein of Builder.

```ruby

# To produce <span class="bookmark"></span> before:
content_tag :span, nil, class: 'bookmark'
# After (because we will keep an index of tags that need closing, like <span>, vs those that do not, like <br>)
tag.span class: 'bookmark'

# To produce <div id="post_1"> before:
content_tag :div, post.title, id: dom_id(post)  
# After:
tag.div post.title, id: dom_id(post)

# To produce <br> before:
tag :br, nil, true
# After (becomes like span, we know this tag doesn't need closing)
tag.br

# Would be nice to support nesting too, so to produce <div id="header"><span>hello</span></div>, you'd:
tag.div(id: 'header') { |tag| tag.span 'hello' }
```

The backwards compatible upgrade path here should be easy enough because `TagHelper#tag` currently requires at least one parameter. So if none is passed, we can switch into this new mode.

**Comment by vipulnsward** [comment]
The self-closing tags should be complaint to which spec?

**Comment by dhh** [comment]
HTML5.

**Comment by vipulnsward** [comment]
Some refs for someone who gets to this before me: 
https://www.w3.org/TR/html5/syntax.html#syntax-tag-omission
https://html.spec.whatwg.org/multipage/syntax.html#void-elements

**Comment by maclover7** [comment]
Do we need to go through a deprecation cycle for this? Even though I think `ActionView::Helpers::*` are `nodoc`'d, this still feels like a pretty big API change to me, which could affect third part libraries 😬

**Comment by vipulnsward** [comment]
@maclover7 this shouldn't need a deprecation in first cycle- see https://github.com/vipulnsward/rails/commit/347e82054ea212f3c3cf5a3c2b3d0a01d3b6ade6 for crude impl.

**Comment by dhh** [comment]
No hard deprecation needed. The proxy is instantiated through a call that wasn't possible before. We should soft deprecate via docs though.

**Comment by marekkirejczyk** [comment]
I am attaching a PR with prototype implementation HTML tag dynamic proxy. This is draft far from being ready, more a starting point for discussion. 
Feedback will be appreciated, let me know if direction is good and should I continue.

**Comment by vipulnsward** [comment]
@marekkirejczyk I started this here- https://github.com/vipulnsward/rails/commit/347e82054ea212f3c3cf5a3c2b3d0a01d3b6ade6 a week ago, din't get time to work over it. Will take a look at your PR as well.

**Comment by marekkirejczyk** [comment]
I updated pull request with hopefully close-to-final implementation. Feedback will be appreciated :)

**Comment by marekkirejczyk** [comment]
@dhh thanks for feedback, remarks has been fixed, questions answered, PR updated.

**Comment by marekkirejczyk** [comment]
New pull request added related to this topic: #25543

**Comment by rafaelfranca** [comment]
@kaspth what is missing to close this issue?

**Comment by kaspth** [comment]
@rafaelfranca nothing, I simply forgot to do it 😁

Fixed in #25543

**Comment by codener** [comment]
How is one supposed to use this with dynamic tag names, i.e. where the tag name comes from a variable?
```
# Before
tag = :span
content_tag tag, nil, class: 'bookmark'
```

**Comment by kaspth** [comment]
You can use Ruby's dynamic method sending ala `tag.public_send(tag, class: "bookmark")`. We could consider adding a `tag.build` method too though.

**Comment by codener** [comment]
Sure this would work, but it feels worse than a plain `content_tag tag, nil, class: 'bookmark'`. Since we're using dynamic tag names quite frequently, we'll stick with `content_tag`/`tag` until there is a native `tag.build tag, class: 'bookmark'`.

Anyway, thanks for the quick reply!

**Comment by kaspth** [comment]
You're welcome to open a PR to add it 👍 Would just need to rename `tag_string` essentially.
