### ISSUE TITLE
Running rails new with --skip-active-record ignores --database option

### ISSUE THREAD

**Issue by CucumisSativus** [rails/rails#25191]
### Steps to reproduce
* Run `rails new todo-app --database=mysql --skip-active-record` (also tested with postgresql)
* Check freshly created app's Gemfile

### Expected behavior
Gem `mysql2` should be present in the Gemfile

### Actual behavior
Gem `msql2` is missing in the Gemfile

### System configuration
**Rails version**: 4.2.6

**Ruby version**: ruby 2.2.2p95 (2015-04-13 revision 50295) [x86_64-darwin14]

Both `pg` and `mysql2` gems are ruby, not rails specific gems. In my opinion installing rails without activerecord has nothing to do with database driver as you might want to use different ORM. Please let me know what do you think about it

**Comment by vipulnsward** [comment]
This is intentional. If the App is not going to use it(since AR is not added), we don't add it by default, and the option is ignored.

**Comment by CucumisSativus** [comment]
@vipulnsward but still you can add another ORM like Sequel or ROM and use it without active record. As I mentioned before, in my opinion activerecord has nothing to do with the database adapter. Can we perhaps add a notice to inform users that rails ignores `--database` option when `--skip-active-record` is passed?

**Comment by vipulnsward** [comment]
We can update the guides instead to reflect this. Want to give this a try?

**Comment by CucumisSativus** [comment]
Sure thing. If you could just let me know where should I search for them I would be grateful :)
