### ISSUE TITLE
ActiveRecord composed_of doesn't trigger converter on mass-assignments / hash-assignment

### ISSUE THREAD

**Issue by tscholz** [rails/rails#25210]
### Steps to reproduce
Upgrading from Rails 3 we are running into issues with the current composed_of implementation. 

We're using an aggregation like:
```
class LdapConfig
  composed_of :mapping, class_name: 'OpenStruct', 
  mapping: [
    %w(attr_firstname firstname),
    %w(attr_lastname lastname)
  ],
  converter: -> (attrs) { attrs.kind_of?(Hash) ? OpenStruct.new(attrs) : attrs },
  constructor: -> (*attrs) {...}
end
```
for mapping custom ldap attribute names.

### Expected behavior
In Rails 3 we were able to assign attributes to it using mass-assignment through a form or assign a hash using `obj.mapping = {firstname:  'custom_ldap_FN_attr', lastname: 'custom_ldap_LN_attr'}`.

### Actual behavior
This is broken now because of [this block](https://github.com/rails/rails/blob/52ce6ece8c8f74064bb64e0a0b1ddd83092718e1/activerecord/lib/active_record/aggregations.rb#L259) that prevents the converter from being called.

May I ask if there is a reason not to call the converter first if defined? Why had the behaviour of the aggregations changed? How can I workaround this?

Thank you very much for looking into this!

### System configuration
**Rails version**: 4.2.6 (upgrading from 3.2)

**Ruby version**: 2.1.5

**Comment by maclover7** [comment]
Can you take your sample code above and create an executable test script using one of the templates [here](https://github.com/rails/rails/tree/master/guides/bug_report_templates), that would demonstrate the problem you are seeing? This helps us to easily reproduce issues locally :)

**Comment by sgrif** [comment]
@maclover7 He's given enough info to reproduce

**Comment by sgrif** [comment]
Backported to 5.0 in https://github.com/rails/rails/commit/41f47090a7cd95b3168081a1ee16aaae582f2ad3

**Comment by sgrif** [comment]
Backported to 4.2 in 0d5d8594b1a7d7caab0cbc9fe3340bb5bfbe79bd

**Comment by tscholz** [comment]
This was really quick! Thank you very much. 👍
