### ISSUE TITLE
rubocop complains about project generated by `rails new rubocop_test`

### ISSUE THREAD

**Issue by matkoniecz** [rails/rails#25223]
### Steps to reproduce

```
rails new rubocop_test
cd rubocop_test
rubocop -R
```

### Expected behavior
rubocop has no complaints

### Actual behavior

> 26 files inspected, 40 offenses detected

full log in https://gist.github.com/matkoniecz/0d2f92e6e09a5536e68b80b8762e7093

### System configuration
**Rails version**:

```
rails -v
Rails 4.2.6
```

**Ruby version**:

```
ruby -v
ruby 2.3.1p112 (2016-04-26 revision 54768) [i386-linux-gnu]
```

**rubocop version**

```
rubocop -v
0.40.0
```

I am aware that it may be in part (or completely) result in differences of opinion what kind of standards should be followed.

**Comment by vipulnsward** [comment]
> I am aware that it may be in part (or completely) result in differences of opinion what kind of standards should be followed.

Yes. Also not all orgs follow default rubocop compliance.
