### ISSUE TITLE
[ActionDispatch][ParameterFilter] does not work properly with Array (changes it to a Hash)

### ISSUE THREAD

**Issue by vledniov** [rails/rails#25237]
### Steps to reproduce

Suppose you have a controller where you filter some data inside a collection of models.

```ruby
data = User.first(2)
pf = ActionDispatch::Http::ParameterFilter.new([/^name$/, "email"])
serialize_collection(pf.filter data)
```

Where `serialize_collection` is a method from a 3rd party library, that transforms your response into a beautifully arranged, paginated data.

`pf.filter data` does not return a filtered **Array**, but a non-filtered **Hash**. After looking into the implementation, it seems legit, works as it should, but is peculiar about the filtering and the returning value.

### Expected behavior
`pf.filter data` should return:

```ruby
[
  {
    "id"=>123622786,
    "name"=>"[FILTERED]",
    "email"=>"[FILTERED]",
    "created_at"=>Wed, 01 Jan 2014 00:00:00 UTC +00:00,
    "updated_at"=>Mon, 04 Apr 2016 10:31:33 UTC +00:00
  },
  {
    "id"=>171831590,
    "name"=>"[FILTERED]",
    "email"=>"[FILTERED]",
    "created_at"=>Wed, 01 Jan 2014 00:00:00 UTC +00:00,
    "updated_at"=>Mon, 04 Apr 2016 10:31:33 UTC +00:00
  }
]
```

### Actual behavior
Now, `pf.filter data` returns:

```ruby
{
  {
    "id"=>123622786,
    "name"=>"Alexander",
    "email"=>"alex@gmail.com",
    "created_at"=>Wed, 01 Jan 2014 00:00:00 UTC +00:00,
    "updated_at"=>Mon, 04 Apr 2016 10:31:33 UTC +00:00
  }=>nil,
  {
    "id"=>171831590,
    "name"=>"Wilfred",
    "email"=>"wilfred@gmail.com",
    "created_at"=>Wed, 01 Jan 2014 00:00:00 UTC +00:00,
    "updated_at"=>Mon, 04 Apr 2016 10:31:33 UTC +00:00
  }=>nil
}
```

### System configuration
**Rails version**: 4.2.6

**Ruby version**: 2.2.1

**Comment by matthewd** [comment]
The `filter` method is documented as taking a parameter named `params`; that needs to be a hash. If you want to filter an array of hashes, you probably want to involve `Enumerable#map`.
