### ISSUE TITLE
assets precompile is connecting to db

### ISSUE THREAD

**Issue by u007** [rails/rails#25246]
### Steps to reproduce
RAILS_ENV=production rails assets:precompile
config/application.rb
...
config.assets.initialize_on_precompile = false
...

### Expected behavior
precompile should not connect to db

### Actual behaviour
attempting to connect to production db

### System configuration
5.0.0.rc1

**Ruby version**:
2.2.4

**Comment by rafaelfranca** [comment]
This option is not a valid option anymore. Rails by default don't connect to the database when precompiling assets but if your application load any code that does it will. That said, if your application is connecting to the database it is something to be fixed in your application.

**Comment by u007** [comment]
hi @rafaelfranca  thanks for your reply.
how do i look for the db connection issue on my code?
is it config/initializer or config/application or any other places?
i find that its running all initialiser

**Comment by philippneugebauer** [comment]
I'm interested in this answer as well

**Comment by skunkworker** [comment]
To get around this I've used https://github.com/nulldb/nulldb, specifically in creating a docker image and precompiling the assets inside.
Like `RUN DB_ADAPTER=nulldb bundle exec rake assets:precompile`

**Comment by rafaelfranca** [comment]
You can change your database connection to something invalid and see where it raises exceptions. Those are the places were your application is connecting to the database.

**Comment by dcosson** [comment]
In case anyone comes across this from google like I did, I spent a while trying to figure this out in my app. The stacktrace just showed that it was being triggered in environment.rb as the app initialized so it was hard to track down.

The issue ended up being that we're using the schema cache and somewhere in rails initializers if a schema_cache.yml file is present that triggers a check of the current migration from the DB.

I think this should potentially be treated as a rails bug -- the above comment claimed that Rails itself won't connect to the db during precompile, but it seems that's not always the case.

**Comment by schmijos** [comment]
Invalidating the database configuration at least doesn't help in Rails 6 because there is an initializer loaded with (`require 'active_record/railtie'`)
![image](https://user-images.githubusercontent.com/245443/98090348-33e39000-1e84-11eb-8b7a-2881a24bf123.png)

**Comment by scomma** [comment]
> In case anyone comes across this from google like I did, I spent a while trying to figure this out in my app. The stacktrace just showed that it was being triggered in environment.rb as the app initialized so it was hard to track down.
> 
> The issue ended up being that we're using the schema cache and somewhere in rails initializers if a schema_cache.yml file is present that triggers a check of the current migration from the DB.
> 
> I think this should potentially be treated as a rails bug -- the above comment claimed that Rails itself won't connect to the db during precompile, but it seems that's not always the case.

This is definitely the case. Run into this issue as soon as I start using schema_cache. Anybody aware of a workaround?

**Comment by defsprite** [comment]
For posteriority:

While this *looks* like a rails issue when debugging, it usually boils down to careless requiring in the railtie of certain gems (e.g. `traco`, `schema_cache` or `data_migrations`). In order to fix the issue, proper situation-aware auto loading should be implemented there.

For the time being, nulldb as mentioned above https://github.com/rails/rails/issues/25246#issuecomment-360384748 seems the way to go when no DB is around during asset compilation.

**Comment by renewooller** [comment]
if you have FactoryBot, check that your class you define for your factory is a string rather than the actual class

**Comment by BrandonTeixeiraStream** [comment]
@rafaelfranca, this might a dumb question but why is it bad to hit your db while initialising your app

**Comment by henrik242** [comment]
We solved this by using [pg_virtualenv](https://manpages.ubuntu.com/manpages/focal/man1/pg_virtualenv.1.html) in our docker image:
``
RUN pg_virtualenv -o 'listen_addresses="127.0.0.1"' -t bundle exec rake assets:precompile --trace
```

**Comment by BrandonTeixeiraStream** [comment]
@henrik, this isn't really a solution for us as we have a dockerfile which is used for production and CI/CD. Do you have two separate docker files then?

**Comment by henrik242** [comment]
We use this image in production. You can uninstall postgresql-common in the image afterwards if you like.

**Comment by rafaelfranca** [comment]
> this might a dumb question but why is it bad to hit your db while initialising your app

because if you db is down, you entire application can't go up. This should not be the case. Sure, you should get error when trying to access the database, but you should not get error in pages that don't have to access the database, like the error pages itself.x

**Comment by BrandonTeixeiraStream** [comment]
Thank you @rafaelfranca that makes sense.

**Comment by dnalbach** [comment]
It's also worth noting that not everyone does the asset compilation as part of a build step that would have access to the database. In which case there may be no database in that particular build step, and trying to contact it would be undesirable.

**Comment by mizukami234** [comment]
Just information for people who are using apartment gem: https://github.com/rails-on-services/apartment/issues/142
You can avoid this with `APARTMENT_DISABLE_INIT=1`
