### ISSUE TITLE
rails 5 db:seed requires db:migrate?

### ISSUE THREAD

**Issue by u007** [rails/rails#25249]
### Steps to reproduce
rails db:schema:load
rails db:seed

### Expected behaviour
run without asking for migration
### Actual behaviour
asking to run migration before seed

### System configuration
**Rails version**:
5.0.0.rc1
**Ruby version**:
2.2.4

**Comment by sgrif** [comment]
I'm unable to reproduce this issue. I'm assuming that your `schema.rb` does include all migrations present. Otherwise, this is the expected behavior. If my assumption is correct, maybe try `spring stop`? In any case, there doesn't appear to be any issue in Rails here.
