### ISSUE TITLE
rails fails to parse erb in `database.yml`, whereas rake successfully parses

### ISSUE THREAD

**Issue by bitsapien** [rails/rails#25244]
### Steps to reproduce
Change your `database.yml` to this 
```
default: &default
  adapter: sqlite3
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: <%= ENV['HOME'] %>/shared/db/production.sqlite3
```

Run `bin/rake db:migrate` (ofcourse create some migrations before this)

Refer a model in your views, and load the rails application

### Expected behavior
ActiveRecord must find the database at `/Users/bitsapien/shared/db/production.sqlite3`

### Actual behavior
 This is the error I get :
```
2016-06-02 10:29:33 +0530: Rack app error: #<ActiveRecord::NoDatabaseError: No such file or directory @ dir_s_mkdir - /shared/db>
/Users/bitsapien/.rvm/gems/ruby-2.3.1/gems/activerecord-5.0.0.rc1/lib/active_record/connection_adapters/sqlite3_adapter.rb:37:in `rescue in sqlite3_connection'
/Users/bitsapien/.rvm/gems/ruby-2.3.1/gems/activerecord-5.0.0.rc1/lib/active_record/connection_adapters/sqlite3_adapter.rb:14:in `sqlite3_connection'
/Users/bitsapien/.rvm/gems/ruby-2.3.1/gems/activerecord-5.0.0.rc1/lib/active_record/connection_adapters/abstract/connection_pool.rb:721:in `new_connection'
```
The file gets created in the right path after a `bin/rake db:migrate` but it looks in the wrong place. Probably `activerecord` is not parsing `<%= ENV['HOME'] %>` in `database.yml`, which is evaluating to a `nil`

### System configuration
**Rails version**:
5.0.0.rc1
**Ruby version**:
2.3.1

**Comment by chashmeetsingh** [comment]
@bitsapien I guess database if of the form
RAILS_ROOT/(path in database.yml)

**Comment by andela-oakinniranye** [comment]
I think the ERB is parsed, probably you should check that the HOME key is set in the ENV variable. As it seems to be evaluating to `nil`

**Comment by maclover7** [comment]
^^ agree with above comments, can you check that the `HOME` environment variable is defined, and that the directory where you want to have the `.sqlite3` file exists?

**Comment by sgrif** [comment]
Confirming that this is not an issue. If rails wasn't parsing the ERB, it'd be trying to access `<%= ENV['HOME'] %>/shared/db/production.sqlite3` as a path, not root. `ENV["HOME"]` is evaluating to `nil`. Make sure that it's properly set for your environment.

**Comment by bitsapien** [comment]
Thanks.
