### ISSUE TITLE
`Date#to_formatted_s` bug

### ISSUE THREAD

**Issue by ilyakorol** [rails/rails#25251]
Hi all, it seems like a little bug:

```
Date.today 
=> Thu, 02 Jun 2016
Date.today.to_formatted_s(:long)
=> "June  2, 2016" # 2 spaces between June and 2
```
### Expected behavior
```
Date.today.to_formatted_s(:long)
=> "June 2, 2016" # 1 space between June and 2
```

### System configuration
**Rails version**: 4.2.6

**Ruby version**: 2.2.3

**Comment by maclover7** [comment]
Can reproduce on master.

**Comment by ilyakorol** [comment]
So, I'll create a pull request soon.

**Comment by jonathanhefner** [comment]
@sgrif What about using `%-e` (or `%-d`) instead of `%d`?

**Comment by sgrif** [comment]
I specifically mentioned the reasoning in the commit message.

**Comment by jonathanhefner** [comment]
@sgrif  My fault!  I did miss that last sentence!

However, in the case of the more human-readable `:long`, I think people are more likely to expect no leading zeros, rather than constant width (particularly in HTML output).
