### ISSUE TITLE
Studying the evolution of the Rails project

### ISSUE THREAD

**Issue by gustavopinto** [rails/rails#25255]
Hi there, 

I'm a researcher studying software evolution. As part of my current research, I'm studying the implications of migrating an open-source software project to GitHub, for instance, if the project succeed in attracting newcomers. Rails was in my list.

To further analyze the impacts of Rails' migration, we analyzed the git log commit history of your project in terms of number of contributions, number of newcomers and number of contributors per month. The following figure presents a temporal perspective regarding these three measures. 

![rails](https://cloud.githubusercontent.com/assets/235062/15752423/dd5407d2-28a2-11e6-88b3-18e86af54401.png)

Given the numbers presented in the graphic, we would like to ask Rails developers the following questions:

1. What motivated the project to migrate to Github? How do you evaluate the benefits of this migration?
2. Does this snapshot make sense? Did you find any inconsistency on the data?
3. Do you have any internal policy to promote/attract/retain newcomers? If so, do them succeed?
4. Why did the number of contributors increased after its migration to GitHub? Was it expected?

Thanks in advance for your collaboration,

Gustavo Pinto, PhD
http://www.gustavopinto.org

**Comment by fxn** [comment]
Before the migration Rails used Subversion, which does not distinguish author from committer. But we have a custom contributors listing which is more accurate and accounts for those years via conventions at the time.

That's http://contributors.rubyonrails.org.

I could send you a dump of the database if you want.

**Comment by rafaelfranca** [comment]
Hey Gustavo, great subject!

> What motivated the project to migrate to Github? How do you evaluate the benefits of this migration?

I was not here when this was decided, maybe @dhh is the best person to answer that.

> Does this snapshot make sense? Did you find any inconsistency on the data?

After the GitHub migration the snapshot make sense but before the migration it is worth to check what @fxn said above, the committer may not be the author of the patch so you can find more accurate data using http://contributors.rubyonrails.org.

> Do you have any internal policy to promote/attract/retain newcomers? If so, do them succeed?

Right now we don't have. There is a constant flow of newcomers to the Rails repository for various of reasons. Our team don't have any strong policy other than: be nice with the newcomers, give them the attention that they deserves, give them good feedback and try to motivate them to solve their own problems. It is more like a social convention followed by all members of the Rails team that a policy and we try our best to keep contributing to Rails one great experience to everyone. And, for the number of newcomers we have every year and the long term contributors we retain it is succeeding.

> Why did the number of contributors increased after its migration to GitHub? Was it expected?

I don't know if it was expected either, but I have some reasons for the number of contributors increased:

* It is easier to contribute. Traditional workflow of sending an email with the patch to an obscure mailing list while works, is not very use friendly.
* It is easier to review and apply changes. This doesn't seems to have direct effect in newcomers but I suspect faster feedback also means more contributions.

**Comment by rafaelfranca** [comment]
Forgot to add. The issue was closed because we try to keep our issue tracker focused on bugs and pull requests to be able to give faster feedbacks to contributions.

**Comment by fxn** [comment]
Even after GitHub the difference between our credits and the ones given by GitHub is not small, the contrib app really tries to go that extra mile. [Aliases](https://github.com/carlhuda), [multiple authors](https://github.com/rails/rails/commit/1eebfc9f66149020efe23a620da110424e5a5c33) (look at the author in the Git commit), [multiple authors given as handlers](2bbcca004cc232cef868cd0e301f274ce5638df0), [credits given in commit messages](7463aa19b1a1492bcc6aeb61e3163a893856453c), ... quite a bunch of fine details.

GitHub just links commits to accounts, which is normal.

**Comment by gustavopinto** [comment]
Hi @rafaelfranca, thank you for your comments.

> It is easier to contribute. 
> t is easier to review and apply changes.

Great points! However, I think that most of these points are related to the Github development process, instead of, for instance, the Rails policy of attracting and retaining contributors. Am I correct, or do you have any other thoughts (e.g., Rails popularity might influence one to become a contributor)?
