### ISSUE TITLE
Feature: Make Javascript Standalone

### ISSUE THREAD

**Issue by hickscorp** [rails/rails#25266]
As many other do, we only use Rails as our API server. The application doesn't serve any HTML, Javascript nor CSS.

Based on our API documentation, we maintain clients based on different technologies (Objective-C, ReactJS, etc). It would be very nice to separate the ActionCable Javascript files and make them available as an NPM dependency, allowing the clients to stay decoupled.

Also, having an Objective-C or Java client would be really the icing on the cake.

**Comment by rafaelfranca** [comment]
This is already implemented

**Comment by hickscorp** [comment]
Any doc on that specific topic?

**Comment by rafaelfranca** [comment]
https://github.com/rails/rails/pull/24991

**Comment by hickscorp** [comment]
Cool, thanks for pointing that out.
