### ISSUE TITLE
ActiveRecord Integer column validation

### ISSUE THREAD

**Issue by itaymishan** [rails/rails#25268]
### Steps to reproduce
When creating a validation on a model such as:
`  validates :some_value, presence: true, numericality: {
    integer: true, greater_than: 1, if: :some_value?
  }`
1. Create a validation on an ActiveRecord model column of type integer value
2. Create an object from the model:
`ModelX.create!(some_value: 0.5)` 

### Expected behavior
I would expect that validation would fail
### Actual behavior
Validation passes and object is created
### System configuration
**Rails version**:
Rails 4.2.6
**Ruby version**:
ruby 2.3.0p0 (2015-12-25 revision 53290) [x86_64-darwin14]

**Comment by sikachu** [comment]
`time_used?` would return `true` if it's not `nil`. It looks like you call `create!` with `time_used: 0.5`. Is that example correct?

**Comment by itaymishan** [comment]
The Thing is I would expect that `greater_than: 1` will make the validation to fail (since the value is 0.5)

**Comment by Edouard-chin** [comment]
I'm also confused by your example. You added a validation rule on the `some_value` attribute, there is no validation on the `times_used` one.

I'm not able to reproduce your issue using this gist: https://gist.github.com/Edouard-chin/5bf7cb5f862d8a577d36ce52cddfbb11

**Comment by itaymishan** [comment]
Updated the issue.
some_value is just an integer column inside a model.
The validation simply suppose to make sure his value is an integer greater than 1, for some reason when I create an object using some_value=0.5 it passes validation and assign 0 to column.

**Comment by vipulnsward** [comment]
@itaymishan can you create an executable gist with failing scenario based on what @Edouard-chin post here - https://gist.github.com/Edouard-chin/5bf7cb5f862d8a577d36ce52cddfbb11

**Comment by sgrif** [comment]
What is `if: :some_value?` meant to accomplish? `https://github.com/rails/rails/issues/25268#issuecomment-223673493` is incorrect. `some_value?` is roughly equivalent to `some_value.blank?`. `0.5` is cast to `0` (this is Ruby's behavior for `to_i` on floats, not a decision by Rails), and `0.blank?` returns true.

So this is the intended behavior with that validation as you've defined it. The `if: :some_value?` looks like it serves no purpose, so I'd recommend removing it.
