### ISSUE TITLE
SQLite3::ConstraintException: assignments.created_at may not be NULL

### ISSUE THREAD

**Issue by basco-johnkevin** [rails/rails#25273]
### Steps to reproduce

Models:
```
class User < ActiveRecord::Base
  has_many :assignments
  has_many :roles, through: :assignments
end

class Role < ActiveRecord::Base
  has_many :assignments
  has_many :users, through: :assignments
end

class Assignment < ActiveRecord::Base
  belongs_to :user
  belongs_to :role
end
```

Fixtures:
```
// users.yml:
admin:
  email: admin@gmail.com
  roles: admin

// roles.yml
admin:
  name: admin
```

When I run `rake test`, it shows me this error: `SQLite3::ConstraintException: assignments.created_at may not be NULL`

The test is just a very simple auto generated test by Rails for one of my controllers:

```
class InstallersControllerTest < ActionController::TestCase
  test "should get index" do
    get :index
    assert_response :success
  end
end
```

Complete error message:
```
InstallersControllerTest#test_should_get_index:
ActiveRecord::StatementInvalid: SQLite3::ConstraintException: assignments.created_at may not be NULL: INSERT INTO "assignments" ("user_id", "role_id") VALUES (135138680, 135138680)
```

schema.rb:
```
  create_table "assignments", force: :cascade do |t|
    t.integer  "user_id"
    t.integer  "role_id"
    t.datetime "created_at", null: false
    t.datetime "updated_at", null: false
  end

  add_index "assignments", ["role_id"], name: "index_assignments_on_role_id"
  add_index "assignments", ["user_id"], name: "index_assignments_on_user_id"
```

### Expected behavior
It should auto populate the `created_at` field

### Actual behavior
It doesn't auto populate the `created_at` field

### System configuration
**Rails version**: 4.2.6

**Ruby version**: 2.1.2p95

**Comment by maclover7** [comment]
Can you please provide a sample application that replicates the error you are seeing? We can debug further from there :)

**Comment by basco-johnkevin** [comment]
@maclover7 I updated my Ruby version to 2.3.1p112 and the issue is still present.

Here's the sample application that replicates the error: https://github.com/basco-johnkevin/rails-fixtures

**Rails version:** Rails 4.2.6

**Ruby version:** ruby 2.3.1p112

**Comment by vipulnsward** [comment]
Problem is the way the fixtures are setup, you can't pass admin to roles, you will need to build the assignment fixture instead-
```
# users.yml:
admin:
  email: admin@gmail.com

# roles.yml
admin:
  name: admin

# assignments.yml
admin:
  user: admin
  role: admin
```

When you specify role, it will to build an implicit hmt object, and fail at the constraint.

**Comment by basco-johnkevin** [comment]
@vipulnsward Thanks! It works now. But shouldn't it still set the `created_at` field when it tries to build an implicit hmt object? Because, why not?
