### ISSUE TITLE
polymorphic has many with default scope error

### ISSUE THREAD

**Issue by yoelblum** [rails/rails#25288]
### Steps to reproduce
I think there's an issue in polymorphic associations that try to use a default scope:
Create any polymorphic relationship and try to use a default scope on the has_many . 
   ```
 #account.rb
 class Account < ActiveRecord::Base
     has_many :notes, {as: :notable}, ->{reverse_order}
end
 #note.rb
  class Note < ActiveRecord::Base
      belongs_to :notable, polymorphic: true
 end
#Now simply type in the console:
Account.first.notes 
```
 It happened to another guy in a similar case:
http://stackoverflow.com/questions/36369333/use-polymorphic-associations-with-default-scope 

### Expected behavior
Default scope should be working (in my example, account notes should be ordered in reverse order)

### Actual behavior
The  association default scope is seems to be ignored 

### System configuration
**Rails version**:
4.2.6
**Ruby version**:

**Comment by vipulnsward** [comment]
This works as expected- https://gist.github.com/vipulnsward/aeec0e8007b2eb11178d61e1df236614
The position of the scope that you are passing is different than the signature, pass the scope after the name and options later.
