### ISSUE TITLE
option_groups_from_collection_for_select fails with NoMethodError: undefined method `map' for ....

### ISSUE THREAD

**Issue by rob99** [rails/rails#25295]
### Steps to reproduce

    rails c
    av =  ActionView::Base.new
    @coll = Fruit.all
    html = av.option_groups_from_collection_for_select(@coll, :color, :color, :id, :name)

### Expected behavior

Should return a html fragment of optgroup and option tags

### Actual behavior

    # => NoMethodError: undefined method `map' for "GREEN":String
    from C:/jruby-9.1.2.0/lib/ruby/gems/shared/gems/actionview-4.2.6/lib/action_view/helpers/form_options_helper.rb:394:in `options_from_collection_for_select'

### System configuration
**Rails version**: 4.2.6

**Ruby version**: jruby 9.1.2.0 (2.3.0) 2016-05-26 7357c8f Java HotSpot(TM) 64-Bit Server VM 24.71-b01 on 1.7.0_71-b14 +jit [mswin32-x86_64]

**Comment by rob99** [comment]
It seems that `option_groups_from_collection_for_select` calls `options_from_collection_for_select` but with the grouping value as the first arg. 

`options_from_collection_for_select` expects the collection to be the first arg.

**Comment by andela-oakinniranye** [comment]
The second argument should be the `group_method`, a collection nested under the first collection. http://api.rubyonrails.org/classes/ActionView/Helpers/FormOptionsHelper.html#method-i-option_groups_from_collection_for_select

**Comment by maclover7** [comment]
^^ agree with this analysis. @rob99 Can you try again with this advice, and see if the error still exists? Also, if possible, can you create an executable test script using one of the templates [here](https://github.com/rails/rails/tree/master/guides/bug_report_templates), that would demonstrate the problem you are seeing?

**Comment by rob99** [comment]
@andela-oakinniranye quite right!  My misunderstanding.  Thanks...
