### ISSUE TITLE
inverse_of: parent not finding children after child.parent = parent

### ISSUE THREAD

**Issue by stevenspiel** [rails/rails#25299]
I'm using Rails 4.2.5.2 and inverse_of relationships are not behaving as expected.

### Steps to reproduce

```
$ rails new foo
$ rails g model parent
$ rails g model child parent:references
$ rake db:migrate
```

app/models/chid.rb:
```rb
class Child
  belongs_to :parent, inverse_of: :children
end
```

app/models/parent.rb:
```rb
class Parent
  has_many :children, inverse_of: :parent
end
```

```
$ rails c
2.3.0 :002 > p = Parent.new
 => #<Parent id: nil, name: nil, created_at: nil, updated_at: nil>
2.3.0 :003 > c = Child.new
 => #<Child id: nil, parent_id: nil, created_at: nil, updated_at: nil>
2.3.0 :004 > c.parent = p
 => #<Parent id: nil, name: nil, created_at: nil, updated_at: nil>
2.3.0 :005 > p.children
 => #<ActiveRecord::Associations::CollectionProxy []>
2.3.0 :006 > p.children[0]
 => nil
```

### Expected behavior

I would expect `p.children` to return `[#<Child id: nil, parent_id: nil, created_at: nil, updated_at: nil>]`

### Actual behavior

I'm getting `[]`

### System configuration
**Rails version**:
4.2.5.2
**Ruby version**:
2.3.0

### Update

I just tried this on a new rails `5.0.0.rc1` app and I'm getting the same behavior.

**Comment by Amrani** [comment]
@stevenspiel Try creating the records so ID's will be assigned. Then the associations will be able to find the records. Replace Child.new with Child.save or Child.create

**Comment by stevenspiel** [comment]
Is there no way for it to be done in-memory?

**Comment by Amrani** [comment]
The has many relationship initiates a query in the database looking for a mapping. If you do not want to persist the relationship, you can

**Comment by Amrani** [comment]
The has many relationship initiates a query in the database looking for a mapping. If you do not want to persist the relationship. I think you can do something like this 
```
class Parent
	attr_accessor :children		
end

p = Parent.new

p.children << Child.new
```

**Comment by maclover7** [comment]
Yep, agree with @Amrani -- you need to save your records to the database before trying to query them (thus, there is no bug here). For reference, I've created a reproduction script [here](https://gist.github.com/maclover7/ddc3fc8769861af7ece854142246fbcf).
