### ISSUE TITLE
Active Record does not dump foreign key's referential actions with MySQL's ANSI_QUOTES

### ISSUE THREAD

**Issue by buehmann** [rails/rails#25300]
### Steps to reproduce

1. Prepare a schema in MySQL with a foreign key that has a referential action, e.g. `on delete cascade`.
1. Set your Active Record connection to use `sql_mode = ANSI_QUOTES`
1. Dump the schema using `rake db:schema:dump`

### Expected behavior
`db/schema.rb` should include `on_delete: :cascade` option in `add_foreign_key`.

### Actual behavior
`on_delete` option is missing. If you work without `sql_mode = ANSI_QUOTES` it is there.

### Diagnosis
Code to reproduce: https://gist.github.com/buehmann/55e155b4b56f75fe1a755bcab82f1a02

In the following line, Active Record tries to parse referential actions out of `show create table` output, but only expects ``` `this` ``` style of quoting, not `"that"` one.
https://github.com/rails/rails/blob/706f7e9c3e2a4807e37b1a1ef21febd6444adf6f/activerecord/lib/active_record/connection_adapters/abstract_mysql_adapter.rb#L895

```
irb(main):017:0> @connection.execute("set session sql_mode = ''")
   (0.2ms)  set session sql_mode = '' /*application:Banking*/
=> nil
irb(main):018:0> @connection.select_one("SHOW CREATE TABLE a")["Create Table"]
   (0.3ms)  SHOW CREATE TABLE a /*application:Banking*/
=> "CREATE TABLE `a` (\n  `id` int(11) NOT NULL AUTO_INCREMENT,\n  `b_id` int(11) DEFAULT NULL,\n  PRIMARY KEY (`id`),\n  KEY `index_a_on_b_id` (`b_id`) USING BTREE,\n  CONSTRAINT `index_a_on_b_id` FOREIGN KEY (`b_id`) REFERENCES `b` (`id`) ON DELETE CASCADE\n) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci"
irb(main):019:0> @connection.execute("set session sql_mode = 'ansi_quotes'")
   (0.2ms)  set session sql_mode = 'ansi_quotes' /*application:Banking*/
=> nil
irb(main):020:0> @connection.select_one("SHOW CREATE TABLE a")["Create Table"]
   (0.3ms)  SHOW CREATE TABLE a /*application:Banking*/
=> "CREATE TABLE \"a\" (\n  \"id\" int(11) NOT NULL AUTO_INCREMENT,\n  \"b_id\" int(11) DEFAULT NULL,\n  PRIMARY KEY (\"id\"),\n  KEY \"index_a_on_b_id\" (\"b_id\") USING BTREE,\n  CONSTRAINT \"index_a_on_b_id\" FOREIGN KEY (\"b_id\") REFERENCES \"b\" (\"id\") ON DELETE CASCADE\n) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci"
```

### System configuration
**Rails version**: `Using rails 5.1.0.alpha from git://github.com/rails/rails.git (at master@3fc5577)`

**Ruby version**: `ruby 2.3.1p112 (2016-04-26 revision 54768) [x86_64-darwin15]`

**MySQL version**: `mysqld  Ver 5.6.27 for osx10.10 on x86_64 (Homebrew)`

**Comment by eileencodes** [comment]
I hit the issue where `on_delete: :cascade` wasn't showing up in my foreign keys in our app this week. The odd thing is though, I'm not using ANSI_QUOTES mode in my MySQL version so I'm not sure why I'm seeing this issue too yet. I can confirm that @kamipo's PR fixes my issue. I'm using MySQL 5.6. A co-worker of mine is using MySQL 5.7 and does not see the issue (the schema is correctly updated post migration).

If I manually run schema dump after the migration the schema is correctly updated. I'm not yet sure what it is about my version of MySQL that is causing me to see this as well.
