### ISSUE TITLE
Instance from docs does not work

### ISSUE THREAD

**Issue by ilyakorol** [rails/rails#25312]
`mattr_accessor` not works as expected. 

### Steps to reproduce (from [docs](http://apidock.com/rails/v4.2.1/Module/mattr_accessor))
```
module HairColors
  mattr_accessor :hair_colors
end

class Person
  include HairColors
end

Person.hair_colors = [:brown, :black, :blonde, :red]
```

### Actual behavior
`NoMethodError: undefined method 'hair_colors=' for Person:Class`

### System configuration
**Rails version**: 4.2.6

**Ruby version**: 2.2.3

**Comment by robin850** [comment]
Hi @ilyakorol,

Yes, this cannot work since `include`mixes in instance methods and we are trying to call a class method in the documentation example. We should rather use `extend` to make the example work. Do you want to give it a try updating the documentation ? :-)

Thanks for reporting !

**Comment by ilyakorol** [comment]
@robin850, thanks for you reply, I can create PR soon:)

**Comment by ilyakorol** [comment]
It seems like this issue has been already fixed in master.

**Comment by robin850** [comment]
@ilyakorol : Ah yes, I forgot to check the edge API before asking you to send a patch, sorry about that ! :/
