### ISSUE TITLE
Association not loaded when included as a concern

### ISSUE THREAD

**Issue by MatthewRDodds** [rails/rails#25316]
### Steps to reproduce

I have a Property model (among others) that include the following concern:

```ruby
module Addressable
  extend ActiveSupport::Concern

  included do
    has_one :address, as: :addressable, dependent: :destroy
    acts_as_mappable through: :address

    accepts_nested_attributes_for :address,
      allow_destroy: true,
      reject_if: :all_blank
  end
end
```

### Actual behavior
The association is not loaded for my Property model
```
pry(main)> Property.ancestors.include?(Addressable)
=> true
pry(main)> Property.new.methods.grep /address/
=> []
```

### Expected behavior

If I copy what is included in the concern to the model and reload, the association works:

```
pry(main)> Property.new.methods.grep /address/
=> [:autosave_associated_records_for_address, :validate_associated_records_for_address, :auto_geocode_address, :address, :address=, :build_address, :create_address, :create_address!, :address_attributes=]
```

### System configuration
Rails **4.2.6**:
Ruby **2.3.1**:

**Comment by sgrif** [comment]
Unable to reproduce. At first glance I would guess that it's an issue with the gem adding `acts_as_mappable`. If you can reproduce without that gem, please comment with a script that can be used to reproduce the issue using [our standard bug report template](https://github.com/rails/rails/blob/master/guides/bug_report_templates/active_record_master.rb) and I will reopen.

**Comment by sgrif** [comment]
For posterity, [this is the script I attempted to reproduce with](https://gist.github.com/sgrif/dcada9591c48ebd05aa7d0c6a06f0da7)

**Comment by MatthewRDodds** [comment]
This was the result of a naming conflict. My module was being overridden. Apparently a gem I added, [letter_opener](https://github.com/ryanb/letter_opener), depends on a gem called [launchy](https://github.com/copiousfreetime/launchy), which depends on a gem [addressable](https://github.com/sporkmonger/addressable), which is what caused my issue. Thanks for the quick feedback @sgrif

**Comment by sgrif** [comment]
No problem. Part of why we ask for the repro script with that template is
to filter out cases like this (which are quite common. 😃)

**Comment by InteNs** [comment]
This was also a problem i was having, in my case I had a controller concern with the same name as my model concern.

**Comment by taylorthurlow** [comment]
@MatthewRDodds You're a legend! Glad I didn't have to spend time figuring this one out. I had exactly the same issue.

**Comment by FlandersBurger** [comment]
> 3 days later. haha. Thanks @MatthewRDodds . You should post it on stackoverflow too.
