### ISSUE TITLE
rails db command to to load schema_search_path config when using postgresql

### ISSUE THREAD

**Issue by marcelokanzaki** [rails/rails#25326]
This is a feature request.

### Steps to reproduce

0. Set the "schema_search_path" config in database.yml: `my_schema, public`
1. At the root of a rails app run: `rails db` to start up a database console
2. When in the database console, print the schema_search_path like this: `show search_path;`

### Expected behavior
```sql
     search_path     
---------------------
 "my_schema, public"
(1 row)
```

### Actual behavior

```sql
   search_path   
-----------------
 "$user", public
(1 row)
```

### System configuration
**Rails version**: Rails 4.2.6

**Ruby version**: ruby 2.3.0p0 (2015-12-25 revision 53290) [x86_64-darwin15]

**Comment by marcelokanzaki** [comment]
I would be glad to help implement this if you guys think it's an interesting behavior.

**Comment by andela-oakinniranye** [comment]
I think you should post this on the [rails-core-mailing list](https://groups.google.com/forum/?fromgroups#!forum/rubyonrails-core). read somewhere that Feature Requests shouldn't be posted on Issues.

**Comment by maclover7** [comment]
Please use the mailing list for feature requests, where a wider community will be able to help you. We reserve the issues tracker for issues only.

**Comment by marcelokanzaki** [comment]
Sorry. Didn't know about the mailing list.

**Comment by chase439** [comment]
I thought it was a bug too. However, for me it turns out to be an issue with the database user's roles/privileges.
