### ISSUE TITLE
It seems ActiveSupport::CoreExt::Date#next_day/prev_day is ignored by Date in Rails

### ISSUE THREAD

**Issue by andela-oakinniranye** [rails/rails#25325]
### Steps to reproduce

While working on #25209, I tried to follow @matthewd's suggestion of using Date.current.next_day(:tuesday), which led me to a possible bug in Rails 5.
I would be interested to learn what I'm missing or if this is really a bug that should be fixed.
1. Open up a `rails console` session
2. Check `Date.current.next_day` from the repl session. This should give tomorrow
3. Check `Date.current.next_day(20)`, this should return 20 days from now
4. Check `Time.current.next_day`, this should return tomorrow at the current time
5. Check `Time.current.next_day(20)`, this should raise an exception `ArgumentError: wrong number of arguments (1 for 0)`
### Expected behavior

When the Numeric argument was passed to [`Date#next_day`](http://www.rubydoc.info/github/rails/rails/DateAndTime%2FCalculations%3Anext_day), a similar exception, as raised on Time should have been raised as well OR the `Time#next_day(20)` should return a similar result to [`Date#next_day(20)`](http://ruby-doc.org/stdlib-2.3.1/libdoc/date/rdoc/Date.html#method-i-next_day)
### Actual behavior

The `Date#next_day(20)` returned the result of 20 days in the future, while `Time#next_day(20)` raises an `ArgumentError`
### System configuration

Rails 5.1.0-alpha

**Ruby version**:
Ruby 2.3.1p112 (2016-04-26 revision 54768) [x86_64-linux-gnu]

`Date#next_day(20)` works because the `next_day` method is defined in `Ruby`, however the redefinition in the `DateAndTime::Calculations` API ought to have overridden this, but that isn't the case.
Also, if it had overridden it or not, that would have brought up some sorts of inconsistencies in usage, as Ruby developers would have expected the `Date#next_day` to work similarly to Ruby's and Rails developers would have expected `Time#next_day` to work similarly to the `Calculations API` and Ruby's `Date#next_day`, since they are all including methods from the `DateAndTime::Calculations` module

**Comment by andela-oakinniranye** [comment]
My bad. Using the `include` method makes the included `Module` a `super_class`. However, I'm wondering if this is desired method in Rails? As I could see some inconsistencies when a dev tries to `Date.current.next_day(20)` which would work, but `Time.current.next_day(20)` doesn't work. Also seeing all of this, does it still make sense going the approach of `Date.current.next_day(:tuesday)` as I think it could introduce more confusions than the problem it's trying to solve.

**Comment by kamipo** [comment]
Fixed by #30620.
