### ISSUE TITLE
[BUG] store_accessor attributes do not work with the new Attributes API

### ISSUE THREAD

**Issue by 3den** [rails/rails#25358]
### Steps to reproduce
```ruby
class Content < ApplicationRecord
   # given that you have a contents table with data: jsonb
   store_accessor :data, :version
   attribute :version, :integer
end

# there is no validation of type
content = Content.new(version: 'i an not an integer')

# it wont be serialized
content.attributes == { ... data: {version:  'i an not an integer'}, version: nil }
```
### Expected behavior
The new attributes should work with the properly with `store_accessor`, e.g.

```ruby
# this should be invalid or raise an error coz version is suppose to be an integer
content = Content.new(version: 'i an not an integer')

# content.attributes should return the correct serialized attributes
content = Content.new(version: 1)
content.attributes == { ... data: {version:  1}, version: 1 }
```

### Actual behavior

```ruby 
# there is no validation of type
content = Content.new(version: 'i an not an integer')

# it wont be serialized
content.attributes == { ... data: {version:  'i an not an integer'}, version: nil }
```
### System configuration
**Rails version**: "5.0.0.beta3"
**Ruby version**: 2.3.1

**Comment by maclover7** [comment]
Hmm, I think the reason why there's no type coercion/validation/whatever here is because `version=` goes through a special pipeline in `store_accessor`, and is literally just added to the `data` hash [here](https://github.com/rails/rails/blob/master/activerecord/lib/active_record/store.rb#L150). Not sure if there is a simple way to invoke the whole attributes API here, but could be something worth looking into.

cc @sgrif

**Comment by sgrif** [comment]
Yeah, this isn't intended to work.

**Comment by 3den** [comment]
@sgrif so what is the solution in this case?

**Comment by sgrif** [comment]
There is no solution. Typed store accessors are not a feature we support.

**Comment by 3den** [comment]
@sgrif can we reopen this issue as a feature request? I understand that the attributes api was not initially designed to work with `store_accessor` but many projects rely on nosql data stored in jsonb columns and it would be very useful to be able to wrap some of that data using the attributes api.

**Comment by rafaelfranca** [comment]
@3den https://github.com/byroot/activerecord-typedstore

**Comment by 3den** [comment]
@rafaelfranca I saw that project before, it was created before the attributes api existed, but it feels weird to have to use 2 different apis that do pretty much the same thing. Stored accessors can validate and save the same way as attributes from db columns, but they lack typing, which is something that the attributes API solves very well.

Would rails accept a PR that add this feature? If not why?

**Comment by rafaelfranca** [comment]
That gem now uses the attribute API for doing that job so they are not two different APIs.

We plan to add this feature to Rails itself some time in the future but I remember @sgrif commented, while working to get activerecord-typedstore using the attribute API, that he was having a hard time to get a good low level API to allow that.
