### ISSUE TITLE
[Action Mailer] Allow setting domain part of `Message-ID`

### ISSUE THREAD

**Issue by paulmenzel** [rails/rails#25359]
Currently, the header field `Message-ID` is generated without control.

```
Message-ID: <4b5d84f9dd6a5_7380800b81ac29578@void.loudthinking.com.mail>
```

The blog post [Tips & Tricks: Avoiding Gmail spam filtering when using Ruby on Rails](http://blog.mailgun.com/tips-tricks-avoiding-gmail-spam-filtering-when-using-ruby-on-rails-action-mailer/) cites [RFC 2822](https://tools.ietf.org/html/rfc2822#section-3.6.4) claiming that the format should be `<[uid][sendingdomain.com]>`.

> The message identifier (msg-id) is similar in syntax to an angle-addr construct without the internal CFWS.
> […]
> message-id      =       "Message-ID:" msg-id CRLF
> […]
> msg-id          =       [CFWS] "<" id-left "@" id-right ">" [CFWS]

So, as sometimes mail relays are used, it’d be useful, to be able to set the domain part of that “address” used in the field `Message-ID`.

**Comment by maclover7** [comment]
To me, this seems like a feature request. Normally we ask contributors to present these to Rails' community mailing list, where a wider group of people will be able to help you. We reserve the issues tracker for issues only.

**Comment by amingRo** [comment]
ignore this
- [ ] ignore this please

**Comment by paulmenzel** [comment]
@maclover7, sorry about that. I’ll try to find time to bring this up on the mailing list, as subscribing without a Google account is always a pain with lists hosted at Google Groups.

**Comment by maclover7** [comment]
👍 cool. Closing this as a "feature request" issue.
