### ISSUE TITLE
Bug in ActionView's distance_of_time_in_words when included outside of rails

### ISSUE THREAD

**Issue by wordswords** [rails/rails#25357]
### Steps to reproduce

Call DateHelper from outside rails like so:

--
require 'action_view'
include ActionView::Helpers::DateHelper
require 'date'

starttime = DateTime.new(2014, 6, 2,  6,  6,  6)
endtime = DateTime.new(2016, 6, 2,  6,  6,  6)
wordy_time = ActionView::Helpers::DateHelper.distance_of_time_in_words(starttime, endtime)

### Expected behavior
It should return '2 years' as per http://api.rubyonrails.org/classes/ActionView/Helpers/DateHelper.html

### Actual behavior
It throws an error in date_helper.rb:

david@David-Craddocks-MBP ~/w/bug-in-action-view> bundle exec ruby bug_in_action_view.rb
/Users/david/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/actionview-4.2.6/lib/action_view/helpers/date_helper.rb:111:in `block in distance_of_time_in_words': undefined   method `acts_like?' for 2014-06-02 07:06:06 +0100:Time (NoMethodError from /Users/david/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/activesupport-4.2.6/lib/active_support/core_ext/object/with_options.rb:67:in `call'
  from /Users/david/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/activesupport-4.2.6/lib/active_support/core_ext/object/with_options.rb:67:in `with_options'
   from /Users/david/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/actionview-4.2.6/lib/action_view/helpers/date_helper.rb:82:in `distance_of_time_in_words'
  from bug_in_action_view.rb:6:in `<main>'

### System configuration
OSX 10.11.15

**Rails version**:
This is in the 'actionview' 4.2.6 gem which is included outside of rails.

**Ruby version**:
2.2.3

###

It works without problem for dates up to 2 years difference.

The error then goes away for > 2 years difference when including this line:

require 'active_support/core_ext/object/acts_like' 

But I don't think I should need to do that manually?

**Comment by prathamesh-sonpatki** [comment]
Looking into this. Confirmed that this fails on master too.
