### ISSUE TITLE
Time values not being typecast for `where` and `find` queries on a date field

### ISSUE THREAD

**Issue by alextaylor000** [rails/rails#25354]
I noticed this issue when I was getting inconsistent behaviour from passing `find_or_create` a Time object as the value for a query against a date field. `create` type-casts this value before saving, but it seems `find` and `where` do not.

The problem can obviously be fixed by calling `#to_date` on the Time object beforehand, or using a Date object in the first place, but I believe the type-casting behaviour should be consistent to avoid confusion.

### Steps to reproduce
__[View Test Case](https://gist.github.com/alextaylor000/df334ecc3da577ce0aaf569a3fd0f894)__

```ruby
date_as_time = Time.new(2016,06,10,19,0,0,'-08:00')
Post.create(date: date_as_time)
# INSERT INTO "posts" ("date") VALUES (?)  [["date", Wed, 10 Jun 2016]]
```

### Expected behavior
```ruby
Post.where(date: date_as_time).count
# => 1

Post.find_by(date: date_as_time)
# => <Post id: 1, date: "2016-06-10">
```

### Actual behavior
```ruby
Post.where(date: date_as_time).count
# => 0

Post.find_by(date: date_as_time)
# => nil
```

### System configuration
**Rails version**: 5.0.0.rc1

**Ruby version**: 2.3.0p0

**Comment by tmertens** [comment]
I am also observing this behavior on rails 4.2.5.2
