### ISSUE TITLE
Could not find compatible versions for rack

### ISSUE THREAD

**Issue by eduardobarbiero** [rails/rails#25385]
### Expected behavior
Gem rack works correctly, via inline installation, however when it is via Gemfile, or the dependence of the rails 5.0.0.rc1 , it says not find the gem.

### Actual behavior
Bundler could not find compatible versions for gem "rack":
  In Gemfile:
    rails (~> 5.0.0.rc1) was resolved to 5.0.0.rc1, which depends on
      actioncable (= 5.0.0.rc1) was resolved to 5.0.0.rc1, which depends on
        actionpack (= 5.0.0.rc1) was resolved to 5.0.0.rc1, which depends on
          rack (~> 2.x)

Was removed **Gemfile.lock** and made ​​**bundle install** again , remembering what was done the **bundle update** before action .
### System configuration
**Rails version**: 5.0.0.rc1

**Ruby version**: 2.3.0 and 2.2.2

**Comment by sgrif** [comment]
Please make sure you're using the latest version of RubyGems and/or Bundler. This is not a bug in Rails.

**Comment by rafaelfranca** [comment]
Thank you for the report. This is not a Rails issue. Seems like your application could not resolve the right rack version, so it is something in your Gemfile.
