### ISSUE TITLE
ActiveRecord: HABTM resaves children even if autosave is false

### ISSUE THREAD

**Issue by dreyks** [rails/rails#25387]
### Steps to reproduce
```ruby
class Item < ApplicationRecord
  has_and_belongs_to_many :tags
end

class Tag < ApplicationRecord
end

item = Item.create(name: 'somename')
tag = Tag.create(text: 'sometxt')
item.tags << tag
```
### Expected behavior
`Tag#save` should only be called once when a tag is created

### Actual behavior
`Tag#save` is called the second time with all the callbacks defined when `item.tags << tag` executes

### System configuration
**Rails version**: 5.0.0.rc1

**Ruby version**: 2.3.1

the reason for this behavior is d849f42b4ecf687ed5350f5a2402fb795aa33aac which switched from saving only if the record (i.e. tag) is a `new_record?` to saving it anyways.

this causes some inconveniences when the class has some business logic attached to update process (updating timestamps, premoderation, caching etc) that fires each time the `item.tags << tag` is executed

I understand, that the change was made consciously, but this causes aforementioned issues

**Comment by maclover7** [comment]
This is documented, expected behavior, I don't think there's anything wrong here 😬

cc @sgrif

**Comment by dreyks** [comment]
I understand. But imagine the situation: a `Tag` has a `updated_at` field. It will be updated each time any user will add this tag to any `Item`

**Comment by sgrif** [comment]
Yes, this is the expected behavior. Unfortunately there is no way to turn this off. I'm in the process of reevaluating a lot of the related code so this may improve in 5.1. Either way, we don't do feature requests on the issue tracker.
