### ISSUE TITLE
ActionCable: Unable to find subscription with identifier...

### ISSUE THREAD

**Issue by tomekw** [rails/rails#25381]
Rails 5.0.0.rc1
Ruby 2.3.1 MRI + Puma

I've only one channel `ApiChannel`, the client (iOS app) connects to the back-end, receives the subscription confirmation and immediately sends a command. Sometimes the client is greeted with `RuntimeError` exception:
https://github.com/rails/rails/blob/a8df1bc345bf062e98bda64ef9638f65292c4b56/actioncable/lib/action_cable/connection/subscriptions.rb#L70

I've added some debugging statements to the code and from time to time the `subscriptions` Hash is indeed empty (the client issues `subscribe` command before), sometimes `identifiers` method returns empty Array for non-empty `subscriptions` (but it's just `.keys` on it).

I spent a lot of time debugging this and I'm out of ideas. Am I doing anything wrong here? Any help would be appreciated!

**Comment by maclover7** [comment]
Hmm, are you verifying that the subscription confirmation is received before you are sending any commands? Also, is there any reliable way to reproduce this? 😬

**Comment by tomekw** [comment]
@maclover7 the client sends command **immediately** after receiving `{"identifier"=>"{\"channel\":\"ApiChannell\"}", "type"=>"confirm_subscription"}` payload.

Also, the back-end propagates client status updated in `subscribed` callback to other connected clients (sort of home-made presence feature).

Reliable way? Hard to tell right now, looks like some kind of race condition... Maybe I would be able to prepare some minimal app to reproduce this, let me try!

**Comment by maclover7** [comment]
Yep, seems like a race condition to me as well 😞😬

**Comment by jbence** [comment]
Is there perhaps a spelling issue here? I notice that it is called ```ApiChannel``` in the initial description, but the reported payload comment has an extra lower-case L on the end.

Looking at the code, there are conditions in the ```add``` method that would result in an empty ```subscriptions``` hash, with an error message going to the log. Checking for that error message might shed some light.

Spelling would produce a consistent error, so this would have to be a situation where sometimes it is spelled correctly... that seems unlikely. But there is that path in the code for ```add``` that results in no update of the ```subscriptions``` hash. Perhaps that is the path taken before the failure occurs.

**Comment by tomekw** [comment]
@jbence I've made a typo in an issue description. Thanks! And no, there is no typo in the code.

Right now we've added some small sleep after subscription is confirmed and, as for now, the error didn't occur. Will post more findings tomorrow.

**Comment by frozenfoxx** [comment]
Has there been any update on this?  I'm experiencing a similar issue with the same error message.  The first time a client hits my Channel it doesn't complete hooking up to the subscription.  If that first client refreshes the page it completes it, and thereafter nobody else has a problem, but it seems to be some sort of race condition with the channel subscription.

**Comment by maclover7** [comment]
@frozenfoxx Since this is a race condition, it's by nature tough to solve. :( The first step towards fixing would be reliable reproduction steps -- would you be willing to take what you've experienced and try and create a "script/flow" of what one would have to do to experience the issue? From there, we can try and figure out where the issue is.

**Comment by frozenfoxx** [comment]
Thank you, I'll have a look to see what I can do to make it into a script.

**Comment by kesha-antonov** [comment]
Had this.
Started to work after restart of server.

**Comment by tomekw** [comment]
@frozenfoxx any update on this? I will dedicate the next few days to pinpoint the issue and reliably reproduce this.

**Comment by tomekw** [comment]
@frozenfoxx what's your setup? Are you on Puma and MRI?

**Comment by tomekw** [comment]
@maclover7 so here is the simple Rails application to demonstrate (and reproduce reliably) the issue:

https://github.com/tomekw/ac-issue

I will try to pinpoint this but it would be wonderful if you could take a look :)

**Comment by palkan** [comment]
Hey @tomekw!

Your reproduction script looks wrong: you should provide _action_ name within `data` object:

```ruby
ws.on :message do |m|
  if m.data == '{"identifier":"{\"channel\":\"ApiChannel\"}","type":"confirm_subscription"}'
    ws.send '{"command": "message","data": "{\"action\":\"foo\"}", "identifier":"{\"channel\":\"ApiChannel\"}"}'
  end
end
```

Does it solve your problem?

**Comment by tomekw** [comment]
@palkan that's not the case. For the simplicity's sake I've overridden `extract_action` method here https://github.com/tomekw/ac-issue/blob/master/app/channels/api_channel.rb#L19-L21

**Comment by palkan** [comment]
@tomekw oh, I see.

There is definitely a race condition problem: `stream_from` _sends_ confirmation without waiting for `subscribe` to finish, while you're still broadcasting messages.

PR attached https://github.com/rails/rails/pull/26547.

P.S. You can try`gem "rails", github: "palkan/rails", branch: "fix/actioncable-confirmation-race-condition"` in your reproduction app. I've just checked it, and it works)

**Comment by tomekw** [comment]
thx @palkan ! I will check this out today and will post my findings

**Comment by tomekw** [comment]
@palkan yes, I can confirm it fixes the issue! https://github.com/tomekw/ac-issue/pull/1

Well done! 👏 Thanks!

**Comment by RobertS92** [comment]
Am also getting the same issue can anybody tell me. How to resolve this issue.

**Comment by cassiompf** [comment]
It looks like the problem has reappeared. I'm getting the message even though I'm on the latest version.

![image](https://user-images.githubusercontent.com/20346767/203468381-3df8f654-0537-4bf6-b44c-04092d7dbb1a.png)

**Comment by Amnesthesia** [comment]
We're getting quite a lot of these errors again as well, on Ruby 3.2.2 and latest Rails

**Comment by Kaakati** [comment]
I'm encountering the same error using Ruby `3.3.6` and **tried** to use edge Rails `gem 'rails', github: "rails/rails", branch: "main"` same issue persisted.
