### ISSUE TITLE
Alternative sql for distinct.count query performs much better

### ISSUE THREAD

**Issue by mnort9** [rails/rails#25383]
Activerecord `distinct.count` performs very poorly on large tables. An alternative sql query performs significantly better (50x). 

I'm no sql expert, but is there any reason for not using the below sql for the underlying 'distinct.count` query?

### Steps to reproduce

```
Message.distinct.count(:foo_id)
```

### Expected behavior
Performance of alternative distinct count sql:
```
Message.count_by_sql('SELECT COUNT(*) FROM (SELECT DISTINCT foo_id FROM messages) AS foo_count')
=> (705.3ms)  SELECT COUNT(*) FROM (SELECT DISTINCT foo_id FROM messages) AS foo_count
```

### Actual behavior
Performance of AR distinct count:
```
Message.distinct.count(:foo_id)
=> (35338.7ms)  SELECT DISTINCT COUNT(DISTINCT "messages"."foo_id") FROM "messages"
```

### System configuration
**Rails version**: 4.2.6

**Ruby version**: 2.3.1

**Comment by sgrif** [comment]
We don't accept feature requests via the issue tracker. Feel free to open a thread on the mailing list if you feel this needs further discussion, or submit a PR

**Comment by sgrif** [comment]
This feature would be unlikely to be accepted though. It would require a lot of additional complexity for a fairly uncommon case, and you can already force this pretty easily with `Message.from(Message.select(:foo_id).distinct).count`

**Comment by mnort9** [comment]
Ok thanks, that works. I was unaware of the "activerecord" way of building the query
