### ISSUE TITLE
locale initializer is missing in rails 5(?)

### ISSUE THREAD

**Issue by murb** [rails/rails#25398]
### Steps to reproduce

In previous versions of rails there was an by default commented line in `config/application.rb` that made it very clear how the default English locale setting could be overridden for any app:

    # config.i18n.default_locale = :de

The new `application.rb` in config reads that "application configuration should go into files in config/initializers". But nothing in the bare new Rails app tries to establish a default.

### Expected behavior

I would expect a default locale.rb in the initializers directory, probably fully commented with content along the lines of the [snippet in the latest i18n docs](http://edgeguides.rubyonrails.org/i18n.html), bit adjusted to accommodate for the follow up error that might occur for those unaware of the `enforce_available_locales` setting.

    # Where the I18n library should search for translation files
    # I18n.load_path += Dir[Rails.root.join('lib', 'locale', '*.{rb,yml}')]
    # Whether or not to accept only available locales
    # I18n.config.enforce_available_locales = true
    # List of available locales
    # I18n.config.available_locales = [:en]
    
    # Set default locale to something other than :en (make sure that you either accept all locale values or do not enforce available locales)
    # I18n.default_locale = :pt

### Actual behavior

It is now harder to figure out where to place locale settings compared to earlier versions of Rails.

### System configuration

**Rails version**: 5.0.0rc1

**Comment by maclover7** [comment]
Hmm, thoughts @dhh? This is a "breaking change" in 5.0. You removed these commented out configuration options @ 28dcadc0140dfdebe87d5e691fd709c0a9ae0bae 😬

**Comment by dhh** [comment]
I don't consider removing comments to be a "breaking change". We should solve this in a guide on internationalization instead.

**Comment by dhh** [comment]
Actually, seems like we already have a section covering this: http://guides.rubyonrails.org/i18n.html#optional-custom-i18n-configuration-setup

**Comment by dhh** [comment]
We just need to cleanup the documentation around that which talks about the stuff in application.rb.

**Comment by murb** [comment]
Hmm... I change the default for nearly every project I start... (mostly targeting a Dutch audience), but I guess that's just n=1.

**Comment by askrynnikov** [comment]
must be removed `The default config/application.rb file has instructions on how to add locales from another directory and how to set a different default locale. ...` from http://guides.rubyonrails.org/i18n.html#optional-custom-i18n-configuration-setup

**Comment by utilum** [comment]
@askrynnikov this was fixed in 983fa3b29f8eb0846f1b5cb6b8aea5f07dfb5ecb, may be worth porting.

**Comment by prathamesh-sonpatki** [comment]
@utilum Thanks, I have [requested for the backport](https://github.com/rails/rails/commit/983fa3b29f8eb0846f1b5cb6b8aea5f07dfb5ecb#commitcomment-20399462)
