### ISSUE TITLE
why the class of model's datetime field is Time class, not ActiveSupport::TimeWithZone < Object when use ActiveRecord in sinatra?

### ISSUE THREAD

**Issue by villins** [rails/rails#25400]
why the class of model's datetime field is Time class, not ActiveSupport::TimeWithZone < Object when use ActiveRecord in sinatra?

```
 pry(#<Sinatra::Application>)> Show.last.show_time.class
D, [2016-06-14T18:34:16.605042 #4094] DEBUG -- :   Show Load (0.7ms)  SELECT  `shows`.* FROM `shows`  ORDER BY `shows`.`id` DESC LIMIT 1
=> Time
```
Wheather this is ActiveRecord's default, and there is a configuration where ActiveSupport::TimeWithZone is automatically returned instead of Time?

thx.

**Comment by maclover7** [comment]
I *think* this is expected behavior, does anything in the docs say otherwise? 😬

cc @sgrif

**Comment by sgrif** [comment]
This is the expected behavior.

**Comment by villins** [comment]
@sgrif Can I make it like Rails ActiveSupport::TimeWithZone back in Sinatra?  Docs?
