### ISSUE TITLE
Validates uniqueness with case_sensitive: false

### ISSUE THREAD

**Issue by Friend-LGA** [rails/rails#25405]
* ```Mac OS X El Capitan```
* ```Ruby 2.3.1```
* ```Rails 5.0.0.rc1```
* ```pg 0.18.4``` or ```pg 0.19.pre```

I have model ```IpAddress```
```ruby
class IpAddress < ApplicationRecord {
     :id => :integer,
  :value => :inet
}

class IpAddress < ApplicationRecord
  validates :value, presence: true, uniqueness: {case_sensitive: false}
end
```
When I try to update some ip_address object, it validates value for uniqueness with sql query:

```sql
IpAddress Exists (19.6ms)  SELECT  1 AS one FROM "ip_addresses" WHERE LOWER("ip_addresses"."value") = LOWER($1) AND ("ip_addresses"."id" != $2) LIMIT $3  [["value", "::1/128"], ["id", 1], ["LIMIT", 1]]
```
But why it use LOWER function? case_sensitive is set to false, and this function is not needed to be used here.

**Comment by rafaelfranca** [comment]
Because to be not case sensitve active record have to make both size of the comparation have the same case otherwise the comparation will be case sensitive.

**Comment by Friend-LGA** [comment]
Sorry, it's my stupid fault
