### ISSUE TITLE
Can't close websocket connection

### ISSUE THREAD

**Issue by callancarr** [rails/rails#25412]
I can't seem to find any documentation on how to close a websocket connection from the client side.

I really need help with this, if anyone can help me it'd be greatly appriciated.

This is my client side code:

    # Run if we're in a room: controller_id = "room show"
    if controller_id == "rooms_show"

      # Define the room
      App.room = App.cable.subscriptions.create { channel: "RoomChannel", chatroom_id: chatroom_params},

        # Called when the subscription is ready for use on the server
        connected: ->

          # Broadcast we are online
          App.room.speak(username+" is now online", true)

        # Called when the subscription has been terminated by the server
        disconnected: ->

        # Called when data is recieved
        received: (data) ->

          # Hide Typing Message after interval
          hide_typing_notification = () ->
            $('#typing_field').html('');

          # Clear notification bar
          $('#typing_field').html('');

          # Append data to page
          if data.message.typing != true

            # Append message to conversation
            $('#messages').append(data.message.content+'<br>')

            # Scroll
            $('#messages').animate({ scrollTop:  $('#messages').get(0).scrollHeight}, "fast");

            # Recieved Message from Peer
            if data.message.username != username
              # Play Audio
              audio = new Audio('/sfx/chat_sound.mp3')
              audio.play()

            # Flash - Notification
            notification = () ->

              # Only show if user is not looking at the window
              if window_focus != true
                document.title = data.message.username+' sent you a message';
                setTimeout(flash, 4000)

            # Flash - Original
            flash = () ->
              document.title = 'Emerald';
              setTimeout(notification, 4000)

          # Recieved Message from Peer
          if data.message.username != username

            setTimeout(notification, 100)

            # Detect Typing
            if data.message.typing == true
              $('#typing_field').html(data.message.username+' is typing...');

              # Hide Typing after Timeout
              setTimeout(hide_typing_notification, 7000)

        # Check when peer is typing
        typing: (msg) ->
          # User is typing...
          @perform 'typing', {message: msg, user_name: username, chatroom_id: chatroom_params}

        # Send message to broadcast to recievers in the chatroom
        speak: (msg, is_system_notification) ->

          # Style message if notification
          if is_system_notification
            msg = "|s|"+msg+"|-s|"
            message_header = ""

          # Style message header
          else
            message_header = "<s5>"+username+" says:</s5><br>"

          @perform 'speak', {
                              header: message_header,
                              message: msg,
                              user_name: username,
                              sender_id: senderid,
                              chatroom_id: chatroom_params,
                              save: save_messages,
                              notification: is_system_notification
                            }

          # Send message
          $(document).on 'keypress', '[data-behavior~=room_speaker]', (event) ->

            # Detect Typing - To save memory, only send if has not been sent recently
            if event.keyCode != 13
              App.room.typing()

            # If Enter is pressed and the text field is not blank
            if event.keyCode is 13 && event.target.value.length > 0 && !event.shiftKey
              # Send Message
              App.room.speak(event.target.value)
              # Set text field to empty
              event.target.value = ''
              # Prevent form submission
              event.preventDefault()

**Comment by vipulnsward** [comment]
@callancarr I believe you are looking for https://github.com/vipulnsward/rails/blob/cbd15da0274316bae64caae54880fee87853f480/actioncable/app/assets/javascripts/action_cable/consumer.coffee#L22-L22 ?

**Comment by callancarr** [comment]
@vipulnsward I think I may have worded my question wrongly.

I am trying to unsubscribe from all channels.

Essentially I have multiple Action Cable channels in chat rooms. I wanted to do AJAX conversation switching rather than reloading the page to open a new chat. So basically i need a way to clean the cable (remove subscribers and reset the connection) each time I switch.

I couldn't find out how to in the docs. Any help would be greatly appriciated.

**Comment by maclover7** [comment]
@callancarr You'd have to loop through all of your subscriptions, and unsubscribe from them all that way.

**Comment by callancarr** [comment]
@maclover7  Is there any code examples of how to do this? I can't find any online

**Comment by maclover7** [comment]
I don't think this is an explicitly documented practice -- you'd have to loop through `App.cable.subscriptions.subscriptions`, and then call `App.cable.subscriptions.remove(subscription)`, though this is beginning to reach into private API a little bit 😬

Going to close out this issue, since this seems like more of a question than a bug report You can use the mailing list or StackOverflow for questions/help, where a wider community will be able to help you. We reserve the issues tracker for issues only. 😬

**Comment by padi** [comment]
@maclover7 ran into this issue as well since I'm using turbolinks together with actioncable. "Orphaned" subscriptions can pile up after a few clicks into turbolinks pages that trigger `App.cable.subscriptions.create`.

I did end up looking into https://github.com/rails/rails/blob/master/actioncable/app/assets/javascripts/action_cable/subscriptions.coffee but I'm afraid the private API might change in the future. Not sure if I'm doing something that's so out of the ordinary but the idea is a subscription is created on `turbolinks:load`:

```coffeescript
$(document).on 'turbolinks:load', ->
  if (certainElement) {
     App.something = App.cable.subscriptions.create "SomethingChannel" -> 
  }
```

Am I missing technique here or is it, as of this writing, a limitation of ActionCable?
