### ISSUE TITLE
sanitize helper doesn't work with custom styles in tag style

### ISSUE THREAD

**Issue by iggant** [rails/rails#25419]
sanitize  doesn't process tags style correctlly if it contain custom styles (for instance: all -webkit- prefix)

```
body = "<a href=\"https://someurl_doesnt_matter/el\" style=\"display: inline-block;text-decoration: none;-webkit-text-size-adjust: none;text-align: center;background-color: #3AAEE0;color: #ffffff\" target=\"_blank\">"

ActionController::Base.helpers.sanitize(body, :tags => ["a"], :attributes => %w(href style target) )
```
return 

> ```<a href=\"https://someurl_doesnt_matter/el\" style target=\"_blank\"></a>```

while
```
body = "<a href=\"https://someurl_doesnt_matter/el\" style=\"display: inline-block;text-decoration: none;text-align: center;background-color: #3AAEE0;color: #ffffff\" target=\"_blank\">"

ActionController::Base.helpers.sanitize(body, :tags => ["a"], :attributes => %w(href style target) )
```
works fine 

> ```<a href=\"https://someurl_doesnt_matter/el\" style=\"display: inline-block; text-decoration: none; text-align: center; background-color: #3AAEE0; color: #ffffff;\" target=\"_blank\"></a>```

Ruby: 4.2.6

**Comment by rafaelfranca** [comment]
The sanitization is made by Loofah. Could you please open this bug there https://github.com/flavorjones/loofah?
