### ISSUE TITLE
merge clobbers query conditions (ActiveRecord::SpawnMethods)

### ISSUE THREAD

**Issue by z5h** [rails/rails#25417]
### Steps to reproduce
```
User.where(id: [1,2,3]).merge(User.where(id: [2,3,4])).to_sql
```

### Expected behavior
```
User.where(id: [1,2,3]).merge(User.where(id: [2,3,4])).to_sql
```
should yield  
```
"SELECT `users`.* FROM `users`  WHERE `users`.`id` IN (1, 2, 3) AND `users`.`id` IN (2, 3, 4)"
```

### Actual behavior
Returns   
```
"SELECT `users`.* FROM `users`  WHERE `users`.`id` IN (2, 3, 4)"
```

### System configuration
**Rails version**:
Rails 4.1.14.2

**Ruby version**:
ruby 2.1.2p95

**Comment by rafaelfranca** [comment]
Yes, this is the expected behavior. Merge overrides the same conditions to make possible to user override `default_scopes` for example. Like Hash#merge is you have the same condition only the last one will be used.
