### ISSUE TITLE
Cannot find certain keys in errors - Rails 5.0.0.rc1

### ISSUE THREAD

**Issue by Veske** [rails/rails#25410]
### Steps to reproduce

Make a model with length validations. For instance: `validates :name, length: { in: 2..25 }`
Test against this model either in a test or console by inserting a too long name that is over 25 characters
Call `.errors.added?(:name, :too_long)` method on the validated object

### Expected behavior
The method should return `true`

### Actual behavior
It returns `false`

### System configuration
**Rails version**: 5.0.0.rc1

**Ruby version**: 2.3.0

This happens also for too_short and maybe for some others too.

In the screenshot you can see that the data is actually there but the `.added?` method is unable to see it. Also worth noting that the other key called `:invalid `is accessible.
![screenshot from 2016-06-16 00-57-38](https://cloud.githubusercontent.com/assets/5602603/16098757/5d2a5884-335d-11e6-9aa3-b8ee54ac2b06.png)

**Comment by rafaelfranca** [comment]
Could you create a reproduction script with this template https://github.com/rails/rails/blob/master/guides/bug_report_templates/active_record_master.rb?

**Comment by Veske** [comment]
This template does not seem to work with postgresql? Or am I doing something wrong

**Comment by Veske** [comment]
`begin
  require 'bundler/inline'
rescue LoadError => e
  $stderr.puts 'Bundler version 1.10 or later is required. Please update your Bundler'
  raise e
end

gemfile(true) do
  source 'https://rubygems.org'
  gem 'rails', '>= 5.0.0.rc1'
  gem 'sqlite3'
end

require 'active_record'
require 'minitest/autorun'
require 'logger'

# This connection will do for database-independent bug reports.
ActiveRecord::Base.establish_connection(adapter: 'sqlite3', database: ':memory:')
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :posts, force: true do |t|
	t.string   "name", default: "", null: false
  end

  create_table :comments, force: true do |t|
    t.integer :post_id
  end
end

class Post < ActiveRecord::Base
  has_many :comments
  validates :name, 
		length: { in: 2..25 }
end

class Comment < ActiveRecord::Base
  belongs_to :post
end

class BugTest < Minitest::Test
  def test_association_stuff
    assert Post.create(name: '123456789123456789123456789123456789').errors.added?(:name, :too_long)
  end
end`

**Comment by tejasbubane** [comment]
Works with the actual error message as string:

```
[12] pry(#<BugTest>)> post.errors
=> #<ActiveModel::Errors:0x007fe03b282ff8
 @base=#<Post:0x007fe03b2d3430 id: nil, name: "123456789123456789123456789123456789">,
 @details={:name=>[{:error=>:too_long, :count=>25}]},
 @messages={:name=>["is too long (maximum is 25 characters)"]}>

[13] pry(#<BugTest>)> post.errors.added?(:name, :too_long)
=> false

[14] pry(#<BugTest>)> post.errors.added?(:name, "is too long (maximum is 25 characters)")
=> true
```

The docs have symbols: http://api.rubyonrails.org/classes/ActiveModel/Errors.html#method-i-added-3F

**Comment by maclover7** [comment]
Opened up #25415 to attempt to fix this 😬

**Comment by morgoth** [comment]
@maclover7 The problem here is that there should be passed all required options for generating proper message - in this case `erros.added?(:name, :too_long, count: 25)`

**Comment by morgoth** [comment]
As discussed on https://github.com/rails/rails/pull/25415 I think it can be closed now.
To properly check for added error, you need to specify all arguments that are building given message (in this example `count: 25`)

**Comment by Veske** [comment]
Could use some ducumentation update then. If this is indeed the intended workflow to use this method, then it is a fairly cryptic one.

**Comment by rafaelfranca** [comment]
:+1: for documentation. Mind to open a PR?
