### ISSUE TITLE
ActiveModel::Errors#add not behaving as expected with symbol message

### ISSUE THREAD

**Issue by tejasbubane** [rails/rails#25413]
Came across this when I was debugging #25410 

### Steps to reproduce

Here is the reproduction script:

```ruby
begin
  require 'bundler/inline'
rescue LoadError => e
  $stderr.puts 'Bundler version 1.10 or later is required. Please update your Bundler'
  raise e
end

gemfile(true) do
  source 'https://rubygems.org'
  gem 'rails', '>= 5.0.0.rc1'
  gem 'sqlite3'
  gem 'pry'
end

require 'active_record'
require 'minitest/autorun'
require 'logger'
require 'pry'

# This connection will do for database-independent bug reports.
ActiveRecord::Base.establish_connection(adapter: 'sqlite3', database: ':memory:')
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :posts, force: true do |t|
    t.string   "name", default: "", null: false
  end
end

class Post < ActiveRecord::Base
  validates :name, length: { in: 2..5 }
end

class BugTest < Minitest::Test
  def test_post # Passing test
    post = Post.new(name: 'example')
    post.valid?

    assert_match /too long/, post.errors[:name][0]
  end

  def test_comment # Failing test
    post = Post.new(name: 'example')
    post.errors.add(:name, :too_long) # add error instead of validating

    assert_match /too_long/, post.errors[:name][0]
  end
end
```

### Expected behavior
`post.errors[:name]` should be `["is too long (maximum is 5 characters)"]`

### Actual behavior
`post.errors[:name]` is `[{:one=>"is too long (maximum is 1 character)", :other=>"is too long (maximum is %{count} characters)"}]`

### System configuration
**Rails version**: `5.0.0.rc1`

**Ruby version**: `2.3.1`

**Comment by tejasbubane** [comment]
Same behaviour can be seen on master (`5.1.0.alpha` at `master@7980b31`)

**Comment by morgoth** [comment]
@tejasbubane It behaves in the same way on 4.2 - you need to specify `count` option, like:
`errors.add(:name, :too_long, count: 1)`
I think it was changed in https://github.com/rails/rails/commit/6604ce63e837efb4c4ddf9f42392e9b0440e3c7e

**Comment by tejasbubane** [comment]
@morgoth Ok. Works as expected with `post.errors.add(:name, :too_long, count: 5)`. Did not notice the `options` in [the doc](http://api.rubyonrails.org/classes/ActiveModel/Errors.html#method-i-add). Closing.
