### ISSUE TITLE
enum integer isnt working properly

### ISSUE THREAD

**Issue by joaoamaral** [rails/rails#25423]
### Steps to reproduce

Have a field in a database that has enumerate with type integer on a Ticket object, example:

`t.integer   "priority"``

on view: 

```
.field
= f.select :priority, Ticket.priorities.map { |key, value| [key, value] }
```

on Model
`
enum priority: { High: 0, Middle: 1, Low:2}`
### Expected behavior

It should insert the value as an integer on model
It works in previous versions of rails
### Actual behavior

It gets rejected when new/inserted saying
ArgumentError in TicketsController
'0' is not a valid status
or
'1' is not a valid status
or
'2' is not a valid status
### System configuration

**Rails version**: 5.0.0.rc1

**Ruby version**: 2.3.1p112

Thank you.

**Comment by sevenseacat** [comment]
`t.string "priority"` that's a string, not an integer

**Comment by joaoamaral** [comment]
Sorry my mistake when copying it. I correct the issue text but it is still valid. 
That is what I wanted to write.
Meaning the issue happens with 
`t.integer "priority"`

**Comment by maclover7** [comment]
Not able to reproduce this on master with [this reproduction script](https://gist.github.com/maclover7/33959535084c82ea0a0c745935c7af0e). 
Can you create an executable test script using one of the templates [here](https://github.com/rails/rails/tree/master/guides/bug_report_templates), that would demonstrate the problem you are seeing?

**Comment by maclover7** [comment]
@rrrcompagnoni not sure what you mean by that -- feel free to duplicate my gist, and then move around some thing to make it break :)

**Comment by rrrcompagnoni** [comment]
@maclover7 I had the same problem some weeks ago and it happened when I was trying to create a resource, the form was sending the enum field as a string not an integer, so I had to convert the param before saving my resource.

**Comment by alediaferia** [comment]
@maclover7 I think [this](https://gist.github.com/alediaferia/9076a677c367254668051b6a60f74a5c) gist reproduces what OP means

**Comment by maclover7** [comment]
Thanks @alediaferia for the reproduction script -- I thought the issue was in the template, not in the POST request. Adding the `needs feedback` label, not sure what the best course is here, since we'd have to call ` to_i` somewhere here...

**Comment by alediaferia** [comment]
@maclover7 If what's claimed by the OP is true a `to_i` shouldn't be necessary as I don't see any in the Rails 4.1 implementation of activerecord: https://github.com/rails/rails/blob/4-1-stable/activerecord/lib/active_record/enum.rb

**DISCLAIMER** I just had a quick glance at it, may have missed something :)

**Comment by alediaferia** [comment]
So, I tried replacing `enum.rb` implementation with the one from Rails 4.1 but the issue persist. So I guess the expected behaviour has to be confirmed or the issue resides somewhere else.

**Comment by joaoamaral** [comment]
It is exactly the problem pointed out by @alediaferia script
I think it is something related with active record because if you declare the same
` enum priority: { High: 0, Middle: 1, Low:2}`
in the model when you check the database (in Rails console) in versions previous to 5 you get the correct type

`priority :integer`

but 5.0.0rc1 you get the type empty.

`priority : `

Thank you so much for checking this everyone.

**Comment by alediaferia** [comment]
@joaoamaral what do you mean by
> when you check the database (in Rails console)

What command you use to "_check the database_"?

**Comment by maclover7** [comment]
I think the issue here is that the parameters coming in from the HTTP request have the priority number as a string, while the enum definition has the value as an integer 😬

cc @sgrif

**Comment by rrrcompagnoni** [comment]
@maclover7 It's I was trying to say. 😅

**Comment by joaoamaral** [comment]
@alediaferia I used Rails console (rails c) to check it

With the following versions I get the following information which is different with the Rails version and I though it could be the culprit (or at least be related)

ruby -v
ruby 2.3.1p112 (2016-04-26 revision 54768) [x86_64-darwin15]

rails -v
Rails 5.0.0.rc1

irb(main):012:0> Ticket
=> Ticket(id: integer, priority: , created_at: datetime, updated_at: datetime)



ruby -v                                        
ruby 2.3.1p112 (2016-04-26 revision 54768) [x86_64-darwin15]

rails -v
Rails 4.2.6

irb(main):004:0> Ticket
=> Ticket(id: integer, priority: integer, created_at: datetime, updated_at: datetime)

**Comment by kamipo** [comment]
Fixed by #25506?

**Comment by eminkel** [comment]
Having this issue in a Rails 5.0.1 app with enums. Any progress since July?

**Comment by kaspth** [comment]
I've backported #25506 to 5-0-stable, so this should be fixed in 5.0.2 :)

**Comment by wellingtondev** [comment]
Hey guys

I'm having this problem using Rails 5.2.2

**Comment by AndreiMotinga** [comment]
Is this problem there because my enums are integers? 
I never noticed that enum options aren't supposed to be integers.

**Comment by ramzieus** [comment]
depends on my small experiens with enums on rails the solution for your issue is 
```
.field
= f.select :priority, Ticket.priorities.keys.map { |priority| [priority, priority] }
```
we need to send the value (string) not the integer

I'm using rails 7.1
@joaoamaral  @AndreiMotinga  @starwels @kaspth
