### ISSUE TITLE
ActionDispatch::Journey::Router#visualizer don't work for me

### ISSUE THREAD

**Issue by JadenTeng** [rails/rails#25422]
env: `/Users/name/.rvm/gems/ruby-2.2.0@blog/gems/rails-4.2.6`

I want output the router DFA struct in my rails app.
So I add code in simple controller

```
class HomeController < ApplicationController
  def index
    File.write("routes.html", Rails.application.routes.router.visualizer)
  end
end
```

But It give me:
```
Errno::ENOENT (No such file or directory - dot):
  app/controllers/home_controller.rb:3:in `index'
```

How can I make the code work? Need require some gems?
Thank you very much.

**Comment by rafaelfranca** [comment]
This method is not part of the public API and we don't recommend users to use it.

This error is because you are missing the `dot` executable that is part of the graphviz package.

**Comment by JadenTeng** [comment]
@rafaelfranca Thanks for your quickly reply.
But it's don't resolve my problem.

> This method is not part of the public API
It's public method and may don't work. why don't just remove or fix it?

**Comment by rafaelfranca** [comment]
It is a public method to internal consumption of the framework developers. Yes, we can remove it, this is exactly why I don't recommend using it.

**Comment by JadenTeng** [comment]
Thanks for your patience. Sorry for my noise.

> that is part of the graphviz package

I did't understand your reply before. I run command `brew install graphviz` resolve my problem.

> Yes, we can remove it, this is exactly why I don't recommend using it.

Please don't remove the method. It's so interesting. Thank you again.
![image](https://cloud.githubusercontent.com/assets/10040765/16139997/7dcdcf4e-347f-11e6-9ae2-27a1642a047e.png)
