### ISSUE TITLE
ActiveRecord - no exception is thrown when invalid UUID value is supplied on update!, update_attribute, etc.

### ISSUE THREAD

**Issue by Nowaker** [rails/rails#25429]
### Steps to reproduce

1. Use PostgreSQL.
1. Create column of UUID type. `add_column :hypervisor, :blah, :uuid`
2. Try updating `:blah` column with invalid UUID value, e.g. `abcd`
3. No error is thrown. Instead, NULL value is persisted in the database.

### Actual behavior

```
2.3.1 :004 > Hypervisor.last.update! blah: SecureRandom.uuid
 => true 
2.3.1 :005 > Hypervisor.last.blah
 => "3018c132-14ae-4e0a-9e0b-584e31484a8e" 
2.3.1 :006 > Hypervisor.last.update! blah: '1234'
 => true 
2.3.1 :007 > Hypervisor.last.blah
 => nil
```

### Expected behavior

Exception should be thrown.

PostgreSQL console itself throws an error so there's something wrong on ActiveRecord side:

```
virtkick_webapp_hosting_development=> update hypervisors set "blah" = 1234 where id = 46;
ERROR:  column "blah" is of type uuid but expression is of type integer
LINE 1: update hypervisors set "blah" = 1234 where id = 46;
```

### System configuration

- **Rails version**: 4.2.5.1
- **Ruby version**: 2.2.2, 2.3.1

**Comment by marekkirejczyk** [comment]
Here is [executable test case](https://gist.github.com/marekkirejczyk/5a5d295cbb0d82a1daf57879418b379f).

Not sure which is desirable behaviour thou. Let examine similar case, update integer field with integer value i.e. `update!(some_integer: 'some string')  `. Value of 0 will be assigned to `some_integer`.

Adding `validates :blah, presence: true` will help not to assign nil to an uuid filed by accident.

**Comment by maclover7** [comment]
Agree with @marekkirejczyk, I think you'd have to add some validations to the model to prevent this from happening 😬

**Comment by Nowaker** [comment]
If there's UNIQUE index on a table and one tries to add a duplicate to the table, some PG::Error will be thrown. Why isn't it a case here? We can clearly see the query fails when executed in psql. Getting an exception when underlying layer fails (SQL level) is a must-have IMO.

**Comment by marekkirejczyk** [comment]
I think query actually succeeds and that is why no error is propagated to the framework, i.e. following SQL script will execute properly:

```
create table tmp (uni uuid);
insert into tmp (uni) values (null);
insert into tmp (uni) values (null);
select * from tmp;
```

and will return:
```
 uni 
-----
 
 
(2 rows)
```

So if it succeeds in SQL why not in Rails?

If you however add not null constraint to your column (i.e. `alter table tmp alter uni set not null;`), it will behave as you expect. That is: `insert into tmp (uni) values (null);` will fail: `DETAIL:  Failing row contains (null).`

**Comment by Nowaker** [comment]
```
virtkick_webapp_hosting_development=> update hypervisors set "blah" = 1234 where id = 46;
ERROR:  column "blah" is of type uuid but expression is of type integer
LINE 1: update hypervisors set "blah" = 1234 where id = 46;
```

**Comment by marekkirejczyk** [comment]
How did you get this error? 
I think it is not being triggered in scenario you showed, the reason for this is that ActiveRecord does the conversion from Integer to nil before sending query. As you can see in [executable test case](https://gist.github.com/marekkirejczyk/5a5d295cbb0d82a1daf57879418b379f) actual query is:
`UPDATE "hypervisors" SET "blah" = $1 WHERE "hypervisors"."id" = $2  [["blah", nil], ["id", 1]]`

**Comment by Nowaker** [comment]
That's psql. Frankly, I didn't know Rails would perform meaningless conversions. Feels like JavaScript casting. ;-) Do you know if it's possible to disable that somehow?

**Comment by matthewd** [comment]
Per https://github.com/rails/rails/issues/25429#issuecomment-226941339, this is consistent with the behaviour for integers.
