### ISSUE TITLE
Enum in concern, concern in abstract class, scopes of enum not working

### ISSUE THREAD

**Issue by jonasheinrich** [rails/rails#25442]
### Steps to reproduce

See here for an example Rails app: https://github.com/jonasheinrich/enum-abstract
- create a concern that adds `enum`
- include that concern in an abstract class
- let a class inherit from that abstract class
- try to get a scope defined by `enum`
### Expected behavior

The scope should work.
### Actual behavior

The scope does not work because `table_name` is not found.
### Explanation (as I understand it)

Scopes are evualated when defined and that's why they get evaluated when `self` is equal to the abstract class. Normally, a workaround I've seen is to explicitly overwrite the scopes via class methods. With `ActiveSupport::Concern` this not possible anymore because the methods from the `included` block gets evaluated last.
### Possible solutions I can see

Unfortunately, all solutions I found are kind of ugly:
- Evaluate scopes later (would be the cleanest IMHO, but probably not possible).
- Option for `enum` to not define scopes.
- Option for `enum` to define `table_name`.
- Define the order of execution inside the concern.

If the preferred solution is in my abilities I'd be glad to implement it. :) 
### Workarounds

Currently, I include the concern in the child class.
### System configuration

**Rails version**: 4.2.6

**Ruby version**: 2.2.4

**Comment by rafaelfranca** [comment]
Does it work in Rails 5?

**Comment by jonasheinrich** [comment]
@rafaelfranca Yes, indeed it works with `v5.0.0.rc1`. So probably this won't be fixed in `4.2`?

Just out of curiosity: Do you know why this works in Rails 5?

**Comment by jonasheinrich** [comment]
I will push the new Gemfile to the repo.
