### ISSUE TITLE
Change need to rails documentation

### ISSUE THREAD

**Issue by sunnyraz** [rails/rails#25445]
### Steps to reproduce

(Please Follow this link to know the problem and check view code of listing all articles [available
here](http://guides.rubyonrails.org/getting_started.html#listing-all-articles))

### Expected behavior
change the code on line no. 7 @articles to @article .It will helpful to beginners

### System configuration
**Rails 4.2.1**:

**ruby 2.0.0**:

**Comment by sevenseacat** [comment]
Your description isn't really clear about what needs to be changed or why. The code in the section you linked to looks fine.

**Comment by sunnyraz** [comment]
`<h1>Listing Articles</h1>
<table>
	<tr>
		<th>Title</th>
		<th>Text</th>
	</tr>
	<% @articles.each do |article| %> //change plural "articles" to "article" .

	<tr>
		<td>
			<td><%= article.title %></td>
			<td><%= article.text %></td>
	</tr>
 <% end %>
</table>`

**Comment by guilleiguaran** [comment]
I've verified that the linked code is fine so I'm closing this.
