### ISSUE TITLE
cache_key not include timestamp and size when using offset

### ISSUE THREAD

**Issue by madmax** [rails/rails#25454]
### Steps to reproduce

When we use offset in query cache_key is not calculated correctly
Here is gist
https://gist.github.com/madmax/e796a740386d1b25516449b5d19b4fd8

without offset: posts/query-322bc402789ebcd22fbdb7b4ea9dec2f-10-20160621080044729910
with offset: posts/query-88260ab1dd3cd2484198b0102cbbc25f-0
### Expected behavior

cache_key should include size and timestamp even if we use offset in other case cache will not expire.
### Actual behavior

Currenlty because we are doing 
SELECT  COUNT(*) AS "size", MAX("posts"."updated_at") AS timestamp FROM "posts" LIMIT ? OFFSET ?  [["LIMIT", 5], ["OFFSET", 5]]

There is no record returned and cache key don't include size + timestamp information. 
### System configuration

**Rails version**: master (5.0 also affected)

**Ruby version**: 2.3.0

**Comment by maclover7** [comment]
Can reproduce this on master. Slightly modified your reproduction script to include `assert_match`es for the current year (modified script can be found [here](https://gist.github.com/maclover7/fb7255a5cd4f07ed3934b6a45c094c4e)). Can confirm that [this query](https://github.com/rails/rails/blob/master/activerecord/lib/active_record/collection_cache_key.rb#L19) is this issue, when dealing with the `offset` query.

**Comment by madmax** [comment]
Can somone look at my attempt to fix issue? I use subquery because calculating max updated_at column when you db can have lots of rows can be slow and if we only want for example 10 rows?

Also using max updated_at without limit and order can expire cache lot often that is needed.

**Comment by YoniAmir** [comment]
@madmax Until the PR is merged, you can workaround in Rails like this-
```Movie.limit(10).unscope(:limit).unscope(:offset).cache_key```

**Comment by alekseyl** [comment]
> Can somone look at my attempt to fix issue? I use subquery because calculating max updated_at column when table have lots of rows can be slow and if we only want for example 10 rows?

Your code will break cache_key. 

Imagine case when you working with ordered collection, and touching ordering column on some of your middle pages. It means that you can get new subcollection for same key, if MAX(updated_at) on this page didn't changed.
  
I also think unscoped and subquery, but this code can't deal with subcollections properly.

**Comment by alekseyl** [comment]
Accidentally open this issue again https://github.com/rails/rails/issues/26330
But if you are looking for perfomant solution for cache_key and using PG you can take it from there.

**Comment by kamipo** [comment]
Fixed in #28776.
