### ISSUE TITLE
ActiveJob undefined method `job_id=` 

### ISSUE THREAD

**Issue by rjrobinson** [rails/rails#25459]
### Steps to reproduce
intermittent issue.

### Expected behavior
I converted my resque workers into ActiveJob workers, and they are working fine in development. 

### Actual behavior
when I  `SomeJob.perform_later(args...)` the error states  `undefined method 'job_id=' `

### Steps I've Tried
In the console I tried to flush the Redis DB, and for some reason that worked for one job. and then it failed. 

This works fine in development. 
### System configuration
**Rails version**: 4.2.5.1

**Ruby version**: 2.2.2

**Resque version**: 1.26.0

This is the exception being thrown on resque-web
``` ruby
Worker
project-guru.novalocal:6406 on JOB_LOADER_QUEUE at just now
Class
 ActiveJob::QueueAdapters::ResqueAdapter::JobWrapper
Arguments
---
job_class: JobLoaderMinion
job_id: 216a6f06-e1a9-45a6-8074-6d1946c9b85c
queue_name: job_loader_queue
arguments:
- HostData
- "/tmp/RackMultipart20160621-3866-19taxtn.zip"
locale: en
Exception
NoMethodError
Error
undefined method `job_id=' for #<JobLoaderMinion:0x00000004c9df70>
```

**Comment by maclover7** [comment]
Do you have the full trace for the error?

**Comment by rjrobinson** [comment]
I do not. 

Just an update. I restarted all of the VMs, and in this case, "Turning it off and back on" seemed to resolve the issue. 

we can mark this matter as closed.

**Comment by maclover7** [comment]
Feel free to close the issue, then. :)
