### ISSUE TITLE
DateTime insertion on rails 5

### ISSUE THREAD

**Issue by waghanza** [rails/rails#25453]
Hi,

I have a simple table **events** on a `postgresql` database

| Column | Type | Modifier |
| --- | --- | --- |
| id | integer | not null default nextval('events_id_seq'::regclass) |
| start_at | timestamp without time zone |  |
| end_at | timestamp without time zone |  |

and I want to create a new **record**

``` rails
Event.create!(end_at:DateTime.strptime("1464559200000","%Q"))
```

I expect to have an event create with a valid date.

on my `fedora` I have

``` ruby
=> #<Event id: 2, start_at: nil, end_at: "2016-05-29 22:00:00">
```

and on a `debian`

``` ruby
=> #<Event id: 2, start_at: nil, end_at: nil>
```
- **Ruby** version : `ruby 2.3.1p112 (2016-04-26 revision 54768) [x86_64-linux]`
- **Rails** version :  `Rails 5.0.0.rc1`
- **PostgreSQL** version: `psql (PostgreSQL) 9.5.3`

I  have made this test, and it seems to be successful

``` ruby
begin
  require 'bundler/inline'
rescue LoadError => e
  $stderr.puts 'Bundler version 1.10 or later is required. Please update your Bundler'
  raise e
end

gemfile(true) do
  source 'https://rubygems.org'
  gem "rails", ">= 5.0.0.rc1", "< 5.1"
  gem "pg", "~> 0.18.4"
end

require "active_record"
require "minitest/autorun"
require "logger"
require "date"

# This connection will do for database-independent bug reports.
ActiveRecord::Base.establish_connection(adapter: "postgresql", database: "test", username: "postgres")
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :events do |t|
    t.timestamp :start_at
    t.timestamp :end_at
  end
end

class Event < ActiveRecord::Base
end

class BugTest < Minitest::Test
  def setup
    @event = Event.create!(dt: DateTime.strptime("1464559200000","%Q"))
  end

  def test_datetime
    assert_respond_to @event.dt, "to_f", "Could not get float from #{@event.dt}"
  end
end
```

**Comment by waghanza** [comment]
~~~rails
Event.create!(end_at: DateTime.strptime("1464559200000","%Q"))
~~~
**work** on a newly create `rails` **5** project

**Comment by vipulnsward** [comment]
I am not sure if this is a Rails bug. AFAIC tell, we properly process if we get a value from input.
This works as expected https://gist.github.com/vipulnsward/2417dc577f4773471ce6909b0ac3f4a7 .

Problem I see is you are not getting value from `DateTime.strptime("1464559200000","%Q")` on two difference systems. Can you confirm if that is the case? Or they both do provide values, but Rails is ignoring it somehow.
