### ISSUE TITLE
ActionView::Template::Error: Invalid query parameters: invalid %-encoding (RkpryQngn+vq%3N+13904)

### ISSUE THREAD

**Issue by mmustala** [rails/rails#25455]
### Steps to reproduce
1. Start rails server
2. Access url http://localhost:3000/?attr1=RkpryQngn+vq%3N+13904
### Expected behavior

I would expect receiving a request to the root_path with params `{attr1: 'RkpryQngn+vq%3N+13904'}` or something similar. Pretty much anything that I can handle in the controller would do.
### Actual behavior

Instead the exception is raised in the `lib/rack/utils.rb:127:in 'rescue in parse_nested_query'` and the execution never reaches the controller. I cannot rescue from this exception in my code. User will get white screen, no error message, nothing.
### System configuration

**Rails version**: 4.2.6

**Ruby version**: 2.3.0
### Additional information

I don't know where these requests are coming but they are consistently pointed to our "contact support" path. Each email that is sent to our users includes a link to support and there is a query string containing the integer id of the email. I suspect that some email client is doing something nasty to the query string.

**Comment by Shwetakale** [comment]
@mmustala In this scenario request will never reach to controller as before going to controller request goes from ```Rack middleware stack``` . 

You are getting this exception from ```ActionDispatch::ParamsParser``` middleware. You can read more about rack middlewares from (here)[http://guides.rubyonrails.org/rails_on_rack.html].

If you want to catch this exception I think you will have to write your own middleware to do this. I have not done this earlier but came across (this)[https://robots.thoughtbot.com/catching-json-parse-errors-with-custom-middleware] example.

**Comment by mmustala** [comment]
Yes, I'm just thinking that shouldn't rails handle this kind of situation gracefully? Or at least provide some method for handling the exception without the need for writing my own middleware.

**Comment by mmustala** [comment]
I mean, this kind of situation can happen to any application, not just mine. The middleware needed to handle this situation would not include any business logic specific to my app. I think, as a Rails developer I shouldn't need to write code to handle this kind of invalid query params.
