### ISSUE TITLE
Nested resources param `id` is repeated.

### ISSUE THREAD

**Issue by juanpastas** [rails/rails#25477]
### Steps to reproduce

Routes:

```ruby
  resources :quizzes do
    member do
      resources :submissions, as: :quiz_submission
    end
  end

```

### Expected behavior

Routes like these:

![routes](https://cloud.githubusercontent.com/assets/671721/16278873/26089a02-387e-11e6-9e39-b54062f0fe86.png)

### Actual behavior

Routes like these, note `:id` is repeated, instead of `:quiz_id`:

![routes rake](https://cloud.githubusercontent.com/assets/671721/16278892/3d4ba9f2-387e-11e6-9e95-2bb7b264003d.png)

### System configuration
**Rails version**: 4.2.6

**Ruby version**: 2.3.1p112

These gems:

```ruby
gem 'devise'
gem 'figaro'
gem 'inherited_resources'
gem 'slim-rails'
gem 'pry-rails'
gem 'quiet_assets'
gem 'rails_12factor'
gem 'simple_form'
```

**Comment by juanpastas** [comment]
I removed `member do`.

**Comment by damuz91** [comment]
It should work fine with member do as a nested resource for a member is valid. 
For example posts and comments simple relation:

    resources :posts do
	    member do
                post 'like'
                resources :comments
	    end
    end
    
Removing the member seems kind of fishy?
