### ISSUE TITLE
On terminal ruby error

### ISSUE THREAD

**Issue by achyuth2016** [rails/rails#25475]
### Steps to reproduce

(Guidelines for creating a bug report are [available
here](http://guides.rubyonrails.org/contributing_to_ruby_on_rails.html#creating-a-bug-report))

### Expected behavior
when ever i do open my terminal I do see the error.

### Actual behavior
Last login: Tue Jun 21 22:21:33 on console
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/universal-darwin15/rbconfig.rb:213: warning: Insecure world writable dir /usr/local in PATH, mode 040757
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/universal-darwin15/rbconfig.rb:213: warning: Insecure world writable dir /usr/local in PATH, mode 040757
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/universal-darwin15/rbconfig.rb:213: warning: Insecure world writable dir /usr/local in PATH, mode 040757

### System configuration
**Rails version**: not installed

**Ruby version**:ruby 2.0.0p648

**Comment by rafaelfranca** [comment]
Thank you for the issue. This is not related with Rails but with your environment.
