### ISSUE TITLE
Trying to change colour of highlighted text in my view

### ISSUE THREAD

**Issue by mananwason** [rails/rails#25484]
I am trying to change colour of highlighted text in the onclick of a button. I did this using a javascript function like : 

```
    $('#btn-highlight').click(function selectHTML() {
        try {
            if (window.ActiveXObject) {
                var c = document.selection.createRange();
                return c.htmlText;
            }

            var nNd = document.createElement("span");
            var w = getSelection().getRangeAt(0);
            w.surroundContents(nNd);
            return nNd.innerHTML;
        } catch (e) {
            if (window.ActiveXObject) {
                return document.selection.createRange();
            } else {
                return getSelection();
            }
        }
    });

    $(function() {
        $('#changeColor').click( function() {
            var mytext = selectHTML();
            $('span').css({"color":"white"});
        });
    });
```
Rails view : 
```
    <button class="btn btn-lg btn-info" id="btn-highlight" title="Highlight Text Filters" onclick="">
      <i class="fa fa-adjust"></i>
    </button>
```
But the issue is that the colour is not changing according to what I have added in the span above. It changes randomly. Any help is appreciated. Thanks

**Comment by sonianand11** [comment]
I suggest you to post this question on stackoverflow.com or any other forum. Mostly the issues created in Rails repository is related to Rails framework.

To help related to your question : it seems you have `onclick=""` in your button tag which causes issues. Try after removing it.

Hope that helps!!

**Comment by mananwason** [comment]
Hi @sonianand11. Thanks for the suggestion. I'll post the question on SO as well. I did try after removing onclick as well. Please let me know if you have any other pointers that might help me. Thanks!

**Comment by maclover7** [comment]
👍 thanks for submitting, but please use the mailing list or StackOverflow for questions/help, where a wider community will be able to help you. We reserve the issues tracker for issues only. :)
