### ISSUE TITLE
the problem about enum and method 'instantiate'

### ISSUE THREAD

**Issue by lczxhf** [rails/rails#25483]
### Steps to reproduce
 I use gem 'second_level_cache' to cache my ActiveRecord instance.
And i used enum just like:
```ruby
    class Shop < ActiveRecord::Base
        enum status: [:probation,:normal,:expire],default: :probation
    end

    Shop.create(name:'test')  # {"id"=>1,"name"=>"123","status"=>"probation"}
    #already cache by Rails.cache
    shop = Shop.find(1)   #fetch from cache   {"id"=>1,"name"=>"123","status"=>"probation"}
    shop.expire!   #{"id"=>1,"name"=>"123","status"=>"expire"}
    Shop.find(1) #fetch from cache {"id"=>1,"name"=>"123","status"=>"probation"}
    #the status that attribute of record also is 'probation'
```
   And then i get cache value directly through redis
   the value was `["Shop", {"id"=>1,"name"=>"123","status"=>"expire"}]`
   and i look  source code of second_level_cache and found out that it call the method `instantiate` by Shop.
   so anybody can tell me how should i do.
   think you
### System configuration
**Rails version**:5.0.0.rc1

**Ruby version**:2.3.0

**Comment by maclover7** [comment]
Based on that you are saying that this is only not working when the `second_level_cache` gem is added to your Rails application, I'm going to close out this issue as a third party problem. I recommend that you open up an issue with `second_level_cache`. :) If this still isn't working with the `second_level_cache` gem removed from the project, then we can reopen the issue.
