### ISSUE TITLE
NullSessionHash.fetch behaves differently than Session.fetch

### ISSUE THREAD

**Issue by raszi** [rails/rails#25489]
### Steps to reproduce

Try to fetch something from session without a session id with:

``` ruby
session.fetch(:key, :default_value)
```
### Expected behavior

It should return `:default_value`
### Actual behavior

Throws an `ArgumentError`:

```
ArgumentError - wrong number of arguments (given 2, expected 1):
```
### System configuration

**Rails version**:

actionpack-4.2.6
rack-1.6.4

But the error is there in the master branches as well.

**Ruby version**:

Ruby-2.3.0

**Comment by raszi** [comment]
The reason is that the `NullSessionHash` has a different implementation of the `fetch` method than the `Session`.

See the differences here:

`NullSessonHash#fetch` is inherited from [`Rack::Session::Abstract::SessionHash#fetch`](https://github.com/rack/rack/blob/8ebe20c80ffabc7cbf797999e74baeb3315673fa/lib/rack/session/abstract/id.rb#L53-L57)

[`ActionDispatch::Request::Session#fetch`](https://github.com/rails/rails/blob/master/actionpack/lib/action_dispatch/request/session.rb#L165-L172)

**Comment by maclover7** [comment]
Thanks for reporting this! Would you be willing to submit a PR to Rack to fix this?

**Comment by raszi** [comment]
For me that is a questions, should this be fixed in Rack or in ActionPack?

**Comment by rafaelfranca** [comment]
I believe it should be fixed in Rack since it is not respecting the same API of Hash. cc @tenderlove

**Comment by raszi** [comment]
Yes, that is a good point and I agree with that but I don't know which one was first the chicken or the egg. :)

Btw this change could and should be done in a backward compatible way.
