### ISSUE TITLE
scope to: 'controller#action' does not work

### ISSUE THREAD

**Issue by sonalkr132** [rails/rails#25488]
### Steps to reproduce
* In routes.rb add:
```
scope to: 'some_controller#some_action' do
    get 'some_path'
    put 'some_other_path'
end
```
* Start rails server

### Expected behavior
Both `some_path` and `some_other_path` should have been routed to `some_controller#some_action`

### Actual behavior
Got following error:
```
/home/user/.rvm/gems/ruby-2.3.1/gems/actionpack-5.0.0.rc2/lib/action_dispatch/routing/mapper.rb:328:in `check_part': Missing :controller key on routes definition, please check your routes. (ArgumentError)
  from /home/user/.rvm/gems/ruby-2.3.1/gems/actionpack-5.0.0.rc2/lib/action_dispatch/routing/mapper.rb:308:in `check_controller_and_action'
  from /home/user/.rvm/gems/ruby-2.3.1/gems/actionpack-5.0.0.rc2/lib/action_dispatch/routing/mapper.rb:251:in `normalize_options!'
  from /home/user/.rvm/gems/ruby-2.3.1/gems/actionpack-5.0.0.rc2/lib/action_dispatch/routing/mapper.rb:115:in `initialize'
  from /home/user/.rvm/gems/ruby-2.3.1/gems/actionpack-5.0.0.rc2/lib/action_dispatch/routing/mapper.rb:68:in `new'
  from /home/user/.rvm/gems/ruby-2.3.1/gems/actionpack-5.0.0.rc2/lib/action_dispatch/routing/mapper.rb:68:in `build'
  from /home/user/.rvm/gems/ruby-2.3.1/gems/actionpack-5.0.0.rc2/lib/action_dispatch/routing/mapper.rb:1690:in `add_route'
  from /home/user/.rvm/gems/ruby-2.3.1/gems/actionpack-5.0.0.rc2/lib/action_dispatch/routing/mapper.rb:1662:in `decomposed_match'
  from /home/user/.rvm/gems/ruby-2.3.1/gems/actionpack-5.0.0.rc2/lib/action_dispatch/routing/mapper.rb:1626:in `block in match'
  from /home/user/.rvm/gems/ruby-2.3.1/gems/actionpack-5.0.0.rc2/lib/action_dispatch/routing/mapper.rb:1609:in `each'
  from /home/user/.rvm/gems/ruby-2.3.1/gems/actionpack-5.0.0.rc2/lib/action_dispatch/routing/mapper.rb:1609:in `match'
  from /home/user/.rvm/gems/ruby-2.3.1/gems/actionpack-5.0.0.rc2/lib/action_dispatch/routing/mapper.rb:722:in `map_method'
  from /home/user/.rvm/gems/ruby-2.3.1/gems/actionpack-5.0.0.rc2/lib/action_dispatch/routing/mapper.rb:680:in `get'
  from /home/user/rubygems.org/config/routes.rb:108:in `block (2 levels) in <top (required)>'
  from /home/user/.rvm/gems/ruby-2.3.1/gems/actionpack-5.0.0.rc2/lib/action_dispatch/routing/mapper.rb:859:in `scope'
  from /home/user/rubygems.org/config/routes.rb:107:in `block in <top (required)>'
  ...
```

### System configuration
**Rails version**:
rails-5.0.0.rc2
**Ruby version**:
ruby 2.3.1p112 (2016-04-26 revision 54768) [x86_64-linux]

This is happening because of this commit: 97d7dc48d

Previously, `options` was first [merged with `scope[:options]`](https://github.com/rails/rails/commit/97d7dc48d68e4c20c17e315c8f4d3f045ed97f5a#diff-46876897330259072a679792c5f45f99R64) and then `@to` was set with:
```
@to  = options.delete :to
```
but now `to` is [set in `process_path`](https://github.com/rails/rails/commit/97d7dc48d68e4c20c17e315c8f4d3f045ed97f5a#diff-46876897330259072a679792c5f45f99R1561) method (which happens before  `scope[:options]` is merged) and passed as params. Thus `Mapping` does not know about `to` option passed with scope.

`via`, `format` and `anchor` would have the same fate but `via` and `format` are saved by `options.delete(:key) { @scope[:key] }` and `anchor` uses `options.delete(:anchor) { true }`. Shouldn't all of them have the same behavior?

**Comment by maclover7** [comment]
Thank you for reporting this! Marking as a regression.

r? @tenderlove

**Comment by maclover7** [comment]
Reproduction script that fails on master can be found here --> https://gist.github.com/maclover7/691ecc4c0b3c8539c078587b65ad1c61
