### ISSUE TITLE
In mountable plugin fixtures from test/dummy/test/fixtures don't load

### ISSUE THREAD

**Issue by yuriihabrusiev** [rails/rails#25493]
### Steps to reproduce
1. Generate new mountable plugin with `rails plugin new cool_plugin --mountable`
2. Go to `test/dummy` and generate few scaffolds
3. Return to plugin root and run `bin/rails t`
### Expected behavior

Tests should pass
### Actual behavior

Tests don't pass because in test helper we have

``` ruby
if ActiveSupport::TestCase.respond_to?(:fixture_path=)
  ActiveSupport::TestCase.fixture_path = File.expand_path("../fixtures", __FILE__)
  ...
end
```
### Potential solution

Change

``` ruby
ActiveSupport::TestCase.fixture_path = File.expand_path("../fixtures", __FILE__)
```

to

``` ruby
ActiveSupport::TestCase.fixture_path = File.expand_path("../dummy/test/fixtures", __FILE__)
```

in `railties/lib/rails/generators/rails/plugin/templates/test/test_helper.rb`
### System configuration

**Rails version**: 5.0.0.rc2

**Ruby version**: 2.3.0

**Comment by maclover7** [comment]
Would you be willing to submit a PR to change this? We can continue the discussion there :)
