### ISSUE TITLE
Add period at the end of error message

### ISSUE THREAD

**Issue by victorngkp** [rails/rails#25490]
From UX perspective, a full sentence is to end with a period (see http://ux.stackexchange.com/questions/18671/), but this is not the case with Rails. In https://github.com/rails/rails/blob/master/activemodel/lib/active_model/locale/en.yml, we see that error messages are left hanging.

If the community agrees that we should add period at the end of error message in ActiveModel (and everywhere else where applicable), please +1, then I shall make a PR.

**Comment by rafaelfranca** [comment]
Thank you so much for the issue but we don't take feature request on the issue tracker. We recommend you to try to implement the feature and send us a pull request or if you are in doubt if the feature will be accepts ask in Rails Core mailing list for feedback.
