### ISSUE TITLE
Rails swallows errors with vanilla setup

### ISSUE THREAD

**Issue by janko-m** [rails/rails#25500]
### Steps to reproduce

```sh
$ gem install rack-test_app
```
```rb
require "rails"
require "action_controller/railtie"

class MyApp < Rails::Application
  config.secret_key_base = "secret"
  routes.append do
    root to: "home#index"
  end
  config.eager_load = true # remove deprecation
  initialize!
end

class HomeController < ActionController::Base
  def index
    raise "something went wrong"
  end
end

require "rack/test_app"

app = Rack::TestApp.wrap(MyApp)
response = app.get "/"

puts response.status #=> 500
```

### Expected behavior

When I create a vanilla Rails application, I would expect Rails to propagate all raised errors. The reason why I'm creating an app in this way (versus with `rails new`) is because when I'm trying to reproduce [Shrine](https://github.com/janko-m/shrine) issues, I want the example to be a single executable file.

### Actual behavior

With this setup Rails swallows all errors, and sets status to 500, which makes it difficult to write code because I don't know if I made a mistake in the controller action.

### System configuration

**Rails version**: 5.0.0.rc2

**Ruby version**: 2.3.0

**Comment by janko-m** [comment]
Just to prove that it isn't the `rack-test_app` gem which is swallowing the errors:

```rb
require "rack/test_app"

app = Rack::TestApp.wrap(->(env) { raise "something went wrong" })
app.get "/" #=> error is properly raised
```

**Comment by rafaelfranca** [comment]
Yes, this is the expected behavior. If you don't want this behavior make sure you set the proper configuration to false in the request header.

```
"action_dispatch.show_exceptions" => false
```

**Comment by rafaelfranca** [comment]
oh. since you have an application you can also set `config.action_dispatch.show_exceptions = false`

**Comment by rafaelfranca** [comment]
See http://guides.rubyonrails.org/configuring.html

**Comment by rafaelfranca** [comment]
Sorry, should not have closed. Clicked the wrong button.

**Comment by janko-m** [comment]
Thanks, this properly propagates the error. I'm not sure what the correct behaviour should be here, probably it should stay like this, because I don't think you can know whether people are opening the application in the browser and want the exception page, or running it in the script and want the error propagated. Can this be detected?

If not, this issue can be closed.

**Comment by rafaelfranca** [comment]
I just made a quick research and we want this to be true when when undefined to not render the default rack error page in production in case people deploy the application removing this setting. As the request comes from rack in both cases there is no way to detect it.
