### ISSUE TITLE
Step 8 Deleting Comments Bug (and solution that worked for me)

### ISSUE THREAD

**Issue by svpersteve** [rails/rails#25505]
### Steps to reproduce

[Step 8 - Deleting Comments](http://guides.rubyonrails.org/getting_started.html#deleting-articles) produces [this error](https://cloud.githubusercontent.com/assets/2977353/13484568/6556bf14-e0bc-11e5-9ee4-a129c0268187.png).
### Expected behavior

The page should load with a 'Destroy comment' link under each comment
### Actual behavior

Page fails to load with [this](https://cloud.githubusercontent.com/assets/2977353/13484568/6556bf14-e0bc-11e5-9ee4-a129c0268187.png) message.

**[Solution is here](https://github.com/rails/rails/issues/24017#issuecomment-191576111)**
### System configuration

**Rails version**:
4.2.6
**Ruby version**:
2.2.4p230 (2015-12-16 revision 53155) [x86_64-darwin15]

**Comment by vipulnsward** [comment]
Are you following http://guides.rubyonrails.org/getting_started.html#adding-a-route-for-comments

See also https://github.com/rails/rails/issues/24019#issuecomment-191582544

**Comment by Shwetakale** [comment]
@svpersteve Could you push sample rails app to reproduce this issue? 

I tried it on the same ruby and rails versions you mentioned and it's working as expected as per guides.

**Comment by solojavier** [comment]
Reading through the links seems like this was not an issue: https://github.com/rails/rails/issues/24019#issuecomment-191582544

Can this be closed @svpersteve ?

**Comment by vipulnsward** [comment]
Closing based on https://github.com/rails/rails/issues/25505#issuecomment-228291065 
Please reopen if that is not a case.
