### ISSUE TITLE
ActiveJob::DeserializationError: Error while trying to deserialize arguments

### ISSUE THREAD

**Issue by sonalkr132** [rails/rails#25516]
### Steps to reproduce
* rails new my_app
* rails g scaffold post title:string body:text
* rails g scaffold comment post:references body:text
* rails g mailer comments submitted
* rails db:migrate
* Change `CommentsMailer#submitted` to:
```Ruby
def submitted(post)
    mail to: "to@example.org", subject: "#{post.title} was commented on"
end
```
* Write test:
```Ruby
class CommentTest < ActionDispatch::IntegrationTest
  setup do
    @post = Post.create(title: 'some', body: 'hah')
  end

  test "submitted" do
    CommentsMailer.submitted(@post).deliver_later
    sleep 5 # since I am calling deliver_later I want to make sure that job gets executed
    assert_equal 'some', Post.last.title # passes. ie @post exists
    assert_equal 1, ActionMailer::Base.deliveries.size # fails. ie `@completed_task_count` is 0
  end
end
```
### Expected behavior
Test should have passed

### Actual behavior
```
Failure:
CommentTest#test_submitted [/home/user/my_app/test/integration/comment_test.rb:12]:
Expected: 1
Actual: 0
```

### System configuration
**Rails version**:
5.0.0.rc2
**Ruby version**:
ruby 2.3.1p112 (2016-04-26 revision 54768) [x86_64-linux]

I believe this is happening because of new `queue_adapter` `async`. Setting following in `environments\test.rb` makes the test pass:
```Ruby
config.active_job.queue_adapter = :inline
```

`async` adapter would [use `Concurrent::ThreadPoolExecutor`](https://github.com/rails/rails/blob/5-0-stable/activejob/lib/active_job/queue_adapters/async_adapter.rb#L85-L87) because I didn't change the `immediate` value.

`executor.post(job, &:perform)` would finally end up [here](https://github.com/ruby-concurrency/concurrent-ruby/blob/master/lib/concurrent/executor/ruby_thread_pool_executor.rb#L350). With exception being: 
```Ruby
#<ActiveJob::DeserializationError: Error while trying to deserialize arguments: Couldn't find Post with 'id'=980190963>
```

cc: @jeremy

**Comment by maclover7** [comment]
Thanks for reporting. Would you be willing to open up a PR for this change, and we can continue the discussion there? Also, I tried to create a reproduction script [here](https://gist.github.com/maclover7/a2e50ef90fbc96cc179792922b00d017), but I'm getting a different error than the one you are getting.

**Comment by kaspth** [comment]
@maclover7 you need to add in GlobalID in your script as well. That's what handles the model lookup.

**Comment by kaspth** [comment]
@sonalkr132 I'm curious why you're using integration tests to test your mailers? Is there some larger context missing from your reproduction where the email is generated through e.g. a controller action?

Also I'd test the mailers' behavior/output separately from the enqueing of it. I'd say `deliver_now` would be appropriate.

This doesn't read like a bug to me, so I'm going to give this a close. Happy to reconsider when I hear back. Thanks for trying the RCs! ❤️

**Comment by sonalkr132** [comment]
> I'm curious why you're using integration tests to test your mailers?

I was just trying to get my point across. Yes, it is missing context. In real application delivering mail is part of an integration test  and we are counting on that mail being delivered. Calling `deliver_now` is not an option because [`clearance` gem was setting it](https://github.com/thoughtbot/clearance/blob/c643e9432c3320724ee96da4e19e381691eae1c0/app/controllers/clearance/passwords_controller.rb#L56).

It has easy work around. One can use  `ActiveJob::Base.queue_adapter.immediate = true` in `setup` to force use of `Concurrent::ImmediateExecutor` or as I mentioned go back to `inline` adapter.
I reported it only because the behavior was different from 4.2.x and I had to read rails code to figure out what was going on.

**Comment by sonalkr132** [comment]
And of course, it is weird that ActiveJob couldn't find `post` even if it was there.

**Comment by kaspth** [comment]
Hm, true, I can't remember why we switched the base dev/test adapter without a deprecation cycle.

Anyway, the immediate option isn't for public use :)

Take a look at the `perform_enqueued_jobs` method in `ActiveJob::TestHelper`. There are also methods to test that a job has been enqueued.
