### ISSUE TITLE
class: 'disabled' in the f.select doesn't work

### ISSUE THREAD

**Issue by rsmything** [rails/rails#25529]
actionview (= 5.1.0.alpha)

Why f.select doesn't want to set value 'disabled' to the :class key? 
The more that 'disable' works...

`= f.select :country, COUNTRIES.map { |k, v| [v, k] }, {}, { class: :disabled, disabled: true }`
_rendered as html:_
`<select class disabled="disabled" name="user[country]" id="user_country">`

`= f.select :country, COUNTRIES.map { |k, v| [v, k] }, {}, { class: :disabled, disabled: true }`
_rendered as html:_
`<select class="disable" disabled="disabled" name="user[country]" id="user_country">`

Can anyone explain me? I didn't find in the code where something starts to go wrong.

**Comment by vipulnsward** [comment]
@rsmything hmm, I was not able to reproduce this, see https://github.com/rails/rails/pull/25562/files.
Can you create an example application to reproduce this. Perhaps this is due to some form builder gem that you may be using.

**Comment by rsmything** [comment]
can't reproduce after update
