### ISSUE TITLE
5.0.0.rc2: 'render :partial' returns an array of ActiveSupport::SafeBuffer

### ISSUE THREAD

**Issue by YoonjaeYoo** [rails/rails#25521]
### Steps to reproduce

I needed to render a view in a controller first then use it like:

1. First, respond with the view
2. Then, broadcast it to ActionCable subscribers.

Code is like:
```ruby
  def create
      ...
      html = render partial: 'message', object: message
      ActionCable.server.broadcast(
          "chat_#{params[:tutoring_id]}",
          message: html, # 2
          senderId: current_user.id
      )
      html # 1
  end
```

The problem is, `html` was a pure string when using 5.0.0.rc1 but after upgrading to 5.0.0.rc2 it is now an array of `ActiveSupport::SafeBuffer`.
'Responding with the view' doesn't cause any problem but when 'broadcasting', subscribers receive an array as their data, not html string. Shouldn't it be just a string? Does it have something to do with #24929?

### Expected behavior
`html` should be a string

### Actual behavior
`html` is an array of `ActiveSupport::SafeBuffer`

### System configuration
**Rails version**:
5.0.0.rc2

**Ruby version**:
2.3.1p112

**Comment by maclover7** [comment]
Hmm, not sure if this is supported behavior 😬. If you were to try and render a partial, I'd recommend going through the controller's `render` class method (see [here](https://github.com/rails/actioncable-examples/blob/master/app/jobs/comment_relay_job.rb#L4) for an example of doing that).

**Comment by YoonjaeYoo** [comment]
Actually, 'create' method is of a controller. Thus, 'render' above is a controller's method. 😫

**Comment by rafaelfranca** [comment]
The return value of render is not defined. It returned a string before by coincidence. What you want is render_to_body but could you create a way to reproduce this behavior so we can bisect to the change or could you do the bisect?

**Comment by YoonjaeYoo** [comment]
My apologize. I stack traced and found that render is calling Remotipart::RenderOverrides::render_with_remotipart. I added 'remotipart' gem when upgrading to '5.0.0.rc2'. Please close this issue.
