### ISSUE TITLE
Deprecation of strings or symbols for middleware class names

### ISSUE THREAD

**Issue by sonalkr132** [rails/rails#25525]
### Steps to reproduce
- Create a middleware folder under `app` directory.
- Create file `app/middleware/unicorns.rb`:

``` Ruby
class Unicorns
  def initialize(app)
    @app = app
  end

  def call(env)
    @app.call(env)
  end
end
```
- Specify use of the middleware in `application.rb`:

``` Ruby
module MyApp
  class Application < Rails::Application
     config.middleware.use Unicorns
  end
end
```
- Check if middleware was added

```
rake middleware
```
### Expected behavior

Unicorns should have showed up at the end of middleware stack 
### Actual behavior

```
NameError: uninitialized constant MyApp::Application::Unicorns
/home/user/my_app/config/application.rb:14:in `<class:Application>'
/home/user/my_app/config/application.rb:10:in `<module:MyApp>'
/home/user/my_app/config/application.rb:9:in `<top (required)>'
/home/user/my_app/Rakefile:4:in `require_relative'
/home/user/my_app/Rakefile:4:in `<top (required)>'
/home/user/.rvm/gems/ruby-2.3.1/gems/rake-11.2.2/exe/rake:27:in `<top (required)>'
/home/user/.rvm/gems/ruby-2.3.1/bin/ruby_executable_hooks:15:in `eval'
/home/user/.rvm/gems/ruby-2.3.1/bin/ruby_executable_hooks:15:in `<main>'
```
### System configuration

**Rails version**:
5.0.0.rc2
**Ruby version**:
ruby 2.3.1p112 (2016-04-26 revision 54768) [x86_64-linux]

Using `config.middleware.use "Unicorns"` works but that is [deprecated](https://github.com/rails/rails/commit/83b767ce). Using `config.middleware.user Unicorns` in `environments/*.rb` works too.

**Comment by maclover7** [comment]
Hmm, I feel like this might have something to do with constant autoloading 😬

cc @fxn

**Comment by rafaelfranca** [comment]
Yeah, it is. You should not put middlewares or any code that should not be reloadable in the app folder.

http://edgeguides.rubyonrails.org/autoloading_and_reloading_constants.html#autoloading-and-initializers

**Comment by ignatiusreza** [comment]
where would be the suggested place to put application custom middlewares? seems like both app and lib suffer from the same autoloading issue.. tried to put it under `config/middlewares` but it's not loaded..

[guide](http://edgeguides.rubyonrails.org/configuring.html#configuring-middleware) should also be updated I guess, to mentioned the suggested way to do so?

**Comment by rafaelfranca** [comment]
It is in `lib`. But I think your problem is that `lib` is not in the load path at that point. I think the only way is to require the file explicitly.

@tenderlove what do you think about this?

**Comment by tenderlove** [comment]
This really does look like a const missing issue.  @ignatiusreza does `::Unicorns` work?

**Comment by matthewd** [comment]
Is it expected that autoloads will work inside application.rb? That's... pretty early.

**Comment by tenderlove** [comment]
It should, I think.  Calling `config` should instantiate the app, so everything *should* be there.  Unless maybe it doesn't have the autoload paths set yet?

**Comment by ignatiusreza** [comment]
@tenderlove same issue `::Unicorns` also doesn't work, with the same const missing issue

**Comment by fxn** [comment]
I need to write a guide about the init process.

When the body of the application class is executed, configuration is set as a side-effect. Autoload paths are set in [an initializer](https://github.com/rails/rails/blob/bb9a4f3f6daafb0089c068522dec0380e68d7fcd/railties/lib/rails/engine.rb#L565) taking the configuration into account, and initializers run after *config/application.rb* and the corresponding overrides per environment have run.

In addition to that, as @rafaelfranca pointed, no one would be reloading that middleware in development mode. The class object would be stored and that's it (as you probably know, the class object lives regardless of the existence of the original constant that evaluated to it). The class object will be there, but changes to the middleware in the implementation won't be reflected.

As of this writing, the easiest solution to this is to load a regular file with `require`. This file can be in *app/middleware* if you want, all these directories are also in the load path.

**Comment by fxn** [comment]
Correction: no, at that point the directory *app/middlewares* is still not in `$LOAD_PATH` because that is also done in [an initializer](https://github.com/rails/rails/blob/bb9a4f3f6daafb0089c068522dec0380e68d7fcd/railties/lib/rails/engine.rb#L553).

**Comment by ignatiusreza** [comment]
The main issue here is not about auto-reloading middleware, it's okay for it to not be reloadable, but it's about not being able to do `config.middleware.use Unicorns` in `application.rb` -- which would raise const missing, even though we can do so in the corresponding overrides for the environment, e.g. `environments/development.rb` -- which would continue just fine, and is the easier solution compared to explicit require I think.. but still, this discrepancy is surprising..

**Comment by run27017** [comment]
Hi, everyone. I put these configs in a initializer file like

    Rails.application.config.middleware.insert_before 0, APIStyle::PathUnderscore

**Comment by arthurnn** [comment]
I would say the easiest solution, for now, is to use a `require_relative` in the application.rb file.
I think a normal `require` should work too, but as @fxn mentioned `app` is not in the LOAD_PATH yet, so maybe it won't, but i would still give it a try.

**Comment by cmrd-senya** [comment]
The issue is still present in Rails 5.2

**Comment by dennym** [comment]
Still an issue in v5.2.2 
require_relative helps to have the required `Class` available but this has also the side effect of loading the file twice. Once with the `application.rb - require_relative` and then when the `app/middleware` is required. If you have constants in you middleware you will get `warning: already initialized ...` messages.

I think in rails version before v5 the `config.middleware...` part worked with string instead of actual classes and got initialized later in the startup. No idea why this got changes in the first place....

**Comment by rafaelfranca** [comment]
middleware can't be in `app` because they can't be reloaded. They should be in `lib` and if you put them in `lib`, `require_relative` will work.

This ticket is closed because this is not an issue.

**Comment by abhilashak** [comment]
the `app/middlewares` folder is not loading even if I added to the load paths in `Rails 5.2.2`

As suggested, the following line in `application.rb` works.

```
require_relative '../app/middlewares/my_middleware'
```

**Comment by juanccamachob94** [comment]
It works for me
```
Dir["./lib/middleware/*.rb"].each { |file| require file }
```

**Comment by stoicAlchemist** [comment]
Taking the linking of my middlewares (`use`, `insert_before` etc.) into an initializer seems to work for me, no `require` worked for me

**Comment by eric-norcross** [comment]
Using `Ruby 2.6` and `Rails 6`, I was able to get this working with:

    # lib/middleware/my_custom_middleware.rb

    module Middleware
      class MyCustomMiddleware
        def initialize(app)
          @app = app
        end

        def call(env)
          #...
        end
      end
    end

and:

    # config/application.rb

    require_relative 'boot'
    require 'rails/all'
    Bundler.require(*Rails.groups)

    module GoApron
      class Application < Rails::Application
        #...

        Dir[Rails.root.join('lib', 'middleware', '*.{rb}')].each { |file| require file }
        config.middleware.use Middleware::MyCustomMiddleware
      end
    end
