### ISSUE TITLE
respond_to_missing? is not implemented for Rails::Application::Configuration::Custom

### ISSUE THREAD

**Issue by fledman** [rails/rails#25542]
[Rails::Application::Configuration::Custom](https://github.com/rails/rails/blob/master/railties/lib/rails/application/configuration.rb#L195) (the backing class of `Rails.configuration.x `)
has a `method-missing` implementation that responds to **all** messages,
but it does not have a matching `respond_to_missing?` implementation.

### Current behavior
```
> cc=Rails::Application::Configuration::Custom.new
 => #<Rails::Application::Configuration::Custom:0x007fb9e71e7960 @configurations={}> 
> cc.respond_to?(:foobar)
 => false 
> cc.foobar
 => {}
> cc.method(:foobar)
NameError: undefined method `foobar' for class `Rails::Application::Configuration::Custom'
```
### Expected behavior
`respond_to?` should be true for all messages, `method` should work properly
```
> cc=Rails::Application::Configuration::Custom.new
 => #<Rails::Application::Configuration::Custom:0x007fb9e43a84c8 @configurations={}> 
> cc.respond_to?(:foobar)
 => true 
> cc.foobar
 => {}
> cc.method(:foobar)
 => #<Method: Rails::Application::Configuration::Custom#foobar> 
```
### Proposed Solution
add the following definition to `Rails::Application::Configuration::Custom`
```
def respond_to_missing?(symbol, *)
  true
end
```

### System configuration
**Rails version**: 3.x, 4.x, and 5.x
**Ruby version**: any

**Comment by maclover7** [comment]
Can you open up a PR for this, and we can continue the discussion there? Thanks!

**Comment by maclover7** [comment]
Closing, since #25704 was merged in.
