### ISSUE TITLE
Rails 4.2.6 cannot use YAML as serializer of AR field

### ISSUE THREAD

**Issue by phuongnd08** [rails/rails#25550]
### Steps to reproduce

(Guidelines for creating a bug report are [available
here](http://guides.rubyonrails.org/contributing_to_ruby_on_rails.html#creating-a-bug-report))

Create an AR model
class Model < ActiveRecord::Base
   serialize :field, YAML
end

Model.create(field: { my_hash: true })
### Expected behavior
No error thrown

### Actual behavior
TypeError: no implicit conversion of nil into String

### System configuration
**Rails version**: 4.2.6

**Ruby version**: 2.1.6

AR use YAML.load(nil) as a part of the calculation, and YAML.load(nil) is raising exception.

**Comment by rafaelfranca** [comment]
If you want to serialize as a YAML just use:

```ruby
serialize :field, Hash
```

As it is in the documentation.

**Comment by phuongnd08** [comment]
Thank you. I used `serialize :field, Hash` but it convert subclass of Hash to Hash. Come back and see your edited comment.

**Comment by siegy22** [comment]
@rafaelfranca I'm migrating updating rails `4.1.5` to `4.2.10`.

In the current code there's this:

```ruby
class User
  serialize :field, YAML
end

User.new.field #=> {}
```

So according to you, this code is now:

```ruby
class User
  serialize :field
end

User.new.field #=> "{}"
```

So the new code returns a string, not a hash. Do you know why?

**Comment by siegy22** [comment]
I think I just found what it caused to return a string there.

My column default was `"{}"`, I changed it to: `{}.to_yaml`. Now it works.
