### ISSUE TITLE
no_cache override other cache control keys

### ISSUE THREAD

**Issue by albertnetymk** [rails/rails#25563]
According to https://www.mnot.net/cache_docs/#FAQ, I can do the following for private asserts:

```
Cache-Control: public, no-cache
```

And, in rails, this is what I did, but the return Cache-Control header contains `no-cache` only.

```
response.cache_control.merge!({ public: true, no_cache: true })
```

I think it's caused by https://github.com/rails/rails/blob/master/actionpack/lib/action_dispatch/http/cache.rb#L195

**Comment by matthewd** [comment]
Are you actually using HTTP authentication?  :confused:

It looks like that code dates to e1786ee6ebee9fab10d6756be1eeacbbe6b65b48.

It seems reasonable that we could respect an explicit `public: true`... though the use case where you actually want such a construct seems awfully rare.

The work-around seems to be `no_cache: true, extras: ['public']`. Given how unusual this requirement is, maybe that's sufficient.

**Comment by albertnetymk** [comment]
> Are you actually using HTTP authentication?

Yes. The action containing `response.cache_control.merge!({ public: true, no_cache: true })` returns different response, depending on which specific user sends the request.

> such a construct seems awfully rare

Really? I have no idea. I was reading the link I posted above on cache, and the instructions in section `My pages are password-protected; how do proxy caches deal with them?` seems reasonable to me.
