### ISSUE TITLE
Unable to test SSL routes with new keyword-arguments

### ISSUE THREAD

**Issue by jeroenvisser101** [rails/rails#25568]
### Steps to reproduce

``` ruby
# in controller
class MyController < ApplicationController
  force_ssl
end

# in test
get :new, protocol: :https # => this works, but throws an deprecation warning
```

How can I mitigate this? Nothing seems to be mentioned [in edgeguides](http://edgeguides.rubyonrails.org/5_0_release_notes.html)

### System configuration
**Rails version**: 5.0.0-rc2

**Ruby version**: 2.3.1

**Comment by maclover7** [comment]
Hmm, are you using RSpec in your tests above? Calling `get '/', protocol: :https` doesn't appear to be supported through Rails' `ActionDispatch::IntegrationTest` -- this might be supported through some `rspec-rails` helpers.

**Comment by jeroenvisser101** [comment]
Ah, so it's `params: { protocol: :https }` for Rails 5? That's great, thanks!

**Comment by jeroenvisser101** [comment]
BTW: Can you do this with HTTP Headers too?

**Comment by vipulnsward** [comment]
@jeroenvisser101 yes http://guides.rubyonrails.org/testing.html#setting-headers-and-cgi-variables 
I believe, we can give this a close then?

**Comment by jeroenvisser101** [comment]
Yes! Thank you so much, and congratulations on the 5.0 milestone, great work of all of you 👍
