### ISSUE TITLE
[ActionCable] remove lib/assets/compiled/action_cable.js

### ISSUE THREAD

**Issue by voxik** [rails/rails#25593]
### Steps to reproduce
Looking into ActionCable gem, there is packaged `lib/assets/compiled/action_cable.js`. I might missing something important, but it looks this file is used just for NPM repository and RoR itself does not use it at all. I believe that the file is included in the ActionCable gem just by accident and therefore I propose to exclude it from the package.

### Expected behavior
`lib/assets/compiled/action_cable.js` should not be included in gem.

### Actual behavior
`lib/assets/compiled/action_cable.js` is shipped with the gem, but not used

**Comment by rafaelfranca** [comment]
It is used by Rails. `lib/assets/compiled` is at the sprockets load path and when people does `//=require action_cable` that file is what is being used.

**Comment by voxik** [comment]
Ah, ok ... should improve my searching skill then. Thank you and sorry for the noise.

**Comment by rafaelfranca** [comment]
No problem. It is not easy to search though. This is an implicit behavior of sprockets with engines so not so easy to gasp only looking the rails source.
