### ISSUE TITLE
ActiveRecord::Base#save sets Timestamps more accurately than #find

### ISSUE THREAD

**Issue by jfornoff** [rails/rails#25592]
Hi there!

### Steps to reproduce

![activerecord_timestamp](https://cloud.githubusercontent.com/assets/1319818/16484099/c036e14e-3eb7-11e6-8561-ebfd5d1e3da1.jpg)

Example app with failing test caused by the issue: https://github.com/jfornoff/AR_timestamps/blob/master/test/models/post_test.rb

### Expected behavior
updated_at timestamp value returned by ActiveRecord#save should equal timestamp value of re-fetched object (e.g. via #reload or finder)

### Actual behavior
Timestamps are slightly different (I am usually seeing 7 fractional digits on the object returned by #save, as opposed to 6 fractional digits on objects returned by #find or #reload.

### System configuration
Rails 4.2.6, issue seen on MySQL and Sqlite databases.

**Ruby version**:
2.3.1

**Comment by sgrif** [comment]
Fixed by #25951
