### ISSUE TITLE
railties v4 - Rails::Generators::Base is missing `require 'rails/generators'` declaration

### ISSUE THREAD

**Issue by Kache** [rails/rails#25614]
### Steps to reproduce
```ruby
$ irb
> require 'rails/generators/active_record/migration/migration_generator'
NoMethodError: undefined method `aliases' for Rails::Generators:Module
	from .../gems/railties-4.0.13/lib/rails/generators/base.rb:307:in `default_aliases_for_option'
```

https://github.com/rails/rails/blob/v4.0.13/railties/lib/rails/generators/base.rb#L307

### Expected behavior

files are loaded:

```ruby
$ irb
> require 'rails/generators' # this shouldn't be neccessary
true
> require 'rails/generators/active_record/migration/migration_generator'
true
```

### Actual behavior

exception raised b/c dependency not being required

### System configuration
**Rails version**:

[https://github.com/rails/rails/blob/**v4.0.13**/railties/lib/rails/generators/base.rb#L307](https://github.com/rails/rails/blob/v4.0.13/railties/lib/rails/generators/base.rb#L307)

**Ruby version**:

n/a

**Comment by rafaelfranca** [comment]
Does this happen with 4.2?

**Comment by rafaelfranca** [comment]
Oh, you need to require the top level files before starting to use something. So make sure you required `rails/generators` before requiring `'rails/generators/active_record/migration/migration_generator'`

**Comment by Kache** [comment]
Oh, it's intended to not require its own dependencies?

**Comment by rafaelfranca** [comment]
Yes. all shared dependencies are in the top level files
