### ISSUE TITLE
Could not find proper version of railties (4.2.6) When doing rails -v

### ISSUE THREAD

**Issue by kannannadarajan** [rails/rails#25622]
### Steps to reproduce

Just installed ruby 2.3.1 via rvm and made it as default. Then installed rails. After installation just checked the version and shows the following message.

$ruby -v
ruby 2.3.1p112 (2016-04-26 revision 54768) [x86_64-darwin15]

$ rails -v
Could not find proper version of railties (4.2.6) in any of the sources
Run `bundle install` to install missing gems.

### Expected behavior
It should say Rails 5.0.0

### Actual behavior
It says "Could not find proper version of railties (4.2.6) in any of the sources"

### System configuration
**Rails version**:

**Ruby version**:

Mac version

uname -a
Darwin Kannans-MacBook-Pro.local 15.5.0 Darwin Kernel Version 15.5.0: Tue Apr 19 18:36:36 PDT 2016; root:xnu-3248.50.21~8/RELEASE_X86_64 x86_64

**Comment by sgrif** [comment]
What is the value of `which rails`? Is it `bin/rails`? If so, this is what you'd expect to see, as it's using the Gemfile for your current directory. If not, can you give exact steps to reproduce (e.g. the console commands that you executed for this)

**Comment by kannannadarajan** [comment]
Oh yes! 

$ which rails
/usr/local/rvm/gems/ruby-2.3.1/bin/rails

**Comment by sgrif** [comment]
> can you give exact steps to reproduce (e.g. the console commands that you executed for this)

**Comment by prakashmurthy** [comment]
> $ rails -v
> Could not find proper version of railties (4.2.6) in any of the sources
> Run bundle install to install missing gems.

Looks like not all gems are installed; could you try running `bundle install` please?

**Comment by kannannadarajan** [comment]
Kannans-MacBook-Pro:BasecampPlus kannan$ rvm list

rvm rubies

=> ruby-2.0.0-p643 [ x86_64 ]
   ruby-2.2.4 [ x86_64 ]
 * ruby-2.3.0 [ x86_64 ]

# => - current
# =* - current && default
#  * - default

Kannans-MacBook-Pro:BasecampPlus kannan$ rvm use 2.3.0
Using /usr/local/rvm/gems/ruby-2.3.0
Kannans-MacBook-Pro:BasecampPlus kannan$ rvm install 2.3.1
Warning, new version of rvm available '1.27.0', you are using older version '1.26.11'.
You can disable this warning with:    echo rvm_autoupdate_flag=0 >> ~/.rvmrc
You can enable  auto-update  with:    echo rvm_autoupdate_flag=2 >> ~/.rvmrc
Searching for binary rubies, this might take some time.
No binary rubies available for: osx/10.11/x86_64/ruby-2.3.1.
Continuing with compilation. Please read 'rvm help mount' to get more information on binary rubies.
Checking requirements for osx.
Certificates in '/usr/local/etc/openssl/cert.pem' are already up to date.
Requirements installation successful.
Installing Ruby from source to: /usr/local/rvm/rubies/ruby-2.3.1, this may take a while depending on your cpu(s)...
ruby-2.3.1 - #downloading ruby-2.3.1, this may take a while depending on your connection...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 13.7M  100 13.7M    0     0  1416k      0  0:00:09  0:00:09 --:--:-- 1879k
No checksum for downloaded archive, recording checksum in user configuration.
ruby-2.3.1 - #extracting ruby-2.3.1 to /usr/local/rvm/src/ruby-2.3.1....
ruby-2.3.1 - #configuring...........................................................
ruby-2.3.1 - #post-configuration.
ruby-2.3.1 - #compiling..............................................................
ruby-2.3.1 - #installing.........
ruby-2.3.1 - #making binaries executable..
Installed rubygems 2.5.1 is newer than 2.4.8 provided with installed ruby, skipping installation, use --force to force installation.
ruby-2.3.1 - #gemset created /usr/local/rvm/gems/ruby-2.3.1@global
ruby-2.3.1 - #importing gemset /usr/local/rvm/gemsets/global.gems...............................................
ruby-2.3.1 - #generating global wrappers........
ruby-2.3.1 - #gemset created /usr/local/rvm/gems/ruby-2.3.1
ruby-2.3.1 - #importing gemsetfile /usr/local/rvm/gemsets/default.gems evaluated to empty gem list
ruby-2.3.1 - #generating default wrappers........
ruby-2.3.1 - #adjusting #shebangs for (gem irb erb ri rdoc testrb rake).
Install of ruby-2.3.1 - #complete 
Ruby was built without documentation, to build it run: rvm docs generate-ri
You have new mail in /var/mail/kannan
Kannans-MacBook-Pro:BasecampPlus kannan$ clear

Kannans-MacBook-Pro:BasecampPlus kannan$ rvm list
'
rvm rubies

   ruby-2.0.0-p643 [ x86_64 ]
   ruby-2.2.4 [ x86_64 ]
 * ruby-2.3.0 [ x86_64 ]
=> ruby-2.3.1 [ x86_64 ]

# => - current
# =* - current && default
#  * - default

Kannans-MacBook-Pro:BasecampPlus kannan$ rvm use 2.3.1
Using /usr/local/rvm/gems/ruby-2.3.1
Kannans-MacBook-Pro:BasecampPlus kannan$ rails -v
Rails is not currently installed on this system. To get the latest version, simply type:

    $ sudo gem install rails

You can then rerun your "rails" command.
Kannans-MacBook-Pro:BasecampPlus kannan$ clear






















Kannans-MacBook-Pro:BasecampPlus kannan$ rvm use 2.3.1
Using /usr/local/rvm/gems/ruby-2.3.1
Kannans-MacBook-Pro:BasecampPlus kannan$ ruby -v
ruby 2.3.1p112 (2016-04-26 revision 54768) [x86_64-darwin15]
You have new mail in /var/mail/kannan
Kannans-MacBook-Pro:BasecampPlus kannan$ gem install rails
Fetching: i18n-0.7.0.gem (100%)
Successfully installed i18n-0.7.0
Fetching: thread_safe-0.3.5.gem (100%)
Successfully installed thread_safe-0.3.5
Fetching: tzinfo-1.2.2.gem (100%)
Successfully installed tzinfo-1.2.2
Fetching: concurrent-ruby-1.0.2.gem (100%)
Successfully installed concurrent-ruby-1.0.2
Fetching: activesupport-5.0.0.gem (100%)
Successfully installed activesupport-5.0.0
Fetching: rack-2.0.1.gem (100%)
Successfully installed rack-2.0.1
Fetching: rack-test-0.6.3.gem (100%)
Successfully installed rack-test-0.6.3
Fetching: mini_portile2-2.1.0.gem (100%)
Successfully installed mini_portile2-2.1.0
Fetching: pkg-config-1.1.7.gem (100%)
Successfully installed pkg-config-1.1.7
Fetching: nokogiri-1.6.8.gem (100%)
Building native extensions.  This could take a while...
Successfully installed nokogiri-1.6.8
Fetching: loofah-2.0.3.gem (100%)
Successfully installed loofah-2.0.3
Fetching: rails-html-sanitizer-1.0.3.gem (100%)
Successfully installed rails-html-sanitizer-1.0.3
Fetching: rails-dom-testing-2.0.1.gem (100%)
Successfully installed rails-dom-testing-2.0.1
Fetching: builder-3.2.2.gem (100%)
Successfully installed builder-3.2.2
Fetching: erubis-2.7.0.gem (100%)
Successfully installed erubis-2.7.0
Fetching: actionview-5.0.0.gem (100%)
Successfully installed actionview-5.0.0
Fetching: actionpack-5.0.0.gem (100%)
Successfully installed actionpack-5.0.0
Fetching: activemodel-5.0.0.gem (100%)
Successfully installed activemodel-5.0.0
Fetching: arel-7.0.0.gem (100%)
Successfully installed arel-7.0.0
Fetching: activerecord-5.0.0.gem (100%)
Successfully installed activerecord-5.0.0
Fetching: globalid-0.3.6.gem (100%)
Successfully installed globalid-0.3.6
Fetching: activejob-5.0.0.gem (100%)
Successfully installed activejob-5.0.0
Fetching: mime-types-data-3.2016.0521.gem (100%)
Successfully installed mime-types-data-3.2016.0521
Fetching: mime-types-3.1.gem (100%)
Successfully installed mime-types-3.1
Fetching: mail-2.6.4.gem (100%)
Successfully installed mail-2.6.4
Fetching: actionmailer-5.0.0.gem (100%)
Successfully installed actionmailer-5.0.0
Fetching: nio4r-1.2.1.gem (100%)
Building native extensions.  This could take a while...
Successfully installed nio4r-1.2.1
Fetching: websocket-extensions-0.1.2.gem (100%)
Successfully installed websocket-extensions-0.1.2
Fetching: websocket-driver-0.6.4.gem (100%)
Building native extensions.  This could take a while...
Successfully installed websocket-driver-0.6.4
Fetching: actioncable-5.0.0.gem (100%)
Successfully installed actioncable-5.0.0
Fetching: thor-0.19.1.gem (100%)
Successfully installed thor-0.19.1
Fetching: method_source-0.8.2.gem (100%)
Successfully installed method_source-0.8.2
Fetching: railties-5.0.0.gem (100%)
Successfully installed railties-5.0.0
Fetching: bundler-1.12.5.gem (100%)
Successfully installed bundler-1.12.5
Fetching: sprockets-3.6.2.gem (100%)
Successfully installed sprockets-3.6.2
Fetching: sprockets-rails-3.1.1.gem (100%)
Successfully installed sprockets-rails-3.1.1
Fetching: rails-5.0.0.gem (100%)
Successfully installed rails-5.0.0
37 gems installed
You have new mail in /var/mail/kannan
Kannans-MacBook-Pro:BasecampPlus kannan$ clear

You have new mail in /var/mail/kannan
Kannans-MacBook-Pro:BasecampPlus kannan$ rails -v
Could not find proper version of railties (4.2.6) in any of the sources
Run `bundle install` to install missing gems.

**Comment by kannannadarajan** [comment]
I haven't created any application so for just curious to see the rails version in my screen. 
In this case I cant run bundle install

**Comment by prakashmurthy** [comment]
I tried the same steps on my machine ( `rvm install 2.3.1`; `gem install rails`), and am getting the expected out put for `rails -v`. 

This seems to be more of an issue with your rvm/bundler setup. https://github.com/rails/rails/issues/24926#issuecomment-217756875 might help.

**Comment by rafaelfranca** [comment]
Yes, this seems to be a problem with rvm

**Comment by kannannadarajan** [comment]
@prakashmurthy and @rafaelfranca Thank you for pointing me the issue. 
Earlier my rvm version was 1.26.11, just updated it to 1.27.0, then reinstalled ruby 2.3.1 now everything seems fine. Very eager to use R5 for our new product.
