### ISSUE TITLE
Rails 5 - Rails g migration

### ISSUE THREAD

**Issue by sognatore24431** [rails/rails#25627]
*******_/gems/rb-inotify-0.9.7/lib/rb-inotify/watcher.rb:74:in `initialize': Invalid argument - Failed to watch
***_***/gems/activesupport-5.0.0/lib/active_support/locale": the given event mask contains no legal events; or fd is not an inotify file descriptor. (Errno::EINVAL)

**Comment by maclover7** [comment]
Can you create an executable test script using one of the templates [here](https://github.com/rails/rails/tree/master/guides/bug_report_templates), that would demonstrate the problem you are seeing, or provide more of the backtrace?

**Comment by electrodem** [comment]
I created a test application api without any additional gems......

I have that problem with: 

rails g migration 
rails g model
rails g scaffold 

Full stack: 

/home/user/.rvm/gems/ruby-2.2.2/gems/rb-inotify-0.9.7/lib/rb-inotify/watcher.rb:74:in `initialize': Invalid argument - Failed to watch "/home/user/.rvm/gems/ruby-2.2.2/gems/activesupport-5.0.0/lib/active_support/locale": the given event mask contains no legal events; or fd is not an inotify file descriptor. (Errno::EINVAL)
        from /home/user/.rvm/gems/ruby-2.2.2/gems/rb-inotify-0.9.7/lib/rb-inotify/notifier.rb:190:in `new'
        from /home/user/.rvm/gems/ruby-2.2.2/gems/rb-inotify-0.9.7/lib/rb-inotify/notifier.rb:190:in `watch'
        from /home/user/.rvm/gems/ruby-2.2.2/gems/rb-inotify-0.9.7/lib/rb-inotify/notifier.rb:204:in `watch'
        from /home/user/.rvm/gems/ruby-2.2.2/gems/listen-3.0.8/lib/listen/adapter/linux.rb:32:in `_configure'
        from /home/user/.rvm/gems/ruby-2.2.2/gems/listen-3.0.8/lib/listen/adapter/base.rb:45:in `block in configure'
        from /home/user/.rvm/gems/ruby-2.2.2/gems/listen-3.0.8/lib/listen/adapter/base.rb:40:in `each'
        from /home/user/.rvm/gems/ruby-2.2.2/gems/listen-3.0.8/lib/listen/adapter/base.rb:40:in `configure'
        from /home/user/.rvm/gems/ruby-2.2.2/gems/listen-3.0.8/lib/listen/adapter/base.rb:63:in `start'
        from /home/user/.rvm/gems/ruby-2.2.2/gems/listen-3.0.8/lib/listen/backend.rb:28:in `start'
        from /home/user/.rvm/gems/ruby-2.2.2/gems/listen-3.0.8/lib/listen/listener.rb:67:in `block in <class:Listener>'
        from /home/user/.rvm/gems/ruby-2.2.2/gems/listen-3.0.8/lib/listen/fsm.rb:120:in `instance_eval'
        from /home/user/.rvm/gems/ruby-2.2.2/gems/listen-3.0.8/lib/listen/fsm.rb:120:in `call'
        from /home/user/.rvm/gems/ruby-2.2.2/gems/listen-3.0.8/lib/listen/fsm.rb:91:in `transition_with_callbacks!'
        from /home/user/.rvm/gems/ruby-2.2.2/gems/listen-3.0.8/lib/listen/fsm.rb:57:in `transition'
        from /home/user/.rvm/gems/ruby-2.2.2/gems/listen-3.0.8/lib/listen/listener.rb:90:in `start'
        from /home/user/.rvm/gems/ruby-2.2.2/gems/activesupport-5.0.0/lib/active_support/evented_file_update_checker.rb:90:in `boot!'
        from /home/user/.rvm/gems/ruby-2.2.2/gems/activesupport-5.0.0/lib/active_support/evented_file_update_checker.rb:61:in `initialize'
        from /home/user/.rvm/gems/ruby-2.2.2/gems/activesupport-5.0.0/lib/active_support/i18n_railtie.rb:59:in `new'
        from /home/user/.rvm/gems/ruby-2.2.2/gems/activesupport-5.0.0/lib/active_support/i18n_railtie.rb:59:in `initialize_i18n'
        from /home/user/.rvm/gems/ruby-2.2.2/gems/activesupport-5.0.0/lib/active_support/i18n_railtie.rb:15:in `block in <class:Railtie>'
        from /home/user/.rvm/gems/ruby-2.2.2/gems/activesupport-5.0.0/lib/active_support/lazy_load_hooks.rb:36:in `call'
        from /home/user/.rvm/gems/ruby-2.2.2/gems/activesupport-5.0.0/lib/active_support/lazy_load_hooks.rb:36:in `execute_hook'
        from /home/user/.rvm/gems/ruby-2.2.2/gems/activesupport-5.0.0/lib/active_support/lazy_load_hooks.rb:45:in `block in run_load_hooks'
        from /home/user/.rvm/gems/ruby-2.2.2/gems/activesupport-5.0.0/lib/active_support/lazy_load_hooks.rb:44:in `each'
        from /home/user/.rvm/gems/ruby-2.2.2/gems/activesupport-5.0.0/lib/active_support/lazy_load_hooks.rb:44:in `run_load_hooks'
        from /home/user/.rvm/gems/ruby-2.2.2/gems/railties-5.0.0/lib/rails/application/finisher.rb:65:in `block in <module:Finisher>'
        from /home/user/.rvm/gems/ruby-2.2.2/gems/railties-5.0.0/lib/rails/initializable.rb:30:in `instance_exec'
        from /home/user/.rvm/gems/ruby-2.2.2/gems/railties-5.0.0/lib/rails/initializable.rb:30:in `run'
        from /home/user/.rvm/gems/ruby-2.2.2/gems/railties-5.0.0/lib/rails/initializable.rb:55:in `block in run_initializers'
        from /home/user/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/tsort.rb:226:in `block in tsort_each'
        from /home/user/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/tsort.rb:348:in `block (2 levels) in each_strongly_connected_component'
        from /home/user/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/tsort.rb:429:in `each_strongly_connected_component_from'
        from /home/user/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/tsort.rb:347:in `block in each_strongly_connected_component'
        from /home/user/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/tsort.rb:345:in `each'
        from /home/user/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/tsort.rb:345:in `call'
        from /home/user/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/tsort.rb:345:in `each_strongly_connected_component'
        from /home/user/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/tsort.rb:224:in `tsort_each'
        from /home/user/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/tsort.rb:203:in `tsort_each'
        from /home/user/.rvm/gems/ruby-2.2.2/gems/railties-5.0.0/lib/rails/initializable.rb:54:in `run_initializers'
        from /home/user/.rvm/gems/ruby-2.2.2/gems/railties-5.0.0/lib/rails/application.rb:352:in `initialize!'
        from /mnt/f/work/myp/mobileauth/api-app/config/environment.rb:5:in `<top (required)>'
        from /home/user/.rvm/gems/ruby-2.2.2/gems/railties-5.0.0/lib/rails/application.rb:328:in `require'
        from /home/user/.rvm/gems/ruby-2.2.2/gems/railties-5.0.0/lib/rails/application.rb:328:in `require_environment!'
        from /home/user/.rvm/gems/ruby-2.2.2/gems/railties-5.0.0/lib/rails/commands/commands_tasks.rb:157:in `require_application_and_environment!'
        from /home/user/.rvm/gems/ruby-2.2.2/gems/railties-5.0.0/lib/rails/commands/commands_tasks.rb:143:in `generate_or_destroy'
        from /home/user/.rvm/gems/ruby-2.2.2/gems/railties-5.0.0/lib/rails/commands/commands_tasks.rb:60:in `generate'
        from /home/user/.rvm/gems/ruby-2.2.2/gems/railties-5.0.0/lib/rails/commands/commands_tasks.rb:49:in `run_command!'
        from /home/user/.rvm/gems/ruby-2.2.2/gems/railties-5.0.0/lib/rails/commands.rb:18:in `<top (required)>'
        from bin/rails:4:in `require'
        from bin/rails:4:in `<main>'


i'm founded that error message in rb-inotify:

https://github.com/nex3/rb-inotify/blob/master/lib/rb-inotify/watcher.rb#L80

" the given event mask contains no legal events; or fd is not an inotify file descriptor."

**Comment by prathamesh-sonpatki** [comment]
This seems to third party issue related to rb-inotify.
