### ISSUE TITLE
5.0 Upgrade Guide should include support dropping for rails-deprecated_sanitizer

### ISSUE THREAD

**Issue by connorshea** [rails/rails#25629]
[`rails-deprecated_sanitizer`'s README](https://github.com/rails/rails-deprecated_sanitizer) says it will be supported until Rails 5.0, which is now released. 

The [`activerecord-deprecated-finders` gem had a mention in the Rails 5 upgrade guide](http://edgeguides.rubyonrails.org/upgrading_ruby_on_rails.html#removed-support-for-activerecord-deprecated-finders-gem), shouldn't this get one too?

**Comment by maclover7** [comment]
@connorshea Can you submit a PR to fix this?

**Comment by connorshea** [comment]
@maclover7 sure :)
