### ISSUE TITLE
activesupport 5.0 no longer installs on osx el capitan due to ruby 2.2.2 dependency

### ISSUE THREAD

**Issue by emmby** [rails/rails#25637]
### Steps to reproduce

```
Mac-Pro:~ build$ sudo gem install activesupport
ERROR:  Error installing activesupport:
	activesupport requires Ruby version >= 2.2.2.
```

### Expected behavior
Should be able to install activesupport on a mac without introducing a new version of ruby.

### System configuration
**Rails version**:
N/A

**Ruby version**:
ruby 2.0.0p648 (2015-12-16 revision 53162) [universal.x86_64-darwin15]

### Workaround
Installing activesupport 4.2.6 instead of 5.0.0 works fine:
```
Mac-Pro:~ build$ sudo gem install activesupport -v 4.2.6
Fetching: activesupport-4.2.6.gem (100%)
Successfully installed activesupport-4.2.6
Parsing documentation for activesupport-4.2.6
unable to convert "\x84" from ASCII-8BIT to UTF-8 for lib/active_support/values/unicode_tables.dat, skipping
Installing ri documentation for activesupport-4.2.6
1 gem installed
```

**Comment by rafaelfranca** [comment]
Yes, this is by design. Rails 5 only support ruby greater of equal to 2.2.2
