### ISSUE TITLE
config.force_ssl ignores hsts preload option

### ISSUE THREAD

**Issue by rbrownejr** [rails/rails#25630]
### Steps to reproduce
In your conf/environments/production.rb set config.force_ssl = true and set config.ssl_options = { hsts: {expires: 15552000, subdomains: true, preload: true} }

Launched app in production mode and did a curl -v https://mydomain.com.

(Guidelines for creating a bug report are [available
here](http://guides.rubyonrails.org/contributing_to_ruby_on_rails.html#creating-a-bug-report))

### Expected behavior
Tell us what should happen

The returning Strict-Transport-Security header should read "max-age=15552000; includeSubDomains; preload"

### Actual behavior
Tell us what happens instead

Instead you get "max-age=15552000; includeSubDomains"

It appears config.force_ssl is ignoring the preload when it's creating the header.

### System configuration
**Rails version**:
4.2.6

**Ruby version**:
2.3.1p112

**Comment by rafaelfranca** [comment]
This is not supported in Rails 4.2 yet. But it is supported in Rails 5.0
