### ISSUE TITLE
"Getting Started" guide commands for migration / routes

### ISSUE THREAD

**Issue by alexpetroni** [rails/rails#25648]
### Steps to reproduce
On 5 Getting Up and Running wrote: run  $bin/rails routes
Result "Error: Command 'routes' not recognized"

Should be $bin/rake routes

On 5.5 Running a Migration wrote: run $ bin/rails db:migrate
Result: Command 'db:migrate' not recognized

should be $bin/rake db:migrate

I am new on Rails and trying to learn using this guide.

### System configuration
**Rails version**: 4.2.6

**Ruby version**:2.3.1p112

**Comment by prathamesh-sonpatki** [comment]
Rails guides are released with every major release of Rails. The current guides at http://guides.rubyonrails.org/getting_started.html are for Rails 5.0 only and the command work in Rails 5.

As you are using older Rails version, please use http://guides.rubyonrails.org/v4.2/getting_started.html.

Thanks 💚

**Comment by yongololo** [comment]
run : bundle exec rake db:migrate
