### ISSUE TITLE
Can't get value of cookies in test file

### ISSUE THREAD

**Issue by hw676018683** [rails/rails#25641]
### Steps to reproduce
I write tests for session_helper，the method is like:
```
def remember_me
   cookies.permanent.signed[:remember_tokens] = {
      value: ‘Something’,
      httponly: true
    }
end
```
but in session_helper_spec:
```
cookies.signed[:ns_remember_tokens] # => nil
```

### System configuration
**Rails version**: 5.0.0

**Ruby version**: 2.2.3

**Comment by prathamesh-sonpatki** [comment]
You method is assigning `cookies.permanent.signed[:remember_tokens]` and you are fetching `cookies.signed[:ns_remember_tokens]`. The name of the cookie that is being fetched is different.

I am giving it a close. Please provide a sample application if the issue persists and I will reopen.

Thanks 💚

**Comment by hw676018683** [comment]
Sorry, that is a typo.
I use rspec. In session_helper_spec, I use `helper.remember_me` to call #remember_me.
Using `helper.cookies.signed[:remember_tokens]` can get correct value. 
Not `cookies.signed[:remember_tokens]`.

**Comment by rickyc** [comment]
I'm running into the same issue. Created a [sample app](https://github.com/rickyc/rails-session-bug) with a test. It works on rails 4.2.6, however, it fails on rails 5.0.0.

Sorry for not splitting the commits 😞 , but the two files to look at are here.

https://github.com/rickyc/rails-session-bug/blob/master/session-bug-rails-5/app/controllers/application_controller.rb

https://github.com/rickyc/rails-session-bug/blob/master/session-bug-rails-5/test/controllers/application_controller_test.rb

**Comment by rickyc** [comment]
It looks like you need to grab the cookies from the controller first.

```rb
  cookies = controller.send :cookies
```
