### ISSUE TITLE
Generators not working without Spring starting

### ISSUE THREAD

**Issue by qiheme** [rails/rails#25651]
### Steps to reproduce
1. In the terminal, create a new rails 5.0.0 project `rails new <project_name>`
2. Try to generate a new model or controller with the `rails generate` command in the terminal: `rails generate model <model_name>` or `rails generate controller <controller_name>`

(Guidelines for creating a bug report are [available
here](http://guides.rubyonrails.org/contributing_to_ruby_on_rails.html#creating-a-bug-report))
### Expected behavior

Your template model and/or controller should generate as normal
### Actual behavior

Getting the below error:

```
/Users/qiheme001c/Google Drive/Developer/workspace/personal_projects/gotham_metro/vendor/bundle/gems/spring-1.7.2/lib/spring/client/run.rb:76:in `spawn': No such file or directory - /Users/qiheme001c/Google (Errno::ENOENT)
    from /Users/qiheme001c/Google Drive/Developer/workspace/personal_projects/gotham_metro/vendor/bundle/gems/spring-1.7.2/lib/spring/client/run.rb:76:in `boot_server'
    from /Users/qiheme001c/Google Drive/Developer/workspace/personal_projects/gotham_metro/vendor/bundle/gems/spring-1.7.2/lib/spring/client/run.rb:56:in `cold_run'
    from /Users/qiheme001c/Google Drive/Developer/workspace/personal_projects/gotham_metro/vendor/bundle/gems/spring-1.7.2/lib/spring/client/run.rb:33:in `rescue in call'
    from /Users/qiheme001c/Google Drive/Developer/workspace/personal_projects/gotham_metro/vendor/bundle/gems/spring-1.7.2/lib/spring/client/run.rb:30:in `call'
    from /Users/qiheme001c/Google Drive/Developer/workspace/personal_projects/gotham_metro/vendor/bundle/gems/spring-1.7.2/lib/spring/client/command.rb:7:in `call'
    from /Users/qiheme001c/Google Drive/Developer/workspace/personal_projects/gotham_metro/vendor/bundle/gems/spring-1.7.2/lib/spring/client/rails.rb:24:in `call'
    from /Users/qiheme001c/Google Drive/Developer/workspace/personal_projects/gotham_metro/vendor/bundle/gems/spring-1.7.2/lib/spring/client/command.rb:7:in `call'
    from /Users/qiheme001c/Google Drive/Developer/workspace/personal_projects/gotham_metro/vendor/bundle/gems/spring-1.7.2/lib/spring/client.rb:30:in `run'
    from /Users/qiheme001c/Google Drive/Developer/workspace/personal_projects/gotham_metro/vendor/bundle/gems/spring-1.7.2/bin/spring:49:in `<top (required)>'
    from /Users/qiheme001c/Google Drive/Developer/workspace/personal_projects/gotham_metro/vendor/bundle/gems/spring-1.7.2/lib/spring/binstub.rb:11:in `load'
    from /Users/qiheme001c/Google Drive/Developer/workspace/personal_projects/gotham_metro/vendor/bundle/gems/spring-1.7.2/lib/spring/binstub.rb:11:in `<top (required)>'
    from /usr/local/var/rbenv/versions/2.2.2/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
    from /usr/local/var/rbenv/versions/2.2.2/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
    from /Users/qiheme001c/Google Drive/Developer/workspace/personal_projects/gotham_metro/bin/spring:13:in `<top (required)>'
    from bin/rails:3:in `load'
    from bin/rails:3:in `<main>'
```

To remedy the issue, I had to `gem install spring` separately and run spring (`spring start`) to be able to use the generate commands properly. Note, there is no mention in the Rails Guides 5.0.0 of needing to `spring start` in order to generate models and/or controllers.
### System configuration

**Rails version**: 5.0.0

**Ruby version**: 2.2.2p95

**Comment by maclover7** [comment]
Hmm, can you post your full terminal backtrace from when you ran `rails new` to when the error started?

**Comment by prakashmurthy** [comment]
What OS is this? 

Looks like the space in `Google Drive` in the file path is causing the error; the script is trying to look for  `/Users/qiheme001c/Google` directory and throwing a `No such file or directory - /Users/qiheme001c/Google` message.

**Comment by qiheme** [comment]
@prakashmurthy nice call, renaming the `Google Drive` directory to `Google_Drive` did the trick...although the Google Drive application wasn't too happy ¯\_(ツ)_/¯ thanks both for the assistance!

cc: @maclover7
