### ISSUE TITLE
Functional testing guides reference to @controller

### ISSUE THREAD

**Issue by brandonhilkert** [rails/rails#25662]
### Steps to reproduce

The functional test guides reference having access to `@controller`, `@request`, and `@response`.

<img width="496" alt="screen shot 2016-07-02 at 10 11 08 pm" src="https://cloud.githubusercontent.com/assets/744212/16543428/e891c460-40a1-11e6-8783-e4ef61f39eeb.png">

However the the majority of the section references to using Integration tests for controller tests, which I don't think has access to those, right?

<img width="661" alt="screen shot 2016-07-02 at 10 11 38 pm" src="https://cloud.githubusercontent.com/assets/744212/16543431/fa4b921c-40a1-11e6-93d3-a6bb5849eccf.png">

### Expected behavior

Maybe a clarification around when these ivars are available...

**Comment by vipulnsward** [comment]
Fixed in https://github.com/rails/docrails/commit/5324665e9f8a6104c79c7798b3e264db2b42c6d7

http://take.ms/4baJj
