### ISSUE TITLE
What does "PG" mean in AR::Attributes documentation?

### ISSUE THREAD

**Issue by will-in-wi** [rails/rails#25660]
In http://api.rubyonrails.org/classes/ActiveRecord/Attributes/ClassMethods.html, it has the following line:

> `array` (PG only) specifies that the type should be an array

What does PG mean? I can't find any reference to the initials anywhere else. My best guess is that the `array` param only applies to attributes which are not backed by a database column.

I'm happy to make a PR to clarify the docs if someone would explain it to me.

Thanks!

**Comment by will-in-wi** [comment]
Appears to have been introduced in 8c752c7a. @sgrif

**Comment by will-in-wi** [comment]
Ah, Postgres? I haven't had the opportunity to use it, so it didn't spring to mind. I'll throw together a doc PR to clarify.

**Comment by sgrif** [comment]
We should probably say PostgreSQL explicitly. Feel free to open  a PR

**Comment by prathamesh-sonpatki** [comment]
Fixed in https://github.com/rails/rails/issues/25661
