### ISSUE TITLE
number_to_human tries to use larger units than provided

### ISSUE THREAD

**Issue by daniel-rikowski** [rails/rails#25664]
### Steps to reproduce

```
number_to_human(1_000_000, units: { unit: 'meter', thousand: 'kilometer' })
```

This should return "1000 kilometer", as it did in Rails 4.x. Instead it returns "1" (i.e. no unit) in Rails 5

Runnable gist: https://gist.github.com/daniel-rikowski/3fb29004560fae2ab7c08ddc2df8c0ef
### Expected behavior

When `number_to_human` receives a list of units it should only use the units given and not larger ones.
### Actual behavior

Instead it tries to use the best machting unit, even if it wasn't provided. For a hash parameter this results in an empty unit, for a I18n scope parameter this results in a lookup exception.
### System configuration

**Rails version**: 5.0
### Remarks
- I want to use this to display distances on a map, where even large numbers like "6371 km" are more favorable than "6 million meter" or "6 thousand kilometer"
- I think the cause was PR https://github.com/rails/rails/pull/20872: First `calculate_exponent(units)` finds the largest exponent matching the given units, but then the rounding loop (lines 23-26) increases the exponent where it possibly exceeds the given units and their exponents.

**Comment by prakashmurthy** [comment]
Reproducible from the console:

#### Rails 4.2.5.2

    $ rails c
    Loading development environment (Rails 4.2.5.2)
    2.3.1 :001 > ActionView::Base.new.number_to_human(1_000_000, units: { unit: 'meter', thousand: 'kilometer' })
    => "1000 kilometer"

#### Rails 5.0.0

    $ rails c
    Loading development environment (Rails 5.0.0)
    2.3.1 :001 > ActionView::Base.new.number_to_human(1_000_000, units: { unit: 'meter', thousand: 'kilometer' })
     => "1"

**Comment by maclover7** [comment]
Confirming based on a `git bisect` that 597a9276671f5d7884a0ee1a617656dd5ee4b0ea is the issue.

**Comment by sai29** [comment]
@maclover7 The PR submitted for this issue was not merged. Can I work on this and submit a PR?

**Comment by maclover7** [comment]
@sai29 Thank you for offering to fix this! ping @mrgilman do you think you can get your PR ready to be merged in, or are you okay if @sai29 starts working on a fix for this?

**Comment by mrgilman** [comment]
@sai29 go for it, sorry I haven't had time to get back to this :/
