### ISSUE TITLE
attr_accessor not accessible when using deliver_later

### ISSUE THREAD

**Issue by shaktik1989** [rails/rails#25666]
### Steps to reproduce
When I try to send the email with deliver_later than on the email template attr_accessor is nil.

I am using devise_invitable to invite users to app, for that I want to add custom message on the email. so my code looks like this.
```

#user.rb
attr_accessor :message

def self.invite(emails, message)
  User.invite!({email: email}) do |user|
    user.message = message
  end
end

#here I am overriding devise_invitable method to send mails later
def send_devise_notification(notification, *args)
  devise_mailer.send(notification, self, *args).deliver_later
end

#users_controller.rb
def invite_user
  User.invite(params[:email], params[:message]) 
end    

#invitation_instructions.html.erb
<% if @resource.message %>
  <p><%= @resource.message %></p>
<% end %>    
```

When I am using only deliver then message is displaying on mailer, but when I use deliver_later attr_accessor in nil on the mailer view. 

### Expected behavior
attr_accessor should be available on the email template when using deliver_later.

### Actual behavior
Tell us what happens instead

### System configuration
**Rails version**: 4.2.6

**Ruby version**: 2.2.1p85

**Comment by maclover7** [comment]
Hmm, this seems like a more devise_invitable specific question than a bug report. Please use the mailing list or StackOverflow for questions/help, or [devise_invitable](https://github.com/scambra/devise_invitable)'s issue tracker where a wider community will be able to help you. We reserve the issues tracker for Rails issues only.

**Comment by s-andy** [comment]
Those, who do not use devise_invitable, also have this problem with `attr_accessor`, so I'm not sure, why the issue was closed...
