### ISSUE TITLE
ActionController::Live does not stream on rails 5

### ISSUE THREAD

**Issue by grosser** [rails/rails#25672]
```Ruby
class StreamsController < ActionController::Base
  include ActionController::Live

  def show
    response.headers['Content-Type'] = 'text/event-stream'
    10.times {
      puts 1
      response.stream.write "This is a test Message\n"
      sleep 1
    }
    response.stream.close
  end
end
```

+ 

```
curl -i http://localhost:3000/streams/1
```

-> no output from curl ... puts 1 shows in the server log though

on rails 5.0.0 / ruby 2.2.3 / puma 3.4.0

works fine on rails 4.2 (instant response header + streamed body)
no output on rails 5.0.0 ... no header and no streamed messages

trying to upgrade our repo here https://github.com/zendesk/samson/pull/972

only remaining issue for rails 5 ...

seeing the same behavior in the tests (ControllerTest) ... so I think this is something bad in rails 5

**Comment by maclover7** [comment]
Thank you for reporting this! Would you be willing to do a `git bisect` to figure out where this bad behavior was introduced?

**Comment by maclover7** [comment]
Hmm, on a local test, [this reproduction script](https://gist.github.com/maclover7/043b3a2acadda29fb554ce1050ea768e) passes for me, and works fine.

Here's the output from when I run `curl`:

```
Jonathans-MacBook-Pro:~ jon$ curl -i http://localhost:9292/
HTTP/1.1 200 OK
Content-Type: text/event-stream
Cache-Control: no-cache
X-Request-Id: 452c829a-7ea9-4148-814c-f241a3754ff3
X-Runtime: 0.001509
Transfer-Encoding: chunked

This is a test Message
This is a test Message
This is a test Message
This is a test Message
This is a test Message
This is a test Message
This is a test Message
This is a test Message
This is a test Message
This is a test Message
Jonathans-MacBook-Pro:~ jon$ 
```

Can you create an executable test script using one of the templates [here](https://github.com/rails/rails/tree/master/guides/bug_report_templates), that would demonstrate the problem you are seeing?

**Comment by grosser** [comment]
yes, works on a clean example app ... must be some gems interfering, will update shortly

**Comment by maclover7** [comment]
👍 no problem, dependencies acting a little weird during major rails upgrades is expected :)

**Comment by grosser** [comment]
the winner is `active_model_serializers` 0.9.5 ... updating to 0.10.1 fixes it ... that was hard to find :D 

not sure if anything can be done about old gems breaking rails ... already changed it's versioning policy so that newer versions rails are not automatically supported ... I'll close this ... hope it helps some other lost soul :D

**Comment by maclover7** [comment]
👍 thanks for opening! Marking as a third party issue.
