### ISSUE TITLE
Missing json in default Gemfile

### ISSUE THREAD

**Issue by waghanza** [rails/rails#25676]
Hi all,

When I try to create a **new** project with last stable release  and to execute

~~~rails
bundle exec rake db:create
~~~

I have

~~~ruby
/home/waghanza/.gem/ruby/2.3.0/gems/activesupport-5.0.0/lib/active_support/core_ext/object/json.rb:2:in `require': cannot load such file -- json (LoadError)
	from /home/waghanza/.gem/ruby/2.3.0/gems/activesupport-5.0.0/lib/active_support/core_ext/object/json.rb:2:in `<top (required)>'
	from /home/waghanza/.gem/ruby/2.3.0/gems/activesupport-5.0.0/lib/active_support/core_ext/object.rb:11:in `require'
	from /home/waghanza/.gem/ruby/2.3.0/gems/activesupport-5.0.0/lib/active_support/core_ext/object.rb:11:in `<top (required)>'
	from /home/waghanza/.gem/ruby/2.3.0/gems/railties-5.0.0/lib/rails/configuration.rb:2:in `require'
	from /home/waghanza/.gem/ruby/2.3.0/gems/railties-5.0.0/lib/rails/configuration.rb:2:in `<top (required)>'
	from /home/waghanza/.gem/ruby/2.3.0/gems/railties-5.0.0/lib/rails/railtie/configuration.rb:1:in `require'
	from /home/waghanza/.gem/ruby/2.3.0/gems/railties-5.0.0/lib/rails/railtie/configuration.rb:1:in `<top (required)>'
	from /home/waghanza/.gem/ruby/2.3.0/gems/railties-5.0.0/lib/rails/railtie.rb:216:in `require'
	from /home/waghanza/.gem/ruby/2.3.0/gems/railties-5.0.0/lib/rails/railtie.rb:216:in `config'
	from /home/waghanza/.gem/ruby/2.3.0/gems/railties-5.0.0/lib/rails/railtie.rb:122:in `config'
	from /home/waghanza/.gem/ruby/2.3.0/gems/activesupport-5.0.0/lib/active_support/i18n_railtie.rb:7:in `<class:Railtie>'
	from /home/waghanza/.gem/ruby/2.3.0/gems/activesupport-5.0.0/lib/active_support/i18n_railtie.rb:6:in `<module:I18n>'
	from /home/waghanza/.gem/ruby/2.3.0/gems/activesupport-5.0.0/lib/active_support/i18n_railtie.rb:5:in `<top (required)>'
	from /home/waghanza/.gem/ruby/2.3.0/gems/activesupport-5.0.0/lib/active_support/railtie.rb:2:in `require'
	from /home/waghanza/.gem/ruby/2.3.0/gems/activesupport-5.0.0/lib/active_support/railtie.rb:2:in `<top (required)>'
	from /home/waghanza/.gem/ruby/2.3.0/gems/railties-5.0.0/lib/rails.rb:14:in `require'
	from /home/waghanza/.gem/ruby/2.3.0/gems/railties-5.0.0/lib/rails.rb:14:in `<top (required)>'
	from /usr/local/share/gems/gems/bundler-1.12.5/lib/bundler/runtime.rb:86:in `require'
	from /usr/local/share/gems/gems/bundler-1.12.5/lib/bundler/runtime.rb:86:in `block (2 levels) in require'
	from /usr/local/share/gems/gems/bundler-1.12.5/lib/bundler/runtime.rb:81:in `each'
	from /usr/local/share/gems/gems/bundler-1.12.5/lib/bundler/runtime.rb:81:in `block in require'
	from /usr/local/share/gems/gems/bundler-1.12.5/lib/bundler/runtime.rb:70:in `each'
	from /usr/local/share/gems/gems/bundler-1.12.5/lib/bundler/runtime.rb:70:in `require'
	from /usr/local/share/gems/gems/bundler-1.12.5/lib/bundler/inline.rb:60:in `gemfile'
	from /tmp/test.rb:8:in `<main>'
~~~

This error could be reproducible with
~~~ruby
begin
  require 'bundler/inline'
rescue LoadError => e
  $stderr.puts 'Bundler version 1.10 or later is required. Please update your Bundler'
  raise e
end

gemfile(true) do
  source 'https://rubygems.org'
  gem "rails", ">= 5.0.0.rc2", "< 5.1"
end
~~~

I'm using `ruby 2.3.1p112 (2016-04-26 revision 54768) [x86_64-linux]`.

**Comment by waghanza** [comment]
I have to **manually** add the **gem** `json` in my `Gemfile`

**Comment by rafaelfranca** [comment]
Which is your Linux distribution?

**Comment by rafaelfranca** [comment]
Cross posting from #25686:

I know that fedora doesn't build some default gems. json is included in Ruby 2.3.1 as you can see here https://github.com/ruby/ruby/tree/v2_3_1/ext/json. If it is a compiled version either rvm is not compiling ruby with json or there was a bug in the compilation.

**Comment by waghanza** [comment]
@rafaelfranca this command `echo "p 'foo'" | ./ruby-mri -rjson` should not be working, if **json** supported from fedora, no ?

**Comment by rafaelfranca** [comment]
not saying that json is not supported but that the maintainer of the ruby package from fedora was complaining about our decision to use the built-in gems because fedora doesn't include the built-in gems, not sure if it is still the case. But if `echo "p 'foo'" | ./ruby-mri -rjson` is working to you so you should not get that error since json is there.

**Comment by waghanza** [comment]
However, I still have this error even with a fresh install on `Docker`.
I can't understand where the bug is

**Comment by rafaelfranca** [comment]
Not sure what is wrong but this doesn't seems to be an issue with Rails. It may be an issue with bundler/rubygems but if you ruby installation has json installed (and it should has) rails is doing to correct thing.

Are you able to reproduce this without Rails in the equation just with bundler and requiring json?
Are you able to reproduce this

**Comment by waghanza** [comment]
I am not able to reproduce this error

With

~~~ruby
begin
  require 'bundler/inline'
rescue LoadError => e
  $stderr.puts 'Bundler version 1.10 or later is required. Please update your Bundler'
  raise e
end

require "json"

data = {foo: :bar}
p data.to_json
~~~

on fresh install

~~~dockerfile
FROM fedora:latest
RUN dnf -y update
RUN dnf -y install ruby{,-devel} wget @development-tools libyaml-devel json-devel @rpm-development-tools
RUN gem update --system
RUN gem update
RUN gem install bundler
RUN wget -O /tmp/test.rb https://gist.githubusercontent.com/anonymous/21a59a87af301366ae8ee60f4ab84338/raw/c78703a1aac138f4d343b2d0e37ba740424366fd
RUN ruby /tmp/test.rb
~~~

I have no error using `json` features.

**Comment by rafaelfranca** [comment]
Try:

```
begin
  require 'bundler/setup'
rescue LoadError => e
  $stderr.puts 'Bundler version 1.10 or later is required. Please update your Bundler'
  raise e
end

require "json"

data = {foo: :bar}
p data.to_json
```

**Comment by jrafanie** [comment]
@waghanza I'm taking a guess... but if you want to use ruby from rpm, you need to use each of ruby/rubygems/bundler from rpm so they all work well together.

Therefore, you might have to add rubygem-bundler to your `dnf -y install ...` command instead of using `gem install bundler`.  I'd also remove the `gem update --system` since you'll be getting rubygems updates from rpm.

Possibly related: https://github.com/bundler/bundler/issues/1960

**Comment by waghanza** [comment]
@rafaelfranca this solution work on `debain` **sid**, `ubuntu` **xenial` and `fedora` 24. thanks

**Comment by rafaelcastellar** [comment]
Hi! I've just start learning Ruby. As I installed I  got this same situation. I'm using Fedora 24.
I'd like to know how was the solution you use to fix it, @waghanza . I could not follow it here.

Tks!

**Comment by waghanza** [comment]
@rafaelcastellar I have fixed it with 
~~~ruby
begin
  require 'bundler/setup'
rescue LoadError => e
  $stderr.puts 'Bundler version 1.10 or later is required. Please update your Bundler'
  raise e
end

require "json"

data = {foo: :bar}
p data.to_json
~~~

as @rafaelfranca suggested

However, I'm trying to understand why `require "json"` has to be here (issue on **fedora** only)

**Comment by rafaelcastellar** [comment]
But where should I put this fix? That's the point I didn't understand.. :)

Tks

**Comment by jrafanie** [comment]
I wonder if rack's change [here to remove json as a dependency](https://github.com/rack/rack/pull/1011)  might be involved.  Before that change, rack as a dependency of rails would cause the json gem to be installed and required by bundler.  Now, you have to add json to your Gemfile if you want an updated one and/or want it auto-required by bundler. 

Note, with chruby/ruby-install on OSX with ruby 2.2.5, I have to `require 'json'` or `require 
'active_support/json'` to be able to call `.to_json`.

**Comment by waghanza** [comment]
@rafaelcastellar the fix is to `require` **bundler/setup** instead of **bundler/inline**

**Comment by rafaelcastellar** [comment]
Thanks @waghanza ! I have not added the "gem 'json'" in my GemFile.

Now it's ok!
