### ISSUE TITLE
Use the HOST environment variable for rails server

### ISSUE THREAD

**Issue by mahnunchik** [rails/rails#25677]
Allow the server `host` to be set with the `HOST` environment variable. #21267

```
$ HOST=0.0.0.0 PORT=8080 rails server
should be similar
$ rails server -p 8080 -b 0.0.0.0
```

### System configuration
**Rails version**: Rails 5.0.0.rc1

**Ruby version**: ruby 2.3.0p0 (2015-12-25 revision 53290) [x86_64-linux]

**Comment by maclover7** [comment]
Can you open up a PR to add this, we can continue the discussion there. :)

**Comment by mahnunchik** [comment]
@maclover7 PR https://github.com/rails/rails/pull/25688

**Comment by maclover7** [comment]
Closing since #25688 was merged in.
