### ISSUE TITLE
ActionCable.server.broadcast doesn't work in an ActiveJob

### ISSUE THREAD

**Issue by h8rry** [rails/rails#25674]
### Steps to reproduce
1. Try using `ActionCable.server.broadcast ` in an ActiveJob

### Expected behavior

`ActionCable.server.broadcast ` should work inside an ActiveJob

### Actual behavior

It doesn't work. But, it works normally in controllers

### System configuration
**Rails version**: 5.0.0

**Ruby version**: 2.3.1

**Comment by matthewd** [comment]
> It doesn't work.

That may not be quite enough information.

**Comment by mrigdon** [comment]
What our friend means by it doesn't work is "nothing happens". There's not really a better way to describe it.
