### ISSUE TITLE
DurationTest#test_iso8601_output_and_reparsing fails randomly

### ISSUE THREAD

**Issue by voxik** [rails/rails#25682]
### Steps to reproduce

It appears to fail randomly.

### Expected behavior

Test pass.

### Actual behavior
```
  1) Error:
DurationTest#test_iso8601_output_and_reparsing:
ArgumentError: invalid date
    /builddir/build/BUILD/rubygem-activesupport-5.0.0/usr/share/gems/gems/activesupport-5.0.0/lib/active_support/core_ext/date/calculations.rb:113:in `>>'
    /builddir/build/BUILD/rubygem-activesupport-5.0.0/usr/share/gems/gems/activesupport-5.0.0/lib/active_support/core_ext/date/calculations.rb:113:in `advance'
    /builddir/build/BUILD/rubygem-activesupport-5.0.0/usr/share/gems/gems/activesupport-5.0.0/lib/active_support/core_ext/time/calculations.rb:142:in `advance'
    /builddir/build/BUILD/rubygem-activesupport-5.0.0/usr/share/gems/gems/activesupport-5.0.0/lib/active_support/duration.rb:144:in `parse'
    /builddir/build/BUILD/rubygem-activesupport-5.0.0/usr/share/gems/gems/activesupport-5.0.0/test/core_ext/duration_test.rb:316:in `block in test_iso8601_output_and_reparsing'
    /builddir/build/BUILD/rubygem-activesupport-5.0.0/usr/share/gems/gems/activesupport-5.0.0/test/core_ext/duration_test.rb:315:in `each'
    /builddir/build/BUILD/rubygem-activesupport-5.0.0/usr/share/gems/gems/activesupport-5.0.0/test/core_ext/duration_test.rb:315:in `test_iso8601_output_and_reparsing'
```

### System configuration
**Rails version**:
Rails 5.0.0

**Ruby version**:
Ruby 2.3.1

**Comment by maclover7** [comment]
Can you please provide more information about how to reproduce this than "it appears to fail randomly."? 😬 😬  I haven't noticed this as being a flaky test on our CI system.

**Comment by voxik** [comment]
I am trying to update package for Fedora Rawhide, so I take the gem from RubyGems.org, add the test suite from the repository and execute the test suite via:

```
$ ruby -Ilib:test -e 'Dir.glob "./test/**/*_test.rb", &method(:require)'
```

and that is the result I (sometimes) get.

These are the gems (all coming from Fedora packages) I am using to execute the test suite (I am not using Bundler at all):

```
$ gem list

*** LOCAL GEMS ***

bigdecimal (1.2.8)
builder (3.2.2)
concurrent-ruby (1.0.0)
dalli (2.7.4)
i18n (0.7.0)
json (1.8.3)
minitest (5.8.4)
psych (2.0.17)
rack (2.0.1)
rdoc (4.2.2)
thread_safe (0.3.5)
tzinfo (1.2.2)
```

and this is the Ruby:

```
$ ruby -v
ruby 2.3.1p112 (2016-04-26 revision 54768) [x86_64-linux]

$ rpm -q ruby
ruby-2.3.1-56.fc25.x86_64
```

BTW I just noticed that AS enforces concurrent-ruby 1.0.2 if that might be the difference ...

**Comment by maclover7** [comment]
👍 can you try adding in the depended upon `concurrent-ruby` version, and check to see if any other dependencies are missing? In order to properly test Active Support, please make sure you have the proper dependencies installed 😬.

Going to close this as a non-issue, but more of an environment setup issue. If the weird errors prevail after doing some environment tweaking, happy to reopen. :)

**Comment by voxik** [comment]
Tested with the latest concurrent-ruby and no change :/

**Comment by voxik** [comment]
This is still an issue in AS 5.1.2:

https://kojipkgs.fedoraproject.org/work/tasks/4884/20484884/build.log
https://apps.fedoraproject.org/koschei/package/rubygem-activesupport?collection=f27

Actually, it was mentioned in #28463 that it fails on 32b, which might be the case.

These were the used dependencies:

ruby.i686 2.4.1-79.fc27
rubygem-minitest.noarch 5.10.2-100.fc27
