### ISSUE TITLE
Title for Action Cable guide not detected on site or Kindle

### ISSUE THREAD

**Issue by CodingItWrong** [rails/rails#25697]
### Steps to reproduce

- Got to http://guides.rubyonrails.org/action_cable_overview.html and note the page title
- Download the Guides in .mobi format from guides.rubyonrails.org
- View them in the Kindle app for Mac or iOS.
- Find the Action Cable section in the Contents

### Expected behavior
Expected the page title to be "Action Cable Overview"
- Expected the Kindle Action Cable section to be titled "Action Cable Overview".

### Actual behavior
- Page title is only Ruby on Rails Guides.
- Action Cable section is titled simply "Rails Guides"

<img width="460" alt="guide-browser" src="https://cloud.githubusercontent.com/assets/15832198/16583961/fb7ee47c-4286-11e6-884f-e601b9946db2.png">
<img width="480" alt="guides-mac" src="https://cloud.githubusercontent.com/assets/15832198/16583165/aaa18848-4281-11e6-881b-d871c8462272.png">
![guides-iphone](https://cloud.githubusercontent.com/assets/15832198/16583166/aaa4a794-4281-11e6-92e1-aa2fc48c1cbb.png)

### System configuration
**Rails version**: 5.0.0

**Ruby version**: n/a

**Comment by maclover7** [comment]
Closing in favor of #25698.
