### ISSUE TITLE
collection_singular_ids= crashes if a non-existing id is passed

### ISSUE THREAD

**Issue by bluehallu** [rails/rails#25719]
### Steps to reproduce

Have two models A B, where A has_many B. Open rails console with empty database, and run

A.create b_ids: [1,2,3]
### Expected behavior

ActiveRecordNotFound exception with a similar message as if you run A.find [1,2,3]

`ActiveRecord::RecordNotFound: Couldn't find all Bs with 'id': (1, 2, 3) (found 0 results, but was looking for 3)`
### Actual behavior

ActiveRecord gets nils for the non-existing ids, doesn't check for that, and then tries to save the association, resulting in:

`ActiveRecord::AssociationTypeMismatch: B(#70166005846320) expected, got NilClass(#70165971014200)`
### System configuration

**Rails version**:
5 RC3
**Ruby version**:
2.2.4

**Comment by rafaelfranca** [comment]
How it works in Rails 4.2?

I guess it is the same behavior. Setting the ids should not trigger any finder logic, the ids should go straight to the database even if the records doesn't exist.

Could you create a reproduction script with this template https://github.com/rails/rails/blob/master/guides/bug_report_templates/active_record_master.rb?

**Comment by bluehallu** [comment]
@rafaelfranca: are you sure? At the moment it does load those associated models. We're missing opportunity to run validations if it goes straight to database, plus it will produce foreign key violations. In my use case, the user is selecting on the UI from a checkbox list of possible associated records, then the UI submits that array as part of form. The problem is that if one of the options is deleted while the user is selecting, the above scenario is triggered.

**Comment by rafaelfranca** [comment]
Right, I'm just speculating 😄 . If you could provide a reproduction script it would be really useful.

**Comment by bluehallu** [comment]
There you go https://gist.github.com/bluehallu/32aa71baea5cb42b4a2a49720be08220

**Comment by bluehallu** [comment]
Ignore those PRs, my bad. Working on a proper PR.
