### ISSUE TITLE
`head` not working with certain statuses

### ISSUE THREAD

**Issue by marcinwyszynski** [rails/rails#25711]
### Steps to reproduce

Call `head` from the controller with one of the statuses `100..199, 204, 205, 304`.
### Expected behavior

`undefined method 'delete' for #<ActionDispatch::Http::Headers:0x0056361a5b7ba0>`
### Actual behavior

Return the correct HTTP status code.

The issue is that setting one of these statuses triggers [this code path](https://github.com/rails/rails/blob/4-2-7/actionpack/lib/action_controller/metal/head.rb#L37) which calls a non-existent method. 
### System configuration

**Rails version**: 4.2.6

**Ruby version**: 2.3.0

**Comment by prathamesh-sonpatki** [comment]
Can you create a reproducible script using https://github.com/rails/rails/blob/master/guides/bug_report_templates/action_controller_gem.rb ?

Thanks!

**Comment by maclover7** [comment]
@prathamesh-sonpatki We don't need a reproduction script -- the original description gives enough info.

@marcinwyszynski Can you open up a PR to add the `delete` method back in?

**Comment by marcinwyszynski** [comment]
@maclover7 Sure, I will. BTW I can't repro that with the script 😱

```rb
begin
  require 'bundler/inline'
rescue LoadError => e
  $stderr.puts 'Bundler version 1.10 or later is required. Please update your Bundler'
  raise e
end

gemfile(true) do
  source 'https://rubygems.org'
  # Activate the gem you are reporting the issue against.
  gem 'rails', '4.2.6'
end

require 'rack/test'
require 'action_controller/railtie'

class TestApp < Rails::Application
  config.root = File.dirname(__FILE__)
  config.session_store :cookie_store, key: 'cookie_store_key'
  secrets.secret_token    = 'secret_token'
  secrets.secret_key_base = 'secret_key_base'

  config.logger = Logger.new($stdout)
  Rails.logger  = config.logger

  routes.draw do
    get '/' => 'test#index'
  end
end

class TestController < ActionController::Base
  include Rails.application.routes.url_helpers

  def index
    head 204
  end
end

require 'minitest/autorun'

# Ensure backward compatibility with Minitest 4
Minitest::Test = MiniTest::Unit::TestCase unless defined?(Minitest::Test)

class BugTest < Minitest::Test
  include Rack::Test::Methods

  def test_returns_success
    get '/'
    assert last_response.status == 204
  end

  private
    def app
      Rails.application
    end
end
```

**Comment by marcinwyszynski** [comment]
And, looking at the history as far back as `4.0.0`, `ActionDispatch::Http::Headers` never had a `delete` method.

**Comment by rafaelfranca** [comment]
Hmmm, if you can't reproduce in the script is very likely it is something in your application causing that behavior.

**Comment by marcinwyszynski** [comment]
@rafaelfranca Yes, that's a fair assumption to make. I'll investigate further.

**Comment by why-el** [comment]
@marcinwyszynski did you end up investigating? Otherwise if it's not reproducible then this issue should be closed.
