### ISSUE TITLE
Possibility to limit available values for StringInquirer

### ISSUE THREAD

**Issue by hedgesky** [rails/rails#25715]
Wouldn't it be great if there is a possibility to limit available methods for instances of `StringInquirer`? Something like that:

```
inquirer = ActiveSupport::StringInquirer.new('environment', only: %w(development production))
inquirer.development? # false
inquirer.develompent? # raise an error (notice a typo)
```

From my point of view, it could help to immediately find typos in code if they occur.

**Comment by prathamesh-sonpatki** [comment]
There is already an PR which is trying to add a similar feature - https://github.com/rails/rails/pull/20943.

Closing this in favour of the PR. Thanks @hedgesky!
