### ISSUE TITLE
Unscoped messing up SQL query params in PostgreSQL adapter

### ISSUE THREAD

**Issue by chenasraf** [rails/rails#25712]
### Steps to reproduce
1. Access a model/relation
   
   ``` ruby
       people = Person #assume it might have a default_scope or previously applied scope
   ```
2. Use `unscope` to remove only some of the previous scope
   
   ``` ruby
   people = Person.unscope(where: [:deleted, :archived])
   # or
   people = Person.unscope(where: :deleted).unscope(where: :archived)
   ```
3. Add where condition using one of the previously removed scope keys
   
   ``` ruby
   people = Person.unscope(where: [:deleted, :archived]).where(deleted: false)
   ```
4. Attempt to use model:
   
   ``` ruby
   a = Person.my(34).unscope(where: :deleted).unscope(where: :archived).where(deleted: false).to_a
   ```
   
   ```
   Person Load (0.9ms)  SELECT "people".* FROM "people" WHERE "people"."account_id" IN (SELECT "accounts"."id" FROM "accounts" WHERE "accounts"."deleted" = $1 AND "accounts"."user_id" = 34) AND "people"."deleted" = $2  [["deleted", "f"]]
   ActiveRecord::StatementInvalid: PG::ProtocolViolation: ERROR:  bind message supplies 1 parameters, but prepared statement "a3" requires 2
   : SELECT "people".* FROM "people" WHERE "people"."account_id" IN (SELECT "accounts"."id" FROM "accounts" WHERE "accounts"."deleted" = $1 AND "accounts"."user_id" = 34) AND "people"."deleted" = $2
   from /<path>/.bundle/ruby/2.2.0/gems/activerecord-4.2.6/lib/active_record/connection_adapters/postgresql_adapter.rb:602:in `exec_prepared'
   ```
   
   Here's how it looks when trying to echo SQL:
   
   ``` sql
   SELECT "people".* FROM "people" WHERE "people"."account_id" IN (SELECT "accounts"."id" FROM "accounts" WHERE "accounts"."deleted" = 'f' AND "accounts"."user_id" = 34) AND "people"."deleted" =
   ```
### Expected behavior

Should output the full query and not raise error.
### Actual behavior

Fails to execute query. This is a by-product of trying to workaround `default_scope` alongside `unscoped` because it was misbehaving; using `unscoped` would not only rid of the `default_scope`, but also any association scopes that might have come with it (via ActiveRecord associations)

If `unscoped` hadn't gotten rid of the association scope, this wouldn't be needed. The initial problem came up when I tried to access: 

``` ruby
Account.find(id).people.where(deleted: false).count
```

Where the default scope is `where(archived: nil, deleted: false)` and I needed to remove the `archived` part of the scope.
### System configuration

**Rails version**: 4.2.6

**Ruby version**: 2.2.3

**Database type**: PostgreSQL

**Comment by rafaelfranca** [comment]
Could you create a reproduction script with this template https://github.com/rails/rails/blob/master/guides/bug_report_templates/active_record_master.rb?

**Comment by chenasraf** [comment]
@rafaelfranca The problem seems to be inside the postgresql adapter, how would one use the adapter in the template test cases? It seems to be requiring me to create the database, unlike sqlite3 which works inline

**Comment by rafaelfranca** [comment]
To change the adapter in the template you only need to change the database configuration in the line 19.

**Comment by aranair** [comment]
@chenasraf Can't seem to reproduce it with [this gist](https://gist.github.com/aranair/15db62fe150944cb5c7fe4053721f537).
