### ISSUE TITLE
Docs are wrong about has_many inverse_of: not working with as:

### ISSUE THREAD

**Issue by alyssais** [rails/rails#25739]
From the Rails docs:

<blockquote>
<dl>
<dt>inverse_of:</dt>
<dd>Specifies the name of the belongs_to association on the associated object that is the inverse of this has_many association. Does not work in combination with :through or :as options. See ActiveRecord::Associations::ClassMethods's overview on Bi-directional associations for more detail.</dd>
</dl>
</blockquote>

But `has_many inverse_of:` does seem to work with the `as:` option.
I've made a [reduced test case](https://github.com/penman/as_inverse_of/blob/master/test/has_many_as_test.rb) that demonstrates this.

So it seems that the docs are wrong.

<dl>
<dt>Rails version</dt>
<dd>5.0.0</dd>
<dt>Ruby version</dt>
<dd>2.3.1</dd>
</dl>

**Comment by maclover7** [comment]
Would you be willing to submit a PR to change the docs?

**Comment by penman** [comment]
Can do, just wanted to make sure that it is definitely that the docs are wrong and the implementation is correct, rather than the other way around?

Those templates are nice!

**Comment by maclover7** [comment]
cc @sgrif

**Comment by Anagha22** [comment]
' :inverse_of '  option is used in an association.A model's associations, as far as memory is concerned, are one-way bindings. The :inverse_of option basically gives us two-way memory bindings when one of the associations is a :belongs_to. We can't use :belongs_to associations in Sentence without :inverse_of because rails needs to know inverses on the sentence in order to create it.

**Comment by trejkaz** [comment]
I would go further and say that not only does `:inverse_of` work fine with `:as`, but _not_ specifying both can [result in weird and hard to find bugs](http://stackoverflow.com/questions/38887701/).

**Comment by alyssais** [comment]
This is still the same on `5-1-stable`. Have updated my reduced test case. Can happily put up a PR for this, but want to check if it is definitely that the docs are wrong and the implementation is correct, rather than the other way around.

**Comment by alyssais** [comment]
Did I miss my chance to keep this open? :(
