### ISSUE TITLE
ActiveRecord 4.0.13 - ActiveRecord::Base.connection.select_all returns ActiveRecord::Result instead of Array

### ISSUE THREAD

**Issue by sgrgic** [rails/rails#25749]
### Steps to reproduce
Simply run any query against your table, for example:
`ActiveRecord::Base.connection.select_all('SELECT * FROM users WHERE id < 3')`

### Expected behavior
It should return array of hashes as result.

### Actual behavior
Returns `ActiveRecord::Result`

### System configuration
**Rails version**: 4.0.13

**Ruby version**: 2.1.6

The problem is that mysql2 adapter select method in Rails 3.2.x was doing to_a for result [here](https://github.com/rails/rails/blob/3-2-stable/activerecord/lib/active_record/connection_adapters/mysql2_adapter.rb#L226) and in Rails 4.0.13  [that's not the case any more](https://github.com/rails/rails/blob/4-0-stable/activerecord/lib/active_record/connection_adapters/mysql2_adapter.rb#L235) but comment still claims this method will return array.

Thanks!

**Comment by matthewd** [comment]
Rails 4.0 is no longer supported
