### ISSUE TITLE
ReferenceError: Can't find variable: App

### ISSUE THREAD

**Issue by afuno** [rails/rails#25746]
I tried to upgrade to version 5.0.0. The problem arose with the channels.

I want to make chat. I created a "Chat" model. I created a "Chat" channel.

cable.coffee:
```
# Action Cable provides the framework to deal with WebSockets in Rails.
# You can generate new channels where WebSocket features live using the rails generate channel command.
#
# Turn on the cable connection by removing the comments after the require statements (and ensure it's also on in config/routes.rb).
#
#= require action_cable
#= require_self
#= require_tree ./channels
#
@App ||= {}
App.cable = ActionCable.createConsumer()
```

routes.rb:
```
root to: 'home#index'
mount ActionCable.server => '/cable'
```

Further, if I write it in the browser console:
```
App # or App.channel
```

So I get back this error:
```
ReferenceError: Can't find variable: App
```

What am I doing wrong?

**Comment by rafaelfranca** [comment]
Please use the mailing list or StackOverflow for questions/help, where a wider community will be able to help you. We reserve the issues tracker for issues only.
