### ISSUE TITLE
Puma restart with tmp/restart.txt not working

### ISSUE THREAD

**Issue by schuetzm** [rails/rails#25751]
Touching `tmp/restart.txt` fails to restart the rails server in development mode. Here's the output:

```
* Restarting...
=> Booting Puma
=> Rails 5.0.0 application starting in development on http://localhost:3000
=> Run `rails server -h` for more startup options
A server is already running. Check /tmp/aaa/tmp/pids/server.pid.
Exiting
```

Using `rails restart` works correctly, however:

```
* Restarting...
=> Booting Puma
=> Rails 5.0.0 application starting in development on http://localhost:3000
=> Run `rails server -h` for more startup options
Puma starting in single mode...
* Version 3.4.0 (ruby 2.3.0-p0), codename: Owl Bowl Brawl
* Min threads: 5, max threads: 5
* Environment: development
* Inherited tcp://localhost:3000
Use Ctrl-C to stop
```

Touching `tmp/restart.txt` also works if the server is started with `puma` instead of `rails server`.

### Steps to reproduce

* `gem install rails` to get the latest version (5.0.0 for me)
* `rails new /tmp/aaa && cd /tmp/aaa`
* `rails server`
* open second shell
    * `rails restart` => works
    * `touch tmp/restart.txt` => fails, complains about already running server
* kill Rails server by pressing Ctrl+C
* `puma`
* open second shell
    * `rails restart` => works
    * `touch tmp/restart.txt` => works

### System configuration
**Rails version**: 5.0.0
**Puma version**: 3.4.0
**Ruby version**: 2.3.0p0

**Comment by vipulnsward** [comment]
See https://github.com/rails/rails/pull/24331 
We need to kill existing pid so that the we don't see those complaints about already running server.

You can see what the restart task actually does over here - https://github.com/rails/rails/blob/fbfc91de32dc04e19258e74283d8786edb21917f/railties/lib/rails/tasks/restart.rake#L9-L8

**Comment by schuetzm** [comment]
@vipulnsward I've seen the PR you linked, but it has been merged a long time ago and is already included in the release, as is the referenced puma PR. But it still does not work even with those fixes. So why did you close this issue? Is the problem already tracked somewhere else, maybe? If so, please post a link so I can follow the progress. Otherwise, please reopen this issue.

**Comment by matthewd** [comment]
@schuetzm  Do we have documentation somewhere claiming that `tmp/restart.txt` will do something? I thought it was just an implementation detail.

**Comment by schuetzm** [comment]
Given that Puma comes with a `tmp_restart` plugin, I pretty much assumed it would work wherever Puma is used. Why wouldn't it, just because I'm using it with Rails?

**Comment by tonytonyjan** [comment]
same here, it's still an issue.

**Comment by jdblack** [comment]
I found that  touching  tmp/restart.txt  did not work.  Running  "rails restart", which claims to touch tmp/restart.txt on the users' behalf,  does.

**Comment by schuetzm** [comment]
Still not working in Rails 5.1. Please reopen.

**Comment by dabit** [comment]
This is still happening in Rails 5.1

**Comment by stedwick** [comment]
+1

**Comment by Fedcomp** [comment]
+1

**Comment by qichunren** [comment]
+1 not work in Rails 8.0.2

**Comment by skipkayhil** [comment]
Everything here is working as expected. If you use `$ rails server`, you must use `$ rails restart`. If you use `$ puma`, you can use `$ touch`.
