### ISSUE TITLE
Nested subquery with has_many relation generates invalid SQL when relation's default scope changes returned expression

### ISSUE THREAD

**Issue by amysutedja** [rails/rails#25753]
# Steps to reproduce

Demo with test showing the failing scenario here: https://github.com/amysutedja/mutable_default_scope_demo
# Description
- A model M has many of child model C.
- C has a default_scope defined which is conditional -- for example, it might return different clauses based on thread-local storage.
- One condition returns all records, and the other returns a where filter based on a boolean.
- The child model C is used in a subquery, such as `C.where(id: m_instance.cs)`.
- A thread exercises both conditions.

In this case, `C.where(id: m_instance.cs)` generates invalid SQL when the `default_scope` returns the second condition.

For example, imagine that we have a `default_scope` like the following, where model M is `User` and child model C is `Book`.

```
default_scope proc {
  if Thread.current[:test]
    all
  else
    where(deleted: false)
  end
  }
```

If you run the following with `Thread.current[:test] == false`:

```
u = User.first
Book.where(u: u.books).to_sql
```

...it generates the following correct SQL.

```
SELECT "books".* FROM "books" WHERE "books"."deleted" = 'f' AND "books"."id" IN (SELECT "books"."id" FROM "books" WHERE "books"."deleted" = 'f' AND "books"."user_id" = 1)
```

Then, when you set `Thread.current[:test] = true`, the same expression produces wrong SQL.

```
SELECT "books".* FROM "books" WHERE "books"."id" IN (SELECT "books"."id" FROM "books" WHERE "books"."user_id" = 'f')
```

Note that the `user_id` is set to `'f'`, when it should be `1`.

However, if you never ran with `Thread.current[:test] = true` in the first place, it generates correct SQL.
# Expected behavior

The generated query should be correct.
# Actual behavior

The generated query is incorrect.
# System configuration

Rails version: 5.0.0 and 4.2.3

Ruby version: 2.3.1

**Comment by amysutedja** [comment]
The fix for this may be related to the fix for this ticket: https://github.com/rails/rails/issues/24588

**Comment by vipulnsward** [comment]
cc @sgrif

**Comment by sgrif** [comment]
Digging into this. The bug can only be reproduced if the user instance is the same for both calls (meaning that `u.comments` is the same scope). `WHERE user_id = 'f'` is *definitely* wrong though

**Comment by amysutedja** [comment]
Updated the repo with Rails 5.0.2. Still repros.

**Comment by kamipo** [comment]
It works since 5.0.3.

**Comment by amysutedja** [comment]
Agreed, it's fixed. Thanks for investigating!
