### ISSUE TITLE
4.2.7.rc1 Regression - Cannot load such file -- concurrent

### ISSUE THREAD

**Issue by bragboy** [rails/rails#25764]
### Steps to reproduce

Checkout the following project : https://github.com/bragboy/rails_issue/tree/rails_4.2.6 and do a `rails s`. Things look good !

Checkout the same project with an upgrade to 4.2.7.rc1: https://github.com/bragboy/rails_issue/tree/rails_4.2.7_rc1 and do a `rails s`. It chokes with the below error

```
/Users/bragadeeshj/.rvm/gems/ruby-2.2.3@rails_issue/gems/activesupport-4.2.7.rc1/lib/active_support/logger_thread_safe_level.rb:2:in `require': cannot load such file -- concurrent (LoadError)
	from /Users/bragadeeshj/.rvm/gems/ruby-2.2.3@rails_issue/gems/activesupport-4.2.7.rc1/lib/active_support/logger_thread_safe_level.rb:2:in `<top (required)>'
	from /Users/bragadeeshj/.rvm/gems/ruby-2.2.3@rails_issue/gems/activesupport-4.2.7.rc1/lib/active_support/logger.rb:3:in `require'
	from /Users/bragadeeshj/.rvm/gems/ruby-2.2.3@rails_issue/gems/activesupport-4.2.7.rc1/lib/active_support/logger.rb:3:in `<top (required)>'
	from /Users/bragadeeshj/.rvm/gems/ruby-2.2.3@rails_issue/gems/activesupport-4.2.7.rc1/lib/active_support.rb:27:in `require'
	from /Users/bragadeeshj/.rvm/gems/ruby-2.2.3@rails_issue/gems/activesupport-4.2.7.rc1/lib/active_support.rb:27:in `<top (required)>'
	from /Users/bragadeeshj/.rvm/gems/ruby-2.2.3@rails_issue/gems/actionpack-4.2.7.rc1/lib/action_dispatch.rb:24:in `require'
	from /Users/bragadeeshj/.rvm/gems/ruby-2.2.3@rails_issue/gems/actionpack-4.2.7.rc1/lib/action_dispatch.rb:24:in `<top (required)>'
	from /Users/bragadeeshj/.rvm/gems/ruby-2.2.3@rails_issue/gems/railties-4.2.7.rc1/lib/rails/commands/server.rb:3:in `require'
	from /Users/bragadeeshj/.rvm/gems/ruby-2.2.3@rails_issue/gems/railties-4.2.7.rc1/lib/rails/commands/server.rb:3:in `<top (required)>'
	from /Users/bragadeeshj/.rvm/gems/ruby-2.2.3@rails_issue/gems/railties-4.2.7.rc1/lib/rails/commands/commands_tasks.rb:123:in `require'
	from /Users/bragadeeshj/.rvm/gems/ruby-2.2.3@rails_issue/gems/railties-4.2.7.rc1/lib/rails/commands/commands_tasks.rb:123:in `require_command!'
	from /Users/bragadeeshj/.rvm/gems/ruby-2.2.3@rails_issue/gems/railties-4.2.7.rc1/lib/rails/commands/commands_tasks.rb:73:in `server'
	from /Users/bragadeeshj/.rvm/gems/ruby-2.2.3@rails_issue/gems/railties-4.2.7.rc1/lib/rails/commands/commands_tasks.rb:39:in `run_command!'
	from /Users/bragadeeshj/.rvm/gems/ruby-2.2.3@rails_issue/gems/railties-4.2.7.rc1/lib/rails/commands.rb:17:in `<top (required)>'
	from bin/rails:4:in `require'
	from bin/rails:4:in `<main>'
```

The only difference between the two branches is the version bump - https://github.com/bragboy/rails_issue/commit/dd48a3a06dc78499275dae35ccb6c8a5f52e240f . The rest of the Gemfile remains intact.

### Expected behavior
Rails server should start

### Actual behavior
Rails server fails to start

### System configuration
**Rails version**: 4.2.7.rc1

**Ruby version**: 2.2.3

### Possible root cause:
I see an include at this particular line - https://github.com/rails/rails/compare/v4.2.6...v4.2.7.rc1#diff-ae0cb1fe3f1f2a3025bdf0dbc3d2890cR2 which apparently is not present in my Gemfile.lock. Is this a development dependency only ? It was introduced as part of this commit - https://github.com/rails/rails/commit/851f0ecd9ea803354754e42ce62ba3414d2eb1e1

Source Pull Request: #25356 

PS: I created a barebone rails project with my own `Gemfile` and `Gemfile.lock` to reproduce and demonstrate the error.

cc: @rafaelfranca @kmcphillips

**Comment by bragboy** [comment]
Closing this since this seem to have been already fixed with https://github.com/rails/rails/commit/e384220a83825db463945becd39d314ff51e8dd1 
Thanks!

**Comment by kmcphillips** [comment]
👍
