### ISSUE TITLE
Uncaught Error: Existing connection must be closed before opening bug

### ISSUE THREAD

**Issue by tarungarg** [rails/rails#25761]
Actioncable is implemented on too many places in my application. Getting this error most of times 
**Existing connection must be closed before opening bug**

As per my assumption, this error comes if i visits the same page more than once (where actioncable is implemented). Actioncable creates new connection every time.
So my question is  
How can i close the running connections if they are not using. Also if i visit the page where actioncable is implemented more than once, the first/prev. connection must be close.  

Some other information:-
I implemented actioncable where ajax was using. Typed messages were duplicating more than once. Like events('received' method of actioncable) were binding again and again, as i was visiting the page. For eg. if I had visited the page 3 times and when i typed the message "Hi". "Hi" was showing 3 times on the page. I got some interesting result when i tried to debug. I ran below command       

> chat_obj.cable.subscriptions.subscriptions

I got array of subscriptions with duplicate identifiers. I tried to close subscriptions with below command 

>   for (var i=0; i <= chat_obj.cable.subscriptions.subscriptions.length; i++) {
>       chat_obj.cable.subscriptions.remove(chat_obj.cable.subscriptions.subscriptions[i+1])
>   }

but i got some unexpected behavior of actioncable. Messages were not delivering sometime.

`Could not execute command from {"command"=>"unsubscribe", "identifier"=>"{\"channel\":\"DeleteMessageChannel\"}"}) [NoMethodError - undefined method `unsubscribe_from_channel' for nil:NilClass]: /home/tarungarg/.rvm/gems/ruby-2.3.1/bundler/gems/actioncable-92adbc2fab09/lib/action_cable/connection/subscriptions.rb:44:in `remove_subscription' | /home/tarungarg/.rvm/gems/ruby-2.3.1/bundler/gems/actioncable-92adbc2fab09/lib/action_cable/connection/subscriptions.rb:40:in `remove' | /home/tarungarg/.rvm/gems/ruby-2.3.1/bundler/gems/actioncable-92adbc2fab09/lib/action_cable/connection/subscriptions.rb:16:in `execute_command' | /home/tarungarg/.rvm/gems/ruby-2.3.1/bundler/gems/actioncable-92adbc2fab09/lib/action_cable/connection/base.rb:88:in `receive' | /home/tarungarg/.rvm/gems/ruby-2.3.1/bundler/gems/actioncable-92adbc2fab09/lib/action_cable/server/worker.rb:19:in `block in invoke
`
### Actual behavior
It should automatically find for the identifier and should not create new one if identifier already exists.

### System configuration
Rails 4.2.6
Ruby 2.3.1p112

**Comment by maclover7** [comment]
Thank you for opening this issue! Would you be willing to condense your bug description a little bit, it's a little hard to figure out what the bug is here. I _think_ the issue you are trying to report is that you "[...] got array of subscriptions with duplicate identifiers"? :)

cc @javan

**Comment by tarungarg** [comment]
Yes, Might be answer of this question can help me a lot. But i am getting 3 issues
1. Existing connection must be closed before opening bug
2. Array of subscriptions with duplicate identifiers.
3. Could not execute command from {"command"=>"unsubscribe", "identifier"=>"{\"channel\":\"DeleteMessageChannel\"}"}) [NoMethodError - undefined methodunsubscribe_from_channel' for nil:NilClass]

Attached file contains the code   
[chats.txt](https://github.com/rails/rails/files/355618/chats.txt)

**Comment by maclover7** [comment]
👍 would you be able to create a sample app(s) to reproduce those above issues (or at least the actions you'd have to take, if you don't want to create a whole app)?

**Comment by tarungarg** [comment]
Please see the below url
https://github.com/tarungarg/actioncable-example

This example app includes bug
Array of subscriptions with duplicate identifiers
 
I have mentioned the desc and steps to reproduce the bug.

**Comment by maclover7** [comment]
Hmm, just taking a quick look at that project's Gemfile, it looks like you are using v0.0.3 of Action Cable, which was published quite a while ago. Can you update your project to use the latest version of Action Cable, and then test and see if the reported issues still exist?

**Comment by tarungarg** [comment]
@maclover7 , I updated the gem list but still issue is occurring

https://github.com/tarungarg/actioncable-example
Branch: rails5

**Comment by maclover7** [comment]
Hi @tarungarg! Took some time today to look into the bugs reported above:

> [...] "As per my assumption, this error comes if i visits the same page more than once (where actioncable is implemented). Actioncable creates new connection every time.
So my question is
How can i close the running connections if they are not using. Also if i visit the page where actioncable is implemented more than once, the first/prev. connection must be close." [...]

I was not able to reproduce a connection being created on every page change. It seems like the same open connection is being reused.

> I implemented actioncable where ajax was using. Typed messages were duplicating more than once. Like events('received' method of actioncable) were binding again and again, as i was visiting the page. For eg. if I had visited the page 3 times and when i typed the message "Hi". "Hi" was showing 3 times on the page.

I was also not able to reproduce this, when I had two tabs open, each on the same chat tab, and I went back and forth sending messages.

> I got array of subscriptions with duplicate identifiers. I tried to close subscriptions with below command
```
for (var i=0; i <= chat_obj.cable.subscriptions.subscriptions.length; i++) {
chat_obj.cable.subscriptions.remove(chat_obj.cable.subscriptions.subscriptions[i+1])
}
```

Again, I was not able to reproduce this as well. Also, I think this is reaching into internal Action Cable API, by operating on the `subscriptions` objects.
---

If for any of the above examples, you are able to reproduce the issue, and list out the reproduction steps, please reopen the issue. Going to give this a close, and I'd say the best place to go for more support is the StackOverflow or Rails mailing list. Thank you for the ticket! :)
