### ISSUE TITLE
Having some strange behavior when has any error adding a foreign key 

### ISSUE THREAD

**Issue by xdougx** [rails/rails#25776]
Hello guys, I just have a strange behave when I tried to create a migration like

```
class CreateModels < ActiveRecord::Migration[5.0]
  def change
    create_table :models do |t|
      t.integer :relation_a_id
      t.integer :relation_b_id
      t.timestamps
    end
    
    add_foreign_key :models, :relation_as
    add_foreign_key :models, :relation_bs

  end
end
```
If you pass for example:

```
add_foreign_key :models, :relation_bs, column: 'wrong_column'
```

Rails create the Table, create the right foreign key, but the last one you get an mysql exception, and doesnt rollback the full operation.

Someone had this issue before?

**Comment by prakashmurthy** [comment]
This is a common behavior. 

`add_foreign_key :models, :relation_bs, column: 'wrong_column'` throws an exception and marks the migration as not completed, but leaves the `models` table in the database. 

If you run `rails db:migrate:status` at this stage, it will show something like below to indicate that the migration is not applied:

```ruby
$ rails db:migrate:status

database: dev_rails_db

 Status   Migration ID    Migration Name
--------------------------------------------------
   ...
   ...
   up     20160701224636  Add deal id to events
  down    20160711170100  Create models
```

However, `models` table is still present as seen from mysql command line:

```sql
$myql
mysql> use dev_rails_db

mysql> select count(*) from models;
+----------+
| count(*) |
+----------+
|        0 |
+----------+
1 row in set (0.00 sec)
```

Best to drop the `models` table from the mysql command line, to bring the database in sync with the migration table, and then run the corrected migration.
```sql
mysql> drop table models;
Query OK, 0 rows affected (0.10 sec)
```

**Comment by rafaelfranca** [comment]
Yes, this is the expected behavior. MySQL doesn't have transactional migrations.

**Comment by xdougx** [comment]
Yeah, Ive done it. Well thats fine, thought it was a wrong behavior, thanks a lot!
