### ISSUE TITLE
Newly generated rails apps contain comments over 80 characters

### ISSUE THREAD

**Issue by amingilani** [rails/rails#25770]
Is this a conscious decision? Because for every new project, I personally have to go through all the files and ensure that they are Rubocop compliant.

### Steps to reproduce

`rails new app`

### Expected behavior

Comments and indeed all code should wrap at 80 characters. Most of the lines do respect this limit, but some do not.

### Actual behavior
as an example: here's the Gemfile
```ruby
  # Access an IRB console on exception pages or by using <%= console %> anywhere in the code.
  gem 'web-console'
  gem 'listen', '~> 3.0.5'
  # Spring speeds up development by keeping your application running in the background. Read more: https://github.com/rails/spring
  gem 'spring'
  gem 'spring-watcher-listen', '~> 2.0.0'
```

The comments are far longer

### System configuration
**Rails version**: 5.0.0

**Ruby version**: 2.3.1

**Comment by rafaelfranca** [comment]
Yes it is. We don't follow this rule in our project.

**Comment by amingilani** [comment]
@rafaelfranca could you link me to a discussion on why this is so? I'm interested in the rationale behind this.

**Comment by matthewd** [comment]
@amingilani I'm not sure I see why the onus is on us to justify why we haven't retroactively adopted rubocop's (often questionable) sense of style.

**Comment by amingilani** [comment]
@matthewd I never said anything about the project retroactively following Rubocop.

I asked if there had been a discussion about the 80 char or any line limit, which I follow because they significantly improves the readability of a codebase.

If there hasn't been a discussion about this before, please say so, and refrain from introducing [strawmen](https://www.logicallyfallacious.com/tools/lp/Bo/LogicalFallacies/169/Strawman-Fallacy) or [red herrings](https://www.logicallyfallacious.com/tools/lp/Bo/LogicalFallacies/150/Red_Herring).

**Comment by amingilani** [comment]
The reason I asked for a reference because when asked if this was a conscious decision:
> Yes it is -@rafaelfranca

**Comment by jonathanhefner** [comment]
I do recall PR #25439 from a few weeks ago.

**Comment by guilleiguaran** [comment]
I think we have discussed this multiple times before but I can't find exact references on github right now, I can find some discussion about it on [twitter](https://twitter.com/dhh/status/245296093263458306) and [blogs](https://signalvnoise.com/posts/3250-clarity-over-brevity-in-variable-and-method-names), tho.

We don't think that we should follow this rule and [we aren't the only ones](
https://www.viget.com/articles/the-line-length-misconception).

**Comment by spk** [comment]
The main point for me is that its annoying for review, just on github I have to scroll horizontally for lots of diff in this project.

**Comment by printercu** [comment]
There is template which wraps long lines in new app: https://github.com/printercu/rails-template-80

**Comment by amingilani** [comment]
Thank you @printercu! Is this just 80 char compliant, or does it comply with the rest of Rubocop's Rails rules as well?

**Comment by printercu** [comment]
I test it only against LineLenght cop: https://github.com/printercu/rails-template-80/blob/master/Rakefile#L9

Other modifications are discussible.
