### ISSUE TITLE
5.5 - Error in text

### ISSUE THREAD

**Issue by Ashley-Pettit** [rails/rails#25788]
Hello, I think in 5.5 of { http://edgeguides.rubyonrails.org/getting_started.html } there is a slight typo. 

The guide tells you to type { bin/rails db:migrate } which gives the error { Error: Command 'db:migrate' not recognized Did you mean: `$ rake db:migrate` ? }. 

I believe the line as specified by the error should be { rake db:migrate }

**Comment by rafaelfranca** [comment]
That line is correct if you are using Rails 5. If you are using Rails 4.2 it is `bin/rake db:migrate`. You are looking the Rails 5.1 documentation, the Rails 4.2 guide can be found in http://guides.rubyonrails.org/v4.2/

**Comment by Ashley-Pettit** [comment]
Thanks for the answer :). Makes perfect sense


Kind Regards,

Ashley Pettit
Phone  0404 590 975
Email ashley@digital380.com <ashleyp@pageuppeople.com>.au
