### ISSUE TITLE
WebSocket connection to 'ws://site.com/cable' failed: Unexpected response code: 404

### ISSUE THREAD

**Issue by afuno** [rails/rails#25783]
Rails 5.0.0.

I create a project.

The next step, I created two channels: chat and comment. In addition to the controller, of course. I think the controllers and modules are not important here.

Then I added in routes.rb file this line:
```
mount ActionCable.server => '/cable'
```

Now when run the project, I got this error:
> WebSocket connection to 'ws://site.com/cable' failed: Unexpected response code: 404

At the address http://site.com/cable I get this error:
> Page not found

This inscription on a blank white page.

What is the problem? Why 404?

**Comment by matthewd** [comment]
Please use the mailing list or StackOverflow for questions/help, where a wider community will be able to help you. We reserve the issues tracker for issues only.

**Comment by afuno** [comment]
In the sense of?

I've done all of your a manual at the just created project. On StackOverflow me for a week can not help.

I do not know what else to do. Help me to understand. Please.

**Comment by afuno** [comment]
I should add that I run the channel server as follows:
```
config.action_cable.mount_path = '/cable'
```

**Comment by afuno** [comment]
@matthewd

**Comment by sizl** [comment]
did you ever find out what the issue was?
