### ISSUE TITLE
Fix lazy load hooks documentation.

### ISSUE THREAD

**Issue by kaspth** [rails/rails#25784]
Active Support has long had load hooks in https://github.com/rails/rails/blob/39b8b8fdbf6c175a64f07198ff1c950e33c72cd0/activesupport/lib/active_support/lazy_load_hooks.rb, but since https://github.com/rails/rails/commit/7c90d91c3c43bdbba25d38589aed0e2940af3bc8 the docs stopped showing up on http://api.rubyonrails.org/files/activesupport/lib/active_support/lazy_load_hooks_rb.html.

Your mission, should you choose to accept it, is to fix this. We could wrap the file's behavior in a module and extend Active Support with it inline.

Then for good measure we should give the docs some housekeeping. Try coming up with a better explanation for why the lazy load hooks exist. Use this as a starting ground: https://github.com/rails/rails-controller-testing/issues/24#issuecomment-231827911

**Comment by mrageh** [comment]
@kaspth I'll pick this up

**Comment by kaspth** [comment]
Sweet!

**Comment by vipulnsward** [comment]
@kaspth I believe this can be closed?

**Comment by mrageh** [comment]
@vipulnsward I'd like to add another commit that improves the docs around load hooks

**Comment by kaspth** [comment]
Yeah, this still encompasses a doc upgrade. So let's keep it open for now.

@mrageh you can add "Fixes #25784" in your PR and then this issue will auto-close when we merge that. Less work for us, thanks :)
