### ISSUE TITLE
dbconsole attempts to execute mysql directory

### ISSUE THREAD

**Issue by sbfaulkner** [rails/rails#25801]
### Steps to reproduce

1. create rails application using mysql adapter
2. create mysql directory within a directory that is in your path.
actual mysql binary
  - eg. given PATH=/usr/local/bin:/usr
3. `bin/rails db -p`

### Expected behavior
I would expect dbconsole to ignore the directory and continue searching my path for the binary.

### Actual behavior
dbconsole attempts to execute the mysql directory instead of the binary.
/home/directory/.gem/ruby/2.2.3/gems/railties-4.2.5.2/lib/rails/commands/dbconsole.rb:186:in `exec': Permission denied - /path/to/folder/mysql (Errno::EACCES)

### System configuration
**Rails version**: 4.2.5.2

**Ruby version**: 2.2.3

NOTE: I will take a look at how to resolve this

**Comment by rafaelfranca** [comment]
> NOTE: I will take a look at how to resolve this

:heart:

**Comment by rafaelfranca** [comment]
The problem should be here https://github.com/rails/rails/blob/master/railties/lib/rails/commands/dbconsole.rb#L150-L171

**Comment by sbfaulkner** [comment]
appears that it should have been fixed here https://github.com/sbfaulkner/rails/commit/17bb531f82b33a8c6365f73f7577ee1f3a37ef1a

**Comment by sbfaulkner** [comment]
@rafaelfranca do I just need to backport the fix to 4-2-stable or something? or would that even get merged?

**Comment by rafaelfranca** [comment]
I can do it manually, but since you used your time to find the solution it would be great if you open a PR against 4-2-stable to get the credits.

**Comment by sbfaulkner** [comment]
@rafaelfranca https://github.com/rails/rails/pull/25803

**Comment by maclover7** [comment]
Closing since #25803 was merged into `4-2-stable`. Thank you for your PR, @sbfaulkner!
