### ISSUE TITLE
ActiveSupport autoload bug:  multi-threads autoloading the same class at the same instant causes error "Circular dependency detected while autoloading constant Xxx"

### ISSUE THREAD

**Issue by johnnytemp** [rails/rails#25807]
### Steps to reproduce

Precondition: No "require 'AnAutoloadingActiveRecordClass'" statement
Code below, e.g. to run the first time in "rails console":

<pre>
threads = (1..10).map do |i|
  Thread.new do
    puts AnAutoloadingActiveRecordClass.all.count
  end
end
threads.each {|t| t.join}
</pre>

### Expected behavior
No exception.  Rails should support multi-thread as it claims.  I am using CRuby with GIL (Global Interpreter Lock).

### Actual behavior

RuntimeError: Circular dependency detected while autoloading constant AnAutoloadingActiveRecordClass

### Problem description
The exception at C:\Rails\Ruby2.2.0\lib\ruby\gems\2.2.0\gems\activesupport-4.2.5\lib\active_support\dependencies.rb line 492 is actually a false positive, checking "loading" array in "if loading.include?(expanded)" when it is indeed loading from another thread, but I/O waiting in that thread.

### System configuration
**Rails version**:  4.2.5

**Ruby version**: 2.2.4p230

**Comment by fxn** [comment]
"Rails has support for multi-threading" does not mean that any piece of code can be used in any multi-threaded scenario.

In particular, constant autoloading is not thread-safe.

For many years that was the reason multi-threading was disabled in development mode. Now, web requests in development mode may be multi-threaded because there are synchronization mechanisms in place at the request level.

In production mode, that's one of the reasons the application is eager loaded before threads are spawned.

In development mode, you need to load the constants before spawning threads.

**Comment by johnnytemp** [comment]
This is where I found someone say Ruby claim itself to be thread-safe:

Link:  https://bearmetal.eu/theden/how-do-i-know-whether-my-rails-app-is-thread-safe-or-not/

All three of these need to be thread-safe. Rails and its included gems have been declared thread-safe since 2.2, i.e. since 2008.

**Comment by johnnytemp** [comment]
It seems a shame for NOT to fix the "most essential" core autoloading code that is thread-unsafe.  Very few detail is documented about this issue in Rails documentation.  :-(

**Comment by fxn** [comment]
@johnnytemp patches welcome.

**Comment by johnnytemp** [comment]
Well, actually many thanks for replying me.

Your comments are useful.

If your comments is real in the Ruby on Rails, it would be quite nice if it would have documented more obviously in a documentation about threading.  Now, Rails users may need to find it out what is the cause of errors themselves.

Of course, you owe me nothing.  :)

**Comment by fxn** [comment]
Yes, Rails needs a whole guide about multi-threading.

Does the fact that AR is safe mean that you can share individual records between threads, or just that classes are safe? Needs documentation.

Multi-threading is a huge topic with many fine details.

But someone has to write that guide.

**Comment by johnnytemp** [comment]
Or add a remark for thread-unsafe autoload in this document may seem suitable:

http://guides.rubyonrails.org/autoloading_and_reloading_constants.html

**Comment by bradleybuda** [comment]
For anyone else who finds this issue - it seems that [this has changed in Rails 6](https://weblog.rubyonrails.org/2019/2/22/zeitwerk-integration-in-rails-6-beta-2/) with the introduction of the Zeitwerk loader. The "classic" (Rails 5 and earlier) autoloader remains thread-unsafe.
