### ISSUE TITLE
Can't assign a hash to a cookie

### ISSUE THREAD

**Issue by rosenfeld** [rails/rails#25802]
I don't actually use a hash as a cookie value, but while investigating how cookies work I faced something which I think is either a bug in the documentation or in the code, so I'm describing it here since I don't know which one is the case.

Assigning a hash to some cookie (cookies['name'], cookies.signed['name'], cookies.encrypted['name], doesn't matter) is silently ignored. `cookies['hash'] = {'a' => 1}` will generate an invalid encoded cookie (or maybe the equivalent of nil encoded).

This happens with either JSON or Marshal used as the serializer.

The API doesn't specify that a hash is not a supported value:

http://api.rubyonrails.org/classes/ActionDispatch/Cookies.html

Is the current behavior expected? If so, I can send a patch to fix the documentation.

**Comment by rosenfeld** [comment]
Sorry, forgot to tell you I've tested this on Rails 5.

**Comment by maclover7** [comment]
Hmm, seems like there's an example in the documentation which promotes setting hashes as cookie values.

Did this work for you in Rails 4 / 
Can you create an executable test script using one of the templates [here](https://github.com/rails/rails/tree/master/guides/bug_report_templates), that would demonstrate the problem you are seeing?

**Comment by rosenfeld** [comment]
I wasn't really affected by this bug so I don't know if it was present in Rails 4. I just found it by accident while writing a gem today. Right now I'm about to sleep but tomorrow morning I'll try to reproduce in a basic Rails app for both Rails 4 and 5. The one I used to test was an existing sample application with Devise included, so I want to be sure it's not affected by Devise. I'll check your templates tomorrow. Thanks.

**Comment by rosenfeld** [comment]
I just took a glance at the templates, they are great, thanks :-)

**Comment by rosenfeld** [comment]
While creating the test case I noticed that not only the bug is also present on Rails 4 but it doesn't affect only hashes. If you set it to a number it will be converted to a string the next time you try to read that value from the cookie:

https://gist.github.com/rosenfeld/7a7b05a23ad2cce2f3fd17296abbea64

Seems like an old bug though since the output is the same on Rails 4.

I hope that helps.

**Comment by slavaZim** [comment]
```
#rails/actionpack/lib/action_dispatch/middleware/cookies.rb

#Cookie values are String based. Other data types need to be serialized. 
#cookies[:lat_lon] = JSON.generate([47.68, -122.37])
#JSON.parse(cookies[:lat_lon]) # => [47.68, -122.37]

```

Comments in this file imply that cookie value is string. However, you can initialize one with a hash:

```
  # The option symbols for setting cookies are:
  #
  # * <tt>:value</tt> - The cookie's value.
  # * <tt>:path</tt> - The path for which this cookie applies. Defaults to the root
  #   of the application.
  # * <tt>:domain</tt> - The domain for which this cookie applies so you can
  #   restrict to the domain level. If you use a schema like www.example.com
  #   and want to share session with user.example.com set <tt>:domain</tt>
  #   to <tt>:all</tt>. Make sure to specify the <tt>:domain</tt> option with
  #   <tt>:all</tt> or <tt>Array</tt> again when deleting cookies.
  #
  #     domain: nil  # Does not set cookie domain. (default)
  #     domain: :all # Allow the cookie for the top most level
  #                  # domain and subdomains.
  #     domain: %w(.example.com .example.org) # Allow the cookie
  #                                           # for concrete domain names.
  #
  # * <tt>:tld_length</tt> - When using <tt>:domain => :all</tt>, this option can be used to explicitly
  #   set the TLD length when using a short (<= 3 character) domain that is being interpreted as part of a TLD.
  #   For example, to share cookies between user1.lvh.me and user2.lvh.me, set <tt>:tld_length</tt> to 1.
  # * <tt>:expires</tt> - The time at which this cookie expires, as a \Time object.
  # * <tt>:secure</tt> - Whether this cookie is only transmitted to HTTPS servers.
  #   Default is +false+.
  # * <tt>:httponly</tt> - Whether this cookie is accessible via scripting or
  #   only HTTP. Defaults to +false+.
```

That probably means that there are special key reserved for cookie instance variables, still it value is string and should be serialized/deserialized on writing/reading for hash representation.

**Comment by rosenfeld** [comment]
Hmm, I think I understand the confusion. In the API it could be clearer that an string is expected. Maybe it would be great to add an example like this, to demonstrate how to use non string values:

```ruby
cookies['my_key'] = {value: {my: 'value'}}
```

Also, maybe it would be a good idea to either fail or to warn about unsupported options while trying to provide the Hash value directly to the cookie like this:

```ruby
cookies['my_key'] = {my: 'value'}
# prints a 'WARNING: :my option is being ignored while setting the cookie. Supported options are [...]. If you instead want to set a hash to the cookie you should use the :value key for that like ..."
```

However, if you think it's just fine as it is, feel free to close this issue.

**Comment by solojavier** [comment]
Is this going to be closed or needs to be worked on?

**Comment by rafaelfranca** [comment]
@solojavier I think the improvement to the documentation that @rosenfeld pointed is a good thing to do. Do you want to send a PR?

**Comment by rosenfeld** [comment]
It seems it was documented here but I missed it somehow.
