### ISSUE TITLE
ActionCable leaks Connection::Base after reloading code

### ISSUE THREAD

**Issue by machty** [rails/rails#25837]
### Expected behavior

Instances of `ActionCable::Connection::Base` don't seem to be cleaned up after code changes. Specifically, methods that are periodically called throughout the lifetime of a connection (e.g. `beat`) should no longer be called.
### Actual behavior

`Connection::Base#beat` continues to be called even after a connected browser window has closed (or a more explicit client-side disconnection) occurs. This affects development only (since prod obviously doesn't reload code), and I only noticed it because I was overriding `beat` to also mark the authenticated user's most recent connectivity timestamp. 
### System configuration

**Rails version**: 5.0.0.rc2

**Ruby version**: 2.3.0

**Comment by matthewd** [comment]
Can you still reproduce this on `5-0-stable`?
