### ISSUE TITLE
4.2.7 tagged commit

### ISSUE THREAD

**Issue by fledman** [rails/rails#25832]
@rafaelfranca

looking [here](https://github.com/rails/rails/releases/tag/v4.2.7) you tagged 7f2327f as the 4.2.7 commit as opposed to the merge d8f5596.

was this intentional?

the parent of 7f2327f is e384220a83825db463945becd39d314ff51e8dd1 so the following `4-2-stable` commits did not get included in the release:
 - a9ad852
 - fd65a90
 - 0f77e0c
 - 93efd1a

**Comment by rafaelfranca** [comment]
Yes, it is intentional. The release was made from the release branch that has its parent in the rc1 release. Commits added after the rc1 to the stable branches are intentionally left off the release.

**Comment by fledman** [comment]
thanks

**Comment by joshuamcginnis** [comment]
Hi @rafaelfranca. Just following up on this. I see that PR #25704 made it to the 4-2-stable branch, but it doesn't look like it's been making to any of the 4.2.x tags.

Do you know why that is and when we might see it released?

**Comment by rafaelfranca** [comment]
It will be released in the next release of the 4-2-stable branch.

**Comment by joshuamcginnis** [comment]
Pardon my ignorance on your release process. Will the next release of this branch happen with the next MINOR update? (ostensibly `4.2.8`)

**Comment by rafaelfranca** [comment]
Yes.

**Comment by joshuamcginnis** [comment]
Thank you
