### ISSUE TITLE
Can't create TIMESTAMP column with MySQL

### ISSUE THREAD

**Issue by PavelPenkov** [rails/rails#25830]
### Steps to reproduce

```
class AddTSColumn < ActiveRecord::Migration[5.0]
  def change
    add_column :posts, :published_at, 'TIMESTAMP'
  end
end
```
### Expected behavior

A column with `TIMESTAMP` data type should be created
### Actual behavior

A column with `DATETIME` data type is created
### System configuration

**Rails version**: 5.0.0

**Ruby version**: 2.3.1p112

**Comment by prakashmurthy** [comment]
From http://stackoverflow.com/a/3929047/429758

> Having said all of this, **Rails actually makes some of these decisions for you.** Both :timestamp and :datetime will default to DATETIME, while :date and :time corresponds to DATE and TIME, respectively.
> 
> This means that within Rails, you only have to decide whether you need to store date, time or both.

[tests asserting the same](https://github.com/rails/rails/blob/ea31bdd7c8b1221d97de2392ac22d9c5fb8657d5/activerecord/test/cases/connection_adapters/type_lookup_test.rb#L51-L52)

```ruby
      def test_datetime_types
        assert_lookup_type :datetime, 'datetime'
        assert_lookup_type :datetime, 'DATETIME'
        assert_lookup_type :datetime, 'timestamp'
        assert_lookup_type :datetime, 'TIMESTAMP'
     end
```

**Comment by sblackstone** [comment]
Could you please post a test case that duplicates the issue?  I tried to duplicate with this script but the column was created as timestamp..

```
begin
  require 'bundler/inline'
rescue LoadError => e
  $stderr.puts 'Bundler version 1.10 or later is required. Please update your Bundler'
  raise e
end

gemfile(true) do
  source 'https://rubygems.org'
  # Activate the gem you are reporting the issue against.
  gem 'activerecord', '5.0.0'
  gem 'mysql2'
  gem 'byebug'
end

require 'active_record'
require 'minitest/autorun'
require 'logger'

# Ensure backward compatibility with Minitest 4
Minitest::Test = MiniTest::Unit::TestCase unless defined?(Minitest::Test)

# This connection will do for database-independent bug reports.
ActiveRecord::Base.establish_connection(adapter: 'mysql2', database: 'r25830', host: 'x.x.x.x', username: 'xxx, password: 'xxx')
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :posts, force: true do |t|
  end

  add_column :posts, :published_at, 'TIMESTAMP'

end

class Post < ActiveRecord::Base
  has_many :comments
end

class BugTest < Minitest::Test
  def test_association_stuff
    assert_equal 1, Post.columns.select {|x| x.sql_type == 'timestamp' }.length 
  end
end
```


And the SQL becomes:

```
-- add_column(:posts, :published_at, "TIMESTAMP")
D, [2016-07-14T17:10:30.133512 #41796] DEBUG -- :    (4.9ms)  ALTER TABLE `posts` ADD `published_at` TIMESTAMP
```

**Comment by kamipo** [comment]
AR aliases small case `timestamp` to `datetime`. Thus `TIMESTAMP` is created as `timestamp`.
https://github.com/rails/rails/blob/v5.0.0/activerecord/lib/active_record/connection_adapters/abstract/schema_definitions.rb#L389-L391

But schema dumper does not support `timestamp` type. #23553 will fix the issue.

**Comment by kamipo** [comment]
Closing since #23553 was merged.
