### ISSUE TITLE
Vary: Accept should be set whenever content negotiation is used

### ISSUE THREAD

**Issue by sethk** [rails/rails#25842]
### Steps to reproduce

Use an `Accept` header to vary the content type used to render the response.
### Expected behavior

Response should include `Vary: Accept` to show that the response differs due to content negotiation.
### Actual behavior

All responses are considered equal to the user agent, leading to caching issues. See these bugs:

https://github.com/rails/jquery-ujs/issues/318
https://bugs.chromium.org/p/chromium/issues/detail?id=94369
### System configuration

**Rails version**: 4.2.1

**Ruby version**: ruby 2.1.7p400 (2015-08-18 revision 51632) [x86_64-darwin14.0]

**Comment by sethk** [comment]
RFC 2616 14.44:

> An HTTP/1.1 server SHOULD include a Vary header field with any cacheable response that is subject to server-driven negotiation. Doing so allows a cache to properly interpret future requests on that resource and informs the user agent about the presence of negotiation on that resource.

http://www.w3.org/Protocols/rfc2616/rfc2616-sec14.html#sec14.44

**Comment by maclover7** [comment]
Going to close in favor of the already existing rails/jquery-ujs#318 issue, to keep the discussion centralized in one place -- @sethk, would you be willing to open up a PR to fix this?

**Comment by matthewd** [comment]
This is a Rails issue.

**Comment by sethk** [comment]
I have worked around this in my app with a `before_filter` callback. The real fix may be pretty simple, but I think there's a high potential for downstream effects. I'm hoping someone who knows the code can at least provide feedback about which layer it should go into. I will try to provide a test for this.

**Comment by DanielHeath** [comment]
More generally I'd like to see rails intercept any attempt to read any request headers and update the `vary` header appropriately (by default).

**Comment by DanielHeath** [comment]
To clarify: I'm proposing that `ActionDispatch::HTTP::Headers` in `actionpack/lib/action_dispatch/http/headers.rb` be able to track which keys have been accessed.
At the end of the request/response cycle, if a cache control header is present, add all of those request header names to the `vary` header.

**Comment by sethk** [comment]
Oh gosh, I mean I know this is Rails, but that sounds like some serious magic. What if all the headers are accessed for debugging or analytics purposes?

**Comment by DanielHeath** [comment]
In that case there would be an information leak (possibly bad! it definitely needs to be obvious that it's going to happen somehow) but nothing would break.

**Comment by DanielHeath** [comment]
One option (avoids the risk of breaking existing apps): put it under a config flag, default to off, and enable it in `application.rb` for newly generated rails apps.

**Comment by sgrif** [comment]
I think that `Vary: Accept` is a reasonable default. I'm strongly against any magic of exposing all accessed headers. At a certain point it is up to the application to specify when they're varying.

**Comment by DanielHeath** [comment]
@sgrif: people *keep* getting this wrong. 

Are there ways rails could help them get it right without going too far?

A console warning in development mode?

**Comment by sethk** [comment]
@DanielHeath I don't think it should be the individual application's responsibility to add `Cache-Control: Vary` when that negotiation/routing is done by Rails on behalf of the app, do you? I assume @sgrif means that applications should be responsible for any cache-affecting choices they make after accessing other headers directly, right? The gitlab-org bug you referenced is the exact same behavior & root cause as what I'm seeing in my app with ujs.

**Comment by DanielHeath** [comment]
Good point @sethk - the `Accept` negotiation stuff is built-in to actioncontroller, so it should *at least* set a default `Vary` header for `Accept`.

**Comment by sethk** [comment]
Here is a simple test:

https://gist.github.com/6d5454a30003e2a44ce42226f2715a59

**Comment by st0012** [comment]
I personally don't think this is a bug that needs to be fixed. Adding `Vary: Accept` by default could cause the proxy server to store multiple versions of cache even when it doesn't have to. I suggest using something like

```ruby
    default_headers = config.action_dispatch.default_headers
    config.action_dispatch.default_headers = default_headers.merge("Vary" => "Accept")
```

in your configuration files to setup the `Vary` header.

**Comment by DanielHeath** [comment]
This bug exists because failing to set `Vary: Accept` by default *does* cause proxy servers to serve JSON instead of HTML (or, equally often, vise versa). 

The default behavior in ActionController violates the HTTP spec in a way that causes production websites to break in hard-to-debug ways.

**Comment by st0012** [comment]
@DanielHeath can you point out the specific rule that this behavior breaks? The `RFC 2616` has been superseded by `RFC 7230-7237`. And in `RFC 7231` I can only find 

> An origin server SHOULD send a Vary header field when its algorithm
   for selecting a representation varies based on aspects of the request
   message other than the method and request target

Which I don't think it means `Vary: Accept` should always be set by default.

**Comment by DanielHeath** [comment]
That's the exact rule I'm talking about :)

By default, the ActionController algorithm for selecting a representation varies based on the `Accept` header. 

This header is not part of the request method or target, and it is checked to determine whether to render a `.html.erb` or a `.js.erb` view, or if you use a `respond_to` block. 

The `Vary` header should be added in the same place so that if you aren't using that part of ActionPack you don't get the header.

**Comment by st0012** [comment]
@DanielHeath I opened a PR for this, can you give it a look? https://github.com/rails/rails/pull/36213

**Comment by st0012** [comment]
Here's another discussion about the `Vary` header: https://github.com/rails/rails/pull/23120

**Comment by st0012** [comment]
@rafaelfranca think this can be closed as well since #36213 is merged?

**Comment by nomis** [comment]
> @rafaelfranca think this can be closed as well since #36213 is merged?

The `Vary: Accept` header should be added for any URL where the content could change based on the `Accept` header.

It should not be omitted on the `html` format if there's another format for the same URL because a proxy may then cache the HTML page and return it in response to an XMLHttpRequest.

When the `js` format is returned it should be specifying `Vary: X-Requested-With` (or `Vary: Accept, X-Requested-With`).

**Comment by DanielHeath** [comment]
I believe that's what has been implemented. Reading the linked PR, the vary header is set whenever the `Accept` header is used to determine the request format, which applies to any request that doesn't specify the format in the URL.

**Comment by nomis** [comment]
It explicitly does not set the `Vary` header if the request is "like a browser" (i.e. HTML):
https://github.com/rails/rails/pull/36213/files#diff-2bdf5835d9c0e57a51b76779d387d02291f0b1d4f9fc93ee811cf608c3416babR163-R165
