### ISSUE TITLE
Can't bundle install if sass-rails doesn't include ~> (can't find railties)

### ISSUE THREAD

**Issue by nicoschuele** [rails/rails#25855]
### Steps to reproduce

If in the Gemfile I want to lock `sass-rails` to `5.0.0` by adding the sass-rails gem like this:

`gem 'sass-rails', '5.0.0'`

I get the following error upon running `bundle install`:

```
Bundler could not find compatible versions for gem "railties":
  In Gemfile:
    rails (= 5.0.0) was resolved to 5.0.0, which depends on
      railties (= 5.0.0)

    sass-rails (= 5.0.0) was resolved to 5.0.0, which depends on
      railties (< 5.0, >= 4.0.0)
```

Now, if I update the Gemfile to:

`gem 'sass-rails', '~> 5.0.0'`

...`bundle install` runs perfectly.

### Expected behavior

It should be possible to lock sass-rails to a specific version without using `~>`

### System configuration
**Rails version**: 5.0.0

**Ruby version**: 2.3.1p112

**Comment by sevenseacat** [comment]
But now you're not locked to 5.0.0, and you haven't installed 5.0.0.

**Comment by prathamesh-sonpatki** [comment]
@sevenseacat is right. You need to use sass-rails 5.0.5 for Rails 5 compatibility. Please check https://github.com/rails/sass-rails/pull/375 for more details. Thanks!

**Comment by nicoschuele** [comment]
@sevenseacat @prathamesh-sonpatki Thanks! I didn't even notice the minimum version that works with Rails. I simply assumed Rails 5.0.0 should work with Sass-Rails 5.0.0 ;-)
