### ISSUE TITLE
On ruby dev rounding causes iso8601 serializer with precision to create different value

### ISSUE THREAD

**Issue by vipulnsward** [rails/rails#25865]
I am unsure of what the resolution should be, so opening up an issue here. 
We test duration here- https://github.com/vipulnsward/rails/blob/629dde297ce5e4b7614fbb0218f2593effaf7e28/activesupport/test/core_ext/duration_test.rb#L293-L293

``` ruby
➜  activesupport git:(master) b ruby -Itest test/core_ext/duration_test.rb -n test_iso8601_output_precision
Run options: -n test_iso8601_output_precision --seed 32455

# Running:

F

Finished in 0.010849s, 92.1744 runs/s, 276.5232 assertions/s.

  1) Failure:
DurationTest#test_iso8601_output_precision [test/core_ext/duration_test.rb:304]:
"P1Y1MT5.5S".
Expected: "P1Y1MT5.5S"
  Actual: "P1Y1MT5.6S"

1 runs, 3 assertions, 1 failures, 0 errors, 0 skips
```

This is currently failing on master + ruby-dev because of the behaviour change of `sprintf %.01f`.

``` ruby
on 2.4-dev


irb(main):006:0> sprintf "%0.01f", 5.55
=> "5.6"
irb(main):007:0> 5.55.class
=> Float

on 2.4-preview

irb(main):001:0> sprintf "%0.01f", 5.55
=> "5.5"
irb(main):002:0> 5.55.class
=> Float
irb(main):003:0>
```

ruby issue here- https://bugs.ruby-lang.org/issues/12580
I see that this is actually a fix, over how it was previously printed, so is an improvement.

Question is, what needs to be done on our end, since this is a somewhat change in behaviour for ISO8601 parser. Do we handle on ruby 2.4+ differently, or leave as is, and accommodate this in our tests.

cc @jeremy @Envek @arnau

**Comment by Envek** [comment]
I will look, can we replaсe `sprintf` here to anything else. If can, I will replace it. If not, I think it's better change tests to something like (so we will check precision handling, but avoid version-specific rounding):

```rb
[1,   'P1Y1MT5.4S',   1.year + 1.month + (5.44).seconds ],
```

Any other ideas?
