### ISSUE TITLE
[Rails 5.0.0] rake doc:guides, doc:app, doc:rails, doc:plugins  no longer works 

### ISSUE THREAD

**Issue by ArpiaPsuv** [rails/rails#25872]
Unable to generate the documentation!

### Steps to reproduce

When I try to generate the  rails documentation 

rake doc:app
rake doc:guides 
rake doc:rails 
rake doc:plugins 

### Actual behavior
Don't know how to build task 'doc:app'
Don't know how to build task 'doc:guides'
Don't know how to build task 'doc:rails'

### System configuration
Linux cleopatra 4.2.0-38-generic #45~14.04.1-Ubuntu SMP Thu Jun 9 09:28:50 UTC 2016 i686 athlon i686 GNU/Linux

**Rails version**: Rails 5.0.0

**Ruby version**: ruby 2.3.1p112 (2016-04-26 revision 54768) [i686-linux]

**Comment by vipulnsward** [comment]
It has been removed starting with Rails 5
https://github.com/rails/rails/commit/cd7cc5254b090ccbb84dcee4408a5acede25ef2a
