### ISSUE TITLE
ActiveRecord `.references` is JOINing all relations in `.includes`

### ISSUE THREAD

**Issue by jeremyblalock** [rails/rails#25893]
### Steps to reproduce

1. Create three models **A**, **B**, & **C**, such that **A** `has_many` **B**'s and **A** `has_many` **C**'s

  ```
  class A < ActiveRecord::Base
    has_many :bs
    has_many :cs
  end
  ```
2. Attempt to query on a relation, without a `.joins` or `.references` (this should fail)

  ```
  puts  A.includes(:bs, :cs).where('bs.id IS NOT NULL')
    # DEBUG: SELECT "as".* FROM "as" WHERE (bs.id IS NOT NULL)
    # ==> ActiveRecord::StatementInvalid: PG::UndefinedTable: ERROR:  missing FROM-clause entry for table "bs"
  ```

3. Now, add a `.references(:cs)`, and notice how `:bs` is referenced as well:

  ```
  puts  A.includes(:bs, :cs).where('bs.id IS NOT NULL').references(:cs)
    # DEBUG: SELECT "as"."id" AS t0_r0, "as"."created_at" AS t0_r1, "as"."updated_at" AS t0_r2, "bs"."id" AS t1_r0, "bs"."a_id" AS t1_r1, "bs"."created_at" AS t1_r2, "bs"."updated_at" AS t1_r3, "cs"."id" AS t2_r0, "cs"."a_id" AS t2_r1, "cs"."created_at" AS t2_r2, "cs"."updated_at" AS t2_r3 FROM "as" LEFT OUTER JOIN "bs" ON "bs"."a_id" = "as"."id" WHERE (bs.id IS NOT NULL)
    # ==> #<ActiveRecord::Relation [ ... ]>
  ```

### Expected behavior

I would expect that adding a `.references(:relation_name)` would `JOIN` join `relation_name`, and not _all_ included relations. Fetching included models separately is more performant, I would hope that this performance benefit can still be felt when using `.references` on just one relation.

### Actual behavior

When `.references` is used on _any_ relation, **all** relations in the `.includes( ... )` statements are `JOIN`'ed.

### System configuration
**Rails version**: 4.x.x, 5.x.x

**Ruby version**: 2.2.2

**Comment by matthewd** [comment]
Yeah, this is known behaviour. I'm not sure how feasible it is to change at this stage. :confused:

Either way, this would count as a feature request, which we don't keep issues open for.

Thanks for the report, though. I hope we can find a way to improve this in the future.

**Comment by ignatiusreza** [comment]
for what its worth, the following should work as TS expected:

```
A.preload(:cs).eager_load(:bs).where('bs.id IS NOT NULL')
```

**Comment by jeremyblalock** [comment]
Thanks so much @ignatiusreza. Do you know if there are any performance implications to using `eager_load` / `preload`? Or is this essentially just forcing ActiveRecord to do things a particular way?
