### ISSUE TITLE
Rails stops logging after a while

### ISSUE THREAD

**Issue by nowakov** [rails/rails#25890]
### Steps to reproduce

It's hard to pinpoint steps to reproduce.
### Expected behavior

Logger should log all the time
### Actual behavior

Logger stops working after few hours after deploy(=server restart) and works again after puma restart. Nginx logs are fine, so it must be error on ruby side.
### System configuration

ruby 2.3.1
Rails 5.0.0
puma 3.4.0
multi_logger 0.1.0

**Comment by rafaelfranca** [comment]
Does it happen without multi_logger? It may be a multi_logger issue.

**Comment by dwbutler** [comment]
Are you using `silence` and `Rack::Timeout`? It sounds to me like the log level is being set too high, and then not getting set back to its normal level. This can happen if `Rack::Timeout` terminates a thread right [here](https://github.com/rails/rails/blob/2518bda97cbbcb33dc9a92e70d5b01c09e64d12d/activesupport/lib/active_support/logger_silence.rb#L18).

**Comment by nowakov** [comment]
Hey. It behaves the same withour multi_logger. I've changed log level to lower and will get back to you with feedback. Thanks!

**Comment by dwbutler** [comment]
This issue is similar to https://github.com/dwbutler/logstash-logger/issues/17. The issue could be caused by anything that is changing the log level and then not changing it back.

**Comment by nowakov** [comment]
It was caused by server's logrotate
