### ISSUE TITLE
Newly generated app should enforce minimal web-console version

### ISSUE THREAD

**Issue by voxik** [rails/rails#25899]
### Steps to reproduce

I installed rails 5 and generated really minimal application. I skipped almost everything I could:

```
$ rails new tr --skip-bundle --skip-git --skip-puma --skip-spring --skip-listen --skip-javascript --skip-turbolinks --skip-active-record --skip-action-cable --skip-sprockets
```

And tried to run the application:

```
$ cd tr/
$ rails s
DEPRECATION WARNING: Accessing mime types via constants is deprecated. Please change `Mime::HTML` to `Mime[:html]`. (called from <top (required)> at /builddir/tr/config/application.rb:17)
DEPRECATION WARNING: Accessing mime types via constants is deprecated. Please change `Mime::TEXT` to `Mime[:text]`. (called from <top (required)> at /builddir/tr/config/application.rb:17)
DEPRECATION WARNING: Accessing mime types via constants is deprecated. Please change `Mime::URL_ENCODED_FORM` to `Mime[:url_encoded_form]`. (called from <top (required)> at /builddir/tr/config/application.rb:17)
=> Booting WEBrick
=> Rails 5.0.0 application starting in development on http://localhost:3000
=> Run `rails server -h` for more startup options
[2016-07-20 16:39:43] INFO  WEBrick 1.3.1
[2016-07-20 16:39:43] INFO  ruby 2.3.1 (2016-04-26) [x86_64-linux]
[2016-07-20 16:39:43] INFO  WEBrick::HTTPServer#start: pid=26108 port=3000
Started GET "/" for 127.0.0.1 at 2016-07-20 16:39:55 +0200
Started GET "/" for 127.0.0.1 at 2016-07-20 16:41:11 +0200
^C[2016-07-20 16:46:47] INFO  going to shutdown ...
[2016-07-20 16:46:47] INFO  WEBrick::HTTPServer#start done.
Exiting
```

But the problem is that this app did no run as epxected. I just got error 500 and as you can see, there is no issue mentioned in the log.

Later I executed the same application with Ruby debug enabled:

```
$ RUBYOPT=-d rails s
```

which unveiled possible error:

```
Exception `NoMethodError' at /usr/share/gems/gems/actionpack-5.0.0/lib/action_dispatch/middleware/remote_ip.rb:112 - undefined method `remote_addr' for nil:NilClass
```

Quick Google query gave me this answer [1]. Which quickly pointed out that my installed web-console 2.2.1 is probably not compatible with Rails 5.

### Expected behavior
1. Rails restricts the minimal compatible web-console version (3.1 according to the web-console CHANGELOG?)
2. Rails does not swallow all the debug information, which could help to identify what is the problem.

### Actual behavior
1. Rails does not restrict web-console version, which might be incompatible.
2. Rails does not provide any helpful information to help to analyze the issue.

### System configuration
**Rails version**:
5.0.0

**Ruby version**:
2.3.1

[1] https://github.com/rails/web-console/issues/155

**Comment by maclover7** [comment]
Thank you for reporting!

It might make sense for us to [pin the version](https://github.com/rails/rails/blob/master/railties/lib/rails/generators/rails/app/templates/Gemfile#L38) of `web-console` we are using, to avoid an compatibility issues. 😬 

cc @gsamokovarov
