### ISSUE TITLE
Question: Can we always deserialize json in ActiveRecord to HashWithIndifferentAccess?

### ISSUE THREAD

**Issue by david50407** [rails/rails#25894]
On Rails 5.0, we deserialize json type into `Hash`.

But only strings can be keys in JSON, if we store a hash with symbol keys and string keys, that could be dangerous, like: 

```
# Model Foo has a json column named `data`
Foo.create data: { :a => 1, 'a' => 2 } #=> #<Foo data: { "a" => 2 }>
Foo.create data: { 'a' => 2, :a => 1 } #=> #<Foo data: { "a" => 1 }>
```

This can happened while using `#merge` or other methods to editing `Hash`.

Can we use `ActiveSupport::HashWithIndifferentAccess` instead of `Hash` that we can use methods, like `#merge`, with symbol keys?

**Comment by rafaelfranca** [comment]
It is not possible to fix this since we don't have information which key was a symbol and which key was a string after it is serialized as JSON:

```irb
>> JSON.dump({ 'a' => 2, :a => 1 })
=> "{\"a\":2,\"a\":1}"
```

So because of this we can't deserialize it with the correct information even if it was a `ActiveSupport::HashWithIndifferentAccess`

**Comment by david50407** [comment]
@rafaelfranca no, I don't want to deserialize back to symbol or string, just want to use both symbol and string keys to access the json data

In other words, if the string key and the symbol key are same they should point to the same data.

If we use `ActiveSupport::HashWithIndifferentAccess` inside models, we can do some operations like:

```ruby
data = { a: 1 }
data2 = { 'a' => 2 }

Foo.create data: data.merge(data2) #=> `data` always be { 'a' => 2 } with symbol accesses
```

Or, for me, the most used operation like this: 

```ruby
foo = Foo.find(1) #=> #<Foo data: { "some" => { "foo" => 1 } }>
foo.data.deep_merge!({
  some: {
    bar: 2
  }
})
foo.data #=> { "some" => { "foo" => 1 }, :some => { :bar => 2 } }
# I expected { "some" => { "foo" => 1, "bar" => 2 } } if we use HashWithIndifferentAccess

foo.save #=> #<Foo data: { "some" => { "bar" => 2 } }> 
# In json, it will use the last value when keys are duplicated.
# But if we use HashWithIndifferentAccess, it can be { "some" => { "foo" => 1, "bar" => 2 } }
```

**Comment by rafaelfranca** [comment]
I see. If you want to work like that you can do calling `with_indiferent_access` in the hash. I really think that it is a bad idea to work with symbol keys in data hashes because different serialization methods always returns strings from the backend, since they don't know anything about symbols.

**Comment by david50407** [comment]
@rafaelfranca but `#with_indiferent_access` creates another instance of the hash, so I have to do like this:

```ruby
foo = Foo.find(1) #=> #<Foo data: { "some" => { "foo" => 1 } }>
foo.data = foo.data.with_indiferent_access.deep_merge!({
  some: {
    bar: 2
  }
})
foo.data.class #=> Hash
foo.save
```

And if the `ActiveSupport::HashWithIndifferentAccess` passed into the model, it will be casted into Hash automatically (even I haven't save yet), so I have to do `with_indiferent_access` again and again if I want to use with symbol (or I don't know the data is using symbol or string keys) every time.

I know that backend doesn't know anything about symbols, but we use symbol keys in Hash more often than using strings, if Rails can bridge these automatically, that will be cool.

**Comment by david50407** [comment]
We use `ActionController::Parameters` in controllers that accepts using symbols or string as key to access the same value (it stores all symbol-keys into string-keys so that can produce string-key hash so fast just like what `ActiveSupport::HashWithIndifferentAccess` does).

If we use `ActiveSupport::HashWithIndifferentAccess` instead of `Hash` in json columns, that we can access with symbols just like other place in Rails (and this won't break how we store and load data with backends).

**Comment by rafaelfranca** [comment]
I personally dislike `HashWithIndifferentAccess` and I really don't want to promote it in the framework. `Parameters` was already implemented as `HashWithIndifferentAccess` but if I would implement it today I'd remove that support.

**Comment by wayne5540** [comment]
Simple workaround could be like this:

```rb
class Foo < ApplicationRecord
  def data
    super.with_indiferent_access
  end
end
```

**Comment by vchervanev** [comment]
For read/write access I ended up using
```ruby
  def data
    @data ||= super.deep_symbolize_keys!
  end
```
and softly enforce to use only symbol keys

**Comment by CarlosCD** [comment]
I know this is old. I've just bumped into something similar.

It seems that if you want symbols as keys, JSONB is not the right format. I believe @rafaelfranca is right. You can always serialize your Hash as YAML.

But if you want to have the ability to run queries in PG using JSONB, and at the same time use symbols in Ruby-land, then you always have the option of write your own serializer, something like:

```
     class HashAsJsonbSerializer

       def self.dump(hash)
         hash
       end

       def self.load(hash)
         # Or if you only want keys as symbols, maybe:
         #   hash.is_a?(Hash) ? hash.symbolize_keys : {}
        (hash.is_a?(Hash) ? hash : {}).with_indifferent_access
       end

     end
```
And then call the class method in your model:

```
  serialize :my_hash_column, HashAsJsonbSerializer
```
