### ISSUE TITLE
Aliased attributes don't play nice with enum

### ISSUE THREAD

**Issue by thomasfedb** [rails/rails#25892]
### Steps to reproduce

Create a model which has an `enum` declared on an aliased attribute:

```
class Person < ActiveRecord::Base
  alias_attribute :citizenship_status, :citizen

  enum citizenship_status: { citizen: 1, foreigner: 0 }
end
```

### Expected behavior

The query methods (`citizen?` and `foreigner?`) should function on model instances and return `true` if their respective values equal `citizenship_status`.

### Actual behavior

The query methods always return `false`.

### System configuration

**Rails version**: 4.2.7, 5.0.0

**Ruby version**: 3.2.1

**Comment by aranair** [comment]
Accessing the value of the alias'ed enum attribute wrongly returns the integer value instead of the string as well. Reproducing both via [this gist](https://gist.github.com/aranair/5c6ff207eafaa71d8eac23c37091369f)

**Comment by thomasfedb** [comment]
@aranair I can reproduce that also in my application.

**Comment by maclover7** [comment]
cc @sgrif

**Comment by sgrif** [comment]
This behavior isn't meant to be supported. `attribute_alias` allows you to create an alias for an attribute, but it doesn't create a "new" attribute that you can change the type of, etc. This type of functionality is something that may be added in the future, but it's not a bug.

**Comment by amatsuda** [comment]
@sgrif Let me point out a fact that `Person.citizen` used to work on AR 4.2 but it's broken on 5.0 (since c51f9b61ce1e167f5f58f07441adcfa117694301, I guess)
4.2: `SELECT "people".* FROM "people" WHERE "people"."citizen" = ?  [["citizen", 1]]`
5.0: `SELECT "people".* FROM "people" WHERE "people"."citizen" = ?  [["citizen", nil]]`

Shouldn't this be considered a regression?

**Comment by sgrif** [comment]
I'll take another look, but no I don't think this is a regression.
