### ISSUE TITLE
New `before_commit` hook in Rails 5?

### ISSUE THREAD

**Issue by Adamantish** [rails/rails#25896]
### Source indicates yes. Documentation say ❓ 

This is [here](https://github.com/rails/rails/blob/5-0-stable/activerecord/lib/active_record/connection_adapters/abstract/transaction.rb#L79)
```ruby
      def before_commit_records
        records.uniq.each(&:before_committed!) if @run_commit_callbacks
      end
```
and
```ruby
    included do
      define_callbacks :commit, :rollback,
                       :before_commit,
                       :before_commit_without_transaction_enrollment,
```
I discovered this while patching rails 4.2. I'm making a `before_commit_batch` callback to be defined at the Model class level and run just once before commit.

It looks like this new feature isn't that but how come no mention of it?

####Update
Just found the answer here: https://github.com/rails/rails/pull/18936

**Comment by rafaelfranca** [comment]
It is not public API and should be not used in applications. It is for Rails internal usage.
