### ISSUE TITLE
Wrong API formatting for protect_from_forgery "prepend" option

### ISSUE THREAD

**Issue by rosenfeld** [rails/rails#25910]
http://api.rubyonrails.org/classes/ActionController/RequestForgeryProtection/ClassMethods.html

I would create a PR if I knew enough about how to format params to prevent this issue.

**Comment by EddM** [comment]
I imagine this has been fixed since the docs at `api.rubyonrails.org` were last generated, since this seems to be formatted correctly on master currently

**Comment by rosenfeld** [comment]
Yes, I can confirm it:

http://edgeapi.rubyonrails.org/

Thanks.
