### ISSUE TITLE
accepts_nested_attributes_for affects parent relation object_id

### ISSUE THREAD

**Issue by kirs** [rails/rails#25915]
### Steps to reproduce

```ruby
require 'bundler/setup'
require 'active_record'

ActiveRecord::Base.establish_connection(adapter: 'sqlite3', database: ':memory:')
ActiveRecord::Schema.define do
  create_table "shops" do |t|
    t.string "title"
  end
  create_table "users" do |t|
    t.string "name"
    t.references "shop"
  end
end

class Shop < ActiveRecord::Base
  has_many :users
end

class User < ActiveRecord::Base
  belongs_to :shop
end

shop = Shop.create!
shop.users.create!

def compare_parent_object_ids
  shop = Shop.last
  user = shop.users.first

  puts user.shop == shop
  puts user.shop.object_id == shop.object_id
end

compare_parent_object_ids
=> true
=> true

Shop.accepts_nested_attributes_for(:users)

compare_parent_object_ids
=> true
=> false
```

### Expected behavior

`shop.object_id == shop.users.first.shop.object_id` is always `true`

### Actual behavior

`shop.object_id == shop.users.first.shop.object_id` is `true` for all relations except for those who use `accepts_nested_attributes_for`.

### System configuration
**Rails version**: 4.2.7 (also reproduces on 5.0.0)

**Ruby version**: 2.3.0 and `2.2.3`.

### Story
The background of this issue is that after getting rid of `protected_attributes` gem at Shopify, we've noticed some difference in AR object behaviour. So I'd like to notice that if you add `protected_attributes` gem, `shop.object_id == shop.users.first.shop.object_id` will always be `true` even for nested relations.

@rafaelfranca @sgrif this is the issue we've been trying to debug last week.

**Comment by sgrif** [comment]
This is actually a bug in `protected_attributes`, not Rails. The disabling of automatic inverse of is intentional (though something that will be removed in Rails 5.1)

**Comment by rafaelfranca** [comment]
Indeed, the protected_attributes gem is out of sync with the Rails code.

**Comment by kirs** [comment]
I mentioned protected_attributes only to provide the background of my issue. Even if it's not a Rails bug, I'm still surprised that using nested_attributes may change relations behaviour.

@sgrif why do we disable automatic reverse when `accepts_nested_attributes_for` macro is declared?

**Comment by rafaelfranca** [comment]
@kirs https://github.com/rails/rails/pull/23197 explain about why autosave associations have automatic inference of inverse_of disabled.

**Comment by kirs** [comment]
Thanks!
