### ISSUE TITLE
ssl_options ignores redirect exclude option

### ISSUE THREAD

**Issue by briantigerchow** [rails/rails#25918]
### Steps to reproduce

``` ruby
Rails.application.configure do
  config.force_ssl = true
  config.ssl_options = { redirect: { exclude: -> request { request.path =~ /health/ } } }
end
```

### Expected behavior

requests to `/_health` should not be redirected to https.

### Actual behavior

requests to `/_health` are redirected to https.

actionpack-5.0.0/lib/action_dispatch/middleware/stack.rb:35
``` ruby
def build(app)
  klass.new(app, *args, &block)
end
```

```
klass == ActionDispatch::SSL
args == [{:hsts=>{:subdomains=>true}}]
```

### System configuration

**Rails version**:
5.0.0
**Ruby version**:
2.3.1-p112

**Comment by kaspth** [comment]
Ah! I think the ssl_options are being overriden by the new framework defaults file: https://github.com/rails/rails/blob/aea0e5cd709e0fc53e1ba4e87235b8ee3f4bc155/railties/lib/rails/generators/rails/app/templates/config/initializers/new_framework_defaults.rb.tt#L33

That's a bug, do you want to submit a PR to help fix it? 😁

**Comment by kaspth** [comment]
The fix would be a way to have the new framework defaults co-exist with a preassigned `ssl_options`.

cc @prathamesh-sonpatki

**Comment by prathamesh-sonpatki** [comment]
Yup, agree! @briantigerchow let me know if you need any help with the PR :smile:

**Comment by briantigerchow** [comment]
> Yup, agree! @briantigerchow let me know if you need any help with the PR 😄

I am not familiar enough with the Rails framework / initialization process to know where the new framework defaults are processed. Could you point me in the right direction?

**Comment by kaspth** [comment]
@briantigerchow that file is generated or updated when you either run `rails new some-app` or `bin/rails app:update`.

The file itself is an initializer. There's a paragraph on those here: http://guides.rubyonrails.org/configuring.html#using-initializer-files.

**Comment by briantigerchow** [comment]
Is this satisfactory?

``` ruby
Rails.application.config.ssl_options.deep_merge! { hsts: { subdomains: true } }
```

**Comment by rafaelfranca** [comment]
I don't think we have something to fix here. The developer should carefully review their configurations. If there is already an initializer setting this configuration why would the developer set it again in application.rb? The initializer code should not be defensive against this kind of thing.

**Comment by kaspth** [comment]
@rafaelfranca I'm with you there, and having to do merges feels like a smell. I think this case is a little different though in that `ssl_options` is an old config and it's odd that it gets overridden in a newly generated initializer.

**Comment by rafaelfranca** [comment]
Well, it is a generated file. People should review carefully that new file
to avoid things to be configured wrongly and overridden. It was never made
to blindly commit to the repository even more because these new defaults
are breaking changes.

**Comment by kaspth** [comment]
Yeah I like that as a signal that someone's update tempo is a bit too brisk.

@briantigerchow how did you come across this? Was it a new app or an existing one you upgraded?

What I'm really going for is, was the new framework defaults file present when you tried to set `ssl_options`? Then how did you figure out where to place that config, from documentation or just yourself?

**Comment by briantigerchow** [comment]
I generated the project as a rails 5.0.0 rc1 project on May 18.

I updated to the rails 5.0.0 gem on July 1.


Last night, I googled: `force_ssl "rails 5" exclude` and found [an issue](https://github.com/betterup/acme-authorizer/issues/1) which led me to[ the source code](https://github.com/rails/rails/blob/52ce6ece8c8f74064bb64e0a0b1ddd83092718e1/actionpack/lib/action_dispatch/middleware/ssl.rb#L38-L40) for `ActionDispatch::SSL`.

Then, I tried to use the following in my environments/production.rb file:

``` ruby
Rails.application.configure do
  config.force_ssl = true
  config.ssl_options = { redirect: { exclude: -> request { request.path =~ /_health/ } } }
end
```

I didn't know that there was an initializer called ssl_options with the contents:
``` ruby
Rails.application.config.ssl_options= { hsts: { subdomains: true } }
```

I suppose this is a user error then, huh?

**Comment by kaspth** [comment]
Thanks for the detailed explanation ❤️

> I suppose this is a user error then, huh?

We try to avoid to adding defensive measures against all the kinds of things that can can end up happening in an app to ease our code's readability and maintainability. I'm sorry this caused you trouble, but that's sometimes how it goes. Thanks for using Rails 5! 😁

**Comment by briantigerchow** [comment]
Thanks for the quick resolution.
