### ISSUE TITLE
skip_action_callback method ignores options

### ISSUE THREAD

**Issue by axvm** [rails/rails#25916]
### Steps to reproduce

``` ruby
begin
  require 'bundler/inline'
rescue LoadError => e
  $stderr.puts 'Bundler version 1.10 or later is required. Please update your Bundler'
  raise e
end

gemfile(true) do
  source 'https://rubygems.org'
  gem 'rails', github: 'rails/rails'
end

require 'action_controller/railtie'

class TestApp < Rails::Application
  config.root = File.dirname(__FILE__)
  config.session_store :cookie_store, key: 'cookie_store_key'
  secrets.secret_token    = 'secret_token'
  secrets.secret_key_base = 'secret_key_base'

  config.logger = Logger.new($stdout)
  Rails.logger  = config.logger

  routes.draw do
    get '/' => 'test#index'
  end
end

class TestController < ActionController::Base
  include Rails.application.routes.url_helpers

  ActiveSupport::Deprecation.silence do
    before_filter :test_exception

    skip_filter :test_exception, if: :test_condition?
  end

  def test_condition?
    false
  end

  def test_exception
    raise
  end

  def index
    render plain: 'Home'
  end
end

require 'minitest/autorun'
require 'rack/test'

class BugTest < Minitest::Test
  include Rack::Test::Methods

  def test_returns_success
    get '/'
    assert last_response.server_error?
  end

  private
    def app
      Rails.application
    end
end
```
### Expected behavior

TestApp must to raise exception 
### Actual behavior

TestApp skips callback
### System configuration

**Rails version**: 5.0.0

**Ruby version**: 2.3.1p112 (2016-04-26 revision 54768)
### What's going on

[`skip_action_callback`](https://github.com/rails/rails/blob/master/actionpack/lib/abstract_controller/callbacks.rb#L66-L68) method appends another hash to args, meanwhile [`Array#extract_options!`](https://github.com/rails/rails/blob/master/activesupport/lib/active_support/core_ext/array/extract_options.rb#L23) returns only last element of Array. This means any other options can't be extracted because of this additional hash in the args.

**Comment by axvm** [comment]
Also I'd like to know if there any alternative for `skip_filter` method? I'm looking for the way to skip every `before`, `after` and `around` callback at once

**Comment by al2o3cr** [comment]
@axvm Regarding your question "how to skip all the callbacks at once": have you considered using a different controller? Not trying to dismiss your original question, but if you have a piece of code that's sufficiently unrelated to the rest of the functionality in a particular controller that it needs to skip ALL the common setup / filters you probably have code that doesn't belong in that controller.

**Comment by NirvashPrime** [comment]
I see this hasn't been updated in a few years, is this still an issue?

**Comment by kamipo** [comment]
`skip_action_callback` had already be removed in Rails 5.1.
Use `skip_{before,after,around}_action` instead.
