### ISSUE TITLE
Rails 4.2.7 should not generate deprecation warnings on rake db:migrate

### ISSUE THREAD

**Issue by joelpresence** [rails/rails#25925]
### Steps to reproduce

rails new pktest --database=postgresql
pushd pktest
rails g scaffold cat name:string age:integer
rake db:create:all
rake db:migrate

(Guidelines for creating a bug report are [available
here](http://guides.rubyonrails.org/contributing_to_ruby_on_rails.html#creating-a-bug-report))

### Expected behavior
Tell us what should happen

Running `rake db:migrate` should **NOT** generate deprecation warnings.

### Actual behavior
Tell us what happens instead

Running `rake db:migrate` does generate deprecation warnings:

```
rake db:migrate
DEPRECATION WARNING: Sprockets method `register_engine` is deprecated.
Please register a mime type using `register_mime_type` then
use `register_compressor` or `register_transformer`.
https://github.com/rails/sprockets/blob/master/guides/extending_sprockets.md#supporting-all-versions-of-sprockets-in-processors
 (called from block (2 levels) in <class:Railtie> at /Users/joel/.rvm/gems/ruby-2.2.2/gems/sass-rails-5.0.5/lib/sass/rails/railtie.rb:57)
DEPRECATION WARNING: Sprockets method `register_engine` is deprecated.
Please register a mime type using `register_mime_type` then
use `register_compressor` or `register_transformer`.
https://github.com/rails/sprockets/blob/master/guides/extending_sprockets.md#supporting-all-versions-of-sprockets-in-processors
 (called from block (2 levels) in <class:Railtie> at /Users/joel/.rvm/gems/ruby-2.2.2/gems/sass-rails-5.0.5/lib/sass/rails/railtie.rb:58)
== 20160722221831 CreateCats: migrating =======================================
-- create_table(:cats)
   -> 0.0435s
== 20160722221831 CreateCats: migrated (0.0436s) ==============================
```

These deprecation warnings are distracting and clog up the terminal.  I am creating a brand new rails app and I have not modified the Gemfile.  Why am I getting deprecation warnings already?  :-(

### System configuration
**Rails version**:
4.2.7

**Ruby version**:
ruby 2.2.2p95 (2015-04-13 revision 50295) [x86_64-darwin14]

**Comment by maclover7** [comment]
👍 Thank you for reporting this! There is already a fix in progress at https://github.com/rails/sass-rails/pull/382.

**Comment by sergio-bobillier** [comment]
This is happening with Rails 4.2.7.1, everytime I run a rake command (even when not related to assets) I get deprecation warnings:

    sergio@sentinel-prime:~/Proyectos/web-viewer [master]$ rake db:migrate:status
    DEPRECATION WARNING: Sprockets method `register_engine` is deprecated.
    Please register a mime type using `register_mime_type` then
    use `register_compressor` or `register_transformer`.
    https://github.com/rails/sprockets/blob/master/guides/extending_sprockets.md#supporting-all-versions-of-sprockets-in-processors
     (called from block (2 levels) in <class:Railtie> at /var/lib/gems/2.3.0/gems/sass-rails-5.0.5/lib/sass/rails/railtie.rb:57)
    DEPRECATION WARNING: Sprockets method `register_engine` is deprecated.
    Please register a mime type using `register_mime_type` then
    use `register_compressor` or `register_transformer`.
    https://github.com/rails/sprockets/blob/master/guides/extending_sprockets.md#supporting-all-versions-of-sprockets-in-processors
     (called from block (2 levels) in <class:Railtie> at /var/lib/gems/2.3.0/gems/sass-rails-5.0.5/lib/sass/rails/railtie.rb:58)
    
    database: web_viewer_dev
    
     Status   Migration ID    Migration Name
    --------------------------------------------------
       up     20160719155847  Create access levels
       up     20160719161548  Create users

Any workaround for this?
