### ISSUE TITLE
find_or_initialize_by query doesn't initiliaze properly when passed an array of records

### ISSUE THREAD

**Issue by andela-oakinniranye** [rails/rails#25922]
### Steps to reproduce
Add a name column to a table
(Optional) Add some records to the table
Query for the following:

```ruby
   #assume table name is User
   user = User.find_or_initiliaze_by(name: ['rafael', 'dhh'])
```

If there's a user matching any part of the query, it would be returned, but if not, the initialized object turns the array to string, as such:

`#<User:0x007f9871bdd768 id: nil, name: "[\"rafael\", \"dhh\"]", created_at: nil, updated_at: nil>`

### Expected behavior
Even though it would have been difficult for AR to determine which of the records it should initialize with, I believe a better interface would probably have initialized with one or both of the records anyway, as such

```ruby
#<User:0x007f9871bdd768 id: nil, name: "rafael", created_at: nil, updated_at: nil>
```

### Actual behavior
The result of the query was:

```ruby
#<User:0x007f9871bdd768 id: nil, name: "[\"rafael\", \"dhh\"]", created_at: nil, updated_at: nil>
```

### System configuration
**Rails version**: Rails 4.2.6

**Ruby version**: Ruby 2.3.1

**Comment by maclover7** [comment]
Hmm, to me this seems like expected behavior -- we are checking to see if a user whose name is `"[\"rafael\", \"dhh\"]"` exists, and otherwise we are creating a user with that name 😬

**Comment by andela-oakinniranye** [comment]
But the SQL query generated uses the `IN` clause like so:

```SQL
SELECT  "users".* FROM "users" WHERE "users"."name" IN ('rafael', 'dhh') LIMIT 1
```

**Comment by maclover7** [comment]
Hmm, agree this seems a little confusing. We should definitely be more explicit about this behavior.

cc @sgrif 

Created a reproduction script for this [here](https://gist.github.com/maclover7/1b70e35e49b694f58764cc22f3e166bc).

**Comment by sgrif** [comment]
We definitely wouldn't set it to the first element of the array. For most types this would end up being `nil`, but strings are a bit quirky here. I agree that the behavior is a bit quirky, but there's not a great "fix" here. It's working as documented, passing the attributes to `new` if the value isn't found.

**Comment by nadavharpazi** [comment]
you have a spelling error here -
User.find_or_initiliaze_by
should be 
User.find_or_initialize_by
