### ISSUE TITLE
Ignore autoload my module in production environment

### ISSUE THREAD

**Issue by okamos** [rails/rails#25943]
### Steps to reproduce

`lib/cat.rb`
```rb
module Cat
  def self.meow
    return 'nya'
  end
end
```

`config/application.rb`
```rb
  class Application < Rails::Application
    config.autoload_paths += %W(#{config.root}/lib)
  end
```

And call module method.

`app/controllers/animals_controller.rb`
```rb
class AnimalsController < ApplicationController
  def index
    render plain: Cat.meow
  end
end

```

### Expected behavior
render text nya

### Actual behavior
```rb
NameError (uninitialized constant AnimalsController::Cat)
```

**This error occur only production environment.**

### System configuration
**Rails version**:
`5.0.0`

**Ruby version**:
`2.3.1`

**Comment by rafaelfranca** [comment]
In rails 5 autoload is disabled in production. You need to use eager_load_paths
