### ISSUE TITLE
Date_field format

### ISSUE THREAD

**Issue by vickeysi** [rails/rails#25947]
### Steps to reproduce

(Guidelines for creating a bug report are [available
here](http://guides.rubyonrails.org/contributing_to_ruby_on_rails.html#creating-a-bug-report))

### Expected behavior
1) 
 cannot change the time format , in date_field 
<%= f.date_field :start_date , value: Date.today.strftime("%d-%m-%Y")  %>
this should generate 31-01-2001 .
firefox support
2 )
<%= f.date_field :date, min: Date.now(1994, 07, 03), max: Date.today %>
the date should not be editable in text with keyboard .

### Actual behavior
1) 
<%= f.date_field :start_date , value: Date.today.strftime("%d-%m-%Y")  %>
even tough it's format  .  it's hard coded as %m-%d-%y  . 
this generate's 01-31-2001 .
 2)
<%= f.date_field :date, min: Date.now(1994, 07, 03), max: Date.today %>
min and max works fine in pop over calender but when directly editted using keyboard it accept all the  date .

### System configuration
**Rails version**:  Rails 4.2.6

**Ruby version**:  ruby 2.3.0p0 (2015-12-25 revision 53290) [x86_64-linux]

**Comment by rafaelfranca** [comment]
This behavior is the browser behavior, Rails just generates the HTML tag.

**Comment by user-matth** [comment]
You can try to use:

`f.date_field :some_name, value: @some_time.strftime('%d.%m.%Y')`

What really makes the difference is strftime (String for Time), but I'm using Ruby on Rails with Slim and it's not working
