### ISSUE TITLE
ActiveRecord's `empty?` and `any?` should use more efficient behavior from `exists?`

### ISSUE THREAD

**Issue by JacobEvelyn** [rails/rails#25957]
### Steps to reproduce

```ruby
> puts Benchmark.measure { User.all.empty? }
  0.000000   0.000000   0.000000 (  2.419133)
=> nil
> puts Benchmark.measure { User.all.any? }
  0.000000   0.000000   0.000000 (  0.756130)
=> nil
> puts Benchmark.measure { User.all.exists? }
  0.000000   0.000000   0.000000 (  0.007413)
=> nil
```

### Expected behavior

As far as I can tell, the `empty?` and `any?` ActiveRecord methods don't need to perform a `COUNT(*)` query, which can be expensive on large tables. They can simply use the `SELECT  1 AS one ... LIMIT 1` construction that `exists?` uses, which is significantly faster.

### Actual behavior

`empty?` and `any?` perform slower `COUNT(*)` queries.

### System configuration
**Rails version**: 4.1 (but to my knowledge this behavior is the same on newer Rails versions)

**Ruby version**: 2.2

**Comment by matthewd** [comment]
This was changed in 02da8aea

**Comment by JacobEvelyn** [comment]
Ah I missed that, thanks!
