### ISSUE TITLE
[4.2.*] Calling #dup on a model using serialized attributes causes troubles

### ISSUE THREAD

**Issue by lacco** [rails/rails#25954]
I am using ```serialize``` to set complex attributes for my models. While upgrading my application from Rails 4.1 to 4.2, I had failing tests which I could track down to the call of ```#dub```. This doesn't seem to be an issue with Rails <=4.1 and =5.0. 

### Steps to reproduce
See this [gist](https://gist.github.com/lacco/9a22c0be0c6ce18787bc6ada6cca39f9#file-rails_dup_test-rb).

    class NamesSerializer
      def self.load(data)
        data.present? ? ActiveRecord::Coders::JSON.load(data) : ["A Name"]
      end

      def self.dump(names)
        ActiveRecord::Coders::JSON.dump(names)
      end
    end

    class Product < ActiveRecord::Base
      serialize :names, NamesSerializer
    end

    class BugTest < Minitest::Test
      def test_dup
        assert_equal 'A Name', Product.new.names.first

        # Uncommenting this line or replacing #dup with #clone makes the test green
        Product.new.dup

        Product.new.names.first.replace('Just Another Name')

        assert_equal 'A Name', Product.new.names.first
      end
    end

### Expected behavior
Calling ```#dup``` should not change the default value for ```serialize```d attributes. In fact, from then on ```serialize```d attributes are returning the **same** objects.

### Actual behavior
Calling ```#dup``` changes the default value for ```serialize```d attributes.

### System configuration
**Rails version**: 4.2.7
**Ruby version**: 2.3.0

I am willing to dig deeper into this topic, but I have no idea how to start debugging with it.

**Comment by sgrif** [comment]
Confirmed that this is fixed in Rails 5, and that issue occurs with the provided gist on 4-2-stable.

**Comment by sgrif** [comment]
Fixed by #25966

**Comment by lacco** [comment]
@sgrif Thank you so much for fixing this so fast! I just tried it out, my problem is solved on 4-2-stable. This is awesome work, I really appreciate it!
