### ISSUE TITLE
ActionCable on AWS ElasticBeanstalk cause `WebSocket connection to 'ws://{hostname}/cable' failed: WebSocket is closed before the connection is established.`

### ISSUE THREAD

**Issue by YoonjaeYoo** [rails/rails#25955]
I get `WebSocket connection to 'ws://{hostname}/cable' failed: WebSocket is closed before the connection is established`. in my chrome browser when connecting to my Rails 5 + ActionCable app. In my local development environment, it doesn't happen. It only happens in my staging and production environment.

I use Amazon ElasticBeanstalk to deploy my app. After monitoring requests with chrome developer tool, I figured out that unlike development environment, WebSocket request in staging, production environment doesn't get response(pending) so ActionCable constantly tries to connect to the WebSocket endpoint (ws://{hostname}/cable).

The thing is, in my puma.log, it says something like this:
```
I, [2016-07-26T13:45:53.921154 #32369]  INFO -- : Registered connection (Z2lkOi8vYXNrLWNvLWRlL1VzZXIvMg)
I, [2016-07-26T13:46:05.775788 #32369]  INFO -- : Finished "/cable/" [WebSocket] for 121.166.105.106 at 2016-07-26 13:46:05 +0000
I, [2016-07-26T13:46:18.074895 #32369]  INFO -- : [917fd706-4f1a-4178-bd95-7a33c0c7b621] Started GET "/cable" for 121.166.105.106 at 2016-07-26 13:46:18 +0000
I, [2016-07-26T13:46:18.075764 #32369]  INFO -- : [917fd706-4f1a-4178-bd95-7a33c0c7b621] Started GET "/cable/" [WebSocket] for 121.166.105.106 at 2016-07-26 13:46:18 +0000
I, [2016-07-26T13:46:18.075817 #32369]  INFO -- : [917fd706-4f1a-4178-bd95-7a33c0c7b621] Successfully upgraded to WebSocket (REQUEST_METHOD: GET, HTTP_CONNECTION: Upgrade, HTTP_UPGRADE: web socket)
```
that is, upgrade to WebSocket was successful but the rest is unknown. Do you have any clue on resolving this?

### Steps to reproduce

1. Configure an in-app actioncable server(mount to '/cable')
2. Subscribe to a actioncable channel
3. Test in development environment: success!
4. Deploy to ElasticBeanstalk
5. Test in staging or productino environment: failure!

### Expected behavior
WebSocket should respond with `101 Switching Protocols`.
[Successful screenshot on development](http://i.stack.imgur.com/TWQqM.png)

### Actual behavior
```
Uncaught Error: Existing connection must be closed before openingActionCable.Connection.t.open @ application-f99b196….js:6(anonymous function) @ application-f99b196….js:6
WebSocket connection to 'ws://{hostname}/cable' failed: WebSocket is closed before the connection is established.
```

[Failed screenshot on staging](http://i.stack.imgur.com/pRUMn.png)

### System configuration
**Rails version**: 5.0.0

**Ruby version**: MRI 2.3.1

**Comment by YoonjaeYoo** [comment]
I resolved this issue by removing load balancing from Elastic Beanstalk, that is, by creating a new environment without auto scaling. I guess there was some problem regarding HTTP header while load balancing.

**Comment by KeithP** [comment]
@YoonjaeYoo this might be related to #22871? To get it working on a single instance on AWS we added a proxy config for NGINX. You may need to configure the EB load balancer to allow the ws connection through to the instance(s). Can't say more than that as we don't currently use EB load balancer so haven't faced this (yet). Will be interested to hear how you solve this.

**Comment by spagnolodesign** [comment]
Hi guys, I still have this issue on my EB configuration I can't get this run properly. 
@YoonjaeYoo did you switch your configuration without load balancing and is working properly? I did it and is not working with my app.
@KeithP I used also your  NGINX configuration but I've some errors:

ERROR: [Instance: i-077b0bd1cfca46fee] Command failed on instance. Return code: 6 Output: nginx: [emerg] duplicate upstream "backend" in /etc/nginx/conf.d/websockets.conf:1
nginx: configuration file /etc/nginx/nginx.conf test failed. 
container_command 01restart_nginx in .ebextensions/nginx_proxy.config failed. For more detail, check /var/log/eb-activity.log using console or EB CLI.

could you please help me with this. 

I really appreciate your work btw.

**Comment by KeithP** [comment]
@spagnolodesign if you wish to debug your NGINX configuration this can be achieved fairly easily and I recommend it.

**Comment by YoonjaeYoo** [comment]
@spagnolodesign I did and it worked fine. Does it work properly on other servers or in your local development environment?

**Comment by lalit-nga** [comment]
Hi, I am facing same issue. I have single instance with Passenger server on Elastic Beanstalk.  Right now I getting the same issue.

@spagnolodesign You have provided the Nginx congfi for puma. But I have passenger at my end. So I have no idea to resolve it with passenger.

**Comment by KeithP** [comment]
@lalit-nga I believe with Rails 5 ActionCable you will need to use a Puma server, not Passenger.

**Comment by lalit-nga** [comment]
@KeithP I have recently moved to Puma from passenger. Same issue exist. 

Just for sharing. I have seen your [issue](https://github.com/rails/rails/issues/22871). I have face same issue when trying to connect with **ws**. But when I changed it to **wss**, issue "Error during WebSocket handshake: Unexpected response code: 404" gone.

After that "WebSocket is closed before the connection is established." issue again came. So I have tried your solution as mentioned this [gist](https://gist.github.com/KeithP/f8534c04d20c2b4e4b1d). It is not working at my end.

**Comment by spagnolodesign** [comment]
I spent quite time and money with Amazon Support and at the end I gave up with EB, I solved it runnig away form EB  and I set a custom EC2 instance with a propper nginx conf no problem at all.

**Comment by lalit-nga** [comment]
I think you right. EBS contains the older version of services which prevent ActionCable to run.

**Comment by KeithP** [comment]
It took some investigation into how NGINX was interpreting the config before we got this working. The key was adding debug logging to the NGINX config file and checking the resulting AWS logs for clues as to why it was failing.

**Comment by terryjray** [comment]
So... anyone gotten this working lately?

I'm running into the same exact issue. Works great everywhere except beanstalk.

nginx version: nginx/1.14.1
puma-3.12.1
rails-5.2.2

I've tried several .ebextensions mods on the nginx conf that I've found in numerous threads about this issue.

I'm curious if everyone is still just avoiding beanstalk :(    or if there is some recent working config that could be shared.

TIA!

**Comment by rokumatsumoto** [comment]
nginx: 1.14.1
puma: 3.12.0
rails: 5.2.3
ruby: 2.5.5

I managed to make it work with this [gist](https://gist.github.com/digitaldrk/e3384d6e57c3257ddd93ec9d164f7d61)

If your load balancer type is **classic load balancer** you need to change your listener protocol to TCP or migrate your load balancer type to **application load balancer**

> Application Load Balancers support content-based routing, and supports applications that run in containers. They support a pair of industry-standard protocols (WebSocket and HTTP/2) and also provide additional visibility into the health of the target instances and containers.

One issue with this approach (TCP) is that you cannot access the Client IP address anymore. 

> The Proxy Protocol header helps you identify the IP address of a client when you have a load balancer that uses TCP for back-end connections

![Screen Shot 2019-10-30 at 15 03 21](https://user-images.githubusercontent.com/28678254/67856831-79a9a200-fb26-11e9-8763-cb9150d98187.png)

See: 
https://aws.amazon.com/blogs/aws/new-aws-application-load-balancer/
https://stackoverflow.com/a/51606658/2015025
https://docs.aws.amazon.com/elasticloadbalancing/latest/classic/enable-proxy-protocol.html

**Comment by kunzig940** [comment]
Using Application Load Balancing will support websockets natively you just need to configure NGINX to upgrade the connection. Their newest docs are buried under years of docs suggesting the use of .ebextensions however this no longer works. Now, they require you to use .platform.  I ended up extending the config file supplied by beanstalk instead of outright replacing it. To do this, create the following directories in your app folder:   `/.platform/nginx/conf.d/elasticbeanstalk/websockets.conf`

/websockets.conf put:
```
# enables WS support
location /cable {
  proxy_pass http://my_app;
  proxy_http_version 1.1;
  proxy_set_header Upgrade $http_upgrade;
  proxy_set_header Connection "upgrade";
  proxy_set_header X-Real-IP $remote_addr;
  proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
}
```
The updated docs here:
