### ISSUE TITLE
Fragment caching does not respond to `force: true`

### ISSUE THREAD

**Issue by bendilley** [rails/rails#25964]
### Steps to reproduce
Loading an erb of the form
```erb
<% cache @model, force: params[:bust_cache].to_bool do %>
  <%= Time.current %>
<% end %>
```
with `bust_cache=true` as an http parameter.

### Expected behavior
I would expect `force: true` to force a cache miss and _replace_ any current cache entry, as per the equivalent option for [`Rails.cache.fetch`](http://api.rubyonrails.org/classes/ActiveSupport/Cache/Store.html#method-i-fetch)

### Actual behavior
The `:force` option has no effect and the current cache entry is returned.

### System configuration
**Rails version**: 4.2.6

**Ruby version**: 2.3.1

### Proposed fix
I have worked around this for the time being with this monkey-patch:
```ruby
module ActionView::Helpers::CacheHelper

  # Simulate behaviour of Rails.cache.fetch with `force: true` option
  # This is a monkey-patch of a private method and could well break on upgrade
  def fragment_for(name = {}, options = nil, &block)
    force = options.try(:[], :force)
    !force && read_fragment_for(name, options) || write_fragment_for(name, options, &block)
  end

end
```
but of course there's every chance this will stop working if I upgrade Rails.

I plan to open a PR against this issue just as soon as I figure out how to write a test for it and update the API docs...

**Comment by stevenharman** [comment]
For what it's worth, this approach will also force-bust the cache if you passed `bust_cache=false`. Incoming request parameters are parsed to strings, so any value is always going to be truthy and only the absence of the parameter will allow the cache to be hit.

```ruby
# with bust_cache=true
bust_or_not = params[:bust_cache] #=> "true"
!bust_or_not #=> false

# with bust_cache=false
bust_or_not = params[:bust_cache] #=> "false"
!bust_or_not #=> false
```

That might be tangental to the original problem, but something to consider as it might also break the principle of least surprise.

**Comment by sgrif** [comment]
Since there is no documentation stating that this method is supposed to take a `force` option, this is a feature request. We only allow bug reports on the issues tracker. Feel free to open a thread on the mailing list, or submit a pull request to add the feature.

**Comment by bendilley** [comment]
@stevenharman I used `to_bool` on the parameter for that reason, though I'd have the controller or some helper worry about returning the 'bust cache' condition IRL.
