### ISSUE TITLE
Confusing `time_select` with `include_blank` option

### ISSUE THREAD

**Issue by JanStevens** [rails/rails#25969]
### Steps to reproduce

Create a `time_select` tag with the option `include_blank`

``` ruby
time_select('default', 'testing', include_blank: true)
```
### Expected behavior

In total 5 different inputs where the value is actually `nil`, or even better no hidden tags

``` html
<input type="hidden" id="permissions_time_1i" name="permissions[time(1i)]" value="">
<input type="hidden" id="permissions_time_2i" name="permissions[time(2i)]" value="">
<input type="hidden" id="permissions_time_3i" name="permissions[time(3i)]" value="">
<select id="permissions_time_4i" name="permissions[time(4i)]">
<option value=""></option>
<option value="00">00</option>
</select>
 :
<select id="permissions_time_5i" name="permissions[time(5i)]">
<option value=""></option>
<option value="00">00</option>
</select>
```

Or just drop the hidden inputs when the user want a `time_select`

``` html
<select id="permissions_time_4i" name="permissions[time(4i)]">
<option value=""></option>
<option value="00">00</option>
</select>
 :
<select id="permissions_time_5i" name="permissions[time(5i)]">
<option value=""></option>
<option value="00">00</option>
</select>
```
### Actual behavior

In total 5 different inputs with hidden inputs have a value of 1 (expected `nil`)

``` html
<input type="hidden" id="permissions_time_1i" name="permissions[time(1i)]" value="1">
<input type="hidden" id="permissions_time_2i" name="permissions[time(2i)]" value="1">
<input type="hidden" id="permissions_time_3i" name="permissions[time(3i)]" value="1">
<select id="permissions_time_4i" name="permissions[time(4i)]">
<option value=""></option>
<option value="00">00</option>
</select>
 :
<select id="permissions_time_5i" name="permissions[time(5i)]">
<option value=""></option>
<option value="00">00</option>
</select>
```
1. Why do the hidden inputs have a value of 1 when I explicitly want `include_blank` values? If I save a form without selecting anything from the `time_select` it still gets converted to a DateTime object with a time of 00:00 and persited like this, this is not the same as `nil`!
2. Reading the docs: `If you set the :ignore_date to true, you must have a date_select on the same method within the form otherwise an exception will be raised.` This is not true, nothing gets raised, looking at the code this is also not true (not now and not in Rails 5.0). I can have a form with only a `select_time` and `ignore_date: true` and nothing gets raised during rendering or submit, it actually works (currently my fix)!
### System configuration

**Rails version**: 4.2.6
**Postgres**: 9.5
**Ruby version**: 2.3.1
### Call To Action
1. When using a `time_select` always include the `ignore_date` option since the user requested explicitly a `time_select` and don't care about the `date` part.
2. Remove the wrong documentation: since nothing gets raised (I traced it back to: https://github.com/rails/rails/commit/a59a67d01cbae485a8b46066b8a94f11db591765, even in 2011 the code never raised a thing)
3. If option `1` is a no go, then set the value to nil when using `include_blank` since the user explicitly wants to be able to select `nil` as `time` now it's not possible to select nothing

**Comment by oscarmrom** [comment]
Want to plus one this issue. The docs mention that `include_blank` will do the trick but it's not correct with this `time_select` helper. 

Including the `ignore_date: true` explicitly gets the job done but isn't conveyed as the "workaround" / manner to accomplish setting an empty time when nothing is selected in the [docs](https://api.rubyonrails.org/classes/ActionView/Helpers/DateHelper.html#method-i-time_select).

**Comment by skipkayhil** [comment]
Would you like to open a PR to update the docs?
