### ISSUE TITLE
Calling has_many association ~100x slower in Rails 4 vs Rails 3 (with associations preloaded)

### ISSUE THREAD

**Issue by pawelgut** [rails/rails#25970]
Even when the associated objects are preloaded (using <tt>includes</tt>, for instance), the actual call to <tt>object.my_children</tt> is significantly slower in Rails 4 than in Rails 3. 10,000 of such calls can add up to a second, which causes significant performance hits in our application. In Rails 3, this was about 100x faster. 
The following flamegraph illustrates a single call to a <tt>has_many</tt> association in Rails 4. It appears as though the call to <tt>ActiveRecord::Associations::CollectionAssociation#scope</tt> has significant overhead.
![rails_4_flamegraph](https://cloud.githubusercontent.com/assets/7838456/17194286/39111aa8-5425-11e6-8d43-377c2f6f2c33.jpg)
Is there anything we can do about this? After upgrading to Rails 4, our a lot of our endpoints have slowed down significantly because of this issue.
### Steps to reproduce

https://github.com/pawelgut/rails-3-association-performance/ and https://github.com/pawelgut/rails-4-association-performance/ are simple apps I created with rake tasks that illustrate this problem. Please see the Readme.
### System configuration

**Rails version**:  4.2.6 and 3.2.22

**Ruby version**:  2.1.3

**Comment by rafaelfranca** [comment]
Could you check this branch? https://github.com/rails/rails/pull/25877

**Comment by serggl** [comment]
We have faced the same issue in our production setup, which uses Rails 5. We were seeing CPU utilization spikes and a general slow down in docker due to this and #25877 has definitely solved them. I would love to see #25877 merged asap

**Comment by kamipo** [comment]
Closing since #25877 was merged.
