### ISSUE TITLE
Active Job logger raises error when job has no arguments

### ISSUE THREAD

**Issue by sgottfried** [rails/rails#25977]
### Steps to reproduce
I have a job with a `perform` method that takes no parameters:

```rb
  class MyJob < ActiveJob::Base
    def perform
      # Do some stuff
    end
  end
```
and I run that job.

`MyJob.new.perform_now`

### Expected behavior
The job should run with no problems.

### Actual behavior
The job runs, but an error is raised in the logs because the ActiveJob logger expects parameters

```rb
[ActiveJob] [MyJob] Could not log "perform_start.active_job" event. NoMethodError: undefined method `any?' for nil:NilClass ["/Users/sam/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/activejob-5.0.0/lib/active_job/logging.rb:89:in `args_info'"...
```

The line in question looks like this:

```rb
   def args_info(job)
          if job.arguments.any?
            ' with arguments: ' +
              job.arguments.map { |arg| format(arg).inspect }.join(', ')
          else
            ''
          end
        end
```

On that second line, `job.arguments` is nil, which does not respond to `.any?`.

### System configuration
**Rails version**: 5.0.0

**Ruby version**: 2.3.0p0

**Comment by jeremy** [comment]
Thanks for the report, @sgottfried. Have you diagnosed why job arguments is `nil` rather than an empty array? Intentional or inadvertent?

**Comment by sgottfried** [comment]
We aren't passing anything into the job.  Is there always supposed to be a job parameter even if it isn't being used?  It seems like this should be allowed, especially since the job still executes correctly.

**Comment by jeremy** [comment]
Right, yes! Have you diagnosed why Active Job is reporting "no params" as `nil` instead of `[]`?

**Comment by sgottfried** [comment]
The job comes from `job = event.payload[:job]` inside lib/activejob/logging.rb:71.  That is supposed to contain arguments.  
That payload comes from line 21 of the same file. 
`payload = {adapter: job.class.queue_adapter, job: job}`

 and the callbacks that include logging get triggered from active_job/execution.rb:33
```rb
def perform_now
      deserialize_arguments_if_needed
      run_callbacks :perform do
        perform(*arguments)
      end
    rescue => exception
      rescue_with_handler(exception) || raise
    end
```
`arguments` in that case are coming up as `nil`.

**Comment by sgottfried** [comment]
I think I figured it out.  The job had its own initializer, and `ActiveJob::Base` includes `ActiveJob::Core`, which sets `@arguments` on the job. If I simply called `super` in that initializer, it would have populated that.  What I don't understand is why this isn't documented anywhere.  It seems like either `ActiveJob::Base`'s initializer shouldn't be overridden, `super` should be called in the initializer, or `@attributes` should default to an array in this case.  In any of those cases, it should be documented somewhere.

Either that, or a `.try` should be made in the logger.

**Comment by jeremy** [comment]
@sgottfried Good point! Any time you're subclassing a framework base class, you'll definitely want to `super` if you override `#initialize` (or other methods the base class implements whose side effects you may rely on). Where and how would you suggest documenting this? Perhaps a broader point for subclass responsibility when overriding methods, documentation on the `Base` class?

**Comment by dubeypranav4** [comment]
For example this was my initializer `def` giving the above error:
### Before
```
  def initialize
    @fb_client = FBClient.new
  end
```
### After
```
  def initialize(*args)
    super(*args)
    @fb_client = FBClient.new
  end
  ```

---
Making the above changes solved the issue.
