### ISSUE TITLE
drop_table not working when migrating 

### ISSUE THREAD

**Issue by naveen1336** [rails/rails#25971]
### Expected behavior

it should drop the table 

### Actual behavior
it don't drop the table
class CreateUsers < ActiveRecord::Migration[5.0]
  def up
    create_table :users do |t|
      t.column "first_name", :string, :limit => 25
      t.string "last_name", :limit => 50
      t.string "email", :default => "", :null => false
      t.string "password", :limit => 40
     # t.datetime "created_at"
      #t.datetime "updated_at"
      t.timestamps
    end

    def down
      drop_table :users  #it does not work when migration:down 
    end
  end
end

### System configuration
mysql  Ver 14.14 Distrib 5.7.13, for Linux (x86_64) using  EditLine wrapper
Rails 5.0.0
ruby 2.3.1p112 (2016-04-26 revision 54768) [x86_64-linux]

**Comment by rafaelfranca** [comment]
Can you please provide a sample application that reproduces the error?

**Comment by naveen1336** [comment]
i just created this  migration  and when i run ( rails db:migrate:down VERSION=232323232) it should drop the table users but it did not i have to manually drop the table in mysql

**Comment by rafaelfranca** [comment]
I did the same thing and the table was removed. We also have tests to assert this behavior so I'm guessing there is something wrong in your application. An example application reproducing this issue would help to identify what is wrong.

**Comment by naveen1336** [comment]
ok, did you use same rails,ruby,mysql version as i did

**Comment by rafaelfranca** [comment]
No, but I'd not go in this direction. Other information that helps is the error message that you see when running the command with the backtrace included.

**Comment by naveen1336** [comment]
ok, i made a mistake in my code , close the issue
