### ISSUE TITLE
"Request to origin not allowed" when running rails s -b <IP address>

### ISSUE THREAD

**Issue by lorint** [rails/rails#25979]
### Steps to reproduce

1. Create a Rails 5 application with rails new.

2. Run:
```
cd <application folder>
rails g scaffold Widget name
rails db:migrate
rails s -b 0.0.0.0
```

If a question about allowing traffic through a firewall is presented, choose Allow.

3. Since the rails server was started with a binding to an IP address instead of to localhost, from any machine on the network you can navigate to  http://<IP address>:3000/widgets.  The page will render correctly and be functional, but a Javascript error about the websocket connection will be reported every 15 seconds.

### Expected behavior
Multiple machines can navigate to the same Rails machine running "rails s" with the "-b" option in order to better facilitate developing real-time Action Cable applications.

### Actual behavior
Errors in the browser's Javascript Console window will include:

```
WebSocket connection to 'ws://<IP address>:3000/cable' failed: Error during WebSocket handshake: Unexpected response code: 404
```

and errors on the Rails server that indicate:

```
Request to origin not allowed: http://<IP address>:3000
Failed to upgrade to WebSocket (REQUEST_METHOD: GET, HTTP_CONNECTION: Upgrade, HTTP_UPGRADE: websocket)
```

### Workaround
Include a line in config/environments/development.rb such as:

```
config.action_cable.allowed_request_origins = [ /https?:\/\/localhost:\d+/, /https?:\/\/192.168.0.5:\d+/ ]
```

One pain point with this solution is that if the development machine's IP changes, then this entry also must be modified.  Would be nice if this could be dynamically set just during development.

### System configuration
**Rails version**: 5.0.0

**Ruby version**: 2.3.0

**Comment by rafaelfranca** [comment]
This is by design. If people want to use action cable in development in different hosts they will need to configure it properly.

**Comment by jeremy** [comment]
Related: #25420

**Comment by lorint** [comment]
@jeremy -- that was actually my first stop along the way in looking into the issue :)

#25980
