### ISSUE TITLE
convert rails query to sql query using 'includes'

### ISSUE THREAD

**Issue by rahulshinde100** [rails/rails#25984]
### Steps to reproduce

(Guidelines for creating a bug report are [available
here](http://guides.rubyonrails.org/contributing_to_ruby_on_rails.html#creating-a-bug-report))

### Expected behavior
**User.includes(:student).select("email AS email, firstname AS f_name, name AS student_name").as_json**
how to fetch perticular column records in pure sql format and without rails object 
### Actual behavior
if  **User.joins(:student).select("email AS email, firstname AS f_name, name AS student_name").as_json** is executed properly and get the object correct 
In this 'joins' clause working for pure select data but not supported  for 'includes'
### System configuration
**Rails version**:
Rails 4.0.0
**Ruby version**:
ruby 2.2.3

**Comment by matthewd** [comment]
Please use the mailing list or StackOverflow for questions/help, where a wider community will be able to help you. We reserve the issues tracker for issues only.
