### ISSUE TITLE
assert_enqueued_with failure messages could be more helpful

### ISSUE THREAD

**Issue by maxehmookau** [rails/rails#25983]
### Actual behavior

When asserting that a job has been enqueued with `assert_enqueued_with`, on failure it returns a message such as this:

```
No enqueued job found with {:job=>JobWithArgsJob, :args=>["Hello", "Ruby", "July 29, 2016 10:47"]}
```

While useful, it doesn't tell us which part of the job is wrong. This error message could suggest one of a few possible issues with my code:
1. No jobs have been enqueued.
2. A job has been enqueued of the right class, but the arguments are wrong or missing.
3. The wrong job has been enqueued with the correct arguments.
4. Any combination of the above.

From a TDD perspective, I'd like to know exactly what part of my job test is failing.
### Expected behavior

Ideally I'd expect to see some sort of diff with any existing jobs such as:

```
No enqueued job found with {:job=>JobWithArgsJob, :args=>["Hello", "Ruby", "July 29, 2016 10:47"]}
Instead JobWithArgsJob found with args ["Hello", "July 29, 2016 10:47"]
```

Or something similar with a bit more polish...

If it's something that the core team think should be included in the ActiveJob test helpers I'd be happy to work on it.

**Comment by utilum** [comment]
The notion is tempting, but I'm not sure the hassle of iterating through all enqueued jobs and checking against possible similarities is worth every test run, especially after initial development, once the test is used mainly to identify regressions. 
You can write your own custom message, right? Did you? And if so, what does it look like?
