### ISSUE TITLE
Query  using array doesn't return results

### ISSUE THREAD

**Issue by stoerebink** [rails/rails#25982]
### Steps to reproduce
I'm trying to use a scope or class method to filter my model by status. The input can be a single status or multiple statuses. According to the Rails documentation (http://guides.rubyonrails.org/v3.2.9/active_record_querying.html#array-conditions), Client.where(:orders_count => [1,3,5]) should return clients with order count 1, 3 or 5. When I apply this to my model, it's Shipment.where(status: status). Status is an array that looks like this: ["New", "Open"]. When I run this in my console, I get 3 results. When I run this code in my Shipment model, I get 0 results. When I select only one status and run this in my console/shipment model, I get results in both cases. The example here being: Shipment.where(status: ["New"]). 

### Expected behavior
Shipment.where(status: ["New", "Open"]) should return records with status New or Open. 

### Actual behavior
Shipment.where(status: ["New", "Open"]) only returns the expected results when run in the console. When I call the same line in my model, no results are returned. 

### System configuration
**Rails version**: rails (4.2.5, 4.2.3)

**Ruby version**: ruby 2.2.1

**Comment by matthewd** [comment]
Please use the mailing list or StackOverflow for questions/help, where a wider community will be able to help you. We reserve the issues tracker for issues only.
