### ISSUE TITLE
when a column is boolean and presence to be true, u cant insert false into database

### ISSUE THREAD

**Issue by wangpc** [rails/rails#25985]
### ENV
ruby: 2.3.0

```
gem 'rails',  '5.0.0'
gem 'sqlite3', '1.3.11'
```

### Steps to reproduce
 new a model like this: 
```ruby
  def change
    create_table :apps do |t|
      t.string :name
      t.string :url
      t.boolean :is_buildin_app

      t.timestamps
    end
  end
```

is_buildin_app is a boolean value

and add a validate to app model:
```ruby
class App < ApplicationRecord
  validates :name, presence: true
  validates :desc, presence: true
  validates :is_buildin_app, presence: true
  before_save :downcase_url, :downcase_name
end
```

and you will never add a new app object to db when is_buildin_app = false

### Expected behavior
i think that keyword presence means this column should be exist no matter its value is true or false

is_buildin_app == true -> presence OK
is_buildin_app == false -> presence OK
is_buildin_app == nil -> presence error

### Actual behavior
only is_buildin_app == true -> presence OK

### System configuration
**Rails version**:
5.0.0
**Ruby version**:
2.3.0

**Comment by pixeltrix** [comment]
hi @wangpc, thanks for your report.

This is a known gotcha when working with the presence validator and boolean columns - we actually [recommend using inclusion or exclusion validation in the guides][1]. e.g:

``` ruby
validates :is_buildin_app, inclusion: { in: [true, false] }
```

Hope this helps.

[1]: http://guides.rubyonrails.org/active_record_validations.html#presence

**Comment by wangpc** [comment]
Hi @pixeltrix really thank you for this info, good luck!  ^_^
