### ISSUE TITLE
CREATE INDEX CONCURRENTLY with algorithm: :concurrently does not write to structure.sql

### ISSUE THREAD

**Issue by mech** [rails/rails#25981]
### Steps to reproduce

I have set my `config.active_record.schema_format = :sql` so that migration will be written to `structure.sql` as a series of real SQL statements. I setup the index concurrently using this:

```ruby
add_index :users, :external_user_id, algorithm: :concurrently
```

I am using Postgres 9.5.3 with PG gem version 0.18.4. Using Rails 5.0.0.

### Expected behavior

Looking at Rails 5's `schema_statements.rb` where `add_index()` is defined, it should know the `index_algorithm` and setup accordingly, but no mention of concurrently at `structure.sql`. 

I want to see this:

```sql
CREATE INDEX CONCURRENTLY index_users_on_external_user_id ON users USING btree (external_user_id);
```

### Actual behavior

Instead I am getting this:

```sql
CREATE INDEX index_users_on_external_user_id ON users USING btree (external_user_id);
```

### System configuration
**Rails version**: Rails 5.0.0

**Ruby version**: Ruby 2.3.1

**Comment by jeremy** [comment]
structure.sql is a raw database dump using `pg_dump`, so it won't know to use concurrent index creation.

How would you suggest tracking that state? What "remembers" whether to add an index concurrently?

**Comment by jeremy** [comment]
Looks like `pg_restore` takes on concurrency with `--jobs=number-of-jobs`. Perhaps attack the problem from the restore end, rather than dump?

**Comment by mech** [comment]
Pardon me, I think I have the wrong impression of how concurrent index work. My initial impression is that the index is perform concurrent whenever there is a new insert/update during operation. But it turn out that it is more for already existing huge number of records in order not to lock write.

For brand new DB, it has no effect. Sorry for the misunderstanding.
