### ISSUE TITLE
ActiveJob::SerializationError: Unsupported argument type: Symbol

### ISSUE THREAD

**Issue by nimylian** [rails/rails#25993]
### Steps to reproduce

> ActiveJob::Base.perform_later(:String)
### Expected behavior

=> #<ActiveJob::Base:0x21b792c2
 @arguments=["String"],
 @job_id="cb5538a9-15a6-4e27-b800-1c95801c21f2",
 @priority=nil,
 @provider_job_id="4d8ee00e0381fc30af4e0dc8",
 @queue_name="default">
### Actual behavior

ActiveJob::SerializationError: Unsupported argument type: Symbol
### System configuration

**Rails version**: 5.0.0

**Ruby version**: 2.3.1

**Comment by rafaelfranca** [comment]
Symbol is not a supported argument type for jobs because some implementations don't work with it (Sidekiq and resque)

**Comment by nimylian** [comment]
Why not just convert Symbols to Strings before passing them to the async worker?

**Comment by lucasocon** [comment]
You can use the the `inquiry` string method in order to perform methods with question mark.

Example: 
```
state = 'valid'
state.inquiry.valid? => true
state.inquiry.invalid? => false
```

**Comment by yashBiz** [comment]
I realize that this issue is quite old and closed. But we were facing the same issue, and decided to write up a quick psuedo-serializer to handle symbol arguments
https://hustle.bizongo.in/serializing-symbols-for-activejobs-785a76a2a1c5

**Comment by oamado** [comment]
I had the same issue but, when I run perform_now it accepts the symbols, the question is in the official documentation appears that symbols are supported, so we need to update the documentation, or reopen this issue? https://edgeguides.rubyonrails.org/active_job_basics.html#supported-types-for-arguments

**Comment by rafaelfranca** [comment]
You are looking the documentation for Rails 6 that supports symbols. Rails 5.2 doesn't

**Comment by kim-tom** [comment]
I used .to_json to pass my own class. And I parsed them by JSON.parse.
This fixed.
