### ISSUE TITLE
Unexpected output from strip_tags

### ISSUE THREAD

**Issue by CamJN** [rails/rails#25996]
### Steps to reproduce

Run `ActionController::Base.helpers.strip_tags("R&D")`

### Expected behavior

It should return `"R&D"` because that's what the code implies: https://github.com/rails/rails/blob/5-0-stable/actionview/lib/action_view/helpers/sanitize_helper.rb#L102 note the `encode_special_chars: false`.

### Actual behavior

It returns `"R&amp;D"`

### System configuration
**Rails version**: 5.0.0 stable

**Ruby version**: 2.3.1

**Comment by rafaelfranca** [comment]
This behavior has changed for security reasons. Now it always escape html entities.
