### ISSUE TITLE
ActiveRecord select does not create accessor method when relation is ordered by attribute of joined model

### ISSUE THREAD

**Issue by fredwillmore** [rails/rails#26029]
### Steps to reproduce
Run the following gist:
https://gist.github.com/fredwillmore/58d0b05446b60d5c38ec6814f6fad33e

### Expected behavior
Objects in ActiveRecord relation should have an accessor named 'duration'

### Actual behavior
When the relation is ordered by 'title', the accessor is available; when the relation is ordered by 'batch_type.short_name', I get:
NoMethodError: undefined method `duration' for #<Batch:0x000001014c6f88>

### System configuration
**Rails version**:
4.2
ActiveRecord 4.2.7
**Ruby version**:
2.1

**Comment by maclover7** [comment]
Thank you for opening up this issue! I am seeing the same issue as you reported above on Rails master, that when you run the query with `order('batch_types.short_name')`, an error occurs. Here's a slightly modified version of your reproduction script --> https://gist.github.com/maclover7/2548449c55536a872d9298111e7d72d8#file-26029-rb-L49

**Comment by fredwillmore** [comment]
Thanks, I've been working with rails for a couple years now and I've been wanting to find a way to contribute. This is my first contribution!

**Comment by jdanielnd** [comment]
Using `includes` with `select` doesn't work well since Rails 3 (as far as I know). It seems that it is related to the aliases created by the `includes` method, since it works fine when it doesn't create any aliases.

Using `joins` works fine:

```
def test_26023_with_joins
   batch_type = BatchType.create!
   batch = Batch.create!(batch_type: batch_type)
   assert_equal 0, Batch.joins(:batch_type).order('batch_types.short_name').my_select_query.duration
end
```

I'm trying to track down where `ActiveRecord` creates the attributes accessors for the `select` statements, but I couldn't find it yet. Does anyone knows more about this mechanics?

**Comment by matthewd** [comment]
> Using `includes` with `select` doesn't work

Indeed.

When `includes` is combined with a reference to the other table (in the `order`, in this case), we must reconstruct multiple related objects from each row; that necessarily means we need to know which object each column belongs to. To do that, we override any custom `select` with a pre-calculated set of aliases.
