### ISSUE TITLE
Activesupport::Duration inconsistencies around daylight saving time (DST)

### ISSUE THREAD

**Issue by vmeyet** [rails/rails#26039]
### Bug

Moving from rails 4.x to rails 5, active support duration daylight saving time (DST) behavior changed.

For example: adding 1 week to a date doesnt have the same behavior in activesupport 4.x and activesupport 5.

I might understand the reasoning behind it. But sadly this is a change that is poorly documented and lead to weird behavior such as `date + 1.week != 1.week.from_now(date)` when passing the DST point.

### Steps to reproduce

```ruby
[1] pry(main)> t = Date.parse('Mon, 24 Oct 2016').in_time_zone('Europe/Paris')
=> Mon, 24 Oct 2016 00:00:00 CEST +02:00
[2] pry(main)> t + 1.week == 1.week.from_now(t)
=> false
[3] pry(main)> t + 1.week
=> Sun, 30 Oct 2016 23:00:00 CET +01:00
[4] pry(main)> 1.week.from_now(t)
=> Mon, 31 Oct 2016 00:00:00 CET +01:00
```

### Expected behavior

I think it's safe to expect that `date + 1.week` and `1.week.from_now(date)` have the same value
(which was the case in 4.2)

### Actual behavior
This is not equal 

### Possible suspect for that bug

I strongly suspect that commit (https://github.com/rails/rails/commit/ee5e476aad791e41c97f2a833f41bb5899d5252b) introduced that bug.

I've added debugging to the `ActiveSupport::Duration#sum` method and noticed that the [`advance` method](https://github.com/rails/rails/blob/master/activesupport/lib/active_support/duration.rb#L167) receive an utc date in 5.0.0. Meaning the timezone support is wrapped externally. this led to this bug.

### System configuration
**Rails version**: 5.0.0

**Ruby version**: 2.3.1

**Comment by pixeltrix** [comment]
Actually the problem is with 434df00:

``` irb
>> t = Date.parse('Mon, 24 Oct 2016').in_time_zone('Europe/Paris')
=> Mon, 24 Oct 2016 00:00:00 CEST +02:00 
>> t + 1.week
=> Sun, 30 Oct 2016 23:00:00 CET +01:00 
>> t + 7.days
=> Mon, 31 Oct 2016 00:00:00 CET +01:00 
```

This is because `:weeks` is now a first class duration, whereas in 4.2 and earlier it got converted to the appropriate number of days. This means that the private method in [time_with_zone.rb][1] needs to be updated:

``` ruby
def duration_of_variable_length?(obj)
  ActiveSupport::Duration === obj && obj.parts.any? {|p| [:years, :months, :days].include?(p[0]) }
end
```

Note that `:weeks` is missing from the array of parts.

[1]: https://github.com/rails/rails/blob/master/activesupport/lib/active_support/time_with_zone.rb#L483-L485

**Comment by vmeyet** [comment]
Yes indeed, `duration_of_variable_length?` should be true for durations containing `weeks` part.

Thanks for the quick answer.

**Comment by pixeltrix** [comment]
@maclover7 already backported 😄

**Comment by maclover7** [comment]
👍 sorry, didn't see
