### ISSUE TITLE
Model#save creates wrong SQL (INSERT INTO instead UPDATE)

### ISSUE THREAD

**Issue by tak1n** [rails/rails#26038]
We currently face a problem when a request spec fails (typo or other exception) it affects other request specs which actually should be unaffected. The problem is we use many gems so I tried to create a minimal reproduction app (without success, https://github.com/tak1n/reproduction)

The problem in detail:

We have a request spec where we need to login a user. For user authentication we use devise and therefore we use Warden::Test::Helpers to log in users in request specs. Devise automatically updates some user related attributes when a user logs in (last_sign_in_at, last_sign_in_ip etc..).

The problem here is that when it tries to save the user for doing this changes the end result is a `INSERT INTO user` instead of a `UPDATE user` and therefore it crashes.

Here is an example spec from our app:

```ruby
require 'rails_helper'

RSpec.describe 'Suggestions API' do
  let(:user) { FactoryGirl.create(:user, :professional) }

  before do
    login(user)
  end

  describe '/suggestions.json', :vcr do
    context 'with non saved filter' do
      # some setup stuff here (setup proper objects in db)

      # also params are defined here through let(:params) { ... }

      it 'returns proper suggestions' do
        Suggestion.refresh!

        get '/suggestions.json', paramst

        expect(json.count).to eq(2)

        expect(json.first['id']).to eq(sug2.id)
        expect(json.second['id']).to eq(sug1.id)
      end
    end

    context 'with saved filter' do
      # some setup stuff here (setup proper objects in db)

      # also params are defined here through let(:params) { ... }

      it 'returns proper suggestions' do
        Suggestion.refresh!

        get '/suggestions.json', params

        expect(json.count).to eq(2)

        expect(json.first['id']).to eq(sug2.id)
        expect(json.second['id']).to eq(sug1.id)
      end
    end
  end
end
```

The result of this should be that the first spec fails because of the typo `paramst`, which it does but it also affects the second spec:

Here is the spec run: https://gist.github.com/tak1n/102c1aa121b66e0ab56602b76f911ec0

I tried to dig deeper and saw that the logic whether save creates or updates a record is depending on https://github.com/rails/rails/blob/master/activerecord/lib/active_record/persistence.rb#L85

Next I tried to output what `@new_record` was in that case.

```ruby
def new_record?
  sync_with_transaction_state
  puts "New record: #{@new_record}" if self.class == User
  @new_record
end
```

I got following: https://gist.github.com/tak1n/330560a3a108abc8fce4d105a48ac444

When the spec run in different order (non failing first then spec with typo or exception in it) I got this: https://gist.github.com/tak1n/6eb24693226d8e6a713c0865ea1bebd5

The difference here is for the "working" spec `New Record: <boolean>` is different.
When the spec with the exception runs before it `New record` suddenly becomes true and therefore it generates SQL to create a new record.

Next I assumed some gems are causing this problem, most likely I thought it would be database_cleaner but in the reproduction I do more or less the same and there it works.

The problem is I'm really stuck at debugging and not sure where to proceed.
Also I'm not sure which gem or our code itself is causing this.

I also asked on [Stackoverflow](http://stackoverflow.com/questions/38635739/request-spec-order-dependent-failure-wrong-sql-created-for-devise-user-update-o) about that first (didn't want to open an issue, because maybe its not a bug but our fault), but so far nobody could help me there. 

P.S.: Here is our [Gemfile.lock](https://gist.github.com/tak1n/c708f9b7563a8c792cc080647a454016)

**Comment by tak1n** [comment]
Yep sorry I know it's hard as I cannot even provide a public available reproduction :S

I removed DatabaseCleaner and added:

```
  after do
    Filter.destroy_all
    Membership.destroy_all
    User.destroy_all
    Organization.destroy_all
    ContentSource.destroy_all
  end
```

With this approach only the spec with the typo in it fails.

When I use transactional fixtures in rspec configuration it still affects the other example. (https://relishapp.com/rspec/rspec-rails/docs/transactions)

I think I can try to create normal rails minitest style integration test and see if I can reproduce it there (to further eliminate some gems as root cause).

**Comment by tak1n** [comment]
I got a rails integration test which has the same problem:

```ruby
require 'test_helper'

class SomethingTest < ActionDispatch::IntegrationTest
  include Warden::Test::Helpers

  setup do
    user = FactoryGirl.create(:user)

    login_as(user, scope: :user)
  end

  test 'returns smth #1' do
    params = {
      format: :json,
    }

    # /something.json does not exist
    get '/something.json', paramst
  end

  test 'returns smth #2' do
    params = {
      format: :json
    }

    # /something.json does not exist
    get '/something.json', params
  end
end
```

Which gives me:

```
./bin/rake test TEST="test/integration/suggestions_test.rb"
Running via Spring preloader in process 6398
Run options: --seed 46434

# Running:

DEPRECATION WARNING: You did not specify a value for the configuration option `active_support.test_order`. In Rails 5, the default value of this option will change from `:sorted` to `:random`.
To disable this warning and keep the current behavior, you can add the following line to your `config/environments/test.rb`:

  Rails.application.configure do
    config.active_support.test_order = :sorted
  end

Alternatively, you can opt into the future behavior by setting this option to `:random`. (called from require at /home/benny/.rubies/2.3.1/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55)
EE

Finished in 0.254045s, 7.8726 runs/s, 0.0000 assertions/s.

  1) Error:
SomethingTest#test_returns_smth_#1:
NameError: undefined local variable or method `paramst' for #<SomethingTest:0x00563f339934a0>
Did you mean?  parameterize
    test/integration/suggestions_test.rb:18:in `block in <class:SomethingTest>'


  2) Error:
SomethingTest#test_returns_smth_#2:
ActiveRecord::StatementInvalid: PG::NotNullViolation: ERROR:  null value in column "created_at" violates not-null constraint
DETAIL:  Failing row contains (1144, null, , null, null, null, 1, 2016-08-03 14:35:18.584876, 2016-08-03 14:35:18.584876, 127.0.0.1, 127.0.0.1, null, null, null, t, null, null, null, null, null, t, null, null).
: INSERT INTO "users" ("last_sign_in_at", "current_sign_in_at", "last_sign_in_ip", "current_sign_in_ip", "sign_in_count") VALUES ($1, $2, $3, $4, $5) RETURNING "id"
    app/middleware/catch_json_parse_errors.rb:7:in `call'
    test/integration/suggestions_test.rb:27:in `block in <class:SomethingTest>'

2 runs, 0 assertions, 0 failures, 2 errors, 0 skips
```

I copy pasted the Gemfile and Gemfile.lock into a fresh app also added the same integration test (changed the order to be sorted in the fresh app) and in there it works like it should.
Therefore I assume something in our codebase (initalizers or somewhere else) is causing this.

**Comment by tak1n** [comment]
https://github.com/tak1n/reproduction is now available as reproduction app.

**Comment by hwangzc** [comment]
greate
