### ISSUE TITLE
Allow force polling on ActiveSupport::EventedFileUpdateChecker

### ISSUE THREAD

**Issue by rwilliams** [rails/rails#26034]
It would be really nice to allow [`force_polling: true`](https://github.com/guard/listen#options) for the Listen gem through ActiveSupport::EventedFileUpdateChecker initialization or through an environment config. Many of us are using Docker development environments with shared vm folders which breaks the default listen adapter and it doesn't fallback gracefully to polling without forcing it. 

### System configuration
**Rails version**:
5.0.0
**Ruby version**:
2.3.1

**Comment by rafaelfranca** [comment]
Thank you so much for the issue but we don't take feature request on the issue tracker. We recommend you to try to implement the feature and send us a pull request or if you are in doubt if the feature will be accepts ask in Rails Core mailing list for feedback.

**Comment by mrkongo** [comment]
@rwilliams please tell me how to activate this. I'm with docker and file_watcher doesn't work.

**Comment by rwilliams** [comment]
You can add the following as an initializer for your rails app and it should work.

```
module ActiveSupport
  class EventedFileUpdateChecker
    private
      def boot!
        Listen.to(*@dtw, force_polling: true,&method(:changed)).start
      end
  end
end
```

**Comment by mrkongo** [comment]
Now it works. Thanks.

But there is a true fix for this problem with docker and Rails 5?

I'm on Windows with Docker for Winows BETA. It's incredible we are fighting with this. How to fix this? How can I help?

**Comment by rwilliams** [comment]
There is an open issue with Docker about the problem. https://github.com/docker/docker/issues/18246
They've fixed it for mac already and there is talk of them fixing it for windows at some point.

**Comment by mrkongo** [comment]
So you are saying to me that on OSX it works now by default? I will try this.

**Comment by rwilliams** [comment]
Yes with Docker for Mac

**Comment by matthewd** [comment]
If the EventedFileUpdateChecker doesn't work for you, the solution is to not turn it on, and use the (default!) FileUpdateChecker.

**Comment by rwilliams** [comment]
@matthewd Why shouldn't we use EventedFileUpdateChecker with polling vs FileUpdateChecker? FileUpdateChecker is terribly slow in comparison.

**Comment by mrkongo** [comment]
My development environment has become much slower adding the `polling: true` as suggested by @rwilliams. If I change `EventedFileUpdateChecke` in `FileUpdateChecke` (default one) still continues to not work at all. They are on ruby 2.3.1 and 5.0.0.1.

Thanks again, @rwilliams, for tips of the polling.

I am waiting for news and I will update this thread.

**Comment by johnunclesam** [comment]
Any news on this?
