### ISSUE TITLE
Suddenly getting no route matches for all routes without any changes to code

### ISSUE THREAD

**Issue by mattLummus** [rails/rails#26047]
Have searched extensively without help so posting my issue here.
### Steps to reproduce

¯\_(ツ)_/¯ If I could tell you I would be a lot better off...
### Expected behavior

Testing a rails-api with Postman (makes API requests).
I know they are valid, I can see them in `rake routes`, and no front end views/helpers/etc are causing this.
As I have not changed anything in code since the last several (successful) requests, my routes should not holistically be missing. 
### Actual behavior

Working fine, and then suddenly every route in app returns a no route matches error.
### Attempted Solutions

Have tried restarting computer, no luck.
Have removed system gems, reinstalled, and then it works, which leads me to believe some dependency or version/dependency manager has an issue. I can't do this every time this happens as it takes a long time to reinstall via rvm + bundler.
### System configuration

**Rails version**: 4.2.4
**Ruby version**: 2.3.0
**Puma version**: 3.4.0

Macbook Pro (Mid 2014)
OSX 10.11.4   (Capitan)
### Error Log

``````
ActionController::RoutingError (No route matches [GET] "/login"):
  actionpack (4.2.4) lib/action_dispatch/middleware/debug_exceptions.rb:21:in `call'
  rollbar (2.12.0) lib/rollbar/middleware/rails/show_exceptions.rb:22:in `call_with_rollbar'
  newrelic_rpm (3.16.0.318) lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
  actionpack (4.2.4) lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
  newrelic_rpm (3.16.0.318) lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
  railties (4.2.4) lib/rails/rack/logger.rb:38:in `call_app'
  railties (4.2.4) lib/rails/rack/logger.rb:20:in `block in call'
  activesupport (4.2.4) lib/active_support/tagged_logging.rb:68:in `block in tagged'
  activesupport (4.2.4) lib/active_support/tagged_logging.rb:26:in `tagged'
  activesupport (4.2.4) lib/active_support/tagged_logging.rb:68:in `tagged'
  railties (4.2.4) lib/rails/rack/logger.rb:20:in `call'
  newrelic_rpm (3.16.0.318) lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
  actionpack (4.2.4) lib/action_dispatch/middleware/request_id.rb:21:in `call'
  newrelic_rpm (3.16.0.318) lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
  rack (1.6.4) lib/rack/runtime.rb:18:in `call'
  newrelic_rpm (3.16.0.318) lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
  rack-timeout (0.4.2) lib/rack/timeout/core.rb:122:in `block in call'
  rack-timeout (0.4.2) lib/rack/timeout/support/timeout.rb:19:in `timeout'
  rack-timeout (0.4.2) lib/rack/timeout/core.rb:121:in `call'
  newrelic_rpm (3.16.0.318) lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
  activesupport (4.2.4) lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
  newrelic_rpm (3.16.0.318) lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
  rack (1.6.4) lib/rack/lock.rb:17:in `call'
  newrelic_rpm (3.16.0.318) lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
  actionpack (4.2.4) lib/action_dispatch/middleware/static.rb:116:in `call'
  newrelic_rpm (3.16.0.318) lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
  railties (4.2.4) lib/rails/engine.rb:518:in `call'
  railties (4.2.4) lib/rails/application.rb:165:in `call'
  newrelic_rpm (3.16.0.318) lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
  rack (1.6.4) lib/rack/content_length.rb:15:in `call'
  puma (3.4.0) lib/puma/configuration.rb:224:in `call'
  puma (3.4.0) lib/puma/server.rb:569:in `handle_request'
  puma (3.4.0) lib/puma/server.rb:406:in `process_client'
  puma (3.4.0) lib/puma/server.rb:271:in `block in run'
  puma (3.4.0) lib/puma/thread_pool.rb:114:in `block in spawn_thread'


  Rendered /Users/mattLummus1/.rvm/gems/ruby-2.3.0/gems/actionpack-4.2.4/lib/action_dispatch/middleware/templates/rescues/_trace.html.erb (1.4ms)
  Rendered /Users/mattLummus1/.rvm/gems/ruby-2.3.0/gems/actionpack-4.2.4/lib/action_dispatch/middleware/templates/routes/_route.html.erb (19.3ms)
  Rendered /Users/mattLummus1/.rvm/gems/ruby-2.3.0/gems/actionpack-4.2.4/lib/action_dispatch/middleware/templates/routes/_table.html.erb (6.7ms)
  Rendered /Users/mattLummus1/.rvm/gems/ruby-2.3.0/gems/actionpack-4.2.4/lib/action_dispatch/middleware/templates/rescues/_request_and_response.html.erb (1.3ms)
  Rendered /Users/mattLummus1/.rvm/gems/ruby-2.3.0/gems/actionpack-4.2.4/lib/action_dispatch/middleware/templates/rescues/routing_error.html.erb within rescues/layout (76.1ms)```
``````

**Comment by maclover7** [comment]
Can you create an executable test script using one of the templates [here](https://github.com/rails/rails/tree/master/guides/bug_report_templates), that would demonstrate the problem you are seeing, with the only gem installed being Rails? It's likely that a third party dependency is doing something funky with your routes. :(

**Comment by chashmeetsingh** [comment]
@mattLummus check whether the request u r sending is a get or post and verify it with the one in routes

**Comment by PaulBabka** [comment]
I'm having the same issue.  Ruby 2.2.0, Rails 4.2.7 / passenger, Route in question is mounted as an engine.  Route shows up in rake routes. App works fine for hours.  Suddenly RouteError POST to a valid route (its a hardcoded callback, so the URL is not entered by a user, but a call back POST from an authentication service).  apachectl restart fixes it for a while.  I'm at a loss.  Same issues as posted above.  Any ideas where to look?  Got to be something environmental.  Rails 1.9 was previously installed on server.

**Comment by imechemi** [comment]
I am facing same issue, we have a route that is mounted as an engine. All of a sudden, apps starts throwing 404 randomly for a valid route and then apache restarts fixes it temporarily. This happens at some period of time and hard to reproduce.

**Comment by PaulBabka** [comment]
Hi - No solution, but I found upgrading to the latest 4.x release made the issue go away…

**Comment by ViksYelapale** [comment]
I am facing same issue with rails 5.1.4 and Ruby 2.4.1. I have also tried with ruby version 2.4.0 but no luck. I have also tried by changing the gemset but not worked that as well. All routes throwing 404  suddenly expect root route. Anyone have any luck on this. Thanks in advance !

Error Log:

ActionController::RoutingError (No route matches [GET] "/login"):
  
actionpack (5.1.4) lib/action_dispatch/middleware/debug_exceptions.rb:63:in `call'
newrelic_rpm (4.4.0.336) lib/new_relic/agent/instrumentation/middleware_tracing.rb:92:in `call'
actionpack (5.1.4) lib/action_dispatch/middleware/show_exceptions.rb:31:in `call'
newrelic_rpm (4.4.0.336) lib/new_relic/agent/instrumentation/middleware_tracing.rb:92:in `call'
lograge (0.6.0) lib/lograge/rails_ext/rack/logger.rb:15:in `call_app'
railties (5.1.4) lib/rails/rack/logger.rb:24:in `block in call'
activesupport (5.1.4) lib/active_support/tagged_logging.rb:69:in `block in tagged'
activesupport (5.1.4) lib/active_support/tagged_logging.rb:26:in `tagged'
activesupport (5.1.4) lib/active_support/tagged_logging.rb:69:in `tagged'
railties (5.1.4) lib/rails/rack/logger.rb:24:in `call'
newrelic_rpm (4.4.0.336) lib/new_relic/agent/instrumentation/middleware_tracing.rb:92:in `call'
sprockets-rails (3.2.1) lib/sprockets/rails/quiet_assets.rb:13:in `call'
newrelic_rpm (4.4.0.336) lib/new_relic/agent/instrumentation/middleware_tracing.rb:92:in `call'
actionpack (5.1.4) lib/action_dispatch/middleware/remote_ip.rb:79:in `call'
newrelic_rpm (4.4.0.336) lib/new_relic/agent/instrumentation/middleware_tracing.rb:92:in `call'
request_store (1.3.2) lib/request_store/middleware.rb:9:in `call'
newrelic_rpm (4.4.0.336) lib/new_relic/agent/instrumentation/middleware_tracing.rb:92:in `call'
actionpack (5.1.4) lib/action_dispatch/middleware/request_id.rb:25:in `call'
newrelic_rpm (4.4.0.336) lib/new_relic/agent/instrumentation/middleware_tracing.rb:92:in `call'
rack (2.0.3) lib/rack/method_override.rb:22:in `call'
newrelic_rpm (4.4.0.336) lib/new_relic/agent/instrumentation/middleware_tracing.rb:92:in `call'
rack (2.0.3) lib/rack/runtime.rb:22:in `call'
newrelic_rpm (4.4.0.336) lib/new_relic/agent/instrumentation/middleware_tracing.rb:92:in `call'
activesupport (5.1.4) lib/active_support/cache/strategy/local_cache_middleware.rb:27:in `call'
newrelic_rpm (4.4.0.336) lib/new_relic/agent/instrumentation/middleware_tracing.rb:92:in `call'
actionpack (5.1.4) lib/action_dispatch/middleware/executor.rb:12:in `call'
newrelic_rpm (4.4.0.336) lib/new_relic/agent/instrumentation/middleware_tracing.rb:92:in `call'
actionpack (5.1.4) lib/action_dispatch/middleware/static.rb:125:in `call'
newrelic_rpm (4.4.0.336) lib/new_relic/agent/instrumentation/middleware_tracing.rb:92:in `call'
rack (2.0.3) lib/rack/sendfile.rb:111:in `call'
newrelic_rpm (4.4.0.336) lib/new_relic/agent/instrumentation/middleware_tracing.rb:92:in `call'
honeybadger (3.1.2) lib/honeybadger/rack/error_notifier.rb:34:in `block in call'
honeybadger (3.1.2) lib/honeybadger/agent.rb:321:in `with_rack_env'
honeybadger (3.1.2) lib/honeybadger/rack/error_notifier.rb:31:in `call'
newrelic_rpm (4.4.0.336) lib/new_relic/agent/instrumentation/middleware_tracing.rb:92:in `call'
honeybadger (3.1.2) lib/honeybadger/rack/user_feedback.rb:31:in `call'
newrelic_rpm (4.4.0.336) lib/new_relic/agent/instrumentation/middleware_tracing.rb:92:in `call'
honeybadger (3.1.2) lib/honeybadger/rack/user_informer.rb:21:in `call'
newrelic_rpm (4.4.0.336) lib/new_relic/agent/instrumentation/middleware_tracing.rb:92:in `call'
rack-cors (1.0.1) lib/rack/cors.rb:93:in `call'
newrelic_rpm (4.4.0.336) lib/new_relic/agent/instrumentation/middleware_tracing.rb:92:in `call'
scout_apm (2.4.24) lib/scout_apm/instruments/middleware_summary.rb:58:in `call'
railties (5.1.4) lib/rails/engine.rb:522:in `call'
newrelic_rpm (4.4.0.336) lib/new_relic/agent/instrumentation/middleware_tracing.rb:92:in `call'
puma (3.10.0) lib/puma/configuration.rb:225:in `call'
puma (3.10.0) lib/puma/server.rb:605:in `handle_request'
puma (3.10.0) lib/puma/server.rb:437:in `process_client'
puma (3.10.0) lib/puma/server.rb:301:in `block in run'
puma (3.10.0) lib/puma/thread_pool.rb:120:in `block in spawn_thread'

**Comment by sumeeti** [comment]
Was there a resolution to this. I'm facing it with rails 6. Intermittently a valid GET route is not found

**Comment by jagthedrummer** [comment]
I'm also seeing this in a project, but have not been able to nail down any repro steps or identify any suspect gems.

**Comment by faraznisar** [comment]
> Was there a resolution to this. I'm facing it with rails 6. Intermittently a valid GET route is not found

Since you are the only one facing this with rails 6. I wanted to know if you somehow got it figured out. i have kind of the same issue and it is a real pain because the app in already in production and the business is taking a hit thanks to this.
