### ISSUE TITLE
Enable an option for customize "ON" clause when eager_load method is used

### ISSUE THREAD

**Issue by gslopez** [rails/rails#26046]
Hi, i opened this issue from 
https://github.com/rails/rails/issues/3912

The final solution doesn't work for me. Currently i have:

``` ruby
class Mission < ActiveRecord::Base
  has_many :mission_user_states
end

class MissionUserState < ActiveRecord::Base
  belongs_to :mission
  belongs_to :user
end

class User < ActiveRecord::Base
  has_many :mission_user_states
end
```

MissionUserState is created when a User accepts a mission. I need all missions, and preload MissionUserState associated to one specific user. If i use:

``` ruby
Mission.includes(:mission_user_states).
    where('mission_user_states.user_id = ? OR mission_user_states.user_id IS NULL', my_user.id).
    references(:mission_user_states)
```

I lose all missions associated to an user distinct to 'my_user'.

If "with()" method would exist, i could use:

``` ruby
Mission.includes(:mission_user_states).with(:user_id => my_user.id).
```

The where clause only works when i need a "INNER JOIN", but not with "LEFT OUTER JOIN".

**Comment by pixeltrix** [comment]
@gslopez does `left_joins` and `preload` do what you need? e.g:

``` ruby
Mission
  .preload(:mission_user_states)
  .left_joins(:mission_user_states)
  .where('mission_user_states.user_id = ? OR mission_user_states.user_id IS NULL', my_user.id)
```

The `left_joins` method is new to Rails 5.0 - you don't mention what version you're using.

**Comment by gslopez** [comment]
I am using rails 4.2.5.

Left join is not exactly what i need. I will explain it with an example. 

#### User table:
| id        | name           
| ------------- |-------------|
| 1      | "john" |
| 2      | "max"      |  

#### Mission table:
| id        | name           
| ------------- |-------------|
| 1      | "common mission" |
| 2      | "john started mission"      |  
| 3      | "max started mission"      |  

#### MissionUserState:
| id        | user_id           | mission_id  | state |
| ------------- |-------------| -----| -----|
| 5   | 1 (john)  | 1 (common mission) | finished|
| 6  | 2  (max) |  1 (common mission) | accepted|
| 7 | 1  (john)  |  2 (john started mission) | started|
| 8 | 2 (max)   |  3 (max started mission)| started|

I need all missions and preload the states only for one specific user, or none in other case. My expected output, for "john" user, is:

#### Mission:
| id        | name           | *preloaded_mission_user_state_id  |
| ------ |---------------------| -----|
| 1   | "common mission"       | 5 |
| 2  | "john started mission" |  2 |
| 3 | "max started mission"  |  nil |

I can get this with the following sql query:
```sql
SELECT "missions".*, "mission_user_states".* 
FROM "missions" LEFT OUTER JOIN "mission_user_states" 
    ON "mission_user_states"."mission_id" = "missions"."id" AND "mission_user_states".user_id = 1
```

I made a little project with rails 5, and i tried with your code. It returns the result:

| id        | name           | *preloaded_mission_user_state_id  |
| ------ |---------------------| -----|
| 1   | "common mission"       | 5 |
| 2  | "john started mission" |  2 |

With this sql:
```sql
SELECT "missions".* 
FROM "missions" LEFT OUTER JOIN "mission_user_states" 
    ON "mission_user_states"."mission_id" = "missions"."id" 
WHERE (mission_user_states.user_id = 5 OR mission_user_states.user_id IS NULL)

SELECT "mission_user_states".* 
FROM "mission_user_states" 
WHERE "mission_user_states"."mission_id" IN (1, 2)
````

Which is expected, because Mission with id=3 doesn't match with where clause.

EDIT: 
I think that would be 'eager_load' instead 'includes' in the proposed method.
```ruby
Mission.eager_load(:mission_user_states).with(:user_id => my_user.id).
```
