### ISSUE TITLE
Rails 4.2 showing error as can't convert String into an exact number

### ISSUE THREAD

**Issue by raunaklakhwani** [rails/rails#26055]
Hi,

I have a application. It was running successfully on rails 3.2. After I upgraded this to rails 4.2, its showing me an error:
###Error : 

> TypeError in NodesController#create (can't convert String into an exact number)

###Logs

activesupport (4.1.14.2) lib/active_support/core_ext/time/calculations.rb:44:in `at'
activesupport (4.1.14.2) lib/active_support/core_ext/time/calculations.rb:44:in `at_with_coercion'
dynamoid (1.1.0) lib/dynamoid/persistence.rb:104:in `undump_field'
dynamoid (1.1.0) lib/dynamoid/persistence.rb:61:in `block (2 levels) in undump'
dynamoid (1.1.0) lib/dynamoid/persistence.rb:60:in `each'
dynamoid (1.1.0) lib/dynamoid/persistence.rb:60:in `block in undump'
dynamoid (1.1.0) lib/dynamoid/persistence.rb:59:in `tap'
dynamoid (1.1.0) lib/dynamoid/persistence.rb:59:in `undump'
dynamoid (1.1.0) lib/dynamoid/document.rb:133:in `load'
dynamoid (1.1.0) lib/dynamoid/document.rb:128:in `block in initialize'
activesupport (4.1.14.2) lib/active_support/callbacks.rb:113:in `call'
activesupport (4.1.14.2) lib/active_support/callbacks.rb:113:in `call'
activesupport (4.1.14.2) lib/active_support/callbacks.rb:552:in `block (2 levels) in compile'
activesupport (4.1.14.2) lib/active_support/callbacks.rb:502:in `call'
activesupport (4.1.14.2) lib/active_support/callbacks.rb:502:in `call'
activesupport (4.1.14.2) lib/active_support/callbacks.rb:86:in `run_callbacks'
dynamoid (1.1.0) lib/dynamoid/document.rb:123:in `initialize'
app/controllers/nodes_controller.rb:81:in `new'
app/controllers/nodes_controller.rb:81:in `create'
actionpack (4.1.14.2) lib/action_controller/metal/implicit_render.rb:4:in `send_action'
actionpack (4.1.14.2) lib/abstract_controller/base.rb:189:in `process_action'
actionpack (4.1.14.2) lib/action_controller/metal/rendering.rb:10:in `process_action'
actionpack (4.1.14.2) lib/abstract_controller/callbacks.rb:20:in `block in process_action'
activesupport (4.1.14.2) lib/active_support/callbacks.rb:113:in `call'
activesupport (4.1.14.2) lib/active_support/callbacks.rb:113:in `call'
activesupport (4.1.14.2) lib/active_support/callbacks.rb:552:in `block (2 levels) in compile'
activesupport (4.1.14.2) lib/active_support/callbacks.rb:502:in `call'
activesupport (4.1.14.2) lib/active_support/callbacks.rb:502:in `call'
activesupport (4.1.14.2) lib/active_support/callbacks.rb:86:in `run_callbacks'
actionpack (4.1.14.2) lib/abstract_controller/callbacks.rb:19:in `process_action'
actionpack (4.1.14.2) lib/action_controller/metal/rescue.rb:29:in `process_action'
actionpack (4.1.14.2) lib/action_controller/metal/instrumentation.rb:32:in `block in process_action'
activesupport (4.1.14.2) lib/active_support/notifications.rb:159:in `block in instrument'
activesupport (4.1.14.2) lib/active_support/notifications/instrumenter.rb:20:in `instrument'
activesupport (4.1.14.2) lib/active_support/notifications.rb:159:in `instrument'
actionpack (4.1.14.2) lib/action_controller/metal/instrumentation.rb:30:in `process_action'
actionpack (4.1.14.2) lib/action_controller/metal/params_wrapper.rb:250:in `process_action'
actionpack (4.1.14.2) lib/abstract_controller/base.rb:136:in `process'
actionview (4.1.14.2) lib/action_view/rendering.rb:30:in `process'
actionpack (4.1.14.2) lib/action_controller/metal.rb:196:in `dispatch'
actionpack (4.1.14.2) lib/action_controller/metal/rack_delegation.rb:13:in `dispatch'
actionpack (4.1.14.2) lib/action_controller/metal.rb:232:in `block in action'
actionpack (4.1.14.2) lib/action_dispatch/routing/route_set.rb:80:in `call'
actionpack (4.1.14.2) lib/action_dispatch/routing/route_set.rb:80:in `dispatch'
actionpack (4.1.14.2) lib/action_dispatch/routing/route_set.rb:48:in `call'
actionpack (4.1.14.2) lib/action_dispatch/journey/router.rb:73:in `block in call'
actionpack (4.1.14.2) lib/action_dispatch/journey/router.rb:59:in `each'
actionpack (4.1.14.2) lib/action_dispatch/journey/router.rb:59:in `call'
actionpack (4.1.14.2) lib/action_dispatch/routing/route_set.rb:690:in `call'
rack (1.5.2) lib/rack/etag.rb:23:in `call'
rack (1.5.2) lib/rack/conditionalget.rb:35:in `call'
rack (1.5.2) lib/rack/head.rb:11:in `call'
actionpack (4.1.14.2) lib/action_dispatch/middleware/params_parser.rb:27:in `call'
actionpack (4.1.14.2) lib/action_dispatch/middleware/flash.rb:254:in `call'
rack (1.5.2) lib/rack/session/abstract/id.rb:225:in `context'
rack (1.5.2) lib/rack/session/abstract/id.rb:220:in `call'
actionpack (4.1.14.2) lib/action_dispatch/middleware/cookies.rb:562:in `call'
actionpack (4.1.14.2) lib/action_dispatch/middleware/callbacks.rb:29:in `block in call'
activesupport (4.1.14.2) lib/active_support/callbacks.rb:82:in `run_callbacks'
actionpack (4.1.14.2) lib/action_dispatch/middleware/callbacks.rb:27:in `call'
actionpack (4.1.14.2) lib/action_dispatch/middleware/reloader.rb:73:in `call'
actionpack (4.1.14.2) lib/action_dispatch/middleware/remote_ip.rb:76:in `call'
actionpack (4.1.14.2) lib/action_dispatch/middleware/debug_exceptions.rb:17:in `call'
actionpack (4.1.14.2) lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
railties (4.1.14.2) lib/rails/rack/logger.rb:38:in `call_app'
railties (4.1.14.2) lib/rails/rack/logger.rb:20:in `block in call'
activesupport (4.1.14.2) lib/active_support/tagged_logging.rb:68:in `block in tagged'
activesupport (4.1.14.2) lib/active_support/tagged_logging.rb:26:in `tagged'
activesupport (4.1.14.2) lib/active_support/tagged_logging.rb:68:in `tagged'
railties (4.1.14.2) lib/rails/rack/logger.rb:20:in `call'
/opt/brazil-pkg-cache/packages/AmazonRailsLogger/AmazonRailsLogger-4.0.80.55/RHEL5_64/DEV.STD.PTHREAD/build/ruby1.9/site_ruby/1.9.1/amazon/set_request_id.rb:9:in `call'
/opt/brazil-pkg-cache/packages/AmazonRailsLogger/AmazonRailsLogger-4.0.80.55/RHEL5_64/DEV.STD.PTHREAD/build/ruby1.9/site_ruby/1.9.1/amazon/set_request_id.rb:9:in `call'
actionpack (4.1.14.2) lib/action_dispatch/middleware/request_id.rb:21:in `call'
rack (1.5.2) lib/rack/methodoverride.rb:21:in `call'
rack (1.5.2) lib/rack/runtime.rb:17:in `call'
activesupport (4.1.14.2) lib/active_support/cache/strategy/local_cache_middleware.rb:26:in `call'
rack (1.5.2) lib/rack/lock.rb:17:in `call'
actionpack (4.1.14.2) lib/action_dispatch/middleware/static.rb:84:in `call'
rack (1.5.2) lib/rack/sendfile.rb:112:in `call'
railties (4.1.14.2) lib/rails/engine.rb:514:in `call'
railties (4.1.14.2) lib/rails/application.rb:144:in `call'
railties (4.1.14.2) lib/rails/railtie.rb:194:in `public_send'
railties (4.1.14.2) lib/rails/railtie.rb:194:in `method_missing'
rack (1.5.2) lib/rack/lint.rb:49:in `_call'
rack (1.5.2) lib/rack/lint.rb:37:in `call'
rack (1.5.2) lib/rack/showexceptions.rb:24:in `call'
rack (1.5.2) lib/rack/commonlogger.rb:33:in `call'
rack (1.5.2) lib/rack/chunked.rb:43:in `call'
rack (1.5.2) lib/rack/content_length.rb:14:in `call'
rack (1.5.2) lib/rack/handler/webrick.rb:60:in `service'
/home/lakhwani/FCLaunchRequirement/env/FCLaunchRequirementWebsite-1.0/runtime/ruby1.9/1.9.1/webrick/httpserver.rb:138:in `service'
/home/lakhwani/FCLaunchRequirement/env/FCLaunchRequirementWebsite-1.0/runtime/ruby1.9/1.9.1/webrick/httpserver.rb:94:in `run'
/home/lakhwani/FCLaunchRequirement/env/FCLaunchRequirementWebsite-1.0/runtime/ruby1.9/1.9.1/webrick/server.rb:191:in `block in start_thread'

### System configuration
**Rails version**: 4.2

**Ruby version**: 1.9

Can you please help me in this?

**Comment by pixeltrix** [comment]
This error is being raised by the `Time.at` method and not by Rails, e.g:

```
$ irb
>> Time.at('0')
TypeError: can't convert String into an exact number
	from (irb):1:in `at'
	from (irb):1
	from /Users/andyw/.rvm/rubies/ruby-2.2.4/bin/irb:11:in `<main>'
```

It looks like a string is being passed instead of an integer. Since this isn't a Rails bug I'm closing.
