### ISSUE TITLE
NumericalityValidator fails on equal decimal to decimal comparisons

### ISSUE THREAD

**Issue by diminish7** [rails/rails#26085]
### Steps to reproduce

Migration:

``` ruby
create_table :number_ranges do |t|
  t.decimal :low
  t.decimal :high
end
```

Model:

``` ruby
class NumberRange < ApplicationRecord
  validates :high, numericality: { greater_than_or_equal_to: :low }
end
```

Spec:

``` ruby
describe NumberRange do
  describe "#high :greater_than_or_equal_to :low validation" do
    it "is valid with equal high and low" do
      # This fails because the validator compares Float('65.6') to BigDecimal('65.6')
      expect(FinalCost.new(low: '65.6', high: '65.6').to be_valid
    end
  end
end
```
### Expected behavior

When validating numericality's `greater_than_or_equal_to` on a decimal column against the value of another decimal column, two equal raw values ought to validate correctly.
### Actual behavior

`NumericalityValidator#parse_raw_value_as_a_number` always parses with `Kernel.Float(raw_value)`, so the validated value is a float, while the comparison value is a `BigDecimal`, and so, due to precision differences, equal numbers will fail validation.
### System configuration

**Rails version**:
`5.0.0` (verified on current master as well)

**Ruby version**:
`2.3.1p112`

**Comment by maclover7** [comment]
Created a reproduction script --> https://gist.github.com/maclover7/f2f118e70d1191a722c7f8669a93c887.

Confirmed as mentioned above that the issue is that we are trying to compare a `BigDecimal` to the `Float` we are creating [here](https://github.com/rails/rails/blob/master/activemodel/lib/active_model/validations/numericality.rb#L75).

Did this work for you on 4.2.x?

**Comment by pixeltrix** [comment]
@maclover7 4-2-stable uses `Kernel.Float` too so I suspect so

**Comment by diminish7** [comment]
@pixeltrix @maclover7 Confirmed, I was able to reproduce in `4.2.7`

**Comment by nanaya** [comment]
At least changing [this line's condition](/rails/rails/blob/67d0c9ee93100dbdcafd20b0632e5bef6735888e/activemodel/lib/active_model/validations/numericality.rb#L41) to:

```
unless value.is_a?(Numeric)
```

fixes this specific test. I think it's more logical to let comparison to be done in the post-casted value when possible?

(not sure what this breaks though :D )

**Comment by pixeltrix** [comment]
> I think it's more logical to let comparison to be done in the post-casted value when possible?

@nanaya unfortunately that negates the point of the validator - things like "foo" will be cast to 0 automatically and not generate an error.

Probably the easiest solution is to replace the use of `Float` with `BigDecimal` since it's safer to cast to that.

**Comment by nanaya** [comment]
The numeric validation happens at line 31 and 36. The following lines are doing comparison against another values.

**Comment by diminish7** [comment]
@pixeltrix I think replacing `Float` with `BigDecimal` in `#parse_raw_value_as_a_number` breaks `is_number?` because `BigDecimal('foo')` doesn't blow up, it creates a `BigDecimal` with a value of `0.0`. So `is_number?` maybe needs to check a regex rather than depending on `Float()`?

Also, I'm wondering if replacing `Float()` with `BigDecimal()` creates the opposite problem, breaking equality when compared against a float field?

**Comment by pixeltrix** [comment]
@diminish7 depends on the precision:

```
>> Float('85.6') == BigDecimal(Float('85.6'), 16)
=> true 
>> Float('85.6') == BigDecimal(Float('85.6'), 8)
=> false 
```

but yeah, I did think about how safe it'd be. Convert both sides to `BigDecimal` maybe? 😄

**Comment by pixeltrix** [comment]
Looks like 7500daec69499e4f2da2fc06cd816c754cf59504 was related to this.

**Comment by nanaya** [comment]
Reading [this comment](/rails/rails/pull/22760#issuecomment-166728500), I think the line really should check for `value`, not `raw_value`.

**Comment by AminArria** [comment]
Has this issue been resolved?

**Comment by moeabdol** [comment]
@nanaya is correct! I'm submitting a PR #29697. Please let me know what you think. Thanks.
