### ISSUE TITLE
where.not does not match nil (NULL) records

### ISSUE THREAD

**Issue by georgeu2000** [rails/rails#26084]
### Steps to reproduce
`User.where.not(status:'complete')` generates the SQL:

    SELECT * FROM "users" WHERE ("users"."status" != $1)  [["status", "complete"]]

### Expected behavior
If the status is nil, then I expect the record to be returned.

### Actual behavior
SQL does not return records with NULL status.

### Suggested feature
The query should match NULL records:

    SELECT * FROM "users" WHERE ("users"."status" != $1) OR ("users"."status" IS NULL )  [["status", "complete"]]

### System configuration
**Rails version**:4.2.6   
PostgreSQL

**Ruby version**:2.3.1p112

I can do PR if this feature makes sense.

**Comment by matthewd** [comment]
This is expected behaviour; as a relatively thin layer on top of SQL, we consciously allow the SQL NULL behaviour to show through.

**Comment by georgeu2000** [comment]
OK, then maybe I'll update RailsGuides or API docs.
