### ISSUE TITLE
[DOCS] Changelog dates? (and docs site info)

### ISSUE THREAD

**Issue by MSP-Greg** [rails/rails#26080]
It would be helpful if Changelog updates included a date.

Also, I’m keeping a relatively current set of docs for the master branch (along with four Ruby versions & aws-sdk-ruby) at

https://msp-greg.github.io/Rails-5.1/ 

Home page has UI info and other notes, along with links to the other libraries.

* All private, protected, and :nodoc: methods shown.
* All the guides are included, see the 'Docs List'.
* Files names and methods have links to the Git repo, along with the source listing.

You may find it helpful and easier to navigate (for large libraries like Rails) than standard YARD or RDoc sites.  Also, a bit more tablet friendly.

I'll close this in a few days if someone else doesn't...

**Comment by rafaelfranca** [comment]
> It would be helpful if Changelog updates included a date.

Helpful for? Changelogs are tied to release, if there is no release why people should care about when a change was made?

Private, protected and even more important nodoc methods should not be presented to users. They are private api of the framework and may be removed, renamed or even moved without any warning.

**Comment by MSP-Greg** [comment]
I suppose people doing development on Rails want to spend all their time reviewing code in an IDE?  Whatever...
