### ISSUE TITLE
rake db:migrate doesn't work (rake aborted! StandardError: An error has occurred)

### ISSUE THREAD

**Issue by elibar-uk** [rails/rails#26091]
I started to have a issue with migrations with the  project I was working on. I've started a brand new one but the issue is still appearing the same. Error messages appearing on attempts to do rake db:migrate
(have tried both starting new project with the default database- sqlite3 and the optional- postgresql ), however, after generating a model (tried both with rails g scaffold Schedule name:name dep_date:datetime and just model - rails g model Schedule name:name dep_date:datetime ) migration stays down.

the migration itself is:

class CreateSchedules < ActiveRecord::Migration[5.0]
  def change
    create_table :schedules do |t|
      t.name :name
      t.datetime :dep_date

      t.timestamps
    end
  end
end

command :   rake db:migrate:status 
give:

database: travel_t_challenge_development

 Status   Migration ID    Migration Name
--------------------------------------------------
  down    20160809121048  Create schedules

commands:

rake db:migrate 
rake RAILS_ENV=production db:migrate or
rake db:migrate:up VERSION=20160809121048 or
bundle exec rake db:migrate VERSION=20160809121048
(or redo)
result in the same error: 

== 20160809121048 CreateSchedules: migrating ==================================
-- create_table(:schedules)
rake aborted!
StandardError: An error has occurred, this and all later migrations canceled:

wrong number of arguments (1 for 0)
/Users/[username]/workspace/travel_t_challenge/db/migrate/20160809121048_create_schedules.rb:4:in `block in change'
/Users/[username]/.rvm/gems/ruby-2.2.2@global/gems/activerecord-5.0.0/lib/active_record/connection_adapters/abstract/schema_statements.rb:277:in `create_table'
/Users/[username]/.rvm/gems/ruby-2.2.2@global/gems/activerecord-5.0.0/lib/active_record/migration.rb:845:in `block in method_missing'
/Users/[username]/.rvm/gems/ruby-2.2.2@global/gems/activerecord-5.0.0/lib/active_record/migration.rb:814:in `block in say_with_time'
/Users/[username]/.rvm/gems/ruby-2.2.2@global/gems/activerecord-5.0.0/lib/active_record/migration.rb:814:in `say_with_time'
/Users/[username]/.rvm/gems/ruby-2.2.2@global/gems/activerecord-5.0.0/lib/active_record/migration.rb:834:in `method_missing'
/Users/[username]/workspace/travel_t_challenge/db/migrate/20160809121048_create_schedules.rb:3:in `change'
/Users/[username]/.rvm/gems/ruby-2.2.2@global/gems/activerecord-5.0.0/lib/active_record/migration.rb:788:in `exec_migration'
/Users/[username]/.rvm/gems/ruby-2.2.2@global/gems/activerecord-5.0.0/lib/active_record/migration.rb:772:in `block (2 levels) in migrate'
/Users/[username]/.rvm/gems/ruby-2.2.2@global/gems/activerecord-5.0.0/lib/active_record/migration.rb:771:in `block in migrate'
/Users/[username]/.rvm/gems/ruby-2.2.2@global/gems/activerecord-5.0.0/lib/active_record/connection_adapters/abstract/connection_pool.rb:398:in `with_connection'
/Users/[username]/.rvm/gems/ruby-2.2.2@global/gems/activerecord-5.0.0/lib/active_record/migration.rb:770:in `migrate'
/Users/[username]/.rvm/gems/ruby-2.2.2@global/gems/activerecord-5.0.0/lib/active_record/migration.rb:950:in `migrate'
/Users/[username]/.rvm/gems/ruby-2.2.2@global/gems/activerecord-5.0.0/lib/active_record/migration.rb:1211:in `block in execute_migration_in_transaction'
/Users/[username]/.rvm/gems/ruby-2.2.2@global/gems/activerecord-5.0.0/lib/active_record/migration.rb:1279:in `block in ddl_transaction'
/Users/[username]/.rvm/gems/ruby-2.2.2@global/gems/activerecord-5.0.0/lib/active_record/connection_adapters/abstract/database_statements.rb:232:in `block in transaction'
/Users/[username]/.rvm/gems/ruby-2.2.2@global/gems/activerecord-5.0.0/lib/active_record/connection_adapters/abstract/transaction.rb:189:in `within_new_transaction'
/Users/[username]/.rvm/gems/ruby-2.2.2@global/gems/activerecord-5.0.0/lib/active_record/connection_adapters/abstract/database_statements.rb:232:in `transaction'
/Users/[username]/.rvm/gems/ruby-2.2.2@global/gems/activerecord-5.0.0/lib/active_record/transactions.rb:211:in `transaction'
/Users/[username]/.rvm/gems/ruby-2.2.2@global/gems/activerecord-5.0.0/lib/active_record/migration.rb:1279:in `ddl_transaction'
/Users/[username]/.rvm/gems/ruby-2.2.2@global/gems/activerecord-5.0.0/lib/active_record/migration.rb:1210:in `execute_migration_in_transaction'
/Users/[username]/.rvm/gems/ruby-2.2.2@global/gems/activerecord-5.0.0/lib/active_record/migration.rb:1183:in `block in migrate_without_lock'
/Users/[username]/.rvm/gems/ruby-2.2.2@global/gems/activerecord-5.0.0/lib/active_record/migration.rb:1182:in `each'
/Users/[username]/.rvm/gems/ruby-2.2.2@global/gems/activerecord-5.0.0/lib/active_record/migration.rb:1182:in `migrate_without_lock'
/Users/[username]/.rvm/gems/ruby-2.2.2@global/gems/activerecord-5.0.0/lib/active_record/migration.rb:1131:in `block in migrate'
/Users/[username]/.rvm/gems/ruby-2.2.2@global/gems/activerecord-5.0.0/lib/active_record/migration.rb:1298:in `with_advisory_lock'
/Users/[username]/.rvm/gems/ruby-2.2.2@global/gems/activerecord-5.0.0/lib/active_record/migration.rb:1131:in `migrate'
/Users/[username]/.rvm/gems/ruby-2.2.2@global/gems/activerecord-5.0.0/lib/active_record/migration.rb:1005:in `up'
/Users/[username]/.rvm/gems/ruby-2.2.2@global/gems/activerecord-5.0.0/lib/active_record/migration.rb:989:in `migrate'
/Users/[username]/.rvm/gems/ruby-2.2.2@global/gems/activerecord-5.0.0/lib/active_record/tasks/database_tasks.rb:161:in `migrate'
/Users/[username]/.rvm/gems/ruby-2.2.2@global/gems/activerecord-5.0.0/lib/active_record/railties/databases.rake:58:in `block (2 levels) in <top (required)>'
/Users/[username]/.rvm/gems/ruby-2.2.2/gems/rake-11.2.2/exe/rake:27:in `<top (required)>'
/Users/[username]/.rvm/gems/ruby-2.2.2/bin/ruby_executable_hooks:15:in `eval'
/Users/[username]/.rvm/gems/ruby-2.2.2/bin/ruby_executable_hooks:15:in `<main>'
ArgumentError: wrong number of arguments (1 for 0)
/Users/[username]/workspace/travel_t_challenge/db/migrate/20160809121048_create_schedules.rb:4:in `block in change'
/Users/[username]/.rvm/gems/ruby-2.2.2@global/gems/activerecord-5.0.0/lib/active_record/connection_adapters/abstract/schema_statements.rb:277:in `create_table'
/Users/[username]/.rvm/gems/ruby-2.2.2@global/gems/activerecord-5.0.0/lib/active_record/migration.rb:845:in `block in method_missing'
/Users/[username]/.rvm/gems/ruby-2.2.2@global/gems/activerecord-5.0.0/lib/active_record/migration.rb:814:in `block in say_with_time'
/Users/[username]/.rvm/gems/ruby-2.2.2@global/gems/activerecord-5.0.0/lib/active_record/migration.rb:814:in `say_with_time'
/Users/[username]/.rvm/gems/ruby-2.2.2@global/gems/activerecord-5.0.0/lib/active_record/migration.rb:834:in `method_missing'
/Users/[username]/workspace/travel_t_challenge/db/migrate/20160809121048_create_schedules.rb:3:in `change'
/Users/[username]/.rvm/gems/ruby-2.2.2@global/gems/activerecord-5.0.0/lib/active_record/migration.rb:788:in `exec_migration'
/Users/[username]/.rvm/gems/ruby-2.2.2@global/gems/activerecord-5.0.0/lib/active_record/migration.rb:772:in `block (2 levels) in migrate'
/Users/[username]/.rvm/gems/ruby-2.2.2@global/gems/activerecord-5.0.0/lib/active_record/migration.rb:771:in `block in migrate'
/Users/[username]/.rvm/gems/ruby-2.2.2@global/gems/activerecord-5.0.0/lib/active_record/connection_adapters/abstract/connection_pool.rb:398:in `with_connection'
/Users/[username]/.rvm/gems/ruby-2.2.2@global/gems/activerecord-5.0.0/lib/active_record/migration.rb:770:in `migrate'
/Users/[username]/.rvm/gems/ruby-2.2.2@global/gems/activerecord-5.0.0/lib/active_record/migration.rb:950:in `migrate'
/Users/[username]/.rvm/gems/ruby-2.2.2@global/gems/activerecord-5.0.0/lib/active_record/migration.rb:1211:in `block in execute_migration_in_transaction'
/Users/[username]/.rvm/gems/ruby-2.2.2@global/gems/activerecord-5.0.0/lib/active_record/migration.rb:1279:in `block in ddl_transaction'
/Users/[username]/.rvm/gems/ruby-2.2.2@global/gems/activerecord-5.0.0/lib/active_record/connection_adapters/abstract/database_statements.rb:232:in `block in transaction'
/Users/[username]/.rvm/gems/ruby-2.2.2@global/gems/activerecord-5.0.0/lib/active_record/connection_adapters/abstract/transaction.rb:189:in `within_new_transaction'
/Users/[username]/.rvm/gems/ruby-2.2.2@global/gems/activerecord-5.0.0/lib/active_record/connection_adapters/abstract/database_statements.rb:232:in `transaction'
/Users/[username]/.rvm/gems/ruby-2.2.2@global/gems/activerecord-5.0.0/lib/active_record/transactions.rb:211:in `transaction'
/Users/[username]/.rvm/gems/ruby-2.2.2@global/gems/activerecord-5.0.0/lib/active_record/migration.rb:1279:in `ddl_transaction'
/Users/[username]/.rvm/gems/ruby-2.2.2@global/gems/activerecord-5.0.0/lib/active_record/migration.rb:1210:in `execute_migration_in_transaction'
/Users/[username]/.rvm/gems/ruby-2.2.2@global/gems/activerecord-5.0.0/lib/active_record/migration.rb:1183:in `block in migrate_without_lock'
/Users/[username]/.rvm/gems/ruby-2.2.2@global/gems/activerecord-5.0.0/lib/active_record/migration.rb:1182:in `each'
/Users/[username]/.rvm/gems/ruby-2.2.2@global/gems/activerecord-5.0.0/lib/active_record/migration.rb:1182:in `migrate_without_lock'
/Users/[username]/.rvm/gems/ruby-2.2.2@global/gems/activerecord-5.0.0/lib/active_record/migration.rb:1131:in `block in migrate'
/Users/[username]/.rvm/gems/ruby-2.2.2@global/gems/activerecord-5.0.0/lib/active_record/migration.rb:1298:in `with_advisory_lock'
/Users/[username]/.rvm/gems/ruby-2.2.2@global/gems/activerecord-5.0.0/lib/active_record/migration.rb:1131:in `migrate'
/Users/[username]/.rvm/gems/ruby-2.2.2@global/gems/activerecord-5.0.0/lib/active_record/migration.rb:1005:in `up'
/Users/[username]/.rvm/gems/ruby-2.2.2@global/gems/activerecord-5.0.0/lib/active_record/migration.rb:989:in `migrate'
/Users/[username]/.rvm/gems/ruby-2.2.2@global/gems/activerecord-5.0.0/lib/active_record/tasks/database_tasks.rb:161:in `migrate'
/Users/[username]/.rvm/gems/ruby-2.2.2@global/gems/activerecord-5.0.0/lib/active_record/railties/databases.rake:58:in `block (2 levels) in <top (required)>'
/Users/[username]/.rvm/gems/ruby-2.2.2/gems/rake-11.2.2/exe/rake:27:in `<top (required)>'
/Users/[username]/.rvm/gems/ruby-2.2.2/bin/ruby_executable_hooks:15:in `eval'
/Users/[username]/.rvm/gems/ruby-2.2.2/bin/ruby_executable_hooks:15:in `<main>'
Tasks: TOP => db:migrate
(See full trace by running task with --trace)

Dropping and setting up/creating the database again hasn't helped either. 

### System configuration
**Rails version**:5.0.0
**Ruby version**:2.2.3

**Comment by MaximAbramchuck** [comment]
You have
`t.name :name`

Does it even a valid syntax? Can you try `t.string :name` instead?

**Comment by elibar-uk** [comment]
sincerely appreciate, I couldn't see the typo..
