### ISSUE TITLE
Rails 5 AR migrations: default value for json type columns

### ISSUE THREAD

**Issue by cmager** [rails/rails#26101]
### Steps to reproduce

Run a migration like this:

`add_column :pages, :config, :json, null: false, default: '{}'`

or

```
create_table :pages do |t|
  t.json :config, null: false, default: '{}'
end
````

I have tested on PostgreSQL only.

### Expected behavior

Under Rails 4.2 these migrations created a column like this:
View with postgresql client: `\d pages`

```
Column   |            Type             |                            Modifiers
---------+-----------------------------+-----------------------------------------------------------------
  config | json                        | not null default '{}'::json
```

### Actual behavior

Under Rails 5 these migrations created the default value as a json string.

```
Column   |            Type             |                            Modifiers
---------+-----------------------------+-----------------------------------------------------------------
  config | json                        | not null default '"{}"'::json
```

### System configuration
**Rails version**: 5.0.0
**Ruby version**: 2.3.1
**PG gem**: 1.8.4
**PG Server**: 9.4 - 9.5

**Comment by cmager** [comment]
When changing the column type to `jsonb`it is creating the default value as expected.
Is it possible to get the behavior back to rails 5 as it was under rails 4.2?

**Comment by veekram** [comment]
@cmager Yup. I got the same .

**Comment by pixeltrix** [comment]
@cmager can you check whether changing to `default: {}` works correctly?

**Comment by cmager** [comment]
@pixeltrix this is working correctly

**Comment by sgrif** [comment]
This is the expected behavior. A string containing `"{}"` is a valid JSON primitive. `default: {}` is the correct usage.

**Comment by kenju** [comment]
> This is the expected behavior. A string containing "{}" is a valid JSON primitive. default: {} is the correct usage.

Here is more details about why on this behavior -> https://github.com/rails/rails/issues/25594

**Comment by acrolink** [comment]
when to use "[]" as default instead of "{}" ?
