### ISSUE TITLE
Proposal: decimal field declarations default to scale: 2 in migrations

### ISSUE THREAD

**Issue by BattleBrisket** [rails/rails#26106]
Given a valid migration, this field declaration:

```
t.decimal :foobar
```

Is currently equivalent to 

```
t.decimal :foobar, precision: 10, scale: 0
```

This keeps migrations in line with the standard SQL definitions for a `DECIMAL` field, which default to `DECIMAL(10)`, which is equivalent to `DECIMAL(10,0)`

If I am defining a `DECIMAL` field I am anticipating fractional values _by rule_. Why should the default behavior assume the opposite and behave like an integer? 

Keeping in line with existing rules "just because" is not The Rails Way, which is designed to write beautiful code and make developer's lives easier. 

I therefore propose that we adjust migration behavior for `decimal` field declarations to default to `precision: 10, scale: 2`. 

**Real world result:** I have a Rails 5.0 app with the following migration

```
    create_table :rate_books do |t|
      t.decimal :ffs_including_all_ime, precision: 10, scale: 2
      t.decimal :ime_phase_out_dollar_amount, precision: 10, scale: 2
      t.decimal :ffs_rate_excluding_phase_out_ime, precision: 10, scale: 2
      t.decimal :pre_aca_rate_excludes_phased_out_ime, precision: 10, scale: 2
      t.decimal :quartile_percent, precision: 5, scale: 4
      t.decimal :bonus_rate, precision: 10, scale: 2
      t.timestamps null: false
    end
```

I see no reason why this should not read as 

```
    create_table :rate_books do |t|
      t.decimal :ffs_including_all_ime
      t.decimal :ime_phase_out_dollar_amount
      t.decimal :ffs_rate_excluding_phase_out_ime
      t.decimal :pre_aca_rate_excludes_phased_out_ime
      t.decimal :quartile_percent, precision: 5, scale: 4
      t.decimal :bonus_rate
      t.timestamps null: false
    end
```

Thoughts?

**Comment by rafaelfranca** [comment]
Thank you for the proposal. I never had to use those values as defaults in my applications so I believe this may be specific for you case.

Even if it wasn't I don't think we should try to guess what is the expectation of the users for this case. The database default is the safer choice to us.
