### ISSUE TITLE
has_many with scope, dependent and foreign_key needs better documentation

### ISSUE THREAD

**Issue by claudiob** [rails/rails#26111]
I found an _unexpected_ behavior in [has_many](http://api.rubyonrails.org/classes/ActiveRecord/Associations/ClassMethods.html#method-i-has_many) that I illustrated with a [failing test in a gist](https://gist.github.com/claudiob/545fa683615bbc7cb6d8ddc99c4306c1).

The short version is the following. If you have these two models:

```ruby
class Post < ActiveRecord::Base
  has_many :comments, -> { where('text is not null') }, dependent: :destroy
end

class Comment < ActiveRecord::Base
end
```

and you call `destroy` on a post, then not all the comments of the post will be destroyed, but only the comments that match the scope  `where('text is not null')`.

Some people might argue that this is the _expected_ behavior, since the Rails [documentation of has_many](http://api.rubyonrails.org/classes/ActiveRecord/Associations/ClassMethods.html#method-i-has_and_belongs_to_many-label-Scopes) states:

> You can pass a second argument scope as a callable (i.e. proc or lambda) to retrieve a specific set of records or customize the generated query when you access the associated collection.

The problem is that, if `post.destroy` does not delete *all* the comments of post, then some comments might be left in the database without a corresponding post. 

Even worse, if you declared a foreign key between the `comments` table and the `posts` table (which is the common case for references), then you can end up with the following error, which is the result of running the referenced [gist]((https://gist.github.com/claudiob/545fa683615bbc7cb6d8ddc99c4306c1)):

```sh
# Comment Load (0.2ms)  SELECT "comments".* FROM "comments" WHERE "comments"."post_id" = $1 AND (text is not null)  [["post_id", 1]]
# SQL (0.1ms)  DELETE FROM "comments" WHERE "comments"."id" = $1  [["id", 2]]
# SQL (0.6ms)  DELETE FROM "posts" WHERE "posts"."id" = $1  [["id", 1]]
# (0.1ms)  ROLLBACK

ActiveRecord::InvalidForeignKey: PG::ForeignKeyViolation: ERROR:  
update or delete on table "posts" violates foreign key constraint "fk_rails_2fd19c0db7" on table "comments"
DETAIL:  Key (id)=(1) is still referenced from table "comments".
: DELETE FROM "posts" WHERE "posts"."id" = $1
```

What do you think? Should the documentation be a little more verbose in this case?

**Comment by rafaelfranca** [comment]
> What do you think? Should the documentation be a little more verbose in this case?

Yes, I agree we should have more verbose documentation about this case.
