### ISSUE TITLE
Jobs enqueued with Sidekiq gets wrong Enqueued value

### ISSUE THREAD

**Issue by theodorton** [rails/rails#26115]
### Steps to reproduce

1. Enqueue a job

```rb
ActiveJob::Base.queue_adapter = :sidekiq

class NoopJob < ActiveJob::Base
end

NoopJob.set(wait_until: 30.minutes.from_now).perform_later
```

2. Open Sidekiq's [web panel for scheduled jobs](http://localhost:3000/sidekiq/scheduled)
3. Click on the job you've enqueued
4. Look for the Enqueued value in the table

![skjermbilde 2016-08-11 kl 10 58 10](https://cloud.githubusercontent.com/assets/874365/17583699/83b848a4-5fb2-11e6-8f08-a62a87fb9c30.png)

### Expected behavior
When I schedule a job to run later with Sidekiq, I expect the Enqueued value in Sidekiq's web panel to reflect the time the job was scheduled.

### Actual behavior
When I schedule a job to run later with Sidekiq, and I visit the Sidekiq's web panel, the Enqueued value tells me the job was created 47 years ago. Probably 1970-01-01 rounded to year.

### System configuration
**Rails version**: 4.2.6

**Ruby version**: 2.3.1.1p112

**Comment by vishalzambre** [comment]
@theodorton  Please check your system and database time, I verified this one and working fine for me.

**Comment by mperham** [comment]
This behavior is because you have not enqueued the job yet, you've only scheduled it to be enqueued in the future.

**Comment by theodorton** [comment]
@mperham Thanks for clarifying! :)

I'll close this issue and see if I can attempt to fix it in the sidekiq repo.
