### ISSUE TITLE
ActionController::Live deadlock on `const_missing` after `SSE#write`

### ISSUE THREAD

**Issue by achinn** [rails/rails#26123]
I'm seeing a deadlock occur when a constant is being loaded after a call to `SSE#write`. This will only occur when there's some delay between the two.

In my exact scenario I'm using `Redis#subscribe` to run a GraphQL query when an event occurs. I was able to distill the issue down to the fact that running the query triggers `const_missing` which causes the deadlock. I created a basic Rails app without the Redis/GraphQL dependencies which reproduces the issue.

Of note is that if you use Rails `4.2.6` in my example app you don't run into the issue.

### Steps to reproduce

https://github.com/achinn/ac-live-deadlock

### Expected behavior

The SSE should close at the end of the HTTP request.

### Actual behavior

A deadlock occurs when a constant is being loaded.

### System configuration
**Rails version**: 5.0.0

**Ruby version**: 2.3.1p112

**Comment by achinn** [comment]
cc @christhomson

**Comment by achinn** [comment]
@matthewd: Could this be related to changes in #23532? It would help to give me a starting place to look.

**Comment by christhomson** [comment]
We also tested this against Rails master (at some point yesterday) and it was still an issue there too, so it hasn't been fixed since 5.0.0.

fyi @rafaelfranca this is the problem I was asking about on Slack yesterday.

**Comment by matthewd** [comment]
If you're on master you should be able to use https://github.com/rails/rails/pull/25344 to get traces of the conflicting threads, if that helps

**Comment by achinn** [comment]
Thanks @matthewd, that middleware did help out.
From what I can gather it looks like there's a race condition here:
https://github.com/rails/rails/blob/master/actionpack/lib/action_controller/metal/live.rb#L269

When the child thread writes to the stream it unblocks the parent which then reacquires its share lock. The child could then want to acquire an exclusive lock at a later point (e.g. via `const_missing`).
Does that sound like I'm on the right track?

**Comment by matthewd** [comment]
Ah! Yes.

https://github.com/rails/rails/blob/master/actionpack/lib/action_controller/metal/live.rb#L208 needs a `permit_concurrent_loads` around the `pop`.
