### ISSUE TITLE
assert_redirected_to duplicate _url suffix

### ISSUE THREAD

**Issue by rosswilson** [rails/rails#26127]
Using `assert_redirected_to :login_url` as show in the docs, results in the error:

```
NoMethodError: undefined method `login_url_url' for #<LoginController:0x007fc6f3a066f0>
```

### Steps to reproduce

Use the `assert_redirected_to` method within an ActionDispatch::IntegrationTest test. Pass it a route name that includes the `_url` suffix. As shown in the docs: http://api.rubyonrails.org/classes/ActionDispatch/Assertions/ResponseAssertions.html#method-i-assert_redirected_to

### Expected behavior
The redirected route should be compared to`login_url`

### Actual behavior
The redirected route is being compared to`login_url_url` - an extra `_url` suffix is being added.

### Additional Information

This bug also applies when passing a route with the `_path` suffix. Resulting in the error:

```
NoMethodError: undefined method `login_path_url' for #<LoginController:0x002fc6c3a066c0>
```

### System configuration
**Rails version**: Rails 5.0.0

**Ruby version**: ruby 2.3.1p112 (2016-04-26 revision 54768) [x86_64-darwin15]

**Comment by georgeclaghorn** [comment]
The docs demonstrate `assert_redirected_to login_url`, which is not the same as `assert_redirected_to :login_url`.
