### ISSUE TITLE
add_index migration doesn't write :order option to schema.rb or database

### ISSUE THREAD

**Issue by brendon** [rails/rails#26128]
### Steps to reproduce
I create a migration like so:

```ruby
class AddIndexOnNameToUsers < ActiveRecord::Migration
  def change
  	add_index :users, [:id, :name], order: :name
  end
end
```

The migration runs successfully:

```
== 20160811220629 AddIndexOnNameToUsers: migrating ============================
-- add_index(:users, [:id, :name], {:order=>:name})
   -> 0.0039s
== 20160811220629 AddIndexOnNameToUsers: migrated (0.0041s) ===================
```

### Expected behavior
I'd expect the order to be defined in the index query in the database as well as the `schema.rb`.

### Actual behavior
The database doesn't reflect the order clause, and neither does `schema.rb`:

```
CREATE INDEX index_users_on_id_and_name
  ON public.users
  USING btree
  (id, name COLLATE pg_catalog."default");
```

```ruby
  add_index "users", ["id", "name"], name: "index_users_on_id_and_name", using: :tree
```

### System configuration
**Rails version**: 4.2.7.1

**Ruby version**: 2.2.2p95

**Postgresql version**: 9.5.2

**pg gem version**: 0.18.4

**Comment by prathamesh-sonpatki** [comment]
The API documentation states 

``` ruby
add_index(:accounts, [:branch_id, :party_id, :surname], order: {branch_id: :desc, party_id: :asc})
```

Can you try with `add_index :users, [:id, :name], order: { name: :asc }`

**Comment by bithavoc** [comment]
I don't think this is a bug, according to [postgres 9.5/indexes-ordering docs](https://www.postgresql.org/docs/9.5/static/indexes-ordering.html):
> By default, B-tree indexes store their entries in ascending order with nulls last.

So the default ordering is `asc` and the following declaration have the same **implicit** meaning:
* `add_index :users, [:id, :name], order: :name`
* `add_index :users, [:id, :name], order: { name: :asc }`
* `add_index :users, [:id, :name]`

the database index will be the same: 
```
"index_users_on_id_and_name" btree (id, name)`
```
and so is the schema:
```
add_index "users", ["id", "name"], name: "index_users_on_id_and_name", using: :btree
```

**Descending** on the other hand needs to be stated in the schema **explicitly**.

Example: a migration declaring `add_index :users, [:id, :name], order: { name: :desc }` will result in a database index as:

```
"index_users_on_id_and_name" btree (id, name DESC)
```
and schema:
```
add_index "users", ["id", "name"], name: "index_users_on_id_and_name", order: {"name"=>:desc}, using: :btree
```

Tested in Rails **4.2** and **5.0**.

**Comment by brendon** [comment]
Ah yes! I just had this thought and tested it out to find that you're right. :) Thanks for looking into this though. And hopefully this helps someone else in the future :)

**Comment by guilleiguaran** [comment]
@bithavoc thanks for the great explanation 👏

**Comment by jsantos** [comment]
@bithavoc So every time the schema changes we need to correct the index representation manually? That's what I'm experiencing with a `desc` index.
