### ISSUE TITLE
Proposal: Increasing efficiency of current_version method in active_record/migration

### ISSUE THREAD

**Issue by kyatul** [rails/rails#26120]
In [**activerecord/lib/active_record/migration.rb**](https://github.com/rails/rails/blob/master/activerecord/lib/active_record/migration.rb), for class **Migrator** we have two methods **current_version** and **get_all_version**.

Currently **current_version** calls **get_all_version** and selects maximum value from returned array.
**get_all_version** fetches all the records, and then it loops through it gathering version number, and then sorting it.

**CURRENT CODE**
`
      def get_all_versions(connection = Base.connection)        
        
       ActiveSupport::Deprecation.silence do
          if connection.table_exists?(schema_migrations_table_name)
            SchemaMigration.all.map { |x| x.version.to_i }.sort  
          else
            []
          end        
        end      
      end

      def current_version(connection = Base.connection)
        get_all_versions(connection).max || 0
      end`

We can get rid of all this overhead, if we can simply query DB to fetch the maximum version number in **current_version** method.

**PROPOSED CODE**
`
    def current_version(connection = Base.connection)
      ActiveSupport::Deprecation.silence do
        if connection.table_exists?(schema_migrations_table_name)
            SchemaMigration.maximum(:version).to_i
        end
      end
   end`

Although current code has cleaner one line approach, but we can look for bigger picture regarding efficiency.
Any suggestions on this are highly appreciated

**Comment by kaspth** [comment]
`needs_migration?` also uses `get_all_versions` and expects it to return an array, so unfortunately we can't just yank it.

Other than that, we need a benchmark to evaluate any performance gain from this. Besides that this doesn't seem like a hotspot, as such we're less likely to accept performance PRs unless the gains are major.

I like your idea though and thanks for the pull request! 😁

**Comment by kyatul** [comment]
Thanks for your review @kaspth. But I have propsed to change **current_version** and not **get_all_version**. So I don't find any dependencies getting messed up like needs_migration? as you suggested.

**Comment by kaspth** [comment]
Ah, you're right, I missed that. My comments on the performance of it still stands though. Plus I'd rather have `needs_migration?` keep using `get_all_versions` instead of duplicating the table exists and deprecation silencing.

**Comment by kyatul** [comment]
Ofcourse, I proposed no change for **needs_migration?**, it will remain as it is.

I would go ahead and do benchmarking for current_version method and share result with you. So that we can see how much we can gain from it. :)

**Comment by kaspth** [comment]
Sorry, I meant to say `current_version`. I don't think there's any need for the benchmark because the proposed change doesn't seem worth it from a maintainability standpoint. I can't see us switching to the proposed change even if it was 10x faster, it's just not a hot spot :)

Unless you can prove it gets called more often than I think and show me that your proposed change has a marked difference on say `db:migrate` :D
