### ISSUE TITLE
Preloading STI trough join table applies STI scope to join table and crashes

### ISSUE THREAD

**Issue by tbreier** [rails/rails#26129]
### Steps to reproduce

Run https://gist.github.com/tbreier/67b2fbd6c679ccea3fd847693f96f9b1

Post 1 <-> n Comment n <-> 1 User (STI) 
And now try to preload a specific type of users on posts.
### Expected behavior

It should preload all users of the specific type on the post records.
### Actual behavior

```
  1) Error:
BugTest#test_association_stuff:
ActiveRecord::StatementInvalid: SQLite3::SQLException: no such column: users.type: SELECT "comments".* FROM "comments" WHERE "users"."type" IN ('OneTypeOfUsers') AND "comments"."post_id" = 1
```
### System configuration

**_Discovered on:**_
**Rails version**:
4.2.1
**Ruby version**:
2.1.2

**_Gist written for:**_
**Rails version**:
Master (5.1.0alpha)
**Ruby version**:
2.3.1

**Comment by tbreier** [comment]
Hm. I just realized it works as expected when I replace
```ruby
belongs_to :one_type_of_users, foreign_key: :user_id
```

with 
```ruby
belongs_to :one_type_of_users, -> { where type: OneTypeOfUsers }, class_name: 'User', foreign_key: :user_id
```
, so not sure if that actually is a bug. 2nd way seems rather cumbersome though. Are you supposed to not reference the STI subclasses directly in associations?

**Comment by veekram** [comment]
It surely needs  `class_name: 'User'` to know where it is referenced.

**Comment by tbreier** [comment]
Thanks for your reply @veekram.
> It surely needs ```class_name: 'User'``` to know where it is referenced. You may want to check this .

The linked docs do not say much about how associations are supposed to work with regard to STI tables (with the exception of using them in polymorphic associations).
The association I set up, ```one_type_of_users```, does work when directly referenced or in joins.

```
Comment.one_type_of_users
Post.one_type_of_users
Post.joins(:one_type_of_users)
# etc
```
I don't see how Rails needs me to specify `class_name: 'User'` here, as it can get that from the STI hierarchy.

It seems to only break for ```Post.all.includes(:one_type_of_users)```, because it applies the STI scope (`WHERE "users"."type" IN ('OneTypeOfUsers')`) to the join table (comments). To me, this seems like a bug? Or is it never okay to reference models inheriting in STI in associations directly?

**Comment by tbreier** [comment]
@rafaelfranca Would you mind taking another look and/or letting me know why this was closed? Thank you! 😄

**Comment by k0kubun** [comment]
Maybe duplicated with https://github.com/rails/rails/issues/11078.
