### ISSUE TITLE
Typo on asset pipeline guide, says to use rails instead of rake

### ISSUE THREAD

**Issue by antidis** [rails/rails#26136]
### Steps to reproduce

* Go to http://guides.rubyonrails.org/asset_pipeline.html#precompiling-assets
* Read the command

### Expected behavior

The command used should be:

```
$ RAILS_ENV=production bin/rake assets:precompile
```

### Actual behavior

The command listed is

```
$ RAILS_ENV=production bin/rails assets:precompile
```

**Comment by atussec** [comment]
rails 5 uses rails instead of rake. and `RAILS_ENV=production bin/rails assets:precompile` works fine in rails 5 and compiles the assets

**Comment by antidis** [comment]
Got it. I'm using Rails 4, must be why.

**Comment by prathamesh-sonpatki** [comment]
@antidis You can check http://guides.rubyonrails.org/v4.2/ for Rails 4 version of guides 💚
