### ISSUE TITLE
Logging backend being flooded by Rails 5 DebugExceptions

### ISSUE THREAD

**Issue by mattcg** [rails/rails#26134]
### Steps to reproduce
1. Set up Rails application that uses the [gelf-rb](https://rubygems.org/gems/gelf) gem to log to a Graylog backend.
2. Trigger an exception in the application.
### Expected behavior

A single message is logged, with the exception.
### Actual behavior

Hundreds of messages are logged for a single exception, including one for each line of the stack trace.
### System configuration

Rails 5.0.0
Ruby 2.3.0

**Comment by rafaelfranca** [comment]
Does it happens without this backend? Is rails doing various call to the logger backend or it is the logger backend that is handling a single call to the backend as many?

**Comment by mattcg** [comment]
It happens without the backend. Rails makes a call to `logger.fatal` for every line of the stack trace, including decorative calls for formatting. This is abuse of the logger.

This breaking change was introduced to DebugExceptions by in @vipulnsward in 632938cfda8762a98a7c7a360a6f05c29d2cdb5e.

**Comment by vipulnsward** [comment]
@mattcg the change was on purpose to log tags from request, see original intention here-https://github.com/rails/rails/issues/22979

AFAIK, the logs are not flushed immediately, so multiple calls to fatal are OK. 
I need to see what is causing issue with the gem.

**Comment by mattcg** [comment]
@vipulnsward I understand your intention, but surely the semantic meaning of `logger.fatal` is to log a single log message not a log line. You are assuming that the logger methods will always be used to log to a terminal or a flat file.

It's not feasible to assume that a logger could condense multiple calls to `fatal` into a single message before they are flushed. How is it supposed to know that subsequent calls are part of the same message?

#22979 is best solved at the log formatter level, not at the DebugExceptions level. If you want tags to appear at the beginning of every line, format the log lines in that way.

**Comment by palexvs** [comment]
In result, we got inconsistent logger tags behaviour - some multilines messages (Errors) contain tags when other does not, examples:
- Exception:
```
[9ba518a4a7c1] app/controllers/test_controller.rb:7:in `index'
[9ba518a4a7c1] lib/request_filter.rb:37:in `call'
[9ba518a4a7c1] lib/handle_unknown_http_method.rb:8:in `call'
```
- simple multiline message `Rails.logger.info "test\ntest" `:
```
[286c21b2f29c] test
dd
```
- multiline SQL query `Model.where("some\ncomplex\nquery")`:
```
[0e63d617e6b9] SELECT ... FROM ... WHERE some
complex
query
```

I think `ActionDispatch::DebugExceptions.log_error` should not add tags, it should be managed centrilized in `ActiveSupport::TaggedLogging::Formatter.call`. `ActiveSupport::TaggedLogging::Formatter` can check if a `msg` is a multiline and add tags to each line
