### ISSUE TITLE
Missing URL helper for namespaced `root` route

### ISSUE THREAD

**Issue by buehmann** [rails/rails#26148]
While upgrading our app to Rails 5.0, we came across this apparent regression: `root` routes in namespaces fail to generate URL helpers in some cases.

### Steps to reproduce

https://gist.github.com/buehmann/b2024a146ade68c9b03dd8893105102a
```
$ ruby root-url-helpers.rb

  1) Failure:
BugTest#test_url_helpers_defined [root-url-helpers.rb:40]:
Expected #<Module:0x0055bd5eeab3b8> (Module) to respond to #bar_root_url.

1 runs, 3 assertions, 1 failures, 0 errors, 0 skips
```
With Rails 4.2 a URL helper was generated for every nested `root`:
```
$ V=4.2.7.1 ruby root-url-helpers.rb

1 runs, 3 assertions, 0 failures, 0 errors, 0 skips
```

### Workaround

As a workaround, we use an explicit
```
root 'test#index', as: 'root'
```
at the moment.

**Comment by intuxicated** [comment]
confirming that this works on version 4.2-stable but not in > 5.0.0

**Comment by pixeltrix** [comment]
Backported in 73e783800526e51faf4fb4f9bce0d41578e936d7
