### ISSUE TITLE
ActionCable doesn't work with Unicorn in development

### ISSUE THREAD

**Issue by jgonera** [rails/rails#26179]
### Steps to reproduce

I think this might be a wide enough problem that it can be reproduced with pretty much any app so I'm not providing all the code for now, but I can if others can't reproduce.

First, create a Rails 5 app that uses `ActionCable` with the following channel:

``` ruby
class StreamingChannel < ApplicationCable::Channel
  def subscribed
    stream_from "streaming:#{params[:file_name]}"
  end
end
```

Then, try to subscribe to that channel in JS with the following code:

``` javascript
(function() {
  var streamingChannel = App.cable.subscriptions.create(
    {
      channel: "StreamingChannel",
      some: "some_param"
    },
    {
      received: function(data) {
        return $('body').append(data.content);
      }
    }
  );
}).call(this);
```

Finally, **Start your app using Unicorn with `RACK_ENV` set to `development`.**
### Expected behavior

This works in Puma (3.4.0), but not in Unicorn (5.1.0, 4.8.3).

This should work and you should receive messages in the client (JS) when doing:

``` ruby
StreamingChannel.broadcast_to("some_param", content: "something")
```

After sending a subscribe message:

```
{"command":"subscribe","identifier":"{\"channel\":\"StreamingChannel\",\"param\":\"some_param\"}"}
```

a confirmation message should be received:

```
{"command":"message","identifier":"{\"channel\":\"StreamingChannel\",\"param\":\"some_param\"}","data":"{\"action\":\"subscribed\"}"}
```

but it isn't. You would also expect to see this in the logs (it shows up with Puma, not in Unicorn):

```
StreamingChannel is transmitting the subscription confirmation
StreamingChannel is streaming from streaming:some_param
```
### Actual behavior

I only receive welcome and ping messages in the client:

```
{"type":"welcome"}
{"type":"ping","message":1471299986}
...
```
### Cause

I tracked this to be caused by `Rack::Lint` that [Unicorn adds (or doesn't remove, depends how you look at it) when `RACK_ENV` is set to `development`](https://github.com/defunkt/unicorn/blob/8be441f052ee9c375993359f7642d3599ef3f6aa/lib/unicorn.rb#L66-L86).

A workaround I'm using right now is `RACK_ENV=deployment RAILS_ENV=development`.

Commenting out the following two lines in `Rack::Lint` also solves the problem:
- https://github.com/rack/rack/blob/fd1fbab1ec8c7fc49ac805aac47b1f12d4cc5a99/lib/rack/lint.rb#L620
- https://github.com/rack/rack/blob/fd1fbab1ec8c7fc49ac805aac47b1f12d4cc5a99/lib/rack/lint.rb#L551

The first one checks if HTTP status is a number >= 100 and fails with ActionCable/hijacking which sets it to -1:

```
2016-08-15_21:58:49.33116 Rack::Lint::LintError: Status must be >=100 seen as integer
2016-08-15_21:58:49.33120       /home/vagrant/.gem/ruby/2.3.0/gems/rack-2.0.1/lib/rack/lint.rb:20:in `assert'
2016-08-15_21:58:49.33120       /home/vagrant/.gem/ruby/2.3.0/gems/rack-2.0.1/lib/rack/lint.rb:620:in `check_status'
...
```

The second one wraps `HijackWrapper` around the class (in case of Unicorn `Kgio::Socket`) that `WebSocket::Driver` uses to write messages. That class is fetched from `env["rack.hijack"]`.
### Possible solution
- Properly forward messages in `HijackWrapper`.
- Fix ActionCable if it violates something that `Rack::Lint` legitimately fails on OR fix `Rack::Lint` to not complain about things that hijacking does if they are not bad.

I unfortunately don't have enough time to dig further now, but I'm reporting this as it seems it's something that more people will run into.
### System configuration

**Rails version**: 5.0

**Ruby version**: 2.3.1

**Unicorn**: 5.1.0 or 4.8.3

**Comment by Slimerkhb** [comment]
+1

**Comment by maclover7** [comment]
@jgonera Sorry for the delay, and thank you for reporting!

Unfortunately, I'm not sure there's much Action Cable itself, as a library, can do in this situation. I think there are two possible solutions to this issue, which would involve making modifications to Rack or Unicorn:

- Submit a patch upstream to `Rack::Lint` that would do some kind of a IO hijacking check, before raising an error if a `>= 100` status code is not returned, so this behavior can continue to function.
- Submit a patch upstream to Unicorn to remove the `Rack::Lint` middleware altogether from its mixed-in middleware stack.

Either way the solution to this problem lies outside the boundaries of Action Cable, and instead needs to focus on fixing third party dependencies 😬 😬

**Comment by nofxx** [comment]
Lost hours with this... thanks @jgonera 
Let me help with some keywords... 
ActionCable registers but doesn't subscribe, App.cable.subscriptions silent failure

**Comment by dijonkitchen** [comment]
Should this be closed then?

**Comment by Kevinrob** [comment]
I lost a lot of time with that...

My workaround: `config/initializers/rack_lint_websocket.rb`
```ruby
class ::Rack::Lint
  alias check_status_orig check_status
  alias check_headers_orig check_headers
  alias check_content_type_orig check_content_type
  alias check_content_length_orig check_content_length
  alias check_hijack_orig check_hijack
  alias _call_orig _call

  def _call(env)
    @web_socket = env['REQUEST_PATH'] == '/cable'
    _call_orig(env)
  end

  def check_status(status)
    return if @web_socket
    check_status_orig(status)
  end

  def check_headers(headers)
    return if @web_socket
    check_headers_orig(headers)
  end

  def check_content_type(status, headers)
    return if @web_socket
    check_content_type_orig(status, headers)
  end

  def check_content_length(status, headers)
    return if @web_socket
    check_content_type_orig(status, headers)
  end

  def check_hijack(env)
    # Don't know why, but HijackWrapper break WebSocket!
    return if @web_socket
    check_hijack_orig(env)
  end
end
```

**Comment by bayburin** [comment]
@Kevinrob you saved my life!!! Thanks!

**Comment by lacostenycoder** [comment]
@Kevinrob so is monkeypatch still the only working solution? I had [looked for help](https://github.com/rack/rack/issues/2136#issue-2000497402) thinking it was Rack related but I guess not.
