### ISSUE TITLE
Error on numericality using less_than_or_equal_to

### ISSUE THREAD

**Issue by pcragone** [rails/rails#26174]
### Steps to reproduce
- Clone the following repository: 
`git clone https://github.com/pcragone/rails_issue/tree/numericality_error`
- Setup the gems
`bundle install`
- Migrate the database:
`rake db:migrate`
- Launch the server:
`rails s`
- Visit:
`localhost:3000/products/new`
- Fill out the fields, making sure to leave the "Price" field blank, and putting any value in the field for "Sales Price"
- Click "Create Product".

### Expected behavior
The nil value should evaluate to `0` and should be compared as normal.

### Actual behavior
`ArgumentError: comparison of Fixnum with nil failed`

### System configuration
**Rails version**: 5.0.0

**Ruby version**: 2.2.3

**Comment by prathamesh-sonpatki** [comment]
Was this working before Rails 5?

**Comment by pcragone** [comment]
I don't think so.  I discovered it in my application in 4.1, but built Rails 5.0 when I built the trial application

**Comment by prakashmurthy** [comment]
Executable script for reproducing this issue:

<details>
  <summary>numericality_error.rb</summary>
```ruby
begin
  require "bundler/inline"
rescue LoadError => e
  $stderr.puts "Bundler version 1.10 or later is required. Please update your Bundler"
  raise e
end

gemfile(true) do
  source "https://rubygems.org"
  # Activate the gem you are reporting the issue against.
  gem "activerecord", "5.0.0"
  gem "sqlite3"
end

require "active_record"
require "minitest/autorun"
require "logger"

# Ensure backward compatibility with Minitest 4
Minitest::Test = MiniTest::Unit::TestCase unless defined?(Minitest::Test)

# This connection will do for database-independent bug reports.
ActiveRecord::Base.establish_connection(adapter: "sqlite3", database: ":memory:")
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :products do |t|
    t.string :name
    t.text :description
    t.float :price
    t.float :sales_price

    t.timestamps
  end
end

class Product < ActiveRecord::Base
  validates :sales_price, numericality: {only_integer: true, less_than_or_equal_to: :price}, allow_blank: true
end

class BugTest < Minitest::Test
  def test_validates_numericality_of
    product_params = {
      name: "First Product",
      description: "Product Desc; the best of all products",
      price: "",
      sales_price: "23"
    }
    assert Product.create!(product_params)
  end
end
```
</details>

**Comment by sgrif** [comment]
This is the expected behavior. Set `allow_nil: true` if you wish to allow nil.

**Comment by pcragone** [comment]
Ya'll are baller. Thanks for looking into this.
