### ISSUE TITLE
Unable to prepend appname (SCRIPT_NAME) to url in rspec tests

### ISSUE THREAD

**Issue by joykoduru** [rails/rails#26173]
### Steps to reproduce

I have a method which creates route url by appending host, app name, parameters.
Now, I have integration tests to test this functionality. In the before block I have the below assignment:
`@controller.config.relative_url_root = ::Rails.application.config.relative_url_root`
This `@controller.config.relative_url_root` is assigned to `@request.env["SCRIPT_NAME"]` on this [line](https://github.com/rails/rails/blob/v4.2.6/actionpack/lib/action_controller/test_case.rb#L747).

Using debugger, it is clear that SCRIPT_NAME is being set to the desired app name but still it is not returning the url with the SCRIPT_NAME included. 

I understood that the tests are doing something different than the actual code to generate urls.

Any suggestions? Am I missing something here?

(Guidelines for creating a bug report are [available
here](http://guides.rubyonrails.org/contributing_to_ruby_on_rails.html#creating-a-bug-report))
### Expected behavior

The spec should return url with @request.env['SCRIPT_NAME'] value included/prepended.
### Actual behavior

It returns a url without the @request.env['SCRIPT_NAME'] value. All other parameters are in place.
### System configuration

**Rails version**:
4.2.6
actionpack: 4.2.6

**Ruby version**:
2.3.0

**Comment by prathamesh-sonpatki** [comment]
Can you upload a sample application on Github that reproduces the issue? Thanks.

**Comment by joykoduru** [comment]
Hey @prathamesh-sonpatki, thanks for your response. I'm working on stubbing out a sample app that replicates the issue. 

Thanks

**Comment by joykoduru** [comment]
@prathamesh-sonpatki, the sample app I was trying to build has turned out much more difficult than I thought it would be because of my company's internal code. Is it possible for you to tell what might be going wrong from your experience?

**Comment by prathamesh-sonpatki** [comment]
I will check the code and see what is going on in few days.

**Comment by joykoduru** [comment]
Thank you @prathamesh-sonpatki
