### ISSUE TITLE
Migrations. Default value to column raises and error

### ISSUE THREAD

**Issue by k2m30** [rails/rails#26172]
This behaviour worked fine in Rails 4.2. Now I have an error:

```
class AddSomeArrayToUser < ActiveRecord::Migration
  def change
    add_column :users, :some_array, :text, default: []
  end
end

class User < ApplicationRecord
  serialize :some_array
end
```

### Steps to reproduce

`rails db:migrate`

### Expected behavior
Just serialize to yaml/hash as before.

### Actual behavior

```
== 20160416214334 AddSomeArrayToUser: migrating =============================
-- add_column(:users, :some_array, :text, {:default=>[]})
rails aborted!
StandardError: An error has occurred, this and all later migrations canceled:

can't quote Array
/usr/local/lib/ruby/gems/2.3.0/gems/activerecord-5.0.0.1/lib/active_record/connection_adapters/abstract/quoting.rb:177:in `_quote'
/usr/local/lib/ruby/gems/2.3.0/gems/activerecord-5.0.0.1/lib/active_record/connection_adapters/postgresql/quoting.rb:96:in `_quote'
...
```

### System configuration
**Rails version**:
5.0.0.1
**Ruby version**:
2.3.0

**Comment by prathamesh-sonpatki** [comment]
@k2m30 Do we not need to speicfy `array: true` for array columns as follows? 

``` ruby
add_column :users, :some_array, :text, array: true, default: []
```

**Comment by prathamesh-sonpatki** [comment]
Verified that above migrations works on Rails 5 and PG database.

**Comment by k2m30** [comment]
@prathamesh-sonpatki Thank you, will know for future. 
http://api.rubyonrails.org/classes/ActiveRecord/ConnectionAdapters/SchemaStatements.html#method-i-add_column 
There is no mentions here.

**Comment by k2m30** [comment]
@prathamesh-sonpatki and by the way, how to deal with `change_column_default`?

It seems, adding `array:true` is not possible there.

**Comment by prathamesh-sonpatki** [comment]
@k2m30 Can you send a PR for adding documentation about `array: true` here - http://api.rubyonrails.org/classes/ActiveRecord/ConnectionAdapters/SchemaStatements.html#method-i-add_column

Note that we should mention that is applicable for PostgreSQL only.

AFAICS, `change_column_default` comes into picture when we want to change default value of the column, we **don't change** type of column here. So you can/should be able to change default value of a array column using it.

**Comment by k2m30** [comment]
@prathamesh-sonpatki It seems I cannot update this column is usual way, is there anything else I need to add to documentation?

```
== 20160816072441 AddSomeArrayToUser: migrating ===============================
-- add_column(:users, :some_array, :text, {:array=>true, :default=>[]})
   -> 0.0321s
== 20160816072441 AddSomeArrayToUser: migrated (0.0322s) ======================

>rails c                                                                                               10:25
irb(main):001:0> User.create(name: '1')
=> #<User id: 1, name: "1", some_array: []>

irb(main):003:0> User.first.update(some_array: [12,3])
  User Load (0.3ms)  SELECT  "users".* FROM "users" ORDER BY "users"."id" ASC LIMIT $1  [["LIMIT", 1]]
   (0.2ms)  BEGIN
  SQL (14.2ms)  UPDATE "users" SET "some_array" = $1 WHERE "users"."id" = $2  [["some_array", "--- []\n"], ["id", 1]]
   (0.2ms)  ROLLBACK
ActiveRecord::StatementInvalid: PG::InvalidTextRepresentation: ERROR:  malformed array literal: "--- []
"
DETAIL:  Array value must start with "{" or dimension information.
```

**Comment by maclover7** [comment]
Looks like @oss92 opened up #26181, which adds docs for this.

**Comment by prathamesh-sonpatki** [comment]
@k2m30 Are you setting `serialize :array` for this column in your model? Please try again after removing it.

@maclover7 Yup, but we still need to mention that it is only for PostgreSQL and not for other databases. @k2m30 can send PR for that :smile:

**Comment by oss92** [comment]
@prathamesh-sonpatki I guess developers should be aware of the limitations of the databases they are using. IMHO it is not the responsibility of the docs.

**Comment by sgrif** [comment]
Migrations won't be affected by changes to an Active Record class, so this would never see that you happen to have called `serialize` on the model. You'll need to call `to_yaml` if you want a YAML dumped array in a text column (or just do `serialize :whatever, Array` in your model and leave the default as nil as per the documentation).

YAML dumping by default was never meant to be visible public API at this level -- there's no bug here.
