### ISSUE TITLE
Confusing part at `5 Getting Up and Running`

### ISSUE THREAD

**Issue by greenbigfrog** [rails/rails#26187]
(Not sure if I'm reporting this at the right place)

According to the guide `config/routes.rb` should look like following after adding `resources :articles`.
```
Rails.application.routes.draw do
 
  resources :articles
 
  root 'welcome#index'
end
```

But where did the `get 'welcome/index'` go? 
If I edit the code as said in the text it would look like following:
```
Rails.application.routes.draw do
  get 'welcome/index'
 
  resources :articles
 
  root 'welcome#index'
end
```

This might be a bit confusing... (or maybe it's just me being confused)

**Comment by maclover7** [comment]
Hmm, this definitely is confusing, that the route would just disappear. Would you be willing to open up a PR here to fix this?

**Comment by greenbigfrog** [comment]
PR opened...
