### ISSUE TITLE
X-Forwarded-Port is omitted from ActionDispatch::Request#url 

### ISSUE THREAD

**Issue by benternet** [rails/rails#26180]
### Steps to reproduce

We have a configuration where nginx is forwarding requests to a rails server, configured via:

```
proxy_pass http://api:8000;
proxy_set_header X-Forwarded-Host $host;
proxy_set_header X-Forwarded-Port $server_port;
proxy_set_header X-Forwarded-For $remote_addr;
```

1. Receive an incoming request with `X-Forwarded-Host` and `X-Forwarded-Port` headers set - `web` and `8000`, respectively.
2. Check the request url in the incoming request

### Expected behavior
In a controller, checking `request.url` should include the port of the original request. Expecting 'http://web:8000'.

### Actual behavior
The port is not included for a forwarded request. Actual 'http://web'.

### System configuration
**Rails version**: 4.2.7.1

**Ruby version**: 2.3.1

**Comment by oss92** [comment]
I believe the answer lies here https://github.com/rails/rails/blob/e6e056c2c141ec94eb8e79a30ee766f77fdaf30d/actionpack/lib/action_dispatch/http/url.rb#L346
If it is a standard port, it is not shown in the url string

**Comment by prathamesh-sonpatki** [comment]
The implementation says that you need to set single header `X-Forwarded-Host` with host as well as port number -- https://github.com/rails/rails/blob/e6e056c2c141ec94eb8e79a30ee766f77fdaf30d/actionpack/lib/action_dispatch/http/url.rb#L232

**Comment by prathamesh-sonpatki** [comment]
Giving it a close as it is documented http://api.rubyonrails.org/classes/ActionDispatch/Http/URL.html#method-i-raw_host_with_port

Thanks for the report @benternet 💚

**Comment by benternet** [comment]
Sure, can put it in the `X-Forwarded-Host` header. In that case our nginx config will look like the following:

```
proxy_pass http://api:8000;
proxy_set_header X-Forwarded-Host $host:$server_port;
proxy_set_header X-Forwarded-For $remote_addr;
```
