### ISSUE TITLE
put :update with String no longer sets RAW_POST_DATA

### ISSUE THREAD

**Issue by jcoyne** [rails/rails#26194]
### Steps to reproduce

In Rails 4.2 I could do this in an ActionController::TestCase:

``` ruby
raw_string = "{title:\"sample\"}"
put :update, raw_string, id: '123', format: :json
```

but in Rails 5.0.0 this results in:

```
     ActionController::UrlGenerationError:
       No route matches {:action=>"update", :controller=>"api/items"}
```

I'm able to work around this by doing:

``` ruby
request.env['RAW_POST_DATA'] = raw_string
put :update, id: '123', format: :json
```

Was this regression intentional?

**Comment by prathamesh-sonpatki** [comment]
@jcoyne It should work with `put :update, params: raw_string, id: '123', format: :json`

This is because the request methods accept keyword argumetns now https://github.com/rails/rails/pull/18323

**Comment by jcoyne** [comment]
@prathamesh-sonpatki thank you. This is mostly a report that it doesn't work in the deprecated non-kwargs way. I would t be terribly inconvenienced if this is closed as #wontfix

**Comment by prathamesh-sonpatki** [comment]
We should definitely work on documenting it. I will keep it open for now. I am looking into the code to see if we can improve something.

**Comment by bobmaerten** [comment]
As of Rails5, `ActionController::TestCase` being deprecated, I managed to replace my test class with `ActionDispatch::IntegrationTest` and use route helpers:

    post api_items_url, params: raw_string
    patch api_items_url(id: 123), params: raw_string

But I do not think this is a good thing, nor this syntax will/should continue to rails 5.x.
