### ISSUE TITLE
ActiveSupport::SafeBuffer loose its escaping depending on concatenation order

### ISSUE THREAD

**Issue by born4new** [rails/rails#26190]
### Steps to reproduce

In a view, 

```ruby
'regular string ' + '<b>should be escaped</b>'.html_safe
```

### Expected behavior

The second string should be escaped.

### Actual behavior

The second string is not escaped.

### Possible problem

```ruby
('test' + ActiveSupport::SafeBuffer.new('<b>should be escaped</b>')).class
=> String

# This one works, since `+` is redefined for ActiveSupport::SafeBuffer
(ActiveSupport::SafeBuffer.new('<b>should be escaped</b>') + 'test').class
=> ActiveSupport::SafeBuffer
```

### System configuration
**Rails version**: Rails 5.0.0.1

**Ruby version**: ruby 2.3.1p112 (2016-04-26 revision 54768) [x86_64-darwin15]

**Comment by prakashmurthy** [comment]
Looking at [the tests for `ActiveSupport::SafeBuffer`](https://github.com/rails/rails/blob/3fc0bbf008f0e935ab56559f119c9ea8250bfddd/activesupport/test/safe_buffer_test.rb#L88-L98) this seems to be the intended behavior. 

```ruby
  test "Should escape dirty buffers on add" do
    clean = "hello".html_safe
    @buffer.gsub!("", "<>")
    assert_equal "hello&lt;&gt;", clean + @buffer
  end

  test "Should concat as a normal string when safe" do
    clean = "hello".html_safe
    @buffer.gsub!("", "<>")
    assert_equal "<>hello", @buffer + clean
  end
```

**Comment by rafaelfranca** [comment]
It is. As the `html_safe` flag is not present in string it doesn't need to be escaped.
