### ISSUE TITLE
Same model validation failing Rails 5

### ISSUE THREAD

**Issue by RomarioLopezC** [rails/rails#26191]
### Steps to reproduce
I have the following validation in my model:
validates :price, numericality: { greater_than_or_equal_to: 0.01 }
Entering in price -5.0 when I submit the form, it fails and it shows me the error message in the view, but when I change the validation to this (it must do the same)
validates_numericality_of :price, greather_than_or_equal_to: 0.01
Doesn't validates and it gets created/saved correctly

### System configuration
**Rails version**: 5.0.0.1

**Ruby version**: 2.3.1

**Comment by sevenseacat** [comment]
You misspelt 'greater' as 'greather'.

**Comment by RomarioLopezC** [comment]
asdfjklask thanks @sevenseacat

**Comment by sevenseacat** [comment]
no problem :)
