### ISSUE TITLE
AR#find_by and AR#where find inconsistently with id param

### ISSUE THREAD

**Issue by amilligan** [rails/rails#26210]
### Steps to reproduce

``` ruby
user = User.find_by(id: 1) # => #<User id: 1>

User.where(id: user).first # => #<User id: 1>
User.find_by(id: user) # => nil
```

I would expect the two above statements to return the same value, as they did in Rails 4.x.  I haven't found any discussion of an intentional change to `.find_by`.
### System configuration

**Rails version**: 5.0.0.1

**Ruby version**: 2.3.1

**Comment by prakashmurthy** [comment]
[Executable test case](https://github.com/prakashmurthy/executable_test_cases/blob/512fe19422866816579cb1ac4827873bda30e0f4/find_by_test.rb) to reproduce the behavior. Works with `Rails 4.2.5.1` and fails with `Rails 5.0.0`.

`git bisect` shows that the behavior change is likely to be introduced by https://github.com/rails/rails/commit/b06f64c3480cd389d14618540d62da4978918af0

**Comment by alexcameron89** [comment]
**Sidenote:** @prakashmurthy, out of curiosity, how did you get past the `Bundler could not find compatible versions for gem "arel"` error when running Git Bisect on this.

**Comment by prakashmurthy** [comment]
@alexcameron89 In such cases, the correct version of `arel` gem has to be specified with the commit ref on `rails/arel` repo corresponding to (meaning, has the same date as) the rails commit under consideration in the bisect process. 

    gem 'arel', github: 'rails/arel', ref: 'aac9da257'

seemed to work for most steps during `git bisect` where bundler complained about arel gem.

**Comment by amilligan** [comment]
The problem here appears to be in the file `lib/active_record/statement_cache.rb` on lines 52 and 53:

```ruby
      def sql_for(binds, connection)
        val = @values.dup
        binds = connection.prepare_binds_for_database(binds) # <== casts values
        @indexes.each { |i| val[i] = connection.quote(binds.shift) } # <== quotes values
        val.join
      end
    end
```

Specifically, the method `#prepare_binds_for_database` uses the attribute type models to cast the bind values to values expected by the database.  This occurs before the `#quote`, which is what would convert the AR instance to the appropriate integer.  The `ActiveModel::Type::Integer` class doesn't understand ActiveRecord models, so it just casts it to nil.

I'm not familiar enough with this code to immediately offer a suggestion for how to reverse the order of these calls.  I will try to find some time to dig into it, if I can, but I'm naturally curious how other finder methods (e.g. `#where`) avoid this problem.

**Comment by amilligan** [comment]
I would offer that this method is already plenty brittle due to RTTI.  Allowing the quoting mechanism to properly handle the AR instance, as it does elsewhere, seems the right way to go.
