### ISSUE TITLE
content_tag :p does not wrap ul properly

### ISSUE THREAD

**Issue by ThomasSevestre** [rails/rails#26239]
with ruby 2.3.1 and latest rails 4.2

The view :

    = content_tag(:p, "<ul><li>a</li><li>a</li></ul>".html_safe)

produces :

    <p></p>
    <ul><li>a</li><li>a</li></ul>
    <p></p>

instead of :

    <p>
    <ul><li>a</li><li>a</li></ul>
    </p>

**Comment by simi** [comment]
This is not related to content_tag, but to html spec. `ul` is not valid inside of `p`.

see [SO](http://stackoverflow.com/a/5681796/319233) for more details

**Comment by MaximAbramchuck** [comment]
but rails 5.0 produces this one
`
<p>
<ul><li>a</li><li>a</li></ul>
</p>
`

**Comment by rafaelfranca** [comment]
Both versions generate the same html that is the expected. What you are seeing in your application is because haml doesn't generate invalid html and it is changing the output that rails generated
