### ISSUE TITLE
ActiveRecord `select` fails to assign values on 'AS' columns with the same name

### ISSUE THREAD

**Issue by Frexuz** [rails/rails#26244]
### Steps to reproduce

Selecting a column named `date`, with an applied mysql function `DATE()`, and naming the result the same as the original column fails:

`Payment.select("DATE(date) as date").first.date`

```
  Payment Load (0.1ms)  SELECT  DATE(date) as date FROM `payments` ORDER BY `payments`.`id` ASC LIMIT 1
nil
```

This raw query works correctly in any mysql tool.
### Expected behavior

Naming it just **d** works
`Payment.select("DATE(date) as d").first.d`

```
  Payment Load (0.4ms)  SELECT  DATE(date) as d FROM `payments` ORDER BY `payments`.`id` ASC LIMIT 1
Fri, 24 Jan 2014
```
### System configuration

**Rails version**: `github: "rails/rails", branch: '5-0-stable'`

**Ruby version**: 2.3.1
### Note

This worked before upgrading from 4.2.x to 5.0-stable

**Comment by alexcameron89** [comment]
I may have fudged this a bit, but I believe I copied your steps into a [executable gist](https://gist.github.com/alexcameron89/4e7e00d903763422670ac00119d0af45), and I was not able to reproduce the problem on `master` or `5-0-stable`.

@Frexuz, could you see if I made a discrepancy in the script from what you're doing? If so, I can update it and retest it.

**Comment by Frexuz** [comment]
@alexcameron89 thanks. Your script works and passes. So I tried removing ALL gems except **rails** and **mysql** from my application. Then removing all initializers etc until the rails console booted.

I still have my issue in the rails console, which makes no sense :( Reverting to rails 4.2.6 works.
I'll have to dig deeper. I could try a fresh rails 5 demo app tomorrow.

**Comment by sgrif** [comment]
I have a hunch as to what this is. Could you clarify what the type of the actual column `date` is?

**Comment by Frexuz** [comment]
the column type is `datetime`

**Comment by sgrif** [comment]
Hm. Still unable to reproduce. It's worth noting that we'll still run the results of the query through the datetime type as we always trust the type of the model over the type of the query. However that should never cause an issue here. The fact that it works on 4.2.6 is strange to me. I just looked through the full diff, and found nothing that should be causing this. The only two changes that look even remotely like they could in any way affect this are:

- we no longer attempt to apply subsecond precision when quoting times on versions of mysql older than 5.6.4
- The date type properly returns a date when serializing for the database

However I see no way that either of those changes could cause this issue. I strongly suspect this is an issue in the application (or a gem that was erroneously updated when attempting to update Rails)

**Comment by Frexuz** [comment]
Here's a fresh Rails 5-0-stable app with the issue https://github.com/Frexuz/activerecord-debug-26244

I tried doing the executable test, but using `gem 'rails', github: "rails/rails", branch: '5-0-stable` gives me `The git source git://github.com/rails/rails.git is not yet checked out. Please run `bundle install` before trying to start your application (Bundler::GitError)`

So I used the console instead. Steps in the readme.

**Comment by uaihebert** [comment]
I created the code bellow and I was not able to reproduce the bug. Did I miss something? Could it be the database?

```
begin
  require "bundler/inline"
rescue LoadError => e
  $stderr.puts "Bundler version 1.10 or later is required. Please update your Bundler"
  raise e
end

gemfile(true) do
  source "https://rubygems.org"
  gem "rails"
  gem "sqlite3"
end

require "active_record"
require "minitest/autorun"
require "logger"

# This connection will do for database-independent bug reports.
ActiveRecord::Base.establish_connection(adapter: "sqlite3", database: ":memory:")
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table "payments", force: :cascade do |t|
    t.datetime "date"
    t.datetime "created_at"
    t.datetime "updated_at"
  end
end

class Payment < ActiveRecord::Base

end

class BugTest < Minitest::Test
  def test_return_as_date
    Payment.create!(date: '2016-08-21 00:53:19')
    assert Payment.select("DATE(date) as d").first.d
    assert Payment.select("DATE(date) as date").first.date
  end
end
```
