### ISSUE TITLE
Warning about "Passing strings or symbols to the middleware builder is deprecated" in my customized rack

### ISSUE THREAD

**Issue by run27017** [rails/rails#26257]
### Steps to reproduce

When I config a rack middleware in my application.rb like below

    config.middleware.insert_before 0, 'APIStyle::PathUnderscore' 

it warns me about

    DEPRECATION WARNING: Passing strings or symbols to the middleware builder is deprecated, please change
    them to actual class references.  For example:

      "APIStyle::PathUnderscore" => APIStyle::PathUnderscore

However, if I remove the braces like below

    config.middleware.insert_before 0, APIStyle::PathUnderscore

It produces an error

    uninitialized constant MyApi::Application::APIStyle 

Module *APIStyle::PathUnderscore* is put in the *app/helpers/api_style/path_underscore.rb* file.

### System configuration
Rails version:  5.0

Ruby version: 2.3

**Comment by rafaelfranca** [comment]
You need to explicitly require your constant, and I recommend to not put in inside `app`.

**Comment by rafaelfranca** [comment]
This is a dup of https://github.com/rails/rails/issues/25525
