### ISSUE TITLE
Can't find out in the documentation how to change channel via javascript without refreshing page

### ISSUE THREAD

**Issue by callancarr** [rails/rails#26251]
So, like the title suggests I can't find out in the documentation how to change channel via javascript without refreshing page.

Some help with this would be greatly appreciated as I am building a large commercial application and am trying to implement AJAX channel switching.

**Comment by rafaelfranca** [comment]
Please use the mailing list or StackOverflow for questions/help, where a wider community will be able to help you. We reserve the issues tracker for issues only.

**Comment by callancarr** [comment]
Nobody answers on stack overfly because ActionCable is really new. I'd really appriciate some help with this, in a way it is a tracker issue because I've looked through all the docs and can't find anything! :/
