### ISSUE TITLE
Namespace routes

### ISSUE THREAD

**Issue by ulugbekov** [rails/rails#26263]
namespace :api do
    namespace :v1 do
      resource :cart do
        delete :empty
      end
    end
  end

 ROUTE Current:  empty_api_v1_cart DELETE    /api/v1/cart/empty(.:format)   api/v1/carts#empty

is n't elegant to put empty action after api_v1 url? like:

ROUTE Enhancement:  api_v1_empty_cart  DELETE    /api/v1/cart/empty(.:format)   api/v1/carts#empty

**Comment by rafaelfranca** [comment]
Please use the mailing list or StackOverflow for questions/help, where a wider community will be able to help you. We reserve the issues tracker for issues only.
