### ISSUE TITLE
Not able to delete default application precompilation in Rails 5.0

### ISSUE THREAD

**Issue by dbackeus** [rails/rails#26260]
### Steps to reproduce

Attempt to remove the recursive application.(css|js) precompile regex in `assets.rb` by running `Rails.application.config.assets.precompile.delete(/(?:\/|\\|\A)application\.(css|js)$/)`.

### Expected behavior
The regexp should not remain in the array after Rails is completes booting to avoid unwanted precompilation of files matching "application.(css|js)".

### Actual behavior
After rails has booted the regexp is present in the precompile array.

### Why are we even doing this in the first place?

The actual problem we're having is that we're adding `node_modules` to our asset paths. Some node modules include `application.scss` in their test directories that will match rails default regex and thus starts precompiling causing exceptions when trying to load any page.

It seems that Rails 5 adds the application regexp after `assets.rb` has loaded (in Rails 4 it was already added at that point) so I'm not sure where I should delete it (seems like principle of least surprise would be to be able to do any asset config I need to do in `assets.rb`).

Any suggestions for workarounds would be appreciated...

### System configuration
**5.0.0.1**:

**2.3.1p112**:

**Comment by duffyjp** [comment]
Does this have anything to do with ```/app/assets/config/manifest.js``` ?

http://eileencodes.com/posts/the-sprockets-4-manifest/

**Comment by dbackeus** [comment]
@duffyjp don't think so, Sprockets is at 3.7 after Rails 5 upgrade so still uses `assets.rb` to declare all the assets we actually want compiled.

**Comment by dbackeus** [comment]
We did find a work around for `assets.rb`:

```ruby
Rails.application.config.after_initialize do
  Rails.application.config.assets.precompile.delete(/(?:\/|\\|\A)application\.(css|js)$/)
end
```

Not sure how much an issue this is for other developers.

Is there any reason for the application.(css|js) regex to be directory recursive? I would have assumed the default is there just to precompile the generated app/assets/javascript/application.js and app/assets/stylesheets/application.css... Not to precompile any random application file under any available path...

**Comment by rafaelfranca** [comment]
This regexp is deprecated and we recommend you to use manifest file if you don't want its behavior.

**Comment by rafaelfranca** [comment]
BTW, it works with sprockets 3 too.

**Comment by elsurudo** [comment]
Another option is to rename your application.scss (or whatnot) to something like application_shared.scss
