### ISSUE TITLE
ActionCable channels are not available in rake tasks.

### ISSUE THREAD

**Issue by nateless** [rails/rails#26264]
If we want to broadcast some event in a task, there's no way to do it.

**Comment by rafaelfranca** [comment]
What do you mean not available? You should be able to use any code inside the application inside rake tasks if you are requiring it. Could you create a way to reproduce this issue?

**Comment by nateless** [comment]
```ruby
require './app/channels/application_cable/event_channel.rb'
namespace :events do
	task process: :environment do
		#...
		EventChannel.broadcast_to user.id, some_data
	end
end
```

When I run `rails events:process` I get:
```
NameError: uninitialized constant ApplicationCable
/Users/nate/Ruby/front/app/channels/application_cable/event_channel.rb:1:in `<top (required)>'
/Users/nate/Ruby/front/lib/tasks/events.rake:2:in `require'
/Users/nate/Ruby/front/lib/tasks/events.rake:2:in `<top (required)>'
/Users/nate/Ruby/front/Rakefile:6:in `<top (required)>'
bin/rails:4:in `require'
bin/rails:4:in `<main>'
```

Calling the same broadcast through WS works fine. If I'm not requiring `EventChannel` it throws exception about uninitialized `EventChannel`.

Rails is in API mode if it helps.

**Comment by rafaelfranca** [comment]
Does this works?

```ruby
namespace :events do
    task process: :environment do
        #...
        EventChannel.broadcast_to user.id, some_data
    end
end
```

**Comment by nateless** [comment]
@rafaelfranca, nope, it throws out `NameError: uninitialized constant EventChannel`

**Comment by rafaelfranca** [comment]
I believe this is an issue with the way your constants are defined. There is nothing preventing channels to be loaded inside tasks because when you run the task `rake environment` they are loaded. Try to move the require inside the `task` block.

**Comment by nateless** [comment]
@rafaelfranca Hmm. Strange but indeed putting require inside task fixes it. Closing and thank you for help.

**Comment by nateless** [comment]
@rafaelfranca, continued to test AC with rake tasks today. I do not know whether it's bug or not. But as rake task is another process and we broadcast from it, server doesn't see this broadcast and users unaware of it. It works only with **redis** adapter and doesn't work with **async** and **evented-redis**.
