### ISSUE TITLE
Rake tasks produces "LoadError: cannot load such file -- action_cable/engine"

### ISSUE THREAD

**Issue by bestori** [rails/rails#26268]
### Steps to reproduce
Create a new rails app and run it. (more specifically, run "bundle exec rake -P")
### Expected behavior
App should run.
### Actual behavior
rake aborted!
LoadError: cannot load such file -- action_cable/engine
### System configuration
**Rails version**: 5.0.0
**Ruby version**: 2.3.0

https://gist.github.com/bestori/81306e364cb057da21d92b770e0d5cb4

**Comment by rafaelfranca** [comment]
I just did this and everything is working. `action_cable/engine` is inside actioncable gem. If you have it in your project it should be working. This  may be a bug with bundler/rubygems.
