### ISSUE TITLE
useless transactions on insert recors using save/create

### ISSUE THREAD

**Issue by akostadinov** [rails/rails#26272]
I'm aware that transaction on model save would be useful when there are after_save hooks. But in a lot of cases the INSERT is the only statement to be executed by rails and wrapping it into a transaction is harmful to performance. For example if MariaDB server is accessible over high latency connection, then the extra two calls make the operation 3 times slower (e.g. all calls take ~ 200ms each due to latency but processing time for insert is very short so total time ~600ms instead of ~200ms).

I think it would be useful to avoid extra calls when possible.

### Steps to reproduce
in controller:
```
  # model without after_save hooks
  @mymodel = MyModel.new(...)
  @mymodel.save!
```

### Expected behavior
SQL INSERT...

### Actual behavior
BEGIN
SQL INSERT
ROLLBACK or COMMIT

### System configuration
**Rails version**:
Rails 5.0.0.1

**Ruby version**:
2.2.5

**Comment by rafaelfranca** [comment]
There is no way to us determine if people is doing something in the callbacks that needs to be wrapped in the transaction. And callbacks is not the only thing that needs to be inside the transaction, there is associations, validations, extensions.

Detecting when those call are not needed would be a lot of complexity in the framework and it would be very error prone so I don't think it is worth to avoid those calls.

**Comment by arthurnn** [comment]
I remember seen another issue about that.

I think we could probably postpone the BEGIN call of the transaction to the first db execute method. Not 100% sure yet how would that look like, but it might be possible.
