### ISSUE TITLE
ActionDispatch::Http::Headers#fetch throws NameError instead of KeyError

### ISSUE THREAD

**Issue by mprostko** [rails/rails#26278]
### Steps to reproduce
Use [ActionDispatch::Http::Headers#fetch](https://github.com/rails/rails/blob/v5.0.0.1/actionpack/lib/action_dispatch/http/headers.rb#L85) method to find a headers key that does not exist without passing an optional default value. As the method documentation states it should throw a KeyError (as it did in Rails4) but in Rails5 it throws a [NameError](https://github.com/rails/rails/blob/v5.0.0.1/actionpack/lib/action_dispatch/http/headers.rb#L89) despire the documentation saying otherwise. It was changed in the following commit: https://github.com/rails/rails/commit/bce4ff70dd1ab88e5b573ad8c88408f100cf219e 

In my opinion this method should mimick the Hash#fetch method which throws the KeyError or the documentation should be changed to reflect the commited changes. Also there are no tests whatsoever regarding the error throwing when the optional default value is not passed:
https://github.com/rails/rails/blob/v5.0.0.1/actionpack/test/dispatch/header_test.rb#L100-L103

### Expected behavior
```
[1] pry(#<ApplicationController>)> request.headers.fetch("SAMPLE_HEADER")
KeyError: key not found: "SAMPLE_HEADER"
```

### Actual behavior
```
[1] pry(#<ApplicationController>)> request.headers.fetch("SAMPLE_HEADER")
NameError: SAMPLE_HEADER
```

### System configuration
**Rails version**: Rails 5.0.0.1

**Ruby version**: Ruby 2.3.1p112

**Comment by maclover7** [comment]
@mprostko thank you for reporting this! I think bce4ff70dd1ab88e5b573ad8c88408f100cf219e introduced a subtle breaking change here. Not sure what the recourse should be 😬 

r? @tenderlove
