### ISSUE TITLE
Action Cable NoMethodError - undefined method `fetch' for nil:NilClass

### ISSUE THREAD

**Issue by vincentlkl** [rails/rails#26275]
### Steps to reproduce
On my development environment I am not able to connect with Action Cable. When I perform 
`App.room.speak('testing 123')` on my chrome console.
it returns NoMethodError - undefined method `fetch' for nil:NilClass

Here are my setup
1. cable.yml
`
development:
  adapter: async
`

2. channels/room_channel.rb
`
  def subscribed
    stream_from "room_channel"
  end

  def speak
    ActionCable.server.broadcast 'room_channel', message: "123"
  end
`

3. javascripts/channels/room.coffee
`
App.room = App.cable.subscriptions.create "RoomChannel",
  connected: ->
    # Called when the subscription is ready for use on the server

  disconnected: ->
    # Called when the subscription has been terminated by the server

  received: (data) ->
    $("#messages").append data
    console.log data

  speak: (message) ->
    @perform 'speak', message: message
`

### Expected behavior
It should return message on my console

### Actual behavior
Currently it is not returning anything from my web console. However on my rails console it returns as
`
RoomChannel#speak({"message"=>"testing 123"})
[ActionCable] Broadcasting to room_channel: {:message=>"123"}
Could not execute command from {"command"=>"message", "identifier"=>"{\"channel\":\"RoomChannel\"}", "data"=>"{\"message\":\"testing 123\",\"action\":\"speak\"}"}) [NoMethodError - undefined method `fetch' for nil:NilClass]: /Users/vincent/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/actioncable-5.0.0/lib/action_cable/server/configuration.rb:24:in `pubsub_adapter' | /Users/vincent/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/actioncable-5.0.0/lib/action_cable/server/base.rb:72:in `block in pubsub' | /Users/vincent/.rbenv/versions/2.3.1/lib/ruby/2.3.0/monitor.rb:214:in `mon_synchronize' | /Users/vincent/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/actioncable-5.0.0/lib/action_cable/server/base.rb:72:in `pubsub' | /Users/vincent/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/actioncable-5.0.0/lib/action_cable/server/broadcasting.rb:43:in `broadcast'
`

### System configuration
**Rails version**: 5.0 

**Ruby version**: 2.3.1

**Comment by rafaelfranca** [comment]
It seems that the configuration is not set for your environment.  Can you please provide a sample application that reproduces the error?

**Comment by vincentlkl** [comment]
@rafaelfranca :
I have just pushed up my sample application at 
https://github.com/vincentlkl/rails5

I have tried to set the action_cable configuration at the actioncable.yml still I am not getting anything.

**Comment by maclover7** [comment]
@vincentlkl I think the issue may be that your config file is named `config/cabel.yml`, not `config/cable.yml`. Can you try and rename the file, and then see if that fixes the issue? 😬

**Comment by vincentlkl** [comment]
Thank you very much sorry for my careless mistake.

**Comment by joallard** [comment]
@vincentlkl Thanks for your careless mistake, I had forgotten to setup the config file and couldn't figure out the cryptic error message.
