### ISSUE TITLE
Rails 5 not responding with :js after redirect

### ISSUE THREAD

**Issue by ponchik** [rails/rails#26279]
On rails 4.2 I used to submit my form via ajax, and redirect to another action and it used to render a js.coffee template 
js request -> redirect -> js response

But now, on 5.0.0.1 it redirects to HTML
js request -> redirect -> html response
```
Started PATCH "/call_journals/111" for 127.0.0.1 at 2016-08-21 00:02:06 +0300
Processing by CallJournalsController#update as **JS**
.........

Redirected to http://localhost:3000/partners/new?call_journal_id=111
Completed 200 OK in 33ms (ActiveRecord: 3.1ms)

Started GET "/partners/new?call_journal_id=111" for 127.0.0.1 at 2016-08-21 00:02:06 +0300
Processing by PartnersController#new as **HTML**
  Parameters: {"call_journal_id"=>"111"}
```

If its not an issue, is there a way to make it work as before?

**Rails version**:
5.0.0.1
**Ruby version**:
2.3.0

**Comment by maclover7** [comment]
Can you create an executable test script using one of the templates [here](https://github.com/rails/rails/tree/master/guides/bug_report_templates), that would demonstrate the problem you are seeing?

I'm interested in seeing the code for your controller action, as some rendering behavior has changed for Rails 5.

**Comment by mkhairi** [comment]
Same behavior happen here using `remote: true` link or form.

```
  def new
    @post = Post.new
  end
```

```
def create
    @post = Post.new(post_params)
    if @post.save
      redirect_to comments_post_path(@post)
      #in rails 4.2 - responsed as js
      #in rails 5.0 - responsed as html
    else
    respond_to do |format|
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
 end

```

**Comment by ponchik** [comment]
I had been trying to reproduce the issue but without any luck. And then I had found a syntax error in my code. 

I'm really sorry for the disturbance, please close this issue!

**Comment by daneelliotthamilton** [comment]
@ponchik  What was the syntax error because I am getting the same type of error.

**Comment by mkhairi** [comment]
@daneelliotthamilton, try this

#respond remote true redirect
```
  def create
    @post = Post.new(post_params)
    respond_to do |format|
      if @post.save
        format.js { redirect_to post_comments_path(@post), turbolinks: false}
        #or 
        #redirect_to post_comments_path(@post), status: 303, turbolinks: false
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end
```

**Comment by imWildCat** [comment]
Similar issue with `request.format.json?`. I was testing my API with `PostMan`. However, all `json` requests were regarded as `*/*` requests.
