### ISSUE TITLE
Unable to add custom config like stated in Rails guides 

### ISSUE THREAD

**Issue by f-plante** [rails/rails#26280]
Rails 4.2 introduced the `config.x` namespace to add custom config variables.

As I'm upgrading to Rails 5, I noticed in the Rails 5 Guides that the `x`namespace is not needed anymore. So, instead of `config.x.app_title = "foo"` we can now write `config.app_title = "foo"`

It just do not work on a fresh Rails 5.0.0.1 app, and the Rails 5 release notes do not mention this change.

The changes in the guide are related to this commit : https://github.com/rails/rails/commit/476b14a32ddb89241027902e76e8455013972276

Am I missing something or the guides is wrong about this ?

**Comment by prathamesh-sonpatki** [comment]
cc @maclover7

**Comment by rafaelfranca** [comment]
`config.app_title = "foo"` should works in any version of Rails. This always worked but `config.app_title.bar = "foo"` only works in the `config.x` namespace.

**Comment by maclover7** [comment]
Hi @f-plante! I created a gist [here](https://gist.github.com/maclover7/980fbadd4550e7a3ad01ed30d12ae74b) to demonstrate the different scenarios in this situation, regarding nested and non-nested configuration. Please let us know if there is any better way to document this behavior.

**Comment by f-plante** [comment]
Hi @maclover7, thanks for your gist. My sample was misleading : I had in my config : 
```
config.x.blog.foo = "baz"
config.x.blog.bar = "baz"
```
Following, the guide, I thought that now I could write the same without the `x` namespace like : 
```
config.blog.foo = "baz"
config.blog.bar = "baz"
```
Now I get it than it is not possible, but IMO the guide is misleading and should be fixed. See the following change in https://github.com/rails/rails/commit/476b14a32ddb89241027902e76e8455013972276, where the `x` was dropped : 
```
config.payment_processing.schedule = :daily
config.payment_processing.retries  = 3
```
Again thanks four your time and your work.

**Comment by maclover7** [comment]
Opened up #26288 to try and fix the docs.

**Comment by maclover7** [comment]
Going to close this out since #26288 was merged in.
