### ISSUE TITLE
Class of variable does not persist correctly after redirect

### ISSUE THREAD

**Issue by miemeow** [rails/rails#26292]
Sorry, My English is bad

### Steps to reproduce
```rb
   ## foo_controller.rb
   class FooController < ApplicationController
    def index
      flash[:success] = "#{view_context.link_to 'Link', '#'}".html_safe
      puts flash[:success].class # ActiveSupport::SafeBuffer
      redirect_to bar_path
    end
   end
   ## ba_controller.rb
   def BarController < ApplicationController
     def index
       puts flash[:success].class # String
     end
   end
```

### Expected behavior
I think correctly shown link

### Actual behavior
HTML tags are escaped

### System configuration
**Rails version**: 5.0.0.1
**Ruby version**: 2.2.5p319 (2016-04-26 revision 54774) [x86_64-darwin16]

**Comment by prakashmurthy** [comment]
> Instead of marking the flash value as html_safe it is better to proper sanitize it when presenting in your view. I believe <%= sanitize(flash[:notice) %> would work fine.

From https://groups.google.com/forum/#!topic/rubyonrails-core/z52zgDgUmbs

**Comment by miemeow** [comment]
@prakashmurthy 
Thanks for your helpful comment!
Sorry, Investigation was insufficiency 😢
