### ISSUE TITLE
Allow logging to STDOUT globally

### ISSUE THREAD

**Issue by jessecurry** [rails/rails#26291]
### Steps to reproduce
1. Set `RAILS_LOG_TO_STDOUT=enabled` in your environment.
2. Start a Rails application using puma directly (e.g. `bundle exec puma -C config/puma.rb`)
3. Observe the console while interacting with the application.

### Expected behavior
Logging could be directed to STDOUT when the `RAILS_LOG_TO_STDOUT` environment variable is present.

### Actual behavior
Logging is not directed to STDOUT.

### Suggested Change
Suggesting that the following is copied to `config/environments/development.rb` or moved higher up the chain:

```
  if ENV["RAILS_LOG_TO_STDOUT"].present?
    logger           = ActiveSupport::Logger.new(STDOUT)
    logger.formatter = config.log_formatter
    config.logger = ActiveSupport::TaggedLogging.new(logger)
  end
```
### System configuration
**Rails version**:
5.0

**Ruby version**:
2.3.1

**Comment by maclover7** [comment]
Looks like we only check `ENV["RAILS_LOG_TO_STDOUT"]` in the [production environment](https://github.com/rails/rails/blob/master/railties/lib/rails/generators/rails/app/templates/config/environments/production.rb.tt#L88-L92), not in development 😬 

For reference, this feature was added to Rails via #23734

cc @schneems

**Comment by schneems** [comment]
By default in development mode we log to STDOUT in addition to the log file if you're using the `rails s` command. Right?

**Comment by jessecurry** [comment]
@schneems I'm using Foreman in development.

Logging to STDOUT does work out of the box if I use `rails s`, but I lose the ability to use the `.env` file (and dotenv feels kludgy).

**Comment by schneems** [comment]
I love dotenv FWIW. If you have `rails s` in your Procfile it would still work and that works with puma out of the box in Rails 5 now. I agree it seems odd that the env var only does something when in production mode. That being said it was quite the uphill battle to even get that in there. There's no real good place to set that for all environments and if there was I think we would hit quite a bit of resistance in getting it implemented.

**Comment by jessecurry** [comment]
Is `rails s` doing anything that would make it unsuitable for production?

I've always stayed away from `rails s` in my Procfile, but that's probably more a force of habit than anything else.

**Comment by schneems** [comment]
It's pretty much equivalent to `$ puma` now if you're using the puma gem and on Rails 5. You could also shell script your foreman with an if statement to use `rails s` locally.

**Comment by localhostdotdev** [comment]
got this today trying to have `rails runner` log to stdout, would be nice to have `RAILS_LOG_TO_STDOUT` work in development env too (maybe test env too?)

obviously adding this to the development.rb file solved it:

```ruby
  if ENV["RAILS_LOG_TO_STDOUT"].present?
    logger = ActiveSupport::Logger.new(STDOUT)
    logger.formatter = config.log_formatter
    config.logger = ActiveSupport::TaggedLogging.new(logger)
  end
```
