### ISSUE TITLE
Strange behavior with references(:foo) on a query

### ISSUE THREAD

**Issue by duffyjp** [rails/rails#26290]
### Steps to reproduce

Test case here:  https://gist.github.com/duffyjp/80e1d10a6a5f329baefc3a3865e058a0

```bash
$ ruby references_bug.rb 

  1) Failure:
BugTest#test_references [references_bug.rb:62]:
Expected #<Post id: 1> to not be equal to #<Post id: 1>.

1 runs, 3 assertions, 1 failures, 0 errors, 0 skips
```

### Expected behavior

This should fail spectacularly:
```ruby
Post.includes(:comments).references(:literally_anything).where("foo_comments.content = ?", 'bar').first
```

### Actual behavior
It magically generates valid SQL and works fine.

```
SQL (0.1ms)  SELECT "posts"."id" AS t0_r0, "foo_comments"."id" AS t1_r0, "foo_comments"."post_id" AS t1_r1, "foo_comments"."content" AS t1_r2 FROM "posts" LEFT OUTER JOIN "foo_comments" ON "foo_comments"."post_id" = "posts"."id" WHERE (foo_comments.content = 'bar') AND "posts"."id" = 1 ORDER BY "posts"."id" ASC
```

### System configuration
**Rails version**: 5.0.0 / 5.0.0.1

**Ruby version**: 2.3.1

I'm really scratching my head on this one.  I verified the result on two machines...

**Comment by prakashmurthy** [comment]
Confirming the behavior on Rails 4/5. 

My **guess** is that the `post.comments << Comment.create!(content: 'bar')` line caches the values for the relationship, and that makes the correct reference table name available to the later query even though an incorrect table name is specified.

**Comment by matthewd** [comment]
> `# My personal opinion is this *should* work, but the docs say references takes table_name`

.. and that's pretty much why `references` does what it does.

Namely: while it's *supposed* to be a specific list of things that are referenced, so we can intelligently pick over `includes` and determine which ones need to be joined... it's actually treated as a boolean flag.

I would hope to make `references` Actually Intelligent (and thus start emitting deprecations and eventually errors for incorrect parameters) at the same time we get association names working in `where` (see https://github.com/rails/rails/pull/13555). Until then, it doesn't seem worth the inconvenience of making everyone revisit their queries; if you specifically want to join some but not others, you can split them between `preload` and `eager_load` yourself.
