### ISSUE TITLE
Typo / wrong command

### ISSUE THREAD

**Issue by krilliaz** [rails/rails#26315]
Hey guys, I dont know where I have to write it so, I guess i'll just dump it here.

I was following the guide: "Get Started with Rails" and there is a command 

**$ bin/rails db:migrate**

And this command doesn't work, because it has to be 
_rake db:migrate_

So I hope you guys can change it for the others that has to read the guide.

**Comment by kaspth** [comment]
That command works on Rails 5. Thanks!
