### ISSUE TITLE
ActionView helper sanitize adds extra \n characters, which affects simple_format's output

### ISSUE THREAD

**Issue by CarlosCD** [rails/rails#26316]
This a consequence of #22799, and its effect on the simple_format helper (I added this comment on that issue as well).

A call to simple_format, 'sanitizes' by default, and sanitize injects \n characters, which become `<br />` and would mess up the HTML output:

```
ActionController::Base.helpers.simple_format("<ul>Test Answer.<li>Item 1</li></ul>")
=> "<p><ul>Test Answer.<li>Item 1</li>\n<br /></ul></p>"
```

This gets easily out of hand as the amount of HTML you pass to simple_format increases. A test would be something like:

```
ActionController::Base.helpers.simple_format("<ul>Test Answer.<li>Item 1</li><li>Item 2</li></ul>")
=> "<p><ul>Test Answer.<li>Item 1</li>\n<br /><li>Item 2</li>\n<br /></ul></p>"
```

The `<p>`, `</p>` are the only expected changes for this HTML fragment.

---

<ul>Test Answer.<li>Item 1</li><li>Item 2</li></ul>

---

versus:

---

<p><ul>Test Answer.<li>Item 1</li><br /><li>Item 2</li><br /></ul></p>

---

A particular use is a CMS-style application in which you get HTML input from an admin form, store it, to later display it using simple_format. Even if the user is an admin, you would like to sanitize the HTML, for security reasons, but also predict which HTML is finally rendered.

A fix could to modify nokogiri SaveOptions to use different output than what Loofah uses by default, something like:

```
Nokogiri::XML::Node::SaveOptions::DEFAULT_HTML ^ Nokogiri::XML::Node::SaveOptions::FORMAT
```

A bypass of the issue is to not to sanitize when calling simple format (`sanitize: false`), but then you would need to take care of the security issues on your own.
### System configuration

**Rails version**: 4.2.7, probably since around 4.2, when the loofah scrubber (and its use of nokogiri) was added.

**Ruby version**: Tested on 1.9.3-p448 and 2.3.1, probably all versions, at least since 1.9.3

**Comment by louiswdavis** [comment]
I am still having this problem:

```
test = "<div>Text 1<br><br>Text 2<br><br></div><ul><li>Item 1</li><li>Item 2</li></ul>"

ActionController::Base.helpers.simple_format(test)
"<p><div>Text 1<br><br>Text 2<br><br>\n<br /></div><ul>\n<br /><li>Item 1</li>\n<br /><li>Item 2</li>\n<br /></ul></p>"
```

And as previously mentioned those "\n" characters are transformed into <br> tags creating extra line breaks

**System configuration**

Rails version: 7.0.1
Ruby version: 3.1.3
