### ISSUE TITLE
ThroughReflection call table_name raise errors in 5.0

### ISSUE THREAD

**Issue by qinmingyuan** [rails/rails#26324]
### Steps to reproduce
```ruby
class Order < ApplicationRecord
  has_many :order_items, dependent: :destroy
  has_many :inquiries, through: :order_items, dependent: :destroy
end
```
when I call `Order.reflections['inquiries'].table_name`, it raise the errors as bellow:
```ruby
NoMethodError: undefined method `class_name' for nil:NilClass
Did you mean?  class_eval
from /Users/qin/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activerecord-5.0.0/lib/active_record/reflection.rb:974:in `derive_class_name'
```

### Expected behavior
It should return the `reflections['inquiries']`'s table name `inquiries`

### System configuration
**Rails version**:
5.0
**Ruby version**:
2.3.1

**Comment by alexcameron89** [comment]
I created an executable gist [here](https://gist.github.com/alexcameron89/775f4536e494abc9093691c6b7ebd17d) to attempt to emulate this issue, and I could not reproduce it on `master` or `v5.0.0`. 

@qinmingyuan Can you provide additional information to the reproduce the problem or create an executable test script using one of the templates [here](https://github.com/rails/rails/tree/master/guides/bug_report_templates), that would demonstrate the problem you are seeing?

**Comment by qinmingyuan** [comment]
I'm very sorry,  I checked our project again. and I found the definition: `has_many :inquiries, through: :order_items, dependent: :destroy` is not correct，so it caused this issue.

It's details 
```ruby
Order.first.inquiries
Order Load (2.0ms)  SELECT  `orders`.* FROM `orders` ORDER BY `orders`.`created_at` DESC LIMIT 1
ActiveRecord::HasManyThroughSourceAssociationNotFoundError: Could not find the source association(s) "inquiry" or :inquiries in model OrderItem. Try 'has_many :inquiries, :through => :order_items, :source => <name>'. Is it one of order, chemical, quotation_item, payment, or shippings?
```

Thank you @alexcameron89 for your nice help.

I think we can close the issue

**Comment by alexcameron89** [comment]
No problem, and I'm glad you solved your issue! 👍
