### ISSUE TITLE
Template is missing

### ISSUE THREAD

**Issue by iFurniture** [rails/rails#26321]
Hi everyone, i'm gotting this error from my web page, when i try to go to "localhost:3000/suscribir" i got this error:

`Missing template subscribe/create, application/create with {:locale=>[:es, :en], :formats=>[:html], :variants=>[], :handlers=>[:erb, :builder, :raw, :ruby, :coffee, :jbuilder]}.`

this is my routes.rb file...

```
  post '/suscribir' => 'subscribe#create'
  mount Refinery::Core::Engine, at: Refinery::Core.mounted_path
```

this is the subscribe controller...

```
class SubscribeController < ApplicationController
  def create
    logger.info "suscripcion #{params.inspect}"
    user = user_params(params)
    MailchimpWrapper.subscribe(user, params[:group_name], params[:group])
    redirect_to '/gracias'
  rescue Mailchimp::Error => e
    logger.error "ERROR mailchimp #{e.message} #{params.inspect}"
  end

  private

  def user_params(params)
    user = {
      email: params[:email].try(:downcase),
      first_name: params[:first_name].try(:titleize),
      last_name: params[:last_name].try(:titleize),
      city: params[:city].try(:titleize),
      phone: params[:phone],
      comment: params[:comment].try(:titleize)
    }
    user
  end
end
```

i'll be watching for your help, thanks.

**Comment by rafaelfranca** [comment]
Please use the mailing list or StackOverflow for questions/help, where a wider community will be able to help you. We reserve the issues tracker for issues only.
