### ISSUE TITLE
as_json dosen't support parameterized methods

### ISSUE THREAD

**Issue by vikramjadon921995** [rails/rails#26336]
While passing methods in 'as_json'/'to_json' to create json response of an object, we cannot pass parameters in methods. What is the reason behind it and how can it be solved? 

For example, 
@posts.to_json(
         :only => [:title, :body, :created_at, :tags, :category],
         :methods => [:likes_count, :comments_count])
      }

Here we cannot pass methods with arguments.

**Comment by matthewd** [comment]
Please use the mailing list or StackOverflow for questions/help, where a wider community will be able to help you. We reserve the issues tracker for issues only.

**Comment by vikramjadon921995** [comment]
@matthewd Shouldn't parameterized methods be allowed in 'to_json'?. I posted it here as an issue.  I have updated my previous comment so that it dosen't look like a question anymore.

**Comment by matthewd** [comment]
We don't take feature requests in the issue tracker either.

The short answer is that there's no practical way to support this with less syntax than would be involved if you just merged the extra items into the hash.
