### ISSUE TITLE
Attribute default value cannot be saved when creating a new record

### ISSUE THREAD

**Issue by Sen-Zhang** [rails/rails#26345]
### Steps to reproduce
```ruby
begin
  require "bundler/inline"
rescue LoadError => e
  $stderr.puts "Bundler version 1.10 or later is required. Please update your Bundler"
  raise e
end

gemfile(true) do
  source "https://rubygems.org"
  gem "activerecord", "4.2.7"
  gem "sqlite3"
end

require "active_record"
require "minitest/autorun"
require "logger"

Minitest::Test = MiniTest::Unit::TestCase unless defined?(Minitest::Test)

ActiveRecord::Base.establish_connection(adapter: "sqlite3", database: ":memory:")
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :users, force: true do |t|
    t.string "locale", limit: 10, null: false
  end
end

class User < ActiveRecord::Base
  attribute :locale, ActiveRecord::Type::String.new, default: "en"
end

class BugTest < Minitest::Test
  def test_save_with_attribute_default
    user = User.new(locale: "en")
    
    assert user.save
  end
end
```

### Expected behavior
Save user successfully.

### Actual behavior
`locale` is not saved.
#### Running:

SQL (0.1ms)  INSERT INTO "users" DEFAULT VALUES
rollback transaction
E

Finished in 0.005314s, 188.1693 runs/s, 0.0000 assertions/s.

  1) Error:
BugTest#test_save_with_attribute_default:
ActiveRecord::StatementInvalid: SQLite3::ConstraintException: NOT NULL constraint failed: users.locale: INSERT INTO "users" DEFAULT VALUES

### System configuration
**Rails version**:
`4.2.7`
**Ruby version**:
`2.3.1`

### Notes
This issue has been fixed in rails 5.0.0+

**Comment by sgrif** [comment]
`attribute` is not part of the public API in 4.2.
