### ISSUE TITLE
In production mode only, incompatible character encodings: ASCII-8BIT and UTF-8 on accented characters

### ISSUE THREAD

**Issue by cenotaph** [rails/rails#26348]
When displaying content with accented characters such as ä or å, ActionView::Template::Error is raised with: ActionView::Template::Error (incompatible character encodings: ASCII-8BIT and UTF-8)

This ONLY happens in production mode and when behind a reverse proxy. Have tested with Passenger, Unicorn and Puma behind both nginx and apache.  Running the app in production mode on port 3000 and browsing to that works perfectly fine.

ALL content is in utf-8. The database (postgres using pg 0.18.4), nginx's charset setting, all of the encoding options in environment.rb, and the HTTP headers. Nothing should be in ASCII-8BIT.

I am using ruby 2.3.1 and rails 5.0.0.1.

If anyone has an idea about this, or a workaround (short of appending .force-encoding('ASCII-8BIT') to every line in every view, please advise. I am extremely frustrated with it and beating my head off the table at this point.

Building a service in Finland, so accented characters are absolutely necessary here!

**Comment by alexcameron89** [comment]
This may be related to #26326, where after save, it was returning a string encoded with ASCII-8BIT rather than UTF-8 due to the PG gem. @sgrif?

**Comment by vipulnsward** [comment]
https://github.com/sgrif/rails/commit/a710dbd91e1b81a7e3d3aaf1b537fed3c29359b4
was related to arrays of strings.
@cenotaph can you confirm if your issue is related/or how your data is being stored?

**Comment by cenotaph** [comment]
These are just regular string/text columns, not arrays. And running rails from master doesn't fix it ... what gets me is that it only happens from behind the reverse proxy.

I'm going to try stepping down to Rails 4 (if it can be done without too much hassle) to see if it occurs there. I have tried it with 5.0.0, 5.0.0.1 and master now and no dice.

**Comment by sgrif** [comment]
Unless we can get a [reproduction script using our template](https://github.com/rails/rails/blob/master/guides/bug_report_templates/active_record_master.rb) or at least a stack trace and log output, there's not much I can do to help

**Comment by sgrif** [comment]
Alternatively, we could just convince all of Finland to stop using accented characters :trollface:

**Comment by cenotaph** [comment]
I wish it was that easy. :)

So, I 'downgraded' to Rails 4.2.7.1 and it still happens, so maybe I have falsely accused Rails as being the culprit.

**Comment by sgrif** [comment]
Unfortunately without any way to reproduce the issue I cannot keep this issue open. If you do determine that Rails *is* in fact the culprit, and are able to give us steps to reproduce, please ping me and I will reopen this issue. Thanks for your understanding. :)

**Comment by Zhigun** [comment]
You can reproduce this by updating any ActiveRecord object which has array column in db with 'russian' letters.
Example:
```
@instructor = Instructor.first
  Instructor Load (2.6ms)  SELECT  "instructors".* FROM "instructors" ORDER BY "instructors"."id" ASC LIMIT $1  [["LIMIT", 1]]
=> #<Instructor:0x007ff3bc26a298
 id: 1,
 user_id: 1,
 description: "Dolorum molestias et. Doloremque itaque quidem rerum et. Quo nesciunt dolore sunt fuga. Omnis voluptatum sed est eum quidem tempore. Eos veritatis voluptatem quia incidunt atque architecto.",
 state: "verified",
 created_at: Tue, 29 Nov 2016 11:47:42 UTC +00:00,
 updated_at: Tue, 29 Nov 2016 14:51:41 UTC +00:00,
 title: "Recusandae perspiciatis alias maxime quia soluta velit amet.",
 tags: ["ыыы", "фыфвфыв"]>
[50] pry(#<InstructorsController>)> @instructor.tags = ['tag', 'tag2']
=> ["tag", "tag2"]
[51] pry(#<InstructorsController>)> @instructor.save
   (0.5ms)  BEGIN
  SQL (2.6ms)  UPDATE "instructors" SET "updated_at" = $1, "tags" = $2 WHERE "instructors"."id" = $3  [["updated_at", 2016-11-29 15:12:10 UTC], ["tags", "{tag,tag2}"], ["id", 1]]
  User Load (1.3ms)  SELECT  "users".* FROM "users" WHERE "users"."id" = $1 LIMIT $2  [["id", 1], ["LIMIT", 1]]
  SQL (1.1ms)  UPDATE "users" SET "updated_at" = '2016-11-29 15:12:10.771629' WHERE "users"."id" = $1  [["id", 1]]
   (0.5ms)  COMMIT
=> true
[52] pry(#<InstructorsController>)> @instructor
=> #<Instructor:0x007ff3bc26a298
 id: 1,
 user_id: 1,
 description: "Dolorum molestias et. Doloremque itaque quidem rerum et. Quo nesciunt dolore sunt fuga. Omnis voluptatum sed est eum quidem tempore. Eos veritatis voluptatem quia incidunt atque architecto.",
 state: "verified",
 created_at: Tue, 29 Nov 2016 11:47:42 UTC +00:00,
 updated_at: Tue, 29 Nov 2016 15:12:10 UTC +00:00,
 title: "Recusandae perspiciatis alias maxime quia soluta velit amet.",
 tags: ["tag", "tag2"]>
[53] pry(#<InstructorsController>)> @instructor.tags << 'Привет'
=> ["tag", "tag2", "Привет"]
[54] pry(#<InstructorsController>)> @instructor.save
   (0.3ms)  BEGIN
  SQL (0.6ms)  UPDATE "instructors" SET "updated_at" = $1, "tags" = $2 WHERE "instructors"."id" = $3  [["updated_at", 2016-11-29 15:12:39 UTC], ["tags", "{tag,tag2,\xD0\x9F\xD1\x80\xD0\xB8\xD0\xB2\xD0\xB5\xD1\x82}"], ["id", 1]]
  SQL (0.8ms)  UPDATE "users" SET "updated_at" = '2016-11-29 15:12:39.688077' WHERE "users"."id" = $1  [["id", 1]]
   (4.2ms)  COMMIT
=> true
[55] pry(#<InstructorsController>)> @instructor
=> #<Instructor:0x007ff3bc26a298
 id: 1,
 user_id: 1,
 description: "Dolorum molestias et. Doloremque itaque quidem rerum et. Quo nesciunt dolore sunt fuga. Omnis voluptatum sed est eum quidem tempore. Eos veritatis voluptatem quia incidunt atque architecto.",
 state: "verified",
 created_at: Tue, 29 Nov 2016 11:47:42 UTC +00:00,
 updated_at: Tue, 29 Nov 2016 15:12:39 UTC +00:00,
 title: "Recusandae perspiciatis alias maxime quia soluta velit amet.",
 tags: ["tag", "tag2", "\xD0\x9F\xD1\x80\xD0\xB8\xD0\xB2\xD0\xB5\xD1\x82"]>

```

**Comment by sgrif** [comment]
Please create [a reproduction script using our template](https://github.com/rails/rails/blob/master/guides/bug_report_templates/active_record_master.rb) and open a new issue.

**Comment by Zhigun** [comment]
Ok, thanks.
Done
https://github.com/rails/rails/issues/27210

**Comment by jormon** [comment]
@cenotaph -- just in case you are still struggling, I wanted to let you know I ran into a very similar situation.  It happened when I was writing strings that were from params in a UTF-8 HAML template.  In particular, the param I was pulling originally came from the path using a route matcher like this: 

    get "/in/:geo", to: "in#geo""

If I put params[:geo] anywhere in the template, and visited a path like "/in/tromsoø`, the app would crash because for one version (4.2.9) was improperly decoding things in params from the URL string as ASCII-8BIT instead of UTF-8.  Like for you, for some reason, this only happened when behind a reverse proxy.

Just a pointer in case you're still stuck with this...
