### ISSUE TITLE
to_json should support parameterized methods

### ISSUE THREAD

**Issue by vikramjadon921995** [rails/rails#26341]
### Expected behavior
to_json should should support parameterized methods. 
I am assuming something like this 
@company.to_json(methods: :is_watchlisted(user))

### Actual behavior
Currently this is throwing syntax error. 
SyntaxError: unexpected ')', expecting end-of-input
Company.first.to_json(methods: :is_watchlisted?(User.first))

**Comment by sgrif** [comment]
It's giving you a syntax error because the code you posted isn't valid Ruby.
