### ISSUE TITLE
Some query returns wrong result after upgrade ActiveRecord from 4.2.6 to 4.2.7.1

### ISSUE THREAD

**Issue by Noeyfan** [rails/rails#26353]
### Steps to reproduce
Assume there exist a database contain tableA.

Here is the model:<rails-root/app/model>
```
TableA < ActiveRecord::Base
   self.table_name = "Foo.table_A"
```

Here is the controller: <rails-root/app/controller>
```
def run_query(id)
   return TableA.where("id = ?", id)
                          .group(:date, :money, :amount)
                          .sum(:amount)
```

### Expected behavior
This should generate query like (before 4.2.7):
```
SELECT SUM("FOO"."TABLE_A"."AMOUNT") AS sum_amount, date AS date, money AS money, amount AS amount
WHERE (id=123)
GROUP BY "FOO"."TABLE_A"."DATE", "FOO"."TABLE_A"."MONEY"."FOO"."TABLE_A"."AMOUNT"
```

Result get by run this query in DB:
```
"AMOUNT" "DATE" "MONEY" "AMOUNT"
100, 30-APR-12, 20, 100
```

And result returned by ActiveRecord:
```
{[30-APR-12, 20, 100] => 100}
```

### Actual behavior
This actual generate query like:
```
SELECT SUM("FOO"."TABLE_A"."AMOUNT") AS sum_amount, "FOO"."TABLE_A"."DATE" AS foo_table_a, "FOO"."TABLE_A"."MONEY" AS foo_table_a, "FOO"."TABLE_A"."AMOUNT" AS foo_table_a
WHERE (id=123)
GROUP BY "FOO"."TABLE_A"."DATE", "FOO"."TABLE_A"."MONEY"."FOO"."TABLE_A"."AMOUNT"
```
Result get by run this query in DB:
```
"AMOUNT" "FOO_TABLE_A" "FOO_TABLE_A1" "FOO_TABLE_A2"
100, 30-APR-12, 20, 100
```

And result returned by ActiveRecord:
```
{[100, 100, 100] => 100}
```

### Summary of problem
All the "SELECT . AS" mapped to the same value "foo_table_a" and the value returned from ActiveRecord is incorrect. Since the group() interpretation changes in 4.2.7 and my code works in 4.2.6, wondering if this cause the problem. Any thoughts might be helpful, thanks!

### System configuration
**Rails version**:
4.2.7.1
**Ruby version**:
1.9

**Comment by prathamesh-sonpatki** [comment]
Can you use https://github.com/rails/rails/blob/master/guides/bug_report_templates/active_record_gem.rb and provide a bug report template so that we rule out any third party gem causing this issue?

Thanks.
