### ISSUE TITLE
form_for helper does not respect the :only option in my routes.rb file

### ISSUE THREAD

**Issue by hadiS** [rails/rails#26355]
### Steps to reproduce

Hi. In my Rails App I have the following routes:

```ruby
resources :seminars, only: :show

 scope '/admin' do
   resources :seminars, except: :show
 end
```

The form_for helper method for updating a record generates the wrong url:

```ruby
<form method="post" accept-charset="UTF-8" action="/seminars/2" enctype="multipart/form-data" id="edit_seminar_2" class="edit_seminar">
```
It doesn't respect the 'only' option in my routes file. I am not sure if I am doing something wrong or if it is a bug.

### Expected behavior
```ruby
<form method="post" accept-charset="UTF-8" action="admin/seminars/2" enctype="multipart/form-data" id="edit_seminar_2" class="edit_seminar">
```

### Actual behavior
```ruby
<form method="post" accept-charset="UTF-8" action="/seminars/2" enctype="multipart/form-data" id="edit_seminar_2" class="edit_seminar">
```
When submitting the form I get a routing error:

No route matches [PATCH] "/seminars/2"
### System configuration
**Rails version**: 5.0.0.1

**Ruby version**: 2.3.1

**Comment by yahorzhylinski** [comment]
What params do you send to form_for?

**Comment by hadiS** [comment]
Just the default params:

```ruby
<%= form_for @seminar do |f| %>
```

**Comment by yahorzhylinski** [comment]
You should a scope to form_for if you want /admin/... like route
http://stackoverflow.com/questions/3371701/routing-scope-problem-with-form-for-partial
http://stackoverflow.com/questions/3853531/rails-routes-namespaces-and-form-for
http://stackoverflow.com/questions/3741979/form-for-and-scopes-rails-3

**Comment by hadiS** [comment]
I am not sure if I can follow. So basically I should prefix my `SeminarsController` with `Admin::` and using 

```ruby
form_for [:admin, @seminar] 
```

in order to get the correct route in form_for? I would prefer not to prefix my controller with `Admin`. I would like to route `admin/seminars` to SeminarsController without the `Admin::` prefix. 

Why wouldn't `form_for` respect the :only option in my routes and generate the correct url?

**Comment by kaspth** [comment]
Yes, prefixing your form for call is the correct solution. Action View generates the routes based on what you give it, not what your routes file says. Say you also had a seminars route that wasn't in the admin namespace, there's no way for us to discern which route we should pick. Thanks!
