### ISSUE TITLE
Code after redirect_to gets executed

### ISSUE THREAD

**Issue by ChakreshwarSharma** [rails/rails#26363]
### Steps to reproduce
1. Write redirect_to "some_path" in any function.
2. Then write some code, flash messages after redirect_to .
3. Statements will gets executed

### Expected behavior
Any code after redirect_to should not gets executed.

### Actual behavior
It executes all the statements/codes after redirect to.

### System configuration
**Rails version**:
4.2.0, 5.0.0

**Ruby version**:
2.0, 2.3.1

**Comment by vipulnsward** [comment]
redirect_to is not meant to stop execution and return immediately, it sets redirection status/rendering,etc. and continues with further execution.

You can achieve what you are looking for with- 

```
redirect_to(post_url(@post), alert: "Watch it, mister!") and return
```

**Comment by ChakreshwarSharma** [comment]
@vipulnsward : What about if I save an object after redirect to.
If it is not for stopping the execution , then it should be rename to nextlocation or something similar to this instead of redirect_to

**Comment by ChakreshwarSharma** [comment]
@vipulnsward : Ruby guide itself suggest that redirect_to should be the last statement ,there are lots of exmaples in the ruby guide like http://guides.rubyonrails.org/action_controller_overview.html#parameters, http://guides.rubyonrails.org/layouts_and_rendering.html#using-redirect-to

I haven't seen any example in which the rails guides has writen the code after redirect_to
The naming convention should be correct which properly explains the purpose & should not create any confusion .

**Comment by vipulnsward** [comment]
Sure, I will add a note about it. 
The `redirection` here is in context of a "web request" and not the ruby method it is running in.

**Comment by vipulnsward** [comment]
Btw, I know it can be confusing, I have myself assumed it will return and stop execution many times.

**Comment by santosh-btc** [comment]
@vipulnsward - I think it is a valid issue & should be fixed

**Comment by ChakreshwarSharma** [comment]
@vipulnsward : If it doesn't stop the execution , then rails guides should have some examples for it.
So, this issue should be reopened.

**Comment by vipulnsward** [comment]
Fixed on https://github.com/rails/docrails/commit/b4dac34508dfa492da69be25321c8f31d5f77b8f

Should be available on http://edgeguides.rubyonrails.org/ shortly.

**Comment by ChakreshwarSharma** [comment]
@vipulnsward : Please share the link where you have fixed it
