### ISSUE TITLE
rake migration accepts none existed datatype and 'string' column name.

### ISSUE THREAD

**Issue by nsantiago2719** [rails/rails#26385]
I have accidentally switched the paramters of creating a column in migration. At running db:migrate it accepts the migration. But when I want to remove the column named 'string' it already returns an error.

Rails version 5.0.0.1
Ruby ruby 2.3.1p112 (2016-04-26 revision 54768) [x86_64-linux]

This is a screen shot of the log.

![screenshot from 2016-09-04 11-37-50](https://cloud.githubusercontent.com/assets/6946531/18228905/46930f00-7294-11e6-85a7-ac119346ebd9.png)

**Comment by nsantiago2719** [comment]
I forgot. This is the schema.rb file.

![screenshot from 2016-09-04 11-41-50](https://cloud.githubusercontent.com/assets/6946531/18228912/9d293b8c-7294-11e6-8462-0213f9f211aa.png)

**Comment by nsantiago2719** [comment]
I forgot, this is the schema.rb file for refernce.
![screenshot from 2016-09-04 11-43-57](https://cloud.githubusercontent.com/assets/6946531/18228929/e43244a6-7294-11e6-904b-cd5008f66a31.png)

**Comment by prathamesh-sonpatki** [comment]
You can just drop the database and start over again. 

Also, please use stackoverflow or other medium for posting questions where a wider community can help you, we reserve the issue tracker for bug reports only, thanks.

**Comment by nsantiago2719** [comment]
But isn't this a bug that it accepts a string column name?

**Comment by prathamesh-sonpatki** [comment]
Actually the error message is happening because sqlite is first copying the table before altering it and it can't find type of the column with name "string".  

I don't think we can check for all valid identifiers, but surely can provide some helpful error messages. I will reopen for now to get feedback from other members.

**Comment by prathamesh-sonpatki** [comment]
I investigated a bit and found out that this happens only in case of sqlite adapter.

PostgreSQL and MySQL both throw errors ~ https://gist.github.com/prathamesh-sonpatki/ed2213f3d0d0755dcac62a4b0ee4245e

This is the schema when sqlite is used - https://gist.github.com/prathamesh-sonpatki/fd15b7320762f26260ec3ebf1c1825ac

I will investigate why sqlite is generating wrong schema.

r? @prathamesh-sonpatki

**Comment by prathamesh-sonpatki** [comment]
This issue is already fixed by https://github.com/rails/rails/pull/26089. It will be available in next 5.0.1 release. Thanks @nsantiago2719
