### ISSUE TITLE
rails can't run on Kali Linux 

### ISSUE THREAD

**Issue by HughLi** [rails/rails#26388]
### System configuration
**Rails version**:5.0.0.1

**Ruby version**:2.3.0

### when run $ rails server
hugh@Victory:~/desktop/blog$ rails server
=> Booting Thin
=> Rails 5.0.0.1 application starting in development on http://localhost:3000
=> Run `rails server -h` for more startup options
Exiting
/var/lib/gems/2.3.0/gems/actionpack-5.0.0.1/lib/action_dispatch/middleware/session/abstract_store.rb:90:in `<module:Session>': uninitialized constant Rack::Session::Abstract::Persisted (NameError)
	from /var/lib/gems/2.3.0/gems/actionpack-5.0.0.1/lib/action_dispatch/middleware/session/abstract_store.rb:8:in `<module:ActionDispatch>'
	from /var/lib/gems/2.3.0/gems/actionpack-5.0.0.1/lib/action_dispatch/middleware/session/abstract_store.rb:7:in `<top (required)>'
	from /var/lib/gems/2.3.0/gems/actionpack-5.0.0.1/lib/action_dispatch/middleware/session/cookie_store.rb:2:in `<top (required)>'
	from /var/lib/gems/2.3.0/gems/railties-5.0.0.1/lib/rails/application/configuration.rb:181:in `const_get'
	from /var/lib/gems/2.3.0/gems/railties-5.0.0.1/lib/rails/application/configuration.rb:181:in `session_store'
	from /var/lib/gems/2.3.0/gems/railties-5.0.0.1/lib/rails/application/default_middleware_stack.rb:58:in `block in build_stack'
	from /var/lib/gems/2.3.0/gems/railties-5.0.0.1/lib/rails/application/default_middleware_stack.rb:13:in `tap'
	from /var/lib/gems/2.3.0/gems/railties-5.0.0.1/lib/rails/application/default_middleware_stack.rb:13:in `build_stack'
	from /var/lib/gems/2.3.0/gems/railties-5.0.0.1/lib/rails/application.rb:504:in `default_middleware_stack'
	from /var/lib/gems/2.3.0/gems/railties-5.0.0.1/lib/rails/engine.rb:506:in `block in app'
	from /var/lib/gems/2.3.0/gems/railties-5.0.0.1/lib/rails/engine.rb:504:in `synchronize'
	from /var/lib/gems/2.3.0/gems/railties-5.0.0.1/lib/rails/engine.rb:504:in `app'
	from /var/lib/gems/2.3.0/gems/railties-5.0.0.1/lib/rails/application/finisher.rb:37:in `block in <module:Finisher>'
	from /var/lib/gems/2.3.0/gems/railties-5.0.0.1/lib/rails/initializable.rb:30:in `instance_exec'
	from /var/lib/gems/2.3.0/gems/railties-5.0.0.1/lib/rails/initializable.rb:30:in `run'
	from /var/lib/gems/2.3.0/gems/railties-5.0.0.1/lib/rails/initializable.rb:55:in `block in run_initializers'
	from /usr/lib/ruby/2.3.0/tsort.rb:228:in `block in tsort_each'
	from /usr/lib/ruby/2.3.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
	from /usr/lib/ruby/2.3.0/tsort.rb:431:in `each_strongly_connected_component_from'
	from /usr/lib/ruby/2.3.0/tsort.rb:349:in `block in each_strongly_connected_component'
	from /usr/lib/ruby/2.3.0/tsort.rb:347:in `each'
	from /usr/lib/ruby/2.3.0/tsort.rb:347:in `call'
	from /usr/lib/ruby/2.3.0/tsort.rb:347:in `each_strongly_connected_component'
	from /usr/lib/ruby/2.3.0/tsort.rb:226:in `tsort_each'
	from /usr/lib/ruby/2.3.0/tsort.rb:205:in `tsort_each'
	from /var/lib/gems/2.3.0/gems/railties-5.0.0.1/lib/rails/initializable.rb:54:in `run_initializers'
	from /var/lib/gems/2.3.0/gems/railties-5.0.0.1/lib/rails/application.rb:352:in `initialize!'
	from /home/hugh/desktop/blog/config/environment.rb:5:in `<top (required)>'
	from /home/hugh/desktop/blog/config.ru:3:in `require_relative'
	from /home/hugh/desktop/blog/config.ru:3:in `block in <main>'
	from /usr/lib/ruby/vendor_ruby/rack/builder.rb:55:in `instance_eval'
	from /usr/lib/ruby/vendor_ruby/rack/builder.rb:55:in `initialize'
	from /home/hugh/desktop/blog/config.ru:in `new'
	from /home/hugh/desktop/blog/config.ru:in `<main>'
	from /usr/lib/ruby/vendor_ruby/rack/builder.rb:49:in `eval'
	from /usr/lib/ruby/vendor_ruby/rack/builder.rb:49:in `new_from_string'
	from /usr/lib/ruby/vendor_ruby/rack/builder.rb:40:in `parse_file'
	from /var/lib/gems/2.3.0/gems/rack-2.0.1/lib/rack/server.rb:318:in `build_app_and_options_from_config'
	from /var/lib/gems/2.3.0/gems/rack-2.0.1/lib/rack/server.rb:218:in `app'
	from /var/lib/gems/2.3.0/gems/railties-5.0.0.1/lib/rails/commands/server.rb:59:in `app'
	from /var/lib/gems/2.3.0/gems/rack-2.0.1/lib/rack/server.rb:353:in `wrapped_app'
	from /var/lib/gems/2.3.0/gems/railties-5.0.0.1/lib/rails/commands/server.rb:124:in `log_to_stdout'
	from /var/lib/gems/2.3.0/gems/railties-5.0.0.1/lib/rails/commands/server.rb:77:in `start'
	from /var/lib/gems/2.3.0/gems/railties-5.0.0.1/lib/rails/commands/commands_tasks.rb:90:in `block in server'
	from /var/lib/gems/2.3.0/gems/railties-5.0.0.1/lib/rails/commands/commands_tasks.rb:85:in `tap'
	from /var/lib/gems/2.3.0/gems/railties-5.0.0.1/lib/rails/commands/commands_tasks.rb:85:in `server'
	from /var/lib/gems/2.3.0/gems/railties-5.0.0.1/lib/rails/commands/commands_tasks.rb:49:in `run_command!'
	from /var/lib/gems/2.3.0/gems/railties-5.0.0.1/lib/rails/commands.rb:18:in `<top (required)>'
	from /home/hugh/desktop/blog/bin/rails:9:in `require'
	from /home/hugh/desktop/blog/bin/rails:9:in `<top (required)>'
	from /var/lib/gems/2.3.0/gems/spring-1.7.2/lib/spring/client/rails.rb:28:in `load'
	from /var/lib/gems/2.3.0/gems/spring-1.7.2/lib/spring/client/rails.rb:28:in `call'
	from /var/lib/gems/2.3.0/gems/spring-1.7.2/lib/spring/client/command.rb:7:in `call'
	from /var/lib/gems/2.3.0/gems/spring-1.7.2/lib/spring/client.rb:30:in `run'
	from /var/lib/gems/2.3.0/gems/spring-1.7.2/bin/spring:49:in `<top (required)>'
	from /var/lib/gems/2.3.0/gems/spring-1.7.2/lib/spring/binstub.rb:11:in `load'
	from /var/lib/gems/2.3.0/gems/spring-1.7.2/lib/spring/binstub.rb:11:in `<top (required)>'
	from /usr/local/lib/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/local/lib/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /home/hugh/desktop/blog/bin/spring:13:in `<top (required)>'
	from bin/rails:3:in `load'
	from bin/rails:3:in `<main>'

**Comment by HughLi** [comment]
please help me ,i spend so many times

**Comment by prathamesh-sonpatki** [comment]
Can you upload a sample application on Github that reproduces the issue? Thanks.

**Comment by HughLi** [comment]
just run the rails server  ,i build a new project ,but can't connecting localhost:3000

**Comment by seuros** [comment]
Check your firewall or iptables.

**Comment by andresfelipegarcia** [comment]
You find the solution?
I have the same problem.

**Comment by frankddk** [comment]
I have same trouble .
I think is GEM_HOME problem, but when i reset GEM_HOME , problem still here .
Now , try to reinstall ruby/rails with rvm  , hope can fix it.....
