### ISSUE TITLE
'Learn more' links on https://github.com/rails/rails/tree/master/activerecord lead to nowhere

### ISSUE THREAD

**Issue by k2m30** [rails/rails#26393]
### Steps to reproduce
Visit https://github.com/rails/rails/tree/master/activerecord
Click any of Learn more link.

### Expected behavior
Should lead to appropriate page

### Actual behavior
404 Github page

### System configuration
**Rails version**:
Latest as of Sep 5, 2016

**Comment by vipulnsward** [comment]
Closing as mentioned in #22181 (comment) and #25547 (comment)

Those links are meant to work in the official documentation web site not on GitHub. They are broken on GitHub but working in the site - http://api.rubyonrails.org/files/activerecord/README_rdoc.html
