### ISSUE TITLE
ActiveRecord::Persistance#becomes and ActiveRecord::Callbacks#after_initialize interference

### ISSUE THREAD

**Issue by mminazek** [rails/rails#26399]
### Steps to reproduce

```
class A < ActiveRecord::Base

after_inititialize :check_new_record

def check_new_record
   if new_record?
      puts "NEW RECORD"
   else
      puts "RECORD STORED IN DB" 
   end
end

class B < A
end

Console:
> var1 = B.create
<Class B id=1 ....>
> var1 = B.find(1)
RECORD STORED IN DB
 <Class B id=1 ....>
> var 1 = B.find(1).becomes(A)
RECORD STORED IN DB
NEW RECORD  <<- this should be RECORD STORED IN DB
 <Class A id=1 ....>
> var1 = B.find(1).becomes(A).new_record?
RECORD STORED IN DB
NEW RECORD
false
```
### Expected behavior

ActiveRecord::Persistance#becomes should assign all it's attributes and properties  (including new_record) in a block so ActiveRecord::Callbacks#after_initialize callback is not called before instance is copied
### Actual behavior

When using ActiveRecord::Persistance#becomes with ActiveRecord::Callbacks#after_initialize callback, this callback is called as soon as 

`became = klass.new`

is called and before  

`became.instance_variable_set("@new_record", new_record?)`

so this causes inconsistency with ActiveRecord::Persistance#new_record? inside ActiveRecord::Callbacks#after_initialize callback
## Suggested solution

Use block when creating new instance in ActiveRecord::Persistance#becomes.

```
def becomes(klass)
      became = klass.new do |became|
         became.instance_variable_set("@attributes", @attributes)
         became.instance_variable_set("@mutation_tracker", @mutation_tracker) if defined?(@mutation_tracker)
         became.instance_variable_set("@changed_attributes", attributes_changed_by_setter)
         became.instance_variable_set("@new_record", new_record?)
         became.instance_variable_set("@destroyed", destroyed?)
         became.errors.copy!(errors)
      end
      became
    end
```
### System configuration

**Rails version**:
4.2.6

**Ruby version**:
2.2.0

**Comment by maclover7** [comment]
@mminazek Can you send a pull request and we can continue the discussion there? Thanks!

**Comment by SampsonCrowley** [comment]
This is still an issue with rails 6; I will be posting a PR later today

**Comment by SampsonCrowley** [comment]
@maclover7 can we reopen this? I don't see any reason why becomes doesn't do its initialization inside of a block so that callbacks are run on the proper data

**Comment by SampsonCrowley** [comment]
https://gist.github.com/SampsonCrowley/96c61fac79922fd9a490ca3ff5530314
