### ISSUE TITLE
Controller tests no longer accept ActionDispatch::Http::UploadedFile

### ISSUE THREAD

**Issue by kirs** [rails/rails#26404]
In the process of upgrading to Rails 5, I've discovered a piece of code that worked fine on 4.2 and no longer works on `5-0-stable`:

```ruby
class PostsController < ApplicationController
  def upload
    raise "content: #{params[:file]}, class: #{params[:file].class}"
  end
end

class PostsControllerTest < ActionController::TestCase
  test "upload" do
    artwork = ActionDispatch::Http::UploadedFile.new(
      filename: 'artwork.jpeg',
      content_type: 'image/jpeg',
      tempfile: StringIO.new,
    )

    post :upload, params: { file: artwork }
  end
end
```

```
$ rails test test/controllers/posts_controller_test.rb
# Running:
Error:
PostsControllerTest#test_upload:
RuntimeError: content: #<ActionDispatch::Http::UploadedFile:0x007fb0c877acd8>, class: String
    app/controllers/posts_controller.rb:16:in `upload'
    test/controllers/posts_controller_test.rb:18:in `block in <class:PostsControllerTest>'
```

As you see, submitting a form with `ActionDispatch::Http::UploadedFile` instance gets the upload casted to `String`.

The reason why it happens is here: https://github.com/rails/rails/blob/5-0-stable/actionpack/lib/action_controller/test_case.rb#L137

It makes sense that Rails 5 is expecting `Rack::Test::UploadedFile` in test env, but I think that we shouldn't have break code that worked on 4.2. It seems like a regression to me.

cc @tenderlove since you've introduced that line.

**Comment by kirs** [comment]
The reason why I cannot use `Rack::Test::UploadedFile` in my test suite is that it only accepts a path to real file. In my test case, I want to test how the controller behaves with an empty file (`ActionDispatch::Http::UploadedFile.new(tempfile: StringIO.new)`)

**Comment by maclover7** [comment]
👍 Makes sense to me, can you open up a PR?

**Comment by kirs** [comment]
@maclover7 I had a chat with @rafaelfranca and it turns out that we can't send a valid file just with `StringIO.new`, because upload should also contain filename and mime type.

I'm going to close the issue.

**Comment by jaredbeck** [comment]
Using `::Rack::Test::UploadedFile` instead of `::ActionDispatch::Http::UploadedFile` worked for me, thanks. The constructor is a bit different, but no problem.

It would be great if someone could add this to the upgrade guide:
http://guides.rubyonrails.org/upgrading_ruby_on_rails.html#upgrading-from-rails-4-2-to-rails-5-0

**Comment by maclover7** [comment]
@jaredbeck opened #27954

**Comment by sergey-alekseev** [comment]
@maclover7 @jaredbeck can you explain why you added 
>If you are using `ActionDispatch::Http::UploadedFile` in your tests to upload files, you will need to change to use the similar `Rack::Test::UploadedFile` class instead.  

to the "Upgrading from Rails 4.2 to Rails 5.0" guide?

`ActionDispatch::Http::UploadedFile` works fine with a real file. As @kirs mentioned above   
>we can't send a valid file just with `StringIO.new`, because upload should also contain filename and mime type  

As I understand that's the reason of the issue and that's why he closed it. Correct me if I'm wrong.
