### ISSUE TITLE
Warning on association

### ISSUE THREAD

**Issue by Xosmond** [rails/rails#26413]
Im Getting this warning on this:

`@clients.sales limit: 10`

Am i forcing association to reload? How should i change this?

### Expected behavior
No message

### Actual behavior
Message appearing:
Passing an argument to force an association to reload is now deprecated and will be removed in Rails 5.1. Please call `reload` on the result collection proxy instead.

### System configuration
**Rails version**: 5.0.0.1

**Ruby version**: 2.3.1

**Comment by prathamesh-sonpatki** [comment]
@Xosmond Was this limit clause working before Rails 5?

**Comment by prathamesh-sonpatki** [comment]
Shouldn't it be `@clients.sales.limit 10`

**Comment by Xosmond** [comment]
Im not sure, because it used on a rails 5 project. By the way, what you suggest its working and no warning appear. Thanks.

PD: I just don't get the difference.

**Comment by SampsonCrowley** [comment]
@Xosmond sorry to comment on a closed thread, but just in case someone else ends up here the way i did.. the difference is what you are doing with the object

`@clients.sales limit: 10` is the equivalent of `@clients.sales(limit: 10)`. you are calling the `sales` method with the argument `limit: 10`.

`@clients.sales.limit 10` is the equivalent of `@clients.sales.limit(10)` here you are calling the method `limit` with the arg 10 on the object that is returned by `sales`

**Comment by booch** [comment]
The problem here is that the `sales` association (in Rails 5 and earlier) doesn't take a hash argument; it takes a boolean argument. That boolean determines whether to reload the association. Ruby is interpreting the `limit: 10` has as `true`, and thus reloading the association.
