### ISSUE TITLE
ActiveRecord::Core#initialize_dup should not be running initialize callbacks

### ISSUE THREAD

**Issue by bughit** [rails/rails#26411]
```ruby
    def initialize_dup(other) # :nodoc:
      @attributes = @attributes.dup
      @attributes.reset(self.class.primary_key)

      _run_initialize_callbacks

      @aggregation_cache = {}
      @association_cache = {}

      @new_record  = true
      @destroyed   = false

      super
    end
```

a dupped model is a copy of the already initialized original, so if you run initialize callbacks again, chances are you'll just overwrite (reinitialize) the already copied state, defeating the purpose of a dup

also there does not appear to be a direct way to detect dupping and skip the initialize callback
you'd need to override initialize_dup and set a flag

**Comment by bughit** [comment]
alternatively, initialize contexts could be helpful here (new, find, dup)

**Comment by bughit** [comment]
another issue here is that if you dup a saved record `@new_record` is not yet true when initialize_callbacks run

**Comment by bughit** [comment]
> alternatively, initialize contexts could be helpful here (new, find, dup)

To expand on this.  after_initialize is currently run in three contexts, new (Model.new), find (model reconstitution from the database) and dup (model.dup).

new is the useful context when you actually want to run initialization code, the other two are more a nuisance than a feature.

- find - reconstituting a model form the db is a very different operation than Model.new, it's not likely you'd want the same "initialization" code to run in both cases.  This case is also covered by the after_find callback, so it's not clear why after_initialize should apply here.  At least it's easy enough to filter out with `new_record?`.
- dup - copying an already initialized model is also different than newing one.  Running initialization code inteded to be run on new, after copying, is likely to reinitialize (overwrite) the copied state.  This situation is worse than find because it's harder to detect, there is no `dupping?` predicate.

I would argue that after_initialize only makes sense for Model.new, but if it's kept for the other contexts it should be easy to discriminate between them:

`after_initialize on: (:new|:find|:dup)`

**Comment by sgrif** [comment]
This is not a bug. Changing this behavior now would be a major breaking change.

**Comment by bughit** [comment]
it's not contrary any documentation because I don't think it's documented, but conceptually and practically it is a problem.

Languages typically have some notion of a copy constructor (initialize_dup in ruby) precisely because newing and dupping are different operations (newing is initializing state, dupping is copying already initialized state) and require different initialization.  But rails conflates them firing after_initialize with **no direct means** to tell the difference.

Do you not see that (at least the part where you can't tell the difference) as a problem that needs some remedy?

Can you comment on the context idea (https://github.com/rails/rails/issues/26411#issuecomment-245350357)?

**Comment by sgrif** [comment]
If you want some code that only runs after find, there is `after_find`. If you want code that is only run for actually new records and not in the other contexts, you can override `initialize`. You can also override `initialize_dup`. I don't think we need to add additional machinery for this.

**Comment by bughit** [comment]
Overriding initialize, if it's only ever invoked when newing, is good enough.  Then let me just point out that the very existence of and the documentation for after_initialize:

>It can be useful to avoid the need to directly override your Active Record initialize method.

seems to discourage using initialize.  In reality it's after_initialize that should be discouraged, because by default it executes in three very different contexts (dupping being undocumented), which more often than not, is unanticipated and undesirable.
