### ISSUE TITLE
Transaction on a Relation scopes all the subsequent queries

### ISSUE THREAD

**Issue by ggpasqualino** [rails/rails#26419]
### Steps to reproduce

The steps are on the following gist https://gist.github.com/ggpasqualino/42c16d6d8ef2bb193fba69651411da23

### Expected behavior
When I call transaction on a relation it shouldn't scope the following queries to the relation itself.

### Actual behavior
When I call transaction on a relation it scopes all the following queries to the relation itself.

### System configuration
**Activerecord version**: 4.2.7.1

**Ruby version**: 2.3.1

**Comment by matthewd** [comment]
Relation doesn't have a `transaction` method. You can call model class methods on a relation (that's how, e.g., chained scopes work), but when doing so, they scope the model to that relation, by design.

**Comment by ggpasqualino** [comment]
But as you can see from the gist it responds to transaction anyways with unexpected behavior.

So, as you are saying this should not be allowed at all.

Is it possible to implement something that when call transaction on a relation it will give me a warning/error? It seems more intuitive to me than responding to it with wrong behavior.
