### ISSUE TITLE
#new_record? is false in after_initialize when duping a persisted model

### ISSUE THREAD

**Issue by bughit** [rails/rails#26423]
``` ruby
begin
  require "bundler/inline"
rescue LoadError => e
  $stderr.puts "Bundler version 1.10 or later is required. Please update your Bundler"
  raise e
end

gemfile(true) do
  source "https://rubygems.org"
  gem "rails", github: "rails/rails"
  gem "sqlite3"
end

require "active_record"
require "minitest/autorun"
require "logger"

# This connection will do for database-independent bug reports.
ActiveRecord::Base.establish_connection(adapter: "sqlite3", database: ":memory:")
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :posts, force: true do |t|
  end
end

class Post < ActiveRecord::Base
  attr_accessor :new_record_during_initialize
  after_initialize do
    @new_record_during_initialize = new_record?
  end
end


class BugTest < Minitest::Test
  def test_association_stuff
    post = Post.create!
    assert post.dup.new_record_during_initialize

  end
end
```

in in #26411 I argue that after_initialize should not be invoked at all on dup, or that after_initialize contexts (new, find, dup) should be available.

**Comment by pixeltrix** [comment]
Closing because #26411 was closed

**Comment by bughit** [comment]
> Closing because #26411 was closed

Why?  Just because it's possible to avoid after_initialize altogether, does not mean that you should ignore bugs in it.  A duped record is new, new_record? should return true in after_initialize

**Comment by pixeltrix** [comment]
Because @sgrif said: 

> This is not a bug. Changing this behavior now would be a major breaking change.

This would also apply to the state of `new_record?` during `after_initialize`

**Comment by bughit** [comment]
He was talking about the proposal that after_initialize should not be run at all when duping.

Keeping after_initialize on dup in no way implies that new_record? should remain broken, or did you mean to imply that, @sgrif.

**Comment by bughit** [comment]
@pixeltrix please clarify your reasons, you are arguing that a method whose sole purpose is to tell you if a record is new, should lie, and that's not a bug, but a feature that people depend on.  This does not make sense to me.
