### ISSUE TITLE
rake db:rollback not rollback schema corrctly when use with change_column.

### ISSUE THREAD

**Issue by zw963** [rails/rails#26437]
### Steps to reproduce

I want to change payment_logs amount(decimal) from

```rb
:precision=>10, :default=>0, :null=>false
```

to

```rb
:precision=>10, :scale=>2, :default=>0, :null=>false
```

Following is my code:

```rb
class ChangeAmountToAddScale < ActiveRecord::Migration[5.0]
  reversible do |dir|
    dir.up do
      change_column :payment_logs, :amount, :decimal, precision: 10, scale: 2, default: 0, null: false
    end

    dir.down do
      change_column :payment_logs, :amount, :decimal, precision: 10, scale: 0, default: 0, null: false
    end
  end
end
```

And another try

```rb
class ChangeAmountToAddScale < ActiveRecord::Migration[5.0]
  reversible do |dir|
    dir.up do
      change_column :payment_logs, :amount, :decimal, precision: 10, scale: 2, default: 0, null: false
    end

    dir.down do
      change_column :payment_logs, :amount, :decimal, precision: 10, default: 0, null: false
    end
  end
end
```

All two case, when I run `rake db:rollback`, no error,  schema is always keep changed to
```rb
 t.decimal  "amount",                     precision: 10, scale: 2, default: "0.0", null: false
 ```
and not be reverted, But schema number is changed.

**Comment by kos-zenin** [comment]
Getting the similar issue with "change_column_null". Cannot remove fk_constraint. 
Migration passed successfully, but psql don't show any changes.

**Comment by girishso** [comment]
@zw963 I think you need to add `reversible` block inside `change` method.

**Comment by arthurnn** [comment]
>  I think you need to add reversible block inside change method.

That's right.

see http://api.rubyonrails.org/classes/ActiveRecord/Migration.html#method-i-reversible

**Comment by zw963** [comment]
@girishso , Thanks for reply. I don't know how I missing this change method ...

I do change as you let me do, it worked, But not as desired.
the schema.rb still keep changed. not revert to previous state.

Following is a full reproduce:

20160907222130 is VERSION before change column
20160909033548  is the VERSION do change column


###  reset to previous version
```sh

 ╰─ $ rake db:migrate:reset VERSION=20160907222130
 worked, elimate ouput ...
```

###  cat VERSION 20160909033548 file

```sh
 ╰─ $ cat db/migrate/20160909033548_change_amount_to_add_scale.rb
class ChangeAmountToAddScale < ActiveRecord::Migration[5.0]
  def change
    reversible do |dir|
      dir.up do
        change_column :payment_logs, :amount, :decimal, precision: 10, scale: 2, default: 0, null: false
      end

      dir.down do
        change_column :payment_logs, :amount, :decimal, precision: 10, default: 0, null: false
      end
    end
  end
end
```
### do migrate

```sh
╰─ $ rake db:migrate VERSION=20160909033548
Running via Spring preloader in process 4175
== 20160909033548 ChangeAmountToAddScale: migrating ===========================
-- change_column(:payment_logs, :amount, :decimal, {:precision=>10, :scale=>2, :default=>0, :null=>false})
   -> 0.0400s
== 20160909033548 ChangeAmountToAddScale: migrated (0.0402s) ==================

```

### see changed as expect.

```sh
 ╰─ $ git diff --word-diff db/schema.rb
t.decimal  "amount",                     precision: 10, {+scale: 2, default: "0.0",+} null: false
```
### do revert

```sh
 ╰─ $ rake db:migrate VERSION=20160907222130
Running via Spring preloader in process 7279
== 20160909033548 ChangeAmountToAddScale: reverting ===========================
-- change_column(:payment_logs, :amount, :decimal, {:precision=>10, :null=>false})
   -> 0.0411s
== 20160909033548 ChangeAmountToAddScale: reverted (0.0447s) ==================
```

### the db/schema.rb is keep changed.

```sh
t.decimal  "amount",                     precision: 10, {+default: 0,+} null: false
```

as you see, the `default: 0` is added to schema, but the initial content from
schema is:

```rb
t.decimal  "amount",                     precision: 10, null: false
```

Not

```rb
t.decimal  "amount",                     precision: 10, default: 0, null: false
```

**Comment by zw963** [comment]
@girishso  , Please see my last reply. thanks.

**Comment by kamipo** [comment]
How about it?

```diff
--- a/db/migrate/20160909033548_change_amount_to_add_scale.rb
+++ b/db/migrate/20160909033548_change_amount_to_add_scale.rb
@@ -6,7 +6,7 @@ def change
       end
 
       dir.down do
-        change_column :payment_logs, :amount, :decimal, precision: 10, default: 0, null: false
+        change_column :payment_logs, :amount, :decimal, precision: 10, null: false
       end
     end
   end
```

**Comment by zw963** [comment]
@kamipo , I changed my previous reply.

the result is same.

please see `cat VERSION 20160909033548 file` section.

**Comment by kamipo** [comment]
Looks like that `change_column` cannot drop default when `null: false`.
https://github.com/rails/rails/blob/v5.0.0/activerecord/lib/active_record/connection_adapters/postgresql/schema_statements.rb#L492
https://github.com/rails/rails/blob/v5.0.0/activerecord/lib/active_record/connection_adapters/abstract/schema_statements.rb#L1152

In the case we need to use `change_column_default` explicitly I think.

```diff
--- a/db/migrate/20160909033548_change_amount_to_add_scale.rb
+++ b/db/migrate/20160909033548_change_amount_to_add_scale.rb
@@ -6,6 +6,7 @@ def change
       end
 
       dir.down do
+        change_column_default :payment_logs, :amount, nil
         change_column :payment_logs, :amount, :decimal, precision: 10, null: false
       end
     end
```

**Comment by girishso** [comment]
Can't reproduce see https://gist.github.com/girishso/93bb3ec2243723acf52a019aa931ab9d

**Comment by zw963** [comment]
@girishso, please see my reproduce process in my reply.

before I do migrate, my table is `t.decimal  "amount",                     precision: 10, null: false`

so up and down is:

```rb
    reversible do |dir|
      dir.up do
        change_column :payment_logs, :amount, :decimal, precision: 10, scale: 2, default: 0, null: false
      end

      dir.down do
        change_column :payment_logs, :amount, :decimal, precision: 10, null: false
      end
    end
```

I think @kamipo ' reply is what I want. if this not a bug ...

**Comment by girishso** [comment]
@zw963 do you mind creating an executable gist similar to https://gist.github.com/girishso/93bb3ec2243723acf52a019aa931ab9d ?

**Comment by zw963** [comment]
@girishso , I create a new gist here. https://gist.github.com/53a7758e0b1397467e2c5829d986da08

Thanks.
