### ISSUE TITLE
has_secure_password cannot be configured with custom fields

### ISSUE THREAD

**Issue by dharamgollapudi** [rails/rails#26436]
`has_secure_password` expects that the user wants to secure `password` filed and there exists `password_digest` field in the database. There is no way to configure/override those expectations.

If we have `pass_digest` as a field in the database instead of the default expected `password_digest` field, we won't be able to use `has_secure_password`.

#26435 addresses this issue.

**Comment by rbcarlos** [comment]
That is true. These values are defaultly associated toeach other, but I am sure there is a way to override that although I do not see point in doing such.

**Comment by rafaelfranca** [comment]
This will be fixed by https://github.com/rails/rails/pull/26764

**Comment by dharamgollapudi** [comment]
@rafaelfranca Just curious, why #26764 is favored over #26435, which has more configurable options?

**Comment by rafaelfranca** [comment]
Because we really don't want to overcomplicate this feature. A configuration to the attribute name is fine. Many fine grained configurations are not what we want.

**Comment by lacostenycoder** [comment]
I think the method should be renamed to `has_secure_field` or `has_secure_attr` or perhaps at least aliased to avoid confusion when passing an argument for what that field name might be.
