### ISSUE TITLE
Rails.configuration.xxx is nil in rails test

### ISSUE THREAD

**Issue by lufeihaidao** [rails/rails#26432]
### Steps to reproduce

(Guidelines for creating a bug report are [available
here](http://guides.rubyonrails.org/contributing_to_ruby_on_rails.html#creating-a-bug-report))

### Expected behavior
I have `config/xxx.yml`. And in my project I use `Rails.configuration.xxx['field']` to get the configurations. 

### Actual behavior
It works well in runtime, but when I run `rails test`,  I got `undefined method '[]' for nil:NilClass`.

### System configuration
**Rails version**: 5.0.0

**Ruby version**: 2.3.0

**Comment by bithavoc** [comment]
does your .yml file has a config entry for `test`?

**Comment by lufeihaidao** [comment]
@bithavoc Oh yes I forgot it! Thank you!
