### ISSUE TITLE
Documentation should better document compilation of gem/engine images

### ISSUE THREAD

**Issue by blakeloverain** [rails/rails#26456]
I have several images in a custom engine ('webcore') under app/assets/images/webcore , that are not referenced by CSS compiled files, so they don't get compiled into my app's /public/assets/webcore . The documentation needs some clarification on how to work around this behavior.

Since the main app's app/assets/images/ files automatically get copied over to /public/assets/, I would expect my engine's asset images to be copied as well. At first I thought my engine's app/assets/images folder was not included in the paths, but I eventually found out  after manually adding in engine.rb that it already was but didn't make any difference.

I stumbled across the behavior by chance - discovering a gem whose images got copied over simply from reference in the CSS files. That behavior itself isn't documented clearly - why some asset images get copied and not others. However, I have images not mentioned in CSS and those would only get copied once I modified my engine's engine.rb file as per: http://guides.rubyonrails.org/engines.html#separate-assets-precompiling

```
    initializer "webcore.assets.precompile" do |app|
            config.assets.precompile += %w( webcore/*.png )
    end
```

 The documentation mostly references js/css files, but very little is said about images from assets/gems. It would be extremely helpful and time saving if the documentation could mention a paragraph on when gem image assets get copied to public (and when they don't) and have an example as well, such as in my case (referencing images, not just CSS/JS).

**Comment by maclover7** [comment]
@blakeloverain If you'd like to submit a PR to make some changes to the documentation, please do so! :)

**Comment by blakeloverain** [comment]
Where are the guides on github?

**Comment by maclover7** [comment]
The markdown files that power the guides live [here](https://github.com/rails/rails/tree/master/guides/source), inside of rails/rails.
