### ISSUE TITLE
Keep JSON data structured

### ISSUE THREAD

**Issue by MatthiasRMS** [rails/rails#26465]
When issuing an AJAX call from a view, and passing JSON, I should receive in the corresponding controller the exact same JSON. 

However, when doing this:

```
json_msg = {
  "object":"page",
  "entry":[
    {
      "id":"1234",
      "time":1458692752478,
      "messaging":[
        {
          "sender":{
            "id":"543"
          },
          "recipient":{
            "id":"34567"
          }
        }
      ]
    }
  ]
}

    $.ajax({
        type: "POST",
        url: "https://url_to_send.com",
        data: json_msg,
        dataType: "json",
        success: function() {

        },
        error: function(msg) {}
    });
```

I receive in the params:

```
Processing by MessagingController#receive_message as JSON
  Parameters: {"object"=>"page", "entry"=>{"0"=>{"id"=>"PAGE_ID", "time"=>"1458692752478", "messaging"=>{"0"=>{"sender"=>{"id"=>"USER_ID"}, "recipient"=>{"id"=>"PAGE_ID"}}}}}}
```

The array in the entry key has been replaced and there is an extra 0 key. Same problem with the messaging array.

There is no other processing, and had this right after starting a new Rails 5 app.
Am I doing something wrong here or is Rails transforming the data received ?

I tried to stringify the JSON before sending it, but then I get this:

```
Processing by MessagingController#receive_message as JSON
  Parameters: {"{\"object\":\"page\",\"entry\":"=>{"{\"id\":\"317614815243036\",\"time\":1473615625653,\"messaging\":"=>{"{\"sender\":{\"id\":\"1142389195826076\"},\"recipient\":{\"id\":\"317614815243036\"},\"timestamp\":1473615625498,\"message\":{\"mid\":\"mid.1473615625491:99adedcab35dd94768\",\"seq\":4741,\"text\":\"Hey\"}}"=>{"}"=>{"}"=>nil}}}}}
```

Which I can't use (impossible to use eval(params), can't use params["entry"], can't use JSON.parse(params) since it's a parameter object). I can't seem to find a turnaround for this.
### System configuration

**Rails version**: 5.0.0.1

**Ruby version**: 2.3.0

**Comment by maclover7** [comment]
Hi @MatthiasRMS! Did this work for you in any previous versions of Rails? Also, can you take your example JSON payload above and create an executable test script using one of the templates [here](https://github.com/rails/rails/tree/master/guides/bug_report_templates), that would demonstrate the problem you are seeing?

**Comment by MatthiasRMS** [comment]
I was able to reproduce it on Rails 4.2.1
I'll create an executable script, but can I run Javascript in those templates ? 

Also, does it seem normal to you to receive a modified JSON or do you also think it's a problem ?

**Comment by maclover7** [comment]
@MatthiasRMS Nope, there's no way to run JavaScript in the tests. I don't think this is a big issue though, we should be focusing on just POST-ing the JSON data to Rails and seeing if anything weird happens. If everything works when you POST the data through the script, then something weird must be going on with your JavaScript code. Let me know if you need any assistance with pulling together a reproduction script. :)

**Comment by dhagerty9009** [comment]
Is this a good test script? I whipped it up with data from the original post. If there's any work needed, let me know.

https://gist.github.com/dhagerty9009/77c9855c03d1b212ad1c0fbe4c47d68c

**Comment by maclover7** [comment]
Hi @dhagerty9009 -- yep, that reproduction script looks good to me! Unfortunately, it seems like the script is passing, and not erroring out... @MatthiasRMS would you be able to provide some more information or a test script to reproduce the error?

**Comment by MatthiasRMS** [comment]
@maclover7 thanks I'll try to put a script together asap and post it here

**Comment by dhagerty9009** [comment]
@MatthiasRMS I updated my test case if you want to use it as a baseline.
