### ISSUE TITLE
rescue_from AbstractController::ActionNotFound does not work

### ISSUE THREAD

**Issue by jasonsof** [rails/rails#26467]
### Steps to reproduce
Having this in my application controller:
`rescue_from AbstractController::ActionNotFound, with: :not_found`

And then trying to go to an action that doesn't exist in the browser

### Expected behavior
I would expect the method `not_found` to be run.

### Actual behavior
`
AbstractController::ActionNotFound at /x
The action 'index' could not be found for XController
`
### System configuration
**Rails version**: 5.0.0

**Ruby version**: 2.3.1

Is this something that needs to be fixed? Or is there a workaround to rescue from this kind of exception in a controller?

**Comment by maclover7** [comment]
Hi @jasonsof! Unfortunately, the `rescue_from` helper only works for errors raised within `process_action` method (you can check that out [here](https://github.com/rails/rails/blob/master/actionpack/lib/action_controller/metal/rescue.rb#L19-L24)), and `AbstractController::ActionNotFound` would be raised before we ever get to that method (you can check that out [here](https://github.com/rails/rails/blob/master/actionpack/lib/abstract_controller/base.rb#L121)).

**Comment by jasonsof** [comment]
Thanks for the info @maclover7, that makes sense (though it is quite annoying).  Can I ask if you know any way to catch and handle those types of exceptions myself that isn't too hacky?

**Comment by maclover7** [comment]
@jasonsof Sadly I think the only way would be to overwrite the method, and wrap a call to `super` in a `rescue` 😢

**Comment by rafaelfranca** [comment]
Why do you need custom error response for that. Are you doing the same with `ActiveRecord::RecordNotFound`? If what you want is a dynamic 404 page you should be not defining customs `rescue_from` but instead using a custom error middleware.

**Comment by jasonsof** [comment]
Yes the reason was to show a custom 404 page.  Using `rescue_from` seemed like the right way to do it since I'm already rescuing from a bunch of other exceptions in the controller.
@maclover7 Overriding Rails methods scares me a little 😨  so I probably won't be doing that.  I'll have a look into the middleware option
