### ISSUE TITLE
`rails plugin new` does not complete properly since bundler 1.12

### ISSUE THREAD

**Issue by jrochkind** [rails/rails#26474]
Bundler 1.12 seems to refuse to do any bundle operations if the Gemfile is considered 'invalid' becuase it has `TODO` in the summary/author/etc, which is how default gemfiles are generated. 

This means the final `bundle install` of the generator script does not work, so you don't actually have a bundled app. I don't _think_ the plugin script contains any `post_bundle` hooks, so it's not as bad as it could be -- any `post_bundle` hooks probably won't run at all, or won't work properly. (Third party software providing generators building on plugin new could provide such post_bundle hooks, and be broken worse). 

With Bundler 1.13 there's a different(?) [worse problem](https://github.com/rails/rails/issues/26472), but I assume if that problem were resolved this one would still be waiting. 

~~~
$ ruby -v
ruby 2.3.1p112 (2016-04-26 revision 54768) [x86_64-darwin15]
$ rails -v
Rails 5.0.0.1
$ bundle -v
Bundler version 1.12.5

$rails plugin new testplugin
      create
      create  README.md
      create  Rakefile
      create  testplugin.gemspec
      create  MIT-LICENSE
      create  .gitignore
      create  Gemfile
      create  lib/testplugin.rb
      create  lib/tasks/testplugin_tasks.rake
      create  lib/testplugin/version.rb
      create  bin/test
      create  test/test_helper.rb
      create  test/testplugin_test.rb
      append  Rakefile
  vendor_app  test/dummy
         run  bundle install
You have one or more invalid gemspecs that need to be fixed.
The gemspec at /Users/jrochkind/code/testplugin/testplugin.gemspec is not valid. Please fix this gemspec.
The validation error was '"FIXME" or "TODO" is not a description'
~~~

With bundler 1.11.2, this does not reproduce, the `rails plugin new` completes without errors, and the `bundle install` happens.

**Comment by vipulnsward** [comment]
We don't bundle install now- https://github.com/rails/rails/commit/fbd1e98cf983572ca9884f17f933ffe92833632a

Need to check the Gemfile though.

**Comment by jrochkind** [comment]
Ah, I see, fbd1e98 is not included in 5.0.0.1 I guess, so by 'now' you mean in 'master', and in a yet to be released future Rails?  Okay, I guess that works. 

Would encourage a bug fix release sooner rather than later, since this makes rails generators broken with recent Bundler releases.

**Comment by jrochkind** [comment]
Also, the plugin generator [theoretically supports](https://github.com/rails/rails/blob/fbd1e98cf983572ca9884f17f933ffe92833632a/railties/lib/rails/generators/rails/plugin/plugin_generator.rb#L263-L267) `after_bundle` callbacks. 

If bundle install isn't being run... what is an `after_bundle` callback, will it never be run, will it be run but without running `bundle install` first? Either option seems like a bug, and I can't think of any other option. I don't think you can support `after_bundle` callbacks if you aren't bundling, yes?

I guess the built-in plugin new task has no `after_bundle` callbacks, but it's still got the hook to run them -- are there supported ways to build your own template on top of `plugin`, and could some of those be using `after_bundle` callbacks, and will those break in an environment where there's no `bundle install` and mysterious behavior of `after_bundle` callbacks?

**Comment by rafaelfranca** [comment]
This is fixed in cbb6a2670ee775531ec92301998be3b824648e7f.

And yes, `after_bundle` will be not supported by plugins.

**Comment by jrochkind** [comment]
If I understand the code right, at the moment `after_bundle` is supported... it just doesn't happen after bundling, since no bundling happens since cbb6a26. But the generator is still gonna call any after_bundle callbacks [here](https://github.com/rails/rails/blob/92703a9ea5d8b96f30e0b706b801c9185ef14f0e/railties/lib/rails/generators/rails/plugin/plugin_generator.rb#L263-L267), isn't it? Should that be removed?

**Comment by rafaelfranca** [comment]
Yes, it should be removed
