### ISSUE TITLE
Misleading error when failing to match a routing constraint

### ISSUE THREAD

**Issue by chriscarter90** [rails/rails#26470]
### Steps to reproduce

1) Create a `resources` block with a a constraint on the named segment, for example:
```ruby
resources :reports, only: [:new, :create, :show], param: :reference, reference: /\d+/

```

2) Use a generate URL path helper, and provide a value for the named segment which fails to match the constraint:
```ruby
report_path(reference: "ABC123")
```

3) Receive a helpfully named error, but with a misleading piece of text saying that a required key is missing:
```plain
ActionController::UrlGenerationError: No route matches {:action=>"show", :controller=>"reports", :reference=>"ABC123"} missing required keys: [:reference]
```

### Expected behavior
The error message should state the route matches, but the value for the required key fails to match any constraints.

### Actual behavior
The error states that the key is missing, when it has been provided with a non-matching value.

### System configuration
**Rails version**: `Rails 4.2.7.1`
**Ruby version**: `ruby 2.3.0p0`

**Comment by maclover7** [comment]
Hi @chriscarter90, thanks for opening up this issue! I've been working on a patch for this, but I think this is going to overcomplicate the route generation code, and is currently leading to a lot of tests failing. This is mostly due to that the Rails router automatically using regular expressions when validating route segments. Because of this, it would be tough to tell which regexes came from the user as opposed to Rails internals, and it would IMHO be a large-ish breaking change in user experience to change many of our error messages. 😢

**Comment by rafaelfranca** [comment]
What we can do is make the message more generic like "one of the required
keys is missing or not matching the constraint"

**Comment by utilum** [comment]
Not a good idea to distinguish between "missing key" and "value not matching the restraint"?

**Comment by rafaelfranca** [comment]
Too much complexity in my opinion.

**Comment by utilum** [comment]
I see, not to mention multiple key-value problems. How about "a required key is missing or not matching the constraint," which allows for the plurality?

**Comment by rafaelfranca** [comment]
:+1:

**Comment by pixeltrix** [comment]
Couldn't we check for the presence of the key(s) when [building the exception message][1] - if it's present in the constraints hash then we can be pretty sure that it's an unmatched constraint and not a missing key. Should just be an intersection of the constraints hash keys and the missing keys array to get the unmatched constraints.

[1]: https://github.com/rails/rails/blob/master/actionpack/lib/action_dispatch/journey/formatter.rb#L47-L48
