### ISSUE TITLE
Make rails middlewares reusable outside of rails

### ISSUE THREAD

**Issue by TiagoCardoso1983** [rails/rails#26479]
### Steps to reproduce

This can be considered chore/feature.

As of now, Rails middlewares are unusable outside of a Rails app. I've been trying to use Rack::URLMap to map subpaths to different apps:

```ruby
# config.ru
app = Rack::URLMap.new(
  "/" => Rails.application,
  "/api" => App::API
)

run app
```

this works, but I lose all the middlewares of the rails app, one of them being the authentication layer, which is handled by devise. 

so I went further and have been trying to do something like this:

```ruby
class CustomBuilder < Rack::Builder
  def call(env)
    req = Rails.application.send(:build_request, env)
    super(req.env)
  end
end

api = CustomBuilder.new do
  run App::API
end

# ugly, but rack doesn't allow me anything else
api.instance_variable_get(:@use, Rack.application.config.middleware)

app = Rack::URLMap.new(
  "/" => Rails.application,
  "/api" => api
```

This will break, because [Rack::Builder#to_app requires the middleware to be reversable](https://github.com/rack/rack/blob/master/lib/rack/builder.rb#L147). From the same link, you can see that the middleware must respond to `[]`.

The first approach seems to be to implement `ActionDispatch::MiddlewareStack#reverse` (it is an Enumerable, not an Array), and to implement `ActionDispatch::MiddlewareStack::Middleware#[]` (could be a simple alias to `ActionDispatch::MiddlewareStack::Middleware#build`). The `#reverse` implementation is however "dangerous", because it means that existing `#use` calls which do global mutation will be executed as many times as the number of apps mapped in my `Rack::URLMap` app. This is why [this would break](https://github.com/plataformatec/devise/issues/4291), but then again, the requirement is from rack, so maybe this could be deviced there. 

**Rails version**:

5.0.0.1

**Ruby version**:

2.2

**Comment by matthewd** [comment]
Please use the mailing list or StackOverflow for questions/help, where a wider community will be able to help you. We reserve the issues tracker for issues only.

**Comment by TiagoCardoso1983** [comment]
Done: https://groups.google.com/forum/#!topic/rubyonrails-core/sIamWxrwHFo

**Comment by matthewd** [comment]
I was more thinking -talk. Anyway, if I use real words instead of a canned reply 😐...

If you want the request to go through the Rails stack but ultimately get passed along to another Rack application, you can do that in `routes.rb`:

```ruby
mount App::API, at: "/api"
```

---

Initializing a second middleware stack that just looks the same as the main application's is unlikely to achieve what you want anyway.

**Comment by TiagoCardoso1983** [comment]
what is -talk? Is it a chat where we could discuss this further?

As it is, is not unlikely, it's impossible :) If I want to be pragmatic then yes, mounting in routes is the solution of today. However, it seems rails is duplicating a lot of the functionality that rack provides. There are 2 ways to add middleware to a rails app, a rails middleware is not a rack middleware, and there is stuff in the env hash which only appears once the request reaches the rails app. I'll try to summarize:

```ruby
class MyRackMiddleware
  def initialize(app)
    @app = app
  end

  def call(env)
     puts "is the key generator here? : #{!env["action_dispatch.key_generator"].nil?}"
     @app.call(env)
  end
end

# application.rb
...
  config.middleware.use MyRackMiddleware

# config.ru

use MyRackMiddleware
run Rails.application
````
