### ISSUE TITLE
Appears to be creating one table alias per query

### ISSUE THREAD

**Issue by rylarson** [rails/rails#26481]
A new table alias appears to be getting created for every association. My very simple rails app had a memory leak. By analyzing heapdumps, I narrowed it down to a huge `@aliases` array inside `Arel::Table`. 

In Active Record, when an association is not polymorphic, it calls `#alias` on the table, which unconditionally adds an alias to that array. After calling `uniq` on the array, there is only one alias remaining. 

I am not 100% sure if this is a bug in `Arel::Table`, or a bug in Active Record associations creating too many aliases.

### Steps to reproduce

http://stackoverflow.com/questions/39460355/areltable-aliases-memory-leak-when-used-in-rails-5

### Expected behavior
A single table alias should be created

### Actual behavior
A table alias is created for every query with the association

### System configuration
**Rails version**: 5.0.0

**Ruby version**: 2.3.0

**Comment by sgrif** [comment]
Fixed in https://github.com/rails/arel/commit/44d2ef9623847dea5cbf6208ae7b5168b374c720

**Comment by rafaelfranca** [comment]
Released as arel 7.1.2

**Comment by aogail** [comment]
Awesome, thanks!

**Comment by avit** [comment]
❤️ I'm so glad this finally got fixed, thank you Sean.

(I offered a pull-request for it 2 years ago but it got closed & locked: https://github.com/rails/rails/pull/18673)
