### ISSUE TITLE
Please release 3-2-stable as 3.2.22.5

### ISSUE THREAD

**Issue by johnnyshields** [rails/rails#26494]
PR #26131, now merged to `3-2-stable`, fixes an interface regression in 3.2.22.3/4 which is likely to occur in any app of sufficient size (it does in mine!)

This should be released; it's a total pain to upgrade to a security patch version (3.2.22.3/4) and discover that it breaks your app.

**Comment by shakycode** [comment]
@johnnyshields I'm in the same position. Upgraded to 3.2.22.3 to fix a security vulnerability and several parts of my app broke.  I doubt the core team will release 3.2.22.5 since this version of Rails is no longer supported.  We may have to pull from the 3-2-stable branch instead when bundling.  I'm forking and rebundling today to see how things go.  Otherwise I've had to patch myself which is a big pain and unfortunately I'm not in a position to upgrade this legacy app to 4.2.6 or 5.x quite yet.

**Comment by shakycode** [comment]
@johnnyshields If you look at the 3-2-stable branch the build is failing right now so maybe wait and see what sort of feedback we see from the community, if any.

**Comment by johnnyshields** [comment]
To leave a `*-stable` branch in a broken build state and have known regressions in your latest security patch version is sloppy. Let's please tie up the loose ends here.

**Comment by johnnyshields** [comment]
By the way, it seems the build has been broken for the recent releases. While it would be best to fix the build, if this is not easily doable then it shouldn't prevent releasing 3.2.22.5.

**Comment by johnnyshields** [comment]
@rafaelfranca @tenderlove @arthurnn the last release (3.2.22.4) was 34 days ago (August 11, 2016) and it contains a serious regression which is fixed on 3-2-stable. I have a PR #26495  in progress which fixes the failing specs on the branch. One the specs are green may we please cut a last release?

**Comment by johnnyshields** [comment]
For avoidance of doubt, I do not expect the core team to provide active support for 3.2 branch, that being said "if you break it, you must fix it." 3.2.22.4 is a broken release.

**Comment by shakycode** [comment]
@johnnyshields There is also RailsLTS that will support 3.2.22.x however it costs money.  I'm forking 3.2.22.3 and patching this myself.  I will post a link to my repo if you want to fork and test it once I'm done.

**Comment by johnnyshields** [comment]
@shakycode your comment is missing the point. Rails team cut a release with a regression a month ago, it needs to be patched, plain and simple.

**Comment by tenderlove** [comment]
@johnnyshields I will release a new version.  Thank you for the kind words.

**Comment by johnnyshields** [comment]
@tenderlove thank you, I appreciate you taking the time to do so and I apologize if my comments are overly terse. I'm working PR #26495 to get the 3-2-stable specs back to green which hopefully can help if/when another pesky CVE pops up.

**Comment by tenderlove** [comment]
@johnnyshields @shakycode do you want me to release `3-2-stable` as is, or wait for #26495?

**Comment by johnnyshields** [comment]
wait for #26495 is my vote

**Comment by tenderlove** [comment]
@johnnyshields ok.  Can you ping me here when #26495 is green?  I'll merge it and ship a new version.  Thanks!

**Comment by shakycode** [comment]
@tenderlove I'll wait for #26495 Thank you kindly ❤️

**Comment by johnnyshields** [comment]
@tenderlove tests on #26495 are green with two caveats, please see PR.

**Comment by tenderlove** [comment]
3.2.22.5 is shipped now.

**Comment by shakycode** [comment]
@tenderlove Thank you so much for the quick turn around.  Please send my love to the family, especially Gorby 👍

**Comment by johnnyshields** [comment]
@tenderlove thank you for shipping, much appreciated!! :beers:
