### ISSUE TITLE
I18n errors

### ISSUE THREAD

**Issue by lifeiscontent** [rails/rails#26491]
### Steps to reproduce

1. create an array in your locale file
2. iterate over it.
3. delete array in i18n file

### Expected behavior
Tell me which key is missing in the locale file

### Actual behavior
Throws error that isn't useful

### System configuration
**Rails version**: 5.0.0.1

**Ruby version**: 2.3.1

<img width="1046" alt="screen shot 2016-09-14 at 5 38 45 pm" src="https://cloud.githubusercontent.com/assets/180963/18509331/337b083a-7aa2-11e6-8c90-89b5c8a822ca.png">

**Comment by prathamesh-sonpatki** [comment]
Can you upload a sample application on Github that reproduces the issue? Thanks.

**Comment by rafaelfranca** [comment]
This seems to be a problem in your application `experience` is an array not a Hash

**Comment by lifeiscontent** [comment]
@rafaelfranca This is a tooling layer problem. As a developer, working in a rails application I'd like better errors to tell me what key the application is breaking on.

Rails already does this for missing keys that are rendered as strings, why can't it forward me the key thats missing on all data types?

**Comment by lifeiscontent** [comment]
@prathamesh-sonpatki I have no problem creating a sample application if you guys deem this as something to be fixed.

**Comment by rafaelfranca** [comment]
The problem that is that you made your i18n file return an array and is using a hash. There is nothing that the tool can do for you.
