### ISSUE TITLE
ActionCable connects in incognito window only after refresh

### ISSUE THREAD

**Issue by pmichna** [rails/rails#26493]
I know the problem is very hard to diagnose only from the reproduction steps but maybe it'll ring a bell for someone.
### Steps to reproduce
1. Open the application in production (localhost works fine) in a new incognito window (tested on Chrome and Firefox).
2. Do something that triggers ActionCable message (or even broadcast them from production's `rails console`).
### Expected behavior

An ActionCable message should be received in JS.
### Actual behavior

The ActionCable message is not received in JS. However, when you REFRESH the page (clicking links on the page doesn't help) and repeat the steps everything works fine. What's more - if you visit the application's page again (not in incognito mode) the problem is not present too.
### System configuration

The production application is behind [incapsula](https://www.incapsula.com/). Could that be a problem?
**Rails version**:
5.0.0.1
**Ruby version**:
2.3.1

**Comment by maclover7** [comment]
cc @javan

**Comment by javan** [comment]
I'm unable to reproduce this. I created a fresh app using 5.0.0.1 and Action Cable works the same for me in an incognito window. Can you create an example app that demonstrates the problem you're seeing?
