### ISSUE TITLE
ActiveRecord module defined twice in the same file

### ISSUE THREAD

**Issue by utilum** [rails/rails#26502]
I hope this isn't too much of cosmetic nitpicking, but is there a reason to close the module on reopen it immediately?
see: 
https://github.com/rails/rails/blob/master/activerecord/lib/active_record/fixtures.rb#L10
and https://github.com/rails/rails/blob/master/activerecord/lib/active_record/fixtures.rb#L844-L846 :
```#/activerecord/lib/active_record/fixtures.rb
...
module ActiveRecord
...
end

module ActiveRecord
...```

**Comment by kaspth** [comment]
Not sure. I think changing it is a cosmetic commit though. Thanks!
