### ISSUE TITLE
Getting started guide section 5 from .11 to end of 5 is wrong

### ISSUE THREAD

**Issue by flybd5** [rails/rails#26512]
### Steps to reproduce

Follow the steps from 5.11 to the beginning of section 6.0

### Expected behavior

Should work as advertised.

### Actual behavior

```
ArgumentError in Articles#edit
Showing /home/juan/rails-1st/app/views/articles/_form.html.erb where line #1 raised:
              
<%= form_for @article do |f| %>
 
  <% if @article.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@article.errors.count, "error") %> prohibited

Trace of template inclusion: app/views/articles/edit.html.erb

Rails.root: /home/juan/rails-1st

Application Trace | Framework Trace | Full Trace
app/views/articles/_form.html.erb:1:in `_app_views_articles__form_html_erb__1200067123094411917_70225546334440'
app/views/articles/edit.html.erb:3:in `_app_views_articles_edit_html_erb___3565774493532637995_70225546491240'
Request

Parameters:

{"id"=>"2"}
Toggle session dump
Toggle env dump
Response

```
Headers:

None

### System configuration
**Rails version**:
Rails 5.0.0.1
**Ruby version**:
ruby 2.3.0p0 (2015-12-25 revision 53290) [x86_64-linux]

**Comment by prathamesh-sonpatki** [comment]
Do you have edit action in your controller as follows?

``` ruby
def edit
  @article = Article.find(params[:id])
end
```

It seems to that `@article` being nil is causing this error.

**Comment by flybd5** [comment]
This is straight out of the Getting Started exercise. I am not qualified to
debug it.

**Comment by utilum** [comment]
@flybd5 Could you have mistyped something in copying from the guide page. I've just completed step 5.11 without encountering anything unexpected.

**Comment by flybd5** [comment]
Wasn't typing, was copy/paste'ing. I will try it again when I have some
time, I've moved on to another task...

**Comment by prathamesh-sonpatki** [comment]
Thanks @utilum! I am closing this for now, will reopen if we can reproduce it.
