### ISSUE TITLE
Error in code listing in "Getting Started" step 5.10

### ISSUE THREAD

**Issue by kenatsun** [rails/rails#26519]
### Steps to reproduce
Do the Getting Started (GS) steps through "5.10 Adding Some Validation".  Look at the "article.rb" model file you generated back in step 5.4.

### Expected behavior
Step 5.10 is the first place that shows us what the model file is supposed to look like:

class Article < ApplicationRecord
end

GS goes on to say that "ApplicationRecord inherits from ActiveRecord::Base..."

### Actual behavior
If your results match mine, the "article.rb" file you generated actually looks like:

class Article < ActiveRecord::Base
end

I'm guessing that the code actually generated is right and GS snippet is wrong.  But, as a total newbie, I'm just reporting the apparent discrepancy.

### System configuration
**Rails version**: 4.2.3

**Ruby version**: 2.2.2p95

**Comment by rafaelfranca** [comment]
Thank you for the report. You are reading the Rails 5 guide and using a 4.2 application, this will be indeed discrepant. Make sure you are reading the guide for the right version.
