### ISSUE TITLE
Tag dynamic proxy does not accept options with keys as strings 

### ISSUE THREAD

**Issue by claudiob** [rails/rails#26518]
I created a gist to reproduce the error:
https://gist.github.com/claudiob/c55b65624af5f726cf7076fca86e559f

In short, the new `tag.p` suggested in #25195 and implemented by @marekkirejczyk in #25543 does not handle options correctly if the keys are strings.

```ruby
tag.p("class" => "show", :class => "elsewhere")
# Expected HTML: <p class="show" class="elsewhere"></p>
# Actual HTML: <p class="elsewhere">{&quot;class&quot;=&gt;&quot;show&quot;}</p>
```

The "old-style" `tag(:p)` was handling the same case correctly as [confirmed by this test](https://github.com/rails/rails/blob/84650022d574d24d6adea6ad941ec3ca57d2a2f0/actionview/test/template/tag_helper_test.rb#L32-L36).

**Comment by maclover7** [comment]
I've got a quick fix for this locally, but it's quite hacky. :(

**Comment by claudiob** [comment]
@maclover7 Can you share what you have? I'm thinking about changing the splat on the options but I'm not 100% sure…

**Comment by rafaelfranca** [comment]
What that is possible if `tag("p")` is implemented using the same code path as `tag.p`?

**Comment by rafaelfranca** [comment]
`:class => "elsewhere"` is being interpreted by ruby as a second argument, not as the same hash.

**Comment by maclover7** [comment]
@claudiob: 26520

**Comment by claudiob** [comment]
It's the same code but the way in which options are passed through is different [here](https://github.com/rails/rails/blob/84650022d574d24d6adea6ad941ec3ca57d2a2f0/actionview/lib/action_view/helpers/tag_helper.rb#L235-L241):

```ruby
def tag(name = nil, options = nil, open = false, escape = true)
  if name.nil?
    tag_builder
  else
    "<#{name}#{tag_builder.tag_options(options, escape) if options}#{open ? ">" : " />"}".html_safe
  end
end
```

**Comment by rafaelfranca** [comment]
You code is just wrong. The first argument of the `tag.p` method is the content, not the options hash.

**Comment by claudiob** [comment]
[This test](https://github.com/rails/rails/blob/84650022d574d24d6adea6ad941ec3ca57d2a2f0/actionview/test/template/tag_helper_test.rb#L50-L52) (and the successive ones) pass the options as the first argument:

```ruby
  def test_tag_builder_options_accepts_false_option
    assert_equal "<p value=\"false\"></p>", tag.p(value: false)
end
```

Are you suggesting it should be `tag.p(nil, value: false)`?

**Comment by rafaelfranca** [comment]
This is an problem with keyword arguments. As ruby keyworks arguments only captures symbol keys the ruby interpreter will split that hash in two as you have one string key:

```irb
>> def foo(*args)
>>   bar *args
>>   end
=> :foo
>> def bar(a = nil, **options)
>>   p a
>>   p options
>>   end
=> :bar
>> foo("a" => 1, :b => 2)
{"a"=>1}
{:b=>2}
```

**Comment by rafaelfranca** [comment]
I'm suggesting: don't mixes symbol keys and string keys.

**Comment by rafaelfranca** [comment]
More example on how that can be lost:

```irb
>> foo(:b => 1, "a" => 2)
{"a"=>2}
{:b=>1}
```

**Comment by claudiob** [comment]
@rafaelfranca thanks for explaining the _cause_ of the issue.

I think there are three ways to solve the issue itself:

1. We document that the options cannot be provided with a mix of symbols and strings as keys

2. We add a `.symbolize_keys` to the code before invoking the `tag_builder`

3. We change the `**options` part with a different Ruby code that accepts keys both as strings and as symbols

**Comment by rafaelfranca** [comment]
I'd go with 3. 1 is not good and 2 will change the behavior anyway.

```
>> { "a" => 1, :a => 2}.symbolize_keys
=> {:a=>2}
```

**Comment by claudiob** [comment]
@rafaelfranca Regarding 1. above, the problem is not _mixing_ symbols and strings. The problem is strings themselves. For instance, the following happens as well (only string keys):

```ruby
tag.p("class" => "show", "id" => "elsewhere")
# Expected HTML: <p class="show" id="elsewhere"></p>
# Actual HTML:   <p>{&quot;class&quot;=&gt;&quot;show&quot;, &quot;id&quot;=&gt;&quot;elsewhere&quot;}</p>
```

**Comment by claudiob** [comment]
Thanks, I'll try to implement 3.!

**Comment by claudiob** [comment]
If we stick with the possibility of passing either the `content` or the `options` as the first argument of `tag.p` then… I think #26520 will do.

`tag.p` is not one of those cases where we can decide whether the first argument is content or options based on `if block_given?`. 

Even changing `**options` to something like `options` wouldn't change the fact that `"class" => "show"` would be interpreted as the first argument `content`.

@rafaelfranca would you consider reopening #26520 ?

**Comment by rafaelfranca** [comment]
I don't think so. That is not the correct fix. extract_options should work
for this case.

**Comment by claudiob** [comment]
Ok I'll try that, thanks!

**Comment by kaspth** [comment]
Why do we want to support mixing strings and symbol keys here? I was the one who told the contributor not to bother in the original PR.

**Comment by claudiob** [comment]
@kaspth and @eileencodes (asking the same question on #26535):

The reason why I opened this issue is that, in the current `master`, the following code:

```ruby
tag.p("class" => "show", "id" => "elsewhere")
# => <p>{&quot;class&quot;=&gt;&quot;show&quot;, &quot;id&quot;=&gt;&quot;elsewhere&quot;}</p>
```

does not return the same as the "old-style" code:

```ruby
tag(:p, "class" => "show", "id" => "elsewhere")
# => <p class="show" id="elsewhere"></p>
```

As I wrote [in my comment above](https://github.com/rails/rails/issues/26518#issuecomment-247704308), if this is _intended_ (we don't support string keys), then we should at least _document_ this.

In my own personal opinion, we should _still_ support string keys because, for instance, the method [html_options_for_form](https://github.com/rails/rails/blob/c66121722b0a39b5090b5e4bad88a3590e88d076/actionview/lib/action_view/helpers/form_tag_helper.rb#L833-L854) builds an `options` Hash with string keys, and this is the hash that is passed to `form_tag` to build a form [in this code](https://github.com/rails/rails/blob/c66121722b0a39b5090b5e4bad88a3590e88d076/actionview/lib/action_view/helpers/form_tag_helper.rb#L886-L889):

```ruby
def form_tag_html(html_options)
  extra_tags = extra_tags_for_form(html_options)
  tag(:form, html_options, true) + extra_tags
end
```

If we changed the `tag(:form)` above with `tag.form` then the code would not work.

**Comment by kaspth** [comment]
I think it's fine to start moving toward symbol keys only (but maybe we need @dhh's confirmation on that).

We're also looking at writing new form helpers in #25197, so that particular incongruence won't stay for long.

**Comment by claudiob** [comment]
@kaspth Testing the code of https://github.com/rails/rails/pull/25560 (which address #25197) is exactly what brought me to open this issue.

If we decide to go with only symbols then of course this issue can be closed.

**Comment by claudiob** [comment]
I just found that we had another PR that https://github.com/rails/rails/pull/26552 by @rafaelfranca where the decision was made to replace strings with symbols. Is this the way to go in the future?

> To fix this inconsistency we are always storing with symbols. This will cause a small breaking change > because in those cases the details could be accessed as strings keys but now it can not.

**Comment by dhh** [comment]
I'd support symbol-only keys going forward with these new APIs.

We can break with the past here since the tag proxy is new and so is form_with.

**Comment by kaspth** [comment]
Symbols it is! 👍

**Comment by chuchiperriman** [comment]
We have problems with symbols attributes. There are cases where parameters are needed: 
* Attributtes with namespace my:test="ok"
* Special frameworks attributes like vue: @click="method",  :prop="value"

We are creating tags with vue attributes but we cannot use TagBuilder because it does not understand it and raise the error:

`wrong number of arguments (given 3, expected 1..2)`

Please, think about implement this feature, it is important for us.
