### ISSUE TITLE
`$ bin/rails db:migrate` in "Getting Started" guide doesn't work

### ISSUE THREAD

**Issue by kenatsun** [rails/rails#26521]
### Steps to reproduce

Do the "Getting Started with Rails" (GS) process.  Try to run `$ bin/rails db:migrate` as instructed in step 5.5, "Running a migration".

### Expected behavior
According to GS, Rails will "execute this migration command and tell you it created the Articles table."

### Actual behavior
$ bin/rails db:migrate
Error: Command 'db:migrate' not recognized
Did you mean: `$ rake db:migrate` ?

As the error message suggests, `rake db:migrate` succeeds.

FWIW, all the other Rails commands in GS that start with `bin/rails ` do work. 

### System configuration
**Rails version**: 4.2.3

**Ruby version**: 2.2.2

**Comment by rafaelfranca** [comment]
You are reading the guides for rails 5 and using rails 4. This command will not work in rails 4
