### ISSUE TITLE
ActiveRecord exec_query fail for nonselect requests

### ISSUE THREAD

**Issue by oklas** [rails/rails#26537]
Hi!

Execution raw sql for `nonselect` queries like this:

    ActiveRecord::Base.connection.exec_query( 'update orders set id=1 where id=1' )

(undependently from correctness of sql) fail with execption :

 > NoMethodError: undefined method `fields' for nil:NilClass

(any requests always applied and db fields always updated as expected)

If it is not bug, how to execute any raw sql requests with same result
(I mean ActiveRecord::Result) which contain selected data for select
requests and any way to recognize empty data in result for nonselect.

**Comment by matthewd** [comment]
Please use the mailing list or StackOverflow for questions/help, where a wider community will be able to help you. We reserve the issues tracker for issues only.

**Comment by oklas** [comment]
The answer is (by analize of sources activerecord-4.2.4):
Method `exec_query` is for select requests only
There set of methods: `exec_insert`, `exec_update`=`exec_delete` and `execute`
Only `exec_query` create ActiveRecord::Result where `result.fields` is called.
But only for select queries result is exists.
So to execute another queries (not select) `exec_query` is not suitable.
