### ISSUE TITLE
rails route bug.

### ISSUE THREAD

**Issue by zw963** [rails/rails#26530]
#### Step 1: Add route like this:

``` rb
namespace :api, path: '' do
  namespace :v1, path: 'v1' do
     namespace, :my do
      resources :follow_search_keywords, only: [:index, :create, :destroy], param: :search_keyword_id
    end  
  end
end
```
#### Step 2: use grep to see the correct result:

We need routes PATH `/v1/my/follow_search_keywords` to controller
`api/v1/my/follow_search_keywords#index`.

``` sh
 ╰─ $ rails routes |g follow_search_keyword
Running via Spring preloader in process 20440
             api_v1_my_follow_search_keywords GET    /v1/my/follow_search_keywords(.:format)                    api/v1/my/follow_search_keywords#index
                                              POST   /v1/my/follow_search_keywords(.:format)                    api/v1/my/follow_search_keywords#create
              api_v1_my_follow_search_keyword DELETE /v1/my/follow_search_keywords/:search_keyword_id(.:format) api/v1/my/follow_search_keywords#destroy
```
#### But I add controller to wrong place. (without my namespace)

``` sh
 ╰─ $ find app/controllers/ -name '*follow*' |grep follow
app/controllers/api/v1/my/follow_categories_controller.rb
app/controllers/api/v1/follow_search_keywords_controller.rb  <=  No my namespace
app/controllers/api/v1/user_follows_controller.rb
```
#### But test is passed.

it found out the expected controller files, in this case, is:
``app/controllers/api/v1/follow_search_keywords_controller.rb`

``` rb
class Api::V1::FollowSearchKeywordsControllerTest < ActionDispatch::IntegrationTest
     test "" do
      get api_v1_my_follow_search_keywords_url(format: :json),
          params: {}
      assert_response :success
     end
end
```
### Expected behavior

Should told me could not found the controller.

because the correct controller file should be in:
``app/controllers/api/v1/my/follow_search_keywords_controller.rb`
### System configuration

**Rails version**:
5.0.0.1
**Ruby version**:
2.2.4

**Comment by Shwetakale** [comment]
@zw963 Could you please reconfirm you routes file? I dpn't see namespace ```my``` in your route file.

When I copy pasted you route file I got following routes

```ruby
api_v1_follow_search_keywords GET    /v1/follow_search_keywords(.:format)                    api/v1/follow_search_keywords#index
                              POST   /v1/follow_search_keywords(.:format)                    api/v1/follow_search_keywords#create
 api_v1_follow_search_keyword DELETE /v1/follow_search_keywords/:search_keyword_id(.:format) api/v1/follow_search_keywords#destroy 

```

**Comment by zw963** [comment]
@Shwetakale ,  sorry, I fix my issue.

**Comment by pixeltrix** [comment]
@zw963 can you double check this report - where does the 'my' namespace aspect fit in as it's not defined by your route definition.

**Comment by pixeltrix** [comment]
@zw963 can I close this then?

**Comment by zw963** [comment]
@pixeltrix ,  Not.

I just give correct my routes content, but this bug is still wait confirm.

**Comment by Neodelf** [comment]
If you execute this [this gist](https://gist.github.com/Neodelf/f4a33319284676e62ef5a72dcb7bf656), result will not been contain errors.

**Comment by zw963** [comment]
@Neodelf , 

my problem is ``file name convention`` not match the routes, this gist seem like could not
decide this is not a bug? 

thanks.
