### ISSUE TITLE
#underscore adds underscores across acronyms even when part of a longer word

### ISSUE THREAD

**Issue by matstc** [rails/rails#26549]
### Steps to reproduce

The underscore function adds underscore in-between acronyms even if they are part of a longer word.

For example, if API is defined as an acronym, it will transform SCRAPING into scr_api_ng.

I believe this behavior only happens when the input is uppercase.

### Expected behavior

More intuitive would be for `SCRAPING` to remain as `SCRAPING`.

### Actual behavior

`SCRAPING` becomes `scr_api_ng`

### System configuration

**Rails version**: master

**Ruby version**: 2.3.1

# Test case
```
begin
  require "bundler/inline"
rescue LoadError => e
  $stderr.puts "Bundler version 1.10 or later is required. Please update your Bundler"
  raise e
end

gemfile(true) do
  source "https://rubygems.org"
  gem "rails", github: "rails/rails"
end

require "active_support"
require "active_support/core_ext/object/blank"
require "minitest/autorun"

ActiveSupport::Inflector.inflections(:en) do |inflect|
  inflect.acronym 'API'
end

class BugTest < Minitest::Test
  include ActiveSupport::Inflector

  def test_stuff
    assert_equal "SCRAPING", underscore("SCRAPING")
  end
end
```

**Comment by matthewd** [comment]
This is intended behaviour. Any uppercase input to underscore is taken to be an acronym, in principle; explicitly registered acronyms are used to identify the boundaries: `"HTTPAPIJSON".underscore`, `"APIV1".underscore`.

**Comment by matstc** [comment]
All right. Although it seems counter-intuitive, especially when used through `titleize` where `SCRAPING` becomes `Scr API Ng` instead of `Scraping`.
