### ISSUE TITLE
Display warning when running tests with no assertions

### ISSUE THREAD

**Issue by maxehmookau** [rails/rails#26546]
When running tests, I've always wondered why tests without assertions automatically count as passing. This works on the assumption that _all_ tests pass by default and only fail if an assertion actively fails. 
As I'm coding, I want to be made aware if I've written a test at any point that isn't asserting something as without an assertion, is it really a test?

### Expected behavior
1. Write a test without asserting anything.
1. Show some sort of warning/error/maybe even a failure?

### Actual behavior
1. Write a test without asserting anything.
1. Test passes.

### System configuration
**Rails version**:
5.0.x (and presumably all previous versions too)

**Comment by JeromeGill** [comment]
I'd argue no warning or you end up writing arbitrary assertions just for the sake of having one in some cases.

I think of it this way, the default state is to assert no exception is thrown.

**Comment by utilum** [comment]
@JeromeGill What are those test cases that need to live in the code without asserting anything?

**Comment by rafaelfranca** [comment]
This should be handle by minitest. Could you report it there? Also we don't get feature requests in the issue tracker. :heart: :green_heart: :blue_heart: :yellow_heart: :purple_heart:

**Comment by maxehmookau** [comment]
Ok! Apologies :)
