### ISSUE TITLE
Strong params are nil if empty hash passed as a parameter from spec test case.

### ISSUE THREAD

**Issue by panigrah** [rails/rails#26569]
`params` set to nil on controller when an empty hash is passed to a param in test case. in Rails 4 params would contain an empty hash. Tests on several of my apps fail to run after upgrade because `params[:key]` is nil in the controller.
### Steps to reproduce on Rails 5.0.0.1

```
#/spec/controllers/users_controller_spec.rb
require 'rails_helper'
RSpec.describe UsersController, type: :controller do
describe "test case" do
   it "tests R5" do
     post :create, user: {} #fails, but setting user: {name: "somevalue"} works
   end
 end
```

   end

Example Controller

```
class UsersController < ApplicationController
  def create
     user_params
  end

  protected
    def user_params
       params[:user].permit(:username) #this barfs because params[:user] becomes nil
  end
```

   end
### Expected behavior

params[:user] in the controller should not be nil
### Actual behavior

params[:user] is nill unlike R4 where params[:user] would be set to an empty hash.
### System configuration

**Rails version**:
5.0.0.1

**Ruby version**:
2.3.1

rspec-3.5.0
actionpack-5.0.0.1

**Comment by maclover7** [comment]
HI @panigrah! Did this work for you in prior version of Rails? I think I've traced the root of this issue to a problem with how the rack-test gem builds its parameter strings.

**Comment by panigrah** [comment]
@maclover7 yes it works on Rails4. I tracked it down to something going different in ActionController::TestCase.assign_parameters()

In rails 4 `@request.parameters` contains 'user: {}' after the call to assign_parameters() but not in Rails5.

**Comment by maclover7** [comment]
Sorry, was confused for a second, thought we were dealing with a different kind of test.

Can confirm the breakage on master right now, looks like it was caused by https://github.com/rails/rails/commit/c546a2b045600b6d700140adf2a4df666d6e08ce. Created a reproduction script [here](https://gist.github.com/maclover7/504154e43eb09afd120fd5502912b023). The issue seems to be that the `Hash#to_query` Active Support doesn't handle empty hashes very well.

cc @tenderlove

**Comment by panigrah** [comment]
@maclover7 so we have a way to fix? Hash#to_query code and behavior is unchanged between r4 and r5.

**Comment by maclover7** [comment]
@panigrah The difference between v4 and v5 is the fact that we are calling `Hash#to_query` at all and doing processing on the parameters 😬. The bug you are seeing is due a problem with the implementation of `Hash#to_query`.

**Comment by panigrah** [comment]
@maclover7 is there an easy fix that I can patch locally  which you can suggest?  It will help me fix 100+ test case failures quickly. thanks

**Comment by panigrah** [comment]
@maclover7 undoing that patch makes the tests pass

**Comment by panigrah** [comment]
Scratch that - it passes that test - but fails others.

**Comment by tenderlove** [comment]
@panigrah does you controller process query parameter or JSON posts?  If it's query parameters, can you give me an example of a query string that produces a `user: {}` in the params hash.  If it's JSON, can you try doing a JSON post in your test?

**Comment by panigrah** [comment]
@tenderlove I may need your help to figure out what this is. Would the following result in json? 

    post :create, xhr:true,  params: {user:  {}}, format: :json

That fails in the controller as `params[:user]` is nil in the `params.require(:user).permit(...)`.

**Comment by tenderlove** [comment]
@panigrah you should be able to do it like this:

```
post :create, format: "json", params: { user: {} }
```

But I would like to know if you're using JSON in production or query parameters?  If you're using query parameters, are you able to make a query string that results in `user: {}` in the params hash?

**Comment by maletor** [comment]
@tenderlove that way of passing params as JSON doesn't seem to work as you suggest. I'm upgrading a Rails 4 project and curious if it's a bug in Rails 4 that's hidden by RSpec or if it actually does work in 4.

**Comment by rafaelfranca** [comment]
Yes, `as:` make it work.

**Comment by masterkain** [comment]
`post :create, params: { playlist: { name: '' }, q: {} }, format: 'json'`

`q` does not exists in `params` when cheking in the controller action

**Comment by hammerdr** [comment]
We also ran into this when upgrading from Rails 4 to Rails 5. Empty hashes (for better or worse) are a valuable and significant construct in our APIs.

**Comment by laertispappas** [comment]
Same here

**Comment by roooodcastro** [comment]
Wait, this does not solve the issue, simply masks it. I have a create action that, due to our business rules, does not redirect to `show`, but instead renders the `new` template again. This "fix" only changes the post format to `json`, so in my case I'm now getting an `ActionView::MissingTemplate` error, because I do not implement a `new.json.erb` template, but instead the default `new.html.erb`. I do not want to submit using JSON, as I don't have an API, but instead a regular form.

The issue is still the same - in Rails 4.x, passing an empty hash as parameter worked, but now in Rails 5.x the parameter is not going to the controller anymore.

Can we please open this ticket again so the underlying issue can be fixed?

**Comment by top4ek** [comment]
Got the same.
rails 5.2.2
ruby 2.6.1
rspec 3.8.0
actionpack 5.2.2

Fixed by passing `as: :json` to request.

**Comment by wjessop** [comment]
Just hit this on Rails 6.0.0 beta1. I worked around it just fine, but it tripped me up for a while because my expectation was for it to work.

In my controller:

```ruby
params.require(:invitation).permit(:decline_reason)
```

In my test, this works:

```ruby
patch decline_invitation_url(i), params: {invitation: {decline_reason: ""}}
```

Params logged are:

```
{"invitation"=>{"decline_reason"=>""}, "invitation_identifier"=>"3fd1fuh"}
```

This doesn't*:

```ruby
patch decline_invitation_url(i), params: {invitation: {}}
```

Params logged are:

```
{"invitation_identifier"=>"3clbsrfuh"}
```

\* The error:

```ruby
ActionController::ParameterMissing: param is missing or the value is empty: invitation
```

**Comment by YassineDM** [comment]
I had exactly the same behavior with Rails 6.0.0.beta3...

**Comment by valterbarros** [comment]
I had the same behavior with rails 5.2.1

**Comment by dyeje** [comment]
Same behavior with Rails 5.2.3

**Comment by Gibbo3771** [comment]
Same result with Rails 5.2.3. This wouldn't be a bad thing but I am trying to build the API to match the JSON API Specification, which has a bunch of _must_ have keys, even if empty, one being attributes. So this completely breaks that design.

Any work arounds? I have 25 controllers so would prefer a monkey patch.

**Comment by danilodelponte** [comment]
Same behaviour occurs with empty arrays:

```ruby 
put :update, params: { params[:phones] = [] }, format: :json
```

`params[:phones]` is `nil` when inspecting inside controller.

Not sure if this behaviour is expected, but replacing `format: :json` with `as: :json` does fix it.

**Comment by mariusz-blaszczak** [comment]
I was having the same issue while upgrading from rails 4.2 to 5.0. In the beginnig my test code looked like this:
```ruby
post :create, user: {}, format: "json"
```
But `params[:user]` was nill

So I changed it according to the suggestions in this issue to:
```ruby
post :create, user: {}, as: :json
```
But it did not work neither.

This eventually worked:
```ruby
post :create, params: { user: {} }, as: :json
```
