### ISSUE TITLE
NameError: uninitialized constant in active record compute_type

### ISSUE THREAD

**Issue by nikhilm492** [rails/rails#26561]
We have the following ActiveRecord models related as follows:

Intranet model -> has_many -> Setting model (settings)
User model -> has_many -> PayrollHour model (payroll_hours)

The code used is:

In app/models/user.rb

has_many :payroll_hours

In app/models/intranet.rb

has_many :settings

So, the code User.first.payroll_hours or Intranet.first.settings should return data from the corresponding related model.

But we get the errors,

NameError: uninitialized constant Intranet::Setsting

NameError: uninitialized constant User::PayrollHmine

The stack trace is:

from /usr/local/rvm/gems/ruby-2.3.1@v5/gems/activerecord-5.0.0/lib/active_record/inheritance.rb:152:in `compute_type'

Our Rails version is 5.0.0 and Ruby version 2.3.1

The same errors also happened in Rails version 4.2.5 and Ruby version 2.3.0

**Comment by matthewd** [comment]
> NameError: uninitialized constant Intranet::Setsting

Typo?

> NameError: uninitialized constant User::PayrollHmine

Custom 'ours' -> 'mine' pluralization rule?

---

Please use the mailing list or StackOverflow for questions/help, where a wider community will be able to help you. We reserve the issues tracker for issues only.

**Comment by nikhilm492** [comment]
NameError: uninitialized constant Intranet::Setsting

is not a typo

NameError: uninitialized constant User::PayrollHmine

no custom pluralization defined

**Comment by andela-echigbo** [comment]
I am running into a similar issue. Mine is in *FactoryGirl* association and I think mine has to do with model namespacing where the polymorphic model is not in the same namespace with the models that associate with it.

```
NameError: uninitialized constant StripeCustomer::Strippable
from /Users/emmanuelchigbo/.rvm/gems/ruby-2.3.0/gems/activerecord-5.0.0/lib/active_record/inheritance.rb:152:in `compute_type'
```

**Comment by SamMolokanov** [comment]
I had the same issue using associated model under namespace.
A workaround here is setting up *class_name* option on association:

` has_many :billing_transactions, class_name: 'Billing::Transaction'`

**Comment by darkindrio** [comment]
> I had the same issue using associated model under namespace.
> A workaround here is setting up _class_name_ option on association:
> 
> ` has_many :billing_transactions, class_name: 'Billing::Transaction'`

Nice, this worked for me. I was using a version deprecated of ruby and needs a direct reference to association.
Thanks

**Comment by MilanVilov** [comment]
> I had the same issue using associated model under namespace.
> A workaround here is setting up _class_name_ option on association:
> 
> ` has_many :billing_transactions, class_name: 'Billing::Transaction'`

This worked for me! Thank you!

**Comment by PierceF** [comment]
I looked up the naming conventions for join tables and join table models, and made changes accordingly, that fixed my issue: https://www.bhalash.com/archives/13544808137
