### ISSUE TITLE
ActiveJob: `provider_job_id` is not serialized after enqueuing the job

### ISSUE THREAD

**Issue by sodar** [rails/rails#26581]
### Steps to reproduce
- Implement job based on `ActiveJob::Base` class with callbacks `after_enqueue` and `before_perform`. Callbacks will print out `provider_job_id`.
  
  ``` ruby
  class FooJob < ActiveJob::Base
      after_enqueue do |job|
          puts job.provider_job_id
      end
      before_perform do |job|
          puts job.provider_job_id
      end
      def perform
          # do something
      end
  end
  ```
### Expected behavior
- Both callbacks should print out identical `provider_job_id`.
### Actual behavior
- Only `after_enqueue` callback prints out correct `provider_job_id`. In `before_perform` `provider_job_id` is equal to `nil`
- It is probably related to the serialization/deserialization code. `provider_job_id` is not stored in job data.
  
  In `ActiveJob::Core#deserialize` (https://github.com/rails/rails/blob/master/activejob/lib/active_job/core.rb#L111) `provider_job_id` is mentioned, but in `ActiveJob::Core#serialize` it is not.
### System configuration

**Rails version**: 5.0.0.1
**Ruby version**: 2.3.1p112

**Comment by antstorm** [comment]
👍

**Comment by cristianbica** [comment]
What adapter are you using for the test above?

**Comment by utilum** [comment]
The test suite iterates through the adapters and runs the all the tests for each of them.
