### ISSUE TITLE
Add License file.

### ISSUE THREAD

**Issue by CaioBianchi** [rails/rails#26585]
Github recently added a new feature which displays the licensing at the top menu bar when specified in the repo. https://github.com/blog/2252-license-now-displayed-on-repository-overview

This is as simple as adding a `LICENSE` file to the root of the repo.
Much like https://github.com/expressjs/express/blob/master/LICENSE

I'm not sure who/if anyone holds the copyrights for Rails, if I did, I would've submitted a pull request.

**Comment by prathamesh-sonpatki** [comment]
Already being worked on here https://github.com/rails/rails/pull/26577
