### ISSUE TITLE
Using .in(x.hours) on a TimeWithZone near DST boundary skips hours

### ISSUE THREAD

**Issue by reist** [rails/rails#26580]
### Steps to reproduce
* Create a TimeWithZone an hour before the local -1 DST boundary.
* Add 1 hour using .in(1.hour)
* See the time added was really 2 hours
 
### Example code
Using NewYork time (US/Eastern)
`t = Time.zone.local(2016,11,6,1) # Sun, 06 Nov 2016 01:00:00 EDT -04:00`
`t.advance(hours: 1) #=> Sun, 06 Nov 2016 01:00:00 EST -05:00`
`t.since(1.hour) #=> Sun, 06 Nov 2016 01:00:00 EST -05:00`
`t + 1.hour #=> Sun, 06 Nov 2016 01:00:00 EST -05:00`
`t.in(1.hour) #=> Sun, 06 Nov 2016 02:00:00 EST -05:00`

### System configuration
**Rails version**: 4.2.7.1 or 5.0.0.1

**Ruby version**: 2.3.1

**Comment by tbalthazar** [comment]
I've been able to reproduce it with:
``` ruby
begin
  require "bundler/inline"
rescue LoadError => e
  $stderr.puts "Bundler version 1.10 or later is required. Please update your Bundler"
  raise e
end

gemfile(true) do
  source "https://rubygems.org"
  # Activate the gem you are reporting the issue against.
  gem "activesupport", "5.0.0.1"
end

require "active_support/time"
require "minitest/autorun"

# Ensure backward compatibility with Minitest 4
Minitest::Test = MiniTest::Unit::TestCase unless defined?(Minitest::Test)

class BugTest < Minitest::Test
  def test_advance_1_hour_across_spring_dst_transition
    @time_zone = ActiveSupport::TimeZone["Eastern Time (US & Canada)"]
    twz = ActiveSupport::TimeWithZone.new(nil, @time_zone, Time.utc(2016,11,6,1))
    assert_equal "Sun, 06 Nov 2016 01:00:00 EST -05:00", twz.advance(hours: 1).inspect
    assert_equal "Sun, 06 Nov 2016 01:00:00 EST -05:00", twz.since(1.hour).inspect
    assert_equal "Sun, 06 Nov 2016 01:00:00 EST -05:00", twz.in(1.hour).inspect
    assert_equal "Sun, 06 Nov 2016 01:00:00 EST -05:00", (twz + 1.hour).inspect
    assert_equal "Sun, 06 Nov 2016 01:00:01 EST -05:00", twz.since(1.hour + 1.second).inspect
    assert_equal "Sun, 06 Nov 2016 01:00:01 EST -05:00", (twz + 1.hour + 1.second).inspect
  end
end
```

and I'm working on a fix.

**Comment by pixeltrix** [comment]
@tbalthazar there should be some tests already for `since` that can be duplicated and changed to `in`. The fix should be as simple as adding `alias_method :in, :+` after `alias_method :since, :+` in `time_with_zone.rb` in Active Support.

**Comment by tbalthazar** [comment]
@pixeltrix Thanks, that was exactly what I was doing. Glad to read I'm on the right track :)
