### ISSUE TITLE
update_attribute returns unexpected nil when new value is the same as current 

### ISSUE THREAD

**Issue by donapieppo** [rails/rails#26593]
`update_attribute(name, value)` returns `nil` if the submitted value is the same as the current value. 
In rails 4 it returned `true` (as aspected, imo).

```ruby
p = Post.create(title: 'foo')
p.update_attribute(:title, 'foo') # returns nil
p.update_attribute(:title, 'bar') # return true
```
I think in rails 4 the db update query was always done. 
In rails 5 the unecessary update is skipped but I think the return value should be `true`.

With `update_column` the update is done and the return value is always `true`.

### Expected behavior
```ruby
   p = Post.create(title: 'foo')
   p.update_attribute(:title, 'foo') # should return true
```

### System configuration

Rails: 5.0.0.1
Ruby: 2.3.1p112

**Comment by rafaelfranca** [comment]
If there is no change in the database why true is expected?

**Comment by donapieppo** [comment]
Because I don't care what happens behind (in db) or what was the previous value. 
With `update_attribute(:title, 'foo')` I need to know that now the current value of title is 'foo', that everything went fine. And I expect `true`  in order to feel good an go on :-)
A `nil` return value is like a `false` return value.

**Comment by rafaelfranca** [comment]
In fact the return of this method should not care for you. If you are
expecting always true, so why are you checking the return of the method?

And yes nil is false in that case and it means exactly what it means, no
attribute were updated so it return false.

**Comment by donapieppo** [comment]
I am not expecting always `true`. I expect `true` if everthing went fine and the value of title is foo. 

You mean that what with `update_attribute` nothing can go wrong and I can never get a `false` result? 
If that is the case maybe the doc should say that. Should say that there is no interesting return value.

If instead there can be a `false` (and I need to check it), than a nil return value is unexpected for an update where everything went fine.

**Comment by donapieppo** [comment]
Of course if the `nil` return value `means exactly what it means, no attribute were updated so it return false` is the wanted behaviour than you can close this.

I still think that `update_attribute` should be idempotent (if it is the correct word) meaning that it sould return the same value when executed multiple time. It should not depend on the previous value of the attribute. As was in rails 4.

Maybe I just need to replace `update_attribute` with `update_column`.

**Comment by prathamesh-sonpatki** [comment]
@rafaelfranca @donapieppo I had changed this behavior to save a SQL call in https://github.com/rails/rails/commit/0fcd4cf5.

I think we can return true if `changed?` is false to restore the old behavior. I can make a PR if this sounds like acceptable solution.

**Comment by donapieppo** [comment]
a `true` return value with `changed?` false would be great for me.

Otherwise the doc should say that `update_attribute` returns nil if the new value is the same as the value in the database.

**Comment by rafaelfranca** [comment]
👍

**Comment by prathamesh-sonpatki** [comment]
Great, I will send a PR in some time.
