### ISSUE TITLE
The ActiveRecord::table_name is in chaos after the inheritance and changing table_name

### ISSUE THREAD

**Issue by fanjieqi** [rails/rails#26596]
```
require "active_record"
  ActiveRecord::Base.establish_connection(
    adapter: "mysql2", 
    host: "localhost", 
    database: "test"
  )

  class DbKeyword < ActiveRecord::Base; end
  class Keyword < DbKeyword; end

  Keyword.table_name = "test_1_keywords"
  p Keyword.table_name # => "test_1_keywords"
  p Keyword.first #  => "ActiveRecord::StatementInvalid: Mysql2::Error: Table 'test.db_keywords' doesn't exist: SHOW FULL FIELDS FROM `db_keywords`"
```

> /usr/local/lib/ruby/gems/2.3.0/gems/mysql2-0.4.4/lib/mysql2/client.rb:107:in `_query'
> /usr/local/lib/ruby/gems/2.3.0/gems/mysql2-0.4.4/lib/mysql2/client.rb:107:in`block in query'
> /usr/local/lib/ruby/gems/2.3.0/gems/mysql2-0.4.4/lib/mysql2/client.rb:106:in `handle_interrupt'
> /usr/local/lib/ruby/gems/2.3.0/gems/mysql2-0.4.4/lib/mysql2/client.rb:106:in`query'
> /usr/local/lib/ruby/gems/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:309:in `block in execute'
> /usr/local/lib/ruby/gems/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/connection_adapters/abstract_adapter.rb:484:in`block in log'
> /usr/local/lib/ruby/gems/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
> /usr/local/lib/ruby/gems/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/connection_adapters/abstract_adapter.rb:478:in`log'
> /usr/local/lib/ruby/gems/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:309:in `execute'
> /usr/local/lib/ruby/gems/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/connection_adapters/mysql2_adapter.rb:231:in`execute'
> /usr/local/lib/ruby/gems/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:316:in `execute_and_free'
> /usr/local/lib/ruby/gems/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:463:in`columns'
> /usr/local/lib/ruby/gems/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/connection_adapters/schema_cache.rb:43:in `columns'
> /usr/local/lib/ruby/gems/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/attributes.rb:93:in`columns'
> /usr/local/lib/ruby/gems/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/model_schema.rb:260:in `column_names'
> /usr/local/lib/ruby/gems/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/attribute_methods.rb:86:in`block in define_attribute_methods'
> /usr/local/lib/ruby/gems/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/attribute_methods.rb:83:in `define_attribute_methods'
> /usr/local/lib/ruby/gems/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/attribute_methods.rb:85:in`block in define_attribute_methods'
> /usr/local/lib/ruby/gems/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/attribute_methods.rb:83:in `define_attribute_methods'
> /usr/local/lib/ruby/gems/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/core.rb:113:in`allocate'
> /usr/local/lib/ruby/gems/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/persistence.rb:69:in `instantiate'
> /usr/local/lib/ruby/gems/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/querying.rb:50:in`block (2 levels) in find_by_sql'
> /usr/local/lib/ruby/gems/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/result.rb:51:in `block in each'
> /usr/local/lib/ruby/gems/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/result.rb:51:in`each'
> /usr/local/lib/ruby/gems/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/result.rb:51:in `each'
> /usr/local/lib/ruby/gems/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/querying.rb:50:in`map'
> /usr/local/lib/ruby/gems/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/querying.rb:50:in `block in find_by_sql'
> /usr/local/lib/ruby/gems/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/notifications/instrumenter.rb:20:in`instrument'
> /usr/local/lib/ruby/gems/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/querying.rb:49:in `find_by_sql'
> /usr/local/lib/ruby/gems/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/relation.rb:639:in`exec_queries'
> /usr/local/lib/ruby/gems/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/relation.rb:515:in `load'
> /usr/local/lib/ruby/gems/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/relation.rb:243:in`to_a'
> /usr/local/lib/ruby/gems/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/relation/finder_methods.rb:500:in `find_nth_with_limit'
> /usr/local/lib/ruby/gems/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/relation/finder_methods.rb:484:in`find_nth'
> /usr/local/lib/ruby/gems/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/relation/finder_methods.rb:127:in `first'
> /usr/local/lib/ruby/gems/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/querying.rb:3:in`first'
> /Users/user/Project/db/Rakefile:82:in `block in <top (required)>'
> /usr/local/lib/ruby/gems/2.3.0/gems/rake-11.2.2/exe/rake:27:in`<top (required)>'
> Mysql2::Error: Table 'test.db_keywords' doesn't exist
> /usr/local/lib/ruby/gems/2.3.0/gems/mysql2-0.4.4/lib/mysql2/client.rb:107:in `_query'
> /usr/local/lib/ruby/gems/2.3.0/gems/mysql2-0.4.4/lib/mysql2/client.rb:107:in`block in query'
> /usr/local/lib/ruby/gems/2.3.0/gems/mysql2-0.4.4/lib/mysql2/client.rb:106:in `handle_interrupt'
> /usr/local/lib/ruby/gems/2.3.0/gems/mysql2-0.4.4/lib/mysql2/client.rb:106:in`query'
> /usr/local/lib/ruby/gems/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:309:in `block in execute'
> /usr/local/lib/ruby/gems/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/connection_adapters/abstract_adapter.rb:484:in`block in log'
> /usr/local/lib/ruby/gems/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
> /usr/local/lib/ruby/gems/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/connection_adapters/abstract_adapter.rb:478:in`log'
> /usr/local/lib/ruby/gems/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:309:in `execute'
> /usr/local/lib/ruby/gems/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/connection_adapters/mysql2_adapter.rb:231:in`execute'
> /usr/local/lib/ruby/gems/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:316:in `execute_and_free'
> /usr/local/lib/ruby/gems/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:463:in`columns'
> /usr/local/lib/ruby/gems/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/connection_adapters/schema_cache.rb:43:in `columns'
> /usr/local/lib/ruby/gems/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/attributes.rb:93:in`columns'
> /usr/local/lib/ruby/gems/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/model_schema.rb:260:in `column_names'
> /usr/local/lib/ruby/gems/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/attribute_methods.rb:86:in`block in define_attribute_methods'
> /usr/local/lib/ruby/gems/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/attribute_methods.rb:83:in `define_attribute_methods'
> /usr/local/lib/ruby/gems/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/attribute_methods.rb:85:in`block in define_attribute_methods'
> /usr/local/lib/ruby/gems/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/attribute_methods.rb:83:in `define_attribute_methods'
> /usr/local/lib/ruby/gems/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/core.rb:113:in`allocate'
> /usr/local/lib/ruby/gems/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/persistence.rb:69:in `instantiate'
> /usr/local/lib/ruby/gems/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/querying.rb:50:in`block (2 levels) in find_by_sql'
> /usr/local/lib/ruby/gems/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/result.rb:51:in `block in each'
> /usr/local/lib/ruby/gems/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/result.rb:51:in`each'
> /usr/local/lib/ruby/gems/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/result.rb:51:in `each'
> /usr/local/lib/ruby/gems/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/querying.rb:50:in`map'
> /usr/local/lib/ruby/gems/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/querying.rb:50:in `block in find_by_sql'
> /usr/local/lib/ruby/gems/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/notifications/instrumenter.rb:20:in`instrument'
> /usr/local/lib/ruby/gems/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/querying.rb:49:in `find_by_sql'
> /usr/local/lib/ruby/gems/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/relation.rb:639:in`exec_queries'
> /usr/local/lib/ruby/gems/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/relation.rb:515:in `load'
> /usr/local/lib/ruby/gems/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/relation.rb:243:in`to_a'
> /usr/local/lib/ruby/gems/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/relation/finder_methods.rb:500:in `find_nth_with_limit'
> /usr/local/lib/ruby/gems/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/relation/finder_methods.rb:484:in`find_nth'
> /usr/local/lib/ruby/gems/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/relation/finder_methods.rb:127:in `first'
> /usr/local/lib/ruby/gems/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/querying.rb:3:in`first'
> /Users/user/Project/db/Rakefile:82:in `block in <top (required)>'
> /usr/local/lib/ruby/gems/2.3.0/gems/rake-11.2.2/exe/rake:27:in`<top (required)>'
> Tasks: TOP => temp1

The Keyword class is inherited from the DbKeyword, and then changing the table_name.

**Comment by tenderlove** [comment]
Can you give us a more complete example?  We've only been able to get this exception:

```
/Users/eileen/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/mysql2-0.4.4/lib/mysql2/client.rb:107:in `_query': Mysql2::Error: Table 'activerecord_unittest.test_1_keywords' doesn't exist: SHOW FULL FIELDS FROM `test_1_keywords` (ActiveRecord::StatementInvalid)
```

The above exception is what I would expect.

**Comment by fanjieqi** [comment]
When there isn't a test_1_keywords, the exception "test_1_keywords doesn't exist" is also what i expect. 

But the exception is "db_keywords doesn't exist", when there is a nonempty test_1_keywords table and there isn't a db_keywords table. 

The Keyword.first is nil when i truncate the test_1_keywords table.

**Comment by uaihebert** [comment]
Hi.

I have created the code bellow and I was not able to reproduce your bug. Did I miss something?

```
begin
  require "bundler/inline"
rescue LoadError => e
  $stderr.puts "Bundler version 1.10 or later is required. Please update your Bundler"
  raise e
end

gemfile(true) do
  source "https://rubygems.org"
  gem "rails"
  gem "sqlite3"
  gem 'mysql2'
end

require "active_record"
require "minitest/autorun"
require "logger"

# This connection will do for database-independent bug reports.
ActiveRecord::Base.establish_connection(
  adapter: "mysql2",
  host: "localhost",
  database: "test"
)
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table "payments", force: :cascade do |t|
    t.datetime "date"
    t.datetime "created_at"
    t.datetime "updated_at"
  end
end

class Payment < ActiveRecord::Base

end

class Payment2 < Payment

end

class BugTest < Minitest::Test
  def test_return_as_date
    Payment.table_name = 'payments'
    Payment2.table_name = 'invalid'
    puts Payment2.table_name
    Payment2.first
    # error => ActiveRecord::StatementInvalid: Mysql2::Error: Table 'test.invalid' doesn't exist: SHOW FULL FIELDS FROM `invalid`
  end
end
```

**Comment by fanjieqi** [comment]
@uaihebert , The difference between yours and mine is that you make the Payment2 inherits from the Payment which there is a "payments" table, but i make the Payment2 inherits from the "Payment1". And then, nothing would trigger when the payments table is empty. When you create a payments record, the exception shows the table name is "payment1s", not the "payments".

```
begin
  require "bundler/inline"
rescue LoadError => e
  $stderr.puts "Bundler version 1.10 or later is required. Please update your Bundler"
  raise e
end

gemfile(true) do
  source "https://rubygems.org"
  gem "rails"
  gem 'mysql2'
end

require "active_record"
require "minitest/autorun"
require "logger"

# This connection will do for database-independent bug reports.
ActiveRecord::Base.establish_connection(
  adapter: "mysql2",
  host: "localhost",
  database: "test"
)
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table "payments", force: :cascade do |t|
    t.datetime "date"
    t.datetime "created_at"
    t.datetime "updated_at"
  end
end

class Payment < ActiveRecord::Base
end



class Payment1 < ActiveRecord::Base

end

class Payment2 < Payment1

end

class BugTest < Minitest::Test
  def test_return_as_date1
    Payment2.table_name = 'payments'
    puts Payment2.first
  end

  def test_return_as_date2
    Payment.create(date: Date.today)
    Payment2.table_name = 'payments'
    puts Payment2.first
    # error ActiveRecord::StatementInvalid: Mysql2::Error: Table 'test.payment1s' doesn't exist: SHOW FULL FIELDS FROM `payment1s`
  end
end

```

**Comment by uaihebert** [comment]
I see. I ran the updated code and I got no error. =/

Maybe is the rails/ruby version?

**Comment by fanjieqi** [comment]
@uaihebert , yeah, I've tried the ActiveRecord-5.0.0.1 which is right, and the exception would triggers in ActiveRecord-4.2.7.1.

**Comment by kamipo** [comment]
If `Payment1` doesn't have a concrete table, it should be `self.abstract_class = true`. Thoughts?
