### ISSUE TITLE
Running `rails console --sandbox` on macOS Sierra results in a Segfault

### ISSUE THREAD

**Issue by rr1000** [rails/rails#26609]
### Steps to reproduce
1. Have a running copy of macOS 10.12
2. Create a new rails 5.0.0.1 app
3. Run `$ rails console --sandbox`

Other than that I'm not sure what else to report. It's a brand new app that I created this morning. I wasn't having any other issues until I upgraded to Sierra. You can see the full output at the bottom of this message.

### Expected behavior
The sandbox console should load as expected

### Actual behavior
Segfault

### System configuration
**5.0.0.1**:

**Ruby version**:
ruby 2.3.1p112 (2016-04-26 revision 54768) [x86_64-darwin15]

```
$ rails console --sandbox
Running via Spring preloader in process 79660
/usr/local/lib/ruby/gems/2.3.0/gems/activerecord-5.0.0.1/lib/active_record/connection_adapters/sqlite3_adapter.rb:27: [BUG] Segmentation fault at 0x00000000000110
ruby 2.3.1p112 (2016-04-26 revision 54768) [x86_64-darwin15]
```

Not sure if the control frame or backtrace info is needed, but I can post that if so. Any help or insight into fixing this issue is greatly appreciated.

### Update:
I'm seeing the same Segfault when running anything in the production console:

```
irb(main):002:0> User.all
/usr/local/lib/ruby/gems/2.3.0/gems/activerecord-5.0.0.1/lib/active_record/connection_adapters/sqlite3_adapter.rb:27: [BUG] Segmentation fault at 0x00000000000110
ruby 2.3.1p112 (2016-04-26 revision 54768) [x86_64-darwin15]
```

**Comment by sgrif** [comment]
This appears to be a bug in the sqlite3 gem, not Rails.

**Comment by ccasabona** [comment]
Getting error:

`activerecord-5.0.0.1/lib/active_record/connection_adapters/sqlite3_adapter.rb:27: [BUG] Segmentation fault at 0x00000000000110`
`ruby 2.3.1p112 (2016-04-26 revision 54768) [x86_64-darwin16]`

when making changes to the source code between running tests.  The error does not occur in development mode.  The command:

`rails console --sandbox`

works fine.  

Solution is to close the terminal and reopen.  Problem reoccurs when change is made to source code and a test is run, whether it is a single test, as in `rails test test/models/user_test`, or running all the tests with `rails test`.  It does not occur when running a group of tests, as in `rails test:models`

New rails app using Rails 5.0.0.1, Ruby 2.3.1, Mac OS Sierra 10.12.

**Comment by ccasabona** [comment]
See sqlite3 gem issues SIGABRT on OSX 10.12 (Sierra) after fork() for a fix

**Comment by drhectapus** [comment]
I have the same problem. How do I fix?

**Comment by ccasabona** [comment]
I fixed this by uninstalling the sqlite3 gem and reinstalling it forcing ruby to use the version installed by brew.

gem uninstall sqlite3

gem install sqlite3 -- --with-sqlite3-include=/usr/local/Cellar/sqlite/3.14.2_1/include --with-sqlite3-lib=/usr/local/Cellar/sqlite/3.14.2_1/lib

regards,
Charlie

**Comment by ccasabona** [comment]
Actually, this no longer necessary.  The gem author has pushed a new version, 1.3.12, that incorporates the fix (I should have read all my emails this morning before responding to you).

**Comment by uestcsp** [comment]
@ccasabona , i use sqlite3 (1.3.12), but the issue occur again

**Comment by ccasabona** [comment]
Did you try it with this command:

gem install sqlite3 -- --with-sqlite3-include=/usr/local/Cellar/sqlite/3.14.2_1/include --with-sqlite3-lib=/usr/local/Cellar/sqlite/3.14.2_1/lib

**Comment by uestcsp** [comment]
@ccasabona ,no , i didn't try that command...

**Comment by terryjray** [comment]
similar issue:

rails console --sandbox 

just hangs indefinitely until I kill it. rails s works fine, etc...

rails 5.0.0.1
ruby 2.3.2

**Comment by sgrif** [comment]
This is not a rails issue. Any information in the context of rails has already been stated on this thread.
