### ISSUE TITLE
Incorrect output from rails routes when using singular resources

### ISSUE THREAD

**Issue by roberts1000** [rails/rails#26606]
In a Rails 5.0.0.1 app, I have an `app/controllers/profiles_controller.rb` with a single `show` action.  In routes.rb I have

``` ruby
resource :profile
```

When I run `rails routes | grep profile`, I get the following output:

``` bash
     profile POST   /profile(.:format)                                 profiles#create
 new_profile GET    /profile/new(.:format)                             profiles#new
edit_profile GET    /profile/edit(.:format)                            profiles#edit
             GET    /profile(.:format)                                 profiles#show
             PATCH  /profile(.:format)                                 profiles#update
             PUT    /profile(.:format)                                 profiles#update
             DELETE /profile(.:format)                                 profiles#destroy
```

This output looks wrong to me with respect to the `show` action so  I tried calling the `profile_path` helper via GET and it routed to the correct controller's show action.  The output implies I should be using `edit_profile_path` with GET.

When I look a the plural routes generated by using `resources :profiles`, I get

``` bash
    profiles GET    /profiles(.:format)                                profiles#index
            POST    /profiles(.:format)                                profiles#create
 new_profile GET    /profiles/new(.:format)                            profiles#new
edit_profile GET    /profiles/:id/edit(.:format)                       profiles#edit
     profile GET    /profiles/:id(.:format)                            profiles#show
           PATCH    /profiles/:id(.:format)                            profiles#update
             PUT    /profiles/:id(.:format)                            profiles#update
          DELETE    /profiles/:id(.:format)                            profiles#destroy
```

This obviously looks correct.  In this version `show`,`update` and `destroy` are tied to `profile_path`.  However, in the singular form, they're _shown_ tied to `edit_profile_path`.   

Since, `profile_path` works as expected in the actual code, it looks like this is an ordering problem in the `rails routes` output.  Logically, it doesn't make sense to call a path helper starting with `edit_` when we're trying to "show" a resource or "destroy" a resource.  Should't the correct output look more like

``` bash
 new_profile GET    /profile/new(.:format)                             profiles#new
edit_profile GET    /profile/edit(.:format)                            profiles#edit
     profile GET    /profile(.:format)                                 profiles#show 
             POST   /profile(.:format)                                 profiles#create
             PATCH  /profile(.:format)                                 profiles#update
             PUT    /profile(.:format)                                 profiles#update
             DELETE /profile(.:format)                                 profiles#destroy
```

Lastly, if I use

``` ruby
resource :profile, only: [:show]
```

I get the following output

``` bash
profile GET    /profile(.:format)                                 profiles#show
```

**Comment by maclover7** [comment]
Hi @roberts1000, thank you for reporting this! I am able to reproduce this on the master branch using [this reproduction script](https://gist.github.com/maclover7/3f28f1236ee0a84309ef7c6d9f486bf2). To me, it seems like the issue is with the ordering of the routes. The `POST /profile` route is loaded in before the `GET /profile` route, meaning that when the aforementioned GET route tries to reserve a new route name, it has already been taken by the POST route. Not sure what the best recourse here is. 😬

**Comment by roberts1000** [comment]
Thank you for confirming.
