### ISSUE TITLE
Guides: incorrect example in functional tests section

### ISSUE THREAD

**Issue by mjhoy** [rails/rails#26602]
(If I'm not misunderstanding something, I can write up a PR for this.)

### Steps to reproduce

See section on controller tests in the guides at: https://github.com/rails/rails/blob/master/guides/source/testing.md#what-to-include-in-your-functional-tests

### Expected behavior

The guides suggest you can refer to a controller action in your controller tests:

```
Example: Calling the :show action, passing an id of 12 as the params and setting HTTP_REFERER header:

get :show, params: { id: 12 }, headers: { "HTTP_REFERER" => "http://example.com/home" }
```

### Actual behavior
This is no longer supported AFAIK, e.g.,`get :show` in a controller test now yields the exception:

```
URI::InvalidURIError: bad URI(is not URI?): http://www.example.com:80show
```
### System configuration

**Rails version**: 5.0.0.1

**Ruby version**: 2.3.1p112

**Comment by prathamesh-sonpatki** [comment]
Thanks @mjhoy, can you please send PR to fix it?
