### ISSUE TITLE
ActiveModel#define_attribute_methods is overrided by ActiveRecord#define_attribute_methods

### ISSUE THREAD

**Issue by Edouard-chin** [rails/rails#26624]
Note sure if I'm allowed to use `ActiveModel#define_attributes_methods` on a ActiveRecord object.
Feel free to close this issue if I'm using this incorrectly.

### Steps to reproduce

```ruby
class Post < ActiveRecord::Base
  has_many :comments

  attribute_method_suffix '_before'
  attribute_method_suffix '_after'
  define_attribute_methods 'credential1_encrypted', 'name'


  def attribute_before(attr)
    arguments_changes[attr.to_s].try(:[], 0)
  end

  def attribute_after(attr)
    arguments_changes[attr.to_s].try(:[], 1)
  end
end
```

This raises an exception `wrong number of arguments (2 for 0) (ArgumentError)` as we are trying to call [ActiveRecord#attribute_methods](https://github.com/rails/rails/blob/master/activerecord/lib/active_record/attribute_methods.rb#L55) instead of [ActiveModel#attribute_methods](https://github.com/rails/rails/blob/master/activemodel/lib/active_model/attribute_methods.rb#L252)

I'm however able to call the singular version of the method [define_attribute_method](https://github.com/rails/rails/blob/master/activemodel/lib/active_model/attribute_methods.rb#L285)

### System configuration
**Rails version**:
4.2.7.1

**Ruby version**:
2.3

**Comment by maclover7** [comment]
Dup of #26533 :)
