### ISSUE TITLE
 El sistema no puede encontrar la ruta especificada ruby rails

### ISSUE THREAD

**Issue by quicklergsg** [rails/rails#26621]
### Steps to reproduce

(Guidelines for creating a bug report are [available
here](http://guides.rubyonrails.org/contributing_to_ruby_on_rails.html#creating-a-bug-report))

### Expected behavior
Tell us what should happen

### Actual behavior
Tell us what happens instead

### System configuration
**Rails version**:

**Ruby version**:

**Comment by maclover7** [comment]
¿Puede elaborar con más información y también con instrucciones para reproducir? ¡Gracias!
