### ISSUE TITLE
Differing schema.rb under mysql 5.7 and utf8mb4 text columns

### ISSUE THREAD

**Issue by YesThatAllen** [rails/rails#26623]
### Steps to reproduce

This situation has similar symptoms to the case described in [issue #7252](https://github.com/rails/rails/issues/7252#issuecomment-7487098). In this case, it's happening to `text` columns in `utf8mb4` tables, in mysql 5.7 (this is not happening with mysql 5.6)

To reproduce: 
Define a migration to create a column with a kind of `text`.

```
class CreateMenuItemTemplates < ActiveRecord::Migration
  def change
    create_table :menu_item_templates do |t|
      t.text :url
```

The resulting schema.rb file shows a length of `65535` 

When using mysql 5.7, performing rake db:migrate results in a change to the schema.rb, showing a length of `16777215`
### Expected behavior

I would expect the schema.rb file to be 

`t.text     "url",         limit: 65535`
### Actual behavior

The schema.rb file shows

`t.text     "url",         limit: 16777215`
### System configuration

**Rails version**: '4.2.7.1'

**Ruby version**: `ruby 2.3.1p112 (2016-04-26 revision 54768) [x86_64-darwin16]`

**mysql version:**  5.7.11

**Comment by jsnick** [comment]
I have had a exactly same issue in Rails 5.0.0.1 , mysql 5.7 utf8mb4.
I can't change the limit of text column T^T. 
If I execute db:migrate for changing a limit of text column, then only schema.rb version is changed.
And I can insert text over new length limit.

**Comment by madkumamon** [comment]
@here SO no response how to fix this ?
