### ISSUE TITLE
compatibility of default uuid generating with postgresql extension

### ISSUE THREAD

**Issue by helperhaps** [rails/rails#26639]
I am new here. And I am lost here.

**Ruby: 2.3.1p112 installed by rbenv**
**Rails: 5.0.0.1 installed by gem**

According to https://github.com/rails/rails/compare/f94e328cf801...5a47639aac45?diff=unified&name=5a47639aac45 I got to know that if I do the following addition, 

``` ruby
# config/application.rb
config.generators do |g|
  g.orm :active_record, primary_key_type: :uuid
end
```

then all my migration will be tag on `id: :uuid` to the `create_table` method.

Amd it works so well with postgresql's uuid-ossp extension. When generate a user model It will get

``` ruby
def change
    create_table :users, id: :uuid do |t|

      t.timestamps
    end
  end
```

And we know that there is another extension can do the same thing which is `pgcrypto`

If use the pgcrypto extension, the `$ rails db:migrate` will be failed with a error `PG::UndefinedFunction: ERROR:  function uuid_generate_v4() does not exist`. The reason is obviously, couse the default generate method of uuid is `uuid_generate_v4()` (ref:https://github.com/rails/rails/issues/20518). To fix that need to edit the phase by hands (just add " default: 'gen_random_uuid()' by hands")

``` ruby
create_table :users, id: :uuid, default: 'gen_random_uuid()' do |t|
```

But if have to do this, It is no use for the default uuid generation configuration above.

So how to do with it? Or Rails can handle that situation but i did't get?

hope to make myself understood.

**Comment by bdewater** [comment]
Fixed by #25395
