### ISSUE TITLE
ActiveRecord::RecordNotFound message vagueness

### ISSUE THREAD

**Issue by oss92** [rails/rails#26645]
**Severity: cosmetic**
#### Example

```
class Order
   scope :executed, -> { where(status: 1) }
end

Order.executed.find(100) # id that is not found with executed status

# => ActiveRecord::RecordNotFound: Couldn't find Order with 'id'=100 [
# => WHERE (`orders`.`status` != ?) AND `orders`.`status` = ?]
```
### Expected behavior

The `arel` where sql is printed here and may be vague sometimes (especially when using a bug reporting tool). The question marks should be replaced with the correct values in the query. AFAIK it was already there pre Rails 5.
### Actual behavior

<img width="791" alt="record_not_found" src="https://cloud.githubusercontent.com/assets/6284234/18891861/71e79e48-8507-11e6-812f-023da65b1871.png">
### System configuration

**Rails version**: 5.0.0.1

**Ruby version**:  2.3.1

**Comment by maclover7** [comment]
cc @sgrif
