### ISSUE TITLE
rails c  doesn't start the rails console.

### ISSUE THREAD

**Issue by prasadsurase** [rails/rails#26658]
I am not able to load the rails console.

```ruby
$ ruby -v
ruby 2.2.4p230 (2015-12-16 revision 53155) [x86_64-darwin15]
~/opensource/intranet(master)*$ rails -v
Rails 4.2.0
$ rails s
=> Booting Thin
=> Rails 4.2.0 application starting in development on http://localhost:3000
=> Run `rails server -h` for more startup options
=> Ctrl-C to shutdown server
Thin web server (v1.6.2 codename Doc Brown)
Maximum connections set to 1024
Listening on localhost:3000, CTRL+C to stop
^CStopping ...
Exiting
$ rails c
/Users/prasad/.rvm/rubies/ruby-2.2.4/lib/ruby/2.2.0/irb/completion.rb:9:in `require': dlopen(/Users/prasad/.rvm/rubies/ruby-2.2.4/lib/ruby/2.2.0/x86_64-darwin15/readline.bundle, 9): Library not loaded: /usr/local/opt/readline/lib/libreadline.6.dylib (LoadError)
  Referenced from: /Users/prasad/.rvm/rubies/ruby-2.2.4/lib/ruby/2.2.0/x86_64-darwin15/readline.bundle
  Reason: image not found - /Users/prasad/.rvm/rubies/ruby-2.2.4/lib/ruby/2.2.0/x86_64-darwin15/readline.bundle
	from /Users/prasad/.rvm/rubies/ruby-2.2.4/lib/ruby/2.2.0/irb/completion.rb:9:in `<top (required)>'
	from /Users/prasad/.rvm/gems/ruby-2.2.4/gems/railties-4.2.0/lib/rails/commands/console.rb:3:in `require'
	from /Users/prasad/.rvm/gems/ruby-2.2.4/gems/railties-4.2.0/lib/rails/commands/console.rb:3:in `<top (required)>'
	from /Users/prasad/.rvm/gems/ruby-2.2.4/gems/railties-4.2.0/lib/rails/commands/commands_tasks.rb:123:in `require'
	from /Users/prasad/.rvm/gems/ruby-2.2.4/gems/railties-4.2.0/lib/rails/commands/commands_tasks.rb:123:in `require_command!'
	from /Users/prasad/.rvm/gems/ruby-2.2.4/gems/railties-4.2.0/lib/rails/commands/commands_tasks.rb:58:in `console'
	from /Users/prasad/.rvm/gems/ruby-2.2.4/gems/railties-4.2.0/lib/rails/commands/commands_tasks.rb:39:in `run_command!'
	from /Users/prasad/.rvm/gems/ruby-2.2.4/gems/railties-4.2.0/lib/rails/commands.rb:17:in `<top (required)>'
	from bin/rails:4:in `require'
	from bin/rails:4:in `<main>'
```

### Expected behaviour
Rails console should be loaded for **rails c**

### Actual behaviour
Rails console doesnt load on **rails c**.

### System configuration
**Rails version**: 4.2.0
**Ruby version**: 2.2.4p230 (2015-12-16 revision 53155) [x86_64-darwin15]

**Comment by prathamesh-sonpatki** [comment]
This is not an issue related to Rails. See how to solve issues with rvm and readline. You will face this issue with any other gem which tries to use readline as well as the issue with your Ruby installation.

Thanks!

**Comment by jeffrey008** [comment]
@prasadsurase, I am also facing this issue now. Although it is not a Rails issue, can you please shed some light on this problem? Googled around and SO solution did not work out. Thanks

**Comment by prasadsurase** [comment]
@jeffrey008 I imploded the RVM and reinstalled it.

**Comment by LegaKh** [comment]
works for me:
``ln -s /usr/local/opt/readline/lib/libreadline.7.0.dylib /usr/local/opt/readline/lib/libreadline.6.dylib``

**Comment by enderahmetyurt** [comment]
Add 'rb-readline' gem to your Gemfile in development group and install it. It's the easiest solution for silly "readline" errors. [Other solutions](http://stackoverflow.com/questions/16756287/cannot-execute-rails-console) didn't work for me. :(

**Comment by zhangda89** [comment]
@LegaKh why libreadline.6.dylib not libreadline.7.dylib

**Comment by ALFmachine** [comment]
enderahmetyurt comment worked for me. thanks

**Comment by bparanj** [comment]
Thanks @enderahmetyurt. It works!

**Comment by jusopi** [comment]
I had to use @enderahmetyurt's solution first and then create the symlink using @LegaKh's suggestion.

**Comment by jackalcooper** [comment]
@LegaKh 's solution works for me

**Comment by keesbriggs** [comment]
@LegaKh 's solution works for me too

**Comment by victorhazbun** [comment]
@LegaKh 's solution works for me too

**Comment by alobban** [comment]
Thanks @enderahmetyurt. It definitely was the easiest solution!

**Comment by kasiaul** [comment]
I was installing other framework & it caused the same error.

Thanks @enderahmetyurt. It works now!

**Comment by kasiaul** [comment]
@enderahmetyurt it is a great solution for rails c but irb requires different one.

**Comment by jd1386** [comment]
@enderahmetyurt and @LegaKh 's solution did the trick. Thanks.

**Comment by cmolenda** [comment]
My case, sidekiq wouldn't start.
- `ruby` installed via `rbenv` (`rbenv-build`)
- `readline` installed via `brew` (Homebrew)

I unwisely did a `brew update` which changed my `readline` installation to one that my `ruby` install was not compiled with.

My steps to correction:
_Note: for good measure, I rehashed rbenv `rbenv rehash` and started a new terminal session after just about every step._
1. Uninstall offending version of ruby (2.2.0): `rbenv uninstall 2.2.0`
2. Made sure homebrew had installed readline: `brew install readline`
3. Reinstall ruby (2.2.0) with brew readline linkage: `rbenv install 2.2.0`
4. Install bundler: `gem install bundler`
5. Install gem bundle (assumes Gemfile): `bundle`

**Comment by cdeliens** [comment]
Just reinstall your current ruby version, worked for me on ruby 2.1.2

**Comment by ringuete** [comment]
gem 'rb-readline'
 as enderahmetyurt  said works fine for rails console.

**Comment by eyelean7** [comment]
enderahmetyurt has a good solution for allowing use of the rails console. for me, psql also was not working but using LegaKh's solution fixed the problem.

**Comment by codepedia** [comment]
Adding  "gem 'rb-readline' "  to my gem file and bundling fixed the issue. Thanks enderahmetyurt

**Comment by victorhazbun** [comment]
@enderahmetyurt give this man a beer

**Comment by Nmuta** [comment]
@LegaKh 's solution works for me

**Comment by alejandrotoro** [comment]
@LegaKh 's solution also worked for me, thank you!

**Comment by saxxi** [comment]
Fyi @LegaKh's solution still applies, I had to do:

```
ln -s /usr/local/opt/readline/lib/libreadline.8.0.dylib /usr/local/opt/readline/lib/libreadline.7.dylib
```

**Comment by ziomio** [comment]
Thanks @saxxi, your solution works!

**Comment by bloudermilk** [comment]
@cmolenda reinstalling Ruby is what did it for me. Homebrew must have decided to upgrade readline without me knowing, which broke Ruby. Yay development tooling!

**Comment by ctsstc** [comment]
If you're using `rvm` you can run this to reinstall the current version which worked for me :) 

```bash
rvm reinstall $(rvm current)
```

**Comment by WebAhmed** [comment]
> works for me:
> `ln -s /usr/local/opt/readline/lib/libreadline.7.0.dylib /usr/local/opt/readline/lib/libreadline.6.dylib`
> 
> 16/01/2019 @saxxi upd:
> `ln -s /usr/local/opt/readline/lib/libreadline.8.0.dylib /usr/local/opt/readline/lib/libreadline.7.dylib`

@saxxi Thank you. That worked for me as well!

**Comment by thiagotcezar** [comment]
Awesome! Thank you

**Comment by iarobinson** [comment]
For me, this problem was solved by addressing some Gemfile duplicates. 

If you don't want to add another gem, you might want to run `bundle` and see if any warnings exist there. Addressing the issues I found in bundle fixed this issue for me.

**Comment by ibrahimelbanna** [comment]
thanks @LegaKh  Your solution worked for me

**Comment by quyle1703** [comment]
@enderahmetyurt I just wanna say thank you man! Your solution works!!!

**Comment by adampal** [comment]
Thanks @cdeliens, Just reinstalling the ruby version worked for me. 
I ran:
`rvm reinstall --disable-binary 2.5.3`

**Comment by WillDeuz** [comment]
> Add 'rb-readline' gem to your Gemfile in development group and install it. It's the easiest solution for silly "readline" errors. [Other solutions](http://stackoverflow.com/questions/16756287/cannot-execute-rails-console) didn't work for me. :(

All hail King of Fixes

**Comment by romenigld** [comment]
ln -s /usr/local/opt/readline/lib/libreadline.8.0.dylib /usr/local/opt/readline/lib/libreadline.7.dylib

**Comment by akeating** [comment]
As others have mentioned possibly the version of `readline` you have installed has changed from that originally used in the initial `ruby` installation. Simply reinstall `ruby`:

If you use `brew` and `rbenv`, read on.

Make sure `readline` is installed:
```
$ brew install readline
```
Reinstall `ruby` with your desired version, in this case `2.5.1`:
```
$ rbenv install 2.5.1 --force
ruby-build: use openssl from homebrew
Downloading ruby-2.5.1.tar.bz2...
-> https://cache.ruby-lang.org/pub/ruby/2.5/ruby-2.5.1.tar.bz2
Installing ruby-2.5.1...
ruby-build: use readline from homebrew
Installed ruby-2.5.1 ...
```

**Comment by ErnestPH** [comment]
This still works. Thanks guys!
ln -s /usr/local/opt/readline/lib/libreadline.8.0.dylib /usr/local/opt/readline/lib/libreadline.7.dylib

**Comment by newtorob** [comment]
Same issue, 

ln -s /usr/local/opt/readline/lib/libreadline.8.0.dylib /usr/local/opt/readline/lib/libreadline.7.dylib

works perfectly

**Comment by danieldimitrov** [comment]
The same problem here. What helped in the end was: 

```
brew upgrade readline
rvm reinstall VERSION
```

**Comment by shamimevatix** [comment]
Thanks @LegaKh your solution saved my day.

**Comment by juniorgarcia** [comment]
> My case, sidekiq wouldn't start.
> 
>     * `ruby` installed via `rbenv` (`rbenv-build`)
> 
>     * `readline` installed via `brew` (Homebrew)
> 
> 
> I unwisely did a `brew update` which changed my `readline` installation to one that my `ruby` install was not compiled with.
> 
> My steps to correction:
> _Note: for good measure, I rehashed rbenv `rbenv rehash` and started a new terminal session after just about every step._
> 
>     1. Uninstall offending version of ruby (2.2.0): `rbenv uninstall 2.2.0`
> 
>     2. Made sure homebrew had installed readline: `brew install readline`
> 
>     3. Reinstall ruby (2.2.0) with brew readline linkage: `RUBY_CONFIGURE_OPTS=--with-readline-dir="$(brew --prefix readline)" rbenv install 2.2.0`
>        _More on this: https://github.com/rbenv/ruby-build/wiki_
> 
>     4. Install bundler: `gem install bundler`
> 
>     5. Install gem bundle (assumes Gemfile): `bundle`

This solution worked for me working with a Docker image of `ruby:2.6`. I wonder why I had to do that on my host machine so that my entrypoint configured as `irb` could work.

**Comment by tashi-179** [comment]
Actually the problem is because of version mismatch between bundler and ruby.
So for ruby version less than 2.5 recommended bundler version less than 2.
Eg:- If my ruby version is 2.3.1
I need to use bundler version 1.7 or any other version less than 2.

1. `gem uninstall bundler`
1. `gem install bundler -v '1.7'`

**Comment by AlexanderZaytsev** [comment]
Had this problem after upgrading ubuntu from 18.04 to 20.04. Reinstalling Ruby helped.

**Comment by git4ruby** [comment]
`ln -s /usr/local/opt/readline/lib/libreadline.8.0.dylib /usr/local/opt/readline/lib/libreadline.7.dylib`

Run above code and then run `rails c `

Then it should work.

**Comment by smcaleese** [comment]
I fixed by console with `gem install ffi` and then `bundle update`.
