### ISSUE TITLE
can't find docs for with_transaction_returning_status 

### ISSUE THREAD

**Issue by mcfiredrill** [rails/rails#26656]
I noticed I can't find the docs for `with_transaction_returning_status` when searching on api.rubyonrails.org anymore.

It was available in older doc versions:
http://api.rubyonrails.org/v3.2.2/classes/ActiveRecord/Transactions.html#method-i-with_transaction_returning_status

Its public and not `:nodoc:` ed so I'm not sure what the reason is.
https://github.com/rails/rails/blob/0fe76197d2622674e1796a9a000995a7a1f6622b/activerecord/lib/active_record/transactions.rb#L390

**Comment by maclover7** [comment]
Can confirm this. cc @fxn

**Comment by fxn** [comment]
This is an internal method [I wrote myself years ago](https://github.com/rails/rails/commit/e02f0dcc24f871d8429229db4219ee1e93636496), should not belong to the public interface.

**Comment by mcfiredrill** [comment]
@fxn Thanks. Is there any alternative method to use, if this is not supposed to be public?

**Comment by matthewd** [comment]
@arthurnn  Looks like #18102 `nodoc`-ed a lot more than it intended to. 🙊 

@mcfiredrill You probably just want to raise `ActiveRecord::Rollback` (or a "regular" exception) inside a `transaction` block. If you require the transaction-membership semantics of `with_transaction_returning_status`, I guess we'd need to better understand your use case.

**Comment by mcfiredrill** [comment]
@matthewd Makes sense, thanks.
