### ISSUE TITLE
ActiveRecord - Model + Not + Scope

### ISSUE THREAD

**Issue by francesco-loreti** [rails/rails#26668]
As for "where.not", Is it possible you can add ".not" to a scope?
For example: "User.all.active" ---> "User.all.not.active", where "active" is a scope.

Thanks

**Comment by prathamesh-sonpatki** [comment]
@francesco-loreti 

Please use stackoverflow or other medium for posting questions where a wider community can help you, we reserve the issue tracker for bug reports only, thanks!
