### ISSUE TITLE
Two controllers with different filenames, but identical classnames doesn't error

### ISSUE THREAD

**Issue by bentedder** [rails/rails#26673]
### Steps to reproduce
* Create a resourceful route (ie, `resources: :groupings`)
* Create 2 files with different names (ie, groupings_controller.rb and not_groupings_controller.rb)
* At the top of each put `class GroupingsController < ApplicationController`

### Expected behavior
Something should error out that two files are trying to control the same controller.

### Actual behavior
On my local box (in dev and prod env) I was getting the groupings_controller#index action. When hosting the rails app (on heroku) it was directing me to the not_groupings_controller#index action. I saw no errors, nothing awry. Just took digging through my files and realizing not_groupings_controller.rb still existed. Deleting the file fixes. But an error should come up that there are competing controllers?

### System configuration
**Rails version**: 5

**Ruby version**: 2.3.0

**Comment by maclover7** [comment]
cc @fxn

**Comment by matthewd** [comment]
Not much we can do about this.

If you reference `NotGroupingsController` it'll show an error because `not_groupings_controller.rb` didn't define it. But if you don't, we never load that file in development... and in production, during eager load, we have no control over what's happening.

**Comment by pixeltrix** [comment]
@bentedder this is just standard class re-opening in Ruby - as @matthewd says, nothing we can do about it.
