### ISSUE TITLE
Actionmailer sends emails with empty content

### ISSUE THREAD

**Issue by ahmadalisaeed** [rails/rails#26670]
NOTE: To be honest, we were never able to replicate the errors in any browser, but our users are complaining and receiving the emails with empty contents and we can also see in our backup email client the emails send by our users has empty contents.
 
### Situation 
In our ExternalMailer class we have a class method called 'send_quote_request'  and which is extended by  ApplicationMailer. 

The ApplicationMailer is
```ruby
class ApplicationMailer < ActionMailer::Base
  default layout: 'application_mailer'  
end
```
Inside the 'send_quote_request' method we are calling the method 'mail'

```ruby
mail( to: email,
          subject: I18n.t('mailer.subject.send_quote_request'),
          content_type: "text/html"
         )
```
We are using the sidekiq worker in order to send those emails

In our system, we have stored the records of the user who had sent the messages and when we try to send those messages by using the Rails console then the mail is send properly (The email body is not empty and which is fine). 

### Expected behavior
It should send email with content which is in send_quote_request.html.haml

### Actual behavior
It is sending empty emails sometimes in production

### System configuration
**Rails version**:
4.2.6
**Ruby version**:
ruby 2.2.0p0 (2014-12-25 revision 49005) [x86_64-linux]

**Comment by maclover7** [comment]
Can you please provide more information to reproduce the problem? Creating a sample application that replicates the error you are seeing would be very helpful. :)

**Comment by jeremy** [comment]
You're sending an HTML-only email which is commonly classified as junk/spam, has its HTML part stripped, or is simply mis-rendered.

- Ask your users who receive "blank" emails for a copy of the actual raw message so you can troubleshoot further.
- Render a text part in addition to the HTML part to guarantee your emails can be read.

**Comment by ahmadalisaeed** [comment]
![email](https://cloud.githubusercontent.com/assets/18677747/19074304/d9edf662-8a3f-11e6-96a0-5687a461f367.png)

@jeremy This is the raw messages which are blank. In the email templates besides HTML we also have the plain text and based on the raw messages we can say that the plain text also does not exists

@maclover7 The problem is we cannot produce this issue is our development but it is happening on run time (production). I do not think making a simple app helps us to further investigate this issue.

**Comment by prcongithub** [comment]
This is happening with me as well.
