### ISSUE TITLE
Recurrence of New app: "key must be 32 bits"

### ISSUE THREAD

**Issue by jonlumb** [rails/rails#26694]
### Steps to reproduce
Fresh install of Ruby 2.4.0preview2 and Rails 5.0.0.1
Create new app, generate a basic scaffold, run db:migrate, navigate to the scaffold overview page and re-encounter this issue (although the "Welcome to Rails" index page still works):

https://github.com/rails/rails/issues/25185

### Expected behavior
Should load scaffold overview

### Actual behavior
Error message: "Key must be 32bytes"

### System configuration
**Rails version**: 5.0.0.1

**Ruby version**: 2.4.0preview2

**Comment by prathamesh-sonpatki** [comment]
It has been fixed by https://github.com/rails/rails/pull/25758 and will be available to use when Rails 5.0.1 is released, thanks for the report!

**Comment by ZuzannaSt** [comment]
@prathamesh-sonpatki Got the same issue with Ruby 2.4.0 and Rails 5.0.1.

**Comment by vipulnsward** [comment]
Can you share an example App with this issue?
This has been fixed with the 5.0.1 release.

**Comment by ZuzannaSt** [comment]
Hey @vipulnsward, sorry, my mistake. The issue I have is introduced by `attr_encrypted/encryptor` gem. Here's a link: https://github.com/attr-encrypted/encryptor/issues/26.
