### ISSUE TITLE
Deleting STI records performs badly due to scoping first on type

### ISSUE THREAD

**Issue by mockdeep** [rails/rails#26691]
### Steps to reproduce

I have an STI table called `fields`, but deleting records from this table is painfully slow. If I simply find a field and try to delete it, I get a query that first filters on the field type, then on the id:

```
SQL (3853.6ms)  DELETE FROM "fields" WHERE "fields"."type" IN ('DropdownField') AND "fields"."id" = 1859476  [["id", 1859476]]
```

### Expected behavior

The query should query on id before type. Not sure if it makes sense to filter on type at all.

### System configuration

**Rails version**: 4.2.7.1

**Ruby version**: 2.3.1

**Comment by mockdeep** [comment]
This compounds if I try to delete a number of records:

```
SQL (198949.1ms)  DELETE FROM "fields" WHERE "fields"."type" IN ('SignatureField') AND "fields"."doc_id" IN (14912, 14911, 14910, 14909, 14908, 14907, 14906, 14905, 14904, 14903, 14902, 14901, 14900, 14899, 14898, 14897, 14896, 14895, 14894, 14893, 14892, 14891, 14890, 14889, 14888, 14887, 14886, 14885, 14884, 14883, 14882, 14881, 14880, 14879, 14878, 14877, 14876, 14875, 14874, 14873, 14872, 14871, 14870, 14869, 14868, 14867, 14866, 14865, 14864, 14863, 14862, 14861, 14860)
```

**Comment by maclover7** [comment]
Can you create an executable test script using one of the templates [here](https://github.com/rails/rails/tree/master/guides/bug_report_templates), that would demonstrate the problem you are seeing?

**Comment by mockdeep** [comment]
@maclover7 sure, the following reproduces it in the logs that come out, but not sure how to write a test around it:

```ruby
begin
  require "bundler/inline"
rescue LoadError => e
  $stderr.puts "Bundler version 1.10 or later is required. Please update your Bundler"
  raise e
end

gemfile(true) do
  source "https://rubygems.org"
  # Activate the gem you are reporting the issue against.
  gem "activerecord", "4.2.7.1"
  gem "sqlite3"
end

require "active_record"
require "minitest/autorun"
require "logger"

# Ensure backward compatibility with Minitest 4
Minitest::Test = MiniTest::Unit::TestCase unless defined?(Minitest::Test)

# This connection will do for database-independent bug reports.
ActiveRecord::Base.establish_connection(adapter: "sqlite3", database: ":memory:")
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :posts, force: true do |t|
  end

  create_table :comments, force: true do |t|
    t.integer :post_id
    t.string :type, null: false
  end
end

class Post < ActiveRecord::Base
  has_many :comments
end

class Comment < ActiveRecord::Base
  belongs_to :post
end

class VideoComment < Comment

end

class BugTest < Minitest::Test
  def test_association_stuff
    post = Post.create!
    VideoComment.create!(post: post)
    Comment.first.destroy
  end
end
```

**Comment by matthewd** [comment]
There is no "first" or "before" in an SQL query. 

If that first query is taking multiple seconds, it seems likely there's something else going on. Likely candidates would be a missing primary key index, concurrent query traffic (causing a lock wait), or a simply underpowered / resource-starved database server.

Unfortunately, none of those are Rails bugs to be fixed.

**Comment by mockdeep** [comment]
@matthewd I see. In this case we're dealing with a default sequential primary key in postgres, with no other queries happening at the same time, and every other query we make seems to perform just fine:

```
> DropdownField.find(1860626)
  DropdownField Load (1.9ms)  SELECT  "fields".* FROM "fields" WHERE "fields"."type" IN ('DropdownField') AND "fields"."deleted_at" IS NULL AND "fields"."id" = 1860626 LIMIT 1  [["id", 1860626]]
```

I do notice that the query above also has the `type` bit first as well, which confirms what you say about the order. Any other tips on debugging this? It seems to be specific to STI tables and `DELETE` queries. Deleting from other tables works just fine. All of the foreign keys are indexed, too.

**Comment by matthewd** [comment]
If you can confirm the raw queries perform similarly when run in `psql`, then you should be able to investigate it as a framework-agnostic PostgreSQL question.

You'll probably want to compare some `EXPLAIN` / `EXPLAIN ANALYZE` plans.. but that's pretty far outside what we can help you with. I've had good experiences with `#postgresql` on Freenode.

**Comment by mockdeep** [comment]
Ah, you know what. I think the problem is from elsewhere. We have a foreign key to our `fields` table from another table. We removed the index on that, since we never query for the other record that way, but it stands to reason that PostgreSQL is taking a peek at the other table before it can decide whether to delete the field record.
