### ISSUE TITLE
ActiveRecord relation delete regression

### ISSUE THREAD

**Issue by kirs** [rails/rails#26719]
```ruby
require 'bundler/setup'
require 'active_record'
require 'active_support/all'
require 'minitest/autorun'

ActiveRecord::Base.establish_connection(adapter: 'sqlite3', database: ':memory:')
ActiveRecord::Schema.define do
  create_table "products" do |t|
    t.string "title"
  end
end

class Product < ActiveRecord::Base;end

class RelationTest < ActiveSupport::TestCase
  def test_delete
    products = Product.all
    products.create!
    products.create!

    assert_equal [1, 2], products.pluck(:id)

    products.each(&:delete)
    assert_equal [], products.pluck(:id)
  end
end
```

The test passes on 4.2, but on `master` or `5-0-stable` I get:

```ruby
RelationTest#test_delete [kirs/ar_relation_delete.rb:25]:
Expected: []
  Actual: [1, 2]
```

@sgrif do we consider it as a regression in 5.0 or should it work like this by the design?

**Comment by maclover7** [comment]
@kirs Would you be able to do a git bisect to figure out where this behavior was changed? Thanks!

**Comment by matthewd** [comment]
Expected consequence of the fact `pluck` now uses the loaded contents of the relation where possible: this has the same (5.0+) behaviour if you use `map(&:id)` instead. Or throw a `products.reload` in there.

I guess there is the question of whether `Relation#delete` should kill the loaded state, but that would introduce a special case we can't generalize, so seems unlikely to be worth changing.
