### ISSUE TITLE
ActiveRecord::CounterCache methods should have an option to change updated_at

### ISSUE THREAD

**Issue by jtrost** [rails/rails#26724]
ActiveRecord::CounterCache should provide an option to update `updated_at` when any one of these methods are called.
- [update_counters](https://github.com/rails/rails/blob/a9dc45459abcd9437085f4dd0aa3c9d0e64e062f/activerecord/lib/active_record/counter_cache.rb#L76)
- [reset_counters](https://github.com/rails/rails/blob/a9dc45459abcd9437085f4dd0aa3c9d0e64e062f/activerecord/lib/active_record/counter_cache.rb#L20)
- [decrement_counter](https://github.com/rails/rails/blob/a9dc45459abcd9437085f4dd0aa3c9d0e64e062f/activerecord/lib/active_record/counter_cache.rb#L120)
- [increment_counter](https://github.com/rails/rails/blob/a9dc45459abcd9437085f4dd0aa3c9d0e64e062f/activerecord/lib/active_record/counter_cache.rb#L102)

My application implements a trash module, so I must call `decrement_counter` when sending a record to the trash, and `increment_counter` when restoring a record. I'm displaying a counter cache in a view, and I would like for the fragment cache to expire whenever I increment or decrement the counters by updating the `updated_at` value. However, I must make a second call to the database to update the `updated_at` value after incrementing or decrementing the counter cache.

I think there should be an additional argument to send to these methods to change `updated_at` when changing the counter cache. For example:

``` ruby
Post.decrement_counter(:comments_count, 1, true) # This would change the post's updated_at value
Post.decrement_counter(:comments_count, 1, false) # This would NOT change the post's updated_at value
Post.decrement_counter(:comments_count, 1) # This would NOT change the post's updated_at value
```
### Expected behavior

ActiveRecord::CounterCache should be able to change a record's `updated_at` value.
### Actual behavior

ActiveRecord::CounterCache does not have the ability to change a record's `updated_at` value.
### System configuration

**Rails version**: 4.2.5.1

**Ruby version**: 2.2.3

**Comment by maclover7** [comment]
👍 Agree that this functionality should be provided, although the API may be need some tweaking :)

Can you open up a PR with what you have so far for an implementation? Thanks!

**Comment by kaspth** [comment]
Fixed by https://github.com/rails/rails/compare/bf77e641ce807857fcf804250c4f8ce817ae66be^...19deeb08df6279a9cbf0c65548641776c0451471
