### ISSUE TITLE
rescue_from does not handle java exceptions in JRuby.

### ISSUE THREAD

**Issue by cshupp1** [rails/rails#26727]
### Steps to reproduce

Place this line in your rails app in the application controller:

```
rescue_from Exception, java.lang.Throwable, :with => :internal_error
```
### Expected behavior

It eats the java class under JRuby
It actually handles the exception
### Actual behavior

An exception will be thrown:

```
Java::JavaLang::Throwable is neither an Exception nor a String
```
### System configuration

**Rails version**: 4.2.5

**Ruby version**: JRuby 9.0.4

_Monkey patch_

```
#monkey patch to handle java exceptions
module ActiveSupport
  module Rescuable
    module ClassMethods
      def rescue_from(*klasses, &block)
        options = klasses.extract_options!

        unless options.has_key?(:with)
          if block_given?
            options[:with] = block
          else
            raise ArgumentError, "Need a handler. Supply an options hash that has a :with key as the last argument."
          end
        end

        klasses.each do |klass|
          key = if (klass.is_a?(Class) && ((klass <= Exception) || (klass <= java.lang.Throwable))) #monkey is here
                  klass.name
                elsif klass.is_a?(String)
                  klass
                else
                  raise ArgumentError, "#{klass} is neither an Exception nor a String"
                end

          # put the new handler at the end because the list is read in reverse
          self.rescue_handlers += [[key, options[:with]]]
        end
      end
    end
  end
end
```

**Comment by headius** [comment]
Seems like Rails could soften the requirement for rescued items to be either Exception or String.

What does a String do? Could we overload that to handle a Java exception?

**Comment by ryanfb** [comment]
For anyone else running across this issue, if you use the String form of the Java exception according to what you would get by calling `.name` on it (e.g. `'Java::JavaLang::Throwable'`), it should be supported: https://github.com/rails/rails/blob/20c91119903f70eb19aed33fe78417789dbf070f/activesupport/lib/active_support/rescuable.rb#L141-L151

Or [in Rails v4.2.5](https://github.com/rails/rails/blob/v4.2.5/activesupport/lib/active_support/rescuable.rb#L89-L101):
```
# The purpose of allowing strings in rescue_from is to support the
# declaration of handler associations for exception classes whose
# definition is yet unknown.
```
