### ISSUE TITLE
Getting started guide has some missing context/content

### ISSUE THREAD

**Issue by cjhenck** [rails/rails#26739]
This part of the getting started guide doesn't make sense.  In particular, the second paragraph I've included lists keys "locale", and "handlers", which are not in the error message as presented.  I got caught up at the locale sentence because nowhere prior in the documentation does it mention locale, including in the error message referenced.  Likewise with handlers.  In this case the error message doesn't actually seem to be a hash, but a specific printout of keys/fields within the request.

> ```
> ArticlesController#new is missing a template for this request format and variant. request.formats: ["text/html"] request.variant: [] NOTE! For XHR/Ajax or API requests, this action would normally respond with 204 No Content: an empty white screen. Since you're loading it in a web browser, we assume that you expected to actually render a template, not… nothing, so we're showing an error to be extra-clear. If you expect 204 No Content, carry on. That's what you'll get from an XHR or API request. Give it a shot.
> ```
> 
> ...
> 
> The next part of the message contains a hash. The :locale key in this hash simply indicates which spoken language template should be retrieved. By default, this is the English - or "en" - template. The next key, :formats specifies the format of template to be served in response. The default format is :html, and so Rails is looking for an HTML template. The final key, :handlers, is telling us what template handlers could be used to render our template. :erb is most commonly used for HTML templates, :builder is used for XML templates, and :coffee uses CoffeeScript to build JavaScript templates.

**Comment by rafaelfranca** [comment]
It needs to be updated to match the new error message. Could you open a PR?

**Comment by prathamesh-sonpatki** [comment]
It has been fixed on master. It is fixed in https://github.com/rails/rails/pull/25952 and backported as well to 5-0-stable. So should be available in next 5.0.1 release.

Thanks @cjhenck!

**Comment by cjhenck** [comment]
You're welcome - sorry I wasn't able to get to a PR, would have been fun to contribute :)
