### ISSUE TITLE
Documentation issue in the Rails 5 guide about Profiling

### ISSUE THREAD

**Issue by tradeli** [rails/rails#26736]
The section about [profiling](http://guides.rubyonrails.org/profiling.html) of the new guide should be explaining the best practices and possibilities/limitations regarding profiling and benchmarking Rails 5 applications, but the page does not contain the proposed information.

I'm still learning so I can't make a pull request :D

Thanks!

**Comment by rafaelfranca** [comment]
That guide is not finished yet, it may be removed

**Comment by tradeli** [comment]
I just thought that because that part of the guide is not complete I should open an issue for it, just as instructed on every page of the guide.

So does this means it won't be updated? Is there another up-to-date place to learn Profiling in Rails 5?

Sorry for the inconvenience!
