### ISSUE TITLE
Doc / comment issue ActionView::Template (template.rb)

### ISSUE THREAD

**Issue by MSP-Greg** [rails/rails#26733]
I believe the comment for [ActionView::Template](https://github.com/rails/rails/blob/master/actionview/lib/action_view/template.rb#L11-L88) is incorrectly placed, as it should be above the class declaration on line 7.

The comment is not shown in either [Rails API Docs](http://api.rubyonrails.org/classes/ActionView/Template.html) or at [RubyDoc](http://www.rubydoc.info/docs/rails/ActionView/Template).

Would it be considered appropriate to move the comment?

I'd submit a PR, but won't bother if no one will accept it.

Thanks,

Greg

**Comment by prathamesh-sonpatki** [comment]
Sounds good, please submit the PR, thanks!

**Comment by rafaelfranca** [comment]
That comment is not made to public consumption so this is why it is not show in any documentation site

**Comment by MSP-Greg** [comment]
Please see comment at https://github.com/rails/rails/pull/26737
