### ISSUE TITLE
ActionCable.server configuration examples? Issue with running different connection types.

### ISSUE THREAD

**Issue by merqlove** [rails/rails#26734]
### Steps to reproduce
1. Create 2 different cables.

`/app/channels/notification_cable`
NotificationCable with its own connection (`without user auth`)  

`/app/channels/application_cable`
ApplicationCable with its own connection (`with user auth`)  
### Actual behavior

Currently i see solution with creating 2 standalone servers, each with it's own ActionCable.server.config
### System configuration

**Rails version**: 5

**Ruby version**: 2.3.1

**Comment by maclover7** [comment]
Can you please provide a sample application that replicates the error you are seeing?

**Comment by merqlove** [comment]
@maclover7 I'm have no errors here. Just issue with setup understanding.
As i understand if i need different connection way, solution is to run independent server, because ActionCable.server instance able to handle only single handler class. Right?

Example scaffold.
https://github.com/merqlove/cablemulticon/tree/master/app/channels/notification_cable

**Comment by merqlove** [comment]
1. Can i send messages into the 2 different connection handlers within single Rails app?
Like `ActionCable.server.broadcast(channel, message)` 

   Or better way is to have single connection handler, with 2 identifiers?

2. This way i'm using in the real app.
https://github.com/merqlove/cablemulticon/blob/master/cable/config.ru

  This way is to run with rails server.
https://github.com/merqlove/cablemulticon/blob/master/config/routes.rb

3. Global configuration, which responds to any option from `ActionCable::Server::Configuration`
https://github.com/merqlove/cablemulticon/blob/master/config/environments/development.rb#L29

**Comment by merqlove** [comment]
Finished by using multiple identities. Final example is here:
https://github.com/merqlove/action-cable-multi-id
