### ISSUE TITLE
Test database is created with environment='development' when running rake db:test:prepare

### ISSUE THREAD

**Issue by hsgubert** [rails/rails#26731]
### Steps to reproduce

Just run the rake tasks below in a new rails 5 app (after having configured your database.yml)

```
rake db:create
rake db:migrate
rake db:test:prepare
```
### Expected behavior

Log in to the test database and issue the following query:

```
select * from ar_internal_metadata;
```

I would expect to see only a single environment metadata with value `test`, like this:

```
MariaDB [rails5_app_test]> select * from ar_internal_metadata;
+-------------+-------------+---------------------+---------------------+
| key         | value       | created_at          | updated_at          |
+-------------+-------------+---------------------+---------------------+
| environment | test        | 2016-10-07 18:02:38 | 2016-10-07 18:02:38 |
+-------------+-------------+---------------------+---------------------+
1 row in set (0.00 sec)
```
### Actual behavior

I actually get the environment set to `development`

```
MariaDB [rails5_app_test]> select * from ar_internal_metadata;
+-------------+-------------+---------------------+---------------------+
| key         | value       | created_at          | updated_at          |
+-------------+-------------+---------------------+---------------------+
| environment | development | 2016-10-07 18:02:38 | 2016-10-07 18:02:38 |
+-------------+-------------+---------------------+---------------------+
1 row in set (0.00 sec)
```
### System configuration

**Rails version**: 5.0.0.1
**Ruby version**: 2.3.1
**Database**: MariaDB + mysql2 gem

**Comment by hsgubert** [comment]
The problem here seems to be that the `rake db:test:load_schema` acts upon the test database, but does not change the rails env to 'test'.

https://github.com/rails/rails/blob/5-0-stable/activerecord/lib/active_record/railties/databases.rake#336

My fix suggestion would be to store the initial Rails.env value, the same way we store a boolean to know if we should reconnect, change the rails env to test, and then restore the value on the ensure block. Does that makes sense?

**Comment by prathamesh-sonpatki** [comment]
Looking into it.

**Comment by dcrockwell** [comment]
I am having the same problem.

* `rails db:setup RAILS_ENV=test` works correctly.
* `rails db:setup` works correctly on the development database, but the test database has `ar_internal_metadata` set to `development`.

**Comment by fredngo** [comment]
Finally got around to upgrading a large app from Rails 4.2.8 to Rails 5.0.3 and this issue is still present.

(Cannot comment on Rails 5.1 yet)

**Comment by bogdanvlviv** [comment]
I will investigate

**Comment by stevenharman** [comment]
Can confirm. I just upgraded a Rails 4.2.8 app to 5.0.3 and I'm seeing the same thing as @fredngo and @hsgubert. Thanks for looking into it, @bogdanvlviv.

**Comment by fredngo** [comment]
Finally updated my app to 5.1.1 and can confirm that this behaviour is still there. (See above)

**Comment by prathamesh-sonpatki** [comment]
I think https://github.com/rails/rails/pull/27102 should fix this by showing an error message in case development DATABASE_URL is being used for the test environment.

**Comment by lacco** [comment]
I experience similar problems: Calling `bin/rails db:test:prepare` always sets the environment to `development` instead of `test`. This is very annoying, I need to call `bin/rails db:environment:set RAILS_ENV=test` every time I switch branches with different migrations...

**Comment by mgodwin** [comment]
Also experiencing this problem on rails 5.1.2.  It causes an annoying error message when I try to run my tests via `rails test`, when I have pending migrations: 

> ActiveRecord::EnvironmentMismatchError: You are attempting to modify a database that was last run in `development` environment. You are running in `test` environment. If you are sure you want to continue, first set the environment using:
>
>    bin/rails db:environment:set RAILS_ENV=test

I can run the command, but w/o knowing about `ar_internal_metadata` table, this is kind of a confusing error message.  _Why_ was my test database run in the `development` environment?

So you can "fix" this by running `rails db:environment:set RAILS_ENV=test` or `rails db:test:prepare` (with the latter, you just won't need to run migrations anymore), but next time that I pull down migrations, we're in the same spot again.

Here's some output showing the problem.
```
$ cat Gemfile.lock | grep rails
  rails (= 5.1.2)
$ rails db:test:prepare
$ psql app_test -c "Select * from ar_internal_metadata;"
     key     |    value    |         created_at         |         updated_at
-------------+-------------+----------------------------+----------------------------
 environment | development | 2017-09-06 21:02:37.771472 | 2017-09-06 21:02:37.771472
(1 row)
```

**Comment by orbanbotond** [comment]
When I do `rake db:reset` it recreates the development and the test db.

In the `test database` the `value` of the `ar_internal_metadata` is `development` but it should be `test`

For the development database it is fine.

**Comment by thisismydesign** [comment]
@orbanbotond What version of ActiveRecord?

**Comment by MadBomber** [comment]
I'm moving a 4.2.10 app to 5.2.0 and when I do `RAILS_ENV=development rake db:reset` I get the message to do `bin/rails db:environment:set RAILS_ENV=development` every time.  Upgrades are wonderful.  :)

**Comment by fdutey** [comment]
I'm using branches a lot, I have one db per branch. 
I rebase a lot and always start a rebase by reseting my db.
I test a lost and always run tests after rebasing

I can tell you that I understand 2 things from this "feature"

- It's extremely annoying (you think i'm calm here but I really want to burn everything right now)
- it doesn't provide any kind of value. test and dev environment are made to be broken. If it happens, well.... `db:reset` is here for that

**Comment by nathan-eko** [comment]
This does seem like a completely useless feature that nobody needs or wants, especially if you're parallelizing your tests locally and have dozens of databases.

**Comment by iarobinson** [comment]
Posting this here for the potential benefit to som one who is dealing with this issue.

I found a strange fix to get around it because `rails db:migrate` was not working for me. I would continue to get the following error:

```
ActiveRecord::EnvironmentMismatchError: You are attempting to modify a database that was last run in `development` environment.
You are running in `test` environment. If you are sure you want to continue, first set the environment using:
        bin/rails db:environment:set RAILS_ENV=test
```

Now, running `rails db:migrate` and the command above did NOT fix the situation… somehow the following is how to get around this:

`rake db:migrate`

...I thought they did mostly the same thing, but apparently they do not....

**Comment by tradesmanhelix** [comment]
FWIW, I was ending up with the strange error:

```
`Activerecord::EnvironmentMismatchError: You are attempting to modify a database that was last run in `test` environment. You are running in `development`...
```

Turns out, I had a `.env.local` file that was setting `DB_NAME=myapp_database_test` and this caused `bundle exec rails db:setup` to attempt to generate a database with the same name for both the test and development environments. Commenting out that bit of the `.env` file allowed `db:setup` to complete normally.

Hopefully that proves helpful to someone.
