### ISSUE TITLE
Submit button gets disabled and is not enabled even after the correction of errors

### ISSUE THREAD

**Issue by kamalpandey** [rails/rails#26744]
### Steps to reproduce

(Guidelines for creating a bug report are [available
here](http://guides.rubyonrails.org/contributing_to_ruby_on_rails.html#creating-a-bug-report))

### Expected behavior
the submit button was enabled 
it worked as expected in rails 4.2

### Actual behavior
In my app there is a user registration form and braintree dropin ui when i click the submit button the button gets disabled and continues to be disabled 

### System configuration
**Rails version**: 5

**Ruby version**: 2.3.1

**Comment by rafaelfranca** [comment]
Can you please provide a sample application that reproduces the error?

**Comment by kamalpandey** [comment]
<%= form_for @order_form, url: orders_path do |f| %>
	<%= f.fields_for :user, f.object.user do |u| %>

		<div class="form-group">
			<%= u.label :name %>
			<%= u.text_field :name, class: "form-control" %>
		</div>

		<div class="form-group">
			<%= u.label :email %>
			<%= u.email_field :email, class: "form-control" %>
		</div>
	<% end %>
 
  		
  		<p><%= f.submit "Place order", class: "btn btn-primary" %></p>
<% end %>

<script>
// We generated a client token for you so you can test out this code
// immediately. In a production-ready integration, you will need to
// generate a client token on your server (see section below).
var clientToken = "eyJ2ZXJzaW9uIjoyLCJhdXRob3JpemF0aW9uRmluZ2VycHJpbnQiOiJjYzNkM2IyNGI1ZGU1NTMyOGJhZmI2MjZlMmY4NWVlNzljMDdkNjBkMGY0MmQ1MGQ5ZDIxOTgwYjA0NzcxOTc2fGNyZWF0ZWRfYXQ9MjAxNi0xMC0wOVQxNTowNTo0OC43MDg5MzExMjgrMDAwMFx1MDAyNm1lcmNoYW50X2lkPTM0OHBrOWNnZjNiZ3l3MmJcdTAwMjZwdWJsaWNfa2V5PTJuMjQ3ZHY4OWJxOXZtcHIiLCJjb25maWdVcmwiOiJodHRwczovL2FwaS5zYW5kYm94LmJyYWludHJlZWdhdGV3YXkuY29tOjQ0My9tZXJjaGFudHMvMzQ4cGs5Y2dmM2JneXcyYi9jbGllbnRfYXBpL3YxL2NvbmZpZ3VyYXRpb24iLCJjaGFsbGVuZ2VzIjpbXSwiZW52aXJvbm1lbnQiOiJzYW5kYm94IiwiY2xpZW50QXBpVXJsIjoiaHR0cHM6Ly9hcGkuc2FuZGJveC5icmFpbnRyZWVnYXRld2F5LmNvbTo0NDMvbWVyY2hhbnRzLzM0OHBrOWNnZjNiZ3l3MmIvY2xpZW50X2FwaSIsImFzc2V0c1VybCI6Imh0dHBzOi8vYXNzZXRzLmJyYWludHJlZWdhdGV3YXkuY29tIiwiYXV0aFVybCI6Imh0dHBzOi8vYXV0aC52ZW5tby5zYW5kYm94LmJyYWludHJlZWdhdGV3YXkuY29tIiwiYW5hbHl0aWNzIjp7InVybCI6Imh0dHBzOi8vY2xpZW50LWFuYWx5dGljcy5zYW5kYm94LmJyYWludHJlZWdhdGV3YXkuY29tLzM0OHBrOWNnZjNiZ3l3MmIifSwidGhyZWVEU2VjdXJlRW5hYmxlZCI6dHJ1ZSwicGF5cGFsRW5hYmxlZCI6dHJ1ZSwicGF5cGFsIjp7ImRpc3BsYXlOYW1lIjoiQWNtZSBXaWRnZXRzLCBMdGQuIChTYW5kYm94KSIsImNsaWVudElkIjpudWxsLCJwcml2YWN5VXJsIjoiaHR0cDovL2V4YW1wbGUuY29tL3BwIiwidXNlckFncmVlbWVudFVybCI6Imh0dHA6Ly9leGFtcGxlLmNvbS90b3MiLCJiYXNlVXJsIjoiaHR0cHM6Ly9hc3NldHMuYnJhaW50cmVlZ2F0ZXdheS5jb20iLCJhc3NldHNVcmwiOiJodHRwczovL2NoZWNrb3V0LnBheXBhbC5jb20iLCJkaXJlY3RCYXNlVXJsIjpudWxsLCJhbGxvd0h0dHAiOnRydWUsImVudmlyb25tZW50Tm9OZXR3b3JrIjp0cnVlLCJlbnZpcm9ubWVudCI6Im9mZmxpbmUiLCJ1bnZldHRlZE1lcmNoYW50IjpmYWxzZSwiYnJhaW50cmVlQ2xpZW50SWQiOiJtYXN0ZXJjbGllbnQzIiwiYmlsbGluZ0FncmVlbWVudHNFbmFibGVkIjp0cnVlLCJtZXJjaGFudEFjY291bnRJZCI6ImFjbWV3aWRnZXRzbHRkc2FuZGJveCIsImN1cnJlbmN5SXNvQ29kZSI6IlVTRCJ9LCJjb2luYmFzZUVuYWJsZWQiOmZhbHNlLCJtZXJjaGFudElkIjoiMzQ4cGs5Y2dmM2JneXcyYiIsInZlbm1vIjoib2ZmIn0=";

braintree.setup(clientToken, "dropin", {
  container: "payment-form"
});

</script>

**Comment by rafaelfranca** [comment]
Sorry, I can't see anything wrong in your code could you try to create a new application and replicate this problem and upload this application in github so we can debug?

**Comment by kamalpandey** [comment]
[https://github.com/kamalpandey/ShoppingCart](url)

**Comment by rafaelfranca** [comment]
Your application is not using disable_with, so I don't think the problem you are having is a Rails bug.

Thank you for reporting.
