### ISSUE TITLE
`rake test` fails to run a single test

### ISSUE THREAD

**Issue by Xenofex** [rails/rails#26748]
### Steps to reproduce

Run `rake test path/to/test.rb` to invoke a single file test, e.g.

```bash
$ bin/rake test test/models/card_test.rb
```

### Expected behavior

Only the specified file is executed.

### Actual behavior

The all the tests are executed.

However, `rails test test/models/card_test.rb` works file

### System configuration
**Rails version**: 5.0.0.1

**Ruby version**: MRI 2.3.1

**Comment by kaspth** [comment]
`bin/rake test` doesn't support running a single file that in Rails 5. `bin/rake test TEST=test/models/card_test.rb` should though.

I'm curious, why would you want to use `bin/rake test` now that we have a Rails test command builtin?

**Comment by Xenofex** [comment]
So it's via a shell env `TEST`?  Before it was `TESTOPTS`.

Yes I would like to use `rails test` instead of the old `rake test` when I'm typing in the terminal. But editor integration breaks due to the changes here. Namely [rails.vim](http://www.vim.org/scripts/script.php?script_id=1567), cannot run a single file/test via `:.Rake` any longer in Rails 5.

And I find that sometimes, the `rails [command]` version doesn't take advantage of `spring` correctly. Here in my project, `bin/rake routes` is run by `spring`, while neither `rails routes` nor `bin/rails routes` utilizes `spring`.

**Comment by kaspth** [comment]
Rails 4.2 did have an extension to Rake such that `rake test test/models/post_test.rb` would work, although the convention was `TEST=test/models/post_test.rb` in gem projects.

> Namely rails.vim, cannot run a single file/test via :.Rake any longer in Rails 5.

Then the plugin should be updated to support Rails 5. Which, judging from the linked issue, it seems to have already been. kudos! 👏

> And I find that sometimes, the rails [command] version doesn't take advantage of spring correctly. Here in my project, bin/rake routes is run by spring, while neither rails routes nor bin/rails routes utilizes spring.

That could just mean you have a spring version that doesn't support Rails 5's new commands. Try looking up its changelog and updating that as well 🤓

**Comment by przbadu** [comment]
Hi, I am using Rails `4.2` and running below command:

```ruby
bin/rake test TEST=test/controllers/api/v1/my_controller_test.rb TESTOPTS="-n /should run this test case/"
```
But it run all test cases in the current file. How should I run current test case and not all test cases in the current file?
