### ISSUE TITLE
Issue in callback when string appended using  '+'

### ISSUE THREAD

**Issue by A9u** [rails/rails#26749]
In rails 5, for a callback, when I try to append string using '+', with no space after it, an error occurs. 

### Steps to reproduce
```ruby
before_save do
    self.name = age_group  +"gender"                                                                         
end 
```

### Expected behavior
It should append the string 
age_group = "U12"
name = "U12 gender"

** These all cases work
`````ruby
name = age_group + "gender"
name = age_group+"gender"
name = age_group + "gender"
name = age_group+ "gender"
`````
### Actual behavior
````ruby
Argument error: wrong number of arguments (given 1, expected 0)
	from /.rvm/gems/ruby-2.3.1/gems/activerecord-5.0.0.1/lib/active_record/attribute_methods/read.rb:34:in `__temp__167656f57627f65707'
	from /app/models/squad.rb:4:in `block in <class:Squad>'
	from /.rvm/gems/ruby-2.3.1/gems/activesupport-5.0.0.1/lib/active_support/callbacks.rb:396:in `instance_exec'
	from /.rvm/gems/ruby-2.3.1/gems/activesupport-5.0.0.1/lib/active_support/callbacks.rb:396:in `block in make_lambda'
```

### System configuration
**Rails version**: 5.0.0.1

**Ruby version**: 2.3.1

**Comment by sevenseacat** [comment]
Looks like it's interpreting `+"gender"` as an argument to the `age_group` method - not sure what Rails can do to fix that one

**Comment by kaspth** [comment]
This is purely Ruby's syntax, nothing for Rails to do.

When doing `+"gender"` it's likely trying to call the `def +@` method on the string and then invoking the `age_group` reader with that string as an argument.

**Comment by A9u** [comment]
But it is working on rails console, irb. I am facing the issue only for callback.

**Comment by matthewd** [comment]
```
% irb -w
irb(main):001:0> puts +"x"
(irb):1: warning: ambiguous first argument; put parentheses or a space even after `+' operator
x
=> nil
```

**Comment by A9u** [comment]
which ruby version are you using?

**Comment by matthewd** [comment]
The above was from 2.3.1.

But: this is not a Rails issue. Please use the mailing list or StackOverflow for questions/help, where a wider community will be able to help you. We reserve the issues tracker for issues only.
