### ISSUE TITLE
to_json on Maill::Message raises "Encoding::UndefinedConversionError" with (jpeg) attachment

### ISSUE THREAD

**Issue by nathansamson** [rails/rails#26751]
### Steps to reproduce
- Create a mail
- Add a JPEG attachment (No way to include this into a gist apparantly but any JPG file should work)
- Convert mail to_json

https://gist.github.com/nathansamson/a911b3f33f05cf04df3f282a7cb595e8
See https://gist.github.com/nathansamson/a911b3f33f05cf04df3f282a7cb595e8#file-activesupport_to_json_bug-rb
### Expected behavior
- Should convert to JSON string with UTF8 encoding
### Actual behavior
- raises an Encoding::UndefinedConversionError

This seems to work with just the mail and json gem included, but not with the activesupport extension.
See https://gist.github.com/nathansamson/a911b3f33f05cf04df3f282a7cb595e8#file-json_works-rb
### System configuration

**Rails version**: 4.2.7 and 5.0.0

**Ruby version**: 2.3.1p112 (2016-04-26 revision 54768) [x86_64-linux]

**Comment by utilum** [comment]
I can reproduce both test results on master and 4.2.7.

**Comment by chancancode** [comment]
I am not sure if we need to fix this. In general, each JSON encoder needs to have some default behavior on how to encode foreign/custom objects that it doesn't understand.

In the case of Active Support's encoder, the default is to dump all the instance variables as a hash, and for the json gem, the default is call `to_s`. Neither is a very useful default in this case, imo.

May I ask why were you dumping a mail object into JSON in the first place?

**Comment by betesh** [comment]
I'm getting this on Rails 5.1.4.

> Neither is a very useful default in this case, imo.

If I want to send a JPEG as part of a JSON response from my API, what would be the right way to do it?
