### ISSUE TITLE
Documentation states that log_formatter defaults, it does not

### ISSUE THREAD

**Issue by rmarone** [rails/rails#26769]
### Steps to reproduce

If you've been upgrading an application or have not used the rails generator to get your config/environments/production.rb file, it may not contain the lines:

  # Use default logging formatter so that PID and timestamp are not suppressed.
  config.log_formatter = ::Logger::Formatter.new

By removing those lines, you will be left with an application which logs in production using the ActiveSupport::Logger::SimpleFormatter

The guide states:
" config.log_formatter defines the formatter of the Rails logger. This option defaults to an instance of ActiveSupport::Logger::SimpleFormatter for all modes **except production, where it defaults to Logger::Formatter**. If you are setting a value for config.logger you must manually pass the value of your formatter to your logger before it is wrapped in an ActiveSupport::TaggedLogging instance, Rails will not do it for you.
"

The formatter is not being defaulted in production, it is being generated with a default value, this is quite different.  I suggest the guide be changed to read:

config.log_formatter defines the formatter of the Rails logger. This option defaults to an instance of ActiveSupport::Logger::SimpleFormatter for all modes. The production.rb configuration is generated set to Logger::Formatter by default. If you are setting a value for config.logger you must manually pass the value of your formatter to your logger before it is wrapped in an ActiveSupport::TaggedLogging instance, Rails will not do it for you.

### System configuration
**Rails version**: 4.2

**Ruby version**: 2

**Comment by rafaelfranca** [comment]
Could you please send a pull request?

**Comment by rmarone** [comment]
Created
#26770

**Comment by arthurnn** [comment]
Closing as PR was merged
