### ISSUE TITLE
[RFE] Generic way for setting headers to be used in the setup phase of integration tests

### ISSUE THREAD

**Issue by imtayadeway** [rails/rails#26763]
In integration tests, I like that you can set the `Accept` header ahead of time (i.e. before the request is made):

```ruby
self.accept = "application/json"
```

AFAIK this is the only header that can be set in this way. I am missing a way to set any header arbitrarily in the setup phase of these tests. Without it, the alternatives seem to be a) duplicated test code, or b) wrapping the request helpers. Setting a header as in the case of `accept=` would be preferable to me.

Are there plans to enhance the integration tests in this way? Or reasons to not want to? If acceptable, I'd be happy to tackle this, but wanted to check first. Thanks!

**Comment by rafaelfranca** [comment]
Thank you so much for the issue but we don't take feature request on the issue tracker. We recommend you to try to implement the feature and send us a pull request or if you are in doubt if the feature will be accepts ask in Rails Core mailing list for feedback.

**Comment by rafaelfranca** [comment]
You are able to set the headers when doing the request so why you need to do it globally? Duplication in tests is totally fine and even make the tests more clear.

**Comment by imtayadeway** [comment]
Thanks! I'm not sure if you're inviting a response but I'll try to pick it up on the mailing list. Apologies for not reading the guidelines properly!

**Comment by rafaelfranca** [comment]
No problem. You can reply here since I did here. I just wanted to point you to the right place next time
