### ISSUE TITLE
Stack level too deep - when belongs_to and foreign_key have the same name

### ISSUE THREAD

**Issue by olavnyy** [rails/rails#26778]
### Steps to reproduce

```
class CreateAccounts < ActiveRecord::Migration[5.0]
  def change
    create_table :accounts do |t|
      t.string :title
      t.integer :created_by

      t.timestamps
    end
  end
end

class CreateUsers < ActiveRecord::Migration[5.0]
  def change
    create_table :users do |t|
      t.string :name

      t.timestamps
    end
  end
end

class Account < ApplicationRecord
  belongs_to :created_by, :class_name => "User", :foreign_key => "created_by"
end

class User < ApplicationRecord
end

Account.create(title: "Test", created_by: User.create(name: "TestUser"))
Account.where(created_by: User.first)

```
### Expected behavior

ActiveRecord_Relation should be returned
### Actual behavior

A stack level too deep error is raised
### System configuration

Rails 5.0.0.1

Ruby 2.3.1

**Comment by utilum** [comment]
The foreign key is supposed to be the column name from associated table... don't you want a column from the users table in there?

**Comment by BEaStia** [comment]
According to the sources, you were to write:

class Account < ApplicationRecord
  belongs_to :user, :class_name => "User", :foreign_key => "created_by"
end

**Comment by yivo** [comment]
The attribute `created_by` exists on `Account`. You are trying to define association with the same name. There is not functionality in Rails to have same attribute and association names. This is your typo and is not related to Rails.

You should rename attribute `created_by` or change association name as @BEaStia mentioned.

**Comment by yivo** [comment]
The convention in Rails is that you should add postfix `_id` to table keys. 
`created_by` => `created_by_id`

**Comment by milep** [comment]
I got the same issue with a legacy database, which had a foreign_key with a same name as referenced table/model.
Eg. in class PaymentRows:
`belongs_to :payment, foreign_key: 'payment'`

**Comment by spidergears** [comment]
@rafaelfranca I have this very issues  today with rails 5.2.3 .
Is this a `won't fix` ?

**Comment by spidergears** [comment]
For anyone coming to this, currently a simple workaround is to change the name of the association and specify class_name.

**Comment by damisul** [comment]
Seeing this issue with rails 5.2.4.4, we got this problem while porting legacy app.
Same code worked fine with rails 5.1.6.2

**Comment by tldev** [comment]
For those needing to rename these pesky columns in order to upgrade Rails, this snippet should help uncover models with column names and associations that have identical names:

```ruby
ActiveRecord::Base.descendants.map do |klass|
  assocations = klass.reflect_on_all_associations(:belongs_to)
  assocations.each do |association|
    begin
      association_name = association.name.to_s
      columns = klass.column_names
      if columns.include?(association_name)
        puts [klass.name, association_name]
      end
    rescue ActiveRecord::StatementInvalid
      next
    end
  end
end; nil
```
