### ISSUE TITLE
How to allow Ruby application to better support multi-threading or multiple CPUs

### ISSUE THREAD

**Issue by jakczuhang** [rails/rails#26773]
We have a website built on Ruby hosted by a company that offers additional CPUs as the plan increases. Are there additional ways to better optimize an application to use multiple CPUs or multi-threaded handling? Most of our usage is from visitors visiting the site and browsing content. 

Thanks

**Comment by matthewd** [comment]
Please use the mailing list or StackOverflow for questions/help, where a wider community will be able to help you. We reserve the issues tracker for issues only.
