### ISSUE TITLE
request.local? returns false in tests

### ISSUE THREAD

**Issue by seanlinsley** [rails/rails#26783]
### Steps to reproduce

``` ruby
  prepend_before_action :https_redirect

  def https_redirect
    if !request.ssl? && !request.local?
      redirect_to protocol: 'https://'
    end
  end
```
### Expected behavior

Requests should be redirected to HTTPS in staging and production, but not in development and test.
### Actual behavior

HTTPS redirection is correctly skipped in development, but incorrectly happens in test.

That's because `request.remote_ip` is 0.0.0.0, and the [`LOCALHOST`](https://github.com/rails/rails/blob/0cbb0be329e1375e415ad37c9c20ea9f74ff1ac3/actionpack/lib/action_dispatch/http/request.rb#L28) regular expression doesn't cover that address.

It appears that 0.0.0.0 is meant to cover all addresses the local machine might respond to ([ref](http://serverfault.com/questions/78048/whats-the-difference-between-ip-address-0-0-0-0-and-127-0-0-1)). Is there a reason why we wouldn't want to include it for `request.local?`?

For now, this is a good enough workaround:

``` ruby
  prepend_before_action :https_redirect

  def https_redirect
    if !request.ssl? && !(request.local? || Rails.env.test?) # 0.0.0.0 in test doesn't match `local?`
      redirect_to protocol: 'https://'
    end
  end
```

**Comment by BEaStia** [comment]
What about changing localhost regex?

**Comment by seanlinsley** [comment]
Sorry, that's what I was suggesting. I only haven't created a PR because I'm not 100% sure it wouldn't cause a security issue in production (for example).

**Comment by BEaStia** [comment]
@seanlinsley How do you manage to receive request from 0.0.0.0?

**Comment by matthewd** [comment]
I'm not sure I accept the premise that requests in tests should be treated as `local?`.

If we wanted that, the right solution would be to change the remote_ip claimed in tests... but I believe it is the non-local 0.0.0.0 precisely to avoid any such special treatment.

**Comment by BEaStia** [comment]
Probably i'm wrong but how can you receive request from 0.0.0.0 in normal server working mode?

**Comment by ruprict** [comment]
I am not sure that changing the `LOCALHOST` to cover `0.0.0.0` would be OK, anyway. Deploying Rails on Docker, for example, often has the server binding to `0.0.0.0`, which means these deployments would report requests as local when they aren't.

(_hopes this is relevant and not a dumb observation_)

**Comment by seanlinsley** [comment]
>@seanlinsley How do you manage to receive request from 0.0.0.0?

@BEaStia simply by running a Rails 4.2 controller test, using RSpec.

>I'm not sure I accept the premise that requests in tests should be treated as `local?`.
>
>If we wanted that, the right solution would be to change the remote_ip claimed in tests... but I believe it is the non-local 0.0.0.0 precisely to avoid any such special treatment.

@matthewd That might indeed be the intention. Perhaps we could add some documentation around this?

>I am not sure that changing the `LOCALHOST` to cover `0.0.0.0` would be OK, anyway. Deploying Rails on Docker, for example, often has the server binding to `0.0.0.0`, which means these deployments would report requests as local when they aren't.

@ruprict I'm not an expert on this subject, but I would expect port binding to be separate from what the requester reports itself as. 0.0.0.0 as a port binding means it'll listen to requests intended for any IP address that makes it to the server, but I imagine a request originating from 0.0.0.0 means something different.

**Comment by seanlinsley** [comment]
Odd that a bot is adding `wontfix` -- that implies that it's a conscious decision to not fix this.

**Comment by maclover7** [comment]
@seanlinsley Apologies -- I believe it meant to add the `stale` label. We're just rolling out the new bot today, so looks like there are a few bugs to be ironed out :)

**Comment by spacemunkay** [comment]
A workaround in rspec:

```
Rspec.confgiure do |config|
  config.before(:each, type: :controller) do
    @request.remote_addr = '127.0.0.1'
  end
end
```
