### ISSUE TITLE
"no such column" error when eager-loading a scoped has-many-through association

### ISSUE THREAD

**Issue by adamlogic** [rails/rails#26780]
### Expected behavior

When eager-loading (via `includes`) a has-many-through association with a scope applied in the association declaration, I would expect `references` to be unnecessary.
### Actual behavior

Without using `references`, I'm getting a `SQLException` because the scoped column isn't referenced in the query.
### System configuration

**Rails version**: 5.0
**Ruby version**: 2.3.1
### Steps to reproduce

``` ruby
begin
  require "bundler/inline"
rescue LoadError => e
  $stderr.puts "Bundler version 1.10 or later is required. Please update your Bundler"
  raise e
end

gemfile(true) do
  source "http://rubygems.org"
  # Activate the gem you are reporting the issue against.
  gem "activerecord", "5.0.0"
  gem "sqlite3"
  gem "pry"
end

require "pry"
require "active_record"
require "minitest/autorun"
require "logger"

# Ensure backward compatibility with Minitest 4
Minitest::Test = MiniTest::Unit::TestCase unless defined?(Minitest::Test)

# This connection will do for database-independent bug reports.
ActiveRecord::Base.establish_connection(adapter: "sqlite3", database: ":memory:")
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :deals, force: true do |t|
  end

  create_table :deal_areas, force: true do |t|
    t.integer :deal_id
    t.integer :area_id
  end

  create_table :areas, force: true do |t|
    t.boolean :deleted
  end
end

class Deal < ActiveRecord::Base
  has_many :deal_areas
  has_many :areas, -> { not_deleted }, through: :deal_areas
end

class DealArea < ActiveRecord::Base
  belongs_to :deal
  belongs_to :area
end

class Area < ActiveRecord::Base
  scope :not_deleted, -> { where(deleted: false) }
end

class BugTest < Minitest::Test
  # Deal has many Areas through DealArea using the Area.not_deleted scope
  # Calling without `references` results in SQLException: no such column: areas.deleted
  # Why is it necessary to use `references` for this to work?

  def test_including_areas_with_references
    deal = Deal.create!
    deal.areas.create!

    assert_equal [deal.id], Deal.includes(:areas).references(:areas).map(&:id)
  end

  def test_including_areas_without_references
    deal = Deal.create!
    deal.areas.create!

    assert_equal [deal.id], Deal.includes(:areas).map(&:id)
  end
end
```

**Comment by mechanicles** [comment]
@adamlogic It's a correct behaviour. Please check this doc http://apidock.com/rails/ActiveRecord/QueryMethods/includes

**Doc says:**

If you want to add conditions to your included models you’ll have to explicitly reference them. For example:

```
User.includes(:posts).where('posts.name = ?', 'example')
```
Will throw an error, but this will work:

```
User.includes(:posts).where('posts.name = ?', 'example').references(:posts)
```
Note that includes works with association names while references needs the actual table name.

**Comment by maclover7** [comment]
👍 closing per @mechanicles, this is the expected behavior.

**Comment by adamlogic** [comment]
It appears to me that the API docs for `includes` don't quite match the [guide](http://guides.rubyonrails.org/active_record_querying.html#specifying-conditions-on-eager-loaded-associations):

> Using where like this will only work when you pass it a Hash. For SQL-fragments you need to use references to force joined tables

In my example, I'm using a conditions Hash, not a SQL fragment.

The [API docs for `references`](http://api.rubyonrails.org/classes/ActiveRecord/QueryMethods.html#method-i-references) also make it sound like it's only needed for SQL fragments, but it's a bit ambiguous.

Still think it's correct behavior?

**Comment by yuktikhurana** [comment]
@adamlogic  Faced the same issue. Don't know if it's expected.
@maclover7  But i feel the following test case failure isn't expected.

```
  def test_including_areas_with_references_having_deleted_areas
    deal = Deal.create!
    deal.areas.create!(deleted: true)

    assert_not_equal [deal.id], Deal.includes(:areas).references(:areas).map(&:id)
  end
```

**Comment by rafaelfranca** [comment]
This should be fixed by https://github.com/rails/rails/pull/29413
