### ISSUE TITLE
Actioncable closes automatically Process (pid=19895, group=the_grid_api_websocket) no longer exists! Detaching it from the pool.

### ISSUE THREAD

**Issue by sulmanweb** [rails/rails#26803]
### Steps to reproduce
- Rails 5.0.0.1
- Ruby 2.3.1
- Rails API
- Deploy on Ubuntu 16.04 using [https://gorails.com/deploy/actioncable](https://gorails.com/deploy/actioncable)

(Guidelines for creating a bug report are [available
here](http://guides.rubyonrails.org/contributing_to_ruby_on_rails.html#creating-a-bug-report))
### Expected behavior

consumer should subscribe and connected
### Actual behavior

```
Process (pid=19895, group=the_grid_api_websocket) no longer exists! Detaching it from the pool.
Checking whether to disconnect long-running connections for process 19895, application the_grid_api_websocket
```
### System configuration

**Rails version**: 2.3.1

**Ruby version**:5.0.0.1

**Comment by maclover7** [comment]
cc @matthewd
