### ISSUE TITLE
Messages should be displayed in dashboard

### ISSUE THREAD

**Issue by Gopi07nath** [rails/rails#26818]
### Steps to reproduce

Open forushealth.com
Click on new visit.

(Guidelines for creating a bug report are [available
here](http://guides.rubyonrails.org/contributing_to_ruby_on_rails.html#creating-a-bug-report))

### Expected behavior
Tell us what should happen
Messages should be displayed

### Actual behavior
Tell us what happens instead
Messages are not displaying

### System configuration
**Rails version**:

**Ruby version**:

**Comment by sevenseacat** [comment]
This isn't a problem in Rails, it will be a problem in the app that runs forushealth.com.
