### ISSUE TITLE
Facing runtime error NameError (uninitialized constant) for modules, classes placed in lib folder after upgrading Rails to 5.0.0.1 from 4.2.5.1

### ISSUE THREAD

**Issue by jiggneshhgohel** [rails/rails#26814]
**Ruby 2.3.1**

I have two separate Rails applications

* one just exposes an API (henceforth termed as **API-app**) and 

* another one acts as an Administration Portal (henceforth termed as **AdminPortal**) for managing the data in API-app.

Both are presently running on Rails **4.2.5.1** on **staging** as well as **production** environments. However on a **staging_experimental** environment I upgraded both the applications to Rails **5.0.0.1**. I have rspecs for the both the applications and the spec suite in both the applications is passing and Capistrano deployment goes success. However when trying to send request to API-endpoint in API-app I face a runtime error 

> NameError (uninitialized constant Api::BaseController::ApiTokenAuthentication)

**/lib/api_token_authentication.rb**

    module ApiTokenAuthentication
      <some module_functions defined here>
    end

and the module functions are accessed in my controller in following manner:

    class Api::BaseController < ActionController::Base
      def authenticate!(user)
         ApiTokenAuthentication.my_module_function_here(user)
      end
    end

The same kind of runtime-error **NameError (uninitialized constant ...)** errors are also encountered in AdminPortal too and they refer to the code placed in AdminPortal's codebase's **lib** folder. For e.g.

> NameError (uninitialized constant MyApiApp::Api): 

> NameError (uninitialized constant MyApiApp::Api::Get): 

> NameError (uninitialized > constant MyApiApp::Api::Post):

 
**/lib/my_api_app**

**/lib/my_api_app/api.rb**

    module MyApiApp
      module Api
      end
    end

**/lib/my_api_app/api/get.rb**

    module MyApiApp
      module Api
        class Get < BaseRequest
        end
      end
    end

**/lib/my_api_app/api/post.rb**

    module MyApiApp
      module Api
        class Post < BaseRequest
        end
      end
    end

**/lib/my_api_app/api/base_request.rb**

    module MyApiApp
      module Api
        class BaseRequest
        end
      end
    end

**/lib/my_api_app/api/base_response.rb**

    module MyApiApp
      module Api
        class BaseResponse
        end
      end
    end

Searching for a solution to fix these errors I found following [post](http://stackoverflow.com/a/13202812/936494) which mentioned to explicitly require the path in an initializer file. For e.g.

**/config/initializers/load_my_api_app_api_utility_classes.rb**

    require File.join(Rails.root, "lib/my_api_app/api.rb")
    
    lib_api_dir_path = Rails.root.join("lib", "my_api_app", "api").to_s
    
    Dir["#{lib_api_dir_path}/*.rb"].each {|file| require file }

After adding the above initializer the errors in AdminPortal app went away

> NameError (uninitialized constant MyApiApp::Api): 

> NameError (uninitialized constant MyApiApp::Api::Get): 

> NameError (uninitialized > constant MyApiApp::Api::Post):

but as soon as AdminPortal app sent request to the end-point exposed by API-app I started encountering following error (mentioned previously)

> NameError (uninitialized constant Api::BaseController::ApiTokenAuthentication)

So I think there is some basic thing which is missing and which is causing the errors related to auto-loading of code residing in the **lib** folder and which is used by the controller classes. I am really puzzled on why this is happening because I have checked `/config/application.rb` and in both the applications `config.autoload_paths << Rails.root.join('lib')` is already there.

The same code is working without any issues on **staging** and **production** envs wherein the application is running on Rails 4.2.5.1. 

Also not facing these errors with the upgraded code on **development** environment on my local machine. 

Can anybody please shed light on this and guide me towards the resolution of this weird error?

Thanks.

**Comment by rafaelfranca** [comment]
Autoload is disabled in any environment that has eager_load enabled. You should never add `lib` to `autoload_paths`. Use `eager_autoload_paths`. All this information is being explained in the upgrading guide http://guides.rubyonrails.org/upgrading_ruby_on_rails.html#autoloading-is-disabled-after-booting-in-the-production-environment

**Comment by jiggneshhgohel** [comment]
@rafaelfranca thanks for your prompt response. I checked the guide link you referred to. I did followed that guide during upgrade but somehow I overlooked the autoloading disabled in production env related section. But at the same time I could not find about `eager_autoload_paths` mentioned about anywhere.

However searching the web I came across following SO post http://stackoverflow.com/a/19852844/93649 and it explains the mechanism in great manner. So I guess you were referring to `eager_load_paths` path. And I will definitely try this out and put the results here so that somebody else like me ending up here can benefit.

Thanks.

**Comment by rafaelfranca** [comment]
Yeah, exactly this one `eager_load_paths`

**Comment by jiggneshhgohel** [comment]
I tried using the `eager_load_paths` approach but it started throwing new errors. Let me explain the whole scenario:

Presently in my **API-app** `config/application.rb` I have following:

```
    config.autoload_paths << Rails.root.join('lib')
    config.autoload_paths << Rails.root.join('app', 'decorators', 'concerns')
```

Using @rafaelfranca's suggestion in comment https://github.com/rails/rails/issues/26814#issuecomment-254586170 I replaced those with

```
lib_dir = Rails.root.join('lib')

config.eager_load_paths << lib_dir.join('api')

Dir["#{lib_dir.to_s}/*.rb"].each do |f_full_path|
    config.eager_load_paths << f_full_path
end

config.eager_load_paths << Rails.root.join('app', 'decorators', 'concerns')
```

**With that I am selectively adding the directories and files path residing in `lib` folder to the `eager_load_paths` so that I can exclude `/lib/tasks` and `/lib/scripts` from getting eager loaded.**

Having that code in place when I tried to access `rails c staging_experimental` I encountered following error:

```
config/routes.rb:40:in `instance_eval': uninitialized constant ApiV1TokenRequestConstraint (NameError)
	from /config/routes.rb:40:in `instance_eval'
	from /config/routes.rb:40:in `draw'
	from /config/routes.rb:50:in `block in <top (required)>'
```

To resolve that error I added following at the top of my routes file `/config/routes/api/v1.rb` (please refer at the bottom of this comment on what kind of code this routes file contains)

```
require_dependency "api_v1_token_request_constraint"
require_dependency "subdomain_constraint"
```

Adding that the above mentioned error went away and I got another error:

```
/app/models/concerns/role_methods.rb:13:in `<module:RoleMethods>': uninitialized constant RoleMethods::SupportedRole (NameError)
	from /app/models/concerns/role_methods.rb:1:in `<top (required)>'
```

The content of **/app/models/concerns/role_methods.rb** is shown below:

```
module RoleMethods
  extend ActiveSupport::Concern

  def has_role?(role_sym)
    return false unless role.present?
    role.name.to_sym == role_sym
  end

  def has_no_role?
    role.blank?
  end

  SupportedRole.all.each do |supported_role_obj|
    role_name = supported_role_obj.name
    method_name = "is_#{role_name}?".to_sym
    define_method(method_name) {    # def is_staff?
      has_role?(role_name.to_sym)   #   has_role?(:staff)
    }                               # end
  end
end
```

`SupportedRole` is a utility class defined at path `/lib/supported_role.rb`.

To resolve that error I added following at the top of  file `/app/models/concerns/role_methods.rb` I added following:

```
require_dependency "supported_role"
```

and that error went away and I got another error:

```
/app/decorators/api/v1/acknowledgement_alert_decorator.rb:3:in `<module:V1>': uninitialized constant Api::V1::CustomDelegator (NameError)
	from /app/decorators/api/v1/acknowledgement_alert_decorator.rb:2:in `<module:Api>'
	from /app/decorators/api/v1/acknowledgement_alert_decorator.rb:1:in `<top (required)>'
```

The content of **/app/decorators/api/v1/acknowledgement_alert_decorator.rb** is shown below:

```
module Api
  module V1
    class AcknowledgementAlertDecorator < CustomDelegator
       ....
    end
  end
end
```


**/lib/custom_delegator.rb**

```
class CustomDelegator
 ...
end
```

To resolve that error I added following at the top of `/app/decorators/api/v1/acknowledgement_alert_decorator.rb` 

```
require_dependency "custom_delegator"
```

and that error went away. But similar errors are encountered in some another decorator, model or controller and I need to add the `require_dependency` statements in each of them.

**Summary:** 

When using `eager_load_paths` I will need to update each and every model, decorator, controller class which uses the utility module or classes placed in `lib` folder by adding the explicit `require_dependency` statement at the top of it. And that would become very much cumbersome because all the decorators in my code-base and a lot of models and controllers are using those utility modules and classes there in `lib` folder. 

**Question**: instead of getting into each and every such file and adding `require_dependency` statements in them, is there any better approach which I can employ using which with a minimal set of changes I can get rid of the dependency errors raised because of eager_loading?

**Observed**:

If I update the `autoload_paths` with `eager_load_paths`  in following manner 

```
    config.eager_load_paths << Rails.root.join('lib')
    config.eager_load_paths << Rails.root.join('app', 'decorators', 'concerns')
```

i.e. not selectively loading any directories and files under `lib` folder then `rails c staging_experimental` starts the rails console without any error. But in this case I temporarily removed the `scripts` directory from `lib` folder because my scripts were getting eager-loaded and also they were raising DB-errors

```
PG::UndefinedTable: ERROR:  relation "clients" does not exist
LINE 1: SELECT  "clients".* FROM "clients" ORDER BY "clients"."id" A...
                                 ^
: SELECT  "clients".* FROM "clients" ORDER BY "clients"."id" ASC LIMIT $1

PG::UndefinedTable: ERROR:  relation "providers" does not exist
LINE 1: SELECT  "providers".* FROM "providers" ORDER BY "providers"....
                                   ^
: SELECT  "providers".* FROM "providers" ORDER BY "providers"."id" ASC LIMIT $1
```

which was strange because the tables **do** exist. But I guess it is during the Rails initialization process eager loading happening before DB-communication and scripts executing as part of eager-loading those errors are raised. That is just my guess and have no idea on what happens internally. 


**Another Question**: 

When just adding `lib` folder to the `eager_load_paths` why no error is encountered? 

But when adding **selected** directories under `lib` folder like `lib/api` and files directly under `lib` folder are added to the `eager_load_paths` why error is encountered?

===================================================

The structure of my `lib` folder is:

```
- lib
    api_error.rb (this is a Module)
    api_token_authentication_helper.rb (this is a Module)
    api_v1_token_request_constraint.rb (this is a Class serving as a routing constraint)
    subdomain_constraint.rb (this is a Class serving as a routing constraint)
    supported_role.rb (this is a Class - a utility class)
    custom_delegator.rb  (this is a Class - a utility class)
    wrapped_custom_delegator.rb (this is a sub-class of CustomDelegator class)
    - api
        bad_request_error.rb (class Api::BadRequestError < StandardError)
        forbidden_error.rb (class Api::ForbiddenError < StandardError)
        not_found_error.rb (class Api::NotFoundError < StandardError)
        unauthorized_error.rb ( class Api::UnauthorizedError < StandardError )
        unprocessable_entity_error.rb ( class Api::UnprocessableEntityError < StandardError )
        - access_token
            expired_error.rb (class Api::AccessToken::CorruptError < Api::UnprocessableEntityError)
            invalid_error.rb (class Api::AccessToken::InvalidError < Api::ForbiddenError)
        - json
            here *.rabl files resides in a structured manner.
        - resource
            validation_errors.rb (class Api::Resource::ValidationErrors < Api::UnprocessableEntityError)
    - scripts
        runner scripts here
    - tasks
        custom rake tasks here
```

**Note: There are more directories and classes and modules nested inside it under `lib` folder which for brevity purpose not included above.**
   
The modules and classes added in `lib` folder are used across the application in various controllers, models and decorator classes.
 
**/config/routes.rb**

```
# Reference: http://stackoverflow.com/a/19781204/936494
class ActionDispatch::Routing::Mapper
  def draw(routes_name)
    instance_eval(File.read(Rails.root.join("config/routes/#{routes_name}.rb")))
  end
end

Rails.application.routes.draw do
  # Reference: http://stackoverflow.com/a/19781204/936494
  draw 'api/v1'
end
```

**/config/routes/api/v1.rb**

```
constraints ApiV1TokenRequestConstraint.new do
  scope module: 'api/v1', defaults: { format: :json } do
    ...
  end
end

constraints SubdomainConstraint.new do
  api_version(:module => "api/authentication",
               header: {
                  name: "Accept", value: "application/vnd.myapiapp.com; version=1"},
               defaults: { format: :json }) do
    post 'login' => 'sessions#create'
    delete 'logout' => 'sessions#destroy'
  end
end

constraints SubdomainConstraint.new do
  api_version(:module => "api/v1",
              header: { name: "Accept", value: "application/vnd.simplyhomeapp.com; version=1"},
              defaults: { format: :json } ) do
   
  ....
    resources :roles, only: [ :index, :show, :create, :update, :destroy ]
    resources :users, only: [ :index, :show, :create, :update, :destroy ]
  ....
end
```

@rafaelfranca Can you please provide your valuable inputs on the situation and questions I have?

**Comment by matthewd** [comment]
Please use the mailing list or StackOverflow for questions/help, where a wider community will be able to help you. We reserve the issues tracker for issues only.

**Comment by jiggneshhgohel** [comment]
@matthewd I had already posted on StackOverflow at http://stackoverflow.com/q/40110104/936494 but since I didn't received any responses there I had to ask about it in Rails repo. 

With the updates added to that SO post hoping somebody will come forward to provide his valuable guidance for the resolution of problems I am facing. 

Thanks.

**Comment by rafaelfranca** [comment]
You answer is also in the link that I sent.

**Comment by jiggneshhgohel** [comment]
@rafaelfranca does the following imply enabling `config.enable_dependency_loading = true`?

> You answer is also in the link that I sent.

If that is the case I will try that out. 

Also can you point me to some references or documentation going through which I can get answers to my following questions (quoted from comment https://github.com/rails/rails/issues/26814#issuecomment-254778348)

> When just adding lib folder to the eager_load_paths why no error is encountered?

> But when adding selected directories under lib folder like lib/api and files directly under lib folder are added to the eager_load_paths why error is encountered and I need to get into each and every file from which errors are raised and add `require_dependency` statements in them?

Thanks.
