### ISSUE TITLE
number_to_currency without unit return with space in first index

### ISSUE THREAD

**Issue by adrianoresende** [rails/rails#26816]
### Steps to reproduce
`<%= f.text_field :sell_price, value: number_to_currency(f.object.sell_price, unit: '', delimiter: '.', precision: 0) %>`

In page have mask javascript for this input, when have space in first index, is converted to '.' (point).

Rails view return ` 900.000` (space in first index)
After load mask javascript `.900.000`

`unit: ''` (no space in string) return with space which is not good for the currency field.

### Expected behavior
`number_to_currency` without `unit` return blank or no space for unit.

### Actual behavior
`number_to_currency` without `unit` return space + currency.

### Solution
`unit` with type string or nil.
If is nil, return no space.

### System configuration
**Rails version**: 4.2.6

**Ruby version**: 2.3.0p0 (2015-12-25 revision 53290) [x86_64-darwin15]

**Comment by prathamesh-sonpatki** [comment]
@adrianoresende This does not seem an issue to be `number_to_currency` helper. Please see reproduction script here - https://gist.github.com/e492533f6272bbfe6b0b4b323daa88d5.

Can you upload a sample app to github which reproduces the issue.

**Comment by adrianoresende** [comment]
@prathamesh-sonpatki Why does not seem a problem for you? I think it's not right to enter space in **currency**.
In script, line 48 should be like this `assert_equal '500'` (no space)

**Comment by prathamesh-sonpatki** [comment]
@adrianoresende The test in the script fails for me. Here is the result - 

```rb
# Running:

F

Finished in 0.018881s, 52.9633 runs/s, 52.9633 assertions/s.

  1) Failure:
BugTest#test_returns_success [number_to_currency_space_unit.rb:48]:
Expected: " 500"
  Actual: "500"

1 runs, 1 assertions, 1 failures, 0 errors, 0 skips
```

So I am not able to reproduce the issue.

**Comment by adrianoresende** [comment]
@prathamesh-sonpatki Thanks! I found the problem, for a while I downloaded language default for rails and space come of format of currency.

```
number:
    currency:
      format:
        delimiter: .
        format: ! '%u %n'
        precision: 2
        separator: ! ','
        significant: false
        strip_insignificant_zeros: false
        unit: R$
```
