### ISSUE TITLE
Appending format to path in routes can break tests

### ISSUE THREAD

**Issue by ostinelli** [rails/rails#26812]
We are allowing email addresses to be used as routes member `:id` in our JSON api. To do so, we set in our routes:

``` ruby
resources :users, constraints: { id: /[^\/]+/ }
```

With the new `ActionDispatch::Integration::Session` implementation, a format always gets appended to path for JSON routes (see [here](https://github.com/rails/rails/blob/v5.0.0.1/actionpack/lib/action_dispatch/testing/integration.rb#L413) and [here](https://github.com/rails/rails/blob/v5.0.0.1/actionpack/lib/action_dispatch/testing/integration.rb#L419)).

From our spec tests, when we issue a request with:

``` ruby
get '/users/user@example.com', as: :json
```

Then the `:id` param in `users#show` includes the format, so for instance instead of `user@example.com` the `:id` param is actually `user@example.com.json`. Hence we cannot find the user in the show action simply by:

``` ruby
user = User.find_by(email: params[:id])
```

As there's no user with email `user@example.com.json`.

Everything works fine using the method:

``` ruby
xhr :get, '/users/user@example.com'
```

...but it's being deprecated. Any suggestions?

Thank you,
r.

Using rails `5.0.0.1`.

**Comment by higorae** [comment]
Have you tried this way?
`resources :users, constraints: { id: /[^\/]+/ }, format: true`

**Comment by ostinelli** [comment]
> Have you tried this way?
> `resources :users, constraints: { id: /[^\/]+/ }, format: true`

Hi @higorae,
This allows for tests to pass but then you're forcing your API consumers to add a `.json` format at the end of the request, which to me does not make much sense.

I also want to point out that this format being forcefully added in tests has other consequences also.

For instance, we have client signing HTTP requests with their RSA keys. To do so, they build a string to sign (in pseudocode):

```
string_to_sign = client_id + "\n" +
  lower(http_verb) + "\n" +
  lower(path) + "\n" +
  date_header + "\n" +
  body
```

and then they sign it (this signature gets passed in the `Authorization` header):

```
signature = remove_newlines(base64(PKI_sha256_sign(UTF8_encoded(string_to_sign))))
```

When a request is received by the server, it will re-compute the signature based on the original request and then compare it to the one that got sent by the client in the `Authorization` header. If they don't match, the server will return a `401`.

In practice, everything works beautifully. However, tests don't pass.

This is because in the tests we specify as path `'/users/user@example.com`, but then the controller's `request.headers['REQUEST_URI']` is `/users/user@example.com.json`, hence the `string_to_sign` used on the client and on the server are different (and so are the resulting signatures).
