### ISSUE TITLE
Memory leak in ActiveSupport?

### ISSUE THREAD

**Issue by ce07c3** [rails/rails#26823]
### Steps to reproduce
- Create a new Rails 5.0.0.1 project with a single route, POST /leaks, which simply instantiates a Leak object (subclass of `ActiveRecord::Base`) - no need to persist
- Disable CSRF (this is not relevant to the leak) and hit it with a lot of HTTP requests to create some load
- Watch memory grow indefinitely(?) (from 60 to 140 MB in about 15 minutes)

### Expected behavior
Expected memory growth to stop at some point.

### Actual behavior
Memory keeps growing indefinitely, both for a "blank" Rails 5.0.0.1 project and my own.

From profiling my own project:
```
Leaked 29828 HASH objects of size 0/5228000 at: /Users/ce07c3/.rvm/gems/ruby-2.3.1/gems/concurrent-ruby-1.0.2/lib/concurrent/collection/map/non_concurrent_map_backend.rb:16
Leaked 29826 DATA objects of size 0/5249376 at: /Users/ce07c3/.rvm/gems/ruby-2.3.1/gems/concurrent-ruby-1.0.2/lib/concurrent/collection/map/mri_map_backend.rb:14
Leaked 14907 STRING objects of size 110447/596280 at: /Users/ce07c3/.rvm/gems/ruby-2.3.1/gems/concurrent-ruby-1.0.2/lib/concurrent/collection/map/non_concurrent_map_backend.rb:24
```
`concurrent-ruby` is used by `active-support` at least since 5.0.0.

### System configuration
**Rails version**: 5.0.0.1

**Ruby version**: 2.3.1

**Comment by ce07c3** [comment]
From `concurrent-ruby`:

```
      def initialize(options = nil)
        @backend = {}
      end
```
(https://github.com/ruby-concurrency/concurrent-ruby/blob/master/lib/concurrent/collection/map/non_concurrent_map_backend.rb#L15)

**Comment by prathamesh-sonpatki** [comment]
cc @matthewd

**Comment by rafaelfranca** [comment]
Is this in the production environment?

**Comment by ce07c3** [comment]
I will try again in production - are memory leaks fine in development environments or what is the take on your comment, @rafaelfranca? No pun, just so I know.

**Comment by rafaelfranca** [comment]
In development they are know to grow fast and keep some cache around but that doesn't mean that it is growing indefinitely.

**Comment by ce07c3** [comment]
@rafaelfranca seems fine in production - just didn't anticipate memory growing that much in development (it later went far beyond the 140 MB). In production the growth is around 0,1 MB every few minutes.

Thanks!
