### ISSUE TITLE
ActiveRecord "lazy" query fulfillment can break transaction scopes

### ISSUE THREAD

**Issue by Ikariusrb** [rails/rails#26827]
### Steps to reproduce
With a postgresql back-end, I have the following code in a controller:
```
    ActiveRecord::Base.transaction(isolation: :repeatable_read) do
      dbversion = DbVersion.find_by client_id: @reader.client_id
      day_schedules = DaySchedule.where( client_id: client_id )
      week_schedules = WeekSchedule.where( client_id: client_id )
    end
```
In development mode, what I see Rails log is:
```
  Reader Load (0.7ms)  SELECT  "readers".* FROM "readers" WHERE (serial = '202481595069867') LIMIT $1  [["LIMIT", 1]]
   (0.3ms)  BEGIN
   (0.1ms)  SET TRANSACTION ISOLATION LEVEL SERIALIZABLE
  DbVersion Load (0.4ms)  SELECT  "db_versions".* FROM "db_versions" WHERE "db_versions"."client_id" = $1 LIMIT $2  [["client_id", 1], ["LIMIT", 1]]
   (0.2ms)  COMMIT
  DaySchedule Load (0.6ms)  SELECT "day_schedules"."id", "day_schedules"."name", "day_schedules"."schedule", "day_schedules"."client_id" FROM "day_schedules" WHERE "day_schedules"."client_id" = $1  [["client_id", 1]]
  WeekSchedule Load (0.9ms)  SELECT "week_schedules"."id", "week_schedules"."name", "week_schedules"."client_id", "week_schedules"."monday_id", "week_schedules"."tuesday_id", "week_schedules"."wednesday_id", "week_schedules"."thursday_id", "week_schedules"."friday_id", "week_schedules"."saturday_id", "week_schedules"."sunday_id" FROM "week_schedules" WHERE "week_schedules"."client_id" = $1  [["client_id", 1]]
```

### Expected behavior
What is expected is that `COMMIT` indicating the end of the transaction should only occur after all the selects inside the transaction block have been completed.  

### Actual behavior
Due to lazy execution of selects, only the first select actually gets executed inside the transaction block, and the subsequent selects end up being deferred until after the transaction gets completed.   Figuring out what might be going on here the first time is... very challenging;  Logically, lazy deferrment of SQL operations declared inside a transaction should *never* be allowed.  Transactions are intended as concurrency control, and leaving it to the user to realize that a SQL operation declared inside a transaction block was deferred until after the transaction was committed is a recipe for bad things.
  
### Available Workaround
Currently, this can be worked around by adding ".load" to ActiveRecord queries inside a transaction block.  IMO, this should not be necessary, it should be default behavior.

### System configuration
**Rails version**: 5.0.0.1

**Ruby version**: 2.3.0

**Comment by Ikariusrb** [comment]
I have reviewed https://github.com/rails/rails/blob/933e11f8311e13c8d5e4355813ebcdbb50037ffc/activerecord/lib/active_record/transactions.rb - and I have a sneaking suspicion that rails does not view "SELECT" as a valid transaction "action";  I haven't fully grokked the code yet, but I suspect that because the code is attempting to manage the state of the ActiveRecord objects in conjunction with a transaction, it decides that there are no more actions, and issues a callback to close the transaction, regardless of the block scope.

Any confirmation of my suspicions and/or possible workarounds would be greatly appreciated.

**Comment by Ikariusrb** [comment]
It gets... more interesting.   It appears that ActiveRecord transactions are averse to selects which return more than one record;
```
    ActiveRecord::Base.transaction(isolation: :repeatable_read) do
      x = WeekSchedule.where( client_id: 1 ).first
      y = DaySchedule.where( id: x ).first
      z = DoorGroupLink.where( week_schedule: x ).first
    end
```
This works.  However- if you strip ".first" off the lines, it exhibits the same early COMMIT behavior that my original code does.

**Comment by rafaelfranca** [comment]
This is a really weird bug. 
Could you create a reproduction script with this template https://github.com/rails/rails/blob/master/guides/bug_report_templates/active_record_master.rb?

**Comment by rafaelfranca** [comment]
Oh. I know what is. `where` doesn't execute the query when it is called. You need to access it to it execute. If you only access it outside the block it will be executed outside the transaction. This is why using `load` and `first` works.

**Comment by Ikariusrb** [comment]
@rafaelfranca  - I figured out why it broke, but  I would argue that allowing lazy fulfillment inside a transaction block is a bad idea- it could easily lead to people's intended concurrency controls being broken without their realizing it.

**Comment by rafaelfranca** [comment]
Laziness of relations is well documented. Not allowing it inside of
transactions will require to Rails to couple relations to transaction just
to protect users for doing the wrong thing. I do not like the idea of being
that defensive.
