### ISSUE TITLE
Could not log sql.active_record event errors...

### ISSUE THREAD

**Issue by wadestuart** [rails/rails#26828]
I had to update one of my apps to head to get some of the actioncable fixes and I am seeing a ton of errors in the log file that seem to be related to f814585bb269f1dd2c275d6ae95d94d8e91d8061,  I am not doing anything weird with logging or my pg connections.  Has the interface changed here?  Any ideas how I would go about trying to diagnose why these errors are getting tossed?  It looks like it happens any time I have missed a Russian doll cache or cached model and it rebuilds as far as I can tell.   Using pg and memcached with the rails memcached cache store. 

### Expected behavior
Normal rails logging of events

### Actual behavior
Tons of errors ```Could not log "sql.active_record" event. TypeError: wrong argument type NilClass (must respond to :each) ["/home/deploy/.rvm/gems/ruby-2.3.1/bundler/gems/rails-8e76f6959efc/activerecord/lib/active_record/log_subscriber.rb:42:in `zip'", ```

### System configuration
**Rails version**:
Head  (edited to add 6aa378400218404f1002177f5457e296079ae255 to be specific)

**Ruby version**:
2.3.1

**Comment by wadestuart** [comment]
more info,   here is some dumpage from placing a binding.pry before line 42 on log_subscriber.rb

```[2] pry(#<ActiveRecord::LogSubscriber>)> payload[:binds]
=> [#<ActiveRecord::Relation::QueryAttribute:0x0000000a00e218
  @name="id",
  @original_attribute=nil,
  @type=#<ActiveRecord::ConnectionAdapters::PostgreSQL::OID::Uuid:0x0000000afa8d18 @limit=nil, @precision=nil, @scale=nil>,
  @value="928788ee-ac00-4405-b21f-8ca4301623c0",
  @value_before_type_cast="928788ee-ac00-4405-b21f-8ca4301623c0",
  @value_for_database="928788ee-ac00-4405-b21f-8ca4301623c0">,
 #<ActiveRecord::Attribute::WithCastValue:0x0000000a00faf0 @name="LIMIT", @original_attribute=nil, @type=#<ActiveRecord::Type::Value:0x0000000aa4beb0 @limit=nil, @precision=nil, @scale=nil>, @value=1, @value_before_type_cast=1>]```

```[3] pry(#<ActiveRecord::LogSubscriber>)> payload
=> {:sql=>"SELECT  \"users\".* FROM \"users\" WHERE \"users\".\"id\" = $1 LIMIT $2",
 :name=>"User Load",
 :binds=>
  [#<ActiveRecord::Relation::QueryAttribute:0x0000000a00e218
    @name="id",
    @original_attribute=nil,
    @type=#<ActiveRecord::ConnectionAdapters::PostgreSQL::OID::Uuid:0x0000000afa8d18 @limit=nil, @precision=nil, @scale=nil>,
    @value="928788ee-ac00-4405-b21f-8ca4301623c0",
    @value_before_type_cast="928788ee-ac00-4405-b21f-8ca4301623c0",
    @value_for_database="928788ee-ac00-4405-b21f-8ca4301623c0">,
   #<ActiveRecord::Attribute::WithCastValue:0x0000000a00faf0 @name="LIMIT", @original_attribute=nil, @type=#<ActiveRecord::Type::Value:0x0000000aa4beb0 @limit=nil, @precision=nil, @scale=nil>, @value=1, @value_before_type_cast=1>],
 :type_casted_binds=>["928788ee-ac00-4405-b21f-8ca4301623c0", 1],
 :statement_name=>"a1",
 :connection_id=>70424580}```

```[4] pry(#<ActiveRecord::LogSubscriber>)> payload[:type_casted_binds]
=> ["928788ee-ac00-4405-b21f-8ca4301623c0", 1]```

**Comment by maclover7** [comment]
Hi @wadestuart! Can you check and see if #26357 fixes this issue?

**Comment by tenderlove** [comment]
@maclover7 that PR will fix it, but it is the wrong way to fix this issue.

**Comment by wadestuart** [comment]
I tried it the error does go away but the reporting of cached entries is wrong (or it is breaking cache I have not dug in yet).  O think @tenderlove is right about it not being the solution.   There is also a review comment on the code talking about a defect.   I can try in more bits if there is another shot at it.

**Comment by wadestuart** [comment]
Confirmed fixed with those bits!  thank you!

**Comment by wadestuart** [comment]
@tenderlove @maclover7 

hmm,  I am still looking at this but it appears that there is still an issue here,  the logging is no longer throwing error spaghetti  but Rails.cache.fetch blocks seem to always fall through to the expensive op and not recreate the entry after these changes.

What I am seeing is cache misses for any Rails.cache,  the code inside the blocks being executed and no cache entry being created.  Tested by placing a logger in the block to show the fall through,  seeing the miss entries in the log and testing with various backends (built in memcached, dalli, file) where memcached -vv shows the fail read (miss) but no attempt to store. 
 

Simple test cache seems to be:

```
  def cached_is_cold?
    Rails.cache.fetch([self.class.name, id, updated_at, :is_cold]), expires_in: 1.hour) do
      logger.warn("Doing expensive call")
      return true if   some_expensive_sql 
    end
  end
```
