### ISSUE TITLE
PostgreSQL DB constraint 'DEFERRED' is not copied to test DB

### ISSUE THREAD

**Issue by aried3r** [rails/rails#26824]
### Steps to reproduce

I added a migration to add a `DEFERRED` constraint to PostgreSQL using:

```Ruby
class AddUniquenessContraintToProjectUserRole < ActiveRecord::Migration[5.0]
  def up
    execute <<-SQL
      alter table project_user_roles
        add constraint project_user_uniqueness unique (project_id, user_id)
        DEFERRABLE INITIALLY IMMEDIATE;
    SQL
  end

  def down
    execute <<-SQL
      alter table project_user_roles
        drop constraint if exists project_user_uniqueness;
    SQL
  end
end
```

I confirmed using `psql`:
```
\c dev-db
\d project_user_roles
...
Indexes:
    "project_user_uniqueness" UNIQUE CONSTRAINT, btree (project_id, user_id) DEFERRABLE
```
I'm not sure why `INITIALLY IMMEDIATE` is missing, the migrations contains it:
```
== 20161019113453 AddUniquenessContraintToProjectUserRole: migrating ==========
-- execute("      alter table project_user_roles\n        add constraint project_user_uniqueness unique (project_id, user_id)\n        DEFERRABLE INITIALLY IMMEDIATE;\n")
   -> 0.0016s
== 20161019113453 AddUniquenessContraintToProjectUserRole: migrated (0.0016s) =
```

When I run `rails db:test:prepare` the constraint is not copied:
```
\c test-db
\d project_user_roles
...
Indexes:
    "project_user_uniqueness" UNIQUE, btree (project_id, user_id)
```

This leads to working code in development, but not during testing, making a lot of specs fail in our case.

### Expected behavior
The constraint should be copied over to the test DB.

### Actual behavior
The constraint is lost in the process.

### System configuration
**Rails version**: 5.0.0.1

**Ruby version**: 2.3.1

**Comment by rafaelfranca** [comment]
Which bump format are you using? If you are using ruby it will not work. Only the sql dump format will work.

**Comment by aried3r** [comment]
I'm not aware of an option to change to format, where can I see what format Rails is using? (Thus, I am certain that I'm using the default format.)

**Comment by rafaelfranca** [comment]
http://guides.rubyonrails.org/configuring.html search for `config.active_record.schema_format`

**Comment by aried3r** [comment]
Ah, that! I was confused for a second. Yeah, I'm using the `:ruby` format instead of the `:sql` format, found it [here](http://edgeguides.rubyonrails.org/active_record_migrations.html#types-of-schema-dumps).

Are there plans to enable this in the `:ruby` format? I was unable to find any issues regarding this.

**Comment by rafaelfranca** [comment]
> Are there plans to enable this in the :ruby format?

No. `:ruby` format doesn't support database speicific things.
