### ISSUE TITLE
Allow action_on_unpermitted_parameters to be configured at the controller level

### ISSUE THREAD

**Issue by jeffblake** [rails/rails#26831]
I'm facing a situation where I would like to have `action_on_unpermitted_parameters` be `:raise` for some controllers, and `:log` for others. 

For example, for my public API I want to use `:raise`:

```
  rescue_from ActionController::ParameterMissing do |e|
    render json: {error: e.message}, status: :bad_request
  end
  rescue_from ActionController::UnpermittedParameters do |e|
    render json: {error: e.message, params: e.params}, status: :bad_request
  end
```

So that I can fail early and let API consumers fix their request, rather than ignoring unpermitted parameters and potentially leave the API consumers scratching their head as to what they are doing wrong.

For all other controllers, I'd like to use `:log` so that updates are still processed, ignoring any unpermitted parameters.

Thoughts?

**Comment by rafaelfranca** [comment]
Makes sense. Could you work in a PR?

Closing since we don't get feature requests in the issue tracker.

**Comment by benoittgt** [comment]
Is it still something that can't be done?

**Comment by rafaelfranca** [comment]
I don't think this is possible to implement without coupling the parameters to the controller class. Right now `Parameters` doesn't know anything about the controller that it is running. And the behavior on unpermitted parameter is implemented in `Parameters`.

Also, a same action can filter the the same `Parameters` instance in different ways. This means that if `action_on_unpermitted_parameters` is `:raise` both calls will raise one exception.

In this case I don't recommend relying on the `Parameters` behavior to validate the schema of the request. There are many more robust solutions for this.

**Comment by benoittgt** [comment]
Thanks @rafaelfranca

**Comment by exterm** [comment]
@rafaelfranca can you elaborate on "many more robust solutions"?

**Comment by benoittgt** [comment]
http://dry-rb.org/gems/dry-validation/ maybe?

**Comment by rafaelfranca** [comment]
You could wrap your parameters in an object that validates the schema of the request. dry-validations is one of the things that implement it.

**Comment by coorasse** [comment]
This is potentially interesting to others: you can listen to this event:

`ActiveSupport::Notifications.subscribe('unpermitted_parameters.action_controller')`
