### ISSUE TITLE
Is it really necessary to override the `*_type=` method for ActiveRecord Polymorphic Association with Single Table Inheritance?

### ISSUE THREAD

**Issue by vaharoni** [rails/rails#26849]
The documentation [here](http://api.rubyonrails.org/classes/ActiveRecord/Associations/ClassMethods.html#module-ActiveRecord::Associations::ClassMethods-label-Polymorphic+Associations) seems to suggest it is necessary to override `attachable_type=` in order to ensure that that the base class `Post` is the one stored in `attachable_type` rather than `GuestPost` or `MemberPost`:

``` ruby
class Asset < ActiveRecord::Base
  belongs_to :attachable, polymorphic: true

  def attachable_type=(class_name)
     super(class_name.constantize.base_class.to_s)
  end
end
```

Is this truly the case? A repo I created [here](https://github.com/vaharoni/arpolytest) to implement the example in the documentation cannot reproduce an issue with straight forward assignment to `attachable` in all `ActiveRecord` versions. 

It seems that [this line](https://github.com/rails/rails/blob/master/activerecord/lib/active_record/associations/belongs_to_polymorphic_association.rb#L14) already calls the `base_class` for us.

If the issue the documentation attempts to point our attention to is direct assignment to `attachable_type`, e.g. when receiving data on form submission, then I suggest to specify it so that developers don't feel they need to override `*_type=` methods for every polymorphic association that can potentially receive an STI model.

If you can confirm this, then I'm happy to update the documentation to something like the following (additions in bold):

Note: The `attachable_type=` method is being called when assigning an `attachable`. The `class_name` of the `attachable` is passed as a `String`. **By default, `ActiveRecord` sets `attachable_type` to the base class when you assign a model to `attachable`. However, in case the `attachable_type` is updated directly, for example when receiving data from a form, you'll need to ensure this behavior manually. The code below demonstrates how to allow accepting `attachable_type` from a form by overriding the `attachable_type=` method.**

**Comment by maclover7** [comment]
Can you open up a PR, and then we can continue the discussion there? Thanks!

**Comment by vipulnsward** [comment]
Note sure what https://github.com/vaharoni/arpolytest/blob/master/run.rb#L7 is meant to describe. 
Apart from that looks 👍 to update. That documentation has been arounds since 2006, somewhere it might have been fixed.
