### ISSUE TITLE
render json: Model.all does not works as guide says

### ISSUE THREAD

**Issue by marvin-min** [rails/rails#26845]
### Steps to reproduce
1. create a api based rails project
2. create Model and initial some data
3. overwrite the `to_json` method and specify some of the attributes of the model
4. create controller
5. render JSON format by using `render json: Model.all`

### Expected behavior
Only the specified fields be return in the json.
here is the reference comes from [Rails Guide](http://guides.rubyonrails.org/layouts_and_rendering.html)
```
You don't need to call to_json on the object that you want to render. If you use the :json option, render will automatically call to_json for you.
```

### Actual behavior
All fields of the model was returned in the json object

### System configuration
**Rails version**:
   `Rails 5.0.0.1`
**Ruby version**:
 `ruby 2.3.0p0 (2015-12-25 revision 53290) [x86_64-darwin14]`

**Comment by marvin-min** [comment]
BTW, if I overwirte the `as_json` method and calls `as_json` in the controller like `render json: Model.all.as_json`. it works as I expected.

**Comment by rafaelfranca** [comment]
The guide is talking about `to_json` in the model object. You are calling `render json:` with a relation object and overriding the `to_json` method in the model instance will not change the behavior of `to_json` in the relation object.

**Comment by marvin-min** [comment]
@rafaelfranca Thanks for your explanation.

**Comment by betesh** [comment]
I want to understand better why we don't call as_json on relations (it seems that we end up calling serializable_hash on each element instead), and I figured a good place to start would be the code itself.  I looked around and was unable to find it in the Rails source code.  ([This](https://github.com/rails/rails/blob/v5.0.1/actionpack/lib/action_controller/metal/renderers.rb#L156) looked like it would be the place but it's not.)

@rafaelfranca Could you point me to the code that decides whether to call as_json on an object when rendering it as json?
