### ISSUE TITLE
Wrong precision in number_to_human_size and number_to_human

### ISSUE THREAD

**Issue by plentz** [rails/rails#26858]
### Steps to reproduce

```ruby
irb(main):014:0> include ActionView::Helpers::NumberHelper
=> Object
irb(main):015:0> 668930519.to_f/1024/1024
=> 637.941855430603
irb(main):016:0> number_to_human_size(668930519)
=> "640 MB"
irb(main):017:0> number_to_human_size(668930519, precision: 2)
=> "640 MB"
irb(main):018:0> number_to_human_size(668930519, precision: 3)
=> "638 MB"
```

### Expected behavior
`number_to_human_size(668930519)` should be equal to `number_to_human_size(668930519, precision: 3)` (which is `638 MB`), because the default is `precision: 3`.

### Actual behavior
`number_to_human_size(668930519)` results in `640 MB`

### System configuration
**Rails version**: Rails 5.0.0.1

**Ruby version**: ruby 2.3.1p112 (2016-04-26 revision 54768) [x86_64-darwin16]

**Comment by plentz** [comment]
Important: it only happens when I set `config.i18n.default_locale = :"pt-BR"` in my application.rb

**Comment by rafaelfranca** [comment]
So maybe your locale is setting the default to 2 not 3?

**Comment by plentz** [comment]
@rafaelfrance yep. sorry dude. it all comes down to [this](https://github.com/svenfuchs/rails-i18n/blob/master/rails/locale/pt-BR.yml#L187).
