### ISSUE TITLE
ERROR -- : Couldn't cleanly terminate all actors in 10 seconds!

### ISSUE THREAD

**Issue by aliAsadi92** [rails/rails#26857]
When I write:
```ruby
bundle exec spring rails c
```
I take this error:
```ruby
ERROR -- : Couldn't cleanly terminate all actors in 10 seconds!
```
Is there someone to help me please?

**Comment by rafaelfranca** [comment]
Please use the mailing list or StackOverflow for questions/help, where a wider community will be able to help you. We reserve the issues tracker for issues only.

**Comment by aliAsadi92** [comment]
yeah Thank you 👍

**Comment by gualopezb** [comment]
I am having the same issue by using celluloid. @aliAsadi92 have you solved this problem?
