### ISSUE TITLE
Prevent creation of database columns/tables with a reserved name

### ISSUE THREAD

**Issue by ruppalsingh** [rails/rails#26850]
Since #2629 is stale and closed:

Making a personal finance app and halfway through my endeavour, I find out that I have to rename my model and controller and all associations because "transactions" is reserved. I only found this out when I was creating an association with another model and tried to `annotate` it. ActiveRecord reserves `transaction_id` apparently.

Ideally, one should be warned at the time of generating a model/resource that the table name/column name is reserved and might cause issues down the line. That would be in line with Rails being developer friendly.

I use Rails for my web-development hobby, because it's friendly and quicker to develop in. Did not expect such a roadblock.

**Comment by rafaelfranca** [comment]
Thank you so much for the issue but we don't take feature request on the issue tracker. We recommend you to try to implement the feature and send us a pull request or if you are in doubt if the feature will be accepts ask in Rails Core mailing list for feedback.

**Comment by rafaelfranca** [comment]
We can't prevent this kind of thing. Even that we use those methods internally you should be able to create a table called transactions or a column called transaction_id and use active record configurations to work around this overriding limitation.
