### ISSUE TITLE
certificate B: certificate verify failed ( https://api.rubygems.org/specs.4.8.gz)

### ISSUE THREAD

**Issue by muhammadkamran113** [rails/rails#26873]
Hello,

I have installed ruby by ruby installer on windows 7 v  2.3.1 64 bit. I am getting this issue 

> ERROR: Could not find a valid gem 'compass' (>= 0), here is why: Unable to download data from https://rubygems.org/ - SSL_connect retur ned=1 errno=0 state=SSLv3 read server certificate B: certificate verify failed ( https://api.rubygems.org/specs.4.8.gz) C:\Users\Muhammad Kamran>gem install net_http_ssl_fix ERROR: Could not find a valid gem 'net_http_ssl_fix' (>= 0), here is why: Unable to download data from https://rubygems.org/ - SSL_connect retur ned=1 errno=0 state=SSLv3 read server certificate B: certificate verify failed ( https://api.rubygems.org/specs.4.8.gz)

I have updated the windows, updated the system variable path. Done all what i can do while searching on  internet. Its been weeks now. Please help me. what can i do to over come this problem.

**Comment by prathamesh-sonpatki** [comment]
Please use stackoverflow or other medium for posting questions where a wider community can help you, we reserve the issue tracker for bug reports only, thanks.

This seems to be an issue with your internet/firewall settings, definitely not an issue with rails.
