### ISSUE TITLE
Sanitized html on edgeguides

### ISSUE THREAD

**Issue by knightq** [rails/rails#26887]
Have a look at http://edgeguides.rubyonrails.org/active_record_validations.html

I see this:

![Escaped HTML](https://cloud.githubusercontent.com/assets/157528/19677965/1293f4d2-9a9c-11e6-94a9-9202ca9302e9.png)

**Comment by sevenseacat** [comment]
Yep, another one like mentioned in #26886

**Comment by prathamesh-sonpatki** [comment]
Closing as duplicate of #26886, thanks @knightq :+1:
