### ISSUE TITLE
ActiveRecord: unable to update records with a `has_one, through:` relationship

### ISSUE THREAD

**Issue by ianks** [rails/rails#26884]
### Steps to reproduce

I have a working example here: https://gist.github.com/ianks/f934a6183b401254099c9e710b23217b
### Expected behavior

I should be able to update the relationship.
### Actual behavior

ActiveRecord is unable to find the primary_key, so it fails with a:

```
TypeError: nil is not a symbol nor a string
```

If I include a primary key, everything works as expected.
### System configuration

**Rails version**: 5.0.0

**Ruby version**: 2.3.1

**Comment by bogdanvlviv** [comment]
Maybe, we should to add ability to set id for `create_join_table`? i think this can be useful and give some flexibility.

**Comment by maclover7** [comment]
Looks like we overwrite `id` to be `false` [here](https://github.com/rails/rails/blob/master/activerecord/lib/active_record/connection_adapters/abstract/schema_statements.rb#L344).

**Comment by al2o3cr** [comment]
`create_join_table` was not designed to handle creating arbitrary tables - it's specifically designed to create the no-extra-attributes tables needed by `has_and_belongs_to_many` - see #4726 for additional detail.
