### ISSUE TITLE
Multi pages were broken

### ISSUE THREAD

**Issue by YangHungTW** [rails/rails#26886]
Here's the broken pages link:

[Active Record and PostgreSQL](http://edgeguides.rubyonrails.org/active_record_postgresql.html)

[Contributing to Ruby on Rails](
http://edgeguides.rubyonrails.org/contributing_to_ruby_on_rails.html#contributing-to-the-rails-documentation)

**Comment by knightq** [comment]
Another one on ActiveRecord Validation page.
[Have a look](http://edgeguides.rubyonrails.org/active_record_validations.html)

**Comment by prathamesh-sonpatki** [comment]
cc @rafaelfranca

**Comment by kundankumar** [comment]
I also encountered few (it seems all links in 'Guides' dropdown menu leads to broken pages)

**Comment by msl12** [comment]
And here:

http://edgeguides.rubyonrails.org/action_cable_overview.html

**Comment by rafaelfranca** [comment]
Fixed now.
