### ISSUE TITLE
[SanitizeHelper] sanitize does not work in title

### ISSUE THREAD

**Issue by Javix** [rails/rails#26881]
### Expected behavior

A title should be displayed with HTML escaped tags passed in to sanitize `tags` option.

### Actual behavior
Tell us what happens instead
Calling `sanitize` inside `title` tag has no effect:
```
<title><%= sanitize "H<sub>2</sub>O", tags: %w(sub sup), attributes: %w(title)%></title>
```

### System configuration
**Rails version**: `4.2.5`

**Ruby version**: `2.3.0`

**Comment by rafaelfranca** [comment]
What is the generated HTML and what is the expected generated HTML?

**Comment by Javix** [comment]
@rafaelfranca the generated HTML is the same, I think it is more the display issue; Here is what it should look like:

![image](https://cloud.githubusercontent.com/assets/83579/19676243/64576f64-9a93-11e6-8e4a-33ec658ec384.png)

When I call `sanitize` the same way in a view, it works as needed and the display is correct. I wonder why it is not the case for the `<title>`tag.

**Comment by rafaelfranca** [comment]
What doesn't work in title? How it is displayed it is up to the browser. Which HTML is being generated when you use `sanitize` inside `title` and what are you expected?

**Comment by Javix** [comment]
Here is how the page title looks like:
https://www.dropbox.com/s/qzd1sruqh1vjwnb/Screenshot%202016-10-25%2017.24.22.png?dl=0

As you see, the navigator tab displays the title with `sub` tags what it should not compared the way it is displayed in the page. I believed that `sanitize` would work the same way everywhere in the page.

**Comment by rafaelfranca** [comment]
This is how HTML works. You can't put tags inside `<title>`. `sanitize` can't know about the context that it is being used. It is doing the correct thing.

**Comment by Javix** [comment]
Good to know that. Thank you for your help.
