### ISSUE TITLE
ActiveRecord can't do the correctly parser of object model from the database.

### ISSUE THREAD

**Issue by herminiotorres** [rails/rails#26892]
### Steps to reproduce

This zip is a rails app with step-by-step for reproduce the bug.
[roles.zip](https://github.com/rails/rails/files/551732/roles.zip)
### Expected behavior

When I use the execute query it returns data properly with the `created_at` and `updated_at` the populated.

```
>> result = ActiveRecord::Base.connection.execute("select * from roles where id = 1")
   (0.8ms)  select * from roles where id = 1
=> #<PG::Result:0x007fcf9d709a30 status=PGRES_TUPLES_OK ntuples=1 nfields=5 cmd_tuples=1>
>> result.first
=> {"id"=>1, "name"=>"admin", "active"=>true, "created_at"=>"2016-10-25 02:54:25.568513", "updated_at"=>"2016-10-25 02:54:25.568513"}
```
### Actual behavior

When I use the model it returns data without the `created_at` and `updated_at` the populated.

```
>> Role.last
  Role Load (24.4ms)  SELECT  "roles".* FROM "roles" ORDER BY "roles"."id" DESC LIMIT $1  [["LIMIT", 1]]
=> #<Role id: 1, name: "admin", active: true, created_at: nil, updated_at: nil>
```
### System configuration

**Rails version**: `5.0.0.1`

**Ruby version**: `ruby 2.3.1p112 (2016-04-26 revision 54768) [x86_64-darwin14]`

**Comment by herminiotorres** [comment]
### Content of the file
The application is a default rails app, where I just added this file `time_zones.rb` in the folder `config/initializers/`, with this content:
```
Rails.application.config.time_zone = 'Brasilia'
Rails.application.config.active_record.default_timezone = 'Brasilia'
```

**Comment by maclover7** [comment]
Hi @herminiotorres! On Rails master, I am not able to reproduce the issue using [this reproduction script](https://gist.github.com/maclover7/cbd0cffba588d870662060fae007ba0b).

**Comment by Ser1aL** [comment]
@herminiotorres 
Jon, try this [script](https://gist.github.com/Ser1aL/31b31d335f8fe80853cf049584970725).

**Comment by Ser1aL** [comment]
I think I know what is the issue. 

@herminiotorres you shouldn't be setting `Rails.application.config.active_record.default_timezone` to anything except `:utc` or `:local`. 

This time_zones.rb might give you what you're expecting: 
```
Rails.application.config.time_zone = 'Brasilia'
Rails.application.config.active_record.default_timezone = :utc
```

**Comment by rafaelfranca** [comment]
oh. that is true. Maybe we need to document it better. @herminiotorres could you take a look in the documentation and see if it needs a update and open a PR?

**Comment by rafaelfranca** [comment]
oh. that is true. Maybe we need to document it better. @herminiotorres could you take a look in the documentation and see if it needs a update and open a PR?
