### ISSUE TITLE
Passing a non ActiveModel object to form_for throws an exception when rendering the view

### ISSUE THREAD

**Issue by estebanz01** [rails/rails#26894]
### Steps to reproduce

create a view with the following info:

**admin.rb**:
```ruby
class Admin
  attr_reader :user_id
  attr_accessor :errors

  def initialize(user_id)
    @user_id = user_id
     self.errors = []
  end
end
```

**new.html.erb**:
```erb
<% object = Admin.new %>
<%= form_for object, as: :admin, url: admin_path do |form|
  form.select :user_id,
              options_for_select([['User A', 1], ['User B'], 2]), 
              { include_blank: 'Select...' },
              {}
  form.submit 'Submit'
end %>
```

### Expected behavior
It should render the view with a select element and a submit button.

### Actual behavior
It throws an exception:
```
no implicit conversion of String into Integer (ActionView::Template::Error)
```

I found that this exception is triggered here: https://github.com/rails/rails/blob/4-0-stable/actionpack/lib/action_view/helpers/active_model_helper.rb#L35 because is trying to call `object.errors['user_id']`.

This doesn't happen in **Rails version**: 3.2-stable.

### System configuration
**Rails version**: 4.0-stable.

**Ruby version**: 2.2.4

### My possible solutions
I can open a PR with one of the following approaches:

(1) Update the `error_messages` method (defined here https://github.com/rails/rails/blob/4-0-stable/actionpack/lib/action_view/helpers/active_model_helper.rb#L34) to:
```ruby
def error_messages
  object.errors.is_a?(ActiveModel::Errors) && object.errors[@method_name]
end
```
(2) Update `object_has_errors?` method (defined here https://github.com/rails/rails/blob/4-0-stable/actionpack/lib/action_view/helpers/active_model_helper.rb#L40) to:
```ruby
def object_has_errors?
  object.respond_to?(:errors) && object.errors.respond_to?(:full_messages) && error_message.present?
end
```

The latter option is a regression to this: https://github.com/rails/rails/blob/3-2-stable/actionpack/lib/action_view/helpers/active_model_helper.rb#L42

Let me know what do you think about this.

**Comment by guilleiguaran** [comment]
We expect to objects passed to `form_for` to be `ActiveModel-compliant`, that is that they pass ActiveModel::Lint::Tests, you can verify this yourself with simple test:

```ruby
class LintTest < ActiveSupport::TestCase
  include ActiveModel::Lint::Tests

  def setup
    @model = Admin.new
  end
end 
```

The easier way to make your objects ActiveModel-compliant is using [ActiveModel::Model](http://api.rubyonrails.org/classes/ActiveModel/Model.html)

Also note that branch `4-0-stable` (and all 4.x branches) is unsupported and is not receiving fixes anymore.
