### ISSUE TITLE
How to monitor DB connections?

### ISSUE THREAD

**Issue by Paxa** [rails/rails#26898]
I have suspicion that my application have leaking db connections that being borrowed and not returned at the right time.

I could not find feature to get connection_pool stats, so I had to dig deep and make assumptions:

``` ruby
# in config.ru

stats_proc = Proc.new do |env|
  pool = ActiveRecord::Base.connection_pool.instance_eval { @available }
  connections = ActiveRecord::Base.connection_pool.instance_eval { @connections }

  connections.each do |c|
    if c.in_use?
      puts "\nConnection taken by:"
      puts c.taken_by
    end
  end

  @connection_pool = {
    max: ActiveRecord::Base.connection_pool.size,
    total: connections.size,
    busy: connections.count {|c| c.in_use? },
    dead: connections.count {|c| c.in_use? && !c.owner.alive? },
    num_waiting: pool.num_waiting,
    checkout_timeout: ActiveRecord::Base.connection_pool.checkout_timeout
  }

  ['200', {'Content-Type' => 'application/json'}, [JSON.pretty_generate(@connection_pool)]]
end

map '/stats' do
  run stats_proc
end
```

Then I wanted to see where my connections are being acquired:

``` ruby
class ActiveRecord::ConnectionAdapters::AbstractAdapter
  attr_accessor :taken_by
end

class ActiveRecord::ConnectionAdapters::ConnectionPool
  alias_method :_orig_acquire_connection, :acquire_connection

  def acquire_connection(*args)
    taken_by = caller
    #puts "\nGetting connection:"
    #puts taken_by
    _orig_acquire_connection.tap {|c| c.taken_by = caller }
  end
end
```

---

After another couple hours I found that `ActiveRecord::QueryCache` always acquire new connection before every request goes to controller. SO no matter if I do anything with database or not, ActiveRecord will keep connection used (locked) during all request (means taken from connection_pool, so other threads can not use this connection).

To prevent this strange behaviour I had to make:

``` ruby
class ActiveRecord::QueryCache
  def self.run
    [true, nil]
  end

  def self.complete(state)
    nil
  end

  def self.install_executor_hooks(executor = ActiveSupport::Executor)
    executor.register_hook(self)

    executor.to_complete do
      if ActiveRecord::Base.connection_pool.active_connection? && !ActiveRecord::Base.connection.transaction_open?
        ActiveRecord::Base.clear_active_connections!
      end
    end
  end
end
```

---

I think it will be nice to have:
1. connection_pool stats accessor, e.g. `ActiveRecord::Base.connection_pool.stats` or separate methods for each metrics (created connections, borrowed connections, dead connections, number of consumers waiting for connection)
2. A way to track where connection was acquired, may be via `ActiveSupport::Notifications`
3. Prevent `ActiveRecord::QueryCache` from obtaining db connection on every request. I'm thinking it can be achieved by setting thread variable.

``` ruby
# in query_cache.rb
    def self.run
      Thread.current[:'active_record.query_cache_enabled'] = true
    end

    def self.complete(enabled)
      if ActiveRecord::Base.connected?
        ActiveRecord::Base.connection.clear_query_cache
        ActiveRecord::Base.connection.disable_query_cache! unless enabled

        unless ActiveRecord::Base.connection.transaction_open?
          ActiveRecord::Base.clear_active_connections!
        end
      end
    end

# in connection_pool.rb
      def acquire_connection(checkout_timeout)
        if conn = @available.poll || try_to_checkout_new_connection
          conn
        else
          reap
          @available.poll(checkout_timeout)
        end.tap {|conn| Thread.current[:'active_record.query_cache_enabled'] && conn.enable_query_cache! }
      end
```

What do you think?

**Comment by matthewd** [comment]
Sorry I missed this earlier.

#26978 should address 3.

For 2, you can use checkin/checkout callbacks.

As for 1, do you want to PR a `stat` method onto the ConnectionPool? (I'm thinking it would return a hash as you built above, along the lines of `GC.stat`.)

**Comment by Paxa** [comment]
@matthewd I will try to make PR

What do you mean by `GC.stat`?

**Comment by matthewd** [comment]
`GC.stat` is a core ruby method, which returns stats on the GC behaviour, as a hash*.

I just mention it because it shows a precedent for a reasonable way to provide this sort of information, and gives us a method name.

\* it also supports individual requests via an extra parameter, but we don't need to worry about that, because the hash allocation doesn't affect our results.

**Comment by rafaelfranca** [comment]
@matthewd can this be closed now?
