### ISSUE TITLE
Has and belongs to many documentation

### ISSUE THREAD

**Issue by j-dexx** [rails/rails#26890]
[Guides Link](http://guides.rubyonrails.org/association_basics.html#has-and-belongs-to-many-association-reference#methods-added-by-has-and-belongs-to-many-collection-delete-object)

> The collection.destroy method removes one or more objects from the collection by running destroy on each record in the join table, including running callbacks. This does not destroy the objects.

This can't be correct for has and belongs to many, as there isn't a join model to initialize and run callbacks on.

In addition to me the warning on delete doesn't make sense either.

> This does not trigger callbacks on the join records.

I assume the content was just copied from `has_many` when the docs were written.  Happy to submit a PR but not sure what you'd want it to say instead, I'm not sure if it's just an alias on HABTM?  I'm assuming not

**Comment by rafaelfranca** [comment]
You are right about the two points. What we can write is that it remove the records from the join table but doesn't destroy the objects. No need to talk about callbacks.

Could you submit the PR?

**Comment by j-dexx** [comment]
Will do.
