### ISSUE TITLE
Same validation is not called in different contexts

### ISSUE THREAD

**Issue by jughead** [rails/rails#26903]
### Steps to reproduce

``` ruby
begin
  require 'bundler/inline'
rescue LoadError => e
  $stderr.puts 'Bundler version 1.10 or later is required. Please update your Bundler'
  raise e
end

gemfile(true) do
  source 'https://rubygems.org'
  gem 'activerecord', '4.1.6'
  gem 'sqlite3'
end

require 'active_support/core_ext/object'
require 'active_record'
require 'minitest/autorun'
require 'logger'

Minitest::Test = MiniTest::Unit::TestCase unless defined?(Minitest::Test)

ActiveRecord::Base.establish_connection(adapter: 'sqlite3', database: ':memory:')
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :users, force: true do |t|
  end

  create_table :candies, force: true do |t|
    t.integer :user_id
    t.decimal :price
  end
end

class User < ActiveRecord::Base
  has_many :candies

  # It seems these two validations are some how combined. And the first one
  # is skipped.
  with_options on: :prices do |obj|
    obj.validate :check_candies
  end

  with_options on: [:create, :update] do |obj|
    obj.validate :check_candies # looks like it replaces previous context options
  end

  def check_candies
    errors.add(:base, :invalid) if candies.any?(&:invalid?)
  end
end

class Candy < ActiveRecord::Base
  belongs_to :user
  validate :check_price

  def check_price
    errors.add(:price, :low) if price < 0.10
  end
end

class BugTest < Minitest::Test
  def test_context_validation_stuff
    user = User.new
    user.save(validate: false)
    candy = Candy.new(user: user, price: 0)
    candy.save(validate: false)
    user.reload

    assert user.invalid?(:prices) #=> false
  end
end
```
### Expected behavior

I would expect it to call `check_candies` when I validate the `user` with `:prices` context. 
I would better split the validation according to context rather specifying `on` array in each of the validate statement
### System configuration

**Rails version**: 4.1.6
**Ruby version**: 2.1.2p95

**Comment by jughead** [comment]
So the problem is actually:
``` ruby
with_options on: :prices do |obj|
  obj.validate :check_candies
end

with_options on: [:create, :update] do |obj|
  obj.validate :check_candies, if: :special_condition_met?
end
```

This is the reason I splitted them. I know it looks strange but we can assume this is quite a huge old model which I try to refactor step by step.

**Comment by yuktikhurana** [comment]
@jughead 
As per [this](https://github.com/rails/rails/blob/92703a9ea5d8b96f30e0b706b801c9185ef14f0e/activesupport/lib/active_support/core_ext/object/with_options.rb#L51)
I feel it's the expected behavior of **with_options** . It will always merge the options given.

So 
```
with_options on: :prices do |obj|
  obj.validate :check_candies
end

with_options on: [:create, :update] do |obj|
  obj.validate :check_candies, if: :special_condition_met?
end
```

translates to 
`validate :check_candies, on: [:create, :update] , if: :special_condition_met?`

You might have to write a custom if condition for your validations. If there are more than one validation with similar scenario then you can use the with_options as in the example below.

```
  with_options if: :can_check_candies? do |obj|
    obj.validate :check_candies
  end

  private

    def can_check_candies?
       #your conditions
    end
```

**Comment by sgrif** [comment]
"Fixing" this would break behavior that's been around for quite some time. I expect a lot of applications are relying on this behavior to change callback options in subclasses or based on some condition.

**Comment by jughead** [comment]
@yuktikhurana the link you give tells about nesting and not about consequent calls.
