### ISSUE TITLE
Can't cast ActionController::Parameters as hash for hstore attributes

### ISSUE THREAD

**Issue by mxie** [rails/rails#26904]
### Steps to reproduce

Create a record where you'd assign the attribute using params that have nested hashes:

``` ruby
irb(main):001:0> params = ActionController::Parameters.new(user_answer: { "stuff" => 1, "more stuff" => 2 })
=> <ActionController::Parameters {"user_answer"=>{"stuff"=>1, "more stuff"=>2}} permitted: false>

irb(main):002:0> user_answer_params = params.require(:user_answer).permit!
=> <ActionController::Parameters {"stuff"=>1, "more stuff"=>2} permitted: true>

irb(main):005:0> Submission.create(answer: user_answer_params)
```

Feel free to clone down https://github.com/mxie/hstore-casting-bug to test.
### Expected behavior

The record should save.
### Actual behavior

A `TypeError` is raised:

``` ruby
irb(main):005:0> Submission.create(answer: user_answer_params)
   (0.2ms)  BEGIN
   (0.2ms)  ROLLBACK
TypeError: can't cast ActionController::Parameters
# ...
```
### System configuration

**Rails version**: 5.0.0.1

**Ruby version**: 2.3.1

**Comment by maclover7** [comment]
Hi @mxie! Do you know if this worked on 4.2.x?

**Comment by mxie** [comment]
@maclover7 I haven't tried it on 4.2.x, but yes, calling `to_h` does work...but you shouldn't have to though since normally, you could just pass `ActionController::Parameters` to a model and it'd save fine. It seems to be that if the parameters are nested though, they don't cast correctly.

**Comment by mxie** [comment]
@maclover7 Sorry, I just realized that I misread your comment, but I think I still stand by my statement that nested parameters should still work the same way as if it wasn't nested. Otherwise, it seems inconsistent.

**Comment by prathamesh-sonpatki** [comment]
Looked into this briefly and couldn't come up with a good solution.

``` diff
modified   activerecord/lib/active_record/connection_adapters/abstract/quoting.rb
@@ -1,4 +1,5 @@
 require "active_support/core_ext/big_decimal/conversions"
+require "action_controller/metal/strong_parameters"
 
 module ActiveRecord
   module ConnectionAdapters # :nodoc:
@@ -188,6 +189,7 @@ def _type_cast(value)
           when BigDecimal then value.to_s("F")
           when Type::Time::Value then quoted_time(value)
           when Date, Time then quoted_date(value)
+          when ActionController::Parameters then value.to_h
```

Seems not good because of tying AC to AR.

**Comment by prathamesh-sonpatki** [comment]
Also this issue is related to HStore columns only as the params hash goes upto `quoting` untouched. I haven't checked with JSON columns but this issue might be present in that case as well.

**Comment by maclover7** [comment]
@mxie Would you be able to look into whether this worked in 4.2.x? If so, can you do a `git bisect` to determine where a possible regression was introduced? I'm curious whether this was ever supported behavior.

**Comment by mxie** [comment]
@maclover7 Sure! I'll take a look later this week.

**Comment by maclover7** [comment]
Bisected, and 14a3bd520dd4bbf1247fd3e0071b59c02c115ce0 is what's introducing the error seen here.

**Comment by sgrif** [comment]
Yes the solution is just to check for responding to `to_unsafe_h` in the
type, but I'd also like to see if we can handle this somewhere higher up.

**Comment by maclover7** [comment]
👍 I have a hunch for a solution, investigating now...

**Comment by maclover7** [comment]
Opened a PR --> #27058

**Comment by mxie** [comment]
Awesome. Thanks, @maclover7 and @sgrif, for looking into and resolving this!
