### ISSUE TITLE
rails 5.0.0.1 ruby 2.3.1 : Article.connection  sqlite3_adapter.rb Found bugs

### ISSUE THREAD

**Issue by lyf-t** [rails/rails#26913]
### Steps to reproduce

(Guidelines for creating a bug report are [available
here](http://guides.rubyonrails.org/contributing_to_ruby_on_rails.html#creating-a-bug-report))

### Expected behavior
Tell us what should happen
i was use
  $ rails c
  $ Article.connection
   then
/Users/F/.rvm/gems/ruby-2.3.1/gems/activerecord-5.0.0.1/lib/active_record/connection_adapters/sqlite3_adapter.rb:27: 
[BUG] Segmentation fault at 0x00000000000110 ruby 2.3.1p112 (2016-04-26 revision 54768) [x86_64-darwin16]
 
mac os 10.21.1
### System configuration
**Rails version**: 5.0.0.1

**Ruby version**: 2.3.1

**Comment by maclover7** [comment]
Can you create an executable test script using one of the templates [here](https://github.com/rails/rails/tree/master/guides/bug_report_templates), that would demonstrate the problem you are seeing?

**Comment by lyf-t** [comment]
it's would like sqlite3 problems, rails everything is well, but i was using 
`$ rails c`
`$ Article.connection`

then 
/Users/*/.rvm/gems/ruby-2.3.1/gems/activerecord-5.0.0.1/lib/active_record/connection_adapters/sqlite3_adapter.rb:27: 
[BUG] Segmentation fault at 0x00000000000110 ruby 2.3.1p112 (2016-04-26 revision 54768) [x86_64-darwin16]

it's occurred again.
and App model can't work

**Comment by rafaelfranca** [comment]
This is a problem in your environment. Make sure sqlite3 and its gem is working great.
