### ISSUE TITLE
SSL Certificate issues with Ruby v2.3.1p112, gem v2.5.1 in Windows 8.1

### ISSUE THREAD

**Issue by ranganayakulu** [rails/rails#26920]
# Installing gems in Windows 8.1 is giving SSL Certificate issues.

On command `gem install rails` it is giving issues as possible:

`ERROR: Could not find a valid gem 'rails' (>= 0), here is why: 
Unable to download data from https://rubygems.org/ - SSL_connect returned=1 errno=0 state=SSLv3 read server certificate B: certificate verify failed (https://api.rubygems.org/specs.4.8.gz)`

On command `gem update --system` it is giving issues as possible:

`ERROR: While executing gem ... (Gem::RemoteFetcher::FetchError)
SSL_connect returned=1 errno=0 state=SSLv3 read server certificate B: certificate verify failed (https://api.rubygems.org/specs.4.8.gz)`

**Comment by rafaelfranca** [comment]
This is a Rubygems issue with your environment, not rails issue.
