### ISSUE TITLE
Array of nested fields_for bug

### ISSUE THREAD

**Issue by ollpu** [rails/rails#26931]
I am trying to construct a form which should be structured like this (simplified for clarity):

``` ruby
{
  users: [
    {
      username: String,
      contacts: {
        full_name: String
      },
      password: String
    },
    ...
  ]
}
```

That is, `users` is an array of objects with nested attributes.
### Steps to reproduce

In a view:

``` erb
<%= fields_for 'users[][]', @user do |user_fields| %>
  <%= user_fields.text_field :username %>
  <% puts user_fields.object_name # users[][] %>
  <%= user_fields.fields_for :contacts, OpenStruct.new(@user.contacts) do |contact_fields| %>
    <%= contact_fields.text_field :full_name %>
  <% end %>
  <% puts user_fields.object_name # users[] %>
  <%= user_fields.password_field :password %>
<% end %>
```

`@user.contacts` is a hash, which contains contact information for the user.

As you can see, after the `fields_for :contacts`, the name of the `user_fields` builder is stripped of one set of `[]`. This interferes with the rest of the form.
### Expected behavior

The above should approximately render as:

``` html
<input type="text" name="user[][username]" />
<input type="text" value="" name="user[][contacts][full_name]" />
<input type="password" name="user[][password]" />
```
### Actual behavior

``` html
<input type="text" name="user[][username]" />
<input type="text" value="" name="user[][contacts][full_name]" />
<input type="password" name="user[password]" />
```
### System configuration

**Rails version**: 5.0.0.1

**Ruby version**: 2.3.0

**Comment by ollpu** [comment]
I dug around the source, and the culprit is clearly [here](https://github.com/rails/rails/blob/master/actionview/lib/action_view/helpers/form_helper.rb#L1572). Is there proper way to make an array of objects without having to name each field manually?

**Comment by vedant1811** [comment]
I am able to reproduce this as well.

**Comment by maclover7** [comment]
Can you take your code from above and create an executable test script using one of the templates [here](https://github.com/rails/rails/tree/master/guides/bug_report_templates), that would demonstrate the problem you are seeing? I'm trying to reproduce the issue locally, and am having some trouble doing so.

**Comment by erickueen** [comment]
I was able to reproduce this too, but it does not seem to be a bug, as you pointed, the problem is that the object name is overwrote when an auto index is defined.
I found that if you define an index when calling the first fields_for, rails reproduce the expected behavior.
 
So if you have an array of users, you can do something like this:
```ruby
<%= fields_for 'users', @user {index: @user.id} do |user_fields| %>
```
So the user ID is used as the index, and the object name will not be overwrote.

**Comment by ollpu** [comment]
@erickueen this would be fine otherwise, but I'm also adding new users to the form dynamically via javascript. This would mean that I couldn't just copy a template to the form, but have to change all the field names as well.
Also, since I'm creating new users, and hence they don't have any id yet, unpacking the hash with completely unrelated id:s causes redundant code.
