### ISSUE TITLE
Changing polymorphic parent not setting associated id if polymorphic parent has id=1

### ISSUE THREAD

**Issue by afeinber** [rails/rails#26937]
### Steps to reproduce

I am making a blackjack game and ran across this problem. I have the following models.

```ruby
class Card < ApplicationRecord
  belongs_to :cardable, polymorphic: true
end

class Deck < ApplicationRecord
  belongs_to :game
  has_many :cards, as: :cardable

  def pop
    last_card = self.cards.last
    self.cards = self.cards - [last_card]
    last_card
  end
end

class Hand < ApplicationRecord
  belongs_to :round
  has_many :cards, as: :cardable
end

```

### Expected behavior
When I pop a card from the deck and add it to a hand, it should set the cardable_id and cardable_type for the card, like so:

```
  card = deck.pop

  SQL (0.6ms)  UPDATE "cards" SET "cardable_id" = NULL WHERE "cards"."cardable_id" = $1 AND "cards"."cardable_type" = $2 AND "cards"."id" = 4  [["cardable_id", 1], ["cardable_type", "Deck"]]

  hand.cards << card

  SQL (0.4ms)  UPDATE "cards" SET "cardable_id" = $1, "cardable_type" = $2, "updated_at" = $3 WHERE "cards"."id" = $4  [["cardable_id", 2], ["cardable_type", "Hand"], ["updated_at", 2016-10-31 06:53:04 
```

### Actual behavior
When the id of the hand is 1 this only sets the cardable_type and not the id.

```
[8] pry(#<RoundsController>)> hand.id
=> 1

hand.cards << card

  SQL (0.7ms)  UPDATE "cards" SET "cardable_type" = $1, "updated_at" = $2 WHERE "cards"."id" = $3  [["cardable_type", "Hand"], ["updated_at", 2016-10-31 06:56:50 UTC], ["id", 5]]

# before I reload
[13] pry(#<RoundsController>)> hand.cards
=> [#<Card:0x007fc996ebb448
  id: 5,
  suit: "♣",
  rank: "6",
  cardable_type: "Hand",
  cardable_id: 1,
  created_at: Mon, 31 Oct 2016 06:51:36 UTC +00:00,
  updated_at: Mon, 31 Oct 2016 06:56:50 UTC +00:00>]

# And of course 
[14] pry(#<RoundsController>)> hand.reload.cards
  Hand Load (0.6ms)  SELECT  "hands".* FROM "hands" WHERE "hands"."id" = $1 LIMIT $2  [["id", 1], ["LIMIT", 1]]
  Card Load (0.3ms)  SELECT "cards".* FROM "cards" WHERE "cards"."cardable_id" = $1 AND "cards"."cardable_type" = $2  [["cardable_id", 1], ["cardable_type", "Hand"]]
=> []
[15] pry(#<RoundsController>)>

```

### How I know it's the id
I added this line to one of my migrations: 
```ruby      
execute("SELECT setval('hands_id_seq', 1000);")
```
And I didn't have that trouble anymore.

### Branch of my repo with issue
https://github.com/afeinber/blackjack/tree/rails-issue

### System configuration
**Rails version**: Rails 5.0.0.1

**Ruby version**: 2.3.1

**DB**: Postgres

**Comment by sgrif** [comment]
You provided a sample app, but there's more there than just what's required to reproduce the issue. Which test case in that app demonstrates the issue? Are you able to provide a [reproducible test case using our bug report template?](https://github.com/rails/rails/blob/master/guides/bug_report_templates/active_record_master.rb)

**Comment by afeinber** [comment]
I was able to write a failing test. Take a look at this file: https://github.com/afeinber/blackjack/blob/rails-issue/test/bug_demo/bug_demo_test.rb.

Also I had the pleasure of hearing your talk last week in Moscow! Thank you so much for that :)

**Comment by afeinber** [comment]
And here's the test case using the bug template https://github.com/afeinber/polymorphic-bug/blob/master/template.rb

**Comment by romuloceccon** [comment]
@afeinber, the problem is: `Deck#pop` is returning a stale record. The statement

```ruby
self.cards = self.cards - [last_card]
```

does not touch the object at `last_card`, and works directly on the database.

Effectively you're doing the following:

```ruby
# Create Deck #1
deck = Deck.create!
# Point card to Deck #1
card = Card.create(cardable: deck)

# Point card to nil using another instance
Card.find(card.id).update!(cardable: nil)

# Create Hand #1
hand = Hand.create!

# Point card to Hand #1 using the stale record. Since the in-memory version
# already has Card#cardable_id=1, only Card#cardable_type needs to be updated.
# The effect is a Card object with Card#cardable_id=nil (actual value in the
# database) and Card#cardable_type=Hand
card.update!(cardable: hand) 

assert_equal 1, hand.reload.cards.size # fails
```

There's no magic associated with the number 1. It's just because the Deck and Hand instances have the same id. The following test would also fail:

```ruby
deck = Deck.create!(id: 5)
card = Card.create(cardable: deck)

Card.find(card.id).update!(cardable: nil)

hand = Hand.create!(id: 5)
card.update!(cardable: hand) 

assert_equal 1, hand.reload.cards.size # fails
```

You can fix it by reloading the `last_card` object before returning it from `Deck#pop`:

```ruby
def pop
  last_card = self.cards.last
  self.cards = self.cards - [last_card]
  last_card.reload
end
```
