### ISSUE TITLE
use ActiveRecord::ConnectionAdapters::ConnectionManagement

### ISSUE THREAD

**Issue by ioquatix** [rails/rails#26947]
### Steps to reproduce

In AR4, you could write 

    use ActiveRecord::ConnectionAdapters::ConnectionManagement

in rack and it would manage connections correctly.

This appears to have stopped working in AR5 and I can't find any documentation explaining what to do. I've copied the source code from AR4 ConnectionManagement directly into my code for now.

### Expected behavior

There should be a rack middleware to manage connections on a per-request basis.

**Comment by rafaelfranca** [comment]
This was removed in favor of Executor e Reloader APIs. That middleware that was removed were not part of the public API https://github.com/rails/rails/pull/23807

**Comment by ioquatix** [comment]
So, i looked through that. Is there a replacement middleware for rack or do I need to make one? Thanks :)

**Comment by rafaelfranca** [comment]
Yes. If you want to use that outside Rails you need to make one.

**Comment by ioquatix** [comment]
Okay, I see. Damn :)

**Comment by matthewd** [comment]
You want `ActionDispatch::Executor`

**Comment by ioquatix** [comment]
So, that's a Rack middleware?

**Comment by Paxa** [comment]
I found `ActiveRecord::ConnectionAdapters::ConnectionManagement ` in http://guides.rubyonrails.org/rails_on_rack.html

Where to find docs for `ActionDispatch::Executor`?

@ioquatix In sinatra can use:
```ruby
after do
  ActiveRecord::Base.clear_active_connections!
end
```

For Rack application can copy [implementation from rails 4.2](https://github.com/rails/rails/blob/4-2-stable/activerecord/lib/active_record/connection_adapters/abstract/connection_pool.rb#L645):
```ruby
class ConnectionManagement
  def initialize(app)
    @app = app
  end

  def call(env)
    testing = env['rack.test']

    response = @app.call(env)
    response[2] = ::Rack::BodyProxy.new(response[2]) do
      ActiveRecord::Base.clear_active_connections! unless testing
    end

    response
  rescue Exception
    ActiveRecord::Base.clear_active_connections! unless testing
    raise
  end
end
```

**Comment by ioquatix** [comment]
@Paxa yeah this is what I did but it is a pain.. I'm probably going to put this in a gem, e.g. "activerecord-rack"

**Comment by ioquatix** [comment]
I've made a gem for this:

https://github.com/ioquatix/activerecord-rack

If you are interested in this you might also be interested in

https://github.com/ioquatix/activerecord-migrations

too.

**Comment by matthewd** [comment]
> Where to find docs for ActionDispatch::Executor?

It's in [the rack guide](http://guides.rubyonrails.org/rails_on_rack.html)... though it does look like that guide needs to be updated: as you noted, it's still claiming `ActiveRecord::ConnectionAdapters::ConnectionManagement` manages AR connections, when, as noted above, that is actually now handled by `ActionDispatch::Executor`.

**Comment by Davidslv** [comment]
Hi,
Is there any example of usage to do this with `ActionDispatch::Executor`?

Thank you

**Comment by wjordan** [comment]
@Davidslv here's an example to insert `ActionDispatch::Executor` middleware into any Rack app along with the connection-management executor hooks:

```
use ActionDispatch::Executor, ActiveSupport::Executor
ActiveRecord::QueryCache.install_executor_hooks
```

**Comment by esilverberg** [comment]
Should anyone be curious, I have posted a StackOverflow question to which @wjordan has provided a very detailed answer at http://stackoverflow.com/questions/41400202/replacing-activerecordconnectionadaptersconnectionmanagement-in-activerecord
