### ISSUE TITLE
Rails should append ancestors when generating i18n error messages

### ISSUE THREAD

**Issue by ifightcrime** [rails/rails#26946]
Not a bug per say, but I think this could potentially be a good improvement. When generating the key combinations for i18n translation for error messages, instead of building a list of all ancestors it only uses the last one in the list (It's looping through but overriding the previous value on each loop). Since `lookup_ancestors` generates the list from child > parent (parent being last), I can only specify a translation for the parent class.

https://github.com/rails/rails/blob/master/activemodel/lib/active_model/errors.rb#L389

By pushing onto the array instead of overwriting, this would allow me to (optionally) specify specific keys for polymorphic associations (children).

For example if I have a class `class ClientUser < User` right now I the list only includes:

```
[
  "activerecord.errors.models.user.attributes.LastName.blank",
  "activerecord.errors.models.user.blank"
]
```

By making this change, the list would include options for the child class as well:

```
[
  "activerecord.errors.models.client_user.attributes.LastName.blank",
  "activerecord.errors.models.client_user.blank",
  "activerecord.errors.models.user.attributes.LastName.blank",
  "activerecord.errors.models.user.blank"
]
```

**Comment by rafaelfranca** [comment]
Thank you so much for the issue but we don't take feature request on the issue tracker. We recommend you to try to implement the feature and send us a pull request or if you are in doubt if the feature will be accepts ask in Rails Core mailing list for feedback.

**Comment by ifightcrime** [comment]
@rafaelfranca roger that. Yea that was my main thing. Wanted to make sure it was worthwhile before spending my time w/ the PR. Will check the mailing list. Thx.
