### ISSUE TITLE
`ActiveRecord::Migration.maintain_test_schema!` not `updating schema_migrations` table with SQLite v3.7.9

### ISSUE THREAD

**Issue by MasterRoot24** [rails/rails#26948]
[rspec/rspec-rails](https://github.com/rspec/rspec-rails) advised I ask for help here on this issue. Original thread [here](https://github.com/rspec/rspec-rails/issues/1733).

### Steps to reproduce
* **Locally, tests pass**:
  * `git clone https://github.com/MasterRoot24/acrm && cd acrm`
  * `git checkout 3f2355d`
  * `bundle --without production`
  * `bundle exec rake`
```
14 examples, 0 failures
```

* **Tests fail in Travis, due to the DB requiring migrations to be run**:
  * https://travis-ci.org/MasterRoot24/acrm/builds/171602866
```
Migrations are pending. To resolve this issue, run:

	bin/rails db:migrate RAILS_ENV=test
```

### Expected behavior
Tests should pass on Travis without having to manually run `rake db:migrate` in a `before_script`.

### Actual behavior
After and including [`3f2355d`](https://github.com/MasterRoot24/acrm/commit/3f2355ded76ff3a23e0416ec6d2da7fbb0c0917f), I need to manually run `rake db:migrate` in a `before_script` in Travis for the build to succeed.

Note: If I push the commit before that ([`5d81376`](https://github.com/MasterRoot24/acrm/commit/5d81376f159325342101b470bebf845033b45d35)) the build succeeds without having to manually run `rake db:migrate` before the build.

Furthermore, I've never had to include `rake db:migrate` as a `before_script` before when testing Rails apps with Travis, so why's it suddenly required now after commit [`3f2355d`](https://github.com/MasterRoot24/acrm/commit/3f2355ded76ff3a23e0416ec6d2da7fbb0c0917f).

### System configuration
**Rails version**:
```
joenyland@Joes-MacBook-Pro /tmp/acrm $ rails --version
Rails 5.0.0.1
```
**Ruby version**:
```
joenyland@Joes-MacBook-Pro /tmp/acrm $ ruby --version
ruby 2.3.0p0 (2015-12-25 revision 53290) [x86_64-darwin16]
```

**Comment by rafaelfranca** [comment]
Can you please provide a sample application that reproduces the error?

**Comment by MasterRoot24** [comment]
Here's a demo app that shows the issue: https://github.com/MasterRoot24/rails-travis-migration-issue-demo-app.

[5d81376](https://github.com/MasterRoot24/rails-travis-migration-issue-demo-app/commit/5d81376f159325342101b470bebf845033b45d35) passes: https://travis-ci.org/MasterRoot24/rails-travis-migration-issue-demo-app/builds/172434742

[3f2355d](https://github.com/MasterRoot24/rails-travis-migration-issue-demo-app/commit/3f2355ded76ff3a23e0416ec6d2da7fbb0c0917f) fails: https://travis-ci.org/MasterRoot24/rails-travis-migration-issue-demo-app/builds/172435724

Again, both commits (`5d81376` and `3f2355d`) pass locally without running `rake db:migrate`, but `3f2355d` fails in Travis.

FYI, Travis logs are currently unavailable: https://www.traviscistatus.com/incidents/lp492hx0z1my

**Comment by MasterRoot24** [comment]
With a little help from Travis, I've managed to recreate this issue outside of Travis' infrastructure.

Travis runs builds on their container based infrastructure and their image (`quay.io/travisci/travis-ruby`) is based on Ubuntu 12.04.5 (Precise).

I can now recreate the issue like so:

```
docker run -it ubuntu:precise /bin/bash
```

```
apt-get update && apt-get install git bash-completion curl nodejs -y && gpg --keyserver hkp://keys.gnupg.net --recv-keys 409B6B1796C275462A1703113804BB82D39DC0E3 && \curl -sSL https://get.rvm.io | bash -s stable && source /etc/profile.d/rvm.sh && rvm install 2.3.0 && git clone --depth=50 --branch=master https://github.com/MasterRoot24/acrm.git MasterRoot24/acrm && cd MasterRoot24/acrm && rvm use 2.3.0 && gem install bundler && export BUNDLE_GEMFILE=$PWD/Gemfile && bundle install --jobs=3 --retry=3 --deployment --path=${BUNDLE_PATH:-vendor/bundle} && bundle exec rake
```

```
root@e4f741e8c189:/MasterRoot24/acrm# bundle exec rake
/usr/local/rvm/rubies/ruby-2.3.0/bin/ruby -I/MasterRoot24/acrm/vendor/bundle/ruby/2.3.0/gems/rspec-core-3.5.4/lib:/MasterRoot24/acrm/vendor/bundle/ruby/2.3.0/gems/rspec-support-3.5.0/lib /MasterRoot24/acrm/vendor/bundle/ruby/2.3.0/gems/rspec-core-3.5.4/exe/rspec --pattern spec/\*\*\{,/\*/\*\*\}/\*_spec.rb
/MasterRoot24/acrm/vendor/bundle/ruby/2.3.0/gems/activerecord-5.0.0.1/lib/active_record/migration.rb:572:in `check_pending!':  (ActiveRecord::PendingMigrationError)

Migrations are pending. To resolve this issue, run:

	bin/rails db:migrate RAILS_ENV=test

	from /MasterRoot24/acrm/vendor/bundle/ruby/2.3.0/gems/activerecord-5.0.0.1/lib/active_record/migration.rb:585:in `load_schema_if_pending!'
	from /MasterRoot24/acrm/vendor/bundle/ruby/2.3.0/gems/activerecord-5.0.0.1/lib/active_record/migration.rb:591:in `block in maintain_test_schema!'
```

If I do the same locally on macOS 10.12 or in Debian Jessie, tests pass and I am not asked to run a manual migration.

Why would I need to run a manual migration under Ubuntu 12.04, but not under any other OS?

**Comment by MasterRoot24** [comment]
> Were you able to reproduce this issue without rspec?

@rafaelfranca Sorry, I didn't notice that you had edited your message above.

I'm not sure how I could ascertain this. Please could you suggest a way in which I could rule Rspec out?

**Comment by MasterRoot24** [comment]
I've managed to narrow this down to what seems to be an issue with SQLite 3.7.9 and ActiveRecord 5.0.0.1.

If I start an clean Ubuntu 12.04 container, install the app and run tests, I get the migration error talked about above. If I inspect this container I can see that according to the `schema_migrations` table, several of the migrations haven't been logged as being run:

```
root@74b8bce16048:/MasterRoot24/acrm# bundle exec rake db:drop db:test:prepare
Dropped database 'db/development.sqlite3'
Dropped database 'db/test.sqlite3'
root@74b8bce16048:/MasterRoot24/acrm# sqlite3 db/test.sqlite3 
SQLite version 3.7.9 2011-11-01 00:52:41
Enter ".help" for instructions
Enter SQL statements terminated with a ";"
sqlite> select * from schema_migrations;
20161029141219
20161027212018
sqlite>
root@74b8bce16048:/MasterRoot24/acrm# ls -lh db/migrate/
total 28K
-rw-r--r-- 1 root root 184 Nov  7 13:35 20161025140025_create_companies.rb
-rw-r--r-- 1 root root 221 Nov  7 13:35 20161025200827_create_users.rb
-rw-r--r-- 1 root root 125 Nov  7 13:35 20161027093255_add_address_to_companies.rb
-rw-r--r-- 1 root root 247 Nov  7 13:35 20161027212018_create_clients.rb
-rw-r--r-- 1 root root 204 Nov  7 13:35 20161027213002_create_estimates.rb
-rw-r--r-- 1 root root 202 Nov  7 13:35 20161028125610_create_invoices.rb
-rw-r--r-- 1 root root 134 Nov  7 13:35 20161029141219_add_password_digest_to_users.rb
```

However, `schema.rb` does seem to have been loaded, as all of the tables are present in the test DB:
```
sqlite> .tables
ar_internal_metadata  estimates             users               
clients               invoices            
companies             schema_migrations   
```

...but it seems that `schema_migrations` hasn't been updated with the migrations that have been run. Consequently, the exception is raised, as `ActiveRecord::Migrator.needs_migration?(connection)` returns true:

```
def needs_migration?(connection = Base.connection)
  (migrations(migrations_paths).collect(&:version) - get_all_versions(connection)).size > 0
end
```
```
root@74b8bce16048:/MasterRoot24/acrm# bundle exec rails console
Running via Spring preloader in process 464
Loading development environment (Rails 5.0.0.1)
2.3.0 :001 > ActiveRecord::Migrator.needs_migration? 
 => true 
```

This is all on Ubuntu 12.04, using the latest version of SQLite available for that OS, which is 3.7.9.

If I add the repos for the next LTS release of Ubuntu 14.04, then upgrade SQLite to 3.8.2, the issue disappears:

```
root@74b8bce16048:/MasterRoot24/acrm# echo "deb http://security.ubuntu.com/ubuntu trusty-security main" >> /etc/apt/sources.list
root@74b8bce16048:/MasterRoot24/acrm# apt-get update && apt-get install -V sqlite3=3.8.2-1ubuntu2.1 -y
# ...
root@74b8bce16048:/MasterRoot24/acrm# sqlite3 --version
3.8.2 2013-12-06 14:53:30 27392118af4c38c5203a04b8013e1afdb1cebd0d
root@74b8bce16048:/MasterRoot24/acrm# bundle exec rake db:drop db:test:prepare
Dropped database 'db/development.sqlite3'
Dropped database 'db/test.sqlite3'
root@74b8bce16048:/MasterRoot24/acrm# sqlite3 db/test.sqlite3 
SQLite version 3.8.2 2013-12-06 14:53:30
Enter ".help" for instructions
Enter SQL statements terminated with a ";"
sqlite> select * from schema_migrations;
20161029141219
20161027212018
20161028125610
20161025200827
20161027093255
20161027213002
20161025140025
sqlite> 
root@74b8bce16048:/MasterRoot24/acrm# 
root@74b8bce16048:/MasterRoot24/acrm# bundle exec rake
/usr/local/rvm/rubies/ruby-2.3.0/bin/ruby -I/MasterRoot24/acrm/vendor/bundle/ruby/2.3.0/gems/rspec-core-3.5.4/lib:/MasterRoot24/acrm/vendor/bundle/ruby/2.3.0/gems/rspec-support-3.5.0/lib /MasterRoot24/acrm/vendor/bundle/ruby/2.3.0/gems/rspec-core-3.5.4/exe/rspec --pattern spec/\*\*\{,/\*/\*\*\}/\*_spec.rb
....................................

Finished in 1.01 seconds (files took 2.76 seconds to load)
36 examples, 0 failures
```

If I revert back to SQLite 3.7.9, the issue occurs again. Seeing as Ubuntu 12.04 only provides SQLite <=3.7.9 and 12.04 is an LTS release that's [supported by Canonical until 2017](https://en.wikipedia.org/wiki/Ubuntu_version_history#Version_timeline), I feel this should be fixed. I'm quite happy to debug further, if someone could suggest a way to dig into the issue further as I'm out of options I'm afraid.

**Comment by rafaelfranca** [comment]
One thing you can do is make sure that the SQL sent to the database is the same. Like, are all the inserts being made by Rails and dropped by the database or it is rails that is not sending all the inserts?

**Comment by MasterRoot24** [comment]
@rafaelfranca It looks like the SQL is sent to the DB from Rails, as far as I can see:

```
root@ff1183812fc4:/code/active-record5_sqlite3_issue_demo# rails db:drop && rm log/*.log
Dropped database 'db/development.sqlite3'
Dropped database 'db/test.sqlite3'
root@ff1183812fc4:/code/active-record5_sqlite3_issue_demo# rails db:test:prepare
root@ff1183812fc4:/code/active-record5_sqlite3_issue_demo# sqlite3 db/test.sqlite3 
SQLite version 3.7.9 2011-11-01 00:52:41
Enter ".help" for instructions
Enter SQL statements terminated with a ";"
sqlite> select * from schema_migrations;
20161027093255
20161025140025
sqlite> root@ff1183812fc4:/code/active-record5_sqlite3_issue_demo# cat log/
.keep            development.log  
root@ff1183812fc4:/code/active-record5_sqlite3_issue_demo# cat log/development.log 
DEPRECATION WARNING: Passing #original_exception is deprecated and has no effect. Exceptions will automatically capture the original exception. (called from require at /code/active-record5_sqlite3_issue_demo/bin/rails:9)
   (6.3ms)  CREATE TABLE "companies" ("id" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, "name" varchar, "website" varchar, "created_at" datetime NOT NULL, "updated_at" datetime NOT NULL, "address" text)
   (5.9ms)  CREATE TABLE "users" ("id" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, "name" varchar, "email" varchar, "company_id" integer, "created_at" datetime NOT NULL, "updated_at" datetime NOT NULL)
   (0.1ms)  select sqlite_version(*)
   (5.8ms)  CREATE  INDEX "index_users_on_company_id" ON "users" ("company_id")
   (6.2ms)  CREATE TABLE "schema_migrations" ("version" varchar NOT NULL PRIMARY KEY)
   (1.4ms)  SELECT version FROM "schema_migrations"
   (7.8ms)  INSERT INTO "schema_migrations" (version) VALUES ('20161027093255')
   (7.7ms)  INSERT INTO schema_migrations (version) VALUES ('20161025140025');

INSERT INTO schema_migrations (version) VALUES ('20161025200827');
   (10.5ms)  CREATE TABLE "ar_internal_metadata" ("key" varchar NOT NULL PRIMARY KEY, "value" varchar, "created_at" datetime NOT NULL, "updated_at" datetime NOT NULL)
  ActiveRecord::InternalMetadata Load (1.8ms)  SELECT  "ar_internal_metadata".* FROM "ar_internal_metadata" WHERE "ar_internal_metadata"."key" = ? LIMIT ?  [["key", :environment], ["LIMIT", 1]]
   (0.1ms)  begin transaction
  SQL (5.4ms)  INSERT INTO "ar_internal_metadata" ("key", "value", "created_at", "updated_at") VALUES (?, ?, ?, ?)  [["key", "environment"], ["value", "development"], ["created_at", 2016-11-08 08:29:44 UTC], ["updated_at", 2016-11-08 08:29:44 UTC]]
   (4.3ms)  commit transaction
  ActiveRecord::InternalMetadata Load (1.9ms)  SELECT  "ar_internal_metadata".* FROM "ar_internal_metadata" WHERE "ar_internal_metadata"."key" = ? LIMIT ?  [["key", :environment], ["LIMIT", 1]]
   (0.1ms)  begin transaction
   (0.1ms)  commit transaction
```

**Comment by MasterRoot24** [comment]
Thought it was best to update the title of the issue, now that I've established the issue has nothing to do with Travis.

**Comment by MasterRoot24** [comment]
FYI, I've created a very simple Rails 5 app that recreates this issue: https://github.com/MasterRoot24/active-record5_sqlite3_issue_demo

**Comment by MasterRoot24** [comment]
Is there anything I can add to this issue that would help move things forward?

**Comment by rafaelfranca** [comment]
If active record is sending the SQL to the database it is not a active record issue. May it be possible that it only happens with this version of SQLite3?

**Comment by rafaelfranca** [comment]
If you run the SQL generated by Active Record on that sqlite3 console does the data got written? Also have you checked that the transaction that contains the insert queries are being committed?

**Comment by MasterRoot24** [comment]
Yes, if I manually run the SQL, the missing migration is added to the `schema_migrations` table.

What's interesting is that all of the migrations are run in the test database. What seems to be the issue is the inserting of the completed migrations into the `schema_migrations` table.

The only thing that stands out to me is the inconsistency of semi-colons in the logged queries:

```
   (44.1ms)  INSERT INTO "schema_migrations" (version) VALUES ('20161027093255')
   (39.6ms)  INSERT INTO schema_migrations (version) VALUES ('20161025200827');

INSERT INTO schema_migrations (version) VALUES ('20161025140025');
```

Migrations `20161027093255` and `20161025200827` get inserted into the `schema_migrations` table, but `20161025140025` is NOT inserted (bit the migration has run and applied it's changes to the test DB. What seems weird is that there's no semi-colons used in the logged queries, except for these two. Also note how it's not prefixed with a time? Could it be that although that last query is being logged by AR, it's not actually being sent to SQLite?

**Comment by MasterRoot24** [comment]
I think I've found the issue!

`ActiveRecord::ConnectionAdapters::SQLite3Adapter.execute` method calls `@connection.execute` where `@connection` is an instance of the `SQLite3::Database` class containing the current DB connection.

According to the docs, [`SQLite3::Database.execute`][execute-docs] only executes the first statement in a string and in order to execute all of the statements in a string, [`SQLite3::Database.execute_batch`][execute-batch-docs] should be used.

If I manually hack `activerecord-5.0.0.1/lib/active_record/connection_adapters/sqlite3_adapter.rb` to use `execute_batch`, the migrations are recorded correctly in `schema_migrations`.

I can try to create a PR containing this fix, if that's preferred?

```
<         log(sql, name) { @connection.execute(sql) }
---
>         log(sql, name) { @connection.execute_batch(sql) }
```

[execute-docs]: http://www.rubydoc.info/gems/sqlite3/1.3.11/SQLite3%2FDatabase%3Aexecute
[execute-batch-docs]: http://www.rubydoc.info/gems/sqlite3/1.3.11/SQLite3%2FDatabase%3Aexecute_batch

**Comment by MasterRoot24** [comment]
I will put together a PR later today when I have time.

**Comment by rafaelfranca** [comment]
Oh! Nice finding. Yes, please open a PR.

**Comment by MasterRoot24** [comment]
Hmm, turns out the patch wasn't as easy as I thought. `execute_batch` just returns nil no matter what the statement returns which obviously is not what we want when we're running statements to retrieve data.

I'll have a think about another solution to this and open a PR when I have a solution.

**Comment by matthewd** [comment]
The safety of only running a single query is generally desirable... I suspect we'd want to add some sort of batch execute method to our connection adapter, and only use it when we mean to.

**Comment by hibaAkroush** [comment]
run: rake db:migrate RAILS_ENV=test 
and then: rspec spec
