### ISSUE TITLE
Rails 5 Undocumented Enumerable Methods Prioritized Over Scopes on Relations

### ISSUE THREAD

**Issue by matt-glover** [rails/rails#26949]
Prior to Rails 5 applications were able to define a scope with a method name that happened to match many methods on `Enumerable` and treat it like any other scope. While attempting to upgrade an older application to Rails 5 I started receiving errors for calls to a legacy `group_by` scope that accepted a single parameter.

I think this commit introduced the change that triggered the error: https://github.com/rails/rails/commit/b644964b2b555798fc4b94d384b98438db863b3f

Including the bug report components in case the maintainers want to treat this as a bug. I think it is also reasonable to treat this as an intended change considering that relations already had a few methods from `Enumerable` explicitly defined on them. If it is intended then I think it should be noted in the docs somewhere (maybe just the 4.2 -> 5.0 upgrade docs).

### Steps to reproduce

1. Create a scope on Rails 4.2 with a method name that matches a method on [`Enumerable`](http://ruby-doc.org/core-2.3.1/Enumerable.html) but is not explicitly noted in the Rails guides.
  * Use a method like `group_by` rather than something like `any?` which has been noted in Rails docs for a while
2. Construct and execute a query using that scope
3. Observe that the scope is executed as expected
4. Switch to Rails 5 and follow steps 1 and 2

```ruby
begin
  require "bundler/inline"
rescue LoadError => e
  $stderr.puts "Bundler version 1.10 or later is required. Please update your Bundler"
  raise e
end

gemfile(true) do
  source "https://rubygems.org"
  gem "rails", github: "rails/rails"
  gem "sqlite3"
end

require "active_record"
require "minitest/autorun"
require "logger"

# This connection will do for database-independent bug reports.
ActiveRecord::Base.establish_connection(adapter: "sqlite3", database: ":memory:")
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :posts, force: true do |t|
   t.string :name
  end

  create_table :comments, force: true do |t|
    t.integer :post_id
  end
end

class Post < ActiveRecord::Base
  has_many :comments

  scope :group_by, ->(value) { group(value) }
end

class Comment < ActiveRecord::Base
  belongs_to :post

  def self.group_by(value)
    group(value)
  end
end

class BugTest < Minitest::Test
  def test_group_by_with_class_method
    assert_nothing_raised(Comment.all.group_by('post_id'))
  end

  def test_group_by_with_scope
    assert_nothing_raised(Post.all.group_by('name'))
	end
end
```

### Expected behavior
The scope is executed as expected, just as in Rails 4.2

### Actual behavior
The scope is never called because the method from `Enumerable` is found and called first. If the arity of your scope is different from the arity of the method on `Enumerable` then an error is thrown.

### System configuration
**Rails version**: 5.0.0.1 (although the bug demo script happens to reproduce the behavior against 5.1.0.alpha)

**Ruby version**: 2.3.1

**Comment by sgrif** [comment]
This is the expected behavior.

**Comment by mtgrosser** [comment]
The "expected behaviour" is to not change low-level behaviours that have been established for years at random and without documentation.

The established behaviour is: Existing relation methods take precedence over ```Array```/```Enumerable```. Ever heard of POLS?

In Rails 4 the receiver can be controlled by explicitly calling or not calling ```to_a``` on the relation. This is no longer possible with the current implementation.

The [activerecord-delegation-expected_behaviour](https://github.com/mtgrosser/activerecord-delegation-expected_behaviour) gem reinstates the Rails 4 call order.
