### ISSUE TITLE
Redis Cache Issue storing Active Record Object

### ISSUE THREAD

**Issue by GeminPatel** [rails/rails#26953]
### Some Info:
class User has 2 db column 'name' and 'lang' both string.

reader for lang is overridden as follows:

def lang
  if false
    puts 'something'
  else
    super
  end
end

### Steps to reproduce

L1- In Terminal 1: Rails.cache.write('some_user', User.first)
L2- In Terminal 1: Rails.cache.read('some_user').name
L3- In Terminal 2: Rails.cache.read('some_user').name
L4- In Terminal 1: Rails.cache.read('some_user').lang
L5- In Terminal 2: Rails.cache.read('some_user').lang

### What is happening
L1- Writes into the cache store.
L2- name is a db column and hence the default reader returns 'gemin'.
L3- name is a db column and hence the default reader returns 'gemin'.
L4- lang's reader is overridden so it goes inside the new reader. super is called and it returns 'en'
L5- lang's reader is overridden so it goes inside the new reader. super is called and it breaks NoMethodError: super: no superclass method `lang' for #<User:0x007fd71ca69078>

NOTE: If u reload! Terminal 1, same error will start to occur. 

### System configuration
**Rails version**: rails-5.0.0

**Ruby version**: 2.3.1

**Comment by maclover7** [comment]
Please use the mailing list or StackOverflow for questions/help, where a wider community will be able to help you. We reserve the issues tracker for issues only.

**Comment by GeminPatel** [comment]
I am new to rails but I feel like this is an issue with how activerecord is introducing readers. Anyways will post this question on Stack. Thanks

**Comment by IvanChou** [comment]
I have the same problem.
