### ISSUE TITLE
Custom ActionController renderer not able to overwrite content type in Rails 5

### ISSUE THREAD

**Issue by fabrik42** [rails/rails#26959]
Hi!

I am in the process of updating the [acts_as_api gem](https://github.com/fabrik42/acts_as_api) to a Rails 5 compatible version.

The gem uses a custom renderer that also allows you to render json, as well as  jsonp responses:

```ruby
  def index
    @users = User.all

    respond_to do |format|
      format.json { render_for_api :name_only, :json => @users, :root => :users }
    end
  end
```

For executing jsonp responses, some browsers will only accept the JavaScript content type, not json. So my custom renderer would change the content type of a json response if a jsonp callback option was provided:  https://github.com/fabrik42/acts_as_api/blob/master/lib/acts_as_api/rails_renderer.rb#L11

This used to work in older Rails versions, but not in Rails 5. I am not sure if this is intended behavior now or a regression.

It would be pretty cool if I could get some context into these changes, so I can decide what to do. :)

Cheers,

Christian

### Expected behavior
Custom renderers can change the content type of a response on the fly.

### Actual behavior
Setting the content type to anything else than JSON when rendering inside of a render/json block will result in an `ActionController::UnknownFormat` error.

### System configuration
**Rails version**: 5.0.0.1

**Ruby version**: 2.3.1p112

**Comment by maclover7** [comment]
@fabrik42 Did this work for you in Rails 4.2.x? If so, can you do a `git bisect` to determine where a possible regression may have been introduced?

**Comment by fabrik42** [comment]
I tried to reproduce this in vanilla Rails applications (4.2 and 5.0) and was not able to reproduce the error. Meanwhile I am pretty sure it's not a bug in Rails at all, but in my Gem's implementation.

Thank you for your help and sorry for taking your time. 😞
