### ISSUE TITLE
listen should not listen on paths loaded from gems

### ISSUE THREAD

**Issue by radiospiel** [rails/rails#26955]
I stumbled across this when I tracked the reason why I have so many fsevent_watch processes running: after starting a rails server in development mode I see a lot of fsevent_watch processes watching directories that are in gems. Since these are not supposed to change anyways they should not be watched:

```
/Users/eno/projects/--redacted-- [master] > ps -xf | grep fs[e]vent_watch
  501  2309  2307   0  5:40PM ttys000    0:00.01 /Users/eno/.rvm/gems/ruby-2.3.1/gems/rb-fsevent-0.9.7/bin/fsevent_watch --latency 0.1 /Users/eno/.rvm/gems/ruby-2.3.1/gems/activesupport-5.0.0.1/lib/active_support/locale
  501  2310  2307   0  5:40PM ttys000    0:00.01 /Users/eno/.rvm/gems/ruby-2.3.1/gems/rb-fsevent-0.9.7/bin/fsevent_watch --latency 0.1 /Users/eno/.rvm/gems/ruby-2.3.1/gems/activemodel-5.0.0.1/lib/active_model/locale
  501  2311  2307   0  5:40PM ttys000    0:00.01 /Users/eno/.rvm/gems/ruby-2.3.1/gems/rb-fsevent-0.9.7/bin/fsevent_watch --latency 0.1 /Users/eno/.rvm/gems/ruby-2.3.1/gems/activerecord-5.0.0.1/lib/active_record/locale
  501  2312  2307   0  5:40PM ttys000    0:00.01 /Users/eno/.rvm/gems/ruby-2.3.1/gems/rb-fsevent-0.9.7/bin/fsevent_watch --latency 0.1 /Users/eno/.rvm/gems/ruby-2.3.1/gems/actionview-5.0.0.1/lib/action_view/locale
  501  2313  2307   0  5:40PM ttys000    0:00.01 /Users/eno/.rvm/gems/ruby-2.3.1/gems/rb-fsevent-0.9.7/bin/fsevent_watch --latency 0.1 /Users/eno/.rvm/gems/ruby-2.3.1/gems/responders-2.3.0/lib/responders/locales
  501  2314  2307   0  5:40PM ttys000    0:00.01 /Users/eno/.rvm/gems/ruby-2.3.1/gems/rb-fsevent-0.9.7/bin/fsevent_watch --latency 0.1 /Users/eno/.rvm/gems/ruby-2.3.1/gems/devise-4.2.0/config/locales
  501  2315  2307   0  5:40PM ttys000    0:00.01 /Users/eno/.rvm/gems/ruby-2.3.1/gems/rb-fsevent-0.9.7/bin/fsevent_watch --latency 0.1 /Users/eno/.rvm/gems/ruby-2.3.1/gems/kaminari-0.17.0/config/locales
  501  2316  2307   0  5:40PM ttys000    0:00.01 /Users/eno/.rvm/gems/ruby-2.3.1/gems/rb-fsevent-0.9.7/bin/fsevent_watch --latency 0.1 /Users/eno/projects/--redacted--/config/locales
  501  2317  2307   0  5:40PM ttys000    0:00.01 /Users/eno/.rvm/gems/ruby-2.3.1/gems/rb-fsevent-0.9.7/bin/fsevent_watch --latency 0.1 /Users/eno/.rvm/gems/ruby-2.3.1/gems/actioncable-5.0.0.1
  501  2318  2307   0  5:40PM ttys000    0:00.01 /Users/eno/.rvm/gems/ruby-2.3.1/gems/rb-fsevent-0.9.7/bin/fsevent_watch --latency 0.1 /Users/eno/.rvm/gems/ruby-2.3.1/gems/jquery-rails-4.2.1
  501  2319  2307   0  5:40PM ttys000    0:00.01 /Users/eno/.rvm/gems/ruby-2.3.1/gems/rb-fsevent-0.9.7/bin/fsevent_watch --latency 0.1 /Users/eno/.rvm/gems/ruby-2.3.1/gems/foundation-rails-6.2.3.0/config
  501  2320  2307   0  5:40PM ttys000    0:00.01 /Users/eno/.rvm/gems/ruby-2.3.1/gems/rb-fsevent-0.9.7/bin/fsevent_watch --latency 0.1 /Users/eno/.rvm/gems/ruby-2.3.1/gems/rails-timeago-2.15.0
  501  2321  2307   0  5:40PM ttys000    0:00.01 /Users/eno/.rvm/gems/ruby-2.3.1/gems/rb-fsevent-0.9.7/bin/fsevent_watch --latency 0.1 /Users/eno/.rvm/gems/ruby-2.3.1/gems/cloudinary-1.2.3
  501  2322  2307   0  5:40PM ttys000    0:00.01 /Users/eno/.rvm/gems/ruby-2.3.1/gems/rb-fsevent-0.9.7/bin/fsevent_watch --latency 0.1 /Users/eno/.rvm/gems/ruby-2.3.1/gems/foundation-rails-6.2.3.0/app/controllers
  501  2323  2307   0  5:40PM ttys000    0:00.01 /Users/eno/.rvm/gems/ruby-2.3.1/gems/rb-fsevent-0.9.7/bin/fsevent_watch --latency 0.1 /Users/eno/.rvm/gems/ruby-2.3.1/gems/devise-4.2.0/app/controllers
  501  2324  2307   0  5:40PM ttys000    0:00.01 /Users/eno/.rvm/gems/ruby-2.3.1/gems/rb-fsevent-0.9.7/bin/fsevent_watch --latency 0.1 /Users/eno/.rvm/gems/ruby-2.3.1/gems/devise-4.2.0/app/helpers
  501  2325  2307   0  5:40PM ttys000    0:00.01 /Users/eno/.rvm/gems/ruby-2.3.1/gems/rb-fsevent-0.9.7/bin/fsevent_watch --latency 0.1 /Users/eno/.rvm/gems/ruby-2.3.1/gems/devise-4.2.0/app/mailers
  501  2326  2307   0  5:40PM ttys000    0:00.01 /Users/eno/.rvm/gems/ruby-2.3.1/gems/rb-fsevent-0.9.7/bin/fsevent_watch --latency 0.1 /Users/eno/projects/--redacted--
```

The culprit here seems to be in railsties' lib/rails/application.rb file, which loads all the ActiveSupport::Dependencies.autoload_paths
as paths to watch. In my case config.watchable_files and config.watchable_dirs is empty.

    # API.
    def watchable_args #:nodoc:
      files, dirs = config.watchable_files.dup, config.watchable_dirs.dup

      ActiveSupport::Dependencies.autoload_paths.each do |path|
        dirs[path.to_s] = [:rb]
      end

      [files, dirs]
    end

I guess for the reason that also autoload_paths should not include paths from inside gems, but maybe I am wrong there.

In any case fixing this could also help with https://github.com/rails/rails/issues/26158 and https://github.com/jonleighton/spring-watcher-listen/issues/13

### Expected behavior

Watchers should only start for the app directories itself.

### Actual behavior

Watchers start for a number of directories outside of the app directory itself.

### System configuration

**Rails version**: 5.0.0.1
**Ruby version**: 2.3.1
**OS**: Mac OS 10.11

**Comment by maclover7** [comment]
cc @fxn

**Comment by rafaelfranca** [comment]
> I guess for the reason that also autoload_paths should not include paths from inside gems, but maybe I am wrong there.

Yes, they should, otherwise you would have to require manually all controller, models and helpers defined in engines.

I guess to fix this we would have to remove all items in the autoload path that are not inside the application.

**Comment by radiospiel** [comment]
I can provide a fix along that path. Is there a better way to check whether or not a path is inside the app apart from `path.starts_with?(App.root)`

**Comment by rafaelfranca** [comment]
I don't think so. That is the best API that I remember.

**Comment by matthewd** [comment]
We should be able to get the paths for all the gems from rubygems, then exclude those... maybe with some consultation with bundler too.

**Comment by radiospiel** [comment]
I have a patch here https://github.com/radiospiel/rails/pull/1 which I verified to work correctly. However, I have trouble building tests since the code detects Rails' root via defined?(::Rails) && Rails.root. Any ideas?

**Comment by fxn** [comment]
Let's think a bit about this.

If you put something in `autoload_paths`, it is _expected_ to change. I mean, that is the normal use case. You have the ability to autoload the constant, and also the expectation to reload it when they are cleaned up.

When you want to spare the `require` but do not want to be monitoring changes, you put that in `autoload_once_paths`. Maybe this issue is saying that we should move more stuff to `autoload_once_paths`, and that we should ignore those when configuring the watchers?

**Comment by fxn** [comment]
Ah, I don't mean this approach is direct in the current _dependencies.rb_, maybe the implementation needs some adjustment (have not checked the code).

**Comment by radiospiel** [comment]
@fxn I agree that maybe things should be moved into autoload_once_paths. However, in the meantime I also found out that listen is called both on the auto_load path (for ruby code), but also on some paths that stem from i18n, and this is in my quite simple application.

On the other hand you would not expect things to change outside of the current app regardless of *how* those were loaded (i18n or ruby autoloading), hence I would suggest to fix evented_file_update_checker.rb to only check for updates from inside the app directory in the first place - and this is what https://github.com/radiospiel/rails/pull/1/files is doing.

Moving things from auto_load to auto_load_once would be a change with a much broader surface and certainly out of scope of my original report. (Not that I would disagree with it)

**Comment by matthewd** [comment]
> you would not expect things to change outside of the current app

FWIW, I disagree, with the sole exception of gem files

**Comment by radiospiel** [comment]
>> you would not expect things to change outside of the current app
>
> FWIW, I disagree, with the sole exception of gem files

Mathew, I am afraid I don’t quite catch that. Can you explain further, 
please?

--
me at github: https://github.com/radiospiel
me at linked.in: https://www.linkedin.com/in/radiospiel

**Comment by matthewd** [comment]
I *do* expect files outside of the application's root directory to change. The *only* files I think it is reasonable to expect not to change are files that belong to installed gems.

**Comment by radiospiel** [comment]
@matthewd if that is the expectation then my original complaint is moot - and in that case feel free to close this issue. However, I can't envision a scenario in which a source file's change should affect an applications behaviour if it is not inside the application nor inside an installed gem.

**Comment by fxn** [comment]
I agree with @matthewd.

The key point here is _which is a better reasonabe default for watchers_? We all would agree that watching stuff in gems is not a good default. It is OK that the use case in which you edit a gem to debug something you need to do something special.

But there are use cases for wanting to watch stuff outside of the application, like developing an engine that is declared as a dependency via `path` in the _Gemfile_ of the parent application. There, you want to watch and reload as we do today.

And that also forces us to put our finger on defining what "stuff in gems" exactly means. Because that engine may be a gem, and it is being loaded by Bundler.

**Comment by fxn** [comment]
I would be open to reconsider this behaviour though. That is, if you want to watch stuff outside or `Rails.root`, then you need to opt-in somehow. That use case exists but it is less common, so if you need to do something to enable it... maybe that's not a big deal, and the the rule or what to watch is more straightforward to implement, and to understand by users.

**Comment by radiospiel** [comment]
Could this be a configuration setting via config/environments/development.rb maybe, which lets users define additional directories that should be watched?

**Comment by matthewd** [comment]
My suggestion is that we include all paths *except* those inside `Gem.path`.

That'll do what we want for installed gems (exclude them) and path gems (include them). It doesn't get git gems right -- we should really exclude those (if they're bundler-managed, and not using a local override): that's where bundler could give us more information.

**Comment by radiospiel** [comment]
Should we really care about git gems? When building a gem locally you would not include it via git but via path anyways, I guess.

**Comment by radiospiel** [comment]
Updated preview here: https://github.com/radiospiel/rails/pull/1

**Comment by radiospiel** [comment]
Any comments on my PR suggestion?

**Comment by fxn** [comment]
The ones present in the thread at the moment.

**Comment by matthewd** [comment]
@radiospiel that looks good to me. Submit it as an actual PR?

**Comment by adlugopolski** [comment]
Is there any recommended short-term fix to this issue? I am seeing this constantly and I have to just keep killing excess fsevent_watch processes in order to prevent general system crash.

**Comment by mdrozdziel** [comment]
I've added the fix proposed by @radiospiel as a monkey patch and so far so good. There is no processes started outside the app directory. The number of active processes is down to ~15 from ~200 per app.

In case someone ends up reading thread from Google while looking for a solution - this worked for me:

`config/initializers/fsevent_watch_fix.rb` 

```ruby
module ActiveSupport
  class EventedFileUpdateChecker
    private

    def directories_to_watch
      dtw = (@files + @dirs.keys).map { |f| @ph.existing_parent(f) }
      dtw.compact!
      dtw.uniq!

      normalized_gem_paths = Gem.path.map { |path| File.join path, "" }
      dtw = dtw.reject do |path|
        normalized_gem_paths.any? { |gem_path| path.to_s.starts_with?(gem_path) }
      end

      @ph.filter_out_descendants(dtw)
    end
  end
end
```

**Comment by rafaelfranca** [comment]
Fixed by https://github.com/rails/rails/commit/8d50b45159b4fec446b4d1e1a756c326fcd582f0

**Comment by rafaelfranca** [comment]
Backported in 5568a77254 and 615baac6e5
