### ISSUE TITLE
handle_argument_error

### ISSUE THREAD

**Issue by guolijun** [rails/rails#26964]
rails server -b 0.0.0.0 -p 4000 -e development

ERROR: "rails server" was called with arguments ["-b", "0.0.0.0", "-p", "4000", "-e", "development"] (Thor::InvocationError)
Usage: "bin/rails server [options]"

**Comment by arthurnn** [comment]
Not sure what the problem is. Can you provide more information? Like a sample broken app, or the full stacktrace?
Thanks

**Comment by guolijun** [comment]
/Users/guolijun/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/thor-0.19.1/lib/thor/base.rb:483:in `handle_argument_error': ERROR: "rails server" was called with arguments ["-b", "0.0.0.0", "-p", "4000", "-e", "development"] (Thor::InvocationError)
Usage: "bin/rails server [options]"
	from /Users/guolijun/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/thor-0.19.1/lib/thor/command.rb:34:in `rescue in run'
	from /Users/guolijun/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/thor-0.19.1/lib/thor/command.rb:21:in `run'
	from /Users/guolijun/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
	from /Users/guolijun/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
	from /Users/guolijun/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/bundler/gems/rails-98faa2a6a12e/railties/lib/rails/command/base.rb:61:in `perform'
	from /Users/guolijun/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/bundler/gems/rails-98faa2a6a12e/railties/lib/rails/command.rb:34:in `invoke'
	from /Users/guolijun/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/bundler/gems/rails-98faa2a6a12e/railties/lib/rails/commands.rb:16:in `<top (required)>'
	from /Users/guolijun/Projects/rails/talkpal_backend/bin/rails:9:in `require'
	from /Users/guolijun/Projects/rails/talkpal_backend/bin/rails:9:in `<top (required)>'
	from /Users/guolijun/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/spring-1.7.2/lib/spring/client/rails.rb:28:in `load'
	from /Users/guolijun/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/spring-1.7.2/lib/spring/client/rails.rb:28:in `call'
	from /Users/guolijun/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/spring-1.7.2/lib/spring/client/command.rb:7:in `call'
	from /Users/guolijun/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/spring-1.7.2/lib/spring/client.rb:30:in `run'
	from /Users/guolijun/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/spring-1.7.2/bin/spring:49:in `<top (required)>'
	from /Users/guolijun/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/spring-1.7.2/lib/spring/binstub.rb:11:in `load'
	from /Users/guolijun/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/spring-1.7.2/lib/spring/binstub.rb:11:in `<top (required)>'
	from /Users/guolijun/.rbenv/versions/2.3.0/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /Users/guolijun/.rbenv/versions/2.3.0/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /Users/guolijun/Projects/rails/talkpal_backend/bin/spring:13:in `<top (required)>'
	from bin/rails:3:in `load'
	from bin/rails:3:in `<main>'

**Comment by guolijun** [comment]
```
/Users/guolijun/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/thor-0.19.1/lib/thor/base.rb:483:in `handle_argument_error': ERROR: "rails server" was called with arguments ["-b", "0.0.0.0", "-p", "4000", "-e", "development"] (Thor::InvocationError)
Usage: "bin/rails server [options]"
	from /Users/guolijun/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/thor-0.19.1/lib/thor/command.rb:34:in `rescue in run'
	from /Users/guolijun/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/thor-0.19.1/lib/thor/command.rb:21:in `run'
	from /Users/guolijun/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
	from /Users/guolijun/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
	from /Users/guolijun/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/bundler/gems/rails-98faa2a6a12e/railties/lib/rails/command/base.rb:61:in `perform'
	from /Users/guolijun/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/bundler/gems/rails-98faa2a6a12e/railties/lib/rails/command.rb:34:in `invoke'
	from /Users/guolijun/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/bundler/gems/rails-98faa2a6a12e/railties/lib/rails/commands.rb:16:in `<top (required)>'
	from /Users/guolijun/Projects/rails/talkpal_backend/bin/rails:9:in `require'
	from /Users/guolijun/Projects/rails/talkpal_backend/bin/rails:9:in `<top (required)>'
	from /Users/guolijun/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/spring-1.7.2/lib/spring/client/rails.rb:28:in `load'
	from /Users/guolijun/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/spring-1.7.2/lib/spring/client/rails.rb:28:in `call'
	from /Users/guolijun/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/spring-1.7.2/lib/spring/client/command.rb:7:in `call'
	from /Users/guolijun/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/spring-1.7.2/lib/spring/client.rb:30:in `run'
	from /Users/guolijun/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/spring-1.7.2/bin/spring:49:in `<top (required)>'
	from /Users/guolijun/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/spring-1.7.2/lib/spring/binstub.rb:11:in `load'
	from /Users/guolijun/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/spring-1.7.2/lib/spring/binstub.rb:11:in `<top (required)>'
	from /Users/guolijun/.rbenv/versions/2.3.0/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /Users/guolijun/.rbenv/versions/2.3.0/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /Users/guolijun/Projects/rails/talkpal_backend/bin/spring:13:in `<top (required)>'
	from bin/rails:3:in `load'
	from bin/rails:3:in `<main>'
```

**Comment by rafaelfranca** [comment]
Can you please provide a sample application that reproduces the error?
