### ISSUE TITLE
module ActionMailer class Base

### ISSUE THREAD

**Issue by DouglasAllen** [rails/rails#26975]
### System configuration
**Rails version**: '5.0.0.1'

**Ruby version**: '2.3.1'

First indent the private and protected headers 2 more spaces

Just one issue right now.

ABC is to high for

def set_payload_for_mail(payload, mail) #:nodoc:
        payload[:mailer]     = name
        payload[:message_id] = mail.message_id
        payload[:subject]    = mail.subject
        payload[:to]         = mail.to
        payload[:from]       = mail.from
        payload[:bcc]        = mail.bcc if mail.bcc.present?
        payload[:cc]         = mail.cc  if mail.cc.present?
        payload[:date]       = mail.date
        payload[:mail]       = mail.encoded
end

using https://github.com/misogi/vscode-ruby-rubocop
I get lots of green squiggly underlines. :-D

**Comment by rafaelfranca** [comment]
Thank you for the issue. We don't care about code complexity metrics
