### ISSUE TITLE
Output of number_to_human_size is wrong!

### ISSUE THREAD

**Issue by mystdeim** [rails/rails#26973]
number_to_human_size is 1024-base, but print KB, MB.
Example: `number_to_human_size(1000, prefix: :si)`

I could adjust by argument `prefix: :si`, but:
`:prefix option of `number_to_human_size` is deprecated and will be removed in Rails 5.1`

WTF? Are you joking? Please read wikipedia at least: https://en.wikipedia.org/wiki/Binary_prefix

Don't damage my favourite framework

**Comment by rafaelfranca** [comment]
This is by design. Please see https://github.com/rails/rails/pull/7835

**Comment by rafaelfranca** [comment]
Also no one is joking here. Please be respectful before posting things in the issue tracker and please read our code of conduct http://rubyonrails.org/conduct/.

**Comment by mystdeim** [comment]
This is wrong according standards!
