### ISSUE TITLE
Validation associated and RecordInvalid and block render

### ISSUE THREAD

**Issue by francesco-loreti** [rails/rails#26989]
I do not know if it is a bug or not but when the program tries to validate the presence of records the procedure returns an error that stops the the procedure. I put below the reproduction error.

**# Steps to reproduce**
To ease reproduction I have created a demo application following the example from the guides: https://github.com/francesco-loreti/recordinvalid

Clone repository
run 'ruby validates_associated_model.rb'

# **Actual behavior**
  1) Error:
BugTest#test_context_validation_stuff:
ActiveRecord::RecordInvalid: Validation failed: User Role just exist!
    C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/activerecord-5.0.0.1/lib/active_record/validations.rb:78:in `raise_validation_error'
    C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/activerecord-5.0.0.1/lib/active_record/validations.rb:50:in `save!'
    C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/activerecord-5.0.0.1/lib/active_record/attribute_methods/dirty.rb:30:in `save!'
    C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/activerecord-5.0.0.1/lib/active_record/transactions.rb:324:in `block in save!'
    C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/activerecord-5.0.0.1/lib/active_record/transactions.rb:395:in `block in with_transaction_returning_status'
    C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/activerecord-5.0.0.1/lib/active_record/connection_adapters/abstract/database_statements.rb:230:in `transaction'
    C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/activerecord-5.0.0.1/lib/active_record/transactions.rb:211:in `transaction'
    C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/activerecord-5.0.0.1/lib/active_record/transactions.rb:392:in `with_transaction_returning_status'
    C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/activerecord-5.0.0.1/lib/active_record/transactions.rb:324:in `save!'
    C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/activerecord-5.0.0.1/lib/active_record/suppressor.rb:45:in `save!'
    C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/activerecord-5.0.0.1/lib/active_record/associations/has_many_through_association.rb:89:in `save_through_record'
    C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/activerecord-5.0.0.1/lib/active_record/associations/has_many_through_association.rb:47:in `insert_record'
    C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/activerecord-5.0.0.1/lib/active_record/associations/collection_association.rb:587:in `block (2 levels) in concat_records'
    C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/activerecord-5.0.0.1/lib/active_record/associations/collection_association.rb:430:in `replace_on_target'
    C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/activerecord-5.0.0.1/lib/active_record/associations/collection_association.rb:423:in `add_to_target'
    C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/activerecord-5.0.0.1/lib/active_record/associations/collection_association.rb:586:in `block in concat_records'
    C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/activerecord-5.0.0.1/lib/active_record/associations/collection_association.rb:584:in `each'
    C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/activerecord-5.0.0.1/lib/active_record/associations/collection_association.rb:584:in `concat_records'
    C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/activerecord-5.0.0.1/lib/active_record/associations/has_many_association.rb:129:in `concat_records'
    C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/activerecord-5.0.0.1/lib/active_record/associations/has_many_through_association.rb:27:in `concat_records'
    C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/activerecord-5.0.0.1/lib/active_record/associations/collection_association.rb:188:in `block in concat'
    C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/activerecord-5.0.0.1/lib/active_record/associations/collection_association.rb:203:in `block in transaction'
    C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/activerecord-5.0.0.1/lib/active_record/connection_adapters/abstract/database_statements.rb:230:in `transaction'
    C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/activerecord-5.0.0.1/lib/active_record/transactions.rb:211:in `transaction'
    C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/activerecord-5.0.0.1/lib/active_record/associations/collection_association.rb:202:in `transaction'
    C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/activerecord-5.0.0.1/lib/active_record/associations/collection_association.rb:188:in `concat'
    C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/activerecord-5.0.0.1/lib/active_record/associations/has_many_through_association.rb:21:in `concat'
    C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/activerecord-5.0.0.1/lib/active_record/associations/collection_association.rb:564:in `replace_records'
    C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/activerecord-5.0.0.1/lib/active_record/associations/collection_association.rb:391:in `block in replace'
    C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/activerecord-5.0.0.1/lib/active_record/associations/collection_association.rb:203:in `block in transaction'
    C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/activerecord-5.0.0.1/lib/active_record/connection_adapters/abstract/database_statements.rb:232:in `block in transaction'
    C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/activerecord-5.0.0.1/lib/active_record/connection_adapters/abstract/transaction.rb:189:in `within_new_transaction'
    C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/activerecord-5.0.0.1/lib/active_record/connection_adapters/abstract/database_statements.rb:232:in `transaction'
    C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/activerecord-5.0.0.1/lib/active_record/transactions.rb:211:in `transaction'
    C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/activerecord-5.0.0.1/lib/active_record/associations/collection_association.rb:202:in `transaction'
    C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/activerecord-5.0.0.1/lib/active_record/associations/collection_association.rb:391:in `replace'
    C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/activerecord-5.0.0.1/lib/active_record/associations/collection_association.rb:78:in `ids_writer'
    C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/activerecord-5.0.0.1/lib/active_record/associations/builder/collection_association.rb:66:in `job_manager_ids='
    validates_associated.rb:85:in `test_context_validation_stuff'

1 runs, 0 assertions, 0 failures, 1 errors, 0 skips

# **System configuration**

Rails version: Rails 5.0.0.1
Ruby version: 
- ruby 2.3.0p0 (2015-12-25 revision 53290) [x64-mingw32]
- ruby 2.3.1p112 (2016-04-26 revision 54768) [x64-mingw32]

DB:
- PostgreSQL 9.6
- Sqlite3

**Comment by danielterega** [comment]
It seems to be an expected behaviour. 
You can try `update_attributes` method to avoid exception raising:
```
unless job.update_attributes({:job_technic_ids => [2]})
  p job.errors.messages
end
```

**Comment by francesco-loreti** [comment]
any?

**Comment by sngeth** [comment]
I'm not quite sure i'm following your business logic 100%, but it looks like the validate_uniqueness_of is being executed and thrown:

https://github.com/francesco-loreti/recordinvalid/blob/master/validates_associated_model.rb#L71

You  attempt to add a job manager id == 2 when the job already has a job_technic_id containing 2 and therefore it triggers the validation error
