### ISSUE TITLE
No "add_index" in schema.rb after migrations

### ISSUE THREAD

**Issue by culov** [rails/rails#26983]
Ruby 1.9.3
Rails 3.12
Postgres

I have a large database with 50 or so tables a resulting schema.rb file of about 2000 lines. Everytime I run a migration, EVERY add_index line is deleted from the schema.rb in the newly generated file. I can add/remove columns or tables, but the add_index lines are never included in the file.

When connect to psql and check whether the tables have the indices, it's clear that they DO. But for some reason they're not being included in the schema.rb file. I am completely out of ideas as to why this is happening, and I can't find any instances of anyone else having this problem online.

Any ideas what may be causing this issue?

**Comment by rafaelfranca** [comment]
Rails 3 is not maintained anymore. Please check if it is still working in Rails 5
