### ISSUE TITLE
Rails tutorial authentication

### ISSUE THREAD

**Issue by ejsorrento** [rails/rails#26984]
Hi guys, 

New to Rails, I've been using this link to practice building apps "http://guides.rubyonrails.org/getting_started.html". For some reason when I plug in the authentication part of the exercise, I am continually prompted to input my user information. That's a no, no. Don't know if others have had this problem. 

Hopefully I'm sending this to the right people, as this was the link provided.
Thanks!
EJ Sorrento

**Comment by lustremedia** [comment]
Hey what Section of the guide are you talking about? 9.1 Basic authentication?

**Comment by ekampp** [comment]
I would expect that most rails applications would need something more feature-rich than basic authentication. There are also security concerns that would be prudent to educate about, such as don't store plain passwords, etc.

**Comment by utilum** [comment]
@ejsorrento did you try entering the values in the code, "dhh" for name and "secret" for password?

**Comment by cefigueiredo** [comment]
@ejsorrento We need more information to figure out what happened and what it was expected to happen...
Can you please show us the code you added on the controller for http_authentication? The getting started shown 2, where on the first:

```
class ArticlesController < ApplicationController
 
  http_basic_authenticate_with name: "dhh", password: "secret", except: [:index, :show]
 
  def index
    @articles = Article.all
  end
```

It was expected to ask for authentication only when you try to access `articles/new`, `articles/1/edit` or tried to delete some. And if you followed exactly what was writen, filling with the username `dhh` and the password `secret`  would be enough to let you pass and only ask again when refreshing or accessing other route.

The other controller with basic authentication shown was
```
class CommentsController < ApplicationController
 
  http_basic_authenticate_with name: "dhh", password: "secret", only: :destroy
 
  def create
    @article = Article.find(params[:article_id])
    # ...
  end
```

And it was expected to ask for username and password just when you try Destroy a comment.

These are exactly the code you wrote or did you add anything else?


-----
And @ekampp, Mostly apps I worked on use something more feature-rich than basic authentication, but the Getting Started tutorial is for beginners and only mentions these third-party features (like Devise). Mostly of the richer authentication plugins obfuscate many of the knowledge you could get implementing something simpler by yourself. When you are learning, it is good to invest some time dealing with things yourself to practice and preferably identifying vulnerabilities and trying to solve...
Then, be aware of possible third-party gems that are well maintained and let solve the issues in a productive way.

I also agree that the security concerns you mentioned are really important to know, but they are already covered on the Security Guides (and the getting-started tutorial mentions it)... by curiosity, the security guide specifically recommends store encrypted passwords besides plain text on the first paragraph here http://guides.rubyonrails.org/security.html#user-management
