### ISSUE TITLE
Ambiguous column name when mixing joins and left_outer_joins on the same association

### ISSUE THREAD

**Issue by aergonaut** [rails/rails#26985]
### Steps to reproduce

Please see my example app illustrating the bug: https://github.com/aergonaut/join_conflict_example

1. Create a model (e.g. `Post`) that has an association to another model (e.g. `User`)
2. Construct a query that uses both `joins` and `left_outer_joins` on the same association (e.g. `Post.joins(:user).left_outer_joins(:user)`)
3. Run the query and observe the error:

```
ActiveRecord::StatementInvalid: SQLite3::SQLException: ambiguous column name: users.id:  
SELECT "posts".* FROM "posts" INNER JOIN "users" ON "users"."id" = "posts"."user_id" LEFT OUTER JOIN "users" ON "users"."id" = "posts"."user_id"
```

### Expected behavior

I would expect that ActiveRecord would alias the table the second time it is referenced in the `LEFT OUTER JOIN`.

The example makes this situation seem kind of contrived, but I think it's very reasonable to assumed that in a large application, with lots of different scopes, that it's possible to want to combine two scopes that reference the same association with different kinds of joins.

### Actual behavior

Ambiguous column name error is raised instead.

### System configuration
**Rails version**: 5.0.0.1

**Ruby version**: 2.3.1p112

**Comment by aergonaut** [comment]
Addendum: I'd love to make a PR to fix this, but I'm not sure where to start!

**Comment by SaiVardhan** [comment]
@aergonaut  I think we should not call `LeftOuterJoin` on a `InnerJoin` for the same table

**Comment by uaihebert** [comment]
What is the reason for this query? I see no point in doing this kind of query.

**Comment by plentz** [comment]
I think that the best way is to "solve" this is to ignore the left join when a inner join already exists. Another possible solution is to add a check when doing joins and raise an exception in case of a join already exists in that relation.

If someone from rails core team can decide this, I can work on a PR.

**Comment by al2o3cr** [comment]
It's certainly possible to have this sort of query, usually in more complicated reporting situations. 

One gotcha with auto-aliasing the joined table name is that it's not particularly discoverable, so additional queries that want to reference it get very brittle. Maybe an explicit `as` option (so `some_relation.left_outer_join(:users, as: :foos)`) or similar would be an escape hatch?

**Comment by christopheraue** [comment]
This:
```ruby
left_join = ActiveRecord::Associations::JoinDependency.new(relation.klass, associations, relation.joins_values)
relation.joins(left_join)
```
is doing what:
```ruby
relation.left_outer_joins(associations)
```
should do. It aliases the joined tables correctly.

The thing with the JoinDependency is happening when doing a left join with `includes(associations).where(...)`, if I see it correctly.

**Comment by 97jaz** [comment]
Yes, this is still an issue in 5.1.2. In my case, I have an AR model with two different associations that reference the same table. In a query, I'm performing an inner join on one of them and an outer on the other. AR chooses the same table alias for both, leading to a syntax error.

**Comment by k4ju** [comment]
Still an issue, I've got similar situation as @97jaz have described it. I filter and sort a relation using left_outer_joins for one and joins for the other. They may happen to be used simultaneously. Right now I'll just guard against such a situation, but it'd be better to one took precedence over the other.
