### ISSUE TITLE
ActionCable streaming performance

### ISSUE THREAD

**Issue by palkan** [rails/rails#26999]
The current implementation of streaming has a rather poor performance (of course, you've heard about [websocket shootout](https://hashrocket.com/blog/posts/websocket-shootout)).

One of the bottlenecks is the [callback hell](https://github.com/rails/rails/blob/9588a3d66d4ca6ba122d32417aa62680f441bf40/actioncable/lib/action_cable/channel/streams.rb#L120-L171). Instead of simply broadcasting messages to sockets we create a callback wrapped in a callback wrapped in another callback etc.
And we also decode and encode message again for every socket.

Here is the [benchmark](https://gist.github.com/palkan/3a77eabb7229d763a53d1d709b9d92e0) I wrote to measure the performance. The results are following:

```
# Very simple transmitter: just broadcast message as is (and adds identifier)
  SimpleSubscriberMap   239.738  (±21.3%) i/s -      1.120k in   5.003338s

# Simple transmitter with JSON round-trip
DecodingSubscriberMap   227.131  (±19.4%) i/s -      1.083k in   5.041594s

# Current ActionCable implementation
        SubscriberMap     9.040  (±11.1%) i/s -     45.000  in   5.028229s

```

Websocket Shootout benchmark also shows that callback-less version (using [this](https://gist.github.com/palkan/42891d59f17f2cf98a074a073a0dbf35) very simple patch) is performing much better (see [slides](https://speakerdeck.com/palkan/railsclub-moscow-2016-anycable#74)). 

So, I have a couple of proposals.

**Soft Proposal**

- do not create _useless_ callbacks when there are no user-specified handlers

- do not decode/encode messages for each socket

**Hard Proposal**

_Soft Proposal_ +  ...

- deprecate custom streaming callbacks, 'cause they influence broadcasting performance (and, IMO, they don't make any sense but provide overhead).

/cc @matthewd @maclover7

**Comment by matthewd** [comment]
> Soft Proposal
> * do not create useless callbacks when there are no user-specified handlers
> * do not decode/encode messages for each socket

[Good idea](https://github.com/rails/rails/blob/9588a3d66d4ca6ba122d32417aa62680f441bf40/actioncable/lib/action_cable/channel/streams.rb#L145-L147).

> Hard Proposal
> * deprecate custom streaming callbacks

That doesn't make much sense to me. The point of Action Cable is not to implement websocket connections in Ruby because it's fun -- it's to give the implementation access to the running Rails app. Making straight retransmission faster is worthwhile, but it's not the only valid use case.

**Comment by maclover7** [comment]
@palkan Thank you for opening up this issue! You've outlined some interesting performance proposals in the description -- thank you for taking the time to look into this. The best way forward is to start opening up PRs with patches, to get community and Rails team feedback.

**Comment by dhh** [comment]
When you say "custom streaming callbacks", you're talking about after_subscribed and friends in [callbacks](https://github.com/rails/rails/blob/master/actioncable/lib/action_cable/channel/callbacks.rb)? I can see that these are used to power the periodic timers. And we also use one of the callbacks one time. But I think we can be more efficient with these and basically only enable them on a channel if the channel implements that method. If that's too hard, I'm actually also OK with having an explicit method to turn them on, like "uses_subscription_callbacks" or similar. Then channels that don't use that won't suffer the performance penalty.

**Comment by palkan** [comment]
@dhh
I meant these _callbacks_:

```ruby
stream_from "notifications" do |msg|
  # do custom broadcasting
end
```

Maybe, _interceptors_ could be a better naming.

ActiveModel-like callbacks do not cause any problems, of course)

Sorry for misunderstanding 😔

**Comment by dhh** [comment]
I don't care so much for stream_from, but stream_for, which I believe just
calls that, is pivotal. Can't do without those. That's the main way we're
configuring which streams a channel should be listening for. Happy to see
it optimized, though. Lest you have any other ideas?

**Comment by NirvashPrime** [comment]
I see this hasn't been updated in almost two years, is this still an issue?

**Comment by palkan** [comment]
> is this still an issue?

Since nothing has changed in the way stream callbacks work it is.

**Comment by ProGM** [comment]
Hello everyone,

I'm taking a look to this issue as a suggestion coming from CodeTriage.

I know it's a pretty old issue, but it's still there and the code of that part looks pretty unchanged. So I like to take a look.


First of all, I've noticed is that the benchmark linked in the first post by @palkan  is **broken**.

The reason is simple: in the example, the method `logger` was returning `nil`, so `logger.debug` raised a `NoMethodError`, invalidating the test.

Since all that code was executed inside an `async_invoke`, the error was invisible.

Here's an updated benchmark:
https://gist.github.com/ProGM/1fbb13fa28ce27f214d8a86ea1d2738a

And the results:
```
# Very simple transmitter: just broadcast message as is (and adds identifier)
 SimpleSubscriberMap        444.971  (± 7.0%) i/s -      2.210k in   5.003435s

# Simple transmitter with JSON round-trip
DecodingSubscriberMap       446.882  (± 7.2%) i/s -      2.240k in   5.051420s

# Current ActionCable implementation
 SubscriberMap              271.715  (± 2.2%) i/s -      1.377k in   5.070107s
```

As you can see, the difference between the ActionCable implementation is still there, but it's not THAT significant as it appeared in the benchmark.

However, now I'll try to check if there's room for improvement. If so, would you accept a Pull Request?

**Comment by byroot** [comment]
Running that script with Rails 8.0 and YJIT:

```
$ ruby --yjit /tmp/ac.rb
Fetching gem metadata from https://rubygems.org/............
Resolving dependencies...
ruby 3.3.4 (2024-07-09 revision be1089c8ec) +YJIT [arm64-darwin23]
Warming up --------------------------------------
 SimpleSubscriberMap    88.000 i/100ms
DecodingSubscriberMap
                        97.000 i/100ms
       SubscriberMap   124.000 i/100ms
Calculating -------------------------------------
 SimpleSubscriberMap      1.035k (±19.3%) i/s  (965.73 μs/i) -      5.016k in   5.030762s
DecodingSubscriberMap
                          1.017k (±17.0%) i/s  (982.94 μs/i) -      4.947k in   5.002120s
       SubscriberMap      1.293k (±17.9%) i/s  (773.31 μs/i) -      6.324k in   5.033887s
```

I think we can close.

**Comment by palkan** [comment]
@byroot Thanks for checking this.

My guts told me we're not done here, so I rewrote the benchmark and got results that still show the performance could still be improved: https://github.com/anycable/actioncable-next/pull/10

**Comment by byroot** [comment]
PR welcome :)
