### ISSUE TITLE
db:migrate log output and verbosity options

### ISSUE THREAD

**Issue by brad-werth** [rails/rails#26996]
### Steps to reproduce

`rails new db_logging_test`
`cd db_logging_test/`
`bin/rails generate migration EmptyMigration`
`bundle exec rake db:migrate`

### Expected behavior

What shows up on the screen and in the log should match, with the ability to granularly specify logging verbosity without resorting to [hacky workarounds](http://stackoverflow.com/q/4100512/525478) or [additional configuration](http://stackoverflow.com/q/2634142/525478).

##### With VERBOSE=true

```
D, [2016-11-08T13:17:58.696193 #16770] DEBUG -- :    (12.2ms)  CREATE TABLE "schema_migrations" ("version" varchar NOT NULL PRIMARY KEY)
D, [2016-11-08T13:17:58.716975 #16770] DEBUG -- :    (19.3ms)  CREATE TABLE "ar_internal_metadata" ("key" varchar NOT NULL PRIMARY KEY, "value" varchar, "created_at" datetime NOT NULL, "updated_at" datetime NOT NULL)
D, [2016-11-08T13:17:58.722476 #16770] DEBUG -- :   ActiveRecord::SchemaMigration Load (0.1ms)  SELECT "schema_migrations".* FROM "schema_migrations"
I, [2016-11-08T13:17:58.724690 #16770]  INFO -- : Migrating to EmptyMigration (20161108185720)
D, [2016-11-08T13:17:58.725810 #16770] DEBUG -- :    (0.0ms)  begin transaction
== 20161108185720 EmptyMigration: migrating ===================================
== 20161108185720 EmptyMigration: migrated (0.0000s) ==========================

D, [2016-11-08T13:17:58.729459 #16770] DEBUG -- :   SQL (0.2ms)  INSERT INTO "schema_migrations" ("version") VALUES (?)  [["version", "20161108185720"]]
D, [2016-11-08T13:17:58.737165 #16770] DEBUG -- :    (7.5ms)  commit transaction
D, [2016-11-08T13:17:58.739030 #16770] DEBUG -- :   ActiveRecord::InternalMetadata Load (0.1ms)  SELECT  "ar_internal_metadata".* FROM "ar_internal_metadata" WHERE "ar_internal_metadata"."key" = ? LIMIT ?  [["key", :environment], ["LIMIT", 1]]
D, [2016-11-08T13:17:58.741616 #16770] DEBUG -- :    (0.0ms)  begin transaction
D, [2016-11-08T13:17:58.742433 #16770] DEBUG -- :   SQL (0.1ms)  INSERT INTO "ar_internal_metadata" ("key", "value", "created_at", "updated_at") VALUES (?, ?, ?, ?)  [["key", "environment"], ["value", "development"], ["created_at", 2016-11-08 19:17:58 UTC], ["updated_at", 2016-11-08 19:17:58 UTC]]
D, [2016-11-08T13:17:58.750108 #16770] DEBUG -- :    (7.5ms)  commit transaction
D, [2016-11-08T13:17:58.752878 #16770] DEBUG -- :   ActiveRecord::SchemaMigration Load (0.0ms)  SELECT "schema_migrations".* FROM "schema_migrations"


```

##### With VERBOSE=false

```
== 20161108185720 EmptyMigration: migrating ===================================
== 20161108185720 EmptyMigration: migrated (0.0000s) ==========================

```

##### With QUIET=true

Nothing is output. May be necessary for backward-compatibility for `VERBOSE=false`.

### Actual behavior

What shows up on the screen and in the log can differ, no ability to specify additional logging verbosity without resorting to [hacky workarounds](http://stackoverflow.com/q/4100512/525478) or [additional configuration](http://stackoverflow.com/q/2634142/525478).

##### With VERBOSE=true

```
== 20161108185720 EmptyMigration: migrating ===================================
== 20161108185720 EmptyMigration: migrated (0.0000s) ==========================

```

##### With VERBOSE=false

Nothing is output.

##### With QUIET=true

This option does not currently exist.

### System configuration
**Rails version**: 5.0.0.1

**Ruby version**: 2.3.1

**Comment by rafaelfranca** [comment]
Thank you so much for the issue but we don't take feature request on the issue tracker. We recommend you to try to implement the feature and send us a pull request or if you are in doubt if the feature will be accepts ask in Rails Core mailing list for feedback.
