### ISSUE TITLE
require_dependency fix for autoloading and STI causes circular dependency error

### ISSUE THREAD

**Issue by kreintjes** [rails/rails#26994]
Rails' autoloading does not work correctly in combination with Single Table Inheritance when having subclasses more than one level deep. This is a known problem described in the Rails guides here: http://guides.rubyonrails.org/autoloading_and_reloading_constants.html#autoloading-and-sti. There is a fix mentioned, but applying this leads to a circular dependency RuntimeError.

### Steps to reproduce
To ease reproduction I have created a demo application following the example from the guides: https://github.com/kreintjes/rails-autoloading-sti-demo.

- Checkout the branch [guides fix](https://github.com/kreintjes/rails-autoloading-sti-demo/tree/guides-fix) of the demo application.
- Run bundler, migrations, etc.
- Execute `Rectangle.all` in a Rails console.

### Expected behavior
I expected the command to return all Rectangles, i.e:

```
irb(main):002:0> Rectangle.all
  Rectangle Load (0.1ms)  SELECT "polygons".* FROM "polygons" WHERE "polygons"."type" IN ('Rectangle', 'Square')
=> #<ActiveRecord::Relation [#<Square id: 1, type: "Square", created_at: "2016-11-07 08:56:42", updated_at: "2016-11-07 08:56:42">]>
```

### Actual behavior
An error is raised: "RuntimeError: Circular dependency detected while autoloading constant Rectangle" 

### System configuration
**Rails version**: 5.0.0.1

**Ruby version**: ruby 2.3.0p0

### Possible fix
I have managed to create an alternative fix that does work, namely by requiring all direct sub classes for all intermediate classes. I am happy to update the guides with this new fix, but I am wondering if this is the way to go. It could also be possible there is an underlying problem with the autoloading feature, but I am not sure. Any suggestions on how to proceed would be appreciated.

An example of the working fix can be found in the [working fix](https://github.com/kreintjes/rails-autoloading-sti-demo/tree/working-fix) branch.

**Comment by maclover7** [comment]
cc @fxn

**Comment by pixeltrix** [comment]
@kreintjes I can't seem to reproduce the problem with your app:

```
$ rake db:setup
Created database 'db/development.sqlite3'
Created database 'db/test.sqlite3'
-- create_table("polygons", {:force=>:cascade})
   -> 0.0063s
-- initialize_schema_migrations_table()
   -> 0.0014s
-- create_table("polygons", {:force=>:cascade})
   -> 0.0019s
-- initialize_schema_migrations_table()
   -> 0.0013s
$ rails c
>> Rectangle.all
Rectangle Load (0.1ms)  SELECT "polygons".* FROM "polygons" WHERE "polygons"."type" IN ('Rectangle')
=> #<ActiveRecord::Relation []>
```

Can you try with Ruby 2.3.1?

**Comment by fxn** [comment]
I think the problem is the following:

1) On a cold launch you evaluate the `Rectangle` constant.
2) That goes to _app/models/rectangle.rb_, and `Polygon` needs to be autoloaded.
3) Which goes to _app/models/polygon.rb_.
4) Which loads _app/models/square.rb_ by hand.
5) Which triggers autoload of `Rectangle`, since 2) did not get a chance.

Yes, the workaround in the guide is not good for this use case.

**Comment by fxn** [comment]
@kreintjes how would the fix you have in mind be in the sample application?

**Comment by matthewd** [comment]
I may be wrong, but I think the proposed fix is still circular, just in a different direction -- so it would fix the particular arrangement shown here, but introduce a problem given a slightly different class hierarchy

**Comment by kreintjes** [comment]
@pixeltrix I tried updating to Ruby 2.3.1 and 2.3.2. The problem still occurs.

@fxn see the working-fix branch: https://github.com/kreintjes/rails-autoloading-sti-demo/tree/working-fix. So instead of `require_dependency 'square'` in [polygon.rb](https://github.com/kreintjes/rails-autoloading-sti-demo/blob/working-fix/app/models/polygon.rb), one would get `require_dependency 'square'` in [rectangle.rb](https://github.com/kreintjes/rails-autoloading-sti-demo/blob/working-fix/app/models/rectangle.rb).

@matthewd I have tried loading the other models (Polygon, Square and Triangle) on cold boot and this all seems to work. I also use the proposed fix in a real world application with a more complex STI hierarchy:

```
A => AA
   => AB
   => AC => ACA
              => ACB => ACBA
                           => ACBB
```

Loading any of the models on cold boot works. Querying any of the models also includes all sub types. This app is still running Rails 4.2 however.

**Comment by maxkwallace** [comment]
If it's at all helpful, I'm running into the same issue (but on Rails 5) with a hierarchy that looks like

```
A < ApplicationRecord

B < A

C < B
D < B
```

I.e. two "leaf" classes share the same parent, which has one superclass, using STI. 

To replicate, run `rails c` followed by `Student.all` in the repo https://github.com/maxkwallace/rails-sti-circular-dep-issue .

kreintjes's solution seems to work. Thanks!

**Comment by kreintjes** [comment]
You're welcome @maxkwallace and thanks for your feedback. So shall I update the guides @fxn/@matthewd?

**Comment by rafaelfranca** [comment]
Yes, please

**Comment by kreintjes** [comment]
Done, see https://github.com/rails/rails/pull/28240
