### ISSUE TITLE
--api flag isn't applied

### ISSUE THREAD

**Issue by itsNikolay** [rails/rails#27001]
### Steps to reproduce
1. Create `~/.railsrc` file with the content
```sh
--skip-bundle
--skip-test
--database=postgresql
```
2. Run `rails new my_api --api`
3. Check that api feature wasn't applied

### Expected behavior
Api must be applied

### Actual behavior
Api isn't applied

### System configuration
**Rails version**:
Rails 5.0.0.1

**Ruby version**:
ruby 2.3.1p112 (2016-04-26 revision 54768) [x86_64-darwin15]

**Comment by maclover7** [comment]
Hmm, I think the `--api` was interpreted correctly. When I run the command above on my machine, it creates an `ApplicationController` class which inherits from `ActionController::API`, which is the desired behavior.
