### ISSUE TITLE
Unexpected behaviour of root route with format: false constraint

### ISSUE THREAD

**Issue by majkelcc** [rails/rails#27000]
### Steps to reproduce

routes.rb:
```ruby
    constraints format: false do
      controller :landing do
        get "/", action: :index
        get "/something", action: :index
      end
    end
```

### Expected behavior
`/` and `/something` paths should resolve to `landing#index` action

### Actual behavior
only `/something` works, `/` returns a 404

### System configuration
**Rails version**:
5.0.0.1

**Ruby version**:
2.3

**Comment by majkelcc** [comment]
I just ran into some weird errors while using `format: false`. Is `false` value valid here? I imagined it forced the format not to be present, but it seemed to break the router.

**Comment by maclover7** [comment]
Hi @majkelcc, can you confirm your Rails version? I think you swapped the Ruby and Rails versions in the issue template :)

**Comment by majkelcc** [comment]
Hi @maclover7, correct, updated :)

**Comment by utilum** [comment]
[Executable Test Case](https://gist.github.com/utilum/cfe0d1991ead1834267fc19b8980dd45)

**Comment by maclover7** [comment]
Can confirm test failure on Rails master. Test also fails on `4-2-stable`, so this is not a regression in behavior.
