### ISSUE TITLE
nil:NilClass exception when calling #performed? on controller

### ISSUE THREAD

**Issue by vinagrito** [rails/rails#27011]
So having a test that does:
```ruby
controller.performed?
```
Generates in my case an exception:
```
NoMethodError:
       undefined method `committed?' for nil:NilClass
   # ./.bundle/gems/actionpack-5.0.0.1/lib/action_controller/metal.rb:185:in `performed?'
```
Seems logical since I see that the implementation of ` #performed?` changed from:
```ruby
def performed?
  response_body || (response && response.committed?)
end
```
to:
```ruby
def performed?
  response_body || (response.committed?)
end
```

### System configuration
**Rails version**: rails-5.0.0.1
**Ruby version**: 2.2.5

**Comment by prathamesh-sonpatki** [comment]
@vinagrito Can you also post the test case details here?

**Comment by vinagrito** [comment]
@prathamesh-sonpatki so when migrating to rails5 I found the next test failing in my code.
```ruby
it "does not perform (render or redirect)" do
   controller.verify_hmac_signature
   expect(!!controller.performed?).to eq(false)
end
```
The controller has something like
```ruby
def verify_hmac_signature
   render status: :forbidden unless hmac_signature_valid?
end
```
And as you can expect `#hmac_signature_valid?` returns a boolean

**Comment by prathamesh-sonpatki** [comment]
@vinagrito Is it `ActionController::TestCase` test case or `ActionDispatch::IntegrationTest` ?

**Comment by kaspth** [comment]
It's much easier for us if you can reproduce in a sample app. Spares a lot of back and forth :)

**Comment by prathamesh-sonpatki** [comment]
@vinagrito Yup, please upload the sample app as Kasper suggested.

Also I am not sure why you are hitting the action using `controller.verify_mac_signature`. Shouldn't it be `get :verify_mac_signature` for ActionController::TestCase or `get verify_mac_signature_url`  for ActionDispatch::IntegrationTest? 

I think that is the reason why you are getting this error.

**Comment by vinagrito** [comment]
@kaspth I'd had gladly written a test that tries to reproduce the issue...but honestly 😬 I didn't manage to run a single actionpack test (it was much simpler running the activerecord suite). So if you could just drop a line on how you run any test there I'll follow.
@prathamesh-sonpatki the method in the controller is not routed...it's just a controller filter (action)

**Comment by prathamesh-sonpatki** [comment]
I am not sure `controller.verify_hmac_signature` is supported. Can you confirm that this issue persists even after hitting the action  which uses this filter the normal way using `get` or `post` helpers?

**Comment by kaspth** [comment]
@vinagrito you don't need to run any Action Pack tests use `rails new reproduce_27011` then reproduce the problem you're seeing with as little code as you can.

However, I don't think we'll be needing it in this case as @prathamesh-sonpatki is on the money. `controller.<action_name>` is not supported in either `ActionController:TestCase` or `ActionDispatch::IntegrationTest`. Thus the problem is probably in your test code. Thanks!

**Comment by vinagrito** [comment]
@kaspth could it be related to the fact that my controller class tests are inherited form `ActionController::TestCase` and not from `ActionDispatch::IntegrationTest`...which does have`@controller` defined and allows me to do the action call as described above.

**Comment by vinagrito** [comment]
@kaspth so just to make sure. That failing test is passing on rails 4.2.7. According to:
`actionpack-5.0.0.1/lib/action_controller/test_case.rb:249`
```
  # == Special instance variables
  #
  # ActionController::TestCase will also automatically provide the following instance
  # variables for use in the tests:
  #
  # <b>@controller</b>::
  #      The controller instance that will be tested.
  # <b>@request</b>::
  #      An ActionController::TestRequest, representing the current HTTP
  ... (goes on)
```
The call is supported... since I'm reaching the controller action (even though if it isn't in the nicest way). So maybe I didn't provide a clear explanation but the scenario is that I have access to the `controller` instance variable and I can call any method (action) defined in controller but in the new `/actionpack-5.0.0.1/lib/action_controller/metal.rb:185` implementation if crashes. 

My precise code is:
```ruby
module Api
  module V1
    class ApplicationController < ActionController::Base
      respond_to :json
      before_action :verify_hmac_signature

      def hmac_signature_valid?
        # some processing here and it returns a boolean
      end

      def verify_hmac_signature
        # the call reaches this point
        render status: :forbidden unless hmac_signature_valid?
      end
    end
  end
end
```
```ruby
require "spec_helper"

RSpec.describe Api::V1::ApplicationController do
  RSpec.describe "#verify_hmac_signature" do
   context "with valid signature" do
      it "does not perform (render or redirect)" do
        controller.verify_hmac_signature
        expect(!!controller.performed?).to eq(false)
      end
    end
  end
end
```
Appreciated

**Comment by kaspth** [comment]
> PS (this is the moment to hit me with some info I didn't take in consideration 😬 )

No thanks, I'm out 👍

Feel free to consult the `ActionController::TestCase` docs and compare the testing API to how you're calling it. Have a nice day 🤘

**Comment by vinagrito** [comment]
@kaspth @prathamesh-sonpatki  any chance you could take a look at this https://github.com/vinagrito/reproduce_27011
Just clone it and run `rspec .` I'd gladly accept any input on what I'm doing here

**Comment by kaspth** [comment]
Let me expand on my last comment.

This is the official API for `ActionController::TestCase`: https://github.com/rails/rails/blob/6d6249b1c1abda4f62fafcc42a7ece570c8da7e9/actionpack/lib/action_controller/test_case.rb#L390-L456

In your test that would be:

```ruby
get :verify_hmac_signature
```

But you're not using the official `get` and friends API, so your test passing in Rails 4.2 was purely coincidental. There's no bug here because you're not using the API correctly.

Let me repeat: calling the controller action directly, e.g. `controller.verify_hmac_signature`, was never supported. This is the last I'll say about this, thanks! 😉

**Comment by prathamesh-sonpatki** [comment]
Yup, as Kasper said!
