### ISSUE TITLE
Error when dropping a SQLite DB on MS-Windows

### ISSUE THREAD

**Issue by gallelli** [rails/rails#27015]
O.S.:  MS-Windows 10 (but I guess also previous releases)
Ruby: version 2.3.1 (but I guess also previous releases)
ActiveRecord: version 5.0.0.1 (but I guess also previous releases)
RDBMS: sqlite3
Framework: Rails or Sinatra

Running  the "rake db:drop" command you get the following error: 
Permission denied @ unlink_internal - (DB pathname follows...)
Couldn't drop database 'db/development.sqlite3'
rake aborted!
Errno::EACCES: Permission denied @ unlink_internal - (DB pathname follows...)
Tasks: TOP => db:drop:_unsafe
(See full trace by running task with --trace)

It is NOT a matter of access privileges to the SQLite DB file!
An obvious workaround is to remove the file manually.
I went through the ActiveRecord source code and I think I found out why this happens.
When trying to drop the DB (i.e. remove the DB file), there is still a connection open to the DB, which keeps the file locked, preventing it from being deleted (probably only on MS-Windows systems); such connection should be closed before removing the file.
In my opinion, the source file:
    ...\gems\activerecord-5.0.0.1\lib\active_record\tasks\sqlite_database_tasks.rb
should be modified as follows:
1. Delegate also the "remove_connection" method:
    delegate :connection, :establish_connection, :remove_connection, to: ActiveRecord::Base
2. Modify the drop method as follows:
      def drop
        require 'pathname'
        path = Pathname.new configuration['database']
        file = path.absolute? ? path.to_s : File.join(root, path)
        remove_connection
        FileUtils.rm(file)
      rescue Errno::ENOENT => error
        raise NoDatabaseError.new(error.message, error)
      end

**Comment by prathamesh-sonpatki** [comment]
@gallelli Can you post full stacktrace in a gist?

**Comment by gallelli** [comment]
Here it is:   https://gist.github.com/gallelli/8f0b6dbe9cc1d5289b8acb1c1570eb86

**Comment by gallelli** [comment]
The same error still occurs in rails 5.1.1 on Windows 10, with rake 12.0.0, sqlite3 (1.3.13 x86-mingw32) and both Ruby MRI 2.3.3 and 2.4.1.
You can simply reproduce it by running:

rails new droptest
cd droptest
rake db:create
rake db:drop

**Comment by rafaelfranca** [comment]
Please go ahead and open a PR

**Comment by gallelli** [comment]
Please re-open this issue.
The same error still occurs in Rails 5.1.4 on Windows 10, with rake 12.1.0, sqlite3 (1.3.13 x86-mingw32) and either Ruby MRI 2.3.3 or 2.4.2 or JRuby 9.1.13.0.
You can simply reproduce it by running:

rails new droptest
cd droptest
rake db:create
rake db:drop

It is a Windows problem, in Linux the behaviour is correct!

**Comment by 13ogue** [comment]
**On rails db:migrate:reset, I get :**

Couldn't drop database 'db/development.sqlite3'
rails aborted!
Errno::EACCES: Permission denied @ unlink_internal - C:/Users/Arthas/Documents/must3/practice/html/Rails/sample_app/db/development.sqlite3
bin/rails:4:in `require'
bin/rails:4:in `<main>'
Tasks: TOP => db:drop:_unsafe
(See full trace by running task with --trace)

**And on "rails db:migrate:reset --trace"**

** Invoke db:migrate:reset (first_time)
** Invoke db:drop (first_time)
** Invoke db:load_config (first_time)
** Execute db:load_config
** Invoke db:check_protected_environments (first_time)
** Invoke environment (first_time)
** Execute environment
** Invoke db:load_config
** Execute db:check_protected_environments
** Execute db:drop
** Invoke db:drop:_unsafe (first_time)
** Invoke db:load_config
** Execute db:drop:_unsafe
Permission denied @ unlink_internal - C:/Users/Arthas/Documents/must3/practice/html/Rails/sample_app/db/development.sqlite3
Couldn't drop database 'db/development.sqlite3'
rails aborted!
Errno::EACCES: Permission denied @ unlink_internal - C:/Users/Arthas/Documents/must3/practice/html/Rails/sample_app/db/development.sqlite3
C:/Ruby24-x64/lib/ruby/2.4.0/fileutils.rb:1341:in `unlink'
C:/Ruby24-x64/lib/ruby/2.4.0/fileutils.rb:1341:in `block in remove_file'
C:/Ruby24-x64/lib/ruby/2.4.0/fileutils.rb:1349:in `platform_support'
C:/Ruby24-x64/lib/ruby/2.4.0/fileutils.rb:1340:in `remove_file'
C:/Ruby24-x64/lib/ruby/2.4.0/fileutils.rb:704:in `remove_file'
C:/Ruby24-x64/lib/ruby/2.4.0/fileutils.rb:507:in `block in rm'
C:/Ruby24-x64/lib/ruby/2.4.0/fileutils.rb:506:in `each'
C:/Ruby24-x64/lib/ruby/2.4.0/fileutils.rb:506:in `rm'
C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/activerecord-5.1.2/lib/active_record/tasks/sqlite_database_tasks.rb:22:in `drop'
C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/activerecord-5.1.2/lib/active_record/tasks/database_tasks.rb:144:in `drop'
C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/activerecord-5.1.2/lib/active_record/tasks/database_tasks.rb:160:in `block in drop_current'
C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/activerecord-5.1.2/lib/active_record/tasks/database_tasks.rb:304:in `block in each_current_configuration
'
C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/activerecord-5.1.2/lib/active_record/tasks/database_tasks.rb:303:in `each'
C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/activerecord-5.1.2/lib/active_record/tasks/database_tasks.rb:303:in `each_current_configuration'
C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/activerecord-5.1.2/lib/active_record/tasks/database_tasks.rb:159:in `drop_current'
C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/activerecord-5.1.2/lib/active_record/railties/databases.rake:42:in `block (2 levels) in <top (required)>
'
C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/rake-12.1.0/lib/rake/task.rb:251:in `block in execute'
C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/rake-12.1.0/lib/rake/task.rb:251:in `each'
C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/rake-12.1.0/lib/rake/task.rb:251:in `execute'
C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/rake-12.1.0/lib/rake/task.rb:195:in `block in invoke_with_call_chain'
C:/Ruby24-x64/lib/ruby/2.4.0/monitor.rb:214:in `mon_synchronize'
C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/rake-12.1.0/lib/rake/task.rb:188:in `invoke_with_call_chain'
C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/rake-12.1.0/lib/rake/task.rb:181:in `invoke'
C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/activerecord-5.1.2/lib/active_record/railties/databases.rake:38:in `block (2 levels) in <top (required)>
'
C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/rake-12.1.0/lib/rake/task.rb:251:in `block in execute'
C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/rake-12.1.0/lib/rake/task.rb:251:in `each'
C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/rake-12.1.0/lib/rake/task.rb:251:in `execute'
C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/rake-12.1.0/lib/rake/task.rb:195:in `block in invoke_with_call_chain'
C:/Ruby24-x64/lib/ruby/2.4.0/monitor.rb:214:in `mon_synchronize'
C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/rake-12.1.0/lib/rake/task.rb:188:in `invoke_with_call_chain'
C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/rake-12.1.0/lib/rake/task.rb:217:in `block in invoke_prerequisites'
C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/rake-12.1.0/lib/rake/task.rb:215:in `each'
C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/rake-12.1.0/lib/rake/task.rb:215:in `invoke_prerequisites'
C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/rake-12.1.0/lib/rake/task.rb:194:in `block in invoke_with_call_chain'
C:/Ruby24-x64/lib/ruby/2.4.0/monitor.rb:214:in `mon_synchronize'
C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/rake-12.1.0/lib/rake/task.rb:188:in `invoke_with_call_chain'
C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/rake-12.1.0/lib/rake/task.rb:181:in `invoke'
C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/rake-12.1.0/lib/rake/application.rb:153:in `invoke_task'
C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/rake-12.1.0/lib/rake/application.rb:109:in `block (2 levels) in top_level'
C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/rake-12.1.0/lib/rake/application.rb:109:in `each'
C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/rake-12.1.0/lib/rake/application.rb:109:in `block in top_level'
C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/rake-12.1.0/lib/rake/application.rb:118:in `run_with_threads'
C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/rake-12.1.0/lib/rake/application.rb:103:in `top_level'
C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/railties-5.1.2/lib/rails/commands/rake/rake_command.rb:21:in `block in perform'
C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/rake-12.1.0/lib/rake/application.rb:179:in `standard_exception_handling'
C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/railties-5.1.2/lib/rails/commands/rake/rake_command.rb:18:in `perform'
C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/railties-5.1.2/lib/rails/command.rb:46:in `invoke'
C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/railties-5.1.2/lib/rails/commands.rb:16:in `<top (required)>'
bin/rails:4:in `require'
bin/rails:4:in `<main>'
Tasks: TOP => db:drop:_unsafe
