### ISSUE TITLE
Rails db migration not recognising Null and Not Null for varchar 

### ISSUE THREAD

**Issue by ajays871** [rails/rails#27017]
Steps to reproduce
1) Install rails 
2) Create a new rails app
3)create a new db migrate file to create a new table 

#############create post table migration file############################

``` ruby
class CreateReports < ActiveRecord::Migration[5.0]
  def change
    create_table :reports do |t|
      #t.integer :id, :auto_increment=1, :primary_key, :null => false
      t.string :reportable_id,:null => :false
      t.string :reportable_type,:null => :true
      t.string :reason,:null => :false
      t.string :comment
      t.boolean :is_delete,:null => :false, :default => false
      t.string :user_id,:null => :false
      t.string :status, :null => :false, :default => 'initiated'
      t.string :action, :null => :false, :default => 'pending'
      t.integer :action_by, :null => :true, :default => :null
      t.boolean :is_resolve, :null => :false, :default => false
      t.timestamp :closed_at, :null => :true, :default => :null

      t.timestamps
    end
    add_index :reports, [:reportable_id, :reportable_type]
  end
end
```
################################################################################

4) run rails db:migrate from terminal in rails application root folder.

### Expected behavior

This db migrate file should generate valid sql query to create this new table

### Actual behavior
Tell us what happens instead
This generated the following create query 

```sql
CREATE TABLE `reports` (`id` int AUTO_INCREMENT PRIMARY KEY, `reportable_id` varchar(255), `reportable_type` varchar(255), `reason` varchar(255), `comment` varchar(255), `is_delete` tinyint(1) DEFAULT 0, `user_id` varchar(255), `status` varchar(255) DEFAULT 'initiated', `action` varchar(255) DEFAULT 'pending', `action_by` int DEFAULT NULL, `is_resolve` tinyint(1) DEFAULT 0, `closed_at` datetime DEFAULT 'null', `created_at` datetime NOT NULL, `updated_at` datetime NOT NULL)

```
Issues - 

1) It neglected null and not null for varchar values reportable_id and reportable_type

2) It generates different format of null values for closed_at and action_by one of them being illegal.

### System configuration
**Rails version**:  5.0.0

**Ruby version**:2.3.1p112 

Database used - Mysql

**Comment by prathamesh-sonpatki** [comment]
@ajays871 You are using `:true` and `:false` instead of `true` and `false` for specifying `null` constraints. This is not an issue with Rails. Thanks.

**Comment by ajays871** [comment]
thanks, i will fix my code.
