### ISSUE TITLE
Rails 5: How to avoid deadlock with threads and autoload?

### ISSUE THREAD

**Issue by skarger** [rails/rails#27025]
I am seeing a deadlocking issue that appears to be related to threads and autoloading.

It sounds very similar to what @matthewd and @jrochkind discussed in a few issues including these two:
* https://github.com/rails/rails/issues/24028
* https://github.com/rails/rails/issues/26847

The basic question is: What is the best practice to avoid autoload-induced deadlocks when creating threads in application code?

There are already hints of an answer in https://github.com/rails/rails/issues/24028 but I don't fully understand it.

### Demonstrating the problem ###
I've created an [example app](https://github.com/skarger/rails-deadlock-example) that creates threads from my `ParallelMapper` class via the `Parallel.map` API provided by the [parallel gem](https://github.com/grosser/parallel). Each thread creates an instance of my `CollaboratorOne` class to perform work. In turn `CollaboratorOne` creates an instance of `CollaboratorTwo` to assist with the work.

```
class ParallelMapper
  def work_in_threads
    data = [1, 2, 3] 
    Parallel.map(data, in_threads: 3) do |item|
      ActiveRecord::Base.connection_pool.with_connection do |conn|
      # or Rails.application.reloader.wrap do
        puts "ParallelMapper instance: work_in_threads: #{item}"
        collaborator_one = CollaboratorOne.new(item)
        collaborator_one.perform
      end
    end
  end
end
```

I have `config.eager_load = false` in config/environments/test.rb|development.rb.
Therefore the instantiations of `CollaboratorOne` and `CollaboratorTwo` provoke autoloading.

The app has an "/examples" endpoint. `ExamplesController` creates a `ParallelMapper` instance and calls its `work_in_threads` method to kick off the work described above. It deadlocks while processing the request.

In addition I have an Rspec request spec that makes an HTTP request to my "/examples" endpoint. The test throws an error "No live threads left. Deadlock?"

```
require "rails_helper"

describe "request where the controller creates threads", threads: true do
  it "does what we expect" do
    get examples_url
    expect(response.code).to eq("200")
  end
end
```

### Existing solutions ### 
1. If I explicitly require the collaborator classes the problem goes away, presumably because autoloading does not occur. That solution seems risky because someone could add a new class downstream that prompted an autoload and brought back the deadlock. What's more the [rails guide about autoloading](http://guides.rubyonrails.org/autoloading_and_reloading_constants.html#autoloading-and-require) advises against that:

> Just follow the flow and use constant autoloading always, never mix autoloading and require.

2. Setting `config.eager_load = true` in test/development would also avoid the problem although I'd prefer not to do that for speed if there's a solution that can work with autoload.

### Steps to reproduce

1. Clone https://github.com/skarger/rails-deadlock-example
2. `bundle exec rails db:setup` (requires postgres)
3. `bundle exec rails server`
4. Visit http://localhost:3000/examples in a browser. Deadlock should occur.

### Expected behavior
The deadlock appears to be expected given changes in Rails 5, but the goal is to avoid deadlocking. Just looking for clarification on the correct approach.

### System configuration
**Rails version**: 5.0.0.1

**Ruby version**: 2.3.1

**Comment by matthewd** [comment]
```ruby
class ParallelMapper
  def work_in_threads
    data = [1, 2, 3] 
    ActiveSupport::Dependencies.interlock.permit_concurrent_loads do
      Parallel.map(data, in_threads: 3) do |item|
        Rails.application.executor.wrap do
          puts "ParallelMapper instance: work_in_threads: #{item}"
          collaborator_one = CollaboratorOne.new(item)
          collaborator_one.perform
        end
      end
    end
  end
end
```

(Note it's important `data` is pre-calculated there, outside the `permit_concurrent_loads` block: the main thread cannot do anything inside that block which might risk interacting with autoloading.)

**Comment by skarger** [comment]
Thanks @matthewd, that works.
