### ISSUE TITLE
Return response instead of status code in integration tests

### ISSUE THREAD

**Issue by printercu** [rails/rails#27039]
Hi!

HDYT about changing return value of `process` method in integration tests? So spec files will get more clear (here are rspec examples, hope similar will be for minitest):

```ruby
# now
subject { get(some_path) && response }
it { should be_ok }
it { should redirect_to }

# after change
subject { get(some_path) }
# same assertions
``` 

I understand that it is not backward-compatible, but it would discourage using magic numbers too:

```ruby
# now
expect(get('/')).to eq 200

# after
expect(get('/')).to be_ok
```

I tried to investigate why rails provides such behaviour. I followed up till some [commit](https://github.com/rails/rails/blame/33030ea7cbfa026b0f9f95a2c5d2dd363a7fe6aa/actionpack/lib/action_dispatch/testing/integration.rb#L380) in 2009, where it already returns status code and gave up.

I can try to prepare PR for it if you like the idea.

**Comment by kaspth** [comment]
Won't `subject { get(some_path); response }` work for this?

Regardless, I don't think `process` should return either the status or response body.

**Comment by printercu** [comment]
@kaspth have you seen my example? Of course it works!

**Comment by kaspth** [comment]
All right, I misunderstood that part 👍

Still we don't want to change the return type.
