### ISSUE TITLE
fields_for used with collection drops data after failed validation

### ISSUE THREAD

**Issue by adas172002** [rails/rails#27031]
### Steps to reproduce

Model with several `has_many` relation has a form_for with nested `fields_for`, some of them are specified with a collection of children. More details described on [SO question](http://stackoverflow.com/q/40577263/3187415)

### Expected behavior
Upon failed validation, form should show all nested fields entered by user.

### Actual behavior
Upon failed validation, form is rendered with edit view, but nested children that have a collection specified in `fields_for` object do not show up on edit view, even if are still  present in model params hash. Only child objects that seem to be persisted are shown. 

### System configuration
**Rails version**: 4.2.7.1

**Ruby version**: 2.2.1

**Comment by prathamesh-sonpatki** [comment]
Can you upload a sample application on Github that reproduces the issue? Thanks.

**Comment by rubyrider** [comment]
Can you provide your full code? According to your post at [SO](http://stackoverflow.com/questions/40577263/only-some-of-nested-attributes-are-shown-after-validation-error), this is not clear how your build your objects! Can you please provide a gist by both of your edit and update action?

**Comment by adas172002** [comment]
Yes, sure I will, just give me some time to prepare a sample code at github. I will upload sample code, but I can't provide full code of app I am working on.

**Comment by rubyrider** [comment]
You don't need to provide the full code, just the view action to load your form and the update action!

**Comment by adas172002** [comment]
OK, lets try like this.

Controller update action (with some simplifications for clarity):
```ruby
def update
  respond_to do |format|
    if @logo.update(logo_params)
      format.html { redirect_to session[:back_logo_path], notice: 'Logo was successfully updated.' }
      format.json { head :no_content }
    else
      format.html do
        flash.now.alert = 'Logo update failed, check the data.'
        render action: 'edit'
      end
    end
  end
end
```

and view partial that is responsible for edit action:
```erb
<%= form_for @logo, :html => { :class => 'form-horizontal' } do |f| %>
  <div id="logoFormContent" class="tab-content" >
    <div class="tab-pane fade active in" id="artwork">
    </div> <!-- koniec artwork tab -->
    <div class="tab-pane fade" id="simulations">
    </div> <!-- koniec simulations tab -->
    <div class="tab-pane fade" id="process">
    </div> <!-- koniec process tab -->
    <div class="tab-pane fade" id="bom">
      <legend>legend here…</legend>
      <div class="accordion">
        <div class="form-inline">
          <%= f.fields_for :components, @logo.components.materials do |component| %>
            <%= render partial: 'component_fields', object: component, as: :component %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
and form controls follow here…
```
and models (again, simplified)

```ruby
class Logo < ActiveRecord::Base
  has_many :components, -> {includes :material}, dependent: :destroy, inverse_of: :logo
  accepts_nested_attributes_for :components, allow_destroy: true 
end

class Component < ActiveRecord::Base
  belongs_to :logo, inverse_of: :components
end
```

As you see, I am using a collection in `fields_for` to filter all `@logo.components` to a scope called `materials`. I already tested that if I keep this filter, after validation error `fields_for` drops components added during editing and not persisted to the database. If I remove the filter, rendering form after validation error keeps all components.

**Comment by rubyrider** [comment]
okey tonight after office, I will try to create a test application.  help me if I need the right direction with the sample application. Because I still don't think this is a rails side issue unless I can completely reproduce the context in my side.

**Comment by adas172002** [comment]
Sure, I will help as much as I can.

**Comment by adas172002** [comment]
https://github.com/adas172002/fields_for_app is the demo code to show the issue. Let me know if it works for you.

**Comment by juscportal** [comment]
I tried running the app you provided. I want to confirm the problem with the image I uploaded below before I try to solve it.

![screen shot 2016-11-26 at 6 35 21 pm](https://cloud.githubusercontent.com/assets/13282518/20639492/f8a5192c-b407-11e6-88ca-db3ebe0a9361.png)

**Comment by adas172002** [comment]
Hi Jus, 
That's right – I need the form to include all components after failed validation. But when fields_for is used with a collection of product components (eq. a scope), only persisted components survive ;-) validation.

**Comment by mluts** [comment]
@adas172002 your demo application is wrong

```
    <%= f.fields_for :components, @product.components.papers + @product.components.envelopes do |component| %>                          
      <%= render partial: "component_fields", locals: {component: component} %>
    <% end %>
```

`@product.components.papers` delegates "papers" to the `Component` class which results in empty result, because none of the `Component` records are persisted when the form is rendered with errors. Not persisted `components` in the `@product` are discarded.

After applying this patch to your demo repository, it works as expected

```diff
 app/views/products/_form.html.erb | 2 +-                                                                                                1 file changed, 1 insertion(+), 1 deletion(-)                                                                                          

diff --git a/app/views/products/_form.html.erb b/app/views/products/_form.html.erb
index a0b29da..5e81398 100644                                                                                                           --- a/app/views/products/_form.html.erb                                                                                                 +++ b/app/views/products/_form.html.erb
@@ -20,7 +20,7 @@
     <%= link_to_add_fields 'Add one more', f, :components, {}, 'ui orange tag label' %>
   </h4>
   <div class="ui attached segment">
-    <%= f.fields_for :components, @product.components.papers + @product.components.envelopes do |component| %>
+    <%= f.fields_for :components, @product.components do |component| %>
       <%= render partial: "component_fields", locals: {component: component} %>
     <% end %>
   </div>
```

![fields-for-error](https://cloud.githubusercontent.com/assets/15202437/21462130/13016280-c961-11e6-93d6-8d79c2923a8d.png)

**Comment by adas172002** [comment]
@mluts, I understand the explanation of what is happening. However, I think this behaviour is a bug. I would expect that using a scope in associated children will allow to keep children with validation errors, just like in case when children are not filtered by a scope. 

BTW, a solution to my issue is to use [Enumerable#select](http://ruby-doc.org/core-2.2.1/Enumerable.html#method-i-select) instead of scope like `@product.components.papers`

**Comment by mluts** [comment]
@adas172002 in this case it is impossible to know to how exactly get components which belong to `papers` from the `components` array of not persisted records. Roughly, `papers` lambda defined in `Component` does some SQL, but you can't do select `components` from ruby array using SQL, right?
