### ISSUE TITLE
MariaDB: migration not reverted on failure

### ISSUE THREAD

**Issue by ayghor** [rails/rails#27049]
### Steps to reproduce

have this schema on a mariadb-backed app:

```
  create_table "commissions", force: :cascade do |t|
    t.string   "policy_number"
    t.integer  "installment"
    t.datetime "created_at",                              null: false
    t.datetime "updated_at",                              null: false
    t.integer  "producer_id"
    t.decimal  "producer_value", precision: 10, scale: 2
    t.date     "producer_date"
    t.integer  "insurer_id"
    t.decimal  "insurer_value",  precision: 10, scale: 2
    t.date     "insurer_date"
    t.index ["insurer_id"], name: "index_commissions_on_insurer_id"
    t.index ["policy_number", "installment"], name: "index_commissions_on_policy_number_and_installment", unique: true
    t.index ["producer_id"], name: "index_commissions_on_producer_id"
  end
```

run this buggy migration:

```
class RemoveInstallmentAndAddInstallmentDateToCommissions < ActiveRecord::Migration[5.0]
  def change
    change_table :commissions do |t|
      t.remove_index [:policy_number, :installment]
      t.remove :installment, :integer
      # FIXME: i know
      t.column :installment_date, :date, null: false, default: Date.today
    end
  end
end
```

fix it by removing `:integer` from `t.remove`:

```
class RemoveInstallmentAndAddInstallmentDateToCommissions < ActiveRecord::Migration[5.0]
  def change
    change_table :commissions do |t|
      t.remove_index [:policy_number, :installment]
      t.remove :installment
      # FIXME: i know
      t.column :installment_date, :date, null: false, default: Date.today
    end
  end
end
```

rerun.

### Expected behavior
it should work

### Actual behavior
it works on dev sqlite and fails on production mariadb.

on mariadb, teh second run will fail with:

```
...
No indexes found on commissions with the options provided.
 DEBUG [27506818] 	/var/www/star-corretora/shared/bundle/ruby/2.3.0/gems/activerecord-5.0.0.1/lib/active_record/connection_adapters/abstract/schema_statements.rb:1221:in `index_name_for_remove'
/var/www/star-corretora/shared/bundle/ruby/2.3.0/gems/activerecord-5.0.0.1/lib/active_record/connection_adapters/abstract/schema_statements.rb:740:in `remove_index'
/var/www/star-corretora/shared/bundle/ruby/2.3.0/gems/activerecord-5.0.0.1/lib/active_record/connection_adapters/abstract/schema_definitions.rb:567:in `remove_index'
/var/www/star-corretora/releases/20161115010846/db/migrate/20161112175759_remove_installment_and_add_installment_date_to_commissions.rb:4:in `block in change'
...
```

because teh first removed teh index and did not rollback on failure.

### System configuration
**Rails version**: `Rails 5.0.0.1`

**Ruby version**: `ruby 2.3.1p112 (2016-04-26) [x86_64-linux-gnu]`

**MariaDB version**: `Server version: 10.0.27-MariaDB-0ubuntu0.16.04.1 Ubuntu 16.04`

**Comment by ayghor** [comment]
this happened because teh first tiem i ran this migration, it had an error **and got partially executed**, removing teh index before failing and leaving my db in a corrupt state.

this shouldn't happen, right?

**Comment by utilum** [comment]
@ayghor : Now that you've figured out how it went wrong, will you restate the issue? Is it that part of a migration was executed before failing and you could not rollback ?

**Comment by ayghor** [comment]
@utilum is it ok now?

**Comment by utilum** [comment]
@ayghor the title is clearer, will you now provide a code example of the actual issue?

**Comment by ayghor** [comment]
@utilum and now? =o3

**Comment by utilum** [comment]
Thank you, @ayghor . I think it's clear now. I'm not sure if this isn't expected behavior...
I'm still looking at the details, but if indeed SQLite3 and MariaDB behave differently you'd have an example why people always recommend to run the same database for development as you do in production.

**Comment by utilum** [comment]
@ayghor: I think this is expected behavior, when a migration crashes it does not undo changes made before the crash. When this happens in an isolated environment, like test, you can safely run `db:reset`, correct your code, and run again.

**Comment by ayghor** [comment]
if you run teh first migration on sqlite, it will pass even though `:integer` column does not exist.

and from teh rails guide, it seems that teh behaviour can be expected too:

> On databases that support transactions with statements that change the schema, migrations are wrapped in a transaction. If the database does not support this then when a migration fails the parts of it that succeeded will not be rolled back. You will have to rollback the changes that were made by hand.

sorry =o(! guess teh pr can be closed now

> people always recommend to run the same database for development as you do in production.

i laugh at teh face of danger =op

**Comment by ayghor** [comment]
btw i was smart enough to run on staging before! =O3

thank you! <3
