### ISSUE TITLE
Rails scaffold erb templates not being used during generation

### ISSUE THREAD

**Issue by asuraphel** [rails/rails#27041]
### Steps to reproduce

Put scaffold erb templates inside ` lib/templates/erb/scaffold.` and run `rails g scaffold xyz x:string`

### Expected behavior
The newly generated scaffold should have the custom templates in the aforementioned path.

### Actual behavior

The templates are ignored 

### System configuration
**Rails version**:
5.001
**Ruby version**:
2.3.1p112

### Related SO Question 

http://stackoverflow.com/questions/39939707/rails-scaffold-erb-templates-not-being-used-during-generation

**Comment by utilum** [comment]
Are you sure that `lib/templates/erb/scaffold` is the correct place to place them?
[The generators guid](http://guides.rubyonrails.org/generators.html) [suggests](http://guides.rubyonrails.org/generators.html#generators-lookup) `lib/generators/`...
