### ISSUE TITLE
JRuby: broken ActiveSupport::Testing::Isolation

### ISSUE THREAD

**Issue by kirs** [rails/rails#27050]
Running `railties/test/initializable_test.rb`:

```ruby
/home/travis/.rvm/rubies/jruby-9.1.5.0/bin/jruby -w -Itest:lib:/home/travis/build/kirs/rails-1/railties/../activesupport/lib:/home/travis/build/kirs/rails-1/railties/../actionpack/lib:/home/travis/build/kirs/rails-1/railties/../activemodel/lib test/initializable_test.rb
# Running:
.......sh: 1: Syntax error: Unterminated quoted string
ArgumentError: marshal data too short
                 load at org/jruby/RubyMarshal.java:147
                  run at /home/travis/build/kirs/rails-1/activesupport/lib/active_support/testing/isolation.rb:21
       run_one_method at /home/travis/build/kirs/rails-1/vendor/bundle/jruby/2.3.0/gems/minitest-5.3.3/lib/minitest.rb:759
  block in initialize at /home/travis/build/kirs/rails-1/vendor/bundle/jruby/2.3.0/gems/minitest-5.3.3/lib/minitest/parallel.rb:14
rake aborted!
```

`Marshal.load` gets an empty string from here: https://github.com/rails/rails/blob/master/activesupport/lib/active_support/testing/isolation.rb#L17

Looks like there's something wrong with `Subprocess.run_in_isolation` method ( https://github.com/rails/rails/blob/master/activesupport/lib/active_support/testing/isolation.rb#L63)

cc @guilleiguaran @headius

**Comment by headius** [comment]
Certainly could be something wrong in JRuby too...keep us posted if you can reduce it down to a behavioral difference with MRI!

**Comment by kirs** [comment]
Should be fixed in https://github.com/rails/rails/pull/27056.
I'm excited that JRuby helps us to find bugs in Rails that MRI couldn't discover.
