### ISSUE TITLE
JS Syntax highlighting inserts non-breaking spaces into the documentation

### ISSUE THREAD

**Issue by martinvonwittich** [rails/rails#27055]
I copied the `secrets.yml` example from http://guides.rubyonrails.org/upgrading_ruby_on_rails.html#config-secrets-yml into a vim instance on my Redmine server while I was trying to upgrade to the most recent Redmine version, but Redmine couldn't read it. After a while I figured out that the leading spaces in the sample were UTF-8 non-breaking spaces (0xC2 0xA0):

<pre>
martin@dogmeat ~ % cat secrets.yml | xxd
00000000: 6465 7665 6c6f 706d 656e 743a 0ac2 a0c2  development:....
00000010: a073 6563 7265 745f 6b65 795f 6261 7365  .secret_key_base
00000020: 3a0a c2a0 0a74 6573 743a 0ac2 a0c2 a073  :....test:.....s
00000030: 6563 7265 745f 6b65 795f 6261 7365 3a0a  ecret_key_base:.
00000040: c2a0 0a70 726f 6475 6374 696f 6e3a 0ac2  ...production:..
00000050: a0c2 a073 6563 7265 745f 6b65 795f 6261  ...secret_key_ba
00000060: 7365 3a20 3c25 3d20 454e 565b 2253 4543  se: <%= ENV["SEC
00000070: 5245 545f 4b45 595f 4241 5345 225d 2025  RET_KEY_BASE"] %
00000080: 3e0a                                     >.
</pre>

I tried to track the issue down and I think that the JS syntax highlighting library used on the site causes this: syntaxhighlighter/syntaxhighlighter#31

Only Chrome/Chromium seem to be affected, it works fine in Firefox.

**Comment by maclover7** [comment]
Hmm, looks like there was a PR attached to that issue, and was merged in 2012, but it seems like the bug has resurfaced. Maybe comment on that issue saying the bug still exists? 😬 

cc @fxn

**Comment by vipulnsward** [comment]
This has been fixed on master, try copying content from- http://edgeguides.rubyonrails.org/upgrading_ruby_on_rails.html#config-secrets-yml
