### ISSUE TITLE
sequence_name=(value) does work on Rails 5.0 / PgSQL 9.4.8

### ISSUE THREAD

**Issue by fchampreux** [rails/rails#27053]
###Steps
I defined a table to store Business Rules objects.
The migration generated a sequence for Business Rules, used as default for the id column: 

**business_rules_id_seq**

But I need an application-wide sequence for all objects. So in each model, I require this sequence, **objects_seq**, to handle objects ids:

    class BusinessRule < ActiveRecord::Base
    
    ### id generation
      self.sequence_name = "objects_seq"

### behaviour
Despite the **self.sequence_name** directive, ActiveRecord still uses the conventional sequence **business_rules_id_seq**. 
Deleting the former sequence does not change a thing, ActiveRecord then raises an error because id should not be null.

Can you help ?

**Comment by maclover7** [comment]
Based on your code example above, can you create an executable test script using one of the templates [here](https://github.com/rails/rails/tree/master/guides/bug_report_templates), that would demonstrate the problem you are seeing? Also, did this work for you on Rails 4.2.x?

**Comment by fchampreux** [comment]
Attached is the test I did.
The `objects_seq` is initialized with 100, but it is not used here either.
Id column of created Posts table refer to `nextval('posts_id_seq'::regclass)` as COLUMN_DEF constraint.
I am quite sure it did work with Rails 4.2, but I could not reproduce the test.

[testing.zip](https://github.com/rails/rails/files/602240/testing.zip)
