### ISSUE TITLE
listen 3.1 for Rails 5.x

### ISSUE THREAD

**Issue by junaruga** [rails/rails#27067]
Hi,

Just question.

Is it possible to merge below commit on master branch to Rails 5.x?
Because I could not find it on 5-0-stable branch, and I want to use `listen` latest version 3.1.5 with default Gemfile.

https://github.com/rails/rails/commit/ddddedc487912e33edb7d78aec6bcf99b1312c6d

Thanks.

**Comment by jeremy** [comment]
Hi @junaruga! Please continue discussion on #26709, the 5-0-stable backport PR for the master PR.

**Comment by junaruga** [comment]
@jeremy ok!
