### ISSUE TITLE
Memcached read_multi always looks up key of "raw => true" when using Dalli

### ISSUE THREAD

**Issue by jonhyman** [rails/rails#27066]
### Steps to reproduce

The definition of `get_multi` in Dalli at https://github.com/petergoldstein/dalli/blob/master/lib/dalli/client.rb#L65 is:

```ruby
def get_multi(*keys)
```

the implementation of `read_multi` in `ActiveSupport::MemCacheStore` at https://github.com/rails/rails/blob/master/activesupport/lib/active_support/cache/mem_cache_store.rb#L100 is:

```ruby
raw_values = @data.get_multi(keys_to_names.keys, raw: true)
```

what's happening is that every call to `read_multi` is also adding a key called `"{:raw=>true}"`. We discovered this because this issue has been causing an incredible cache miss rate for us on one of our memcached servers. We run with 9 memcached servers and 8 of the 9 get about 1.5k misses per second. The server that `"{:raw => true}"` is supposed to reside on is getting about 40k misses per second and the incoming packets per second is now starting to overload the box.

I think the `raw: true` should be removed, unless other drives require it, in which case it should only be removed for Dalli.

### System configuration
**Rails version**:
4.2.7.1

**Ruby version**:
2.2.3p173

**Comment by maclover7** [comment]
@jonhyman Can you open up a PR, and then we can continue the discussion there?

**Comment by jonhyman** [comment]
@maclover7 https://github.com/rails/rails/pull/27070

**Comment by jonhyman** [comment]
We forked Dalli to ignore this `"{:raw=>true}"` key (https://github.com/Appboy/dalli/pull/1) and are gradually pushing it out everywhere. You can see the impact of this bad key as the cause of the issue.

![image](https://cloud.githubusercontent.com/assets/832655/20366424/13fc0952-ac19-11e6-8c3b-1b22ecd13430.png)

![image](https://cloud.githubusercontent.com/assets/832655/20366432/1950c582-ac19-11e6-8574-462e3badeb79.png)
