### ISSUE TITLE
The symbol "£" is not accepting the rails 4.2.0 and ruby 2.2.0

### ISSUE THREAD

**Issue by sonu1989** [rails/rails#27065]
I have requirement in which I am getting array as parameter like below -
```
arr = ["£12.50", "£1", "£5.00"]
```
I want to delete this "£" symbol from each array element
I am using this code to remove this symbol
```
arr.map! { |amount| amount.delete('£,').to_d }
```
but when I am trying to perform this operation I am getting error (see in Backtrace)

Guys, Please let me know how this issue can be resolved.

### Backtrace

/.rvm/gems/ruby-2.2.0@rtm-new/gems/pry-0.10.3/lib/pry/history.rb:106:in `write': "\xC2" from ASCII-8BIT to UTF-8 (Encoding::UndefinedConversionError)
	from /home/sonus/.rvm/gems/ruby-2.2.0@rtm-new/gems/pry-0.10.3/lib/pry/history.rb:106:in `puts'
	from /home/sonus/.rvm/gems/ruby-2.2.0@rtm-new/gems/pry-0.10.3/lib/pry/history.rb:106:in `save_to_file'
	from /home/sonus/.rvm/gems/ruby-2.2.0@rtm-new/gems/pry-0.10.3/lib/pry/history.rb:50:in `call'
	from /home/sonus/.rvm/gems/ruby-2.2.0@rtm-new/gems/pry-0.10.3/lib/pry/history.rb:50:in `push'
	from /home/sonus/.rvm/gems/ruby-2.2.0@rtm-new/gems/pry-0.10.3/lib/pry/pry_instance.rb:267:in `handle_line'
	from /home/sonus/.rvm/gems/ruby-2.2.0@rtm-new/gems/pry-0.10.3/lib/pry/pry_instance.rb:243:in `block (2 levels) in eval'
	from /home/sonus/.rvm/gems/ruby-2.2.0@rtm-new/gems/pry-0.10.3/lib/pry/pry_instance.rb:242:in `catch'
	from /home/sonus/.rvm/gems/ruby-2.2.0@rtm-new/gems/pry-0.10.3/lib/pry/pry_instance.rb:242:in `block in eval'
	from /home/sonus/.rvm/gems/ruby-2.2.0@rtm-new/gems/pry-0.10.3/lib/pry/pry_instance.rb:241:in `catch'
	from /home/sonus/.rvm/gems/ruby-2.2.0@rtm-new/gems/pry-0.10.3/lib/pry/pry_instance.rb:241:in `eval'
	from /home/sonus/.rvm/gems/ruby-2.2.0@rtm-new/gems/pry-0.10.3/lib/pry/repl.rb:77:in `block in repl'
	from /home/sonus/.rvm/gems/ruby-2.2.0@rtm-new/gems/pry-0.10.3/lib/pry/repl.rb:67:in `loop'
	from /home/sonus/.rvm/gems/ruby-2.2.0@rtm-new/gems/pry-0.10.3/lib/pry/repl.rb:67:in `repl'
	from /home/sonus/.rvm/gems/ruby-2.2.0@rtm-new/gems/pry-0.10.3/lib/pry/repl.rb:38:in `block in start'
	from /home/sonus/.rvm/gems/ruby-2.2.0@rtm-new/gems/pry-0.10.3/lib/pry/input_lock.rb:61:in `call'
	from /home/sonus/.rvm/gems/ruby-2.2.0@rtm-new/gems/pry-0.10.3/lib/pry/input_lock.rb:61:in `__with_ownership'
	from /home/sonus/.rvm/gems/ruby-2.2.0@rtm-new/gems/pry-0.10.3/lib/pry/input_lock.rb:79:in `with_ownership'
	from /home/sonus/.rvm/gems/ruby-2.2.0@rtm-new/gems/pry-0.10.3/lib/pry/repl.rb:38:in `start'
	from /home/sonus/.rvm/gems/ruby-2.2.0@rtm-new/gems/pry-0.10.3/lib/pry/repl.rb:15:in `start'
	from /home/sonus/.rvm/gems/ruby-2.2.0@rtm-new/gems/pry-0.10.3/lib/pry/pry_class.rb:169:in `start'
	from /home/sonus/.rvm/gems/ruby-2.2.0@rtm-new/gems/railties-4.2.5.1/lib/rails/commands/console.rb:110:in `start'
	from /home/sonus/.rvm/gems/ruby-2.2.0@rtm-new/gems/railties-4.2.5.1/lib/rails/commands/console.rb:9:in `start'
	from /home/sonus/.rvm/gems/ruby-2.2.0@rtm-new/gems/railties-4.2.5.1/lib/rails/commands/commands_tasks.rb:68:in `console'
	from /home/sonus/.rvm/gems/ruby-2.2.0@rtm-new/gems/railties-4.2.5.1/lib/rails/commands/commands_tasks.rb:39:in `run_command!'
	from /home/sonus/.rvm/gems/ruby-2.2.0@rtm-new/gems/railties-4.2.5.1/lib/rails/commands.rb:17:in `<top (required)>'
	from /home/sonus/.rvm/gems/ruby-2.2.0@rtm-new/gems/activesupport-4.2.5.1/lib/active_support/dependencies.rb:274:in `require'
	from /home/sonus/.rvm/gems/ruby-2.2.0@rtm-new/gems/activesupport-4.2.5.1/lib/active_support/dependencies.rb:274:in `block in require'
	from /home/sonus/.rvm/gems/ruby-2.2.0@rtm-new/gems/activesupport-4.2.5.1/lib/active_support/dependencies.rb:240:in `load_dependency'
	from /home/sonus/.rvm/gems/ruby-2.2.0@rtm-new/gems/activesupport-4.2.5.1/lib/active_support/dependencies.rb:274:in `require'
	from /home/sonus/raisethemoney/bin/rails:8:in `<top (required)>'
	from /home/sonus/.rvm/gems/ruby-2.2.0@rtm-new/gems/activesupport-4.2.5.1/lib/active_support/dependencies.rb:268:in `load'
	from /home/sonus/.rvm/gems/ruby-2.2.0@rtm-new/gems/activesupport-4.2.5.1/lib/active_support/dependencies.rb:268:in `block in load'
	from /home/sonus/.rvm/gems/ruby-2.2.0@rtm-new/gems/activesupport-4.2.5.1/lib/active_support/dependencies.rb:240:in `load_dependency'
	from /home/sonus/.rvm/gems/ruby-2.2.0@rtm-new/gems/activesupport-4.2.5.1/lib/active_support/dependencies.rb:268:in `load'
	from /home/sonus/.rvm/rubies/ruby-2.2.0/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /home/sonus/.rvm/rubies/ruby-2.2.0/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from -e:1:in `<main>'

### System configuration
**Rails version**: 4.2.0

**Ruby version**: 2.2.0

**Comment by Jesus** [comment]
Hi @sonu1989, this seems to be an encoding issue. Not related to Rails and not a bug.

Afaik, Github issues is just used as a bug tracker and you won't get support here. Maybe you would get more help if you post your question on http://stackoverflow.com

**Comment by sonu1989** [comment]
Hi Jesus,
Thanks for quick response.
I tried with other version of rails and ruby in my system it's working fine for me
rails: 3.2.18 
ruby 2.0.0-p481

So I think this is not related encoding issue.
Please let us know your thought on this.

**Comment by utilum** [comment]
The error *does* seem unrelated to Rails.

It runs smoothly for me both on 4.2.0 and on master.

```Loading development environment (Rails 4.2.0)
irb(main):001:0> arr = ["£12.50", "£1", "£5.00"]
=> ["£12.50", "£1", "£5.00"]
irb(main):002:0> arr.map! { |amount| amount.delete('£,').to_d }
=> [#<BigDecimal:559bdf5e4bf8,'0.125E2',18(18)>, #<BigDecimal:559bdf5e4ab8,'0.1E1',9(18)>, #<BigDecimal:559bdf5e49f0,'0.5E1',9(18)>]```

```Loading development environment (Rails 5.1.0.alpha)
irb(main):001:0> arr = ["£12.50", "£1", "£5.00"]
=> ["£12.50", "£1", "£5.00"]
irb(main):002:0> arr.map! { |amount| amount.delete('£,').to_d }
=> [#<BigDecimal:55abce5e2a98,'0.125E2',18(18)>, #<BigDecimal:55abce5e2868,'0.1E1',9(18)>, #<BigDecimal:55abce5e2570,'0.5E1',9(18)>]```

**Comment by sonu1989** [comment]
Thank you utilum.
I will test again at my side.
