### ISSUE TITLE
Custom Configuration example in Guides not working

### ISSUE THREAD

**Issue by djunzu** [rails/rails#27068]
Docs currently shows this example in [Custom Configuration](http://guides.rubyonrails.org/v5.0.0.1/configuring.html#custom-configuration) 
```ruby
config.payment_processing.schedule = :daily
config.payment_processing.retries  = 3
config.super_debugger = true
```
which raises a `NoMethodError`:
```
[...]/railties-5.0.0.1/lib/rails/railtie/configuration.rb:95: in `method_missing':
undefined method `payment_processing' for #<Rails::Application::Configuration:0x0055da316c5078> (NoMethodError)
```

(`config.super_debugger = true` alone works fine.)

It came from #21995, updating from rails 4. The previous example from rails 4 still runs smoothly:
```ruby
config.x.payment_processing.schedule = :daily
config.x.payment_processing.retries  = 3
config.x.super_debugger = true
```

Is it supposed the user should add something like
```ruby
config.payment_processing = ActiveSupport::OrderedOptions.new 
```
(and so docs should be updated) or is it a bug and rails should process `config.payment_processing.schedule` out the box in the same way it does with `config.x.payment_processing.schedule`?

---

Following the example, `Rails.configuration.super_debugger.not_set` or `Rails.configuration.x.super_debugger.not_set` will both raise
```
NoMethodError: undefined method `not_set' for true:TrueClass
```
Should it returns `nil` like docs say or is it just a wrong example?

---

### System configuration
```bash
$ rails -v
Rails 5.0.0.1
$ ruby -v
ruby 2.3.1p112 (2016-04-26 revision 54768) [x86_64-linux]
```

**Comment by kaspth** [comment]
The docs should add the x namespace. PR welcome!
