### ISSUE TITLE
Rails.configuration.i18n.available_locales is not applicable?

### ISSUE THREAD

**Issue by nambrot** [rails/rails#27083]
### Steps to reproduce

Looking at `Rails.configuration.i18n.available_locales` and `I18n.available_locales`, it seems like the former one isn't actually used, yet is referenced in the guides in this repo on https://github.com/rails/rails/blob/1f63d09ad78b6dada597e97359dce507c1169081/guides/source/configuring.md#L281

Should this be removed from that file?

**Comment by rafaelfranca** [comment]
Could you expand why do you think the former is not being used? It is.

**Comment by nambrot** [comment]
Sorry for my premature comment in that case. I did a search through the repo and couldn't find any references, but should have been more thorough. The case we were running into is that setting `Rails.configuration.i18n.available_locales` did not propagate to `I18n.available_locales` which we just assumed incorrectly, since we do some internationalization outside the core functionality
