### ISSUE TITLE
Make `rails test` run `rake test`

### ISSUE THREAD

**Issue by scottgonzalez** [rails/rails#27088]
### Steps to reproduce

Modify the `test` rake task and then run `rails test`.

### Expected behavior

I expect that `rails test` will just run `rake test`.

### Actual behavior

`rails test` only executes `Minitest.run`.

### System configuration
**Rails version**: 5.0.0.1

**Ruby version**: 2.3.1-p112 (x86_64-darwin16)

----

Since the `test` task is already set up to run minitest, is there a reason that the `test` command is included in `Rails::CommandsTasks::COMMAND_WHITELIST`? I can send a PR to remove this from the whitelist if that's acceptable. This caused me to waste a lot of time trying to figure out why modifications to the `test` task didn't affect `rails test`.

**Comment by rafaelfranca** [comment]
`rails test` is different from `rake test` by design. We want to move away from `rake`. `rails test` will not run `rake test`, so we need to think in another way to fix this issue. Why do you need to modify the test task?

**Comment by rafaelfranca** [comment]
cc @kaspth since you have more context on this

**Comment by scottgonzalez** [comment]
> rails test is different from rake test by design. We want to move away from rake. rails test will not run rake test, so we need to think in another way to fix this issue.

Is there a document or blog post explaining why rails is moving away from rake? Everything not in the whitelist is a direct pass through to rake, so I don't really understand this.

> Why do you need to modify the test task?

Because developers expect to run `rails test` to run all tests, and we need to inject additional tests into the test task. Specifically, we're adding a rubocop task as a dependency of the test task.

**Comment by rafaelfranca** [comment]
https://github.com/rails/rails/issues/18878.

> Because developers expect to run rails test to run all tests, and we need to inject additional tests into the test task. Specifically, we're adding a rubocop task as a dependency of the test task.

In Rails 5 this is not true anymore `rails test` does run all the tests but it doesn't run `rake tasks`.

All this information is present in the release notes and changelogs. Example:

http://guides.rubyonrails.org/5_0_release_notes.html#test-runner.

Right now it is not possible to extend the rails commands, so you are not able to add dependencies to the `rails test` command, but we are working on this for Rails 5. https://github.com/rails/rails/pull/26414.

**Comment by rafaelfranca** [comment]
> Everything not in the whitelist is a direct pass through to rake, so I don't really understand this.

This is also going to change in Rails 5.1. We are not going to pass things to rake anymore.

**Comment by kaspth** [comment]
> but we are working on this for Rails 5

We're currently targeting 5.1 for that, yeah. But don't think we need to keep this issue open for that work. Thanks!
