### ISSUE TITLE
option_groups_from_collection_for_select fails with Proc as group_label_method

### ISSUE THREAD

**Issue by soyellupi** [rails/rails#27080]
### Steps to reproduce
`rails c
 ActionView::Base.new.option_groups_from_collection_for_select(collection, :children, lambda{|parent| "#{parent.id} #{parent.name}"}, :id, :name)`

### Expected behavior
It should returns a select with grouped options

### Actual behavior
#<Proc:0x007f91c3622fd0 (lambda)> is not a symbol nor a string

### System configuration
**Rails version**:
4.2.7.1
**Ruby version**:
2.3.1

**Comment by utilum** [comment]
@soyellupi The [api](http://api.rubyonrails.org/v4.2.7/classes/ActionView/Helpers/FormOptionsHelper.html#method-i-option_groups_from_collection_for_select) suggests that the third argument be a method name. Why do you expect the Proc to work?

**Comment by soyellupi** [comment]
@utilum it is working with `options_from_collection_for_select`, so I assumed that it could work in the same way.

**Comment by utilum** [comment]
So issue resolved?

**Comment by soyellupi** [comment]
Not really, why `option_groups_from_collection_for_select` could not accepts a proc as value_method as `options_from_collection_for_select `?

**Comment by rafaelfranca** [comment]
> Not really, why option_groups_from_collection_for_select could not accepts a proc as value_method as options_from_collection_for_select?

There is no reason. Feel free to open a PR, but we don't take feature requests in the issue tracker. Thank you.
