### ISSUE TITLE
accepts_nested_attributes_for : belongs_to relation requires "optional: true" for validations to pass

### ISSUE THREAD

**Issue by john-999** [rails/rails#27081]
Scenario:
- User can have many Roles
- 3 Models: User -< Userrole >- Role
- User+Userrole are created using the "nested models" approach
- Validation fails with: "Userroles user must exist"

Models:

    class User < ApplicationRecord
	    has_many :userroles
	    accepts_nested_attributes_for :userroles
    end

    class Userrole < ApplicationRecord
	    belongs_to :user, optional: true  # <--- This seems to be required and disables the foreign_key check
	    belongs_to :role
    end

    class Role < ApplicationRecord
	    has_many :userroles
    end

The failed validation seems to be the result of Rails 5's enforced foreign_key presence validation.

It seems that all the validations (both parent and child) are occurring before either entity is actually being persisted to the DB. One might expect in such a scenario that Rails would validate the parent, persist the parent, validate the child, persist the child.

Userroles thus requires "optional: true" and disables the foreign_key check.

If this is not a bug, this behavior must be explained in the Rails documentation (http://api.rubyonrails.org/ and Rails Guides).

**Comment by maclover7** [comment]
Can you create an executable test script using one of the templates [here](https://github.com/rails/rails/tree/master/guides/bug_report_templates), that would demonstrate the problem you are seeing?

**Comment by john-999** [comment]
I just did. The issue had originally popped up in the context of the creation of Devise users. But the issue vanishes when I now run a basic test script which does not use/include Devise. So it's an issue with Devise, not Rails.
