### ISSUE TITLE
after_destroy is not called on has_many through

### ISSUE THREAD

**Issue by rept** [rails/rails#27099]
I have these models

```ruby
class User < ActiveRecord::Base
  has_many :user_functions, :dependent => :destroy
  has_many :functions, :through => :user_functions
  accepts_nested_attributes_for :functions, allow_destroy: true

class Function < ActiveRecord::Base
  has_many :user_functions, dependent: :destroy
  has_many :users, :through => :user_functions

class UserFunction < ActiveRecord::Base
  belongs_to :user, inverse_of: :user_functions
  belongs_to :function, inverse_of: :user_functions
  after_destroy :unplan_items
  after_create :plan_items
```

and of course the model of function but this is like user...

Now when I do the following in my tests:

```ruby
@user.functions = @functions  #here the after_create callback works perfectly
@user.save
@user.functions = []
@user.save #here the after_destroy callback is never called
```

Since after_create is always called but after_destroy isn't, this should be considered an inconsistency bug.

The docs mention advice to use has_mny :through if you need callbacks:
See the suggestion here: http://guides.rubyonrails.org/association_basics.html

> You should use has_many :through if you need validations, callbacks, or extra attributes on the join model.

After searching for a long time I found this issue submitted by @heaven: https://github.com/rails/rails/issues/7618  this describes perfectly the issue at hand but is closed (since Rails 3.2 isn't supported anymore).  However I'm experiencing this issue in Rails 4.2.5 so it's very current.

@nanaya wrote a test case for this: https://github.com/edogawaconan/rails-hmt-after_destroy which fails in Rails >4.0 ...

Also mentioned this on StackOverflow: http://stackoverflow.com/questions/40681340/after-destroy-not-called-for-linked-table

**Comment by maclover7** [comment]
Hmm, I'm not completely sure if this is supported behavior. In order to trigger the destroy callbacks, I think you'd need to call `@user.functions.destroy_all` or similar.

cc @sgrif

**Comment by rept** [comment]
If you put 

`
has_many :functions, :through => :user_functions, :dependent => :destroy`

It will also work, however it's not consistent with the after_create call (as also mentioned in the other issue).  

@sgrif also said: "Rails 3.2 is no longer supported. Can you reproduce the issue on 4.1 or master? If so, please open a new issue."  I can reproduce in rails 4.2.5

**Comment by sgrif** [comment]
Can you reproduce on Rails 5? Do you have a script that we can use to try?

**Comment by rept** [comment]
@sgrif 
I have no idea what it gives in Rails 5.  
The original issue (#7618) has been there since 2012 and the question there was if it still happened in Rails 4.  That I can confirm and there is a test script to use ( https://github.com/edogawaconan/rails-hmt-after_destroy ).

**Comment by utilum** [comment]
The test script linked to gives an error on a different issue. I [removed the extra bit](https://gist.github.com/utilum/8bc7814985f09555f867c6b528640bd3) and it passes both on rails 4.7.2 and on master.

**Comment by maclover7** [comment]
@rept, can you confirm that @utilum is accurately trying to reproduce the circumstances in which you had an error thrown? If so, I think we can close this issue since the problem seems to have been solved.

**Comment by rept** [comment]
@maclover7 @utilum Changed the script to rails 4.2.7.1 and it passes.  Thanks!
