### ISSUE TITLE
rescue_responses differ from those in the guides

### ISSUE THREAD

**Issue by azul** [rails/rails#27128]
### Steps to reproduce

```bash
rails new blank
cd blank
bin/rails c
```
```ruby
Blank::Application.config.action_dispatch.rescue_responses
```
 
### Expected behavior
According to the [guides](http://guides.rubyonrails.org/configuring.html#configuring-action-dispatch) there should be a bunch of rescue_responses set from different railties.

### Actual behavior
Only rescue_responses from ActiveRecord are listed:
```ruby
{"ActiveRecord::RecordNotFound"=>:not_found,
 "ActiveRecord::StaleObjectError"=>:conflict,
 "ActiveRecord::RecordInvalid"=>:unprocessable_entity,
 "ActiveRecord::RecordNotSaved"=>:unprocessable_entity}
```

The more verbose list is only set for ActionDispatch::ExceptionWrapper
```ruby
pp ActionDispatch::ExceptionWrapper.rescue_responses
{"ActionController::RoutingError"=>:not_found,
 "AbstractController::ActionNotFound"=>:not_found,
 "ActionController::MethodNotAllowed"=>:method_not_allowed,
 "ActionController::UnknownHttpMethod"=>:method_not_allowed,
 "ActionController::NotImplemented"=>:not_implemented,
 "ActionController::UnknownFormat"=>:not_acceptable,
 "ActionController::InvalidAuthenticityToken"=>:unprocessable_entity,
 "ActionController::InvalidCrossOriginRequest"=>:unprocessable_entity,
 "ActionDispatch::ParamsParser::ParseError"=>:bad_request,
 "ActionController::BadRequest"=>:bad_request,
 "ActionController::ParameterMissing"=>:bad_request,
 "Rack::Utils::ParameterTypeError"=>:bad_request,
 "Rack::Utils::InvalidParameterError"=>:bad_request,
 "ActiveRecord::RecordNotFound"=>:not_found,
 "ActiveRecord::StaleObjectError"=>:conflict,
 "ActiveRecord::RecordInvalid"=>:unprocessable_entity,
 "ActiveRecord::RecordNotSaved"=>:unprocessable_entity}
```

### System configuration
**Rails version**:
* 5.0.0.1
* 4.2.7.1

**Ruby version**:
ruby 2.3.1p112 (2016-04-26) [x86_64-linux-gnu]

**Comment by azul** [comment]
My guess is this is a documentation issue and rescue_responses are only temporarily collected in the config and then added to the ExceptionWrapper. If that's the case it would be good to clearify in the docs.

**Comment by prathamesh-sonpatki** [comment]
It was added in https://github.com/rails/rails/pull/17076 cc @yuki24

**Comment by prathamesh-sonpatki** [comment]
The code uses `ActionDispatch::ExceptionWrapper.rescue_responses` and it also merges the rescue_responses configured by the user into `ActionDispatch::ExceptionWrapper.rescue_responses` so I think it is documentation issue.

@azul Can you open a PR to fix this?

**Comment by yuki24** [comment]
@azul @prathamesh-sonpatki Sorry for not getting back to you sooner. I also think this is a documentation issue.
