### ISSUE TITLE
Route scoring ignores options/defaults conflicts

### ISSUE THREAD

**Issue by veloutin** [rails/rails#27132]
### Steps to reproduce
Create routes:
```
get '/pretty-url-foo' => 'pages#show', defaults: {id: 1}
get '/pretty-url-bar' => 'pages#show', defaults: {id: 2}
```

In rails console/controller/view, call url_for
```
Rails.application.routes.url_helpers.url_for controller: 'pages', action: 'show', only_path: true, id: 2
```

(Guidelines for creating a bug report are [available
here](http://guides.rubyonrails.org/contributing_to_ruby_on_rails.html#creating-a-bug-report))

### Expected behavior

I would expect the '/pretty-url-bar' path to be returned, since it would be a better match than the first one.

### Actual behavior

The '/pretty-url-foo' is always returned, no matter the id passed.

### System configuration
**Rails version**:
4.2.7.1

**Ruby version**:
2.3.0p0

### Extra

This did not happen in Rails 3.1

It seems that all the `ActionDispatch::Journey::Route.score(options)` gives the same results to all of these, so it always takes the first declared route.

**Comment by veloutin** [comment]
For what it worth, this solves my problem:
```
module ActionDispatch
  module Journey
    class Route
      alias_method :score_original, :score

      def score(constraints)
        res = score_original(constraints)
        if res >= 0
          constraints.each do |k, v|
            unless (dv = @defaults[k]).nil?
              if dv.to_s != v.to_s
                res = -1
                break
              else
                res += 1
              end
            end
          end
        end

        res
      end
    end
  end
end
```

**Comment by utilum** [comment]
- [Executable test with master](https://gist.github.com/utilum/89a6bead2ea8a785a5935d5f1630fe2e)
- [Executable test with Rails 4.0.0](https://gist.github.com/utilum/da579d6c0cffb6be783d0b037bfe2376).

Can also reproduce @veloutin 's result with a fresh install of Rails 3.2.

**Comment by maclover7** [comment]
cc @pixeltrix

**Comment by pixeltrix** [comment]
This is likely because Journey was designed to replace Rack::Mount which behaved in a similar fashion so it's "not a bug", however it's worth considering but it would probably need to go in with a config option that defaults to false and an initialiser that sets it to true in new applications. Definitely couldn't be backported so it'd be in 5.1 at the earliest.
