### ISSUE TITLE
Unable to opt-out of path expansion using `ActionDispatch::Integration:: RequestHelpers`

### ISSUE THREAD

**Issue by FriedSock** [rails/rails#27144]
### Steps to reproduce

The exact problem is using the `as: :json` option to the request helpers defined in `ActionDispatch::Integration:: RequestHelpers`, which also seems to be the only way to correctly encode the body of your request as json. Otherwise `WWWFormEncoder` will be used.

using rspec-rails:

```
require 'rails_helper'

RSpec.describe "Authentication", :type => :request do
  params = { some: "niceparams" }
  headers = { 'HTTPS' => 'on'}
  post "/anything", params: params, headers: headers, as: :json
end
```

### Expected behavior
The path for the request should be left as "/anything" by default, or there should be an option to not expand the path. 

### Actual behavior
the path is expanded to include the format : `/anything.json`

### System configuration
**Rails version**:
5.0.0.1

**Ruby version**:
ruby 2.3.1p112 (2016-04-26 revision 54768) [x86_64-darwin14]

**Comment by kaspth** [comment]
Thinking more about this, perhaps we should just not append to the request path altogether. If we just assign the correct headers, Rails should still suss out the request format.

**Comment by kaspth** [comment]
On the other hand, I'm curious why your request can't handle `.json` being appended to it? If it is a JSON route, shouldn't it respond to it in Rails' standard way?

**Comment by FriedSock** [comment]
I hit the error when using the omniauth gem which does an exact check on the request path
https://github.com/omniauth/omniauth/blob/master/lib/omniauth/strategy.rb#L248

**Comment by FriedSock** [comment]
I'd be happy to work on this if you think that removing the format appending is the way to go. I do think it is quite strange default behaviour to be rewriting the path when it isn't needed.

**Comment by rafaelfranca** [comment]
Yeah, I think we don't need  to append the path.

**Comment by kaspth** [comment]
I'm working on a fix 👍

**Comment by kaspth** [comment]
Backported to 5-0-stable in: 27c5139
