### ISSUE TITLE
Can not set false for primary_key(ActiveRecord, Mysql)

### ISSUE THREAD

**Issue by tranthuc141** [rails/rails#27142]
### Input

migrate file:
def change
  &nbsp; &nbsp;create_table :users, id: false do |t|
    &nbsp; &nbsp;&nbsp; &nbsp; t.boolean :is_boss
  &nbsp; &nbsp;end
  &nbsp; execute "ALTER TABLE users ADD PRIMARY KEY (is_boss);"
end

model file: models/user.rb

class User < ActiveRecord::Base
 &nbsp; &nbsp;self.primary_key = "is_boss"
end

### Expected behavior
- I hope I can create an user by: User.create is_boss: false

### Actual behavior
- Rollback
- But "User.create is_boss: true" is ok

### System configuration
**Rails version**: 4.2.5.2

**Ruby version**: 2.2

**Comment by sevenseacat** [comment]
how can you have a boolean primary key??? that doesn't make sense...

**Comment by tranthuc141** [comment]
Yes, you are right. I just did it as a test. And I don't know why I can save successfully for only true value.

**Comment by niharika88** [comment]
I will be working on it .is anyone else working on it?

**Comment by kaspth** [comment]
Nobody is working on it and you shouldn't either. There's no bug to fix, because it's not a use case that needs support ❤️

Though it is funny that true works 😄
