### ISSUE TITLE
Confusing / unclear documentation for CSRF protection

### ISSUE THREAD

**Issue by gingerlime** [rails/rails#27157]
I also [asked this on StackOverflow](http://stackoverflow.com/q/40706394/305019), but I think it's worth raising an issue. At the very least to improve documentation and make it clearer.

The [documentation on Request Forgery Protection](http://edgeapi.rubyonrails.org/classes/ActionController/RequestForgeryProtection.html) is a little confusing and unclear in certain parts. Specifically the example and surrounding text on the main text:

> It's important to remember that XML or JSON requests are also affected and if you're building an API you should change forgery protection method in ApplicationController (by default: :exception):
> 
> ```ruby
> class ApplicationController < ActionController::Base
>   protect_from_forgery unless: -> { request.format.json? }
> end
> ```
> CSRF protection is turned on with the protect_from_forgery method. By default protect_from_forgery protects your session with :null_session method, which provides an empty session during request.
> 
> We may want to disable CSRF protection for APIs since they are typically designed to be state-less. That is, the request API client will handle the session for you instead of Rails.

If I read this correctly, the first sentence says that "XML / JSON requests are also affected" (i.e. susceptible to CSRF attacks?), but then recommend bypassing CSRF protection for JSON requests.

Is this a contradiction? Or perhaps "affected" is there to mean "blocked (unnecessarily?) by CSRF protection" ?

Another source of confusion for me is whether turning off CSRF protection always implies managing your own session.

Lastly, I think it's worth pointing out (and please correct me if I'm wrong) that CSRF protection [isn't necessary for XHR](https://www.owasp.org/index.php/Cross-Site_Request_Forgery_(CSRF)_Prevention_Cheat_Sheet#Protecting_REST_Services:_Use_of_Custom_Request_Headers) as long as CORS is blocked for requests from untrusted domains. The last point is one I'm hoping to get some more clarity (and hence the SO question I mentioned).

Hope it's the right place to report or discuss this, but especially when it comes to security, it's very important that threats and countermeasures are crystal clear.

**Comment by rafaelfranca** [comment]
I think this thread explain most of your doubts https://github.com/rails/rails/pull/9405. Can you work in the documentation changes recommended in that thread?

**Comment by gingerlime** [comment]
Thanks for the pointer, @rafaelfranca ! I'd be happy to suggest a change to the documentation / create a PR for this, but I'd need to clarify a couple of things first. Maybe proposing the change to documentation will naturally trigger a discussion?

I'm not sure #9405 answers my question however. Not directly anyway. If I understand things correctly, it rightly points out that you should use CSRF even with Ajax, to avoid issues with Flash. But I hope this is now outdated and browsers do a good job protecting again any bypass of CORS(?).

Not sure if I should ask those questions again on #9405, or here? or create a PR with documentation changes based on my personal perspective and continue the discussion around the suggested changes? Happy to take whatever path works best with the community. I'm not that involved on a regular basis (even though I did contribute to some security-related discussions / changes previously).

**Comment by rafaelfranca** [comment]
https://github.com/rails/rails/pull/9405#issuecomment-14070676 is what answer your question.

**Comment by gingerlime** [comment]
It kinda does, but without any supporting arguments. "Just do this because it's more secure" is nice and all, but there's some balance to strike, cost/benefit etc.

Even if we treat this comment as gospel, then documentation should be updated to reflect this. Right?

 OWASP seems to give a more nuanced / balanced advice re CSRF, and I think it's worth acknowledging or discussing...

**Comment by rafaelfranca** [comment]
Yes. Like it is stated in that thread there is an issue in the documentation. It should not be recommending to remove the protection. I don't think it should recommend removing even that with CORS it is already secure.

**Comment by gingerlime** [comment]
I wouldn't *recommend* removing it either, but to explain the trade-offs a bit better and let people make an informed decision. Right now, to me it kinda recommends doing that actually. Doesn't it?

**Comment by Schwad** [comment]
I know that there is a good thread on that PR but since it's against a PR that was closed four years ago maybe not the best place to wrap up this conversation. 

@gingerlime would you feel confident pulling a PR together on this issue with an implementation on your thoughts on what the docs should look like with what you know?

Are there any further gaps you need to know? I'm sure if you're only 80% confident in a PR that @rafaelfranca wouldn't mind giving you an honest back and forth in a review.

**Comment by gingerlime** [comment]
Sorry for the delay replying to you, @Schwad. It's been a while since this discussion took place, so I needed some time to refresh my memory about the whole thing. I'd be happy to create a PR. I think I am reasonably confident I understand things, I just hope I can explain those nuances clearly on the docs :)
