### ISSUE TITLE
History file not loaded

### ISSUE THREAD

**Issue by ctlong** [rails/rails#27161]
Whenever I enter `pry` console through `rails c` or `binding.pry` I get the error "History file not loaded: invalid byte sequence in UTF-8" and no key strokes history is given me.

Ex. If I type `Company.new`, hit enter, and hit the up arrow I expect `Company.new` to be re-entered according to the history. But nothing happens and the above error on startup of the console is all I get.

### System configuration
**Rails version**: 4.2.1

**Ruby version**: 2.2.3

**Comment by rafaelfranca** [comment]
This doesn't seems to be a Rails issue. Does this happens without pry?
