### ISSUE TITLE
I am not able to use db2 native encrypt method in ruby on rails active record

### ISSUE THREAD

**Issue by Hareramrai** [rails/rails#27168]
### Steps to reproduce
I am try to use IBM db2 encrypt method to encrypt password in db2 itself using db2 native method.
### Expected behavior
Tell us what should happen
````
user = User.new 
user.password = "encrypt('mysecurepassword')" 
user.save
````
user.password should not return "encrypt('mysecurepassword')". 

I am not able to encrypt the password.Is there any ways to use encrypt method of db2 ?
### System configuration
**Rails version**: 4.2

**Ruby version**:2.3

**Comment by kaspth** [comment]
Please use the Ruby on Rails talk mailing list or StackOverflow for questions/help, where a wider community will be able to help you. We reserve the issues tracker for issues only.

**Comment by Hareramrai** [comment]
@kaspth I am not seeing any ways to call db native methods in rails guide.

**Comment by Hareramrai** [comment]
@kaspth I have already create at stackoverflow(http://stackoverflow.com/questions/40787065/invoke-db2-encrypt-function-in-active-record-in-ruby-on-rails-for-new-record). It will great if you can help me on this.

**Comment by Hareramrai** [comment]
@guilleiguaran Can it done using ActiveRecord ?

**Comment by kaspth** [comment]
@Hareramrai that's for the users on StackOverflow to answer. Have a nice day!

**Comment by guilleiguaran** [comment]
`ActiveRecord.connection.raw_connection` should give you a instance of db2 driver connection.
