### ISSUE TITLE
Explain detail of websocket behavior in documentation

### ISSUE THREAD

**Issue by macabeus** [rails/rails#27162]
A lot of people uses Rails to create a provider API. In some cases, we need to establish a websocket connection. But, this situation wasn't written in the documentation, and [it's was a problem for me](https://stackoverflow.com/questions/40749647/not-receive-broadcast/40776406).

After establishing the connection on websocket's url, I need to send a message to the channel that I want to subscribe, like `{"command":"subscribe","identifier":"{\"channel\":\"MessagesChannel\"}"}`.

In my opinion, it is good write this detail [in this article](http://edgeguides.rubyonrails.org/action_cable_overview.html)

**Comment by maclover7** [comment]
Can you send a PR updating the documentation?

**Comment by brunomacabeusbr** [comment]
@maclover7 Sorry, but I'm newbie about websocket and Rails... I would not be a good person to document this.

**Comment by nateberkopec** [comment]
Hm, I think this is covered here: http://edgeguides.rubyonrails.org/action_cable_overview.html#client-side-components-connections

> The connection won't be established until you've also specified at least one subscription you're interested in having.

**Comment by brunomacabeusbr** [comment]
Well... I'm writing a code in Swift to use Rails' websocket more easily. And, I can't understand why values of key "identifier" and "data" to pass as string, instead of dictionary!

I expected:
```
{
  "command": "message",
  "identifier": {
    "channel": "MessagesChannel
  },
  "data": {
    "room_id": "1",
    "action": "enter_room"
  }
}
```

But, I need use:
```
{
  "command": "message",
  "identifier": \"{
    \"channel\": \"MessagesChannel\"
  }",
  "data": "{
  \"room_id\": \"1\",
  \"action\": \"enter_room\"
  }"
}
```

It took me a lot of time to find it. Why we need use a string?
