### ISSUE TITLE
activerecord table missing column

### ISSUE THREAD

**Issue by donaldleslie** [rails/rails#27194]
I am running the following:

ruby -v
ruby 2.3.1p112 (2016-04-26 revision 54768) [x86_64-linux]

gems are:

activerecord (5.0.0.1)
sqlite3 (1.3.12)

The table create is:

CREATE TABLE "member_statuses" ("member_statuses_key" INTEGER PRIMARY KEY   ,"members_key" integer  ,"board_member" text(1) DEFAULT 'N'  ,"membership_categories_key" integer  ,"membership_expiration" date  ,"paid_member" text(1) DEFAULT 'N'  ,"inactive" text(1) DEFAULT 'N'  );

The ruby program has:

  class Member_status < ActiveRecord::Base
    self.primary_key = 'member_statuses_key'
    belongs_to :membership_category, :class_name => 'Membership_category',
               :foreign_key=> 'membership_categories_key'
  end

  class Membership_category < ActiveRecord::Base
    self.primary_key = 'membership_categories_key'
    has_many :member_statuses, :class_name => 'Member_status'
  end 

From withing the program Typing Member_status shows all columns.

Member_status(member_statuses_key: integer, members_key: integer, board_member: text, membership_categories_key: integer, membership_expiration: date, paid_member: text, inactive: text)

But entering Member_status.column_names members_key is missing.

["board_member", "membership_categories_key", "membership_expiration", "paid_member", "inactive"]

So if I run the following:

      r = Member_statuses.create(fields)
      ret2 = r.save

where fields = {"board_member"=>"N", "membership_categories_key"=>8, "membership_expiration"=>"2015-12-31", "paid_member"=>"N", "inactive"=>"N", "members_key"=>393}

The table has members_key as null

If I run the command from sqlite3

 INSERT INTO MEMBER_STATUSES ( board_member, membership_categories_key, membership_expiration, paid_member, inactive, members_key) VALUES ( 'N', 8, '2015-12-31', 'N', 'N', 392 );

This can be seen from a sqlite3 select.

select * from member_statuses where member_statuses_key>391;

392|392|N|8|2015-12-31|N|N
393||N|8|2015-12-31|N|N

This did work with older gems. I do not know the versions that worked.

**Comment by matrix9180** [comment]
Please provide a test case using this template: https://github.com/rails/rails/blob/master/guides/bug_report_templates/active_record_gem.rb

**Comment by sgrif** [comment]
I was unable to reproduce with the provided information. This is likely a bug in your application, not with Rails. Please provide a reproducible test case and I will reopen the issue.

**Comment by donaldleslie** [comment]
I constructed a small test case and found the problem. I do not know if this is an expected behavior.

You can get column names with 
columns1 = Member_statuses.column_names

If you change columns1 with columns1.shift

Subsequent usage of Member_statuses.column_names has the first column missing. Using
columns1 = Member_statuses.column_names.dup avoids the problem.  I did not think that I 
could change the programs view of the table in this way. Restarting the program gets all the columns
so the table is not changes just the current view.

The file test.sql contains:

DROP TABLE IF EXISTS `member_statuses`;
CREATE TABLE "member_statuses" ("member_statuses_key" INTEGER PRIMARY KEY   ,"members_key" integer  ,"board_member" text(1) DEFAULT 'N'  ,"membership_categories_key" integer  ,"membership_expiration" date  ,"paid_member" text(1) DEFAULT 'N'  ,"inactive" text(1) DEFAULT 'N'  );
INSERT INTO "member_statuses" VALUES(1,1,'N',8,'2014-12-31','N','N');

and test_db created with :  sqlite3 test_db<test.sql
