### ISSUE TITLE
Second arg for 'options for select' works in Rails 5

### ISSUE THREAD

**Issue by dare05** [rails/rails#27202]
Here:

http://guides.rubyonrails.org/form_helpers.html

it writes:

`The second argument to options_for_select must be exactly equal to the desired internal value. In particular if the value is the integer 2 you cannot pass "2" to options_for_select - you must pass 2. Be aware of values extracted from the params hash as they are all strings.`

However, I tried doing exactly this in Rails 5 and it worked. So you might want to remove this or specify it applies for older versions of Rails.

**Comment by utilum** [comment]
This tip in the guides *does* date from 2009 (96d610553e5fdaabc923835ab1f194070ddb4477) (the invention of Rails guides?).
Perhaps we handle these better now?

**Comment by maclover7** [comment]
@dare05 Would you be able to submit a PR to update the docs? Thanks!

**Comment by sgrif** [comment]
Closing as there's no actionable bug here. Feel free to open a PR removing that warning if you wish, but it's not hurting anything if not.
