### ISSUE TITLE
Consistent generation of schema.rb

### ISSUE THREAD

**Issue by Dorian** [rails/rails#27200]
### Steps to reproduce

- Have some migrations
- Run `rake db:migrate`
- Coworker add more migrations
- Coworker runs `rake db:migrate`
- The difference between the two `schema.rb` is full of added spaces, different orders etc.

### Expected behavior

A consistent generation of `schema.rb`, shouldn't be machine-dependent.

### Actual behavior

- Adds / removes extensions, spaces, etc.
- Different order (views first now, views last before, for instance).

### Proposed solution

Having a `schema.rb` formatter would be nice a a post-processing step after its generation using a similar concept as `rubocop -a` for instance.

I think It would be far more difficult to have an actual consistent generation as its derived from the database.

### System configuration
**Rails version**: 5.0.0

**Ruby version**: 2.3.2

**Postgres version**: 9.5.5

**Comment by sgrif** [comment]
Migrations are expected to be consistent with the same set of migrations. Adding new migrations may alter the indentation of lines that were added by previous migrations to line up arguments. If running the *same* set of migrations on two different machines produces a different `schema.rb`, please provide an example application with that set of migrations, and enough information about the environments for us to reproduce.
