### ISSUE TITLE
There is no index.html file in public folder

### ISSUE THREAD

**Issue by Faari7** [rails/rails#27203]
i am new in ruby and just developing my first app, i am following a tutorial on youtube, when i run the server by localhost:3000 it shows me "Yay! You’re on Rails!". i don't know how to route it to index.html file in my home where i start developing my app. please need help i am new here

**Comment by kaspth** [comment]
Welcome! Try the Ruby on Rails talk mailing list or StackOverflow for questions/help, where a wider community will be able to help you. We reserve the issues tracker for issues only.

You'd want to look into config/routes.rb :)

**Comment by Faari7** [comment]
Rails.application.routes.draw do
  get 'home/index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end
this is routes.rb

**Comment by kaspth** [comment]
I didn't mean "post your routes" file, I meant "routes.rb" is where you should look to fix your own problem. Although you're frustrated and trying to learn, I hope you can see how we can't just give support to "some tutorial on youtube". I'd revisit the tutorial, either starting over from scratch, or look to where it's setting up the routes now that you know where to look (again, `config/routes.rb`).

Have at it! ❤️
