### ISSUE TITLE
Scope channel if multiple actioncable server using redis

### ISSUE THREAD

**Issue by StephaneRob** [rails/rails#27224]
### Steps to reproduce

1. create two rails app with a basic chat
2. Setup ChatChannel for both app with `stream_from "chat_channel"`
3. Run both app and two differents actioncable server (using redis)
4. send a message from app 1

### Expected behavior

The message is saved in app 1 and broadcasted to **app 1** websocket

### Actual behavior

The message is saved in app 1 and broadcasted to **both app** websocket

**Comment by matrix9180** [comment]
You need to set a different redis database in your cable.yml. Redis databases are integers, defaulting to 0.  Database name is the number after the last `/` in `url: redis://localhost:6379/1`

This request is like saying all table names in a SQL database need the app name prefixed because somebody wanted to use the same db for everything.

**Comment by StephaneRob** [comment]
I use two differents redis database `redis://localhost:6379/1` and `redis://localhost:6379/2`.
But according to redis doc
> Pub/Sub has no relation to the key space. It was made to not interfere with it on any level, including database numbers.
> Publishing on db 10, will be heard by a subscriber on db 1.
> If you need scoping of some kind, prefix the channels with the name of the environment (test, staging, production, ...).

**Comment by matrix9180** [comment]
Ah, disregard my comment then. That seems like a really odd design choice by the redis team to me though...

**Comment by matrix9180** [comment]
I'll see if I can make a patch to prefix channels with app/env

**Comment by matrix9180** [comment]
For now, looks like you should be able to override `channel_name` in your `ApplicationCable::Channel`. It's defined in `actioncable/lib/action_cable/channel/naming.rb` as: 

        def channel_name
          @channel_name ||= name.sub(/Channel$/, "").gsub("::", ":").underscore
        end

So you could change it to something like: 

        def channel_name
          @channel_name ||= "your_app_name:#{Rails.env}:' + name.sub(/Channel$/, "").gsub("::", ":").underscore
        end

**Comment by maclover7** [comment]
Thank you for opening up this issue, this is a neat bug! :)

The best way we can solve this is probably to create an app specific unique identifier or use the app name as @matrix9180 proposed.

**Comment by StephaneRob** [comment]
Looks like the @matrix9180 solution will work with Channel `broadcast_to` method, but what happen if we use `ActionCable.server.broadcast` directly ?

For now I have to scope the stream `stream_for "chat_channel_#{app1_name}"`

**Comment by StephaneRob** [comment]
Maybe we need to prefix on the `stream_from` method (`actioncable/lib/action_cable/channel/streams.rb`) too

```ruby
def stream_from(broadcasting, callback = nil, coder: nil, &block)
  broadcasting = "your_app_name:#{Rails.env}:#{String(broadcasting)}"
  ....
end
```

**Comment by matrix9180** [comment]
I'm having a bit of trouble getting the actioncable test suite running locally, will report back later today if I'm able to get that working, otherwise yes working on a PR.

**Comment by matrix9180** [comment]
Fixed my issues with the test suite. Looking into a PR.

**Comment by matrix9180** [comment]
@maclover7 After a couple runs of the tests I start getting `Errno::EMFILE: Too many open files - pipe`. 
I'm also seeing lots of warnings about uninitialized instance variables from concurrent-ruby and websocket-client-simple. 

I'm on Sierra, Ruby 2.3.2p217. 

Are you on Freenode so we don't have to pollute the comments here?

**Comment by matrix9180** [comment]
@maclover7 Seems I'm in a bit over my head on this one. I made the changes @StephaneRob suggested but can't see what tests it breaks because rake spews a bunch of warnings from concurrent-ruby and finally bombs out with 
`libc++abi.dylib: terminating with uncaught exception of type std::runtime_error: Too many open files
rake aborted!
SignalException: SIGABRT`

https://gist.github.com/matrix9180/42d9435d4c438396fdfa0995d54a7363

Ideas?

**Comment by matrix9180** [comment]
@maclover7 Does this seem like a reasonable approach?

**Comment by StephaneRob** [comment]
Any news on this ?

**Comment by matrix9180** [comment]
I'm thinking of dropping this down to the adapter level, will update the redis/evented_redis adapters & double check whether any others need it. Looks like Postgres does NOTIFY at the 'current database' level, so doesn't have this problem.

**Comment by matrix9180** [comment]
#27425

**Comment by matrix9180** [comment]
@maclover7 Ready for review here I believe.

**Comment by matrix9180** [comment]
Added some documentation on SubscriptionAdapter configuration to the ActionCable Overview guide. Not sure if it's in-scope for this PR or not.
