### ISSUE TITLE
Find by an array of values

### ISSUE THREAD

**Issue by azbshiri** [rails/rails#27223]
### Steps to reproduce

articles = []
article_ids.each do |article_id|
  articles << Article.find_by!(id: article_id)
end

### Expected behavior
articles = Article.find_batch_by!(id: article_ids)

### Actual behavior
There's no such method.

### System configuration
**Rails version**:
5.x
**Ruby version**:
2.3.x

**Comment by seuros** [comment]
#find accept an array of ids.

**Comment by azbshiri** [comment]
#find doesn't raise an exception if it doesn't find a record and also it doesn't accept other attributes.

**Comment by matthewd** [comment]
Please use the mailing list or StackOverflow for questions/help, where a wider community will be able to help you. We reserve the issues tracker for issues only.
