### ISSUE TITLE
Broken Link on ActiveRecord readme - https://github.com/rails/rails/blob/master/activerecord/README.rdoc

### ISSUE THREAD

**Issue by leealexcash** [rails/rails#27226]
### Steps to reproduce

Try clicking on the **"Learn More"** link directly below the code block with the text:-
```
class Product < ActiveRecord::Base
end
```

(Guidelines for creating a bug report are [available
here](http://guides.rubyonrails.org/contributing_to_ruby_on_rails.html#creating-a-bug-report))

### Expected behavior
Link should redirect to a new page

### Actual behavior
404 error

### System configuration
NA

**Ruby version**:
NA

**Comment by matthewd** [comment]
That's the raw source; the file is intended to be read from http://api.rubyonrails.org/files/activerecord/README_rdoc.html.
