### ISSUE TITLE
NameErrors in tests for large applications have a noticeable performance penalty

### ISSUE THREAD

**Issue by zmoazeni** [rails/rails#27230]
### Steps to reproduce

1. Generate a brand new application `rails new some_awesome_app`
2. Generate a model `rails generate model post title:string body:text`
3. Tweak the post_test to look like this:

```ruby
require 'test_helper'

class PostTest < ActiveSupport::TestCase
  test "the truth" do
    posts(:one)
    puts inspect
    some_variable_not_set
  end
end
```

4. Run the tests `rake test`

### Expected behavior
The test to fail in a reasonable time.

### Actual behavior
The tests fail in a reasonable time for small codebases, but for codebases with tons of models and fixtures, there's a noticeable delay per each test with a NameError (~10 seconds in our production app).

For some reason it boils down to test failures calling inspect on the test itself which generates the output for all the instance variables with `@fixture_cache`, `@fixture_connections`, and `@loaded_fixtures` being the main culprits. For our production application, the output of a single test running `puts inspect` generates a 54MB file.

We can monkey patch `ActiveSupport::TestCase` to avoid this, but that doesn't seem like the right approach to this. Overriding the `inspect` method on `ActiveSupport::TestCase` or the `inspect` methods on those variables will reclaim the performance hit. But there may be a better/smarter way to fix this.

### System configuration
**Rails version**: 4.0. 4.1, 4.2, 5.0

**Ruby version**: All

**Comment by zmoazeni** [comment]
I can help put together a PR for this, but I'd like to discuss it first to figure out what the right approach to solving this should be.

**Comment by sgrif** [comment]
This isn't really a bug in Rails. I don't think we want to set a precedent for overriding `inspect` on every object to be small just in case there's some case it can get huge and someone happens to cause a `NameError` on it. Really, this is an issue with Ruby itself. There is https://bugs.ruby-lang.org/issues/9725 open. I'd comment there or open another issue with Ruby requesting that it truncate the output above a certain size.
