### ISSUE TITLE
Class.descendants returns singleton classes starting from Ruby 2.3.0

### ISSUE THREAD

**Issue by conf** [rails/rails#27238]
### Steps to reproduce

Starting from Ruby 2.3.0, `Object.each_space` also [returns singleton classes](https://bugs.ruby-lang.org/issues/11360).

That breaks behavior of `Class.descendants` and `Class.subclasses` that also start to return singleton classes of their arguments.

```
begin
  require "bundler/inline"
rescue LoadError => e
  $stderr.puts "Bundler version 1.10 or later is required. Please update your Bundler"
  raise e
end

gemfile(true) do
  source "https://rubygems.org"
  # Activate the gem you are reporting the issue against.
  gem "activesupport", "5.0.0"
end

require "active_support/core_ext/object/blank"
require "minitest/autorun"

# Ensure backward compatibility with Minitest 4
Minitest::Test = MiniTest::Unit::TestCase unless defined?(Minitest::Test)

require "active_support/core_ext/class/subclasses"
Pants = Class.new

class BugTest < Minitest::Test
  def test_stuff
    Pants.new.singleton_class

    assert_equal Pants.descendants, []
  end
end

```

### Expected behavior

`Class.descendants` and `Class.subclasses` should not return singleton classes (test should pass).

### Actual behavior

```Fetching gem metadata from https://rubygems.org/..............
Fetching version metadata from https://rubygems.org/.
Resolving dependencies...
Using concurrent-ruby 1.0.2
Using minitest 5.9.1
Using i18n 0.7.0
Using bundler 1.13.6
Using thread_safe 0.3.5
Using tzinfo 1.2.2
Using activesupport 5.0.0 (was 4.2.7.1)
Run options: --seed 39273

# Running:

F

Finished in 0.011394s, 87.7655 runs/s, 87.7655 assertions/s.

  1) Failure:
BugTest#test_stuff [as_test.rb:28]:
Expected: [#<Class:#<Pants:0x007f90c4036310>>]
  Actual: []

1 runs, 1 assertions, 1 failures, 0 errors, 0 skips
```

### System configuration
**Rails version**: 5.0.0

**Ruby version**: 2.3.3

**OS**: macOS Sierra 10.12.1

**Comment by nateberkopec** [comment]
Hm - it was a breaking change for Ruby, so why shouldn't it be a breaking change in Activesupport? Is it Rails' job to cover up breaking changes in Ruby?

**Comment by conf** [comment]
Well, it's a breaking change for `ObjectSpace#each_object` that I can understand, but for `Class#descendants` usage of `ObjectSpace#each_object` is a detail of internal implementation that shouldn't be exposed. Nothing in the documentation, code examples nor tests points that `Class#descendants` should also return singleton objects, at least I was very surprised seeing this behavior.

Personally, I got a failed build in my CI with a very cryptic error, that I debugged to this snippet:
```ruby
def descendants(klass)
  ObjectSpace.each_object(klass.singleton_class).to_a - [klass]
end

def test_descendants(klass)
  print 'descendants before: '
  p descendants(klass)
  puts "creating singleton class... "
  yield klass
  print 'descendants after: '
  p descendants(klass)
end

# one way to create a singleton class
Pants = Class.new
test_descendants(Pants) { |k| k.new.instance_eval('{}') }

# pp also does it under the hood
require 'pp'

class RealCase 
  def initialize
    @context = {}
  end
end

# another way
test_descendants(RealCase) { |k| pp k.new }
```
Here's the output:
```
♥ ruby test.rb
descendants before: []
creating singleton class...
descendants after: [#<Class:#<Pants:0x007fe583979120>>]
descendants before: []
creating singleton class...
#<RealCase:0x007fe58503a8a0 @context={}>
descendants after: [#<Class:#<RealCase:0x007fe58503a8a0>>]
```

I also think that expected usage of `Class#descendants` is the old behavior (i.e. with singleton classes filtered out), and for the new behavior we can add a separate method (if we need to).

**Comment by maclover7** [comment]
Agree that the old behavior is what is intended. Working on a PR.

**Comment by conf** [comment]
@maclover7 Thank you, sir! Can we also have a backport to 4.2.x branch? The code should be identical there.

**Comment by sgrif** [comment]
@nateberkopec It's not our job to cover up changes in Ruby, but it is our job to make sure that our methods work as intended. `Class#descendants` definitely needs to exclude singleton classes.

**Comment by conf** [comment]
@sgrif Wow, that was fast! Any chance for a backport to 4.2.x? My project is still on that branch :(
