### ISSUE TITLE
Saving an ActiveRecord model with a PostgreSQL money field set with a Ruby Float throws a PostgreSQL syntax error in Rails 5

### ISSUE THREAD

**Issue by wiegand** [rails/rails#27246]
Creating a new Rails 5 application with a model that has a PostgreSQL money typed field will fail to save records if said field is set as a Ruby Float. Note:

1. Setting the money field as an `Fixnum` (e.g. `12`), `String` (e.g. `"12.25"`), or `String` with a dollar sign (e.g. `"$12.25"`) works as expected. No error is thrown, and the field when read back from PostgreSQL is properly typed in Rails as a `BigDecimal`.
2. Setting the money field as a `Float` (e.g. `12.25`), fails in Rails 5.0.0.1 (see below for example output and test file), and passes in Rails 4.2.7.1

### Steps to reproduce

Test file here: https://gist.github.com/wiegand/b481bdb9e6dc992048c127baf60cf0b5

(**Note**: you will need to update the PostgreSQL connection string on line 22 with an appropriate value for your system.)

### Expected behavior
Setting and persisting a money-typed field as a float should properly convert and store the value as the appropriate money value in PostgreSQL.

### Actual behavior
The following error is thrown:

```
BugTest#test_price_as_float:
ActiveRecord::StatementInvalid: PG::InvalidTextRepresentation: ERROR:  invalid input syntax for type money: "1.4000000000000000E+01"
: INSERT INTO "items" ("price") VALUES ($1) RETURNING "id"
```

### System configuration
**Rails version**: 5.0.0.1

**Ruby version**: ruby 2.3.2p217 (2016-11-15 revision 56796) [x86_64-darwin16]

**PostgreSQL version**: 9.6.1

**Comment by sgrif** [comment]
Thank you for a well written bug report.
