### ISSUE TITLE
database index creation with length options failing in 5.0.1.rc1

### ISSUE THREAD

**Issue by seanwalbran** [rails/rails#27243]
With rails 5.0.1.rc1, I'm seeing failures to create indexes in MySQL with `length` options specified.  It looks like the `length` options are being ignored.

### Steps to reproduce

- Executable reproduction script: https://gist.github.com/seanwalbran/03939f95c9dd2ba2c02fadc99698fe52#file-active_record_gem-rb
- Log of failure under 5.0.1.rc1: https://gist.github.com/seanwalbran/03939f95c9dd2ba2c02fadc99698fe52#file-5-0-1-rc1-log
- Log of success under 5.0.0.1: https://gist.github.com/seanwalbran/03939f95c9dd2ba2c02fadc99698fe52#file-5-0-0-1-log

[Line that breaks](https://gist.github.com/seanwalbran/03939f95c9dd2ba2c02fadc99698fe52#file-active_record_gem-rb-L30): ```t.index ["user_id", "uri"], name: "index_posts_on_user_id_and_uri", length: {"user_id"=>nil, "uri"=>255}, using: :btree```

Error message: ```Mysql2::Error: Specified key was too long; max key length is 767 bytes: CREATE TABLE `posts` (`id` int AUTO_INCREMENT PRIMARY KEY, `user_id` int NOT NULL, `uri` varchar(4096) NOT NULL,  INDEX `index_posts_on_user_id_and_uri` USING btree (`user_id`, `uri`)) ENGINE=InnoDB (ActiveRecord::StatementInvalid)```

### Expected behavior

Index `length` options should be applied when the index is created

### Actual behavior

Index `length` options are ignored, resulting in the failure to create the index if underlying length limits are exceeded.  Note in particular that the create table USING clause differs as follows:
- 5.0.1.rc1 (failure): USING btree (`user_id`, `uri`))
- 5.0.0.1 (success): USING btree (`user_id`, `uri`(255)))

### System configuration
**Rails version**: 5.0.1.rc1

**Ruby version**: 2.3.1

**Database**: mysql 5.6.22

**Comment by maclover7** [comment]
Bisected, 4ce674f6449c870707ebdc0f7995e4147a1348af seems to introduce the error.

cc @kamipo
cc @matthewd, 5.0.1 release manager

**Comment by kamipo** [comment]
#26687 will fix this issue.
