### ISSUE TITLE
Strange warnings in default `rails g --help` output

### ISSUE THREAD

**Issue by mltsy** [rails/rails#27256]
### Steps to reproduce

```
> rails new test-project
> rails g --help
```

### Expected behavior
A useful help message without any errors or warnings

### Actual behavior
A useful help message, AND the following 3 warnings:
```
Expected string default value for '--jbuilder'; got true (boolean)
Expected string default value for '--helper'; got true (boolean)
Expected string default value for '--assets'; got true (boolean)
```

### System configuration
**Rails version**: 5.0.0.1
**Ruby version**: 2.3.1 (mri)
Ubuntu 16.04

**Comment by mltsy** [comment]
I couldn't figure out where these warnings were even coming from.  If I knew, I would look into it and try to be more specific about the bug or submit a patch... any ideas?  Do other people get this output?

**Comment by rafaelfranca** [comment]
It is from thor. Could you check if the 5.0.1.rc1 also show that?

**Comment by brad-werth** [comment]
Same thing here, with Rails 5.0.1.rc1:

```bash
bwerth@worth:~/test-project$ rails --version
Rails 5.0.1.rc1
bwerth@worth:~/test-project$ ruby --version
ruby 2.3.1p112 (2016-04-26 revision 54768) [x86_64-linux]
bwerth@worth:~/test-project$ rails g --help
Running via Spring preloader in process 10245
Expected string default value for '--jbuilder'; got true (boolean)
Usage: rails generate GENERATOR [args] [options]
...
```

**Comment by utilum** [comment]
Same here. Rails 5.0.1.rc1, ruby 2.3.3p222 (2016-11-21 revision 56859) [x86_64-linux].
However, in Rails 5.0.0.1, the command `rails g --help` just hangs, not even responding to `Ctrl+C`.

**Comment by rafaelfranca** [comment]
You have to use jbuilder master to remove all of them. But `--helper` and `--assets` were removed in 5.0.1.rc1

**Comment by mltsy** [comment]
Oh, awesome.  Thanks! :)
@utilum Yeah, I've gotten that hanging process a couple times right after initializing a project.  Usually if I close the console and open a new one it works fine.  (Hopefully that's not an issue in 5.0.1, as you indicated, but I haven't tried, and it was kind of intermittent)
