### ISSUE TITLE
Why there is no render_relative method?

### ISSUE THREAD

**Issue by rusikf** [rails/rails#27252]
Hello rails contributers ! Do you plan to create method for views context like ```render_relative``` ?
There are a lot of apps where I have a nested structure of views, for example
```
user/aggregates/news/partial_1.html
user/aggregates/news/partial_2.html
user/aggregates/news/list.html

user/aggregates/posts/partial_3.html
user/aggregates/posts/partial_4.html
user/aggregates/posts/list.html
```
It will be excellent if we can use relative path in any partial for render another partial, not absolute path... What you think about this idea ?

With best regards, Ruslan

**Comment by rafaelfranca** [comment]
`render` already supports relative paths. And no, we don't have any plan to add new methods.

Also please don't ask questions in the issue tracker.

Thanks!

**Comment by nateberkopec** [comment]
@rusikf In the future, if you have questions, the Rails gitter/IRC channels are very active and have plenty of people who can help.
