### ISSUE TITLE
Parameterize strips unicode characters

### ISSUE THREAD

**Issue by SeanHealy33** [rails/rails#27270]
### Expected behavior
It feels kinda buggy that currently if you have a case like `'Здравствуйте'.parameterize` returns `''` 

It would be nice if `.parameterize` could be configured to generate slugs with unicode characters preserved.

Would something like this be a reasonable change?
___

```
def parameterize(string, sep = :unused, separator: '-', preserve_case: false, preserve_unicode: false)
``` 

And if the `preserve_unicode: true` was passed we would use a different regex like: `^p{Alnum}` over `^a-z0-9`
___

**Comment by rafaelfranca** [comment]
Preserving unicode is already the default behavior or parameterize. Look the documentation.

```
Replaces special characters in a string so that it may be used as part of a 'pretty' URL.
```

If it is not working it is a bug but it doesn't require any new option.

**Comment by rafaelfranca** [comment]
In your case I believe the i18n rules to transliterate those characters are missing. Make sure you have them configured. See the transliterate documentation http://api.rubyonrails.org/classes/ActiveSupport/Inflector.html#method-i-transliterate

**Comment by ndvbd** [comment]
@rafaelfranca, this doesn't work for me too. Why do we need transliterate? You can't/dont want to transliterate when it's russian,hebrew,arabic, etc. We just want to parameterize them, so we can't put them in a URL, not to change the characters.
