### ISSUE TITLE
Extending ActiveRecord::Base breaks presence validation on belongs_to relations

### ISSUE THREAD

**Issue by efatsi** [rails/rails#27276]
### Steps to reproduce

- extend ActiveRecord::Base:

```ruby
# config/initializers/extend_module.rb
module Nothing; end
ActiveRecord::Base.extend Nothing
```

### Expected behavior
Presence validation on `belongs_to` relationships exist

### Actual behavior
The built in presence validation on `belongs_to` relationships no longer exist. The validation will exist if you explicitly pass `optional: false`, but no longer exists by default.

### System configuration
**Rails version**: 5.0.0.1

**Ruby version**: 2.3.1

I've provided a sample application with minimal functionality required to demonstrate this issue: https://github.com/efatsi/testing-rails5

**Comment by rafaelfranca** [comment]
You should not extend active record like that. It will change the load order of the framework.

Use:

```ruby
module Nothing; end
ActiveSupport.on_load(:active_record) do
  extend Nothing
end

**Comment by efatsi** [comment]
Thanks for the quick response!
