### ISSUE TITLE
Wrong command for secret key creation in rails security guidelines

### ISSUE THREAD

**Issue by andneuma** [rails/rails#27295]
### Expected behavior
Should be `rake secret`

### Actual behavior
Actually is `rails secret`

See [Ruby on Rails Security Guide](http://guides.rubyonrails.org/security.html#session-storage)

**Comment by sgrif** [comment]
`rails secret` is the correct command.

**Comment by andneuma** [comment]
Sorry, but it's not... it's a rake task, try it yourself please

**Comment by kaspth** [comment]
@andneuma you're looking at the guides for Rails 5, where `rails secret` works just fine.

**Comment by andneuma** [comment]
yeah, came to my mind just a minute ago, still being on 4.2+
