### ISSUE TITLE
"rescure_from" not working?

### ISSUE THREAD

**Issue by 1c7** [rails/rails#27301]
### ENV:
* Ruby 2.3.1
* Rails 5
* macOS （MacBook Pro 2014 mid)
![image](https://cloud.githubusercontent.com/assets/1804755/21010222/e3d89776-bd85-11e6-95ff-c107a9f16d7f.png)

![image](https://cloud.githubusercontent.com/assets/1804755/21010136/6b914e66-bd85-11e6-94f4-9fbc09319e9a.png)

## The code should work:
```ruby
   rescue_from ActiveRecord::RecordNotFound, with: :invalid_cart

    def invalid_cart
      logger.eror "Attempt to access invalid card #{params[:id]}"
      redirect_to store_index_url, notice: 'invalid cart'
    end
```
## The problem
it didn't work
![image](https://cloud.githubusercontent.com/assets/1804755/21010288/37108926-bd86-11e6-9a27-ec15dcce0969.png)

## Problem detail
rescue_from just not working, I already google it. But still can't find a answer.
I remember this book involve a lot core member of Ruby on Rails. 
so I think Github issue may be a good place to ask question like this?

### Full Code is down below:  
```ruby
class CartsController < ApplicationController
  before_action :set_cart, only: [:show, :edit, :update, :destroy]

  rescue_from ActiveRecord::RecordNotFound, with: :invalid_cart

  # GET /carts
  # GET /carts.json
  def index
    @carts = Cart.all
  end

  # GET /carts/1
  # GET /carts/1.json
  def show
  end

  # GET /carts/new
  def new
    @cart = Cart.new
  end

  # GET /carts/1/edit
  def edit
  end

  # POST /carts
  # POST /carts.json
  def create
    @cart = Cart.new(cart_params)

    respond_to do |format|
      if @cart.save
        format.html { redirect_to @cart, notice: 'Cart was successfully created.' }
        format.json { render :show, status: :created, location: @cart }
      else
        format.html { render :new }
        format.json { render json: @cart.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /carts/1
  # PATCH/PUT /carts/1.json
  def update
    respond_to do |format|
      if @cart.update(cart_params)
        format.html { redirect_to @cart, notice: 'Cart was successfully updated.' }
        format.json { render :show, status: :ok, location: @cart }
      else
        format.html { render :edit }
        format.json { render json: @cart.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /carts/1
  # DELETE /carts/1.json
  def destroy
    @cart.destroy
    respond_to do |format|
      format.html { redirect_to carts_url, notice: 'Cart was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cart
      @cart = Cart.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def cart_params
      params.fetch(:cart, {})
    end

    def invalid_cart
      logger.eror "Attempt to access invalid card #{params[:id]}"
      redirect_to store_index_url, notice: 'invalid cart'
    end

end

```

## My Question:
why `rescue_from` not working as it work in the book?
Am I doing anything wrong?

Thank in advance for all these nice people in Rails community.

**Comment by utilum** [comment]
Welcome to 5 :)

Try the Ruby on Rails talk mailing list or StackOverflow for questions/help, where a wider community will be able to help you. We reserve the issues tracker for issues only.

(You may want to see if spring is running, and stop it if it does).

**Comment by 1c7** [comment]
@utilum Thank you very much

**Comment by davidpatters0n** [comment]
@ic7 - you had a typo: `logger.eror "Attempt to access invalid card #{params[:id]}"`. `.eror` -> `.error`

**Comment by 1c7** [comment]
@davidpatters0n  
Thank you!
It work now!


![image](https://cloud.githubusercontent.com/assets/1804755/21036612/1814a558-be02-11e6-8713-207ee54cb0e0.png)
