### ISSUE TITLE
Rails documentation and :nodoc:

### ISSUE THREAD

**Issue by MSP-Greg** [rails/rails#27317]
I've been working on a YARD plugin, and decided to parse into several of the Rails DSL's to generate better Rails docs.  A good example would be [ActiveRecord::Base](https://msp-greg.github.io/rails_gem/ActiveRecord/Base.html).

I've got a question on expectations regarding the RDoc `:nodoc:` directive.  In the RDoc docs, `:nodoc:` will hide all methods/constants/etc of a class/module marked as such.  But, it will not hide inner classes/modules (or namespace child classes/modules).  See [Directives](http://docs.seattlerb.org/rdoc/RDoc/Markup.html#class-RDoc::Markup-label-Directives).  To hide inner classes, one should use the `:nodoc: all` directive.

Conversely, when viewing docs at [api.RubyOnRails.org](http://api.rubyonrails.org/), it appears that inner classes/modules are being hidden.

I've got two types of Rails docs online (user & contributor), the current gem docs (user version) show the following class -

[ActiveRecord::Associations::Builder::HasAndBelongsToMany::JoinTableResolver::KnownTable](https://msp-greg.github.io/rails_gem/ActiveRecord/Associations/Builder/HasAndBelongsToMany/JoinTableResolver/KnownTable.html),

since it is not `:nodoc:`, but all its parents are (scroll the treeview up to see that).  This class isn't shown at [api.RubyOnRails.org](http://api.rubyonrails.org/).

I don't use RDoc, but the docs sure seem to imply the class should be visible.

Hence --

1. Should it be visible?
2. If not, should Rails code be changed to hide these objects?

If 2 is true, I can generate a list of all non `:nodoc:` objects with `:nodoc:` parents.

**Comment by rafaelfranca** [comment]
Usually not. They should be also no visible. If you could generate a list of those cases it would be really useful. Feel free to send PRs, although maybe it is better to keep all changes in the same pr so we can discuss easily what should and what should not be removed from the documentation. Thanks.

**Comment by MSP-Greg** [comment]
See [Rails :nodoc: info](https://raw.githubusercontent.com/MSP-Greg/MSP-Greg.github.io/master/rails_master/rails_nodoc_info_2016-11-02.txt)

The above file shows non `:nodoc:` objects with `:nodoc:` namespace parents, and also shows non `:nodoc:` classes (and exceptions) with `:nodoc:` superclasses.  Object on the left, file on the right.

I know we may disagree about this, but you might have a look at --

[Rails master branch](http://10.31.31.2:8808/rails_master/index.html), which is a 'contributor version'.  Expand the 'Classes' list with the global plus button (to the right of the 'List Search' textbox).  This will show you all of the `:nodoc:` classes/modules, as they're flagged with a red left border.  The docs have a separate 'Exceptions' list, which also contains `:nodoc:` items.

A 'user version' of the 5.0.0.1 gem is at [Rails current gem](http://10.31.31.2:8808/rails_gem/index.html).  It has all `:nodoc:` items removed, excepting what we're now discussing.

Reminder, the `:nodoc:` and `:nodoc: all` directives are file based, so in any file where the namespace 'path' appears, the directive needs to exist (if there are children in the file).  I'd prefer to use the `:nodoc: all` directive, and I could help with the pr's (after discussion).

If you ever have time, I'd like to know if there are any DSL's I've missed.  Part of the reason I went to the trouble of writing the code is because I'd like to learn Rails.  When I saw docs that showed no methods for [api.RubyOnRails.org ActiveRecord::Base](http://api.rubyonrails.org/classes/ActiveRecord/Base.html) (compared to [ActiveRecord::Base](http://10.31.31.2:8808/rails_gem/ActiveRecord/Base.html)), but Ruby showed it with several hundred methods...
