### ISSUE TITLE
read_multi via cached: true doesn’t work with abbreviated syntax

### ISSUE THREAD

**Issue by brchristian** [rails/rails#27315]
On a Rails 5.0.0.1 project, I noticed by looking at my logs that when I use 

```ruby
<%= render partial: "articles/article", collection: @articles, cached: true %>
```

My articles are nicely fetched all at once. However, when I instead use the syntactic sugar to write

```ruby
<%= render @articles, cached: true %>
```

My articles are _not_ fetched all at once. The only clue that this was the case was looking at the logs and noticing that I wasn’t seeing the nice

```
 Rendered collection of articles/_article.html.erb [12 / 12 cache hits] (9.2ms)
```

in the logs.

It seems to me that if `render: @articles` is meant to be shorthand for `render partial: "articles/article", collection: @articles`, then `cached: true` should work equally well in both cases.

Is this a bug? If so, I’d be happy to submit a PR.

**Comment by kaspth** [comment]
On the todo list but keep getting distracted with other things. Do look into it!

**Comment by brchristian** [comment]
@kaspth As far as I can tell the crux of it is in the [rendering helper](https://github.com/rails/rails/blob/master/actionview/lib/action_view/helpers/rendering_helper.rb#L24-L37):

```ruby
# If no options hash is passed or :update specified, the default is to render a partial and use the second parameter
# as the locals hash.
def render(options = {}, locals = {}, &block)
  case options
  when Hash
    if block_given?
      view_renderer.render_partial(self, options.merge(partial: options[:layout]), &block)
    else
      view_renderer.render(self, options)
    end
  else
    view_renderer.render_partial(self, partial: options, locals: locals, &block)
  end
end
```

To my mind there are two ways of addressing this if we wanted to get the `render @projects, cached: true` syntax working.

1. We could explicitly check to see if `cached` is in the `locals` and shift it over to the `options` hash. This isn’t particularly pretty. It also means 

2. We could make it so that the handy `render @projects` syntax _doesn’t_ by default put whatever else you pass into it into the `locals` hash. This might break some existing behavior for some users.

If there are more elegant answers here, I’m game to do some of the implementation, but at the moment it seems like both of these paths have drawbacks. I’d be happy to know if you have any instincts here. Cheers!

**Comment by kaspth** [comment]
Yeah, that's where I injected as well. Feel free to take this further: https://github.com/kaspth/rails/commit/35fc9588e5f22ad678a7553c0395e377b13cff98

It needs to be explored whether we're better off with `def render(options = {}, cached: false, **locals)` or similar (and whether or not we've said we support string keys in locals).

Also not sure about the `stub` in the tests. Anyway, do investigate! ❤️
