### ISSUE TITLE
Caching woes since #20884

### ISSUE THREAD

**Issue by brchristian** [rails/rails#27326]
Since updating our main production app to Rails 5.0.0.1, we’ve noticed a bunch of substantial performance regressions, and I’ve managed to trace them back to #20884.

Our main app is a publishing platform that has a `public` scope that looks something like

```ruby
.where("publish_date <= ?", Time.current)
```

We have a partial on the home page that looks something like this:

**app/controllers/article.rb**
```ruby
@recent = Article.public.order(publish_date: :desc).limit(4)
```

**app/articles/_recent.html.erb**
```
<% cache @recent do %>
  <%= render partial: "articles/article", collection: @recent, cached: true %>
<% end %>
```

The first thing that I noticed is that in Rails 4.2 the `@recent` object would lazily evaluate at the top of the `articles/recent` partial, and then the cache_key would be an array of the cache keys of the member objects. This would, n-1 times a day, result in a cache hit, and we’d never need to render the collection.

In Rails 5.0.0.1, however, two things happen:

1. The fragment cache _never_ hits, because the scope has `Time.current` in it and so the query signature will always be different.
2. The default implementation since #20884 involves `count` and `MAX`, so it triggers _two_ db queries: one `COUNT` query to get the cache key, and then a _second_ one to actually evaluate the `@recent` scope. (By the way, the cache key query takes 8x as long in our application as the actual record fetch!)

This behavior seems totally counterproductive to me from a performance standpoint.

The only way I can find to get the Rails 4.2 behavior back is to replace the controller code with 

```
@recent = Article.public.order(publish_date: :desc).limit(4).to_a
```

*  *  *

**Edit:** I’ve also discovered that the #20884 cache_key behavior plays weirdly with kaminari, as the following controller code illustrates:

```ruby
@articles = @author.articles.public.paginate page: params[:page], per_page: 12
```

Will this cache the Rails 4.2 way, on the fetched articles (in which case the fragment will cache hit and only trigger one query)? Or the #20884 way, on the query signature + count + maximum updated_at (in which case the fragment will never cache hit and will trigger two queries)? Turns out, it depends! If more than 12 records exist, it will be the Rails 4.2 way; if fewer than 12 records exist, it will be the #20884 way.

*  *  *

In my opinion, #20884 should be reverted, because the pre-existing 4.2 behavior is both more intuitive and more performant (at least in our application). Barring that I think the documentation needs to be much more clear on how one is expected to use this new default behavior.

Filling my code with explicit `.to_a` at the end of every scope doesn’t seem very Rails-y to me, but maybe that’s the new best practice in 5.0.0.1?

**Comment by sgrif** [comment]
If you want a query that changes every day, you should use `Time.current.at_beginning_of_day` or `Time.current.at_end_of_day`. I do not think that this is a bug.

**Comment by brchristian** [comment]
@sgrif I’m looking into getting `Time.current` out of our `public` scope declaration, which I think is a good suggestion. However this turns out to be way less obvious in practice than it sounds (what if you publish something midday, for instance?). Not obvious to me what the solution is here. If you know of some best practice off the top of your head that I’m not aware of, I’m all ears.

At any rate, that aside there are a number of issues remaining here that go beyond that particular point. Just to clarify:

1. The new cache_key query since https://github.com/rails/rails/pull/20884 is in our application about 8x slower than just fetching the records directly. I suspect this is because we don’t have an index on `updated_at`. What’s the recommendation here? Add `updated_at` index to all If users migrating from Rails 4.2 apps need to add an index on `updated_at` to most of their queries so that the cache keys are performant, I think this needs to be better documented.

2. The new cache_key implementation appears to have many issues: for instance it’s not always unique [1](https://github.com/rails/rails/pull/20884#issuecomment-128910649) [2](https://github.com/rails/rails/pull/20884#issuecomment-132687705) and plays weirdly with limit [3](https://github.com/rails/rails/pull/21503). If I can help with any PRs I would be glad to pitch in.

3. Cache misses will result in double queries. This seems like a mixed blessing in a lot of applications where the caches turn over frequently.

4. The fact that, to use the Kaminari example, the way the cache key is generated depends on the size of the record set returned by the query, seems like an issue either in Rails and/or in Kaminari.

If there are places I can contribute with PRs, even if it’s just to documentation, let me know. This really threw us in our Rails 5 migration and I’d love to save other people from needing to do all the performance debugging that we’ve been doing to diagnose this!

**Comment by sgrif** [comment]
1) That's a valid concern. I'm not sure if this just requires documentation, or investigation for a fix.
2) PRs to fix any concrete issues, with an explanation of why it's a problem and how that PR improves it are much appreciated.
3) It's usually the case that a cache friendly solution is more expensive on a cold cache. For example, N+1 query bugs are usually more cache friendly.
4) The size of the record set should be consistent. If it changes, the cache key should change.

**Comment by brchristian** [comment]
@sgrif 👍 I agree with you on 3 - fair point. Not sure yet if 4 is a bug or not; may investigate after we tweak our queries to try to get `Time.current` out of the picture. Will look into 1 & 2 and see if I can come up with something concrete. Cheers!

**Comment by sgrif** [comment]
Thanks for being friendly on the issue tracker! <3

**Comment by matthewd** [comment]
The fact we've traded caching of the view render for caching of the query result (and view render) seems... complex.

For a lot of use cases, that's a win because it saves constructing a bunch of AR instances. But for others, as shown here, we've blown a cache that was previously working well -- it always loaded the records, but it re-rendered the view precisely once each time that set of records changed.

It'd be nice if we had a simple answer to get back the old behaviour, at least. Perhaps we should use the query-based key for unloaded relations, but the actual records for a loaded relation? It's surely going to be pretty rare for real-world code to reach the same cache call sometimes with a loaded relation, and sometimes with an unloaded relation with an identical query.

**Comment by sgrif** [comment]
I don't know that changing the behavior based on the loaded status is
useful. `.to_a` trivially returns the old behavior

**Comment by brchristian** [comment]
I keep coming back to the performance of the digest query itself. It’s consistently about 8x slower in MySQL than fetching the actual objects. Any idea what’s up here?

```
   (10.7ms)  SELECT  COUNT(*) AS `size`, MAX(`articles`.`updated_at`) AS timestamp FROM `articles` WHERE `articles`.`is_visible` = 1 AND (publish_date <= '2016-12-11 00:25:35.549491') AND (publish_date <= '2014-10-23 07:00:00') AND (`articles`.`id` != 8538) LIMIT 5
Read fragment views/articles/query-49c894ca7b5055d3bf95a5599507cb7d-8407-20161209211715000000/79d6fc9e95add5258ce19b090015704a (0.1ms)
  Article Load (1.2ms)  SELECT  `articles`.* FROM `articles` WHERE `articles`.`is_visible` = 1 AND (publish_date <= '2016-12-11 00:25:35.549491') AND (publish_date <= '2014-10-23 07:00:00') AND (`articles`.`id` != 8538) ORDER BY `articles`.`publish_date` DESC, `articles`.`id` DESC LIMIT 5
```

```
   (8.1ms)  SELECT  COUNT(*) AS `size`, MAX(`articles`.`updated_at`) AS timestamp FROM `articles` WHERE `articles`.`is_visible` = 1 AND (publish_date <= '2016-12-11 00:31:00.997447') AND (publish_date <= '2014-10-23 07:00:00') AND (`articles`.`id` != 8538) LIMIT 5
Read fragment views/articles/query-8d46de0edee3ba68a082cece280aa53f-8407-20161209211715000000/79d6fc9e95add5258ce19b090015704a (0.0ms)
  Article Load (0.7ms)  SELECT  `articles`.* FROM `articles` WHERE `articles`.`is_visible` = 1 AND (publish_date <= '2016-12-11 00:31:00.997447') AND (publish_date <= '2014-10-23 07:00:00') AND (`articles`.`id` != 8538) ORDER BY `articles`.`publish_date` DESC, `articles`.`id` DESC LIMIT 5
```

```
   (6.3ms)  SELECT  COUNT(*) AS `size`, MAX(`articles`.`updated_at`) AS timestamp FROM `articles` WHERE `articles`.`is_visible` = 1 AND (publish_date <= '2016-12-11 00:31:42.256369') AND (publish_date <= '2014-10-23 07:00:00') AND (`articles`.`id` != 8538) LIMIT 5
Read fragment views/articles/query-4bcaa1a63fc45dc52b8456d0337c970a-8407-20161209211715000000/79d6fc9e95add5258ce19b090015704a (0.1ms)
  Article Load (0.9ms)  SELECT  `articles`.* FROM `articles` WHERE `articles`.`is_visible` = 1 AND (publish_date <= '2016-12-11 00:31:42.256369') AND (publish_date <= '2014-10-23 07:00:00') AND (`articles`.`id` != 8538) ORDER BY `articles`.`publish_date` DESC, `articles`.`id` DESC LIMIT 5
```

I even created a custom index just for the cache_key but it’s still much slower than the actual AR fetch.

**schema.rb**
```ruby
  create_table "articles", force: :cascade, options: "ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci" do |t|
   [...]
    t.index ["is_visible"], name: "index_articles_on_is_visible", using: :btree
    t.index ["publish_date", "id", "is_visible", "updated_at"], name: "cache_key_index", using: :btree
    t.index ["publish_date", "id", "is_visible"], name: "index_articles_on_publish_date_and_id_and_is_visible", using: :btree
    t.index ["publish_date", "id"], name: "index_articles_on_publish_date_and_id", using: :btree
    t.index ["publish_date", "is_visible"], name: "index_articles_on_publish_date_and_is_visible", using: :btree
    t.index ["publish_date"], name: "index_articles_on_publish_date", using: :btree
    t.index ["updated_at"], name: "index_articles_on_updated_at", using: :btree
  end
```

Here is the query explainer. Any ideas?

```
irb(main):022:0> Article.public.where(["publish_date <= ?", day_of_last_published]).limit(5).where.not(id: 555).select("COUNT(*) AS size", "MAX(updated_at) AS timestamp").explain
  Article Load (5.0ms)  SELECT  COUNT(*) AS size, MAX(updated_at) AS timestamp FROM `articles` WHERE `articles`.`is_visible` = 1 AND (publish_date <= '2016-12-11 00:43:32.171880') AND (publish_date <= '2016-12-10 08:00:00') AND (`articles`.`id` != 555) ORDER BY `articles`.`publish_date` DESC, `articles`.`id` DESC LIMIT 5
=> EXPLAIN for: SELECT  COUNT(*) AS size, MAX(updated_at) AS timestamp FROM `articles` WHERE `articles`.`is_visible` = 1 AND (publish_date <= '2016-12-11 00:43:32.171880') AND (publish_date <= '2016-12-10 08:00:00') AND (`articles`.`id` != 555) ORDER BY `articles`.`publish_date` DESC, `articles`.`id` DESC LIMIT 5
+----+-------------+----------+------------+-------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------+---------+------+------+----------+--------------------------+
| id | select_type | table    | partitions | type  | possible_keys                                                                                                                                                                                                                | key             | key_len | ref  | rows | filtered | Extra                    |
+----+-------------+----------+------------+-------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------+---------+------+------+----------+--------------------------+
|  1 | SIMPLE      | articles | NULL       | range | PRIMARY,index_articles_on_is_visible,index_articles_on_publish_date,index_articles_on_publish_date_and_is_visible,index_articles_on_publish_date_and_id,index_articles_on_publish_date_and_id_and_is_visible,cache_key_index | cache_key_index | 5       | NULL | 3464 |    32.18 | Using where; Using index |
+----+-------------+----------+------------+-------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------+---------+------+------+----------+--------------------------+
1 row in set (0.00 sec)

irb(main):023:0> Article.public.where(["publish_date <= ?", day_of_last_published]).limit(5).where.not(id: 555).explain
  Article Load (0.9ms)  SELECT  `articles`.* FROM `articles` WHERE `articles`.`is_visible` = 1 AND (publish_date <= '2016-12-11 00:43:40.977823') AND (publish_date <= '2016-12-10 08:00:00') AND (`articles`.`id` != 555) ORDER BY `articles`.`publish_date` DESC, `articles`.`id` DESC LIMIT 5
=> EXPLAIN for: SELECT  `articles`.* FROM `articles` WHERE `articles`.`is_visible` = 1 AND (publish_date <= '2016-12-11 00:43:40.977823') AND (publish_date <= '2016-12-10 08:00:00') AND (`articles`.`id` != 555) ORDER BY `articles`.`publish_date` DESC, `articles`.`id` DESC LIMIT 5
+----+-------------+----------+------------+-------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------------------+---------+------+------+----------+-------------+
| id | select_type | table    | partitions | type  | possible_keys                                                                                                                                                                                                                | key                            | key_len | ref  | rows | filtered | Extra       |
+----+-------------+----------+------------+-------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------------------+---------+------+------+----------+-------------+
|  1 | SIMPLE      | articles | NULL       | index | PRIMARY,index_articles_on_is_visible,index_articles_on_publish_date,index_articles_on_publish_date_and_is_visible,index_articles_on_publish_date_and_id,index_articles_on_publish_date_and_id_and_is_visible,cache_key_index | index_articles_on_publish_date | 5       | NULL |   10 |     6.44 | Using where |
+----+-------------+----------+------------+-------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------------------+---------+------+------+----------+-------------+
1 row in set (0.00 sec)
```

**Comment by brchristian** [comment]
It seems to me like this gets back to the `LIMIT` not being respected. I like the ideas in https://github.com/rails/rails/pull/21503 as a way to address this -- is this something I can pitch in to get merged?
