### ISSUE TITLE
More :nodoc: questions / issues

### ISSUE THREAD

**Issue by MSP-Greg** [rails/rails#27325]
Below is a (final?) summary of my questions/cases for :nodoc: use in Rails.  My interest is that I would prefer YardT2 doc's 'user version' correctly hides these objects.

`:nodoc:` Cases

1. Non `:nodoc:` object with `:nodoc:` namespace parent
    1.1 Non `:nodoc:` `ClassMethods` module with `:nodoc:` namespace parent (does this question have a 'global' answer, vs case by case?)
2. Non `:nodoc:` class with `:nodoc:` superclass
3. Non `:nodoc:` object with attributes created via a `:nodoc:` module's `included do` call

Case 1 was the main question in #27317, but I touched on case 2.  Case 3 is new.  Below is an example of case 3.

In `ActiveRecord::Base`, there are several modules that add attributes to it via the `included do` call.  Three of these are `:nodoc:` modules.

See [ActiveRecord::Base ActiveRecord::Reflection include](https://msp-greg.github.io/rails_gem/ActiveRecord/Base.html#Reflection-Attributes-Methods)

This could be considered equivalent to opening the `ActiveRecord::Base` class in the `ActiveRecord::Reflection` module, which would categorize the added attributes as non `:nodoc:`.

Hence, case 3 is equivalent to - should attributes like [.nested_attributes_options](https://msp-greg.github.io/rails_gem/ActiveRecord/Base.html#nested_attributes_options-class_method) or [#aggregate_reflections](https://msp-greg.github.io/rails_gem/ActiveRecord/Base.html#aggregate_reflections-instance_method) be visible in user versions of `ActiveRecord::Base`?

I've updated the [Rails :nodoc: info](https://raw.githubusercontent.com/MSP-Greg/MSP-Greg.github.io/master/rails_master/rails_nodoc_info_2016-11-02.txt) text file.  [Case 1](https://github.com/MSP-Greg/MSP-Greg.github.io/blob/master/rails_master/rails_nodoc_info_2016-11-02.txt#L1-L98) is listed first, followed by [case 2](https://github.com/MSP-Greg/MSP-Greg.github.io/blob/master/rails_master/rails_nodoc_info_2016-11-02.txt#L101-L157) and [case 3](https://github.com/MSP-Greg/MSP-Greg.github.io/blob/master/rails_master/rails_nodoc_info_2016-11-02.txt#L160-L193).

Finally, some info re doc software.  I'd like to make this clear, since you seem adamant that :nodoc: information should not appear anywhere.

#### RDoc

All of the public facing RDoc versions of Rails seem to not include `:nodoc:` objects, but as I've pointed out, there may some issues.  RDoc does not natively parse into any Rails DSL.

#### YARD

[RubyDoc.info - rails](http://www.rubydoc.info/docs/rails) shows many repos and gems doc'd with YARD.  The only RDoc directives that YARD currently supports are when parsing c source.  Hence, **YARD docs will show all `:nodoc:` objects**.  I don't believe that any public YARD sites parse into Rails DSL.

#### YardT2

I've gone to the trouble of allowing creation of both 'user' and 'contributor' versions of docs, and `:nodoc:` objects are tagged as such.  I've added code to parse Rails DSL.

In the info on case 1 (namespace parent), there are several children of [ActionView::Helpers](https://msp-greg.github.io/rails_master/ActionView/Helpers.html) listed.

I thought some consideration should be given to whether `ActionView::Helpers` should be `:nodoc:`, so I looked around.  It has one native method, `.eager_load!`.  So I checked the 'Methods' list for it.
Seven `.eager_load!` methods, two are `:nodoc:`, five are not.

That kind of information may be helpful to contributors, so that's why I went to the trouble.

Another example might be looking up the `#process_action` chain in [ActionController::Base](https://msp-greg.github.io/rails_master/ActionController/Base.html), which shows six methods (in order).  This kind of information cannot be obtained in RDoc or YARD, and would take a bit of work to find in an IDE / editor...

Anyway, moving forward, if you tagged the text file with directions, I'd be happy to start generating PR's.  Maybe a commit per base namespace, or pile them all together by the three case types?

**Comment by rafaelfranca** [comment]
Cc @fxn

**Comment by matthewd** [comment]
Can you link to some code examples to clarify your questions? (and/or add some actual questions?)

I've tried following the links to your generated output, but it seems too crowded for me to work out what it's trying to represent.

**Comment by MSP-Greg** [comment]
@matthewd

Matthew,

Sorry, some of this is a continuation of a previous issue.

The central question is what is the intent of the Rails contributors as to how the RDoc `:nodoc:` directive affects visiblility in documentation.  I've shown three cases that I consider relevant.

Once that is decided, should corrections be made if some of the RDoc directives in Rails are incorrect?

#### Case 1

I've mentioned that RDoc's docs seem to imply that if you have nesting such as:

```ruby
module A  # :nodoc:
  class B
  end
end
```

that `B` will be shown in documents.  The RDoc docs state to use the `:nodoc: all` directive to hide `B`.

There are several instances in Rails where a namespace parent (`A`) is `:nodoc:`, but a child (`B`) is not.

#### Case 2

This is simply a case as follows:

```ruby
class A  # :nodoc:
end

class B < A
end
```

Was the intent to have `B` hidden?  Again, several cases in Rails.

#### Case 3

This is a bit more complex, and it doesn't have a 'pre-existing' answer.  Code something like:

```ruby
module A  # :nodoc:
  include ActiveSupport::Concern
  included do
    mattr_accessor :index_nested_attribute_errors, instance_writer: false
  end
end

class B
  include A
end
```

`A`, which is `:nodoc:`, creates attributes in `B` via the `included` block parameter.  Should the attributes be listed in docs for `B`?


I hope this helps.  The text file shows all the instances of the three cases.

As also mentioned, I've created docs without `:nodoc:` (user version), and docs with `:nodoc:` (contributor version).  I would like the 'user version' to display exactly what the contributor's intent was, and the 'contributor version' to correctly tag all `:nodoc:` items.

> I've tried following the links to your generated output, but it seems too crowded for me to work out what it's trying to represent.

I'm sorry to hear that.  Open to suggestions...

It all started with `ActiveRecord::Base`.  Many docs show it with no methods, and that seemed odd.

I looked at it with Ruby's meta-programming methods, and saw (from my memory) over 200 native methods (most created via `included` blocks), and another 500 inherited methods.  Then, I discovered how many different files those methods were contained in.  Then, I noticed how much 'chaining' exists in the include/extend topology.

At that point, I decided that, even though showing all those methods would make for a big document, I needed to show all that detail in `ActiveRecord::Base`.  I also added method search within a document, so one could find matching methods easily.

If you check out the docs for the Ruby or AWS libraries, they're similar to other docs systems.  Things just explode with some of the Rails objects...

**Comment by matthewd** [comment]
> There are several instances in Rails where a namespace parent (A) is :nodoc:, but a child (B) is not.

This one probably depends on the individual situation. Sometimes it will be the case that B is missing a nodoc... but that is also an IMO reasonable pattern for a documented B inside a namespace A:

If A is a class defined in `a.rb`, and A::B is defined in `a/b.rb`, then it can be distracting for `A` to claim it is partly defined in `a/b.rb` (and contrariwise, for the file to claim to be responsible for defining the class) when in truth, it's merely mentioned as a namespace around `A::B`.

> [B inherits from nodoc A] Was the intent to have B hidden?

I think the answer to all three questions, really, is: no, there are not rules you can apply to impute intent other than the behaviour visible in our published documentation.

There are likely to be things missing a nodoc, certainly.. but they're generally going to be because we forgot to consider it, not because we don't know how rdoc works.

---

PRs to correct `:nodoc:` flags on things that are incorrectly showing up on http://api.rubyonrails.org/ are welcome.

**Comment by matthewd** [comment]
> I'm sorry to hear that. Open to suggestions...

Backing off the font size and closing the floating-over-half-the-content TOC makes it feel slightly less claustrophobic, but it still feels somehow unpleasant. I'm not a designer, so I can only really guess, but I think it needs a *lot* more white space.

**Comment by MSP-Greg** [comment]
Wasn't sure whether to float the TOC when first use happens or not.  I'm either on a 1920 monitor, or an iPad.  I almost never float either pane, but YARD has a floating pane...  By chance, what's your monitor resolution is?

More on your previous reply later.  And, thanks.

**Comment by matthewd** [comment]
I'm on a 13" MBP, so it presents as 1280x800.

**Comment by MSP-Greg** [comment]
Give it a try now (please clear cache & reset font size).  Added some css media queries.  You should be at 13px font size now.  Let me know if you think 14px would be better.  Some of the SVG images may be blurry or incorrectly sized, I fixed two.

Interested in moving to a google group or the docs site repo?

> If A is a class defined in a.rb, and A::B is defined in a/b.rb, then it can be distracting for A to claim it is partly defined in a/b.rb (and contrariwise, for the file to claim to be responsible for defining the class) when in truth, it's merely mentioned as a namespace around A::B.

Kind of a doc question, and I've thought the same, but left it as is since RDoc and YARD both do it that way.   IOW, why should one see a gazillion files in [RoR ActiveRecord](http://api.rubyonrails.org/classes/ActiveRecord.html) or [YardT2 ActiveRecord](https://msp-greg.github.io/rails_master/ActiveRecord.html) when the constants and methods are defined in just a few (or one) files?  If one's coding in Ruby, and doesn't understand namespaces and standard filename/object mappings, well...  FWIW, I think that's a pretty easy thing for me to change.  That's also the reason I made that section collapsible (plus / minus to the left of 'Relationships & Source Files')...

I do have more Rails documentation comments, but I'd prefer to discuss somewhere else.

**Comment by MSP-Greg** [comment]
As I've stated, I have created a documentation system, and the 'contributor version' for Rails is located at [Rails master](https://msp-greg.github.io/rails_master/index.html).

It includes information that does not appear in other doc systems.  I've cited the example of [ActiveRecord::Base](https://msp-greg.github.io/rails_master/ActiveRecord/Base.html), which, when inspected in Ruby, has a very large set of methods available, but when viewed at [RoR Docs](http://edgeapi.rubyonrails.org/classes/ActiveRecord/Base.html), there are no methods.

Docs system UI's are difficult to design due the needs of users when viewing large, highly nested libraries like Rails.

Docs system's content is difficult to design due the needs of the two types of users, the first being API users (user), the second being API creators/maintainers (c/m).

The difference is essentially what to remove from user docs, as the c/m docs should show everything.  This can be done on an object basis (directives like `:nodoc:` or YARD tags), or done thru doc system configuration.

c/m docs should also show object relationships, properties, and children that are difficult to discern by code inspection.  'Instance chain' vs 'static/direct includes' is one example, what is `:nodoc:` is another.

An example of a configuration setting is the removal of c source in all of the [Ruby Core](https://msp-greg.github.io/ruby_stable/Core/index.html) libraries, except for the [Ruby Core trunk](https://msp-greg.github.io/ruby_trunk/Core/index.html).

Since 'object basis removal' is important, the c/m version should clearly show that distinction so c/m's can verify it.

If you're interested in these docs, I would like help/feedback with the following:

#### UI issues with the docs

I have used them with 1920 monitors and a non retina iPad. I need help with css settings for other devices.

#### user vs c/m visibility

I'm wondering about additional configuration settings for user docs.  For example, what info in the 'Relationships & Source Files' section do users need to see?

#### 'Relationships & Source Files - c/m version'

I've shown 'full chain' information, should I additionally show 'direct'? eg:

* `A` included in `B`, `B` included in `C`, `A` instance chain shows `B` and `C`.  Should I add 'direct includes', which for `A` would show `B` (but not `C`)?

* `E` < `D`, `F` < `E`, `D` subclasses shows `E` and `F`. Should I add direct subclasses, which for `D` would show `E` (but not `F`)?

#### Rails

I've created code to parse into many Rails DSL methods.  I'm know I'm missing things.  For instance (using my favorite example), `ActiveRecord::Base` ancestors includes `ActiveSupport::Callbacks` and `ActiveRecord::Base::GeneratedAssociationMethods`, but my code isn't finding them.  How are they added?

#### Please post issues [here](https://github.com/MSP-Greg/MSP-Greg.github.io/issues)

If possible, please separate Rails, general, and UI issues...
