### ISSUE TITLE
Error on reload when registering ActiveRecord::Types in initializer

### ISSUE THREAD

**Issue by clupprich** [rails/rails#27337]
### Steps to reproduce

1. Create a custom `ActiveRecord::Type`
2. Register that type in an initializer (as advised in the docs) via `ActiveRecord::Type.register`
3. Create a model where that custom type is used
4. Start a `rails console`
5. `reload!` the environment
6. `ArgumentError: A copy of CustomType has been removed from the module tree but is still active!`

I've created a sample application that does above steps and exhibits the error: https://github.com/clupprich/ar_types_register

### Expected behavior
I'd expect the type to be reloaded just fine

### Actual behavior
An `ArgumentError` is raised, because the Type registry still holds the old reference to the now reloaded `CustomType`.

### System configuration
**Rails version**: 5.0.0.1

**Ruby version**: 2.3.1p112

I'm able to work around this issue by placing the `ActiveRecord::Type.register` call into the file that defines the type. However, you then need to be careful about the order the files are loaded (e.g. that hack doesn't work out of the box for the example repository above).

I tried producing a quick fix by clearing the types registry in a `to_prepare` callback, but of course we would need to re-register the custom defined types (and any other default ones). Haven't found a nice way how to do this yet.

**Comment by fxn** [comment]
You cannot autoload in an initializer, please have a look at http://guides.rubyonrails.org/autoloading_and_reloading_constants.html#autoloading-and-initializers.

**Comment by gsamokovarov** [comment]
What you can do is call `attribute :price, Price::Type.new` and that way you don't need to register the types and worry about autoloading. If you still fancy the symbols, you can do something in the lines below without going through the registry:

```ruby
# app/models/application_record.rb

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true

  class << self
    def attribute(name, cast_type, **options)
      if guess = cast_type.to_s.camelize.safe_constantize
        guess = guess::Type if guess.const_defined?(:Type)
        cast_type = guess.new
      end

      super
    end
  end
end
```

That will allow you to write `attribute :price, :price`, but it won't hit the registry, if it can guess the attribute type in the application.

**Comment by clupprich** [comment]
Thanks for the link, @fxn! I now understand the behaviour.
@gsamokovarov Thanks for the solution how to fix this - I'm totally okay with the `Price::Type.new`.

Is that something worth hinting to in the docs? If yes, I'm happy to create a PR!

**Comment by eileencodes** [comment]
Sounds like this isn't a bug so I'm going to close.

@clupprich if you think that the information would be useful in the documentation please do open a PR.

**Comment by timdiggins** [comment]
@clupprich thanks for this and also your blog post on it, really helped. I've changed the docs to help guide other people away from this problem -- if you have a chance to look at #32242 let me know your thoughts?
