### ISSUE TITLE
actionview-5.1.0.alpha.gem

### ISSUE THREAD

**Issue by DouglasAllen** [rails/rails#27336]
### Steps to reproduce
 I cloned the master.
Ran bundle
Ran some rake tasks for building and installing gems. 
> rake build
> rake install

Both aborted at actionview.

(Guidelines for creating a bug report are [available
here](http://guides.rubyonrails.org/contributing_to_ruby_on_rails.html#creating-a-bug-report))

### Expected behavior
It got the first three activesupport, activemodel, and activerecord installed just fine.

### Actual behavior
When it got to actionview Rake aborted.

> cd actionview && bundle exec rake package && gem build actionview.gemspec && mv actionview-5.1.0.alpha.gem C:/row/rails/pkg/
rake aborted!
LoadError: cannot load such file -- blade

### System configuration
**Rails version**: = rails (5.1.0.alpha)

**Ruby version**: = ruby 2.2.6p396 (2016-11-15 revision 56800) [x64-mingw32]

**Comment by guilleiguaran** [comment]
is this problem reproducible with actioncable as well?

**Comment by MSP-Greg** [comment]
@DouglasAllen 

On behalf of the Rails team (of which I'm not a member), thank you for reporting your installation issue.

Sometimes installation code changes are not tested on 'fresh' systems that have been cleaned of previous builds and dependencies.

Assume you installed the blade gem and continued?

**Comment by DouglasAllen** [comment]
I don't know because it never got that far. And I cannot install blade with the devkit. There are too many missing libraries.

**Comment by MSP-Greg** [comment]
@DouglasAllen 

I've got a little different Rails install, but, I'm also on Windows, and I didn't have blade installed.

Tried, stopped due to an issue with curses, tried curses by itself, still wouldn't compile curses.

Hence, the issue seems to be curses on Windows...

When I have a chance to get back to it, and if I can find the issue, I'll let you know.  Sorry...

I'm using ruby-2.3.2p182.

**Comment by matthewd** [comment]
Sorry, but it doesn't sound like we can easily support building the gems on Windows, and it doesn't sound like something we're likely to want to do non-easily.
