### ISSUE TITLE
ActiveRecord: Attribute methods are not getting defined on Marshal.load

### ISSUE THREAD

**Issue by kamaljoshi** [rails/rails#27348]
As outlined in the issue https://github.com/rails/rails/issues/18659, If you create your object instance using Marshal.load; `#allocate`, `#initialize` or `#init_with` are not called and that results in model not getting defined with attribute methods. So, things like overriding attribute method breaks. This used to work prior to AR 4.2 and broke with this change: https://github.com/rails/rails/commit/84cf156e2428551069d6fba5547fc41bc42182b2#diff-dfe09551f2188457e7e1891d86047c57

I tested this on AR 4.2 but I guess this bug is even present in AR 5.

### Steps to reproduce
According to the issue creation guidelines, I am adding the script to reproduce it

```ruby
begin
  require "bundler/inline"
rescue LoadError => e
  $stderr.puts "Bundler version 1.10 or later is required. Please update your Bundler"
  raise e
end

gemfile(true) do
  source "https://rubygems.org"
  gem "rails", '4.2.7.1'
  gem "sqlite3", '1.3.11'
end

require "active_record"
require "minitest/autorun"
require "logger"

# This connection will do for database-independent bug reports.
ActiveRecord::Base.establish_connection(adapter: "sqlite3", database: ":memory:")
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :posts, force: true do |t|
    t.string :title
  end
end

class Post < ActiveRecord::Base
  def title
    super || 'Default Title'
  end
end

class BugTest < Minitest::Test
  def test_attribute_definition
    Post.create!
    Post.reset_column_information

    post = Post.last

    assert_equal 'Default Title', post.title
    assert_equal true, post.class.instance_variable_get(:@attribute_methods_generated)
  end

  def test_attribute_definition_with_marshal
    dump = Marshal.dump(Post.create!)
    Post.reset_column_information

    post = Marshal.load(dump)

    assert_equal 'Default Title', post.title
  end

  def test_attribute_definition_bool_with_marshal
    dump = Marshal.dump(Post.create!)
    Post.reset_column_information

    post = Marshal.load(dump)

    assert_equal true, post.class.instance_variable_get(:@attribute_methods_generated)
  end
end
```

### Expected behaviour
If the attribute methods are not defined, they should be appropriately defined so things like calling `super` works in case of overriden methods.

### Actual behaviour
Right now, due to the attribute not being defined it fails and throws a NoMethodError when `method_missing` from ActiveModel tries to call the original method as the method defined check(`respond_to_without_attributes?(method, true)`) succeeds in that.

### System configuration
**Rails version**: 4.2.7.1

**Ruby version**: 2.1.5

**Comment by maclover7** [comment]
cc @sgrif

**Comment by utilum** [comment]
@kamaljoshi I don't understand everything in your test, but I've tweaked it to remove the call to `super` which raises an error and then to use Rails 4.7.2's [own test for record_attributes](https://github.com/rails/rails/blob/v4.2.7.1/activerecord/test/cases/attribute_methods/read_test.rb#L53-L57).
The tweaked tests for [master](https://gist.github.com/utilum/49e7353777a65857486468c9000dd430) and [4.7.2](https://gist.github.com/utilum/2faa32e70838d1966971d20897032577) both pass.

**Comment by utilum** [comment]
That is to say, at least the attribute read method is alive and kicking. What's not working for you?

**Comment by kamaljoshi** [comment]
@utilum The whole issue is when you have a method with the same name as an attribute. You removed that from your tests, so they will not show the error anyway.

**Comment by utilum** [comment]
I had the impression from the subject and description that your problem was related to marshalling... Now you say it's all about overriding the generated attribute method... what are you trying to do?

**Comment by kamaljoshi** [comment]
@utilum My proper is with marshalling. But the problem surfaces only when you have a method that was overriding a generated attribute method, as the attribute methods are not generated properly.

**Comment by utilum** [comment]
@kamaljoshi [test on master with generated attribute method override](https://gist.github.com/utilum/49e7353777a65857486468c9000dd430) passes. But what is it you are actually trying to do? There are simpler ways to set a default value.

**Comment by kamaljoshi** [comment]
@utilum Your new test is also avoiding the original method call.
The example I gave for method `#title` was just supposed to be a sample method to display the bug. The problem is still the same. If you load an object using Marshal, the original methods are not defined as the `#generate_attribute_methods` is not called when the object is loaded. So, any method that was overriding an attribute method and calling the original method inside breaks. 

I can workaround this issue by replacing the original method calls by accessing attributes in alternative ways(like you did) but the bug is still there.

**Comment by utilum** [comment]
OK, @sgrif would have a better response, but I have the impression this is expected behavior, and the shortest way to recreate your expected behavior would be call `post.class.define_attribute_methods` just after `Marshal.load`, or monkey patch `Marshal.load` if it recurs.

**Comment by kamaljoshi** [comment]
@utilum Thanks for looking into this. 

I noticed this issue in memcache cached objects where dalli was calling `Marshal.load`. So, to fix this for that flow, I will need to patch Dalli's `#get` methods.

Calling `self.class.define_attribute_methods` feels repetitive as I will have to do this every time I override so I would like to avoid that. Also, it may lead to a dev missing this and breaking something.

**Comment by stanhu** [comment]
This problem also affected us in GitLab. We use `Rails.cache` to fetch cached objects, and because `define_attribute_methods` is not called, the overridden methods fail. Here's the modified script demonstrating the problem:

```ruby
begin
  require "bundler/inline"
rescue LoadError => e
  $stderr.puts "Bundler version 1.10 or later is required. Please update your Bundler"
  raise e
end

gemfile(true) do
  source "https://rubygems.org"
  gem "rails", '4.2.8'
  gem 'redis', '~> 3.2'
  gem 'redis-activesupport', '5.0.1'
  gem "sqlite3", '1.3.11'
end

require "active_record"
require "minitest/autorun"
require "logger"
require 'rails'

# This connection will do for database-independent bug reports.                                                                                                                                                                                                                                                                                                                                                                    
ActiveRecord::Base.establish_connection(adapter: "sqlite3", database: ":memory:")
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :posts, force: true do |t|
    t.string :title
  end
end

class Post < ActiveRecord::Base
  def title=(value)
    super("prefixed #{value}")
  end

  def title
    super || 'Default Title'
  end
end

class BugTest < Minitest::Test
  def test_first_pass
    return unless ARGV[0] == '1'

    post = Post.create!
    assert_equal 'Default Title', post.title

    cache = ActiveSupport::Cache::RedisStore.new
    cache.write('test_key', post)
  end

  def test_second_pass
    return unless ARGV[0] == '2'

    cache = ActiveSupport::Cache::RedisStore.new
    post = cache.fetch('test_key')
    # post.class.define_attribute_methods                                                                                                                                                                                                                                                                                                                                                                                          
    assert_equal 'Default Title', post.title
  end
end
```

Run the script in two passes:

```
ruby fail.rb 1
ruby fail.rb 2
```

In the second pass, you see:

```
BugTest#test_second_pass:
NoMethodError: super: no superclass method `title' for #<Post id: 1, title: nil>
Did you mean?  title=
    /Users/stanhu/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/activemodel-4.2.8/lib/active_model/attribute_methods.rb:430:in `method_missing'
    fail1.rb:37:in `title'
    fail1.rb:58:in `test_second_pass'
```

**Comment by jasonayre** [comment]
Getting bitten by this also.

```
  revision: dc3ae21802c316e1639239d28202db7aa7fb7cac
  branch: 4-2-stable
```

Simply caching a model with the following method:

``` ruby
    def label
      super || self.name
    end
```

Is blowing up. However, additional information I didn't see mentioned already:

Currently using file store cache in production, which is working fine (though it's possible that it's only working fine due to use of docker cloud / docker services file system being ephemeral), problem only surfaced in development when switching over to redis/memcached for cache store

**Comment by kamaljoshi** [comment]
@jasonayre Not a proper fix but I ended up doing this to fix it. This calls define whenever an object is loaded from marshalled dump.

```ruby
require 'active_support/core_ext/module/aliasing'

module Marshal
  class << self
    def load_with_activerecord_special_consideration(source)
      obj = load_without_activerecord_special_consideration(source)
      if defined?(::ActiveRecord::Base) && obj.is_a?(::ActiveRecord::Base)
        obj.class.define_attribute_methods
      end
      obj
    end

    alias_method_chain :load, :activerecord_special_consideration
  end
end
```

**Comment by IvanChou** [comment]
The problem still exists with `Rails 5.0.6`

won't fix? @sgrif

**Comment by vinodlala** [comment]
@kamaljoshi @stanhu @jasonayre @IvanChou  

Would this work?  

Using @kamaljoshi's example, changing from:

```
  def title
    super || 'Default Title'
  end
```

To:

```
  def title
    self[:title] || 'Default Title'
  end
```

**Comment by utilum** [comment]
@stanhu 's script still fails with master (and `redis-activesupport` master).
@vinodlala : it works not.

```
begin
  require 'bundler/inline'
rescue LoadError => e
  $stderr.puts 'Bundler version 1.10 or later is required. Please update your Bundler'
  raise e
end

gemfile(true) do
  source 'https://rubygems.org'

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  gem 'rails', github: 'rails/rails'
  gem 'redis', '~> 3.2'
  gem 'redis-activesupport', github: 'redis-store/redis-activesupport'
  gem "sqlite3"
end

require "active_record"
require "minitest/autorun"
require "logger"
require 'rails'

# This connection will do for database-independent bug reports.
ActiveRecord::Base.establish_connection(adapter: "sqlite3", database: ":memory:")
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :posts, force: true do |t|
    t.string :title
  end
end

class Post < ActiveRecord::Base
  def title=(value)
    super("prefixed #{value}")
  end

  def title
    super || 'Default Title'
  end
end

class BugTest < Minitest::Test
  def test_first_pass
    return unless ARGV[0] == '1'

    post = Post.create!
    assert_equal 'Default Title', post.title

    cache = ActiveSupport::Cache::RedisStore.new
    cache.write('test_key', post)
  end

  def test_second_pass
    return unless ARGV[0] == '2'

    cache = ActiveSupport::Cache::RedisStore.new
    post = cache.fetch('test_key')
    # post.class.define_attribute_methods
    assert_equal 'Default Title', post.title
  end
end
```

**Comment by vinodlala** [comment]
@utilum - Thanks for trying that.
