### ISSUE TITLE
ActiveRecord reselect() - would a PR be welcome?

### ISSUE THREAD

**Issue by brchristian** [rails/rails#27340]
Inspired by `rewhere` and `reorder`, I’ve been looking into a similar implementation for `reselect`. I find it a helpful syntax to have, especially after getting used to the feel of the other two.

Is this something the Rails team would be interested in if I prepared a PR?

**Comment by matthewd** [comment]
Can you show some example uses?

I'm generally dubious about API methods that strip aspects back out of the relation -- they seem to over-expose the deferred evaluation, for example.

**Comment by brchristian** [comment]
This came up when I was looking at collection cache key implementations. You might, for instance, have some AR relation that you want to create a cache key for. Let’s just say hypothetically you’ve got a fragment cache for `Post.all.select(:title, :body)`. The cache key is based only on `:updated_at`. You can always take the original query and just append `.select(:updated_at)`, but then you’re pulling an arbitrary amount of `title` and `body` out of the db when you don’t need it. Something like `query.reselect(:updated_at)` would be a tidy way of dealing with a case like that.

**Comment by brchristian** [comment]
(Obviously, one can always `query.unscope(:select).select(:updated_at)`, but just given the existence of rewhere and reorder, I figure it might be intuitive to offer reselect as well.)
