### ISSUE TITLE
Gem Load Error is: Could not find a JavaScript runtime

### ISSUE THREAD

**Issue by pradeepagrawal** [rails/rails#27357]
### Steps to reproduce
- Generate new rails app by using "rails new appname"
- run "bundle install"
- start server by "rails s"

You will see the error in the terminal

### Expected behavior
It should not give an error when running server

### Actual behavior
It gives an error saying "Gem Load Error is: Could not find a JavaScript runtime. See https://github.com/rails/execjs for a list of available runtimes."

### System configuration
**Rails version**: 5.0.0.1

**Ruby version**: 2.3.0

### Solution
- uncomment the "therubyracer" gem in gemfile and run bundle install
- Now try running server. It will work file

So I think in default rails generated app by the rails generator should have this change.
Please let me know what you think.

**Comment by guilleiguaran** [comment]
therubyracer doesn't work in Windows or JRuby so it can't be a default in those platforms, plus JSC is installed by default on OSX so OSX users don't need it and Linux users with Node.js installed don't need it neither. That's why we prefer to have therubyracer commented in the Gemfile.

**Comment by pradeepagrawal** [comment]
I use ubuntu and it gives me the same error every time. That's why I thought to tell you guys about this.

**Comment by guilleiguaran** [comment]
Yes, but we can't make it a default for every user (Windows, Linux, OSX, JRuby) because it doesn't work/isn't needed in every platform.

**Comment by pradeepagrawal** [comment]
But if you think as a developer's perspective, Around 70-80 % of developers uses OSX or ubuntu for development. And Let's take 30% of them is uses ubuntu then it is huge. So can't we provide a way for them that it automatically overcome the problem if it is ubuntu OS instead the developer has to manually uncomment it after facing the error.
Just a suggestion.

**Comment by nateberkopec** [comment]
See #22339.

**Comment by sammymwangangi** [comment]
I was am using windows 8.1 and i am running ```rails server``` on NodeJS Command Prompt,since the environment is set with node.
