### ISSUE TITLE
Rails 5 belongs_to requirement error in nested attributes

### ISSUE THREAD

**Issue by thalesfp** [rails/rails#27360]
### Steps to reproduce

Using the following configuration:

```ruby
class Car < ApplicationRecord
  has_one :category, as: :categorizable

  accepts_nested_attributes_for :category
end

class Category < ApplicationRecord
  belongs_to :categorizable, polymorphic: true
end

class CarsController < ApplicationController
  def create
    @car = Car.new(car_params)

    if @car.save
      render json: @car
    else
      render json: @car.errors, status: :unprocessable_entity
    end
  end

  private

  def car_params
    params.require(:car)
          .permit(:name, :color, category_attributes: [:name])
  end
end

Rails.application.config.active_record.belongs_to_required_by_default = true
```

### Expected behavior

When I created a new car using these parameters:

car[name]:Fusca
car[color]:Blue
car[category_attributes][:name]:Old

Then I got:

{"category.categorizable":["must exist"]}

But when I set belongs_to_required_by_default = false it worked.

I think that this issue is caused because the id of the Car is created before the validation of Category.

### System configuration
Rails 5.0.0.1
ruby 2.3.3p222

**Comment by nateberkopec** [comment]
This looks like expected behavior. [For more information, look up `validates_presence_of`.](https://stackoverflow.com/questions/14553463/validate-presence-of-polymorphic-parent)

You'll get a faster/better response on StackOverflow or Gitter, since this is not a bug in Rails.

**Comment by qinmingyuan** [comment]
The same issue,  I consider `accepts_nested_attributes_for` should assign the object id to foriegn key.

**Comment by thalesfp** [comment]
But since in Rails 5 the behavior of belongs to is required by default the accepts_nested_attributes_for should assign the object id to foreign key, otherwise it will never work (I guess).

**Comment by prathamesh-sonpatki** [comment]
This is the same issue as https://github.com/rails/rails/issues/25198

**Comment by thalesfp** [comment]
@nateberkopec @prathamesh-sonpatki Thank you guys
