### ISSUE TITLE
CoffeeScript is not defined error

### ISSUE THREAD

**Issue by bplmp** [rails/rails#27372]
### Steps to reproduce
1. `rails new myapp`
2. `cd myapp`
3. `rails generate controller Welcome index`
4. Add `root 'welcome#index'` to config/routes.rb
5. `rails server`

### Expected behavior
Renders index.html.erb.

### Actual behavior
    ...app/views/layouts/application.html.erb where line #7 raised:

    ReferenceError: CoffeeScript is not defined

    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

### System configuration
OSX 10.11.6
**Rails version**:
5.0.0.1
**Ruby version**:
ruby 2.3.3p222 (2016-11-21 revision 56859) [x86_64-darwin15]

**Comment by bplmp** [comment]
Changing this gem worked for me, but I'm not on Windows (I followed these steps http://stackoverflow.com/questions/28760633/ruby-on-rails-errors-with-javascript-include-tag)... 

    gem 'coffee-script-source', '1.8.0'



More, I have other Rails apps I had created just yesterday that are still working without changing the gem. Strange.

**Comment by tjbladez** [comment]
Could be related to the fact that latest `coffee-script-source-1.12.1` gem is empty :)

**Comment by markhkim** [comment]
I can confirm I have the same error on:
Linux Mint 18
```
$ ruby -v
ruby 2.3.3p222 (2016-11-21 revision 56859) [x86_64-linux]
$ rails -v
Rails 5.0.0.1
```

**Comment by markhkim** [comment]
Seems like this is an issue over at coffeescript: https://github.com/jashkenas/coffeescript/issues/4403

**Comment by guilleiguaran** [comment]
coffee-script-source 1.12.1 was yanked

**Comment by prodhan29** [comment]
coffee-script-source 1.12.1 is problematic.
changing  the "coffee-script-source 1.12.1"  to "coffee-script-source 1.11.1" in Gemfile.lock file worked for me.

**Comment by utilum** [comment]
jashkenas/coffeescript#4403 was closed. this also?

**Comment by bplmp** [comment]
Actually I'm still getting the error, even with https://github.com/jashkenas/coffeescript/issues/4403 closed.

**Comment by Mirv** [comment]
Still getting it too - https://ide.c9.io/mirv/slimtest ...

Gemfile

`source 'https://rubygems.org'
gem 'rails', '5'
gem 'sqlite3'
gem 'jquery-rails'
gem 'turbolinks'
gem 'jbuilder', '~> 2.0'
gem 'sdoc', '~> 0.4.0', group: :doc
gem 'slim'
gem 'cocoon'
gem 'sass-rails', '~> 5.0'
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 4.1.0'
gem 'coffee-script-source', '1.8.0'
group :development, :test do
  gem 'byebug'
end
group :development do
  gem 'web-console', '~> 2.0'
  gem 'spring'
end
`

**Comment by guilleiguaran** [comment]
I've released a new version of coffee-script-source https://rubygems.org/gems/coffee-script-source/versions/1.12.2
