### ISSUE TITLE
Assymetric Time/String equality

### ISSUE THREAD

**Issue by rwz** [rails/rails#27377]
### Steps to reproduce

```ruby
require "active_support/all"
time = Time.now.round

# comparing String with Time
time.iso8601 == time # false, as expected

# comparing Time with String
time == time.iso8601 # true, ¯\_(ツ)_/¯ 
```

### Expected behavior
Both comparisons return false

### Actual behavior
Time equals String

### System configuration
Behavior can be examined in ActiveSupport 4.2 and 5.0. I didn't test other versions.
Ruby 2.3.3

This causes all kinds of weird issues like this one for example: https://github.com/rspec/rspec-expectations/issues/958

Normally you'd assume object equality to be symmetrical so that if`a == b` then `b == a`. This is not true in this case.

**Comment by rafaelfranca** [comment]
This is not true in many cases. A String don't need to know how to compare with time, but a time can know how to compare with a String. The same hold true with any object. You don't expect to monkey patch String if your object implement `==` that coerces a string.

**Comment by rwz** [comment]
I try to not have coersing `==` operators in my code and consider it an anti-pattern.

Also, this is the case where Active Support changes the way Ruby works. In Ruby without ActiveSupport Time does not equal String.

I'm not saying that this is a bug that needs to be fixing , I'm arguing that this behavior exhibits  a bad design and it might be worth exploring the possibility of removing it in the future.

**Comment by rafaelfranca** [comment]
Active Support changes the way Ruby works, but I agree maybe it is worth to explore the possibility of removing this comparing in the future.
