### ISSUE TITLE
Chaining .where with .first_or_initialize only assigns association_id, not the full model

### ISSUE THREAD

**Issue by sidot3291** [rails/rails#27370]
### Steps to reproduce

```
#define a category association on model
class Product < ApplicationRecord
  belongs_to :category
end

#from console
c = Category.find(1)

p = Product.where(category: c).first_or_initialize

p.category_id #rightfully returns 1

p.category #runs a query to reload the Category object
```

### Expected behavior
Since a Category object was passed into the where, `p.category` should already be in memory, and should not trigger an additional query.

### Actual behavior
Calling `p.category` triggers an additional query.

### System configuration
**Rails version**:5.0.0.1

**Ruby version**:2.3.3

**Comment by andreykul** [comment]
`c` and `p.category` are not the same object, this is why it loaded it again. There is no way for it to recognize it is the same record. The `where` just generates a query, it does not actually create the object. I see your point, You are saying that it should be smarters and make `p.`category` point to `c`

**Comment by maclover7** [comment]
Agree with @andreykul, I think it is the expected behavior for a new query to be generated when calling `p.category`.
