### ISSUE TITLE
Regression: Bigint change doesn't work for schema dump's of previous created application

### ISSUE THREAD

**Issue by eileencodes** [rails/rails#27374]
I was testing something with Rails 5 master and noticed the change to use bigint at primary keys has caused an issue when using the schema dump, for example in CI or in a bin/setup script.

If the application is created previous to upgrading to Rails 5 the schema dump does not properly handle the primary key. Because the migration itself has a compatibility layer the `auto_increment` is correctly applied.

```ruby
#https://github.com/rails/rails/blob/master/activerecord/lib/active_record/migration/compatibility.rb#L106-L122
class V5_0 < V5_1
  def create_table(table_name, options = {}) 
    if adapter_name == "PostgreSQL"
      if options[:id] == :uuid && !options[:default]
        options[:default] = "uuid_generate_v4()"
      end 
    end 

    # Since 5.1 Postgres adapter uses bigserial type for primary
    # keys by default and MySQL uses bigint. This compat layer makes old migrations utilize
    # serial/int type instead -- the way it used to work before 5.1.
    if options[:id].blank?
      options[:id] = :integer
      options[:auto_increment] = true
    end 

    super
  end 
end 
```

The schema dumper code, however, does not go through the compatibility layer and Active Record sees the `:id` has a type of `:integer` and has no `auto_increment` set so it gets set in the schema to a regular `:id`. Mysql though still knows it's a primary key so it will blow up when trying to insert data into the tables created.

```ruby
#https://github.com/rails/rails/blob/master/activerecord/lib/active_record/connection_adapters/mysql/schema_definitions.rb#L5-L11
def primary_key(name, type = :primary_key, **options)
  if type == :primary_key && !options.key?(:default)
    options[:auto_increment] = true
    options[:limit] = 8 
  end 
  super
end 
```

[I've created a test application](https://github.com/eileencodes/migration_bug_demo). First clone the repo and run bin/setup. Then checkout the Rails master branch and try to do bin/setup again.

You'll see the following error because AR didn'tmark the primary key as auto incrementing, the ID is set to nil:

```
ActiveRecord::NotNullViolation: Mysql2::Error: Field 'id' doesn't have a default value: INSERT INTO `posts` (`title`, `created_at`, `updated_at`) VALUES ('This is a title', '2016-12-15 19:22:00', '2016-12-15 19:22:00')
```

In the output you should also see the migration properly adds the `auto_increment` option because it's going through the compatibility layer

```
create_table(:posts, {:id=>:integer, :auto_increment=>true})`
```

but the schema dump version does not:

```
create_table("posts", {:id=>:integer, :force=>:cascade, :options=>"ENGINE=InnoDB DEFAULT CHARSET=utf8"})
```

I can try to look into this more this weekend but thought possibly someone else may know offhand how to fix this.

cc/ @jmccartie @sgrif @matthewd

**Comment by jmccartie** [comment]
@eileencodes 1) ARGH!  2) Thanks for the details. 

I wasn't aware schema dumper didn't use the compatibility layer. I'll defer to @sgrif or @matthewd on how best to proceed. I'm happy to put in the work to make sure this is fixed.

**Comment by maclover7** [comment]
Been playing around with this locally, and it seems like we're going to need some kind of a data storage layer between `ActiveRecord::SchemaDumper` and `ActiveRecord::Migration`, to store shared metadata. I'm thinking it might make sense to use `ActiveRecord:: InternalMetadata`, but then again there might be a place in the connection adapter API where this fits in better.

**Comment by eileencodes** [comment]
This is fixed 👍
