### ISSUE TITLE
[DOCS] Change ActiveModel::Type::Helpers to :nodoc: ?

### ISSUE THREAD

**Issue by MSP-Greg** [rails/rails#27385]
All of its namespace children are `:nodoc:`, and it contains no methods or constants.

No reason to have it appear in normal docs, which, at [api.rubyonrails.org](http://api.rubyonrails.org/classes/ActiveModel/Type/Helpers.html), shows all the files the namespace is defined in.

See also [ActiveModel::Type::Helpers](https://msp-greg.github.io/rails_master/ActiveModel/Type/Helpers.html)

**Comment by rafaelfranca** [comment]
Yes, lets change it to nodoc. Could you open a PR?

**Comment by MSP-Greg** [comment]
Mind if I use `:nodoc: all` on the four files?

IOW, remove `:nodoc` from the four namespace child objects, and add `# :nodoc: all` to the `module Helpers` line.

**Comment by rafaelfranca** [comment]
I think it is safer to use `:nodoc:` if we want to document something in the future we can just add the class in the namespace and document it without having to change all files that have `:nodoc: all`

**Comment by MSP-Greg** [comment]
Well, not quite.  `:nodoc:` is file based, so, if in the future someone wants to add a non `:nodoc:` class/module to the namespace, they don't have to change anything.

The old `:nodoc:` children will continue to be, and `ActiveModel::Type::Helpers` should appear because it would now have children that aren't `:nodoc:`....

Using `:nodoc: all` just allows one directive to make its associated object and that object's children (**in the file**) `:nodoc:`.  FWIW, `:nodoc: all` is used in Ruby Core & Std-Lib.

The doc system I'm working on (YardT2) will remove `ActiveModel::Type::Helpers` from docs iff every file referencing it shows it as `:nodoc:` (or `:nodoc: all`) and all its children are `:nodoc:`.

I'm, not positive about RDoc behavior regarding namespace parents and children across several files.

**Comment by rafaelfranca** [comment]
Thanks for the explanation. I think we can try it.
