### ISSUE TITLE
Rails/Rake commands exiting in production environment

### ISSUE THREAD

**Issue by peric** [rails/rails#27397]
### Steps to reproduce

I'm using Rails 5.0.0.1 (have just updated to 5.0.1.rc2) and I have problems with Rails/Rake commands while executing them (with whenever gem) in production. 

Commands are going through as they should, but each of those (have 4 cron jobs atm) finishes with SystemExit. Sometimes, there is an error message `NoMethodError: undefined method `from' for main:Object` and sometimes error says that some constants that I'm using are not available - depends on the task I'm executing. 

This is an example of that error (catched in Sentry) -> https://sentry.io/share/issue/3131303433382e313933303632343039/

As I said, task are successfully doing their work, but I get this kind of error every time.

I thought it has something to do with loading lib files in production (http://stackoverflow.com/questions/38198668/rails-5-load-lib-files-in-production), but I did this proposed changes and that also didn't work.

I also don't experience in development environment, and neither when I run those commands manually. So, it happens just on scheduled jobs (cron jobs) in production.

### Expected behavior

Tasks should finish without exiting and reporting errors.

### Actual behavior

Described above.

### System configuration
**Rails version**:
5.0.0.1

**Ruby version**:
2.2.2p95

**Comment by maclover7** [comment]
Hi @peric! Can you please provide a sample application that replicates the error you are seeing?

**Comment by peric** [comment]
Sure. The app is here -> https://github.com/moonleerecords/moonlee-website

**Comment by utilum** [comment]
@peric would you also paste a copy of your cron commands?

**Comment by peric** [comment]
Sure, @utilum, here are few examples from crontab.

```
# Begin Whenever generated tasks for: moonlee-website
0 0,6,12,18 * * * /bin/bash -l -c 'cd /release_directory/nevermind_that && bundle exec bin/rails runner -e production '\''Fetch images from Instagram'\'' >> /var/log/cron_log.log 2>&1'

0 0,6,12,18 * * * /bin/bash -l -c 'cd /release_directory/nevermind_that && RAILS_ENV=production bundle exec rake social:fetch_instagram --silent >> /var/log/cron_log.log 2>&1'

10 0,6,12,18 * * * /bin/bash -l -c 'cd /release_directory/nevermind_that && bundle exec bin/rails runner -e production '\''Fetch videos from Youtube'\'' >> /var/log/cron_log.log 2>&1'

10 0,6,12,18 * * * /bin/bash -l -c 'cd /release_directory/nevermind_that && RAILS_ENV=production bundle exec rake social:fetch_youtube --silent >> /var/log/cron_log.log 2>&1'

# End Whenever generated tasks for: moonlee-website
```

**Comment by utilum** [comment]
OK @peric, I don't get any unexpected errors launching these commands locally, but you say that neither do you, so no news there. The app you provided seems like it's your app, not something reduced to the bare-minimum in order to reproduce the issue -- what's usually meant by 'a sample app'. Then again, you are unable to narrow it down.
I suggest that you try to replicate your production environment as closely as possible, to be able to reproduce the error and trace it.
