### ISSUE TITLE
rails api with action cable

### ISSUE THREAD

**Issue by atussec** [rails/rails#27405]
### Steps to reproduce

(Guidelines for creating a bug report are [available
here](http://guides.rubyonrails.org/contributing_to_ruby_on_rails.html#creating-a-bug-report))

### Expected behavior
Tell us what should happen
as on the rails actioncable base is the documentation it stated that
```
 def find_verified_user
        if current_user = User.find_by_identity cookies.signed[:identity_id]
          current_user
        else
          reject_unauthorized_connection
        end
      end
```
### Actual behavior
Tell us what happens instead
so in my channel file i try to use this

```
   if current_user = User.find_by_identity cookies.signed[:identity_id]
       current_user
     else
       reject_unauthorized_connection
     end
```

but am getting this error

```
 
SyntaxError (/home/geniuskid/rails/chatty/app/channels/application_cable/connection.rb:13: syntax error, unexpected tIDENTIFIER, expecting keyword_then or ';' or '\n'
...= User.find_by_identity cookies.signed[:identity_id]
...                               ^
/home/geniuskid/rails/chatty/app/channels/application_cable/connection.rb:21: syntax error, unexpected keyword_end, expecting end-of-input):

```
### System configuration
**Rails version**:
rails 5.0.0
**Ruby version**:
ruby 2.3.1p112 (2016-04-26 revision 54768) [x86_64-linux]

**Comment by maclover7** [comment]
Hi @atussec! Can you post the whole file? I think there's a syntax error, which is what's causing the code error you're seeing.

**Comment by atussec** [comment]
here is it

`  identified_by :current_user
    
    def connect
        self.current_user = find_verified_user
        logger.add_tags 'ActionCable', "User #{current_user.id}"
    end
    
    protected
    
    def find_verified_user
        if current_user = User.find_by_identity cookies.signed[:identity_id]
            current_user
        else
            reject_authorized_connection
    
      end
    end`

**Comment by robin850** [comment]
Hi @atussec,

That's actually more a Ruby syntax problem than a Rails problem ; you just need to wrap the `find_by_identity` call with braces. You can reproduce this problem with this snippet for instance:

~~~ruby
def foo(arg); end

def bar
  if a = foo :baz
    a
  end
end
~~~

 I'm giving this a close but feel free to comment if I'm wrong, we can reopen then. Thanks for reporting anyway ! :-)
