### ISSUE TITLE
NotImplementedError on File.atomic_write

### ISSUE THREAD

**Issue by frankwong15** [rails/rails#27406]
### Steps to reproduce

Please refer to below:
[https://gist.github.com/frankwong15/a59f5e976140b2d377c4c1902bfbe63e](https://gist.github.com/frankwong15/a59f5e976140b2d377c4c1902bfbe63e)

### Expected behavior
It should ignore error on chmod and create a file

### Actual behavior
It raises NotImplementedError

### System configuration
**Rails version**: master
**Ruby version**: JRuby 9.1.6.0 with JRUBY_OPTS=-Xnative.enabled=false

**Comment by matthewd** [comment]
Thanks, but we don't accept feature requests on the issue tracker.

(And yes, "work with a [deliberately] broken ruby implementation" is a feature request.)

**Comment by guilleiguaran** [comment]
maybe this is related https://github.com/jruby/jruby/issues/3457?

Anyway I think this is a JRuby bug not a Rails one

**Comment by frankwong15** [comment]
Sorry, I don't agree. The root cause is that atomic_write assume you can always chown. Then people started rescue Errno::EPERM and Errno::EACCES. I think NotImplementedError should be rescued as well because on some Ruby implementation you cannot chown.

[https://github.com/rails/rails/commit/851f8c10235a0874f5e34b2c7b5544c33f89c022](https://github.com/rails/rails/commit/851f8c10235a0874f5e34b2c7b5544c33f89c022)
[https://github.com/rails/rails/commit/4d59832f29b0f98f0c8c4cc228e6d5d00a5a8ffd](https://github.com/rails/rails/commit/4d59832f29b0f98f0c8c4cc228e6d5d00a5a8ffd)
