### ISSUE TITLE
Queries with a association named same as specified FK causes SystemStackError

### ISSUE THREAD

**Issue by DanAndreasson** [rails/rails#27409]
### Steps to reproduce
1. Have a table `matches` with a column named `winner` (without _id).
2. Have a model with `belongs_to :winner, class_name: "Match", foreign_key: :winner`
3. Do a where query `Match.where winner: team` 

```Ruby
begin
  require "bundler/inline"
rescue LoadError => e
  $stderr.puts "Bundler version 1.10 or later is required. Please update your Bundler"
  raise e
end

gemfile(true) do
  source "https://rubygems.org"
  # Activate the gem you are reporting the issue against.
  gem "activerecord", "5.0.0"
  gem "sqlite3"
end

require "active_record"
require "minitest/autorun"
require "logger"

# Ensure backward compatibility with Minitest 4
Minitest::Test = MiniTest::Unit::TestCase unless defined?(Minitest::Test)

# This connection will do for database-independent bug reports.
ActiveRecord::Base.establish_connection(adapter: "sqlite3", database: ":memory:")
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :teams, force: true do |t|
  end

  create_table :matches, force: true do |t|
    t.integer :winner
  end
end

class Team < ActiveRecord::Base
end

class Match < ActiveRecord::Base
  belongs_to :winner, class_name: "Team", foreign_key: :winner
end

class BugTest < Minitest::Test
  def test_association_stuff
    team = Team.create!
    match = Match.create! winner: team

    Match.where winner: team
  end
end

```
### Expected behavior
Rather self explanatory I think. Return a collection where the winner is equal to *team*. This was the case in previous versions (at least 4.2)

### Actual behavior
Causes `SystemStackError: stack level too deep`

### System configuration
**Rails version**:
5.0.0.1

**Ruby version**:
2.3.0

I worked around it by renaming the column `winner` to `winner_id` and not specifying the foreign_key.

**Comment by alexcameron89** [comment]
I believe this is a duplicate of https://github.com/rails/rails/issues/26778.

**Comment by DanAndreasson** [comment]
Yeah that seems correct. Missed that one. Thank you @alexcameron89!
