### ISSUE TITLE
“Expected string default value for `--jbuilder`; got true (boolean)” error in a new rails project with a previously used name

### ISSUE THREAD

**Issue by r3id** [rails/rails#27415]
I am starting a new project, and have done this meany times now. However, this is the first time I have run into this issue!

I created the app as normal `rails new myapp -d postgresql`

I've created the DB using `rails db:create` and ran the site `rails s`. It all works, and I see the Rails welcome/holding page.

Now I start to create my models, `rails g model user` for example. And I get the following error...

```
Expected string default value for `--jbuilder`; got true (boolean)
      invoke  active_record

The name 'User' is either already used in your application or reserved by Ruby on 
Rails. Please choose an alternative and run this generator again.
```

Ok, that's fair enough, I understand the error message. So I thought I would try to create a different model. When I run `rails g model testing`, and I get...

```
Running via Spring preloader in process 31815
Expected string default value for '--jbuilder'; got true (boolean)
      invoke  active_record
      create    db/migrate/20161217171019_create_testings.rb
      create    app/models/testing.rb
      invoke    test_unit
      create      test/models/testing_test.rb
      create      test/fixtures/testings.yml
```

Has anyone else had this issue and if so any ideas why? I have tried running bundle install and bundle update with no luck. I have also tried setting the thor version as mentioned in this post

I am using Rails 5.0.0.1 and Ruby 2.3.1. I noticed this has only just started happening since I did an update to macOS to 10.12.1 I am not sure if they are related.

--- 

I started to test this out further. And I created a couple of different projects `rails new testapppg` and `rails new testapp-pg`.

On both of apps I changed the thor gem `gem 'thor', '0.19.1'`. I then went on to run bundle update, and create the DB. Now both of these projects created the test models when running` rails g model sample`.

Cool! So that is the fix. So I went back and recreated my `myapp` app from scratch as i did before, updated the thor gem, created the DB. Now when I went to create the model I got the errors again!?

So my next question is does Rails cache project names? which is why the new projects worked fine, but the one with the previously used name causes the error?

**Comment by oyeanuj** [comment]
Also getting this on Rails 4.2.7, on upgrading from 4.2.6 to 4.2.7. Seems like thor started throwing that warning on 0.19.3 and it needs to be fixed here?

**Comment by rafaelfranca** [comment]
This is a thor problem with the jbuilder gem. Both are fixed now, but not released. This is not a Rails issue.

**Comment by oyeanuj** [comment]
@rafaelfranca It seems to be a railties issue as well. I'm not using JBuilder at all.

```sh
→ rails --version
Expected string default value for '--rc'; got false (boolean)
Rails 4.2.7.1
```

**Comment by kaspth** [comment]
@oyeanuj that error is coming from Thor, lock it to an earlier version for now and it goes away 😁
