### ISSUE TITLE
after_commit callbacks not running when an action is specified

### ISSUE THREAD

**Issue by wolfemm** [rails/rails#27410]
The problem seems to be that [transaction_include_any_action?](https://github.com/rails/rails/blob/5-0-stable/activerecord/lib/active_record/transactions.rb#L458) is being passed a list of strings but the case statement expects symbols.

Overriding `transaction_include_any_action?` and calling `to_sym` on the action in the case statement makes everything work as expected, but the fact that this doesn't appear to have been brought up before makes me uncertain.

### Steps to reproduce

1. Model:

```
class User < ActiveRecord::Base
  after_commit :callback_method, on: :create

  def callback_method
    puts "`callback_method` called"
  end
end
```

2. Run `User.create(username: "test")`

### Expected behavior
`callback_method` should be run.

### Actual behavior
`callback_method` is not run.

### System configuration
**Rails version**: 5.0.0.1

**Ruby version**: 2.3.1p112

**Comment by rafaelfranca** [comment]
Could you create a reproduction script with this template https://github.com/rails/rails/blob/master/guides/bug_report_templates/active_record_master.rb?

**Comment by wolfemm** [comment]
After further investigation, it turns out an ill conceived monkey patch in my app affecting arrays was to blame.

Thank you for your time.
