### ISSUE TITLE
= render @collection || 'empty_list' when @collection is empty

### ISSUE THREAD

**Issue by fabrouy** [rails/rails#27420]
### Steps to reproduce

```ruby
# controller
def index
  @foos = Foo.none
end

# view
= render @foos || "no_foos"
```

### Expected behavior
`no_foos` partial should be rendered

### Actual behavior
`no_foos` partial is not rendered unless `@foos = nil`

### System configuration
**Rails version**: 4.1.15

**Ruby version**: 2.2.4

**Comment by georgeclaghorn** [comment]
This isn't a bug. `@foos` is not `nil` or `false`, so the result of `@foos || "no_foos"` is `@foos`.

**Comment by guilleiguaran** [comment]
as @georgeclaghorn said, this isn't a bug, that is how Ruby works :)
