### ISSUE TITLE
Rails upgrade from 5.0.0.1 to 5.0.1 breaks ActionCable WSS Upgrade

### ISSUE THREAD

**Issue by kobaltz** [rails/rails#27421]
### Steps to reproduce

Upgraded existing application on Rails 5.0.0.1 to Rails 5.0.1. No other changes were made. Websocket connected and were able to switch protocol in development environment without any issues when on 5.0.0.1. However, when pushed to production, the websockets would not switch protocols.

### Expected behavior
Request URL:wss://www.example.com/cable
Request Method:GET
Status Code:101 Switching Protocols

### Actual behavior
ActionCable  WebSocket never switches protocol

### System configuration
 - Rails 5.0.1
 - Ruby 2.3.3
 - Passenger 5.1.0
 - Nginx Config
```
    server {
      listen 443 ssl;
      server_name example.com;
      ssl_certificate /home/deploy/example/ssl.crt;
      ssl_certificate_key /home/deploy/example/ssl.key;
      root /home/passenger/example/public;
      passenger_enabled on;
      passenger_min_instances 8;

      location ~*  \.(jpg|jpeg|png|gif|ico|css|js)$ {
        expires 365d;
      }

      location /cable {
        passenger_app_group_name example_action_cable;
        passenger_force_max_concurrent_requests_per_process 0;
      }
    }
```

 - production.rb
```
  config.action_cable.mount_path = Rails.application.secrets.action_cable_wss
  # action_cable_wss secret is /cable
  config.action_cable.allowed_request_origins = ['https://www.example.com', 'https://example.com']
```

**Comment by Nekromancer** [comment]
Exactly same problem with me

**Comment by eileencodes** [comment]
Thanks for the report @kobaltz. Would it be possible for you to make an example application that demonstrates this issue so we can investigate?

**Comment by kobaltz** [comment]
So a bit more background, within my dev environment, I use `puma-dev` to manage my Rails apps (which uses puma instead of passenger).

Here is a super basic example app.

Start the app with `rails s` (default puma) and the WS connects just fine.

Start the app with `passenger start` and the WS upgrade request fails.

[https://github.com/kobaltz/rails-example-issue-27421](https://github.com/kobaltz/rails-example-issue-27421)

**Comment by guilleiguaran** [comment]
@FooBarWidget you might be interested on this.

**Comment by FooBarWidget** [comment]
Yes we are looking into this, thanks for the heads-up.

**Comment by OnixGH** [comment]
@eileencodes we've also reproduced this with the Rails 5 [Live comments example](https://github.com/rails/actioncable-examples).

**Comment by StephaneRob** [comment]
by changing
```ruby
# action_cable/connection/stream.rb
written = @rack_hijack_io.write_nonblock(data, exception: false)
```
to 
```ruby
# action_cable/connection/stream.rb
written = @rack_hijack_io.write_nonblock(data)
```
actioncable works well again.

https://github.com/phusion/passenger/blob/stable-5.1/src/ruby_supportlib/phusion_passenger/utils/unseekable_socket.rb#L120

**Comment by FooBarWidget** [comment]
@StephaneRob I *just* arrived at the same conclusion too. :)

A fix is on its way.

**Comment by FooBarWidget** [comment]
The Rails team may also want to fix the fact that any errors inside ActionCable::Connection::Stream#write may be silently swallowed.

ActionCable::Connection#write is called from ActionCable::Connection::ClientSocket#write, which catches any errors and emits them over the socket using `emit_error`. But if it is the socket write itself that fails, then `emit_error` fails as well, causing the error to be swallowed. More sophisticated error handling may be appropriate here.

**Comment by Nekromancer** [comment]
@FooBarWidget Thanks for fixing that! Do you know when can we expect release of version 5.1.1?

**Comment by FooBarWidget** [comment]
We're trying to release it today.

**Comment by kobaltz** [comment]
`Passenger 5.1.1` does appear to have addressed this issue! Thank you!
