### ISSUE TITLE
rails test command fails with warning to run bundle install after upgrade from 5.0.0.1 to 5.01

### ISSUE THREAD

**Issue by ccasabona** [rails/rails#27428]
### Steps to reproduce

run command rails test

### Expected behavior
entire test suite should run

### Actual behavior
receive message:
Could not find concurrent-ruby-1.0.3 in any of the sources
Run `bundle install` to install missing gems.

running bundle install does not resolve issue
running rake test works fine
cannot run individual tests
development mode boots and runs fine

### System configuration
rails 5.0.1
ruby 2.3.3
OS Sierra
**Ruby version**:

**Comment by prathamesh-sonpatki** [comment]
Can you upload a sample application on Github that reproduces the issue? Thanks.

**Comment by kaspth** [comment]
I can't reproduce this with a barebones new Rails 5.0.1 app, e.g.:

```
$ rails new test_test
$ cd test_test
$ bin/rails db:migrate
$ cat test/models/running_test.rb
require 'test_helper'

class RunningTest < ActiveSupport::TestCase
  test "running?" do
    flunk
  end
end
$ bin/rails test
Running via Spring preloader in process 74226
Run options: --seed 23022

# Running:

F

Failure:
RunningTest#test_running? [/Users/kasperhansen/Documents/code/test_test/test/models/test_test.rb:5]:
Epic Fail!

bin/rails test test/models/test_test.rb:4

Finished in 0.003566s, 280.4358 runs/s, 280.4358 assertions/s.
```

**Comment by ccasabona** [comment]
Kasper,

I can’t reproduce it from a new bare bones 5.01 app either, so it will take more investigation to see why this error is occurring on the main app.

Charlie

**Comment by ccasabona** [comment]
Follow up:
deleted gemfile.lock and ran bundle install
running command rails test got this error:
Your bundle is locked to activesupport (5.0.1), but that version could not be found in any of the sources listed in your Gemfile....

Needless to say, activesupport 5.0.1 is present in the gemfile with permissions set correctly.  

Upon removing spring from the bundle, the rails test command works correctly.

**Comment by ccasabona** [comment]
Solved problem for now by reinstalling spring gem and using version 1.7.2.

**Comment by prathamesh-sonpatki** [comment]
Great!
