### ISSUE TITLE
5.0.0.1 -> 5.0.1 breaks .group(enum).count with PostgreSQL adapter

### ISSUE THREAD

**Issue by claudiob** [rails/rails#27438]
See bug report at https://gist.github.com/claudiob/5724f2c0aeaf59b356e3955359eee921

In short, if you have a `Post` model with an `integer` column "category" that acts as enum:

```ruby
class Post < ActiveRecord::Base
  enum category: %i(sport entertainment) # category is an integer in the PostgreSQL DB
end

Post.create! category: 'sport'
Post.create! category: 'entertainment'
```

and you group Post by category, the *key* of the returned Hash used to be the category **as an integer** under Rails 5.0.0.1:

```ruby
Rails.version # => 5.0.0.1
Post.group(:category).count # => {1=>1, 0=>1}
```

but under Rails 5.0.1 is now the category **as a string**:

```ruby
Rails.version # => 5.0.1
Post.group(:category).count # => {"sport"=>1, "entertainment"=>1}
```

Using `git bisect` I found that 9c28c54879d61ef95a3bc132ef9854f7ac5e9ec7 is the first bad commit.

To be honest, I like this new behavior better and it aligns with the other adapters.

However, it was a breaking change for my Rails app and, in principle, there shouldn't be breaking changes without warnings / deprecations / minor releases.

**Comment by rafaelfranca** [comment]
Are you sure that is the commit? It doesn't change anything in the framework.

**Comment by claudiob** [comment]
@rafaelfranca It's weird, but this is what I found.

I added the following file `activerecord/test/cases/adapters/postgresql/enum_group_test.rb` as a new test to rails/rails:

```ruby
require "cases/helper"

class EnumGroupTest < ActiveRecord::PostgreSQLTestCase
  class PostgresqlPost < ActiveRecord::Base
    enum category: %i(sport entertainment)
  end

  setup do
    @connection = ActiveRecord::Base.connection
    @connection.create_table("postgresql_posts", force: true) do |t|
      t.integer "category"
    end
  end

  teardown do
    @connection.drop_table "postgresql_posts", if_exists: true
  end

  def test_group_count_with_enum
    PostgresqlPost.create! category: 'sport'
    PostgresqlPost.create! category: 'entertainment'

    assert_equal PostgresqlPost.group(:category).count, {1=>1, 0=>1}
  end
end
```

Then first I checked out 9c28c54 (the first bad commit according to `git bisect`):

```sh
git:master~/code/rails$ git checkout 9c28c54 
Note: checking out '9c28c54'.
HEAD is now at 9c28c54... Override the github git source instead of changing manually all entries

git:(v5.0.0-271-g9c28c54)~/code/rails$ cd activerecord; ARCONN=postgresql  bundle exec ruby -Itest test/cases/adapters/postgresql/enum_group_test.rb; cd ..
Using postgresql
Run options: --seed 53850

# Running:

F

Finished in 0.066876s, 14.9530 runs/s, 14.9530 assertions/s.

  1) Failure:
EnumGroupTest#test_group_count_with_enum [test/cases/adapters/postgresql/enum_group_test.rb:23]:
--- expected
+++ actual
@@ -1 +1 @@
-{"entertainment"=>1, "sport"=>1}
+{1=>1, 0=>1}


1 runs, 1 assertions, 1 failures, 0 errors, 0 skips
```

And then I checked out the previous commit (the "last good one" according to `git bisect`):

```sh
git:(v5.0.0-271-g9c28c54)~/code/rails$ git checkout 9c28c54^
HEAD is now at 99c0cb5... 5-0-backport: activerecord/mysql2: Avoid setting @connection to nil, just close it (#26473)

git:(v5.0.0-270-g99c0cb5)~/code/rails$ cd activerecord; ARCONN=postgresql  bundle exec ruby -Itest test/cases/adapters/postgresql/enum_group_test.rb; cd ..
Using postgresql
Run options: --seed 19777

# Running:

.

Finished in 0.028566s, 35.0067 runs/s, 35.0067 assertions/s.

1 runs, 1 assertions, 0 failures, 0 errors, 0 skips
```

Am I doing something wrong?

**Comment by rafaelfranca** [comment]
You are doing it right, but it seems really weird to that commit to change this behavior. Only if it depends in a dependency that was updated in that commit.

**Comment by maclover7** [comment]
Looks like that commit also bumped the Arel version in Gemfile.lock from 7.1.1 to 7.1.2. Only code change commit in that release is https://github.com/rails/arel/commit/6982e6e6e3da977424b63c65a676b58447ff86c1.

**Comment by utilum** [comment]
I get the same failure with master that uses Arel 7.1.1, as well as 7.1.0 and 7.0.0.

**Comment by claudiob** [comment]
Investigating a little more, I found that if I checkout 99c0cb5 (the "last good commit" according to git bisect) and run `bundle update` then the test fails!

Therefore, the reason why 9c28c54 is the first bad commit might simply be because that commit updated Gemfile.lock for the first time in a while.

I'll keep on :female_detective:

**Comment by claudiob** [comment]
Aaaaand… after a long set of `git bisect` and `bundle update`, I finally found the real culprit! :male_detective:  

39f8402751 by @sgrif 

Once again… I do like this new behavior… I just think we should deal with the fact that it's a breaking change for people updating from 5.0.0.1 to 5.0.1.

**Comment by matthewd** [comment]
Per https://github.com/rails/rails/issues/25595#issuecomment-230071825, this was a bug fix.
