### ISSUE TITLE
Upgrading from Rails 5.0.0.1 to 5.0.1 increases import from local CSV from 3 to 94 minutes

### ISSUE THREAD

**Issue by stefankp** [rails/rails#27434]
I have a rake task which imports 38242 rows from a local CSV file. Even though it might not be the most efficient way, for each row `create!` is executed to create a new record. Just by updating Rails to 5.0.1, without changing anything else, the time to create these records increased tremendously. I couldn't find anything in the changelog that would indicate such an increase. 

Any ideas?

### The rake task basically looks like this

```
require 'csv'

namespace :csv do
  desc 'Import records from CSV file'
  task import: :environment do
    puts "#{Time.now}: Loading ..."

    csv_file = File.read(Rails.root.join('lib', 'assets', "data.csv"), encoding: Encoding::UTF_8)
    csv = CSV.parse(csv_file, headers: true)

    count = 0

    csv.each do |row|
      Record.create!(
        attribute1: row['attribute1'],
        attribute2: row['attribute2'],
        attribute3: row['attribute3'],
        attribute4: row['attribute4'],
        attribute5: row['attribute5']
      )

      count += 1
    end

    puts "#{Time.now}: Loaded #{count} rows."
  end
end

```

### Rails 5.0.0.1
Import in less than 3 minutes.
```
$ rake csv:import
2016-12-21 22:59:49 +0100: Loading ...
2016-12-21 23:02:37 +0100: Loaded 38242 rows.
```

### Rails 5.0.1
Import in almost 94 minutes.
```
$ rake csv:import
2016-12-22 08:32:49 +0100: Loading ...
2016-12-22 10:06:26 +0100: Loaded 38242 rows.
```

### System configuration
- Ruby 2.3.3
- Rails 5.0.1
- Puma 3.6.2
- Postgres 9.6
- Mac OS Sierra 10.12.2

**Comment by matthewd** [comment]
Can you reproduce the problem with a [standalone script](https://github.com/rails/rails/blob/master/guides/bug_report_templates/active_record_gem.rb)?

**Comment by stefankp** [comment]
Here is the script: https://gist.github.com/stefankp/4d0ac8d02e264086e0e36ee2c2543fa4

Run it with `gem "activerecord", "5.0.0"` and afterwards with `gem "activerecord", "5.0.1"`. Change the `1000.times` to any number you like. 

I left out the CSV import and just tested creating records. Here are my results:

#### 1000 records
- **5.0.0**: Finished in 1.071250s, 0.9335 runs/s, 1.8670 assertions/s.
- **5.0.1**: Finished in 3.142346s, 0.3182 runs/s, 0.6365 assertions/s.

#### 5000 records
- **5.0.0**: Finished in 5.548328s, 0.1802 runs/s, 0.3605 assertions/s.
- **5.0.1**: Finished in 55.538117s, 0.0180 runs/s, 0.0360 assertions/s.

####10000 records
- **5.0.0**: Finished in 10.070713s, 0.0993 runs/s, 0.1986 assertions/s.
- **5.0.1**: Finished in 273.957032s, 0.0037 runs/s, 0.0073 assertions/s.

**Comment by matrix9180** [comment]
I'll try to bisect this & report back.

**Comment by matrix9180** [comment]
15ddd5179c746a2201b9805edf0764f515da8d7a is the first bad commit
commit 15ddd5179c746a2201b9805edf0764f515da8d7a
Author: Sean Griffin <sean@seantheprogrammer.com>
Date:   Thu Sep 29 14:57:31 2016 -0400

    Don't skip in-memory insertion of associations when loaded in validate
    
    This was caused by 6d0d83a33f59d9415685852cf77818c41e2e2700. While the
    bug it's trying to fix is handled if the association is loaded in an
    after_(create|save) callback, it doesn't handle any cases that load the
    association before the persistence takes place (validation, or before_*
    filters). Instead of caring about the timing of persistence, we can just
    ensure that we're not double adding the record instead.
    
    The test from that commit actually broke, but it was not because the bug
    has been re-introduced. It was because `Bulb` in our test suite is doing
    funky things that look like STI but isn't STI, so equality comparison
    didn't happen as the loaded model was of a different class.
    
    Fixes #26661.

**Comment by matrix9180** [comment]
Here's what I used to reach that:
https://gist.github.com/matrix9180/d8925937d04ca1b764dcf06909862a26

**Comment by stefankp** [comment]
@matrix9180 the runtime is flexible. It is around 1 second for 1000 records, so can also be 0.9 on `5.0.0` and 2. on `5.0.1`.

**Comment by kaspth** [comment]
I take it this `include?` becomes slower and slower as the collection grows (plus it's called each time through the loop): https://github.com/rails/rails/commit/15ddd5179c746a2201b9805edf0764f515da8d7a#diff-20f545c453ee24942b6f7ae565e9e369R659

**Comment by matrix9180** [comment]
@stefankp Yeah I just hacked out the script for it quickly as it was consistently around 1.7 seconds on my machine with 5.0.0.1. 
@kaspth looks that way to me.
