### ISSUE TITLE
Can not parsing "&lt" to "<"

### ISSUE THREAD

**Issue by kunkaiHuang** [rails/rails#27433]
hello friends!,in rails haml project.Can not parsing "&lt" to "<",how should i due it? thanks you very much!
`- title "#{@project.name}`
the "@project.name" is `"<water>"`,and i found the title is "&lt water &gt"

**Comment by matthewd** [comment]
Please use the mailing list or StackOverflow for questions/help, where a wider community will be able to help you. We reserve the issues tracker for issues only.
