### ISSUE TITLE
Journey parser should use frozen string literals

### ISSUE THREAD

**Issue by SamSaffron** [rails/rails#27440]
At the moment jouney parser does not have the comment

```
# frozen_string_literal: true
```

at the top. 

This means that lines like this: 

https://github.com/rails/rails/blob/master/actionpack/lib/action_dispatch/journey/parser.rb#L177

end up causing retention of 4961 objects on boot for Discourse. 

Is there anything stopping us adding `# frozen_string_literal: true` to the parser?

**Comment by SamSaffron** [comment]
also, it seems 

```
SLASH = Slash.new('/')
def _reduce_15(val, _values)
  SLASH
end
```

makes much more sense than:

```
def _reduce_15(val, _values)
  Slash.new('/')
end
```

**Comment by maclover7** [comment]
cc @tenderlove @pixeltrix

**Comment by SamSaffron** [comment]
also ... scanner.rb has tons to win with frozen string literals... counting about 2500 retained strings there.

**Comment by matthewd** [comment]
Looks like a Slash singleton would obviate a change in the parser.

I see no string literals in [scanner.rb](https://github.com/rails/rails/blob/fd63aa02289d64e9d14fe56723f1de64bca3bb1f/actionpack/lib/action_dispatch/journey/scanner.rb) other than the args to `tr` :confused:

**Comment by SamSaffron** [comment]
@matthewd  yeah that `tr` is called and retained about 2500 in our app.  I guess this change would cut down on 5000 or so allocations. 

I tested on local and a slash singleton seems to work fine, app boots routes seem to work. 

Couldn't, https://github.com/rails/rails/blob/fd63aa02289d64e9d14fe56723f1de64bca3bb1f/actionpack/lib/action_dispatch/journey/parser.y#L33 simply be changed to 

```
SLASH              { ::ActionDispatch::Journey::Parser::SLASH }
```
or something along those lines?

**Comment by matthewd** [comment]
Surely the result of the tr is being retained, not the throw-away literal arguments.

Yep, that slash change sounds fine.

**Comment by SamSaffron** [comment]
yeah retention is absolutely a result of the transposed string but can
avoid allocating 5000 objects here, sounds like an easy win by just
freezing "" '\\'

**Comment by matthewd** [comment]
I just had a look at this, and freezing the slash singleton reveals some relevant-sounding mutation on `memo`. Even though we're not currently doing any compilation in parallel here (which is presumably why it still works for you), I'd rather pay the allocations than explicitly depend on that fact.

I haven't looked into the use of that attribute, though.. particularly given how little Slash does, maybe it could be skipped / worked around.

I've done the easy ones in 4273ab34c484f38fa9f77d133cd83256d721e7c8.
