### ISSUE TITLE
ActiveRecord::JDBCError: org.postgresql.util.PSQLException: ERROR: multiple primary keys for table "schema_migrations" are not allowed

### ISSUE THREAD

**Issue by rosunshrestha** [rails/rails#27444]
### Steps to reproduce
When postgres db with jruby is used with rails 5 it causes following problem. However same works well with rails 4.X versions/

(Same bug report is also [available
here](https://github.com/jruby/activerecord-jdbc-adapter/issues/734))

### Expected behavior
rake db:migrate should run pending migration.

### Actual behavior
gives an error
`Position: 75: CREATE TABLE "schema_migrations" ("version" character varying PRIMARY KEY PRIMARY KEY  PRIMARY KEY)`

### System configuration
**Rails version**: 5.0.1 (also tried in several rails 5 version)

**Ruby version**: jruby-9.1.6.0 (also tried with jruby 9.1.2.0)

**Comment by rafaelfranca** [comment]
The jdbc adapter is not developed by the rails team so it is better to report the issue there.

**Comment by Helsioufy** [comment]
Hey guys, I am getting this error however with a different table:
`ActiveRecord::StatementInvalid: ActiveRecord::JDBCError: org.postgresql.util.PSQLException: ERROR: multiple primary keys for table "ar_internal_metadata" are not allowed`

I specified this in my Gemfile: `gem 'activerecord-jdbcpostgresql-adapter', platforms: :jruby, github: 'jruby/activerecord-jdbc-adapter', branch: 'rails-5'` and still having the same issue.

**Rails verision**: 5.0.0
**Jruby version**: 9.1.5.0
