### ISSUE TITLE
Unable to pass parameters to rails server command

### ISSUE THREAD

**Issue by JohnMerlino2** [rails/rails#27445]
I am testing the ransack demo app from github. The app is using rails 5.1.0.alpha. Unfortunately, it appears this version of Rails is broken. I am unable to pass any parameters to the call rails server:

```
$ rails server -b 0.0.0.0
/Users/myuser/.rvm/gems/ruby-2.3.1@ransack_demo/gems/thor-0.19.4/lib/thor/base.rb:484:in `handle_argument_error': ERROR: "rails server" was called with arguments ["-b", "0.0.0.0"] (Thor::InvocationError)
Usage: "bin/rails server [options]"
```

Is there some kind of ref or branch I can update to?

When I try downgrading Rails, I get an error at this line of code:

<%= tag.h1 'Search Users' %>

What is tag? Is that a new feature of rails?

**Comment by rafaelfranca** [comment]
Yes, it is a new version of Rails. And no there is no ref you can use. The master branch is unstable and we don't give support for things that are broken with it.
