### ISSUE TITLE
Running specific rails version

### ISSUE THREAD

**Issue by ivanovaleksey** [rails/rails#27456]
Hi.
I have rails `5.0.0.1` and `4.2.7.1` installed.
I am using `rbenv` to manage multiple ruby versions.

I would like to create new `4.2.7.1` rails app and I use the following command
`rails _4.2.7.1_ new to_remove`

As far as I know this `_4.2.7.1_` should tell rubygems which version to use. And it seems to work well since rubygems resolves binary path to
`/Users/aleksey/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/railties-4.2.7.1/bin/rails`

The [file](https://github.com/rails/rails/blob/v4.2.7.1/railties/bin/rails) is very short
```
#!/usr/bin/env ruby

git_path = File.expand_path('../../../.git', __FILE__)

if File.exist?(git_path)
  railties_path = File.expand_path('../../lib', __FILE__)
  $:.unshift(railties_path)
end
require "rails/cli"
```

In my case `git_path` is equal to
 ```
/Users/aleksey/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/.git
```
 and `File.exist?(git_path)` returns false. 
So `.../railties-4.2.7.1/lib` folder is not pushed to `$LOAD_PATH`.
And `require "rails/cli"` finds `.../railties-5.0.0.1/lib/rails/cli.rb` and loads it.

That is why I have
```
rails _4.2.7.1_ --version
# Rails 5.0.0.1
```

Is it something wrong with my environment or am I doing something wrong?
Is there any way to run specific rails version?

Thank you.

**Comment by matthewd** [comment]
The rubygems shim in `~/.rbenv/versions/2.3.3/bin/rails` should set the chosen version (and thereby set up the load path) before the distributed file is invoked.

https://github.com/rubygems/rubygems/pull/1527 may be relevant; check you're using the latest version of rubygems.

**Comment by ivanovaleksey** [comment]
Thank you @matthewd.
I was running rubygems `2.5.2`. Updating rubygems solves the problem.

But my `~/.rbenv/versions/2.3.3/bin/rails` is still the same.
Seems like the problem was in rubygems internals.

Thanks once again.

**Comment by hallelujah** [comment]
@matthewd @ivanovaleksey I am still encountering this issue

```
$ gem --version
2.6.10

$ rails _4.2.7.1_ -v
5.0.1
```
