### ISSUE TITLE
params from cookies in routes.rb

### ISSUE THREAD

**Issue by eiked** [rails/rails#27453]
I'd like to suggest an enhancement for routes:
- params may also come from cookies
- I'd like to declare and handle them in routes
- they shall not be query parms in the generated urls

I think about cookies like a preferences,
set in the browser by the individual user.

But I don't want to explode the url space of my site.

So I'd like to hide the users preferences (saved in cookies)
but then, these are params for generating a page.
(and I want to declare that difference once in routes)

Let's see what we could do (my first try)

- routes: cookies:  map in declared cookies into params
- routes: drop: remove params from url generation
- routes: preferences: (both of the above combined)

---
It's all about context.
Let's make this easy!
(more to come)
~eike

**Comment by prathamesh-sonpatki** [comment]
Please use rails-core mailing list for feature requests. Github issue tracker is for bugs only.

Thanks!
