### ISSUE TITLE
Adding a manipulated Activesupport::Duration to dates gives unexpected result

### ISSUE THREAD

**Issue by vmeyet** [rails/rails#27457]
### Bug

Adding a manipulated Activesupport::Duration to dates gives unexpected result

### Steps to reproduce:

```ruby
[1] pry(main)> pry(main)> d = Date.parse('1 Jan 2017')
=> Sun, 01 Jan 2017
[2] pry(main)> d + 12.hours == d + 2 * 6.hours
=> false
[3] pry(main)> d + 12.hours
=> Sun, 01 Jan 2017 12:00:00 UTC +00:00
[4] pry(main)> d + 2 * 6.hours
=> Wed, 13 Apr 2135
```

### Expected behavior

I think it's safe to expect that `date + 2 * 12.hours` gives the same result as `date + 24.hours`

### Actual behavior

This is not equal. However this works fine with time/time with zone when not around daylight saving, else the same bug is present.

### Suspect

`2 * 12.hours` is converted to a number of seconds as an integer and then added to the date. The date coerce/convert the integer into a number of days and then add it.

### System configuration

Rails version: 5.0.0

Ruby version: 2.3.1

**Comment by maclover7** [comment]
Hi @vmeyet! Did this work for you in previous versions of Rails?

**Comment by vmeyet** [comment]
@maclover7, I started rails at version 3.2.0 and it was already present (re-tested today).

I opened this because this issue because I stumbled upon a bug introduced by this, and it took me some time to find out the bottom of it.

I think this is deeply related to the fact that multiplication with a scalar on `ActiveSupport::Duration` yields an `Integer`.

```ruby
[1] pry(main)> Date.today
=> Fri, 30 Dec 2016
[2] pry(main)> Date.today + 1 # core ruby spec (https://ruby-doc.org/stdlib-2.4.0/libdoc/date/rdoc/Date.html#2B-method)
=> Sat, 31 Dec 2016
[3] pry(main)> 1.second.class
=> ActiveSupport::Duration
[4] pry(main)> Date.today + 1.second # Addition goes well because we're adding a Date and a Duration
=> Fri, 30 Dec 2016 00:00:01 UTC +00:00
[5] pry(main)> (1 * 1.second).class
=> Integer
[6] pry(main)> Date.today + (1 * 1.second) # Addition goes well because we're adding a Date and an Integer
=> Sat, 31 Dec 2016
```

**Comment by al2o3cr** [comment]
@vmeyet There's a fundamental asymmetry in how operators work in Ruby - `1 * 1.second` is really doing `1.send(:*, 1.second)` which dispatches to the `*` operator for `Integer`. Swapping the two operands produces an entirely different method call - `1.second * 1` dispatches as `1.second.send(:*, 1)`, which dispatches to the `*` on `Duration`.

The second form there works correctly. I don't know of a good way to fix the first form, short of monkey-patching over the arithmetic operations for core types - which would be catastrophic to performance.

**Comment by pixeltrix** [comment]
@al2o3cr actually neither form works correctly since they both result in a seconds value which when added to a Date instance isn't right. We should be able to do something with `coerce` makes the result a duration and not an integer.

**Comment by vmeyet** [comment]
@al2o3cr,

@pixeltrix is right. Look at the following:

```ruby
[1] pry(main)> Date.today
=> Mon, 02 Jan 2017
[2] pry(main)> Date.today + (1 * 1.second)
=> Tue, 03 Jan 2017
[3] pry(main)> Date.today + (1.second * 1)
=> Tue, 03 Jan 2017
```

As mentionned there is a `coerce` method doing just what is needed (dimension/class conversion before operations). It's used with brio in the core ruby class `Matrix` (https://github.com/ruby/ruby/blob/ruby_1_9_3/lib/matrix.rb#L1275-L1282) for matrix multiplication with scalar.

Here is a pseudo code of what it could look like

```ruby
module ActiveSupport
    class Scalar
        attr_reader :value
        def initialize(val)
            @value = val
        end

        # implement stuff here ...

        def *(other)
            # reverse the multiply operation and handle it within the Duration class
            return other * self if other.is_a?(Duration)
            # other handlings or raise exception
        end

        # delegate everything to Numeric
        def method_missing(name, *args, &blk)
           ret = value.send(name, *args, &blk)
           ret.is_a?(Numeric) ? Scalar.new(value) : value
        end
    end

    class Duration
        def coerce(other)
            case other
            when Numeric
                [Scalar.new(other), self] # cast any Numeric into a Scalar that we control
            else
                raise TypeError, "#{self.class} can't be coerced into #{other.class}"
            end
        end

        def *(other)
            other = Scalar.new(other) if other.is_a?(Numeric)
            raise TypeError unless other.is_a?(Scalar)
            Duration.new(value * other.value, @parts.map { |part| [part[0], part[1] * other.value] })
        end
    end
end



### EX:

[1] pry(main)> 1.second + 4.minutes # old addition is still working
=> 4 minutes and 1 second
[2] pry(main)> 1.second * 4 # Duration * Numeric gives a Duration
=> 4 seconds
[3] pry(main)> 5 * 1.second # Numeric * Duration gives a Duration
=> 5 seconds
[4] pry(main)> Date.today
=> Mon, 02 Jan 2017
[5] pry(main)> Date.today + (1 * 1.second)
=> Mon, 02 Jan 2017 00:00:01 UTC +00:00
[6] pry(main)> Date.today + (1.second * 1)
=> Mon, 02 Jan 2017 00:00:01 UTC +00:00
```

Of course, I'm missing a lot of details due to rails internal and it's probably breaking a lot of code doing so, but it just a glimpse of what it could look like.

**Comment by al2o3cr** [comment]
@vmeyet That's what I get for asserting the behavior of code I didn't actually run. :)

TIL about the `coerce` method & associated plumbing. [Here's a writeup I found useful](https://www.mutuallyhuman.com/blog/2011/01/25/class-coercion-in-ruby)
