### ISSUE TITLE
Asking permission for docrails

### ISSUE THREAD

**Issue by riseshia** [rails/rails#27452]
Hi, I'm shia, who is maintainer of Korean version, contributor of Japanese, Rails Guides.
I'm sorry to open this here, but I can't find proper place...
if someone who read thinks it's not proper, please let me know where I could ask about this.

so, here is my main topic.
Please give me the permission for docrails, It's really hard to maintain translation with rails repository.
It's heavy to work with as well as sometime, upstream break deploy process for translation. ;)

furthermore, I find some fix of railsguides during updating translation, please let me contribute easier. Here is somethings I did:

- https://github.com/rails/rails/pull/26938
- https://github.com/rails/rails/pull/26365
- https://github.com/rails/rails/pull/26329
- https://github.com/rails/rails/pull/26267

Thanks to read :)

**Comment by maclover7** [comment]
cc @rafaelfranca @fxn

**Comment by rafaelfranca** [comment]
Done

**Comment by riseshia** [comment]
Thanks 👍
