### ISSUE TITLE
activesupport-5.0.1 ERROR

### ISSUE THREAD

**Issue by menjxo** [rails/rails#27460]
### Expected behavior
the terminal should only have a message that will tell the user how to terminate the rails app.

### Actual behavior
But then again this is what happened
`/Users/Menj/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/activesupport-5.0.1/lib/active_support/xml_mini.rb:51: warning: constant ::Fixnum is deprecated
/Users/Menj/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/activesupport-5.0.1/lib/active_support/xml_mini.rb:52: warning: constant ::Bignum is deprecated
`

### System configuration
**Rails version - 2.4.0**:

**Ruby version - 5.0.1**:

**Comment by prathamesh-sonpatki** [comment]
This is not an error, it is a warning about things deprecated in Ruby 2.4 It will be fixed in Rails 5.0.2.

Thanks!

**Comment by menjxo** [comment]
Thanks sir!
