### ISSUE TITLE
Activesupport-5.0.1 not compatible with Ruby 2.4.0, few deprecations

### ISSUE THREAD

**Issue by craft37** [rails/rails#27461]
activesupport-5.0.1/lib/active_support/xml_mini.rb:51: warning: constant ::Fixnum is deprecated
/activesupport-5.0.1/lib/active_support/xml_mini.rb:52: warning: constant ::Bignum is deprecated
/activesupport-5.0.1/lib/active_support/core_ext/numeric/conversions.rb:138: warning: constant ::Fixnum is deprecated

### Actual behavior
Starting server

### System configuration
**Rails version**: 5.0.1
**Ruby version**: 2.4.0

**Comment by matthewd** [comment]
#27458

**Comment by kikonen** [comment]
Is there coming up 5.0.2 release including fixes?

**Comment by jeremy** [comment]
Yes, 5.0.2 is next on deck.
