### ISSUE TITLE
StackOverflowError when method_missing gets called

### ISSUE THREAD

**Issue by kalsan** [rails/rails#27481]
### Steps to reproduce
In our deeply nested hierarchy of our own libraries, attempt to call an inexisting method in development mode.

### Expected behavior
`NoMethodError`

### Actual behavior
`StackOverflowError`

### System configuration
**Rails version**: 5.0.1.rc2

**Ruby version**: jruby  9.1.6.0 (2.3.1) 2016-11-09 0150a76 Java HotSpot(TM) 64-Bit Server VM 25.112-b15 on 1.8.0_112-b15 +jit [linux-x86_64]

I described the problem in detail in [this StackOverflow question](http://stackoverflow.com/questions/41363626/how-to-debug-a-bug-in-rails-that-causes-a-stackoverflow-in-method-missing/41363976#41363976)

We found out that there was code removed in commit 6b543166f7b0fd5712ffe831dad31d34f6de5dcd and indeed see [the build fails](https://github.com/rails/rails/commits/5-0-stable/actionpack/lib/action_controller/metal/rescue.rb) from there.

That might be a bug right there. Since it only happens in the development mode (where auto(re)loading is enabled), this might be a bug related with autoloading.

**Comment by matthewd** [comment]
Can you reproduce the problem with a demo application?

**Comment by kalsan** [comment]
Since the problem happens in combination with library that I do not own, I'm afraid I cannot publish the code.

However, we found out why this is happening: When the exception is it's own cause (which apparently is possible; we yet have to find out why this is happening), the method `rescue_with_handler` in `activesupport-5.0.1.rc2/lib/active_support/rescuable.rb` goes into an infinite recursion.

Adding some puts statements to the method:

```
  def rescue_with_handler(exception, object: self)
        puts '#######################################'.green
        if handler = handler_for_rescue(exception, object: object)
          handler.call exception
          exception
        elsif exception
          puts "second case".blue if (exception.cause == exception)
          rescue_with_handler(exception.cause, object: object)
        end
  end
```

...we end up with lots of:
```
...
second case
#######################################
second case
#######################################
second case
#######################################
...
```

Of course, it is questionable whether or not Rails should be prepared to an exception that is its own cause. I will meet with the author of the library in question and check why such an exception is even possible.

However, it might by nice for debugging if Rails would detect such a situation and break out out the recursion. Even if it makes no sense to have an exception like this, it can apparently happen - getting an appropriate stack trace would make debugging time much shorter.

Without having insights about Rails, my first-guess approach would be something like adding the following conditional `return nil` line, which indeed solves the StackOverflowError on my machine:

```
      def rescue_with_handler(exception, object: self)
        if handler = handler_for_rescue(exception, object: object)
          handler.call exception
          exception
        elsif exception
          return nil if exception == exception.cause
          rescue_with_handler(exception.cause, object: object)
        end
      end
```

I'm not an experienced Rails programmer, so I hope this makes at least some sense. Please excuse me if I'm talking rubbish. Thank you for your time.

**Comment by kalsan** [comment]
Update: The following lines of code are responsible for the exception having its own cause:
 ```
    begin
      ohnoes # NameError occurs here
    rescue OurFreakyFramework::Exceptions::ValidationFailed, ActiveRecord::RecordInvalid
      return false
    end
```
Commenting out the rescue clause avoids the problem. I'm still working on reproducing the problem outside our framework.

**Comment by beatgutzwiller** [comment]
Update: Seems like a jruby bug.
With jruby 9.1.5.0 the cause and the exception are identical in following code:

```
class TestController < ApplicationController
  def dtest
    begin
      begin
        sadas
      rescue ActiveRecord::RecordInvalid
      end
    rescue => e
      puts e.object_id         # 6782
      puts e.cause.object_id   # 6782 Same Id
    end
  end
end                             
```
In Jruby 9.1.6.0 the issue is not reproducable.
I think the issue can be closed.

**Comment by kalsan** [comment]
The behavior is reproducible when using the (jruby) rails console:
```
bin/jruby -S rails console
> load 'rescue-jruby-test.rb'

Exception ID is: 6686
Cause ID is: 6686

```

However, the issue is not reproducible when calling the script from jruby directly:
```
bin/jruby rescue-jruby-test.rb

Exception ID is: 6686
Cause ID is: 8
```

**Comment by beatgutzwiller** [comment]
Ok now i think i got it:
```
class TestController < ApplicationController
  def dtest
    begin
      begin
        sadas
      rescue =>e
        fail e
      end
    rescue => e
      puts e.object_id.inspect.green
      puts e.cause.object_id.inspect.yellow
    end
  end
end
```
Since both time the same exception is raised, the exception cause is the exception.
It still looks like a jruby bug, since i can't reproduce it in jruby 9.1.6.0.

**Comment by kalsan** [comment]
Reducing your script to the bare minimum, I can still reproduce the issue:

Here's the completely rails-free code:

```
begin
  begin
    begin
      sadas
    rescue => e
      fail e
    end
  rescue => e
    puts e.object_id.inspect
    puts e.cause.object_id.inspect
  end
end

```

And these are the results:

```
> jruby rescue-jruby-test.rb 
2002
8
> ruby rescue-jruby-test.rb 
8740720
8
> bin/jruby rescue-jruby-test.rb 
2002
2002
```

So the origin of this issue is not related to Rails. Rails simply transforms this jruby bug into a StackOverflow.

Thanks!
