### ISSUE TITLE
shouldn't AcitveSupport::Concern be abstracting away prepending vs including

### ISSUE THREAD

**Issue by bughit** [rails/rails#27483]
Currently it doesn't hook prepending (`prepend_features`, `prepended`) but it seems to make sense for  Concern to abstract this away, because Concern functionality is applicable regardless of whether it's ultimately prepended or included

**Comment by rafaelfranca** [comment]
Thank you for the issue but we don't accept feature requests in the issue tracker.

**Comment by bughit** [comment]
If pretending concerns is explicitly not supported currently should it not at least raise when prepended?

**Comment by bughit** [comment]
@rafaelfranca

A concern behaves like a concern when included but a plain module when prepended.  If prepend support is an unsupported feature then why not at least raise when prepended?

**Comment by rafaelfranca** [comment]
Because a concern is a module as any other module

**Comment by bughit** [comment]
A concern is more than a module.  It has expected specialized behavior.  You would not bother creating a concern if all you wanted was plain module behavior.  So for a concern to quietly regress to a plain module when prepended, is not obvious, self-evident, expected.

**Comment by rafaelfranca** [comment]
I'm not arguing that the behavior is expected but it is a feature request and the issue tracker is not the place for feature requests/
