### ISSUE TITLE
Backport Ruby 2.4 support into Rails 4.2

### ISSUE THREAD

**Issue by SamSaffron** [rails/rails#27489]
At the moment the Rails 4.2 branch does not work on Ruby 2.4.0 due to

- Active Support has an explicit dependency on json gem version 1.x and json gem in 2.4.0 is at 2.0.2 
- Fixnum/Bignum unification means that some of the internal fixes in later versions of active support need to be backported

@dhh  was open to back-porting support provided it is not too much work and someone is willing to take it. 

Since we are looking at dropping sprockets at Discourse and sprockets 4 upgrade is chewing up more memory than current 3 branch we are in a bit of a bind when it come to upgrading to Rails 5 but really want to get some of the perf benefits of Ruby 2.4. 

@rafaelfranca  @matthewd  thoughts? 

see also: https://github.com/rails/rails/pull/27458

**Comment by rafaelfranca** [comment]
👍 We are working on it at https://github.com/rails/rails/pull/27473. Closing as duplicated of that PR.
