### ISSUE TITLE
ActiveRecord does not work well with STI associations in where clause

### ISSUE THREAD

**Issue by jarmo** [rails/rails#27495]
### Steps to reproduce

See this [gist](https://gist.github.com/jarmo/987d820832e1b99b6d63569791ce9e30#file-rails-sti-test-rb) for reproducible test-cases.

### Expected behavior

All tests should pass.

### Actual behavior

Final test fails with an error message like:
```
ActiveRecord::StatementInvalid: SQLite3::SQLException: no such column: video_posts.deleted: SELECT "users"."id" AS t0_r0, "posts"."id" AS t1_r0, "posts"."deleted" AS t1_r1, "posts"."type" AS t1_r2, "posts"."user_id" AS t1_r3 FROM "users" LEFT OUTER JOIN "posts" ON "posts"."user_id" = "users"."id" AND "posts"."type" IN ('VideoPost') WHERE "video_posts"."deleted" = ?
```

ActiveRecord tries to select from a table `video_posts` instead of a `post` even though it should know that it is an STI association. It does work only when specifying STI base-class in __where__ statement.

### System configuration
**Rails version**:
4.2.7.1 and 5.0.1

**Ruby version**:
2.3.2

**Comment by matthewd** [comment]
This is currently expected behaviour: `where` qualifies columns with the table name, not the association name. See https://github.com/rails/rails/pull/13555 for history.
