### ISSUE TITLE
Aliasing associations in STI sub-classes properly

### ISSUE THREAD

**Issue by jarmo** [rails/rails#27496]
### Situation

Let's assume we have a situation similar to:

```ruby
ActiveRecord::Schema.define do
  create_table :posts, force: true do |t|
    t.string :type
  end

  create_table :comments, force: true do |t|
    t.integer :post_id
  end
end

class Comment < ActiveRecord::Base
end

class Post < ActiveRecord::Base
  has_many :comments
end

class VideoPost < Post
end
```

Now, in the code we can always write queries like this:

```ruby
VideoPost.where(foo: "bar").first.comments
```

What if __VideoPost__ comments are still underneath type of __Comment__, but business-logically they're somewhat different, let's say a __video_comment__ and I'd like to do something like this:

```ruby
VideoPost.where(foo: "bar").first.video_comments
```

It's possible by changing __VideoPost__ to this:

```ruby
class VideoPost < Post
  alias_method :video_comments, :comments
end
```

This however does __not__ work when using in __where__, __includes__ or __joins__ statements similar to:
```ruby
VideoPost.includes(:video_comments) # blows up with an error saying that this association does not exist
```

One possible way I've found to be working is like this:
```ruby
class VideoPost < Post
  has_many :video_comments, foreign_key: :post_id
end
```

However, this seems to be kind of silly and verbose.

What would be the correct way of aliasing associations under STI sub-classes so that reading code would make more sense?

### System configuration
**Rails version**:
4.2.7.1

**Ruby version**:
2.3.2

**Comment by matthewd** [comment]
If you want to do this, there isn't going to be a better option than redefining the association.

It doesn't make much sense to me, though... given a `video`, I'd want to call `video.comments`, not `video.video_comments`.

Please use the mailing list or StackOverflow for questions/help, where a wider community will be able to help you. We reserve the issues tracker for issues only.

**Comment by jarmo** [comment]
I totally understand `video.comments` vs `video.video_comments` being a strange example, but in my real code it makes more sense because there's actual business rules involved.

Try to imagine that `comments` are abstracted collection name, but STI sub-classes have a more specific `comments`, which would not make too much sense in the code outside of models.

I even have a case where one sub-class does not need to redefine association because that abstracted association makes totally sense from business-logic side, but other sub-classes would be more readable when having a more specific name for the *comment-like* association.

It would be nice when regular `alias_method` would work as expected in this case.
