### ISSUE TITLE
Mismatch type error when you create an non-integer index

### ISSUE THREAD

**Issue by ezekielriva** [rails/rails#27501]
bug found by @alelopez91

### Steps to reproduce

1. Create a new table migration with a non-integer primary key.
2. Run the migration.
3. Drop your database
4. Run bundle exec rake db:schema:load

### Expected behavior
This should create the table with the same type. Initial: string, after load: string

### Actual behavior
It's creating the table using Integer as column type. Initial: string, after load: integer

### System configuration
**Rails version**: 4.2.7

**Ruby version**: 2.3.1-p112

**Comment by rafaelfranca** [comment]
How does it work with Rails 5?

**Comment by kamipo** [comment]
Non integer primary key is suppoted since 5.0.0 by #17851.

**Comment by rafaelfranca** [comment]
Closing since it works in Rails 5
