### ISSUE TITLE
Passing a block to an active record relationship should throw an error

### ISSUE THREAD

**Issue by Dorian** [rails/rails#27519]
### Steps to reproduce

- `User.first(2) { |t| fail "this doesn't get executed" }`

### Expected behavior

Should throw an error, the user probably meant to use `#map`, `#each`, etc.

### Actual behavior

Ignore the block silently.

### System configuration

**Rails version**: 5.0.0
**Ruby version**: 2.3.3

**Comment by matthewd** [comment]
It is normal ruby behaviour for any method to silently ignore a supplied block it doesn't expect.

We're not going to add a conditional to every method to manually check for this mistake; it seems better directed as a feature request to ruby itself.
