### ISSUE TITLE
5.0.0.1 -> 5.0.1 `pluck` returns data of unsaved association records

### ISSUE THREAD

**Issue by dsander** [rails/rails#27510]
`pluck` now returns data from new records if the association is loaded. 
Pull request that changed the behavior: https://github.com/rails/rails/pull/25976

### Steps to reproduce

```
associations = current_user.associations.load;
new = associations.build
ids = current_user.associations.pluck(:id)
=> [...., nil]
```

### Expected behavior

`pluck` should not return data of unsaved records. 

### System configuration
**Rails version**: 5.0.1

**Ruby version**: 2.3.3

**Comment by bogdan** [comment]
Wow! nice improvement... not for a patch release though....

**Comment by matthewd** [comment]
Thanks for the report!

This was a bug fix:

* `pluck` is defined on any Enumerable, and returns values for each item in the collection
* a loaded association acts as an Enumerable collection *including* unsaved records

The fact this particular combination was behaving differently was an aberration. Unfortunately, the nature of a bug fix is that it creates a behavioural change for anyone depending on the buggy behaviour. 😕

**Comment by dsander** [comment]
Thanks for the quick response!

I wasn't aware pluck was added to `Enumerable` in Rails 5. Would you accept a PR updating the [`pluck` documentation](http://api.rubyonrails.org/classes/ActiveRecord/Calculations.html#method-i-pluck) to show examples that do not hit the database?
It being in the same class as all the database based calculation methods and only having examples that hit the database still give the impression it only returns data from records that are in the database.

**Comment by matthewd** [comment]
Sure!

Note that on a loaded relation, it'll use the loaded records for `pluck(:some_attribute)`, but still has to go to the DB for `pluck('arbitrary sql')`:

```
Person.pluck(:id) => SELECT id FROM people
Person.load.pluck(:id) => SELECT * FROM people
Person.to_a.pluck(:id) => SELECT * FROM people

Person.pluck('id * 2') => SELECT id * 2 FROM people
Person.load.pluck('id * 2') => SELECT * FROM people; SELECT id * 2 FROM people
Person.to_a.pluck('id * 2') => SELECT * FROM people; exception
```

(In the context of this issue, that means different arguments to pluck can actually give different numbers of results on the same object. Maybe we should raise if pluck needs to hit the database and there are unsaved records in the association. 🤔)

**Comment by dsander** [comment]
Good point, my argument against raising an exception would be that this is to only way I see to force `pluck` to hit the database: `.pluck('id AS id')`
What I would love to see is `pluck` filtering out unsaved records, which would bring it back closer to the other `ActiveRecord::Calculations` methods. `sum` is also defined for `Enumerable` but always hits the database (as well are `maximum`, `minimum` with slightly different names).
