### ISSUE TITLE
Rails Guides Active Record Associations Conflicting Information

### ISSUE THREAD

**Issue by davidsherline** [rails/rails#27516]
In the Active Record Associations page of the Rails Guides, section [3.5 Bi-directional Associations](http://guides.rubyonrails.org/association_basics.html#bi-directional-associations), it appears there is conflicting information.

First, the section states that given two models, one with a `belongs_to` and another with a `has_many`, ActiveRecord will not know about the connection between the two. The example shows an instantiation of each, and the two getting out of sync. This is resolved by calling `:inverse_of` on both sides of the association.

However, a few paragraphs later, the section states that, "For belongs_to associations, has_many inverse associations are ignored." If that's true, why is `:inverse_of` called on both sides of the association in the example?

Moreover, the section further states, "Every association will attempt to automatically find the inverse association and set the :inverse_of option heuristically (based on the association name)." Indeed, setting up the associations in the example mentioned above yields a single object in memory without the `:inverse_of` call required.

It seems, then, that ActiveRecord _will_ know about the connection between two well-named models without `:inverse_of`, even though the section states otherwise. This seemingly conflict of information within the section will likely lead to confusion amongst readers new to Rails.

Thanks!

**Comment by maclover7** [comment]
Hmm, I think the statement regarding that `inverse_of`s declared on `has_many` associations are ignored / not registered within Active Record is incorrect. Would you be willing to submit a PR to remove this section from the documentation? Thanks!

**Comment by davidsherline** [comment]
Sure! I took a stab at re-writing the section to be a bit more clear. Let me know what you think!

**Comment by maclover7** [comment]
Thanks for the PR, did an initial review.

**Comment by alexcameron89** [comment]
The documentation for this issue was merged, so I think this can be closed.
