### ISSUE TITLE
Symbol#deep_dup fails for certain symbols with Ruby 2.4.0

### ISSUE THREAD

**Issue by matthewrudy** [rails/rails#27532]
### Steps to reproduce

I don't know what makes a Symbol duplicable or not.

But in my app, certain frequently used Symbols appear to not be duplicable.

```
# simple symbols work
>> :a.duplicable?
=> true
>> :a.deep_dup
=> :a
>> :a.dup
=> :a

# but some don't
>> :price_per_km.duplicable?
=> true
>> :price_per_km.deep_dup
TypeError: allocator undefined for Symbol
from /Users/matthew/.rvm/gems/ruby-2.4.0@gogovan/bundler/gems/rails-08af4e1d7fd7/activesupport/lib/active_support/core_ext/object/deep_dup.rb:14:in `dup'
>> :price_per_km.dup
TypeError: allocator undefined for Symbol
from (pry):6:in `dup'

# it doesn't seem to be length related
>> :something_else_long.duplicable?
=> true
>> :something_else_long.deep_dup
=> :something_else_long
>> :something_else_long.dup
=> :something_else_long
```

I posted this issue on the PR that introduced the change too
https://github.com/rails/rails/pull/27293#issuecomment-269883741

### Expected behavior

I expect `Symbol#deep_dup` to never raise an exception

### Actual behavior

`Symbol#deep_dup` raises exceptions for certain symbols in a project
perhaps related to frequency of use?

### System configuration
**Rails version**:

```
  remote: https://github.com/rails/rails.git
  revision: 08af4e1d7fd77eba4a3b587f2153bf92a3ac4ca1
  ref: 08af4e1
  branch: 5-0-stable
```

**Ruby version**:

2.4.0

**Comment by matthewrudy** [comment]
It seems I can easily reproduce by doing this

```
>> ('aaa'...'zzz').each{|a| a.to_sym.dup rescue puts "#{a} can't be dup-ed"}
...
zzu can't be dup-ed
zzv can't be dup-ed
zzw can't be dup-ed
zzx can't be dup-ed
zzy can't be dup-ed
 => "aaa"..."zzz"
```

**Comment by kaspth** [comment]
Nice find! The issue is a bug in Ruby, so you should file the issue there, thanks! 😄

**Comment by matthewrudy** [comment]
@kaspth that seems to be true,
but it means 5-0-stable is also broken with Ruby 2.4.0

May work with 2.4.1

**Comment by matthewd** [comment]
Yeah, this is (also) a bug in `duplicable?`.

**Comment by kaspth** [comment]
Yup, true 😊

**Comment by matthewrudy** [comment]
Just to check @kaspth 
so the plan is to leave this broken, and not support Ruby 2.4.0?

It does seem like an obscure Ruby bug,
but I hit it by upgrading from `5.0.1` to `5-0-stable` in order to remove the Ruby 2.4.0 deprecation warnings.

The bug was hit in a very ordinary place
and I expect if you try to release a 5.0.2 in order to fully support Ruby 2.4.0
you'll just get a bunch more reports of this same issue.

Here's my stacktrace;

```
Failure/Error: it { should validate_numericality_of(:price_per_km) }

TypeError:
  allocator undefined for Symbol
# /home/rof/cache/bundler/ruby/2.4.0/bundler/gems/rails-08af4e1d7fd7/activesupport/lib/active_support/core_ext/object/deep_dup.rb:14:in `dup'
# /home/rof/cache/bundler/ruby/2.4.0/bundler/gems/rails-08af4e1d7fd7/activesupport/lib/active_support/core_ext/object/deep_dup.rb:14:in `deep_dup'
# /home/rof/cache/bundler/ruby/2.4.0/bundler/gems/rails-08af4e1d7fd7/activesupport/lib/active_support/core_ext/object/deep_dup.rb:48:in `block in deep_dup'
# /home/rof/cache/bundler/ruby/2.4.0/bundler/gems/rails-08af4e1d7fd7/activesupport/lib/active_support/core_ext/object/deep_dup.rb:43:in `each_pair'
# /home/rof/cache/bundler/ruby/2.4.0/bundler/gems/rails-08af4e1d7fd7/activesupport/lib/active_support/core_ext/object/deep_dup.rb:43:in `deep_dup'
# /home/rof/cache/bundler/ruby/2.4.0/bundler/gems/rails-08af4e1d7fd7/activemodel/lib/active_model/errors.rb:80:in `initialize_dup'
# /home/rof/cache/bundler/ruby/2.4.0/gems/shoulda-matchers-3.1.1/lib/shoulda/matchers/active_model/validator.rb:99:in `dup'
# /home/rof/cache/bundler/ruby/2.4.0/gems/shoulda-matchers-3.1.1/lib/shoulda/matchers/active_model/validator.rb:99:in `perform_validation'
...
```

Notably, the `Symbol#dup` bug is a Ruby bug in 2.4.0
but the `Symbol#deep_dup` bug is a Rails bug only available on `5-0-stable` (I guess it'll be released to 5.0.2 shortly?)

Notably, I fixed this in my app by overriding `duplicable?`

``` ruby
require 'active_support/core_ext/object/duplicable'

class Symbol
  # XXX: symbol duplication sometimes works and sometimes doesn't in 2.4.0
  # so just make it not duplicable
  def duplicable?
    false
  end
end
```

**Comment by kaspth** [comment]
@matthewrudy oh, I see what you're saying now 😄

Pushed a fix for this case in c6c3b13 and backported to 5-0-stable in 2badd55, so `'symbol_from_string'.to_sym.duplicable?` will be false.

Thanks for the well written report! ❤️

(Note: the fix assumes `'symbol_from_string'.to_sym` etc. are the only kinds of symbols that Ruby 2.4 can't handle. Thus if Ruby 2.4.1 is released with a fix we'll `dup` symbols correctly.)

**Comment by matthewrudy** [comment]
thanks @kaspth 

Sorry I was less clear in my initial report (hadn't quite debugged it myself)

Updated my app to use the latest `5-0-stable`
Thanks.

**Comment by kaspth** [comment]
No worries, we figured it out in the end 😊
