### ISSUE TITLE
`cache_if` always computes the cache key

### ISSUE THREAD

**Issue by Hamada92** [rails/rails#27533]
### Steps to reproduce

Say I have the following code : 
```
cache_if false, [@article, @article.user.name, @article.comments.count] do 
  = render @article
```
### Expected behavior
since the condition is false, the cache should NOT compute `@article.user.name` or `@article.comments.count`.

### Actual behavior
Both values are computed by reaching to the database, although the cache should be ignored since the condition is false.

### System configuration
**Rails version**: 5.0.0.1

**Comment by prathamesh-sonpatki** [comment]
In case the condition is false, [it just yields the block](https://github.com/rails/rails/blob/b23187cc097f0f7177e228c9a64e47c680f81f9b/actionview/lib/action_view/helpers/cache_helper.rb#L181-L183)

Can you upload a sample application on Github that reproduces the issue without any external dependencies? Thanks.

**Comment by kaspth** [comment]
This is just how Ruby works. It'll evaluate the array no matter what the condition is because it's at the same scope as the condition.

You should be able to workaround this by going with a standard if and then put the cache call inside there.

Thanks!

**Comment by kaspth** [comment]
I should clarify a bit: the array contents are evaluated, but the cache key from those contents isn't computed.

**Comment by Hamada92** [comment]
Thank you @kaspth , you can close this.
