### ISSUE TITLE
RubyGems.org incorrectly lists the json gem as a dependency for ActiveSupport 4.2.7.1

### ISSUE THREAD

**Issue by paulyoder** [rails/rails#27544]
### Steps to reproduce
* View [the dependencies RubyGems.org has](https://rubygems.org/gems/activesupport/versions/4.2.7.1) for ActiveSupport 4.2.7.1
  * Notice it shows `json >= 1.7.7, ~> 1.7 ` as a dependency
* View [the actual dependencies in the source](https://github.com/rails/rails/blob/4-2-stable/activesupport/activesupport.gemspec) for ActiveSupport 4.2.7.1
  * Notice it does not list `json` as a dependency

### Expected behavior
ActiveSupport 4.2.7.1 from RubyGems should not have a dependency on the `json` gem

### Actual behavior
ActiveSupport 4.2.7.1 from RubyGems shows a dependency on the `json` gem

### System configuration
**Rails version**: 4.2.7.1

**Ruby version**: 2.4.0

**Comment by rafaelfranca** [comment]
The 4-2-stable branch is not 4.2.7.1 it is the future 4.2.8. See the tag tags you will see that JSON is still a dependency of 4.2.7.1

**Comment by paulyoder** [comment]
Thanks @rafaelfranca. Sorry for the confusion.

I tried updating my rails app today to use ruby 2.4.0 and received an error from Bundler because it cannot compile `json 1.8.3` on Ruby 2.4.0 ([see GH issue](https://github.com/flori/json/issues/303))

Do you have an estimated timetable for when version 4.2.8 will be released so it will work with Ruby 2.4?

**Comment by matthewd** [comment]
https://github.com/rails/rails/pull/27473
