### ISSUE TITLE
assigns() and assert_template in controller testing

### ISSUE THREAD

**Issue by marlinpierce** [rails/rails#27556]
Philosophically I agree, but in the spirit of hey I was using that...

    Testing what instance variables are set by your controller is a bad idea.
    The same goes for assert_template.

Absolutely.  These were dirty.  However...

It's dirty for the controller to pass data to the view by scraping the controller object's instance variables, and setting them as instance variables available to the templating.  The view should be a class, and the helper methods should be methods in that class.  Just as a stub for a model method can test if the controller called the model, a stub for this (non-existent class) should be able to test if the controller passed data to the view.  Since the controller does this by setting instance variables, assigns is the way you have to do it.  It's dirty, but it's making up for the dirtiness of how rails passes data to the view.

For instance, if you want a test to see if a given object occurs in the index results, how are you going to test it?  Do you have to screen scrape the HTML?  You could have the controller call a method on the model and test the results from that model, but how do you know the controller used the data by passing it to the view?  Since instance variables are how the controller does this, it is reasonable to test the instance variable.

For assert_template, consider controllers which fail a create by rendering the new template.  Arguably, they shouldn't do this.  If they do, if this is supported, then you need to test that it happened.

Developers should redirect to the new page, and have the controller render the new page properly.  That does mean passing all the field values, but that's not outrageously hard.  However, it also means getting the object's error aggregate populated for the new page.  If rails (suggested?) error handling requires rendering a template from the action where it failed, then handling errors requires such template switching and needs a way to be tested.

Again, assert_template is dirty, but it's making up for a dirty-ness in rails.

So maybe the new issue is
a) pass data from the controller to the view in a cleaner way, so it can be tested.
b) redesign the error handling on the view so you can redirect to the new (and edit) page instead of rendering the view from the create (and update) action.

**Comment by rafaelfranca** [comment]
Thank you so much for the issue but we don't take feature request on the issue tracker. We recommend you to try to implement the feature and send us a pull request or if you are in doubt if the feature will be accepts ask in Rails Core mailing list for feedback.

**Comment by rafaelfranca** [comment]
BTW, controllers tests are deprecated and are going to be moved to the rails-controller-testing so all answering all your questions:

Rails recommends you to write integration tests so you don't know about the Controller object and the View object. You make the request and assert in the response.

**Comment by rafaelfranca** [comment]
> a) pass data from the controller to the view in a cleaner way, so it can be tested.

I'm positive about this, but you know that this is already how it works? A view is a object and helpers are methods on that object and the instance variables are passed to the view in the initialization. So as a pseudo-code this is how views works in Rails

```
view = ActionView::Base.new
view.assignments = copy_all_instance_variables
```
