### ISSUE TITLE
`rails new` fails to read my Ruby version and won't create a new project

### ISSUE THREAD

**Issue by jodosha** [rails/rails#27569]
### Steps to reproduce

```
➜ gem install rails
➜ rails new hello_domains

    Rails 5 requires Ruby 2.2.2 or newer.

    You're running
      ruby 2.0.0p648 (2015-12-16 revision 53162) [universal.x86_64-darwin15]

    Please upgrade to Ruby 2.2.2 or newer to continue.
```

### Expected behavior

It should generate the project.

### Actual behavior

It refuses to generate the project because it reads a wrong version of Ruby.

It's worth mentioning that I'm using `chruby`. My three versions installed are:

```
➜ chruby
   jruby-9.1.6.0
   ruby-2.3.3
 * ruby-2.4.0
```

But `rails` bin reads the "system" Ruby instead:

```
➜ chruby system
➜ ruby -v
ruby 2.0.0p648 (2015-12-16 revision 53162) [universal.x86_64-darwin15]
```

Please note that when I'm trying to create the new project, my current Ruby version is 2.4 (as shown above).

### System configuration

**Rails version**:

`5.0.1`

**Ruby version**:

`ruby 2.4.0p0 (2016-12-24 revision 57164) [x86_64-darwin15]` (installed via `ruby-install`)
`chruby: stable 0.3.9 (bottled), HEAD` (installed via Homebrew)

**Comment by jodosha** [comment]
Update: It works if I use Ruby 2.3.3 (via chruby). So it's only about 2.4.0.

**Comment by matthewd** [comment]
Sounds like you have the `rails` gem (and thus binstub) installed in 2.3.3, but not 2.4.0 -- and when the chruby-managed binstub is absent, it finds one pointing at your system ruby.

Anyway, `rails` doesn't "read" anything; it checks the version of the ruby interpreter that's executing it.

**Comment by jodosha** [comment]
@matthewd Thanks for the quick reply. FYI I installed `rails` for 2.4 before to try to generate the new project.

**Comment by matthewd** [comment]
Some combination of `which rails` and `head -1 $(which rails)` should point to the problem. Otherwise, it sounds like a chruby issue.

**Comment by jodosha** [comment]
@matthewd After I generated the project with 2.3, I did `cd hello_domains && chruby 2.4 && bundle`.

After that, I'm able to generate new projects with `rails` and 2.4.

**Comment by stephaniewilkinson** [comment]
For me, switching back and forth reset my ruby and i was able to create a new rails app.

```
chruby system
ruby -v  
#>> ruby 2.0.0p648 (2015-12-16 revision 53162) [universal.x86_64-darwin16]
chruby 2.4.1
ruby -v
#>> ruby 2.4.1p111 (2017-03-22 revision 58053) [x86_64-darwin16]
rails new my_app
#>> generates app
```

**Comment by fxn** [comment]
I am also getting this one with

```
$ which rails
/Users/fxn/.gem/ruby/2.4.1/bin/rails
$ ruby -v
ruby 2.4.1p111 (2017-03-22 revision 58053) [x86_64-darwin16]
```

**Comment by jodosha** [comment]
@stephaniewilkinson @fxn thanks, it was in the end my oh-my-zsh plugin for Rails that failed. Sorry for the false positive. :smile:

**Comment by fxn** [comment]
Pretty vanilla bash setup over here, which might be good news to understand what is going on.

**Comment by dimkir** [comment]
Had same problem, with `rvm` on MacOS. But switching to system and back to 2.4 fixed the issue.
