### ISSUE TITLE
Object#blank? has incorrect behavior for empty whitespace string

### ISSUE THREAD

**Issue by mycargus** [rails/rails#27571]
### Steps to reproduce
1. open an irb console
2. enter the following method from [/activesupport/lib/active_support/core_ext/object/blank.rb:16](https://github.com/rails/rails/blob/master/activesupport/lib/active_support/core_ext/object/blank.rb#L16):
```ruby
def blank?
    respond_to?(:empty?) ? !!empty? : !self
end
```
3. execute the following example from [/activesupport/lib/active_support/core_ext/object/blank.rb:5](https://github.com/rails/rails/blob/master/activesupport/lib/active_support/core_ext/object/blank.rb#L5):
```ruby
'   '.blank?
```

### Expected behavior
```sh
=> true
```
### Actual behavior
```sh
=> false
```

### System configuration
**Rails version**: 5.0.1

**Ruby version**: 2.3.3

**Comment by matthewd** [comment]
Copying arbitrary lines out of files in the library is.. not supported.

**Comment by mycargus** [comment]
Ah, indeed... IRB isn't Rails console.  😄 
![please_disperse_nothing_to_see_here](https://cloud.githubusercontent.com/assets/3387765/21656061/7d723202-d28a-11e6-9618-76ce3212cfb8.gif)
