### ISSUE TITLE
cookies.delete broken for request type other than GET in controller tests

### ISSUE THREAD

**Issue by iamchucky** [rails/rails#27584]
### Steps to reproduce
[Reproduction Script](https://gist.github.com/iamchucky/c0d6acb48befe9ac72c12e079739cb2e)

### Expected behavior
`cookies["foo"]` in test cases should be `nil` after `cookies.delete` is called in controller

### Actual behavior
only GET request has the `cookies["foo"]` deleted while other request types still has `cookies["foo"]`

### System configuration
**Rails version**: 5.0.1, 5-0-stable
**Ruby version**: 2.3.1p112

Note that this is passing for Rails 4.2.7.1

I've noticed that https://github.com/rails/rails/commit/ae29142142324545a328948e059e8b8118fd7a33 has `cookies.update res.cookies` only for `get` but not for other request types, is that the root of the issue though?

This issue also seems to be related:
https://github.com/rspec/rspec-rails/issues/1574

**Comment by maclover7** [comment]
👍 Can confirm failing on master, passing on `4-2-stable`. Looks like ae29142142324545a328948e059e8b8118fd7a33 / 8363b879fe759f0645179f4521cc64795efbee6e are the commits that touched this part of the codebase.

Working on a solution...

**Comment by maclover7** [comment]
Opened up #27586 to solve this.

**Comment by rafaelfranca** [comment]
I had to revert because the fix caused a new regression

**Comment by yujinakayama** [comment]
We can use `@response.cookies["foo"]` instead of `cookies["foo"]` in test cases as a workaround.
