### ISSUE TITLE
Merge secure_headers into core?

### ISSUE THREAD

**Issue by oreoshake** [rails/rails#27583]
I wanted to open a discussion (forgive me if this isn't the right place) about merging the https://github.com/twitter/secureheaders library functionality into rails core. https://github.com/rails/rails/pull/15777 attempted to add similar CSP functionality but has stalled out. 

In https://github.com/rails/rails/issues/24961, I suggested a static default policy and that turned into a "let's write better docs" conversation. This is entirely separate.

`secure_headers` does much more than CSP and is meant to be a "here's a place where you configure 'security' for all header-based things (including cookies)" thing. Maybe it tries to do too much, maybe it doesn't. The rails `default_headers` mechanism does not suffice for any non-trivial application. CSP and X-Frame-Options are not meant to be static. 

Before I go through the motions of spiking out what this would look like, I just want to see if this is something that would be agreeable. And during the porting process y'all can review out anything that is disagreeable. If there's anything wrong with the current design of `secure_headers`, that'd be a great place to start.

### Features

* Global configs
  * Meant to be fairly static or the basis of a dynamic policy. e.g. `:api_policy` vs the default policy or `:admin` CSP vs the default or `:preview_potentially_breaking_features_to_employees_only` vs the default
  * There's a default policy and a set of policies that can be referred to by name.
* API for opting out of a given header or of all headers for a given request
* API for setting specific X-Frame-Options values per request
* Grouped policy changes based on specific needs
  * e.g. that one page that needs an extra `frame-src` `font-src` and `form-action` that doesn't belong in the global policy.
  * See `named_overrides` and `named_appends`.
* It validates values via regex
  * It does some light validation on the CSP, certainly not comprehensive
* It handles per-content type, per-controller, per-action, per-tag helper configs well.
  * An API for overriding a directive
  * An API for appending to a directive
  * @josh's minifying code
  * middleware to set everything once. there should never be a need to check their string values in the application layer
* It handles cookie security marking cookies as `httponly`, `secure`, `samesite`, etc.

### Why not?

* The API is not clear enough for *everyone*.
  * [@jeremy's suggestion](https://github.com/rails/rails/pull/15777#issuecomment-46390256) seems more friendly. To me, it doesn't buy much. But I'm clearly not the right person to have an opinion here :smile:
* Maybe the code is so awful it's painful to try and grok
* Maybe it tries to do too much
* Maybe the way it's shoehorned as a library has created some not so desirable code
* Maybe the current mechanisms that are duplicated by secure_headers are actually better, even if incomplete.

### How to move forward?

* Figure out which parts of `secure_headers` are terrible/agreeable
* Agree on an API
* Agree on a configuration scheme
* Settle on UA sniffing (if any)
* Agree on safe defaults

Getting security closer to the framework is always a win and is something @GitHubSecurity is actively working on.

/cc @ptoomey3 @mastahyeti @gregose @tenderlove @arthurnn @connorshea @nateberkopec @jacobbednarz @stve

**Comment by guilleiguaran** [comment]
+1 to this, I've wishing to copy secure_headers in Rails core since years ago ❤️

**Comment by maclover7** [comment]
👍 on making more security configuration and defaults available at a framework level.

Can you make a list of all features in the gem we'd want to consider including into Rails, and then we make make incremental PRs towards that (say one PR for CSP, and so on)? Will be easier to manage than one large PR.

**Comment by oreoshake** [comment]
> Can you make a list of all features in the gem we'd want to consider including into Rails

I tried to do that in the `Features` section above. All of the features have been very useful for github.com, however we aren't using the cookie features yet. Others are.

> make incremental PRs towards that (say one PR for CSP, and so on)?

I think this is the right approach. !CSP is trivial. CSP is hard. Cookies are hard. All of these things can be discrete PRs:

* *HOW* things are configured (currently just passing a hash for the most part)
* Easy headers, configure and apply (XCTO, XDownloadOptions, X-XSS, etc) *
* XFO config/application + per action API
* Static CSP config/application
* Multiple policies API (`SecureHeaders.override` and `SecureHeaders.use_override`)
* Per-action append/overrides API (`override/append_content_security_directives`)
* Cookie secure settings * (https://github.com/twitter/secureheaders/blob/master/docs/cookies.md)
* Cookie HTTPOnly settings * 
* Cookie SAMESITE settings

\* Pretty sure rails currently handles these, we could either not change it or make it backwards compatible and deprecate

**Comment by oreoshake** [comment]
Whoops, I forgot to mention a fairly powerful feature: automated nonce and hash application/management for CSP: https://github.com/twitter/secureheaders/blob/7801462a4ea6c83479d7c38f6820e56177610745/lib/secure_headers/view_helper.rb#L12-L68

**Comment by rafaelfranca** [comment]
@oreoshake I'm a little bit concerned about merging the code to the framework. It is already an isolated gem and have different maintainers so unless there is huge benefits for having the gem integrated in the framework I'd keep it as a separated gem.

I do agree that is good to have its features in the framework so what about adding the gem by default in the generated Gemfile and making it first class citizen in our documentation and guides as a first step?

**Comment by oreoshake** [comment]
> huge benefits for having the gem integrated in the framework I'd keep it as a separated gem.

The _huge_ benefit is the "default effect". Setting these detailed, safe, secure headers means everyone is better off by default. You have to consciously opt-out of the protection provided. 

**In my experience, nobody opts out. They adapt. Adapting is better than opting out.**

The default CSP proposed in one of the referenced PRs would overnight make new applications much more secure. Yes, CSP has it's issues, but some CSP is infinitely better than no CSP*.

> I do agree that is good to have its features in the framework so what about adding the gem by default in the generated Gemfile and making it first class citizen in our documentation and guides as a first step?

Well, that's certainly a lot easier for me :smile:

**Comment by rafaelfranca** [comment]
When I say benefits is benefits on term of code. Like, making the design of the gem simpler by coupling it in the framework.

To make it default we can make the gem an entry in the default Gemfile and if we need to go further we can also make it a dependency of the `rails` gem. Both approaches will give the benefits of having it by default (and make possible to opt-out) without loosing the benefits of running it as a separate gem with a different issue tracker and different maintainers. We can also move it to the rails organization (if maintainer agree) so we have the Rails core team access and the actual maintainers keep all the access they already have.

**Comment by oreoshake** [comment]
>  I'm a little bit concerned about merging the code to the framework. It is already an isolated gem and have different maintainers

Oh, I seemed to have skipped over that part. Ignore my "default effect" comment

**Comment by oreoshake** [comment]
>  We can also move it to the rails organization (if maintainer agree) so we have the Rails core team access and the actual maintainers keep all the access they already have.

I've been [trying to add maintainers](https://github.com/twitter/secureheaders/issues/280) for some time now. I would be :100: to transferring the project to the rails org. While I'm no longer part of the twitter org, I do have admin rights to the repo.

**Comment by oreoshake** [comment]
So including it in the generated Gemfile actually accomplishes nothing without an additional initializer. Any objections to auto-generating the initializer that will be full of details and information that points to the guide on how to customize it?

**Comment by rafaelfranca** [comment]
> Any objections to auto-generating the initializer that will be full of details and information that points to the guide on how to customize it?

No at all. If we want to make it default it is fine to generate the application with all informations it needs about the gem.

**Comment by matthewd** [comment]
I think this is important enough to be in core, and important enough to deserve a well designed, ActionController-style, API.

Unfortunately, *that* is where previous efforts have stalled: there are clearly people who think this is important enough to ask for, but less who think it's important enough to work on.

https://github.com/rails/rails/pull/24961 didn't turn into "we should just write some documentation instead", but "https://github.com/rails/rails/pull/15777 is almost done, and a much more comprehensive solution; it just needs some docs work to get it across the line".

Once we insist on designing an API for it, I'm not sure there's much benefit to using/relying on secure\_headers.

Literally merging code from secure\_headers is impossible because of its license: Rails is not Apache licensed, and has no intention of becoming so.

---

Anyone wanting to see a CSP implementation in Rails is best served by helping get https://github.com/rails/rails/pull/15777 merged. The reasons it stalled aren't unknowable mysteries: it stalled because no-one is working on it.

**Comment by oreoshake** [comment]
> For example, it is going to be very difficult to propose a suitable (and secure) CSP default. 

As you can probably tell by https://github.com/rails/rails/pull/24961, I disagree with this statement. For existing apps, yes. For new apps, I think not. 

Sorry, I realize that statement does nothing for this PR but I got nerd sniped.

**Comment by oreoshake** [comment]
Closing this one out. I'm happy to collaborate with someone on finishing out https://github.com/rails/rails/pull/15777 but I'm not interested in writing the code or maintaining two things :smile: 

There be demons in there, godspeed.

**Comment by clod81** [comment]
what about adding samesite option to the session cookie?

**Comment by jacobbednarz** [comment]
@clod81 I was looking at this yesterday for one of our applications and I haven't quite determined if you can just append it onto the existing cookie options or whether you need to add the functionality into the cookie middleware.

**Comment by clod81** [comment]
@jacobbednarz I had a quick look myself before, before running out of time and had to do something else. appears need to be added into cookie middleware functionality
