### ISSUE TITLE
Forked foundation-rails gem causes assets:precompile error deploying to production

### ISSUE THREAD

**Issue by bennyzr** [rails/rails#27592]
### Steps to reproduce
1) Fork the foundation-rails gem (without modifying any code). 
2) Use branch v5 in your gemfile.
3) Deploy to production with Capistrano.

### Expected behavior
The deployment should be successful using the forked gem along with potential code modifications.

### Actual behavior
I get an error "ExecJS::RuntimeError: SyntaxError: Name expected (line: 17864, col: 111, pos: 559646)" during the Execute assets:precompile step in Capistrano.

### System configuration
Rails v. 5.0.0.1

Ruby v. 2.3.1

**Comment by rafaelfranca** [comment]
This seems to be a problem with foundation-rails not Rails.
