### ISSUE TITLE
unable to add to action_dispatch.rescue_responses in an engine

### ISSUE THREAD

**Issue by dsusco** [rails/rails#27590]
### Steps to reproduce

I'm still not certain if this is an issue or a lack of understanding of the configuration option.

I'm trying to add a rescue response in an engine initializer so the application renders its 403 error page:

    Rails.application.config.action_dispatch.rescue_responses.merge!({
      'MyEngine::Errors::Forbidden' => :forbidden
    })

This isn't working, I'm still getting a 500 error and its page and not a 403. When I move the above code to the application's `config/application.rb` or an initializer though I get the 403 page.

### System configuration
Rails 5.0.1
Ruby 2.3.3

**Comment by rafaelfranca** [comment]
A initializer present inside the engine `config/initializer` or the application `config/initializer` run after the configuration is set in Action Pack so it is too later to configure it. See `ActiveRecord::Railtie` code to see how to do it properly.
