### ISSUE TITLE
doc, active record, add_index

### ISSUE THREAD

**Issue by stoivo** [rails/rails#27606]
### Steps to reproduce

(Guidelines for creating a bug report are [available
here](http://guides.rubyonrails.org/contributing_to_ruby_on_rails.html#creating-a-bug-report))

### Expected behavior
Tell us what should happen

### Actual behavior
Tell us what happens instead

### System configuration
**Rails version**: none

**Ruby version**: none

I read the docs at http://apidock.com/rails/ActiveRecord/ConnectionAdapters/SchemaStatements/add_index and  saw some matformed formating.
![screen shot 2017-01-07 at 22 43 48](https://cloud.githubusercontent.com/assets/3492040/21745379/c569882e-d52a-11e6-8d97-3a49c3429622.png)

I think is is something in these [lines](https://github.com/rails/rails/blob/fdc219e0f857c372748296eae9cc5828ffb2c2c3/activerecord/lib/active_record/connection_adapters/abstract/schema_statements.rb#L665-L669) but could see anything stange there.

I am willing to contribute but need some guidelines then :)

**Comment by Gaurav2728** [comment]
hi @stoivo ,

You can check right documentation here http://api.rubyonrails.org/ , It's official and updated rails documentation.

here you can find for `add_index` and check right and update doc  -->
```
Creating an index with specific key lengths for multiple keys

add_index(:accounts, [:name, :surname], name: 'by_name_surname', length: {name: 10, surname: 15})
```

**Comment by stoivo** [comment]
Thanks, is there a way I can update apidock.com

**Comment by Gaurav2728** [comment]
@stoivo  you should go through http://edgeguides.rubyonrails.org/contributing_to_ruby_on_rails.html

http://edgeguides.rubyonrails.org/api_documentation_guidelines.html

**Comment by prathamesh-sonpatki** [comment]
@stoivo Rails official documentation is hosted on http://api.rubyonrails.org/. 

apidock.com is a different service and you need to contact them to see how to update it.

**Comment by stoivo** [comment]
Okey, thanks.

I did some blameing and saw that is was fixed in https://github.com/rails/rails/commit/5df94c6ffd82a7d42f36e36892281a4b28ce2ebc
