### ISSUE TITLE
nginx+passenger with Rails 5.0.1: "WebSocket connection to 'ws://localhost/cable' failed: WebSocket is closed before the connection is established"

### ISSUE THREAD

**Issue by gbisheimer** [rails/rails#27625]
This problem doesn't exists with Rails 5.0.0.1.

I uploaded 2 test repositories.
Working: https://github.com/gbisheimer/actioncable-5.0.1-test
Not working: https://github.com/gbisheimer/actioncable-5.0.1-test/tree/rails-5.0.1

### Steps to reproduce

```
git glone https://github.com/gbisheimer/actioncable-5.0.1-test/tree/rails-5.0.1
make docker-build
docker-compose up
docker ps (use this to get the port that the application is using)
```

### Expected behavior
Application runs normally. Actioncable is streaming from /cable URL.

### Actual behavior
Browser console shows "WebSocket connection to 'ws://localhost/cable' failed: WebSocket is closed before the connection is established"

### System configuration
**Rails version**: 5.0.1

**Ruby version**: 2.2.5

**Comment by rafaelfranca** [comment]
Which passenger version are you using? Maybe related with https://github.com/rails/rails/issues/2742?

**Comment by gbisheimer** [comment]
Thanks @rafaelfranca. I can confirm its related to that passenger issue and is fixed in passenger 5.1.1.

**Comment by superacidjax** [comment]
This problem does exist still when using Puma.

**Comment by edwardmp** [comment]
I too notice this problem using Puma.

**Comment by lalit-nga** [comment]
I had deployed my rails application with help of **Elastic Beanstalk**. I have **Passenger Standalone** as application server with **rails 5.1** and **Ruby 2.3**.

On development, I have puma as application server. I am seeing no such issue. It is only happening with passenger on production.

**Comment by lalit-nga** [comment]
I have recently moved to Puma from Passenger. But the issue still exist.

**Comment by edwardmp** [comment]
@lalit-nga which versions of Passenger and Puma were you using? Might be another issue.

**Comment by lalit-nga** [comment]
@edwardmp I have below configuration.

**Rails - 5.1.1**

**Elastic Beanstalk with Puma** 
```
Puma -2.16.0 
nginx 1.10.2
```
**Elastic Beanstalk with Passneger** 
```
Passenger 4.0.60
nginx 1.8.1
```

You can find it more [here](http://docs.aws.amazon.com/elasticbeanstalk/latest/dg/concepts.platforms.html)

I have also tried it this [thread](https://github.com/rails/rails/issues/25955) and used nginx_proxy.config, with no luck.

**Comment by vcavallo** [comment]
Why is this closed if the last few comments indicate that it's still an issue?

**Comment by ChinaHDJ** [comment]
This problem does exist still when using Puma.

**Comment by bear-in-mind** [comment]
Same here !
