### ISSUE TITLE
`sum` no longer queries for associations when previously loaded

### ISSUE THREAD

**Issue by justincase** [rails/rails#27626]
### Steps to reproduce
```ruby
begin
  require "bundler/inline"
rescue LoadError => e
  $stderr.puts "Bundler version 1.10 or later is required. Please update your Bundler"
  raise e
end

gemfile(true) do
  source "https://rubygems.org"
  # Activate the gem you are reporting the issue against.
  gem "activerecord", "5.0.1"
  gem "sqlite3"
end

require "active_record"
require "minitest/autorun"
require "logger"

# Ensure backward compatibility with Minitest 4
Minitest::Test = MiniTest::Unit::TestCase unless defined?(Minitest::Test)

# This connection will do for database-independent bug reports.
ActiveRecord::Base.establish_connection(adapter: "sqlite3", database: ":memory:")
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :posts, force: true do |t|
  end

  create_table :comments, force: true do |t|
    t.integer :post_id
  end
end

class Post < ActiveRecord::Base
  has_many :comments
  validates_associated :comments
end

class Comment < ActiveRecord::Base
  belongs_to :post

  def dice
    4
  end
end

class BugTest < Minitest::Test
  def test_association_stuff
    post = Post.create!
    Comment.create!(post: post)
    Comment.create!(post: post)
    assert_equal(8, post.comments.sum(&:dice))
  end
end
```

### Expected behavior
`8` on Rails `v5.0.0.1`

### Actual behavior
`0` on Rails `v5.0.1`

The behavior of `sum` changed in https://github.com/rails/rails/pull/25976. No query is executed since the `:comments` association is already `loaded?` due to the `validates_associated` validator. I realize, however, that `model.association.create` is a more proper way of creating those associations.

### System configuration
**Rails version**: `v5.0.0.1` and `v5.0.1`

**Ruby version**: `ruby 2.3.1p112`

**Comment by kamipo** [comment]
Related to #27510. `sum` with block is delegated to Enumerable, but previously always hit the database. But a loaded association should have acted as an Enumerable collection.
As you say, `model.association.create` is a proper way in that case, I think. Or if you need to force hit the database, please use `model.association.reset` or `model.association.reload`.

**Comment by justincase** [comment]
Thank you, I reckon it's a simple fix and the change certainly seems more consistent. It was a little unexpected to have the API change with a patch release however. It broke in a subtle way — especially since, at a glance, it appeared that the validator was the issue at hand. Oh well, perhaps this will save others some debugging time.
