### ISSUE TITLE
Add String#nil_or_empty? and  "allow_nil_or_empty: true" option to validations

### ISSUE THREAD

**Issue by enatividad** [rails/rails#27627]
### Context
There are edge cases where these features might be useful.

For example, I want to add and change a __password__ to a __User__ model.

### Steps to reproduce
1\. Generate User model

```
USING ACTIVERECORD ORM
rails generate model user password:digest
```

2\. Copy paste the following code

```ruby
# == Schema Information
#
# Table name: users
#
#  id              :integer          not null, primary key
#  password_digest :string(255)
#

class User < ApplicationRecord
  PASSWORD_VALIDATIONS = {
    presence: true, length: { minimum: 8, maximum: 72 }, confirmation: true
  }
  PASSWORD_CONFIRMATION_VALIDATIONS = { presence: true }

  with_options on: :create do |r|
    r.validates :password,
        PASSWORD_VALIDATIONS
    r.validates :password_confirmation,
        PASSWORD_CONFIRMATION_VALIDATIONS
  end
  with_options on: :update do |r|
    r.validates :password,
        PASSWORD_VALIDATIONS.merge(allow_blank: true)
    r.validates :password_confirmation,
        PASSWORD_CONFIRMATION_VALIDATIONS.merge(if: :password)
  end

  has_secure_password validations: false
end
```

3\. Run the rails console, add a new user, and try to update the password of the new user.

```ruby
password = 'password'
user     = User.create(password: password, password_confirmation: password)

password   = '        '
password_c = 'anything (except blank) since confirmation is not validated'
user.update(password: password, password_confirmation: password_c)
```

### Expected behaviour
1. on create, password and password_confirmation must be present
2. on update and if password is not an empty string, password and password_confirmation must be present
3. on update but if password is nil or an empty string, do not validate password and password_confirmation

### Actual behaviour
1. on create, password and password_confirmation presence is validated. CORRECT
2. on update and if password is present, password and password_confirmation presence is validated. CORRECT
3. on update and if password is a series of whitespaces, password and password_confirmation. WRONG

### Importance
In the example, if actual behaviour number 3 is left unfixed, the user may accidentaly
type a series of whitespaces (e.g. '&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;') as their password, and __the database will still update the password__.

Once the user signs in and types his old password (e.g. 'password'), he would not be able to sign in (since the correct password is '&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;')

### Temporary Fix for the Example
```ruby
# ...
class User < ApplicationRecord
  # ...
  with_options on: :update do |r|
    r.validates :password,
        PASSWORD_VALIDATIONS.merge(allow_nil: true)
    # ...
  end
  # ...
  before_validation :set_default_values

  private
  def set_default_values
    password = nil if password.nil? || password.empty?
  end
end
```

### Desired Fix/es for the Example
```ruby
# ...
class User < ApplicationRecord
  # ...
  with_options on: :update do |r|
    r.validates :password,
        PASSWORD_VALIDATIONS.merge(allow_nil_or_empty: true)
    # ...
  end
  # ...
end

# OR

class User < ApplicationRecord
  # ...
  with_options on: :update do |r|
    r.validates :password,
        PASSWORD_VALIDATIONS.merge(allow_nil: true)
    # ...
  end
  # ...
  before_validation :set_default_values

  private
  def set_default_values
    password = nil if password.nil_or_empty?
  end
end
```

### System configuration
__Rails version__: 5.0.1

__Ruby version__: 2.3.3

**Comment by al2o3cr** [comment]
"In the example, if actual behaviour number 3 is left unfixed, the user may accidentaly
type a series of whitespaces (e.g. '        ') as their password, and the database will still update the password."

Are you certain about this? I'd expect the string of whitespace to fail the `presence: true` validation, since `'    '.blank? == true`.

**Comment by rafaelfranca** [comment]
Yup, those two issues explain the behavior. We don't want to introduce new options to validations.
