### ISSUE TITLE
No Rails 5 in apidock.com/rails

### ISSUE THREAD

**Issue by Nowaker** [rails/rails#27633]
http://apidock.com/rails/ is number one resource for browsing Rails sources and exploring changes accross different versions. API Dock results are usually first in all Rails related search results. I'm aware this is third party, but we as a community shouldn't ignore it - having it up to date helps everyone in the community.

I've just pinged API Dock team on Twitter. https://twitter.com/nwkr/status/818847245563031552

**Comment by sevenseacat** [comment]
People still use API Dock? Why?

**Comment by matthewd** [comment]
Even if I didn't want to ignore it, I'm not sure what I can do about it.

**Comment by Nowaker** [comment]
@matthewd There's a lot you or any member of this community can do about it:

1. The maintainer of this project at API Dock might spot it and fix it.
2. Anyone knows / has a direct contact to API Dock guys can step in and help.
3. Rails team might adopt this project on API Dock to make sure it's always up to date.

For any of this to happen though, all you @matthewd need to do is keep it this issue open. Closing it a minute later won't help the community. API Dock is top 1 search result in Google for most code-related queries.

**Comment by kaspth** [comment]
> Rails team might adopt this project on API Dock to make sure it's always up to date.

We already have api.rubyonrails.org and won't be looking to adopt another site even if it was up for grabs.

Maybe api.rubyonrails.org just needs some SEO love?

@toshimaru you improved the SEO on the Rails blog, are you interested in doing so for the API site as well? 😊

**Comment by toshimaru** [comment]
@kaspth Yes, I'd live to. ;) But I don't know how the website ( <http://api.rubyonrails.org> ) is built. If it's built by Github Pages, it's pretty easy to introduce SEO features, but it seems not. ( The doc seems on DigitalOcean server )

**Comment by matthewd** [comment]
It's generated by sdoc: https://github.com/zzak/sdoc/tree/master/lib/rdoc/generator/template/rails

In a local checkout of rails/rails, you should be able to change the Gemfile entry for sdoc to point to a local path. `rake rdoc` will generate it into `doc/rdoc/`.

**Comment by toshimaru** [comment]
Thanks, @matthewd , now I understood how it's built. I'll look into how it could be SEO-friendly.

**Comment by ento** [comment]
> People still use API Dock? Why?

To me, API Dock is still useful for:

- Reading API docs of older versions of Rails (namely, 3.x and 4.x)
- Comparing APIs of older versions of Rails

**Comment by tomanistor** [comment]
API Dock has been down for me for some time, but http://guides.rubyonrails.org/ provides good guides on current and old version of Rails.

**Comment by lastobelus** [comment]
How do you ignore  apidock.com? I'd love to ignore it, I really would. I spent more than an hour once trying to figure out how to get google to NEVER SHOW IT TO ME AGAIN, but I was unsuccessful.

**Comment by chrisarcand** [comment]
@lastobelus As Ruby/Rails has grown and the number of obsolete StackOverflow answers from 2009 and old sites like API Dock become impossible to filter in a google search, I have found tools like [Dash](https://kapeli.com/dash) to be invaluable and suggest you give that a try.

**Comment by rsmithlal** [comment]
Seems like apidock.com is pretty dead. The company that was running it (nodeta) no longer exists, or at least its web page is not pointing to anything, which is a bad sign for a tech company. The APIdock twitter has been inactive since 2013. Can't even register for an account on the website anymore because the recaptcha version is no longer supported.

**Comment by Nowaker** [comment]
I did a little digging and I think the guys behind Apidock / Nodeta are @mutru and @tsilen. Guys! Would you be willing to pass apidock to community? I could take it over, revive it, and host.

**Comment by maxim** [comment]
Back in the early 2000s I loved the comments on php community docs, and was glad to see this carried over to ruby. Even to this day I find doc comments useful and perhaps under-appreciated. If anything, this is just my 2c on what I think ApiDock got right.

**Comment by andyw8** [comment]
I believe @livedo was also involved in Apidock. I have tried to reach him but without success.

I was hoping the domain would eventually expire and it would fade away, but it has just been renewed for another year.

One upside though – thanks to @peterc, it's no longer linked to from https://old.reddit.com/r/ruby/.

**Comment by toshimaru** [comment]
I've created new Rails apidoc website, [railsdoc.github.io](https://railsdoc.github.io/). The goal of the project is to make apidoc SEO(search engine optimized). 

https://github.com/railsdoc/railsdoc.github.io#project-goal

It's still beta version, if any feedback please let me know.

**Comment by andyw8** [comment]
Surprisingly, there's been a recent update to the site – on May 15th, docs for Rails 4 and 5 were added, along with Ruby versions up to 2.6.3.
