### ISSUE TITLE
Module#parent_name broken for frozen classes

### ISSUE THREAD

**Issue by ccutrer** [rails/rails#27637]
### Steps to reproduce

```ruby
class A
  class B
  end
end

A::B.freeze
A::B.parent_name
```

### Expected behavior

Should return `"A"`, and not try to cache the parent_name into an instance variable on the frozen class

### Actual behavior

`RuntimeError: can't modify frozen #<Class:A::B>`

### System configuration
**Rails version**: 4.2.7.1 (though the code hasn't changed in 5.0 or master)
**Ruby version**: 2.3.1

**Comment by maclover7** [comment]
Caching introduced via 269c6c6bcfec342cf830e0b20c44bb2c888e8fdf.

**Comment by coreyward** [comment]
What do you think about checking for `frozen?` before defining?

Current:
```ruby
def parent_name
  unless defined? @parent_name
    @parent_name = name =~ /::[^:]+\Z/ ? $`.freeze : nil
  end
  @parent_name
end
```
Proposed:
```ruby
def parent_name
  return @parent_name if defined?(@parent_name)
  parent_name = name =~ /::[^:]+\Z/ ? $`.freeze : nil
  @parent_name = parent_name unless frozen?
  parent_name
end
```

**Comment by ccutrer** [comment]
:+1: from me

**Comment by maclover7** [comment]
@coreyward Can you please open up a PR with that code change and a regression test? Thanks!
