### ISSUE TITLE
Getting Started With Rails: Blog Tutorial Unit 6

### ISSUE THREAD

**Issue by Spencer197** [rails/rails#27657]
Is the Getting Started With Rails: Blog tutorial known to work?  Could there be a bug in it?  I carefully copied and pasted the given code into the generated files.  Everything work fine until I did unit 6.  Then I got the error: NoMethodError in Articles#show undefined method `article_comments_path' for #<#<Class:0x007fc8993a6510>:0x007fc8986c6868>
Did you mean?  article_path

Nobody on Stackoverflow could solve the problem.  

### Expected behavior:
The Show link should take user to the article clicked on.

### Actual behavior:
Rails throws the above error.

### System configuration
**Rails version**: Rails 5.0.1

**Ruby version**: 2.4.0
Thanks

**Comment by matrix9180** [comment]
Are you sure you updated your routes as described in 6.3? That's what defines the article_comments_path helper

```ruby
resources :articles do
  resources :comments
end
```

**Comment by Spencer197** [comment]
Matrix9180,  Thanks for responding.  In config/routes.rb, should I keep or delete the top line: Rails.application.routes.draw do ?  And how about root  'welcome#index' ?  The tutorial code doesn't include those lines, but I get errors without them.  Thanks.

**Comment by matrix9180** [comment]
Yes, absolutely keep those lines. You insert new routes after the `Rails.application.routes.draw do` line.

Based on your question it sounds like you maybe need to learn a bit more about Ruby before diving into Rails - the Rails guides tend to assume a certain level of understanding of Ruby. https://www.ruby-lang.org/en/documentation/quickstart/ is a good starting point.
