### ISSUE TITLE
[feature request] automatically generate options routes

### ISSUE THREAD

**Issue by aymericbouzy** [rails/rails#27655]
### Steps to reproduce

Send `OPTIONS` http method to any route.

### Expected behavior

`routes.rb` should automatically generate `OPTIONS` routes to advertise the API.
Currently, it is possible to generate them manually using https://gist.github.com/dhoelzgen/cd7126b8652229d32eb4 but it would be much better if it was automatically generated by rails.

### Actual behavior

I get a 500 error status

### System configuration
**Rails version**: 4.2.5.1

**Ruby version**: 2.2.4

**Comment by maclover7** [comment]
Hi @aymericbouzy! Thanks for opening up this issue to discuss this feature request. Unfortunately, Rails reserves the issue tracker for bugs/issues only, so the best venue to discuss this idea would be the mailing list. Thanks again!
