### ISSUE TITLE
authenticate_with_http_basic allows invalid headers

### ISSUE THREAD

**Issue by akostadinov** [rails/rails#27650]
When using the `authenticate_with_http_basic` it accepts invalid basic authentication header and passes to the block `nil` username and password. User's auth system may not expect nil values for these variables and this could lead to possible security issues in the app. I'm providing an example of how this could happen.

In my opinion, when invalid basic auth header is supplied, the methid should return nil as if no auth header has been supplied. This would be least surprise behavior. 

### Steps to reproduce
In some controller method do:
```
auth = authenticate_with_http_basic do |user, password|
  # if user and password are `nil`, this can be true although there is no such user
  users_hash[user] == password
end

unless res
    request_http_basic_authentication('MyApp')
end
```

Then send invalid auth header to app like:
```
curl http://localhost:3000/auth -H "Authorization: Basic 123456" -v
curl http://localhost:3000/auth -H "Authorization: Basic " -v
```

### Expected behavior
`HTTP/1.1 401 Unauthorized`

### Actual behavior
`HTTP/1.1 204 No Content`

### System configuration
**Rails version**:
5.0.0.1

**Ruby version**:
2.3.1

**Comment by maclover7** [comment]
Hi @akostadinov! I was experimenting around with this issue in a gist, and I think this is a small issue with your application, and a bug within Rails. In the auth check where you have `users_hash[user] == password`, I think you should change this to be: `users_hash[user] && users_hash[user] == password`. Otherwise, the original statement (essentially `nil == nil` when it evaluates) returns true.

**Comment by akostadinov** [comment]
I know how to workaround this and my app doesn't use this exact code. It was given for illustration purposes. The point was that in my opinion `authenticate_with_http_basic` method should provide some minimal guarantees for even calling the inner block. An invalid basic auth header should not be treated as if authentication has been provided. `Authorization: Basic 123456` certainly doesn't mean user provided `nil` username and `nil` password.

App authentication code may not handle `nil` values for username and password properly because developer did not expect such values to be ever possible to set by client. It is for me natural to expect that username and/or password might be empty strings. Being `nil` is something that client should not be able to set, no semantics for that in the spec I can see.
The least surprise for developer would be to have this method return `nil` as if authentication header was not provided. There is no documentation that explains `nil` username or password can be passed to the block. IMO this at least needs to be documented well if current behavior makes sense to anybody.

No sure why you closed issue when you wrote "and a bug within Rails". Or did you mean "not a bug"?
