### ISSUE TITLE
after_commit's previous changes lose the changes made earlier in the transaction

### ISSUE THREAD

**Issue by Dorian** [rails/rails#27661]
### Steps to reproduce

```ruby
class Show < ActiveRecord::Base
  after_commit(on: :update) do
    p previous_changes
  end
end

show = Show.create!(name: 'The Show', description: 'The Description', artist: 'The Artist')

Show.transaction do
  show.update!(name: 'Another Show')
  show.update!(description: 'Another Description')
end
```

[Full active-record-after-commit-and-transaction.rb](https://gist.github.com/730e71edea9046f312cc76f0bb5f96c2)

### Expected behavior

It should accumulate all the changes in the transaction and pass them as `previous_changes` to the after_commit hook.

```bash
$ ruby active-record-after-commit-and-transaction.rb
{"name"=>["The Show", "Another Show"],
"description"=>["The Description", "Another Description"]}
```

### Actual behavior

It only contains changes from the last update.

```bash
$ ruby active-record-after-commit-and-transaction.rb
{"description"=>["The Description", "Another Description"]}
```

### System configuration
**Rails version**: 5.0.0
**Ruby version**: 2.3.3

**Comment by matrix9180** [comment]
I don't believe `previous_changes` has ever been transaction-aware, so this would be a feature request. `changes` is reset after a save, which an `update!` implicitly does. 

Agree it would be a useful feature, not sure about the path for implementing though.

**Comment by maclover7** [comment]
+1 to what @matrix9180 posted above, I believe this would be a feature request, not a bug fix. Going to close out this issue since we reserve the issue tracker for bugs/issues only, but feel free to continue discussing this feature idea on the mailing list! :)

**Comment by Dorian** [comment]
@matrix9180 @maclover7 Actually I feel like having all the changes from the transaction is the expected behavior (at least to me).

**Comment by Dorian** [comment]
BTW somebody made a project about that: https://github.com/ccmcbeck/after-commit

**Comment by arthurnn** [comment]
i know @dylanahsmith has a gem for https://github.com/dylanahsmith/ar_transaction_changes

**Comment by esen** [comment]
I'm using following module:

```
module TransactionChanges
  extend ActiveSupport::Concern

  included do
    after_commit -> { reset_transaction_changes }
  end

  def reset_transaction_changes
    @transaction_changes = nil
  end

  def transaction_changes
    @transaction_changes ||= HashWithIndifferentAccess.new
  end

  private

  def accumulate_transaction_changes
    self.saved_changes.each do |key, value|
      transaction_changes[key] = value
    end

    yield
  end
end
```

You include this module in your model. Then, if you wrap your update calls in ```accumulate_transaction_changes```, you can later get all changes made within transaction using ```transaction_changes```

**Comment by pirj** [comment]
The gem didn't work well for me, I had some models for which accumulated results were not reset on transaction commit.

Regarding the snippet above - similar code worked fine, however, I have concerns on the order of the callbacks, wouldn't `reset_transaction_changes` be called earlier than other `after_commit` callbacks that might use the results of the accumulation?

**Comment by dylanahsmith** [comment]
> The gem didn't work well for me, I had some models for which accumulated results were not reset on transaction commit.

If you have issues with the ar_transaction_changes gem, then please report them on that repo.  That gem already makes sure to reset transaction changes after all after_commit callbacks.

**Comment by pirj** [comment]
Well, I was pointing out that it does not reset transaction changes in `after_commit` in some cases, and the snippet above worked better.

Added this comment so that the future researchers considered the snippet as a good option as well.

**Comment by dylanahsmith** [comment]
That is exactly why the ar_transaction_changes gem [wraps _run_commit_callbacks](https://github.com/dylanahsmith/ar_transaction_changes/blob/v1.1.3/lib/ar_transaction_changes.rb#L5-L9) instead of just using `after_commit` to reset the transaction changes.
