### ISSUE TITLE
ActiveSupport::TimeZone.find_by_zipcode missing 37212 Nashville, TN 

### ISSUE THREAD

**Issue by kquet** [rails/rails#27663]
### Steps to reproduce
```
irb(main):001:0> ActiveSupport::TimeZone.find_by_zipcode('37212')
=> nil
```

### Expected behavior
```
irb(main):001:0> ActiveSupport::TimeZone.find_by_zipcode('37212')
=> "Central Time (US & Canada)"
```

### Actual behavior
```
irb(main):001:0> ActiveSupport::TimeZone.find_by_zipcode('37212')
=> nil
```

### System configuration
**Rails version**: Rails 5.0.0.1

**Ruby version**: ruby 2.3.1p112 (2016-04-26 revision 54768) [x86_64-darwin16]

**Comment by Edouard-chin** [comment]
`find_by_zipcode` is not defined in ActiveSupport. I think it's a gem https://github.com/farski/TZip. You should probably open an issue on this repo

**Comment by kquet** [comment]
@Edouard-chin Sorry, thanks.
