### ISSUE TITLE
Wrong query produced when through association duplicated.

### ISSUE THREAD

**Issue by hjinu** [rails/rails#27666]
### Steps to reproduce

```
# user.rb

class User
  has_one :family, through: :family_tree
  has_one :family_tree, -> { rewhere(token: nil) }, foreign_key: 'member_id'
  has_many :family_members, through: :family, source: 'members'
end
```

```
# family.rb

class Family < ActiveRecord::Base
  has_many :family_trees, -> { rewhere(token: nil) }
  has_many :members, through: :family_trees
end
```

```
# family_tree.rb
#
#  id        :integer          not null, primary key
#  family_id :integer
#  member_id :integer
#  token     :string
#

class FamilyTree < ActiveRecord::Base
  belongs_to :member, class_name: 'User', foreign_key: 'member_id'
  belongs_to :family, class_name: 'Family'

  validates :member, uniqueness: { scope: :family }
end

```

`user.family_members` makes the below query

```
SELECT "users"."id" FROM "users" 
INNER JOIN "family_trees" ON "users"."id" = "family_trees"."member_id" 
INNER JOIN "families" ON "family_trees"."family_id" = "families"."id" 
INNER JOIN "family_trees" "family_trees_family_members_join" ON "families"."id" = "family_trees_family_members_join"."family_id" 

WHERE "family_trees_family_members_join"."member_id" = $1 AND "family_trees"."token" IS NULL  [["member_id", 3363]]
```

In the result, it is different with `user.family_members` and `user.family.members`

### Expected behavior

I wrote the method named `family_members` instead of association like this

```
def family_members
  User.where(id: FamilyTree.where(family: family, token: nil).pluck(:member_id))
end
```

This is exactly what I expected.

### Actual behavior

`user.family_members` got the records which have a `family_tree` with `token` is not NULL

### System configuration

I'm using Rails 4.2.0 with Ruby 2.3.0

**Comment by al2o3cr** [comment]
I've recreated this issue in the standard ActiveRecord bug report template:

https://gist.github.com/al2o3cr/c9840d061da202cb12b5e49b904ae144

The behavior is still present on 5.0.1.

Swapping the `rewhere` to plain `where` makes the bug clearer, as the resulting SQL looks like this:
```
SELECT "users".* FROM "users"
INNER JOIN "family_trees" ON "users"."id" = "family_trees"."member_id"
INNER JOIN "families" ON "family_trees"."family_id" = "families"."id"
INNER JOIN "family_trees" "family_trees_family_members" ON "families"."id" = "family_trees_family_members"."family_id"
WHERE "family_trees_family_members"."member_id" = ?
AND "family_trees"."token" IS NULL
AND "family_trees"."token" IS NULL
```

My interpretation of the above SQL is that one of the two duplicated `WHERE` clauses should have instead referred to the aliased table `family_trees_family_members` rather than the default `family_trees`.

**Comment by hjinu** [comment]
I want to try to fix it, but I don't know what files are need to revised.
@al2o3cr @maclover7 Could you give me some advices?

**Comment by ddragostinov** [comment]
Hi, I'm new and I'm looking into the issue  but I don't see any problem.

So far I found the following:
**user.family.members.to_sql produces**
SELECT "users".* FROM "users" 
INNER JOIN "family_trees" ON "users"."id" = "family_trees"."member_id" 
WHERE "family_trees"."family_id" = 1 AND "family_trees"."token" IS NULL

**user.family_members.to_sql**
SELECT "users".* FROM "users" 
INNER JOIN "family_trees" ON "users"."id" = "family_trees"."member_id" 
INNER JOIN "families" ON "family_trees"."family_id" = "families"."id" 
INNER JOIN "family_trees" "family_trees_family_members" ON "families"."id" = "family_trees_family_members"."family_id" 
WHERE "family_trees_family_members"."member_id" = 1 
AND "family_trees"."token" IS NULL

**User.where(id: FamilyTree.where(family: family, token: nil).pluck(:member_id)).to_sql**
Executes the query in two steps:
1st step
SELECT "family_trees"."member_id" FROM "family_trees" WHERE "family_trees"."family_id" = 1 AND "family_trees"."token" IS NULL

2nd step
SELECT "users".* FROM "users" WHERE "users"."id" IN (1, 2)

Can you please explain what behavior do you expect from: **user.family.members**

**Comment by hjinu** [comment]
`user.family.members` has no problems. `user.family_members` is different from what I expected.

As @al2o3cr said, 

`
SELECT "users".* FROM "users"
INNER JOIN "family_trees" ON "users"."id" = "family_trees"."member_id"
INNER JOIN "families" ON "family_trees"."family_id" = "families"."id"
INNER JOIN "family_trees" "family_trees_family_members" ON "families"."id" = "family_trees_family_members"."family_id"
WHERE "family_trees_family_members"."member_id" = ?
AND "family_trees"."token" IS NULL
>>>>> THIS IS CURRENT SQL CODE
AND "family_trees"."token" IS NULL
----------------------------------------------------
<<<<< THIS IS WHAT I EXPECTED
AND "family_trees_family_members"."token" IS NULL
`
