### ISSUE TITLE
Calling path_to_stylesheet from job give different results than view

### ISSUE THREAD

**Issue by stoivo** [rails/rails#27671]
### Steps to reproduce
I started both rails server and rails console with RAILS_ENV=production

In view 
```ruby
extend ActionView::Helpers::AssetTagHelper
=> ....(including all paths with digest)
path_to_stylesheet('application')
=> "/assets/application-477467a41f81a8f91475e45831103e4c4eba2d6b666cc38251bdeb6a7f08c6e4.css"
```
in job and console
```ruby
extend ActionView::Helpers::AssetTagHelper
=> main
path_to_stylesheet('application')
=> "/stylesheets/application.css"
```

### Expected behavior
We would like to have the same result in job as in view.

### Actual behavior
In jobs it returns "/stylesheets/application.css" while "/assets/application-477467a41f81a8f91475e45831103e4c4eba2d6b666cc38251bdeb6a7f08c6e4.css" in view.

### System configuration
**Rails version**: 4.2.2

**Ruby version**: 2.2.2

**Comment by rafaelfranca** [comment]
This is the expected behavior. You only included the action view helpers in the job not the sprockets helpers so you don't have the sprockets behavior.
