### ISSUE TITLE
find_by_sql("select sum(price) from orders"),return [order: id:nil], not sum(price)?

### ISSUE THREAD

**Issue by KevinLion** [rails/rails#27678]
### Steps to reproduce

(Guidelines for creating a bug report are [available
here](http://guides.rubyonrails.org/contributing_to_ruby_on_rails.html#creating-a-bug-report))

### Expected behavior
find_by_sql("select sum(price) from orders"),return [order: id:nil], not sum(price)?
![image](https://cloud.githubusercontent.com/assets/4750194/21951808/33b5ab1a-da48-11e6-8a2e-10959b47c985.png)

### Actual behavior
Tell us what happens instead

### System configuration
**Rails version**: 5.0.1

**Ruby version**:ruby 2.3.0p0 (2015-12-25 revision 53290) [x86_64-darwin15]

**Comment by matthewd** [comment]
Please use the mailing list or StackOverflow for questions/help, where a wider community will be able to help you. We reserve the issues tracker for issues only.

**Comment by KevinLion** [comment]
The sql does not have error. I search on stackOverflow ,So I consider that rails has some mistakes with deal with mysql.
