### ISSUE TITLE
Wrong SQL syntax is generated when count is called on limit and custom select

### ISSUE THREAD

**Issue by cmrd-senya** [rails/rails#27676]
### Steps to reproduce

You can find a reproducible test case [here](https://gist.github.com/cmrd-senya/98fc3b9f8c7fcebb170b0f8e7428c068).

Construct a query with:
1. select with custom SQL
2. limit
3. count

For instance:
```ruby
Post.select("id, some_property IS NOT NULL AS with_comment").limit(5).count
```

### Expected behavior
The query is executed properly

### Actual behavior
The query fails because the constructed SQL is broken:
```sql
SELECT COUNT(count_column) FROM (SELECT  id, some_property IS NOT NULL AS with_comment AS count_column FROM "posts" LIMIT ?) subquery_for_count
```

### System configuration
**Rails version**: master

**Ruby version**: ruby 2.3.3p222 (2016-11-21 revision 56859) [x86_64-linux-gnu]

**Comment by coreyward** [comment]
This is a little hard to unpack. Can you help clarify which issue you're referring to, how it should be handled (i.e. what should the SQL be?), and why ActiveRecord should handle it?

For what it's worth, these both work fine:

```ruby
User.select('id').limit(5).count
```
```sql
SELECT COUNT(count_column) FROM (SELECT  "users"."id" AS count_column FROM "users" LIMIT 5) subquery_for_count;
```
```ruby
User.select('id', 'id is not null').limit(5).count
```
```sql
SELECT COUNT(count_column) FROM (SELECT  id, id is not null AS count_column FROM "users" LIMIT 5) subquery_for_count;
```

**Comment by cmrd-senya** [comment]
I'm not sure this issue is something really major. We managed to easily workaround it by changing from `.count` to `.size` because it were in tests, so performance was less important. However I'm sure that the fact that Rails constructs invalid SQL from elements which are valid by themselves is something wrong.

**Comment by kamipo** [comment]
Originally not all valid `Relation#select` expressions are valid `count` expressions.
http://api.rubyonrails.org/classes/ActiveRecord/Calculations.html#method-i-count
https://github.com/rails/rails/blob/v5.0.1/activerecord/test/cases/calculations_test.rb#L221-L228

**Comment by cmrd-senya** [comment]
The doc you referenced says "In invalid cases, an error from the database is thrown". Does it imply exception because of incorrect SQL generated by Rails?

**Comment by kamipo** [comment]
Yes, the following case, `Account.select("credit_limit, firm_name").count` generates `SELECT COUNT(credit_limit, firm_name) FROM "accounts"`, COUNT with multiple columns is invalid SQL.

https://github.com/rails/rails/blob/v5.0.1/activerecord/test/cases/calculations_test.rb#L221-L228

```ruby
  def test_count_on_invalid_columns_raises
    e = assert_raises(ActiveRecord::StatementInvalid) {
      Account.select("credit_limit, firm_name").count
      # => SELECT COUNT(credit_limit, firm_name) FROM "accounts"
    }

    assert_match %r{accounts}i, e.message
    assert_match "credit_limit, firm_name", e.message
  end
```

**Comment by cmrd-senya** [comment]
Ok, then I agree that it can't be considered a bug!
