### ISSUE TITLE
`validates_associated` causes premature collection proxy loading

### ISSUE THREAD

**Issue by tjjjwxzq** [rails/rails#27685]
### Steps to reproduce
Say I have a `Thing` model:

```ruby
class Thing < ActiveRecord::Base

  has_many :comments
  validates_associated :comments

  validates :name, presence: true
  validates :description, presence: true

end
```
and a `Comment` model

```ruby
class Comment < ActiveRecord::Base

  belongs_to :thing

  validates :title, presence: true
  validates :body, presence: true

end
```
If we try the following in the console:
```ruby
> thing = Thing.create(name: "Thing", description: "A thing")
> Comment.create(title: "Comment", body: "A comment", thing: thing)
> thing.comments
=> #<ActiveRecord::Associations::CollectionProxy []> # this is empty, which is not expected behaviour
```

Now we remove `validates_associated`:
```ruby
class Thing < ActiveRecord::Base

  has_many :comments
  # validates_associated :comments

  validates :name, presence: true
  validates :description, presence: true

end
```
Now the console session again:
```ruby
> thing = Thing.create(name: "Thing", description: "A thing")
> Comment.create(title: "Comment", body: "A comment", thing: thing)
> thing.comments
=> # <ActiveRecord::Associations::CollectionProxy [#<Comment id: 7, title: "comment", body: "sdfds", thing_id: 4>]> # this is expected
```

This caught me unaware when I wrote my factories:
```ruby
FactoryGirl.define do

  factory :thing do
    name "Thing"
    description "A thing"

    transient do
      comments_count 3
    end

    trait :with_comments do
      after(:build) do |thing, evaluator|
        create_list(:comment, evaluator.comments_count, thing: thing)
      end
    end
  end

end
```

Because of `validates_associated` causing premature proxy-loading, the following specs will fail:
```ruby
require 'rails_helper'

RSpec.describe Thing, type: :model do

  describe 'comments' do
    subject { create(:thing, :with_comments) }

    it { expect(subject.comments).not_to be_empty }
  end

end
```

What happens is that the `AssociatedValidator` is calling `to_ary` on the collection proxy:
```ruby
module ActiveRecord
  module Validations
    class AssociatedValidator < ActiveModel::EachValidator #:nodoc:
      def validate_each(record, attribute, value)
        # calling 
        if Array(value).reject { |r| valid_object?(r) }.any?
          record.errors.add(attribute, :invalid, options.merge(value: value))
        end
      end
...
```
This calls `load_target` on the association which sets the loaded flag to true while the proxy is still empty (before the `Thing` object is saved, and has the `Comment` object associated to it); thus the proxy becomes stale.

Can we `reload` the `value` if `value.is_a?(ActiveRecord::Associations::CollectionProxy` ?

### Expected behavior
```ruby
> thing = Thing.create(name: "Thing", description: "A thing")
> Comment.create(title: "Comment", body: "A comment", thing: thing)
> thing.comments
=> # <ActiveRecord::Associations::CollectionProxy [#<Comment id: 7, title: "comment", body: "sdfds", thing_id: 4>]> # this is expected
```
### Actual behavior
```ruby
> thing = Thing.create(name: "Thing", description: "A thing")
> Comment.create(title: "Comment", body: "A comment", thing: thing)
> thing.comments
=> #<ActiveRecord::Associations::CollectionProxy []> # this is empty, which is not expected behaviour
```

### System configuration
**Rails version**: 5.0.1

**Ruby version**: 2.3.1

**Comment by al2o3cr** [comment]
I don't see anywhere in your example that the framework *could* reload the association proxy. `validates_associated` needs the collection to be loaded, so it is loaded when `Thing` saves. 

If you want a newly-added record to be reflected in the already-loaded association, use the association proxy to create it:
```ruby
thing.comments.create(...)
# now thing.comments has the new object
```

**Comment by tjjjwxzq** [comment]
Hmmm, could we not just do something like 

```ruby
module ActiveRecord
  module Validations
    class AssociatedValidator < ActiveModel::EachValidator #:nodoc:
      def validate_each(record, attribute, value)
        # calling 
        if Array(value).reject { |r| valid_object?(r) }.any?
          record.errors.add(attribute, :invalid, options.merge(value: value))
        end
        value.reload if value.is_a?(ActiveRecord::Associations::CollectionProxy)
      end
...
```

And yes, I'm aware that we could create the associated record on the collection proxy itself, but I think this change in behaviour is going to catch people unaware who add associations to their factories the way I did in my example, and I don't think it's reasonable to expect people to realize that adding `validates_associated` is going to the change the result of calling the association reader in any way.

**Comment by matrix9180** [comment]
Would your change really fix the issue? Wouldn't the `CollectionProxy` still be empty even if reloaded there as `thing` is still created/validated before the comment is created?

**Comment by matrix9180** [comment]
Interesting bug though - isn't it safe to assume a has_many association won't have anything to load from the database on a record being created?

**Comment by tjjjwxzq** [comment]
I have tested it locally, and it seems to work. And I don't understand really why this is happening and when the validation is getting called, but it seems to be getting called twice, once when the proxy is properly empty and once after associated records have actually been assigned.

```
Interesting bug though - isn't it safe to assume a has_many association won't have anything to load from the database on a record being created?
```
If the associated records are being created together with the parent records, then they will be saved first before the parent record is saved, wouldn't they?

**Comment by composerinteralia** [comment]
I messed around with this for a while today. One extreme solution is just to avoid caching associations altogether when validating.

The note above `invertible_for?` also seems relevant: https://github.com/rails/rails/blame/master/activerecord/lib/active_record/associations/belongs_to_association.rb

**Comment by magpieuk** [comment]
Had something similar but not sure if its related. We have a Contact that belongs_to a primary_primary location but its actually a Location. The contact accepts nested attributes and also validates associated.

```
  belongs_to :primary_location, :foreign_key => :location_id, :class_name => "Location"
  accepts_nested_attributes_for :primary_location
  validates_associated :primary_location
```
We were getting a very strange error where the values of the primary location were having valid? called on them. Looking at the Rails code it seems the issue is with the ActiveRecord::Validations::AssociatedValidator this used to call Array.wrap(value) but now calls Array(value) which is taking the location object and calling to_a on it, resulting in an array of the values.  

Changing the code back to Array.wrap seems to do the trick. Any ideas?
