### ISSUE TITLE
Can anyone help me

### ISSUE THREAD

**Issue by prabin12** [rails/rails#27691]
hi 
I want to auto save data created in description method. but I could not save it. Please anyone can help me.
class Room < ApplicationRecord
	 auto_save :description 
	
def description
        letters = (0..9).to_a + ('a'..'z').to_a + ('A'..'Z').to_a # add or remove possibilities
self. description = letters.sample(6).join
end

end

**Comment by kamipo** [comment]
Please use the mailing list or StackOverflow for questions/help, where a wider community will be able to help you. We reserve the issues tracker for issues only.
