### ISSUE TITLE
Why delete_all on dependent option rather than delete ?

### ISSUE THREAD

**Issue by Hugo-Hache** [rails/rails#27698]
While inspecting the different value of the dependent option, I was surprised that all the values are phrased as a verb alone (`destroy`, `nullify`, `restrict_with_exception`, `restrict_with_error`), outside delete which is suffixed by _all (`delete_all`).

Is there a specific reason for this ?

**Comment by rafaelfranca** [comment]
To match the name of the method that is called in the association. When the option was added `destroy_all` still didn't exist otherwise `destroy` value would be `destroy_all`.
