### ISSUE TITLE
Rails::MailersController#preview - can't modify frozen String

### ISSUE THREAD

**Issue by vemv** [rails/rails#27702]
Hi, the following should be self explanatory. My bet is that this is easy to fix, so creating a repro might be bit of useless work.

## Backtrace (screenshot and text)

![image](https://cloud.githubusercontent.com/assets/1162994/21992981/f499013e-dc18-11e6-8538-8810ea0dca52.png)

```
, [2017-01-16T18:19:42.451255 #88587] FATAL -- : RuntimeError (can't modify frozen String):
F, [2017-01-16T18:19:42.451344 #88587] FATAL -- :
F, [2017-01-16T18:19:42.451432 #88587] FATAL -- : actionmailer (5.0.1) lib/action_mailer/inline_preview_interceptor.rb:29:in `gsub!'
actionmailer (5.0.1) lib/action_mailer/inline_preview_interceptor.rb:29:in `transform!'
actionmailer (5.0.1) lib/action_mailer/inline_preview_interceptor.rb:19:in `previewing_email'
actionmailer (5.0.1) lib/action_mailer/preview.rb:113:in `block in inform_preview_interceptors'
actionmailer (5.0.1) lib/action_mailer/preview.rb:112:in `each'
actionmailer (5.0.1) lib/action_mailer/preview.rb:112:in `inform_preview_interceptors'
actionmailer (5.0.1) lib/action_mailer/preview.rb:67:in `call'
railties (5.0.1) lib/rails/mailers_controller.rb:22:in `preview'
actionpack (5.0.1) lib/action_controller/metal/basic_implicit_render.rb:4:in `send_action'
actionpack (5.0.1) lib/abstract_controller/base.rb:188:in `process_action'
actionpack (5.0.1) lib/action_controller/metal/rendering.rb:30:in `process_action'
actionpack (5.0.1) lib/abstract_controller/callbacks.rb:20:in `block in process_action'
activesupport (5.0.1) lib/active_support/callbacks.rb:126:in `call'
activesupport (5.0.1) lib/active_support/callbacks.rb:506:in `block (2 levels) in compile'
activesupport (5.0.1) lib/active_support/callbacks.rb:455:in `call'
activesupport (5.0.1) lib/active_support/callbacks.rb:101:in `__run_callbacks__'
activesupport (5.0.1) lib/active_support/callbacks.rb:750:in `_run_process_action_callbacks'
activesupport (5.0.1) lib/active_support/callbacks.rb:90:in `run_callbacks'
actionpack (5.0.1) lib/abstract_controller/callbacks.rb:19:in `process_action'
actionpack (5.0.1) lib/action_controller/metal/rescue.rb:20:in `process_action'
actionpack (5.0.1) lib/action_controller/metal/instrumentation.rb:32:in `block in process_action'
activesupport (5.0.1) lib/active_support/notifications.rb:164:in `block in instrument'
activesupport (5.0.1) lib/active_support/notifications/instrumenter.rb:21:in `instrument'
activesupport (5.0.1) lib/active_support/notifications.rb:164:in `instrument'
actionpack (5.0.1) lib/action_controller/metal/instrumentation.rb:30:in `process_action'
actionpack (5.0.1) lib/action_controller/metal/params_wrapper.rb:248:in `process_action'
activerecord (5.0.1) lib/active_record/railties/controller_runtime.rb:18:in `process_action'
actionpack (5.0.1) lib/abstract_controller/base.rb:126:in `process'
actionview (5.0.1) lib/action_view/rendering.rb:30:in `process'
actionpack (5.0.1) lib/action_controller/metal.rb:190:in `dispatch'
actionpack (5.0.1) lib/action_controller/metal.rb:262:in `dispatch'
actionpack (5.0.1) lib/action_dispatch/routing/route_set.rb:50:in `dispatch'
actionpack (5.0.1) lib/action_dispatch/routing/route_set.rb:32:in `serve'
actionpack (5.0.1) lib/action_dispatch/journey/router.rb:39:in `block in serve'
actionpack (5.0.1) lib/action_dispatch/journey/router.rb:26:in `each'
actionpack (5.0.1) lib/action_dispatch/journey/router.rb:26:in `serve'
actionpack (5.0.1) lib/action_dispatch/routing/route_set.rb:725:in `call'
```

### System configuration

**Rails version**:

5.0.1

**Ruby version**:

2.4.0

Cheers - Victor

**Comment by maclover7** [comment]
Can you please provide a sample application that replicates the error you are seeing? Also, have you encountered this on any versions of Rails before 5.0.1?

**Comment by vemv** [comment]
I cannot reproduce the error anymore.

Also I can't provide a minimal, open-source reproduction. That'd be a lot of work in comparison to the work of guessing the actual issue (modifying a frozen string). Or at least I hope so.

Feel free to close

**Comment by pixeltrix** [comment]
@vemv going to close this since it's likely that something called `freeze` on the rendered content and duping the whole HTML because it might have been frozen by something else external to Rails isn't something we want to do. Will reopen if you have new/more information.

**Comment by vemv** [comment]
Good, no issue!

I'd just add the observation that perhaps it's not safe (or even actually needed) to attempt to modify the string. I'm not very familiar with AM though - just throwing ideas around

Cheers - Victor

**Comment by pixeltrix** [comment]
The `ActionMailler::InlinePreviewInterceptor` class rewrites `<img src="cid:xxx">` to data uris so that the previews work in a web browser. Not possible without modification of the HTML source and as I said we don't want to dup it. If for some reason you need frozen mail bodies then you can disable the feature using the following: 

``` ruby
ActionMailer::Base.preview_interceptors.delete(ActionMailer::InlinePreviewInterceptor)
```

**Comment by eugeneius** [comment]
In https://github.com/mikel/mail/pull/1001, @jeremy said:

> Mutating `raw_source` directly is going to be (very) error-prone and generally undesirable. Consider gsubbing against each part's decoded body and assigning the body back to the part.

It seems that the mail gem and Action Mailer disagree on how `raw_source` should be used.

**Comment by jeremy** [comment]
Mutating `raw_source` directly is risky for general use since other memoized properties may be derived from it. It's typically the encoded MIME part—including headers.

In this case, we're intercepting a message just after the HTML part was rendered, meaning it'll work in most cases. Some uncommon scenarios may fail, like redelivering a received message or rendering an HTML part from a template engine that freezes its output.

Work putting some work into this, if you're interested, even if just for its own sake (rather than treating "works with frozen raw sources" as a feature).

Essential idea would be to `html_part.body = html_part.decoded.gsub(…)` instead of `html_part.body.raw_source.gsub!(…)`.

**Comment by eugeneius** [comment]
Thanks for the pointer! I've opened https://github.com/rails/rails/pull/27854 with that change.

**Comment by edgartheunready** [comment]
I personally had this issue when the html and text templates for my email were completely blank. Adding content to them resolved the issue.
