### ISSUE TITLE
Rails rails generate controller to add missing view file got error.

### ISSUE THREAD

**Issue by zw963** [rails/rails#27708]
For my case, I almost all I need file except view, as following

```sh
app/controllers/xxx_www/publish/posts_controller.rb  # exist
app/views/xxx_www/publish/posts  # exist
test/controllers/xxx_www/publish/posts_controller_test.rb #exist
app/views/xxx_www/publish/posts/new.html.slim  # this file is missing ...
```

so, I run `rails g controller` to try to add this missing file.

```sh
$ rails generate controller xxx_www/publish/posts new --skip --skip-routes --helper=false --assets=false
```

Got following error:

```sh
The name 'XxxWww::Publish::PostsController' is either already used in your application or reserved by Ruby on Rails. Please choose an alternative and run this generator again.
```

**Comment by sevenseacat** [comment]
Generating a controller doesn't generate view files with any content, you might be thinking of scaffolds. In any case, you can simply create the missing file yourself.

**Comment by zw963** [comment]
@sevenseacat 

Current project file/directory struction is complicated.

So, I just create a bash shell script which invoke `rails generate controller`
to add missing file to correct position, so,  this function is useful enough for me.

Thanks.

**Comment by sevenseacat** [comment]
It might be useful for you, it doesnt make sense to use a _controller_ generator to generate a missing _view_ file for a controller that already exists.

**Comment by zw963** [comment]
BTW:  This not always not work ...

I try it again in another terminal, it worked now.

```sh
Running via Spring preloader in process 9772
        skip  app/controllers/xxx_www/publish/posts_controller.rb
      invoke  slim
       exist    app/views/xxx_www/publish/posts
       create  app/views/xxx_www/publish/posts/create.html.slim
      invoke  test_unit
        skip    test/controllers/xxx_www/publish/posts_controller_test.rb
       error  false [not found]
       error  false [not found]
```

Seem like it not stable if run with different file, e.g.


```sh
# success
rails generate controller xxx_www/publish/posts new --skip --skip-routes --helper=false --assets=false
```
```sh
# failed
rails generate controller xxx_www/publish/goods_items new --skip --skip-routes --helper=false --assets=false
```

**Comment by rafaelfranca** [comment]
I'm not sure what is the issue here? Could you add how to reproduce it?

**Comment by zw963** [comment]
@rafaelfranca , Could not, sorry, If it occur again, i will reopen this issue.

Thanks.
