### ISSUE TITLE
Guides: Rails Internationalization (I18n) API - 4.2 Pluralization - broken link

### ISSUE THREAD

**Issue by maxcal** [rails/rails#27711]
> In English there are only one singular and one plural form for a given string, e.g. "1 message" and "2 messages". Other languages (Arabic, Japanese, Russian and many more) have different grammars that have additional or fewer plural forms. Thus, the I18n API provides a flexible [pluralization](http://unicode.org/repos/cldr-tmp/trunk/diff/supplemental/language_plural_rules.html) feature.

The link to unicode.org is no longer valid and should be should be http://cldr.unicode.org/index/cldr-spec/plural-rules

**Comment by rafaelfranca** [comment]
Could you send a PR?

**Comment by matrix9180** [comment]
I don't see this specific problem on [edge guides](http://edgeguides.rubyonrails.org/i18n.html#pluralization) or [guides](http://guides.rubyonrails.org/i18n.html#pluralization) but the links on Arabac, Japanese, Russian, and plural forms are indeed broken.

**Comment by y-yagi** [comment]
This fixed by #27723
