### ISSUE TITLE
send email error connection reset by peer - SSL_connect

### ISSUE THREAD

**Issue by hendranata** [rails/rails#27729]
### Steps to reproduce
i have problem when sending email using SMTP TLS/SSL..
it was working fine but now has a problem.. all the email cant be send and detail described in Actual behavior.

### Expected behavior
the email should send successfully

### Actual behavior
when sending email..error message like this:
UserMailer#notification: processed outbound mail in 162.3ms

Sent mail to hendranatas@yahoo.com (545.5ms)
Date: Wed, 18 Jan 2017 20:35:12 +0700
From: system@xxx.com
To: xxx@yahoo.com
Message-ID: <587f6f10c21c9_78e28d30ec47753@xxx-HP-Pro-3330-MT.mail>
Subject: [PO Notification] number: xxxxxx
Mime-Version: 1.0
Content-Type: text/html;
 charset=UTF-8
Content-Transfer-Encoding: base64

PT09PT09PT09PT09PT09PT09IEJBSEFTQSBJTkRPTkVTSUEgPT09PT09PT09
PT09PT09PT09PT08YnI+PGJyPgoKVGVyZGFwYXQgbm90aWZpa2FzaSBQTyBi
YXJ1IHVudHVrIGFuZGE8YnI+PGJyPgoKPGI+bm9tb3IgUE86PC9iPiBEQ0kz
MTUxMjAwMDE8YnI+CjxiPlBPIGRpYnVhdCB0YW5nZ2FsOjwvYj4gMDEtMTIt
MjAxNSAxMToxNDoyOTxicj4KPGI+UE8gZGlidWF0IG9sZWg6PC9iPiBFcmZp
bmEgT3U8YnI+CjxiPkRlcGFydG1lbnQ6PC9iPiBNYWludGVuYW5jZTxicj4K
PGI+U3RhdHVzOjwvYj4gRmluaXNoPGJyPjxicj4KCjxwPlNpbGFoa2FuIGxv
Z2luIGtlIGhhbGFtYW4gUE8gPGEgaHJlZj0iaHR0cDovLzE4MC4yNTAuMTY5
LjE3MC8iPmJlcmlrdXQgaW5pLjwvYT48L3A+CjxwPlRlcmltYWthc2loPC9w
Pgo8YnI+PGJyPgo9PT09PT09PT09PT09PT09PT09PSBDSElORVNFID09PT09
PT09PT09PT09PT09PT09PT09PT09PT09PQoK5pyJ5paw5o6h6LO85Zau6aCI
57C95qC4PGJyPjxicj4KCjxiPuaOoeizvOWWruiZn+eivDo8L2I+IERDSTMx
NTEyMDAwMTxicj4KPGI+6KO95Zau5pel5pyfOjwvYj4gMDEtMTItMjAxNSAx
MToxNDoyOTxicj4KPGI+6KO95Zau6ICFOjwvYj4gRXJmaW5hIE91PGJyPgo8
Yj7pg6jploA6PC9iPiBNYWludGVuYW5jZTxicj4KPGI+5oOF5rOBOjwvYj4g
RmluaXNoPGJyPjxicj4KCjxwPuiri+m7numAo+e1kOWIsOaOoeizvOWWriA8
YSBocmVmPSJodHRwOi8vMTgwLjI1MC4xNjkuMTcwLyI+5paw5o6h6LO85Zau
PC9hPjwvcD4KPHA+6Kyd6KydPC9wPgo8YnI+PGJyPg==

Errno::ECONNRESET: Connection reset by peer - SSL_connect
	from /home/globalway/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/net/smtp.rb:587:in `connect'
	from /home/globalway/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/net/smtp.rb:587:in `tlsconnect'
	from /home/globalway/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/net/smtp.rb:555:in `do_start'
	from /home/globalway/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/net/smtp.rb:521:in `start'

### System configuration
**Rails version**: 4.2.4

**Ruby version**: 2.3

**Comment by rafaelfranca** [comment]
Thanks for the issue. This is a issue with your smtp server. Make sure it is working fine

**Comment by hendranata** [comment]
This is working fine in my local computer.. But not work in server. We have sure that development and production setting smtp are the same and correct
