### ISSUE TITLE
Replace byebug with binding.irb when RUBY_VERSION >= "2.4.0"

### ISSUE THREAD

**Issue by jtrost** [rails/rails#27745]
After upgrading a few Rails applications to Ruby 2.4, I've found myself removing the `byebug` gem and replacing it with this code in `config/application.rb`:
````ruby
if Rails.env.development? || Rails.env.test?
  require 'irb'
end
````
This allows `binding.irb` to be called anywhere in the application in the development and test environments. I would like to discuss if `binding.irb` a suitable replacement for `byebug`, and if a pull request that made this change would be welcome.

**Comment by bogdanvlviv** [comment]
We can't [byebug](https://github.com/deivid-rodriguez/byebug) has functionality([Byebug's commands](https://github.com/deivid-rodriguez/byebug#byebugs-commands)) that help debug code.

**Comment by rafaelfranca** [comment]
Yeah, until we have a full debug built-in in irb I think it is better to stick with byebug. Thank you for the issue.
