### ISSUE TITLE
Find doesn't work in thread

### ISSUE THREAD

**Issue by lets2009** [rails/rails#27747]
### Steps to reproduce

items_controller.rb

  def print
    t = Thread.new do 
      begin
        Item.find(1)
      ensure
      end
    end
    t.join
  end

### Expected behavior
Find works, and server return respons.

### Actual behavior
Thread not terminate. Browser was waiting respons for a long time and console don't show the sql.
It works on rails 4.2.7, but on rails5, not.

**Rails version**:
ruby 2.3.3p222 (2016-11-21 revision 56859) [i386-mingw32]
**Ruby version**:
Rails 5.0.1

**Comment by matrix9180** [comment]
Confirmed against v5.0.1 & master, ruby 2.4.0

**Comment by lets2009** [comment]
Thenk you.
I confirmed with ruby 2.4. And The results were the same.
ruby version.( I confirmed with both versions)
ruby 2.4.0p0 (2016-12-24 revision 57164) [i386-mswin32_100]
ruby 2.4.0p0 (2016-12-24 revision 57164) [x64-mswin64_100]

**Comment by arthurnn** [comment]
What is your connection pool size?
ActiveRecord, needs a new connection from the pool to use that in threads.
Also, you could have some db level locking happening, which might be blocking the thread. 

I am not sure this is a ActiveRecord bug, as we don't force any locking on the `find` code path.

**Comment by lets2009** [comment]
Thank you for your question.
The connection pool size of my app is 5, as default value of new application.
And I have no db level locking, one 'find' operation only.
I found a new Thing now.
If there is no record in db and ActiveRecord throw exception, rails returns respons.
But if there is a record in db and ActiveRecord don't throw exception, rails don't returns respons.
Thank you for your works.

**Comment by arthurnn** [comment]
hey @lets2009 , can you create an isolated app that simulates the issue? or a one file script?
You can follow this example https://github.com/rails/rails/blob/master/activerecord/examples/simple.rb

thanks

**Comment by bmclean** [comment]
@lets2009 I have seen the same deadlock when using threads within a controller action. Take a look at the solution presented in issue #26847.
