### ISSUE TITLE
image_tag

### ISSUE THREAD

**Issue by Captainkirkdawson** [rails/rails#27741]
I have one windows developer who receives

ActionView::Template::Error (TypeError: Object doesn't support this property or method):
   
    24:             <%= image_tag "info.png", alt: "Info", size: "16x16" %>
  

Other windows developers and Linux developers do not experience the issue nor does a production server exhibit issue

This developer is able to use a website running this code

Also happens  with <%= image_tag( "info.png", alt: "Info", size: "16x16") %>

Does not happen with <%= image_tag "image/info.png", alt: "Info", size: "16x16" %>

### System configuration

Windows 10; all browsers

'rails', '4.2.6'

ruby 2.2.6

**Comment by rafaelfranca** [comment]
Can you please provide a sample application that reproduces the error?

**Comment by Captainkirkdawson** [comment]
Unfortunately not as it only fails on one persons implementation of  ruby . 

I understand you may not be able to assist without a reproducible piece of code but I am at lose on how to diagnose the problem on that implementation.

**Comment by rafaelfranca** [comment]
Yeah, unfortunately there is nothing we can do in this case. I recommend seeing if the permission of the directories are correct and that the rails process can access the image.

**Comment by Captainkirkdawson** [comment]
@rafaelfranca  but is that not a compile time message rather than an execution time message i.e

**Comment by rafaelfranca** [comment]
This looks like a JavaScript error when trying to compile all the assets. You can see if you can reproduce it running `bin/rake assets:precompile`
