### ISSUE TITLE
Broken links for ActiveRecord README

### ISSUE THREAD

**Issue by jondayton** [rails/rails#27753]
### Steps to reproduce

* [view activerecord readme](/rails/rails/blob/master/activerecord/README.rdoc)
* Click on any of the "Learn More" links

**Comment by jondayton** [comment]
I'm happy to put in a PR, but should the links go to the guides site or to the corresponding github pages?

**Comment by vipulnsward** [comment]
https://github.com/rails/rails/pull/26141#issuecomment-239517131
