### ISSUE TITLE
documentation for managing database connections

### ISSUE THREAD

**Issue by jjb** [rails/rails#27759]
As far as I can tell there exists no documentation for how to manage database connections in various situations.

The documentation for the methods themselves is good.

* http://api.rubyonrails.org/classes/ActiveRecord/ConnectionAdapters/AbstractAdapter.html
* http://api.rubyonrails.org/classes/ActiveRecord/ConnectionAdapters/ConnectionPool.html

But it's not clear what rails will automagically do for me and what I should deal with myself. Between blog posts, third-party documentation, and implementation of various tools, one can make a guess. But these sources don't agree with one another. To add to this confusion, Rails' behavior has changed over the years, and it's not clear if the blog posts match up with the latest behavior.

### relevant methods I'm aware of

 - `ActiveRecord::Base.establish_connection`
 - `ActiveRecord::Base.connection_pool.disconnect!`
 - `ActiveRecord::Base.connection.disconnect!`
 - `ActiveRecord::Base.connection.reconnect!`
 - `ActiveRecord::Base.clear_active_connections!`

### sources of information

* https://github.com/puma/puma-heroku/blob/master/lib/puma/plugin/heroku.rb
* https://github.com/grosser/parallel#activerecord
* https://devcenter.heroku.com/articles/deploying-rails-applications-with-the-puma-web-server#on-worker-boot
* https://devcenter.heroku.com/articles/concurrency-and-database-connections#threaded-servers
* https://tenderlovemaking.com/2011/10/20/connection-management-in-activerecord.html

### examples

Here's an example of what I want to know how to do. I think it's probably pretty generically representative of many process and thread situations.

A worker script, runner.rb, is run with `rails runner`:

```ruby
Process.fork
  ProcessFoos.run
end

Process.fork
  ProcessBars.run
end
```

Also, inside `ProcessFoo.run`, a thread is sometimes started:

```ruby
class ProcessFoo
  def run
    loop do
      # do things
      start_sub_thread if something?
      sleep 10
    end
  end

  def start_sub_thread
    Thread.new do
      # do other things
    end
  end
end
```

### Questions I have

* When forking a process, what should be done at the top of the process?
* When starting a thread, what should be done at the start and end of the thread?
* After forking a process, what should be done?
* After starting a thread, what should be done?

I have a pretty good guess about most of these, and have implemented code that works, but I couldn't explain to you why different documentation suggests using different combinations of the above methods for seemingly the same ends.

If some more guidance around these issues is shared here, then I'll be happy to put together some documentation about it. In fact, maybe it can be a new standalone guide, maybe about concurrency.

Thanks!

**Comment by jjb** [comment]
After some more experimentation, I've realized I have this more specific problem, which perhaps serves as a good encapsulation of the overall problem of lack of documentation and/or a failing int the api.

When making a subprocess, I don't want the parent process to have to reconnect in order to continue its work. so...

```ruby
# .. do work
5.times do
  Process.fork do
    ActiveRecord::Base.establish_connection
    ## do subwork
    ## do subwork
  end
end
ActiveRecord::Base.connection.reconnect!
# ... do work
```

What I would like to do is not have to do `ActiveRecord::Base.connection.reconnect!` after forking the processes. I just want the subprocesses to create their own connection and not discard the parent connections. Is this possible?

**Comment by jjb** [comment]
after much experimentation and errors, I found another method, not listed above, which solved my particular problem. `ActiveRecord::Base.clear_active_connections!`

**Comment by arthurnn** [comment]
> I just want the subprocesses to create their own connection and not discard the parent connections. Is this possible?

If you are using mysql2, that's a known behaviour there. see https://github.com/brianmario/mysql2/issues/606

As far as I remember, what happens is: because the forked process still has a reference to the parent, when the forked process gets GCed, mysql2 gem will close the socket. Even if the socket is still in use by the parent itself.

The Rails solution for that, is to call `disconnect` before forking a process: https://devcenter.heroku.com/articles/forked-pg-connections

@matthewd and I talked about a possible solution there, which includes adding a `at_exit` hook, to the process, so we would do something about that connection.
This is still at the drawing board stage TBH. 

What I would suggest is to add that `disconnect` before you fork the process (in the parent). Or you could change the mysql2 gem, or whatever gem/adapter you are using.

Talking about the docs. I think Rails Guides could have a dedicated doc for AR connections.
Fell free to open a PR to start the work.

**Comment by jjb** [comment]
Thanks for the feedback and info!

> What I would suggest is to add that `disconnect` before you fork the process (in the parent). Or you could change the mysql2 gem, or whatever gem/adapter you are using.

So you're saying I just need that one disconnect, and then my subprocesses and the continued parent process will automatically reconnect?

Sure, that works, and is a bit tidier goal, but my goal is to disconnect as little as possible. So I'd like the forked processes to just forget they ever had connections and re-make their own, instead of discarding their parent connections. The parent process can then keep the same connection pool forever.

>  I think Rails Guides could have a dedicated doc for AR connections.
Fell free to open a PR to start the work.

K, I'll try to start something in the next few weeks.

**Comment by jjb** [comment]
@arthurnn (or anyone else who knows) -- could you answer my questions above? Then I'll put together the PR.

**Comment by arthurnn** [comment]
> So you're saying I just need that one disconnect, and then my subprocesses and the continued parent process will automatically reconnect?

That's right.

>  Sure, that works, and is a bit tidier code, but my goal is to disconnect as little as possible. So I'd like the forked processes to just forget they ever had connections ...

Right now that's not possible. You need to disconnect from the parent.

**Comment by jjb** [comment]
🎉 https://github.com/rails/rails/pull/29807

**Comment by jjb** [comment]
Hello @rails-bot. I have provided a reproduction repo above 😄

**Comment by jjb** [comment]
see work and discussion in #29807
