### ISSUE TITLE
Different configs objects?

### ISSUE THREAD

**Issue by mariogintili** [rails/rails#27752]
### Steps to reproduce

```ruby
Rails.application.configure do |config|
  config.foo = "1"
end
```

throws an exception `NoMethodError foo=`

However

```ruby
Rails.application.configure do
  config.foo = "1"
end
```

does not.

### Expected behavior

Declaring `config` as an argument should have the same behaviour inside of the block as if it didn't otherwise this can confuse framework users

### System configuration

**Rails version**: `Rails 5.0.0.1`

**Ruby version**: `ruby 2.3.1p112`

**Comment by rafaelfranca** [comment]
Configure don't take an argument. So `config` there is `nil`, this is why you got the NoMethodError

**Comment by rafaelfranca** [comment]
```irb
>> def foo
>>   yield
>>   end
=> :foo
>> foo { |x| p x }
nil
=> nil
```
