### ISSUE TITLE
`count` and `count(:all)` generate different queries, leading to SQL errors

### ISSUE THREAD

**Issue by wkirby** [rails/rails#27765]
### Steps to reproduce

1. Generate an `ActiveRecord` model, I'm using `Company` here, but any `AR` model will do.
2. `Company.select('companies.*').count` throws a SQL Syntax Error
3. `Company.select('companies.*').count(:all)` behaves as expected

This is a minimal repro, which is _very_ contrived. In the real world, a similar `select` statement might come at the end of a long `join` sequence --- such as the one found in the `Rolify` gem.

### Expected behavior
No SQL error should be thrown.

### Actual behavior
An SQL syntax error occurs.

### System configuration
**Rails version**: 5.0.1
**Ruby version**: 2.3.0

**Comment by sevenseacat** [comment]
What are the queries generated and what is the error?

**Comment by vipulnsward** [comment]
This does not fail for me- https://gist.github.com/vipulnsward/a52147b19ac7bf2ed2139f37121fd59d

Can you confirm if this is specific to some database.

**Comment by wkirby** [comment]
`Company.select('companies.*).count` generates:

```sql
SELECT COUNT(companies.*) FROM "companies"
```

While `Company.select('companies.*').count(:all)` generates:

```sql
SELECT COUNT(*) FROM "companies"
```

I did notice when digging into this that the documentation explicitly says:

> If count is used with Relation#select, it will count the selected columns.
>
> Note: not all valid Relation#select expressions are valid count expressions. The specifics differ between databases. In invalid cases, an error from the database is thrown.
