### ISSUE TITLE
What is a good gem for work asynchronous  in rails 4.2.5 ?

### ISSUE THREAD

**Issue by marcosvicente** [rails/rails#27781]
### Steps to reproduce

(Guidelines for creating a bug report are [available
here](http://guides.rubyonrails.org/contributing_to_ruby_on_rails.html#creating-a-bug-report))

### Expected behavior
Tell us what should happen

### Actual behavior
Tell us what happens instead

### System configuration
**Rails version**: 4.2.5.1

**Ruby version**: 2.1.2

**Comment by matthewd** [comment]
Please use the mailing list or StackOverflow for questions/help, where a wider community will be able to help you. We reserve the issues tracker for issues only.
