### ISSUE TITLE
Less formatting in schema.rb to prevent unnecessary changes

### ISSUE THREAD

**Issue by Zyphrax** [rails/rails#27806]
### Steps to reproduce

The schema.rb file uses spaces to align the column names / types / options.
Although this makes the file a bit easier to read, it is not that practical for tracking changes in git.

Let's say I have a column _email_ with a limit of _64_ and I change that to _128_, the schema generator will change all the lines of that table definition. If I add a column with a name that is a bit longer than the name of the other column, same thing happens.

It would be great if there was a way to turn the alignment off.

Another question: why are all the strings double quotes?
Column names probably won't need string interpolation or special symbols?

### System configuration
**Rails version**: 4.2.7.1
**Ruby version**: 2.3.3p222

**Comment by al2o3cr** [comment]
Double-quotes without interpolation haven't had a performance difference from single-quotes for a while now, I don't think there's any reason to fiddle with them.

For the rest, you may want to look into a gem like [fix-db-schema-conflicts](https://github.com/jakeonrails/fix-db-schema-conflicts) which does some of what you've described.

**Comment by morgoth** [comment]
@Zyphrax I think it was already discussed in https://github.com/rails/rails/pull/16398

**Comment by kamipo** [comment]
Already implemented in #25675.
