### ISSUE TITLE
ActiveModel::Type::Date.new.serialize returns nil unless formatted like 2016-01-25

### ISSUE THREAD

**Issue by niedfelj** [rails/rails#27800]
### Steps to reproduce

ActiveModel::Type::Date.new.serialize('10/18/2015') returns nil

Similar implementations like ActiveModel::Type::DateTime.new.serialize('10/18/2015') will return the original string. 

This seems related to changes made in 5.0.1 to the Date serialize function.

10b81fb51acc600926613e

### Expected behavior

Seems like it should return the original string at least (not sure why new_date is returning nil either, as that format '10/18/2015' should be parseable). We had a situation where assigning '10/18/2015' would just silently do nothing to update the database.

### Actual behavior

It returns nil and the database doesn't receive an update or any message stating an error.

### System configuration
**Rails version**: 5.0.1

**Ruby version**: 2.3.3

**Comment by Sen-Zhang** [comment]
From the following code, it looks the only supported format is 'dd/mm/yyyy' if it date format is not ISO date. So I believe `ActiveModel::Type::Date.new.serialize('18/10/2015')` should work.
```ruby
def fallback_string_to_date(string)
  new_date(*::Date._parse(string, false).values_at(:year, :mon, :mday))
end
```

**Comment by Sen-Zhang** [comment]
The supported format is 'dd/mm/yyyy', so this should work.
```ruby
ActiveModel::Type::Date.new.serialize('18/10/2015')
```

**Comment by niedfelj** [comment]
@Sen-Zhang It wasn't really a question of WHAT format the date should be, but rather that it is returning nil instead of what was entered (serialized or not) and failing silently.

**Comment by Sen-Zhang** [comment]
@niedfelj I understand your point. After checking the code and tests, I realize returning nil for strings that cannot be parsed as a date is the expected behavior. So I am not sure this is a bug or not. Hopefully some rails core team members can help answer this question.

**Comment by lugray** [comment]
@niedfelj As @Sen-Zhang mentions, this is expected behaviour. Your point that DateTime was behaving differently was a good one, and the fix for that has been merged.
