### ISSUE TITLE
Rails working fine last night; woke up this morning, now giving errors

### ISSUE THREAD

**Issue by PeterDavidCarter** [rails/rails#27818]
### Expected behavior
System should have the same rails gems it had yesterday today, given I have changed nothing at all on the server.

### Actual behavior

```
peter@ubuntu:~/alisaesage$ rails server -h
/usr/local/lib/site_ruby/2.3.0/rubygems.rb:270:in `find_spec_for_exe': can't find gem railties (>= 0.a) (Gem::GemNotFoundException)
	from /usr/local/lib/site_ruby/2.3.0/rubygems.rb:298:in `activate_bin_path'
	from /usr/local/bin/rails:22:in `<main>'
peter@ubuntu:~/alisaesage$ bundle install
/usr/local/lib/site_ruby/2.3.0/rubygems.rb:270:in `find_spec_for_exe': can't find gem bundler (>= 0.a) (Gem::GemNotFoundException)
	from /usr/local/lib/site_ruby/2.3.0/rubygems.rb:298:in `activate_bin_path'
	from /usr/local/bin/bundle:22:in `<main>'
```

### System configuration
**Rails version**:

5.0.1

**Ruby version**:

ruby 2.3.1p112 (2016-04-26 revision 54768) [x86_64-linux]

**Comment by eileencodes** [comment]
Hey @PeterDavidCarter - I don't think this is a Rails issue. Your system can't find bundler or the other gems - so maybe an issue with your bundler copy? I found this issue that seems similar to yours https://github.com/guard/guard-bundler/issues/32.

Check your `.bundle/config` for anything odd that may be interfering.
