### ISSUE TITLE
Rails 5 generate controller generates the wrong type of test

### ISSUE THREAD

**Issue by ukblewis** [rails/rails#27812]
### Steps to reproduce

Type `rails g controller MyNameHere` to generate a controller.

### Expected behavior

Rails would generate a controller in the controllers folder and would generate a unit test for the controller in the controllers folder within the test folder.

### Actual behavior

Rails actually generates a controller file successfully, but generates a test in the controller folder within the test folder which is actually an integration test. You can see this by noting that it inherits from `ActionDispatch::IntegrationTest` and not `ActionController::TestCase`.

### System configuration
**Rails version**: 5.0.0.1

**Ruby version**: 2.3.1

**Comment by utilum** [comment]
This is expected behavior, [documented](http://guides.rubyonrails.org/testing.html#functional-tests-for-your-controllers) even.

**Comment by ukblewis** [comment]
Hi @utilum ,

I am sorry to bug you, but can you explain why this is the behavior?

Is it not rather confusing that Rails is now mixing unit and integration tests?

Why would you want to build integration tests first and not unit tests?


Warmest regards,

Ben

**Comment by utilum** [comment]
@ukblewis I think I understand your confusion. The general idea is that the controller tests are indeed integration tests, or a kind of functional tests. But having this discussion here disrupts the focus of people volunteering to fix bugs in Rails. Read the documentation, ask on stackoverflow, etc...
