### ISSUE TITLE
Rails server not loading rack handler

### ISSUE THREAD

**Issue by PeterDavidCarter** [rails/rails#27827]
### Steps to reproduce

???

### Expected behavior
Server process should start.

### Actual behavior
Running: 

    rails server -p 80 - b [ipaddress]

Results in:

```
/var/lib/gems/2.3.0/gems/rack-2.0.1/lib/rack/handler.rb:74:in `require': cannot load such file -- rack/handler/- (LoadError)
	from /var/lib/gems/2.3.0/gems/rack-2.0.1/lib/rack/handler.rb:74:in `try_require'
	from /var/lib/gems/2.3.0/gems/rack-2.0.1/lib/rack/handler.rb:16:in `get'
	from /var/lib/gems/2.3.0/gems/rack-2.0.1/lib/rack/server.rb:300:in `server'
	from /var/lib/gems/2.3.0/gems/railties-5.0.1/lib/rails/commands/server.rb:112:in `print_boot_information'
	from /var/lib/gems/2.3.0/gems/railties-5.0.1/lib/rails/commands/server.rb:73:in `start'
	from /var/lib/gems/2.3.0/gems/railties-5.0.1/lib/rails/commands/commands_tasks.rb:90:in `block in server'
	from /var/lib/gems/2.3.0/gems/railties-5.0.1/lib/rails/commands/commands_tasks.rb:85:in `tap'
	from /var/lib/gems/2.3.0/gems/railties-5.0.1/lib/rails/commands/commands_tasks.rb:85:in `server'
	from /var/lib/gems/2.3.0/gems/railties-5.0.1/lib/rails/commands/commands_tasks.rb:49:in `run_command!'
	from /var/lib/gems/2.3.0/gems/railties-5.0.1/lib/rails/commands.rb:18:in `<top (required)>'
	from bin/rails:4:in `require'
	from bin/rails:4:in `<main>'
```
 
### System configuration
**Rails version**:

5.0.1

**Ruby version**:

ruby 2.3.1p112 (2016-04-26) [x86_64-linux-gnu]

**Additional**: uninstalling and reinstalling ruby and rails, specifically including railties and bundler, does not appear to help.

**Comment by y-yagi** [comment]
There seems to be extra space between `-` and `b`. 
What if you remove the space between `-` and `b` as shown below?

```
rails server -p 80 -b [ipaddress] 
```

**Comment by PeterDavidCarter** [comment]
Strange. I pressed the up arrow on Linux, which should have reproduced the previously working command exactly, but instead resulted in the version you see, with the space. Obviously a Linux problem not a Rails one tho...
