### ISSUE TITLE
I18n - 'true', 'false' are not accepted as valid key names.

### ISSUE THREAD

**Issue by richseviora** [rails/rails#27829]
There is an issue where YAML keys `true` and `false` cannot be located by I18n. I don't see any documentation capturing this.

The following conditions create the issue:

1. [YAML (see language independent scalars section)](http://www.yaml.org/refcard.html) treats `true` as `TrueClass`, not `"true"`, and instantiates the objects accordingly. (It also treats `yes`, `no` as true/false as well)
2. `I18n::Backend::Simple#store_translations` calls `Hash#deep_symbolize_keys`.
3. `Hash#deep_symbolize_keys`  keeps the key unless the key respond to `to_sym`. 
4. `true` and `false` do not respond to `to_sym`.
5. `I18n::Backend::Simple#lookup` does not have logic redirecting true/yes keys to `true`.

As a result, the key is for that tree is `true` instead of the expected `'true'`, and I18n is not able to find the translation.

I'm thinking there's a number of possible solutions:

### Update I18n Backends

1. Update `I18n::Backend::Simple#lookup` and `KeyValue#lookup` logic to  match the YAML keys for true and false to their corresponding boolean value, and proceed with that key.

This has the benefit of being more or less transparent to the user and does not extend a core class in ways that may break existing code. Docs should be updated to capture that the boolean keys are all equivalent to each other for the purpose of I18n.

### Extend Hash

2. Create `TrueClass#to_sym` and `FalseClass#to_sym` so that they return `:true` and `:false`. respectively.

Even easier to implement, but may break existing code because we're making a core class symbolizable(sp?) where it was not before. Docs should be updated to capture that the boolean keys are all equivalent to each other for the purpose of I18n.

### Documentation Only

3. Update the guide and API documentation with a warning that these keys are reserved.

Doesn't really solve the problem, but at least it's documented.

Thoughts?

### Steps to reproduce

1. Create translation entry in {lang}.yml as follows:

```
key_name:
  true: 'True Result'
  false: 'False Result'

```
2. Call `I18n.t 'key_name.true'`.

(Guidelines for creating a bug report are [available
here](http://guides.rubyonrails.org/contributing_to_ruby_on_rails.html#creating-a-bug-report))

### Expected behavior
Should return `True Result`.

### Actual behavior
Returns `translation missing: en.key_name.true`.

### System configuration
**Rails version**: 5.0.1

**Ruby version**: 2.3.3

**Comment by richseviora** [comment]
Just for clarity, I'm happy to write the PR myself, but I'd like to get some input before I go charging off :)

**Comment by pixeltrix** [comment]
Thanks for the report @richseviora

This is actually a know limitation in the i18n gem (svenfuchs/i18n#94) - you need to quote your key or use a symbol key directly, e.g:

``` yaml
en:
  foo:
    :true: "True Value"
    "false": "False Value"
```

``` irb
>> I18n.t :"foo.true"
=> "True Value"
>> I18n.t :"foo.false"
=> "False Value"
```

Since `true` and `false` do support `to_s` then there's an argument that it should support `to_sym` as well but I'd rather that argument was made upstream in Ruby than us monkey-patching it.

**Comment by richseviora** [comment]
@pixeltrix any objection to a documentation update? I think it'd be nice to have some reference to YAML reserved words in either the I18n guide, or perhaps the default `config\locales\en.yml` file so that users unfamiliar with the YAML syntax specification aren't wasting time going down an unnecessary path.

**Comment by pixeltrix** [comment]
@richseviora please do 👍
