### ISSUE TITLE
Setting "where: true" for a partial index in a migration should probably throw an error

### ISSUE THREAD

**Issue by djcp** [rails/rails#27828]
### Steps to reproduce
Given a migration that looks like:

```
# pingable is a boolean
add_index :users, :pingable, where: true
```

This silently succeeds and generates a normal index, but doesn't generate a partial index.  The correct syntax is:

```
add_index :users, :pingable, where: "pingable is true"
```

### Expected behavior
I would expect this to throw an error, or at least a warning.

### Actual behavior
A normal, non-partial index is created.

### System configuration
activerecord 4.2.7.1

**Ruby version**:
2.3.3

**Comment by pixeltrix** [comment]
@djcp seems like there's a whole class of conditions that would evaluate to true that would also be affected by this, e.g. `where "1 = 1"` and `where: "foo = foo"`. In a previous version of Active Record we tried to detect lolqueries which would always return empty results and it didn't work out so we removed it in 9c023cc - seems like this would be going down a similar path so I don't think it's a good idea, sorry.
