### ISSUE TITLE
Uniq based on a certain column

### ISSUE THREAD

**Issue by mostafa-zahran** [rails/rails#27839]
When a table contains a json column then uniq function raise an error 
'could not identify an equality operator for type json'
and the only possible solution for that is 
select('DISTINCT ON (users.id) users.*')
I think it will be better if uniq method can accept a named parameter like 
uniq(on: :id)

**Comment by kaspth** [comment]
Please use the Ruby on Rails talk mailing list or StackOverflow for questions/help, where a wider community will be able to help you. We reserve the issues tracker for issues only. Thanks!
