### ISSUE TITLE
Rails g scaffold for module resource generates wrong directory in jbuilder templates.

### ISSUE THREAD

**Issue by jung-hunsoo** [rails/rails#27845]
### Steps to reproduce
`$ rails g scaffold guest/category title description`

### Expected behavior
While many new files being generated, three jbuilder templates are expected to be created like this:

- _guest_category.json.jbuilder
`json.extract! guest_category, :id, :title, :description, :created_at, :updated_at`
`json.url guest_category_url(guest_category, format: :json)`

- index.json.jbuilder
`json.array! @guest_categories, partial: 'guest/categories/guest_category', as: :guest_category`

- show.json.jbuilder
`json.partial! "guest/categories/guest_category", guest_category: @guest_category`

### Actual behavior
The two jbuilder templates for index and show have inexistent directory which the module namespace isn't applied.

- _guest_category.json.jbuilder
`json.extract! guest_category, :id, :title, :description, :created_at, :updated_at`
`json.url guest_category_url(guest_category, format: :json)`

- index.json.jbuilder
`json.array! @guest_categories, partial: 'guest_categories/guest_category', as: :guest_category`

- show.json.jbuilder
`json.partial! "guest_categories/guest_category", guest_category: @guest_category`

### System configuration
**Rails version**: 5.0.1

**Ruby version**: 2.3.3

**Comment by rafaelfranca** [comment]
This issue was moved to rails/jbuilder#379
