### ISSUE TITLE
ActiceJob::TestHelper behaves unintended when using a filter

### ISSUE THREAD

**Issue by apauly** [rails/rails#27848]
### Steps to reproduce

    class FooJob < ActiveJob::Base
      def perform
        puts "FooJob executed"
      end
    end

    class BarJob < ActiveJob::Base
      def perform
        puts "BarJob executed"
      end
    end

    ActiveJob::Base.queue_adapter = :test
    include ActiveJob::TestHelper

    perform_enqueued_jobs only: FooJob do
      FooJob.perform_later
      BarJob.perform_later
    end

    puts "Number of enqueued jobs: #{enqueued_jobs.count}"
    puts "Enqueued job: #{enqueued_jobs.first.try(:[], :job).inspect}"

### Expected behavior
Personally, I'd expected the `FooJob` to be executed and the `BarJob` to be not executed but queued instead. I'd expect something like this:

    FooJob executed
    Number of enqueued jobs: 1
    Enqueued job: BarJob

### Actual behavior
Instead, when a filter is present, every job is skipped completely if it is not included in the filter:

    FooJob executed
    Number of enqueued jobs: 0
    Enqueued job: nil

### System configuration
**Rails version**:
rails-5.0.0.1

**Ruby version**:
=> ruby-2.2.3 [ x86_64 ]

### Discussion

Assuming that this is not the intended behavior, I could think of two possible solutions that would not break existing implementations:

a) The `perform_enqueued_jobs` method could take an additional options like this:

    perform_enqueued_jobs only: FooJob, queue_filtered: true do
      # FooJob will be executed, all other Jobs will be added to `enqueued_jobs`
    end

b) Store filtered jobs instead of ignoring them so that we can verify that they have been enqueued:

    perform_enqueued_jobs only: FooJob do
      # FooJob will be executed, all other Jobs will be added to a seperate array, e.g. `skipped_jobs`
    end

**Comment by rafaelfranca** [comment]
Could you try to change the behavior to keep the skipped job in the enqueued_jobs array?

**Comment by apauly** [comment]
Sure, I'll take a look at it

**Comment by apauly** [comment]
I've created a pull request: #27850

**Comment by dhh** [comment]
Just stumbled over this as it broke BC3 tests. It was designed with the original behavior in mind: If you're only interested in performing certain jobs, those are the only that should queue as well. I could see having an option where you queue jobs that you don't want to perform right now, but that should be an option. Going to revert the PR for now. If you want to take a stab at the option approach, please do reopen!
