### ISSUE TITLE
`db:create` Rake task leaks db credentials into logs

### ISSUE THREAD

**Issue by anicholson** [rails/rails#27852]
### Steps to reproduce

1. In an environment when the database is not available, run `rake db:create`

### Expected behaviour

If `Rails.env.production?`, don't blindly `inspect` the configuration into the logs. Just because the db wasn't able to be created doesn't mean the credentials aren't correct. 

### Actual behaviour

The db credentials, including password, are leaked into the logs/`$stderr`.

### System configuration
**Rails version**: since `a1c88273f4321e203ccf389ccff8a8e043c4f8f9` 0_o

**Ruby version**: <all>

**Comment by rafaelfranca** [comment]
Make sense. Could you open a PR?

**Comment by ashishprajapati** [comment]
Hello @anicholson,
I am looking at that issue and will raise the PR if you are not looking into that.

**Comment by marrsale** [comment]
Hi guys (@anicholson @ashishprajapati @rafaelfranca),

I hope this isn't rude, but I cut a branch to give this a look and make a tentative fix yesterday for fun.  I just made up the PR [here](https://github.com/rails/rails/pull/27878) and I'm commenting to avoid any duplication of effort if unnecessary.

Thanks.

**Comment by marrsale** [comment]
Hi guys (@anicholson @ashishprajapati),

I hope this isn't rude, but I cut a branch yesterday and was playing with this issue for fun and I am submitting a final PR for it.  I'm just commenting here in case you already have a better solution worked up, or alternatively so you don't waste time if you think that mine is adequate.  I'll take it down if you have something better.

Thanks.
