### ISSUE TITLE
Rails 5.0.1.: Nested Error field wrapping not applied (in case of: accepts_nested_attributes_for)

### ISSUE THREAD

**Issue by john-999** [rails/rails#27871]
If:
- Model1 ```:has_many``` Model2
- Model1 ```accepts_nested_attributes_for``` Model2

And then:
- Model2 has a validation error

Then:
Error field wrapping with the div element ```<div class="field_with_errors"></div>``` is not applied on the (Model2) field containing the error.

This could be related to: https://github.com/rails/rails/issues/20690

**Comment by dmitry** [comment]
@john-999 please include example how to reproduce it.

**Comment by zztczcx** [comment]
I can reproduce this.

###models

```
class Member < ApplicationRecord
  has_one :avatar
  accepts_nested_attributes_for :avatar


  validates :name, presence: true
end
```


```
class Avatar < ApplicationRecord
  belongs_to :member

  validates :icon, presence: true
end
```


### view

```
<%= form_for(setup_member(member)) do |f| %>
    <% if member.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(member.errors.count, "error") %> prohibited this member from being saved:</h2>

        <ul>
        <% member.errors.full_messages.each do |message| %>
          <li><%= message %></li>
>>      <% end %>
        </ul>
      </div>
    <% end %>

    <div class="field">
      <%= f.label :name %>
      <%= f.text_field :name %>
    </div>

    <div class="field">
      <%= f.label :age %>
      <%= f.number_field :age %>
    </div>

```
    <%= f.fields_for :avatar do |builder| %>
      <div class="field">
        <%= builder.label :icon %>
        <%= builder.text_field :icon %>
      </div>
    <% end %>

    <div class="actions">
      <%= f.submit %>
    </div>
  <% end %>


### helper_method

```
module MembersHelper
  def setup_member(member)
    member.avatar ||= Avatar.new
    member
  end
end
```





so when you create a member but the icon of avatar is blank,  it will not give you a field_with_errors wrap with the icon field.

**Comment by dmitry** [comment]
@zztczcx what shows `member.errors` in case of invalid nested object?

**Comment by zztczcx** [comment]
@dmitry 
If you donot input name of member and the icon, the errors will be just only name cannot be blank. 

And if you look into the member.avatar. It is nil.

**Comment by zztczcx** [comment]
I think we should make a decision if show the nested errors in the up most errors. 

I am not sure if this is a bug or need to add as a feature
