### ISSUE TITLE
=== operator on ActiveRecord::Base doesn't return expected values

### ISSUE THREAD

**Issue by arathiramani** [rails/rails#27876]
### Steps to reproduce
In a Rails 3 console:
[28] pry(main)> ActiveRecord::Base === ActiveRecord::Base
=> false

### Expected behavior
This should be the same constant, but === is returning false.

### Actual behavior
I'd expected === to return true in this case, even though this is the 'case subsumption' operator, it seems like this satisfies case subsumption conditions

### System configuration
**Rails version**: 3.2.17

**Ruby version**: 2.1.1

Apologies if this has been fixed in a later version of Rails.

**Comment by matthewd** [comment]
Thanks for the report, but that's expected behaviour. See also: `String === String # => false`.

(Also, FYI, Rails 3.2 is no longer supported.)
