### ISSUE TITLE
Docs: Potentially incorrect docs for `Module#delegate` re: NoMethodError

### ISSUE THREAD

**Issue by jaredbeck** [rails/rails#27873]
The docs say that a `NoMethodError` will be raised, but I think the error is actually `Module::DelegationError`.

```
class C
  delegate :a, to: :b
  def b
    nil
  end
end
C.new.a
# Module::DelegationError: C#a delegated to b.a, but b is nil: #<C:0x007feddf07f768>
```

But, I wasn't confident enough to make a PR :)

The docs mention `NoMethodError` in a few different places. Here are some examples:

Example 1:

> :allow_nil - if set to true, prevents a NoMethodError from being raised

Example 2:

> Foo.new.goodbye # => NoMethodError: undefined method `goodbye' for #<Foo:0x1af30c>

**Comment by eileencodes** [comment]
Do you want to send a PR? You said you weren't confident enough but if it's what you're seeing in the console then the docs should be corrected.

**Comment by jaredbeck** [comment]
> Do you want to send a PR? You said you weren't confident enough but if it's what you're seeing in the console then the docs should be corrected.

Sure. Closing via https://github.com/rails/rails/pull/27898
