### ISSUE TITLE
Incorrect Join Order for Multiple ActiveRecord Merges

### ISSUE THREAD

**Issue by niedfelj** [rails/rails#27887]
### Steps to reproduce

When attempting to merge multiple relations together, the last one below incorrectly generates joins that are out of order and throw an error in Postgres. Not sure if this is related to #25806. There seem to be a few open issues that have not been resolved that are similar to this one.

```
location_filter = Location.where(@location_wheres.join(' AND '))
user_filter = User.opt_in.where("birthday >= ? and birthday <= ? #{@birthday_null}", Time.now() - @end_age.years, Time.now() - @start_age.years).where(@gender).joins(:location).merge(location_filter)
@all_list_items = account_group.list_items.joins(:contributor_user).merge(user_filter)
@all_lists = account_group.lists.merge(@all_list_items)
```

All of the queries except for the last one are successful:

```
!! #<ActiveRecord::StatementInvalid: PG::UndefinedTable: ERROR:  missing FROM-clause entry for table "users"
LINE 1: ...LEFT OUTER JOIN "locations" ON "locations"."id" = "users"."l...
                                                             ^
: SELECT "lists".* FROM "lists" LEFT OUTER JOIN "locations" ON "locations"."id" = "users"."location_id" LEFT OUTER JOIN "users" ON "users"."id" = "list_items"."contributor_user_id" INNER JOIN "list_items" ON "lists"."id" = "list_items"."list_id" WHERE (list_status_code!='Deleted') AND "list_items"."domain" = $1 AND "list_items"."domain" = $2 AND "users"."opt_out" = $3 AND (birthday >= '1817-02-02 18:03:12.184201' and birthday <= '2017-02-02 18:03:12.184290'  or birthday is null) AND (1=1) AND (city='Brooklyn')>

```

### Expected behavior

It should do the joins in the correct order.

### Actual behavior

It joins in the wrong order and throws an error.

### System configuration
**Rails version**: 5.0.1

**Ruby version**: 2.3.3

**Comment by eileencodes** [comment]
Can you recreate this error using our [bug report template](https://github.com/rails/rails/blob/master/guides/bug_report_templates/active_record_migrations_master.rb)? That will make it easier for us to track down the bug you're seeing.

**Comment by aleksandrs-ledovskis** [comment]
Tracked https://github.com/rails/rails/issues/24281
