### ISSUE TITLE
cant install rails 4.2.7

### ISSUE THREAD

**Issue by Fattouh92** [rails/rails#27882]
### Steps to reproduce

(Guidelines for creating a bug report are [available
here](http://guides.rubyonrails.org/contributing_to_ruby_on_rails.html#creating-a-bug-report))

### Expected behavior
installing rails 4.2.7 on ubuntu 16.04 running on windows 2012 r2 hyper v virtual machine

### Actual behavior
Tell us what happens instead
gem install rails -v 4.2.7
ERROR:  Error installing rails:
	invalid gem: package is corrupt, exception while verifying: undefined method `size' for nil:NilClass (NoMethodError) in /home/navy/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/cache/activesupport-4.2.7.gem

### System configuration
**Rails version**: 4.2.7

**Ruby version**:2.3.1

**Comment by j-dexx** [comment]
I've just installed ruby 2.3.1 and rails 4.2.7 with rbenv with no issues.  I don't think this is a rails issue.

Have you tried removing the cache in rbenv for activesupport-4.2.7.gem as detailed in this [SO answer](http://stackoverflow.com/questions/32353715/invalid-gem-package-is-corrupt-while-installing-rails-in-osx-yosemite-10-10)

**Comment by arthurnn** [comment]
as @j-dexx  said, I don't think this is a rails issue.
