### ISSUE TITLE
General question: Migrating from 4.x to 5

### ISSUE THREAD

**Issue by x-itec** [rails/rails#27883]
a) is R5 stable enough to upgrade from 4.x
b) I have a very big project, worked on it for about 2 years or so and I think there are many changes in R5. Are there any compatibility/wrapper gems or so to make a migration easier?
c) how long is R4.x supported, is there any plan?

**Comment by utilum** [comment]
@x-itec, this space is dedicated to help volunteers manage work on the code (right now: 581 issues, + 663 pull requests). Questions, discussion, support... are best sought on the mailing list, on IRC, or on such sites as stackoverflow...
