### ISSUE TITLE
Autoloading ignores namespaces if class with name is already loaded

### ISSUE THREAD

**Issue by Rsullivan00** [rails/rails#27889]
### Steps to reproduce

I set up a sample project that has a generated rails app and a single mounted (namespaced) engine to demonstrate the issue.

I can reproduce the issue on both Rails 4.2.5/Ruby 2.2.3 and Rails 5.0.1/Ruby 2.3.0.

1. `git clone https://github.com/Rsullivan00/rails-broken-autoloading`
2. `bundle install`
3. `rails s`
4. Go to http://localhost:3000/test

### Expected behavior
You should see 'engine user'.

The controller you hit is in the `Myengine` namespace, so we should expect `User` to reference `Myengine::User`.

### Actual behavior
You see 'main app user'.

### System configuration
**Rails version**:
5.0.1
**Ruby version**:
2.3.0

### Other notes

I believe this may be related to https://github.com/rails/rails/issues/27119

**Comment by Rsullivan00** [comment]
Note that as soon as Ruby fails to load a constant, [`const_missing`](https://github.com/rails/rails/blob/f243e7f0d0b2cef350127fd518532fedb65f0bd0/activesupport/lib/active_support/dependencies.rb#L200) triggers a search of the current module for constants, which will cause future references to refer to the appropriately namespaced versions.

**Comment by matthewd** [comment]
This is a known limitation: http://guides.rubyonrails.org/autoloading_and_reloading_constants.html#when-constants-aren-t-missed

**Comment by Rsullivan00** [comment]
@matthewd Thanks for the info.

I understand why this is happening, but it seems like a namespace should not be able to implicitly reference constants outside of the namespace. I could see the namespace referencing the outer user using `::User`, but it seems like a bug if the `User` reference is ambiguous.
