### ISSUE TITLE
fields_for with/without record name

### ISSUE THREAD

**Issue by clthck** [rails/rails#27892]
### Steps to reproduce

```ruby
ActiveRecord::Schema.define do
  create_table :roles, force: true do |t|
  end

  create_table :users, force: true do |t|
    t.integer :role_id
    t.string :email
  end
end

class Role < ActiveRecord::Base
  has_one :user
  accepts_nested_attributes_for :user
end

class User < ActiveRecord::Base
  belongs_to :role
  validates :email, presence: true
end

class TestController < ActionController::Base
  def new
    @role = Role.new
    @role.build_user
  end
end
```

`new.erb`
```erb
<%= form_for @role, url: '' do |f| %>
  <%= f.fields_for @role.user do |uf| %>
    <%= uf.email_field :email %>
  <% end %>
<% end %>
```

### Expected behavior
email field tag should have name `role[user_attributes][email]`

### Actual behavior
email field tag name is `role[user][email]`

### System configuration
**Rails version**: 5.0.1

**Ruby version**: 2.4.0p0

**NOTE**:
If I use `f.fields_for :user, @role.user`, then tag name renders properly. But in case record name is omitted, Rails infers appropriate record name from given record object, according to Rails guide, doesn't it?

**Comment by st0012** [comment]
Although the case is not exactly identical, but in [this example](http://guides.rubyonrails.org/form_helpers.html#using-form-helpers) it should render `PARENT_MODEL_NAME[CHILD_MODEL_NAME][CHILD_ATTRIBUTE]` instead of `PARENT_MODEL_NAME[CHILD_MODEL_NAME_attributes][CHILD_ATTRIBUTE]`

**Comment by clthck** [comment]
But `PARENT_MODEL_NAME[CHILD_MODEL_NAME][CHILD_ATTRIBUTE]` is not accepted by `accepts_nested_attributes_for` class method and that's why I opened this ticket.

**Comment by st0012** [comment]
This is because `f.fields_for :user, @role.user` is the correct usage for your situation not the original one. See [here](https://github.com/rails/rails/blob/master/actionview/lib/action_view/helpers/form_helper.rb#L893).

**Comment by dmitry** [comment]
Right, it works only with string and symbol: https://github.com/rails/rails/blob/master/actionview/lib/action_view/helpers/form_helper.rb#L1919

**Comment by rafaelfranca** [comment]
While it can be changed it is not an issues so I'm closing this. But feel free to open a PR to change the behavior.
