### ISSUE TITLE
When using adapter inference from URL, adapter in config should override

### ISSUE THREAD

**Issue by rickmark** [rails/rails#27899]
### Steps to reproduce

In database.yml with `activerecord-postgis-adapter` in the bundle

```
production:
  url: postgres://myuser:mypass@localhost/somedatabase
  adapter: postgis
```

### Expected behavior
ActiveRecord should load the PostGIS adapter instead of the Postgres adapter

### Actual behavior
The Postgres adapter is used (inferred from the URL scheme).  This leads to difficulties where the URL is passed in by environment variable (Ala Heroku).

### System configuration
**Rails version**: 5.0.1

**Ruby version**: 2.3.3

**Comment by arthurnn** [comment]
i have a PR that change behavior on the database.yml config a bit. I will make sure i take this into consideration there too. It make sense to me.
