### ISSUE TITLE
Rails 4.2 and Rubinius 3.69 seg faults

### ISSUE THREAD

**Issue by goodcode** [rails/rails#27907]
Hi there,

I am trying to setup a Rails 4.2 app with puma, running on rubinius 3.69. I am having the following issues:

http://stackoverflow.com/questions/42043769/rails-4-2-4-with-rubinius-and-puma-crashes-or-hangs-forever

Can someone please share a successful rails 4.2 and puma production setup, using rubinius? What versions did you use and what issues did you run into. Honestly this had to be an easy migration from a staging setup that uses MRI, to a production setup, using something that should give us higher performance. Now I'm feeling like the only person in the world that ever tried it...

**Comment by al2o3cr** [comment]
Decidedly not a Rubinius expert, but several of the call stacks linked above seem to happen in the GC (based on names like `collect_full` etc). 

For the "server starts but hangs", you might want to try something like the GDB technique described in [this article](http://rrsoft.co/2015/05/11/using-gdb-to-inspect-a-running-ruby-process-and-execute-arbitrary-commands/). NOTE NOTE NOTE: this will NOT WORK as-written as it invokes MRI internals by name, but you should be able to track down equivalent pieces in Rubinius.

Related issue (so future readers can keep track): https://github.com/rubinius/rubinius/issues/3733

**Comment by matthewd** [comment]
We don't provide support for Rubinius; if it works on MRI, it's not our bug.
