### ISSUE TITLE
Methods defined in array/conversions not working when called by ActiveRecord::Relation

### ISSUE THREAD

**Issue by kenta-s** [rails/rails#27901]
## Summary

It looks like ActiveRecord::Relation lost some methods such as `to_sentence`, `to_formatted_s` and `to_xml`. All of the methods are in activesupport/lib/active_support/core_ext/array/conversions.rb.

Let's say there is a `Blog` model which has three records on DB, and try to call `Blog.all.to_formatted_s(:db)`.

## Expected behavior
`Blog.all.to_formatted_s(:db)`  returns `"1,2,3"`

## Actual behavior
`Blog.all.to_formatted_s(:db)` raises a `NoMethodError`

I found that those methods work fine on 4-2-stable.

on 4-2-stable:
```
Blog.all.to_formatted_s(:db) # => "1,2,3"
Blog Load (10.7ms)  SELECT "blogs".* FROM "blogs"
=> "1,2,3"
```

on master(and on 5-0-stable as well):
```
Blog.all.to_formatted_s(:db) 
NoMethodError:   Blog Load (11.8ms)  SELECT "blogs".* FROM "blogs"
undefined method `to_formatted_s' for #<ActiveRecord::Relation []>
```

**Comment by y-yagi** [comment]
This is the effect of 9d79334a1dee67e31222c790e231772deafcaeb8
In 9d79334a1dee67e31222c790e231772deafcaeb8, `ActiveRecord::Relation` only delegates specific methods to Array. Therefore, I think this is expected behavior.
If you want to use Array's method, you need to convert it to Array yourself.

```ruby 
Blog.all.to_a.to_formatted_s(:db) 
```
But this is incompatible. Is it necessary to deprecate first?

**Comment by kenta-s** [comment]
Thank you so much. Now I understand that those methods removed on purpose. 
Then, these lines should be removed as well?
https://github.com/rails/rails/blob/master/activesupport/lib/active_support/core_ext/array/conversions.rb#L88-L89

Or should we consider:

> But this is incompatible. Is it necessary to deprecate first?

**Comment by matthewd** [comment]
This was not intentional. We should follow the example from https://github.com/rails/rails/pull/23782 and add them to the delegation.

**Comment by kenta-s** [comment]
I opened up a PR. I realized that `to_xml` was already delegated and was working correctly sorry.
So I just added `to_sentence` and `to_formatted_s`
