### ISSUE TITLE
ActiveRecord::ConnectionAdapters::PostgreSQLColumn#limit behaviour between Rails 3 and Rails 4

### ISSUE THREAD

**Issue by gipcompany** [rails/rails#27906]
### Steps to reproduce

I found a difference in `ActiveRecord::ConnectionAdapters::PostgreSQLColumn#limit` between Rails 3 and 4 App.

Below are the console result of each, but each of them is a valid behaviour?

#### Rails 3 App

`ActiveRecord::ConnectionAdapters::PostgreSQLColumn#limit` can return 255.

```ruby
$ rails c
Loading development environment (Rails 3.2.22.5)
[1] pry(main)> User.columns[1]
=> #<ActiveRecord::ConnectionAdapters::PostgreSQLColumn:0x007f6324e5ddd0
 @coder=nil,
 @default=nil,
 @limit=255,
 @name="name",
 @null=true,
 @precision=nil,
 @primary=false,
 @scale=nil,
 @sql_type="character varying(255)",
 @type=:string>
[2] pry(main)> User.columns[1].limit
=> 255
```

#### Rails 4 App

`ActiveRecord::ConnectionAdapters::PostgreSQLColumn#limit` can return nil. So, it cannot show the size of string.

```ruby
$ rails c
Loading development environment (Rails 4.2.7.1)
[1] pry(main)> User.columns[1]
=> #<ActiveRecord::ConnectionAdapters::PostgreSQLColumn:0x007f96e55d3508
 @array=false,
 @cast_type=#<ActiveRecord::Type::String:0x007f96e55d4660 @limit=nil, @precision=nil, @scale=nil>,
 @default=nil,
 @default_function=nil,
 @name="name",
 @null=true,
 @sql_type="character varying">
[2] pry(main)> User.columns[1].limit
=> nil
```

### Expected behavior

In case of Rails 4 App, `ActiveRecord::ConnectionAdapters::PostgreSQLColumn#limit` should return 255 in that case?

### Actual behavior

In case of Rails 4 App, `ActiveRecord::ConnectionAdapters::PostgreSQLColumn#limit` returns nil.

#### Rails 3 App

**Rails version**:

```
$ rails -v
Rails 3.2.22.5
```

**Ruby version**:

```
$ ruby -v
ruby 2.1.9p490 (2016-03-30 revision 54437) [x86_64-linux]
```

#### Rails 4 App

**Rails version**:

```
$ rails -v
Rails 4.2.7.1
```

**Ruby version**:

```
$ ruby -v
ruby 2.3.1p112 (2016-04-26 revision 54768) [x86_64-linux]
```

**Comment by al2o3cr** [comment]
I can't find the specific PR that introduced this behavior, but I believe it's intentional - for instance, see discussion around #20815.

**Comment by rafaelfranca** [comment]
The sql type in the Rails 4 example is different from the Rails 3 example. It is `character varying` not `character varying(255)`. Are you using the exactly same database schema to compare the behavior?

**Comment by gipcompany** [comment]
@al2o3cr 
@rafaelfranca 

> The sql type in the Rails 4 example is different from the Rails 3 example.

Yes, it's because they are different apps. However the model is scaffolded by the following command `$ rails g scaffold user name`. So, I believe everyone can easily reproduce the same incident.

Rails 4 App has the following `schema.rb`.

```
ActiveRecord::Schema.define(version: 20170202084559) do

  # These are extensions that must be enabled in order to support this database
  enable_extension "plpgsql"

  create_table "users", force: :cascade do |t|
    t.string   "name"
    t.datetime "created_at", null: false
    t.datetime "updated_at", null: false
  end

end
```

And, Rails 3 App has the following `schema.rb`.

```
ActiveRecord::Schema.define(:version => 20170203032446) do

  create_table "users", :force => true do |t|
    t.string   "name"
    t.datetime "created_at", :null => false
    t.datetime "updated_at", :null => false
  end

end
```

At least, each of them `schema.rb` looks the same.

**Comment by rafaelfranca** [comment]
But does this difference in behavior happens in the same app with different versions? What is different is how the database was created not how Rails behaves. In Rails 3.2 the limit was being set in the column and in Rails 4 it is not being set anymore so you need to specify. This change was intentional.

Just to make sure, what is the result of the structure.sql in both applications when you do `rake db:structure:dump`?

**Comment by gipcompany** [comment]
@rafaelfranca thanks!

> But does this difference in behavior happens in the same app with different versions?

No, each app is an independent app that I newly created with Rails 3 and 4. And just did scaffold user  with its name column.

> In Rails 3.2 the limit was being set in the column and in Rails 4 it is not being set anymore so you need to specify. This change was intentional.

It means that `ActiveRecord::ConnectionAdapters::PostgreSQLColumn#limit` should work as the same in each version? I just would like to make sure how it should work in Rails.

> Just to make sure, what is the result of the structure.sql in both applications when you do rake db:structure:dump?

The dumped files were pasted in [gist](https://gist.github.com/gipcompany/f81f597a9b8175620aead21f8b121f2d). Looks like we can see the difference also in both of dumped files.

**Comment by rafaelfranca** [comment]
> t means that ActiveRecord::ConnectionAdapters::PostgreSQLColumn#limit should work as the same in each version? I just would like to make sure how it should work in Rails.

Yes, it does work in the same way in both version. The difference that you are seeing is on the database creation and in this aspect both versions should behave differently. Rails 3 still set the default limit value, Rails 4 doesn't.

If both versions are running against the same database schema `limit` will return the same value.
