### ISSUE TITLE
Ruby on Rails 5, Ruby 2.4.0 start server fails with Gem openssl 2.0.3

### ISSUE THREAD

**Issue by Sega100500** [rails/rails#27912]
Ruby on Rails 5, Ruby 2.4.0 start server fails with Gem openssl 2.0.3

https://github.com/ruby/openssl/issues/104

**Comment by al2o3cr** [comment]
Sounds like this is an upstream issue - [this comment](https://github.com/ruby/openssl/issues/103#issuecomment-276582243) from the maintainers has more info.
