### ISSUE TITLE
Rails fails on Windows when rails is updated

### ISSUE THREAD

**Issue by pkosenko** [rails/rails#27932]
Updating Rails on Windows destroys rails.
### Steps to reproduce
Install older Ruby on Rails with Rails installer.
Install the latest rails
>gem install rails   
Installs rails 5.0.1
Update gemfile of project to include new rails version
gem 'rails', '5.0.1'
>gem list
rails (5.0.1, 4.2.5.1, 3.2.13)
railties (5.0.1, 4.2.5.1, 3.2.13, 3.2.0)
Run project
>rails server
Bundler could not find compatible versions for gem "railties":
    rails (= 5.0.1) x86-mingw32 was resolved to 5.0.1, which depends on
      railties (= 5.0.1) x86-mingw32  <-- 

Bundler is looking for the windows version, but gem installed the non-windows version when installing rails.  Hence it BROKE the installation.
### Expected behavior
Gem should update rails correctly on Windows and not break the installation.
### Actual behavior
Gem installs non-windows railties and breaks the installation.
### System configuration
**Rails version**:  5.0.1
**Ruby version**:  ruby 2.2.4p230 (2015-12-16 revision 53155) [i386-mingw32]

**Comment by rafaelfranca** [comment]
Thank you for the issue. This is a bug in bundler. Rails does not hsve windows version. it is the same in all platforms

**Comment by pkosenko** [comment]
Thanks for the quick response . . .  I will move my commentary over to Bundler.
