### ISSUE TITLE
Rails ignoring lazy evaluation  (&&): ActiveRecord and instance variables

### ISSUE THREAD

**Issue by jjant** [rails/rails#27931]
### Steps to reproduce

1. Create a model, for example a `Channel` model.
2. In rails console, run `Channel.exists? non_existent_record_id && @var = 5`.
3. `@var` is now `5` even though `Channel.exists?` returned false.

NOTE: Only works with instance variables, for some reason.

### Expected behavior

`@var` should have been `nil` at the end.

### Actual behavior

`@var` gets assigned `5`.

### System configuration
**Rails version**:

`Rails 5.0.1`

**Ruby version**:

`ruby 2.3.1p112 (2016-04-26 revision 54768) [x86_64-darwin16]`

**Comment by rafaelfranca** [comment]
This has nothing to do with Rails. It is how the operator precedence of `&&` behaves. It has more precedence than the method call. So it is being executed as:

```
Channel.exists?(non_existent_record_id && @var = 5)
```

Not

```
Channel.exists?(non_existent_record_id) && @var = 5
```

As you are expecting.
