### ISSUE TITLE
ActionMailer :tls in smtp_settings undocumented

### ISSUE THREAD

**Issue by Sathors** [rails/rails#27937]
In ActionMailer, in the smtp_settings configuration hash, setting :tls to true solved a connection prolem to my smtp server.
But this option is not documented, neither in the rails guide, nor in the official API documentation.

I am not opening a pull request directly, because I am not sure what this option means exactly, or its relation to enable_starttls_auto.

### System configuration
**Rails version**: 5.0.0.1

**Ruby version**: ruby 2.3.3p222 (2016-11-21 revision 56859) [x86_64-linux]

**Comment by jeremy** [comment]
These settings are passed through to the Mail library and then on to Ruby's `net/smtp` as `enable_tls` (and the equivalent `enable_ssl`).

They should be documented at http://www.rubydoc.info/github/mikel/mail/Mail/SMTP but aren't either.

Ruby net/smtp: http://ruby-doc.org/stdlib-2.4.0/libdoc/net/smtp/rdoc/Net/SMTP.html#method-i-enable_tls

Enabling TLS is necessary for mail servers that use SMTPS—SMTP over SSL—on port 587. STARTTLS, on the other hand, is an SMTP protocol command to upgrade to a TLS connection.

Documentation PRs welcome on Action Mailer and the Mail library!

**Comment by Sathors** [comment]
Thanks for the prompt answer @jeremy, I guess I will try to write a PR in the following days.
