### ISSUE TITLE
Remote ip should use the first ip address

### ISSUE THREAD

**Issue by askehansen** [rails/rails#27942]
Shouldn't request.remote_ip return the first address in x-forwarded-for?
https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-Forwarded-For

### Steps to reproduce
`curl -H "X-Forwarded-For: 1.1.1.1,0.0.0.0" "http://localhost:3000/"`

### Expected behavior
`request.remote_ip` should be 1.1.1.1

### Actual behavior
`request.remote_ip` is 0.0.0.0

**Comment by rafaelfranca** [comment]
Thank you for the issue. See https://github.com/rails/rails/pull/7980 discussion and the code to understand why.
