### ISSUE TITLE
Chained associations do not behave consistently 

### ISSUE THREAD

**Issue by abepetrillo** [rails/rails#27946]
### Steps to reproduce
The quick way:

- clone the repo: https://github.com/abepetrillo/rails_issue_example
- run command: rake test
- Observe that the behavior is different between a persisted model and a none persistent model.

I've tried to keep the example as basic as possible, let me know if you need more information.

### Expected behavior
When we are building an ActiveRecord model, any associations that are assigned should support the `through` functionality before being persisted, for example the following test should pass:

```
test "associations" do
    school = School.create(name: 'school')
    principal = Principle.create(name: 'Principal', school: school)
    teacher = Teacher.create(name: 'Teacher', principle: principal)
    student = Student.create(name: 'Student', teacher: teacher)
    assert student.school.id == school.id

    not_persisted_student = Student.new(name: 'unpersisted', teacher: teacher)
    assert not_persisted_student.school.id == school.id
  end
```

### Actual behavior
What actually happens is, the student.school returns `nil` as opposed to the school which is indirectly associated with the teacher.

### System configuration
**Rails version**: 4.2.5.2

**Ruby version**:2.2.3p173

**Comment by al2o3cr** [comment]
This is a feature request, not a bug. Also note that this is only possible for a very specific case (a `through` association through a `belongs_to`).

If you need this functionality, you could get something similar to it by overwriting the generated accessors (in the definition of `Student`):
```ruby
  def school(*args)
    if !persisted? && teacher
      teacher.school
    else
      super
    end
  end
```
(code should work, but I have not tested it)

This can also cause anomalies, depending on which associations your code looks at. For instance, if this worked `non_persisted_student.school.students.include?(non_persisted_student)` then would return `false`.

**Comment by abepetrillo** [comment]
If this is a feature request, should I expect this to fail to:
```
built_student = Student.new(name: 'built student')
    built_student.build_teacher({name: 'Some Teacher', principle: principal})
    assert( built_student.teacher != nil )
```
The student is not persisted but still obeys the `through` association

**Comment by abepetrillo** [comment]
Given your example: `non_persisted_student.school.students.include?(non_persisted_student)` I'm not sure that would be considered an anomaly. I'm expecting school to be available because I'm depending on the `teacher` instance to return it. The `teacher` is persisted so all of it's associations should work. The `non_persisted_student` is not persisted, so when retrieving the collection from the database returning false is reasonable.

Where this gets confusing is what happens if you build the whole tree, should it still work then?

```ruby
school = School.build(name: 'school')
principal = Principle.build(name: 'Principal', school: school)
teacher = Teacher.build(name: 'Teacher', principle: principal)
student = Student.build(name: 'Student', teacher: teacher)
```

I think I would still expect that to work, because doing `principal.school` should be the same as doing `teacher.shool`

In spite of the above I do understand your perspective. I'm not sure how the behavior could be better represented to avoid accidents like I experienced when discovering this behavior.
