### ISSUE TITLE
ActionCable not connecting in certain environments

### ISSUE THREAD

**Issue by lorenzsell** [rails/rails#27955]
Not sure if this is an issue with ActionCable, websockets, or my implementation.  I've asked everyone I can ask, posted on StackOverflow, and done all the research I can, so I'm posting here as a final recourse...

I've built a chat application and in certain environments, particularly office spaces, people are unable to post messages.  I have never been able to replicate the issue personally, which is why it's been very hard to solve.  I thought maybe it was a firewall issue, but it's happened in offices where they had no firewall.

Before I send a message out, I try to test if the connection is active.  The code looks like this:

```
if (App.pods.consumer.connection.disconnected == false) {
    App.pods.speak(message, pod_slug, user_id, msg_type);
  } else {
    if ( !$(".chat-connection-error #ajax-loader").length ) {
      $(".chat-stream").append("<div class='chat-connection-error alert alert-info'><div id='ajax-loader'></div><div class='text-center reconnect-msg'>Reconnecting to server, please wait...</div></div>");
      $(".chat-stream").scrollTop($(".chat-stream")[0].scrollHeight);

      var reconnect = setInterval(function(){
        if(App.pods.consumer.connection.disconnected == false) {
            clearInterval(reconnect);
            $(".chat-connection-error").html("<div class='text-center reconnect-msg'>Connected!</div>").delay(2000).fadeOut("slow");
        }
      }, 200);
    } else {
      $(".reconnect-msg").html("Still trying to reconnect. Please check your internet connection...")
    }
  }
```

Users will just get the trying to reconnect message and are never able to post.  This is happening frequently enough to be a big issue.

**Comment by rafaelfranca** [comment]
Can you please provide a sample application that reproduces the error?

**Comment by shakycode** [comment]
@lorenzsell For what it's worth I had a similar issue with a Cable based app behind a corporate firewall.  The traffic was being filtered heavily although I'm not sure what sorts of traffic or ports.  But every time I tried to use the app at this one office it would not work.  Anywhere else it was fine.

If you can provide a sample app as @rafaelfranca suggested someone from the community will look at it.  I'd be happy to take a stab at it for you.

**Comment by lorenzsell** [comment]
@rafaelfranca and @shakycode - the application is currently running at http://www.sutra.co.  You can create a pod and use the chat feature.  My intention is to actually turn this into an open source project eventually but I am somewhat new to this.  I have created a duplicate repository and added both of you to the repo.  It's a pretty big application that requires a fair amount of set up to get going.  Not sure if you're up for this but if you are I can walk you through the environment variables that need to get set up.

Otherwise let me know if you'd rather I rip out just the relevant action cable parts into a mini app of sorts or how I can make it easier for you to help me with this.  Thank you.

**Comment by rafaelfranca** [comment]
The whole point of asking for a sample application is to make sure the issues is on the framework or the application. A huge application doesn't help with it. It would be better if you try to create a new application and reproduce this issue there.

**Comment by shakycode** [comment]
@lorenzsell The amount of setup your app requires really doesn't help to isolate the behavior.  But I've setup an account on sutra.co and have tested this on 3 different firewall setups (2 strict office environments and 1 home environment).  So far I do not see any issues with ActionCable transmitting messages or getting connection time outs.

In digging into your implementation I think it's fine.  However you sort of answered your own question that the app doesn't work in certain office spaces.  These office spaces may have firewalls or complex NAT configurations which disregard the socket request.  

I feel that you should be looking at the configuration of these office spaces and see what the difference is versus it working from home or a coffee shop.

I don't feel that this is an ActionCable issue.  However if you can make a sample application with your ActionCable implementation solely myself or @rafaelfranca or someone can take a look at this and look for potential issues.

**Comment by shakycode** [comment]
@lorenzsell One thought on this, the forked repo you invited me to I'm looking at on github.  I noticed in environments/production.rb you do not have any request origins set for actioncable.  Is this on purpose?

You also are using subdomains to create spaces.  So in your ActionCable implementation (I went through this same thing) you have to specify the request origins in production.rb and use a regex to handle subdomains.  This may be more of a problem with your request origins and less of an issue with your app working in office spaces.

Just thinking out loud here.  Feel free to email me directly: shakycode@gmail.com if you'd like to pair on this.  I do not think this is an actual Rails issue and can be safely closed by one of the team members.

**Comment by lorenzsell** [comment]
@rafaelfranca @shakycode thanks for your time.  I'll close the issue for now and work on a sample app with just the action cable implementation.  In the meantime, I just sent you an email shakycode...
