### ISSUE TITLE
Issue with PG json queries

### ISSUE THREAD

**Issue by pyromaniac** [rails/rails#27951]
Hello, guys, I've found a strange behavior, it is probably related to the attribute types system.

### Steps to reproduce

```
rails new test_app --database=postgresql
cd test_app
rails generate model user data:jsonb
rails c
```

```ruby
2.3.3 :003 > puts User.where(data: {foo: 42}).to_sql
 => SELECT "users".* FROM "users" WHERE "data"."foo" = 42
2.3.3 :004 > puts User.where(data: {foo: 42}.to_json).to_sql
 => SELECT "users".* FROM "users" WHERE "users"."data" = '"{\"foo\":42}"'
2.3.3 :005 > puts User.where(data: '{foo: 42}').to_sql
 => SELECT "users".* FROM "users" WHERE "users"."data" = '"{foo: 42}"'
```

### Expected behavior

In Rails 4 it was:

```ruby
puts User.where(data: {foo: 42}.to_json).to_sql
 => SELECT "users".* FROM "users" WHERE "users"."data" = '{"foo":42}'
```

AR didn't try to wrap it in one more string.

### Actual behavior

I don't see any way to query the whole content of a jsonb field.

### System configuration
**Rails version**: 5.0.1

**Comment by pyromaniac** [comment]
Found one more interesting thing here:

```ruby
puts User.where(data: [{foo: 42}]).to_sql
 => SELECT "users".* FROM "users" WHERE "users"."data" = '{"foo":42}'
```

**Comment by pyromaniac** [comment]
While the serializer works completely fine:

```ruby
[1] pry(main)> ActiveRecord::ConnectionAdapters::PostgreSQL::OID::Jsonb.new.serialize({foo: 42})
=> "{\"foo\":42}"
[2] pry(main)> ActiveRecord::ConnectionAdapters::PostgreSQL::OID::Jsonb.new.serialize([{foo: 42}])
=> "[{\"foo\":42}]"
```

Seems like where method does all this stuff.

**Comment by pyromaniac** [comment]
Ok, there was an issue with arrays as well, but seems like it is fixed in the upcoming 5.1.0. Thanks everyone for help.

**Comment by hugoroger** [comment]
Are we completely removing that?

`puts User.where(data: [{foo: 42}]).to_sql
 => SELECT "users".* FROM "users" WHERE "users"."data" = '{"foo":42}'`

**Comment by pyromaniac** [comment]
I think it makes sense. What if you got an array in the JSON field and want to query it this way? You will be unable to query one-entry JSON array assuming this hack existence. JSON structures have to be passed as is.
