### ISSUE TITLE
Clickable linkable headers in rails guides

### ISSUE THREAD

**Issue by mbigras** [rails/rails#27958]
Hello Rails team!

One of the features I love about viewing markdown on GitHub is I'm able to easily link to headers.

On [rubyonrails.org](http://guides.rubyonrails.org/index.html) you're able to link to headers also. For example, this a link a section about [dealing with basic forms](http://guides.rubyonrails.org/form_helpers.html#dealing-with-basic-forms).

However, it's only possible to link to these sections by scrolling up to the right bar and clicking on the relevant section; you can't just click on the header link when viewing a markdown file on GitHub.

Reading through the [documentation contribution](http://edgeguides.rubyonrails.org/ruby_on_rails_guides_guidelines.html#headings) section and it looks markdown is used for the guides.

* Does the clickable functionality come from the type of renderer used?
* What does rubyonrails.org use to render markdown?
* What should I start learning/reading/doing if I'd like to eventually have clickable headers for the rails guides?

I looked through the [documentation contributing guidelines](http://edgeguides.rubyonrails.org/contributing_to_ruby_on_rails.html#contributing-to-the-rails-documentation) but nothing jumped out at me immediately.

**Comment by maclover7** [comment]
cc @fxn

**Comment by cefigueiredo** [comment]
Rails guides uses [Redcarpet Markdown](https://github.com/rails/rails/blob/master/guides/rails_guides/markdown.rb#L59)

**Comment by mbigras** [comment]
@cefigueiredo thank you for the jumpstart!

Will look through [vmg/redcarpet](https://github.com/vmg/redcarpet) and see if I can find anything helpful 👍
