### ISSUE TITLE
validates numericality: {greater_than: :other_method} fails with non-numeric comparison values

### ISSUE THREAD

**Issue by lostapathy** [rails/rails#27968]
Given this class:

```
class Product
  include ActiveModel::Validations

  attr_accessor :retail, :wholesale
  validates :retail, numericality: {greater_than: :wholesale}
end
```
When `wholesale` is nil or non-numeric, the validator throws an `ArgumentError: comparison of Fixnum with nil failed`.  It should cause a validation error instead.

Example:
```
irb(main):001:0> p = Product.new
=> #<Product:0x0055625336c8a0>
irb(main):002:0> p.retail = 10
=> 10
irb(main):003:0> p.valid?
ArgumentError: comparison of Fixnum with nil failed
```
It fails when `wholesale` is nil or non-numeric, but works fine in cases where `wholesale` is numeric.

This test added to activemodel/test/cases/validations/numericality_validation_test.rb exposes the issue (in a basic way)
```
  def test_validates_numericality_with_invalid_types
    Topic.validates_numericality_of :approved, greater_than: :returns_nil
    Topic.send(:define_method, :returns_nil, lambda { nil })
    t = Topic.new
    t.approved = 50
    t.valid?
  ensure
    Topic.send(:remove_method, :returns_nil)
  end

```

I'd like to write a patch and PR to turn this into a validation error rather than an exception, but I'm unsure of how to structure the validation message since the error involves another attribute.  Advice is appreciated.

**Comment by rafaelfranca** [comment]
I'd consider this a programmer error not an users error. If you want to use a method as `greater_than` option you need to make sure it only returns a number. Thank you for the issue.

**Comment by lostapathy** [comment]
Perhaps I oversimplified my example, @rafaelfranca, please consider the following:

Both methods (in practice) are columns in the database, and both would have validation to ensure they are numeric, as below (which throws the same exception on valid?).

```
class Product
  include ActiveModel::Validations

  attr_accessor :retail, :wholesale
  validates :retail, numericality: {greater_than: :wholesale}
  validates :wholesale, numericality: true
end
```

One can work around this with either a custom validator (that gracefully handles an invalid `wholesale`) or having `retail` validate via another method that wraps `wholesale` in a way that returns a (bogus) numeric in cases where wholesale is not valid.  

Both options seem like a little much,when it appears very straightforward to modify NumericalityValidator to gracefully raise a validation error, rather than throw an unhandled exception.  I've already written a patch that covers this case (and passes all tests) as well as new tests, I was just hoping for some guidance on how we might construct the right validation message.

**Comment by rafaelfranca** [comment]
I don't think it should be a validation error in this case. It is not an user fault. It is a programmer fault that is using user input to compare with a number. If the user doesn't provide a number to `wholesale` in your example they will already get a validation error an it is enough. Another validation error because of the same error is just burden to the user.

See http://blog.plataformatec.com.br/2009/08/do-not-burden-your-users-with-validations/.

In this case you should conditionally add the validation on retails only if wholesale is a number.

**Comment by rafaelfranca** [comment]
Just a follow up. We discussed on IRC and we agreed that we can improve the exception being raised but not show the error to the end user as a validation error. So I'll keep this issue open to track this improvement in the exception.

**Comment by lostapathy** [comment]
Closing this, #28014 seems to cover my problem case.

**Comment by simi** [comment]
@rafaelfranca Currently this returns "raw" exception.

```ruby
TypeError: can't convert nil into Float 
```

Would be patch introducing better exception welcomed?
