### ISSUE TITLE
Warning Message

### ISSUE THREAD

**Issue by lws68825** [rails/rails#27970]
Hi, After I installed rails 4.2.8.rc, I ran rails -v, and I got a message "Expected string default value for '--rc'; got false (boolean)". Some people say that the latest version of thor(0.19.4) causes this issue, and thor(0.19.1) works well. Please fix it in the final release.

**Comment by sgrif** [comment]
You can safely ignore this warning. You can fix it by uninstalling the latest version of thor and installing an older version, or upgrading to Rails 5.

**Comment by lws68825** [comment]
@sgrif , I think you can modify the railties.gemspec to limit thor version <= 0.19.1.

**Comment by rafaelfranca** [comment]
This specific issue is now fixed in the 4-2-8 branch will be fixing in the final release. Thanks.
