### ISSUE TITLE
Base url for ActiveRecord readme is wrong

### ISSUE THREAD

**Issue by dansteele** [rails/rails#27975]
### Steps to reproduce

https://github.com/rails/rails/blob/master/activerecord/README.rdoc
Click on any of the _Learn more_ links.

### Expected behavior
First link goes to
https://github.com/rails/rails/blob/master/activerecord/classes/ActiveRecord/Base.html

### Actual behavior
Should go to
http://api.rubyonrails.org/classes/ActiveRecord/Base.html

**Comment by fxn** [comment]
That is a page [for the API](http://api.rubyonrails.org/files/activerecord/README_rdoc.html) and links are written to work there, this document is not intended to be read in GitHub.

Thanks for opening the issue anyway.
