### ISSUE TITLE
QueryMethods#lock! not locking row - concurrent SELECT ... FOR UPDATE queries not blocked - 4.2.7.1

### ISSUE THREAD

**Issue by jonahwh** [rails/rails#27988]
### Steps to reproduce
* Create a model, persist one instance of that model to the database
* Run the following (for a model named `Thing`)
```ruby
Thread.new do
  Thing.transaction do
    Thing.where(id: 1).lock!
    puts 'lock granted in thread 1'
    sleep 5
  end
end

Thread.new do
  Thing.transaction do
    Thing.where(id: 1).lock!
    puts 'lock granted in thread 2'
    sleep 5
  end
end
```

### Expected behavior
We should see "lock granted in thread 1", then five seconds later, we should see "lock granted in thread 2"

### Actual behavior
We see "lock granted in thread 1" and "lock granted in thread 2" immediately.

-----

An interesting thing to note is if `Thing.where(id: 1).lock!` is changed to `Thing.where(id: 1).lock!.first` in both threads, everything works fine. Same for `Thing.find(1).lock!`

This same issue occurs if multiple IDs are passed, e.g. `Thing.where(id: [1, 2]).first(2)`

### System configuration
**Rails version**: 4.2.7.1
**PG Gem Version**: 0.19.0
**Postgres Version**: 9.3.3
**Ruby version**: 2.2.2p95

**Comment by rafaelfranca** [comment]
`lock!` as many relation methods are lazy evaluated. They are only sent to the database when you try to read the values. This is why it works with `first`. So, in order to your code work you have to execute the query inside the transaction.

**Comment by matthewd** [comment]
> `lock!` as many relation methods are lazy evaluated

Small correction: `Relation#lock` is a lazily evaluated relation method. `Relation#lock!` is an undocumented internal implementation detail, whose behaviour is undefined.
