### ISSUE TITLE
Arel_table[:column].matches double-quotes its argument

### ISSUE THREAD

**Issue by dolzenko** [rails/rails#27987]
### Steps to reproduce

Rails 4:

```
Blocked::Base.where(Blocked::Base.arel_table[:values].matches("%.com%"))
  Blocked::Base Load (1.1ms)  SELECT `blocked`.* FROM `blocked` WHERE (`blocked`.`values` LIKE '%.com%')
```

Rails 5

```
Blocked::Base.where(Blocked::Base.arel_table[:values].matches("%.com%"))
  Blocked::Base Load (0.7ms)  SELECT `blocked`.* FROM `blocked` WHERE (`blocked`.`values` LIKE '\"%.com%\"')
```

### Expected behavior
Queries to be identical, namely LIKE argument should not be double quoted in Rails 5 version.

### Actual behavior
LIKE argument incorrectly encoded twice leading to query returning empty set after upgrade to Rails 5.

### System configuration
**Rails version**: 5.0.1

**Comment by rafaelfranca** [comment]
Arel is private API and should not be used by users. If you can reproduce this issue without using arel let us know and we will reopen it.

**Comment by sebastianguarin** [comment]
Just wondering is this is already an issue as Arel is now integrated with ActiveRecord.
