### ISSUE TITLE
passing multiple raw sql commands to ActiveRecord::Base.connection.execute returns nil but thesame sql works as psql command

### ISSUE THREAD

**Issue by mankind** [rails/rails#27989]
### Steps to reproduce

I am trying to turn on and turn off **postgresql enable_nestloop** for a single query in activerecord using raw SQL. Here is the command

     class Segment < ApplicationRecord
       def self.count_payload_kind

         s = "
         
           SET LOCAL enable_nestloop = off;

           SELECT count(*)
           FROM   segments s
           WHERE  s.payload @> '[{\"kind\":\"person\"}]';

           SET LOCAL enable_nestloop = on;
         "

         ActiveRecord::Base.connection.execute(s).to_a

       end
     end

When I call **ActiveRecord::Base.connection.execute(s).to_a**, it doesn't return any record and throws no error. However, if I remove the 2 calls to **SET LOCAL enable_nestloop** the query returns the correct count.

Here is the schema.rb

     create_table "segments", force: :cascade do |t|
         t.jsonb    "payload",  default: "[]", null: false 
     end

How can I turn enable_nestloop on and off for one query.

### Expected behavior
It ought to return the correct count eg [{"count"=>2}]

     $> psql --host=x.19.x.2 --port=5432 --username=name  --password --dbname=filter_development
     $> SET LOCAL enable_nestloop = off; SELECT count(*) FROM segments s WHERE s.payload @> '[{"kind":"person"}]'; SET LOCAL enable_nestloop = on;

Running the last psql command returns the correct count instead of nil when using ActiveRecord::Base.connection.execute :

     count 
     -------
     2
    (1 row)

### Actual behavior

When I call **ActiveRecord::Base.connection.execute(s).to_a**, it doesn't return any record and throws no error. However, it works correctly if i remove the 2 calls to **SET LOCAL enable_nestloop**

### System configuration
**Rails 5.0.1**:

**Ruby 2.3.1p112**:

**Comment by rafaelfranca** [comment]
For security reason `execute` only executes the first command when multiple commands are passed in. If you wan to run more than one command you have to call execute more than once inside a transaction.

**Comment by mankind** [comment]
Thanks @rafaelfranca that solved my problem.

**Comment by skunkworker** [comment]
@rafaelfranca 
> For security reason `execute` only executes the first command when multiple commands are passed in. If you wan to run more than one command you have to call execute more than once inside a transaction.

When testing this on Rails `5.2.6`and `6.1.1` using both `activerecord-jdbc-adapter` and using `pg` both in MRI and JRuby, I'm able to have it run earlier commands then return a result from a later command. The following two examples demonstrates this

```
jruby-9.2.7.0 :025 > puts ::ActiveRecord::Base.connection.execute("select pg_sleep(2); show search_path;").to_a
[DEBUG] [2021-05-28 19:01:29 -0600]    (2006.5ms)  select pg_sleep(2); show search_path;
{"search_path"=>"\"$user\",public"}
 => nil
```

and when setting a transaction-local variable
```
jruby-9.2.7.0 :026 > puts ::ActiveRecord::Base.connection.execute("show search_path;").to_a
[DEBUG] [2021-05-28 19:02:26 -0600]    (3.8ms)  show search_path;
{"search_path"=>"\"$user\",public"}
 => nil
jruby-9.2.7.0 :027 > puts ::ActiveRecord::Base.connection.execute("set local search_path = local_foobar; show search_path;").to_a
[DEBUG] [2021-05-28 19:02:37 -0600]    (4.2ms)  set local search_path = local_foobar; show search_path;
{"search_path"=>"local_foobar"}
 => nil
jruby-9.2.7.0 :028 > puts ::ActiveRecord::Base.connection.execute("show search_path;").to_a
[DEBUG] [2021-05-28 19:02:39 -0600]    (2.9ms)  show search_path;
{"search_path"=>"\"$user\",public"}
 => nil
```

Is this a bug or is this correct behavior?

**Comment by zzak** [comment]
@skunkworker That is a good question, to which I'm not sure. I think it would be worth opening a [new issue](http://github.com/rails/rails/issues/new) and adding a [reproducible example](https://github.com/rails/rails/blob/main/guides/bug_report_templates/active_record_main.rb) to help triage.

The examples you posted should be enough though! I'm just worried this comment will get looked over since this issue has been closed for so long 🙏
