### ISSUE TITLE
Rails 5.0.1 issue-- undefined method `push' for #<User::ActiveRecord_Relation:0x0000000aba23b8>

### ISSUE THREAD

**Issue by jaswinder-trantor** [rails/rails#27998]
### Steps to reproduce

Make a query for collections
> @users = User.includes(:account).order(:last_name)

Create a new user record 
> @new_user = User.create(last_name: 'jazz')

Now ,I want to push this new record into the collections
> @users.push(@new_user)

### Expected behavior
The activerecord array should include the new record into its collection

### Actual behavior
But in Rails 5.0.1 ,it is raising an error-
   undefined method `push' for #<User::ActiveRecord_Relation:0x0000000aba23b8>

### System configuration
Rails 5.0.1

Ruby 2.3.0

I have checked 'concat' method in rails 5 https://github.com/rails/rails/blob/master/activerecord/lib/active_record/associations/collection_association.rb , but not working anyway.

**Comment by PareshGupta** [comment]
@jaswinder-trantor 
`concat` and `push` methods work for the collection_association records and not on the parent record. These methods are defined for `:has_many`, `has_many: :through` associations.

For Ex:-

> class User < ActiveRecord::Base
    # field - :firstname
  has_many :posts
end

> class Post < Activerecord::Base
    # field- :title, :user_id
    belongs_to :user
end

> user = User.create(firstname: 'Rails')
user.posts 
#<ActiveRecord::Associations::CollectionProxy []>

>post = Post.create(title: 'Rails is awesome.')
user.posts.concat(post)

>user.posts 
#<ActiveRecord::Associations::CollectionProxy [#<Post id: 1, title: "Rails is awesome.", user_id: 1>]>

**Comment by rafaelfranca** [comment]
Yes, a Relation object doesn't respond to those methods because you should not be able to change a Relation. What you want is to operate in the Relation as an Array so you have to call `to_a` to make it an Array.
