### ISSUE TITLE
ActiveRecord "Learn More" links all 404

### ISSUE THREAD

**Issue by malakai97** [rails/rails#28002]
### Steps to reproduce

1. Go to https://github.com/rails/rails/tree/master/activerecord
2. Glick a "Learn More" link

### Expected behavior
We visit the link

### Actual behavior
We get a 404

**Comment by abevoelker** [comment]
They're links meant for the generated RDocs, not for browsing on GitHub source. You can either view the generated docs on the web (http://api.rubyonrails.org/files/activerecord/README_rdoc.html) or generate them locally yourself with `bundle exec rake rdoc` (http://guides.rubyonrails.org/api_documentation_guidelines.html#rdoc) to see that they are working correctly.

**Comment by prathamesh-sonpatki** [comment]
Yes, this page is not intended to be read on Github. Please check similar comment: https://github.com/rails/rails/issues/27975#issuecomment-279214353
