### ISSUE TITLE
Failed migration in a fresh database prevents subsequent `rails db:drop` from working

### ISSUE THREAD

**Issue by abevoelker** [rails/rails#28001]
### Steps to reproduce

In a fresh Rails app, create a migration that succeeds and a later one that fails:

```ruby
# db/migrate/20170211175941_good_migration.rb
class GoodMigration < ActiveRecord::Migration[5.1]
  def change
  end
end
```

```ruby
# db/migrate/20170211175942_bad_migration.rb
class BadMigration < ActiveRecord::Migration[5.1]
  def change
    raise "fail"
  end
end
```

Then create the database and run the migration with `rails db:create db:migrate`, which fails on the second migration:

```
$ RAILS_ENV=test bundle exec rails db:create db:migrate
Created database 'foo_test'
== 20170211175941 GoodMigration: migrating ====================================
== 20170211175941 GoodMigration: migrated (0.0000s) ===========================

== 20170211175942 BadMigration: migrating =====================================
rails aborted!
StandardError: An error has occurred, this and all later migrations canceled:

fail
...
```

Now if I want to drop the whole database to start over with `rails db:drop`, I can't:

```
$ VERBOSE=true RAILS_ENV=test bundle exec rails db:drop --trace
** Invoke db:drop (first_time)
** Invoke db:load_config (first_time)
** Execute db:load_config
** Invoke db:check_protected_environments (first_time)
** Invoke environment (first_time)
** Execute environment
** Invoke db:load_config 
** Execute db:check_protected_environments
rails aborted!
ActiveRecord::NoEnvironmentInSchemaError: 

Environment data not found in the schema. To resolve this issue, run: 

        bin/rails db:environment:set RAILS_ENV=test
...
```

(Here's a demo app with the above that reproduces the issue: https://github.com/abevoelker/rails5bug/tree/rails-db-drop-issue)

### Expected behavior
`rails db:drop` should succeed

### Actual behavior
`rails db:drop` fails. If I instead do `rails db:environment:set db:drop` it works, but coming from 4.2 it's not intuitive what is going on to cause this error. Apparently the underlying issue is that the new "ar_internal_metadata" table gets created during migrations, but not populated with any rows.

### System configuration
**Rails version**: edge (437020aa6dd4bae19706628daab6725fcb786a45), 5.0.1

**Ruby version**: 2.3.3

**Comment by skipkayhil** [comment]
Fixed in #45185
