### ISSUE TITLE
Test helper `with_routing` does not work with `default_url_options`

### ISSUE THREAD

**Issue by splattael** [rails/rails#28003]
Hi,

I'd like to share a possible bug in `with_routing` test helper when used in combination with `default_url_options`.

### Steps to reproduce

I've created a [reproduction](https://github.com/splattael/with_routing_single) which demonstrates the unexpected behavior described below:
https://github.com/splattael/with_routing_single

### Expected behavior
I would expect the test helper `with_routing` to work with `default_url_options`.
In the case of the reproduction above, I would expect all four tests to pass.

### Actual behavior
The usage of the test helper `with_routing` in combination with `def default_url_options` fails with `ActionController::UrlGenerationError`.

Workaround: Define test routes inside `config/routes.rb`.

### System configuration
**Rails version**:
* 4.2.7.1
* 5.0.1

**Ruby version**:
* 2.3.3

Feedback is very welcome :smile: 

Kind regards,
  Peter

**Comment by maclover7** [comment]
Hi @splattael! The issue isn't with `with_routing`, but that there is no `root` route declared within the `with_routing` block. If you add a `root` route, then all works as fine. The application's routes and `with_routing`'s routes can't be used simultaneously.

**Comment by splattael** [comment]
@maclover7 Thanks for your answer!

You are right, adding `root to: "simple#index"` to https://github.com/splattael/with_routing_single/blob/c24fe33a9c02856c6a23d161430cc439ab5a7f04/single.rb#L79 works.

But why does the "simple" case using `with_routing` pass?
https://github.com/splattael/with_routing_single/blob/c24fe33a9c02856c6a23d161430cc439ab5a7f04/single.rb#L58,L68
IMO it should fail too? There is no `root` route defined neither.

(The only difference between "single" and "with_defaults" is `default_url_options`)

Note: I've [modified](https://github.com/splattael/with_routing_single/commit/c24fe33a9c02856c6a23d161430cc439ab5a7f04) the repro to proof my statement above.

Kind regards,
  Peter

**Comment by maclover7** [comment]
I believe it's because it's including `Rails.application.routes.url_helpers`, which includes the `root` route.

**Comment by splattael** [comment]
@maclover7 Yeah, my example was a bit contrived.

I have another reproduction using a full-fledged Rails application (4.2.7.1) at https://github.com/splattael/with_routing.
The test at https://github.com/splattael/with_routing/blob/master/test/controllers/application_controller_test.rb fails only for the controller which defines `default_url_options`. The other one passes.
I don't know why :-(

For me, it looks like a bug.
WDYT?

Kind regards,
  Peter

**Comment by splattael** [comment]
@maclover7 Any thoughts? Is it worth to re-open this issue?

**Comment by splattael** [comment]
@maclover7 I've updated the reproduction to Rails 4.2.8 and it still fails:
https://github.com/splattael/with_routing 

Do you mind trying the repro above?

I still think that `with_routing` is somewhat broken when used with `default_url_options`.
