### ISSUE TITLE
:if option in after_commit on: :create processed during destroy

### ISSUE THREAD

**Issue by niborg** [rails/rails#28019]
In short, an `after_commit` `:if` option is still triggered after the destroy lifecycle even if the `after_commit` is limited to, say, `[:create, :update]`. This doesn't seem like it should be expected behavior.

### Steps to reproduce
[Here is a gist.](https://gist.github.com/niborg/39214bd8d088eacd1ffb296b6232060d)

### Expected behavior
Since the `after_commit` is limited to being triggered on the create and update events, and therefore never be triggered on destroy events, it seems counter-intuitive for ActiveRecord to bother processing the `:if` option, and can cause errors if the code within the `:if` option assumes that it will only be run when the model is valid and existing.

### Actual behavior
The `after_commit` `:if` option is triggered on destroy.

### System configuration
**Rails version**: Gist reproduces this in 5.0.1. I discovered this issue in 4.2.7.

**Ruby version**: 2.3.1

**Comment by st0012** [comment]
Not related to the subject but I think you can change the gist's filename extension to `.rb` to make it more readable.

**Comment by Erol** [comment]
If you're not yet working on it, I think I can come up with a PR to address this.
