### ISSUE TITLE
ActiveRecord Can't Process Nested Query with Parameterized WHERE Parameters

### ISSUE THREAD

**Issue by mufid** [rails/rails#28015]
### Steps to Reproduce

ActiveRecord can process Nested Query by giving ActiveRecord::Relation inside a where like this:

    > puts User.where(Post.where('views_count > ?', 100).where('posts.user_id = users.id').exists).to_sql
    SELECT "users".* FROM "users" WHERE (EXISTS (SELECT "posts".* FROM "posts" WHERE (views_count > 100) AND (posts.user_id = users.id)))

However, it does not work well if there is a parameterized where inside the inner relation. Example:

    > puts User.where(Post.where(views_count: 100).where('posts.user_id = users.id').exists).to_sql
    SELECT "users".* FROM "users" WHERE (EXISTS (SELECT "posts".* FROM "posts" WHERE "posts"."views_count" =  AND (posts.user_id = users.id))
         --->                                                                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^

### Expected Behaviour

The query can be executed.

### Actual Behaviour

The parameterized WHERE is gone.

    WHERE "posts"."views_count" =  AND (posts.user_id = users.id))

On Postgres, it will throw error:

    2.4.0 :001 > User.where(Post.where(views_count: 100).where('posts.user_id = users.id').exists).to_a
      User Load (0.5ms)  SELECT "users".* FROM "users" WHERE (EXISTS (SELECT "posts".* FROM "posts" WHERE "posts"."views_count" = $1 AND (posts.user_id = users.id)))
    ActiveRecord::StatementInvalid: PG::ProtocolViolation: ERROR:  bind message supplies 0 parameters, but prepared statement "" requires 1
    : SELECT "users".* FROM "users" WHERE (EXISTS (SELECT "posts".* FROM "posts" WHERE "posts"."views_count" = $1 AND (posts.user_id = users.id)))

### System configuration
**Rails version**: 5.0.1

**Ruby version**: 2.4.0

However, it can be reproduced too on Ruby 2.3.1 and Rails `master`.

### Attachment

[Here is the example test case from active record bug test template](https://gist.github.com/mufid/874ec8f6fa265d632f87c0846234477a). I've tested it with both Postgres and SQLite.

**Comment by alexcameron89** [comment]
I've looked into this a little bit and [sized some of it down](https://gist.github.com/alexcameron89/25ce038df3e17093b8fde18214ae0cc9). On 4.2.7,  
`Post.where(views_count: 50..500).where('posts.id = comments.post_id').exists` passes, but 
`Post.where(views_count: 500).where('posts.id = comments.post_id').exists`
does not. Both are failing on master for me.
```
  2) Failure:
BugTest#test_exact_count [../peruse/master_pg.rb:103]:
Expected "EXISTS (SELECT \"posts\".* FROM \"posts\" WHERE \"posts\".\"views_count\" = $1 AND (posts.id = comments.post_id))" to include "500".


  3) Failure:
BugTest#test_range [../peruse/master_pg.rb:97]:
Expected "EXISTS (SELECT \"posts\".* FROM \"posts\" WHERE (\"posts\".\"views_count\" BETWEEN $1 AND $2) AND (posts.id = comments.post_id))" to include "50".
```

So far, it looks like the issue with the range was introduced by 6efb39456a8ee3569f3787cc2f26c041365a0e27. cc @sgrif

**Comment by alexcameron89** [comment]
Looking at it, the following queries work and I believe give you the same result you're looking for in terms of the query:
```
    query = Comment.where(post_id: Post.where(views_count: 50..500))
    assert_includes query.to_sql, '50'
    assert_equal query.to_a.first.post_id, @post.id

    query = Comment.where(post_id: Post.where(views_count: 100))
    assert_includes query.to_sql, '100'
    assert_equal query.to_a.first.post_id, @post.id

Comment Load (0.2ms)  SELECT "comments".* FROM "comments" WHERE "comments"."post_id" IN (SELECT "posts"."id" FROM "posts" WHERE ("posts"."views_count" BETWEEN $1 AND $2))  [["views_count", 50], ["views_count", 500]]
Comment Load (0.2ms)  SELECT "comments".* FROM "comments" WHERE "comments"."post_id" IN (SELECT "posts"."id" FROM "posts" WHERE "posts"."views_count" = $1)  [["views_count", 100]]
```
[Here](https://github.com/rails/rails/blob/127509c071b4f983f2beafc8766e990670a21215/activerecord/test/cases/relation/where_test.rb) are the Active Record test cases for examples on how `where` is tested and expected use cases. Another approach could be a join:
```
    query = Comment.joins(:post).where(posts: { views_count: 50..500 })
    assert_includes query.to_sql, '50'
    assert_equal query.to_a.first.post_id, @post.id

    query = Comment.joins(:post).where(posts: { views_count: 100 })
    assert_includes query.to_sql, '100'
    assert_equal query.to_a.first.post_id, @post.id

Comment Load (0.3ms)  SELECT "comments".* FROM "comments" INNER JOIN "posts" ON "posts"."id" = "comments"."post_id" WHERE ("posts"."views_count" BETWEEN $1 AND $2)  [["views_count", 50], ["views_count", 500]]
Comment Load (0.2ms)  SELECT "comments".* FROM "comments" INNER JOIN "posts" ON "posts"."id" = "comments"."post_id" WHERE "posts"."views_count" = $1  [["views_count", 100]]
```

**Comment by mufid** [comment]
Hi Thanks. Currently, i can use `find_by_sql` for complex query (Can't use join for some reason). Anyway, since `where` can accept `ActiveRecord::Relation`, so i am expecting query i put in description works too.

**Comment by alexcameron89** [comment]
I think the problem is that `exists` does not return an `ActiveRecord::Relation`, instead it returns an `Arel::Nodes::Exists` object, which gets passed to `Comment.where()`. I believe because of that, the `bound_attributes` then get erased for `Post.where(views_count: 50..500).where('posts.id = comments.post_id')` which holds the `50` & `500` values.

**Comment by sgrif** [comment]
`.exists` is not public API.
