### ISSUE TITLE
ActiveRecord DATABASE_URL does not support variables hash

### ISSUE THREAD

**Issue by wkonkel** [rails/rails#28024]
### Steps to reproduce

Given database.yml:
```production:
  adapter: mysql2
  host: host
  port: 3306
  username: user
  password: pass
  database: db
  variables: 
    sql_mode: ''
```

There is no equivalent way to construct a DATABASE_URL with `variables[sql_mode]`.

### Expected behavior
Given:  `DATABASE_URL=mysql2://user:pass@host:3306/db?variables[sql_mode]=`
The connection config should: `@config.fetch(:variables) == { 'sql_mode': '' }`

### Actual behavior

`@config.fetch(:variables)` is empty.

### Related Source Code
* https://github.com/rails/rails/blob/master/activerecord/lib/active_record/connection_adapters/connection_specification.rb#L75
* https://github.com/rails/rails/blob/master/activerecord/lib/active_record/connection_adapters/abstract_mysql_adapter.rb#L866

### System configuration
**Rails version**: 5.0.1
**Ruby version**: 2.4.0

**Comment by rafaelfranca** [comment]
Why do you want to pass it as `DATABASE_URL`? You can use DATABASE_URL with config.yml to when DATABASE_URL is not sufficient.

**Comment by wkonkel** [comment]
DATABASE_URL already supports config options like `?pool=10&timeout=600`. Why would it not support config variables?

**Comment by rafaelfranca** [comment]
Because it is blank and we remove blank configurations https://github.com/rails/rails/blob/master/activerecord/lib/active_record/connection_adapters/connection_specification.rb#L51.

The DATABASE_URL is a security measure to avoid you to put the password in the config file but the best place to configure things in in the database.yml file. Not everything that database.yml file supports will be supported by DATABASE_URL.

You can easily do:

```
production:
  url: ENV['DATABASE_URL']
  variables: 
    sql_mode: ''
```

**Comment by wkonkel** [comment]
We have many connections across many environments and moving from database.yml to ENV based configuration has been extremely helpful in managing all of this. We use a MemSQL database in one environment which doesn't understand the strict mode stuff that Rails 5 is doing by default now. It'd be a step backwards if we had to bring back database.yml for just one connection in one environment. Especially considering that DATABASE_URL format already supports all of the other config options, just not the `variables` hash.

**Comment by wkonkel** [comment]
Also, it's not just because it's blank. It's also because "variables" hash isn't being parsed:

```
> ActiveRecord::ConnectionAdapters::ConnectionSpecification::ConnectionUrlResolver.new("mysql2://localhost/db?strict=false&variables[sql_mode]=test").to_hash
=> {"strict"=>"false", "variables[sql_mode]"=>"test", "adapter"=>"mysql2", "database"=>"db", "host"=>"localhost"}
```

**Comment by rafaelfranca** [comment]
Like I said, `DATABASE_URL` was never meant to support all the cases. database.yml is the most complete configuration option.

**Comment by rafaelfranca** [comment]
Also, if you wan to disable the strict mode why not `strict=false`?

**Comment by rafaelfranca** [comment]
@matthewd do you have any opinion about this?

**Comment by johvet** [comment]
Seems like we're hit by this as well. It seems inconsistent not to support `variables[key]=value` to begin with, while there are useful use-cases (setting session wide parameters like synchronous_commit). As mentioned above there are good reasons to prefer ENV over a database.yml
