### ISSUE TITLE
ActiveRecord::Attributes should work standalone in a PORO

### ISSUE THREAD

**Issue by vizcay** [rails/rails#28020]
```
class FormObject::SignUp
  include ActiveModel::Model
  include ActiveRecord::Attributes

  attribute :birthday, :date
  validates :birthday, presence: true
end
```

It wil be great if, as you can include ActiveModel::Model in a PORO, to also include ActiveRecord::Attributes to use the automatic typecast feature. After all, if you can define a virtual attribute in a ActiveRecord::Base derived class.. why not here?

### Expected behavior
```
f = Form::SignUp.new(birthday: '2017-02-15')
f.birthday # => Date(2017, 2, 15)
```

### Actual behavior
```NameError: undefined local variable or method `reload_schema_from_cache' for FormObjects::SignUp:Class```

### System configuration
**Rails version**: 5.0.1

**Ruby version**: 2.3.1p112

**Comment by rafaelfranca** [comment]
`ActiveRecord::Atrributes` is made to work in ActiveRecord::Base objects. The attribute API will work in POROs in the future, but currently it doesn't.

**Comment by TylerRick** [comment]
As of Rails 5.2 (https://github.com/rails/rails/pull/30985), `ActiveModel::Atrributes` is now available to use in POROs (at least POROs that include `ActiveModel::Model`)...
