### ISSUE TITLE
JSON.parse() chokes on the UTF-8 character EM SPACE (U+2003, e2 80 83)

### ISSUE THREAD

**Issue by 7stud** [rails/rails#28032]
### Steps to reproduce

No error here:

```
json = %Q{
  ["a", "b"]
}

obj = JSON.parse(json)
```

But there is a UTF-8 space character called `EM SPACE`  (U+2003, e2 80 83), which looks like a regular ascii space, and it causes a parse error:

```
def index
  json = %Q{
    ["a",\u2003"b"]
  }
  obj = JSON.parse(json)
end
```

Here's the error in my browser:

```
JSON::ParserError in UsersController#index

419: unexpected token at ' "b"] '

Extracted source (around line #16):
14      }
15
16      obj = JSON.parse(json)
17
18
19
```
### Expected behavior
Because UTF-8 characters are supposed to be valid in json, I expected the ```EM SPACE``` not to cause a parse error.  ```jsonlint.com``` reports the json with the ```EM SPACE``` to be valid, yet rails/ruby can't parse it.

### Actual behavior
I get this error:

```
JSON::ParserError in UsersController#index

419: unexpected token at ' "b"] '

Extracted source (around line #16):
14      }
15
16      obj = JSON.parse(json)
17
18
19
```

### System configuration
**Rails version**:

```
~/rails_projects/test4$ rails -v
Rails 4.2.7
```

**Ruby version**:
```
$ ruby --version
ruby 2.3.0p0 (2015-12-25 revision 53290) [x86_64-darwin14]
```

However, I get the same error running the code outside rails in ruby 2.4.0:
```
require 'json'

json = %Q{
  ["a",\u2003"b"]
}

obj = JSON.parse(json)
```
Here's the error:
```
~/ruby_programs$ ruby --version
ruby 2.3.0p0 (2015-12-25 revision 53290) [x86_64-darwin14]

~/ruby_programs$ ruby 1.rb
/Users/7stud/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/json/common.rb:156:in `parse': 419: unexpected token at ' "b"] (JSON::ParserError)
'
	from /Users/7stud/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/json/common.rb:156:in `parse'
	from 1.rb:7:in `<main>'
```

**Comment by denqxotl** [comment]
Not rails problem

**Comment by 7stud** [comment]
You are right.  I'll report elsewhere.
