### ISSUE TITLE
redirect_to fails when controller has a `location` method

### ISSUE THREAD

**Issue by tylerdiaz** [rails/rails#28033]
## Steps to reproduce
Add a controller method called `location`. Have another method in the controller call `redirect_to`.

Minimum reproducible bug code can be seen here: https://github.com/tylerdiaz/rails-redirect-bug

## Expected behavior
I expect `location` to not be called. It might have models that expect `params` or other request information that a redirect wouldn't provide and cause it to raise an exception. For example, with the following code:

```
class TestController < ApplicationController
  def index
    redirect_to test_destination_path
  end

  def destination
    render text: "What I expect to see"
  end

  def location
    raise 'Error for some reason'
  end
end
```
If I visit `/test/index`, I expect to see the destination text. Instead, the `#location` exception is raised.

## Actual behavior
The `location` method is exectued when I use the `redirect_to` method. If it raises an exception, the `redirect_to` fails and it isn't immediately apparent why that method was called.

## System configuration

**Rails version**:

```
$ rails -v
Rails 5.0.1
```

**Ruby version**:

```
$ ruby -v
ruby 2.3.0p0 (2015-12-25 revision 53290) [x86_64-darwin16]
```

**Comment by al2o3cr** [comment]
Very odd indeed, since there's a test that's supposedly verifying that this *doesn't* happen...

https://github.com/rails/rails/commit/75dd33a0aed96d9f03b79c82f7e5bc5ccf462e8e

**Comment by tylerdiaz** [comment]
@al2o3cr Maybe those test methods _are_ being run. There's just nothing that confirms they weren't called in that commit, and since it doesn't raise an exception it's probably running silently. Furthermore, if there's a `redirect_to` method, it'll probably execute the function but cancel the `render` which makes the issue harder to catch with a test like this.

**Comment by glupo** [comment]
This time location being called from [here](https://github.com/rails/rails/blob/master/actionpack/lib/action_controller/metal/redirecting.rb#L59). 
Changing it to `response.location` as in commit @al2o3cr mentioned will work out since `location` method reads header, but still it does not feel right(to me at least) to address response for redirect location.
