### ISSUE TITLE
Unexpected values in `assert_recognizes` when multiple routes matches

### ISSUE THREAD

**Issue by barthez** [rails/rails#28031]
### Steps to reproduce

When multiple routes matches given path, parameters are being collected from all matched routes.

See [failing test](https://gist.github.com/barthez/d71a31dc2179b4bbda8cae9de1893697)

### Expected behavior

Params from previously matches routes shouldn't be included.

[Suggested fix](https://gist.github.com/barthez/dab12d3f311c73a6a2fa093904f5e146)

### Actual behavior

Params from previously matched routes are included, which makes assertion expect unexpected parameters.

### System configuration
**Rails version**: `5.0.1`

**Ruby version**: `ruby 2.3.3p222 (2016-11-21 revision 56859) [x86_64-darwin15]`

**Comment by thenonsequitur** [comment]
Looks like this was reported here: https://github.com/rails/rails/issues/28398
And fixed in master: https://github.com/rails/rails/commit/886085d6431e4f42191028d05519789f67d32bf8

**Comment by maclover7** [comment]
Closing as a duplicated issue -- the fix is in master and will be out with the next release.

@thenonsequitur 👋 👋
