### ISSUE TITLE
Setting action_mailer default params doesn't define charset

### ISSUE THREAD

**Issue by HoneyryderChuck** [rails/rails#28034]
### Steps to reproduce

1. Create a test rails app with `rails new`, and go get a coffee because it's going to take loong (couldn't resist :) ). 
2. `bundle exec rails g mailer TestMailer`
3. `touch app/views/test_mailer/test_mail.text.erb`
4. define the test_mail method:

```ruby
# inside app/mailer/test_mailer.rb
def test_mail
  mail(subject: "Hi",
          from: "",
          to: "me@me.com")
end
```

This is the set of commands to execute in the console, once I'm done describing the environments:

```
# in the rails console
>  m = TestMailer.test_mail 
> m.charset
```

Run this with:

1. Default configuration (don't change anything)
2. Set ```ruby config.action_mailer.default_params = {from: "noreply@me.com"}``` in `config/application.rb`

### Expected behavior

My expectation is, obviously, that the same result occurs in both cases when you inspect charset. 

### Actual behavior

1. `UTF-8`
2. `nil`

This seems fairly meaningless, but try to actually deliver that mail and you'll get:

```
NoMethodError: undefined method `ascii_only?' for nil:NilClass  
```

and some stacktrace. In simple terms, sending mails breaks. 

My expectation as a user is that, when I set my default params, that these overwrite/do not replace the default params coming from rails. Charset should be the same, unless I specifically set it otherwise. 

### System configuration
**Rails version**:

* Rails 5 latest
* Rails 4.2.7.1

(didn't test others)

**Comment by al2o3cr** [comment]
The [documentation](http://guides.rubyonrails.org/action_mailer_basics.html#action-mailer-configuration) says to use `default_options` not `default_params`. From the implementation, looks like the former does exactly what you're expecting:

https://github.com/rails/rails/blob/f06ee2a703e8cd7c18f70642f3d1d15a43eeb7ce/actionmailer/lib/action_mailer/base.rb#L516

**Comment by HoneyryderChuck** [comment]
You're right, I completely overlooked, as it is a legacy codebase. But what it the default params then? Why can I set them? What's the use case? It led to an IMO obscure error message that took me some time to debug.

**Comment by al2o3cr** [comment]
@HoneyryderChuck From the source, it looks like `default_params` is where the data ultimately lives. (`default_options=` merges the supplied values in)

It's an implementation detail, not something that's intended for public use.

**Comment by HoneyryderChuck** [comment]
can't find any documentation regarding its usage, so I can't really argue about it. As this has been an ancient rails 2 app, this might aso have been the "old way" of doing things. Have to look into it. 

I'd advocate for not allowing setters in context where they shouldn't be accessed, but overall, my issue has been solved. @al2o3cr thank you for your assistance!
