### ISSUE TITLE
ActionView::Helpers::TagHelper.tag won't produce a closed textarea tag

### ISSUE THREAD

**Issue by xanderflood** [rails/rails#28045]
### Steps to reproduce

(Guidelines for creating a bug report are [available
here](http://guides.rubyonrails.org/contributing_to_ruby_on_rails.html#creating-a-bug-report))

Simply create a bare rails application, and place `<%= tag :textarea%>` in the body of any view. The tag produced will be open, and all other HTML code produced from that point until the view is finished rendering will appear as contents inside the textarea.

Overriding the default with `tag :textarea, {}, true` or `tag :textarea, {}, false` has no effect. `tag :input` seems to work perfectly fine.

The `tag` method seems to work perfectly find outside of that context. If I place a `pry` on the line immediately before the `tag` call and evaluate `tag :textarea` in the console, the result is `<textarea />`, a properly closed tag. Sure enough though, after exiting the pry, the rendered page that by browser receives contains an unclosed textarea tag.

As a workaround, anyone else having this issue can place

`<%= html safe '</textarea>'%>`

on the line following the textarea.

### Expected behavior
`tag :textarea` cannot be forced to produce a closed textarea tag. 

### Actual behavior
It produces an open one and renders other page content as textarea contents.

### System configuration
**Rails version**: 5.0.1

**Ruby version**: 2.4.0

I typically use HAML rather than ERB, and originally noticed the bug in that context, but reproduced it in an ERB view as well.

**Comment by Erol** [comment]
Since `textarea` is a block tag, shouldn't you be using `content_tag` instead?

```
<%= content_tag "textarea" %>
```

Or if you want to specify the value:

```
<%= content_tag "textarea" do -%>
  Lorem ipsum dolor...
<%- end -%>
```

**Comment by xanderflood** [comment]
Thanks, that does work, but is this really the intended behavior?

The docs say the `tag` function creates a closed tag by default, not that it depends on the tag name. And the fact that the output of the function is different in a console than when actually rendering seem really bizarre. Not to mention, it breaks my expectation of scope by allowing a tag inside a partial to swallow all subsequent code on the rendered page, even if it was rendered outside the current partial/block., although I suppose that'd be possibly anyways if I deliberately created an open tag.

**Comment by Erol** [comment]
@xanderflood That's because `<textarea />` alone is not a properly closed tag and is not proper HTML. A `textarea` 's value is defined by its content - unlike other elements where you define their value as an attribute - and therefore requires an explicit end tag.

If you try the below HTML code, it will not render correctly:

```html
<!DOCTYPE html>
<html>
  <body>
    <textarea />
  </body>
</html>
```

**Comment by xanderflood** [comment]
Ah that makes a lot of sense. Thank you!

**Comment by kaspth** [comment]
Which documentation have you been looking at?

In the coming Rails 5.1 there's a new syntax, `tag.textarea` which will generate `<textarea>\n</textarea>`.

But in Rails 5 `tag` isn't as smart: https://github.com/rails/rails/blob/e79ffaf7e0a559f79d7a4f764e8381a34fb1759d/actionview/lib/action_view/helpers/tag_helper.rb#L76

The workaround is `content_tag` as suggested above. Thanks!
