### ISSUE TITLE
Order of "through" association affects behavior

### ISSUE THREAD

**Issue by iamvery** [rails/rails#28054]
### Steps to reproduce

Let's say you have two models with a many-to-many association through a join model. We have observed that the order in which you declare the association to the join model and the association _through_ the join model affects the queries generated by ActiveRecord.

Take this example: ([available as a Gist](https://gist.github.com/iamvery/d59f0d3fa0aaf58b326c1496a8b08058) you can clone and run)

```ruby
require "active_record"
require "logger"

ActiveRecord::Base.logger = Logger.new(STDOUT)
ActiveRecord::Base.establish_connection adapter: 'sqlite3', database: ':memory:'
ActiveRecord::Base.connection.create_table :foos do |t|
end
ActiveRecord::Base.connection.create_table :bars do |t|
end
ActiveRecord::Base.connection.create_table :foo_bars do |t|
  t.belongs_to :foo, null: false
  t.belongs_to :bar, null: false
end

class Foo < ActiveRecord::Base
  has_many :bars, through: :foo_bars
  has_many :foo_bars
end
class Bar < ActiveRecord::Base
  has_many :foos, through: :foo_bars
  has_many :foo_bars
end
class FooBar < ActiveRecord::Base
  belongs_to :foo
  belongs_to :bar
end
```

If we attempt the following in the console, persistence fails:

```
irb> f = Foo.create!
=> #<Foo id: 1>
irb> b = Bar.create!(foo_ids: [1])
ActiveRecord::StatementInvalid: SQLite3::ConstraintException: NOT NULL constraint failed: foo_bars.bar_id: INSERT INTO "foo_bars" ("foo_id") VALUES (?)
```

If we swap the order the associations are declared, the example works:

```diff
 class Foo < ActiveRecord::Base
-  has_many :bars, through: :foo_bars
   has_many :foo_bars
+  has_many :bars, through: :foo_bars
 end
 class Bar < ActiveRecord::Base
-  has_many :foos, through: :foo_bars
   has_many :foo_bars
+  has_many :foos, through: :foo_bars
 end
```

```
irb> f = Foo.create!
=> #<Foo id: 1>
irb> b = Bar.create!(foo_ids: [1])
=> #<Bar id: 1>
irb> FooBar.count
=> 1
```

With the first ordering, the query generator is attempting to do an INSERT into `foo_bars` without a `bar_id` and then a second query to UPDATE `foo_bars` with a `bar_id`. Which as you can see does not work if the join table is null-constrained. With the second ordering, both IDs are INSERTed at the same time.

### Expected behavior

This may very well be the expected behavior, but we found it surprising that the order of association declaration would affect the query generator in this way.

### Actual behavior

Shown above.

### System configuration
**Rails version**:
Initially observed on activerecord 4.2.7.1, and subsequently confirmed still an issue on 5.0.1.

**Ruby version**:
Confirmed on 2.2.3 and 2.4.0.

### Proposed Fix

It seems like there are a couple options.
- remove the order sensitivity of dependent associations
- OR warn the user if dependent associations are declared out of order, e.g. `has_many :foos, through: :foo_bars` before` has_many :foo_bars` seen above would result in a warning/error

**Comment by meinac** [comment]
I remember a similar issue with this, I'll try to find it.

**Comment by al2o3cr** [comment]
This configuration (the `through` before the plain `has_many`) is an error on `master`, due to a check added in #27485.

Also resembles the issue reported in #26834.

**Comment by iamvery** [comment]
Awesome! That sounds like the issue should be closed then. Agreed?

**Comment by maclover7** [comment]
Agree, going to close out this issue. Thank you for opening!!

**Comment by iamvery** [comment]
Should have thought to try it against master! 😝 Thanks everyone ❤
