### ISSUE TITLE
rails console doesn't catch RuntimeError and exits

### ISSUE THREAD

**Issue by davetrollope** [rails/rails#28065]
### Steps to reproduce

This is an edge case, but there may be other side effects because it looks like dependency loading is modifying a frozen entity.

Davids-MacBook-Air:gitstats dave$ rails c
Running via Spring preloader in process 28290
Loading development environment (Rails 5.0.1)
Cannot read termcap database;
using dumb terminal settings.
irb(main):001:0> def a
irb(main):002:1> puts a
irb(main):003:1> end
=> :a
irb(main):004:0> a
/Users/dave/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/activesupport-5.0.1/lib/active_support/dependencies.rb:301:in `blame_file!': can't modify frozen fatal (RuntimeError)
	from /Users/dave/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/activesupport-5.0.1/lib/active_support/dependencies.rb:262:in `rescue in load_dependency'
	from /Users/dave/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/activesupport-5.0.1/lib/active_support/dependencies.rb:256:in `load_dependency'
	from /Users/dave/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/activesupport-5.0.1/lib/active_support/dependencies.rb:293:in `require'
	from /Users/dave/dev/gitstats/bin/rails:9:in `<top (required)>'
	from /Users/dave/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/activesupport-5.0.1/lib/active_support/dependencies.rb:287:in `load'
	from /Users/dave/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/activesupport-5.0.1/lib/active_support/dependencies.rb:287:in `block in load'
	from /Users/dave/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/activesupport-5.0.1/lib/active_support/dependencies.rb:259:in `load_dependency'
	from /Users/dave/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/activesupport-5.0.1/lib/active_support/dependencies.rb:287:in `load'
	from /Users/dave/.rbenv/versions/2.2.3/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /Users/dave/.rbenv/versions/2.2.3/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from -e:1:in `<main>'
Davids-MacBook-Air:gitstats dave$

(Guidelines for creating a bug report are [available
here](http://guides.rubyonrails.org/contributing_to_ruby_on_rails.html#creating-a-bug-report))

### Expected behavior
The console should not exit.

irb correctly recurses until the stack is exceeded and then returns to the prompt. console should probably do the same.

### Actual behavior
RuntimeError is raised and causes console to exit

### System configuration
**Rails version**: 5.0.1

**Ruby version**: 2.2.3p173
Davids-MacBook-Air:gitstats dave$ ruby -v
ruby 2.2.3p173 (2015-08-18 revision 51636) [x86_64-darwin15]

**Comment by maclover7** [comment]
It seems like the error is being triggered by defining a function and then calling that function within its body. Closing, since not an Active Support bug.

**Comment by davetrollope** [comment]
Why would exiting the console be the right behaviour? I would expect the console to catch the error and return to the rails console prompt just like irb does.
