### ISSUE TITLE
cannot load such file -- bcrypt_ext while installing devise 

### ISSUE THREAD

**Issue by Feroz-Istar** [rails/rails#28074]
### Steps to reproduce
I am using Rails 5.0.1 and ruby 2.3.3p222 (2016-11-21 revision 56859) [i386-mingw32] versions on windows 10 using railsinstaller .
I have added gem 'devise' in gem file and run bundle install
then rails g devise:install
then in  config/environments/development.rb file i have added the below line 
   config.action_mailer.default_url_options = { host: 'localhost', port: 3000 }
before the end keyword.
then i have run rails g devise user followed by 
   rake db:migrate
after going to this url  http://localhost:3000/users/sign_up while submitting the form i am getting 

**"LoadError in Devise::RegistrationsController#create
cannot load such file -- bcrypt_ext"** 

(Guidelines for creating a bug report are [available
here](http://guides.rubyonrails.org/contributing_to_ruby_on_rails.html#creating-a-bug-report))

### Expected behavior
Tell us what should happen
Expected behaviour is user should be able sign up using devise
### Actual behavior
Tell us what happens instead
I am not able to install required -- bcrypt_ext 
### System configuration
**Rails version**:
Rails 5.0.1
**Ruby version**:
ruby 2.3.3p222 (2016-11-21 revision 56859) [i386-mingw32]

**Comment by al2o3cr** [comment]
This is an issue with how the `bcrypt` gem is packaged for Windows - see https://github.com/codahale/bcrypt-ruby/issues/139 for additional details and suggested fixes.
