### ISSUE TITLE
Feature Request: Error if `content_for` called from within fragment cache

### ISSUE THREAD

**Issue by mipearson** [rails/rails#28072]
It is very easy to accidentally call `content_for` from within a block that will be fragment cached, especially if the cached fragment calls out to a partial. eg:

```erb
<!--  index.html.erb -->
<%= cache "fragment" do %>
  <!-- ... -->
  <%= render "javascript_widget" %>
<% end %>
<!-- load javascript files last -->
<%= content_for :javascript_includes %>

<!--- _javascript_widget.html.erb -->
<div class="jsPlaceholder />
<% content_for :javascript_includes do %>
  <%= javascript_inlcude_tag ... %>
<% end %>
```

### Steps to reproduce

Call `content_for` from within code that will end up in a fragment cache

### Expected behavior

An error should be raised letting the developer know that the content_for would not occur.

### Actual behavior

The contents of the `content_for` are silently discarded.

### System configuration
Rails 5.0.1, Ruby 2.3.1

**Comment by st0012** [comment]
I think feature request should be posted in [mailing list](https://groups.google.com/forum/#!forum/rubyonrails-core)?

**Comment by maclover7** [comment]
Agree with @st0012. Please use the mailing list for feature requests, where a wider community will be able to help you. We reserve the issues tracker for issues only.

**Comment by mipearson** [comment]
No problem, will do.
