### ISSUE TITLE
Joined table alias filtering unpredictability

### ISSUE THREAD

**Issue by rickyhopkins** [rails/rails#28071]
Full disclosure - I am not sure this is a bug, I may just be doing things very wrong, but I have never been so frustrated with lack of documentation/examples as I am with this.

I have created a test gist for this [here](https://gist.github.com/rickyhopkins/5852d1ca575235d4bd27500273aa162b)

Basically if I have a model that looks like:

```
belongs_to :pickup_place, class_name: 'Place'
belongs_to :dropoff_place, class_name: 'Place'

has_one :pickup_street, through: :pickup_place, class_name: 'Street', source: :street
has_one :dropoff_street, through: :dropoff_place, class_name: 'Street', source: :street

has_one :pickup_city, through: :pickup_street, class_name: 'City', source: :city
has_one :dropoff_city, through: :dropoff_street, class_name: 'City', source: :city

scope :pickup_city, lambda { |id|
  joins(:pickup_city).where(pickup_place: { 'streets' => { city_id: id } })
}

scope :dropoff_city, lambda { |id|
  joins(:dropoff_city).where(dropoff_place: { 'streets' => { city_id: id } })
}
```

The scopes, when used individually work well, but when used together the first will work fine but the second will break as the `streets` table gets aliased, which is expected, what I need is a way to know what the table alias is so that I can call it correctly. I could assume that pickup is going to be called first and change the dropoff scope to:

```
scope :dropoff_city, lambda { |id|
  joins(:dropoff_city).where(dropoff_place: { 'pickup_streets_cars_join' => { city_id: id } })
}
```

But this will then break the scope when it is used on its own. I feel like rails should know which table I am referencing based on the hash that I provide and I should not have to be guessing aliases.

I have attempted to extract the alias names based on `current_scope` but have been spectacularly unsuccessful, probably due to inexperience.

$ rails -v
Rails 5.0.0.1
$ ruby -v
ruby 2.3.1p112 (2016-04-26 revision 54768) [x86_64-linux]

**Comment by musicmage4114** [comment]
Hey there!

This sounds like a support request, rather than a bug report. If you're looking for advice or a better way of doing things, I would suggest you ask a question over at [StackOverflow](https://stackoverflow.com/) to receive a quality answer.

If you feel like you're experiencing incorrect behavior, you may want to revise your issue to highlight that, noting in particular the expected versus actual behavior. [Here's a brief guide](https://coenjacobs.me/2013/12/06/effective-bug-reports-on-github/) to writing effective bug reports if you need some guidance.

Happy coding!

**Comment by rickyhopkins** [comment]
I would argue that this is more of a feature request than a support request. I spent 3 solid days trying to work around this issue with endless googling and eventually resorted to asking the question on SO, after 2  days of no SO answers I then went the extra step and offered a bounty on my question. Even this did not result in a viable solution.

I am certain that there needs to be a simple solution to this problem, and as far as I can tell there is nothing in rails that can currently handle this elegantly.

**Comment by musicmage4114** [comment]
If this is a feature request, then it does not belong here. Please see the [guide to Contributing to Rails](http://edgeguides.rubyonrails.org/contributing_to_ruby_on_rails.html#what-about-feature-requests-questionmark) for how feature requests are handled.

In short, you'll need to either contribute the code yourself, or partner with someone else to help you. You can put up a message on the [Rails Core mailing list](https://groups.google.com/forum/?fromgroups#!forum/rubyonrails-core) to see if there anyone who might be interested in assisting you.
