### ISSUE TITLE
Fixnum & Bignum Deprecated ERROR

### ISSUE THREAD

**Issue by ddagone** [rails/rails#28091]
#### I don't know if this really an error but each command I type no matter if it's a 
`$ rails db:migrate `
`$ rails g migration .......`
#### But I keep getting this lines which I can't figure out why 

/Users/rubyn/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/activesupport-5.0.1/lib/active_support/xml_mini.rb:51: warning: constant ::Fixnum is deprecated
/Users/rubyn/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/activesupport-5.0.1/lib/active_support/xml_mini.rb:52: warning: constant ::Bignum is deprecated
/Users/rubyn/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/activesupport-5.0.1/lib/active_support/core_ext/numeric/conversions.rb:138: warning: constant ::Fixnum is deprecated

**Comment by waiting-for-dev** [comment]
It seems it has been fixed in master and will be released with 5.0.2. See #cb0452e and #27366

**Comment by ddagone** [comment]
Thank you but for when the version 5.0.2 is scheduled ?

**Comment by eileencodes** [comment]
We don't have an exact schedule but since it's fixed on master and back ported to 5-0-stable it's fixed and we can close this.

**Comment by ddagone** [comment]
Could you just prevent me when the version 5.0.2 is going to show up ?

**Comment by rafaelfranca** [comment]
We don't know yet

**Comment by ddagone** [comment]
I know but when it will be released :)

**Comment by rafaelfranca** [comment]
The release candidate will be release today.

**Comment by ddagone** [comment]
Great ! How can I install it ? I mean what's the command ?
