### ISSUE TITLE
thread_safe warnings with Rails 4.2.8

### ISSUE THREAD

**Issue by mamantoha** [rails/rails#28099]
Hello, Rails team!

I've just upgraded my application to Rails 4.2.8 and Ruby 2.4.
And I see a lot of warnings in the console when just start the application:

```
2.4.0/lib/ruby/gems/2.4.0/gems/thread_safe-0.3.5/lib/thread_safe/cache.rb:155: warning: constant ::Fixnum is deprecated
```

**Comment by ashishprajapati** [comment]
The warnings come from the activesupport gem which is part of rails and fixed in the new releases.

**Comment by maclover7** [comment]
cc @jdantonio

**Comment by jdantonio** [comment]
cc @pitr-ch

I'm no longer the maintainer, @pitr-ch is. I believe he has an update in the works which clears these warnings. I do not know when that is scheduled to be released.

**Comment by rafaelfranca** [comment]
Closing since it is an issue in thread_safe

**Comment by eproulx-petalmd** [comment]
Since `thread_safe` is now part of `concurrent_ruby`, is there a way to update the dependency to `concurrent_ruby` instead ? Master branch is on `concurrent_ruby`

**Comment by rafaelfranca** [comment]
No. This is a big change for a stable version.

**Comment by mamantoha** [comment]
But this is not a big change in the code https://github.com/mamantoha/rails/compare/4-2-stable...4-2-stable-concurrent-ruby

**Comment by rafaelfranca** [comment]
It is not a big change in terms of diff, but conceptually it is. It is changing a dependency of an almost 2 years old version.

**Comment by eproulx-petalmd** [comment]
I guess will have to wait a PR for `thread_safe`

**Comment by mamantoha** [comment]
`thread_safe` is no longer maintained

**Comment by jdantonio** [comment]
@mamantoha That is not correct. `thread_safe` is deprecated but it is still being actively maintained by @pitr-ch. He merged a PR last month which removes these warnings. I believe he is planning a new release soon.

I have no opinion regarding this issue--I am not arguing for or against. I just want to clarify the status of `thread_safe`.

**Comment by eproulx-petalmd** [comment]
@mamantoha still supported according to this comment https://github.com/ruby-concurrency/thread_safe/issues/24#issuecomment-174592333

**Comment by mamantoha** [comment]
@jdantonio @eproulx-petalmd  thank you for clarifying a situation with `thread_safe` :-)
