### ISSUE TITLE
ActiveSupport::Reloader#reload! invokes `to_prepare` callbacks twice

### ISSUE THREAD

**Issue by f1sherman** [rails/rails#28108]
Calling `reload!` invokes `to_prepare` callbacks twice. This is asserted [in the tests](https://github.com/rails/rails/blob/a92bd65e37bb08a08fd0aaf4d12c7c6cb92c2c17/activesupport/test/reloader_test.rb#L58-L59) but seems undesirable from a consistency and performance standpoint. This also differs from the Rails server behavior, which calls the `to_prepare` callbacks only once when reloading.

### Steps to reproduce
```ruby
# test.rb

begin
  require "bundler/inline"
rescue LoadError => e
  $stderr.puts "Bundler version 1.10 or later is required. Please update your Bundler"
  raise e
end

gemfile(true) do
  source "https://rubygems.org"
  gem "rails", github: "rails/rails"
end

require "active_support"
require "active_support/core_ext/object/blank"
require "minitest/autorun"

class BugTest < Minitest::Test
  def test_reloader_calls_to_prepare_once
    to_prepare_call_count = 0
    reloader = Class.new(ActiveSupport::Reloader)
    reloader.to_prepare { to_prepare_call_count += 1 }
    reloader.reload!
    assert_equal 1, to_prepare_call_count
  end
end
```

```sh
$ ruby test.rb
<SNIP>
# Running:

F

Finished in 0.006512s, 153.5627 runs/s, 153.5627 assertions/s.

  1) Failure:
BugTest#test_reloader_calls_to_prepare_once [test.rb:25]:
Expected: 1
  Actual: 2

1 runs, 1 assertions, 1 failures, 0 errors, 0 skips
```

### Expected behavior
The `to_prepare` callback should be invoked once

### Actual behavior
The `to_prepare` callback is invoked twice

### System configuration
**Rails version**:
master (also reproduced in 5.0.1)

**Ruby version**:
2.4.0

**Comment by maclover7** [comment]
cc @matthewd

**Comment by f1sherman** [comment]
This is working as expected per [this comment](https://github.com/rails/rails/pull/28111#issuecomment-285370954)

**Comment by xiaohui-zhangxh** [comment]
I got the same issue when writing some code in `to_prepare` block, I really don't want `to_prepare` to run twice, but seems Rails do!! I don't why it has to run twice and there almost nobody complain this issue, why?

My solution is add a small feature to ActiveSupport::Reloader

```ruby
require 'active_support'
mod = Module.new do
  RELOADER_EXECUTED_TO_PREPARE_KEY = 'reloader_executed_to_prepare'.freeze
  def to_prepare_executed?
    Thread.current[RELOADER_EXECUTED_TO_PREPARE_KEY] == true
  end

  def self.extended(base)
    base.to_run(:before) { Thread.current[RELOADER_EXECUTED_TO_PREPARE_KEY] = false }
    base.to_prepare(:after) { Thread.current[RELOADER_EXECUTED_TO_PREPARE_KEY] = true }
  end
end

ActiveSupport::Reloader.extend(mod)

# Now I can define my to_prepare block

reloader = Class.new(ActiveSupport::Reloader)
reloader.to_prepare do
  puts "I'm called twice, hmmm..."
end

reloader.to_prepare do
  puts "I just run once in the to_prepare block, good" unless reloader.to_prepare_executed?
end
reloader.reload!
```
