### ISSUE TITLE
Puma startup message breaks the test results

### ISSUE THREAD

**Issue by renchap** [rails/rails#28109]
This is probably for @eileencodes. As the title says, it looks like Puma is started when the first system test is ran, which can happen after other tests ran. When it is the case, the Puma startup message is outputted in the middle of the test results.

FYI it looks like `capybara-rails` suppresses the Puma startup message, hence avoiding this issue.

### Steps to reproduce

Add system tests to your application, run `rails test`

### Expected behavior
Tests output is a continuous line of dots : 
```
$ rails test
# Running tests with run options --seed 58345:
..................
Finished tests in 3.501496s, 5.1407 tests/s, 10.2813 assertions/s.
18 tests, 36 assertions, 0 failures, 0 errors, 0 skips
```

### Actual behavior
The puma starting message appears in the middle of all of those nice dots
```
$ rails test
# Running tests with run options --seed 58345:
.............Puma starting in single mode...
* Version 3.7.1 (ruby 2.3.3-p222), codename: Snowy Sagebrush
* Min threads: 0, max threads: 1
* Environment: test
* Listening on tcp://0.0.0.0:53594
Use Ctrl-C to stop
.....
Finished tests in 3.501496s, 5.1407 tests/s, 10.2813 assertions/s.
18 tests, 36 assertions, 0 failures, 0 errors, 0 skips
```

### System configuration
**Rails version**:
5.1.0 from master

**Ruby version**:
2.3.3p222

**Comment by eileencodes** [comment]
Hrm yea - system tests aren't supposed to run with the whole suite. I'll take a look. Thanks for the report

**Comment by eileencodes** [comment]
Closed by #28286

**Comment by juanbrein** [comment]
I'd like to see this as well, but understand the reasons behind not doing it. You can always use the snippet below to achieve the same results

```
Capybara.configure do |config|
  config.register_server :rails_puma_custom do |app, port, host|
    Rack::Handler::Puma.run(app, Port: port, Threads: "0:1", Silent: true)
  end                                                                     
  config.server = :rails_puma_custom
end
```

**Comment by microweb10** [comment]
I guess you mean:

```
Capybara.register_server :rails_puma_custom do |app, port, host|
  Rack::Handler::Puma.run(app, Port: port, Threads: "0:1", Silent: true)
end

Capybara.configure do |config|                                                                     
  config.server = :rails_puma_custom
end
```

cause `register_server` is a method of the class `Capybara`, not of the class `Config`
[https://www.rubydoc.info/github/jnicklas/capybara/Capybara.register_server](https://www.rubydoc.info/github/jnicklas/capybara/Capybara.register_server)

**Comment by embs** [comment]
This worked for me (as per [Capybara's README'](https://github.com/teamcapybara/capybara/blob/a17115ee07001345b157eb5ebad2c68c729a095d/README.md#setup)):

```ruby
Capybara.server = :puma, { Silent: true } # To clean up your test output
```

**Comment by siegy22** [comment]
@eileencodes 

> system tests aren't supposed to run with the whole suite

Can I ask why? Because before there were system test cases I used to add capybara to my `ActionDispatch::IntegrationTest`s. And they'd run pretty smoothly with all the other tests.

**Comment by eileencodes** [comment]
We made them a separate Rake command because they can be pretty slow. Everywhere I've worked we've run them separate from the main build. On CI I think this makes the most sense. It seems minor for smaller apps but once you get to a larger build it makes a lot of sense. If you want to run them all at once you can write a custom rake task to do that. As for Rails it was a design decision to have them separate.
