### ISSUE TITLE
Use of #count vs. #size when rendering partials with collection

### ISSUE THREAD

**Issue by jwilger** [rails/rails#28110]
### Steps to reproduce

If you have a collection built using an Enumerator, i.e.:
```
class MyController
  def index
    @things = Enumerator.new do |y|
      Things.all.each do |t|
        y << some_expensive_operation_on(t)
      end
    end
end
```

and you want to render each item in a partial:

```
<ul>
  <%= render partial: 'thing', collection: @things %>
</ul>
```

you end up with no list items being rendered.

### Expected behavior

There should be a list item rendered for each item in the `@things` Enumerator.

### Actual behavior

Nothing gets rendered.

The reason is that on line https://github.com/rails/rails/blob/087385a0946645744b7702b3e5af71a04c84e086/actionview/lib/action_view/renderer/partial_renderer.rb#L317, the number of items is being identified using `#size`, which returns `nil` on an Enumerator object. The partial rendering would work with Enumerators if this was changed to use `#count` instead.

Is there a particular reason to use `#size` vs `#count` here?

If so, then perhaps the method should at least emit a warning if you try to use an Enumerator; it took me longer than it should have to realize that was the reason that nothing was being rendered when I could verify that there were indeed items in the collection.

Obviously this usage negates some of the *advantage* of the Enumerator, since it will still have to cycle through each item in order to get the count, but practically that wouldn't be any different than if I just made the Array explicitly in the controller for this purpose. The advantage is that the *controller* then does not need to know exactly how the collection is going to be used by the view (and it eliminates the surprising and "invisible" bug that I encountered.)

I'd be happy to do the PR to make this change, but just wanted to get some feedback first as to whether there was already an explicit decision to use `#size` instead of `#count` here.

### System configuration
**Rails version**: 5.0.0.1

**Ruby version**: 2.2.4

**Comment by jwilger** [comment]
Another option might be to do explicit conversion of the collection argument to an Array (with `Array(collection)`) if the semantics are that the collection is intended to always be an Array. Not sure how I feel about that, though.

**Comment by al2o3cr** [comment]
I'd assume that `count` was avoided since it always runs a query when sent to an `ActiveRecord::Relation`.

You might also consider passing the size (or a callable that can calculate it) to `Enumerator.new` - that will make it either return the given value or call the callable and return its result. Something like:
```ruby
    @things = Enumerator.new(Things.all.count) do |y|
      Things.all.each do |t|
        y << some_expensive_operation_on(t)
      end
    end
```

**Comment by matthewd** [comment]
> Obviously this usage negates some of the advantage of the Enumerator, since it will still have to cycle through each item in order to get the count, but practically that wouldn't be any different than if I just made the Array explicitly in the controller for this purpose.

Untrue: it would iterate twice. That seems bad.

Realistically, the most expected type here is AR::Relation, followed by Array.

I'd accept a PR that, when the collection doesn't respond to `size` or `size` is nil, proceeded to blindly iterate it. But to be honest, from a quick read-through, I don't see why that isn't already happening for you: `instrument` doesn't care about the count.

**Comment by jwilger** [comment]
@al2o3cr:
> You might also consider passing the size (or a callable that can calculate it) to Enumerator.new

Neat! I didn't realize you could do that with Enumerator.

@matthewd:

> Untrue: it would iterate twice. That seems bad.

Yes, you are right about that. Mea culpa. For some reason I got it into my head that Enumerator was caching the calculated values. Not sure *where* I got that idea. Wishful thinking maybe. In my specific use case, I wanted to lazily calculate the items in the list, so that I could avoid the performance hit of the calculation on items that wouldn't actually end up being used without needing to know which items would be used by the calling code. Clearly Enumerator isn't the right (or at least full) solution here. Thanks for pointing that out! :-)

> But to be honest, from a quick read-through, I don't see why that isn't already happening for you: instrument doesn't care about the count.

Hrm. I may have misunderstood what was going on there. Looks like this will require some further investigation into where things are really failing to work as expected when passing an Enumerator. I'll have to do more poking at it when I have time, although that may be a bit, since the immediate need isn't there any more (due to Enumerator not being the right thing here in any case.) Feel free to close this issue if that seems appropriate, and thanks for your time! :-)
