### ISSUE TITLE
inappropriate IrreversibleOrderError

### ISSUE THREAD

**Issue by lazylester** [rails/rails#28117]
### Steps to reproduce
create any (postgres) table named, say, "things" with a string column, called, say "mystring"

the corresponding model:
class Thing < ActiveRecord::Base
  default_scope ->{ order("string_to_array(mystring,'.')::int[]") }
end

(so this will sort when strings are in the format "1.1.3.5", "1.2.8.7" etc)

in rails console, type:
Thing.last

### Expected behavior
should return the Thing instance with the highest value of "mystring" according to the order criterion defined in the model.

### Actual behavior
DEPRECATION WARNING: Finding a last element by loading the relation when SQL ORDER can not be reversed is deprecated. Rails 5.1 will raise ActiveRecord::IrreversibleOrderError in this case. Please call `to_a.last` if you still want to load the relation.

FinderMethods#last interprets the sort criterion (in the default_scope definition) as not being reversible. However, appending "DESC" to the query _does_ correctly reverse the order, it _is_ reversible.

The SQL query that is produced by AR is:
SELECT "things".* FROM "things" ORDER BY string_to_array(mystring,'.')::int[]

it works perfectly well if "DESC" is appended.

Also, it appears that all the records in the table are being intstantiated, and the result set is not being limited to 1, as might be expected from the #last method.

### System configuration
Rails 5.0.0
Postgres 9.4.8

**Ruby version**:
2.3.1

**Comment by matthewd** [comment]
> However, appending "DESC" to the query does correctly reverse the order, it *is* reversible.

Everything "*is* reversible". The question is whether we can programatically determine *how* to reverse it. That, we can't, because without implementing a full SQL parser (for each SQL dialect), we can't tell whether the comma is separating column references (which each need to be reversed individually), or is part of a single column expression (as it is in this case).

**Comment by eugeneius** [comment]
In the example given here, the user knows that they're providing a single expression that can be reversed by appending "DESC". That information is lost when the string is passed to `#order`, which treats it as an SQL fragment which may contain multiple columns.

I thought passing the expression as a hash key might work:

```ruby
default_scope ->{ order("string_to_array(mystring,'.')::int[]" => :asc) }
```

But it ends up being quoted as if it was a column name:

```sql
SELECT  "things".* FROM "things" ORDER BY "things"."string_to_array(mystring,'.')::int[]" DESC LIMIT $1
```

I've opened https://github.com/rails/rails/pull/28191 to try to fix that.
