### ISSUE TITLE
In Rails 5 controller test, nil is converted to string for ActionController::TestCase but not for ActionDispatch::IntegrationTest

### ISSUE THREAD

**Issue by bibstha** [rails/rails#28129]
### Steps to reproduce

```ruby
# helloworld_controller.rb
class HelloworldController < ApplicationController
  def sample_action
    render plain: params["value"].inspect
  end
end
```

Respective Tests

```ruby
class HelloworldControllerTest < ActionDispatch::IntegrationTest
  test "passes with ActionDispatch::IntegrationTest" do
    post helloworld_sample_action_url, params: { "value": nil }
    assert_equal response.body, "nil"
  end

  test "passes with ActionDispatch::IntegrationTest as json" do
    post helloworld_sample_action_url, params: { "value": nil }, as: :json
    assert_equal response.body, "nil"
  end
end

class SecondHelloworldContollerTest < ActionController::TestCase
  tests HelloworldController

  test "fails with ActionController::TestCase" do
    post :sample_action, params: { "value": nil }
    assert_equal response.body, "nil"
  end

  test "passes with ActionController::TestCase as json" do
    post :sample_action, params: { "value": nil }, as: :json
    assert_equal response.body, "nil"
  end
end
```

The failing test works all fine in Rails 4.2
### Expected behavior

a. Either all tests should pass, as ActionController::TestCase and ActionDisplatch::IntegrationTest should work the same.
b. OR, given the conversation in #26075, `ActionDisplatch::IntegrationTest` should also fail the first test.

### Actual behavior

The two `ActionDisplatch::IntegrationTest` and `ActionController::TestCase` behave differently with nil passing in test case.

Ca #26569 also be related?

### System configuration

**Rails version**: 5.0.1
**Ruby version**: 2.3.3

**Comment by rafaelfranca** [comment]
It is a bug in IntegrationTest. The first test should fail.

**Comment by meinac** [comment]
I think the current behaviour of IntegrationTest is valid because you may want to send a query string which does not contain any key&pair but just a string like `example.com/path?string` and the only way to do this is sending parameter with `nil` value. If you have a look at the `raw_post` method of `request` this is what the first test case of `HelloworldControllerTest ` does. I don't know whether this is common or not but I think we have to consider this.

**Comment by rafaelfranca** [comment]
@meinac when do you try `example.com/path?string` in a browser, which value rails get in the controller for `params[:string]`? I guess it is not `nil`.

**Comment by pixeltrix** [comment]
@rafaelfranca 😊 

```
Started GET "/?string" for ::1 at 2017-02-27 11:02:51 +0000
Processing by PagesController#index as HTML
  Parameters: {"string"=>nil}
```

**Comment by pixeltrix** [comment]
When you add the `=` it's an empty string:

```
Started GET "/?string=" for ::1 at 2017-02-27 11:06:28 +0000
Processing by PagesController#index as HTML
  Parameters: {"string"=>""}
```

How does params even work? ¯\_(ツ)_/¯

**Comment by pixeltrix** [comment]
@meinac I think expecting `post` to submit nils is misleading - you'd never get that submitted by a browser from a form. What happens when you use `get '/path?string'` in an integration test vs. a controller test? Hopefully that should work correctly.

**Comment by meinac** [comment]
Yes, browsers do not send nil with form submit but they are not the only user interface to submit forms via HTTP(s). For example following `curl` command does same with hitting an endpoint with just string:
```
curl --data "string" localhost:8888
```

Content type of this post request is `application/x-www-form-urlencoded` and the params object which is parsed by rack is `{"string"=>nil}` and this is completely correct.

The only case that we can't send only keys is while using media type `multipart/form-data`(According to [RFC 2388](https://www.ietf.org/rfc/rfc2388.txt)) therefore following `curl` command does not work:
```
curl -F "string" localhost:8888
```

Btw I'm not trying to force that the behaviour of integration test API should stay same. I just want to add another point of view to the problem which may lead you to think different and figure out possible consequences of decision.

**Comment by pixeltrix** [comment]
@meinac do you have a reference for `x-www-form-urlencoded` being allowed to submit keys only? The [WHATWG reference][1] seems to talk about name-value tuples or name-value-type tuples.

> Btw I'm not trying to force that the behaviour of integration test API should stay same. I just want to add another point of view to the problem which may lead you to think different and figure out possible consequences of decision.

I'm in agreement with @rafaelfranca - the first integration test should fail and I think any weirdness around `?string` doesn't really need to be considered by either integration tests or controller tests because to do otherwise would involve `{ "foo" => nil }.to_query` outputting `foo` and that's going break tons of apps.

[1]:https://url.spec.whatwg.org/#concept-urlencoded-serializer

**Comment by meinac** [comment]
> @meinac do you have a reference for x-www-form-urlencoded being allowed to submit keys only? The WHATWG reference seems to talk about name-value tuples or name-value-type tuples.

For serialization part I could not find any reference and its obvious that we need key&value pairs **but** according to reference you mentioned on your comment, for parsing part if there is no `=` symbol it says `let name have the value of bytes and let value be the empty byte sequence.` which means it is possible to meet with a payload like I mentioned, isn't it?

> I'm in agreement with @rafaelfranca - the first integration test should fail and I think any weirdness around ?string doesn't really need to be considered by either integration tests or controller tests because to do otherwise would involve { "foo" => nil }.to_query outputting foo and that's going break tons of apps.

Of course this should be taken into account and much more important than the case I mentioned. I don't even know someone using it in a way I mentioned, just had encountered with an example on wikipedia and wanted to notice you.

**Comment by laertispappas** [comment]
Is this fixed?
