### ISSUE TITLE
rails 4.2 gets stuck when schema migrations table differs from active migrations on disk

### ISSUE THREAD

**Issue by sandys** [rails/rails#28124]
we had a sequence when another engineer ran migrations on our staging database (and therefore updated the schema migrations table), however forgot to check it in.

We then added new migrations, and then attempted to run these  migrations  on the staging database.

Rake db:migrate gets stuck and doesnt move forward. neither does rollback.

What we expected is an error that the rails migrations are mismatching - that would help us instantly figure out what was wrong. Instead we spent an hour trying to figure out if our connection pooling was working fine, database locks were freed, etc.

**Comment by rafaelfranca** [comment]
Can you please provide a sample application that reproduces the error?

**Comment by sandys** [comment]
im struggling on how to because it is a situation where the schema
migration table has more rows than migration files on disk.

we "fixed"  it by just removing the extra entries in the schema migrations
table,then stuff started running.

**Comment by rafaelfranca** [comment]
Without a way to reproduce it is hard to us to do anything. In my application we always have more rows in the schema migration table than migration files on disk so I don't think that is the problem. We would need a way to reproduce this problem so we can work on a fix.
