### ISSUE TITLE
ActionCable default from npm is 5.1.0-beta1

### ISSUE THREAD

**Issue by dpogue** [rails/rails#28134]
If someone runs `npm install actioncable` now, they're getting the 5.1.0-beta1 release instead of the stable 5.0.1.

This is because `npm install actioncable` is effectively saying `npm install actioncable@latest`.  If you run `npm publish` with no additional arguments, it publishes to the `latest` tag.

The standard way of handling beta or rc releases on npm is to publish to a `next` tag, via `npm publish --tag next`.

To correct this (make 5.0.1 latest, and 5.1.0-beta1 next), you would run
```
npm dist-tag add actioncable@5.1.0-beta1 next
npm dist-tag add actioncable@5.0.1 latest
```

**Comment by matthewd** [comment]
Fixed, thanks!
