### ISSUE TITLE
Screenshots in system testing should not always be displayed

### ISSUE THREAD

**Issue by renchap** [rails/rails#28133]
When running system tests using a CI, there should be an option to not display the screenshot inline : https://github.com/rails/rails/blob/master/actionpack/lib/action_dispatch/system_testing/test_helpers/screenshot_helper.rb#L42

Currently you can set `ENV["CAPYBARA_INLINE_SCREENSHOT"] = "artifact"` but this is not documented.

I would suggest an environment variable to control this behaviour, with a "simple" option to just display the screenshot path, "artifact" to display it using the artifact protocol (supported by some CI), and "inline".

The default could be "inline" (a terminal/platform detection may be better here to avoid big Base64 outputs in basic terminals), and I would strongly advise to have "simple" or "artifact" defined if `ENV["CI"]` is set to provide a sane default.

@eileencodes what do you prefer? I can send a PR with the implementation you want.

**Comment by eileencodes** [comment]
Hey @renchap your preferred suggestion sounds good. Please do go ahead and work on a PR if you want to. Let me know if you have any questions about implementation. Appreciate your finding these issues before final release! 😺
