### ISSUE TITLE
rails secrets:edit => secrets.yml.enc: Permission denied

### ISSUE THREAD

**Issue by drnic** [rails/rails#28143]
### Steps to reproduce

```
$ uname -a
Darwin starkair.local 15.6.0 Darwin Kernel Version 15.6.0: Mon Jan  9 23:07:29 PST 2017; root:xnu-3248.60.11.2.1~1/RELEASE_X86_64 x86_64
$ ruby -v
ruby 2.3.3p222 (2016-11-21 revision 56859) [x86_64-darwin15]
$ rvm @rails51beta --create
$ gem install rails -v 5.1.0.beta1
$ rails new testsekrets
$ cd testsekrets
$ bin/rails secrets:setup
$ bin/rails secrets:edit
```

### Expected behavior

I think I'm supposed to now edit my secrets? Not sure. But output below looks bad; and I'm still not sure how to edit secrets :)

### Actual behavior

```
$ bin/rails secrets:edit
Waiting for secrets file to be saved. Abort with Ctrl-C.
sh: /var/folders/wd/xnncwqp96rj0v1y2nms64mq80000gn/T/secrets.yml.enc: Permission denied
New secrets encrypted and saved.
```

**Update:** trying some `$EDITOR` values:

vim worked - the vim editor showed up and I could see the yaml file:

```
% EDITOR=vim bin/rails secrets:edit
Waiting for secrets file to be saved. Abort with Ctrl-C.
New secrets encrypted and saved.
```

Atom failed differently than above. The atom editor window opened but it was a blank page:

![screen shot 2017-02-24 at 10 38 28 am](https://cloud.githubusercontent.com/assets/108/23285525/6fede4bc-fa7d-11e6-9e39-53e7f6b74757.png)

To reproduce:

```
% EDITOR=atom bin/rails secrets:edit
Waiting for secrets file to be saved. Abort with Ctrl-C.
New secrets encrypted and saved.
```

If `EDITOR` is unset I get the permissions error in this ticket above:

```
% EDITOR= bin/rails secrets:edit
Waiting for secrets file to be saved. Abort with Ctrl-C.
sh: /var/folders/wd/xnncwqp96rj0v1y2nms64mq80000gn/T/secrets.yml.enc: Permission denied
New secrets encrypted and saved.
```

### System configuration
**Rails version**: 5.1.0.beta1

**Ruby version**: 2.3.3p222

**Comment by matthewd** [comment]
I think you need `EDITOR='atom --wait'`. You'd presumably have the same "immediate exit + deleted tempfile" behaviour with Git, say.

We definitely need to handle EDITOR not being set... but I'm not sure we should get clever for editors that default to forking. (@kasper had included such cleverness, but we removed it: 9fdf326a5f6f7e10594dd6205cfc8e0425fb3e67.)

We could detect that the file's unchanged, and give a hint, though.

**Comment by Fudoshiki** [comment]
same issue

**Comment by MrEmelianenko** [comment]
Same situation:

```
Waiting for secrets file to be saved. Abort with Ctrl-C.
sh: /var/folders/s_/6b30sknj2x70ff5f174jtp_h0000gn/T/secrets.yml.enc: Permission denied
New secrets encrypted and saved.
```

OS: Mac OS

**Comment by kaspth** [comment]
Thanks for the report @drnic, I've just pushed a commit to help deal with this and give a better hint as to what's happening. 😊

**Comment by Fudoshiki** [comment]
@kaspth 
Maybe need add note about EDITOR variable
as example 
https://www.sublimetext.com/docs/2/osx_command_line.html
https://gist.github.com/martinbuberl/5823ed247d279d1a2d06

**Comment by kaspth** [comment]
Not sure I follow, there is a note about $EDITOR added in the commit above. What do you mean? :)

Glad to hear it's working!

**Comment by Fudoshiki** [comment]
I did not know about the existence of such a variable.  But I see that this is the standard unix shell variable. But there may be newcomers who are not know it too, can be given a note saying that they need to read about `$EDITOR` env variable and available values?

**Comment by lucas-wade** [comment]
EDITOR=nano bin/rails secrets:edit
Works On Ubuntu 16.04.2

**Comment by cmcollin41** [comment]
Any thoughts on how to get this working on Windows 10? $EDITOR isn't recognized. I've added EDITOR as a variable to to my environment variables to set the path to my editor with --wait. rails secrets:edit runs, but it doesn't open my editor to allow me to edit anything.

**Comment by kaspth** [comment]
I'd be happy to review a pull request that makes it work on Windows. I'm just not a Windows user personally, but if you are please do investigate and PR! 😊

**Comment by K1N5L4Y3R** [comment]
I also have an issue in Windows (have tried with cmd, Git Bash and Cygwin, and the same occurs):

```
$ bin/rails secrets:edit
No $EDITOR to open decrypted secrets in. Assign one like this:

EDITOR="mate --wait" bin/rails secrets:edit

For editors that fork and exit immediately, it's important to pass a wait flag,
otherwise the secrets will be saved immediately with no chance to edit.

$ EDITOR="atom -w" bin/rails secrets:edit
Waiting for secrets file to be saved. Abort with Ctrl-C.
New secrets encrypted and saved.
```

After setting editor (have tried with atom, atom -w, vim, and others), it says it is waiting for the file to be saved, but no editor ever opens.

**Comment by kaspth** [comment]
@K1N5L4Y3R thanks! I've pushed f81f840 with that fix to master and backported it to 5-1-stable at ff7ec79 (with a changelog entry in 457c127).

**Comment by K1N5L4Y3R** [comment]
@kaspth tested it on a new app with edge Rails (from `github: "rails/rails"`) and it worked. Nice job!

As a side note, writing to the file needed no additional configuration. Reading the secrets, however, needed me to use `config.read_encrypted_secrets = true` in config/application.rb. Otherwise I could only see the secrets in secrets.yml. The documentation recommends using this only for Production. Am I missing something here?

**Comment by kaspth** [comment]
We didn't want to just decrypt the secrets in case the key was there. The original impetus was here: https://github.com/rails/rails/pull/28038#discussion_r102193118

**Comment by lucascaton** [comment]
For those who use MacVim, `mvim -f` solves the problem:

```sh
EDITOR='mvim -f' rails credentials:edit
```
