### ISSUE TITLE
ActionController::HttpAuthentication::Token.token_and_options parses the Authorization header unexpectedly 

### ISSUE THREAD

**Issue by andreydeineko** [rails/rails#28148]
```ruby
# API auth token
token   = 'abc'
# API auth options
options = { customer_name: 'Stanton, Kunde and Grady' }
# encode token and options, which works fine
ActionController::HttpAuthentication::Token.encode_credentials(token, options)
```
Now, when I use
```ruby
ActionController::HttpAuthentication::Token.token_and_options(request)
```
to get the auth token and options,

I get
```ruby
["abc", {"customer_name"=>"Stanton", "Kunde and Grady\""=>nil}]
```
instead of
```ruby
["abc", {"customer_name"=>"Stanton, Kunde and Grady"}]
```

It only happens, when `customer_name` has comma in it, works fine with single word names and dashed names.

I think I found the problem:

Having the above data, [`raw_params`](https://github.com/rails/rails/blob/51a2f7bb67cd58a1f5e999ee60f4eb97730f7f35/actionpack/lib/action_controller/metal/http_authentication.rb#L485) method makes it to go wrong from the very first line:
```ruby
_raw_params = auth.sub(TOKEN_REGEX, '').split(/\s*#{AUTHN_PAIR_DELIMITERS}\s*/)
```

Which would return
```ruby
["token=\"abc\"", "customer_name=\"Stanton", "Kunde and Grady\""]
```

Not the expected
```ruby
["token=\"abc\"", "customer_name=\"Stanton, Kunde and Grady\""]
```

The problem is with `,` in
```ruby
AUTHN_PAIR_DELIMITERS = /(?:,|;|\t+)/
```

Rails 5.0.0.1,
Ruby  2.3.3p222

**Comment by pixeltrix** [comment]
@andreydeineko yep, how we extract the auth params from the header doesn't take account of the fact that a comma may be inside a quoted value. We should definitely be parsing the header properly to take account of the quoting. Some devs in Unboxed were keen to get involved with fixing Rails so I'll get them to write a proper parser.
