### ISSUE TITLE
logger methods don't prepend tags in subthread context

### ISSUE THREAD

**Issue by alexjmacdonald** [rails/rails#28156]
I found the issue while writing an ActiveJob subclass, but upon further investigation, this pertains strictly to ```ActiveSupport::TaggedLogger```.

### Steps to reproduce

From a fresh rails project (```rails new```):

Define ```app/jobs/application_job.rb``` thusly:

```ruby
class ApplicationJob < ActiveJob::Base
  def perform
    logger.info("Main thread logger:\t#{logger.inspect}")
    Thread.new do
      logger.info("Sub thread logger:\t#{logger.inspect}")
    end.join
  end
end
```

Run ```ApplicationJob.perform_now``` from the console, then examine output in ```log/development.log```.

### Expected behavior

In ```log/development.log```, all log lines from one job performance should be prepended with the same tags.  By default, [ActiveJob], [ApplicationJob], [:UUID].

### Actual behavior

Lines logged from within a subthread do not contain any tags.

You can see that the same logger is being called from both contexts in this sample output:

```
[ActiveJob] [ApplicationJob] [3fa0fbad-60aa-4613-8f41-3d768309ff78] Performing ApplicationJob from Async(default)
[ActiveJob] [ApplicationJob] [3fa0fbad-60aa-4613-8f41-3d768309ff78] Main thread logger:	#<ActiveSupport::Logger:0x007f8defd15db0 [ trimmed ]>
Sub thread logger:	#<ActiveSupport::Logger:0x007f8defd15db0 [ trimmed ]>
[ActiveJob] [ApplicationJob] [3fa0fbad-60aa-4613-8f41-3d768309ff78] Performed ApplicationJob from Async(default) in 1.06ms
```

### System configuration
**Rails version**: Rails 5.0.1

**Ruby version**: ruby 2.3.1p112 (2016-04-26 revision 54768) [x86_64-darwin16]

**Comment by alexjmacdonald** [comment]
It appears the triggering code is in ``activesupport/lib/active_support/tagged_logging.rb``, method ```current_tags```:
https://github.com/rails/rails/blob/f1c5b0bd0a6211286bfbb8f46991de325d45a2e5/activesupport/lib/active_support/tagged_logging.rb

```current_tags``` maintains a separate tag stack per thread by binding tag stacks to thread IDs.

If I revise my test case above to explicitly manipulate the tag stack, while in the context of the subthread, I achieve the expected behavior:

```ruby
class ApplicationJob < ActiveJob::Base
  def perform
    logger.info("Main thread logger:\t#{logger.inspect}")
    main_thread_tags = logger.formatter.current_tags
    Thread.new do
      logger.formatter.current_tags.replace main_thread_tags
      logger.info("Sub thread logger:\t#{logger.inspect}")
    end.join
  end
end
```

**Comment by rafaelfranca** [comment]
I'm leaning on accepting it as a limitation of the tagged logging and explictly say that tags are not maintained across threads. @matthewd opinion about this one?

**Comment by eugeneius** [comment]
There's a test that specifically covers this behaviour: https://github.com/rails/rails/blob/v5.0.1/activesupport/test/tagged_logging_test.rb#L72-L80

**Comment by sorra** [comment]
Hi, I'm a passer-by.
I try to cover this behavior in the test mentioned above
https://github.com/rails/rails/pull/28171

If we also delegate `#current_tags` to the logger, @alexjmacdonald 's workaround could become shorter:
```Ruby
main_thread_tags = logger.current_tags
# Thread.new ...
logger.push_tags(main_thread_tags)
logger.info("...")
```
Or
```Ruby
logger.tagged(main_thread_tags) do
  logger.info("...")
end
```

**Comment by alexjmacdonald** [comment]
@rafaelfranca As a matter of the Principle of Least Surprise, I would not expect logging behavior of one single thread-safe logger object to vary depending on thread context.

My expectation, if I wanted to have different log tags across threads, would be to create different loggers, with the expectation that they could synchronize access to the underlying log store.

I think a good intermediate fix would be a usage notice in non-prod (default on, toggle-able off) if a logger is called from a non-main thread.

If that sounds reasonable, I'd be happy to code up such a patch.

**Comment by rafaelfranca** [comment]
@alexjmacdonald can you open a PR with the new thread inheriting the value of the main thread?

**Comment by matthewd** [comment]
> the new thread inheriting the value

I don't see how we can do that without a hack like overriding `Thread.new` -- which we've previously declared off limits.

**Comment by alexjmacdonald** [comment]
@matthewd yeah, the big edge case with the approach I mentioned earlier is that ```current_tags``` initializes the thread-local tag stack, so you don't know what your subthread tags are going to be until that method gets coincidentally invoked.  If your main thread is inside a ```tagged``` block, that's going into your subthread tag stack when you wouldn't expect it.  The only way I can think of resolving this would be, as you said, overriding Thread.new to force upfront initialization of those tags.

It might be cleaner to have a global tag stack synchronized across all threads (for [MyController] class-level tags), then thread-local stacks for ```tagged``` (for more event-specific tags like [MyWorkerThread] [PersistingStuff]).  It's a little more complex than the current paradigm, but if there's going to be any thread-dependent behavior then it's worth being explicit about how the tag stack operates.  As a consequence:

-  ```tagged``` would use a thread-local stack; the tagged block implies a temporary scope of applying those tags, in contrast to push/pop_tags which imply permanent mutation of the tag stack.
- a thread-local setting to ignore/override the global tag stack
- optionally initializing the thread-local stack with a thread ID

@rafaelfranca I can, but let me think about these edge cases some more.

**Comment by matthewd** [comment]
There is no main thread, and there is no global context.

**Comment by alexjmacdonald** [comment]
Global meaning shared between threads, i.e. not thread-local.

Main thread = http://ruby-doc.org/core-2.4.1/Thread.html#method-c-main
