### ISSUE TITLE
Remove comments from structure.sql for PostgreSQL adapter

### ISSUE THREAD

**Issue by aripollak** [rails/rails#28153]
When using the postgresql database adapter, run `rake db:structure:dump`. Note that the full version number is included in `db/structure.sql`:

```
-- Dumped from database version 9.5.4
-- Dumped by pg_dump version 9.5.4
```

 If we check it into git, that means that anyone with a different minor version of PostgreSQL server would have differences in the file after running `rake db:migrate`. Would you accept a pull request to remove all "--" comments from the resulting structure.sql?

**Comment by rafaelfranca** [comment]
Yes

**Comment by ZimbiX** [comment]
Edit: Comment moved to new issue: https://github.com/rails/rails/issues/55509
