### ISSUE TITLE
Attempting to install 5.1.0.beta1 fails on actionpack dependency

### ISSUE THREAD

**Issue by sudhirj** [rails/rails#28174]
### Steps to reproduce

Start with a Rails 5.0.1 installation. 

`gem install rails -v 5.1.0.beta1 --pre`

### Expected behavior
Rails 5.1.0.beta1 should be installed.

### Actual behavior
```
ERROR:  While executing gem ... (Gem::DependencyResolutionError)
    conflicting dependencies activesupport (= 3.0.0) and activesupport (= 5.1.0.beta1)
  Activated activesupport-5.1.0.beta1
  which does not match conflicting dependency (= 3.0.0)

  Conflicting dependency chains:
    rails (= 5.1.0.beta1), 5.1.0.beta1 activated, depends on
    activesupport (= 5.1.0.beta1), 5.1.0.beta1 activated

  versus:
    rails (= 5.1.0.beta1), 5.1.0.beta1 activated, depends on
    sprockets-rails (>= 2.0.0), 2.0.0 activated, depends on
    actionpack (>= 3.0), 3.0.0 activated, depends on
    activesupport (= 3.0.0)
```

### System configuration
**Rails version**: 5.0.2.rc1

**Ruby version**: 2.4.0

**Comment by y-yagi** [comment]
That is rubygem's issue, not rails. Ref: https://github.com/rubygems/rubygems/issues/1851

**Comment by sudhirj** [comment]
Closing because it seems to be a Rubygems problem.

**Comment by sudhirj** [comment]
Installed for now using 

`ruby -rbundler/inline -e "gemfile(true) do; source 'https://rubygems.org/'; gem 'rails', '5.1.0.beta1'; end"`

**Comment by jcoyne** [comment]
I'm having the same problem with 5.0.2.rc1.
