### ISSUE TITLE
Rails 5.1.0.beta1: PG::SEInvalidSpecification: ERROR:  no such savepoint

### ISSUE THREAD

**Issue by KeithP** [rails/rails#28197]
This now happens during a full test run against a Postgres DB. Could it be related to PR #28083 ? 

### Steps to reproduce
Run full suite of tests after updating Rails 5.0.1 to 5.1.0.beta1

### Expected behavior
1) Rspec tests should continue to succeed after upgrade
2) We should get the same result running the tests locally and on the build server (codeship)

### Actual behavior
On git push we get 3 test failures out of 1400 on the build server , but on running a failed test locally - it succeeds. And when we run the full suite of tests locally ( with later ruby version 2.3 ) it sometimes succeeds, sometimes fails, sometimes fails to complete and outputs:

```
message type 0x54 arrived from server while idle
message type 0x44 arrived from server while idle
message type 0x43 arrived from server while idle
message type 0x5a arrived from server while idle
.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/logger.rb:654: [BUG] Segmentation fault at 0x000000000001a0
ruby 2.3.0p0 (2015-12-25 revision 53290) [x86_64-linux]
```

Here is the output of a test failure from the build server:

```
Engagement::PublicationsHelper publish_load_complete_notify publishes to subscribers 
Failure/Error: @user = create(:user)
ActiveRecord::StatementInvalid:
PG::SEInvalidSpecification: ERROR:  no such savepoint
: ROLLBACK TO SAVEPOINT active_record_2
/home/rof/cache/bundler/ruby/2.2.0/gems/activerecord-5.1.0.beta1/lib/active_record/connection_adapters/postgresql/database_statements.rb:97:in async_exec
/home/rof/cache/bundler/ruby/2.2.0/gems/activerecord-5.1.0.beta1/lib/active_record/connection_adapters/postgresql/database_statements.rb:97:in block (2 levels) in execute
/home/rof/cache/bundler/ruby/2.2.0/gems/activesupport-5.1.0.beta1/lib/active_support/dependencies/interlock.rb:46:in block in permit_concurrent_loads
/home/rof/cache/bundler/ruby/2.2.0/gems/activesupport-5.1.0.beta1/lib/active_support/concurrency/share_lock.rb:185:in yield_shares
/home/rof/cache/bundler/ruby/2.2.0/gems/activesupport-5.1.0.beta1/lib/active_support/dependencies/interlock.rb:45:in permit_concurrent_loads
/home/rof/cache/bundler/ruby/2.2.0/gems/activerecord-5.1.0.beta1/lib/active_record/connection_adapters/postgresql/database_statements.rb:96:in block in execute
/home/rof/cache/bundler/ruby/2.2.0/gems/activerecord-5.1.0.beta1/lib/active_record/connection_adapters/abstract_adapter.rb:611:in block (2 levels) in log
/home/rof/cache/bundler/ruby/2.2.0/gems/activerecord-5.1.0.beta1/lib/active_record/connection_adapters/abstract_adapter.rb:610:in block in log
/home/rof/cache/bundler/ruby/2.2.0/gems/activesupport-5.1.0.beta1/lib/active_support/notifications/instrumenter.rb:21:in instrument
/home/rof/cache/bundler/ruby/2.2.0/gems/activerecord-5.1.0.beta1/lib/active_record/connection_adapters/abstract_adapter.rb:602:in log
/home/rof/cache/bundler/ruby/2.2.0/gems/activerecord-5.1.0.beta1/lib/active_record/connection_adapters/postgresql/database_statements.rb:95:in execute
/home/rof/cache/bundler/ruby/2.2.0/gems/activerecord-5.1.0.beta1/lib/active_record/connection_adapters/abstract/savepoints.rb:13:in exec_rollback_to_savepoint
/home/rof/cache/bundler/ruby/2.2.0/gems/activerecord-5.1.0.beta1/lib/active_record/connection_adapters/abstract/database_statements.rb:284:in rollback_to_savepoint
/home/rof/cache/bundler/ruby/2.2.0/gems/activerecord-5.1.0.beta1/lib/active_record/connection_adapters/abstract/query_cache.rb:17:in rollback_to_savepoint
/home/rof/cache/bundler/ruby/2.2.0/gems/activerecord-5.1.0.beta1/lib/active_record/connection_adapters/abstract/transaction.rb:112:in rollback
/home/rof/cache/bundler/ruby/2.2.0/gems/activerecord-5.1.0.beta1/lib/active_record/connection_adapters/abstract/transaction.rb:180:in rollback_transaction
/home/rof/cache/bundler/ruby/2.2.0/gems/activerecord-5.1.0.beta1/lib/active_record/connection_adapters/abstract/transaction.rb:201:in rescue in within_new_transaction
/home/rof/cache/bundler/ruby/2.2.0/gems/activerecord-5.1.0.beta1/lib/active_record/connection_adapters/abstract/transaction.rb:198:in within_new_transaction
/home/rof/cache/bundler/ruby/2.2.0/gems/activerecord-5.1.0.beta1/lib/active_record/connection_adapters/abstract/database_statements.rb:225:in transaction
/home/rof/cache/bundler/ruby/2.2.0/gems/activerecord-5.1.0.beta1/lib/active_record/transactions.rb:210:in transaction
/home/rof/cache/bundler/ruby/2.2.0/gems/activerecord-5.1.0.beta1/lib/active_record/transactions.rb:381:in with_transaction_returning_status
/home/rof/cache/bundler/ruby/2.2.0/gems/activerecord-5.1.0.beta1/lib/active_record/transactions.rb:313:in save!
/home/rof/cache/bundler/ruby/2.2.0/gems/activerecord-5.1.0.beta1/lib/active_record/suppressor.rb:46:in save!
/home/rof/cache/bundler/ruby/2.2.0/gems/factory_girl-4.8.0/lib/factory_girl/configuration.rb:18:in block in initialize
/home/rof/cache/bundler/ruby/2.2.0/gems/factory_girl-4.8.0/lib/factory_girl/evaluation.rb:15:in []
/home/rof/cache/bundler/ruby/2.2.0/gems/factory_girl-4.8.0/lib/factory_girl/evaluation.rb:15:in create
/home/rof/cache/bundler/ruby/2.2.0/gems/factory_girl-4.8.0/lib/factory_girl/strategy/create.rb:12:in block in result
/home/rof/cache/bundler/ruby/2.2.0/gems/factory_girl-4.8.0/lib/factory_girl/strategy/create.rb:9:in tap
/home/rof/cache/bundler/ruby/2.2.0/gems/factory_girl-4.8.0/lib/factory_girl/strategy/create.rb:9:in result
/home/rof/cache/bundler/ruby/2.2.0/gems/factory_girl-4.8.0/lib/factory_girl/factory.rb:42:in run
/home/rof/cache/bundler/ruby/2.2.0/gems/factory_girl-4.8.0/lib/factory_girl/factory_runner.rb:29:in block in run
/home/rof/cache/bundler/ruby/2.2.0/gems/activesupport-5.1.0.beta1/lib/active_support/notifications.rb:166:in instrument
/home/rof/cache/bundler/ruby/2.2.0/gems/factory_girl-4.8.0/lib/factory_girl/factory_runner.rb:28:in run
/home/rof/cache/bundler/ruby/2.2.0/gems/factory_girl-4.8.0/lib/factory_girl/strategy_syntax_method_registrar.rb:20:in block in define_singular_strategy_method
./spec/helpers/engagement/publications_helper_spec.rb:39:in block (3 levels) in <top (required)>


Caused by:
PG::SEInvalidSpecification:
ERROR:  no such savepoint
/home/rof/cache/bundler/ruby/2.2.0/gems/activerecord-5.1.0.beta1/lib/active_record/connection_adapters/postgresql/database_statements.rb:97:in async_exec
```

### System configuration
**Rails version**: 5.1.0.beta1
**Ruby version**: ruby/2.2.0

**Comment by maclover7** [comment]
cc @eileencodes

**Comment by matthewd** [comment]
@KeithP are the tests that fail fairly consistent?

From the name alone, I'd guess that publications_helper_spec isn't likely to involve multiple threads or a request/response. Am I wrong on the latter, perhaps?

**Comment by KeithP** [comment]
@matthewd yet to see a pattern in the failures. Have just upgraded Rails 5.0.2 to 5.1.0.beta1 again and pushed to the build server. This time got one failure, with the same error but it was a different test that failed;
Ran the build again: all tests passed;
Ran the build a third time: got 2 failures. Different tests failed, and one of the failures was PG::NoActiveSqlTransaction, reported in two parts like this:

`2.1) Failure/Error: @admin = create(:admin_user)
ActiveRecord::StatementInvalid:
  PG::NoActiveSqlTransaction: ERROR:  SAVEPOINT can only be used in transaction blocks
  : SAVEPOINT active_record_1
  
2.2) Failure/Error: @connection.async_exec(sql)
ActiveRecord::StatementInvalid:
  PG::NoActiveSqlTransaction: ERROR:  ROLLBACK TO SAVEPOINT can only be used in transaction blocks
  : ROLLBACK TO SAVEPOINT active_record_1`

Might be relevant to say we are testing with rspec-rails 3.5 and the active_job.queue_adapter = :sucker_punch

**Comment by KeithP** [comment]
#28466 appears related. It may explain why running the tests locally sometimes hang and fail to complete. The suggested quickie work-around (self.use_transactional_tests = false) would also require an urgent rethink on how to manage / roll back test data. More costly than a quickie.

**Comment by benoitongit** [comment]
Not sure if exact same issue or not, but I inconsistently get the following errors. It happens randomly, 50% chance I would say. No issue when testing with Rails 5.0.2. Only happens with 5.1.0.rc1.

Error:
ChargesControllerTest#test_Show_payment_page:
ActiveRecord::StatementInvalid: PG::NoActiveSqlTransaction: ERROR:  SAVEPOINT can only be used in transaction blocks
: SAVEPOINT active_record_1

Error:
ChargesControllerTest#test_Show_payment_page:
ActiveRecord::StatementInvalid: PG::NoActiveSqlTransaction: ERROR:  ROLLBACK TO SAVEPOINT can only be used in transaction blocks
: ROLLBACK TO SAVEPOINT active_record_1


Error:
ProposalsControllerTest#test_Create_new_proposal:
ActiveRecord::ActiveRecordError: Cannot expire connection, it is owned by a different thread: #<Thread:0x0000000fd39730>. Current thread: #<Thread:0x00000001fe37a0>.

**Comment by KeithP** [comment]
We have Rspec setting config.use_transactional_fixtures = true, which is the default value.
This means "run every test method within a transaction." 
The idea is to start each example/test with a clean database, create whatever data
is necessary for that example, and then remove that data by simply rolling back
the transaction at the end of the example/test.
Changing this setting to false requires a replacement strategy for tearing down data between tests.
Rspec suggests using the database_cleaner gem. So this is what we did and the issue appears to be resolved


# add to Gemfile:
group :test do
  gem 'database_cleaner'
end

# add to spec/rails_helper.rb:
require 'database_cleaner'
config.use_transactional_fixtures = false
RSpec.configure do |config|
  config.before(:suite) do
    DatabaseCleaner.strategy = :truncation
    DatabaseCleaner.clean_with(:truncation)
  end
  config.around(:each) do |example|
    DatabaseCleaner.cleaning do
      example.run
    end
  end
end

Also if your DB migration scripts contain any seed data then you will also need to add this to the before(:each) block where required.

**Comment by eileencodes** [comment]
We changed how active record worked so that you no longer need to use the database cleaner gem @KeithP

**Comment by KeithP** [comment]
Thanks @eileencodes. Just now we re-tested against Rails branch: '5-1-stable': The database cleaner gem is still needed. Without it we got the 'Segmentation fault' error again when run locally, and with it all tests passed. Have those changes landed in '5-1-stable' ?

**Comment by eileencodes** [comment]
I think we're misunderstanding each other. The changes Matthew and I made in #28083 that may have (since we have no way to reproduce it's hard to tell) caused your segmentation fault were added so that database cleaner was no longer needed.

**Comment by eileencodes** [comment]
And I understand you're having a problem with that change. Using database cleaner works for you because you have transactions turned off so the lock code is never activated. It's fine for you to use that for your app but I wouldn't consider that "fixing" the issue.

**Comment by KeithP** [comment]
Its strange. We always used to always have "use_transactional_fixtures = true" and all was well. But for this issue with Rails 5.1.0.rc1 our "workaround" is to change it to false and introduce the database cleaner gem!  :)

**Comment by benoitongit** [comment]
This error happens to me when I am testing a controller action that triggers jobs that interact with the database. Doesn't seems to happen otherwise.

**Comment by eileencodes** [comment]
@benoitongit any possibility of creating a test app that reproduces the issue?

**Comment by benoitongit** [comment]
Sure, here it is: https://github.com/benoitongit/rails-pg-test-issue

You should be able to reproduce by just running rails test.

There is only one test class: test/controllers/users_controller_test.rb
Using ruby 2.4.0 and PG 9.4.5 and Rails 5.1.0.rc1.
