### ISSUE TITLE
ActiveSupport::HashWithIndifferentAccess#compact behaves differently from Hash in Rails 5.1.0.beta1

### ISSUE THREAD

**Issue by nov** [rails/rails#28194]
### Steps to reproduce

```ruby
hash = {foo: :bar}
# => {:foo=>:bar}

hash_with_indifferent_access = ActiveSupport::HashWithIndifferentAccess.new(foo: :bar)
# => {"foo"=>:bar}

hash.compact
# => {:foo=>:bar}

hash_with_indifferent_access.compact
# => nil # NOTE: this case behaves differently from Hash#compact

hash[:bar] = nil
hash_with_indifferent_access[:bar] = nil

hash_with_indifferent_access.compact
# => {"foo"=>:bar}

hash.compact
# => {:foo=>:bar}
```

(Guidelines for creating a bug report are [available
here](http://guides.rubyonrails.org/contributing_to_ruby_on_rails.html#creating-a-bug-report))

### Expected behavior

Same behavior with Ruby's Hash#compact

### Actual behavior

It returns `nil` if nothing removed.

### System configuration
**Rails version**: 5.1.0.beta1

**Ruby version**: 2.4.0

**Comment by matthewd** [comment]
#28138
