### ISSUE TITLE
Can't get proper #arity of scopes

### ISSUE THREAD

**Issue by dsounded** [rails/rails#28198]
### Steps to reproduce

Declare a `scope` in your `model`, let's say:

`scope :active, -> {  where(status: :active) }`

try to get an arity of it in some class method:
`def self.test`
`self.class.method(:active).arity` # always returns -1, 
`end`

from http://ruby-doc.org/core-2.0.0/Method.html#method-i-arity

-1 is only for `C` methods, I've tried `.to_proc` but that haven't helped neither.

### Expected behavior
It should return 0, when no args and args count when scope accepts args.

### Actual behavior
returns -1

### System configuration
4.2.7, but I believe it works the same in newest versions also

**Ruby version**:
2.3.3

**Comment by al2o3cr** [comment]
`-1` is also the arity for Ruby methods which take optional arguments and zero required arguments - which is how `scope` [declares them](https://github.com/rails/rails/blob/4cc1c14493e7a9bd188ee13c237366f6bc2e13f4/activerecord/lib/active_record/scoping/named.rb#L158). I don't think this is a bug.

**Comment by ystefanyuk** [comment]
`-1` also returns when scope expects to receive 1+ args

**Comment by ystefanyuk** [comment]
http://guides.rubyonrails.org/active_record_querying.html#scopes

To define a simple scope, we use the scope method inside the class, passing the query that we'd like to run when this scope is called:

```ruby
class Article < ApplicationRecord
  scope :published, -> { where(published: true) }
end
```

This is exactly the same as defining a class method, and which you use is a matter of personal preference:

```ruby
class Article < ApplicationRecord
  def self.published
    where(published: true)
  end
end
```

For the first example:
```ruby
Article.method(:published).arity # => -1
```

For the second example:
```ruby
Article.method(:published).arity # => 0
```

**Comment by dsounded** [comment]
Dear @rafaelfranca , could you please at least explain why you closed it ?

**Comment by sevenseacat** [comment]
Well scopes and class methods aren't exactly the same. In that example they do the same thing and generate the same SQL, but that isn't always the case. 

http://blog.plataformatec.com.br/2013/02/active-record-scopes-vs-class-methods/ (old but still relevant)

**Comment by dsounded** [comment]
@sevenseacat Yeah, but look at the documentation link above, it says they are, or at least they should act the same. Plus, I need an answer if it's possible or not, if not, how can I overcome this problem ?

**Comment by stereobooster** [comment]
Very hacky approach https://github.com/activerecord-hackery/ransack/pull/1377/files#diff-e64d88952171f9321900495faeb1b53afcddcb90d028264a3918c956ef267a42L56-R73
