### ISSUE TITLE
ActiveRecord changes inner join to left outer join with merge

### ISSUE THREAD

**Issue by meinac** [rails/rails#28219]
If you merge a scope which has `inner join` with another relation then the `inner join` becomes `left join`. It should stay as `inner join`. Below you can find an example test case that demonstrates the issue.

### Steps to reproduce
```ruby
begin
  require 'bundler/inline'
rescue LoadError => e
  $stderr.puts 'Bundler version 1.10 or later is required. Please update your Bundler'
  raise e
end

gemfile(true) do
  source 'https://rubygems.org'
  gem 'rails', github: 'rails/rails'
  gem 'arel', github: 'rails/arel'
  gem 'sqlite3'
end

require 'active_record'
require 'minitest/autorun'
require 'logger'

# This connection will do for database-independent bug reports.
ActiveRecord::Base.establish_connection(adapter: 'sqlite3', database: ':memory:')
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :projects, force: true  do |t|
    t.string :title
  end

  create_table :tasks, force: true do |t|
    t.references :project
    t.string :title
  end

  create_table :submissions, force: true do |t|
    t.references :task
  end
end

class Project < ActiveRecord::Base
  has_many :tasks

  scope :with_some_logic, -> { joins(:tasks).merge(Task.with_some_logic) }
end

class Task < ActiveRecord::Base
  belongs_to :project
  has_many :submissions

  scope :with_some_logic, -> { joins(:submissions) }
end

class Submission < ActiveRecord::Base
  belongs_to :task
end

class BugTest < Minitest::Test
  def test_inner_join
    project_1 = Project.create(title: 'Project 1')
    task_1    = Task.create(title: 'Task 1', project: project_1)
    project_2 = Project.create(title: 'Project 2')
    task_2    = Task.create(title: 'Task 2', project: project_2)
    Submission.create(task: task_1)

    assert_equal 1, Project.with_some_logic.count
  end
end
```

### Expected behavior
Merging relations should not change `inner join` to `left join`.

### Actual behavior
Merging relations changes `inner join` to `left join` on merged part.

### System configuration
**Rails version**: 4.2.x, 5.x.x, master

**Comment by harshvardhansharma** [comment]
some findings:
1. ```joins(:tasks).merge(Task.with_some_logic)``` is processed as one due to lazy loading.
2. Did some benchmarking and found that left join is almost 10times faster than inner join.
3. Also writing ```joins(:submissions)``` in Task class as ```joins('submissions on <join-condition>')``` over rides this default behaviour.

Some other related issues - https://github.com/rails/rails/issues/16140 and https://github.com/rails/rails/issues/12933

**Comment by meinac** [comment]
Hi @harshvardhansharma,

> joins(:tasks).merge(Task.with_some_logic) is processed as one due to lazy loading.

Yes, it should fire only one query because I don't call any kicker method before merge.

> Did some benchmarking and found that left join is almost 10times faster than inner join.

 It depends on lots of parameters like the database you are using, the dataset you are querying against and of course the query itself.

> Also writing joins(:submissions) in Task class as joins('submissions on <join-condition>') over rides this default behaviour.

Yes, rails can't change if I write my join statement by myself.

Thank you for spending time to find related issues, I was not aware of this issue had already been reported. But the issues you mentioned are closed and I think this is a big issue which I've encountered in production environment and someone even may not be able to realise the query is wrong and the data coming from database is not correct which may lead big problems. Because the intention of `merge` is, it merges two ActiveRecord::Relation objects and generates one which gets its behaviour from ancestors which means If I use `inner join` the result of merge should use `inner join`.

**Comment by pixeltrix** [comment]
@meinac thanks for the report but from everything I can see on previous issues related to this it seems to be by design. Whether that design is correct is an argument to be had but I'd doubt we would want to change this behaviour during the beta phase of 5.1, but we could certainly revisit later.
