### ISSUE TITLE
 ActiveSupport::FileUpdateChecker Not worked As expect.

### ISSUE THREAD

**Issue by zw963** [rails/rails#28218]
I split my `config/routes.rb` into some small files which inside `config/routes` directory.

I still need the fancy autoloads feature in development, so I Add following code in my
`config/environments/development.rb`:

```rb
  ActiveSupport::FileUpdateChecker.new(Dir[Rails.root.join('config/routes')]) do
    FileUtils.touch Rails.root.join('config/routes.rb')
  end.execute_if_updated
```

I think it should OK as expect, But not. : (

I found so long time to find out what wrong with this,  still not.

So, I just use Rails dependency gem, like following:
```rb
  Listen.to(Rails.root.join('config/routes'), only: /\.rb$/) do
    FileUtils.touch Rails.root.join('config/routes.rb') 
  end.start
```

It worked very well.

Rails version: 5.0.1
Ruby version: 2.2.4

Thanks

**Comment by maclover7** [comment]
cc @fxn

**Comment by matthewd** [comment]
Yeah... `start` and `execute_if_updated` are not the same. It seems to be working as expected and documented.
