### ISSUE TITLE
Ruby 2.4.0 Update: Unify Fixnum and Bignum into Integer

### ISSUE THREAD

**Issue by likelazyeyes** [rails/rails#28227]
It seems like a mini fix required for ruby 2.4.0
https://www.ruby-lang.org/en/news/2016/12/25/ruby-2-4-0-released/

Output
00:08:02 worker.1 | /home/evo/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/activesupport-5.0.1/lib/active_support/xml_mini.rb:51: warning: constant ::Fixnum is deprecated
00:08:02 worker.1 | /home/evo/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/activesupport-5.0.1/lib/active_support/xml_mini.rb:52: warning: constant ::Bignum is deprecated
00:08:02 web.1    | /home/evo/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/activesupport-5.0.1/lib/active_support/xml_mini.rb:51: warning: constant ::Fixnum is deprecated
00:08:02 web.1    | /home/evo/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/activesupport-5.0.1/lib/active_support/xml_mini.rb:52: warning: constant ::Bignum is deprecated
00:08:04 web.1    | /home/evo/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/activesupport-5.0.1/lib/active_support/core_ext/numeric/conversions.rb:138: warning: constant ::Fixnum is deprecated
00:08:04 worker.1 | /home/evo/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/activesupport-5.0.1/lib/active_support/core_ext/numeric/conversions.rb:138: warning: constant ::Fixnum is deprecated

### System configuration
**Rails version**: 5.0.1

**Ruby version**: 2.4.0

**Comment by morgoth** [comment]
@likelazyeyes it's already fixed - you can try rails 5.0.2.rc1
