### ISSUE TITLE
5.0.2.rc1 deprecation warning

### ISSUE THREAD

**Issue by jcoyne** [rails/rails#28225]
I see `Expected string default value for '--test-framework'; got false (boolean)` when upgrading from 5.0.1 to 5.0.2.rc1.

**Comment by rafaelfranca** [comment]
When you moved from one version to other was also thor updated?

**Comment by jcoyne** [comment]
@rafaelfranca I have thor-0.19.4 in both versions.   5.0.1 has a lot more of these deprecations than 5.0.2.rc1, but I just thought you might want to get rid of all of them.

You can reproduce this problem by running `rails g`

**Comment by rafaelfranca** [comment]
Thanks for confirming. I just want to make sure we didn't add any new warning in 5.0.2. I'll fix it.
