### ISSUE TITLE
upgrade from 5.0 to 5.1 beta throws StandardError

### ISSUE THREAD

**Issue by ferdinandrosario** [rails/rails#28221]
### Steps to reproduce
I tried to upgrade a rails 5.0.1 app to latest 5.1.0.beta1 and found all old migration are failing. adding [4.2] on each old migration resolved the issue.

Is this the expected behaviour for Rails 5.1?

### System configuration
**Rails : 5.1.0.beta1**:

**ruby : 2.4.0**:

**Comment by pixeltrix** [comment]
Yes, because inheriting directing from `ActiveRecord::Migration` was deprecated in Rails 5.0

**Comment by ferdinandrosario** [comment]
👍 Thank you @pixeltrix
