### ISSUE TITLE
Why includes use LEFT JOIN

### ISSUE THREAD

**Issue by xuxiangyang** [rails/rails#28248]
I discovered that when I use `User.includes(:posts)`, includes may create 2 sql sometimes, may use LEFT JOIN sometimes.

what is the condition that includes use LEFT JOIN instead of creating 2 sql?

I need some help, thanks~

**Comment by pixeltrix** [comment]
@xuxiangyang please use other channels listed on the [Community page][1] for help in using/understanding Rails - issues and PRs on GitHub are for the discussions of bugs and new features, thanks.

[1]: http://rubyonrails.org/community/
