### ISSUE TITLE
Action Cable + External App Server

### ISSUE THREAD

**Issue by interpegasus** [rails/rails#28241]
### Steps to reproduce
I would like to use action cable and send real time notifications via Firebase Cloud Messaging (FCM)

### Expected behavior
I would like to know if I can use the FCM app server along with action cable for sending notifications?

### Actual behavior
The documentation mostly mentions about using a proprietary rack server for web socket connections. But it does not mention about integration with third party app servers. Eg: Pusher, FCM, Onesignal

### System configuration
**Rails version**:
```
$ rails --version
Rails 5.0.1
```

**Ruby version**:
```
ruby --version
ruby 2.3.3p222 (2016-11-21 revision 56859)
```

**Comment by matthewd** [comment]
Please use the mailing list or StackOverflow for questions/help, where a wider community will be able to help you. We reserve the issues tracker for issues only.
