### ISSUE TITLE
Running system tests doesn’t output the correct number of assertions made

### ISSUE THREAD

**Issue by joeldrapper** [rails/rails#28254]
### Steps to reproduce

Run `bin/rails test:system`

### Expected behavior

System tests should run and the output should list the number of runs, assertions, failures, errors, and skips.

### Actual behavior

The system tests run, but the output shows `0 assertions` where it should say `11 assertions`.

### System configuration

**Rails version**: 5.1.0.beta1

**Ruby version**: 2.4.0

**Comment by eileencodes** [comment]
Hey @joeldrapper I'm aware of this issue but I'm not sure what we on the Rails side can do about it.

Rails uses the `assert` verb in an assertion definition to figure out the assertions and failures. All of the assertions for system tests come from Capybara and they use a different syntax. So I think we actually need some kind of hook into Capybara or overwrite the Capybara expectations and replace them with Rails expectations.

Maybe @twalpole could give some insight in to the best way to work the number of pass/fail from Capbyara into Rails assertions?

**Comment by twalpole** [comment]
The issue here is that the Capybara assert_xxx methods are not Minitest specific - I could add support for Minitest specific assertions to Capybara to give it parity with the RSpec support we provide, or there is the minitest-capybara gem which provides that.  I would lean towards adding it to Capybara due to the usual lag between Capybara feature adds and third party gem support.  Thoughts?

**Comment by eileencodes** [comment]
Thanks @twalpole! I agree that including it in Capybara, if you're ok with that, would be best.

**Comment by twalpole** [comment]
@joeldrapper It's still very much a WIP, but would you be able to try the Capybara minitest branch - https://github.com/teamcapybara/capybara/tree/minitest,  require 'capybara/minitest' and then include Capybara::Mintest into your test class?  That will let me know if I'm heading down the right track before I spend a lot more time finishing this up.  Thanks

**Comment by twalpole** [comment]
This is now in Capybara's master branch. It would be great if someone could give it a try and confirm it's what is desired/expected .

**Comment by joeldrapper** [comment]
Thanks @twalpole, I’ll check it out!

**Comment by eileencodes** [comment]
I think I may be missing a step (apologies for not being able to test earlier). I've included `require 'capybara/minitest'` in my test helper and then updated Capybara to point at master but I'm not seeing any changes. 

Here's my test (capybara/minitest is included in application_system_test_case):

```ruby
require "application_system_test_case"

class PostsTest < ApplicationSystemTestCase
  test "visiting the index" do
    visit posts_url

    assert_selector "h1", text: "Posts"
  end
end
```

Output where 1 passes but assertions aren't 1.

```
.

Finished in 1.932343s, 0.5175 runs/s, 0.0000 assertions/s.

1 runs, 0 assertions, 0 failures, 0 errors, 0 skips
```

**Comment by lucasmazza** [comment]
I managed to replace https://github.com/wojtekmach/minitest-capybara with the `Capybara::Minitest::Assertion` module on our 5.0.x app (I opened teamcapybara/capybara#1843 to clarify some of the required steps)

```ruby
require 'test_helper'

class StaticTest < ActionDispatch::IntegrationTest
  include Capybara::DSL
  include Capybara::Minitest::Assertions

  teardown do
    Capybara.reset_sessions!
    Capybara.use_default_driver
  end

  test 'renders the home page' do
    visit root_path

    10.times do
      assert_css 'h1'
    end
  end
end
```
```
$ bin/rails t test/integration/static_test.rb
Running via Spring preloader in process 86796
Run options: --seed 17487

# Running:

.

Finished in 0.984111s, 1.0161 runs/s, 10.1615 assertions/s.

1 runs, 10 assertions, 0 failures, 0 errors, 0 skips
``` 

I'm going to review this with rails HEAD (and `ApplicationSystemTestCase` over `IntegrationTest`) later.

**Comment by eileencodes** [comment]
Ah! It needed to be `include Capybara::Minitest::Assertions`, not require 'capybara/minitest'. Thanks @lucasmazza I'm seeing it work now.

**Comment by joeldrapper** [comment]
Thank you @eileencodes and @twalpole!

**Comment by twalpole** [comment]
@eileencodes Sorry about that, I changed the module names after posting the initial instructions - The Capybara readme had the include correctly identified but I didn't update here.   @lucasmazza  submitted a PR that makes the README much more explicit which is now in Capybara's master branch.  Barring anything unforeseen Capybara 2.13 including this will be released within the next week or so.

**Comment by eileencodes** [comment]
Thanks so much for working on this @twalpole! I'll be on the lookout for the new release. At that time I'll bump Capybara in Rails and then close this PR.

**Comment by twalpole** [comment]
@eileencodes Capybara 2.13.0 has been released with this included

**Comment by eileencodes** [comment]
Thank you @twalpole for getting this upstream and for letting me know when it was released!! I've pushed a commit to Rails https://github.com/rails/rails/commit/eadbc82c47fd157ed4f1eb4c4983ab0734023106 that bumps Capybara and adds the required minitest file to the test case. 🎉
