### ISSUE TITLE
Rails 5.1: Cannot require yarn packages

### ISSUE THREAD

**Issue by ankitrg** [rails/rails#28263]
I tried to install vue.js like: 

```
yarn add vue
```
Then I add a line 
```
//= require vue
```

in application.js, which throws error:

```
ActionView::Template::Error (couldn't find file 'vue' with type 'application/javascript'
Checked in these paths: 
  /home/aks/playground/toppack/app/assets/config
  /home/aks/playground/toppack/app/assets/images
  /home/aks/playground/toppack/app/assets/javascripts
  /home/aks/playground/toppack/app/assets/stylesheets
  /home/aks/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/coffee-rails-4.2.1/lib/assets/javascripts
  /home/aks/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/actioncable-5.1.0.beta1/lib/assets/compiled
  /home/aks/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/actionview-5.1.0.beta1/lib/assets/compiled
  /home/aks/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/turbolinks-source-5.0.0/lib/assets/javascripts
  /home/aks/playground/toppack/node_modules):
```

What I think is `bin/yarn` is creating `node_modules` directory in the root instead of `vendor`. This could be the problem.

> Note: I have yarn installed globally too.

**Comment by atussec** [comment]
i am having the same issue here.
```
couldn't find file 'vue' with type 'application/javascript'
Checked in these paths: 
  /home/geniuskid/rails/butik/app/assets/config
  /home/geniuskid/rails/butik/app/assets/images
  /home/geniuskid/rails/butik/app/assets/javascripts
  /home/geniuskid/rails/butik/app/assets/stylesheets
  /home/geniuskid/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/jquery-rails-4.2.2/vendor/assets/javascripts
  /home/geniuskid/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/coffee-rails-4.2.1/lib/assets/javascripts
  /home/geniuskid/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/actioncable-5.1.0.beta1/lib/assets/compiled
  /home/geniuskid/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/actionview-5.1.0.beta1/lib/assets/compiled
  /home/geniuskid/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/turbolinks-source-5.0.0/lib/assets/javascripts
  /home/geniuskid/rails/butik/node_modules

```
as from the log the node_modules folder created in the root

**Comment by ankitrg** [comment]
I figured it out, I am not sure if the location of `node_modules` is correct or not, but I was able to import them like: 

```
//= require rails-ujs
//= require turbolinks
//= require vue/dist/vue
//= require vue-strap/dist/vue-strap
//= require_tree .
```

I looked into `assets.rb` they it expects node_modules to be in the root, I hope someone can comment on this.

I would like to ask, can there be a better way to import things? Like we do in es6:

`import vue from 'vue';` or something. I need to get inside node modules and see the structure for all the package and decide for myself what to import!

**Comment by maclover7** [comment]
cc @dhh

**Comment by dhh** [comment]
@ankitrg That's the correct way to do it via the asset pipeline. If you use Webpacker, you can use the import vue style.

**Comment by piedoom** [comment]
I have a quick question.

I built my app when Rails 5 launched, and I recently upgraded to 5.1  I want to use Yarn with my project, but could only find docs on how to start a new project with the `--yarn` option.

Looking through the changes, I could only find the line in `assets.rb` that includes `node_modules` in the assets, so I added that to my older project along with setting up yarn.  However, I'm still running into a `Sprockets::FileNotFound` error on my old project, whereas my new test project made with the `--yarn` flag works fine.  Is there another config setting I'm missing?

**Comment by rickapichairuk** [comment]
I am also experiencing the same error. I am using Rails 5.1.1 and Ruby version 2.4.1p111 (2017-03-22 revision 58053):

```
$ rbenv exec bundle exec rake assets:precompile
yarn install v0.24.5
[1/4] Resolving packages...
success Already up-to-date.
Done in 0.08s.
rake aborted!
Sprockets::FileNotFound: couldn't find file 'turbolinks' with type 'application/javascript'
Checked in these paths:
```

**Comment by 7stud** [comment]
> `require vue/dist/vue`
> 
> That's the correct way to do it via the asset pipeline. If you use Webpacker, you can use the import vue style.
