### ISSUE TITLE
Rails 5.1 Action cable breaks when importing lodash

### ISSUE THREAD

**Issue by ankitsinghaniyaz** [rails/rails#28268]
I installed `lodash` via yarn and when I try to require the file, I get the following error:

```
Uncaught ReferenceError: module is not defined
    at action_cable.source-689da07….js:1
(anonymous) @ action_cable.source-689da07….js:1
```

For some reason, action_cable seems to break when importing `underscore`.

**Comment by maclover7** [comment]
cc @javan

**Comment by javan** [comment]
@ankitsinghaniyaz, can you provide more details please? When does this error occur? Are you using webpack?

**Comment by ankitsinghaniyaz** [comment]
@javan I am not using webpack.

I am just using yarn. I did `yarn add lodash`, then I required it in application.js like:

```
require lodash
```

It throws up the error I mentioned above. If I remove the require everything works fine.

**Comment by javan** [comment]
Do you have other `require`s in your application.js? `require` won't work in a browser unless you use a module loader like webpack.

**Comment by javan** [comment]
Or is that a sprockets directive? (`//= require lodash`)

**Comment by ankitsinghaniyaz** [comment]
@javan right, it's the sprockets directive, sorry for skipping that.

**Comment by ankitsinghaniyaz** [comment]
Yes I have lot of other requires like:

`/= require vue/dist/vue`

All of them works fine.

**Comment by javan** [comment]
The error you're seeing is coming from lodash, not Action Cable. In a fresh app that only requires lodash, you'll see the same error. `//= require lodash/core` might work for you, but otherwise you'll need to use a module loader like webpack to properly load npm packages for the web. Check out https://github.com/rails/webpacker.
