### ISSUE TITLE
Routes Action / Methods as the block in place of key and value pairs

### ISSUE THREAD

**Issue by ashishprajapati** [rails/rails#28273]
### Proposed idea of the routes structure

Hello everyone,

I have did lots of research to implement these kind of routes structure those and I found it more relevant as per the developer perspectives. I have used get, post etc as the block so It's don't required to define the methods every time. 

Basically, there is no need to define get, post, delete, put methods every time when we are defining the routes. It's providing a great feasibility to define routes separately in there respective blocks like in get, post, put or delete.

I got this idea by seeing collection and member so as we are defining member and collection than why can't be use get and post etc in the same way. 

**Please everyone,  provide your points and suggestion over this proposed idea.**
**If everyone is fine than I can propose a robust solution for it**

### Idea specification for new routes structure

```ruby

resources :posts do
    collection do 
        get do 
          :path_a
          :path_b
          :path_c
        end
        post do
          :path_d
          :path_e
        end
        put do 
          :path_f
        end
    end

    member do
        get do 
          :path_g
          :path_h
        end

        post do
          :path_i
          :path_j
        end
    end
end

```

### Our current route structure:
```ruby
resources :posts do
    collection do 
        get :path_a
        get :path_b
        get :path_c
        post :path_d
        post :path_e
    end
end

resources :comments do
    collection do 
      get :path_a, :path_b, :path_c
      post :path_i, :path_j
    end
    member do 
      get :path_k, :path_l, :path_m
      post :path_n, :path_o
    end
end

```

### Idea to implement in this way

```ruby
resources :posts do
    collection do 
        get do 
          :path_a
          :path_b, to: :test_path_a
          :path_c
        end
        post do
          :path_d, to: :test_path_d
          :path_e
        end
    end
end
```

**Comment by al2o3cr** [comment]
Short of doing Lisp-macro-style AST manipulation, this isn't going to be implementable as written - this block of code:
```ruby
get do
  :path_a
  :path_b
end
```
returns `:path_b` if you run the block, but there's nowhere (AFAIK) that `:path_a` could be captured.
