### ISSUE TITLE
Incorrect SQL coloring

### ISSUE THREAD

**Issue by 9mm** [rails/rails#28277]
### Steps to reproduce

Create a custom SQL query which starts with `WITH ...`. I'm not sure if there's more keywords that trigger this behavior, but I do know `WITH` is one of them.

### Expected behavior

It should be colored the same as a custom query which starts with `SELECT ...`

### Actual behavior

The entire query remains pink (instead of blue)

### System configuration

**Rails version**: 5.0.2
**Ruby version**: 4.2.0

### Screenshots

![image](https://cloud.githubusercontent.com/assets/1386207/23575088/a9524864-0055-11e7-8d0f-71a60602ee37.png)

![image](https://cloud.githubusercontent.com/assets/1386207/23575092/b0b70414-0055-11e7-8c7d-701ed238bffd.png)

**Comment by matthewd** [comment]
I don't think we can practically do much about this. Choosing a hint colour based on the first word in the query isn't a problem, but fully parsing enough SQL (including various engines' differing [and configurable!] ideas on string quoting, for example) to correctly skip past the WITH and find the "true" operation is way too hard.

And we can't just treat `WITH` as implying `SELECT`: `INSERT`/`UPDATE`/`DELETE` can all be preceded by a `WITH` clause too.

**Comment by 9mm** [comment]
Ah, interesting. I was under the impression it was "dumb" and didn't do any parsing, just colored the entire query the same color (at least that's how it is in my console, there doesn't appear to be any variation in color within the actual query, after the opening `SQL (1.00ms)` line)

**Comment by matthewd** [comment]
Right: it does that by [looking at the first word in the query](https://github.com/rails/rails/blob/299728de1da404d789752156a13828ec3b48f3d6/activerecord/lib/active_record/log_subscriber.rb#L68-L87).

**Comment by 9mm** [comment]
Ahhhh that makes sense now. I totally didn't even notice queries were colored like that and I've used rails for years lol. Some details 😳😳😳

Sent from my iToaster

**Comment by vipulnsward** [comment]
Closing based on https://github.com/rails/rails/issues/28277#issuecomment-284131883 

Thanks for reporting!
