### ISSUE TITLE
Inconsistent behavior between save and save! when unsetting object.id on a new record

### ISSUE THREAD

**Issue by wallyaltman** [rails/rails#28274]
If you make a new model object `foo` and manually set `foo.id` to a value that's already in use, then call `foo.save` or `foo.save!`, you'll get an `ActiveRecord::RecordNotUnique` error (as expected).

However, if you then set `foo.id = nil` and call `foo.save!`, you'll get _another_ `ActiveRecord::RecordNotUnique` error. The SQL statements will show that Rails still uses the `id` from before.

On the other hand, if you set `foo.id = nil` and call `foo.save`, the record is saved with an automatically assigned `id` as expected.

Test case:

```ruby
begin
  require "bundler/inline"
rescue LoadError => e
  $stderr.puts "Bundler version 1.10 or later is required. Please update your Bundler"
  raise e
end

gemfile(true) do
  source "https://rubygems.org"
  gem "rails", '5.0.2'
  gem "sqlite3"
end

require "active_record"
require "minitest/autorun"
require "logger"

# This connection will do for database-independent bug reports.
ActiveRecord::Base.establish_connection(adapter: "sqlite3", database: ":memory:")
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do

  create_table "foos", force: :cascade do |t|
    t.string "name"
  end

end

class Foo < ActiveRecord::Base
end

class BugTest < Minitest::Test
  def test_save_with_duplicate_id
    foo = Foo.create(name: "Original")
    dup_foo = Foo.new(name: "Duplicate", id: foo.id)

    assert_raises ActiveRecord::RecordNotUnique do
      dup_foo.save
    end

    dup_foo.id = nil

    assert_nil dup_foo.id

    dup_foo.save

    refute_equal dup_foo.id, foo.id
  end

  def test_save_bang_with_duplicate_id
    foo = Foo.create(name: "Original")
    dup_foo = Foo.new(name: "Duplicate", id: foo.id)

    assert_raises ActiveRecord::RecordNotUnique do
      dup_foo.save!
    end

    dup_foo.id = nil

    assert_nil dup_foo.id

    dup_foo.save!                    # Exception happens here

    refute_equal dup_foo.id, foo.id  # If the second exception is rescued, this assertion fails.
  end
end
```

The first test passes, but the second one fails.

This behavior happens on Rails 5.0.2 and on 5.1.0.beta1.

**Comment by tejasbubane** [comment]
I found the issue to originate somewhere between `4.2.2` and `4.2.3`.

| version | test case |
| ------------- |:-------------:|
|   5.0.2 | fail   |
|   5.0.1 | fail   |
|   4.2.5 | fail   |
|   4.2.3 | fail   |
|   4.2.2 | pass   |
|   4.2.0 | pass   |
|  4.1.16 | pass   |

I tried to `git bisect` but could not, since I came across some unrelated errors in the process.

**Comment by eugeneius** [comment]
I bisected between v4.2.2 and v4.2.3 (thanks @tejasbubane!) and the test started to fail at https://github.com/rails/rails/commit/ec712fb4ca5289a22872eabf32c74459a304115d.

However after investigating further, I think that commit just surfaced an existing problem. Accessing a record's primary key is supposed to first update its state to reflect any rolled back transactions; before that commit they were just being ignored, but now the record's previous state was being restored _after_ the test set the `id` to nil.

Using this simplified test case, I traced that behaviour all the way back to 67d8bb963d5d51fc644d6b1ca20164efb4cee6d7:

```ruby
begin
  require "bundler/inline"
rescue LoadError => e
  $stderr.puts "Bundler version 1.10 or later is required. Please update your Bundler"
  raise e
end

gemfile(true) do
  source "https://rubygems.org"
  gem "rails", path: "."
  gem "sqlite3"
end

require "active_record"
require "minitest/autorun"

ActiveRecord::Base.establish_connection(adapter: "sqlite3", database: ":memory:")

ActiveRecord::Schema.define do
  create_table :foos
end

class Foo < ActiveRecord::Base
end

class BugTest < MiniTest::Unit::TestCase
  def test_restore_id_after_rollback
    foo = Foo.new

    Foo.transaction do
      foo.save!
      raise ActiveRecord::Rollback
    end

    assert_nil foo.id
  end
end

```

I've opened https://github.com/rails/rails/pull/28395 with a proposed fix.

**Comment by eugeneius** [comment]
Calling `save` instead of `save!` works because [this line](https://github.com/rails/rails/blob/097612e8f5bc520bbcdd3c9134a3421eac4d624a/activerecord/lib/active_record/transactions.rb#L322) clobbers the previous transaction state without applying it; https://github.com/rails/rails/pull/28302 extends that behaviour to `save!`, but it seems more like a bug that happens to fix this problem to me.
