### ISSUE TITLE
Question about description and code in Active Record Query Interface of RailsGuide

### ISSUE THREAD

**Issue by jun68ykt** [rails/rails#28278]
Hello.
Now I read the Rails Guide for using Rails more effectively  and I post about a unclear description which I found in it.

### Steps to reproduce

&nbsp;In the  section [17.1 Retrieving filtered data from multiple tables](http://guides.rubyonrails.org/active_record_querying.html#retrieving-filtered-data-from-multiple-tables) of the chapter [17 Understanding The Method Chaining](http://guides.rubyonrails.org/active_record_querying.html#understanding-the-method-chaining) of [Active Record Query Interface](http://guides.rubyonrails.org/active_record_querying.html),  following code and description are written:

<hr />

**17.1 Retrieving filtered data from multiple tables**

```ruby
Person
  .select('people.id, people.name, comments.text')
  .joins(:comments)
  .where('comments.created_at > ?', 1.week.ago)
```

The result should be something like this:

```sql
SELECT people.id, people.name, comments.text
FROM people
INNER JOIN comments
  ON comments.person_id = people.id
WHERE comments.created_at = '2015-01-01'
```

<hr />

### Expected behavior

&nbsp;I think that ActiveRecord’s `where` method part above
```ruby 
 .where('comments.created_at > ?', 1.week.ago)
```
can not generate WHERE clause of SQL above
```sql
WHERE comments.created_at = '2015-01-01'
```
in Rails Guide , but e.g. like
```sql
WHERE (shops.created_at > '2017-02-25 05:06:29.919421’) 
```
may be generated.

How about this issue ?

This post is the first time in which I submit new issue.
Best regards.

**Comment by kamipo** [comment]
Yeah, the result is incorrect. Can you create a PR that fixes the result (`[ci skip]` contained in the commit message)?

**Comment by vipulnsward** [comment]
Fixed in https://github.com/rails/docrails/commit/c0f621ae63b048c02a1c8341a7c093e8a76c0e7e

Thanks!

**Comment by jun68ykt** [comment]
@kamipo @vipulnsward Thank you for your answers ! I send PR, but is this issue done ? Anyway I'm glad the unclarified issue was solved.
