### ISSUE TITLE
Rails 5.1: erb generator methods got private and break other gems

### ISSUE THREAD

**Issue by januszm** [rails/rails#28275]
In this commit:

```ruby
commit d1daf4c31301f5f5917b877fd63a817f5f4608ed
Author: Akira Matsuda <ronnie@dio.jp>
Date:   Fri Dec 23 19:20:01 2016 +0900

    Privatize unneededly protected methods in Railties

diff --git a/railties/lib/rails/generators/erb.rb b/railties/lib/rails/generators/erb.rb
index d015020..d5e326d 100644
--- a/railties/lib/rails/generators/erb.rb
+++ b/railties/lib/rails/generators/erb.rb
@@ -3,7 +3,7 @@
 module Erb # :nodoc:
   module Generators # :nodoc:
     class Base < Rails::Generators::NamedBase #:nodoc:
-      protected
+      private
 
         def formats
           [format]
```

several methods, including `format` were  changed to `private` from `protected`. Because of that they are no longer accessible in subclasses and cause troubles in other gems/generators that inherit from ERB

See: https://github.com/slim-template/slim-rails/issues/139

**Comment by januszm** [comment]
cc: @amatsuda

**Comment by amatsuda** [comment]
Aww, thank you for reporting this.
It's not really related to subclassing (note that `protected` in Ruby is different from that in Java). The essential problem lies in `self.format` call [here](https://github.com/rails/rails/blob/64b797dee1c268da1b7e9a1e82b2599b54c0ed5a/railties/lib/rails/generators/erb.rb#L20).
Here's a shorter code that reproducing the problem.

```ruby
class A
  private def x() :x; end

  def foo(x = self.x)
    p x
  end
end

A.new.foo
#=> 28275.rb:4:in `foo': private method `x' called for #<A:0x007f9673944858> (NoMethodError)
```
