### ISSUE TITLE
Remove new_framework_defaults.rb from newly generated apps

### ISSUE THREAD

**Issue by robin850** [rails/rails#28291]
Hello,

I take the liberty to open this ticket to discuss about the future of the `new_framework_defaults.rb` file. We've discussed about that with @matthewd and came to the conclusion that this file shouldn't be generated as it is done at the moment.

Actually, it would be easier to generate a file on a version basis like `new_framework_defaults_51.rb` with only the new defaults for this version.

An important thing to consider with this approach though is that this file takes precedence over any file stored under `config/environments` and may take precedence over certain initializers since they are alphabetically required (AFAIK). So if people want to opt out from the default, we should maybe require initializers that match `new_framework_default_*.rb` first.

By the way, since 5.0, it looks like only [this option](https://github.com/rails/rails/blob/893035782d427b1fea3d1299417b507220752c3e/railties/lib/rails/generators/rails/app/templates/config/initializers/new_framework_defaults.rb.tt#L38) has been changed and [this one](https://github.com/rails/rails/commit/70e8fed5a36484ea602c318be74079b58dc543d0) has been removed.

To-do:

* No longer generate this file for new 5.1 applications so properly set the configuration settings in the appropriate configuration files.
* During the upgrade process (i.e. running `bin/rails app:upgrade`), generate a file tied to the current version with the new settings.

Have a nice day !

**Comment by eugeneius** [comment]
I agree that generating this file for new applications doesn't make much sense. 👍 

Two thoughts:

If we're going to add special behaviour and override the normal initializer load order, I don't think the file belongs in `config/initializers/` any more. Maybe just `config/new_framework_defaults_51.rb`?

The workflow encouraged by this file is to keep as much of the previous version's behaviour as possible when upgrading, and then later adopt the new settings one by one. If we're going to generate a new file for every version, presumably they should be deleted when all of the options have been switched. If a user is running the task to upgrade to Rails 5.1 and they still have the 5.0 file in place, should we warn them that they should "finish" upgrading to Rails 5.0 first?

**Comment by robin850** [comment]
> If we're going to generate a new file for every version, presumably they should be deleted when all of the options have been switched.

That was raised during our discussion with Matthew and to quote him:

> We generate the file, as a helpful guide *if* they want to adopt the new settings, that's all we care about; we don't need to touch it again
> [...]
> It's about ensuring their app will just continue to work without intervention, for the foreseeable future

**Comment by matthewd** [comment]
I don't think we need to affect the order: the file only exists to give upgrading people hints of what settings they might want to consider changing. If they have some interdependency that complicates that, it seems fine to leave them to relocate the setting to an earlier file[name].

**Comment by matthewd** [comment]
And yeah, we only care about encouraging people to adopt the "new" value if, for some particular reason, we want to deprecate the setting -- but that goes through the normal deprecation flow, and would probably [hopefully] occur in some further future version.. not necessarily the very next after the default changed.
