### ISSUE TITLE
Rails 4.2.2 vs Rails 5.0.2 JSON Storage with PG

### ISSUE THREAD

**Issue by kengreeff** [rails/rails#28292]
After updating our app from Rails 4.2.2 to Rails 5 we have noticed that JSON strings are being stored as a string rather than a Hash or Array.

Is there a way we can reproduce the behaviour in Rails 5?

### Steps to reproduce
1. Create Model
`bundle exec rails g model OrderItem options:json`

2. Run migration
`bundle exec rake db:migrate`

3. Open Console
`bundle exec rails c`

4. In Console (Rails 4.2.2)
```
item = OrderItem.new(options: "{\"key\":\"value\"}")
 => #<OrderItem id: nil, options: {"key"=>"value"}>

item.options
 => {"key"=>"value"} 

item.options.is_a?(String)
 => false 

item.options.is_a?(Hash)
 => true
```

5. In Console (Rails 5.0.2)
```
item = OrderItem.new(options: "{\"key\":\"value\"}")
 => #<OrderItem id: nil, options: "{\"key\":\"value\"}">

item.options
 => "{\"key\":\"value\"}"

item.options.is_a?(String)
 => true 

item.options.is_a?(Hash)
 => false
```

### Expected behavior
The options attribute should return a hash

### Actual behavior
The options attribute returns a string

### System configuration
**Rails version**: 5.0.2
**Ruby version**: ruby 2.3.1p112
**PostgreSQL**: 9.4.5

**Comment by Erol** [comment]
Similar issue to #28285.

**Comment by kamipo** [comment]
This behavior is because efaa6e4f79d457c2cdd08cbc56d63bc972a6993c to fix the issue #24234.
Please use `OrderItem.new(options: JSON.parse("{\"key\":\"value\"}"))`.

**Comment by maclover7** [comment]
Closing in favor of #28285 to keep similar bug reports in one place.

**Comment by kengreeff** [comment]
Awesome, thank you. I did see issue #28285 but wasn't sure if that only applied to jsonb columns and that it corrected after calling `reload`.

@kamipo Will this be the new behaviour going forward or only a temporary fix? I have overwritten the setter methods in my model to check for the JSON string then parse if required for the time being.

**Comment by kamipo** [comment]
JSON RFC was updated from RFC 4627 to RFC 7159.

https://www.ietf.org/rfc/rfc4627.txt
http://rfc7159.net/rfc7159

Previously `JSON-text = object / array`, but now `value = false / null / true / object / array / number / string`.
The new behaviour respects RFC 7159.

**Comment by kengreeff** [comment]
Do you think this would be worth adding to the upgrade guides (4.2 -> 5) as the behaviour has changed?

**Comment by kamipo** [comment]
Actually the breaking change was noted in CHANGELOG.md ("Properly accept all valid JSON primitives in the JSON data type.") as a minor breaking change. But adding the guides looks fine to me. Feel free to create a PR.

**Comment by kengreeff** [comment]
Ok, working on the below.

### JSON/JSONB Columns

Rails 5 has been updated to comply with RFC 7159. JSON strings e.g. JSON.stringify() from Javascript are now saved as strings rather than a Hash/Array. To maintain the behaviour from previous versions of Rails you need to parse the JSON string before assigning:
  
    Model.payload = JSON.parse("{\"key\":\"value\"}")

Do you think it is worth mentioning overriding the setter method in the model for the column to keep code DRY?

```
def payload=(value)
  self[:payload] = value.is_a?(String) ? JSON.parse(value) : value
end
```

**Comment by jwg2s** [comment]
We made a quick concern to handle the upgrade a little more gracefully:

```ruby
module JsonAttrParser
  extend ActiveSupport::Concern

  included do
    columns.select { |column| column.type == :json }.map(&:name).each do |attr|
      define_method("#{attr}=") do |value|
        self[attr] = value.is_a?(String) ? JSON.parse(value) : value
      end
    end
  end
end
```
