### ISSUE TITLE
`rails new -C` generates and then removes actioncable-related files

### ISSUE THREAD

**Issue by ajm188** [rails/rails#28298]
### Steps to reproduce

`rails new myapp -C`

### Expected behavior

Files/directories such as app/channels, app/assets/javascript/cable.js, config/cable.yml should never exist

### Actual behavior

Files/directories such as app/channels, app/assets/javascript/cable.js, config/cable.yml are generated and then removed in a later step.

### System configuration
**Rails version**: 5.0.1

**Ruby version**: 2.3.1

### Other

I'm happy to work on this, provided someone isn't already tackling it.

**Comment by rafaelfranca** [comment]
Thank you for the issue. That is true and it is by design. The application template already have all those files in the same way that has all active record related files. The options only have effect after the template is copied so we can't selectely avoid coping some files
