### ISSUE TITLE
BUG rails new  "PLEASE HELP ME :("

### ISSUE THREAD

**Issue by Ingosmar89219** [rails/rails#28300]
noeblack@garyhost:~$ rails new sistema
/home/noeblack/.rvm/rubies/ruby-2.3.0/lib/ruby/site_ruby/2.3.0/rubygems/specification.rb:2278:in `check_version_conflict': can't activate activesupport-5.0.2, already activated activesupport-5.0.1 (Gem::LoadError)
	from /home/noeblack/.rvm/rubies/ruby-2.3.0/lib/ruby/site_ruby/2.3.0/rubygems/specification.rb:1404:in `activate'
	from /home/noeblack/.rvm/rubies/ruby-2.3.0/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:89:in `block in require'
	from /home/noeblack/.rvm/rubies/ruby-2.3.0/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:88:in `each'
	from /home/noeblack/.rvm/rubies/ruby-2.3.0/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:88:in `require'
	from /home/noeblack/.rvm/gems/ruby-2.3.0/gems/concurrent-ruby-1.0.5/lib/concurrent.rb:15:in `<top (required)>'
	from /home/noeblack/.rvm/rubies/ruby-2.3.0/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:68:in `require'
	from /home/noeblack/.rvm/rubies/ruby-2.3.0/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:68:in `require'
	from /home/noeblack/.rvm/gems/ruby-2.3.0/gems/activesupport-5.0.1/lib/active_support/logger_silence.rb:3:in `<top (required)>'
	from /home/noeblack/.rvm/rubies/ruby-2.3.0/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:68:in `require'
	from /home/noeblack/.rvm/rubies/ruby-2.3.0/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:68:in `require'
	from /home/noeblack/.rvm/gems/ruby-2.3.0/gems/activesupport-5.0.1/lib/active_support/logger.rb:1:in `<top (required)>'
	from /home/noeblack/.rvm/rubies/ruby-2.3.0/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:68:in `require'
	from /home/noeblack/.rvm/rubies/ruby-2.3.0/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:68:in `require'
	from /home/noeblack/.rvm/gems/ruby-2.3.0/gems/activesupport-5.0.1/lib/active_support.rb:27:in `<top (required)>'
	from /home/noeblack/.rvm/rubies/ruby-2.3.0/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:68:in `require'
	from /home/noeblack/.rvm/rubies/ruby-2.3.0/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:68:in `require'
	from /home/noeblack/.rvm/gems/ruby-2.3.0/gems/railties-5.0.1/lib/rails/generators.rb:6:in `<top (required)>'
	from /home/noeblack/.rvm/rubies/ruby-2.3.0/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:68:in `require'
	from /home/noeblack/.rvm/rubies/ruby-2.3.0/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:68:in `require'
	from /home/noeblack/.rvm/gems/ruby-2.3.0/gems/railties-5.0.1/lib/rails/commands/application.rb:1:in `<top (required)>'
	from /home/noeblack/.rvm/rubies/ruby-2.3.0/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:68:in `require'
	from /home/noeblack/.rvm/rubies/ruby-2.3.0/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:68:in `require'
	from /home/noeblack/.rvm/gems/ruby-2.3.0/gems/railties-5.0.1/lib/rails/cli.rb:14:in `<top (required)>'
	from /home/noeblack/.rvm/rubies/ruby-2.3.0/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:68:in `require'
	from /home/noeblack/.rvm/rubies/ruby-2.3.0/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:68:in `require'
	from /home/noeblack/.rvm/gems/ruby-2.3.0/gems/railties-5.0.1/exe/rails:9:in `<top (required)>'
	from /home/noeblack/.rvm/gems/ruby-2.3.0/bin/rails:23:in `load'
	from /home/noeblack/.rvm/gems/ruby-2.3.0/bin/rails:23:in `<main>'
	from /home/noeblack/.rvm/gems/ruby-2.3.0/bin/ruby_executable_hooks:15:in `eval'
	from /home/noeblack/.rvm/gems/ruby-2.3.0/bin/ruby_executable_hooks:15:in `<main>'

**Comment by kamipo** [comment]
This looks rvm issue. Not a Rails bug.

**Comment by laertispappas** [comment]
You need to pass bundle exec rails new projectname

**Comment by michaelmakun** [comment]
it seems the issue of rails.    You can try "gem install rails" on iterm

**Comment by kamipo** [comment]
```
% gem install rails
Fetching: activesupport-5.0.2.gem (100%)
Successfully installed activesupport-5.0.2
Fetching: actionview-5.0.2.gem (100%)
Successfully installed actionview-5.0.2
Fetching: actionpack-5.0.2.gem (100%)
Successfully installed actionpack-5.0.2
Fetching: activemodel-5.0.2.gem (100%)
Successfully installed activemodel-5.0.2
Fetching: activerecord-5.0.2.gem (100%)
Successfully installed activerecord-5.0.2
Fetching: activejob-5.0.2.gem (100%)
Successfully installed activejob-5.0.2
Fetching: actionmailer-5.0.2.gem (100%)
Successfully installed actionmailer-5.0.2
Fetching: actioncable-5.0.2.gem (100%)
Successfully installed actioncable-5.0.2
Fetching: railties-5.0.2.gem (100%)
Successfully installed railties-5.0.2
Fetching: rails-5.0.2.gem (100%)
Successfully installed rails-5.0.2
10 gems installed

% rails new sistema
Using -T --skip-bundle from /Users/kamipo/.railsrc
      create  
      create  README.md
      create  Rakefile
      create  config.ru
      create  .gitignore
      create  Gemfile
      create  app
      create  app/assets/config/manifest.js
      create  app/assets/javascripts/application.js
      create  app/assets/javascripts/cable.js
      create  app/assets/stylesheets/application.css
      create  app/channels/application_cable/channel.rb
      create  app/channels/application_cable/connection.rb
      create  app/controllers/application_controller.rb
      create  app/helpers/application_helper.rb
      create  app/jobs/application_job.rb
      create  app/mailers/application_mailer.rb
      create  app/models/application_record.rb
      create  app/views/layouts/application.html.erb
      create  app/views/layouts/mailer.html.erb
      create  app/views/layouts/mailer.text.erb
      create  app/assets/images/.keep
      create  app/assets/javascripts/channels
      create  app/assets/javascripts/channels/.keep
      create  app/controllers/concerns/.keep
      create  app/models/concerns/.keep
      create  bin
      create  bin/bundle
      create  bin/rails
      create  bin/rake
      create  bin/setup
      create  bin/update
      create  config
      create  config/routes.rb
      create  config/application.rb
      create  config/environment.rb
      create  config/secrets.yml
      create  config/cable.yml
      create  config/puma.rb
      create  config/spring.rb
      create  config/environments
      create  config/environments/development.rb
      create  config/environments/production.rb
      create  config/environments/test.rb
      create  config/initializers
      create  config/initializers/application_controller_renderer.rb
      create  config/initializers/assets.rb
      create  config/initializers/backtrace_silencers.rb
      create  config/initializers/cookies_serializer.rb
      create  config/initializers/cors.rb
      create  config/initializers/filter_parameter_logging.rb
      create  config/initializers/inflections.rb
      create  config/initializers/mime_types.rb
      create  config/initializers/new_framework_defaults.rb
      create  config/initializers/session_store.rb
      create  config/initializers/wrap_parameters.rb
      create  config/locales
      create  config/locales/en.yml
      create  config/boot.rb
      create  config/database.yml
      create  db
      create  db/seeds.rb
      create  lib
      create  lib/tasks
      create  lib/tasks/.keep
      create  lib/assets
      create  lib/assets/.keep
      create  log
      create  log/.keep
      create  public
      create  public/404.html
      create  public/422.html
      create  public/500.html
      create  public/apple-touch-icon-precomposed.png
      create  public/apple-touch-icon.png
      create  public/favicon.ico
      create  public/robots.txt
      create  tmp
      create  tmp/.keep
      create  tmp/cache
      create  tmp/cache/assets
      create  vendor/assets/javascripts
      create  vendor/assets/javascripts/.keep
      create  vendor/assets/stylesheets
      create  vendor/assets/stylesheets/.keep
      remove  config/initializers/cors.rb
```

**Comment by girishso** [comment]
@Ingosmar89219  Try this

`ruby -rbundler/inline -e "gemfile(true) do; source 'https://rubygems.org/'; gem 'rails', '5.0.2'; end" bundle exec rails new taggable`

**Comment by kangkyu** [comment]
http://railspro.net/questions/293
```
gem cleanup
gem uninstall rails
gem uninstall activesupport
gem uninstall railties
```
and then 
```
gem install rails -v 5.0.1
gem install rails -v 5.0.2
```
and it worked!
