### ISSUE TITLE
Rails 5 Changes Lookup Order of Virtual SQL Attributes

### ISSUE THREAD

**Issue by tgturner** [rails/rails#28314]
### Steps to reproduce

Given an ActiveRecord model, `WidgetMaker` that looks like the following 
```ruby
class WidgetMaker < ActiveRecord::Base
  belongs_to :publisher
end
```
when I create a SQL statement like the following,

```ruby
suspended_widget_maker = WidgetMaker.select("widget_makers.id, widget_makers.name AS publisher")
                                    .where("widget_type IS NOT NULL")
```

Attempting to call `suspended_widget_maker.first.publisher` will attempt to call the association method, not the virtual attribute. Under Rails 4.2.7 it calls the virtual attribute first.

I could not find anything in the release notes relating to this change.

### Expected behavior
Calling `.publisher` on an instance returned by this SQL statement will attempt to call the virtual attribute first.

### Actual behavior
Calling `.publisher` on an instance returned by this SQL statement attempts to call the association method first. This is a regression from Rails 4.2.7

### System configuration
**Rails version**: 5.0.1

**Ruby version**: 2.2.3

**Comment by chrisarcand** [comment]
We ran in to something similar. The change you're looking for is in https://github.com/rails/rails/commit/3e37a8b9e84a9dd532485ee7945c9d053b9f9d86

Our solution in our particular case may or may not help you as well:  https://github.com/ManageIQ/manageiq/pull/13302/commits/28a71e9facb0f2ddd4189f47cf02d47795b681ad

I don't believe we had time to see about fixing this upstream.

**Comment by tgturner** [comment]
@chrisarcand Thanks for your help! Unless I'm looking at your code incorrectly, I don't think this addresses my issue. I might have named the issue wrong, but I'm having problems specifically with virtual columns derived from SQL select statements. From what I can tell, the issue that you linked to is in regards to the new attributes API in Rails 5. Am I correct on this? If not please feel free to explain further.

I hope someone can offer more clarity on this issue.

**Comment by NickLaMuro** [comment]
@chrisarcand that fix was specifically a Rails 5.0.0.1 to Rails 5.0.1 fix, and I believe that @tgturner is going from 4.2.7 to 5.0.1 if I am not mistaken.  Unless this issue does not present itself when using `"rails", "<= 5.0.1"`, I think our issue and this is a separate issue entirely.

**Comment by chrisarcand** [comment]
Hmm I guess I would have figured that the issue would manifest going from any version to 5.0.1. ¯\\\_(ツ)_/¯

**Comment by maclover7** [comment]
@tgturner Are you sure in Rails v4.2.7 virtual SQL attributes have precedence over associations? Using [this reproduction script](https://gist.github.com/maclover7/03ddb446f336f44fc130400ceb6b42f8), it's showing that the `publisher` method is declared as an associations reader.

Can you create an executable test script using one of the templates [here](https://github.com/rails/rails/tree/master/guides/bug_report_templates), that would demonstrate the problem you are seeing?

**Comment by tgturner** [comment]
@maclover7 after diving a bit deeper into the issue it looks like the issue resides here.

https://github.com/rails/rails/blob/master/activerecord/lib/active_record/associations/belongs_to_association.rb#L102

In Rails 4.2, no block was passed to `_read_attribute` so an error was never thrown, and even though the virtual SQL attribute didn't have precedence, it would eventually get called. In Rails 5, that doesn't have the opportunity to happen because of the missing_attribute error being thrown when _read_attribute can't find anything because of the missing foreign_key.
