### ISSUE TITLE
Titleize doesn't capitalize first word in sub-string

### ISSUE THREAD

**Issue by zinosama** [rails/rails#28312]
### Steps to reproduce

> str = "i said 'the first word should be cap'."
=> "i said 'the first word should be cap'."
> str.titleize
=> "I Said 'the First Word Should Be Cap'."

### Expected behavior
"I Said 'The First Word Should Be Cap'."

### Actual behavior
"I Said 'the First Word Should Be Cap'."

### System configuration
**Rails version**: 5.0.1

**Ruby version**: 2.3.3

It seems like [this](https://github.com/rails/rails/commit/4b685aad7b5edeb087968c42f815be2bec14b822) is the commit that introduced this behavior - the lookbehind operator added in the PR doesn't match any character behind a single quotation mark, even when there's whitespace before that quotation mark.
 
I'm no expert in regex, but I can create a PR to revert to the previous behavior and add a test case for this.

**Comment by pixeltrix** [comment]
@zinosama since this behaviour has been around since 2012 I don't want to simply revert - we should try to fix this.

**Comment by matthewd** [comment]
Looks like ```/\b(?<!\b['’`])[a-z]/``` might do it

**Comment by pixeltrix** [comment]
@matthewd hmm, I went with `/\b(?<!\w['’`])[a-z]/` - any issues you can see with that?

**Comment by matthewd** [comment]
Nope; as this is already zero-width, they should be identical 👍🏻
