### ISSUE TITLE
In development, RAILS_MASTER_KEY is not read from the environment variable

### ISSUE THREAD

**Issue by sevos** [rails/rails#28310]
### Steps to reproduce

1. add `config.read_encrypted_secrets = true` to `config/environments/development.rb`
2. `$ export RAILS_MASTER_KEY=$(cat config/secrets.yml.key)`
3. `$ mv config/secrets.yml.key config/secrets.yml.key.bak`
4. `$ bundle exec rails g`
5. `mv config/secrets.yml.key.bak config/secrets.yml.key`
6. `$ bundle exec rails g`

### Expected behavior
Both `rails g` executions should show the Rails generator help entry.

### Actual behavior
The first execution raises the following exception:

```
$ bundle exec rails g                                       rbenv:2.3.3
/Users/sevos/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/railties-5.1.0.beta1/lib/rails/secrets.rb:71:in `handle_missing_key': Missing encryption key to decrypt secrets with. Ask your team for your master key and put it in ENV["RAILS_MASTER_KEY"]
```

The second execution works as expected.

### System configuration
**Rails version**: 5.1.0.beta1

**Ruby version**: 2.3.3

**Comment by pixeltrix** [comment]
@sevos is this true for master as well? The handling of `RAILS_MASTER_KEY` seems pretty straightforward in the code.

**Comment by sevos** [comment]
I just did the exercise: I succeeded to reproduce it on beta1, but not on master.

[The changes](https://github.com/rails/rails/compare/v5.1.0.beta1...master) also do not explain why it's not the case anymore.

**Comment by pixeltrix** [comment]
> The changes also do not explain why it's not the case anymore.

Yeah, I can't explain it either - will try to reproduce locally.

**Comment by kaspth** [comment]
Can't seem to reproduce it on master either, lets consider this closed then. Thanks for the report!
