### ISSUE TITLE
AR 5.0.2 migrations invokes Rails.application which breaks for non-rails apps

### ISSUE THREAD

**Issue by ioquatix** [rails/rails#28325]
AR 5.0.2

https://github.com/rails/rails/blob/20107ff6c80a7e162adf22176eee811a59498126/activerecord/lib/rails/generators/active_record/migration.rb#L24-L30

Perhaps it should be

```ruby
if defined?(Rails) and Rails.respond_to?(:application) and Rails.application
```

**Comment by ioquatix** [comment]
So, this was what was used in 5.0.1

https://github.com/rails/rails/blob/26b7f9b47b6fb8357d3c0b48351fc03e610d9d5c/activerecord/lib/active_record/tasks/database_tasks.rb#L82-L84

Now the code is in two places, and broken for users who don't use AR migrations with Rails.

**Comment by ioquatix** [comment]
Here is the PR which made the change, not sure why it causes a problem, since it's just refactoring existing stuff

https://github.com/rails/rails/commit/b8c34d1a09a5584497cbc9916ce2704288fe1420

**Comment by ioquatix** [comment]
Okay, here is the PR that broke the behaviour:

https://github.com/rails/rails/commit/c942361a601b9486967ab45bdc3d2d0ce926977f

Because previously it didn't depend on Rails.config and the test didn't check for that, this could use some work.  @kjg

**Comment by ioquatix** [comment]
I think the real issue here is leaking global state from Rails into something that should really be AR specific.

**Comment by ioquatix** [comment]
Here is how I was invoking the generator:

```ruby
			require "rails/generators"
			
			parameters = [name] + options
			Rails::Generators.invoke "active_record:migration", parameters, :destination_root => ActiveRecord::Migrations.root
```

**Comment by ioquatix** [comment]
Here is how I had to work around the issue.

https://github.com/ioquatix/activerecord-migrations/commit/a360e3ff6bf230dc42014e34810edfa1bbbfd2bc

**Comment by pixeltrix** [comment]
@ioquatix are you saying that c942361 broke it because it checks for `Rails.application` and not `Rails.application.config` ?

**Comment by ioquatix** [comment]
@pixeltrix Rails.application doesn't exist, it's a no method error.

**Comment by ioquatix** [comment]
I think this is ultimately a good change, it just probably wasn't suitable in some ways for a patch release. I finally got it working by https://github.com/ioquatix/activerecord-migrations/commit/c297b3d1a4e537f2c6acd6f4ab4cfdfa1463abba which is probably better overall.

My original assertion that AR contains too much Rails specific code is still valid IMHO.

**Comment by pixeltrix** [comment]
@ioquatix I have a simple fix - we just check for `defined?(Rails.application)` before calling it.

> My original assertion that AR contains too much Rails specific code is still valid IMHO.

Glue code has to live somewhere - the `Rails::Railtie` class and friends provide a mechanism for other libraries to integrate with Rails without Rails itself having to know about those libraries, we just messed up a `defined?` check.

**Comment by pixeltrix** [comment]
@ioquatix I've backported to 5-0-stable in bd66fb8 if you want to test against it.

**Comment by ioquatix** [comment]
@pixeltrix Thanks for looking into this.

w.r.t glue code, I feel the flow is wrong. Given how things are designed, it would make more sense for there to be an interface for providing configuration to ActiveRecord, and Rails can install it's own global state into ActiveRecord via the interface. That way, other systems could also install their own configuration. I thought this was mostly the purpose of ActiveRecord's `DatabaseTasks` module/class hybrid.
