### ISSUE TITLE
NilClass.to_query(key) does not round-trip with Rack::Utils.parse_nested_query

### ISSUE THREAD

**Issue by md5** [rails/rails#28322]
### Steps to reproduce

It should ideally be possible to round-trip from a `Hash` or `ActionController::Parameters` object to a query string and back. Currently, this does not work when the value is `nil`, in which case the value round-trips to `''` instead of `nil`.

See this gist: https://gist.github.com/md5/be5d072bb2c853baf2143dd5faba69cb

### Expected behavior
Having a `nil` value in the parameters hash should result in a key with no value in the query string.

### Actual behavior
Currently, a `nil` value results in the same query string as a blank string, namely `key=`.

### System configuration
**Rails version**: Any

**Ruby version**: Any

**Comment by al2o3cr** [comment]
The HTML spec which defines `application/x-www-form-urlencoded` allows the omission of `=` but specifies the value when no `=` sign is found in the pair should be the empty string (last sentence of step 1):

http://www.w3.org/TR/html5/forms.html#application/x-www-form-urlencoded-decoding-algorithm

The stdlib has a similar corner-case:
```ruby
URI.encode_www_form([['foo', nil]]) # => "foo"
URI.encode_www_form([['foo', '']]) # => "foo="
# BUT
URI.decode_www_form(URI.encode_www_form([['foo', nil]])) # => [['foo', '']]
```

**Comment by md5** [comment]
@al2o3cr Thanks for the reference. I guess if we're looking to distinguish between `nil` and `''`, we're either out of luck or we need to go against the spec.

That being said, it looks like this is an addition to the HTML5 spec that wasn't specified in previous versions (as far as I was able to find). It was added in whatwg/html@9178f8b3f491c3a37a5782fb3c11825326c8ab5f in August 2011. It was also later removed in whatwg/html@0fef169e6fca7433e3aac2a3640b4665b791ff8e in February 2016 in preference to the WHATWG URL spec, where it was first added in https://github.com/whatwg/url/commit/e977c3cebdc36a455b86ec43c46e4a56213d1cc6 (cf. https://url.spec.whatwg.org/#urlencoded-parsing).

I'm fine with this being closed if it's a "won't fix".

**Comment by md5** [comment]
I was thinking about this a bit more and it seems like the referenced section of the HTML5 spec more properly governs the behavior of `Rack::Utils.parse_nested_query` and `URI. decode_www_form`, since the section is about parsing query strings, not producing them. Assuming that's the case, it's actually the behavior of those two methods that go against the spec, not my proposed change to `NilClass.to_query(key)`.
