### ISSUE TITLE
Routes constraints defined in a single route is being applied for Rack blocks too

### ISSUE THREAD

**Issue by lucasas** [rails/rails#28331]
### Steps to reproduce

Declaring a route pointing to a `Rack` block and declaring a `Rails Route` pointing to a controller with a `constraint`:

```ruby
MySite::Application.routes.draw do
  get "/test", to: ->(env) { [ 200, {"Content-Type" => "text/html"}, "any response" ] }

  get "/another_test", to: "pets#another_test"

  get "/*id",
    to: "pets#show",
    constraints: { id: /some-regex-here/ }
end
```

### Expected behavior
The `constraint` declared must be applied only for `get "/*id"` route

### Actual behavior
The given `constraint` is applied for `rack` action. The same does not happen for the second route `get "/another_routes"`

### System configuration
**Rails version**: 4.2.7.1

**Ruby version**: 2.3.3

**Comment by pixeltrix** [comment]
@lucasas I can't reproduce this - can you get it to fail in a similar fashion to how you're seeing failures:

``` ruby
begin
  require "bundler/inline"
rescue LoadError => e
  $stderr.puts "Bundler version 1.10 or later is required. Please update your Bundler"
  raise e
end

gemfile(true) do
  source "https://rubygems.org"
  gem "rails", "4.2.8"
end

require "rack/test"
require "action_controller/railtie"

class TestApp < Rails::Application
  config.action_dispatch.show_exceptions = false

  config.root = File.dirname(__FILE__)
  config.session_store :cookie_store, key: "cookie_store_key"
  secrets.secret_token    = "secret_token"
  secrets.secret_key_base = "secret_key_base"

  config.logger = Logger.new($stdout)
  Rails.logger  = config.logger

  routes.draw do
    get "/test", to: ->(env) { [200, { "Content-Type" => "text/html" }, ["rack_app"]] }
    get "/another_test", to: "pets#another_test"
    get "/*id", to: "pets#show", constraints: { id: /foo/ }
  end
end

class ApplicationController < ActionController::Base; end

class PetsController < ApplicationController
  def show
    render plain: params[:id]
  end

  def another_test
    render plain: "another_test"
  end
end

require "minitest/autorun"

class BugTest < Minitest::Test
  include Rack::Test::Methods

  def test_rack_app_ignores_constraints
    get "/test"
    assert_equal "rack_app", last_response.body

    get "/another_test"
    assert_equal "another_test", last_response.body

    get "/foo"
    assert_equal "foo", last_response.body

    assert_raises(ActionController::RoutingError) do
      get "/bar"
    end
  end

  private

  def app
    Rails.application
  end
end
```

**Comment by lucasas** [comment]
@pixeltrix I've built some requests tests for it, and does not happen. It happens only on `development` or `production` env. I've tried with webrick or unicorn

**Comment by pixeltrix** [comment]
@lucasas in that case can you build a simple app that exhibits the problem and push it up to a repo I can check out and debug in development mode, thanks.

**Comment by lucasas** [comment]
hey @pixeltrix, I don't know if this is exactly a bug, but I discovered what is happening.

My application has a middleware that uses `Rails.application.routes.recognize_path` method, we this method receives a `Rack` route, it raises an `ActionController::RoutingError` exception.

I know is not recommended to use `recognize_path` method (ex: https://github.com/rails/rails/issues/21477).

What do you think?

**Comment by pixeltrix** [comment]
@lucasas as you said `recognize_path` is private API predominately used in tests so isn't suitable for being used in a Rack middleware. I would recommend finding an alternative way to achieve what you need using public API.

**Comment by rhymes** [comment]
@pixeltrix is there a public API in Rails 5.1+ to resolve a path to a controller/action/params combo?

Thank you!

**Comment by pixeltrix** [comment]
@rhymes in a word, no - sorry. A path could route to different controllers depending on the request context like domain, etc. so it's not feasible to implement anything that would be reliable enough for a public API.

**Comment by pixeltrix** [comment]
@rhymes straying into a support request there but I suggest you look at the [addressable][1] gem's support for URI templates.

[1]: https://github.com/sporkmonger/addressable#uri-templates

**Comment by rhymes** [comment]
@pixeltrix thanks again, and sorry for straying a bit ;-)
