### ISSUE TITLE
Feature request: Render collection to strings

### ISSUE THREAD

**Issue by glebm** [rails/rails#28344]
Hi, I've originally posted this in the [Rails Core mailing list](https://groups.google.com/forum/#!topic/rubyonrails-core/Cx0GXz_k7Dc) but it doesn't seem very active.

Often, it is useful to render a collection not to one string but to a list of strings, especially when caching.

In my app, the [Thredded]() forums engine, we used to cache the posts on a topic page using collection caching.

This requires the entire post to be cached due to the current collection caching interface,
even though only the post content itself is slow to render. That's was not a large problem for us until now.

To get around that, I've implemented a `render_collection_to_strings_with_cache` method that returns a list of `[object, rendered partial]` pairs: [implementation](https://github.com/thredded/thredded/pull/536/files#diff-00110786c7c8a611fd05432b7fb15270).

We now only cache the post contents and not the chrome around it, using multi-get, and with cache hits instrumentation same as regular the collection caching.

Do you think a feature like this belongs in ActionView?

**Comment by vipulnsward** [comment]
Hi @glebm we reserve this tracker for bug reports and issues. 

[Rails Core mailing list](https://groups.google.com/forum/#!topic/rubyonrails-core/Cx0GXz_k7Dc) is still the best place to discuss this, or send a patch to start a discussion.

Thanks!
