### ISSUE TITLE
Add adapter method for creating job retries

### ISSUE THREAD

**Issue by mperham** [rails/rails#28347]
Today, ActiveJob creates retries by creating a brand new job and swallowing the error.

```ruby
  rescue_from(RuntimeError) do
    retry_job wait: 1.minutes
  end
```

Unfortunately that bypasses a lot of functionality that Sidekiq has around job retry.

1. The job is not listed in the set of Retries in the Sidekiq UI so you can't inspect your app's current set of failing jobs.
2. Failing jobs can't be enumerated, as they can today with `Sidekiq::RetrySet.new.each`.
3. The failing job does not output its error message and backtrace on the console so developers can't actually tell if any job is failing.
4. The exception is not bubbled up so Sidekiq's global error handlers can report it (things like Honeybadger, Bugsnag, etc install handlers so any errors within the Sidekiq process can be reported to the app's error service).
5. Any other Sidekiq-specific state for the job is lost

My initial thought is that, instead of scheduling jobs directly, ActiveJob could stub a new adapter method through which job systems can implement retry creation so as to restore as much of their native functionality as possible.  Today we have `enqueue` and `enqueue_at`, maybe something like:

```ruby
class ActiveJob::QueueAdapters::SidekiqAdapter
  def retry_job(job, error, options={})
    # Sidekiq::Client magic
  end
end
```

WDYT?

**Comment by rafaelfranca** [comment]
Yeah, I agree it should be responsibility of the adapter to implement the retry. Now that `retry_on` is a thing it is more important to us to keep the adapter behavior otherwise people will have to not use Active Job's API to get those features.

@dhh @matthewd @jeremy thoughts?

How the implementation for the sidekiq adapter would look like?

**Comment by dhh** [comment]
A delegation sounds like a good idea to me. Sidekiq specific features exposed through that is a little more iffy, but happy to see a proposal for it.

**Comment by mperham** [comment]
More thoughts.  Even if AJ handles the retry via this new scheme, it still does not bubble up the error into the provider; Sidekiq's middleware stack thinks the job execution was successful.  This will break any features that differentiate between job success and failure: batches, metrics, rate limiting, amongst other features.  Raising an error into the provider would be a big implementation change for AJ.

**Comment by dhh** [comment]
Maybe using the Rails API for this stuff just isn't a good fit for Sidekiq,
then. Fair enough for Sidekiq users simply not to take advantage of it if
they want to rely on the more advanced features you offer.

**Comment by mperham** [comment]
Thanks for the sounding board.  We'll see how it goes over the next year and if it becomes a support problem.  Otherwise, let sleeping dogs lie!
