### ISSUE TITLE
Regression on numericality validation

### ISSUE THREAD

**Issue by bluefalcon26** [rails/rails#28346]
### Steps to reproduce

```
ActiveRecord::Schema.define(version: 20170307300001) do

create_table "size_ranges", force: :cascade, options: "ENGINE=InnoDB DEFAULT CHARSET=utf8" do |t|
    t.decimal  "min_mill",   precision: 40, scale: 10
    t.decimal  "max_mill",   precision: 40, scale: 10
    t.datetime "created_at",                           null: false
    t.datetime "updated_at",                           null: false
  end

end
```

```
class SizeRange < ApplicationRecord
  # validations
  validates :min_mill, :max_mill, numericality: true, allow_nil: true
end
```

```
RSpec do
  describe "bug" do
    it "creates a size_range or returns a validation error" do
       SizeRange.create(min_mill: "apple")
    end
  end
end

```

(Guidelines for creating a bug report are [available
here](http://guides.rubyonrails.org/contributing_to_ruby_on_rails.html#creating-a-bug-report))

### Expected behavior
Should get a validation error

### Actual behavior
ArgumentError: invalid value for BigDecimal(): "apple"

### System configuration
**Rails version**:
Rails 5.1.0.beta1

**Ruby version**:
ruby 2.4.0p0 (2016-12-24 revision 57164) [x86_64-linux]

**Notes**
This is a regression from 5.0.2

**Comment by al2o3cr** [comment]
Looks like a possible duplicate of #27429

**Comment by maclover7** [comment]
@bluefalcon26 Can you check and see if #27429 fixes the problem for you?

**Comment by bluefalcon26** [comment]
Yes, it's fixed on the master branch.
