### ISSUE TITLE
ActiveRecord unexpected query generation with polymorphic associations

### ISSUE THREAD

**Issue by 2called-chaos** [rails/rails#28343]
### Steps to reproduce

* Create a model with multiple polymorphic associations (Activity with owner and trackable)
* Try to fetch activities for a user where owner != trackable by passing model objects
  `Activity.where(owner: @user).where.not(trackable: @user)`
* Be lazy and use this: https://gist.github.com/2called-chaos/80ca47cd8da791327837948e7ccf073d

### Expected behavior
I would expect a query like this (_id/_type to be a grouped statement):

```SQL
SELECT * FROM `activities`
WHERE   (`activities`.`owner_type` = 'User' AND `activities`.`owner_id` = 123)
AND NOT (`activities`.`trackable_type` = 'User' AND `activities`.`trackable_id` = 123)
```

### Actual behavior
_id/_type combinations will not be grouped and the resulting set is very different from what the code implies. Ironically there are parentheses for the where.not part of the statement (at least it tries ;) ).

```SQL
SELECT * FROM `activities`
WHERE `activities`.`owner_type` = 'User'
 AND  `activities`.`owner_id` = 123
 AND (`activities`.`trackable_type` != 'User')
 AND (`activities`.`trackable_id` != 123)
```

### System configuration
**Rails version**: 5.0.1

**Ruby version**: 2.3.0

**Comment by al2o3cr** [comment]
Possible duplicate of #16983 and #28258

**Comment by 2called-chaos** [comment]
I searched for "poly" in github issues and did not found these two... Thanks github?!?

https://github.com/rails/rails/issues?utf8=%E2%9C%93&q=is%3Aissue%20poly%20
