### ISSUE TITLE
has_many through injects unwanted join

### ISSUE THREAD

**Issue by ThunderKey** [rails/rails#28350]
### Steps to reproduce

```bash
$ rails new test
$ cd test
```
enable "therubyracer" in the Gemfile

create the follwing files:

```ruby
# db/migrate/20170308215859_create_appointments.rb
class CreateAppointments < ActiveRecord::Migration[5.0]
  def change
    create_table :physicians do |t|
      t.string :name
      t.timestamps
    end

    create_table :patients do |t|
      t.string :name
      t.timestamps
    end

    create_table :appointments do |t|
      t.belongs_to :physician, index: true
      t.belongs_to :patient, index: true
      t.datetime :appointment_date
      t.timestamps
    end
  end
end

# app/models/appointment.rb
class Appointment < ApplicationRecord
  belongs_to :physician
  belongs_to :patient
end

# app/models/patient.rb
class Patient < ApplicationRecord
  has_many :appointments
  has_many :physicians, through: :appointments

  scope :my_test_scope, ->() {
    puts "Patient.all.to_sql : #{Patient.all.to_sql}"
  }
end

# app/models/physician.rb
class Physician < ApplicationRecord
  has_many :appointments
  has_many :patients, through: :appointments
end

# db/seeds.rb
physician = Physician.create name: 'Test Physician'

3.times do |i|
  physician.patients << patient = Patient.create(name: "Test Patient #{i}")
end

4.times do |i|
  Patient.create(name: "Test Patient #{i + 10}")
end
```

Execute:
```bash
$ rake db:migrate
$ rake db:seed
$ rails c
> Physician.first.patients.all.my_test_scope
```

This should now print `

### Expected behavior
The output "Patient.all.to_sql" should be `SELECT "patients".* FROM "patients"`

### Actual behavior
But the output is `SELECT "patients".* FROM "patients" INNER JOIN "appointments" ON "patients"."id" = "appointments"."patient_id" WHERE "appointments"."physician_id" = 1`

### System configuration

**Rails version**: `5.0.0`, `5.0.1`, `5.0.2` and `5.1.0.beta1`

**Ruby version**: `2.3.0`, `2.3.3` and `2.4.0`

**Comment by al2o3cr** [comment]
IIRC this is expected behavior - the block given to the association macro is evaluated in a context where some stuff has already been added to `scoping`.

I'd recommend looking into `unscoped`, which can undo that part.

**Comment by ThunderKey** [comment]
But shouldn't the scope only be used on the current query only? I.e. if call `Patient.count` I would expect to get the total count whether I am in a scope or not.

**Comment by matthewd** [comment]
This is indeed expected behaviour. It's not ideal behaviour, but it is expected: it's a consequence of how scopes work. I'd love to see it improve, but I don't think we've ever had a viable plan to do so.

**Comment by ThunderKey** [comment]
Oh, that's unfortunate. Thank you for the clarification.
