### ISSUE TITLE
System testing: failure screenshots no longer taken

### ISSUE THREAD

**Issue by renchap** [rails/rails#28357]
This is in fact probably linked to #28264, #28223 and/or #28144.
The driver seems to be reset to RackTest before the failure screenshot is taken.

With Rails @37770bc8d13c when I display the driver name in `setup`, `teardown` and `supports_screenshot?`:
```
# Running tests with run options --seed 23034:

Puma starting in single mode...
* Version 3.7.1 (ruby 2.3.3-p222), codename: Snowy Sagebrush
* Min threads: 0, max threads: 1
* Environment: test
* Listening on tcp://0.0.0.0:56702
Use Ctrl-C to stop
Setup: #<Capybara::Poltergeist::Driver:0x007f89317a2c88>
supports_screenshot?: #<Capybara::RackTest::Driver:0x007f893938f418>
Teardown: #<Capybara::RackTest::Driver:0x007f893938f418>
F
```

**Comment by renchap** [comment]
ping @y-yagi @eileencodes

**Comment by y-yagi** [comment]
Thank you for pointing out! I tried to reproduce, but I could not do it. 
The sample application is [here](https://github.com/y-yagi/fix_28357). 

Could you tell me how to reproduce it?

**Comment by eileencodes** [comment]
Yea I can't repro either, but I have a refactoring I'm working on that removes the need for setup/teardown and sets the driver on initialization instead. So I'll finish that up and push and hopefully that will fix the issue.

**Comment by renchap** [comment]
Reproduced it using your sample application @y-yagi, this in fact somes from `minitest-capybara`.
Add the gem to your Gemfile then `include Minitest::Capybara::Behaviour` in `ApplicationSystemTestCase` and the problem occurs.

It is caused by the gem's teardown: https://github.com/wojtekmach/minitest-capybara/blob/master/lib/minitest/capybara.rb#L33

This gem was used in our project before switching to Rails System Testing, I guess I will drop it.

Feel free to close the bug, or keep it open if you want to handle the case when other teardown/setup blocks are using `Capybara.use_default_driver`

**Comment by eileencodes** [comment]
@renchap I pushed the refactoring I was working on https://github.com/rails/rails/commit/17c65342469f211f4a845073e47bf1dfa13ba259

Let me know if you're still seeing this problem.
