### ISSUE TITLE
Allow rake task eager loading to be allowed in production

### ISSUE THREAD

**Issue by olivierlacan** [rails/rails#28358]
It seems that class eager loading in rake tasks [was disabled in 2013](https://github.com/rails/rails/commit/9cac69c602f57e397fe01d866cb24ce1781606d4#diff-580e183141be706162224ef696bdb6c7R294) due to an issue with precompilation (https://github.com/rails/rails/issues/11381) but as a result I'm seeing thread safety issues when running rake tasks in a production worker. 

Shouldn't Rails users be given a choice (configuration option) as to whether their classes are eager loaded in rake tasks or not?

**Comment by olivierlacan** [comment]
My solution to avoid thread safety issues in rake tasks was to call `Rails.application.eager_load!` at the top of the specific task for which I knew we were having issues like `Circular dependency detected while autoloading constant X`. Here's hoping that can help someone with a similar issue in the future.

**Comment by eugeneius** [comment]
https://github.com/rails/rails/pull/28209 was recently opened to make this behaviour configurable!

**Comment by olivierlacan** [comment]
Fantastic. Thanks for the link @eugeneius. Closing in favor of #28209.
