### ISSUE TITLE
Rails 5.1: Cannot require a file located in app/javascript/packs

### ISSUE THREAD

**Issue by fzingg** [rails/rails#28361]
I'm trying to require a javascript file that I created inside app/javascript/packs.
I have run `bin:webpack` and the file is correctly loaded and visible inside the JS console.

But if I try to require it inside my application.js like this :
```ruby
#application.js

require "packs/myfile.js"
```

The app cannot find it. Off course I have try many different paths.

**Comment by fzingg** [comment]
I found the solution :

By default the webpack output folder `public/packs` is not included in the asset pipeline.
So you can include it in the Rails application.rb file or change the output folder in webpack config file.

**Comment by rafaelfranca** [comment]
Yeah, files inside pack are not included in the assets pipeline.
