### ISSUE TITLE
Rails 5.0.2/5.0.1 + Puma ActionCable connection issue

### ISSUE THREAD

**Issue by edwardmp** [rails/rails#28362]
**Steps to reproduce**

Open puma.rb and add SSL certificates:
```
ssl_key = File.expand_path '../certificates/server.key', __FILE__
ssl_cert = File.expand_path '../certificates/server.crt', __FILE__
bind "ssl://127.0.0.1:3000?key=#{ssl_key}&cert=#{ssl_cert}"
# Set on development.rb to force SSL and allowed origin request for ActionCable:
...
config.force_ssl = true
config.action_cable.allowed_request_origins = ['https://lvh.me:4000']
```
In my settings I use redis:
```
development:
  adapter: redis
  url: redis://localhost:6379/1
```
**Expected behavior**

The connection using ActionCable works seamlessly with SSL, just as it does for non-SSL connections.

**Actual behavior**

If I try to use SSL, this warning message is shown in the client's browser console:

`WebSocket connection to 'wss://lvh.me:3000/cable' failed: WebSocket is closed before the connection is established.`

**System configuration**

Ruby version: ruby 2.3.1p112 (2016-04-26 revision 54768) [x86_64-linux]
Rails version: Rails 5.0.2 (also confirmed to be not working on 5.0.1, but did work fine in 5.0.0.1)

Borrowed from https://github.com/puma/puma/issues/1189, seeing same issue as user there.
Related issues: #27625, #27421

**Comment by rafaelfranca** [comment]
This seems to be an issue in puma. cc @schneems

**Comment by rafaelfranca** [comment]
Also cc @matthewd since it is related to https://github.com/rails/rails/commit/5d92089bcae42275953ad310b24f5dd66ff0ec6e

**Comment by edwardmp** [comment]
@rafaelfranca it could be but I can say this:
I've used to the same Puma gem version for the past few months. In combination with Rails 5.0.0.1 everything worked as expected. With Rails 5.0.1 and 5.0.2 it does no longer work. So if it's Puma it wasn't caused by any code change on their part, only the interaction with Rails.

**Comment by wonderer007** [comment]
is it the same issue as this https://github.com/websocket-rails/websocket-rails/issues/399#issuecomment-237814291

**Comment by edwardmp** [comment]
@wonderer007 
It doesn't appear so, the errror message in the client browser is different (does not mention handshake)

**Comment by maclover7** [comment]
@edwardmp Can you confirm that if you keep the Puma version constant, only upgrading from Rails 5.0.0.1 to 5.0.2 introduces this issue for you?

**Comment by edwardmp** [comment]
@maclover7 
Good question. Actually I haven't yet but it was definitely on my mind. Let me try that and get back to you.

**Comment by edwardmp** [comment]
@maclover7 
It's confirmed: downgrading to 5.0.0.1 shows the issue is not present when using that version. It then broke when 5.0.1 was released and continued to be present in 5.0.2.

**Comment by maclover7** [comment]
Dug into this, turns out this is an issue with Puma...

Starting with [this commit](https://github.com/rails/rails/commit/5d92089bcae42275953ad310b24f5dd66ff0ec6e), on [this line](https://github.com/rails/rails/blob/master/actioncable/lib/action_cable/connection/stream.rb#L43), Action Cable calls `@rack_hijack_io.write_nonblock` to write data out to the socket. However, this code depends on the 99% case where `@rack_hijack_io` is a `TCPSocket` / `IO`. When using Puma, `@rack_hijack_io` is actually an instance of `Puma::MiniSSL::Socket`, which does not implement the `write_nonblock` method (it does implement the `read_nonblock` method...). My take on how to fix this would be for Puma to conform to `TCPSocket`'s API, and to implement the `write_nonblock` method.

cc puma folks @schneems @nateberkopec @evanphx

**Comment by edwardmp** [comment]
@maclover7 Great that you'd be able to find this out! Sounds logical, but why aren't we seeing any exceptions being raised after a non-existing method is called on `Puma::MiniSSL::Socket`

**Comment by matthewd** [comment]
Yeah, please do see what seems reasonable. I think the problem with keeping an exception is just that we don't have anywhere sane to raise it.

Failing that, and assuming we're not "legitimately" eating some other exceptions that we *want* to be silent, a log message does seem like a reasonable minimum.

**Comment by edwardmp** [comment]
@matthewd 
Great, I'll look into that in the coming days.

On the side of Puma though, this might be a hard nut to crack: they in turn call `TCPServer` or `UnixServer`, neither of which implements `write_nonblock` functionality.

**Comment by nateberkopec** [comment]
@edwardmp Please do!

**Comment by edwardmp** [comment]
Here is a oneliner logging all socket write errors:
https://github.com/edwardmp/rails/commit/2de531a81b679626a2b14b174c8d859f2c37cd7f

This needs work though, as I need to call Rails.logger to access the logger, because the logger dependency isn't injected in this class yet.

**Comment by edwardmp** [comment]
Hi  @schneems @nateberkopec @evanphx,

I've looked into this and tried a few things, simply creating a method similar to the existing write method to primarily just call the sockets write_nonblock method in turn. Unfortunately this did not appear to work/fix the issue. I think my socket related knowledge is insufficient atm to create a proper fix, so I hope one of you is able to figure this out without spending to much time.

Thanks in advance!

**Comment by djones** [comment]
I get this issue too. Rails 5.0.2, Puma 3.8.2, Ruby 2.4.1p111

**Comment by djones** [comment]
In the browser I get:

```
WebSocket connection to 'wss://localhost:3001/cable' failed: WebSocket is closed before the connection is established.
```

The Rails log loops over these lines when the browser tries to make the connection but can't establish it:

```
Started GET "/cable" for ::1 at 2017-04-11 17:04:39 -0700
Started GET "/cable/" [WebSocket] for ::1 at 2017-04-11 17:04:39 -0700
Successfully upgraded to WebSocket (REQUEST_METHOD: GET, HTTP_CONNECTION: Upgrade, HTTP_UPGRADE: websocket)
Finished "/cable/" [WebSocket] for ::1 at 2017-04-11 17:04:45 -0700
Started GET "/cable" for ::1 at 2017-04-11 17:04:46 -0700
Started GET "/cable/" [WebSocket] for ::1 at 2017-04-11 17:04:46 -0700
Successfully upgraded to WebSocket (REQUEST_METHOD: GET, HTTP_CONNECTION: Upgrade, HTTP_UPGRADE: websocket)
Finished "/cable/" [WebSocket] for ::1 at 2017-04-11 17:04:49 -0700
Started GET "/cable" for ::1 at 2017-04-11 17:04:49 -0700
Started GET "/cable/" [WebSocket] for ::1 at 2017-04-11 17:04:49 -0700
Successfully upgraded to WebSocket (REQUEST_METHOD: GET, HTTP_CONNECTION: Upgrade, HTTP_UPGRADE: websocket)
```

If I change `config.action_cable.url` to use HTTP (in my case `ws://localhost:3000/cable`) and I disable forcing SSL... it starts working just fine like so:

```
Finished "/cable/" [WebSocket] for ::1 at 2017-04-11 17:06:55 -0700
Started GET "/cable" for ::1 at 2017-04-11 17:06:55 -0700
Started GET "/cable/" [WebSocket] for ::1 at 2017-04-11 17:06:55 -0700
Successfully upgraded to WebSocket (REQUEST_METHOD: GET, HTTP_CONNECTION: Upgrade, HTTP_UPGRADE: websocket)
ReportsChannel is transmitting the subscription confirmation
ReportsChannel is streaming from reports
```

**Comment by edwardmp** [comment]
Submitted a PR to start logging socket write errors: #28757 

The folks over at Puma have a temporary fix for the issue on their part (not implementing `write_nonblock` and `read_nonblock` methods). If this can be merged in I think we can close this issue :)

**Comment by zerocool4u2** [comment]
`config.action_cable.url = 'ws:lvh.me:3000/cable'` solved it for me, thanks @djones 
notice ws instead wss, I'm guessing wss stands for websocket secure?
