### ISSUE TITLE
Limited ids returns incorrect results

### ISSUE THREAD

**Issue by ahorek** [rails/rails#28364]
### Steps to reproduce

This query returns wrong results, because issues.id is incorrectly used as a condition for the primary key.
### Expected behavior
I removed issues.id from the order statement

>> Project.eager_load(:issues).order('issues.subject').limit(10)
  SQL SELECT  DISTINCT `projects`.`id`, issues.subject AS alias_0 FROM `projects` LEFT OUTER JOIN `issues` ON `issues`.`project_id` = `projects`.`id`  ORDER BY issues.subject LIMIT 10
  SQL SELECT `projects`.`id` AS t0_r0, `projects`.`name` AS t0_r1, `projects`.`description` AS t0_r2, `projects`.`homepage` AS t0_r3, `projects`.`is_public` AS t0_r4, `projects`.`parent_id` AS t0_r5, `projects`.`created_on` AS t0_r6, `projects`.`updated_on` AS t0_r7, `projects`.`identifier` AS t0_r8, `projects`.`status` AS t0_r9, `projects`.`lft` AS t0_r10, `projects`.`rgt` AS t0_r11, `projects`.`easy_is_easy_template` AS t0_r12, `projects`.`easy_due_date` AS t0_r13, `projects`.`author_id` AS t0_r14, `projects`.`easy_start_date` AS t0_r15, `projects`.`easy_level` AS t0_r16, `projects`.`easy_external_id` AS t0_r17, `projects`.`inherit_members` AS t0_r18, `projects`.`calculation_discount` AS t0_r19, `projects`.`calculation_position` AS t0_r20, `projects`.`client_id` AS t0_r21, `projects`.`calculation_discount_is_percent` AS t0_r22, `projects`.`client_name` AS t0_r23, `projects`.`calculation_date` AS t0_r24, `projects`.`easy_currency_id` AS t0_r25, `projects`.`easy_baseline_for_id` AS t0_r26, `projects`.`easy_currency_code` AS t0_r27, `projects`.`default_version_id` AS t0_r28, `projects`.`dmsf_description` AS t0_r29, `projects`.`dmsf_notification` AS t0_r30, `projects`.`easy_priority_id` AS t0_r31, `projects`.`easy_has_custom_menu` AS t0_r32, `issues`.`id` AS t1_r0, `issues`.`tracker_id` AS t1_r1, `issues`.`project_id` AS t1_r2, `issues`.`subject` AS t1_r3, `issues`.`description` AS t1_r4, `issues`.`due_date` AS t1_r5, `issues`.`category_id` AS t1_r6, `issues`.`status_id` AS t1_r7, `issues`.`assigned_to_id` AS t1_r8, `issues`.`priority_id` AS t1_r9, `issues`.`fixed_version_id` AS t1_r10, `issues`.`author_id` AS t1_r11, `issues`.`lock_version` AS t1_r12, `issues`.`created_on` AS t1_r13, `issues`.`updated_on` AS t1_r14, `issues`.`start_date` AS t1_r15, `issues`.`done_ratio` AS t1_r16, `issues`.`estimated_hours` AS t1_r17, `issues`.`easy_is_easy_template` AS t1_r18, `issues`.`parent_id` AS t1_r19, `issues`.`root_id` AS t1_r20, `issues`.`lft` AS t1_r21, `issues`.`rgt` AS t1_r22, `issues`.`is_private` AS t1_r23, `issues`.`activity_id` AS t1_r24, `issues`.`easy_level` AS t1_r25, `issues`.`easy_external_id` AS t1_r26, `issues`.`easy_due_date_time` AS t1_r27, `issues`.`easy_helpdesk_mailbox_username` AS t1_r28, `issues`.`easy_helpdesk_project_sla_id` AS t1_r29, `issues`.`closed_on` AS t1_r30, `issues`.`easy_is_repeating` AS t1_r31, `issues`.`easy_repeat_settings` AS t1_r32, `issues`.`easy_next_start` AS t1_r33, `issues`.`easy_start_date_time` AS t1_r34, `issues`.`calculation_position` AS t1_r35, `issues`.`calculation_rate` AS t1_r36, `issues`.`easy_ldap_entity_mapping` AS t1_r37, `issues`.`resolved_at` AS t1_r38, `issues`.`closed_at` AS t1_r39, `issues`.`easy_response_date_time` AS t1_r40, `issues`.`calculation_discount` AS t1_r41, `issues`.`calculation_discount_is_percent` AS t1_r42, `issues`.`calculation_unit` AS t1_r43, `issues`.`easy_time_to_solve_paused_at` AS t1_r44, `issues`.`easy_closed_by_id` AS t1_r45, `issues`.`easy_sms_tel_num` AS t1_r46, `issues`.`easy_sms_binding_method` AS t1_r47, `issues`.`easy_status_updated_on` AS t1_r48, `issues`.`in_easy_calculation` AS t1_r49, `issues`.`easy_reopen_at` AS t1_r50, `issues`.`easy_sprint_id` AS t1_r51, `issues`.`easy_last_updated_by_id` AS t1_r52, `issues`.`easy_time_to_solve_pause` AS t1_r53, `issues`.`easy_helpdesk_need_reaction` AS t1_r54, `issues`.`easy_story_points` AS t1_r55 FROM `projects` LEFT OUTER JOIN `issues` ON `issues`.`project_id` = `projects`.`id` WHERE `projects`.`id` IN (167, 102, 132, 168, 103, 133, 169, 104, 134, 171)  ORDER BY issues.subject
**=> #<ActiveRecord::Relation [#<Project id: 102, ....]>
=> got 10 results**

### Actual behavior

>> Project.eager_load(:issues).order('issues.id, issues.subject').limit(10)
DISTINCT doesn't work here like it was intended, project ids will not be uniq!
  SQL  **SELECT  DISTINCT `projects`.`id`, issues.id, issues.subject** AS alias_0 FROM `projects` LEFT OUTER JOIN `issues` ON `issues`.`project_id` = `projects`.`id`  ORDER BY issues.id, issues.subject LIMIT 10
  SQL SELECT `projects`.`id` AS t0_r0, `projects`.`name` AS t0_r1, `projects`.`description` AS t0_r2, `projects`.`homepage` AS t0_r3, `projects`.`is_public` AS t0_r4, `projects`.`parent_id` AS t0_r5, `projects`.`created_on` AS t0_r6, `projects`.`updated_on` AS t0_r7, `projects`.`identifier` AS t0_r8, `projects`.`status` AS t0_r9, `projects`.`lft` AS t0_r10, `projects`.`rgt` AS t0_r11, `projects`.`easy_is_easy_template` AS t0_r12, `projects`.`easy_due_date` AS t0_r13, `projects`.`author_id` AS t0_r14, `projects`.`easy_start_date` AS t0_r15, `projects`.`easy_level` AS t0_r16, `projects`.`easy_external_id` AS t0_r17, `projects`.`inherit_members` AS t0_r18, `projects`.`calculation_discount` AS t0_r19, `projects`.`calculation_position` AS t0_r20, `projects`.`client_id` AS t0_r21, `projects`.`calculation_discount_is_percent` AS t0_r22, `projects`.`client_name` AS t0_r23, `projects`.`calculation_date` AS t0_r24, `projects`.`easy_currency_id` AS t0_r25, `projects`.`easy_baseline_for_id` AS t0_r26, `projects`.`easy_currency_code` AS t0_r27, `projects`.`default_version_id` AS t0_r28, `projects`.`dmsf_description` AS t0_r29, `projects`.`dmsf_notification` AS t0_r30, `projects`.`easy_priority_id` AS t0_r31, `projects`.`easy_has_custom_menu` AS t0_r32, `issues`.`id` AS t1_r0, `issues`.`tracker_id` AS t1_r1, `issues`.`project_id` AS t1_r2, `issues`.`subject` AS t1_r3, `issues`.`description` AS t1_r4, `issues`.`due_date` AS t1_r5, `issues`.`category_id` AS t1_r6, `issues`.`status_id` AS t1_r7, `issues`.`assigned_to_id` AS t1_r8, `issues`.`priority_id` AS t1_r9, `issues`.`fixed_version_id` AS t1_r10, `issues`.`author_id` AS t1_r11, `issues`.`lock_version` AS t1_r12, `issues`.`created_on` AS t1_r13, `issues`.`updated_on` AS t1_r14, `issues`.`start_date` AS t1_r15, `issues`.`done_ratio` AS t1_r16, `issues`.`estimated_hours` AS t1_r17, `issues`.`easy_is_easy_template` AS t1_r18, `issues`.`parent_id` AS t1_r19, `issues`.`root_id` AS t1_r20, `issues`.`lft` AS t1_r21, `issues`.`rgt` AS t1_r22, `issues`.`is_private` AS t1_r23, `issues`.`activity_id` AS t1_r24, `issues`.`easy_level` AS t1_r25, `issues`.`easy_external_id` AS t1_r26, `issues`.`easy_due_date_time` AS t1_r27, `issues`.`easy_helpdesk_mailbox_username` AS t1_r28, `issues`.`easy_helpdesk_project_sla_id` AS t1_r29, `issues`.`closed_on` AS t1_r30, `issues`.`easy_is_repeating` AS t1_r31, `issues`.`easy_repeat_settings` AS t1_r32, `issues`.`easy_next_start` AS t1_r33, `issues`.`easy_start_date_time` AS t1_r34, `issues`.`calculation_position` AS t1_r35, `issues`.`calculation_rate` AS t1_r36, `issues`.`easy_ldap_entity_mapping` AS t1_r37, `issues`.`resolved_at` AS t1_r38, `issues`.`closed_at` AS t1_r39, `issues`.`easy_response_date_time` AS t1_r40, `issues`.`calculation_discount` AS t1_r41, `issues`.`calculation_discount_is_percent` AS t1_r42, `issues`.`calculation_unit` AS t1_r43, `issues`.`easy_time_to_solve_paused_at` AS t1_r44, `issues`.`easy_closed_by_id` AS t1_r45, `issues`.`easy_sms_tel_num` AS t1_r46, `issues`.`easy_sms_binding_method` AS t1_r47, `issues`.`easy_status_updated_on` AS t1_r48, `issues`.`in_easy_calculation` AS t1_r49, `issues`.`easy_reopen_at` AS t1_r50, `issues`.`easy_sprint_id` AS t1_r51, `issues`.`easy_last_updated_by_id` AS t1_r52, `issues`.`easy_time_to_solve_pause` AS t1_r53, `issues`.`easy_helpdesk_need_reaction` AS t1_r54, `issues`.`easy_story_points` AS t1_r55 FROM `projects` LEFT OUTER JOIN `issues` ON `issues`.`project_id` = `projects`.`id` WHERE `projects`.`id` IN (**NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL**)  ORDER BY issues.id, issues.subject
**=> #<ActiveRecord::Relation []>
=> got no results!**

changing the order should not have any effect on results count

### System configuration
tested on Rails 4.2.7.1 and current master
ruby 2.3.3 mingw
works correctly on sqlite, doesn't work on mysql & postgres

**Comment by al2o3cr** [comment]
Hmmm, something appears to have gone awry in the eager loader:
```
WHERE projects.id IN (NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
```
*That's* not right.

Do you get the same results if you split the SQL literal passed to `order`? (so `order('issues.id', 'issues.subject')`)

**Comment by ahorek** [comment]
yes, it works separately. Take a look at the first query:
**order('issues.id, issues.subject')**
SELECT DISTINCT projects.id, issues.id, issues.subject AS alias_0 FROM projects LEFT OUTER JOIN issues ON issues.project_id = projects.id ORDER BY issues.id, issues.subject LIMIT 10

**order('issues.id', 'issues.subject')**
SELECT DISTINCT projects.id, issues.id **AS alias_0**, issues.subject AS alias_1 FROM projects LEFT OUTER JOIN issues ON issues.project_id = projects.id ORDER BY issues.id, issues.subject LIMIT 10

as you can see there's a conflict between issues.id and projects.id. issues.id should also have an alias, otherwise it generates ids for the second query WHERE projects.id IN (NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL) - these values are from issues.id, but obviousely it should be projects.

I'm working on a fix, because **DISTINCT also doesn't work** here (it doesn't return unique projects.ids, so after LIMIT is applied, some entiries are lost).
Both issues work properly on SQLITE, because it doesn't need FULL GROUP BY STATEMENT like mysql 5.7 or postgres. Limited_ids_for method tries to handle these differences, but in a wrong way.

**Comment by al2o3cr** [comment]
@ahorek Seems like it's going to require parsing the SQL fragment to make the first case look like the second, especially since the fragment could be something like `date_part('month', created_at), status` in the general case.
