### ISSUE TITLE
[Feature Request] webpack2 import actioncable 

### ISSUE THREAD

**Issue by limichange** [rails/rails#28366]
actioncable@5.0.2 not support webpack2 now.

```js
import ActionCable from 'actioncable'

console.log(ActionCable) // undefined
```

please support it, thx.
just like this.
```json
...
  "main": "dist/vue.runtime.common.js",
  "module": "dist/vue.runtime.esm.js",
  "unpkg": "dist/vue.js",
  "typings": "types/index.d.ts",
...
```

**Comment by limichange** [comment]
I just publish `actionscable-esm`.
Look at https://github.com/yuki-torii/actioncable-esm

**Comment by rafaelfranca** [comment]
Feel free to open a PR.

**Comment by rafaelfranca** [comment]
BTW, does actioncable@5.1.0-beta1 work?

**Comment by smarquez1** [comment]
@rafaelfranca it was working on actionvable@5.0.1, it does not work on actioncable@5.1.0-beta1

**Comment by rafaelfranca** [comment]
Weird. The way it was released was the same and the code seems to be the same. I'm not a webpack user, could you investigate why those version doesn't work?

**Comment by limichange** [comment]
Thanks reply 😃 .

@rafaelfranca In fact, it's not same :D
https://github.com/yuki-torii/actioncable-esm/blob/master/index.esm.js#L591

@smarquez1 @rafaelfranca `actionvable@5.0.1` `actioncable@5.1.0-beta1` not work, just get `undefinded`.

I think you should improve js module build way. Because more and more people use webpack2 to build app. 

### About javascript module
- **[UMD](https://github.com/umdjs/umd)**: UMD builds can be used directly in the browser via a `<script>` tag.

- **[CommonJS](http://wiki.commonjs.org/wiki/Modules/1.1)**: CommonJS builds are intended for use with older bundlers like [browserify](http://browserify.org/) or [webpack 1](https://webpack.github.io). 

- **[ES Module](http://exploringjs.com/es6/ch_modules.html)**: ES module builds are intended for use with modern bundlers like [webpack 2](https://webpack.js.org) or [rollup](http://rollupjs.org/).

**Comment by rafaelfranca** [comment]
Yeah. What I could get is that sprockets-export doesn't Es modules yet. https://github.com/javan/sprockets-export/blob/master/lib/sprockets/export/template.js.erb

@javan is that correct?

**Comment by javan** [comment]
Found the issue. Fix in progress here https://github.com/rails/rails/pull/28385

**Comment by javan** [comment]
FWIW, I tested `actioncable@5.0.1` and `actioncable@5.0.2`, and both work fine with webpack using `require` or `import` statements. `actioncable@5.1.0-beta1` does not.

**Comment by limichange** [comment]
@javan Thx. You are a great help.
