### ISSUE TITLE
ActiveRecord connections not checked in

### ISSUE THREAD

**Issue by michalbugno** [rails/rails#28363]
First time reporting here, please be gentle ;-)

### Steps to reproduce

1. `rails new myapp`
2. Use `mysql2` gem (I believe it doesn't matter which DB)
3. Use `thin` webserver (I couldn't reproduce on mongrel)
4. Setup `config/database.yml` to work with mysql2 & create db
5. `bin/rails server`
6. `curl localhost:3000` -- this instantiates AR connection
7. `sudo service mysql stop` or similar - stop you DB
8. `curl localhost:3000` again (when DB is stopped to make sure connection try will fail)

### Expected behavior

The connection is marked as 'failed' and AR pool is left in consistent state with the failed connection not 'using up' pool's space.

### Actual behavior

The previously instantiated connection fails upon the second request and is unusable anymore additionally taking up the AR pool "space" forever. Eventually you will drain the whole pool (default is 5) and make your app unusable ("waited 5.0000s for connection").

### System configuration
**Rails version**:

4.2

**Ruby version**:

2.1.0

### My investigation
* the connection is instantiated because of `QueryCache` middleware
* I don't think Ruby version matters, as well as AR (I'm pretty sure 3.x and 4.x are affected, don't know about 5.x)

1. At the second request the connection is fetched from `@available` Queue (https://github.com/rails/rails/blob/4-2-stable/activerecord/lib/active_record/connection_adapters/abstract/connection_pool.rb#L419)
2. Then the connection is checked out and verified (https://github.com/rails/rails/blob/4-2-stable/activerecord/lib/active_record/connection_adapters/abstract/connection_pool.rb#L351)
3. `verify!` fails leaving checked out connection in inconsistent state (https://github.com/rails/rails/blob/4-2-stable/activerecord/lib/active_record/connection_adapters/abstract/connection_pool.rb#L456)

**Comment by maclover7** [comment]
Hi @michalbugno! Are you able to reproduce this on Rails master?
