### ISSUE TITLE
Cookies from development server won't save in IE

### ISSUE THREAD

**Issue by MMercieca** [rails/rails#28376]
### Steps to reproduce

This is visible when trying to save any cookie from a development server in IE.  I ran in to this trying to set up a log in with the devise gem, but this applies to all cookies. 

Steps to reproduce.

Setup: 
1. A development web server (connect on a lan using an IP address e.g. http://10.x.x.x)
2. Visit the web site in IE 11

Actions
1. Attempt to save a cookie

I was trying to log in with the devise gem installed.

Observe that the `Set-Cookie` header is sent with `domain=;`.

### Expected behavior
The cookie is saved to the browser when the `Set-Cookie` header is sent.

### Actual behavior
No cookie is saved after the `Set-Cookie` header is sent.

### How this can be fixed

I monkey patched `ActionDispatch::Cookies::CookieJar.handle_options` to delete the `domain` key from the options hash if it is blank.  This allowed the cookie to be saved and the site to operate normally. 

### System configuration
**Rails version**: 4.2.7.1

**Ruby version**: 2.2.5p319

**Comment by rafaelfranca** [comment]
Could you open a PR? As https://tools.ietf.org/html/rfc6265#page-20, if the domain is empty the behavior is undefined so I guess IE11 ignore the cookie entirely as the RFC recommends and other browsers not.

**Comment by MMercieca** [comment]
PR opened at https://github.com/rails/rails/pull/28377
