### ISSUE TITLE
Rails 5.1: 'select' on association proxy does not see new (unsaved) records

### ISSUE THREAD

**Issue by rst** [rails/rails#28374]
### Steps to reproduce

 * Run test in gist [here](https://gist.github.com/rst/bd316b76edf2684b00157b1684e76a68), or...
 * Set up a blog/comment schema, where comments have a 'text'
 * Create a post
 * Do `post.comments.build(text: 'New text')`
 * Do `post.comments.select{ |x| x.text == 'New text' }`

### Expected behavior
I expect this to return an array containing the new, unsaved record returned by `build`, as it does in Rails 5.0.2. This is also what happens in 5.1.0.beta1 with `post.comments.to_a.select{ |x| x.text == 'New text' }` (note the `to_a`).

### Actual behavior
It returns an empty array.

### System configuration
**Rails version**: 5.1.0.beta1

**Ruby version**: 2.2.4

**Comment by kamipo** [comment]
Fixed in #28354.
