### ISSUE TITLE
guide incorrectly refers to public/assets/images ?

### ISSUE THREAD

**Issue by jjb** [rails/rails#28387]
The [asset pipeline guide](https://github.com/rails/rails/blob/master/guides/source/asset_pipeline.md#coding-links-to-assets) has this line:

> In regular views you can access images in the `public/assets/images` directory like this:

To my knowledge the asset pipeline never creates an "images" directory and puts all images, stylesheets, and javascripts into the top-level "assets" directory. Am I wrong or is the guide wrong?

When I find out either way, I'll put in a PR to fix / make more clear.

**Comment by promptc3** [comment]
you are right `public/` has no subdirectory

**Comment by vipulnsward** [comment]
https://github.com/rails/rails/blob/master/guides/source/asset_pipeline.md#how-to-use-the-asset-pipeline states why this existed. 

Since it is preferred, we can change to "app/assets/images". @jjb can you send a PR for this?

**Comment by maclover7** [comment]
Closing since #28421 was merged.
