### ISSUE TITLE
Rails 5.1: Primary Key is not a BIGINT

### ISSUE THREAD

**Issue by jonhue** [rails/rails#28386]
### Expected behavior
Using `rails 5.1.beta1` and `mysql2`, migrations *should* use `BIGINT` as primary key integers by default. -> #26266 

### Actual behavior
Still my *primary keys are all 4-bit integers*.

### Steps to reproduce

*db/migrate/20170311112129_create_receipts.rb*

    class CreateReceipts < ActiveRecord::Migration[5.1]
      def change
        create_table :receipts do |t|
    
          t.timestamps null: false
        end
      end
    end

Trying to set a `BIGINT` like `5473508900871246157` as `id`, Rails raises the following exception:

> ActiveModel::RangeError: 5473508900871246157 is out of range for ActiveModel::Type::Integer with limit 4 bytes

### System configuration
**Rails version**: 5.1.beta1

**Ruby version**: 2.3.3

**Comment by vipulnsward** [comment]
Going to give this a close, since its not reproducible on master - https://gist.github.com/vipulnsward/de107851b4c0db07571a324dee64df3e

Let me know if https://gist.github.com/vipulnsward/de107851b4c0db07571a324dee64df3e still fails for you.

**Comment by jonhue** [comment]
@vipulnsward You are right, I noticed that all migrations I created after upgrading to Rails 5.1 have indeed a `BIGINT` as primary key.
I just assumed that if I change ` < ActiveRecord::Migration[5.0]` to ` < ActiveRecord::Migration[5.1]` the older migrations would use that as well after resetting database and schema.

Is there a way I can use my older migrations or do I need to recreate them all?

**Comment by matthewd** [comment]
> I just assumed that if I change < ActiveRecord::Migration[5.0] to < ActiveRecord::Migration[5.1] the older migrations would use that as well after resetting database and schema.

That should be true. My guess would be that when you reset your database, you recreated it from schema.rb, not by actually migrating from scratch. Maybe?

`rails db:drop db:create db:migrate` should do what you want, I think.

(Of course, in any situation where your database actually contains something of value [in any environment!], the correct thing to do is to create a new migration to convert the columns, and leave the existing migrations unchanged.)

**Comment by jonhue** [comment]
@matthewd That exactly is my problem.

> rails db:drop db:create db:migrate

will still create tables for these migrations with regular integers as primary keys.

**Comment by jmccartie** [comment]
@jonhue Unfortunately, I cannot reproduce this.  I'm running MySQL `5.5.49`.

Here's what I did:

* Created new app with `5.0.2`
* Created and ran new migration 

```ruby
class CreateUsers < ActiveRecord::Migration[5.0]
  def change
    create_table :users do |t|
      t.string :name
    end
  end
end
```

* Confirmed integer primary key (expected):

```
mysql> describe users;
+-------+--------------+------+-----+---------+----------------+
| Field | Type         | Null | Key | Default | Extra          |
+-------+--------------+------+-----+---------+----------------+
| id    | int(11)      | NO   | PRI | NULL    | auto_increment |
| name  | varchar(255) | YES  |     | NULL    |                |
+-------+--------------+------+-----+---------+----------------+
```

* Backed out migration with `rake db:rollback`

```
mysql> describe users;
ERROR 1146 (42S02): Table 'temp_development.users' doesn't exist
```

* Updated to Rails `5.1.0.beta1`
* Modified migration file to 5.1

```ruby
class CreateUsers < ActiveRecord::Migration[5.1]
  def change
    create_table :users do |t|
      t.string :name
    end
  end
end
```

* Re-ran migration with `rake db:migrate`
* Primary key is now BIGINT (expected)

```
mysql> describe users;
+-------+--------------+------+-----+---------+----------------+
| Field | Type         | Null | Key | Default | Extra          |
+-------+--------------+------+-----+---------+----------------+
| id    | bigint(20)   | NO   | PRI | NULL    | auto_increment |
| name  | varchar(255) | YES  |     | NULL    |                |
+-------+--------------+------+-----+---------+----------------+
```

**Comment by jonhue** [comment]
@matthewd Could that behavior be due to creating migrations with rails 4.2 in the first place? I have absolutely no idea, even in production on heroku on a postgres db, I have the same problem.

**Comment by matthewd** [comment]
@jonhue I don't see how... the generator just writes a file: manually updating the file for the one difference (the version number) should give exactly the same result.

@jmccartie's sequence looks as I expect; where does it diverge for you?

**Comment by jonhue** [comment]
Here is what I did when trying to reproduce that error in a new app:

* Created new app with 4.2.8
* Created and ran new migration

``` ruby
class CreateUsers < ActiveRecord::Migration
  def change
    create_table :users do |t|
      t.string :name
    end
  end
end
```

* Confirmed integer primary key (expected):

``` text
mysql> describe users;
+-------+--------------+------+-----+---------+----------------+
| Field | Type         | Null | Key | Default | Extra          |
+-------+--------------+------+-----+---------+----------------+
| id    | int(11)      | NO   | PRI | NULL    | auto_increment |
| name  | varchar(255) | YES  |     | NULL    |                |
+-------+--------------+------+-----+---------+----------------+
2 rows in set (0.00 sec)
```

* Updated to Rails 5.1.0.beta1
* Modified migration file to 4.2

``` ruby
class CreateUsers < ActiveRecord::Migration[4.2]
  def change
    create_table :users do |t|
      t.string :name
    end
  end
end
```

* Backed out migration with `rails db:rollback`
* Modified migration file to 5.1

``` ruby
class CreateUsers < ActiveRecord::Migration[5.1]
  def change
    create_table :users do |t|
      t.string :name
    end
  end
end
```

* Re-ran migration with `rails db:migrate`
* And ...

``` text
mysql> describe users;
+-------+--------------+------+-----+---------+----------------+
| Field | Type         | Null | Key | Default | Extra          |
+-------+--------------+------+-----+---------+----------------+
| id    | bigint(20)   | NO   | PRI | NULL    | auto_increment |
| name  | varchar(255) | YES  |     | NULL    |                |
+-------+--------------+------+-----+---------+----------------+
2 rows in set (0.00 sec)
```

it worked.

**But** as I noticed then all tables in my 'real' app use `bigint(20)`, and I still get the error.

``` test
max for bigint(20): 9_223_372_036_854_775_807
value I am trying to set: 5_473_508_900_871_246_157
```

But I now know what I missed. I did not upgrade the attributes related to the id's to bigint. The error did not specifically named the attribute `id` as source of the exception, I just assumed it.

**Comment by jonhue** [comment]
@jmccarte @matthewd is the number I am attempting to set as id too big? MySql tells me that the column is a bigint, and still I cannot set it to a big int. Could there be an issue with rails connecting to the database, because rails still thinks it is a 4 bit integer?

**Comment by rab** [comment]
I ran into this issue from a different angle: creating a foreign key to a table created pre-5.1 fails (MySQL).

In my (client's) case, the Member model exists and the Role and Hat models are going to be created (for a role-based authorization implementation). Starting simply with:

```
$ rails g migration CreateRole name description
$ rails g migration CreateHat member:references role:references
$ rails db:migrate
== 20170927000118 CreateRole: migrating =======================================
-- create_table(:roles)
   -> 0.2327s
== 20170927000118 CreateRole: migrated (0.2331s) ==============================

== 20170927000202 CreateHat: migrating ========================================
-- create_table(:hats)
rails aborted!
StandardError: An error has occurred, all later migrations canceled:

Mysql2::Error: Table 'sa_website4_dev.hats' doesn't exist: SHOW FULL FIELDS FROM `hats`
```
_and *many* more backtrace lines_ including these lines:

```
ActiveRecord::StatementInvalid: Mysql2::Error: Table 'sa_website4_dev.hats' doesn't exist: SHOW FULL FIELDS FROM `hats`
Mysql2::Error: Table 'sa_website4_dev.hats' doesn't exist
Mysql2::Error: Cannot add foreign key constraint
```

That last one turns out to be the clue!
```
==> db/migrate/20170927000118_create_role.rb <==
class CreateRole < ActiveRecord::Migration[5.1]
  def change
    create_table :roles do |t|
      t.string :name, index: true, unique: true
      t.string :description
    end
  end
end

==> db/migrate/20170927000202_create_hat.rb <==
class CreateHat < ActiveRecord::Migration[5.1]
  def change
    create_table :hats do |t|
      t.references :member, foreign_key: true
      t.references :role, foreign_key: true
    end
  end
end
```

When the SQL is generated, the attempt is to make a `hats.member_id` which is created as a `bigint(20)` be a foreign key referencing `members.id` which is a lowly `int(11)` having been created from an old migration (before the version tagging began and when 4-byte primary keys were good enough).

The "fix" is to change the migrations to be 5.0 rather than 5.1 and the constraints get created successfullly.

**Comment by johan-smits** [comment]
Is there a way to migrate all current schema's to a new 5.1 migration without lossing the data?

**Comment by elyalvarado** [comment]
The only way to migrate all current schema to 5.1 bigint primary keys will be to manually remove the foreign_keys, change all primary keys and referencing columns to bigint, and then recreate the foreign keys. Possible but not easy.

**Comment by wellington1993** [comment]
I have the same problem with latest stable version.

**Comment by lluchez** [comment]
Same issue here.
On a project I'm trying to upgrade from Rails `5.0.6` to `5.2.0` ([link to PR](https://github.com/lluchez/my-ledger/pull/36/)).
When CircleCI tries to run my tests it fails to create the database:
> rake aborted!
ActiveRecord::MismatchedForeignKey: Column `statement_parser_id` on table `bank_accounts` has a type of `int(11)`.
This does not match column `id` on `statement_parsers`, which has type `bigint(20)`.
To resolve this issue, change the type of the `statement_parser_id` column on `bank_accounts` to be :integer. (For example `t.integer statement_parser_id`).

It was working fine before.
[Github link to my schema file](https://github.com/lluchez/my-ledger/blob/i34-update_to_rails_520/db/schema.rb)
