### ISSUE TITLE
ActiveRecord: Memory leak in record.relation.new

### ISSUE THREAD

**Issue by atombender** [rails/rails#28397]
### Steps to reproduce

Complete reproducible test case ([zip file with Gemfile](https://github.com/rails/rails/files/837317/leak.zip)):

```ruby
require 'active_support'
require 'active_record'

ActiveRecord::Base.establish_connection(adapter: 'sqlite3', database: './testfile')
ActiveRecord::Schema.define do
  create_table :cats, force: true do |t|
  end
  create_table :dogs, force: true do |t|
    t.text :uid
    t.integer :cat_id
  end
end

class Cat < ActiveRecord::Base
  has_many :dogs
end

class Dog < ActiveRecord::Base
  belongs_to :cat
end

Thread.start do
  loop do
    p GC.stat[:heap_live_slots]
    sleep 1
  end
end

cat = Cat.create!

i = 0
loop do
  uid = i.to_s

  # (1) Leaks
  dog = cat.dogs.new(uid: uid)

  # (2) Does not leak
  #dog = Dog.new(cat: cat, uid: uid)

  # (3) Also does not leak:
  #cat = Cat.first
  #dog = cat.dogs.new(cat: cat, uid: uid)

  # (4) Also does not leak:
  #dog = cat.dogs.scoping { cat.dogs.klass.new(uid: uid) }

  i += 1
  if i % 100 == 0
    GC.start
  end
end
```

Sample run:

```shell
$ ruby leak.rb
-- create_table(:cats, {:force=>true})
   -> 0.0206s
-- create_table(:dogs, {:force=>true})
   -> 0.0009s
143273
155981
129954
157154
180954
233069
226854
247254
293332
341468
351157
323754
342454
359454
378154
432682
458494
476618
483722
465068
471654
...
```

### Expected behavior
Should not leak memory.

### Actual behavior
Does leak quite a lot of memory over time. On my machine the above test case consumes about 100MB per minute.

It is my understanding that `new` is not stateful. However, the leak goes away if I always choose a new object to build on. The leak also doesn't happen if I do exactly what ActiveRecord is supposedly doing itself:

```ruby
dog = cat.dogs.scoping { cat.dogs.klass.new(uid: uid) }
```

That's how `new` is implemented.

### System configuration
**Rails version**: 5.0.2
**Ruby version**: 2.2.2, 2.3.3

**Comment by al2o3cr** [comment]
I don't think this is a bug. `dog = cat.dogs.new(uid: uid)` will result in the record being retained in the association - try printing `cats.dogs.length` inside the loop to see what I mean.

**Comment by atombender** [comment]
Thanks. That's not explained by the documentation (it just says the returned record is linked to the parent through the foreign key or join table), and it's also extremely unclear from the code that it's stateful.
