### ISSUE TITLE
rails secrets:edit fails on $EDITOR=atom

### ISSUE THREAD

**Issue by tmilewski** [rails/rails#28396]
When running `rails secrets:edit`, the save watcher abruptly ends during Atom's startup process.

*A file* still opens but nothing will be saved as the watcher has already ended.

### Steps to reproduce

`EDITOR=vim rails secrets:edit` - Triggers vim; works as expected.
`EDITOR=atom rails secrets:edit` - Triggers atom; Watcher thinks the file has been saved and immediately ends.

### Expected behavior
With Atom, the watcher should continue to watch for a user-invoked save.

### Actual behavior
With Atom, the watcher ends during Atom's startup process.

### System configuration

- Ruby: 2.3.1
- Rails: 5.1.0.beta1
- Atom: 1.12.7

**Comment by y-yagi** [comment]
I think you need `EDITOR='atom --wait'`.

**Comment by maclover7** [comment]
Agree with @y-yagi, you need to add the `--wait` flag to your `EDITOR` environment variable. See [here](https://github.com/rails/rails/blob/master/railties/lib/rails/commands/secrets/secrets_command.rb#L26) for more details.

**Comment by belgoros** [comment]
I still have the same issue on a fresh Rails `5.2.3` app.
Tried to run as described earlier by @y-yagi by just uncommenting the default `aws`values and got:
<img width="1029" alt="Screenshot 2019-09-19 at 16 47 31" src="https://user-images.githubusercontent.com/83579/65254923-4a524f00-dafd-11e9-91fb-eb1707ebccbd.png">

**Comment by belgoros** [comment]
It did work with Sublime Text when running `EDITOR="subl --wait" rails credentials:edit`.
