### ISSUE TITLE
 validates uniqueness: with case_sensitive: false and  scope: :organization_id seems not working

### ISSUE THREAD

**Issue by mberrueta** [rails/rails#28400]
### Steps to reproduce
 I have this model 
```
class Tag < ActiveRecord::Base
  belongs_to :organization
  validates :name, :organization, presence: true
  validates :name, uniqueness: { case_sensitive: false, scope: :organization_id }
end
```
```
create_table "tags", id: :uuid, default: -> { "uuid_generate_v4()" }, force: :cascade do |t|
    t.string   "name",                        null: false
    t.uuid     "organization_id",             null: false
    t.index ["name", "organization_id"], unique: true, using: :btree
  end
```

and in my db
```
[#<Tag:0x0055deb3ac0d40
  id: "c22e344c-010b-4ae3-8575-deb0b51ed99c",
  name: "event",
  organization_id: "1e499977-3bc6-4e39-b453-471642d4b560",
 #<Tag:0x0055deb3ac0c00
  id: "2d0f9dff-cbc2-46ec-979e-56b5ae5917a2",
  name: "event",
  organization_id: "97a7d2bf-4ff6-4901-9207-45053348f220",
 #<Tag:0x0055deb3ac0ac0
  id: "24ceedcd-00b4-4919-8da2-5fe76394cef5",
  name: "event",
  organization_id: "70c96725-ffc3-4e66-9525-2fc13d6c3ee8",
]
```

### Expected behavior
when I call 
`Tag.new(name: 'event', organization_id: '40f678ee-9f7a-4a51-ba73-bc09b1fa4a1d').save!`

should allow me to save it (is not there with the name `event` and for this organization)

### Actual behavior
I get a 
`ActiveRecord::RecordInvalid: Validation failed: Name has already been taken`

also: if I remove the `case_sensitive` flag, it works (and also make the validation without case)

### System configuration
**Rails version**:
Rails 5.0.1
ruby 2.3.2p217 (2016-11-15 revision 56796) [x86_64-linux]
db postgress
  psql (PostgreSQL) 9.6.2

**Comment by al2o3cr** [comment]
Can you post the SQL generated when you execute the statement above? Something seems to be going wrong when generating the query to check uniqueness.

**Comment by mberrueta** [comment]
Sorry I can reproduce again, probably something bad in my db or with `paranoia` gem
