### ISSUE TITLE
Can't decode encrypted text with 2.3.0 with 2.4.0

### ISSUE THREAD

**Issue by benoittgt** [rails/rails#28401]
### Steps to reproduce

```ruby
# Ruby 2.3.0
key = (0...128).map { ('a'..'z').to_a[rand(26)] }.join
# "aqdenhhmdgnhpbpwunqfhpvbgvdqzjojubnwcufyzldjqhdwemvkjeadrdykhthcgbetrwhoalrrfkttgpipmjkxazwwlriwudghpticiubpmodwqagjmrgsdqkfvcam"
ActiveSupport::MessageEncryptor.new(key).encrypt_and_sign("MyTextIsLong")
"TW52TURHYjhlK2hyTEppL05kbThoU1Q4bmtBZEcrZW42QTJIUFZPeHVlVT0tLXNUcHlkakcyMnhOZzNqRFVJUDdIRWc9PQ==--6aea682ea412fae46ec92a1d73548ea85a8190b3"
```
No problem on the first part. I discovered with the recent update that longer keys are truncated in OpenSSL and invalid size now raise an error (https://github.com/ruby/openssl/issues/116#issuecomment-286115710). 
With the update of Ruby 2.4.0 I will have to encrypt with key size of 32 bytes otherwise OpenSSL will raise an error.

```ruby
# Ruby 2.4.0
same_key = "aqdenhhmdgnhpbpwunqfhpvbgvdqzjojubnwcufyzldjqhdwemvkjeadrdykhthcgbetrwhoalrrfkttgpipmjkxazwwlriwudghpticiubpmodwqagjmrgsdqkfvcam"
previously_encrypted_text = "TW52TURHYjhlK2hyTEppL05kbThoU1Q4bmtBZEcrZW42QTJIUFZPeHVlVT0tLXNUcHlkakcyMnhOZzNqRFVJUDdIRWc9PQ==--6aea682ea412fae46ec92a1d73548ea85a8190b3"
ActiveSupport::MessageEncryptor.new(same_key).decrypt_and_verify(previously_encrypted_text)
# ActiveSupport::MessageEncryptor::InvalidMessage: ActiveSupport::MessageEncryptor::InvalidMessage
#	from /Users/bti/.rvm/gems/ruby-2.4.0/gems/activesupport-4.2.8/lib/active_support/message_encryptor.rb:103:in `rescue in _decrypt'
#	from /Users/bti/.rvm/gems/ruby-2.4.0/gems/activesupport-4.2.8/lib/active_support/message_encryptor.rb:91:in `_decrypt'
#	from /Users/bti/.rvm/gems/ruby-2.4.0/gems/activesupport-4.2.8/lib/active_support/message_encryptor.rb:66:in `decrypt_and_verify'
```
The error is related to key size. [When catching the exception](https://github.com/rails/rails/blob/4-2-stable/activesupport/lib/active_support/message_encryptor.rb#L103), it refers to key size `#<ArgumentError: key must be 32 bytes>`.

But when you truncate key size and try to decrypt encrypted text on 2.3.0 with 128 bytes key, it leads to `InvalidSignature` :

```ruby
32_bytes_key = key[0..31]
ActiveSupport::MessageEncryptor.new(32_bytes_key).decrypt_and_verify(encoded)
# ActiveSupport::MessageVerifier::InvalidSignature:  ActiveSupport::MessageVerifier::InvalidSignature
#	from /Users/bti/.rvm/gems/ruby-2.4.0/gems/activesupport-4.2.8/lib/active_support/message_verifier.rb:50:in `verify'
#	from /Users/bti/.rvm/gems/ruby-2.4.0/gems/activesupport-4.2.8/lib/active_support/message_encryptor.rb:66:in `decrypt_and_verify'
```

Normally we should not have an issue. But I can no longer decode new version of the text encoded with the previous ruby version.

```ruby
data, digest = previously_encrypted_text.split('--')
# => ["T09WTGJ4Y0dhbFEycUJZUHVnWmFXSmtPY1N3OVVodjhIMUxwNVA5bkI0UT0tLUZ1bHR0WWpGa1FMVllPYXVwUkpXTEE9PQ==", "d3ac1eb8fcedd0f5703422fdcd9bed0a40a8bc6d"]

generate_digest = ActiveSupport::MessageVerifier.new(key).send(:generate_digest, data)
# => "d3ac1eb8fcedd0f5703422fdcd9bed0a40a8bc6d"
ActiveSupport::SecurityUtils.secure_compare(digest, generate_digest)
# => false
```

[`secure_compare`](https://github.com/rails/rails/blob/4-2-stable/activesupport/lib/active_support/message_verifier.rb#L41) does not validate the generate_digest/digest.

You need to use the previous longer key to validate : 
```ruby
ActiveSupport::SecurityUtils.secure_compare(digest, ActiveSupport::MessageVerifier.new(32_bytes_key).send(:generate_digest, data))
# => false
ActiveSupport::SecurityUtils.secure_compare(digest, ActiveSupport::MessageVerifier.new(key).send(:generate_digest, data))
# => true
```

### Expected behavior
I would like to be able to decode text encoded on Rails 4.2.8+2.3.0 on 4.2.8+2.4.0. 

I know this issue is related to ruby 2.4.0 but also with the rails implementation. I may have miss a simple way of doing it but after hours I can't figure out.

There is a sort of mix between ruby key validation size needed for `cipher.key` inside `MessageEncryptor` and what is used inside `ActiveSupport::MessageVerifier#generate_digest`. It needs the encoding key at the right size (32) for `ActiveSupport::MessageEncryptor.new(key)` but the full key (used for encryption on 2.3.0) for `OpenSSL::HMAC.hexdigest(OpenSSL::Digest.const_get(@digest).new, @secret, data)` ([source](https://github.com/rails/rails/blob/4-2-stable/activesupport/lib/active_support/message_verifier.rb#L69))

### System configuration
**Rails version**:
4.2.8
**Ruby version**:
2.3.0 then 2.4.0

Thanks in advance for the help.

**Comment by rafaelfranca** [comment]
@matthewd @jeremy do you have any idea on how to fix this since you reviewed the PRs that changed this implementation to 2.4?

**Comment by benoittgt** [comment]
This not an issue. Their is a test to validate this kind of behaviour.

https://github.com/rails/rails/blob/4-2-stable/activesupport/test/message_encryptor_test.rb#L58-L66

This part is simply not documented. I'm gonna make a PR for that.
