### ISSUE TITLE
Global vars defined in javascripts folder get lost in production

### ISSUE THREAD

**Issue by LouisSayers** [rails/rails#28408]
### Steps to reproduce

Create a rails app which defines a global var in a javascript file. Include javascript in page via a manifest file, reference global var in an html page, precompile assets, run in production, and watch for a console error. 

I've created an example app to show the error: 

[https://github.com/LouisSayers/rails-assetpipeline-js-bug](https://github.com/LouisSayers/rails-assetpipeline-js-bug)

### Expected behavior
The global variable should be accessible on the html page.

### Actual behavior
A console error occurs `Uncaught ReferenceError: <GlobalVarName> is not defined`

### System configuration
**Rails version**: 5.1.0.beta1

**Ruby version**: 2.4.0

**Comment by strangeworks** [comment]
I'm not sure but, as far as I know webpack doesn't not expose global variables by default and as rails 5.1.0.beta1 use webpack in order to expose global variable try to use:
```javascript 
window.varName = 'value'
```
