### ISSUE TITLE
[Rails 4.2.8][Ruby 2.4] to_time doesn't preserve time zone

### ISSUE THREAD

**Issue by yivo** [rails/rails#28411]
### Steps to reproduce
```ruby
begin
  require "bundler/inline"
rescue LoadError => e
  $stderr.puts "Bundler version 1.10 or later is required. Please update your Bundler"
  raise e
end

gemfile(true) do
  source "https://rubygems.org"
  # Activate the gem you are reporting the issue against.
  gem "activesupport", "4.2.8"
end

require "active_support/all"
require "minitest/autorun"

# Ensure backward compatibility with Minitest 4
Minitest::Test = MiniTest::Unit::TestCase unless defined?(Minitest::Test)

class BugTest < Minitest::Test
  def test_time_to_date_to_time_preserves_time_zone_using_time_zone_parse
    ActiveSupport.to_time_preserves_timezone = true
    Time.zone = "Kyiv"
    t1 = Time.zone.parse("2017-03-17 14:40:00 +0200")
    d  = t1.to_date
    t2 = d.to_time

    assert_equal "EET", t1.zone.to_s
    assert_equal "EET", t2.zone.to_s    
    assert_equal "2017-03-17 14:40:00 +0200", t1.to_s
    assert_equal "2017-03-17 00:00:00 +0200", t2.to_s
  end
  
  def test_time_to_date_to_time_preserves_time_zone_using_time_zone_local
    ActiveSupport.to_time_preserves_timezone = true
    Time.zone = "Kyiv"
    t1 = Time.zone.local(2017, 03, 17, 14, 40, 00)
    d  = t1.to_date
    t2 = d.to_time

    assert_equal "EET", t1.zone.to_s
    assert_equal "EET", t2.zone.to_s    
    assert_equal "2017-03-17 14:40:00 +0200", t1.to_s
    assert_equal "2017-03-17 00:00:00 +0200", t2.to_s
  end
end
```

### Expected behavior
`Time.zone.parse("2017-03-17 14:40:00 +0200")` must preserve time zone.

### Actual behavior
Time zone isn't preserved, local used instead.

### System configuration
**Rails version**: 4.2.8

**Ruby version**: 2.4.0

**OS**: OS X 10.12.2

**Comment by yivo** [comment]
Currently I am using `date.to_time.in_time_zone` to fix this in my project.

**Comment by pixeltrix** [comment]
@yivo does `Time.zone.parse` preserve the time zone on master - I don't think it does. The compatibility is around the `to_time` method change in Ruby 2.4.

**Comment by yivo** [comment]
I have added `Time.zone.local` to `BugTest`. (`test_time_to_date_to_time_preserves_time_zone_using_time_zone_local`)

```
# Running:

FF

Finished in 0.046794s, 42.7404 runs/s, 85.4808 assertions/s.

  1) Failure:
BugTest#test_time_to_date_to_time_preserves_time_zone_using_zone_local [bug_test.rb:42]:
--- expected
+++ actual
@@ -1 +1,2 @@
-"EET"
+# encoding: US-ASCII
+"UTC"



  2) Failure:
BugTest#test_time_to_date_to_time_preserves_time_zone_using_time_zone_parse [bug_test.rb:29]:
--- expected
+++ actual
@@ -1 +1,2 @@
-"EET"
+# encoding: US-ASCII
+"UTC"
```

**Comment by yivo** [comment]
Please let me know if I can help resolve this issue.

**Comment by yivo** [comment]
Test fails in `4-2-stable`, `5-0-stable` and `master`

**Comment by pixeltrix** [comment]
@yivo is your issue with `Date#to_time`? If so I can't see how it can preserve the timezone since it doesn't have one when it's a date.

**Comment by pixeltrix** [comment]
If you just want a date converted to a time in the configured `Time.zone` then you can directly do `date.in_time_zone` and not go through `to_time`.  The `to_time_preserves_timezone` is purely about handling the difference between `Time#to_time` in Ruby 2.3 and Ruby 2.4 where the latter returns `self` instead of always calling `getlocal` as it did previously in 2.3 and earlier.

**Comment by azeezahmed** [comment]
Hi, Let me explain what is going on here,

- ActiveSupport.to_time_preserves_timezone introduces a new behavior that lets us enable/disable preserving of time zone when .to_time methods are used.[(link to code)](https://github.com/rails/rails/blob/v4.2.8/activesupport/lib/active_support/core_ext/date_and_time/compatibility.rb)

- This new feature overrides .to_time method from Classes DateTime, Time and ActiveSupport::TimeWithZone only.

-  When we convert a Time/DateTime object to Date object the result will only hold year, month and date.

- Hence when a date object is converted to time, time defaults to the beginning of the day and timezone defaults to local (or it can be UTC). [(link to code)](https://github.com/rails/rails/blob/v4.2.8/activesupport/lib/active_support/core_ext/date/conversions.rb)

**Comment by pixeltrix** [comment]
@yivo as @azeezahmed helpfully explained - it's not possible to preserve timezones when converting from a date to a time so this is as expected. Thanks for your report.

**Comment by yivo** [comment]
@pixeltrix @azeezahmed Thank you guys!
