### ISSUE TITLE
Generator logs incorrectly removes all the "app" from the paths

### ISSUE THREAD

**Issue by christophemaximin** [rails/rails#28418]
### Steps to reproduce
    
    # Commands executed from ruby:2.4.0 docker image with:
    # docker run -it ruby:2.4.0 bash
    gem install rails -v 5.1.0.beta1
    cd / && rails new app --skip-javascript && cd /app && rails g controller articles

### Expected behavior

The logs should show:

    create  app/controllers/articles_controller.rb
    invoke  erb
    create    app/views/articles
    invoke  test_unit
    create    test/controllers/articles_controller_test.rb
    invoke  helper
    create    app/helpers/articles_helper.rb
    invoke    test_unit
    invoke  assets
    invoke    js
    create      app/assets/javascripts/articles.js
    invoke    scss
    create      app/assets/stylesheets/articles.scss

### Actual behavior

The logs do show (notice the missing 'app' in the paths):

    create  /controllers/articles_controller.rb
    invoke  erb
    create    /views/articles
    invoke  test_unit
    create    test/controllers/articles_controller_test.rb
    invoke  helper
    create    /helpers/articles_helper.rb
    invoke    test_unit
    invoke  assets
    invoke    js
    create      /assets/javascripts/articles.js
    invoke    scss
    create      /assets/stylesheets/articles.scss

NOTE: All the files are correctly created, e.g. `/app/app/controllers/articles_controller.rb` exists as it should.

### System configuration
**Rails version**: 5.1.0.beta1  
**Ruby version**: 2.4.0p0 (2016-12-24 revision 57164) [x86_64-linux]

**Comment by maclover7** [comment]
@christophemaximin I think this is an upstream issue with Thor -- can you open up an issue on Thor's [issue tracker](https://github.com/erikhuda/thor)?
