### ISSUE TITLE
Docs incorrectly refer to uniqueness being a default rails validator

### ISSUE THREAD

**Issue by jmwelch** [rails/rails#28439]
### Docs
In multiple places throughout the Rails docs, `ActiveModel::Validations` refers to `uniqueness` being a default rails validator. This does not appear to be the case, understandably because ActiveModel has no database in which to ensure uniqueness.

Examples:

- [api.rubyonrails.org](http://api.rubyonrails.org/classes/ActiveModel/Validations/ClassMethods.html#method-i-validates) in 3 places

- [Rails GitHub](https://github.com/rails/rails/blob/master/activemodel/lib/active_model/validations/validates.rb) master branch (and others), lines 21, 37, and 97.

### Code
Related, it would be nice to be able to specify an ActiveRecord class to which we'd like to claim uniqueness. Something like:
```
validates :email, uniqueness: true, class_name: "User"
```
seems to make sense.

**Comment by azeezahmed** [comment]
Hi jmwelch, I could see where you're coming from. 

However, the scope of the mentioned lines is to explain the shorthand [validates method]( http://api.rubyonrails.org/classes/ActiveModel/Validations/ClassMethods.html#method-i-validates ) and what are the available options for it. And I find it convenient if all the options available are listed here.

**Comment by jmwelch** [comment]
The scope is `ActiveModel`, in which `uniqueness` is not an available default option.

If you look at [ActiveRecord](http://api.rubyonrails.org/classes/ActiveRecord/Validations/ClassMethods.html) validations, `uniqueness` is listed, which is correct.

**Comment by azeezahmed** [comment]
I do understand that uniqueness has more to do with ActiveRecord than ActiveModel however if we drill down to sub-scope of ActiveModel which is explaining [validates](http://api.rubyonrails.org/classes/ActiveModel/Validations/ClassMethods.html#method-i-validates) shorthand, having uniqueness there doesn't seem incorrect as it is one of the valid options for it.

And I would not expect validates shorthand documentation under [ActiveRecord](http://api.rubyonrails.org/classes/ActiveRecord/Validations/ClassMethods.html) (if that's what your suggesting) as it is an ActiveModel thing.

**Comment by maclover7** [comment]
Hi @jmwelch! I agree with you that it's not great that `unique` is listed as a "Rails default validator". However, this is one of the most popular validators, and I agree with @azeezahmed that it makes sense to include it in the large list in the Active Model documentation.

**Comment by LiamKeene** [comment]
Everyone is making valid points, but the code examples in the documentation are wrong.

`[2] pry(main)> class Person
[2] pry(main)*   include ActiveModel::Validations
[2] pry(main)*   attr_accessor :name
[2] pry(main)*
[2] pry(main)*   validates :name, presence: true, uniqueness: true, length: { maximum: 100 }
[2] pry(main)* end
ArgumentError: Unknown validator: 'UniquenessValidator'`

If you came to this page with the intention to create a non-DB backed class with validations for its attributes you would be led astray.  Including ActiveModel::Validations does not mean you can use the uniqueness validator.  You would have to write your own method for validating uniqueness of an attribute of your class.
