### ISSUE TITLE
ActiveSupport::TimeZone.country_zones(country_code) fails to find valid Alpha2

### ISSUE THREAD

**Issue by darrennix** [rails/rails#28431]
### Steps to reproduce
```
ActiveSupport::TimeZone.country_zones('GT')
ActiveSupport::TimeZone.country_zones('SV')
```
### Expected behavior
Guatemala and El Salvador share the same time zone ("Central America") and should return the same TZInfo response array.

### Actual behavior
```
ActiveSupport::TimeZone.country_zones('GT')
=> [#<ActiveSupport::TimeZone:0x007ff9f0c61c08 @name="Central America", @utc_offset=nil, @tzinfo=#<TZInfo::DataTimezone: America/Guatemala>>]
ActiveSupport::TimeZone.country_zones('SV')
=> []
```

### Cause
https://github.com/rails/rails/blob/master/activesupport/lib/active_support/values/time_zone.rb

The underlying reason seems to be that ActiveSupport::TimeZone::MAPPING is only a partial mapping of TZinfo identifiers: "Keys are Rails TimeZone names, values are TZInfo identifiers."   As a result, country_zones() will return the correct response only if a Rails TimeZone name is not shared by multiple countries.

### Version
ruby 2.3.3p222
activesupport (= 5.0.2)
tzinfo (1.2.2)

**Comment by azeezahmed** [comment]
- SV is officially assigned country code for [America/El_Salvador](https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2#SV)

- Also Verified that TZInfo returns as below

`TZInfo::Country.get('SV').zone_identifiers`

`=> ["America/El_Salvador"]`

- However, Mapping used in [time_zone.rb](https://github.com/rails/rails/blob/v5.0.2/activesupport/lib/active_support/values/time_zone.rb) seems to be missing:
` "Central America"              => "America/El_Salvador"`

**Comment by espen** [comment]
See https://github.com/rails/rails/issues/12461#issuecomment-25874610

**Comment by rafaelfranca** [comment]
@pixeltrix could you review this?

**Comment by azeezahmed** [comment]
After going through #12461, I would agree with @pixeltrix 
As he stated that "The main purpose of MAPPING is to build the options list for time_zone_select" 

And it also says in the documentation that it "Limits the set of zones provided by TZInfo to a meaningful subset of 146 zones." ( which seem more readable to me)

If these 146 defined zones cover everything then it shouldn't be a problem and if at all we need to be specific with a time zone we should be calling out TZInfo.

**Comment by pixeltrix** [comment]
This is fixable - working on it

**Comment by sgringwe** [comment]
@pixeltrix FWIW, this was a breaking change for our app that we are having to build in a workaround for. We validate `validates :time_zone, inclusion: { in: ActiveSupport::TimeZone.all.map(&:name) }` for any time zone field and by adding time zones to `ActiveSupport::TimeZone.us_zones` that aren't in `ActiveSupport::TimeZone.all`, it causes validation issues for new records.

Would it be possible to revert the behavior of `us_zones` to its previous and introduce a new method, perhaps `all_us_zones` for this new behavior to avoid the breaking change?

**Comment by pixeltrix** [comment]
@sgringwe I don't want to revert since it does fix a bug but I'm pretty sure I can come up with a way for `us_zones` to return what it did previously. I would suggest that using Rails timezone shorthand name in the database as opposed to a proper zone identifier is not a great idea though.

Can you open a new issue and cc me, thanks.

**Comment by BigGillyStyle** [comment]
@pixeltrix In Rails 5.0.2 and prior we used the following method to provide the "available time zones" for our app:

`(ActiveSupport::TimeZone.us_zones + [ActiveSupport::TimeZone.all - ActiveSupport::TimeZone.us_zones]).flatten.uniq`

That logic has been in place untouched since February 25, 2014 (according to git blame).  As of Rails 5.0.3 this now returns a different array of zones.  I suspect this is the same issue that @sgringwe mentioned in his comment?

**Comment by BigGillyStyle** [comment]
@pixeltrix and @sgringwe 
I have filed an issue here: https://github.com/rails/rails/issues/29210

**Comment by BigGillyStyle** [comment]
@sgringwe 
Could you share your workaround for getting the `us_zones` to behavior as before?

**Comment by sgringwe** [comment]
@BigGillyStyle it's basically a copy/paste from old version:

```
def self.basic_us_zones
    @_basic_us_zones ||= begin
      TZInfo::Country.get('US').zone_identifiers.map do |tz_id|
        name = ActiveSupport::TimeZone::MAPPING.key(tz_id)
        name && ActiveSupport::TimeZone[name]
      end.compact.sort!
    end
  end
```
