### ISSUE TITLE
has_secure_password validations can not be conditionally skipped per user

### ISSUE THREAD

**Issue by rhetoric** [rails/rails#28433]
I have a User model where there is a 'guest' flag that is used when creating short lived 'guest' Users that do not have/need passwords. There does not seem to be a straight forward way to use has_secure_password for normal users with passwords and to skip/ignore password validations for 'guest' users.

Given a basic user table:
```
create_table "users", force: :cascade do |t|
  t.string   "email"
  t.string   "password_digest"
  t.boolean  "guest"
  ...
end
```
and the following setup in the User model:
```
class User < ApplicationRecord 
  has_secure_password validations: -> { member? }  # <-- does nothing, same as no options
  # has_secure_password validations: :member?  # <-- does nothing, same as no options
  # has_secure_password validations: false  # <-- works fine, but impacts all normal users

  def member?
    !guest?
  end
end
```

trying to save a guest user:
```
norm_user = User.new email: 'user@example.com', password: 'pass', password_confirmation: 'pass'
norm_user.save # all good

guest_user = User.new email: 'guest@exampe.com', guest: true
guest_user.save # errors.full_messages: ["Password can't be blank"]
```
I get it, has_secure_password is a class method and only run once on model activation/instantiation... but shouldn't a proc or method or something be allowed to be passed into the validations option to be run/checked against for each individual user?

As it stands my options seem to be:
- just auto add a random password to each guest user (what I am currently doing)
- use ```has_secure_password validations: false```, then manually re-setup all password validations with conditions as needed
- inherit/subclass User/GuestUser/NormalUser

Is there a more straight forward way to configure the User model to conditionally skip password validations per user/record?

### System configuration
**Rails version**: 5.0.1

**Ruby version**: ruby 2.4.0p0 (2016-12-24 revision 57164) [x86_64-darwin16]

**Comment by musicmage4114** [comment]
Hey there!

This sounds like a support request, rather than a bug report. If you're looking for advice or a better way of doing things, I would suggest you ask a question over at [StackOverflow](https://stackoverflow.com/) to receive a quality answer.

If you feel like you're experiencing incorrect behavior, you may want to revise your issue to highlight that, noting in particular the expected versus actual behavior. [Here's a brief guide](https://coenjacobs.me/2013/12/06/effective-bug-reports-on-github/) to writing effective bug reports if you need some guidance.

Happy coding!

**Comment by rhetoric** [comment]
Sorry, ya, was quite hesitant to create the issue as it does come across more supportish. Was only because I couldn't really think of an actual situation where someone would want to use the validations: false option for all users all the time, other than in the conditional sense I described... made me wonder if it was fully intended to work that way.
