### ISSUE TITLE
rake doc:rails for ActiveRecord 4.2.8 is empty

### ISSUE THREAD

**Issue by adas172002** [rails/rails#28434]
### Steps to reproduce

Hey,

just noticed that locally generated documentation for RoR 4.2.8 is missing everything related to ActiveRecord. 

### Expected behavior
There should be docs for ActiveRecord
### Actual behavior
There is no folder doc/api/classes/ActiveRecord and index file has only `test_help.rb` mixin link

### System configuration
**Rails version**: 4.2.8

**Ruby version**: 2.2.1

**Comment by maclover7** [comment]
Hi @adas172002! All of the documentation Rake tasks were removed from Rails in v5.0.0, and 4-2-stable is pretty much in "security fixes only" mode 😬 😬 

cc @fxn

**Comment by adas172002** [comment]
Hi @maclover7 
I am aware that in RoR since version 5 generating local copy of rails doc is deprecated. Justification for this removal is easy access to online docs like [APIdock](https://apidock.com/rails). On the other hand, the newest release documented on APIDock is 4.2.7. So the current status as of the time I am writing this is that 2 recent releases (4.2.8 and 5.0.x) of RoR do not have API documentation available. 

BTW: could it be that the reason for stale APIDock rails docs is removal of doc:rails task?

**Comment by rafaelfranca** [comment]
@adas172002 APIdock is not the official documentation website. The official documentation website is always using the latest Rails version http://api.rubyonrails.org/v4.2/.

**Comment by adas172002** [comment]
Thanks for the info. I was not aware that API docs for other releases are also available online. Is there a link from official web page?

**Comment by rafaelfranca** [comment]
Yes. The only official API documentation for Rails is http://api.rubyonrails.org.
