### ISSUE TITLE
Question about description and code in the chapter "Action View Overview" of RailsGuide

### ISSUE THREAD

**Issue by jun68ykt** [rails/rails#28435]
### Steps to reproduce

&nbsp;Hello. Now I read RailsGuide for using Rails more effectively and I found an unclear point in which sample codes might be  an error in writing. So I post this issue.

&nbsp;Following codes and descriptions between two lines are sited from the section <b>3.2.4 The as and object options</b> in [3.2 Partials of the chapter "Action View Overview"](http://guides.rubyonrails.org/action_view_overview.html#partials) .

<hr />

**3.2.4 The as and object options**

By default ```ActionView::Partials::PartialRenderer``` has its object in a local variable with the same name as the template. So, given:

```ruby
<%= render partial: "product" %>
```
within ```_product``` partial we'll get ```@product``` in the local variable ```product```, as if we had written:

```ruby
<%= render partial: "product", locals: { product: @product } %>
```
<hr />

### Expected behavior

Descriptions above tell us that:

```ruby
<%= render partial: "product" %>
```
make us be able to use local variable ```product``` referring to ```@product```  in partial ```_product.html.erb```.

### Actual behavior
But when I tried to verify the descriptions above by writing some ERB like ```show.html.erb``` e.g.   including
```ruby
<%= render partial: "product" %>
```
and partial ```_product.html.erb``` including a code using local variable ```product``` like 
```ruby
<%= product.id %>
```

and tried to render this ```show.html.erb``` from an action to use these ERBs, I got the error message like: 

```ruby
undefined local variable or method `product' for #<#<Class:0x007f95239429c8>:0x007f9523828a38>

```

So, I think that the sample code:

```ruby
<%= render partial: "product" %>
```
written in RailsGuide is an error in writing and 

```ruby
<%= render @product %>
```
is correct. How about it? 

Regards.

### System configuration
**Rails version**: 5.0.2

**Ruby version**: 2.2.6p396

**Comment by jun68ykt** [comment]
FYI, I commited my guess into my forked rails as https://github.com/jun68ykt/rails/commit/13ff821687430a3879f878fa13061e662ac21298 .

**Comment by st0012** [comment]
That part of documents was written about 4 or 5 years ago ([check here](https://github.com/rails/rails/blame/master/guides/source/action_view_overview.md#L242)). And there are no tests about this behavior. So I think this behavior was deprecated without updating documents?

**Comment by st0012** [comment]
I found the [commit](https://github.com/rails/rails/commit/c67005f221f102fe2caca231027d9b11cf630484) that deprecated this behavior.
@jun68ykt I think you can open a PR for your change.

**Comment by jun68ykt** [comment]
@st0012 Thank you for your answer. I understand the status of that part in documents and the related commit.
