### ISSUE TITLE
ActionDispatch remote_ip returns wrong client IP when deployed internally behind a load balancer/reverse proxy

### ISSUE THREAD

**Issue by jkuchta** [rails/rails#28436]
### Steps to reproduce
Create a rails app with a page that outputs request.remote_ip. Set your X-Forwarded-For header to a private IP (ex. 10.1.0.1). The IP displayed will not match the X-Forwarded-For header unless it is a non-private IP.

### Expected behavior
This should be configurable, I'm sure there are many instances of Rails being run internally as a service (behind a reverse proxy or load balancer). In these instances, all client IPs are being reported incorrectly as the IP of the proxy or load balancer.

### Actual behavior
The remote_ip being reported is from the load balancer or proxy.

### System configuration
**Rails version**: 4.x, 5.x

**Ruby version**:
2.3.x

**Comment by maclover7** [comment]
Very similar issue opened at #27942

cc @rafaelfranca

**Comment by pixeltrix** [comment]
@jkuchta the `remote_ip` method uses the `RemoteIp` middleware to make a best-attempt at finding the IP address of the client that made the request. Since many Rails apps are proxied behind load balancers with private internal IP addresses we ignore those addresses.

If you need a different method of calculating the remote IP address remove the `RemoteIp` middleware and add your own that behaves in the way you need.

**Comment by jkuchta** [comment]
@pixeltrix I understand what remote_ip is trying to do and I think it makes sense in some cases. I also think that many users would see a benefit in this method following the standard behavior for forwarded IPs instead of guessing. 

For such a simple change I don't see why a configuration option is not the preferred option compared to creating an entirely new middleware (note: this is disabled by default and has zero impact). This RemoteIp already has a few configuration options to alter behavior ex. trusted_proxies. 

Would you be open to re-opening this so we can continue the discussion and/or get additional feedback?

**Comment by matthewd** [comment]
There's no need for configuration here.

@jkuchta if you're up for resuscitating https://github.com/rails/rails/pull/14600, I believe that will do what you want automatically.

**Comment by jkuchta** [comment]
@matthewd, I don't disagree with your PR but there might be some indivuals that rely on the current behavior which is why I prefer configuration for this change.

**Comment by matthewd** [comment]
The current behaviour is broken, and doesn't make sense. The possibility of people depending on bugs doesn't preclude those bugs being fixed.

More importantly: I'll merge a change that fixes said misbehaviour; the proposed config option is both problematic (it actively ignores untrusted intermediates, making it only usable for people who *only* see all-internal requests), and disproportionate for the edge case it's addressing. I'm not even going to touch "that is probably accurate".

If you want the blindly-take-first behaviour from your PR, the right solution is indeed to replace RemoteIp with your own trivial middleware. We're not going to offer such a foot-gun as a built-in option.

**Comment by jkuchta** [comment]
@matthewd foot-gun is a bit harsh for adding a configuration option to follow the standard for X-Forwarded-For. The current implementation is over engineered to solve a problem it shouldn't be responsible for.
