### ISSUE TITLE
Model.any? uses a SELECT COUNT(*) query rather than a SELECT 1 query

### ISSUE THREAD

**Issue by pachonk** [rails/rails#28456]
### Steps to reproduce
```
[4] pry(main)> User.any?
   (2.5ms)  SELECT COUNT(*) FROM "users"
=> true
[5] pry(main)> User.exists?
  User Exists (0.4ms)  SELECT  1 AS one FROM "users" LIMIT $1  [["LIMIT", 1]]
=> true
```

### Expected behavior
`Model.any?` should check first for the cache (it already does), then use `SELECT 1`, rather than `SELECT COUNT(*)`

### Actual behavior
`Model.any` checked cache first, then uses `SELECT COUNT(*)` which is less efficient than `SELECT 1`.

### System configuration
**Rails version**: 5.0.2

**Ruby version**: 2.3.3

**Comment by pachonk** [comment]
Additional source: https://semaphoreci.com/blog/2017/03/14/faster-rails-how-to-check-if-a-record-exists.html

**Comment by matthewd** [comment]
We don't accept feature requests in the issue tracker, but this is already done: 02da8aea832485044fde1b94c021a66d37d54dec

**Comment by pachonk** [comment]
@matthewd Yeah, I learned this and went to close this issue just as I got the notification. I'm sorry.
