### ISSUE TITLE
Rake Task not including app/lib properly

### ISSUE THREAD

**Issue by jockmac22** [rails/rails#28452]
We recently upgrade from Rails 4.x to 5.0.2.  During this process, we moved our application dependencies from the `lib/` directory to the `app/lib` directory as per this discussion:

https://github.com/rails/rails/issues/13142

This fixed issues we were having in the application on production. But now our tasks are failing because those tasks have the same dependencies and they aren't loading properly.

We have a task file that gives us some helper tasks to rebuild and update our database.

```
namespace :db do
  task :rebuild_environment => :environment do |t, args|
    if Rails.env.test? || Rails.env.development? || Rails.env.banzai?
      run_task "db:drop"
      run_task "db:create"
      run_task "db:migrate"
      run_task "db:schema:cache:clear"
      run_task "db:germinate"
    else
      puts ""
      puts "This task can only be run in the development and test environments"
      puts ""
    end
  end

  # Short alias for rebuild environment
  task :re => :environment do |t, args|
    run_task "db:rebuild_environment"
  end

  task :update_environment => :environment do |t, args|
    run_task "db:migrate"
    run_task "db:germinate"
  end

  # Short alias for update environment
  task :ue => :environment do |t, args|
    run_task "db:update_environment"
  end

  def run_task task
    Rake::Task[task].reenable
    Rake::Task[task].invoke
  end
end

```

All of this worked fine in Rails 4.x.  Now were're getting this error:

```
NameError: uninitialized constant Wsc::Errors::Authentication
```

This is a dependency that comes from our app/lib directory.

This is our Rakefile

```
#!/usr/bin/env rake
# Add your own tasks in files placed in lib/tasks ending in .rake,
# for example lib/tasks/task1.rake, and they will automatically be available to Rake.

require File.expand_path('../config/application', __FILE__)

Wowzacloud::Application.load_tasks

```

What do I need to do to get the dependencies to load properly in the rake task without having to write an unmaintainable and huge `require` dependency chain file?

**Comment by jockmac22** [comment]
So I was able to fix it, but I'm not sure it's the best way.  Modified the Rakefile to do this instead:
```
require File.expand_path('../config/environment', __FILE__)
```

Let me know your thoughts.

**Comment by pixeltrix** [comment]
Hmm, given that all that does extra is call `Rails.application.initialize!` seems weird - what's the backtrace for that `NameError`?

**Comment by clockworkpc** [comment]
> So I was able to fix it, but I'm not sure it's the best way. Modified the Rakefile to do this instead:
> 
> ```
> require File.expand_path('../config/environment', __FILE__)
> ```
> Let me know your thoughts.

Did the trick for me too, but I can't understand why.

**Comment by inertia186** [comment]
Me too, just now.

**Comment by hackmastera** [comment]
For people puzzling over this in the future: before messing with this make sure you're actually loading the environment in your task with `=> :environment`!

**Comment by arturhaddad** [comment]
I added this in Rakefile and it worked:
```
Dir.glob('app/lib/tasks/*.rake').each { |r| load r}
```
