### ISSUE TITLE
filter params white list array not working as described

### ISSUE THREAD

**Issue by grantzau** [rails/rails#28459]
### Steps to reproduce

When I try to white list an array parameter as described in the documentation, I get a syntax error.

[http://guides.rubyonrails.org/action_controller_overview.html#strong-parameters](http://guides.rubyonrails.org/action_controller_overview.html#strong-parameters)

The documentation says: 
`params.permit(id: [])`

I would expect this to work:

 ```
def subscription_params
      params.require(:subscription).permit(week_days: [], :from_week, :to_week, :product_id, :price, :quantity, :note)
end
```

But it throws SyntaxError and I have to wrap the array parameter in {} to get it to work:

```
def subscription_params
      params.require(:subscription).permit({ week_days: [] }, :from_week, :to_week, :product_id, :price, :quantity, :note)
end
```

Rails 5.0.2
ruby 2.4.0p0

**Comment by 1a2b** [comment]
@grantzau in ruby `week_days: []` <- hash so it is tha same as :week_days => [].

you can do only like this
`some_method(:a, :b, :c, week_days: object) `
or 
`some_method({week_days: object}, :a, :b, :c ) `

ruby syntax allow you not wrap hash in method params if it comes last

**Comment by grantzau** [comment]
Thank you for clarifying! Even though it is not a Rails issue, the documentation could maybe be clear about it.
