### ISSUE TITLE
I'd like to improve the docs for action_dispatch/request/session

### ISSUE THREAD

**Issue by jaredbeck** [rails/rails#28464]
I'd like to improve the docs for `action_dispatch/request/session`. It seems that I should be able to use methods like `::ActionDispatch::Request::Session#delete`.

The Action Controller Overview mentions a few methods in [Section 5.1 Accessing the Session][1], but it is not (nor should be) comprehensive.

I think that methods like `::ActionDispatch::Request::Session#delete` should appear on http://api.rubyonrails.org/

How can I help to make this happen? Do we remove a `:nodoc:` statement somewhere?

[1]: http://guides.rubyonrails.org/action_controller_overview.html#accessing-the-session

**Comment by pixeltrix** [comment]
@jaredbeck I think exposing that class is exposing the implementation details - there's an overview of session accessing in the documentation of `ActionController::Base` on http://api.rubyonrails.org. Perhaps expanding that and making it more prominent in some way would be better?

**Comment by jaredbeck** [comment]
> @jaredbeck I think exposing that class is exposing the implementation details ..

Hi Andrew. When you say "implementation details" it sounds to me like some of the class (`::ActionDispatch::Request::Session`) is API-public, and some is API-private? For example, I'm pretty sure that `#[]` is API-public, because it is mentioned in the guide, yet it is not visible on http://api.rubyonrails.org/. If we can identify which parts are API-public, I would like to help make those parts appear on http://api.rubyonrails.org/. How can I help with that?

**Comment by jaredbeck** [comment]
> there's an overview of session accessing in the documentation of ActionController::Base on http://api.rubyonrails.org. Perhaps expanding that and making it more prominent in some way would be better?

I don't think that would be "discoverable". I would like to see `::ActionDispatch::Request::Session` appear on http://api.rubyonrails.org/. I would like to find it by searching for the word "session". It is a class that I interact with regularly, so I think the public parts of it should be documented.

**Comment by pixeltrix** [comment]
@jaredbeck what do you mean you interact with that class regularly? Do you just mean via `session` in a controller? If so that's the API we want to expose - the fact that it's implemented via a class called `ActionDispatch::Request::Session` is irrelevant because it's been something else in the past. Exposing implementation details like that makes it harder for us to deliver improvements in the future.

**Comment by jaredbeck** [comment]
Andrew, it sounds like you want to be able to change the name of the class in the future. That's understandable.

Currently, none of the methods on `session` (lowercase s) appear in the reference documentation (api.rubyonrails.org). Will it be possible to remedy this? I should be able to search for, e.g. `[]` and find it. Ideally, all of the public methods would appear in the reference documentation.

**Comment by pixeltrix** [comment]
@jaredbeck yes, that's the case - however I'm not sure whether there's a way to expose `session[]` as a method on `ActionController::Base` in RDoc. Maybe just document `session` and then give examples?

**Comment by jaredbeck** [comment]
> Maybe just document `session` and then give examples?

Given the requirement that we cannot document the class name (`ActionDispatch::Request::Session`), this seems the best option we've come up with so far. Would you like me to give that a shot?

**Comment by pixeltrix** [comment]
> Would you like me to give that a shot?

That would be good but currently it's just a delegation to `@_request.session` and that method comes from `Rack::Request` :cry:

I think you'd have to undelegate the method in `ActionController::Metal` and make it an explicit method that you can add docs to.

**Comment by jaredbeck** [comment]
> I think you'd have to undelegate the method ..

hmm that might be above my pay grade lol

**Comment by jaredbeck** [comment]
The requirements given above make this proposed documentation improvement too difficult, so this issue became stale. My recommendation would be to relax the requirements, e.g. add `::ActionDispatch::Request::Session` to the public API. If we can do that, documentation becomes much easier.

**Comment by jaredbeck** [comment]
> The requirements given above make this proposed documentation improvement too difficult, so this issue became stale. My recommendation would be to relax the requirements, e.g. add ::ActionDispatch::Request::Session to the public API. If we can do that, documentation becomes much easier.

Not stale, waiting for approval from e.g. @pixeltrix for above recommendation.
