### ISSUE TITLE
Rewrite documentation so it talks about app/views/application not app/views/shared

### ISSUE THREAD

**Issue by krainboltgreene** [rails/rails#28468]
There's quite a bit of documentation in the layout and rendering documentation using the `app/views/shared/` folder example:

<img width="654" alt="screen shot 2017-03-17 at 1 31 51 pm" src="https://cloud.githubusercontent.com/assets/334809/24061845/51426a0c-0b16-11e7-9f93-df8e30dff271.png">
<img width="619" alt="screen shot 2017-03-17 at 1 32 02 pm" src="https://cloud.githubusercontent.com/assets/334809/24061846/5142bf70-0b16-11e7-923c-8d774f3780d8.png">

The problem is there's a much better place to put shared partials: `app/views/application/`

It only gets a small bit of the spotlight, below `shared`:

<img width="731" alt="screen shot 2017-03-17 at 1 32 22 pm" src="https://cloud.githubusercontent.com/assets/334809/24061918/a030a8ae-0b16-11e7-885f-90838131ecb2.png">

**Comment by krainboltgreene** [comment]
For what it's worth, I would love to work on this ticket, but I think there needs to be some real discussion on how to "teach" the cool features around `app/views/application` (namely the inheritance).

**Comment by maclover7** [comment]
I'd merge a PR to convert the `shared` to `application`
