### ISSUE TITLE
Rails 5.1 breaks transactional tests that use AR and Threads

### ISSUE THREAD

**Issue by rst** [rails/rails#28466]
In Rails through 5.0, if a transactional `ActiveSupport::TestCase` starts a new Thread, that Thread gets its own `ActiveRecord::Base.connection`, outside the context of the test transaction.  The same applies if the code under test starts a thread which uses a separate Connection. This may be slightly odd, but the effects were repeatable and useful; in fact `default_scoping_test.rb` in the ActiveRecord tests did this.

In 5.1.0.beta1, all threads in a transactional test get the same connection object. The effects if they try to use it simultaneously can be very strange, and generally aren't useful. This behavior was introduced in commit d6466beb for acceptance tests (so the server and test-runner processes can share the same connection and transactional context), but it does have the unfortunate effect of breaking pre-existing test suites.  And the quickie work-around (`self.use_transactional_tests = false`) does have a performance penalty.

The simplest thing for users might be to limit the new behavior to acceptance tests, for which it was introduced. But if that's too awkward, or undesirable for some other reason, this may merit prominent mention in the release notes -- if only because it can otherwise be awfully hard to track down why a test suite that's been working since Rails 3.1 is suddenly hanging while trying to talk to the database!

Putting this in the usual litany:

### Steps to reproduce

In a transaction `ActiveSupport::TestCase`, do something like this

```
  def test_thread_connections
    conn = ActiveRecord::Base.connection
    Thread.new do
      if conn == ActiveRecord::Base.connection
        raise "Connection pool no longer per thread!"
      end
    end.join
  end
```

### Expected behavior
I expected this test case to pass without throwing exceptions, as in Rails 5.0 and earlier releases.  (The template says "Tell us what should happen," and you may have intended to change the behavior here.  Nevertheless, that's what I expected!)

### Actual behavior
It throws an uncaught exception.

### System configuration
**Rails version**: 5.1.0.beta1

**Ruby version**: 2.2.4

**Comment by maclover7** [comment]
Looks like this is very similar to #28197.

**Comment by rst** [comment]
#28197 describes one possible symptom of this problem. It's not 100% clear from the description there that forced connection-sharing among threads in tests is the cause of that issue, but it does seem very, very likely.  (You'd need to look at `AR::Base.connection.object_id` in multiple threads to be sure.)

**Comment by rst** [comment]
I've got a quick, mostly-working approach to this issue [here](https://github.com/rst/rails/commit/fb6c29a193cc26d071a9997668b7c2d0d1648988). (There's one prior commit on the branch, which just reverts d6466be.)

The root of the problem here is that we want two particular threads to share a DB connection, but the `lock_thread` mechanism introduced in commit d6466be affects _all_ threads while running any transactional test.  So, I instead arrange for those two threads only to share a connection, like so:

 * Give `ConnectionPool` a `using_connection` method, which affects only the current thread
 * Give `SystemTestCase` a `setup` hook which puts a pointer to the fixture-managing DB connection
   someplace that the web-service thread can find it. (I used a class attribute on `SystemTestCase`
   itself, for lack of any better ideas.)
 * Put Rack middleware in the server thread's pipeline which wraps a `using_connection` on 
   `SystemTestCase.cached_db_connection` around the invocation of `Rails.application` to
   actually process the request.

The upshot is that the web-service thread in a `SystemTestCase` "borrows" the DB connection from the test-runner thread, but all other threads behave normally.

To be a PR, this would at least need explicit tests for the new `using_connection` method.  We might also want to still avoid the thread-sharing if the `SystemTestCase` is _not_ transactional, which would be a little extra code, but not particularly difficult.

**Comment by rafaelfranca** [comment]
cc @matthewd @eileencodes

**Comment by eileencodes** [comment]
Hey @rst can you clarify what your tests are doing that causes this behavior? Are you specifically testing connection threads like your steps to reproduce demonstrate? Or are you using multiple connections?

**Comment by rst** [comment]
I had two sets of unit tests which bumped up against this. One was tests which started a thread with a separate connection to verify that code under test was using transactions as specified. The other group was tests of code which starts threads on its own -- a set of maintenance jobs which typically has one thread hold a row locked while another runs several transactions. (Some of this code has defensive checks like the one I extracted into the test case, which is how I knew what was happening -- though some of them didn't, and those just hung. But the defensive checks were not the point of the test!)

Both of these were pre-existing unit tests which didn't involve anything at the controller level. Part of the issue here is that the beta 1 system-test machinery is altering the behavior of those tests.

You might also ask Keith about #28197, which is very likely related.

**Comment by matthewd** [comment]
https://github.com/rails/rails/pull/28605#issuecomment-297207156
