### ISSUE TITLE
ApplicationRecord "alias :has_many_and_belongs_to :has_and_belongs_to_many" or special error notice.

### ISSUE THREAD

**Issue by kelby** [rails/rails#28471]
We usually use :has_many and :belongs_to

When i want to use :has_and_belongs_to_many, i always typo : has_many_and_belongs_to
And i noticed some others people has this problem too.
(Especially for those people whose native language is not English.)

Should we alias :has_many_and_belongs_to :has_and_belongs_to_many,
or given a friendly special error notce, not just "NoMethodError: undefined method `has_many_and_belongs_to'"

**Comment by pixeltrix** [comment]
@kelby since the `did_you_mean` gem is now included by default from Ruby 2.3 I don't think we want to start doing any special checking on names and we certainly don't want to add an alias, sorry.
