### ISSUE TITLE
Improve API documentation to include more details about `render`

### ISSUE THREAD

**Issue by Erol** [rails/rails#28484]
I'd like to see more details about `render` on the API documentation. For example: what are the available options that can be passed? IMO, the current copy is lacking:

![c7hwg9sxwaccnbk](https://cloud.githubusercontent.com/assets/20772/24087046/7c1cb846-0d54-11e7-8752-3e6f2a5284e5.jpg)

I'll try to write something up if I find the time this week.

**Comment by maclover7** [comment]
Looks like a bunch of this is documented [here](http://api.rubyonrails.org/classes/ActionView/Helpers/RenderingHelper.html#method-i-render), probably just needs to be moved to a more prominent spot.

**Comment by juliusdelta** [comment]
If this is up for grabs, I'll hop on it. @maclover7

**Comment by Erol** [comment]
Apologies didn't really had the time to do this recently. Feel free to go ahead @juliusdelta.

**Comment by fakefarm** [comment]
Hello, I had some time tonight and have been looking for an easy one in order to get on the board. Please let me know if you think I should anything else. Thanks!

**Comment by PHedkvist** [comment]
Does anyone have time to look at my PR? :)

**Comment by azbshiri** [comment]
I'll continue this. @rafaelfranca @gmcgibbon
