### ISSUE TITLE
Merge not working for controller params

### ISSUE THREAD

**Issue by Tectract** [rails/rails#28494]
### Steps to reproduce

params.merge!({:myKey:false})

### Expected behavior
params should contain a key, :myKey, with the boolean value false

### Actual behavior
nothing happens, params is silently not updated

### System configuration
**Rails version**: Rails 4.2.6

**Ruby version**: Ruby 2.2.2

Ok guys, so how do I add a value into the params array? I tired of losing time on this issue.

**Comment by DavS1993** [comment]
whitelist the params that you receive i.e. strong params concept. e.g.

```
def blog_params
  params.require(:blog).permit(:name, :description)
end
```

then you can simply do:

```
blog_params.to_h.merge!({status: :active})
```
i find this to be a much cleaner and secure way.

**Comment by rafaelfranca** [comment]
This is fixed in Rails 5
