### ISSUE TITLE
previous_changes is empty if two models have autosave: true for each other

### ISSUE THREAD

**Issue by s-mage** [rails/rails#28491]
I have a code where `previous_changes` are used in `after_commit` callback. But it shows empty `previous_changes` when it shouldn't, so I created a test case to reproduce this.

I think this can be fixed in a way similar as in `nested_records_changed_for_autosave?`, i.e. adding special variable to avoid modifying "root" record.

### Steps to reproduce

https://gist.github.com/s-mage/20ebc5af616c340abade206f9d4670ca

Some explanations are provided in the gist.

### Expected behavior

`previous_changes` should not be empty

### Actual behavior

`previous_changes` is empty

### System configuration
**Rails version**:
4.2.7.1, 5.0.0, 5.1.0rc1 (tested on these versions, I'm almost sure older versions affected too)
**Ruby version**:
2.3.0

**Comment by s-mage** [comment]
Updated the gist, added another test case about double validation, which is caused by similar behaviour but in different place

**Comment by s-mage** [comment]
Tested on 5.0.0 and 5.1.0rc1 and behaviour there is the same.
Also I don't think that adding `@_already_called` here and there is the best way to improve the situation, but I don't know the right way either.

**Comment by s-mage** [comment]
Updated the gist to use activerecord 5.1. Behaviour is still the same.
https://gist.github.com/s-mage/20ebc5af616c340abade206f9d4670ca

**Comment by s-mage** [comment]
hi. Seems like nothing is changed and I still can reproduce the bug.

**Comment by pduey** [comment]
I just got bit too. Can it be reopened so it might get picked up for a fix?

**Comment by Shuiei** [comment]
I encounter the same behavior.

**Comment by pfeiffer** [comment]
Seeing this as well.

**Comment by abdelbk** [comment]
Seeing this as well. There is the https://github.com/hzamani/active_record-acts_as gem which adds `autosave: true` in the associated records and the `previous_changes` are empty in the `after_commit` callback.
