### ISSUE TITLE
Differences between `bin/rake test` and `bin/rails test`

### ISSUE THREAD

**Issue by eldano** [rails/rails#28506]
According to the [rails guides](http://guides.rubyonrails.org/command_line.html#bin-rails), in recent versions of rails (5.0+) the `bin/rails` command is the new default for running all commands.

We understand that this also means that tests are expected to run the same when using `bin/rails test` or `bin/rake test`. However, we found differences when the test includes `Rake::Task`.

### Steps to reproduce

- clone dummy app (https://github.com/eldano/rake_test_app)
- run `bundle install`
- execute `bin/rake test`
- execute `bin/rails test`

### Expected behavior

Both runs of the test pass and the output is the same, or there's some clarification in the documentation that there are exceptions for which these commands don't behave the same.

### Actual behavior
The second run of the test fails.

### System configuration
**Rails version**: 5.0.1

**Ruby version**: 2.4.0

**Comment by rafaelfranca** [comment]
cc @kaspth

**Comment by st0012** [comment]
According to [this comment](https://github.com/rails/rails/pull/28619#issuecomment-295386537),  those 2 command are not exchangeable

> In light of #28786 I've been thinking we should just update the documentation instead of loading the Rake tasks for people. Quoting @pixeltrix bin/rails test isn't bin/rake test 1:1 and the fact that the latter runs the rake task is incidental to how the commands are run.

I think this can be closed. cc @sikachu

**Comment by marcelolx** [comment]
@eldano I think this can be closed based on this comment https://github.com/rails/rails/pull/28619#issuecomment-295386537

**Comment by eldano** [comment]
I'll close this issue then, thanks
