### ISSUE TITLE
Fragment cache digest is blank when HTML partial is rendered inside JS view

### ISSUE THREAD

**Issue by thomasfedb** [rails/rails#28503]
### Steps to reproduce

1. `git clone https://github.com/thomasfedb/rails-cache-test.git`
2. `touch tmp/caching-dev.txt`
3. Run `rails s` and open in browser. Note that the paragraph is **red**.
4. Click the link to reload partial over JS. The paragraph is still **red**.
5. `git checkout blue` but **do not** restart Rails server.
6. Reload browser. Note that the paragraph is **blue**.
7. Click the link to reload partial over JS. The paragraph changes back to **red**.

When you review the logs from `rails s` you'll find that the following:

**Loading red partial via `index.html.erb`**
```
Started GET "/" for ::1 at 2017-03-21 21:05:30 +0800
Processing by HomeController#index as HTML
  Rendering home/index.html.erb within layouts/application
Read fragment views/x.dev.localhost//a8f265d1f73f3dafd91c3d947bbaac43 (0.0ms)
Write fragment views/x.dev.localhost//a8f265d1f73f3dafd91c3d947bbaac43 (0.0ms)
```

**Loading red partial via `index.js.erb`**
```
Started GET "/" for ::1 at 2017-03-21 21:05:54 +0800
Processing by HomeController#index as JS
  Rendering home/index.js.erb
  'home/_partial' file doesn't exist, so no dependencies
  Couldn't find template for digesting: home/_partial
Read fragment views/x.dev.localhost// (0.1ms)
Write fragment views/x.dev.localhost// (0.1ms)
```

**Loading blue partial via `index.html.erb`**
```
Started GET "/" for 127.0.0.1 at 2017-03-21 21:06:23 +0800
Processing by HomeController#index as HTML
  Rendering home/index.html.erb within layouts/application
Read fragment views/x.dev.localhost//2338c21dccfbc4347d872c453af9f072 (0.1ms)
Write fragment views/x.dev.localhost//2338c21dccfbc4347d872c453af9f072 (0.1ms)
```

**Loading blue partial via `index.js.erb`**
```
Started GET "/" for ::1 at 2017-03-21 21:06:24 +0800
Processing by HomeController#index as JS
  Rendering home/index.js.erb
  'home/_partial' file doesn't exist, so no dependencies
  Couldn't find template for digesting: home/_partial
Read fragment views/x.dev.localhost// (0.1ms)
```

### Expected behavior
The cache digest should be calculated correctly when rendering an HTML partial inside a JS view.

### Actual behavior
When rendering a HTML partial inside a JS view, the cache digest is blank. When the partial source changes, the key does not change, leading to the wrong content being displayed.

The issue seems to stem from [this line](https://github.com/rails/rails/blob/4d6feef79248a63c4cefde3f9ceb2242925e8d8d/actionview/lib/action_view/digestor.rb#L48) in `ActionView::Digestor`:
```
options[:formats] = [finder.rendered_format] if finder.rendered_format
```

Which, [as seen here](https://github.com/rails/rails/blob/fc2aa53f875b12df93b0d07932e3ab563b89152c/actionview/lib/action_view/renderer/template_renderer.rb#L12), will take only the first format (in this case `:js`) when it should probably take all formats (which would be `[:js, :html]`):
```
@lookup_context.rendered_format ||= (template.formats.first || formats.first)
```

### System configuration
**Rails version**: 5.0.2
**Ruby version**: 2.4.0

**Comment by richseviora** [comment]
I've just ran into the same problem myself and can duplicate in my project. It looks like there's an implicit assumption within this code that templates never cross formats.

I was able to patch `ActionView::Digestor.tree` to resolve this issue:

        options[:formats] = [finder.rendered_format] if finder.rendered_format
        options[:format].push(:json, :html) if finder.rendered_format == :js

But this is only a crude fix.

**Comment by thomasfedb** [comment]
Should it just be:

```ruby
options[:formats] = template.formats || formats
```

**Comment by richseviora** [comment]
@thomasfedb I'm doing this before `template` is assigned. [Here's](https://gist.github.com/richseviora/d46fe0baa02e97e5b475b43cd1647d8f) the patch file I'm using in `config/initializers`.

I think the challenge is that `ActionView::Digestor` and `ActionView::DependencyTracker` are only rough simulations of the template rendering process that takes place when a view is rendered. They don't actually run through the process itself.

In theory, we could supply all the supported formats available in `finder.details.formats` but there's a lot of formats that wouldn't be applicable.

`[:html, :text, :js, :css, :ics, :csv, :vcf, :png, :jpeg, :gif, :bmp, :tiff, :svg, :mpeg, :xml, :rss, :atom, :yaml, :multipart_form, :url_encoded_form, :json, :pdf, :zip, :gzip]`

I think the ideal solution would be one that determines what template the render template command would normally render in that context. I haven't experimented with rendering JS from within HTML ERB so that may add some wrinkles if you have both `_resource.js.erb` and `_resource.html.erb`.

As a related note, I've also noticed that `coffee-rails` does not register an `ActionView::DependencyTracker` for `.coffee` files and therefore does not resolve dependencies for `.coffee` files when they have ERB injections. I'll open an issue there.

**Comment by richseviora** [comment]
Actually I'm not sure my fix works completely; while it does attach a digest to the fragment key that digest doesn't seem to change when the dependencies are updated. I'll do some more debugging later.

**Comment by thomasfedb** [comment]
Is there a good reason that the dependency determination is done differently than during template rendering?

**Comment by richseviora** [comment]
@thomasfedb My guess is that we can't simulate the template rendering process without real data. A dry run would not necessarily resolve all the dependencies that are required when rendering a template. Especially when we're looking at if statements, collections, objects that render partials and so on.

The crude patch does eliminate the problem for my use case, however but I'm not sure whether it is a sufficiently generalized solution for a PR. 

I'd also like to see better tools for detecting dependencies (as well as testing digest changes) and I'll submit a PR to supplement the rake tasks currently available with something I put together.

**Comment by thomasfedb** [comment]
I think in my example it should be possible for Rails to determine the exact template to be rendered. At least, it should realise that if no cache digest can be computed than it should not cache template?

Also, at the point when you're calculating cache digests to store or retrieve fragments, shouldn't you in theory have all the data required to do the same lookup you would it you were rendering without caching?

The line in my reproduction is `render "partial", collection: [1], cached: true`, and the only info required to locate the `_partial.html.erb` should really be `"partial"`, the directory listing, and whatever from the current template that Rails uses to choose what format it's looking for in a partial.

**Comment by thomasfedb** [comment]
Hey @maclover7, is there anybody in particular who know how all this works well enough to comment on what's going on here? If I can get some advice I'd be happy to attempt the PR.

**Comment by thomasfedb** [comment]
I believe that that this issue remains, I certainly haven't notice if being fixed. Will attempt to replicate again when possible.

**Comment by zhengpd** [comment]
Seeing the same issue when rendering a `:js` format partial inside the `:html` partial. The `Digestor` use `[finder.rendered_format]` as `options[:formats]` to find the partial template, while `PartialRender` is using the formats array passed from `render partial: 'xxx', formats: [:js]` as you can see in [here](https://github.com/rails/rails/blob/master/actionview/lib/action_view/renderer/partial_renderer.rb#L421). I'm not clear how exactly the `:formats` is designed to work, so for a quick fix I just change to `options[:formats] = finder.formats || [finder.rendered_format]` in `ActionView::Digestor.tree` method.

**Comment by thomasfedb** [comment]
@zhengpd, is your patch working for you so far? Noticed any issues?

**Comment by zhengpd** [comment]
@thomasfedb Works good for me and no issue so far.

**Comment by thomasfedb** [comment]
@zhengpd to clarify, are you saying that even with an explicitly specified `:format` the `Digestor` will still use `[finder.rendered_format]` to find the partial?

**Comment by zhengpd** [comment]
@thomasfedb With specified `formats: [:js]`, yes. In my case, I do something like:

```ruby
# something.html.erb
render partial: 'xxx', formats: [:js]
```

This will result in a `Couldn't find template for digesting: xxx` error after cache is enabled.

**Comment by thomasfedb** [comment]
@richseviora did you end up submitted the PR your mentioned?

**Comment by richseviora** [comment]
@thomasfedb I never got around to it (I don't think!), but I found this [rake task](https://gist.github.com/richseviora/1066660016d7f5795ef6646820e96d72) in the repo I was working on at the time.

**Comment by thomasfedb** [comment]
@javan I've noticed your commits 1ee4eeb and 1717836 which seem to have introduced the following:

```
options[:formats] = [finder.rendered_format] if finder.rendered_format
```

Correct me if I'm wrong, but it seems to me that `finder.rendered_format` will be the format of the template or partial that's rendered by the controller, rather than the template that `cache` is called from. This results in the current template not being found if it's a different format from the template the controller directly rendered.

Could you explain why setting `options[:formats]` to this value is required?

I tried removing `options[:formats]` from `Digestor.tree` and the only issue I had was the the following test from `digestor_test.rb` failed afterwards:

```
  def test_different_formats_with_same_logical_template_names_results_in_different_digests
    html_digest = digest("comments/_comment", format: :html)
    json_digest = digest("comments/_comment", format: :json)

    assert_not_equal html_digest, json_digest
  end
```

To be honest I've not been able to work out quite what the consequences of this would be.

**Comment by javan** [comment]
> what the consequences of this would be

The consequences would be reintroducing the bug that those commits fixed. See https://github.com/rails/rails/pull/25411.

**Comment by thomasfedb** [comment]
Thanks for pointing out the PR @javan. I believe that your fix has the had the (unintended I assume) consequence that any templates used in a request with a different format are not found by the `Digestor`. Do you agree?

Would it be possible to only restrict the format of templates to `finder.rendered_format` when `cache` is called from the template that is directly invoked by the controller?

**Comment by javan** [comment]
I agree that my change may have broken previously untested behavior so the next step would be writing a failing test for this issue. Is that something you're interested in doing?

**Comment by thomasfedb** [comment]
@javan, sure I'll give it a go a little later

**Comment by thomasfedb** [comment]
@javan have a look here: https://github.com/rails/rails/compare/master...thomasfedb:cross-format-cache-digest

```
Failure:
TemplateDigestorTest#test_cross_format_digest [/home/thomasfedb/Code/rails/actionview/test/template/digestor_test.rb:310]:
Expected "" to not be equal to "".
```

**Comment by thomasfedb** [comment]
@javan have you had a chance to look at the failing test?

**Comment by javan** [comment]
No, sorry. I’m on vacation until March 16.

**Comment by javan** [comment]
@thomasfedb, think I have a fix for this: https://github.com/rails/rails/compare/master...javan:fix-digesting-mixed-formats

Mind giving that branch a try?

**Comment by thomasfedb** [comment]
Sure @javan, I'll give it a crack now.

**Comment by thomasfedb** [comment]
Certainly seems to avoid the `Couldn't find template for digesting` errors in my testing @javan.

**Comment by thomasfedb** [comment]
Many thanks @javan
