### ISSUE TITLE
Remove reference with foreign key and index

### ISSUE THREAD

**Issue by matheussilvasantos** [rails/rails#28504]
### Steps to reproduce

Old migration
`add_reference :products, :feedstock_group, foreign_key: { on_delete: :nullify }, index: true`

New migration
`remove_reference :products, :feedstock_group, foreign_key: { on_delete: :nullify }, index: true`

### Expected behavior

Delete the field in the migration and create with the foreign key and index on rollback

### Actual behavior

ActiveRecord::StatementInvalid: Mysql2::Error: Cannot drop index 'index_products_on_feedstock_group_id': needed in a foreign key constraint: ALTER TABLE `products` DROP `feedstock_group_id`

### System configuration
**Rails version**: Rails 5.0.1

**Ruby version**: ruby 2.4.0p0 (2016-12-24 revision 57164) [x86_64-linux]

**Comment by mubashirhanif** [comment]
I've created a Minimal Testing [script](https://gist.github.com/mubashirhanif/d8dbe44d5c999041ac172d309596a0bd) for this issue, I am unable to replicate this issue.

### System Config
**Rails:** 5.0.1
**Ruby:** 2.4.0p0 (2016-12-24 revision 57164) [x86_64-darwin16]
**MySql:** mysql  Ver 14.14 Distrib 5.7.17, for osx10.12 (x86_64) using  EditLine wrapper
