### ISSUE TITLE
Routing strip off optional (.:format) when nesting resources under a parent resource named :formats

### ISSUE THREAD

**Issue by pouellet** [rails/rails#28517]
### Steps to reproduce

Considering the following routes:

```ruby
class TestApp < Rails::Application
  routes.draw do
    resources :formats do
      resources :items
    end
  end
end
```

The optional format part of the route `(.:format)` always gets stripped off by the router.

Repro test: https://gist.github.com/pouellet/d5d2e9dd6879971ee3b24b0556468e2d 

### Expected behavior
```
=> rake routes
    
...
    format_items GET      /formats/:format_id/items(.:format)              items#index
                 POST     /formats/:format_id/items(.:format)              items#create
 new_format_item GET      /formats/:format_id/items/new(.:format)          items#new
edit_format_item GET      /formats/:format_id/items/:id/edit(.:format)     items#edit
     format_item GET      /formats/:format_id/items/:id(.:format)          items#show
                 PATCH    /formats/:format_id/items/:id(.:format)          items#update
                 PUT      /formats/:format_id/items/:id(.:format)          items#update
                 DELETE   /formats/:format_id/items/:id(.:format)          items#destroy
         formats GET      /formats(.:format)                               formats#index
...

```

### Actual behavior
```
=> rake routes

...
    format_items GET      /formats/:format_id/items            items#index
                 POST     /formats/:format_id/items            items#create
 new_format_item GET      /formats/:format_id/items/new        items#new
edit_format_item GET      /formats/:format_id/items/:id/edit   items#edit
     format_item GET      /formats/:format_id/items/:id        items#show
                 PATCH    /formats/:format_id/items/:id        items#update
                 PUT      /formats/:format_id/items/:id        items#update
                 DELETE   /formats/:format_id/items/:id        items#destroy
         formats GET      /formats(.:format)                   formats#index
...
```
### Problem / suggested solution
The problem seems to be in this method:

```ruby
module ActionDispatch::Routing
  class Mapper::Mapping
    def optional_format?(path, format)
      format != false && !path.include?(":format") && !path.end_with?("/")
    end
  end 
end
```

With the nested resource, the path passed in looks like `/formats/:format_id/items` which will match the `path.include?(":format")` check and always remove the optional `(.:format)`. I've changed it to the following against master to make the check more restrictive and it seems to solve the issue while not breaking tests.

```ruby
module ActionDispatch
  module Routing
    class Mapper
      class Mapping
        CONTAINS_FORMAT_REGEX = %r{:format(?!_id)}
        
        private

        def optional_format?(path, format)
          format != false && path !~ CONTAINS_FORMAT_REGEX && !path.end_with?('/')
        end
      end
    end
  end
end
```

There might be an easier fix for this, but I'm not familiar enough with the Rails codebase to know if a more generic match wouldn't affect other stuff. I can submit a fix if you consider it's good enough.

### System configuration
**Rails version**: 4.2.7.1 (also reproduced against master)
**Ruby version**: 2.3.1

**Comment by maclover7** [comment]
@pouellet Hi! Are you able to submit a patch with a fix and a regression test? Thanks!

**Comment by maclover7** [comment]
cc @pixeltrix

**Comment by pixeltrix** [comment]
Backported to [5-1-stable], [5-0-stable] and [4-2-stable]. The 4-2-stable branch is technically unsupported but it's a straightforward enough fix.

[5-1-stable]: https://github.com/rails/rails/commit/7aee155f2ccba83de8d29ceb3b48901adc545a1e
[5-0-stable]: https://github.com/rails/rails/commit/f48f3c371b1b38cb8332021dbb941df57e9297d9
[4-2-stable]: https://github.com/rails/rails/commit/ea11acd17a4c5dcbaa736a7caeee950c2a73c801

**Comment by pouellet** [comment]
Thanks for the fix @pixeltrix, I knew my suggested fix was too specific, this makes a lot more sense.
