### ISSUE TITLE
rails new: webpack option doesn't consider javascript option

### ISSUE THREAD

**Issue by sunnyrjuneja** [rails/rails#28512]
### Steps to reproduce
`rails new reproduce-js-wp --javascript=typescript --webpack`

### Expected behavior
package.json should add typescript as a development dependency (and optionally, not include the coffee script one). 

### Actual behavior
It ignores --javascript option and includes coffee-script as a dependency instead. Contents of package.json here:
```
{
  "name": "reproduce-js-wp",
  "private": true,
  "dependencies": {},
  "devDependencies": {
    "babel-core": "^6.24.0",
    "babel-loader": "^6.4.1",
    "babel-preset-latest": "^6.24.0",
    "coffee-loader": "^0.7.3",
    "coffee-script": "^1.12.4",
    "glob": "^7.1.1",
    "path-complete-extname": "^0.1.0",
    "rails-erb-loader": "^3.2.0",
    "webpack": "^2.3.0",
    "webpack-dev-server": "^2.4.2",
    "webpack-merge": "^4.1.0"
  }
}
```

### System configuration
Rails 5.1.0.rc1
ruby 2.3.3p222 (2016-11-21 revision 56859) [x86_64-linux]

**Comment by sunnyrjuneja** [comment]
This might be a separate bug (unsure) but coffee-rails is included in Gemfile and coffee-script loaded is included in package.json.

**Comment by maclover7** [comment]
`--javascript` is an argument for the Rails app generator, not for Webpacker. Also, all of the dependencies above are added to `package.json` by Webpacker, not by Rails. ...sounds like we might be missing an integration point between the two tools? 😬 

cc @dhh

**Comment by sunnyrjuneja** [comment]
I think this problem requires a non trivial amount of integration. Perhaps if someone can point to a similar example integration, I could take this on directly or at least do some research on what an implementation could look like for feedback.

**Comment by rafaelfranca** [comment]
https://github.com/rails/rails/pull/26902
