### ISSUE TITLE
Rails 5.1 sets ARGV for `rails runner "...code..."` differently from earlier releases

### ISSUE THREAD

**Issue by rst** [rails/rails#28515]
### Steps to reproduce

 * Create a Rails 5.1 app (tried with 5.1.0.rc1).
 * At the command line, run `rails runner 'puts ARGV.inspect' x`

### Expected behavior
I expected this to output `["x"]`, as it does in prior releases.

### Actual behavior
It outputs `["puts ARGV.inspect", "x"]`. If the code being run by `runner` looks at `ARGV`, and does not expect to see a copy of itself in the array, this can cause trouble.  So, if this is a deliberate change, it probably merits mention in the release notes.

### System configuration
**Rails version**: 5.1.0.rc1

**Ruby version**: 2.2.4

**Comment by matthewd** [comment]
Sounds fixable. Do you want to try for a PR?

**Comment by rst** [comment]
Will try over the next day or two. The change to the code itself is almost certainly trivial; I'm just not sure where to put the test. `railties/test/application/runner_test.rb` looks like where current tests for this are (not `railties/test/commands`). Have I got that right?

**Comment by rst** [comment]
PR submitted, as one commit based on master. Let me know if you need anything else...
