### ISSUE TITLE
date_select causing wrong date when using discard_year and include_blank

### ISSUE THREAD

**Issue by grantzau** [rails/rails#28521]
When using discard_year together with include_blank the date_helper sets year to "1" using a hidden field. That somehow causes the saved date value to be altered in a way, that the "day" part of the date increases by two ...

So choosing "january" "1" from the two selects saves the date "0001-01-03" instead of "0001-01-01"

But if the value of the year part is set anything from 201 upto 300 or 1583 upto 2017 the day and month parts remains as entered, which makes no sense to me. 

### Steps to reproduce

`rails new app_test_discard_year`
`cd app_test_discard_year/`
`rails generate scaffold test_day day:date`
`rails db:migrate`

Add `{ discard_year: true, include_blank: true }` to the date_select in 

> app/views/test_days/_form.html.erb

so it looks like this `<%= f.date_select :day, { discard_year: true, include_blank: true } %>`

> http://localhost:3000/test_days 

Start server and try creating a new "Test Day" choosing january 1st and save. 

Rails 5.0.2
ruby 2.4.0p0

**Comment by nynhex** [comment]
@grantzau I've reproduced this with Rails `5.0.2` and Ruby `2.4.0` can confirm.

**Comment by CharlieHawker** [comment]
Also present in `5.1.0.rc1` with Ruby `2.4.0p0`

**Comment by CharlieHawker** [comment]
A bit of further digging and this doesn't seem to relate to how date_select passes the params through to rails - it seems to be to do with how ActiveRecord does it's type casting; the parameters in the log are as expected:
```
Parameters: {"utf8"=>"✓", "authenticity_token"=>"z1Wri0PN6F8ngRgUODePl3oJNvEB8CM9Gf5mJQWp5SjWu0qHhalVHsEIj7jPbZtsj5W21BVbSUHY4NCc0kQbqA==", "test_day"=>{"day(1i)"=>"1", "day(2i)"=>"1", "day(3i)"=>"1"}, "commit"=>"Create Test day"}
```

and if you use the rails console to create a TestDate with the same attributes, you get the same issue:

```
2.4.0 :085 > d = TestDay.new({"day(1i)"=>"1", "day(2i)"=>"1", "day(3i)"=>"1"})
 => #<TestDay id: nil, day: "0001-01-03", created_at: nil, updated_at: nil> 
2.4.0 :086 > d
 => #<TestDay id: nil, day: "0001-01-03", created_at: nil, updated_at: nil> 
```

Digging a little deeper, the attribute assignment code in _lib/active_record/attribute_assignment.rb_ seems to prepare the hash as expected for the 'day' attribute; so the issue I *believe* is arising in the ActiveRecord::Attribute type casting code.

As a further proof, you can see the uncast attribute value of a new TestDay is showing correctly:

```
2.4.0 :087 > d = TestDay.new({"day(1i)"=>"1", "day(2i)"=>"1", "day(3i)"=>"1"})
 => #<TestDay id: nil, day: "0001-01-03", created_at: nil, updated_at: nil> 
2.4.0 :088 > d.day_before_type_cast
 => {1=>1, 2=>1, 3=>1} 
```

**Comment by grantzau** [comment]
@CharlieHawker  Thanks for clarifying, I agree that the problem seems to be in the ActiveRecord library. Personally I haved fixed it by setting the default value of year to "2001" instead.

I don´t know if it makes sense to do the same in the rails/date_helper.rb - as the year is discarded anyway, setting it to 2001 has no side-effect from my point of view, only the possitive effect, that it makes the day/month select work ... ! :)

[action_view/helpers/date_helper.rb#L824](https://github.com/rails/rails/blob/df63abe6d31cdbe426ff6dda9bdd878acc602728/actionview/lib/action_view/helpers/date_helper.rb#L824)

**Comment by grantzau** [comment]
Year is still set to "1" in 5-1 stable so the problem is still there

**Comment by Sayanc93** [comment]
I took a stab at it here https://github.com/rails/rails/pull/29651 😄

**Comment by gregblass** [comment]
Can confirm this is happening on my production application. Was sitting here for an hour trying to figure out what was going on. It's adding two days to my date for some reason.

Anyone have a workaround for code currently in production?

**Comment by MOOn2k** [comment]
Rails is 5.1.4 already and problem is still there..

**Comment by grantzau** [comment]
How can the issue be opened again? Seems like @Sayanc93 resolved it

**Comment by MOOn2k** [comment]
Rails gem I'm using:

Mac-User-2:jarvisydan user$ bundle show rails
/Users/user/.rvm/gems/ruby-2.5.0@jarvisydan/gems/rails-5.1.4

Sceenshot of problem (Fromtastic, AA, Pry):

![2018-03-13 15 50 00](https://user-images.githubusercontent.com/1121622/37342681-5b3c192c-26d6-11e8-9fc3-133cc5517475.png)

So, every time page renders back with updated object I'm getting new dates with additional 2 days.

**Comment by marcosdemelo** [comment]
When upgrading to version 5.2.3 of Rails, my test suite had several flaws related to the validation of numerics of larger values.

I made a small script that makes it possible to simulate the problem in version 5.2.3 of Rails
In the script I noticed that the `bigdecimal` gem generates interference, but I don't know if the defect is in it or in Rails.

can anybody help me?

With `Rails or ActiveModel 5.2.3` and `bigdecimal 1.x`

```ruby

# - Open the `irb` 
# - Paste the class below
# - Then, the calls below to see the situation

require 'active_model'
class AClass
  include ActiveModel::Validations

  attr_accessor :a_column

  validates :a_column, numericality: { less_than_or_equal_to: 999_999_999_999.9999 }

  def initialize
    puts "ActiveModel version: #{ActiveModel.version}"
    puts "BigDecimal version: #{BigDecimal::VERSION}\n\n"

    @a_column = 999_999_999_999.9999
  end
end

a = AClass.new
a.valid?
a.a_column = 1_000_000_000_000.0000
a.valid? # When using bigdecimal-1.4.1 => true ???
```

If using bigdecimal> 2, it works. And the second call `a.valid?`, returns false.
In Rails 6, I have the same problem.

My tests:

```shell
irb(main):017:0> a = AClass.new
ActiveModel version: 5.2.2

BigDecimal version: 1.4.1

=> #<AClass:0x00007fd2689b01d0 @a_column=999999999999.9999>
irb(main):018:0> a.valid?
=> true
irb(main):019:0> a.a_column = 1_000_000_000_000.0000
=> 1000000000000.0
irb(main):020:0> a.valid?
=> false
```

```shell
irb(main):018:0> a = AClass.new
ActiveModel version: 5.2.3

BigDecimal version: 1.4.1

=> #<AClass:0x00007fea515d33e0 @a_column=999999999999.9999>
irb(main):019:0> a.valid?
=> true
irb(main):020:0> a.a_column = 1_000_000_000_000.0000
=> 1000000000000.0
irb(main):021:0> a.valid?
=> true
```

**Comment by marcosdemelo** [comment]
@Sayanc93 do you think this problem should be investigated? Should I open an issue?

**Comment by Sayanc93** [comment]
@marcosdemelo sorry, I just checked this thread. If the error is reproducible in current rails version please go ahead and open an issue!
