### ISSUE TITLE
Confusion between asset_path and asset_url

### ISSUE THREAD

**Issue by yivo** [rails/rails#28520]
**actionpack**
When we call `user_form_path` we get **relative URL**: `/users/form`.
When we call `user_form_url` we get **full URL***: `https://mysite.com/users/form`.
\* computed from `config.action_controller.default_url_options` or current request object `ActionDispatch::Request`

**actionview** with `config.action_controller.asset_host = nil`
When we call `image_path('car.png')` we get **relative URL**: `/assets/car.png`.
When we call `image_url('car.png')` we get **full URL***: `https://mysite.com/assets/car.png`.
\* computed from current request object `ActionDispatch::Request`

**actionview** with `config.action_controller.asset_host ='https://cdn.mysite.com'`
When we call `image_path('car.png')` we get **full URL ???**: `https://cdn.mysite.com/assets/car.png`. WTF?
When we call `image_url('car.png')` we get **full URL**: `https://cdn.mysite.com/assets/car.png`.

Why `image_path` returns full URL? It says path, not a URL. **path != URL**

I think this behaviour is ugly and breaks rails conventions: path is relative URL, URL is full URL.

This behaviour is about 3 years old so I probably think many projects are using it.
To not break them I am ready to submit a pull request with a new config variable which will affect `asset_path` behaviour.  

What do you think about it?

### Steps to reproduce
Set `Rails.application.config.action_controller.asset_host ='https://cdn.mysite.com'`
Call `image_path('car.png')`

### Expected behavior
Should return only path `/assets/car.png`

### Actual behavior
Full URL is returned`https://cdn.mysite.com/assets/car.png`

### System configuration
**Rails version**: unknown

**Ruby version**: doesn't matter

**Comment by rafaelfranca** [comment]
This is by design to avoid mistake for part of the users, if you are setting a asset host we can't generate a relative URL otherwise the asset will not be served. To make sure that all assets come from the asset host we always return the full path.

**Comment by rafaelfranca** [comment]
This is a dup of https://github.com/rails/rails/issues/22721
