### ISSUE TITLE
Cache hit/miss markers are applied to partials that aren't cached

### ISSUE THREAD

**Issue by dhh** [rails/rails#28529]
The new [ cache hit/miss ] markers in the log when rendering partials can often be applied wrong when the partial is either not cached or nested. This is because the flag to track this is [stored on the view context](https://github.com/kaspth/rails/blob/843345cae59b73e50af685ac1303a419a06b4c91/actionview/lib/action_view/helpers/cache_helper.rb#L234), rather than attached to the specific partial.

**Comment by st0012** [comment]
This is my fault, I will try to fix it 😢

**Comment by st0012** [comment]
@kaspth So this is fixed or....?

**Comment by dhh** [comment]
Not fixed. Please take a look if you'd like!

**Comment by st0012** [comment]
I've attached a PR that should fix this issue and add more tests for it, which is waiting for review.

**Comment by dhh** [comment]
❤️

**Comment by kaspth** [comment]
Fixed in https://github.com/rails/rails/commit/8240636beda7b2b487217be1d945eb0d36145c4d
