### ISSUE TITLE
Improve Docs Readbility

### ISSUE THREAD

**Issue by colmtuite** [rails/rails#28533]
I'm a 30 year-old with good eye-sight and I always have trouble reading the rails docs. The main body copy and code blocks are so small I have to squint to see them.

### How to improve legibility

1. The base font size could be bumped up to at least the default font size; 16px.
2. The measure (line-length or character count) is currently only limited by viewport width. It should be capped at the recommended line-length of 80 characters max. This would make it much easier to follow the text as you read.
3. The base typeface could be upgraded from Helvetica to San Francisco, leaving Helvetica as a fallback. San Francisco is a much higher quality typeface with greater readability at small sizes.
4. The base code typeface could be upgraded to a higher quality font-family with fallbacks, similar to what you see on Github or StackOverflow.
5. The cream background color on code blocks is quite harsh, especially with the current syntax highlighting theme. A less harsh cream, light gray or dark gray would make the code easier to read.

There are many more optimisations which could be made to improve the readability of the docs. For a start though, I'd love to make the minimum improvements required to make the docs legible.

Should I go ahead and open a pull request for this? Would it get any support?

**Comment by fxn** [comment]
Hi @colmtuite.

I am a 48 years old that is resisting doing anything with presbyopia for as long as possible, and read the Rails docs on a daily basis without problem. But we could definitely try and compare.

If the comparison is favorable I am all for it, only take into account that supporting the initiative is not a promise for a merge.
