### ISSUE TITLE
Accessing a key from ActiveModel::Errors creates it in the messages hash

### ISSUE THREAD

**Issue by AlexVPopov** [rails/rails#28545]
### Steps to reproduce

In the rails console of a Rails 4.2 (probably the same for Rails 5) project with [active_model-errors_details](https://github.com/cowbell/active_model-errors_details) included in the Gemfile:

```ruby
new_foo = Foo.new
new_foo.errors[:bar] # => []
new_foo.errors.messages # => {:foo=>[]}
```

Why does accessing a key automatically adds it to the messages hash? It is not a very intuitive behavior that doing a read operation would mutate an object. Furthermore, it is also not consistent with `details`, as accessing a key adds it to the `messages` hash, but not the `details` hash:

```ruby
new_foo = Foo.new
new_foo.errors[:bar] # => []
new_foo.errors.details # => {}
```

I guess the rational for this was that so a check like `errors[:foo].empty?` wouldn't throw `NoMethodError: undefined method `empty?' for nil:NilClass`. However, adding the key to the messages hash leads to unexpected bugs, when serializing errors and relying on particular structure of the errors object. For example:

```ruby
record.errors.keys.map do |error|
  { location: error,
    code: record.errors.details[error].first[:error],
    message: record.errors.messages[error].first }
end
```

would throw `NoMethodError - undefined method `[]' for nil:NilClass`. That's kind of hard to debug, because one ends up with an error object, the `messages` hash of which contains an unexpected key and it is kind of hard to figure out how this key got into it.

### Expected behavior
```ruby
new_foo = Foo.new
new_foo.errors[:bar] # => nil
new_foo.errors.messages # => {}

```

### Actual behavior

Described in the first section.

### System configuration
**Rails version**: 4.2.8.

**Ruby version**: 2.3.1

**Comment by vipulnsward** [comment]
https://github.com/rails/rails/issues/23468#issuecomment-179868835

**Comment by sekmo** [comment]
For posterity: now we can use `errors.include?` / `errors.has_key?` / `errors.key?`
