### ISSUE TITLE
TestDrives singularization issue

### ISSUE THREAD

**Issue by ItsMeCK** [rails/rails#28542]
### Steps to reproduce

Create two models:
1. Enquery
has_many test_drives
accepts_nested_attributes_for :test_drives

2.TestDrive
belongs_to enquery

So whenevr we call enquery#create with test_drives as nested attributes. it raises error uninitilise constant **Enquery::TestDrife**.

(Guidelines for creating a bug report are [available
here](http://guides.rubyonrails.org/contributing_to_ruby_on_rails.html#creating-a-bug-report))

### Expected behavior
Tell us what should happen
test_drives or drives should be singularised to TestDrive/ Drive.
### Actual behavior
Tell us what happens instead
test_drives singularised to TestDrife
### System configuration
**Rails version**:
4.0.0
**Ruby version**:
2.3.0

**Comment by vipulnsward** [comment]
Please create an executable test case to reproduce this issue - https://github.com/rails/rails/blob/master/guides/bug_report_templates/active_record_gem.rb 
so that we can take a look at your issue.

**Comment by fedegratti** [comment]
Hello guys, I just create an executable test case and I could reproduce this issue:
`# This connection will do for database-independent bug reports.
ActiveRecord::Base.establish_connection(adapter: "sqlite3", database: ":memory:")
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :enqueries, force: true do |t|
  end

  create_table :test_drives, force: true do |t|
    t.integer :enquerie_id
  end
end

class Enquery < ActiveRecord::Base
  has_many :test_drives
  accepts_nested_attributes_for :test_drives
end

class TestDrive < ActiveRecord::Base
  belongs_to :enquery
end

class BugTest < Minitest::Test
  def test_association_stuff
    enquery = Enquery.create!
    enquery.test_drives << TestDrive.create!

    assert_equal 1, enquery.test_drives.count
    assert_equal 1, TestDrive.count
    assert_equal enquery.id, TestDrive.first.enquery.id
  end
end`
I hope it helps.

**Comment by matthewd** [comment]
The inflector is frozen; you can add an override in `config/initializers/inflections.rb`.

**Comment by ItsMeCK** [comment]
Thanks Matthewd for help.
Another way is adding associated class name in model file.
E.g 
class Enquery
   has_many :test_drives, class_name: "TestDrive"
end

Thanks,
-Chandrakant.
