### ISSUE TITLE
hepler :all or helper SomeHelper not worked in ActionController::API

### ISSUE THREAD

**Issue by zw963** [rails/rails#28554]
Following is sample code:

```rb
module CommonHelper
  def display_price(number)
    number_with_precision(
      number,
      precision: 2,
      separator: '.',
      delimiter: ',',
      strip_insignificant_zeros: true
    )
  end

end
class XxxApi::V1::ApiController < ActionController::API
  helper CommonHelper

  # use helpers.display_price method here, not exist
  # NoMethodError: undefined method `display_helper' for #<ActionView::Base:0x0000000817ddd0>
end
```

BTW:  `ActionController::Base` is worked, Just `ActionController::API` not work.

**Comment by ItsMeCK** [comment]
I think this is not issue. Rails API skips helpers. So you might need to  include **ActionController::Helpers** in your controller.

**Comment by zw963** [comment]
@ItsMeCK , Following code not work.

```rb
class XxxApi::V1::ApiController < ActionController::API
  include ActionController::Helpers
  helper CommonHelper


  # use helpers.display_price method here, not exist
  # NoMethodError: undefined method `display_helper' for #<ActionView::Base:0x0000000817ddd0>
end
```

**Comment by zw963** [comment]
AFAIK: If Rails API skip helpers, when I invoke `helper` method, is should told me,
`helper` method is not exists.

**Comment by rafaelfranca** [comment]
As you can see in the linked commit, that exact code you posted works.

**Comment by zw963** [comment]
@rafaelfranca,  Thanks for you reply.

I know the problem which caused this ...
following is some explain about this:

1. define a helper, named `display_price`
```rb
# app/helpers/common_helper.rb
module CommonHelper
  def display_price(number, symbol='')
    display_number = ActionController::Base.helpers.number_with_precision(
      number,
      precision: 2,
      separator: '.',
      delimiter: ',',
      strip_insignificant_zeros: true
    )
    "#{symbol}#{display_number}"
  end
end
```

2.  include this helper in API base class

```rb
# app/controllers/xxx_api/v1/api_controller.rb
class XxxApi::V1::ApiController < ActionController::API
  include ActionController::Helpers
  helper CommonHelper
end
```

3.  But use helper in ApiController subclass. it not worked. should this is a bug?

```rb
# app/controllers/xxx_api/v1/json/home_controller.rb
class XxxApi::V1::Json::HomeController < XxxApi::V1::ApiController
  def index
     # try use `helpers.display_helper` here,  method not exist
  end
end
```

4. because the following method `method1` is invoked in sub class, so `helpers.display_price` 
in following `method1` is not worked too.
it is confuse a little ... I change this issue topic too.

```rb
# app/controllers/xxx_api/v1/api_controller.rb
class XxxApi::V1::ApiController < ActionController::API
  include ActionController::Helpers
  helper CommonHelper

  def method1
     # use helpers.display_price method here, not exist
     # NoMethodError: undefined method `display_helper' for #<ActionView::Base:0x0000000817ddd0>
  end
end
```

5. instead of,  add `helper CommonHelper` in subclass directly, it worked.

```rb
# app/controllers/xxx_api/v1/json/home_controller.rb
class XxxApi::V1::Json::HomeController < XxxApi::V1::ApiController
  helper CommonHelper
  def index
     # try use `helpers.display_helper` here, it worked!
  end
end
```

6. this behavior is not consistant `ActionController::Base`, in rails 5, I don't need add
any line code in my following file.

```rb
# app/controllers/xxx_api/v1/application_controller.rb
class XxxApi::V1::ApplicationController < ActionController::Base
   # no need add any code here
end
```

```rb
class XxxApi::V1::Html::TestController < XxxApi::V1::ApplicationController
  def index
    `helpers.display_price` can worked here
   end
end
```

7. I want to confirm a problem is correct,  the `helper CommonHelper` usage is just for
 the case I used like previous API example ?  Thanks.

**Comment by rafaelfranca** [comment]
I added another test in 862cc0bfbe. As you can see subclasses also works if you include `ActionController::Helpers`.

It is expected that users of `ActionController::API` needs to add code to use helpers since `ActionController::API` don't include helpers, so the behavior is not consistent indeed by design.

**Comment by zw963** [comment]
@rafaelfranca , very sad to say, it not worked for me, I think i test this
should not exists some problem.

And, sorry for say, your's test I could not run success , I does not config 
rails test run env,  i just run the `abstract_unit.rb` which from here
https://github.com/rails/rails/blob/862cc0bfbe6f125aff4e76c2d71764a14bcf4891/actionpack/test/abstract_unit.rb with:

```rb
rails r abstract_unit.rb
```

Got:

```rb
abstract_unit.rb:443:in `<top (required)>': uninitialized constant ActionDispatch::SystemTestCase (NameError)
```

**Comment by zw963** [comment]
Somethings is maybe useful for clarify:

I use `ActionController::API` from a existing project which only pure http web page
from Rails 5.0.1, I am not use `rails new new_project --api` to create a new project.
and I does not add any new extra application config for new API to worked.

basically, I just add a class to inherit from `ActionController::API`.

maybe I missing some special config for your's test situation to work? thanks

**Comment by rafaelfranca** [comment]
My test is passing, as you can see in the travis-ci page https://travis-ci.org/rails/rails/builds/216686192.

Like your case, I just made the class inherit from `ActionController::API` and it works.

I just created a new application without the `--api` flag and created a `ActionController::API` controller using a helper and it also works.

**Comment by zw963** [comment]
oh, all right, I don't know what happen for me,  I just add `helper CommonHelper` to subclass
to make it work. I will try this feature in my next project.

Thanks

**Comment by jjercx** [comment]
I have extactly same problem :/
