### ISSUE TITLE
Rails 5.1 breaks gem activerecord-postgis-adapter

### ISSUE THREAD

**Issue by MtnBiker** [rails/rails#28551]
With no version specified for `gem activerecord-postgis-adapter` `bundle update` resulted in `Installing activerecord-postgis-adapter 3.1.2 (was 4.0.2)`, but then `rails server` error 

    ~/.gem/ruby/2.4.0/gems/bundler-1.14.6/lib/bundler/runtime.rb:94:in `rescue in block (2 levels) in require': There was an error while trying to load the gem 'activerecord-postgis-adapter'. (Bundler::GemRequireError)
    Gem Load Error is: uninitialized constant ActiveRecord::ConnectionAdapters::PostgreSQL::ColumnDefinition
    Did you mean?  ActiveRecord::ConnectionAdapters::ColumnDefinition
                   ActiveRecord::ConnectionAdapters::AddColumnDefinition
    Backtrace for gem load error is:
    ~/.gem/ruby/2.4.0/gems/activerecord-postgis-adapter-3.1.2/lib/active_record/connection_adapters/postgis/spatial_table_definition.rb:46:in `<module:PostGIS>'
...
Put version 4.0.2 in Gemfile and got this `bundle update` error

    Bundler could not find compatible versions for gem "activerecord":
      In Gemfile:
        activerecord-postgis-adapter (= 4.0.2) was resolved to 4.0.2, which depends on
          activerecord (~> 5.0.0)
    
        rails (~> 5.1.0.rc1) was resolved to 5.1.0.rc1, which depends on
          activerecord (= 5.1.0.rc1)

### System configuration
**Rails version**: 5.1.0.rc1

**Ruby version**: 2.4.0p0

Posted to the gem also https://github.com/rgeo/activerecord-postgis-adapter/issues/248

I'm a Rails newbie and am developing an app. I am getting into the JavaScript aspects and seemed as if I may as well get on 5.1 and use the asset manager changes in 5.1 rather than fighting Rails 4.

I too much of a newbie to know if this is my problem, the gem's problem or Rails 5.1, but thought it better to report it now rather than later.

**Comment by rafaelfranca** [comment]
It seems that the `activerecord-postgis-adapter` gem still don't support Rails 5.1 https://github.com/rgeo/activerecord-postgis-adapter/blob/master/activerecord-postgis-adapter.gemspec#L22

**Comment by MtnBiker** [comment]
Excuse my ignorance, but I have no idea what this means. 

Maybe add to Gemfile, but there is no ./lib/active_record/connection_adapters/postgis/version.rb” or more specifically what does it contain?

Greg

**Comment by rafaelfranca** [comment]
I mean the developers of the gem `activerecord-postgis-adapter` needs to work in their gem to support Rails 5.1. If you need to use that gem you can't use Rails 5.1, only Rails 5.0

**Comment by MtnBiker** [comment]
Thank you. I’ll pass it along.

I presume activerecord has to be 5.1

Greg
