### ISSUE TITLE
Can't determine whether an environment is suitable for rails development in the first chapter of Rails Guide

### ISSUE THREAD

**Issue by keisei1092** [rails/rails#28565]
### Expected behavior
I think it'll be better if we can notice the matter [latter chapter](http://edgeguides.rubyonrails.org/getting_started.html#installing-rails) shows some commands to check an environment in the [first chapter](http://edgeguides.rubyonrails.org/getting_started.html#guide-assumptions).

### Actual behavior
In the [first chapter](http://edgeguides.rubyonrails.org/getting_started.html#guide-assumptions) of [Getting Started with Rails](http://edgeguides.rubyonrails.org/getting_started.html) page, it describes some prerequisites for installing rails.
Since this chapter doesn't describe any commands to check an environment, I first thought I have to know them by googling it.
But it does describes some ways in the [third chapter](http://edgeguides.rubyonrails.org/getting_started.html#installing-rails). Once seeing it I noticed that my efforts were needless.

If this issue is reasonable, I can afford to open a pull request :)
Any reviews would be thankful.

**Comment by maclover7** [comment]
Hi @keisei1092! Seems reasonable to me. Feel free to send a PR.
