### ISSUE TITLE
Destroyed_record.save returns true with SQLite and unfreezes the model instance

### ISSUE THREAD

**Issue by mandysimon88** [rails/rails#28563]
### Steps to reproduce
rails new my_app
rails generate model User
rake db:migrate
rails c
user = User.new
user.save
user.destroy
user.frozen?
=> true
user.save
=> true // should be false
user.frozen?
=> false // should still return true
User.count
=> 0
user.save!
=> true // should throw an error
User.count
=> 0

### Expected behavior
Destroyed objects still held in memory should return `false` or throw an error when trying to save. They should remain frozen even after attempts to save.

### Actual behavior
Destroyed objects in memory, when told to `save` or `save!` return `true`, even though they are not actually saved to the database. And, they unfreeze themselves.

### System configuration
**Rails version**:
5.0.2

**Ruby version**:
2.4.0

**SQLite version**:
1.3.13

I did not modify any gems. The steps to reproduce are complete to show the error in this Rails version.

**Comment by johncalvinyoung** [comment]
To follow up, I believe that this problem does not happen in `rails 5.0.0.1` using `pg 0.18.4` and `Postgresql 9.5.4.0`. A similar sequence does not unfreeze the record, and throws an exception when the destroyed record is saved.

**Comment by alexcameron89** [comment]
Using `git bisect`, it looks like the unfreezing behavior was introduced with 07723c23a7dc570beae73c074ad37227e3e8a06e.

The attributes are changed on a `save`, despite it being frozen. This happens for both destroyed records and saved-but-frozen records. Here is a [test script](https://gist.github.com/alexcameron89/11b77a2d2da66757062cfcf9d52eb490) for the frozen issue.
