### ISSUE TITLE
Missing default values from default_scope on ActiveRecord model initialization

### ISSUE THREAD

**Issue by rossta** [rails/rails#28561]
### Summary
ActiveRecord models using `default_scope` with *where conditions defined in array format* do not get initialized with the expected default scope attribute values.

### Steps to reproduce

```ruby
begin
  require "bundler/inline"
rescue LoadError => e
  $stderr.puts "Bundler version 1.10 or later is required. Please update your Bundler"
  raise e
end

gemfile(true) do
  source "https://rubygems.org"
  # Activate the gem you are reporting the issue against.
  gem "activerecord", "~> 5.0.0"
  gem "sqlite3"
end

require "active_record"
require "minitest/autorun"
require "logger"

# Ensure backward compatibility with Minitest 4
Minitest::Test = MiniTest::Unit::TestCase unless defined?(Minitest::Test)

# This connection will do for database-independent bug reports.
ActiveRecord::Base.establish_connection(adapter: "sqlite3", database: ":memory:")
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :squares, force: true do |t|
    t.integer :number
  end

  create_table :circles, force: true do |t|
    t.integer :number
  end
end

class Square < ActiveRecord::Base
  default_scope { where(number: 1) }
end

class Circle < ActiveRecord::Base
  default_scope { where("number = ?", 1) }
end

class BugTest < Minitest::Test
  def setup
    Square.delete_all
    Circle.delete_all
  end

  def test_find_with_default_scope_hash_conditions
    Square.create(number: 1)

    # SELECT "squares".* FROM "squares" WHERE "squares"."number" = ?  [["number", 1]]
    assert_equal 1, Square.all.length
  end

  def test_initialize_with_default_scope_hash_conditions

    # puts Square.new.attributes
    # {"id"=>nil, "number"=>1}
    assert_equal 1, Square.new.number
  end

  def test_find_with_default_scope_array_conditions
    Circle.create(number: 1)

    # SELECT "circles".* FROM "circles" WHERE (number = 1)
    assert_equal 1, Circle.all.length
  end

  # This spec fails
  def test_initialize_with_default_scope_array_conditions

    # puts Circle.new.attributes
    # {"id"=>nil, "number"=>nil}
    assert_equal 1, Circle.new.number
  end
end
```
### Expected behavior
Above, I'd expect `Circle.new` to be initialized with its `:number` attribute set to 1, same as the `Square.new` example. The difference between the two models is the format of the where conditions.

### Actual behavior
`Circle.new` gets initialized with its `:number` attribute set to `nil`, unlike `Sqaure.new` which gets its `:number` attribute set to 1.

### System configuration
**Rails version**:
Occurs in 4.1, 4.2, 5.0

**Ruby version**:
2.3.1

**Comment by maclover7** [comment]
As you mentioned, this issue originates with the fact that with one model the `default_scope` attributes are provided through a Hash, and with the other, it's a string. The Hash version will be turned into Arel objects, which is [a requirement](https://github.com/rails/rails/blob/master/activerecord/lib/active_record/relation/where_clause.rb#L45) for when we turn the default_scope's attributes [into a Hash](https://github.com/rails/rails/blob/master/activerecord/lib/active_record/relation.rb#L590) to be used for default attribute assignment. Only real way to solve this would be to turn the string into Arel objects somehow, which seems unlikely 😞

**Comment by rafaelfranca** [comment]
Yeah, this is a limitation of using strings in scopes.

**Comment by rossta** [comment]
Thanks for the info! 

Would it be helpful to have this something to this effect documented in the Rails guides for defining `where` conditions? It's not immediately obvious to the uninformed that these ways of defining (nearly) equivalent SQL would not have equivalent behavior in Rails scopes in certain cases.

**Comment by maclover7** [comment]
@rossta Sure, that sounds like a good idea. Would you be willing to send a PR to add this to the documentation?

**Comment by rossta** [comment]
@maclover7 Yes, will do
