### ISSUE TITLE
ActiveRecord::ConnectionAdapters::Quoting doesn't use double quotes for escaped characters

### ISSUE THREAD

**Issue by henrytseng** [rails/rails#28562]
### Steps to reproduce

1. Set up connection/ActiveRecord model
2. Call `ActiveRecord::ConnectionAdapters::Quoting.quote` method with characters to escape

### Expected behavior

The `quote` method should return a properly escaped string with double-quotes.  This causes an issue especially for `Arel::InsertManager` since it accesses connection adapter directly to utilize `quote`.  

https://github.com/rails/arel/issues/479

### Actual behavior

The `quote` method uses single-quotes even when it escapes characters.  This creates malformed string statements for MySQL adapter.  

### System configuration
**Rails version**: 4.2.7.1

**Ruby version**: 2.3.1

**Comment by maclover7** [comment]
@henrytseng I'm not able to reproduce the issue using [this reproduction script](https://gist.github.com/maclover7/4fa6c8444f80d03348d637e113db097f).
Can you create an executable test script using one of the templates [here](https://github.com/rails/rails/tree/master/guides/bug_report_templates), that would demonstrate the problem you are seeing?

Also, please be careful that you are using public API. `ActiveRecord::ConnectionAdapters::Quoting` and Arel are both private API, and are not meant to be used by end users.

**Comment by henrytseng** [comment]
I understand that `ActiveRecord::ConnectionAdapters::Quoting` is not a public API but would `Arel::InsertManager` also be a private API?  

Our team has a constant need to write high performance SQL that will require the use of Arel and/or directly writing SQL statements.  I would be great to be able to use Arel directly and build modular code rather than writing SQL statements as strings forcing us to do more string manipulation.  

Thanks for the quick response!

**Comment by maclover7** [comment]
@henrytseng Yep, all of Arel is private API 😞
