### ISSUE TITLE
Add indefinite article to to_sentence

### ISSUE THREAD

**Issue by abrambailey** [rails/rails#28576]
Sometimes it is necessary to produce a sentence like "I have an apple and a banana" or "The phone has 3G, and an FM radio" ... It would be nice to add indefinite articles in front of each word in the array or optionally before the final array item. I'm assuming this is not currently possible.  http://apidock.com/rails/Array/to_sentence

**Comment by abrambailey** [comment]
For now this works
```ruby
array.to_sentence(:last_word_connector => "#{%w(a e i o u).include?(array.last.downcase.first) ? ", and an " : ", and a "}")
```

**Comment by rafaelfranca** [comment]
Thank you so much for the issue. For this case I believe a custom code is good enough. Rails tries to work in 80% of the cases. There are 20% of cases that will need custom logic.
