### ISSUE TITLE
Rails 5.1.0.rc1: rake webpack:install:vue task not available

### ISSUE THREAD

**Issue by mdesantis** [rails/rails#28573]
It seems to be an issue with webpacker gem version. In the Gemfile created there is `gem 'webpacker'` which installs 1.0 version which ships without the vue task. If I replace it with `gem 'webpacker', github: 'rails/webpacker'` the task is available.

### Steps to reproduce

Create a new Rails 5.1.0.rc1 application running `rails new rails_vue --webpack=vue`

### Expected behavior

The step which executes `rails  webpacker:install:vue` does not abort due to rake task not found

### Actual behavior

The step which executes `rails  webpacker:install:vue` aborts due to rake task not found. Error:

```
[...]
       rails  webpacker:install:vue
rails aborted!
Don't know how to build task 'webpacker:install:vue' (see --tasks)
bin/rails:4:in `require'
bin/rails:4:in `<main>'
(See full trace by running task with --trace)
```

Full output: https://gist.github.com/mdesantis/214982b377e94020980347eaf21b8efc

### Fix

In the Gemfile, replace `gem 'webpacker'` with `gem 'webpacker', github: 'rails/webpacker'`.

### System configuration

Ruby 2.4.0
Rails 5.1.0.rc1

**Comment by maclover7** [comment]
Hi @mdesantis! Since this appears to be a Webpacker specific issue, can you please open up an issue at the rails/webpacker repo [here](https://github.com/rails/webpacker/issues/new)? Thanks!

**Comment by mdesantis** [comment]
Sure, I wanted to but since I encountered this issue creating a new Rails application I was in doubt where to open the issue :) I'll do it right now.
