### ISSUE TITLE
4.2.8 throws error when doing [time1, time2].max on frozen times

### ISSUE THREAD

**Issue by Goltergaul** [rails/rails#28585]
### Steps to reproduce
calling `[time1, time2].max` where both times are frozen throws:
RuntimeError: can't modify frozen Time
from /home/dog/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/activesupport-4.2.8/lib/active_support/core_ext/date_and_time/compatibility.rb:23:in `to_time'

### Expected behavior
There should be no error

### Actual behavior
RuntimeError is thrown

### System configuration
**Rails version**: none

**Ruby version**: ruby 2.3.3p222 (2016-11-21 revision 56859) [x86_64-linux]

**Comment by eugeneius** [comment]
This is already fixed on 4-2-stable by https://github.com/rails/rails/pull/28465.
