### ISSUE TITLE
load_schema is not thread-safe.

### ISSUE THREAD

**Issue by nasa42** [rails/rails#28589]
In a threaded environment, it is possible that multiple threads may try to load schema for a model concurrently. This may lead to concurrency issues like `serialize`d columns not working correctly (example below).

### Steps to reproduce

I've created a [sample application](https://github.com/watchmanmonitoring/load-schema-thread-safety-issue) with steps to reproduce in the README.

### Expected behavior

If `ExampleModel` class has `serialize :example_column`, I'd expect `example_column` to return the Ruby object that was saved to it. E.g., if I saved an Array instance in column `example_column`, it should return an Array instance next time I read it from database.

### Actual behavior

In certain conditions, `example_column` returns the YAML dump stored in database instead of the Ruby object.

This happens because in threaded environment, a race-condition may occur, which causes type of column `example_column` to be evaluated as `ActiveModel::Type::Text` instead of `ActiveRecord::Type::Serialized`.

### Possible solution

[`ActiveRecord::ModelSchema::ClassMethods#load_schema`](https://github.com/rails/rails/blob/v5.0.2/activerecord/lib/active_record/model_schema.rb#L435) should be wrapped in a Mutex. I'm happy to make a PR if consensus is reached.

### System configuration
**Rails version**: 5.0.2 (also reproducible on 5.1.0rc1).

**Ruby version**: 2.4.1

Possibly related: https://github.com/rails/rails/issues/27418

**Comment by nasa42** [comment]
Possible stop-gap solution: (untested)

Put this in `config/initializers/00_load_schema_thread_safety_workaround.rb`

```
# See issue https://github.com/rails/rails/issues/28589
ModelWithSerializedAttribute1.send(:load_schema)
ModelWithSerializedAttribute2.send(:load_schema)
```

**Comment by rafaelfranca** [comment]
Other alternative is eager load the model schema on boot time if `eager_load` is true (usually production). We are doing this in our application not just to avoid race-conditions but also to make sure that the first request don't take the performance overhead of loading the schema.

@matthewd WDYT?

**Comment by nasa42** [comment]
> Other alternative is eager load the model schema on boot time if `eager_load` is true (usually production).

@rafaelfranca Is there a config in ActiveRecord to eager load schema that I missed?

**Comment by rafaelfranca** [comment]
There is not. We implemented that in our application, but I think it is good to have.

**Comment by matthewd** [comment]
> ActiveRecord::ModelSchema::ClassMethods#load_schema should be wrapped in a Mutex. I'm happy to make a PR if consensus is reached.

👍🏻 Yes please!

---

@rafaelfranca connecting to the database at boot seems a bit over-eager to me -- though I could see value in one central "extreme eager load" option.

**Comment by aud** [comment]
Is there anything I can do to expedite this? This bug seems very similar to what we're experiencing in one of our apps as well.

**Comment by rafaelfranca** [comment]
Yeah agree. Let's go with the mutex for now. @nasa42 could you open a PR?
