### ISSUE TITLE
tsrange breaks with time zone awareness and infinity

### ISSUE THREAD

**Issue by TrevorHinesley** [rails/rails#28581]
Reproducible test case below. 

1. Make sure to `createdb railstestdb`
2. To see this work properly (when used with no time zone functionality), comment out the two `COMMENT OUT TO PASS` lines.

```ruby
begin
  require "bundler/inline"
rescue LoadError => e
  $stderr.puts "Bundler version 1.10 or later is required. Please update your Bundler"
  raise e
end

gemfile(true) do
  source "https://rubygems.org"
  gem "rails", github: "rails/rails"
  gem "arel", github: "rails/arel"
  gem "pg"
end

require "active_record"
require "minitest/autorun"
require "logger"

# This connection will do for database-independent bug reports.
ActiveRecord::Base.establish_connection(adapter: "postgresql", database: "railstestdb")
ActiveRecord::Base.logger = Logger.new(STDOUT)
ActiveRecord::Base.time_zone_aware_attributes = true # COMMENT OUT TO PASS

ActiveRecord::Schema.define do
  create_table :rangers, force: true do |t|
    t.tsrange :range
    t.timestamps null: false
  end
end

class Ranger < ActiveRecord::Base
  before_create :set_range
  self.time_zone_aware_types += [:tsrange]  # COMMENT OUT TO PASS

  def set_range
    self.range = self.created_at..DateTime::Infinity.new
  end
end

class BugTest < Minitest::Test
  def test_association_stuff
    ranger = Ranger.create
    ranger.range.last # ERROR

    assert_equal 1, 1 # Dummy assertion just so error above will be thrown
  end
end
```

Error:

```
  1) Error:
BugTest#test_association_stuff:
NoMethodError: undefined method `begin' for #<Date::Infinity:0x007fb7ab8a90e8 @d=1>
```

**Comment by pixeltrix** [comment]
@TrevorHinesley using timezone conversion with `DateTime::Infinity` values isn't possible, e.g:

```
>> Time.zone = 'America/New_York'
=> "America/New_York"
>> DateTime::Infinity.new.in_time_zone
NoMethodError: undefined method `in_time_zone' for #<Date::Infinity:0x007fc3ceeeb080 @d=1>
```

**Comment by pixeltrix** [comment]
Also they don't work without conversion too - they're typecast to `Float` when reloaded.

**Comment by TrevorHinesley** [comment]
That's fine, but if time zone awareness is going to be supported as well as infinity dates, then it should also handle this gracefully.

**Comment by pixeltrix** [comment]
Another potential issue is that timestamp values themselves are bounded between 4713 BC and 294276 AD:

https://www.postgresql.org/docs/current/static/datatype-datetime.html

**Comment by TrevorHinesley** [comment]
Why couldn't it just ignore time zone and return/set infinity just like it does without time zone awareness? Seems logical

**Comment by pixeltrix** [comment]
@TrevorHinesley given the [comment here][1] by @sgrif, I'm not sure that conversion to Float is intentional or going to be deprecated at some point. Also from that comment is that `Date::Infinity` (which is what you're really getting since `DateTime` inherits from `Date`) is an internal class and not supposed to be used.

We tried to make date/time comparable with infinity in #7350 but that was reverted in 6c61dbf1 for the reasons outlined in [this comment][2].

[1]: https://github.com/rails/rails/pull/17365#issuecomment-74690967
[2]: https://github.com/rails/rails/pull/7350#issuecomment-17419820

**Comment by TrevorHinesley** [comment]
Ahh I gotcha. What's the current status then? Obviously infinite dates are doable/intended to be used in Postgres, so what should our implementation assume?
