### ISSUE TITLE
Getting attribute_changed? deprecation warning in a place that's not deprecated in Rails 5.1.0.rc1

### ISSUE THREAD

**Issue by hult** [rails/rails#28594]
### Steps to reproduce
In a model, call `attribute_changed?` from the condition of a `validate` callback.

```ruby
class MyModel
  validate :name_is_valid, if: lambda { |obj| obj.name_changed? }
end
```

### Expected behavior
I expect this to work without deprecation warnings.

### Actual behavior
I'm getting a deprecation warning that suggest the behavior of `attribute_changed?` changed from inside after callbacks, but this is not inside one (I could of course not use the deprecation warning's suggested fix of changing to `saved_change_to_attribute?` since it's not saved yet).

> DEPRECATION WARNING: The behavior of `attribute_changed?` inside of after callbacks will be changing in the next version of Rails. The new return value will reflect the behavior of calling the method after `save` returned (e.g. the opposite of what it returns now). To maintain the current behavior, use `saved_change_to_attribute?` instead. (called from block in <class:MyModel> at /Users/magnus/Code/rails_test/api/app/models/my_model.rb:2)

### System configuration
**Rails version**: 5.1.0.rc1

**Ruby version**: 2.4.1

**Comment by fillman** [comment]
Have you tried this in latest `master`? I'm not receiving any deprecation. But! When used inside after callbacks I do receive deprecation. Which is expected!
Anyway your commit is here:
https://github.com/rails/rails/commit/16ae3db5a5c6a08383b974ae6c96faac5b4a3c81
Checkout DHH comment. There's still a bug with before callbacks.

**Comment by hult** [comment]
My example is a bit more contrived than what I explained, and I can't manage to find a simple example to reproduce it. I guess I'll come back once I found one.

**Comment by hult** [comment]
Ok, the warning happened because of a save from within a before_save (which is exactly what DHH talked about, if I understood him correctly). Weird having the message talk about after callbacks though, since only before and validate callbacks were involved.

**Comment by fillman** [comment]
It's definitely a bug my friend, but I guess as a workaround you can switch to those new dirty methods introduced in the commit (as also pointed by dhh).

**Comment by fillman** [comment]
Anyway, I suggest you either modify this issue, or close and create new one, with steps to reproduce, so someone can fix it. Good luck @hult!

**Comment by hult** [comment]
Thanks! Submitted #28599 instead.
