### ISSUE TITLE
5.1.0.rc1 --webpack, problem with rails-ujs

### ISSUE THREAD

**Issue by Danilo-Araujo-Silva** [rails/rails#28597]
### Steps to reproduce
I'm using rails **5.1.0.rc1** with **--webpack** option.

So, in this vein, I would like to avoid to use assets pipelines to load the dependencies and use only webpack for this.
I'd configured the system and is working fine but, after I integrated with devise, I couldn't get the route`users/sign_out` working.

After doing a research looks like I should add `rails-ujs` and maybe `turbolinks`. But, because I not working with assets pipelines anymore (and not getting rails-ujs and turbolinks from the gems), I added this two packages with yarn.

`yarn add rails-ujs turbolinks`

The problem is when I require this libraries

```
let railsUJS = require('rails-ujs');
let tubolinks = require('turbolinks');

```
the `rails-ujs` throw an error:

```
rails-ujs.js:24 Uncaught ReferenceError: Rails is not defined
    at Object.<anonymous> (rails-ujs.js:24)
    at Object.topLevelTypes.topAbort (rails-ujs.js:50)
    at __webpack_require__ (bootstrap da09793…:19)
    at Object.<anonymous> (index.js:151)
    at Object.exports.byteLength (body.js:21627)
    at __webpack_require__ (bootstrap da09793…:19)
    at Object.<anonymous> (body.js:2)
    at __webpack_require__ (bootstrap da09793…:19)
    at Object.<anonymous> (body.js:21407)
    at __webpack_require__ (bootstrap da09793…:19)
```

For now I have about 17 javascript dependencies loading and working (bootstrap, material components web, materialize-css, font-awesome, etc) but rails-ujs unfortunally not.

I tried to open a issue on the [rails/rails-ujs](https://github.com/rails/rails-ujs) repository but the github send me a **page not found** error.

(Guidelines for creating a bug report are [available
here](http://guides.rubyonrails.org/contributing_to_ruby_on_rails.html#creating-a-bug-report))

### Expected behavior
Tell us what should happen

```
let railsUJS = require('rails-ujs');
let tubolinks = require('turbolinks');
```
should not thrown an error and the dependencies should be loaded.

### Actual behavior
Tell us what happens instead

`require('rails-ujs')` throw an error, like explained above.

### System configuration
**Rails version**:
5.1.0.rc1
**Ruby version**:
ruby 2.4.1p111 (2017-03-22 revision 58053) [x86_64-linux]

**Comment by Danilo-Araujo-Silva** [comment]
With **jquery-ujs** instead of **rails-ujs** the route works! =)
Anywary, rails-ujs for now isn't working.

**Comment by rafaelfranca** [comment]
What is the version of rails-ujs that was installed by yarn?

**Comment by Danilo-Araujo-Silva** [comment]
From package.json:
```
"jquery-ujs": "^1.2.2",
"rails-ujs": "^5.1.0-beta1",
```

From yarn.lock:
```
jquery-ujs@^1.2.2:
  resolved "https://registry.yarnpkg.com/jquery-ujs/-/jquery-ujs-1.2.2.tgz#6a8ef1020e6b6dda385b90a4bddc128c21c56397"
rails-ujs@^5.1.0-beta1:
  resolved "https://registry.yarnpkg.com/rails-ujs/-/rails-ujs-5.1.0-beta1.tgz#6e2cc0250d124570759a63f9631e81975dcefc47
```

**Comment by rafaelfranca** [comment]
Could you try the `rails-ujs@^5.1.0-rc1`?

**Comment by Danilo-Araujo-Silva** [comment]
Unfortunally still the same error.

```
$ cat node_modules/rails-ujs/package.json | grep version
  "version": "5.1.0-rc1",
```
If I go back to jquery-ujs the error is solved.

I don't know if this could help, but I'm working on this [project](https://github.com/Danilo-Araujo-Silva/startup-mvp-boilerplate/compare/raw/server/ruby/rails/5.1.0.rc1...dev?expand=1). The link show a branch comparision of a raw/untouched rails 5.1.0.rc1 app with my current dev branch.

**Comment by sekrett** [comment]
Strange, I have no errors with `rails-ujs` but it simply does not work when I click in browser, but `jquery-ujs` works fine. Rails 5.1.2, I am adding `require('rails-ujs')` to `app/javascripts/packs/application.js`.

**Comment by mikker** [comment]
@sekrett You need to start it as well.

```javascript
const Rails = require('rails-ujs');
Rails.start()
```

**Comment by sekrett** [comment]
Thanks, that was not obvious.

**Comment by mikker** [comment]
I agree.

**Comment by vincentwoo** [comment]
This definitely should be reflected in documentation somewhere.

**Comment by a-ta-ta** [comment]
@mikker Could you, please, explain it more specificly? Where do these lines go?

**Comment by capripot** [comment]
https://github.com/rails/rails/tree/master/actionview/app/assets/javascripts#es2015
