### ISSUE TITLE
The "Learn More" links on the ActiveRecord readme page are broken

### ISSUE THREAD

**Issue by jtokash** [rails/rails#28608]
### Steps to reproduce
Open [this link](https://github.com/rails/rails/tree/master/activerecord) in Chrome (I'm on a Mac).

Notice that clicking on any of the "Learn More" links (for instance, [this one](https://github.com/rails/rails/blob/master/activerecord/classes/ActiveRecord/Base.html)) takes you to a github 404 screen.

Thanks!

**Comment by rafaelfranca** [comment]
Thank you for the issue. Those links are not made to be view at GitHub, they are to be clicked in the API website and they are working there.
