### ISSUE TITLE
Secrets not being read because of issue with production.rb

### ISSUE THREAD

**Issue by hahmed** [rails/rails#28618]
### Steps to reproduce

I am trying to add paperclip s3 config to my `production.rb`, e.g.

```
config.paperclip_defaults = {
    storage: :s3,
    s3_credentials: {
      bucket: Rails.application.secrets.S3_BUCKET_NAME,
      access_key_id: Rails.application.secrets.AWS_ACCESS_KEY_ID,
      secret_access_key: Rails.application.secrets.AWS_SECRET_ACCESS_KEY,
      s3_region: Rails.application.secrets.AWS_REGION
    }
  }
```
In the command line I enter: `RAILS_ENV=production rails c` to get into the rails command, then I enter `Appname::Application.secrets`

### Expected behavior

This should read the secrets in the `secrets.yaml.enc` and the paperclip configuration should be set up.

### Actual behavior

I only get the secrets from my `secrets.yml` file. I am just wondering if `config.paperclip_defaults = {` is a valid syntax for production.rb? 

I had another similar issue when I tried to set my send grid smtp settings in a similar way in the production.rb, I ended up having to move the code into environment.rb (adding this just in case it helps)

```
ActionMailer::Base.smtp_settings = {
  user_name: Rails.application.secrets.sendgrid_username,
  password: Rails.application.secrets.sendgrid_password,
  domain: 'app-name.herokuapp.com',
  address: 'smtp.sendgrid.net',
  port: 587, # 465 for ssl connections
  authentication: :plain,
  enable_starttls_auto: true
}

```

### System configuration
**Rails version**: 5.1.0.rc1

**Ruby version**: 2.3.1p112 (2016-04-26 revision 54768) [x86_64-darwin15]

**Edit:**

Here is the sample repo. 

https://github.com/hahmed/secretly

Initial commit (with the paperclip config): https://github.com/hahmed/secretly/blob/5740b6bf95cbc6665ef124adcbaa1638a6adbf3f/config/environments/production.rb#L79

```
haroon-mbp:secretly haroon$ RAILS_ENV=production rails c
Running via Spring preloader in process 1567
Loading production environment (Rails 5.1.0.rc1)
irb(main):001:0> Secretly::Application.secrets
=> {:api_key=>123, :secret_key_base=>nil, :secret_token=>nil}
irb(main):002:0> quit

```
Second commit (hide the paperclip config): 
https://github.com/hahmed/secretly/blob/master/config/environments/production.rb#L79

```
haroon-mbp:secretly haroon$ RAILS_ENV=production rails c
Running via Spring preloader in process 1722
Loading production environment (Rails 5.1.0.rc1)
irb(main):001:0> Secretly::Application.secrets
=> {:api_key=>123, :secret_key_base=>nil, :external_api_key=>"1466aac22e6a869134be3d09b9e89232fc2c2289", :sky=>"has_gots_to_fly", :me=>"the_admins_boy", :secret_token=>nil}
irb(main):002:0> 
```

Let me know if there is anything else you need for this.

**Comment by rafaelfranca** [comment]
Let me see if I get it correct, have both `secrets.yml` and `secrets.yml.enc` files with the production configuration and it is reading the `secrets.yml` instead of `secrets.yml.enc`?

**Comment by hahmed** [comment]
Yes that is correct, I have updated with the repo and a bit more information, hope that helps clarify things a little bit more. In the same I have used paperclip config, same applies for smtp settings too.

**Comment by hahmed** [comment]
@y-yagi @maclover7 so does the attached PR fix the issue with the syntax below - if added to the production.rb or the paperclip config settings?

```
ActionMailer::Base.smtp_settings = {
  user_name: Rails.application.secrets.sendgrid_username,
  password: Rails.application.secrets.sendgrid_password,
  domain: 'app-name.herokuapp.com',
  address: 'smtp.sendgrid.net',
  port: 587, # 465 for ssl connections
  authentication: :plain,
  enable_starttls_auto: true
}
```

Is there a way I can get my app to target a local rails version on my machine, so I can test this out? 

Thanks @y-yagi for the PR not too familiar with the rails source (just been reading it recently), hoping to land my first PR into the codebase 😄 soon

**Comment by hahmed** [comment]
I can confirm the fix in the attached PR works for me.

I have cherry picked the commit and added to my rails repo (hahmed/rails) so I could test this out, my production environment is working with files uploading to s3 via the config settings and emails are also getting sent out. 

Thanks @y-yagi

**Comment by y-yagi** [comment]
Thank you for your confirmation! @hahmed

**Comment by wfried** [comment]
I am currently having a very similar issue even though I'm running the release version of Rails 5.1.0, and I see a fix was merged in for that.  I have a line in my `application.rb` file as follows:
```
    config.action_mailer.smtp_settings = {
      address:              'smtp.sendgrid.net',
      port:                 587,
      user_name:            'apikey',
      password:             Rails.application.secrets.sendgrid_api_key,
      enable_starttls_auto: true
    }
```
If the password line with the Rails secret is present in this file, then Rails fails to load my encrypted secrets, only my secrets.yml.  If I comment that line out, then Rails loads my encrypted secrets as well.  Any suggestions?

**Comment by y-yagi** [comment]
The `application.rb` is read before `production.rb`.  Therefore, can not read encrypted secrets because try to read before setting `config.read_encrypted_secrets` to true in `production.rb`.
If you want to use encrypted secrets in `application.rb`, you need to add `config.read_encrypted_secrets = true` to `application.rb`. As following: 

```ruby 
# application.rb 

config.read_encrypted_secrets = true 

config.action_mailer.smtp_settings = {
  address:              'smtp.sendgrid.net',
  port:                 587,
  user_name:            'apikey',
  password:             Rails.application.secrets.sendgrid_api_key,
  enable_starttls_auto: true
} 
```

**Comment by wfried** [comment]
I have a feeling I won't be the only person to make this mistake, so thanks for taking the time to point it out!

**Comment by Immortalin** [comment]
@rafaelfranca the priority for `config.read_encrypted_secrets` should be increased, I just got bitten by the bug too

**Comment by kaspth** [comment]
@Immortalin nope, we won't be doing that. Currently we recommend encrypted secrets for production. 

We've also long encouraged moving most configs into initializers, so that's the true fix for the issue you and @wfried are seeing.

**Comment by vizcay** [comment]
I've been bitten by the exact same thing: trying to use Rails.application.secrets at config/application.rb.. two hours scratching my head wondering.. don't move read_encrypted_secrets to application.rb but please emit a warning or something because it is far from obvious what is happening.
