### ISSUE TITLE
sass @import statements being ignored in application.scss

### ISSUE THREAD

**Issue by stepheneb** [rails/rails#28628]
### Steps to reproduce

Summary: sass @import statements in application.scss appear to be ignored, instead scss files are loaded in alphabetic order.

See demo in this repo with 7 commits: https://github.com/stepheneb/sass-demo

Details (how repo linked above was created):

1. generate a new rails app using Ruby 2.4.1 and Rails 5.1.0.rc1.

```
rails new sass-demo
cd sass-demo/
bin/rails g controller welcome index
```
2. Fix root route in routes.rb (not sure why this is needed)

```
root 'welcome#index'
```

3. Add two sass files with variables defined in colors.scss.

Make two sass files: colors.scss and welcome.scss. Replace content in application.css with two sass @import statements importing colors.scss first.

file: colors.scss:
```
$backgroundcolor: rgb(200, 117, 216);
```

file: welcome.scss
```
p {
  color: $backgroundcolor;
}
```

file: application.scss:
```
@import 'colors';
@import 'welcome';
```
This works fine.

4. change name of colors.scss to z-colors.scss -- placing it after welcome.scss alphabetically and update @import statement in application.scss.

error generated: Undefined variable: "$backgroundcolor".

### Expected behavior

Should be able to @import a file defining sass variables before other sass files are processed

### Actual behavior

@import statements in application.scss appear to be ignored. Instead the scss files appear to be processed alphabetically.

### System configuration
Rails 5.1.0.rc1.
Ruby 2.4.1

**Comment by stepheneb** [comment]
A simpler description of the issue:

In a very simple rails 5.0.1.rc1 application a sass variable defined in the file `colors.scss` is available in `application.scss` -- the file that imports `colors.scss' but not in a second file, `welcome.scss` imported by `application.scss`.

file: `colors.scss`

```
$backgroundcolor: rgb(200, 117, 216);
```

file: `application.scss`

```
@import 'colors';

p {
  color: $backgroundcolor;
}
```

This works correctly.

However if I remove the p styling from `application.scss` and instead reference it from a second file `welcome.scss` Rails generates an `Undefined variable: "$backgroundcolor".` error when rendering.

file: `application.scss`

```
@import 'colors';
@import 'welcome';
```

file: `welcome.scss`
```
p {
  color: $backgroundcolor;
}
```

**Comment by stepheneb** [comment]
I rebased exampled repo to follow the details in my previous comment.

Example repo with simple Rails 5.1.rc1 app.

At this commit referencing the sass var from `application.scss` works:
https://github.com/stepheneb/sass-demo/commit/bf854ab3a02d99235db665094c3cc32d692a4140

At next commit referencing sass variable from second imported file doesn't work:
https://github.com/stepheneb/sass-demo/commit/fccec7f03b80109ff74f2cd1e9802838a12caa4d

At last commit using sass-rails v5.0.6 instead of master branch version of gem (Rails 5.1.rc1 generated github reference for sass-rails gem in Genfile) problem with second @import still present:
https://github.com/stepheneb/sass-demo/commit/ac6f3a006c4a0223a5f8615dacaa0b2a9bb1449a

**Comment by stepheneb** [comment]
The problem is with sprockets (4.0.0.beta4). See: https://github.com/rails/sass-rails/issues/396#issuecomment-296190674

**Comment by rafaelfranca** [comment]
Thank you for tracking it down. closing in favor or rails/sass-rails#396 (comment)
