### ISSUE TITLE
rails 5.1.0.rc1 --webpack - import action_cable from webpack

### ISSUE THREAD

**Issue by Danilo-Araujo-Silva** [rails/rails#28630]
### Steps to reproduce

At the cable.js file inside of a new rails appliction we find the following:

```
// Action Cable provides the framework to deal with WebSockets in Rails.
// You can generate new channels where WebSocket features live using the `rails generate channel` command.
//
//= require action_cable
//= require_self
//= require_tree ./channels
```

But if we would like use webpack, instead of assets pipelines, to import the needed files we need convert the sentences appropriately.

`require_self` is resolved using `import '/path/to/cable.js'` from somewhere.
`require_tree ./channels` is resolved using `import './channels'` for example.

But the problem is with `action_cable` because action_cable looks like is inside of a gem (for example .../.rvm/gems/ruby-2.4.1/gems/actioncable-5.1.0.rc1/lib/assets/compiled/action_cable.js
). I didn't find any npm repository so we can't load it from node_modules as usual.

How could we import it?

(Guidelines for creating a bug report are [available
here](http://guides.rubyonrails.org/contributing_to_ruby_on_rails.html#creating-a-bug-report))

### Expected behavior
Tell us what should happen

`import 'action_cable'` should be resolved correctly.

### Actual behavior
Tell us what happens instead

`import 'action_cable'` or another variations cannot be resolved correctly because action_cable.js is inside of a gem.

### System configuration
**Rails version**:
Rails 5.1.0.rc1
**Ruby version**:
ruby 2.4.1p111 (2017-03-22 revision 58053) [x86_64-linux]

**Comment by matthewd** [comment]
Please use the mailing list or StackOverflow for questions/help, where a wider community will be able to help you. We reserve the issues tracker for issues only.
