### ISSUE TITLE
Regression - Query cache is being enabled in background jobs

### ISSUE THREAD

**Issue by barthez** [rails/rails#28646]
### Steps to reproduce

Imagine model:
```ruby
class User < ActiveRecord::Base
  has_one :role
  has_one :data
end
```

and Job:
```ruby
class ProcessUsersJob < ActiveJob::Base
  def perform
    User.preload(:role, :data).find_each do
      # Prepare some report, do not save/update anything in database
    end
  end
end
```

Run the job with Delayed::Job backend.

### Expected behavior

Query cache won't be created.

### Actual behavior

Query cache is being created. While having thousands or millions of objects in `users` table we are storing cached results with keys like `SELECT roles.* FROM roles WHERE user_id IN ({1000x id})` - as 1000 is default batch size for `find_each`. It easily leads to huge memory increases.

I've noticed that it was introduced with https://github.com/rails/rails/pull/23807 (https://github.com/rails/rails/commit/5bdeb9bfd72a97ad578efc6cce95283f589f1555 to be precise)

### System configuration
**Rails version**: `Rails 5.0.2`

**Ruby version**: `ruby 2.3.3p222 (2016-11-21 revision 56859) [x86_64-darwin16]`

**Comment by maclover7** [comment]
@barthez Thank you for opening this issue! Just to confirm, before that PR / commit, you were not experiencing the issue?

**Comment by barthez** [comment]
I wasn't experiencing an issue with Rails 4.2.8 and I started experiencing it on 5.0.2. I've just narrowed suspects to this piece of code while debugging the issue.

**Comment by matthewd** [comment]
Query caching being enabled while running a job is expected behaviour. See also https://github.com/rails/rails/issues/27002 -- per my comment there, the thing we should change is that batch queries populate/use the cache, regardless of where they're being run.
