### ISSUE TITLE
gzipped JSON files are not served

### ISSUE THREAD

**Issue by kirel** [rails/rails#28648]
Rails: 5.0.2

Put `test.js` and `test.json` into `public`. Add gzipped versions. Start `rails s`.

```
$ curl  -H "Accept-Encoding: gzip" -I http://localhost:3000/test.js
HTTP/1.1 200 OK
Last-Modified: Thu, 30 Mar 2017 12:13:12 GMT
Content-Type: application/javascript
Content-Encoding: gzip
Vary: Accept-Encoding
Content-Length: ...
```

Gzipped response.

```
$ curl  -H "Accept-Encoding: gzip" -I http://localhost:3000/test.json
HTTP/1.1 200 OK
Last-Modified: Thu, 30 Mar 2017 12:13:12 GMT
Content-Type: application/json
Content-Length: ...
```

No gzipped response.

This happens due to this line:
https://github.com/rails/rails/blob/master/actionpack/lib/action_dispatch/middleware/static.rb#L89

This monkeypatch fixes my problem:
```ruby
require 'action_dispatch/middleware/static'

module ActionDispatch
  class FileHandler
    def gzip_file_path(path)
      can_gzip_mime = content_type(path) =~ /\A(?:text\/|application\/javascript|application\/json)/
      gzip_path     = "#{path}.gz"
      if can_gzip_mime && File.exist?(File.join(@root, ::Rack::Utils.unescape_path(gzip_path)))
        gzip_path
      else
        false
      end
    end
  end
end
```

But: Wouldn't a blacklist (Images/Videos/Sounds) be better than a whitelist?

**Comment by pixeltrix** [comment]
> Wouldn't a blacklist (Images/Videos/Sounds) be better than a whitelist?

From a security perspective, no - whitelists are better. However not sure whether this is for security or not so 🤷‍♂️ 

Probably best to make this a config option on `config.public_file_server` like `enabled` and `index_name`. Do you want to try to create a PR? If not then no problem - I can find someone to do it.

**Comment by matthewd** [comment]
Context here: https://github.com/rails/rails/pull/16616#discussion-diff-16576945
