### ISSUE TITLE
Nil value in SQL

### ISSUE THREAD

**Issue by thinhlvv** [rails/rails#28658]
### Steps to reproduce
```
user = User.where("role = ?", nil)
```
=> SELECT "users".* FROM "users" WHERE "users"."name" = NULL
 
(Guidelines for creating a bug report are [available
here](http://guides.rubyonrails.org/contributing_to_ruby_on_rails.html#creating-a-bug-report))

### Expected behavior
Tell us what should happen
```
user = User.where("role = ?", nil)
```
=> SELECT "users".* FROM "users" WHERE "users"."name" IS NULL

### Actual behavior
Tell us what happens instead
When we got value with `nil` SQL query should exec `IS NULL` instead of `= NULL`

### System configuration
**Rails version**:
5.0.0.1
**Ruby version**:
ruby 2.3.3p222 (2016-11-21 revision 56859) [x86_64-darwin15]

**Comment by matthewd** [comment]
The query fragment you supplied contains `=`; there's not much we can do about that.

Prefer the hash form of `where` if you want us to take care of this for you.

Please use the mailing list or StackOverflow for questions/help, where a wider community will be able to help you. We reserve the issues tracker for issues only.

**Comment by thinhlvv** [comment]
Ok, thanks for spending time @matthewd .
