### ISSUE TITLE
Percona XtraDB Cluster and advisory_lock defaults error with migrations

### ISSUE THREAD

**Issue by doberg** [rails/rails#28666]
### Steps to reproduce

Working with Percona XtraDB Cluster, MySql/InnoDB in clustered mode . PXC Strict Mode is set to ENFORCING by default.
Create a migration to add a column to a table. The migration will fail do to advisory lock being on by default. Advisory lock does table level locking instead of row level locking. This is incompatible with Pecona XtraDB Cluster. 

### Expected behavior
advisory_lock should detect to see if the DB supports advisory lock. If the DB is Percona XtraDB for example. When MySql system variable `pxc_strict_mode` is set to `ENFORCING` then `supports_advisory_locks?` should be set to false.

### Actual behavior
supports_advisory_locks is true by default. A monkey patch is required to get rails to work with MySql/InnoDB in clustered mode. Specifically Percona XtraDB Cluster. With advisory_lock required by default you cannot perform normal 'safe' migrations because table locks are prohibited by default in Percona XtraDB Cluster.

Monkey-patch needed for:

- create a new file
 app/config/initializers/advisory.rb with the following:
```
require 'active_record/connection_adapters/abstract_mysql_adapter'
ActiveRecord::ConnectionAdapters::AbstractMysqlAdapter.class_eval do
  def supports_advisory_locks?
    return false if ActiveRecord::Base.connection.execute("SELECT @@SESSION.sql_mode;").first.first.split(",").include?("STRICT_TRANS_TABLES")
    true
  end
end
```
- restart application

### System configuration
**Rails version**:
>= 5.0.0.1

**Ruby version**:
>= 2.3.3

**Comment by rafaelfranca** [comment]
Is there any  configuration in the database that tell us that the advisory lock is supported or not?

**Comment by doberg** [comment]
Yes there is: see https://www.percona.com/doc/percona-xtradb-cluster/5.7/features/pxc-strict-mode.html.

**Comment by atipugin** [comment]
Any plans to make migrations w/ advisory locks optional? It also causes problems with pgbouncer with `pool_mode = transaction`.

**Comment by doberg** [comment]
@atipugin can the pgbouncer  pool mode be queried with something like ```ActiveRecord::Base.connection.execute("SELECT @@SESSION.sql_mode;").first.first.split(",").include?("STRICT_TRANS_TABLES")```

if so we can add the query to the above code and submit a patch.

**Comment by doberg** [comment]
@rafaelfranca is this what you were looking for? ```ActiveRecord::Base.connection.execute("SELECT @@SESSION.sql_mode;").first.first.split(",").include?("STRICT_TRANS_TABLES")```

**Comment by rafaelfranca** [comment]
Yes. I think that can work. Mind to send a PR?

**Comment by atipugin** [comment]
@doberg i almost sure there is not good way to do it (expect some tricky solutions like [this](http://blog.endpoint.com/2015/05/connected-to-pgbouncer-or-postgres.html)). 

What about config option to allow turn this feature off?

**Comment by doberg** [comment]
Yea I can do that. Let me review the contribution requirements and I will submit a PR.

**Comment by doberg** [comment]
@atipugin I will keep that issue on my radar and try to figure something out in time to make it in this PR. Otherwise I will do another pr once I figure it out.

**Comment by mixail7** [comment]
Hi. @doberg have you done this PR?

**Comment by doberg** [comment]
I have not had time to figure the tests out for this. If anyone has suggestions on how to approach the tests for this that would be great.

**Comment by jbotelho2-bb** [comment]
For reference, this PR seems to add the flag discussed in this thread: https://github.com/rails/rails/pull/33691
