### ISSUE TITLE
Transactions still fire after_commit if a record is destroyed in it

### ISSUE THREAD

**Issue by bobbytables** [rails/rails#28667]
### Steps to reproduce

(Guidelines for creating a bug report are [available
here](http://guides.rubyonrails.org/contributing_to_ruby_on_rails.html#creating-a-bug-report))

* Have a model that has an after_commit on create
* Start a transaction block
* Create a record in that block
* Destroy that record in the same transaction block
* The after_commit will have fired even though the record was never technically committed

### Expected behavior
The after commit should never happen since the record was technically never committed

### Actual behavior
The after commit fires

### System configuration
**Rails version**: 4.2.7.1

**Ruby version**: 2.3.1

I have an app with 2 tests to show this bug(?) here: https://github.com/bobbytables/rails-transaction-bug/blob/master/test/models/bunk_test.rb

I'm aware this is odd, but we discovered it when someone was just deleting the record if something else happened in the transaction. We added an `after_commit` to the model and discovered that even with a `destroy` called on it, we'd still fire the after commit.

Thanks!

**Comment by meinac** [comment]
Here is a reproduction script:
```ruby
begin
  require 'bundler/inline'
rescue LoadError => e
  $stderr.puts 'Bundler version 1.10 or later is required. Please update your Bundler'
  raise e
end

gemfile(false) do
  source 'https://rubygems.org'
  # Activate the gem you are reporting the issue against.
  gem 'rails', github: 'rails/rails'
  gem 'arel', github: 'rails/arel'
  gem 'sqlite3'
  gem 'pry'
end

require 'active_record'
require 'minitest/autorun'
require 'logger'
require 'pry'

# Ensure backward compatibility with Minitest 4
Minitest::Test = MiniTest::Unit::TestCase unless defined?(Minitest::Test)

# This connection will do for database-independent bug reports.
ActiveRecord::Base.establish_connection(adapter: 'sqlite3', database: ':memory:')
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :posts, force: true do |t|
    t.string :title
    t.string :body
  end

end

$callback_call_count = 0

class Post < ActiveRecord::Base
  validates :title, presence: true

  after_commit -> { $callback_call_count += 1 }, on: :create
end

class BugTest < Minitest::Test
  def test_association_stuff
    Post.transaction do
      post = Post.create(title: 'Foo')
      post.destroy
    end

    assert_equal 0, $callback_call_count
  end
end
```

**Comment by st0012** [comment]
This is the method Rails uses to fire `after_commit` callback.
```ruby
    def committed!(should_run_callbacks: true) #:nodoc:
      if should_run_callbacks && destroyed? || persisted?
        _run_commit_without_transaction_enrollment_callbacks
        _run_commit_callbacks
      end
    ensure
      force_clear_transaction_record_state
    end
```
And the line triggers callback is `post.destroy`, which will make `destroyed?` true although it doesn't actually destroy anything.

The reason it checks `destroyed?` without checking its persistence is because after calling destroy on one object, it will be marked un-persisted. So there is no way to check if we are truly destroying a object or not in this method under current implementation.

**Comment by bobbytables** [comment]
Couldn't a solution to just implicitly add a `unless: :destroyed?` to any `after_commit on: :create` callback?

**Comment by st0012** [comment]
@bobbytables I think this is a bug and will try to fix it, but I don't know if maintainers would have same opinion.
@matthewd Would you like to give us some advice about this issue?
