### ISSUE TITLE
Strange Rails.logger behavior

### ISSUE THREAD

**Issue by ivanovaleksey** [rails/rails#28663]
Hi guys,

that is not an issue really but I stuck with Rails logger and hope to get some help.

I was playing with logging in Rails and I have noticed a strange thing.
A question I initially tried to understand was how ActiveRecord log SQL queries to console.
```
irb(main):001:0> Message.last
  Message Load (7.4ms)  SELECT  "messages".* FROM "messages"  ORDER BY "messages"."id" DESC LIMIT 1
```
I found that the output is made [here](https://github.com/rails/rails/blob/master/activerecord/lib/active_record/log_subscriber.rb#L41).
But I can't understand how does `ActiveRecord::Base.logger#debug` print both to `STDOUT` and `log/development.log`?

I create new Rails 5.0.2 application and run console.

Then I do
```
irb(main):001:0> Rails.logger.debug 'foo bar'
foo bar
=> true
```
I get _foo bar_ text both in console and `log/development.log` file.

`Rails.logger` looks like this
```
#<ActiveSupport::Logger:0x007f9545860150 @progname=nil, @level=0, @default_formatter=#<Logger::Formatter:0x007f9545860088 @datetime_format=nil>, @formatter=#<ActiveSupport::Logger::SimpleFormatter:0x007f95430b7d10 @datetime_format=nil, @thread_key="activesupport_tagged_logging_tags:70139525840520">, @logdev=#<Logger::LogDevice:0x007f9545861820 @shift_size=nil, @shift_age=nil, @filename=nil, @dev=#<File:/Users/aleksey/projects/test-logger/log/development.log>, @mon_owner=nil, @mon_count=0, @mon_mutex=#<Thread::Mutex:0x007f9545863080>>, @local_levels=#<Concurrent::Map:0x007f9545893de8 entries=0 default_proc=nil>>
```

But if I create custom logger I get text only in log file
```
irb(main):005:0* logger = ActiveSupport::Logger.new('log/development.log')
=> #<ActiveSupport::Logger:0x007f9543411588 @progname=nil, @level=0, @default_formatter=#<Logger::Formatter:0x007f9543411510 @datetime_format=nil>, @formatter=#<ActiveSupport::Logger::SimpleFormatter:0x007f9543411330 @datetime_format=nil>, @logdev=#<Logger::LogDevice:0x007f95434114c0 @shift_size=1048576, @shift_age=0, @filename="log/development.log", @dev=#<File:log/development.log>, @mon_owner=nil, @mon_count=0, @mon_mutex=#<Thread::Mutex:0x007f9543411448>>, @local_levels=#<Concurrent::Map:0x007f9543411290 entries=0 default_proc=nil>>
irb(main):006:0> logger.debug 'foo bar'
=> true
```

I don't see too much difference between `Rails.logger` and custom logger except `@thread_key` in formatter (as I can see it comes from `ActiveSupport::TaggedLogging`, I don't think it has something to do with the problem).

Does anyone know where is the problem? What I am missing?

The same thing happens with Rails 4.2.8 too.
I have Rails 4.2.8 application running on MongoDB (with mongoid gem) and there `Rails.logger.debug('foo bar')` write text **only** in log file.
It makes thing that the whole thing is somehow related to ActiveRecord.
Is it so?

Thank you.

**Comment by matthewd** [comment]
Please use the mailing list or StackOverflow for questions/help, where a wider community will be able to help you. We reserve the issues tracker for issues only.

**Comment by ivanovaleksey** [comment]
Thanks @matthewd. 
I thought wider community is here. I will create an issue on StackOverflow.
