### ISSUE TITLE
how can I make fragment cache cooperate with around filter

### ISSUE THREAD

**Issue by frozenfung** [rails/rails#28674]
### Steps to reproduce
Just found an around filter which does not cooperate with fragment cache.

I use the gem [hypernova-ruby](https://github.com/airbnb/hypernova-ruby). There is a [around filter](https://github.com/airbnb/hypernova-ruby/blob/master/lib/hypernova/controller_helpers.rb#L14-L18) which is not work as expected when it comes to fragment cache. Let me show you a simplify example below: 

```
def some_around_filter
  do_whatever
  yield
  replace_token_to_content
end
``` 
the definition of `replace_token_to_content`
```
def replace_token_to_content
  # replace token in response body to content 
  new_body = ...

  # reassign response body
  response.body = new_body
end
```

I have some tokens in response body which is going to be replaced with `replace_token_to_content` which is demonstrate in the template:

```
...
<% cache CACHE_KEY %>
  ...
  token1
  ...
  token2
  ...
<% end %>
...
```

Eventually, it seems like that rails' fragment cache will cache the token rather content.

### Expected behavior
It suppose to cache content not token

### Actual behavior
It cache token

### System configuration
**Rails version**: 5.0.2

**Ruby version**: 2.3.3

I am not familiar with Rails codebase so I just fool around for a while and get nothing. Any advice?

thanks

**Comment by st0012** [comment]
The rendering process happens in around filter's `yield` part, including the execution of fragment cache. So `replace_token_to_content` will only see the rendering result (ruby string, not erb template) because it's placed after the yield. What ever you want to cache should be processed before or during the yield and inserted to template before rendering.
