### ISSUE TITLE
Rails child controllers don't inherit parent controller helper module

### ISSUE THREAD

**Issue by smartYi** [rails/rails#28679]
### Steps to reproduce
I defined an `ApplicationController` and `ApplicationHelper` module. And then define another helper module `CommonHelper` and declare use in `ApplicationController`  like this:

```
class ApplicationController < ActionController::Base
    protect_from_forgery with: :exception
    helper CommonHelper
end
```
And then define another Controller `IndexController` like this:

```
class IndexController < ApplicationController
    def some_action
    end
end
```

And then I access `index#some_action` and will reuse some helper methods already defined in `ApplicationHelper` and `CommonHelper`
### Expected behavior
It should render view template successfully 

### Actual behavior
It can't fetch helper methods defined in `ApplicationHelper` and `CommonHelper` and also I print out some debugging message, it looks like it even didn't go through `ApplicationController` firstly and jump directly to `IndexController`

### System configuration
**Rails version**:
4.2
**Ruby version**:

**Comment by maclover7** [comment]
@smartYi Are you able to reproduce this issue on `5-1-stable` or Rails master?

**Comment by pixeltrix** [comment]
@smartYi by default Rails will include all helpers in `app/helpers` in all views - are you doing something to change this default? It's really hard to debug this without reproduction steps or a example repo - can you please supply one, thanks.

**Comment by adityakapoor-homebell** [comment]
Let me take a stab at this, we recently faced a similar issue on Rails 4.2 but not sure if it is the same issue or not?

**Comment by aditya-kapoor** [comment]
Let me take a stab at this, we recently faced a similar issue on Rails 4.2 but not sure if it is the same issue or not?

**Comment by smartYi** [comment]
@pixeltrix Hmm. I faced this issue when I made code changes to my company codes. BTW, this issue occurred in rails engine rather than in main app. It looks like the main app can serve properly but not in rails engine.

**Comment by pixeltrix** [comment]
@smartYi if you used isolated engines then that may have affected the visibility of helpers - if you read the docs on engines it explains how to access isolated engine helpers in the main app and vice-versa.

http://api.rubyonrails.org/classes/Rails/Engine.html
