### ISSUE TITLE
ActiveRecord::Persistence#reload does not support STI

### ISSUE THREAD

**Issue by chikamichi** [rails/rails#28689]
When using [Single Table Inheritance](http://api.rubyonrails.org/classes/ActiveRecord/Inheritance.html), creating a new "parent" record while setting its type at the same time, then calling [`reload`](https://github.com/rails/rails/blob/de2bca4e8513d59c1a4f131e6fc6386231db1f82/activerecord/lib/active_record/persistence.rb#L447) on it, returns an object of the parent type instead of the child type.

### Steps to reproduce

``` ruby
class Company < ActiveRecord::Base; end
class Firm < Company; end

my_firm = Company.create(type: 'firm')
my_firm.reload # => #<Company id:1 …>
```

### Expected behavior

Returning `#<Firm id:1 …>`. Not changing `self` as it's dead-impossible, ie. `my_firm` remains a `Company` instance.

#### Rational

In the case of STI, it *could* come in handy returning not `self`, but an instance of the expected class instead. It sure wouldn't be a "reload" of the instance it`self`, but it would abide by this instance's state and play along `reload`'s idea of cache-busting. Just a proposal, not a big proponent :)

#### Use-case

Such a behavior of returning an instance of the "true" class would be useful when dealing with dynamic assignment of the type, and/or when one has to use (as in: there's a dependency over legacy or third-party code) the parent class at creation time but then wants to rely on a child-specific API to move forward with that instance.

This behavior seems not to introduce unwanted side effects besides breaking the principle of least surprise; but then `reload` could support STI through an opt-in option alongside `.lock`, or STI tables could tweak `reload`'s behavior specifically, and may do so optionally.

### Actual behavior

Returns `#<Company id:1 …>`, for `reload` refreshes the model (`self`) it's been called onto and returns that very `self`, only up-to-date, discarding that model's type altogether.

### System configuration

**Rails version**: any up to current as of date.

**Ruby version**: any.

**Comment by chikamichi** [comment]
I'm interested in contributing with a PR but would like to gather some feedback about this issue's revelancy first :)

**Comment by louim** [comment]
Maybe you forgot to add the `type` [column to the table](http://api.rubyonrails.org/classes/ActiveRecord/Inheritance.html)?
> If you don't have a type column defined in your table, single-table inheritance won't be triggered. In that case, it'll work just like normal subclasses with no special magic for differentiating between them or reloading the right type with find.

See this gist showing it working as intented: https://gist.github.com/louim/ed2dd9039113707603713cf4c338cd0e

**Comment by chikamichi** [comment]
The classes use the default `type` column whcih is defined and part of db/schema.rb. I'll investigate your example and test it against my stack, which happens to be Rails 3.2.

**Comment by matthewd** [comment]
Yeah, no. `reload` returns `self`, and changing that is going to confuse too many things.

As @louim noted, current AR versions should already return the right class from the `create` for this example. That feeds into the above point: if the current class doesn't match `type`, someone has likely gone out of their way to arrange that, suggesting it's not something for `reload` to "fix".

If you do end up with an instance of the base class where you need the specific one, you can use `becomes` (or, more carefully, `becomes!`).
