### ISSUE TITLE
Rails Security Guide - Session Fixation

### ISSUE THREAD

**Issue by sidk** [rails/rails#28683]
Given that cookies in Rails are encrypted, signed and contain a lot more information than just the session_id, how would one actually modify `session_id` in a session fixation attack?

It looks to me that even if we didn't reset the session on login, the fact that cookies can't be modified on a granular level (assuming Rails defaults) prevents this attack from being viable. Is this right?

**Comment by rafaelfranca** [comment]
Please use the mailing list or StackOverflow for questions/help, where a wider community will be able to help you. We reserve the issues tracker for issues only.

**Comment by sidk** [comment]
Hi @rafaelfranca, I think the guide should be updated with this info - the fact that on default, because Rails encrypts and signs cookies, session fixation as described in the guide is not possible.

Happy to PR this if you agree.

**Comment by rafaelfranca** [comment]
The guide is not talking about Rails specifically. It explain how a session fixation attack happens.

**Comment by sidk** [comment]
In the "Session FIxation - Countermeasures" section, Rails is mentioned specifically. The implication that your app is vulnerable if you don't have the `reset_session` line post-login is not entirely right because of the fact that cookies are encrypted and signed. That being said, calling `reset_session` is still a good practice.

**Comment by rafaelfranca** [comment]
Where it is saying that your application is vulnerable if you don't do that? As I read it is recommending you to follow the best practice and I think we should still do that regardless Rails is not vulnerable by default or not.

**Comment by sidk** [comment]
It doesn't say that directly - as I said it is implied (it says "One line of code will protect you against session fixation", which implies that if you don't have this line you're not protected). Agree that `reset_session` should be done. I'm not proposing that we remove this. 

All I'm saying is that since the section is named "Session Fixation - Countermeasures", and having encrypted+signed cookies is a countermeasure, we could mention this in the guide.
