### ISSUE TITLE
Websocket error code 1006 in iOS

### ISSUE THREAD

**Issue by viniciodeltoro** [rails/rails#28690]
I'm trying to connect to my actioncable service from my iOS app created with Nativescript. I'm using the actioncable js file provided by this project. The code works properly (connection successful) when I do the testing in my Android app, and the test works properly on the web browser as well. but It doesn't work in iOS. I did a [post](https://github.com/NathanaelA/nativescript-websockets/issues/25) on this project repo (since I'm using that plugin) and also in [Stackoverflow](http://stackoverflow.com/questions/43175006/getting-websocket-error-code-1006-when-trying-to-connect-to-actioncable-server). In the response NathanaelA says it may be related to a compression config happening on the server.
Any ideas on why this error is happening when trying to do the handshake?
Thanks

**Comment by rafaelfranca** [comment]
Please use the mailing list or StackOverflow for questions/help, where a wider community will be able to help you. We reserve the issues tracker for issues only.
