### ISSUE TITLE
Italics block in section 2.6 of security.md not terminating properly

### ISSUE THREAD

**Issue by eebbesen** [rails/rails#28691]
Documentation bug.

The last sentence of section 2.6 Replay Attacks for CookieStore Sessions is displaying improperly due to the italicization of the first sentence.

> The best solution against it is not to store this kind of data in a session, but in the database_. In this case store the credit in the database and the logged_in_userid in the session.

When I preview this markdown using Sublime Text 3 it looks ok and that's why I'm not submitting a PR.  I suspect an escape of the period in `_.` at the end of the first sentence might help.  What it looks like is the second `_` is not being recognized as the end of the italicized block.  The italics continue until `user` in `logged_in_userid`.

### Steps to reproduce
Browse to http://guides.rubyonrails.org/v3.2.16/security.html#sessions.  Go to the last paragraph of section 2.6 and note the italics don't terminate properly.

### Expected behavior
Only the first sentence should be italicized.

### Actual behavior
Italics continue through the second sentence of the paragraph.  The terminating `_` in the first sentence is visible.

### System configuration
**Rails version**:
n/a
**Ruby version**:
n/a

**Comment by eebbesen** [comment]
<img width="698" alt="screen shot 2017-04-06 at 8 37 46pm" src="https://cloud.githubusercontent.com/assets/2716636/24781976/ef223fac-1b08-11e7-866d-dd2a194b6267.png">

**Comment by maclover7** [comment]
@eebbesen Thank you for opening up this issue! Would you be willing to send a PR to fix this?

**Comment by matthewd** [comment]
The current version seems to be formatted correctly.
