### ISSUE TITLE
ActiveRecord sandbox causes postgres locking

### ISSUE THREAD

**Issue by mikebaldry** [rails/rails#28694]
### Steps to reproduce

related to: https://github.com/rails/rails/issues/26570

If you use the ActiveRecord sandbox in a console, to create a "read only" environment, it locks tables until you close that console. If you try and migrate while a console is open, everything gets locked up and your website becomes unresponsive.

### Expected behavior
A sandbox should not have any side effects

### Actual behavior
Side effects in the form of long-held postgres locks which cause other problems

### System configuration
**Rails version**: Any version that includes https://github.com/rails/rails/blob/master/activerecord/lib/active_record/railties/console_sandbox.rb - which I guess is all?

**Ruby version**: All

**Comment by maclover7** [comment]
Hi @mikebaldry! Are you experiencing the locking behavior with other database adapters, or is it only with Postgres?

**Comment by matthewd** [comment]
This is expected behaviour: the sandbox works by executing inside a database transaction, so that it can make changes and then roll them back.

**Comment by mikebaldry** [comment]
@mathewd I understand it is expected behaviour, I just think that in a production environment if you use this as a failsafe, you probably should know that if you have a sandboxed console open and try to migrate your database, it'll lock up and your site will go down.
