### ISSUE TITLE
Rails Security Guide - SafeErb Recommendation

### ISSUE THREAD

**Issue by sidk** [rails/rails#28700]
The Rails Security Guide mentions the "SafeErb plugin" as a recommendation to catch XSS errors. From what I can tell, this plugin is essentially abandonware (this is the repo I found: https://github.com/abedra/safe-erb), and the guide should be updated to recommend something like brakeman. Happy to PR if you agree.

**Comment by rafaelfranca** [comment]
It was already removed in the edge guide
