### ISSUE TITLE
(Rails 4.2/5) StatementInvalid error when using includes() on a has_many :through with a custom scope

### ISSUE THREAD

**Issue by aergonaut** [rails/rails#28703]
### Steps to reproduce

1. Have 3 models (e.g. User, Group, Membership). Groups can be `fancy` or not and have a scope to filter to only fancy groups. User `has_many :memberships` and also `has_many :groups, through: :memberships`. User _also_ `has_many :fancy_groups, -> { fancy }, through: :memberships`.
2. Try to do `User.includes(:fancy_groups)`.

I have uploaded examples demonstrating the error to this Gist: https://gist.github.com/aergonaut/7ebd847721f64087c99de7249767468c

Here's the Rails 4.2 version inline:

```ruby

require 'bundler/inline'

gemfile(true) do
  source "http://rubygems.org"

  gem "activerecord", "~> 4.2"
  gem "sqlite3"
end

require "active_record"
require "minitest/autorun"
require "logger"

ActiveRecord::Base.establish_connection(adapter: "sqlite3", database: ":memory:")
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :users, force: true do |t|
  end

  create_table :groups, force: true do |t|
    t.boolean :fancy
  end

  create_table :memberships, force: true do |t|
    t.integer :user_id
    t.integer :group_id
  end
end

class User < ActiveRecord::Base
  has_many :memberships
  has_many :groups, through: :memberships
  has_many :fancy_groups, -> { fancy },
    class_name: "Group",
    through: :memberships,
    source: :group
end

class Group < ActiveRecord::Base
  has_many :memberships
  has_many :users, through: :memberships

  scope :fancy, -> { where(fancy: true) }
end

class Membership < ActiveRecord::Base
  belongs_to :user
  belongs_to :group
end

class IssueTest < Minitest::Test
  def setup
    user = User.create!

    group1 = Group.create!
    group2 = Group.create!(fancy: true)

    user.groups << group1
    user.groups << group2
    user.save!
  end

  def test_fancy_groups_includes
    User.includes(:fancy_groups).to_a
  end
end
```

### Expected behavior

`User.include(:fancy_groups)` should execute successfully.

### Actual behavior

StatementInvalid error is thrown instead:

```
ActiveRecord::StatementInvalid: SQLite3::SQLException: no such column: groups.fancy: SELECT "memberships".* FROM "memberships" WHERE "groups"."fancy" = ? AND "memberships"."user_id" = 1
```

### System configuration
**Rails version**: 4.2 or 5

**Ruby version**: ruby 2.3.1p112 (2016-04-26 revision 54768) [x86_64-darwin15]

**Comment by al2o3cr** [comment]
FWIW, the test above will pass if you use `User.includes(:fancy_groups).references(:fancy_groups)`.

**Comment by maclover7** [comment]
@aergonaut Hmm, I think you're going to have to add a `references` here... How else would Active Record know about the `fancy` column on `groups`?

**Comment by matthewd** [comment]
This is a bug.

**Comment by aergonaut** [comment]
@al2o3cr @maclover7 @matthewd Thanks all for the responses.

I had noticed that `references` makes the query correct. However, I would expect that ActiveRecord would know how to pull in the right tables automatically, especially since if I just use the association directly, or use it in `joins`, the SQL is correct. It's just `includes` that is different.

```ruby
def test_accessing_association
  user = User.first
  assert_equal user.fancy_groups.to_a, Group.fancy.to_a
end

def test_joining_association
  User.joins(:fancy_groups).where(groups: { id: 2 }).to_a
end
```

I have a patch to `ActiveRecord::Associations::Preloader#through_scope` that I made for the project I noticed this in. I basically just made it also spawn a references for the source association in the case that the reflection scope had any where values. I could try to work it into a PR if that'd be good?

**Comment by matthewd** [comment]
Yes please, that sounds like a good start.

There's some potential complication in the fact that other query parts (e.g. `order`) could also be referencing the table. We might essentially have to apply the `references` any time the association has a block scope argument. But we can see that once we have a start, and can think through other reasonable test cases. (And ensure any such change doesn't interfere with any existing behaviour.)

**Comment by rafaelfranca** [comment]
This should be fixed by https://github.com/rails/rails/pull/29413
