### ISSUE TITLE
default_url_options are ignored when GET form is sent

### ISSUE THREAD

**Issue by LukasSkywalker** [rails/rails#28716]
### Steps to reproduce

* Set `default_url_options` as explained in the [i18n guide](http://guides.rubyonrails.org/i18n.html#setting-the-locale-from-url-params)
* Create a form having `get` as the method
* Submit the form

### Expected behavior
The form should send the browser to a page having all form inputs as query params _including_ the `default_url_options`.

### Actual behavior
`default_url_options` get ignored. This breaks i18n setups, resetting the locale to the `default_locale`

See [this gist](https://gist.github.com/LukasSkywalker/594dee2b6448a2e37aa912fdeafc0858) for an isolated test case

### System configuration
**Rails version**: 5.1.0.rc1

**Ruby version**: 2.2.2p95

**Comment by LukasSkywalker** [comment]
I realize Rails does set the `default_url_options` in the action attribute of the form but it is discarded on submit. This behaviour is correct according to the HTML spec: https://www.w3.org/TR/2011/WD-html5-20110525/association-of-controls-and-forms.html#form-submission-algorithm, heading "Mutate action URL".

**Comment by henrik** [comment]
I know this is an old issue, but adding it here for googleability:

If you don't want to manually add hidden inputs to forms, you could have JavaScript do it for you – here's a stab using jQuery, to pass along a param named "s":

```
$("form[action]").each(function() {
  var $form = $(this);
  var m = $form.attr("action").match(/[?&](s)=(.+?)(&|$)/);
  if (m) {
    $("<input/>", { type: "hidden", name: decodeURIComponent(m[1]), value: decodeURIComponent(m[2]) }).appendTo($form)
  }
})
```
