### ISSUE TITLE
AR behaviour regarding date_trunc('month', x) changed in 4.2.8

### ISSUE THREAD

**Issue by michaelsauter** [rails/rails#28719]
I inherited a piece of code which reads like this and works in 4.2.7:
```ruby
month = DateTime.parse("2017-03-01")
Invoice.where("date_trunc('month',invoice_date) = ?", month).count # not zero
```
However, in 4.2.8, the same code piece returns zero results. However, it can be fixed either by
```ruby
Invoice.where("date_trunc('month',invoice_date) = ?", month.to_date).count
```
or
```ruby
Invoice.where("date_trunc('month',invoice_date) = ?::date", month).count
```
Ruby version is 2.2.4, database is Postgres 9.5. I read https://github.com/rails/rails/blob/v4.2.8/activesupport/CHANGELOG.md#rails-428-february-21-2017 before upgrading but did not realize the changes would affect the code in question.

Of course the code should convert the month to a date in any case, but I'm still wondering if the new behaviour is an intentional consequence of the changes to date/time handling in 4.2.8?

**Comment by matthewd** [comment]
cc @pixeltrix

**Comment by pixeltrix** [comment]
@michaelsauter do you have a comparison of the two queries generated?

**Comment by pixeltrix** [comment]
Hmm, just tried this locally and I get the same query in 4.2.7.1 and 4.2.8 - @michaelsauter can you please let me know all the related settings such as DB timezone, whether Active Record is using `:local` or `:utc` to store timestamps, your app's timezone, the OS timezone and the setting of `to_time_preserves_timezone`, thanks.

**Comment by michaelsauter** [comment]
@pixeltrix Thanks for getting back so quickly.

* DB timezone: `Europe/Berlin`
* `config.active_record.default_timezone = :local`
* `config.time_zone = 'Berlin'`
* `ActiveSupport.to_time_preserves_timezone` is `false`

I've run the queries again and they do differ for me:

4.2.8:
```
SELECT COUNT(*) FROM "invoices" WHERE (date_trunc('month',invoice_date) = '2017-03-01 01:00:00.000000')
```

4.2.7.1:
```
SELECT COUNT(*) FROM "invoices" WHERE (date_trunc('month',invoice_date) = '2017-03-01 00:00:00.000000')
```

**Comment by pixeltrix** [comment]
@michaelsauter I assume the system timezone is `Europe/Berlin` too? If so I think what it's doing now in 4.2.8 is actually correct, e.g.

```
>> Time.zone = 'Europe/Berlin'
=> "Europe/Berlin"
>> ENV['TZ'] = 'Europe/Berlin'
=> "Europe/Berlin"
>> DateTime.parse('2017-03-01').utc_offset
=> 0
>> DateTime.parse('2017-03-01').to_time.to_s(:db)
=> "2017-03-01 01:00:00"
```

Effectively, the `DateTime` you've created is in UTC so when it's converted to local format for the database it gets the extra hour of CET. However I'm not entirely sure that it's due to the changes in date/time support for Ruby 2.4 - `DateTime` in Rails 4.2.7.1 behaves in the same way. I'm going to look at the Active Record type casting code to see if there's any changes there that may account for it.

**Comment by michaelsauter** [comment]
Oh, good to know that `DateTime.parse` is actually in UTC even if the timezone in Rails is not UTC. I never checked but assumed it would take the Rails timezone into account. `DateTime.now` does ...

**Comment by michaelsauter** [comment]
I don't think this needs to be reproduced as such on master/5.1. The new behaviour is correct, the old was wrong. There was a change from 4.2.7 to 4.2.8 that was not intended/communicated, but it seems not many people got tripped up by this. I'm closing this now.
