### ISSUE TITLE
Setting default_url_options in controller does not work

### ISSUE THREAD

**Issue by malikolivier** [rails/rails#28714]
### Steps to reproduce

As the [doc](https://apidock.com/rails/ActionController/Base/default_url_options) says, I set up default_url_options. 

```rb
class ApplicationController < ActionController::Base
  def default_url_options
    { locale: I18n.locale }
  end
end
```

The default url options would never show up in any of the url helpers I tried.

After some investigations in Rails 5 source code, I found that this monkey patch seems to work in setting `default_url_options`:

```rb
module ActionDispatch
  module Routing
    module UrlFor
      def default_url_options
        { locale: I18n.locale }
      end
    end
  end
end
```

### Expected behavior

I would have expected that defining default_url_options in ApplicationController would work. Instead it did not.

The comments in the code [here](https://github.com/rails/rails/blob/34fe2a4fc778d18b7fe6bdf3629c1481bee789b9/actionpack/lib/action_dispatch/routing/url_for.rb#L109) seems to imply that the override in application controller should work.

Did I miss something? Is it the expected behavior?

I made a test case demonstrating the issue in this gist:
https://gist.github.com/malikolivier/065048bd243b0ab768683232fe8ad84b

### System configuration
**Rails version**: 2.3.4

**Ruby version**: 5.0.2

**Comment by st0012** [comment]
I thinks this is related to #26040?

**Comment by malikolivier** [comment]
@st0012 I cannot say my original post is related with the issue you pointed it.

By the way, now I get very strange results with the monkey patch above. The issue below happens from time to time inside my views (I cannot reproduce it when I want) and I can reproduce it by running all my tests in a loop and and need to wait a few iterations before it happens (wait, seriously?):

```sh
while true; do  bin/rails test; done
```

After a few iterations, of the above loop my tests would fail at some point because I get this kind of output out of some URL generators:
 
```rb   
> edit_external_autopsy_url(@autopsy)
=> "http://www.example.com/autopsies/979617184/edit_external?locale=en.json"
```

Though my default locale should be ja and I never ever gave "*.json" values to my locale. Afterwards, all the views would throw exceptions when looking for the translations as it will find no translation data with "en.json" as a locale).

Should I give up using URL generators with default? It seems that URL generators are completely unreliable. This issue does look like to be related to #26040 now. My tests always succeed if I set up the locale manually using:

```rb
edit_external_autopsy_url(@autopsy, locale: :ja)
```

**Comment by pixeltrix** [comment]
@malikolivier in your test example you assert on the value generated by `root_path` in the test but you override `default_url_options` in the controller. These are two completely different contexts and it's the expected behaviour. The reason your monkey patch works is because you're overwriting the `default_url_options` defined in the module that gets included into `Rails.application.routes.url_helpers`.

Can you adjust your test to `render plain: root_path` and assert on the response body? That would be a more accurate test of whether `default_url_options` is being overridden correctly.

**Comment by malikolivier** [comment]
@pixeltrix Thanks! You are right. The test is successful when url_helpers are run inside the controller's context.
See this gist: https://gist.github.com/malikolivier/44d60e8ba8eba21c84c157cd42d79645

But I have another questions. First I think the documentation should be clearer and states that it only works in a controller's context. Poor stupid me assumed it should work in any context.
Secondly, is there any way to set `default_url_options` inside the views' context?

**Comment by pixeltrix** [comment]
@malikolivier I think this comes back to #26040 as @st0012 said - `controller.url_options` is being cached without your overridden `default_url_options` being added.
