### ISSUE TITLE
Freeze attributes when I create new Active record object with them

### ISSUE THREAD

**Issue by skosh** [rails/rails#28718]
I faced one unexpected behavior: when I have one new active record object and build second with first's attributes, attributes of first object will be frozen.

For example:
I have ActiveRecord model 'User' with 2 attributes - 'first_name' and 'last_name'
### Steps to reproduce
```ruby
user = User.new(first_name: 'Alex', last_name: 'Kosh')
user.first_name.frozen? #=> false
User.new(user.attributes)
user.first_name.frozen? #=> true
```

### Expected behavior
user.attributes are not frozen

### System configuration
Rails version: 5.0.2
Ruby version: 2.3.3

**Comment by alexcameron89** [comment]
Hey @skosh, I've tried to reproduce the issue with a test script, but I was not able to. 

To demonstrate the problem you are seeing, can you try to reproduce it in an executable test script using one of the templates [here](https://github.com/rails/rails/tree/master/guides/bug_report_templates)? 

[This](https://gist.github.com/alexcameron89/a8e28afb1e0dd4aa0e171535d8f69712) is the script I used if you want to modify it.

**Comment by skosh** [comment]
Hey @alexcameron89, It's too weird: test will pass for me if I run your test script like "ruby 28718.rb". But when I execute test script in irb console, the issue will apear.
Could you execute code from you test script in irb console and after 'User' class declaration you will see the issue.
```ruby
...
2.3.3 :028 > class User < ActiveRecord::Base
2.3.3 :029?>   end
 => nil
2.3.3 :030 > user = User.new(first_name: 'Alex', last_name: 'Kosh')
 => #<User id: nil, first_name: "Alex", last_name: "Kosh">
2.3.3 :031 > user.first_name.frozen?
 => false
2.3.3 :032 > User.new(user.attributes)
 => #<User id: nil, first_name: "Alex", last_name: "Kosh">
2.3.3 :033 >
2.3.3 :032 > user.first_name.frozen?
 => true
```

**Comment by alexcameron89** [comment]
That is interesting, I can reproduce that issue in IRB and Pry.
``` ruby
From: /home/alex/library/Github/peruse/a8e28afb1e0dd4aa0e171535d8f69712/28718.rb @ line 36 :

    31: end
    32: 
    33: user = User.new(first_name: 'Alex', last_name: 'Kosh')
    34: puts "user.first_name.frozen?: #{ user.first_name.frozen? }"
    35: 
 => 36: binding.pry
    37: User.new(user.attributes)
    38: 
    39: puts "user.first_name.frozen?: #{ user.first_name.frozen? }"

[1] pry(main)> User.new(user.attributes)
=> #<User:0x00000007574b60 id: nil, first_name: "Alex", last_name: "Kosh">
[2] pry(main)> user.first_name.frozen?
=> true
```

**Comment by rafaelfranca** [comment]
Maybe it is related with inspecting the object? Try to change the test script to inspect the object before testing it is frozen.

**Comment by alexcameron89** [comment]
@rafaelfranca I thought that might be it, but neither `user.inspect` nor `user.attributes.inspect` seem to be freezing it:
``` ruby
[1] pry(main)> user.inspect
=> "#<User id: nil, first_name: \"Alex\", last_name: \"Kosh\">"
[2] pry(main)> user.first_name.frozen?
=> false
[3] pry(main)> user.attributes.inspect
=> "{\"id\"=>nil, \"first_name\"=>\"Alex\", \"last_name\"=>\"Kosh\"}"
[4] pry(main)> user.first_name.frozen?
=> false
```

I had the same results in the test script as well.

**Comment by rafaelfranca** [comment]
I see. Thanks for checking. If it is only reproducible inside a debug session it is related to that debug session. If it is not inspect it may be something that is only executed when in a debug session. I don't see anything in the Active Record code that is only loaded in a debug session.

**Comment by rafaelfranca** [comment]
I could reproduce the issue in the script. It was indeed related with inspect:

https://gist.github.com/rafaelfranca/dd0a2d32397fd9c3a596a349e6601309

**Comment by alexcameron89** [comment]
Ahh, I see! I was inspecting the wrong thing. I have found from `git bisect` that it looks to be introduced by 34321e4a433bb7eef48fd743286601403f8f7d82.

**Comment by rafaelfranca** [comment]
Nice finding 👍

**Comment by alexcameron89** [comment]
It's happening because the `user`'s strings are being saved in `x`'s attributes as the **FromUser's** `@value_before_type_cast`. 
``` ruby
(byebug) user.first_name.__id__
67550100

# from x's @attributes
(byebug) @attributes["first_name"].value_before_type_cast.__id__
67550100
```
In ActiveModel's `ImmutableString`, it [freezes x's @value_before_type_cast](https://github.com/rails/rails/blob/master/activemodel/lib/active_model/type/immutable_string.rb#L26) to reduce allocations, freezing the same object that is user's `first_name`.

@rafaelfranca would it be reasonable to a "deep clone" of the attributes that are passed into new so the new object would have its own unique objects?

**Comment by vishalzambre** [comment]
I tried [this](https://gist.github.com/vishalzambre/f8a4bb6c02ba9958994ca3439d151e71) script and It reproduced above issue.

I tried with AR class and Ruby class, issue is reproduced with AR class, only after inspect it.

**Comment by kaspth** [comment]
Also related to https://github.com/rails/rails/issues/24185#issuecomment-236202826

**Comment by alexcameron89** [comment]
I updated my reproduction script with an additional test that fails. If you mutate a string that you pass in as a parameter, it mutates the object's attribute as well.:
``` ruby
  def test_mutated_name
    first_name = "Alex_Capitalized"
    user = User.new(first_name: first_name)
    first_name.downcase!

    assert_equal "Alex_Capitalized", user.first_name
    assert_equal "#<User id: nil, first_name: \"Alex_Capitalized\", last_name: nil>", user.inspect
  end
```
