### ISSUE TITLE
ActionController::Parameters fails to merge

### ISSUE THREAD

**Issue by libin0120** [rails/rails#28725]
### Steps to reproduce

When I have two set of parameters needed to be merge together before filter them using strong parameters, I get failed to merge them. A sample can be reproduced using Rails console
```
irb(main):025:0> a = {"a": 1}
=> {:a=>1}
irb(main):026:0> b = {"b": 2}
=> {:b=>2}
irb(main):027:0> pa = ActionController::Parameters.new(a)
=> <ActionController::Parameters {"a"=>1} permitted: false>
irb(main):028:0> pb = ActionController::Parameters.new(b)
=> <ActionController::Parameters {"b"=>2} permitted: false>
irb(main):029:0> pa.merge!(pb)
=> <ActionController::Parameters {"a"=>1} permitted: false>
irb(main):030:0> pa
=> <ActionController::Parameters {"a"=>1} permitted: false>
irb(main):031:0>
```

### Expected behavior
Tell us what should happen
pa should have both {"a"=>1, "b"=>2}

### Actual behavior
Tell us what happens instead
pa is still {"a"=>1}

### System configuration
**Rails version**:
5.0.2

**Ruby version**:
ruby 2.3.1p112

**Comment by rafaelfranca** [comment]
This is the expected behavior. Since the `pb` instance of `ActionController::Parameters` doesn't have any permitted parameter it is like it was empty. So you are merging `pa` with an empty hash
