### ISSUE TITLE
Time#change doesn't allow to change offset

### ISSUE THREAD

**Issue by abotalov** [rails/rails#28723]
### Steps to reproduce
> Time.now.change(offset: 0)
=> 2017-04-10 17:35:53 +0300
> DateTime.now.change(offset: 0)
=> Mon, 10 Apr 2017 17:35:57 +0000

### Expected behavior
`Time#change` should have `:offset` option just like DateTime.
> Time.now.change(offset: 0)
=> 2017-04-10 17:35:53 +0000

### Actual behavior
`Time#change` doesn't have `:offset` option.

### System configuration
**Rails version**:
4.2

**Ruby version**:
2.2

**Comment by maclover7** [comment]
cc @pixeltrix
