### ISSUE TITLE
Use ancora in render

### ISSUE THREAD

**Issue by frankyston** [rails/rails#28732]
Hi I would like to know if there is any support for anchoring any method to do in a controller action.

### Steps to reproduce
Render action :: index, slug: params [: slug], anchor: "new_participant"

### Expected behavior
Render a view with the link of the activated ring

### Actual behavior
Rendered the page without activating the anchor

### System configuration
**Rails version**: Rails 5.0.2

**Ruby version**:ruby 2.4.0p0 (2016-12-24 revision 57164) [x86_64-linux]

**Comment by rafaelfranca** [comment]
Please use the mailing list or StackOverflow for questions/help, where a wider community will be able to help you. We reserve the issues tracker for issues only.

**Comment by rafaelfranca** [comment]
The answer is: render only render the file it doesn't tell the browser which URL it should go. This was already told by the link they clicked or the form that was submitted. If you want to change were to go you need to tell the browser to go to other place and the only way to do that is with a redirect.

**Comment by frankyston** [comment]
I understood Rafael, thank you for clarifying.
