### ISSUE TITLE
String to BigDecimal for empty string throws exception

### ISSUE THREAD

**Issue by vishalzambre** [rails/rails#28738]
### Steps to reproduce

When tried to convert empty string to bigdecimal if throws exception'
```
ArgumentError: invalid value for BigDecimal(): ""
```

This is more related to ruby, I checked ruby code. This issue is fixed with ruby `trunk` branch not backported to any stable versions.

[Here](https://gist.github.com/vishalzambre/d51a0b6b3668719d8bc6744c1c5ec15e) is script to reproduce.

### Expected behavior

It should return 0 for empty string as `to_f`, `to_i` returns

### Actual behavior
Throwing an exception

### System configuration
**Rails version**:
  master branch
**Ruby version**:
2.4.0 and 2.4.1

**Comment by pixeltrix** [comment]
This is fixed in version 1.3.2 of the bigdecimal gem as described here:

https://bugs.ruby-lang.org/issues/13062
