### ISSUE TITLE
`pluck` disregards preloaded data

### ISSUE THREAD

**Issue by toby-1-kenobi** [rails/rails#28747]
### Steps to reproduce

In the controller:
`@users = User.includes(:posts)`

In the view:
`@users.each{ |user| user.posts.pluck(:title) }`

### Expected behaviour
pluck shouldn't issue a database query to get the post title since posts have been preloaded by `includes`. It should behave in the same way as
`@users.each{ |user| user.posts.map(&:title) }`

### Actual behaviour
`pluck` issues a new query for each user retrieving posts

### System configuration
**Rails version**: 4.2.6

**Ruby version**: 2.3.0p0

**Comment by kamipo** [comment]
Fixed in #25976.
