### ISSUE TITLE
ActionCable's stream_for creates channel identifiers are too long for postgres

### ISSUE THREAD

**Issue by twfarnam** [rails/rails#28751]
The `stream_for` method of `ActionCable::Channel` can make database identifiers that are invalid for Postgres, which has a 63 character limit. I am using UUIDs for ids in my database and `stream_for` uses `to_gid_param` to make the name, creating an identifier that is often over 80 characters. I was able to get things to work by just using `model.id` instead of `model.to_gid_param` as in the [base class](https://github.com/rails/rails/blob/92703a9ea5d8b96f30e0b706b801c9185ef14f0e/actioncable/lib/action_cable/channel/broadcasting.rb#L21).

Fix in app/channels/application_cable/channel.rb:

````ruby
module ApplicationCable
  class Channel < ActionCable::Channel::Base

    def self.broadcasting_for(model)
      case
      when model.is_a?(Array)
        model.map { |m| broadcasting_for(m) }.join(":")
      when model.respond_to?(:id)
        model.id
      else
        model.to_param
      end

    end
````

**Comment by edwardmp** [comment]
I imagine `to_gid_param` being used to avoid collisions with records of other models that would have the same numeric id.

**Comment by matrix9180** [comment]
Storing a smaller hash of the gid should keep uniqueness and meet size constraints. SHA1 is 40 characters, and should be random enough for this task.

**Comment by palkan** [comment]
@twfarnam Do you store broadcasting identifiers in database? What for?

**Comment by twfarnam** [comment]
Ah, yes, I'm using the postgres adapter for ActionCable so that's the reason it needs to be in postgres. Not sure how common that is but the result was it just failed silently (no messages received).

**Comment by edwardmp** [comment]
Yeah so just use the gid but hash it again, that should do the trick

**Comment by palkan** [comment]
@twfarnam What kind of failures are you expecting? Could you, please, provide an example or reproduction script?

ActionCable Postgres adapter uses only LISTEN/NOTIFY functionality, there should not be any problem with long identifiers.

**Comment by twfarnam** [comment]
As I understand it Postgres identifiers, including channel names on LISTEN/NOTIFY, are limited to 63 characters. Channel names in Rails that are created with to_gid_param can be longer than that. From the psql shell, this doesn't seem to be a problem although it does offer a warning:

```
# LISTEN "Z2lkOi8vY29kZXgtcHJlc3MvQXJ0aWNsZS8wMDE2M2I3Mi05MjM4LTRlNjYtYmQ5My03Mzk1ZWZhMTRlYjQ";

NOTICE:  identifier "Z2lkOi8vY29kZXgtcHJlc3MvQXJ0aWNsZS8wMDE2M2I3Mi05MjM4LTRlNjYtYmQ5My03Mzk1ZWZhMTRlYjQ" will be truncated to "Z2lkOi8vY29kZXgtcHJlc3MvQXJ0aWNsZS8wMDE2M2I3Mi05MjM4LTRlNjYtYmQ"

# NOTIFY "Z2lkOi8vY29kZXgtcHJlc3MvQXJ0aWNsZS8wMDE2M2I3Mi05MjM4LTRlNjYtYmQ5My03Mzk1ZWZhMTRlYjQ", 'hi';

NOTICE:  identifier "Z2lkOi8vY29kZXgtcHJlc3MvQXJ0aWNsZS8wMDE2M2I3Mi05MjM4LTRlNjYtYmQ5My03Mzk1ZWZhMTRlYjQ" will be truncated to "Z2lkOi8vY29kZXgtcHJlc3MvQXJ0aWNsZS8wMDE2M2I3Mi05MjM4LTRlNjYtYmQ"

Asynchronous notification "Z2lkOi8vY29kZXgtcHJlc3MvQXJ0aWNsZS8wMDE2M2I3Mi05MjM4LTRlNjYtYmQ" with payload "hi" received from server process with PID 9337.

```

This **does** appear to be a problem on the connection that Rails uses. Messages are never delivered and therefore never arrive at the web socket. An example from the log is:

```
CommitCompileChannel is transmitting the subscription confirmation
CommitCompileChannel is streaming from commit_compile:Z2lkOi8vY29kZXgtcHJlc3MvRWRpdG9yLzVkN2FmYjQzLTQzNTctNDhmOS1iNTQzLWQyMzIzYjExNTMxNg
[ActionCable] Broadcasting to commit_compile:Z2lkOi8vY29kZXgtcHJlc3MvRWRpdG9yLzVkN2FmYjQzLTQzNTctNDhmOS1iNTQzLWQyMzIzYjExNTMxNg: "hi"
```

Using a shorter identifier (in this case the UUID), the message is sent as you can see in the last line of the log:

```
CommitCompileChannel is transmitting the subscription confirmation
CommitCompileChannel is streaming from commit_compile:5d7afb43-4357-48f9-b543-d2323b115316
[ActionCable] Broadcasting to commit_compile:5d7afb43-4357-48f9-b543-d2323b115316: "hi"
CommitCompileChannel transmitting "hi" (via streamed from commit_compile:5d7afb43-4357-48f9-b543-d2323b115316)
```

@palkan I am happy to create a script that reproduces the problem as you suggest, but I'm not sure how best to do that. Would it be best to create an entire Rails app in another repository?

**Comment by palkan** [comment]
@twfarnam Thanks! Now it's clear, I don't think we need a reproduction script.

Postgres [docs](https://www.postgresql.org/docs/current/static/sql-syntax-lexical.html#SQL-SYNTAX-IDENTIFIERS) (just for reference).
