### ISSUE TITLE
Rails Server sometimes didn't save my data correctly to the database

### ISSUE THREAD

**Issue by HarrisLawYF** [rails/rails#28752]
### Steps to reproduce
Our system will store each profile item of the user profile into as a new item in profile table due to the design (which means I need to do .save action in a for loop). It seems like when more and more users are connected to the server, some data didn't get stored.

(Guidelines for creating a bug report are [available
here](http://guides.rubyonrails.org/contributing_to_ruby_on_rails.html#creating-a-bug-report))

### Expected behavior
All data should be saved correctly into database without any missing one. The system should perform correctly and return a correct response.

### Actual behavior
Some data went missing, and this affected the system, eg. the 'visibility' data went missing and the system needs to check this data when it wants to return the result. This renders a 500 issue since it can't find the data and not returning a correct response to the frontend. 

### System configuration
**Rails version**: 4.2.6

**Ruby version**: 2.3.1p112

**Comment by st0012** [comment]
Can you provide a sample app for this issue?

**Comment by pixeltrix** [comment]
@HarrisLawYF from your description of the problem becoming more prevalent when the number of concurrent users increases it would seem that you have a [race condition][1] in your code. Given the lack of information I can't even point you where it might be so I'm closing the issue for now. If you really think there's a Rails bug then please provide more information so we can try to debug the problem and I'll reopen this issue.

[1]: https://en.wikipedia.org/wiki/Race_condition#Software
