### ISSUE TITLE
If the noun as an adjective, the noun should be singular

### ISSUE THREAD

**Issue by sachin21** [rails/rails#28769]
### Steps to reproduce
- cd /path/to/rails/guides/source/association_basics.md
- Look at line **948**

This pointing out about `./guides/source/association_basics.md` at line **948**'s incorrect English.

### Expected behavior
`book_count`

### Actual behavior
If the noun as an adjective, the noun should be singular
The actual name is `books_count`.
 is should be book_count because when We are using the noun as an adjective, the noun should be singular.

FYI: https://www.englishclub.com/grammar/nouns-adjective.htm

### System configuration
**Rails version**:
- Rails 5.0.2

**Ruby version**:
- ruby 2.3.1p112 (2016-04-26 revision 54768) [x86_64-linux]

**Comment by pixeltrix** [comment]
Whilst you may be grammatically correct, the `books_count` attribute is the correct name for the default behaviour of counter caching to work. If you're arguing that counter caching should singularize the table name before suffixing it with `_count` then I think that ship has sailed - you can always use a custom name anyway.

**Comment by sachin21** [comment]
@pixeltrix I see. Thanks for the quickly response.
