### ISSUE TITLE
Unable to turn remote: false when using form_with tag

### ISSUE THREAD

**Issue by ankitrg** [rails/rails#28764]
I am not sure if this is possible or not, but I want to turn off remote when using `form_with`. 

Here is how my form looks like:
```erb
<%= form_with(model: @form, remote: false) do |f| %>
<% end %>
```

Even after this the form is submitted via ajax. When I inspect the dom I can see `data-remote="true"` on the form tag.

**Comment by y-yagi** [comment]
You need to specify the `local` option, not the `remote` option.

```erb
<%= form_with(model: @form, local: true) do |f| %>
<% end %>
```

Ref: http://edgeapi.rubyonrails.org/classes/ActionView/Helpers/FormHelper.html#method-i-form_with

**Comment by ankitrg** [comment]
That was all I needed. I was also having trouble finding the edge docs. Thanks for the link too.

**Comment by murdoch** [comment]
Any particular reason why it's `local: true`, and not `remote: false`? Just wondering.

**Comment by ramses-lopez** [comment]
@murdoch It may be the fact that now remote is the new default, so it makes sense that you specify the "exception" with local: true

**Comment by natetech333** [comment]
I debugged the form_with source code. There is a method argument named local. But it can conflict with the rails config option for remote forms. I think remote forms default should have been left alone. Now, we have 3 different possible ways to set remote forms. In our rails config, local or remote.

**Comment by RuanHerculano** [comment]
``` ruby
<%= form_with(
  data: { remote: false }
) do |form| %>

<% end %>
```

**Comment by CaptGillespie** [comment]
> You need to specify the `local` option, not the `remote` option.
> 
> ```
> <%= form_with(model: @form, local: true) do |f| %>
> <% end %>
> ```
> 
> Ref: http://edgeapi.rubyonrails.org/classes/ActionView/Helpers/FormHelper.html#method-i-form_with

this thread saved my sanity. From the bottom of my heart, thank you.
