### ISSUE TITLE
Migrations adding multiple columns with foreign keys to the same table can't be reversed

### ISSUE THREAD

**Issue by alyssais** [rails/rails#28762]
### Steps to reproduce

<I>I wasn't sure how to fit this into the bug report template.</I>

1. Create a migration like this:

    ```ruby
    change_table :patches do |t|
      t.belongs_to :old_path, foreign_key: { to_table: :git_paths }
      t.belongs_to :new_path, foreign_key: { to_table: :git_paths }
    end
    ```

2. Run the migration
3. Attempt to roll the migration back

### Expected behavior
The migration should be rolled back successfully.

### Actual behavior
Rails successfully reverses the `:new_path` reference, but in doing so deletes _both_ foreign keys on the patches table. This means that when it comes to reverse the `:old_path` reference, it fails because it can't find the foreign key to delete.

I think this happens because `ActiveRecord::ConnectionAdapters::SchemaStatements#remove_reference` [does not](https://github.com/rails/rails/blob/e7f45d370ab10ad86a748ff2ec8b34c54d87b0bf/activerecord/lib/active_record/connection_adapters/abstract/schema_statements.rb#L861-L870) take into account the column the foreign key constraint is on.

### System configuration
**Rails version**: 5.0.2

**Ruby version**: 2.4.0

**Comment by kamipo** [comment]
Can you test on 5.1.0.rc1? #25285 should have fixed the issue.

**Comment by alyssais** [comment]
5.1.0.rc1 does indeed fix the issue. :)
