### ISSUE TITLE
ActiveRecord::Migration version support for engines

### ISSUE THREAD

**Issue by jamesmk** [rails/rails#28766]
When I copy migrations from an engine to a Rails 5.1.0.rc1 app via `rake ENGINE:install:migrations` and migrate the DB I'm now seeing the following error:

```
Directly inheriting from ActiveRecord::Migration is not supported. Please specify the Rails release the migration was written for: class AddUserTable < ActiveRecord::Migration[4.2]
```

This is easy enough to fix in the engine and app, however adding new migrations in the engine in this manner will produce the following error when copied to a Rails 4.2 app:

```
NoMethodError: undefined method '[]' for #<ActiveRecord::Migration:0x007f9ef2288c08>
```

**The issue:** This make it impossible to have an engine support Rails 4.2 and 5.1+ without writing your own method  to copy and conditionally munge the migrations.

### Possible Solution

It seems like the Rails release should be omitted when created within an engine. Then `ActiveRecord::Migration.copy` called from `rake ENGINE:install:migrations` can be responsible for adding the Rails release. This would allow the release to be based on the parent app and not the engine.

thanks

**Comment by maclover7** [comment]
Hi @jamesmk! It seems like gems in the ecosystem have been adding conditional flags at the top of the migrations. For example, take [Clearance](https://github.com/thoughtbot/clearance/commit/b0ce189c69d52155660232604cc30d729d6b4221), where they have `< ActiveRecord::Migration<%= migration_version %>` at the top of the migration file.

**Comment by matthewd** [comment]
It would arguably be wiser for Clearance to be explicitly stating the version its migration was actually written for -- grabbing the current running Rails version leaves their migration exposed to exactly the sort of changed-defaults-make-migration-mean-different-things dangers the versioning was introduced to prevent (cc/fyi @derekprior)

That aside, though.. yeah, I think that's the best way to solve the problem in an engine that wishes to continue supporting < 5.0. Us attempting to mangle the content of the migration file seems much riskier -- and leaves the issue of which version we should be inserting... though I guess the argument would be if it's a 4.2-compatible migration, that's how it should be marked.

**Comment by jamesmk** [comment]
Thanks for the responses. The Clearance example is exactly what I about writing your own solution. That is what I will have to do for my engine. More that just conditionally adding the Rails release, I'll have to recreate all functionality that `rake ENGINE:install:migrations` gives me: checking if migrations exists, setting timestamps, etc.

It's unfortunate that all Rails engines making this transition have to effectively ditch the built in method.

**Comment by derekprior** [comment]
> It would arguably be wiser for Clearance to be explicitly stating the version its migration was actually written for -- grabbing the current running Rails version leaves their migration exposed to exactly the sort of changed-defaults-make-migration-mean-different-things dangers the versioning was introduced to prevent (cc/fyi @derekprior)

Thanks for the ping. Clearance is only supported on Rails versions its test suite passes on. The test suite tests this migration, so I think using the current version is appropriate, although I'm open to changing this as the situation warrants.
