### ISSUE TITLE
Inconsistent method names in ActiveSupport::NumberHelper and ActionView::Helpers::NumberHelper

### ISSUE THREAD

**Issue by murb** [rails/rails#28770]
### Steps to reproduce

Try to create a number with delimiters with two different two different modules, `ActiveSupport::NumberHelper` and `ActionView::Helpers::NumberHelper`

```
class HelperWithAS
  include ActiveSupport::NumberHelper
end

class HelperWithAV
  include ActionView::Helpers::NumberHelper
end
```

### Expected behavior

```
HelperWithAS.new.number_to_delimited(10000) # returns "10.000"
HelperWithAS.new.number_with_delimiter(10000) # returns "10.000"

HelperWithAV.new.number_with_delimiter(10000) # returns "10.000"
HelperWithAV.new.number_to_delimited(10000) # returns "10.000" 
```

### Actual behavior
```
HelperWithAS.new.number_to_delimited(10000) # returns "10.000"
HelperWithAS.new.number_with_delimiter(10000) # NoMethodError

HelperWithAV.new.number_with_delimiter(10000) # returns "10.000"
HelperWithAV.new.number_to_delimited(10000) # NoMethodError
```

### System configuration

**Rails version**: 5.0.2
**Ruby version**: 2.4.1

**Comment by murb** [comment]
Note: I haven't dived in the underlying issue, but I'd think that the `ActionView::Helper::NumberHelper` could simply be a proxy to `ActiveSupport::NumberHelper` (or are ActionView modules not allowed to rely on ActiveSupport?). Alternatively, I'd expect both to be named similarly, and at least alias_methods should be created for the 'missing' method-names on both sides (I'm happy to provide a pull request for either option).

**Comment by pixeltrix** [comment]
@murb the difference in method names is intentional and `ActionView::Helpers::NumberHelper` does call `ActiveSupport::NumberHelper` [under the hood][1]. The view helpers aren't really meant to be used outside of a view context - use `ActiveSupport::NumberHelper` if you need to format numbers in a model or a PORO.

[1]: https://github.com/rails/rails/blob/1e0d8425f6526b0082693fe122a36449aa12a69e/actionview/lib/action_view/helpers/number_helper.rb#L65

**Comment by murb** [comment]
Thanks for the reply. As a non-native English speaker I overlooked the detail that a view helper offers a view 'with delimiters' and the more general Support module a less specific 'to delimited' :)
