### ISSUE TITLE
Postgres doesn't work with column default values 

### ISSUE THREAD

**Issue by sivagollapalli** [rails/rails#28785]
Added migration as 

```
class AddAutoIncrementToScreenNumber < ActiveRecord::Migration[5.0]
  def change
    execute <<-SQL
      CREATE SEQUENCE screen_number_seq;
      ALTER TABLE screens ALTER COLUMN number SET DEFAULT nextval('screen_number_seq');
    SQL
  end
end
```

It generates schema as 
```
  create_table "screens", force: :cascade do |t|
     t.integer  "number",         default: -> { "nextval('screen_number_seq'::regclass)" }
  end
```

when I do `rails db:scheme:load` it gives following error `ActiveRecord::StatementInvalid: PG::UndefinedTable: ERROR:  relation "screen_number_seq" does not exist
`

### System configuration
**Rails**: 5.0.1

**Ruby**: 2.4.0.p0

Looks like this issue is similar to #21627

**Comment by kamipo** [comment]
`db:scheme:dump` doesn't support dumping sequences. So if anyone use a sequence, need to restore it by themselves.

**Comment by pixeltrix** [comment]
@sivagollapalli as @kamipo said, the `schema.rb` format doesn't support things like sequences and triggers so if you need those you need to switch to `:sql` schema formatting - see this link for more information:

http://guides.rubyonrails.org/active_record_migrations.html#types-of-schema-dumps

**Comment by sivagollapalli** [comment]
@pixeltrix @kamipo Thanks for help. But when I run `rails db:structure:load` it loads structure but I didn't find tables in database. Am I missing anything?

**Comment by pixeltrix** [comment]
@sivagollapalli do you have a `db/structure.sql` file? If not then `rake db:schema:load` and then `rake db:structure:dump` to create one.

**Comment by sivagollapalli** [comment]
@pixeltrix Yes I have `db/structure.sql` in my project.

**Comment by rogercampos** [comment]
This problem also happens by default on the "id" column of a table with a long name using postgresql. If it happens that the name of the table + "_id_seq" is too large for postgres (63 chars), it's automatically truncated. However, when dumping the schema I guess it detectes that the primary key is following a sequence that doesn't follow the convention and adds the "default nextval" clause. That, however, cannot be dumped using a ruby schema as you say. 

I think this is a bug, the problem occurs even if the user doesn't intentionally use a custom default.
