### ISSUE TITLE
Invoking rake task from bin/rails results in uninitialised constant "rake::task"

### ISSUE THREAD

**Issue by BookOfGreg** [rails/rails#28786]
### Steps to reproduce

```bash
rails new foo
cd foo
rails g task feeds fetch
```
In test_helper.rb
```ruby
ENV['RAILS_ENV'] ||= 'test'
require File.expand_path('../../config/environment', __FILE__)
require 'rails/test_help'

Rake::Task['feeds:fetch'].execute

class ActiveSupport::TestCase
  # Setup all fixtures in test/fixtures/*.yml for all tests in alphabetical order.
  fixtures :all

  # Add more helper methods to be used by all tests here...
end
```

### Expected behaviour

`bin/rails test` should successfully run tests

### Actual behaviour

```
/Users/BookOfGreg/source/FOO/test/test_helper.rb:5:in `<top (required)>': uninitialized constant Rake::Task (NameError)
```

### System configuration
**Rails version**:
5.0.2
**Ruby version**:
ruby 2.3.1p112

**Comment by pixeltrix** [comment]
What happens if you `require 'rake'` before invoking the task?

**Comment by BookOfGreg** [comment]
```ruby
ENV['RAILS_ENV'] ||= 'test'
require File.expand_path('../../config/environment', __FILE__)
require 'rails/test_help'
require 'rake'

Rake::Task['feeds:fetch'].execute

class ActiveSupport::TestCase
  # Setup all fixtures in test/fixtures/*.yml for all tests in alphabetical order.
  fixtures :all

  # Add more helper methods to be used by all tests here...
end
```

```
$ bin/rails test
#/Users/BookOfGreg/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rake-12.0.0/lib/rake/task_manager.rb:58:in `[]': Don't know how to build task 'feeds:fetch' (see --tasks) (RuntimeError)
...

$ rake test
Run options: --seed 46262

# Running:
...
```

**Comment by pixeltrix** [comment]
@BookOfGreg okay, this is as expected then - `bin/rails` isn't `rake` and you need to require it if you need it.

**Comment by BookOfGreg** [comment]
Isn't bin/rails supposed to be the new task runner as specified in https://github.com/rails/rails/pull/22288 ?
The guide also implies that bin/rails should be used.
http://guides.rubyonrails.org/command_line.html#bin-rails
The docs may want to be updated to show that bin/rails doesn't execute the way rake does, or if there is a `Rails::Commands.invoke` equivalent of `Rake::Task.invoke` , it would be worth mentioning that.

**Comment by pixeltrix** [comment]
@BookOfGreg yes, but Rails commands are based on Thor and not Rake so it won't be loaded by default. There's a `rake` Thor command which calls the legacy rake commands like db:create, etc. so you can probably use `Rails::Command.invoke :rake, [args]` to run your task.

**Comment by artur-beljajev** [comment]
In our app (https://github.com/internetee/registry) I had to put the following in order to make both `bin/rails test` and `rake test` work:

```
# `bin/rails test` is not the same as `bin/rake test`.
# All tasks will be loaded (and executed) twice when using the former without `Rake::Task.clear`.
# https://github.com/rails/rails/issues/28786
require 'rake'
Rake::Task.clear
Rails.application.load_tasks
```
