### ISSUE TITLE
form_with(url: url, remote: false, authenticity_token:true) won't generate tokens

### ISSUE THREAD

**Issue by krtschmr** [rails/rails#28796]
=form_with url: "/", remote: false, authenticity_token: true do |f|
      =f.submit "Boom"

### Expected behavior
according https://github.com/rails/rails/pull/26976#pullrequestreview-8448693 and also the comments i expect that there will be a token, because it's not remote AND authenticity_token is set to true.

### Actual behavior

```
<form action="/" accept-charset="UTF-8" data-remote="true" method="post">
    <input name="utf8" type="hidden" value="✓">
    <input type="submit" name="commit" value="Boom!" class="btn btn-primary" />
</form>
```

remote is set to :true and no tokens included

### System configuration
5.1.rc1

**Ruby version**:
2.3

**Comment by pixeltrix** [comment]
@krtschmr if you check [the documentation][1] for `form_with` options you'll see there's a new option called `:local` - set that to true and it will add the token. There's no need to add `authenticity_token: true`.

[1]: http://edgeapi.rubyonrails.org/classes/ActionView/Helpers/FormHelper.html#method-i-form_with

**Comment by krtschmr** [comment]
thank you @pixeltrix i was just reading code ;)
