### ISSUE TITLE
to delete

### ISSUE THREAD

**Issue by krtschmr** [rails/rails#28792]
```
# require 'rails/commands/server'
# module Rails
#   class Server
#     def default_options
#       super.merge(Host:  '0.0.0.0', Port: 3000)
#     end
#   end
# end
```

this is not working anymore and i can't figure out, how i can fix this require

https://github.com/rails/rails/blob/83776676e54b387fc52081ff31cfd7710bae9e03/railties/lib/rails/commands/server/server_command.rb

**Comment by rafaelfranca** [comment]
Is this issue fixed already?

**Comment by krtschmr** [comment]
@rafaelfranca  no, my monkey patch is not working in 5.1

**Comment by rafaelfranca** [comment]
Oh. It is a monkey patch. We don't give support for monkey patches.
