### ISSUE TITLE
Adding an error with a symbol as message is not possible if attribute is not defined on the model

### ISSUE THREAD

**Issue by AlexVPopov** [rails/rails#28810]
### Steps to reproduce

When trying to add an error on a non-existent attribute of a model, it works with string, but not with symbol:

```ruby
class Foo
  include ActiveModel::Validations
end

foo = Foo.new
foo.errors.add(:bar, :blank) # => NoMethodError: undefined method `bar' for #<Foo:0x005603f38e66b8>
foo.errors.messages # => {}
foo.errors.details # => {}
foo.errors.add(:bar, "can't be blank") # => ["can't be blank"]
foo.errors.messages # => {:bar=>["can't be blank"]}
foo.errors.details # => {:bar=>[{:error=>"can't be blank"}]}
```

### Expected behavior
I think the behavior should be consistent - it should either work with both string (`foo.errors.add(:bar, "can't be blank")`) or symbol (`foo.errors.add(:bar, :blank)`) or it should throw a `NoMethodError` in both cases.

### Actual behavior
It works with string, but not with a symbol

### System configuration
**Rails version**: 4.2.8

**Ruby version**: 2.3.1

**Comment by pixeltrix** [comment]
This is because it needs to pass the value to the `I18n.translate` call so it calls `read_attribute_for_validation`, which by default is aliased to `send`. You can implement your own `read_attribute_for_validation` method which does whatever you need it to do for your application.

**Comment by AlexVPopov** [comment]
@pixeltrix Is the user supposed to know how `add` is implemented? Shouldn't it behave consistently? Also, is `read_attribute_for_validation` part of the public API?

**Comment by pixeltrix** [comment]
@AlexVPopov they could start by reading the documentation for `ActiveModel::Errors`:

http://api.rubyonrails.org/classes/ActiveModel/Errors.html

Where it has the following:

```
  # The following methods are needed to be minimally implemented

  def read_attribute_for_validation(attr)
    send(attr)
  end

  def self.human_attribute_name(attr, options = {})
    attr
  end

  def self.lookup_ancestors
    [self]
  end
```

and the statement:

```
The last three methods are required in your object for Errors to be able to generate
error messages correctly and also handle multiple languages.
```

**Comment by AlexVPopov** [comment]
O.K., thank you for the hint. But this only answers my last question, whether `read_attribute_for_validation`, for which I admit could have done a better job at researching. However, I still don't see the rational about why the method behaves differently in the two cases. In your first answer you explain the technical side of `why` - it passes the value to `I18n.translate`, which in turn calls `read_attribute_for_validation`. Yet, is it intentional, that in the one case it allows you to assign an error to a non-existent attribute and in the other - not. I mean, is it a mere coincidence and is there intention behind it?

**Comment by pixeltrix** [comment]
Obviously there's no specific intent to make the method behave differently but the API is designed around it being an attribute so if you need to work with things that aren't attributes then it's up to the developer to make it appear as an attribute.

It's arguable that the default implementation and example should be more resilient and check using `respond_to?` or use `try` over just blindly using `send` but that discussion is probably better had in a PR.

**Comment by arianf** [comment]
I wish I could use symbols instead of strings as well for unknown attributes... seems like a weird constraint

**Comment by h0jeZvgoxFepBQ2C** [comment]
Can confirm, weird. 👍
