### ISSUE TITLE
Detach fixture loading order from model name/filename

### ISSUE THREAD

**Issue by nbdavies** [rails/rails#28811]
### Steps to reproduce
1. Create a rails app with a Postgres database, and two or more tables connected via foreign keys. Let's say the models are Car and Driveway, where a car belongs to a driveway.
2. Create fixtures for these models: a couple cars that point to one or more driveways.
3. Run your tests.

### Expected behavior
Loading the Car fixture first will result in a referential integrity error, because of the foreign key constraint. See https://github.com/rails/rails/pull/17726 for background. And I'm not saying that error is wrong...

One current solution to this is to allow tests to run with a Postgres superuser who can disable referential integrity altogether. And I'm not saying that option should go away. But that solution is much broader than the problem. It might be very useful to enforce referential integrity within the test suite just as it is in the application itself. 

A better solution would be to provide a standard option to define the logical order for fixtures to be loaded, rather than the default alphabetical behavior. Controlling the order of individual records within a model, to account for referential integrity within a table, is already a standard option mentioned in the Rails Guides. If that's allowed for records within the same table, it seems unfair not to allow it across tables.

Here are a couple forms this could take: 

* An optional higher-level YML file to define the order of the models. 

* Allow model name to be specified in the content/structure of the individual YML files. Then the filename wouldn't need to correspond to the model name. This would allow for the files to be alphabetized intentionally. It could also allow a single fixture file to contain more than one model, and for those models to be listed in an intentional order within a file. 

### Actual behavior
Currently the only options are to create a Postgres superuser to run the tests, which will disable foreign key constraints within the tests. Or some folks have overwritten ActiveRecord::FixtureSet.create_fixtures, which is not ideal. Maybe others even alphabetize their model names to deal with this.

### System configuration
**Rails version**: 5.0

**Ruby version**: 2.2.5

**Comment by rafaelfranca** [comment]
Thank you so much for the issue but we don't take feature request on the issue tracker. We recommend you to try to implement the feature and send us a pull request.
