### ISSUE TITLE
Using hash of the key for enumaration in ActiveRecord::Enum instead of array index

### ISSUE THREAD

**Issue by itay-grudev** [rails/rails#28817]
I was adding an `enum` field to a Model when I noticed that the `ActiveRecord::Enum` implementation uses the array index value when storing the `enum` in the database. I know that this solutions is fast but comes with the rather annoying problem that the order of items is important and new values should only be added to the end of the array to preserve existing values.

We could make a dummy-proof implementation using a hash of the `enum` keys?

If you are OK with the idea I would be willing to implement it. I realise that for backwards compatibility it will only be added to the next major Rails version, but the framework has to evolve.

**Comment by rafaelfranca** [comment]
That is already possible today.

Take a look on the enum documentation http://api.rubyonrails.org/classes/ActiveRecord/Enum.html
