### ISSUE TITLE
Make `rake app:update` more configurable

### ISSUE THREAD

**Issue by betesh** [rails/rails#28825]
I don't want to start a PR on this until others have had the chance to comment so we can make sure we address this thoroughly in one PR.  Here's a start to the list of things we could do better:

* Run `spring binstub --all`
* Support (or autodetect whether app was generated with) `--skip-action-cable`, `--skip-listen`, `--skip-puma`, `--skip-sprockets` (I'm probably missing a few here...)
* Update code not modified since the rails app was generated without overwriting non-generated code in the same file (in files such as `config/locales/en.yml`, `config/routes.rb`, `config/secrets.yml`)

Does anyone have further suggestions?

**Comment by st0012** [comment]
I don't think they are really "unnecessary changes", maybe just you don't need them. And seems that you are not really want to remove them, you just want more flexibilities when running the task? So I suggest a better subject might be "Add more options for rake app:update".
BTW I agree we should have more options when running this command.

**Comment by y-yagi** [comment]
Related #22790, #22042

**Comment by betesh** [comment]
@st0012 I renamed it to avoid giving the wrong impression, but clobbering custom application logic in places like config/routes just to get the latest behavior doesn't seem like something anyone would want.

**Comment by betesh** [comment]
I opened this issue to gather some suggestions from the Rails community and Rails core team about how we could make `rake app:update` better.  This hasn't been addressed, and from the one piece of feedback I got, it's clear that there are different opinions, but it's not clear what direction to go since there is so little feedback.

I continue to welcome feedback about this, whether it's open or stale or closed.

**Comment by kaspth** [comment]
The second point should be fixed with https://github.com/rails/rails/pull/29645. First one should be handled over in the spring repo.

The third one: let's see what a PR would look like 👍
