### ISSUE TITLE
slice keys from hash with indifferent access

### ISSUE THREAD

**Issue by rajesh38** [rails/rails#28822]
### Steps to reproduce

If you have a Hash which is not HashWithIndifferentAccess and you don't know what kind of keys it have e.g. symbol or string and you want to `slice` some keys from the hash i.e. even if the keys in the hash are symbol you should be able to extract it with symbol or string as keys.

Try `{ a: 1, b: 2, c: 3, d: 4 }.slice('a', 'b')`

### Expected behavior
It should return `{:a=>1, :b=>2}`

### Actual behavior
It returns `{}`

### System configuration
**Rails version**: 5.0.1

**Ruby version**: 2.2.4

**Comment by rafaelfranca** [comment]
See https://github.com/rails/rails/pull/28823#issuecomment-296256502
