### ISSUE TITLE
rake db:* tasks ignore DATABASE_URL settings, partly

### ISSUE THREAD

**Issue by plutino** [rails/rails#28827]
### Steps to reproduce
1. export DATABASE_URL with settings different from `database.yml`
2. run any databased related rake tasks (db:setup, db:create, db:drop, etc) with RAILS_ENV set to `development` or unset

### Expected behavior
Settings in DATABASE_URL, such as MySQL host, is used for both `development` and 'test' databases.

### Actual behavior
Settings in DATABASE_URL are used when the task is run for `development` environment, but they are not used for `test` environment

### System configuration
**Rails version**:
5.0.2

**Ruby version**:
2.3.1

**Comment by plutino** [comment]
This issue would be less annoying if there is a way to run the db tasks against `development` database only.

**Comment by st0012** [comment]
Can you provide information like a test script or app that can reproduce this issue? I test on my app and it works as expected.

**Comment by plutino** [comment]
I created a test app to reproduce the bug.  It comes with setup to run the reproducing steps in Docker containers, and has detailed instruction in `README.md` on how to reproduce.

https://github.com/plutino/rails-test

**Comment by maclover7** [comment]
Hi @plutino! I could be wrong, but I think `DATABASE_URL` isn't meant to be used for only some configuration options (ex: only host). Maybe you want to modify your `config/database.yml` to accept environment variables for some arguments?

**Comment by bwebster** [comment]
We are running into this as well in a docker environment.

**Comment by bbuchalter** [comment]
I've taken a shot at addressing this issue in https://github.com/rails/rails/pull/37351 and would welcome feedback.
