### ISSUE TITLE
Migrations not running on test database (postgres)

### ISSUE THREAD

**Issue by lollar** [rails/rails#28826]
### Steps to reproduce
1. Create a new rails app using rails 5.1.0.rc2 and postgres database
2. run `bundle exec rake db:create`
3. Create a new migration
4. run `bundle exec rake db:migrate`
5. Check the test database to verify migration did not run

I've ran several other commands including using the `RAILS_ENV=test` and still cannot get it to populate.  

Here is a link to the repo where I first discovered the bug: https://github.com/lollar/praeceptor

Just to make sure I didn't break something in the config I created a separate app with `rails new` defaults: https://github.com/lollar/blah_app

Not sure if this is related but I did find this issue in my research: https://github.com/rails/rails/issues/25804

### Expected behavior
Should populate the test database on `rake db:migrate` especially on `RAILS_ENV=test rake db:migrate`

### Actual behavior
Only runs migration on development database

### System configuration
**Rails version**:
5.1.0.rc2

**Ruby version**:
2.4.1

**Postgres Version**:
9.6

Thanks!

**Comment by lollar** [comment]
Also wanted to leave this snippet from the blah app Postgres database:
```
psql (9.6.2)
Type "help" for help.

blah_app_test=# \d
No relations found.

psql (9.6.2)
Type "help" for help.

blah_app_development=# \d
                 List of relations
 Schema |         Name         |   Type   | Owner  
--------+----------------------+----------+--------
 public | ar_internal_metadata | table    | lollar
 public | schema_migrations    | table    | lollar
 public | user_tables          | table    | lollar
 public | user_tables_id_seq   | sequence | lollar
(4 rows)
```

**Comment by rafaelfranca** [comment]
`bin/rake db:migrate` don't migrate the test database unless you pass `RAILS_ENV=test`. I just tried your reproduction steps and they migrated the test database just fine when I use `RAILS_ENV=test bin/rails db:migrate` (works with `bin/rake` too). I also tested your application and it works just fine.

```
[2.4.0 blah_app (master)]$ bin/rake db:create
Running via Spring preloader in process 70893
Created database 'blah_app_development'
Created database 'blah_app_test'
[2.4.0 blah_app (master)]$ bin/rake db:migrate
Running via Spring preloader in process 70936
== 20170421165903 CreateUserTable: migrating ==================================
-- create_table(:user_tables)
   -> 0.0037s
== 20170421165903 CreateUserTable: migrated (0.0038s) =========================

[2.4.0 blah_app (master)]$ RAILS_ENV=test bin/rake db:migrate
Running via Spring preloader in process 70980
== 20170421165903 CreateUserTable: migrating ==================================
-- create_table(:user_tables)
   -> 0.0036s
== 20170421165903 CreateUserTable: migrated (0.0038s) =========================

[2.4.0 blah_app (master)]$ psql -d blah_app_test
psql (9.6.2)
Type "help" for help.

blah_app_test=# \d
                    List of relations
 Schema |         Name         |   Type   |    Owner
--------+----------------------+----------+--------------
 public | ar_internal_metadata | table    | rafaelfranca
 public | schema_migrations    | table    | rafaelfranca
 public | user_tables          | table    | rafaelfranca
 public | user_tables_id_seq   | sequence | rafaelfranca
(4 rows)

blah_app_test=#
```

**Comment by shqear93** [comment]
I have exactly the same problem!!! any help?

**Command :**
```
rake db:migrate RAILS_ENV=test
```
**Error message :**
```
PG::ConnectionBad: could not connect to server: No such file or directory
        Is the server running locally and accepting
        connections on Unix domain socket "/var/run/postgresql/.s.PGSQL.5432"?
```

**Comment by lackita** [comment]
PSA for anybody else struggling with this issue. If you rolled back a migration to, say, change your mind on a column name, it's possible the test database will think it's run the migration even though it has the old name.

What this will look like is nothing will be migrated when you run `RAILS_ENV=test rake db:migrate`, but if you try `RAILS_ENV=test rake db:rollback` it throws an error. What I did to rollback is edit the migration back to the original name, rollback, undo the edit, and then rerun the migration.

**Comment by cesc1989** [comment]
@lackita I followed a much simpler approach(I think).

I was in a situation similar to what you describe:

- Added new model and run migration
- Rolled back, changed a column name
- Run migration `rails db:migrate`
- Specs failed because the column name in the test database didn't update

To fix it, I just dropped and recreated _test_ database:

```bash
$ RAILS_ENV=test rails db:drop
$ RAILS_ENV=test rails db:create
$ RAILS_ENV=test rails db:schema:load
```

**Comment by MikeRogers0** [comment]
I ran into this same problem when using `docker-compose` to run my tests. I was passing in the `DATABASE_URL` (Which looked like `postgres://postgres:postgres@postgres:5432/`) as an environment variable, but whenever I ran my tests I ran into the error mentioned above.

The solution was to update my `config/database.yml` to have the line:

```yml
default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  url: <%= ENV['DATABASE_URL'] %> # < this line here
```

Hopefully this helps someone else who ended up googling their way onto this issue :)
