### ISSUE TITLE
ActiveRecord::Rollback has no effect with collection.create

### ISSUE THREAD

**Issue by cerdiogenes** [rails/rails#28836]
### Steps to reproduce

In a controller, trigger a creation in a has_many collection: `@model.collection.create` and in the collection model `raise ActiveRecord::Rollback`

### Expected behavior
A rollback must be executed and I should see ROLLBACK in logs.

### Actual behavior
No rollback, the model get persisted and there isn't ROLLBACK in logs. If I invert the object creation with `CollectionModel.create(model: @model)` and `raise ActiveRecord::Rollback` the rollback occurs.

### System configuration
**Rails version**: 5.1.0.beta1

**Ruby version**: 2.4.1p111

**Comment by mltsy** [comment]
Yup - I have been stumped on this issue for several hours!  Thanks for the error report.  This one is a doozey!

**Rails version**: 5.0.0

**Comment by eileencodes** [comment]
@cerdiogenes can you provide an executable test script using [this template](https://github.com/rails/rails/blob/master/guides/bug_report_templates/active_record_master.rb)

I have a hunch that this is caused by my fix for this issue https://github.com/rails/rails/issues/29320 but would like to be able to easily test using your use case.

**Comment by mltsy** [comment]
Here's a script.  I'm having trouble getting even the normal transaction case to pass using sqlite3 (although both pass fine when raising an exception other than ActiveRecord::Rollback).  I think perhaps you just need to connect to a different database to get the intended result, but I don't have time to figure out how to do that in a script at the moment! :wink:

```ruby
# frozen_string_literal: true

begin
  require "bundler/inline"
rescue LoadError => e
  $stderr.puts "Bundler version 1.10 or later is required. Please update your Bundler"
  raise e
end

gemfile(true) do
  source "https://rubygems.org"
  gem "rails", github: "rails/rails"
  gem "arel", github: "rails/arel"
  gem "sqlite3"
end

require "active_record"
require "minitest/autorun"
require "logger"

# This connection will do for database-independent bug reports.
ActiveRecord::Base.establish_connection(adapter: "sqlite3", database: ":memory:")
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :posts, force: true do |t|
  end

  create_table :comments, force: true do |t|
    t.integer :post_id
  end
end

class Post < ActiveRecord::Base
  has_many :comments
end

class Comment < ActiveRecord::Base
  belongs_to :post

  after_create do
    raise ActiveRecord::Rollback # This should rollback every comment created, theoretically
  end
end

class BugTest < Minitest::Test
  def test_normal_rollback
    Comment.create

    assert_equal 0, Comment.count # This should succeed
  end

  def test_collection_rollback
    post = Post.create
    post.comments.create

    assert_equal 0, Comment.count # This should fail because of the bug
  end

end
```

**Comment by mltsy** [comment]
It still happens in 5.1.4.  Here's an easy way to reproduce:

```shell-script
$ rails new . --database=postgresql
$ rails g model post
$ rails g model comment post:references
$ vim app/models/post.rb # Add 'has_many :comments'
$ vim app/models/comments.rb # Add 'after_create { raise ActiveRecord::Rollback }'
$ rails db:migrate
$ rails c
> post = Post.create
> post.comments.create
> Comment.count # => 1
```

**Comment by mltsy** [comment]
Ah shoot.  Reopen!  This is still happening in 5.1.4.

**Comment by phoebetse** [comment]
Can this issue please be re-opened? Running into this with Rails 5.2.1 and Ruby 2.3.4 (and Ruby 2.5.1). 
Found this PR that never merged, which could be a solution: https://github.com/rails/rails/pull/31488 
This open issue might be related as well: https://github.com/rails/rails/issues/33868
