### ISSUE TITLE
ActionCable - Postgresql write/read disconnects ActionCable connection in development

### ISSUE THREAD

**Issue by emerald-co** [rails/rails#28842]
In my development environment I **had** a perfectly working app using action cable when I was using the SQLite database adapter in development. 

I switched to Postgres from SQLite in my development environment and all of a sudden am unable to connect to ActionCable, it seems from my tests any DB write disconnects the connection.

Because my app does a database write on connection I get an infinite loop of connections and disconnections, the only change that has caused this is using Postgres as the database adapter in development.

I also have a production app with the exact same code running perfectly in production using the Postgresql database with no problems.

### Steps to reproduce

Essentially any read/write will create a disconnection so it's fairly easy to reproduce.

1. Set PostgresSQL as the database adapter in development]
2. Add a simple write operation on the channel subscribed method to trigger a database write on connection
3. Observe the connection issues

### Expected behavior
Postgres write/read should not affect ActionScable connection

### Actual behavior
Postgresql write/read disconnects ActionCable connection in development

### System configuration
**Rails version**: Rails 5.2

**Ruby version**: Tested in Rails 2.4.0 and 2.4.1

**Comment by maclover7** [comment]
Hi @emerald-co! Can you create an executable test script using one of the templates [here](https://github.com/rails/rails/tree/master/guides/bug_report_templates), that would demonstrate the problem you are seeing? Also, I'm assuming this is broken on `5-0-stable` and `5-1-stable`, right?

**Comment by emerald-co** [comment]
hello there,

I've been trying to figure this out all day, it's actually not related to PostgreSQL at all. It still happens with SQLite3

What is happening is essentially I keep getting disconnected and reconnected, this never happened before. This happened after a bundle update but action cable was not updated.. ActiveSupport, however was updated. So I am wondering if it is an issue with that.

I am unable to create a test script at the moment as I am too swamped with corporate work (related to this bug incidentally) 

has anyone else found a fix for constant reconnecting/disconnections

**Comment by emerald-co** [comment]
Okay I have found a solution to the problem, basically its something to do with an updated Gem, unfortunately I am not sure which one it is. I can confirmed a bundle update is what broke action cable causing the constant disconnections.

I will paste the gem files that were updated and narrow it down to help your development team come to an understanding and replicate the error.

**Comment by maclover7** [comment]
@emerald-co Since it sounds like updating a gem in your application is causing this issue, I'm going to close out this ticket. Please feel free to reopen if you are able to reproduce it in isolation :)
