### ISSUE TITLE
[ActionCable] client same use subscribe to same room repeatedly.

### ISSUE THREAD

**Issue by zw963** [rails/rails#28855]
### Expected behavior
Not to subscribe again if current client with current user is subscribed.
I think we should ignore same subscribe request from js clients or
js client just not to subscribe.

### Actual behavior
can be subscribe repeatly, which cause `received` callback invoke time
+2 when user switch out chatroom page and in again in a single page app.
(because not reload page, see chrome js log, can see `received` is invoked
many times

So, I think we should introduced a feature to ``stream_for`` or js clients,
 if one user stream from one chatroom, It should not stream again to same user and
same chatroom for same channel

### System configuration
**Rails version**:
Rails 5.0.2

**Ruby version**:
2.3.3

**Comment by musicmage4114** [comment]
Hey there!

Please see the [guide to Contributing to Rails](http://edgeguides.rubyonrails.org/contributing_to_ruby_on_rails.html#what-about-feature-requests-questionmark) for how feature requests are handled.

In short, you'll need to either contribute the code yourself, or partner with someone else to help you. You can put up a message on the [Rails Core mailing list](https://groups.google.com/forum/?fromgroups#!forum/rubyonrails-core) to see if there anyone who might be interested in assisting you.

If you feel like you're experiencing incorrect behavior, you may want to revise your issue to highlight that, noting in particular the expected versus actual behavior. [Here's a brief guide](https://coenjacobs.me/2013/12/06/effective-bug-reports-on-github/) to writing effective bug reports if you need some guidance.

Happy coding!

**Comment by zw963** [comment]
@musicmage4114 , I think this is a bug, I update my issue for more clear. : )

**Comment by maclover7** [comment]
Hi @zw963! This sounds a little bit like a bug in your application -- IMHO it's the app's job to keep track of whether the user has already subscribed to, for example, a chat room, not Action Cable's.

**Comment by zw963** [comment]
@maclover7 , Fine, I think it too somewhat, but it a little complex in some front-end framework to
do this well,I think maybe we should maintain a hash table in server, which record all connect pairs, 
to avoid subscribe again and again.

anyway, it this should be the expect behavior, just close it,  : )

thanks

**Comment by maclover7** [comment]
@zw963 yeah, this seems like expected behavior to me. Managing subscriptions (and avoiding duplicates) seems like an application-level concern, not a framework one. Thank you for opening up the issue!! :)
