### ISSUE TITLE
Deprecation message for attribute_changed?, change,... does not include the correct location in 5.1.0.rc2

### ISSUE THREAD

**Issue by aried3r** [rails/rails#28852]
### Steps to reproduce

I'm currently trying our codebase with Rails 5.1.0 RC2 and get spammed by deprecation warnings on our model specs. However the location of the deprecations are wrong.

In my case I think it's the paper_trail gem. See [this commit](https://github.com/airblade/paper_trail/commit/442f7a02b38e405d0b56b93d78591f73a6ecfb8b) followed by [@sgrif's commit](https://github.com/airblade/paper_trail/commit/ad5976ebc0ad3aecad19dc0a1967191df8078b17) (so, maybe it's a different gem after all?).

It does seem to be related to https://github.com/rails/rails/issues/28594 but I don't think it's a duplicate.

(Maybe also related another deprecation warning that doesn't show the correct place: https://github.com/rails/rails/issues/27343 as well as the first comment https://github.com/rails/rails/issues/27343#issuecomment-266759770.)

### Expected behavior
The caller location should display where the actual deprecated methods were called.

### Actual behavior
```
DEPRECATION WARNING: The behavior of `attribute_change` inside of after callbacks will be changing in the next version of Rails. The new return value will reflect the behavior of calling the method after `save` returned (e.g. the opposite of what it returns now). To maintain the current behavior, use `saved_change_to_attribute` instead. (called from attribute_change at /usr/local/opt/rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activerecord-5.1.0.rc2/lib/active_record/attribute_methods/dirty.rb:220)
DEPRECATION WARNING: The behavior of `attribute_changed?` inside of after callbacks will be changing in the next version of Rails. The new return value will reflect the behavior of calling the method after `save` returned (e.g. the opposite of what it returns now). To maintain the current behavior, use `saved_change_to_attribute?` instead. (called from attribute_changed? at /usr/local/opt/rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activerecord-5.1.0.rc2/lib/active_record/attribute_methods/dirty.rb:225)
DEPRECATION WARNING: The behavior of `changed_attributes` inside of after callbacks will be changing in the next version of Rails. The new return value will reflect the behavior of calling the method after `save` returned (e.g. the opposite of what it returns now). To maintain the current behavior, use `saved_changes.transform_values(&:first)` instead. (called from changed_attributes at /usr/local/opt/rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activerecord-5.1.0.rc2/lib/active_record/attribute_methods/dirty.rb:103)
DEPRECATION WARNING: The behavior of `changes` inside of after callbacks will be changing in the next version of Rails. The new return value will reflect the behavior of calling the method after `save` returned (e.g. the opposite of what it returns now). To maintain the current behavior, use `saved_changes` instead. (called from block in changes at /usr/local/opt/rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activerecord-5.1.0.rc2/lib/active_record/attribute_methods/dirty.rb:110)
DEPRECATION WARNING: The behavior of `changed` inside of after callbacks will be changing in the next version of Rails. The new return value will reflect the behavior of calling the method after `save` returned (e.g. the opposite of what it returns now). To maintain the current behavior, use `saved_changes.keys` instead. (called from changed at /usr/local/opt/rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activerecord-5.1.0.rc2/lib/active_record/attribute_methods/dirty.rb:235)
```

### System configuration
**Rails version**: 5.1.0.rc2

**Ruby version**: 2.3.1

**Comment by maclover7** [comment]
On the surface, seems like this is very similar to #27343.

**Comment by dbackeus** [comment]
Possibly getting the same thing but my take is that I'm getting the wrong message rather than the wrong location.

I'm getting:
```
DEPRECATION WARNING: The behavior of `attribute_changed?` ...<ommited>... use `saved_change_to_attribute?` instead. (called from password= at /Users/davidbackeus/development/rails/mndx-web/app/models/user.rb:40)
```

At `user.rb:40` I'm actually calling: `attribute_will_change! :password`

And I'm not inside any callback scenario at all.

Should I file this as another issue or related to this?

**Comment by jaredbeck** [comment]
In case it helps anyone upgrading to 5.1, you can get the full stack trace by hacking `attribute_methods/dirty.rb`. Just add a `pp caller` to `emit_warning_if_needed`. If you don't know where to find `dirty.rb` on disk, use `bundle show active_record`. Don't forget to `gem pristine` when you're done :)
