### ISSUE TITLE
`safe_constantize` raises `LoadError` when it should not

### ISSUE THREAD

**Issue by grzesiek** [rails/rails#28854]
### Steps to reproduce

`safe_constantize` raises `LoadError` in case it should just return `nil`.

```ruby
"Pipeline".safe_constantize
LoadError: Unable to autoload constant Pipeline, expected /home/grzesiek/gitlab/app/models/ci/pipeline.rb to define it
```

Notice that file that is expected to define `Pipeline` constant is located within `Ci` module. That means there is no `::Pipeline` constant, only `Ci::Pipeline` exists.

### Expected behavior

`safe_constantize` should return `nil` in that case.

### Actual behavior

`safe_constantize` raises `LoadError`

### System configuration

**Rails version**: 4.2.8  
**Ruby version**: 2.3.3

Code of `safe_constantize` looks exactly the same on `master` in this repository, but it might be solved elsewhere, sorry for creating issue in that case!

Thanks for looking into this in advance! :purple_heart:

**Comment by Edouard-chin** [comment]
Does your autoload_path includes `/home/grzesiek/gitlab/app/models/ci` ?

**Comment by grzesiek** [comment]
@Edouard-chin Yes.

**Comment by matthewd** [comment]
That's expected behaviour, then: the file is not located within anything.

**Comment by grzesiek** [comment]
Sorry, I was confused, we do not have specific `autoload_paths` entry for this directory. only `eager_load_paths`. Is it still expected to work this way then @matthewd?

**Comment by matthewd** [comment]
If the subdirectory is explicitly listed in `eager_load_paths`, yes. You probably don't want to do that.

**Comment by stas** [comment]
> That's expected behaviour, then: the file is not located within anything.

@matthewd I'm a bit confused why this issue was closed. This is not an expected behaviour, or at least it's not documented.

Based on the docs this method should not raise any exceptions:
https://github.com/rails/rails/blob/4-2-stable/activesupport/lib/active_support/inflector/methods.rb#L281-L310

If the documentation is not correct, we should update it, but I do believe this is a valid issue.

I'll be happy to provide a patch if this gets confirmed.

**Comment by matthewd** [comment]
@stas `safe_constantize` will return nil if the application is behaving properly and the named constant doesn't exist. If there's an error in the application code, e.g. the application appears to be trying to define that constant but failing, then exceptions will be raised as normal.

I see nothing in the content you linked that claims it will swallow all exceptions: it says only that "`nil` is returned when the name is not in CamelCase or the constant (or part of it) is unknown."

If you're seeing an exception from `safe_constantize`, you have a bug in your code (or in the case of this original issue, the configured autoload paths), and it will go away if you fix it.

**Comment by stas** [comment]
@matthewd I'm just looking at these two methods `constantize` and `safe_constantize` and based on what you say, there's no real _safeness_ in using the later.

Please take a look at the example bellow:
```
/im # cd /tmp/
/tmp # mkdir issue_28854
/tmp # cd issue_28854/
/tmp/issue_28854 # cat > im.rb
module IM
end
/tmp/issue_28854 # irb
irb(main):001:0> require 'active_support/inflector'
=> true
irb(main):002:0> ActiveSupport::Inflector.inflections do |inflect|
irb(main):003:1*   inflect.acronym 'IM'
irb(main):004:1> end
=> /IM/
irb(main):005:0> ActiveSupport::Inflector.safe_constantize('IM')
=> nil
irb(main):006:0> require 'im'
LoadError: cannot load such file -- im
	from /usr/local/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:122:in `require'
	from /usr/local/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:122:in `require'
	from (irb):6
	from /usr/local/bin/irb:11:in `<main>'
irb(main):007:0> require_relative 'im'
=> true
irb(main):008:0> ActiveSupport::Inflector.safe_constantize('IM')
=> IM
irb(main):009:0> ActiveSupport::Inflector.safe_constantize('IM::Im')
=> nil
irb(main):010:0> ActiveSupport::Dependencies.autoload_paths
NameError: uninitialized constant ActiveSupport::Dependencies
	from (irb):10
	from /usr/local/bin/irb:11:in `<main>'
irb(main):011:0> ActiveSupport::Inflector.safe_constantize('ActiveSupport::Dependencies')
=> nil
irb(main):012:0> require 'active_support/dependencies'
=> true
irb(main):013:0> ActiveSupport::Dependencies.autoload_paths
=> []
irb(main):014:0> ActiveSupport::Dependencies.autoload_paths << '/tmp/issue_28854/'
=> ["/tmp/issue_28854/"]
irb(main):015:0> ActiveSupport::Inflector.safe_constantize('IM::Im')
LoadError: Unable to autoload constant Im, expected /tmp/issue_28854/im.rb to define it
	from /usr/local/bundle/gems/activesupport-4.2.10/lib/active_support/dependencies.rb:495:in `load_missing_constant'
	from /usr/local/bundle/gems/activesupport-4.2.10/lib/active_support/dependencies.rb:184:in `const_missing'
	from /usr/local/bundle/gems/activesupport-4.2.10/lib/active_support/dependencies.rb:526:in `load_missing_constant'
	from /usr/local/bundle/gems/activesupport-4.2.10/lib/active_support/dependencies.rb:184:in `const_missing'
	from /usr/local/bundle/gems/activesupport-4.2.10/lib/active_support/inflector/methods.rb:263:in `const_get'
	from /usr/local/bundle/gems/activesupport-4.2.10/lib/active_support/inflector/methods.rb:263:in `block in constantize'
	from /usr/local/bundle/gems/activesupport-4.2.10/lib/active_support/inflector/methods.rb:259:in `each'
	from /usr/local/bundle/gems/activesupport-4.2.10/lib/active_support/inflector/methods.rb:259:in `inject'
	from /usr/local/bundle/gems/activesupport-4.2.10/lib/active_support/inflector/methods.rb:259:in `constantize'
	from /usr/local/bundle/gems/activesupport-4.2.10/lib/active_support/inflector/methods.rb:304:in `safe_constantize'
	from (irb):15
	from /usr/local/bin/irb:11:in `<main>'
irb(main):016:0> ActiveSupport::Inflector.safe_constantize('IM::IM')
=> nil
```

This is very confusing. As a developer, I don't understand why the `safe_constantize` still tries to resolve an acronym under the wrong name and at the wrong path.

I suggest at least updating the documentation on these two methods which rely on the autoload and inflector modules of active support. But generally, this is quite inconsistent.

Thanks for taking time to look into it.
