### ISSUE TITLE
[ActiveRecord] `includes` ignored when using `update_all`

### ISSUE THREAD

**Issue by Dorian** [rails/rails#28863]
### Steps to reproduce

```ruby
Sitter.includes(:bookings).where(bookings: { id: nil }).update_all(status_id: 1)
```

### Expected behavior

```sql
UPDATE "sitters" SET "status_id" = 1 WHERE (id in (SELECT "sitters"."id" FROM "sitters" LEFT OUTER JOIN "bookings" ON "bookings"."sitter_id" = "sitters"."id" WHERE "bookings"."id" IS NULL))
```

```
# minus all the extra fields
PLUCK_IDS_QUERY = Sitter.includes(:bookings).where(bookings: { id: nil }).select(:id).to_sql

Sitter.where("id in (#{PLUCK_IDS_QUERY})").update_all(status_id: 1)
```

### Actual behavior

Fails with:

```sql
UPDATE "sitters" SET "status_id" = 1 WHERE "bookings"."id" IS NULL
```

### System configuration

- **Rails version**: `Rails 5.0.2`
- **Ruby version**: `ruby 2.4.1p111 (2017-03-22 revision 58053) [x86_64-darwin16]`

**Comment by st0012** [comment]
@Dorian Why do you want to use `includes` in this case? I think you should use `joins` instead of `includes`

```ruby 
Sitter.joins(:bookings).where(bookings: { id: nil }).update_all(status_id: 1)
```

**Comment by jomz** [comment]
I think I'm running into this same bug. Trying to make a scope with .includes which is ignored. Works if I use left_outer_join instead;
https://pastebin.com/raw/QeyNMnFh

Rails 5.1.2
Ruby 2.4.1

**Comment by inopinatus** [comment]
@st0012 `update_all` doesn't actually work with `joins`.

e.g.

```
Notification.joins(:alarm).update_all("notifications.device_id = alarms.device_id")
# => PG::UndefinedTable: ERROR:  missing FROM-clause entry for table "alarms"
```

because the SQL produced is `UPDATE "notifications" SET notifications.device_id = alarms.device_id WHERE "notifications"."id" IN (SELECT "notifications"."id" FROM "notifications" INNER JOIN "alarms" ON "alarms"."id" = "notifications"."alarm_id")`.
