### ISSUE TITLE
rails-ujs: "TypeError: Handler is undefined"

### ISSUE THREAD

**Issue by jcoyne** [rails/rails#28878]
Using Rails 5.1.0.rc2

When I load my page on firefox 52.0.2 I get this error:
<img width="1434" alt="screen shot 2017-04-25 at 1 08 44 pm" src="https://cloud.githubusercontent.com/assets/92044/25400475/58c9408c-29b8-11e7-8afd-6a0ea0cd418b.png">

It runs through this method about 5 times with a handler, and then it is invoked without one:

<img width="1119" alt="screen shot 2017-04-25 at 1 09 59 pm" src="https://cloud.githubusercontent.com/assets/92044/25400556/9962e47c-29b8-11e7-8ff8-feaf2cf117e6.png">

Called from here:
<img width="737" alt="screen shot 2017-04-25 at 1 11 32 pm" src="https://cloud.githubusercontent.com/assets/92044/25400640/cd52ad08-29b8-11e7-9c33-35f030020962.png">

Moved from https://github.com/rails/jquery-ujs/issues/493

It looks to me like https://github.com/rails/rails/blob/master/actionview/app/assets/javascripts/rails-ujs/features/disable.coffee was never compiled into rails-ujs.js

**Comment by jcoyne** [comment]
I think that method exists in master https://github.com/rails/rails/blob/master/actionview/app/assets/javascripts/rails-ujs/features/disable.coffee#L5 but not on the 5-1-stable branch https://github.com/rails/rails/blob/5-1-stable/actionview/app/assets/javascripts/rails-ujs/features/disable.coffee

/cc @rafaelfranca

**Comment by jcoyne** [comment]
I think this regression was introduced in https://github.com/rails/rails/commit/154c879e097ba088a8eee1d55f4d9703b70680b7

**Comment by rafaelfranca** [comment]
Fixed in 3d43a96b24

**Comment by jcoyne** [comment]
@rafaelfranca You rock! 🎸 ⚡️   Thank you!
