### ISSUE TITLE
Move ActionController::TestCase to its own gem

### ISSUE THREAD

**Issue by aried3r** [rails/rails#28870]
I saw this commit https://github.com/rails/rails/commit/f42ac6a06880bfc02857ab71758214ad7867c22f talking about moving `ActionController::TestCase` to its own gem, but haven't seen that happen yet. I also found this commit https://github.com/rails/rails/commit/b556e2b483019260ece880a157cc6844a8d5163e from a few months later, so I'm not sure if `ActionController::TestCase` is here to stay or if it has not yet been moved for the upcoming 5.1 release.

I only realized just now when using 5.1.0 RC2 and the tests still running without adding a separate gem.

**Comment by rafaelfranca** [comment]
Right now we don't have plans to move it but it is deprecated so we don't recommend new tests to use this class.
