### ISSUE TITLE
[ActiveJob] rescue_from not working

### ISSUE THREAD

**Issue by fguillen** [rails/rails#28874]
I am trying to reproduce this example code: https://apidock.com/rails/ActiveJob/Enqueuing/retry_job but I don't manage to make the `rescue_from` working in an ActiveJob

### Steps to reproduce
I have prepared a test project:

- https://github.com/fguillen/TestingActiveJobRescueFrom

### Expected behavior
In this Job: 

- https://github.com/fguillen/TestingActiveJobRescueFrom/blob/master/app/jobs/test_job_job.rb

I am expecting to see the `rescue_from` message when I perform the Job:

    irb(main):005:0> TestJobJob.perform_now

### Actual behavior
Instead of the message I see the Exception been propagated:

```
irb(main):004:0> TestJobJob.perform_now
Performing TestJobJob from Async(default)
Performed TestJobJob from Async(default) in 0.82ms
Exception: This is the error message
	from /Users/fguillen/Development/Temp/TestingActiveJobRescueFrom/app/jobs/test_job_job.rb:9:in `perform'
	from /Users/fguillen/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activejob-5.0.2/lib/active_job/execution.rb:34:in `block in perform_now'
	from /Users/fguillen/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activesupport-5.0.2/lib/active_support/callbacks.rb:126:in `call'
	from /Users/fguillen/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activesupport-5.0.2/lib/active_support/callbacks.rb:506:in `block (2 levels) in compile'
	from /Users/fguillen/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activesupport-5.0.2/lib/active_support/callbacks.rb:455:in `call'
	from /Users/fguillen/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activesupport-5.0.2/lib/active_support/callbacks.rb:448:in `block (2 levels) in around'
	from /Users/fguillen/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activesupport-5.0.2/lib/active_support/callbacks.rb:286:in `block (2 levels) in halting'
	from /Users/fguillen/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/i18n-0.8.1/lib/i18n.rb:257:in `with_locale'
```

Same behaviour when I try to reproduce the issue in a test:

- https://github.com/fguillen/TestingActiveJobRescueFrom/blob/master/test/jobs/test_job_job_test.rb

### System configuration
**Rails version**: 5.0.2
**Ruby version**: 2.3.1p112

**Comment by rafaelfranca** [comment]
`Exception` is not an rescueable exception class. Only subclasses of `StandardError` is. Rescuing `Exception` is usually a bad practice.

**Comment by fguillen** [comment]
@rafaelfranca then we should do something with the documentation of `rescue_from` because it is not clear at all:

- https://apidock.com/rails/ActiveSupport/Rescuable/ClassMethods/rescue_from

> Rescue exceptions raised in controller actions.

Even in the community examples in the above page there are some `rescue_from Exception, :with => :error_generic` ?

**Comment by fguillen** [comment]
Confirmed that raising `StandardError` the `rescue_from` block works properly:

    class TestJob2Job < ApplicationJob
      queue_as :default

      rescue_from Exception do |exception|
        Rails.logger.info "I am on rescue_from: #{exception}"
      end

      def perform(*args)
        raise StandardError.new("This is the error message")
      end
    end

I am seeing that this behaviour is not coherent with the `rescue_from` in a `ActionController::Base` for example:

    class MyTestsController < ApplicationController
      rescue_from Exception do |exception|
        render plain: "Rescuing the exception: '#{exception}'", status: 500
      end

      def raise_exception
        raise Exception.new("This is an Exception")
      end

      def raise_standard_error
        raise StandardError.new("This is an StandardError")
      end
    end

In the above case both `Exception` and `StandardError` will be captured by the `rescue_from` block. Check here:

- https://github.com/fguillen/TestingActiveJobRescueFrom/commit/fdbb58bd1bd9e7a1e0b90953d318b8aacddb248c

**Comment by rafaelfranca** [comment]
In this case this is a nice inconsistence. Recuing `Exception` is really a bad practice. Unfortunately `rescue_from` in `ActionController::Base` supports it, but I prefer to not add support in any other new `rescue_from` blocks.

**Comment by fguillen** [comment]
@rafaelfranca I understand the reason of saying rescuing Exception is a bad practice, basically because the [broadness of this class](http://stackoverflow.com/questions/10048173/why-is-it-a-bad-style-to-rescue-exception-e-in-ruby), but the actual implementation also ignoring more customized Exceptions as:

```
class MyCustomException < Exception
end
```

The actual `ActiveJob.rescue_from` is also ignoring the above customized Exception:

- https://github.com/fguillen/TestingActiveJobRescueFrom/commit/ffaf11b2fa321c124b74332bf5fa1e7c3d6dde2d

**Comment by rafaelfranca** [comment]
Yes. You should also not inherit from Exception. `StandardError` is what you want.

**Comment by fguillen** [comment]
Ok I see, thanks @rafaelfranca

**Comment by anhadgill23** [comment]
@rafaelfranca is there a way to rescue `SignalException`, specifically the `Interrupt` error handling subclass for a job?
