### ISSUE TITLE
Setting datetime inside Time#use_zone does not work

### ISSUE THREAD

**Issue by wdruzkawiecki** [rails/rails#28877]
### Steps to reproduce
```ruby
event = Event.new # start_at: datetime
Time.use_zone("Sydney") { event.start_at = "2017-05-01 13:00" }
event.start_at
event
```

### Expected behavior
> Mon, 01 May 2017 13:00:00 AEST +10:00
#<Event id: nil, name: nil, start_at: "2017-05-01 03:00:00", created_at: nil, updated_at: nil> 

### Actual behavior
> Mon, 01 May 2017 13:00:00 UTC +00:00
#<Event id: nil, name: nil, start_at: "2017-05-01 13:00:00", created_at: nil, updated_at: nil>

### System configuration
**Rails version**: Rails 5.0.2

**Ruby version**: ruby 2.3.0p0 (2015-12-25 revision 53290) [x86_64-linux]

**Postgresql version**: psql (PostgreSQL) 9.5.6

### Additional info

In my another project on ruby 2.3.0 and rails 4.2.6 it works fine.

```ruby
2.3.0 :001 > event = Event.new
 => #<Event id: nil, name: nil, start_at: nil, created_at: nil, updated_at: nil> 
2.3.0 :002 > Time.use_zone("Sydney") { event.start_at = "2017-05-01 13:00" }
 => "2017-05-01 13:00" 
2.3.0 :003 > event.start_at
 => Mon, 01 May 2017 13:00:00 AEST +10:00 
2.3.0 :004 > event
 => #<Event id: nil, name: nil, start_at: "2017-05-01 03:00:00", created_at: nil, updated_at: nil> 
2.3.0 :005 > 
```

**Comment by pixeltrix** [comment]
This is because the typecast has been moved from on write to on read - not sure this is going to be easy to fix

**Comment by smadeja** [comment]
To put it more into context, this is the kind of thing we're trying to achieve.

```ruby
def start_at=(datetime)
  Time.use_zone(time_zone) do
    super
  end
end
```

The model has its own time zone, and we'd like to apply it by default to all the datetime fields. It seems to work with the following hack. (And it worked on Rails 4 without any hacks.)

```ruby
def start_at=(datetime)
  Time.use_zone(time_zone) do
    super; start_at
  end
end
```

Do you maybe know of a better way of doing this, @pixeltrix? We're basing our approach on the "Working with multiple user time zones" section from [here](https://www.varvet.com/blog/working-with-time-zones-in-ruby-on-rails/).

**Comment by pixeltrix** [comment]
@smadeja yes, that workaround will trigger a read so make the typecast happen inside the execution of the `use_zone` block.

I've discussed this with @sgrif and we agree that we should record the timezone in effect when the attribute was set so that we can use that in the typecast. Moving the typecast back to write would result in a performance degradation.

**Comment by DanielHeath** [comment]
As of rails 7, this appears to have broken again:

Rails 6.1.6:
```
Time.use_zone("Perth") { c = Course.new; c.start_date = '2015-03-02 09:00:00.000000000 +0000'; c.start_date}
=> Mon, 02 Mar 2015 17:00:00.000000000 AWST +08:00
```

Rails 6.1.6:
```
Time.use_zone("Perth") { c = Course.new; c.start_date = '2015-03-02 09:00:00.000000000 +0000'; c.start_date}
=> 2015-03-02 09:00:00 UTC
```
