### ISSUE TITLE
5.1.0.rc2 Does not properly handle fixtures on postgres where the tables have a foreign key with on_delete restrict or cascade.

### ISSUE THREAD

**Issue by AndrewSwerlick** [rails/rails#28888]
### Steps to reproduce

Create two tables like this in a migration 

    create_table :connections do |t|
      t.string :status, null: false
      t.timestamps
    end

    create_table :connection_members do |t|
      t.belongs_to :connection, foreign_key: { on_delete: :restrict }, null: false
      t.timestamps
    end

Then create corresponding fixtures. When you run your tests you'll recieve the following error 

    ActiveRecord::InvalidForeignKey: PG::ForeignKeyViolation: ERROR:  update or delete on table "connections" violates foreign key constraint "fk_rails_8b5000f871" on table "connection_members"
    DETAIL:  Key (id)=(31264196) is still referenced from table "connection_members".

### Expected behavior
In previous versions of rails these tests would work fine. The fixtures would load properly.

### Actual behavior
The above error

### System configuration
**Rails version**:
5.1.0.rc2

**Ruby version**:
2.4.1

I believe this issue is tied to the changes from this pull request https://github.com/rails/rails/pull/27636. The code in that request switches the behavior of rails fixtures to rely on deferred constraints in postgres, rather than disabling triggers. However both the RESTRICT and CASCADE constraints cannot be deferred, as called out in the postgres docs here https://www.postgresql.org/docs/9.5/static/sql-createtable.html. 

>  Referential actions other than the NO ACTION check cannot be deferred, even if the constraint is declared deferrable.

Patching the PostgreSQLAdapter to go back to the old behavior resolves the issue. Here's an example patch 

    require 'active_record/connection_adapters/postgresql_adapter'

    module FixReferentialIntegrityHandling

      def disable_referential_integrity(&block)
        if supports_disable_referential_integrity?
          disable_referential_integrity_with_disable_trigger(&block)
        else
          yield
        end
      end
    end

    ActiveRecord::ConnectionAdapters::PostgreSQLAdapter.send :include, FixReferentialIntegrityHandling

**Comment by rafaelfranca** [comment]
Fixed on 5-1-stable

**Comment by defkode** [comment]
Why is this fix reverted?

**Comment by rafaelfranca** [comment]
@defkode the commit message explains it https://github.com/rails/rails/commit/2812694aa65e4d0591e0ea6c5f7d8c97927be7dc
