### ISSUE TITLE
form_with model parameter

### ISSUE THREAD

**Issue by savroff** [rails/rails#28893]
Hi everyone, after we get fancy new `form_with` I start thinking about syntax.

Right now we have this for `form_for`:
```
= form_for @form, ... do |f|
```

With new version, we can move to 

```
= form_with model: @form, ... do |f|
```

All seems good, but `@form` in our case, not a model, it's a form object. 
Don't you think that it's a little bit confusing?

**Comment by rafaelfranca** [comment]
Thank you for the report. By the model definition in the MVC pattern a form object is also a model. So the method call is correct.

**Comment by savroff** [comment]
@rafaelfranca ok, thank you for clarifying!
