### ISSUE TITLE
Rails 5.1 showing wrong error message when routing error happens

### ISSUE THREAD

**Issue by prathamesh-sonpatki** [rails/rails#28892]
### Steps to reproduce

rails new blog --dev # pointing to 5-1-stable
edit config/routes.rb and add `resources :articles`
rails s
visit localhost:3000/articles/new

Shows error: http://take.ms/GSbZ9

On Rails 5.0.2, it shows proper routing error: https://monosnap.com/file/hDZjt99m2vkXe3kP9K1hxhz0uALq1f

Puma version: 3.8.2

Stacktrace: https://gist.github.com/prathamesh-sonpatki/c2f97d0540adbc9562171b9a0787b39a

Looks like it is rendering the [FAILSAFE response](https://github.com/rails/rails/blob/eac6f3690fd245b9d72aadcfa365ed16c4ef8b96/actionpack/lib/action_dispatch/middleware/show_exceptions.rb#L18) but not sure why.

Found this while following the steps from getting started guide on the new app created from 5-1-stable branch.

cc @rafaelfranca

**Comment by prathamesh-sonpatki** [comment]
Example app https://github.com/prathamesh-sonpatki/blog-5-1

**Comment by prathamesh-sonpatki** [comment]
Looks like related to https://github.com/rails/rails/commit/2eb0a6630ac as now we are trying to [load controller_class](https://github.com/rails/rails/blob/eac6f3690fd245b9d72aadcfa365ed16c4ef8b96/actionpack/lib/action_dispatch/http/parameters.rb#L88) and in this case, the controller class does not exist.

**Comment by vipulnsward** [comment]
cc @tenderlove

**Comment by tenderlove** [comment]
I'll take a look.  My guess is that the routing error middleware is at the wrong level.  In this case maybe we should explicitly render the routing error (rather than having a middleware catch an exception somehow)
