### ISSUE TITLE
ActiveModel::Errors deletes all the Translations Lookup when message flag is set

### ISSUE THREAD

**Issue by alexsotocx** [rails/rails#28903]
### Steps to reproduce
Use inheritance in ActiveModel and set I18n errors, add an error with default message, it will only show the default message.
```ruby
require "rails_helper"
# Using gem "rails-i18n", "~> 5.0", ">= 5.0.3"
describe "Issue" do
  class Person
    include ActiveModel::Model
    extend ActiveModel::Translation

    attr_accessor :name

    def add_error
      errors.add(:name, :blank, message: "This is the default message")
    end
  end

  class Kid < Person
    extend ActiveModel::Translation
  end

  it "test" do
    I18n.locale = :en
    # Translation attribute level
    I18n.backend.store_translations "en", activemodel: { errors: { models: { person: { attributes: { name: { blank: "Attribute level" } } } } } }
    puts I18n.t("activemodel.errors.models")
    # Translation at message level
    I18n.backend.store_translations "en", activemodel: { errors: { messages: { blank: "Global Level" } } }

    kid = Kid.new
    person = Person.new

    kid.add_error
    person.add_error
    expect(person.errors.full_messages).to contain_exactly("Name Attribute level")
    expect(kid.errors.full_messages).to eq(["Name Attribute Level"])
  end

  # Failure/Error: expect(kid.errors.full_messages).to eq(["Name Attribute Level"])
  #
  #      expected: ["Name Attribute Level"]
  #           got: ["Name This is the default message"]
end
```

From the Rails I18nGuide sections 4.5.1, this is overrides by adding a default message (https://github.com/rails/rails/blob/5-0-stable/activemodel/lib/active_model/errors.rb#L493)
```
Then Active Record will look for messages in this order:

activerecord.errors.models.admin.attributes.name.blank
activerecord.errors.models.admin.blank
activerecord.errors.models.user.attributes.name.blank
activerecord.errors.models.user.blank
activerecord.errors.messages.blank
errors.attributes.name.blank
errors.messages.blank
```
The message passed as default violates the normal behaviour as stated on https://github.com/svenfuchs/i18n/blob/master/lib/i18n.rb#L105-L116

### Expected behavior
It should lookup all the inheritance and return the default if and only if there is no translation.

### Actual behavior
The translation is using the default message in the inheritance.

### How to solve it
The line https://github.com/rails/rails/blob/5-0-stable/activemodel/lib/active_model/errors.rb#L493 should be changed to (`<< instead of =`)
`defaults << options.delete(:message) if options[:message]`

### System configuration
**Rails version**:
5.0.2

**Ruby version**:
2.3.3

**Comment by pixeltrix** [comment]
@alexsotocx thanks for finding the bug - are you planning to write a PR?

**Comment by alexsotocx** [comment]
@pixeltrix I already tried, but you have test coverage for this(With the change it broke like 36 tests). I'm afraid that the behaviour was intended.
For example:
`validates name, presence: true, message: "This is something"` 
The problem now that this is too widely used, so we can break all the apps.

**Comment by pixeltrix** [comment]
@alexsotocx yeah, I think on reflection what's happening is that you're saying you want to override that defaults lookup chain when you use the `:message` option - hard to see how we could fallback to that default lookup in a subclass. Possibly one option would be to store the custom message in the backend at boot rather than overriding defaults so that it matches on the key when you do a lookup.

**Comment by 4geru** [comment]
@alexsotocx cc: @pixeltrix Associated pull request is already closed. does this pull request still have any problems?

**Comment by alexsotocx** [comment]
Sure, Thanks :) I will proceed to close it

**Comment by jonathanhefner** [comment]
@4geru Could you provide a link to the closed PR that you are referring to?
