### ISSUE TITLE
Rails converted multidimension array to nil when post

### ISSUE THREAD

**Issue by jeffrey008** [rails/rails#28900]
### Steps to reproduce
I posted a 2D array ` table: [[1,2,3] , [4,5,6]]` to my controller, but the controller gives `[nil, nil, nil, nil, nil, nil]`.

### Expected behavior
Table should still be a 2D array `[[1,2,3] , [4,5,6]]`.

### Actual behavior
Rails flattened my array and changed all values to nil.

### System configuration
**Rails version**:
Rails 4.2.0
**Ruby version**:
ruby 2.2.5-p319
**config**:
I have already disabled `perform_deep_munge`.
```ruby
#config/application.rb
config.action_dispatch.perform_deep_munge = false
```

**Comment by pixeltrix** [comment]
What was the format of the POST - `application/x-www-form-urlencoded` or `application/json`? Can you please show us the POST body so that we can double check the format, thanks.

**Comment by jeffrey008** [comment]
After adding `application/json` to my header, the problem was gone.

What I did previously is:
```
HTTParty.post("url", body: body)
```

What works for me:
```
HTTParty.post("url", body: body.to_json , headers: { 'Content-Type': 'Application/json'} )
```

However I am not fully understand what is the difference between two and how Rails response differently to them.
