### ISSUE TITLE
rails new does not work with --webpack and --skip-bundle on Rails 5.1

### ISSUE THREAD

**Issue by jarednorman** [rails/rails#28916]
### Steps to reproduce

Run this command: `rails new --webpack --skip-bundle test_app`

### Expected behavior

Probably bailing out and informing the user that it's not possible to install webpacker without running bundle is the best option here.

### Actual behavior

It generates the initial project structure and then errors out at the `webpacker:install` step.

```
       rails  webpacker:install
Could not find gem 'rails (~> 5.1.0)' in any of the gem sources listed in your Gemfile.
Run `bundle install` to install missing gems.
```

### System configuration
**Rails version**: 5.1.0

**Ruby version**: 2.4.0p0

**bundler version**: 1.14.6

**Comment by maclover7** [comment]
cc @dhh @gauravtiwari

**Comment by gauravtiwari** [comment]
Yes, expected behaviour sounds right to me. Will push up a fix for install task to bail out if webpacker isn't bundled.
