### ISSUE TITLE
The bundled verison of rails-ujs is broken in ActionView 5.1.0-rc2

### ISSUE THREAD

**Issue by vincentwoo** [rails/rails#28917]
### Steps to reproduce

1. Examine the file `actionview-5.1.0.rc2/lib/assets/compiled/rails-ujs.js`
2. Note that sections defining functionality like [Rails.handleDisableElement](https://github.com/rails/rails/blame/896ee2b679462e7bcaa6890c6f5fdbd3b2e2fccb/actionview/app/assets/javascripts/rails-ujs/features/disable.coffee#L5) do *not* seem to be present in the compiled bundle.

### Expected behavior
The stuff should be in the thing.

### Actual behavior
The stuff is not in the thing, causing runtime issues with rails-ujs when using the actionview bundled copy.

Note however that the copy of `rails-ujs` in npm appears to be correct, as it has this section in `lib/assets/compiled/rails-ujs.js`, lines 368-374:

```js
      Rails.handleDisabledElement = function(e) {
        var element;
        element = this;
        if (element.disabled) {
          return stopEverything(e);
        }
      };
```

### System configuration
**Rails version**: 5.1.0-rc2

**Ruby version**: 2.4.0

**Comment by y-yagi** [comment]
Already fixed by https://github.com/rails/rails/commit/3d43a96b24c24ef3767a42b3960f9b4465826498

**Comment by vincentwoo** [comment]
Ah, okay.
