### ISSUE TITLE
make form_with work nicely with params

### ISSUE THREAD

**Issue by grosser** [rails/rails#28925]
Usecase: I want my search forms to display the values the user just searched form
Problem: It's tedious to always add `selected: params.dig(:search, :foo)` to every select/text_field
Solution:  `form_with` picks selected values from `params`, 

I'm currently using this, which makes model and param forms act the same. Maybe have a `params: true` option to make it pick values from params automatically ?

```Ruby
form_with model: ParamsFormObject.new(params[:search]), scope: :search, url: '?', method: :get do |form|
  form.select :foobar, [1, 2, 3]
end

class ParamsFormObject
    def initialize(params)
      @params = params || {}
    end

    def method_missing(name, *)
      @params[name]
    end

    def respond_to_missing?(*)
      true
    end
  end
```

**Comment by maclover7** [comment]
cc @kaspth

**Comment by kaspth** [comment]
Not convinced `form_with` should respect `[]` and `[]=` after trying standard readers and writers, from just this use case.

Why not start with a `search_form_with` helper in your app instead? That's as close to the use case as you're gonna get and it establishes the conventions of how your app's search forms typically work. E.g.:

```ruby
def search_form_with(param: :search, **form_options, &block)
  form_with(model: ParamWrapper.new(params[param]), method: :get, scope: param, url: "?", **form_options, &block)
end

search_form_with param: :search
```

**Comment by grosser** [comment]
that's exactly what I'm doing ;)
I was not suggesting it should fall back to `:[]`, but that it gets some internal `oh this is params, use [] instead of sending methods` logic to not need this method_missing wrapper

**Comment by kaspth** [comment]
True, you didn't say that, but the `params: true` suggestion grates Rails' aesthetic, I think. So I thought of the alternative that I would be most willing to accept. However, I don't find the use case compelling enough to bake that into `form_with` 😊

**Comment by rafaelfranca** [comment]
Any object passed to a form needs to follow the Active Model API. That is the minimum requirement. Although the API don't require accessors to be defined I don't think `form_with` should behave differently of `form_for` in the implementation.

**Comment by grosser** [comment]
... just realized that I can simply wrap the params in OpenStruct and it will work ... so no need for extra code in rails ;)
