### ISSUE TITLE
Problem implementing polymorphic behavior with STI

### ISSUE THREAD

**Issue by mesirendon** [rails/rails#28922]
### Steps to reproduce

Hi, I'm dealing with a problem where I have to use polymorphic behavior and STI. And despite, I've read a lot of docs, and search for similar issues, I got nothing yet.

Here's my code:

```ruby
# app/models/place.rb
class Place < ApplicationRecord
  belongs_to :localizable, polymorphic: true
  def localizable_type=(class_name)
    super(class_name.constantize.base_class.to_s)
  end
end

# app/models/user.rb
class User < ApplicationRecord
  has_many :places, -> {where(show: true)}, as: :localizable
  validates_presence_of :username
  validates_presence_of :password
end

# app/models/warehouse.rb
class Warehouse < User
  alias_attribute :name, :first_name
  validates_presence_of :name
end

# app/models/producer.rb
class Producer < User
  validates_presence_of :first_name
  validates_presence_of :last_name
end
```

### Expected behavior
I expect querying the `Producer` and the `Warehouse` to get their `Place`s like this.

```bash
p = Producer.find(1)
w = Warehous.find(2)

p.places
SELECT "places".* FROM "places" WHERE "places"."localizable_id" = $1 AND "places"."localizable_type" = $2 AND "places"."show" = $3 ORDER BY places.tag ASC  [["localizable_id", 1], ["localizable_type", "Producer"], ["show", "t"]]
w.places
SELECT "places".* FROM "places" WHERE "places"."localizable_id" = $1 AND "places"."localizable_type" = $2 AND "places"."show" = $3 ORDER BY places.tag ASC  [["localizable_id", 2], ["localizable_type", "Warehouse"], ["show", "t"]]
```

### Actual behavior
However, the queries that I always get are related to `User`, not its children.
```bash
irb(main):049:0> p.places
  Place Load (0.4ms)  SELECT "places".* FROM "places" WHERE "places"."localizable_id" = $1 AND "places"."localizable_type" = $2 AND "places"."show" = $3 ORDER BY places.tag ASC  [["localizable_id", 1], ["localizable_type", "User"], ["show", "t"]]
=> #<ActiveRecord::Associations::CollectionProxy []>

rb(main):052:0> w.places
  Place Load (0.6ms)  SELECT "places".* FROM "places" WHERE "places"."localizable_id" = $1 AND "places"."localizable_type" = $2 AND "places"."show" = $3 ORDER BY places.tag ASC  [["localizable_id", 2], ["localizable_type", "User"], ["show", "t"]]
=> #<ActiveRecord::Associations::CollectionProxy []>
```

### System configuration
**Rails version**: 
```bash
rails -v
Rails 5.1.0
```

**Ruby version**:
```bash
ruby -v
ruby 2.4.0p0 (2016-12-24 revision 57164) [x86_64-linux]
```

**Gemfile.lock**
```
GEM
  remote: https://rubygems.org/
  
PLATFORMS
  ruby

DEPENDENCIES
  active_model_serializers
  apipie-rails (~> 0.5.0)
  byebug
  database_cleaner
  factory_girl_rails (~> 4.0)
  faker
  hirb
  listen (>= 3.0.5, < 3.2)
  pg (~> 0.18)
  puma (~> 3.7)
  rack-attack
  rack-cors
  rails (~> 5.1.0)
  rspec-rails (~> 3.5)
  shoulda-matchers (~> 3.1)
  spring
  spring-watcher-listen (~> 2.0.0)
  tzinfo-data

BUNDLED WITH
   1.14.6
```

**Comment by rab** [comment]
perhaps you want: `class_name.constantize.base_class.sti_name`

I think that you're misunderstanding how STI works with polymorphism. The `localizable_type` and `localizable_id` reference (indirectly) the *table* and the record. It is the `type` column in the STI table itself that indicates the ultimate model class that is instantiated.

**Comment by mesirendon** [comment]
Hi @rab . Thanks for the reply.

Well, I also tried what you pointed out, but still having the same response. I've based my code on the documentation at http://api.rubyonrails.org/classes/ActiveRecord/Associations/ClassMethods.html under the section **Polymorphic Associations**. That's what's recommended. I'm still trying to figure out what I'm missing.

**Comment by rab** [comment]
Well, I guess _part_ of what I'm saying is that the documentation might be wrong, but also that your expectation that the query would use `Producer` and `Warehouse` rather than just `User` may be equally wrong. (Possibly misled by the docs.)

I believe that if you have:

```ruby
# app/models/place.rb
class Place < ApplicationRecord
  belongs_to :localizable, polymorphic: true
  def localizable_type=(class_name)
    super(class_name.constantize.base_class.sti_name)
  end
end
```

that the code will work properly, the generated queries will be what you have in *Actual* behavior, and the `type` column in the `users` table will have the `Producer` or `Warehouse` value that you need (for the STI to work).

If it _doesn't work_, then perhaps you can explain where it is broken rather than where it doesn't conform to your (_current_) expectation. (I've dealt with a lot of polymorphic associations in the past -- back from even before polymorphic associations existed in Rails, in fact.)

**Comment by mesirendon** [comment]
Hi @rab thanks for replying.

I'm still lost at this. I'm kinda new to ruby and rails. The only place I have to get an official way to use rails in the documentation, and as you say I might be misled because of what the documentation says.

I wrote the `localizable_type=` method as you suggested, but still not getting the behavior I want.

I'm using the rails console, because I want to guarantee my models do as planned leaving controllers out of this logic. If I create a `Producer` I see it works, it clearly identifies the type of user and gives me this:

```bash
irb(main):002:0> p = Producer.create(username: 'mesirendon', password:'123', email: 'a', first_name: 'mesi', last_name: 'rendon')
   (0.2ms)  BEGIN
  SQL (0.7ms)  INSERT INTO "users" ("username", "password", "email", "first_name", "last_name", "type", "created_at", "updated_at") VALUES ($1, $2, $3, $4, $5, $6, $7, $8) RETURNING "id"  [["username", "mesirendon"], ["password", "123"], ["email", "a"], ["first_name", "mesi"], ["last_name", "rendon"], ["type", "Producer"], ["created_at", "2017-04-30 19:13:39.648989"], ["updated_at", "2017-04-30 19:13:39.648989"]]
   (18.7ms)  COMMIT
+----+------------+----------+-------+------------+-----------+----------+------+-----------+-------------------------+-------------------------+
| id | username   | password | email | first_name | last_name | type     | show | origin_id | created_at              | updated_at              |
+----+------------+----------+-------+------------+-----------+----------+------+-----------+-------------------------+-------------------------+
| 1  | mesirendon | 123      | a     | mesi       | rendon    | Producer | true |           | 2017-04-30 19:13:39 UTC | 2017-04-30 19:13:39 UTC |
+----+------------+----------+-------+------------+-----------+----------+------+-----------+-------------------------+-------------------------+
1 row in set
```

Keeping on mind that I wrote the `localizable_type=` at the `Place` model as you suggested, when I type this, I get the unwanted behavior:

```bash
irb(main):003:0> p.places.create(tag: "Home", lat: 12.12, lon: 12.12)
   (0.2ms)  BEGIN
"User"
  User Load (0.5ms)  SELECT  "users".* FROM "users" WHERE "users"."id" = $1 LIMIT $2  [["id", 1], ["LIMIT", 1]]
  SQL (1.6ms)  INSERT INTO "places" ("tag", "lat", "lon", "created_at", "updated_at", "localizable_type", "localizable_id") VALUES ($1, $2, $3, $4, $5, $6, $7) RETURNING "id"  [["tag", "Home"], ["lat", 12.12], ["lon", 12.12], ["created_at", "2017-04-30 19:20:53.420842"], ["updated_at", "2017-04-30 19:20:53.420842"], ["localizable_type", "User"], ["localizable_id", 1]]
   (1.1ms)  COMMIT
+----+------+-------+-------+-------------------------+-------------------------+------+------------------+----------------+
| id | tag  | lat   | lon   | created_at              | updated_at              | show | localizable_type | localizable_id |
+----+------+-------+-------+-------------------------+-------------------------+------+------------------+----------------+
| 1  | Home | 12.12 | 12.12 | 2017-04-30 19:20:53 UTC | 2017-04-30 19:20:53 UTC | true | User             | 1              |
+----+------+-------+-------+-------------------------+-------------------------+------+------------------+----------------+
1 row in set
```
I'd appreciate if you tell me where to read something to. Here's at the model is right now https://github.com/TrazabilidadUNAL/shimizusuntou/commit/f218b18f1366d946899442bc26bfd95dc6ca0687

I really appreciate any advise.

**Comment by rab** [comment]
So, if you were to find that very place in the console:

```ruby
home = Place.find(1)
home.localizable.class
# => Producer
```

This is what I meant by the code *will work* and you just need to align your expectations with how things _actually_ work rather than how you imagine that they should.

**Comment by mesirendon** [comment]
@rab I really appreciate your help.

I think I'm starting to grasp what you mean with "how things *actually* work rather than how [I] imagine they should".

No matter who's dealing with a `Place`, finally they're `User`s after all, and the `Place` model is doing right identifying 'who' is saving one.

If by any means another model has to deal with `Place`s, then the `Place` model will get what model class made the call.

I really, really appreciate the time you spent having me understand this. Thank you very, very much :smile:
