### ISSUE TITLE
Unnecessary second query for an EXISTS in Rails ActiveRecord?

### ISSUE THREAD

**Issue by seanfcarroll** [rails/rails#28935]
### Steps to reproduce

Running an EXISTS subquery in ActiveRecord produces 2 SQL queries. I am not sure if this is by design, but it does add an overheard, especially in large databases.

```
User.where("exists (select 'X' from roles where roles.role = 'teacher' and roles.user_id = users.id)")
```

### Expected behavior
Is there some way so that only the second (necessary) query is run?

### Actual behaviour

Produces in the log

```
     (1.2ms)  SELECT COUNT(count_column) FROM (SELECT  1 AS count_column FROM "users" WHERE (users.id <> 3 and exists (select 'X' from roles where roles.role = 'teacher' and roles.user_id = users.id)) LIMIT $1 OFFSET $2) subquery_for_count  [["LIMIT", 2], ["OFFSET", 0]]
```

and

```
  User Load (1.0ms)  SELECT  "users".* FROM "users" WHERE (users.id <> 3 and exists (select 'X' from roles where roles.role = 'teacher' and roles.user_id = users.id)) LIMIT $1 OFFSET $2  [["LIMIT", 2], ["OFFSET", 0]]
```

Attempting to build a query like this

```
SELECT u.*
FROM users u,
     roles r
WHERE r.user_id = u.id
 AND u.id <> 3
 AND r.role = 'teacher'
```

### System configuration

Ruby 2.3.3
Rails 5.0.2
Postgres 9.5.6

### Side notes

I did try to use **find_by_sql** to achieve this, but it returns an Array rather than an ActiveRecord object.

Also logged at StackOverflow: http://stackoverflow.com/questions/43686904/unnecessary-second-query-for-an-exists-in-rails-activerecord

**Comment by matthewd** [comment]
The supplied code does not produce the queries you've shown.

Please try to produce a real example with https://github.com/rails/rails/blob/master/guides/bug_report_templates/active_record_gem.rb

**Comment by alexcameron89** [comment]
I too was not able to reproduce the queries that you have shown.

Here is the [bug report](https://gist.github.com/361612d41f0358b04ec6087599b812e6) that I used to attempt to reproduce your issue, based off of the one that Matthew provided, and you may try tweaking it to see if you can reproduce the issue.

**Comment by seanfcarroll** [comment]
OK I'll look into if something else is interfering. Thnks.
