### ISSUE TITLE
enum scope generates wrong SQL WHERE condition when using nil as an enum value

### ISSUE THREAD

**Issue by jugglinghobo** [rails/rails#28945]
### Context and TL;DR
I'm trying to put rails on top of a legacy DB.
This DB stores enumerated status information in the `tp_Measure.Disposal_Unit` column (as `Integer`).
Some of these enum values are `NULL` instead of an `int`. When calling the class scope for the values that are `NULL`, the generated `WHERE` statement checks equality with `= NULL` instead of `IS NULL`.

I am aware that this may be a very rare use case and would like to know if others have had this problem as well, or if the enum implementation is not supposed to handle this case.

Below you'll find code to describe the issue in more detail. If you think that this might really be a bug, I'll gladly prepare a test case and/or reproduction scenario.

### Steps to reproduce
Create a class that has an enum where one enum value is `nil` instead of an int or string.
Create some records of this class that have `nil` as their enum value.
```ruby
class Measure < ApplicationRecord
  self.table_name = 'tp_Measure'

  alias_attribute :disposal_unit, :Disposal_Unit

  enum disposal_unit: {
    cubic_meter: 1,
    tons: 2,
    no_data: 0,
    nothing: nil
  }
end
```

### Expected behavior
When calling the generated scopes, the generated SQL statement should consider the possibility that instead of a correctly set enum value, the DB value might be `nil`, and therefore generate the following `WHERE` condition:

```ruby
irb(main):017:0> Measure.nothing
  Measure Load (1.4ms)  SELECT `tp_Measure`.* FROM `tp_Measure` WHERE `tp_Measure`.`Disposal_Unit` IS NULL
=> #<ActiveRecord::Relation [#<Measure ... >, #<Measure ... >, ...]>
```

### Actual behavior
Currently, it is just assumed that the enum DB column only contains enum values and it is always possible to query the DB with the `=` operator.

When calling the generated class scope `Measure.nothing`:
```ruby
irb(main):017:0> Measure.nothing
  Measure Load (1.4ms)  SELECT `tp_Measure`.* FROM `tp_Measure` WHERE `tp_Measure`.`Disposal_Unit` = NULL
=> #<ActiveRecord::Relation []>
```

### System configuration
**Rails version**: 5.0.2
**ActiveRecord version**: 5.0.2
**Ruby version**: ruby 2.4.0p0 (2016-12-24 revision 57164) [x86_64-darwin16]

**Comment by alexcameron89** [comment]
Here is a [script](https://gist.github.com/10640f08ae82a3ab8d35365534c2ba25) reproducing the issue on master.

**Comment by maclover7** [comment]
Seems like the main issue here is that bind parameters are being used here. When we're building the query, and deciding whether or not attributes can be bound, we [first check](https://github.com/rails/rails/blob/master/activerecord/lib/active_record/relation/predicate_builder.rb#L172) whether the attribute is `nil`, which is why `Measure.where(disposal_unit: nil)` works. This seems like a limitation not within enum, but instead with the Attributes API. Not sure what how the query's supposed to look if an attribute serializes to `nil`. 😢

**Comment by maclover7** [comment]
Per @sgrif, using `nil` as an enum value is not supported. Opened #28948 to raise if this happens.

**Comment by jugglinghobo** [comment]
Thanks for answering this so quick.

I think disallowing `nil` is a good idea, because I found other strange behaviour that occurs because of the `nil` enum value.

Remember the enum is defined like so:

```ruby
enum disposal_unit: {
  cubic_meter: 1,
  tons: 2,
  no_data: 0,
  nothing: nil
}
```

If you aggregate on this enum, the resulting hash contains `nil` instead of `"nothing"` as the hash key:

```ruby
irb(main):003:0> Measure.group(:disposal_unit).sum(:disposal_mass)
SELECT SUM(`tp_Measure`.`Disposal_Mass`) AS sum_disposal_mass, `tp_Measure`.`Disposal_Unit` AS tp_measure_disposal_unit FROM `tp_Measure` GROUP BY `tp_Measure`.`Disposal_Unit`
=> {nil=>65174, "no_data"=>0, "cubic_meter"=>3505445, "tons"=>2280107}
```
Whereas the expected result would be
```ruby
=> {"nothing"=>65174, "no_data"=>0, "cubic_meter"=>3505445, "tons"=>2280107}
```

The easiest fix in my case is to just update all `NULL` values in this column to an unused enum value like 4, and replace the `nothing: nil` with `nothing: 4`.

I'm not sure how you handle these things, but IMO the issue can be closed. I also agree that something like https://github.com/rails/rails/pull/28948 should probably be implemented to prevent problems like mine in the future.
