### ISSUE TITLE
ActiveRecord::Base.sanitize removed in 5.1

### ISSUE THREAD

**Issue by niedfelj** [rails/rails#28947]
### Steps to reproduce

ActiveRecord::Base.sanitize seems to have been removed in 5.1 without any replacements on the class level. Is there a recommended way to sanitize/escape raw SQL for use in execute statements?

(Guidelines for creating a bug report are [available
here](http://guides.rubyonrails.org/contributing_to_ruby_on_rails.html#creating-a-bug-report))

### Expected behavior
Tell us what should happen

### Actual behavior
Tell us what happens instead

### System configuration
**Rails version**: 5.1.0 

**Ruby version**: 2.4.1

**Comment by rafaelfranca** [comment]
Yes. santize was never part of the public API of the framework. As we didn't need it in the framework anymore, we removed. The recommend ways sanitize raw SQL fro use in execute statements were the public API for that http://api.rubyonrails.org/classes/ActiveRecord/Sanitization/ClassMethods.html

**Comment by niedfelj** [comment]
@rafaelfranca Ok, I would have just expected that it would have been at least listed in the change notes or deprecated for a release as it was currently at least publicly known:

https://apidock.com/rails/ActiveRecord/Base/sanitize/class

We were using ActiveRecord::Base.sanitize in some libraries and other places where we weren't in a Rails model. The new class methods listed above now require that they be used in a model or jump through some other hoops. We've switched to using ActiveRecord::Base.connection.quote as a dropin for the previous sanitize since that was just a delegate. Is that the recommended way forward?

**Comment by kaspth** [comment]
> We were using ActiveRecord::Base.sanitize in some libraries and other places where we weren't in a Rails model.

@niedfelj our public docs are at api.rubyonrails.org. apidock.com is not a reliable place for those. That `sanitize` method wasn't public 😊

**Comment by rafaelfranca** [comment]
Only changes in the public API are listed in the change notes or goes through deprecation cycle. In this case that method never was in the public API.

**Comment by 9mm** [comment]
How can I just sanitize any string, regardless of where it goes? I have a `RawQuery` module I built that loops through all the various attributes that go into the query and called `ActiveRecord::Base.sanitize()` on it... now that I can't do that though, only options which are left seem to require logic about where it goes in the query, making things a lot more complicated.

**Comment by 9mm** [comment]
Can I just use `ActiveRecord::Base.connection.quote`?

**Comment by m1neral** [comment]
I changed `ActiveRecord::Base.sanitize` to `ActiveRecord::Base.connection.quote`

**Comment by 9mm** [comment]
Thanks!

**Comment by lcoq** [comment]
@rafaelfranca Every methods described in the [documentation](http://api.rubyonrails.org/classes/ActiveRecord/Sanitization/ClassMethods.html) are "Instance Private methods", so how could we sanitize sql conditions, etc using public methods ?

Thanks !

**Comment by P9GIT** [comment]
@9mm and @m1neral 

Be aware that `ActiveRecord::Base.connection.quote` requires and utilizes a connection from your DB connection pool.
You can in other words risk starving your application for DB connections if you don't increase your pool size which then again will have implications for your database.
It seems a complete waste of a connection just to do quoting...

**Comment by 9mm** [comment]
@P9GIT so how would you do it then? I just need to escape code in a raw query

**Comment by P9GIT** [comment]
@9mm 

Ideally you would need to check out the connection and then use it for both quoting and SQL execution before returning it to the pool.
This way you only use one connection from the pool.

I would certainly like to hear what the Rails developers recommend.

In a highly threaded and busy website I wonder if the idea of using a connection from the pool for quoting is judicious...

**Comment by ykessler** [comment]
Sanitization methods available here: https://api.rubyonrails.org/classes/ActiveRecord/Sanitization/ClassMethods.html

**Comment by P9GIT** [comment]
@ykessler 

Thanks, but all these methods require a live connection for quoting as they are based on `connection.quote_string`.

**Comment by RowiDont** [comment]
I'm commenting so others who see this aren't afraid to use `ActiveRecord::Base.connection.quote`.

I think @P9GIT is overstating the issues with using `ActiveRecord::Base.connection`. I might be misreading the docs, but it seems like `connection` comes from `ActiveRecord::ConnectionAdapters::ConnectionPool#connection` (https://api.rubyonrails.org/classes/ActiveRecord/ConnectionHandling.html#method-i-connection).

Where it says:

> Retrieve the connection associated with the current thread, or call checkout to obtain one if necessary.
>
> connection can be called any number of times; the connection is held in a cache keyed by a thread.


If someone is trying to sanitize a string for use in raw sql, for the current thread processing the request, the `connection` should be the exact same between the `quote` call and the `exec_query` call.

Probably best to use the methods linked by yKessler anyways, since they can do more than just sanitize a simple string: https://api.rubyonrails.org/classes/ActiveRecord/Sanitization/ClassMethods.html
