### ISSUE TITLE
IndexDefinition (SchemaStatements) do not return index length

### ISSUE THREAD

**Issue by voltechs** [rails/rails#28958]
I was digging through schema statements, particularly for PostgreSQL, and I noticed that when we go to fetch indexes off a table we do not include/encode the length information about the index. This makes it difficult of have a full picture of the table and its indexes (for example inheritance, which I understand rails does not natively support).

Is there a specific reason for this or was this an oversight?

Here are a couple starting points.

https://github.com/rails/rails/commit/1a92ae8318c3f5720907dec671d9ebb9221c0817
https://github.com/rails/rails/blob/master/activerecord/lib/active_record/connection_adapters/postgresql/schema_statements.rb#L143

### System configuration
**Rails version**:
4.2+
**Ruby version**:
2.2.0+

**Comment by rafaelfranca** [comment]
There is no reason. Please send a PR.

Closing since this is not an issue.
