### ISSUE TITLE
Using webpack=react and css

### ISSUE THREAD

**Issue by MrSkinny** [rails/rails#28962]
The popular `create-react-app` uses a default config where you would create a complementary css file with every component, e.g.

```
// App.css

.App {
  /* stuff */
}
```

```
import './App.css';

const App = () => {
  return (
    <div className="App">App</div>
  );
};

export default App;
```

What is the best way to configure this in Rails 5.1 with `--webpack=react`?  It looks like `style-loader` and `css-loader` are bundled by default and I'm not getting an error when I `import './Whatever.css';` but it's not outputting the style tag to the DOM.

**Comment by rafaelfranca** [comment]
This issue was moved to rails/webpacker#317

**Comment by maclover7** [comment]
cc @dhh @gauravtiwari, should this be moved over to rails/webpacker?

**Comment by maclover7** [comment]
commented at the same time 😝
