### ISSUE TITLE
LoadError (cannot load such file -- coffee_script) on a new project created using --skip-coffee

### ISSUE THREAD

**Issue by pedropazello** [rails/rails#28965]
### Steps to reproduce
Create a new Rails project using `--skip-coffee` and access any page that loads `application.html.erb` layout

Example:

Run:
`rails new example-app  --skip-coffee  --edge`

and create a new scaffold:

`rails g scaffold posts title:string body:string`

and access `/posts` route

```
=> Booting Puma
=> Rails 5.2.0.alpha application starting in development on http://localhost:3000
=> Run `rails server -h` for more startup options
Puma starting in single mode...
* Version 3.8.2 (ruby 2.4.1-p111), codename: Sassy Salamander
* Min threads: 5, max threads: 5
* Environment: development
* Listening on tcp://0.0.0.0:3000
Use Ctrl-C to stop
Started GET "/posts" for 127.0.0.1 at 2017-05-02 22:13:13 -0300
   (0.9ms)  SELECT "schema_migrations"."version" FROM "schema_migrations" ORDER BY "schema_migrations"."version" ASC
Processing by PostsController#index as HTML
  Rendering posts/index.html.erb within layouts/application
  Post Load (0.7ms)  SELECT "posts".* FROM "posts"
  Rendered posts/index.html.erb within layouts/application (12.1ms)
Completed 500 Internal Server Error in 202ms (ActiveRecord: 2.6ms)


  
LoadError (cannot load such file -- coffee_script):
  
app/views/layouts/application.html.erb:7:in `_app_views_layouts_application_html_erb___254135094133469328_70356233708400'

```
### Expected behavior
`--skip-coffee` should create a new app without load coffee_script

### Actual behavior
Access any route that loads `application.html.erb` causes `LoadError (cannot load such file -- coffee_script):`

### System configuration
**Rails version**:  5.2.0.alpha

**Ruby version**: 2.4.1p111

**Comment by matthewd** [comment]
edge requires coffeescript, because that's the source we keep in git; it's converted to pure JS during the gem release.

**Comment by stevenharman** [comment]
> edge requires coffeescript, because that's the source we keep in git; it's converted to pure JS during the gem release.

@matthewd Is this also true of RC releases? I'm seeing it when trying to deploy a Rails 5.2.0.rc1 app.

**Comment by matthewd** [comment]
If you're pointing at rails/rails git, you need coffeescript; if you're using a packaged gem (including prereleases), our internal code is converted to JS and does not require coffeescript -- though that of course doesn't preclude some other library supplying a coffeescript-requiring asset.

**Comment by stevenharman** [comment]
Hmm... I'm pointed at the `5.2.0.rc1` gem with a nearly vanilla app.
