### ISSUE TITLE
Inconsistent pluralize behaviour 

### ISSUE THREAD

**Issue by zachaysan** [rails/rails#28977]
### Steps to reproduce

Using latest Ruby (2.4.1) / Rails (5.1.0) I'm encountering the following problem. I know I can write a custom inflection, but unlike `secretary_of_state => secretaries_of_state` this seems to be normal behaviour that isn't being handled correctly.

```ruby
2.4.1 :001 > "fancy_chair".pluralize
 => "fancy_chairs" 
2.4.1 :002 > "fancy_axis".pluralize
 => "fancy_axis" 
2.4.1 :003 > "axis".pluralize
 => "axes" 
```

### Expected behavior

```ruby
2.4.1 :002 > "fancy_axis".pluralize
 => "fancy_axes" 
```

### Actual behavior
```ruby
2.4.1 :002 > "fancy_axis".pluralize
 => "fancy_axis" 
```

### System configuration
**Rails version**: 5.1.0

**Ruby version**: 2.4.1

**Comment by rafaelfranca** [comment]
Even that the inflector is inconsistent it is not frozen and can't be changed in the framework anymore for backwards compatibility reasons.

**Comment by zachaysan** [comment]
Ah. Understood. I read through the source and searched through open issues first. Maybe there should be a note of this somewhere?

**Comment by matthewd** [comment]
https://github.com/rails/rails/issues?q=custom%20inflection seems to show a pretty common theme (to pick on an expression you already knew & used). There's also a note at the top of http://api.rubyonrails.org/classes/ActiveSupport/Inflector.html, and again [with the actual inflection list](https://github.com/rails/rails/blob/48b37f127fb44b787ae6c0710982d7949b14454f/activesupport/lib/active_support/inflections.rb#L4-L7).

Where else do you suggest we note it?

**Comment by zachaysan** [comment]
Errant seems to imply a mistake in choosing the correct pluralization, not that the code itself is bugged. For example "waves".singularize => "wafe", which is obviously wrong / errant.

Whereas it's *surprising* that a single word would be pluralized correctly (axis => axes) but as part of a larger set of words it would not. My typical workflow is to check a single word in the rails console before I create a migration to make sure that I get the pluralization right. So I would highlight that that is a possibility.

As for the backwards compatibility reasoning, I get it, but in the long run it would be better to issue deprecation warnings and get people that rely on `fancy_axis` or `wafe` to either migrate or write their own inflectors, if for no other reason than to stop these issues from popping up.

Either way, no big deal for me now that I know. Thanks for your time.
