### ISSUE TITLE
Rails server starts on wrong port when passed -b

### ISSUE THREAD

**Issue by astrashe** [rails/rails#28973]
### Steps to reproduce

(This is the same issue described in the closed ticket #28971.)

With Ruby 2.4.1 and Rails 5.1.0, create a new app, then start the server with "-b 0.0.0.0"

```
[root@localhost ~]# ruby -v
ruby 2.4.1p111 (2017-03-22 revision 58053) [x86_64-linux]
[root@localhost ~]# rails -v
Rails 5.1.0
[root@localhost ~]# rails new portbug

[...]

root@localhost portbug]# echo $PORT

root@localhost ~]# cd portbug
[root@localhost portbug]# rails db:create
Created database 'db/development.sqlite3'
Created database 'db/test.sqlite3'
[root@localhost portbug]# rails s -b 0.0.0.0
=> Booting Puma
=> Rails 5.1.0 application starting in development on http://0.0.0.0:3000
=> Run `rails server -h` for more startup options
Puma starting in single mode...
* Version 3.8.2 (ruby 2.4.1-p111), codename: Sassy Salamander
* Min threads: 5, max threads: 5
* Environment: development
* Listening on tcp://0.0.0.0:9292
Use Ctrl-C to stop
```

### Expected behavior

Server should bind to port 3000.

### Actual behavior

Server binds to port 9292.  

If port 3000 is specified explicitly with -p, the server binds to the correct port.

### System configuration

Rails 5.1.0

Ruby 2.4.1

Fedora Server 25 with RVM

**Comment by rafaelfranca** [comment]
Thanks! Closing as dup of https://github.com/rails/rails/issues/28971
