### ISSUE TITLE
[Migration] Run db migrate failed with pgbouncer. (session mode)

### ISSUE THREAD

**Issue by zw963** [rails/rails#28985]
Please see followings links.

https://github.com/pgbouncer/pgbouncer/issues/201

Thanks

**Comment by rafaelfranca** [comment]
Are you able to reproduce it without pgbouncer?

**Comment by zw963** [comment]
@rafaelfranca , Can't.

I run pgbouncer+pg in same container, this container expose two port, 
5432 for pg, 6432 for pgbouncer.

Before switch to pgbouncer, migration work well for me, after switch to
pgbouncer(6432), It seem like work well too, until run a migration, I occur
this issue, after switch back to pg(5432), it worked well for me now.

BTW:  migration worked in my local development with same config pgbouncer.
I deploy with capistrano 3.7.2.

Ruby: 2.3.3
Rails: 5.0.2

**Comment by rafaelfranca** [comment]
I see. For what you described this doesn't seems to be a Rails problem. If it worked in development with the same config, and it also works without pgbouncer it is something in your production configuration.
