### ISSUE TITLE
Rails constant autoloading fails to load modules transitively.

### ISSUE THREAD

**Issue by mijoharas** [rails/rails#28997]
### Steps to reproduce

Run [this small self contained rails application](https://github.com/mijoharas/rails-dependency-autoloading-bug-ssce) keeping `config.eager_load = false`. Try to navigate to root path `/`. Observe error message:

```
NameError (uninitialized constant TestClass::ChildClass):
  
app/models/test_class.rb:4:in `foobar'
app/controllers/test_controller.rb:3:in `test'
```
See [README.md](https://github.com/mijoharas/rails-dependency-autoloading-bug-ssce/blob/master/README.md) for a short explanation of what's going on.

### Expected behavior
When run with `config.eager_load = true` there is no error message and the page is displayed.

### Actual behavior
Constant autoloading has failed to load the transitively included class `TestClass`.

Explanation:

We have a class `TestClass` which includes a module `IncludeModule`. `IncludeModule` itself also includes a module called `ContainerModule` which contains a class `ChildClass`.

We simply want to access `ChildClass` from within `TestClass` to call a method on it. This does not seem to be allowed by rails constant autoloading.

### System configuration
**Rails version**: ruby 2.4.1p111 (2017-03-22 revision 58053) [x86_64-linux]

**Ruby version**: Rails 5.1.0

**Comment by pixeltrix** [comment]
I think the best we can do here is an entry in section 10 of the [Autoloading and Reloading Constants][1] guide. Since you don't have a `container_module.rb` file, Rails will synthesise a new module and then return that in response to `include ContainerModule`. The only way to fix it would be to try to eager load any constants underneath that namespace which defeats the purpose of `config.eager_load = false`. The workaround is to create a `container_module.rb` file which looks like this:

``` ruby
require_dependency 'container_module/child_class'
```

Using `require_dependency` will ensure that the constant is unloaded and reloaded properly in development mode.

[1]: http://guides.rubyonrails.org/autoloading_and_reloading_constants.html

**Comment by matthewd** [comment]
@pixeltrix this sounds like it could be a bug to me.

The `include` will use a synthetic module... but when we try to autoload `TestClass::ChildClass`, ISTM we should be trying for `ContainerModule::ChildClass` just as we would `BaseClass::ChildClass`. (Or am I very confused? I thought that would work, but looking at the code, can't see where it would happen.)

**Comment by pixeltrix** [comment]
@matthewd I may be wrong but I don't think we've ever walked the ancestor chain looking for autoloading matches - sounds doable though.

**Comment by mijoharas** [comment]
Hi @pixeltrix and @mathewd. I have a PR that fixes this issue. I think the code is simple enough to read, but do let me know if it's not clear.

**Comment by fxn** [comment]
That is right, the ancestor chain has been always ignored (as a particular case of constant autoloading not pretending to emulate Ruby constant resolution, because it cannot).

**Comment by mijoharas** [comment]
@fxn, I agree we can't fully replicate Ruby constant resolution, but is there any reason we shouldn't be allowed to load from the ancestor chain? Does my PR do anything it shouldn't?

**Comment by fxn** [comment]
@mijoharas can't dedicate time right now, but let me say something quick.

Constant autoloading in Rails is a map from constants to file names with support for "parents", which also map to a file system hierarchy. That is about it. Walking up the ancestor chain departs from this fundamental design principle, consequences have to be evaluated (or whether we want to depart at all).

I might write something more elaborate later, but @matthewd and @pixeltrix please feel free to take it over.

**Comment by mijoharas** [comment]
Thanks for taking the time.

@pixeltrix and @fxn let me know what more you want to know. I think I can make a pretty compelling argument for it's use (happy to expand on that, just ask). In terms of safety, the PR abstracts out the section where we map the files to the constant name, and simply checks the ancestor chain for similar files, but let me know if you want an explanation.

**Comment by mijoharas** [comment]
Hi, is there anything else needed for the PR to fix this? it works and has a benchmark showing that it doesn't slow things down (speeds things up if anything, but basically the same).

**Comment by fxn** [comment]
I am going to close this one.

The reason is the same one in https://github.com/rails/rails/pull/29773#issuecomment-325101995: dependencies.rb does not emulate Ruby, and does not attempt to.

If you try to get just a tad closer to Ruby you are going in the wrong direction in my view. It brings the expectation that's desirable or a goal. Emulating Ruby is not possible with `const_missing`, so better to clearly stay away from it. Otherwise, it will leak.

By keeping dependencies.rb as it is, we underscore the behavior explained in the autoloading guide is the contract you have to program against.

**Comment by mijoharas** [comment]
@fxn that's fair enough, and I understand the argument about not wanting to build a leaky abstraction, but I think the attached PR does emulate how ruby find constants with `const_missing` (it first checks the parents and then walks the ancestors chain while avoiding cycles, I also think the new code is easier to understand, and just as fast in all existing cases).

It's obviously up to you, and feel free to leave this closed if you think it's better, but let me try and describe why I think this is an advantageous change (example is made up, but hopefully illustrates the need for this kind of thing).

Say you have a large rails application that can send messages to a messaging system. Inside your app directory you have something like this:

```
<normal_rails_stuff>
├── messaging_system
│   ├── message_helper.rb
│   ├── helpers
│   │       ├── message_builder.rb
│   │       ├── message_writing_helper.rb
│   │       ├── message_reading_helper.rb
```

Now lots of different models might need to send some sort of messages as part of their normal operation, message sending is a cross-cutting concern, but you want to keep it nice and organised, so you have a nice little helper module `message_helper.rb` which you include in any class that might need to send messages. Now this module helpfully includes `messaging_system/helpers` so that in any of the other classes you can use `message_builder.rb` class to build your messages and you may need some of the other `message_*_helper.rb` classes.

So with the attached PR this will work fine. You include your `message_helper.rb` class and then you can find any of the other helpers that you want to be included. Remember, these are cross cutting concerns so could be used in most other parts of the codebase. Without this, every time you want to use a helper you need to either not use rails auto-loading, or fully qualify your helper as `MessagingSystem::Helpers::MessageBuilder`, this adds quite a bit of friction.

The example I used is cut down, there can be more nesting, but there isn't a nice solution for encapsulating this stuff in rails, while there is in ruby and it makes for nicer more expressive code.

So that's why I think the PR attached to this should be merged. Sorry for the long post. In essence I think modules can greatly simplify the organisation of code, and not auto-loading things based on modules means we cannot really use any of those advantages in rails development.

Let me know what you think, even if it's just a "Sorry, no" response.

**Comment by fxn** [comment]
For the archives, Zeitwerk supports this use case, see [this test suite](https://github.com/fxn/zeitwerk/blob/main/test/lib/zeitwerk/test_ancestors.rb).
