### ISSUE TITLE
Enhancement - rails_ujs node module doesn't fire without additional code

### ISSUE THREAD

**Issue by djforth** [rails/rails#28992]
### Steps to reproduce

If you add the module via yarn (or npm) - https://www.npmjs.com/package/rails-ujs and them run import 'rails-ujs'; it doesn't fire the the rails-ujs properly. After digging around in the source I realised because of the way your running the module.exports method you need to do the following:

```javascript
import Rails from 'rails-ujs';
if(Rails.fire(document, 'rails:attachBindings')){
  Rails.start();
}
```

While this isn't a massive problem it took a little bit of figuring out why it wasn't trigger.  My suggestion is either to tweak your js code so:

```javascript
if (typeof module === "object" && module.exports) {
    module.exports = Rails;
  } else if (typeof define === "function" && define.amd) {
    define(Rails);
  }
```

should become:

```javascript
if (typeof module === "object" && module.exports) {
    module.exports = ()=>{
        if(Rails.fire(document, 'rails:attachBindings')){
          Rails.start();
        }
        return Rails;
    }
  } else if (typeof define === "function" && define.amd) {
    define(Rails);
  }
```
Then you could just call to start it:

```javascript
import Rails from 'rails-ujs';
const ujs =  Rails();
```

Alternatively it might be worth updating the readme for module so if someone wants to use rails-ujs through webpack it's clear what you need to do?

Happy to issue a pull request on the JS updates if you want me too.

**Comment by rafaelfranca** [comment]
Yeah, please send a PR.

**Comment by djforth** [comment]
Ok great will do!

**Comment by maclover7** [comment]
cc @javan

**Comment by vesan** [comment]
I would prefer to have it work like turbolinks: https://github.com/turbolinks/turbolinks#installation-using-npm

That's how we currently use it in our projects that load JS using webpacker.

**Comment by javan** [comment]
> I would prefer to have it work like turbolinks

That's how I intended for it work (call `Rails.start()` when using as a package).

@djforth, so I'm clear, is the issue that you need to call `Rails.fire(document, 'rails:attachBindings')` too?

**Comment by javan** [comment]
> I can't see anything obvious and the output doesn't seem to add the module.exports or umd code?

That's handled by [sprockets-export](https://github.com/javan/sprockets-export) via [this directive](https://github.com/rails/rails/blob/11341fdb3a1664ba58edf729ed46e04cd0e20ed6/actionview/app/assets/javascripts/rails-ujs.coffee#L2) (`#= export Rails`).

**Comment by javan** [comment]
From what I can tell, `Rails.fire(document, 'rails:attachBindings')` is only [used as a hook for the test suite](https://github.com/rails/rails/blob/11341fdb3a1664ba58edf729ed46e04cd0e20ed6/actionview/test/ujs/views/layouts/application.html.erb#L10) so that part isn't necessary. 

The issue is that the need to call `Rails.start()` when importing `rails-ujs` as a module isn't documented. Sorry about that! Please do open a PR with documentation if you'd like. The Turbolinks docs are a good example.

**Comment by vesan** [comment]
@djforth Want to do the documentation improvement?

**Comment by djforth** [comment]
Ok @javan & @vesan will update docs then no problem. Will get the pull request up Mon when I'm back in front of a machine.

**Comment by rafaelfranca** [comment]
Thanks!
