### ISSUE TITLE
rails webpacker:install and rails new . --webpack does nothing

### ISSUE THREAD

**Issue by DivXZero** [rails/rails#29007]
### Steps to reproduce

Run the following command inside an existing directory (this method is used with setting up an environment in docker)
```bash
$ rails new . --force --webpack
```

### Expected behavior
Command rails webpacker:install should do something.

### Actual behavior
gem 'webpacker' is added to Gemfile, nothing else happens. No error output, no files generated or modified.

### System configuration
**Rails version**: 5.1
**Ruby version**: 2.4.1
**Node version**: 4.8.3
**Yarn version**: 0.23.4

**Comment by maclover7** [comment]
cc @gauravtiwari @dhh

**Comment by gauravtiwari** [comment]
@DivXZero Your node version is < 6.4. Just did a fresh app using node > 6.4 and it works fine. @maclover7 This is related to what we have been discussing in https://github.com/rails/rails/pull/28929

**Comment by gauravtiwari** [comment]
@DivXZero You should be getting this error message though - 

![screen shot 2017-05-07 at 20 41 39](https://cloud.githubusercontent.com/assets/771039/25784473/a1f6e7c6-3365-11e7-938e-5fc1b965cdb1.png)

**Comment by DivXZero** [comment]
The error I initially received was that yarn required node >= 4.x or < 5 when installing via npm (I was using 5.0.0) so I downgraded, and then received no output at all. I bumped node up to v6.5 and everything seems to be working as expected. Thank you!
