### ISSUE TITLE
MissingAttributeError goes away after save

### ISSUE THREAD

**Issue by willbryant** [rails/rails#29017]
### Steps to reproduce

Take a record from a scope that uses `select` to load only some columns.

If you try to reference once of the other columns that you didn't load, you will get a MissingAttributeError.

But if you first `save` or `save!` the record, you get `nil` instead of an error.

### Expected behavior
You should continue to get `MissingAttributeError` after `save`.

### Actual behavior
You get a nil from the attribute reader.

### System configuration
**Rails version**:
5.0.2 and 5.1.0

**Ruby version**:
2.3.1

This is because dirty.rb uses `@attributes = @attributes.map(&:forgetting_assignment)` which converts the `Attribute::Uninitialized` to an `Attribute::FromDatabase`.

**Comment by alexcameron89** [comment]
[Here](https://gist.github.com/1a38ffbf07e4656e567f9f42c09c6324) is a script reproducing the issue.
