### ISSUE TITLE
url_for() produces path with double namespace

### ISSUE THREAD

**Issue by cristian-rivera** [rails/rails#29019]
I have routes defined like this:

```
 namespace :dealer, path: '' do
   resources :images, except: :index do
     resources :comments, only: [:create, :destroy] do
       resources :attachments, only: :show
     end
   end
 end
```

In my view using `link_to [@image, @comment]` results in a url named:

`dealer_image_dealer_comment_path` which doesn't exist. It should be `dealer_image_comment_path`. Any way to avoid the double namespace?

I'm receiving this error:

```
undefined method `dealer_image_dealer_comment_path' for #<#<Class:0x007fb599499520>:0x007fb5994980d0>
Did you mean?  dealer_image_comments_path
               dealer_image_comment_path
```

rake routes:

```
dealer_image_comments POST      /images/:image_id/comments(.:format)                                                                   dealer/comments#create {:subdomain=>"dealer"}
dealer_image_comment DELETE    /images/:image_id/comments/:id(.:format) 
```

**Rails version**: 5.0.2

**Ruby version**: 2.4.0

**Comment by alexcameron89** [comment]
Hey @cristian-rivera, can you provide us with a minimal Rails application so we can reproduce the issue you are seeing?

**Comment by cristian-rivera** [comment]
Hey @alexcameron89, here is the link to a test repo I setup [https://github.com/cristian-rivera/Example](url) just run `rails s` and navigate to `http://lvh.me:3000/dealer/images/1/comments/new`!

**Comment by pixeltrix** [comment]
@cristian-rivera are you using namespaces for your models, e.g. `Dealer::Image` and `Dealer::Comment` ? If so this is a limitation of the way `polymorphic_url` works. It effectively guesses the url helper name based on the model name and namespaces can cause it to go wrong.
