### ISSUE TITLE
ActiveRecord [5.1] container operator (@>) behavior not consistant.

### ISSUE THREAD

**Issue by zw963** [rails/rails#29016]
Postgres version: 9.5.5
ActiveRecord version: 5.1

In SearchKeyword table: exists a `groups` field

```rb
add_column :search_keywords, :groups, :string, array: true, default: []
add_index :serach_keywords, :groups, using: :gin
```

I invoke following SQL query, which seem like work well in earlier
ActiveRecord version and postgres version (don't remember which version)

But current got following errors:

```sh
(pry):0> SearchKeyword.where(" @> array[?]", ["group1"])
(pry) output error: #<ActiveRecord::StatementInvalid: PG::UndefinedFunction: ERROR:  operator does not exist: character varying[] @> text[]
LINE 1: ..._keywords".* FROM "search_keywords" WHERE (groups @> array['...
                                                             ^
HINT:  No operator matches the given name and argument type(s). You might need to add explicit type casts.
: SELECT "search_keywords".* FROM "search_keywords" WHERE (groups @> array['group1'])>
```

we have to change those code to:

```sh
(pry):0> SearchKeyword.where("groups @> array[?]::varchar[]", ["SurplusGoodsItem"]).explain
EXPLAIN for: SELECT "search_keywords".* FROM "search_keywords" WHERE (groups @> array['SurplusGoodsItem']::varchar[])
                                          QUERY PLAN
-----------------------------------------------------------------------------------------------
 Bitmap Heap Scan on search_keywords  (cost=12.01..17.36 rows=2 width=188)
   Recheck Cond: (groups @> '{SurplusGoodsItem}'::character varying[])
   ->  Bitmap Index Scan on index_search_keywords_on_groups  (cost=0.00..12.01 rows=2 width=0)
         Index Cond: (groups @> '{SurplusGoodsItem}'::character varying[])
(4 rows)
```

**Comment by matthewd** [comment]
> `operator does not exist: character varying[] @> text[]`

That sounds like a PostgreSQL matter. Perhaps when it previously worked, your column's type was `text[]` instead.

**Comment by zw963** [comment]
> That sounds like a PostgreSQL matter. Perhaps when it previously worked, your column's type was text[] instead.

@matthewd, No, I think i never use text type in array fields, I only use one type, `:string` anywhy ....

maybe the problem is:  

Current 5.1 version migrate ``array: true`` generate a pg varying[] type fields like this:

```sql
CREATE TABLE recommended_keywords (
    groups character varying[]
);
```

But in older version, genereate pg text[] type fields like this??

```sql
CREATE TABLE recommended_keywords (
    groups character text[]
);
```

**Comment by zw963** [comment]
Accroding [this](http://stackoverflow.com/a/36806014/749774) answer from SO ,  text almost same performance as varchar, why not just generate a array use text[] to make write SQL more simple?

anywhy, I thinks this is the issue ...
