### ISSUE TITLE
AR::Base#save doesn't assert valid keys

### ISSUE THREAD

**Issue by dnl** [rails/rails#29011]
### Steps to reproduce
`save` doesn't use `assert_valid_keys`, so a typo of `save(validate: false)`, such as `save(validates: false)` will work unexpectedly.

### Expected behavior
`.save(validates: false)` raises `ArgumentError: Unknown key: :validates. Valid keys are: :validate, :touch`
or
`.save(validates: false)` raises `ArgumentError: unknown keyword: validates`
### Actual behavior
`.save(validates: false)` silently acts like `.save()` because `:validates` does nothing.

### System configuration
**Rails version**: 5.0.1
**Ruby version**: 2.3.1

because save is redefined so many times It wasn't a straightforward PR, but I can have a go if you agree this should be an ArgumentError

**Comment by RupeeOnRails** [comment]
Confirmed. Here's a [test case](https://gist.github.com/RupeeOnRails/be2025ac340ff95c19cef92dfbcc7ffa) for it.
