### ISSUE TITLE
Eager loading on empty?

### ISSUE THREAD

**Issue by kaluznyo** [rails/rails#29025]
Since Rails 5.1, this followed line make an eager loading for empty?.
`
comments = SupplierComment.where("DATE(created_at) = ?", Date.yesterday).includes(:supplier)
comments.empty?
`

For the first line, the SQL generated is : 
`SELECT  `supplier_comments`.* FROM `supplier_comments` WHERE (DATE(created_at) = '2017-05-09') ORDER BY supplier_comments.created_at DESC LIMIT 11
`

For the second the SQL is : 

` SELECT  `supplier_comments`.* FROM `supplier_comments` LEFT OUTER JOIN `suppliers` ON `suppliers`.`id` = `supplier_comments`.`supplier_id` WHERE (DATE(created_at) = '2017-05-09') ORDER BY supplier_comments.created_at DESC`

In my code this cause an ambiguous request because of created_at on the two table.
In Rails 5.0, not LEFT OUTER JOIN was made.

I suspect this commit https://github.com/rails/rails/commit/02da8aea832485044fde1b94c021a66d37d54dec

The empty? method was redefine, with support of no eager loading, but seems to not work fine ?

I use Rails 5.1.0 and Ruby 2.4.0

**Comment by alexcameron89** [comment]
Hey @kaluznyo, can you create an executable test script using one of the templates [here](https://github.com/rails/rails/tree/master/guides/bug_report_templates) to demonstrate the problem you are seeing?

**Comment by kaluznyo** [comment]
Yep, https://gist.github.com/kaluznyo/bdba8fd36a4112741596a90bcada1570. Fail in 5.1.0, pass in 5.0.2

**Comment by alexcameron89** [comment]
Thanks, and you are correct on the commit that introduced this behavior, 02da8ae.
