### ISSUE TITLE
Please release minitest fix

### ISSUE THREAD

**Issue by zenspider** [rails/rails#29038]
Can you please push a release with #29022 [fixed] in it to whatever versions are affected by this bug? (and what are they?)

**Comment by simi** [comment]
#362 (request for 'from_to' method to be added to array/acces.rb) ?

**Comment by tenderlove** [comment]
I can take care of it tomorrow.

**Comment by zenspider** [comment]
@simi UGH. Now I _know_ I need more coffee. Fixed. Thanks for pointing it out.

**Comment by LeBenLeBen** [comment]
Rails 5.0.3 and 5.1.1 where released with the fix. This issue can probably be closed.
