### ISSUE TITLE
ActionController::Parameters#delete does use default value

### ISSUE THREAD

**Issue by JasonBarnabe** [rails/rails#29037]
http://api.rubyonrails.org/classes/ActionController/Parameters.html#method-i-delete

> Deletes and returns a key-value pair from Parameters whose key is equal to key. If the key is not found, returns the default value. If the optional code block is given and the key is not found, pass in the key and return the result of block.

Rails 4.2.8
```ruby
> ActionController::Parameters.new.delete('foo') { 'default' }
=> "default"
```

Rails 5.0.2
```ruby
> ActionController::Parameters.new.delete('foo') { 'default' }
=> nil
```

Rails 5.1.0
```ruby
> ActionController::Parameters.new.delete('foo') { 'default' }
=> nil
```

I found [this commit](https://github.com/rails/rails/commit/dbf67b3a6f549769c5f581b70bc0c0d880d5d5d1), not sure if this is an intentional change. If so, the comment should be updated.

**Comment by eugeneius** [comment]
This regressed in https://github.com/rails/rails/pull/20868; we went from calling `super`, which propagates the block, to calling `@parameters.delete(key)`, which doesn't.

https://github.com/rails/rails/commit/dbf67b3a6f549769c5f581b70bc0c0d880d5d5d1 later removed the `&block` parameter, but at that point it wasn't doing anything.

I've opened https://github.com/rails/rails/pull/29040 with a fix.
