### ISSUE TITLE
Bring back before_filter and friends as aliases

### ISSUE THREAD

**Issue by dhh** [rails/rails#29030]
We deprecated `before_filter` and friends in favor of `before_action`. That's a win for new applications, but it's an undue burden for gem engines and people who use them. While you can easily upgrade your own app, it's a lot harder to just upgrade every dependency you rely on.

And that's just not a proportionate amount of pain to inflict on the ecosystem given the light weight of a few aliases.

So let's bring back `before_filter` and friends as documented, historical aliases to soothe the pain.

Mea culpa!

**Comment by nynhex** [comment]
This is extremely helpful, great suggestion!

**Comment by simi** [comment]
I'll try to submit PR.

**Comment by derekprior** [comment]
This will need to be backported to 5.0.x as well if we want to save engine maintainers from [this mess](https://github.com/thoughtbot/clearance/blob/master/app/controllers/clearance/sessions_controller.rb#L2-L18). 

Even still, as an engine maintainer I don't think I'd have a way to specify that if you're using 5.0.x it must be a certain patch level.

The horse may have left the barn here.

**Comment by dhh** [comment]
Lots of gems will not have updated to such a splitter, so hopefully we'll
at least save some of the people some of the time.

**Comment by rafaelfranca** [comment]
Given that 4.2 is now officially unsupported, should we care about this? At this point gem/engines should be dropping support to 4.2.

**Comment by dhh** [comment]
It's unsupported but that doesn't mean people will stop using it right away. I don't think the weight of these aliases warranted the pain associated with removing them.

**Comment by simi** [comment]
Is this about to revert https://github.com/rails/rails/commit/d7be30e8babf5e37a891522869e7b0191b79b757, remove deprecation messages and mention that in docs?

**Comment by sikachu** [comment]
I think the ship has sailed. Maintainers who made their gem to support both 4.2 and 5.0 (and now 5.1) would still have to have this splitter in their app.

I think the better solution might be creating a shim gem instead. Going forward, the idea is that if they drop 4.2 support they could then just remove this gem without having to change anything else. Would that be a better compromise?

**Comment by dhh** [comment]
Josef, yes.

Prem, I don't think so. Lots of people who have not upgraded to 5.1, where
these disappeared. And 5.1 has only been out for a short time. We can
lessen the hit by reverting this in a tiny release. Don't think the weight
of this warrants a gem.

On Thu, May 11, 2017 at 2:46 AM, Prem Sichanugrist <notifications@github.com

**Comment by chrisarcand** [comment]
As a maintainer who's done the before_filter replacement song and dance on 4-5 different gems I certainly agree the ship has sailed/horse out of the barn/some other silly idiom.

I think it might have made sense with the first patch release of 5.0 but as 5.1 is now out and 4.2 support has dropped anyway (as @rafaelfranca mentions), reintroducing methods which have been removed for almost a year and half seems more confusing than anything else. I do respect trying to minimize gem maintainers' effort but I just think it's past time at this point. *shrug*

**Comment by dhh** [comment]
Oh, we dropped this in 5.0? Then I'm mistaken. I through we warned in 5.0
and dropped in 5.1. Yes, if this was dropped in 5.0, then I agree the ship
has sailed.

**Comment by kaspth** [comment]
Deprecated in 5.0 http://edgeguides.rubyonrails.org/5_0_release_notes.html#action-pack-deprecations (https://github.com/rails/rails/pull/18410) and gone for 5.1.

Though I think resurrecting them now is a waste. Why would gems with 5.0 support ship with deprecation warnings?

If we're looking for high pain point upgrades for little gain, the deprecation of positional args in controller and integration tests would be my pick — especially for the documentation-deprecated controller tests.

**Comment by derekprior** [comment]
> I through we warned in 5.0 and dropped in 5.1

A warning is as good as removed in my gem maintainer view.

I'd *maybe* use these if they were re-added. As was pointed out to me, I could update my gemspec to say: `spec.add_runtime_dependency 'rails', '>= 3.1', '!= 5.0.0', '!= 5.0.0.1', '!= 5.0.1', '!= 5.0.2'`. That is a little weird though. This also ignores `rc` releases of those versions, but I think that's probably fine. You shouldn't be running old release candidates in production.

Either way this ends up, I support the line of thinking that resulted in this issue being created.
