### ISSUE TITLE
Multiple calls to validate with same symbol will overwrite it

### ISSUE THREAD

**Issue by runephilosof** [rails/rails#29048]
It would be useful to be able to call validate with the same symbol multiple times.
This could be used when you have multiple blocks of `with_options if: -> { some_condition }` grouping some validations.

### Steps to reproduce
```
class MyModel
  include ActiveModel::Model   
  validate :validate_me, if: -> { true }
  validate :validate_me, if: -> { false }
end                     
Dbd.new.valid? # returns true
```

### Expected behavior
`NoMethodError: undefined method `validate_me' for #<MyModel:0x00557688c5bdf0>` since I didn't define that method.

### Actual behavior
The second `validate :validate_me` call overwrites the first one.
So it returns `true`

### System configuration
**Rails version**:
5.1

**Ruby version**:
2.3.4

**Comment by meinac** [comment]
What is the reason behind of defining same validation twice with different conditions? We can merge them into one condition with `or`, can't we?

**Comment by runephilosof** [comment]
That might be the decision. But then that should be documented.

**Comment by runephilosof** [comment]
I mean the documentation of [validate](http://api.rubyonrails.org/classes/ActiveModel/Validations/ClassMethods.html#method-i-validate) doesn't mention what happens if you call it twice with the same symbol.

**Comment by meinac** [comment]
Actually it is documented for callbacks [here](http://api.rubyonrails.org/classes/ActiveSupport/Callbacks/ClassMethods.html#method-i-define_callbacks). Maybe it's a nice idea to add this documentation for validations as well but then we also need to add this documentation for all callback related stuff.

**Comment by pixeltrix** [comment]
If you're going to do the documentation for `validate` then you should also do the documentation for controller callbacks as they're also subject to the same limitation.

**Comment by meinac** [comment]
@pixeltrix what you say is just **subset** of what I have already mentioned by saying `we also need to add this documentation for all callback related stuff`, isn't it or am I missing something? For example we also need to document all callbacks like `before_save` or Active Job callbacks etc., it will be too verbose though.

**Comment by pixeltrix** [comment]
@meinac ah sorry, my fault. I think I stopped parsing the sentence once I read validations - I blame it on my age and failing eyesight.

**Comment by meinac** [comment]
@pixeltrix no worries, I'm asking because the opened pr only covers validate and Action Controller callbacks, shall we extend other callback documentations in that pr too?

**Comment by pixeltrix** [comment]
@meinac yes, but I think it needs to be a note at the beginning of `ActiveModel::Callbacks`, `ActiveJob::Callbacks`, etc. not on every method.

**Comment by 3limin4t0r** [comment]
I walked upon this issue while working on address geolocating.

Let me provide the a code sample of my use case scenario. In this scenario I want to fetch geo data based on the address. When the _lat_ or _lng_ attribute is absent during creation geo data is fetched. When updating an address this is only done if _lat_ and _lng_ attributes are both unchanged, and the address itself contains a change.

```ruby
class Address < ApplicationRecord

  validate :geocode_address, on: :create, if: -> { !lat || !lng }
  validate :geocode_address, on: :update, if: -> { !lat_changed? && !lng_changed? && address_changed? }

  def address_changed?
    street_changed?                ||
      house_number_changed?        ||
      house_number_suffix_changed? ||
      zip_changed?                 ||
      place_changed?               ||
      country_changed?
  end

  def to_s
    "#{street} #{house_number}#{house_number_suffix}, #{zip}, #{place}, #{country}"
  end

  def geocode_address
    geo_resp = GeoKit::Geocoders::GoogleGeocoder.geocode(self.to_s)

    if geo_resp.success
      self.lat = geo_resp.lat
      self.lng = geo_resp.lng
    else
      errors.add(:base, :unlocatable)
    end

    self
  end

end
```

The above code does not work due the issue that you  can't use the same symbol twice and I had to rewrite the validation to:

```ruby
validate(on: :create, if: -> { !lat || !lng }) { geocode_address }
validate(on: :update, if: -> { !lat_changed? && !lng_changed? && address_changed? }) { geocode_address }
```

@meinac - The documentation you refer to is for defining callbacks. From my outside point of view this is not the same as using the _validate_ class method. I consider _validate_ to be equal to _set_callback_ and that method does not provide a note or warning when using the same name twice.

Example:

```ruby
validate :geocode_address, on: :create, if: -> { !lat || !lng }

# Would equal something along the lines of:

set_callback :validate, :geocode_address, if: [
  -> { !([:create] & Array(validation_context)).empty? }, 
  -> { !lat || !lng }
]
```

**Comment by dkniffin** [comment]
Another use case this would solve is the ability to do multi-level nesting of `with_options`:

```ruby
with_options if: :condition_1? 
  with_options if: :condition_2? do
    validate :validation_1
    validate :validation_2
    validate :validation_3
  end

  with_options if: :condition_3? do
    validate :validation_4
    validate :validation_5
    validate :validation_6
  end

  with_options if: :condition_4? do
    validate :validation_7
    validate :validation_8
    validate :validation_9
  end
end
```

Right now, to avoid the `condition_1?` check getting clobbered, you have to write it like this

```ruby
with_options if: -> { condition_1? && condition_2? } do
  validate :validation_1
  validate :validation_2
  validate :validation_3
end

with_options if: -> { condition_1? && condition_3? } do
  validate :validation_4
  validate :validation_5
  validate :validation_6
end

with_options if: -> { condition_1? && condition_4? } do
  validate :validation_7
  validate :validation_8
  validate :validation_9
end
```

**Comment by mpkhr** [comment]
Just ran into the same issue. In this case it's not even about readability, but simply very unexpected behavior:

```
with_options if: -> { admin? } do |admin|
  admin.validates :some_date, comparison: { greater_than_or_equal_to: :other_date },
    allow_nil: true, if: -> { other_date.present? }
end
```

The expected behavior would be that the scoped validation is only for admins and the logic within that scope is added on-top.

My work around for now is to repeat the condition, which is not DRY and error-prone

```
with_options if: -> { admin? } do |admin|
  admin.validates :some_date, comparison: { greater_than_or_equal_to: :other_date },
    allow_nil: true, if: -> { admin? && other_date.present? }
end
```
