### ISSUE TITLE
More info on previous_changes deprecation message.

### ISSUE THREAD

**Issue by MidnightWonderer** [rails/rails#29047]
Now when I try to use previous_changes in after_save callback I am greeted with
```md
DEPRECATION WARNING: The behavior of `previous_changes` inside of after callbacks is
deprecated without replacement. In the next release of Rails,
this method inside of `after_save` will return the changes that
were just saved.
```
I think the url to the original thread should also puts there inside the deprecation message.  
Here the original discussion thread: https://github.com/rails/rails/pull/25337  
  
Or I will never knows what's going on.  
This is not the first time the code references github thread.  
For instance:  
https://github.com/rails/rails/blob/92703a9ea5d8b96f30e0b706b801c9185ef14f0e/activerecord/lib/active_record/associations/join_dependency/join_part.rb#L50  
also reference to a pull request.

**Comment by rafaelfranca** [comment]
I agree the deprecation message should give actionable information but it can't point to github threads. Can you work on improving the message so users don't have to look for more information in the issue tracker?
