### ISSUE TITLE
Update Testing Your Mailers docs to say fixtures are not stubbed.

### ISSUE THREAD

**Issue by boykoc** [rails/rails#29051]
I think the documentation is incorrect based on the behavior shown below and my review of the code but am not sure if this is desired behavior to be included vs just updating the documentation.

### Steps to reproduce

rails g mailer User invite

### Expected behavior
Based on the current documentation for [Testing Your Mailers](http://edgeguides.rubyonrails.org/testing.html#testing-your-mailers), stub out `test/fixtures/UserMailer/invite.html.erb`

### Actual behavior
No fixtures are stubbed. Only `test/mailers/*` are created in the test directory.

### System configuration
**Rails version**: master and 4.2.8

### Test case
Add the following test to `/rails/railties/test/generators/mailer_generator_test.rb`.

```
def test_stubs_fixtures
  assert_directory "test/fixtures/notifier_mailer"
end
```

**Comment by rafaelfranca** [comment]
Yeah, the documentation is incorrect and needs to be changed.

**Comment by rafaelfranca** [comment]
Yeah, the documentation is incorrect and needs to be changed. Could you open a PR?

**Comment by boykoc** [comment]
Thanks for confirming. I'll open a PR.
