### ISSUE TITLE
Broken links in Rails Guides ActiveSupport

### ISSUE THREAD

**Issue by juliusdelta** [rails/rails#29055]
It looks like currently the [Rails Guides ActiveSupport](http://guides.rubyonrails.org/active_support_core_extensions.html#stand-alone-active-support) page has broken links which are supposed to link to the methods used in the various examples.

Ex. http://guides.rubyonrails.org/active_support_core_extensions.html#blank-questionmark-and-present-questionmark The link to `active_support/core_ext/object/blank.rb.` returns a 404 from Github.

My understanding is that it's supposed to link to the ActiveSupport codebase with that method. 

Unless anyone has objections. I'll submit a PR for this in the coming hours.

**Comment by rafaelfranca** [comment]
Thank you for the issue. Yes, your understanding is correct, please send a PR.

**Comment by juliusdelta** [comment]
PR - #29056
