### ISSUE TITLE
How do I give Rails money?

### ISSUE THREAD

**Issue by thejonanshow** [rails/rails#29054]
Is there a donation link? I'm having trouble finding it.

Heroku hosted a giveaway at RailsConf that let people vote for an OSS project to receive a $500 donation and Rails won.

I have $500 on an AMEX card burning a hole in my pocket, somebody help me out?

**Comment by britnia** [comment]
I think the official procedure is you just send the money to @eileencodes 's bank account 😂

**Comment by jeremy** [comment]
Thanks Heroku and thanks to everyone who voted!!!

Please donate to the [Rails Girls Summer of Code](https://railsgirlssummerofcode.org/campaign/) on our behalf 💕
