### ISSUE TITLE
Action cable not working in test environent

### ISSUE THREAD

**Issue by massrb** [rails/rails#29061]
### Steps to reproduce

I am trying to figure out why action cable is not working in the test environment. I tried this:
 rails server --port 5200 -e test

 The error on the client side is: "WebSocket is closed before the connection is established"

(Guidelines for creating a bug report are [available
here](http://guides.rubyonrails.org/contributing_to_ruby_on_rails.html#creating-a-bug-report))

### Actual behavior

I see this in the test.log: 
WebSocket error occurred: undefined method `write_nonblock' for nil:NilClass"

I added a local stack trace by editing the gem source which shows this:

mydir/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/actioncable-5.1.0/lib/action_cable/connection/stream.rb:43:in `write'
mydir/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/actioncable-5.1.0/lib/action_cable/connection/client_socket.rb:73:in `write'
mydir/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/websocket-driver-0.6.5/lib/websocket/driver.rb:104:in `start'
mydir/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/actioncable-5.1.0/lib/action_cable/connection/client_socket.rb:64:in `start_driver'
mydir/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/actioncable-5.1.0/lib/action_cable/connection/client_socket.rb:68:in `rack_response'
mydir/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/actioncable-5.1.0/lib/action_cable/connection/web_socket.rb:32:in `rack_response'
mydir/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/actioncable-5.1.0/lib/action_cable/connection/base.rb:212:in `respond_to_successful_request'
mydir/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/actioncable-5.1.0/lib/action_cable/connection/base.rb:71:in `process'
mydir/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/actioncable-5.1.0/lib/action_cable/server/base.rb:28:in `call'
mydir/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/actionpack-5.1.0/lib/action_dispatch/routing/mapper.rb:17:in `block in <class:Constraints>'
mydir/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/actionpack-5.1.0/lib/action_dispatch/routing/mapper.rb:46:in `call'
mydir/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/actionpack-5.1.0/lib/action_dispatch/routing/mapper.rb:46:in `serve'
mydir/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/actionpack-5.1.0/lib/action_dispatch/journey/router.rb:46:in `block in serve'
mydir/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/actionpack-5.1.0/lib/action_dispatch/journey/router.rb:33:in `each'
mydir/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/actionpack-5.1.0/lib/action_dispatch/journey/router.rb:33:in `serve'
mydir/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/actionpack-5.1.0/lib/action_dispatch/routing/route_set.rb:832:in `call'
mydir/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/rack-cors-0.2.8/lib/rack/cors.rb:54:in `call'
mydir/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/rack-2.0.2/lib/rack/etag.rb:25:in `call'
mydir/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/rack-2.0.2/lib/rack/conditional_get.rb:25:in `call'
mydir/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/rack-2.0.2/lib/rack/head.rb:12:in `call'
mydir/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/rack-2.0.2/lib/rack/session/abstract/id.rb:232:in `context'
mydir/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/rack-2.0.2/lib/rack/session/abstract/id.rb:226:in `call'
mydir/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/actionpack-5.1.0/lib/action_dispatch/middleware/cookies.rb:613:in `call'
mydir/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/actionpack-5.1.0/lib/action_dispatch/middleware/callbacks.rb:26:in `block in call'
mydir/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/activesupport-5.1.0/lib/active_support/callbacks.rb:97:in `run_callbacks'
mydir/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/actionpack-5.1.0/lib/action_dispatch/middleware/callbacks.rb:24:in `call'
mydir/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/actionpack-5.1.0/lib/action_dispatch/middleware/debug_exceptions.rb:59:in `call'
mydir/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/actionpack-5.1.0/lib/action_dispatch/middleware/show_exceptions.rb:31:in `call'
mydir/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/railties-5.1.0/lib/rails/rack/logger.rb:36:in `call_app'
mydir/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/railties-5.1.0/lib/rails/rack/logger.rb:24:in `block in call'
mydir/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/activesupport-5.1.0/lib/active_support/tagged_logging.rb:69:in `block in tagged'
mydir/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/activesupport-5.1.0/lib/active_support/tagged_logging.rb:26:in `tagged'
mydir/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/activesupport-5.1.0/lib/active_support/tagged_logging.rb:69:in `tagged'
mydir/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/railties-5.1.0/lib/rails/rack/logger.rb:24:in `call'
mydir/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/actionpack-5.1.0/lib/action_dispatch/middleware/remote_ip.rb:79:in `call'
mydir/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/request_store-1.3.2/lib/request_store/middleware.rb:9:in `call'
mydir/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/actionpack-5.1.0/lib/action_dispatch/middleware/request_id.rb:25:in `call'
mydir/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/rack-2.0.2/lib/rack/method_override.rb:22:in `call'
mydir/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/rack-2.0.2/lib/rack/runtime.rb:22:in `call'
mydir/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/activesupport-5.1.0/lib/active_support/cache/strategy/local_cache_middleware.rb:27:in `call'
mydir/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/actionpack-5.1.0/lib/action_dispatch/middleware/executor.rb:12:in `call'
mydir/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/rack-2.0.2/lib/rack/lock.rb:15:in `call'
mydir/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/actionpack-5.1.0/lib/action_dispatch/middleware/static.rb:125:in `call'
mydir/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/rack-2.0.2/lib/rack/sendfile.rb:111:in `call'
mydir/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/railties-5.1.0/lib/rails/engine.rb:522:in `call'
mydir/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/puma-3.7.0/lib/puma/configuration.rb:226:in `call'
mydir/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/puma-3.7.0/lib/puma/server.rb:578:in `handle_request'
mydir/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/puma-3.7.0/lib/puma/server.rb:415:in `process_client'
mydir/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/puma-3.7.0/lib/puma/server.rb:275:in `block in run'
mydir/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/puma-3.7.0/lib/puma/thread_pool.rb:120:in `call'
mydir/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/puma-3.7.0/lib/puma/thread_pool.rb:120:in `block in spawn_thread'
mydir/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/actioncable-5.1.0/lib/action_cable/connection/stream.rb:43:in `write'
mydir/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/actioncable-5.1.0/lib/action_cable/connection/client_socket.rb:73:in `write'
mydir/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/websocket-driver-0.6.5/lib/websocket/driver/hybi.rb:228:in `send_frame'
mydir/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/websocket-driver-0.6.5/lib/websocket/driver/hybi.rb:191:in `frame'
mydir/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/websocket-driver-0.6.5/lib/websocket/driver.rb:111:in `text'
mydir/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/actioncable-5.1.0/lib/action_cable/connection/client_socket.rb:83:in `transmit'
mydir/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/actioncable-5.1.0/lib/action_cable/connection/web_socket.rb:20:in `transmit'
mydir/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/actioncable-5.1.0/lib/action_cable/connection/base.rb:92:in `transmit'
mydir/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/actioncable-5.1.0/lib/action_cable/connection/base.rb:193:in `send_welcome_message'
mydir/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/actioncable-5.1.0/lib/action_cable/connection/base.rb:170:in `handle_open'
mydir/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/actioncable-5.1.0/lib/action_cable/server/worker.rb:58:in `block in invoke'
mydir/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/actioncable-5.1.0/lib/action_cable/server/worker.rb:39:in `block in work'
mydir/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/activesupport-5.1.0/lib/active_support/callbacks.rb:108:in `block in run_callbacks'
mydir/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/actioncable-5.1.0/lib/action_cable/server/worker/active_record_connection_management.rb:14:in `block in with_database_connections'
mydir/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/actioncable-5.1.0/lib/action_cable/connection/tagged_logger_proxy.rb:22:in `block in tag'
mydir/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/activesupport-5.1.0/lib/active_support/tagged_logging.rb:69:in `block in tagged'
mydir/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/activesupport-5.1.0/lib/active_support/tagged_logging.rb:26:in `tagged'
mydir/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/activesupport-5.1.0/lib/active_support/tagged_logging.rb:69:in `tagged'
mydir/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/actioncable-5.1.0/lib/action_cable/connection/tagged_logger_proxy.rb:22:in `tag'
mydir/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/actioncable-5.1.0/lib/action_cable/server/worker/active_record_connection_management.rb:14:in `with_database_connections'
mydir/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/activesupport-5.1.0/lib/active_support/callbacks.rb:117:in `block in run_callbacks'
mydir/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/actioncable-5.1.0/lib/action_cable/engine.rb:60:in `call'
mydir/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/actioncable-5.1.0/lib/action_cable/engine.rb:60:in `block (4 levels) in <class:Engine>'
mydir/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/activesupport-5.1.0/lib/active_support/execution_wrapper.rb:85:in `wrap'
mydir/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/actioncable-5.1.0/lib/action_cable/engine.rb:55:in `block (3 levels) in <class:Engine>'
mydir/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/activesupport-5.1.0/lib/active_support/callbacks.rb:117:in `instance_exec'
mydir/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/activesupport-5.1.0/lib/active_support/callbacks.rb:117:in `block in run_callbacks'
mydir/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/activesupport-5.1.0/lib/active_support/callbacks.rb:135:in `call'
mydir/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/activesupport-5.1.0/lib/active_support/callbacks.rb:135:in `run_callbacks'
mydir/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/actioncable-5.1.0/lib/action_cable/server/worker.rb:38:in `work'
mydir/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/actioncable-5.1.0/lib/action_cable/server/worker.rb:56:in `invoke'
mydir/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/actioncable-5.1.0/lib/action_cable/server/worker.rb:51:in `block in async_invoke'
mydir/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:348:in `call'
mydir/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:348:in `run_task'
mydir/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:337:in `block (3 levels) in create_worker'
mydir/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:320:in `loop'
mydir/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:320:in `block (2 levels) in create_worker'
mydir/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:319:in `catch'
mydir/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:319:in `block in create_worker'
^CExiting

### System configuration
**Rails version**:

5.1.0

**Ruby version**:

ruby 2.2.2p95

**Comment by matthewd** [comment]
Please use the mailing list or StackOverflow for questions/help, where a wider community will be able to help you. We reserve the issues tracker for issues only.

**Comment by brunowego** [comment]
@massrb same here. If you found the solution, please share here.

**Comment by Uysim** [comment]
Anyone know how to fix it? It happen to me in production
