### ISSUE TITLE
Server-generated JS is not executed by rails-ujs on IE9.

### ISSUE THREAD

**Issue by inopinatus** [rails/rails#29069]
Not sure of IE9 support status re. rails-ujs, but unfortunately a tiny fraction of our users are still IE9. So:

### Steps to reproduce

Using IE9, submit a `remote: true` link, that gets a server-generated JavaScript response.

### Expected behavior

rails-ujs should execute the JS received.

### Actual behavior

rails-ujs does not execute the JS received, I think because it is using `xhr.response`, which was not in XMLHttpRequest Level 1.
Perhaps consider using `xhr.responseText` if `xhr.response` is `null`?

### System configuration
**Rails version**: 5.1

**Ruby version**: 2.3.4p301

**Comment by guilleiguaran** [comment]
@inopinatus I think the proposed solution is good, can you send a pull request applying it?

**Comment by guilleiguaran** [comment]
About IE9 support status re. rails-ujs: it should be supported

**Comment by inopinatus** [comment]
I am not even going to start trying to make the rails-ujs test suite pass on IE9. I took a look, and it was a sea of red.

The attached PR makes my simple test at https://github.com/inopinatus/ujs-test-app work in IE9.

**Comment by liudangyi** [comment]
FYI, you may want to take a look at liudangyi/jquery-ujs#1.

**Comment by y-yagi** [comment]
Fixed by #29108
