### ISSUE TITLE
Configuration not read properly

### ISSUE THREAD

**Issue by hadmut** [rails/rails#29066]
### Steps to reproduce

Fresh setup with rails, simple model created, using postgres database, rails 5.1.0, activerecord 5.1.1.

config/database.yml:

...
development:
  <<: *default
  database: inventar_dev
  port: 5456
...

Note the different port. 

This works with bin/rails server and rake db:migrate. both commands use the specified port number. 

but commands like 
rake db:reset
rake db:drop
rake db:create

fail and complain, that the connection to port 5432 (the default port of postgres) is not possible. some commands read and some ignore the port clause. 

### Expected behavior
all commands should use the specified port

### Actual behavior
some commands, i.e. 
rake db:reset
rake db:drop
rake db:create

ignore the port and thus cannot connect to the configured database. (while others do work)

### System configuration
**Rails version**:
5.1.0

**Ruby version**:
2.3.1

**Comment by robin850** [comment]
Hello @hadmut,

Actually these commands will run both for the `development` and `test` environments. Did you set the port to 5456 for the `test` environment as well ?

**Comment by hadmut** [comment]
Hi Robin,

Yeah, looks as if this was the problem. I used a postgres docker image for developing, and the docker image provides only one database at a time. I do not use testing _while_ developing (i.e. I'm testing in my development database). That's why I had set the port only for developing.

Is it really wise to have commands like db:reset db:create and db:crop , which are mainly used during development, to be bound to a second testing database?

regards

**Comment by robin850** [comment]
Actually yes, that's a feature because when you are developing, most of the time, you are writing tests along the process (or even before if you are following TDD). This would be pretty annoying to have to type the command two times because the test environment mostly replicates the development one.

I'm giving this a close but thanks for reporting anyway ! :-)
