### ISSUE TITLE
enable_extension regression in 5.1?

### ISSUE THREAD

**Issue by mockdeep** [rails/rails#29080]
### Steps to reproduce

When upgrading from Rails 5.0 to 5.1, it seems that there is a regression with `enable_extension`. I have in my schema the line:

```ruby
enable_extension "intarray"
```

### Expected behavior

This should enable the `intarray` extension for Postgres, which includes adding an `idx` function.

### Actual behavior

When I run `rake db:reset` it runs as expected, but then when I try to make use of the `intarray` extension, I see an error:

```
ActiveRecord::StatementInvalid - PG::UndefinedFunction: ERROR:  function idx(integer[], bigint) does not exist
```

If I revert to Rails 5.1 and run `rake db:reset`, the `intarray` extension works.

### System configuration
**Rails version**: 5.1

**Ruby version**: 2.3.3

**Comment by mockdeep** [comment]
It looks like the `bigint` is relevant. I changed my query to cast the column to `int` and it works now, from:

```ruby
where(id: ids).update_all(['position = idx(array[?], id)', ids])
```

to:

```ruby
where(id: ids).update_all(['position = idx(array[?], id::int)', ids])
```

Does that count as being a bug in AR or dependencies?

**Comment by maclover7** [comment]
@mockdeep Thank you for opening up this issue! It seems like we may need to add a bigger note to the upgrading guide / release notes about the int --> bigint change, since that's what breaking your code. IMHO, I'd say it's more of a documentation issue than a regression.
