### ISSUE TITLE
Clarify ActiveSupport String#first and String#last behavior for negative limit value

### ISSUE THREAD

**Issue by etdev** [rails/rails#29106]
### Steps to reproduce

1. Create a string
```ruby
str = "hello"
```
2. Use the ActiveSupport `first` and `last` methods with a negative limit:
```ruby
str.first(-1)
# => "hell"
str.last(-2)
# => "llo"
```

### Expected behavior

Personally I'd expect it to return a blank string or possibly raise an `ArgumentError`.

### Actual behavior

`first` returns the characters at indices up to the limit (non-inclusive)
`last` returns the characters from (limit - 1) to the end of the string.

This behavior appears to be [untested and undocumented](https://github.com/rails/rails/blob/master/activesupport/test/core_ext/string_ext_test.rb#L379-L413).

### System configuration

**Rails version**: 5.0

**Ruby version**: 2.3.4

### Pull Request

I've added a [Pull Request](https://github.com/rails/rails/pull/29105) proposing new behavior for this case.  It returns a blank string.

**Comment by jonathanhefner** [comment]
Fixed by #33058.
