### ISSUE TITLE
rails db:migrate db:seed cannot be run in the same command as of v5.1

### ISSUE THREAD

**Issue by glebm** [rails/rails#29112]
### Steps to reproduce

1. Create a new Rails project with postgresql.
3. Add a migration that creates a table.
2. `echo 'ApplicationRecord.connection.reconnect!' > db/seeds.rb`  
3. Run `rails db:create db:migrate db:seed`

### Expected behavior

Finishes without errors.

### Actual behavior

Hangs on Rails 5.1.1.
Works on Rails 5.0.3.

### System configuration
**Rails version**: 5.1.1
**Ruby version**: 2.4.1

---

### Another way to reproduce (without `reconnect!`)

1. Create a `User` model and table with a `name` field.
2. Add this snippet to the user model
   
   ```ruby
   def name=(value)
     super(value)
   end
   ```
3. `echo 'User.create(name: "Joe")' > db/seeds.rb`
4. `rails db:create db:migrate db:seed`
    :boom: error, no superclass method `name=` defined.

Running `rails db:create db:migrate` and then `rails db:seed` works in both cases.

**Comment by andrehjr** [comment]
Hey @glebm, I've tried following your steps and was not able to reproduce this issue. Maybe I'm missing something?

```
➜  rails db:drop db:create db:migrate db:seed
Dropped database 'sandbox_development'
Created database 'sandbox_development'
== 20170521021717 CreateUsers: migrating ======================================
-- create_table(:users)
   -> 0.0016s
== 20170521021717 CreateUsers: migrated (0.0018s) =============================

Running: ApplicationRecord.connection.reconnect!
Running: User.create(name: "Joe")
➜ ruby -v
ruby 2.4.1p111 (2017-03-22 revision 58053) [x86_64-darwin16]
➜ rails --version
Rails 5.1.1
```

**Comment by glebm** [comment]
@andrehjr You're right, I've just tried to reproduce it in a standalone Rails app and it works.

However, for some reason that I haven't been able to isolate yet, it does not work in this case:

```bash
git clone https://github.com/thredded/thredded_create_app
cd thredded_create_app
git checkout c26b25953af56db1082e58478311cf84fea787ed
bundle
bin/create-tmp-myapp
```

**Comment by dansteele** [comment]
Also getting this issue on 5.1.1 and 5.1.2
Relatively new app, and not doing anything 'odd' with migrations 😅

**Comment by dansteele** [comment]
After a load of fiddling, I managed to resolve by adding
```ruby
ApplicationRecord.reset_column_information
```
at the top of my seeds.rb

**Comment by rafaelfranca** [comment]
Can you please provide a sample application that reproduces the error?

**Comment by vnbrs** [comment]
This still happens. As in 5.1, I have to run `rails db:migrate && rails db:seed` instead of `rails db:migrate db:seed`. It seems `db:seed` caches the column info somehow.

**Comment by alienxp03** [comment]
Still happening. Rails 5.2.2.1. At the moment, I'm writing the code below on top of the seed file to fix the issue.

```ruby
Rails.application.eager_load!
ActiveRecord::Base.descendants.each { |model| model.reset_column_information }
```

**Comment by mandark97** [comment]
Still happening in Rails 5.2.3.
Adding 
`ApplicationRecord.reset_column_information`
on top of seed file resolved the issue

**Comment by edmundtfy** [comment]
Adding
`ApplicationRecord.reset_column_information`
did not work for me. Nothing did.

**Comment by yoniamir** [comment]
Same issue here. 
Adding `ApplicationRecord.reset_column_information` did not work.

**Comment by ianlet** [comment]
Similar issue for me. Adding `ApplicationRecord.reset_column_information` did work though.
Running version 5.2.3

**Comment by zbornstein** [comment]
> After a load of fiddling, I managed to resolve by adding
> 
> ```ruby
> ApplicationRecord.reset_column_information
> ```
> 
> at the top of my seeds.rb

This solution worked for my scenario, Rails v5.2.4.1 👍

**Comment by LiiKaz** [comment]
> > After a load of fiddling, I managed to resolve by adding
> > ```ruby
> > ApplicationRecord.reset_column_information
> > ```
> > at the top of my seeds.rb
> 
> This solution worked for my scenario, Rails v5.2.4.1 +1

Thanks @zbornstein
This work with Rails 6 too.

**Comment by pil0u** [comment]
> ```ruby
> ApplicationRecord.reset_column_information
> ```
> at the top of my seeds.rb

Running Rails 7.1, this also solved my problem.

I understand that the `schema` starts to be cached somehow (after X migrations? what is the threshold for that?). I would expect that cache to be cleared systematically before running the seed task, but I'm probably missing something that makes the current behaviour expected.
