### ISSUE TITLE
Is there a known performance regression with querying/eager loading/instantiating AR objects in Rails 4.2.8?

### ISSUE THREAD

**Issue by MGPalmer** [rails/rails#29114]
Please see my SO question here:

http://stackoverflow.com/questions/44011085/is-there-a-known-performance-regression-with-querying-eager-loading-instantiatin

Or should I repeat the info here?

**Comment by matthewd** [comment]
I'd say it's not totally implausible, though more than I'd expect

Rails 4.2 is no longer supported -- and 3.2 is too far back for rubybench.org comparisons. So there isn't really much more to offer here.
