### ISSUE TITLE
Raise on missing events for ActiveSupport::Notifications.instrument

### ISSUE THREAD

**Issue by Dorian** [rails/rails#29126]
Typos / mistakes / ... are too easy with `ActiveSupport::Notifications.instrument` because calling it on any event name, even non-exisiting ones doesn't raise an exception.

### Steps to reproduce

```
require 'active_support/all'

ActiveSupport::Notifications.instrument(:nope)
```

### Expected behavior

It should raise an exception.

### Actual behavior

It doesn't raise an exception.

### System configuration

**Rails version**: `Rails 5.0.2`
**Ruby version**: `ruby 2.4.1p111 (2017-03-22 revision 58053) [x86_64-darwin16]`

**Comment by rafaelfranca** [comment]
The current behavior make sense. The instrumenter should be able to instrument any event even the ones that are not being listen yet.
