### ISSUE TITLE
`db:schema:load_if_ruby` also runs `db:create`

### ISSUE THREAD

**Issue by schneems** [rails/rails#29128]
The task `db:schema:load_if_ruby` does not simply call `db:schema:load` when the schema format is set to `:ruby` instead it also calls `db:create` which fails on systems where a user does not have super user access. 

This task was originally extracted from `db:setup` however I think that it was a mistake that `db:create` is called at this location. Here is the commit https://github.com/rails/rails/commit/38d26b0cb56d82093889efa95992a35ba3bb9f29.

If we do want the schema load to create a database we should add it to `db:schema:load` so the task is consistent with the task name.

**Comment by eugeneius** [comment]
I don't think we want `db:schema:load` to automatically create the database.

The `db:schema:load_if_ruby` task is undocumented, so we could change its behaviour to match its name without worrying about backwards compatibility.

What's the use case for running that task directly?
