### ISSUE TITLE
Using .unscope with a default_scope that has .or(where....) in it

### ISSUE THREAD

**Issue by frederikspang** [rails/rails#29125]
### Steps to reproduce

1. Create a default scope that includes a `where(x: nil).or(where('x > ?', Time.now))` for example
2. Try to unscope that one field (or two) using `.unscope(where: :x)`

### Expected behavior
I'm expecting the unscope to remove the default scope, both the first `where` and the where inside the `or`-block.

### Actual behavior
Nothing happens. I've reproduced the case in this repository, with a User model with a deleted_at field, that outputs a JSON in root, with the created queries using `.to_sql` for showing off what the actual output is from the query.
https://github.com/frederikspang/rails-test-unscoping 

```
{
  "User.all (Correct)": "SELECT \"users\".* FROM \"users\" WHERE (\"users\".\"deleted_at\" IS NULL OR (deleted_at >= '2017-05-17 16:50:01.378815'))",
  "User.all.unscope(where: :deleted_at)": "SELECT \"users\".* FROM \"users\" WHERE (\"users\".\"deleted_at\" IS NULL OR (deleted_at >= '2017-05-17 16:50:01.380314'))",
  "User.all.unscope(:where)": "SELECT \"users\".* FROM \"users\"",
  "User.all.unscoped": "SELECT \"users\".* FROM \"users\""
}
```

I've also set up 5 testcases that I believe covers the subject somewhat accurate.

### System configuration
**Rails version**: master-branch and tested with 5.1.0 and 5.0.1

**Ruby version**: 2.3.3, 2.4.1 (All probably)

Of course I'll provide any other info you might need, and I'll also go with any other solution that might solve the problem of default scope being "not deleted, or deleted_at is in the future". I haven't been able to solve this, no matter what I've tried. Only solution is to use `.unscoped` which creates a number of other issues.

**Comment by matthewd** [comment]
> I'm expecting the unscope to remove [..] the where inside the or-block

That wouldn't work even without the `or`: it has no way to know the opaque SQL string condition references that column.

It might be possible to teach it to remove the hash-based condition, though.

**Comment by frederikspang** [comment]
True. Or maybe removing a 'named' default_scope, if one were to add multiple, say in a Gem and directly in the model-file?

If i had removed the .or(where..)) it would just be `.where(x: nil)` which `unscope(where: :x)` could remove.. I was hoping that I was missing out on some way to do a >= with a where - One that'd actually use a symbol in the where-call like, `where(x: lt(Time.Now))`-ish.

**Comment by frederikspang** [comment]
Okay in addition to above, I've also tried using
`where(deleted_at: nil).or(where(deleted_at: (DateTime.now..DateTime::Infinity.new)))`, to ensure that I'm using a hash with symbolkeys for both where's, which produces the exact same result, sadly.. 

Any ideas? Maybe it'd be a solution to also check for `.or`-calls somehow?

**Comment by mathmatomancer** [comment]
not sure if this is documented elsewhere, but I did find a smaller, more common repro for this. A scope that gets turned into an or clause is unable to be unscoped:

```
default_scope -> {where(disabled: [nil, false]}
...

Thing.all.to_sql -> "SELECT  \"things\".* FROM \"things\" WHERE (\"things\".\"disabled\" IS NULL OR  \"things\".disabled  = 'f')

Thing.unscope(where: :disabled).to_sql -> "SELECT  \"things\".* FROM \"things\" WHERE (\"things\".\"disabled\" IS NULL OR  \"things\".disabled  = 'f')
```
