### ISSUE TITLE
rails 5.1: validates_associated in polymorphic associations: parent is not set

### ISSUE THREAD

**Issue by gatperdut** [rails/rails#29121]
First of all, you can checkout a project where this can be reproduced under: https://github.com/gatperdut/testing

The scenario is as follows: I have 3 models, one of which is the parent (`Character`) and the other two are associations of it (`Inventory` and `SkillSet`). `Inventory` is polymorphic. Here they are:

```
class Character < ApplicationRecord

  has_one :skill_set, dependent: :destroy

  has_one :inventory, as: :parent, dependent: :destroy

  validates_associated :inventory, :skill_set

end
```

```
class Inventory < ApplicationRecord

  belongs_to :parent, polymorphic: true, validate: true

  #validate :fake_validation

  def fake_validation
    errors.add(:parent, "why not")
  end

end
```

```
class SkillSet < ApplicationRecord

  belongs_to :character

end

```

The migrations for the models are:

```
class CreateCharacters < ActiveRecord::Migration[5.1]
  def change
    create_table :characters do |t|

    end
  end
end
```

```
class CreateInventories < ActiveRecord::Migration[5.1]
  def change
    create_table :inventories do |t|
      t.references :parent, null: false, index: true, polymorphic: true
    end
  end
end
```
```

class CreateSkillSets < ActiveRecord::Migration[5.1]
  def change
    create_table :skill_sets do |t|
      t.references :character, null: false, index: true
    end
  end
end
```

As you can see, I'm using `validates_associated` in `Character` because I want the associated objects to be validated when the parent model is saved.

My problem is, when I save a new parent, the `SkillSet` gets a correctly assigned `character_id`, but for `Inventory` (the polymorphic one) the same does not happen:

```
c = Character.new(inventory: Inventory.new, skill_set: SkillSet.new)
c.save
   (0.1ms)  begin transaction
   (0.1ms)  rollback transaction
=> false

irb(main):004:0> c.skill_set
=> #<SkillSet id: 1, character_id: 1>


irb(main):002:0> c.inventory
=> #<Inventory id: nil, parent_type: "Character", parent_id: nil>

c.inventory.errors.full_messages
=> ["Parent must exist"]
```

Is there any reason why this is so?

I tried a couple of alternatives:
a) just remove the `validates_associated`. In this case, `character` gets saved but the validations for `inventory` are not run. So even if I force `inventory` to be invalid (note `fake_validation`, I activate it in this scenario) it gets saved. Not good.
b) remove `validates_associated` and turn `has_one :inventory` in `character` into `has_one :inventory, validate: true`. Same behaviour.
c) remove `validates_associated` and turn `belongs_to :parent, polymorphic: true` in `inventory` into `belongs_to :parent, polymorphic: true, validate: true`. `Inventory` is not saved, but `character` is!.

I'm honestly at a loss here. Am I doing something wrong. Did I stumble upon a bug?

**Comment by JarLowrey** [comment]
I believe you're running into this https://github.com/rails/rails/issues/29781#issuecomment-315194525

**Comment by dongoclam** [comment]
I have the same problem on `rails-5.1.6`. There are two model
```
class Candidate < ApplicationRecord
  belongs_to :channel, polymorphic: true
end

class ChannelCustom < ApplicationRecord
  has_many :candidate, as: :channel
end
```

And when I try
```
>> candidate.channel = ChannelCustom.new
  #<ChannelCustom:0x00007f6a0de61170 id: nil, name: nil, created_at: nil, updated_at: nil>
>> candidate.valid?
  # true
>> candidate.save
  # true
```
Rails ignore the channel parent (I don't see any query string relatively to the channel_customs table) and then
```
>> candidate = Candidate.last
>> candidate.valid?
  # false
>> candidate.errors
 #  @details={:channel=>[{:error=>:blank}]}
```
In another case
```
>> candidate.channel = ChannelCustom.new name: "Something"
```
Everything work great !
The problem is Rails ignore the channel parent in the first case so no exception is raised and then we do not have a rollback as expected
