### ISSUE TITLE
rescue_from ActiveRecord::RecordNotFound is not rendering .js.erb

### ISSUE THREAD

**Issue by feliperaul** [rails/rails#29124]
I have a scaffolded Rails Controller that is working fine, responding with update.js.erb when the update is successful. 

But when record isn't found, server was returning error 500 to the browser, and I wanted to return javascript (an alert for example). 

Following convention, this is what I did: 

### Steps to reproduce

```
class PostsController < ApplicationController

  rescue_from ActiveRecord::RecordNotFound, :with => :record_not_found

  before_action :set_post, only: [:show, :edit, :update, :destroy]

def record_not_found

end

private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

```
And then in app/views/posts/record_not_found.js.erb:
`alert('test');`

Following Rails convention, being this a JS request, Rails should return to the browser the content of record_not_found.js.erb. I use this convention all the time in my other actions and it works really nice (I love it btw). 

The problem is, with this `rescue_from` method, Rails is *alway* returning status 200 to the browser *without* any responde body whatsoever. In other words, it doesn't return the javascript in record_not_found.js.erb. 

I can confirm that the action `record_not_found` is being triggered, since if I put `binding.pry` there it get's run. Also, If I use `head :not_found` or something like this, the status code returned to the browser also changes.

I can confirm that the browser is sending the request as xhr. Also, in rails server, I can confirm that the request is being processed as JS:
```
Started PATCH "/posts/244" for ::1 at 2017-05-17 08:58:35 -0300
Processing by PostsController#update as JS
Parameters: (...)
  User Load (0.6ms)  SELECT  "users".* FROM "users" WHERE "users"."id" = $1 ORDER BY "users"."id" ASC LIMIT $2  [["id", 1], ["LIMIT", 1]]
  Post Load (2.2ms)  SELECT  "posts".* FROM "posts" WHERE "posts"."id" = $1 LIMIT $2  [["id", 244], ["LIMIT", 1]]
Completed 200 OK in 9ms (ActiveRecord: 2.8ms)
```

Even if I create a record_not_found.html.erb nothing is sent in the response body. 

And yes, I'm pretty sure post id 244 doesn't exist. If I remove rescue_from, the exception get's raised in rails server again. I can also confirm in rails console:

```
Post.find 244
  Post Load (0.9ms)  SELECT  "posts".* FROM "posts" WHERE "posts"."id" = $1 LIMIT $2  [["id", 244], ["LIMIT", 1]]
ActiveRecord::RecordNotFound: Couldn't find Post with 'id'=244
```

### Expected behavior

Following Rails convention, it should render record_not_found.js.erb content.

### Actual behavior
Returns no response to the browser, just a status 200. 

### System configuration
**Rails version**:
rails (5.0.2)
**Ruby version**:
ruby 2.2.2p95 (2015-04-13 revision 50295) [x86_64-darwin16]

**Comment by meinac** [comment]
You need to explicitly render the template in `record_not_found` method. What `rescue_from` doing is just **calling** the method which has given with `with` keyword or just runs the block in case you provide.

**Comment by feliperaul** [comment]
If I'm not mistaken, there's a convention in Rails that an action will always render the template with the same name of the action. So even an *empty* action (record_not_found) should render, for instance, record_not_found.html.erb or record_not_found.js.erb according to the request. No code required, and it works like that for every other action I have in my app. 

If that's the case, why a rescue action should behave any differently? If that's the case, I didn't see it documented anywhere, it's a break of pattern/convention and very counterintuitive.

**Comment by meinac** [comment]
Lets imagine you have an `index` action and inside of this `index` action at the very end you are calling another **method** of the class what do you expect Rails to do? Of course rails will render template of `index` action. If you call a method of a controller on your own, the action dispatch and rendering does not work for the method you called.

**Comment by feliperaul** [comment]
@meinac Understood your point, but I still think its not very intuitive because I'm not exactly calling another method of the controller, I'm using a Rails rescue method and specifying, per documentation, the 'action' to be rescued to. So this is not a custom meethod I made up, It's using a Rails feature to rescue to another 'action' and IMHO this behavior broke convention, causing unexpected behavior. Anyways, thanks for the help, I'm closing this one!
