### ISSUE TITLE
Rails secrets:edit doesn't work properly when $EDITOR == gvim

### ISSUE THREAD

**Issue by pedroadame** [rails/rails#29120]
### Steps to reproduce

```
export EDITOR=gvim
rails new gvim_bug_test
cd gvim_bug_test
rails secrets:setup
rails secrets:edit
```
GVim will open with an empty file. (and it should show the comments in the file)
Modify it and run `:wq<ENTER>` to save & exit.
Rails will tell you "saved secrets"

### Expected behavior
Run `rails secrets:edit` and you can see the content of the file

### Actual behavior
Run `rails secrets:edit` again and there is no content in file.
Exit gvim with `:q<ENTER>`
Now run `export EDITOR=vim`
Run `rails secrets:edit` and you can see the content. And it will be the original file (the commented one). The changes done in GVim will not appear.

### System configuration
**Rails version**: 5.1.1

**Ruby version**: 2.4.0p0

**Comment by matthewd** [comment]
This is expected behaviour: `gvim` is not suitable for use in `EDITOR`, because it returns immediately. You probably want `gvim -f`.

**Comment by pedroadame** [comment]
Thank you! Didn't know about `-f`.
