### ISSUE TITLE
AR 5.1: Polymorphic association failure when a poly attribute shares its table name

### ISSUE THREAD

**Issue by jgelo** [rails/rails#29139]
Found an issue with AR 5.1 when an attribute in a polymorphic table is the same as the table name, eg. table notes has a text field also named notes.

If a user has_many notes as 'notable', user.notes fails with a "TypeError: can't cast Hash" error.  

Method _type_cast in activerecord-5.1.1/lib/active_record/connection_adapters/abstract/quoting.rb                                   
is receiving a hash of {'notable_id' => ...} which it can't typecast.

The problem does not appear if the notes attribute is renamed to something other than notes.

Below is a template to reproduce the issue -

```
begin
  require "bundler/inline"
rescue LoadError => e
  $stderr.puts "Bundler version 1.10 or later is required. Please update your Bundler"
  raise e
end

gemfile(true) do
  source "https://rubygems.org"
  gem "rails", github: "rails/rails"
  gem "arel", github: "rails/arel"
  gem "sqlite3"
end

require "active_record"
require "minitest/autorun"
require "logger"

# This connection will do for database-independent bug reports.
ActiveRecord::Base.establish_connection(adapter: "sqlite3", database: ":memory:")
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :users, force: true do |t|
  end

  create_table :notes, force: true do |t|
    t.text    :notes
    t.text    :notable_type
    t.integer :notable_id
  end
end

class User < ActiveRecord::Base
  has_many :notes, as: 'notable'
end

class Note < ActiveRecord::Base
  belongs_to :notable, polymorphic: true
end

class NoteTest < Minitest::Test
  def test_notable
    user = User.create!

    assert_equal 0, user.notes.count
  end
end
```

**Comment by kamipo** [comment]
#29058 will fix the issue.

**Comment by jgelo** [comment]
Thanks @kamipo, I confirmed that #29058 does fix this issue and it's also a duplicate of #29045.
