### ISSUE TITLE
Interface of ajax callbacks.

### ISSUE THREAD

**Issue by DmytroVasin** [rails/rails#29137]
Based on source code: [`fire` call](https://github.com/rails/rails/blob/master/actionview/app/assets/javascripts/rails-ujs/features/remote.coffee#L61) and [`fire` definition](https://github.com/rails/rails/blob/master/actionview/app/assets/javascripts/rails-ujs/utils/event.coffee#L22)

`ajax:beforeSend`, `ajax:success`, `ajax:error` and etc callbacks are fired by `CustomEvent ` that contains `event.detail` argument with an array of callback options.

**Previously:** 
When we based on jquery-ujs we have next interface:

```
function handleAjaxSuccess(event, data, status, xhr) {
  // ...
}
$(‘#form’).on('ajax:success', handleAjaxSuccess)
```
That contains `event` with `several parameters` ( depends from event )

**Now we have next:**
```
function handleAjaxSuccess(event) {
  console.log(event.details[0]) // xhr
  console.log(event.details[1]) // options
  // ...
}
$(‘#form’).on('ajax:success', handleAjaxSuccess)
```

What do you think to present(return) parameters in `event.details` like an associative array structure?

In this case interface will looks like:
```
function handleAjaxSuccess(event) {
  console.log(event.details.xhr)
  console.log(event.details.options)
  // ...
}
$(‘#form’).on('ajax:success', handleAjaxSuccess)
```

I can attach PR with such implementation. 
If current implementation is completely right - i can build kind of documentation of such behaviour. What do you think?

Thanks.

**Comment by inopinatus** [comment]
I have already adapted to the new form with code like this:

```` coffeescript
document.body.addEventListener 'ajax:success', (event) ->
  [data, status, xhr] = event.detail
````

**Comment by mtrolle** [comment]
Took me ages to find this - at least the documentation should be updated here:
http://guides.rubyonrails.org/working_with_javascript_in_rails.html#dealing-with-ajax-events

**Comment by robin850** [comment]
Would one of you be interested in submitting a patch to fix this ? We could keep the current `event.detail` for people who have already upgraded but this would be cool to make it backward-compatible for people that will upgrade in the future.

**Comment by DmytroVasin** [comment]
As i mentioned above: I can provide documentation of such new behaviour. That will cause less pain while updating.

About backward-compatibility:
From source-code of jQuery - [jQuery Dispatch function](https://github.com/jquery/jquery/blob/a6b0705294d336ae2f63f7276de0da1195495363/src/event.js#L294).  Our data, status, xhr -  are inside arguments `array`. 
As you can see - jQuery tries to determine appropriate handler for current dispatch and then [apply arguments](https://github.com/jquery/jquery/blob/a6b0705294d336ae2f63f7276de0da1195495363/src/event.js#L338) to this function.

I could be wrong, but my assumption is it will not be easy to provide backward-compatibility.

<hr />
According to current implementation: 
As for me, it would be more appropriate to create:

```
function handleAjaxSuccess(event) {
  console.log(event.details.xhr)
  console.log(event.details.options)
  // ...
}
$(‘#form’).on('ajax:success', handleAjaxSuccess)
```

Because in this case:
```
document.querySelector('#form').addEventListener 'ajax:success', (event) ->
  [data, status, xhr] = event.detail
```

User should always remember position of the attributes.

 P.S. Maybe I was wrong somewhere, correct me please.
