### ISSUE TITLE
Add :json type to auto_discovery_link_tag()

### ISSUE THREAD

**Issue by veganstraightedge** [rails/rails#29142]
This is a feature request to support the new JSON Feed format in `auto_discovery_link_tag`.

See: https://jsonfeed.org/version/1#discovery

### Steps to reproduce

Add an `auto_discovery_link_tag` using the type of `:json`

```erb
<%= auto_discovery_link_tag(:json, "https://example.com/feed.json", title: "JSON Feed" ) %>
```

### Expected behavior

```html
<link rel="alternate" title="JSON Feed" type="application/json" href="https://example.com/feed.json" />
```

### Actual behavior

```
You should pass :type tag_option key explicitly, because you have passed json type other than :rss or :atom.
```

This meant I had to re-write like this:

```erb
<%= auto_discovery_link_tag(nil, "https://example.com/feed.json", { title: "JSON Feed", type: "application/json" }) %>
```

Bummer.

### System configuration
**Rails version**: 5.1.0

**Ruby version**: 2.4.0

**Comment by bogdanvlviv** [comment]
@pixeltrix this issue can be closed

**Comment by veganstraightedge** [comment]
@bogdanvlviv @pixeltrix Can you give a reason why it was closed?

**Comment by pixeltrix** [comment]
@veganstraightedge because I merged #29158 which adds support for `:json` to `auto_discovery_link_tag` 😄

**Comment by veganstraightedge** [comment]
Oh thanks! I missed the merger PR. 👍🏻👍🏻👍🏻

**Comment by veganstraightedge** [comment]
s/merger/merged/
