### ISSUE TITLE
ActiveSupport::Dependencies.unhook! Not working

### ISSUE THREAD

**Issue by nazarhussain** [rails/rails#29148]
I was debugging a memory leak (more details can be found on http://stackoverflow.com/questions/44073356/memory-leak-activesupport-dependencies
To debug further I tried to unhook `ActiveSupport::Dependencies` but its crashing with error

```
define_method': wrong argument type NilClass (expected Proc/Method) (TypeError
```

### Steps to reproduce
1. Create a file `test.rb` under root `scripts` directory 
2. Add the code in the file

```
ENV['RAILS_ENV'] = 'production'
require File.expand_path('../../config/environment', __FILE__)

ActiveSupport::Dependencies.unhook!

```
3. Run the file with `bundle exec ruby scritps/test.rb`

### Expected behavior
It should work without any crash 

### Actual behavior
Crash with error 
```
activesupport-5.0.2/lib/active_support/dependencies.rb:196:in `define_method': wrong argument type NilClass (expected Proc/Method) (TypeError)
  from activesupport-5.0.2/lib/active_support/dependencies.rb:196:in `block in exclude_from'
  from activesupport-5.0.2/lib/active_support/dependencies.rb:195:in `class_eval'
  from activesupport-5.0.2/lib/active_support/dependencies.rb:195:in `exclude_from'
  from activesupport-5.0.2/lib/active_support/dependencies.rb:326:in `unhook!'
```
### System configuration
Rails 5.0.2
Ruby 2.3.4p301

**Comment by nazarhussain** [comment]
One interesting thing I found is it do work in `development` environment but not in `production` environment.

**Comment by matthewd** [comment]
It's already unhooked in production.

`unhook!` is an internal method, so it's not expected to behave well if called directly.
