### ISSUE TITLE
Suggestion for new method 'without_callback' in ActiveRecord and ActiveModel

### ISSUE THREAD

**Issue by pedrofurtado** [rails/rails#29144]
Isn't interesting to provide a new method called `without_callback`, to wrap the use of `skip_callback` and `set_callback` of the models, in a more idiomatic way?

A draft of implementation (that I use in my projects) is something like this:

```ruby
# config/initializers/without_callback.rb

module ActiveSupport::Callbacks::ClassMethods
  def without_callback(*args)
    skip_callback(*args)
    yield if block_given?
    set_callback(*args)
  end
end
```

An example of use:

```ruby
# app/models/user.rb

class User < ActiveRecord::Base do
  after_create :send_welcome_email

  def send_welcome_email do
    MyMailer.deliver(name, email)
  end
end

User.without_callback :create, :after, :send_welcome_email do 
  1000.times do |i|
    user = User.new
    user.email = "user#{i}@example.com"
    user.name = "User #{i}"
    user.save
  end
end
```

What do the Rails team think about this suggestion? Is interesting to insert this on Rails Core?

Thanks!

**Comment by alexcameron89** [comment]
Hey @pedrofurtado, we reserve this tracker for bug reports and issues.

[Rails Core mailing list](https://groups.google.com/forum/#!topic/rubyonrails-core/Cx0GXz_k7Dc) is the best place to discuss this, or you can send a pull request with the changes to start a discussion.

Thanks!
