### ISSUE TITLE
ActiveSupport::Callbacks - Memory Leak ?

### ISSUE THREAD

**Issue by nazarhussain** [rails/rails#29150]
I am debugging a memory leak and dig out some interesting things. Need input from you guys weather its a memory leak or something else.

So first here is the script I run to verify blank state: 

```
require 'objspace'
ObjectSpace.trace_object_allocations_start

ENV['RAILS_ENV'] = 'production'
require File.expand_path('../../config/environment', __FILE__)
GC.start
heap_values = GC::stat[:heap_live_slots]
ObjectSpace.dump_all output: 'start.dump'

# Processing Code
10_000_00.times do 
   a = 'Some random string'
end

GC.start
heap_values2 = GC::stat[:heap_live_slots]
ObjectSpace.dump_all output: 'end.dump'

puts heap_values2 - heap_values
```
When I run above script I usually get `0` or a `negative` output. Which seems obvious and clearly shows no memory leak. 

No if I replace my processing code with some real `active record` queries and different `json` processing. The output `difference of heap slots` return a high number. In my code normally over 1k objects. 

To dig further I compare both heap dumps and tried to identify which objects are available in heap at the end of script, which were not available in start. 

I used the script https://gist.github.com/nazarhussain/e2f95518cc7e236afbbb501f1e00fbe4 to compare two heap dumps. 

Most of the retained objects in memory are of type `DATA` and coming from 
https://github.com/rails/rails/blob/5-0-stable/activesupport/lib/active_support/callbacks.rb#L382
https://github.com/rails/rails/blob/5-0-stable/activesupport/lib/active_support/callbacks.rb#L385

Can any one help me to further diagnose. Does the difference in heap slots can really be considered as memory leaks? Why those `proc` from callbacks retained in memory even after end of script and `GC.start`?

**Comment by matthewd** [comment]
Please use the mailing list or StackOverflow for questions/help, where a wider community will be able to help you. We reserve the issues tracker for issues only.

**Comment by nazarhussain** [comment]
@matthewd As per my knowledge it was an issue in active support so why I reported here. Since I have less knowledge of rails core components so asked guys here to confirm it. 

In case someone come across this ticket, I moved it to http://stackoverflow.com/questions/44076674/activesupportcallbacks-memory-leak
