### ISSUE TITLE
[Date.civil() + 2 * 1.day] duration test is failing 

### ISSUE THREAD

**Issue by beck03076** [rails/rails#29160]
### Steps to reproduce

```
cd activesupport
bundle exec ruby -Itest test/core_ext/duration_test.rb
```

### Expected behavior
`Expected: Tue, 03 Jan 2017`

### Actual behavior
`Actual: 2017-01-03 00:00:00 +0800`

### System configuration
**Rails version**:
Rails 5.2.0.alpha
**Ruby version**:
ruby 2.4.0p0 (2016-12-24 revision 57164) [x86_64-darwin16]

**Comment by bogdanvlviv** [comment]
duplicate #28970
