### ISSUE TITLE
Feature Request: Port Ruby and Ruby on Rails to the Genode Operating System Framework

### ISSUE THREAD

**Issue by baconicsynergy** [rails/rails#29171]
My lifetime dream of mine is to run a Diaspora pod on Genode using the seL4 microkernel... but there is a lot of work to do! There is currently no Ruby port available for Genode, but there is a port for Python so I know it can be done!

I got in contact with one of the Genode developers and while they are too busy working on other parts of the system to devote time to porting Ruby, I was encouraged to play a role in it myself and seek help from the community.

I truly believe that porting Ruby to high-assurance and highly secure operating systems can help us build a safer internet and make the world a better place.

Any thoughts or feedback? I'm going to continue seeking help from all over the community and see what can be done.

**Comment by matthewd** [comment]
Please use the mailing list or StackOverflow for questions/help, where a wider community will be able to help you. We reserve the issues tracker for issues only.
