### ISSUE TITLE
`rails new . -d=sqlserver` 5.1.1 failing to init new app

### ISSUE THREAD

**Issue by Kyitrai** [rails/rails#29177]
Trying to install Rails 5.1.1 with SQLServer ... `rails new . -d=sqlserver` fails to generate a new app

- Ubuntu 16.04
- rbenv 1.1.0
- Ruby 2.3.3 (also tried 2.3.1, 2.2.3)

### Steps to reproduce
After freshly installing Ruby 2.3.1 in rbenv:

- `mkdir` and `cd` to new dir (to be new project root)
- `rbenv local 2.3.1`
- `gem install rails`
- `gem update`
- `rails new . -d=sqlserver`

### Expected behavior
A successfully initialized application, that I can `bin/rails server` to make sure it can run, and start writing.

### Actual behavior
ON RUBY 2.3.3, 2.3.1
```
$ rails new . -d=sqlserver
     <spam>
Bundler::GemRequireError: There was an error while trying to load the gem 'activerecord-sqlserver-adapter'.
Gem Load Error is: undefined method `alias_method_chain' for #<Class:ActiveRecord::Base>
Did you mean?  alias_method
Backtrace for gem load error is:
/home/kyitrai/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/activerecord-sqlserver-adapter-2.3.8/lib/active_record/connection_adapters/sqlserver_adapter/core_ext/active_record.rb:13
```
ON RUBY 2.2.3, `rails new . -d=sqlserver` succeeds, but any invocation of bundle (`bundle exec rails s`, or `bin/rails server`) will throw the following:
```
kyitrai@Houou:~/code/r3-ui1$ bundle exec rails s
/home/kyitrai/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/bundler-1.15.0/lib/bundler/runtime.rb:85:in `rescue in block (2 levels) in require': There was an error while trying to load the gem 'activerecord-sqlserver-adapter'. (Bundler::GemRequireError)
Gem Load Error is: undefined method `alias_method_chain' for #<Class:ActiveRecord::Base>
Backtrace for gem load error is:
/home/kyitrai/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/activerecord-sqlserver-adapter-2.3.8/lib/active_record/connection_adapters/sqlserver_adapter/core_ext/active_record.rb:13:in `singleton class'
```

### Comments
So all said, I'm new with Ruby and Rails specifically, but not with coding and troubleshooting. I scoured Google for a couple hours without any luck as well.

In my trials I also tried to modify the `gemfile` to require a more current version of the sqlserver adapter (newest is 5.0.7 or so - very big gap in version numbers to what Rails takes), but that just created an unresolveable dependency issue:
```
Bundler could not find compatible versions for gem "activerecord":
  In Gemfile:
    activerecord-sqlserver-adapter (~> 5.0.0) was resolved to 5.0.0, which depends on
      activerecord (~> 5.0.0)

    rails (~> 5.1.1) was resolved to 5.1.1, which depends on
      activerecord (= 5.1.1)
```

**Comment by prathamesh-sonpatki** [comment]
Looks like sqlserver-adapter is [not yet compatible with Rails 5.1.](https://github.com/rails-sqlserver/activerecord-sqlserver-adapter/blob/master/activerecord-sqlserver-adapter.gemspec#L19) 

This issue is not with Rails but sqlserver-adapter not supporting Rails 5.1. Thanks but giving this a close.
