### ISSUE TITLE
README "Learn more" links not working

### ISSUE THREAD

**Issue by tdtadeu** [rails/rails#29188]
Pretty straight forward: none of the "Learn more" links in the README seem to be working. Were they supposed to link to code or documentation?

Edit: Forgot to mention, I'm talking about activerecord's, not rails'

**Comment by alexcameron89** [comment]
Hey @tdtadeu, thank you for the concern, but those links are actually meant to work in the generated RDoc at api.rubyonrails.org. [Here is the page for reference.](http://api.rubyonrails.org/files/activerecord/README_rdoc.html)
