### ISSUE TITLE
Possible bug - Minitest could not find js assets installed via gem

### ISSUE THREAD

**Issue by psantos10** [rails/rails#29185]
### Steps to reproduce

I am following the "Agile Web Development with Rails 5.1 b1.0". On page 160, was asked to update Gemfile to add the following 2 lines: 

```
gem 'jquery-rails
gem 'jquery-ui-rails
```

and add those 2 lines at `app/assets/javascripts/application.js`:

// ...
//= require jquery
//= require jquery_ujs
//= require jquery-ui/effects/effect-blind
//...

And testing the page, its runs successfully. 

### Expected behavior

Running the Tests: bin/rails test

I expect the test to pass successfully. 

### Actual behavior

unfortunately, when I run the tests I got this error:

> 
> bin/rails test test/controllers/products_controller_test.rb:19
> 
> E
> 
> Error:
> ProductsControllerTest#test_should_get_index:
> ActionView::Template::Error: couldn't find file 'jquery' with type 'application/javascript'
> Checked in these paths:
>   /Users/psantos/Workspace/learning_programming/ruby/awdwr51/depot/app/assets/config
>   /Users/psantos/Workspace/learning_programming/ruby/awdwr51/depot/app/assets/images
>   /Users/psantos/Workspace/learning_programming/ruby/awdwr51/depot/app/assets/javascripts
>   /Users/psantos/Workspace/learning_programming/ruby/awdwr51/depot/app/assets/stylesheets
>   /Users/psantos/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/coffee-rails-4.2.1/lib/assets/javascripts
>   /Users/psantos/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/actioncable-5.1.1/lib/assets/compiled
>   /Users/psantos/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/actionview-5.1.1/lib/assets/compiled
>   /Users/psantos/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/turbolinks-source-5.0.3/lib/assets/javascripts
>   /Users/psantos/Workspace/learning_programming/ruby/awdwr51/depot/node_modules
>     app/assets/javascripts/application.js:14
>     app/views/products/index.html.erb:9:in `block in _app_views_products_index_html_erb__3914504961955239148_70098856983740'
>     app/views/products/index.html.erb:6:in `_app_views_products_index_html_erb__3914504961955239148_70098856983740'
>     test/controllers/products_controller_test.rb:15:in `block in <class:ProductsControllerTest>'

But if I add `jquery` using yarn: `bin/yarn add jquery`, the test will pass. As I can understand, if I already have `jquery-rails` gem, I don't need to add jquery via yarn.

### System configuration
**Rails version**: 5.1.1

**Ruby version**: 2.4.1

**Comment by robin850** [comment]
Hello @psantos10,

Did you run `bundle` to install the dependencies before running `bin/rails test` ?

**Comment by psantos10** [comment]
@robin850 yes I did. 

The application runs as expected. The error appears only on Test environment .

**Comment by robin850** [comment]
Hum, that seems very strange. Would you be able to upload an application that reproduces this issue please ?

**Comment by psantos10** [comment]
@robin850 here you have: https://github.com/psantos10/awdwr51depot

**Comment by robin850** [comment]
When I clone your project, run `yarn`, then `bin/webpack-dev-server` then `bin/rails test`, there are two errors because of missing assets:

* [This line](https://github.com/psantos10/awdwr51depot/blob/529907ac2a10e5e28453b659b0ceeb44e73b9882/app/views/orders/new.html.erb#L8) asks for a `pay_type` pack which doesn't exist.
* [This line](https://github.com/psantos10/awdwr51depot/blob/529907ac2a10e5e28453b659b0ceeb44e73b9882/app/views/store/index.html.erb#L9) produces an error because I don't have the product assets.

Anyway, I don't have any error regarding jQuery. Are you experimenting the issue cloning your repo and doing the steps described above ?

**Comment by psantos10** [comment]
@robin850 use this commit: #48aaf3d349e4ee8260412be81e855edc12a1714a

* https://github.com/psantos10/awdwr51depot/tree/48aaf3d349e4ee8260412be81e855edc12a1714a

**Comment by robin850** [comment]
@psantos10 : Sorry but I'm still not able to reproduce the error:

~~~
$ git branch
* (HEAD detached at 48aaf3d)
  master

$ bin/rails test
bin/rails test
Running via Spring preloader in process 2164
Run options: --seed 17397

# Running:

................................E

Error:
OrdersControllerTest#test_should_get_new:
ActionView::Template::Error: Can't find hello_react.js in /Users/robin/Code/Lab/awdwr51depot/public/packs/manifest-test.json. Is webpack still compiling?
    app/views/orders/new.html.erb:8:in `_app_views_orders_new_html_erb___900925183910727165_70138054784040'
    test/controllers/orders_controller_test.rb:22:in `block in <class:OrdersControllerTest>'


bin/rails test test/controllers/orders_controller_test.rb:19

....

Finished in 1.905274s, 19.4198 runs/s, 37.2650 assertions/s.
37 runs, 71 assertions, 0 failures, 1 errors, 0 skips
~~~

Does it happen randomly or consistently ? Are you seeing the same error checking out the given commit ?

**Comment by psantos10** [comment]
@robin850 don't know what happened. Maybe restart the terminal solved the issue:

bin/rails test
Running via Spring preloader in process 82459
Run options: --seed 33632

# Running:

.................................................

Finished in 5.050942s, 9.7012 runs/s, 17.2245 assertions/s.
49 runs, 87 assertions, 0 failures, 0 errors, 0 skips
