### ISSUE TITLE
How to track unsubscribe if user has multiple tabs open

### ISSUE THREAD

**Issue by gryphon** [rails/rails#29196]
Documentation said that it is possible to use unsubscribe event to track if user online or not.
But this will not work if user has many browser tabs open. User will go offline after closing one of tabs when others are still open.

### Steps to reproduce

Just open 2 tabs and close one of them. ActionCable will fire unsubscribe event and user will go offline (disappear). 

### Expected behavior

There could be a way to track if user has any remaining opened connections. I tried to use Redis to watch for "action_cable/#{user_gid}" pubsub. It correctly shows that there is one channel per user even if there are many tabs opened. But when I trying to track unsubscribe/disappear event it seems that redis channel sometimes disappeared before the event and sometimes after the event making it unreliable way to track connections count for user.

**Comment by maclover7** [comment]
Please use the mailing list or StackOverflow for questions/help, where a wider community will be able to help you. We reserve the issues tracker for issues only.
