### ISSUE TITLE
Make protect_from_forgery(with: :exception) the default on ActionController::Base

### ISSUE THREAD

**Issue by dhh** [rails/rails#29193]
We currently generate the following ApplicationController in a fresh Rails app:

```ruby
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end
```

That's an oddly specific, lonely setting to expose. We should move that to be the default in ActionController::Base with a new framework setting. 

Then add `skip_forgery_protection if/unless:` as a wrapper around `skip_before_action :verify_authenticity_token` for the common case of turning it off for API requests.

**Comment by kaspth** [comment]
I think @eileencodes is already looking into this as part of her CSRF review/restructure. Mostly because ActionController::Base, when used directly, dosdnt have CSRF enabled.

**Comment by dhh** [comment]
👍
