### ISSUE TITLE
nil.to_json throws an error

### ISSUE THREAD

**Issue by erichummel** [rails/rails#29198]
nil.to_json throws a "nil not allowed error". Since, per https://tools.ietf.org/html/rfc7159, a plain `null` is valid JSON (and `JSON.parse("null")` successfully returns `nil`), nil.to_json shouldn't throw an error.

I tried unsuccessfully to find where this was implemented so I could submit a PR with a fix. If anyone can point me in the right direction I'd be happy to submit a PR with a fix myself.

### Steps to reproduce

```
> nil.to_json
TypeError: nil not allowed.
	from (irb):2
```

### Expected behavior

Behavior should be the same as the plain JSON and Oj gems (as well as the other primitives that are valid son)

(Note that `JSON.dump(nil)` when in a rails console, not a plain IRB console with that gem loaded, will have the same behavior as rails' `#to_json`

```
> JSON.dump(nil)
 => "null"

> Oj.dump(nil)
 => "null"

> true.to_json
 => "true"

> 42.to_json
 => "42"
```

### System configuration
Rails 5.1.1, Ruby 2.3.4

**Comment by andrehjr** [comment]
Hey @erichummel 

I tried running this with Rails 5.1.1 and master, it seems to be working for me. (Ruby 2.4.1)

```
Loading development environment (Rails 5.1.1)
irb(main):001:0> nil.to_json
=> "null"
```

**Comment by erichummel** [comment]
Hmm, there must be another gem interfering, then. I will investigate further and post what I find here for some future googler. Thanks @andrehjr for taking a look.

**Comment by erichummel** [comment]
Turns out we were calling Oj.mimic_JSON, which was causing this bug. In order to get Oj's fast JSON encoding/decoding you need to call Oj.optimize_rails, which fixed this problem.
