### ISSUE TITLE
ActionCable: disconnect/unsubscribed never called

### ISSUE THREAD

**Issue by d-schloss-mvg** [rails/rails#29207]
### Steps to reproduce
Create an `ActionCable` channel and subscribe to it. Unplug the client from the Internet and immediately call on server-side:
<pre>
ActionCable.server.remote_connections.where( :some_identifier => 'some suitable value for the disconnected client').disconnect
</pre>

### Expected behavior
Client should be `unsubscribed` from his channels and `disconnect` method on connection should be called.

### Actual behavior
`unsubscribed` and `disconnect` methods do not get called

### System configuration
**Rails version**:
Rails 5.1.0
ActionCable 5.1.0
(default setup)

**Ruby version**:
ruby-2.2.3p173

mac os 10.12.4

But should also affect **other versions**.

**Comment by XenorPLxx** [comment]
#29307

**Comment by d-schloss-mvg** [comment]
I guess that this bug still exists. But I will confirm this in a couple of days!
