### ISSUE TITLE
Executing a pl/pgsql function that uses RAISE appears to be executing twice

### ISSUE THREAD

**Issue by DrSayre** [rails/rails#29214]
I have found that when using the pg gem and executing a pl/pgsql function that uses a `RAISE` it appears that the function is being executed twice.

### Steps to reproduce
Create a pl/pgsql function that contains a raise:

```
CREATE OR REPLACE FUNCTION public.spike_foo()
    RETURNS void AS
$BODY$
    DECLARE
    BEGIN
        RAISE LOG '-------- Spike Foo ----------';
        RAISE '============ This is an error! ==============';
        RETURN;
    END;
$BODY$
LANGUAGE 'plpgsql' VOLATILE
COST 100;
```

Then execute the function like this:

```
ActiveRecord::Base.connection.execute('SELECT * FROM spike_foo();')
```

### Expected behavior
Looking at the Postgresql server logs, I would expect to see the the "spike foo" and "This is an error!" messages each only one time.

### Actual behavior

Instead, I see the "spike message" and the "This is an error" lines both twice.  I also see a statement showing where the function was called twice, which leads me to believe that the function is being called twice.

```
2017-05-04 12:41:22.255 EDT 0 590b596b.e8d0: LOG: -------- Spike Foo ---------- 2017-05-04 12:41:22.255 EDT 0 590b596b.e8d0: STATEMENT: SELECT * FROM spike_foo(); 2017-05-04 12:41:22.255 EDT 0590b596b.e8d0: ERROR: ============ This is an error! ============== 2017-05-04 12:41:22.255 EDT 0 590b596b.e8d0: STATEMENT: SELECT * FROM spike_foo(); 2017-05-04 12:41:23.064 EDT 0 590b596b.e8d0: LOG: -------- Spike Foo ---------- > 2017-05-04 12:41:23.064 EDT 0 590b596b.e8d0: STATEMENT: SELECT * FROM spike_foo(); 2017-05-04 12:41:23.064 EDT 0 590b596b.e8d0: ERROR: ============ This is an error! ============== 2017-05-04 12:41:23.064 EDT 0 590b596b.e8d0: STATEMENT: SELECT * FROM spike_foo();
```

When I remove the "Raise" line and only use the "RAISE LOG"  the output shows "Spike Foo" only once.

When I execute the function through `psql` or the `PG` gem directly, I see the Error and the log message only once.  If it would help to reproduce this error, I can put together a rails app that will setup this error to make it easier to reproduce.

### System configuration
**Rails version**:
4.1.8

**Ruby version**:
2.2.3

**Comment by alexcameron89** [comment]
Hey @DrSayre, can you create an executable test script, using [one of the templates here](https://github.com/rails/rails/tree/master/guides/bug_report_templates), that would demonstrate the problem you are seeing?

Also, Rails 4.1 is [not longer supported](http://guides.rubyonrails.org/maintenance_policy.html) for bug fixes.

**Comment by DrSayre** [comment]
@alexcameron89 I went to create an executable test script, but was unable to reproduce the error. Looking at the error some more, I was able to find legacy code in my app that was doing the reconnect and executing the sql again.  Thanks for your help!
