### ISSUE TITLE
create_association doesn't insert foreign key to database

### ISSUE THREAD

**Issue by willnet** [rails/rails#29219]
`create_association` method defined by `has_one` insert association to database without foreigh key.

```ruby
class Post < ActiveRecord::Base
  has_one :comment
end

class Comment < ActiveRecord::Base
  belongs_to :post
end

post = Post.new
comment = post.create_comment
comment.post_id #=> same as post.id
comment.reload.post_id #=> nil
```

### Steps to reproduce

[executable test case](https://gist.github.com/willnet/8974c15a876ccb8d544ded5c4b714fda)

### Expected behavior

```
comment.reload.post_id #=> same as post.id
```

### Actual behavior

```
comment.reload.post_id #=> nil
```

### System configuration
**Rails version**:
master, 5.1.1
**Ruby version**:
2.4.1

**Comment by sevenseacat** [comment]
well `post.id` will be nil, if `post = Post.new`, so this seems logical that it stays nil after a reload.

**Comment by alexcameron89** [comment]
I [updated the script](https://gist.github.com/0aa4d3aa04150102dcdeee962d0c8345) to try doing something similar with `build_comment` and then `comment.save` which works. If that works, I'd expect this to work as well.

With both, a comment and a post are saved to the database. With `create_comment`, both are saved with default values, so the `post_id` is not saved to the database for the comment:
```
SQL (0.0ms)  INSERT INTO "posts" DEFAULT VALUES
Comment Load (0.1ms)  SELECT  "comments".* FROM "comments" WHERE "comments"."post_id" = ? LIMIT ?  [["post_id", 2], ["LIMIT", 1]]
SQL (0.0ms)  INSERT INTO "comments" DEFAULT VALUES
```
*Note: This can be caught by passing a `null: false` option on the `post_id` column for comments*

With `build_comment` and `save`, the `post` is created with default values and its `id` is used in the `comment`:
```
SQL (0.0ms)  INSERT INTO "posts" DEFAULT VALUES
SQL (0.0ms)  INSERT INTO "comments" ("post_id") VALUES (?)  [["post_id", 1]]
```

**Comment by cpg** [comment]
I had a similar situation today after an app upgrade to 5.1.

We have a polymorphic type (Note) used for notes that users do. In User, I do have a `has_many :notes, as: :notable, dependent: :destroy` and in Note, I have `belongs_to :user` association. User notes are by far the most common and there is always a user associated with a note no matter what, hence the user_id field/index.

When doing `@user.notes.create(...)` the user_id field is no longer set in Rails 5.1 (it was before the upgrade) and I think it may be a similar or same instance of this bug.

**Comment by willnet** [comment]
I tried [this script](https://gist.github.com/anonymous/0aa4d3aa04150102dcdeee962d0c8345) with Active Record 4.1.0, 4.2.0, 5.0.0, and it displayed same behavior.

**Comment by willnet** [comment]
[I changed from has_one to has_many](https://gist.github.com/willnet/b52ff9348dcd31e487eac155aafdd37a)
, so `post.comments.create` raise error `ActiveRecord::RecordNotSaved: You cannot call create unless the parent is saved`.

**Comment by syguer** [comment]
```
post = Post.new
```

`post` looks not be saved, so foreign_key being nil is sure.
What is your expecting value of foreign_key_id?
Or Do you expect `create_association` should save parent?

**Comment by alexcameron89** [comment]
> I changed from has_one to has_many
, so post.comments.create raise error ActiveRecord::RecordNotSaved: You cannot call create unless the parent is saved.

@willnet I opened #29392 so that `post.create_comment` would do the same. Since `:has_many` expects that behavior, I think it's reasonable to say the same for `:has_one`.
