### ISSUE TITLE
make activejob logging configurable

### ISSUE THREAD

**Issue by celesteking** [rails/rails#29224]
There should be a way to scrap the default log subscriber for activejob and provide a custom one.
Currently, `ActiveJob::Logging::LogSubscriber.attach_to :active_job` is hard-coded, which requires monkey-patching to make custom logging work.
Thanks.

**Comment by alexcameron89** [comment]
Thank you for the issue, but we don't take feature requests in the issue tracker. You can post about it to the [rubyonrails-core@googlegroups.com](rubyonrails-core@googlegroups.com) mailing list for further discussion, or feel free to open a PR to with the changes you're proposing.

**Comment by rafaelfranca** [comment]
If you interested on implementing this the way I see this going is to add a `deattach` method on the subscriber so you could attach a new one later.
