### ISSUE TITLE
REQ: allow passing initial capacity into ActiveSupport::SafeBuffer constructor

### ISSUE THREAD

**Issue by kikonen** [rails/rails#29236]
Would be useful to be able to pass initial capacity for ActiveSupport::SafeBuffer constructor. This is based into  statistics I collected in app I'm developing. Most of the time, generated content for tags is not fitting into ruby string's magical 23 char limit, thus triggering realloc. Specifying capacity could avoid that (assuming of course that "capacity: 55" could be specified as constant to avoid realloc due to extra opt Hash passing...).

```ruby
sb = ActiveSupport::SafeBuffer('', capacity: 55)
```

### System configuration
**Rails version**:
5.1.1

**Ruby version**:
2.4.1

**Comment by matthewd** [comment]
It doesn't seem easy to do this without adding extra allocations to `some_string.html_safe`. If you can see a sufficiently-palatable option that I'm missing, please do open a PR.
