### ISSUE TITLE
System test generator for namespaced test not going to the correct location

### ISSUE THREAD

**Issue by cheeseweasel** [rails/rails#29247]
### Steps to reproduce
````
rails generate system_test admin/dashboard
````

### Expected behavior
I would expect the test to end up in `/test/system/admin/dashboard`

### Actual behavior
The test ends up in `/test/system/dashboards`

The namespace looks right - `Admin::DashboardsTest` (well apart from the fact that I don't think it should be pluralizing the name, but that's a separate issue)

Apologies if this is intentional, it just was not what I expected.

### System configuration
**Rails version**: 5.1.1

**Ruby version**: 2.4.1

**Comment by y-yagi** [comment]
Thanks for the report. I think this is not expected behavior. I will try to fix.
