### ISSUE TITLE
Migrations generated in a directory with "future" migrations are also in the future and are not timestamps

### ISSUE THREAD

**Issue by musicmage4114** [rails/rails#29254]
When using `rails generate migration`, if the timestamp of the "most recent" migration is in the future, any further generated migrations will have a "timestamp" that is actually the integer value of the timestamp + 1.

#### /db/migrate/
* 20170528053546_past_migration.rb

```ruby
Time.now.utc #=> 2017-05-28 05:35:59 UTC
rails generate migration FutureMigration

    #=> create db/migrate/20170528053559_future_migration.rb

#rename to '29990528053559_future_migration.rb' => Still a valid timestamp, just in the future.
```

#### /db/migrate/
* 20170528053546_past_migration.rb
* 29990528053555_future_migration.rb

```ruby
Time.now.utc #=> 2017-05-28 05:42:32 UTC
rails generate migration PresentMigration
```

#### /db/migrate/
* 20170528053546_past_migration.rb
* 20170528054232_present_migration.rb
* 29990528053559_future_migration.rb

#### /db/migrate/
* 20170528053546_past_migration.rb
* 29990528053559_future_migration.rb
* 29990528053560_present_migration.rb

```ruby
Time.now.utc #=> 2017-05-28 06:22:34 UTC
rails generate migration AnotherMigration
```

#### /db/migrate/
* 20170528053546_past_migration.rb
* 29990528053559_future_migration.rb
* 29990528053560_present_migration.rb
* 29990528053561_another_migration.rb #=> Not a valid timestamp.

### System configuration
**Rails version**: 5.1.1

**Ruby version**: ruby 2.3.3p222 (2016-11-21 revision 56859) [i386-mingw32]

**Comment by matthewd** [comment]
Thanks, but this behaviour is expected and by design.
