### ISSUE TITLE
Migrations removing "using: :btree" from indexes

### ISSUE THREAD

**Issue by vinistock** [rails/rails#29269]
After upgrading to rails 5.1.1 I noticed a different behavior in migrations. I'm not sure if this is an intentional change or a bug. Let me know if not applicable or if you need more information.

If I run any migration (say for instance create a new table or add a column), it removes every occurrence of "using: :btree" from my schema's indexes. It also changes the indentation a little (removes or adds blank spaces everywhere).

Reverting my rails version back to 5.0.2 fixes this, and I'm able to run migrations normally.

### Steps to reproduce

Create a migration ```rails g migration create_table```
Run the migration ```rake db:migrate```

### Expected behavior
Changes in schema.rb should only be: schema version and the lines defining the new table

### Actual behavior
The entire schema is changed, removing the option ```using: :btree``` from indexes. Blank spaces are also added or removed pretty much everywhere in the schema.

### System configuration
**Rails version**: 5.1.1
**Ruby version**: 2.4.1
**OS**: Ubuntu 16.04

**Comment by matthewd** [comment]
https://github.com/rails/rails/pull/27981
