### ISSUE TITLE
Flash messages become nil on redirection

### ISSUE THREAD

**Issue by Sohair63** [rails/rails#29267]
This is the problem that I start facing of HTML request Format. After:
- `redirect_to some_path, notice: 'some message'`

UI does not show any alert or notice.
- I have tried flash.now flash.keep and flash[:notice], nothing helped me.

Note that: Flash messages are working when I request in JS format and reload my flash/messages partial in `.js.erb` file.

### System configuration
**Rails 5.1.1**
**Ruby 2.4.1**

**Comment by matthewd** [comment]
Please use the mailing list or StackOverflow for questions/help, where a wider community will be able to help you. We reserve the issues tracker for issues only.

**Comment by Silex** [comment]
@Sohair63: I have the same problem. Did you manage to fix it? Rails 5.1.2
