### ISSUE TITLE
Strict CSP policy support on error pages

### ISSUE THREAD

**Issue by renchap** [rails/rails#29260]
For more informations and context about CSP: https://csp.withgoogle.com/docs/strict-csp.html

I have a quite strict CSP header on my website, using the [secureheaders](https://github.com/twitter/secureheaders) gem:

```default-src 'self';
base-uri 'self';
block-all-mixed-content;
child-src 'self' blob: localhost:8080;
connect-src 'self' ws://localhost:8080 http://localhost:8080 ws://localhost:3000;
font-src 'self' data: localhost:8080;
form-action 'self';
frame-ancestors 'none';
img-src 'self' www.google-analytics.com data: blob: localhost:8080;
object-src 'none';
script-src 'self' www.google-analytics.com localhost:8080 'nonce-devOnly' 'unsafe-eval';
style-src 'self' fonts.googleapis.com 'nonce-devOnly'
```

On Rails error page, the CSP header is sent and this breaks the page because of inline script and style.

I do not want to remove my CSP policy in development, as it allows me to catch errors that would occur in production.

I see multiple ways to fix this:
- scripts and styles are moved to external files served with other Rails assets, so they are allowed by the policy (does not seem easy to do)
- There is a way to set a nonce, and the nonce is added to the inline `<script>` & `<style>` tags, all CSS is moved to `<style>` tags, and `on...` attributes are no longer used. This is the cleaner solution, but might require quite a lot of work. I detailed this approach here: https://github.com/rails/web-console/issues/242#issuecomment-304523182
- There is a callback called when the error page is displayed, allowing a block to be called where you can call `append_content_security_policy_directives` to allow inline styles/scripts (see https://github.com/twitter/secureheaders/blob/master/docs/per_action_configuration.md). This is not ideal as it means the CSP policy is changed for this page and might no longer catch errors that would occur in production, but `web-console` should not be a permanent part of this page.

CSP support is now in all major browsers and a lot of websites are starting to implement it with strict policies. I think Rails should support a strict policy in development.
I know there have been several unfinished efforts to move CSP handling into Rails, this is related but not exactly the same.

**Comment by matthewd** [comment]
Surely the simplest option would be to omit the CSP in development *on error responses*.

Otherwise your first suggestion sounds like the easiest to me.

Please feel free to look into it; I'm giving this a close because this is a feature request, and we reserve the issue tracker for issues only.

**Comment by renchap** [comment]
Is it any way to have a `before_action` executed when an error response occurs? Disabling CSP on those is indeed a solution.

**Comment by matthewd** [comment]
I imagine the easiest option would be to move the [SecureHeaders middleware](https://github.com/twitter/secureheaders/blob/0966fb9088c93453bb97fa77f5f2531cd9fa0055/lib/secure_headers/railtie.rb#L13) down the stack, so it comes after the error handlers.

**Comment by guilleiguaran** [comment]
I've tested this with our new CSP DSL and is working fine, the unique thing that is not working is the <% console %> helper that is intended to be placed in any view.
