### ISSUE TITLE
Security: Remove all traces of therubyracer from Rails

### ISSUE THREAD

**Issue by SamSaffron** [rails/rails#29276]
therubyracer is a relic, it depends on an ancient version of v8 that has multiple known security vulnerabilities 

https://github.com/cowboyd/therubyracer/blob/master/therubyracer.gemspec#L20 

In particular this is the equivalent of shipping a dependency to Chrome version 31.

Chrome 31 was released 2013-11-12

All places that talk about therubyracer or include it in templates should be replaced with mini_racer that depends on the most recent version of v8.

**Comment by SamSaffron** [comment]
Only 4 spots, so changing this should be fairly easy:

https://github.com/rails/rails/search?utf8=%E2%9C%93&q=therubyracer&type=

**Comment by maclover7** [comment]
@SamSaffron Can you open a PR, and then we can continue the discussion there? Thanks!
