### ISSUE TITLE
Contradicting documentation regarding `skip_before_action :verify_authenticity_token`

### ISSUE THREAD

**Issue by jfragoulis** [rails/rails#29284]
In 5.1 `ActionController.verify_authenticity_token` has become private, hence adding  `skip_before_action :verify_authenticity_token` in the `ApplicationController` throws:

```
ArgumentError: Before process_action callback :verify_authenticity_token has not been defined
```

The [documentation](https://github.com/rails/rails/blob/master/actionpack/lib/action_controller/metal/request_forgery_protection.rb#L103) states otherwise.

**Comment by matthewd** [comment]
It sounds more like you haven't called `protect_from_forgery`.

Please use the mailing list or StackOverflow for questions/help, where a wider community will be able to help you. We reserve the issues tracker for issues only.

**Comment by jfragoulis** [comment]
Sorry, I used github since I think it is a source code documentation issue.
