### ISSUE TITLE
PG::AmbiguousColumn: ERROR:  column reference "name" is ambiguous

### ISSUE THREAD

**Issue by sinscary** [rails/rails#29283]
### Steps to reproduce
I am having three tables locations, accounts, states. locations and states both have column 'name'. I am running this query to get all the locations

`@locations = @account.locations.includes(:state)`
I am using `ilike` to find all the matching locations.

`@locations = @locations.where("name ilike ?", "%params[:search]%")`

Now the issue is whenever I enter a name with '.' in it, e.g. "google inc.", it returns this error `PG::AmbiguousColumn: ERROR:  column reference "name" is ambiguous`

I know I haven't specified the table name before the column name in the second query so Postgres is confused which `name` to use. But my doubt is if that's the case then why it's not giving this error for all the params which don't have a '.' in it. I have tried with all other special characters and query works fine. Only for the names with a '.' are getting this error.

### Expected behavior
`@locations = @locations.where("name ilike ?", "%params[:search]%")`
returning locations, so it should also return all the locations if any matches the name with '.'  in it.

### Actual behavior
Its returning this error `PG::AmbiguousColumn: ERROR:  column reference "name" is ambiguous`

### System configuration
**Rails version**: 4.0

**Ruby version**: 2.1.5

**Comment by luispcosta** [comment]
Can you past here the full SQL generated from the query and your schema definition?

**Comment by sinscary** [comment]
Here is the sql generated 

`
 SELECT "locations"."id" AS t0_r0, "locations"."name" AS t0_r1, "locations"."street" AS t0_r2, "locations"."city" AS t0_r3, "locations"."postal_code" AS t0_r4, "locations"."phone" AS t0_r5,  "states"."id" AS t1_r0, "states"."name" AS t1_r1, "states"."iso" AS t1_r2, "states"."updated_at" AS t1_r3, "states"."created_at" AS t1_r4 FROM "locations" LEFT OUTER JOIN "states" ON "states"."id" = "locations"."state_id" WHERE "locations"."account_id" = $1 AND (name ilike '%The.%')  [["account_id", 1]]
`

**Comment by luispcosta** [comment]
Can you try this:

`@locations = @locations.where("locations.name ilike ?", "%params[:search]%")`

**Comment by sinscary** [comment]
It works fine.

**Comment by sinscary** [comment]
but my question is, why its happening when there is no dot in my string. And its not necessary for dot to be in end, if its something like this "Th.e", it gives error. And without dot it works fine, evenif tabel name is not specified

**Comment by sinscary** [comment]
@alexcameron89 sorry, saw this today, yeah sure i will create one.

**Comment by savayg** [comment]
reproducible bug script:

https://gist.github.com/savayg/18b5109d8fd72815f01a02f31371b24f

**Comment by kamipo** [comment]
This is not happend in 5.0 and 4.0 is no longer supported.
