### ISSUE TITLE
Reformat implicit render exception

### ISSUE THREAD

**Issue by maclover7** [rails/rails#29280]
We want to change how we render our big implicit rendering exception, in order to make it more approachable for users. Below are the requested changes to the exception handling :)

### Requested changes

- [ ] Create a new error subclass of `ActionController:: ActionControllerError ` for the error raised [here](https://github.com/rails/rails/blob/master/actionpack/lib/action_controller/metal/implicit_render.rb#L53), with naming of your choice. Possible candidates are `ActionController::MissingExactTemplate` / `ActionController::MissingExactTemplate`.
- [ ] Turn the [long exception message](https://github.com/rails/rails/blob/master/actionpack/lib/action_controller/metal/implicit_render.rb#L42-L51) into a custom HTML template, similar to how we do it [here](https://github.com/rails/rails/blob/master/actionpack/lib/action_dispatch/middleware/exception_wrapper.rb#L27) and [here](https://github.com/rails/rails/blob/master/actionpack/lib/action_dispatch/middleware/templates/rescues/missing_template.html.erb).
- [ ] Submit a PR with the changes!

**Comment by iaptsiauri** [comment]
@maclover7 Is this issue still open, I would like to give it a shot

**Comment by prog1dev** [comment]
@iaptsiauri @vinistock Are you still working on this issue?

**Comment by vinistock** [comment]
@prog1dev I'm available for helping and doing more work on it, but I'm still not sure if the template on the current PR meets the expectations.

**Comment by akshaysharma096** [comment]
Hey guys, if anyone is not working on this issue, I would like to work. Let me know if it's okay.

**Comment by vinistock** [comment]
@akshaysharma096 Hey. I believe my pull request for this is about done, but I'm still waiting on feedback / reviews. If any other changes are needed, I'm still available to do work and fully complete it.

**Comment by akshaysharma096** [comment]
@vinistock no issues, please carry on!
