### ISSUE TITLE
Association Extensions Problem

### ISSUE THREAD

**Issue by cwheart** [rails/rails#29295]
```
class User < ApplicationRecord
  has_many :articles do
    def build(attributes = {})
      puts 'custom_build'
      super(attributes)
    end

    def custom_method
      puts 'custom_method'
    end
  end
end

class Article < ApplicationRecord
  belongs_to :user
end
```

I have two class such as above.
When i call `User.last.articles.build` there is nothing output
But if i call 'User.last.articles.custom_method'. This will output `custom_method`

If i call 'User.last.articles.build' after 'User.last.articles.custom_method'. I can get `custom_method` and `custom_build` 

I found this problem with Rails-5.1.1 and Rails-5.0.3

**Comment by kamipo** [comment]
Fixed in #29098.
