### ISSUE TITLE
#average, #sum method do not limit number of activerecord queries

### ISSUE THREAD

**Issue by olttwa** [rails/rails#29300]
### Steps to reproduce
Samplemodel.where(column: any_value).order(updated_at::desc).limit(any_number).sum(:any_column)

### Expected behavior
This should give sum of `any_number` of matching records in the activerecord query.

### Actual behavior
This instead returns sum of all the matching records in the activerecord query. It ignores the limit altogether.

### System configuration
**Rails version**: 4.2.8

**Ruby version**: 2.3.0

**Comment by alexcameron89** [comment]
Hey @olttwa, this is a SQL limitation, but you can achieve what you're wanting [through a subquery](https://gist.github.com/7148650310e3ccea5df3f3d23b16f6e9). Also check out https://github.com/rails/rails/issues/15003 for additional context.
