### ISSUE TITLE
rails dev:cache failed to restart the Rails server with custom pid file path

### ISSUE THREAD

**Issue by ranmocy** [rails/rails#29306]
### Steps to reproduce
1. Start rails server with a custom pid file: `rails s -P tmp/pids/dev.pid`.
2. Toggle dev cache: `rails dev:cache`.

### Expected behavior
Rails server should be restarted successfully.

### Actual behavior
Restarting failed. Log:
```
=> Booting Puma
=> Rails 5.1.1 application starting in development on http://localhost:3000
=> Run `rails server -h` for more startup options
Puma starting in single mode...
* Version 3.8.2 (ruby 2.3.3-p222), codename: Sassy Salamander
* Min threads: 5, max threads: 5
* Environment: development
* Listening on tcp://0.0.0.0:3000
Use Ctrl-C to stop
* Restarting...
=> Booting Puma
=> Rails 5.1.1 application starting in development on http://localhost:3000
=> Run `rails server -h` for more startup options
A server is already running. Check /tmp/rails-test/tmp/pids/dev.pid.
Exiting
```

### System configuration
**Rails version**: Rails 5.1.1

**Ruby version**: Ruby 2.3.3

### Potential Reason
1. The pid file path is hard coded in [dev_caching.rb](https://github.com/rails/rails/blob/92703a9ea5d8b96f30e0b706b801c9185ef14f0e/railties/lib/rails/dev_caching.rb#L20) as `"tmp/pids/server.pid"`
2. When restarting rails with Puma, it won't remove the pid file it generated.

**Comment by skunkworker** [comment]
Doing a search for "tmp/pids/server.pid" I can find that it is being hardcoded multiple places - [search](https://github.com/rails/rails/search?utf8=%E2%9C%93&q=%22tmp%2Fpids%2Fserver.pid%22&type=), even though `server_command.rb` has that set to be the default location, it allows for other settings.

Is there a reason why a disparity exists?

**Comment by prathamesh-sonpatki** [comment]
Looking into this.

**Comment by y-yagi** [comment]
@prathamesh-sonpatki Are you working on this? If not, I will fix.

**Comment by prathamesh-sonpatki** [comment]
@y-yagi No, I am not working on it, feel free to take a stab at it, thanks :)
