### ISSUE TITLE
ActiveRecord::Base.all method behaves incorrectly in named scope

### ISSUE THREAD

**Issue by kuzukuzu** [rails/rails#29310]
`ActiveRecord::Base.all` do not returns all records in named scope.

### Steps to reproduce

I'll show you a tiny example below.

### Expected behavior
```
class User < ActiveRecord::Base
  # do nothing scope
  scope :not_scoping, -> { all }

  # this scope reset scoping
  scope :reset_scoping, -> { User.all }
end

10.times { User.create }
users = User.where(id: [1, 2, 3])

users.not_scoping # => user 1, 2, 3
users.reset_scoping # => user 1, 2, 3, 4, 5, 6, 7, 8, 9, 10
```

expect `reset_scoping` to reset scoping.

### Actual behavior
```
class User < ActiveRecord::Base
  # do nothing scope
  scope :not_scoping, -> { all }

  # this scope reset scoping
  scope :reset_scoping, -> { User.all }
end

10.times { User.create }
users = User.where(id: [1, 2, 3])

users.not_scoping # => user 1, 2, 3
users.reset_scoping # => user 1, 2, 3
```

`reset_scoping` do not reset scoping.

### System configuration
**Rails version**: 5.0.0

**Ruby version**: 2.3.1

**Comment by alexcameron89** [comment]
Hey @kuzukuzu, this is expected. The correct way to reset the scoping is through [unscoped](http://api.rubyonrails.org/classes/ActiveRecord/Scoping/Default/ClassMethods.html#method-i-unscoped).

Here's an [example script](https://gist.github.com/9504e481c612d6ee6b924ae6b263fbee) using your code above.
