### ISSUE TITLE
Assets on the precompile list compiling on first request

### ISSUE THREAD

**Issue by camertron** [rails/rails#29319]
### Steps to reproduce
Our application has quite a few assets on the precompile list that used to be compiled on-demand if the current page specifically asked for them. As of Rails 4.2, sprockets 3.7, it appears all assets on the precompile list are precompiled on the first request, which slows down the first request by an incredible amount. We used to be able to make the first request in ~30 seconds. It now takes ~10 minutes. Did this behavior intentionally change as of sprockets 3?

### Expected behavior
Assets on the precompile list should not all be compiled on the first request.

### System configuration
**Rails version**: 4.2.8
**Ruby version**: 2.4.1

**Comment by henrik** [comment]
We've also seen some very slow first requests (minutes) in dev after upgrading from Rails 4.1 to 4.2; this seems like a reasonable explanation. Rails 4.2.8, Ruby 2.2.5.

**Comment by camertron** [comment]
@henrik We've mitigated the slowdown somewhat by preloading assets in parallel when the app boots. Preloading effectively compiles all the assets on the precompile list and caches them in the sprockets cache. [Here's the code we're using](https://gist.github.com/camertron/6a43b707efafb0922b4e06d6a556f4c5). You can give it a try by dropping it into your lib/ directory and modifying config/environments/development.rb like so:

```ruby
require './lib/asset_preloader'

MyApp::Application.configure do
  ... lots of other stuff ...

  config.after_initialize do
    if Rails.const_defined?(:Server)
      AssetPreloader.preload!
      ActiveRecord::Base.connection.reconnect!
    end
  end
end
```

You'll also need to add a dependency on the [parallel](https://github.com/grosser/parallel) gem.

One final thing: switching git branches tends to mess up the sprockets cache, so I would suggest blowing away your tmp/sprockets directory whenever you change git branches.

**Comment by henrik** [comment]
@camertron Thank you, really appreciate it! We'll look into this.

**Comment by joakimk** [comment]
Hello @camertron. I work with @henrik.

Your workaround works just fine for us. I've also added code to remove incompatible assets.

This is our version:

```ruby
  # Speeds up initial page load in dev by preloading assets.
  # From: https://github.com/rails/rails/issues/29319#issuecomment-307542639
  require "./lib/dev_asset_preloader"
  config.after_initialize do
    RailsVersions.revisit_this_on_rails_5

    if ENV["RUNNING_WEB_SERVER"]
      assets_cache_path = "#{Rails.root}/tmp/cache/assets"

      if File.ctime(assets_cache_path) < Time.parse("2017-06-13 12:00")
        puts "Removing assets not generated by DevAssetPreloader. This ensures Rails will be able to use the assets generated by DevAssetPreloader instead of trying to generate all assets during the request."
        system("rm", "-rf", assets_cache_path)
      end

      DevAssetPreloader.preload!
      ActiveRecord::Base.connection.reconnect!
    end
  end
```

**Comment by rafaelfranca** [comment]
That behavior is by design. See https://github.com/rails/sprockets-rails/issues/352#issuecomment-223639405

**Comment by henrik** [comment]
Thank you, @rafaelfranca. So this is what I did instead, based on that other issue.

Added to the config block in `config/environments/development.rb`:

```
# Speed up boot enormously (by minutes) by not verifying precompiled assets.
# https://github.com/rails/sprockets-rails/issues/352
# https://github.com/rails/rails/issues/29319
config.assets.check_precompiled_asset = false
```

**Comment by joakimk** [comment]
We ended up restoring @camertron's patch. We still saw slowness with `check_precompiled_asset`. Our impression was that this was due to assets being generated just in time, so it was e.g. slow when switching between a "public" section and an "admin" section of the same app, with different assets. We have not investigated very thoroughly. / @joakimk and @henrik

**Comment by joakimk** [comment]
We’ve seen some indications that development and test assets cache is incompatible.

In case it’s helpful to someone we’re currently trying this:

```
config.assets.configure do |env|
  env.cache = ActiveSupport::Cache.lookup_store(:file_store, “#{Rails.root}/tmp/cache/#{Rails.env}-assets”)
end
```

**Comment by camertron** [comment]
Cool, thanks @joakimk :)
