### ISSUE TITLE
model.collection_association returns different object on every call in Rails 5.0.3

### ISSUE THREAD

**Issue by abezzub** [rails/rails#29316]
### Steps to reproduce

Run this in rails console:
```
user = User.new
# some_objects is a has_many association
puts user.some_objects.object_id
puts user.some_objects.object_id
```
### Expected behavior
On Rails 5.0.2 above script prints the same object id twice:
```
70102938308920
70102938308920
```

### Actual behavior
On Rails 5.0.3 above script prints different object ids:
```
70118579979780
70118579771100
```

### System configuration
**Rails version**: 5.0.3

**Ruby version**: 2.4.1p111

**Comment by eileencodes** [comment]
Bisected to find this was fixed on master and 5-1-stable, and 5-0-stable by https://github.com/rails/rails/commit/c86a9e1096de3ff290b51e437daa77d5647d88ea

The next release of Rails 5.0 (5.0.4) and 5.1 (5.1.2) respectively. Thanks for reporting!

**Comment by abezzub** [comment]
thanks!
