### ISSUE TITLE
Array.instance_methods different for jRuby inside Rails

### ISSUE THREAD

**Issue by straydogstudio** [rails/rails#29329]
### Steps to reproduce

Using Docker:

```
docker run -it --rm -p 3000:3000 --name arraytest jruby /bin/bash
# gem install rails
# gem install listen
# rails new arraytest -O
# cd arraytest
# echo "gem 'listen', group: :development" >> Gemfile
# bundle exec rails c
irb > Array.instance_methods.select {|m| m =~ /each/}
irb > exit
# irb
irb > Array.instance_methods.select {|m| m =~ /each/}
```

To check MRI, replace the jruby image with ruby. 

### Expected behavior

Whether in our out of Rails, using MRI or jRuby, Array.instance_methods should return the same thing.

### Actual behavior

When using jRuby 9 inside Rails 5.0, Array.instance_methods doesn't have each_cons, each_entry, each_with_index, each_with_object, as well as several other methods. They are present with MRI. Outside Rails they are present in jRuby. 

This is the difference, which may contain some artifacts due to other required gem changes between MRI and jRuby:

```ruby
 [:all?, :byebug, :chunk, :chunk_while, :collect_concat, :detect, :each_cons, :each_entry, :each_with_index, :each_with_object, :entries, :exclude?, :find, :find_all, :flat_map, :grep, :grep_v, :group_by, :index_by, :inject, :lazy, :many?, :max_by, :member?, :min_by, :minmax, :minmax_by, :none?, :one?, :partition, :pluck, :reduce, :singleton_method, :slice_after, :slice_before, :slice_when, :sort_by, :sum, :to_h, :to_ruby, :to_set]
```

### System configuration
**Rails version**: 5.0.3 or 5.1.1

**Ruby version**: jRuby 9.1.10.0, MRI 2.4.1p111

### Other

Found because the Axlsx gem uses Array.instance_methods to delegate methods. When used inside Rails 5.0 with jRuby it fails. See https://github.com/randym/axlsx/issues/533

**Comment by matthewd** [comment]
We'll consider a PR if we seem to be doing something demonstrably wrong, but by default, if it's working on MRI, it sounds like a JRuby issue.
