### ISSUE TITLE
ActiveRecord Relations in 4.0.x not working when used in subqueries, did in 3.2

### ISSUE THREAD

**Issue by jasonperrone** [rails/rails#29328]
### Steps to reproduce
So, in 3.2 I have a relation returned by a scope, where clause, what have you. The relation consists of full objects. So, MyObject.my_scope returns a relation of MyObjects. 

So let's say I put my relation into a variable:
my_object_relation = MyObject.where('1=1')

If I then used that relation as a subquery like
MyOtherObject.where('my_object_id in (?)',my_object_relation)

Rails 3.2 correctly generated the SQL to be like "select * from my_other_objects where my_object_id in (select id from my_objects)"

But Rails 4 does this:  "select * from my_other_objects where my_object_id in (select * from my_objects)". That's an invalid SQL and gives the error "Operand should contain 1 column(s)".

Notice what I am saying is that in Rails 4, the SQL incorrectly put select * in the subquery instead of select id the way Rails 3.2 did. Sure, I can do MyOtherObject.where('my_object_id in (?)',my_object_relation.map(&:id)
but man that seems like a step backwards. I rely on this behavior in many places in the code and I'd hate to have to track them all down.

### System configuration
**Rails version**: 4.0.13

**Ruby version**: 2.3.3

**Comment by rafaelfranca** [comment]
Rails 4 is not under maintenance anymore. If what you want is to only select the id your relation should do it.

**Comment by jasonperrone** [comment]
Ok. I appreciate the response.
