### ISSUE TITLE
Order of query results is inconsistent

### ISSUE THREAD

**Issue by jvrsgsty** [rails/rails#29363]
### Steps to reproduce
I attempted to reproduce my production bug unsuccessfully here: 
https://gist.github.com/jvrsgsty/77ffbaae972a7b1b56cab7c80eba09da

Yet, the test case yields insight into the source of the bug I am seeing in production. 

The query I am creating in line 53 gets evaluated to SQL without an "order by" clause as soon as I execute line 55. Further evaluation of lines 56 and 57 yields no resulting SQL query (I am assuming the result of the query is cached somewhere in memory to save I/O access to disk). Thus, `query.last` gets evaluated the last record of a query with no "order by" clause. 

Problem is, `query.last` would be evaluated as the last record returned by the query **without** an "order by" clause, whereas `User.where("email = '#{email}'").last` does issue an SQL statement **with** an "order by" clause. In this case, I was unable to generate a use case where the last result of the query without the "order by" clause differed from the last result of the query with the "order by" clause, yet this **could** happen for a larger database (as a matter of fact, it happens in our production database). 

### Expected behavior
A bit different from the test case I submitted, since my production app is more complex than this simple example. 

In production, I would expect the following code to work as per the Rails documentation. 
```ruby
params[:email].downcase!
# busqueda is evaluated without an "order by" clause
busqueda = Persona.where("email = '#{params[:email]}'")
if !busqueda.nil? && busqueda.length > 0
  #Expected persona with the largest ID. Got a Persona with a smaller id
  id = busqueda.last.id 
end

# If I were to run the following line, it would evaluate to false
# The right part would issue a query with an "order by" clause
# whereas the left side would take the last record returned by the query without the "order by" clause
Persona.where("email = '#{params[:email]}'").last.id == busqueda.last.id
```
to yield the last record on the query

### Actual behavior
Instead, I am getting the last record returned by the query without the "order by" clause and not the `last` record as specified in http://guides.rubyonrails.org/active_record_querying.html#last

### System configuration
**Rails version**: 5.0.0.1

**Ruby version**: 2.3.1

**Comment by kamipo** [comment]
This is because `busqueda.length` causes `Relation#load` without ordering then `busqueda.last` refers loaded `records`. You have two choices to prevent the issue.

* Use `busqueda.count` instead of `busqueda.length`.
* Use `busqueda.reset` before `busqueda.last` if `busqueda.loaded?` is true.

**Comment by acangiano** [comment]
I know this is just an example, but as a side note, watch out for that embedded input in your where clause. It makes your app vulnerable to SQL injections. You can use:

`busqueda = Persona.where(email: params[:email])`

**Comment by jvrsgsty** [comment]
OK, thanks for the input @acangiano . I did code a bit carelessly there. 

Noted, @kamipo . Isn't this unexpected behaviour, though? At least I wasn't quite expecting it from reading the Rails docs. Another solution that came to my mind was to use `busqueda.count`, which would issue a `select count(*)` query causing `busqueda` to reload upon calling `busqueda.last`, this time with an `order by `clause`.
