### ISSUE TITLE
Minitest: assert_select causes subsequent assert_select after follow_redirect! to fail

### ISSUE THREAD

**Issue by starrychloe** [rails/rails#29367]
### Steps to reproduce
```
  test "should update deal" do
    patch user_deal_url(@user, @deal), params: { deal: { name: @deal.name+'xxx' } }
    # p @response.body
    # p @deal.errors.full_messages
    # puts css_select('#error_explanation')
    # assert_select ".alert", false   # should not have alert
    assert_select "#error_explanation", false   # should not have error
    assert_redirected_to dashboard_url
    follow_redirect!
    # puts css_select('.alert')
    assert_select ".alert", "Deal was successfully updated."   # line 78
  end
```

By uncommenting `assert_select "#error_explanation", false` the test fails, when it should pass either way.

```
Failure:
DealsControllerTest#test_should_update_deal [C:/Users/Chloe/workspace/test/controllers/deals_controller_test.rb:78]:
Expected at least 1 element matching ".alert", found 0..
Expected 0 to be >= 1.
```

### Expected behavior
Testing for a CSS element should not affect subsequent CSS tests, especially ones on another page after the `follow_redirect!`. The test should pass whether the first few `assert_select` are commented or not.

### Actual behavior
The last `assert_select` fails for some reason. 

### System configuration
**Rails version**: 5.0.2

**Ruby version**: ruby 2.3.1p112 (2016-04-26 revision 54768) [x64-mingw32]

**Comment by alexcameron89** [comment]
Hey @starrychloe, can you provide us with a sample application that reproduces the error you're seeing?

**Comment by starrychloe** [comment]
Can't you just put 

    assert_select ".alert", false   # should not have alert

In front of

    follow_redirect!
    assert_select ".alert", "..."

of an existing update test for an existing project you have?

**Comment by Edouard-chin** [comment]
I'm able to reproduce https://gist.github.com/Edouard-chin/8475cbd82d60556f34783c2ee3b754cb

I'll look into it
