### ISSUE TITLE
model w/o primary key defined as association beeing eager loaded is not populated

### ISSUE THREAD

**Issue by disorganizer23** [rails/rails#29374]
### Steps to reproduce
migration:

```
def up
    create_table :institution_hierarchies, id: false do |t|
      t.integer :parent_id, index: true
      t.integer :child_id, index: true
    end
    create table :clients do |t|
      t.integer :institution_id
    end
end

```
models:
```
class InstitutionHierarchy < ActiveRecord::Base
end
```
```
class Client < ActiveRecord::Base
   has_many :institution_hierarchies, foreign_key: :child_id,  primary_key: :institution_id
end
```

reproduce:
  ```
InstitutionHierarchy.create!({child_id: 2, parent_id: 1})
  Client.create!({institution_id: 2})
  puts Client.eager_load(:institution_hierarchies).first.institution_hierarchies.inspect
```

### Expected behavior
The Collection with a single object representing the previously inserted row should be printed

### Actual behavior
An empty collection is printed

### Solution
execute following migration:
```
def change
    add_column :institution_hierarchies, :id, :primary_key
end
```

then execute:

```
puts Client.eager_load(:institution_hierarchies).first.institution_hierarchies.inspect
```

Now the collection contains the desired Object.
I'm not sure if this is in fact a bug or if i'm just missing something, but i could not find any documentation exactly on that topic.

### System configuration
**Rails version**:  4.2.1

**Ruby version**:  2.2.3

**Database**: postgresql 9.5

**Comment by forvoid** [comment]
> Database: postgresql 9.5

:rabbit

**Comment by forvoid** [comment]
👍 


> Ruby version: 2.2.3

💯

**Comment by chopraanmol1** [comment]
@disorganizer23  
Confirm if #30212  solves your problem?

**Comment by mattalat** [comment]
@vipulnsward Sorry to nag, but I opened #43402 to solve this and have not managed to get the attention of someone with Rails write-access. Is there anything I should do to reach out, or is patience the best option? My apologies if you are not the person to ask.

**Comment by ghiculescu** [comment]
Patience is the best option. Core team is pretty busy but they do get to stuff.

**Comment by mattalat** [comment]
Thank you—I just wanted to be sure that I wasn't missing any part of the process.
