### ISSUE TITLE
Update Guide for Upgrading from Rails 4.2 to Rails 5.0 regarding ActionController::Parameters methods

### ISSUE THREAD

**Issue by kacarter** [rails/rails#29376]
The Guide for Upgrading Ruby on Rails, section [3.11 ActionController::Parameters No Longer Inherits from HashWithIndifferentAccess](http://edgeguides.rubyonrails.org/upgrading_ruby_on_rails.html#actioncontroller-parameters-no-longer-inherits-from-hashwithindifferentaccess) under Upgrading from Rails 4.2 to Rails 5.0 states 

> If you are using slice and other methods that depend on being able to read the hash regardless of permitted? you will need to upgrade your application to first permit and then convert to a hash.

but a slice method has been added to [ActionController::Parameters](http://api.rubyonrails.org/v5.0.2/classes/ActionController/Parameters.html#method-i-slice), so this is not always necessary.

I'm unsure how this should be updated exactly, but the current version is misleading.

**Comment by robin850** [comment]
Thanks for reporting ! There's no big deal but would you be willing to send a pull request to fix this ? You can mention another method like `map` for instance.

**Comment by edwardmp** [comment]
@robin850 I've got his. PR submitted.
