### ISSUE TITLE
When creating new application with mysql it gives me older version of rails

### ISSUE THREAD

**Issue by aniketstiwari** [rails/rails#29381]
Creating new application but still giving me older version of rails.I even tried creating multiple project and still getting the older version of rails.I am sharing my Gem file 

I tried creating project using

rails new project -d mysql

source 'https://rubygems.org'

gem 'rails', '4.2.6'
gem 'mysql2', '>= 0.3.13', '< 0.5'
gem 'sass-rails', '~> 5.0'
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 4.1.0'
gem 'jquery-rails'
gem 'turbolinks'
gem 'jbuilder', '~> 2.0'
gem 'sdoc', '~> 0.4.0', group: :doc

group :development, :test do
  gem 'byebug'
end

group :development do
  gem 'web-console', '~> 2.0'
  gem 'spring'
end

**Comment by ferdinandrosario** [comment]
@aniketstiwari  could you plz provide the result of the following commend...
`rails -v` 
when we create a new rails application by default it will take default rails version. Ensure that you have the latest stable rails before create a new application using `gem install rails`...

**Comment by aniketstiwari** [comment]
Okay yeah I got it my default version was Rails 4.2.6 .That is the reason it was taking older version of rails

**Comment by aniketstiwari** [comment]
close
