### ISSUE TITLE
Security Guide should probably mention brakeman

### ISSUE THREAD

**Issue by matildasmeds** [rails/rails#29383]
Rails Security Guide should probably mention [brakeman gem](https://github.com/presidentbeef/brakeman), the static code analysis tool for identifying vulnerabilities - or if other projects of similar standing and utility exist, those as well. 

My personal understanding is that if a Ruby-on-Rails practitioner does just one thing for security, they should brakeman against the instance, but I don't know how others feel about it. Personally I would like to see it even in the first paragraphs of the guide. I can write up a PR too. But would be useful to hear what others think.

**Comment by vipulnsward** [comment]
https://github.com/rails/rails/commit/8426978c54429c28398daca3d14c8b5e52939657
