### ISSUE TITLE
Fix ArgumentError when calling localize with nil

### ISSUE THREAD

**Issue by ebeigarts** [rails/rails#29395]
It would be more user friendly if localize helper didn't throw an exception when calling `localize(nil)`.

For example, if I have `approved_at` column, than can be null, then this code will explode and I have seen 500th error dozen of times in production because some one forgot to add if's.

```
<%= localize @record.approved_at %>
```

So currently the solution is to write `if` checks everywhere or use a custom helper.

```
<%= localize @record.approved_at if @record.approved_at? %>
```

So, I suggest to make `localize` nil aware.

```diff
  def localize(*args)
+   return if args[0].nil?
    I18n.localize(*args)
  end
```

**Comment by vipulnsward** [comment]
You can simply pass a default value to handle nils:

https://github.com/svenfuchs/i18n/blob/master/lib/i18n/backend/base.rb#L64

Moreover, we just delegate localize and provide it as a easy helper, don't think thus is a good place to override its behaviour.
