### ISSUE TITLE
application_record generation does not honor autoload paths

### ISSUE THREAD

**Issue by catmando** [rails/rails#29407]
### Steps to reproduce

add a new directory to autoload paths (i.e. foo_model)
move application_record to this directory
create a new migration
a new copy of application_record will appear in models directory

### Expected behavior

If the constant ApplicationRecord can be found using the normal auto load mechanism then do not regenerate a new blank copy.

### Actual behavior
System seems to thave the path app/models hard coded as the location of application-record

### System configuration
5.0 +
any ruby version

**Comment by catmando** [comment]
FYI work around is to add a file like this:

```ruby
# the presence of this file prevents rails migrations from recreating application_record.rb see https://github.com/rails/rails/issues/29407

require 'some_other_dir/application_record.rb'
```

**Comment by kirs** [comment]
> add a new directory to autoload paths (i.e. foo_model)

Where exactly is that directory located? `app/foo_model`, `foo_model/` or somewhere else?

**Comment by kirs** [comment]
FYI the autoloading guides doesn't recommend using `require` directly: http://guides.rubyonrails.org/autoloading_and_reloading_constants.html#autoloading-and-require

This may break autoloading in your app.

**Comment by rafaelfranca** [comment]
> If the constant ApplicationRecord can be found using the normal auto load mechanism then do not regenerate a new blank copy.

The generators don't have knowledge about autoload paths so there is no way we could detect this case. We could remove the code that generated application record when a migration or model is created and only create it when running `rails app:update`.
