### ISSUE TITLE
current_page? method returns false for engine root path.

### ISSUE THREAD

**Issue by JanBussieck** [rails/rails#29401]
Say I have mounted an engine in my routes file:
```
# routes.rb
  mount MyEngine::Engine => '/my_engine'
```
Then within that engine, the root path points to `/my_engine/`. Similarly `request.path` also returns `/my_engine/`. However `current_page?` assumes that the only path containing a trailing slash is the main apps root path: `/` and hence removes it from all other URL strings passed it.
So that when I am at `/my_engine/`, `current_page?('/my_engine/')` returns `false` even though `request.path` returns `/my_engine/`

[The method line causing this behavior is the following](https://github.com/rails/rails/blob/a72041597e7980a14926eafc09fbcbb9f8b1fd2c/actionview/lib/action_view/helpers/url_helper.rb#L536):
```
url_string.chomp!("/") if url_string.start_with?("/") && url_string != "/"
```
I am proposing to simply check whether the request uri ends with "/":
```
url_string.chomp!("/") if url_string.start_with?("/") && !request_uri.end_with? "/"
```
This would also be a more robust solution should there be other situations where the path returned by `request.path` or `request.full_path` ends with a slash.

I am on **Rails version**: 5.1.1 and **Ruby version**: 2.3.1

**Comment by savroff** [comment]
Get the same issue. 
**Rails version**: 5.1.1
 **Ruby version**: 2.4.0p0 

This is test app:
https://github.com/savroff/current_page_example

**Comment by savroff** [comment]
@JanBussieck problem actually affects not only engines :)
