### ISSUE TITLE
present?/blank? on an ActiveRecord::Relation loads all associated records into memory

### ISSUE THREAD

**Issue by aripollak** [rails/rails#29400]
It looks like this was originally attempted to be fixed in #10539, but that ended up getting reverted and not fixed further. This is something that can very easily trip up any Rails developer. It's not obvious that `present?` or `blank?` (which is very easy to reach for) on a relation/collection will load all matching records into memory, since the other similar methods will run a more optimized query.

### Steps to reproduce

Run this file:

```ruby
begin
  require "bundler/inline"
rescue LoadError => e
  $stderr.puts "Bundler version 1.10 or later is required. Please update your Bundler"
  raise e
end

gemfile(true) do
  source "https://rubygems.org"
  gem "rails", github: "rails/rails"
  gem "arel", github: "rails/arel"
  gem "sqlite3"
end

require "active_record"
require "minitest/autorun"
require "logger"

# This connection will do for database-independent bug reports.
ActiveRecord::Base.establish_connection(adapter: "sqlite3", database: ":memory:")
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :posts, force: true do |t|
  end

  create_table :comments, force: true do |t|
    t.integer :post_id
  end
end

class Post < ActiveRecord::Base
  has_many :comments
end

class Comment < ActiveRecord::Base
  belongs_to :post
end

class BugTest < Minitest::Test
  def test_blank
    post = Post.create!
    puts 'USING BLANK?'
    post.comments.blank?
  end

  def test_empty
    post = Post.create!
    puts 'USING EMPTY?'
    post.comments.empty?
  end
end
```

### Expected behavior
```
USING BLANK?
DEBUG -- :   Comment Exists (0.1ms)  SELECT  1 AS one FROM "comments" WHERE "comments"."post_id" = ? LIMIT ?  [["post_id", 1], ["LIMIT", 1]]
```

### Actual behavior
```
USING BLANK?
DEBUG -- :   Comment Load (0.1ms)  SELECT "comments".* FROM "comments" WHERE "comments"."post_id" = ?  [["post_id", 1]]
```

### System configuration
**Rails version**:
master

**Ruby version**:
2.3.3

**Comment by matthewd** [comment]
To me, the current behaviour seems more likely to be more efficient on average.

In my experience, `collection.present?` generally precedes `collection.each` -- to first output a heading, for example. In that case, treating it as `exists?` would mean an extra query.

And if the caller specifically intends to do a lightweight check before using further Relation-specific methods (as opposed to treating it as a generic Enumerable), it seems reasonable [and clearer] to use `exists?` or `empty?` directly.

**Comment by aripollak** [comment]
@matthewd I agree, but this is about memory, not necessarily performance, specifically about the worst case use of `present?`/`blank?`. If I have a relation with a large underlying set (which you may not realize up front) and just want to know if any of those exist, I'm likely to reach for `present?`/`blank?` since that's what I've been trained to do in Rails/ActiveSupport for any object, and it's not obviously iterating over every record like `each` or `map`. I don't think it should try to perform a potentially catastrophic operation in that case. If you want to optimize out an extra query when you know you'll need the full results, you can still use `.load` on the relation.

**Comment by rafaelfranca** [comment]
@aripollak I could say the same about `present?` If you want to optimize out the memory usage you can still use `.exists?` on the relation. I don't think we should change the behavior of `blank?` and `present?` in a relation. We already provide an API for that. It is also important to us to keep the current api for `present?` and `blank?` to the cases that @matthewd mentioned.

**Comment by nateberkopec** [comment]
> In that case, treating it as exists? would mean an extra query.

This is already how, for example, `count` or `size` works. Up to the developer to know that they should use `load`.

Agree with @jrochkind that the potential downside of an extra `exists?` is waaay less than the downside of loading an entire association that you didn't need.

**Comment by matthewd** [comment]
> This is already how, for example, `count` or `size` works.

Sure, but the theory of the trade-off there is that it's comparatively common to get a count and then do something other than loop over those records; the corresponding theory here is that that's less common on a boolean enquiry.

As noted elsewhere, the [arguably more natural] `any?` takes the other trade-off... is the argument that we shouldn't offer any convenient spelling for this common pattern, or that it's on the wrong method? The theoretical advantage of the current arrangement is that you can operate on an Enumerable collection in an intuitive way, and if you're conscious of this issue and want to address it, you have both alternatives available on methods that'll work just as happily on an Array.

> the potential downside of an extra `exists?` is waaay less than the downside of loading an entire association that you didn't need.

The downside for someone unknowingly misusing the API is higher, yes... but there's a frequency multiplier to factor in too. I allege that `puts "good for you" if records.present?` is far less common than `if records.present?; records.each { .. }; else; puts "nope"; end`, and that the latency cost of the extra query is substantial for everyone, whereas even someone hitting this surprise only has a problem given a non-trivial result set. (That's not "it's okay to be slow for big results", but if we're going to balance minimal surprise impact for someone using an API without understanding its nuances, I lean toward the less-deeply-aware majority, whose pages will be substantially affected by an extra set of DB round-trips.)

Isn't this something Bullet could/should be catching anyway?
