### ISSUE TITLE
database.yml, Only numbers in database name

### ISSUE THREAD

**Issue by stoivo** [rails/rails#29429]
### Steps to reproduce

My database yml file look like this right now.
database.yml
```
development:
  adapter: postgresql
  database: 20170421
  pool: 25
  username: user
  password: pass
  host: localhost
```
When I run 
`rake db:structure:dump` 
I get this runtime error
```
rake aborted!
TypeError: no implicit conversion of Integer into String
/../gems/activerecord-5.1.1/lib/active_record/tasks/postgresql_database_tasks.rb:112:in `exec'
/../gems/activerecord-5.1.1/lib/active_record/tasks/postgresql_database_tasks.rb:112:in `run_cmd'
/../gems/activerecord-5.1.1/lib/active_record/tasks/postgresql_database_tasks.rb:71:in `structure_dump'
/../gems/activerecord-5.1.1/lib/active_record/tasks/database_tasks.rb:217:in `structure_dump'
/../gems/activerecord-5.1.1/lib/active_record/railties/databases.rake:277:in `block (3 levels) in <top (required)>'
Tasks: TOP => db:structure:dump
(See full trace by running task with --trace)
```

### More details I have found
It is due to that database is just numbers. Then it is read as a number. Later on when it is passed on to do the structure dump it uses Kernal.system.
https://github.com/rails/rails/blob/42a80721938453a2ecbba204ce21a0d496756178/activerecord/lib/active_record/tasks/mysql_database_tasks.rb#L150

I could change the name of the database or wrap it in ", but I wanted to see if we could make a nicer solution.

If I change [these](https://github.com/rails/rails/blob/42a80721938453a2ecbba204ce21a0d496756178/activerecord/lib/active_record/tasks/mysql_database_tasks.rb#L8-L10) to 
```ruby 
def initialize(configuration)
  configuration["database"] = configuration["database"].to_s
  @configuration = configuration
end
```
This isn't a nice solution.

### Expected behavior
I Expect it to work as normal.

### Actual behavior
It fails.

### System configuration
**Rails version**: 5.1.1

**Ruby version**: 2.4.1

**Comment by rafaelfranca** [comment]
I think the nicer solution is to pass strings to Rails wrapping the name with quotes. This is how yaml works. If you only put number in the value it will think that number is an integer or float not a string.

We could check the type of the option though so at least we show the users a better error message. 

Maybe change the code to:

```
def initialize(configuration)
  @configuration = configuration
  verify_configuration!
end
```

And implement that `verify_configuration`! method

**Comment by yahonda** [comment]
I'm wondering if Rails should cover database name starting wit number.
even psql client level, database name starting with number needs quote(").


* Only numbers

```sql
postgres=# create database 20170421;
ERROR:  syntax error at or near "20170421"
LINE 1: create database 20170421;
                        ^
postgres=# create database "20170421";
CREATE DATABASE
postgres=#
```

* Starting with number, alphabet character following

```sql
postgres=# create database 1foobar;
ERROR:  syntax error at or near "1"
LINE 1: create database 1foobar;
      ``                  ^
postgres=# create database "1foobar";
CREATE DATABASE
postgres=#



https://www.postgresql.org/docs/9.6/static/sql-syntax-lexical.html

>> 4.1.1. Identifiers and Key Words
>> SQL identifiers and key words must begin with a letter (a-z, but also letters with diacritical marks and non-Latin letters) or an underscore (_). Subsequent characters in an identifier or key word can be letters, underscores, digits (0-9), or dollar signs ($). 

I think as long as quoting database name starting with number in database.yml works, I think it is enough.

**Comment by stoivo** [comment]
Since this is so unimportant I will close this.
