### ISSUE TITLE
Rails 5.1.1.: update_attribute uses wrong column to update record

### ISSUE THREAD

**Issue by alexander-mayr** [rails/rails#29436]
### Steps to reproduce

I have made a small test app here: https://github.com/alexander-mayr/primary_key_test

to reprodue:

![image](https://user-images.githubusercontent.com/5887938/27081683-ce58ea28-5041-11e7-8af1-9fea7e130adf.png)

I tracked the problem down to the dynamically generated method "id_in_database" but couldn't get any further, sorry. This behaviour wasn't there on any other version (back to 4.0)

### Expected behavior
update_attribute should use the correct db column

### Actual behavior
update_attribute seems to use another column as the one defined in the model

### System configuration
**Rails version**: 5.1.1

**Ruby version**: 2.4.1

**Comment by meinac** [comment]
it seems like this is broken since 5.1.0, I can confirm that this is working as expected in 5.0.x, I'll have a look at this today.

**Comment by meinac** [comment]
Thank for reporting this, I've created a pull request to address this issue.

**Comment by alexandermayr** [comment]
great news, thanks alot!

**Comment by eugeneius** [comment]
This is a duplicate of https://github.com/rails/rails/issues/29350, and would be fixed by https://github.com/rails/rails/pull/29378.

**Comment by meinac** [comment]
I should have searched this. This will be fixed by #29378.

**Comment by alexander-mayr** [comment]
thanks guys, will upgrade then with the upcoming release. closing this
