### ISSUE TITLE
destroy link not working

### ISSUE THREAD

**Issue by bishals** [rails/rails#29434]
### Expected behavior
on clicking destroy link confirmation box should have appeared. but that didn't happen.

### Actual behavior
while clicking to destroy link it redirects to show link. I tried everything online. I have all the required gemfiles and application.js also has //=jquery and //=jquery_ujs 
javascript is working on my browser. i also did this: #config.assets.compile = true  
in production.rb but still it has got same issue of redirecting to show link.
I have been stuck in it for long hours already. It would be great if anybody can help me. Thank you.
![git1](https://user-images.githubusercontent.com/24369088/27080573-b281b58e-507b-11e7-92dd-fca04866a3de.JPG)
![git2](https://user-images.githubusercontent.com/24369088/27080574-b2856d1e-507b-11e7-8193-94182d370317.JPG)

### System configuration
**Rails version**:  5.1.1

**Ruby version**: ruby 2.2.6p396

**Comment by adamshen** [comment]
use the url_helper method 'user_path' instead of 'user' after 'Delete'.

This is not an issue, please ask the problem at stackoverflow.

**Comment by bishals** [comment]
I have already tried that as well but didn't work for me. Anyway thanks for trying to help

**Comment by gajendrajena** [comment]
@bishals, Open browser debugger, please check if you are getting javascript error on the page.
Any javascript error would cause this issue.

**Comment by bishals** [comment]
thank you for reply but my javascript is working because when I try it locally it works but when i try from heroku I get that issue.

**Comment by alexcameron89** [comment]
Hey @bishals, please use the mailing list or StackOverflow for questions/help, where a wider community will be able to help you. We reserve the issues tracker for issues only.
