### ISSUE TITLE
Can't use `change` in migration to remove an index in a revertible manner (`remove_index` should accept an options hash, like `add_index`)

### ISSUE THREAD

**Issue by aried3r** [rails/rails#29432]
### Steps to reproduce

I have an index on the `email` column like this (example):
```Ruby
create_table "users", force: :cascade do |t|
  t.string "email", default: "", null: false
  t.index ["email"], name: "index_users_on_email", using: :btree
end
```

When I try to remove this index using `change` I can only do it in a non revertible manner:
```Ruby
class RemoveEmailIndexOnUsers < ActiveRecord::Migration[5.0]
  def change
    remove_index :users, :email
  end
end
```

after running `rails database:migrate` followed by `rails database:rollback`, the diff is the following:
```diff
389c389
<     t.index ["email"], name: "index_users_on_email", unique: true, using: :btree
---
>     t.index ["email"], name: "index_users_on_email", using: :btree
```
### Expected behavior

`remove_index` should accept an options hash to add something like `unique: true` to make migrations using `change` instead of `up` and `down` reversible.

### Actual behavior
Trying to use (note the `unique: true` at the end)
```Ruby
class RemoveEmailIndexOnUsers < ActiveRecord::Migration[5.0]
  def change
    remove_index :users, :email, unique: true
  end
end
```

results in this stack trace after trying to run `rails database:migrate`
```
== 20170613103702 RemoveEmailIndexOnUsers: migrating ==========================
-- remove_index(:users, :email, {:unique=>true})
rake aborted!
StandardError: An error has occurred, this and all later migrations canceled:

wrong number of arguments (given 3, expected 1..2)
/remove_index_bug/db/migrate/20170613103702_remove_email_index_on_users.rb:3:in `change'
-e:1:in `<main>'
ArgumentError: wrong number of arguments (given 3, expected 1..2)
/remove_index_bug/db/migrate/20170613103702_remove_email_index_on_users.rb:3:in `change'
-e:1:in `<main>'
Tasks: TOP => db:migrate
(See full trace by running task with --trace)
```

### System configuration
**Rails version**:
5.0.3
**Ruby version**:
2.4.1

**Comment by aried3r** [comment]
It seems this is possible, however, see https://github.com/rails/rails/blob/5-0-stable/activerecord/test/cases/migration/index_test.rb#L183, just not within a migration.

**Comment by bogdanvlviv** [comment]
This should work for you
```ruby
remove_index :users, column: :email, unique: true
```

**Comment by aried3r** [comment]
Thanks @bogdanvlviv, that worked! Did I somehow miss this [in the docs](http://api.rubyonrails.org/classes/ActiveRecord/Migration.html)? I can't seem to correctly interpret 

> `remove_index(table_name, column: column_names)`: Removes the index specified by `column_names`.
> `remove_index(table_name, name: index_name)`: Removes the index specified by `index_name`.

that one takes an option hash and the other doesn't. Is that a bug and missing docs?

**Comment by bogdanvlviv** [comment]
Take a look [here](http://api.rubyonrails.org/classes/ActiveRecord/ConnectionAdapters/SchemaStatements.html#method-i-remove_index)

**Comment by aried3r** [comment]
I see, thank you. I'd argue that another example using `unique: true` wouldn't hurt, but from the page you linked it implicitly follows.
