### ISSUE TITLE
Active Model cache is out of date after using db:migrate as a prerequisite

### ISSUE THREAD

**Issue by sbwoodside** [rails/rails#29448]
### Steps to reproduce

1. Have a project with 42 migrations, where one near the end adds a attribute `how_to_fix` to a model called `Inspector`.

2. Create `lib/tasks/sample_data.rake`:

```ruby
namespace :db do
  desc 'Drop, create, migrate, seed and populate sample data'
  task seed_sample_data: [:drop, :create, :migrate, :seed, :populate_sample_data] do
  end

  desc 'Populate the database with sample data'
  task populate_sample_data: :environment do
    puts Inspector.column_names.include?('how_to_fix')
    # create my sample data...
  end
end
```

3. Run `bundle exec rake db:populate_sample_data`

Output printed is `true` as expected.

4. Run `bundle exec rake db:seed_sample_data`

### Expected behavior

Expect `true`.

In other words, I expect the model attribute `how_to_fix` to exist.

### Actual behavior

Output printed is  for the final rake run is `false`.

It appears that the cache of the ActiveRecord Model/Attributes is out of date. I can access some of the attributes, but not all of them (not the ones in later migrations). If I add this I get the correct output:

```ruby
Inspector.reset_column_information
```

### System configuration
**Rails version**:

```
$ bundle exec rails --version
Expected string default value for '--rc'; got false (boolean)
Rails 4.2.6
```

**Ruby version**:

```
$ ruby --version
ruby 2.3.3p222 (2016-11-21 revision 56859) [x86_64-darwin15]
```

**Comment by jacobwalkr** [comment]
I've just come across this on Rails 5.2.4.1 while running several migrations through `db:migrate`.

Haven't been able to test on Rails 6 (under deadline pressure) but it seems to be that if you add a column in one migration (in my case, making an association polymorphic) and then try to use the column in the next migration (creating new records), the column information is out of date.

Should Rails reset column information between migrations?

If I run the migrations separately (or just re-run them after they fail), there's no problem.

Sorry for responding to a closed issue but I didn't want to create a whole new one when it seems to be exactly the same issue.
