### ISSUE TITLE
Infoblox incompatible with Rails 5.1

### ISSUE THREAD

**Issue by clarkent86** [rails/rails#29440]
### Steps to reproduce

(Guidelines for creating a bug report are [available
here](http://guides.rubyonrails.org/contributing_to_ruby_on_rails.html#creating-a-bug-report))

using the Infoblox gem with Rails 5.1

### Expected behavior
Tell us what should happen
Calls to the Infoblox API should return a Cname provided a connection, FQDN, and view. 

### Actual behavior
Tell us what happens instead

lib/infoblox/resource.rb line 110

connection.get(resource_uri, params) returns:

*** Faraday::SSLError Exception: SSL_connect returned=1 errno=0 state=error: certificate verify failed

with Rails 5.1 where previously this gem worked fine on Rails 5.0.1 . I'm still digging into whether or not it's actually a cert SSL issue on our end but nothing seems to be working with valid certs.

### System configuration
**Rails version**:
5.1.0

**Ruby version**:
2.4.1

**Comment by vipulnsward** [comment]
Hi @clarkent86 we reserve the tracker for issues related to Rails. Please open the incompatibility issue with the gem. 

If there's something wrong between Rails versions, you can open an issue with that information.
