### ISSUE TITLE
AbstractController::Translation#translate breaks when default option is an array

### ISSUE THREAD

**Issue by mtgrosser** [rails/rails#29441]
### Steps to reproduce

```
ApplicationController.new.translate '.foobar', default: ['Foo Bar', :barfoo]
=> ["Foo Bar", :barfoo]
```

### Expected behavior
```
ApplicationController.new.translate '.foobar', default: ['Foo Bar', :barfoo]
=> "Foo Bar"
```

### Actual behavior

The `default` option is modified using the `<<` operator, which results in an array within an array if multiple defaults are given by the caller. `I18n.t` cannot handle this kind of defaults.

See: https://github.com/rails/rails/blob/628e51ff109334223094e30ad1365188bbd7f9c6/actionpack/lib/abstract_controller/translation.rb#L15

### Affected Rails versions
5.x upto current

**Comment by vipulnsward** [comment]
I believe i18n already handles it: 
https://github.com/svenfuchs/i18n/blob/f331b763a2617ebaa1c27d43d134a72aaecd50ba/lib/i18n/backend/fallbacks.rb#L62

and finds a non symbol default. 

Atleast that's what I see from tests: 
```
assert_equal "bar", @controller.t("one.two.three.four", default: ["bar", :testsss])
```

What versions are you seeing this on?

**Comment by mtgrosser** [comment]
The method `AbstractController::Translation#translate` is all about keys starting with a dot. 
Therefore, the mentioned test case will not be affected by the bug. 

`I18n.t` *can not* handle defaults composed of an array containing other arrays, however such defaults are produced by the current implementation, which has been there since Rails 5.x.

https://github.com/rails/rails/blob/628e51ff109334223094e30ad1365188bbd7f9c6/actionpack/lib/abstract_controller/translation.rb#L15
