### ISSUE TITLE
Session in controller to not always have the same class

### ISSUE THREAD

**Issue by tjoyal** [rails/rails#29443]
### Steps to reproduce

Retrieving the session from the controller does not always return the same object type.

Normally the session would be of type `ActionDispatch::Request::Session`, but there are cases where it will be an empty `Hash`.

This makes it hard to use method that are only available in the `Session` class. (eg.: `session.loaded?`)

Around rails code there are conditionals to go around this by adding a conditional around the object type: https://github.com/rails/rails/blob/34fe2a4fc778d18b7fe6bdf3629c1481bee789b9/actionpack/lib/action_dispatch/middleware/session/abstract_store.rb#L73-L75 

In some other cases it check if the "session" respond to a specific method: https://github.com/rails/rails/blob/34fe2a4fc778d18b7fe6bdf3629c1481bee789b9/actionpack/lib/action_dispatch/http/request.rb#L327

I tried to poke around myself to open a draft, but this is spread all across the place. There seems to be session logic in many layers that don't have full context on the store being used.

The current code path I'm working on can reproduce the issue as I invoke a rails engine directly:
https://github.com/tjoyal/rails/blob/57877c2b2c21a926b86ba9f4a843e9606613f37d/railties/lib/rails/engine.rb#L520-L524 (I suspect there are easier way to reproduce the same result)

```ruby
env = Rack::MockRequest.env_for(path, input: body, method: method)
Something::Engine.call(env)
```
And then from a controller retrieving `session` gives me an empty `Hash`

### Expected behavior
I would expect a call to `session` from a controller to always return a `ActionDispatch::Request::Session` (or a `nil`)

### Actual behavior
Calling `session` can return a `ActionDispatch::Request::Session` or a `Hash` depending on different factors.

### System configuration
**Rails version**: 5.0.3

**Ruby version**: 2.3.3p222

**Comment by savroff** [comment]
seems like an interesting issue to work with. I'm up for it

**Comment by savroff** [comment]
@tjoyal seems like tests don't even cover this issue because if we remove checks from `actionpack` everything would be green)

I think we need to return `ActionDispatch::Request::Session` not `nil` because in other case we can get errrors in controllers where we try to assign new
