### ISSUE TITLE
Query Cache is not used in v5.0.x and v5.1.x for Model.exists? queries

### ISSUE THREAD

**Issue by zmoazeni** [rails/rails#29449]
### Steps to reproduce

```bash
# RAILS_VERSION="4.2.8"
# RAILS_VERSION="5.1.1"
# RAILS_VERSION="5.0.3"

set -e
set -x

gem install rails -v $RAILS_VERSION
rails _${RAILS_VERSION}_ new -d mysql --skip-spring query-cache-${RAILS_VERSION}-test
cd query-cache-${RAILS_VERSION}-test

bundle install
bundle exec rails g model Person name:string
bundle exec rake db:drop
bundle exec rake db:create
bundle exec rake db:migrate
bundle exec rails r "Person.cache { 3.times { Person.where(id: 1).exists? } }; Person.cache { 3.times { Person.where(id: 1).exists? } }"

```

You can run it manually by uncommenting the environment variables at the top or save it as a script and run it like `RAILS_VERSION=4.2.8 ./setup-query-cache-test.sh`

### Expected behavior

In all Rails versions 4.2.x, 5.0.x, and 5.1.x, the query cache would be used for subsequent `exists?` queries.

### Actual behavior

* 4.2.8 does not use it on the first cache run, but it will in all subsequent cache runs. _(See my notes at the bottom.)_
* 5.0.3 and 5.1.1 will never use the query cache for all queries.

4.2.8 will output `CACHE (0.0ms) ...` in the the log/development.log. 5.0.3 and 5.1.1 won't. I can also verify by turning on the general log in mysql locally and seeing the cached queries in 4.2.8 never hitting the server, but 5.0.3 and 5.1.1 query mysql all the time.

This behavior is strange with sqlite3 because 5.1.1 _says_ it uses the cache in the development.log (5.0.3 never prints out `CACHE`). You can remove the `-d mysql` the script and take a look at the log/development.log for both cases. I don't know of a way of verifying if sqlite3 actually ran the queries.

### System configuration
**Rails version**: 4.2.8, 5.0.3, and 5.1.1

**Ruby version**: ruby 2.4.1p111

### Some other debugging I've tried.

I thought perhaps the inconsistent behavior for 4.2.8 on the first run was due to `eager_load=false` but that doesn't seem the be the case. I believe it has something to do with needing a connection to the database created. 

This will also work to test that:

```bash
bundle exec rails r "Person.first; Person.cache { 3.times { Person.where(id: 1).exists? } }"
```

I also thought perhaps the new prepared_statements behavior might be causing this behavior in 5.0.3 and 5.1.1, but adding `prepared_statements: false` to the database.yml didn't change the behavior.

Other queries seem to work just fine with the query cache in both 5.0.3 and 5.1.1. For example:

```ruby
irb(main):001:0> Person.create!(name: 'foo')
irb(main):002:0> Person.cache { 3.times { Person.find(1).name } }
  Person Load (0.7ms)  SELECT  `people`.* FROM `people` WHERE `people`.`id` = 1 LIMIT 1
  CACHE Person Load (0.0ms)  SELECT  `people`.* FROM `people` WHERE `people`.`id` = 1 LIMIT 1  [["id", 1], ["LIMIT", 1]]
  CACHE Person Load (0.0ms)  SELECT  `people`.* FROM `people` WHERE `people`.`id` = 1 LIMIT 1  [["id", 1], ["LIMIT", 1]]
```

**Comment by zmoazeni** [comment]
Doing a little more digging (and a short term fix). Rewriting the query explicitly works fine and uses the query cache in both 5.0.3 and 5.1.1:

```ruby
Person.cache { 3.times { Person.where(id: 1).select(1).to_a.present? } }
```

**Comment by vipulnsward** [comment]
I see this on mysql and postgres being an issue, while sqlite seems to cache them.

**Comment by vipulnsward** [comment]
I suppose https://github.com/rails/rails/pull/26584/files is causing this.

**Comment by tjschuck** [comment]
Like @vipulnsward said, this affects the mysql2 and postgresql adapters, and sqlite3 is fine.

Adding the following test to `activerecord/test/cases/query_cache_test.rb`:

```diff
diff --git a/activerecord/test/cases/query_cache_test.rb b/activerecord/test/cases/query_cache_test.rb
index 494663eb04..9b64fa4095 100644
--- a/activerecord/test/cases/query_cache_test.rb
+++ b/activerecord/test/cases/query_cache_test.rb
@@ -204,6 +204,12 @@ def test_count_queries_with_cache
     end
   end

+  def test_exists_queries_with_cache
+    Task.cache do
+      assert_queries(1) { Task.exists?(1); Task.exists?(1) }
+    end
+  end
+
   def test_query_cache_dups_results_correctly
     Task.cache do
       now  = Time.now.utc
```

you can see this is currently failing on `master` (right now, at 326914dd3a15e04851c9ef4a47edeb3dad2ec381) for mysql2 and postgresql, but passing for sqlite3:


```
ubuntu@rails-dev-box:/vagrant/rails/activerecord$ ARCONN=sqlite3 bundle exec ruby -Itest test/cases/query_cache_test.rb -n /exists/
Using sqlite3
Run options: -n /exists/ --seed 59392

# Running:

.

Finished in 0.065338s, 15.3051 runs/s, 15.3051 assertions/s.

1 runs, 1 assertions, 0 failures, 0 errors, 0 skips





ubuntu@rails-dev-box:/vagrant/rails/activerecord$ ARCONN=mysql2 bundle exec ruby -Itest test/cases/query_cache_test.rb -n /exists/
Using mysql2
Run options: -n /exists/ --seed 58845

# Running:

F

Finished in 0.093257s, 10.7231 runs/s, 10.7231 assertions/s.

  1) Failure:
QueryCacheTest#test_exists_queries_with_cache [test/cases/query_cache_test.rb:209]:
2 instead of 1 queries were executed.
Queries:
SELECT  1 AS one FROM `tasks` WHERE `tasks`.`id` = 1 LIMIT 1
SELECT  1 AS one FROM `tasks` WHERE `tasks`.`id` = 1 LIMIT 1.
Expected: 1
  Actual: 2

1 runs, 1 assertions, 1 failures, 0 errors, 0 skips





ubuntu@rails-dev-box:/vagrant/rails/activerecord$ ARCONN=postgresql bundle exec ruby -Itest test/cases/query_cache_test.rb -n /exists/
Using postgresql
Run options: -n /exists/ --seed 62120

# Running:

F

Finished in 0.126424s, 7.9099 runs/s, 7.9099 assertions/s.

  1) Failure:
QueryCacheTest#test_exists_queries_with_cache [test/cases/query_cache_test.rb:209]:
2 instead of 1 queries were executed.
Queries:
SELECT  1 AS one FROM "tasks" WHERE "tasks"."id" = $1 LIMIT $2
SELECT  1 AS one FROM "tasks" WHERE "tasks"."id" = $1 LIMIT $2.
Expected: 1
  Actual: 2

1 runs, 1 assertions, 1 failures, 0 errors, 0 skips
```

Bisecting back, it looks like this commit introduced the problem for MySQL: https://github.com/rails/rails/commit/7bfc6ea1ef6963eeff39d1cdd4852a822371b528

And this commit introduced the problem for Postgres: https://github.com/rails/rails/commit/1a7338d868d68ecef899fb8d81cf37852cc94a8c

**Comment by vipulnsward** [comment]
Can confirm about https://github.com/rails/rails/pull/20024/files
