### ISSUE TITLE
form_with is not assigning id's to inputs

### ISSUE THREAD

**Issue by tomrossi7** [rails/rails#29450]
### Steps to reproduce
```
<%= f.label :name %>
<%= f.text_field :name %>
```

### Expected behavior
I would expect it to assign ids so the label functions correctly as it does with `form_for`
which produces the following output:

```
  <label for="model_name">Name</label>
  <input type="text" name="model[name]" id="model_name">
```

### Actual behavior
`form_with` produces a label with an invalid `for` attribute since the `id` is missing from the input:

```
  <label for="model_name">Name</label>
  <input type="text" name="model[name]">
```

### System configuration
**Rails version**:
5.1.1

**Ruby version**:
2.3.3

**Comment by rafaelfranca** [comment]
That is by design. `form_with` don't assign id's to inputs.

**Comment by morgoth** [comment]
@rafaelfranca but it still produces `for` attribute. The form doesn't look nice this way:
```
form.label :content
form.text_field :name, id: "object_class_name_content"
```
And it's impossible to turn on generating ids, because of hardcoded https://github.com/rails/rails/blob/master/actionview/lib/action_view/helpers/form_helper.rb#L717

@kaspth Why was it designed this way?

**Comment by kaspth** [comment]
@morgoth See the first point here: https://github.com/rails/rails/issues/25197 😊

**Comment by tomrossi7** [comment]
If that is the behavior, shouldn't the `for` attribute be removed from the label as well as the `id` on the input?
