### ISSUE TITLE
Rails 5 isn't playing well with minitest-focus

### ISSUE THREAD

**Issue by jdborneman** [rails/rails#29469]
I wrote an issue with minitest-focus and they said it was somethign with Rails and I should write something up here. ANything to figure out a solution!
https://github.com/seattlerb/minitest-focus/issues/12

### Steps to reproduce
Install and use minitest-focus
Set a minitest to 'focus' with a tag before the test

### Expected behavior
Only the 'focused' test will run

### Actual behavior
All tests run

### System configuration
**Rails version**:
5.1.1

**Ruby version**:
2.3.3

**Other versions**:
minitest 5.10.2
minitest-focus 1.1.2
minitest-ar-assertions 0.1.1
minitest-reporters 1.1.14

**Comment by jdborneman** [comment]
Closed without comment? Any feedback to better figure out the issue?

**Comment by rafaelfranca** [comment]
It was not closed. We are not users of minitest-focus so I'd recommend you to investigate it.

**Comment by zenspider** [comment]
rails did hijack the plug in loading system for reasons that I do not understand. This is definitely broken by rails' changes to minitest.

**Comment by jdborneman** [comment]
oops sorry misread. ALright I'll try to find the time. alas the minitest focus guys are saying to ask the rails people about it ¯\_(ツ)_/¯

**Comment by rafaelfranca** [comment]
@zenspider the only place were we change how minitest plugins are loaded is here https://github.com/rails/rails/blob/master/railties/lib/rails/test_unit/minitest_plugin.rb#L140-L145. What we want is to put Rails in the beginning of the list. Do you know why that would break others plugins like minitest-focus?

**Comment by rafaelfranca** [comment]
Does minitest focus use a different option. One thing that we do right now that is broken is to call the parameter parsing too early and not allowing other plugins to register their parameters.

**Comment by rafaelfranca** [comment]
https://github.com/rails/rails/pull/25055

**Comment by zenspider** [comment]
IIRC, MTF loads up ARGV w/ extra flags as the files are loading, then at_exit triggers and processes them. I'm open to alternatives.

Can you point me to where https://github.com/rails/rails/blob/master/railties/lib/rails/test_unit/minitest_plugin.rb#L65 is run? and it's alternative?

I think that's probably the crux of MT vs rails issues... in MT files load and then options get processed. Rails seems to do the reverse based on that method and the bottom of that file?

**Comment by rafaelfranca** [comment]
That method is being used https://github.com/rails/rails/blob/46adb59b3474351e95ddc2357e67d169d6ffec51/railties/lib/rails/test_unit/testing.rake#L12, so when `rake test` and friends are used.

Yeah, I think that is the problem. We only process the options early because we want to capture the name of the files that were passed https://github.com/rails/rails/blob/master/railties/lib/rails/test_unit/minitest_plugin.rb#L62.

So when you run `rails test my_test_file.rb` we parse all argument to be able to get the `my_test_file`. Is there any way to use to get that without parsing the arguments?

**Comment by rafaelfranca** [comment]
Maybe if we store the `args` here https://github.com/seattlerb/minitest/blob/db0c34dd2f7333e53bc1a97d254a12d16ba8349d/lib/minitest.rb#L215 in `options` we can do what we want without eagerly parse the options.

**Comment by kaspth** [comment]
@rafaelfranca @zenspider took a stab at making us a better minitest citizen here: https://github.com/rails/rails/pull/29572 😊
