### ISSUE TITLE
Can't find partial when controller subclasses another controller

### ISSUE THREAD

**Issue by zachahn** [rails/rails#29468]
### Steps to reproduce

1. Generate new Rails app
1. Generate scaffold for Articles
1. Move article table row of index into partial (its filepath is `articles/_article` to match its `to_partial_path`)
1. Generate `Articles::DraftController` which subclasses from `ArticlesController`
1. Route `/articles/draft` to `Articles::DraftController#index`

[Example repo](https://github.com/zachahn/rails_partial_path_example)

(I wrote seeds which create two articles for this example.)

### Expected behavior

http://localhost:3000/articles/draft should find the article partial located in `articles/_article`, and the page should render exactly the same as http://localhost:3000/articles, except with the published articles filtered out

### Actual behavior

http://localhost:3000/articles/draft looks for the article partial at `articles/articles/_article`, and the page fails to render.

```
Started GET "/articles/draft" for 127.0.0.1 at 2017-06-15 23:54:39 +0900
Processing by Articles::DraftController#index as HTML
  Rendering articles/index.html.erb within layouts/application
  Article Load (0.3ms)  SELECT "articles".* FROM "articles" WHERE ("articles"."published" != ?)  [["published", "t"]]
  Rendered articles/index.html.erb within layouts/application (8.2ms)
Completed 500 Internal Server Error in 21ms (ActiveRecord: 1.0ms)



ActionView::Template::Error (Missing partial articles/articles/_article with {:locale=>[:en], :formats=>[:html], :variants=>[], :handlers=>[:raw, :erb, :html, :builder, :ruby, :coffee, :jbuilder]}. Searched in:
  * "/path/to/rails_partial_path_example/app/views"
):
    12:   </thead>
    13:
    14:   <tbody>
    15:     <%= render @articles %>
    16:   </tbody>
    17: </table>
    18:

app/views/articles/index.html.erb:15:in `_app_views_articles_index_html_erb__3270307881277883589_70318547216560'
```

### System configuration

**Rails version**: `Rails 5.1.1`

**Ruby version**: `ruby 2.4.0p0 (2016-12-24 revision 57164) [x86_64-darwin16]`

**Comment by zachahn** [comment]
I found a workaround for now which allows `/articles` and `/articles/draft` to use the same partial.

```erb
<%# In app/views/articles/index.html %>
...
<%= render partial: "articles/article", collection: @articles %>
...
```

This issue seems like a bug to me, since the documentation for `ActionView::PartialRenderer` says that `<%= render @articles %>` is equivalent to the above (though it doesn't mention anything about inherited controllers)

**Comment by savroff** [comment]
Hi @zachahn!
It's kinda funny situation. From what I see with controller behavior, partials should follow same rules. This case this looks like a bug for me too. 

But I honestly never used a nested controller in this way.

**Comment by zachahn** [comment]
Hi @savroff!

I'd really appreciate it if you took a look at this! I was poking around before submitting this issue, but I only got as far as noticing that the method `ActionView::Template#virtual_path` returned something that looked like `articles/articles/_article` (but I may have some of the details incorrect).

I actually just noticed something interesting... There's an ActionView [configuration](http://guides.rubyonrails.org/configuring.html) called `prefix_partial_path_with_controller_namespace` which was introduced in 18d275ada1b23bf07cc51a815385afac6bb2b8cb.

I wonder if that configuration should be deprecated and if partials should follow the same controller rules?

**Comment by savroff** [comment]
@zachahn I'm right now exactly looking around `prefix_partial_path_with_controller_namespace` 👍

**Comment by savroff** [comment]
@zachahn 
After time looking on code, I think the best way to do fix in your case is add
```
ActionView::Base.prefix_partial_path_with_controller_namespace = false
```
Inside your nested controller.

Seems like is a better way to do it, rather try to make some fix or deprecate this functionality and potentially break a lot of apps. 

@rafaelfranca what you think about this case? Because I don't have too much experience to exactly say how rare case from [Example Repo](https://github.com/zachahn/rails_partial_path_example) when you have nested controller like this.

In [tests](https://github.com/rails/rails/blob/master/actionview/test/activerecord/render_partial_with_record_identification_test.rb#L99)
Right now `NestedController` inherit from `ActionController::Base`, but if we change this to `GamesController`
 
And add controller on top:

```
class GamesController < ActionController::Base
  def render_with_record
    render partial: Game.new("Ping")
  end
end
```
Tests will fail because you must change `prefix_partial_path_with_controller_namespace` to `false`

**Comment by zachahn** [comment]
Ah thanks for looking into it! 

Hm.. I just found an interesting solution. I overrode `Article#to_partial_path` so that it returned `article` instead of `articles/article`.

https://github.com/zachahn/rails_partial_path_example/compare/to_partial_path

All of the following links work, and they all resolve exactly like I was expecting:

- http://localhost:3000/articles
- http://localhost:3000/articles/draft (looks like /articles)
- http://localhost:3000/articles/published (uses overridden article partial)

This is definitely a breaking change though. If there was an `AuthorsController#show` which listed an author's recent articles via the `articles/article` partial, it would no longer be able to find the correct article partial since it'd look only at `authors/article` then `application/article`. But the solution for that could be to place the article partial into `app/views/application/_article.html.erb`.

**Comment by savroff** [comment]
@zachahn I found one fix around this problem. But I need to do more tests before pull request, to make sure that it's will work with every case.

**Comment by zachahn** [comment]
Ah thanks for looking into it further! I'd be very interested to see what you did 😄

**Comment by savroff** [comment]
ok, after several hours here. My solution will help in your situation :) but will not help with other people problem, when they expect to see nested controller logic for partial. 
I still trying to figure out a way here. Never giveup 💃

**Comment by savroff** [comment]
@zachahn my fix should fix your problem
🎉 thank you for a lot of helpful thoughts about this problem.

**Comment by zachahn** [comment]
@savroff thank you for helping!! 😄

**Comment by savroff** [comment]
@zachahn welcome!
After hours of checks, I agree with your suggestion to deprecate this strange logic with `prefix_partial_path_with_controller_namespace`.
