### ISSUE TITLE
Problem overriding association proxy methods

### ISSUE THREAD

**Issue by dskecse** [rails/rails#29463]
Rails 5.0.3 won't override `ActiveRecord::Associations::CollectionProxy` methods with the ones that can be defined inside the block of the `has_many` macro. The same code works in Rails 5.0.1 and 5.0.2.

### Steps to reproduce

[An executable test case](https://gist.github.com/e6d0bdafa9b33f8877e4bd5cac7e9cc8)

```ruby
ActiveRecord::Schema.define do
  create_table :articles, force: true

  create_table :comments, force: true do |t|
    t.text :content
    t.references :article, foreign_key: true
  end
end

class Article < ActiveRecord::Base
  has_many :comments do
    def build(*args, &block)
      args << { content: 'Sample' }
      super
    end
  end
end

class Comment < ActiveRecord::Base
  belongs_to :article
end

class BugTest < Minitest::Test
  def test_association_stuff
    article = Article.create!
    comment = article.comments.build

    assert_equal comment,  article.comments.first
    assert_equal 'Sample', article.comments.first.content
  end
end
```

### Expected behavior

Adding the `build` method to the anonymous module should have overridden the `ActiveRecord::Associations::CollectionProxy#build` method.

### Actual behavior

`ActiveRecord::Associations::CollectionProxy#build` method does not get overridden.

### System configuration

**Rails version**: 5.0.3
**Ruby version**: 2.2.7

**Comment by kamipo** [comment]
Fixed in c86a9e1096de3ff290b51e437daa77d5647d88ea.

**Comment by kamipo** [comment]
Yeah, already backported in 5.0.4.rc1.
https://github.com/rails/rails/blob/v5.0.4.rc1/activerecord/CHANGELOG.md

**Comment by dskecse** [comment]
@kamipo thanks a bunch!
