### ISSUE TITLE
Problem in ActiveJob::QueueAdapters::SneakersAdapter::JobWrapper reads only from default queue

### ISSUE THREAD

**Issue by nielsjansendk** [rails/rails#29478]
There is a fundamental flaw in the ActiveJob Sneakers adaptor (https://github.com/rails/rails/blob/master/activejob/lib/active_job/queue_adapters/sneakers_adapter.rb). When you use enqueue you insert the job into the queue specified in the job. So this job

class MyJob < ApplicationJob
    queue_as :my_queue

    def perform()
        puts "working..."
    end
end

will (correctly) insert the job into the rabbit-queue named "my_queue". However, the JobWrapper will never read from this queue. The JobWrapper is hardcoded to read only from the "default" queue. Which means that the message will be stuck in "my_queue" forever, never getting processed.

I'm not sure what the correct way to solve this particular problem is. It seems that the JobWrapper should be able to take a parameter that specifies which queue to read from, depending on the job it is wrapping. 

If anyone else has run into the same problem, I'd love to know if you found a way to work around it.

This problem exists in every rails version that has ActiveJob as far as I can tell.

**Comment by laertispappas** [comment]
I think that by default all workers wait for jobs in the `default` queue.

**Comment by nielsjansendk** [comment]
@laertispappas I already have. The activejob job in my code example is supposed to listen to 'my_queue'. Except it does not, because JobWrapper never checks which queue the job is supposed to listen to. It only listens to the default queue. All jobs are started by using the following command:

WORKERS=ActiveJob::QueueAdapters::SneakersAdapter::JobWrapper rails sneakers:run

Which means that in order to listen to other queues I would somehow have to override the queue in JobWrapper. One workaround could be that ActiveJob only inserts things into queues, but a sneakers worker takes things out of the queue. Except I would need to somehow access all the rails magic that deserialises the information in the message. And I don't know how to do that.

**Comment by utilum** [comment]
It *is* surprising to see `from_queue` argument hard coded

**Comment by nielsjansendk** [comment]
@utilum Yes! That makes no sense, and it is certainly not going to work as described in the Sneakers documentation. You will never be able to listen to any other queue than "default".

**Comment by utilum** [comment]
@nielsjansendk can you provide an automated test for this?

**Comment by y-yagi** [comment]
If my understanding is correct, Active Job provides only the function to send job to sneakers, worker does not provide. 
If you want to customize the queue name, it would be better to create your own worker. As below: 

```ruby 
# app/workers/my_worker.rb 
class MyWorker < ActiveJob::QueueAdapters::SneakersAdapter::JobWrapper
  from_queue :my_queue 
end 
```

FYI: https://github.com/rails/activejob/issues/47#issuecomment-53490859

**Comment by nielsjansendk** [comment]
@y-yagi That is definitely not clear from any documentation. This https://github.com/jondot/sneakers/wiki/How-To:-Rails-Background-Jobs-with-ActiveJob doesn't mention it at all. But yeah, a workaround is the have a sneakers worker that mirrors every activejob, making it call MyJob.perform_now. It's not DRY at all, though. Maybe this is more of a feature request then, but I think that if ActiveJob can put a message into a queue it should be able to take it out of the same queue.

**Comment by nielsjansendk** [comment]
I found this, which also describes the issue and how to work around it: https://medium.com/@dongwookkoo/rails-activejob-and-sneakers-9b8625e778eb Just in case anyone else runs into the same problem.

**Comment by BookOfGreg** [comment]
In jondot/sneakers#311 I make an attempt to fix this issue.

I first looked for a solution within Rails but it seems that the way Sneakers detects Workers [[1](https://github.com/jondot/sneakers/blob/master/lib/sneakers/worker.rb#L123-L128)] and uses it to run them [[2](https://github.com/jondot/sneakers/blob/master/lib/sneakers/tasks.rb#L17)] doesn't play nice with how Rails's Jobs all share a single class [[3](https://github.com/rails/rails/blob/master/activejob/lib/active_job/queue_adapters/sneakers_adapter.rb#L36)].

If there was a way of defining one class per worker in that adapter or otherwise metaprogramming the Worker names then we could implement the queue properly.
