### ISSUE TITLE
rails5.1 can't connected actioncable

### ISSUE THREAD

**Issue by huhu502** [rails/rails#29477]
### Steps to reproduce

our project want to convert rails5.0 to rails5.1,but meet some problems in actioncable.

### Expected behavior
The problem is that the find_verified_user method can't used.
### Actual behavior
**The former code :**
``` bash
private
    def find_verified_user
      begin
        header_array = **self.**request.headers[:HTTP_SEC_WEBSOCKET_PROTOCOL].split(',')
        token = header_array[header_array.length - 1]
        user_id = JsonWebToken.decode(token)[:user_id].to_i
        if current_user = User.find(user_id)
          current_user
        else
          reject_unauthorized_connection
        end
      rescue
        reject_unauthorized_connection
      end
    end
```
**The latter code:**
``` bash
 private
    def find_verified_user
      begin
        header_array = request.headers[:HTTP_SEC_WEBSOCKET_PROTOCOL].split(',')
        token = header_array[header_array.length - 1]
        user_id = JsonWebToken.decode(token)[:user_id].to_i
        if current_user = User.find(user_id)
          current_user
        else
          reject_unauthorized_connection
        end
      rescue
        reject_unauthorized_connection
      end
    end
```
### System configuration
**Rails version**:
rails5.1
**Ruby version**:
ruby2.3.3

**Comment by palkan** [comment]
@huhu502 Could you, please, more information and logs? What do you mean by

> find_verified_user method can't used.

?

**Comment by huhu502** [comment]
When I update rails5.0 to rails5.1, The actioncable can't be connected.I found a problem in there https://github.com/rails/rails/commit/91fa2b71c3fecb26a1dc7836874478f12e6d7a02#diff-e7a49345fe344d173cbcd874c21a1a61 find_verified_user method from protected to private.Then I changed my connection.rb file https://github.com/huhu502/rais5.1_actioncable/blob/master/channels/application_cable/connection.rb  Then the problem is solved. because I removed this code "self.".

**Comment by palkan** [comment]
Thanks for explanation!
I think, it's time to close the issue)

**Comment by huhu502** [comment]
ok, thanks.

**Comment by eileencodes** [comment]
Sounds like this issue has been resolved. Let me know if it's not @huhu502
