### ISSUE TITLE
rails-ujs prematurely enables disabled elements for XHR requests with redirects

### ISSUE THREAD

**Issue by mrhead** [rails/rails#29473]
### Steps to reproduce

```
rails new rails-ujs-test
```

```
# config/routes.rb

Rails.application.routes.draw do
  resources :users
end
```

```
# app/controllers/users_controller.rb

class UsersController < ApplicationController
  def index
    sleep 2
  end

  def new
  end

  def create
    sleep 2
    redirect_to users_path
  end
end
```

```
# app/views/users/new.html.erb

<h1>Users#new</h1>

<%= form_with url: users_path do |form| %>
  <%= form.submit "Create user", data: { disable_with: "Creating user..." } %>
<% end %>
```

```
# app/views/users/index.html.erb

<h1>Done!</h1>
```

Start the server, visit http://localhost:3000/users/new and click on the submit button.

### Expected behavior

When the form is submitted, the submit button should be disabled until the redirect action finishes. This is the behaviour which happens for non-XHR requests.

### Actual behavior

The submit button is disabled during the `create` action. But the `create` action redirects us to the `index` action and button is enabled again in the meantime.

This is caused by combination of rails-ujs and Turbolinks.

`redirect_to users_path` is automatically converted to

```
Turbolinks.clearCache()
Turbolinks.visit("http://localhost:3000/users", {"action":"replace"})
```

for XHR requests. This is a HTTP 200 reply and when rails-ujs receives it, then it enables the button again which allows users to click on it again. This is happening in our real world app even if the responses are pretty fast.

You can see it here:

![ujs-test](https://user-images.githubusercontent.com/522375/27210987-8e142704-5256-11e7-812d-7c2b9a1b10df.gif)

I've reported this issue to the original rails-ujs repository some time ago. But it doesn't exist anymore and I can't reference the original report. However, I've tried to fix it, but I did not find a workable solution. It should be probably fixed in rails-ujs which shouldn't enable elements again if a response contains `Turbolinks.visit`.

### System configuration
**Rails version**: 5.1.1 and `master` branch

**Ruby version**: 2.4.1p111

**Turbolinks version**: 5.0.1

**Comment by valterbarros** [comment]
I had the same issue.

**Comment by bryanrite** [comment]
I've been able to work around this somewhat.

Looking through the `rails-ujs` source, I noticed it re-enables elements on `ajax:complete`: https://github.com/rails/rails/blob/cbf378bc2725afe55e81d74bf97be7d484309863/actionview/app/assets/javascripts/rails-ujs/start.coffee#L60

I already have a handler for  to deal with remote form errors as discussed in https://github.com/turbolinks/turbolinks/issues/85 so I extended it so we re-disable form elements if the form is a successful redirect.

Something like:

```javascript
var remoteForm = 'form[method!=get][data-remote=true]';

$(document).on('ajax:complete', remoteForm, function(e, xhr) {
  if(xhr.responseText.substring(0, 10) == 'Turbolinks') {
    // This is a turbolink redirect, so re-disable the form until turbolinks
    // fetches the new page.
    $.rails.disableFormElements($(e.target));
  } else {
    // Handle if there was a form error... possible solutions in 
    // turbolinks/turbolinks#85
  }
});
```

**Comment by mrhead** [comment]
@rafaelfranca Could you please help us here? Or could you please CC anyone who could help?

I think that this should work out of the box without creating custom event handlers, but I'm not sure in what place we should solve this issue. rails-ujs shouldn't know about Turbolinks and Turbolinks shouldn't know about rails-ujs. But that means that none of them can contain fix for this issue.

So the question is: Where should we solve this issue?

Thank you!

**Comment by rafaelfranca** [comment]
I totally agree neither of them should know about each other. Maybe we can set a header in Turbolinks and check this header on rails-ujs? This way we are not coupling any of the tools we are using a custom header that any tool can set.

**Comment by mrhead** [comment]
We could set the header from here: https://github.com/turbolinks/turbolinks-rails/blob/master/lib/turbolinks/redirection.rb#L24

Do you mean something like setting a header called `X-XHR-Redirect` and checking for it in rails-ujs? Or do you mean something else?

**Comment by rafaelfranca** [comment]
Yes, exactly that

**Comment by skuark** [comment]
Still able to reproduce this issue on 5.1.x.

**Comment by pioz** [comment]
Why this issue is closed?

**Comment by mrhead** [comment]
Because of inactivity and I'm not sure how to push the fix.

**Comment by mrhead** [comment]
@georgeclaghorn Thank you for reopening this issue!

There are two possible solutions to this issue: 

- In https://github.com/rails/rails/pull/29475 rails-ujs has to know about Turbolinks, but it works out of the box.
- In https://github.com/rails/rails/pull/31441 rails-ujs doesn't know anything about Turbolinks, but it depends on the `X-Xhr-Redirect` header and https://github.com/turbolinks/turbolinks-rails/pull/28.

I'll be happy to go with either solution. However, I don't know how to test this fix with [rails-ujs tests](https://github.com/rails/rails/tree/master/actionview/test/ujs) and I'm not sure if it's feasible to test it.

**Comment by mrhead** [comment]
I've just added tests for rails-ujs to both PRs.

**Comment by mrhead** [comment]
Thinking about it, I probably prefer https://github.com/rails/rails/pull/31441. It requires a change in [turbolinks-rails](https://github.com/turbolinks/turbolinks-rails/pull/28) but it's less coupled to Turbolinks than https://github.com/rails/rails/pull/29475.

**Comment by valterbarros** [comment]
@bryanrite Thanks
