### ISSUE TITLE
Make new Rails apps not generate long lines

### ISSUE THREAD

**Issue by betesh** [rails/rails#29480]
Rails itself is one of many gems that now use rubocop to enforce consistent styling.

We may be approaching a point where it's time to make new rails apps include rubocop in their Gemfile, and generate some reasonable default rubocop configuration.  However, that's a conversation for a different time.

Before we get there, as the Ruby community trends towards enforcing consistent styling on individual projects, it's becoming more common that one of the first things people do when they generate a Rails app is add Rubocop.  (I can't speak for everyone, but the team I work with has definitely been moving in this direction.)

It would save us time if the generated app was more consistent with a default rubocop configuration.

To be fair, while there are a handful of rubocop cops that a new Rails app violates, some are a matter of debate (`Prefer single-quoted strings inside interpolations`, `Use nested module/class definitions instead of compact style`), and others can easily be autocorrected, so I don't think we need to worry about those.

However, I think one thing most would agree about is a maximum line length.  Rubocop recommends no more that 80 characters per line and Rails itself follows this default.  So I think it's fair that the apps that Rails generates should also follow this default.

Let me know if the Rails core team agrees and I will gladly prepare a PR.

### Steps to reproduce

```
rails new not-a-rubocop
cd not-a-rubocop
sed -i.bak "40i\\\n  gem 'rubocop', require: false" Gemfile # i.e. add rubocop to Gemfile
bundle
rubocop | grep "Line is too long"
```

### Expected behavior
It should not have any rubocop Metrics/LineLength violations

### Actual behavior
```
$ rubocop | grep "Line is too long"
Gemfile:37:81: C: Line is too long. [83/80]
Gemfile:47:81: C: Line is too long. [93/80]
Gemfile:50:81: C: Line is too long. [130/80]
Rakefile:2:81: C: Line is too long. [90/80]
config/puma.rb:10:81: C: Line is too long. [85/80]
config/environments/production.rb:2:81: C: Line is too long. [85/80]
config/environments/production.rb:33:81: C: Line is too long. [102/80]
config/environments/production.rb:45:81: C: Line is too long. [96/80]
config/environments/production.rb:47:81: C: Line is too long. [96/80]
config/environments/production.rb:60:81: C: Line is too long. [83/80]
config/environments/production.rb:66:81: C: Line is too long. [100/80]
config/environments/production.rb:81:81: C: Line is too long. [83/80]
config/environments/test.rb:2:81: C: Line is too long. [85/80]
config/environments/development.rb:2:81: C: Line is too long. [85/80]
config/initializers/wrap_parameters.rb:6:81: C: Line is too long. [96/80]
config/initializers/backtrace_silencers.rb:3:81: C: Line is too long. [107/80]
config/initializers/backtrace_silencers.rb:6:81: C: Line is too long. [112/80]
config/application.rb:14:81: C: Line is too long. [82/80]
test/test_helper.rb:5:81: C: Line is too long. [82/80]
db/seeds.rb:1:81: C: Line is too long. [103/80]
db/seeds.rb:2:81: C: Line is too long. [111/80]
db/seeds.rb:6:81: C: Line is too long. [81/80]
```

### System configuration
**Rails version**: 5.1.1

**Ruby version**: 2.3.4

**Comment by rafaelfranca** [comment]
We don't follow the rubocop default and we are not going to follow. If you application want to follow you can change the generated code.

**Comment by betesh** [comment]
@rafaelfranca I think there's a misunderstanding here.

Rails itself does use Rubocop.  And it uses the default LineLength of 80.  

Am I mistaken about one of those statements?

All I'm suggesting is being consistent about that one rule in generated apps.

**Comment by rafaelfranca** [comment]
Rails use rubocop but it doesn't use the default LineLength of 80. We don't enforce line length in our codebase. The only rules we follow are those were https://github.com/rails/rails/blob/6bb7d50dece5d02540e5c420f63478185102fd70/.rubocop.yml#L11-L124.

**Comment by betesh** [comment]
Ah, I see.  I missed the `DisabledByDefault: true` when I was looking at that file earlier.

Thanks for clarifying!
