### ISSUE TITLE
Documentation still refers to config.assets.raise_runtime_errors

### ISSUE THREAD

**Issue by betesh** [rails/rails#29483]
I can't seem to find it used anywhere in the source code of rails, sprockets or sprockets-rails.

I even grepped all installed gems and couldn't find it being used anywhere later than sprockets-rails-2.3.3

### Steps to reproduce

```
# In the rails repo
$ git grep raise_runtime_errors
```

### Expected behavior
No references to raise_runtime_errors in documentation

### Actual behavior
```
$ git grep raise_runtime_errors
guides/source/asset_pipeline.md:config.assets.raise_runtime_errors = false
guides/source/configuring.md:* `config.assets.raise_runtime_errors` Set this flag to `true` to enable additional runtime error checking. Recommended in `config/environments/development.rb` to minimize unexpected behavior when deploying to `production`.
```

### System configuration
**Rails version**: 5.1.1

**Ruby version**: 2.4.0

**Comment by vipulnsward** [comment]
https://github.com/rails/rails/commit/019c7f92f09170f0f87105f544ae4eff49e83de7
