### ISSUE TITLE
Rails stats command counts files only from the hardcoded list

### ISSUE THREAD

**Issue by kirs** [rails/rails#29497]
Steps to reproduce:

1. `rails new myapp`
2. Create `app/policies/my_policy.rb` that would contain a hundred lines of code
3. `bin/rails stats` output won't include any files in `app/policies`.

The issue comes from the fact that `rails stats` is using a hardcoded list of directories to count stats:

```
STATS_DIRECTORIES = [
  %w(Controllers        app/controllers),
  %w(Helpers            app/helpers),
  %w(Jobs               app/jobs),
  %w(Models             app/models),
  %w(Mailers            app/mailers),
  %w(Channels           app/channels),
  %w(JavaScripts        app/assets/javascripts),
  %w(Libraries          lib/),
  %w(APIs               app/apis),
  %w(Controller\ tests  test/controllers),
  %w(Helper\ tests      test/helpers),
  %w(Model\ tests       test/models),
  %w(Mailer\ tests      test/mailers),
  %w(Job\ tests         test/jobs),
  %w(Integration\ tests test/integration),
  %w(System\ tests      test/system),
]
```

Which obviously won't include anything custom like `app/policies` or `app/services`.

I think we could potentially leverage `Rails.application.config.paths` to make stats command use all directories in the app and calculate more realistic stats. This would require loading environment (right now the stats task doesn't load it).

Thoughts? @matthewd @rafaelfranca 

I have a draft of the patch that I'll be happy to submit.

**Comment by rafaelfranca** [comment]
Seems like a good plan to me

**Comment by kirs** [comment]
I'm not sure what to do about tests. If we follow the same convention than the tests for services would be in `test/services`. However `Rails.application.config.paths` doesn't include `test/` dirs.

I'd probably go with `Rails.application.config.paths` for any app/ and lib/ stuff and then `Dir["test/**/"]` to count all kind of tests. WDYT?

**Comment by gaurish** [comment]
@kirs are you working on this? if not, then we send pr?

**Comment by kirs** [comment]
Yep I'm working on it. Will submit the PR :soon:

**Comment by matthewd** [comment]
IIRC rspec-rails mangles `STATS_DIRECTORIES`; forcing a change on them for improved overall functionality seems okay, but we'll need to make sure they're still able to achieve what they need.
