### ISSUE TITLE
Failure to save PostgreSQL Array Column

### ISSUE THREAD

**Issue by s2t2** [rails/rails#29498]
### Steps to reproduce

Setup a migration and migrate the database:

```` rb
class CreateThings < ActiveRecord::Migration[5.0]
  def change
    create_table :things do |t|
      t.text :tags, array: true, default: []
      t.timestamps
    end
  end
end
````

Setup the model:

```` rb
class Thing < ApplicationRecord
  serialize(:tags, Array)
end
````
Then in a rails console:

```` rb
thing = Thing.create(tags: ["a", "b", "c"])
````

### Expected behavior

```` rb
thing.persisted? #> true
thing.tags #> ["a", "b", "c"]
````

This was the case (no errors) when I wasn't using `, array: true, default: []` in the migration. But adding `, array: true, default: []` seems to break the desired functionality.

### Actual behavior

```` rb
thing.persisted? #=> true
thing.tags #=> []
````

Furthermore:

```` rb
thing.tags = ["a", "b", "c"]
thing.save
thing.tags #=> []
````

Furthermore:

```` rb
thing.update_attributes(tags: ["a", "b", "c"]) #=> true
thing.tags #> []
````

### System configuration
**Rails version**: 5.0.3

**Ruby version**: 2.2.3

NOTE: I read maybe newer versions of rails had some fixes for pg arrays. But when I tried reproducing after upgrading to rails 5.1.0, I ran into: `private constant User::ActiveRecord_Associations_CollectionProxy referenced`.

**Comment by promptc3** [comment]
Try using `t.text :tags,array: true` and remove `default: []`.

**Comment by louim** [comment]
@s2t2 have you tried it without the `serialize(:tags, Array)` bit? Looking at the guides and [the array tests](https://github.com/rails/rails/blob/5-0-4/activerecord/test/cases/adapters/postgresql/array_test.rb), I think it's not needed when using PG arrays.

**Comment by alexcameron89** [comment]
@s2t2, I believe @louim is correct here. Here's a [reproducible script](https://gist.github.com/1fcf7f00cfad0aa9fe04f41e71a2318e) showing what you're doing and what he's recommending.

**Comment by s2t2** [comment]
yes @louim @alexcameron89 removing `serialize(:tags, Array)` was the trick! Thanks. Sorry for missing this in the docs, if it's there. Closing this issue now...

**Comment by kirs** [comment]
I made a safety check that would prevent issues like this one. Let me know what you think: https://github.com/rails/rails/pull/29520
