### ISSUE TITLE
update_attribute Updating more than one attribute

### ISSUE THREAD

**Issue by thierri** [rails/rails#29496]
### Steps to reproduce

On UserModel (for example), I have a method:

 ```
   Def UpdateToken
        	update_attribute(:columnA, newValueA)
		update_attribute(:columnB, newValueB)
   End
```

And also, an after_save command:

```
after_save :clean_columnC

   Def clean_columnC
        	self. clean_columnC = nil
   End
```

### Expected behavior
When I execute **UpdateToken**, I wish rails update only column A and B.

### Actual behavior
But instead, Rails updated Column A, and on the second **update_attribute** it updates Column B and Column C (setting it to nil).

### System configuration
**Rails version**:5.1.1

**Ruby version**: 2.4.0p0

**Comment by vipulnsward** [comment]
This is expected: https://github.com/vipulnsward/rails/blob/c0038f7c362fa0c92fc9e1ea3bdb2706f42386c6/activerecord/lib/active_record/persistence.rb#L259-L259
