### ISSUE TITLE
Make .sanitize_sql_for_assignment public

### ISSUE THREAD

**Issue by DamirSvrtan** [rails/rails#29507]
### Steps to reproduce

I want to execute a raw SQL query and pass it user generated parameters. 
I will execute a query with `ActiveRecord::Base.connection.execute(query)`. But first I will sanitize the parameters.

### Expected behavior
To sanitize parameters, I would expect to have a convenient method for sanitizing, such as:

`ActiveRecord::Base.sanitize_sql_for_assignment([query, params])`

### Actual behavior
Fortunately there is a method for sanitizing sql queries, however it is **private**. 
Even the [docs](http://api.rubyonrails.org/classes/ActiveRecord/Sanitization/ClassMethods.html#method-i-sanitize_sql_for_assignment) have an example on how to use it and advise to use it with send:

`Post.send(:sanitize_sql_for_assignment, { name: nil, group_id: 4 })`

If it's advised in the docs, it should not be private. I believe it is a perfectly valid use case to execute raw SQL and to sanitize it first, so I don't see a reason to make it private.

I would do this also for `sanitize_sql_for_conditions` and `sanitize_sql_for_order`.

### System configuration
**Rails version**:
5.0.3
**Ruby version**:
2.3.1

**Comment by rafaelfranca** [comment]
Thank you for the issue. We prefer to keep this method private so you keep the code that deal with SQL encapsulated in the model instead of spreading it in the other layers of your application.

**Comment by alexcameron89** [comment]
With what @rafaelfranca said, these methods are available within your models, and you can create a public method that references these methods. Here's an example: https://gist.github.com/alexcameron89/c384212d2c16e1046857d082e0709ef8

**Comment by louim** [comment]
If anyone lands here from a google seach, `sanitize_sql_` methods were made public in https://github.com/rails/rails/commit/9d43a84f73c1b3853a91d052a462ee60eccaf957, which is included in rails 5.2
