### ISSUE TITLE
Passing json params, with one param the same name as the controller set as false, causes the params object in the contoller to be created in an unexpected way

### ISSUE THREAD

**Issue by motevets** [rails/rails#29501]
### Steps to reproduce
1. create a new rails project
1. set `config/routes.rb` to be as follows:
    ```ruby
    Rails.application.routes.draw do
      post 'foo/echo'

      # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
    end
    ```
1. create a new file `app/controllers/foo_controller.rb` and fill it as follows:
    ```ruby
    class FooController < ApplicationController
      def echo
        params.permit!
        render plain: "The parameter 'foo' is set as #{params[:foo].as_json}"
      end
    end
    ```
1. start server with `rails s`
1. curl the new foo endpoint with the following command:
    ```bash
    curl http://localhost:3000/foo/echo -X POST -H "Content-Type: application/json" -d '{"foo": false, "bar": "baz"}'
    ```

### Expected behavior
Should see the output:
```
The parameter 'foo' is set as false
```

### Actual behavior
See the output:
```
The parameter 'foo' is set as {"foo"=>false, "bar"=>"baz"}
```

### System configuration
**Rails version**:
Rails 5.1.1
**Ruby version**:
2.3.4

**Comment by ztsuperman** [comment]
This parameter is added in lib/action_controller/metal/params_wrapper.rb
in this method: def process_action(*args)
...
wrapped_filtered_hash = _wrap_parameters request.filtered_parameters.slice(*wrapped_keys)
...
end


before wrapping, "foo"=>false, but after wrapping , it's overwrote by "foo"=>{"foo"=>false, "bar"=>"baz"}.
It happens when the wrapper key(controller name) is same as the parameter you passed in. 
So, I don't know if we should fix this, or we should just let people know you cannot pass in the parameter with the same name of the controller.

BTW, I've never contributed to Rails. But, I would like to. Can someone guide me how to contribute to Rails?

**Comment by rafaelfranca** [comment]
There is nothing to fix here. It is a documented feature called parameter wrappers http://api.rubyonrails.org/v5.1.1/classes/ActionController/ParamsWrapper.html. You can disable in your application if you want. It is inside the `config/initializers/wrap_parameters.rb` file. https://github.com/rails/rails/blob/master/railties/lib/rails/generators/rails/app/templates/config/initializers/wrap_parameters.rb.tt#L8

**Comment by motevets** [comment]
Thanks for your replies @rafaelfranca and @ztsuperman.  I read through that documentation, and I've observed it functioning as described in other controllers; however, it still seems to be behaving inconsistently in this particular example (perhaps for reasons that @ztsuperman described.)  One, because there is no model `Foo`, and two because it only does this wrapping when `foo` is passed as `false`.

For example, doing the same reproduction steps above, except curling with parameters with `foo` as `0` instead of `false`:
```bash
curl http://localhost:3000/foo/echo -X POST -H "Content-Type: application/json" -d '{"foo": 0, "bar": "baz"}'
```
gives the following output which does not wrap the parameters:
```
The parameter 'foo' is set as 0
```

Here is a repository of the rails app I am testing with, which was made using the reproduction steps in this issue: https://github.com/motevets/rails_param_same_name_as_controller

Is this a bug?  It seems odd that it wraps the parameters when a parameter with same name of the controller is set to `false`, but not for any other values.
