### ISSUE TITLE
api.rubyonrails.org doc has a typo

### ISSUE THREAD

**Issue by lustan3216** [rails/rails#29512]
Just a typo , is need to be <=> but == [ here is link](http://api.rubyonrails.org/classes/ActiveModel/Name.html#method-i-3C-3D-3E)

<img width="524" alt="2017-06-21 10 08 34" src="https://user-images.githubusercontent.com/12712127/27363882-a18b6e3e-5669-11e7-9d57-5641ae238f08.png">

**Comment by kamipo** [comment]
Fixed in ab0e455. Thanks!
