### ISSUE TITLE
form_with is not applying explicit id to select tag

### ISSUE THREAD

**Issue by hansondr** [rails/rails#29526]
### Steps to reproduce

`rails new testingapp`
`cd testingapp`
`rails g controller post new`

append the following to `app/views/post/new.html.erb`

```
<%= form_with scope: 'post' do |f| %>
  <%= f.label :category, for: :post_category %>
  <%= f.select :category, [1, 2, 3], id: :post_category, include_blank: 'Please choose' %>
<% end %>
```
Start rails server and browse to `/post/new`

### Expected behavior

Clicking on the 'Category' label should apply focus to the select box.  

**Generated HTML**

```html
<form action="/post/new" accept-charset="UTF-8" data-remote="true" method="post">
  <input name="utf8" type="hidden" value="&#x2713;" />
  <input type="hidden" name="authenticity_token" value="G<SNIP>Q==" />
  <label for="post_category">Category</label>
  <select name="post[category]" id="post_category">
    <option value="">Please choose</option>
    <option value="1">1</option>
    <option value="2">2</option>
    <option value="3">3</option>
  </select>
</form>
```

### Actual behavior

Clicking on the 'Category' label does not apply focus to the select box

**Generated HTML**

```html
<form action="/post/new" accept-charset="UTF-8" data-remote="true" method="post">
  <input name="utf8" type="hidden" value="&#x2713;" />
  <input type="hidden" name="authenticity_token" value="G<SNIP>Q==" />
  <label for="post_category">Category</label>
  <select name="post[category]">
    <option value="">Please choose</option>
    <option value="1">1</option>
    <option value="2">2</option>
    <option value="3">3</option>
  </select>
</form>
```

### System configuration
**Rails version**: 5.1.1

**Ruby version**: 2.4.0

**Comment by hansondr** [comment]
Digging into this it appears the correct syntax to get the `id` applied is:

```
<%= form_with scope: 'post' do |f| %>
  <%= f.label :category, for: :post_category %>
  <%= f.select :category, [1, 2, 3], { include_blank: 'Please choose' }, {  id: :post_category } %>
<% end %>
```

to explicitly split into the `options` and `html_options` hashes.  So not a bug just unwieldy behavior given the need for explicit `id` definitions now.  

Thoughts on combining `options` and `html_options` for initialization and splitting back into options and html_options within each actionview helper tag `render` method?

**Comment by y-yagi** [comment]
It is intentional that `form_with` does not generate DOM id.  Please see the description of #25197 for reason. 
However, tries to generate a DOM id in `form_with` is in progress. The PR is #29439.
