### ISSUE TITLE
bin/rails generate test_unit:helper Users doesn't do anything?

### ISSUE THREAD

**Issue by zenspider** [rails/rails#29523]
### Steps to reproduce

Exactly as the title says, executing the generator for any helper goes through the motions but generates nothing.

### System configuration
**Rails version**:

5.0.1

**Ruby version**:

2.4.0p1

**Comment by vipulnsward** [comment]
Yeah, looks like we don't do anything there, just execute the hook.

https://github.com/vipulnsward/rails/commit/e5e4d08450642c77c5e4f8051d478663c57d97a3

**Comment by rafaelfranca** [comment]
Yes, that is by design. Rails doesn't generate helper tests, but we need the hook for test frameworks that does like rspec.
