### ISSUE TITLE
HABTM Association: Default Join table naming is not as expected.

### ISSUE THREAD

**Issue by t-deetiw** [rails/rails#29530]
source: [code link](https://github.com/rails/rails/blob/master/activerecord/lib/active_record/associations/builder/has_and_belongs_to_many.rb#L14)
### Steps to reproduce

=> Regex being Used in the source.

```
## Join Table name for "signup_flow_categories" and "signup_flows"

## In Rails >= 4
["signup_flow_categories", "signup_flows"].sort.join("\0").gsub(/^(.*[._])(.+)\0\1(.+)/, '\1\2_\3').tr("\0", "_") 
=> "signup_flow_categories_flows"

## In Rails < 4
# It was same as
["signup_flow_categories", "signup_flows"].sort.join("_")
=> "signup_flow_categories_signup_flows"

```

### Expected behavior
We are in process of upgrading rails from 3.2.22 to 4.2.8. 
We were expecting the join table names to be ```"signup_flow_categories_signup_flows"``` for the given example.

### Actual behavior
But join table name is truncated to ``` "signup_flow_categories_flows" ```
We are not sure whether this way the naming should be but its a bit misleading.
So please clarify on this.

As an alternative we can use ```join_table``` option anytime but we have to be more explicit in the code.

### System configuration
**Rails version**: 4.2.8

**Ruby version**: 2.2.2

**Comment by alexcameron89** [comment]
Hey @t-deetiw,

The `join_table` method you referenced follows the same derivation as `create_join_table` in migrations which uses [`derive_join_table_name`](https://github.com/rails/rails/blob/master/activerecord/lib/active_record/model_schema.rb#L156). In `derive_join_table_name`'s documentation, it mentions that it removes common prefixes, so here it sees the `signup_flow` as a common prefix(possibly a namespace) and removes it.

As you mentioned, using the `join_table` option will allow you to specify the table name.

**Comment by alexcameron89** [comment]
Here's a [Pull Request](https://github.com/rails/rails/pull/16219) and the [issue it was resolving](https://github.com/rails/rails/issues/13683) for additional context. I'm going to close this as expected behavior.
