### ISSUE TITLE
Rails update from 5.0.0 to 5.1.1 assets in public folder not found 

### ISSUE THREAD

**Issue by emmanuelmillionaer** [rails/rails#29535]
### Steps to reproduce
I update a project from Rails 5.0.0 to Rails 5.1.1

This project is not using the webpacker gem, but puts the assets with it's own webpack-procedure into the `public` folder.

### Expected behavior
With Rails 5.0.0 I was displaying images in my views with:

    image_path("user/favicon.png") => localhost:3000/images/user/favicon.png

### Actual behavior
 In Rails 5.1.1 when I do the same I get:

    Sprockets::Rails::Helper::AssetNotFound

for 

    image_path("user/favicon.png")

**Which helpers should I use to access the assets in the public folder with Rails 5.1.1?**: Thanks

Thanks to all maintainers 🙂  You're doing an amazing job 🥇 💯

**Comment by y-yagi** [comment]
From sprockets-rails 3.2.0, an error occurs if asset does not exist in asset pipeline. 
If want to use helper method without asset pipeline, need to specify the `skip_pipeline` option.  

Like this. 

```ruby 
image_path("user/favicon.png", skip_pipeline: true) 
``` 
Ref: #26226

Or if want to enable asset fallback for the entire application,
`config.assets.unknown_asset_fallback` can be set to true. 
See: http://guides.rubyonrails.org/asset_pipeline.html#raise-an-error-when-an-asset-is-not-found

**Comment by emmanuelmillionaer** [comment]
Hi @y-yagi big thanks for your help! 👍  I'm using the `unknown_asset_fallback` solution now. Have a great weekend! 💯
