### ISSUE TITLE
`ActionDispatch::DebugExceptions` won't show an exception if it itself throws an exception

### ISSUE THREAD

**Issue by thegedge** [rails/rails#29537]
`ActionDispatch::DebugExceptions` won't show an exception if it itself throws an exception making it difficult to trace the initial exception.

In my particular case, `ActionDispatch::DebugExceptions` received an exception that responds to `annoted_source_code`, but that function returns `nil` which ends up in [`log_array` raising `NoMethodError: undefined method 'join' for nil:NilClass`](https://github.com/rails/rails/blob/55a443b847ccf37aa8fb62fbc827f5b540980dd9/actionpack/lib/action_dispatch/middleware/debug_exceptions.rb#L177-L183).

To go a step further, the underlying exception was an `ActionView::Template::Error`, and the `line_number` of the exception was beyond the number of lines in the underlying template.

### Steps to reproduce

Unfortunately, I haven't been able to create an MVP to reproduce this issue.

### Expected behavior
Although it's expected for this to happen, my expectation is that `DebugExceptions` would be as immune as possible to throwing any exceptions. In this particular case, I'd expect it to show the exception backtrace without any annotated source code.

### Actual behavior
`DebugExceptions` middleware throws its own exception, making it difficult to know what the underlying exception actually was.

### System configuration
**Rails version**:
5.0.3

**Ruby version**:
2.3.3

**Comment by gsamokovarov** [comment]
Hey, @thegedge we're trying to tackle that in: https://github.com/rails/rails/pull/29131. I'll also take a look at the `log_array` issue.
