### ISSUE TITLE
actioncable reconnect same connection and resend same actions again.

### ISSUE THREAD

**Issue by islam-taha** [rails/rails#29545]
### Steps to reproduce

This was generated using a standalone javascript client 

1. Start server then start your client.
2. After actioncable on client successfully connected to server, stop rails server.
3. Wait until actioncable client connection fails and starts retrying to reconnect to server.
4. Reboot your server.

### Expected behavior
Actioncable should not recreate duplicate connection with same messages again, which duplicate whatever the behavior is in the sent to-channel, as an example: if i create a record on a sent action called "speak", after reconnecting again during the same session, "speak" action is called again which will duplicate the record with unessential call from actioncable.

### Actual behavior
Actioncable start another connection similar to the already fired 101-one at the very beginning.

### System configuration
**Rails version**: 5.0.2
**Ruby version**: ruby 2.3.1p112 (2016-04-26 revision 54768) [x86_64-darwin16]

**Comment by palkan** [comment]
Hi, @islam-taha!

Could you, please, clarify this part:

>  if i create a record on a sent action called "speak", after reconnecting again during the same session, "speak" action is called again which will duplicate the record with unessential call from actioncable.

It would be great if you share your client-side code and server logs.

**Comment by islam-taha** [comment]
What i meant, is when client-side actioncable performs an action "speak", then the server got disconnected, the client-side will try to reconnect to server side, after it reconnected again, it will performs all alread-perfomed actions from the last connection (before disconnection).

Here is a snippet of client-side code which sends params during subscription:
```
window.cable.subscriptions.create({
        channel: 'MessagesChannel',
        guest: true,
        uid: uid,
        user_id: this.props.curUser.id,
        body: this.state.textAreaValue,
        attachment: this.state.screenShotDataURL,
        conversation_id: (this.props.curConversation || {}).id,
      }, {
        received: (data) => {
          if (typeof data.message === 'string') {
            const curMessage = JSON.parse(data.message);
            this.props.onMessageRecieved(curMessage);
          }
        },
      });
```

Server logs don't have any special logs, it's just streaming_from and unsubscribed infos, but here is another snippet from server side messages_channel.rb which uses before_subscribe to create a conversation in order to be streamed_from:

```
  before_subscribe lambda {
    create_conversation
  }

  def subscribed
      stream_from "conversation_#{@conversation.id}"
  end
``` 

**NOTE**: that's one case different from a special action that is recalled on reconnection, but it also act here as a case, where in reconnection before_subscribe is called again which in return recreate another conversation of the same message that had been sent during the last connection.
