### ISSUE TITLE
cruby.so cannot be loaded while starting the server

### ISSUE THREAD

**Issue by wjh94** [rails/rails#29548]
### Steps to reproduce

Run rails server

### Expected behavior
C:\Users\jianh\sistem_tugas_akhir>rails s
=> Booting Puma
=> Rails 5.0.4 application starting in development on http://localhost:3000
=> Run `rails server -h` for more startup options
Exiting

### Actual behavior
C:\Users\jianh\sistem_tugas_akhir>rails s
=> Booting Puma
=> Rails 5.0.4 application starting in development on http://localhost:3000
=> Run `rails server -h` for more startup options
Exiting
C:/RailsInstaller/Ruby2.2.0/lib/ruby/gems/2.2.0/gems/activesupport-5.0.4/lib/active_support/dependencies.rb:293:in `require': 1114: A dynamic link library (DLL) initialization routine failed.   - C:/RailsInstaller/Ruby2.2.0/lib/ruby/gems/2.2.0/extensions/x86-mingw32/2.2.0/bindex-0.5.0/bindex/cruby.so (LoadError)
        from C:/RailsInstaller/Ruby2.2.0/lib/ruby/gems/2.2.0/gems/activesupport-5.0.4/lib/active_support/dependencies.rb
:293:in `block in require'
        from C:/RailsInstaller/Ruby2.2.0/lib/ruby/gems/2.2.0/gems/activesupport-5.0.4/lib/active_support/dependencies.rb
:259:in `load_dependency'
        from C:/RailsInstaller/Ruby2.2.0/lib/ruby/gems/2.2.0/gems/activesupport-5.0.4/lib/active_support/dependencies.rb
:293:in `require'
        from C:/RailsInstaller/Ruby2.2.0/lib/ruby/gems/2.2.0/gems/bindex-0.5.0/lib/bindex.rb:7:in `<top (required)>'
        from C:/RailsInstaller/Ruby2.2.0/lib/ruby/gems/2.2.0/gems/activesupport-5.0.4/lib/active_support/dependencies.rb
:293:in `require'
        from C:/RailsInstaller/Ruby2.2.0/lib/ruby/gems/2.2.0/gems/activesupport-5.0.4/lib/active_support/dependencies.rb
:293:in `block in require'
        from C:/RailsInstaller/Ruby2.2.0/lib/ruby/gems/2.2.0/gems/activesupport-5.0.4/lib/active_support/dependencies.rb
:259:in `load_dependency'
        from C:/RailsInstaller/Ruby2.2.0/lib/ruby/gems/2.2.0/gems/activesupport-5.0.4/lib/active_support/dependencies.rb
:293:in `require'
        from C:/RailsInstaller/Ruby2.2.0/lib/ruby/gems/2.2.0/gems/web-console-3.5.1/lib/web_console/railtie.rb:9:in `blo
ck in <class:Railtie>'
        from C:/RailsInstaller/Ruby2.2.0/lib/ruby/gems/2.2.0/gems/railties-5.0.4/lib/rails/initializable.rb:30:in `insta
nce_exec'
        from C:/RailsInstaller/Ruby2.2.0/lib/ruby/gems/2.2.0/gems/railties-5.0.4/lib/rails/initializable.rb:30:in `run'
        from C:/RailsInstaller/Ruby2.2.0/lib/ruby/gems/2.2.0/gems/railties-5.0.4/lib/rails/initializable.rb:55:in `block
 in run_initializers'
        from C:/RailsInstaller/Ruby2.2.0/lib/ruby/2.2.0/tsort.rb:226:in `block in tsort_each'
        from C:/RailsInstaller/Ruby2.2.0/lib/ruby/2.2.0/tsort.rb:348:in `block (2 levels) in each_strongly_connected_com
ponent'
        from C:/RailsInstaller/Ruby2.2.0/lib/ruby/2.2.0/tsort.rb:429:in `each_strongly_connected_component_from'
        from C:/RailsInstaller/Ruby2.2.0/lib/ruby/2.2.0/tsort.rb:347:in `block in each_strongly_connected_component'
        from C:/RailsInstaller/Ruby2.2.0/lib/ruby/2.2.0/tsort.rb:345:in `each'
        from C:/RailsInstaller/Ruby2.2.0/lib/ruby/2.2.0/tsort.rb:345:in `call'
        from C:/RailsInstaller/Ruby2.2.0/lib/ruby/2.2.0/tsort.rb:345:in `each_strongly_connected_component'
        from C:/RailsInstaller/Ruby2.2.0/lib/ruby/2.2.0/tsort.rb:224:in `tsort_each'
        from C:/RailsInstaller/Ruby2.2.0/lib/ruby/2.2.0/tsort.rb:203:in `tsort_each'
        from C:/RailsInstaller/Ruby2.2.0/lib/ruby/gems/2.2.0/gems/railties-5.0.4/lib/rails/initializable.rb:54:in `run_i
nitializers'
        from C:/RailsInstaller/Ruby2.2.0/lib/ruby/gems/2.2.0/gems/railties-5.0.4/lib/rails/application.rb:352:in `initia
lize!'
        from C:/Users/jianh/sistem_tugas_akhir/config/environment.rb:5:in `<top (required)>'
        from C:/Users/jianh/sistem_tugas_akhir/config.ru:3:in `require_relative'
        from C:/Users/jianh/sistem_tugas_akhir/config.ru:3:in `block in <main>'
        from C:/RailsInstaller/Ruby2.2.0/lib/ruby/gems/2.2.0/gems/rack-2.0.3/lib/rack/builder.rb:55:in `instance_eval'
        from C:/RailsInstaller/Ruby2.2.0/lib/ruby/gems/2.2.0/gems/rack-2.0.3/lib/rack/builder.rb:55:in `initialize'
        from C:/Users/jianh/sistem_tugas_akhir/config.ru:in `new'
        from C:/Users/jianh/sistem_tugas_akhir/config.ru:in `<main>'
        from C:/RailsInstaller/Ruby2.2.0/lib/ruby/gems/2.2.0/gems/rack-2.0.3/lib/rack/builder.rb:49:in `eval'
        from C:/RailsInstaller/Ruby2.2.0/lib/ruby/gems/2.2.0/gems/rack-2.0.3/lib/rack/builder.rb:49:in `new_from_string'

        from C:/RailsInstaller/Ruby2.2.0/lib/ruby/gems/2.2.0/gems/rack-2.0.3/lib/rack/builder.rb:40:in `parse_file'
        from C:/RailsInstaller/Ruby2.2.0/lib/ruby/gems/2.2.0/gems/rack-2.0.3/lib/rack/server.rb:319:in `build_app_and_op
tions_from_config'
        from C:/RailsInstaller/Ruby2.2.0/lib/ruby/gems/2.2.0/gems/rack-2.0.3/lib/rack/server.rb:219:in `app'
        from C:/RailsInstaller/Ruby2.2.0/lib/ruby/gems/2.2.0/gems/railties-5.0.4/lib/rails/commands/server.rb:84:in `app
'
        from C:/RailsInstaller/Ruby2.2.0/lib/ruby/gems/2.2.0/gems/rack-2.0.3/lib/rack/server.rb:354:in `wrapped_app'
        from C:/RailsInstaller/Ruby2.2.0/lib/ruby/gems/2.2.0/gems/railties-5.0.4/lib/rails/commands/server.rb:148:in `lo
g_to_stdout'
        from C:/RailsInstaller/Ruby2.2.0/lib/ruby/gems/2.2.0/gems/railties-5.0.4/lib/rails/commands/server.rb:102:in `st
art'
        from C:/RailsInstaller/Ruby2.2.0/lib/ruby/gems/2.2.0/gems/railties-5.0.4/lib/rails/commands/commands_tasks.rb:90
:in `block in server'
        from C:/RailsInstaller/Ruby2.2.0/lib/ruby/gems/2.2.0/gems/railties-5.0.4/lib/rails/commands/commands_tasks.rb:85
:in `tap'
        from C:/RailsInstaller/Ruby2.2.0/lib/ruby/gems/2.2.0/gems/railties-5.0.4/lib/rails/commands/commands_tasks.rb:85
:in `server'
        from C:/RailsInstaller/Ruby2.2.0/lib/ruby/gems/2.2.0/gems/railties-5.0.4/lib/rails/commands/commands_tasks.rb:49
:in `run_command!'
        from C:/RailsInstaller/Ruby2.2.0/lib/ruby/gems/2.2.0/gems/railties-5.0.4/lib/rails/commands.rb:18:in `<top (required)>'
        from bin/rails:4:in `require'
        from bin/rails:4:in `<main>'

### System configuration
**Rails version**: 5.0.4

**Ruby version**: 2.2.6p396

**Comment by robin850** [comment]
Hi @wjh94,

This is not a Ruby on Rails issue. It's either a RailsInstaller or a Windows issue. A quick search shows that you may try another port to run your server, doing something like `rails s -p 5000`. Thanks for reporting anyway!

**Comment by schneems** [comment]
This is an issue with your installation of ruby on your system. It does not appear to be a problem with rails. 

Did it work previously?

Likely an issue with with rails installer or chruby or simply a bad installnof some tool.
