### ISSUE TITLE
Select form helper handles selected option incorrectly

### ISSUE THREAD

**Issue by IngoAlbers** [rails/rails#29562]
### Steps to reproduce
```
<%= form_for :values do |f| %>
  <%= f.select 'x', options_for_select(['1', '2']), { prompt: true, selected: '2' }, required: true %>
<% end %>
```

### Expected behavior
The select should have a prompt. The value '2' should be selected. HTML is valid.

This works if you set the selected value by passing it in `options_for_select`:

```
<%= form_for :values do |f| %>
  <%= f.select 'x', options_for_select(['1', '2'], '2'), { prompt: true }, required: true %>
<% end %>
```

This generates following HTML:

```
<select required="required" name="values[x]" id="values_x">
  <option value="">Please select</option>
  <option value="1">1</option>
  <option selected="selected" value="2">2</option>
</select>
```

### Actual behavior

The select does not have prompt. Value '2' is not selected.
Following HTML is generated:

```
<select required="required" name="values[x]" id="values_x">
  <option value="1">1</option>
  <option value="2">2</option>
</select>
```
This HTML is invalid, as a placeholder value is necessary for required selects with size of 1 and multiple false. 
See: https://github.com/rails/rails/commit/077540738460d44c1463b3e52d2acb1fed9bc766

If it is not intended to use the `selected` option like that, it should be ignored.

### System configuration
**Rails version**: 5.1.1

**Ruby version**: 2.4.1

**Comment by savroff** [comment]
Confirmed.  Already working on fix

Rails version: 5.1.1
Ruby version: 2.4.1

**Comment by rafaelfranca** [comment]
@savroff is right. When you use `options_for_select` you need to pass the select option there and `pront` only show up if there is no value selected.

**Comment by IngoAlbers** [comment]
@savroff I just used it, so that I have 2 very similar examples, with the only difference being where the selected value is set. Your example with the disabled is actually a totally different behaviour. The 1 should still be selectable.

@rafaelfranca Yes. I know that's how to make it work correctly. As you can see in the expected behavior example that I posted. I just wanted to report this wrong behavior if you set the selected option in this way. In my opinion it should not break the behavior if the `selected` option is passed in this way. The option should either be ignored or handled correctly.

> pront only show up if there is no value selected.
This is wrong information. As you can see in the expected behaviour example, I still have the prompt and a preselected value.

**Comment by rafaelfranca** [comment]
From the documentation:

> :prompt - set to true or a prompt string. When the select element doesn't have a value yet, this prepends an option with a generic prompt - “Please select” - or the given prompt string.

In your case the prompt was showing because you used `options_for_select(['1', '2'], '2')` to select the value not the `select` method.
