### ISSUE TITLE
Yarn assets paths aren't compiled properly for production

### ISSUE THREAD

**Issue by amingilani** [rails/rails#29563]
### Steps to reproduce

Demo: https://warm-garden-98956.herokuapp.com/
Source: https://github.com/amingilani/rails-sprockets-path-bug

You can clone the source from above, but the steps to recreate are:

* Create a rails app
* Include a css framework with yarn, e.g. `yarn semantic-ui-css`
* Require it in `application.css` with `require semantic-ui-css/semantic.min.css`
* Add font files in the pipeline but editing `assets.rb` with `Rails.application.config.assets.precompile << /\.(?:svg|eot|woff|ttf)$/`
* Create a view that uses included icon fonts
* Verify that the app renders as wanted in development
* Precompile assets
* Deploy to production

*Or just use my [example app](https://github.com/amingilani/rails-sprockets-path-bug)*

### Expected behavior

It should display properly as in development:
<img width="125" alt="screen shot 2017-06-25 at 3 04 17 am" src="https://user-images.githubusercontent.com/1188552/27512220-0e98ea6a-5953-11e7-8c00-64e176cd1a84.png">

### Actual behavior
The icon font did not load and I see a blank square:
<img width="141" alt="screen shot 2017-06-25 at 3 04 24 am" src="https://user-images.githubusercontent.com/1188552/27512223-1c79ce4c-5953-11e7-938b-10fea0ccca8f.png">

Errors on the console show:

>GET https://warm-garden-98956.herokuapp.com/assets/themes/default/assets/fonts/icons.woff 
warm-garden-98956.herokuapp.com/:1
>GET https://warm-garden-98956.herokuapp.com/assets/themes/default/assets/fonts/icons.ttf 404 (Not Found)

The path is incorrectly identified as:  
`/assets/themes/default/assets/fonts/icons.woff `

Upon browsing through the precompiled assets, and checking out for myself, I can see that the font is actually at:  
`/assets/semantic-ui-css/themes/default/assets/fonts/icons-ba0c59deb5450f5cb41b3f93609ee2d0d995415877ddfa223e8a8a7533474f07.woff`

### System configuration

```
$ ruby -v
ruby 2.4.0p0 (2016-12-24 revision 57164) [x86_64-darwin16]
$ rails -v
Rails 5.1.1
```

**Comment by rafaelfranca** [comment]
Yarn css not always works automatically in a Rails applicaiton. It depends on how the css library links to external image. To them work they need to use the rails helpers and that is not always the case. It is also not the case of these css

**Comment by amingilani** [comment]
@rafaelfranca yes but that clearly affects not just this library, but many other pure CSS libraries that don't use rails helpers and are installed via `yarn`

Is there a workaround for this, or any plans on a fix?

**Comment by rafaelfranca** [comment]
No plans to fix, neither workarounds. This problem also exists with any pure css libraries that don't use rails helpers and are not installed via `yarn`.

**Comment by amingilani** [comment]
Workaround found [here](https://stackoverflow.com/a/45580349/3970701) using webpack!

**Comment by juanbrein** [comment]
Another workaround that works for me

Create folder `public/node_assets` and copy over the images / fonts there

Add the following task:

`
# lib/tasks/precompile.rake
namespace :assets do                                             
  desc 'Compile all the assets named in config.assets.precompile'
  task :precompile do
    Dir.chdir File.join('public', 'assets')         
    Dir['../node_assets/*'].each do |asset|         
      FileUtils.ln_s asset, '.'                     
    end                                                          
  end                                                            
end                                                              
`

run `rails assets:precompile`

**Comment by maxivak** [comment]
I had the same problem.
I managed it as follows:

assets.rb:
```
# yarn
Rails.application.config.assets.paths << Rails.root.join('node_modules')

# font-awesome fonts
Rails.application.config.assets.precompile << %r{font-awesome/fonts/[\w-]+\.(?:eot|svg|ttf|woff2?)$}

```

application.scss:
```
$fa-font-path: "font-awesome/fonts";
@import 'font-awesome/scss/font-awesome';
```

package.json:
```
{
  "name": "mysite",
  "version": "1.0.0",
  "main": "index.js",
  "repository": "...",
  "author": "mmx <maxivak@gmail.com>",
  "license": "MIT",
  "dependencies": {
    "bootstrap": "4.0.0-beta.2",
    "font-awesome": "^4.7.0",
    "jquery": "3.2.1",
    "popper.js": "1.12.4"
  }
}

```


after `yarn install` files appear in node_modules/font-awesome/fonts.
After 'rake assets:precompile' files for fonts should appear in `public/assets/font-awesome/fonts/` folder.
