### ISSUE TITLE
association methods do not cache since Rails v5

### ISSUE THREAD

**Issue by tonytonyjan** [rails/rails#29570]
### Steps to reproduce

(Guidelines for creating a bug report are [available
here](http://guides.rubyonrails.org/contributing_to_ruby_on_rails.html#creating-a-bug-report))

1. Create a new project with version >= 5

```
$ rails new myapp
$ cd myapp
$ bin/rails g model Post title content:text
$ bin/rails g model Tag name post:references
$ bin/rails db:create db:migrate
$ echo 'class Post < ApplicationRecord; has_many :tags end' > app/models/post.rb
$ bin/rails r 'Post.create.tap{|post| post.tags.create}'
$ bin/rails c
Running via Spring preloader in process 70422
Loading development environment (Rails 5.1.2.rc1)
irb(main):001:0> post = Post.first
  Post Load (0.3ms)  SELECT  "posts".* FROM "posts" ORDER BY "posts"."id" ASC LIMIT $1  [["LIMIT", 1]]
=> #<Post id: 1, title: nil, content: nil, created_at: "2017-06-25 14:56:47", updated_at: "2017-06-25 14:56:47">
irb(main):002:0> post.tags
  Tag Load (0.3ms)  SELECT  "tags".* FROM "tags" WHERE "tags"."post_id" = $1 LIMIT $2  [["post_id", 1], ["LIMIT", 11]]
=> #<ActiveRecord::Associations::CollectionProxy [#<Tag id: 1, name: nil, post_id: 1, created_at: "2017-06-25 14:56:47", updated_at: "2017-06-25 14:56:47">]>
irb(main):003:0> post.tags
  Tag Load (0.4ms)  SELECT  "tags".* FROM "tags" WHERE "tags"."post_id" = $1 LIMIT $2  [["post_id", 1], ["LIMIT", 11]]
=> #<ActiveRecord::Associations::CollectionProxy [#<Tag id: 1, name: nil, post_id: 1, created_at: "2017-06-25 14:56:47", updated_at: "2017-06-25 14:56:47">]>
irb(main):004:0>
```

### Expected behavior
Tell us what should happen

According to [this guide](http://guides.rubyonrails.org/association_basics.html#controlling-caching), in Rails console, `Tag Load (ms)` should only spear once because of caching.

### Actual behavior
Tell us what happens instead

`post.tags` does not cache and will repeat querying the database every time.

### System configuration
**Rails version**: 5.1.1

**Ruby version**: 2.4.1

**Comment by eugeneius** [comment]
This is a consequence of https://github.com/rails/rails/pull/28592 - calling `inspect` on an unloaded relation no longer causes it to become loaded. The new behaviour is better, since `inspect` really shouldn't mutate its receiver.

The section of the Associations guide you linked to is slightly misleading, as calling `author.books` won't load the relation. I think those lines should be changed to use `author.books.load` instead.

**Comment by rafaelfranca** [comment]
Correct. The method still cache, but not with `inspect`. Could you update the documentation?
