### ISSUE TITLE
distance_of_time_in_hours returns the wrong result

### ISSUE THREAD

**Issue by tolien** [rails/rails#29582]
Seems to be a regression in Rails 5.1.2 - I've tried reproducing with 5.1.1 and got the expected result.

### Steps to reproduce

Easiest to do use the REPL:

```
require 'action_view'
include ActionView::Helpers::DateHelper
distance_of_time_in_words(Time.now - 1.hour, Time.now)
```

### Expected behavior
Get "1 hour"

### Actual behavior
 => "12960000 hours"

### System configuration
**Rails version**: 5.1.2
**Ruby version**: ruby 2.4.1p111 (2017-03-22 revision 58053) [x86_64-linux]
I can also reproduce it with ruby 2.4.1p111 (2017-03-22 revision 58053) [x86_64-darwin16]

**Comment by tolien** [comment]
Started digging into this further.

First thing, I’m using the dotiw gem, which uses Numeric#divmod to break the difference between the two Times into a hash, so my next step was to use divmod directly to eliminate the dotiw gem:
3600.divmod(1.hour)
=> [12960000, -12960000 hours and 3600 seconds]

Numeric#divmod does, for x.divmod(y), q = (x/y) so I tried 3600/ 1.hour:
=> 3600 hours

The root cause seems to be that 3600 / 1.hour now returns 3600 hours, when previously it returned 1 hour.

That looks like the change from PR #29163?

**Comment by pavel-jurasek-joincoup-com** [comment]
@tolien I did more generic error case as well https://github.com/rails/rails/issues/29592

**Comment by ahazem** [comment]
@tolien This https://github.com/rails/rails/pull/29594 fixes the issue for `5-1-stable`.
