### ISSUE TITLE
5.1.2 memory leak on production

### ISSUE THREAD

**Issue by ideo-henry** [rails/rails#29596]
### Expected behavior
Upgraded from Rails 5.1.1 to 5.1.2 , and no code changes should be required.

### Actual behavior
`NoMemoryError (failed to allocate memory)`
`Errno::ENOMEM (Cannot allocate memory - nodejs)`

### System configuration
**Rails version**:
5.1.2
**Ruby version**:
2.3.1

**Comment by rafaelfranca** [comment]
You need to give us more information on how to reproduce this issue, otherwise there is nothing we can do. Please read CONTRIBUTING.md file for more information about creating bug reports. Thanks!
