### ISSUE TITLE
Calculate duration it has been changed between 5.1.1 and 5.1.2

### ISSUE THREAD

**Issue by pavel-jurasek-joincoup-com** [rails/rails#29592]
### Steps to reproduce

Related to: https://github.com/rails/rails/pull/29163

Rails 5.1.1

For simplification i cast `ActiveSupport::TimeWithZone` from DateTime but currently we getting this object directly from ActiveRecord (`created_at` and `updated_at`) for example.

```ruby
rental_end = DateTime.parse('01-01-2017 12:45:00').utc.in_time_zone('Europe/Berlin')
rental_start = DateTime.parse('01-01-2017 12:00:00').utc.in_time_zone('Europe/Berlin')
(rental_end - rental_start) / 1.hour
=> 0.75
```

### Expected behavior

I would say it's fine to keep ActiveSupport::Duration but should be mention in Changelog as breaking change.

### Actual behavior

Rails 5.1.2

```ruby
rental_end = DateTime.parse('01-01-2017 12:45:00').utc.in_time_zone('Europe/Berlin')
rental_start = DateTime.parse('01-01-2017 12:00:00').utc.in_time_zone('Europe/Berlin')
(rental_end - rental_start) / 1.hour
=> 2700.0 hours
```

Can be fixed with explicit conversion to scalar type (Float)

```ruby
rental_end = DateTime.parse('01-01-2017 12:45:00').utc.in_time_zone('Europe/Berlin')
rental_start = DateTime.parse('01-01-2017 12:00:00').utc.in_time_zone('Europe/Berlin')
(rental_end.to_f - rental_start.to_f) / 1.hour.to_f
=> 0.75
```

### System configuration
**Rails version**: 5.1.1

**Ruby version**: 2.4.1 2.4.1p111 (2017-03-22 revision 58053) [x86_64-linux]

**Comment by rafaelfranca** [comment]
cc @pixeltrix

**Comment by tolien** [comment]
@pixeltrix I'm looking mainly at the division method but does it make more sense to do the conversion to seconds when populating new_parts, i.e. to do

```
new_parts = other.parts.map { |part, other_value| [part, value / (Duration::PARTS_IN_SECONDS[part] * other_value)] }.to_h
new_value = new_parts.inject(0) { |total, (part, value)| total + value  }
```

This seems to still work for the test cases given in the original PR:
```
> Time.zone = "Beijing"           # => "Beijing"
> date = Date.civil(2017, 5, 20)  # => Sat, 20 May 2017
> 2 * 1.day                       # => 2 days
> date + 2 * 1.day                #  => Mon, 22 May 2017
```
but also fixes the issue above:
```
rental_end = DateTime.parse('01-01-2017 12:45:00').utc.in_time_zone('Europe/Berlin')
rental_start = DateTime.parse('01-01-2017 12:00:00').utc.in_time_zone('Europe/Berlin')
(rental_end - rental_start) / 1.hour
=> 0.75 hours
```
(5.1.1 returned 0.75 seconds - so at least this way the unit also makes sense)

**Comment by doits** [comment]
You can fix it by replacing `1.hour` by the amount of seconds (`3600`):

```ruby
(rental_end - rental_start) / 3600
=> 0.75
```

It looks like multiplication and division with a `ActiveSupport::Duration` is really flaky atm (#29603 is a similar problem, albeit it has it's roots in Rails 5.1 already)

**Comment by pavel-jurasek-joincoup-com** [comment]
@doits as you said i could it's not that i am not able to fix it it's more about process this change should be optional with soft deprecation warning... I would not expect that minor version Rails would break code base who survived from Rails 3.2 :)

**Comment by rafaelfranca** [comment]
@pavel-jurasek-joincoup-com usually they don't, and we could have avoided that if people tested the release candidates. Now that it is out people will have to wait it to be fixed.

**Comment by koic** [comment]
AFAIK, Rails 5.1.2 uses `.second` (or `seconds`) instead of `.to_f` to return the same value as Rails 5.1.1.

```console
> (rental_end - rental_start) / 1.hour.seconds
=> 0.75 seconds
```

This is to get an instance of `ActiveSupport::Duration`, not an instance of `Float`.

**Comment by dmke** [comment]
We've run into this as well, having code like

```ruby
# in app/helpers/
def number_to_human_duration(number)
  if (number%7.days) == 0
    u, n = :w, number / 7.days
  elsif number >= 24.hours
    u, n = :d, number / 24.hours
  elsif number >= 1.hour
    u, n = :h, number / 1.hour
  else
    u, n = :min, number / 60
  end
  pluralize n, DURATION_UNITS[u].singular, DURATION_UNITS[u].plural
end
```

which broke when upgrading to 5.1.2 (our hotfix is to append a `to_i` to the duration instances). If I recall correctly, this is a breaking change for functionality already present in Rails 2...

If `Date#+` is the problem, this should have been fixed in [`Date::DateAndTime::Calculations#plus_with_duration`](https://github.com/rails/rails/blob/5-1-stable/activesupport/lib/active_support/core_ext/date/calculations.rb#L88), no?

**Comment by doits** [comment]
Just tested `5.1.3.rc1`, and it is still broken

**Comment by csrutil** [comment]
I got that issue last night.
```bash
➜ rails c
Loading development environment (Rails 5.1.2)
irb(main):001:0> 1.days / 4
0 days
```

```bash
➜ rails c
Loading development environment (Rails 4.2.8)
irb(main):001:0> 1.days / 4
21600
```

**Comment by francocatena** [comment]
It is still broken on ```5.1.3.rc2```, can you take a look @kaspth?

Sorry to mention here instead of a new issue as instructed on the release post, but think the context is important.

**Comment by pixeltrix** [comment]
@rafaelfranca @kaspth I'll take a look at this today

**Comment by pixeltrix** [comment]
FYI, this is what I think should be the outcome of the various ways in which a duration is involved in division:

```
duration / numeric = duration
numeric / duration = numeric (assumes numerator is a duration in seconds)
duration / duration = numeric
```

This means if you do this:

``` ruby
(Date.tomorrow - Date.today) / 1.hour
```

Then the result isn't going to be 24 as you might think because `Date#-` returns days and not seconds. You would need to wrap the subtraction with a `.days` to make it work:

``` ruby
(Date.tomorrow - Date.today).days / 1.hour
```

The only other way to make it work would be to override `Date#-` and friends to return a duration which we don't want to do.

**Comment by Sayanc93** [comment]
@pixeltrix I've done similar changes on https://github.com/rails/rails/pull/29953

**Comment by pixeltrix** [comment]
@Sayanc93 I think where we have a `duration / duration` we should explicitly return a numeric since according to dimensional analysis the units on the numerator and denominator cancel each other out - that's what my change in #29971 does.

**Comment by espen** [comment]
5.1.2 broke my app and 5.1.3.rc3 is now giving me green tests 🙇
