### ISSUE TITLE
transform_keys returns Hash even if invoked class is an inhertited class

### ISSUE THREAD

**Issue by sreekanthgs** [rails/rails#29590]
### Steps to reproduce

class MyHash < Hash
end

obj = MyHash.new
obj = obj.merge({foo: :bar}).symbolize_keys

### Expected behavior
Class of obj should be MyHash

### Actual behavior
Class of obj is Hash

### Root Cause Analysis
This issue was solved in Rails 4.2.x stable. However, it has reappeared in 5.x.x

Fix Line in 4.2.x stable: https://github.com/rails/rails/blob/4-2-stable/activesupport/lib/active_support/core_ext/hash/keys.rb#L10

Buggy Line in 5.1.x stable: https://github.com/rails/rails/blob/5-1-stable/activesupport/lib/active_support/core_ext/hash/keys.rb#L14 

### System configuration
**Rails version**: 5.1.2
**Ruby version**: 2.4.1

**Comment by Sayanc93** [comment]
I believe that was the intention. Check this commit https://github.com/rails/rails/commit/64ae9a58ae54d7d036e930e75fac3e4a1ab0052e

**Comment by sreekanthgs** [comment]
I dont get the reason though. It prevents using symbolize_keys on an inherited hash class. Any specific purpose to revert that change and adding that test?

**Comment by rafaelfranca** [comment]
See https://github.com/rails/rails/pull/24517#issuecomment-208994355
