### ISSUE TITLE
Broken association preloading with SqlLiteral as a foreign_key

### ISSUE THREAD

**Issue by triplepointfive** [rails/rails#29607]
### Steps to reproduce

Use a `Arel::Nodes::SqlLiteral` as a foreign_key in association.

```ruby
begin
  require "bundler/inline"
rescue LoadError => e
  $stderr.puts "Bundler version 1.10 or later is required. Please update your Bundler"
  raise e
end

gemfile(true) do
  source "https://rubygems.org"
  gem "rails", github: "rails/rails"
  gem "arel", github: "rails/arel"
  gem "pg"
end

require "active_record"
require "minitest/autorun"
require "logger"

# Ensure backward compatibility with Minitest 4
Minitest::Test = MiniTest::Unit::TestCase unless defined?(Minitest::Test)

# This connection will do for database-independent bug reports.
ActiveRecord::Base.establish_connection(adapter: "postgresql", database: "test")
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :posts, force: true do |t|
  end

  create_table :comments, force: true do |t|
    t.jsonb :properties
  end
end

class Post < ActiveRecord::Base
  has_many :comments,
    class_name: "Comment",
    primary_key: "id",
    foreign_key: Arel::Nodes::SqlLiteral.new("properties->>'post_id'")
end

class Comment < ActiveRecord::Base
  belongs_to :post,
    class_name: "Post",
    primary_key: "id",
    foreign_key: Arel::Nodes::SqlLiteral.new("properties->>'post_id'")
end

class BugTest < Minitest::Test
  def test_association_stuff
    post = Post.create!
    Comment.create!(properties: { post_id: post.id })

    assert_equal 1, Post.last.comments.length
    assert_equal 1, Post.includes(:comments)[0].comments.length
  end
end
```

### Expected behavior

Should use the given foreign key as is and build a query like

`SELECT "comments".* FROM "comments" WHERE "comments".properties->>'post_id' = 1`

### Actual behavior

Activerecord quotes the given key. 

`SELECT "comments".* FROM "comments" WHERE "comments"."properties->>'post_id'" = 1`

Postgresql treats double quotes as a column name and therefore fails.

> ActiveRecord::StatementInvalid: PG::UndefinedColumn: ERROR:  column comments.properties->>'post_id' does not exist

Note: it's been working on rails 4.2.6. Seems like it's broken [here](https://github.com/rails/rails/blob/master/activerecord/lib/active_record/relation/where_clause_factory.rb#L16). Arel doesn't quote a column name if it's a SqlLiteral, but `stringify_keys` transforms a SqlLiteral into a string.

### System configuration
**Rails version**:
master
**Ruby version**:
2.3.1

**Comment by rafaelfranca** [comment]
Thank you for the issue. Arel is private API and we don't support `SqlLiteral` as foreign keys
