### ISSUE TITLE
Since 5.1: Broken times modulo with other units than second

### ISSUE THREAD

**Issue by doits** [rails/rails#29603]
### Steps to reproduce

Works fine in 5.0.3, but with 5.1.2: You cannot use `%` with something other than seconds, or it gets really weird.

```ruby
# works
5.seconds % 2.seconds
#  => 1.seconds

# does not work
5.minutes % 2.minutes
# => -18000 minutes und 300 seconds

5.hours % 2.hours
# => -64800000 hours und 18000 seconds
```

### Expected behavior

```ruby
5.seconds % 2.seconds
#  => 1.seconds

# does not work
5.minutes % 2.minutes
# => 1.minutes (or 60.seconds)

5.hours % 2.hours
# => 1.hours (or 3600.seconds)
```

### System configuration
**Rails version**: 5.1.2

**Ruby version**: 2.4.1

**Comment by redtachyons** [comment]
Relevent commit https://github.com/rails/rails/commit/9ae511f55047b2380224ad993a7d0ed97dbcf944#diff-eb2080ef257a835f0739f57d136efbc9

**Comment by doits** [comment]
Corrected Rails version: It actually broke in 5.1 (at least 5.1.1) and works fine in 5.0.3. <small>(Another change in 5.1.2 broke my app but I though it was this)</small>

Rails 5.0.3 does:

```ruby
5.seconds % 2.seconds
#  => 1

# does not work
5.minutes % 2.minutes
# => 60

5.hours % 2.hours
# => 3600
```

Which is consistent in the way it always outputs the correct amount of seconds at least.

**Comment by geriyoga** [comment]
I have done the test, the result is the same as @doits 's result.
# works
5.seconds % 2.seconds
#  => 1.seconds

# does not work
5.minutes % 2.minutes
# => -18000 minutes und 300 seconds

5.hours % 2.hours
# => -64800000 hours und 18000 seconds

when i tracking in resource code 
..activesupport-5.1.2/lib/active_support/duration.rb
...
```
class << self
...
  
  def /(other)
      if Scalar === other || Duration === other
        Duration.new(value / other.value, parts.map { |type, number| [type, number / other.value] })
...
the code _parts.map { |type, number| [type, number / other.value] }_
when i test
parts = 5.minutes.parts
parts.map { |type, number| [type, number / 2] }
the result is right, '[[:minutes, 2]] '

but when i test 

parts = 5.minutes.parts
other = 2.minutes
parts.map { |type, number| [type, number / other.value] }
the result is right, '[[:minutes, 0]] '

```

**Comment by doits** [comment]
Still broken on `5.1.3.rc1`
