### ISSUE TITLE
FormTagHelper uses ActionController::Parameters#to_s for hashes

### ISSUE THREAD

**Issue by JasonBarnabe** [rails/rails#29617]
Rails 5.1.1, Ruby 2.3.3

When using the methods of `ActionView::Helpers::FormTagHelper` like `text_field_tag :test, params[:test]`, if the value of `test` parameter is a `Hash` (e.g. `?test[foo]=bar`) whether through a coding error or a malicious user, the text field will display a value like `#<ActionController::Parameters:0x007f802f38ae80>`, which isn't very nice.

In Rails 4.2, the field would display a value of `{"foo"=>"bar"}`, which is nicer, but still not great.

This can be compared to when the `test` parameter is an `Array` (`?test[]=foo&test[]=bar`), which reasonably results in a display of `foo bar`.

```ruby
[1] pry(main)> include ActionView::Helpers::FormTagHelper
=> Object
[2] pry(main)> text_field_tag(:test, 'foo')
=> "<input type=\"text\" name=\"test\" id=\"test\" value=\"foo\" />"
[3] pry(main)> text_field_tag(:test, ['foo', 'bar'])
=> "<input type=\"text\" name=\"test\" id=\"test\" value=\"foo bar\" />"
[4] pry(main)> text_field_tag(:test, ActionController::Parameters.new(foo: 'bar'))
=> "<input type=\"text\" name=\"test\" id=\"test\" value=\"#&lt;ActionController::Parameters:0x007fe2bbee53e0&gt;\" />"
```

**Comment by rafaelfranca** [comment]
This is expected `Parameters` is not a Hash anymore so if you want to show the value as a hash you need to convert it. Rails is not going to do the conversion automatically to you anymore

**Comment by JasonBarnabe** [comment]
@rafaelfranca The issue is not that I want to show the value as a `Hash`. I am expecting a `String`, but due to an incorrect link or URL crafting, it can actually be any of the other types. I want reasonable behaviour in that case. Displaying `#<ActionController::Parameters:0x007f802f38ae80>` in a text field is not reasonable.

For `ActionController::Parameters` I think doing [something similar to what is done with `Array`s](https://github.com/rails/rails/blob/3f2046f00ab0046f9252a5a7b52f617028bc4e0c/actionview/lib/action_view/helpers/tag_helper.rb#L88-L89) would be reasonable - `flatten` and `join` so that the text field gets `foo bar` in my example.

**Comment by rafaelfranca** [comment]
What happens if you create an class called `Foo` and pass a object of `Foo` there? I guess it will be the same as `ActionController::Parameters`. `ActionController::Parameters` is not a primitive like array and we are not going to make it a primitive neither add special logic in the forms to do it.

**Comment by JasonBarnabe** [comment]
@rafaelfranca  If I passed a `Foo` in there then that would be my error that I could fix.

In this case I am passing `params[:test]` which I am expecting to be a `String` but depending on the request could also be an `Array` or a `ActionController::Parameters`. The type is not within my control.

I would imagine code like `text_field_tag :test, params[:test]` is very common. Any app using code like that would have this behaviour. [Like any Shopify site](https://ca.soyoung.ca/search?type=product&q[foo]=test). If it's too much of an edge case to handle, then fine. Any app that cares can change all callers from `text_field_tag(:test, params[:test])` to `text_field_tag(:test, params[:test].is_a?(String) ? params[:test] : '')`.

**Comment by rafaelfranca** [comment]
True. We could implement `to_s` to be the same as `Hash#to_s` like it was before, although it would show parameters that are not permitted yet.
