### ISSUE TITLE
Forever running ActiveJob halts the application

### ISSUE THREAD

**Issue by soapsign** [rails/rails#29620]
### Steps to reproduce

add `init_demo.rb` into `config/initializers`
```
if defined?(Rails::Server)
  Rails.application.config.after_initialize do
    DemoJob.perform_later 'A'
  end
end
```

add `demo_job.rb` into `jobs/`
```
class DemoJob < ApplicationJob
  queue_as :default

  def perform(tag)
    loop do
      puts tag
      sleep 1
    end
  end
end
```
Use default `Async` as `ActiveJob` backend.
Start Rails with puma.
[Demo Repo](https://github.com/soapsign/RailsBugReportDemo/tree/active_job)

### Expected behavior
Rails should able to serve request normally.

### Actual behavior
Rails can't serve request. Browser visiting `localhost:3000` result in forever loading.

If moving `DemoJob.perform_later 'A'` outside of `Rails.application.config.after_initialize`, the problem resolves.

If adding another `DemoJob.perform_later 'Tag'` outside of `Rails.application.config.after_initialize`, the problem resolves.

If switching to `sidekiq`  as `ActiveJob` backend, the problem resolves.
### System configuration
**Rails version**:
Rails 5.1.2
**Ruby version**:
ruby 2.2.2p95 (2015-04-13 revision 50295) [x86_64-darwin16]

**Comment by gen1321** [comment]
I was able to reproduce this, will try to fix that

**Comment by uaihebert** [comment]
@gen1321 what did you do? I was not able to reproduce it. Even the demo repo worked as expected.

**Comment by gen1321** [comment]
@soapsign After some debugging i found line where it stops is https://github.com/rails/rails/blob/master/actionpack/lib/action_dispatch/routing/route_set.rb#L29. it doing some processing and then it try to constantize a string in `ActiveSupport::Inflector.constantize.
do anyone have any idea how  its related to `ActiveJob` async adapter?  i wasn't able to debug `Inflector.constantize` yet because if i put `puts` nothing happens or 500 error, if i put a breakpoint i get `stack level too deep`. if we will figure that out it would be a pleasure for me to make pr for fixing this

**Comment by gen1321** [comment]
@uaihebert  nothing special. just `rails s` and visiting any route

**Comment by gen1321** [comment]
So i ended up with very strange behavior. no idea wtf is happening. 
as i said before  failure happens in `ActiveSupport::Inflector.constantize` https://github.com/rails/rails/blob/master/activesupport/lib/active_support/inflector/methods.rb#L281. Here is fun part. when i try to debug it as soon as any class from test app like `ApplicationController` is  loaded via `Object.const_get` or when i just type type something  like `ApplicationRecord` it interrupt my debug session with output of a job. here is logs. 

```
   268: 
   269:       names.inject(Object) do |constant, name|
   270:         if camel_cased_word == 'TestController'
   271:           byebug
   272:         end
=> 273:         if constant == Object
   274:           constant.const_get(name)
   275:         else
   276:           candidate = constant.const_get(name)
   277:           next candidate if constant.const_defined?(name, false)
(byebug) Rails
Rails
(byebug) ApplicationRecord
A
A
A
A
A
```

**Comment by soapsign** [comment]
@uaihebert the demo repo should be tested in `active_job` branch.

**Comment by matthewd** [comment]
This is expected behaviour.

> Forever running ActiveJob

Don't do that.
