### ISSUE TITLE
Params wrapper is trying to safe_constantize wrong class based on url instead of what is present 

### ISSUE THREAD

**Issue by anildigital** [rails/rails#29625]
### Steps to reproduce
1. Clone and run this app https://github.com/anildigital/wrap_parameters_bug_app
2. Run below curl command
```curl -H "Content-Type: application/json" http://localhost:3000/api/v1/me/stars/hello```
3. See exception thrown which should be something like

```
Started GET "/api/v1/me/stars/hello" for 127.0.0.1 at 2017-06-29 17:47:18 +0530
Klass name
Api::V1::Me::StarsController
Model name
Api::V1::Me::Star

LoadError (Unable to autoload constant Star, expected /Users/anil/Code/ruby/rails/bugs/wrap_parameters_bug_app/app/models/galaxy/star.rb to define it):
```

In above logs, I have also printed `klass.name` and `model_name` from `_default_wrap_model` method of actionpack's params_wrapper.rb
i.e.
```
def _default_wrap_model
  return nil if klass.anonymous?
  model_name = klass.name.sub(/Controller$/, "").classify
  puts "Klass name "
  puts klass.name
  puts "Model name"
  puts model_name
```

### Expected behavior
Looks like params wrapper is assuming there must be a class named `Star` in star.rb based on passed URL, but that's wrong, the related model class doesn't exist, but a name scoped class `class Galaxy::Star` actually exist there.

### Actual behavior
Should not throw the error. 

### System configuration
**Rails version**:
I have used Rails 5.1.2, but error exists for 5.0.1 app too.

**Ruby version**:
ruby 2.3.3p222

**Comment by rafaelfranca** [comment]
That is the expected behavior for `_default_wrap_model`. It tries to find the model with the same name as the controller. It can't know for sure that it the correct model, so it tries to infer from the controller.

What you are seeing is a classing autoload problem. Rails is trying to find `Start` at the top level but you don't have this class defined. It looked in all possible candidates and he found a file that it was expecting it to be defined but it was not. Given that it raised an exception.

I think the problem here is that `safe_constantize` should rescue `LoadError` too. @fxn WDYT?

**Comment by anildigital** [comment]
@rafaelfranca if it's a simple fix like rescue `LoadError`, I can try to send PR for this 😃 Let me know.

**Comment by rafaelfranca** [comment]
I'm not sure if it is a good idea rescue `LoadError`, maybe change that exception to be a subclass of `LoadError` and rescue it. Let see what @fxn has to say

**Comment by matthewd** [comment]
The application is misconfigured: https://github.com/anildigital/wrap_parameters_bug_app/blob/master/config/application.rb#L23

`safe_constantize` will "safely" return nil for an unknown constant name, but a file on the autoload path which doesn't define the constant it's supposed to is a capital-E Error.

**Comment by anildigital** [comment]
@matthewd There is no such constant `Star` in the code base. The application uses subfolder `galaxy` under models and that's why there is `star.rb` contains `Galaxy::Star` class.

So as you are saying, an error is raised correctly as the file doesn't have related constant. This is fine.

The actual issue is the part where it tries to find the model with the same name as the controller. Isn't it plainly wrong to couple the REST URL to ultimately derive the name of the constant?

**Comment by januszm** [comment]
This is still a problem and it seems to me that it is mainly related to controllers such as API whose names are nested, please look at the following example:

```ruby
# model app/models/foo/bar.rb
module Foo
  class Bar
    # ...
  end
end

# controller
class API::V1::Foo::BarsController
  # ...
end

# console, just replaying commands from actionpack, params_wrapper.rb
> klass = ::API::V1::Foo::BarsController
> model_name = klass.name.sub(/Controller$/, "").classify
=> "API::V1::Foo::Bar"
> model_name.safe_constantize
Traceback (most recent call last):
LoadError (Unable to autoload constant Bar, expected app/models/foo/bar.rb to define it)
```

It freaks out when the model is defined in the namespace.

I guess that adding  `wrap_parameters Foo::Bar` or  `def model; Foo::Bar; end` to the problematic controller would help, right?


Also, this fragment of the comments section seems correct, this mechanism works for the cases like `Admin::UsersController`  even if the top-level `User` model is not defined:

```
  #     class Admin::UsersController < ApplicationController
  #     end
  #
  # will try to check if <tt>Admin::User</tt> or +User+ model exists, and use it to
  # determine the wrapper key respectively. If both models don't exist,
  # it will then fallback to use +user+ as the key.
```
But , it will fail if we add just one more layer of nesting, like `Api::Admin::UsersController` (and `Admin::User` model.

cc: @rafaelfranca
