### ISSUE TITLE
When LoadError#path is nil LoadError#is_missing? throws NoMethodError

### ISSUE THREAD

**Issue by nrser** [rails/rails#29632]
It's possible for `LoadError#path` to be `nil` when a mixin included in `ApplicationHelper` is misnamed, resulting in a crash on boot with a none-too-useful error:

```
web_1  | ./dev/.bundle/ruby/2.3.0/gems/activesupport-5.1.1/lib/active_support/core_ext/load_error.rb:12:in `is_missing?': undefined method `sub' for nil:NilClass (NoMethodError)
web_1  | 	from ./dev/.bundle/ruby/2.3.0/gems/actionpack-5.1.1/lib/abstract_controller/helpers.rb:189:in `rescue in default_helper_module!'
web_1  | 	from ./dev/.bundle/ruby/2.3.0/gems/actionpack-5.1.1/lib/abstract_controller/helpers.rb:185:in `default_helper_module!'
web_1  | 	from ./dev/.bundle/ruby/2.3.0/gems/actionpack-5.1.1/lib/abstract_controller/helpers.rb:36:in `block in inherited'
web_1  | 	from ./dev/.bundle/ruby/2.3.0/gems/actionpack-5.1.1/lib/abstract_controller/helpers.rb:36:in `class_eval'
...
```

Full stack trace here:

https://gist.github.com/nrser/f59050d699dbdcb8772a4afcee07be5d

### Steps to reproduce

I have several chunks of application-wide helper functionality split out into mixins like:

```ruby
# app/helpers/helper_mixins/css_helper.rb
module HelperMixins
  module CSSHelper
    # ...
  end
end
```

They are included in `ApplicationHelper`:

```ruby
module ApplicationHelper  
  include HelperMixins::CSSHelper
  # ...
end
```

Everything works fine when the names are correct, but when they aren't - say `ApplicationHelper` includes `HelperMixins::CssHelper` by accident - I get a crash on boot with the above stack trace.

It's worth noting that i'm using inflections to define a `CSS` acronym, though when messing around it doesn't seem to make a difference.

There are actually two `sub` calls on the line in question:

https://github.com/rails/rails/blob/master/activesupport/lib/active_support/core_ext/load_error.rb#L12

But I hacked a `puts` in there and confirmed that it's `LoadError#path` that is `nil`.

### Expected behavior

The error message should reflect the problem - missing module, bad file name, etc.

### Actual behavior

The `LoadError#is_missing?` method itself errors, raising a `NoMethodError` that does little to indicate the underlying problem.

### System configuration
**Rails version**: 5.1.1

**Ruby version**: 2.3.4

**Comment by uaihebert** [comment]
I tried to look at this bug, but I was not able to reproduce. 

Could you post a code that would reproduce the bug?

**Comment by domangi** [comment]
@nrser, I also tried to reproduce but I was not able like @uaihebert , meaning that I see a different error output.

I created a new app adding just the css_helper.rb file and including it in application_helper.rb and when i boot in production env i get the following error message that seems quite useful:

> /Apps/issue-29632/app/helpers/application_helper.rb:2:in <module:ApplicationHelper>': uninitialized constant HelperMixins::ScssHelper (NameError)
    from /Apps/issue-29632/app/helpers/application_helper.rb:1:in <top (required)>'
    from /Users/domangi/.rvm/gems/ruby-2.3.3/gems/activesupport-5.1.1/lib/active_support/dependencies/interlock.rb:12:in block in loading'
    from /Users/domangi/.rvm/gems/ruby-2.3.3/gems/activesupport-5.1.1/lib/active_support/concurrency/share_lock.rb:149:in exclusive'
    from /Users/domangi/.rvm/gems/ruby-2.3.3/gems/activesupport-5.1.1/lib/active_support/dependencies/interlock.rb:11:in loading'
    from /Users/domangi/.rvm/gems/ruby-2.3.3/gems/actionpack-5.1.1/lib/abstract_controller/helpers.rb:150:in block in modules_for_helpers'
    from /Users/domangi/.rvm/gems/ruby-2.3.3/gems/actionpack-5.1.1/lib/abstract_controller/helpers.rb:145:in map!'
    from /Users/domangi/.rvm/gems/ruby-2.3.3/gems/actionpack-5.1.1/lib/abstract_controller/helpers.rb:145:in modules_for_helpers'
    from /Users/domangi/.rvm/gems/ruby-2.3.3/gems/actionpack-5.1.1/lib/action_controller/metal/helpers.rb:93:in modules_for_helpers'
    from /Users/domangi/.rvm/gems/ruby-2.3.3/gems/actionpack-5.1.1/lib/abstract_controller/helpers.rb:109:in helper'
    from /Users/domangi/.rvm/gems/ruby-2.3.3/gems/actionpack-5.1.1/lib/abstract_controller/helpers.rb:187:in default_helper_module!'
    from /Users/domangi/.rvm/gems/ruby-2.3.3/gems/actionpack-5.1.1/lib/abstract_controller/helpers.rb:36:in block in inherited'
    from /Users/domangi/.rvm/gems/ruby-2.3.3/gems/actionpack-5.1.1/lib/abstract_controller/helpers.rb:36:in class_eval'
    from /Users/domangi/.rvm/gems/ruby-2.3.3/gems/actionpack-5.1.1/lib/abstract_controller/helpers.rb:36:in inherited'
    from /Users/domangi/.rvm/gems/ruby-2.3.3/gems/actionview-5.1.1/lib/action_view/layouts.rb:217:in inherited'

Btw, if I include HelperMixins::CSSHelper in application_helper.rb i get another error because it is searching for CssHelper instead:

> /Users/domangi/.rvm/gems/ruby-2.3.3/gems/actionpack-5.1.1/lib/abstract_controller/helpers.rb:163:in
`rescue in block in modules_for_helpers': Couldn't find HelperMixins::CssHelper, expected it to be defined in helpers/helper_mixins/css_helper.rb (NameError)

I will investigate more on this to understand if it is actually a bug or not.

**Comment by nrser** [comment]
Yes, the *underlying* issue is that the helper is misnamed. Easy to fix.

The problem this issue is addressing is that - one way or another - it is possible for to enter the `LoadError#is_missing?` function for a `LoadBlock` that has `#path` of `nil`, causing the `undefined method `sub' for nil:NilClass (NoMethodError)` error, which - since `LoadError#is_missing?` is attempting to provide a useful error message - seems to defeat it's purpose.

Because this is Ruby-land, pretty much any gem anywhere could be doing something to `LoadError` that causes `#path` to be `nil`. What gem and where? Who knows... we could spend a bunch of time tracking down exactly what did it and how, but that wouldn't change anything... a new gem someone wrote tomorrow could pop up and do the same thing.

My suggestion is that it might be worth the few characters or lines to make sure `LoadError#path` "quacks" (responds to `#sub` or is a `String` or whatever) before telling it to.

**Comment by matthewd** [comment]
Yes, please do PR. While modern rubies won't internally raise a LoadError without a `path`, it wasn't *that* long ago that it was normal, so it seems reasonable for us to accomodate 3rd party libraries that haven't caught up with the times. (Though correspondingly, *we* shouldn't be generating such half-formed exceptions.)

I don't think it should raise, though: just return false. This method is already here for us to attempt to friendlify an error message; if the `path` is missing, the safest choice would seem to be to assume it's not the error we're looking for, and let it proceed as is.

It'd also probably be worthwhile identifying which library is seemingly interfering, to help them modernize.. but as you say, handling it on our side is independent of that.

**Comment by sgrif** [comment]
Even just sticking a `.to_s` in there seems fine. Either way this should be a very small change, just needs a test. @nrser Were you interested in opening a PR for this?

**Comment by nrser** [comment]
Sorry, hadn't had the time because i was thinking I'd have to set up a whole local dev env to do the change and test it, but it's so small and I figured you guys probably have some sort of CI anyways so I just did it in the web UI.

**Comment by eileencodes** [comment]
@nrser we do have a CI but there isn't a test testing the case you changed, i.e. the case where a load path is nil.

We can't accept a change without a test because then someone can come along and say the same thing "just a small change, the suite passes, remove the `to_s`" and then your case will be broken again. The test is prevent regressions, not because we think this change is too dangerous.

**Comment by nrser** [comment]
@eileencodes nah I totally get it, I just don't have a dev env set up for Rails and I figured that was gonna take a decent amount of time... I've been in serious crunch mode trying to ship something. But I just looked at the dev setup instructions and it looks really simple so I'll give it an hour right now and see where get.

**Comment by nrser** [comment]
@eileencodes is there a Docker image for the dev env? I'm wary to install Virtual Box because I know it's had conflicts with Docker in the past and I really can't break my work env right now.

**Comment by eileencodes** [comment]
If you're on a mac I recommend doing it "the hard way" which really isn't that time consuming. You can probably skip setting up active record so as long as you have a supported Ruby installation shouldn't be much more involved than starting a rails app.

We don't have a docker image that I'm aware of.

I totally understand if you don't have time to work on the issue. Open source is time consuming! I wanted to explain why we can't merge the PR as is 😀

If you run into an issue setting up locally let me know
