### ISSUE TITLE
Question: Does rails support to add one column and set default value the same time with db migration?

### ISSUE THREAD

**Issue by bibobibo** [rails/rails#29637]
### Steps to reproduce
I have one table `agencies` and it has some data already.
Action:
I'd like to add a new column `test_default` with default value 0 for it, so I add under migration code:
```
class AddTestDefaultToAgencies < ActiveRecord::Migration[5.1]
  def change
    add_column :agencies, :test_default, :integer, default: 0
  end
end
```

(Guidelines for creating a bug report are [available
here](http://guides.rubyonrails.org/contributing_to_ruby_on_rails.html#creating-a-bug-report))

### Expected behavior
Run migration successfully.

### Actual behavior
It runs failed and show me some error
```
WARNING: Skipping key "AWS_REGION". Already set in ENV.
== 20170630023420 AddTestDefaultToAgencies: migrating =========================
rake aborted!
StandardError: An error has occurred, this and all later migrations canceled:


 __          __     _____ _______ _
 \ \        / /\   |_   _|__   __| |
  \ \  /\  / /  \    | |    | |  | |
   \ \/  \/ / /\ \   | |    | |  | |
    \  /\  / ____ \ _| |_   | |  |_|
     \/  \/_/    \_\_____|  |_|  (_)

Adding a column with a non-null default requires
the entire table and indexes to be rewritten. Instead:

1. Add the column without a default value
2. Commit the transaction
3. Backfill the column
4. Add the default value
/Users/xwfeng/.rvm/gems/ruby-2.3.0/gems/strong_migrations-0.1.5/lib/strong_migrations/migration.rb:139:in `raise_error'
/Users/xwfeng/.rvm/gems/ruby-2.3.0/gems/strong_migrations-0.1.5/lib/strong_migrations/migration.rb:41:in `method_missing'
```
### System configuration
**Rails version**:
Rails 5.1.0.rc1
**Ruby version**:
ruby 2.3.0p0 (2015-12-25 revision 53290) [x86_64-darwin14]

**Comment by matthewd** [comment]
Please use the mailing list or StackOverflow for questions/help, where a wider community will be able to help you. We reserve the issues tracker for issues only.

But that error is clearly coming from a 3rd party gem whose whole purpose is to disallow this, so...
