### ISSUE TITLE
Mixed messages regarding quoted_id in custom attribute type classes

### ISSUE THREAD

**Issue by hult** [rails/rails#29639]
### Steps to reproduce

Have a custom attribute class

```ruby
class MyType
  def initialize(value); @value = value; end
  def id; ...; end
  def quoted_id; ...; end
end

class MyValue < ActiveRecord::Type::Value
  def deserialize(value); MyType.new(value); end
  ...
end

class MyModel < ApplicationRecord
  attribute :some_column, MyValue.new
end
```

### Actual behavior

If a `MyType` instance is sent to `ActiveRecord::ConnectionAdapters::Quoting::quote` (not sure about the exact circumstances under which this happens), I get the deprecation warning that "Defining #quoted_id is deprecated and will be ignored in Rails 5.2".

However, if I remove the `quoted_id` method from `MyType`, `ActiveRecord::ConnectionAdapters::Quoting::type_cast` always fails (and that method is called all the time), since it returns `value.id` only if `value.respond_to?(:quoted_id) && value.respond_to?(:id)`.

What am I supposed to do? It seems `type_cast` should not check whether `quoted_id` is implemented?

### System configuration
**Rails version**: 5.1.2

**Ruby version**: 2.4.1

**Comment by rafaelfranca** [comment]
In 5.2 it will not call `value.id` anymore and this is why you should not implement `quoted_id` anymore.

You need to use the proper API for your type now (implement `serialize` and `deserialize` and don't rely on `id` being called.

**Comment by hult** [comment]
Ok, I realize you have a strategy going forward, but right now, do I
implement quoted_id or not? Either way, I get errors and/or deprecations.
Le ven. 30 juin 2017 à 19:04, Rafael França <notifications@github.com> a
écrit :

**Comment by rafaelfranca** [comment]
You should not implement `quoted_id`. You need to change your type to not rely on calling `id` anymore.

**Comment by hult** [comment]
I’m not calling id, ActiveRecord::ConnectionAdapters::Quoting::type_cast
does that for me
Le ven. 30 juin 2017 à 21:44, Rafael França <notifications@github.com> a
écrit :

**Comment by rafaelfranca** [comment]
I got it. What I mean is that you should not expect `id` to be called. Like you said you in the description you are expecting, given you said that "ActiveRecord::ConnectionAdapters::Quoting::type_cast always fails".

> However, if I remove the quoted_id method from MyType, ActiveRecord::ConnectionAdapters::Quoting::type_cast always fails (and that method is called all the time), since it returns value.id only if value.respond_to?(:quoted_id) && value.respond_to?(:id).

**Comment by sgrif** [comment]
You are missing an implementation of `serialize` in your type. You need to convert from `MyType` to something that the database knows how to deal with (likely you just need to call `.id`). The deprecation warning is correctly telling you that you cannot rely on this happening automatically anymore.
