### ISSUE TITLE
destroyed_by_association for has_one?

### ISSUE THREAD

**Issue by kshnurov** [rails/rails#29635]
`destroyed_by_association` is not set when using `has_one` with `dependent: :destroy`, works only for `has_many`.
It this a bug/missing code or made by intention?

Probably `target.destroyed_by_association = reflection` should be added [here](https://github.com/rails/rails/blob/7fcd25f44ce059bf9d68b9fd125c44c46b08c074/activerecord/lib/active_record/associations/has_one_association.rb#L59) and [here](https://github.com/rails/rails/blob/7fcd25f44ce059bf9d68b9fd125c44c46b08c074/activerecord/lib/active_record/associations/has_one_association.rb#L81), like it's done [in has_many](https://github.com/rails/rails/blob/7fcd25f44ce059bf9d68b9fd125c44c46b08c074/activerecord/lib/active_record/associations/has_many_association.rb#L25
)

**Comment by lugray** [comment]
If you look at https://github.com/rails/rails/blob/310918f6a194bf5752fe1025930881756f5d8a8e/activerecord/lib/active_record/autosave_association.rb#L254-L259, `destroyed_by_association` is used to avoid updating the counter cache unnecessarily.  A counter doesn't make sense for a `has_one` relation.

I wonder if this method should become `:nodoc:` if it's really for internal use?

**Comment by kshnurov** [comment]
It also can be used to check if a parent is being destroyed.
It's useful if you have some validations in `before_destroy` and you want to skip them when this object is destroyed by it's parent's `dependent: destroy` (which is done before parent gets any signs of being destroyed, ).

**Comment by lugray** [comment]
I'm still not convinced this is meant to be public api, but here's a demonstration of the difference between them.

```ruby
begin
  require "bundler/inline"
rescue LoadError => e
  $stderr.puts "Bundler version 1.10 or later is required. Please update your Bundler"
  raise e
end

gemfile(true) do
  source "https://rubygems.org"
  # Activate the gem you are reporting the issue against.
  gem "activerecord", "5.1.0"
  gem "sqlite3"
end

require "active_record"
require "minitest/autorun"
require "logger"

# Ensure backward compatibility with Minitest 4
Minitest::Test = MiniTest::Unit::TestCase unless defined?(Minitest::Test)

# This connection will do for database-independent bug reports.
ActiveRecord::Base.establish_connection(adapter: "sqlite3", database: ":memory:")
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :posts do |t|
    t.integer :user_id
  end

  create_table :profiles do |t|
    t.integer :user_id
  end

  create_table :users do |t|
  end
end

class Post < ActiveRecord::Base
  belongs_to :user
  before_destroy :dont, unless: :destroyed_by_association

  def dont
    throw(:abort)
  end
end

class Profile  < ActiveRecord::Base
  belongs_to :user
  before_destroy :dont, unless: :destroyed_by_association

  def dont
    throw(:abort)
  end
end

class User < ActiveRecord::Base
  has_many :posts, dependent: :destroy
  has_one :profile, dependent: :destroy
end

class BugTest < Minitest::Test
  def test_has_many_dependent_destroy
    user = User.create!
    post = Post.create!(user: user)

    user.destroy

    assert_equal 0, Post.count #passes
  end

  def test_has_one_dependent_destroy
    user = User.create!
    post = Profile.create!(user: user)

    user.destroy

    assert_equal 0, Profile.count # fails
  end
end
```

**Comment by kshnurov** [comment]
Actually, `user.destroy` will fail in `test_has_one_dependent_destroy` because Profile won't allow to delete itself and the User. Add `assert_not_equal false, user.destroy`.

**Comment by benphelps** [comment]
This is useful when working with the callbacks or gems that depends on callbacks like paranoia, where :delete_all is not an option.

I want to skip only one of my before_destroy callbacks when the has_one association is being destroyed by it's parent and currently there is no way to know this form what I can tell.  I would like to see this or something similar for has_one as well.

**Comment by sgrif** [comment]
I agree that it was probably not intended to be public API, but it's been part of our documented public API since 4.0. If we were to make it private, we'd need to at least have a deprecation cycle. I'd rather just fix this issue.
