### ISSUE TITLE
A question about cursors support

### ISSUE THREAD

**Issue by pyromaniac** [rails/rails#29648]
AR fakes cursors in the find_each method using id lookup. Is there any reason why doesn't AR support cursors yet? At least, for some DBMS, I believe, it is possible to implement it on the driver level using the current approach as a fallback maybe.

**Comment by eugeneius** [comment]
Can you give an example of a database that can be used with Active Record and supports cursors?

**Comment by zernie** [comment]
PostgreSQL support cursors. There's even a gem for this - https://github.com/afair/postgresql_cursor

**Comment by pyromaniac** [comment]
https://dev.mysql.com/doc/refman/5.7/en/cursors.html
https://www.mssqltips.com/sqlservertip/1599/sql-server-cursor-example/
https://www.ibm.com/support/knowledgecenter/en/SSEPEK_11.0.0/sqlref/src/tpc/db2z_sql_declarecursor.html
https://www.techonthenet.com/oracle/cursors/declare.php

A lot of RDBMS implemented cursors. Unfortunately, I didn't find any support table or so.

Yeah, I've seen the the PG cursors gem, even two. The idea is that I've got my own gems where I'm using find_in_batches or even self-implemented pluck_in_batches, but I would like to have a universal API exist in AR and I would like it to be implemented in the most efficient way. Unfortunately sorting, even by id, is not the best idea for performance. Especially if records natural order is changed on update as some databases do.

**Comment by duffyjp** [comment]
@pyromaniac Would this allow `find_in_batches` for oracle views that don't have a primary key?  That would be so great.

**Comment by pyromaniac** [comment]
I think so

**Comment by matthewd** [comment]
> A lot of RDBMS implemented cursors

... *inside stored procedures*.

Where they are available, cursors apply constraints on what you can do with the connection while they're open, and/or you need to consciously choose the right cursor mode for your use case. So I don't see them being the default implementation for batching.

Given that, I don't think there's much for us to do here.

**Comment by pyromaniac** [comment]
Ok, thanks for the clarification
