### ISSUE TITLE
Bug: Custom generator inheriting from Rails::Generators::NamedBase does not have `file_name` method

### ISSUE THREAD

**Issue by thefliik** [rails/rails#29657]
### Steps to reproduce

1. Generate a new rails 5.1.2 project with `rails new test-app` (& bundle install...)
2. Generate a new generator with `rails g generator test`
3. Edit your `TestGenerator` in `lib/generators/test/test_generator.rb` to add `puts file_name` on the last line, like so
```
class TestGenerator < Rails::Generators::NamedBase
  source_root File.expand_path('../templates', __FILE__)
  
  puts file_name
end

```
4. run the test generator with `rails g test MyCustomFileName`

### Expected behavior
As [described in the docs](http://edgeguides.rubyonrails.org/generators.html#creating-generators-with-generators), running this generator should print "MyCustomFileName" to the terminal because the `file_name` method is inherited from `Rails::Generators::NamedBase` and returns the first argument passed to the TestGenerator (i.e. 'MyCustomFileName' string)

> The method file_name is automatically created when we inherit from Rails::Generators::NamedBase.

### Actual behavior
Instead, a `[WARNING] Could not load generator "generators/test/test_generator". Error: undefined local variable or method 'file_name' for TestGenerator:Class.` exception is raised. Inspecting the task with `byebug`, it doesn't appear that `TestGenerator` has inherited any of the generator methods [described in the docs](http://guides.rubyonrails.org/generators.html#generator-methods).

### System configuration
**Rails version**: 5.1.2

**Ruby version**: 2.4.0

Thanks!!

**Comment by y-yagi** [comment]
This is the expected behavior. Since `file_name` is defined as an instance variable, it can only be used within an instance method.  
https://github.com/rails/rails/blob/fb9e846be9a1e1a907c84f5d0336bec56fe2a5bc/railties/lib/rails/generators/named_base.rb#L38 

Like so.

```ruby 
class TestGenerator < Rails::Generators::NamedBase
  source_root File.expand_path('templates', __dir__)

  def copy_file
    puts file_name
  end
end 
```

```console
$ bin/rails g test MyCustomFileName
my_custom_file_name 
```

**Comment by thefliik** [comment]
@y-yagi. Ok, thank you. That wasn't clear to me from the documentation.
