### ISSUE TITLE
DB configuration does not accept symbols anymore.

### ISSUE THREAD

**Issue by voxik** [rails/rails#29672]
### Steps to reproduce

Trying to execute rails-observers against RoR 5.1, I'm observing following error:

~~~
$ ruby -Ilib:test -e 'Dir.glob '\''./test/*_test.rb'\'', &method(:require)'
/usr/share/gems/gems/activerecord-5.1.2/lib/active_record/connection_adapters/connection_specification.rb:246:in `resolve_symbol_connection': 'test' database is not configured. Available: [] (ActiveRecord::AdapterNotSpecified)
	from /usr/share/gems/gems/activerecord-5.1.2/lib/active_record/connection_adapters/connection_specification.rb:227:in `resolve_connection'
	from /usr/share/gems/gems/activerecord-5.1.2/lib/active_record/connection_adapters/connection_specification.rb:141:in `resolve'
	from /usr/share/gems/gems/activerecord-5.1.2/lib/active_record/connection_handling.rb:55:in `establish_connection'
	from /builddir/build/BUILD/rails-observers-0.1.4/usr/share/gems/gems/rails-observers-0.1.4/test/helper.rb:34:in `<top (required)>'
	from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /builddir/build/BUILD/rails-observers-0.1.4/usr/share/gems/gems/rails-observers-0.1.4/test/transaction_callbacks_test.rb:1:in `<top (required)>'
	from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:55:in `require'
	from -e:1:in `glob'
	from -e:1:in `<main>'
~~~

It seems this is caused by https://github.com/rails/rails/commit/0a4f60090ba6a61a2610d8a0c163cc97e8c95833#diff-9220267c89717bc78a987fe6d4439c72R157. This line filters out the configuration if it does not contain "adapter" string as a key. But the thing is, that rails-observers are using :adapter symbol on this place [[1]].

I submitted rails/rails-observers/pull/61 PR fixing this issue on rails-observers side, but I am not entirely sure that the change on the Rails side was intentional. Could you please clarify what is the expected behavior here?

[1]: https://github.com/rails/rails-observers/blob/master/test/helper.rb#L33

**Comment by rafaelfranca** [comment]
Yes, it is the expected behavior.

**Comment by ioquatix** [comment]
This caused a issues for us too. It was an unexpected breaking change in a minor patch update.
