### ISSUE TITLE
Can't override Enumerable methods in ActiveRecord models

### ISSUE THREAD

**Issue by mikecmpbll** [rails/rails#29674]
I have a class method called `sort` in my model  which worked fine up until upgrading to Rails 5, where when I call the method now on a Relation, the method that get's called is `Enumerable#sort`. same applies for any method names in Enumerable as far as I've tested it.

### Steps to reproduce

```ruby
begin
  require "bundler/inline"
rescue LoadError => e
  $stderr.puts "Bundler version 1.10 or later is required. Please update your Bundler"
  raise e
end

gemfile(true) do
  source "https://rubygems.org"
  gem "rails", github: "rails/rails"
  gem "arel", github: "rails/arel"
  gem "sqlite3"
end

require "active_record"
require "minitest/autorun"
require "logger"

# This connection will do for database-independent bug reports.
ActiveRecord::Base.establish_connection(adapter: "sqlite3", database: ":memory:")
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :posts, force: true do |t|
    t.string :name
  end
end

class Post < ActiveRecord::Base
  def self.sort
    raise
  end

  def self.foo
    raise
  end
end

class BugTest < Minitest::Test
  def test_active_record_enumerable_proxying
    assert_raises(RuntimeError){ Post.where(name: "foo").foo }
    assert_raises(RuntimeError){ Post.where(name: "foo").sort }
  end
end
```

### Expected behavior
Should use the model's `sort` class method.

### Actual behavior
Enumerable#sort is called.

### System configuration
**Rails version**: Fails on >= 5.0, passes < 5.0

**Ruby version**: 2.3.1

**Comment by Sayanc93** [comment]
Doesn't Model.where return an Array of objects? So by that logic, class methods can't be called with respect to an Array object? Correct me if I'm wrong

**Comment by mikecmpbll** [comment]
@Sayanc93 nope, it returns a Relation.

**Comment by Sayanc93** [comment]
@mikecmpbll On further digging into this, the array sort delegation happens here
<img width="805" alt="screen shot 2017-07-04 at 9 13 21 pm" src="https://user-images.githubusercontent.com/6565629/27836617-cbec530c-60fd-11e7-84aa-4c523dee11d3.png">

Also, check this commit https://github.com/rails/rails/commit/cdd45fa09d76f7c16ccbb6682e672a44f82174a0#diff-942244607b1fb3f1b71083b87025b440R4

Removing :each from delegation breaks the delegation call of sort to Array, so I think .sort is getting delegated through :each.

@matthewd @kamipo Thoughts?

**Comment by mikecmpbll** [comment]
@Sayanc93 thanks for the digging! i had a look at that delegation file and did some debugging. because Enumerable is now included in ActiveRecord::Relation, `method_missing` is never hit when calling `sort` (or other enumerable methods). it's the first hit to `method_missing` that creates the delegate to the model class methods on relations https://github.com/rails/rails/blob/master/activerecord/lib/active_record/relation/delegation.rb#L89 .

so i think i understand what's going on, but i'm not really sure how to address it at this stage. i'll have a stab at something though.

**Comment by Sayanc93** [comment]
Yeap `method_missing` is not hit because it gets delegated to Array.sort on the line I mentioned.
I can have a patch ready but I think this was intentional. Look into this commit by @sgrif 
https://github.com/rails/rails/commit/9d79334a1dee67e31222c790e231772deafcaeb8#diff-563ce9140aa399b5ba97bb2a64b7c568

**Comment by sgrif** [comment]
This is intentional.

**Comment by matthewd** [comment]
@sgrif we intentionally made an unreported breaking change without deprecation? :confused:

I do think we should keep the new behaviour (and we're at least one release too late to usefully add in any warning), but I don't recall us specifically considering a klass having defined an Enumerable method when we weighed up b644964b2b555798fc4b94d384b98438db863b3f.

**Comment by mikecmpbll** [comment]
just had the same problem with another scope named `in_groups`. this breaking change is going to cause lots of people a bit of headache.

**Comment by moveson** [comment]
I'm having the same problem after a Rails 5 upgrade. My `User.sort` method no longer works.

**Comment by bluengreen** [comment]
@sgrif why is this intentional? Is that the rails mantra these days - as long as as it works for basecamp its all good to push breaking changes?

**Comment by flavono123** [comment]
`delegate :each, to: :records` makes a delegation that `Enumerate#sort` to `ActiveRecord::Relation#sort`? I can't understand that

**Comment by flavono123** [comment]
`Enumerable`, got it
