### ISSUE TITLE
Registered observer on one mailer gets called with every email delivering, possible bug?

### ISSUE THREAD

**Issue by pedroadame** [rails/rails#29671]
I found what could be a possible bug, as this solution is not working: 
https://stackoverflow.com/questions/15836923/is-it-possible-to-have-a-mail-observer-that-handle-only-a-specific-mailer

### Steps to reproduce

1. Create two mailers ex `OneMailer` and `AnotherMailer`
2. Create an observer class. ex:
```ruby
# app/observers/test_observer.rb
class TestObserver
  def delivered_email(mail)
    puts "Sent!"
  end
end
```
3. Call `OneMailer.register_observer(TestObserver)`
4. Call `OneMailer.some_mail.deliver_now`
5. Call `AnotherMailer.some_mail.deliver_now`
### Expected behavior
In step 4, `"Sent!"` gets printed
In step 5, nothing gets printed

If I register the observer in `ActionMailer::Base.register_observer` it should apply to all mailers
### Actual behavior
It prints `"Sent"` on steps 4 and 5

### System configuration
**Rails version**: 5.1.1

**Ruby version**: MRI 2.4.0

**OS**: Arch Linux with kernel 4.11.7-1-ARCH

**Comment by rafaelfranca** [comment]
The observers are added to the mail library so there is no way to add one observer to only one mailer.

**Comment by pedroadame** [comment]
@rafaelfranca Good to know that. I need to call a method right after a mail is sent correctly. Is there any way to do that?

**Comment by rafaelfranca** [comment]
`after_action`?

**Comment by pedroadame** [comment]
As pointed here http://guides.rubyonrails.org/action_mailer_basics.html#action-mailer-callbacks
`after_action` seems to be called right after the deliver method, but before the email is really sent.
```
You could use an after_action to do similar setup as a before_action but using instance variables set in your mailer action.
```

**Comment by rafaelfranca** [comment]
You could add an observer and check the [`delivery_handler` on it](https://github.com/mikel/mail/blob/4876ae4ff33cb3a564de0a27b819ddb7f5123bee/lib/mail/message.rb#L201), or you could subscribe to the `deliver.action_mailer` message and check the [`payload[:name]` value](https://github.com/rails/rails/blob/6f2b0eb44ab166f98f3bc4a3aa09d3b899e0fd62/actionmailer/lib/action_mailer/base.rb#L565).

**Comment by pedroadame** [comment]
This seems to work. Thanks!
```
class TestObserver
  def self.delivered_email(mail)
    # Check if sent by WelcomeMailer until another option comes up
    if mail.delivery_handler == WelcomeMailer && mail.to&.any?
      welcome_mail = Student.find_by_email(mail.to.first).welcome_email
      welcome_mail.update_attributes sent: true
    end
  end
end
```

**Comment by gaurav-patil-qp** [comment]
Hi @pedroadame 
I have implemented the observer, but I want to pass one extra parameters to that observer method for e.g. `self.delivered_email(mail, <active_record_object_id>)` 
It is possible to pass extra parameter to this method?
or there is any available solution for the same ?

Thanks
