### ISSUE TITLE
Migration with virtual column fails to populate 'AS' expression for the virtual column in the schema file

### ISSUE THREAD

**Issue by kaurinz** [rails/rails#29670]
### Steps to reproduce

Create a migration with a defined virtual column, 't.virtual' with an appropriate AS expression

### Expected behavior
During migration schema should be updated with an entry for the new virtual column, containing its 'AS' expression as previously specified in migration file

### Actual behavior
Schema contains new "t.virtual" column with an empty "AS: " expression instead of the one found in the migration 

### System configuration
Rails 5.1.2
ruby 2.4.0p0

**Comment by rafaelfranca** [comment]
Could you create a reproduction script with this template https://github.com/rails/rails/blob/master/guides/bug_report_templates/active_record_master.rb?

**Comment by kaurinz** [comment]
I'm not sure how to use that test given the issue that I've noticed. I've done some investigation and hopefully the information below can shed some light on where the issue is arising.

For my given environment a call to `extract_expression_for_virtual_column` made to mariadb using the mysql2 adapter, results in the following being generated by `create_table_info(column.table_name)`:

```
CREATE TABLE `messageaddresses` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `address` varchar(255) DEFAULT NULL,
  `forward_address` varchar(255) DEFAULT NULL,
  `temporary` tinyint(1) DEFAULT 0,
  `system` tinyint(1) DEFAULT 0,
  `internal` tinyint(1) GENERATED ALWAYS AS (left(`address`,1) = '#') STORED,
  `created_at` datetime NOT NULL,
  `updated_at` datetime NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `index_messageaddresses_on_address` (`address`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8
```

However the regular expression that is used to extract the AS expression of the `internal` column, ends with **STORED GENERATED**, instead of **STORED**, hence it is not found and the expression is not captured (and not output to the generated schema file)

This relates to **column.extra** , although why it is capturing STORED GENERATED and not just STORED, and whether it was indeed functioning as intended, was something I couldn't discern.

**Comment by rafaelfranca** [comment]
Is this some difference between mariabd and mysql?

**Comment by kaurinz** [comment]
There might be some variation between the virtual column syntax between MySQL and Mariadb.  I haven't yet tested it using a MySQL server, but the above generated query already fails on a different version of MariaDB

On my local machine (the one which generated it), it runs flawless on 10.2.6-MariaDB, for osx10.12 (x86_64).

However on a remote server running  10.1.24-MariaDB, it refuses to run due to the STORED on the virtual column line. Once omitted, the query runs.

**Comment by kaurinz** [comment]
After reviewing the syntax for the columns, MariaDB versions until 10.2.1 didn't support the STORED  keyword. 

The values returned in the EXTRA information for a virtual column also changed – version 10.1.24
(with STORED omitted) returns _VIRTUAL_ whereas 10.2.1 returns _VIRTUAL GENERATED_ . 

As mentioned earlier, given the table defined above  _STORED GENERATED_  is returned in 10.2.1 in the EXTRA information .
