### ISSUE TITLE
Postgres select "COUNT() AS": PG::SyntaxError: ERROR:  syntax error at or near "AS"

### ISSUE THREAD

**Issue by olegantonyan** [rails/rails#29686]
### Steps to reproduce
```ruby
begin
  require "bundler/inline"
rescue LoadError => e
  $stderr.puts "Bundler version 1.10 or later is required. Please update your Bundler"
  raise e
end

gemfile(true) do
  source "https://rubygems.org"
  gem "rails", github: "rails/rails"
  gem "arel", github: "rails/arel"
  gem "pg"
end

require "active_record"
require "minitest/autorun"
require "logger"

# This connection will do for database-independent bug reports.
ActiveRecord::Base.establish_connection(adapter: "postgresql", database: "test", username: "testuser")
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :posts do |t|
    t.string :text
  end
end

class Post < ActiveRecord::Base
end

class BugTest < Minitest::Test
  def test__stuff
    3.times { |i| Post.create!(text: "post #{i}") }

    Post.select('posts.*, COUNT(*) OVER() AS posts_count').group('posts.id').find_each { |i| puts i.attributes } # OK
    puts Post.select('posts.*, COUNT(*) OVER() AS posts_count').group('posts.id').count # ERROR
  end
end
```

### Expected behavior
Printed correct number of records

### Actual behavior
Calling `count` yields this error:
```ActiveRecord::StatementInvalid: PG::SyntaxError: ERROR:  syntax error at or near "AS"
LINE 1: SELECT COUNT(posts.*, COUNT(*) OVER() AS posts_count) AS cou...
                                              ^
: SELECT COUNT(posts.*, COUNT(*) OVER() AS posts_count) AS count_posts_all_count_all_over_as_posts_count, posts.id AS posts_id FROM "posts" GROUP BY posts.id
```
### System configuration
**Rails version**:
5.1
**Ruby version**:
2.4.1

**Comment by meinac** [comment]
`count` method always fires count query. You can use `length` or `size` method to avoid firing count query. **Note that**, if the count of the result set is the only thing you are interested in, using `count` makes more sense because it fires only the count query instead of loading all entries from database into memory.

**Comment by ddfznt** [comment]
call `.count` should ignore `.select`, right? 🤔

**Comment by olegantonyan** [comment]
@meinac this isn't really a solution because this will count real objects instead of nice and fast count() sql query

**Comment by meinac** [comment]
This is what I've already mentioned. If you want to skip previous `select` call, you can try `except` method.

**Comment by olegantonyan** [comment]
This is still hacky.
I use `to_a` as workaround which is basically the same as you mentioned earlier and it's ok in my case. But the point of this issue is that it feels like a bug in ActiveRecord.

**Comment by matthewd** [comment]
`select(...).count()` is equivalent to `count(...)`. If you don't want to count by the `select`ed columns, you can use `count(:all)`. Grouping complicates things further, but the general rule is that `size` should Just Figure Out What To Do, whereas `count` is a lower-level method that explicitly constructs a `COUNT()` SQL query: it gives stronger control, but that flexibility means it also has sharper corners when things get more complex.
