### ISSUE TITLE
Cannot register custom Capybara drivers 

### ISSUE THREAD

**Issue by sebastianiorga** [rails/rails#29688]
### Steps to reproduce

New 5.1.2 app with some system test written. Chromedriver installed. The following system test configuration:

```ruby
# test/application_system_test_case.rb
require 'test_helper'
require 'capybara'
# require 'capybara/poltergeist'

ENV['RAILS_SYSTEM_TESTING_SCREENSHOT'] = 'simple'

class ApplicationSystemTestCase < ActionDispatch::SystemTestCase
  # driven_by :selenium, using: :chrome, screen_size: [1400, 1400]
  Capybara.register_driver(:headless_chrome) do |app|
    capabilities = Selenium::WebDriver::Remote::Capabilities.chrome(
      chromeOptions: { args: %w[headless disable-gpu window-size=1920x1080] }
    )

    Capybara::Selenium::Driver.new(
      app,
      browser: :chrome,
      desired_capabilities: capabilities
    )
  end
  driven_by :headless_chrome
  # Rack::Test
  # driven_by :rack_test

  # capybara-webkit
  # Capybara::Webkit.configure do |config|
  #   config.raise_javascript_errors = false
  # end
  # driven_by :webkit

  # Poltergeist
  # Capybara.register_driver :poltergeist do |app|
  #   Capybara::Poltergeist::Driver.new(app, js_errors: true)
  # end
  # driven_by :poltergeist
end
```

### Expected behavior
`rails test:system` works just fine, and uses headless chrome.

### Actual behavior
Every test errors due to a nil error in `Capybara::Session#driver` since driver ends up being set to nil for the `:headless_chrome` mode.

```
bin/rails test test/system/data_hub_filters_test.rb:93

E

Error:
DataHubFiltersTest#test_can_filter_and_save_and_delete_a_search_immediately:
NoMethodError: undefined method `needs_server?' for nil:NilClass
    /home/seb/.rvm/gems/ruby-2.4.1/gems/capybara-2.14.4/lib/capybara/session.rb:87:in `initialize'
    /home/seb/.rvm/gems/ruby-2.4.1/gems/capybara-2.14.4/lib/capybara.rb:304:in `new'
    /home/seb/.rvm/gems/ruby-2.4.1/gems/capybara-2.14.4/lib/capybara.rb:304:in `current_session'
    /home/seb/.rvm/gems/ruby-2.4.1/gems/capybara-2.14.4/lib/capybara/dsl.rb:45:in `page'
    /home/seb/.rvm/gems/ruby-2.4.1/gems/capybara-2.14.4/lib/capybara/dsl.rb:50:in `block (2 levels) in <module:DSL>'
    /home/seb/work/active_apps/water_data/test/system/data_hub_filters_test.rb:173:in `load_utilities_page'
    /home/seb/work/active_apps/water_data/test/system/data_hub_filters_test.rb:8:in `setup'

Error:
DataHubFiltersTest#test_can_filter_and_save_and_delete_a_search_immediately:
NoMethodError: undefined method `needs_server?' for nil:NilClass
    /home/seb/.rvm/gems/ruby-2.4.1/gems/capybara-2.14.4/lib/capybara/session.rb:87:in `initialize'
    /home/seb/.rvm/gems/ruby-2.4.1/gems/capybara-2.14.4/lib/capybara.rb:304:in `new'
    /home/seb/.rvm/gems/ruby-2.4.1/gems/capybara-2.14.4/lib/capybara.rb:304:in `current_session'
    /home/seb/.rvm/gems/ruby-2.4.1/gems/capybara-2.14.4/lib/capybara/dsl.rb:45:in `page'
    /home/seb/.rvm/gems/ruby-2.4.1/gems/actionpack-5.1.2/lib/action_dispatch/system_testing/test_helpers/screenshot_helper.rb:49:in `save_image'
    /home/seb/.rvm/gems/ruby-2.4.1/gems/actionpack-5.1.2/lib/action_dispatch/system_testing/test_helpers/screenshot_helper.rb:24:in `take_screenshot'
    /home/seb/.rvm/gems/ruby-2.4.1/gems/actionpack-5.1.2/lib/action_dispatch/system_testing/test_helpers/screenshot_helper.rb:36:in `take_failed_screenshot'
    /home/seb/.rvm/gems/ruby-2.4.1/gems/actionpack-5.1.2/lib/action_dispatch/system_testing/test_helpers/setup_and_teardown.rb:18:in `after_teardown'
```

### System configuration
**Rails version**: 5.1.2
**Ruby version**: 2.4.1
**Capybara version**: 2.14.4
**Chrome version**: 59.0.3071.115 (Official Build) (64-bit)
**Chromedriver version**: 2.30.477691
**OS**: Ubuntu 15.04

### Background
The changes made in [this commit](https://github.com/rails/rails/commit/c5dd45119a28fb1c41de6d27d63443480c86894e), associated with [this pull request](https://github.com/rails/rails/pull/29315), to `actionpack/lib/action_dispatch/system_testing/driver.rb` break the ability to register Capybara drivers not named `[:selenium, :poltergeist, :webkit]`.

Because `ActionDispatch::SystemTesting::Driver#driver` now gets called UNLESS name is :rack_test, it ends up overwriting custom Capybara drivers setup in `RAILS_ROOT/test/application_system_test_case.rb` with nil(since the case statement in `ActionDispatch::SystemTesting::Driver#register` can only handle 3 keys.

### Super quick and dirty fix
Super hacky fix is to monkey patch `ActionDispatch::SystemTesting::Driver#register`:

```ruby
# test/application_system_test_case.rb
require 'test_helper'
require 'capybara'
# require 'capybara/poltergeist'

ENV['RAILS_SYSTEM_TESTING_SCREENSHOT'] = 'simple'
ActionDispatch::SystemTestCase.driver # dumb way to make sure all constants are loaded.
class ActionDispatch::SystemTesting::Driver # :nodoc:
  def register
    return unless [:selenium, :poltergeist, :webkit].include?(@name)

    Capybara.register_driver @name do |app|
      case @name
      when :selenium then register_selenium(app)
      when :poltergeist then register_poltergeist(app)
      when :webkit then register_webkit(app)
      end
    end
  end
end

class ApplicationSystemTestCase < ActionDispatch::SystemTestCase
...
```

This is obviously not the way to go about things. I'm not sure modifying `ActionDispatch::SystemTesting::Driver#register` with that guard clause is the right solution either. After all: what makes those 3 options special? And if they are special there should be some single source of truth where they are declared with the case statement and other areas in the code referencing them.

Maybe the clean solution is to just check if the user has already registered a Capybara driver for that name and do nothing in that situation?

**Comment by eileencodes** [comment]
Thanks for the report @sebastianiorga. I fixed this and backported to 5-1-stable so the next release of 5.1 should have this fix. 

Eventually we'll want to add support for headless chrome directly. Have you found headless chrome to be stable?

**Comment by sebastianiorga** [comment]
Thank you for the fix :)

It works perfectly on the small app I'm using it on. No intermittent/wrong failures(which I did get with poltergeist, usually when modal forms + ajax were involved). Takes screenshots on failure correctly. Setting the window-size option is essential since at the moment it defaults to 800x600 or something ridiculous(at least on my system).

The speed up is only about 10-15% over selenium+chrome, sadly. That being said, I didn't dive very deep into the tests' performance, yet. Other people might see better speed gains.
