### ISSUE TITLE
current_page? requires "action" if custom parameter is set

### ISSUE THREAD

**Issue by elbarto132** [rails/rails#29682]
I'm using rails 5.1.1
If i have a route like
`get '/bla/:something', to: 'bla#whatever'`
and want to check this route using
`current_page? controller: 'bla', something: '123'`
it throws an error stating that it can't find a matching route, because if i don't set an action it is set to index as default somewhere inside the current_page? function and my route/controller doesn't have an index action
so it would require me to write it like
`current_page? controller: 'bla', action: 'whatever' something: '123'`
But my problem was now that i have different action names on which i want to match, and i didn't want to chain multiple function calls for all actions.

In my case this view helper method was a sufficient workaround to replace the current_page? function and get my expected behaviour
```
  def is_active(options)
    options.each do |k,v|
      if params[k] != v
        return false
      end
    end
    true
  end
```

**Comment by shayonj** [comment]
I believe you should just be able to
```ruby
current_page? something: '123'
```

It works because,
> If an explicit :controller was given, always make :action explicit too ...

[here](https://github.com/rails/rails/blob/master/actionpack/lib/action_dispatch/routing/route_set.rb#L67), `index` is made default action, if `controller` is given but no `action`.

**Comment by j1wilmot** [comment]
What is unexpected about this behavior? `current_page?` uses `url_for` under the hood, and `url_for` needs an action passed to it, so erroring seems like a very reasonable behavior if an action option isn't passed. Wrapping `current_page?` in another helper as you have done is a fine solution if you don't want to specify the action every time, but I don't see what rails should do differently here.

**Comment by sgrif** [comment]
I don't think there is any bug here.

**Comment by elbarto132** [comment]
Maybe not a bug, but it's unexpected behaviour that an action is required if i pass controller
Imho code like this:
`options[:action]     ||= "index"`
Is ok in my personal website project, but not in a framework at the scale of rails. If it's a required value throw if it's not set and don't just set it to something.
So my suggestion would be to add a deprecation warning if it's not set, and make it throw in rails 6.

Is it somehow necessary that current_page? uses url_for or could we just replace it with a function like mine which would significantly reduce the functions footprint? I don't know if this would break somewhere.

And for now we could add this line "If an explicit :controller was given, always make :action explicit too" to the documentation of current_page?

**Comment by j1wilmot** [comment]
`url_for` uses `default_url_options` to default params that are not passed, so as an alternative to using a wrapper helper method to set the action you could define `default_url_options` to set the default action you want to use. That may also be what is defaulting the action to index in your example. You can check out http://api.rubyonrails.org/v5.1/classes/ActionDispatch/Routing/UrlFor.html for more info on using `default_url_options`.
