### ISSUE TITLE
No such file or directory @ rb_sysopen

### ISSUE THREAD

**Issue by danielsteevin** [rails/rails#29691]
Hi, I need upload a file, but when I try to copy it to put it in the public folder I get this error` No such file or directory @ rb_sysopen`.

I think it's because it does not find the directory from where it's going to be copied and I do not know how to send it.

Please help me.

### System configuration
**Rails version**: 5.0.2

**Ruby version**: 2.4.1

**Comment by KayCaesar** [comment]
https://www.paulleasure.com/errors-fixes/how-to-fix-errnoenoent-no-such-file-or-directory-rb_sysopen-undefined-grunt-error/

There are many posts online about this error. How are you copying the file? As what user? What is the full path and what are the permissions/ownerships on all of the directories?

**Comment by danielsteevin** [comment]
file = params[:file]

directory = "#{::Rails.root}/public/files/"

FileUtils.cp_r(file, directory)

**Comment by matthewd** [comment]
Please use the mailing list or StackOverflow for questions/help, where a wider community will be able to help you. We reserve the issues tracker for issues only.
