### ISSUE TITLE
FrontEnd use actioncable npm package

### ISSUE THREAD

**Issue by pdkproitf** [rails/rails#29709]
### ActionCable NPM Package

I got 2 problems when I try to use actiocable of npm package.
I using it on angular 2 app to call Rails API server.

### Expected behavior
First: When I create a consumer, using this command: "var cable = ActionCable.createConsumer('wss://RAILS-API-PATH.com/cable')"
Sometimes it throw exception `WebSocket connection to 'wss://localhost:3000/cable' failed: Error in connection establishment: net::ERR_SSL_PROTOCOL_ERROR`

Seconds: When I try to create a consumer, how can I send auth_params to Serve.  I mean, how can pass auth_param to  Connection channel.
I researched on google but I couldn't find the solution. Please help me.

### System configuration
**Rails version**:

**ruby 2.4.0p0 **:

**Comment by matthewd** [comment]
> `wss://localhost:3000/cable`

Is your server expecting a TLS connection on port 3000?

Please use the mailing list or StackOverflow for questions/help, where a wider community will be able to help you. We reserve the issues tracker for issues only.

**Comment by Capitalsav** [comment]
If you use 

> wss://localhost:3000/cable

and got this error:
`VM9525:164 WebSocket connection to 'wss://localhost:3000/cable' failed: Error in connection establishment: net::ERR_SSL_PROTOCOL_ERROR`
Try to use this:
`ws://localhost:3000/cable`
