### ISSUE TITLE
eager_loading has_one association not taking default scoped order into account 

### ISSUE THREAD

**Issue by Mathiou04** [rails/rails#29713]
If we have a has_one relationship with a scope defining an order, this order is not taken into accounting during the eager_loading. Using preload works as expected.

Here is the test case that fails:
```ruby
begin
  require "bundler/inline"
rescue LoadError => e
  $stderr.puts "Bundler version 1.10 or later is required. Please update your Bundler"
  raise e
end

gemfile(true) do
  source "https://rubygems.org"
  gem "rails", github: "rails/rails"
  gem "sqlite3"
end

require "active_record"
require "minitest/autorun"
require "logger"

# This connection will do for database-independent bug reports.
ActiveRecord::Base.establish_connection(adapter: "sqlite3", database: ":memory:")
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :documents, force: true do |t|
  end

  create_table :pages, force: true do |t|
    t.integer :document_id
  end
end

class Page < ActiveRecord::Base
  belongs_to :document
end

class Document < ActiveRecord::Base
  has_many :pages
  has_one :last_page, -> { order(id: :desc) }, class_name: 'Page'
end


class BugTest < Minitest::Test
  def test_last_page
    document = Document.create
    page1 = Page.create(document: document)
    page2 = Page.create(document: document)


    loaded_document = Document.eager_load(
        :last_page
    ).all

    assert_equal loaded_document[0].last_page, page2
  end

end
```
Unless I made a mistake, it fails on 4.2 but also on current master. I wondered if it was an issue similar to #28415 so I tested it also against @kamipo pull request #29154 but it looks like it still fails.

**Comment by EddM** [comment]
I could be wrong, but it appears to me that `#eager_load` isn't intended to be used in this way since it uses a join to eager load the associations, instead of the alternatives that fetch the associated records in separate queries - `#eager_load` would then be useful when you are _filtering_ your results by the associations, but not in other cases.

`#preload` seems to be the eager loading strategy you want here. Check out this pry session for your above example:

````ruby
[1] pry(main)> document = Document.create
[2] pry(main)> page1 = Page.create(document: document)
[3] pry(main)> page2 = Page.create(document: document)

[4] pry(main)> Document.eager_load(:last_page).all[0].last_page
D, [2017-07-09T14:56:48.174295 #9520] DEBUG -- :   SQL (0.3ms)  SELECT "documents"."id" AS t0_r0, "pages"."id" AS t1_r0, "pages"."document_id" AS t1_r1 FROM "documents" LEFT OUTER JOIN "pages" ON "pages"."document_id" = "documents"."id"
=> #<Page:0x007fa79ed60d10 id: 1, document_id: 1>

[5] pry(main)> Document.preload(:last_page).all[0].last_page
D, [2017-07-09T14:56:53.585341 #9520] DEBUG -- :   Document Load (0.1ms)  SELECT "documents".* FROM "documents"
D, [2017-07-09T14:56:53.586728 #9520] DEBUG -- :   Page Load (0.1ms)  SELECT "pages".* FROM "pages" WHERE "pages"."document_id" = 1 ORDER BY "pages"."id" DESC
=> #<Page:0x007fa79ecfd788 id: 2, document_id: 1>
````

Whether or not this is expected behaviour, I dunno. It makes sense that it would be expected, because reconciling different `order` clauses from different sources (i.e. both the `Document` model and its `Page` association could potentially both have order clauses) could be awkward.

**Comment by Mathiou04** [comment]
Thank you for taking the time to answer this @EddM.
The above test case is in fact a simplified version of what happened to us in our application to isolate the issue. I will try to give a clearer description of what could happen because of this. Let's say I add a new model `Author`, with a `valid` attribute and a new relation between the `Document` and the `Author` :
```ruby
class Author < ActiveRecord::Base
  has_many :documents
end

class Document < ActiveRecord::Base
  belongs_to :author
  has_many :pages
  has_one :last_page, -> { order(id: :desc) }, class_name: 'Page'

  scope :valid, -> { where(valid: true) }
end

Document.includes(:author, :last_page).valid
```
Rails will use `#preload` and everything will work as expected. Now imagine I modify the `valid` scope like this:
```ruby
  scope :valid, -> { where(valid: true).joins(:author).where(author: {valid: true}) }
```
Now because of the `where` clause on the joined association, Rails will use `eager_load` for both `author` and `last_page` and the preloaded `last_page` will not be correct.

I agree that I can still force a `preload` in this case (that is what I did to fix our production issue), but it looks a bit like a fragile interface to me. And if I add a `where` condition on the `pages` in the query, it will also break unless I force a `preload` + `joins` which is what I think `eager_load` tries to avoid.

I also agree that even if it were possible, adding the `ORDER` clause in the sql might not be a good idea. But maybe we could do it directly in Ruby after the query, as we retrieve all the `pages` ?

**Comment by onyxblade** [comment]
If someone is in need of this feature, creating a SQL view that has the default scope inside might help. https://github.com/scenic-views/scenic this gem is very handy in maintaining SQL views in Rails.
