### ISSUE TITLE
config.action_dispatch.show_exceptions = true seems counterintuitive

### ISSUE THREAD

**Issue by brunofacca** [rails/rails#29712]
It seems like `config.action_dispatch.show_exceptions` (which comes set to `false` in `config/environments/test.rb`) is counterintuitive, even misleading. One can expect that setting `show_exceptions` to `true` will actually show exceptions. However, by setting it to `true`, exceptions are rescued and Rails returns a corresponding HTTP status code. By setting it to `false`, exceptions are not rescued (they are "showed").

Am I missing something here?

**Comment by matthewd** [comment]
I agree that "show" is a matter of perspective... but I'm not sure there's much we can do to improve this, short of disruptively renaming it to something much longer and more detailed about what it will actually do.

`test.rb` comes with our best guess at useful defaults for a test environment. But note the config setting is for Action Dispatch, not for the test system: as far as that framework is concerned, it *shows* the exception when it reports it via its primary interface (the HTTP response), and hides it when it doesn't. Consider which value feels more like "show" when placed in `development.rb`, for example.
