### ISSUE TITLE
Changes in time calculations

### ISSUE THREAD

**Issue by Paxa** [rails/rails#29743]
Since 5.1.2 some time calculation changed (also latest version in git)

```ruby
time = Time.current
time -= time.to_f % 30.minutes # round down to half an hour
p time.to_s # => 173056-02-10 23:00:00 UTC
```
When using rails 5.1.1 or earlier it will give `"2017-07-10 18:00:00 UTC"`

I use this calculations for making charts, I think it's a bug

**Comment by Paxa** [comment]
Probably same issue as https://github.com/rails/rails/issues/29603

**Comment by meinac** [comment]
@Paxa did you check this with the version of code sent in [this](https://github.com/rails/rails/pull/29606) pr.

**Comment by Paxa** [comment]
@meinac Actually no.
That PR fixes only when `<ActiveSupport::Duration> % <ActiveSupport::Duration>`
In my example it's `<ActiveSupport::TimeWithZone> % <ActiveSupport::Duration>`

**Comment by Sayanc93** [comment]
@Paxa Can you pull my branch again and check? I've addressed your use case, modulo operations on Scalar returns Duration object in seconds.

I've squashed my commits on that branch so you might have to do a fresh pull.

**Comment by Paxa** [comment]
@Sayanc93 It works great now! Thank you for fixing it!

**Comment by Paxa** [comment]
Fixed by https://github.com/rails/rails/pull/29606
