### ISSUE TITLE
rails new --webpack --skip-sprockets still creates the assets folder, doesn't set up Webpacker for CSS

### ISSUE THREAD

**Issue by unikitty37** [rails/rails#29749]
### Steps to reproduce

Enter `rails new testapp --webpack --skip-sprockets`

### Expected behavior
The new app is created without the `app/assets` folder, and with Webpack configured to serve stylesheets from a documented location.

### Actual behavior
The `app/assets` folder, and its underlying structure, is created, despite the fact that dropping stylesheets into `app/assets/stylesheets` no longer causes them to be loaded. This is misleading, at best.

As Webpacker can replace Sprockets, this seems to be a use case that's going to become increasingly common. People doing this are going to want to use stylesheets — should `rails new` not set things up so there is a place to put stylesheets such that they'll be automatically packed into application.css, and should the docs not cover this use case a bit more clearly?

I've filed this under rails/rails, because it seems that `rails new` is erring by creating `app/assets` when the asset pipeline's not being used, but I suspect there are various places it could go; my apologies if I've got it wrong.

### System configuration
**Rails version**: 5.1.2

**Ruby version**: 2.4.1p111

**Comment by matthewd** [comment]
Thanks, but this feels more like a feature request than a bug. We reserve the issues tracker for issues only.

While people are free to experiment with more future-thinking setups, Sprockets remains the recommended mechanism for managing assets.

**Comment by lustrousgorilla** [comment]
Even if Sprockets is the recommended setup, shouldn't the --skip-sprockets flag actually remove the Sprockets dependency?
