### ISSUE TITLE
[ActiveRecord] after_commit callback is called when update fails within explicit transaction block

### ISSUE THREAD

**Issue by naw** [rails/rails#29747]
### Steps to reproduce

```ruby
begin
  require "bundler/inline"
rescue LoadError => e
  $stderr.puts "Bundler version 1.10 or later is required. Please update your Bundler"
  raise e
end

gemfile(true) do
  source "https://rubygems.org"
  gem "rails", github: "rails/rails"
  gem "arel", github: "rails/arel"
  gem "sqlite3"
end

require "active_record"
require "minitest/autorun"
require "logger"

# This connection will do for database-independent bug reports.
ActiveRecord::Base.establish_connection(adapter: "sqlite3", database: ":memory:")
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :posts, force: true do |t|
    t.string :arbitrary_column
  end
end

class Post < ActiveRecord::Base
  after_commit :my_callback

  validates :arbitrary_column, length: { minimum: 10 }

  def my_callback
    puts "Callback was called"
    if changed?
      fail "This callback should not be called"
    end
  end
end

class BugTest < Minitest::Test
  def test_callback_is_not_called_when_save_fails

    post = Post.create!(arbitrary_column: "This is valid")
    post = Post.find(post.id)

    Post.transaction do
      post.arbitrary_column = 'too short'
      assert !post.valid?
      post.save # This won't actually save, but the callback is (incorrectly) called anyway because the transaction commits
    end

  end
end
```

### Expected behavior

`after_commit` callbacks should only be called if the underlying record is successfully saved.
  
### Actual behavior

When updating an existing record, `after_commit` callbacks are called even if the update fails (when attempted update is within an explicit transaction block).

### Note

A similar issue was fixed for record creation in #9115

I believe the underlying problem is that https://github.com/rails/rails/blob/07ed697f7b0debd8736a188fad67fe5e0c98739e/activerecord/lib/active_record/transactions.rb#L341 uses `persisted?` to determine if the save succeeded. This isn't an adequate heuristic for existing records (because they are `persisted?` regardless of whether the underlying update succeeds).

I would be happy to work on a PR, if you can confirm that this is a bug.

**Comment by lugray** [comment]
This looks like a bug to me.  Will possibly help with the fix: if you change to `after_commit :my_callback, on: [:create, :update, :destroy]`, the test passes.  That option should be superfluous.

**Comment by lugray** [comment]
@naw Are you still planning to work on a PR for this?

**Comment by naw** [comment]
@lugray Yes, thanks for taking a look and confirming that this looks like a bug. I am planning to work on a PR.
