### ISSUE TITLE
[ActiveRecord] OFFSET does not work with Postgres FLOOR function

### ISSUE THREAD

**Issue by anduong** [rails/rails#29751]
### Steps to reproduce
**This should be a feature request actually**
I am selecting random records from Postgres according to this
https://stackoverflow.com/questions/5297396/quick-random-row-selection-in-postgres
```Ruby
MyTable.offset("floor(random() * #{MyTable.count}))")
```
or even
```Ruby
MyTable.offset("floor(2.5)")
```

### Expected behavior
It should generate the SQL query like
```SQL
SELECT * FROM my_tables OFFSET 2
```

### Actual behavior
```SQL
SELECT * FROM my_tables OFFSET 0
```

### System configuration
**Rails version**: 4.2.3

**Ruby version**: 2.2.3

**Comment by anduong** [comment]
I use Ruby `floor` for the calculation as a workaround for now.

**Comment by lugray** [comment]
This is intentional: `"floor(2.5)".to_i` is 0.  The form you wish cannot be done with a [parameterized query](https://www.w3schools.com/sql/sql_injection.asp).  What's wrong with `MyTable.offset(rand(MyTable.count)).limit(1)`?

**Comment by sgrif** [comment]
We don't accept feature requests on the issue tracker. Feature requests can be submitted at the [Rails Core Mailing List](https://groups.google.com/forum/#!forum/rubyonrails-core)
