### ISSUE TITLE
Error in production env not manifested in dev/test environments

### ISSUE THREAD

**Issue by lazylester** [rails/rails#29755]
### Steps to reproduce
Standard out-of-the-box rails installation,
One of the views has an internationalized field translated with an interpolation argument, like:
=t('.greeting', name : 'Wilma')
so the locale file has:
`en:
    greeting: 'hello %{name}`

but due to a coding error, this translation is called without the interpolation argument at some point:
=t('.greeting')

### Expected behavior
Integration tests should fail, because in the production environment this will cause a failure and the page will not render. Therefore we need to discover this error in the development and test environments too.

### Actual behavior
In development and test environments, the translated locale string (in the above example) simply renders as "Hello %{name}".

But in the production environment (where the standard out-of-the-box i18n configuration in environments/production.rb has config.i18n.fallbacks = true), an error is raised in i18n and the page does not render.

### System configuration
**Rails version**: 5.1.2 (This problem did not exist in 5.0.x, I don't know why)
i18n version: 0.8.5

**Ruby version**: 2.4.0

### Solution?
configuring config.i18n.fallbacks = true in environments/development.rb and environments/test.rb solves the problem, but since this has only come about in Rails 5.1.2, it's possible that there is a more appropriate solution. My proposal, then, is for the standard rails dev/test environment config files to have config.i18n.fallbacks = true.

It's possible that the root cause of the error here is in the i18n gem, or it may be intentional behaviour of the i18n gem, but nevertheless, b/c the configuration in production is different from development/test, the error is not caught.

**Comment by Edouard-chin** [comment]
You can make it raise in development/test environment by uncommenting this line https://github.com/rails/rails/blob/master/railties/lib/rails/generators/rails/app/templates/config/environments/development.rb.tt#L56

**Comment by lazylester** [comment]
Yes, I agree, my point is that it should be standard operation, so that rails "out of the box" comes configured this way.

**Comment by Edouard-chin** [comment]
If we were to have this behaviour by default, we would get a `500` without having a chance to see what was the missing translation.

IMHO it's better to not raise and just be able to see which translation is missing. Rails adds a  `.translation_missing` css class to the wrapped span https://github.com/rails/rails/blob/47eadb68bfcae1641b019e07e051aa39420685fb/actionview/lib/action_view/helpers/translation_helper.rb#L107 you could add a css rule in your app to make if super flashy or something to be able to see it quickly?

**Comment by lazylester** [comment]
I can understand your point about not seeing the missing translation, but in much of TDD you don't spend much time actually looking at the page, just the test results.

Better, in my view, to get a 500 in test than to get it for the first time in production! That's why we test, no?

Better too, in my view, to make the default configuration the one which catches the error, vs remembering to look for every translation being present. It makes refactoring unwieldy translation files less error-prone too.

**Comment by meinac** [comment]
> Better, in my view, to get a 500 in test than to get it for the first time in production! That's why we test, no?

I totally agree with this. I think it's better to have **almost** same configuration with production at test environment. But maybe there should be a smooth transition from current behaviour maybe with a deprecation message or maybe deprecation is just redundant.

**Comment by Edouard-chin** [comment]
Also agree that in **test** this would be better if it raised

**Comment by sgrif** [comment]
Deprecation would be redundant. We shouldn't change the behavior of existing apps here, we only need to change the generated file if we choose to make this change. I'd want to know the reasoning for this being a production-only setting when it was originally introduced before changing it.

**Comment by meinac** [comment]
Yes you are completely right, we can just change the template and new applications should work in this way. Could you please let us know when you get the reason about why this is set like this.

**Comment by lazylester** [comment]
@sgrif I don't know how to find out the rationale for this being a production-only setting. If you have some ideas let me know, I have little experience at open source PRs.

Ordinarily I would agree that this understanding would better inform the decision. However in this case the proposed change _only_ affects dev and test environments, and then only their default settings. The developer can always change the configuration. And, too, it's a conservative change where more errors will be caught in dev and test.

If you are persuaded, let me know and I'll generate a PR. Are new tests required, or is it sufficient to ensure that existing tests still pass?

**Comment by sgrif** [comment]
`git blame` would be the way to find it

**Comment by lazylester** [comment]
@sgrif yes, that's what I thought, but it doesn't give you insight into why a line of code is not there, when it has never been there. The line

`config.i18n.fallbacks = true`

is included in config/initializers/production.rb but not in config/initializers/def(or test).rb

or am I missing something?
