### ISSUE TITLE
Entire Rails.root is being watched when watchable_dirs contains non-existing directory

### ISSUE THREAD

**Issue by schnittchen** [rails/rails#29750]
### Steps to reproduce

* Create an app with _lots_ of files somewhere below `Rails.root` (but outside the usual directories where Rails expects files to be able to reload in development mode)
* Start the rails console, or a rake task, do anything that boots the Rails environment
* The boot process takes long (up to a minute with thousands of files), you can watch Rails stat'ing each of the files using strace

### Expected behavior

We have a large number of files below `Rails.root.join("import_data"), that Rails should not care about. Boot times should not be affected.

### Actual behavior

Boot is slow, and the console / rake task / ... performs badly for some time afterwards, while the process is still stat'ing files.

### System configuration

Rails 5.1.0.rc1, ruby 2.4.1p111 (2017-03-22 revision 58053) [x86_64-linux]

**Comment by schnittchen** [comment]
Some details:

In our case, `config.watchable_dirs` contains `"#{Rails.root}/test/mailers/previews"=>[:rb]`, but `Rails.root.test` does not exist. Here https://github.com/rails/rails/blob/8d98bb0cc6e2baf1694971ae2bdf19e8b8bcdce5/activesupport/lib/active_support/evented_file_update_checker.rb#L125 the path is normalized (through https://github.com/rails/rails/blob/8d98bb0cc6e2baf1694971ae2bdf19e8b8bcdce5/activesupport/lib/active_support/evented_file_update_checker.rb#L170) to the "most recent" existing ancestor path, which is `Rails.root`.

The effect is that the entirety of the Rails app is being watched, which is slow, and I'm constantly running out of Inotify handles.

In my case, `mkdir -p test/mailers/preview` worked around the issue.

**Comment by rishav** [comment]
@schnittchen like you ssiad this because the "test" directory doesn't exist. Correct? In that case the expected behaviour should be that the entire "Rails.root" directory shouldn't end up getting watched ?

**Comment by schnittchen** [comment]
That is true. Adding `test` would have worked around as well.

**Comment by matthewd** [comment]
It is expected behaviour that we watch `Rails.root` in this case, so that we'll notice if a `test` directory appears... but there should be no need to recurse in order to do that.

I'm not sure whether this is something we're doing wrong, or an API limitation of the `listen` gem.

(I assume that disabling the `EventedFileUpdateChecker` makes the problem go away?)

**Comment by schnittchen** [comment]
Why is this expected behaviour? Why is the nearest ancestor path picked insted of skipping a path?

**Comment by matthewd** [comment]
> It is expected behaviour that we watch Rails.root in this case, **so that we'll notice if a test directory appears.**

**Comment by schnittchen** [comment]
That makes sense indeed...

Given that the problem is googlable now and there is a workaround, I'm closing this issue.

**Comment by schnittchen** [comment]
Thanks @matthewd for the explanation.
