### ISSUE TITLE
Add something like `default_value` for initializing class_attribute

### ISSUE THREAD

**Issue by glaucocustodio** [rails/rails#29754]
Hi there, the guides shows us how to initialize a class_attribute (http://edgeguides.rubyonrails.org/active_support_core_extensions.html#class-attributes) by doing so:

```ruby
class Pet
  class_attribute :table_name_prefix
  self.table_name_prefix = "myapp"
end
```

Would something like a default_value be welcome?

```ruby
class Pet
  class_attribute :table_name_prefix, default_value: "myapp"
end
```

I intend to make a PR if you think it's ok.

**Comment by georgeclaghorn** [comment]
A `:default` option was added to `class_attribute` in #29270.

**Comment by glaucocustodio** [comment]
Thanks, I didn't know. Here is a PR adding documentation https://github.com/rails/rails/pull/29758.
