### ISSUE TITLE
PG::ProtocolViolation: bind message supplies 1 parameters, but prepared statement "" requires 2

### ISSUE THREAD

**Issue by doits** [rails/rails#29766]
Combining some `where` queries with an `.or` and `.merge` can lead to: 

> PG::ProtocolViolation: bind message supplies 1 parameters, but prepared statement "" requires 2

Having a simple class `Person` with a `status` column, the following query generates the error:

```ruby
Person
  .where(status: 1)
  .or(Person.where('1 = 1'))
  .where(status: 2)
  .merge(Person.where(status: 3))
```

I admit the query looks constructed (and makes no sense in itself), but it happened to me that my complex Rails app generated a similar query like this today (through various scopes) and I could reduce the test case to this one just to trigger the bug.

It does not matter what the `status` is searched for (value could be all `1`, too).

As far as I can tell, one must have exactly this order of method calls to hit the bug. For example, all these do *not*  trigger the bug:

```ruby
# no or
Person
  .where(status: 1)
  .where(status: 2)
  .merge(Person.where(status: 3))

# no merge
Person
  .where(status: 1)
  .or(Person.where('1 = 1'))
  .where(status: 2)

# no first where
Person
  .all
  .or(Person.where('1 = 1'))
  .where(status: 2)
  .merge(Person.where(status: 3))

# second where before or
Person
  .where(status: 1)
  .where(status: 2)
  .or(Person.where('1 = 1'))
  .merge(Person.where(status: 3))
```

Running the test template (see below) with sqlite adapter works as expected, that's why I think it is postgresql specific.

### Steps to reproduce

Run the [test template](https://gist.github.com/doits/4ce503e5a061a72b8d927030dec80176). It tries to use a postgres database named `test` by default.

### Expected behavior

All queries in test template should work.

### Actual behavior

> ActiveRecord::StatementInvalid: PG::ProtocolViolation: ERROR:  bind message supplies 1 parameters, but prepared statement "" requires 2

### System configuration
**Rails version**: 5.1.2

**Ruby version**: 2.4.1

**Comment by kamipo** [comment]
This is due to `non_conflicting_binds` rejects all matched binds.
This should be fixed by #29621.

**Comment by doits** [comment]
Is sqlite then silently ignoring the error? Or why does it happen only on postgres for me?

I cannot test your PR unfortunately, because when loading rails with...

```ruby
gem 'rails', github: 'che-burashco/rails', branch: 'issue-29445'
```

... I always get an error when trying to run the test template:

> There was an error while trying to load the gem 'rails'. (Bundler::GemRequireError)
> Gem Load Error is: superclass mismatch for class Cipher
> Backtrace for gem load error is:
> .../.rbenv/versions/2.4.1/lib/ruby/2.4.0/openssl/cipher.rb:64:in `<class:Cipher>'

Happens on rails master, too, though. Not sure what's wrong. I already reinstall openssl and ruby, but it didn't change.

**Comment by kamipo** [comment]
If # of bind values are short than placeholders, SQLite simply ignore and do not replace `?`.

**Comment by doits** [comment]
@sgrif thanks, the bug is gone now on current master! Is there any plan to backport this to 5.1.x?

**Comment by sgrif** [comment]
No, the fix is not something that can be backported.
