### ISSUE TITLE
[ActiveRecord] Postgres reconnection error on database failover

### ISSUE THREAD

**Issue by cswilliams** [rails/rails#29760]
### Steps to reproduce

1. Create a rails app with sidekiq workers that connect to a postgres AWS RDS instance.
2. Force a manual failover of postgres instance on AWS RDS.
3. After database failover, a small number of sidekiq jobs will continually fail with the following error/backtrace:
```ruby
PG::UnableToSend: SSL SYSCALL error: EOF detected
  File "/home/app/.bundle/2.3.3/1/ruby/2.3.0/gems/activerecord-5.0.1/lib/active_record/connection_adapters/postgresql_adapter.rb", line 197, in exec
  File "/home/app/.bundle/2.3.3/1/ruby/2.3.0/gems/activerecord-5.0.1/lib/active_record/connection_adapters/postgresql_adapter.rb", line 197, in dealloc
  File "/home/app/.bundle/2.3.3/1/ruby/2.3.0/gems/activerecord-5.0.1/lib/active_record/connection_adapters/statement_pool.rb", line 38, in block in clear
  File "/home/app/.bundle/2.3.3/1/ruby/2.3.0/gems/activerecord-5.0.1/lib/active_record/connection_adapters/statement_pool.rb", line 37, in each_value
  File "/home/app/.bundle/2.3.3/1/ruby/2.3.0/gems/activerecord-5.0.1/lib/active_record/connection_adapters/statement_pool.rb", line 37, in clear
  File "/home/app/.bundle/2.3.3/1/ruby/2.3.0/gems/activerecord-5.0.1/lib/active_record/connection_adapters/postgresql_adapter.rb", line 236, in clear_cache!
  File "/home/app/.bundle/2.3.3/1/ruby/2.3.0/gems/activerecord-5.0.1/lib/active_record/connection_adapters/abstract_adapter.rb", line 386, in reconnect!
  File "/home/app/.bundle/2.3.3/1/ruby/2.3.0/gems/activerecord-5.0.1/lib/active_record/connection_adapters/postgresql_adapter.rb", line 253, in reconnect!
  File "/home/app/.bundle/2.3.3/1/ruby/2.3.0/gems/activerecord-5.0.1/lib/active_record/connection_adapters/abstract_adapter.rb", line 423, in verify!
  File "/home/app/.bundle/2.3.3/1/ruby/2.3.0/gems/activerecord-5.0.1/lib/active_record/connection_adapters/abstract/connection_pool.rb", line 778, in block in checkout_and_verify
....
```

I believe the problem is that StatementPool::connection_active? in the PostgreSQLAdapter is using PG's connection status method which does not accurately update when the connection is disconnected.  Because connection_active? is incorrectly returning true in this case, activerecord is trying to dealloc the statement pool which causes a query to be run on the dead connection, which in turn generates the PG::UnableToSend exception.

It looks like a very similar problem happened once before in a different part of the Postgresql Adapter, see issue #3392 and was changed to the following: https://github.com/rails/rails/commit/4dacac3baa271597e6bcf3527c557182d64a6a95#diff-cc31fc1dd1e78db64638200f710b2f59
Ironically, someone pointed out this problem in the StatementPool class in the original above issue, but it unfortunately was missed, and never made it into the PR for the issue.

Anyhow, it seems like the same fix in issue #3392 needs to be applied to the StatementPool class. In other words, stop relying on the connection status method, since it is not accurate.

### Expected behavior
Rails should reconnect to Postgres without throwing an error.

### Actual behavior
Rails throws an PG::UnableToSend exception instead of reconnecting

### System configuration
**Rails version**: 5.0.1
pg 0.19.0

**Ruby version**: 2.3.3

**Comment by cswilliams** [comment]
I am going to try out the following fix (the same fix as in issue #3392) to the StatementPool class. Changing
```ruby
def connection_active?
    @connection.status == PGconn::CONNECTION_OK
rescue PGError
    false
end
```
TO
```ruby
def connection_active?
    @connection.query 'SELECT 1'
    true
rescue PGError
    false
end
```

If there are no side effects, I will make a PR in a few days.

**Comment by matthewd** [comment]
That could add a lot of round-trips.

I think the surgical fix would be to just rescue & ignore the exception inside `dealloc`.

The wider, less surgical and less backportable, change would be to stop bothering with this at all: if we know the connection (is gone || will be disconnected), we need to flush our internal mapping, but explicitly deallocating the statements on the server is a waste of time.

**Comment by cswilliams** [comment]
Hey Matthew,  

Really appreciate the feedback!  Good point on the round trips since it would be generating a select once per each value in the cache.  What do you think about the following change instead:
Changing the existing PostgreSQLAdapter `clear_cache!` method from calling `@statements.clear` TO `@statements.clear if active?`
I think this would generate a lot less queries since it's higher up the chain. 

Your other suggestion of just ignoring the exception inside dealloc also seems fine too.  

What do you think?

**Comment by matthewd** [comment]
That would avoid sending the pointless DEALLOCATE queries, but would it leave `@statements` believing the statements were still prepared after it reconnects? Threading that needle is why that felt like a more involved change -- probably needing a change to the internal adapter API to better distinguish "`clear` because I want you to actively deallocate everything" from "`clear` because they've gone away anyway, and you just need to catch up".

**Comment by cswilliams** [comment]
Ahh, yes. I see you what you mean now. Thanks for the explanation.

I think I'll just rescue the error in `dealloc` then since that makes it easy to backport.

**Comment by renra** [comment]
Hmm, not sure my problem is the same, but it seems related. I'm also getting `PG::UnableToSend` errors after which the apps won't reconnect, even if the database becomes available again. For now this monkey patch seems to work ...

```ruby
class ActiveRecord::ConnectionAdapters::PostgreSQLAdapter
def exec_no_cache(sql, name, binds)
  type_casted_binds = type_casted_binds(binds)
  log(sql, name, binds, type_casted_binds) do
    ActiveSupport::Dependencies.interlock.permit_concurrent_loads do
      begin
        @connection.exec_params(sql, type_casted_binds)
      rescue PG::UnableToSend
         reconnect!
         exec_no_cache(sql, name, binds)
       end
     end
   end
end
end
```

I'm on a slightly outdated version `v5.2.3` though.

**Comment by tjoyal** [comment]
Most likely related to https://github.com/rails/rails/issues/38324
