### ISSUE TITLE
Rails getting started documentation

### ISSUE THREAD

**Issue by ragavendra** [rails/rails#29774]
### Steps to reproduce
In Rails documentation for update operation 5.11, the controller returns edit method but it does not exist. it has to be created like below. The documentation needs to be added for it

```
  def edit
    @article = Article.find(params[:id])
  end
```

### Expected behavior
Article to be edited should be brought up in the form and can be edited

### Actual behavior
Rails blog gives error

### System configuration
**5.1.2**:

**2.3.0**:

**Comment by lugray** [comment]
That section has the text

> The first step we'll take is adding an `edit` action to the `ArticlesController`,

directly above a code block containing exactly the method you show.

**Comment by ragavendra** [comment]
true, that's correct, I don't know how I missed it.
