### ISSUE TITLE
Rails 5 polymorphic table requires `optional: true`

### ISSUE THREAD

**Issue by JarLowrey** [rails/rails#29781]
### Steps to reproduce

I wrote a blog post about polymorphic behavior in Rails 5, and noticed that polymorphic tuples cannot be created if `optional: true` is missing - [see blog here](http://jarlowrey.com/blog/polymorphic-rails-5.html#troubleshooting). You can see a working example [here on GitHub](https://github.com/JarLowrey/polymorphic-rails).

### Expected behavior
A new polymorphic tuple should be created fine.

### Actual behavior
Begin transaction, rollback transaction if optional:true is missing. So you're forced to turn this validation off. Error occurs when trying to save in controller#create action, and may have something to do with nested forms IDK.

### System configuration
**Rails version**: 5.1.2

**Ruby version**: 2.4.0

**Comment by JarLowrey** [comment]
I have figured out the issue and confirmed 1 bug and 1 usability problem.

To summarize the blog post/project, there is an Event table and a polymorphic Address/Addressable table. To create an Event there is a nested form that, when submitted, is passed to Event#create. If Address's model does not have `optional: true` on its addressable line, creation will fail and the transaction will rollback due to `{:"address.addressable"=>["must exist"]}`. Manually creating the addressable in create fixes this.

The bug is that automatic addressable creation does not work

  def create
    @event = Event.new(event_params)
    @event.address.addressable = @event #<<<<<<<< ADD THIS IN
    respond_to do |format|
      if @event.save
        format.html { redirect_to @event, notice: 'Event was successfully created.' }
        format.json { render :show, status: :created, location: @event }
      else
        format.html { render :new }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

Usability issue is not yet confirmed, will confirm after I finish making pizza dough.

In my real project, Event is not an integer ID it is a string. In my address migration I am making the address table polymorphic with `t.references :addressable, polymorphic: true, index: true`. According to [Rails docs](http://guides.rubyonrails.org/association_basics.html#polymorphic-associations) is an alias to the following code.

```
t.integer :addressable_id
t.string  :addressable_type
```

This alias is incorrect and causes unpredictable behavior. Address expects an integer ID for addressable/events table, when a string id actually appears. There is no warning or indication that this will cause problems, stuff just breaks everywhere.

**Comment by sgrif** [comment]
This is a known issue with `accepts_nested_attributes`, we have several reports for it already. Thank you.

**Comment by JarLowrey** [comment]
What about string ids when using `references`?

**Comment by sgrif** [comment]
`references` will always assume an integer ID. It cannot query the database to determine the data type you're using for the PK. This could cause the behavior of the migration to vary over time or across machines.

**Comment by JarLowrey** [comment]
@sgrif is there anywhere that I can see progress on this issue?

**Comment by oyeanuj** [comment]
@JarLowrey @sgrif Same question - how can we keep up with the outcome for this issue?

**Comment by jkowens** [comment]
I believe issue #21843 is tracking this problem.
