### ISSUE TITLE
Refactor ActiveRecord's WhereClause to group predicates and binds

### ISSUE THREAD

**Issue by MaxLap** [rails/rails#29804]
I would like to do a pull request to refactor the WhereClause class of ActiveRecord. However, before doing it, I would like to have the approval that this is something that could be interesting.

The refactor would group one predicate and its binds into a sub-struct, something like WherePredicate.

Doing so would solve lots of complexities in the code of WhereClause, as it often needs to interact between predicates and their associated binds, which in the current code, means doing iteration and counting the number of BindParam in the predicates, and keeping track of such a thing. This is also the cause of a few bugs / needed in some solutions: #29780, #29621. And I am working on another pull request which also needs to do this tracking of predicates/binds.

With the refactor, there would be a single array with one struct instance per predicate and zero to many binds. This way, you can easily iterate over the predicates and filter them along with their binds, or any other operations. the attr_reader :binds would be replaced by a simple .flat_map(&:binds)

So, is this something that I can expect to have a positive feedback?

@sgrif Since you introduced WhereClause, maybe you have some input on this proposal?

**Comment by MaxLap** [comment]
Going to go though the core mailing list... I found the wrong one initially which didn't seem to be made for such questions.

**Comment by kaspth** [comment]
@kamipo is good with this stuff too 😊

**Comment by MaxLap** [comment]
Reopening this as I haven't had a single reply in the core mailing list in almost a week and believe this would be a nice improvement to WhereClause.

@kamipo, Any input on this idea?

**Comment by sgrif** [comment]
The issue tracker is reserved for bugs only. Feel free to open a pull request if you have concrete proposals. I'm currently working on rewriting a lot of this code.

**Comment by MaxLap** [comment]
I know the issue tracker is reserved for bugs only. I started with the core mailing list. After one week of no answer, I went with the issue tracker. @kaspth didn't seem to mind and even tagged someone to this issue. But i had closed this issue in favor of the useless core mailing list.

In both places, I explain pretty clearly the goal of the change, pretty much as "concrete proposal" as possible without having coded it or made some actual specs.

By "have a concrete proposal", do you mean "finished writing the code of the PR"? 

Expecting people to just waste hours of their free time to do a refactor, without having any idea this is something that the maintainers would even be interested, in is a good way of making sure those people don't get involved in the project. 

Everytime a PR for a feature/refactor is refused straigth up for reasons such as:
 
* We don't want this kind of feature in the project / I'm strongly against this feature (#21438)
* We have other plan for this code and this refactor would cause trouble (No example, just another idea of a reason to say no)
* @sgrif is already refactoring a good chunk of this code (Kinda said in the previous comment of this issue)
* Adds too little value for the complexity it adds to the code base (#29805)

Without giving any way to the public to discuss those PR ideas before coding them, you are really hurting the people that spent time to contribute. It doesn't mean much statistically, but somehow, I'm really not supprised that after the "I'm strongly against this feature" of #21438, that person never did any other pull request to rails. 

So I ask in simple term, is there a way to actually get some kind of "We don't have upfront reasons to say no to such a thing" for the idea/goal of a PR before spending time coding it? Either with an issue that has a special [PR proposal] or something else?

**Comment by sgrif** [comment]
> By "have a concrete proposal", do you mean "finished writing the code of the PR"?

To a certain extent, yes. Talking about a hypothetical refactoring is incredibly difficult without the actual code available to discuss. 

> Expecting people to just waste hours of their free time to do a refactor, without having any idea this is something that the maintainers would even be interested

The core mailing list is generally the place to ask. If there hasn't been a reply, you should probably treat it the same as a "no". There are 500 open issues and 750 open pull requests at the moment, so a lack of a reply probably means that we don't have the bandwidth to deal with that refactoring right now.

> So I ask in simple term, is there a way to actually get some kind of "We don't have upfront reasons to say no to such a thing" for the idea/goal of a PR before spending time coding it?

It sounds like you have, in multiple places asked that question and gotten an answer. In case it's not clear, the answer is that we're not interested in a PR with this change at this point in time.

**Comment by MaxLap** [comment]
Re-reading my first message and the email (which was a copypaste), I see that I didn't actually ask for what I thought I had asked... 

Basically, I was wondering if anyone had reasons I should not do that refactor, so that I didn't waste time doing the proposal if it was doomed from the start... I didn't want a "yes, do it, this is good", I wanted a "I don't see any reasons this would be refused". This may have made my previous comment sound a little off-context.

Sorry for my confusion.

You gave me the answer when you said you were working on rewriting a lot of this code.

FWIW, maybe you will consider this in your rewrite, my suggestion was to add something like this to WhereClause:

```
BoundPredicate = Struct.new(:predicate, :binds)
```

And then replacing the 2 instance variables `@predicates` and `@binds` by an Array of BoundPredicate. 

This way, iterating over the predicates and theirs associated binds would become really easy and avoids using `grep` to count the number of BindParam.

After that, it's just about changing the tests and the WhereClauseFactory.

**Comment by sgrif** [comment]
The rewrite is already on master, you can see the results for yourself. Feel free to ping me if you have any questions or goals for improvements now that it's done.

**Comment by MaxLap** [comment]
Well I have nothing to add to this. It does what I wanted to do and pushes it further.

That's a spot-on example of why I wanted feedback before doing something for nothing. But i did ask quite poorly.

**Comment by sgrif** [comment]
:) I'm glad it does what you wanted to see. Sorry that I wasn't around to answer your earlier queries (I was on parental leave until last week and am still getting caught up)
