### ISSUE TITLE
ActiveRecord::Relation#send doesn't work when scope name collides with Kernel

### ISSUE THREAD

**Issue by msimonborg** [rails/rails#29832]
### Steps to reproduce

https://gist.github.com/msimonborg/b620cce4d7ea40f89d108d35318b35a5

based on this SO question: https://stackoverflow.com/questions/45152214/send-is-calling-the-wrong-class-because-of-a-scope-with-reserved-word/45152325#45152325

### Expected behavior
Expecting to be able to use `#send` to dynamically call scope methods on `ActiveRecord::Relation` objects with values from a params hash.

e.g.

    class Issue < ActiveRecord::Base
      scope :recent, -> { ...some code... }
      scope :open, -> { where open: true }
      scope :closed, -> { where open: false }
    end

    # Given the following request and params hash...
    get '/issues?status=open'
    params[:status] # => "open"

    # You would expect to be able to do this
    Issue.recent.send(params[:status]) # => #<ActiveRecord::Relation [ ... ]>

### Actual behavior
In most cases this works, but when the scope name collides with a Kernel method name the Kernel method is called instead. I think this is because `#send` bypasses `#method_missing` and goes right up the ancestry chain, and `ActiveRecord::Relation` relies on `#method_missing` to define scope methods. In this case the `#open` method defined on `Kernel` by `OpenURI` is being called and raising an `ArgumentError`

    Issue.recent.send(params[:status])
    ArgumentError: wrong number of arguments (given 0, expected 1+)
    from /Users/matthewborg/.rvm/rubies/ruby-2.4.1/lib/ruby/2.4.0/open-uri.rb:29:in `open'

However, if the scope is called directly, thereby defining it on `Issue::ActiveRecord_Relation` by way of `#method_missing`, then subsequent calls to `#send` will work.

    Issue.recent.open # => #<ActiveRecord::Relation [ ... ]>
    Issue.recent.send(params[:status]) # => #<ActiveRecord::Relation [ ... ]>

### System configuration
**Rails version**: 5.1.2

**Ruby version**: 2.4.1

**Comment by matthewd** [comment]
While I agree this is an unfortunate result of how we make this work, I think it'd be a bit of an over-reach for us to redefine `send`. If you don't intend to call a private method, you should probably be using `public_send`.

**Comment by msimonborg** [comment]
Makes perfect sense, thanks!

**Comment by msimonborg** [comment]
@matthewd if this can be addressed without messing with `send`, would you consider it?

**Comment by matthewd** [comment]
Consider, yes... but for sufficiently-obscure edge cases, the desirability of the framework code becomes a more pressing factor too. (I haven't thought about what a work-around might look like, but just want you to be forewarned that "ah yes I see how that works, but no thanks it's ugly" is a possibility before you dig too far.)
