### ISSUE TITLE
Unable to recognize type of Postgres xact advisory locks

### ISSUE THREAD

**Issue by sreekanthgs** [rails/rails#29837]
### Steps to reproduce

```
[2] pry(main)> ActiveRecord::Base.connection.select_values("Select pg_advisory_xact_lock(1);")
   (1.5ms)  Select pg_advisory_xact_lock(1);
unknown OID 2278: failed to recognize type of 'pg_advisory_xact_lock'. It will be treated as String.
=> [""]
```

### Expected behavior
Warning should not be thrown. It was working fine in previous versions of active record.

### Actual behavior
Warning is issued. Uncertain if the lock is applied, still inspecting.

### System configuration
**Rails version**: 5.1.2
**Ruby version**: 2.4.1

**Comment by sgrif** [comment]
`pg_advisory_xact_lock` has no return value (the type with that OID is `void`). Use `execute` instead.

**Comment by matthewd** [comment]
@sgrif seems like we should probably have a built-in conversion for void to a nil, though?
