### ISSUE TITLE
will there be an official release for ruby 2.3.x for rails 3.2 stable? 

### ISSUE THREAD

**Issue by ritikesh** [rails/rails#29847]
I see that the current rails 3-2 stable [branch](github.com/rails/rails/commits/3-2-stable) has commits relevant to supporting ruby 2.3 for rails 3.2. But there hasn't been an official release after rails [3.2.22.5](https://github.com/rails/rails/commits/v3.2.22.5) for rails 3.2.x. Is there any plans for an official release?

**Comment by kaspth** [comment]
Rails 3.2 is unsupported, so there's not going to be a release. You can point to the 3-2-stable branch at your own peril.
