### ISSUE TITLE
Stray characters may be returned on render as xml

### ISSUE THREAD

**Issue by sneakernets** [rails/rails#29856]
I have created a program that accepts XML streams and saves them to a file, then sends back an XML response. However, the company sending me the XML stream claims extraneous characters are being sent along with the return output. Honestly I don't see this on my end at *all*.

### Steps to reproduce

1. Build any XML file. I personally used Nokogiri to do it. Here's an snippet taken out of context but this should be enough to mentally follow along:
```ruby
message_type = @p_data.xpath("//MessageType").children.to_s
    card_number = @p_data.xpath("//CardNumber").children.to_s
    transaction_id = @p_data.xpath("//TransactionId").children.to_s
    back = Nokogiri::XML::Builder.new do |xml|
      xml.send(:'ContinuousFeedResponse'){
        xml.send(:'MessageType', message_type)
        xml.send(:'Status', 'ACK')
        xml.send(:'Date', Time.now.strftime("%m/%d/%Y"))
        xml.send(:'Time', Time.now.strftime("%H:%M:%S"))
        xml.send(:'CardNumber', card_number)
        xml.send(:'TransactionID', transaction_id)
      }
    end
    render xml: back
``` 

### Expected behavior
```xml

<?xml version="1.0"?>
<ContinuousFeedResponse>
  <MessageType>Transaction</MessageType>
  <Status>ACK</Status>
  <Date>07/19/2017</Date>
  <Time>10:54:47</Time>
  <CardNumber>[REDACTED]</CardNumber>
  <TransactionID>[REDACTED]</TransactionID>
</ContinuousFeedResponse>
```

### Actual behavior

**NOTE:** This is what the sender of the data *claims* they see as a response. Personally I see nothing of the sort when I do my tests.

```text
13b

<?xml version="1.0"?>

<ContinuousFeedResponse>

  <MessageType>Transaction</MessageType>

  <Status>ACK</Status>

  <Date>07/19/2017</Date>

  <Time>16:23:27</Time>

  <CardNumber>[REDACTED]</CardNumber>

  <TransactionID>[REDACTED]</TransactionID>

</ContinuousFeedResponse>

 

0

```

But the "Expected behavior" section is what I see on my tests.

### System configuration
**Rails version**: 5.0.4

**Ruby version**:2.3.4p301

I'm not sure if this is even a bug or not - more of "peace of mind" that I'm not doing something wrong.

**Comment by henrebotha** [comment]
Is it possible for you to check the response yourself?

**Comment by matthewd** [comment]
Please use the mailing list or StackOverflow for questions/help, where a wider community will be able to help you. We reserve the issues tracker for issues only.

**Comment by sneakernets** [comment]
I figured out the issue anyway, it was not on my end, it was another system not using encoding from the 21st century.
