### ISSUE TITLE
Rails::Secrets.encrypt should work even if secrets.yml.key doesn't exist

### ISSUE THREAD

**Issue by michiomochi** [rails/rails#29868]
I don't want to show the production environment token to some developers. (e.g. temporary staff), so there are some developmers who can not access `secrets.yml.key`.

But, `Rails::Secrets.encrypt` is not working without `secrets.yml.key`(or `ENV["RAILS_MASTER_KEY"]`).
https://github.com/rails/rails/blob/master/railties/lib/rails/secrets.rb#L51

So, I'm considering applying the following patch to `Rails::Secrets`.
https://github.com/rails/rails/blob/master/railties/lib/rails/secrets.rb#L38
This patch makes `Rails::Secrets.encrypt` work even without secrets.yml.key in development and test environments. (for temporary staff)
```
module Rails
  class Secrets
    class << self
      def key
        key = ENV["RAILS_MASTER_KEY"] || read_key_file
        return key unless key.nil?

        if Rails.env.development? || Rails.env.test?
          # key must be 32 bytes
          return "duuuuuuuuuuuuuuuuuuuuuuuuuuuuumy"
        end

        handle_missing_key
      end
    end
  end
end
```

Are there any good ideas?

### System configuration
**Rails version**:

5.1.1

**Ruby version**:

2.4.1p111

**Comment by matthewd** [comment]
It doesn't seem very useful, to me, for an "encrypt" method to quietly fallback to a hard-coded "secret". If people don't have the key, ISTM they shouldn't be doing things that call `encrypt`.. and if they are, they should be consciously configuring and using *a* key, even if it's not the same one used in production (and I agree it generally shouldn't be).
