### ISSUE TITLE
What is the purpose of assets/config/manifest.js?

### ISSUE THREAD

**Issue by shivabhusal** [rails/rails#29862]
I see no documentation on `manifest.js` and even doubt if its being used at all. I deleted its content and precompiled assets for production and it works just fine.

```bash
bundle exec rails assets:precompile RAILS_ENV=production
```

**Comment by y-yagi** [comment]
The `manifest.js` is required for Sprockets 4. Please see [sprockets/UPGRADING\.md](https://github.com/rails/sprockets/blob/master/UPGRADING.md#manifestjs)  for details.
