### ISSUE TITLE
ActiveRecord's before_update is called on create

### ISSUE THREAD

**Issue by cristianbica** [rails/rails#29864]
ActiveRecord's before_update is called on create. This happens when the record being create has a belongs_to relationship which declares back a has_one relationship (the common User -> Profile pattern). 

```ruby
class User < ActiveRecord::Base
  belongs_to :profile
  before_update do
    # this shouldn't be called on create
  end
end

class Profile < ActiveRecord::Base
  has_one :user
end

# the following will call the before_update block
User.create!(email: "john@domain.com", profile: Profile.new(name: "John"))
```

This seems to be caused by the `has_one`'s autosave. If the `has_one` has `autosave: false` the block isn't called.

I've briefly looked at the code and what I believe it's happening is:

- `User#save` is triggered
- `User#save` tries to save the `belongs_to` association (`Profile`)
  - `Profile#save` is triggered
  - `Profile#save` saves the `Profile` record
  - `Profile#save` saves the `has_one` associations though creating the `User` record
- `User#save` continues but record is already `persisted` so it will trigger the update callbacks

### Steps to reproduce

https://gist.github.com/cristianbica/b6f00b2ebb51b10986df3ff788e25885

### Expected behavior

`before_update` block shouldn't be called

### Actual behavior

`before_update` block is called

### System configuration

**Rails version**: master

**Ruby version**: ruby 2.4.1p111

**Comment by sgrif** [comment]
I don't think it makes sense to change this behavior. Ultimately we are going to perform three saves. Once to save the user, once to save the profile, and then once to update the user with the profile's primary key. The third one is an update, so we should run those same callbacks. This is no different then if you were manually updating some field of the user in an `after_save` callback on `Profile`.

I could see an argument for us making sure that the profile saves before the user, which means we'd only need to perform 2 saves, but I don't think the behavior of the callbacks are wrong here.

**Comment by yulia-che** [comment]
The problem is that the profile is already getting saved before the user, and it triggers the save of the user, which results in both the foreign and the primary keys set up on the user. So the last save   
> then once to update the user with the profile's primary key.
doesn't really do anything.

**Comment by al2o3cr** [comment]
FWIW, adding `autosave: false` to the `has_one` in `Profile` makes this stop happening.
