### ISSUE TITLE
Hash#slice! remains unchanged if all keys are passed as arguments

### ISSUE THREAD

**Issue by stevenspiel** [rails/rails#29879]
### Steps to reproduce

```rb
hash = { a: :b, c: :d, e: :f }
# => {:a=>:b, :c=>:d, :e=>:f}
hash.slice!(:a, :c, :e)
# => {}
hash
# => {a: :b, c: :d, e: :f}
```

I would expect `slice!` to return `{a: :b, c: :d, e: :f}` and `hash` to be modified to `{}`

Instead, `slice!` returns `{}` and the hash remains unmodified

**Rails version**:
5.0.1
**Ruby version**:
2.3.1

**Comment by dmcclory** [comment]
That's perfectly consistent with [the documented behavior!](http://api.rubyonrails.org/classes/Hash.html#method-i-slice-21)

`slice!` has a different return value than `slice`. I suspect that is really old behavior, so it's probably unlikely to change.

**Comment by stevenspiel** [comment]
The documentation says that `#slice` is destructive. The issue is not what it returns, but that the hash stays the same.

Maybe this is easier to understand:

```rb
# DOES NOT change the hash
hash = { key1: "value1", key2: "value2", key3: "value3" }
hash.slice!(:key1, :key2, :key3)
p hash # => {:key1=>"value1", :key2=>"value2", :key3=>"value3"}

# DOES change the hash
hash = { key1: "value1", key2: "value2", key3: "value3" }
hash.slice!(:key1, :key2)
p hash # => {:key1=>"value1", :key2=>"value2"}
```

**Comment by stevenspiel** [comment]
Ah, I was mistaken. For a moment, I thought that slice removed keys from the hash, but it's the other way around.
