### ISSUE TITLE
Contradictory port information on startup

### ISSUE THREAD

**Issue by brian-kephart** [rails/rails#29880]
In my Rails app with Puma, the console output from the `rails s` command shows an incorrect port when specifying a port other than the default of 3000.

### Steps to reproduce

1) In .env: `PORT=5000`

2) In config/puma.rb (rails app): `port ENV.fetch("PORT") { 5000 }`

3) `rails s`

### Expected behavior

`Rails 5.1.2 application starting in development on http://localhost:5000`
`* Listening on tcp://0.0.0.0:5000`

App is viewable at http://localhost:5000

### Actual behavior

<img width="645" alt="screen shot 2017-07-15 at 3 22 45 pm" src="https://user-images.githubusercontent.com/21235090/28242473-5113a82e-6972-11e7-95eb-882b5e5ffb1e.png">

App is viewable at http://localhost:5000
App is not viewable at http://localhost:3000 (this is correct but contradicts the startup message)

### System configuration

**Ruby version**: 2.4.1
**Rails version**: 5.1.2

**Comment by albertoalmagro** [comment]
Hello @brian-kephart ,

how did you set the environment variable? I have tried to reproduce it creating a new rails app but I am seeing everything as expected with port 5000.

I simply quickly set the environment variable on the console before starting rails with:
`export PORT=5000`

### Console output
```
=> Booting Puma
=> Rails 5.1.2 application starting in development on http://localhost:5000
=> Run `rails server -h` for more startup options
Puma starting in single mode...
* Version 3.9.1 (ruby 2.4.0-p0), codename: Private Caller
* Min threads: 5, max threads: 5
* Environment: development
* Listening on tcp://localhost:5000
Use Ctrl-C to stop
```

### System configuration
**Ruby version:** 2.4.0
**Rails version:** 5.1.2

Thanks,
Alberto

**Comment by brian-kephart** [comment]
@albertoalmagro thanks for looking at this. I set the variable in a .env file in the app root.

**Comment by albertoalmagro** [comment]
@brian-kephart are you using a third party gem like [dotenv](https://github.com/bkeepers/dotenv) for this?

**Comment by brian-kephart** [comment]
No, nothing like that.

Upon further review, it appears to be the setting in config/puma.rb that causes the conflict. Puma and Rails appear to ignore the .env file, so sorry for that bit of misleading information.

So, when specifying the port in config/puma.rb, Puma picks up the setting, but Rails still prints the default port to the console.

**Comment by albertoalmagro** [comment]
Yes, Rails ignores the .env file, for that reason I started thinking about third party gems.

Thanks @brian-kephart !
