### ISSUE TITLE
Strong parameters doesn't permit all nested attributes if key is not numeric

### ISSUE THREAD

**Issue by lfekson** [rails/rails#29888]
### Steps to reproduce
ppp = ActionController::Parameters.new( {"user_infos_attributes"=>{"1500663412001"=>{"address"=>"222", "city"=>"222"}, 'NEW_RECORD' => {"address" => "333", "city" => "333"}}})
aaa = [{:user_infos_attributes => [:address, :city]}]
ppp.permit(aaa)

vs

With removed non-numeric key 'NEW_RECORD':
ppp = ActionController::Parameters.new( {"user_infos_attributes"=>{"1500663412001"=>{"address"=>"222", "city"=>"222"}}})
aaa = [{:user_infos_attributes => [:address, :city]}]
ppp.permit(aaa)

(Guidelines for creating a bug report are [available
here](http://guides.rubyonrails.org/contributing_to_ruby_on_rails.html#creating-a-bug-report))

### Expected behavior
Tell us what should happen
ppp.permit(aaa) should give a correct set:
<ActionController::Parameters {"user_infos_attributes"=><ActionController::Parameters {"1500663412001"=><ActionController::Parameters {"address"=>"222", "city"=>"222"} permitted: true>} permitted: true>} permitted: true>

"Strong parameters" permitting should not think that keys of nested records are always numeric ('NEW_RECORD' or '12332435345'), anyway the keys are not used. Or at least only the record with non-numeric key should be unpermitted, but not all of the passed records.

### Actual behavior
Tell us what happens instead
ppp.permit(aaa) gives
<ActionController::Parameters {"user_infos_attributes"=><ActionController::Parameters {} permitted: true>} permitted: true>

### System configuration
**Rails version**:
Rails 5.0.4.
**Ruby version**:
2.4.1

**Comment by eileencodes** [comment]
Hey @lfekson can you reproduce what you're seeing with our bug report template: https://github.com/rails/rails/blob/master/guides/bug_report_templates/action_controller_master.rb

I suspect the reason strong params is rejecting the keys has to do with the database type. If you're database type is INT then I believe Rails will reject strings for INT columns. This is to protect your app from malicious activity.

**Comment by kirs** [comment]
The bug looks legit to me. I could reproduce it with:

```ruby
require "bundler/setup"
require "active_support/all"
require "rack"
require "rack/test"
require "action_controller/metal/strong_parameters"
require "minitest/autorun"

class BugTest < Minitest::Test
  def test_fails
    input = ActionController::Parameters.new( {"profiles_attributes"=>{'NEW_RECORD' => {"city" => "value"}}})
    result = input.permit(profiles_attributes: [:city])
    expected = {"profiles_attributes"=>{"NEW_RECORD"=>{"city"=>"value"}}}
    assert_equal expected, result.to_h
  end

  def test_passes
    input = ActionController::Parameters.new( {"profiles_attributes"=>{"1500663412001"=>{"city"=>"value"}}})
    result = input.permit(profiles_attributes: [:city])
    expected = {"profiles_attributes"=>{"1500663412001"=>{"city"=>"value"}}}
    assert_equal expected, result.to_h
  end
end
```

I think that the issue comes from [this](https://github.com/rails/rails/blob/master/actionpack/lib/action_controller/metal/strong_parameters.rb#L801) regexp that expects numeric key.

**Comment by lfekson** [comment]
@eileencodes, sorry, didn't understand which field in database you meant. The passed keys that cause failure are never saved or used, they don't have any relation to database, but just a part of previous Rails syntax for nested atributes.

**Comment by eileencodes** [comment]
@lfekson Yup I misread originally - I thought you were talking about the values.

**Comment by lfekson** [comment]
One more problem caused by the same issue: result of any merge of ActionController::Parameters objects will include only that object that doesn't have non-numeric keys.

**Comment by kirs** [comment]
I can still reproduce the issue with the snippet posted above.

It seems like https://github.com/rails/rails/pull/30033 is a possible fix.
