### ISSUE TITLE
links on README in ActiveRecord are not available

### ISSUE THREAD

**Issue by kenta-s** [rails/rails#29890]
### Steps to reproduce

Access this page 
https://github.com/rails/rails/blob/master/activerecord/README.rdoc

and click 'Learn more'

### Expected behavior

I could learn more.

### Actual behavior

redirected to  404.

**Comment by vipulnsward** [comment]
https://github.com/rails/rails/issues/28608#issuecomment-290277451

**Comment by kenta-s** [comment]
I see. The file is not README.md. I misunderstood. Thank you!
