### ISSUE TITLE
Referece to api.rubyonrails.org is broken

### ISSUE THREAD

**Issue by fho-wtag** [rails/rails#29903]
### Steps to reproduce

Visit README of [activerecord](https://github.com/rails/rails/blob/master/activerecord/README.rdoc) and [activemodel](https://github.com/rails/rails/blob/master/activemodel/README.rdoc) then click through the links labeled `Learn more`

### Expected behavior
Links should take to us to a specific section of api.rubyonrails.org like:
 `http://edgeapi.rubyonrails.org/classes/ActiveModel/AttributeMethods.html`

### Actual behavior
Links are taking us to wrong github url like:
 `https://github.com/rails/rails/blob/master/activerecord/classes/ActiveRecord/Base.html`

**Comment by y-yagi** [comment]
Please see https://github.com/rails/rails/issues/28608#issuecomment-290277451

**Comment by fho-wtag** [comment]
@y-yagi Thanks for the note.
