### ISSUE TITLE
attribute_was and attribute_before_last_save have different behavior for first change, but deprecation notices says they are the same

### ISSUE THREAD

**Issue by BenMusch** [rails/rails#29913]
### Steps to reproduce

1. Create an ApplicationRecord instance an initialize an attribute to a non-nil value
2. Save the ApplicationRecord instance
3. Call attribute_was, compare to attribute_before_last_save

Example

```ruby
class Foo < ApplicationRecord
  # some record, assume it has a #bar attribute
end

foo = Foo.create(bar: 'baz')
foo.bar_before_last_save
# => nil
foo.bar_was
# DEPRECATION WARNING: The behavior of `attribute_was` inside of after callbacks will be changing in the next version of Rails. The new return value will reflect the behavior of calling the method after `save` returned (e.g. the opposite of what it returns now). To maintain the current behavior, use `attribute_before_last_save` instead.
# => 'baz'
```

### Expected behavior

Either remove this deprecation notice in that case:

```
DEPRECATION WARNING: The behavior of `attribute_was` inside of after callbacks will be changing in the next version of Rails. The new return value will reflect the behavior of calling the method after `save` returned (e.g. the opposite of what it returns now). To maintain the current behavior, use `attribute_before_last_save` instead.
```

(I understand that there is context in that deprecation notice, but it still floods the logs and is pretty confusing)

Or change the behavior of `before_last_save` to fallback to the current value

### Actual behavior

`before_last_save` and `was` differ in value, but output a deprecation notice saying that they are the same

### System configuration
**Rails version**: 5.1.3.rc1

**Ruby version**: 2.3.1

**Comment by sgrif** [comment]
These methods are only expected to behave the same *inside* of an `after_*` callback, which is what the deprecation warning is focused on. In 5.2 the behavior of `attribute_was` will return `nil` in that case inside of an `after_*` callback as well

**Comment by BenMusch** [comment]
@sgrif is there any way to get the deprecation notices not to show when it's not in the after callback? The logs for my CI builds currently take ~5 minutes to load because there's so many deprecation notices

**Comment by sgrif** [comment]
The deprecation notices should only ever appear inside of an after callback. If they appear outside of an after callback, please open an issue with steps to reproduce and it will be fixed.

**Comment by BenMusch** [comment]
@sgrif Okay -- I'll investigate and build up some context. Thanks!
