### ISSUE TITLE
Autoloading guide should mention `eager_load_paths`

### ISSUE THREAD

**Issue by mikehale** [rails/rails#29920]
The [Autoloading guide](http://guides.rubyonrails.org/autoloading_and_reloading_constants.html). Mentions adding `lib` to `autoload_paths`, but does not mention anything about also adding it to `eager_load_paths`. Without `eager_load_paths` constants may fail to load in production.

**Comment by rafaelfranca** [comment]
We only mention adding `lib` to autoload_paths to explain that we don't do that anymore. We don't recommend adding `lib` to `eager_load_paths` either.

But I agree the guide should talk about `eager_load_paths`.

**Comment by kirs** [comment]
Great idea. I took a stab at it in https://github.com/rails/rails/pull/30106
Any feedback is welcome.

**Comment by kamipo** [comment]
Fixed by #31755.
