### ISSUE TITLE
[ActiveRecord] after_commit callback is not called for nested model update

### ISSUE THREAD

**Issue by ptrln** [rails/rails#29925]
### Steps to reproduce
```ruby
begin
  require "bundler/inline"
rescue LoadError => e
  $stderr.puts "Bundler version 1.10 or later is required. Please update your Bundler"
  raise e
end

gemfile(true) do
  source "https://rubygems.org"
  gem "rails", github: "rails/rails"
  gem "arel", github: "rails/arel"
  gem "sqlite3"
end

require "active_record"
require "minitest/autorun"
require "logger"

# This connection will do for database-independent bug reports.
ActiveRecord::Base.establish_connection(adapter: "sqlite3", database: ":memory:")
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :orders, force: true do |t|
    t.string :arbitrary_column
  end
end

class Order < ActiveRecord::Base
  after_save   :update_arbitrary_column

  after_create :after_create_callback
  after_save   :after_save_callback
  after_commit :after_commit_callback

  def update_arbitrary_column
    Order.find(self.id).update(arbitrary_column: :updated) if self.arbitrary_column.blank?
  end

  def after_create_callback
    p "after_create_callback for #{self.class.name}: #{self.object_id}"
  end

  def after_save_callback
    p "after_save_callback   for #{self.class.name}: #{self.object_id}"
  end

  def after_commit_callback
    p "after_commit_callback for #{self.class.name}: #{self.object_id}"
  end

end

Order.create
```

Here is the output:

```
after_create_callback for Order: 70146722315640
after_save_callback   for Order: 70146715961680
after_save_callback   for Order: 70146722315640
after_commit_callback for Order: 70146722315640
```

### Expected behavior
`after_commit` callbacks should be called on all models that have written to db in the transaction. So, in this case, I expected `after_commit` to also be called for object_id `70146715961680`.

### Actual behavior
The `after_commit` callback is not called on the nested model update.

### System configuration
**Rails version**:
rails 5.2.0.alpha

**Ruby version**:
ruby 2.3.4p301 (2017-03-30 revision 58214) [x86_64-darwin16]

### Notes
I understand that the use case seems odd, but this is causing issues for us in prod.

I would be happy to work on a PR, if you can confirm that this is a bug.

Thank you!

**Comment by meinac** [comment]
since there is only one transaction calling after_commit once looks correct to me and if we change this behaviour this will affect lots of applications.

**Comment by sgrif** [comment]
Looking through the code, the behavior has been "commit callbacks are only run once if two separate models with the same id are touched in the same commit" for as long as commit callbacks have existed. Given that `inverse_of` exists and is used much more broadly now, it probably wouldn't be *as* bad for us to change that today as it would have been 7 years ago. That said, I think that changing this behavior would cause more problems than it would solve.
