### ISSUE TITLE
Postgres Schema adapter ignores limit argument for binary columns

### ISSUE THREAD

**Issue by betesh** [rails/rails#29922]
### Steps to reproduce

```
$ rails new postgres-without-limits
```

Create this migration:

```
class CreateAttachments < ActiveRecord::Migration[5.1]
  def change
    create_table :attachments, id: false do |t|
      t.binary :content, limit: 1.megabyte
    end
  end
end
```

```
$ bin/rake db:setup
$ bin/rake db:migrate
```

### Expected behavior
db/schema.rb should show that the column has a size limit, and the column should actually have that limit.
http://api.rubyonrails.org/v5.1.2/classes/ActiveRecord/ConnectionAdapters/SchemaStatements.html#method-i-add_column states: `:limit - Requests a maximum column length. This is the number of characters for a :string column and number of bytes for :text, :binary and :integer columns`, so it should be valid for a binary type.

### Actual behavior
The limit argument is not passed along to the CREATE command.  It does not show up in the db/schema.rb file, and I can create records with more than 1 MB in the column.

### System configuration
**Rails version**: 5.1.2

**Ruby version**: 2.4.0

**Comment by rafaelfranca** [comment]
PostgreSQL doesn't support limit for binary columns

**Comment by betesh** [comment]
Can we update the docs to not be confusing then?

**Comment by sgrif** [comment]
The docs do explicitly say "This is the number of bytes for binary columns". We should probably just not list the types affected by it explicitly, or at least mention "this field is ignored by some backends" since I don't think there is any type we support for which postgres will actually apply a limit.
