### ISSUE TITLE
[5.0.5rc1/5.1.3rc1] `bin/rails test` does not recognize abolute path

### ISSUE THREAD

**Issue by Edouard-chin** [rails/rails#29923]
Passing an absolute path to `bin/rails test` used to work fine (tests only in the given file were running) before the minitest plugin was introduced. 

Passing an absolute path now runs the entire test suite.

@kaspth Just wanted to let you know as I was told there will be a final release today.
Will dig a bit on the issue and will let you know. Thanks <3

**Comment by kaspth** [comment]
Thanks for the issue, reproduction and fix! Applied at 5948871e82.
