### ISSUE TITLE
cant run built in web server after fresh installing on ubuntu

### ISSUE THREAD

**Issue by jougene** [rails/rails#29943]
I had to install nodejs to run `bin/rails server`. Suggest to add description about installing nodejs to getting started guide after part `To install Rails, use the gem install command provided by RubyGems`

### Steps to reproduce

(Guidelines for creating a bug report are [available
here](http://guides.rubyonrails.org/contributing_to_ruby_on_rails.html#creating-a-bug-report))
install rails by getting started guide
`gem install rails`

### Expected behavior
after installing rails and running `bin/rails server` in project folder, server started.

### Actual behavior
```var/lib/gems/2.3.0/gems/bundler-1.15.3/lib/bundler/runtime.rb:85:in `rescue in block (2 levels) in require': There was an error while trying to load the gem 'uglifier'. (Bundler::GemRequireError)
Gem Load Error is: Could not find a JavaScript runtime. See https://github.com/rails/execjs for a list of available runtimes.```

### System configuration
**Rails version**: 5.1.2

**Ruby version**: 2.3.1

**Comment by pixeltrix** [comment]
Definitely should add an entry to the list in [Guide Assumptions][1] in the "Getting Started with Rails" guide.

[1]: http://guides.rubyonrails.org/getting_started.html#guide-assumptions

**Comment by rafaelfranca** [comment]
You don't need the nodejs, what you needed is a javascript runtime and there is one already in the gemfile commented.
