### ISSUE TITLE
form_for generates wrong URL for polymorphically-associated namespaced nested resources

### ISSUE THREAD

**Issue by darmenise** [rails/rails#29956]
### Steps to reproduce
`Admin::Comment` is associated to `Admin::Account` by a polymorphic association.

```ruby
# routes.rb
  namespace :admin do
    resources :accounts do
      resources :comments, only:  [ :create ]
    end
end
```
Which correctly generates this route:
 ```
admin_account_comments POST /admin/accounts/:account_id/comments(.:format) admin/comments#create
``` 
to POST a new comment for an account.

### Expected behavior
`<%= form_for [@commentable, @commentable.comments.new] do |f| %>` where `@commentable`, is an instance of  `Admin::Account`, should POST to `admin_account_comments_path`.

### Actual behavior
`<%= form_for [@commentable, @commentable.comments.new] do |f| %>` tries to POST to `admin_account_admin_comments_path`, which is the wrong URL generated by `polymorphic_url`, so a `NoMethodError` exception is raised.

### System configuration
**Rails version**: 5.1
**Ruby version**: 2.4.1

### Temporary fix / workaround
[Alessandro](https://github.com/coorasse) suggested this possible fix:

```ruby
<%= form_for [@commentable, @commentable.comments.new], url: "#{polymorphic_path(commentable)}/comments" do |f| %>
```
Other possible fixes are suggested in issue #10705, which was closed because "polymorphic_url heuristic is very simple, it simply gets the model names, put them together and attempt to generate a URL" but said attempt still fails when the resources are nested inside a namespace.

**Comment by pixeltrix** [comment]
One solution is to add `use_relative_model_naming?` singleton method to your `Admin` module and then add `:admin` to your polymorphic url array, e.g:

``` ruby
# app/models/admin.rb
module Admin
  def self.use_relative_model_naming?
    true
  end
end
```

```
>> app.polymorphic_url([:admin, @commentable, @commentable.comments.new])
=> "/admin/accounts/1/comments"
```

Anything more than this would require a lot more coupling between models and routing which is something we don't want to do as it's often not a direct mapping.

**Comment by darmenise** [comment]
Fair enough, thank you!
