### ISSUE TITLE
Support for multiple foreign keys in ActiveRecord::Associations?

### ISSUE THREAD

**Issue by rlue** [rails/rails#29969]
## Problem

Suppose you have a `User` model with a HABTM self-join relationship, maintained through a separate join table:

#### The `User` model

```
class User < ApplicationRecord
  has_many :followers, through: :supply_links
  has_many :followeds, through: :supply_links
  ...
end
```

#### The join model

```
class Following < ApplicationRecord
  belongs_to :followers, class_name: 'User'
  belongs_to :followeds, class_name: 'User'
  ...
end
```

As I currently understand it, if you want to add a has-many association on the `User` model for the join model itself, you have to create two separate associations:

```
# app/model/user.rb
class User < ApplicationRecord
  ...
  has_many :follower_connections, class_name: :followings, foreign_key: :follower_id
  has_many :followed_connections, class_name: :followings, foreign_key: :followed_id
  ...
end
```

Then, in order to get **all** join table records referencing a given user, you'd have to concatenate calls to each of these associations:

```
alice.follower_connections + alice.followed_connections
```

when really, all I want is to call:

```
alice.followings
```

## Proposal

What would the Rails team think about supporting the following syntax?

```
has_many :followings, foreign_keys: [:follower_id, :followed_id]
```

I'd be willing to take a stab at a PR, but I'd like to understand if there's a reason it doesn't work this way first. I've done a bit of digging on SO, and at least [a](https://stackoverflow.com/questions/39184047/rails-self-join-with-has-many-through-relationship) [few](https://stackoverflow.com/questions/6387355/rails-self-referential-has-many-through-i-cant-figure-out-what-im-doing-wro) [people](https://stackoverflow.com/questions/24642005/rails-association-with-multiple-foreign-keys) have been looking for something like this since 2011.

**Comment by invidian** [comment]
I'm also currently looking for a solution for this. Another example would be: `Team` has many `games`, `game` has `host` and `guest` fields, which are both `Team` type. For my specific case, it would be nice if this could work with polymorphic association as well, so:
```
has_many :host_games, class_name: 'Foo', as: :host,
has_many :guest_games, class_name: 'Foo', as :guest
has_many :games, class_name: 'Foo', as: [:host, :guest]
```

What I currently do for to workaround it is:
```
  def games
    Games.where("host_id = ? AND host_type = ?", self.id, 'Foo').or(Games.where("guest_id = ? AND guest_type = ?", self.id, 'Foo'))
  end
```
however this solution does not allow for example eager loading, which is bad.

**Comment by sgrif** [comment]
I don't think this is a common enough use case to warrant special APIs for it, especially now that `Relation#or` exists and makes it fairly easy to implement in your application. If anything, I'd expect passing an array to `foreign_key` like that to deal when you have a composite foreign key referencing a composite primary key. I'd like to reserve it for that usage in Rails.

**Comment by rlue** [comment]
> If anything, I'd expect passing an array to foreign_key like that to deal when you have a composite foreign key referencing a composite primary key. I'd like to reserve it for that usage in Rails.

That makes much more sense, actually.

Is anyone working on this? Would the team be open to a contribution here?

**Comment by olivierlacan** [comment]
@rlue This seems like it would be a natural extension of the support for composite primary keys in ActiveRecord. Are you still interested in working on this?

**Comment by rlue** [comment]
Okay, so it's been a while, but I'm definitely still interested in working on this. Just to gather a little bit of information before I start diving in, though:

AFAIK Rails still does not natively support primary keys—is that correct? and if so, are there currently plans to implement composite primary key support in Rails? (and @olivierlacan, does your question mean you/the Rails team would be open to reviewing a PR for this?) 

The `composite_primary_keys` gem appears to be the most popular solution for adding CPK support to AR. Does the team have an opinion on the way @cfis has done it in the CPK gem?

**Comment by SeanJManning** [comment]
`class User < ApplicationRecord
  has_many :tasks, ->(user) { unscope(:where).where("owner_id = :id OR assignee_id = :id", id: user.id) }
end`

https://stackoverflow.com/a/41978449

**Comment by james-caresnap** [comment]
The solutions outlined here seem to work ok for a `has_many` relation, but they don't work for `belongs_to`. The docs indicate you can pass a scope to `belongs_to`, and you _can_, but it gets completely ignored. The scope is never called because `SingularAssociation` [overrides](https://github.com/rails/rails/blob/main/activerecord/lib/active_record/associations/singular_association.rb#L40) `Association`'s `find_target` method and `scope` is never called.

**Comment by ghiculescu** [comment]
@james-caresnap that sounds like a bug. Could you please create an issue with [replication steps](https://edgeguides.rubyonrails.org/contributing_to_ruby_on_rails.html#create-an-executable-test-case) ?

**Comment by sergioisidoro** [comment]
I was struggling with a similar problem (multiple keys), but with opposite results.

My goal was to have:
```
    belongs_to :foreign_object, primary_keys: ["x", "y"], foreign_keys: ["a", "b"]
```
resulting into the query 
```
WHERE "foreign_objects"."x" == "owner_objects"."a" AND "foreign_objects"."y" ==  "owner_objects"."b" 
```

Right now it already resolves the list of foreign keys into a list, I wonder if we could just resolve them into multiple WHERE AND clauses in the reflection scope.  
```
ActiveRecord::StatementInvalid (PG::UndefinedColumn: ERROR:  column foreign_objects.["field_a", "field_b"] does not exist)
LINE 1: SELECT "foreign_objects".* FROM "foreign_objects" WHERE "foreign_objects"."[""field_a""...
```

So I guess I would expect and AND behaviour when multiple keys are provided instead of an OR.

**Comment by simi** [comment]
:thinking: There is this well maintained gem for composite primary keys support - https://github.com/composite-primary-keys/composite_primary_keys.

**Comment by sergioisidoro** [comment]
@simi at least my issue is that I don't want them to be _primary_, I want them just to be keys, while keeping id as a primary key.
