### ISSUE TITLE
Console autocompletion

### ISSUE THREAD

**Issue by pacMakaveli** [rails/rails#29968]
##### Rails 5
`$ rails c`
``` ruby
a = 'foo'
b = 'bar'
c = 'daz'
```
`a = [UP ARROW]` should come up with `a = 'foo'`, instead it comes up with `c = 'daz'`

##### Rails 4
`$ rails c`
``` ruby
a = 'foo'
b = 'bar'
c = 'daz'
```
`a = [UP ARROW]` comes up with `a = 'foo'`

### System configuration
**Rails version**:

Rails 4.2.3
Rails 5.1.2

**Ruby version**:
```
$ ruby -v
ruby 2.3.1p112 (2016-04-26 revision 54768) [x86_64-darwin15]
```

Apologies if it's not related, but I'm opening this issue here because it works as expected in Rails 4. Behavior changed in Rails 5 for some reason.

**Comment by lugray** [comment]
I cannot reproduce the desired behaviour, even in Rails 4.2.3 using `tools/console` in rails or `rails c` in a new Rails 4.2.3 app.  This looks like a feature request to me.  Maybe it comes from a gem you added to your Rails 4.2.3 app?

**Comment by rafaelfranca** [comment]
The Rails console is just a IRB console. We don't do anything special on it.

**Comment by pacMakaveli** [comment]
@lugray it seems you're right. Managed to trace it to `rb-readline` gem. Weird, it worked fine with Rails 4.

@rafaelfranca Sorry about this! I thought it was something in Rails that changed. My bad 👍
