### ISSUE TITLE
A model named Mls has no corresponding fixture

### ISSUE THREAD

**Issue by wuliwong** [rails/rails#29973]
Create a model `Mls < ApplicationRecord` in `app/models/mls.rb`.

Run `Mls.name.pluralize` and you receive `"Mls"` as the response.

Create a corresponding fixture in `test/fixtures/mls.yml`.

Run `rails test` and receive the error

`ActiveRecord::NotNullViolation: PG::NotNullViolation: ERROR:  null value in column "created_at" violates not-null constraint`

A previous issue explains the problem is actually that the model file is not being located (https://github.com/rails/rails/issues/23316).

What is happening is that the fixture is looking for `app/models/ml.rb`. 

I'm sure these pluralization problems come up a lot. Maybe this is a case that can't be fixed. "MLS" is an acronym which stands for "Multiple Listing Service". Is it against convention to use acronyms for model names?

### System configuration
**Rails version**: 5.1.2

**Ruby version**: 2.4.0p0

**Comment by sgrif** [comment]
Thanks for the report, but we don't make changes to the inflector anymore. It will never handle every edge case, and changes to it can break people's apps. You can fix this in your own app in `config/initializers/inflections.rb`, there are examples there on how to use it.

**Comment by wuliwong** [comment]
Ok, cool. Thanks

**Comment by ddfznt** [comment]
@wuliwong  by convention i add 
```
inflect.acronym 'MLS'
inflect.uncountable %w(mls)
```
 into `config/initializers/inflections.rb`

and uses upcase class name 

```
class MLS < ApplicationRecord
...
end
```

**Comment by moveson** [comment]
I'm having similar problems, and adding the model name to `config/initializers/inflections.rb` does not help. I have a model named EventSeries, which is the same singular as it is plural. I have added this in every way I can imagine to the inflector:

    inflect.uncountable %w( fish sheep EventSeries event_series Series series )

I have an `event_series.yml` fixtures file within `spec/fixtures`. I have even tried adding:

```
_fixture:
  model_class: EventSeries
```
at the top of the file, but it does not help. 

In a system spec, I have the following declaration:
```
let(:subject_series) { event_series[:d30_short_series] }
```
When I run the spec, I get this error:
```
NameError: undefined local variable or method `event_series'
```
I have many other models and this pattern works for every other model, so I assume this is a pluralization issue.
