### ISSUE TITLE
AngularJS attach files, send to Rails server

### ISSUE THREAD

**Issue by AceInfoSolutions** [rails/rails#29972]
Hi,

I'm trying to use AngularJS on the front-end to upload the model and file data to Rails server. Below is the AngularJS http configuration.
```
        var settings = {
                method: 'POST',
                url: baseUrl + "/create_request?username="+username,
                // data: request,
                headers: {
                    'Content-Type': undefined
                },
                data: {
                    request: request,
                    files: files
                },
                transformRequest: function (data) {
                    var formData = new FormData();
                    formData.append("request", angular.toJson(data.request));
                    formData.append("file", data.files);
                    return formData;
                }
        };
```
Then I print the request data on the server side. Is there a way to retrive the [object file] from request?

Started POST "/create_request?username=abc" for 127.0.0.1 at 2017-07-27 10:31:37 -0400
Processing by RequestController#create_request as HTML
  Parameters: {"request"=>"{\"pria_related\":true,\"also_include\":[{\"primary_email\":\"abc@abc.com\"},{\"primary_email\":\"abc@abc.com\"},{\"primary_email\":\"abc@abc.com\"}],\"applications\":[{\"scr_application_id\":8},{\"scr_application_id\":7},{\"scr_application_id\":6}],\"division\":[{\"relationship_id\":1},{\"relationship_id\":2},{\"relationship_id\":3}],\"title\":\"afsdf\",\"description\":\"asfsdf\",\"point_of_contact\":\"abc@abc.com\",\"answer_id\":3}", _**"file"=>"[object File],[object File],[object File]"**_, "username"=>"abc"}
Completed 400 Bad Request in 0ms (Views: 0.1ms | ActiveRecord: 0.0ms)

**Comment by pacMakaveli** [comment]
The file shouldn't come as an Object in the first place. I don't know what your view looks like, but make sure you have `multipart: true` in your form in order to receive the file as a `ActionDispatch::Http::UploadedFile` Object. From there on you should be able to query your File.

**Comment by robin850** [comment]
Hi @AceInfoSolutions,

Sorry but this tracker is only for issues. If you have questions, you should rather post on StackOverflow or the [rails-talk mailing list](https://groups.google.com/forum/#!forum/rubyonrails-talk).
