### ISSUE TITLE
bundle exec rails new ~/my-test-app --dev failed on window host

### ISSUE THREAD

**Issue by wizdata** [rails/rails#29987]
### Steps to reproduce
use https://github.com/rails/rails-dev-box.git

bundle exec rails new ~/my-test-app --dev failed

### Expected behavior
source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }
gem 'rails', path: "/vagrant/rails"

### Actual behavior
source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }
gem 'rails'
, path: "/vagrant/rails"

### System configuration
Devbox

**Comment by Rubemlrm** [comment]
wich error you got from this process ? I mean , the bundle throw any kind of error when you started the process of creating a new rails application ?

**Comment by wizdata** [comment]
[!] There was an error parsing `Gemfile`: syntax error, unexpected ',', expecting end-of-input - , path: "/vagrant/rails"
 ^. Bundler cannot continue.

 #  from /home/ubuntu/my-test-app/Gemfile:8
 #  -------------------------------------------
 #
 >  , path: "/vagrant/rails"
 #
 #  -------------------------------------------

**Comment by wizdata** [comment]
gem 'rails'
, path: "/vagrant/rails" should be in the same line

**Comment by lugray** [comment]
This is not an issue with rails, but rather with your line endings.  The template for the Gemfile is found at `railties/lib/rails/generators/rails/app/templates/Gemfile`, and when I convert line endings from `\n` (as checked in to the repo) to `\r\n`, I get the same behaviour.  This is because the erb template uses `<% code -%>`, where the `-` indicates removing a following newline.  This doesn't work properly with windows style (`\r\n`) line endings.

**Comment by wizdata** [comment]
So -%> processing needs to consider if win or nix is


Sent from my iPhone

On Aug 1, 2017, at 8:51 AM, Lisa Ugray <notifications@github.com<mailto:notifications@github.com>> wrote:


This is not an issue with rails, but rather with your line endings. The template for the Gemfile is found at railties/lib/rails/generators/rails/app/templates/Gemfile, and when I convert line endings from \n (as checked in to the repo) to \r\n, I get the same behaviour. This is because the erb template uses <% code -%>, where the - indicates removing a following newline. This doesn't work properly with windows style (\r\n) line endings.

**Comment by robin850** [comment]
It looks like this is not a Rails issue but rather an ERB one. [This ticket](https://bugs.ruby-lang.org/issues/11464) should fix this issue so it should not be a problem on the next 2.4 patch release.

Thanks for reporting anyway and thanks for investigating this @lugray !
