### ISSUE TITLE
Asset pipeline precompiles coffeescript when passed "*.js"

### ISSUE THREAD

**Issue by amingilani** [rails/rails#29993]
### Steps to reproduce

1. Create a react webpacker app
2. Create a new controller and web page
3. Append `Rails.application.config.assets.precompile += %w( *.js *.css )` to `assets.rb`
4. Visit the page

Or just:
1. clone my [demo app](https://github.com/amingilani/no_coffee)
2. run `rails s`
3. visit `localhost:3000/hello/hello`

### Expected behavior

The page should load.

### Actual behavior

You get an error:

``
LoadError in HelloController#hello
cannot load such file -- coffee_script
``

<img width="1022" alt="screen shot 2017-07-30 at 1 39 05 am" src="https://user-images.githubusercontent.com/1188552/28748097-e61705b4-74c7-11e7-82c3-ba3eeee0a6ae.png">

### Futher investigation

But we explicitly required `*.js` and not `*.coffee`, let's list all the coffee files anyways:

```
$ find . -name "*.coffee"
./node_modules/coa/src/arg.coffee
./node_modules/coa/src/cmd.coffee
./node_modules/coa/src/color.coffee
./node_modules/coa/src/completion.coffee
./node_modules/coa/src/index.coffee
./node_modules/coa/src/opt.coffee
./node_modules/coa/src/shell.coffee
./node_modules/fsevents/node_modules/performance-now/src/performance-now.coffee
./node_modules/fsevents/node_modules/performance-now/test/performance-now.coffee
./node_modules/ipaddr.js/src/ipaddr.coffee
./node_modules/ipaddr.js/test/ipaddr.test.coffee
./node_modules/performance-now/src/performance-now.coffee
./node_modules/performance-now/test/performance-now.coffee
./node_modules/resolve/test/resolver/cup.coffee
./node_modules/resolve/test/resolver/mug.coffee
./node_modules/whet.extend/src/whet.extend.coffee
./node_modules/whet.extend/test/extend_test.coffee
./node_modules/whet.extend/test/test_helper.coffee
```

Maybe it's requiring `./node_modules/ipaddr.js` because it matches the pattern. These are the following files:

```
./node_modules/ipaddr.js/src/ipaddr.coffee
./node_modules/ipaddr.js/test/ipaddr.test.coffee
````

Let's delete this entire directory:

```
$ rm -rf node_modules/ipaddr.js
$ find . -name "*.coffee"
./node_modules/coa/src/arg.coffee
./node_modules/coa/src/cmd.coffee
./node_modules/coa/src/color.coffee
./node_modules/coa/src/completion.coffee
./node_modules/coa/src/index.coffee
./node_modules/coa/src/opt.coffee
./node_modules/coa/src/shell.coffee
./node_modules/fsevents/node_modules/performance-now/src/performance-now.coffee
./node_modules/fsevents/node_modules/performance-now/test/performance-now.coffee
./node_modules/performance-now/src/performance-now.coffee
./node_modules/performance-now/test/performance-now.coffee
./node_modules/resolve/test/resolver/cup.coffee
./node_modules/resolve/test/resolver/mug.coffee
./node_modules/whet.extend/src/whet.extend.coffee
./node_modules/whet.extend/test/extend_test.coffee
./node_modules/whet.extend/test/test_helper.coffee
```

It's gone.. testing now by visiting the page

```
LoadError in HelloController#hello
cannot load such file -- coffee_script
```

**Rats, the problem's still there.** Are we sure it's a `node_modules` issue? Let's nuke all the files in there.

```
$ rm -rf node_modules
$ node_modules
```

And visiting the page works!

```
Hello#hello

Find me in app/views/hello/hello.html.erb
```

### The Real Question

While I get that webpacker includes too many files and we have no control over them. The more important question is: why is the assets pipeline including "*.coffee" files when all we want is "*.js"

### System configuration

```
$ rails -v
Rails 5.1.2
$ ruby -v
ruby 2.4.0p0 (2016-12-24 revision 57164) [x86_64-darwin16]
```

**Comment by amingilani** [comment]
Also, since other developers will be Googling this, here's the full error message:

```
This error occurred while loading the following files:
   sprockets/autoload/coffee_script
   coffee_script
```

[This](https://github.com/spree/spree/issues/7578#issuecomment-314182642) dev recommended getting rid of the `node_modules` from the pipeline, that isn't a good idea, though.

**Comment by rolsdorph** [comment]
Weird - I'm unable to reproduce this. Same Ruby version, same Rails version, cloned your demo repository, and localhost:3000/hello/hello loaded fine.

**Comment by amingilani** [comment]
@rolsdorph did you run `yarn` before? You've got to populate the `node_modules` folder first.

**Comment by schneems** [comment]
I think that that telling sprockets *.js translates to telling it to compile anything that will end up eventually being a `.js` file which includes css?

**Comment by rafaelfranca** [comment]
The .js is the target, not the the origin. A coffee file will end up being a js file. Same goes with any transformation that the target is js.

My recommendation: never do `*.js` or `*.css`. `Rails.application.config.assets.precompile` is not even recommended to be used anymore. Be explicit the files that are going to be compiled using the `app/assets/config/manifest.js` file.

**Comment by amingilani** [comment]
@rafaelfranca could you elaborate for the five year olds among us? Maybe link to some docs since this now shows up for everyone Googling the problem.

**Comment by schneems** [comment]
I was going to link you to docs, but it looks like we don't have them https://github.com/rails/sprockets/blob/master/guides/end_user_asset_generation.md#manifest-file

:x 

The short version is you need to use Sprockets 4 and then add a file like this in app/assets/config/manifest.js https://github.com/codetriage/codetriage/blob/master/app/assets/config/manifest.js

This file is now how you tell Sprockets what files to generate instead of a "precompile" list. Anything you `link` will be generated as an asset in production. 

You might also want to link_tree your images as well.

**Comment by rafaelfranca** [comment]
You don't need sprockets 4, sprockets 3 supports the manifest and every new Rails application already come with it.

See https://github.com/rails/rails/blob/3fc47f4d82175c3f32dab6177685ae24f485c7b1/activestorage/test/dummy/app/assets/config/manifest.js.

That file uses a declarative way different from the precompile list. Instead of doing `*.js` you can do `//= link_directory ../javascripts .js` (that also compiles *.coffee because you are asking for anything that compiles to .js), but that will not compile anything inside node_modules.
