### ISSUE TITLE
Isolated AR connections on a per authentication base?

### ISSUE THREAD

**Issue by jordanlance** [rails/rails#29990]
Is it possible to have Isolated AR connections on a per authentication base?

**The problem**
Using connection_establish to switch the database in a rails application, after we have authenticated with devise in this case. Devise Organisation  role connects to organisation_development, Devise  Teacher role connects to teacher_development.
But establish_connection switches the database globally for _every_ devise authenticated user that is logged-in. 
This causes issues when logging in at the same time with 2 different user roles, the database would switch and we would loose the Devise session data so the authentication breaks.

After many hours/days of hunting down the code and solutions Im rather stuck with this and believe there is no real solution for AR to resolve this issue.

*The solution?* 
If there is a solution could someone please tell me how to have isolated database connections from a single running rails applications. If its not possible at all would it be possible to implement a database connection isolated. thus making establish_connection more smart so It knows it should connect to the database but only for a certain authentication, in our case Devise. Or is this out of scope for AR. 
It seems a bit odd that rails does not support multiple databases ( multitennant ) out of the box. I know the gems that facillitate this functionality but im already implemented a great custom solution it only does not work with this database connection problems which I hope can be resolved somehow.

**Comment by matthewd** [comment]
Please use the mailing list or StackOverflow for questions/help, where a wider community will be able to help you. We reserve the issues tracker for issues only.
