### ISSUE TITLE
routes.default_url_options should be read from config.action_controller.default_url_options if it is specified

### ISSUE THREAD

**Issue by hron84** [rails/rails#29992]
I'm currently facing a situation where I need to use URL helpers from an ActiveJob (I generating picture from an in-app page) and it does not read the `default_url_options` from `config.action_controller.default_url_options` even if it is specified to the active Rails.env. However, at the Job, I cannot and would not detect and define which host and port should be used because I think this is not what an ActiveJob should do. The URL helpers should be smart enough to do this. I accept it could not be dynamic, as ActiveJob is not running in a webserver context, but I expect it should fall back to the defaults I already specified.

```
Rails version             5.1.0
Ruby version              2.4.1-p111 (x86_64-linux)
RubyGems version          2.6.11
Rack version              2.0.3
JavaScript Runtime        Node.js (V8)
```

**Comment by pixeltrix** [comment]
If this is the behaviour you want it's trivially easy to configure - either in `ApplicationJob` or a specific job class:

``` ruby
class ApplicationJob < ActiveJob::Base
  include Rails.application.routes.url_helpers

  class << self
    def default_url_options
      Rails.application.config.action_controller.default_url_options
    end
  end
end
```

Routes aren't included by default into job classes so it's up to the developer to configure what they need - when the module is included we'll add a class attribute if there's no existing `default_url_options` method. Where we do include them by default we have config options - one for Action Mailer and one for Action Controller. I can't see a strong reason why Active Job should use the Action Controller config over the Action Mailer one - if anything the latter is probably the stronger case as it's recommended that emails are sent from background jobs.

**Comment by hron84** [comment]
@pixeltrix so ActiveJob uses ActionMAiler url options by default?

**Comment by pixeltrix** [comment]
@hron84 no, it doesn't because it doesn't include routes - what I'm saying is that if we were to use one then it's more likely that Action Mailer would be the one chosen. Our preferred position is the status quo - that we leave it up to the developer.

**Comment by lulalala** [comment]
I did some testing: https://stackoverflow.com/a/48781000/474597

I think if you do this then it should work for console and jobs:

```
# in development.rb, outside config block
Rails.application.routes.default_url_options[:protocol] = 'https'
# Does not work on web, but works under console
```

I think having so many setters in different places is a sign for refactoring, especially when some setters do not have any effects.

**Comment by apotonick** [comment]
Quick question: why is this closed? Wouldn't this create a much more expected interface if the setter mentioned in the title would work?

**Comment by tdeck** [comment]
I've got to say, having just encountered this it's extremely confusing. I find examples all over the web that describe setting default URL options in all different places:

```
    Rails.application.config.action_mailer.default_url_options
    Rails.application.routes.default_url_options
    MyApp::Application.default_url_options
    config.action_controller.default_url_options
    ApplicationController#default_url_options method
```

There appears to be no documentation describing which of these inherits from which others, which (if any) are deprecated, and which environments they work in. This isn't the kind of thing I would expect to have already spent half an hour on.

**Comment by jasonfb** [comment]
for Rails 6.02
```
Rails.application.config.action_mailer[:default_url_options]
```
and
```
Rails.application.config.action_mailer[:default_url_options][:host]
```

**Comment by jbranchaud** [comment]
I did a bit of research into this lately (for a Rails 6.1 app) and this is what I came up with for setting application-wide `default_url_options` in _development_.

```ruby
# config/environments/development.rb
Rails.application.default_url_options = { host: 'localhost', port: 3000 }

Rails.application.configure do
 # ...
end
```

https://github.com/jbranchaud/til/blob/master/rails/set-default-url-options-for-entire-application.md

**Comment by pierrea** [comment]
@jbranchaud Great, thanks
And I guess we can do this from the configure block to avoid repeating ourselves:

```ruby
config.action_mailer.default_url_options = Rails.application.default_url_options
```

**Comment by mockdeep** [comment]
@pierrea as far as I can tell, you shouldn't need to set it for `action_mailer` if you set if for `Rails.application`. It looks like the `Rails.application` setting is global.

**Comment by acushlakoncept** [comment]
> 

For some reason, this is the only thing that worked for me 🤔

**Comment by ConfusedVorlon** [comment]
> @jbranchaud Great, thanks And I guess we can do this from the configure block to avoid repeating ourselves:
> 
> ```ruby
> config.action_mailer.default_url_options = Rails.application.default_url_options
> ```

watch out for this one - it bit me hard.
that uses the same object, so if code elsewhere changes a value in `config.action_mailer.default_url_options`, then it will also change `Rails.application.default_url_options`

I use 

```
  # Set to include the correct URLs from Turbo, etc
  Rails.application.default_url_options = {host: "localhost", port: ENV.fetch("PORT", 3000).to_i}
  # sets values for partial rendering
  # Note use of dup so that we don't end up with the same object that can then be changed elswhere. (Mail.rb)
  config.action_controller.default_url_options = Rails.application.default_url_options.dup
  config.action_mailer.default_url_options = Rails.application.default_url_options.dup
```

**Comment by webzorg** [comment]
> > [@jbranchaud](https://github.com/jbranchaud) Great, thanks And I guess we can do this from the configure block to avoid repeating ourselves:
> > config.action_mailer.default_url_options = Rails.application.default_url_options
> 
> watch out for this one - it bit me hard. that uses the same object, so if code elsewhere changes a value in `config.action_mailer.default_url_options`, then it will also change `Rails.application.default_url_options`
> 
> I use
> 
> ```
>   # Set to include the correct URLs from Turbo, etc
>   Rails.application.default_url_options = {host: "localhost", port: ENV.fetch("PORT", 3000).to_i}
>   # sets values for partial rendering
>   # Note use of dup so that we don't end up with the same object that can then be changed elswhere. (Mail.rb)
>   config.action_controller.default_url_options = Rails.application.default_url_options.dup
>   config.action_mailer.default_url_options = Rails.application.default_url_options.dup
> ```
```
Rails.application.default_url_options = { host: "localhost", port: 3000 }
config.action_mailer.default_url_options = default_url_options
```
also works
