### ISSUE TITLE
Set Ruby version in Gemfile and .ruby-version by default

### ISSUE THREAD

**Issue by dhh** [rails/rails#30007]
When you generate a new Rails skeleton, we should be using the Ruby version you're generating with as the baseline for the application. So that version should be set in the Gemfile and .ruby-version.

**Comment by sgrif** [comment]
We should probably verify that the version is >= our minimum supported version (using a version older than 2.2 might not result in an error in this case)

**Comment by dhh** [comment]
Pretty sure we block older versions of Ruby from running the rails template
command?

**Comment by redtachyons** [comment]
@sgrif Will that version check (>=) work properly in non MRI ruby versions ?

**Comment by sgrif** [comment]
Ah you're right, it'd get caught by https://github.com/rails/rails/blob/310918f6a194bf5752fe1025930881756f5d8a8e/railties/lib/rails/ruby_version_check.rb.

**Comment by albertoalmagro** [comment]
I already implemented it, I am going to create the PR.

**Comment by albertoalmagro** [comment]
Created PR https://github.com/rails/rails/pull/30016

**Comment by guilleiguaran** [comment]
Closing this since the PR is ready: #30016
