### ISSUE TITLE
No info about exact line of error in backtrace if something is wrong in view partial

### ISSUE THREAD

**Issue by rubydev** [rails/rails#30008]
In view:

<pre> app/views/client/hotels/index.html.erb</pre>

on line 37 I have partial:

<pre><%= render 'hotel_detail', hotel: hotel %></pre>

and I have something wrong in model, but in backtrace is info, that problem is on line 37 in partial 'hotel_detail'. No more info where exactly in partial is problem. See my backtrace:

<pre>
ActionView::Template::Error - undefined method `[]' for nil:NilClass:
  actionview (5.1.2) lib/action_view/template/error.rb:67:in `initialize'
  actionview (5.1.2) lib/action_view/template.rb:321:in `handle_render_error'
  actionview (5.1.2) lib/action_view/template.rb:160:in `rescue in render'
  actionview (5.1.2) lib/action_view/template.rb:155:in `render'
  actionview (5.1.2) lib/action_view/renderer/partial_renderer.rb:342:in `block in render_partial'
  actionview (5.1.2) lib/action_view/renderer/abstract_renderer.rb:42:in `block in instrument'
  activesupport (5.1.2) lib/active_support/notifications.rb:166:in `block in instrument'
  activesupport (5.1.2) lib/active_support/notifications/instrumenter.rb:21:in `instrument'
  activesupport (5.1.2) lib/active_support/notifications.rb:166:in `instrument'
  actionview (5.1.2) lib/action_view/renderer/abstract_renderer.rb:41:in `instrument'
  actionview (5.1.2) lib/action_view/renderer/partial_renderer.rb:331:in `render_partial'
  actionview (5.1.2) lib/action_view/renderer/partial_renderer.rb:310:in `render'
  actionview (5.1.2) lib/action_view/renderer/renderer.rb:47:in `render_partial'
  actionview (5.1.2) lib/action_view/helpers/rendering_helper.rb:35:in `render'
  app/views/client/hotels/index.html.erb:37:in `block in _app_views_client_hotels_index_html_erb__717525217098993777_70312721499440'
  app/views/client/hotels/index.html.erb:33:in `_app_views_client_hotels_index_html_erb__717525217098993777_70312721499440'
  actionview (5.1.2) lib/action_view/template.rb:157:in `block in render'
  activesupport (5.1.2) lib/active_support/notifications.rb:168:in `instrument'
  actionview (5.1.2) lib/action_view/template.rb:352:in `instrument_render_template'
  actionview (5.1.2) lib/action_view/template.rb:155:in `render'
  actionview (5.1.2) lib/action_view/renderer/template_renderer.rb:52:in `block (2 levels) in render_template'
  actionview (5.1.2) lib/action_view/renderer/abstract_renderer.rb:42:in `block in instrument'
  activesupport (5.1.2) lib/active_support/notifications.rb:166:in `block in instrument'
  activesupport (5.1.2) lib/active_support/notifications/instrumenter.rb:21:in `instrument'
  activesupport (5.1.2) lib/active_support/notifications.rb:166:in `instrument'
  actionview (5.1.2) lib/action_view/renderer/abstract_renderer.rb:41:in `instrument'
  actionview (5.1.2) lib/action_view/renderer/template_renderer.rb:51:in `block in render_template'
  actionview (5.1.2) lib/action_view/renderer/template_renderer.rb:59:in `render_with_layout'
  actionview (5.1.2) lib/action_view/renderer/template_renderer.rb:50:in `render_template'
  actionview (5.1.2) lib/action_view/renderer/template_renderer.rb:14:in `render'
  actionview (5.1.2) lib/action_view/renderer/renderer.rb:42:in `render_template'
  actionview (5.1.2) lib/action_view/renderer/renderer.rb:23:in `render'
  actionview (5.1.2) lib/action_view/rendering.rb:103:in `_render_template'
  actionpack (5.1.2) lib/action_controller/metal/streaming.rb:217:in `_render_template'
  actionview (5.1.2) lib/action_view/rendering.rb:83:in `render_to_body'
  actionpack (5.1.2) lib/action_controller/metal/rendering.rb:52:in `render_to_body'
  actionpack (5.1.2) lib/action_controller/metal/renderers.rb:141:in `render_to_body'
  actionpack (5.1.2) lib/abstract_controller/rendering.rb:24:in `render'
  actionpack (5.1.2) lib/action_controller/metal/rendering.rb:36:in `render'
  actionpack (5.1.2) lib/action_controller/metal/instrumentation.rb:44:in `block (2 levels) in render'
  activesupport (5.1.2) lib/active_support/core_ext/benchmark.rb:12:in `block in ms'
  /Users/marian/.rvm/rubies/ruby-2.3.3/lib/ruby/2.3.0/benchmark.rb:308:in `realtime'
  activesupport (5.1.2) lib/active_support/core_ext/benchmark.rb:12:in `ms'
  actionpack (5.1.2) lib/action_controller/metal/instrumentation.rb:44:in `block in render'
  actionpack (5.1.2) lib/action_controller/metal/instrumentation.rb:87:in `cleanup_view_runtime'
  actionpack (5.1.2) lib/action_controller/metal/instrumentation.rb:43:in `render'
  remotipart (1.3.1) lib/remotipart/render_overrides.rb:16:in `render_with_remotipart'
  actionpack (5.1.2) lib/action_controller/metal/implicit_render.rb:33:in `default_render'
  actionpack (5.1.2) lib/action_controller/metal/basic_implicit_render.rb:4:in `block in send_action'
  actionpack (5.1.2) lib/action_controller/metal/basic_implicit_render.rb:4:in `send_action'
  actionpack (5.1.2) lib/abstract_controller/base.rb:186:in `process_action'
  actionpack (5.1.2) lib/action_controller/metal/rendering.rb:30:in `process_action'
  actionpack (5.1.2) lib/abstract_controller/callbacks.rb:20:in `block in process_action'
  activesupport (5.1.2) lib/active_support/callbacks.rb:131:in `run_callbacks'
  actionpack (5.1.2) lib/abstract_controller/callbacks.rb:19:in `process_action'
  actionpack (5.1.2) lib/action_controller/metal/rescue.rb:20:in `process_action'
  actionpack (5.1.2) lib/action_controller/metal/instrumentation.rb:32:in `block in process_action'
  activesupport (5.1.2) lib/active_support/notifications.rb:166:in `block in instrument'
  activesupport (5.1.2) lib/active_support/notifications/instrumenter.rb:21:in `instrument'
  activesupport (5.1.2) lib/active_support/notifications.rb:166:in `instrument'
  actionpack (5.1.2) lib/action_controller/metal/instrumentation.rb:30:in `process_action'
  actionpack (5.1.2) lib/action_controller/metal/params_wrapper.rb:252:in `process_action'
  actionpack (5.1.2) lib/abstract_controller/base.rb:124:in `process'
  actionview (5.1.2) lib/action_view/rendering.rb:30:in `process'
  actionpack (5.1.2) lib/action_controller/metal.rb:189:in `dispatch'
  actionpack (5.1.2) lib/action_controller/metal.rb:253:in `dispatch'
  actionpack (5.1.2) lib/action_dispatch/routing/route_set.rb:49:in `dispatch'
  actionpack (5.1.2) lib/action_dispatch/routing/route_set.rb:31:in `serve'
  actionpack (5.1.2) lib/action_dispatch/journey/router.rb:46:in `block in serve'
  actionpack (5.1.2) lib/action_dispatch/journey/router.rb:33:in `serve'
  actionpack (5.1.2) lib/action_dispatch/routing/route_set.rb:832:in `call'
   () Users/marian/.rvm/gems/ruby-2.3.3@gre/bundler/gems/recurring_select-6dcd97ee6ee4/app/middleware/recurring_select_middleware.rb:22:in `call'
  mongoid (6.2.0) lib/mongoid/query_cache.rb:118:in `block in call'
  mongoid (6.2.0) lib/mongoid/query_cache.rb:69:in `cache'
  mongoid (6.2.0) lib/mongoid/query_cache.rb:118:in `call'
  remotipart (1.3.1) lib/remotipart/middleware.rb:32:in `call'
  warden (1.2.7) lib/warden/manager.rb:36:in `block in call'
  warden (1.2.7) lib/warden/manager.rb:35:in `call'
  rack (2.0.3) lib/rack/etag.rb:25:in `call'
  rack (2.0.3) lib/rack/conditional_get.rb:25:in `call'
  rack (2.0.3) lib/rack/head.rb:12:in `call'
  rack (2.0.3) lib/rack/session/abstract/id.rb:232:in `context'
  rack (2.0.3) lib/rack/session/abstract/id.rb:226:in `call'
  actionpack (5.1.2) lib/action_dispatch/middleware/cookies.rb:613:in `call'
  actionpack (5.1.2) lib/action_dispatch/middleware/callbacks.rb:26:in `block in call'
  activesupport (5.1.2) lib/active_support/callbacks.rb:97:in `run_callbacks'
  actionpack (5.1.2) lib/action_dispatch/middleware/callbacks.rb:24:in `call'
  actionpack (5.1.2) lib/action_dispatch/middleware/executor.rb:12:in `call'
  better_errors (2.1.1) lib/better_errors/middleware.rb:84:in `protected_app_call'
  better_errors (2.1.1) lib/better_errors/middleware.rb:79:in `better_errors_call'
  better_errors (2.1.1) lib/better_errors/middleware.rb:57:in `call'
  actionpack (5.1.2) lib/action_dispatch/middleware/debug_exceptions.rb:59:in `call'
  actionpack (5.1.2) lib/action_dispatch/middleware/show_exceptions.rb:31:in `call'
  railties (5.1.2) lib/rails/rack/logger.rb:36:in `call_app'
  railties (5.1.2) lib/rails/rack/logger.rb:24:in `block in call'
  activesupport (5.1.2) lib/active_support/tagged_logging.rb:69:in `block in tagged'
  activesupport (5.1.2) lib/active_support/tagged_logging.rb:26:in `tagged'
  activesupport (5.1.2) lib/active_support/tagged_logging.rb:69:in `tagged'
  railties (5.1.2) lib/rails/rack/logger.rb:24:in `call'
  sprockets-rails (3.2.0) lib/sprockets/rails/quiet_assets.rb:13:in `call'
  actionpack (5.1.2) lib/action_dispatch/middleware/remote_ip.rb:79:in `call'
  actionpack (5.1.2) lib/action_dispatch/middleware/request_id.rb:25:in `call'
  rack (2.0.3) lib/rack/method_override.rb:22:in `call'
  rack (2.0.3) lib/rack/runtime.rb:22:in `call'
  activesupport (5.1.2) lib/active_support/cache/strategy/local_cache_middleware.rb:27:in `call'
  actionpack (5.1.2) lib/action_dispatch/middleware/executor.rb:12:in `call'
  actionpack (5.1.2) lib/action_dispatch/middleware/static.rb:125:in `call'
  rack (2.0.3) lib/rack/sendfile.rb:111:in `call'
  rack-cors (1.0.1) lib/rack/cors.rb:93:in `call'
  railties (5.1.2) lib/rails/engine.rb:522:in `call'
  puma (3.9.1) lib/puma/configuration.rb:224:in `call'
  puma (3.9.1) lib/puma/server.rb:602:in `handle_request'
  puma (3.9.1) lib/puma/server.rb:435:in `process_client'
  puma (3.9.1) lib/puma/server.rb:299:in `block in run'
  puma (3.9.1) lib/puma/thread_pool.rb:120:in `block in spawn_thread'
</pre>

### Expected behavior

In backtrace should be info, that problem is in model. 

### Actual behavior

In backtrace is info, that problem is in partial somewhere, not exactly where.

### System configuration

**Rails version**: 5.1.2
**Ruby version**: 2.3.3

**Comment by K-S-A** [comment]
Maybe, colon is missing:

```
<%= render 'hotel_detail', hotel: hotel %>
```

**Comment by rubydev** [comment]
I'm sorry. I have mistake in this example. In code it is Ok (I changed it for example here). But it isn't first case. It was multiple times when bug was somewhere in model and backtrance ended in partial, no more informations.

**Comment by rubydev** [comment]
I found problem.

I'm using these gems also:

gem 'better_errors',      '2.1.1'
gem 'binding_of_caller',  '0.7.2'

and gem 'binding_of_caller' causing this problem.

**Comment by topherfangio** [comment]
@rubydev Did you discover why bindin_of_caller was causing issues?

I just hit this exact same thing and my workaround was to change the following code in `lib/action_view/template.rb` to a simple `raise e` so I could get the backtrace.

```ruby
      def handle_render_error(view, e)
        if e.is_a?(Template::Error)
          e.sub_template_of(self)
          raise e
        else
          #raise Template::Error.new(self)
          raise e # This is the modified line; original code above
        end
      end
```

**Comment by mildred** [comment]
It seems around 2017, there was another error that was resolved back then: https://github.com/BetterErrors/better_errors/issues/411

The issue seems to be: https://github.com/BetterErrors/better_errors/issues/466 (there is not live stack frame that exists for the original error, so it is not displayed).

**Comment by mildred** [comment]
Thanks @topherfangio, your trick allows to get a live stack frame of the error, and even get a shell with better_errors.
