### ISSUE TITLE
UnpermittedParameters not raised

### ISSUE THREAD

**Issue by KjellMorgenstern** [rails/rails#30025]
### Steps to reproduce

In config/environments/test.rb (and development.rb) set
config.action_controller.action_on_unpermitted_parameters = :raise

Run a test that tries to pass a non whitelisted parameter to an action.

Rails 5.1.2 behaves fine, the moment we upgrade to 5.1.3RC3, the unpermitted parameter is logged instead of raised.

### Expected behavior
ActionController::UnpermittedParameters should be raised.

### Actual behavior
Nothing is raised, instead the unpermitted parameter ist logged and the transaction is executed.

### System configuration
**Rails version**:
5.1.3RC3

**Ruby version**:
2.4.1

**Comment by sgrif** [comment]
Please provide a sample application that demonstrates your issue.

**Comment by pixeltrix** [comment]
Looks like it's related to this change: 6b0606a984ef259c283f1c763b12017711ed35bc

**Comment by JakariaBlaine** [comment]
I also tried to pass unpermitted parameters in the request. No exception was thrown.
The rails version was 5.1.3RC3

This is the sample application with tests - https://github.com/JakariaBlaine/rails-test

**Comment by albertoalmagro** [comment]
I could reproduce it with Rails 5.1.3RC3

@sgrif @pixeltrix May I try to fix it?

**Comment by rafaelfranca** [comment]
@albertoalmagro yes

**Comment by albertoalmagro** [comment]
Created PR https://github.com/rails/rails/pull/30045

**Comment by kaspth** [comment]
Thanks for helping out with the RCs! Much appreciated ❤️

We're on the third RC for 5.1.3 and didn't want to delay that release further. Instead we've reverted the change causing this for now.

Hopefully #30045 is ready for 5.1.4.rc1 💪

**Comment by albertoalmagro** [comment]
@kaspth yesterday I updated #30045 please feel free to review it 😊

**Comment by albertoalmagro** [comment]
PR is now merged ❤️

**Comment by rafaelfranca** [comment]
Thanks!
