### ISSUE TITLE
Request to merge regression fix (PR #29848) from 5-1-stable to 5.1.3

### ISSUE THREAD

**Issue by teohm** [rails/rails#30028]
This regression fix https://github.com/rails/rails/pull/29848 was merged into [5-1-stable](https://github.com/rails/rails/commit/0e8d4edd56f44b27f33bd214aa03af60cc5d39ae), but it's still not available in 5.1.3 branch.

The regression was introduced here https://github.com/rails/rails/pull/26972 back in 5.1.0.beta, but the root cause is only identified recently. This regression is causing production errors after we upgraded from Rails 5.0 to 5.1. Others have reported similar problem, see: https://github.com/spark-solutions/spree/commit/b5785add448062d7a7ed125ae4c5556f060a556e, https://github.com/kaminari/kaminari/issues/888.

Is there any chance we can include this regression fix into next 5.1.3 RC?

**Comment by teohm** [comment]
@kaspth Any chance we can make this happen? 🙏

**Comment by kaspth** [comment]
Nope, 5.1.3.rc3 is pretty much settled at this point. It'll be in 5.1.4 coming sometime in august 😊

**Comment by teohm** [comment]
@kaspth August is fine as well, thanks!
