### ISSUE TITLE
Rails documentation show some incorrect information about destroy_all

### ISSUE THREAD

**Issue by kashif-umair** [rails/rails#30026]
Link for reference: http://api.rubyonrails.org/v4.2/classes/ActiveRecord/Associations/CollectionProxy.html#method-i-destroy_all

The documentation of `destroy_all` in `ActiveRecord::Associations::CollectionProxy` class says that it ignores `:dependent` option but I have tested it on my system by creating a company, some groups in that company and those groups have many assets. For explanation, following is the code:
```ruby
class Company
  has_many :groups
end

class Group
  belongs_to :company
  has_many :assets, dependent: :destroy
end

class Asset
  belongs_to :group
end
```
So when I run the following code, all groups of a specific company along with it's assets get destroyed while according to the docs it should not be destroyed.
```ruby
c = Company.first
c.groups.destroy_all
```

**Comment by sgrif** [comment]
The documentation is referring to the dependent option of the association you're calling it on. You did not specify a dependent option on `groups`
