### ISSUE TITLE
ApplicationController.renderer.defaults gets unset/reloaded in development

### ISSUE THREAD

**Issue by coreyward** [rails/rails#30049]
Using the new `config/initializers/application_controller_renderer.rb` example to set the default `http_host` for ApplicationController is largely ineffective in development. This might not be the case for production, but if it can't work in development I can't use it in production. ;)

```ruby
ApplicationController.renderer.defaults.merge!(
  http_host: 'super.example.org',
  https: true
)

# bin/rails console
ApplicationController.renderer.defaults[:http_host] #=> "super.example.org"
reload!
ApplicationController.renderer.defaults[:http_host] #=> "example.org"
```

This may be related to #22975 or #24661 where `DEFAULTS.dup` was introduced to allow for modification of the defaults hash (which was frozen).

Using: Rails 5.1.1, Ruby 2.4.1

**Comment by zzb0521** [comment]
‘’‘’ruby
def hello_world
 puts 'hellow world!’
end
'''''

**Comment by zzb0521** [comment]
# This is an <h1> tag
## This is an <h2> tag
###### This is an <h6> tag

**Comment by intrip** [comment]
Maybe I'm missing something, but what about wrapping that code in a `to_prepare` block like this:

```ruby
ActiveSupport::Reloader.to_prepare do
   # put the code here
end
```

**Comment by rafaelfranca** [comment]
@intrip correct! Mind to open a PR?

**Comment by coreyward** [comment]
This would need to be applied to the generator template since this code is created with a new Rails (5+?) app. As far as initializers and generated code goes, it would be the first that comes wrapped in a `to_prepare` block. I'm not sure if that's a smell, but it's a little fishy.

**Comment by rafaelfranca** [comment]
It is not fishy, it is the only way you can configure a reloadable constant. It is fine to be the first one that requires that code, because it is the first one that needs it.

**Comment by intrip** [comment]
@rafaelfranca Yeah sure, I'll be happy to open a PR for this.

**Comment by coreyward** [comment]
> …it is the first one that needs it. 

Yes, and doesn't that strike you as odd? It should. Nowhere else does Rails require this to adjust what amounts to configuring a string. If it's necessary for some architectural reason, great. I have no issue with using hooks, or exposing them via generated code. It *is* suspect though. I imagine it would be better to adjust the implementation such that we generate the appropriate boilerplate inside of `ApplicationController` directly.

**Comment by intrip** [comment]
@rafaelfranca I've pushed a PR for this issue: #30115
