### ISSUE TITLE
SchemaDumper table_name_prefix and table_name_suffix with dollar sign support

### ISSUE THREAD

**Issue by yahonda** [rails/rails#30044]
### Summary

When `table_name_prefix` and `table_name_suffix` have the dollar sign "$",
`SchemaDumper` generates table name with `table_name_prefix` and `table_name_suffix`.
It should remove `table_name_prefix` and `table_name_suffix`.

### Steps to reproduce

$ git clone http://github.com/yahonda/rep_schema_dumper_prefix_suffix_dollar_sign
$ cd rep_schema_dumper_prefix_suffix_dollar_sign
$ ruby rep_sqlite3.rb

### Expected behavior
It should generate table name without `table_name_prefix` and `table_name suffix`. Just "posts".

### Actual behavior
It generates "foo$posts$bar". with when `table_name_prefix = "foo$"` and `ActiveRecord::Base.table_name_suffix = "$bar"`

* Formatted output below by replacing `\n` with actual new line:
```ruby 

Failure:
BugTest#test_schema_dump_with_table_name_prefix_and_suffix_with_dollar_sign [rep_sqlite3.rb:54]:
Expected /create_table "posts"/ to match "# This file is auto-generated from the current state of the database. Instead
# of editing this file, please use the migrations feature of Active Record to
# incrementally modify your database, and then regenerate this schema definition.
#
# Note that this schema.rb definition is the authoritative source for your
# database schema. If you need to create the application database on another
# system, you should be using db:schema:load, not running all the migrations
# from scratch. The latter is a flawed and unsustainable approach (the more migrations
# you'll amass, the slower it'll run and the greater likelihood for issues).
#
# It's strongly recommended that you check this file into your version control system.

ActiveRecord::Schema.define(version: 0) do

  create_table \"foo$ar_internal_metadata$bar\", primary_key: \"key\", id: :string, force: :cascade do |t|
    t.string \"value\"
    t.datetime \"created_at\", null: false
    t.datetime \"updated_at\", null: false
    t.index [\"key\"], name: \"sqlite_autoindex_foo$ar_internal_metadata$bar_1\", unique: true
  end

  create_table \"foo$posts$bar\", force: :cascade do |t|
  end

end
".
```

### System configuration
**Rails version**: master branch

**Ruby version**: 2.4.1

### Additional information

I have found this behavior when I'm working for refactoring Oracle enhanced adapter
to use `SchemaDumper#remove_prefix_and_suffix` https://github.com/rsim/oracle-enhanced/pull/1401

Oracle enhanced adapter allows (I mean it has test cases) `table_name_prefix` and `table_name_suffix` have the dollar sign.

From database point of view MySQL 5.7, PostgreSQL 9.6 and Oracle Database 12.1 allows table identifiers have dollar sign.

* MySQL 5.7
https://dev.mysql.com/doc/refman/5.7/en/identifiers.html

> Permitted characters in unquoted identifiers:
>  ASCII: [0-9,a-z,A-Z$_] (basic Latin letters, digits 0-9, dollar, underscore)

* PostgreSQL 9.6
https://www.postgresql.org/docs/9.6/static/sql-syntax-lexical.html

> SQL identifiers and key words must begin with a letter (a-z, but also letters with diacritical marks and non-Latin letters) or an underscore (_). Subsequent characters in an identifier or key word can be letters, underscores, digits (0-9), or dollar signs ($). Note that dollar signs are not allowed in identifiers according to the letter of the SQL standard, so their use might render applications less portable. The SQL standard will not define a key word that contains digits or starts or ends with an underscore, so identifiers of this form are safe against possible conflict with future extensions of the standard.

* Oracle Database 12.1
https://docs.oracle.com/database/121/SQLRF/sql_elements008.htm#SQLRF51129

> Nonquoted identifiers can contain only alphanumeric characters from your database character set and the underscore (_), dollar sign ($), and pound sign (#). Database links can also contain periods (.) and "at" signs (@).

Have not found if SQLite3 allows it or not.

**Comment by yahonda** [comment]
Created a dirty workaround fix https://github.com/yahonda/rails/commit/2d674ac05068d0bb62e48251b0eb3cf75310eddb

**Comment by kamipo** [comment]
> Created a dirty workaround fix https://github.com/yahonda/rails/commit/2d674ac05068d0bb62e48251b0eb3cf75310eddb

It is better to use `Regexp.escape`:

```ruby
prefix = Regexp.escape(@options[:table_name_prefix])
suffix = Regexp.escape(@options[:table_name_suffix])
table.sub(/\A(?:#{prefix})(.+)(?:#{suffix})\z/, "\\1")
```

**Comment by yahonda** [comment]
Thanks as always. `Regexp.escape` looks better just escaping $ separately. Will create a pull request.

**Comment by yahonda** [comment]
Opened #30048. Added `.to_s` to handle `TypeError: no implicit conversion of nil into String` when `table_name_prefix` or `table_name_suffix` is nil. 

```$ grep -r 'fix = nil' test/
test/cases/migration/foreign_key_test.rb:          ActiveRecord::Base.table_name_prefix = nil
test/cases/migration/foreign_key_test.rb:          ActiveRecord::Base.table_name_suffix = nil
test/cases/migration/references_foreign_key_test.rb:          ActiveRecord::Base.table_name_prefix = nil
test/cases/migration/references_foreign_key_test.rb:          ActiveRecord::Base.table_name_suffix = nil
$
```
