### ISSUE TITLE
Session: concurrency while storing in cache

### ISSUE THREAD

**Issue by lfekson** [rails/rails#30043]
### Steps to reproduce
Not sure if it's possible to reproduce stable enough, the workflow is:
1) session has *old* values in key1 and key2.
2) controller1 action changes a session key1 and key2 and redirects to controller2.
3) controller2 action renders a page. This page has an asynchronous ajax call to controller3. The ajax call comes to server and changes session key1.
After that the session can have updated only key1, but old key2. The more slowly network/server, the bigger chance to get this problem.

### Expected behavior
Session should have new values in both key1 and key2. For that probably cache should be saved before redirection happens or at least before the action called by redirection starts. Don't know about Rails 4, but Rails 3.2 didn't have this problem.

### Actual behavior
Session has updated key1 only, because step 3) reads session before step 2) was able to write it to cache. For this exactly case a workaround with moving the ajax call to inside $(document).ready(...) does help.

### System configuration
**Rails version**: 5.0
dalli 2.7
**Ruby version**: 2.4.1

**Comment by rafaelfranca** [comment]
Thank you for the issue but this is not a problem in the framework. It is a concurrency problem in your application.
