### ISSUE TITLE
Method 'message' is not allowed in Mailer Class

### ISSUE THREAD

**Issue by papayalabs** [rails/rails#30055]
If you have a Mailer class with the method 'message' gives error: ArgumentError: wrong number of arguments (given 0, expected 2)

```
class MessageMailer < ApplicationMailer
      default from: Rails.application.secrets.no_reply_email

      def message(current_user, email)
        mail to: email, subject: "#{current_user.name} has sent you a message"
      end
end
```

If you change method name 'message' works.

### System configuration
**Rails version**:
Rails 5.1.2 
**Ruby version**:
Ruby 2.4.1

**Comment by georgeclaghorn** [comment]
ActionMailer::Base defines a method named `message`. You’re overriding it.

This isn’t really a bug. You’ll need to choose a different name for your action. It could perhaps be better documented that you can’t define an action named `message`.

**Comment by papayalabs** [comment]
Ah Ok!. And yes, I was searching and I did not find anything that said I can not use an action named 'message'.

**Comment by papayalabs** [comment]
Wait, could you please send me where is defined 'message' in ActionMailer:Base. I could not find it. Thank!

**Comment by georgeclaghorn** [comment]
It’s defined [here](https://github.com/rails/rails/blob/5fd50c387bdfc2761859ec7a57477bcd56e93210/actionmailer/lib/action_mailer/base.rb#L591), by way of [`attr_internal`](https://github.com/rails/rails/blob/5fd50c387bdfc2761859ec7a57477bcd56e93210/activesupport/lib/active_support/core_ext/module/attr_internal.rb#L30-L37).

**Comment by papayalabs** [comment]
Ah ok! Thanks! I will look what is attr_internal.

**Comment by nynhex** [comment]
I ran into the same problem, but ActionMailer should be better documented as I spent nearly 30 minutes debugging this same thing.  I'd be happy to open a PR if you think it warrants it.
