### ISSUE TITLE
Usefulness of ID attribute in hidden_field_tag

### ISSUE THREAD

**Issue by meowsus** [rails/rails#30063]
### Steps to reproduce
Suppose there are two forms on a page. Both contain the same hidden input value, perhaps to honor a special case such as telling the controller to redirect to an unexpected path if the specific form was to submit:

```erb
<%= form_for first_route_path, method: 'post' do %>
  <%= hidden_field_tag 'redirect_to', some_other_path %>
<%= end %>

<%= form_for second_route_path, method: 'post' do %>
  <%= hidden_field_tag 'redirect_to', some_other_path %>
<%= end %>
```

### Expected behavior
The behavior I would expect is more developer facing. Why should I have to remove the value of the ID attribute of these fields to avoid issues caused by having more than one ID on a single page?

```erb
<%= form_for first_route_path, method: 'post' do %>
  <%= hidden_field_tag 'redirect_to', some_other_path, id: nil %>
<%= end %>

<%= form_for second_route_path, method: 'post' do %>
  <%= hidden_field_tag 'redirect_to', some_other_path, id:nil %>
<%= end %>
```

### Actual behavior
The compiled output of the first example produces duplicate IDs in the DOM.

```html
<form action='/path/to/route' method='post' ...>
    <input type='hidden' name='redirect_to' id='redirect_to' value='/path/to/somewhere/else'>
</form>

<form action='/path/to/route' method='post' ...>
    <input type='hidden' name='redirect_to' id='redirect_to' value='/path/to/somewhere/else'>
</form>
```

### Proposal

IDs on inputs are used to connect a `label` tag with an associated `input` tag, via:

```html
<label for="assoc-input">Label</label>
<input id="assoc-input" type="text" name="some-input">
```

Since there is no natural reason for a hidden input to have an associated label, I propose that the ID attribute be omitted by default. It could always be manually specified if the developer is trying to achieve some desired functionality via JavaScript or some sneaky CSS.

### System configuration
**Rails version**: N/A

**Ruby version**: N/A

**Comment by sgrif** [comment]
Thanks, but the IDs are there to be able to reference the form field from JS and tests. Labels use `name` not `id`. This behavior is not something we are going to change.

**Comment by meowsus** [comment]
@sgrif I can understand the argument for keeping IDs for JavaScript and testing purposes. 

However, labels do not use `name` for their association, as shown in this stub: https://codepen.io/meowsus/pen/XajQam

**Comment by SampsonCrowley** [comment]
@meowsus I just want to clarify for future visitors, that labels DO use the name prop, but they check for a matching ID first
