### ISSUE TITLE
Association subquery not fetching foreign_key for `has_many` or `has_one`

### ISSUE THREAD

**Issue by coreyward** [rails/rails#30077]
For the following models:
```ruby
class Account < ActiveRecord::Base
  has_many :invoices
end

class Invoice < ActiveRecord::Base
  belongs_to :account
end
```

This query:

```ruby
Account.where(invoices: Invoice.where(paid: true))
```

Results in the following SQL (using Postgres):
```sql
SELECT "accounts".* FROM "accounts" WHERE "accounts"."account_id" IN (SELECT "invoices"."id" FROM "invoices" WHERE "invoices"."paid" = 't')
```

This will fail as it's expecting `accounts` to have an `account_id` column that is on `invoices`. The other direction works fine, and I expected Rails to correctly select `invoices.account_id` in the subquery. 

The expected query is:

```sql
SELECT "accounts".* FROM "accounts" WHERE "accounts"."id" IN (SELECT "invoices"."account_id" FROM "invoices" WHERE "invoices"."paid" = 't')
```

ActiveRecord will generate the correct query if specified more directly (below), so I suspect it's just a matter of reflecting on the association and determining the directionality, but I'm not super familiar with this area of ActiveRecord.
```ruby
Account.where(id: Invoice.where(paid: true).select(:account_id))
```

**Rails version**: 5.1.1

**Ruby version**: 2.4.1

**Comment by JakariaBlaine** [comment]
I tried to run these codes and wrote tests....
The issue is accurate...
This is the repo that I tested the feature in - https://github.com/JakariaBlaine/rails-test/tree/30077

**Comment by lugray** [comment]
You want `Account.joins(:invoices).where(invoices: {paid: true})`

**Comment by coreyward** [comment]
@lugray This is another strategy to accomplish this, but it does not use a subquery, and it forces manual pluralization of table names rather than using relational geometry handled by ActiveRecord (i.e. `Invoice.where(paid: true)`, which lends itself to scoping: `Invoice.paid`). As mentioned, this works the other direction (`Invoice.where(account: Account.where(active: false))`); requiring knowledge of which model has the foreign key to adapt strategies makes it a leaky abstraction. 

Assuming this isn't existing behavior and would be desirable, I would be happy to do the legwork to add it.

**Comment by lugray** [comment]
I'm not convinced that abstracting away the directionality is desired.  For one, `Account.where(invoices: Invoice.where(paid: true))` is somewhat ambiguous: should this be accounts where all invoices are paid, or accounts having at least one paid invoice? Because in this direction `invoices:` is plural, it actually somewhat looks like accounts where the set of invoices is the set of all paid invoices, which is almost certainly never what's desired.

**Comment by coreyward** [comment]
I could see where that would be confusing, but if you're familiar with this syntax/construction already it should be clear. This always results in an `IN` statement and a subquery. `invoices:` maps to the association named thusly.

If this worked as I've described, you could actually get the other result you've described like this:

```
Account.where.not(invoices: Invoice.where(paid: false))
```

That's a lot better than forcing an outer join isn't it:

```
Account.joins(
Account.arel_table.join(Invoice.arel_table, Arel::Nodes::OuterJoin).on(
Invoice.arel_table[:paid].eq true
).join_sources
)
```

**Comment by lugray** [comment]
I think your `Account.where(id: Invoice.where(paid: true).select(:account_id))` syntax makes sense, being clear about what's happening (and also allows `Account.where.not(id: Invoice.where(paid: false).select(:account_id))`).

If you really think this should be a feature, and you want to validate it with more people, I'd recommend asking in the Rails Core mailing list for feedback before you try to implement the feature and send us a pull request.  For the moment though, thank you for the issue but we don’t take feature request on the issue tracker.

**Comment by coreyward** [comment]
@lugray The problem with this query: 

```ruby
Account.where(id: Invoice.where(paid: true).select(:account_id))
```

…is that it breaks scope chaining and requires some other object to couple to the specific foreign key. In the types of apps I've worked on (early stage, moderate complexity, fast moving), this quickly winds up getting broken. Whenever possible I use scopes and the underlying association definition to delegate to the database.

Consider a less basic scenario: Invoice maps to an `accounts_payable` table, and the name of the association from account is `PaidInvoices` with a `where(paid: true)` clause on it, and what we're actually trying to fetch here is accounts with an invoice that needs a receipt sent (`Invoice.where(receipt_sent_at: nil)`). This isn't that far a stretch considering some of what I'm working on right now (though the problem domain is different).

**Comment by rafaelfranca** [comment]
It should be fixed by https://github.com/rails/rails/pull/30126
