### ISSUE TITLE
String of numbers not fully stored in database

### ISSUE THREAD

**Issue by qinglong15** [rails/rails#30071]
I'm trying to store a number as a string into the database. It works in general but not with the number mentioned below.

### Steps to reproduce
Setup a model with a string attribute, schema:
```ruby
create_table "people", id: :integer, force: :cascade, options: "ENGINE=InnoDB DEFAULT CHARSET=utf8mb4" do |t|
    t.string "firstname"
    t.string "lastname"
    t.string "mobile"
end
```

Create new object:
```ruby
Person.create firstname: 'Chuck', lastname: 'Norris', mobile: '0792900414'
```

Resulting SQL:
```sql
INSERT INTO `people` (`firstname`, `lastname`, `mobile`, `gender`, `created_at`, `updated_at`) VALUES ('Chuck', 'Norris', '0792904', '2017-08-04 07:39:06', '2017-08-04 07:39:06')
```

### Expected behavior
Insert `0792900414` into database

### Actual behavior
`0792904` inserted into database

### System configuration
**Rails version**: 5.1.3

**Ruby version**:
- ruby 2.3.3p222 (2016-11-21 revision 56859) [x86_64-darwin16]
- ruby 2.4.0p0 (2016-12-24 revision 57164) [x86_64-darwin16]

**Comment by sgrif** [comment]
I was unable to reproduce this issue using the steps provided. Please provide an executable test case that we can use to reproduce this issue, using [our standard bug report template](https://github.com/rails/rails/blob/master/guides/bug_report_templates/active_record_master.rb)

**Comment by qinglong15** [comment]
I did some investigating an found an invalid method (after hours of searching) which changes the mobile number...

```ruby
self.mobile = self.mobile.gsub("+41", "0").gsub("0041", "0").gsub("+49", "0049")
```

I'm very sorry for bothering you!
