### ISSUE TITLE
secrets.rb

### ISSUE THREAD

**Issue by patleb** [rails/rails#30117]
Not a big issue, but I was surprised to see `lib/rails/secrets.rb` in Railties instead of ActiveSupport. Wouldn't it be a more appropriate place? That would allow to reuse secrets in other contexts/gems without requiring Railties, but ActiveSupport only.

**Comment by robin850** [comment]
Hello @patleb,

This tracker is for issues only. If you have proposals, please post a message on the rails-core mailing list.

Also, `Rails.secrets` is just a wrapper around regular YAML and ERB. The encrypted secrets are encrypted / decrypted through `ActiveSupport::MessageEncryptor` which is really simple to use.

**Comment by patleb** [comment]
Got it. Thanks!

**Comment by kaspth** [comment]
I didn't at first because it was very much scoped to just encrypted secrets. But we're doing exactly what you're asking for here: https://github.com/rails/rails/pull/30067 😊
