### ISSUE TITLE
Autosave does not save associated records, `belongs_to` validation fooled

### ISSUE THREAD

**Issue by coreyward** [rails/rails#30128]
[Documentation for `belongs_to`](http://api.rubyonrails.org/classes/ActiveRecord/Associations/ClassMethods.html#method-i-belongs_to) specifies that the default behavior for `autosave` is to save associated records if they are new (i.e., not-persisted). This isn't working for me in Rails 5.1.1 or 5.1.3.

[Example app available here](https://github.com/coreyward/testing-autosave)

### Steps to reproduce
Given the following app: 
```ruby
class CreateUsers < ActiveRecord::Migration[5.1]
  def change
    create_table :users do |t|
      t.string :name

      t.timestamps
    end
  end
end

class CreateWidgets < ActiveRecord::Migration[5.1]
  def change
    create_table :widgets do |t|
      t.string :name
      t.belongs_to :user, foreign_key: true

      t.timestamps
    end
  end
end

class Widget < ApplicationRecord
  belongs_to :user
end

class User < ApplicationRecord
  has_many :widgets
  validates :name, presence: true
end
```

Saving a record does not save associated records: 

```ruby
u = User.new
# => #<User id: nil, name: nil, created_at: nil, updated_at: nil> 
w = u.widgets.new(name: "Widgie")
# => #<Widget id: nil, name: "Widgie", user_id: nil, created_at: nil, updated_at: nil> 
w.valid?
# => true 
w.save
   (0.2ms)  BEGIN
  SQL (0.9ms)  INSERT INTO "widgets" ("name", "created_at", "updated_at") VALUES ($1, $2, $3) RETURNING "id"  [["name", "Widgie"], ["created_at", "2017-08-07 22:58:25.275935"], ["updated_at", "2017-08-07 22:58:25.275935"]]
   (6.7ms)  COMMIT
# => true 
w.user
# => #<User id: nil, name: nil, created_at: nil, updated_at: nil> 
w.valid?
# => true 
w.user.persisted?
# => false 
```

### Expected behavior

The primary record and all associated records that are new should attempt to be saved. Any associated record that is invalid should result in the save being aborted and the errors be available via the usual ActiveModel::Validations errors hash. 

If a `belongs_to` associated record is not able to be saved for any reason (e.g., database constraint prevents it), and `optional` is not set to `true`, the record should have a validation error specifying that the association is required (even if there are no ActiveModel::Validations errors on the associated record).

### System configuration
**Rails version**: discovered on 5.1.1, tested on 5.1.3

**Ruby version**: 2.4.1

**Comment by lugray** [comment]
To get the effect you're looking for, you need `validates_associated` on `Widget`.

```ruby
class Widget < ActiveRecord::Base
  belongs_to :user, required: true

  validates_associated :user
end
```

**Comment by coreyward** [comment]
@lugray Not according to the documentation I linked or the [tests for autosave](https://github.com/rails/rails/blob/master/activerecord/test/cases/autosave_association_test.rb). Did you experience different behavior with the `validates_associated` call?

**Comment by intrip** [comment]
@coreyward  According to [this test](https://github.com/rails/rails/blob/master/activerecord/test/cases/autosave_association_test.rb#L223) looks like the behavior is the one expected. 
The documentation in this case looks a bit leaky, especially in this part: `If validations for any of the associations fail, their error messages will be applied to the parent.` That part should say explicitly  that this happens only when `autosave: true` or `validate: true`

**Comment by lugray** [comment]
The key there is parent: in this case user is the parent since widget `belongs_to` it.

**Comment by intrip** [comment]
Yeah you're right

**Comment by coreyward** [comment]
I've also noticed that `belongs_to` now loads the associated records on save, even when the foreign key has not been updated:

```ruby
w = Widget.first
  Widget Load (0.3ms)  SELECT  "widgets".* FROM "widgets" ORDER BY "widgets"."id" ASC LIMIT $1  [["LIMIT", 1]]
 => #<Widget id: 1, name: "Foo", user_id: 1, created_at: "2017-08-07 22:58:25", updated_at: "2017-08-08 19:01:26"> 
w.name = "Bar"
 => "Bar" 
w.save
   (0.2ms)  BEGIN
  User Load (0.2ms)  SELECT  "users".* FROM "users" WHERE "users"."id" = $1 LIMIT $2  [["id", 1], ["LIMIT", 1]]
  SQL (0.4ms)  UPDATE "widgets" SET "name" = $1, "updated_at" = $2 WHERE "widgets"."id" = $3  [["name", "Bar"], ["updated_at", "2017-08-08 19:02:05.252106"], ["id", 1]]
   (0.9ms)  COMMIT
 => true
```

This is undesirable, especially when `validate` is not set on the association.

**Comment by lugray** [comment]
@coreyward I see that behaviour with `validates_associated :user`, as indeed it must to validate on update as well, but if you just use `belongs_to :user, validate: true`, it doesn't load the user when you update a widget.  If I've missed something, please include a failing test using the [template](https://github.com/rails/rails/blob/master/guides/bug_report_templates/active_record_master.rb).

**Comment by coreyward** [comment]
The first test is successful in demonstrating the behavior I described above. The second test passes when using a memory-backed SQLIte adapter in this test case, but fails in [the provided example application](https://github.com/coreyward/testing-autosave) using Postgres.

```ruby
begin
  require "bundler/inline"
rescue LoadError => e
  $stderr.puts "Bundler version 1.10 or later is required. Please update your Bundler"
  raise e
end

gemfile(true) do
  source "https://rubygems.org"
  gem "rails", github: "rails/rails"
  gem "arel", github: "rails/arel"
  gem "sqlite3"
end

require "active_record"
require "minitest/autorun"
require "logger"

# This connection will do for database-independent bug reports.
ActiveRecord::Base.establish_connection(adapter: "sqlite3", database: ":memory:")
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :posts, force: true do |t|
    t.string :title
  end

  create_table :comments, force: true do |t|
    t.integer :post_id
    t.string :message
  end
end

class Post < ActiveRecord::Base
  has_many :comments
  validates_presence_of :title
end

class Comment < ActiveRecord::Base
  belongs_to :post
end

class BugTest < Minitest::Test
  def test_child_aborts_if_parent_not_persisted
    post = Post.new
    comment = post.comments.new(message: "Hello world.")

    assert !post.valid?
    assert comment.valid?

    comment.save

    assert !comment.persisted?
    assert !post.persisted?
  end

  def test_parent_not_loaded_when_child_saved
    post = Post.create!(title: "Test Post")
    post.comments.create!(message: "Hello again.")

    comment = Comment.first
    assert !comment.association(:post).loaded?

    comment.message = "Hello again!"
    comment.save!

    assert !comment.association(:post).loaded?
  end
end
```

**Comment by coreyward** [comment]
This bug still exists.

@lugray Can you comment on why this was closed? Should I update the documentation to reflect current behavior?
