### ISSUE TITLE
Deprecations misused?

### ISSUE THREAD

**Issue by jcoyne** [rails/rails#30137]
I'm seeing lot deprecation warnings informing me of behavior that will be changing.  

```
DEPRECATION WARNING: The behavior of `attribute_changed?` 
inside of after callbacks will be changing in the next version of Rails.
The new return value will reflect the behavior of calling the method 
after `save` returned (e.g. the opposite of what it returns now). 
To maintain the current behavior, use `saved_change_to_attribute?` instead. 
```

I believe these were introduced with #25337

A deprecation is to "express disapproval of something" However, these are not deprecating the method.  Rather they are informing the user of an impending change. 

I want to use the new behavior, so sending deprecation warnings to me makes for a cluttered log/stderr.  I don't want to turn off all deprecation warnings, as many of them will be helpful to me.  It would be helpful if there was a new method I could switch to so that I don't see warnings and I'm sure I have the correct behavior.

**Comment by rafaelfranca** [comment]
I think the intention is to remove those methods, and new methods were added to map to the two different behaviors this method could have today, but I'll let @sgrif explain

**Comment by sgrif** [comment]
There's no current plan to remove any of the old or new methods, but yeah we do have two aliases. If you want the new behavior, you should not be calling `attribute_changed?` in 5.1. You should be calling `will_save_change_to_attribute?` instead. The methods are documented, but I only realized last night that they aren't showing up on the API docs website due to the whole module being `# :nodoc:`. It'll be fixed later today.

**Comment by sgrif** [comment]
Closing as there's nothing actionable here. Hopefully I've answered your question. Feel free to continue to comment here if you have more questions (since the docs aren't currently being rendered >_>)

**Comment by jcoyne** [comment]
@sgrif thanks for the explanation.  I'm not sure that the existing deprecation communicates that as clearly as your comment above does.  Perhaps it could be improved?

**Comment by sgrif** [comment]
The deprecation is mostly for existing code, which will want to keep the old behavior (at the time it was introduced we weren't sure if the "new" methods were something we wanted to keep around).

I'd be fine with a PR against 5-1-stable which adds a "to use the new behavior to day call x instead" though
