### ISSUE TITLE
Custom validation message for numericality validator

### ISSUE THREAD

**Issue by RuslanKorn** [rails/rails#30136]
I don't have opportunity to add custom message for numericality validator.
I can change global message, but would be great if I can change it for concrete type (greater_than, greater_than_or_equal_to, odd, even etc) as it is done in length validator (for ex. length: { within: 1..2, too_short: 'min 1',  too_long: 'max 2'}).

**Comment by lugray** [comment]
Thank you so much for the issue but we don’t take feature request on the issue tracker. We recommend you try to implement the feature and send us a pull request or if you are in doubt as to whether the feature will be accepted, ask in the Rails Core mailing list for feedback.
