### ISSUE TITLE
Non-English filenames in Active Storage

### ISSUE THREAD

**Issue by colorfulfool** [rails/rails#30134]
URLs with non-English filenames are still broken. UTF8-encoding them didn't help, apparently.
![2017-08-08 15 06 05](https://user-images.githubusercontent.com/1292290/29071240-532343e0-7c4b-11e7-9bc5-3f23bb334bfb.png)
I propose transliterating them, at least for the uncooperative services. An image with imperfect filename is better than no image at all.

**Comment by georgeclaghorn** [comment]
As I said the last time you brought this up, the correct fix for this is to properly encode the filename according to RFC 2231. That hasn’t been done yet.

**Comment by colorfulfool** [comment]
Sorry, I thought it has.

**Comment by georgeclaghorn** [comment]
@colorfulfool: I just added RFC 2231 encoding for Content-Disposition filenames in 63395ab. Mind taking it for a spin?

**Comment by colorfulfool** [comment]
Works just fine 👍
