### ISSUE TITLE
ActiveStorage looses storage service after exception

### ISSUE THREAD

**Issue by 42he** [rails/rails#30151]
### Steps to reproduce

After the Rails App throws an exception in one request the AS looses it configuration and fails working until the restart of the puma server. 

I Used the Disk Storage Server in development enviroment. 

local:
  service: Disk
  root: <%= Rails.root.join("storage") %>

  config.active_storage.service = :local

### Expected behavior
Keep the config after an exception. 

### Actual behavior
AS looses it storage service configuration until the restart of puma.

until then all request containing an Attachment will cause an exception: 

undefined method `download' for nil:NilClass
/Users/mo/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/bundler/gems/rails-4b72bee47bb5/activestorage/app/models/active_storage/blob.rb:160:in `download'

### System configuration
**Rails version**:

5.2.0.alpha
**Ruby version**:

MRI 2.4.1

**Comment by rafaelfranca** [comment]
This should be fixed on master now.
