### ISSUE TITLE
Adding active storage fails to create the configuration

### ISSUE THREAD

**Issue by hahmed** [rails/rails#30150]
I am trying to install active storage, I am following along with the installation at:
https://github.com/rails/rails/tree/master/activestorage#installation

### Steps to reproduce

```
haroon in projects/ 
› rails new ohmystorage --database=postgresql --edge
```

### Expected behavior

Run `rails activestorage:install` to create needed _directories_, _migrations_, and _configuration_.

Create the 3 items above.

### Actual behavior

I can confirm the migrations are created, but no configuration file - I assume this is the **storage.yml**? 

BTW what directories _should_ get created?

### System configuration
**Rails version**: edge

**Ruby version**: 2.3.1

**Repo**: https://github.com/hahmed/ohmystorage

**Comment by rafaelfranca** [comment]
`rails new --edge` don't support Active Storage yet, because that command is being run in the version you have installed (maybe 5.1.3). To be able to generate a new application with active storage you need to clone rails and run the command inside `railties/exe`
