### ISSUE TITLE
form_with and params scoping

### ISSUE THREAD

**Issue by knzudgt** [rails/rails#30153]
### System configuration
**Rails version**: 5.0.0.1

**Ruby version**: 2.3.1

First of all I wonder if I will be able to use `form_with` in `Rails 5.0.0.1`.
I found little documentation about `form_with`. My main question is: how will the attributes be scoped when using `form_with` with and without a model? Take for instance the following code:

    <%= form_with url: users_path do |form| %>
      <%= form.text_field :email %>
      <%= form.submit %>
    <% end %>

Will `email` be available in `params[:email]` or in `params[:user][:email]`? 
Consider also the following example using `form_with` with a model:

    <%= form_with model: @user, local: true do |form| %>
      <%= form.text_field :email %>
      <%= form.check_box :send_welcome_email %>
      <%= form.submit %>
    <% end %>

Where `email` and `send_welcome_email` will be available? In `params[:user][:email]` and `params[:user][:send_welcome_email]` or in `params[:email]` and `params[:send_welcome_email]`?

**Comment by JagdeepSingh** [comment]
I was trying to check the params for the configuration you mentioned above:
**Rails version**: 5.0.0.1
**Ruby version**: 2.3.1

But, it gave me this error:
```
ActionView::Template::Error (undefined method 'form_with' for #<#<Class:0x007f9cf635eef0>:0x007f9cf635daf0>
```

I guess `form_with` is not available in this version of `rails`.

So, i upgraded `rails` to **5.1.3** and `ruby` (optional) to **2.4.1** and tried again.

With first approach:

```erb
<%= form_with url: users_path do |form| %>
  <%= form.text_field :email %>
  <%= form.submit %>
<% end %>
```

`params` are caught in the controller as follows:

```ruby
> params
=> <ActionController::Parameters {"utf8"=>"✓", "authenticity_token"=>"DRC+Zm09nRfwYOQhPIDT5c186sHG+jw+aMNeTGBsUxXtl9I7d/60fU6boWqFFX4FFgbE+RWIQEPV/LqmOhWQvA==", "email"=>"jagdeepsingh@demo.com", "commit"=>"Save ", "controller"=>"users", "action"=>"create"} permitted: false>
> params[:email]
=> "jagdeepsingh@demo.com"
```

And for second approach:

```erb
<%= form_with model: @user, local: true do |form| %>
  <%= form.text_field :email %>
  <%= form.check_box :send_welcome_email %>
  <%= form.submit %>
<% end %>
```

they can be accessed as below:

```ruby
> params
=> <ActionController::Parameters {"utf8"=>"✓", "authenticity_token"=>"LL233FxEfIzCJKv0bualSzc9XUQ+4qURbJU517uYS5PMOtuBRodV5nzf7r/Xcwir7EdzfO2Q2WzRqt094eGIOg==", "user"=>{"email"=>"jagdeepsingh@demo.com", "send_welcome_email"=>"1"}, "commit"=>"Create User", "controller"=>"users", "action"=>"create"} permitted: false>
> params[:user]
=> <ActionController::Parameters {"email"=>"jagdeepsingh@demo.com", "send_welcome_email"=>"1"} permitted: false>
```

Hope it helps.
