### ISSUE TITLE
Rails where.not query for postgresql not returning correct result for Boolean fields when having null values

### ISSUE THREAD

**Issue by om-nishu-trantor** [rails/rails#30155]
### Steps to reproduce
1. Create a model with a boolean column.
2. Create some entries with with value NULL/nil in boolean column
Hit the following in rails console :-
`Model.where.not(boolean_field: [true]).count` 
### Expected behavior
It is expected that it should return the count of all the entries in database having value in boolean column as `nil`/`NULL`.

### Actual behavior
Despite having multiple `nil` values which are evantually `!= true` it returns count as `0`

### System configuration
**Rails version**:
Rails 5.0.0.1
**Ruby version**:
2.3.1
**Postgresql Version**
9.6.1

### Additional information
A funny thing happening is.
When I hit the non-conventional call to database i.e. 
`Model.where.not('models.boolean_field IS true').count`
###=> `SELECT COUNT(*) FROM "models" WHERE (NOT (models.boolean_field IS true))`
returns the expected count
Where as when I hit the conventional call Rails query i.e.
`Model.where.not(boolean_field: [true]).count`
###=> `SELECT COUNT(*) FROM "models" WHERE ("models"."boolean_field" != 't')`
returns `0`
I tried hitting multiple queries returning result 0 :-
`Model.where.not(boolean_field: [true]).count`
`Model.where.not(boolean_field: true).count`
`Model.where.not(boolean_field: false).count`
`Model.where.not(boolean_field: [false]).count`

**Comment by lugray** [comment]
This is expected behaviour.  `NULL` is not a value, it's the absence of one, so `NULL != true` is not true, it is NULL, because absent the value, the value of the expression cannot be determined.
```
SELECT NULL != true, NULL = true, NULL != false, NULL = false, false != true, false = true;
+--------------+-------------+---------------+--------------+---------------+--------------+
| NULL != true | NULL = true | NULL != false | NULL = false | false != true | false = true |
+--------------+-------------+---------------+--------------+---------------+--------------+
|         NULL |        NULL |          NULL |         NULL |             1 |            0 |
+--------------+-------------+---------------+--------------+---------------+--------------+
```
 https://stackoverflow.com/questions/5658457/not-equal-operator-on-null

**Comment by om-nishu-trantor** [comment]
I am not sure then why 
```ruby
Model.where.not('models.boolean_field IS true').count
```
is returning the results correctly.
Also, to solve this problem, rather put the default value as false(instead of not defining it, leading to NULL/nil) and Not nil.
At least, that is how I solved my problem.

**Comment by om-nishu-trantor** [comment]
Moreover, rails should implement this as a feature.
Just like it do for `datetime` and `timestamp`. Bot being different in SQL but same for Rails ActiveRecord.

**Comment by lugray** [comment]
`IS` is a special operator in SQL, usually reserved for comparison to NULL. Setting a default of `false` will help, you could also add a not null constraint to your database.   The timestamps are generated with this constraint as you point out, but generic datetime columns do not have a default/not null constraint, just like generic boolean columns.  Adding this as a default would be surprising, but rails already has this as an optional feature, just add options to your migration: `null: false, default: false`

**Comment by om-nishu-trantor** [comment]
Sorry for the confusion, when I mention the `datetime` and `timestamp`, I meant that, in the domain of SQL they are different, but whether you create a migration with the column as a `:datetime`, or a `:timestamp` they both become the `:datetime` as mentioned here : https://stackoverflow.com/questions/3928275/in-ruby-on-rails-whats-the-difference-between-datetime-timestamp-time-and-da

But, my confusion is that why are the following queries not same :-
1. `Model.where.not('models.boolean_field IS true').count` #=> `SELECT COUNT(*) FROM "models" WHERE (NOT (models.boolean_field IS true))`
2. `Model.where.not(boolean_field: [true]).count` #=> `SELECT COUNT(*) FROM "models" WHERE ("models"."boolean_field" != 't')`

And one more finding,
`Model.where.not('boolean_field IS ?', true).count` throws an error :-
`SELECT COUNT(*) FROM "application_logs" WHERE (NOT (processed IS 't'))
ActiveRecord::StatementInvalid: PG::SyntaxError: ERROR:  syntax error at or near "'t'"`

**Comment by lugray** [comment]
`IS` and `=` are intentionally different operators in SQL.  As you've noticed, testing `=` (or `!=`) against `NULL` always gives `NULL`, while testing with `IS NULL` (or `IS NOT NUL`) is the expected way to check whether a value is `NULL`:
```
SELECT NULL = NULL, NULL != NULL, NULL IS NULL, NULL IS NOT NULL;
+-------------+--------------+--------------+------------------+
| NULL = NULL | NULL != NULL | NULL IS NULL | NULL IS NOT NULL |
+-------------+--------------+--------------+------------------+
|        NULL |         NULL |            1 |                0 |
+-------------+--------------+--------------+------------------+
```

**Comment by brandondrew** [comment]
>  so NULL != true is not true

If `NULL != true` is _not true,_ then `NULL != true` is _false._

An absent value is _clearly_ not the same as a specified value.
