### ISSUE TITLE
Documentation error?

### ISSUE THREAD

**Issue by juryghidinelli** [rails/rails#30162]
Is "collection(force_reload = false)" right in has_many relation? I saw that it was deprecated

https://github.com/rails/rails/blob/4aaa053a2bf6b32f68c2b384ca7b909c4e849b11/activerecord/lib/active_record/associations.rb#L1190

**Comment by robin850** [comment]
Hello @juryghidinelli,

This issue but it has been fixed with https://github.com/rails/rails/commit/d9496c19c07d56bb200acd7312bf5d6355d515f4. The API documentation is tied to a release of Rails and this patch hasn't been part of any release yet.

Thanks for reporting anyway ! :-)
