### ISSUE TITLE
The so-called "abstract" ApplicationController is not an abstract controller

### ISSUE THREAD

**Issue by joshpencheon** [rails/rails#30172]
### Steps to reproduce
I've posted a test script here: https://gist.github.com/joshpencheon/5ac9245540c0011f0b69686d9e509251

The test should have a failing assertion when run.

### Expected behaviour
It's common to refer to `ApplicationController` as an "abstract" controller, and use it as a dumping ground for site-wide authentication logic, helpers, and so forth. There is generally no expectation that it is routable.

My expectation would be that `ApplicationController` is an abstract class, and that any public methods it has would not become `action_methods` on all inheriting controllers. This is a trade-off between expected Ruby inheritance behaviour, and the principle of least surprise when using something that Rails suggests is "abstract-y".

_Noting also that, as of in Rails 5, we have the related concept of `ApplicationRecord`, which is explicitly flagged as an `abstract_class`._

### Actual behaviour
`ApplicationController` is not actually marked as an abstract controller, meaning that its public methods become routable actions on any other controllers in an application. This came as a surprise to me, particularly in light of the `ApplicationRecord` direction of travel.

My crude test case, linked above, shows how confusion here could lead to some rather undesirable consequences of allowing unintended code to be routable. Admittedly the same is true mixing in logic to any controller, but my feeling is `ApplicationController` isn't _any_ controller.

### System configuration
**Rails version**: master

**Ruby version**: 2.4.1

### Next?
If this is known and intended, then fine - I can chalk this up to "learn something every day". Otherwise, I have prepared a commit to make `ApplicationController` abstract for newly-generated apps: https://github.com/joshpencheon/rails/commit/9de32f88bba6

I didn't open a pull request immediately as I wasn't sure what the answer was here, and even if the current behaviour is not intended I'm not sure how best one would handle existing applications.

Thanks,
Josh

**Comment by rafaelfranca** [comment]
This is by design. It is perfectly fine to define an action on `ApplicationController`, it was never meant to be abstract, it is just a subclass.
