### ISSUE TITLE
Record is saved even if associated `belongs_to` record is invalid 

### ISSUE THREAD

**Issue by ojab** [rails/rails#30177]
### Steps to reproduce
https://gist.github.com/ojab/3f937dc236696c1cdbded879178a131b
tl;dr: we're calling `post.comments.first.save!` with invalid `post`.
  
### Expected behavior
`comment` is not saved.

### Actual behavior
`comment` is saved and we have invalid `Comment` in DB.

### System configuration
**Rails version**: 5.1.3, master

**Ruby version**: ruby 2.4.1p111 (2017-03-22 revision 58053) [x86_64-linux]

**Comment by Nocturne92** [comment]
By the looks of it, associated records will only be validated when a :validate => true or :autosave => true argument is passed to the belongs_to call. Passing either of those fixed it for me.

**Comment by sgrif** [comment]
As you have discovered yourself, this is the expected behavior.

**Comment by ojab** [comment]
Associated record is validated in reproducer even without `validate: true` and/or `autosave: true` (`post.errors` has our error after `post.comments.first.save!` is run in reproducer) and if we don't call `validate :invalidate` -- it's saved into DB and all works fine.

So either:
- `post` should be saved and we should raise if it can't be saved (i. e. validation fails)
- `post` should not be validated/saved and `post.comments.first.save!` should fail unconditionally in that case

I don't see how current behavior can be expected or useful to anyone.
