### ISSUE TITLE
ActiveRecord hitting wrong query match values in database for IS/IS NOT

### ISSUE THREAD

**Issue by om-nishu-trantor** [rails/rails#30178]
### Steps to reproduce
Have a Boolean field in you Model, fire the following query :-
`Model.where.not('boolean_field IS ?', true).count`

### Expected behavior
Should fire the following query :-
`SELECT COUNT(*) FROM "application_logs" WHERE (NOT (processed IS TRUE))`

### Actual behavior
Firing the following query :-
`SELECT COUNT(*) FROM "application_logs" WHERE (NOT (processed IS 't'))`

Returning Error :-
`ActiveRecord::StatementInvalid: PG::SyntaxError: ERROR: syntax error at or near "'t'"`

### System configuration
**Rails version**:
Rails 5.0.0.1
**Ruby version**:
Ruby 2.3.1

**Comment by matthewd** [comment]
This is [relatively] expected behaviour: `IS` is a special operator. It might possibly work differently (on some RDBMSes) with https://github.com/rails/rails/pull/29699, but that'd mostly be a side-effect.
