### ISSUE TITLE
`belongs_to` association is saved after record itself

### ISSUE THREAD

**Issue by ojab** [rails/rails#30181]
### Steps to reproduce
https://gist.github.com/ojab/d9314c42c0090fdcde83e8fe35d39ea2

### Expected behavior
Records are successfully saved

### Actual behavior
`parent` is saved after `link`, so we have `ActiveRecord::NotNullViolation: SQLite3::ConstraintException: NOT NULL constraint failed: links.parent_id: INSERT INTO "links" ("child_id") VALUES (?)`

### System configuration
**Rails version**: master, 5.1.3

**Ruby version**: ruby 2.4.1p111 (2017-03-22 revision 58053) [x86_64-linux]

**Comment by sgrif** [comment]
This is the expected behavior, unless you've specified `autosave: true`

**Comment by ojab** [comment]
Yout mean `autosave: true` on `belongs_to :parent` association? It doesn't work, `parent` is still saved after `link` and we have the same error.

**Comment by ojab** [comment]
Actually it _works_ without `autosave: true` if I rearrange `belongs_to` association declarations in `Link`, i. e. make `child` first:
```ruby
class Link < ActiveRecord::Base
  belongs_to :child, class_name: 'Comment', optional: false
  belongs_to :parent, class_name: 'Comment', optional: false
end
```
so it's clearly a bug.
