### ISSUE TITLE
`belongs_to` association's id is not present on record INSERT and added in subsequent UPDATE

### ISSUE THREAD

**Issue by ojab** [rails/rails#30182]
### Steps to reproduce
https://gist.github.com/ojab/8af49df12bdcd3ba0299e90ab1fb27fd

### Expected behavior
Records are successfully saved

### Actual behavior
Although `post` is created before `author` is saved, `post_id` is not present in `author` on create, so we have ` ActiveRecord::NotNullViolation: SQLite3::ConstraintException: NOT NULL constraint failed: authors.post_id: INSERT INTO "authors" DEFAULT VALUES`
If `null: false` constraint is removed from `authors` table, we can see that `author` is updated with proper `post_id` after all records are saved, i. e.:
```
DEBUG -- :   SQL (0.1ms)  INSERT INTO "posts" DEFAULT VALUES
DEBUG -- :   SQL (0.1ms)  INSERT INTO "comments" ("post_id") VALUES (?)  [["post_id", 1]]
DEBUG -- :   SQL (0.1ms)  INSERT INTO "authors" DEFAULT VALUES
DEBUG -- :   SQL (0.1ms)  INSERT INTO "links" ("comment_id", "author_id") VALUES (?, ?)  [["comment_id", 1], ["author_id", 1]]
DEBUG -- :   SQL (0.1ms)  UPDATE "authors" SET "post_id" = ? WHERE "authors"."id" = ?  [["post_id", 1], ["id", 1]]
```

### System configuration
**Rails version**: master, 5.1.3

**Ruby version**: ruby 2.4.1p111 (2017-03-22 revision 58053) [x86_64-linux]

**Comment by ojab** [comment]
(it can be solved by `autosave: true` on `belongs_to` association, but I believe that it should work without such change)

**Comment by sgrif** [comment]
This is the expected behavior.

**Comment by ojab** [comment]
...and looks like I've done something wrong when testing with `autosave: true` (it actually doesn't help).
Added `autosave: true` to the reproducer, it still fails with the same error.
I assume that it isn't expected behavior and really a bug.

**Comment by ojab** [comment]
...and `autosave: true` doesn't work if both `belongs_to` associations in `Link` are the same model: [reproducer](https://gist.github.com/ojab/852577a3abab37026932c50e40393792).
Looks like the same issue, but in this case without workarounds.
