### ISSUE TITLE
How can I use foreign_key: { to_table: :users }?

### ISSUE THREAD

**Issue by xuwupeng2000** [rails/rails#30187]
https://github.com/rails/rails/blob/a7d49ef78c36df2d1ca876451f30915ada1079a5/activerecord/lib/active_record/connection_adapters/abstract/schema_definitions.rb#L328

Did I just find a bug? How can I use foreign_key_options if to_table is just set by Base?
I want to use opt like:
foreign_key: { to_table: :users }

**Comment by rafaelfranca** [comment]
Please use the mailing list or StackOverflow for questions/help, where a wider community will be able to help you. We reserve the issues tracker for issues only.
