### ISSUE TITLE
validates :attribute, :format => { :with => REGEX}

### ISSUE THREAD

**Issue by SelinaChen07** [rails/rails#30194]
### Steps to reproduce
1. Build a model with integer attribute. For example,
$ rails generate model Product stock:integer
2. validate the model Product's stock attribute with below code:
validates :stock, :format => { :with => /\A\d+\z/}
3. In rails console, try to create a new record with invalid stock value. For example:
> p = Product.new(stock: "abcd")
> p.save
The new record was successfully saved by by-passing the format validation because input value "abcd" is type casted to integer 0 before validation is performed.

### Expected behavior
It's expected that the above new record(stock="abcd") is not valid. Similar errors should be checked by format validation.
Alternatively, when using below code, it is working as expected.
validates :stock, numericality:{only_integer: true}

### Actual behavior
Unlike numericality validation, which checks the attributes_before_type_cast, format validation checks the type-casted data. The different behaviors between these two validation method will cause confusion to developers.

### System configuration
**Rails version**:
Rails 5.0.4

**Ruby version**:
Ruby 2.2.2p95

**Comment by sevenseacat** [comment]
I think this will be marked 'working as intended'.

**Comment by rafaelfranca** [comment]
Yes, that is exactly the case. Format validation is not to be used for numeric values. We have a different validation for that.
