### ISSUE TITLE
Rails 5.1 redirect_to flash issue

### ISSUE THREAD

**Issue by clthck** [rails/rails#30207]
### Steps to reproduce

`users_controller.rb`
```rb
class UsersController < ApplicationController
  def update
    if @user.update(user_params)
      redirect_to action: 'show', notice: 'User saved!'
    end
  end
end
```

`application.html.slim`
```slim
- if notice.present?
  .message= notice
```

### Expected behavior
After successful update on `User` model, it should redirect to `show` and display `flash[:notice]` (or just `notice`).

### Actual behavior
Redirect works fine, but flash does not show up. Instead, browser url bar has some GET style querystring, e.g., `localhost:3000/users?notice=User+saved%21`

However, if I set flash in separate line (e.g., `flash[:notice] = 'User saved!'`) and remove `notice` param in `redirect_to`, flash notice displays properly.

### System configuration
**Rails version**: 5.1.2

**Ruby version**: 2.4.1p111

**Comment by y-yagi** [comment]
Action and flash need to be passed separately. Like following:

```ruby 
def update
  if @user.update(user_params)
    redirect_to({ action: 'show'}, notice: 'User saved!')
  end
end
``` 
Otherwise flash is considered an option for the URL. 

Ref: http://api.rubyonrails.org/classes/ActionController/Redirecting.html#method-i-redirect_to

**Comment by clthck** [comment]
Ah I see. Didn't notice about that before. Thank you!
