### ISSUE TITLE
ActiveJob's DelayedJob adapter lack of hooks support

### ISSUE THREAD

**Issue by FLemon** [rails/rails#30205]
Using ActiveJob with delayed_job adapter does not support some of delayed_job's native hooks, i.e. `#failure` and `#error`

### Steps to reproduce
define an class inherit from [ApplicationJob](http://edgeguides.rubyonrails.org/active_job_basics.html#create-the-job), and define a method `#failure(job)` 
.i.e 
```ruby
class ExampleJob < ApplicationJob
  def perform
  end

  def failure(job)
  end
end
```

Use :delayed_job as your active_job's queue_adapter, `config.active_job.queue_adapter = :delayed_job`

Install and setup the Rails app to use the [delayed_job](https://github.com/collectiveidea/delayed_job#installation).

Observe when a job reach its maximum retries(which is configured in delayed_job yml - `Delayed::Worker.max_attempts = 3`)

### Expected behavior
It should trigger the failure method defined in the job class

### Actual behavior
It does not trigger the failure, and in fact, the delayed_job checks if the payload_object(ActiveJob::QueueAdapters::DelayedJobAdapter::JobWrapper) respond_to :failure, only if yes it will call the `#failure` method

### System configuration
**Rails version**: 5.0.0

**Ruby version**: 2.3.1

### tests with patch
```ruby
begin
  require "bundler/inline"
rescue LoadError => e
  $stderr.puts "Bundler version 1.10 or later is required. Please update your Bundler"
  raise e
end

gemfile(true) do
  source "https://rubygems.org"
  # Activate the gem you are reporting the issue against.
  gem "activejob", "5.0.0.1"
  gem "delayed_job", "4.1.3"
  gem "delayed_job_active_record", "4.1.1"
  gem "sqlite3"
  gem "pry-byebug"
  # gem "pg", "0.19.0"
end

require "minitest/autorun"
require "active_job"
require "delayed_job"

# Ensure backward compatibility with Minitest 4
Minitest::Test = MiniTest::Unit::TestCase unless defined?(Minitest::Test)

ActiveRecord::Base.establish_connection(adapter: "sqlite3", database: ":memory:")
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :delayed_jobs, force: true do |table|
    table.integer :priority, default: 0, null: false # Allows some jobs to jump to the front of the queue
    table.integer :attempts, default: 0, null: false # Provides for retries, but still fail eventually.
    table.text :handler,                 null: false # YAML-encoded string of the object that will do work
    table.text :last_error                           # reason for last failure (See Note below)
    table.datetime :run_at                           # When to run. Could be Time.zone.now for immediately, or sometime in the future.
    table.datetime :locked_at                        # Set when a client is working on this object
    table.datetime :failed_at                        # Set when all retries have failed (actually, by default, the record is deleted instead)
    table.string :locked_by                          # Who is working on this object (if locked)
    table.string :queue                              # The name of the queue this job is in
    table.timestamps null: true
  end

  add_index :delayed_jobs, [:priority, :run_at], name: "delayed_jobs_priority"
end

# == start of the patch, uncomment it and test will pass ==
# module ActiveJob
#   module QueueAdapters
#     class DelayedJobAdapter
#       class JobWrapper
#         def failure(job)
#           job_data = Base.deserialize(job.payload_object.job_data)
#           job_data.failure(job) if job_data.respond_to?(:failure)
#         end
#       end
#     end
#   end
# end
# == end of the patch ==

class BuggyJob < ActiveJob::Base
  FAILURE_ERROR = "this job is dead, reached max attempts"

  def perform
    raise "single failure"
  end

  def failure(job)
    job.update_attributes!(last_error: FAILURE_ERROR)
  end
end

class BuggyJobTest < ActiveJob::TestCase
  def setup
    ActiveJob::Base.queue_adapter = :delayed_job
    Delayed::Worker.delay_jobs = true
    Delayed::Worker.destroy_failed_jobs = false
    Delayed::Worker.max_attempts = 2
  end

  def test_delayed_job_working_with_active_record
    job_count = Delayed::Job.count
    BuggyJob.perform_later
    assert_equal job_count + 1, Delayed::Job.count
  end

  def test_failure_hook_not_triggered_before_patch
    BuggyJob.perform_later
    job = Delayed::Job.last
    Delayed::Worker.max_attempts.times { Delayed::Worker.new.reschedule(job) }
    job.reload
    assert_equal 2, job.attempts
    assert_equal BuggyJob::FAILURE_ERROR, job.last_error
  end
end
```

**Comment by kirs** [comment]
The goal of ActiveJob is providing an abstraction for any adapter. AJ simply cannot support native features of every adapter like `failure` hook in DelayedJob.

If you want to catch exceptions that are raised in the job, you can use `rescue_from` that AJ [provides](http://edgeguides.rubyonrails.org/active_job_basics.html#exceptions).

**Comment by FLemon** [comment]
@kirs , I think I get your point, and it does make sense. But can you suggest how is it I can use `rescue_from` to do something when the maximum retries has reached, regardless what error the job raised, do I have to `rescue_from Exception`(it doesn't look right to rescue Exception, but I don't know what other ways) ?

**Comment by rafaelfranca** [comment]
I'm closing this since as @kirs explained this is not something Active Job will support. But feel free to continue discussing how to implement that here.

**Comment by kirs** [comment]
@FLemon [`retry_on`](http://api.rubyonrails.org/classes/ActiveJob/Exceptions/ClassMethods.html#method-i-retry_on) is probably the method of AJ that you're looking for. It accepts a block of code to execute when the maximum retries has reached. Hope it helps!

**Comment by FLemon** [comment]
@kirs ah, thanks, so i can't do much about it for now(as i am on Rails 5.0.0.1)

**Comment by JohnSmall** [comment]
ActiveJob is an abstraction layer, but the DelayedJob adapter is meant to work only with DelayedJob and this patch is only for the adapter code.

Since there is other code specific to DelayedJob in the DelayedJob adapter I don't see the problem adding this patch.
