### ISSUE TITLE
Arel display data

### ISSUE THREAD

**Issue by a0t0a** [rails/rails#30254]
### Steps to reproduce
This table

 class Post < ApplicationRecord
  has_many :post_categories, dependent: :delete_all
  has_many :categories, through: :post_categories

  Post_Table = Post.arel_table
  Category_Table = Category.arel_table
  PostCategory_Table = PostCategory.arel_table

  scope :announce, -> {Post_Table.project(Post_Table[Arel.star]).where(Post_Table[:id].eq(1))}

end

class Category < ApplicationRecord
  has_many :post_categories, dependent: :delete_all
  has_many :posts, through: :post_categories
end

class PostCategory < ApplicationRecord
  belongs_to :post
  belongs_to :category
end
(Guidelines for creating a bug report are [available
here](http://guides.rubyonrails.org/contributing_to_ruby_on_rails.html#creating-a-bug-report))

### Expected behavior
Tell us what should happen
My data example
[34] pry(main)> tp Post.all
  Post Load (0.5ms)  SELECT "posts".* FROM "posts"
ID | TITLE            | BODY      | CREATED_AT              | UPDATED_AT            
---|------------------|-----------|-------------------------|------------------------
4  | Primer registro  | Con Ruby  | 2017-08-08 13:56:41     | 2017-08-08 13:56:41   
5  | Segundo registro | Con Rails | 2017-08-08 13:56:53     | 2017-08-08 13:56:53   
6  | Tercer registro  | Con todos | 2017-08-08 13:57:44     | 2017-08-08 13:57:44   
=> #<TablePrint::Returnable:0x27d4c70>

[35] pry(main)> tp Category.all
  Category Load (0.6ms)  SELECT "categories".* FROM "categories"
ID | NAME  | DESCRIPTION           | CREATED_AT              | UPDATED_AT            
---|-------|-----------------------|-------------------------|------------------------
1  | Ruby  | Lenguaje Programacion | 2017-08-08 12:37:43     | 2017-08-08 12:37:43   
2  | Rails | Framework             | 2017-08-08 12:37:50     | 2017-08-08 12:37:50   
3  | Perl  | Lenguaje Programacion | 2017-08-08 12:37:59     | 2017-08-08 12:37:59   
=> #<TablePrint::Returnable:0x23fcc9c>

[36] pry(main)> tp PostCategory.all
  PostCategory Load (1.0ms)  SELECT "post_categories".* FROM "post_categories"
ID | POST_ID | CATEGORY_ID | CREATED_AT              | UPDATED_AT            
---|---------|-------------|-------------------------|------------------------
6  | 4       | 1           | 2017-08-08 13:56:41     | 2017-08-08 13:56:41   
7  | 5       | 2           | 2017-08-08 13:56:53     | 2017-08-08 13:56:53   
8  | 6       | 1           | 2017-08-08 13:57:44     | 2017-08-08 13:57:44   
9  | 6       | 2           | 2017-08-08 13:57:44     | 2017-08-08 13:57:44   
10 | 6       | 3           | 2017-08-08 13:57:44     | 2017-08-08 13:57:44   
=> #<TablePrint::Returnable:0x22d6e94>

### Actual behavior
Tell us what happens instead
But, when from console I call it is scope me this appears

[1] pry(main)> Post.announce
=> #<Arel::SelectManager:0x000000055fd318
 @ast=
  #<Arel::Nodes::SelectStatement:0x000000055fd2c8
   @cores=
    [#<Arel::Nodes::SelectCore:0x000000055fd2a0
      @groups=[],
      @havings=[],
      @projections=
       [#<struct Arel::Attributes::Attribute
         relation=
          #<Arel::Table:0x00000005718a90
           @name="posts",
           @table_alias=nil,
           @type_caster=
            #<ActiveRecord::TypeCaster::Map:0x00000005718ae0
             @types=Post (call 'Post.connection' to establish a connection)>>,
         name="*">],
      @set_quantifier=nil,
      @source=
       #<Arel::Nodes::JoinSource:0x000000055fd278
        @left=
         #<Arel::Table:0x00000005718a90
          @name="posts",
          @table_alias=nil,
          @type_caster=
           #<ActiveRecord::TypeCaster::Map:0x00000005718ae0
            @types=Post (call 'Post.connection' to establish a connection)>>,
        @right=[]>,
      @top=nil,
      @wheres=
       [#<Arel::Nodes::Equality:0x000000055fcfa8
         @left=
          #<struct Arel::Attributes::Attribute
           relation=
            #<Arel::Table:0x00000005718a90
             @name="posts",
             @table_alias=nil,
             @type_caster=
              #<ActiveRecord::TypeCaster::Map:0x00000005718ae0
               @types=Post (call 'Post.connection' to establish a connection)>>,
           name=:id>,
         @right=
          #<Arel::Nodes::Casted:0x000000055fcff8
           @attribute=
            #<struct Arel::Attributes::Attribute
             relation=
              #<Arel::Table:0x00000005718a90
               @name="posts",
               @table_alias=nil,
               @type_caster=
                #<ActiveRecord::TypeCaster::Map:0x00000005718ae0
                 @types=Post (call 'Post.connection' to establish a connection)>>,
             name=:id>,
           @val=1>>],
      @windows=[]>],
   @limit=nil,
   @lock=nil,
   @offset=nil,
   @orders=[],
   @with=nil>,
 @bind_values=[],
 @ctx=
  #<Arel::Nodes::SelectCore:0x000000055fd2a0
   @groups=[],
   @havings=[],
   @projections=
    [#<struct Arel::Attributes::Attribute
      relation=
       #<Arel::Table:0x00000005718a90
        @name="posts",
       @name="posts",
       @table_alias=nil,
       @type_caster=
        #<ActiveRecord::TypeCaster::Map:0x00000005718ae0 @types=Post (call 'Post.connection' to establish a connection)>>,
     @right=[]>,
   @top=nil,
   @wheres=
    [#<Arel::Nodes::Equality:0x000000055fcfa8
      @left=
       #<struct Arel::Attributes::Attribute
        relation=
         #<Arel::Table:0x00000005718a90
          @name="posts",
          @table_alias=nil,
          @type_caster=
           #<ActiveRecord::TypeCaster::Map:0x00000005718ae0
            @types=Post (call 'Post.connection' to establish a connection)>>,
        name=:id>,
      @right=
       #<Arel::Nodes::Casted:0x000000055fcff8
        @attribute=
         #<struct Arel::Attributes::Attribute
          relation=
           #<Arel::Table:0x00000005718a90
            @name="posts",
            @table_alias=nil,
            @type_caster=
             #<ActiveRecord::TypeCaster::Map:0x00000005718ae0
              @types=Post (call 'Post.connection' to establish a connection)>>,
          name=:id>,
        @val=1>>],
   @windows=[]>>
(END)

[2] pry(main)> Post.announce.class
=> Arel::SelectManager

Because I do not see the information

### System configuration
**Rails version**:
Rails 5.1.3
**Ruby version**:
ruby 2.4.0p0 (2016-12-24 revision 57164) [x86_64-linux]

**Comment by rafaelfranca** [comment]
Arel is not part of the public API of Rails, so we don't support its usage. You scope is returning a Arel SelectManager instead of a ActiveRecord::Relation and it should always return an ActiveRecord::Relation.
