### ISSUE TITLE
Attributes API: Attribute casting and serializing not taken into account for queries with relations that specify a class_name.

### ISSUE THREAD

**Issue by markoudev** [rails/rails#30278]
### Steps to reproduce
*See attached tests below.*

1. Create two models with a `has_many` and `belongs_to` relation between them, and add a binary column named `uuid` to their schemas.
1. Make sure that the relation between those models is named differently from the model, and specifies the model with `class_name: ...`.
1. Use [mysql-binuuid-rails](https://github.com/nedap/mysql-binuuid-rails), which registers a `uuid` attribute with ActiveRecord and allows UUIDs to be stored as binary values in the database.
1. Specify `attribute :uuid, MySQLBinUUID::Type.new` in the two models.
1. Go make queries using `.joins(:model).where(other_model: { uuid: ... })` and see it fail

### Expected behavior
When specifying an attribute in a model, the casting and serializing behaviour should be taken into account with `where` statements in combination with a `join`. In this example with UUIDs, I would expect a query to be executed in which the value of the UUID column is the hex value of the uuid.

### Actual behavior
It seems that when a `class_name` is specified with the relation, this does not work anymore. A query is executed where the value of the uuid is just its string value.

*I've included two sample tests in the Ruby code below, in which the second test illustrates the issue.*

### System configuration
**Rails version**: `master`
**Ruby version**: 2.4.1

### 
```ruby
# frozen_string_literal: true

begin
  require "bundler/inline"
rescue LoadError => e
  $stderr.puts "Bundler version 1.10 or later is required. Please update your Bundler"
  raise e
end

gemfile(true) do
  source "https://rubygems.org"
  gem "rails", github: "rails/rails"
  gem "arel", github: "rails/arel"
  gem "mysql2"
  gem "mysql-binuuid-rails", require: false
  gem "minitest-hooks"
end

require "active_model"
require "active_record"
require "minitest/autorun"
require "minitest/hooks"
require "logger"
require "mysql-binuuid-rails"

ActiveRecord::Base.establish_connection(adapter: "mysql2", username: "root")
ActiveRecord::Base.connection.drop_database("class_name_issue") rescue nil
ActiveRecord::Base.connection.create_database("class_name_issue")

ActiveRecord::Base.establish_connection(adapter: "mysql2", username: "root", database: "class_name_issue")
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :posts, force: true do |t|
    t.binary :uuid, limit: 16
  end

  create_table :comments, force: true do |t|
    t.integer :post_id
    t.binary :uuid, limit: 16
  end

  create_table :my_authors, force: true do |t|
    t.binary :uuid, limit: 16
  end

  create_table :my_books, force: true do |t|
    t.integer :my_author_id
    t.binary :uuid, limit: 16
  end
end

# To create an example that shows expected behaviour
class Post < ActiveRecord::Base
  attribute :uuid, MySQLBinUUID::Type.new
  has_many :comments
end
class Comment < ActiveRecord::Base
  attribute :uuid, MySQLBinUUID::Type.new
  belongs_to :post
end

# To create an example that shows unexpected behaviour
class MyAuthor < ActiveRecord::Base
  attribute :uuid, MySQLBinUUID::Type.new
  has_many :books, class_name: "MyBook"
end
class MyBook < ActiveRecord::Base
  attribute :uuid, MySQLBinUUID::Type.new
  belongs_to :author, class_name: "MyAuthor"
end

class BugTest < Minitest::Test
  include Minitest::Hooks

  def after_all
    ActiveRecord::Base.connection.drop_database("class_name_issue")
  end

  # This test shows expected behaviour
  def test_find_post_by_join_on_comment_and_uuid
    post_uuid = SecureRandom.uuid
    comment_uuid = SecureRandom.uuid

    post = Post.create!(uuid: post_uuid)
    comment = Comment.create!(uuid: comment_uuid, post_id: post.id)

    found_posts = Post.joins(:comments).where(comments: { uuid: comment_uuid })

    # The SQL generated by this expression is:
    #   SELECT COUNT(*)
    #   FROM `posts`
    #   INNER JOIN `comments` ON `comments`.`post_id` = `posts`.`id`
    #   WHERE `comments`.`uuid` = x'af924113926f49a9973d17a35fea7201'
    #
    # Which is exactly what should happen, since the uuid column is binary, and
    # the value in SQL should be the uuid without the dashes (which is the
    # binary representation of the uuid). It's what mysql-binuuid-rails does.
    assert_equal 1, found_posts.size

    # A similar query is generated for this one, works fine.
    assert_equal post, found_posts.first
  end

  # Well, this is unexpected
  def test_find_author_by_join_on_book_and_uuid_and_other_class_name
    post_uuid = SecureRandom.uuid
    comment_uuid = SecureRandom.uuid

    author = MyAuthor.create!(uuid: post_uuid)
    book = MyBook.create!(uuid: comment_uuid, my_author_id: author.id)

    found_authors = MyAuthor.joins(:books).where(my_books: { uuid: comment_uuid })

    # The SQL generated by this expression is:
    #   SELECT COUNT(*)
    #   FROM `my_authors`
    #   INNER JOIN `my_books` ON `my_books`.`my_author_id` = `my_authors`.`id`
    #   WHERE `my_books`.`uuid` = '026876d9-d3dd-4b15-9b2b-4019fb74680b'
    #
    # Which is unexpected. The UUID here is treated as a string, while the
    # MyBook model described the UUID attribute to be of a certain type. I would
    # have expected x'026876d9d3dd4b159b2b4019fb74680b' as the value for the
    # UUID here.
    assert_equal 1, found_authors.size

    assert_equal author, found_authors.first
  end

  # A work-around that works
  def test_specifying_the_attribute_type_workaround_works
    post_uuid = SecureRandom.uuid
    comment_uuid = SecureRandom.uuid

    author = MyAuthor.create!(uuid: post_uuid)
    book = MyBook.create!(uuid: comment_uuid, my_author_id: author.id)

    found_authors = MyAuthor.joins(:books).where(my_books: { uuid: MySQLBinUUID::Type.new.serialize(comment_uuid) })

    # The SQL generated by this expression is:
    #   SELECT COUNT(*)
    #   FROM `my_authors`
    #   INNER JOIN `my_books` ON `my_books`.`my_author_id` = `my_authors`.`id`
    #   WHERE `my_books`.`uuid` = x'026876d9d3dd4b159b2b4019fb74680b'
    #
    # This works, but is not desirable.
    assert_equal 1, found_authors.size

    assert_equal author, found_authors.first
  end
end
```

**Comment by chopraanmol1** [comment]
Hey, I've looked into it.
if you try
`MyAuthor.joins(:books).where(books: { uuid: comment_uuid })`
then uuid will be properly typecasted but it will lead to another issue in which where condition will have books.uuid rather than my_books.uuid

So actual issue is that whenever you use different class_name in that case wrong alias is used while building query. I'm creating a PR to fix that.

**Comment by sgrif** [comment]
Unfortunately this is the expected behavior for the time being. Since `where` focuses on the table name rather than the association name, and it is possible to have more than one association to the same table but with different classes, we can only assume that the class referenced by an association should be used when the table name and association name are the same. We may change this in the future by allowing you to *always* specify the association name, but that is a breaking change that we aren't looking to make at this point in time.

See https://github.com/rails/rails/commit/6a6c4c459106e2d9b76dd1233133a2bf30866ab0 and #20308 for more details.

**Comment by markoudev** [comment]
Thanks for your explanation @sgrif and references to the commit in which you explain this even more accurately. It explains why the table name should be used with `where`. I'm not entirely sure yet on how this relates to specific attribute types not being taken into account.

I'm okay with specifying the table name in the `where` statement, but in that case the custom attribute serialization and casting seems not to be taken into account. Is that an expected side-effect?

**Comment by sgrif** [comment]
It is expected that the type used would be based on the database type in this case. `where` doesn't know to use a type from your model class, because it is does not know that you are trying to reference that association.
