### ISSUE TITLE
Rails route URL helpers do not handle strong parameters `format` correctly

### ISSUE THREAD

**Issue by codeodor** [rails/rails#30273]
### Steps to reproduce

```
git clone https://github.com/codeodor/rails-issue-with-format
cd rails-issue-with-format
rails s
open http://localhost:3000/tests
```

### Expected behavior
The two URLs output should be identical.

### Actual behavior
The first example sticks a parameter in the URL for `format` instead of changing the extension. 

Rails' controllers behave fine when responding to these links -- the controller still responds with the requested format. But [Turbolinks does not see this as an extension it should avoid, which causes it to send a request with a different format than the server responds with](https://github.com/turbolinks/turbolinks/issues/315).

### System configuration
**Rails version**: 5.1.3

**Ruby version**: 2.3.0

**Comment by lugray** [comment]
I can reproduce:

```ruby
begin
  require "bundler/inline"
rescue LoadError => e
  $stderr.puts "Bundler version 1.10 or later is required. Please update your Bundler"
  raise e
end

gemfile(true) do
  source "https://rubygems.org"
  gem "rails", github: "rails/rails"
  gem "arel", github: "rails/arel"
end

require "action_controller/railtie"

class TestApp < Rails::Application
  config.root = __dir__
  secrets.secret_token    = "secret_token"
  secrets.secret_key_base = "secret_key_base"

  config.logger = Logger.new($stdout)
  Rails.logger  = config.logger

  routes.draw do
    resources :tests, only: [:index]
  end
end

class TestController < ActionController::Base
  include Rails.application.routes.url_helpers

  def index
    render plain: "Home"
  end
end

require "minitest/autorun"
require "rack/test"

class BugTest < Minitest::Test
  include Rack::Test::Methods
  include Rails.application.routes.url_helpers

  def test_returns_success
    param_hash = { location_id: 10, format: 'pdf' }
    params = ActionController::Parameters.new(param_hash).permit!

    hash_path = tests_path(param_hash)
    params_path = tests_path(params)

    assert_equal hash_path, params_path
  end

  private
    def app
      Rails.application
    end
end
```

**Comment by codeodor** [comment]
Thanks for doing that @lugray.

**Comment by albertoalmagro** [comment]
I could also reproduce it. Would you like me to try to provide a fix for this?

**Comment by lugray** [comment]
@albertoalmagro sure!  A little more from my investigation that I didn't post yesterday: you get the same (wrong) path for `{ "location_id" => 10, "format" => "pdf" }`.  `ActionController::Parameters` becomes a HWIDA, and somewhere down the road through merges with plain hashes it becomes a plain hash with a string key `"format"`, since `{}.merge({foo: :bar}.with_indifferent_access)` is a plain hash `{"foo"=>:bar}`.

**Comment by albertoalmagro** [comment]
Then I will start figuring out what happened here. Thanks @lugray !

**Comment by albertoalmagro** [comment]
I think this may not be a bug. Since Rails 5.0 is recommended to provide full params hash explicitly. If you do the following you will get the same paths generated:

```
param_hash = { params: { location_id: 10, format: 'pdf' } }
params = ActionController::Parameters.new({ location_id: 10, format: 'pdf' }).permit!

hash_path = tests_path(param_hash)
params_path = tests_path(params)

puts hash_path
puts params_path
```
Results:
```
/tests?format=pdf&location_id=10
/tests?format=pdf&location_id=10
```

**Comment by lugray** [comment]
It still seems to me that `tests_path({"format" => "pdf"})` should give `/tests.pdf`.

**Comment by codeodor** [comment]
@albertoalmagro, maybe I should improve the description. Those results are indeed identical, but as @lugray points out, they are incorrect.

I think the result should be that the file extension is modified by the format key.

**Comment by lugray** [comment]
They're not both incorrect: `tests_path("params" => {"format" => "pdf"})` should give `/tests?format=pdf`

**Comment by codeodor** [comment]
Gotcha. I didn't read as closely as I should have. I saw the output and assumed it was following my example. Sorry for confusing the matter!

**Comment by codeodor** [comment]
Ideally I would love to see a fix, because I've seen this pattern a lot in the dozens of Rails apps I've worked on, and I think there's probably a lot of people's apps that are broken in these parts when they upgrade, and probably without anyone noticing before users might report it. 

But if not a fix, I could see it being helpful if there was a big warning when detecting any keys that used to work in the options hash that no longer work when you pass in an `ActionController::Parameters` without knowing it.

**Comment by albertoalmagro** [comment]
@codeodor I remember when I upgraded to Rails 5.0 having seen a deprecation warning at my tests. I can search in code where it was if you want to.

**Comment by codeodor** [comment]
Now that you mention it, I seem to recall something too. But if Rails is not going to do the expected thing when generating the URL, should it at least be consistent in what it interprets in the params passed to the controller?

I think that would be a worse solution, since it just involves more breakage. But I don't understand why it's ignoring the format in one place and accepting it in another.

**Comment by codeodor** [comment]
(Note that I mean I seem to recall it when upgrading to Rails 5, but this project went from 4.2 to 5.1, skipping 5 -- so I didn't notice it here, but in another project).

**Comment by albertoalmagro** [comment]
@codeodor if you try this in a Rails 5.0 app you would get the following:
```
DEPRECATION WARNING: Using positional arguments in functional tests has been deprecated,
in favor of keyword arguments, and will be removed in Rails 5.1.

Deprecated style:
get :show, { id: 1 }, nil, { notice: "This is a flash message" }

New keyword style:
get :show, params: { id: 1 }, flash: { notice: "This is a flash message" },
  session: nil # Can safely be omitted.
```
Upgrading right to 5.1 may have been the cause you didn't notice this.

**Comment by codeodor** [comment]
@albertoalmagro Is that what I was thinking of? If so, I think I was wrong. Because I definitely remember that, and I had to fix all my tests. However, as near as I can tell, there was no such requirement to use keyword arguments in route url helpers (that I recall, and certainly it is not erroring-out without them).

**Comment by albertoalmagro** [comment]
@codeodor You are right, this was only for tests.

I would like someone else to also take a look at this before I start fixing it and to confirm what should be the expected outcome.
