### ISSUE TITLE
Problem with datatype serial in postgres

### ISSUE THREAD

**Issue by alencarandre** [rails/rails#30298]
I am using rails 5.3.1 with ruby 2.4.1p111 (2017-03-22 revision 58053) [x86_64-darwin16]

Well, I create this migration
```ruby
class CreateUsers < ActiveRecord::Migration[5.0]
  def change
    create_table :users do |t|
      t.string  :login,              null: false,  index: true
      t.string  :name,               null: false, limit: 100
      t.string  :email,              null: false, limit: 100
      t.string  :crypted_password,   null: false
      t.timestamps
    end
  end
end
```
And than I have run rake db:migrate and ok. After that was generated this schema
```ruby
  create_table "users", id: :serial, default: %q{nextval('users_id_seq'::regclass)}, force: :cascade do |t|
    t.string   "login",               :null=>false, :index=>{:name=>"index_users_on_login"}
    t.string   "name",                :limit=>100, :null=>false
    t.string   "email",               :limit=>100, :null=>false
    t.string   "crypted_password",    :null=>false
    t.datetime "created_at",          :null=>false
    t.datetime "updated_at",          :null=>false
  end
```

If I run `rake db:setup` or `rake db:schema:load`, give me this error:
```
ActiveRecord::StatementInvalid: PG::UndefinedObject: ERROR:  type "serial" does not exist
LINE 1: SELECT 'serial'::regtype::oid
               ^
: SELECT 'serial'::regtype::oid
```

I am using postgres 9.6.2

Best regards

**Comment by lugray** [comment]
You say you're using rails 5.3.1, but that's not released.  Are you using 5.1.3?  If so, you should be using `ActiveRecord::Migration[5.1]`.  In any case, I cannot reproduce this.

**Comment by alencarandre** [comment]
Ow, I am sorry.

Thanks

**Comment by BroiSatse** [comment]
Hi guys, I am having exactly same problem now (rails 5.1.3 + ruby 2.4.1p111). It seems to be related to schema dumper (db:schema:load heavily modifies create_table options on my machine adding `id: :serial` and default key) which later on breaks the schema loading. Any ideas what could cause it?

**Comment by BroiSatse** [comment]
Ok, after some more digging it seems that the issue is caused by `schema_plus_indexes` gem.
