### ISSUE TITLE
mysql utf8mb4 string lengths should be 191 by default

### ISSUE THREAD

**Issue by dpogue** [rails/rails#30305]
### Steps to reproduce
When using MySQL with utf8mb4, the following migration fails when it tries to add the index:

```ruby
class CreateCustomers < ActiveRecord::Migration[5.1]
  def change
    create_table :customers do |t|
      t.string :name

      t.timestamps
    end

    add_index :customers, :name, unique: true
  end
end
```

### Expected behavior
The name column should default to a length of 191 so that it can be indexed, rather than 255.

### Actual behavior
The name column defaults to a length of 255 and is unindexable.

### Workarounds
We've been adding this code to the top of every migration file to work around this issue:

```ruby
## This should really be part of ActiveRecord, but it isn't :(
if ActiveRecord::Base.connection.instance_variable_get(:@config)[:encoding] == 'utf8mb4'
  ActiveRecord::ConnectionAdapters::AbstractMysqlAdapter::NATIVE_DATABASE_TYPES[:string][:limit] = 191
end
```

### System configuration
**Rails version**: 5.1.3

**Ruby version**: 2.4.0

**MySQL version**: 5.5.56

**Comment by rafaelfranca** [comment]
Thank you for the issue but this is a limitation in the MySQL version you are using. Modern MySQL servers don't have this limitation anymore Rails should not dealing with this/
