### ISSUE TITLE
The "learn more" links in active record readme have broken

### ISSUE THREAD

**Issue by tammy-txt** [rails/rails#30306]
### Steps to reproduce
Click the "learn more" link in Active Record Readme

### Expected behavior
Show me the detail page.

### Actual behavior
404

**Comment by albertoalmagro** [comment]
Thanks @tammy-txt 
I can reproduce it, also in ActiveModel.

* [ActiveRecord](https://github.com/rails/rails/tree/master/activerecord)
* [ActiveModel](https://github.com/rails/rails/tree/master/activemodel)

**Comment by kamipo** [comment]
Looks like that viewing on GitHub is out of expectation for README.rdoc.
 
http://api.rubyonrails.org/files/activerecord/README_rdoc.html

**Comment by albertoalmagro** [comment]
Yes @kamipo, but we don't give any hint about that. Do you think it is worth to add a hint with a link pointing to the API docs?

**Comment by kamipo** [comment]
Seems a good idea.

**Comment by albertoalmagro** [comment]
I will take care of it.

**Comment by matthewd** [comment]
@robin850 can we change these to full `api.` links now?

**Comment by albertoalmagro** [comment]
@matthewd That would be even better

**Comment by albertoalmagro** [comment]
I opened a PR with absolute links to api.rubyonrails.org #30312

**Comment by robin850** [comment]
> can we change these to full `api.` links now?

If you are referring to #27232, this was only for guides. If we want to make sure that these links won't redirect to a forward version of the API when someone browses documentation for a previous version of Rails, we will have to hook into SDoc/RDoc -- there's nothing to prevent this at the moment. I can work on that unless someone else wants to take a stab at it.

**Comment by matthewd** [comment]
Ah, right. Yeah, that'd be great, thanks! :heart:

Linking to `api.` from inside API docs is a pretty niche requirement -- for anything other than these readmes, a relative link would presumably be just fine -- but I assume the same effort would allow us to link to [version-appropriate] `guides.` URLs too, which does sound useful.

**Comment by albertoalmagro** [comment]
We can close this issue.
