### ISSUE TITLE
Time attributes contain different values before and after reloading from DB

### ISSUE THREAD

**Issue by marz0** [rails/rails#30301]
### Steps to reproduce
```ruby
# frozen_string_literal: true

begin
  require "bundler/inline"
rescue LoadError => e
  $stderr.puts "Bundler version 1.10 or later is required. Please update your Bundler"
  raise e
end

gemfile(true) do
  source "https://rubygems.org"
  gem "rails", github: "rails/rails"
  gem "arel", github: "rails/arel"
  gem "sqlite3"
end

require "active_record"
require "minitest/autorun"
require "logger"

# This connection will do for database-independent bug reports.
ActiveRecord::Base.establish_connection(adapter: "sqlite3", database: ":memory:")
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :posts, force: true do |t|
    t.timestamps null: false
  end
end

class Post < ActiveRecord::Base
end

class BugTest < Minitest::Test
  def test_association_stuff
    post = Post.create!

    assert_equal post.created_at, post.reload.created_at
    assert_equal post.updated_at, post.reload.updated_at
  end
end

```

### Expected behavior
The `created_at` and `updated_at` times *should* be the same before and after reloading the record from the database. 

### Actual behavior
The `created_at` and `updated_at` times display different values before and after reloading. This can be seen when comparing the values for `post.created_at.nsec` and `post.reload.created_at.nsec`.

### System configuration
**Rails version**: 5.1.2

**Ruby version**: `ruby 2.2.2p95 (2015-04-13 revision 50295) [x86_64-linux-gnu]` on RHEL6.

**NOTE:** This spec passes when using `ruby 2.2.2p95 (2015-04-13 revision 50295) [x86_64-darwin15]` on macOS.

**Comment by lugray** [comment]
I can reproduce on Ubuntu with `ruby 2.3.3p222 (2016-11-21 revision 56859) [x86_64-linux]`

**Comment by lugray** [comment]
To see the issue on other platforms (Im' working on a fix):
```ruby
# frozen_string_literal: true

begin
  require "bundler/inline"
rescue LoadError => e
  $stderr.puts "Bundler version 1.10 or later is required. Please update your Bundler"
  raise e
end

gemfile(true) do
  source "https://rubygems.org"
  gem "rails", github: "rails/rails"
  gem "arel", github: "rails/arel"
  gem "sqlite3"
end

require "active_record"
require "minitest/autorun"
require "logger"

# This connection will do for database-independent bug reports.
ActiveRecord::Base.establish_connection(adapter: "sqlite3", database: ":memory:")
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :posts, force: true do |t|
    t.datetime :mytime
  end
end

class Post < ActiveRecord::Base
end

class BugTest < Minitest::Test
  def test_association_stuff
    post = Post.create!(mytime: Time.now.change(nsec: 123456789))

    assert_equal post.mytime, post.reload.mytime
  end
end
```

**Comment by al2o3cr** [comment]
Away from a machine to try this on right now, but does adding `precision: 6` to the column definition change this behavior? Seems like that was the intent, based on discussion here:

https://github.com/rails/rails/pull/22381#issuecomment-160662074

**Comment by lugray** [comment]
That does fix it, but I have sympathy with the position that it ought not to default to the maximum precision provided in the setter, but the maximum precision supported by the database column.

**Comment by htanata** [comment]
I think this is the same as #31560. It's considered an expected behavior because [Ruby's subsecond precision is higher than what the database is capable of storing](https://github.com/rails/rails/issues/31560#issuecomment-353891545).
