### ISSUE TITLE
Document how to provide both query string and body when posting in an integration test

### ISSUE THREAD

**Issue by duane** [rails/rails#30316]
### Steps to reproduce

Go to [the documentation page](http://api.rubyonrails.org/v5.1/classes/ActionDispatch/IntegrationTest.html).

### Expected behavior

I should be able to see the documentation for `post` and `get`—particularly, a) whether the `params` keyword maps to the query string or to the request body and b) how to specify the other option. In fact, `GET` is rather unusual in being the only request type you might expect to only have a single way to pass parameters.

### Actual behavior

There are just examples, none of which explain the expected behavior of the method, let alone talk about the `params` keyword. In fact, I am not seeing any evidence you can pass *any type of query string* to a `POST` request.

### System configuration
**Rails version**:

5.1

**Ruby version**:

2.3

**Comment by rafaelfranca** [comment]
params is always the body. Query string you pass in the query sting.

**Comment by rafaelfranca** [comment]
```
post "/login?my_query_string=1"
```
