### ISSUE TITLE
"Ambiguous route definition" error in Rails 5.1.3

### ISSUE THREAD

**Issue by roberts1000** [rails/rails#30321]
### Steps to reproduce

Add the following to a new Rails 5.1.3 project

```ruby
get 'terms_of_use', to: 'pages#terms_of_use', path: "terms-of-use"
```

Start the rails server,

### Expected behavior

The rails server should start.

### Actual behavior

The rails server crashes with the following message

```bash
/home/dev/.rvm/gems/ruby-2.3.3/gems/actionpack-5.1.3/lib/action_dispatch/routing/mapper.rb:1852:in `block in map_match': Ambigous route definition. Both :path and the route path where specified as strings. (ArgumentError)
```

In addition to the error itself, "Ambigous" is misspelled and "where" is used incorrectly in the error message.  The above route definition works correctly in Rails 5.0.5.

### System configuration
**Rails version**: 5.1.3

**Ruby version**: 2.3.4

**Comment by zokioki** [comment]
Passing `:path` and route path as strings appears to have been fully deprecated via https://github.com/rails/rails/commit/9185b68cc652a113a85e29c8d6f7655f360cbedb.

**Comment by kamipo** [comment]
Yeah, please use `get "terms-of-use", to: "pages#terms_of_use"` instead.

**Comment by roberts1000** [comment]
Thank You
