### ISSUE TITLE
Consistent quotes in generated files

### ISSUE THREAD

**Issue by zachahn** [rails/rails#30327]
When creating a new Rails app, one of the first things I do is install Rubocop and swap all the single quotes with double quotes.

I noticed that the Rails `.rubocop.yml` itself also prefers double quotes. Would the maintainers be okay if I opened a PR to change all the single quotes of the generated files to double quotes?

I know this is a basically a cosmetic change, but since this is dealing with generated files, this is code that developers look at without looking into the Rails gems. Although the argument between single vs double quotes can get pretty heated 😨, I was hoping that we could agree that consistency was a win we could all agree on! :p

If this is something we'd be interested in, I'll happily put together a PR!

**Comment by syedfazilbasheer** [comment]
I thought the community Ruby style guide prefers single quotes.

**Comment by georgeclaghorn** [comment]
The generated files are fine as they are.
