### ISSUE TITLE
ActiveSupport 5.0.5 different loading logic for 'app/lib' and 'lib' dirs

### ISSUE THREAD

**Issue by kinnrot** [rails/rails#30334]
### Steps to reproduce

new rails app with rspec 

add cats_controller.rb to controllers
```
class CatsController < ApplicationController
  def index
  end
end

```

add a Cat Class under lib/space/
```
module Space
  class Cat
  end
end

```

configure application.rb to autoload lib
`config.autoload_paths += Dir["#{config.root}/lib/**/"]`

add following spec cats_controller_spec.rb
```
require 'rails_helper'

RSpec.describe CatsController, type: :controller do
  it 'should do something' do
    request.headers["Content-Type"] = 'application/json' # critical for test to fail
    get :index
  end
end

```
### Expected behavior
Test should pass

### Actual behavior

>LoadError: Unable to autoload constant Cat, expected /ruby/rspeccontroller/lib/space/cat.rb to define it
./spec/cats_controller_spec.rb:7:in `block (2 levels) in <top (required)>'
-e:1:in `load'
-e:1:in `<main>'

If I move the Space::Cat to app/lib the test pass, I'd like to understand why.

### System configuration
**Rails version**: 5.0.5

**Ruby version**: 2.3.3

**Comment by serihiro** [comment]
@kinnrot
This worked for me.

```ruby
config.autoload_paths << config.root.join('lib')
```

or

```ruby
config.autoload_paths += %W(#{config.root}/lib)
```

If you add `Dir["#{config.root}/lib/**/"]` to `config.autoload_paths` in `config/application.rb`,
all directories that are located under `app/lib` are defined as autoload_paths recursively.

```sh
$ bin/rails r 'puts ActiveSupport::Dependencies.autoload_paths'
cat_rails/lib/
cat_rails/lib/assets/
cat_rails/lib/space/
cat_rails/lib/tasks/
cat_rails/app/assets
cat_rails/app/channels
cat_rails/app/controllers
cat_rails/app/controllers/concerns
cat_rails/app/helpers
cat_rails/app/jobs
cat_rails/app/mailers
cat_rails/app/models
cat_rails/app/models/concerns
cat_rails/spec/mailers/previews
```

It looks like that `lib/space` works as a root directory of modules (as well as `app/models` , `app/controllers` , etc.).
So you cannot define `Space::Cat` class under the `lib/space/cat.rb` directories.
It looks like that Rails considers `Cat` class is defined in `lib/space/cat.rb`, not `Space::Cat`.

But if you add `%W(#{config.root}/lib)` to `config.autoload_paths` in `config/application.rb`,
it looks like that rails adds only `lib` directory as a root directory of modules.

```sh
$ bin/rails r 'puts ActiveSupport::Dependencies.autoload_paths'
cat_rails/lib
cat_rails/app/assets
cat_rails/app/channels
cat_rails/app/controllers
cat_rails/app/controllers/concerns
cat_rails/app/helpers
cat_rails/app/jobs
cat_rails/app/mailers
cat_rails/app/models
cat_rails/app/models/concerns
cat_rails/spec/mailers/previews
```

So you can define `Space::Cat` at `lib/space/cat.rb`

I hope this experiment will help you.

**Comment by kinnrot** [comment]
Yes, thanks for clearing that up.

**Comment by kinnrot** [comment]
Is there any place I can find docs about "root directory for modules"

**Comment by hjijin** [comment]
In order to load `app/lib` folder, this worked for me：
 change ` require 'rails'` to  `require 'rails/all'` in config/application.rb.
