### ISSUE TITLE
RAILS_MASTER_KEY should be read very early in startup, and then cleared

### ISSUE THREAD

**Issue by samsonjs** [rails/rails#30338]
### Steps to reproduce

Use secrets.yml.enc and provide the key to your app via the environment variable RAILS_MASTER_KEY.

### Expected behavior

The secret key shouldn't remain in your environment after it's read by Rails, otherwise you're simply making it ever so slightly more difficult for an attacker to steal your secrets.

### Actual behavior

The environment still contains your secret key and your secrets can be stolen with little additional effort. 3rd party gems run in-process and can steal the key even if you provide the key in the command itself, e.g. `RAILS_MASTER_KEY=abc123 bin/rails start`, instead of exporting it to prevent forked/spawned processes from inheriting it.

### System configuration
**Rails version**: 5.1

**Ruby version**: Any

**Comment by albertoalmagro** [comment]
Thanks @samsonjs for reporting, after discussing this [here](https://github.com/rails/rails/pull/30067#issuecomment-324426268) I will try to provide a fix for this.

**Comment by samsonjs** [comment]
Ok thanks @albertoalmagro, let me know if I can help at all.

(The main concern is about forking/spawning really because required gems are in-process and can trivially look at Rails.secrets anyway.)

**Comment by albertoalmagro** [comment]
Could someone please review https://github.com/rails/rails/pull/30511 ? It has been open for a while. Thanks!

**Comment by albertoalmagro** [comment]
@matthewd could you please close this issue as PR has been closed?
