### ISSUE TITLE
How does actionmailer send email?

### ISSUE THREAD

**Issue by ContentInX** [rails/rails#30333]
After using function ActionMailer::mail, the email has already been sent out.We haven't called any method such as delivery, delivery_now...
I wanna know that is there any interceptor to help us do this?

**Comment by albertoalmagro** [comment]
Hi @ContentInX thanks. Please provide more info to reproduce this:

- Ruby version
- Rails version
- An example app or script that reproduces the problem.

If you want to preview/ensure emails are sent you can use mailcatcher gem  https://mailcatcher.me/

**Comment by prathamesh-sonpatki** [comment]
Please use stackoverflow or other medium for posting questions where a wider community can help you, we reserve the issue tracker for bug reports only, thanks.
