### ISSUE TITLE
Callbacks of ActionMailer

### ISSUE THREAD

**Issue by michiomochi** [rails/rails#30358]
ActiveJob has `#before_perform`, `#after_perform`, `#around_perform` and some useful callbacks.
https://github.com/rails/rails/blob/master/activejob/lib/active_job/callbacks.rb#L52

But ActionMailer doesn't have any callbacks. 😞  (I can't find it.)

I want ActionMailer to have callbacks, like ActiveJob.
What do you think of this?

**Comment by kaspth** [comment]
Action Mailer includes Action Controller callbacks: https://github.com/rails/rails/blob/fabac4fe025e3af5ecd53e621a06cc4ab20b01b5/actionmailer/lib/action_mailer/base.rb#L451

So `before_action`, `around_action` and `after_action` all work. You can see it leveraged for Rails 5.1's parameterized mailers her: http://api.rubyonrails.org/classes/ActionMailer/Parameterized.html
