### ISSUE TITLE
Rails Secrets config.read_encrypted_secrets is not picked up anymore

### ISSUE THREAD

**Issue by pavel-jurasek-joincoup-com** [rails/rails#30362]
### Steps to reproduce

`config/environments/staging.rb`

OK all secrets are loaded

```ruby
Rails.application.configure do
  config.read_encrypted_secrets = true

  if ENV['LOCAL_DEVEL'] == 'true'
    config.action_mailer.default_url_options = { host: Rails.application.secrets.base_url }
    config.action_mailer.delivery_method = :test
    config.action_mailer.perform_deliveries = false
  else
    config.action_mailer.default_url_options = { protocol: 'https', host: Rails.application.secrets.base_url }
  end
end
```

`puts Rails.application.secret.foo`
`$ => "secret value foo from secrets.yml.enc"`

ERROR

```ruby
Rails.application.configure do
  if ENV['LOCAL_DEVEL'] == 'true'
    config.action_mailer.default_url_options = { host: Rails.application.secrets.base_url }
    config.action_mailer.delivery_method = :test
    config.action_mailer.perform_deliveries = false
  else
    config.action_mailer.default_url_options = { protocol: 'https', host: Rails.application.secrets.base_url }
  end
  config.read_encrypted_secrets = true
end
```

`puts Rails.application.secret.foo`
`$ => "dummy value foo from secrets.yml"`

### Expected behavior

Rails should warn / failed if read_encrypted_secrets are not use before people asking for secrets.

and/or

Rails should resolve values only after all environments are set.

### Actual behavior

If user calls `Rails.application.secrets` and then set `Rails.application.config.read_encrypted_secrets` after values of `Rails.application.secrets` are already cached and `secrets.yml.enc` is never merged to final result set.

### System configuration
**Rails version**:
5.1.1+ after this PR : https://github.com/rails/rails/pull/28631/files
**Ruby version**:
2.4.1

**Comment by albertoalmagro** [comment]
Hello @pavel-jurasek-joincoup-com , just a clarification please: At the beginning you say _before_ that PR and then you say _after_. Could you please confirm which one is correct? Thanks.

**Comment by kaspth** [comment]
Not sure I follow you either 😊

**Comment by pavel-jurasek-joincoup-com** [comment]
Hi guys @kaspth @albertoalmagro @y-yagi  here is change bug report i know that this can be just put as miss configuration but would be nice to change documentation and mention this issue there... right know this issue is super confusing for people used to to throw configuration directives to environment.rb in any order.

**Comment by kaspth** [comment]
`config.read_encrypted_secrets` isn't long for this world. Let's revisit after https://github.com/rails/rails/pull/30067 😊
