### ISSUE TITLE
Unable to use cookie from Rails 5.0.3

### ISSUE THREAD

**Issue by Geesu** [rails/rails#30364]
### Steps to reproduce
1. Login to a rails application using Rails 5.0.3 specifying a session key in `session_store.rb`:

`Rails.application.config.session_store :cookie_store, key: '_my_session'`

2. Restart the rails application using rails 5.1.3 (or 5.1.0). Simply loading the home page will result in this exception.

### Expected behavior
The page loads and uses the previous session.

### Actual behavior
An exception is thrown:
![screen shot 2017-08-22 at 1 49 44 pm](https://user-images.githubusercontent.com/170654/29580079-bbb26664-8742-11e7-804a-4b4a4f021180.png)

### System configuration
**Rails version**: 5.1.3

**Ruby version**: 2.3.3

**Comment by jkepps** [comment]
I ran into this same problem earlier this week. Did you find a solution before you closed the issue @Geesu?

**Comment by Geesu** [comment]
I believe I had to change `Rails.application.config.action_dispatch.cookies_serializer`

**Comment by jkepps** [comment]
Yep, that's what it was. Thanks!
