### ISSUE TITLE
action_dispatch Array.wrap(@env["action_dispatch.parameter_filter"]) change original env

### ISSUE THREAD

**Issue by bingyanz** [rails/rails#30374]
### Steps to reproduce

(Guidelines for creating a bug report are [available
here](http://guides.rubyonrails.org/contributing_to_ruby_on_rails.html#creating-a-bug-report))

### Expected behavior
Tell us what should happen

### Actual behavior
Below code change original value of @env["action_dispatch.parameter_filter"], which makes size of @env["action_dispatch.parameter_filter"] increased after many requests, is it expected?

Lots of /RAW_POST_DATA/ are appended to @env["action_dispatch.parameter_filter"]
```
From: .rvm/gems/ruby-2.3.4/gems/actionpack-3.2.22.5/lib/action_dispatch/http/filter_parameters.rb
@ line 52 ActionDispatch::Http::FilterParameters#env_filter:

    51: def env_filter
 => 52:   parameter_filter_for(Array.wrap(@env["action_dispatch.parameter_filter"]) << /RAW_POST_DATA/)
    53: end
```
### System configuration
**Rails version**:
3.2.22.5
**Ruby version**:
2.3.4

**Comment by sevenseacat** [comment]
I don't think Rails 3 gets any updates anymore...

**Comment by kaspth** [comment]
Rails 3 is unsupported 😊
