### ISSUE TITLE
Only one validation is invoked when called with different context conditions

### ISSUE THREAD

**Issue by laertispappas** [rails/rails#30375]
### Steps to reproduce

```ruby
# frozen_string_literal: true

begin
  require "bundler/inline"
rescue LoadError => e
  $stderr.puts "Bundler version 1.10 or later is required. Please update your Bundler"
  raise e
end

gemfile(true) do
  source "https://rubygems.org"
  gem "rails", github: "rails/rails"
  gem "arel", github: "rails/arel"
  gem "sqlite3"
end

require "active_record"
require "minitest/autorun"
require "logger"

# This connection will do for database-independent bug reports.
ActiveRecord::Base.establish_connection(adapter: "sqlite3", database: ":memory:")
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :posts, force: true do |t|
	t.string :title
	t.string :status
  end

  create_table :comments, force: true do |t|
    t.integer :post_id
  end
end

class Post < ActiveRecord::Base
  has_many :comments
  
  validate :some_validation, if: -> { status.present? && status == 'published' }
  validate :some_validation, if: -> { status.present? && status == 'draft' }

  def some_validation
    if status == 'published' || status == 'draft'
      self.errors.add :base, 'Status is invalid'
    end
  end
end

class Comment < ActiveRecord::Base
  belongs_to :post
end

class BugTest < Minitest::Test
  def test_association_stuff
    invalid_post = Post.create(status: 'published')
    invalid_post2 = Post.create(status: 'draft')

    assert(false, invalid_post.valid?)
    assert(false, invalid_post2.valid?)
  end
end
```

### Expected behavior
Both posts should be invalid.

### Actual behavior
Only one validation callback is executed. 

### System configuration
Rails 5, Rails 4

**Ruby version**:
2.2.6

Is this by design?

**Comment by albertoalmagro** [comment]
Hello @laertispappas,

to define multiple validations please combine validation conditions: http://guides.rubyonrails.org/active_record_validations.html#combining-validation-conditions

or group them together:
`validate :some_validation, if: -> { status.present? && (status == 'published' || status == 'draft') }`

or use a method to determine if it should validate:
`validate :some_validation, if: :should_validate?`

Thanks

**Comment by laertispappas** [comment]
Hello @albertoalmagro Thank you for your feedback. I did combine them in order to not create an alias method that will call the original `validate :some_validation`. The grouping could be extracted in a method as well but on small conditions I like to see the logic directly in the validate definition.

I was curious for the implementation though and the decision behind the logic or any technical difficulties that avoids registering the same validation twice.

Thanks

**Comment by lugray** [comment]
The signature of `assert` is `assert(test, msg = nil)`.  Your `assert(false, invalid_post.valid?)` will always fail.  You're looking for `assert_equal false, invalid_post.valid?` or `assert !invalid_post.valid?`

The relevant PR around not setting the same callback twice (validations are callback under the hood) is #7376.

If you really want something that looks similar to what you have,
```ruby
validate -> { some_validation if status.present? && status == 'published' }
validate -> { some_validation if status.present? && status == 'draft' }
```
will work.

**Comment by laertispappas** [comment]
@lugray Many thanks for your quick prompt and your feedback. Looks valid to not run them twice.

Thanks.
