### ISSUE TITLE
[DOCUMENTATION] Is the `:template` option for `render` absent from the docs?

### ISSUE THREAD

**Issue by rlue** [rails/rails#30396]
I was trying to figure out how, in a given controller, I could render a view template belonging to a different resource than the one the controller was for (I know there probably isn't a good justification for this, but bear with me). 

In the process, I chanced upon [this SO answer](https://stackoverflow.com/questions/6051776/rails-3-render-action-from-another-controller), which deals with using `render` in views to render whole view templates rather than partials (also probably hard to justify, but hey, it works):

> Try to render template:
> 
>     <%= render :template => "controller/index" %> 
> 
> Or file:
> 
>     <%= render :template => "#{Rails.root}/app/controllers/controller/index" %> 

I've searched the docs high and low (mostly googling “site:api.rubyonrails.org render template”), but haven't been able to find any mention of this `:template` option.

Have I missed it somewhere? If not, is there any chance this could be added to the appropriate docs page?

More importantly, what use cases was this option originally designed to support? Are there times when the situations I mentioned above might actually make sense?

**Comment by prathamesh-sonpatki** [comment]
It is mentioned in the guides: http://guides.rubyonrails.org/layouts_and_rendering.html#rendering-an-action-s-template-from-another-controller & http://guides.rubyonrails.org/layouts_and_rendering.html#rendering-an-arbitrary-file

[This section](http://guides.rubyonrails.org/layouts_and_rendering.html#wrapping-it-up) has some explanation about intended use cases.

**Comment by rlue** [comment]
Whoops, don't know how I missed @prathamesh-sonpatki's answer. 

To be clear then, it's in the guides (which I hadn't noticed before, so thank you), but it's absent from the _API documentation._ Specifically, I might expect to find some information about it either in the docs [for `AbstractController::Rendering`](http://api.rubyonrails.org/classes/AbstractController/Rendering.html#method-i-render) or [for `ActionController::Renderers](http://api.rubyonrails.org/classes/ActionController/Renderers.html#method-i-render_to_body). 

Then again, it's far from the only undocumented method in Rails. In light of that fact, it probably makes more sense just to drop this one.
