### ISSUE TITLE
Streaming with ActionCable

### ISSUE THREAD

**Issue by cuvant** [rails/rails#30397]
I'm trying to implement a new feature that requires a bit of real time functionality. My project is built using Rails 5.1.3 and I want to achieve my goals using ActionCable.
Basically I have a dashboard with multiple widgets. Each widget displaying a certain informations like RAM & CPU usage, Git Hub Pull Requests Count, Issues Count, Honey Badger errors count, etc..

There is a Sidekiq job that runs every 30 seconds that saves data and streams it to the consumer ( dashboards#show ).

My question is: how do I stream only to dashboards that are "online", how do I know if the page www.myapp.com/dashboards/1 is used?
Lets say I have 1000 dashboards, I don't want to stream data to all of the from the job, only to the dashboards that are "used".

Thank you!

At the moment I have the following code, but Its not working properly..

`
  module DashboardTracker
  
    def self.add_sub(dashboard_id)
      $redis.watch("dashboard_#{dashboard_id}_online")
    
      $redis.multi do
        $redis.INCR("dashboard_#{dashboard_id}_online")
      end
    end
   
    def self.remove_sub(dashboard_id)
      $redis.watch("dashboard_#{dashboard_id}_online")
    
      val = $redis.multi do
        $redis.DECR("dashboard_#{dashboard_id}_online")
      end
    
      if val[0] <= 0
        $redis.del("dashboard_#{dashboard_id}_online")
      end
    end
  
    def self.sub_count(dashboard_id)
      $redis.get("dashboard_#{dashboard_id}_online").to_i
    end

    end
`
`  
  def subscribed
    stream_from "dashboard:#{params['dashboard_id']}"
    DashboardTracker.add_sub(params['dashboard_id'])
  end

  def unsubscribed
    DashboardTracker.remove_sub(params['dashboard_id'])
  end
`

And in the job

`
  if Dashboard.online?(widget.dashboard_id) ... stream data
`

I can't understand why but the unsubscribe method is not called all the time.. there are cases when a page refresh won't call it.. and everything is messed up..

Hope I posted the question it he right place, if not I'm sorry and I will remove it. Thank you!

**Comment by palkan** [comment]
Hi, @cuvant!

> My project is built using Rails 5.3

I guess, you meant 5.1.3.

> there are cases when a page refresh won't call it.. 

Do you use Turbolinks?

> and everything is messed up

Do you mean that the user on `/dashboards/:x` page receives messages for `/dashboards/:y`?

Could you, please, reproduce it locally (in development mode) and provide server logs?

**Comment by cuvant** [comment]
Hello, yes I have Turbolinks enabled and its Rails 5.1.3, I will try to reproduce and send server logs.. but at the moment I need to find a way to stream the data only if the the page `/dashboards/:x` is open..

**Comment by palkan** [comment]
That might be cause by Turbolinks–Action Cable connection persists between _Turbolinked_ page updates, so your subscriptions is not closing. Try to remove subscription yourself on Turbolinks events.
