### ISSUE TITLE
:inverse_of association option not working with eager_loading.

### ISSUE THREAD

**Issue by kuzukuzu** [rails/rails#30402]
`:inverse_of` association option not working with eager_loading.

### Steps to reproduce

```
class User < ActiveRecord::Base
  has_many :posts, inverse_of: :user
end

class Post < ActiveRecord::Base
  belongs_to :user, inverse_of: :posts
  belongs_to :category
end

user = User.first

puts "without eager_loading:"
puts user.object_id == user.posts.first.user.object_id
puts ""

puts "with eager_loading:"
puts user.object_id == user.posts.eager_load(:category).first.user.object_id
```

### Expected behavior
Expected outputs are as below.

```
without eager_loading:
true

with eager_loading:
true
```

### Actual behavior
Actually like this.

```
without eager_loading:
true

with eager_loading:
false
```

### Further note
In my survey, it derives from changes in 5.1 release.

![2017-08-25 15 05 32](https://user-images.githubusercontent.com/3271606/29701558-6326c7a8-89a7-11e7-96c4-80c47b6f21d7.png)

The block passed to super method isn't executed with eager_loading.

![2017-08-25 15 06 37](https://user-images.githubusercontent.com/3271606/29701601-92bfdc70-89a7-11e7-8761-ba012f6a0f0e.png)

Is this intended change?

### System configuration
**Rails version**: 5.1.2

**Ruby version**: 2.3.1

**Comment by kamipo** [comment]
Thanks for the report. This regression was caused by caa178c178468f7adcc5f4c597280e6362d9e175.
Fixed in 1a723c65bbe91ad969b67416233d20eff6d2a46a.
