### ISSUE TITLE
ActiveSupport::TimeZone gives incorrect offsets for dates grossly in the future.

### ISSUE THREAD

**Issue by Mihail-K** [rails/rails#30408]
### Steps to reproduce
Dates significantly into the future are producing incorrect timezone offset. Specifically, DST is not applied.
This conflicts with the behaviour we have in Postgres, which does apply DST correctly.

### Expected behaviour
```ruby
time_zone = ActiveSupport::TimeZone['America/Toronto']
time_zone.at(Time.current).formatted_offset # => -04:00
time_zone.at(50.years.from_now).formatted_offset # => -04:00
```

### Actual behaviour
```ruby
time_zone = ActiveSupport::TimeZone['America/Toronto']
time_zone.at(Time.current).formatted_offset # => -04:00
time_zone.at(50.years.from_now).formatted_offset # => -05:00
```

### System configuration
**Rails version**: 5.0.2

**Ruby version**: 2.3.3

**Comment by mkbehbehani** [comment]
Validating correct behavior at TZInfo gem.
```
irb(main):023:0> tz= TZInfo::Timezone.get('America/Toronto')
irb(main):028:0> tz.period_for_local(Time.current).utc_offset
=> -18000
irb(main):029:0> tz.period_for_local(50.years.from_now).utc_offset
=> -18000
```
I was able to replicate this bug. There is an incorrect UTC offset returning from ActiveSupport#at:
```
irb(main):003:0> time_zone.at(Time.current)
=> Sun, 27 Aug 2017 19:03:22 EDT -04:00
irb(main):004:0> time_zone.at(50.years.from_now)
=> Sat, 27 Aug 2067 18:03:34 EST -05:00
```
Seems like this incorrect offset is coming from the conversion during Time#in_time_zone. It appears that calling .in_time_zone for every date after 2037-11-2 returns an offset of -05:00, regardless of being in DST (March 12 - November 5) or not.
```
irb(main):062:0> Time.new(2037, 11, 1, 0, 0, 0).in_time_zone(ActiveSupport::TimeZone['America/Toronto'])
=> Sun, 01 Nov 2037 01:00:00 EDT -04:00
irb(main):063:0> Time.new(2037, 11, 2, 0, 0, 0).in_time_zone(ActiveSupport::TimeZone['America/Toronto'])
=> Mon, 02 Nov 2037 01:00:00 EST -05:00
```
More examples:
```
irb(main):067:0> Time.new(2017, 8, 27, 0, 0, 0).in_time_zone(ActiveSupport::TimeZone['America/Toronto'])
=> Sun, 27 Aug 2017 01:00:00 EDT -04:00
irb(main):069:0> Time.new(2038, 8, 27, 0, 0, 0).in_time_zone(ActiveSupport::TimeZone['America/Toronto'])
=> Fri, 27 Aug 2038 00:00:00 EST -05:00
irb(main):070:0> Time.new(2045, 8, 27, 0, 0, 0).in_time_zone(ActiveSupport::TimeZone['America/Toronto'])
=> Sun, 27 Aug 2045 00:00:00 EST -05:00
```

**Comment by mkbehbehani** [comment]
Debugging further down in Time#in_time_zone, this gets called: https://github.com/rails/rails/blob/ac717d65a31d05458588b78ea7719b79f8ea69e5/activesupport/lib/active_support/values/time_zone.rb#L545

Behavior with a time before 2037-11-2:

```
(byebug) time.utc
2017-08-27 05:00:00 UTC
(byebug) TimeWithZone.new(time.utc, self)
Sun, 27 Aug 2017 01:00:00 EDT -04:00
```

TimeWithZone when the year is bumped to after 2037-11-2. Note that the return value is in time zone EST, not EDT:
```
(byebug) time.utc
2057-08-27 05:00:00 UTC
(byebug) TimeWithZone.new(time.utc, self)
Mon, 27 Aug 2057 00:00:00 EST -05:00
```

**Comment by mkbehbehani** [comment]
After some digging, it looks like this issue originates with the TZInfo gem. @Mihail-K you can see here that beyond 2037-11-2, TZinfo, does not include EDT in the periods_for_local, so you get a different UTC offset than expected:

```
time_zone = TZInfo::Timezone.get('America/Toronto')
irb(main):005:0> time_zone.periods_for_local(Time.new(2017, 8, 27, 10, 0, 0))
=> [#<TZInfo::TimezonePeriod: #<TZInfo::TimezoneTransitionDefinition: #<TZInfo::TimeOrDateTime: 1489302000>,#<TZInfo::TimezoneOffset: -18000,3600,EDT>>,#<TZInfo::TimezoneTransitionDefinition: #<TZInfo::TimeOrDateTime: 1509861600>,#<TZInfo::TimezoneOffset: -18000,0,EST>>>]
irb(main):006:0> time_zone.periods_for_local(Time.new(2047, 8, 27, 10, 0, 0))
=> [#<TZInfo::TimezonePeriod: #<TZInfo::TimezoneTransitionDefinition: #<TZInfo::TimeOrDateTime: 2140668000>,#<TZInfo::TimezoneOffset: -18000,0,EST>>,nil>]
```
Tested on Rails version: v5.1.4.rc1, revision: f0811db8074e46feef368161f8b12e592bb4c559
Ruby version: 2.4.1

**Comment by pixeltrix** [comment]
Closing because this isn't a bug in Rails (and isn't really a bug in the tzinfo gem either)
