### ISSUE TITLE
Controllers bubbling up in development environment only

### ISSUE THREAD

**Issue by AdrienGiboire** [rails/rails#30419]
### Steps to reproduce

*tl,dr:* For the sake of anyone, I have created a repo from a new project: https://github.com/AdrienGiboire/controller-bubbling

All the instructions are for `development` environment only. Otherwise, it behaves as expected.

Set up your routes:

```
Rails.application.routes.draw do
  namespace :parents do
    namespace :children do
      get '/hello', to: 'great_children#hello'
    end
  end
end
```

Create an empty folder as follow:

```
mkdir app/controllers/parents/children
```

This way Rails does not complain with the following:

```
Routing Error
uninitialized constant Parents::Children
```

Create a controller as follow:

```
# app/controllers/parents/great_children_controller.rb
class Parents::GreatChildrenController < ApplicationController
  def hello
    render json: { message: 'You should not be here!'}
  end
end
```

### Expected behavior

Rails should raise an error as follow:

```
Routing Error

uninitialized constant Parents::Children::GreatChildrenController
```

### Actual behavior

It runs `Parents::GreatChildrenController#hello`.

### System configuration

**Rails version**: 5.1.3
**Ruby version**: 2.4.1

**Comment by composerinteralia** [comment]
I ran your app in development and got the expected `uninitialized constant Parents::Children` when visiting `/parents/children/hello`.

**Comment by AdrienGiboire** [comment]
That's not what I'm describing.

Create the folder as follow:

```mkdir app/controllers/parents/children```

Then visit again and see it working instead of being warned of `
uninitialized constant Parents::Children::GreatChildrenController`

**Comment by matthewd** [comment]
http://guides.rubyonrails.org/autoloading_and_reloading_constants.html#common-gotchas

**Comment by AdrienGiboire** [comment]
@matthewd Thanks but how can it be that it doesn't behave the same in `development` where it resolve the dependency but not in a non-`development` environment?

**Comment by adilbenseddik** [comment]
@matthewd it would be nice of you if you could provide a more detailed explanation instead of just pointing to the common gotchas, as this behaviour is nothing to expect from a ruby based framework hence the difference in behaviour between `production` and `development` environments.. noo??

**Comment by composerinteralia** [comment]
`production` and `development` environments do have some differences in the way things are loaded. Compare the various files in `config/environments`.

**Comment by AdrienGiboire** [comment]
@composerinteralia I get that but how? I've taken a look already but didn't spotted the one thing that makes it behave that way. Yet, it's a critical behaviour. We caught this because we tested it in a different environment than the one use to develop things. That does not seems quite normal.
