### ISSUE TITLE
rake environment bleeding?

### ISSUE THREAD

**Issue by haydenk** [rails/rails#30423]
### Steps to reproduce

(Guidelines for creating a bug report are [available
here](http://guides.rubyonrails.org/contributing_to_ruby_on_rails.html#creating-a-bug-report))

### Expected behavior
* `rake db:create` creates a development database
* `RAILS_ENV=development rake db:create` creates a development database
* `RAILS_ENV=development bundle exec rake db:create` creates a development database

### Actual behavior
`rake db:create` creates a development AND a test database

### System configuration
**Rails version**: Rails 5.1.3

**Ruby version**: ruby 2.4.1p111 (2017-03-22 revision 58053) [x86_64-darwin16]

I noticed this in a Rails application I was starting with where I added Grape API and thought it was doing it with all the environments but apparently it is just doing it with development and test environments. Should this be doing this? I would expect it to only do this with one or the other or whatever environment I have selected.

I tried this on a newly generated rails application to make sure there were not any other changes that I made that caused this to occur. This occurred whether it was using the default Sqlite adapter or PostgreSQL adapter.

This does seem to respect the environment for test and production but not for development.

**Comment by y-yagi** [comment]
This is expected behavior. It behaves like that to work properly even when using spring. 
Please see #24201 for details.

**Comment by prathamesh-sonpatki** [comment]
Yup, this is [expected behavior](https://github.com/rails/rails/pull/24201#issuecomment-197055483), thanks for the issue but giving it a close.

**Comment by abaldwin88** [comment]
Is there any way for me to drop the development database but not the test database?  In my workflow I run scripts in parallel on both my test and development environments that use `db:create` and `db:drop`.

P.S.

Appreciate all the hard work on rails 👍
