### ISSUE TITLE
Error (incompatible character encodings: UTF-8 and ASCII-8BIT) after RAILS update from 4.2.6 to 4.2.9

### ISSUE THREAD

**Issue by nnonet** [rails/rails#30440]
### Steps to reproduce
Rails broke Redmine after update from 4.2.6 to 4.2.9
when creating new page that contains Unicode characters 
page doesn't open. (error is displayed)
Error from Redmine log:

> ActionView::Template::Error (incompatible character encodings: UTF-8 and ASCII-8BIT):
>     1: <%= wiki_page_breadcrumb(@page) %>
>     2: 
>     3: <h2><%= @page.pretty_title %></h2>
>     4: 
>     5: <%= form_for @content, :as => :content,
>     6:             :url => {:action => 'update', :id => @page.title},
>   app/views/wiki/edit.html.erb:3:in `_app_views_wiki_edit_html_erb__895841188678804177_70176465922900'
>   app/controllers/wiki_controller.rb:73:in `show'
>   lib/redmine/sudo_mode.rb:63:in `sudo_mode'

Problem happens when you get url: [unicode characters]?parent=ASCII
Rails version 4.2.6 din't had this problem.
(Guidelines for creating a bug report are [available
here](http://guides.rubyonrails.org/contributing_to_ruby_on_rails.html#creating-a-bug-report))

### Expected behavior

It should open new Redmine page

### Actual behavior

Error is displayed.
### System configuration
**Rails version**:
4.2.9
**Ruby version**:
2.3.1-p112 
![screenshot 7](https://user-images.githubusercontent.com/31402064/29765237-557aa032-8c15-11e7-83b8-a6ac4ee58ca4.png)

**Comment by nnonet** [comment]
How can I use fixed version with redmine. bundler seem to install bad version 4.2.9.

**Comment by y-yagi** [comment]
Since the new version to which the above commit has been adapted has not yet been released, you need to specify a branch as shown below.

```ruby
# Gemfile 
gem 'rails', github: 'rails/rails', branch: '4-2-stable'
```
If there is no error in the workaround at #29669, I think that it is the same problem.

**Comment by kostikpl** [comment]
I have same issue with ckeditor.
```ruby
<%= semantic_form_for @page do |f| %>
  <%= f.input :content, as: :ckeditor %>
  ...
<% end %>
```
weird part of this is same field present on activeadmin and it works fine

**Comment by eileencodes** [comment]
Closing because this is fixed in the 4.2.10 version of Rails.

**Comment by romaingibs13** [comment]
@eileencodes who would have guessed that it wold haave popped back in 2022 and rails 7  with an engine (even though it happens in the typical App ? XD

**Comment by romaingibs13** [comment]
![Screenshot 2022-01-27 at 14 43 33](https://user-images.githubusercontent.com/65034040/151370760-6ef56d92-b07a-4595-b2fb-2edcdab09d0a.png)
