### ISSUE TITLE
Indirect dependency on Nokogiri

### ISSUE THREAD

**Issue by lloeki** [rails/rails#30442]
From Nokogiri's [very own install guide](http://www.nokogiri.org/tutorials/installing_nokogiri.html):

> Because Nokogiri needs to be compiled and dynamically linked against both `libxml2` and `libxslt`, it has gained a reputation for being complicated to install.

[For various reasons](https://github.com/YorickPeterse/oga#why-another-htmlxml-parser) we have been striving to minimise our use of Nokogiri in favor of alternatives where necessary (e.g ReXML or Oga) which proved to be surprisingly easy internally.

In the case of software depending on Rails, it turns out the dependency on Nokogiri is computed as mandatory but seems (at a glance) quite loose in reality: the two culprits are [`rails-dom-testing`](https://github.com/rails/rails-dom-testing) and [`rails-html-sanitizer`](https://github.com/rails/rails-html-sanitizer).

`rails-dom-testing` has been extracted from `ActionView`, and apparently could be an optional dependency of Rails altogether for those who don't use the likes of `assert_dom_equal` and `css_select`.

I'm not too sure about the use of `rails-html-sanitizer` within Rails itself but looking at the [`sanitize` method](http://api.rubyonrails.org/classes/ActionView/Helpers/SanitizeHelper.html#method-i-sanitize) it seems like things are quite encapsulated as long as you're not developing custom scrubbers, where loofah [appears leak-ish](https://github.com/rails/rails-html-sanitizer#read-more) on purpose:

> Loofah is what underlies the sanitizers and scrubbers of rails-html-sanitizer.
> The node argument passed to some methods in a custom scrubber is an instance of Nokogiri::XML::Node

At any rate, someone willfully implementing a custom scrubber will know about this and pull Nokogiri  in by its own volition.

But that's assuming `rails-html-sanitizer` is used within Rails at all. If not, the same reasoning as for `rails-dom-testing` can be applied.

My personal and humble opinion is that it would be great for Rails not to pull such a heavyweight dependency in when it seems to be hardly needed. What do you think?

### Steps to reproduce

- create a Rails application or engine
- look at `Gemfile.lock` (excerpt):

    ```
    loofah (2.0.3)
      nokogiri (>= 1.5.9)
    nokogiri (1.8.0)
      mini_portile2 (~> 2.2.0)
    rails-dom-testing (2.0.3)
      activesupport (>= 4.2.0)
      nokogiri (>= 1.6)
    rails-html-sanitizer (1.0.3)
      loofah (~> 2.0)
    actionpack (5.1.2)
      actionview (= 5.1.2)
      rails-dom-testing (~> 2.0)
      rails-html-sanitizer (~> 1.0, >= 1.0.2)
    actionview (5.1.2)
      rails-dom-testing (~> 2.0)
      rails-html-sanitizer (~> 1.0, >= 1.0.3)
    ```

### Expected behavior

Not having rails pull Nokogiri in

### Actual behavior

Nokogiri gets pulled in by a Rails dependency

### System configuration

**Rails version**: 5.1.2

**Ruby version**: 2.3.4

**Comment by rafaelfranca** [comment]
Thank you for the issue. My opinion is still the same as it was in https://groups.google.com/d/msg/rubyonrails-core/TqPPisZ3ttU/JK5RBvgnViIJ. I'm closing this since we don't take feature requests in the issue tracker.
