### ISSUE TITLE
ActiveModel: Unexpected or undocumented behavior for run_callbacks

### ISSUE THREAD

**Issue by JAMSUPREME** [rails/rails#30443]
### Steps to reproduce

Create an ActiveModel and at the **end** of the `run_callbacks` block body (final evaluated expression) put an expression that evaluates to something falsey.

Refer to https://github.com/JAMSUPREME/rails-run-callbacks-bug for a functioning example (simply clone the repo and run `bundle exec rake test`)

### Expected behavior

I expected the `after_initialize` method (`after_initialize :give_cooler_name`) to be run after `run_callbacks`, but it was not.

**If this is expected**, I would like the doc summary of `active_model/callbacks.rb` 
 to be a little more explanatory (https://github.com/rails/rails/blob/456c9e721940dd9e134c96c0e638f41532dfb6a6/activemodel/lib/active_model/callbacks.rb#L6)

**If this is not expected**, I would like it to be corrected.

**If perhaps it is not expected**, but I am doing something horribly wrong, it would be nice if someone could explain to me the error of my ways.

### Actual behavior

The `after_initialize` method was not run.

### System configuration
**Rails version**: `5.1.3` and `4.2.9` (The referenced repo has a branch https://github.com/JAMSUPREME/rails-run-callbacks-bug/tree/rails-v4 for verifying against 4.x)

**Ruby version**: `ruby 2.3.3p222 (2016-11-21 revision 56859) [x86_64-linux]` and `ruby 2.3.4p301 (2017-03-30 revision 58214) [x86_64-linux]`

**Comment by al2o3cr** [comment]
To sum up what you're observing: returning `false` from the block passed to `run_callbacks` causes the chain to be halted & no `after` callbacks run.

There's a test that verifies this exact behavior:

https://github.com/rails/rails/blob/86389b41436e7020a403c72669cf7748850fb15e/activemodel/test/cases/callbacks_test.rb#L80

so it seems intentional. The docs could probably use an explicit call-out of this.

For reference, the code implementing this lives here:

https://github.com/rails/rails/blob/553f863e0a58ae5df528523f41dd34d1f77ddb0e/activemodel/lib/active_model/callbacks.rb#L141

**Comment by matthewd** [comment]
@claudiob could this be a missing piece from #17227?

**Comment by JAMSUPREME** [comment]
@al2o3cr Thanks for the links - I believe I was staring at the higher level callback tests (https://github.com/rails/rails/blob/cfb1e4dfd8813d3d5c75a15a750b3c53eebdea65/activesupport/test/callbacks_test.rb) and hadn't stumbled onto the other one.

If one did have to do potentially falsey assignments, is the recommended practice to explicitly put something truthy afterwards? e.g. (based on referenced github repo example)
```
run_callbacks :initialize do
  @name = name

  @is_cool = false

  true # make sure truthy value returned
end
```

**Comment by claudiob** [comment]
@matthewd I think you are right. I'm looking back at #17227 (and at 3a25cdca3e which then cleaned up the deprecated code) and that PR should have probably changed this behavior as well.

I was also looking at the discussion that happened regarding `after_` callbacks (https://github.com/rails/rails/pull/17227#issuecomment-59449204) but looks unrelated.

**Comment by al2o3cr** [comment]
@matthewd @claudiob I don't believe this is (directly) related to the behavior changed in #17227 - that dealt with the return value from *callbacks* causing the chain to be cancelled (using the `terminator` option to `define_callbacks`).

This issue instead focuses on the return value of the block passed to `run_callbacks`, which *also* cancels `after` callbacks (via the plumbing around line 141, linked above).

**Comment by matthewd** [comment]
@al2o3cr right.. our contention is that that's a distinction #17227 didn't intend to make. The high level goal was to switch from false-return cancelling callbacks to needing an explicit throw; they were obviously implemented separately, but this `run_callbacks` behaviour was pretty clearly modelled on the [now removed] wider callback behaviour.

So, conclusion: we should deprecate this behaviour, and direct people to use an explicit `:abort` to match how callbacks now work.

**Comment by al2o3cr** [comment]
@matthewd This seems like a distinct behavior compared to canceling callbacks with `throw :abort` - at a minimum, it would need to instead be `throw :abort, return_value` since the returned value is used (for instance, as the result of `save`).
