### ISSUE TITLE
Sneaky Params via Resource Identifier Configuration

### ISSUE THREAD

**Issue by schmijos** [rails/rails#30467]
This is probably a very hypothetical problem. And please don't ask, how I found it. But somehow it still bugs me.

### Steps to reproduce

Since Rails 4.0 it is possible to sneak in additional parameters via the `param` option for resources. You can do something like that:

    routes.draw do
      resources :users, param: :'name/:sneaky'
    end

[`ActionDispatch::Routing::Mapper::Resources::Resource#initialize`](https://github.com/rails/rails/blob/86389b41436e7020a403c72669cf7748850fb15e/actionpack/lib/action_dispatch/routing/mapper.rb#L1134) just takes it as-is. Later the strings generated by [`#member_scope`](https://github.com/rails/rails/blob/86389b41436e7020a403c72669cf7748850fb15e/actionpack/lib/action_dispatch/routing/mapper.rb#L1186) and [`#nested_param`](https://github.com/rails/rails/blob/86389b41436e7020a403c72669cf7748850fb15e/actionpack/lib/action_dispatch/routing/mapper.rb#L1196) are handed over to the [`Journey::Parser`](https://github.com/rails/rails/blob/86389b41436e7020a403c72669cf7748850fb15e/actionpack/lib/action_dispatch/routing/mapper.rb#L1919) which creates an *AST* with the sneaked in parameters.

You will see that the parameters are added to the `RouteSet` and can be used by the controller action: 

    def show
      render plain: "#{params[:name]} : #{params[:sneaky]}"
    end

Full **reproduction example** is available here (visualizer can be commented out): https://github.com/renuo/railshoeck-route-mapping/blob/master/sample.rb#L21

### Expected behavior
I'd expect the mapper to escape the colon somehow or to throw a route mapping/generation error.

### System configuration
**Rails version**:
4.0 up to *master* (currently at 87eb1a26da0b1385af07a8347dcfd32998a614ee)

**Ruby version**:
Since you can write colons in symbols.

### Further questions

* Is there any possibility that someone out there is using this as a feature?
* Is there any possibility to sneak in user input into your route generation? Some sort of CMS maybe? Like `param: :'id/:is_admin'`...

**Comment by jeremy** [comment]
This is def sneaky and surprising. PR welcome to raise ArgumentError when there's a colon in the param.

**Comment by schmijos** [comment]
@jeremy Fixed by https://github.com/rails/rails/pull/35236

**Comment by searls** [comment]
> Is there any possibility that someone out there is using this as a feature?

For what it's worth, I was actually using this as a feature (upgrading to 6.0 today so just got bit)

```ruby
  resources :weeks, param: "year/:month/:day"
``

I was using this for identifying weeks not based on an id, but instead on a `params[:year]`,`params[:month]`,`params[:day]` tuple. ¯\_(ツ)_/¯

**Comment by scd31** [comment]
Is there a workaround for this? A fairly common url pattern is `:id/:path`, where `:id` is a unique identifier, and `:path` is more human readable, but not necessarily unique. Reddit does their routing this way, in the form of `reddit.com/r/subreddit/a39xb/post_title_here`.

I am doing precisely this on one of my projects. At the moment, I'm forced to forego a resource and just write out all of the routes manually.

**Comment by h0jeZvgoxFepBQ2C** [comment]
We were also using this feature.. Is there any workaround?

**Comment by h0jeZvgoxFepBQ2C** [comment]
F.e. with following route:

```ruby
    resources :unsubscribe_pages, only: [:show, :create, :edit], path: "unsubscribe", param: "unsubscribe_page_id/(:user_id)"

```

To open a unsubscribe page.. If user_id is provided, we just show the prefilled form, without we only show an empty form.. The sneaky parameters were nice since you could name the params in advance nicely?
