### ISSUE TITLE
Touch does not reset previous_changes like save does

### ISSUE THREAD

**Issue by heaven** [rails/rails#30466]
Rails has `before_commit` and `after_commit` callbacks, which run on `:create`, `:update`, `:destroy`, and also on `:touch`, which also triggers a DB commit.

The problem is that `#touch` does not reset `#previous_changes` like `#save` does. So the same after commit callbacks that we run on after update also run on after touch but `previous_changes` keeps outdated changes:
```
2.3.3 :001 > interest = Market::Interest.last
2.3.3 :002 > interest.update(name: "TEST 123456")

2.3.3 :003 > interest.previous_changes
 => {"name"=>["TEST 12345", "TEST 123456"], "updated_at"=>[Wed, 30 Aug 2017 09:20:00 EDT -04:00, Wed, 30 Aug 2017 09:24:26 EDT -04:00]}

2.3.3 :004 > interest.saved_changes
 => {"name"=>["TEST 12345", "TEST 123456"], "updated_at"=>[Wed, 30 Aug 2017 09:20:00 EDT -04:00, Wed, 30 Aug 2017 09:24:26 EDT -04:00]}
```

Now if you run `interest.update(:name => "TEST 1234567")` it will reset previous changes, but if you call `interest.touch` it won't, but the same after commit callback will run and observe obsolete previous changes.

We have `after_commit` callbacks that send emails if specific changes present in `previous_changes`. This doesn't work properly in the case of `:touch => true`, which triggers these callbacks with stale `previous_changes`.

Imagine the following model:
```ruby
class Market::Interest < Market::ListItem
  after_commit on: [:create, :update] do
    if self.previous_changes[:name]
      # send email message
    end
  end
end

class Market::Group < ApplicationRecord
  belongs_to :market_interest, :touch => true
end
```

If you create an interest and then create a group like `Market::Group.create(:market_interest => interest)` you will receive a second email.

### System configuration
**Rails version**: 2.3.3

**Ruby version**: 5.1.3

**Comment by westonganger** [comment]
Also seems very similar to https://github.com/airblade/paper_trail/issues/1047

**Comment by FX-HAO** [comment]
The problem still exists. The issue should be reopened.

**Comment by kfuchs** [comment]
This is also an issue when you touch a relationship from a model. The after commit on the relationship you touched shows all fields as previously being `nil`

IE: `comment.after_commit.user_touch` < comments after_commit runs a method that touches it's associated user.
