### ISSUE TITLE
database.yml mistery charset and broken mysql create_database charset default

### ISSUE THREAD

**Issue by epinault** [rails/rails#30479]
the database.yml has an undocumented configuration parameter called "charset"

Setting the charset in the database.yml , will ensure that when creating a database with this [method: create_database](http://api.rubyonrails.org/classes/ActiveRecord/ConnectionAdapters.html#method-i-create_database)

the charset will be properly set up as the database default in mysql. Currently this is completely undocumented and I have spent quite a few hours trying to understand why my server setting where being ignore on database creation.....

It even gets more confusing as there is an encoding param in database yaml but it seems to be ignored basically on database create..

### System configuration

**Rails version**: 4.x , 5.x
**Ruby version**: 2.x

**Comment by kamipo** [comment]
The charset in the database.yml is no longer used since Rails 5.0.

**Comment by epinault** [comment]
I disagree with your statement. Or at least the source code does..

http://api.rubyonrails.org/classes/ActiveRecord/ConnectionAdapters.html#method-i-create_database

This is 5.1 code. Are you saying that create_database is not used anymore? 

```
def create_database(name, options = {})
  if options[:collation]
    execute "CREATE DATABASE #{quote_table_name(name)} DEFAULT CHARACTER SET #{quote_table_name(options[:charset] || 'utf8')} COLLATE #{quote_table_name(options[:collation])}"
  else
    execute "CREATE DATABASE #{quote_table_name(name)} DEFAULT CHARACTER SET #{quote_table_name(options[:charset] || 'utf8')}"
  end
end
```

**Comment by rafaelfranca** [comment]
@kamipo is right. The database configuration `encoding` that is used as the charset when creating a database. But the question is: Where do you propose the documentation improves? Even if you don't set that configuration the default will be always 'utf8' and this is documented in the method you pointed.

**Comment by epinault** [comment]
hum. so in the case of mysql, when you need UTF-8, it is not setting a good default. UTF8mb4 is what we needed . The problem is that to get that working I had to set the charset and collation separately and not just the encoding.

Digging further I found a library (Apartment) that make use of the create_database directly and so in order to have the correct charset /collation, i had to have the 3 key set properly in the database.yml. Maybe this should be consolidated? or at least in the documentation of the API mentioned around create_database ?  I had to spend lot of time reversing and testing something that basically ended up being defaulted  in the create_database and also not working as expected when I was setting the encoding.

I would expect both charset and collation to be able to default based on the encoding more than than just hardcoding utf8 (which is pretty sad in Mysql world. Not rails fault here..)

**Comment by sekrett** [comment]
@epinault Could you please quote the 3 keys you added to help others?

**Comment by epinault** [comment]
encoding: utf8mb4
  charset: utf8mb4
  collation: utf8mb4_unicode_ci
