### ISSUE TITLE
Incorrect attribute/column type fetched for a group by column on an associated table

### ISSUE THREAD

**Issue by francisli** [rails/rails#30476]
I've just encountered an interesting edge case that breaks grouped count queries in ActiveRecord.

Background: I'm currently in the process of migrating tables from integer to uuid primary keys in my postgresql db. As a result, some tables have an id of integer, and others have an id of uuid. In the following example, Note has a uuid id, and Organization has an integer id. If I execute the following query (simplified from my actual usage, but enough to demonstrate the issue):

`Note.joins(:organization).group('organizations.id').count`

I'll get a result of something like `{nil => 1234}`, instead of a collection of many organization ids and their counts.

The reason is, when `execute_grouped_calculation` is checking for the type of the result set columns:

https://github.com/rails/rails/blob/86389b41436e7020a403c72669cf7748850fb15e/activerecord/lib/active_record/relation/calculations.rb#L334)

It calls `type_for` which simply lops off the table name of the column (`organization.id` into `id`), and ends up getting the type of `id` on the Note class, which is uuid, not integer:

https://github.com/rails/rails/blob/86389b41436e7020a403c72669cf7748850fb15e/activerecord/lib/active_record/relation/calculations.rb#L368

The typecast of the integer Organization id to a uuid results in `nil` for every row in the result set.

My current quick fix solution is to assume any column names with a . in it are references to model tables, and to check the type on that model:

```
    def type_for(field, &block)
      field_name = field.respond_to?(:name) ? field.name.to_s : field.to_s.split(".").last
      if field.include?('.')
        field.to_s.split('.').first.classify.constantize.type_for_attribute(field_name, &block)
      else
        @klass.type_for_attribute(field_name, &block)
      end
    end
```

There's clearly ways that this can also break, and not the most optimal code (splitting the string multiple times, etc), so I didn't think it was necessarily a good solution to submit a pull request for, but this monkey patch gets my code working for now, and I suspect the maintainers will have better ideas...!

**Comment by composerinteralia** [comment]
Any chance you could link to a gist with an executable test case in this format: https://github.com/rails/rails/blob/master/guides/bug_report_templates/active_record_master.rb

**Comment by NoryDev** [comment]
I have this exact same bug. It will happen for every group on joined table where both tables have a column with the same name but a different type.

Thanks @francisli for pointing it out. I can confirm that your monkey patch would break some implementations: the argument passed to `#group` can be a SQL string including a dot. Like:

```ruby
# count posts per day
Post.group("date_trunc('day', CAST(posts.created_at as timestamp))").count
```

In this case it would try to `"date_trunc('day', CAST(posts".classify.constantize` which raise a `NameError`. I use the following monkey patch, but it's not ideal either:

```ruby
def type_for(field, &block)
  field_name = field.respond_to?(:name) ? field.name.to_s : field.to_s.split(".").last
  if field.include?('.') && (field.to_s.split('.').first.classify.constantize rescue false)
    field.to_s.split('.').first.classify.constantize.type_for_attribute(field_name, &block)
  else
    @klass.type_for_attribute(field_name, &block)
  end
end
```

**Comment by NoryDev** [comment]
@composerinteralia here is a gist: https://gist.github.com/NoryDev/194dd5f112ff2b6d7ae5b69757267878

(test failing)

**Comment by UlyssesInvictus** [comment]
This seems to be even more general than for `group` queries. See here: https://github.com/rails/rails/issues/31196
