### ISSUE TITLE
db:schema:dump fails to dump a table with a PostgreSQL enum column

### ISSUE THREAD

**Issue by AndyKriger** [rails/rails#30475]
### Steps to reproduce

1. New Rails project with PostgreSQL as the database
2. Create two migrations
```ruby
class NewTable < ActiveRecord::Migration[5.1]
  def change
          create_table :mytable
  end
end
```
```ruby
class EnumType < ActiveRecord::Migration[5.1]
  def change
          reversible do |dir|
                dir.up do
                        execute <<-SQL
                                create type foo as enum ('a','b');
                        SQL
                end
                dir.down do
                        execute <<-SQL
                        drop type roles;
                        SQL
                end
          end

          add_column :mytable,:col, :foo
  end
end
```
2. ```rake db:migrate db:schema:dump```

### Expected behavior
The schema dump contains the table mytable such that it can be recreated

### Actual behavior
The schema dump contains
```ruby
# Could not dump table "mytable" because of following StandardError
#   Unknown type 'foo' for column 'col'
```

### Notes
The table and column are created correctly and can be used by ActiveRecord. It is the dump that fails, which has implications for testing since minitest/rspec uses schema.rb to create test databases, which will not work.

### Workaround
Throw this into application.rb
```ruby
config.active_record.schema_format = :sql
```
Then run ```rake db:structure:dump```
You'll get a db/structure.sql file that has the enum type properly defined

This is not a great workaround because db:schema is so well-known and beloved by Rails developers around the world.

### System configuration
**Rails version**:
5.1.3

**Ruby version**:
2.4.1

**Comment by kamipo** [comment]
This is expected behavior for now. Custom types are not supported.
Supported type list is here.

https://github.com/rails/rails/blob/c2b2a8c74fcd2e32996641503ed029c8f7484b00/activerecord/lib/active_record/connection_adapters/postgresql_adapter.rb#L77-L115
