### ISSUE TITLE
Scopes fail to use aliased table names if their associated table gets aliased for a join

### ISSUE THREAD

**Issue by dgsan** [rails/rails#30488]
### Steps to reproduce

Have model that somehow reference another table in two ways. Then try including both of them with a query.

For example:
```ruby
# Thing(id, other_id, name)
# Other(id, favorite_thing_id, name)
class Other < ApplicationRecord
  belongs_to :favorite_thing, class_name: 'Thing', foreign_key: :favorite_thing_id
  has_many :things, -> { where.not(things: { name: '' }) }
end

result = Other.all.includes(:favorite_thing, :things).references(:things) # References may be needed
# This results in something like:
# "... JOINS `things` `things_others` ON `things_others`.`other_id` = `others`.`id` AND ( `things`.`name` != '' )
# instead of:
# "... JOINS `things` `things_others` ON `things_others`.`other_id` = `others`.`id` AND ( `things_others`.`name` != '' )
```
When joins involving the same table multiple times in single query happen Rails/ActiveRecord seems to use some kind of pattern to alias subsequent table names. However, the scope involved with each join does not pick up the appropriate table aliases also.

### Expected behavior
If a table is forced to be aliased in a join, its associated scopes should pick up the aliased name.
```sql
"... JOINS `things` `things_others` ON `things_others`.`other_id` = `others`.`id` AND ( `things_others`.`name` != '' )` 
```
in this example.

### Actual behavior
When a table is forced to be aliased in a join its scope retains the original table name.
```sql
"... JOINS `things` `things_others` ON `things_others`.`other_id` = `others`.`id` AND ( `things`.`name` != '' )
```

### System configuration
**Rails version**:  Rails 4.2.7.1 (Not sure if applicable to 5.x)

**Ruby version**: 2.3.4p301

### Notes
If you only have a scope on one of the two relations, listing it first in `includes` may "solve" the issue.
May need to add `references(:things)` to the all ... includes query.
Whichever item is included last will trigger a requery instead of result access even it was successfully queried for! (In this example, `result[0].things` will likely trigger a requery of data that was in the original result.)

**Comment by kamipo** [comment]
`things:` is not needed, simply use `where.not(name: '')` instead.
