### ISSUE TITLE
[Request] Please put back app/assets/fonts into the pipeline

### ISSUE THREAD

**Issue by hron84** [rails/rails#30480]
I have two different applications, one on Rails 5.1.0, one on Rails 5.1.3. I want to use few fonts in my application, and under Rails 5.1.0 I did not needed any configuration, Sprockets just picked up my fonts, 5.1.3 does not serve these fonts. 

See what happens:
```
$ rails c
Running via Spring preloader in process 26038
Loading development environment (Rails 5.1.0)
[1] pry(main)> helper.asset_path 'Discognatehacka_1.ttf'
=> "/assets/Discognatehacka_1-369e9e63bb3eb9e8b4adeb9142cf10aad0e32f679e032cb5255f924de9f0e147.ttf"
[2] pry(main)> Dir.glob('app/assets/fonts/Disco*.ttf')
=> ["app/assets/fonts/Discognatehacka_1.ttf"]
```
and
```
$ rails c
Running via Spring preloader in process 26028
Loading development environment (Rails 5.1.3)
[1] pry(main)> helper.asset_path 'Discognatehacka_1.ttf'
Sprockets::Rails::Helper::AssetNotFound: The asset "Discognatehacka_1.ttf" is not present in the asset pipeline.
from /home/hron/.rvm/gems/ruby-2.4.1@dhtv/gems/sprockets-rails-3.2.0/lib/sprockets/rails/helper.rb:83:in `compute_asset_path'
[2] pry(main)> Dir.glob('app/assets/fonts/Disco*.ttf')
=> ["app/assets/fonts/Discognatehacka_1.ttf"]
[3] pry(main)> 
```
I have absolute no idea what happened. I double-checked `config/initializers/assets.rb` under the 5.1.0 app and I have no lines that add fonts folder to the asset pipeline. 

I also checked `Rails.application.config.assets.paths` on both application and under 5.1.0 `fonts` folder is picked up from all possible places while 5.1.3 refuses to do this.

**Comment by matthewd** [comment]
Please use the mailing list or StackOverflow for questions/help, where a wider community will be able to help you. We reserve the issues tracker for issues only.

**Comment by hron84** [comment]
@matthewd As it is worked previously (without any configuration), I think it's a regression, not a simple question. Or, if you removed this ability, you should just say that.

**Comment by kaspth** [comment]
We don't remove things in a patch release.

Just printing the Rails version doesn't prove that it's a regression or that it was due to a change in Rails itself. For instance, you can try confirming that no other gems got upgraded when you did the 5.1.3 upgrade.

**Comment by guilleiguaran** [comment]
Just tested this and it is not caused by any change between Rails versions

```
~/src/foo[master] % rails c
Running via Spring preloader in process 49420
Loading development environment (Rails 5.1.0)
irb(main):001:0> helper.asset_path 'Roboto-Regular.ttf'
=> "/assets/Roboto-Regular-b2efabca5ea4bc56eea829713706b5cd0788b82aca153bd4adde9b1573933b4f.ttf"
irb(main):002:0> exit

~/src/foo[master] % mvim Gemfile # Changed rails version from '5.1.0' to '5.1.3'
~/src/foo[master] % bundle update

~/src/foo[master] % rails c
Running via Spring preloader in process 49530
Loading development environment (Rails 5.1.3)
irb(main):001:0> helper.asset_path 'Roboto-Regular.ttf'
=> "/assets/Roboto-Regular-b2efabca5ea4bc56eea829713706b5cd0788b82aca153bd4adde9b1573933b4f.ttf"
```

**Comment by hron84** [comment]
Hmmm... strange. I will try to disable all non-essential gems to dig down into the problem. Thanks anyway.
