### ISSUE TITLE
Fix for #24179 regressed in Rails 5.1.3

### ISSUE THREAD

**Issue by samcday** [rails/rails#30491]
### Steps to reproduce

Add `minitest-reporters` to a project with Rails 5.1.3 and try to configure minitest-reporters with some custom reporters in your `test_helper.rb`:

```
Minitest::Reporters.use!([
  Minitest::Reporters::SpecReporter.new,
  Minitest::Reporters::JUnitReporter.new("data/test/reports", false),
])
```

### Expected behavior
Should see minitest-reporters SpecReporter  when running tests. 

### Actual behavior
You do, but you *also* see default Rails test runner reporter output.

### System configuration
**Rails version**: 5.1.3

**Ruby version**: 2.4.1

---

AFAICT, the reason for this issue is the commit b9465e8755509cc79ad7492914a26c8ac3884de0 that fixed the problem was somehow lost in Rails 5.1.3. I don't follow Rails core development too much but if I had to hazard a guess, that changeset was somehow lost due to `railties/lib/rails/test_unit/minitest_plugin.rb` moving to `railties/lib/minitest/rails_plugin.rb`.

This issue is causing much consternation for minitest-reporters users, see kern/minitest-reporters#230

**Comment by rafaelfranca** [comment]
cc @kaspth

**Comment by kaspth** [comment]
> that fixed the problem was somehow lost in Rails 5.1.3

The entire point of b9465e8 was to remove those very lines and demote Rails' minitest test runner integration to be just another minitest plugin.

Of course that brings other hurdles with it because of load order. Especially when two plugins add and replace reporters. I'm happy to give suggestions if people are willing to debug a more suitable solution.

Rails won't go back to hijacking the plugin load order anymore though.

=============================

Perhaps minitest-reporters could do that though, if willing. When `use!` is called for instance, minitest-reporters could perhaps do:

```ruby
Minitest.load_plugins
Minitest.extensions.delete("minitest-reporters")
Minitest.extensions << "minitest-reporters"
```

**Comment by samcday** [comment]
@kaspth I'm not sure I follow. b9465e8 didn't *remove* those lines, it *added* them. The comment (which was introduced in the commit) also explains the intent - to ensure that the Rails minitest plugin is moved to the front of the list to ensure any other present minitest plugins will initialize *after* the Rails one does.

AFAICT, the changes in b9465e8, which solved the issue people are having in kern/minitest-reporters#230, are no longer present in the [5.1.3 source tree](https://github.com/rails/rails/blob/v5.1.3/railties/lib/minitest/rails_plugin.rb).

That's why I theorized that these changes were inadvertently lost as part of some refactoring. The 5.1.2 source tree does not even have that [`railties/lib/minitest/rails_plugin.rb` file](https://github.com/rails/rails/tree/v5.1.2/railties/lib/minitest/rails_plugin.rb) in that location. Instead, it's located at [`railties/lib/rails/test_unit/minitest_plugin.rb`](https://github.com/rails/rails/blob/v5.1.2/railties/lib/rails/test_unit/minitest_plugin.rb) and it *does* have that Minitest plugin load ordering -hack- fix in place.

**Comment by samcday** [comment]
I think I better understand what you're saying now. In the intervening time since b9465e8 a decision was made for Rails to integrate with Minitest as a "regular" Minitest plugin, rather than the runner basically sticking the plugin into the extension list right before running tests.

I'll propose a changeset to minitest-reporters that does exactly what you describe, we'll see if they accept it.

**Comment by kaspth** [comment]
I meant to reference 0d72489b — and somehow got it into my head that that was the commit you were referencing via b9465e8. Sorry about that, I'll eat my hat now 🤠

> I'll propose a changeset to minitest-reporters that does exactly what you describe, we'll see if they accept it.

Cool 👍. Note, it's just one maybe possible solution. It's entirely likely that there's a better way to solve this. I should know, I've been writing and rewriting Rails' minitest integration a couple times over now 😄

I'll close this for now. Do comment here with what you end up with in minitest-reporters, thanks! ❤️

**Comment by samcday** [comment]
I barfed up the kern/minitest-reporters#236 PR last night. We'll see what the `minitest-reporters` maintainer(s) think.

**Comment by kaspth** [comment]
👍( ͡° ͜ʖ ͡°)👍
