### ISSUE TITLE
Plugin generator appends gemfile entry without making sure line is empty

### ISSUE THREAD

**Issue by a-barbieri** [rails/rails#30523]
### Steps to reproduce
1. `rails new foo`
2. `cd foo` 
3. remove empty last line of Gemfile
4. `rails plugin bar`
5. `bundle`

This throws the following error:
```
[!] There was an error parsing `Gemfile`: syntax error, unexpected tIDENTIFIER, expecting end-of-input - ... :mswin, :x64_mingw, :jruby]gem 'baz', path: 'baz'
...                               ^. Bundler cannot continue.

 #  from /Users/abcd/Sites/foo/Gemfile:54
 #  -------------------------------------------
 #  # Windows does not include zoneinfo files, so bundle the tzinfo-data gem
 >  gem 'tzinfo-data', platforms: [:mingw, :mswin, :x64_mingw, :jruby]gem 'baz', path: 'baz'
 #  -------------------------------------------
```

This is probably due to [these lines](https://github.com/rails/rails/blob/master/railties/lib/rails/generators/rails/plugin/plugin_generator.rb#L170-L171). 
```
        entry = "gem '#{name}', path: '#{relative_path}'"
        append_file gemfile_in_app_path, entry
```

A solution could be simply adding `\n`:
```
        entry = "\ngem '#{name}', path: '#{relative_path}'"
        append_file gemfile_in_app_path, entry
```

### Expected behavior
The plugin generator should append `gem 'bar', path: 'bar'` to the application Gemfile on a new line.

### Actual behavior
The plugin generator appends `gem 'bar', path: 'bar'` to the application Gemfile immediately after the latest digit which might not be an empty line. In this case the result is the following: 
```
gem 'tzinfo-data', platforms: [:mingw, :mswin, :x64_mingw, :jruby]gem 'bar', path: 'bar'
```

### System configuration
**Rails version**: 5.1.3

**Ruby version**: 2.3.1

**Comment by y-yagi** [comment]
Thank you for reporting the issue. This issue is solved with #30004.
