### ISSUE TITLE
Repeated method in same callback causes unexpected behavior

### ISSUE THREAD

**Issue by asherkach** [rails/rails#30526]
Specifying `before_save :my_before_save_callback, :my_before_save_callback` causes the specified callback to be run exactly once before a save, not twice as expected.

Specifying `after_update_commit :my_commit_callback` after `after_commit :my_commit_callback` causes the specified callback to only be run only on an update commit (not, e.g., on a create commit).

These may be considered "desired" behavior, based on the `Notes` at the bottom of the [`#define_callback`](http://api.rubyonrails.org/classes/ActiveSupport/Callbacks/ClassMethods.html#method-i-define_callbacks) documentation. If this is the case, better documentation and warning should be provided.

### Steps to reproduce
[GIST](https://gist.github.com/asherkach/daa307675030c4c0429a268b180590b4): Repeated calls to the same method in a [before_save callback](https://gist.github.com/asherkach/daa307675030c4c0429a268b180590b4) are executed only once.

[GIST](https://gist.github.com/asherkach/cd790bc972bfcf9d743d73c0f481ef59): A call to the [after_commit callback](https://gist.github.com/asherkach/cd790bc972bfcf9d743d73c0f481ef59) is not executed on create.

### Expected behavior
The `#my_before_save_callback` method should run twice on save. The `#my_commit_callback` method should run on any commit.

### Actual behavior
The `#my_before_save_callback` method runs once on save. The `#my_commit_callback` method runs only on an update commit.

### System configuration
**Rails version**:
```
$ rails --version
Rails 5.1.3
```
**Ruby version**:
```
$ ruby --version
ruby 2.4.1p111 (2017-03-22 revision 58053) [x86_64-darwin16]
```

### Notes
These issues seem to be very much related, caused by this usage of [`#merge`](https://github.com/rails/rails/blob/ac717d65a31d05458588b78ea7719b79f8ea69e5/activesupport/lib/active_support/callbacks.rb#L851-L853).

**Comment by sgrif** [comment]
Sorry this went so long without a response. While I can see where you're coming from, we generally try to make our class macros idempotent (meaning that calling it with the same arguments any number of times has the same outcome). This fits that mold, and is the expected behavior in my opinion.

**Comment by asherkach** [comment]
Idempotency explains why `before_save :my_before_save_callback, :my_before_save_callback` might only run the callback once, as I would expect this to be equivalent to `before_save :my_before_save_callback; before_save :my_before_save_callback`.

However, I don't think idempotency explains the behavior of `after_commit :my_commit_callback; after_update_commit :my_commit_callback`. The latter command, my registering a callback, has the surprising effect of deregistering a callback (for any non-update commit).

**Comment by asherkach** [comment]
@sgrif, any comment on `after_commit :my_commit_callback; after_update_commit :my_commit_callback` deregistering a callback?

**Comment by eugeneius** [comment]
That issue was previously reported in https://github.com/rails/rails/issues/29554, but the conclusion there was that it was expected behaviour and just needed to be documented.
