### ISSUE TITLE
Terminal corruption when backgrounding then restoring rails console

### ISSUE THREAD

**Issue by oystersauce8** [rails/rails#30537]
### Steps to reproduce

rails c   #means rails console
Control-z # to minimize
fg        # to un-minimize

![terminal_corruption2](https://user-images.githubusercontent.com/10361390/30140917-c5c75114-932c-11e7-90c8-c295b2e278be.gif)

### Expected behavior
The rails console should "work"

### Actual behavior
The terminal is corrupted. What I type is not what's interpreted by the repl. The prompt also looks weird at times. exit doesn't get me back to bash.  the bash command `reset` also canno't be used at this prompt.

### System configuration
rbenv shell 2.4.1
bash 3.2.57
gem install rails -v 5.1.4.rc1
macOS 10.12.6

**Comment by matthewd** [comment]
I imagine this is being caused by spring.. can you confirm that passing `--skip-spring` to `rails new` fixes it?

**Comment by oystersauce8** [comment]
Interesting!  --skip-spring sure seems to make the issue go away

![terminal_corruption3](https://user-images.githubusercontent.com/10361390/30167233-94b87c1a-939a-11e7-95fb-230fd9604583.gif)

I'm working on a production app which is several years old. So it might be too late for me to provide the `--skip-spring` option

**Comment by rohitpaulk** [comment]
@oystersauce8: There's also a `DISABLE_SPRING` env var available.

[![asciicast](https://asciinema.org/a/vmEbqv6plII7vqbLMfS1avBRE.png)](https://asciinema.org/a/vmEbqv6plII7vqbLMfS1avBRE)

**Comment by rafaelfranca** [comment]
Yeah, you can use `DISABLE_SPRING`.
