### ISSUE TITLE
List Available Rails Version

### ISSUE THREAD

**Issue by bparanj** [rails/rails#30530]
### Current Workflow

When you want to update Rails version, you have to go to the releases section of the wiki to figure out the version of Rails available for update.

### Steps to reproduce

rails list 

### Expected behavior

List all available released versions of Rails

### Actual behavior

Provides the help screen

### System configuration

Any officially supported Rails version.
Any officially supported Ruby version

**Comment by sgrif** [comment]
We don't accept feature requests on the issue tracker. You can either open a pull request or submit a thread to the Rails Core mailing list.
