### ISSUE TITLE
[Rails 5.0] Unscope for the join

### ISSUE THREAD

**Issue by Riddlerrr** [rails/rails#30534]
We have 2 models:
```ruby
class DeveloperList < ApplicationRecord
  has_many :developers, -> { unscope(where: :deleted_at) }
end

class Developer < ApplicationRecord
  belongs_to :developer_list
  default_scope { where(deleted_at: nil) }
end
```

With  simple using `has_many` it works as expected:
```ruby
>   DeveloperList.first.developers.count
  DeveloperList Load (0.5ms)  SELECT  "developer_lists".* FROM "developer_lists" ORDER BY "developer_lists"."id" ASC LIMIT ?  [["LIMIT", 1]]
   (0.5ms)  SELECT COUNT(*) FROM "developers" WHERE "developers"."developer_list_id" = ?  [["developer_list_id", 1]]
 => 2
```

But with `join` it doesn't work.
```ruby
> DeveloperList.joins(:developers).count
   (0.5ms)  SELECT COUNT(*) FROM "developer_lists" INNER JOIN "developers" ON "developers"."developer_list_id" = "developer_lists"."id" AND "developers"."deleted_at" IS NULL
 => 1 # should be 2
```

That because in sql still leave the `AND "developers"."deleted_at" IS NULL`.

Rails 5.0.6.rc1 Ruby 2.2.3

In Rails 5.1.4.rc1 (latest `5-1-stable` branch, not release) it works as expected.
I think we need to backport fix from 5.1 rails to 5.0 too.

**Comment by kamipo** [comment]
Yeah, backported in 9d364cc9d2c07bdf74b6eb89bb3d16824acdde6b.

**Comment by estani** [comment]
This still doesn't work if a where clause is added (afaic only count works).

`default_scope` adds the current tenant:

    Billing.unscoped { Tenant.joins(:billing).count }
    SELECT COUNT(*) FROM "tenants" INNER JOIN "billings" ON "billings"."tenant_id" = "tenants"."id"

no tenant id, unscoped *is* working here.

    Billing.unscoped { Tenant.joins(:billing).where(billings: {state: 1})}
    SELECT  "tenants".* FROM "tenants" INNER JOIN "billings" ON "billings"."tenant_id" = "tenants"."id" AND "billings"."tenant_id" = $1 WHERE "billings"."state" = $2 ORDER BY "tenants"."id" ASC LIMIT $3 

All those extra conditions show that unscoped is not being honored here.
