### ISSUE TITLE
Behavior of days is different between Rails5.0 and 5.1

### ISSUE THREAD

**Issue by ponkotuy** [rails/rails#30546]
### Steps to reproduce
```
Time.now.ago(1.days / 2)
```
Results::
Rails5.1.4/5.1.3/5.1.0 => now
Rails5.0.2 => half a day ago

### Expected behavior
Rails5.0.2

### System configuration
Ruby 2.4.1

**Comment by redtachyons** [comment]
Related to #29163 ?

**Comment by ponkotuy** [comment]
I don't understand whether #29163 can solve this issue. But I think it is a close problem.

**Comment by ponkotuy** [comment]
Rails5.1.0 is equal to Rails5.1.3

**Comment by sgrif** [comment]
This seems like the expected behavior to me.
<img width="383" alt="screen shot 2017-09-21 at 5 32 54 pm" src="https://user-images.githubusercontent.com/1529387/30723204-ebdfa12c-9ef2-11e7-8cd4-7bb98b9e8905.png">

**Comment by matthewd** [comment]
Seems surprising to me: `1.to_f / 2` isn't `0.0`, despite having "started" from an integer.

@pixeltrix ?

**Comment by ghiculescu** [comment]
Is this still an issue in Rails 6.1?

**Comment by aried3r** [comment]
@ghiculescu, just tried using Rails 6.1.4.1:

```Ruby
Loading development environment (Rails 6.1.4.1)
2.7.4 [1] » 1 / 2
=> 0
2.7.4 [2] » 1.day / 2
=> 43200 seconds
2.7.4 [3] » 1.0 / 2
=> 0.5
2.7.4 [4] » 1.0.day / 2
=> 0.5 days
```

**Comment by pixeltrix** [comment]
This seems fine as well ```
>> Time.current.at_beginning_of_hour
=> Thu, 09 Sep 2021 15:00:00.000000000 BST +01:00
>> Time.current.at_beginning_of_hour.ago(1.day / 2)
=> Thu, 09 Sep 2021 03:00:00.000000000 BST +01:00
```
