### ISSUE TITLE
Rails destroy session problem

### ISSUE THREAD

**Issue by akshay18496** [rails/rails#30545]
### Steps to reproduce

(Guidelines for creating a bug report are [available
here](http://guides.rubyonrails.org/contributing_to_ruby_on_rails.html#creating-a-bug-report))

### Expected behavior
DELETE function not working in my rails app code
= link_to "Delete", (@job), method: :delete, data: { confirm: "Are you sure?" }
other issue is ones i signed in then signout not working i am useing devise gem
### Actual behavior
activesupport (5.1.3) lib/active_support/tagged_logging.rb:26:in `tagged'
activesupport (5.1.3) lib/active_support/tagged_logging.rb:69:in `tagged'
railties (5.1.3) lib/rails/rack/logger.rb:24:in `call'
sprockets-rails (3.2.0) lib/sprockets/rails/quiet_assets.rb:13:in `call'
actionpack (5.1.3) lib/action_dispatch/middleware/remote_ip.rb:79:in `call'
actionpack (5.1.3) lib/action_dispatch/middleware/request_id.rb:25:in `call'
rack (2.0.3) lib/rack/method_override.rb:22:in `call'
rack (2.0.3) lib/rack/runtime.rb:22:in `call'
activesupport (5.1.3) lib/active_support/cache/strategy/local_cache_middleware.rb:27:in `call'
actionpack (5.1.3) lib/action_dispatch/middleware/executor.rb:12:in `call'
actionpack (5.1.3) lib/action_dispatch/middleware/static.rb:125:in `call'
rack (2.0.3) lib/rack/sendfile.rb:111:in `call'
railties (5.1.3) lib/rails/engine.rb:522:in `call'
puma (3.9.1) lib/puma/configuration.rb:224:in `call'
puma (3.9.1) lib/puma/server.rb:602:in `handle_request'
puma (3.9.1) lib/puma/server.rb:435:in `process_client'
puma (3.9.1) lib/puma/server.rb:299:in `block in run'
puma (3.9.1) lib/puma/thread_pool.rb:120:in `call'
puma (3.9.1) lib/puma/thread_pool.rb:120:in `block in spawn_thread'
ERROR 

### System configuration
**Rails version**:
5
**Ruby version**:
ruby 2.2.6p396 (2016-11-15 revision 56800) [i386-mingw32]

**Comment by BigChief45** [comment]
Try restarting your server. Also check that your controller's `destroy` action is correct, and you have valid route for that.

**Comment by akshay18496** [comment]
solved  i missed , //= require jquery_ujs in application.js

**Comment by utilum** [comment]
@akshay18496 care to close your ticket then?
