### ISSUE TITLE
ActiveRecord::HasManyThroughNestedAssociationsAreReadonly when using has_many through belongs_to relation

### ISSUE THREAD

**Issue by ciembor** [rails/rails#30566]
### Steps to reproduce

Create model `Document`.
Create model `Version`.
Create model `Section`.
Add `HABTM` between versions and sections.
Document `belongs_to :current_version, class_name: "Version"`
Document `has_many :sections, through: :current_version`
Document `accepts_nested_attributes_for :current_version, :sections`
Try to update sections from a document level.

### Expected behavior
`document.update(sections: sections)` should work the same as `document.current_version.update(sections: sections)`.

### Actual behavior
`ActiveRecord::HasManyThroughNestedAssociationsAreReadonly: Cannot modify association 'Document#sections' because it goes through more than one other association.`

### System configuration
**Rails version**: `5.0.5`

**Ruby version**: `2.4.1p111`

**Comment by alexcameron89** [comment]
Hey @ciembor, can you create a reproducible bug script from [this template](https://github.com/rails/rails/blob/master/guides/bug_report_templates/active_record_master.rb)? That will make it easier for us to reproduce your issue and understand your schema and associations.

**Comment by ciembor** [comment]
I don't have time at the moment, but I will try to find some in the future... this problem was discussed before and I have to understand why has many through nested associations are read only in general, then I would know if it's a case that could be supported or a #wontfix.

**Comment by yatindrarao** [comment]
Here is a script to reproduce this issue.
https://gist.github.com/yatindrarao/ca1f43cf80de123710722be1d4623fbb
