### ISSUE TITLE
Can auto update columns which keep same value to parent's columns in child model when parent model changed?

### ISSUE THREAD

**Issue by excosy** [rails/rails#30565]
### This is not a bug
For instance, there are two models: 
```
class Room < ActiveRecord::Base
  belongs_to :location, required: true
  has_many :desks, dependent: :destroy
end

class Desk < ActiveRecord::Base
  belongs_to :location, required: true
  belongs_to :room
end
```
Both of them have `location_id`, when room's location_id is changed, expect desks' location_id are changed as same.
Can we write as this
```
  has_many :desks, dependent: :destroy, inherited: %w[location_id]
```
or
``` 
  # for child model has different column name with parent model
  has_many :desks, dependent: :destroy, inherited: {location_id: :location_id}
```
to auto update or fill(on creating) child model's columns which keep same value to parent column?

**Comment by PHedkvist** [comment]
I would suggest looking the callback after_save [here](http://guides.rubyonrails.org/active_record_callbacks.html) and update all child objects. But I would probably look at the parent location if they are going to be same anyway.

**Comment by matthewd** [comment]
Please use the mailing list or StackOverflow for questions/help, where a wider community will be able to help you. We reserve the issues tracker for issues only.
