### ISSUE TITLE
Rails server do not output any logs when run as a daemon

### ISSUE THREAD

**Issue by jjyr** [rails/rails#30567]
### Steps to reproduce
``` shell
rails -v # Rails 5.1.4
rails new test_app
cd test_app && bundle exec rails s -d
cat log/development.log # nothing
```
I use `RAILS_ENV=development puma -d ....` to launch server and it works, so it's not a puma bug.

### Expected behavior
Server log should output to `log/development.log`, just like non-daemon mode

### Actual behavior
nothing output

### System configuration
**Rails version**:
Rails 5.1.4
**Ruby version**:
ruby 2.4.1p111 (2017-03-22 revision 58053) [x86_64-darwin16]
**Puma version**:
puma version 3.10.0

**Comment by y-yagi** [comment]
Hmmm. I can't reproduce issue with your steps(log output correctly).
Can you please upload a sample Rails application which demonstrates your issue?

**Comment by PHedkvist** [comment]
I am currently looking into this, so far I have found that a variable called `@log_stdout` inside railties/lib/rails/commands/server/server_commanrd.rb is set so that if the daemon flag exists, the variable will contain this `@log_stdout = options[:daemon].blank? && (options[:environment] || Rails.env) == "development"`. It seems unreasonable to have `options[:daemon].blank?` when the daemon flag is provided. I cant find any reason for not logging when the daemon flag is provided.

**Comment by y-yagi** [comment]
If the `daemon` option is specified, since the terminal is likely to be closed, so it makes sense to suppress log output of stdout. 
However, just logging to stdout is only suppressed, the log to the file(`log/development.log`) is written.

**Comment by PHedkvist** [comment]
Yes, ok I understand, my mistake. I cant reproduce the issue using 5.1.4 either.

**Comment by jjyr** [comment]
![image](https://user-images.githubusercontent.com/1695400/31553279-8b7696ac-b06c-11e7-8854-04142ac619ed.png)

I tried to reproduce on my mac, seems `FATAL: prematurely zombied` caused by fsevent_watch, the pid file is created but server not start.

I'm not sure is it a same issue I described early..

**Comment by y-yagi** [comment]
Can you create an application with the `--skip-listen` option and check whether the problem appears? 

```
rails new test_app --skip-listen  
cd test_app && bundle exec rails s -d
```
Your issue seems like a problem with `listen` gem. Ref: #26158

**Comment by jjyr** [comment]
It works

**Comment by rraallvv** [comment]
Is there a way to enable log when starting the app with -d on rails v4.2.10 ?

**Comment by vinyll** [comment]
That seems to work for a new app, but how would you set that `skip-listen` parameter with an existing app?

**Comment by shopify01** [comment]
> That seems to work for a new app, but how would you set that `skip-listen` parameter with an existing app?

facing the same issue.
