### ISSUE TITLE
ActiveRecord validations being disabled on unicorn restart

### ISSUE THREAD

**Issue by felixthemagnificent** [rails/rails#30599]
ActiveRecord validation rules and callbacks for all models of app has been disabled after unicorn restart (from log rotation script). Here it is

```
/var/www/fitness_crm/shared/log/production.log
/var/www/fitness_crm/shared/log/unicorn.stderr.log
/var/www/fitness_crm/shared/log/unicorn.stdout.log {
        daily
        missingok
        rotate 30
        compress
        notifempty
        create 640 deploy deploy
        sharedscripts
        postrotate
                kill -s USR2 `cat /var/www/fitness_crm/shared/tmp/pids/unicorn.pid`
        endscript
}
```
We've changed the script to send USR1 instead of USR2, but nothing has changed. When USR1 is sent validations/callbacks simply keep being disabled. Here is our unicorn configuration file

```
working_directory "/var/www/fitness_crm/current"
pid "/var/www/fitness_crm/shared/tmp/pids/unicorn.pid"
stdout_path "/var/www/fitness_crm/shared/log/unicorn.stdout.log"
stderr_path "/var/www/fitness_crm/shared/log/unicorn.stderr.log"

listen "/tmp/unicorn.fitness_crm_production.sock"

worker_processes 8
timeout 30

preload_app true

before_exec do |server|
  ENV["BUNDLE_GEMFILE"] = "/var/www/fitness_crm/current/Gemfile"
end

before_fork do |server, worker|
  # Disconnect since the database connection will not carry over
  if defined? ActiveRecord::Base
    ActiveRecord::Base.connection.disconnect!
  end

  # Quit the old unicorn process
  old_pid = "#{server.config[:pid]}.oldbin"
  if File.exists?(old_pid) && server.pid != old_pid
    begin
      Process.kill("QUIT", File.read(old_pid).to_i)
    rescue Errno::ENOENT, Errno::ESRCH
      # someone else did our job for us
    end
  end

  if defined?(Resque)
    Resque.redis.quit
  end

  sleep 1
end

after_fork do |server, worker|
  # Start up the database connection again in the worker
  if defined?(ActiveRecord::Base)
    ActiveRecord::Base.establish_connection
  end

  if defined?(Resque)
    Resque.redis = 'localhost:6379'
  end
end
```

After this we kill unicorn and start it manually with command:

`bundle exec unicorn -D -c /var/www/fitness_crm/shared/config/unicorn.rb -E production`

After this everything is good and validations and callbacks are enabled again. Please, help to find out what is the reason of such a behavior and how to fix it.

We use Ruby v2.2.3, Rails v4.2.4, Unicorn v5.1.0 in production.

**Comment by al2o3cr** [comment]
Seems odd that `USR1` would cause this behavior; the Unicorn docs state that that signal tells the master process (& children) only to reopen their log files.

When 4.2.10 is released (soon, I'm guessing - it's in RC right now) I'd recommend you try upgrading to see if the issue still happens. I'm not aware of any relevant changes in that release vs 4.2.2, but it's good to check.

Other than that, it's going to be very difficult to debug this issue without more information about your environment - what other gems are you using? Are you doing anything unusual with class loading or validations?

The ideal thing to debug with would be a Rails app that manifests the described behavior when run with Unicorn.
