### ISSUE TITLE
Active_admin rails problem

### ISSUE THREAD

**Issue by akshay18496** [rails/rails#30594]
### Steps to reproduce

(Guidelines for creating a bug report are [available
here](http://guides.rubyonrails.org/contributing_to_ruby_on_rails.html#creating-a-bug-report))

### Expected behavior
active admin not working in rails (Rails 5)

### Actual behavior
In terminal 
Started GET "/admin" for 127.0.0.1 at 2017-09-13 20:52:14 +0300
Processing by Admin::DashboardController#index as HTML
Completed 401 Unauthorized in 79ms

Started GET "/admin/login" for 127.0.0.1 at 2017-09-13 20:52:16 +0300
Processing by ActiveAdmin::Devise::SessionsController#new as HTML
  Rendering C:/RailsInstaller/Ruby2.2.0/lib/ruby/gems/2.2.0/bundler/gems/activeadmin-acff8334b3c3/app/views/active_admin/devise/sessions/new.html.erb within layouts/active_admin_logged_out
Completed 500 Internal Server Error in 3761ms (ActiveRecord: 10.0ms)

### System configuration
**Rails version**:
Rails 5.1.4
**Ruby version**:
ruby 2.2.6p396 (2016-11-15 revision 56800) [i386-mingw32]

**Comment by rafaelfranca** [comment]
Please open an issue in the Active Admin repository.
