### ISSUE TITLE
String truncate returns result with size greater than :length when :length is smaller than omission length

### ISSUE THREAD

**Issue by danielkman** [rails/rails#30600]
### Steps to reproduce
Create a string with size greater than 2
call truncate with length 2
### Expected behavior
"this is a test".truncate(2) should return ".." or empty string

### Actual behavior
"this is a test".truncate(2) returns "..." which is longer than 2 

### System configuration
**Rails version**:4.2.6

**Ruby version**:ruby 2.2.4p230 (2015-12-16 revision 53155) [x86_64-darwin16]

**Comment by steverob** [comment]
@danielkman curious to how this edge case is affecting your app. :)

**Comment by danielkman** [comment]
@steverob It's not really, I've been playing around with truncate and noticed this behaviour. I'll be happy to submit a PR for it.

**Comment by matthewd** [comment]
This is by design; the omission value is inviolable, and a blank string would be even more surprising.

I'd suggest just not doing that :smile:
