### ISSUE TITLE
ActiveRelation with pop different behavior on Rails 5

### ISSUE THREAD

**Issue by maxforasteiro** [rails/rails#30612]
Hey there!

I'm having some wierd behavior on Rails 5.0.6 comparing with 4.1.14.1...

### Steps to reproduce
Lets say that we have an `Foo` object that inherit from ActiveRecord:Base, we can do something like `Foo.limit(3)`, right?

### Expected behavior

In Rails 4.1.14.1 when I execute something like

```
foo = Foo.limit(3)
foo.count
=> 3
foo.to_a.pop
foo.count
=> 2
```

The `foo` object after the pop is a ActiveRelation with 2 elements

### Actual behavior

```
foo = Foo.limit(3)
foo.count
=> 3
foo.to_a.pop
foo.count
=> 3
```

In Rails 5.0.6 when I execute the same code, my `foo` object is a ActiveRelation too but has 3 elements, like the pop method didn't do anything...

### System configuration
**Rails version:**
New one: 5.0.6
Old one:  4.1.14.1

**Ruby version:**
2.2.3

**Comment by redtachyons** [comment]
Same behavior is rails 4.2.9 as well. rails 4.1 behavior seems buggy to me

**Comment by ab320012** [comment]
4.1 
```
# to_a seems to modify the variable foo in place
foo.to_a.pop # makes foo an array and pops the first off array
foo.count # calls count on array object

```
4.26 + ? 
```
foo.to_a.pop  # returns a new array then calls pop on array. foo is still ActiveRecord::Relation
foo.count # calls count on original ActiveRecord::Relation 

# the following works as expected
bar=  foo.to_a
bar.count 
=> 3  
bar.pop
bar.count
=> 2  
```

**Comment by maxforasteiro** [comment]
@redtachyons yeah, it seems a buggy for me too... I was just wondering why and how this behavior changed on Rails 5.

@ab320012 ok `foo.count` makes the method on a Array, but if i ask for `foo.class` it will still return `Foo::ActiveRecord_Relation` even after the pop call. (Oh, and pop removes the last element off the array, not the first one)

**Comment by sgrif** [comment]
This is the expected behavior. `ActiveRecord::Relation` objects are not arrays, and you should not assume that mutating `to_a` would mutate the relation.
