### ISSUE TITLE
Rails 4 STI first_or_create! callback problem

### ISSUE THREAD

**Issue by tomgi** [rails/rails#30663]
### Steps to reproduce

Run this code
https://gist.github.com/tomgi/447b2e7458ffc64ad662f4cd9a381347

### Expected behavior
When having `Animal`, `Cat` and `Dog` STI models
Then `Cat.all` should never return any `Dog`

### Actual behavior

`Cat.all` returns all animals when called inside `Dog`'s `after_save` callback, when `Dog` is created using `first_or_create!`

### System configuration
**Rails version**: 4.2.9 (works in ~5)

**Ruby version**: 2.3.1

**Comment by sgrif** [comment]
Rails 4 only receives security fixes as per our support policy.
