### ISSUE TITLE
can no longer pass directory to rails test runner

### ISSUE THREAD

**Issue by jjb** [rails/rails#30660]
As of this change: f2bd6d85729cb31b08d77061cf3c7497b4c93393 introduced in 5.1.3

I can no longer pass a directory to the test runner. It seems to ignore directories and just run the whole suite.

Previously, the only way I could run my system tests was with `rails test test` (whole suite) or `rails test test/system` (just system test). `rails test` never ran system tests. This might be another unrelated issue, and/or maybe it's the reason the bug I'm reporting in this issue became apparent to me.

### rails 5.1.2

the failure is expected, i put it there to make sure the system tests were running

```
$ rails test test/system/
Run options: --seed 51172

# Running:

starting puma config
ending puma config
Puma starting in single mode...
* Version 3.9.1 (ruby 2.4.1-p111), codename: Private Caller
* Min threads: 0, max threads: 1
* Environment: test
* Listening on tcp://0.0.0.0:31337
Use Ctrl-C to stop
........[Screenshot]: tmp/screenshots/failures_test_account_deletion_is_available_for_trial_users.png

E

Error:
AccountManagementTest#test_account_deletion_is_available_for_trial_users:
Capybara::ElementNotFound: Unable to find link or button "Delete account"
    test/system/account_management_test.rb:8:in `block in <class:AccountManagementTest>'


bin/rails test test/system/account_management_test.rb:5

.........

Finished in 41.742681s, 0.4312 runs/s, 1.2936 assertions/s.
18 runs, 54 assertions, 0 failures, 1 errors, 0 skips
```

### rails 5.1.3

```
$ rails test test/system/
Run options: --seed 63188

# Running:

......................................................................................................................................................................

Finished in 12.453183s, 13.3299 runs/s, 37.5808 assertions/s.
166 runs, 468 assertions, 0 failures, 0 errors, 0 skips
```

**Comment by ccasabona** [comment]
The issue with the ending forward slash.  The system tests will run if one enters the command as

rails test test/system

Appending a forward slash at the end of the command causes the entire test suite to run, as in:

rails test test/system/

I noticed that this command will now run the system tests in Rails 5.1.4:

rails test:system

**Comment by jjb** [comment]
Thanks for your recommendation.

`rails test test/system` and `rails test:system` do indeed run only my system tests.

`rails test test` still runs everything but my system tests

I'll wait to hear back from rails devs on if the behavior change I described above is expected/desired.

**Comment by ccasabona** [comment]
I forgot to say that the command, rails test (or rails test test, as you are using) runs all the tests but the system ones by design.  

http://guides.rubyonrails.org/testing.html#system-testing

**Comment by eileencodes** [comment]
Yes @ccasabona is correct, this is by design.

Running the test directory shouldn't run the system tests. If you need system tests to run with the whole suite you can add a custom task. I'd also accept a PR for a `rails test:all` or something like that to run everything.

**Comment by jjb** [comment]
@eileencodes gotcha, thanks for the info!

So the fact that `rails test test` was running all tests before 5.1.3 was an unintended behavior that we are okay losing?

**Comment by eileencodes** [comment]
I'm confused. Except for the first RC for 5.1 you were never able to run system tests with `rails test`. Are there other tests not running in 5.1.3?

**Comment by jjb** [comment]
@eileencodes 

First of all, I apologize for my poorly presented issue, which sort of addresses 1.5 things at the same time.

> I'm confused. Except for the first RC for 5.1 you were never able to run system tests with rails test. Are there other tests not running in 5.1.3?

Correct, `rails test` never ran system tests. I'm talking about `rails test test`, which in 5.1.2 would run all tests, including system tests.

**Comment by eileencodes** [comment]
No worries!

If `rails test test` was running system tests that was a bug so the behavior in 5.1.3 is correct.
