### ISSUE TITLE
ActiveJob enqueued but not performed

### ISSUE THREAD

**Issue by wzdot** [rails/rails#30670]
### Steps to reproduce

in config/application.rb
```
config.active_job.queue_adapter = :sidekiq
```
in config/initializers/sidekiq.rb
```
Sidekiq.configure_server do |config|
  config.redis = {url: '127.0.0.1:6379'}
end
Sidekiq.configure_client do |config|
  config.redis =  {url: '127.0.0.1:6379'}
end
```
in config/sidekiq.yml
```
:queues:
  - [task, 10]
  - [default, 5]
```
in Procfile
```
sidekiq: bundle exec sidekiq -C config/sidekiq.yml
```
in app/jobs/task_job.rb
```
class TaskJob < ApplicationJob
  queue_as :task

  def perform(serial_no)
    logger.info(serial_no)
  end
end
```
### Expected behavior
```
# TaskJob.perform_later('aXcdGy')

[ActiveJob] [TaskJob] [3c36a31b-c495-41ee-898e-cf9f896c1bcd] aXcdGy
[ActiveJob] [TaskJob] [3c36a31b-c495-41ee-898e-cf9f896c1bcd] Performed TaskJob (Job ID: 3c36a31b-c495-41ee-898e-cf9f896c1bcd) from Sidekiq(development.task) in 0.49ms
```
### Actual behavior
```
# TaskJob.perform_later('aXcdGy')

[ActiveJob] Enqueued TaskJob (Job ID: 7dfaef27-b1d1-43ff-b964-cb2716ab975c) to Sidekiq(development.task) with arguments: aXcdGy
```
Job was enquened, but not performed. And I show the job not pop by sidekiq web ui.

if I change app/jobs/task_job.rb to
```
class TaskJob
  include Sidekiq::Worker
  def perform(serial_no)
    logger.info(serial_no)
  end
end

# TaskJob.perform_async('aXcdGy')
```
It will performed successful.

### System configuration
**Rails version**:
5.1.3
**Ruby version**:
2.4.1p111
**Sidekiq version**:
4.2.10

**Comment by y-yagi** [comment]
> [ActiveJob] Enqueued TaskJob (Job ID: 7dfaef27-b1d1-43ff-b964-cb2716ab975c) to Sidekiq(development.task) with arguments: aXcdGy

This log shows that the queue name of your job is `development.task` instead of `task`. 
Perhaps did you specify `config.active_job.queue_name_prefix`? 
If so, you need to specify a value that includes prefix for the queue name of `config/sidekiq.yml`.  As following: 

```
:queues:
  - [task, 10]
  - [development.task, 10]
  - [default, 5]
```

**Comment by wzdot** [comment]
Thank you! I was too careless。
