### ISSUE TITLE
ActionCable repeatedly successful connect, but connect never called, and constantly disconnecting.

### ISSUE THREAD

**Issue by asoap** [rails/rails#30678]
### Steps to reproduce

I am not sure how to reproduce this.  I've setup action cable before.  I'm setting it up again this time on project without active record and using mongoid.  Also this is rails 5.1.3.   Also I'm developing my project using a virtual machine, which I've successfully used before.

### Expected behavior

A websocket connection that stays connected.

### Actual behavior

It constantly sends requests to the server to establish a connection. 

![image](https://user-images.githubusercontent.com/512430/30709722-2ea40cb8-9ed1-11e7-8c05-04bfa5cf88f3.png)

![image](https://user-images.githubusercontent.com/512430/30709782-640e7fc8-9ed1-11e7-82bb-889a291912ee.png)

These frames are empty in case any one is curious.  The first frame is subscribing to a channel.

![image](https://user-images.githubusercontent.com/512430/30709866-aa8c4a16-9ed1-11e7-989a-285cde4a8b3a.png)

I have attempted to use async and redis.  And I'm baffled.  Is there supposed to be some sort of handoff that's not happening?   Without an error message I'm left confused.

I have console logs in the JS for the channel.  It only executes the disconnected code, and never the connected code.  

### System configuration
Rails 5.1.3

Ruby 2.3.1

Using Puma as well.

Developing on Windows with Ubuntu in a virtual machine. 

Also starting rails with -b 0.0.0.0

**Comment by asoap** [comment]
I managed to fix it.  I'm not exactly sure what caused it.  I've been ripping my hair out.  I built a new rails project and jumped right into action cable.  And it worked just like it should.  The older project is 5.1.3, and the one I just created was 5.1.4.  I don't think that made much of a difference.  

I ended up copying my previous project to the new project and it was still working fine.  I then copied the config folder from the new project into the old one.  Then the old project started working as expected.  So I'm guessing something in my config files was causing it.

**Comment by progapandist** [comment]
@asoap, you saved my dignity, I spent a day trying to debug the same thing and removing that line helped!

**Comment by ThompZon** [comment]
@asoap This fixed the issue for me! 

With it set to false, only the channel's `disconnected `-function (defined in *.coffee-file) is called, with `reload_classes_only_on_change = true` connected is called as expected, followed by received when sending data there. 

I am running:
Rails 5.1.4
ruby 2.4.2p198 (2017-09-14 revision 59899) [x86_64-linux]
puma version 3.10.0
`config.force_ssl = true`

in a Vagrant box (virtual machine with windows host)

**Comment by bp974** [comment]
I also had a similar problem to this but was using the thin webserver. For other people running into this issue ensure you are not using thin as your server. ActionCable will not work with the thin server.

**Comment by sarmad90** [comment]
Thanks @asoap . It worked for me. But did anyone figure out why was this a problem?

**Comment by joshleblanc** [comment]
This problem also occurs when your actioncable adapter is redis, and redis isn't running.

**Comment by shadiramadan** [comment]
After a license issue forcing me to update to the latest rails 5 I have the same issue when my adapter is redis (yes it is running and a can connect using Redis.new).  I went crazy and updated to rails 6 and still have the same exact issue.

**Comment by Tashows** [comment]
I am facing the same issue as well.
Rails 6.1.4.1
ruby 3.0.1p64 (2021-04-05 revision 0fb782ee38) [x86_64-linux]
Puma version: 5.4.0 (ruby 3.0.1-p64) ("Super Flight")

`reload_classes_only_on_change` is not present in my codebase (it is set to true in Rails::Application::Configuration#initialize).
I am facing this only in production. Server is on DigitalOcean, using dokku and dokku-redis plugin. Everything seems to be working and the Redis service is running and is connected to the application. Running Redis.new via in-app cli connects. Any other clues?
