### ISSUE TITLE
ORM creates wrong sql-query if ids is kind of Set

### ISSUE THREAD

**Issue by mr-dxdy** [rails/rails#30684]
Hi!

Rails: 4.2.7
Ruby: 2.2.4

``` ruby
User.where(id: Set.new([1, 2])).to_sql
=> "SELECT \"users\".* FROM \"users\" WHERE \"users\".\"id\" = NULL"

User.where(id: [1, 2]).to_sql
=> "SELECT \"users\".* FROM \"users\" WHERE \"users\".\"id\" IN (1, 2)"
```

**Comment by al2o3cr** [comment]
Short-term fix: use `to_a` on the `Set` before handing it to `where`.

Longer-term, seems like there would need to be a `PredicateBuilder` handler for `Set`.

**Comment by ccasabona** [comment]
It works if the Set is converted to an array:

` User.where(id: Set.new([1, 2]).to_a).to_sql`
`"SELECT \"users\".* FROM \"users\" WHERE \"users\".\"id\" IN (1, 2)" `

**Comment by michaldarda** [comment]
I've added test case https://gist.github.com/michaldarda/b2dd81731cba180904def87f508cfc3d
