### ISSUE TITLE
rails_ujs not trigger events when we replace dom.

### ISSUE THREAD

**Issue by madmax** [rails/rails#30692]
When we send remote form and render js.erb that will replace current form with new one (for example validation errors) we are not longer able to observer ajax:complete event because original form is removed from dom end event triggered by rails wont work. 

Before removing jquery there was possibility to observer ajaxStop event now this is not longer working. 

Maybe there should be also global event for ajax:complete? 
### System configuration
Rails. 5.1.4

**Comment by pabse** [comment]
Anyone still working on this?

In my case I want to use remote pagination. But when I replace the paginator elements in my .js.erb file, `ajax:complete` does not get triggered.

I'm showing a loading animation when `ajax:before` gets fired and remove this animation on `ajax:complete`.
In the above case, if I clock on "next" the `ajax:before` gets called, but `ajax:complete` is missing.

**Comment by RuanAyram** [comment]
Anyone still working on this?

**Comment by madmax** [comment]
Here is my solution for this problem (sorry for coffeescript)

```
class window.Dom
  @ajaxComplete: (callback) =>
    document.addEventListener("ajax:before", (event) ->
      event.target.addEventListener("ajax:complete", callback)
    )
```

Dom.ajaxComplete yourmethod
