### ISSUE TITLE
NoMethodError: undefined method `logger' for MyClass

### ISSUE THREAD

**Issue by PerjuAndrei** [rails/rails#30701]
Hi. I'm currently upgrading a Rails application from 4.2.7.1 to 5.0.6 and got the following issue.

### Steps to reproduce
I created a gem and for naming purpose added the controllers inside a module. In those controllers I don't have access to 'logger' method.  After debugging I found that it fails in this method: https://github.com/rails/rails/blob/v5.0.6/activerecord/lib/active_record/railties/controller_runtime.rb#L21 
### Expected behavior
The application should handle this.

### Actual behavior
The test suite fails with `NoMethodError: undefined method 'logger' for MyClass`.

### System configuration
**Rails version**:
Rails 5.0.6
**Ruby version**:
ruby 2.3.1p112 (2016-04-26 revision 54768) [x86_64-darwin16]

For now I added in my ApplicationController:
`def logger
Rails.logger
end`

**Comment by kinnrot** [comment]
@PerjuAndrei I couldn't understand how to reproduce the issue, could you elaborate or maybe provide a failing test case ?

**Comment by rafaelfranca** [comment]
`ActionController::Base` has a `logger` method defined. https://github.com/rails/rails/blob/v5.0.6/actionpack/lib/abstract_controller/logger.rb#L8. If your controller is not working look if it is inheriting from the right class or if any gem is not removing that method.
