### ISSUE TITLE
VERSION in environment value used for rake db:migrate causing catastrophic issues

### ISSUE THREAD

**Issue by sreekanthgs** [rails/rails#30707]
### Steps to reproduce

export VERSION=0.1.11
bundle exec rake db:migrate

### Expected behavior
DB Migration should happen without considering VERSION, since VERSION variable was not set for this purpose. It could have been set by an independent application. In our case, it was set as docker container version for the rails app to use and show in view.

### Actual behavior
VERSION variable is taken into account and rollback was executed to some random point.

### System configuration
**Rails version**: 5.1.x
**Ruby version**: 2.4.1

PS: Kindly do not say this is default or expected behaviour of rails or activerecord or rake. Thank you.

**Comment by georgeclaghorn** [comment]
This is the [documented behavior](http://guides.rubyonrails.org/active_record_migrations.html#running-migrations) of `rails db:migrate`.

**Comment by sayuj** [comment]
At least think about having some other variable name than VERSION, which is generic. Would save hours of debugging and financial loss incurring on production db.

**Comment by sreekanthgs** [comment]
@dhh @sgrif, would be great if you can voice your opinions.

**Comment by redtachyons** [comment]
`VERSION` is a documented feature and it is in rails for a long time, so people relying on this behavior. But since ENV variables having global scope, it is better have explicit names for environment variables

**Comment by matthewd** [comment]
If you want to PR a change that makes it fail if the version is an unexpected format, that seems worth consideration.

Insisting that more people spend their time to restate something so obvious you noted it in the description, on the other hand, is unproductive.

**Comment by sreekanthgs** [comment]
Still not getting the idea why a generic environment variable be used application specific and call it behaviour of any kind.

And yes, a PR is the final target of this. Pulling people into this is to just state an obvious point that things that dont agree with common sense get pushed onto developers under the pretense of behaviour.

Apologies for the harsh tone, my three PR got closed just because it was not according to the "behaviour". Its as good as saying a bug is a feature.

**Comment by eileencodes** [comment]
@sreekanthgs can you take a look at https://github.com/rails/rails/pull/30714 and let me know if this fixes your usecase?

Our use of `VERSION` as an env var for migrations has been in use for a long time, but I understand the frustration you're feeling. If we were to change the env var name, we wouldn't be able to release it until Rails 5.2 or 6 since it's a change in behavior of a feature. Do you have a recommendation on another solution if the above doesn't work for you?

**Comment by sreekanthgs** [comment]
Thank you @eileencodes for hearing out my worries. I understand that VERSION as an argument as well as an env var has been in place for quite some time and we can't deprecate it overnight.

My suggestion would be to introduce a new variable which is not generic, say, DB_SCHEMA_VERSION and phase deprecate the VERSION tag over one or two major/feature releases of rails. In the meantime, as all has suggested, introduce a sanity to check to avoid conflicting behaviour.

The point being, Ideally, applications should not use generic variables when consumed from environment variables. We cant quite be certain that it won't be producing unexpected behaviour. 

In our case, we could quickly figure out the schema rollback (had some production tables got dropped) was due to the VERSION env we passed as -e switch param to the Docker run command. Others might not be that lucky.

Once again, Thank you @eileencodes for not just stating it is default/expected/documented behaviour, and for hearing me out.

**Comment by bogdanvlviv** [comment]
@eileencodes, @sreekanthgs
https://github.com/rails/rails/pull/30714 doesn't fix completely the current problem but prevents from rollback all migrations when `VERSION` is a negative number.

We always do `VERSION.to_i` in the sourcecode
so if `VERSION=0.1.11` (as in this issue) then `"0.1.11".to_i # => 0`
but `0` is acceptable see http://edgeguides.rubyonrails.org/engines.html#engine-setup

Thanks!

**Comment by ParadoXxGER** [comment]
I ran also into this issue, thanks to this i spent 4 hours asking myself if i am completely messed up my migrations. Great. 💯
