### ISSUE TITLE
why not delegate broadcast_to to class

### ISSUE THREAD

**Issue by pynixwang** [rails/rails#30719]
https://github.com/rails/rails/blob/813af4655f9bf3c712cf50205eebd337070cee52/actioncable/lib/action_cable/channel/broadcasting.rb#L8

or make a broadcast_for model method.

```
stream_from broadcasting
stream_for model
broadcast_to broadcasting
broadcast_for model
```

**Comment by y-yagi** [comment]
Please use the [mailing list](https://groups.google.com/forum/#!forum/rubyonrails-talk) or StackOverflow for questions/help, where a wider community will be able to help you. We reserve the issues tracker for issues only. Thanks.
