### ISSUE TITLE
Encrypted secrets not being read in some rake tasks

### ISSUE THREAD

**Issue by sintro** [rails/rails#30717]
### Steps to reproduce
Try to perform `RAILS_ENV=production rails db:drop` with correctly setup of secrets.yml.enc with 'secret_key_base' variable. To handy error indication also 'devise' gem is needed, so it will raise error if no 'secret_key_base' variable was read. To read the variable from new secrets store, add ``config.secret_key = Rails.application.secrets.devise_secret_key if Rails.env.production?`` to devise.rb.
``config.read_encrypted_secrets = true`` is set in production.rb.
PS It is not only devise-related problem, some strange errors with the rest of variables happens also.
### Expected behavior
Successful database dropping (for sure with correct credentials are in place).
### Actual behavior
`Devise.secret_key was not set. Please add the following to your Devise initializer`. 
Some other rake tasks still works fine (db:migrate etc.)
There is no such problem in RAILS_ENV=development.
### Way to solve
If you move `config.read_encrypted_secrets = true` from `environments\production.rb` to `application.rb`, looks like every errors related to unread secrets are gone. For some reason config files in different environments are loaded in different orders, and probably in production a lot of them are loaded before ``config.read_encrypted_secrets = true`` will be hit.
### System configuration
**Rails version**:
5.1.3
**Ruby version**:
ruby 2.4.2p198 
Windows 7

**Comment by vochicong** [comment]
Thanks for your report.
Since I actually don't want to use encrypted secrets for development and test,
I've added the following into my `config/application.rb`
```
    # to use encrypted secrets in rake tasks on production env
    config.read_encrypted_secrets = (Rails.env == 'production') 
```

**Comment by kaspth** [comment]
@y-yagi do you remember something related to this?

**Comment by y-yagi** [comment]
There seems to be tasks that is missing environment loading. I created a PR. #31135

**Comment by thedumbtechguy** [comment]
@y-yagi you are correct. Saved me!
