### ISSUE TITLE
Active storage direct upload not working for s3

### ISSUE THREAD

**Issue by hahmed** [rails/rails#30723]
### Steps to reproduce

New rails app, with active storage using amazon s3 for storage, added policy to user and CORS config.

The model:

```
class Episode < ApplicationRecord
  has_one_attached :video

  validates :name, presence: true
  validates :video, presence: true
end
```
 
The view:

```
  <div class="form-group">
    <%= form.label :video %>
    <%= form.file_field :video, class: 'form-control-file', direct_upload: true %>
  </div>
```

Attach the upload to the video like so:

`@episode.video.attach(params[:episode][:video])`

If I remove the direct_upload, the file get's created in s3 successfully, if I add `direct_upload: true`, the upload does not work.

### Expected behavior
File should be uploaded to s3

Note: Direct uploads to file storage (`Rails.root.join("tmp/storage")`) works, just an issue with s3.

### Actual behavior
The url is called: `http://localhost:3000/rails/active_storage/direct_uploads`

`{"blob":{"filename":"oceans.mp4","content_type":"video/mp4","byte_size":23014356,"checksum":"ISUpgJFTKQWSIBMRnMPS6Q=="}}`

In the console I can see the error:

```
[Error] Failed to load resource: Preflight response is not successful (jKXHKnTUkyNcJdqF7g6Rbo2Q, line 0)
[Error] XMLHttpRequest cannot load https://******-production.s3.eu-west-2.amazonaws.com/jKXHKnTUkyNcJdqF7g6Rbo2Q?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=*******%2Feu-west-2%2Fs3%2Faws4_request&X-Amz-Date=20170926T113638Z&X-Amz-Expires=300&X-Amz-SignedHeaders=content-md5%3Bcontent-type%3Bhost&X-Amz-Signature=a4848afd1a13265d94c9e469d2ec5af54373d23034ea50ad5de92af79aaba29f. 
Preflight response is not successful
```

Finally I get an alert: Error storing "oceans.mp4". Status: 0

The submit button is disabled. Is this some sort of request signing issue? Hope you can help.

### System configuration
**Rails version**: master (revision: 1bb106c0b7b918606a7e94a6abb6ade364cc4270)

**Ruby version**: 2.3.1

**Comment by dwightwatson** [comment]
Could be an issue with the CORS configuration on your S3 bucket (it's an issue I ran into recently). I [wrote a blog post on it recently](https://www.neontsunami.com/posts/direct-image-uploads-to-s3-with-activestorage) but the gist of it is that you need to tell S3 to allow your client to upload directly into it.

```
<?xml version="1.0" encoding="UTF-8"?>
<CORSConfiguration xmlns="http://s3.amazonaws.com/doc/2006-03-01/">
    <CORSRule>
        <AllowedOrigin>*</AllowedOrigin>
        <AllowedMethod>GET</AllowedMethod>
        <MaxAgeSeconds>3000</MaxAgeSeconds>
        <AllowedHeader>Authorization</AllowedHeader>
    </CORSRule>
    <CORSRule>
        <AllowedOrigin>*</AllowedOrigin>
        <AllowedMethod>PUT</AllowedMethod>
        <AllowedHeader>*</AllowedHeader>
    </CORSRule>
</CORSConfiguration>
```

**Comment by hahmed** [comment]
@dwightwatson Much appreciated!

My original CORS config was:

```
<?xml version="1.0" encoding="UTF-8"?>
<CORSConfiguration xmlns="http://s3.amazonaws.com/doc/2006-03-01/">
<CORSRule>
    <AllowedOrigin>*</AllowedOrigin>
    <AllowedMethod>GET</AllowedMethod>
    <MaxAgeSeconds>3000</MaxAgeSeconds>
    <AllowedHeader>Authorization</AllowedHeader>
</CORSRule>
<CORSRule>
    <AllowedOrigin>*</AllowedOrigin>
    <AllowedMethod>PUT</AllowedMethod>
    <AllowedMethod>POST</AllowedMethod>
    <MaxAgeSeconds>3000</MaxAgeSeconds>
    <AllowedHeader> Authorization </AllowedHeader>
</CORSRule>
</CORSConfiguration>
```

I had to update the  `<AllowedHeader> Authorization </AllowedHeader>` to  `<AllowedHeader>*</AllowedHeader> ` to get this to work.
