### ISSUE TITLE
#save raises exception on strings containing NULL byte in postgres

### ISSUE THREAD

**Issue by knjko** [rails/rails#30730]
### Steps to reproduce

https://gist.github.com/knjko/35e1b2e40cde110ca5d292a4934f49bd

Given the following app:
	
```ruby
class Post < ActiveRecord::Base
  validates :body, presence: true
end
```

Saving post with assigning NULL byte:
	
```ruby
post = Post.new(body: "hello\x00world")
post.save
# => ArgumentError: string contains null byte
```

### Expected behavior

```ruby
# In SQLite,
puts post.body # => 'hello\u0000world'

# In MySQL,
puts post.body # => 'hello\u0000world'
```

Since the string are saved in other databases, should the string be escaped and saved in Postgres as well? 

### Actual behavior

```ruby
# In Postgres,
post = Post.new(body: "hello\x00world")
post.save
# => ArgumentError: string contains null byte
```

### System configuration

**Rails version**: 5.1.4
**Ruby version**: 2.4.1
**PostgreSQL**: 9.6.3

Thank you.

**Comment by kamipo** [comment]
This is a limitation in PostgreSQL, so it is expected behavior for PostgreSQL.

https://github.com/rails/rails/blob/35ecf460395341aaf0bc2a6a45fb030de6e6c5d9/activerecord/test/cases/adapter_test.rb#L16-L27

**Comment by knjko** [comment]
@kamipo Thanks for your reply! In PostgreSQL, I need to escape strings containing null bytes before assigning them?

**Comment by matthewd** [comment]
There's no escaping possible, unless you intend to actually store the escaped version of the string, and unescape it again when you read it.

If you're storing null bytes, you probably want a `bytea` column instead.

**Comment by knjko** [comment]
Thank you! 🙏
