### ISSUE TITLE
Has Many association not working as expect.

### ISSUE THREAD

**Issue by weichenghsu** [rails/rails#30747]
Not sure which gem cause this exception.
As you can see

slot.slot_details should have two children (slot_details)
However, it returns an empty array.
But I can get the two slot_details by traversing to slot.store then go back to the slot and show its children.

    [5] pry(#<RSpec::ExampleGroups::Slot>)> slot.slot_details
    => []
    [6] pry(#<RSpec::ExampleGroups::Slot>)> slot.store.slots[0].slot_details
    => [
        [0] #<SlotDetail:0x007fef2657f720> {
                         :id => 23,
                    :slot_id => 13,
              :minimum_seats => 1,
                   :discount => 1.5,
                    :deposit => 1.5,
             :deposit_policy => "MyString",
                 :created_at => Fri, 29 Sep 2017 01:22:27 UTC +00:00,
                 :updated_at => Fri, 29 Sep 2017 01:22:27 UTC +00:00,
                  :book_type => "splittable",
                  :available => false,
            :remaining_seats => 5,
            :available_seats => 5
        },
        [1] #<SlotDetail:0x007fef2657f130> {
                         :id => 24,
                    :slot_id => 13,
              :minimum_seats => 1,
                   :discount => 1.5,
                    :deposit => 1.5,
             :deposit_policy => "MyString",
                 :created_at => Fri, 29 Sep 2017 01:22:27 UTC +00:00,
                 :updated_at => Fri, 29 Sep 2017 01:22:27 UTC +00:00,
                  :book_type => "splittable",
                  :available => false,
            :remaining_seats => 10,
            :available_seats => 10
        }
    ]

        source 'https://rubygems.org'

        git_source(:github) do |repo_name|
          repo_name = "#{repo_name}/#{repo_name}" unless repo_name.include?("/")
          "https://github.com/#{repo_name}.git"
        end

        # Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
        gem 'rails', '5.1.3'
        # Use mysql as the database for Active Record
        gem 'mysql2', '>= 0.3.18', '< 0.5'
        # Use Puma as the app server
        gem 'puma', '~> 3.0'
        # Use SCSS for stylesheets
        gem 'sass-rails', '~> 5.0'
        # Use Uglifier as compressor for JavaScript assets
        gem 'uglifier', '>= 1.3.0'
        # Use CoffeeScript for .coffee assets and views
        # gem 'coffee-rails', '~> 4.2'
        # See https://github.com/rails/execjs#readme for more supported runtimes
        # gem 'therubyracer', platforms: :ruby

        # Use jquery as the JavaScript library
        # gem 'jquery-rails'
        # Turbolinks makes navigating your web application faster. Read more: https://github.com/turbolinks/turbolinks
        # gem 'turbolinks', '~> 5'
        # Build JSON APIs with ease. Read more: https://github.com/rails/jbuilder
        gem 'jbuilder', '~> 2.5'
        # Use Redis adapter to run Action Cable in production
        # gem 'redis', '~> 3.0'
        # Use ActiveModel has_secure_password
        # gem 'bcrypt', '~> 3.1.7'

        # Use Capistrano for deployment
        # gem 'capistrano-rails', group: :development

        group :development, :test do
          # Call 'byebug' anywhere in the code to stop execution and get a debugger console
          gem 'byebug', platform: :mri
        end

        group :development do
          # Access an IRB console on exception pages or by using <%= console %> anywhere in the code.
          gem 'web-console', '>= 3.3.0'
          gem 'listen', '~> 3.0.5'
          # Spring speeds up development by keeping your application running in the background. Read more: https://github.com/rails/spring
          gem 'spring'
          gem 'spring-watcher-listen', '~> 2.0.0'
        end

        # Windows does not include zoneinfo files, so bundle the tzinfo-data gem
        gem 'tzinfo-data', platforms: [:mingw, :mswin, :x64_mingw, :jruby]

        group :test do
          gem "guard"
          gem "guard-rspec"
          gem 'database_cleaner'
          gem 'email_spec'
          gem 'shoulda', '3.5.0'
          gem 'shoulda-matchers', '2.8.0'
        end

        group :development, :test do
        gem 'rspec-rails'
          gem 'spring-commands-rspec'
          gem 'spring'
          gem 'rspec-deep-ignore-order-matcher'
          gem "capistrano",  "~> 3.6.0", require: false
          gem "capistrano-rails", "~> 1.1", require: false
          gem "capistrano-rbenv", "~> 2.0.4", require: false # production server use rbenv
          gem 'capistrano-puma',  require: false
          gem 'capistrano-file-permissions'
          gem 'god'
          gem "rspec-expectations"
          gem 'cancancan'
          # RSPEC
          gem 'launchy'

        end

        gem "rails-erd"
        gem 'factory_girl_rails'
        gem 'factory_girl'
        gem 'recursive-open-struct'
        gem 'faker'
        gem 'annotate' # show DB attrs
        gem 'pry-awesome_print'
        gem 'zeus'
        gem "awesome_print", require: "ap"

**Comment by al2o3cr** [comment]
@weichenghsu You'll get much better help for this question if you post the code that declares associations like `slot_details`.

Also note that this issue tracker is for reporting bugs in the library itself; questions about *using* the library should be directed to either the [mailing list](https://groups.google.com/forum/#!forum/rubyonrails-talk) or [StackOverflow](http://stackoverflow.com/questions/tagged/ruby-on-rails)
