### ISSUE TITLE
ActionCable does not work inside Vue.js webpack app

### ISSUE THREAD

**Issue by nengine** [rails/rails#30753]
### Steps to reproduce
I am running Vue.js with webpack inside Rails 5.1.3 app.  Subscribing from a javascript in regular Rails app is working fine.  I can see new messages as they arrive.  However, since I'm using Vue.js inside Rails, when I try to subscribe ActionCable from Vue.js component it is not working.  

trades.vue
```js
<template>
  <div id="trades">
    <p>{{ message }}</p>
    <button @click='subscribe'>Subscribe cable</button>    
  </div>
</template>

<script>
  const ActionCable = require('actioncable'); 
  var cable = ActionCable.createConsumer('ws://localhost:3000/cable');

  export default {
    data: function() {
      return {
        message: 'Hello from trades Vue'
      }
    },
    methods: {
      subscribe: function() {
        cable.subscriptions.create('DepositsChannel', {
          connected: function() {
            console.log('connected to rails actioncable Yay!')    
          } ,
          received: function(data) {
            console.log(data);
          }          
        });        
      }
    }
  }
</script>
```

deposits.rb
```rb
class DepositsChannel < ApplicationCable::Channel
  def subscribed
    stream_from "deposits"
  end
end
```

This file is under app\assets\javascripts\deposits.js and is working fine! Above code inside cable.vue is not working.

```js
App.deposits = App.cable.subscriptions.create('DepositsChannel', {
  connected: function() {
    console.log('connection to actiontion cable Aha!');
  },
  received: function(data) {    
    return $('#deposits').append(this.renderDeposits(data));
  },

  renderDeposits: function(data) {
    return "<p> <b>" + data.amount + ": </b>" + data.currency + "</p>";
  }
});
```

(Guidelines for creating a bug report are [available
here](http://guides.rubyonrails.org/contributing_to_ruby_on_rails.html#creating-a-bug-report))

### Expected behavior
I should see data printed to the console when a subscription message is received.

### Actual behavior
No output o the console when a subscription message is received.

### System configuration
**Rails version**: 5.1.3

**Ruby version**: 2.4.1

**Comment by dimroc** [comment]
I was able to successfully get ActionCable working inside a vue single file component with the following setup:

Rails version: 5.1.4
Ruby Version: 2.4.1
Webpacker Version: edge
Vue Version: 2.5.2

I took a minimalist approach and left all the default ActionCable js bootstrapping code as is in `app/assets/javascripts/cable.js`, added it to `application.js` with the usual sprockets require, included application.js in my layout and just referenced the global `App.cable` in my .vue file.

```vue
<script>
App.cable.subscriptions.create(
  { channel: "MyChannel", room: "myroom" },
  { received: function() { console.log(arguments); } });

export default {
  data: function () {
    return {
      message: "Hello Vue!"
    }
  }
}
</script>
```

Got a console statement with

```ruby
ActionCable.server.broadcast("myroom")
```

**Comment by kennyx46** [comment]
@nengine I have emulated your situation and everything works fine, both from assets folder and single file vue component. Please check if you have any errors in your javascript or terminal consoles.

**Comment by kennyx46** [comment]
I suppose we can close this one
