### ISSUE TITLE
Actioncable doesn't support faye-websockets in rails 5.1 any more?

### ISSUE THREAD

**Issue by Llermy** [rails/rails#30775]
Hi !

I just saw that apparently actioncable in rails 5.1 doesn't have any more the option to be used with gem `faye-websocket`, which is needed for actioncable to work with some web servers like `thin`.

In rails 5.0, as it is documented [here](http://www.rubydoc.info/gems/actioncable/5.0.1/ActionCable/Server/Configuration), you had the option to configure the actioncable server to use faye like:

`Rails.application.config.action_cable.use_faye = true`

But in rails 5.1, you would receive the following exception:

```
/usr/local/rvm/gems/ruby-2.2.7/gems/actioncable-5.1.0/lib/action_cable/engine.rb:37:in 'block (3 levels) in <class:Engine>': undefined method 'use_faye=' for #<ActionCable::Server::Configuration:0x00000007326048> (NoMethodError)
	from /usr/local/rvm/gems/ruby-2.2.7/gems/actioncable-5.1.0/lib/action_cable/engine.rb:37:in 'each'
	from /usr/local/rvm/gems/ruby-2.2.7/gems/actioncable-5.1.0/lib/action_cable/engine.rb:37:in 'block (2 levels) in <class:Engine>'
	from /usr/local/rvm/gems/ruby-2.2.7/gems/activesupport-5.1.0/lib/active_support/lazy_load_hooks.rb:45:in 'instance_eval'
	from /usr/local/rvm/gems/ruby-2.2.7/gems/activesupport-5.1.0/lib/active_support/lazy_load_hooks.rb:45:in 'execute_hook'
	from /usr/local/rvm/gems/ruby-2.2.7/gems/activesupport-5.1.0/lib/active_support/lazy_load_hooks.rb:52:in 'block in run_load_hooks'
	from /usr/local/rvm/gems/ruby-2.2.7/gems/activesupport-5.1.0/lib/active_support/lazy_load_hooks.rb:51:in 'each'
	from /usr/local/rvm/gems/ruby-2.2.7/gems/activesupport-5.1.0/lib/active_support/lazy_load_hooks.rb:51:in 'run_load_hooks'
	from /usr/local/rvm/gems/ruby-2.2.7/gems/actioncable-5.1.0/lib/action_cable/server/base.rb:85:in '<module:Server>'
	from /usr/local/rvm/gems/ruby-2.2.7/gems/actioncable-5.1.0/lib/action_cable/server/base.rb:4:in '<module:ActionCable>'
	from /usr/local/rvm/gems/ruby-2.2.7/gems/actioncable-5.1.0/lib/action_cable/server/base.rb:3:in '<top (required)>'
	from /usr/local/rvm/gems/ruby-2.2.7/gems/actioncable-5.1.0/lib/action_cable.rb:44:in 'server'
```

And in the [documentation for actioncable in rails 5.1](http://www.rubydoc.info/gems/actioncable/5.1.0/ActionCable/Server/Configuration), the property `use_faye` seems indeed to be removed. Without this property, actioncable won't work with some web servers that need faye to work with it (at least `thin`). Is there a new way to configure actioncable 5.1 with faye or support was totally removed?

This is related to issue [#23696](https://github.com/rails/rails/issues/23696).

**Ruby version**: 2.2.7

**Comment by y-yagi** [comment]
Faye mode of Action Cable has been removed with #26676. 
Incidentally, http://www.rubydoc.info/gems/actioncable is not an official document. The official document is http://api.rubyonrails.org/.

**Comment by y-yagi** [comment]
As mentioned above, faye mode has already been removed. Since faye mode was not described in the official docc, it was removed without deprecation. Please remove `use_faye` specification. Thanks!
