### ISSUE TITLE
Building through a scope with a where(id: foo) clause where foo.length == 1 results in primary key exceptions

### ISSUE THREAD

**Issue by zhubert** [rails/rails#30776]
### Steps to reproduce

I would expect a call to `build` to always result in a record that can be saved, but if you are calling through a scope that used `id` to build the association, it will fail if comment_ids.length == 1:

```
new_comment = post.comments.where(id: comment_ids).build
```

It tries to create a new record with the same id and throw an ActiveRecord::RecordNotUnique exception.

It will correctly provide a `nil` id if `comment_ids.length >1`

### Expected behavior

`build` always results in a nil id on the new object

### Actual behavior
The id is set to whatever was provided in the scope.

### System configuration
**Rails version**: Edge: https://gist.github.com/zhubert/f698995f74cfa27d306ca977e0e4fc61

**Ruby version**: Ruby 2.3.3p222

**Comment by kamipo** [comment]
This is an expected behavior of `Relation#build`.
http://api.rubyonrails.org/v5.1/classes/ActiveRecord/Relation.html#method-i-new
