### ISSUE TITLE
ajax:before events not stopping remote links with method: option

### ISSUE THREAD

**Issue by guaguasi** [rails/rails#30790]
### Steps to reproduce
Use `jquery-rails` gem. Require `jquery3` in `application.js` manifest. No `turbolinks`

```
<%= link_to 'Edit', edit_item_path(item), data: { confirm: 'Are you sure?' }, remote: true %>
<%= link_to 'Destroy', item, method: :delete, data: { confirm: 'Are you sure?' }, remote: true %>

<script type="text/javascript">
$(document).ready(function() {
  $('a').on('ajax:before', function(e) {
    return false;
  }).on('ajax:success', function(e) {
    console.log('success');
  }).on('ajax:complete', function(e) {
    console.log('complete');
  });
});
</script>
```

### Expected behavior
Clicking either link should do nothing other than ask to confirm.

### Actual behavior
Clicking link with `method: :delete` asks to confirm then follows through with the request successfully. Does not fire `ajax:complete` or `ajax:success`.

If `ajax:before` does not `return false`, `ajax:success` and `ajax:complete` are fired.

### System configuration
**Rails version**: Rails 5.1.4

**Ruby version**: ruby 2.4.1p111 (2017-03-22 revision 58053) [x86_64-linux]

**Comment by sevab** [comment]
Having similar issue with rails-ujs.

When `method: option` is passed to a remote link, cancelling the request with `e.preventDefault();`  within `ajax:beforeSend` still makes the request.

Cancelling the request with `e.preventDefault();`  within `ajax:before` works.

Cancelling within `ajax:beforeSend` when `method: option` isn't specified works.
