### ISSUE TITLE
Cannot unscope 'where' values that appear in quotes

### ISSUE THREAD

**Issue by brchristian** [rails/rails#30793]
Many publishing platforms use a `where` clause to filter articles by their publication date (i.e., to hide articles with a publication date in the future).

However, the `where` syntax does not offer a clean way to express gt/lt relations, leading to code like this, in which the `where` clause is expressed as a string rather than a hash:

```ruby
scope :published, -> { where('publish_date <= ?', Time.current) }
```

This causes problems with `unscope`, however, because neither of the following will work correctly:

```ruby
Article.published.unscope(where: :publish_date)
Article.published.unscope(where: 'publish_date')
```

These will _not_ remove the restriction on the `publish_date`!

The only way I can think of to create a version of the `published` scope that can be cleanly usncoped would be the following:

```ruby
scope :published, -> { where.not(publish_date: Time.current..DateTime::Infinity.new) }
```

This works! This can be cleanly unscoped! However this seems extremely awkward and un-Rails-like.

(Note that date ranges with negative infinity appear not to work, hence the even more awkward `not` part of the clause.)

Perhaps there is a more elegant solution here, but this seems like a relatively common use-case. Would it be helpful to build in support for unscoping attributes that appear in the string part of `where` clauses?

If this seems useful, I can look into making a PR for this.

If there’s another easier solution entirely, however, I am all ears!

**Comment by kamipo** [comment]
A string condition doesn't support unscoping.
Please use `where(arel_attribute(:publish_date).lteq(Time.current))` instead if you want it.

**Comment by brchristian** [comment]
@kamipo Cheers, I didn’t know that the `.lteq` syntax was an option. Agreed that’s the right way to go. Thanks! :+1:
