### ISSUE TITLE
Rails DateTime silent data modification

### ISSUE THREAD

**Issue by benmmurphy** [rails/rails#30805]
### Steps to reproduce

https://gist.github.com/benmmurphy/e3d6ef6f4545683132ae2eb23c3840cb

1. Load a datetime_select helper for a datetime that falls on an ambiguous local time when rails has a time zone configured. For example: 2017/10/29 1:00 UTC in the Europe/London timezone is '2017/10/29 1:00'. However, '2017/10/29 1:00' in the Europe/London timezone happens at two different times in UTC:

    2017/10/29 1:00 UTC
    2017/10/29 0:00 UTC

2. Submit the form updating the time. Rails will convert localtime to UTC before writing to the database. But the time is ambiguous and Rails resolves this by choosing the first time. The time is now changed even though the user did not modify it on the form.

### Expected behavior

If you only have a single timezone configured for your application then this is not such a big problem because existing data won't be silently changed. Though, there is still the problem of allowing the user to specify the actual time they want but this is a problem that a lot applications that show a time in local time struggle with. But if you have multiple users sharing the a rails application with different time zones then it is possible for users to inadvertently corrupt the times other users have created even though they are not editing that field if they are in different time zones. There is also documentation in rails about how you might set up different time zones for different users so presumably this is a supported use case:

https://github.com/rails/rails/blob/f1e89628fe3d18427e3b6644b1e7f3ef965ecd5b/activesupport/lib/active_support/core_ext/time/zones.rb#L27

I think there needs to be consideration to throwing an exception in these cases when there is an ambiguity rather than have the risk of data being silently changed or at least give users the option of throwing the exception and keeping the current behaviour as the default.

### Actual behavior

The date was silently changed.

### System configuration
**Rails version**: 5.1.4

**Ruby version**: 2.4.0

**Comment by pixeltrix** [comment]
This is something that needs to be handled via application-level validation since the handling of such errors would vary. This is an example of how to validate such an attribute:

``` ruby
class Post < ApplicationRecord

  validate do
    tz = published_at.time_zone
    time = published_at.time
    periods = tz.periods_for_local(time)
  
    if periods.size > 1
      errors.add(:published_at, :ambiguous_time)
    end
  end

end
```

Obviously, if you have user-level timezones that information would need to be passed into the validation process in some way.
