### ISSUE TITLE
Upload from URL with ActiveStorage

### ISSUE THREAD

**Issue by MatthiasRMS** [rails/rails#30819]
Is it possible yet to do an upload from a remote URL with ActiveStorage ? 
Solutions like [CarrierWave](https://github.com/carrierwaveuploader/carrierwave/wiki/How-to:-Upload-remote-image-urls-to-your-seedfile) offer this possibility, which is extremely useful in many cases. 

Happy to provide a PR to do this

**Comment by georgeclaghorn** [comment]
Sorry, Active Storage doesn’t support that.

Please note that this issue tracker is reserved for bug reports.

**Comment by MatthiasRMS** [comment]
Ok, where should I discuss this to know if it's worth it to work on a PR ?

**Comment by Morganjackson** [comment]
@MatthiasRMS did you end up figuring this out?

**Comment by MatthiasRMS** [comment]
@Morganjackson yup, but they chose to close it:
https://github.com/rails/rails/pull/30834

**Comment by williamromero** [comment]
Someone knows if Active Storage will keep this opinion about doesn't support URL uploads?
