### ISSUE TITLE
URLs containing certain character codes break routing (reprise)

### ISSUE THREAD

**Issue by jcoyne** [rails/rails#30811]
This was originally raised in #4450 and I see that some code was created to address this:

https://github.com/econsultancy/rails/commit/7c385d085f131346e617b8bbdecf05d006429576
(I'm not seeing this code in the rails master branch though)

When this url is called:
https://example.com/assets/%F8%80%80%80%AE%F8%80%80%80%AE/%F8%80%80%80%AE%F8%80%80%80%AE/%F8%80%80%80%AE%F8%80%80%80%AE/%F8%80%80%80%AE%F8%80%80%80%AE/%F8%80%80%80%AE%F8%80%80%80%AE/%F8%80%80%80%AE%F8%80%80%80%AE/%F8%80%80%80%AE%F8%80%80%80%AE/%F8%80%80%80%AE%F8%80%80%80%AE/%F8%80%80%80%AE%F8%80%80%80%AE/%F8%80%80%80%AE%F8%80%80%80%AE/%F8%80%80%80%AE%F8%80%80%80%AE/%F8%80%80%80%AE%F8%80%80%80%AE/etc/passwd
```
ArgumentError: invalid byte sequence in UTF-8

    [GEM_ROOT]/gems/sprockets-3.7.1/lib/sprockets/server.rb:289 :in `[]`
    [GEM_ROOT]/gems/sprockets-3.7.1/lib/sprockets/server.rb:289 :in `path_fingerprint`
    [GEM_ROOT]/gems/sprockets-3.7.1/lib/sprockets/server.rb:36 :in `call`
    [GEM_ROOT]/gems/actionpack-5.1.4/lib/action_dispatch/routing/mapper.rb:17 :in `block in <class:Constraints>`
    [GEM_ROOT]/gems/actionpack-5.1.4/lib/action_dispatch/routing/mapper.rb:46 :in `serve`
    [GEM_ROOT]/gems/actionpack-5.1.4/lib/action_dispatch/journey/router.rb:50 :in `block in serve`

    [GEM_ROOT]/gems/actionpack-5.1.4/lib/action_dispatch/journey/router.rb:33 :in `each`
    [GEM_ROOT]/gems/actionpack-5.1.4/lib/action_dispatch/journey/router.rb:33 :in `serve`
    [GEM_ROOT]/gems/actionpack-5.1.4/lib/action_dispatch/routing/route_set.rb:834 :in `call`
    [GEM_ROOT]/gems/rack-2.0.3/lib/rack/etag.rb:25 :in `call` 
```

**Comment by pixeltrix** [comment]
@jcoyne looks like this is a Sprockets issue?

**Comment by jcoyne** [comment]
@pixeltrix I wasn't sure if it was ActionDispatch passing bad parameters to Sprockets, or if it was Sprockets handling the parameters incorrectly.

**Comment by pixeltrix** [comment]
@jcoyne Action Dispatch hasn't don't anything with the path - in fact the path method is defined in `Rack::Request` and just concatenates the `script_name` and `path_info` headers. The problem is when Sprockets tries to extract the fingerprint from the path using a regex that it blows up.

**Comment by jcoyne** [comment]
Moved to rails/sprockets#513 Thanks @pixeltrix 👍
