### ISSUE TITLE
undefined method `find_in_source_paths`

### ISSUE THREAD

**Issue by mukarramali** [rails/rails#30820]
https://github.com/rails/rails/blob/5473e390d362755125d2f47b64ef0a135f2fe111/railties/lib/rails/generators/migration.rb#L55

Can anybody help me locate this method?
It throws `NoMethodError` on using `migration_template` method

**Comment by veekram** [comment]
@mukarramali Yeah same problem here. Are you able to figure out the problem?

**Comment by mukarramali** [comment]
@veekram  problem wasn't with the rails. So, I used another approach, I don't remember the purpose though. You can elaborate your problem here or ask on stackoverflow, I can try.

**Comment by veekram** [comment]
@mukarramali Thanks. I was setting up wrong path while generating rails generator. I had a workout for that . Thanks again :)
