### ISSUE TITLE
[Possible Feature Discussion] (Optional) Predicate Methods For AR Scopes

### ISSUE THREAD

**Issue by mvastola** [rails/rails#30830]
So I haven't really contributed code to `rails` before, and it's entirely possible this has been rejected previously (though I did perform an obligatory search), but if I, for instance, had:
```ruby
class User < ApplicationRecord
  scope :blocked, ->() { when(blocked: true) }
  scope :not_blocked, ->() { when(blocked: false) }
end
```
It would be super helpful if instance methods named `#blocked?` and `#not_blocked?` were (optionally?) automagically created for all my records to test if they actually matched the scopes I defined. 

Is there any particular reason why this feature *can't* exist (or would otherwise be difficult to adopt into `rails`?)

As an example of how simply this feature could be implemented, I am currently using the following code in one project (to `prepend` `ApplicationRecord`):
```ruby
    def scope(name, *args, &block)
      super(name, *args, &block).tap do
        define_scope_tester(name)
      end
    end

    def define_scope_tester(*names)
      names.each do |name|
        next if dangerous_attribute_method?("#{name}?")
        next unless singleton_methods.include?(name)
        define_method "#{name}?" do |*args|
          return nil unless persisted?
          self.class.unscoped.where(:id => id).send(name, *args).one?
        end
      end
    end
    alias_method :define_scope_testers, :define_scope_tester
```

**Comment by sgrif** [comment]
We don't accept feature requests on the issue tracker. If you'd like to work on this feature, you should submit a PR. If you'd like feedback on whether a feature might be implemented before working on it, or just want to request a feature and have no interest in working on it, you should open a thread on the Rails core mailing list.
