### ISSUE TITLE
Wrong typecast when plucking boolean value from joined table in MySQL2

### ISSUE THREAD

**Issue by DerTraveler** [rails/rails#30848]
### Steps to reproduce

https://gist.github.com/DerTraveler/05703597ee825dcbca64735c8976114b

### Expected behavior
When plucking a boolean value from a joined table it should be returned as a list of booleans.

This is the behaviour pluck shows on an unjoined table. Also when reproducing the steps with another adapter (like postgresql), the values are properly returned as booleans.

### Actual behavior
It is returned as a list of integers

### System configuration
**Rails version**: master, so I guess > 5.1.4 - but was initially found on 4.2.7.1

**Ruby version**: 2.4.2

**Comment by ChrisBr** [comment]
I can confirm that for sqlite3 as well (```['t', 'f'] instead of [true, false]```)

The problem seems to be in 
https://github.com/rails/rails/blob/master/activerecord/lib/active_record/relation/calculations.rb#L191
There we only pass the attribute_type of the klass to cast_values:
```
result.cast_values(klass.attribute_types)
```
We would need to pass also the attribute_types of the associated objects. Something like:

```
attribute_types = klass.attribute_types
klass.reflections.each do |_key, reflection|
  attribute_types = reflection.klass.attribute_types.merge(attribute_types)
end
result.cast_values(attribute_types)
```
However, this would be a problem when columns of associated tables have similar name. 
@rafaelfranca could you please provide some feedback if this is the way to go?

**Comment by spejamchr** [comment]
I wrote a test to show this error. I put it in `activerecord/test/cases/relations_test.rb`, though I'm not sure if that's the best place for it:

```ruby
def test_pluck_joined_boolean_type_cast
  Reader.create! post_id: 1, person_id: 1, skimmer: true
  Reader.create! post_id: 1, person_id: 1, skimmer: false
  assert_equal Reader.pluck(:skimmer), Post.joins(:readers).pluck('readers.skimmer')
end
```

For mysql2 I get:

```
Failure:
RelationTest#test_pluck_joined_boolean_type_cast [/vagrant/rails/activerecord/test/cases/relations_test.rb:590]:
Expected: [1, 0]
  Actual: [true, false]
```

And for sqlite3:

```
Failure:
RelationTest#test_pluck_joined_boolean_type_cast [/vagrant/rails/activerecord/test/cases/relations_test.rb:590]:
Expected: ["t", "f"]
  Actual: [true, false]
```

**Comment by nmichels** [comment]
@ChrisBr I've noticed also that database_statements.rb creates a new instance of ActiveRecord::Result in different ways for mysql adapter and postgresql adapter:
https://github.com/rails/rails/blob/master/activerecord/lib/active_record/connection_adapters/mysql/database_statements.rb#L34
https://github.com/rails/rails/blob/master/activerecord/lib/active_record/connection_adapters/postgresql/database_statements.rb#L89

**Comment by nmichels** [comment]
@spejamchr I've added a similar test to activerecord/test/cases/calculations_test.rb, it looks like there are some tests related to the current issue:
https://github.com/rails/rails/blob/master/activerecord/test/cases/calculations_test.rb#L631

**Comment by nmichels** [comment]
@ChrisBR @spejamchr is it really necessary a fix since the syntax pluck('table.column') solves both the casting and ambiguity issue?
