### ISSUE TITLE
Use lazy "url_for" into "link_to"

### ISSUE THREAD

**Issue by kambata940** [rails/rails#30849]
Hello,
I notice that [here](https://github.com/rails/rails/blob/master/actionview/lib/action_view/helpers/url_helper.rb#L197) in `link_to` we always construct the URL not taking into account if it's gonna be used or not.

The current implementation is:
```ruby
.
.
html_options = convert_options_to_data_attributes(options, html_options)

url = url_for(options)
html_options["href".freeze] ||= url

content_tag("a".freeze, name || url, html_options, &block)
```
I propose as performance optimization to call `url_for` only when it's needed.

```ruby
.
.
html_options = convert_options_to_data_attributes(options, html_options)

html_options["href".freeze] ||= (url = url_for(options))

content_tag("a".freeze, name || url, html_options, &block)
```
NOTE: if you think that it makes sense we can change the behavior and use `html_options["href".freeze]`  for a default for the name. But this maybe is a separate issue...

```ruby
.
.
html_options = convert_options_to_data_attributes(options, html_options)

url = html_options["href".freeze] || url 
html_options["href".freeze] = url

content_tag("a".freeze, name || url, html_options, &block)
```

**Comment by rafaelfranca** [comment]
Unless we are sure this performance optimisation will be massive I prefer to keep the code as it is since it is easier to understand. I'm closing this since it is not an issue but feel free to investigate the performance difference to open a pull request.

Thank you so much for the issue.
