### ISSUE TITLE
ActionCable → upgrade to Redis 4

### ISSUE THREAD

**Issue by smenor** [rails/rails#30840]
### Steps to reproduce
bundle up without a constraint on the Redis version

(Guidelines for creating a bug report are [available
here](http://guides.rubyonrails.org/contributing_to_ruby_on_rails.html#creating-a-bug-report))

### Expected behavior
Tell us what should happen
Action Cable works

### Actual behavior
Tell us what happens instead
ActionCable fails and reports that the Redis gem is missing

### System configuration
**Rails version**:
5.1.4

**Ruby version**:
ruby 2.4.1p111 (2017-03-22 revision 58053) [x86_64-darwin17]
ruby 2.3.1p112 (2016-04-26 revision 54768) [x86_64-linux]

**Comment by kamipo** [comment]
This has been fixed in #30757 and #30748.

**Comment by dfang** [comment]
@kamipo
so how can i apply this patch to my rails 5.1.1 application. since rails 5.2.0 is not released yet

thanks !
