### ISSUE TITLE
Remove utf8=✓ input or set enforce_utf8 to false by default

### ISSUE THREAD

**Issue by kshnurov** [rails/rails#30852]
`<input name="utf8" type="hidden" value="✓" />` was introduced as a workaround for IE <= 8.
As of today IE5-8 has a 0.3% share worldwide and nothing really works in it.
Shouldn't we get rid of this input or at least set `enforce_utf8` to false by default?

**Comment by rafaelfranca** [comment]
We already considered this a lot and we don't see any advantage of removing this code since it is really small and it doesn't affect any user. Maybe for 6.0

**Comment by kshnurov** [comment]
@rafaelfranca the code is small but the effect is huge. Useless bytes in __each__ rails form lead to GBs of traffic. Also it's a bit annoying to see it in logs & params :)

**Comment by Fudoshiki** [comment]
**Rails-ujs** and **Turbolinks** support only IE10/11, `<input name="utf8" type="hidden" value="✓" />` is artifact

**Comment by kamipo** [comment]
Closing in favor of #32125.
