### ISSUE TITLE
ActiveRecord serialize with Marshal as coded does not work

### ISSUE THREAD

**Issue by kreintjes** [rails/rails#30856]
I cannot use the Marshal class directly for the [ActiveRecord serialize feature](http://api.rubyonrails.org/classes/ActiveRecord/AttributeMethods/Serialization/ClassMethods.html#method-i-serialize). When I do this and try to save the object, I get an error.

### Steps to reproduce
Create an ActiveRecord model with a binary column which is serialized through Marshal, i.e.: `bin/rails g model MyModel data:binary`

app/models/my_model.rb:
```
class MyModel < ApplicationRecord
   serialize :data, Marshall
end
```

And try to instantiate and save the model: `MyModel.create!`. Problem also occurs when filling data with something (e.g. a Hash with some key values).

### Expected behavior
I expect the instance to be stored in the database, where the given data is serialized using Marshal.dump.

### Actual behavior
I get an error: "TypeError: instance of IO needed"

### System configuration
**Rails version**: 5.0.4

**Ruby version**: 2.4.1

### Cause and potential solution
The error is caused by the calling Marshal.load(nil) in [ActiveRecord::Type::Serialized#default_value?](https://github.com/rails/rails/blob/99820fbeb29ae35a7771f3991bd119b102861aa7/activerecord/lib/active_record/type/serialized.rb#L53), which is called from the deserialize method in the same file.

It can be fixed by by creating a coder class in the spirit of [ActiveRecord::Coders::YAMLColumn](https://github.com/rails/rails/blob/99820fbeb29ae35a7771f3991bd119b102861aa7/activerecord/lib/active_record/coders/yaml_column.rb) where Marshal.load(data) is only performed if data not nil: `obj = Marshal.load(marshal) unless marshal.nil?`. The coder class should then be used in the ActiveRecord model: `serialize :data, MarshallCoder.new(:data)`. However I do not know if this is the way to go.

Should serialize always be used with a special coder object, or should it also be possible to use Serialization classes like YAML and Marshall directly? The documentation is a bit vague on that. In case of the first, then it probably would be nice to add a MarshallColumn coder class to active_record/coders as well. In case of the latter, the serialized type should be fix to not call `coder.load(nil)`, but not sure how (maybe rescue from exception in which case `default_value?` always returns false?).

**Comment by eileencodes** [comment]
Hey @kreintjes can you provide an executable script that demonstrates the issue? You can use this template https://github.com/rails/rails/blob/master/guides/bug_report_templates/active_record_master.rb for active record bugs. Thanks!

**Comment by sgrif** [comment]
`Marshal` is not intended to be used as an argument to `serialize`, as its output is not guaranteed to be stable across Ruby versions. You can work around this by creating your own coder class (as you mentioned) or using the [attributes API](http://api.rubyonrails.org/classes/ActiveRecord/Attributes/ClassMethods.html#method-i-attribute) instead

**Comment by kreintjes** [comment]
Clear. Thanks for the explanation!
