### ISSUE TITLE
Join Queries Defined in Scopes Disappear when Eager Loading

### ISSUE THREAD

**Issue by DarkArc** [rails/rails#30858]
### Brief Explanation

This is a bug with the includes/eager loading system where join queries defined in scopes disappear causing invalid SQL to be generated.

#### Model Setup/Example
ThingWhichHasEvents
```
    has_many :event_record_links, as: :related_record, inverse_of: :related_record, dependent: :destroy

    has_many :user_events, -> { user_defined }, through: :event_record_links, source: :event
```

EventRecordLink
```
    belongs_to :event, touch: true, inverse_of: :event_record_links
    belongs_to :related_record, polymorphic: true
```

Event
```
    scope :user_defined, -> { joins(:event_type).where('event_types.user_defined = ?', true) }
```

### Steps to reproduce

Eager load records of `ThingWhichHasEvents` ex:

```
ThingWhichHasEvents.includes(:user_events).find_each do |thing|
  puts thing.user_events.inspect
end
```
The same result is observed when using `preload` in place of `includes`.

### Expected behavior
The `user_events` should be loaded.

### Actual behavior
The request fails:
```
ActiveRecord::StatementInvalid: PG::UndefinedTable: ERROR:  missing FROM-clause entry for table "event_types"

SELECT "event_record_links"."related_record_type" ... FROM "event_record_links" LEFT OUTER JOIN "events" ON "events"."id" = "event_record_links"."event_id" WHERE (event_types.user_defined = 't') AND "event_record_links"."related_record_type" = $1 AND "event_record_links"."related_record_id" IN ('bd2edfcd-a7d1-44a0-be50-097c1055a0d9',...)
```
For some reason, the join needed for the `user_events` scope in `Event` was removed.

### System configuration
**Rails version**: `5.0.2`

**Ruby version**: `ruby 2.3.3p222 (2016-11-21) [x86_64-linux-gnu]`

**Database**:  Postgres 9.5

**Comment by kamipo** [comment]
Fixed in #29413.
