### ISSUE TITLE
Failing adding a column during migration

### ISSUE THREAD

**Issue by sofianeOuafir** [rails/rails#30866]
### Steps to reproduce

Try to add a column with the key work 'id' at the end like 'original_user_id' to a model call User. This column is not a reference but an integer.

### Expected behavior

It should add the original_user_id column to the user table

### Actual behavior

It does not add the column but the migration is executed with success

### System configuration
**Rails version**: 5.0.2

**Ruby version**: 2.3.4

**Comment by meinac** [comment]
I tried with the version you mentioned  as well as master of upstream with PostgreSQL and SQLite but could not reproduce it. Can you provide a test application which we can reproduce the issue with?
