### ISSUE TITLE
ActiveRecord::QueryMethods#reverse_order is doing a strange thing where several order clauses exist

### ISSUE THREAD

**Issue by bankair** [rails/rails#30869]
### Steps to reproduce

Assuming that I have a model User with 3 attributes (first_name, last_name and email), when I get a peek at the SQL generated by the following statement:

```ruby
puts(
  User
    .order(first_name: :asc)
    .order(last_name: :desc)
    .order(email: :desc)
    .reverse_order
    .to_sql
)
```

I get something rather weird (repetition of attributes of order clause).

### Expected behavior

```SQL
SELECT "users".*
FROM "users" 
ORDER BY "users"."first_name" DESC, "users"."last_name" ASC, "users"."email" ASC
```

### Actual behavior

```SQL
SELECT "users".*
FROM "users" 
ORDER BY
  "users"."first_name" DESC, "users"."last_name" ASC, "users"."email" ASC,
  "users"."first_name" DESC, "users"."last_name" ASC, "users"."email" ASC,
  "users"."first_name" DESC, "users"."last_name" ASC, "users"."email" ASC
```

Funny part is: If I have 2 order clauses on my relation, I get 2 repetitions. 3 orders => 3 repetitions. Not tested with 4, but I'm ready to bet my fur that it will give 4 repetitions ;)

This have no impact on performance of execution with a postgresql database, but it seems odd anyway.

Is this an expected behavior ?

### System configuration
**Rails version**: 4.2.8

**Ruby version**: 2.4.1

**Comment by tcopeland** [comment]
FWIW, all seems well with this on 5.1.4:

```ruby
>> User.order(first_name: :desc).order(last_name: :asc).order(email: :asc).order(id: :desc).reverse_order
  User Load (0.5ms)  SELECT  "users".* FROM "users" ORDER BY "users"."first_name" ASC, "users"."last_name" DESC, "users"."email" DESC, "users"."id" ASC LIMIT $1  [["LIMIT", 11]]
```

**Comment by houhoulis** [comment]
@bankair , I was not able to reproduce this on Ruby 2.4.2 (not 2.4.1) and Rails 4.2.8 via any of these methods:

* modified bug report template script from https://github.com/rails/rails/blob/master/guides/bug_report_templates/active_record_master.rb
* fresh rails app, in rails console
* fresh rails app, running rails server

In all cases I tried both `.to_sql` as well as executing the query to inspect the result in the log.  I also tried both the `pg` and `sqlite3` gems.

Could you give a sample app or script to reproduce?

I wonder whether your version of postgresql makes a difference.  Does the behavior persist for you if you use sqlite?
