### ISSUE TITLE
Exception#as_json returns a string instead of Hash

### ISSUE THREAD

**Issue by allenwq** [rails/rails#30865]
After https://github.com/rails/rails/pull/23702, the `as_json` of `Exception` returns a `String` instead of `Hash`.  

For consistency, `as_json` should return a `Hash` and `to_json` should return a `String`.

This breaks my application in Rails 5 and I am not sure what's the reason behind this change.

**Comment by meinac** [comment]
> For consistency, as_json should return a Hash and to_json should return a String.

There are lots of cases where you can't return hash, like instances of TrueClass, FalseClass, NilClass, Integer etc.

> I am not sure what's the reason behind this change

The reason behind the change is already pointed in the pr you mentioned, to be coherent with default behaviour of `to_json` method.

**Comment by allenwq** [comment]
> The reason behind the change is already pointed in the pr you mentioned, to be coherent with default behaviour of to_json method.
Yes I realised that, however I believe there could be a better fix instead of changing the behaviour of `as_json`. 

This is a serious API change of the `Exception` class, and it will break for the everyone that relies on `as_json`.

**Comment by meinac** [comment]
> This is a serious API change of the Exception class, and it will break for the everyone that relies on as_json.

I agree, this introduces a breaking change but this is a **fix** which should have been done.

**Comment by allenwq** [comment]
Okay, thanks for the quick response! personally I think the fix might introduce more issues later, because it monkey patches the Exception class and made `as_json` same as `to_s`.  I believe there would be a better fix without this breaking change.
