### ISSUE TITLE
Rails 5.1.4 with Ruby 2.3.3 load slow .

### ISSUE THREAD

**Issue by vladi160** [rails/rails#30871]
I am creating an app, with Rails 5, but the problem is that it loads really slow, around 10-15 seconds.
This is only the first time loading, right after start the server (Puma). It doesn' t matter, is it development or production mode, it take more than 10 seconds to load simple page which is 11Kb. 
I made and test with new Rails app. The page which is by default loads normal, but if I create a route, controller and simple (empty) view, without assets it loads slow. This is happen only the first time after starting server. If I load page stop and start server and reload page it is slow, too. But if I load page after first time loading (after server starting), it loads normal. I am using Windows 10, but it is same on the Ubuntu, too. I am using Chrome and Firefox.
This is from my test app (console):

> Started GET "/test" for 127.0.0.1 at 2017-10-13 02:17:18 
> Processing by TestController#index as HTML
>  Rendering test/index.html.erb within layouts/application
>  Rendered test/index.html.erb within layouts/application (1.0ms)
> Completed 200 OK in 380ms (Views: 223.3ms)   

and this is from WEB console:
> test -> document -> 2.2KB -> 10.91s

**Comment by vinceve** [comment]
Hey @vladi160,

On what OS are you working? And would it be possible to upload your test code to a repo?

Kind regards,
Vince

**Comment by vladi160** [comment]
Hi, Windows 10 and Ubuntu. I can't upload my project, but I think I found some reason. Is it because server needs to spin up after start/restarting ? Is this happen not for first loading for each user, but only for the first loading from the server (for now I just can't check this)  ? In this case is it normal the app loads around 10-12 seconds ?
I have test app in the Heroku, which first time loads for around 10 seconds, but it is empty view with no assets.
And because on Heroku is same, I read this: "Free apps will sleep to converse resource".

**Comment by lostapathy** [comment]
Yes, you're seeing the time it takes for the app to start up.  I wouldn't worry about it, especially if it's only on the first request. Depending on how many gems you depend on and whether or not you're on an SSD it could get worse or better, but that's not an unreasonable startup time in my experience.

**Comment by vladi160** [comment]
Yes It is about the start-up. The problem was when I upload the app in Heroku (free account) and my friends access it. They said that is slow for them, too (in Heroku there is same process to start-up the app, if it is not used some time, this is only for free account).

**Comment by vedmant** [comment]
I'm curious why Rails startup take so much time. I use also Laravel a lot, and it has milliseconds time startup.

**Comment by vinceve** [comment]
Laravel is a php based framework and php is loaded when a request comes in. Rails is an environment that gets started and from then on requests can come in.

Both have their perks and disadvantages which you can search for on the internet. :)

**Comment by vedmant** [comment]
@vinceve Thanks, this is what I thought about. Yet I'm curious why it needs to load all the code and services on startup, this doesn't make sense especially for console commands when only one action is run at a time and it may require just a few services. In Laravel for example most of services are loaded only on first call instead of boot time.
