### ISSUE TITLE
ActiveRecord: conflict in foreign key names

### ISSUE THREAD

**Issue by rhys-vdw** [rails/rails#30873]
### Steps to reproduce

The following migration code:

```rb
add_foreign_key :usability_test_section_questions, :usability_test_sections, on_delete: :cascade
# ...
remove_reference(
  :usability_test_section_questions,
  :usability_test,
  foreign_key: { on_delete: :cascade },
)
```

### Expected behavior

Should create unique names for each constraint so that it can create one constraint and remove a different one.

### Actual behavior

Outputs the following which creates and removes the same constraint:

```sql
   (303.9ms)  ALTER TABLE "usability_test_section_questions" ADD CONSTRAINT "fk_rails_a2cf00f0c5"
FOREIGN KEY ("usability_test_section_id")
  REFERENCES "usability_test_sections" ("id")
 ON DELETE CASCADE
--
   (0.8ms)  ALTER TABLE "usability_test_section_questions" DROP CONSTRAINT "fk_rails_a2cf00f0c5"
```

### System configuration

**Rails version**:
```
5.0.5
```
**Ruby version**:
```
ruby 2.3.4p301 (2017-03-30 revision 58214) [x86_64-darwin16]
```

**Comment by al2o3cr** [comment]
I suspect this is the same issue fixed in #25285, which was released as part of 5.1.0.

**Comment by rhys-vdw** [comment]
@al2o3cr Sorry I haven't checked against 5.1.0. I just did a search for the issues and couldn't see any similar reports.

**Comment by eileencodes** [comment]
Sounds like this is fixed in a newer version of Rails. If it's not fixed please let me know and I'll reopen.
