### ISSUE TITLE
Rails remote form js handler no longer returns extra parameters for rails-ujs

### ISSUE THREAD

**Issue by dimroc** [rails/rails#30880]
### Steps to reproduce

Using `rails-ujs`, not `jquery-ujs`

The following remote form

```haml
= link_to "an article", @article, remote: true
```

can no longer be handled with the documented javascript as shown here http://edgeguides.rubyonrails.org/working_with_javascript_in_rails.html#form-with:

```javascript
  $("a[data-remote]").on("ajax:success", function(e, data, status, xhr) {
    console.log(data, status, xhr) // undefined
  }));
```

Discussion:
https://stackoverflow.com/a/45632235/639773

### Expected behavior
Either the parameters `e, data, status, xhr` are populated or update Rails documentation to talk about the new `event.detail` that does indeed work:

```javascript
    $("#new_article").on("ajax:success", function(event) {
      [data, status, xhr] = event.detail
      console.log(data);
    });
```

### Actual behavior
```javascript
  $("a[data-remote]").on("ajax:success", function(e, data, status, xhr) {
    console.log(data, status, xhr) // undefined
  }));
```

### System configuration
**Rails version**: 5.1.4

**Ruby version**: 2.4.1

**Comment by DmytroVasin** [comment]
@dimroc 

The link you provided ( [form_with](http://edgeguides.rubyonrails.org/working_with_javascript_in_rails.html#form-with) ) is true only when you use `jquery-ujs`

Signature of calls to UJS's event handlers has changed for `rails-ujs`.
Here is new documentation about that behaviour: [rails-ujs-event-handlers](http://edgeguides.rubyonrails.org/working_with_javascript_in_rails.html#rails-ujs-event-handlers)

**Comment by dimroc** [comment]
Thanks @DmytroVasin, I realized that and made a corresponding PR which I've referenced. It updates the documentation to the newer `rails-ujs` that's now the default in Rails 5.1+:

https://github.com/rails/rails/pull/30881

All feedback welcome.

**Comment by guilleiguaran** [comment]
Closing in favor of #30881
