### ISSUE TITLE
unit test failed to run single test

### ISSUE THREAD

**Issue by przbadu** [rails/rails#30900]
### Steps to reproduce

- go to your unit test project and run below commands:

```shell
bin/rake test TEST=test/controllers/api/v1/my_controller_test.rb TESTOPTS="-n /should run this test case/"
```

- I have vim-test setup, which is running test case like:

```shell
./bin/rake test TEST="test/controllers/api/v1/my_controller_test.rb" TESTOPTS="--name='/Api::V1::MyControllerTest\#test_should_run_this_test_case$/'"
```

### Expected behavior

It should run only one testcase i.e `test_should_run_this_test_case`

### Actual behavior

It is running all test cases under current Test file e.g: all test cases under `my_controller_test.rb`

### System configuration

**Rails version**: `Rails 4.2.7`

**Ruby version**: `ruby 2.3.1p112 (2016-04-26 revision 54768) [x86_64-darwin16]`

**Comment by gentcys** [comment]
It works as expected behavior here.

**Comment by lostapathy** [comment]
Any chance you can post a minimal app that replicates this?

I have seen similar behavior before on an app that was upgraded all the way from rails 2.0 and some of the generated files were never quite upgraded 100% correctly, you may be seeing similar.

**Comment by przbadu** [comment]
I generated new `4.2.7` app and it is working as expected. Any idea what could have missing in my old app?

**Comment by lostapathy** [comment]
Not offhand, sorry.  If this is an app you intend to continue supporting long-term, it's probably worth the effort to go through all the generated files and see how they differ from what you have, it'll make future upgrades easier.  It only took a few hours when I finally did it, and that process solved several other little annoyances for me as well.  Good luck!

**Comment by eileencodes** [comment]
Sounds like this is specific to your app and isn't an issue in Rails 4.2. That said Rails 4.2 isn't supported anymore except for severe security fixes, so I'm going to close this.

**Comment by przbadu** [comment]
@lostapathy thanks, I will see the diffs.

**Comment by przbadu** [comment]
Looks like:

`test/test_helper.rb`

```ruby
require 'test/unit'
```

was causing the problem. I guess we don't need this require in rails app, because default test case is `unit-test` and rails configure that for us.
