### ISSUE TITLE
undefined method '+' for nil:NilClass on actioncable connection

### ISSUE THREAD

**Issue by ianloblaw** [rails/rails#30908]
Hi I am seeing the following in production on connections to actioncable websockets.

`undefined method '+' for nil:NilClass

bundle/ruby/2.4.0/gems/websocket-driver-0.6.5/lib/websocket/driver/hybi.rb:11:in 'generate_accept'
bundle/ruby/2.4.0/gems/websocket-driver-0.6.5/lib/websocket/driver/hybi.rb:76:in 'initialize'
bundle/ruby/2.4.0/gems/websocket-driver-0.6.5/lib/websocket/driver.rb:158:in 'new'
bundle/ruby/2.4.0/gems/websocket-driver-0.6.5/lib/websocket/driver.rb:158:in 'rack'
bundle/ruby/2.4.0/gems/actioncable-5.1.4/lib/action_cable/connection/client_socket.rb:45:in 'initialize'
bundle/ruby/2.4.0/gems/actioncable-5.1.4/lib/action_cable/connection/web_socket.rb:8:in 'new'
bundle/ruby/2.4.0/gems/actioncable-5.1.4/lib/action_cable/connection/web_socket.rb:8:in 'initialize'
bundle/ruby/2.4.0/gems/actioncable-5.1.4/lib/action_cable/connection/base.rb:57:in 'new'
bundle/ruby/2.4.0/gems/actioncable-5.1.4/lib/action_cable/connection/base.rb:57:in 'initialize'
bundle/ruby/2.4.0/gems/actioncable-5.1.4/lib/action_cable/server/base.rb:28:in 'new'
bundle/ruby/2.4.0/gems/actioncable-5.1.4/lib/action_cable/server/base.rb:28:in 'call'
bundle/ruby/2.4.0/gems/actionpack-5.1.4/lib/action_dispatch/routing/mapper.rb:17:in 'block in <class:Constraints>'
bundle/ruby/2.4.0/gems/actionpack-5.1.4/lib/action_dispatch/routing/mapper.rb:46:in 'serve'
bundle/ruby/2.4.0/gems/actionpack-5.1.4/lib/action_dispatch/journey/router.rb:50:in 'block in serve'
bundle/ruby/2.4.0/gems/actionpack-5.1.4/lib/action_dispatch/journey/router.rb:33:in 'each'
bundle/ruby/2.4.0/gems/actionpack-5.1.4/lib/action_dispatch/journey/router.rb:33:in 'serve'
bundle/ruby/2.4.0/gems/actionpack-5.1.4/lib/action_dispatch/routing/route_set.rb:834:in 'call'
bundle/ruby/2.4.0/gems/rack-2.0.3/lib/rack/etag.rb:25:in 'call'
bundle/ruby/2.4.0/gems/rack-2.0.3/lib/rack/conditional_get.rb:25:in 'call'
bundle/ruby/2.4.0/gems/rack-2.0.3/lib/rack/head.rb:12:in 'call'
bundle/ruby/2.4.0/gems/rack-2.0.3/lib/rack/session/abstract/id.rb:232:in 'context'
bundle/ruby/2.4.0/gems/rack-2.0.3/lib/rack/session/abstract/id.rb:226:in 'call'`

### Steps to reproduce

I am not clear on how to reproduce this or what it's impact is to the client. Also I am not even sure that this a problem in actioncable, it might be the fault of websocket-driver or the client. I am a little out of my depth in trying to understand exactly what could be happening from the source code.

I have the following environment information from a failed request.

GATEWAY_INTERFACE: CGI/1.2
HTTP_ACCEPT_ENCODING: gzip, deflate, br
HTTP_ACCEPT_LANGUAGE: en-US,en;q=0.8
HTTP_CACHE_CONTROL: no-cache
HTTP_CONNECTION: upgrade
HTTP_PRAGMA: no-cache
HTTP_USER_AGENT: Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/61.0.3163.100 Safari/537.36
REQUEST_METHOD: GET
REQUEST_URI: /ws
SERVER_PROTOCOL: HTTP/1.1

### Expected behavior
An exception probably shouldn't occur? Or at least it should have sensible error message so the people know what went wrong.

### Actual behavior
undefined method '+' for nil:NilClass

### System configuration
**Rails version**: Rails 5.1.4

**Ruby version**: ruby 2.4.2p198 (2017-09-14 revision 59899) [x86_64-linux-gnu]

**Puma version**: 3.10.0

**Nginx version**: nginx/1.12.1

**Comment by eileencodes** [comment]
I don't think think this is an issue with Rails's Action Cable.

Using your traceroute the line throwing the error is from websocket-driver: https://github.com/faye/websocket-driver-ruby/blob/master/lib/websocket/driver/hybi.rb#L11

The `key` which is nil, is passed in here https://github.com/faye/websocket-driver-ruby/blob/master/lib/websocket/driver/hybi.rb#L76 and that key comes from `@socket.env` here: https://github.com/faye/websocket-driver-ruby/blob/master/lib/websocket/driver/hybi.rb#L71

I think this is an issue with `websocket-driver` and you should open an issue here: https://github.com/faye/websocket-driver-ruby

If you find anything else from the folks over at webdriver-socket that indicates Rails is causing the issue you're seeing please reopen.

**Comment by shrinathaithal** [comment]
Just for reference for folks who end up here, it is filed with webdriver-socket -    
https://github.com/faye/websocket-driver-ruby/issues/58   

In short, it seems like you should use Rails 5.2 if you can, update Gemfile with the fixed version or use the Nginx hack if that works for you.

**Comment by vikk2411** [comment]
@shrinathaithal - can you please tell us the nginx hack.. as I think our application is not ready to upgrade the rails version..

i tried adding these lines in my nginx.conf but did not work
`map $http_sec_websocket_key $connection_upgrade {
    default $http_connection;
    ''      close;
}`

**Comment by shrinathaithal** [comment]
> @shrinathaithal - can you please tell us the nginx hack.. as I think our application is not ready to upgrade the rails version..
> 
> i tried adding these lines in my nginx.conf but did not work
> `map $http_sec_websocket_key $connection_upgrade { default $http_connection; '' close; }`

Do you have relevant `/cable` block as well? 

```
  location /cable {
    proxy_pass http://puma_<yourwebsite>.com;
    proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection "upgrade";
  }
```

**Comment by vikk2411** [comment]
> > @shrinathaithal - can you please tell us the nginx hack.. as I think our application is not ready to upgrade the rails version..
> > i tried adding these lines in my nginx.conf but did not work
> > `map $http_sec_websocket_key $connection_upgrade { default $http_connection; '' close; }`
> 
> Do you have relevant `/cable` block as well?
> 
> ```
>   location /cable {
>     proxy_pass http://puma_<yourwebsite>.com;
>     proxy_http_version 1.1;
>     proxy_set_header Upgrade $http_upgrade;
>     proxy_set_header Connection "upgrade";
>   }
> ```

yes I do have this block..  should I add something in this block?
