### ISSUE TITLE
Enum conflict detection disallows common values between different enum fields

### ISSUE THREAD

**Issue by zackxu1** [rails/rails#30913]
### Steps to reproduce

I have an ActiveRecord model `Account` with two different enum fields, which share common values.  For example,

    enum billing_frequency: { monthly: 1, quarterly: 2 }
    enum statement_frequency: { quarterly: 1, yearly: 2 }

### Expected behavior

The above is allowed.

### Actual behavior

I get error message:
    /Users/username/.rvm/gems/ruby-2.4.1/gems/activerecord-5.1.3/lib/active_record/enum.rb:230:in `raise_conflict_error': You tried to define an enum named "statement_frequency" on the model "Account", but this will generate a instance method "quarterly?", which is already defined by another enum. (ArgumentError)

I guess ActiveRecord creates methods like `monthly?`, `quarterly?` on the object.
But it's ambiguous, compare

    account.monthly?

with

    account.billing_frequency_monthly?

The latter is clearly more clear in intent.

### System configuration
**Rails version**: 5.1.3

**Ruby version**: 2.4.1

**Comment by nmichels** [comment]
Hi @zackxu1 I agree that it would be nice to have ActiveRecord allowing more than one enum to have the same value, I don't know if this is currently possible but another way to generate the method would be something like that:
```
account.billing_frequency.quarterly?
account.statement_frequency.quarterly?
```

For sure it will be a breaking change, so it will require further analysis.

**Comment by zackxu1** [comment]
The `_prefix` and `_suffix` options solve my problem.

Quoting http://api.rubyonrails.org/v5.1/classes/ActiveRecord/Enum.html
`You can use the :_prefix or :_suffix options when you need to define multiple enums with same values.`
