### ISSUE TITLE
Rails UJS - Are all the features documented anywhere?

### ISSUE THREAD

**Issue by wmakley** [rails/rails#30924]
I've googled a lot, but I cannot find a list of Rails/jQuery UJS features/functions anywhere. I just want to make sure I don't reinvent the wheel and add redundant page load scripts in my own project, when I could have just put a data attribute on a tag.

**Comment by saiqulhaq** [comment]
I think it's already documented on [https://github.com/rails/jquery-ujs/wiki](https://github.com/rails/jquery-ujs/wiki)

**Comment by rafaelfranca** [comment]
Yes. Documentation is on https://github.com/rails/jquery-ujs/wiki, but it would be great if we move that documentation to rails-ujs readme.

**Comment by fakefarm** [comment]
> Yes. Documentation is on https://github.com/rails/jquery-ujs/wiki, but it would be great if we move that documentation to rails-ujs readme.

Hi @rafaelfranca, I'd be willing to submit a PR for this. I was thinking of putting the readme at the following location, unless you suggest otherwise: `/rails/rails/tree/master/actionview/app/assets/javascripts/rails-ujs`
