### ISSUE TITLE
Undefined Symbol: OPENSSL_init_ssl when starting server

### ISSUE THREAD

**Issue by oshanley** [rails/rails#30934]
I've tried everything I could think of to fix the issue before posting here. I've uninstalled and reinstalled openssl, changed the config, etc. and nothing helps. 

### Steps to reproduce
Generate new rails app via `rails new <app>`
`bundle install`
Start server via `bin/rails server`

### Expected behavior
Server should start

### Actual behavior
Server exits with `/var/lib/gems/2.3.0/gems/activesupport-5.0.6/lib/active_support/dependencies.rb:293:in `require': /var/lib/gems/2.3.0/gems/puma-3.10.0/lib/puma/puma_http11.so: undefined symbol: OPENSSL_init_ssl - /var/lib/gems/2.3.0/gems/puma-3.10.0/lib/puma/puma_http11.so (LoadError)`

### System configuration
Running on ElementaryOS 0.4.1 Loki, built on Ubuntu 16.04.3 LTS
Path to openssl: /usr/bin/openssl

**Rails version**:
Rails 5.0.6

**Ruby version**:
ruby 2.3.1p112 (2016-04-26) [x86_64-linux-gnu]

**Comment by rafaelfranca** [comment]
Thank you for the issue. It is a problem with puma, please open an issue there.
