### ISSUE TITLE
Documentation for html_escape implies that it's needed if you want to escape content in ERB templates

### ISSUE THREAD

**Issue by maxfelsher** [rails/rails#30931]
The documentation for `ERB::Util.html_escape` includes the following:
 
```ruby
    # In your ERB templates, use this method to escape any unsafe content. For example:
    #   <%= h @person.name %>
```
(taken from https://github.com/rails/rails/blob/v5.1.4/activesupport/lib/active_support/core_ext/string/output_safety.rb#L15 and visible at http://api.rubyonrails.org/classes/ERB/Util.html#method-c-html_escape).

This sentence and example appear to have been added in a1b0349362fd6c17af5aeff481996f6fac235828 (see `actionpack/lib/action_view/template_handlers/erb.rb`), which was from Rails 2.1. My understanding is that, since Rails 3, it's been redundant to use `h` within a `<%= %>` section. Seeing this documentation has confused me, though.

Is it correct that the use in the documentation would be redundant in modern Rails? If yes, would the preference be to delete this example or try to rework it into a more relevant one?

**Comment by rafaelfranca** [comment]
> Is it correct that the use in the documentation would be redundant in modern Rails?
Yes

> If yes, would the preference be to delete this example or try to rework it into a more relevant one?

Yes. Could you open a PR?

**Comment by maxfelsher** [comment]
Thanks, @rafaelfranca. Done.
