### ISSUE TITLE
Rack app error when using SystemTestCase alongside ActiveStorage

### ISSUE THREAD

**Issue by jeffreyguenther** [rails/rails#30935]
### Steps to reproduce

We are using system tests and ActiveStorage for attachments. To run a set of tests that check a user-choosable theme, the app requires that we load real data into the app. This includes loading files into our objects. We have code that builds up a sample organization for each test and then we run our capybara methods and assertations based on that sample data.

Views that reference attached files use `url_for` creating URLs to the blob.

I've isolated the storage for ActiveStorage by adding the following to `storage.yml` and setting the service for the test environment to `:local_test`.

```
local_test:
  service: Disk
  root: <%= Rails.root.join("storage_test") %>
```

I added a teardown method to `ApplicationSystemTestCase` to ensure that all the files in the store are removed after each test.

```
  def tear_down
    FileUtils.rm_rf("#{Rails.root}/storage_test")
  end
```

### Expected behavior
I would expect no error to be raised.

### Actual behavior

Intermittently, we receive the following log at various points while the test suite is running:

```
2017-10-19 16:29:51 -0700: Rack app error handling request { GET /rails/active_storage/blobs/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBcXNOIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--916509bbf4cea7904172997246178dd84441d3fc/default.jpg }
#<ActiveRecord::RecordNotFound: Couldn't find ActiveStorage::Blob with 'id'=3499>
/Users/jeffreyguenther/.rbenv/versions/2.3.4/lib/ruby/gems/2.3.0/bundler/gems/rails-a52ff1b0848e/activerecord/lib/active_record/core.rb:182:in `find'
/Users/jeffreyguenther/.rbenv/versions/2.3.4/lib/ruby/gems/2.3.0/bundler/gems/rails-a52ff1b0848e/activestorage/app/models/active_storage/blob.rb:38:in `find_signed'
```

It appears that the Chrome instance driving the test is looking for a file after the test runner has cleaned up and moved to the next file and ActiveStorage is throwing an exception when it can find the file that's been deleted. Is this true? Is there something I should be doing differently in my test suite setup to allow these two features to interact?

### System configuration
**Rails version**: rails/master commit: a52ff1b0848e8bb2310738ec7b762b82edbbfcb2
**Ruby version**: 2.3.4

**Comment by jeffreyguenther** [comment]
I know this probably has nothing to do with the issue, but when I run the system tests using `rails test:system` I see more instances of this issue than if run them using `rails test test/system/**`.

Trying to collect data as I go.

**Comment by twalpole** [comment]
You need to make sure your removal of files doesn't happen until after the `Capybara.reset_sessions!` call in `ActionDispatch::SystemTesting::TestHelper::SetupAndTeardown#after_teardown`.  Until that returns requests may still be active.

**Comment by jeffreyguenther** [comment]
I can confirm that doing file removal after the sessions are reset works as anticipated.

What I ended up doing was:

``` ruby
class ApplicationSystemTestCase < ActionDispatch::SystemTestCase
  driven_by :selenium, using: :chrome, screen_size: [1400, 1400]

  def remove_uploaded_files
    FileUtils.rm_rf("#{Rails.root}/storage_test")
  end

  def after_teardown
    super
    remove_uploaded_files
  end
end
