### ISSUE TITLE
Rails adding too many decimals to datetime precision in MySQL

### ISSUE THREAD

**Issue by jasonperrone** [rails/rails#30942]
### Steps to reproduce
I have attached a testing file for this. You will need a MySQL database.

### Expected behavior
I want a particular table's created_at and updated_at to be stored in the database with millisecond precision, like 2017-10-20 18:31:23.234.  The way we've done that in my app with Rails 3.1 thru 4.1 is twofold:
1) Define the datetime columns for this table in the migration with precision: 3, such as t.datetime "created_at",                 precision: 3, null: false
    That creates the table in MySQL as a datetime(3) so it can store the milliseconds
2) Override the db Date Format in Rails so that Rails will actually put the precise time in:
Time::DATE_FORMATS[:db] = '%Y-%m-%d %H:%M:%S.%3N'

What has always happened in Rails 3.1 -> 4.1 is that for all datetime fields with no precision in the migration, the dates were merely stored without the precision, such as 2017-10-19 18:31:23. IF you happened to define the field with precision: 3, then the date would be inserted with the decimals to 3 places, like 2017-10-20 18:31:23.234.

### Actual behavior
Starting in 4.2, what is happening is that Rails is putting an extra decimal on the date before it inserts it, like 2017-10-20 18:31:23.234.234. Here is the error right from the test attached:

ActiveRecord::StatementInvalid: Mysql2::Error: Incorrect datetime value: '2017-10-20 13:09:18.031.031' for column 'created_at' at row 1: INSERT INTO `payments` (`created_at`) VALUES ('2017-10-20 13:09:18.031.031')

Not sure what to do because if I remove the precision: 3 from the migration, the date is not stored in the database with the precision. If I don't override the :db time format, Rails doesn't put the precision on the date before it saves it. So it seems I can either have no precision, or have Rails create the decimal portion twice.

### System configuration
**Rails version**: 4.2.9

**Ruby version**: 2.3.4

**MySQL 2 Gem Version: 0.3.21
[create_precise_table.zip](https://github.com/rails/rails/files/1402115/create_precise_table.zip)

**Comment by jasonperrone** [comment]
Hmm, I may have to look into this more. In my test, if I remove the override of the time format, it inserts the date precisely and correctly, but in my app, it does not create the decimal portion at all. Stay tuned.

**Comment by jasonperrone** [comment]
Ok, so in my further testing, Rails 4.2 by default inserts dates with full precision as if you defined Time::DATE_FORMATS[:db] = '%Y-%m-%d %H:%M:%S.%3N' in an initializer.

I still think it's a bug that if you DO define that DATE_FORMAT override for [:db], then SQL inserts produce the invalid date with the two decimal parts.

**Comment by rafaelfranca** [comment]
How Active Record behaves if you don't override a private data format?

**Comment by pixeltrix** [comment]
@jasonperrone I'm going to close this since it seems that you've found that the previous hack you did to get precision support for MySQL is no longer needed now it's built into Active Record from Rails 4.2. If this isn't the case then please comment.

**Comment by jasonperrone** [comment]
Well I think it's a bug that if you define a DATE_FORMAT for the :db format that the SQL is invalid rather than just overriding the :db format. Do you know what I mean? It should take my override of the :db format and use it, rather than create invalid dates in the generated SQL statements.

**Comment by pixeltrix** [comment]
@jasonperrone since different columns have different levels of precision I think relying on `:db` to set the date format for all circumstances would be incorrect - I'd rather we stop using it to format dates and and times entirely.

**Comment by khiav223577** [comment]
It still happens in Rails 6. :(

We added this line `Time::DATE_FORMATS[:db] = "%Y-%m-%d %H:%M:%S.%6N"` in 2017, when our project was in Rails 4.0.x. Didn't find this bugs until 4 years later......

If setting the format of `:db` will cause problems, it will be nice if rails can throw errors or show warnings so that we can find this problem earlier.
