### ISSUE TITLE
Accessing both request.raw_post and params in the same action in tests fails

### ISSUE THREAD

**Issue by fabn** [rails/rails#30946]
I'm testing a paypal integration within a controller test and I see a weird behaviour within ActionController::TestCase. Since paypal signs request body I need to access `request.raw_body` to verify signature and then I need request params to process the payment, so the controller action I'm testing is more or less this

```ruby
def process
  if valid_signature?(request.raw_post)
    ProcessPaymentJob.perform_later(params.to_unsafe_h)
    head :created
  else
    head :bad_request
  end
end
```

The code is working when running the application but it fails with this test case:

```ruby
post :process_notification, body: raw_ipn
expect(subject).to respond_with :created
# A job has been enqueued with the given arguments
expect(ProcessPaymentJob).to have_been_enqueued.with(hash_including('payment_type' => 'instant'))
```

The previous test is written with RSpec but the same happens within rails ActionController::TestCase

### Steps to reproduce

Here's a quick script to reproduce the issue
```ruby
begin
  require "bundler/inline"
rescue LoadError => e
  $stderr.puts "Bundler version 1.10 or later is required. Please update your Bundler"
  raise e
end

gemfile(true) do
  source 'https://rubygems.org'
  gem 'rails', '5.1.4'
  gem 'byebug'
end

require "action_controller/railtie"

class TestApp < Rails::Application
  config.root = File.dirname(__FILE__)
  secrets.secret_token    = "secret_token"
  secrets.secret_key_base = "secret_key_base"

  config.logger = Logger.new($stdout)
  Rails.logger  = config.logger

  routes.draw do
    post "/" => "test#parse_body"
  end
end

class TestController < ActionController::Base
  include Rails.application.routes.url_helpers

  def parse_body
    render json: {raw_post: request.raw_post, params: params.to_unsafe_h.except('controller', 'action')}
  end
end

require "rails/test_help"
require "minitest/autorun"

class TestControllerTest < ActionController::TestCase
  test "accessing both params and raw_post using body: String syntax" do
    post :parse_body, body: 'payment_type=instant'
    assert response.ok?
    expected_response = {'raw_post' => 'payment_type=instant', 'params' => {'payment_type' => 'instant'}}
    assert_equal expected_response, JSON.parse(response.body)
  end
  
  test "accessing both params and raw_post using params syntax" do
    post :parse_body, params: {payment_type: 'instant'}
    assert response.ok?
    expected_response = {'raw_post' => 'payment_type=instant', 'params' => {'payment_type' => 'instant'}}
    assert_equal expected_response, JSON.parse(response.body)
  end
end
```

### System configuration
**Rails version**: 5.1.4
**Ruby version**: 2.3.1

**Comment by rafaelfranca** [comment]
Does it work with `ActionPack::IntegrationTest`?

**Comment by fabn** [comment]
I don't have any integration test right now, I'm still working at controller level.

However I've found out that it works (actually kind of...) if I pass both params and body keywords.

```ruby
post :process_notification, params: ipn, body: raw_ipn
```

i.e. it seems that if parameters are passed in a POST request `request.raw_post` is populated accordingly, the inverse is not true.

In my case I cannot pass parameters because signature is computed against the raw body string and passing it as parameter hash keep values but not the order of them in raw body.

**Comment by Wirachmat** [comment]
G
Nbnjjjnnnnnmmmmllllppppiiii

Pada tanggal 21 Okt 2017 04:09, "Fabio Napoleoni" <notifications@github.com>
menulis:

**Comment by rafaelfranca** [comment]
`ActionController::TestCase` is soft deprecated in Rails 5.1 exactly because it doesn't behaves in the same way a true request does. It is recommended to you to use `ActionDispatch::IntegrationTest`. In fact all the controller tests in Rails 5.1 are generated using `ActionDispatch::IntegrationTest` as superclass, so even that you are working at controller level that is the superclass your should be using.

**Comment by fabn** [comment]
I tried the same script above, however if I just replace `ActionController::TestCase` with `ActionDispatch::IntegrationTest` I get this error:

```
E

Error:
TestControllerTest#test_accessing_both_params_and_raw_post_using_body:_String_syntax:
ArgumentError: unknown keyword: body
```

Also first test fails with this error

```
E

Error:
TestControllerTest#test_accessing_both_params_and_raw_post_using_params_syntax:
URI::InvalidURIError: bad URI(is not URI?): http://www.example.com:80parse_body
```

It seems that `ActionDispatch::IntegrationTest` does not accept raw body for post requests.

**Comment by rafaelfranca** [comment]
`params` in integrations tests is the raw body. And the second one is failing because it is missing the `/` in front of `parse_body` since integration test receive a URL path.
