### ISSUE TITLE
ActiveSupport Array#to code refactor

### ISSUE THREAD

**Issue by coderhs** [rails/rails#30950]
Was looking through the code of active_support `Array#to`, code for it is:

```rb
def to(position)
    if position >= 0
      take position + 1
    else
      self[0..position]
    end
end
```

Not sure of the purpose of that condition as just `self[0..position]` does achieve the purpose. I changed the code to 

```rb
def to(position)
  self[0..position]
end
```

and all the test passes.

If this is a scope to reduce lines of code and refactor, do let me know and I will send a PR :)

**Comment by matthewd** [comment]
Blame shows that this was introduced in ed03d4eaa89a7b4ab09e7f5da76b522d04650daf, to avoid needlessly allocating the range object.
