### ISSUE TITLE
Unfriendly default on ApplicationSystemTestCase#after_teardown

### ISSUE THREAD

**Issue by rpbaptist** [rails/rails#30957]
### Steps to reproduce

Run a failing system spec from any terminal which isn't iterm2. 

### Expected behavior

I would expect to see the error displayed.

### Actual behavior

Binary output is put directly into the terminal.

### System configuration
**Rails version**:  5.1.4

**Ruby version**: 2.4.2

Currently it's not possible to disable screenshot on failure without overriding the `ApplicationSystemTestCase#after_teardown` or `#take_failed_screenshot`. I found an env variable with API docs: `RAILS_SYSTEM_TESTING_SCREENSHOT`

I propose to make the default `simple` instead of `inline` as the last option works on specific configurations only.

**Comment by rafaelfranca** [comment]
cc @eileencodes

**Comment by eileencodes** [comment]
I've changed the default to simple so hopefully that will behave better for you. Thanks for the report!

**Comment by rpbaptist** [comment]
Thanks very much for your response. Awesome work on system tests by the way!
