### ISSUE TITLE
PG::ConnectionBad: PQsocket() can't get socket descriptor: SELECT ...

### ISSUE THREAD

**Issue by TimBest** [rails/rails#30968]
This error started appearing when upgrading to Rails 5.1. Where a small number of queries would fail raising `PG::ConnectionBad: PQsocket() can't get socket descriptor: SELECT ...`

### Expected behavior
The db connection should be reconnected if it experiences an issue

### Actual behavior
Rails checks out a connection and verifies that is is valid. And then when it is time to execute a query PQsocket() returns -1 indicating the socket has closed. Causing the error.

Although in this [comment](https://github.com/rails/rails/issues/29189#issuecomment-303268979) it appear that is may be difficult to reestablish the connection due to potential state. However this seems like a different case since it is just a small number of request that are failing and postgres is not being reset.

I also noticed that there are [suggestions](https://discuss.circleci.com/t/pg-connectionbad-pqsocket-cant-get-socket-descriptor/470) to set a `reaping_frequency`. Since this error can be an indication that the connection pool has been exhausted. However this does not seem like it would help since the connection is being verified as active when it is checked out. 

#### StackTrace 
```
rails/activerecord/lib/active_record/connection_adapters/postgresql/database_statements.rb" line 73 in async_exec
rails/activerecord/lib/active_record/connection_adapters/postgresql/database_statements.rb" line 73 in block (2 levels) in execute
rails/activesupport/lib/active_support/dependencies/interlock.rb" line 46 in block in permit_concurrent_loads
rails/activesupport/lib/active_support/concurrency/share_lock.rb" line 185 in yield_shares
rails/activesupport/lib/active_support/dependencies/interlock.rb" line 45 in permit_concurrent_loads
rails/activerecord/lib/active_record/connection_adapters/postgresql/database_statements.rb" line 72 in block in execute
rails/activerecord/lib/active_record/connection_adapters/abstract_adapter.rb" line 612 in block (2 levels) in log
.rbenv/versions/2.4.1/lib/ruby/2.4.0/monitor.rb" line 214 in mon_synchronize
rails/activerecord/lib/active_record/connection_adapters/abstract_adapter.rb" line 611 in block in log
rails/activesupport/lib/active_support/notifications/instrumenter.rb" line 21 in instrument
octopus/lib/octopus/abstract_adapter.rb" line 13 in instrument
rails/activerecord/lib/active_record/connection_adapters/abstract_adapter.rb" line 603 in log
rails/activerecord/lib/active_record/connection_adapters/postgresql/database_statements.rb" line 71 in execute
rails/activerecord/lib/active_record/connection_adapters/postgresql/database_statements.rb" line 131 in begin_db_transaction
rails/activerecord/lib/active_record/connection_adapters/abstract/transaction.rb" line 130 in initialize
rails/activerecord/lib/active_record/connection_adapters/abstract/transaction.rb" line 156 in new
rails/activerecord/lib/active_record/connection_adapters/abstract/transaction.rb" line 156 in block in begin_transaction
.rbenv/versions/2.4.1/lib/ruby/2.4.0/monitor.rb" line 214 in mon_synchronize
rails/activerecord/lib/active_record/connection_adapters/abstract/transaction.rb" line 152 in begin_transaction
rails/activerecord/lib/active_record/connection_adapters/abstract/transaction.rb" line 193 in block in within_new_transaction
.rbenv/versions/2.4.1/lib/ruby/2.4.0/monitor.rb" line 214 in mon_synchronize
rails/activerecord/lib/active_record/connection_adapters/abstract/transaction.rb" line 191 in within_new_transaction
rails/activerecord/lib/active_record/connection_adapters/abstract/database_statements.rb" line 235 in transaction
octopus/lib/octopus/proxy.rb" line 122 in transaction
rails/activerecord/lib/active_record/transactions.rb" line 210 in transaction
rails/activerecord/lib/active_record/transactions.rb" line 381 in with_transaction_returning_status
rails/activerecord/lib/active_record/transactions.rb" line 308 in block in save
rails/activerecord/lib/active_record/transactions.rb" line 323 in rollback_active_record_state!
rails/activerecord/lib/active_record/transactions.rb" line 307 in save
rails/activerecord/lib/active_record/suppressor.rb" line 42 in save
(Controller)
```

### System configuration
**Rails version**: 5.1.3

**Ruby version**: 2.4.1

**Comment by matthewd** [comment]
> `octopus/lib/octopus/proxy.rb" line 122 in transaction`

My guess would be that the gem whose job is to swap connections out from under AR, is swapping connections out from under AR -- presumably after we verify, and without doing any verification for itself.

**Comment by TimBest** [comment]
Fair point will look into the octopus gem

**Comment by 3minus1** [comment]
Are you using a sneakers worker by any chance?

**Comment by anirudh-dasu** [comment]
@3minus1 I am using sneakers worker and facing this issue. Have you faced the same and managed to resolve it?

**Comment by wwwermishel** [comment]
Hi all! I have the same problem. Is there any solution for this problem?
@3minus1 @anirudh-dasu could you tell me how you solved this problem?
