### ISSUE TITLE
ActiveRecord does not unscope where conditions when right-hand side is a group

### ISSUE THREAD

**Issue by jemminger** [rails/rails#30967]
### Steps to reproduce
https://gist.github.com/jemminger/b14dc10bc1501c9efce081729182de33

### Expected behavior
Calling `unscope` for `:where` on a column with a group RH side should remove that column's conditions

### Actual behavior
The column's conditions remain

### System configuration
**Rails version**: 5.1.3

**Ruby version**: 2.3.4

**Comment by jemminger** [comment]
I think I've fixed it in the second part of the gist.  I'm not so sure how to go about writing the test for it though.

**Comment by markedmondson** [comment]
Just ran into this on 5.2.1. Still valid.

`Widget.where(dongle_id: [nil, 1, 2]).unscope(where: :dongle)`
> => SELECT "widgets".* FROM "widgets" WHERE ("widgets"."dongle_id" IN (1, 2) OR "widgets"."dongle_id" IS NULL)

**Comment by jemminger** [comment]
I'll update my local fix and create a PR for 5.1 and probably 5.2 as well, we'll see if they take it

**Comment by markedmondson** [comment]
Thanks @jemminger - I've been digging around for a while and your solution certainly seems to be the correct route.

**Comment by markedmondson** [comment]
I think I kind of got around it with a hack (untested psuedo code):

```ruby
class Widget
  scope :dongle -> { where(dongle_id: [nil, 1, 2]) }

  def self.unscope_dongle
    current_clause = current_scope.where_clause
    unscope_clause = unscoped.dongle.where_clause
  
    current_scope.unscope(:where).tap do |scope|
      scope.where_clause = current_clause - unscope_clause
    end
  end
end
```

`Widget.dongle.where(name: "thingy").unscope_dongle` 
> => SELECT "widgets".* FROM "widgets" WHERE "widgets"."name" = 'thingy'

It also lets you effectively rescope with:

`Widget.dongle.unscope_dongle.where(dongle_id: [nil, 1])` 
> => SELECT "widgets".* FROM "widgets" WHERE "widgets"."dongle_id" IS NULL OR "widgets"."dongle_id" = 1
