### ISSUE TITLE
belongs_to_required_by_default is not setting required: true in belongs_to association

### ISSUE THREAD

**Issue by lourenci** [rails/rails#30977]
I migrated a Rails 4 app to 5.0.6. The new default for `belongs_to` association is required.

I have `Rails.application.config.active_record.belongs_to_required_by_default = true` configured in my app. I can confirm this on rails console.

I have a model that has a `belongs_to` association:
![image](https://user-images.githubusercontent.com/2339362/31971283-e4de2dd2-b8f9-11e7-88d4-a3463bcc4c7b.png)

When I create a new record, it's valid even if I don't define its association:
![image](https://user-images.githubusercontent.com/2339362/31971423-908e96f8-b8fa-11e7-8051-2f91f471f97c.png)

### Expected behavior
The belongs_to association should trigger a validation error by default if the association is not present.

### System configuration
**Rails version**: 5.0.6

**Ruby version**: ruby 2.2.5p319 (2016-04-26 revision 54774) [x86_64-linux]

**Comment by rafaelfranca** [comment]
Can you please provide a sample application that reproduces the error?

**Comment by simi** [comment]
@rafaelfranca feel free to assign me then (I'm original contributor of this change).
