### ISSUE TITLE
Combining references, includes and left_joins produces invalid queries

### ISSUE THREAD

**Issue by ameboide** [rails/rails#30974]
### Steps to reproduce

When constructing a query using `references` at some point, joining the same `belongs_to` relation with both `includes` and `left_joins` will produce a query containing 2 identical `left outer join` statements, raising a MySQL exception.
This only happens when using `references` at some point (referencing either the same or any other relation), with a `belongs_to` relation (`has_many` works fine) and `left_joins` (`joins` is also fine)
 
```ruby
# frozen_string_literal: true

begin
  require "bundler/inline"
rescue LoadError => e
  $stderr.puts "Bundler version 1.10 or later is required. Please update your Bundler"
  raise e
end

gemfile(true) do
  source "https://rubygems.org"

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  gem "rails", github: "rails/rails"
  gem "arel", github: "rails/arel"
  gem "sqlite3"
end

require "active_record"
require "minitest/autorun"
require "logger"

# This connection will do for database-independent bug reports.
ActiveRecord::Base.establish_connection(adapter: "sqlite3", database: ":memory:")
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :posts, force: true do |t|
  end

  create_table :comments, force: true do |t|
    t.integer :post_id
  end
end

class Post < ActiveRecord::Base
  has_many :comments
end

class Comment < ActiveRecord::Base
  belongs_to :post
end

class BugTest < Minitest::Test
  def test_association_stuff
    count = Comment.includes(:post).references(:post).left_joins(:post).count

    assert_equal 0, count
  end
end
```

### Expected behavior

```sql
SELECT COUNT(DISTINCT `comments`.`id`) 
FROM `comments` 
LEFT OUTER JOIN `posts` ON `posts`.`id` = `comments`.`post_id`
```

### Actual behavior

```sql
-- ActiveRecord::StatementInvalid: Mysql2::Error: Not unique table/alias: 'posts': 
SELECT COUNT(DISTINCT `comments`.`id`) 
FROM `comments` 
LEFT OUTER JOIN `posts` ON `posts`.`id` = `comments`.`post_id` 
LEFT OUTER JOIN `posts` ON `posts`.`id` = `comments`.`post_id`
```

### System configuration
**Rails version**: 5.0.6 / 5.1.4

**Ruby version**: 2.3.1

**Comment by rafaelfranca** [comment]
Why are you using `includes`, `references` and `left_joins` in the same table?

**Comment by ameboide** [comment]
Because it's a chain of existing scopes and filters. First there's a scope that uses `references` for a different relation, then a filter that needs the `left_joins`, and finally `includes` in the controller to avoid lazy loading that relation for each item of the list that needs to be displayed.

It would expand to something like this: 
```ruby
Comment.references(:author).where('something about the author')
  .left_joins(:post).where('something about the post')
  .includes(:post).each do |comment| 
    puts comment.post.content 
  end
end
```

**Comment by rafaelfranca** [comment]
If you already have `includes` you don't need `left_joins`. It makes sense to Active Record generates invalid SQL because you are asking it to do the same thing twice.

**Comment by ameboide** [comment]
True, but my example was just a simplification of the actual code. In reality there are many methods involved in the construction of that query, which are called from many different places. In most of those cases using `includes` for the filtering method would only slow things down as the related ActiveRecord object isn't needed, so it makes sense to use `left_joins` there.
Besides, this problem only occurs with `left_joins`, not with `joins`, which seems to imply this use case was originally considered and solved but not replicated.

**Comment by kamipo** [comment]
It works on master.

**Comment by ameboide** [comment]
Thank you. Will this fix make it to 5.0.x or 5.1.x?

**Comment by kamipo** [comment]
I don't have time to investigate which commit has fixed this issue.
Can you find that commit?

**Comment by ameboide** [comment]
Probably 40cadf52db5e21349f6ecd9c4dc9b89d42ebc986, maybe 9fedd013475456dc9bdbf0be45a194cc5fc2566e helped too

**Comment by guich-wo** [comment]
Includes handle eager loading, though left_joins handle associated conditions.
Not sure if stil the case, but in some cases the includes triggers a separated query and could not be used to set conditions.
