### ISSUE TITLE
Active Record 'Is not null' query very slow

### ISSUE THREAD

**Issue by valterbarros** [rails/rails#30987]
### Expected behavior
Expect return data is not null more fast

### Actual behavior
I'm try run this query but is very slow spend so much time:

```
result.distinct(true)
.where(obras: { id: construction_site_id })
.where.not(dados_inspecao: { quantidade_erros: 0} )
.where.not(dados_inspecao: { quantidade_erros: nil } )
```

**If I run without 'is not null' statement is pretty fast**

result#to_sql:
`SELECT DISTINCT servicos.id, servicos.titulo as service_title, sum(quantidade_erros) as qtd FROM "dados_inspecao" INNER JOIN "fvs_metodos_verificados" ON "fvs_metodos_verificados"."id" = "dados_inspecao"."fvs_metodos_verificados_id" INNER JOIN "fvs_preenchimento" ON "fvs_preenchimento"."id" = "fvs_metodos_verificados"."fvs_preenchimento_id" INNER JOIN "fvs" ON "fvs"."id" = "fvs_preenchimento"."fvs_id" AND "fvs"."empresas_id" = 44093 INNER JOIN "atividade" ON "atividade"."id" = "fvs_preenchimento"."atividade_id" AND "atividade"."empresas_id" = 44093 INNER JOIN "servicos" ON "servicos"."id" = "atividade"."servicos_id" AND "servicos"."empresas_id" = 44093 INNER JOIN "local" ON "local"."id" = "atividade"."local_id" INNER JOIN "obras" ON "obras"."id" = "local"."obras_id" AND "obras"."empresas_id" = 44093 WHERE "obras"."id" = 96520 AND ("dados_inspecao"."quantidade_erros" != 0) AND ("dados_inspecao"."quantidade_erros" IS NULL) GROUP BY servicos.id`

I already try this and I had no success:

`ActiveRecord::Base.connection.execute(%Q{ SELECT DISTINCT servicos.id, servicos.titulo as service_title, sum(quantidade_erros) as qtd FROM "dados_inspecao" INNER JOIN "fvs_metodos_verificados" ON "fvs_metodos_verificados"."id" = "dados_inspecao"."fvs_metodos_verificados_id" INNER JOIN "fvs_preenchimento" ON "fvs_preenchimento"."id" = "fvs_metodos_verificados"."fvs_preenchimento_id" INNER JOIN "fvs" ON "fvs"."id" = "fvs_preenchimento"."fvs_id" AND "fvs"."empresas_id" = 44093 INNER JOIN "atividade" ON "atividade"."id" = "fvs_preenchimento"."atividade_id" AND "atividade"."empresas_id" = 44093 INNER JOIN "servicos" ON "servicos"."id" = "atividade"."servicos_id" AND "servicos"."empresas_id" = 44093 INNER JOIN "local" ON "local"."id" = "atividade"."local_id" INNER JOIN "obras" ON "obras"."id" = "local"."obras_id" AND "obras"."empresas_id" = 44093 WHERE "obras"."id" = 96520 AND ("dados_inspecao"."quantidade_erros" != 0) AND ("dados_inspecao"."quantidade_erros" IS NULL) GROUP BY servicos.id })`

### System configuration
**Rails version**: 4.2.0

**Ruby version**: 2.2.5

**Comment by rafaelfranca** [comment]
Thank you for the issue. Active Record is not responsible for query performance. It only generates the query you asked it to do.

**Comment by valterbarros** [comment]
But is on postgres this query is very very fast

**Comment by rafaelfranca** [comment]
I see. Are you able to reproduce this in Rails 5.1? Rails 4 is not supported anymore.

**Comment by valterbarros** [comment]
Not because I will spend very long time to update the all system to rails 5.1. Because is a system in production with many clients.

To measure this the system has 3000+ specs

**Comment by rafaelfranca** [comment]
It doesn't need to be in your application. You can try to reproduce with this template https://github.com/rails/rails/blob/master/guides/bug_report_templates/active_record_master.rb?

**Comment by valterbarros** [comment]
@rafaelfranca Oh man, I solve the problem with this slow query today, the problem was scoped query this verifies many times for **"empresas_id" = 44093`**, I removed this and works very well. Thanks

- `INNER JOIN "fvs" ON "fvs"."id" = "fvs_preenchimento"."fvs_id" AND "fvs"."empresas_id" = 44093`

- `INNER JOIN "atividade" ON "atividade"."id" = "fvs_preenchimento"."atividade_id" AND "atividade"."empresas_id" = 44093`

- `INNER JOIN "servicos" ON "servicos"."id" = "atividade"."servicos_id" AND "servicos"."empresas_id" = 44093`

- `INNER JOIN "obras" ON "obras"."id" = "local"."obras_id" AND "obras"."empresas_id" = 44093`

**Comment by rafaelfranca** [comment]
Glad to hear it.
