### ISSUE TITLE
present? called on activerecord record does not return true

### ISSUE THREAD

**Issue by richardrails** [rails/rails#30983]
### Expected behavior
User.create(name: 'John') # returns true
User.first.present? #returns true in older version of rails

### Actual behavior
User.create(name: 'John') # returns true
User.first.present? #returns FALSE

### System configuration
**Rails version**: 5.1.4

**Ruby version**: 2.3.5

**Comment by ChrisBr** [comment]
Hi @richardrails,

I wasn't able to reproduce this one. Could you please have a look at my Gist: https://gist.github.com/ChrisBr/73852e2b66a8cb11e08b779b782c8a9b

I used sqlite to reproduce it, what DB do you use?
Does ``User.first`` return the first user or does it already return ``nil``?

Thanks

**Comment by richardrails** [comment]
Hi, I use Postgresql db, this gem:
gem 'pg', '~> 0.18' # currently 0.21.0

User.first really returns existed user, but when i call present? on this user, it returns false. 
look: https://pasteboard.co/GQFOJPi.png

**Comment by ChrisBr** [comment]
Hi @richardrails,
could you please try this again with my gist (but adapt the database before) or in a new rails application to make sure that this is really a rails problem and not a problem with one of your gems.
Thanks

**Comment by richardrails** [comment]
your gist works. It also works on my Postgre DB, also on MySQL DB. Maybe really another gem rewrites the present? method... damn. I have more than 150 gems and dependencies, it is impossible to find it.

**Comment by matthewd** [comment]
Try `User.first.method(:present?).source_location`, and/or copying part/all of your full gem list into the gist.

Either way, it doesn't sound like a Rails issue, so I'll give this a close.

**Comment by richardrails** [comment]
Aaah, it gets the result:
["/home/rf/.rvm/gems/ruby-2.3.5/gems/activerecord-5.1.4/lib/active_record/enum.rb", 190]

so IT IS the activerecord bug? In other project, it returns another method in another class:
[".../2.3.0/gems/activesupport-5.0.0.1/lib/active_support/core_ext/object/blank.rb", 21]

**Comment by ChrisBr** [comment]
So it seems like your User.first returns an Enum object instead of a User object. Still it is most likely a sideeffect of one of your gems. From your screenshot I see that you use several gems which extend ActiveRecord (e.g. ransack, kaminari), so I would try to look into that. Maybe the Enum type is already a hin.

**Comment by rafaelfranca** [comment]
Do you have an enum in your model where one of the status is `present`?

**Comment by richardrails** [comment]
yes, I have it in my user.rb model:
enum study_type: {daily: 0, present: 1, distance: 2}

so this is it?
