### ISSUE TITLE
extensions added postgresql schemas are not properly save it into the schema.rb file

### ISSUE THREAD

**Issue by degzcs** [rails/rails#30990]
### Steps to reproduce
1. create a migration to add an extension 
for example:

```ruby
class EnableUuidExtension < ActiveRecord::Migration[5.1]
  def change
    #enable_extension 'pgcrypto'
    exec_query("CREATE SCHEMA IF NOT EXISTS shared_extensions;")
    exec_query("CREATE EXTENSION IF NOT EXISTS plpgsql SCHEMA shared_extensions;")
    exec_query("CREATE EXTENSION IF NOT EXISTS pgcrypto SCHEMA shared_extensions;")
  end
end
```
2. run migration

```
$ rake db:migrate
```
3. review the schema.rb file

```ruby
...
enable_extension "plpgsql"
enable_extension "pgcrypto"
...
```
but if someone load the schema.rb ( for example ` load "db/schema.rb" `) it the extension is not created in the correct postgres schema, because method run the next command:

``` 
CREATE EXTENSION IF NOT EXISTS "plpgsql"
CREATE EXTENSION IF NOT EXISTS "pgcrypto"

``` 
(Guidelines for creating a bug report are [available
here](http://guides.rubyonrails.org/contributing_to_ruby_on_rails.html#creating-a-bug-report))

### Expected behavior
Tell us what should happen

It should create the extensions in the correct Postgres schema (in my example in `shared_extensions` schema) 

### Actual behavior
Tell us what happens instead

It created the extensions in the current schema used, in most of the cases is `public`. But if you are using a different schema and run the migration for the first time these extensions are installed on that schema.

### System configuration
**Rails version**:
5.4.1
**Ruby version**:
2.4.1

I've created a possible solution that is working like a charm for my projects. If you think that it is  the correct one, I can start the process of creating the test and all things needed to do the pull request. The solution is [here](https://github.com/degzcs/rails/tree/extensions_with_schemas_fix) in the `extensions_with_schemas_fix` branch. You can see my last 2 commits.

Cheers!

**Comment by rafaelfranca** [comment]
schema.rb file doesn't support postgresql schema. If you need postgresql specific features use the structure.sql format. Thank you for the issue.

**Comment by degzcs** [comment]
Gotcha!!! Many thanks for your answer.
Cheers!
