### ISSUE TITLE
Ruby On Rails - When play video. it shows no pictures only audio can be heard why is that?

### ISSUE THREAD

**Issue by sumitsinghnaruka** [rails/rails#30992]
### Steps to reproduce

When playing a video on ruby on rails website, every time only audio play. It does'nt play video. Current i am using ffmpeg software. it's work on local system but not working on live server (Hostgrator).

### System configuration
**Rails version**: Rails 5.1.3

**Ruby version**: Ruby 2.4.0

**Comment by rafaelfranca** [comment]
Thank you for the issues. The videos are hosted in youtube so we don't have any control on how clients will play it. Also this repository is for issues in the framework, the website is outside of the scope of this repository.
