### ISSUE TITLE
ActiveSupport::Inflector.parameterize differs from doc because of special dash and underscore behavior

### ISSUE THREAD

**Issue by peagha** [rails/rails#31008]
### Steps to reproduce
Direct call to `ActiveSupport::Inflector.parameterize` or `String#parameterize`

### Expected behavior
Parameterize should replace any group of nonalphanumeric chars with the separator.
Example [from the documentation](http://api.rubyonrails.org/classes/ActiveSupport/Inflector.html#method-i-parameterize):
```ruby
ActiveSupport::Inflector.parameterize("^trés|Jolie-- ", separator: '_')
=> "tres_jolie"
```
Using the default separator (`-`):
```ruby
ActiveSupport::Inflector.parameterize('aa______b')
=> "aa-b"
```
### Actual behavior
Running this code on the latest Rails version doesn't replace dashes:
```ruby
ActiveSupport::Inflector.parameterize("^trés|Jolie-- ", separator: '_')
=> "tres_jolie--"
```
It also doesn't replace underscores when using the default separator (`-`):
```ruby
ActiveSupport::Inflector.parameterize('aa______b')
=> "aa______b"
```

### More info
`parameterize` always had special behavior for dashes and underscores, [there are even tests for that](https://github.com/rails/rails/blob/8479b79a0a4dad21a36e69a4502ff7414c250949/activesupport/test/inflector_test_cases.rb#L212-L222). It removes all special chars except for dashes and underscores. This behavior is present since Rails 4.

Technically the doc should be updated to explain this special case, but IMO the special case should be removed - it is counter-intuitive and doesn't seem to be useful.

### System configuration
**Rails version**:
5.1.4
**Ruby version**:
2.4.2p198

**Comment by peagha** [comment]
I can fix this issue! 😄 
But there is some info I need:
- Is it desirable to remove this behavior?
- What docs should be updated?

**Comment by PHedkvist** [comment]
To me its seems like using another separator than the default one should not remove the default separator "-" in the string. I can reproduce your example from the documentation using "^trés|Jolie-- ".

There is a testcase in 

> rails/activesupport/test/inflector_test.rb

which runs tests taken from the hash StringToParameterizeWithUnderscore in 

> rails/activesupport/test/inflector_test_cases.rb
Add "^trés|Jolie-- "                      => "tres_jolie--" to StringToParameterizeWithUnderscore will give you.

```
Failure:
InflectorTest#test_parameterize_with_custom_separator [test/inflector_test.rb:297]:
Expected: "tres_jolie"
  Actual: "tres_jolie--"
```
I think this could be an issue with the documentation and not the code.

**Comment by rafaelfranca** [comment]
Yes. We can't change the code since there are people already relying on that behavior, only the doc can be updated. Could you open a PR?

**Comment by peagha** [comment]
@rafaelfranca I understand! Any chance this is modified in a future release? It seems more like a legacy behavior; I can't think of a scenario where preserving dashes and underscores is desirable.

**Comment by rafaelfranca** [comment]
This kind of behavior is tricky to change even in a major release since we can't easily deprecate. Let say you have an application with the following code:

```
def create
  Post.create!(slug: params[:name].parameterize)
end

def show
  Post.find_by(slug: params[:id].parameterize)
end
```

And the name ends with `--`. If the post was created in Rails 5.1, the slug in the database will contain the `--`. If we change this behavior in Rails 6.0 the `show` action will not be able to find that post based on the slug generated by the name.

Of course this case is theoretical and my example is really bad, but since we can't deprecate and since there is a possibility of the result of the call of `parameterize` being in the database changing this will be a major backward compatibility breaking.
