### ISSUE TITLE
Any more information available regarding Active Storage JavaScript events?

### ISSUE THREAD

**Issue by shairyar** [rails/rails#31015]
Hello,

I am reading the Active Storage documentation available [here](https://github.com/rails/rails/tree/master/activestorage#direct-upload-javascript-events) and I am trying to find out how to display a progress bar. Just to test I added the following code inside my application.js

The image gets uploaded on amazon just fine but I see nothing in browser's console

```
	addEventListener("direct-upload:initialize", doSomething, false);

	function doSomething(e) {
		alert("Event is called: " + e.type);
	}
```

I also tried but I do not see anything in console.

```
document.getElementById("image_form").addEventListener("direct-upload:initialize", function() {
  console.log('direct-uploads:initialize')
});

document.getElementById("image_form").addEventListener("direct-uploads:end", function() {
  console.log('direct-uploads:start')
});
```

I would like to know how to make use of the events available? I just want to console something when the event fires?

**Comment by rafaelfranca** [comment]
Please use the mailing list or StackOverflow for questions/help, where a wider community will be able to help you. We reserve the issues tracker for issues only.
