### ISSUE TITLE
Dots are not accepted in routing path even when format: false is specified on Routing

### ISSUE THREAD

**Issue by aeroastro** [rails/rails#31032]
### Steps to reproduce

Add the following code on your routes.rb

```ruby
Rails.application.routes.draw do
  scope format: false do
    resources :tags
  end
end
```

Then access as follows:

```
curl http://localhost:3000/tags/v1.2
```

### Expected behavior

Return success resource like:

```json
{
  "tag": "v1.2.0",
  "description": "foo"
}
```

The reason behind this is the document below. When we specify `format: false`, there seems to be no need to reject dots, and specifying `constraints: { id: /[^/]+/ }` to all the resources seems redundant.

```
TIP: By default, dynamic segments don't accept dots - this is because the dot is used as a separator for formatted routes. If you need to use a dot within a dynamic segment, add a constraint that overrides this – for example, id: /[^\/]+/ allows anything except a slash.
```

https://github.com/rails/rails/blob/5aa5e35cf948b430538152024495583e9defe3af/guides/source/routing.md#dynamic-segments

### Actual behavior

```
No route matches [GET] "/v1/tags/v1.2"
```

### System configuration

**Rails version**:
4.2.9

**Ruby version**:
ruby 2.3.1p112

I am willing to make some Pull Requests to resolve this issue.

**Comment by gwincr11** [comment]
Does this work?
```
Rails.application.routes.draw do
  scope format: false do
    resources :tags, constraints: { id: /.+/ }
  end
end
```

**Comment by aeroastro** [comment]
Thank you for the comment. 🐱 
Yes. As I explained above, it works as a workaround.

However, if you build a large API application, say, an application with over 100 resources, specifying constraints on all the resources is a little bit redundant. In light of the reason why default regular expression does not accept dots, IMHO, it is natural to accept dots when `format: false` is specified.

If it is O.K. to fix this issue, I am willing to try fixing it.

**Comment by matthewd** [comment]
I'm concerned that it could break things for everyone currently using `format: false` if we change what their path segments match. It seems clearer to maintain consistent rules: that `.` and `/` are both separator characters by default, and can only be matched when explicitly requested.

**Comment by aeroastro** [comment]
Thanks for the comment. 🐱 

I'm also concerned that changing the default behavior could potentially break the codes which depend on default `.` and `/` rules. However, the effect is limited. More specifically, path parameters with dots, which are now rejected as `ActionController::RoutingError`, would be passed to controllers. IMHO, there are little dot-sensitive applications with `format: false` if their architectures are resource-oriented.

On the other hand, I also think it is important to maintain consistent rules in the codes especially on Rails, where Convention over Configuration is thought highly of.

If we give priority to consistent `.` and `/` rules. I would like to improve the usability of routing by followings. Is it possible?

1. Explicitly document that `.` and `/` are excluded regardless of `format` option.
2. Introduce routing option to override default `.` and `/` rules so that repetitive constraint definitions could be avoided.

**Comment by pixeltrix** [comment]
@aeroastro if you're worried about putting `constraints: { id: /.+/ }` on all your `resources` then you should just use a `scope`, e.g:

``` ruby
scope format: false, constraints: { id: %r{[^/]+} } do
  resources :posts do
    resources :comments
  end
end
```

The constraints should be correctly applied even on the nested ids since [we have a test for that behaviour][1].

I'm happy to take a documentation patch that makes the fact that default separators don't change with `format: false` clearer, but I don't think we need another routing option given that your concern over repetitive declarations is easily addressed.

[1]: https://github.com/rails/rails/blob/master/actionpack/test/dispatch/routing_test.rb#L2560-L2601

**Comment by aeroastro** [comment]
@pixeltrix 
Thank you for your feedback. I will make a documentation patch.

On the other hand, unfortunately, I have already tried using `constraints: { id: /.+/ }` on `scope`, and found out it does not address the issue.
This is because we are using `:param` option in routing. Writing all the params at top level `scope` does not resolve the redundancy and rather increases the complexity, e.g.:

```ruby
# If we have 3 kinds of param
scope format: false, constraints: { id: /.+/, name: /.+/, encrypted_id: /.+/ } do
  resources :posts
  resources :players, param: :name do
    resources :tickets, param: :encrypted_id
  end
end
```

If we can write as followings, the redundant problem will be addressed.

```ruby
scope format: false, constraints: { segment_format: /.+/ } do
end
```

**Comment by pixeltrix** [comment]
@aeroastro I always thought adding the `:param` option was a bad idea 😃 

Surely you can just add the overridden param name constraints on the individual resources? How many `:param` options are we talking about here?
