### ISSUE TITLE
All the activerecord learn more links are defunct

### ISSUE THREAD

**Issue by d-m-u** [rails/rails#31033]
### Steps to reproduce
Go to https://github.com/rails/rails/tree/master/activerecord and click on learn more links.

### Expected behavior
Links on https://github.com/rails/rails/tree/master/activerecord should work. 

### Actual behavior
Get 404s.

**Comment by GeniusStorm** [comment]
Do we know where exactly the learn more links should be pointed to ? I can create a quick PR to get them fixed.

**Comment by d-m-u** [comment]
That's just the thing, would've opened a PR if I'd known where to link to. Not a clue, sorry!

**Comment by georgeclaghorn** [comment]
See https://github.com/rails/rails/issues/28608#issuecomment-290277451.
