### ISSUE TITLE
Action controller load hooks getting executed twice

### ISSUE THREAD

**Issue by redtachyons** [rails/rails#31041]
This is a followup of a merit gem issue [here](https://github.com/merit-gem/merit/issues/173) . Issue is Action controller load hooks get executed twice so that re-initialization of the constant giving the warning message

### Steps to reproduce
Executable script to reproduce the issue
https://gist.github.com/redtachyons/568e0f79804d80f90de12f73353a86a2

### Expected behaviour
Load hooks should not be loaded twice

### Actual behaviour
Load hooks gets loaded twice

### System configuration
**Rails version**: 5.1.4

**Ruby version**: 2.4.2

**Comment by redtachyons** [comment]
Copying the comment from original [issue](https://github.com/merit-gem/merit/issues/173#issuecomment-340967251)

> After digging more I found the cause, rails calls ActiveSupport.run_load_hooks(:action_controller, self) From two places, one from ActionController::Base and other from ActionController::API, If your app or the gems you use load both, then action_controller load callback will load twice
> 
>     https://github.com/rails/rails/blob/5-1-stable/actionpack/lib/action_controller/base.rb#L271
> 
>     https://github.com/rails/rails/blob/5-1-stable/actionpack/lib/action_controller/api.rb#L145
>

**Comment by gwincr11** [comment]
I am going to go out on a limb and say that is intentional, as some apps may only use one or the other (API, or Normal) controllers. Could you tie to an alternate event? Could you attach to either the api, or the base event?

https://github.com/rails/rails/blob/5.1.3/actionpack/lib/action_controller/base.rb#L270
or
https://github.com/rails/rails/blob/5.1.3/actionpack/lib/action_controller/api.rb#L144

**Comment by redtachyons** [comment]
@gwincr11 Thanks, that makes sense, But I think the current behaviour of running callback twice If I want to add an onload event to either type of the controller is not a good user experience 

@rafaelfranca Would like to know your thoughts before closing the issue

**Comment by rafaelfranca** [comment]
We have now a [`run_once:` option on on_load](https://github.com/rails/rails/blob/5-1-stable/actionpack/lib/action_controller/railtie.rb#L25) hooks to make sure you can run the hook only once. But you can't use that option if you expect to have access to both type of controller.

Let me know if that works for you.

**Comment by redtachyons** [comment]
Thanks, @rafaelfranca, It worked 👍
