### ISSUE TITLE
rails new myapp --with-rspec

### ISSUE THREAD

**Issue by taw** [rails/rails#31044]
Using RSpec with Rails is extremely popular combination (numbers on [this](https://rubygems.org/gems/rails) vs [this](https://rubygems.org/gems/rspec-rails) suggest about 30% of all Rails project use RSpec, not hard data but sounds like decent ballpark figure).

Right now it's a multistep process to setup:

* google instructions in case you forgot exact commands since you last did it

    $ rails new myapp -T
    $ cd myapp

*  manually edit Gemfile putting `gem "rspec-rails"` in proper group

    $ bundle install
    $ bundle exec rails g rspec:install

This really deserves to be simplified into something like `rails new myapp --with-rspec`, or `rails new myapp --test=rspec` or something like that, analogously to how database and webpack options are handled.

It's sort of minor inconvenience per use, but it adds up, and Rails one command setup is a big advantage over other frameworks.

Similar argument could be made for other popular variants of Rails setup, if there are any.

**Comment by rafaelfranca** [comment]
Webpacker is an official Rails project so it has hight priority, and ORMs you can't exchange them when generating the app, you can only disable Active Record. The ORM option is to make possible to during other generators call like: `rails generate model foo` the ORM is used. There is a option for a test framework that does the same thing. This is why `rails generate model foo` when you are using RSpec generates RSpec files. This is as far as we are going to support multiple drivers. We are not going to change the Rails install generator to take drivers options.

Thank you for the issue.
