### ISSUE TITLE
Select(nil) and select(false) don't chain with more selects

### ISSUE THREAD

**Issue by octavpo** [rails/rails#31059]
### Steps to reproduce

Both `select(nil)` and `select(false)` work fine by themselves or chained with other query methods (in the sense that they're just ignored):
```
> User.select(nil).to_sql
 => "SELECT `users`.* FROM `users`" 
```
```
> User.select(false).where(username: 'foo').to_sql
 => "SELECT `users`.* FROM `users` WHERE `users`.`username` = 'foo'"
```
But they give an error when chained with another select:
```
> User.select(nil).select(:username).to_sql
Arel::Visitors::UnsupportedVisitError: Unsupported argument type: NilClass. Construct an Arel node instead.
```
This is inconsistent with the behavior of other query methods, like `joins` or `where`, which work fine with a similar pattern. 

The pattern is very useful for chaining conditional selects, like:
```
User.select(test && :full_name).select(:username)
```
This works fine if test is not false but fails with the above error if it's false.

### Expected behavior
```
> User.select(nil).select(:username).to_sql
=> "SELECT `users`.`username` FROM `users`"
```

### Actual behavior
```
> User.select(nil).select(:username).to_sql
Arel::Visitors::UnsupportedVisitError: Unsupported argument type: NilClass. Construct an Arel node instead.
```

### System configuration
**Rails version**: 5.1.4

**Ruby version**: 2.4.2

**Comment by mohsen-alizadeh** [comment]
I've fixed it. I'm preparing PR

**Comment by octavpo** [comment]
Has the PR been approved?

**Comment by matthewd** [comment]
@octavpo  merged; thanks for the reminder :+1:
