### ISSUE TITLE
HasManyThroughOrderError when redefining association in a subclass

### ISSUE THREAD

**Issue by skyfmmf** [rails/rails#31068]
### Steps to reproduce
I do have two classes called Foo and Bar, Bar being a subclass of Foo, with some associations defined for them. The critical point is that I am using a `has_many :through` association in a parent class and I try to redefine the association in a subclass to go through an other class than I used in the parent one. This is my stripped down example:

```ruby
class Foo < ApplicationRecord
  has_many :foo_refs
  has_many :targets, :through => :foo_refs
end
```

```ruby
class Bar < Foo
  has_many :bar_refs
  has_many :targets, :through => :bar_refs
end
```

### Expected behavior
I expect things like `Bar.first.targets` to be a working association in this setting.

### Actual behavior
Instead I'm getting this error: `ActiveRecord::HasManyThroughOrderError: Cannot have a has_many :through association 'Bar#targets' which goes through 'Bar#bar_refs' before the through association is defined.`

I think that the error is in `active_record/reflection.rb` in `add_reflection` (line 35): the new defined associations are merged into the existing ones. That leads to a wrong position in the hash for the redefined association what will then fail in line 943. As I do not have the overview over the whole Rails stack I did not try to fix it myself. 

### System configuration
**Rails version**: `Rails 5.1.4`
**Ruby version**: `ruby 2.3.3p222 (2016-11-21) [x86_64-linux-gnu]` (Tested on Ubuntu 17.04)

**Comment by skyfmmf** [comment]
To make this issue more clear and to allow reproduction I've made a test case using one of your templates. It works with version 4.2.7 but fails with 5.1.4. 

You can find it here: https://gist.github.com/skyfmmf/71ed703bceb1d2042dc6dce572435642

**Comment by MarconiVini** [comment]
I tested with ruby ruby 2.4.0p0 and I've being able to reproduce. I never contributed before but I'll try to follow and help somehow.
