### ISSUE TITLE
ActiveStorage download with block not working for S3 or Azure Storage

### ISSUE THREAD

**Issue by dwightwatson** [rails/rails#31073]
I think I've identified an issue that affects the download method for the Azure Storage and S3 ActiveStorage services. I first became aware of it when `ActiveStorage::AnalyzeJob` was failing because it couldn't download the file, but I've found the same issue occurs when you try to download a preview (or download with a block). I discovered the issue with S3 but having a look at the code I believe it would affect Azure Storage too.

This is the error I'm seeing:

```
undefined local variable or method `block' for #<ActiveStorage::Service::S3Service:0x00000000069ebbb8>
```

And here is what I believe to be the [relevant block of code](https://github.com/rails/rails/blob/master/activestorage/lib/active_storage/service/s3_service.rb#L29-L39):

```
    def download(key)
      if block_given?
        instrument :streaming_download, key do
          stream(key, &block)
        end
      else
        instrument :download, key do
          object_for(key).get.body.read.force_encoding(Encoding::BINARY)
        end
      end
    end
```

If a block is given it calls `instrument` and then attempts to use the block inside the block passed, but I suspect it's getting confused and not getting the block from the parent method call. 

### Steps to reproduce
Attempt to preview an ActiveStorage attachment or download with a block.

```
blob = ActiveStorage::Blob.first
blob.preview(resize: '100x100').processed # error
blob.download { |random_block| puts 'Random block } # error
```

### Expected behavior
The `download` method should work with a block and allow the `ActiveStorage::AnalyzeJob` and previews to work for the Azure Storage and S3 drivers.

### Actual behavior
An `undefined local variable or method 'block' for #<ActiveStorage::Service::S3Service:0x00000000069ebbb8>` error is raised.

### System configuration
**Rails version**: Rails 5.2.0.alpha

**Ruby version**: ruby 2.4.2p198

**Comment by georgeclaghorn** [comment]
Thanks for the report, @dwightwatson!
