### ISSUE TITLE
Belongs to relation does not accept dependent nullify

### ISSUE THREAD

**Issue by dsantosmerino** [rails/rails#31070]
### Steps to reproduce

```ruby
class Flat < ApplicationRecord
  belongs_to :location, dependent: :nullify
end

class Location < ApplicationRecord
  has_many :flats
end
```

### Expected behavior
Since the relation can include also an `optional: true`, I expected that I can nullify after destroy the related entity. Does it make sense?

### Actual behavior
Raises an `ArgumentError`
> The :dependent option must be one of [:destroy, :delete], but is :nullify (ArgumentError)

Related code: https://github.com/rails/rails/blob/6f0729b604dca46d4198f74a08eb836b2e8b5492/activerecord/lib/active_record/associations/builder/belongs_to.rb#L13-L15

### System configuration
**Rails version**: 5.0.0.1

**Ruby version**: 2.3.1

**Comment by rafaelfranca** [comment]
Thank you for the issue but we don't take feature requests in the issue tracker. It is deliberate that we don't support `nullify` because we want to avoid orphan objects. If you think it makes sense to support it please open a PR adding this option.
