### ISSUE TITLE
attribute_will_change! in after_save callback produces deprecation warning

### ISSUE THREAD

**Issue by accessd** [rails/rails#31087]
### Steps to reproduce

Just call `attribute_will_change!` in after_save callback. It relates https://github.com/carrierwaveuploader/carrierwave/issues/2181.

I have this backtrace with deprecation warning:

```
DEPRECATION WARNING: The behavior of `attribute_changed?` inside of after callbacks will be changing in the next version of Rails. The new return value will reflect the behavior of calling the method after `save` returned (e.g. the opposite of what it returns now). Tomaintain the current behavior, use `saved_change_to_attribute?` instead. (called from assign_thumbnail! at /Users/accessd/projects/hb_babysnap_backend/app/models/movie.rb:104)
/Users/accessd/projects/hb_babysnap_backend/vendor/bundle/gems/activerecord-5.1.4/lib/active_record/attribute_methods/dirty.rb:225:in `attribute_changed?'
  /Users/accessd/projects/hb_babysnap_backend/vendor/bundle/gems/activemodel-5.1.4/lib/active_model/dirty.rb:239:in `attribute_will_change!'
  /Users/accessd/projects/hb_babysnap_backend/vendor/bundle/gems/activerecord-5.1.4/lib/active_record/attribute_methods/dirty.rb:277:in `attribute_will_change!'
  /Users/accessd/projects/hb_babysnap_backend/vendor/bundle/gems/activemodel-5.1.4/lib/active_model/attribute_methods.rb:384:in `thumb_will_change!'
  /Users/accessd/projects/hb_babysnap_backend/vendor/bundle/gems/carrierwave-1.2.1/lib/carrierwave/orm/activerecord.rb:67:in `thumb='
  /Users/accessd/projects/hb_babysnap_backend/app/models/movie.rb:104:in `assign_thumbnail!'
```

I suppose it's a problem with calling `attribute_changed?` from `ActiveModel::Dirty` that calls overriden `attribute_changed?` from `ActiveRecord::AttributeMethods::Dirty`.
Maybe method `attribute_will_change!` should looks like:

```
        def attribute_will_change!(attr_name)
          return if saved_change_to_attribute?(attr)
          super
          if self.class.has_attribute?(attr_name)
            mutations_from_database.force_change(attr_name)
          else
            ActiveSupport::Deprecation.warn(<<-EOW.squish)
              #{attr_name} is not an attribute known to Active Record.
              This behavior is deprecated and will be removed in the next
              version of Rails. If you'd like #{attr_name} to be managed
              by Active Record, add `attribute :#{attr_name} to your class.
            EOW
            mutations_from_database.deprecated_force_change(attr_name)
          end
        end
```

### Expected behavior
There should be no deprecation warning

### Actual behavior
There's deprecation warning

### System configuration
**Rails version**: 5.1.4

**Ruby version**: 2.4.0

**Comment by rafaelfranca** [comment]
@sgrif could you take a look?

**Comment by accessd** [comment]
@sgrif ping

**Comment by kbleabres** [comment]
This happens to me, too. Trying to change/save a new value for an attribute also declared as `store_accessor` generates the deprecation warning

> DEPRECATION WARNING: The behavior of `attribute_changed?` inside of after callbacks will be changing in the next version of Rails. The new return value will reflect the behavior of calling the method after `save` returned (e.g. the opposite of what it returns now). To maintain the current behavior, use `saved_change_to_attribute?` instead

After investigating, this line here is what (I think) causes the deprecation warning.
https://github.com/rails/rails/blob/375a4143cf5caeb6159b338be824903edfd62836/activerecord/lib/active_record/store.rb#L150

**Comment by sgrif** [comment]
My gut is that `attribute_changed!` in an after callback *should* be producing a deprecation warning, and this is just the wrong one. I will look more closely though.

**Comment by domangi** [comment]
The deprecation warning occurs because inside activemodel/lib/active_model/dirty.rb the method attribute_changed? is called, which will change behavior in the next release.

@sgrif Not quit sure if it makes sense, but can't we just replace the deprecated attribute_changed? method with saved_change_to_attribute?, like the warning message suggests?

I already sent a pull request for this https://github.com/rails/rails/pull/32563
