### ISSUE TITLE
ActiveModel::Error add JSON API code property to errors

### ISSUE THREAD

**Issue by arefaslani** [rails/rails#31080]
I have a JSON API built with Rails API. I'm following [JSON API spec](http://jsonapi.org/) for creating responses for my API. How could I add `code` property to errors as [described in the spec](http://jsonapi.org/format/#errors)? I use ActiveModel::Errors#add method to add an error to the object.

**Comment by al2o3cr** [comment]
@arefaslani A good place to start would be to look at how other JSON-API-compliant code handles this; for instance, [here](https://github.com/cerebris/jsonapi-resources/blob/31b305eb9b72465f9d881130e02543808420f4f4/lib/jsonapi/resource.rb#L191) is where jsonapi-resources does it.

However, I don't think this is a question for this issue tracker - this is reserved for bug reports & Pos on the core framework, not help or feature requests.
