### ISSUE TITLE
`select` form helpers with `required: true` generate a blank option even when one is already present

### ISSUE THREAD

**Issue by octavpo** [rails/rails#31083]
### Steps to reproduce

It seems `select` decides on whether to add a blank option or not only by looking at whether an `include_blank` or a `prompt` option is provided or not (besides if a `required: true` is present). It doesn't look to see if a blank option is already present in the given options. In my case I generate the options using my own helpers, which already add a blank option with a text selected based on other parameters. This behavior is forcing me to get that part out of the helpers and into the `include_blank`, making the code more verbose (since the helpers are used in many places).

### Expected behavior

`select` & co should not generate a blank option if the first option in the given list is already blank.

### Actual behavior

It generates a blank option even when one is already present.

### System configuration
**Rails version**: 5.1.4

**Ruby version**: 2.4.2

**Comment by kinnrot** [comment]
@octavpo why not putting `include_blank: false` in your code?

**Comment by octavpo** [comment]
First because I just tried it and it doesn't work, I get an error saying:
```
ActionView::Template::Error (include_blank cannot be false for a required field.):
```

But even if it worked it wouldn't be a good solution for me for the same reason I didn't use `include_blank` in the first place to actually include the blank option, it wouldn't be DRY in my case.

My main point is that this should really be considered a bug. It's behavior that's happening completely behind the user's back, it's not documented anywhere, the documentation for `include_blank` suggests that if you're not using it nothing is included. So then when you get it, the first reaction is 'Where the hack did that come from? Is it the browser, is it Rails?' And you need to dig a while, read all relevant tickets, to figure out what happens. So it's a case where, in trying to help less knowledgeable users, Rails gets in the way of users who know what they're doing. It should either just not include anything and let the user deal with the issue, or it should be smart enough to only include the blank option when actually needed.

**Comment by kinnrot** [comment]
Ok so what you are saying is
"When using required: true , the blank is always added "
And it's not ok.

Right ?

**Comment by octavpo** [comment]
Well, it's not added if an `include_blank` or a `prompt` option is already present. But it is added when these options are missing, but a blank item is already present in the list of choices, so you end up with two of them. I'm saying it should check for that case too, so only add a blank choice if those options are missing and the first choice is not already blank. 

HTML standard specifically says that the first choice needs to be blank in this case, so Rails only needs to check the first one, not the whole list. Of course this choice could take one of several forms that Rails helpers accept, so the test would probably need to deal with all of them to be thorough. I'm only using array pairs, so for me it's enough if it checks that form.

**Comment by kinnrot** [comment]
@octavpo  can you share some code?

**Comment by octavpo** [comment]
So no chance of fixing this? I don't know what code you want from me.

**Comment by rafaelfranca** [comment]
You can either write a PR or at least be more explicit about what is your expected behavior writing some code example.

**Comment by SampsonCrowley** [comment]
I just ran into this and i found it quite shocking. I already have prompt: true set, yet you're FORCING me to also include a blank option. this doesn't feel like the rails way of doing things.

**Comment by SampsonCrowley** [comment]
I don't think this should be an error at all. I should have the option to leave out anything I want from the element

**Comment by GPrimola** [comment]
I just faced this and I was like :scream: 
@SampsonCrowley I totally agree with you! If I mark a field as required, what I mean is that I expect some value from it, therefore the `include_blank: false` it is kinda redundant. What I think could be an error is if I set a field as required and `include_blank:`**`true`**

The error that is happening is contradictory.

**Comment by kinnrot** [comment]
IMO - When setting a required field, it's ok to include a blank option,
otherwise, no need to set the field as required, cause first option will be
selected by default.

UX wise, if the first option is not the user default option, the blank
option should be present.


Chen Kinnrot
kinnrot@gmail.com

**Comment by GPrimola** [comment]
@kinnrot I'm trying really hard to see your point, for me it doesn't make any sense to force an option `include_blank: true` if I set the field as required.
In my understanding, to set the field as required means I expect a value from that field. I really don't want to enter in the discussion if blank (empty, null, undefined, etc) is some value.

Only to enforce my argument, I tryied to submit a form with a required select with blank selected, and browsers (Firefox and Chrome) prevented the form to be submitted, meaning that required needs a value other than blank.

Therefore I don't see any reason why in Rails a required field requires option `include_blank` to be true. UX wise as you have pointed, IMO `required` and `include_blank` should be related at all, so the UX would choose whatever he/she likes. But, if it would be for they to be related, IMO it would be for when `required` is set, `include_blank` should default to false, once that field needs a value other than blank (no value, null, ...)


// Giorgio Torres
torres.giorgio@gmail.com

**Comment by kinnrot** [comment]
Ok than answer the following question: what would you benefit from required
field without a blank option, how does it different from a field that is
not required without a blank option? It doesn't in the common case cause
first option which is not blank would be chosen by default, so maybe you
should just use required false with blank false also.

**Comment by GPrimola** [comment]
@kinnrot 

> Ok than answer the following question: what would you benefit from required field without a blank option, how does it different from a field that is not required without a blank option?

It doesn't differ at all.
I understand your point, what I mean is that I don't see why the option `required` is bound to `include_blank`.

IMO, it would be ok if I wanted an optional select with a blank option as much as a required select with/without the blank option. I don't think the framework should deal with this either way.

**Comment by octavpo** [comment]
The reason is that the HTML5 standard requires that required select tags have a blank option, and Rails is just trying to help with that, so you're not getting an error in HTML if you forget it.

The issue here is only that Rails' `select` helper is not smart enough about it. That is right now the helper forces you to add the blank option through the `include_blank` option. If instead you include a blank option in your list of options, select doesn't recognize it and adds a second blank option, so you end up with two. If you try to prevent the second one by specifying `include_blank: false`, you get an error. So all I was suggesting is that `select` checks the received option list and adds a blank option or gives you an error only if none is present.

**Comment by stan0612** [comment]
The pirate way : 
Remove required: true and add include_blank: false
If select have 2 options, there will be then only 2 choices to make... ;)
