### ISSUE TITLE
客户端断开网络，服务器无法检测客户端断开链接。

### ISSUE THREAD

**Issue by shadowyq** [rails/rails#31094]
### Steps to reproduce

(Guidelines for creating a bug report are [available
here](http://guides.rubyonrails.org/contributing_to_ruby_on_rails.html#creating-a-bug-report))

### Expected behavior
Tell us what should happen
客户端关闭网络后，服务器端无法检测客户端断开链接。当客户端重新打开网络的时候，服务器端打印了客户端断开链接的log.
### Actual behavior
Tell us what happens instead

### System configuration
**Rails version**:
5.1.3
**Ruby version**:
2.3.4p301

**Comment by rafaelfranca** [comment]
Thank you for the issue. Unfortunately we don't understand the language you used so we can't help you. If you want support please use English.

**Comment by Yuyue** [comment]
This issue want to report bug about client and server. I try to translate it as follows:
The server cannot get notice at the time of the client‘s network shutdown. However, the server can print out this disconnection log, when the client reopen his network.
