### ISSUE TITLE
Move away from Erubi(s)

### ISSUE THREAD

**Issue by toncid** [rails/rails#31108]
Hello,

Erubi maintainer claims that this bug will not be fixed: https://github.com/jeremyevans/erubi/issues/11

Rails should consider moving to ERB or allow other ERB renderers (not sure if it's possible now). 

There is no point in switching to Erubi if bugs, albeit rare, are not going to be fixed.

### Steps to reproduce

Render the following ERB block (from #18098):

```
    <div>
        <%%= Results: <%= 'first' %> | <%= 'second' %> | <%= 'third' %> %>
    </div>
```

### Expected behavior

Correct and consistent handling of nested ERB tags:

```
    <div>
        <%= Results: first | second | third %>
    </div>
```

### Actual behavior

Nested ERB tags are not resolved correctly:

```
    <div>
        <%= Results: <%= 'first' %> | second | third %>
    </div>
```

### System configuration

**Rails version**:
Any recent one (tested on 4.2.10).

**Ruby version**:
Any (tested on 2.3.5).

**Comment by rafaelfranca** [comment]
Thank you for the issue but we don't plan to moving away from Erubi.

> allow other ERB renderers (not sure if it's possible now).

That is already possible. `ActionView::Template::Handlers::ERB.erb_implementation = ::ERB`
