### ISSUE TITLE
Query with symbols doesn't accept keys from ActionController::Parameters

### ISSUE THREAD

**Issue by lfekson** [rails/rails#31103]
### Steps to reproduce
params = ActionController::Parameters.new({ :statuses => ['Something'] }).permit!
AModel.where(["status in (:statuses)", params]).to_sql

### Expected behavior
Output: "select * from a_table WHERE status in ('Something')"

### Actual behavior
Output: "select * from a_table WHERE status in (:statuses)"

### System configuration
**Rails version**:
5.0
**Ruby version**:
2.4.1

**Comment by pixeltrix** [comment]
@lfekson you need to pass a `Hash` so just add a `to_h` in your `where` arguments, e.g:

``` ruby
Model.where("status in (:statuses)", params.to_h)
```
