### ISSUE TITLE
rails secrets:edit returns "New secrets encrypted and saved." since 5.1.4

### ISSUE THREAD

**Issue by nanark** [rails/rails#31109]
I can't edit my secret file anymore.

```
EDITOR=vim rails secrets:edit
```

it used to work fine since my last update.
Now i get a "New secrets encrypted and saved." and nothing more.

![image](https://user-images.githubusercontent.com/581768/32626514-d5e96362-c58f-11e7-9671-2d8b85d5b689.png)

All my files are in place
```
-rw-r--r--  1 root root 1719 Nov  6 23:00 secrets.yml
-rw-r--r--  1 root root 1560 Nov  6 23:00 secrets.yml.enc
-rw-r--r--  1 root root   33 Nov  7 21:42 secrets.yml.key
```
And the server and the test work fine too.

**Comment by rafaelfranca** [comment]
cc @kaspth

**Comment by kaspth** [comment]
> since my last update.

What did you upgrade from and to? iirc, we changed the encryption scheme in a beta release prompting: https://gist.github.com/kaspth/bc37989c2f39a5642112f28b1d93f343 (which I think we linked from the changelog.)

I'll close for now. Let us know if there's more trouble. Thanks!

**Comment by nanark** [comment]
Hi, I got this:

```
root@2ce6de1399c1:/app# rails runner upgrade_encrypted_secrets.rb
Running via Spring preloader in process 326
Generating a new higher entropy encryption key in config/secrets.yml.key.
Rotate the encryption key now.
upgrade_encrypted_secrets.rb:9:in `final': wrong final block length (OpenSSL::Cipher::CipherError)
	from upgrade_encrypted_secrets.rb:9:in `decrypt'
	from /bundle/gems/railties-5.1.4/lib/rails/secrets.rb:59:in `read'
	from upgrade_encrypted_secrets.rb:16:in `<top (required)>'
	from /bundle/gems/railties-5.1.4/lib/rails/commands/runner/runner_command.rb:34:in `load'
	from /bundle/gems/railties-5.1.4/lib/rails/commands/runner/runner_command.rb:34:in `perform'
	from /bundle/gems/thor-0.20.0/lib/thor/command.rb:27:in `run'
	from /bundle/gems/thor-0.20.0/lib/thor/invocation.rb:126:in `invoke_command'
	from /bundle/gems/thor-0.20.0/lib/thor.rb:387:in `dispatch'
	from /bundle/gems/railties-5.1.4/lib/rails/command/base.rb:63:in `perform'
	from /bundle/gems/railties-5.1.4/lib/rails/command.rb:44:in `invoke'
	from /bundle/gems/railties-5.1.4/lib/rails/commands.rb:16:in `<top (required)>'
	from /bundle/gems/activesupport-5.1.4/lib/active_support/dependencies.rb:292:in `require'
	from /bundle/gems/activesupport-5.1.4/lib/active_support/dependencies.rb:292:in `block in require'
	from /bundle/gems/activesupport-5.1.4/lib/active_support/dependencies.rb:258:in `load_dependency'
	from /bundle/gems/activesupport-5.1.4/lib/active_support/dependencies.rb:292:in `require'
	from /app/bin
```

**Comment by kaspth** [comment]
It's possible there's a syntax error in the YAML and thus the file can't be deserialized properly.

The secrets code is all in here: https://github.com/rails/rails/blob/bb30f05f3858f97791f0e1530e625b7ea2c6c5e2/railties/lib/rails/secrets.rb#L44

Try manually decrypting the file, but then don't parse the YAML and see what happens. Otherwise you'll have to reproduce your error in a sample app.

We'll have a fix out to serialize/deserialize the YAML before saving in another release.

**Comment by nanark** [comment]
I decrypted the file successfully with `Rails::Secrets.decrypt` and decided to start all over again.
I removed the `secrets.yml*` and launched `bin/rails secrets:setup` again.

And I still have the same issue with fresh new files generated with Rails 5.1.4.
```
root@d88dce38e6b3:/app# EDITOR=vim bin/rails secrets:edit
New secrets encrypted and saved.
```
Nothing more happens.

(To answer your previous question, I was upgrading from Rails 5.1.3)

**Comment by kaspth** [comment]
I can't reproduce on a new Rails 5.1.4 app. The secrets editing keeps on trucking.

Can you reproduce it in a sample application?

**Comment by nanark** [comment]
Everything works fine with a new Rails app.
But I have 2 different apps (on Docker) with the same issue.

This is my Gemfile, do you see something wrong?
```
gem 'active_model_serializers', '~> 0.10.6'
gem 'activeadmin', '~> 1.0.0'
gem 'aws-sdk', '~> 2.3.0'
gem 'coffee-rails', '~> 4.2.2'
gem 'curb', '~> 0.9.4'
gem 'devise', '~> 4.3.0'
gem 'dotiw', '~> 4.0.0'
gem 'inherited_resources', '~> 1.7'
gem 'jbuilder', '~> 2.7'
gem 'jwt', '~> 2.1.0'
gem 'kaminari', '~> 1.1.1'
gem 'mandrill-api', '~> 1.0.53'
gem 'meta-tags', '~> 2.6.0'
gem 'mini_magick', '~> 4.8.0'
gem 'mysql2', '>= 0.3.18', '< 0.5'
gem 'nilify_blanks', '~> 1.2.0'
gem 'paperclip', '~> 5.1.0'
gem 'puma', '~> 3.10'
gem 'rack-cors', '~> 0.4.1'
gem 'rails', '~> 5.1.4'
gem 'redis', '~> 4.0.1'
gem 'redis-rails', '~> 5.0.1'
gem 'sass-rails', '~> 5.0'
gem 'sidekiq', '~> 5.0.5'
gem 'slim', '~> 3.0.7'
gem 'therubyracer', git: 'https://github.com/cowboyd/therubyracer.git'
gem 'turbolinks', '~> 5'
gem 'uglifier', '>= 1.3.0'

group :development, :test do
  gem 'better_errors'
  gem 'binding_of_caller'
  gem 'byebug', platform: :mri
  gem 'rspec'
  gem 'simplecov', :require => false
end

group :development do
  gem 'listen', '~> 3.0.5'
  gem 'spring'
  gem 'spring-watcher-listen', '~> 2.0.0'
  gem 'web-console', '>= 3.3.0'
end
```

**Comment by nanark** [comment]
The `bin/rails runner "puts Rails::Secrets.read"` command works perfectly too.

**Comment by nanark** [comment]
Ok I found the culprit.
For some reason vim wasn't working on Docker. Everything works fine now. Thanx for your time!

**Comment by kaspth** [comment]
Cool, glad you figured it out 👍
