### ISSUE TITLE
SystemStackError: stack level too deep when using where with created_by

### ISSUE THREAD

**Issue by heebj** [rails/rails#31110]
### Steps to reproduce
I have the following model:
```
class Comment < ApplicationRecord
	# associations
	#####################################
	belongs_to :entry
	belongs_to :created_by, :class_name => 'User', :foreign_key => :created_by

	# validations
	#####################################
	validates_presence_of :body
	validates_length_of :body, :within => 0..600

	validates_presence_of :entry_id
	validates_presence_of :created_by
end
```

I create a comment:
```
u = FactoryBot.create(:user)
c = Comment.create(body: 'Test', entry: FactoryBot.create(:entry), created_by: u)
```

And afterwards try to query the comment:
```
Comment.where(created_by: u).first
```

(Guidelines for creating a bug report are [available
here](http://guides.rubyonrails.org/contributing_to_ruby_on_rails.html#creating-a-bug-report))

### Expected behavior
I should get the created comment

### Actual behavior
I get a `SystemStackError: stack level too deep` instead.

However if I use the following query it works as expected:
```
Comment.where('created_by = ?', u.id).first
```

### System configuration
**Rails version**:
5.0.6

**Ruby version**:
2.4.2

**Comment by rafaelfranca** [comment]
Have you tested in Rails 5.1? 
Could you create a reproduction script with this template https://github.com/rails/rails/blob/master/guides/bug_report_templates/active_record_master.rb?

**Comment by heebj** [comment]
Not yet, I am still in the process of upgrading from 4.2 to 5.0. As soon as this is done I will try it with 5.1, probably tomorrow.

I will try to create a reproduction script as soon as possible.

**Comment by heebj** [comment]
I can reproduce it with this script:

```
# frozen_string_literal: true

gem "bundler", "< 1.16"

begin
  require "bundler/inline"
rescue LoadError => e
  $stderr.puts "Bundler version 1.10 or later is required. Please update your Bundler"
  raise e
end

gemfile(true) do
  source "https://rubygems.org"

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  gem "rails", '~> 5.0.0'
  #gem "arel", github: "rails/arel"
  gem "sqlite3"
end

require "active_record"
require "minitest/autorun"
require "logger"

# This connection will do for database-independent bug reports.
ActiveRecord::Base.establish_connection(adapter: "sqlite3", database: ":memory:")
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table "comments", force: :cascade do |t|
    t.integer  "created_by"
    t.datetime "created_at", null: false
    t.datetime "updated_at", null: false
  end

  create_table "users", force: :cascade do |t|
    t.string   "name",                      limit: 100, default: ""
  end
end

class User < ActiveRecord::Base
  has_many :comments, :foreign_key => :created_by
end

class Comment < ActiveRecord::Base
  belongs_to :created_by, :class_name => 'User', :foreign_key => :created_by
end

class BugTest < Minitest::Test
  def test_association_stuff
    user = User.create!(name: "Tester")
    Comment.create!(created_by: user)
    
    Comment.where(created_by: user.id).first
  end
end
```

I think the problem lies in the fact that the foreign_key and the association have the same name `created_by` which is kind of ugly.

The funny thing is that this code was working with Rails 4.2

**Comment by jsncmgs1** [comment]
> I think the problem lies in the fact that the foreign_key and the association have the same name created_by which is kind of ugly.

I played around with this a little bit, I'm pretty confident that's definitely the issue. If this is something rails wants to support, or provide a specific error message for, I'm happy to dig in further.

**Comment by matthewd** [comment]
I think it's definitely worth exploring what's involved in supporting it.

If it's nontrivial we might decide we don't care *that* much.. but if it used to work, it at least seems worth a try.

I don't specifically recall a conscious change to use `self.send(foreign_key_name)` over `self[foreign_key_name]` (which is what this sounds like it boils down to), but if we did, hopefully the surrounding history can shed some light.

**Comment by jsncmgs1** [comment]
That script passes when run against the `5-1-stable` branch.

**Comment by heebj** [comment]
Thanks for all your quick support!

I can confirm that it works with Rails 5.1.

**Comment by heebj** [comment]
Hi there. This issue pops up again in Rails 5.2

**Comment by cis-nidhi** [comment]
I have this code
 def save_participant(context_object, email)
    context_object.approval_set = @approval_set if @approval_set
    if context_object.class == SimDojo::EventParticipant
      context_object.is_new = true
    end
    
    **return add_errors(email, context_object) unless context_object.save**

    return unless @event&.is_sim_dojo?

    apply_scorer(context_object) if @scorer
    apply_approvers(context_object) if @approver_group_user
    apply_custom_fields(context_object) if @custom_field_values.present?
    apply_tags(context_object) if @tags_params[:tag_list].present?
  end

and I receive 
SystemStackError - stack level too deep:
on     **return add_errors(email, context_object) unless context_object.save** this line.

Please anyone can help me with this
