### ISSUE TITLE
Scope named records behaves inconsistently

### ISSUE THREAD

**Issue by nimish-mehta** [rails/rails#31120]
### Steps to reproduce
```ruby
begin
  require 'bundler/inline'
rescue LoadError => e
  $stderr.puts 'Bundler version 1.10 or later is required. Please update your Bundler'
  raise e
end

gemfile(true) do
  source 'https://rubygems.org'

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  # Activate the gem you are reporting the issue against.
  gem 'activerecord', "5.0.6"
  gem 'sqlite3'
  gem 'byebug'
end

require 'active_record'
require 'minitest/autorun'
require 'logger'

# Ensure backward compatibility with Minitest 4
Minitest::Test = MiniTest::Unit::TestCase unless defined?(Minitest::Test)

# This connection will do for database-independent bug reports.
ActiveRecord::Base.establish_connection(adapter: 'sqlite3', database: ':memory:')
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :posts, force: true do |t|
    t.string :name
    t.integer :category, default: 0
    t.integer :status, default: 0
  end
end

class Post < ActiveRecord::Base
  enum category: %i(other records)
  enum status: %i(in_review reviewed published)
end

class BugTest < Minitest::Test
  def test_chaining
    Post.destroy_all
    Post.create!(category: :other, status: :published)
    Post.create!(category: :records, status: :published)
    assert Post.published.records == Post.records.published
  end

  def test_scope
    Post.destroy_all
    Post.create!(category: :other, status: :published)
    p = Post.create!(category: :records, status: :published)
    assert Post.records == [p]
  end
end
```

### Expected behavior
```Post.records.published``` should be same as ```Post.published.records``` and calling records should not terminate the scope chaining. If it is not possible to create a valid scope named ```records``` Rails should raise ArgumentError that this is a dangerous method or not a valid scope name.

### Actual behavior
The method call records is handled by ActiveRecord_Relation object if it is called after calling a scope and immediately executes the query. Unless records is the called first, in which case it seems to be working properly.

This was working in previous version of Rails and seems to have been broken in Rails5.0

### System configuration
**Rails version**: 5.0.6

**Ruby version**: 2.4.1

**Comment by kinnrot** [comment]
Reproduced successfully.

The first call returns an `ActiveRecord::Relation`

This class has a method named `records` but not a method called `published` which makes things act strange.

Suggested solution will be to raise an error when trying to define a scope named same as a defined instance method of `ActiveRecord::Relation`

I think a change in `#valid_scope_name` is required add 
`Relation.instance_method(name)`

to the condition of valid scope name

**Comment by eugeneius** [comment]
As https://github.com/rails/rails/pull/31179 was merged, I think this can now be closed.
