### ISSUE TITLE
Active Storage: blob metadata is overwritten by analyzer

### ISSUE THREAD

**Issue by tbalthazar** [rails/rails#31138]
### Steps to reproduce

```ruby
class Payment < ActiveRecord::Base
  has_many_attached :archives
end

payment.archives.attach(
   io: File.open("./archive.zip"),
   filename: "archive.zip",
   content_type: "application/gzip",
   metadata: { foo: :bar }
)
```

### Expected behavior
Metadata should be there:
```ruby
Payment.first.archives.first.metadata # => {foo: :bar}
```

### Actual behavior
Metadata is overwritten:
```ruby
Payment.first.archives.first.metadata # => {"analyzed": true}
```

The [`AnalyzeJob`](https://github.com/rails/rails/blob/605484079d297d1ba6835628465be81f03c052ee/activestorage/app/models/active_storage/blob.rb#L259) will [`update`](https://github.com/rails/rails/blob/605484079d297d1ba6835628465be81f03c052ee/activestorage/app/models/active_storage/blob.rb#L252) the `metadata` with the [`metadata` from the `analyzer`](https://github.com/rails/rails/blob/605484079d297d1ba6835628465be81f03c052ee/activestorage/app/models/active_storage/blob.rb#L302). The default analyzer is the [`NullAnalyzer`](https://github.com/rails/rails/blob/605484079d297d1ba6835628465be81f03c052ee/activestorage/lib/active_storage/analyzer/null_analyzer.rb#L10) that just returns an empty `Hash`.

Would that make sense to return `blob.metadata || {}` there? (as well as in the `ImageAnalyzer` and `VideoAnalyzer` that could merge the metadata they fetch with the one from `blob.metadata`?)
Would you accept a PR for that?

### System configuration
**Rails version**: Rails master https://github.com/rails/rails/commit/8f2490b57f488ed60fc6e0a201ccd5e66811ab51

**Ruby version**: ruby 2.4.2p198 (2017-09-14 revision 59899) [x86_64-darwin16]

**Comment by georgeclaghorn** [comment]
We ought to merge the existing metadata with the metadata extracted by the analyzer in `ActiveStorage::Blob#analyze`.

**Comment by sparkhead95** [comment]
What's happening with this change @georgeclaghorn ?
I'm getting the same thing, and the workaround is getting tedious

**Comment by alexisvisco** [comment]
Same behavior here with the latest version of rails and active storage
