### ISSUE TITLE
System Test not filling in fields in chrome properly

### ISSUE THREAD

**Issue by PHedkvist** [rails/rails#31143]
### Steps to reproduce

First create test app, and scaffold..
```
bundle exec rails new ../system_testing --dev
rails g scaffold Post title:string body:text
bundle exec rails db:migrate
bundle exec bin/rails test:system

```
Default settings in `application_system_test_case.rb`

```
require "test_helper"

class ApplicationSystemTestCase < ActionDispatch::SystemTestCase
  driven_by :selenium, using: :chrome, screen_size: [1400, 1400]
end

```
The test generated by scaffold generator looks like this, (Note I added **take_screenshot**,  **assert_text @post.body** and  **assert_text @post.title** inside "creating a Post"):
```
require "application_system_test_case"

class PostsTest < ApplicationSystemTestCase
  setup do
    @post = posts(:one)
  end

...

  test "creating a Post" do
    visit posts_url
    click_on "New Post"

    fill_in "Body", with: @post.body
    fill_in "Title", with: @post.title
    click_on "Create Post"

    assert_text @post.body
    assert_text @post.title
    assert_text "Post was successfully created"
    take_screenshot
    click_on "Back"
  end
...
...
end
```

### Expected behavior
If I use firefox it will work.
```
ubuntu@rails-dev-box:/vagrant/system_testing$ bundle exec bin/rails test:system
Run options: --seed 38665

# Running:

Puma starting in single mode...
* Version 3.10.0 (ruby 2.4.2-p198), codename: Russell's Teapot
* Min threads: 0, max threads: 4
* Environment: test
* Listening on tcp://127.0.0.1:38607
Use Ctrl-C to stop
...[Screenshot]: tmp/screenshots/test_creating_a_Post.png

.

Finished in 9.689074s, 0.4128 runs/s, 0.6193 assertions/s.
4 runs, 6 assertions, 0 failures, 0 errors, 0 skips
```

![test_creating_a_post](https://user-images.githubusercontent.com/2817059/32746434-e6d86820-c8b5-11e7-9ceb-8f6f82918413.png)

### Actual behavior
If I use google chrome the test will fail to add correct text input to the post title and body. 
```
Failure:
PostsTest#test_creating_a_Post [/vagrant/system_testing/test/system/posts_test.rb:21]:
expected to find text "MyText" in "Post was successfully created. Title: Myt Body: Myxting Edit | Back"
```
![test_failure_creating_a_post](https://user-images.githubusercontent.com/2817059/32746435-e6f44496-c8b5-11e7-96a0-e10e2b907117.png)

### System configuration
**google-chrome version**
Google Chrome 62.0.3202.89 
**firefox version**
Mozilla Firefox 56.0
**Rails version**:
Rails 5.2.0.alpha
**Ruby version**:
ruby 2.4.2p198 (2017-09-14 revision 59899) [x86_64-linux-gnu]

**Comment by eileencodes** [comment]
I created an app locally and added the same changes you did to your test scaffold and all of the tests passed. I suspect this is an issue with one of the tools outside of system tests in Rails as it is mostly a wrapper around Capybara and it's drivers. 

One difference is I'm on Chrome 61 but if the Chrome version that's not something that Rails can deal with. It might be possible that the chrome driver needs to be updated. Can you check your chrome driver version and see if updating it resolves your problem?

**Comment by twalpole** [comment]
If your `chromedriver` is up to date and the problem still exists, you're probably running running into https://bugs.chromium.org/p/chromedriver/issues/detail?id=1771&q=send_keys&colspec=ID%20Status%20Pri%20Owner%20Summary which seems to keep reappearing in `chromedriver` every few versions.  Not much rails or capybara can do about it.

**Comment by eileencodes** [comment]
Thanks @twalpole. I'm going to close this issue then since it's not a Rails issue.
