### ISSUE TITLE
Don't know how to build task 'active_storage:install'

### ISSUE THREAD

**Issue by pbmarcano** [rails/rails#31142]
Hi. I'm making a new app and needed attachments so I figured I'd give ActiveStorage a try.

Only changes to the rails defaults I've made is using PostgreSQL for the database and Rspec for the tests.

### Steps to reproduce

1. Create a new rails app.
2. Add `gem 'activestorage', '~> 0.1'` to `Gemfile`
3. `bundle install`
3. Run `rails active_storage:install`

### Expected behavior
I expect the migrations to be copied over as the [documentation](https://github.com/rails/rails/tree/master/activestorage#installation) suggests

### Actual behavior
I get this error:
```
Don't know how to build task 'active_storage:install' (see --tasks)
/Users/pbmarcano/.rvm/gems/ruby-2.4.0/gems/railties-5.1.4/lib/rails/commands/rake/rake_command.rb:21:in `block in perform'
/Users/pbmarcano/.rvm/gems/ruby-2.4.0/gems/railties-5.1.4/lib/rails/commands/rake/rake_command.rb:18:in `perform'
/Users/pbmarcano/.rvm/gems/ruby-2.4.0/gems/railties-5.1.4/lib/rails/command.rb:46:in `invoke'
/Users/pbmarcano/.rvm/gems/ruby-2.4.0/gems/railties-5.1.4/lib/rails/commands.rb:16:in `<top (required)>'
/Users/pbmarcano/Developer/active_storage_test/bin/rails:9:in `require'
/Users/pbmarcano/Developer/active_storage_test/bin/rails:9:in `<top (required)>'
/Users/pbmarcano/.rvm/gems/ruby-2.4.0/gems/spring-2.0.2/lib/spring/client/rails.rb:28:in `load'
/Users/pbmarcano/.rvm/gems/ruby-2.4.0/gems/spring-2.0.2/lib/spring/client/rails.rb:28:in `call'
/Users/pbmarcano/.rvm/gems/ruby-2.4.0/gems/spring-2.0.2/lib/spring/client/command.rb:7:in `call'
/Users/pbmarcano/.rvm/gems/ruby-2.4.0/gems/spring-2.0.2/lib/spring/client.rb:30:in `run'
/Users/pbmarcano/.rvm/gems/ruby-2.4.0/gems/spring-2.0.2/bin/spring:49:in `<top (required)>'
/Users/pbmarcano/.rvm/gems/ruby-2.4.0/gems/spring-2.0.2/lib/spring/binstub.rb:31:in `load'
/Users/pbmarcano/.rvm/gems/ruby-2.4.0/gems/spring-2.0.2/lib/spring/binstub.rb:31:in `<top (required)>'
/Users/pbmarcano/Developer/active_storage_test/bin/spring:15:in `<top (required)>'
bin/rails:3:in `load'
bin/rails:3:in `<main>'
```

### System configuration
**Rails version**: `5.1.4`

**Ruby version**: `2.4.0`

**Comment by rafaelfranca** [comment]
Thank you for the issue. You are using the instructions of active storage in the Rails framework that is a little bit different from the instructions of the activestorage 0.1 https://github.com/rails/activestorage/tree/archive#installation. Please try the installation of the version you have.
