### ISSUE TITLE
Schema cache doesn't work with syck

### ISSUE THREAD

**Issue by mrsimo** [rails/rails#31141]
### Steps to reproduce

1. Have any Rails 5.1+ application with `syck` added to the Gemfile.
2. Run `rails db:schema:cache:dump`

Sometimes dumping the cache crashes, in our case it succeeds, but crashes when parsing it.

Here's the failure using the template: https://gist.github.com/mrsimo/1ca7d1c233754279fab70f1d77818158

Includes a monkey patch that when uncommented makes the test pass.

### Expected behavior

Schema caching should hopefully work with syck too.

### Actual behavior

It crashes on dumping or parsing (depending on the adapter, I think).

### System configuration
**Rails version**: 5.1.4
**Ruby version**: 2.4.2, 2.3.5

**Comment by mrsimo** [comment]
I'd like to work on a patch for this. The `SchemaCache` class already [has some code](https://github.com/rails/rails/blob/72c311955128d3d1693ac35b41a80d4caaebec99/activerecord/lib/active_record/connection_adapters/schema_cache.rb#L24-L38) so that it can be serialized/deserialized with psych. If you think it reasonable, we can include the necessary bits so that it can also be serialized/deserialized with syck.

**Comment by kaspth** [comment]
I thought syck was removed from Ruby core in favor or Psych? What's the difference between them?

**Comment by mrsimo** [comment]
Psych is certainly the default now, but [syck is still alive](https://github.com/ruby/syck/). We've kept using syck the last few years since we have quite a bit of serialized data that isn't easy to convert.

**Comment by jeremy** [comment]
We assume that YAML is backed by Psych very thoroughly:
```ruby
actionpack/lib/action_controller/metal/strong_parameters.rb
763:      # Makes the YAML parser call `init_with` when it encounters the keys below
770:    def init_with(coder) # :nodoc:

activesupport/lib/active_support/ordered_hash.rb
29:    def encode_with(coder)

activesupport/lib/active_support/core_ext/string/output_safety.rb
222:    def encode_with(coder)

activesupport/lib/active_support/values/time_zone.rb
516:    def init_with(coder) #:nodoc:
520:    def encode_with(coder) #:nodoc:

activesupport/lib/active_support/time_with_zone.rb
175:    def init_with(coder) #:nodoc:
179:    def encode_with(coder) #:nodoc:

activemodel/lib/active_model/errors.rb
439:    def init_with(coder) # :nodoc:

activemodel/lib/active_model/attribute.rb
119:    def init_with(coder)
127:    def encode_with(coder)

activerecord/test/cases/yaml_serialization_test.rb
91:    Topic.first.encode_with(coder)

activerecord/lib/active_record/relation/delegation.rb
41:    delegate :to_xml, :encode_with, :length, :each, :uniq, :join,

activerecord/lib/active_record/locking/optimistic.rb
203:      def init_with(coder)
207:      def encode_with(coder)

activerecord/lib/active_record/core.rb
306:    # #encode_with.
313:    #   old_post.encode_with(coder)
316:    #   post.init_with(coder)
318:    def init_with(coder)
377:    # guaranteed to match the structure of +coder+ passed to the #init_with
385:    #   Post.new.encode_with(coder)
387:    def encode_with(coder)

activerecord/lib/active_record/connection_adapters/column.rb
45:      def init_with(coder)
56:      def encode_with(coder)

activerecord/lib/active_record/connection_adapters/schema_cache.rb
26:      def encode_with(coder)
34:      def init_with(coder)

activerecord/lib/active_record/persistence.rb
71:        klass.allocate.init_with("attributes" => attributes, "new_record" => false, &block)

activerecord/lib/active_record/relation.rb
257:    def encode_with(coder)
```

We aren't going to reintroduce Syck support in case it has replaced the YAML constant. Ruby 2.2+ removed the ability to change the YAML engine entirely. Psych is now just the official YAML lib.

Best case: The syck gem stops overriding `YAML` by default. Allow users to use Syck when needed for backward compatibility while still using the official YAML parser.

**Comment by mrsimo** [comment]
Ah, thank you about that. Makes a lot of sense. I guess we'll do some kind of monkey patch and work on removing syck from our codebase. Sorry about the noise, then! ❤️

**Comment by jeremy** [comment]
Definitely signal. Been through Syck → Psych conversions too—no fun migrating old serialized data. Thanks for raising the issue 😊
