### ISSUE TITLE
Journey router adds single slash to request.script_name after mounting Engine at '/'

### ISSUE THREAD

**Issue by mamhoff** [rails/rails#31152]
### Steps to reproduce

Given a Rails `routes.rb` file that references an Engine: 

```ruby
MyApp::Application.routes.draw do
  get '*path',
    to: 'before_engine_requests#process',
    as: 'before_engine_requests',
    constraints: lambda { |request|
      # everything is fine
      request.fullpath == '/before_engine_request'
    }

  mount Spree::Core::Engine, at: '/'

  get '*path',
    to: 'after_engine_requests#process',
    as: 'after_engine_requests',
    constraints: lambda { |request|
      # This will never match as at this point, the router prepends a second '/ '
      request.fullpath == '/before_engine_request' 
    }
end
``` 

And a routing spec that references the second `get` block: 

```ruby
  it 'lets the redirects controller handle it' do
    expect(get: '/after_engine_request').to route_to(
      controller: 'after_engine_requests', action: 'process', path: 'after_engine_request'
    )
  end
```

This spec will fail although the `get` constraint in the first example works fine. 

### Expected behavior

`request.fullpath` inside the route constraint lambda should evaluate to `/before_engine_request`

### Actual behavior

`request.fullpath` inside the second route constraint lambda evaluates to `//before_engine_request` (with two slashes in front).

### Probable cause

After the engine is mounted, the request's `SCRIPT_NAME` environment key is set to '/'. 

This only happens in `ActionDispatch::Journey::Router#recognize`: https://github.com/rails/rails/blob/master/actionpack/lib/action_dispatch/journey/router.rb#L70

In `ActionDispatch::Journey::Router#call`, it has been fixed in https://github.com/rails/journey/commit/61ddc45c07c2b946a725bbdca8ef8 (ages ago), referencing Rails issues

rails/rails#2131
rails/rails#2230
rails/rails#2579
rails/rails#5342

Also, the IETF says SCRIPT_NAME should be an empty string (although the wording here is not entirely clear): https://tools.ietf.org/html/rfc3875#section-4.1.13

### System configuration
**Rails version**: 4.2.10 (and newer versions)

**Ruby version**: 2.3.5

**Comment by kyrylo** [comment]
This is still an issue with Rails `6.0.3.2`. I found this because a user of my library reported a bug, which led me to this issue. Bug report: https://github.com/airbrake/airbrake/issues/1072
