### ISSUE TITLE
Ability to provide body for post request in ActionDispatch::IntegrationTest

### ISSUE THREAD

**Issue by skatkov** [rails/rails#31161]
### Steps to reproduce

If you look into ActionController::TestCase documentation you'll notice this line on top:

> Rails discourages the use of functional tests in favor of integration tests (use ActionDispatch::IntegrationTest).
1. I have a cart controller:
```
class Api::CartController < ApiController
  def create
    ... #does something with items object
  end

  def items
    JSON.parse(request.body.string|| { items: [] })
  end
end
```
2. I'm trying to write a IntegrationTest that does post request with body:
```
class CartControllerTest < ActionDispatch::IntegrationTest
  test 'correct request' do
    post api_cart_index_path, 
      params: correct_params
      headers: {'content-type': 'application/json'}
  end
end
```

### Expected behavior
I expect a way to provide a body for request.

It would be nice if `ActionDispatch::IntegrationTest` and `ActionController::TestCase` to have a feature parity, so `ActionDispatch::IntegrationTest` could be used in all cases.

### Actual behavior
But there seems to be no way to provide JSON body in here? or i'm missing something here?

with `ActionController::TestCase` you can still do something like this;

```
class CartControllerTest < ActionController::TestCase
  test 'correct request' do
    post :create,
        body: "{\"items\":{\"quantity\":1, \"asin\":\"test\"}}"
    ...
  end
end
```

### System configuration
**Rails version**:
Rails 5.1.4
**Ruby version**:
2.4.2

**Comment by al2o3cr** [comment]
@skatkov Reading the code, it seems like passing the body as `params:` would work. If it doesn't, what happens?

**Comment by skatkov** [comment]
https://github.com/rails/rails/issues/30316

This issue cleared up some of the confusion I had with this. I'll implement this in a code and will report back with details.

**Comment by skatkov** [comment]
So here is end code:

```
post "#{api_cart_index_path}/?store_id=#{@store.public_id}&store_code=#{@store.code}",
        params: {items: [{ "quantity" => 1, 'asin' => 'test'}]},
        as: :json
```

It was a bit unexpected that params will be later on passed as a body. I would say that my issue is not actual -- and should be closed. By agree with #30316 -- it would be nice to put some more documentation about this functionality.
