### ISSUE TITLE
ActiveRecord sum returns nil for date time columns

### ISSUE THREAD

**Issue by curtp** [rails/rails#31168]
We've been using the sum method on date time columns for many versions of rails.  We're upgrading from 4.2 to 5.0 (on the way to 5.1) and encountered the following issue.

In rails 4.2 (and before) the following would return a value
PostComments.where(post_id: 1).sum(:updated_at)
 => 584938820615279  

In rails 5.0.6 it is returning nil
PostComments.where(post_id: 1).sum(:updated_at)
 => nil

I tried this and it seemed to work
PostComments.where(post_id: 1).select("sum(updated_at) as sum").first.sum
=> 584938820615279

Rails version: 5.0.6
Ruby version: 2.3.0
MySQL: 5.6

**Comment by curtp** [comment]
I may have found a better work around and possibly the solution:

PostComments.where(post_id: 1).sum("unix_timestamp(updated_at)")

**Comment by pixeltrix** [comment]
Scratching my head to think what the use case is for knowing the total number of seconds since the epoch date for a bunch of records. I can sort of see a use for `average` since that gives an estimation of how old the records are but can you explain your use of `sum` - the `PostComments` example above doesn't seem to make sense.

**Comment by curtp** [comment]
We use it for creating a cache key used for fragment caching. If any of the records changed, then the cache is busted. The PostComments example was contrived.

**Comment by pixeltrix** [comment]
@curtp yeah, that's the only thing I could think of that could've been useful. The idiomatic version of that would be to take the maximum timestamp - I assume that an update doesn't always result in a higher maximum timestamp and that's why you're using `SUM` ?

**Comment by curtp** [comment]
@pixeltrix Possibly.  Will have to check things and see if max would work.

**Comment by duffyjp** [comment]
In the past I've had to do similar things when a max updated_at doesn't cut it.  For instance when a row in the middle is deleted.

Would [collection_cache_key](https://github.com/rails/rails/blob/master/activerecord/lib/active_record/collection_cache_key.rb) work for your situation? It's the same kind of thing but stores the sum of records so if one is removed it invalidates.

**Comment by curtp** [comment]
@duffyjp Thanks for the pointer to collection_cache_key.  I'll definitely check it out and see if it will work for us.

Yes, the delete scenario is what we had to get around.  I'm also going to look into other options like callbacks stamping something on the parent model.  Kind of like a cache counter.  That would save the overhead of running a query to build the cache key.  Not sure I like the idea of widening out the parent model for this scenario, but may be worth it for performance gain.

**Comment by pixeltrix** [comment]
@duffyjp yes, if your model allows deletion then `MAX(created_at)` doesn't work. In these scenarios I tend to have a parent model that can be touched to invalidate caches - doing calculations on millions of rows for a cache key doesn't really cut it.

@curtp will still look into what's causing this, I suspect that we're trying to cast a very large value to a Time instance and getting an invalid value which is captured and then converted to nil.

**Comment by pixeltrix** [comment]
Going to close this because `sum(:updated_at)` isn't a valid query on PostgreSQL - you need to use `EXTRACT(epoch FROM updated_at)` and given that `UNIX_TIMESTAMP(updated_at)` works on MySQL then I don't think we should support automatically casting to an integer.
