### ISSUE TITLE
ActiveStorage: Cannot attach a has_many_attached attachment if model instance is not persisted

### ISSUE THREAD

**Issue by DLawla** [rails/rails#31164]
Hi guys,
I'm seeing a discrepancy in the `#attach` behaviour for a `has_one_attached` and a `has_many_attached` model instance if an attachment is attached before the model instance is saved.
Specifically, for a model w/ `has_one_attached`, you can attach an attachment before the model instance is saved. However, for a model w/ `has_many_attached`, if you try to attach an attachment before the model is saved, the following exception is raised:
`ActiveRecord::RecordNotSaved: You cannot call create unless the parent is saved`

I've done some testing below, and found a temporary work-around, but it is not the ideal solution.

### Steps to reproduce
```
class Comment < ApplicationRecord
  has_many_attached :files
  # ...
end

Comment.new.files.attach(io: File.open('path/to/file'), filename: 'test.pdf', content_type: 'application/pdf')
# => ActiveRecord::RecordNotSaved: You cannot call create unless the parent is saved
```

I dug into the `ActiveStorage::Attached::Many`, and comparing with how `attach` is handled in `ActiveStorage::Attached::One` I did the following to find a temporary solution. It reveals, in my opinion, some weird and unintuitive behaviour:

```
def attach(*attachables)
      attachables.flatten.collect do |attachable|        
        # If record does not yet persist

        # Fails (original) => Raises exception
        # Raises ActiveRecord::RecordNotSaved: You cannot call create unless the parent is saved
        attachments.create!(name: name, blob: create_blob_from(attachable))

        # Including record => Raises exception
        # Raises ActiveRecord::RecordNotSaved: You cannot call create unless the parent is saved
        # attachments.create!(name: name, record: record, blob: create_blob_from(attachable))

        # building then saving => Raises different exception
        # Raises ActiveRecord::RecordInvalid: Validation failed: Record must exist
        # attachments.build(name: name, blob: create_blob_from(attachable)).save!

        # building with record, then saving => Works!
        # attachments.build(name: name, record: record, blob: create_blob_from(attachable)).save!
      end
    end
```
Weird, huh? I was surprised that `build` -> `save!` works, but a straight `create!` with an included record doesn't.

Again, perhaps this is by design, but thought it weird that the two attachments `One` and `Many` have different behaviour here.

**Rails version**:
rails 5.2.0.alpha

**Ruby version**:
ruby 2.4.2

**Comment by georgeclaghorn** [comment]
> Specifically, for a model w/ has_one_attached, you can attach an attachment before the model instance is saved.

While it’s true that you can call `attach` for an unpersisted record, doing so causes the record to be saved. For example, the following unexpectedly causes a Person record to be created:

```ruby
Person.new(name: 'Jane Doe').tap do |user|
  user.photo.attach(file)
end
```

There’s no way to build a record and attach files to it before saving. This prevented us from making it easier to create a record and attach a file in a single step in #30737.

I don’t think this needs to block the first 5.2 beta, but the more I think about it, the more I’m convinced that it could block final release. At the very least, if we intend not to allow files to be attached to unpersisted records, we ought to raise an error in `ActiveStorage::Attached::{One,Many}#attach`.

/cc @dhh

**Comment by DLawla** [comment]
@georgeclaghorn thanks for the fast reply, mate.

> There’s no way to build a record and attach files to it before saving.

I am seeing some funny behaviour upon further digging. When I try to attach a file to an instance that is not yet valid, a blob and an attachment can be created.

From my testing, if person required `name`, then
`
person = Person.new.tap do |user|
  user.photo.attach(file)
end

Person.count # => 0
ActiveStorage::Blob.count # => 1
ActiveStorage::Attachment.count # => 1

person.name = 'test'
person.save
person.photo # => <ActiveStorage::Attached::One ...>

Person.count # => 1
ActiveStorage::Blob.count # => 1
ActiveStorage::Attachment.count # => 1
`

 Any thoughts on this?

**Comment by GBH** [comment]
Because of reasons, I "attach" files to unsaved records. By having an accessor that holds file data and then doing the actual attachment on `after_save` callback. That's basically what Paperclip does.

Would it makes sense to defer actual attachment after record is successfully saved?

**Comment by georgeclaghorn** [comment]
Yes, that seems like the appropriate thing to do when the record hasn’t been persisted yet.
