### ISSUE TITLE
Consider reverting: Raise ArgumentError when passing nil to Relation#merge

### ISSUE THREAD

**Issue by JanStevens** [rails/rails#31197]
### Steps to reproduce

Build up a query and pass in `nil` to `merge`. As described in this commit https://github.com/rails/rails/commit/b71e08f8ba0447971553452a00917d00020edd35 an ArgumentError is raised

### Expected behavior
I do not expect this at all and rather see the old behaviour, for one simple reason you cannot merge scopes on the fly, consider following example:

```ruby
Person.where(...)
  .merge(sorting_scope)

def sorting_scope
  return if special condition
  Person.additional_scope
end
```

Add another 2 - 3 files that build up the resulting query the above statements are needed else you have to brake up the method chain and assign a variable and return early in the main method.

### Actual behavior
Raise an exception

### System configuration
**Rails version**: 5.1.3

**Ruby version**: 2.4.1

**Comment by matthewd** [comment]
The meaning of "merge with nil" is too unclear to me.

You can solve your problem by either defining `sorting_scope` using `scope`, or by just changing its definition:

```ruby
def sorting_scope
  return all if special condition
  Person.additional_scope
end
```

Or by changing the call to `.merge(sorting_scope || all)` -- but IMO the more surprising behaviour here is to have `sorting_scope` return nil... which would make it *only* suitable for use with `merge`.
