### ISSUE TITLE
Rails-generated binstubs are incompatible with Bundler-generated binstubs

### ISSUE THREAD

**Issue by stevenharman** [rails/rails#31193]
There seems to be an incompatibility between the Rails vs. Bundler-generated `bin/bundle` binstub. Futher, other Bundler-generated binstubs (e.g., `bin/rspec`) generated by older versions of Bundler don't play well with those generated by Bundler v1.16.

### Steps to reproduce

```shell
rails new widget_app
cd widget_app
# add rspec-rails to Gemfile and bundle
bundle binstubs rspec-core
bin/rspec
```

### Expected behavior
RSpec should be invoked and run tests.

### Actual behavior
The `bin/bundler` binstub, as generated by Rails, loads Bundler, which installs gems.

If you'd passed any arguments to the original binstub, e.g.,  `bin/rspec -p --fail-fast`, you'd see the following error:

```text
bin/rspec -p --fail-fast
Unknown switches '-p, --fail-fast'
```

### What's happening?

The Bundler-generated `bin/rspec` looks for a `bin/bundle` binstub, and if it's found, loads it. This isn't too different from what the Rails-generated binstubs do. But the Bundler-generated `bin/bundle` binstub is significantly different from the Rails-generated `bin/bundle` bin stub.

Specifically, the Bundler-generated version checks to see how `bin/bundle` was invoked. It ensure arguments are passed along in different ways depending on invocation. The Rails-generated `bin/bundle` just loads Bundler and runs it. The Rails-generated version effectively turns

```shell
bin/rspec -p --fail-fast
```

into

```shell
bin/rspec $(bin/bundle -p --fail-fast)
```

See the following Gist for the differences between the various binstubs generated by Rails and Bundler: https://gist.github.com/stevenharman/8fca435526917a70ec57ec457ecd55c9. Also, this conversation started over in https://github.com/rails/webpacker/issues/998#issuecomment-345322193, so there's some more context there.

### System configuration
**Rails version**: 5.1.4

**Ruby version**: 2.4.2

**Comment by jsncmgs1** [comment]
Personally I'd avoid bundler 1.16 for now:

https://github.com/rails/rails/pull/31023
https://github.com/bundler/bundler/issues/6072
... and more

**Comment by guilleiguaran** [comment]
Looks like this was reported in Bundler issue tracker also: https://github.com/bundler/bundler/issues/6149

**Comment by indirect** [comment]
We've fixed bundler/bundler#6072, and we're working on a clearer error message for this issue in bundler/bundler#6149. For now, the fix is to run `bundle binstubs bundler --force`.

**Comment by stevenharman** [comment]
@indirect I see the changes in Bundler (bundler/bundler#6149), but am unclear if that is sufficient to consider this issue, from the Rails-side, as closed? If not, is there more work being done, or a criteria we can use to judge when this issue has been fixed?

**Comment by Neilos** [comment]
@stevenharman I ran into this problem when trying to run `./bin/webpack-dev-server` in a new project I created on 27th Feb 2018. The latest Bundler changes in relation to the issue you reference ([bundler/bundler#6149](https://github.com/bundler/bundler/issues/6149)) added a helpful message ("Run `bundle binstubs bundler --force` to correct this."). This did indeed resolve the issue for me, but, in my opinion, it would be good if rails either did this for us (as part of the rails new generator) or just doesn't generate bin stubs at all (leaving it to the developer to manage bin stubs entirely via bundler).

**Comment by gregblass** [comment]
Hey there @Neilos - I'm getting this when trying to deploy with Capistrano, but I'm unsure of where to change `bin/bundle` to `bundle binstubs bundler --force`. I tried running it locally, but that didn't do anything. Any direction you can point me in? I currently can't deploy my production app :(

**Comment by michaelglass** [comment]
It appears that the current state of the world is:
- 😭using rails generated binstubs? bundle generated binstubs no longer work 
- 😐using bundler generated binstubs? rails raises a warning (better)
- 😄using rails generated binstubs AND bundler generated `bin/bundle` seems copacetic

can rails use bundler's `bin/bundler` binstub?

**Comment by alopez25** [comment]
Hi @gregblass , I was wondering if you managed to solve this issue (i.e. running `bundle binstubs bundler --force` and getting nothing in return. Have you?

**Comment by FunkyloverOne** [comment]
@alopez25 you might have that issue if `/your-app-root-folder-path/bin` is in your `PATH` env var, so it tries to use that `bin/bundle` binstub to re-generate itself _(I guess)_.

Anyway, I had that issue when I tried to run `bundle binstubs bundler --force` inside my docker container, where it was the case. So then on my host machine, where:
```
$ which bundle
/home/funky/.gem/ruby/2.5.3/bin/bundle
```
I knew it is going to use the correct bin, and `bundle binstubs bundler --force` worked as expected.
