### ISSUE TITLE
Error in the document about smtp configuration

### ISSUE THREAD

**Issue by qriqri** [rails/rails#31192]
### Steps to reproduce

(Guidelines for creating a bug report are [available
here](http://guides.rubyonrails.org/contributing_to_ruby_on_rails.html#creating-a-bug-report))

In the installation guide http://www.redmine.org/projects/redmine/wiki/EmailConfiguration
we can read about the smtp port config:
      port: '587'
The good syntaxe is (remove the quote):
      port: 587

### Expected behavior
Tell us what should happen
Redmine word

### Actual behavior
Tell us what happens instead
Redmine do not start

### System configuration
**Rails version**:

**Ruby version**:

**Comment by redtachyons** [comment]
This is not a rails issue, open the issue in [Redmine's issue tracker](www.redmine.org/projects/redmine/issues) instead

**Comment by y-yagi** [comment]
@redtachyons is right. Please open the issue to Redmine's issue tracker.
