### ISSUE TITLE
Incorrect column type after joins call

### ISSUE THREAD

**Issue by UlyssesInvictus** [rails/rails#31196]
### Steps to reproduce

Gist here: https://gist.github.com/UlyssesInvictus/86c910f81a72dee66b4ef722f783be6b

This is similar to https://github.com/rails/rails/issues/30476, but more general, in that it seems to apply to any joins and not just a follow up with `group_by`.

If I select a column on a table accessed through a joins, and that column shares a name with a column from the original table being joined _to_, then AR will cast the result to the column type of the joined _on_ table rather than using the column type of the joined _to_ table.

For example, (as produced in the gist), if I have User and a Group, where the former has an `integer` `number` column and the latter has a `string` `number` column, then

`Group.joins(:user).pluck('users.number')`

will produce a string instead of an integer/

This is true if I use `select` instead, or if I reverse the direction, in which case what should be `string` becomes an `integer` (this is even more egregious, if it can't be cast nicely, as the gist shows a value of `"test"` is changed into `0`).

_**However**_, the issue is avoided if I cast the column name to any non-clashing name, i.e.

`Group.joins(:user).pluck('users.number AS foo')`

in which case, an integer with the right value is produced.

### Expected behavior

Column types of table being queried from are retained after joining to that table.

### Actual behavior

Column type of table being used as joins start point is being used instead.

### System configuration
**Rails version**:
5.0.5

**Ruby version**:
ruby 2.4.1p111 (2017-03-22 revision 58053) [x86_64-darwin16]

**Comment by NoryDev** [comment]
This issue is still valid, the bug is still present 😕

**Comment by UlyssesInvictus** [comment]
I haven't been able to spend any time following up on this issue further -- nor would I know how to, since I really don't have much experience working with AR guts -- but, yes, it does still seem to be a problem. I don't really know what I can do, though, beside try and get this issue open again so people can at least see the fix I found.
