### ISSUE TITLE
change_table migration fails on sqlite if table is using id: false and custom id type (string for uuid)

### ISSUE THREAD

**Issue by luchano** [rails/rails#31201]
### Steps to reproduce

Create a table with id:false in options, and then create an :id column with primary_key: true 
Create a record on this table.
Then try to create a migration to alter the table (remove_column for example)

Test case reproducing the error
```
# frozen_string_literal: true

begin
  require "bundler/inline"
rescue LoadError => e
  $stderr.puts "Bundler version 1.10 or later is required. Please update your Bundler"
  raise e
end

gemfile(true) do
  source "https://rubygems.org"

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  # Activate the gem you are reporting the issue against.
  gem "activerecord", "5.1.0"
  gem "sqlite3"
end

require "active_record"
require "minitest/autorun"
require "logger"

# Ensure backward compatibility with Minitest 4
Minitest::Test = MiniTest::Unit::TestCase unless defined?(Minitest::Test)

# This connection will do for database-independent bug reports.
ActiveRecord::Base.establish_connection(adapter: "sqlite3", database: ":memory:")
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table "payments", id: false, force: :cascade do |t|
    t.string :id, primary_key: true, index: true, null: false
    t.text :other_attr
  end
end

class Payment < ActiveRecord::Base
end


class RemoveOtherAttrFromPayment < ActiveRecord::Migration[5.1]
  def change
    change_table "payments" do |t|
      t.remove :payments, :other_attr, :text
    end
  end
end

class BugTest < Minitest::Test
  def test_migration_up
    uuid="214fe0c2-dd47-46df-b53b-66090b3c1d40"
    Payment.create! id: uuid, other_attr: "xxx"
    RemoveOtherAttrFromPayment.migrate(:up)
    Payment.reset_column_information

    assert_equal uuid, Payment.first.id
  end
end
```

### Expected behavior

That the migration works.

### Actual behavior

An "SQLite3::MismatchException: datatype mismatch" is raised. 
The temporary table created seems to have fixed ""id" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL" ignoring the previous id: false on table creation.
 
### System configuration
**Rails version**:
5.1.2

**Ruby version**:
2.4.1

**Comment by composerinteralia** [comment]
I think the problem is when the old table gets copied into a new temporary table: https://github.com/rails/rails/blob/master/activerecord/lib/active_record/connection_adapters/sqlite3_adapter.rb#L397
It ignores the `type` of the primary key.
`@definition.primary_key(from_primary_key, :varchar)` seems to produce the right query, but then it errors out later when it tries to copy over the index. I will look into this more next week.
