### ISSUE TITLE
Feature: render partial, dynamic:true

### ISSUE THREAD

**Issue by eiked** [rails/rails#31207]
I'd like to suggest a new feature:
render partials should provide for dynamic reload.

I'd expect some harness on render(partial)
so to reload that partial upon trigger.

**Comment by y-yagi** [comment]
Please use the [Rails Core mailing list](https://groups.google.com/forum/#!forum/rubyonrails-core) for feature requests, where a wider community will be able to help you. We reserve the Rails issue tracker only for bugs in Rails.
