### ISSUE TITLE
config.railties_order and railties initializers firing in reverse

### ISSUE THREAD

**Issue by GBH** [rails/rails#31218]
### Steps to reproduce

* You define this in your application.rb: `config.railties_order = [:all, :main_app]`
* You realise that engine's initializer runs **after** your own. Thus you cannot override things set by it.
* Cry  

I found issue right here: https://github.com/rails/rails/blob/master/railties/lib/rails/application.rb#L556
For some reason there's `reverse` there. Removing that reverse seems to make things work again (with or without `config.railties_order`)

I'll try to make a PR for this.

**Edit:** Working through existing test: https://github.com/GBH/rails/commit/7aae71dcca8e314859d99f384b0d1787ee46984a

Removing reverse makes things fail because other initializers are prepending things (routes, view paths) instead of appending. That's why there's `reverse` in the first place I guess?.

Switching things around worked until I got to `append_assets_path` that comes from sprokets. Now this is the same oddity: https://github.com/rails/sprockets-rails/blob/master/lib/sprockets/railtie.rb#L57
It's called "append" yet it prepends via `unshift`. 

Is there a reason why it's all set up this way? There must be something I'm not seeing.

**Edit2:** Ok, so this is even worse now. Because of this reverse prepending business it's not possible to even override engine's views/controllers/models/assets.

### System configuration
**Rails version**:
5.2.alpha

**Ruby version**:
2.4

**Comment by rafaelfranca** [comment]
I don't know if there is a reason but I find really hard to change this behavior right now. Removing that reverse, as you already saw, is going to require a lot of railties to change their code.

**Comment by GBH** [comment]
I think prepending is happening because railties need to be overriden by the main app. That works just fine as long as you don't mess with railties_order. There must be a way to make it behave predictably without messing up existing railties that use `prepend`.
