### ISSUE TITLE
Unexpected sudden test failures with ActiveStorage. (recent change?)

### ISSUE THREAD

**Issue by GBH** [rails/rails#31210]
Some recent change to ActiveStorage started to mess things up. Was working fine before.

When running tests I get odd and completely random errors. Sometimes test suite passes completely, more often I get random number of errors. Completely inconsistent.

Error usually looks like this:
```
Error:
Comfy::Admin::Cms::FilesControllerTest#test_get_index_with_redactor_files:
NoMethodError: undefined method `attachment_url' for #<Comfy::Admin::Cms::FilesController:0x005606581fb968>
    /home/oleg/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/bundler/gems/rails-fbb12910bdf2/actionpack/lib/action_dispatch/routing/polymorphic_routes.rb:281:in `handle_model_call'
```
or 
```
Error:
Comfy::Admin::Cms::FilesControllerTest#test_get_index_with_redactor_images:
NoMethodError: undefined method `to_model' for #<ActiveStorage::Variant:0x0056065588bdf8>
    /home/oleg/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/bundler/gems/rails-fbb12910bdf2/actionpack/lib/action_dispatch/routing/polymorphic_routes.rb:265:in `handle_model'
```

Completely random:

496 runs, 1717 assertions, 0 failures, 1 errors, 0 skips

496 runs, 1675 assertions, 0 failures, 13 errors, 0 skips

496 runs, 1718 assertions, 0 failures, 0 errors, 0 skips

### System configuration
**Rails version**:
5.2.alpha

**Ruby version**:
2.4.1

**Comment by georgeclaghorn** [comment]
Are you able to reproduce with a minimal script, perhaps using [this template](https://github.com/rails/rails/blob/master/guides/bug_report_templates/active_record_master.rb) as a starting point?

**Comment by GBH** [comment]
Here's Travis run: https://travis-ci.org/comfy/comfortable-mexican-sofa/builds/306575854

3 runs against same code with completely different outcomes. 

All I did was switch from https://github.com/rails/rails/pull/30783 (hint hint!) to master branch to try `config.railties_order` approach. (It's not railties_order issue, fails with or without it).

I'll try to replicate using the script. I just don't understand the randomness of this.

**Comment by GBH** [comment]
@georgeclaghorn https://gist.github.com/GBH/1efc6c2511765730e647f539aedc4203

How does one even load active_storage in? I get
```
undefined method `has_one_attached' for Post(id: integer):Class (NoMethodError)
```

**Comment by georgeclaghorn** [comment]
You can make a minimal reproduction app if that’s easier.

**Comment by GBH** [comment]
You know what. I think it's my app. I do route mangling in tests and it seems that routes coming from engines `config/routes.rb` are affected for some reason. I killed the mangling and there's no more of those errors. Now to figure out why `with_routing` still doesn't work as advertised.

I'll close this issue as there's nothing new with ActiveStorage that caused this. I just never noticed it before because I used my fork where I move ActiveStorage routes.

Please merge https://github.com/rails/rails/pull/30783

Thanks.

**Comment by JohnSmall** [comment]
I'm surprised you solved this just by changing `config/routes.rb` Random failures associated with ActiveStorage seems to be a common problem which no one has solved.
