### ISSUE TITLE
Use of expensive Redis operations in Redis Cache Store

### ISSUE THREAD

**Issue by badboy** [rails/rails#31246]
Hey, maintainer (of some sorts) of the redis-rb gem here.
I came across the new [Cache thingy](http://weblog.rubyonrails.org/2017/11/27/Rails-5-2-Active-Storage-Redis-Cache-Store-HTTP2-Early-Hints-Credentials/) in Rails using Redis.

I briefly skimmed the implementation and found the usage of the [`KEYS` command][keys], called from [`delete_matched`][delete_matched].
`KEYS` is a really expensive blocking command on Redis, as it will always need to scan the full keyspace for matching elements. It's use in production is generally not advised.
I'm not sure how frequently used the `delete_matched` API is/will be, so I can't say for sure that it will cause problems.

This should at least be documented for end users.

[delete_matched]: https://github.com/rails/rails/blob/95b86e57a6c07bc636f8feab4afd4c7fe0ca512c/activesupport/lib/active_support/cache/redis_cache_store.rb#L208
[keys]: https://github.com/rails/rails/blob/95b86e57a6c07bc636f8feab4afd4c7fe0ca512c/activesupport/lib/active_support/cache/redis_cache_store.rb#L54

**Comment by jeremy** [comment]
It's primarily to support namespaced `Rails.cache.clear` for use in dev/test/CI: https://github.com/rails/rails/blob/95b86e57a6c07bc636f8feab4afd4c7fe0ca512c/activesupport/lib/active_support/cache/redis_cache_store.rb#L262

 PR welcome to give a pointer + caveat in the method docs 👍
