### ISSUE TITLE
Failure to run active_storage:install

### ISSUE THREAD

**Issue by spdawson** [rails/rails#31245]
Should the `activestorage.gemspec` list `db/migrate/*` in the `files` field? the Rake task runs correctly if the same app is pointed at edge Rails on GitHub.

### Steps to reproduce

```sh
bundle exec rails active_storage:install
```

### Expected behavior

```sh
Copied migration 20171127215057_create_active_storage_tables.active_storage.rb from active_storage
```

### Actual behavior

```sh
rails aborted!
Don't know how to build task 'active_storage:install:migrations' (see --tasks)
```

### System configuration

Rails 5.2.0.beta1
Ruby 2.4.2

**Comment by y-yagi** [comment]
Thanks for your report! I think you are right. I created a patch.

**Comment by spdawson** [comment]
Thanks for the quick fix; confirmed working in 5.2.0.beta2

**Comment by boboroshi** [comment]
Note that if you're upgrading a pre 5.2 app, you have to uncomment the field in application.rb: `require "active_storage/engine"`

**Comment by mikecalex** [comment]
I'm getting the error `LoadError: cannot load such file -- active_storage/engine`. Any suggestions?

**Comment by KilmerLuizAleluia** [comment]
> I'm getting the error `LoadError: cannot load such file -- active_storage/engine`. Any suggestions?

Had the same here. How did you solve the problem?

**Comment by likeuwill** [comment]
add to app.rb
`require "active_storage/engine"`

**Comment by Rotaka92** [comment]
Getting same LoadError after adding require "active_storage/engine" to my application.rb. 

Further ideas?
