### ISSUE TITLE
Rails --api only app, not responding to PUT request via patch from pure html forms

### ISSUE THREAD

**Issue by atul-shimpi** [rails/rails#31249]
### Steps to reproduce

1) Create new app with --api option
2) Create a model and routes for the model
3) Create another seperate application. Add html form in it for updating any resource.
4) Form actions should be post and add hidden field with name = "method" and value = "patch"
5) Enter values and click the submit button

example
<form action="http://localhost:3000/brands/3" method="post">
        <input name="_method" type="hidden" value="patch" />
        Brand Name :  <input type="text" name="name" value="lg new"/>
        <br><br>
        Brand Description :  <input type="text" name="desc" value="india"/>
        <br><br>
        <input type="submit" value="Submit"/>
    </form>

(Guidelines for creating a bug report are [available
here](http://guides.rubyonrails.org/contributing_to_ruby_on_rails.html#creating-a-bug-report))

### Expected behavior
Put request should be fired at rails.

### Actual behavior
Rails throws error cannot POST [resource/3]

### System configuration
**Rails 5.1.4**:

**Ruby 2.3.3p222 (2016-11-21 revision 56859)**:

**Comment by atul-shimpi** [comment]
This works from postman with PUT request

**Comment by rafaelfranca** [comment]
Api only applications doesn't support method override. If you want to be able to use this feature you need to add the `Rack::MethodOverride` middleware in your middleware stack.

**Comment by atul-shimpi** [comment]
@rafaelfranca 
If possible can u share any code snippet or url ?

**Comment by atul-shimpi** [comment]
Please ignore
