### ISSUE TITLE
[AssetPipeline] all application.js files are precompiled, even in node_modules

### ISSUE THREAD

**Issue by MathieuDerelle** [rails/rails#31263]
### Steps to reproduce

```
rails new newapp --webpack
cd newapp
rake assets:precompile 
# at this point express/application.js is already precompiled in public/assets
# I'm not sure if it's normal or not so let's continue ...

yarn add vuetify
rake assets:precompile
# now vuetify/es5/.../application.js is precompiled
# which is clearly weird
```

Moveover you can not precompile in production anymore
`RAILS_ENV=production rake assets:precompile`
fails with
`ExecJS::RuntimeError: SyntaxError: Unexpected token: keyword (default)`
Explanation : 
Uglifier fail at minifying `vuetify/es5/.../application.js` because of `export default ...`

### Expected behavior
`node_modules/**/application.js` should not be precompiled

### Actual behavior
`node_modules/**/application.js` are precompiled

### System configuration
**Rails version**: 5.1.4

**Ruby version**: 2.2.5

![image](https://user-images.githubusercontent.com/16286023/33337311-e5ebcefc-d472-11e7-90b0-030767acb23a.png)

**Comment by schneems** [comment]
Can you switch over to using the sprockets 4 beta? This should only generate application.css files in the `app/assets/stylesheets` folder.

**Comment by eelcowen** [comment]
I have the same issue with Vuetify.... Any updates?

**Comment by schneems** [comment]
Did you try Sprockets 4?

**Comment by MathieuDerelle** [comment]
I've just tested sprocket 4 and yeah, it solved the problem. It is still in beta tho

Isn't there an available config somewhere in sprockets 3 in order to exclude some folders ?

**Comment by schneems** [comment]
Sprockets 4 not being released is basically a formality right now. The beta has been stable.


The thing causing this behavior in Sprockets 3: It’s the default lambda added by Sprockets-Rails gem in the precompile config.

It is set to compile everything that isn’t in javascripts or styleshseets which was originally only images. You could also move the folder into the javascripts folder.
