### ISSUE TITLE
add api for SQL EXISTS queries

### ISSUE THREAD

**Issue by eiked** [rails/rails#31269]
It should be easy to write EXISTs queries.

### Steps to reproduce
new feature

### Expected behavior
It should be easy to write EXIST queries

### Actual behavior
Writing EXIST queries needs me to go down into Ariel or resort to raw SQL

### Comment
The EXIST queries are very important.
But the rails query api does not yet have sufficient support for that.

This is an old lasting problem.
It can be addressed via Arel (with some Pain)
but it is not available on the rails query api.

I resort to write the EXIST queries in plain SQL,
but then I'm missing all name aliasing on that.
There should really be a more easy way to write that kind of queries.

---

just some thoughts:

maybe something like:
   Foo.exists(Bar){where(foreign_id:id)}

In that simplistic case: the foreign_id should reference Foo,
and id should reference to Bar, so bar should be the self in that block

But for more complicated cases, we might need something like:
   Foo.exists(Bar){|foo_table, bar_table| where(...)}

---

It was a big step forward to have rails based on Arel,
but this is nowhere orthogonal, yet
some work still needs to be done

### System configuration
**Rails version**:
Rails 5.1.4

**Ruby version**:
ruby 2.4.2p198 (2017-09-14 revision 59899) [x86_64-darwin16]

**Comment by y-yagi** [comment]
Thank you so much for the issue but we don't take feature request on the issue tracker. We recommend you to try to implement the feature and send us a pull request or if you are in doubt if the feature will be accepts ask in Rails Core mailing list for feedback.
