### ISSUE TITLE
Server-side generated JavaScript Responses aren't executed because of default Content Security Policy 

### ISSUE THREAD

**Issue by mrhead** [rails/rails#31273]
I'm not sure if this is a bug or an intended change, but this was working by default in previous versions of Rails. However in `5.2.beta2` Server-side generated JavaScript Responses aren't executed because of default Content Security Policy introduced in https://github.com/rails/rails/pull/31162.

### Steps to reproduce

Create a new Rails app:

```
rails new sjr-test
cd sjr-test
rake db:create db:migrate
```

Add the following files:

```
# config/routes.rb
Rails.application.routes.draw do
  resources :sjrs, only: [:new, :create]
end
```

```
# app/controllers/sjrs_controller.rb
class SjrsController < ApplicationController
  def new
  end

  def create
  end
end
```

```
# app/views/sjrs/new.html.erb
<%= button_to "Create SJR", sjrs_path, remote: true %>
```

```
# app/views/users/create.js.erb
alert("SJR is working!")
```

Then:
1. Start the server
2. Visit http://localhost:3000/sjrs/new
3. Click on the "Create SJR" button

### Expected behavior

You should see a JavaScript alert saying "SJR is working!".

### Actual behavior

No alert is shown and Server-generated JavaScript Response isn't executed because of Content Security Policy. This is the error from JavaScript console:

```
rails-ujs.self-9d0f3ce06afecd4183b5a50580cd7617b5e10fba48d12d3cf53668539f4d77db.js:244 Refused to execute inline script because it violates the following Content Security Policy directive: "script-src 'self' https:". Either the 'unsafe-inline' keyword, a hash ('sha256-djTI7ayTUPgKSs+qoOHPSkHb3BZ3yW1FOMkS7/k/vzw='), or a nonce ('nonce-...') is required to enable inline execution.
```

### System configuration
**Rails version**: 5.2.0.beta2

**Ruby version**: 2.4.1p111

**Comment by rafaelfranca** [comment]
cc @pixeltrix

**Comment by pixeltrix** [comment]
@mrhead the quick fix is to add `:unsafe_inline` to the `script_src` line in your CSP. Investigating whether there's a secure solution we can do that leverages nonce values to handle this automatically.

**Comment by Yanchek99** [comment]
I am encountering the same issue but am unclear on the quick fix suggested by @pixeltrix. Where does the unsafe_inline get added to? Does that belong to application.html.erb?  Sorry in advanced for lack of understanding.

**Comment by pixeltrix** [comment]
@Yanchek99 there's a new initializer called `content_security_policy.rb` - in there you'll find a line like this:

```
p.script_src :self, :https
```

change it to:

```
p.script_src :self, :https, :unsafe_inline
```

**Comment by Yanchek99** [comment]
@pixeltrix Thank you that helped!  So is this simply a workaround fix? Or is this the preferred setup for Content Security Policy? Just curious if I am violating best practices here or not.

**Comment by pixeltrix** [comment]
@Yanchek99 the default policy generated is to nullify the effect of XSS script injection - I'm working on a way of transparently adding a nonce attribute to server-rendered javascript that removes the need to add `:unsafe_inline`.

**Comment by mokolabs** [comment]
FYI... I just ran into this same issue when using Action Mailer previews.

I'm unable to switch from the plain html email to the text email using the dropdown in the page header. Nothing happens after selecting a value from the dropdown and there is a CSP-related error in the console.

**Comment by mokolabs** [comment]
Also, I can confirm that the fix suggested @pixeltrix works in this case too.

**Comment by Fudoshiki** [comment]
`:unsafe_inline ` is temp solution to fix, but https://securityheaders.io warning
```
Content-Security-Policy  This policy contains 'unsafe-inline' which is dangerous in the script-src directive.
```
best way use `nonce`
https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/script-src
