### ISSUE TITLE
Indices are not created when adding columns

### ISSUE THREAD

**Issue by orhantoy** [rails/rails#31281]
### Steps to reproduce

```ruby
# Migration 0
class CreateUsers < ActiveRecord::Migration[5.2]
  def change
    create_table :users do |t|
      t.timestamps null: false
      t.string :name
      t.string :email, null: false, index: { unique: true }
    end
  end
end

# Migration 1
class AddUsername < ActiveRecord::Migration[5.2]
  def change
    change_table :users do |t|
      t.string :username, index: true
    end
  end
end

# Migration 2
class AddUserSlug < ActiveRecord::Migration[5.2]
  def change
    add_column :users, :slug, :string, index: { unique: true }
  end
end
```

### Expected behavior

- I expect Migration 1 to create a `username` column + an index on the column.
- I expect Migration 2 to create a `slug` column + unique index on the column.

### Actual behavior

- Migration 1 creates the `username` column **but not** the index.
- Migration 2 creates the `slug` column **but not** the unique index.

---

The behavior is unchanged from 4.2 to 5.2 beta. So I guess this is how migrations have always been. But for me it seems logical that Migration 1 and 2 should have added an index, especially Migration 1 as `create_table` and `change_table` appears to have very similar interfaces.

Another way to handle this could be to raise an exception when `index` is passed as an option and it actually doesn't add an index - currently you could think you are adding a unique index (like in Migration 1 (modified with `index: { unique: true }` and Migration 2) because `./bin/rails db:migrate` will not fail.

**Comment by yahonda** [comment]
I think this is an expected behavior explained at https://github.com/rails/rails/pull/20616#issuecomment-144870870

**Comment by orhantoy** [comment]
Both `add_column` [API docs](http://api.rubyonrails.org/v4.2/classes/ActiveRecord/ConnectionAdapters/SchemaStatements.html#method-i-add_column) and `column` [API docs](http://api.rubyonrails.org/v4.2/classes/ActiveRecord/ConnectionAdapters/Table.html#method-i-column) link to http://api.rubyonrails.org/v4.2/classes/ActiveRecord/ConnectionAdapters/TableDefinition.html#method-i-column as the reference, where `index` is listed as an option.

So we should either

1. keep the behavior as it is and update the docs to clarify the supported options
2. raise an exception when using unsupported options like `index` in `change_table` and `add_column`
3. add support for adding indices in `change_table` and `add_column`

To make matters more inconsistent I just noticed that adding indices are supported if you're using `references` in a `change_table`-block.
