### ISSUE TITLE
new_framework_defaults.rb as an initializer doesn't actually work as an upgrade path

### ISSUE THREAD

**Issue by albus522** [rails/rails#31285]
If your app uses any gem that augments the behavior of ActiveRecord or ActionController that references `ActiveRecord::Base` or `ActionController::Base` outside of an `ActiveSupport.on_load` block, the new_framework_defaults.rb initializer has no effect. This appears to happen because the framework initializers that setup the `on_load` to copy the app config to the individual frameworks run before `config/initializer/*` files. Because the gems have already triggered the load the app config is copied immediately before the initializer files have set the values.

### Steps to reproduce
Super simple concrete example
- Generate a 5.0 app which has new_framework_defaults.rb
- Load a console and check `ActiveRecord::Base.belongs_to_required_by_default` and it will be as the initializer has it set.
- Add `ActiveRecord::Base` after `Bundler.require(*Rails.groups)` line in application.rb to simulate a gem that augments or uses ActiveRecord.
- Load a console and check `ActiveRecord::Base.belongs_to_required_by_default` which will now show as `nil`

### Expected behavior
The upgrade config values from new_framework_defaults.rb need to actually be applied.

### Actual behavior
The upgrade config is not actually applied

### System configuration
**Rails version**: Rails 5+ as long as new_framework_defaults.rb is setting something other than a default

**Ruby version**: Tested on 2.4.2 but likely an issue across the board

This does have a broader impact in that any app that uses an initializer to set `Rails.application.config.action_controller` or `Rails.application.config.active_record` and is using a gem that triggers the autoload of those classes before the rails initialization kicks off isn't doing what they think it is doing.

**Comment by rafaelfranca** [comment]
Thank you for the report. This is a bug in the gems that needs to be fixed on them.

**Comment by albus522** [comment]
I hole heartedly disagree. You are providing an upgrade path that only pretends to work for real world apps

**Comment by lazyatom** [comment]
I reported a similar issue on FriendlyID (norman/friendly_id#823), and while I in principle about gems needing to understand and respect what happens when ActiveRecord initialises itself, it seems like there's an opportunity for Rails to be pragmatic here too. Even just renaming the `new_framework_defaults.rb` to `0_new_framework_defaults.rb` and thus making it load before other initialisers would help.

**Comment by pjurewicz** [comment]
I addressed this issue in a [blogpost](https://blog.arkency.com/i-do-not-blindly-trust-setting-things-in-new-framework-defaults-initializers-anymore/)
