### ISSUE TITLE
Credentials cleared when running credentials:edit

### ISSUE THREAD

**Issue by spdawson** [rails/rails#31286]
### Steps to reproduce

1. Run `bundle exec rails credentials:edit`, and add some well-formed YAML to the credentials file
2. Run `bundle exec rails credentials:show`, and observe the just-added YAML credentials
3. Run `bundle exec rails credentials:edit` a second time

### Expected behavior

The credentials loaded in the `$EDITOR` should contain the entries added in step 1.

### Actual behavior

The credentials are reset to the default "empty" condition, containing `secret_key_base` entry only.

My hunch is that the `IO` backing the temporary file might need to be `flush`ed around line [62](https://github.com/rails/rails/blob/master/activesupport/lib/active_support/encrypted_file.rb#L62) in `ActiveSupport::EncryptedFile#writing`; this hypothesis is based on a quick skim through the source code &mdash; I have no evidence to support it at this stage.

### System configuration

* Rails v5.2.0.beta2
* Ruby 2.4.2
* `EDITOR` set to either Emacs, GNU nano, or gedit

**Comment by y-yagi** [comment]
Thanks for your report. I can confirm the issue. I will fix.

**Comment by kaspth** [comment]
Damn, sorry about that! Good we have @y-yagi 😊

**Comment by dimerman** [comment]
Q: when was this fix deployed? I'm running `Rails 5.2.0.beta2` and I see this happening.

**Comment by swrobel** [comment]
@dimerman not on any released gem, you'd have to use Rails master from git

**Comment by saurabhbhatia** [comment]
Was this not released in ```Rails 5.2.0.RC1``` I'm facing the same issue in RC1 ?

**Comment by kaspth** [comment]
@saurabhbhatia it's in 5.2.0.rc1 as the commit says: https://github.com/rails/rails/commit/f7e3c686685fb89e67293440d24356f93fa34847 :)

Try replicating in a `rails new` test app uploaded to GitHub.

**Comment by ifellinaholeonce** [comment]
Hey - just throwing this out there. We were having the same issues. We edited in vim instead of sublime and the changes seem to not get wiped. I'm not sure if this offers anything helpful.

**Comment by swrobel** [comment]
@ifellinaholeonce make sure your `EDITOR` is `subl -w` otherwise control will immediately return to the terminal you launched `credentials:edit` rather than waiting (`-w`) for the Sublime to close.

**Comment by kaspth** [comment]
@ifellinaholeonce, @swrobel is correct about needing `-w`. Looks like we only display that if `$EDITOR` isn't set https://github.com/rails/rails/blob/79aa6158b8d56a4df3099bc111e0a12c24763f22/railties/lib/rails/command/helpers/editor.rb#L11

Feel free to make sure we also describe it in `bin/rails credentials --help` (we also have to make sure that works over `bin/rails credentials:help`) and the `bin/rails encrypted` commands as well.

**Comment by ghepting** [comment]
This was what I was missing in my .bash_profile, too. Thanks for the helpful thread :)

For others stumbling onto this, this is the line in my .bash_profile to use Atom:

`export EDITOR="/usr/local/bin/atom --wait"`

**Comment by Randall-Coding** [comment]
This problem persists today.  It would be helpful for there to be a visible warning or error if the editor is not set to "wait".  

I thought silent errors like this are usually against Rails ethos.
