### ISSUE TITLE
ActiveSupport::EncryptedFile::MissingKeyError in default generated app

### ISSUE THREAD

**Issue by calebthompson** [rails/rails#31283]
### Steps to reproduce

(Guidelines for creating a bug report are [available
here](http://guides.rubyonrails.org/contributing_to_ruby_on_rails.html#creating-a-bug-report))

```bash
$ rails --version
Rails 5.2.0.beta2
$ rails new rails52
$ cd rails52
$ grep -r "config.require_master_key" *
config/environments/production.rb:  # config.require_master_key = true
$ ls config/master.key
config/master.key
$ bundle
# clipped
$ RAILS_ENV=production rake environment
$ rm config/master.key
$ RAILS_ENV=production rake environment
rake aborted!
ActiveSupport::EncryptedFile::MissingKeyError: Missing encryption key to decrypt file with. Ask your team for your master key and write it to /Users/caleb.thompson/code/rails52/config/master.key or put it in the ENV['RAILS_MASTER_KEY'].
```

### Expected behavior

I have not specified that I am using the master key (the line in config/production.rb is commented out). I should be able to not have config/master.key and loading the environment should work correctly.

### Actual behavior

I get the `ActiveSupport::EncryptedFile::MissingKeyError` error, which says that I do need the master key.

This happens for development as well, but the config isn't specified in that environment file by default. The value for `config.require_master_key` by default should be false.

### System configuration
**Rails version**: 5.2.0.beta2

**Ruby version**: ruby 2.4.2p198 (2017-09-14 revision 59899) [x86_64-darwin16]

**Comment by y-yagi** [comment]
Is there `Rails.application.credentials` method in `config/storage.yml`?
The default `config/storage.yml` uses `credentials` method, and `credentials` method execute key check.  

If you have any, please try to remove it.

**Comment by calebthompson** [comment]
@y-yagi Yes, they're in the commented out yaml. Removing those lines fixes this. I suppose yaml still evaluates ERB even when commented out, so Rails ought not include those lines in the generated app?

**Comment by calebthompson** [comment]
I'm happy to take a whack at removing that if you'd like.

**Comment by y-yagi** [comment]
Rails 5.2 recommends using credentials. Therefore, in my personal opinion, that is fine as is.

@kaspth  What do you think?

**Comment by calebthompson** [comment]
According to https://github.com/rails/rails/pull/28038#pullrequestreview-23045478 it should only be when rake secrets:setup is run. Cc @schneems @kaspth

**Comment by Yanchek99** [comment]
Also noticing this exception gets thrown when running. `rails test` from a non development environment (ex. ci).  Assuming this is because master.key is not present.  Is the preferred approach to set the master key environment variable for CI? Or disable encryption for the test configuration?

**Comment by kaspth** [comment]
@calebthompson encrypted secrets, `secrets:setup` and `secrets:edit`, were optional in Rails 5.1. The new credentials feature in 5.2, used via `credentials:edit`, is generated by default. 

@Yanchek99 you definitely shouldn't have to include the encryption key to run your tests on CI. It's a bug, we have to fix 😊

@y-yagi looks like this is the culprit: https://github.com/rails/rails/blob/7609ca08ce5000689838eeb04ed37084bf364f78/activesupport/lib/active_support/railtie.rb#L52-L62

We don't prevent environments that don't require a master key from raising, we just raise if the key is missing in environments that do. We could copy over the config to a `raise_if_missing_key: config.require_master_key` when instantiating an encrypted configuration in `encrypted`. People will then have to pass that manually when doing custom instantiation. I'll look into it tomorrow unless you want to take a stab at it.

**Comment by schneems** [comment]
my end goal is being able to boot someone’s Rails app in a container. Right now it can be done with zero steps (give us the app). Adding this command means there’s now an extra step as it doesn’t look like it’s something we can generate for a Rails app (since it needs to match local values). 

Thanks for taking a look. I would usually be able to dive in with some code in a PR, but I’m having a baby literally any day now.

**Comment by y-yagi** [comment]
@kaspth Gotcha. I will take a stab at it. If you have already fixed, please ignore ;)
