### ISSUE TITLE
Respect gems.rb for Bundler 2.0 and higher (do not tie to Gemfile)

### ISSUE THREAD

**Issue by nbulaj** [rails/rails#31295]
Hi. Anyone knows, [that Bundler 2.0 will use `gems.rb` instead of `Gemfile`](https://depfu.com/blog/2017/09/06/gemfiles-new-clothes) for the project dependencies. Actually, it supports `gems.rb` starting from current version (1.16) and everyone can (but not _must_) use it.

So I think it will be great to support this feature in Rails. Currently it tied to `Gemfile` in [bundle.tt] and [boot.rb.tt](https://github.com/rails/rails/blob/master/railties/lib/rails/generators/rails/app/templates/config/boot.rb.tt#L1) templates, so if anyone will try to migrate to new dependencies format - he will get an error while trying to run an application. The workaround is to manually rename `Gemfile` to `gems.rb` in `bin/bundle` and `config/boot.rb`.

Can't find any related issues so I created this one.

### Steps to reproduce

Install Bundler _1.16_, rename `Gemfile` to `gems.rb` in any RoR project, run `bundler install` and run `rails server`.

### Expected behavior

> => Booting Puma
> => Rails 5.1.4 application starting in development 
> => Run `rails server -h` for more startup options
> Puma starting in single mode...
> * Version 3.11.0 (ruby 2.4.1-p111), codename: Love Song
> * Min threads: 5, max threads: 5
> * Environment: development
> * Listening on tcp://0.0.0.0:3000
> Use Ctrl-C to stop

### Actual behavior

> /home/nbulai/projects/dummy_app/Gemfile not found

### System configuration
**Rails version**: any

**Ruby version**: any

**Comment by georgeclaghorn** [comment]
Thanks for the heads-up, but we don’t take feature requests here. PR welcome! :smile:

**Comment by nowakov** [comment]
@georgeclaghorn As of July 2018, what is your opinion on implementing `gems.rb` support? I can make this change and provide a PR, however not sure if it's needed.

**Comment by rafaelfranca** [comment]
Our opinion right now is that we don't agree with the change and maybe we are not going to support. We are still discussing this.

**Comment by nowakov** [comment]
@rafaelfranca ok, thanks for your answer. Can I ask why you don't agree with it? Do you have any open discussion about it or a blogpost?(links)
