### ISSUE TITLE
rails credentials:edit does not allow user to save changes

### ISSUE THREAD

**Issue by Yanchek99** [rails/rails#31303]
### Steps to reproduce
`export EDITOR=vi`
`rails credentials:edit`
Which opens the credentials file and then using vim I make my edits and `wq`
`rails credentials:edit`
Observe the changes made are not saved and what appears is the original default file.

### Expected behavior
Changes made and saved from vi editor should persist to the actual credentials.yml.enc file

### Actual behavior
Changes are never actually saved

### System configuration
On macOS High Sierra 10.13.1
**Rails version**:5.2.0.beta2
**Ruby version**:2.4.2

**Comment by y-yagi** [comment]
Thanks for your report. This issue fixed by #31287. Please wait the next release. Thanks!

**Comment by modusss** [comment]
I'm experiencing the same issue with Rails 6.0.3 and Ruby 2.7.0

**Comment by hudarsono** [comment]
> I'm experiencing the same issue with Rails 6.0.3 and Ruby 2.7.0, but the answer is to close the window in order to save.

Wow, that exactly solved my problem.
