### ISSUE TITLE
::destroy no longer throws RecordNotFound

### ISSUE THREAD

**Issue by kddeisz** [rails/rails#31301]
This may be desirable, but it's odd in a minor version release. It breaks the default behavior of a lot of standard controllers, as in:

```ruby
class ModelsController < ApplicationController
  def destroy
    Model.destroy(params[:id])
    head :no_content
  end
end
```

I expect this to return a 404 if it's not found. Looks like this behavior was introduced in https://github.com/rails/rails/commit/358360198e623229495b7175a2b3a0fe96a543ac. 

### Steps to reproduce

```ruby
gem "bundler", "< 1.16"

begin
  require "bundler/inline"
rescue LoadError => e
  $stderr.puts "Bundler version 1.10 or later is required. Please update your Bundler"
  raise e
end

gemfile(true) do
  source "https://rubygems.org"

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  gem "rails", "= 5.2.0.beta2"
  gem "sqlite3"
end

require "active_record"
require "minitest/autorun"
require "logger"

# This connection will do for database-independent bug reports.
ActiveRecord::Base.establish_connection(adapter: "sqlite3", database: ":memory:")
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table(:users, force: true) {}
end

class User < ActiveRecord::Base
end

class BugTest < Minitest::Test
  def test_association_stuff
    assert_raises(ActiveRecord::RecordNotFound) do
      User.destroy('foobar')
    end
  end
end
```

### Expected behavior

It should throw a `RecordNotFound`.

### Actual behavior

It doesn't.

### System configuration
**Rails version**: 5.2.0.beta2
**Ruby version**: 2.4.2

**Comment by kamipo** [comment]
Thanks for the report. Yeah, the compatibility should not be broken. I've fixed it in 0dc3b6535dfb8127f568bb4abc2fb09118ce4b96.

**Comment by matthewd** [comment]
@kamipo could those methods be changed to use `find(ids).each(&:destroy)` instead, so they continue raising when given invalid IDs, as their tests originally showed, and just stop making changes before checking all the records exist?

(I would comment on the PR instead of this only-slightly-related issue, but there isn't one)

**Comment by kamipo** [comment]
ah... using `find(ids).each(&:destroy)` makes sense.
I'll create a PR that checking all the records exist before making changes.
