### ISSUE TITLE
Configure Content Security Policy for Action Cable

### ISSUE THREAD

**Issue by olimart** [rails/rails#31309]
### Steps to reproduce

Generate a new app (5.2.0.beta2) with Action Cable.

### Expected behavior

when generating a fresh application the content security policy should add directive to `connect_src` 
to work with Action Cable.

Should skip if action_cable is ignored when generating a new app.

### Actual behavior

Content security policy has no instructions for `connect-src` (which is fine as the default setting), however there should be instructions to turn it on for Action Cable.

For instance I added the following in `config/initializers/content_security_policy.rb`:

```
p.connect_src :self
```

but it does not work.

In `development.rb` I have

```
config.action_cable.url = 'ws://localhost:5000/cable'
config.action_cable.allowed_request_origins = [ 'http://localhost:5000', 'http://127.0.0.1:5000' ]
```

### System configuration
**Rails version**: 5.2.0.beta2

**Ruby version**: 3.3.1

**Comment by olimart** [comment]
Hi @pixeltrix I see that you worked on the Content security policy, maybe you can shed some light. Thanks.

**Comment by jeremy** [comment]
Related https://github.com/w3c/webappsec-csp/issues/7

**Comment by olimart** [comment]
https://github.com/w3c/webappsec-csp/issues/7#issuecomment-158688999

> As an example, it would be useful to serve a page at http://localhost:3000/ using connect-src 'self', and have this behave as if the CSP (under current rules) had specified connect-src 'self' ws://localhost:3000.

If the aforementioned configuration is not possible not sure how people use Action Cable with a security policy in **development**.

Thanks @Jeremy for the link. The issue is quite old so I doubt this will change anytime soon.

**Comment by guilleiguaran** [comment]
just to confirm, so we need to have `p.connect_src :self, :https, 'ws://localhost:3000'` for ActionCable in development?

**Comment by olimart** [comment]
@guilleiguaran getting `EvalError: Refused to evaluate a string as JavaScript because 'unsafe-eval' is not an allowed source of script in the following Content Security Policy directive: "script-src 'self' https:".`

**Comment by pixeltrix** [comment]
@olimart that error suggests that there's an eval somewhere in the JavaScript code - was there a line specified so we can tell whether it's your code or Action Cable's JavaScript code.

**Comment by olimart** [comment]
@pixeltrix  Turned out that the eval issue comes from `rack-mini-profiler` gem loading jQuery externally so never mind.

@guilleiguaran is right, this seems to work though when you set `p.connect_src :self, :https, 'ws://localhost:3000'` in content security policy.

At then end I guess it'a matter of documenting this in ActionCable docs. Will open a PR separately. Thank you all.

**Comment by kieraneglin** [comment]
Where does this leave system tests?  For use with Webpacker (Vue) and ActionCable, my CSP includes this: `p.connect_src :self, :https, 'http://localhost:3035', 'ws://localhost:3035', 'ws://localhost:3000'`

However, this doesn't work in the test environment, since the port changes each time.  Is this a Rails CSP concern, or should I move this to StackOverflow?

**Comment by guilleiguaran** [comment]
@kieraneglin what port change during tests? Action Cable one?

**Comment by kieraneglin** [comment]
@guilleiguaran yes.  This was confirmed by accessing the browser during a system test and checking the value of `window.App.cable`.  The cable port matched the browser port.

Without my workaround above, the console would repeatedly error that it could not connect to the WS.

**Comment by pedromartinez** [comment]
Also having this issue. Need to somehow whitelist all ports on localhost.

**Comment by deanius** [comment]
I also would like to whitelist all ports on localhost.
