### ISSUE TITLE
`0 % <ActiveSupport::Duration>` returns unexpected result

### ISSUE THREAD

**Issue by moveson** [rails/rails#31302]
### Steps to reproduce

From the Rails console:
`>> a = 0 % 1.second`
`>> a`
`#>`

### Expected behavior
`a` should report its existence as `0`.

### Actual behavior
`a` returns nothing at all: No `0`, no `nil`, no indication of what it is. However,

`>> a.zero?`
`#> true`

### System configuration
**Rails version**: 5.1.4

**Ruby version**: 2.3.5

**Comment by georgeclaghorn** [comment]
It returns an `ActiveSupport::Duration` with no parts:

```
> a = 0 % 1.second


> a.class
ActiveSupport::Duration

> a.parts
{}
```

`ActiveSupport::Duration#inspect` returns an empty string when the receiving object has no parts. Tricky!

**Comment by moveson** [comment]
That's interesting, and good to understand. But it does violate principle of least surprise.

```
>> a = 3 % 2
#> 1
>> a = 3 % 1
#> 0
>> a = 3 % 2.seconds
#> 1.0 second
>> a = 3 % 1.second
#> "" # Not 0.seconds?

```

**Comment by kinnrot** [comment]
Looks like the problem is within ActiveSupport::Duration.build(0) compared to ActiveSupport::Duration.seconds(0)

build method reject all zero values, Maybe it should not reject the smallest unit, seconds.
