### ISSUE TITLE
Group uses wrong type when column name exists on selecting table

### ISSUE THREAD

**Issue by trevorrjohn** [rails/rails#31304]
### Steps to reproduce

Using postgresql

`gem pg -v 0.18`

Using this schema:

```ruby
  # db/schema.rb
  create_table "bars", force: :cascade do |t|
    t.string "foo"
  end
  create_table "blahs", force: :cascade do |t|
    t.integer "foo"
    t.integer "bar_id"
  end
```

```ruby
bar = Bar.create(foo: "some string")
Blah.create(foo: 2, bar: bar)
Bar.joins(:blah).group('bars.foo').count
```

### Expected behavior

```ruby
Bar.joins(:blah).group('bars.foo').count
#=> {"some string"=>1}
```

### Actual behavior

```ruby
Bar.joins(:blah).group('bars.foo').count
#=> {0=>1}
```

This does work in Rails 5.0.0 to 4.2

### System configuration
**Rails version**:
5.0.1 - 5.1.4
**Ruby version**:
2.3.3

**Comment by trevorrjohn** [comment]
I have created an example app with a failing spec.

<https://github.com/trevorrjohn/group-bug-example>

**Comment by trevorrjohn** [comment]
I am pretty sure this changed caused this bug: https://github.com/rails/rails/compare/master...aranair:25595#diff-6c8fd220c92c2b25aa29891b59d00c04R279

**Comment by trevorrjohn** [comment]
I did some more digging and I think this is the correct commit that broke the existing behavior https://github.com/rails/rails/commit/a45363a2fb53e0a016f33dd211c00b5d81764379

**Comment by fillman** [comment]
You have an error in your schema. 
`name` is integer and it is converted into integer while you pass it a string on create event.
If you change like this, all the tests will work.

```ruby
create_table "bars", force: :cascade do |t|
-    t.integer "name"
+    t.string "name"
```

```ruby
# Your test output
vagrant@rails-dev-box:/vagrant/group-bug-example$ bin/rake test
Run options: --seed 6585

# Running:

.

Finished in 0.191003s, 5.2355 runs/s, 10.4711 assertions/s.
1 runs, 2 assertions, 0 failures, 0 errors, 0 skips
```

PS: I also had to change expectation to `'42' => 1` since 42 is a string too.

**Comment by trevorrjohn** [comment]
@fillman the whole point is that I have different types on the two different tables. The bug is that it uses the type from the wrong table. I have created a failing test here as well: 

https://github.com/trevorrjohn/rails/commit/adf6dc8a9ff770275354d5718ce6ba0d76710813

**Comment by trevorrjohn** [comment]
@fillman I changed my example https://github.com/trevorrjohn/rails/commit/7e0240d19a5506f46e439a7b37fe003fd85d1778 to be more like my actual use case. Basically I have one table with an id that is a uuid and another table that has an integer id, when I join them and group by id it gets the type from the selecting table not from the joined table and it tries to cast the uuid as an integer.

**Comment by tradeli** [comment]
Maybe this is related #31196

**Comment by trevorrjohn** [comment]
@tradeli yes I will close this in favor of #31196
