### ISSUE TITLE
Minitest with Rails 5.2.0 - Uninitialized constant Minitest::Rails::TestUnit (NameError)

### ISSUE THREAD

**Issue by tomrossi7** [rails/rails#31324]
While using `Ruby 2.3.3` and upgrading the Rails gem from `5.1.4` to `5.2.0.beta2`, rake fails:

```
$ rake
.../gems/railties-5.2.0.beta2/lib/minitest/rails_plugin.rb:16:in `plugin_rails_options': uninitialized constant Minitest::Rails::TestUnit (NameError)
	.../gems/ruby-2.3.3@donortools2/gems/minitest-5.10.3/lib/minitest.rb:201:in `block (2 levels) in process_args'
	.../gems/ruby-2.3.3@donortools2/gems/minitest-5.10.3/lib/minitest.rb:199:in `each'
	.../gems/minitest-5.10.3/lib/minitest.rb:199:in `block in process_args'
	.../.rvm/rubies/ruby-2.3.3/lib/ruby/2.3.0/optparse.rb:1062:in `initialize'
	.../gems/minitest-5.10.3/lib/minitest.rb:169:in `new'
	.../gems/minitest-5.10.3/lib/minitest.rb:169:in `process_args'
	.../gems/minitest-5.10.3/lib/minitest.rb:123:in `run'
	.../gems/minitest-5.10.3/lib/minitest.rb:63:in `block in autorun'
```

I can't tell if the problem is with`minitest 5.10.3` or `Rails 5.2.0.beta2`?

**Comment by jeremy** [comment]
https://github.com/rails/rails/blob/master/railties/lib/minitest/rails_plugin.rb#L4-L5

Those requires pull in Rails::TestUnit::Runner, so resolving the Rails::TestUnit constant within the Minitest module should resolve to the toplevel ::Rails::TestUnit.

The error message suggests that there's some existing Minitest::Rails constant, though, and we're resolving TestUnit against that, which fails. To fix, we should reference ::Rails::TestUnit instead of Rails::TestUnit in the plugin.

You'll need to hop in a debugger and see what's happening to figure it out. I'd guess you have another minitest plugin on your system that introduces a Minitest::Rails constant. Maybe https://github.com/ordinaryzelig/minispec-rails ?

**Comment by tomrossi7** [comment]
@jeremy thanks! I found the culprit, the gem minitest-rails-capybara.

Incidentally, I found it by eliminating minitest related gems one at a time. I dropped into debugger on the offending line, but couldn't figure out how to see what gem was using the module. I did `self`, `self.ancestors`, but neither gave me any clues. Is there something I am missing that would have made it easier to figure out who had called the line?

**Comment by jeremy** [comment]
The smoking gun is if there's a ::Minitest::Rails constant defined at that point. Unwinding what defined the constant is tricky since Ruby doesn't tell us a source location directly. You can look at ::Minitest::Rails methods in the debugger, though, and ask for `.method(:whatever_method_name).source_location` to pin it down. Checking `$"` ($LOADED_FEATURES) is a good route too.

**Comment by tomrossi7** [comment]
Thanks for taking the time to help @jeremy!

**Comment by atstockland** [comment]
I have experience this too.  I suspect minitest-rails gem is causing...but, haven't proven that or figured out out if I can fix it, yet.

**Comment by mode-x** [comment]
What is the solution to this issue? I am stuck with this error.

**Comment by tomrossi7** [comment]
@mode-x I removed the minitest-rails-capybara gem and that resolved my issue...

**Comment by atstockland** [comment]
I removed Minitest-Rails gem and that fixed it for me.  I’m back to bare bones, stock Minitest and loving it!

**Comment by mode-x** [comment]
Removing minitest-rails-capybara took care of it for me

**Comment by tomrossi7** [comment]
On a related note, I had to lock the minitest version in at 5.10.3. The latest version was causing an error.

**Comment by taq** [comment]
Just got this error after upgrading to Rails 5.2.0, released yesterday. 

I was not using `minitest-rails-capybara` but I'm using the `minitest-rails` to use specs etc. So, while it stopped to gives the `Uninitialized constant`, now I don't have, for example, the `describe` method (which was an alias for `context`) anymore. I'm using minitest 5.11.3 and minitest-rails 3.0.0, which seems to be the latest versions. 

The error happens on `gems/railties-5.2.0/lib/minitest/rails_plugin.rb:16`, which has this code:

```
Rails::TestUnit::Runner.attach_before_load_options(opts)
```

The complete traceback:

```
Traceback (most recent call last):         
        8: from /home/taq/.rvm/gems/ruby-2.5.0/gems/minitest-5.11.3/lib/minitest.rb:63:in `block in autorun'                                                                 
        7: from /home/taq/.rvm/gems/ruby-2.5.0/gems/minitest-5.11.3/lib/minitest.rb:123:in `run'                                                                             
        6: from /home/taq/.rvm/gems/ruby-2.5.0/gems/minitest-5.11.3/lib/minitest.rb:169:in `process_args'                                                                    
        5: from /home/taq/.rvm/gems/ruby-2.5.0/gems/minitest-5.11.3/lib/minitest.rb:169:in `new'                                                                             
        4: from /home/taq/.rvm/rubies/ruby-2.5.0/lib/ruby/2.5.0/optparse.rb:1062:in `initialize'                                                                             
        3: from /home/taq/.rvm/gems/ruby-2.5.0/gems/minitest-5.11.3/lib/minitest.rb:201:in `block in process_args'                                                           
        2: from /home/taq/.rvm/gems/ruby-2.5.0/gems/minitest-5.11.3/lib/minitest.rb:201:in `each'                                                                            
        1: from /home/taq/.rvm/gems/ruby-2.5.0/gems/minitest-5.11.3/lib/minitest.rb:203:in `block (2 levels) in process_args'                                                
/home/taq/.rvm/gems/ruby-2.5.0/gems/railties-5.2.0/lib/minitest/rails_plugin.rb:16:in `plugin_rails_options': uninitialized constant Minitest::Rails::TestUnit (NameError)  
```
I'm trying to find more info, but do you guys have a clue about this? Thanks!

**Comment by taq** [comment]
Hey, I just edited the `gems/railties-5.2.0/lib/minitest/rails_plugin.rb` file and commented the 

```
Rails::TestUnit::Runner.attach_before_load_options(opts)
```

line and it worked!

**Comment by maddox** [comment]
@taq there's an [issue opened](https://github.com/blowmage/minitest-rails/issues/209) on the `minitest-rails` repo regarding this. It seems that it is up to the gem authors to update their gems. Though there's been no response on the issue, which was opened in Dec of 2017.

**Comment by taq** [comment]
Thanks @maddox!

**Comment by grosser** [comment]
```
# https://github.com/rails/rails/issues/31324
if ActionPack::VERSION::STRING >= "5.2.0"
  Minitest::Rails::TestUnit = Rails::TestUnit
end
```

fix in railties-5.2.0/lib/minitest/rails_plugin.rb:16 should be using `::Rails`

**Comment by y-yagi** [comment]
Sorry for the inconvenience. I fixed this issue with 686f4f3. And backported to 5-2-stable 4887f97.

**Comment by maddox** [comment]
❤️ thanks @y-yagi.

**Comment by mauditecandela** [comment]
thanks @y-yagi! this is also keeping us from updating to rails 5.2.0, any idea when this will be merged? :) <3

**Comment by taq** [comment]
@mauditecandela meanwhile I edited `gems/railties-5.2.0/lib/minitest/rails_plugin.rb` and replaced `Rails::TestUnit::Runner.attach_before_load_options(opts)` with `::Rails::TestUnit::Runner.attach_before_load_options(opts)`, it's working on a new 5.2 project.

**Comment by mauditecandela** [comment]
Thanks @taq yeah, that worked for me as well, but I don't know how to set up in a FOSS project that uses travis. Any hints/ideas/advices? :)

**Comment by grosser** [comment]
see monkeypatch above

**Comment by mauditecandela** [comment]
Thanks @grosser I added to an initializer -- it's my first patch like this, therefore my questions. ^^

**Comment by grosser** [comment]
You'll soon get used to the dark side ;)
