### ISSUE TITLE
First request on Windows is extremely slow

### ISSUE THREAD

**Issue by schlamar** [rails/rails#31337]
### Steps to reproduce

- Install Redmine on Windows
- Open Redmine in browser
- Open Redmine in browser again

### Expected behavior
Similar loading times for both requests.

### Actual behavior
The first request is extremely slow (>5s) compared to the second one (<1s). Subsequent requests are fast, too.

### System configuration
**Rails version**: 4.2.8

**Ruby version**: rubyinstaller-2.4.2-2-x64

This could be the same issue as #25805. The comments suggest that the issue is not really resolved.

**Comment by schlamar** [comment]
I can confirm that the workaround in #25805 is actually working. I have put 

    require 'openssl'
    OpenSSL::Random.random_bytes(1)

in the `boot.rb` file and the slow request is gone. 

The boot time of the application is not slower as @vipulnsward has suggested in https://github.com/rails/rails/issues/25805#issuecomment-232537039. His conclusion is wrong.

**Comment by vipulnsward** [comment]
Lets track on https://github.com/rails/rails/issues/25805 . I have reopened that.

**Comment by schlamar** [comment]
Some numbers for you.

If I put 

    t = Time.now
    require 'openssl'
    OpenSSL::Random.random_bytes(1)
    p Time.now - t

in `boot.rb` I get 0.49s.

If I put this in `application.rb` after `Bundler.require(...)` I get 3.7s.

If it is in both files I get 0.5s and 0.0s.
