### ISSUE TITLE
Rails.application.credentials on development

### ISSUE THREAD

**Issue by crigor** [rails/rails#31333]
Should Rails.application.credentials load the credentials even if config.require_master_key is false?

Rails.application.secrets doesn't load the secrets if config.read_encrypted_secrets is false.

### Steps to reproduce

Add some credentials using rails credentials:edit.

```
foo: bar
```

On the rails console using the development environment, run Rails.application.credentials.

### Expected behavior

I don't know what the expected behavior is. But Rails.application.secrets on 5.1 won't read the encrypted secrets if config.read_encrypted_secrets isn't set.

### Actual behavior

Rails.application.credentials.foo is set to bar. If this is intended behavior, there seems to be a danger of using the production credentials in development mode.

### System configuration
**Rails version**: Rails 5.2.0.beta2 (c383c4142a1c)

**Ruby version**: Ruby 2.4.2p198

**Comment by y-yagi** [comment]
`require_master_key` is an option for specifying behavior when the master key does not exist. 
Therefore, unlike `read_encrypted_secrets`, `require_master_key` does not relate that load credentials. 
If you don't want to expose credentials in development, please remove the master key. Thanks.
