### ISSUE TITLE
5.2.0.beta 'order' SQL whitelist doesn't treat 'lower(safe_thing)' as safe

### ISSUE THREAD

**Issue by rst** [rails/rails#31342]
### Steps to reproduce

In a 5.2.0.beta2 Rails app, with an AR model (say, "Blog") with a string attribute (say, "name"), issue a query such as
```ruby
   Blog.order("lower(name)")
```

### Expected behavior

This idiom for a case-insensitive sort should be recognized as safe; likewise for variants such as
```ruby
   Blog.order("lower(blogs.name) asc")
```

### Actual behavior

The new SQL-fragmenting whitelist code does not recognize it as safe, and issues an "unsafe query method" deprecation warning, suggesting wrapping the fragment in an invocation of `Arel.sql()`.  

I understand not wanting to open the Pandora's box of a full SQL parse, but the code already does quite a bit more than bare column names, and allowing 'lower(' (and possibly 'LOWER(') as prefixes on the current COLUMN_NAME_WHITELIST (with a matching ')' suffix) wouldn't add all that much hair.  And there are codebases in which this construct occurs a _lot_.

### System configuration
Rails 5.2.0.beta2
Ruby 2.3.4

**Comment by jeremy** [comment]
Let's not go down the path of special-casing certain string usage. If we find ourselves repeating a particularly verbose `.order`, it's time to extract a scope like `alphabetically` or `order_by_name` that wraps it up for you.
