### ISSUE TITLE
Missing doc with supported ruby version for each rails version

### ISSUE THREAD

**Issue by fabioperrella** [rails/rails#31340]
Hi!

In my job, we've tried to upgrade ruby to 2.4 in an application using rails 3.2 and we've found it was not possible, due to an incompatibility with activesupport 3 and ruby 2.4.

We've tried to find a doc with the supported ruby version for each rails version but we didn't find it.

For example, in rails 3, [this doc shows it is required at least ruby 1.8.7](http://guides.rubyonrails.org/3_0_release_notes.html#rails-3-requires-at-least-ruby-1-8-7), but it does not show the maximum supported version of ruby (I think it is 2.3.x).

Do you think this information can be placed in rails guides? If yes, I can send a PR with this.

Thanks,

**Comment by rafaelfranca** [comment]
Thank you for the issue. If Rails 3.2 was not a version that is dead for almost two years now we could add that information to the guides.

The maximum supported version of Ruby can only be determined by testing the framework with it, and we don't want to test a dead version of the framework with newer versions of ruby.

So a guideline for that could be: the maximum supported version of ruby for a version of rails is the newest Ruby version existent when that Rails version is become not supported anymore.
