### ISSUE TITLE
Environment-specific credentials

### ISSUE THREAD

**Issue by mrsweaters** [rails/rails#31349]
### Steps to reproduce

Run `Rails.application.credentials` from the console from any environment.

### Expected behavior
`Rails.application.secrets` will return environment specific secrets from `secrets.yml` if they are name spaced by environment.

I would expect `Rails.application.credentials` to do the same. There are instances where data like third-party API keys are still unique to the loaded environment. It would be nice to be able to store these in the encrypted credentials as well.

Instead of having to do this:
```ruby
Rails.application.credentials[Rails.env].my_credential
```
This is preferred:
```ruby
Rails.application.credentials.my_credential
```
With a credentials file structured like this:
```yml
development:
  my_credential: token
test:
  my_credential: token
production:
  my_credential: token
```

### Actual behavior
`Rails.application.credentials` returns all credentials at root level.

### System configuration
**Rails version**: 5.2.0.beta2

**Ruby version**: 2.4.2

**Comment by y-yagi** [comment]
This is intentional behavior. For details, please see the description of #30067. 

Also, please use the [mailing list](https://groups.google.com/forum/#!forum/rubyonrails-talk) or StackOverflow for questions/help, where a wider community will be able to help you. We reserve the issues tracker for issues only. Thanks!

**Comment by mrsweaters** [comment]
@y-yagi Definitely disagree with the decision there. Will follow up in that discussion. Thanks for pointing me in the right direction!

**Comment by jpatters** [comment]
A reference for anyone else who lands here:
https://github.com/rails/rails/pull/33521

This has been added for rails 6.0
