### ISSUE TITLE
ActiveStorage migration fails if encoding isn't utf8

### ISSUE THREAD

**Issue by davidpaulhunt** [rails/rails#31353]
### Steps to reproduce

1. Create a new rails app specifying mysql as the database: `rails new MyApp -d mysql`
1. Change database.yml encoding option to `utf8mb4`
1. Create database and run migration: `rails db:create db:migrate`

### Expected behavior
Active storage migration should run successfully.

### Actual behavior
Active storage migration fails with the error `Mysql2::Error: Specified key was too long; max key length is 767 bytes`.

Emojis are pretty common, making `utf8mb4` a necessity, and in such a case, the index keys would need to be limited to ~191. Could this be set as the default in the migration? Or is there another solution beyond having users change the standard ActiveStorage migration?

Cheers.

### System configuration
**Rails version**: 5.2.0.beta2

**Ruby version**: 2.4.2

**Comment by rafaelfranca** [comment]
Which MySQL version are you using? This max key length limitation doesn't exist anymore with modern MySQL. Since the migrations are copied to your project and you can change them, if you are using a limited database you should be changing the migrations to work in your platform.

**Comment by ahorek** [comment]
If innodb_large_prefix is enabled (the default in MySQL 5.7.7), the index key prefix limit is 3072 bytes for InnoDB tables that use DYNAMIC or COMPRESSED row format. If innodb_large_prefix is disabled, the index key prefix limit is 767 bytes for tables of any row format.

innodb_large_prefix is deprecated in MySQL 5.7.7 and will be removed in a future release. innodb_large_prefix was introduced in MySQL 5.5 to disable large index key prefixes for compatibility with earlier versions of InnoDB that do not support large index key prefixes.

**Comment by davidpaulhunt** [comment]
@rafaelfranca you're correct in assuming that my local version of MySQL was outdated.

So, it'd definitely on me to either upgrade to >= 5.7 or change my migration file directly before running migrations.

Thanks for the feedback and feel free to close the issue.

**Comment by ahorek** [comment]
just add this
```
sql_mode                = "STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION"
innodb_large_prefix     = 1
```
into **/etc/mysql/my.cnf** and it'll work just fine with your current version

**Comment by davidpaulhunt** [comment]
@ahorek okay, I'll try it and high five you if it works out!

**Comment by josephsiefers** [comment]
I am unable to upgrade to 5.7 at this time, so need to figure out how to get this to work on 5.6

@ahorek I tried this configuration, but is still giving me an error, any ideas?

**Comment by ahorek** [comment]
Did you also change the row format from compact to dynamic? Mysql 5.6 should be fine, but additional config is required if you want to use utf8mb4.

**Comment by slavajacobson** [comment]
I upgraded MySQL from 5.6 to 5.7 ..same issue

Rails and activestorage at 5.2.1


Mysql2::Error: Specified key was too long; max key length is 1000 bytes: CREATE TABLE `active_storage_attachments` (`id` bigint NOT NULL AUTO_INCREMENT PRIMARY KEY, `name` varchar(255) NOT NULL, `record_type` varchar(255) NOT NULL, `record_id` bigint NOT NULL, `blob_id` bigint NOT NULL, `created_at` datetime NOT NULL,  INDEX `index_active_storage_attachments_on_blob_id`  (`blob_id`), UNIQUE INDEX `index_active_storage_attachments_uniqueness`  (`record_type`, `record_id`, `name`, `blob_id`))

**Comment by jasonfb** [comment]
I am on MySQL `5.6.44` — it is a good time to upgrade. I will do so and report back here. 

@rafaelfranca

**Comment by jasonfb** [comment]
it works on MySQL `5.7`
