### ISSUE TITLE
link with data-remote=true fails inside disabled fieldset

### ISSUE THREAD

**Issue by philayres** [rails/rails#31352]
### Steps to reproduce

I understand that disabling a form fieldset should disable form elements. Unfortunately it has the unwanted side effect of also disabling the data-remote functionality of any links within it, causing them to act as standard page navigation. 

Note: this is common to jquery-ujs too, and I have raised an issue there at: https://github.com/rails/jquery-ujs/issues/503

Here is a self contained project demonstrating the issue:

https://github.com/philayres/rails-link-fail

A snippet from the **views/tests/index.html.erb** showing the failure is:

```
<form>
  <fieldset disabled="true">
    <p>Link should run as AJAX request but doesn't.</p>
    <%=link_to "test", new_test_path, data: {remote: true} %>
    <p>Submit tag being disabled confirms the fieldset is disabled</p>
    <%=submit_tag%>
  </fieldset>
</form>
```

### Expected functionality

This functionality seems to be a bug. Ideally, data-remote links should continue to function as designed when they appear inside a disabled fieldset. If the intent was to disable link operation, then disable them completely rather than making them malfunction.

A workaround is to do:

    $('fieldset[disabled=true] a[data-remote]').on('click', function(ev){
      ev.preventDefault();
      $.rails.handleRemote($(this));
    })

But this is really an unnecessary hack.

I will happily help in attempting to resolve this, though I'm struggling to see what is actually causing this issue.

### Versions

Rails 5.1
Ruby 2.4.1

**Comment by gwincr11** [comment]
Hi @philayres,

Thanks for the sample application. Perhaps I am confused but everything seems to work as I would expect. 

I did notice that you are setting up an alert function in your view to trigger on `ajax:complete` in your example. In doing so you set an id for the element to have this work with. Only the second element has the id, even if both had it only one should work as id's are expected to be unique per a page. When I switch which element has the id the ajax alert shows as expected.

Try changing your javascript to:
```javascript
<script>
var els = document.getElementsByTagName('a')

for(i=0; i < els.length; i++) {
  els[i].addEventListener('ajax:complete', function(){
    alert('ajax:complete!');
  });
}
</script>
```

**Comment by philayres** [comment]
Sorry for the delay responding, I've been away from a computer for a while. Let me try and explain why I think there is a bug. My example code is functioning as I intended it, to demonstrate the issue.

Intuitively I do not believe that a disabled fieldset should also disable contained links that have `data-remote="true"`. Since regular links are not disabled (and are functionally not part of a form submission), to my mind it makes no sense that links that make GET Ajax requests should be disabled. But that is what is happening. This is inconsistent behaviour for a link that is not really a form element.

As such I don't see why it should be necessary for me to add event listener code, as I have in my example to make a remote link operate.

To reinforce this, the is that remote links are disabled when placed inside a disabled fieldset. This does not match the normal operation of a link in a disabled fieldset, and as such I believe that the inconsistent behaviour is a bug.

I hope that is more clear.

**Comment by gwincr11** [comment]
I am not sure I follow. When I click the link in the disabled form, I see the request go to the server and returned as a 200 in the chrome dev tools. The only difference I am seeing is that in the form that has not being disabled you have an event listener setup to listen to the response and create an alert.

I commented out all the javascript on the page and clicked on both links and got the same result for each.

Here are the two requests in the browser, both resolve /new
<img width="1142" alt="screen shot 2018-01-04 at 9 28 26 pm" src="https://user-images.githubusercontent.com/289882/34593051-725ba52a-f196-11e7-919f-5ecfbda96eff.png">

Here are multiple requests from the server side. 
<img width="756" alt="screen shot 2018-01-04 at 9 29 08 pm" src="https://user-images.githubusercontent.com/289882/34593052-726ee0b8-f196-11e7-94d7-d0aa1477f21a.png">

Is there some behavior you are expecting that I am not understanding? Is this perhaps happening in a specific browser?

**Comment by philayres** [comment]
I understand why my previous comment was even more confusing now (I will edit it in a moment to identify it as junk to the casual reader). When testing with Chrome the functionality works as expected. On Firefox the (v57 and 40-ish) the data-remote="true" link in the first form in my example no longer makes an Ajax call but actually a standard page navigation (as per my original post).

My excuse for missing this is the project I'm working on is Firefox only. Bad slip on my part. Apologies for the confusion, and thanks for prompting this.

Either way, for such a major browser this still appears to be a bug. Does this help?

**Comment by gwincr11** [comment]
So this is actually a standard Firefox behavior, along with Opera I believe? Firefox does not bubble events up the dom that occur in disabled containers. http://www.webdeveloper.com/forum/showthread.php?186057-Disabled-button-stealing-onclick-events-in-firefox

Handling this situation would require some changes in how the UJS events work, currently all events are bound to the window object and rely on the individual elements being activated to bubble up to the document element. Rails would need to instead be added to every element on the page that match certain selectors. I am guessing things are the way they are for performance reasons, but I am not certain.

**Comment by gwincr11** [comment]
Here is the same issue as reported to JQuery, https://github.com/jquery/jquery/issues/2592, they considered it a bug with Firefox, here is a related Firefox bug report, https://bugzilla.mozilla.org/show_bug.cgi?id=218093,  looks pretty old, I am thinking they will not resolve it anytime soon.

**Comment by philayres** [comment]
Thanks for leading me through the maze to the FF bug report. I have commented on it: https://bugzilla.mozilla.org/show_bug.cgi?id=218093#c48 but like you say I don't expect any action.

It looks like the best I can do for something repeatable is also perform the delegate call in UJS on elements matching `'[disabled="true"] *'` and ensure there is a wrapper container within the disabled fieldset, like this:

```
<form>
  <fieldset disabled="true">
    <span>
      <a data-remote="true" href="/tests/new">test</a>
    </span>
  </fieldset>
</form>
```
Anyway, I understand that there is nothing you can do about this, so I'll close the issue. Thanks for taking the time to look at it.
