### ISSUE TITLE
DEPRECATION WARNING: call is deprecated and will be removed from Rails 5.1

### ISSUE THREAD

**Issue by janicetyp** [rails/rails#31357]
### Expected behavior
Rails 5.0.0.1 - warning appears here
`call` is deprecated but not sure if there are any alternatives offered.

### Actual behavior
Rails 5.1.4 - breaking behaviour in this version
`response = @app.call(env)` - breaking here
undefined method `call' for XYZController:Class

### System configuration
**Rails version**: Rails 5.1.4

**Ruby version**: ruby 2.3.1p112

**Comment by matthewd** [comment]
Please use the mailing list or StackOverflow for questions/help, where a wider community will be able to help you. We reserve the issues tracker for issues only.
