### ISSUE TITLE
ActiveStorage ActiveStorage::AnalyzeJob: no delegate for this image format '' w/ SVG image

### ISSUE THREAD

**Issue by DLawla** [rails/rails#31356]
We are using rails 5.2.0.beta2, and encountering what we think might be an ActiveStorage issue.

While uploading an SVG image, via direct uploads to s3 in our case, the `ActiveStorage::AnalyzeJob` encounters the following error:

```
MiniMagick::Error: `identify -format %m %w %h %b /tmp/ActiveStorage20171207-4-1w1xcid[0]` failed with error: identify: no decode delegate for this image format `' @ error/constitute.c/ReadImage/501.
```

It's worth noting the the common image file types are being happily analyzed by MiniMagick (jpg's and pngs).

After making sure imagemagick was installed, in the console I tried to recreate what `ImageAnalyzer.rb` is performing and where the error seems to stem from: extracting the height and width of the image. Running the following succeeds happily.

```
require "mini_magick"
MiniMagick::Image.new(path/to/an/svg).height
# => 28 # correct height of SVG
```

I found it interesting that this worked, but the seemingly same operation was failing in the job. So, we looked a little upstream of that.

We took a closer look at the initial error, and noticed that the error message gives a blank image format, which looked suspicious. So, we removed the `.svg` file extension from the file, and we received the same error shown above (as expected, to be honest).

So, I'm not sure if we encountered a bug here with ActiveStorage; Is it possible that the `download_blob_to_tempfile` method is returning a file w/o a file extension, and causing the above error? Also worth nothing that the ActiveStorage::Blob created during our upload that is failing, does correctly store the filename (with extension) and the content_type ("image/svg+xml").

### System configuration
Rails 5.2.0.beta2
mini_magick (4.8.0)
ImageMagick 7.0.7-13 Q16 x86_64 2017-12-01

**Ruby version**:
2.4.2

**Comment by pixeltrix** [comment]
@DLawla do you have a backtrace for that error - looking at the mini_magick repo issues it seems that it's related to the quoting of the `-format` argument, e.g:

``` sh
$ identify -format %m %w %h %b /path/to.svg
identify: unable to open image `%w': No such file or directory @ error/blob.c/OpenBlob/2702.
identify: no decode delegate for this image format `' @ error/constitute.c/ReadImage/501.
identify: unable to open image `%h': No such file or directory @ error/blob.c/OpenBlob/2702.
identify: no decode delegate for this image format `' @ error/constitute.c/ReadImage/501.
identify: unable to open image `%b': No such file or directory @ error/blob.c/OpenBlob/2702.
identify: no decode delegate for this image format `' @ error/constitute.c/ReadImage/501.

$ identify -format '%m %w %h %b' /path/to.svg
SVG 128 128 1.05KB
```

In minimagick/minimagick#386 there some discussion about using `spawn` prevents the need for quoting and I was wondering whether it was using that or some been executed differently.

**Comment by DLawla** [comment]
@pixeltrix, thanks for the response.

Sorry, should have included this earlier, but here is a backtrace:
```
vendor/bundle/ruby/2.4.0/gems/mini_magick-4.8.0/lib/mini_magick/shell.rb:17:in `run': `identify -format %m %w %h %b /tmp/ActiveStorage20171205-4-2sjp6i[0]` failed with error:
identify: no decode delegate for this image format `' @ error/constitute.c/ReadImage/501.
 (MiniMagick::Error)
    from vendor/bundle/ruby/2.4.0/gems/mini_magick-4.8.0/lib/mini_magick/tool.rb:92:in `call'
    from vendor/bundle/ruby/2.4.0/gems/mini_magick-4.8.0/lib/mini_magick/tool.rb:40:in `new'
    from vendor/bundle/ruby/2.4.0/gems/mini_magick-4.8.0/lib/mini_magick/image/info.rb:170:in `identify'
    from vendor/bundle/ruby/2.4.0/gems/mini_magick-4.8.0/lib/mini_magick/image/info.rb:114:in `raw'
    from vendor/bundle/ruby/2.4.0/gems/mini_magick-4.8.0/lib/mini_magick/image/info.rb:35:in `[]'
    from vendor/bundle/ruby/2.4.0/gems/mini_magick-4.8.0/lib/mini_magick/image/info.rb:45:in `block in cheap_info'
    from vendor/bundle/ruby/2.4.0/gems/mini_magick-4.8.0/lib/mini_magick/image/info.rb:44:in `fetch'
    from vendor/bundle/ruby/2.4.0/gems/mini_magick-4.8.0/lib/mini_magick/image/info.rb:44:in `cheap_info'
    from vendor/bundle/ruby/2.4.0/gems/mini_magick-4.8.0/lib/mini_magick/image/info.rb:17:in `[]'
    from vendor/bundle/ruby/2.4.0/gems/mini_magick-4.8.0/lib/mini_magick/image.rb:132:in `block in attribute'
    from vendor/bundle/ruby/2.4.0/gems/activestorage-5.2.0.beta2/lib/active_storage/analyzer/image_analyzer.rb:21:in `block in metadata'
    from vendor/bundle/ruby/2.4.0/gems/activestorage-5.2.0.beta2/lib/active_storage/analyzer/image_analyzer.rb:32:in `block in read_image'
    from vendor/bundle/ruby/2.4.0/gems/activestorage-5.2.0.beta2/lib/active_storage/downloading.rb:10:in `block in download_blob_to_tempfile'
    from vendor/ruby-2.4.2/lib/ruby/2.4.0/tempfile.rb:295:in `open'
    from vendor/bundle/ruby/2.4.0/gems/activestorage-5.2.0.beta2/lib/active_storage/downloading.rb:8:in `download_blob_to_tempfile'
    from vendor/bundle/ruby/2.4.0/gems/activestorage-5.2.0.beta2/lib/active_storage/analyzer/image_analyzer.rb:30:in `read_image'
    from vendor/bundle/ruby/2.4.0/gems/activestorage-5.2.0.beta2/lib/active_storage/analyzer/image_analyzer.rb:20:in `metadata'
    from vendor/bundle/ruby/2.4.0/gems/activestorage-5.2.0.beta2/app/models/active_storage/blob.rb:303:in `extract_metadata_via_analyzer'
    from vendor/bundle/ruby/2.4.0/gems/activestorage-5.2.0.beta2/app/models/active_storage/blob.rb:252:in `analyze'
    from vendor/bundle/ruby/2.4.0/gems/activestorage-5.2.0.beta2/app/jobs/active_storage/analyze_job.rb:6:in `perform'
```

I'll have a play with the `format` logic and see if I can unearth anything.

**Comment by DLawla** [comment]
@pixeltrix, 
Just some more information here: I just dropped a breakpoint into the private method `ImageAnalyzer#read_image` to take a look at the file passed into `MiniMagick::Image.new`, and this is what it looks like for a case for a SVG file that will raise the `no decode delegate` error:

```
(byebug) file
#<Tempfile:/var/folders/06/bty11_tn6632dqdz67rly7680000gn/T/ActiveStorage20171208-58722-1ydtz6p>
(byebug) MiniMagick::Image.new(file.path).width
*** MiniMagick::Error Exception: `identify -format %m %w %h %b /var/folders/06/bty11_tn6632dqdz67rly7680000gn/T/ActiveStorage20171208-58722-1ydtz6p[0]` failed with error:
identify: no decode delegate for this image format `' @ error/constitute.c/ReadImage/509.
```

Here is the same for a PNG file that will be analyzed just fine:
```
(byebug) file
#<Tempfile:/var/folders/06/bty11_tn6632dqdz67rly7680000gn/T/ActiveStorage20171208-58722-15n4xhn>
(byebug) MiniMagick::Image.new(file.path).identify
"/var/folders/06/bty11_tn6632dqdz67rly7680000gn/T/ActiveStorage20171208-58722-15n4xhn PNG 128x64 128x64+0+0 8-bit sRGB 2693B 0.000u 0:00.000"
```

This refutes my first comment where I wasn't sure if the lack of file extension in the temp file could be causing an issue, so disregard that.

This leaves me unsure of why error is raised on the SVG temp file when `identify` is called after passing through the ActiveStorage ecosystem (and being downloaded as a tempfile), but `identify` will work fine on the same original image, but called through a rails console.

```
require "mini_magick"
MiniMagick::Image.new(path/to/an/svg).indentify
# => "/Users/drlawler/.../arrow-right.svg SVG 28x17 28x17+0+0 16-bit sRGB 234B 0.000u 0:00.029" 
```

**Comment by atstockland** [comment]
I get the same error from a failed job after trying to preview a PDF.

      identify -format %m %w %h %b /var/folders/zg/71x_xpk11g96g7lxknf2w17w0000gn/T/ActiveStorage20171230-74049-1qo212f[0]` 
      failed with error: identify: no decode delegate for this image format `' @ error/constitute.c/ReadImage/509.

**Comment by georgeclaghorn** [comment]
@atstockland Is the PDF in question password-protected?

**Comment by atstockland** [comment]
It is not.  I will try a couple other PDF files and see what happens.

**Comment by georgeclaghorn** [comment]
Could you try running the PDF through `mutool` manually? Does it produce a valid image? Do you get error output?

This is the command you’ll want to run:

    mutual draw -F png -o preview.png path/to/document.pdf 1

I suspect whatever you’re experiencing is unrelated to this bug.

**Comment by georgeclaghorn** [comment]
@DLawla I couldn’t reproduce this with an arbitrary SVG image. Can you share the one you’re using?

**Comment by atstockland** [comment]
I tried 3 other PDF (single page and multi-page), just to see if it was related to corruption...or, MiniMagick thinking it was an "invalid" PDF.  Same result on all.  All have extension ".pdf"

Running:

      mutool draw -F png -o preview.png "/Users/LilWayne/Desktop/testing/ukulele.pdf" 1

returns

      page /Users/LilWayne/Desktop/testing/ukulele.pdf 1

no errors, no file is returned in the /testing directory

whats the best way for me to share the PDF with you?

**Comment by atstockland** [comment]
whooops.  The png images were created.  I was looking in the directory where the image was from...not looking in the directory my console was already in.  The command you gave me was successful.

**Comment by atstockland** [comment]
Is this a MiniMagick bug..or issue?

**Comment by georgeclaghorn** [comment]
Is the image’s size greater than zero bytes?

**Comment by atstockland** [comment]
110k for the original PDF.

**Comment by atstockland** [comment]
the created png file is 93k

**Comment by DLawla** [comment]
@georgeclaghorn Attached is an SVG that will cause the error on my end.
[arrow-right.svg.zip](https://github.com/rails/rails/files/1594958/arrow-right.svg.zip)

**Comment by atstockland** [comment]
I'm a moron.  I emailed a file.  ha. here it is...
[ukulele.pdf](https://github.com/rails/rails/files/1594959/ukulele.pdf)

**Comment by georgeclaghorn** [comment]
@DLawla: I reproduced this issue with your image. When I removed the extension from the filename, ImageMagick failed to identify it. However, ImageMagick successfully identified it when I added an XML declaration to the beginning of the file:

```xml
<?xml version="1.0" encoding="UTF-8" ?>
<svg width="28" height="17" viewBox="0 0 28 17" xmlns="http://www.w3.org/2000/svg">
  <g stroke="#FFF" fill="none" fill-rule="evenodd" stroke-linecap="square">
    <path d="M26.5 8.5l-8.062 8.062M25.5 8.5H1.48M18.5.5l8.062 8.062"/>
  </g>
</svg>
```

It seems like ImageMagick looks for an XML declaration to identify SVG images and falls back to the extension if it finds none. The XML declaration is optional, so I’ll modify `ActiveStorage::Downloading#download_blob_to_tempfile` to append the blob’s extension to the tempfile name.

**Comment by atstockland** [comment]
@georgeclaghorn That fixed my issue too...using a PDF.  The png is created, rendered, and has content_type of PNG.  However, the image url in the browser is still "ukulele.pdf".  Perhaps that is expected behavior since the PDF url is called and the "short-lived" direct url is actually the path to the png file.

      <img  src="http://localhost:3000/rails/active_storage/previews/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBHUT09IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--84e6e34efcc74104a59de66f632017d67185ee4d/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaDdCam9MY21WemFYcGxTU0lNTXpVd2VETTFNQVk2QmtWVSIsImV4cCI6bnVsbCwicHVyIjoidmFyaWF0aW9uIn19--6d49c6b0ae913a78b5cb38269a6412565ee1d837/ukulele.pdf">

that path renders the attached png.
![ukulele](https://user-images.githubusercontent.com/536711/34464172-b44f146e-ee29-11e7-859d-c9507be2ce44.png)

**Comment by atstockland** [comment]
This same issue has resurfaced for me in production on heroku

**Comment by loop23** [comment]
@georgeclaghorn - I'm having a similar issue when generating a preview for any pdf file. It seems like mupdf (version 1.12.0, osx via brew) does not recognize a pdf file if it does not end in .pdf, but the preview method ends up calling it with a tempfile (which does not end in .pdf); Do tests suggest generating a pdf preview works? in my environment it cannot possibly work, but maybe other mutools versions do? 
Further, I have two questions:

1) If the storage is local, why bother with the tempfile at all? Wouldn't it be better to just pass it the original filename?
2) Previewer#capture ignores any error. Is it by design? This way, the preview is wrong (0 byte file) but it does not stop it from saving the attachment version - which then never shows correctly and never will;

Personally, i modified capture like that:
```ruby
def capture(*argv, to:)
  Rails.logger.debug("capture invocata con #{argv.inspect}, to: #{to.path}")
    to.binmode
    IO.popen(argv) { |out| IO.copy_stream(out, to) }
    raise(RuntimeError, "Exit status for popen: #$?") if $? != 0
 end
```

but am not terribly sure about it, probably a custom exception would make sense?

**Comment by georgeclaghorn** [comment]
@loop23: Are you using an older revision than 316d87e? That commit fixes the issue you describe.

> If the storage is local, why bother with the tempfile at all?

Active Storage is designed for cloud services. The disk service is provided for local development convenience; we’re not likely to add special cases for it.

> Previewer#capture ignores any error. Is it by design? This way, the preview is wrong (0 byte file) but it does not stop it from saving the attachment version - which then never shows correctly and never will

That’s a known issue (and unrelated to this one). I have it on my to-do list. Yes, we should probably raise an error.

**Comment by loop23** [comment]
Yes, I'm using the 5.2 beta.
+1 for raising an aptly named exception. 
Sorry to bother you.. how do I switch ActiveStorage in Gemile to use a newer version that includes this commit (which I checked locally, and actually fixes things)?

**Comment by georgeclaghorn** [comment]
You can bundle Rails from GitHub:

```ruby
gem "rails", github: "rails/rails"

# Optionally specify a commit:
gem "rails", github: "rails/rails", ref: "0f7d3b6"
```

If you’d prefer to use a released version and don’t mind waiting, a 5.2 release candidate should drop soon.

**Comment by loop23** [comment]
I meant bundle just ActiveStorage.
I'll take my chances, I really need previews now ;)
Thanks

**Comment by taylor01** [comment]
I am also having a similar image on heroku running 5.2.RC1

**Comment by taylor01** [comment]
I was able to resolve my issue by creating a custom buildpack of mupdf so that it would go to version 1.12 on heroku.  When it was using the 1.7 version it wouldn't work.  In my case it looks like it was the difference in version of mupdf that did the trick.
