### ISSUE TITLE
Unexpected column added

### ISSUE THREAD

**Issue by chukitow** [rails/rails#31367]
I created a migration and noticed that an unexpected column was added, checking the migration I realized there was a typo.

```ruby
  def change
    create_table :products do |t|
      t.integer :user_id,
      t.timestamps
    end
  end
``` 

Leaving the `,` creates the following column name in the table

```
<ActiveRecord::ConnectionAdapters::SQLite3::TableDefinition:0x007fd73d1c21d8>
```

### System configuration
**Rails version**:
5.1.3

**Ruby version**:
2.3.1

**Comment by al2o3cr** [comment]
What resolution are you proposing for this situation?

**Comment by rafaelfranca** [comment]
I don't think there is much we can do here. The second argument can be anything even a number and I don't think we should be defensive about which arguments are being passes. Users should be testing if they migrations are working.
