### ISSUE TITLE
GEM=ar:postgresql with Ruby:2.4.2 has been failing at Travis CI

### ISSUE THREAD

**Issue by yahonda** [rails/rails#31369]
### Steps to reproduce
Since https://travis-ci.org/rails/rails/jobs/312045308 GEM=ar:postgresql with Ruby:2.4.2 has been failing at Travis CI

I do not think this is due to this commit. Because another CI for pull requests including this commit are fine https://travis-ci.org/rails/rails/jobs/313223402

It should not be opened as Rails issue but I do not know other proper way. It would be helpful if Rails committer who can change CI setting take some actions.

### Expected behavior
It should pass.

### Actual behavior
```ruby
/home/travis/.rvm/rubies/ruby-2.4.2/bin/ruby -w -Itest test/cases/validations/absence_validation_test.rb
/home/travis/build/rails/rails/activerecord/lib/active_record/connection_adapters/postgresql/database_statements.rb:75:in `async_exec': PG::UnableToSend: server closed the connection unexpectedly (ActiveRecord::StatementInvalid)
	This probably means the server terminated abnormally
	before or while processing the request.
: CREATE TABLE "uuid_items" ("uuid" uuid NOT NULL PRIMARY KEY, "title" character varying)
```

### System configuration
**Rails version**:master branch

**Ruby version**:2.4.2

**Comment by yahonda** [comment]
I've found the similar error has been happening with `ruby-head`

* This was the last successful build
https://travis-ci.org/rails/rails/builds/312034264

* This is the first failed build triggered by https://github.com/rails/rails/commit/7544cf7603959f25100b21f70b5e70354bed7e45
https://travis-ci.org/rails/rails/builds/312034264

`bundle exec rake postgresql:test` has been fine even in the failed builds
`bundle exec rake postgresql:isolated_test` always fails with `ruby-2.4` and `ruby-head`

I've been trying to reproduce it but unable to do so far. I'd like to see if it still fails by reverting 7544cf7603959f25100b21f70b5e70354bed7e45

**Comment by yahonda** [comment]
There is another type of error reported at https://travis-ci.org/rails/rails/jobs/315219528

```ruby
/home/travis/.rvm/rubies/ruby-2.4.2/bin/ruby -w -Itest test/cases/result_test.rb
/home/travis/build/rails/rails/activerecord/lib/active_record/connection_adapters/postgresql/database_statements.rb:75:in `async_exec': PG::DiskFull: ERROR:  could not extend file "base/45968/253535": No space left on device (ActiveRecord::StatementInvalid)
HINT:  Check free disk space.
: CREATE TABLE "warehouse-things" ("id" bigserial primary key, "value" integer)
```

I'm wondering what consumes disk space.

**Comment by eileencodes** [comment]
@yahonda thanks for the investigation. Since PR's don't run isolated I'm going to push a branch to the main repo which will run isolated tests that reverts that commit and see if it alleviates the problem.

**Comment by matthewd** [comment]
If it helps, #31415 is a different approach to approximately the same problem as 7544cf7603959f25100b21f70b5e70354bed7e45. 

I'm not sure whether we want to do something so drastic.. but I do feel like we've been pushing up against this issue [of wanting differently-configured machines for different test suites] for a while.

**Comment by eileencodes** [comment]
Ok so reverting  7544cf7 does fix the issue (see https://github.com/rails/rails/tree/whats-wrong-postgresql and it's build https://travis-ci.org/rails/rails/jobs/315360677). 

@yahonda can you open a PR that reverts that commit and cc me? I want to make sure you get the credit for finding the commit.

I think that we should test @matthewd's branch by pushing it to rails/rails and make sure the issue with postgresql doesn't come back.

**Comment by yahonda** [comment]
Opened #31418 @eileencodes Thanks for considering the credit.

**Comment by yahonda** [comment]
Closing since the build is green. https://travis-ci.org/rails/rails/builds/315420746

**Comment by lostapathy** [comment]
@eileencodes are there docs somewhere that explain why travis tests PRs and branches differently (in particular, the isolate tests)?  Would like to understand why that is, and maybe come up with a way to force that in PRs so this type of thing would be easier to troubleshoot in the future.  I'd really like to get the original commit restored (it was a huge resource savings) but not sure how to troubleshoot that without being a committer.

**Comment by eileencodes** [comment]
@lostapathy isolation essentially runs the suite twice so it would be very time consuming to run all pushes / PR's with isolation. 99% of the time we don't have an issue with isolated, so it doesn't make sense to use Travis' resources (which we get for free for being an oss project) to double run every push.

As for your original change we think https://github.com/rails/rails/pull/31415 will have the same fix but haven't gotten around to merging it yet.
