### ISSUE TITLE
validates_confirmation_of always return valid if confirmation is nil

### ISSUE THREAD

**Issue by danillop** [rails/rails#31362]
### Steps to reproduce

1. Create a new rails application.
2. Create any simple model validating confirmation of a field.

### Example
```
class User < ApplicationRecord

  validates_presence_of     :password
  validates_confirmation_of :password
end
```

```
irb(main):008:0> User.new(password: 'q1w2e3r4', password_confirmation: nil).valid?
=> true
irb(main):009:0> User.new(password: 'q1w2e3r4', password_confirmation: '').valid?
=> false
```

### Expected behavior
Tell us what should happen
When the field to be confirmed is not nil and the confirmation field is nil it should not be valid.
```
irb(main):009:0> User.new(password: 'q1w2e3r4', password_confirmation: '').valid?
=> false

```
### Actual behavior
Tell us what happens instead
Now if the confirmation field is nil the model is consider valid.

```
irb(main):008:0> User.new(password: 'q1w2e3r4', password_confirmation: nil).valid?
=> true
```

### System configuration
**Rails version**:
5.1.4
**Ruby version**:
ruby 2.3.1

**Comment by georgeclaghorn** [comment]
This is the intended and documented behavior of `validates_confirmation_of`:

> NOTE: This check is performed only if password_confirmation is not nil. To require confirmation, make sure to add a presence check for the confirmation attribute:
>
>     validates_presence_of :password_confirmation, if: :password_changed?
