### ISSUE TITLE
app_template and dYYYYMMDD-nnnnn-* directories not deleted after running railties unit tests

### ISSUE THREAD

**Issue by yahonda** [rails/rails#31368]
While investigating #31351 I have found that `app_template` directory and dummy applications named like d20171208-9536-183z97g remain at /tmp directory after unit tests completed.

### Steps to reproduce

```ruby
$ cd rails/railties
$ bundle install
$ bundle exec rake test
$ ls -l /tmp
```
### Expected behavior
`app_template` or `dYYYYMMDD-nnnn-*` directories should not exist.

### Actual behavior
```ruby
 ls -l /tmp/
total 52
drwxrwxr-x 14 vagrant vagrant 4096 Dec  8 00:18 app_template
drwx------  3 vagrant vagrant 4096 Dec  8 00:17 d20171208-27434-p89081
drwx------  3 vagrant vagrant 4096 Dec  8 00:17 d20171208-27437-1c9asbh
drwx------  3 vagrant vagrant 4096 Dec  8 00:17 d20171208-27465-f33qp6
drwx------  3 vagrant vagrant 4096 Dec  8 00:17 d20171208-27470-1bjpnvr
drwx------  3 vagrant vagrant 4096 Dec  8 00:17 d20171208-27497-4d1wce
drwx------  3 vagrant vagrant 4096 Dec  8 00:17 d20171208-27500-36sp8p
drwx------  3 vagrant vagrant 4096 Dec  8 00:17 d20171208-27505-1qky6mv
drwx------  3 vagrant vagrant 4096 Dec  8 00:17 d20171208-27532-vwod4m
```
### System configuration
**Rails version**:master branch

**Ruby version**:ruby 2.4.2p198 (2017-09-14 revision 59899) [x86_64-linux-gnu]

**Comment by y-yagi** [comment]
Although I noticed this, that directory is useful for investigations when the test fails. 
However, I understand the opinion that it is an obstacle, so if someone intentionally want to remove, I do not object to remove.

**Comment by yahonda** [comment]
Understood. Closing this issue since I do not have strong opinion to remove them.
