### ISSUE TITLE
Documentation changes merged are not visible

### ISSUE THREAD

**Issue by atul-shimpi** [rails/rails#31370]
My pull request for association document were merged.
However the they are not reflected on document yet.

Changes,
http://guides.rubyonrails.org/association_basics.html
In the image, models are shown to be dervied from ActiveRecord::Base, which should be ApplicationRecord.

**Comment by y-yagi** [comment]
http://guides.rubyonrails.org show released Rails doc. Therefore, now the doc at 5.1.4 release is showed. 
Also, if you want to check the unreleased Rails doc, you can check it with http://edgeguides.rubyonrails.org/association_basics.html.
