### ISSUE TITLE
Rails 5.1.4 ajax:error not trigger when object can't be save

### ISSUE THREAD

**Issue by helmutrs** [rails/rails#31385]
### Steps to reproduce

(Guidelines for creating a bug report are [available
here](http://guides.rubyonrails.org/contributing_to_ruby_on_rails.html#creating-a-bug-report))
When submitting a remote form, and the controller failed to save or update the object because some restrictions in the model (like the attribute must not be blank), the ajax:error is not trigger, instead it keeps trigger the ajax:success method.

### Expected behavior
Tell us what should happen
The ajax:error method should be trigger, since the object failed to be created or updated.

### Actual behavior
Tell us what happens instead
the ajax:success method keeps being trigger instead.

### System configuration
**Rails version**:
5.1.4
**Ruby version**:
2.4.2

**Comment by al2o3cr** [comment]
@helmutrs Can you provide an example of this behavior? Useful things would include:

* logs of this behavior showing what the server replies to the AJAX call with
* source code of the controller action exhibiting this behavior
* (ideally!) a simplified application that demonstrates the issue

Without some of this additional information, it's difficult to debug your issue.

**Comment by helmutrs** [comment]
```
class Home < ApplicationRecord
	validates :name, presence: true
end
class HomesController < ApplicationController
  before_action :set_home, only: [:show, :edit, :update, :destroy]

  def new
    @home = Home.new
  end

  def create
    @home = Home.new(home_params)

    respond_to do |format|
      if @home.save
        format.html { redirect_to @home, notice: 'Home was successfully created.' }
        format.json { render :show, status: :created, location: @home }
        format.js
      else
        format.html { render :new }
        format.json { render json: @home.errors, status: :unprocessable_entity }
        format.js
      end
    end
  end
 
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_home
      @home = Home.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def home_params
      params.require(:home).permit(:name)
    end
end

# new.html.erb
<h1>New Home</h1>

<%= render 'form', home: @home %>

<%= link_to 'Back', homes_path %>

# _form.html.erb
<%= form_with(model: home) do |form| %>
  <% if home.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(home.errors.count, "error") %> prohibited this home from being saved:</h2>

      <ul>
      <% home.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :home_name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

# homes.coffee
document.addEventListener 'ajax:success', (event)->
	console.log "Success: #{event}"

document.addEventListener 'ajax:error', (event)->
	console.log "Error: #{event}"
```

If the form was submitting successfully (the object can be created), then the ajax:success callback fires. But if the object can't be created, stills fire the ajax:success callback, if you need more info, please let me know.. thanks.

**Comment by aditya-vector** [comment]
@helmutrs This looks more like a format issue.
The `format.js` is what you should be looking for instead of `format.json`,

If you look at your response in the console, you should be able to see that the response has status `200` instead of `422`. That is because you have not specified a block in `format.js`.

So, `format.js` should get you to `ajax:error` event with proper response status.

Note: You might want to add a `js.erb` template to handle the javascript. Or you can just respond from the controller as well.

**Comment by helmutrs** [comment]
Hi @aditya-vector 
In this particular example that I just created for demonstration, I do have a js.erb created (created.js.erb) to hide the form and update the homes table, or if the @home has any error, show the error on the homes index. But I thought that if the object has any error, the ajax was handle automatically without me change the status on the controller. Thanks.

**Comment by aditya-vector** [comment]
@helmutrs Sorry for the extreme delay! I somehow had lost the thread topic. If not solved already, I think you would need to check what response code is the request serving. Also, why not just check if the object has errors in the erb file? Im sorry if I havent commented with a lot of context.

**Comment by wellingtondev** [comment]
Hey guys,

I'm having the same problem trying to trigger ajax:error
