### ISSUE TITLE
ActiveSupport::MessageEncryptor::InvalidMessage Rails 5.1 secrets

### ISSUE THREAD

**Issue by piotrpietrusewicz** [rails/rails#31397]
I generated secrets.yml.enc & secrets.yml.key, after secrets:edit and deploy by capistrano, I get above error. I don't know why. Production mode locally works fine, but on real production wrong. 

/home/crazypiter1990/domains/crazypiter1990.usermd.net/shared/bundle/ruby/2.2.0/gems/activesupport-5.1.4/lib/active_support/message_encryptor.rb:133:in `rescue in _decrypt': ActiveSupport::MessageEncryptor::InvalidMessage (ActiveSupport::MessageEncryptor::InvalidMessage)
	from /home/crazypiter1990/domains/crazypiter1990.usermd.net/shared/bundle/ruby/2.2.0/gems/activesupport-5.1.4/lib/active_support/message_encryptor.rb:112:in `_decrypt'
	from /home/crazypiter1990/domains/crazypiter1990.usermd.net/shared/bundle/ruby/2.2.0/gems/activesupport-5.1.4/lib/active_support/message_encryptor.rb:84:in `decrypt_and_verify'
	from /home/crazypiter1990/domains/crazypiter1990.usermd.net/shared/bundle/ruby/2.2.0/gems/railties-5.1.4/lib/rails/secrets.rb:55:in `decrypt'
	from /home/crazypiter1990/domains/crazypiter1990.usermd.net/shared/bundle/ruby/2.2.0/gems/railties-5.1.4/lib/rails/secrets.rb:96:in `preprocess'
	from /home/crazypiter1990/domains/crazypiter1990.usermd.net/shared/bundle/ruby/2.2.0/gems/railties-5.1.4/lib/rails/secrets.rb:27:in `block in parse'
	from /home/crazypiter1990/domains/crazypiter1990.usermd.net/shared/bundle/ruby/2.2.0/gems/railties-5.1.4/lib/rails/secrets.rb:24:in `each'
	from /home/crazypiter1990/domains/crazypiter1990.usermd.net/shared/bundle/ruby/2.2.0/gems/railties-5.1.4/lib/rails/secrets.rb:24:in `each_with_object'
	from /home/crazypiter1990/domains/crazypiter1990.usermd.net/shared/bundle/ruby/2.2.0/gems/railties-5.1.4/lib/rails/secrets.rb:24:in `parse'
	from /home/crazypiter1990/domains/crazypiter1990.usermd.net/shared/bundle/ruby/2.2.0/gems/railties-5.1.4/lib/rails/application.rb:391:in `secrets'
	from /home/crazypiter1990/domains/crazypiter1990.usermd.net/shared/bundle/ruby/2.2.0/gems/devise-4.3.0/lib/devise/rails.rb:36:in `block in <class:Engine>'
	from /home/crazypiter1990/domains/crazypiter1990.usermd.net/shared/bundle/ruby/2.2.0/gems/railties-5.1.4/lib/rails/initializable.rb:30:in `instance_exec'
	from /home/crazypiter1990/domains/crazypiter1990.usermd.net/shared/bundle/ruby/2.2.0/gems/railties-5.1.4/lib/rails/initializable.rb:30:in `run'
	from /home/crazypiter1990/domains/crazypiter1990.usermd.net/shared/bundle/ruby/2.2.0/gems/railties-5.1.4/lib/rails/initializable.rb:59:in `block in run_initializers'
	from /home/crazypiter1990/.rvm/rubies/ruby-2.2.5/lib/ruby/2.2.0/tsort.rb:226:in `block in tsort_each'
	from /home/crazypiter1990/.rvm/rubies/ruby-2.2.5/lib/ruby/2.2.0/tsort.rb:348:in `block (2 levels) in each_strongly_connected_component'
	from /home/crazypiter1990/.rvm/rubies/ruby-2.2.5/lib/ruby/2.2.0/tsort.rb:429:in `each_strongly_connected_component_from'
	from /home/crazypiter1990/.rvm/rubies/ruby-2.2.5/lib/ruby/2.2.0/tsort.rb:347:in `block in each_strongly_connected_component'
	from /home/crazypiter1990/.rvm/rubies/ruby-2.2.5/lib/ruby/2.2.0/tsort.rb:345:in `each'
	from /home/crazypiter1990/.rvm/rubies/ruby-2.2.5/lib/ruby/2.2.0/tsort.rb:345:in `call'
	from /home/crazypiter1990/.rvm/rubies/ruby-2.2.5/lib/ruby/2.2.0/tsort.rb:345:in `each_strongly_connected_component'
	from /home/crazypiter1990/.rvm/rubies/ruby-2.2.5/lib/ruby/2.2.0/tsort.rb:224:in `tsort_each'
	from /home/crazypiter1990/.rvm/rubies/ruby-2.2.5/lib/ruby/2.2.0/tsort.rb:203:in `tsort_each'
	from /home/crazypiter1990/domains/crazypiter1990.usermd.net/shared/bundle/ruby/2.2.0/gems/railties-5.1.4/lib/rails/initializable.rb:58:in `run_initializers'
	from /home/crazypiter1990/domains/crazypiter1990.usermd.net/shared/bundle/ruby/2.2.0/gems/railties-5.1.4/lib/rails/application.rb:353:in `initialize!'
	from /usr/home/crazypiter1990/domains/crazypiter1990.usermd.net/releases/20171211152401/config/environment.rb:5:in `<top (required)>'
	from /home/crazypiter1990/domains/crazypiter1990.usermd.net/shared/bundle/ruby/2.2.0/gems/activesupport-5.1.4/lib/active_support/dependencies.rb:292:in `require'
	from /home/crazypiter1990/domains/crazypiter1990.usermd.net/shared/bundle/ruby/2.2.0/gems/activesupport-5.1.4/lib/active_support/dependencies.rb:292:in `block in require'
	from /home/crazypiter1990/domains/crazypiter1990.usermd.net/shared/bundle/ruby/2.2.0/gems/activesupport-5.1.4/lib/active_support/dependencies.rb:258:in `load_dependency'
	from /home/crazypiter1990/domains/crazypiter1990.usermd.net/shared/bundle/ruby/2.2.0/gems/activesupport-5.1.4/lib/active_support/dependencies.rb:292:in `require'
	from /home/crazypiter1990/domains/crazypiter1990.usermd.net/shared/bundle/ruby/2.2.0/gems/railties-5.1.4/lib/rails/application.rb:329:in `require_environment!'
	from /home/crazypiter1990/domains/crazypiter1990.usermd.net/shared/bundle/ruby/2.2.0/gems/railties-5.1.4/lib/rails/command/actions.rb:16:in `require_application_and_environment!'
	from /home/crazypiter1990/domains/crazypiter1990.usermd.net/shared/bundle/ruby/2.2.0/gems/railties-5.1.4/lib/rails/commands/console/console_command.rb:96:in `perform'
	from /home/crazypiter1990/domains/crazypiter1990.usermd.net/shared/bundle/ruby/2.2.0/gems/thor-0.20.0/lib/thor/command.rb:27:in `run'
	from /home/crazypiter1990/domains/crazypiter1990.usermd.net/shared/bundle/ruby/2.2.0/gems/thor-0.20.0/lib/thor/invocation.rb:126:in `invoke_command'
	from /home/crazypiter1990/domains/crazypiter1990.usermd.net/shared/bundle/ruby/2.2.0/gems/thor-0.20.0/lib/thor.rb:387:in `dispatch'
	from /home/crazypiter1990/domains/crazypiter1990.usermd.net/shared/bundle/ruby/2.2.0/gems/railties-5.1.4/lib/rails/command/base.rb:63:in `perform'
	from /home/crazypiter1990/domains/crazypiter1990.usermd.net/shared/bundle/ruby/2.2.0/gems/railties-5.1.4/lib/rails/command.rb:44:in `invoke'
	from /home/crazypiter1990/domains/crazypiter1990.usermd.net/shared/bundle/ruby/2.2.0/gems/railties-5.1.4/lib/rails/commands.rb:16:in `<top (required)>'
	from bin/rails:9:in `require'
	from bin/rails:9:in `<main>'
### System configuration
**Rails version**:
Rails 5.1.4
**Ruby version**:
2.2.5

**Comment by y-yagi** [comment]
Can you please provide a sample application that reproduces the error?

**Comment by piotrpietrusewicz** [comment]
I can not, because is private project on production server. Generally, I run e.g 'rails console' and I get this kind of error.

**Comment by rafaelfranca** [comment]
You need to give us more information on how to reproduce this issue, otherwise there is nothing we can do. Please read CONTRIBUTING.md file for more information about creating bug reports. Thanks!

**Comment by piotrpietrusewicz** [comment]
So few things that I did before error came up: 

1. Run rails secrets:setup
2 Add line config.config.read_encrypted_secrets = true to production.rb
3. Run "EDITOR='subl --wait' rails secrets:edit" in terminal
4. Fill the file with data  ( attachment see)

- [example.txt](https://github.com/rails/rails/files/1554432/example.txt)

5. Rails encrypt the file with file secrets.yml.key
6. Add secrets.yml.key to linked_files in capistrano
7. Use secrets inside database.yml , e.g 
> <%= WorkoutRails::Application.secrets.database %>

**Comment by kaspth** [comment]
I don't think we can provide help on a Capistrano set up. It seems unlikely to me that there's a bug in Rails here. All the best to figuring it out!

**Comment by januszm** [comment]
It might be `spring`'s fault , remove it from `bin/rails` and `bin/rake` and try again

**Comment by okuramasafumi** [comment]
I had the issue and I seemed to find the problem.
Rails reads the key from environment variables (`RAILS_MASTER_KEY`) if it exists before trying to read the key from a file.
I had two apps on the same server and the second app reads the key from environment variable for the first app, which is wrong key, and raises this error.

Is this a bug of rails? I mean, shouldn't it be possible to override the key from environment variable so that multiple apps can coexist on the same server?

**Comment by christophelh** [comment]
I think i have the same error but I dont know how to debug it .... i think the error started when setting up Rails Master key too ... how did you fixed it


2018-03-21T00:50:33.786Z: /home/bas/app_0c1c9c36-cc8c-4c59-affb-988c46d3c2b9/vendor/bundle/ruby/2.3.0/gems/activesupport-5.1.5/lib/active_support/message_encryptor.rb:133:in `rescue in _decrypt': ActiveSupport::MessageEncryptor::InvalidMessage (ActiveSupport::MessageEncryptor::InvalidMessage)
2018-03-21T00:50:33.786Z: from /home/bas/app_0c1c9c36-cc8c-4c59-affb-988c46d3c2b9/vendor/bundle/ruby/2.3.0/gems/activesupport-5.1.5/lib/active_support/message_encryptor.rb:112:in `_decrypt'
2018-03-21T00:50:33.786Z: from /home/bas/app_0c1c9c36-cc8c-4c59-affb-988c46d3c2b9/vendor/bundle/ruby/2.3.0/gems/activesupport-5.1.5/lib/active_support/message_encryptor.rb:84:in `decrypt_and_verify'
2018-03-21T00:50:33.786Z: from /home/bas/app_0c1c9c36-cc8c-4c59-affb-988c46d3c2b9/vendor/bundle/ruby/2.3.0/gems/railties-5.1.5/lib/rails/secrets.rb:55:in `decrypt'
2018-03-21T00:50:33.786Z: from /home/bas/app_0c1c9c36-cc8c-4c59-affb-988c46d3c2b9/vendor/bundle/ruby/2.3.0/gems/railties-5.1.5/lib/rails/secrets.rb:96:in `preprocess'
2018-03-21T00:50:33.786Z: from /home/bas/app_0c1c9c36-cc8c-4c59-affb-988c46d3c2b9/vendor/bundle/ruby/2.3.0/gems/railties-5.1.5/lib/rails/secrets.rb:27:in `block in parse'
2018-03-21T00:50:33.787Z: from /home/bas/app_0c1c9c36-cc8c-4c59-affb-988c46d3c2b9/vendor/bundle/ruby/2.3.0/gems/railties-5.1.5/lib/rails/secrets.rb:24:in `each'
2018-03-21T00:50:33.787Z: from /home/bas/app_0c1c9c36-cc8c-4c59-affb-988c46d3c2b9/vendor/bundle/ruby/2.3.0/gems/railties-5.1.5/lib/rails/secrets.rb:24:in `each_with_object'
2018-03-21T00:50:33.787Z: from /home/bas/app_0c1c9c36-cc8c-4c59-affb-988c46d3c2b9/vendor/bundle/ruby/2.3.0/gems/railties-5.1.5/lib/rails/secrets.rb:24:in `parse'
2018-03-21T00:50:33.787Z: from /home/bas/app_0c1c9c36-cc8c-4c59-affb-988c46d3c2b9/vendor/bundle/ruby/2.3.0/gems/railties-5.1.5/lib/rails/application.rb:391:in `secrets'
2018-03-21T00:50:33.787Z: from /home/bas/app_0c1c9c36-cc8c-4c59-affb-988c46d3c2b9/vendor/bundle/ruby/2.3.0/gems/devise-4.4.2/lib/devise/rails.rb:40:in `block in <class:Engine>'
2018-03-21T00:50:33.787Z: from /home/bas/app_0c1c9c36-cc8c-4c59-affb-988c46d3c2b9/vendor/bundle/ruby/2.3.0/gems/railties-5.1.5/lib/rails/initializable.rb:30:in `instance_exec'
2018-03-21T00:50:33.788Z: from /home/bas/app_0c1c9c36-cc8c-4c59-affb-988c46d3c2b9/vendor/bundle/ruby/2.3.0/gems/railties-5.1.5/lib/rails/initializable.rb:30:in `run'
2018-03-21T00:50:33.788Z: from /home/bas/app_0c1c9c36-cc8c-4c59-affb-988c46d3c2b9/vendor/bundle/ruby/2.3.0/gems/railties-5.1.5/lib/rails/initializable.rb:59:in `block in run_initializers'

**Comment by okuramasafumi** [comment]
@rafaelfranca @y-yagi 
OK, now I found a way to reproduce this error.

Steps for isolated environment:

1. create a directory to export `RAILS_MASTER_KEY` for two apps (I recommend using direnv)
2. create one app from that directory (say app1)
3. create another app from that directory (say app2)
4. get master key from app1 and export it in parent directory
5. confirm `rails credentials:edit` command works in app1
6. confirm `rails credentials:edit` command DOESN'T work and raise error in app2

Simpler steps:
1. create one app
2. export master key from it
3. create another app in the same shell session
4. cd second app and run `rails credentials:edit`

**Comment by januszm** [comment]
@okuramasafumi did you mean that one app on your server should use the `RAILS_MASTER_KEY` var, and the other app should read the master key from a **file**, and **ignore** the `RAILS_MASTER_KEY` var?

**Comment by y-yagi** [comment]
@okuramasafumi 
The original issue uses encrpyed secrets, but the reproduction step you presented uses credentials. 
These are commands that provide the same feature, but some implementations are different. It has also been updated with Rails 5.1.x and Rails 5.2.
Therefore, I can not be sure that its reproduction method is appropriate for reproducing the original issue...(I think that only the original issue creator knows this)

**Comment by smithcoin** [comment]
Are you sure that the master.key or RAILS_MASTER_KEY is the same as when you encrypted the credentials?

I had something similar to your error `rescue in _decrypt ...` when I had accidentally changed the master.key

**Comment by okuramasafumi** [comment]
@januszm No, what I meant was that rails should prefer loading key from file over loading from environment variable. In other words, if master key file exists rails should ignore environment variable so that multiple apps can use different keys.

**Comment by okuramasafumi** [comment]
@y-yagi Oops sorry that I didn't notice rails version is different than the original. I'd like to use rails `5.1.5` to confirm reproduction process within a few days.

**Comment by niightly** [comment]
Guys, anyone solves this issue?

**Comment by boboroshi** [comment]
I've replicated this and the issue lies as @okuramasafumi noted: Rails reads the environment variable RAILS_MASTER_KEY even if it is not called, or master.key is present in the app folder on the server. 

I have a Rails 5.1 app that uses environment variables and works fine. I have a rails 5.2 app that works fine as long as RAILS_MASTER_KEY is not defined in the production environment .bash_profile for the deploy user. Once it's defined, it ignores the app-included `master.key`

Expected:
App provided master.key would overrider ENV declared master key variables.

Actual:
RAILS_MASTER_KEY overrides master.key file. 

@javiermurillo's fix did not affect this behavior.

**Comment by BerkhanBerkdemir** [comment]
That [comment](https://github.com/rails/rails/issues/31397#issuecomment-387561117) didn't work for me, so I tried

```bash
bundle exec rails credentials:edit
```

I also set

```bash
export EDITOR=vim
```

---

Rails 5.2.0
Ruby 2.5.1 P57

**Comment by ricardopinto08** [comment]
check your master key at config/master, it must be the same in development and production, remember that file is ignored by git (gitignore) thinking in the security of your project.
If you don't have master.key in your production environment you should copy it.
It's a good idea too to set the environment variable associated to master.key.

**Comment by lucascaton** [comment]
Deleting the enc file and re-creating it doesn't seem a decent solution.
Also, I can confirm it still happens on Rails 5.2.1.

Has anyone found a decent solution?

Thank you.

**Comment by alienatix** [comment]
Workaround that solved this issue for me with capistrano deployment:

Add to ```.bashrc``` on your server:
```export SECRET_KEY_BASE=<key value>```

or 

simply use ```dotenv-rails``` gem, create ```.env``` file on your server (```shared/.env```), place your key there:

```SECRET_KEY_BASE:<key value>```

and then link this file in capistrano ```deploy.rb```:

```append :linked_files, 'config/database.yml', 'config/secrets.yml', '.env'```

**Comment by hirosmans** [comment]
> Deleting the enc file and re-creating it doesn't seem a decent solution.
> Also, I can confirm it still happens on Rails 5.2.1.
> 
> Has anyone found a decent solution?
> 
> Thank you.

it works for me EDITOR=vim rails credentials:edit 😄 rails 5.2

**Comment by acro5piano** [comment]
I had the same problem.
In my case, `config/credentials.yml.enc` has trailing newline.
So I deleted it with the following command:

```
perl -pe 's/\n//g' -i config/credentials.yml.enc 
```

Some text editor or Git hook add newline at the end of file, so I created a PR to delete error before decrypting:

https://github.com/rails/rails/pull/34059

**Comment by lww** [comment]
Solved it by copying the `master.key` file to the `shared/config` folder on the production server when using capistrano.

**Comment by krtschmr** [comment]
i can confirm

deleting `config/credentials.yml.enc` and rerun `rails credentials:edit` is fixing the issue in rails 5.2.2

**Comment by trungtinhandsome** [comment]
> So few things that I did before error came up:
> 
> 1. Run rails secrets:setup
>    2 Add line config.config.read_encrypted_secrets = true to production.rb
> 2. Run "EDITOR='subl --wait' rails secrets:edit" in terminal
> 3. Fill the file with data  ( attachment see)
> 
> * [example.txt](https://github.com/rails/rails/files/1554432/example.txt)
> 
> 1. Rails encrypt the file with file secrets.yml.key
> 2. Add secrets.yml.key to linked_files in capistrano
> 3. Use secrets inside database.yml , e.g
> 
> > <%= WorkoutRails::Application.secrets.database %>

It saves me, Thank you very much, my dude.

**Comment by umarov** [comment]
thanks @acro5piano 
Having a new line in the `config/credentials.yml.enc` breaks `rails secrets:edit`. I accidentally pressed save on the file and it added a new line.

**Comment by TheBlackHacker** [comment]
> 
> 
> i can confirm
> 
> deleting `config/credentials.yml.enc` and rerun `rails credentials:edit` is fixing the issue in rails 5.2.2

Save my day, thanks!

**Comment by scratchoo** [comment]
Delete config/credentials.yml.enc (**and also config/master.key**), then regenerate credentials file :

```
rm config/credentials.yml.enc
rm config/master.key
EDITOR=vim rails credentials:edit 
```

**Comment by sdhull** [comment]
`rm config/master.key` helped me. I needed to leave `credentials.yml.enc` in place, but I was mucking around with stuff and did not realize that a `master.key` file had been created and then I could no longer run specs 😳

**Comment by danman01** [comment]
Make sure you do not have a competing environment variable `SECRET_KEY_BASE`...that broke Heroku deployment for me.

Removed that environment variable (`heroku config:remove SECRET_KEY_BASE`) and for good measure regenerated keys like the above commenters advise, and set the env var on production `RAILS_MASTER_KEY` to be the same as my local `config/master.key`

**Comment by MichaMichael** [comment]
> hey @niightly, I had the same problem, I just delete `config/credentials.yml.enc`, then I ran `rails edit:credentials` and a new credentials file without issue was generated and everything works pretty well. I hope this helps!! Kudos

Thanks !

**Comment by natusdrew** [comment]
Yes, this error happens if you try to copy the credentials.yml.enc to another server and the master.key is different. The error means the new master.key can't decrypt the original credentials.yml.enc

You'll need to re-run 

```EDITOR="vim" rails credentials:edit```

On the production server

**Comment by iraritchiemeek** [comment]
I had this issue when using environment specific credentials on Heroku. 
What fixed it was removing `RAILS_MASTER_KEY` and replacing it with `RAILS_STAGING_KEY` (or whatever environment you want to use). It will not work if both keys are present.

**Comment by Korak-997** [comment]
> > i can confirm
> > deleting `config/credentials.yml.enc` and rerun `rails credentials:edit` is fixing the issue in rails 5.2.2
> 
> Save my day, thanks!
> 
> **My Solution:**
> 
> 1. Delete `config/credentials.yml.enc`
> 2. Run
> 
> ```
> $ export EDITOR=vim
> $ rails secrets:edit
> ```

I had same error on **Rails 6.0.3.4** and solved with that solution.

Thanks @TheBlackHacker

**Comment by sebasalmeidam** [comment]
> Yes, this error happens if you try to copy the credentials.yml.enc to another server and the master.key is different. The error means the new master.key can't decrypt the original credentials.yml.enc
> 
> You'll need to re-run
> 
> `EDITOR="vim" rails credentials:edit`
> 
> On the production server

Insipired in this answer, I was having the same issue, my local key was different from my production key. So I copy the production key on local and problem solved. 
I re-run:
EDITOR=nano rails credentials:edit

**Comment by roseliux** [comment]
nothing that was mention above help me, what I had to do in the end was to define an enviable variable with
`export RAILS_MASTER_KEY='your master key'`

**Comment by Zhi0105** [comment]
This is my case:

![rspec](https://user-images.githubusercontent.com/88585596/155780182-96243574-a32c-45bd-9650-5ba84247d0c7.JPG)

**Comment by kaka-ruto** [comment]
I found that your `RAILS_MASTER_KEY` needs to be the same as your environments `config/credentials/environment_name.key`

For my case, I had a production `RAILS_MASTER_KEY`, so when I tried to run the server locally, Rails found that this key differed from my `config/credentials/development.key` and threw the error.

So make sure the two are the same for the environment you're running at!
