### ISSUE TITLE
Anonymous ActiveRecord classes leak memory

### ISSUE THREAD

**Issue by ebeigarts** [rails/rails#31395]
Anonymous ActiveRecord classes (`Class.new(ActiveRecord::Base)`) are not garbage collected.

```
rails c
Loading development environment (Rails 5.1.4)
[1] pry(main)> nil; 1000.times { Class.new(ActiveRecord::Base) }; GC.start(full_mark: true); ActiveRecord::Base.descendants.size
1003
[2] pry(main)> nil; 1000.times { Class.new(ActiveRecord::Base) }; GC.start(full_mark: true); ActiveRecord::Base.descendants.size
2003
[3] pry(main)> nil; 1000.times { Class.new(ActiveRecord::Base) }; GC.start(full_mark: true); ActiveRecord::Base.descendants.size
3003
```

I have now discovered that anonymous classes are not supported #9002, but I can still create those classes without calling `establish_connection` on the child class.

```
> k = Class.new(ActiveRecord::Base); k.table_name = "users"; k.count
(1.0ms)  SELECT COUNT(*) FROM "users"
3216
```

A lot of rails test cases use anonymous classes, and this is the place I have learned to use them.

```
cd rails
ack 'Class.new\(ActiveRecord::Base\)' | wc -l
     125
```

Suggestions:

1. Do not use anonymous AR classes in rails test suite to avoid people learning to use them.
2. Raise exceptions when executing queries on anonymous classes, not just `establish_connection`.
3. Document this somewhere in the guides.

Or maybe we can fix the leak? Maybe someone already knows the place where it leaks?

**Comment by ebeigarts** [comment]
I think it might be caused by `ActiveSupport::DescendantsTracker`.

**Comment by ebeigarts** [comment]
The same problem is with `ActiveSupport::Callbacks`, which also uses `DescendantsTracker`.

```
[25] pry(main)> class Callbackable; include ActiveSupport::Callbacks; end
Callbackable < Object
[26] pry(main)> nil; 1000.times { Class.new(Callbackable) }; GC.start(full_mark: true); Callbackable.descendants.size
1000
[27] pry(main)> nil; 1000.times { Class.new(Callbackable) }; GC.start(full_mark: true); Callbackable.descendants.size
2000
```

**Comment by ebeigarts** [comment]
What is the purpose of `DescendantsTracker`, isn't it needed only in `development` environment for `reload` to work? Can we disable it when `cache_classes = true`?

**Comment by ebeigarts** [comment]
I have found a workaround, that doesn't leak memory `k = Class.new(ActiveRecord::Base); k.superclass.direct_descendants.delete(k)`, but this feels wrong and would brake `.descendants` method.

**Comment by rafaelfranca** [comment]
> Do not use anonymous AR classes in rails test suite to avoid people learning to use them.

The test suite is not the documentation. We can and want to use any feature of the language and the framework in our test suite. There are a lot of private API being used in the test suite.

> What is the purpose of DescendantsTracker, isn't it needed only in development environment for reload to work?

No. It is a faster way to go through descendants of a class without having to go through the slow `ObjectSpace`

> Can we disable it when cache_classes = true?

We can't because callbacks use it.

> Raise exceptions when executing queries on anonymous classes, not just establish_connection.

That seems to be the course of action but that doesn't prevents you to create anonymous classes and do not do any queries. So, I'd define a `inherited` hook in `ActiveRecord::Base` and raise an exception when inheriting without name. But that will only cause a source of memory leak since any class that extend DecendentTracker will have this problem.

**Comment by ebeigarts** [comment]
> That seems to be the course of action but that doesn't prevents you to create anonymous > classes and do not do any queries. So, I'd define a inherited hook in ActiveRecord::Base and raise an exception when inheriting without name. But that will only cause a source of memory leak since any class that extend DecendentTracker will have this problem.

Wouldn't it be better then to modify `DescendantsTracker#inherited`?

```diff
  module ActiveSupport
    module DescendantsTracker
      def inherited(base)
+      warn "Tracking descendants for anonymous classes can cause memory leaks" unless name
       DescendantsTracker.store_inherited(self, base)
       super
     end
  end
```

Maybe it would be better to just skip tracking for anonymous classes? Because anonymous classes is a nice ruby feature and I would like to use them also for AR classes.

```diff
  module ActiveSupport
    module DescendantsTracker
      def inherited(base)
-      DescendantsTracker.store_inherited(self, base)
+      DescendantsTracker.store_inherited(self, base) if name
       super
     end
  end
```

**Comment by matthewd** [comment]
Whether a class has a name has only a superficial relationship to whether it's going to "leak memory" -- the descendants tracker tracks all descendants. It's slightly more likely that an anonymous subclass will later go away, but not necessarily true: it might even be assigned to a constant at some later point.

Likewise, the existing exception has nothing to do with this "leak" -- there are other places we depend on a class having a name, for other reasons, and that's one of them.

**Comment by ebeigarts** [comment]
@matthewd so what are you suggesting we do with this?

Another idea - How about if we change `DescendantsTracker` to store `klass.object_id` instead of `klass` and use something like `ObjectSpace._id2ref(object_id)` to get the class and check if it is still alive (not garbage collected), the `DescendantsTracker` could be a bit slower, but this could fix the leaks. WDYT?

**Comment by matthewd** [comment]
If you describe the problem you're actually trying to solve by creating 1000s of AR::Base subclasses, I might be able to offer an opinion. Right now "don't do that" is definitely a front-runner.

**Comment by ebeigarts** [comment]
I have used this in multiple ways and I know there are workarounds, but anonymous classes are pretty basic ruby feature. At least it should give a warning.

1. Creating active models with dynamic attributes

```
class Estimation
  include ActiveModel::Model

  def self.instantiate_rows(rows, column_names)
    klass = Class.new(self)
    column_names.each do |attr|
      klass.send(:attr_accessor, attr)
    end
    rows.map do |attributes|
      klass.new attributes
    end
  end
end
```

2. Preloading active record associations with dynamic conditions to avoid N+1 queries

```
class ProjectPlan < ActiveRecord::Base
  has_many :plan_allocations # 1000+ records
end

klass = Class.new(ProjectPlan)
d = dates
klass.class_eval do
  has_many :plan_allocations, -> { within_interval(d.begin, d.end).order(:start_at) }
end

# Get all projects plans with allocations for period X
plans = klass.preload(:plan_allocations)
...
```

I could find more examples where I have used `Class.new`, most of them could be rewritten to avoid anonymous classes, but to me this was a surprise that anonymous AR/AM classes leak memory.

**Comment by ebeigarts** [comment]
Maybe we can use https://ruby-doc.org/stdlib-2.4.2/libdoc/weakref/rdoc/WeakRef.html in descendants tracker to allow anonymous classes?

**Comment by matthewd** [comment]
Thanks for the example. 

As I said, it has nothing to do with anonymous classes -- the behaviour you're objecting to is that all descendants of AR::Base are retained.

Yes, I'm open to considering a WeakRef in the tracker, if a race-free implementation isn't too ugly (and doesn't measurably impact performance, though I don't expect it would).

**Comment by ebeigarts** [comment]
By `race-free` do you mean threadsafe or something else?

I have found https://github.com/ruby-concurrency/ref and it states that `MRI Ruby 2.0+ has a good implementation of WeakRef`.

I could create a PR with WeakRef from stdlib and do some benchmarks. How that sounds? Is there anything else I should know?

**Comment by matthewd** [comment]
Thread-safe, and "not let WeakRef::RefError escape, no matter when the GC runs"-safe. Mentioned because I suspect doing the obvious thing for one might create issues on the other.

We'll also need to check what the existing test coverage looks like, especially as it's likely impractical to test the actual weak part.

**Comment by gregnavis** [comment]
@ebeigarts I'm using `temping` to generate temporary models in the test suite of [`active_record_doctor`](https://github.com/gregnavis/active_record_doctor) and run into that problem as well. In my case calling `ActiveSupport::DescendantsTracker.clear` didn't help but `ActiveSupport::DescendantsTracker.class_variable_get(:@@direct_descendants).clear` **did**. I added it to the teardown phase of my test suite.

**Comment by P9GIT** [comment]
We use anonymous AR Base classes for our custom SQL statements in a (dynamic) multi tenant host scenario.
Avoiding leaking on these classes would be great.

@ebeigarts 
Are there any unwanted/negative consequences of using your workaround?
You mentioned this would break the "#descendants" method. 

`k = Class.new(ActiveRecord::Base); k.superclass.direct_descendants.delete(k)`

Thanks.
Thomas Balsløv.

**Comment by ebeigarts** [comment]
@P9GIT That means that `ActiveRecord::Base.descendants` would not include the anonymous class, but in my case this is not an issue.

**Comment by P9GIT** [comment]
@ebeigarts 

Aha. We don't use the "#descendants" method directly anywhere so I assume it would also be safe for us then?
We simply execute SQL statements on the connector.
