### ISSUE TITLE
Request for rails website. Issue is not about Rails it's self.

### ISSUE THREAD

**Issue by jakeyeaton16** [rails/rails#31400]
### Steps to reproduce

(Guidelines for creating a bug report are [available
here](http://guides.rubyonrails.org/contributing_to_ruby_on_rails.html#creating-a-bug-report))

### Expected behavior
**This has to do with the guide's website rather then rails its self.**
When scrolling through a guide the side navigation (on your right side on desktop view) should follow users as they scroll.

### Actual behavior
When scrolling the side navigation stays at the top of the page

**Comment by y-yagi** [comment]
Thanks for the issue, but we don’t take feature requests here. We reserve the Rails issue tracker only for bugs in Rails. PR welcome. Thanks!
