### ISSUE TITLE
before_type_cast does not appear to work in Rails 5 for decimal columns

### ISSUE THREAD

**Issue by primerano** [rails/rails#31404]
### Steps to reproduce

Run this script

```
begin
  require "bundler/inline"
rescue LoadError => e
  $stderr.puts "Bundler version 1.10 or later is required. Please update your Bundler"
  raise e
end

gemfile(true) do
  source "https://rubygems.org"
  #gem "activerecord", "4.1.1"  # This works
  gem "activerecord", "5.1.4"
  gem "sqlite3"
end

require "active_record"
require "minitest/autorun"

Minitest::Test = MiniTest::Unit::TestCase unless defined?(Minitest::Test)
ActiveRecord::Base.establish_connection(adapter: "sqlite3", database: ":memory:")
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :posts, force: true do |t|
    t.decimal :prediction
  end
end

class Post < ActiveRecord::Base
end

class BugTest < Minitest::Test
  def test_association_stuff
    post = Post.create!(prediction: '-11')
    assert_equal '-11', post.prediction_before_type_cast
  end
end
```

### Expected behavior

I expected _before_type_cast to return the data as entered by the user.

### Actual behavior

I get a BigDecimal

Expected: "-11"
 Actual: -0.11e2

### System configuration
**Rails version**:
5.1.4
**Ruby version**:
2.4.2p198

**Comment by primerano** [comment]
Note..  This does work with new instead of create.   But in rails 4.1 it also worked in create.   I'm actually using this in a validation so I'll come up with a better example of my issue if this is WAD.

**Comment by primerano** [comment]
Between rails 4 and 5 before_type_cast changed only have the original value before saving to the database.

Once saved, before_type_cast returns the database value.

The problem this causes me is if I have a validation that uses before_type_cast, calling valid? on a saved record will return false.  Test case follows..
```

# frozen_string_literal: true
begin
  require "bundler/inline"
rescue LoadError => e
  $stderr.puts "Bundler version 1.10 or later is required. Please update your Bundler"
  raise e
end

gemfile(true) do
  source "https://rubygems.org"
  #gem "activerecord", "4.1.1"  # This works
  gem "activerecord", "5.1.4"
  gem "sqlite3"
end

require "active_record"
require "minitest/autorun"

Minitest::Test = MiniTest::Unit::TestCase unless defined?(Minitest::Test)
ActiveRecord::Base.establish_connection(adapter: "sqlite3", database: ":memory:")
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :posts, force: true do |t|
    t.decimal :prediction
    t.float :floater
    
  end
end

class Post < ActiveRecord::Base
  validate :prediction_has_no_decimal_places
  def prediction_has_no_decimal_places
    
    decimals_places = prediction_before_type_cast.to_s.split('.')[1].try(:length) || 0
    if decimals_places > 0
      errors[:base] << "Predicion can not have decimal places"
    end
  end
end

class BugTest < Minitest::Test
  def test_association_stuff

    post = Post.create(prediction: '-11', floater: '1.23')
    assert_equal false, post.new_record?
    assert_equal true, post.persisted?
    assert_equal true, post.valid?
    assert_equal '-11', post.prediction_before_type_cast
  end
end
```

**Comment by rafaelfranca** [comment]
@sgrif can you check if this issue is valid or this is expected behavior?

**Comment by sgrif** [comment]
:eyes:

**Comment by sgrif** [comment]
It's the expected behavior. Once you save, the "before_type_cast" version of all attributes becomes what is currently persisted in the database. This is required for us to guarantee that your model is not considered dirty. Consider the following:

```ruby
user.name << " hello"
user.save
assert_not user.changed?
```

Additionally, you shouldn't be relying on the exact value of `_before_type_cast`. Your code will also fail if:
- The database gives us a binary representation
- The value gets cast by the database driver before getting to Active Record
- Someone assigns a value that isn't a string.

It sounds like you're assuming that `_before_type_cast` means "direct user input", but that's not always the case. We added a method for this in Rails 5 (or maybe it was 4.2). You should probably at minimum be doing `return unless prediction_came_from_user?` in that validation, and probably also checking whether it's a string.

**Comment by primerano** [comment]
Thanks for the insight @sgrif - my validation did seem a bit fragile after writing out the test case.

**Comment by abhi-patel** [comment]
@sgrif @primerano - This somehow does not work for DateTime columns.
```
ActiveRecord::Schema.define do
  create_table :posts, force: true do |t|
    t.datetime :publish_time
    t.integer :ref_number
  end
end


Post.create(publish_time: Date.today, ref_number: 3)
post = Post.last
post.ref_number = 'abcdedf'
=> "abcdedf"
post.ref_number
=> 0

post.ref_number_before_type_cast
=> "abcdedf" #this works

post.publish_time = 'xyz'
=> "xyz"
post.publish_time
=> nil
post.publish_time_before_type_cast
=> nil #This should have been "xyz"
post.publish_time_came_from_user?
=> true
```
