### ISSUE TITLE
Unable to access main_app secrets from Rails engine initializer

### ISSUE THREAD

**Issue by augustosamame** [rails/rails#31438]
### Steps to reproduce

Create a Rails main app
Create Rails mountable engine
Mount engine in main rails app

Edit the secrets.yml in main app:

```
S3_AWS_ACCESS_KEY_ID: "1234567890"
S3_AWS_SECRET_ACCESS_KEY: "1234567890"
CARRIERWAVE_CONFIG_FOG_DIRECTORY: "mybucketname"
```

create an initializer in engine. For example:

config/initializers/carrierwave.config

```
require 'carrierwave'
require 'carrierwave/storage/fog'

CarrierWave.configure do |config|
  config.fog_provider = 'fog/aws'

  config.fog_credentials = {
    :provider               => 'AWS',
  :aws_access_key_id      => Rails.application.secrets.S3_AWS_ACCESS_KEY_ID,
  :aws_secret_access_key  => Rails.application.secrets.S3_AWS_SECRET_ACCESS_KEY
  }
  config.fog_directory  = Rails.application.secrets.CARRIERWAVE_CONFIG_FOG_DIRECTORY
  config.storage = :fog
end
```

### Expected behavior
Engine initializer should be able read Rails.application secrets from main_app

### Actual behavior
The variables set in engine initializer are set to nil
It works fine in models and controllers, but not in initializer

Ref: https://stackoverflow.com/questions/47744985/access-to-main-app-secrets-from-rails-engine-initializer

### System configuration
**Rails version**: 5.1.4

**Ruby version**: 2.3.1

**Comment by kaspth** [comment]
Thanks for the issue!

@y-yagi you have a knack for engines, care to take a look? 😊

**Comment by y-yagi** [comment]
Can you provide a sample application that reproduces the issue?
I tried to reproduce with a sample application(https://github.com/y-yagi/reproduce_31438). But could not reproduce.

**Comment by y-yagi** [comment]
I close because the issue can not be reproduced.
If you can prepare the reproduction procedure, please feel free to reopen. Thanks.
