### ISSUE TITLE
ActiveRecord 5.1 - #includes raises NoMethodError when case doesn't match on join columns

### ISSUE THREAD

**Issue by seandilda** [rails/rails#31445]
### Steps to reproduce

(This is how my app is setup, there may be other configurations that produce the same error).

schema.rb:
```ruby
create_table "activities"  do |t|
  t.string 'username'
end
create_table 'users', id: false do |t|
  t.string 'username', null: false
end
```

Models:
```ruby
class Activity < ApplicationRecord
  belongs_to :user, foreign_key: :username, optional: true
end
class User < ApplicationRecord
  self.primary_key = :username
  has_many :activities
end
```

Set the username on an activity to a username that doesn't exist in the users table.
Run: 
```ruby
Activity.all.includes(:user).to_a
```

(I realize this is a case of bad data consistency, but I'm dealing with data from other systems, and I don't want to lose data or generate artificial data.)

### Expected behavior

I should get an array of all Activities with all relevant users preloaded, and the activities that don't have a valid matching user should return `nil` when I call `activity.user`.
This is the same behavior you'd get if you didn't use includes, except the users would be preloaded.

### Actual behavior

NoMethodError: undefined method `association' for nil:NilClass

### System configuration
**Rails version**: 5.1.4

**Ruby version**: 2.4.1

**Comment by meinac** [comment]
I tried but couldn't reproduce the issue, can you please try to provide an executable reproduction script by using the information given in [this](http://guides.rubyonrails.org/contributing_to_ruby_on_rails.html#create-an-executable-test-case) page?

**Comment by seandilda** [comment]
Thanks, the reproduction script made this a lot easier to narrow down.
Turns out I was mistaken, the issue actually comes when you're joining on a string key and there is different capitalization.  The following script reproduces it.

I had to switch to mysql backend to reproduce it.  In case it matters, my backend is mariadb 5.5.56

```ruby
# frozen_string_literal: true

begin
  require "bundler/inline"
rescue LoadError => e
  $stderr.puts "Bundler version 1.10 or later is required. Please update your Bundler"
  raise e
end

gemfile(true) do
  source "https://rubygems.org"

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  # Activate the gem you are reporting the issue against.
  gem 'activerecord', '5.1.4'
  gem 'mysql2'
end

require "active_record"
require "minitest/autorun"
require "logger"

# Ensure backward compatibility with Minitest 4
Minitest::Test = MiniTest::Unit::TestCase unless defined?(Minitest::Test)

# This fails on mysql connections, but not sqlite
ActiveRecord::Base.establish_connection(
  adapter: 'mysql2',
  host: ENV['DB_HOST'],
  port: 3306,
  database: ENV['DB_NAME'],
  username: ENV['DB_USER'],
  password: ENV['DB_PASS'],
)
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :activities, force: true do |t|
    t.string "username"
  end

  create_table :users, force: true do |t|
    t.string "username"
  end
end

class Activity < ActiveRecord::Base
  belongs_to :user, primary_key: :username, foreign_key: :username
end

class User < ActiveRecord::Base
  has_many :activities, primary_key: :username, foreign_key: :username
end


class BugTest < Minitest::Test
  def test_association_stuff

    Activity.create! username: 'user'
    User.create! username: 'USER'

    assert_equal 1, Activity.all.includes(:user).to_a.count
  end
end
```

**Comment by htanata** [comment]
I have a pull request for this here: #31752.

**Comment by htanata** [comment]
Still broken on `master` (38dbc8e2b87eb6b303180c45ccb153e72da87c44). I've also rebased my PR #31752 against latest master.

**Comment by jules2689** [comment]
This issue is caused by mysql comparing in a case insensitive mode.
One way I've fix this is using `, options: "ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin"` on the table. The `utf8_bin` collation causes the case to be taken into account

**Comment by bjeanes** [comment]
I'm also getting this with Postgres when joining on a `citext` column (holding email addresses).

**Comment by Silex** [comment]
This also happens more viciously if you have `stephane` in one table and `stéphane` in the other, because MySQL also consider these equivalent.

**Comment by kapcod** [comment]
As stated by the author of the issue 3 years ago, Rails `includes` is supposed to be smart enough to give exactly the same results as without `includes` just with preloading. Worst case, in case the `case` doesn't match it should ignore the value not throw exception.

Rails 6 still throws this error in case of same value (as per DB) but different case.
> NoMethodError: undefined method `first' for nil:NilClass

Having a case-insensitive column is OK in any DB and actually default in MySQL, so it would be nice for Rails to handle that correctly.
Ideally it should be transparent for the developer and should "just work". As I said earlier, worst case it should ignore the value with wrong case, not throw exception. Also we could be allowed to add `case_sensitive: false` option to `has_many` or `has_one` and so tell Rails to compare the values accordingly.

**Comment by byroot** [comment]
I reran the provided repro script updated for Rails edge, and the test passed, I'm going to assume someone fixed that bug.
