### ISSUE TITLE
Autoloading issue when the parent module defines the same constant

### ISSUE THREAD

**Issue by adimitrov** [rails/rails#31459]
### Description

Class autoloading returns the wrong class when trying to load a non existing constant. Its an edge case that only happens only if the parent module defines the same constant, which is not yet autoloaded. It also happens sometimes for existing constants, but the issue is the same and this test its more obvious and easy to reproduce.

### Steps to reproduce

```
# app/domain/foo.rb
class Foo
end

# app/domain/foo/update.rb
class Foo
  class Update
  end
end

# app/domain/foo/bar.rb
class Foo
  class Bar
  end
end
```

```
$ rails c
Loading development environment (Rails 5.1.4)
irb(main):001:0> Foo::Bar::Update # This class does not exist !
=> Foo::Update
irb(main):002:0> Foo::Bar::Update
NameError: uninitialized constant Foo::Bar::Update
  from (irb):2
irb(main):003:0>
```

Here is a example [minimal rails app](https://github.com/adimitrov/autoloading_bug), including two test cases that reproduces the issue.
I've come to the conclusion that the offending code is https://github.com/rails/rails/blob/master/activesupport/lib/active_support/dependencies.rb#L533
### Expected behavior
It should raise NameError in any case.

### Actual behavior
It returns the wrong constant on the first call, after that it correctly raises NameError

### System configuration
**Rails version**: Rails 5.1.4

**Ruby version**: ruby 2.3.1p112 (2016-04-26 revision 54768) [x86_64-darwin16]

**Comment by rohitpaulk** [comment]
I don't think it's possible to fix this, [as mentioned in the comment above the line you pasted](https://github.com/rails/rails/blob/1a5bf01fe024eb1d91903094327d937f7abcb24d/activesupport/lib/active_support/dependencies.rb#L514-L530). 

SInce `const_missing` doesn't allow access to `Module.nesting` at the point of the call, we can't differentiate between the following calls if `Update` hasn't been loaded already: 

```ruby
class Foo
  class Bar
    Update # Should use Foo::Update
  end
end
```

and
 
```ruby
class Foo::Bar
  Update # Should NOT use Foo::Update
end
```

**Comment by georgeclaghorn** [comment]
Yeah, this is a documented quirk of constant autoloading.

**Comment by rohitpaulk** [comment]
Link to docs: http://guides.rubyonrails.org/autoloading_and_reloading_constants.html#autoloading-algorithms-qualified-references
