### ISSUE TITLE
Ruby 2.5 BigDecimal#dup is deprecated 

### ISSUE THREAD

**Issue by yahonda** [rails/rails#31465]
BigDecimal#dup is deprecated in BigDecimal 1.3.3, which is part of Ruby 2.5.0 rc1 https://github.com/ruby/bigdecimal/pull/85

### Steps to reproduce

```ruby
$ cd activerecord
$ ARCONN=postgresql bundle exec ruby -Itest -w test/cases/adapters/postgresql/money_test.rb -n test_default
```

### Expected behavior
It should finish without warnings.

### Actual behavior
```ruby
$ ARCONN=postgresql bundle exec ruby -Itest -w test/cases/adapters/postgresql/money_test.rb -n test_default
Using postgresql
Run options: -n test_default --seed 23102

# Running:

/home/yahonda/git/rails/activemodel/lib/active_model/attribute.rb:151: warning: BigDecimal#dup is deprecated.
.

Finished in 0.035841s, 27.9010 runs/s, 55.8019 assertions/s.
1 runs, 2 assertions, 0 failures, 0 errors, 0 skips
$
```
### System configuration
**Rails version**:master branch

**Ruby version**:ruby 2.5.0rc1 (2017-12-14 trunk 61243) [x86_64-linux]

**Comment by yahonda** [comment]
It would be addressed by changing from `true` to `false`. Let me check and test with all versions of Ruby versions 2.2, 2.3, 2.4 and 2.5.0 rc.

https://github.com/rails/rails/blob/06dbc028da444079d82b36ea4325a924982838a6/activesupport/lib/active_support/core_ext/object/duplicable.rb#L113-L115

**Comment by yahonda** [comment]
Based on https://github.com/ruby/bigdecimal/pull/85#issuecomment-351915783 this warning is going to be removed.

**Comment by rafaelfranca** [comment]
That sounds right. I'm going to close this issue then.

**Comment by y-yagi** [comment]
Fixed by https://github.com/ruby/bigdecimal/pull/93
