### ISSUE TITLE
headers argument to controller test_case process is ignored

### ISSUE THREAD

**Issue by runephilosof** [rails/rails#31472]
### Steps to reproduce
Do as the guides describe in a controller test

```
get article_url, params: { id: 12 }, headers: { "HTTP_REFERER" => "http://example.com/home" }
```

Then check for `request.referer` in the controller.

http://guides.rubyonrails.org/v5.0/testing.html#what-to-include-in-your-functional-tests
http://guides.rubyonrails.org/v5.1/testing.html#what-to-include-in-your-functional-tests

### Expected behavior
`request.referer` returns "http://example.com/home".

### Actual behavior
`request.referer` returns nil.

### System configuration
**Rails version**:
5.0.6

**Ruby version**:
2.3.5

**Comment by y-yagi** [comment]
Can you please provide a sample application that reproduces the issue?

**Comment by gwincr11** [comment]
I took some time to investigate this. From what I can tell, the referer is coming from an [Action Dispatch item that is using a Rack module](https://github.com/rails/rails/blob/9668cc3bb03740b13477df0832332eec71563bc5/actionpack/lib/action_dispatch/http/request.rb#L23) to get the referer from the Rack env using the env https://github.com/rack/rack/blob/master/lib/rack/request.rb#L50-L52. 

This is basically passed straight through and the only place I can find to update the object where the route settings and the rack object are together are in the [Action Dispatch Journey Router](https://github.com/rails/rails/blob/9668cc3bb03740b13477df0832332eec71563bc5/actionpack/lib/action_dispatch/journey/router.rb#L32) in the serve method. 

I think basically we would need to grab the settings from the router merge them in if they are missing. 

Here is a repo with the broken referer being shown on the index. https://github.com/gwincr11/broken_things

**Comment by runephilosof** [comment]
I have just tried setting up a sample app the reproduces the issue.
https://gitlab.com/rp1/bug-rails-controller-test.git

I discovered that my issue was with rspec-rails, not Rails.
I haven't tested with older versions < 5.1.4.
