### ISSUE TITLE
An encrypted secrets file containing invalid YAML cannot be edited if used by development environment

### ISSUE THREAD

**Issue by m-z-b** [rails/rails#31486]
### Steps to reproduce

1. Create a rails project with encrypted secrets
2. Add `config.read_encrypted_secrets = true` to config/environments/development.rb
3. Run `rails secrets:edit` and edit the secrets file so that it contains some invalid YAML
4. Exit the editor
5. Run `rails secrets:edit`

The editor will fail to load as an attempt is made to parse the encrypted secrets file before the editor starts.

A workaround is to use an alternative environment which does not load the secrets file, e.g. 
`RAILS_ENV=test rails secrets:edit`

### Expected behavior
The editor should load and display the encrypted secrets file even though the YAML is invalid.
The secrets file /should not be loaded and parsed before performing a simple edit function.

### Actual behavior
An exception is raised and a stack trace is printed. The editor does not start.

### System configuration
**Rails version**: 5.1.4

**Ruby version**: 2.4.2p198

**Comment by y-yagi** [comment]
Thanks for creating an issue. This is duplicate with #30851. Let's track on #30851.
