### ISSUE TITLE
Environment variables missing, depending on rails cli context

### ISSUE THREAD

**Issue by flah00** [rails/rails#31498]
### Steps to reproduce

We have an application, which we upgraded from 5.0 to 5.1.4. It relies on some environment variables, to run correctly. I created an initializer, which exits, if the variables are not set.

#### config/initializers/vars.rb

```ruby
vars = %w|VAR1 VAR2 VAR3|
errs = vars.inject([]) do |memo, var|
  ENV[var].blank? ? memo << var : memo
end
if errs.any?
  puts "Missing env vars #{errs.join(', ')}"
  exit 1
end
```

1. Try starting web server, with env vars set
    * `VAR1=foo VAR2=bar VAR3=baz rails s`
    * This succeeds, for me (expected)
1. Try starting console, with env vars set
    * `VAR1=foo VAR2=bar VAR3=baz rails c`
    * This fails, for me (unexpected)

### Expected behavior
My application should start, reliably, when the env vars are set
My application should fail to start, reliably, when the env vars are not set

### Actual behavior
It seems like my application fails to start the console, whether environment variables are explicitly set or not. 

It seems like my application web server can start, if the environment variables are set. 

#### Starting rails web server

I am able to start my web server, if I set the env vars correctly.

```console
$ rails s
Missing env vars VAR1, VAR2, VAR3
$ VAR1=foo VAR2=bar VAR3=baz rails s
...
[10827] Use Ctrl-C to stop
[10827] * Starting control server on unix:///Users/pchampon/devel/ld-api/tmp/pumactl.sock
[10827] - Worker 0 (pid: 10841) booted, phase: 0
[10827] - Worker 1 (pid: 10842) booted, phase: 0
```

#### Starting rails console

I am unable to start a console, whether or not the env vars are defined

```console
$ rails c
Missing env vars VAR1, VAR2, VAR3
$ VAR1=foo VAR2=bar VAR3=baz rails c
Missing env vars VAR1, VAR2, VAR3
```

### System configuration
**Rails version**: 5.1.4

**Ruby version**: 2.3.1p112

**Comment by Jecko-o** [comment]
Just tried, on Rails 5.1.4 and Ruby 2.4.0 everything works fine on my machine.

**Comment by flah00** [comment]
Ok. Any thoughts on what might cause this.

Would you like to have a go, with my Gemfile? Do you think using a
different version of ruby, from the one I'm using, would make the
difference?

**Comment by y-yagi** [comment]
Everything works fine in my environment too. Maybe it is your application's problem. So I close this.  

If you cannot fix the issue, please use the [mailing list](https://groups.google.com/forum/#!forum/rubyonrails-talk) or StackOverflow for questions/help, where a wider community will be able to help you. We reserve the issues tracker for issues only.
