### ISSUE TITLE
double decrement counter_cache when updating association nil

### ISSUE THREAD

**Issue by hw676018683** [rails/rails#31491]
### Steps to reproduce
```
class A < ApplicationRecord
  has_many :bs
end


class B < ApplicationRecord
  belongs_to :a, counter_cache: true
end
```

```
  a = A.create
  b = a.bs.create
```

```
a.reload.bs_count # => 1
b.update a: nil
a.reload.bs_count # => -1
```

update sql
```
   (0.2ms)  BEGIN
  A Update All (0.4ms)  UPDATE "as" SET "bs_count" = COALESCE("bs_count", 0) - 1 WHERE "as"."id" = $1  [["id", 1]]
  B Update (0.3ms)  UPDATE "bs" SET "a_id" = $1, "updated_at" = $2 WHERE "bs"."id" = $3  [["a_id", nil], ["updated_at", "2017-12-17 06:02:26.884865"], ["id", 28]]
  A Update All (0.2ms)  UPDATE "as" SET "bs_count" = COALESCE("bs_count", 0) - 1 WHERE "as"."id" = $1  [["id", 1]]
   (0.2ms)  COMMIT
```

### Expected behavior
```
a.reload.bs_count # => 1
b.update a: nil
a.reload.bs_count # => 0
```

### Actual behavior
as the above

### System configuration
**Rails version**: 2.3.1

**Ruby version**: 5.2.0.beta2

**Comment by hw676018683** [comment]
when updating , rails handles counter_cache in two places
- https://github.com/rails/rails/blob/v5.2.0.beta2/activerecord/lib/active_record/associations/belongs_to_association.rb#L11
- https://github.com/rails/rails/blob/v5.2.0.beta2/activerecord/lib/active_record/associations/builder/belongs_to.rb#L33

In #replace, dont set `@_after_replace_counter_called` when record is nil.

Is it necessary to handle counter_cache in #replace? 
If rm `@_after_replace_counter_called`, is there something wrong to only handle counter_cache in after_update callback when updaing?

`b.a = a` will incement a.bs_count, but b doesnt save, which i think is an expected behaving

**Comment by tradeli** [comment]
Could be related to #31493

**Comment by xymbol** [comment]
I'm seeing this issue as well.
