### ISSUE TITLE
Unable to send Rails.ajax request with Content-Type application/json

### ISSUE THREAD

**Issue by michaldarda** [rails/rails#31507]
### Steps to reproduce

Hello, I am trying to send JSON data using `Rails.ajax` `rails-ujs` method, the problem is I am unable to set content-type to `application/json`, because the configuration is very limited. Is this method even designed to be used directly? There is little documentation about that part of Rails.

I have reviewed https://github.com/rails/rails/commit/ad3a47759e67a411f3534309cdd704f12f6930a7 and what concerns me is that fragment:

```coffeescript
+  # Set Content-Type only when sending a string
 +  # Sending FormData will automatically set Content-Type to multipart/form-data
 +  if typeof options.data is 'string'
 +    xhr.setRequestHeader('Content-Type', 'application/x-www-form-urlencoded; charset=UTF-8')
```

And my HTTP request

```javascript
  Rails.ajax({
    type: 'PATCH',
    dataType: 'json',
    accept: 'json',
    url: options.url,
    data: {
      image: cropperImage.src,
      crop_x: left,
      crop_y: top,
      crop_w: width,
      crop_h: height
    },
    success: (response) => {
    },
    failure: (response) => {
    }
  });

```

### Expected behavior
I should be able to set my Content-Type, or it should be set automatically if I send JSON object

### Actual behavior
Content-Type is magically overridden

### System configuration
**Rails version**: 5.1.4

**Ruby version**: 2.4.2

**Comment by georgeclaghorn** [comment]
> Is this method even designed to be used directly?

No, it exists only for use by `rails-ujs` itself. Use XMLHttpRequest, the WHATWG fetch API, or your favorite Ajax request utility to send requests from your own JavaScript code.

> There is little documentation about that part of Rails.

In general, methods and classes that don’t appear in the API docs or the guides are for internal use only.

**Comment by dsandstrom** [comment]
@georgeclaghorn Can you clarify something?  The Rails teams is saying to not use `Rails.ajax` in our JavaScript.  You recommend using XMLHttpRequest instead?  So we should build the headers and the cross browser protection ourselves instead of using `Rails.ajax` from rails_ujs?  I'm wondering if I should report a bug in 5.1.5.

**Comment by iv-mexx** [comment]
I'm confused now - #31002 was merged with a description of 

> When we call Rails.ajax outside rails-ujs.js, we must define beforeSend even though it's empty function. I think Rails.ajax is not private api so it's more useful.

which sounds to me like its intended to be used outside of rails-ujs.js as well...

**Comment by Leoxxid** [comment]
I'm trying make a rails-ujs ajax and the call was returning false.
```
Rails.ajax({
  url: "/teste",
  type: "GET",
  success: function(data) {
    console.log('Carregou')
  }
})
```

I resolved this with the code bellow  
```
Rails.ajax({
  dataType: 'script',
  url: "/teste",
  type: "GET",
  beforeSend: function() {
    return true
  },
  success: function(data) {
    console.log('Carregou')
  }
})
```
Now the ajax call  is working. Hope this helps someone!

**Comment by baldursson** [comment]
I also think it's a bit weird to pull in another library to perform such a simple task when rails-ujs is already built-in and fully capable. I thought it would work by setting content type manually, like this:

    Rails.ajax({
      type: 'PATCH',
      dataType: 'json',
      accept: 'json',
      url: options.url,
      data: {
        image: cropperImage.src,
        crop_x: left,
        crop_y: top,
        crop_w: width,
        crop_h: height
      },
      beforeSend: (xhr, options) => {
        xhr.setRequestHeader('Content-Type', 'application/json')
        return true
      },
      success: (response) => {
      },
      failure: (response) => {
      }
    });

But when the request arrives at the controller, the content type is "application/x-www-form-urlencoded" again and the JSON data has been discarded.

I ended up using FormData instead. That makes working directly with rails-ujs less awkward:


    let formData = new FormData()
    
    formData.append('image', cropperImage.src)
    formData.append('crop_x', left)
    formData.append('crop_y', top)
    formData.append('crop_w', width)
    formData.append('crop_h', heigh)

    Rails.ajax({
      type: 'PATCH',
      url: options.url,
      data: formData,
      success: (response) => {
      },
      failure: (response) => {
      }
    })

**Comment by dsandstrom** [comment]
Thank you @Leoxxid , adding the `beforeSend` method worked.  I can upgrade past 5.1.4 now, which I had to do to get mariadb working again (https://github.com/rails/rails/pull/31521).  Hopefully `Rails.ajax` stays public.

```coffee
Rails.ajax(
  url: path
  type: 'PUT'
  dataType: 'script'
  beforeSend: -> true
)
```

**Comment by ftes** [comment]
Here is my workaround to put/post with `Content-Type: application/json`.

It works by setting `options.data` in the `beforeSend` callback. This way the internal `Rails.ajax.createXHR` method does not set the `Content-Type` header first.
https://github.com/rails/rails/blob/master/actionview/app/assets/javascripts/rails-ujs/utils/ajax.coffee#L53


```js
    Rails.ajax({
      url: 'http://some-url.com',
      type: 'put',
      beforeSend(xhr, options) {
        xhr.setRequestHeader('Content-Type', 'application/json; charset=UTF-8')
        // Workaround: add options.data late to avoid Content-Type header to already being set in stone
        // https://github.com/rails/rails/blob/master/actionview/app/assets/javascripts/rails-ujs/utils/ajax.coffee#L53
        options.data = JSON.stringify(data)
        return true
      },
    });
```

**Comment by archonic** [comment]
@ftes's comment wasn't working for me but I found that setting `dataType: 'json'` works.
