### ISSUE TITLE
"string".freeze is not working - ruby@2.3.4p301 rails@3.2.22.5

### ISSUE THREAD

**Issue by ritikesh** [rails/rails#31505]
### Steps to reproduce
Create a new rails app using ruby 2.3.x and rails 3.2.22.x. Open rails console and try the below:
```ruby
2.3.4 :003 > "hello".freeze.object_id
 => 70129481049280
2.3.4 :004 > "hello".freeze.object_id
 => 70129481018940

```
### Expected behavior
object_id should be the same for both cases.

### Actual behavior
They're different

Trying the same in irb works as expected:
```ruby
2.3.4 :001 > "hello".freeze.object_id
 => 70332438486000
2.3.4 :002 > "hello".freeze.object_id
 => 70332438486000
```

### System configuration
**Rails version**: 3.2.22.5

**Ruby version**: 2.3.4p301

**Comment by eileencodes** [comment]
Hello @ritikesh! Thanks for the report. Unfortunately Rails 3.2 is no longer supported so we can't fix the bug you're seeing in Rails 3.2. If you experience this bug in Rails 5+ please let me know and I'll reopen this issue.
