### ISSUE TITLE
Update 5.1 release notes to include final removal of `HashWithIndifferentAccess` interface from `AC::Parameters`

### ISSUE THREAD

**Issue by JanBussieck** [rails/rails#31512]
Since version 5.0 `ActionController::Parameters` no longer inherits from `HashWithIndifferentAccess`, however, although the inheritance was removed, it was still possible to call `Enumerable` methods on `params` (method calls where being delegated in a afaik `method_missing`) and merely a deprecation warning was shown.
The removal of the actual behavior only happened in 5.1, however there is no mention of this in the release notes, which think such a major change would merit. I'd open a PR but I am unsure of the exact wording, since the release notes of 5.0 already state:
> Make ActionController::Parameters no longer inherits from HashWithIndifferentAccess. 

Maybe something like:

> Remove deprecated support for calling `HashWithIndifferentAccess` methods on `ActionController::Parameters`

Thanks!

**Comment by unimatrixZxero** [comment]
Your reasoning is good.

**Comment by eileencodes** [comment]
Makes sense @JanBussieck, can you open a PR with your suggestion? Thanks!

**Comment by JanBussieck** [comment]
Will do!

**Comment by y-yagi** [comment]
Fixed by #31545.
