### ISSUE TITLE
Rspec rails Logger issue

### ISSUE THREAD

**Issue by anson2590** [rails/rails#31510]
### Steps to reproduce

(Guidelines for creating a bug report are [available
here](http://guides.rubyonrails.org/contributing_to_ruby_on_rails.html#creating-a-bug-report))

### Expected behavior
Im writing rspec and it is failing issue is with rails logger.

### Actual behavior
this is the code im using, "expect(Rails.logger).to receive(:info).with('abc')" its throwing error saying " expected: ("abc") 
got: ("Processing by App::SampleController#personal_info as HTML") . "

### System configuration
**Rails version**:
5.1
**Ruby version**:
2.4.1

**Comment by y-yagi** [comment]
Please use the [mailing list](https://groups.google.com/forum/#!forum/rubyonrails-talk) or StackOverflow for questions/help, where a wider community will be able to help you. We reserve the issues tracker for issues only. 
Also, RSpec is not part of Rails.  If it is really a bug, please create an issue to RSpec repository.
