### ISSUE TITLE
rake db:migrate is creating tables from other rails projects in my laptop

### ISSUE THREAD

**Issue by fcalderonnearsoft** [rails/rails#31529]
I have created a new rails project and I have added a migration to create a table called `blogs`. When I ran `rake db:migrate` it created this table along with other tables I have set in other projects I have in my laptop.
Under `db/migrate` I have only 1 file with the migration I added, there's no reference in the project of the other tables, for some reason it is pulling the migrations from other projects and adding it to my DB project

### Expected behavior
It must run migrations that are under `db/migrate` in my current project
### Actual behavior
It is running migrations under `db/migrate` of my current project and other projects.

### System configuration
**Rails version**:
5.1.4
**Ruby version**:
2.4.1

**Comment by kobaltz** [comment]
That's strange behavior. Does this behavior also happen after a reboot? My thought is that Spring could be running from one of the apps and things are getting mixed up.

Try `bin/spring stop` and ensure that all instances are stopped `ps aux | grep spring`.

**Comment by y-yagi** [comment]
Can you please provide a sample application that reproduces the issue?
Or, please give us more information on how to reproduce this issue, otherwise, there is nothing we can do.

**Comment by fcalderonnearsoft** [comment]
I fixed by stopping all `spring` instances. Thanks @kobaltz
