### ISSUE TITLE
Active storage direct upload to GCS

### ISSUE THREAD

**Issue by benbonnet** [rails/rails#31523]
### Steps to reproduce

cors.json :
```
[
  {
    "origin": ["*"],
    "responseHeader": ["Access-Control-Allow-Origin"],
    "method": ["PUT","POST","GET"],
    "maxAgeSeconds": 3600
  }
]
```
Applied to the concerned bucket via `gsutil cors set cors.json gs://bucket`

storage.yml:
```
google:
  service: GCS
  project: "project"
  credentials: <%= Rails.root.join("/pah/to/gcloud-credentials.json") %>
  bucket: bucket
```

config.routes.rb :
```
Rails.application.routes.draw do
  root to: 'items#index'
  resources :items
end

```
app/models/item.rb :
```
class Item < ApplicationRecord
  has_many_attached :images
end
```

app/views/items/index.html.erb :
```
<%= form_with model: Item.new, local: true do |form| %>
  <%= form.text_field :title, placeholder: "Title", value: 'demo' %><br>
  <%= form.file_field :images, multiple: true, direct_upload: true %><br>
  <%= form.submit %>
<% end %>
```

app/controllers/items_controller.rb :
```
class ItemsController < ApplicationController
  def index
  en
  def create
    item = Item.create! params.require(:item).permit(:title)
    item.images.attach(params[:item][:images])
    redirect_to item
  end
end
```

### Expected behavior
configured both s3 and gcs with relevant cors. Without direct upload, everything works ok, s3 and gcs. Direct uploads fails on gcs

### Actual behavior
From console :
`Failed to load https://storage.googleapis.com/... Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:3000' is therefore not allowed access.`

### System configuration
**Rails version**: Rails 5.2.0.beta2 (`gem 'rails', git: 'https://github.com/rails/rails.git'`)

**Ruby version**:ruby 2.4.2p198

**Comment by cocoarocket** [comment]
Sorry for stupid question, but, you code:
credentials: <%= Rails.root.join("/pah/to/gcloud-credentials.json") %>
Maybe should it be<%= Rails.root.join("/PATH/to/gcloud-credentials.json") %>?
like "PATH"

**Comment by loop23** [comment]
I had the same exact issue. I fixed it by replacing the responseHeader line like that:

```
 "responseHeader": ['Content-Type', 'Content-Md5' ],
```

in the cors config for the bucket. It wouldn't hurt if this bit of configuration was documented somewhere in ActiveStorage docs.

**Comment by georgeclaghorn** [comment]
Thanks, @loop23! Please do open a PR to update the docs.

**Comment by archonic** [comment]
I've set my cors with `"responseHeader": ['Content-Type', 'Content-Md5' ]`, and the preflight request works, but the payload with the files doesn't. It's getting "No 'Access-Control-Allow-Origin' header is present on the requested resource". Details are here: https://stackoverflow.com/questions/51488304/google-cloud-storage-cors-issue-with-rails-activestorage. Any help much appreciated!

**Comment by ishanray** [comment]
@archonic Same here. It doesn't happen every time though for me.

**Comment by trkoch** [comment]
Direct uploads to GCR didn't work for me either because the preflight request was denied. I needed to explicitly allow the Content-MD5 _request_ header by adding it to the CORS _response_ header.

cors.json
```json
[
    {
      "origin": ["*"],
      "responseHeader": ["Content-Type", "Content-Md5"],
      "method": ["PUT", "GET", "HEAD", "DELETE"],
      "maxAgeSeconds": 3600
    }
]
```

Apply with

```
gsutil cors set cors.json gs://<bucket>
```

Verify with

```
gsutil cors get gs://<bucket>
```

See https://cloud.google.com/storage/docs/configuring-cors, specifically

> If this is a preflight request, see if it includes one or more Access-Control-Request-Header headers. (…) All headers named in the Access-Control-Request-Header must be in the CORS configuration for the preflight request to succeed and include CORS headers in the response.

**Comment by archonic** [comment]
@trkoch I've got exactly that for my cors json and have confirmed it with `gsutil cors get gs://<bucket>` and I'm still getting `Access to XMLHttpRequest at ... has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.` after the pre-flight request succeeds. @ishanray Were you able to make it consistently work?

**Comment by archonic** [comment]
I solved this by updating the direct_uploads_controller.js file (and all it's friends) I copied out of this folder:
https://github.com/rails/rails/tree/master/activestorage/app/javascript/activestorage

And installed the missing spark-md5 npm package. All is well with direct uploads to GCS now with the above CORS config.

**Comment by weilandia** [comment]
I'm running into this again after the upgrade to Rails 6.1/Webpacker 5.2.1.  Same CORS config as above.  Any ideas?

**Comment by svpersteve** [comment]
If anyone's still stuck on this, [this](https://stackoverflow.com/a/70006765/17634914) worked for me.

**Comment by trkoch** [comment]
>  I needed to explicitly allow the Content-MD5 request header.

If you end up here, please note that by now you should follow the official docs ([example](https://guides.rubyonrails.org/active_storage_overview.html#example-google-cloud-storage-cors-configuration)).
