### ISSUE TITLE
Active Storage Direct Upload using IE11

### ISSUE THREAD

**Issue by 10io** [rails/rails#31531]
### Steps to reproduce
Using Active Storage, upload a file directly to a service (tested with local and s3) using Internet Explorer 11.

### Expected behavior
The file should be properly uploaded via javascript directly to the service.

### Actual behavior
A `Unable to get property 'url' of undefined or null reference` is thrown:
<img width="511" alt="screen shot 2017-12-21 at 11 06 16" src="https://user-images.githubusercontent.com/337347/34261387-4ce0fbc0-e669-11e7-9f10-25a4c05ec222.png">

This is due to a bug in IE 11: when using a XMLHttpRequest with `xhr.responseType = "json"`, IE 11 will not automatically parse the response body (see [here](https://connect.microsoft.com/IE/feedback/details/794808)).

The faulty code line is [here](https://github.com/rails/rails/blob/master/activestorage/app/javascript/activestorage/blob_record.js#L33), when the property `direct_upload` is read from the `response`, an `undefined` is returned since `reponse` is a string and not an object.

I did workaround this by simply checking if the response body is a string and parse it with `JSON.parse`.

I can submit this fix but I'm not sure if Active Storage should support IE 11 or not. If that's not the case, feel free to close this issue.

### System configuration
**Rails version**:
5.2.0.alpha 5c7e59a

**Ruby version**:
ruby 2.4.2

**Comment by vfonic** [comment]
@10io IE11 is the latest version of IE, right? I'm pretty sure that, in that case, ActiveSupport supports/should-support IE11. (I'm no rails maintainer.)
I'd suggest that you create a PR.
