### ISSUE TITLE
Status of this ActionCable section

### ISSUE THREAD

**Issue by jhpratt** [rails/rails#31550]
[The section in question](https://github.com/rails/rails/blob/master/actioncable/README.md#notes)

Why I'm questioning this:

> We'll get all this abstracted properly when the framework is integrated into Rails.

Any updates? ActionCable was integrated into Rails over 2 years ago.

**Comment by matthewd** [comment]
Oops.. yeah, that and the paragraph preceding it should be deleted; reloads happen automatically.

Up for an easy PR? :smile:

**Comment by jhpratt** [comment]
Haha, feel free. Was just looking into ActionCable and was thrown off by that bit. Good to know it reloads automatically as well.
