### ISSUE TITLE
DateTime objects representing the end of the day won't persist consistently

### ISSUE THREAD

**Issue by wynksaiddestroy** [rails/rails#31560]
### Steps to reproduce

```ruby
# frozen_string_literal: true

begin
  require "bundler/inline"
rescue LoadError => e
  $stderr.puts "Bundler version 1.10 or later is required. Please update your Bundler"
  raise e
end

gemfile(true) do
  source "https://rubygems.org"

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  # Activate the gem you are reporting the issue against.
  gem "activerecord", "5.1.0"
  gem "sqlite3"
end

require "active_record"
require "minitest/autorun"
require "logger"

# Ensure backward compatibility with Minitest 4
Minitest::Test = MiniTest::Unit::TestCase unless defined?(Minitest::Test)

# This connection will do for database-independent bug reports.
ActiveRecord::Base.establish_connection(adapter: "sqlite3", database: ":memory:")
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :events, force: true do |t|
    t.string   :title
    t.datetime :starts_at
    t.datetime :ends_at
  end
end

class Event < ActiveRecord::Base
end

class BugTest < Minitest::Test
  def test_association_stuff
    event = Event.create!(
      title: "Mom's birthday",
      starts_at: DateTime.now.beginning_of_day,
      ends_at: DateTime.now.end_of_day
    )
    
    # Event object is still in memory and both assertions will succeed
    assert_equal event.starts_at, DateTime.now.beginning_of_day
    assert_equal event.ends_at, DateTime.now.end_of_day

    # Load the object from the database
    event = Event.last

    assert_equal event.starts_at, DateTime.now.beginning_of_day
    # This assertion fails
    assert_equal event.ends_at, DateTime.now.end_of_day
  end
end
```
### Expected behavior
Persisting a DateTime object which represents the end of the day (23:59:59) should show consistent behaviour:

```ruby
event = Event.create!(
  title: "Mom's birthday",
  starts_at: DateTime.now.beginning_of_day,
  ends_at: DateTime.now.end_of_day
)
# Object is still in memory and the comaparison works as expected
event.ends_at == DateTime.now.end_of_day # returns true
# Now load the object from the database
event = Event.last
# The comparison still should yield true as before
event.ends_at == DateTime.now.end_of_day # returns true
```

### Actual behavior
While comparing the beginning of the day will work
```ruby
event = Event.last
event.starts_at == DateTime.now.beginning_of_day # returns true
```
comparing the end of the day will fail
```ruby
event = Event.last
event.ends_at == DateTime.now.end_of_day # returns false
event.ends_at.to_i == DateTime.now.end_of_day.to_i # returns true
```

### System configuration
**Rails version**: 5.1.0

**Ruby version**: 2.4.2p198

**Comment by Dorian** [comment]
Confirmed on Rails 5.2.0.beta2 / Ruby 2.5.0. Minimal version to reproduce the bug: https://gist.github.com/Dorian/9881da28dcd5e65f332bd954ed610909

```ruby
> Time.now.end_of_day.to_f
1514242800.0
> event.ends_at.to_f
1514242799.999999
```

**Comment by sgrif** [comment]
This is pretty much the expected behavior. `end_of_day` returns an object with higher subsecond precision than your database is capable of storing. That said, we should be doing this conversion earlier (e.g. `foo.starts_at == DateTime.now.end_of_day` should *never* return `true`.

**Comment by wynksaiddestroy** [comment]
As @Dorian already pointed out this happens with SQLite as well as PostgreSQL.
Why should `foo.starts_at == DateTime.now.end_of_day` never return true?

**Comment by sgrif** [comment]
As I stated in my last comment

> `end_of_day` returns an object with higher subsecond precision than your database is capable of storing.

That includes PostgreSQL

**Comment by wynksaiddestroy** [comment]
Is there any database that is able to store the proper precision? Shouldn't ActiveRecord take care of the precision that the underlying database is able to store?

**Comment by htanata** [comment]
@wynksaiddestroy Adding `precision` to the datetime column definition might help, as described here https://github.com/rails/rails/issues/30301#issuecomment-323531885.

**Comment by wynksaiddestroy** [comment]
@htanata Thank's for the hint!

**Comment by wynksaiddestroy** [comment]
@htanata Adding precision doesn't solve the problem. At least on my machine. (macOS 10.12.6, Postres 10.1, Ruby 2.5.0 and Rails 5.1.5)

**Comment by pixeltrix** [comment]
@wynksaiddestroy what adding the precision to the column does is trigger the change in #20317, i.e. the precision is truncated on assignment so that assigning the end of the day to an attribute never returns true in a later comparison - it won't make that equal to `Time.current.end_of_day`. 

The only thing extra we could possibly do here is round to the maximum precision supported by the database on assignment when we don't have a specified precision - however not sure whether this is something we want to do. WDYT @sgrif ?

**Comment by emerak** [comment]
I have the same issue
