### ISSUE TITLE
With install Ruby 2.5.0 and Passenger 5.1.12 ALL sites will fail to open

### ISSUE THREAD

**Issue by Sega100500** [rails/rails#31566]
With install **Ruby 2.5.0** and **Passenger 5.1.12** ALL sites will fail to open

application out:
Incomplete response received from application

Same problems with **Ruby 2.4.3**, **Ruby 2.3.6**

Debian 8 Jessie, Apache 2.4

[passenger.log](https://github.com/rails/rails/files/1586912/passenger.log)

**Comment by Sega100500** [comment]
passenger reports:
https://github.com/phusion/passenger/issues/2010
https://github.com/phusion/passenger/issues/2012

**Comment by Sega100500** [comment]
more debug log-file
[passenger.log.debug-7.log](https://github.com/rails/rails/files/1586929/passenger.log.debug-7.log)

**Comment by Sega100500** [comment]
Commands of Phusion Passenger say - problem in ```therubyracer```
https://github.com/cowboyd/therubyracer/issues/444

but command of developers of ```therubyracer``` do NOTHING.

**Comment by y-yagi** [comment]
I checked log. But that error seems unrelated to Rails. Thanks.

**Comment by Sega100500** [comment]
@y-yagi 
May be one of components of RoR ?
Or I must use older versions of Ruby?
