### ISSUE TITLE
mysql2 MULTI_STATEMENTS + ActiveRecord error and patch ...

### ISSUE THREAD

**Issue by JokerCatz** [rails/rails#31569]
if I need multi sql statements in mysql , I need add flag `MULTI_STATEMENTS` in `database.yml`
like

    default: &default
      adapter: mysql2
      {SKIP}
      flags:
        - MULTI_STATEMENTS

then when I use

    ActiveRecord::Base.connection.execute("select 1;" * 10)
      #=> only 1 result
    ActiveRecord::Base.connection.execute("select 1;" * 10)
      #=> ActiveRecord::StatementInvalid: Mysql2::Error: Commands out of sync; you can't run this command now
    ActiveRecord::Base.connection.execute("select 1;" * 10)
      #=> ActiveRecord::StatementInvalid: Mysql2::Error: MySQL client is not connected

then I found it not pull back all result in multi sql statements , and second execute will be fail ... so I try to patch like this (just demo code)

    class ActiveRecord::Base
      def self.multi_sql(safe_raw_sql)
        db_client = ActiveRecord::Base.connection.raw_connection
        datas = []
        begin
          db_client.query("BEGIN")
          db_client.query(safe_raw_sql)
          while data = db_client.next_result
            datas << db_client.store_result
          end
          db_client.query("COMMIT")
        rescue
          db_client.query("ROLLBACK")
        end
        return datas
      end
    end

then same demo code will be work but return ugly result obj ...... so ... has any another way to do it ? or just help me fix to ActiveRecord and help another people? becourse it didn't need to reset/clear any connection or something else ...

### System configuration
Rails 5.1.4 , Ruby 2.4.1p111

**Comment by sodabrew** [comment]
Hello! I maintain the mysql2 gem. Subscribing to this ticket to keep up with any updates. I don't have any specific advice here for what ActiveRecord should do to handle multiple statements, but I'm interested in participating in the conversation if/when.

**Comment by rafaelfranca** [comment]
For security reason Active Record don't support multiple statements in the same string. It is possible to use it and we even use internally, but we don't officially support it.
