### ISSUE TITLE
Rails with Ruby 2.3.6, Ruby 2.4.3, Ruby 2.5.0 fail to run with Apache + Passenger

### ISSUE THREAD

**Issue by Sega100500** [rails/rails#31573]
Rails with **Ruby 2.3.6**, **Ruby 2.4.3**, **Ruby 2.5.0** fail to run with Apache + Passenger
Apache/2.4.10 (Debian)
Passenger 5.1.12

ALL applications out:
**Incomplete response received from application**

Before versions of Ruby ALL works fine!

In log-file:
```
App 31519 stderr: /home/ruby/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/therubyracer-0.12.3/lib/v8/context.rb:99: [BUG] Segmentation fau
lt at 0x0000000000000000
App 31519 stderr: ruby 2.5.0p0 (2017-12-25 revision 61468) [x86_64-linux]
App 31519 stderr:
App 31519 stderr: -- Control frame information -----------------------------------------------
App 31519 stderr: c:0161 p:---- s:1007 e:001006 CFUNC  :Run
App 31519 stderr: c:0160 p:0006 s:1003 e:001002 BLOCK  /home/ruby/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/therubyracer-0.12.3/lib/v8/
context.rb:99
```

_But!!! **therubyracer** is a PART of Ruby on Rails._
However, it seems that this gem (**therubyracer**) has long since died and is no longer supported (Latest commit 466a1f0 on 5 Jan).

Without ```gem 'therubyracer', platforms: :ruby``` in Gemfile no one application not working (even in development mode - without Apache+Passenger - ```rails -s```)!

PLEASE HELP!!!

[passenger.level7.log.therubyracer.bug.log](https://github.com/rails/rails/files/1588551/passenger.level7.log.therubyracer.bug.log)

**Comment by kamipo** [comment]
This is not a Rails issue.

**Comment by Sega100500** [comment]
@kamipo 

Ok. Because ```therubyracer``` is a PART of Ruby on Rails, and ```therubyracer``` is died (Latest commit 466a1f0 on 5 Jan) then **Ruby on Rails also will die with newest version of Ruby 2.3.6, 2.4.3, 2.5.0**.

Or any one may correct the gem ```therubyracer```?
