### ISSUE TITLE
Documentation text mistake

### ISSUE THREAD

**Issue by daniel-costa** [rails/rails#31576]
I was reading through [you documentation](http://api.rubyonrails.org) and realised the return of `Numeric` -> `in_milliseconds()` isn't accurate.

It says 

```
2.in_milliseconds # => 2_000
```

But it should be 

```
2.in_milliseconds # => 2000
```

It's peanuts but I figure I will inform you of it.

Edit: actually you have the same on `megabytes()` and so on. It might be a visibility think I just realise...

**Comment by prathamesh-sonpatki** [comment]
`2.in_milliseconds` is fixed in https://github.com/rails/rails/commit/08a177ee63c

Feel free to open PR to fix the other one.

**Comment by daniel-costa** [comment]
I’m not allowed to creating branches.

**Comment by prathamesh-sonpatki** [comment]
You can fork the rails repo on your account and then open a pull request. Please check https://help.github.com/articles/creating-a-pull-request-from-a-fork/

**Comment by pkayokay** [comment]
@prathamesh-sonpatki this seems closed based on the referenced issue.

**Comment by ahmad19** [comment]
Here: https://github.com/rails/rails/pull/31613

**Comment by georgeclaghorn** [comment]
Per https://github.com/rails/rails/pull/31579#issuecomment-354233411, we prefer this form because it’s equivalent and easier to read.
