### ISSUE TITLE
Nested link_to do block

### ISSUE THREAD

**Issue by gdswan** [rails/rails#31582]
```
<%=link_to root_path do%>
   Hi
  <%=link_to 'Man', root_path%>
<%end%>
```
This should produces :

```
<a href="/">
 Hi 
<a href="/">Man</a>
</a>
```
But instead produces

```
<a href="/"> Hi </a>
<a href="/">Man</a>
```

Rails 5.1.4

In Rails console it works. But, when we try the same in erb it fails

```
2.4.2 :001 > helper.link_to "http://example.com" do
2.4.2 :002 >     helper.link_to "aaa", "http://example.com"
2.4.2 :003?>   end
 => "<a href=\"http://example.com\"><a href=\"http://example.com\">aaa</a></a>" 
```

**Comment by y-yagi** [comment]
Rails generate tag you expected. But nested links are illegal in the W3C definition. 
So browser maybe adjusts the HTML automatically. 
Ref: https://stackoverflow.com/questions/9882916/are-you-allowed-to-nest-a-link-inside-of-a-link
