### ISSUE TITLE
How can I get image url from an ActiveStorage attachment in a worker?

### ISSUE THREAD

**Issue by vitalyliber** [rails/rails#31581]
I have a simple worker. I need an image url from ActiveStorage attachment. I use Google Cloud Storage for upload images.

[I have read this docs.](http://edgeguides.rubyonrails.org/active_storage_overview.html#link-to-attachments)

### Expected behavior
I expect to get link to image on GCS.

### Actual behavior
I can get link in controller via image_tag or rails_blob_path(user.avatar, disposition: "attachment"), but I don't know how to do it from a worker.

### System configuration
**Rails version**:
5.2.0.beta2

**Ruby version**:
2.5.0

**Comment by prathamesh-sonpatki** [comment]
You will need to include the URL helpers in the worker and then you can call any URL helper, rails_blob(path/url) are URL helpers.

``` ruby
class MyWorker
  include Rails.application.routes.url_helpers
  
  def my_url
    rails_blob_path(user.avatar, disposition: "attachment")
  end
end
```

**Comment by vitalyliber** [comment]
@prathamesh-sonpatki Thanks! 

It works. 

Also I added an option `only_path: true`

```ruby
rails_blob_path(user.avatar, disposition: "attachment", only_path: true)
```

**Comment by seanfcarroll** [comment]
I assume this will do the job

```
config.active_storage.service_urls_expire_in = 99.years
```

**Comment by noma4i** [comment]
@seanfcarroll that option have appeared in master not long time ago. Not included in 5.2.1.

as for now `ActiveStorage::Blob.service.url_expires_in` override is accessible.

**Comment by seanfcarroll** [comment]
@noma4i thanks for the post. So we will have to wait for a future version (unless tracking master) ?

**Comment by noma4i** [comment]
@seanfcarroll Sure.
 Another catch is that if you do use S3 to store files you are limited by `1.week` as max expire_time.

https://docs.aws.amazon.com/sdkforruby/api/Aws/S3/Presigner.html
```
 The number of seconds before the presigned URL expires. Defaults to 15 minutes. 
As signature version 4 has a maximum expiry time of one week for presigned URLs, 
attempts to set this value to greater than one week (604800) will raise an exception.
```
The only workaround is to generate links via rails app which is kind of crazy if you do many attachments to be served to other websites
```
Rails.application.routes.url_helpers.rails_blob_path(record.image, only_path: true)
```

**Comment by jfrux** [comment]
This just seems nuts to me... it seems like there would be far more use-cases that require publicly accessible persistent URLs over private one-off urls that expire...

Seriously no better solution rather than `rails_blob_path`.

Seems silly to me.

**Comment by phoet** [comment]
@vitalyliber i have some users, that experience this issue even-though i've set expiration to `1.week`. are there any recommendations for GCS? i could not find a maximum in the docs.

**Comment by yoniamir** [comment]
Thanks @Lupeipei.

In fact, `polymorphic_url(user.avatar)` is better than `rails_blob_path(attachment)` because it also works with variants.

Exmaple:
```ruby
polymorphic_url(user.avatar).variant(resize: "300x300")
```
works 👍🏼

But:
```ruby 
rails_blob_path(attachment).variant(resize: "300x300")
```
does not.

**Comment by rafaeldev** [comment]
> Thanks @Lupeipei.
> 
> In fact, `polymorphic_url(user.avatar)` is better than `rails_blob_path(attachment)` because it also works with variants.
> 
> Exmaple:
> 
> ```ruby
> polymorphic_url(user.avatar).variant(resize: "300x300")
> ```
> 
> works 👍🏼
> 
> But:
> 
> ```ruby
> rails_blob_path(attachment).variant(resize: "300x300")
> ```
> 
> does not.

@yoniamir this example does not works for me. I'm need made some changes (my context):
```ruby
polymorphic_url(@company.logo.variant(resize: "x72"))
```
