### ISSUE TITLE
mail.to return [nil] if invalid mail address

### ISSUE THREAD

**Issue by ponkotuy** [rails/rails#31587]
### Steps to reproduce
```
mail = Mail.new do
  to '<a>'
end
mail.to # => [nil]
```

### Expected behavior
Return an empty array 

### Actual behavior
Return an array with nil

### System configuration
Rails: 5.1.3
Ruby: 2.4.1

**Comment by georgeclaghorn** [comment]
This isn’t a Rails issue. `Mail` is provided by the [mail](https://github.com/mikel/mail) gem.
