### ISSUE TITLE
ActiveRecord relation 'merge' merges bind values only by column name only

### ISSUE THREAD

**Issue by CharlesMcMillan** [rails/rails#31584]
### Steps to reproduce

When using the relation `merge` functionality in ActiveRecord, we noticed that in the rare case that we used merge with two models that coincidentally happened to have an identically named column, those bind values were getting blown out, irrespective of which table was being merged from/to. Unit test to reproduce in merging_test.rb:

```ruby
require 'models/essay'

  def test_relation_merging_with_subquery
    left = Developer.where(name: 'test_value1').where(id: Essay.where(name: 'test_value2'))
    right = Developer.where(name: 'test_value3')
    developer_name_column = Developer.columns_hash['name']
    essay_name_column = Essay.columns_hash['name']
    binds = [[developer_name_column, 'test_value3'], [essay_name_column, 'test_value2']]
    assert_equal left.merge(right).bind_values, binds
  end
```

### Expected behavior

Bind values for Essay model 'test_value2' should remain

### Actual behavior

The bind value for Essay ('test_value2') is blown away

### System configuration
**Rails version**: Rails 4.2.10

**Ruby version**: ruby 2.4.1p111 (2017-03-22 revision 58053) [x86_64-darwin16]

**Comment by y-yagi** [comment]
Rails 4.2 is not supported anymore for anything besides security fixes.
Please check whether your issue can reproduce with latest Rails. Thanks!
