### ISSUE TITLE
in windows rails implementation, db:reset or db:drop gives permissions error

### ISSUE THREAD

**Issue by gartha1** [rails/rails#31589]
I have 

C:\rubytest\blah2>ruby --version
ruby 2.4.2p198 (2017-09-14 revision 59899) [x64-mingw32]

C:\rubytest\blah2>rails --version
Rails 5.1.4

C:\rubytest\blah2>

My OS is Windows 7.

The error I get is when I do  rails db:drop  or rails db:reset

I get Permission denied @ unlink_internal - C:/rubytest/blah2/db/development.sqlite3

I get this even from an administrative cmd prompt(which is  a bit like root in linux), and I can see that file is not locked, as I can delete it with the del command from cmd.exe.  But I still get the error. 

C:\rubytest>rails --version
Rails 5.1.4

C:\rubytest>

C:\rubytest>rails new blah2
..

C:\rubytest\blah2>bundle update
...

C:\rubytest\blah2>rails db:reset
Permission denied @ unlink_internal - C:/rubytest/blah2/db/development.sqlite3
Couldn't drop database 'db/development.sqlite3'
rails aborted!
Errno::EACCES: Permission denied @ unlink_internal - C:/rubytest/blah2/db/development.sqlite3
bin/rails:4:in `require'
bin/rails:4:in `<main>'
Tasks: TOP => db:drop:_unsafe
(See full trace by running task with --trace)

I heard that maybe in *nix it might mention about setting an environment variable or something that would give the developer permission.  But perhaps the error in windows doesn't state that info.    If I try adding --trace then it doesn't give me any ideas as to a solution.

C:\rubytest\blah2>rails db:reset --trace
** Invoke db:reset (first_time)
** Invoke db:drop (first_time)
** Invoke db:load_config (first_time)
** Execute db:load_config
** Invoke db:check_protected_environments (first_time)
** Invoke environment (first_time)
** Execute environment
** Invoke db:load_config
** Execute db:check_protected_environments
** Execute db:drop
** Invoke db:drop:_unsafe (first_time)
** Invoke db:load_config
** Execute db:drop:_unsafe
Permission denied @ unlink_internal - C:/rubytest/blah2/db/development.sqlite3
Couldn't drop database 'db/development.sqlite3'
rails aborted!
Errno::EACCES: Permission denied @ unlink_internal - C:/rubytest/blah2/db/develo
pment.sqlite3
C:/Ruby24-x64/lib/ruby/2.4.0/fileutils.rb:1341:in `unlink'
C:/Ruby24-x64/lib/ruby/2.4.0/fileutils.rb:1341:in `block in remove_file'
C:/Ruby24-x64/lib/ruby/2.4.0/fileutils.rb:1349:in `platform_support'
C:/Ruby24-x64/lib/ruby/2.4.0/fileutils.rb:1340:in `remove_file'
C:/Ruby24-x64/lib/ruby/2.4.0/fileutils.rb:704:in `remove_file'
C:/Ruby24-x64/lib/ruby/2.4.0/fileutils.rb:507:in `block in rm'
C:/Ruby24-x64/lib/ruby/2.4.0/fileutils.rb:506:in `each'
C:/Ruby24-x64/lib/ruby/2.4.0/fileutils.rb:506:in `rm'
C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/activerecord-5.1.4/lib/active_record/task
s/sqlite_database_tasks.rb:22:in `drop'
C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/activerecord-5.1.4/lib/active_record/task
s/database_tasks.rb:144:in `drop'
C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/activerecord-5.1.4/lib/active_record/task
s/database_tasks.rb:160:in `block in drop_current'
C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/activerecord-5.1.4/lib/active_record/task
s/database_tasks.rb:304:in `block in each_current_configuration'
C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/activerecord-5.1.4/lib/active_record/task
s/database_tasks.rb:303:in `each'
C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/activerecord-5.1.4/lib/active_record/task
s/database_tasks.rb:303:in `each_current_configuration'
C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/activerecord-5.1.4/lib/active_record/task
s/database_tasks.rb:159:in `drop_current'
C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/activerecord-5.1.4/lib/active_record/rail
ties/databases.rake:42:in `block (2 levels) in <top (required)>'
C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/rake-12.3.0/lib/rake/task.rb:251:in `bloc
k in execute'
C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/rake-12.3.0/lib/rake/task.rb:251:in `each
'
C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/rake-12.3.0/lib/rake/task.rb:251:in `exec
ute'
C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/rake-12.3.0/lib/rake/task.rb:195:in `bloc
k in invoke_with_call_chain'
C:/Ruby24-x64/lib/ruby/2.4.0/monitor.rb:214:in `mon_synchronize'
C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/rake-12.3.0/lib/rake/task.rb:188:in `invo
ke_with_call_chain'
C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/rake-12.3.0/lib/rake/task.rb:181:in `invo
ke'
C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/activerecord-5.1.4/lib/active_record/rail
ties/databases.rake:38:in `block (2 levels) in <top (required)>'
C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/rake-12.3.0/lib/rake/task.rb:251:in `bloc
k in execute'
C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/rake-12.3.0/lib/rake/task.rb:251:in `each
'
C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/rake-12.3.0/lib/rake/task.rb:251:in `exec
ute'
C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/rake-12.3.0/lib/rake/task.rb:195:in `bloc
k in invoke_with_call_chain'
C:/Ruby24-x64/lib/ruby/2.4.0/monitor.rb:214:in `mon_synchronize'
C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/rake-12.3.0/lib/rake/task.rb:188:in `invo
ke_with_call_chain'
C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/rake-12.3.0/lib/rake/task.rb:217:in `bloc
k in invoke_prerequisites'
C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/rake-12.3.0/lib/rake/task.rb:215:in `each
'
C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/rake-12.3.0/lib/rake/task.rb:215:in `invo
ke_prerequisites'
C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/rake-12.3.0/lib/rake/task.rb:194:in `bloc
k in invoke_with_call_chain'
C:/Ruby24-x64/lib/ruby/2.4.0/monitor.rb:214:in `mon_synchronize'
C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/rake-12.3.0/lib/rake/task.rb:188:in `invo
ke_with_call_chain'
C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/rake-12.3.0/lib/rake/task.rb:181:in `invo
ke'
C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/rake-12.3.0/lib/rake/application.rb:160:i
n `invoke_task'
C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/rake-12.3.0/lib/rake/application.rb:116:i
n `block (2 levels) in top_level'
C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/rake-12.3.0/lib/rake/application.rb:116:i
n `each'
C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/rake-12.3.0/lib/rake/application.rb:116:i
n `block in top_level'
C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/rake-12.3.0/lib/rake/application.rb:125:i
n `run_with_threads'
C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/rake-12.3.0/lib/rake/application.rb:110:i
n `top_level'
C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/railties-5.1.4/lib/rails/commands/rake/ra
ke_command.rb:21:in `block in perform'
C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/rake-12.3.0/lib/rake/application.rb:186:i
n `standard_exception_handling'
C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/railties-5.1.4/lib/rails/commands/rake/ra
ke_command.rb:18:in `perform'
C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/railties-5.1.4/lib/rails/command.rb:46:in
 `invoke'
C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/railties-5.1.4/lib/rails/commands.rb:16:i
n `<top (required)>'
bin/rails:4:in `require'
bin/rails:4:in `<main>'
Tasks: TOP => db:drop:_unsafe

C:\rubytest\blah2>

**Comment by bialpio** [comment]
Hi, I'm running into this issue on rails version 5.2.0, ruby version 2.4.4p296 (2018-03-28 revision 63013) [x64-mingw32]. I took a trace using procmon, and it seems that the ruby.exe process tries to open the sqlite file incorrectly?

Here's what I see:
1. CreateFile on the db file using the following parameters - this succeeds:
`Desired Access: Generic Read/Write, Disposition: OpenIf, Options: Synchronous IO Non-Alert, Non-Directory File, Attributes: N, ShareMode: Read, Write, AllocationSize: 0, OpenResult: Opened`
2. Some time later Second create file on the db file - this fails with sharing violation error (asks for access to delete, but prior CreateFile allows only sharing of read & write):
`Desired Access: Read Attributes, Delete, Disposition: Open, Options: Non-Directory File, Open   Reparse Point, Attributes: n/a, ShareMode: Read, Write, Delete, AllocationSize: n/a`
3. Yet another CreateFile call - succeeds:
`Desired Access: Write Attributes, Synchronize, Disposition: Open, Options: Synchronous IO   Non-Alert, Open Reparse Point, Attributes: n/a, ShareMode: Read, Write,   Delete, AllocationSize: n/a, OpenResult: Opened`
4. CloseFile - probably for open in point 3.
5. CreateFile - fails with sharing violation error:
`Desired Access: Read Attributes, Delete, Disposition: Open, Options: Non-Directory File, Open   Reparse Point, Attributes: n/a, ShareMode: Read, Write, Delete, AllocationSize: n/a`
6. CloseFile - probably for open in point 1.

Unfortunately, I do not know a lot about debugging ruby applications so it might be hard for me to make further progress with investigation. :( Let me know if you need more information in order to investigate!

**Comment by MSCAU** [comment]
I can confirm that I have seen this issue happen once too (around 9 Aug 2018), using Rails 5.1.6 and SQLite3 on Windows. The problem went away after a few hours of coding. If it comes up again, I'll try and document it.

**Comment by bialpio** [comment]
I took a closer look, with my limited understanding of ruby and rails, it seems that db:reset will trigger (as a prerequisite?) a db:drop, and that in turn triggers an initialization of rails application (application.rb, `initialize!`) - after that finishes, the file is already open with share mode set to Read + Write (step 1. from above).

**Comment by williammoreschi** [comment]
I am having problem I am using win 10 and using the vagrant and for working AWS Cloud9.
I started creating a myapp test project

vagrant@ubuntu-bionic:/vagrant/workspace/myapp$ rails db:drop
Text file busy @ unlink_internal - /vagrant/workspace/myapp/db/development.sqlite3
Couldn't drop database 'db/development.sqlite3'
rails aborted!
Errno::ETXTBSY: Text file busy @ unlink_internal - /vagrant/workspace/myapp/db/development.sqlite3
/home/vagrant/.rvm/gems/ruby-2.4.4/gems/activerecord-5.2.1/lib/active_record/tasks/sqlite_database_tasks.rb:24:in `drop'
/home/vagrant/.rvm/gems/ruby-2.4.4/gems/activerecord-5.2.1/lib/active_record/tasks/database_tasks.rb:146:in `drop'
/home/vagrant/.rvm/gems/ruby-2.4.4/gems/activerecord-5.2.1/lib/active_record/tasks/database_tasks.rb:162:in `block in drop_current'
/home/vagrant/.rvm/gems/ruby-2.4.4/gems/activerecord-5.2.1/lib/active_record/tasks/database_tasks.rb:316:in `block in each_current_configuration'
/home/vagrant/.rvm/gems/ruby-2.4.4/gems/activerecord-5.2.1/lib/active_record/tasks/database_tasks.rb:313:in `each'
/home/vagrant/.rvm/gems/ruby-2.4.4/gems/activerecord-5.2.1/lib/active_record/tasks/database_tasks.rb:313:in `each_current_configuration'
/home/vagrant/.rvm/gems/ruby-2.4.4/gems/activerecord-5.2.1/lib/active_record/tasks/database_tasks.rb:161:in `drop_current'
/home/vagrant/.rvm/gems/ruby-2.4.4/gems/activerecord-5.2.1/lib/active_record/railties/databases.rake:44:in `block (2 levels) in <main>'
/home/vagrant/.rvm/gems/ruby-2.4.4/gems/activerecord-5.2.1/lib/active_record/railties/databases.rake:40:in `block (2 levels) in <main>'
/home/vagrant/.rvm/gems/ruby-2.4.4/gems/railties-5.2.1/lib/rails/commands/rake/rake_command.rb:23:in `block in perform'
/home/vagrant/.rvm/gems/ruby-2.4.4/gems/railties-5.2.1/lib/rails/commands/rake/rake_command.rb:20:in `perform'
/home/vagrant/.rvm/gems/ruby-2.4.4/gems/railties-5.2.1/lib/rails/command.rb:48:in `invoke'
/home/vagrant/.rvm/gems/ruby-2.4.4/gems/railties-5.2.1/lib/rails/commands.rb:18:in `<main>'
/home/vagrant/.rvm/gems/ruby-2.4.4/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `require'
/home/vagrant/.rvm/gems/ruby-2.4.4/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `block in require_with_bootsnap_lfi'
/home/vagrant/.rvm/gems/ruby-2.4.4/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/loaded_features_index.rb:65:in `register'
/home/vagrant/.rvm/gems/ruby-2.4.4/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:20:in `require_with_bootsnap_lfi'
/home/vagrant/.rvm/gems/ruby-2.4.4/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:29:in `require'
/home/vagrant/.rvm/gems/ruby-2.4.4/gems/activesupport-5.2.1/lib/active_support/dependencies.rb:287:in `block in require'
/home/vagrant/.rvm/gems/ruby-2.4.4/gems/activesupport-5.2.1/lib/active_support/dependencies.rb:253:in `load_dependency'
/home/vagrant/.rvm/gems/ruby-2.4.4/gems/activesupport-5.2.1/lib/active_support/dependencies.rb:287:in `require'
/vagrant/workspace/myapp/bin/rails:9:in `<top (required)>'
/home/vagrant/.rvm/gems/ruby-2.4.4/gems/spring-2.0.2/lib/spring/client/rails.rb:28:in `load'
/home/vagrant/.rvm/gems/ruby-2.4.4/gems/spring-2.0.2/lib/spring/client/rails.rb:28:in `call'
/home/vagrant/.rvm/gems/ruby-2.4.4/gems/spring-2.0.2/lib/spring/client/command.rb:7:in `call'
/home/vagrant/.rvm/gems/ruby-2.4.4/gems/spring-2.0.2/lib/spring/client.rb:30:in `run'
/home/vagrant/.rvm/gems/ruby-2.4.4/gems/spring-2.0.2/bin/spring:49:in `<top (required)>'
/home/vagrant/.rvm/gems/ruby-2.4.4/gems/spring-2.0.2/lib/spring/binstub.rb:31:in `load'
/home/vagrant/.rvm/gems/ruby-2.4.4/gems/spring-2.0.2/lib/spring/binstub.rb:31:in `<top (required)>'
/vagrant/workspace/myapp/bin/spring:15:in `require'
/vagrant/workspace/myapp/bin/spring:15:in `<top (required)>'
bin/rails:3:in `load'
bin/rails:3:in `<main>'
Tasks: TOP => db:drop:_unsafe
(See full trace by running task with --trace)

**Comment by cadamini** [comment]
Old topic but still worth to mention I think. 
Solved it after I have found this on SO: 
`rake db:drop:_unsafe`

**Comment by gartha1** [comment]
I got a notification of a reply from somebody suggesting a solution and their solution worked, though their post has gone from here,  Their solution was that instead of rails db:drop  do rails db:drop:_unsafe

So, here's the output if doing rails db:drop, getting an error, then notice

C:\rubytest\h\testaa1>rails db:drop
Permission denied @ unlink_internal - C:/rubytest/h/testaa1/db/development.sqlite3
Couldn't drop database 'db/development.sqlite3'
rails aborted!
Errno::EACCES: Permission denied @ unlink_internal - C:/rubytest/h/testaa1/db/develo
bin/rails:4:in `require'
bin/rails:4:in `<main>'
Tasks: TOP => db:drop:_unsafe
(See full trace by running task with --trace)

C:\rubytest\h\testaa1>rails db:drop:_unsafe
Dropped database 'db/development.sqlite3'
Dropped database 'db/test.sqlite3'

C:\rubytest\h\testaa1>

Funnily enough, as you can see from the output of rails:drop, the rails:drop does mention "Tasks: TOP => db:drop:_unsafe"    I guess maybe that's rails way of asking the user/programmer to do that command!

**Comment by cadamini** [comment]
This was me, I have found [this article](https://stackoverflow.com/questions/39414892/rails-dbmigratereset-producing-errnoeacces-permission-denied-unlink-interna). I am happy that it helped you as well.

**Comment by overskilled** [comment]
For my case i fix this error but hitting 

rake db:drop:_unsafe in the cli
