### ISSUE TITLE
Improving ActionMailer::new Documentation

### ISSUE THREAD

**Issue by JeremyRubin** [rails/rails#31599]
Hey Rails Devs,

A bit of a newbie here, but it seems that following https://github.com/rails/rails/commit/e76c38ef1047ad3ffb25c1c639c38432a9228796 the ActionMailer documentation is messed up.

Further this change seems to be ill-documented in changelogs as I couldn't find any breaking change notifications?

There's a bunch of code floating around using new with constructions like

    @obj ||= @mailer.send(:new, @mail_method, *@args).message

from http://codelikeshit.com/tricky-action-mailer/

which should now be broken.

Cheers,

Jeremy

**Comment by georgeclaghorn** [comment]
> the ActionMailer documentation is messed up

Can you elaborate? The API docs look fine at a glance.

> I couldn't find any breaking change notifications

`ActionMailer::Base#new` was private before e76c38e, so the modification to its signature didn’t warrant a CHANGELOG mention. The blog post to which you linked explains Rails internals prior to that change; it doesn’t demonstrate a valid or emulable use of Action Mailer in a Rails app.

**Comment by JeremyRubin** [comment]
> Can you elaborate? The API docs look fine at a glance.

The documentation says

    # Instantiate a new mailer object. If +method_name+ is not +nil+, the mailer
    # will be initialized according to the named method. If not, the mailer will
    # remain uninitialized (useful when you only need to invoke the "receive"
    # method, for instance).

but new no longer has a method_name parameter

**Comment by georgeclaghorn** [comment]
That comment was removed in d33bdef. The API docs will be updated when Rails 5.2 is released. (See [edgeapi.rubyonrails.org](http://edgeapi.rubyonrails.org) for a preview.)
