### ISSUE TITLE
Scaffold Hang: Rails 4.2.10 & Ruby 2.4.0

### ISSUE THREAD

**Issue by PrimeTimeTran** [rails/rails#31593]
### Steps to reproduce
Create new project. Go in. Run generator.
```
➜  contactbook ruby -v
ruby 2.4.0p0 (2016-12-24 revision 57164) [x86_64-darwin15]
➜  contactbook rails -v
Rails 4.2.10
➜  contactbook rails g scaffold Contact name:string
```
### System configuration
- rails 4.2.10
- ruby 2.4.0

![screen shot 2017-12-30 at 2 21 53 am](https://user-images.githubusercontent.com/16382165/34445767-83f4abd4-ed08-11e7-970b-d2023e6c5632.jpg)
## The Bug
Running the following code results in a hang. 
`rails g scaffold Contact name:string address:string city:string phone:string email:string`

## Here's the hang 
When I hit **ctrl+c** this is the log. 
```
contactbook rails g scaffold Contact name:string address:string city:string phone:string email:string
^[[1;9C^C/Users/Lois/.rvm/gems/ruby-2.4.0/gems/spring-2.0.2/lib/spring/client/run.rb:117:in `gets': Interrupt
	from /Users/Lois/.rvm/gems/ruby-2.4.0/gems/spring-2.0.2/lib/spring/client/run.rb:117:in `verify_server_version'
	from /Users/Lois/.rvm/gems/ruby-2.4.0/gems/spring-2.0.2/lib/spring/client/run.rb:62:in `run'
	from /Users/Lois/.rvm/gems/ruby-2.4.0/gems/spring-2.0.2/lib/spring/client/run.rb:42:in `warm_run'
	from /Users/Lois/.rvm/gems/ruby-2.4.0/gems/spring-2.0.2/lib/spring/client/run.rb:35:in `call'
	from /Users/Lois/.rvm/gems/ruby-2.4.0/gems/spring-2.0.2/lib/spring/client/command.rb:7:in `call'
	from /Users/Lois/.rvm/gems/ruby-2.4.0/gems/spring-2.0.2/lib/spring/client/rails.rb:24:in `call'
	from /Users/Lois/.rvm/gems/ruby-2.4.0/gems/spring-2.0.2/lib/spring/client/command.rb:7:in `call'
	from /Users/Lois/.rvm/gems/ruby-2.4.0/gems/spring-2.0.2/lib/spring/client.rb:30:in `run'
	from /Users/Lois/.rvm/gems/ruby-2.4.0/gems/spring-2.0.2/bin/spring:49:in `<top (required)>'
	from /Users/Lois/.rvm/gems/ruby-2.4.0/gems/spring-2.0.2/lib/spring/binstub.rb:31:in `load'
	from /Users/Lois/.rvm/gems/ruby-2.4.0/gems/spring-2.0.2/lib/spring/binstub.rb:31:in `<top (required)>'
	from /Users/Lois/Desktop/projects/contactbook/bin/spring:15:in `require'
	from /Users/Lois/Desktop/projects/contactbook/bin/spring:15:in `<top (required)>'
	from bin/rails:3:in `load'
	from bin/rails:3:in `<main>'

➜  contactbook
```
![screen shot 2017-12-30 at 2 21 53 am](https://user-images.githubusercontent.com/16382165/34445830-007dba60-ed09-11e7-89ee-a800ac637ab2.jpg)

[Possible Duplicate of this issue](https://github.com/rails/rails/issues/27310)? 
#27310 
Rails 5.1.4 though. Probably not? 

### Expected behavior
Generator should complete creating scaffold. 

### Actual behavior
It hangs for several minutes. I've restarted both machine & terminal session.

**Comment by y-yagi** [comment]
Rails 4.2 is not supported anymore for anything besides security fixes.
Please check whether your issue can reproduce with latest Rails. Thanks!
