### ISSUE TITLE
Should channel prefix support be rolled into the ActionCable Redis adapter?

### ISSUE THREAD

**Issue by matrix9180** [rails/rails#31605]
In #27425 I added channel prefix support to the redis & evented_redis ActionCable connection adapters. The decision to abstract channel prefixes to it's own module was due to there being two redis adapters at the time. After #30945, there is only one redis adapter so the abstraction isn't needed. I see two options and am seeking feedback.

Option 1: Just leave it alone.
 - It *could potentially* be useful for some unknown adapter that's added in the future, but seems to violate the YAGNI principal.

Option 2: Roll the channel prefix support directly into the redis adapter and drop the abstraction.
- It would clean up the code a bit and hopefully reduce technical debt.

Thoughts?

**Comment by georgeclaghorn** [comment]
Please use the [rubyonrails-core](https://groups.google.com/forum/#!forum/rubyonrails-core) mailing list to discuss this. We reserve the issue tracker for bug reports.

My two cents: fold it back into `RedisAdapter`. Feel free to open a PR.
