### ISSUE TITLE
destroy_all blocks the pry with ActiveStorage purge job

### ISSUE THREAD

**Issue by sebastiandeutsch** [rails/rails#31609]
### Steps to reproduce

Looks at this snapshot from my terminal.

https://gist.github.com/sebastiandeutsch/d7e021198b36cab54ecb9370a6aaf519

### Expected behavior
It should delete all the records including the attached documents.

### Actual behavior
It blocks and when I hit CTRL+D it might leave the database in an inconsistent state.

### System configuration
Rails 5.2.0.beta2
Ruby 2.4.0

**Comment by GBH** [comment]
Maybe related to https://github.com/rails/rails/issues/30937

**Comment by sebastiandeutsch** [comment]
I'm using Postgres so maybe it's not limited to SQLite.
