### ISSUE TITLE
ActiveStorage using local direct-upload-url even when set to :amazon

### ISSUE THREAD

**Issue by atstockland** [rails/rails#31601]
It seems the development environment is defaulting to :local storage service, regardless of what is set in development.rb.  I have chosen to use S3 in development (or, at least use it temporarily to make sure things are working)...but storage is still using localhost.

### Steps to reproduce
* create a dev bucket on S3
* add the following to storage.yml

      amazon_dev:
          service: S3
          access_key_id: <%= Rails.application.credentials.dig(:aws, :access_key_id) %>
          secret_access_key: <%= Rails.application.credentials.dig(:aws, :secret_access_key) %>
          region: us-east-1
         bucket: development-bucket

* add the following to development.rb

      config.active_storage.service = :amazon_dev

* restart server
* refresh form page that includes form_with the following:

      <%= f.file_field :avatar, direct_upload: true %>

* inspect html on that form element

### Expected behavior
I would expect, since :amazon_dev, is set as the service in development.rb...that, files would be uploaded to S3.  I would expect to see the file field "direct-upload-url" to be an S3 url.

### Actual behavior
The file field is still pointing to localhost storage, even though :amazon_dev set as storage service in development.rb

      <input data-direct-upload-url="http://localhost:3000/rails/active_storage/direct_uploads" type="file" name="user[avatar]" id="user_avatar">

### System configuration
**Rails version**:
Rails 5.2.0.beta2

**Ruby version**:
ruby 2.4.3p205 (2017-12-14 revision 61247) [x86_64-darwin17]

**Comment by atstockland** [comment]
I only specified that I was inspecting the page HTML....however, I did submit the form and render the image successfully.  Inspecting the image path also indicates localhost.  It seems there may be some rails magic happening with the url in the BLOB.  But, after the image renders, should I not be seeing an S3 url?  I'm second guessing this as a bug, but I'll leave it open for now.

**Comment by georgeclaghorn** [comment]
This is the expected behavior. Active Storage’s JS library hits a stable app URL to request a signed, short-lived direct upload URL.

**Comment by atstockland** [comment]
Thanks @georgeclaghorn!  Sorry for a fake-bug :|

**Comment by georgeclaghorn** [comment]
No worries! This could probably be better documented.
