### ISSUE TITLE
Fragment Cache - always cold on server restart/reload?

### ISSUE THREAD

**Issue by butchmarshall** [rails/rails#31608]
### Steps to reproduce

1. Fragement cache some pages using any caching engine
2. Restart your server
3. Cache is cold

### Expected behavior

I'd like the ability to keep my cache warm between server restarts

### Actual behavior

Cache is not warm between restarts.

### System configuration
**Rails version**:

4.2.10

**Ruby version**:
2.2.1p85

**Comment by georgeclaghorn** [comment]
Are you using the memory cache store? If not, which cache store are you using?

**Comment by butchmarshall** [comment]
This happens for me when using both file & dalli (memcached).

**Comment by butchmarshall** [comment]
Actually @georgeclaghorn this looks like it might be an issue with [jsonapi-resources](https://github.com/cerebris/jsonapi-resources).

I'm opening an issue there instead.  I'll re-open if it turns out not to be the culprit.
