### ISSUE TITLE
Don't want :coffee:

### ISSUE THREAD

**Issue by igravious** [rails/rails#31616]
### Steps to reproduce not having :coffee:

Install Rails as new. I followed [this particular guide](https://bendyworks.com/blog/installing-ruby-on-rails-edge-with-bundler) because I wanted to [track master](https://github.com/rails/rails) and also install Rails via Bundler but I'm presuming that makes no difference to the outcome, please correct me if I'm wrong. Choose the ```--skip-coffee``` parameter. I think my whole command line was ```bundle exec rails new . --dev --skip-coffee --skip-turbolinks --skip-spring```.

### Expected behavior
Rails as normal. I'd be happy to find out I've done something stupid and that the fault lies with me and not Rails.

### Actual behavior
After creating a dummy scaffold and navigating to the correct page Rails (Sprockets autoloader) complains that it can't find file ```coffee_script``` from the line ```<%= stylesheet_link_tag    'application', media: 'all' %>``` in file ```app/views/layouts/application.html.erb```

### System configuration
**Rails version**: 5.2.0.beta2 

**Ruby version**: ruby 2.5.0-p0

**Comment by matthewd** [comment]
Master requires coffeescript, because [we have code written in coffeescript](https://github.com/rails/rails/search?l=CoffeeScript). (It gets precompiled to JS during the release process.)

**Comment by igravious** [comment]
Is this always going to be the case? Shouldn't the ```--skip-coffee``` command line option be removed in that case?

I think having a hard requirement on CoffeeScript is a bad idea for a number of reasons.

- you'll get more users of Rails if you _support_ CoffeeScript but don't _require_ it
- you'll get more contributors to Rails if the client-side internals are written in JavaScript, not CoffeeScript
- Even though Rails is batteries included and convention over configuration you could always choose to opt out of the stuff you didn't want – for instance Turbolinks, or Spring, or whatever …
- Being able to remove what you don't want allows you to slim down your install, this is kind of powerful psychologically

**Comment by matthewd** [comment]
As I said, the option works fine when using the released gems; it's just incompatible with using `--dev` to work directly against master.

Thanks for your concern, but I think we do okay with getting users.

**Comment by igravious** [comment]
No need for the snark @matthewd .

I didn't understand that you meant that if I target master using ```--dev``` that this disables ```--skip-coffee``` and that releases work differently. Are there any other things that ```--dev``` does that I need to know about? This needs to be documented somewhere! What I thought you meant was that from now on I wouldn't be able to disable CoffeeScript.

And every user counts. And I'm one of them.

**Comment by chrisarcand** [comment]
This got defensive quickly due to a simple misunderstanding of where the 'hard requirement' lies.

@igravious This has been closed as Not A Bug, but you're welcome to open a pull request to make a small note of this behavior; perhaps in the contributing guides, [here](https://github.com/rails/rails/blob/921b877c2fd51cc0abdcf0ef6ca3528808047056/guides/source/contributing_to_ruby_on_rails.md#running-an-application-against-your-local-branch)? Seems like that should be a happy path for everyone.

**Comment by igravious** [comment]
Thanks for your calm words @chrisarcand . I've been chatting with a couple of people in the RubyOnRails IRC channel in my attempt to get to the bottom of the exact behaviour so that it can be documented. A small note in the appropriate guide should, as you say, make everyone happy.
