### ISSUE TITLE
bin/rails db:setup ignores application configuration (Rails.application.config.active_record.schema_format = :sql)

### ISSUE THREAD

**Issue by enatividad** [rails/rails#31614]
### Steps to reproduce
1. Install ruby 2.4.1 via rbenv. Install rails 5.4.1. Running them in Fedora 25 is a plus.
2. Download/clone this source code: https://github.com/enatividad/sen_sys_public/tree/development
3. Note that `/config/initializers/0_custom_config.rb` says `Rails.application.config.active_record.schema_format = :sql`.
4. Run `bin/setup` (which runs `bin/rails db:setup').

(Guidelines for creating a bug report are [available
here](http://guides.rubyonrails.org/contributing_to_ruby_on_rails.html#creating-a-bug-report))

### Expected behavior
The database loads `structure.sql'.

### Actual behavior
I get a runtime error instead.
```
/home/enatividad/workspace/sen_sys/db/schema.rb doesn't exist yet. Run `rails db:migrate` to create it, then try again. If you do not intend to use a database, you should instead alter /home/enatividad/workspace/sen_sys/config/application.rb to limit the frameworks that will be loaded.
```

This didn't happen until a few commits were made.

### System configuration
**Operating System**: Fedora 25

**Rails version**: 5.1.4

**Ruby version**: 2.4.1

**Comment by joshmn** [comment]
I can confirm this acts as reported, _however_, could you try putting `config.active_record.schema_format = :sql` into your `config/environments/development.rb` and then running `bin/setup` and report back? I got different behavior once I did so.

**Comment by y-yagi** [comment]
This because `db:setup` task set config before load environment files. 
But that behavior changed to load environment files before set config with #31135. So this issue will not happen on Rails 5.2. 
In Rails 5.1.4, please set `schema_format` in `config/application.rb`. Like following. 

```diff 
diff --git a/config/application.rb b/config/application.rb
index bef7884..9a9563b 100644
--- a/config/application.rb
+++ b/config/application.rb
@@ -24,5 +24,7 @@ module SenSys
     # Settings in config/environments/* take precedence over those specified here.
     # Application configuration should go into files in config/initializers
     # -- all .rb files in that directory are automatically loaded.
+
+    config.active_record.schema_format = :sql
   end
 end 
``` 

Thanks!

**Comment by enatividad** [comment]
Placing the `active_record.schema_format` configuration in development.rb and application.rb seems to fix the problem. Thank you for your hard work!
