### ISSUE TITLE
DEPRECATION WARNING: Passing a class to the `class_name` is deprecated and will raise an ArgumentError in Rails 5.2. It eagerloads more classes than necessary and potentially creates circular dependencies. Please pass the class name as a string: `has_many :transactions, class_name: 'BitcoinPayable::BitcoinPaymentTransaction'` (called from <class:BitcoinPayment> at /home/Ammad/.rvm/gems/ruby-2.3.1/bundler/gems/bitcoin_payable-7af6f7d51d69/lib/bitcoin_payable/bitcoin_payment.rb:9)

### ISSUE THREAD

**Issue by amysid** [rails/rails#31622]
### Steps to reproduce

(Guidelines for creating a bug report are [available
here](http://guides.rubyonrails.org/contributing_to_ruby_on_rails.html#creating-a-bug-report))

### Expected behavior
Tell us what should happen

### Actual behavior
Tell us what happens instead

### System configuration
**Rails version**:

**Ruby version**:

**Comment by Onumis** [comment]
No problems here, the warning is self explanatory.
