### ISSUE TITLE
Postgres Advisory Lock should include schema name

### ISSUE THREAD

**Issue by JanStevens** [rails/rails#31627]
### Steps to reproduce
When using Aparment or pg bouncer it is common to have multiple identical structure postgres schemas. These can be migrated in parallel separately without any conflict (they are separate namespaces). With rails current implementation of advisory locks this does not work since a lock is generated only on the database name and not on schema + database name.

### Expected behavior
Expect that parallel migrations work with advisory locks

### Actual behavior

```
ActiveRecord::ConcurrentMigrationError:

Cannot run migrations because another migration process is currently running.

Tasks: TOP => apartment:migrate
(See full trace by running task with --trace)
```

### System configuration
**Rails version**: master
**Ruby version**: 2.4.3

Reference: https://github.com/influitive/apartment/issues/506

I'm open for making a PR request as I think it would be fairly easy. I think `generate_migrator_advisory_lock_id` (https://github.com/rails/rails/blob/master/activerecord/lib/active_record/migration.rb#L1350) needs to be moved to `abstract_adapter` so PostgresAdapter can overwrite the method and implement the following

```ruby
      MIGRATOR_SALT = 2053462845
      def generate_migrator_advisory_lock_id
        db_name_hash = Zlib.crc32(Base.connection.current_schema + Base.connection.current_database)
        MIGRATOR_SALT * db_name_hash
      end
```

Or every adapter has a `current_session_name` method that returns by default the `current_database` but for Postgres `current_schema + current_database`. If anyone can point me in the direction we want to go I can make a PR for it.

**Comment by pts-owentran** [comment]
This issue is still happening with rails 5.1.3.

**Comment by noma4i** [comment]
Rails 5.2 affected

**Comment by nidhindamodaran** [comment]
We are still facing this issue while using apartment gem, What is the status of the fix?
