### ISSUE TITLE
Hide date_select tag rails 5 with jquey not working

### ISSUE THREAD

**Issue by gabolucuy** [rails/rails#31623]
I'm trying to hide a date select tag in rails 5 on document ready with jquey, the tag looks like this:
`<%= date_select :search_input, params[:search_input], class:"form-control mr-sm-2 " ,id:"date_select"%>`
and the jquery code:
`$( document ).on('turbolinks:load', function
  $("#date_select").hide();
})`
### Expected behavior
The element should hide

### Actual behavior
The element doesnt hide, but with other tags the element does hide

### System configuration
**Rails version**:
Rails 5.1.4

**Ruby version**:
ruby 2.4.1p111 (2017-03-22 revision 58053) [x86_64-linux]

**Comment by dwightwatson** [comment]
Your JavaScript code is broken - the function definition is incorrect.

```
$(document).on('turbolinks:load', function () {
  $("#date_select").hide(); 
});
```

This is not an issue with Rails.

**Comment by y-yagi** [comment]
@dwightwatson is right. Please fix your code. 

Also, please use the [mailing list](https://groups.google.com/forum/#!forum/rubyonrails-talk) or StackOverflow for questions/help, where a wider community will be able to help you. We reserve the issues tracker for issues only.

**Comment by gabolucuy** [comment]
I open an issue because i tried many ways to hide the tag but i didn't accomplished, i even opened a question on stackOverflow but got no answer, thats why this was my last option
