### ISSUE TITLE
POSTing doubles up on parameters

### ISSUE THREAD

**Issue by TrevorHinesley** [rails/rails#31631]
### Steps to reproduce

Manually declare a POST route to (example) an AuthController, and post JSON parameters:

Route:
```
post :auth, to: "auth#create"
```

POST to it with a body:
```
{
  "email": "email@email.com",
  "password": "password"
}
```

### Expected behavior
It should POST with only the supplied parameters.

`params` should be:
```
Parameters: {"email"=>"email@email.com", "password"=>"[FILTERED]"}
```

### Actual behavior
Instead, the supplied parameters are added to the root of the `params` hash, as well as being listed a second time, nested under a key matching the controller name:
```
Parameters: {"email"=>"email@email.com", "password"=>"[FILTERED]", "auth"=>{"email"=>"email@email.com", "password"=>"[FILTERED]"}}
```

### System configuration
**Rails version**: 5.1.4

**Ruby version**: 2.3.1p112

**Comment by shivhg** [comment]
This is actual behaviour of rails. It helps during creation where you can just say params[:auth] or during the require.permit check for attr_accessible. 

Refer following for more details
https://stackoverflow.com/questions/9133652/rails-3-params-unwanted-wrapping
http://borgs.cybrilla.com/tils/wrap-parameters-rails/

Also please close the Issue.

**Comment by TrevorHinesley** [comment]
Got it. Thanks!
