### ISSUE TITLE
Russian Doll Caching with Rails 5.2

### ISSUE THREAD

**Issue by tomrossi7** [rails/rails#31635]
I have upgraded an application to Rails 5.2 from 5.1 and all of my tests pass, but caching is not working. I believe there is something wrong with recyclable cache keys. I didn't see anything in the documentation for configuring cache versioning, but maybe I've missed something?

### Steps to reproduce
With Rails 5.2.0.beta2 and caching configured:
```
    config.load_defaults 5.2
    config.cache_store = :dalli_store
```
view:
```
<% cache product do %>
  ...
<% end %>
```
### Expected behavior
The cache should automatically bust when the product is updated.

### Actual behavior
The cache never busts. From looking at the logs, the cache helper doesn't appear to pass version information in to the cache get request:

`Cache read: views/admin/productss/index:f6730463a833fc7265c145e311fd4ea9/products/391526183/
`

**Comment by Fudoshiki** [comment]
in development?
In development env need run one time `rails dev:cache`

```cmd
$ rails dev:cache
Development mode is now being cached.
```
https://blog.bigbinary.com/2016/01/25/caching-in-development-environment-in-rails5.html

**Comment by tomrossi7** [comment]
Caching is working, but the cache is not busting. This is related to the change for recyclable keys.

**Comment by georgeclaghorn** [comment]
The third-party Dalli store is incompatible with recyclable cache keys. Disable that feature or use the built-in Memcache store.

**Comment by tomrossi7** [comment]
@georgeclaghorn thanks for the reply! If I try to use `config.cache_store = :mem_cache_store`, I get the error `Could not find cache store adapter for mem_cache_store (cannot load such file -- dalli)`. The [edge documentation](http://edgeguides.rubyonrails.org/caching_with_rails.html#activesupport-cache-memcachestore) still says it uses Dalli. How do I disable it to use the built-in store?

**Comment by georgeclaghorn** [comment]
The built-in store does use Dalli, so you’ll need to have Dalli installed. (There’s nothing wrong with Dalli itself, just the `DalliStore` that comes with it.)

**Comment by tomrossi7** [comment]
Perfect! I understand now, thanks again!
