### ISSUE TITLE
Cannot use custom fields in :sum operation

### ISSUE THREAD

**Issue by emirkin** [rails/rails#31645]
Using `activerecord (= 5.0.6)`...

`User.select([:kind, '4 as "coeff"']).sum('coeff')`

should not produce

```
ActiveRecord::StatementInvalid: PG::UndefinedColumn: ERROR:  column "coeff" does not exist
LINE 1: SELECT SUM(coeff) FROM "users"
                   ^
: SELECT SUM(coeff) FROM "users"
```

since `coeff` is defined. Am I missing something?

(I double-checked https://apidock.com/rails/v4.0.2/ActiveRecord/QueryMethods/select)

**Comment by mrstebo** [comment]
You could do `User.select([:kind, '4 as "coeff"']).sum {|x| x[:coeff]}`. Although this doesn't do the sum in the query 😅 

For the example you have given, couldn't you do `User.count * 4`? Or do you have a specific scenario?

**Comment by y-yagi** [comment]
Please use the [mailing list](https://groups.google.com/forum/#!forum/rubyonrails-talk) or StackOverflow for questions/help, where a wider community will be able to help you. We reserve the issues tracker for issues only. Thanks.

**Comment by emirkin** [comment]
I ended up using `User.sum("kind * coeff")` with `coeff` being an inline `CASE-END` query.
