### ISSUE TITLE
Error in Rails Guides? (Asset Pipeline: tag helpers' `debug` option)

### ISSUE THREAD

**Issue by rlue** [rails/rails#31647]
From [Section 3.3 of the Edge Guides on the Asset Pipeline](http://edgeguides.rubyonrails.org/asset_pipeline.html#turning-debugging-off):

> Debug mode can also be enabled in Rails helper methods:
> 
> ```erb
> <%= stylesheet_link_tag "application", debug: true %>
> <%= javascript_include_tag "application", debug: true %>
> ```
> 
> The `:debug` option is redundant if debug mode is already on.

When I try this in Rails 5.1, it simply adds a `debug="true"` HTML attribute to the corresponding tag, rather than enabling debug mode on the specified tag helper. Furthermore, the [Edge API documentation](http://edgeapi.rubyonrails.org/classes/ActionView/Helpers/AssetTagHelper.html#method-i-javascript_include_tag) makes no mention of a `debug` option.

I've also looked into the source for the `javascript_include_tag` method as far back as it goes in the repo ([4.1-stable](https://github.com/rails/rails/blob/4-1-stable/actionview/lib/action_view/helpers/asset_tag_helper.rb)), and I see no mention of such an option.

Am I missing something, or is this information incorrect? If so, would the team accept a PR amending this portion of the guides?

**Comment by georgeclaghorn** [comment]
The debug option is (supposed to be) implemented in [sprockets-rails](https://github.com/rails/sprockets-rails). Do you not use Sprockets in your app?

**Comment by rlue** [comment]
Thanks! This was a bug in sprockets-rails; [I've submitted a PR for it](https://github.com/rails/sprockets-rails/pull/418).
