### ISSUE TITLE
ActionDispatch::RequestId#make_request_id strips characters used by common request ID modules

### ISSUE THREAD

**Issue by bradland** [rails/rails#31644]
While using Apache + Passenger, we pass a request ID to our app using [mod_request_id](https://httpd.apache.org/docs/2.4/mod/mod_unique_id.html). This library uses the @ symbol as part of its alphabet, as documented in this paragraph:

>The UNIQUE_ID environment variable is constructed by encoding the 144-bit (32-bit IP address, 32 bit pid, 32 bit time stamp, 16 bit counter, 32 bit thread index) quadruple using the alphabet `[A-Za-z0-9@-]` in a manner similar to MIME base64 encoding, producing 24 characters. The MIME base64 alphabet is actually `[A-Za-z0-9+/]` however + and / need to be specially encoded in URLs, which makes them less desirable.

The `make_request_id` method removes the @ symbol from any request ID passed through `X-Request-Id`.

https://github.com/rails/rails/blob/9a130ee465fd8bd933d62a766ac1abcbb818b0be/actionpack/lib/action_dispatch/middleware/request_id.rb#L31

Any chance `make_request_id` could be loosened up a bit to accommodate request IDs generated by this common library?

**Comment by y-yagi** [comment]
Fixed by #31815
