### ISSUE TITLE
ActiveStorage attachment validations not working

### ISSUE THREAD

**Issue by swordray** [rails/rails#31656]
### Steps to reproduce

```ruby
class User < ActiveRecord::Base
  has_one_attached :avatar

  validates_each :avatar do |record, attr, value|
    record.errors.add attr unless record.avatar.attachment.blob.content_type.starts_with?('image/')
  end
end
```

### Expected behavior
A non-image avatar should not be saved.

### Actual behavior
saved.

### System configuration
**Rails version**: master@428939b

**Ruby version**: 2.5.0

**Comment by georgeclaghorn** [comment]
Active Storage doesn’t support blob validations yet, so this is the expected behavior.

**Comment by rubiii** [comment]
Any plans on supporting validation?

**Comment by kvoshell** [comment]
```if avatar.attached? && !avatar.attachment.blob.content_type.in?(%w(image/png image/jpeg))
        errors.add(:avatar, 'Must be an image file')
      end```

This works for me

**Comment by kvoshell** [comment]
```
if avatar.attached? && !avatar.attachment.blob.content_type.in?(%w(image/png image/jpeg))
    errors.add(:avatar, 'Must be an image file')
end
```

This works for me.

**Comment by georgeclaghorn** [comment]
That won’t prevent the blob from being stored.

**Comment by tomrossi7** [comment]
I've used this code for now. I believe this will remove the attachment, blob, and file:

```
  validate :logo_validation

  def logo_validation
    if logo.attached?
      if logo.blob.byte_size > 1000000
        logo.purge
        errors[:base] << 'Too big'
      elsif !logo.blob.content_type.starts_with?('image/')
        logo.purge
        errors[:base] << 'Wrong format'
      end
    end
  end

```

**Comment by Dejosel** [comment]
@tomrossi7 when i try to use the validation (e.g. a PDF) the whole rails code is broken...

**Comment by SampsonCrowley** [comment]
how is this closed? this is a MAJOR feature lapse. just because it's not supported yet, doesn't mean it's correct

**Comment by SampsonCrowley** [comment]
even further, how is ActiveStorage even released if it can't be validated?

**Comment by Dejosel** [comment]
Answer us, please Any plans on supporting validation?

**Comment by ben-rabid** [comment]
+1
