### ISSUE TITLE
Silent failure when an ActiveJob::SerializationError occured

### ISSUE THREAD

**Issue by zedtux** [rails/rails#31654]
### Steps to reproduce

I was passing a symbol in one of the arguments, but there was no error raised, no log, nothing helping me to find out the issue.

### Expected behavior

Have at lease a warning in the log file, or an error raised breaking the code.

### Actual behavior

The `[ActiveJob] Enqueued <job name> (Job ID: <job id>) to Sidekiq(<queue name>) with arguments: "<argument list>"` log appears, but the web UI of my background job library remains empty and nothing happens.

### System configuration
**Rails version**: 4.2

**Ruby version**: 2.4

**Comment by rafaelfranca** [comment]
Can you please provide a sample application that reproduces the error?

**Comment by zedtux** [comment]
Thank you @rafaelfranca for suggesting me to create an app to reproduce it. Doing so I figured out that we have some tricky code hiding this error 😞.
