### ISSUE TITLE
PG::Error : result has been cleared rails serilization

### ISSUE THREAD

**Issue by shaikshakeel** [rails/rails#31666]
Hi,

i am using ruby-pg gem(0.18.4) for PostgreSQL connection. i am writing below line to run SQL queries in PostgreSQL.  `result = connection.exec(sql)`. 

i have a model called `Test`. it has serialized column like `serialize :meta`. i am storing the `result` into MySQL into serialized column `meta`

When i query meta column using Active Record `Test.select('meta').where(:id=> 726345)`. it is throwing error `PG::Error Exception: result has been cleared`

data in MySQL row is : 
```
---------------------------------------------------------------------
ID          Name                meta
------------------------------------------------------------------------
726345      test               - :status: :success
                                 :result: !ruby/object:PG::Result {}
-------------------------------------------------------------------------
```

i found out the problem with empty PG::Result object. i have a lot of rows in MYSQL like above. how can i query those records ?

### System configuration
Rails version: 5.1
Ruby version:2.2.5
MySQL version:5.6

any help ??

**Comment by matthewd** [comment]
Please use the mailing list or StackOverflow for questions/help, where a wider community will be able to help you. We reserve the issues tracker for issues only.
