### ISSUE TITLE
ActiveSupport::TimeZone.country_zones('GB') returns Edinburgh instead of London

### ISSUE THREAD

**Issue by MattFenelon** [rails/rails#31668]
### Steps to reproduce

```ruby
> ActiveSupport::TimeZone.country_zones('GB')
=> [#<ActiveSupport::TimeZone:0x00007f8c20349d48 @name="Edinburgh", @utc_offset=nil, @tzinfo=#<TZInfo::DataTimezone: Europe/London>>]
```

### Expected behavior

```ruby
ActiveSupport::TimeZone.country_zones('GB').map(&:name) == ['London']
```

The `ActiveSupport::TimeZone` returned for the UK (ISO 3166-1 Alpha2 code 'GB') is Edinburgh. I believe most UK nationals would expect this to return the 'London' timezone.

### Actual behavior

```ruby
ActiveSupport::TimeZone.country_zones('GB').map(&:name) == ['Edinburgh']
```

It seems `load_country_zones`, which is called from `country_zones`, returns the first entry from `MAPPING` for the country code, via the tz identifier for 'GB' - 'Europe/London' (line 271):

https://github.com/rails/rails/blob/e97221a32d02cb0691760fc1783da74e4c3a371a/activesupport/lib/active_support/values/time_zone.rb#L267-L276

And in `MAPPING` Edinburgh is added before London:

https://github.com/rails/rails/blob/e97221a32d02cb0691760fc1783da74e4c3a371a/activesupport/lib/active_support/values/time_zone.rb#L70-L72

### System configuration
**Rails version**:
Rails 5.2.0.beta2

**Ruby version**:
ruby 2.4.3p205 (2017-12-14 revision 61247) [x86_64-darwin17]

**Comment by rafaelfranca** [comment]
cc @pixeltrix

**Comment by alpracka** [comment]
There is also problem that http://api.rubyonrails.org/classes/ActiveSupport/TimeZone.html MAPPING constant doesn't include all the zone identifiers as TZInfo has. Example:

``` ruby
# Zone identifiers for Australia
au_zone_identifiers = TZInfo::Country.get("AU").zone_identifiers
au_zone_identifiers.map {|i| ActiveSupport::TimeZone::MAPPING.key(i) }
# => [nil, nil, "Hobart", nil, "Canberra", "Sydney", nil, "Brisbane", nil, "Adelaide", "Darwin", "Perth", nil]
```

**Comment by pixeltrix** [comment]
@MattFenelon I think the right thing to do here is return both Edinburgh and London.

@alpracka for those without mappings we still return a timezone object but it has the tzid as the name. Don't really want to add mappings for every timezone.
