### ISSUE TITLE
Preloader behaviour change in Rails 5.2

### ISSUE THREAD

**Issue by TheRusskiy** [rails/rails#31661]
### Steps to reproduce
`ActiveRecord::Base::Preloader.new.preload(order, order_items: { order_subitems: [] })`

### Expected behavior
Expected to preload given associations for `order`.

### Actual behavior
Fails with error `undefined method compact for #Order...`

### System configuration
**Rails version**:
5.2.0.beta2

This happens due to this commit https://github.com/rails/rails/commit/4bb4824ae711b7b550e8e33b428110575adaefac#diff-8bdf4d71fc80d5866e82a8024bb148d2 dated 18 Sep 2017.
If before preloader would work for a single object via `Array.wrap` now it only works for arrays.

To be fair comments for this method do state that it works for arrays, not single objects. But it worked this way ever since rails 3.
And this change is breaking a lot of stuff for me.
If you guys decide to keep this, at least put a big bold deprecation in release notes.

**Comment by kamipo** [comment]
Thanks for the report. I've restored the passing single record support in b8e5d4f9dffb35b7b0ca2f583cb1c9258a7d7cbe.
