### ISSUE TITLE
ActiveStorage's signed keys not unique, e.g. can be reused for other variants

### ISSUE THREAD

**Issue by koenpunt** [rails/rails#31662]
The comments in [`BlobsController`](https://github.com/rails/rails/blob/d749b5d0e8a659f2018a3acdd0061ec6b57b7f7e/activestorage/app/controllers/active_storage/blobs_controller.rb#L5) and [`VariantsController`](https://github.com/rails/rails/blob/af0caadb8d9781770399c1804976af4a71d1313b/activestorage/app/controllers/active_storage/variants_controller.rb#L5) mention `security-through-obscurity`, altho I would argue that this is no security at all, since the signed keys returned from `ActiveStorage::Variation.encode` are not unique, and thus the variant key of one stored file, can be reused for another file.

For example; a website provides you thumbnails, where upon purchase you get access to the download page. The signed key then being used, can be reused for any other image, by replacing the signed key part in the thumbnail URL.

I might be misunderstanding the "security-through-obscurity" case here, and it could be that this is the designed behavior, but I would say it would be better to generate these signed keys with an additional variable parameter (filename maybe), so that the signed key for `1000x1000` is not for every file the same.

**Rails version**: 5.2.0.beta2

**Ruby version**: 2.4.1p111

**Comment by georgeclaghorn** [comment]
Security-through-obscurity refers more to the signed blob ID than the signed variation key, even though the comment on `VariantsController` suggests otherwise. (It should be edited not to do that.)

As I see it, variations are generally harmless. The point of the key is primarily to have a convenient way to reference one in a URL.

**Comment by koenpunt** [comment]
> As I see it, variations are generally harmless.

Maybe, but in some occasions they're not; like the example I gave above. And I can give more examples like it, but it all boils down to that sometimes not all variants are equal.

> The point of the key is primarily to have a convenient way to reference one in a URL.

I figured it was for preventing users to request any variant they want, but it is just for convenience, then why does it has to be encoded at all?

Then also, what is the static part doing in the variant key?

```
eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBFZz09IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--d8898284494e573d3806c5d773a4f831b8cd862a
^ static hash                                                                     ^ encoded 1000x1000
```

Anyway; if the file (digest) would be a variable in generating the signature, the issue would not exist. I can try and open a PR with this proposed change?
