### ISSUE TITLE
AR 5.1.4 causes `Gem::LoadError` with pg 1.0.0 (wants '~> 0.18')

### ISSUE THREAD

**Issue by rgarner** [rails/rails#31669]
### Steps to reproduce

* Start a new Rails project with ActiveRecord 5.1.4
* Add `gem postgres, '1.0.0'` to the Gemfile
* `bundle`
* Start `bundle exec rails s`
* Visit the root page

### Expected behavior
The default public page should display

### Actual behavior
`Gem::LoadError can't activate pg (~> 0.18), already activated pg-1.0.0. Make sure all dependencies are added to Gemfile.`

it appears that a squiggly [version check](https://github.com/rails/rails/blob/master/activerecord/lib/active_record/connection_adapters/postgresql_adapter.rb#L4) is made in `postgresql_adapter.rb` that fails now `pg` has recently released `1.0.0`.

### System configuration
**Rails version**: 5.1.4
**Ruby version**: 2.4.1

**Comment by francesco-loreti** [comment]
I have opened an same issue on pg repository
[https://bitbucket.org/ged/ruby-pg/issues/270/pg-100-x64-mingw32-rails-server-not-start](url)

**Comment by rafaelfranca** [comment]
Thank you for the issue. Rails still don't support pg 1.0.

**Comment by johnnyshields** [comment]
@rafaelfranca is there an ETA for getting support? Also I'm curious as to why the maintainers of the PG gem didn't test/coordinate their 1.0.0 release with Rails.

**Comment by yahonda** [comment]
Refer #31671

**Comment by rafaelfranca** [comment]
It is already supported in the stable branches, just not released yet

**Comment by dogweather** [comment]
This seems to be a bug; an [incorrect version spec](https://github.com/rails/rails/blob/master/activerecord/lib/active_record/connection_adapters/postgresql_adapter.rb#L4). (Doesn't have to do with supporting pg 1.0.0 or not.)

If a bug fix version is due out sooner than the stable branches, could we accept a fix for this?

**Comment by olliebennett** [comment]
After updating to [Rails 5.1.5.rc1](http://weblog.rubyonrails.org/2018/2/1/Rails-5-1-5-rc1-has-been-released/), this problem seems to be resolved.

It seems `pg 1.0` support isn't mentioned in the [ActiveRecord 5.1.5.rc1 changelog](https://github.com/rails/rails/blob/v5.1.5.rc1/activerecord/CHANGELOG.md) though - should it be?

Thanks a lot!

**Comment by kjerrya** [comment]
I tried 5.1.5.rc1 with 0.18.0 and 1.0.0 uninstall/reinstall and a new error comes now:

`C:/Ruby25-x64/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:135:in `require': cannot load such file -- bundler/dep_proxy (LoadError)`
