### ISSUE TITLE
Rails does not work with pg 1.0.0

### ISSUE THREAD

**Issue by thomasfedb** [rails/rails#31673]
### Steps to reproduce
1. Ensure `gem "pg"` is in `Gemfile`
2. `bundle update`
3. `rails s`

### Expected behavior
Rails server should run

### Actual behavior
> /.../gems/activerecord-5.1.4/lib/active_record/connection_adapters/connection_specification.rb:188:in `rescue in spec': Specified 'postgresql' for database adapter, but the gem is not loaded. Add `gem 'pg'` to your Gemfile (and ensure its version is at the minimum required by ActiveRecord). (Gem::LoadError)

### System configuration
**Rails version**:  5.1.4
**Ruby version**: 2.4.3

The issue appears to be caused by this line: https://github.com/rails/rails/blob/15ef55efb591e5379486ccf53dd3e13f416564f6/activerecord/lib/active_record/connection_adapters/postgresql_adapter.rb#L4

**Comment by rgarner** [comment]
https://github.com/rails/rails/issues/31669

**Comment by thomasfedb** [comment]
Thanks @rgarner

**Comment by kjerrya** [comment]
I'm having major issues with this right now. Is there still no fix?

**Comment by rafaelfranca** [comment]
It is fixed in the 5.1.5.rc1 release

**Comment by celsoMartins** [comment]
thank you!

**Comment by nadavb** [comment]
I solved it by putting this in the Gemfile:

`gem 'pg', '~> 0.21'`

**Comment by thomasfedb** [comment]
@nadavb pg version 1.0.0 should work fine with rails 5.1.5 and newer.

**Comment by erdemoflaz** [comment]
are you king?
thnx bro!

**Comment by corregidor** [comment]
I have the same problem, If i generate de project rails new mm -d postgresql I can run postgresql

**Comment by mikebaldry** [comment]
Not ideal, but a fix to allow new version of the PG gem in a Rails 4.2.x application is achieved by:

```ruby
# in config/application.rb after Bundler.require(..)

# catch the incorrect pg version check, replace it with one that will pass
module Kernel
  def gem_with_pg_fix(dep, *reqs)
    if dep == "pg" && reqs == ["~> 0.15"]
      reqs = ["~> 1.0"]
    end
    gem_without_pg_fix(dep, *reqs)
  end

  alias_method_chain :gem, :pg_fix
end
# pg 1.0 gem has removed these constants, but 4.2 ActiveRecord still expects them
PGconn   = PG::Connection
PGresult = PG::Result
PGError  = PG::Error
```

This is working for me until we are able to upgrade to Rails 5
