### ISSUE TITLE
Accessing the ActiveStorage file in the controller

### ISSUE THREAD

**Issue by iamdriz** [rails/rails#31676]
Not 100% sure if this is a bug or a missing feature of ActiveStorage, or I purely just don't know how to do it.

### Steps to reproduce

If I have a method like this in my controller:
~~~
def show_file
  send_data @user.avatar.blob, filename: @user.avatar.blob.filename, type: @user.avatar.blob.content_type, disposition: 'inline'
end
~~~
It seems we can't access the blob of the file itself because `blob` is a method to the ActiveStorage blob object. The source: https://github.com/rails/rails/blob/5e8c79a6fafb8d7a84c272b3c9a0474a0d01b471/activestorage/lib/active_storage/attached/one.rb#L67

Trying to change it so that you send the file instead also does not work:
~~~
def show_file
  send_file helpers.url_for(@user.avatar), filename: @user.avatar.blob.filename, type: @user.avatar.blob.content_type, disposition: 'inline'
end
~~~

### Expected behavior
The file should be accessible in the controller as either data or path.

### Actual behavior
Using `send_data` and passing the `blob` method causes empty render for the file.
Using `send_file` throws an error that the file can't be found even though you can access the file in the browser directly from the value of `url_for(@user.avatar)`.

### System configuration
**Rails version**: 5.2

**Ruby version**: 2.4.1

Is it possible to return an ActiveStorage file using `send_data` or `send_file`?

**Comment by georgeclaghorn** [comment]
> Is it possible to return an ActiveStorage file using `send_data` or `send_file`?

It is, but I’d advise against it. Prefer to redirect to a signed URL for the blob instead:

```ruby
redirect_to @user.avatar.service_url
```

If you must serve the file yourself, download it first:

```ruby
send_data @user.avatar.download, filename: @user.avatar.filename, content_type: @user.avatar.content_type
```

Avoid doing this without a good reason, as it entails reading the entire blob into memory.

**Comment by Hamdan85** [comment]
Hey guys.. I really need to do this, but my files always come corrupted
