### ISSUE TITLE
link_to block does not forward :method => :delete

### ISSUE THREAD

**Issue by nicolehu15** [rails/rails#31672]
### Steps to reproduce
I'm trying to create a logout link for the devise gem. It works when link_to is not a block but stops working once it is a block

Working code:
```<%= link_to('Logout', destroy_user_session_path, method: :delete) %>```

Working html:
```<a rel="nofollow" data-method="delete" href="/users/sign_out">Logout</a>```

Faulty code: 
```
<%= link_to destroy_user_session_path, method: :delete do %>
  <div class="button-class">
    <span class="icon-Logout---white icon"></span>
    SIGN OUT
  </div>
<% end %>
```

Faulty html:
```
<a rel="nofollow" data-method="delete" href="/users/sign_out">
  <div class="button-class">
    <span class="icon-Logout---white icon"></span>
    SIGN OUT
  </div>
</a>
```

### Expected behavior
This link should send a DELETE request to /user/sign_out 

### Actual behavior
This link sends a GET request to /user/sign_out, returning with the error 'No route matches [GET] "/users/sign_out"'

### System configuration
**Rails version**:
4.2.9

**Ruby version**:
2.4.1

**Comment by rafaelfranca** [comment]
Can you please provide a sample application that reproduces the error?

**Comment by jimmybaker** [comment]
`data-method="delete"` is present in the "faulty html"
Was that a mistake?

**Comment by nicolehu15** [comment]
It wasn't a mistake. However, I got around to fix this. 

Turns out I had an issue where my <a> link was located at a different location than the contents of the <a> link. This was due to styling related changes. 

I'm not yet sure why this led to it converting from 'delete' to 'get' but correcting the style in my code helped fix this
