### ISSUE TITLE
How to attach same file to multiple models with ActiveStorage

### ISSUE THREAD

**Issue by ribanez7** [rails/rails#31674]
### Steps to reproduce

I want to upload a file once, on a model, and also create a record on the active_storage_attachments table linking same file to a diferent model.

My first attempt has been the following one:

```ruby
class Tax < ApplicationRecord
  has_one_attached :document
  belongs_to :operation
end

class Operation < ApplicationRecord
  has_many_attached :documents
  has_many :taxes
end
```

```ruby
def create
  @tax = Tax.new(tax_params)
  if @tax.save
    @tax.document.attach(document_param)
    @tax.operation.documents.attach(@tax.document)
    redirect_to home_path
  else
    render :new
  end
end
```

### Expected behavior

The file should be reflected as attached also for the relation (Operation). A record on active_storage_attachment would do the trick maybe.

### Actual behavior

An ActiveRecord::RecordInvalid error is raised because the blob must exist.

I could simply do @tax.operation.documents.attach(document_param), but I'm thinking on other contexts where the blob won't be available. ActiveRecord callbacks, for example.

### System configuration
**Rails version**: 5.2.0.beta2

**Ruby version**: 2.4.1p111

**Comment by georgeclaghorn** [comment]
You can pass a blob to `#attach`:

```ruby
@tax.operation.documents.attach(@tax.document.blob)
```

**Comment by ribanez7** [comment]
Hi George,

Many thanks, this solves my problem. I don't know if it should be necessary to exemplify the relation (.blob) in the docs, right in the place where it says: `One file, one blob. You can associate the same blob with multiple application models as well.`. Or maybe it is clear this way, I just escaped the sentence.

Anyway, closing the issue.

Thanks
