### ISSUE TITLE
Upgrade CSP script_src default from unsafe_inline to nonce approach

### ISSUE THREAD

**Issue by dhh** [rails/rails#31689]
The new default CSP was preventing SJR and Turbolinks redirects from working out the box, as described in #31273. The default was changed to unsafe_line in https://github.com/rails/rails/commit/0f7d3b612cc9264a90a1da6820d442099d8641f8, but the proper fix is to use the nonce approach instead.

**Comment by oliverguenther** [comment]
The `secureheaders` gem already does exactly this by adding helpers that output [nonce and hash sources](https://w3c.github.io/webappsec-csp/2/#nonce_source) per script tag for each request: https://github.com/twitter/secureheaders

They do that by adding a `nonced_javascript_tag` wrapper that appends the nonce automatically. I found that to be very straightforward. Maybe it can inspire your approach.

**Comment by aledalgrande** [comment]
Need any help here? I am really interested in getting 5.2.0 out 😊

**Comment by dhh** [comment]
This will be a lovely upgrade over what we have, but it's not a blocker for 5.2.

**Comment by glaszig** [comment]
i can't seem to figure out how turbolinks is supposed to work with csp level 3 (nonce + strict-dynamic). is this not yet supported?
