### ISSUE TITLE
Allow customization of how content_type is determined in ActiveStorage

### ISSUE THREAD

**Issue by codehugger** [rails/rails#31686]
Hi,

I have been reimplementing a part of my solution (that currently uses Shrine) using ActiveStorage in the 5.2.0 beta2. I think there should be a an easy way to customize how the UploadedFile content_type gets determined, similar to Shrine's DetermineMimeType plugin works.

http://shrinerb.com/rdoc/classes/Shrine/Plugins/DetermineMimeType.html

Something like

```ruby
config.active_storage.content_type_analyzer = :mimemagic
```

My use case is that in my application users are uploading a lot of files from proprietary hardware that produces binary files that have no extensions (DICOM files). These files can be easily identified by the `file` command or using [mimemagic](https://github.com/minad/mimemagic) but they get the content_type 'application/octet-stream' when uploaded through ActiveStorage because they have no extension. When I try to edit the content_type directly in a custom analyzer I get a checksum error.

If somebody knows how to do this then please share or point me in the right direction!

### System configuration
**Rails version**: Rails 5.2.0.beta2

**Ruby version**: ruby 2.5.0p0 (2017-12-25 revision 61468) [x86_64-darwin17]

**Comment by georgeclaghorn** [comment]
Thanks, but we don’t take feature requests in the issue tracker.

I’d recommend opening a PR, but I’m already in the process of adding MimeMagic-based content type extraction. We need it for Basecamp, too.
