### ISSUE TITLE
Consider sandboxing binaries used in previewers

### ISSUE THREAD

**Issue by alex** [rails/rails#31697]
Currently the previewers in rails shell out to the `mupdf` and `ffmpeg` binaries:

- https://github.com/rails/rails/blob/master/activestorage/lib/active_storage/previewer/pdf_previewer.rb#L19
- https://github.com/rails/rails/blob/master/activestorage/lib/active_storage/previewer/video_previewer.rb#L19-L20

Unfortunately, these are both large codebases, parsing complex formats, written in memory unsafe languages, with a history of security issues. [Here](https://bugs.chromium.org/p/oss-fuzz/issues/list?can=1&q=label%3AProj-ffmpeg+Type%3DBug-Security+&colspec=ID+Type+Component+Status+Proj+Reported+Owner+Summary&cells=ids) are 82 security vulnerabilities that Google's OSS-Fuzz has found in ffmpeg alone.

I'd like to encourage Rails to run these binaries under an OS sandbox so that vulnerabilities in these binaries cannot be used to trivially take over a system. http://nsjail.com/ is a tool that can simplify sandboxing on Linux.

**Comment by georgeclaghorn** [comment]
I’d love to sandbox third-party previewing/analysis utilities by default, and DHH and I have discussed it, but I don’t know that it’s practical. We have to support more than just Linux. Please do investigate and open a PR.

We could, at minimum, explain how to do it in a guide. Here’s how we use custom previewers and analyzers for sandboxing in Basecamp:

```ruby
# config/initializers/active_storage.rb
require 'active_storage/analyzer/sandboxed_video_analyzer'
require 'active_storage/previewer/sandboxed_video_previewer'

Rails.application.configure do
  # Customize analyzers and previewers. Use LXC sandboxes where appropriate.
  if BC3.deployment.online?
    config.active_storage.analyzers = [
      ActiveStorage::Analyzer::ImageAnalyzer,
      ActiveStorage::Analyzer::PDFAnalyzer,
      ActiveStorage::Analyzer::SandboxedVideoAnalyzer.build(config.x.sandboxes.ffmpeg)
    ]

    config.active_storage.previewers = [
      ActiveStorage::Previewer::SandboxedPDFPreviewer.build(config.x.sandboxes.mupdf),
      ActiveStorage::Previewer::SandboxedVideoPreviewer.build(config.x.sandboxes.ffmpeg)
    ]
  else
    config.active_storage.analyzers.append ActiveStorage::Analyzer::PDFAnalyzer
  end
end
```

```ruby
# lib/active_storage/previewer/sandboxed_video_previewer.rb
require 'active_storage/previewer/video_previewer'
require 'active_storage/sandboxing'

class ActiveStorage::Previewer::SandboxedVideoPreviewer < ActiveStorage::Previewer::VideoPreviewer
  include ActiveStorage::Sandboxing

  private
    def draw_relevant_frame_from(file, &block)
      draw bin, sandbox, ffmpeg_path, '-i', file.path, '-y', '-vcodec', 'png',
        '-vf', 'thumbnail', '-vframes', '1', '-f', 'image2', '-', &block
    end
end
```

```ruby
# lib/active_storage/sandboxing.rb
module ActiveStorage::Sandboxing
  extend ActiveSupport::Concern

  included do
    class_attribute :bin, :sandbox, :tempdir
  end

  class_methods do
    def build(bin:, sandbox:, tempdir:)
      Class.new(self).tap do |klass|
        klass.bin     = bin
        klass.sandbox = sandbox
        klass.tempdir = tempdir
      end
    end

    def inspect
      name.presence || "#{superclass.name}(bin: #{bin.inspect}, sandbox: #{sandbox.inspect}, tempdir: #{tempdir.inspect})"
    end
  end
end
```

/cc @rails/security

**Comment by alex** [comment]
Was closing this intentional?

**Comment by georgeclaghorn** [comment]
Yes. We don’t take feature requests in the issue tracker.
