### ISSUE TITLE
Rails guide needs some clarification for noobs.

### ISSUE THREAD

**Issue by loothunter1** [rails/rails#31699]
Sorry, if I post this in a wrong place, but [Contributing to the Rails Documentation](http://edgeguides.rubyonrails.org/contributing_to_ruby_on_rails.html#contributing-to-the-rails-documentation) paragraph says to "open a pull request", but opening a request is itself requires to make a change to source code. Which I'm not doing because I just want to make a suggestion about a guide.
So, that's the **first issue** - [Contributing to the Rails Documentation](http://edgeguides.rubyonrails.org/contributing_to_ruby_on_rails.html#contributing-to-the-rails-documentation) instructions should be more clear.

And the **second issue**, that I wanted to tell about is an SQL statement in [Creating Active Record Model](http://guides.rubyonrails.org/active_record_basics.html#creating-active-record-models) tutorial. You see, I am a new guy to all this web design stuff. I just got some basic knowledge of HTML and started to learn Ruby on Rails. So not only I had to search the web for what that SQL statement actually means, but I also found out that this is not SQL statement, but **MySQL** statement which has a slightly different syntax. So, my suggestion is - either put a link to a viable MySQL tutorial/documentation for people who don't have prior knowledge of Relational Data Bases or scrap SQL reference altogether and just write that "product" table has two columns with certain properties.

Again, sorry if I post this in the wrong section, but that's the only place I figured out my request should go. Where else?

**Comment by daveshah** [comment]
I think opening a pull request with a [change to the documentation](https://github.com/rails/rails/blob/master/guides/source/active_record_basics.md) might be a good way to request the change you're suggesting. 
I read through the section you mention. 
Being explicit about this being a MySQL statement wouldn't hurt - to at least avoid confusion for beginners. 
Do you think adding a section that calls out that _some_ knowledge of relational databases would be helpful but is outside the scope of these guides?

**Comment by y-yagi** [comment]
Thanks for your suggestion. But we reserve the Rails issue tracker only for bugs in Rails. 
Please use the [Rails Core mailing list](https://groups.google.com/forum/#!forum/rubyonrails-core) for feature requests or creates a PR. 
Thanks!
