### ISSUE TITLE
Generated modules repeatedly added to autoloaded_constants after an error

### ISSUE THREAD

**Issue by rmosolgo** [rails/rails#31694]
Hi! 

Thanks for your work making Rails so great! I'm having a little trouble with `ActiveSupport::Dependencies` in development and I wonder if you can help me through it. 

The issue works like this (link to Rails app below): 

- In a controller, reference a constant
- In that module/class definition, reference another constant which is in an autogenerated module 
- In that _last_ constant (which is inside a generated module), have some kind of error that prevents the constant from being loaded, for example, a runtime error in the class definition. 
- Load a page which triggers the error; see the error page 
- After seeing the error page, correct the error 
- Reload the page 
- The server spins forever :'( 

I've been [hunting this issue](https://github.com/rmosolgo/graphql-ruby/issues/651) for about 10 months in the context of graphql-ruby, but finally had the good sense to investigate it in a plain Rails context. 

I _did_ find a work-around, although it's pretty heavy-handed: 

```ruby
    class UniqueArray < Array
      def <<(other)
        if include?(other)
          self
        else
          super(other)
        end
      end
    end
    ActiveSupport::Dependencies.autoloaded_constants = UniqueArray.new
```

(I use this wacky class instead of `Set` because `Set` doesn't implement some methods like `.concat`, which are used by `ActiveSupport::Dependencies`.)

Are you interested in pursuing this issue in Rails? If so, I'm happy to search for a more proper solution and submit a pull request. If you think a certain approach would be best, please let me know and I'd love to look into it! 

Thanks for your review!

### Steps to reproduce

Here's a Rails app to demonstrate the issue, with instructions in the readme: 

https://github.com/rmosolgo/constant-loading-issue

### Expected behavior

The auto-generated module should be unloaded once, then reloaded once. 

### Actual behavior

After the error, the auto-generated module is _in_ `ActiveSupport::Dependencies.autoloaded_constants`, but the constant is _not_ defined in Ruby. So, during `ActiveSupport::Dependencies.remove_constant`, the constant is re-loaded, re-added to `autoloaded_constants`, then removed. Since the constant appears _again_ in `autoloaded_constants`, it is next in line to be removed, and the subsequent call to `remove_constant` starts this process from the beginning. This begins an infinite loop. (Well, not infinite, Ruby would probably run out of memory eventually!)

### System configuration

**Rails version**: 5.1.4

**Ruby version**: 2.4.1

**Comment by gwincr11** [comment]
This is a pretty good description, thanks for the app! I am going to dig into some possible approaches.

**Comment by rmosolgo** [comment]
Ok, thanks for talking a look!
