### ISSUE TITLE
Rails Guides - link to ebook (.mobi) version is 404

### ISSUE THREAD

**Issue by jm3** [rails/rails#31709]
The link on https://guides.rubyonrails.org ([`guides/source/index.html.erb`](https://github.com/rails/rails/blob/92703a9ea5d8b96f30e0b706b801c9185ef14f0e/guides/source/index.html.erb)) that points to the Kindle version of Rails Guides is 404.

After reading the Rails Guides contribution docs, I was able to successfully (re-)generate the Kindle docs using:

    bundle install
    cd guides
    setupkindlerb
    # install kindlegen from https://www.amazon.com/gp/feature.html?docId=1000765211
    rake guides:generate:kindle

So the rake tasks and source generation seem to be fine. 

What I can tell from generating the Kindle file locally for Edge Rails is that the .mobi file *is* correctly available at `edgeguides.org`: ([ruby_on_rails_guides_562dd04.mobi](http://edgeguides.rubyonrails.org/kindle/ruby_on_rails_guides_562dd04.mobi)), but the link that specifically references the 5.1.4 guide [ruby_on_rails_guides_v5.1.4.mobi](http://edgeguides.rubyonrails.org/kindle/ruby_on_rails_guides_v5.1.4.mobi) does not exist).

**Comment by y-yagi** [comment]
Thanks for creating an issue. This is duplicated of #29865. Let's track that.
