### ISSUE TITLE
App update extends asset paths for api-only app

### ISSUE THREAD

**Issue by schmijos** [rails/rails#31712]
### Steps to reproduce

I ran `rails app:update` to update my api-only app from Rails 5.0 to 5.1. The assets initializer is being updated the following way:

![image](https://user-images.githubusercontent.com/245443/34949339-19127980-fa10-11e7-8201-83b5587b7eb0.png)

### Expected behavior
I'd not expect my asset path to be extended because I don't use the asset pipeline.

### Actual behavior
It adds `node_modules` to the asset path.

`bin/yarn` is also added by the way even though I don't need it for an api-only app.

### System configuration
**Rails version**: 5.1

**Ruby version**: 2.4

**Comment by y-yagi** [comment]
Thanks for creating an issue. This issue already fixed by #28557. 
So latest Rails, will not create `bin/yarn` and `initializers/assets.rb` in `app:update` task. Thanks.
