### ISSUE TITLE
validates_uniqueness_of with scope does not work

### ISSUE THREAD

**Issue by innovationsbg** [rails/rails#31718]
I have table posts (Post model) and table languages (Language model). Post has many languages and language belongs to the Post. Languages table has columns - id, post_id and language. I want that language column to be unique, but for a scope of the Post (scope: :post_id). The problem is that if I type same string for all  languages in the form, it validates them insert to the table and there is no error. I have created repo for this:  [https://github.com/innovationsbg/untitled](https://github.com/innovationsbg/untitled)

**Comment by joshmn** [comment]
Assuming below accurately depicts the issue you're having, this test passes correctly. 

```
begin
  require "bundler/inline"
rescue LoadError => e
  $stderr.puts "Bundler version 1.10 or later is required. Please update your Bundler"
  raise e
end

gemfile(true) do
  source "https://rubygems.org"

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  gem "activerecord", "5.1.0"
  gem "sqlite3"
  gem 'pry'
end

require "active_record"
require "minitest/autorun"
require "logger"

Minitest::Test = MiniTest::Unit::TestCase unless defined?(Minitest::Test)

ActiveRecord::Base.establish_connection(adapter: "sqlite3", database: ":memory:")
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :posts, force: true do |t|
    t.string :title 
  end

  create_table :languages, force: true do |t|
    t.integer :post_id
    t.string :language 
  end
end

class Post < ActiveRecord::Base
  has_many :languages

  validates :title, presence: true

  accepts_nested_attributes_for :languages
  validates_associated :languages
end

class Language < ActiveRecord::Base
  validates_presence_of :language 
  belongs_to :post, :inverse_of => :languages
  validates_uniqueness_of :language, scope: :post_id 
end

class BugTest < Minitest::Test
  def test_association_stuff
    post = Post.new
    post.assign_attributes(:title => "This is a title", :languages_attributes => [{:language => "English"}])
    post.save!
    assert post.id.present?
    assert_raises ActiveRecord::RecordInvalid do 
      post.languages.create!(:language => "English")
    end
  end
end
```

**Comment by innovationsbg** [comment]
Your test is not for the correct case. This is the correct case:
`  def test_association_stuff
    post = Post.new
    assert_raises ActiveRecord::RecordInvalid do
      post.assign_attributes(:title => "This is a title", :languages_attributes => [{:language => "English"}, {:language => "English"}])
      post.save!
    end
  end`

**Comment by joshmn** [comment]
That makes more sense. That's a bug, I think (I don't contribute _yet_)

Enforcing these constraints on your database _does_ make this fail, `add_index :languages, [:post_id, :language], :unique => true` but it should also fail within ActiveRecord I believe.

**Comment by sgrif** [comment]
Can someone please provide a full executable example that fails?

**Comment by joshmn** [comment]
@sgrif I updated mine an attempted to reflect OPs reported bug.

**Comment by sgrif** [comment]
Thank you

**Comment by innovationsbg** [comment]
Add unique indexes does not fix the problem. Still validation doesn't work and you will get only the MySQL error.

**Comment by joshmn** [comment]
@innovationsbg it raises ActiveRecord::RecordNotUnique; I've updated the test case to reflect that for you.

**Comment by innovationsbg** [comment]
Ok, thx, but this still is not the fix, because there is and MySQL error which in the production user will see 500 error, I guess,  and this will not add error to `@post.errors`. I will search a way with custom validation in the model. I just need to see how to get the array of languages in the custom validation method. I see if I use custom validation method with `self.public_methods`, there are most of the validations like `validates_confirmation_of,  validates_length_of`, but not uniqueness validation. And another thing, in the custom validation method with some languages added, it loop through the languages array  twice. I mean validation method is called twice for each language.

**Comment by innovationsbg** [comment]
This fix the problem: [https://stackoverflow.com/questions/48342466/loop-through-attributes-in-the-custom-validation-method/48343633#48343633](https://stackoverflow.com/questions/48342466/loop-through-attributes-in-the-custom-validation-method/48343633#48343633)

**Comment by meinac** [comment]
The problem is in the `AutosaveAssociation` module. It does not validate the child records while automatically saving them.

**Comment by SeinopSys** [comment]
I ran into the same issue. Nested attributes' length and presence is validated, but uniqueness is ignored.
