### ISSUE TITLE
Rails generate migration can generate numerically lower timestamp

### ISSUE THREAD

**Issue by niko-pax-uofa** [rails/rails#31722]
### Steps to reproduce
<pre>
$ rails new test_app
$ cd test_app
$ rails generate migration first_migration
Running via Spring preloader in process 65119
      invoke  active_record
      create    db/migrate/20180117071603_first_migration.rb
$ mv db/migrate/20180117071603_first_migration.rb db/migrate/2017141707160301_first_migration.rb
$ rails generate migration second_migration
Running via Spring preloader in process 65128
      invoke  active_record
      create    db/migrate/20180117071645_second_migration.rb
$ ls db/migrate/ | sort -n
20180117071645_second_migration.rb
2017141707160301_first_migration.rb
$ mv db/migrate/20180117071645_second_migration.rb db/migrate/2018141707164501_second_migration.rb
$ rails generate migration third_migration
Running via Spring preloader in process 65141
      invoke  active_record
      create    db/migrate/2018141707164502_third_migration.rb
$ ls db/migrate/ | sort -n
2017141707160301_first_migration.rb
2018141707164501_second_migration.rb
2018141707164502_third_migration.rb
</pre>
### Expected behavior
migration should be listed(and executed by `rails db:migrate`) in the order they were created.

### Actual behavior
migrations are listed (and executed by `rails db:migrate`) in wrong order.
This appears to happen after a year boundary(2017/2018)

### System configuration
**Rails version**: 5.1.4

**Ruby version**: ruby 2.4.2p198 (2017-09-14 revision 59899) [x86_64-darwin15]

**Comment by sikachu** [comment]
> $ mv db/migrate/20180117062308_first_migration.rb db/migrate/20170117062308**01**_first_migration.rb

Is there a reason why `01` was added in your test case? That's the reason why `sort -n` doesn't work as expected though:

```
$ echo "2017011706230801 \n20180117062351" | sort 
2017011706230801 
20180117062351

$ echo "2017011706230801 \n20180117062351" | sort -n
20180117062351
2017011706230801 
```

I feel like if we change the sort order it will break other people's app that rely* the behavior to be this way, so I would love to hear your intention of suffixing it with `01` first.

Thank you!

**Comment by niko-pax-uofa** [comment]
Hi!
I've updated the steps to reproduce to highlight the issue.
If migrations were created with a non-timestamp series last year(2017) and I run a migration this year, it reverts to a timestamp. but if i make the last migration start with 2018 it does not do this.
moreover the switch causes lower numeric migrations which will run _before_ previous migrations. 
So i have a situation like this in one of my projects:
<pre>
20170710032739_create_assignments.rb
2017210712051234_create_questions.rb
2017210712051235_rename_table_assignments_to_jobs.rb
..
2017210712051256_add_predefined_question.rb
20180115211941_change_question_text_to_text.rb
20180117051458_create_job_users.rb
</pre>
which means 20180115211941_change_question_text_to_text and 20180117051458_create_job_users try to run _before_ 2017210712051234_create_questions.rb

**Comment by matthewd** [comment]
It's generally expected that if you have the `timestamped_migrations` option turned on, you're using timestamps to order your migrations. If you just always want N+1, you can turn that option off. (Though if you're going to use sequential numbers, and give up the branch-merge benefits of timestamps, I'd personally go for a slightly smaller starting number.)

However, I agree this should probably be using a numeric comparison:

https://github.com/rails/rails/blob/6783bcab7ab11f2ced4b711d3518422e35e3dc01/activerecord/lib/active_record/migration.rb#L935

Want to open a PR?

**Comment by niko-pax-uofa** [comment]
Yeah I'll open a PR. Just have to do some reading about how open a PR right!
