### ISSUE TITLE
ActiveStorage client-side encryption

### ISSUE THREAD

**Issue by phildionne** [rails/rails#31729]
I'd like to do direct uploads to AWS S3 with client-side encryption so that data is already encrypted when being sent over the wire.

- Is this feature on the roadmap for ActiveStorage?
- Does that sound like a good idea?

**Comment by sgrif** [comment]
We reserve the Rails issue tracker only for bugs in Rails. We don't accept feature requests on the issue tracker. Please ask on the [Rails core mailing list](https://groups.google.com/forum/#!forum/rubyonrails-core)
