### ISSUE TITLE
Railties Generator produces error on rails engine 5.1.x

### ISSUE THREAD

**Issue by tzabaman** [rails/rails#31737]
### Steps to reproduce

**Notice:** The example that I am describing below is not producing the error itself, but consider it as the general idea.

Now, think of the following stack:

- A rails **engine**, named e.g. "core" which contains all logic. Models, controllers e.t.c, all live there.
- A rails **application** which is (almost) empty, it has no written logic. It is used as a container in order to load the "core" engine. Even its Gemfile is (almost) empty, it just defines the "core" gem.

Now, inside the main rails **application** we want to create a custom configuration `.yml` file which will holds some application-wide settings that will be shared amongst the "core" engine/gem and any other engines/gems that will be added in the future. So inside our `testapp/config/application.rb` file we define the custom configuration by writing:

```
module Testapp
  class Application < Rails::Application
    ...
    config.custom_conf = config_for(:custom_conf)
    ...
  end
end
```
Finally we create the desired `.yml` file, e.g. `testapp/config/custom_conf.yml`

Now we want to use this custom configuration inside our "core" engine, and specifically inside an initializer that we have created. So inside `core/config/initializer/apartment.rb` we write:

```
Rails.configuration.custom_conf["custom_title"]
```

That's all! So now let's scaffold a new "User" model **inside the "core" engine** by typing to the terminal:

`bin/rails g model User`

### Expected behavior
On rails 5.0.x everything is fine, the generator creates the expected files (migration, model, test, fixture)

### Actual behavior
On rails 5.1.x we are getting the following error:

> /.../ruby-2.4.0/gems/railties-5.1.4/lib/rails/railtie/configuration.rb:95:in 'method_missing': undefined method 'custom_conf' for #<Rails::Application::Configuration:0x000000021139e

As we can see from the stack trace printed on the console, when calling the generator, the "core" engine will get initialized via the `core/test/dummy` rails application and as a result the code of the engine will be executed without prior some parts of our code be defined (e.g. the custom configuration). This change introduced in rails 5.1.

So my question is if there is a configuration in order to overlap this error. I noticed the constant

`APP_PATH    = File.expand_path('../../test/dummy/config/application', __FILE__)` 

which is defined inside `core/bin/rails` file. If I change it to point the main rails application in an external folder the generator works properly. But is this the right practice or other unexpected errors may occur??

Any thoughts???

### System configuration
**Rails version**: 5.1.4

**Ruby version**: 2.4.0

**Comment by rafaelfranca** [comment]
You can't develop you engine based in configuration of the app that is going to be mounted. Engine were made to be isolated from the main app so they can't know anything about the main app. If you want to do that (which is not recommended) the `APP_PATH` constant is the right value to change.

**Comment by tzabaman** [comment]
@rafaelfranca I am reporting this, because using configuration from the main application into the engine was not a problem until version 5.0.6. 

But configuration is just an example I provided. There may be other parts between an engine and the app that may be interacting so:

>  Engine were made to be isolated from the main app so they can't know anything about the main app

is not 100% accurate as described inside [http://guides.rubyonrails.org/engines.html](url) at section 4.3

Anyway thanks for your answer!
