### ISSUE TITLE
windows, rails test   displays loads of lines regarding a reporter/minitest, after displaying the error it should show

### ISSUE THREAD

**Issue by gartha1** [rails/rails#31731]
in win7.

C:\blah11>rails -v
Rails 5.1.4

C:\blah11>ruby -v
ruby 2.4.2p198 (2017-09-14 revision 59899) [x64-mingw32]

C:\blah11>

C:\rubytest\hartl\ch4>rails new blah11 >nul

C:\rubytest\hartl\ch4>cd blah11

C:\blah11>rails generate controller abc def >nul

C:\blah11>rails test
Run options: --seed 57228

# Running:

.

Finished in 0.581000s, 1.7212 runs/s, 1.7212 assertions/s.
1 runs, 1 assertions, 0 failures, 0 errors, 0 skips

C:\blah11>

C:\blah11>wordpad.exe test\controllers\abc_controller_test.rb

C:\blah11>type test\controllers\abc_controller_test.rb
require 'test_helper'

class AbcControllerTest < ActionDispatch::IntegrationTest
  test "should get def" do
    get abc_def_url
    assertttt_response :success
  end

end

Rails test now will show the error but after it shows the error it displays lots of junk errors.

C:\blah11>rails test
Run options: --seed 59902

# Running:

E

Error:
AbcControllerTest#test_should_get_def:
NoMethodError: undefined method `assertttt_response' for #<AbcControllerTest:0x00000000052d9c18>
Did you mean?  assert_response
    test/controllers/abc_controller_test.rb:6:in `block in <class:AbcControllerTest>'

C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/railties-5.1.4/lib/rails/test_unit/reporter.rb:70:in `method': undefined method `test_should_get_def' for class `Minitest::Result' (NameError)
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/railties-5.1.4/lib/rails/test_unit/reporter.rb:70:in `format_rerun_snippet'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/railties-5.1.4/lib/rails/test_unit/reporter.rb:23:in `record'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/minitest-5.11.1/lib/minitest.rb:786:in `block in record'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/minitest-5.11.1/lib/minitest.rb:785:in `each'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/minitest-5.11.1/lib/minitest.rb:785:in `record'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/minitest-5.11.1/lib/minitest.rb:334:in `run_one_method'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/minitest-5.11.1/lib/minitest.rb:321:in `block (2 levels) in run'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/minitest-5.11.1/lib/minitest.rb:320:in `each'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/minitest-5.11.1/lib/minitest.rb:320:in `block in run'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/minitest-5.11.1/lib/minitest.rb:360:in `on_signal'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/minitest-5.11.1/lib/minitest.rb:347:in `with_info_handler'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/minitest-5.11.1/lib/minitest.rb:319:in `run'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/railties-5.1.4/lib/rails/test_unit/line_filtering.rb:9:in `run'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/minitest-5.11.1/lib/minitest.rb:159:in `block in __run'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/minitest-5.11.1/lib/minitest.rb:159:in `map'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/minitest-5.11.1/lib/minitest.rb:159:in `__run'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/minitest-5.11.1/lib/minitest.rb:136:in `run'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/minitest-5.11.1/lib/minitest.rb:63:in `block in autorun'

**Comment by y-yagi** [comment]
Thanks for creating an issue. This issue already fixed with #31624.  
This issue will occur with using Minitest 5.11.
Please lock Minitest version until released next version of Rails.
