### ISSUE TITLE
size method with counter_cache collection is still broken in rails 5.0.6

### ISSUE THREAD

**Issue by Rudiney** [rails/rails#31735]
Looks like a `.size` method of a **Post** model which has_many **Comments** using a counter cache is still broken in Rails 5.0.6. 

I follow up [this issue](https://github.com/rails/rails/issues/28579) to #26940 but im still getting the same exception.

### Steps to reproduce

```ruby
ActiveRecord::Schema.define do
  create_table :posts, force: true do |t|
    t.integer :comments_count
  end

  create_table :comments, force: true do |t|
    t.integer :post_id
  end
end

class Post < ActiveRecord::Base
  has_many :comments
end

class Comment < ActiveRecord::Base
  belongs_to :post, counter_cache: true
end

post = Post.create!
post.comments.size #BOOM!
```

[Here is test cases reproducing the exception following the template](https://gist.github.com/Rudiney/9e8ee79135fc518413b6c4fa062d0fe8)

### Expected behavior
`post.size` should return `0`

### Actual behavior
`TypeError: nil can't be coerced into Integer` exception is thrown 

### System configuration
**Rails version**: 5.0.6
**Ruby version**: tested on both 2.4.1 and 2.5.0

**Comment by joshmn** [comment]
With the test case you submitted, adding a default of 0 to the comments_count column does solve the problem. Maybe the question is, should ActiveRecord assume that nil is 0 for a counter_cache_column?

**Comment by eugeneius** [comment]
This works correctly in Rails 5.1; https://github.com/rails/rails/pull/26940 was merged, but it wasn't backported.

At this point Rails 5.0 is only supported for security issues, so it's unlikely this will be fixed.

**Comment by Rudiney** [comment]
Thanks @joshmn and @eugeneius! 

Im holding to the *default to 0* strategy until i upgrade my Rails version to 5.1
