### ISSUE TITLE
resources typo in code-snippet in the getting-started-guide to rails

### ISSUE THREAD

**Issue by tanvibhakta** [rails/rails#31734]
### Steps to reproduce

The issue is a typo (a missing s) in the highlighted section below, which is found in section 5.2 at this link: http://guides.rubyonrails.org/getting_started.html
![screen shot 2018-01-18 at 5 05 55 pm](https://user-images.githubusercontent.com/13763558/35096390-04a39eac-fc72-11e7-84de-28ceb98cfd4a.png)

### Expected behavior
The entire code snippet is supposed to lead to the error mentioned in the next steps. Instead...

### Actual behavior
This error is found: No route matches [POST] "/articles/new"
This error is further documented here: https://stackoverflow.com/questions/23864868/no-route-matches-post-articles-new

### System configuration
**Rails version**:
Rails 5.1.4

**Ruby version**:
ruby 2.4.1p111 (2017-03-22 revision 58053) [x86_64-darwin17]

**Comment by y-yagi** [comment]
`scope: :article` is correct in this form. 
Maybe you missed adding `url: articles_path`, that described in the section. 
Please check `5.2 The first form` whole. Thanks.
