### ISSUE TITLE
 Rails 5.2.0.beta2 sockjs error: "Refused to connect to 'http://localhost:3035/sockjs-node/info ..." 

### ISSUE THREAD

**Issue by shmay** [rails/rails#31754]
### Steps to reproduce
Using Ruby 2.5.0 and Rails 5.2.0.beta2, generate a new Rails app via:

`rails new myapp --webpack=react`

Then do:

*  `bin/rails g controller home`  & add an index method in that controller
*  `root 'home#index'` in config/routes.rb
*  `<%= javascript_pack_tag 'application' %>` in application.html.erb
*  `bin/rails s` & `bin/webpack-dev-server` in sep tabs.

Then go to localhost:3000 and see the following error in the js console: 
```
sockjs.js:1601 Refused to connect to 'http://localhost:3035/sockjs-node/info?t=1516563963136' because it violates the following Content Security Policy directive: "default-src 'self' https:". Note that 'connect-src' was not explicitly set, so 'default-src' is used as a fallback.
```
![sockjs](https://user-images.githubusercontent.com/74591/35198289-f8a0be7c-feb1-11e7-8fc5-3552e77246dd.jpg)

In the meantime, changing `inline: true` to `inline: false` in config/webpacker.yml got rid of the error.  But not sure if that's just a hack.

### System configuration
**Ruby version**: 2.5.0

**Rails version**:  5.2.0.beta2

Thank you for any help!

**Comment by savroff** [comment]
Hi @shmay,
You just need to setup your content security policy:
`app/config/initializers/content_security_policy.rb`

I suggest you to update it like this:

```ruby
Rails.application.config.content_security_policy do |p|
  p.font_src    :self, :https, :data
  p.img_src     :self, :https, :data
  p.object_src  :none
  p.style_src   :self, :https, :unsafe_inline

  if Rails.env.development?
    p.script_src :self, :https, :unsafe_eval
    p.default_src :self, :https, :unsafe_eval
    p.connect_src :self, :https, 'http://localhost:3035', 'ws://localhost:3035'
  else
    p.script_src :self, :https
    p.default_src :self, :https
  end
end
```

This case you can use unsafe scripts and use Webpack reload functions in Development mode.

**Comment by shmay** [comment]
Thank you @savroff.  That solved it.  Missed that note about Rails 5.2 in the docs.  I agree that it should "just work" out of the box, and perhaps the docs made more clear.

**Comment by y-yagi** [comment]
This is issue of webpacker. Please create an issue to [webpacker's issue](https://github.com/rails/webpacker/issues). Thanks.
