### ISSUE TITLE
Active record: Add order option to "find_in_batches" and "find_each"

### ISSUE THREAD

**Issue by y-mitsuyoshi** [rails/rails#31759]
Add order option to "find_in_batches" and "find_each"

Currently, if "primary_key" does not exist, "find_in_batches" and "find_each" will result in an error.
Since there may be cases where "primary_key" does not exist when performing batch processing,
I think that it can be solved by adding an order option.

**Comment by georgeclaghorn** [comment]
Thanks, but we don’t take feature requests in the issue tracker. Feel free to open a PR or seek feedback in the [rubyonrails-core](https://groups.google.com/forum/#!forum/rubyonrails-core) mailing list.
