### ISSUE TITLE
In ActiveJob, how to rescue_from in a base class?

### ISSUE THREAD

**Issue by steveburkett** [rails/rails#31764]
This works (catching a deserialization error) in my ActiveJob

```
class MyJob < ActiveJob::Base
    rescue_from(StandardError) do |ex|
      App::ErrorNotifier.new(ex: ex).notify
      raise ex
    end

    rescue_from(ActiveJob::DeserializationError) do |ex|        #this is hit first. good. 
      App::ErrorNotifier.new(ex: ex).notify
      if ex.cause == ActiveRecord::ConnectionTimeoutError
        raise
      end
    end
   ...
```

However...what if i want to put the rescue_from(ActiveJob::DeserializationError)  into a base class i can use in all my AJs?  I tried this: 

```
class MyJob < ApplicationJob
    rescue_from(StandardError) do |ex|
      App::ErrorNotifier.new(ex: ex).notify
      raise ex
    end
   ...

class ApplicationJob < ActiveJob::Base
    rescue_from(ActiveJob::DeserializationError) do |ex|    #i want this to be hit first
      App::ErrorNotifier.new(ex: ex).notify
      if ex.cause == ActiveRecord::ConnectionTimeoutError
        raise
      end
    end
```

But when the job raises a DeserializationError, it's always caught in the top level class, in the StandardError rescue_from.   I do see that it's because the rescue_from(SE) is called last here:

``` 
 # put the new handler at the end because the list is read in reverse
       self.rescue_handlers += [[key, options[:with]]]
```

My question is how do i do this correctly?  How can i get the rescue_from(ActiveJob::DeserializationError) to be handled generically for all my AJs (before other exceptions are handled)?

**Comment by rafaelfranca** [comment]
Please use StackOverflow for questions/help, where a wider community will be able to help you. We reserve the issues tracker for issues only.
