### ISSUE TITLE
PG::ConnectionBad on activejob(resque adapter) after upgrading to rails 5.2.0.beta2

### ISSUE THREAD

**Issue by bituinb** [rails/rails#31766]
### Expected behavior
Tell us what should happen
All jobs fails with PG::ConnectionBad  exception

### Actual behavior
Job fails with exception : 
    PG::ConnectionBad (connection is closed)

### System configuration
**Rails version**:  Rails 5.2.0.beta2
**Ruby version**: ruby 2.4.3p205
**Pg gem version**: pg-0.21.0
**Resque config**:  'config/resque.rb'

> require "redis"
> Resque.before_fork = Proc.new do |job|
>    ActiveRecord::Base.connection.disconnect!
> end

>Resque.after_fork = Proc.new do |job|
>    ActiveRecord::Base.establish_connection
>end

**Comment by matthewd** [comment]
Thanks for the report!

Could you create a new demo application that shows the problem?

**Comment by bituinb** [comment]
Please see demo application

https://github.com/bituinb/xyz 

My local dev is using Postgres 9.5.2 and mac OSX 10.9.5

Instruction is in readme

Thank you

**Comment by matthewd** [comment]
Perfect, thank you. :heart:

This was a bug in #31173; fixed in 1280ad6d19fa56e9bf6d6a261c1231326cb3d8c3.

FYI, you don't actually need those before/after fork blocks any more -- that's what that PR does -- but they certainly shouldn't break your application 😅, so this was a good catch.
