### ISSUE TITLE
Rails Installer link broken on getting started section of ruby on rails website.

### ISSUE THREAD

**Issue by MorganMarshall** [rails/rails#31772]

**Comment by joshmn** [comment]
Assuming you're referring to http://railsinstaller.org/ — that's not owned or managed by the Rails team. 

This can probably be closed.

**Comment by y-yagi** [comment]
Thanks for an issue. @joshmn is correct.  Rails installer is not managed by the Rails team.  
Seems issue was already created in Rails Installer 's repo.  https://github.com/railsinstaller/website/issues/59
Let's check that.
