### ISSUE TITLE
ActiveRecord::Enum #defined_enums uses string as hash key??

### ISSUE THREAD

**Issue by KDGundermann** [rails/rails#31775]
### Steps to reproduce
in the documentation there is always a symbol as the name of an enum
```
class Conversation < ActiveRecord::Base
  enum status: [ :active, :archived ]
end
```
and in the code activerecord/lib/active_record/enum.rb#157 its forced to be a symbol
```
name        = name.to_sym
```
but later forced to a string key for the hash:
```
defined_enums[name.to_s] = enum_values
```
### Expected behavior
```
Conversation.defined_enums.include?(:status)
=> true 
```
### Actual behavior
```
Conversation.defined_enums.include?(:status)
=> false
Conversation.defined_enums.include?("status")
=> true 
```
### System configuration
**Rails version**: 4.2.8
**Ruby version**: 2.3.3p222

**Comment by rafaelfranca** [comment]
`defined_enums` is private API of the framework and should not be used in applications. We chose to only store strings keys there to have an unified API (only checking for string keys not symbol and strings keys)/

**Comment by thelucid** [comment]
Could this method be made public? Or maybe if I add a `reflect_on_enum` method, is this likely to be accepted?

**Comment by sergiopantoja** [comment]
Working on something today that brought me to this thread. I'm also in favor of `defined_enums` becoming public, or a `reflect_on_enum` method. @thelucid do you still have any interest in making a PR for this? I can pick it up if not.

**Comment by thelucid** [comment]
Feel free to have a crack, I’m not sure I’ll be able to get to it in the near future.
