### ISSUE TITLE
Postgresql query with includes, order, limit fails with PG::InvalidColumnReference

### ISSUE THREAD

**Issue by charlesvallieres** [rails/rails#31774]
Postgresql expects ORDER BY expressions to appear in SELECT when using DISTINCT.

### Steps to reproduce

_Might need to change ActiveRecord::Base.establish_connection parameters_

```
# frozen_string_literal: true

begin
  require "bundler/inline"
rescue LoadError => e
  $stderr.puts "Bundler version 1.10 or later is required. Please update your Bundler"
  raise e
end

gemfile(true) do
  source "https://rubygems.org"

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  gem "rails", github: "rails/rails"
  gem "pg"
end

require "active_record"
require "minitest/autorun"
require "logger"

# This connection will do for database-independent bug reports.
ActiveRecord::Base.establish_connection(
  adapter: "postgresql",
  username: "postgres",
  password: "",
  database: "postgres"
)
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :posts, force: true do |t|
    t.integer :author_id
  end

  create_table :authors, force: true do |t|
    t.string :full_name
  end
end

class Post < ActiveRecord::Base
  belongs_to :author
end

class Author < ActiveRecord::Base
  has_many :posts
end

class BugTest < Minitest::Test
  def test_includes_order_count
    author = Author.create!(full_name: "Foo Bar")
    Post.create!(author: author)

    Post.includes(:author).order("authors.full_name").limit(10).count
  end

  def test_each_slice
    Post.includes(:author).order("authors.full_name").each_slice(3) do |slice|
      # Do something with slice
    end
  end
end
```

### Expected behavior
It should count the results without failing.

### Actual behavior
```
ActiveRecord::StatementInvalid: PG::InvalidColumnReference: ERROR:  for SELECT DISTINCT, ORDER BY expressions must appear in select list
```

### System configuration
**Rails version**: Tested on 5.1.4 and 5.2.0.beta2

**Ruby version**: ruby 2.4.0p0 (2016-12-24 revision 57164) [x86_64-darwin16]

### Related commits
https://github.com/rails/rails/commit/a265d4b29cf9c1be84603ec53a6f8b17b53321a9
https://github.com/rails/rails/commit/c6cd9a59f200863ccfe8ad1d9c5a8876c39b9c5c

### Possible solution (untested)
Use DISTINCT ON the first order column when `column_name` is `:all`, `distinct` is `true` and there is at least one order value.

https://www.postgresql.org/docs/9.5/static/sql-select.html
> SELECT DISTINCT eliminates duplicate rows from the result.
> SELECT DISTINCT ON eliminates rows that match on all the specified expressions.
> SELECT ALL (the default) will return all candidate rows, including duplicates.

Maybe there is a more efficient way to do this and I am not sure about the implications of `distinct_on` on non-postgresql database.

Change
https://github.com/rails/rails/blob/master/activerecord/lib/active_record/relation/calculations.rb#L393

For something like
```
  def build_count_subquery(relation, column_name, distinct)
    if column_name == :all
      relation.select_values = [ Arel.sql(FinderMethods::ONE_AS_ONE) ] unless distinct
    else
      column_alias = Arel.sql("count_column")
      relation.select_values = [ aggregate_column(column_name).as(column_alias) ]
    end

    ar_relation = relation.arel

    if column_name == :all && distinct && order_values.any?
      ar_relation = ar_relation.distinct_on(Arel.sql(order_values.first))
    end

    subquery = ar_relation.as(Arel.sql("subquery_for_count"))
    select_value = operation_over_aggregate_column(column_alias || Arel.star, "count", false)

    Arel::SelectManager.new(subquery).project(select_value)
  end
```

**Comment by sgrif** [comment]
I don't think that we should make `order` implicitly change the behavior of `distinct`. It's up to you to make sure your query is actually valid. You can create a `DISTINCT ON` clause by passing a SQL string to `select`.

**Comment by charlesvallieres** [comment]
@sgrif Aight, I thought it was more of supporting Postgresql correctly for common operations (see second test).

Thanks for you answer
