### ISSUE TITLE
ActiveStorage not inserting record into active_storage_attachments

### ISSUE THREAD

**Issue by legacy370** [rails/rails#31776]
### Steps to reproduce
As of yesterday, 1/22/2018, I had a small demo application working with the activestorage, properly uploading files to S3, and able to display links to those files.

 Today, after making no changes whatsoever other than bundle:update, the application has stopped working.

(Guidelines for creating a bug report are [available
here](http://guides.rubyonrails.org/contributing_to_ruby_on_rails.html#creating-a-bug-report))

### Expected behavior
Upon attaching data to a model, there should be a record inserted into active_storage_attachments, and a record inserted into active_storage_blobs.

### Actual behavior
A record gets inserted into active_storage_blobs, but **nothing gets inserted into active_storage_attachments**.  Hence when doing a Show, the system cannot find the attached data.  

### System configuration
Rails 5.2.0.beta2  .  ruby 2.3.1p112 (2016-04-26 revision 54768) [x86_64-linux]

[ActiveStorageFailure.txt](https://github.com/rails/rails/files/1658051/ActiveStorageFailure.txt)

**Comment by georgeclaghorn** [comment]
Can you share your demo application, or another minimal application that reproduces the issue?

**Comment by composerinteralia** [comment]
One thing to keep in mind is that `bundle update` updates all of your dependencies. Any updates to the major version of a gem is likely to have breaking changes. Checkout out your Gemfile.lock before and after running `bundle update` to see exactly what was changed.

**Comment by iwaffles** [comment]
@legacy370 I ran into this same issue today. I solved it by adding this to my controller wherever I save the parent object (such a a `Post`) with `images` as the attachment name. This wasn't super obvious, but after some experimenting it solved my issue.

`@post.images.attach(params[:post][:images])`

Hope that helps!
