### ISSUE TITLE
Camelize returning wrong string for UPPERCASE_STRING

### ISSUE THREAD

**Issue by CoryMcDonald** [rails/rails#31785]
### Steps to reproduce
I think this is a bug but I'm not 100% sure if it is. I was certainly surprised by this behavior.

### Expected behavior
I would expect the result to be something similar to this

| original string | function | expected string |
| ------------- | ----------| -----------------|
| TEST_CASE_HERE | `camelize` | TestCaseHere |
| TEST_CASE_HERE | `camelize(:lower)` | testCaseHere|

### Actual behavior

```ruby
"TEST_CASE_HERE".camelize
=> "TESTCaseHere"
"TEST_CASE_HERE".camelize(:lower)
=> "tESTCaseHere"
```

### System configuration
**Rails version**:
`5.1.4`
**Ruby version**:
`2.4.1`

**Comment by rafaelfranca** [comment]
Thank you for the report. It is not a bug. camelize expects the string to be lowercase and with `_`. Like the documentation points. `camelize` is the inverse of `underscore`. And `"TestCaseHere".underscore` is `"test_case_here"`.

**Comment by CoryMcDonald** [comment]
Hey there @rafaelfranca, I appreciate the quick response. I think the docs might be out of date because the SSL example they give makes it seem like it would behave like I've listed

>As a rule of thumb you can think of camelize as the inverse of underscore, though there are cases where that does not hold: "SSLError".underscore.camelize gives back "SslError". To support cases such as this, Active Support allows you to specify acronyms in config/initializers/inflections.rb:

http://guides.rubyonrails.org/active_support_core_extensions.html#camelize

**Comment by rafaelfranca** [comment]
It only behaves like you think in that case because you are calling `underscore` in in `SSLError` and that returns `ssl_error` And `ssl_error` is downcased. `"TEST_CASE_HERE".underscore.camelize` will return what you want, but it doesn't means that `"TEST_CASE_HERE".camelize` should to.

**Comment by CoryMcDonald** [comment]
Ah, okay, that's right. 👍 

Thanks for all your help.
