### ISSUE TITLE
Fixtures for models referencing nested models attempts to create instances of the wrong model

### ISSUE THREAD

**Issue by jrmhaig** [rails/rails#31782]
I do not know if this is a bug or a misunderstanding on my part. I apologise if it is the latter but would appreciate a pointer in the right direction.

### Steps to reproduce

Create two models where one references the other and the latter is a subclass of the first (pluralized):

```
rails g model Outers::Inner name:string
rails g model Outer outer_inner:references
# Change app/model/outer.rb to include:
#    belongs_to :outers_inner, class_name: 'Outers::Inner'
rails db:migrate
```

Change the name of one of the automatically generated fixtures. Eg, in `test/fixtures/outers.yml`:

```yaml
# one: # old
three: # new
  outers_inner: one
```

Run `rails db:fixtures:load`.

### Expected behavior

The fixtures are generated as they are defined in the fixtures files.

Note that this works correctly if the fixture files have not been changed from the templates and the resultant models can be used correctly.

### Actual behavior

```bash
$ rails db:fixtures:load
rails aborted!
ActiveRecord::Fixture::FixtureError: table "outers" has no column named "name".
/.../bin/rails:9:in `require'
/.../minitest_test/bin/rails:9:in `<top (required)>'
/.../minitest_test/bin/spring:15:in `<top (required)>'
bin/rails:3:in `load'
bin/rails:3:in `<main>'
Tasks: TOP => db:fixtures:load
(See full trace by running task with --trace)
```

When it encounters the line in the fixtures file `outers_inner: one` it appears to be trying to create an instance of the `Outer` model with the details for the `Outers::Inner` fixture. If, however, there is an `Outer` fixture with the same name there is no problem.

### System configuration
**Rails version**: 5.1.4

**Ruby version**: 2.5.0 (also 2.4.1p111)

**Comment by y-yagi** [comment]
Fixture loads files in subdirectories with the same name as the fixture name. 
In this case, files under the `fixtures/outers` are regarded as the fixture of `Outer` model. This is intentional behavior. 

As a workaround, you can fix by changing fixture name of `Outers::Inner` model from `outers/inners.yml` to `outers_inners.yml`.

```yml 
# test/fixtures/outers_inners.yml
_fixture:
  model_class: Outers::Inner

one:
  name: MyString
```  

By specifying `model_class`, the fixture will be recognized even if file name changes.

**Comment by jrmhaig** [comment]
Thanks, @y-yagi, that looks like exactly what I need.

I didn't realise that fixtures could be defined in subdirectories but with a large number I can see that that makes perfect sense.

**Comment by y-yagi** [comment]
Thanks for your confirmation. I close this because it is intentional behavior. 
If you have that there is a better approach, please feel free to make a PR. Thanks!
