### ISSUE TITLE
Bundle erro

### ISSUE THREAD

**Issue by kaline** [rails/rails#31790]
![2018-01-25--1516896933_1366x768_scrot](https://user-images.githubusercontent.com/31135896/35399960-59f92630-01d4-11e8-9f8f-8957af00674b.png)

**Comment by rafaelfranca** [comment]
Can you please provide a sample application that reproduces the error?

**Comment by composerinteralia** [comment]
This looks like a problem with the way your development environment is set up, rather than an issue with rails. Your best bet is to search or post on StackOverflow, where lots of people are ready to help with this sort of problem. 😸
