### ISSUE TITLE
Rails autoloading cannot load constant when folder name is same as class name 

### ISSUE THREAD

**Issue by RallySahil** [rails/rails#31793]
### Steps to reproduce
1. Inside lib folder make a folder `test`
2. Inside test folder make a class `test.rb` that includes `a.rb` module
3. Inside test folder make a module `a.rb`

### Expected behavior
It should autoload since the lib directory and its subdirectories are in auto load paths correctly.

### Actual behavior

Error  `load_missing_constant': Unable to autoload constant Test::A`

This happens because class name `test` is same as folder name `test`. When I changed folder name from test to something else, it worked fine.

### System configuration
**Rails version**:
Rails 4.2.8
**Ruby version**:
ruby 2.3.4p301 (2017-03-30 revision 58214) [x86_64-darwin16]

**Comment by rafaelfranca** [comment]
`test.rb` should be inside `lib` (the root of the autoload directory)` not under `test`. If you put under test you class or module needs to be called `Test::Test`.
