### ISSUE TITLE
Destroying record multiple times repeatedly runs callbacks

### ISSUE THREAD

**Issue by fatkodima** [rails/rails#31801]
### Steps to reproduce

Just simply destroy any record multiple times.
```ruby
class User < ActiveRecord::Base
  ...
  after_destroy do
    puts "User#after_destroy"
  end
end

>> u = User.create
>>
>> u.destroy
   (0.1ms)  begin transaction
  ReadMark Destroy (0.1ms)  DELETE FROM "read_marks" WHERE "read_marks"."reader_id" = ? AND "read_marks"."reader_type" = ?  [["reader_id", 7], ["reader_type", "User"]]
  User Destroy (0.2ms)  DELETE FROM "users" WHERE "users"."id" = ?  [["id", 7]]
User#after_destroy
   (1.6ms)  commit transaction
=> #<User id: 7, name: nil, email: nil, created_at: "2018-01-26 10:23:39", updated_at: "2018-01-26 10:23:39">
>>
>> u.destroy
   (0.1ms)  begin transaction
  ReadMark Destroy (0.2ms)  DELETE FROM "read_marks" WHERE "read_marks"."reader_id" = ? AND "read_marks"."reader_type" = ?  [["reader_id", 7], ["reader_type", "User"]]
User#after_destroy
   (0.1ms)  commit transaction
=> #<User id: 7, name: nil, email: nil, created_at: "2018-01-26 10:23:39", updated_at: "2018-01-26 10:23:39">
```

### Expected behavior
After first `.destroy`, next calls should be no-ops -  callbacks should not be called, queries for destroying associations should not be fired. Is this intended behavior? Looks a bit counter-intuitive. Callbacks will have dangerous actions, assuming that record is deleted only once. And no need to perform needless db queries again.

### Actual behavior
Callbacks are called, queries for destroying associations fired multiple times.

### System configuration
**Rails version**: master

If this sounds reasonable, will submit a PR.

**Comment by rafaelfranca** [comment]
Yeah, it sounds reasonable to me. I'd just raise an exception if the record is already destroyed, silently doing nothing seems wrong to me.

**Comment by fatkodima** [comment]
> I'd just raise an exception if the record is already destroyed

Makes sense. I'm preparing a PR.
