### ISSUE TITLE
Testing an ActionController::Live controller leads to a deadlock

### ISSUE THREAD

**Issue by Kjir** [rails/rails#31813]
This is a deeper and more correct report of #31200 after some deep investigation of the issue.

### Steps to reproduce
In a new rails application generate a controller and implement it like follows:
```
rails new stream_test
cd stream_test
bin/rails g controller Home index
```

```ruby
class HomeController < ApplicationController
  include ActionController::Live

  def index
    11.times { response.stream.write('a') }
    ensure
      response.stream.close
  end
end
```
Then run the controller test
```
bin/rails test
```
### Expected behavior
The test should succeed

### Actual behavior
The test will just hang forever. This is because under the hood when streaming responses with `ActionController::Live` we are adding the responses to a `SizedQueue` with size `10`. In a real context, the browser will consume the data as soon as it is generated thus freeing space in the queue; in a rack test context, however, we are expecting the whole response to be returned without actually consuming it as it is processed. So if the test includes more than `10` writes on the stream, the tests will hang forever.

I can see three possible solutions:
 * Disable streaming in test environments
 * Substitute the `SizedQueue` with an infinite `Queue` in test environments
 * Consume the response in async.

The third option is arguably the best solution, but it is also the most complex one. I'm also not sure where it should be implemented, it could require changes in the `rack-test` gem.

Any other thoughts?

### System configuration
**Rails version**:
Lastest master (Rails 5.2.0.beta2) at the time of writing. Commit: `a88eb9087260cca256c6faba40bf538d4a0289b3`
**Ruby version**:
ruby 2.4.2p198 (2017-09-14 revision 59899) [x86_64-darwin16]

**Comment by zzak** [comment]
Fixed by #41609
