### ISSUE TITLE
sql_type error

### ISSUE THREAD

**Issue by MrQile** [rails/rails#31824]
# An external mysql database has been connected.
# My schema.rb after running rails db:schema:dump 

 This file is auto-generated from the current state of the database. Instead of editing this file, please use the migrations feature of Active Record to incrementally modify your database, and then regenerate this schema definition. Note that this schema.rb definition is the authoritative source for your database schema. If you need to create the application database on another system, you should be using db:schema:load, not running all the migrations from scratch. The latter is a flawed and unsustainable approach (the more migrations you'll amass, the slower it'll run and the greater likelihood for issues).
 It's strongly recommended that you check this file into your version control system.

ActiveRecord::Schema.define(version: 0) do

   Could not dump table "employees" because of following NoMethodError 
     undefined method `sql_type' for "int(11)":String

end

OR

ActiveRecord::Schema.define(version: 0) do

   Could not dump table "employees" because of following NoMethodError 
     undefined method `type' for "varchar(20)":String

end

**Comment by composerinteralia** [comment]
I am not totally sure what you are asking here. Can you clarify what the problem is and include some instructions for how to reproduce it? A sample app that demonstrates the bug would be most helpful.

**Comment by MrQile** [comment]
I am trying to connect to an existing mysql. have configured the database.yml accordingly-
development:
  adapter: mysql2
  encoding: utf8
  pool: 5
  host: localhost
  username: Ruby
  password: ****
  port: 3306
  socket: /var/lib/mysql/mysql.sock
  database: rubyappdb

test:
  adapter: mysql2
  encoding: utf8
  pool: 5
  host: localhost
  username: Ruby
  password: ****
  port: 3306
  socket: /var/lib/mysql/mysql.sock
  database: rubyappdb

production:
  adapter: mysql2
  encoding: utf8
  pool: 5
  host: localhost
  username: Ruby
  password: ****
  port: 3306
  socket: /var/lib/mysql/mysql.sock
  database: rubyappdb

After editing the database.yml i tried the rails db:schema:dump which gave me errors and to install mysql2 and mysql2 adapter gem, which i have installed.

Now the command rails db:schema:dump works but the schema.rb is not filling the schema of the existing mysql database but this-
ActiveRecord::Schema.define(version: 0) do

Could not dump table "employees" because of following NoMethodError
undefined method `sql_type' for "int(11)":String

end

**Comment by matthewd** [comment]
Please use the mailing list or StackOverflow for questions/help, where a wider community will be able to help you. We reserve the issues tracker for issues only.
