### ISSUE TITLE
Autoloader still fails to handle namespaces

### ISSUE THREAD

**Issue by ngollan** [rails/rails#31837]
### Steps to reproduce
Try to have a model in nested namespaces with the same name as a toplevel constant (or any other constant anywhere in a Rails application), in an environment running the autoloader, i.e., normally anything but production.

### Expected behavior
Autoloader does not confuse the already loaded constant with the requested one.

### Actual behavior
Autoloader confuses the already loaded constant with the requested one, puts it into the wrong namespace, and stuff breaks in more or less subtle ways.

### System configuration
**Rails version**: 5.1.4

**Ruby version**: 2.3.3

**Comment by matthewd** [comment]
Thanks for the report, but this is "still" expected behaviour: http://guides.rubyonrails.org/autoloading_and_reloading_constants.html#common-gotchas

If Ruby doesn't think the constant is missing, we don't get a chance to define it.
