### ISSUE TITLE
ActionCable circular websocket_message processing when connection is closed

### ISSUE THREAD

**Issue by DedovR** [rails/rails#31836]
### Steps to reproduce

I don't known exactly, because I found this bug in production log.

### Expected behavior

In production log I found many same records like this:
`E, [2018-01-30T14:08:39.893202 #12649] ERROR -- : Ignoring message processed after the WebSocket was closed: "{\"command\":\"message\",\"data\":\"{\\\"command\\\":\\\"follow\\\",\\\"symbols\\\":\\\"ABB,BTCUSD:BITFINEX,AMZN,AAPL\\\",\\\"action\\\":\\\"follow\\\"}\",\"identifier\":\"{\\\"channel\\\":\\\"TickerChannel\\\"}\"}")
E, [2018-01-30T14:08:39.975338 #12649] ERROR -- : Ignoring message processed after the WebSocket was closed: "{\"command\":\"message\",\"data\":\"{\\\"action\\\":\\\"unfollow\\\"}\",\"identifier\":\"{\\\"channel\\\":\\\"TickerChannel\\\"}\"}")`

It's about a thousand identical records in log. After that was lost connection to redis. When I restart unicorn everything became good.

### Actual behavior
I think that happens because message_buffer not cleaned after connection closing.

### System configuration
**Rails version**: 5.0.2

**Ruby version**: 2.3.0

**Comment by rafaelfranca** [comment]
You need to give us more information on how to reproduce this issue, otherwise there is nothing we can do. Please read CONTRIBUTING.md file for more information about creating bug reports. Thanks!
