### ISSUE TITLE
ActiveRecord default_scope is ignored during reload

### ISSUE THREAD

**Issue by grosser** [rails/rails#31833]
confirmed the same in 4.2 up to 5.2

```Ruby
class Foo < ActiveRecord::Base
  default_scope { where(deleted_at: nil) }

  def soft_delete!
    update_column :deleted_at, Time.now
  end
end

foo = Foo.create!
foo.soft_delete!
foo.reload # expected ActiveRecord::RecordNotFound ... but just works
```

the sql the reload generates ignores the default scope
... I can make a PR with a failing test and maybe a fix if someone can confirm that this not expected behavior

**Comment by matthewd** [comment]
Seems expected to me: `reload` doesn't care how you got the record, it just cares about synchronising with what's in the database.

The default scope is an invisible condition applied to your queries when you're looking for records; it isn't involved once you've found one.

To me, this isn't substantially different from:

```ruby
Foo.create! n: 1
foo = Foo.find_by(n: 1)
foo.update_column :n, 2
foo.reload # still there
```

Generally, the expectation with a default scope is that you'll end up choosing to retrieve records that it filters out *sometimes*, and when you do, you want them to behave the same as their peers. `save` doesn't refuse to work, and nor does `reload`.

If you're writing a test, I'd go with an explicit re-find (`foo = Foo.find(foo.id)`). For anything else, I'm curious to understand the use case where this would be desirable.

**Comment by grosser** [comment]
was writing an unrelated test and got confused that it did not raise, not a big deal
