### ISSUE TITLE
`rails new` silently fails on incorrect command line option

### ISSUE THREAD

**Issue by dogweather** [rails/rails#31847]
### Steps to reproduce

My error, which I didn't catch until later, when I saw that the database was configured for Sqlite:

```bash
rails new my_app --database-postgresql
```

Also:

```bash
rails new my_app --heyheyhey
```
etc.

### Expected behavior
An error message, naming the unknown option. `rails new` should then quit with an error status.

### Actual behavior
`rails new` gives no sign that it was invoked incorrectly. It generates an app, and it appears to be successful.

### System configuration
**Rails version**: 5.1.4

**Ruby version**: 2.5.0

**Comment by dogweather** [comment]
I'm happy to submit a PR for this, if a fix is wanted.

**Comment by rafaelfranca** [comment]
This is expected behavior. rails new can also run a custom template, and this template can accept options that are not valid `rails new` commands. If we raise when we see invalid options we would remove this feature.

**Comment by dogweather** [comment]
@rafaelfranca Do you mean Application Templates enabled with `-m, [--template=TEMPLATE]`? I can imagine raising an error if a template hasn't been specified.

**Comment by matthewd** [comment]
:+1: that sounds like a good idea if it's feasible

**Comment by rafaelfranca** [comment]
:+1:

**Comment by dogweather** [comment]
I'll submit a PR.
