### ISSUE TITLE
Override api_only in Engine is not possible

### ISSUE THREAD

**Issue by radeno** [rails/rails#31841]
### Steps to reproduce

Rails app defined as more (shared models) have defined  in application.rb ```config.api_only = true``` because i want have base app most slim as possible. 
Then exists multiple Engines, for example multiple API, CMS, etc. But only one is active per app.

For CMS i want to again thick version of Rails. In Engine settings (engine.rb) i re-enable full Rails stack as ```config.api_only = false```

### Expected behavior
I except that middlewares (as Cookies and Sessions and etc) and route resource generator will generate paths for /new and /edit for every resource.

### Actual behavior
"api_only" is overridden to false but without effect.
I shlould add middlewares back, but there is not way how to force route resource generator to make missing paths.

### System configuration
**Rails version**: 5.1.4

**Ruby version**: 2.5.0

### Non working example
Base:
```ruby
module CoreApp
  class Application < Rails::Application
    config.load_defaults 5.1
    config.api_only = true
  end
end
```

Engine:
```ruby
module Cms
  class Engine < ::Rails::Engine
    isolate_namespace Cms
    config.api_only = false
  end
end
```

**Comment by rafaelfranca** [comment]
api_only take effect in the application so you can't override in an engine.

**Comment by rafaelfranca** [comment]
right.
