### ISSUE TITLE
.where([ ]) returns all records instead it should raise an error

### ISSUE THREAD

**Issue by Aravind99** [rails/rails#31852]
```ruby
class Organization < ApplicationRecord
end

Organization.where([ ])  # loads all records from database
Organization Load (39.8ms)  SELECT `organizations`.* FROM `organizations`

```

where
`Organization.all` does the same
**I think `Organization.where([ ])` should raise an error**

**Rails version**:
4.2.7, 5.0.1
**Ruby version**:
2.3.3

**Comment by bogdanvlviv** [comment]
@Aravind99 Currently, this is expected behavior, see https://github.com/rails/rails/blob/5-2-stable/activerecord/lib/active_record/relation/query_methods.rb#L574-L577

Related to https://github.com/rails/rails/pull/28290
