### ISSUE TITLE
active record: connection to multiple databases in different models

### ISSUE THREAD

**Issue by andrew-aladev** [rails/rails#31857]
### Steps to reproduce

Open [active_record/base.rb](https://github.com/rails/rails/blob/master/activerecord/lib/active_record/base.rb#L227-L240)

```
# Connections are usually created through
# {ActiveRecord::Base.establish_connection}[rdoc-ref:ConnectionHandling#establish_connection] and retrieved
# by ActiveRecord::Base.connection. All classes inheriting from ActiveRecord::Base will use this
# connection. But you can also set a class-specific connection. For example, if Course is an
# ActiveRecord::Base, but resides in a different database, you can just say <tt>Course.establish_connection</tt>
# and Course and all of its subclasses will use this connection instead.
```

Open [active_record/migration.rb](https://github.com/rails/rails/blob/master/activerecord/lib/active_record/migration.rb#L552-L600)

Try to search `Base.connect` and `Base.establish`. Is there an easy way to use your own connection? Is there an easy way to use your own `Base`? No.

Open [active_record/schema_migration.rb](https://github.com/rails/rails/blob/master/activerecord/lib/active_record/schema_migration.rb)

`ActiveRecord::Base.schema_migrations_table_name`

Open [active_record/log_subscriber.rb](https://github.com/rails/rails/blob/master/activerecord/lib/active_record/log_subscriber.rb#L90-L100)

`ActiveRecord::Base.logger`
`if ActiveRecord::Base.verbose_query_logs`

Open [active_record/fixtures.rb](https://github.com/rails/rails/blob/master/activerecord/lib/active_record/fixtures.rb#L536)

There is a workaround:
```
# FIXME: Apparently JK uses this.
connection = block_given? ? yield : ActiveRecord::Base.connection
```

But `ActiveRecord::Base.clear_active_connections!` will kill all base connections from currrent thread. Nobody cares about it. People just trust that all active connections from current thread belongs to current context.

Open [active_record/autosave_association.rb](https://github.com/rails/rails/blob/master/activerecord/lib/active_record/autosave_association.rb#L331).

`ActiveRecord::Base.index_nested_attribute_errors`

Open [active_record/railtie.rb](https://github.com/rails/rails/blob/master/activerecord/lib/active_record/railtie.rb)

`ActiveRecord::Base.verbose_query_logs = false`
`if ActiveRecord::Base.connected?`
`ActiveRecord::Base.clear_cache!`
`ActiveRecord::Base.clear_reloadable_connections!`

Open [active_record/schema_dumper.rb](https://github.com/rails/rails/blob/master/activerecord/lib/active_record/schema_dumper.rb#L250)

`connection = ActiveRecord::Base.connection` (perfect solution)
`ActiveRecord::Base.schema_migrations_table_name`
`ActiveRecord::Base.internal_metadata_table_name`

Open [active_record/type.rb](https://github.com/rails/rails/blob/master/activerecord/lib/active_record/type.rb#L52)

`adapter: ActiveRecord::Base.connection.adapter_name.downcase.to_sym` (perfect solution)

There are many `ActiveRecord::Base` read-write usages in `tasks/database_tasks`, `connection_adapters/*`, `railties/*`

### Expected behavior
We need to tell user the truth that it is not possible to use multiple databases today. We need to recognize architectural mistakes to fix it in future.

### Actual behavior
Total lie. Part of functionality was implemented as a `Base` side effects.

It is not possible to use active record with different databases.

You need to create dynamically your own `Base` and slip it under 10-12 core active record classes. Moreover you need to verify that all functionality respect your base. The chance to do something wrong is high.

### System configuration
**Rails version**: master
**Ruby version**: 2.4.3

We need to remove all `ActiveRecord::Base` usages from classes. `ActiveRecord::Base` can be the default source for some options, but it should be possible to rewrite it.

Please do not merge any pull request that uses `ActiveRecord::Base` directly.

**Comment by matthewd** [comment]
Thanks for the well-researched report, but we don't take feature requests in the issue tracker.

Lies notwithstanding, plenty of applications successfully work with multiple databases today. There's active work to support *migrations* on multiple databases... but limitations in periphery maintenance tasks don't prevent the application-proper from working just fine.

**Comment by andrew-aladev** [comment]
@matthewd, Can you please provide a name of branch or fork with WIP for migrations?

**Comment by Assaya** [comment]
Hi

Sent from Mail for Windows 10

**Comment by matthewd** [comment]
@andrew-aladev most recently, see #31727.

But note that the basic database maintenance commands are always going to be primarily focused on the also-basic situation of having and maintaining a single database.

Also note that your above grep conflates a number of places that yes, do use Base's connection, with a strong number that use it as the single source of truth for configuration settings. (Something like `verbose_query_logs` is set once in the application, and has no intention of being scoped by any specific connection or model.)

**Comment by andrew-aladev** [comment]
`verbose_query_logs` is good example. I want to enable verbose logs for first database client and disable for second one. It is not possible.

`pluralize_table_names` is good option too. I could change it globally for all databases but I couldn't do it for single database.

What is a `connection`? It is just a part of `Base` class. People are trying today to create a workaround to provide an alternative connection for some parts of logic like migration. This is not a solution, it is just a workaround. The problem is in `Base` architecture.

User are extending `Base` class. It received default logger, default options, etc. The key word is **default**. Storing real connection, connection pools, forcing options are inheritance violation. It won't lead to anything good.

**Comment by eileencodes** [comment]
@andrew-aladev while my PR didn't solve all the problems it's a very good start.

I'm actively working on improving features and writing new ones that will improve the experience around using multiple databases. But even without this it is still possible to use multiple databases with Rails. Basecamp and GitHub both do it but it requires some customization - customization I'm working on extracting. Hang tight, improvements to multiple databases are coming.

**Comment by andrew-aladev** [comment]
I am looking into `active_record/migration.rb` and I don't know how to fight with `Base`.

Maybe this is a result of `convention over configuration` paradigm. In wikipedia it means: "decrease the number of decisions that a developer using the framework is required to make without necessarily losing flexibility". But wikipedia don't want to teach us how to **restore** lost flexibility in system without configuration and what amount of time it will require.

**Comment by Assaya** [comment]
Hi Andrew

Sent from Mail for Windows 10

**Comment by rafaelfranca** [comment]
@andrew-aladev I already warned you in a different thread, but here I go again. Your passive-agressive comments are already becoming annoying. I humbly ask you to avoid doing them. Like we already said many times in this thread, improvements to multiple databases are coming. We don't know when, neither we don't know why. You are welcome to do whatever you want in the meantime. You can wait, or you can complain, it your choice. If you want to keep complaining, I just ask to you to not do here since it is not helpful.

Thanks
