### ISSUE TITLE
bundle update rails (4.1.4 to 4.2.10) taking long time 

### ISSUE THREAD

**Issue by surajit** [rails/rails#31856]
### Steps to reproduce
Changed 4.1.4 to 4.2.10 in Gemfile
(Guidelines for creating a bug report are [available
here](http://guides.rubyonrails.org/contributing_to_ruby_on_rails.html#creating-a-bug-report))

### Expected behavior
Tell us what should happen
It should update 
### Actual behavior
Tell us what happens instead
Its stuck in Resolving dependencies.......... 
### System configuration
**Rails version**:
present 4.1.4  need to upgrade to 4.2.10
**Ruby version**:
2.2.1 or 2.4.2

My Gemfile is:

ource 'https://rubygems.org'

gem 'rails', '4.2.10'
gem 'sass-rails'
gem 'uglifier'
gem 'jquery-rails'
gem 'mysql2'
gem 'devise'
gem 'devise_invitable', git: 'https://github.com/scambra/devise_invitable.git',
                        ref: '229b12e3ab08167e0c5286d5ac6fe9f9fa2445a3'

gem 'paperclip'
gem 'acts_as_list'
gem 'rubyzip'
gem 'to_bool'
gem 'jquery-fileupload-rails'
gem 'jquery-sparkline-rails', git: 'https://github.com/cubus/jquery-sparkline-rails.git'
gem 'aws-sdk', '< 2.0'
gem 'sidekiq-limit_fetch'
gem 'activerecord-session_store'
gem 'active_model_serializers'
gem 'devise_security_extension'
gem 'pretender'
gem 'puma', require: false

gem 'bootstrap-sass'
gem 'bootstrap-select-rails'
gem 'flag-icons-rails'
gem 'autoprefixer-rails'
gem 'font-awesome-sass'
gem 'local_time'
gem 'groupdate'
gem 'chartkick'
gem 'pace-rails'

gem 'sidekiq'
gem 'sidekiq-status'
gem 'sinatra', require: false
gem 'slim'
gem 'rails-i18n'

gem 'ransack'
gem 'kaminari'
gem 'counter_culture'

gem 'activerecord-import'
gem 'ar-octopus'

gem 'mina'
gem 'mina-multistage', require: false

gem 'airbrake'

gem 'newrelic_rpm', group: :production
gem 'paranoia'
gem 'sendgrid-actionmailer'

Please suggest what need to do

**Comment by matthewd** [comment]
Sounds like a question for Bundler, sorry 🤷🏻‍♂️
