### ISSUE TITLE
ActionView's CheckBox incorrectly calculates 'checked' property on inverted check values

### ISSUE THREAD

**Issue by hartsick** [rails/rails#31867]
### Steps to reproduce

Configure a form with a checkbox field where checked_value = "0" and unchecked_value = "1" (inverting the defaults) and a method (here :bad on model Dog) that returns a boolean value, like so:

```
<%= form_for @dog, invoice, index: nil do |form| %>
   Dogs who are good:
  <%= f.check_box(:bad,  {}, "0", "1") %>
<% end %>
```

### Expected behavior
When `dog.bad = true`, the box should be unchecked.
When `dog.bad = false`, the box should be checked.

### Actual behavior
The opposite:
When `dog.bad = true`, the box is checked.
When `dog.bad = false`, the box is unchecked.

### System configuration
**Rails version**:
5.1.4

**Ruby version**:
ruby 2.5.0p0

I've targeted the unexpected behavior to within the `checked?` method of ActionView::Helpers::Tags::CheckBox. Here's a screenshot showing the code and current behavior:

![screen shot 2018-02-01 at 1 38 05 pm](https://user-images.githubusercontent.com/3675092/35705703-0ff82dcc-0758-11e8-8489-58bc19a4cab4.png)

**Comment by rafaelfranca** [comment]
But why the checked value are `"0"` and `"1"` and not `true`, `false`?

**Comment by rafaelfranca** [comment]
If you know you value is a boolean you need to pass booleans as the checked value. Let me know if that also doesn't work so I can reopen this issue. thanks

**Comment by hartsick** [comment]
The default checked value is "1" and the default unchecked value is "1", so seems like a reasonable expectation?

![screen shot 2018-02-01 at 2 13 45 pm](https://user-images.githubusercontent.com/3675092/35706315-21dcf304-075a-11e8-840e-1e744604bfaa.png)

**Comment by rafaelfranca** [comment]
The default are strings to when the value is also a string or an integer, but if your value is a boolean you can't use strings because any string evaluates to `true` in ruby.

**Comment by hartsick** [comment]
Yeah, I understand that. I'm suggesting if not supporting the reversal of those arguments that they should be changed as the defaults (right now the defaults are both strings, too). It's confusing until you dig down where I did in the code (screenshot above). The current interface suggests that the reversal of the defaults would be fine.

I'm no longer using this on my project, but I do think it's a bug and at the least the usage should be clarified by better defaults, if not supported. But, I'm disengaging. Thanks.

**Comment by rafaelfranca** [comment]
That reversal of those argument are supported now, but the type or your attribute needs to be a string.

I agree the default value being strings is weird, and I agree it is confusing but changing that default to booleans will break a lot of code, so we can't do that.
