### ISSUE TITLE
Uploading files automatically with ActiveStorage

### ISSUE THREAD

**Issue by murdoch** [rails/rails#31863]
In my current setup, where I use Carrierwave and Cloudinary, files upload automatically as soon as they are attached. So the file is usually on Cloudinary before the user has finished filling out the form.

I'm trying to figure out if that's possible with ActiveStorage.

If not, would it be a worthwhile feature for me to try and contribute back to Rails, or is there something in the ActiveStorage code that prevents automatic uploads from working in the first place?

**Comment by morgoth** [comment]
@murdoch There is a library that tries to integrate activestorage with cloudinary https://github.com/0sc/activestorage-cloudinary-service but I didn't manage to make direct upload work with it so far.

**Comment by murdoch** [comment]
Thanks @dwightwatson but I've seen that already. What I'm looking to know is wether it's possible to make the upload start as soon as the file is attached. The example you linked to shows that the file upload starts when the form is submitted.

I guess I can place my upload progress bars down near my submit button, so the users at least know the reason why the form is taking so long to submit. Actually that would work.

**Comment by wbotelhos** [comment]
Hi @murdoch , any tip to make it works?

I tried to use `change` listener on file field and submit form, but stop it to be submited if form data have a flag `locked-by-upload`, so the upload is execute and the file field receives a string value like: `C:\fakepath\image.jpg`. The problem is that a do not now how to render this file as an image on HTML.

By the way, when you submit a form with an image and form contains an error and re-render, your image still keep attached on form? My image is rendered on field, but on submit it is `nil`.

**Comment by georgeclaghorn** [comment]
You can use the Active Storage’s JS API—the `DirectUpload` class specifically, which is documented [here](https://guides.rubyonrails.org/active_storage_overview.html#integrating-with-libraries-or-frameworks)—to perform direct uploads whenever you want.

**Comment by cseelus** [comment]
If you need to track the progress of the file upload, the `Uploader` class in the Rails docs currently is a little faulty (using both `this.upload` and an `upload` function cannot work).

I played around with making a custom Uploader class, using a different approach, which will also trigger all the callbacks like `direct-upload:initialize` and so forth and which will of course upload the files as soon as they are attached (which makes more sense imho).

For anyone interested, you can [see the code in this Gist](https://gist.github.com/cseelus/63baa4f46f6f0ae0c4630a3987022f97).

**Comment by modusss** [comment]
@cseelus I tried your code and didn't work to me.
