### ISSUE TITLE
numericality validator with custom getter adds an error when assigned blank value

### ISSUE THREAD

**Issue by nachokb** [rails/rails#31870]
check the gist => https://gist.github.com/nachokb/7d9763e8fadbe6286383e813f79fcadc

### Steps to reproduce

1. have a model with 
    1. an optional column and
    1. an accessor which computes it when it's blank (e.g. `StudentClass#total_count` is either the explicit value of that column or it's computed by summing other values);
1. add a numericality validator (with `allow_blank: true`)
1. assign an empty string `''` to that column

### Expected behavior

1. the model should behave exactly like it is when assigning `nil` to that column:
    1. particularly, it shouldn't trigger any validation error (because of `allow_blank: true`)

### Actual behavior

The model adds a "is not a number" validation error;

### System configuration
**Rails version**:

1. Rails 4.1.8 and 4.1.16: works as expected
1. Rails 4.2.9 and 4.2.10: fails (adds "is not a number" error)
1. Rails 5.1.4 & 5.2.0.rc1: fails and also throws weird `undefined method 'test_total_can_be_blank'` error

**Ruby version**: tested all Rails versions on Ruby 2.1, 2.2, 2.3 and 2.4 [*]. Behavior is exactly the same.

[*] with the exception of Rails 5+ on Ruby 2.1 (which is unsupported and fails when installing rack).

**Comment by fatkodima** [comment]
Looks like you should use a custom validation (`validate ....`) for overriden getter.
Related https://github.com/rails/rails/issues/29574.

**Comment by nachokb** [comment]
@fatkodima I'm not defending the particular usage here (overriding a getter is hairy indeed).

What I think I find incorrect is 

1. that it behaves differently whether I assign `nil` or `''`. Particularly b/c 90% of the time it will be assigned from parameters;
1. also, that this has changed and not been documented (AFAICT);

It only happens when overriding the getter, but I think *that* is incidental. I'll keep debugging it later though.

Thanks!

**Comment by nachokb** [comment]
I now believe that the problem is a little more subtle.

1. [EachValidator#validate](https://github.com/rails/rails/blob/master/activemodel/lib/active_model/validator.rb#L150) uses `#read_attribute_for_validation` (which is just an alias for `#send`) to implement `allow_blank`;
1. [NumericalityValidator#validate_each](https://github.com/rails/rails/blob/master/activemodel/lib/active_model/validations/numericality.rb#L22) uses `#XYZ_before_type_cast` instead to do the validation;

Thus, assigning a blank string to an attribute with a getter jumps the blank control, but the validation sees `''`.

This app is buggy, because validations historically respected overriden getters, and _this_ validation is trying to validate not the getter but the value set by the user (ie. it will never be blank, even if the user didn't set it, because it's getting computed in that case).

BUT, it is still a change from prior versions, and thus maybe we should document it somewhere? Maybe making it clear that

> if you override a getter, make sure `#XYZ_before_type_cast` and `#read_attribute_for_validation` behave consistently with your changes

I'm closing this issue because the new behavior _is the correct one_.
