### ISSUE TITLE
RedisCacheStore fetch_multi writes incorrect values.

### ISSUE THREAD

**Issue by swordray** [rails/rails#31884]
### Steps to reproduce

1. Create a new Rails 5.2.0.rc1 project.

2. Add gems `hiredis` and `redis`.

3. Add `redis_cache_store` to config/environments/development.rb.

```ruby
config.cache_store = :redis_cache_store, { driver: :hiredis, compress: true, timeout: 1 }
```

4. Enter console.

```ruby
2.5.0 :012 > Rails.cache
 => <#ActiveSupport::Cache::RedisCacheStore options={:namespace=>nil, :compress=>true, :compress_threshold=>1024, :expires_in=>nil, :race_condition_ttl=>nil} redis=#<Redis client v4.0.1 for redis://127.0.0.1:6379/0>>
2.5.0 :013 > Rails.cache.fetch_multi(:key) do 'value' end
 => {:key=>"value"}
2.5.0 :015 > Rails.cache.fetch_multi(:key) do 'value' end
 => {:key=>"#<ActiveSupport::Cache::Entry:0x00007fc0f5e6f588>"}
```

### Expected behavior
Expectedly return `"value"`.

### Actual behavior
Actually return `"#<ActiveSupport::Cache::Entry:0x00007fc0f5e6f588>"`.

### System configuration
**Rails version**: 5.2.0.rc1

**Ruby version**: 2.5.0

**Comment by jeremy** [comment]
Thanks for the report, @swordray! Fixed by #31886.
