### ISSUE TITLE
Rails, polymorphic association. Destroy with "touch: true", useless steps.

### ISSUE THREAD

**Issue by ghost** [rails/rails#31891]
I'm on **Rails 5**.

I have a polymorphic association like this:

*models/enjoy_level.rb*:

    class EnjoyLevel < ApplicationRecord
      belongs_to :enjoyable, polymorphic: true, touch: true, optional: true
    end

*models/mother.rb*:

    class Mother < ApplicationRecord
      has_one :enjoy_level, as: :enjoyable, dependent: :destroy
    
      accepts_nested_attributes_for :enjoy_level
    end

If I destroy one `mother` (which have `touch: true` option) it still:

- destroy the `enjoy_level` one before;
- set `Mother` `update_at` to now();
- and finally destroy this `Mother` record one.

**The first and second steps are useless**, right?

Where am I wrong?

### System configuration
**Rails version**: 5.1.4
**Ruby version**: 2.5.0

**Comment by eileencodes** [comment]
Hey @johnunclesam I'm not sure exactly what problem you're seeing. Can you use [our test scripts to provide a test case](https://github.com/rails/rails/blob/master/guides/bug_report_templates/active_record_master.rb) that reproduces your issue? Thanks.

**Comment by noma4i** [comment]
@eileencodes I think I know he is trying to explain. Check my gist https://gist.github.com/noma4i/3034ac3776cdfea2730f2ca81dd3f836

You can see that rails from master has 6 queries overall for that test while 5.1.5.rc1 will use 7 sql queries generating one useless SELECT statement so my assert will pass on master while failing for 5.1.*

flip `gem 'rails'` in my test suite to see the problem.

**Comment by AKovtunov** [comment]
@eileencodes I think he is trying to ask, what is the purpose of updating Mother's object by related EnjoyLevel objects just before Mother's object will be destroyed.

For example using his code:
```
mother = Mother.new
enjoy_level = EnjoyLevel.create(mother_id: mother.id)

mother.destroy
# After we called destroy action:
# 1. Rails will go to all the EnjoyLevel objects and destroy them, that belong to that mother object because of `depend: :destroy` condition.
# 2. Each destroy of EnjoyLevel object will do `touch` method to related mother's model because of `belongs_to ..., touch: true' condition and will make a commit to the database updating updated_at field of mother's model
# 3. Mother model will be completely destroyed
```

So in this case step 2 looks like a useless set of queries that can be omitted.

**Comment by johnunclesam** [comment]
Dear @rails-bot, I can still reproduce the "issue" on `master`. Please, remove `stale` label. Thanks.
