### ISSUE TITLE
Caching behavior regression

### ISSUE THREAD

**Issue by kddeisz** [rails/rails#31897]
### Steps to reproduce

Here's a gist with the behavior: https://gist.github.com/kddeisz/e513f30e315912d8eb40ed97b644346d. 

Note you'll need redis running to run this script. I'm not sure if it's isolated to the redis store or not, I'm just trying to mirror my application as closely as possible.

### Expected behavior

When updating a record (and thereby updated the `updated_at` column) it should bust the cache.

### Actual behavior

It's not busting.

### System configuration
**Rails version**: 5.2.0.rc1

**Ruby version**: 2.5.0

**Comment by kddeisz** [comment]
Update: it's not the cache store. After bisecting it comes to here: https://github.com/rails/rails/commit/f6d2efa9e8d597832510fd20e3b8fee87f6e6df6. Working on a PR now.

**Comment by kddeisz** [comment]
Okay yeah no I'm going to need help with this. I can get it to fix my use case but I can't get it to pass to the test here: https://github.com/rails/rails/commit/57f0e3d1300d01444d2a311560c055d26968dc3f#r26439527. @georgeclaghorn I'm going to probably need your help here.

**Comment by kddeisz** [comment]
I'm actually not sure I understand why we wouldn't want to use `cache_key_with_version` in this case.

**Comment by eugeneius** [comment]
Your script uses the `redis_store` adapter provided by the [redis-activesupport](https://github.com/redis-store/redis-activesupport) gem, which isn't maintained by the Rails team; unless you can reproduce the bug using one of the in-tree adapters, this issue should be opened against that gem instead.

**Comment by kddeisz** [comment]
@eugeneius I've updated the gist to use the built-in redis cache store, the tests still fail.

**Comment by georgeclaghorn** [comment]
The test passes for me:

```
Run options: --seed 48525

# Running:

.

Finished in 0.012247s, 81.6526 runs/s, 244.9579 assertions/s.
1 runs, 3 assertions, 0 failures, 0 errors, 0 skips
```

**Comment by kddeisz** [comment]
Oh so embarrassing sorry! I forgot to clear out the cache between switching the adapters. Sorry about that!

**Comment by tubbo** [comment]
I was able to reproduce this when setting `config.cache_store = :memory_store` in my 5.2.0.rc1 application...

```
irb(main):002:0> Project.first.cache_key
  Project Load (0.5ms)  SELECT  "projects".* FROM "projects" ORDER BY "projects"."id" ASC LIMIT $1  [["LIMIT", 1]]
=> "projects/1"
```
