### ISSUE TITLE
5.2.0 RC1 Cache Digesting Issue

### ISSUE THREAD

**Issue by tomrossi7** [rails/rails#31902]
There appears to be an issue with determining the template for digesting. I believe it may be related to rendering HTML in response to a javascript request. Here is the code that worked in previous versions of Rails:

```
    respond_to do |format|
      format.html
      format.js { render @objects, cached: true }
    end
```

With 5.2.0, I am getting the warning:

`Couldn't find template for digesting: admin/_object`

I tried being more explicit:

```
    respond_to do |format|
      format.html
      format.js { render partial: 'admin/object', collection: @objects, cached: true }
    end
```

But that didn't work. I was finally able to get it to work by providing the full path (except the underscore for the partial):

```
    respond_to do |format|
      format.html
      format.js { render partial: 'admin/object.html.erb', collection: @objects, cached: true }
    end
```

**Comment by y-yagi** [comment]
Can you please provide a sample application that reproduces the issue?

**Comment by matthewd** [comment]
@georgeclaghorn this sounds a little like https://github.com/rails/jbuilder/pull/400 to me... do you think it could be related?

**Comment by georgeclaghorn** [comment]
It seems like we may expect a JS template at `admin/_object.js.erb` because the rendered format is JS. I reproduced this in a test app, and passing `formats: :html` to `render` fixes it.

**Comment by georgeclaghorn** [comment]
When we [look up](https://github.com/rails/rails/blob/5ae2ecab6d3365f6f17e3c8cb298dfeeea113774/actionview/lib/action_view/digestor.rb#L52) the partial for digesting, we only give the lookup context the rendered format.

**Comment by tomrossi7** [comment]
Nevermind, passing `formats: :html` (formats plural) did remove the warning!

**Comment by georgeclaghorn** [comment]
The option is `:formats`, not `:format`.

**Comment by tomrossi7** [comment]
I had the same issue with an `html.erb` page rendering the same partial:

` <%= render partial: 'admin/object.html.erb', collection: @objects %>`

I was able to apply the same fix to avoid the digesting issue:

`<%= render @objects, formats: :html %>`
