### ISSUE TITLE
Error querying empty string on a ActiveRecord Association Relation

### ISSUE THREAD

**Issue by everaldo** [rails/rails#31908]
### Steps to reproduce

I was unable to reproduce the bug using the template, but I will paste the output of explain command on rails console, using Rails 3.2.x (where it works) and Rails 4.2.10 (where it fails)

EXPLAIN SELECT `agency_manufacturers`.* FROM `agency_manufacturers` WHERE `agency_manufacturers`.`manufacturer_id` = 90 AND `agency_manufacturers`.`imprint_ids` = '' AND (country like '%Australia%')

SELECT `agency_manufacturers`.* FROM `agency_manufacturers` WHERE `agency_manufacturers`.`manufacturer_id` = 90 AND `agency_manufacturers`.`imprint_ids` = **'--- \'\'\n'** AND (country like '%Australia%')

### Expected behavior
Query an empty String on an ActiveRecord Association Relation

### Actual behavior
Rails replaces empty String with '--- \'\'\n'

### System configuration
**Rails version**: 4.2.10

**Ruby version**: 2.4.1

**Comment by composerinteralia** [comment]
4.2 is only getting security updates at this point. You can check out the [maintenance policy](http://guides.rubyonrails.org/maintenance_policy.html) for details. Is this something you can recreate on 5.1, preferably using one of these [templates](http://guides.rubyonrails.org/contributing_to_ruby_on_rails.html#create-an-executable-test-case)?

**Comment by everaldo** [comment]
I couldn't manage to reproduce the bug using the templates. When we upgrade to Rails 5.1 I could check the bug again. But, since I've made a search on google before creating the issue, I believe it still persists on 5.1

**Comment by y-yagi** [comment]
You need to give us more information on how to reproduce this issue or provides reproduce script, otherwise there is nothing we can do.  
So I close this. But if you can create a reproduce script, feel free to reopen this. Thanks!

**Comment by everaldo** [comment]
@y-yagi , I discovered that this bug occurs because the Machine was using MySQL 5.6.16

When in 5.7.21, this bug doesn't exists.

Thanks!
