### ISSUE TITLE
5.1.5.rc1 after commit on update still doesn't work

### ISSUE THREAD

**Issue by ahorek** [rails/rails#31903]
Hi,
I've noticed that this bug wasn't fixed yet, but there's a PR for it. Is there any chance to merge this before the final release?
https://github.com/rails/rails/pull/29096

cc @rafaelfranca @kamipo 

Thanks

**Comment by claudiob** [comment]
@ahorek Thanks for the reminder.
I just restarted the build on Travis for that branch (was red but probably unrelated).

**Comment by ahorek** [comment]
ci is green, anything else I can do to move this forward? should I also make a MR for 5.1.5?

**Comment by rafaelfranca** [comment]
It will not be included in 5.1.5, unless it is a regression since 5.1.4, that is not the case. Maybe it will be included in 5.1.6, but it depends if someone merge it.
