### ISSUE TITLE
@object.errors.details has unexpected behaviour

### ISSUE THREAD

**Issue by chinito** [rails/rails#31921]
### Steps to reproduce

Simple Rails App with one Person model. Person has a name and a birthdate. Add a validation for the name to the model so it must bei present.
But should be reproducabale with any Rails Model

### Expected behavior
```
irb(main):001:0> foo = Person.new
=> #<Person id: nil, name: nil, birthdate: nil, created_at: nil, updated_at: nil>
irb(main):002:0> foo.valid?
=> false
irb(main):003:0> foo.errors.details
=> {:name=>[{:error=>:blank}]}
irb(main):004:0> foo.errors.details[:bar].present?
=> false
irb(main):005:0> foo.errors.details
=> {:name=>[{:error=>:blank}]}
```

### Actual behavior
```
irb(main):001:0> foo = Person.new
=> #<Person id: nil, name: nil, birthdate: nil, created_at: nil, updated_at: nil>
irb(main):002:0> foo.valid?
=> false
irb(main):003:0> foo.errors.details
=> {:name=>[{:error=>:blank}]}
irb(main):004:0> foo.errors.details[:bar].present?
=> false
irb(main):005:0> foo.errors.details
=> {:name=>[{:error=>:blank}], :bar=>[]}
irb(main):006:0> foo.errors.details[:bar].present?
=> false
```
You see, after asking if `:bar`is there, it is there. But actually it is not, if you ask again.
Same happens with `.any?`, `.empty?` ...
Problem is, if you render the details as JSON then, the `:bar` shows up there.

### System configuration
**Rails version**: 5.1.4

**Ruby version**: ruby 2.4.1p111

**Comment by bogdanvlviv** [comment]
Thanks for the report. I'll fix
Related to #23468, #28584

**Comment by bogdanvlviv** [comment]
From comments in https://github.com/rails/rails/issues/23468#issuecomment-288865859 i got that this is expected behavior and we shouldn't change this.
Thank you.

**Comment by chinito** [comment]
@bogdanvlviv thanks for getting into it. I still think this is weird. Because if you check some details for a certain error before rendering the json, the key then shows up in the view. We had some really confused frontend-developers because of this. But thank you anyway!
