### ISSUE TITLE
ActionCable exceptions are logged and then ignored. There needs to be a way to hook in some airbrake/honeybadger notification etc.

### ISSUE THREAD

**Issue by sjain** [rails/rails#31924]
### Steps to reproduce

I am using a `before_subscribe` hook on ActionCable::Channel::Base to authorize user when a new connection request comes in. If there is a bug in my custom code that raises an exception, I would have expected there to be a way to tap into that exception much like there exists `rescue_from` for ActionController hierarchy. All it does right now is log the error using `logger.error` and silently moves on.

https://github.com/rails/rails/blob/master/actioncable/lib/action_cable/connection/subscriptions.rb#L23-L24
and
https://github.com/rails/rails/blob/master/actioncable/lib/action_cable/connection/base.rb#L86-L90

Would it be a good idea to build something like `rescue_from`?

### Expected behavior

Be able to tap into exceptions and use custom reporting logic.

### Actual behavior

Silent ignore of error, with a just a log in log file.

### System configuration
**Rails version**:
5.1.4

**Ruby version**:
2.3.0

**Comment by pixeltrix** [comment]
The standard way to do this is with callbacks - rescue the exception, report to the relevant service and then re-raise. The [Appsignal gem][1] is doing a combination of callbacks and method chaining which suggests that maybe we're missing callbacks for actions on channels. Other than that it's up to the third-party gems to implement support.

[1]: https://github.com/appsignal/appsignal-ruby/blob/master/lib/appsignal/hooks/action_cable.rb

**Comment by sjain** [comment]
The Appsignal gem seems to be monkey patching `ActionCable::Channel::Base#perform_action` method. In my project, I did it at `ActionCable::Connection::Subscriptions::execute_command` level.
