### ISSUE TITLE
Some guides are not listed in documents.yaml

### ISSUE THREAD

**Issue by yskkin** [rails/rails#31920]
### Steps to reproduce
- guides/source/active_record_postgresql.md
- guides/source/development_dependencies_install.md
- guides/source/rails_application_templates.md

These files are not listed in guides/source/documents.yaml

### Expected behavior
All pages should be listed in http://edgeguides.rubyonrails.org/ or at least reachable via links.
(But I don't know this is intended or not.)

### Actual behavior
Two of these pages are reachable via links, but http://edgeguides.rubyonrails.org/active_record_postgresql.html seems unreachable.
```
➜  rails git:(master) PAGER=cat git grep development_dependencies_install
guides/source/contributing_to_ruby_on_rails.md:In case you can't use the Rails development box, see [this other guide](development_dependencies_install.html).
➜  rails git:(master) PAGER=cat git grep rails_application_templates
guides/source/generators.md:Now that you've seen how generators can be used _inside_ an application, did you know they can also be used to _generate_ applications too? This kind of generator is referred to as a "template". This is a brief overview of the Templates API. For detailed documentation see the [Rails Application Templates guide](rails_application_templates.html).
➜  rails git:(master) PAGER=cat git grep active_record_postgresql
```

**Comment by kamipo** [comment]
At least active_record_postgresql.md is intended as work in progress. https://github.com/rails/rails/pull/23376#discussion_r51372663

**Comment by yskkin** [comment]
As for `development_dependencies_install.md` and `rails_application_templates.md`, is this expected?
Personally I found `rails_application_templates.md` is useful on its own and worth to list in `documents.yaml`

**Comment by cowlibob** [comment]
active_record_postgresql.md was helpful to me, could it be included in the index or linked to now?
