### ISSUE TITLE
Unable to skip before commit callback

### ISSUE THREAD

**Issue by heaven** [rails/rails#31936]
In model I have:
```ruby
before_commit :queue, on: [:create, :update]
after_commit :queue, on: :destroy
```

We also need to skip these callbacks in one place, I tried:
```ruby
EmailAddress.skip_callback(:commit, :before, :queue)
EmailAddress.skip_callback(:commit, :after, :queue)
```

But this leads to:
```
ArgumentError: Before commit callback :queue has not been defined
```

But still can skip the `after_commit` one.

UPD. It seems to skip the `before` one I have to write `before_commit` instead of just `before`, which is strange:
```ruby
EmailAddress.skip_callback(:before_commit, :before, :queue)
```

And the error message in case of undefined callback also looks weird:
```
2.3.3 :003 > EmailAddress.skip_callback(:before_commit, :before, :test)
 => ArgumentError: Before before_commit callback :test has not been defined
```

**Comment by fatkodima** [comment]
It is a private api, as stated here https://github.com/rails/rails/issues/25896 so not recommended to use.
And implemented here https://github.com/rails/rails/blob/d7f9adf7941574d0a40a165739938d28f278bd77/activerecord/lib/active_record/transactions.rb#L217 through `:before_commit` - so this is why the second example is working.

**Comment by heaven** [comment]
Yeah, exactly, I figured this out looking at this same code. I find this a little discrepancy compared to the other callbacks, even though the API might be private. And it is not very clear that the API is private.

**Comment by y-yagi** [comment]
Only the API that appears on the API site(http://api.rubyonrails.org) are public user-facing API. 
If visibility is public but `:nodoc:` is specified, it is an API for internal use, so it does not appear on the API site. 
`before_commit` is specified `:nodoc:`. In other words, it is an internal API, not public user-facing API.  
https://github.com/rails/rails/blob/4a17b26c6850dd0892dc0b58a6a3f1cce3169593/activerecord/lib/active_record/transactions.rb#L215 

Ref: http://edgeguides.rubyonrails.org/api_documentation_guidelines.html#method-visibility
