### ISSUE TITLE
Running rails new with template URL fails with HTTP Error Code 406

### ISSUE THREAD

**Issue by jw81** [rails/rails#31930]
### Steps to reproduce
Attempt to pass a web URL to a template file via the `-m` option on `rails new`.
Example :: `rails new helloworld -m https://github.com/jw81/Rails_Templating/blob/master/template.rb`

### Expected behavior
A new Rails project is created using the template passed into the `-m` option.

### Actual behavior
`/usr/local/lib/ruby/2.5.0/open-uri.rb:377:in open_http': 406 Not Acceptable (OpenURI::HTTPError)`

### System configuration
**Rails version**: 5.0.0

**Ruby version**: 2.5

**Comment by y-yagi** [comment]
Please use the [mailing list](https://groups.google.com/forum/#!forum/rubyonrails-talk) or StackOverflow for questions/help, where a wider community will be able to help you. We reserve the issues tracker for issues only.

**Comment by jw81** [comment]
Dang it, I'm sorry.
It wasn't a bug.  It was user error.

For people who may stumble across this in the future, make sure you are passing a URL that points at the RAW version of a file.
In my example, if I change the url that I pass via the `-m` option to `https://raw.githubusercontent.com/jw81/Rails_Templating/master/template.rb`, it works perfectly.

Sorry for opening the issue.  :(
