### ISSUE TITLE
5.2.0.rc1: Rails.cache.fetch raise TypeError: no _dump_data is defined for class Proc

### ISSUE THREAD

**Issue by liukun-lk** [rails/rails#31931]
### Steps to reproduce

When update Rails to 5.2.0.rc1, 
```
Rails.cache.fetch('test') { Page.home.enable.includes(:banners).first }
```
will raise `TypeError: no _dump_data is defined for class Proc`.

```
# app/models/page.rb
...
  has_many :pages_banners, -> { order(weight: :asc, id: :desc) }, dependent: :destroy, inverse_of: :page
  has_many :banners, through: :pages_banners
...
```

When I remove `-> { order(weight: :asc, id: :desc) }`, rails cache can run correctly.

And when I rollback to `5.2.0.beta2`, rails cache also can run correctly even if `-> { order(weight: :asc, id: :desc) }` exist.

### System configuration
**Rails version**:
5.2.0.rc1
**Ruby version**:
ruby 2.4.0p0 (2016-12-24 revision 57164) [x86_64-darwin16]

**Comment by fatkodima** [comment]
Thanks. I will look at this.
