### ISSUE TITLE
Newly created record has changes on timestamps

### ISSUE THREAD

**Issue by wagenet** [rails/rails#31937]
The issue can be approximated as follows:

```rb
> a = App.create!
> a.changes
=> {"created_at"=>
  [Thu, 08 Feb 2018 17:41:13 UTC +00:00, Thu, 08 Feb 2018 17:41:13 UTC +00:00],
 "updated_at"=>
  [Thu, 08 Feb 2018 17:41:13 UTC +00:00, Thu, 08 Feb 2018 17:41:13 UTC +00:00]}
> a.changes["created_at"][0].nsec
=> 707180575
> a.changes["created_at"][1].nsec
=> 707180000
```

I've yet to be able to create a local repro, though I am continuing to try. None of my code attempts to set either of these values so it's not clear to me why they should be dirty.

Ruby: 2.5.0
Rails: 5.2.0.rc
Postgres: 9.6.5
pg gem: 1.0.0

Postgres schema:
```sql
CREATE TABLE apps (
    created_at timestamp without time zone,
    updated_at timestamp without time zone
)
```

**Comment by fatkodima** [comment]
Can't reproduce. Looks like problem is arising from other party (external gem for example). Could you, please, provide a reproducible script using this template https://github.com/rails/rails/blob/master/guides/bug_report_templates/active_record_master.rb?

**Comment by wagenet** [comment]
@fatkodima it's almost certainly some edge case interaction. I can't even reproduce it on my local dev system, only on Heroku. That said, I'm happy to dig in further, though if anyone can point me in a more specific direction that would be very helpful.

**Comment by wagenet** [comment]
So I think I have a pretty good idea of what is causing this.

The `App` record has an `after_save` call back which attempts to update a cache on a `belongs_to` for `Organization`. The `Organization`'s cache update method calls `apps.length`, this in turn eventually hits this code in ActiveRecord: https://github.com/rails/rails/blob/master/activerecord/lib/active_record/associations/collection_association.rb#L331. Along the way, we compare the record persisted in the DB with the local one in memory. However, Postgres doesn't store nanoseconds so the times don't match up.

**Comment by wagenet** [comment]
I can't repro this locally because I'm developing on macOS and Ruby doesn't have nanoseconds here.

**Comment by wycats** [comment]
@fatkodima In light of the fact that @wagenet can't reproduce locally, it seems more likely to be a platform-specific edge-case rather than an interaction with a third party gem.

**Comment by sgrif** [comment]
Adding `sleep 1` might help for getting a repro script

**Comment by wagenet** [comment]
@wycats I couldn't reproduce locally because macOS doesn't have nano seconds in `Time`, but as @sgrif mentioned, a well-placed `sleep 1` would probably work around this. I'll try to put together a repro for this, but TBH it's not a high priority for me now that I have a workaround.

**Comment by ideaoforder** [comment]
+1

**Comment by lacostenycoder** [comment]
Can anyone comment weather the OP in this SO question might be related to this?
https://stackoverflow.com/questions/54994592/ruby-time-zone-now-and-accounting-for-database-precision/54994862?noredirect=1#comment96748134_54994862

**Comment by byroot** [comment]
Without a reproduction script, this isn't actionable so I'll close.
