### ISSUE TITLE
feature proposal: delegate private

### ISSUE THREAD

**Issue by equivalent** [rails/rails#31932]
I want to introduce a PR to Rails after which  there would be a possibility to delegate methods to object as private methods. But I want to check first with you if it's a good idea before I do the work.

So we would have this (already existing method `#delegate`) for delegation as  public methods :

```ruby
class Foo
   # ...
   delegate :foo, :bar, to: :baz
   # ...
end

foo = Foo.new
foo.foo
foo.bar
```

https://github.com/rails/rails/blob/master/activesupport/lib/active_support/core_ext/module/delegation.rb#L154

And I want to introduce method `#delegate_privately` 

```ruby
class Foo
   # ...
   delegate_privately :car, :dar, to: :daz
   # ...
end

foo = Foo.new
foo.car  # => NoMethodError: private method `car' called for #<Foo:0x000000015e8b10>
foo.dar # => NoMethodError: private method `car' called for #<Foo:0x000000015e8b10>
```

...or if you don't want a new method I can change existing `delegate` method to include flag `private: true`

```ruby
class Foo
   # ...
   delegate :foo, :bar, to: :baz
   delegate :car, :dar, to: :daz, private: true
   # ...
end

foo = Foo.new
foo.foo
foo.bar
```

**Reason**

from my understanding,  currently the only way how to delegate as private method is by doing:

```ruby
class Foo
   # ...
   private *delegate( :car, :dar, to: :daz)
   # ...
end

foo = Foo.new
foo.car  # => NoMethodError: private method `car' called for #<Foo:0x000000015e8b10>
foo.dar # => NoMethodError: private method `car' called for #<Foo:0x000000015e8b10>
```

* https://blog.eq8.eu/til/how-to-delegate-methods-in-rails-as-private.html
* https://stackoverflow.com/questions/15643172/make-delegated-methods-private

and there are some cases when I want to do delegation in object and not expose it as interface method

-----

and BTW this don't work:

```ruby
class Foo
   private  
   delegate :to_s, to: :bar  
   def bar
     12
   end  
end  

Foo.new.to_s
#=> "12"

Foo.new.public_methods - Object.new.public_methods 
#=> [:foo]
```

**Comment by equivalent** [comment]
:thinking: looking at the [code](https://github.com/rails/rails/blob/master/activesupport/lib/active_support/core_ext/module/delegation.rb#L154) the `   delegate :car, :dar, to: :daz, private: true` would be simpler, but it's your call really I don't mind

**Comment by simi** [comment]
AFAIK Active Support accepts mainly features used internally in Rails code. Is there chance for any benefit for current Rails code?

**Comment by equivalent** [comment]
I don't know, I use the `#delegate` all over the production code of applications that I write (as other Active Support methods)  

The delegation is extension of `class Module` => it's used everywhere. So I'm not sure what benefit it will have for Rails code but  it's sort of an issue for application code if there is no way how to delegate privately. `¯\_(ツ)_/¯`

**Comment by equivalent** [comment]
:thinking: 

>Also feature proposals without code belongs to rails-core mailing list - http://edgeguides.rubyonrails.org/contributing_to_ruby_on_rails.html#what-about-feature-requests-questionmark.

![sorry](https://rlv.zcache.com/okay_meme_postcard-r431d6dd2726a40d98d4f55ef721556ed_vgbaq_8byvr_324.jpg) 

sorry didn't know, closing the ticket

**Comment by equivalent** [comment]
https://github.com/rails/rails/pull/31933
