### ISSUE TITLE
Record not found if relation is empty on an M-N relation

### ISSUE THREAD

**Issue by axos88** [rails/rails#31946]
### Steps to reproduce

```
t = Teacher.create(name 'T1', students: [] )

Teacher.find(t.id).students # ==> []
Teacher.joins(:students).find(t.id).students # ==> ActiveRecord::RecordNotFound: Couldn't find Teacher with 'id'=5a7d8965df499c0b7234ec1d
```

### Expected behavior

Should also return []

### Actual behavior

ActiveRecord::RecordNotFound, with a bogus message, as the Teacher with that id actually exists!

The reason probably is that the join is an inner join, but most likely should be an outer join:

```
SELECT  "teachers".* FROM "teachers" INNER JOIN "teachers_students" ON "teachers_students"."teacher_id" = "teachers"."id" INNER JOIN "students" ON "students"."id" = "teachers_students"."student_id" WHERE "teachers"."id" = $1 LIMIT 1  [["id", "5a7d8965df499c0b7234ec1d"]]
```

### System configuration
**ActiveRecord**: 4.2.8
**Ruby version**: 2.3.1

**Comment by tbuehlmann** [comment]
I'd expect `Teacher.joins(:students).find(t.id)` to raise `ActiveRecord::RecordNotFound` as that specific teacher is not part of the relation because of the inner join.

**Comment by liukun-lk** [comment]
Maybe you should use `Teacher.includes(:students).find(t.id).students`. And `Teacher.includes(:students).references(:students).find(t.id).students` will be LEFT OUTER JOIN.

**Comment by axos88** [comment]
@tbuehlmann @liukun-lk That may be true, but unless someone takes time to debug what is happening, they do not know that there is an inner join at play behind the scenes. Also the error message saying that the Teacher with the specific id does not exist is even worse, since it absolutely does. I'm not sure what "relation" the teacher would not be part of...

**Comment by georgeclaghorn** [comment]
This is the correct behavior.
