### ISSUE TITLE
[5.1.4] mysql2 gem seems not to work with activesupport-5.1.4

### ISSUE THREAD

**Issue by palladius** [rails/rails#31940]
### Steps to reproduce

I have rails app which works fine. I try to add `mysql2` config to database.yml, and system doesnt run anymore. I've done lots of digging on internet, but I believe that "activesupport-5.1.4" doesnt play well with mysql2.

# Gemfile:
[..]
gem 'mysql2' # adding this
[..]

### Expected behavior
Tell us what should happen:

Should work like a charm. I'm including the libraries, I have packages installed locally, everything seems to work, but it does not RUN.

### Actual behavior
Tell us what happens instead:

$ bundle exec unicorn -c config/unicorn.rb

/home/riccardo/.rvm/gems/ruby-2.3.4/gems/activesupport-5.1.4/lib/active_support/dependencies.rb:292:in `require': Could not load 'active_record/connection_adapters/mysql_adapter'. Make sure that the adapter in config/database.yml is valid. If you use an adapter other than 'mysql2', 'postgresql' or 'sqlite3' add the necessary adapter gem to the Gemfile. (LoadError)
	from /home/riccardo/.rvm/gems/ruby-2.3.4/gems/activesupport-5.1.4/lib/active_support/dependencies.rb:292:in `block in require'
	from /home/riccardo/.rvm/gems/ruby-2.3.4/gems/activesupport-5.1.4/lib/active_support/dependencies.rb:258:in `load_dependency'
	from /home/riccardo/.rvm/gems/ruby-2.3.4/gems/activesupport-5.1.4/lib/active_support/dependencies.rb:292:in `require'
	from /home/riccardo/.rvm/gems/ruby-2.3.4/gems/activerecord-5.1.4/lib/active_record/connection_adapters/connection_specification.rb:186:in `spec'
	from /home/riccardo/.rvm/gems/ruby-2.3.4/gems/activerecord-5.1.4/lib/active_record/connection_adapters/abstract/connection_pool.rb:880:in `establish_connection'
	from /home/riccardo/.rvm/gems/ruby-2.3.4/gems/activerecord-5.1.4/lib/active_record/connection_handling.rb:58:in `establish_connection'
	from /home/riccardo/.rvm/gems/ruby-2.3.4/gems/activerecord-5.1.4/lib/active_record/railtie.rb:124:in `block (2 levels) in <class:Railtie>'
	from /home/riccardo/.rvm/gems/ruby-2.3.4/gems/activesupport-5.1.4/lib/active_support/lazy_load_hooks.rb:69:in `instance_eval'
	from /home/riccardo/.rvm/gems/ruby-2.3.4/gems/activesupport-5.1.4/lib/active_support/lazy_load_hooks.rb:69:in `block in execute_hook'
	from /home/riccardo/.rvm/gems/ruby-2.3.4/gems/activesupport-5.1.4/lib/active_support/lazy_load_hooks.rb:60:in `with_execution_control'
	from /home/riccardo/.rvm/gems/ruby-2.3.4/gems/activesupport-5.1.4/lib/active_support/lazy_load_hooks.rb:65:in `execute_hook'
	from /home/riccardo/.rvm/gems/ruby-2.3.4/gems/activesupport-5.1.4/lib/active_support/lazy_load_hooks.rb:50:in `block in run_load_hooks'
	from /home/riccardo/.rvm/gems/ruby-2.3.4/gems/activesupport-5.1.4/lib/active_support/lazy_load_hooks.rb:49:in `each'
	from /home/riccardo/.rvm/gems/ruby-2.3.4/gems/activesupport-5.1.4/lib/active_support/lazy_load_hooks.rb:49:in `run_load_hooks'
	from /home/riccardo/.rvm/gems/ruby-2.3.4/gems/activerecord-5.1.4/lib/active_record/base.rb:326:in `<module:ActiveRecord>'
	from /home/riccardo/.rvm/gems/ruby-2.3.4/gems/activerecord-5.1.4/lib/active_record/base.rb:25:in `<top (required)>'
	from /home/riccardo/.rvm/gems/ruby-2.3.4/gems/activesupport-5.1.4/lib/active_support/dependencies.rb:292:in `require'
	from /home/riccardo/.rvm/gems/ruby-2.3.4/gems/activesupport-5.1.4/lib/active_support/dependencies.rb:292:in `block in require'
	from /home/riccardo/.rvm/gems/ruby-2.3.4/gems/activesupport-5.1.4/lib/active_support/dependencies.rb:258:in `load_dependency'
	from /home/riccardo/.rvm/gems/ruby-2.3.4/gems/activesupport-5.1.4/lib/active_support/dependencies.rb:292:in `require'
	from /home/riccardo/git/ror5-pasta/pasta/app/models/application_record.rb:1:in `<top (required)>'
	from /home/riccardo/.rvm/gems/ruby-2.3.4/gems/activesupport-5.1.4/lib/active_support/dependencies.rb:292:in `require'
	from /home/riccardo/.rvm/gems/ruby-2.3.4/gems/activesupport-5.1.4/lib/active_support/dependencies.rb:292:in `block in require'
	from /home/riccardo/.rvm/gems/ruby-2.3.4/gems/activesupport-5.1.4/lib/active_support/dependencies.rb:258:in `load_dependency'
	from /home/riccardo/.rvm/gems/ruby-2.3.4/gems/activesupport-5.1.4/lib/active_support/dependencies.rb:292:in `require'
	from /home/riccardo/.rvm/gems/ruby-2.3.4/gems/activesupport-5.1.4/lib/active_support/dependencies.rb:379:in `block in require_or_load'
	from /home/riccardo/.rvm/gems/ruby-2.3.4/gems/activesupport-5.1.4/lib/active_support/dependencies.rb:36:in `block in load_interlock'
	from /home/riccardo/.rvm/gems/ruby-2.3.4/gems/activesupport-5.1.4/lib/active_support/dependencies/interlock.rb:12:in `block in loading'
	from /home/riccardo/.rvm/gems/ruby-2.3.4/gems/activesupport-5.1.4/lib/active_support/concurrency/share_lock.rb:149:in `exclusive'
	from /home/riccardo/.rvm/gems/ruby-2.3.4/gems/activesupport-5.1.4/lib/active_support/dependencies/interlock.rb:11:in `loading'
	from /home/riccardo/.rvm/gems/ruby-2.3.4/gems/activesupport-5.1.4/lib/active_support/dependencies.rb:36:in `load_interlock'
	from /home/riccardo/.rvm/gems/ruby-2.3.4/gems/activesupport-5.1.4/lib/active_support/dependencies.rb:357:in `require_or_load'
	from /home/riccardo/.rvm/gems/ruby-2.3.4/gems/activesupport-5.1.4/lib/active_support/dependencies.rb:335:in `depend_on'
	from /home/riccardo/.rvm/gems/ruby-2.3.4/gems/activesupport-5.1.4/lib/active_support/dependencies.rb:251:in `require_dependency'
	from /home/riccardo/.rvm/gems/ruby-2.3.4/gems/railties-5.1.4/lib/rails/engine.rb:476:in `block (2 levels) in eager_load!'
	from /home/riccardo/.rvm/gems/ruby-2.3.4/gems/railties-5.1.4/lib/rails/engine.rb:475:in `each'
	from /home/riccardo/.rvm/gems/ruby-2.3.4/gems/railties-5.1.4/lib/rails/engine.rb:475:in `block in eager_load!'
	from /home/riccardo/.rvm/gems/ruby-2.3.4/gems/railties-5.1.4/lib/rails/engine.rb:473:in `each'
	from /home/riccardo/.rvm/gems/ruby-2.3.4/gems/railties-5.1.4/lib/rails/engine.rb:473:in `eager_load!'
	from /home/riccardo/.rvm/gems/ruby-2.3.4/gems/railties-5.1.4/lib/rails/engine.rb:354:in `eager_load!'
	from /home/riccardo/.rvm/gems/ruby-2.3.4/gems/railties-5.1.4/lib/rails/application/finisher.rb:67:in `each'
	from /home/riccardo/.rvm/gems/ruby-2.3.4/gems/railties-5.1.4/lib/rails/application/finisher.rb:67:in `block in <module:Finisher>'
	from /home/riccardo/.rvm/gems/ruby-2.3.4/gems/railties-5.1.4/lib/rails/initializable.rb:30:in `instance_exec'
	from /home/riccardo/.rvm/gems/ruby-2.3.4/gems/railties-5.1.4/lib/rails/initializable.rb:30:in `run'
	from /home/riccardo/.rvm/gems/ruby-2.3.4/gems/railties-5.1.4/lib/rails/initializable.rb:59:in `block in run_initializers'
	from /home/riccardo/.rvm/rubies/ruby-2.3.4/lib/ruby/2.3.0/tsort.rb:228:in `block in tsort_each'
	from /home/riccardo/.rvm/rubies/ruby-2.3.4/lib/ruby/2.3.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
	from /home/riccardo/.rvm/rubies/ruby-2.3.4/lib/ruby/2.3.0/tsort.rb:431:in `each_strongly_connected_component_from'
	from /home/riccardo/.rvm/rubies/ruby-2.3.4/lib/ruby/2.3.0/tsort.rb:349:in `block in each_strongly_connected_component'
	from /home/riccardo/.rvm/rubies/ruby-2.3.4/lib/ruby/2.3.0/tsort.rb:347:in `each'
	from /home/riccardo/.rvm/rubies/ruby-2.3.4/lib/ruby/2.3.0/tsort.rb:347:in `call'
	from /home/riccardo/.rvm/rubies/ruby-2.3.4/lib/ruby/2.3.0/tsort.rb:347:in `each_strongly_connected_component'
	from /home/riccardo/.rvm/rubies/ruby-2.3.4/lib/ruby/2.3.0/tsort.rb:226:in `tsort_each'
	from /home/riccardo/.rvm/rubies/ruby-2.3.4/lib/ruby/2.3.0/tsort.rb:205:in `tsort_each'
	from /home/riccardo/.rvm/gems/ruby-2.3.4/gems/railties-5.1.4/lib/rails/initializable.rb:58:in `run_initializers'
	from /home/riccardo/.rvm/gems/ruby-2.3.4/gems/railties-5.1.4/lib/rails/application.rb:353:in `initialize!'
	from /home/riccardo/git/ror5-pasta/pasta/config/environment.rb:5:in `<top (required)>'
	from config.ru:4:in `require_relative'
	from config.ru:4:in `block in <main>'
	from /home/riccardo/.rvm/gems/ruby-2.3.4/gems/rack-2.0.4/lib/rack/builder.rb:55:in `instance_eval'
	from /home/riccardo/.rvm/gems/ruby-2.3.4/gems/rack-2.0.4/lib/rack/builder.rb:55:in `initialize'
	from config.ru:1:in `new'
	from config.ru:1:in `<main>'
	from /home/riccardo/.rvm/gems/ruby-2.3.4/gems/unicorn-4.9.0/lib/unicorn.rb:48:in `eval'
	from /home/riccardo/.rvm/gems/ruby-2.3.4/gems/unicorn-4.9.0/lib/unicorn.rb:48:in `block in builder'
	from /home/riccardo/.rvm/gems/ruby-2.3.4/gems/unicorn-4.9.0/lib/unicorn/http_server.rb:768:in `build_app!'
	from /home/riccardo/.rvm/gems/ruby-2.3.4/gems/unicorn-4.9.0/lib/unicorn/http_server.rb:137:in `start'
	from /home/riccardo/.rvm/gems/ruby-2.3.4/gems/unicorn-4.9.0/bin/unicorn:126:in `<top (required)>'
	from /home/riccardo/.rvm/gems/ruby-2.3.4/bin/unicorn:22:in `load'
	from /home/riccardo/.rvm/gems/ruby-2.3.4/bin/unicorn:22:in `<main>'
	from /home/riccardo/.rvm/gems/ruby-2.3.4/bin/ruby_executable_hooks:15:in `eval'
	from /home/riccardo/.rvm/gems/ruby-2.3.4/bin/ruby_executable_hooks:15:in `<main>'

### System configuration
**Rails version**: 5.1.4
**Ruby version**: tried 2.3.4p301 and 2.2

**Comment by y-yagi** [comment]
> /home/riccardo/.rvm/gems/ruby-2.3.4/gems/activesupport-5.1.4/lib/active_support/dependencies.rb:292:in require': Could not load 'active_record/connection_adapters/mysql_adapter'. Make sure that the adapter in config/database.yml is valid. If you use an adapter other than 'mysql2', 'postgresql' or 'sqlite3' add the necessary adapter gem to the Gemfile.

In this error, you probably have specified erroneous `adater` in `config/database.yml`. 
Confirm the `adapter` specification, if you specified `mysql`, change to` mysql2`.

**Comment by dogweather** [comment]
This seems to be a Rails incompatibilty with the current mysql2 version 0.5.0. Note that a new Rails install creates this `Gemfile` entry:

```ruby
# Use mysql as the database for Active Record
gem 'mysql2', '>= 0.3.18', '< 0.5'
```

**Comment by Edouard-chin** [comment]
This will be fixed by https://github.com/rails/rails/pull/32310
