### ISSUE TITLE
Reload does not refresh the object, only the data

### ISSUE THREAD

**Issue by kgathi2** [rails/rails#31945]
### Steps to reproduce
Create and migrate model with attr_accessor
```ruby
class User < ApplicationRecord
  attr_accessor :virtual
end
```
(Guidelines for creating a bug report are [available
here](http://guides.rubyonrails.org/contributing_to_ruby_on_rails.html#creating-a-bug-report))

### Expected behavior
Tell us what should happen
```bash
user = User.create(virtual: 'bla')
user.virtual #=> 'blah'
user.reload  #<User id: 1>
user.virtual #=> nil
```
### Actual behavior
Tell us what happens instead
```bash
user = User.create(virtual: 'bla')
user.virtual #=> 'blah'
user.reload  #<User id: 1>
user.virtual #=> 'blah'
```
### System configuration
**Rails version**:
'rails', '~> 5.1.4'

**Ruby version**:
ruby:2.5.0

**Comment by y-yagi** [comment]
This is intentional behavior. 
`reload` method only reload `attributes` from database and clear cache. 
For details, please see [API doc](http://api.rubyonrails.org/classes/ActiveRecord/Persistence.html#method-i-reload).
