### ISSUE TITLE
Polymorphism object with .tap 

### ISSUE THREAD

**Issue by korabh** [rails/rails#31950]
### Expected behavior
```    
   location = Location.new.tap do |l|
      l.locatable_type = 'Product',
      l.locatable_id = product.id,
      ...
   [19] pry(#<Resolvers::CreateProduct>)> location.locatable_type => "Product"

```
### Actual behavior
```
    location = Location.new.tap do |l|
      l.locatable_type = 'Product',
      l.locatable_id = product.id,
      ...
   [21] pry(#<Resolvers::CreateProduct>)> location.locatable_type => "[\"Product\", 16, 1, 1, 0.42667542e2, 0.21166191e2]"
```

### System configuration
**Rails version**: Rails 5.1.4

**Ruby version**: ruby 2.4.0p0 (2016-12-24 revision 57164) [x86_64-darwin16]

**Comment by fatkodima** [comment]
Try to delete extra commas in your example
```ruby
l.locatable_type = 'Product',  <-- here
l.locatable_id = product.id,   <-- here
```

**Comment by georgeclaghorn** [comment]
Deleting the commas will help.

**Comment by korabh** [comment]
@fatkodima @georgeclaghorn Ahh, no the problem is with `locatable_type` result. Using `.tap` method on new object returns `[\"Product\", 16, 1, 1, 0.42667542e2, 0.21166191e2]` instead of "Product".
