### ISSUE TITLE
Validations can be bypassed when calling save!

### ISSUE THREAD

**Issue by artur-beljajev** [rails/rails#31959]
### Steps to reproduce

1. rails new testapp
2. rails g scaffold user name
3. rake db:migrate
4. Add `validates :name, presence: true` to `app/models/user.rb`
5. rails c

```
Loading development environment (Rails 5.1.4)
irb(main):001:0> u = User.new
=> #<User id: nil, name: nil, created_at: nil, updated_at: nil>
irb(main):002:0> u.validate
=> false
irb(main):003:0> u.valid?
=> false
irb(main):004:0> u.save
   (0.1ms)  begin transaction
   (0.1ms)  rollback transaction
=> false
irb(main):005:0> u.save!
   (0.1ms)  begin transaction
   (0.3ms)  rollback transaction
ActiveRecord::RecordInvalid: Validation failed: Name can't be blank
        from (irb):5
irb(main):006:0> u.save!(validate: false)
   (0.1ms)  begin transaction
  SQL (0.9ms)  INSERT INTO "users" ("created_at", "updated_at") VALUES (?, ?)  [["created_at", "2018-02-11 21:01:38.955998"], ["updated_at", "2018-02-11 21:01:38.955998"]]
   (22.5ms)  commit transaction
=> true

```

### Expected behavior
1. Inform about incorrect usage
2. Ignore silently

As per spec, there is no way to bypass validations. And I guess having it defeats the purpose of the method entirely.

https://github.com/rails/rails/blob/v5.1.4/activerecord/lib/active_record/validations.rb#L49

### Actual behavior
Saves a record

### System configuration
5.1.4

**Ruby version**:
ruby 2.2.7p470

**Comment by rafaelfranca** [comment]
This is the expected behavior, save! is the same as save and allows users to bypass validation if they pass validate option as false

**Comment by artur-beljajev** [comment]
But isn't `save!(validate: false)` confusing if the purpose of `save!` method is to
> raise an ActiveRecord::RecordInvalid exception instead of returning +false+ if the record is not valid.
?

**Comment by rafaelfranca** [comment]
It is documented there:

    # However, if you supply
    # <tt>validate: false</tt>, validations are bypassed altogether. See
    # ActiveRecord::Validations for more information.

**Comment by artur-beljajev** [comment]
Thanks! Missed that entirely.
