### ISSUE TITLE
EventedFileUpdateChecker makes things slow when watching missing directories

### ISSUE THREAD

**Issue by jhawthorn** [rails/rails#31954]
When `EventedFileUpdateWatcher` is instructed to watch a directory which doesn't exist, it will find a parent directory which does and watch that.

One of the standard directories to be watched is `test/mailers/previews`. If there's no `test/` directory at all, it will watch the root of the project. This could also be caused by a missing `db`, `config`, or (admittedly unlikely) `app` directory.

Listen always watches recusrively, so this will watch **all** directories within the project. This will include directories with a lot of I/O (like `tmp`, `db`) as well as directories with tons of files (like `vendor/bundle` and `node_modules`).

Listen will filter out [some of these](https://github.com/guard/listen/blob/master/lib/listen/silencer.rb) and EventedFileUpdateChecker [filters the rest](https://github.com/rails/rails/blob/master/activesupport/lib/active_support/evented_file_update_checker.rb#L99-L123) but this is done in ruby, costs CPU, and still eats up OS limits (`fs.inotify.max_user_watches` on Linux)

### Steps to reproduce

An easy way to reproduce is to make a new app **with no `test/` directory** and run anything which does file I/O within `Rails.root`.

```
rails new listen_issue_demo --skip-spring --skip-test
cd listen_issue_demo
LISTEN_GEM_DEBUGGING=2 rake assets:precompile
```

### Expected behavior

No wakeups (we aren't changing files in watched directories).

### Actual behavior

Many wakeups. ([full debug text](https://gist.github.com/b409673aeb67c4dcad32dd5c45c291d5))
```
D, [2018-02-10T00:06:55.737266 #2721] DEBUG -- : inotify: tmp/cache/assets/sprockets ([:create, :isdir])
D, [2018-02-10T00:06:55.737426 #2721] DEBUG -- : (silenced): "tmp/cache/assets/sprockets"
D, [2018-02-10T00:06:55.739134 #2721] DEBUG -- : inotify: tmp/cache/assets/sprockets/v3.0/De ([:create, :isdir])
D, [2018-02-10T00:06:55.739249 #2721] DEBUG -- : (silenced): "tmp/cache/assets/sprockets/v3.0/De"
D, [2018-02-10T00:06:55.739606 #2721] DEBUG -- : inotify: tmp/cache/assets/sprockets/v3.0/D2 ([:create, :isdir])
D, [2018-02-10T00:06:55.739656 #2721] DEBUG -- : (silenced): "tmp/cache/assets/sprockets/v3.0/D2"
(hundreds more)
```

This is a nearly empty new app, in a large one this can add seconds to the asset build. [I gist'd an example here](https://gist.github.com/jhawthorn/12aac0dcf714399b3863e85824f27f94).

There are also potential issues due to symlinks (ex. in `vendor/bundle`) [making Listen unhappy](https://gist.github.com/jhawthorn/f5ab81dc32c5a8c02236225b3b6efedc), which are hard to avoid when Listen is set to watch everything.

### System configuration
**Rails version**: 5.1.4

**Ruby version**: 2.5.0

**Comment by y-yagi** [comment]
Duplicated with #29750?

**Comment by jeremy** [comment]
Great diagnosis @jhawthorn. Unfortunately for this case, this is by design… to detect when the directory is created! Not much help if we never intend or expect it to exist. Perhaps the listen lib could offer an alternative, or we could selectively omit nonexistent watchable dirs ourselves. Merging with #29750.

**Comment by matthewd** [comment]
Yeah, I think we need `listen` to offer an API that will watch a folder non-recursively. (Or more likely, "in whatever manner is simplest for the platform" -- if all watches are recursive it shouldn't filter things out, but if they're not, it shouldn't manually set up deep watches.)

It's intended behaviour that we stand ready in case the missing directory appears, but there's certainly no reason we need or want to watch everything else besides.
