### ISSUE TITLE
Missing Component on links with remote true Rails-UJS

### ISSUE THREAD

**Issue by ltenzil** [rails/rails#31961]
### Steps to reproduce
application.js
//= require jquery3
//= require jquery-ui
//= require rails-ujs
//= require turbolinks
//= require foundation
//= require wice_grid
//= require select2
//= require_tree .

$(document).on('turbolinks:load', function() {
  $(document).foundation();
  $('[data-app-dashboard-toggle-shrink]').on('click', function(e) {
    e.preventDefault();
    $(this).parents('.app-dashboard').toggleClass('shrink-medium').toggleClass('shrink-large');
  });
});

(Guidelines for creating a bug report are [available
here](http://guides.rubyonrails.org/contributing_to_ruby_on_rails.html#creating-a-bug-report))

### Expected behavior
Tell us what should happen
on click of links with remote true should work properly without throwing any js errors.

### Actual behavior
Tell us what happens instead
On click of links with remote: true it always throws missing component error in js

### System configuration
**Rails version**: 5.1.4
![missing-component](https://user-images.githubusercontent.com/16436134/36082679-8ea90930-0fd1-11e8-8a1d-537d55058945.png)

**Ruby version**: 2.4.2

**Comment by y-yagi** [comment]
Please use the [mailing list](https://groups.google.com/forum/#!forum/rubyonrails-talk) or StackOverflow for questions/help, where a wider community will be able to help you. We reserve the issues tracker for issues only. Thanks.
