### ISSUE TITLE
Expiring S3 URLs and HTML Emails

### ISSUE THREAD

**Issue by thomasotoole** [rails/rails#31965]
Probably not a bug but, is there any way to prevent prevent ActiveStorage's S3 URLs from expiring?

Or ... does ActiveStorage provide a method for obtaining the true S3 bucket URL?

I am using ActiveStorage and S3 to manage images used for HTML emails. It works great immediately after the email is created. However, the next day all of the image URLs in the email message are broken. 

I am using the service_url method to obtain the image, like this:
art.related_image.variant(resize: "500x500").processed.service_url

**Rails version**:
Rails 5.2
**Ruby version**:

**Comment by rafaelfranca** [comment]
Please use StackOverflow for questions/help, where a wider community will be able to help you. We reserve the issues tracker for issues only.

**Comment by gregblass** [comment]
This seems to be a common theme with activestorage. I understand the notion and point of separating questions and issues, but this seems like it could be a recurring gap in functionality for many use cases - which could arguably/potentially belong here.
