### ISSUE TITLE
rails new <app> --skip-coffee cause LoadError when using gem 'rails', github: 'rails/rails'

### ISSUE THREAD

**Issue by kw7oe** [rails/rails#31969]
When I `rails generate <app>` with `--skip-coffee`, it will cause 

```LoadError (cannot load such file -- coffee_script)``` 

when visiting the page if the following configuration is used

```gem 'rails', :git => 'https://github.com/rails/rails.git', :branch => '5-2-stable'```

in the Gemfile. However, **it works perfectly fine if I use `gem 'rails', '~> 5.2.0.rc1'`.**

### Steps to reproduce

1. `rails new testing --skip-coffee`
2. `cd testing`
3. Replace `gem 'rails', '~> 5.2.0.rc1'` with `gem 'rails', :git => 'https://github.com/rails/rails.git', :branch => '5-2-stable'` in the `Gemfile`
4. `rails generate controller pages index`
5. `rake test`
or
6. `rails s` and visit to [http://localhost:3000/pages/index](http://localhost:3000/pages/index)

### Expected behavior
- Test should pass.
- Page should be render successfully.

### Actual behavior
- Test failed with following outputs:
```
Error:
PagesControllerTest#test_should_get_index:
LoadError: cannot load such file -- coffee_script
    app/views/layouts/application.html.erb:7:in `_app_views_layouts_application_html_erb__3959579703635133883_70287663479740'
    test/controllers/pages_controller_test.rb:5:in `block in <class:PagesControllerTest>'
```
- Page is render with `LoadError (cannot load such file -- coffee_script)`.

### System configuration
**Ruby version**: `ruby 2.5.0p0 (2017-12-25 revision 61468) [x86_64-darwin17]`

----
#### So, I am just curious whether this is a bug or something wrong with my configuration?

**Comment by eugeneius** [comment]
CoffeeScript is a required dependency when using Rails directly from GitHub.

See https://github.com/rails/rails/issues/31616, https://github.com/rails/rails/issues/28965.
