### ISSUE TITLE
Model generator with polymorphic references creates invalid migration file

### ISSUE THREAD

**Issue by choix** [rails/rails#31963]
### Steps to reproduce

1) Create a new rails application. `rails new gen`
2) Use an example from `rails g model` output. Which is `rails generate model product supplier:references{polymorphic}:index`

### Expected behavior

Generated migration show have the following content:

```ruby
class CreateProducts < ActiveRecord::Migration[5.2]
  def change
    create_table :products do |t|
      t.references :supplier, polymorphic: true, index: true

      t.timestamps
    end
  end
end
```

### Actual behavior

Generated migration has the following content:

```ruby
class CreateProducts < ActiveRecord::Migration[5.2]
  def change
    create_table :products do |t|
      t.referencesc :supplier
      t.referencesh :supplier
      t.referencesi :supplier
      t.referencesl :supplier
      t.referencesm :supplier
      t.referenceso :supplier
      t.referencesp :supplier
      t.referencesr :supplier
      t.referencesy :supplier

      t.timestamps
    end
    add_index :products, :supplier
    add_index :products, :supplier
    add_index :products, :supplier
    add_index :products, :supplier
    add_index :products, :supplier
    add_index :products, :supplier
    add_index :products, :supplier
    add_index :products, :supplier
    add_index :products, :supplier
  end
end
```

### System configuration

**Rails version**: `5.2.0.rc1`
**Ruby version**: `ruby 2.4.1p111 (2017-03-22 revision 58053) [x86_64-darwin16]`

**Comment by bogdanvlviv** [comment]
Hi @choix. I can't reproduce this on `5.2.0.rc1`

here is my migration:
```ruby
class CreateProducts < ActiveRecord::Migration[5.2]
  def change
    create_table :products do |t|
      t.references :supplier, polymorphic: true

      t.timestamps
    end
  end
end
```
tip: using of `index` in "the reproduction step 2" and "Generated migration" you provided is redundant since
 ```ruby
t.references :supplier, polymorphic: true
```
adds appropriate index
```ruby
t.index ["supplier_type", "supplier_id"], name: "index_products_on_supplier_type_and_supplier_id"
```

**Comment by choix** [comment]
@bogdanvlviv Thank you for looking into it.

I've checked again. The issue was in the way `zsh` parses `supplier:references{polymorphic}`. For example, `printf '=%.0s' {1..100}` will turn into 100 `=` character.

It turned this shell command:
```
rails generate model product supplier:references{polymorphic}
```

into:
```
/Users/choix/.rbenv/versions/2.4.1/bin/ruby bin/rails generate model product supplier:referencesc supplier:referencesh supplier:referencesi supplier:referencesl supplier:referencesm supplier:referenceso supplier:referencesp supplier:referencesr supplier:referencesy
```

In case anyone will come here because of the same issue. Just wrap field definition inside double quote, like this:
```
rails generate model product "supplier:references{polymorphic}"
```

**Comment by pinzonjulian** [comment]
For anyone else having this issue, if found that removing `index: true` solves the issue. For me, it didn't have anything to do with zsh

**Comment by sunny-mittal** [comment]
If using `zsh`, you can also prefix any line with `noglob` and it'll ignore patterns. In this case, using quotes is simpler, but there are times it won't work.
