### ISSUE TITLE
has_one through not available on unpersisted instances

### ISSUE THREAD

**Issue by zachwalton** [rails/rails#31975]
Note: I believe the way that this works is by associating with post_id, so if that's the case it makes sense that this would be the behavior, and I suppose this becomes an enhancement request.

`Comment` knows that it has a `Post` associated with it as evidenced by the passed assertion on L66, so is it possible to leverage that relationship to make the `through` association work?

### Steps to reproduce

Script to reproduce: https://gist.github.com/zachwalton/395412f5b7e97837e6273981dbb7faf3

### Expected behavior

`owner` should be not be nil when accessed through the `has_one through` association

### Actual behavior

`owner` is nil when accessed through the `has_one through` association

### System configuration
**Rails version**: 5.1.2

**Ruby version**: 2.4.2

**Comment by jfragoulis** [comment]
This may have to do with https://github.com/rails/rails/pull/31575.

**Comment by adamlogic** [comment]
Here's a workaround that passes the test above.

```ruby
class Comment < ActiveRecord::Base
  belongs_to :post
  has_one :post_author, through: :post, source: :author

  def post_author
    super || post.try(:author)
  end
end
```

**Comment by zachwalton** [comment]
https://github.com/rails/rails/issues/33155
