### ISSUE TITLE
Default renderer not used when rendering outside of controllers

### ISSUE THREAD

**Issue by ennder** [rails/rails#31979]
### Expected behavior
Default renderer (configured in config/initializers/application_controller_renderer.rb) should be used when rendering pages outside a controller.

### Actual behavior
Hard-coded default renderer is used (host : example.org).

### System configuration
**Rails version**: 5.1.4 (last stable)
**Ruby version**: 2.4.1

### Steps to reproduce

1.  Install missing packages if necessary :

```
# debian instructions
sudo apt-get install autoconf
sudo apt-get install automake
sudo apt-get install libtool
sudo apt-get install libffi-dev
```

2. New app :

```
rails new test_default_renderer
rails -v
=> 5.1.4
```

3. Enable the default JS runtime :

```
vi Gemfile
# uncomment gem 'therubyracer', platforms: :ruby
bundle install # to install the gem
```

4. Check the default renderer :

```
cd test_default_renderer
cat config/initializers/application_controller_renderer.rb
# Be sure to restart your server when you modify this file.

# ActiveSupport::Reloader.to_prepare do
#   ApplicationController.renderer.defaults.merge!(
#     http_host: 'example.org',
#     https: false
#   )
# end

rails c
irb(main):001:0> ApplicationController.renderer.defaults
=> {:http_host=>"example.org", :https=>false, :method=>"get", :script_name=>"", :input=>""}`
```

5. Generate a scaffold :

`rails generate scaffold page title: string`

6. Check the Pages Controller renderer :

```
rails c
irb(main):001:0>  PagesController.renderer.defaults
=> {:http_host=>"example.org", :https=>false, :method=>"get", :script_name=>"", :input=>""}
```

7. Change default renderer :

```
cat config/initializers/application_controller_renderer.rb
# Be sure to restart your server when you modify this file.

ActiveSupport::Reloader.to_prepare do
  ApplicationController.renderer.defaults.merge!(
    http_host: 'genuinedomain.org',
    https: false
  )
end
```

8. Recreate Page scaffold :

```
rails destroy scaffold Page
rails generate scaffold page title: string
```

9. Re-check the Pages Controller renderer :

```
rails c
irb(main):001:0>  PagesController.renderer.defaults
=> {:http_host=>"example.org", :https=>false, :method=>"get", :script_name=>"", :input=>""}
```

10. Conclusion :

- **the default renderer is not used**
- It is an issue when rendering pages outside a controller, within Channels for example

**Comment by ennder** [comment]
Related to #22975

**Comment by ennder** [comment]
With Rails 5.0.0.beta2, **rails generate scaffold page title: string** trigger an error :

`config/initializers/application_controller_renderer.rb:3:in `merge!': can't modify frozen Hash (RuntimeError)`

**Comment by ennder** [comment]
Anyone having an idea on how to workaround this issue ?

**Comment by Utopism** [comment]
Hi, If I have the time I'll check where the fix has to be done.

**Comment by dongennl** [comment]
I'm having this issue too; can't figure out a way to solve.

**Comment by a-ta-ta** [comment]
The same.

**Comment by TWGerard** [comment]
I am having this issue now when rendering an HTML partial from a JBuilder view. Running rails 6.0.0.rc1

**Comment by kwent** [comment]
Fixed it by doing

```
ActiveSupport::Reloader.to_prepare do
  ApplicationController.renderer.defaults.merge!(
    http_host: 'rootly.ai',
    https: true
  )
end
```

**Comment by Utopism** [comment]
Hi kwent,
> Fixed it by doing
> ```ruby
> ActiveSupport::Reloader.to_prepare do
>   ApplicationController.renderer.defaults.merge!(
>     http_host: 'hello.com',
>     https: true
>   )
> end
> ```
This is exactly what does not work outside a controller. Do you mean it works for you ?
If yes, with which version of rails ?

**Comment by kwent** [comment]
@Utopism Nevermind i ended up doing 

in production.rb
```ruby
config.action_controller.default_url_options = {host : "hello.com"}
```

This works outside of controllers.

**Comment by although2013** [comment]
Just for someone who encounter this problem later, I am also confused that the `ApplicationController.render()` would **NOT** use the defaults you defined in default renderer file. Instead you need to **create a new instance of renderer.**

You can try the following solution to render html outside of controllers with custom `http_host`:

> 👇 Tested on Rails 6.1.1, Ubuntu 20.04

1. Comment out these code as below:
```ruby
# config/initializers/application_controller_renderer.rb
ActiveSupport::Reloader.to_prepare do
  ApplicationController.renderer.defaults.merge!(
    http_host: 'localhost:3000',
    https: false
  )
end
```

2. Create a new instance of `SomeController.renderer`, for example, I'm going to render html in ActionCable channels:
```ruby
# app/channels/applications_cable/channel.rb
module ApplicationCable
  class Channel < ActionCable::Channel::Base

    # create a new instance of renderer with defaults
    def default_renderer
      @default_renderer ||= ApplicationController.renderer.new
    end
  end
end

```

3. Then you can use it in your `chat_channel.rb` like this:
```ruby
class ChatChannel < ApplicationCable::Channel
  def subscribed
    html = default_renderer.render(
      partial: '......',
      locals: { user: current_user }
    )

    ActionCable.server.broadcast(...)
  end
end
```

**Comment by clarkology56** [comment]
I was having the same issue. I fixed it by using the `path` helper instead of the `url` helper (ex `user_path(@user)` instead of `user_url(@user)`)
