### ISSUE TITLE
Model generator creates database migration with awkward columns types.

### ISSUE THREAD

**Issue by skatkov** [rails/rails#31977]
### Steps to reproduce
Go to console, find existing project and generate a model:
``` rails g model ProductVariation asin:string{null:false} data:jsonb{null:false} parent_asin:string{null:false} ```

### Expected behavior
I was expecting that i would have a database migration, that would create a product_variations table

with following structure:
```
t.string :asin, null: false
t.jsonb :data, null: false
t.string :parent_asin, null: false
```

+ plus created_at and updated_at columns
### Actual behavior
I got this in a migration:

```
create_table :product_variations do |t|
      t.string :asin
      t.stringa :asin
      t.stringe :asin
      t.stringf :asin
      t.stringl :asin
      t.stringn :asin
      t.strings :asin
      t.stringu :asin
      t.jsonb :data
      t.jsonba :data
      t.jsonbe :data
      t.jsonbf :data
      t.jsonbl :data
      t.jsonbn :data
      t.jsonbs :data
      t.jsonbu :data
      t.string :parent_asin
      t.stringa :parent_asin
      t.stringe :parent_asin
      t.stringf :parent_asin
      t.stringl :parent_asin
      t.stringn :parent_asin
      t.strings :parent_asin
      t.stringu :parent_asin

      t.timestamps
    end
```

Model looked as expected.
### System configuration
**Rails version**:
Rails 5.2.0.rc1
**Ruby version**:
ruby 2.5.0p0 (2017-12-25 revision 61468) [x86_64-darwin15]

**Comment by y-yagi** [comment]
It looks like the same issue as https://github.com/rails/rails/issues/31963#issuecomment-364902124.
Please try to wrap field definition inside double quote. Thanks.
