### ISSUE TITLE
In test environment, data of sqlite db are erased after system test execution

### ISSUE THREAD

**Issue by giacomo-giovenzana** [rails/rails#31973]
### Steps to reproduce
1. setup test environment and db. In my setup I have copied the db from development to test
```rails db:drop RAILS_ENV='test'
rails db:create RAILS_ENV='test'
rails db:schema:load RAILS_ENV='test'
cp db/development.sqlite3 db/test.sqlite3
```
2. create new system test
`rails g system_test system_test_xyz`
Here the simple test I am using (in the page I printed all database table element in css selector span):
```require "application_system_test_case"
class SystemTestXyz < ApplicationSystemTestCase
  test "visiting the welcome index page" do
    visit root_path
    assert_selector "span", {text: "Table element 1"}
  end
end
```
3. Check the test db data
`rails s -e test`
Browsing inside the local website I can see all data (so, it means test.sqlite3 is populated)
4. Close rails server and start rails test
`rails test test/system/system_test_xyz.rb`

### Expected behavior
- Test have to pass

### Actual behavior
- Test fails due to missing data. Also found "MyString" instead
Test data have been erased and there are only "MyString" string data in test DB
Also, If I reopen the rails server in test env, I can see "MyString" data instead of my data.
If I replace again the test.sqlite3 with development.sqlite3 and I restart the server, I can see again my data correctly.
Currently I am not able to run any test because each time I run a test I have my db test.sqlite3 erased.
The magic point is that, after the test run the test.sqlite3 seem unchanged: the memory size of test.sqlite file is the same, so it seems it contains all data, but when I run the server I see only "MyString" value.
Looking at console, if I check the table content, I can see all filed to nil value except for the "name" field which contain "MyString" (instead of "Table element 1").

### System configuration
I am using rails 5.1.1

**Comment by y-yagi** [comment]
Perhaps I think there is fixtures in the test directory. 

Fixtures remove any existing data from the table corresponding to the fixture and load the fixture data into the table.
Please see: http://guides.rubyonrails.org/testing.html#fixtures-in-action for details.
