### ISSUE TITLE
ActiveStorage - should zero bytes attachments be allowed?

### ISSUE THREAD

**Issue by loop23** [rails/rails#31981]
### Steps to reproduce

Upload a zero bytes file, no errors are raised. This is almost always a (end)user error, maybe for some particular apps they make sense, but not in general.
Also, if zero bytes user uploads are questionable, zero bytes generated previews are even worse, as they generally point out to some issue with the previewer class

### Expected behavior
I would expect an exception being raised

**Comment by MicahBrown** [comment]
You can handle that in your own application via validation. I don't think default behavior should be to raise an exception because, for some cases, a zero byte file will be valid.

**Comment by sikachu** [comment]
Yep, zero byte file is considered valid. You should consider adding a validation for size or content type as that will prevent user from uploading a bad data.

**Comment by loop23** [comment]
You mean monkey patching the engine model?

**Comment by SampsonCrowley** [comment]
@sikachu how? according to: https://github.com/rails/rails/issues/31656 content type validations aren't supported. and maybe im alone in this, but i don't think validations belong in the controller

**Comment by CaioBianchi** [comment]
Feels odd not having validation being part of ActiveStorage.

**Comment by igorkasyanchuk** [comment]
I've created a simple gem with validations for Active Storage: https://github.com/igorkasyanchuk/active_storage_validations

Please try it and let me know if it works.

**Comment by mu-is-too-short** [comment]
@igorkasyanchuk But does that help with the harder issue? If you say:

    obj.image.attach(thing)
    obj.image.purge
    ...

and then validations on `obj` fail or `obj.save` fails in some other way (such as a constraint violation in the database) then nothing permanent should happen to `obj.image`.

Built-in validation support would be nice but forcing everyone to hack up their own two-phase commit system with an `around_save` seems a bit odd.

Am I missing something obvious or is ActiveStorage a little under done?
