### ISSUE TITLE
Add 'framework' topic to better categorize rails repository

### ISSUE THREAD

**Issue by plcosta** [rails/rails#31986]
It's a suggestion to edit the topics for the Rails repository.

![rails-repsoitory](https://user-images.githubusercontent.com/1139813/36108893-98f8cd3c-0ffc-11e8-81a2-1bf0b03d8fd9.png)

Rails doesn't turn up in this list: [https://github.com/topics/framework]( https://github.com/topics/framework?o=desc&s=stars), but others polular frameworks like Laravel and Django does.

My suggestion is to add the "framework" topic and make it more discoverable.

**Comment by rafaelfranca** [comment]
Thanks
