### ISSUE TITLE
Destroying all objects in through-association only destroys join table 

### ISSUE THREAD

**Issue by skyfmmf** [rails/rails#31980]
### Steps to reproduce
I have three models looking like this: 

```ruby
class City < ActiveRecord::Base
  has_many :buildings
  has_many :managers, :through => :buildings
end
class Building < ActiveRecord::Base
  belongs_to :city
  belongs_to :manager
end
class Manager < ActiveRecord::Base
  has_many :buildings
end
```

I try to destroy all managers in a city using `city.managers.destroy_all`. I've also created a test case using one of the templates: [https://gist.github.com/skyfmmf/83d18f81fd06b5ec0e52809c468e6292](https://gist.github.com/skyfmmf/83d18f81fd06b5ec0e52809c468e6292)

### Expected behavior
I would have expected that all the managers in the city would be gone afterwards but everything else is still there. 

### Actual behavior
Instead the buildings are deleted and the managers keep existing

### System configuration
**Rails version**: 5.1.4
**Ruby version**: 2.3.6

**Comment by georgeclaghorn** [comment]
This is the [documented behavior](http://api.rubyonrails.org/classes/ActiveRecord/Associations/ClassMethods.html#module-ActiveRecord::Associations::ClassMethods-label-What+gets+deleted-3F) of `destroy_all` on `has_many ..., through: ...` associations.
