### ISSUE TITLE
ActiveStorage - pdf previews not working on some environments

### ISSUE THREAD

**Issue by loop23** [rails/rails#31982]
### Steps to reproduce

Upload a valid pdf file and ask for a preview in a view

### Expected behavior
Should display the previewed version

### Actual behavior
a broken image is displayed, error logs contain misleading information

### System configuration
rails 5.2rc1 and 5.2 freeze
recent debian derived os's (discovered on google app engine flex env)

**Ruby version**:
n/a

### Notes

on debian and derived distros (and probably upstream) they changed the command for accessing the "generate image preview of pdf file" feature. While "mutool draw ..." used to work, apparently until 1.8, newer versions use the command "mudraw". Also, you can't invoke as "mudraw draw", something along:

```
$ mudraw draw  -F png -o - report.pdf 1 
nothing to do.. 
```

but returns a zero exit status (so cannot simply configure the command to use)

On a related note, I believe pdf_previewer.rb  could use something along:
```ruby
    def preview
      download_blob_to_tempfile do |input|
        draw_first_page_from input do |output|
          raise("size of preview is zero, no good!") if output.size == 0
          yield io: output, filename: "#{blob.filename.base}.png", content_type: "image/png"
        end
      end
    end
```

given mutools tendency to pretend all is well even when it itsn't at all.

**Comment by georgeclaghorn** [comment]
> While "mutool draw ..." used to work, apparently until 1.8, newer versions use the command "mudraw".

What version of MuPDF are you running? My recollection is the opposite: `mudraw` was folded into `mutool` in 1.8.

**Comment by loop23** [comment]
exact version is 1.5-1+deb8u3, deb package on google app engine base image, seems to come from debian jessie.. a bit old but not prehistoric!

**Comment by georgeclaghorn** [comment]
You’ll need to upgrade to at least 1.8.

**Comment by loop23** [comment]
unfortunately it isn't that easy in my environment - On google cloud (at least if you want to use app engine) you have to use a given base image to build your container upon. Or at least all of the documentation seems to point to that. So if/until the image is based on debian jessie I'm stuck on 1.5 for mupdf. I probably could force a newer version by either compiling from source or looking for a updated .deb in some repo during container build.. but I'd rather be able to (fully) configure the command the previewer uses, wouldn't you? ;)
Otherwise.. could it be possible to swap the pdf previewer for my own version with my custom command?

**Comment by georgeclaghorn** [comment]
> could it be possible to swap the pdf previewer for my own version with my custom command?

Yes, you can trivially do that by replacing `ActiveStorage::Previewer::PDFPreviewer` in `config.active_storage.previewers`.
