### ISSUE TITLE
Fish shell's $EDITOR setting doesn't appear to be recognized by `secrets:edit` command

### ISSUE THREAD

**Issue by AlanQuatermain** [rails/rails#31992]
### Steps to reproduce

Install [Fish Shell](http://fishshell.com) on macOS.

Set a value for $EDITOR globally, similar to:
`> set -U EDITOR "/usr/local/bin/mate -w"`

In a Rails project, run `bin/rails secrets:setup` if necessary, then run:
`> bin/rails secrets:edit`

### Expected behavior
The decrypted file should open in my chosen command-line editor (in this case, TextMate).

### Actual behavior
Instead, I get an error that $EDITOR is not set:

    No $EDITOR to open decrypted secrets in. Assign one like this:
    
    EDITOR="mate --wait" bin/rails secrets:edit
    
    For editors that fork and exit immediately, it's important to pass a wait flag,
    otherwise the secrets will be saved immediately with no chance to edit.

My shell definitely sees it, though:

    > echo $EDITOR
    /usr/local/bin/mate -w

I've tried adding a similar EDITOR specification to my `.bashrc` and that definitely shows up when I open a bash shell. I'm unclear where else it might need to be set, though— it *ought* to pick up the environment from the shell process executing the original `bin/rails` command.

### System configuration
**Rails version**:
Rails 5.1.4

**Ruby version**:
ruby 2.4.1p111 (2017-03-22 revision 58053) [x86_64-darwin16]

**Comment by AlanQuatermain** [comment]
Of course, after much searching, I find the PEBKAC answer thirty seconds after filing a bug. I needed the -x flag to have my EDITOR exported to child processes. Sigh.

**Comment by Willardgmoore** [comment]
I'm having what looks like the same problem and I still don't have a solution.

**Comment by ksylvest** [comment]
For anyone who runs into this issue - the correct way to run with fish is:

```fish
set -x EDITOR "atom --wait"; bin/rails credentials:edit
```
