### ISSUE TITLE
ActiveRecord::Relation.cache_key produces same key on different results when using limit

### ISSUE THREAD

**Issue by krainboltgreene** [rails/rails#31996]
# Steps to reproduce

Okay so recently my company wanted to start using the collection cache key before rails 5 (we're just about to upgrade from 4.2 to rails 5 on one of our services), so I was tasked with backporting it by hand. I feel like I did a *pretty good* job, but we encountered something that I believe still exists in the current live implementation.

Let's go through a scenario to get a scope of things:

  1. First you have a table with some data, I've shortened the 'updated-at' to relative for human consumption.

  ``` sql
  SELECT * FROM records ORDER BY id ASC
  ```

  id|position|valid|updated_at
  -|-|-|-
  a|2|t|2018-03-08 01:59:18.944702
  b|3|t|2018-03-08 01:59:45.332233
  c|1|t|2018-03-08 01:59:43.751097
  d|4|t|2018-03-08 01:59:45.332233

  2. Now we make a sufficiently complex query involving a `WHERE`, `ORDER BY`, and `LIMIT`:

  ``` sql
  SELECT * FROM records WHERE valid is true ORDER BY position DESC LIMIT 3
  ```

  id | position | valid | updated_at
  -|-|-|-
  c | 1 | t | 2018-03-08 01:59:43.751097
  a | 2 | t | 2018-03-08 01:59:18.944702
  b | 3 | t | 2018-03-08 01:59:45.332233

  3. So lets create our cache key:

  ``` ruby
  relation.cache_key
  ```

  ``` sql
  SELECT COUNT(*), MAX(updated_at) FROM (SELECT updated_at FROM records WHERE valid is true ORDER BY position DESC LIMIT 3)
  ```

  updated_at
  -|
  2018-03-08 01:59:43.751097
  2018-03-08 01:59:18.944702
  2018-03-08 01:59:45.332233

  size|max
  -|-
  3|2018-03-08 01:59:43.751097

  ``` ruby
  ["records", "collection", checksum, 3, 2018-03-08 01:59:45.332233]
  ```

  4. Now let's do a mutation:

  ``` ruby
  Record.find(id: "b").update(position: 5)
  ```

  ``` sql
  UPDATE position=5, updated_at=2018-03-08 02:01:58.519036 WHERE id = b
  ```

  id|position|valid|updated_at
  -|-|-|-
  a|2|t|2018-03-08 01:59:18.944702
  b|5|t|2018-03-08 02:01:58.519036
  c|1|t|2018-03-08 01:59:43.751097
  d|4|t|2018-03-08 01:59:45.332233

  5. And our query (where `b` no longer exists):

  ``` sql
  SELECT * FROM records WHERE valid is true ORDER BY position DESC LIMIT 3
  ```

  id|position|valid|updated_at
  -|-|-|-
  c|1|t|2018-03-08 01:59:43.751097
  a|2|t|2018-03-08 01:59:18.944702
  d|4|t|2018-03-08 01:59:45.332233

  6. And our collection cache key query:

  ``` ruby
  relation.cache_key
  ```

  ``` sql
  SELECT COUNT(*), MAX(updated_at) FROM (SELECT updated_at FROM records WHERE valid is true ORDER BY position DESC LIMIT 3)
  ```

  updated_at
  -|
  2018-03-08 01:59:43.751097
  2018-03-08 01:59:18.944702
  2018-03-08 01:59:45.332233

  size|max
  -|-
  3|2018-03-08 01:59:45.332233

  ``` ruby
  ["records", "collection", checksum, 3, 2018-03-08 01:59:45.332233]
  ```

As you can see from above, our query cache key has *not changed*, but our set of data absolutely has changed. Am I missing something? For what it's worth, I've compared *my implementation* to Rails 5.1 and they produce semantically the same queries and the exact same results (both the query and the collection cache query).

## Expected behavior

It should create a cache key that changes since the items have changed.

## Actual behavior
The cache key is exactly the same.

## System configuration
**Rails version**: 4.2 .. 5.1 (Maybe 5.2)

**Ruby version**: Agnostic

**Comment by eugeneius** [comment]
The [documentation for `ActiveRecord::Relation#cache_key`](https://github.com/rails/rails/blob/6ccd2b0efdfb8e9ef41764ee60dfac9731338608/activerecord/lib/active_record/relation.rb#L299-L303) says:

> The cache key is built with a fingerprint of the sql query, the number of records matched by the query **and a timestamp of the last updated record**.

Moving `updated_at` back in time, or even updating a record without touching `updated_at`, means the cache key won't change. Maybe we need to document that restriction, but I don't think it's a bug; it's optimising for the common case where all updates will move the maximum `updated_at` forward.

**Comment by krainboltgreene** [comment]
> back in time, or even updating a record without touching updated_at

I want to be clear, this is not happening in my example.

**Comment by krainboltgreene** [comment]
I've updated the ticket with tables, some corrections to the generated SQL, and some clarifications.

**Comment by krainboltgreene** [comment]
I've removed some typos and made the case example a lot easier to understand, thanks @7sun

**Comment by matthewd** [comment]
Related: #21503 #27570 #28075

**Comment by krainboltgreene** [comment]
For what it's worth I wrote an implementation that works in postgres and might work in other databases.

**Comment by krainboltgreene** [comment]
To be clear, unlike the other PR's it uses a checksum of the primary keys at the database level rather than the ActiveRecord level.

**Comment by sikachu** [comment]
I can see that this is happening though.

There are two parts of the problem:

1. The relation result is being cached since step 2, and an update to the database won't reflect the result in the relation object — I think that's a common pitfall, but it's pretty much how it works (since we don't have identity map 😅)

2. I actually found something interesting for `#cache_key`. Looking at source code, it seems like it's being [memoized](https://github.com/rails/rails/blob/0e8d4edd56f44b27f33bd214aa03af60cc5d39ae/activerecord/lib/active_record/relation.rb#L320-L323) after it's being calculated the first time. It [also does not get reset](https://github.com/rails/rails/blob/0e8d4edd56f44b27f33bd214aa03af60cc5d39ae/activerecord/lib/active_record/relation.rb#L557) in `relation.reset` method either.

I think the obvious fix is to make it unset `@cache_keys` when `relation.reset` got called. While this won't fix the scenario described in this PR (as `relation` result would still get cached so any update in the database doesn't reflect on the result), it will work as expected when user explicitly calling `relation.reset` before trying another `relation.cache_key`.

Here's some example on what I mean, with SQL logging to STDOUT on:

```
> users = User.all.select(:id).limit(5); false # false is here so it won't call #inspect on relation
#=> false
> users.cache_key
  [slave/1] (0.5ms)  SELECT COUNT(*) AS `size`, MAX(subquery_for_cache_key.updated_at) AS timestamp FROM (SELECT  `users`.`updated_at` FROM `users` LIMIT 5) subquery_for_cache_key
#=> "users/query-e91b2169cd0011244de33facd07a4a62-5-20180207064812000000"
> users.cache_key
#=> "users/query-e91b2169cd0011244de33facd07a4a62-5-20180207064812000000"
# *** no SQL before this line = no reload ***

> users.reset; false
#=> false
> users.cache_key
#=> "users/query-e91b2169cd0011244de33facd07a4a62-5-20180207064812000000"
# *** Still no reload ***

> users.instance_variable_set(:"@cache_keys", nil)
#=> nil
> users.cache_key
  [slave/1] (0.4ms)  SELECT COUNT(*) AS `size`, MAX(subquery_for_cache_key.updated_at) AS timestamp FROM (SELECT  `users`.`updated_at` FROM `users` LIMIT 5) subquery_for_cache_key
#=> "users/query-e91b2169cd0011244de33facd07a4a62-5-20180207064812000000"
# *** It reloaded ***
```

Please let me know if you plan to submit a patch to fix this.

**Comment by krainboltgreene** [comment]
The described issue is not a memoization issue, but faulty cache key logic.

**Comment by krainboltgreene** [comment]
Updated the example.

**Comment by sikachu** [comment]
Okay, I think I agree that the cache key should be changed. However, it seems like we need to pretty much change the way we compute the cache key, right? I wonder how we can archive that without actually looking inside the result and generate some kind of checksum, which sounds very expensive ...

Do you have any suggestion on how we should fix this?

**Comment by krainboltgreene** [comment]
There have been a lot of suggestions, but ultimately I believe it's impossible without looking at the content because we're ultimately talking about content operators (`ORDER`, `LIMIT`, `GROUP`).

That said, while we use the checksum option in my company's application we have a warning if the size (cached) is greater than 500k. It's too much in memory.
