### ISSUE TITLE
Very minor suggestion - method alias on Object#presence

### ISSUE THREAD

**Issue by andyjeffries** [rails/rails#32009]
I was just wondering if there was any support for aliasing `Object#presence` to `Object#if_present`. The code sample reads a lot better to me using that name:

```ruby
region = params[:state].if_present || params[:country].if_present || 'US'
```

It reads like "use this if it's present, or this if it's present, or 'US'".

**Comment by giovannibenussi** [comment]
Hi @andyjeffries!
I also think that the name `presence` isn't too self explanatory and that your example at least reads better than using `presence`.

+1 for this

**Comment by rafaelfranca** [comment]
Thank you so much for the issue but we don't take feature request on the issue tracker. We recommend you to try to implement the feature and send us a pull request or if you are in doubt if the feature will be accepts ask in Rails Core mailing list for feedback.

**Comment by andyjeffries** [comment]
Thanks @rafaelfranca - I thought it was more polite to ask first, but I guess code speaks. Pull request created - https://github.com/rails/rails/pull/32043
