### ISSUE TITLE
All tests are run (and fail) if fixtures fail database constraints (regression from 5.1.4)

### ISSUE THREAD

**Issue by jeffblake** [rails/rails#32000]
### Steps to reproduce

I made a quick app here: https://github.com/jeffblake/fixture-regression

(Guidelines for creating a bug report are [available
here](http://guides.rubyonrails.org/contributing_to_ruby_on_rails.html#creating-a-bug-report))

### Expected behavior

Running `rails test` should fail immediately if fixtures fail database constraints

### Actual behavior

All tests are run, and fail due to database constraints

<img width="1267" alt="screen shot 2018-02-14 at 8 42 30 pm" src="https://user-images.githubusercontent.com/620564/36240579-9e9b5562-11c7-11e8-9793-7ad38cefcf61.png">

### System configuration
**Rails version**:

5.1.5

**Ruby version**:

2.5.0

**Comment by jeffblake** [comment]
Running it on rails 5.1.4 I get:

<img width="1261" alt="screen shot 2018-02-14 at 8 39 33 pm" src="https://user-images.githubusercontent.com/620564/36240528-4535dd30-11c7-11e8-8707-6fadf37c75ed.png">

Maybe this is actually due to the minitest bug that was fixed. What is expected behavior here? It would sure be nice if the suite fails immediately... I don't see a point in running a whole test suite if the fixtures are bad.

**Comment by y-yagi** [comment]
Fixture's insert is done at the time of each test run, so this is the expected behavior for now.
If you want to stop the test immediately if something goes wrong, use the `--fail-fast` option.
