### ISSUE TITLE
Possible regression of HWIA#transform_keys in rails 5.2.0.rc1

### ISSUE THREAD

**Issue by eitoball** [rails/rails#32007]
### Steps to reproduce

1. Use ruby 2.5.0
1. Create an instance of `HashWithIndifferentAccess`
1. Convert keys to `Symbol`

```
hsh = {a: 1}.with_indifferent_access
hsh = hsh.transform_keys { |_| :b }
```

### Expected behavior

Return some value if given key exists in `String` and `Symbol`. In example above, `hsh['b']` and `hsh[:b]` should return `1`.

### Actual behavior

Return `nil`

I think than since [this commit](https://github.com/rails/rails/commit/de9e3238a008f8f20c5beedefb8787b6e51359d0#diff-9f4b3d7342097a6f22290f147a09b77b), `HWIA#transform_keys` returns a `HWIA`, but it uses ruby's `Hash#transform_keys!` on ruby 2.5.0.

### System configuration
**Rails version**: Rails 5.2.0.rc1

**Ruby version**: ruby 2.5.0p0 (2017-12-25 revision 61468) [x86_64-darwin15]

**Comment by rafaelfranca** [comment]
This feel more like an issue with Ruby 2.5.0 than with Rails. Can you report to Ruby? It looks like that their `transform_keys =` don't use the `[]=` method to set the value.

**Comment by eitoball** [comment]
> Can you report to Ruby? It looks like that their transform_keys = don't use the []= method to set the value.

I will report it ruby-core. But I don't think that it is necessary to use `[]=` to convert keys.
