### ISSUE TITLE
Array routing constraints do not work

### ISSUE THREAD

**Issue by jcoyne** [rails/rails#32013]
### Steps to reproduce

When I have this routing code:

```ruby
Rails.application.routes.draw do
  scope '/(:locale)', constraints: { locale: %w[en de es fr dk] } do
    root to: 'home#index'
  end
end
```

And I make the request: `GET /de` then I get an error: 
```
Routing Error
No route matches [GET] "/de"
```

However if I change the constraint to be a regex like this:
```ruby
Rails.application.routes.draw do
  scope '/(:locale)', constraints: { locale: /(en|de|es|fr|dk)/ } do
    root to: 'home#index'
  end
end
```

Then my `GET /de` request works fine and routes to `home#index`

I believe this feature was originally added here: https://github.com/rails/rails/commit/90d2802b71a6e89aedfe40564a37bd35f777e541

### System configuration
**Rails version**: 5.2.0.rc1

**Ruby version**: 2.4.3

**Comment by claudiob** [comment]
@jcoyne I wasn't able to reproduce the expected behavior that you describe.

In which version of Rails was `locale: %w[en de es fr dk]` working?

The commit you pointed to (90d2802) might not be the one that changed the behavior, since the comment says:

> Note that this only applies to constraints on the request - path constraints still need to be specified as Regexps as the various constraints are compiled into a single Regexp.

**Comment by jcoyne** [comment]
I've never seen this working before, I just saw this while reading the code that @pixeltrix added and was going to test it out and add some documentation about it.  Maybe @pixeltrix could explain how it's supposed to work?  If it's not supported, maybe something should be added to warn about the expected format for the constraints parameter.

**Comment by fatkodima** [comment]
Reproduced this issue and looks like have found the problem, so preparing a PR.
