### ISSUE TITLE
Rails 5.2 Dangerous query method called with non-attribute arguments

### ISSUE THREAD

**Issue by pzupan** [rails/rails#32011]
Rails: 5.2.0.rc1
Ruby: 2.5.0

I'm getting a deprecation warning for sql pass through on the order method.

DEPRECATION WARNING: Dangerous query method (method whose arguments are used as raw SQL) called with non-attribute argument(s): "NULLIF(regexp_replace(penalty_reports.item_no, E'\\D', '', 'g'), '')::int ?, penalty_reports.created_at DESC". Non-attribute arguments will be disallowed in Rails 6.0. This method should not be called with user-provided values, such as request parameters or model attributes. Known-safe values can be passed by wrapping them in Arel.sql(). 

The offending method is:

`order("NULLIF(regexp_replace(penalty_reports.item_no, E'\\D', '', 'g'), '')::int #{direction}, penalty_reports.created_at DESC")`

It seems it doesn't like the insertion of the direction parameter.

**Comment by georgeclaghorn** [comment]
If you know `direction` to be safe, wrap the order clause in `Arel.sql` as the warning instructs:

```ruby
order(Arel.sql("NULLIF(regexp_replace(penalty_reports.item_no, E'\\D', '', 'g'), '')::int #{direction}, penalty_reports.created_at DESC"))
```
