### ISSUE TITLE
store_accessor fields callback/validations run in wrong order

### ISSUE THREAD

**Issue by kgathi2** [rails/rails#32010]
### Steps to reproduce
It seems to me that if an object validation fails, callback for after validation should not be run. Is this not the case?

```ruby
class Test < ApplicationRecord
  # Database Columns
  # station_id: integer
  # data: jsonb
  store_accessor :data, :station

  after_validation :initialize_station

  validates_presence_of :station

  private

  def initialize_station
    self.station_id = station[:id]
  end
end
```
(Guidelines for creating a bug report are [available
here](http://guides.rubyonrails.org/contributing_to_ruby_on_rails.html#creating-a-bug-report))

### Expected behavior
Tell us what should happen

```ruby
user = Test.new(station: { id: 1, name: 'Some name' })
user.valid? #=> true
user = Test.new()
user.valid? #=> false because station is missing
```

### Actual behavior
Tell us what happens instead

```ruby
user = Test.new(station: { id: 1, name: 'Some name' })
user.valid? #=> true
user = Test.new()
user.valid? 
#=> NoMethodError: undefined method `[]' for nil:NilClass
#=> app/models/user.rb:14:in `initialize_station'
```

### System configuration
**Rails version**:
5.1.4
**Ruby version**:
2.5.0

**Comment by y-yagi** [comment]
This is intended behavior. `after_validation` is called regardless of the result of validation. 
If you do not want to process if validation fails, please check whether `errors` is an empty inside method. 
Ref: http://api.rubyonrails.org/classes/ActiveModel/Validations/Callbacks/ClassMethods.html#method-i-after_validation
