### ISSUE TITLE
`include` on one line shows different behavior than separate `include` statements

### ISSUE THREAD

**Issue by cannikin** [rails/rails#32023]
This is going to sound impossible but I ran it by @tenderlove and he agreed that it sounded like a [bug](https://twitter.com/tenderlove/status/964576299825053697) It seems hard to believe that it could be a bug in Ruby after all these years of usage, so I thought I would start here first since I discovered it when writing some Rails tests.

Run the following in a Rails console:

```ruby
class BustedInclude
  include ActiveModel::Validations, ActiveModel::Validations::Callbacks
  before_validation { puts 'Callback!' }
end

instance = BustedInclude.new
instance.valid? # outputs only `true`

class WorkingInclude
  include ActiveModel::Validations
  include ActiveModel::Validations::Callbacks
  before_validation { puts 'Callback!' }
end

instance = WorkingInclude.new
instance.valid? # outputs "Callback!" and then `true`
```

As you can see the only difference between these two is a one-line`include` statement vs two separate calls.

As I dug into this I found that `ActiveModel::Validations::Callbacks.run_callbacks!` is supposed to override `ActiveModel::Validations.run_callbacks!`. When I stepped through in the debugger the overriding version declared in `Callbacks` is never called, it only enters the original definition in `Validations`.

### Expected behavior

Both versions should output "Callback!" in the console.

### Actual behavior

Only the `WorkingInclude` instance outputs "Callback!", the other just outputs `true`.

### System configuration

**Rails version**: 5.1.4

**Ruby version**: 2.5.0

**Comment by rafaelfranca** [comment]
Given you already debugged and investigated how do you recommend us to fix this? I don't think this is a bug in the rails code. If ruby is not allowing a method to be overridden because the module was included in the same `include` call of the other module I think it is a Ruby issue.

**Comment by rafaelfranca** [comment]
Ah, just saw the reason. The modules are inserted in reverse order

```
include(module, ...) → self
Invokes Module.append_features on each parameter in reverse order.
```

So:

```
class BustedInclude
  include ActiveModel::Validations, ActiveModel::Validations::Callbacks
  before_validation { puts 'Callback!' }
end
```

is equivalent to:

```
class BustedInclude
  include ActiveModel::Validations::Callbacks
  include ActiveModel::Validations
  before_validation { puts 'Callback!' }
end
```

**Comment by cannikin** [comment]
Huh, strangely counter-intuitive, but I’ll never forget that now! Sorry for wasting your time there, and thanks for taking the extra time to find the reason. :)

**Comment by rafaelfranca** [comment]
No problem at all. I also learned that just now.
