### ISSUE TITLE
Possible regression of `after_rollback on: :update` and `after_rollback on: :destroy` is not working

### ISSUE THREAD

**Issue by fatkodima** [rails/rails#32035]
### Steps to reproduce

By bisecting I have found, that regression was introduced some time ago (starting from 5.1.0) in this PR https://github.com/rails/rails/pull/27248.

When model fails to update, `after_rollback .. on: :update` should be called, if defined. While `after_rollback .. on: :create` works as expected, `after_rollback .. on: :destroy` is not working neither on master, nor in 5.0.6.

```ruby
# frozen_string_literal: true

begin
  require "bundler/inline"
rescue LoadError => e
  $stderr.puts "Bundler version 1.10 or later is required. Please update your Bundler"
  raise e
end

gemfile(true) do
  source "https://rubygems.org"

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  gem "activerecord", "5.0.6"
  gem "sqlite3"
end

require "active_record"
require "minitest/autorun"
require "logger"

# Ensure backward compatibility with Minitest 4
Minitest::Test = MiniTest::Unit::TestCase unless defined?(Minitest::Test)

# This connection will do for database-independent bug reports.
ActiveRecord::Base.establish_connection(adapter: "sqlite3", database: ":memory:")
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :users, force: true do |t|
    t.string :name
  end
end

class User < ActiveRecord::Base
  validates :name, presence: true

  before_update  :raise_rollback!
  before_destroy :raise_rollback!

  after_rollback(on: :create) { |record| record.do_after_rollback(:create) }
  after_rollback(on: :update) { |record| record.do_after_rollback(:update) }
  after_rollback(on: :destroy) { |record| record.do_after_rollback(:destroy) }

  def after_rollback_block(on, &block)
    @after_rollback ||= {}
    @after_rollback[on] ||= []
    @after_rollback[on] << block
  end

  def do_after_rollback(on)
    blocks = @after_rollback[on] if defined?(@after_rollback)
    blocks.each { |b| b.call(self) } if blocks
  end

  def history
    @history ||= []
  end

  def raise_rollback!
    raise ActiveRecord::Rollback
  end
end

class BugTest < Minitest::Test
  def test_after_rollback_on_create_was_called
    user = User.new
    user.after_rollback_block(:create) { |u| u.history << :after_rollback_on_create }
    user.save

    # works on 5.0.6 and master
    assert_equal [:after_rollback_on_create], user.history
  end

  def test_after_rollback_on_update_was_called
    user = User.create(name: "john")
    user.after_rollback_block(:update) { |u| u.history << :after_rollback_on_update }
    user.save

    # works on 5.0.6, fails on master
    assert_equal [:after_rollback_on_update], user.history
  end

  def test_after_rollback_on_destroy_was_called
    user = User.create(name: "john")
    user.after_rollback_block(:destroy) { |u| u.history << :after_rollback_on_destroy }
    user.destroy

    # fails on 5.0.6 and master
    assert_equal [:after_rollback_on_destroy], user.history
  end
end
```

### Expected behavior
When model fails to update/destroy, `after_rollback .. on: :update`/`after_rollback .. on: :destroy` should be called.

### Actual behavior
Callbacks are not called.

Related https://github.com/rails/rails/issues/7640.

### System configuration
**Rails version**: master

**Ruby version**: 2.4.1

**Comment by eugeneius** [comment]
> When model fails to update, `after_rollback .. on: :update` should be called

The documentation [actually says](http://api.rubyonrails.org/v5.2.0/classes/ActiveRecord/Transactions/ClassMethods.html#module-ActiveRecord::Transactions::ClassMethods-label-Callbacks):

> `after_rollback` callbacks are called on every record saved or destroyed within a transaction immediately after the transaction or savepoint is rolled back.

If the call to save is cancelled by a `before_save` callback, the record hasn't been saved, and I wouldn't expect its `after_rollback` callbacks to run. In my opinion it's the `on: :create` behaviour that's incorrect here: if the record was never inserted into the database, it can't have been rolled back.

Did this change in behaviour cause a bug in your application? If so, could you share more details?
