### ISSUE TITLE
ActiveStorage fails when a model concern Identifiable exists

### ISSUE THREAD

**Issue by OyoKooN** [rails/rails#32040]
### Steps to reproduce

When you have a model concern in your app with the same name as one of the three included in `ActiveStorage::Blob`, an error may occurs. 

In my case, I have a the following concern:

```
module Identifiable
  extend ActiveSupport::Concern

  included do
    # Validations
    validates_presence_of :first_name, :last_name, :email
  end
end
```

### Expected behavior

My model should be saved and the files uploaded.

### Actual behavior

I get the error `undefined method 'first_name' for #<ActiveStorage::Blob:0x00007f87d0132388>` which is triggered by the validation in my concern.

### System configuration
**Rails version**: 5.2.0.rc1

**Ruby version**: 2.5.0p0

**Comment by georgeclaghorn** [comment]
This was fixed in #31968 and #31995. Those changes will be included in the next RC.

Bundle Rails from the `5-2-stable` branch to get the fixes now.
