### ISSUE TITLE
.text_area and text_area_tag always append 1 whitespace to begin of string when use Slim

### ISSUE THREAD

**Issue by rsmything** [rails/rails#32057]
**.text_area** and **text_area_tag** always append 1 whitespace to begin of string when use **Slim**

<textarea maxlength="200" name="hint[one]" id="hint_one"**> Why?<**/textarea>

rails 5-2-stable - f45a3f89ab92efc7f45bf4891f93fb38a76c6f5e
slim 3.0.9
ruby 2.5

**Comment by pixeltrix** [comment]
Thanks for the report @rsmything but unless you can identify where this extra space is being added in Rails I would suggest reporting it on the [Slim repo][1] first.

Looking at the source code for `text_area_tag` it just takes the passed in content and calls `content_tag` after marking it as HTML safe so difficult to see anywhere this could be a Rails problem.

[1]: https://github.com/slim-template/slim
