### ISSUE TITLE
Duplicated .js files content from public server

### ISSUE THREAD

**Issue by tomascharad** [rails/rails#32068]
### Steps to reproduce

Here is a sample with the error:  https://github.com/tomascharad/rails-public-js-files-duplication

1. Start the server (`rails s`)
2. Open your chrome network tab
3. Enable "Disable cache"
4. Enable "Slow 3G" network throttling
![image](https://user-images.githubusercontent.com/1534092/36423643-8895e744-161f-11e8-9a25-cd9574ac4e9d.png)
5. Hit Refresh
6. Before angular or main.d90603e7e9c46c1577d5.bundle.js get completely loaded:
6.1. Disable "Disable cache"
![image](https://user-images.githubusercontent.com/1534092/36423291-1ca555f2-161e-11e8-9618-f5554dad5482.png)
6.2. Hit Refresh again
7. Wait until the js files load partially (Be sure to not load them completely)
![image](https://user-images.githubusercontent.com/1534092/36423429-b7085176-161e-11e8-8dd5-029576bd3ec9.png)
8. Keep hiting refresh and loading these two files partially

9. Now two things can happen, If you successfully duplicated the files:
9.1. And keep hitting refresh, at one moment the files are going to throw error
9.2 If you load them completely, they will throw error

![image](https://user-images.githubusercontent.com/1534092/36423501-f3b1d2d2-161e-11e8-8c53-05645b976aba.png)
9.3: I believe that there is something wrong in the file size calculation in `Content-Range` header
![image](https://user-images.githubusercontent.com/1534092/36423798-fae006fe-161f-11e8-88dc-bd8baa53e877.png)

10. The error will change depending with the duplication
11. If you hit refresh now, with "Disable cache" Disabled, then the error doesn't leave
11.1: Note that files are loaded from "Memory cache"

![image](https://user-images.githubusercontent.com/1534092/36423531-1740314e-161f-11e8-804c-8bdcf394760e.png)

12. This also happen with only one file, I just left two for isolating the cause to rails public server.

### Expected behavior
Files shouldn't get duplicated.

### Actual behavior
The js files get duplicated like and they start throwing errors, after this happened, the browser caches them so its impossible for the end user to recover from that state:

![image](https://user-images.githubusercontent.com/1534092/36423207-b6aaa630-161d-11e8-8a09-e5a331d995ec.png)

### System configuration
**Rails version**:
rails (5.1.2)
**Ruby version**:
ruby 2.4.1p111

**Comment by pixeltrix** [comment]
After removing all the third-party gems and their respective initializers I finally managed to replicate the problem.

Turns out that this is cause by rack/rack@e0ac329 - the alias of `to_path` means that the rack handler for webrick just passes the file object back as the body and it loses the offset so reads from the beginning of the file.

Have you tried using puma instead of webrick?

**Comment by tomascharad** [comment]
Many thanks @pixeltrix 

I think I haven't been able to reproduce it from a new rails environment.
Will try to change to puma and let you know.
Many thanks.

**Comment by pixeltrix** [comment]
Closing since this is a problem in Rack: rack/rack#1235

**Comment by tomascharad** [comment]
Many thanks @pixeltrix
