### ISSUE TITLE
Active Storage/s3_service requires s3:ListBucket premission for exists?

### ISSUE THREAD

**Issue by mfazekas** [rails/rails#32066]
### Steps to reproduce

Use active storage variants on S3 when you have `s3:GetObject` but no `s3:ListBucket` permission

### Expected behavior
Tell us what should happen

I'd expect active storage to work with only `s3:GetObject` permissions

### Actual behavior
Tell us what happens instead. Following error is raised:

```
     
  Aws::S3::Errors::Forbidden (): 
     
  vendor/bundle/ruby/2.4.0/gems/aws-sdk-s3-1.8.0/lib/aws-sdk-s3/object.rb:262:in `rescue in exists?' 
  vendor/bundle/ruby/2.4.0/gems/aws-sdk-s3-1.8.0/lib/aws-sdk-s3/object.rb:258:in `exists?' 
  vendor/bundle/ruby/2.4.0/gems/activestorage-5.2.0.beta2/lib/active_storage/service/s3_service.rb:49:in `block in exist?' 
  vendor/bundle/ruby/2.4.0/gems/appsignal-2.4.3/lib/appsignal/hooks/active_support_notifications.rb:19:in `block in instrument' 
  vendor/bundle/ruby/2.4.0/gems/activesupport-5.2.0.beta2/lib/active_support/notifications/instrumenter.rb:23:in `instrument' 
  vendor/bundle/ruby/2.4.0/gems/appsignal-2.4.3/lib/appsignal/hooks/active_support_notifications.rb:36:in `instrument' 
  vendor/bundle/ruby/2.4.0/gems/appsignal-2.4.3/lib/appsignal/hooks/active_support_notifications.rb:18:in `instrument' 
  vendor/bundle/ruby/2.4.0/gems/activestorage-5.2.0.beta2/lib/active_storage/service.rb:108:in `instrument' 
  vendor/bundle/ruby/2.4.0/gems/activestorage-5.2.0.beta2/lib/active_storage/service/s3_service.rb:48:in `exist?' 
  vendor/bundle/ruby/2.4.0/gems/activestorage-5.2.0.beta2/app/models/active_storage/variant.rb:75:in `processed?' 
  vendor/bundle/ruby/2.4.0/gems/activestorage-5.2.0.beta2/app/models/active_storage/variant.rb:47:in `processed' 
```

### System configuration
**Rails version**: Rails 5.2.0.beta2
**Ruby version**: ruby 2.4.0p0

**Comment by mfazekas** [comment]
According to s3 documentation operation can raise "access denied"  when you have no `s3:ListBucket` permission, i think s3 service could handle that case, as AFAIK it doesn't needs list premissions.

https://docs.aws.amazon.com/AmazonS3/latest/API/RESTObjectGET.html

> If the object you request does not exist, the error Amazon S3 returns depends on whether you also have the s3:ListBucket permission.
>
>    If you have the s3:ListBucket permission on the bucket, Amazon S3 will return an HTTP status code 404 ("no such key") error.
>
>   if you don’t have the s3:ListBucket permission, Amazon S3 will return an HTTP status code 403 ("access denied") error.

**Comment by pixeltrix** [comment]
@mfazekas from that documentation it seems there's no way to definitively tell whether an object exists if you don't have ListBucket permission. It would seem dangerous to capture the 403 error and return false for `exists?` since that could lead to uploads being overwritten.

**Comment by mfazekas** [comment]
@pixeltrix if you have s3:GetObject then `exists?` should return true if the file is there. 

```
irb(main):004:0> variant.service.send(:object_for,"foo").exists?
Aws::S3::Errors::Forbidden: 
	from (irb):4
irb(main):005:0> variant.service.send(:object_for,"foo").put(body:"foo")
=> #<struct Aws::S3::Types::PutObjectOutput expiration=nil, etag="\"acbd18db4cc2f85cedef654fccc4a4d8\"", server_side_encryption=nil, version_id=nil, sse_customer_algorithm=nil, sse_customer_key_md5=nil, ssekms_key_id=nil, request_charged=nil>
irb(main):006:0> variant.service.send(:object_for,"foo").exists?
=> true
```

I assume if you don't have `s3:GetObject` but you have `s3:PutObject` permissions then, yes could overwrite, but as i understand this is path is only used on variants/previews so in that case you need to download to original to resize, if you don't have permission for that then you won't get to the upload which would overwrite.

**Comment by pixeltrix** [comment]
@mfazekas whilst I accept that currently it's probably not going to cause a problem if we assume that 403 is really a 404 error,  the `ActiveStorage::Service#exist?` method is a documented public API so may be used by application developers. Is there a reason why you wouldn't grant `ListBucket` permission to the application - either via an IAM instance profile or an explicit bucket policy for specific IP addresses.

**Comment by mfazekas** [comment]
Sure we can give reconfigure our s3 so we have `ListBucket`, we're migrating from Shrine and it was working fine with current permissions.

It think it would be nice if ActiveStorage could work with only Get and PutObject permissions and did not require ListBucket, as it could be implemented without it.

I'd argue it's fine for the `ActiveStorage::Service#exist?` to be implemented the way it's ideal for `ActiveStorage`. That is to return `false` even in case the file is there but you don't either `list` or `get` permission. In a concurrent environment `put(p,data) unless exists?(p)`  can be an overwrite with the current semantics too.

Feel free to close the issue if you disagree.

**Comment by pixeltrix** [comment]
@mfazekas turns out we need `ListObject` to batch delete all the variants: https://github.com/rails/rails/blob/c42dafd437f6392bf0fb41ac751a8e231940b67e/activestorage/lib/active_storage/service/s3_service.rb#L49

We should document this though, so thanks for the report.

**Comment by mfazekas** [comment]
Yes you're right, i've overlooked deletion: it does require `List` permissions, thanks for pointing this out.

**Comment by estani** [comment]
It took me forever to find this one. In case someone ends up here, and cannot find a solution:
The `S3:ListBucket` permission requirement means you need to provide access to the whole bucket resource, this is different from granting `S3:GetObject` where a key prefix is defined as well.

See how the resource is written differently.
```js
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Effect": "Allow",
      "Action": ["s3:ListBucket"],
      "Resource": ["arn:aws:s3:::test"]
    },
    {
      "Effect": "Allow",
      "Action": [
        "s3:PutObject",
        "s3:GetObject",
        "s3:DeleteObject"
      ],
      "Resource": ["arn:aws:s3:::test/*"]
    }
  ]
}
```
https://aws.amazon.com/de/blogs/security/writing-iam-policies-how-to-grant-access-to-an-amazon-s3-bucket/
