### ISSUE TITLE
Cache key on 5.2.0.rc1

### ISSUE THREAD

**Issue by arni1981** [rails/rails#32061]
### Steps to reproduce
`<% cache @group %>`

No longer includes the updated_at in the cache_key in 5.2.0.rc1

### Expected behavior
This is an example of a generated key in 5.2.0.beta2
`groups/show:b25ce2a718e61c4980803b1b01b4d28a/groups/3-20180219205350119722`

### Actual behavior
The same command in 5.2.0.rc1 does not include the updated_at and therefore is stale even though the record is updated
`groups/show:d8f81a8f744c2141d7eb53baca7d32fa/groups/3`

I have not enabled this line in the `initializers/new_framework_defaults_5_2.rb` file
`# Rails.application.config.active_record.cache_versioning = true`

I'm using `:redis_store`

**Comment by eugeneius** [comment]
See https://github.com/rails/rails/issues/31897; the `redis_store` adapter is provided by the [redis-activesupport](https://github.com/redis-store/redis-activesupport) gem, which isn't maintained by the Rails team. This issue should be reported there instead.

**Comment by tubbo** [comment]
On a new Rails 5.2.0.rc1 application, this is what I get when I set `config.cache_store = :memory_store` and `config.load_defaults 5.2`:

```
irb(main):002:0> Project.first.cache_key
  Project Load (0.5ms)  SELECT  "projects".* FROM "projects" ORDER BY "projects"."id" ASC LIMIT $1  [["LIMIT", 1]]
=> "projects/1"
```

This doesn't seem like it's isolated to redis-activesupport, since I can reproduce it without that gem in use/installed.

**Comment by georgeclaghorn** [comment]
That’s the expected behavior. `ActiveRecord::Base#cache_key_with_version` includes the timestamp.

**Comment by tubbo** [comment]
That makes sense @georgeclaghorn, but I don't think `ActiveSupport::Base#cache_key_with_version` is being used here in `ActiveSupport::Cache::Store#fetch`, because when I inspect the key used in my logs I see this:

```
Cache read: views/application/test:520cc54da9d0445ac315c7660f8e3205/projects/1
```

I have a fix though, the `ActiveSupport::Cache::Store#expanded_key method just needs to call `ActiveSupport::Cache.expanded_cache_key` instead of trying to do a half-baked key expansion on its own. Got a PR incoming for ya :)

**Comment by georgeclaghorn** [comment]
The cache key is not supposed to include the version; it’s included in the entry itself and validated on read. That is the point of [recyclable cache keys](https://github.com/rails/rails/pull/29092), and calling `ActiveSupport::Cache.expanded_cache_key` will break it.

**Comment by tubbo** [comment]
@georgeclaghorn I see, so I'm supposed to call something like `cache @project, version: @project.updated_at` in my view?

**Comment by tubbo** [comment]
@georgeclaghorn OK, so if this is expected behavior, then this is a non-issue for both Rails and `Redis::ActiveSupport`?

**Comment by tubbo** [comment]
**update:** turns out redis-activesupport had the `#write` method overridden, this isn't an issue anymore for us. thanks for being so patient!
