### ISSUE TITLE
unscoped default scope with Joins or includes

### ISSUE THREAD

**Issue by kashifnaseer** [rails/rails#32069]
It seems, unscoped is having some issues with joins and includes, any idea how we can fix it ?

    class Document < ActiveRecord::Base
      include KillMeSoftly
      has_many :versions, dependent: :destroy
      
      default_scope { where(is_deleted: false, is_archived: false) }
    end

    class Version < ActiveRecord::Base
      include KillMeSoftly
      belongs_to :document
      
       default_scope { where(is_deleted: false, is_archived: false) }
    end

I'm using following versions:-

     Rails 4.2.10 upgraded to Rails 5.0.2
     ruby 2.4.2p198

Calling this in console 
    
    Document.unscoped do 
     Version.unscoped do
       Document.joins(:versions)
     end
    end

gives this result. How I can unscoped default scoped values.
     
     SELECT "documents".* FROM "documents" INNER JOIN "versions" ON 
     "versions"."document_id" = "documents"."id" AND "versions"."is_deleted" = $1 
     AND "versions"."is_archived" = $2  [["is_deleted", "f"], ["is_archived", "f"]]

Other Example with includes: while joining it is ignoring default_scope attributes.

    Document.unscoped.includes(:versions).where(phase_id: xxxx, is_archived: true, versions: { 
    is_archived: true, is_deleted: false }).count

    SELECT COUNT(DISTINCT "documents"."id") FROM "documents" LEFT OUTER JOIN "versions" ON 
    "versions"."document_id" = "documents"."id" AND "versions"."is_deleted" = $1 AND 
    "versions"."is_archived" = $2 WHERE "documents"."phase_id" = $3 AND "documents"."is_archived" = 
     $4 AND "versions"."is_archived" = $5 AND "versions"."is_deleted" = $6  [["is_deleted", "f"], 
     ["is_archived", "f"], ["phase_id", 5363], ["is_archived", "t"], ["is_archived", "t"], ["is_deleted", "f"]]

**Comment by y-yagi** [comment]
Rails 4.2 is not supported anymore for anything besides security fixes.
Please check whether your issue can reproduce with latest Rails. Thanks.

**Comment by kashifnaseer** [comment]
@y-yagi i updated to Rails 5.0.2 and still I'm facing same issue. Joins dont respect unscoped.

**Comment by kashifnaseer** [comment]
![image](https://user-images.githubusercontent.com/1460838/36668316-5858a4d2-1b0a-11e8-80d6-9589ea5eb8c5.png)

**Comment by kashifnaseer** [comment]
I just wan to avoid/ignore default scope in joins or includes. any idea how i can do it ?

**Comment by y-yagi** [comment]
Can you create an executable test case with using this [template](https://github.com/rails/rails/blob/master/guides/bug_report_templates/active_record_master.rb)?

**Comment by kamipo** [comment]
This should be fixed by #30267 in 5.0.6.
