### ISSUE TITLE
Deprecation warning is triggered inside update! when used in after_create callback

### ISSUE THREAD

**Issue by joker-777** [rails/rails#32060]
### Steps to reproduce
We call `update!` in an after_create callback. This produces this deprecation warning.

DEPRECATION WARNING: The behaviour of `changed_attributes` inside of after callbacks will be changing in the next version of Rails. The new return value will reflect the behaviour of calling the method after `save` returned (e.g. the opposite of what it returns now). To maintain the current behavior, use `saved_changes.transform_values(&:first)` instead. 

### Expected behavior

It seems to me that this deprecation warning is triggered somewhere in rails which shouldn't happen.

### System configuration
**Rails version**: 5.1.4

**Ruby version**: ruby 2.3.4p301 (2017-03-30 revision 58214) [x86_64-linux]

**Comment by Edouard-chin** [comment]
I can't reproduce the issue using this template. The issue might happen because your app is calling `attribute_changed?` inside one of your validation method (which gets called when `update!` is fired and at that point the validation will be called in the context on an after_save callback)

<details>
   
   ```ruby
     require "bundler/inline"

    gemfile(true) do
      source "https://rubygems.org"
      gem "activerecord", "5.1.4"
      gem 'sqlite3'
    end

    require "active_record"
    require "minitest/autorun"
    require "logger"

    # Ensure backward compatibility with Minitest 4
    Minitest::Test = MiniTest::Unit::TestCase unless defined?(Minitest::Test)

    # This connection will do for database-independent bug reports.
    ActiveRecord::Base.establish_connection(adapter: "sqlite3", database: ":memory:")
    ActiveRecord::Base.logger = Logger.new(STDOUT)

    ActiveRecord::Schema.define do
      create_table :posts, force: true do |t|
        t.string :name
      end
    end

    class Post < ActiveRecord::Base
      after_save :update_me

      def update_me
        if !defined?(@_updated)
          @_updated = 1
          update!(name: 'Test')
        end
      end
    end

    class BugTest < Minitest::Test
      def test_association_stuff
        post = Post.new(name: 'John')
        post.save!
      end
    end
   ```
</details>

**Comment by joker-777** [comment]
I think you might be right. Good point, I haven't really thought about the validations. I will check them. Thanks a lot for your response.

**Comment by joker-777** [comment]
@Edouard-chin Just checked our validations without luck. We don't use and `changed` method there. I commented out everything in the model so it only looks like this

```ruby
class AModel < ApplicationRecord
  after_create :after_create_callback

  def after_create_callback                                                                
    update!(:a_attribute => "test")                                                               
  end                                                                                           
end   

And I still see the deprication method.
```

**Comment by Edouard-chin** [comment]
Looks like it's similar to the test script I provided above, have you checked the associated models as well?
The deprecation message should also point the code triggering the deprecation, maybe you can try debugging from here

**Comment by joker-777** [comment]
I finally found the reason why we see these deprecation warnings. We maintain indices with thinking-sphinx of the AnatomyTerm model and it uses the method `changed?`. 
I created an issue here https://github.com/pat/thinking-sphinx/issues/1085

**Comment by joker-777** [comment]
@Edouard-chin Thinking Sphinx has responded to my question and there answer might interest you too. https://github.com/pat/thinking-sphinx/issues/1085
