### ISSUE TITLE
video_tag helper returns incorrect HTML attributes

### ISSUE THREAD

**Issue by humphreybc** [rails/rails#32078]
`controls`, `autoplay`, `muted`, and `loop` [are all binary attributes](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/video), however the `video_tag` helper returns them as strings in the HTML.

### Steps to reproduce

You may need to configure your `assets.rb` to precompile videos from `/app/assets`.

1. Add a video to your project under `/app/assets/videos`
1. Use the `video_tag` helper (documented [here](http://api.rubyonrails.org/classes/ActionView/Helpers/AssetTagHelper.html#method-i-video_tag)) to insert the video into a view
1. Specify `controls: true` in the helper, like: `video_tag('video.mp4', controls: true)`

### Expected behavior

Output HTML should be:

```html
<video controls src="/videos/video.mp4"></video>
```

### Actual behavior

Output HTML is:

```html
<video controls="controls" src="/videos/video.mp4"></video>
```

### System configuration

**Rails version**: 5.1.0

**Ruby version**: 2.4.1

**Comment by bogdanvlviv** [comment]
This is expected behavior and it is [documented](http://api.rubyonrails.org/classes/ActionView/Helpers/AssetTagHelper.html#method-i-video_tag). See examples of using `video_tag`.

**Comment by matthewd** [comment]
Thanks for the report.

That Mozilla document references the HTML Living Standard, which [says](https://html.spec.whatwg.org/multipage/common-microsyntaxes.html#boolean-attribute):

> If the attribute is present, its value must either be the empty string or a value that is an ASCII case-insensitive match for the attribute's canonical name, with no leading or trailing whitespace.

As far as I can see, the attribute values are not *necessary*, but they're also not *wrong*. As such, it seems best to leave it as is: they're generated by common boolean-in-HTML-attribute code, which is also used on older tags/attributes, and some people might be relying on us producing valid XHTML. If we had to choose valid HTML5 xor valid XHTML, I'd of course choose the former... but if we can have both, that seems the safe choice.

**Comment by humphreybc** [comment]
@matthewd Hey, thanks for the explanation! That's very useful. I didn't know that about the Living Standard's definition of attributes.
