### ISSUE TITLE
[5.2.0.rc1] controller generator outputs duplicate route namespace block when one already exists

### ISSUE THREAD

**Issue by moomerman** [rails/rails#32072]
### Steps to reproduce

`rails new routebug --api --skip-active-record --skip-test`
`cd routebug/`
`rails g controller api/ones`

```
      create  app/controllers/api/ones_controller.rb
       route  namespace :api do
      end
```

edit `config/routes.rb` to add the new resource in the namespace

```
Rails.application.routes.draw do
  namespace :api do
    resources :ones
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end
```

`rails g controller api/twos`
```
      create  app/controllers/api/twos_controller.rb
       route  namespace :api do
      end
```

`cat config/routes.rb`

```
Rails.application.routes.draw do
  namespace :api do
  end
  namespace :api do
    resources :ones
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end
```

### Expected behavior

I would expect the routes file to remain unchanged on the second generator:

```
Rails.application.routes.draw do
  namespace :api do
    resources :ones
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end
```

### Actual behavior

A duplicate api namespace block is generated:

```
Rails.application.routes.draw do
  namespace :api do
  end
  namespace :api do
    resources :ones
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end
```

### System configuration

```
rails -v 
Rails 5.2.0.rc1
```

**Ruby version**:

```
ruby -v
ruby 2.5.0p0 (2017-12-25 revision 61468) [x86_64-darwin17]
```

**Comment by pixeltrix** [comment]
@moomerman is this a regression or does 5.1 also exhibit this behaviour?

**Comment by moomerman** [comment]
@pixeltrix it looks like this is a new feature in 5.2

**Comment by y-yagi** [comment]
Thanks for your report. 

I think should not add routes when actions are not specified. So I fixed with 651c2492f079cc2e37bf8e93a9fd23bde1e5349e. Thanks!

**Comment by pixeltrix** [comment]
@y-yagi does that fix the scenario where you do `rails g controller api/ones index` and then `rails g controller api/twos index` (i.e. you specify actions for both). Will that not generate a duplicate namespace or is it just an empty namespace matching issue? I know that thor doesn't have the best tools for patching in source code like this to existing files.

**Comment by y-yagi** [comment]
What I fixed is to avoid generating routes if action is not specified. This is to match behavior until 5.1. 
As you pointed out, if action is specified, the same namespace will be generated.  I think that it is difficult to handle this with thor... 
But I will check if it can cope.
