### ISSUE TITLE
Param types differ in integration Tests 

### ISSUE THREAD

**Issue by imechemi** [rails/rails#32073]
### Steps to reproduce

1. Clone example_app

        git clone https://github.com/imechemi/example_app

2. Start server, and hit POST /authors

       $ curl -H "Content-Type: application/json" -X POST -d '{"values":[123]}' http://localhost:3000/authors

When I print `param[:values]` in [controller](https://github.com/imechemi/example_app/blob/master/app/controllers/authors_controller.rb#L4), I get array of integers `[123]`. 

3. Quit server, hit integration test for same endpoint ([Test Code](https://github.com/imechemi/example_app/blob/master/test/integration/author_flows_test_test.rb#L5)): 

        $ rails test

When I print `param[:values]` in controller, I get array of strings `["123"]`.

(Guidelines for creating a bug report are [available
here](http://guides.rubyonrails.org/contributing_to_ruby_on_rails.html#creating-a-bug-report))

### Expected behavior
[123]

### Actual behavior
["123"]

### System configuration
**Rails version**: 5.1.5

**Ruby version**: 2.5.0

**Comment by imechemi** [comment]
I tested this with other rails version: `5.2.0.rc1` and `5.1.5.rc1`, still the same. I believe the types should still be consistent in both workflows.

**Comment by pixeltrix** [comment]
@imechemi please read the documentation about changing the request encoding - your test is being treated as a standard form POST and not a JSON post.

http://api.rubyonrails.org/classes/ActionDispatch/IntegrationTest.html#class-ActionDispatch::IntegrationTest-label-Changing+the+request+encoding
