### ISSUE TITLE
Is it to possible wildcards on the route system for everything except one pattern?

### ISSUE THREAD

**Issue by Drillan767** [rails/rails#32083]
This isn't a bug, but more something I have been wondering and couldn't find on the Rails documentation. I also asked a question on StackOverflow but I didn't get any answer, so I'm trying my luck here.

I would like to use React-Router to handle the majority of my pages from the visitor part and create a Single Page Application in the mean time. However, I would like to make sure that if the user types /admin, he wouldn't get "redirected" to the root_path

So far I only managed to either pass everything to a wildcard or make "compartiments" as follows:

```
root 'home#index'
# example 1
get '/*path' => 'home#index'
get '/articles' => 'home#articles_index'
# example 2
get '/articles/*all' => 'home#articles_index'
# vain try 1
get '/*path' => 'home#index', except: :admin
# vain try 2
get '/*path' => 'home#index', except: '/admin'

```

I found out about the constraints, but I realized it's to make sure the url is correctly passed (ie, integer instead of strings) but it doesn't "blacklist" urls.

Any idea?

Thank you in advance

### System configuration
**Rails version**: 5.1.4

**Ruby version**: 2.4.3

**Comment by pixeltrix** [comment]
Okay, I'm probably setting a bad precedent here but the question was interesting and I wasn't sure it'd work but it seems like using negative lookup assertions in the constraint regex is the way to go:

``` ruby
# frozen_string_literal: true

begin
  require "bundler/inline"
rescue LoadError => e
  $stderr.puts "Bundler version 1.10 or later is required. Please update your Bundler"
  raise e
end

gemfile(true) do
  source "https://rubygems.org"
  gem "rails", "5.1.5"
end

require "rack/test"
require "action_controller/railtie"

class TestApp < Rails::Application
  config.root = __dir__
  config.session_store :cookie_store, key: "cookie_store_key"
  secrets.secret_key_base = "secret_key_base"

  config.logger = Logger.new("/dev/null")
  Rails.logger  = config.logger

  routes.draw do
    get "/*id", to: "pages#show", id: /(?!admin).*/
  end
end

class ApplicationController < ActionController::Base
  include Rails.application.routes.url_helpers
end

class PagesController < ApplicationController
  def show
    render plain: request.path
  end
end

require "minitest/autorun"

# Ensure backward compatibility with Minitest 4
Minitest::Test = MiniTest::Unit::TestCase unless defined?(Minitest::Test)

class BugTest < Minitest::Test
  include Rack::Test::Methods

  def test_negative_lookup_constraints
    get "/foo"
    assert_equal 200, last_response.status
    assert_equal "/foo", last_response.body

    get "/foo/admin"
    assert_equal 200, last_response.status
    assert_equal "/foo/admin", last_response.body

    get "/admin"
    assert_equal 404, last_response.status

    get "/admin/foo"
    assert_equal 404, last_response.status
  end

  private

  def app
    Rails.application
  end
end
```

The other way to do it is define the routes you don't want to match before the catchall and get them to return a 404 error.

**Comment by Drillan767** [comment]
Hey, thank you for your answer, and sorry for not answering earlier! It works really fine and I managed to "improve" it by adding elements to the "whitelist:
By doing the following

`get '/*id', to: 'home#index', id: /(?!admin|settings|users).*/`

I can "whitelist" routes such as "/settings" (the website's general configuration), "/users/sign_in", and so on. I just hope, as you said it yourself, I don't settle a bad precedent

Thank you again!

**Comment by ignatiusreza** [comment]
isn't routing prioritize those which are first define? I've been doing the following and it works:

```rb
get '/admin', to: 'admin#index'
get '/*path' => 'home#index'
```

**Comment by Drillan767** [comment]
@ignatiusreza I should try, I never thought about that!
