### ISSUE TITLE
Can't update a counter_cache column using update!

### ISSUE THREAD

**Issue by harshalbhakta** [rails/rails#32098]
### Steps to reproduce

* Create a new Rails project. (Sample project [available here](https://github.com/harshalbhakta/test-rails-counter-cache-update))

````bash
$ rails new test-rails-counter-cache-update
$ bundle install
$ rails g model Author name:string articles_count:integer
$ rails g model Article name:string author:references
$ rails db:migrate
$ rails db:seed
````
* Modify the model files to support counter cache.

````ruby
# article.rb
class Article < ApplicationRecord
  belongs_to :author, counter_cache: :articles_count
end

# author.rb
class Author < ApplicationRecord
  has_many :articles
end
````

### Expected behavior

counter_cache column should get updated in all below scenarios. Currently it works only in the first scenario. 

Updating the column using Author.reset_counters(3, :articles) works as expected. However, I think it should also work correctly using author.update! articles_count: 20

#### Works (articles_count column does get updated)

````ruby
$ rails c
irb(main):001:0> author = Author.first
irb(main):001:0> author.update! articles_count: 20
    (0.2ms)  begin transaction
  SQL (0.6ms)  UPDATE "authors" SET "articles_count" = ?, "updated_at" = ? WHERE "authors"."id" = ?  [["articles_count", 20], ["updated_at", "2018-02-24 07:12:34.124976"], ["id", 3]]
    (2.5ms)  commit transaction
irb(main):001:0> exit
````
#### Does not work (articles_count column does not get updated)

````ruby
$ rails c
irb(main):001:0> article = Article.first
irb(main):001:0> author = Author.first
irb(main):001:0> author.update! articles_count: 10
    (0.2ms)  begin transaction
  SQL (25.0ms)  UPDATE "authors" SET "updated_at" = ? WHERE "authors"."id" = ?  [["updated_at", "2018-02-24 07:11:40.597808"], ["id", 3]]
    (1.6ms)  commit transaction
irb(main):001:0> exit
````

#### Does not work (articles_count column does not get updated)

````ruby
$ rails c
irb(main):001:0> author = Author.first
irb(main):001:0> author.update! articles_count: author.articles.count
    (9.3ms)  SELECT COUNT(*) FROM "articles" WHERE "articles"."author_id" = ?  [["author_id", 3]]
    (0.2ms)  begin transaction
  SQL (26.4ms)  UPDATE "authors" SET "updated_at" = ? WHERE "authors"."id" = ?  [["updated_at", "2018-02-24 07:15:03.272752"], ["id", 3]]
    (1.5ms)  commit transaction
irb(main):001:0> exit
````

### System configuration
**Rails version**: Rails 5.1.5

**Ruby version**: ruby 2.4.2p198 (2017-09-14 revision 59899) [x86_64-darwin17]

**Comment by y-yagi** [comment]
Counter cache columns are added to the containing model's list of read-only attributes. So can't update using `update!`. 
Ref: http://guides.rubyonrails.org/association_basics.html#options-for-belongs-to-counter-cache 

Added to read-only depends on whether model is loaded or not. 
Therefore, the first example works in development, but it does not work on production where eager load is enabled. 

If you want to update counter cache to any value, please use `update_counters`. 
http://api.rubyonrails.org/classes/ActiveRecord/CounterCache/ClassMethods.html#method-i-update_counters

**Comment by danielricecodes** [comment]
For anyone looking for a working counter cache warm up implementation, here's a sample migration that gets the job done.  This uses `reset_counters` instead of `update_counters`; however, it creates the SQL query needed.  This isn't a great migration for a large database, but works fine for most use cases or people who are patient :) 

```ruby
class WarmInvoiceCounterCache < ActiveRecord::Migration[5.2]
  def up
    Invoice.reset_column_information
    Invoice.pluck(:id).each { |invoice_id| Invoice.reset_counters(invoice_id, :payment_transactions) }
  end
  def down
    Invoice.update_all(payment_transactions_count: 0)
  end
end
```
