### ISSUE TITLE
Rails 5.2 engine dummy app doesn't auto require 'rails-ujs'

### ISSUE THREAD

**Issue by shroy** [rails/rails#32094]
Not sure if this was intentional, however, I found that **rails-ujs** is not automatically required in the dummy app for Rails Engines.

### Steps to reproduce

- Create a new engine.
- Scaffold a resource in the *test/dummy* app
- Visit the **#new** page for the resource.
- Create a resource.
- Visit the **#index** page to view the newly created resource.
- Click on the `Destroy` link

### Expected behavior
Resource *should* be deleted via **#delete** method

### Actual behavior
User is directed to the resource's **#show** page

### System configuration
**Rails version**: 5.2.0.rc1

**Ruby version**: 2.4.1

**Comment by bogdanvlviv** [comment]
Hi @shroy. Thanks for the report. I just opened PR(#32095) that should fix that.
