### ISSUE TITLE
Foreign key replacement in inverse association regression

### ISSUE THREAD

**Issue by jfragoulis** [rails/rails#32116]
### Steps to reproduce

https://gist.github.com/jfragoulis/41a5529d26a8d9921b7aa54b6e17e001

### Expected behavior

Test does not blow up.

### Actual behavior

Test fails with validation error on `Post`.

### System configuration
**Rails version**: 5.2.0.rc1

**Ruby version**: 2.3.3

This *regression* is traced to https://github.com/rails/rails/pull/31575.
The **expected** behavior is how it works in latest stable.

EDIT:

The problem lies with the fact that when saving a parent object, its associations go through validation as well before the parent is actually saved. This is fine I guess generally I suppose, but in my use-case, I have a presence validation check on the fk (see gist) which means that since the #31575 sets the fk to `nil`, the validation fails.

**Comment by pixeltrix** [comment]
Confirmed that this is a regression from 5.1.5

**Comment by kamipo** [comment]
This is what #31575 want to do, it is the expected behavior to me.

`validates :author_id, presence: true` in `Post` means that `author_id` must be present before `Post` is saved.

Previous behavior which pass the validation by the remained `author_id` makes me feel a bug.

Following example will fail as expected from the beginning.

```ruby
class Author < ActiveRecord::Base
  has_many :posts
end

class Post < ActiveRecord::Base
  belongs_to :author
  validates :author_id, presence: true
end

author = Author.new                                                                                                                 
post = Post.new                                                                                                                     
author.posts << post                                                                                                                
author.save!                                                                                                                        
```

Probably `belongs_to :author, required: true` should be used in that case.

**Comment by pixeltrix** [comment]
@kamipo yes, you're right - this fails in 5.1:

``` ruby
class Author < ActiveRecord::Base
  has_many :posts
end

class Post < ActiveRecord::Base
  belongs_to :author
  validates :author_id, presence: true
end

Author.create!(posts: [Post.new])
```

Closing this as a won't fix

**Comment by pixeltrix** [comment]
@jfragoulis FYI moving the validation to the `belongs_to :author` as `required: true` and doing this:

``` ruby
 author = Author.create!(posts: [Post.new])
 post = author.posts.first

 Author.create! posts: [post]
```

works in both Rails 5.1 and 5.2.

**Comment by jfragoulis** [comment]
Thank you both for your comments.

@kamipo You are right, it does feel like a bug and it is a correct fix.

I verified that removing the validation check and adding `required: true` works.

My comment is the following: The documentation is either not clear or wrong and I should probably open a PR for this.

In the documentation under `belongs_to` and `:required` in both 5.1 and 5.2 we read:

> When set to true, the association will also have its presence validated. This will validate the association itself, not the id. You can use :inverse_of to avoid an extra query during validation. NOTE: **required is set to true by default and is deprecated**. If you don't want to have association presence validated, use optional: true.

That means that removing the validation should suffice, since it is required by default. That is not the case though. The default value is set through `ActiveRecord::Base.belongs_to_required_by_default` which [is set to `false`](https://github.com/rails/rails/blob/master/activerecord/lib/active_record/core.rb#L126). My console says it is `nil` which is really weird:

```
[1] pry(main)> ActiveRecord::Base.belongs_to_required_by_default
=> nil
```
The [configure page](http://guides.rubyonrails.org/configuring.html) simply describes it, and the [upgrading page](http://edgeguides.rubyonrails.org/upgrading_ruby_on_rails.html#active-record-belongs-to-required-by-default-option) which says:

> This default will be automatically configured in new applications

This is vague. My guess for what it means is that the new app generator will put it in your initializers or some config file. Which does not make it `true` by default as mentioned in the docs. True by default means, true in the framework's default.

What do you think?

**Comment by jfragoulis** [comment]
@pixeltrix
