### ISSUE TITLE
hardcode url in activestorage

### ISSUE THREAD

**Issue by pynixwang** [rails/rails#32110]
### Steps to reproduce

use activestorage.

### Expected behavior
can set base url of it.

### Actual behavior
hardcode.

https://github.com/rails/rails/blob/master/activestorage/config/routes.rb

### System configuration
**Rails version**:
5.2.0.rc1

**Ruby version**:
2.5.0

this can make it easy to detect framework and do some hack.

**Comment by georgeclaghorn** [comment]
> this can make it easy to detect framework and do some hack.

There are probably a dozen ways to tell whether an app is using Rails. If you come across specific vulnerabilities, please do [report them](http://rubyonrails.org/security/).

**Comment by georgeclaghorn** [comment]
I should add that you’re free to create and use your own routes for Active Storage’s controllers.

**Comment by pynixwang** [comment]
we all love rails, but we do not need add it to route. maybe remove it and leave `activestorage` as namespace for protecting name conflict.
