### ISSUE TITLE
OptionParser::InvalidOption:  with any `--` rake commands arguments

### ISSUE THREAD

**Issue by benoittgt** [rails/rails#32117]
### Steps to reproduce

Hello,

I am writing a proposition for `rails routes` command options. In the rake task I added an option to optparser https://github.com/benoittgt/rails/blob/0508d7c28b13e271db7d277494a87e1aeddfb04d/railties/lib/rails/tasks/routes.rake#L27-L29

My issue is the option is always invalid. `#<OptionParser::InvalidOption: expanded>`

I wrote a small script to try to reproduce the issue but it's work perfectly:

```ruby
require 'optparse'

options = {}
expanded = false
OptionParser.new do |opts|
  opts.banner = "Usage: example.rb [options]"

  opts.on("-v", "--[no-]verbose", "Run verbosely") do |v|
    options[:verbose] = v
  end

  opts.on("--expanded") do |v|
    expanded = true
  end
end.parse!

p options
p ARGV
p expanded

=begin

{}
["--expanded"]
true

=end

```
It doesn't seems to be on optparser, it happens here https://github.com/benoittgt/rails/blob/rake-routes-compact-mode/railties/lib/rails/commands/rake/rake_command.rb#L21 on `.init`. It seems like if command arguments where validated before the routes rake task was loaded.

Or do I made something wrong?

To reproduce the issue:
- clone https://github.com/benoittgt/rails/tree/rake-routes-compact-mode
- `clear; bundle exec ruby -w -Itest test/application/rake_test.rb -n test_rails_routes_with_expanded_option`

### Expected behavior

Be able to add `--option`

### Actual behavior

`OptionParser::InvalidOption:`

### System configuration
**Rails version**: master
**Ruby version**: 2.4

Thanks 👏🏻

**Comment by matthewd** [comment]
`rake` isn't intended for generic subcommands, and thus cannot support "normal" option arguments.

This is a large part of our motivation for moving our rake commands over to our new Rails::Commands infrastructure.

I don't really have a good suggestion for you in the meantime, sorry... apart from overriding the task wholesale, and then defining a new `routes:verbose` maybe?

Alternatively, help converting it to a Rails::Command would be very welcome :smile:

**Comment by benoittgt** [comment]
Thanks @matthewd for the quick answer. Will finish this PR first and we will see for `Rails::Command` 😄
