### ISSUE TITLE
Amazing bug in AS::TimeWithZone 

### ISSUE THREAD

**Issue by bogdan** [rails/rails#32112]
### Steps to reproduce

AS tries to be smart and allows the comparation of time to a String that is a serialized time.
It results in a really weird behavior in `#==`:

``` ruby
a = ActiveSupport::TimeWithZone.new(Time.utc(1999, 12, 31, 23, 59, 59), ActiveSupport::TimeZone["UTC"])
b = a.to_s

a == b # => true
b == a # => false

h1 = {created_at: a}
h2 = {created_at: b}

h1 == h2 # => true
h2 == h1 # => false
```

It can be considered related to #31503 due to the following scenario:

``` ruby
u  = User.first
serialized = JSON.parse(u.to_json)
expected = u.as_json
serialized == expected # => false
expected == serialized # => true
```

### Expected Behavior

`AS::TimeWithZone#==` to be commutative operation.

### Actual Behavior

`AS::TimeWithZone#==` is not commutative operation.

### System configuration

**Rails version**: 5.4.1 but I think a lot of them are affected

**Ruby version**: 2.4.2

**Comment by matthewd** [comment]
This is expected behaviour to me; it's a natural consequence of calling `==` on two objects of different types: the LHS determines the equality rules.

**Comment by rafaelfranca** [comment]
Yup. This is how a lot of objects in Ruby works. Example:

```
>> require 'ipaddr'
=> true
>>
>> ipaddr1 = IPAddr.new "3ffe:505:2::1"
=> #<IPAddr: IPv6:3ffe:0505:0002:0000:0000:0000:0000:0001/ffff:ffff:ffff:ffff:ffff:ffff:ffff:ffff>
>> ipaddr1 == "3ffe:505:2::1"
=> true
>> "3ffe:505:2::1" == ipaddr1
=> false
```
