### ISSUE TITLE
Actioncable test if clients are connected on a channel

### ISSUE THREAD

**Issue by johansmitsnl** [rails/rails#32120]
### Expected behavior
A way to test if users are subscribed on a channel so that we can decide to do expensive calculations that have clients listening for

### Actual behavior
Unable to check if users are subscribed

### System configuration
**Rails version**: 5.1.2

**Ruby version**: 2.3.0

Currently I have in my app I have cron tasks running that gather information and broadcasts it to the subscribers on the channels. On these taks I do view rendering before I broadcast the message to the client. But due to being a background cron task there is no user requesting the updated information and there might be no user listening to this broadcast and rendering is useless.
Therefore I'm looking (but could not find it in the documentation) if there is a way to check if there are clients listening on this channel/stream? It could save a lot of cpu. Now I send a very small message out and check the return value not 0 (means consumers are listening) but it should be more simple.
I could write code to track in the database if there are clients connected/disconnected on certain streams but the app already knows this (I assume?).

I opened an issue because I did not got any reply on the gitter chat about this.

**Comment by y-yagi** [comment]
Please use the [mailing list](https://groups.google.com/forum/#!forum/rubyonrails-talk) or StackOverflow for questions/help, where a wider community will be able to help you. We reserve the issues tracker for issues only. Thanks.
