### ISSUE TITLE
rails db:schema:load fails for PostgreSQL arrays while rails db:migrate does work 

### ISSUE THREAD

**Issue by breytner** [rails/rails#32123]
Hi, this migration works fine when executing rails db:migrate

```
class CreateBmcCards < ActiveRecord::Migration[5.1]
  def change
    create_table :bmc_cards do |t|
      t.string :name
      t.string :description
      t.string :purposes, array: true, default: []

      t.timestamps
    end
  end
end
```
and produces the following lines in schema.rb:
```
  create_table "bmc_cards", force: :cascade do |t|
    t.string "name", default: ""
    t.string "description", default: ""
    t.string "purposes", default: [], array: true
    t.datetime "created_at", null: false
    t.datetime "updated_at", null: false
  end
```

But when trying to re-create the database tables from the generated schema by running rails db:schema:load, I get the error:

> -- create_table("bmc_cards", {:force=>:cascade})
> rails aborted!
> TypeError: can't quote Array

All previous tables to this one are correctly created. 

If I do `rake db:drop db:create db:migrate`, it does create all tables without errors.  

I'm using:
Rails version: 5.1.2
Ruby version: 2.3.3

**Comment by fatkodima** [comment]
I have tried, but can't reproduce this issue. Can you provide a reproducible script with this template https://github.com/rails/rails/blob/master/guides/bug_report_templates/active_record_gem.rb?

**Comment by kashifnaseer** [comment]
any update on this ?
