### ISSUE TITLE
Doc mistake with self.abstract_class = true

### ISSUE THREAD

**Issue by wycats** [rails/rails#32132]
### Steps to reproduce

I used the bug report template: https://gist.github.com/chancancode/00296a017b46a9c8f2fd32987d46af9a#file-bugreport-rb

TL;DR

According to the docs, you need to use `self.abstract_class = true` in order to get Rails to use the explicitly overridden `table_name`. That isn't true, and I created a bug report using the bug report template (with @chancancode) to illustrate the mistake.

**Comment by kamipo** [comment]
Definitely. This should be fixed by #31171.
