### ISSUE TITLE
ActionCable not respecting port assigning in production.rb

### ISSUE THREAD

**Issue by culov** [rails/rails#32152]
Rails 5.1.3

I'm trying to run my ActionCable server on an alternative port (8080). I set up my `production.rb` as follows:

`config.action_cable.url = 'wss://my-domain.org:8080/cable'`
`config.web_socket_server_url = "wss://my-domain.org:8080/cable"`

The metatags included on the page accurately reflect the changed port:

`<meta name="action-cable-url" content="wss://my-domain.org:8080/cable" />`

However, when I inspect the requests, I see that the specified port is NOT included in the URL, so the we can never connect to the websocket:

`WebSocket connection to 'wss://my-domain.org/cable' failed: WebSocket is closed before the connection is established.`

I've tested and verified that my server is actively listening on port 8080 for websocket requests, and it's working fine. If I manually set `App.cable.url = 'wss://my-domain.org:8080/cable'` in javascript, everything works fine.

The problem appears to be that the port specification is not being read by ActionCable from the metatag. How can I resolve this?

**Comment by victorhazbun** [comment]
Is there a way for @culov to reproduce this issue with a script?

**Comment by mohsen-alizadeh** [comment]
@culov have you set `config.action_cable.allowed_request_origins`

**Comment by pixeltrix** [comment]
@culov what do you get if you do the following the browser console:

``` js
ActionCable.getConfig('url')
```

**Comment by wdiechmann** [comment]
Hi @culov did you master this after all? If so, I'd like to learn from you how to set up Rails with Action Cable and Puma thank you very much :) 

I have development running just perfect - but production tells me:
```
WebSocket connection to 'wss://speicher.ltd/cable' failed: WebSocket is closed before the connection is established.
```

**Comment by drindc24** [comment]
Same issue. Hopefully someone can help

**Comment by culov** [comment]
Not totally sure what I did to fix it, but here are my current settings in production.rb

   config.action_cable.mount_path = ":8080/cable"
   config.action_cable.url = 'wss://my-domain.com:8080/cable'
   config.web_socket_server_url = "wss://my-domain.co:8080/cable"
