### ISSUE TITLE
Document what Activerecord can and can't rollback on its own

### ISSUE THREAD

**Issue by moore3071** [rails/rails#32155]
It would be nice to know what Activerecord migrations can and can't reverse without a custom user method. The guides states:

> If you wish for a migration to do something that Active Record doesn't know how to reverse, you can use reversible

yet there's no apparent list of what Active Record doesn't know.

**Comment by y-yagi** [comment]
Please see http://guides.rubyonrails.org/active_record_migrations.html#using-the-change-method
