### ISSUE TITLE
How do you counter_cache:  active-storage

### ISSUE THREAD

**Issue by zPhumzani** [rails/rails#32169]
How do you counter_cache:  active-storage
How do you make a image as default for your views when using has_many_attached

### System configuration
**Rails version**:
rails-5.2
**Ruby version**:
ruby.2.5.0

**Comment by y-yagi** [comment]
Please use the [mailing list](https://groups.google.com/forum/#!forum/rubyonrails-talk) or StackOverflow for questions/help, where a wider community will be able to help you. We reserve the issues tracker for issues only.
