### ISSUE TITLE
ActiveModel::Errors should use deep_dup?

### ISSUE THREAD

**Issue by sfcgeorge** [rails/rails#32178]
### Expected behavior

`deep_dup` is used in one place in ActiveModel::Errors to dup details—in `initialize_dup` here: https://github.com/rails/rails/blob/8228d12a43927a22d0ac9bd351d18f473d6a49ae/activemodel/lib/active_model/errors.rb#L82

So I'm assuming since details is a hash then `deep_dup` should be used whenever dupping details.

### Actual behavior

But in the `copy` method regular `dup` is used, here: https://github.com/rails/rails/blob/8228d12a43927a22d0ac9bd351d18f473d6a49ae/activemodel/lib/active_model/errors.rb#L95

There are specs to do with dup but only 3 and they don't cover deepness.

### System configuration
**Rails version**: master

**Comment by rafaelfranca** [comment]
Probably, yeah, but `copy!` is private api of the framework and should not used by libraries or applications. If you have a example of how using the public API that `dup` is a problem we can change to use `deep_dup`.

**Comment by sfcgeorge** [comment]
Ah I saw it was a public method but didn't see the `:nodoc:`. I'll close.
