### ISSUE TITLE
Render within before_action incorrect format

### ISSUE THREAD

**Issue by r4do** [rails/rails#32179]
### Steps to reproduce

1. Create before_action function and run render within it:

```
class BeforeController < ApplicationController
  before_action :before_index

  def index
  end

  private
  def before_index
    render partial: 'test'
  end
end
```

2. Create templates for html and js format: `_test.html.erb` and `_test.json.erb`

3. Open index action url.

### Expected behavior
Render uses the format specified in the request, so if open `http://localhost:3000/before/index.html` you see _test.html.erb rendered, and if open `http://localhost:3000/before/index.json` you see _test.json.erb rendered.

### Actual behavior
Default format (_test.html.erb) is being rendered.
If make same render execution within index action, format specified in the request is being used.

### System configuration
**Rails version**: 5.1.5

**Ruby version**: 2.5.0

**Comment by r4do** [comment]
I've found that this is happens because `self.formats` are being set right after `before_` callbacks:

```
class BeforeController < ApplicationController
  # before_action :before_index

  def index
    p 'index action', formats
    render partial: 'test'
  end

  private
  def before_index
    p 'before_index', formats
    render partial: 'test'
  end
end
```

Console logs:

```
Started GET "/before/index.json" for 127.0.0.1 at 2018-03-06 12:38:22 +0200
Processing by BeforeController#index as JSON
"before_index"
[:html, :text, :js, :css, :ics, :csv, :vcf, :png, :jpeg, :gif, :bmp, :tiff, :svg, :mpeg, :xml, :rss, :atom, :yaml, :multipart_form, :url_encoded_form, :json, :pdf, :zip, :gzip]
  Rendered before/_test.html.erb (0.3ms)
Filter chain halted as :before_index rendered or redirected
Completed 200 OK in 19ms (Views: 18.7ms)


Started GET "/before/index.json" for 127.0.0.1 at 2018-03-06 12:38:35 +0200
Processing by BeforeController#index as JSON
"index action"
[:json]
  Rendered before/_test.json.erb (0.2ms)
Completed 200 OK in 3ms (Views: 2.2ms)
```

**Comment by pixeltrix** [comment]
Setting formats after the before callbacks have been run has been that way since the first Rails 3.0 beta (possibly earlier - I didn't check). Introducing such a change now could break a lot of apps and prevent manipulation of the formats in a before callback. This seems an incredibly risky thing to do for little benefit - can you explain why the rendering can't happen in the action itself?

**Comment by r4do** [comment]
@pixeltrix I'm using cancancan for authorization with load_and_authorize_resource and I don't want to redirect when some ajax request isn't authorized so I render toasts with JS. So since load_and_authorize_resource is before action, response is being rendered not in the action.

**Comment by pixeltrix** [comment]
@r4do sounds like you need to implement a custom before action that replicates what `load_and_authorize_resource` is doing but checks for a XHR request and renders the partial with an explicit `formats: [:json]` option.

**Comment by mikerobe** [comment]
I ran into exactly this issue recently in Rails 7.

We have a before_action hook that checks various conditions for requests coming from our mobile app to sync a section of the app. When certain conditions apply (like they're trying to render the wallets section of the app but haven't completed KYC yet -- it's a banking app), the before_action hook renders a different screen.

When we rolled out an HTML version of our app basically, it started rendering the HTML templates only in these before_action hooks for the app, which was requesting JSON. This behavior only happens in the before_action hooks: in the controller actions themselves, the correct templates are rendered based on the format.

This definitely caught us by surprise and has led to replacing calls like `render :account_details` with weird blocks like this any time we need to render from a `before_action` hook:

``` ruby
before_action :foo do
  # Just calling `render :bar` will not work in before_action: it'll render
  # the bar.html template even for JSON requests instead of bar.json.
  respond_to do |format|
    format.any { render :bar }
  end
end
```

**Comment by Buyzed** [comment]
32179
