### ISSUE TITLE
System tests require Puma single mode configuration

### ISSUE THREAD

**Issue by titanium-cranium** [rails/rails#32181]
Recently created new app using Ruby 2.5, Rails 5.1.4

Added RSpec, FactoryBot, Capybara gems and configured as per their instructions to run system tests

Created basic system test to to assess devise login in spec/system directory using capybara/selenium

```
RSpec.describe 'PersonLogin' do
  it 'will allow login' do
    user = FactoryBot.create(:user)
    visit new_user_session_path
    fill_in "Email", with: user.email
    fill_in "Password", with: user.password
    click_on "Log in"
    expect(page).to have_content 'Submit my request'
  end
end
```

### Expected behavior
Navigating the path by hand with the browser is functioning normally so the tests should pass. 

### Actual behavior
System tests fail.  

After much digging, it appears this is due to the Puma configuration. Default Rails configuration spawns no workers and puma runs in single mode. Uncommenting the default code specifying that puma should spawn a minimum of 2 workers causes system tests to fail. 

```
#puma.rb
workers ENV.fetch("WEB_CONCURRENCY") { 2 }`
```
Configuring puma to have 0 workers in the test environment and force it to run in single mode solves the problem and tests pass. 

```
#puma.rb
(ENV.fetch("RAILS_ENV") == 'test') ? (workers 0) : (workers ENV.fetch("WEB_CONCURRENCY") { 2 })
```

### System configuration
**Rails version**: 5.1.4
**Ruby version**: 2.5.0
**Capybara** : 2.18.0
**RSpec** : 3.7.2
**Factory Bot**: 4.8.2
**Puma**: 3.11.0

**Comment by y-yagi** [comment]
Thanks for your issue. 
This issue already fixed by #30638.
