### ISSUE TITLE
regression: contextual validation not working

### ISSUE THREAD

**Issue by plentz** [rails/rails#32180]
### Steps to reproduce

```ruby
# frozen_string_literal: true

begin
  require "bundler/inline"
rescue LoadError => e
  $stderr.puts "Bundler version 1.10 or later is required. Please update your Bundler"
  raise e
end

gemfile(true) do
  source "https://rubygems.org"

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  gem "rails", "5.1.4" #works
  #gem "rails", "5.1.5" #fail
  gem "sqlite3"
end

require "active_record"
require "minitest/autorun"
require "logger"

ActiveRecord::Base.establish_connection(adapter: "sqlite3", database: ":memory:")
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :posts, force: true do |t|
    t.string :name
    t.integer :status
  end

end

class Post < ActiveRecord::Base
  enum status: { inactive: 0, active: 1 }
  validates :status, inclusion: { in: ["active"] }, on: :update, if: ->(t) { t.saved_change_to_status? }
  after_create :fail_after_create
  def fail_after_create
    self.update!(name: "yolo again")
  end
end

class BugTest < Minitest::Test
  def test_validation
    post = Post.create(status: "active", name: "yolo")
    assert_equal false, post.update(status: "inactive")
  end
end
```

### Expected behavior
Update should fail because the validation should prevent it.

### Actual behavior
Validation only works @ 5.1.4

### System configuration
**Rails version**: 5.1.4 & 5.1.5

**Ruby version**: 2.5.0

Probably related #31483

**Comment by eugeneius** [comment]
`git bisect` points to https://github.com/rails/rails/pull/30472 - the behaviour of `saved_change_to_attribute?` changed, not the validation.

The new behaviour seems to be intentional: `update!` (in the callback) saves the record again without changing the `status` attribute, so `update` (in the test) doesn't see the attribute as changed.

The behaviour is now consistent with what would happen if no callbacks were involved:

```ruby
post = Post.create(status: "active", name: "yolo")
post.update!(name: "yolo again")
post.update(status: "inactive")
```

Could you explain your actual use case here? Why would you want the validation to conditionally run based on whether an attribute changed in the _last_ save?

**Comment by plentz** [comment]
the actual use case is more complex, I've just reduced it to the minimum amount of code possible to reproduce. the main purpose of the validation is to ensure the once a entity is created, it never goes back to the original `status`. think as a model that can be `created` and once `activated` should never go back to `created`.

**Comment by rafaelfranca** [comment]
But why are you changing the record itself in a `after_save` callback? Is not better to change it in a `before_save` callback and only save the record in the database once?

**Comment by plentz** [comment]
@rafaelfranca sure it is. I've reported because it changed the behavior, not because I think the test it broke was well written 🤣

**Comment by rafaelfranca** [comment]
The behavior that has changed was a bug so it is expected it change between two bug fix releases. Thanks for reporting.
