### ISSUE TITLE
[ActionDispatch] SystemTesting: custom options are ignored

### ISSUE THREAD

**Issue by renchap** [rails/rails#32197]
### Steps to reproduce

I am using this in my system tests:

```ruby
chrome_options = Selenium::WebDriver::Chrome::Options.new
chrome_options.add_preference(:download, default_directory: DL_PATH)
driven_by :selenium, using: :headless_chrome, screen_size: [1600, 1200], options: { options: chrome_options }
```

### Expected behavior

The `download.default_directory` Chrome preference should be set when running the tests
Selenium should be passed a `Selenium::WebDriver::Chrome::Options` instance looking like this:

```
<Selenium::WebDriver::Chrome::Options:0x00007f9f64e5ee20
  @args=#<Set: {"--headless", "--disable-gpu"}>,
  @binary=nil,
  @prefs={:download=>{:default_directory=>#<Pathname:/path/tmp/test_downloads>}},
  @extensions=[], @options={}, @emulation={}, @encoded_extensions=[]>
```

### Actual behavior

`download.default_directory` is not set.
`Selenium::WebDriver::Chrome` is passed the following options object:

```
<Selenium::WebDriver::Chrome::Options:0x00007f9f64f85088
  @args=#<Set: {"--headless", "--disable-gpu"}>,
  @binary=nil,
  @prefs={},
  @extensions=[], @options={}, @emulation={}, @encoded_extensions=[]>
```

### System configuration
**Rails version**: 5.2.0-rc1

### Workaround

Registering a custom driver works fine.

I tried using this:
```ruby
chrome_profile = Selenium::WebDriver::Chrome::Profile.new
chrome_profile["download.default_directory"] = DL_PATH

driven_by :selenium, using: :headless_chrome, screen_size: [1600, 1200], options: {
  profile: chrome_profile
}
```

It works (`download.default_directory` is set) but I get a deprecation notice: `WARN Selenium [DEPRECATION] Using Selenium::WebDriver::Chrome::Profile#extensions is deprecated. Use Selenium::WebDriver::Chrome::Options#add_extension instead.`

### Analysis

In https://github.com/SeleniumHQ/selenium/blob/29b5be0a72331df9ab99e36b05b4c29cf7046f30/rb/lib/selenium/webdriver/chrome/driver.rb#L67 it is expected that the driver is getting an `options` key with a proper `Selenium::WebDriver::Chrome::Options` object. The other keys are processed below for backward compatibility, but with a deprecation notice.

https://github.com/rails/rails/blob/190744cd8ed014915803fa805996be04dc750d9d/actionpack/lib/action_dispatch/system_testing/driver.rb#L34-L36

Here the user-provider options hash has its `options` key overriden by the driver default options, not merged in. Merge will be difficult as `Selenium::WebDriver::Chrome::Options` does not have a `merge` method. `profile` is not merged so my above workaround works.

To solve this, I thought about:
- Changing the `driven_by`'s `options` parameter to accept a WebDriver options object (like  `Selenium::WebDriver::Chrome::Options` here), and use this options object when adding default driver options
- or allowing `driven_by` to take a block parameter, with the options object as argument. This would allow something like:
    ```ruby
    driven_by :selenium, using: :headless_chrome, screen_size: [1600, 1200] do |options|
      options.add_preference(:download, default_directory: DL_PATH)
    end
    ```

cc @eileencodes

**Comment by eileencodes** [comment]
I want to double check - is it only some options or all options that aren't being passed in? I'm wondering if this is a bug in how we're passing the options if it's all options.

**Comment by renchap** [comment]
I know this probably looks confusing, and I did not get it right the first time. The logic is not straightforward and a lot of things are called `options` and `opts`, which does not make it easier :)

Each Capybara drivers expects an `options` argument as a `Hash`. This is the `driven_by`'s `options` arg.

This `options` arg is then passed to the Selenium Webdriver `initialize` call.
For Chrome (the other drivers may be different), see here: https://github.com/SeleniumHQ/selenium/blob/master/rb/lib/selenium/webdriver/chrome/driver.rb

Some keys of the `options` arg are used to set specific settings (`:driver_path`, `:url`, …).
Other keys have specific behaviour, like `:args` or `:prefs` (correctly setting it but displaying a deprecation notice).
For `:profile`, depending on the sub-key, it sets something (`:directory`), or sets something but with a deprecation notice (`:extensions`), or  it is ignored.

All of this currently works fine.

The problem I encountered is when you want to pass a an `:options` key (so `options[:options]`). This is expected to be a `Selenium::WebDriver::Chrome::Options` (for Chrome) instance.

https://github.com/rails/rails/blob/190744cd8ed014915803fa805996be04dc750d9d/actionpack/lib/action_dispatch/system_testing/driver.rb#L34-L36

Here `options[:options]` is overriden with `@browser.options`, (which is defined here: https://github.com/rails/rails/blob/master/actionpack/lib/action_dispatch/system_testing/browser.rb#L34)

This makes it impossible to have a custom `Selenium::WebDriver::Chrome::Options` object passed to Selenium/Webdriver, thus impossible to set a custom config for the driver.

The easiest solution would be to not override `options[:options]`, but allow the user to pass a `Selenium::WebDriver::Chrome::Options` object to `driven_by`, like this:

```ruby
chrome_options = Selenium::WebDriver::Chrome::Options.new
chrome_options.add_preference(:download, default_directory: DL_PATH)
driven_by :selenium, using: :headless_chrome, screen_size: [1600, 1200], options: { options: chrome_options }
```

To achieve this, `SystemTesting::Driver#browser_options` should take the user-supplied `:options`, and pass it to `SystemTesting::Browser#options` (and then `headless_chrome_browser_options`) which either create a `Selenium::WebDriver::Chrome::Options` if its `nil`, or add the required options to the user-supplied one.

I do not really like passing this object through this many calls, but I do not see an alternative. I can work on a PR for it, if you are ok with the proposal.

**Comment by eileencodes** [comment]
It's hard for me to parse exactly without a PR and right now I don't have the bandwidth to dig into this issue, so your proposal seems fine and if you want to work on a PR I'd really appreciate that 😄 Thanks!

**Comment by renchap** [comment]
Sure, I will make a PR next week.

**Comment by Edouard-chin** [comment]
👋  @renchap Are you planning to work on this? I'd be happy to takeover otherwise as I'm facing the same issue.

**Comment by renchap** [comment]
Thanks for the nudge. I have been sick for 2 weeks and now need to catch back with work, so I wont have time to look at this before next week.  Feel free to send a PR if you need this.

FYI, if you are using headless Chrome, setting the download directory in the options is not working (see https://bugs.chromium.org/p/chromium/issues/detail?id=696481). I got a workaround with the following code:

```ruby
driver = page.driver
bridge = driver.browser.send(:bridge)

path = "/session/#{bridge.session_id}/chromium/send_command"

bridge.http.call(:post, path, cmd: 'Page.setDownloadBehavior',
                  params: {
                    behavior: 'allow',
                    downloadPath: downloads_path
                  })
```

It also requires a recent chromedriver and Chrome 65+ (see https://bugs.chromium.org/p/chromedriver/issues/detail?id=1973#c22)

I wrapped it in a helper similar to https://collectiveidea.com/blog/archives/2012/01/27/testing-file-downloads-with-capybara-and-chromedriver and it seems to work but I have not been able to test it thoroughly yet.

**Comment by Edouard-chin** [comment]
> I have been sick for 2 weeks and now need to catch back with work

Hope you feel better! Otherwise no rush, mainly wanted to let you the time to work on it instead of taking over without asking :).

My issue is not about the download_directory, but mobile emulation, it's the same underlying problem though.
I like the solution you proposed

```ruby
driven_by ... do |option|
  option.add_argument
end
```

Since the `Chrome::Option` class was introduced in Selenium 3.4.4 a bunch of convenient way to pass options were deprecated, here is one [example](https://github.com/SeleniumHQ/selenium/blob/1c77719bba98205c81f69161a1e6bca7bb045280/rb/lib/selenium/webdriver/chrome/driver.rb#L69)

IMHO Rails should deprecate the way of passing an options hash to the `driven_by` method, but instead if someone wants to add option he can do directly mutate the  `Chrome::Option` object that we will be passing them

**Comment by seandilda** [comment]
I'm seeing the same issue in rails 5.2.0.  I will also add that this worked fine in rails 5.1.

**Comment by seandilda** [comment]
After digging into this more, I'm seeing a related, but slightly different issue.  Perhaps they have a single solution.

For my problem is a regression that appears to be caused by f52e17f1c3b59f4301a84da5ed4f46a77363f29d   Before the regression, ```options[:options]``` would be passed along for all drivers, except ```:headless_chrome``` and ```:headless_firefox```

One possible fix is to undo the regression by changing ```ActionDispatch::SystemTesting::Driver#browser_options``` to something like
```ruby
  def browser_options
    @options.merge(options: @browser.options || @options[:options]).compact
  end
```

With the regression gone, users who want to pass a custom options can do so, as long as they don't use ```:headless_chrome``` or ```:headless_firefox```.    Those option sets are pretty easy to recreate

**Comment by kentrino** [comment]
I got the same warning.

**Comment by Edouard-chin** [comment]
https://github.com/rails/rails/pull/32442 should give you a way to pass browser capabilities options

**Comment by renchap** [comment]
Issue is still here, #32442 is pending review with a fix.

**Comment by eileencodes** [comment]
Closed in https://github.com/rails/rails/pull/35081
