### ISSUE TITLE
ActiveRecord serializer called twice

### ISSUE THREAD

**Issue by remofritzsche** [rails/rails#32201]
### Steps to reproduce

As this may be a race condition, this is a issue happening very sparsely and is incredibly difficult to reproduce which is why we can't provide any example application or test this time.

We have a simple custom serializer like this in place:

```ruby
class CommaSeparatedSerializer
  SEPARATOR = ','.freeze

  def self.load(value)
    return nil if value.nil?
    return value.split(SEPARATOR)
  end

  def self.dump(value)
    return nil if value.nil?
    return value.join(SEPARATOR)
  end
end

class User
  serialize :languages, CommaSeparatedSerializer
end

# To test:

User.first.languages
```

### Expected behavior

The serializer should only be called once when accessing the respective attribute, even when concurrent requests are happening during startup of the application.

### Actual behavior

In most cases, the above code works well. Sometimes though, when requests are happening to the application while starting it up (in production mode), the serializer seems to be loaded and applied twice. From then on, the application is in this "damaged" state and the serializer does not work anymore.

By *applied twice* I mean that it is called a first time, and then this result is supplied to the serializer a second time. So with a value of `a,b,c,d`, we're getting `[['a', 'b', 'c']]` instead of `['a', 'b', 'c']` (note that it is wrapped in another array). Of course this is specific to our serializer and may lead to different problems with other ones.

### System configuration

**Rails version**: `5.1.4`

**Ruby version**: `jruby 9.1.14.0 (2.3.3)`, `java 8`

**Container**: Apache tomcat

### Conclusion

We think this a race-condition or code loading issue in Rails and possibly related to #28589 and / or #27418. We're again that we could not provide a valid sample application or test case and hope that you'll be able to look into nevertheless. Thanks a bunch for your support 👍

**Comment by matthewd** [comment]
> So with a value of `a,b,c,d`, we're getting `[['a', 'b', 'c']]` instead of `['a', 'b', 'c']`

I don't see what input could cause `CommaSeparatedSerializer.load` to return such a value

**Comment by sitroxrmeier** [comment]
This issue is still relevant for us and we would be happy if there was any progress. Thank you in advance.

**Comment by rafaelfranca** [comment]
I recommend you to try to fix it. If after 6 months nobody did it will be hardly fixed by itself.

**Comment by remofritzsche** [comment]
Thank you @wgordon17. We're using a similar workaround. Since we're serializing an array into a comma separated string, it's way easier to detect whether it has already been serialized though (`.is_a?(Array)`).

But still I think this is a serious Rails bug, possibly a concurrency issue. Unfortunately I don't have the resources to dive into a fix at this time.

**Comment by heitorsilva** [comment]
Hey guys! Me and @motine went through the same problem.

We also saw that load was called twice, and after investigation, we realized that ActiveRecord:Type:Serialized#default_value? makes a comparison like this `value == coder.load(nil)`, and thereby implicitly calling load to create the instance to compare to. Unfortunately, we can't figure out the intention behind this. Can someone explain it, please?

The workaround for us, was to do our serializer like this:

```ruby
class SomeSerializer
  class << self
    def load(value)
      return nil if value.nil?
      ...
    end
  end
end
```
