### ISSUE TITLE
Sprockets Asset was not declared to be precompiled in production. error on  Rails 4.2.6 

### ISSUE THREAD

**Issue by theasteve** [rails/rails#32204]
In development I get the following error `Asset was not declared to be precompiled in production.`
<img width="1334" alt="screen shot 2018-03-08 at 1 51 01 pm" src="https://user-images.githubusercontent.com/14843767/37173083-a49e18b2-22e0-11e8-94b2-f896e060d7ce.png">
The styles for the faq-page are in the assets folder. Is there really a need to modified assets.rb? This would mean to add each asset manually. I tried using `gem 'sprockets-rails', '~> 3.0'` without success.

### System configuration
**Rails version**:
Rails 4.2.6
**Ruby version**:
ruby 2.2.2p95 (2015-04-13 revision 50295) [x86_64-darwin17]

**Comment by y-yagi** [comment]
Rails 4.2 is not supported anymore for anything besides security fixes.
Please check whether your issue can reproduce with latest Rails.
