### ISSUE TITLE
Unresolved dependency found during sorting

### ISSUE THREAD

**Issue by reckerswartz** [rails/rails#32205]
##### sudo gem install activesupport-6.0.0.alpha.gem 
```
Fetching: concurrent-ruby-1.0.5.gem (100%)
Successfully installed concurrent-ruby-1.0.5
Fetching: thread_safe-0.3.6.gem (100%)
Successfully installed thread_safe-0.3.6
Fetching: tzinfo-1.2.5.gem (100%)
Successfully installed tzinfo-1.2.5
Fetching: i18n-1.0.0.gem (100%)
Successfully installed i18n-1.0.0
Successfully installed activesupport-6.0.0.alpha
5 gems installed 
```
### Expected behavior
Successfully installed
### Actual behavior
```
ERROR:  While executing gem ... (Gem::DependencyError)
    Unresolved dependency found during sorting - activesupport (>= 4.2.0) (requested by rails-dom-testing-2.0.3)
```
### System configuration
**Rails version** 6.0.0.alpha:

**Ruby version** 2.5.0:

**Comment by y-yagi** [comment]
Please use the [mailing list](https://groups.google.com/forum/#!forum/rubyonrails-talk) or StackOverflow for questions/help, where a wider community will be able to help you. We reserve the issues tracker for issues only.
