### ISSUE TITLE
limit in has_one condition produces different results Rails 4 -> 5

### ISSUE THREAD

**Issue by david-wolgemuth** [rails/rails#32200]
### Steps to reproduce

```
rails generate model User name:string
rails generate model Post title:string user:references
```

User Model:

```
has_one :latest_post, ->{ order(created_at: :desc).limit(1) }, class_name: :Post
```

### Expected behavior

```
User.all.includes(:latest_post).map(&:latest_post).select(&:present?).count
User.all.map(&:latest_post).select(&:present?).count
```

Both should return the same number.  (In my current app, 4.1, they both would produce the same number)

(I know there are more efficient ways to find the count, this is the easiest way I could think of to demonstrate the problem)

### Actual behavior

When using `includes`, the `limit(1)` gets applied to the `WHERE ID IN` query.

```SQL
 SELECT "users".* FROM "users"
SELECT  "posts".* FROM "posts" WHERE "posts"."user_id" IN ( ... ) ORDER BY "posts"."created_at" DESC LIMIT 1  -- SHOULD NOT BE HERE
```

This causes `User.all.includes(:latest_post).map(&:latest_post).select(&:present?).count` to always return 1.

### System configuration

**Rails version**: 5.1.5

**Ruby version**: 2.4.3

### Personal Note

After looking into this, I learned that the `limit(1)` wasn't required, so the immediate problem with my app has been solved.  I feel a good solution would be to raise a warning or error along the lines of "LIMIT IS NOT REQUIRED/ALLOWED IN HAS_ONE CONDITION" because it had worked in previous versions of rails.

**Comment by pixeltrix** [comment]
What happens if you leave the limit out of the association scope? The `has_one` will naturally apply a `limit(1)` when you try to load it so it shouldn't be needed.

**Comment by pixeltrix** [comment]
Sorry, posted with noticing the update.

As for adding the warning I don't think it's possible to do cleanly without trying to load the source code for the proc or adding the check at runtime on the relation that the proc returns, neither of which sound like good options. Also I'm not entirely sure that `limit` is not useful in some scenarios.
