### ISSUE TITLE
After rake db:reset the value of the ar_internal_metadata is dev in the test database.

### ISSUE THREAD

**Issue by orbanbotond** [rails/rails#32202]
When I do `rake db:reset` it recreates the development and the test db.

In the `test database` the `value` of the `ar_internal_metadata` is `development` but it should be `test`

For the development database it is fine.

Maybe it is related to this issue:
https://github.com/rails/rails/issues/26731

**Comment by bogdanvlviv** [comment]
@orbanbotond Thanks for the report. Could you provide a version of Rails you use?

**Comment by orbanbotond** [comment]
@bogdanvlviv oh...thx for the question. It is `5.1.4`

**Comment by bogdanvlviv** [comment]
It was fixed by https://github.com/rails/rails/pull/30579 and backported to `5-1-stable` via https://github.com/rails/rails/commit/bb67b5f278c2dbca65b9dd03038788a4dbb4a21f. Try to upgrade Rails to `5.1.5`.
Thank you!
