### ISSUE TITLE
using keyword arguments in def initialize raises an ArgumentError

### ISSUE THREAD

**Issue by matt-riemer** [rails/rails#32217]
Hey all,

First time submitting a bug here, please go easy on me...

In some of my gems I override the `def initialize` of an `ActiveRecord::Base` object and use ruby keyword arguments.  This has worked fine for me up until "5.2.0.rc1".

The following test fails when gem "activerecord", "5.2.0.rc1", but passes in "5.2.0.beta2" and lower.

### Steps to reproduce

```ruby
# frozen_string_literal: true

begin
  require "bundler/inline"
rescue LoadError => e
  $stderr.puts "Bundler version 1.10 or later is required. Please update your Bundler"
  raise e
end

gemfile(true) do
  source "https://rubygems.org"

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  # Activate the gem you are reporting the issue against.
  gem "activerecord", "5.2.0.rc1"
  gem "sqlite3"
end

require "active_record"
require "minitest/autorun"
require "logger"

# Ensure backward compatibility with Minitest 4
Minitest::Test = MiniTest::Unit::TestCase unless defined?(Minitest::Test)

# This connection will do for database-independent bug reports.
ActiveRecord::Base.establish_connection(adapter: "sqlite3", database: ":memory:")
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :posts, force: true do |t|
  end
end

class Post < ActiveRecord::Base

  def initialize(body, keyword: nil)
    # None of the following code gets run anyway:
    @body = body
    @keyword = keyword
    super()  # Call super with no arguments
  end

end

class BugTest < Minitest::Test
  def test_association_stuff
    post = Post.new('body', keyword: 'word')
    assert post.present?
  end
end
```

### Expected behavior

I should be able to use keyword arguments in `def initialize` on an ActiveRecord::Base class without error.  It should create a `Post` object.

### Actual behavior

Calling `Post.new('body', keyword: 'word')` in "5.2.0.rc1" raises the following error:

```
ArgumentError: wrong number of arguments (2 for 0..1)
/Users/matt/.rvm/gems/ruby-2.5.0/gems/activerecord-5.2.0.rc1/lib/active_record/inheritance.rb:50:in `new'
active_record_gem.rb:63:in `test_association_stuff'

1 runs, 0 assertions, 0 failures, 1 errors, 0 skips
```

### System configuration
**Rails version**:   This only affects `5.2.0.rc1`

**Ruby version**:   I have reproduced the bug in ruby 2.3, 2.4, and 2.5.

### Additional Information

@kamipo

I'm 100% sure this commit is the source of the behaviour change:

https://github.com/rails/rails/commit/d4007d5a54b60bd6924eeffb52c126ed32e9f31f#diff-3a78900604b345c3b1fec1156f23f43a

**Comment by kamipo** [comment]
Originally `Post.new('body', keyword: 'word')` raises ArgumentError for all stable versions.

https://github.com/rails/rails/blob/38c7ddd4e9f3f22f67d9615dd04a2ae9525824fb/activerecord/lib/active_record/core.rb#L299-L307

Rails does not guarantee that overriding the initialize with imcompatible definition could avoid the error due to the irregular arguments.
Please use compatible definition or override `new` instead.

**Comment by matt-riemer** [comment]
Thanks for the tip on overriding `new`

Cheers! :)
