### ISSUE TITLE
Rails.logger.reopen does not work because the @logdev does not know it's @filename

### ISSUE THREAD

**Issue by grosser** [rails/rails#32211]
### Steps to reproduce

 - start a server
 - move logfile
 - make server call `Rails.logger.reopen`
 - see that logs still go to old logfile (instead of the newly created lgofile)

that is because the logdev does not know what it's filename is:
```
rails runner 'puts Rails.logger.instance_variable_get(:@logdev).instance_variable_get(:@filename)'
```

### Workaround

```
Rails.logger.reopen Rails.logger.instance_variable_get(:@logdev).dev.path
```

### System configuration
**Rails version**: 5.1.4

**Ruby version**: 2.5.0

**Comment by y-yagi** [comment]
When `Rails.logger` makes `Logger`, `File` object is specified to `logdev`. 
https://github.com/rails/rails/blob/38c7ddd4e9f3f22f67d9615dd04a2ae9525824fb/railties/lib/rails/application/bootstrap.rb#L42-L46

However, when pass `File` object, it seems that `@filename` is not set in `LogDevice#set`. 
https://github.com/ruby/ruby/blob/af0d504f2df2d6b63ee8ce433216f294c21eb2c4/lib/logger.rb#L732..L740 

There seems to be no way to specify `@filename` from outside. Therefore, this seems like a problem with Ruby. 
Please create an issue to https://bugs.ruby-lang.org/issues/ ?

**Comment by grosser** [comment]
hmm could avoid that if we don't have to set binmode and sync, but I guess that's hard to revert ...
what do you think about using `instance_variable_set` to set the filename ?

**Comment by y-yagi** [comment]
It seems intentional behaviour that `reopen` does not work with `IO`. 
https://github.com/ruby/ruby/blob/af0d504f2df2d6b63ee8ce433216f294c21eb2c4/lib/logger.rb#L716 

Therefore, there is no guarantee that it will behave as expected just by giving filename, so I think that it is better not to do it.

**Comment by grosser** [comment]
I think this code is meant to not reopen an IO like StringIO,
but even if we make it work for a File then it would change `sync` and
`binmode` ... so not ideal
solutions I can think of are:
 - pass filename, sync, binread to ActiveSupport::Logger and make Logger
reopen with the settings we want (needs a ruby change ... so hard)
 - pass filename, sync, binread to ActiveSupport::Logger and make it
re-create a new Logger
 - make ActiveSupport::Logger trick Logger into reopening by setting
@filename and then re-set previous sync/binread on the new @dev
 - make ActiveSupport::Logger open a new file (with correct sync/binread)
and create a new Logger with that

any of these sound good to you ?

**Comment by y-yagi** [comment]
Another approach: 

I think that it is also a problem that the default log file generation is not made public. 
Does it solve the issue if it becomes possible to get the default log file? 

Like following:

```diff 
--- a/railties/lib/rails/application/bootstrap.rb
+++ b/railties/lib/rails/application/bootstrap.rb
@@ -34,16 +34,7 @@ module Bootstrap
       # Initialize the logger early in the stack in case we need to log some deprecation.
       initializer :initialize_logger, group: :all do
         Rails.logger ||= config.logger || begin
-          path = config.paths["log"].first
-          unless File.exist? File.dirname path
-            FileUtils.mkdir_p File.dirname path
-          end
-
-          f = File.open path, "a"
-          f.binmode
-          f.sync = config.autoflush_log # if true make sure every write flushes
-
-          logger = ActiveSupport::Logger.new f
+        logger = ActiveSupport::Logger.new config.default_log_file
           logger.formatter = config.log_formatter
           logger = ActiveSupport::TaggedLogging.new(logger)
           logger
diff --git a/railties/lib/rails/application/configuration.rb b/railties/lib/rails/application/configuration.rb
index 912faed..1303493 100644
--- a/railties/lib/rails/application/configuration.rb
+++ b/railties/lib/rails/application/configuration.rb
@@ -252,6 +252,18 @@ def content_security_policy(&block)
         end
       end
 
+      def default_log_file
+        path = paths["log"].first
+        unless File.exist? File.dirname path
+          FileUtils.mkdir_p File.dirname path
+        end
+
+        f = File.open path, "a"
+        f.binmode
+        f.sync = autoflush_log # if true make sure every write flushes
+        f
+      end 
```

```bash
Rails.logger.reopen(Rails.application.config.default_log_file)
```

**Comment by grosser** [comment]
that's a pretty clean change, I like it! :)
(not perfect, but a better then users having to mess with instance vars)

**Comment by rafaelfranca** [comment]
@y-yagi can you apply your patch?

**Comment by y-yagi** [comment]
Done! ee10e05af27facf42b1c49f8aaa0463d3af6989c, 5de554e76ffb3efedcbb41639b69ee7c36b39824
