### ISSUE TITLE
Active Storage: Redirect always go to localhost:3000 for Disk Storage

### ISSUE THREAD

**Issue by zumbrunnen** [rails/rails#32214]
### Expected behavior
Using the default local disk service for `config.active_storage` (and all the defaults in `config/storage.yml`), a request to an image source for an attached image (e.g. `<%= image_tag @customer.logo %>`) should get a redirect **to the same domain as the original request**.

http://my.cool.domain/rails/active_storage/blobs/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBDZz09IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--28827ae3c6d7539243df1bb174ee713fec40b095/logo.png

should get redirected to something like

http://my.cool.domain/rails/active_storage/disk/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaEpJaDFhYW1kT2QxUnhVRTQxTVdwMWNYUjRha3RJY1ZGSWRGZ0dPZ1pGVkE9PSIsImV4cCI6IjIwMTgtMDMtMDlUMTQ6MzQ6MTEuOTAwWiIsInB1ciI6ImJsb2Jfa2V5In19--7af06b3e84ca9c712835d52b9da7f1fb891e05a9/logo.png?content_type=image%2Fpng&disposition=inline%3B+filename%3D%22logo.png%22%3B+filename%2A%3DUTF-8%27%27logo.png

### Actual behavior

Instead, the redirect always goes to

http://localhost:3000/rails/active_storage/disk/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaEpJaDFhYW1kT2QxUnhVRTQxTVdwMWNYUjRha3RJY1ZGSWRGZ0dPZ1pGVkE9PSIsImV4cCI6IjIwMTgtMDMtMDlUMTQ6MzQ6MTEuOTAwWiIsInB1ciI6ImJsb2Jfa2V5In19--7af06b3e84ca9c712835d52b9da7f1fb891e05a9/logo.png?content_type=image%2Fpng&disposition=inline%3B+filename%3D%22logo.png%22%3B+filename%2A%3DUTF-8%27%27logo.png

This is environment-independent: Tested on :development and :production and with Puma and Passenger.

### System configuration
**Rails version**:
rails (5.2.0.rc1)

**Ruby version**:
ruby-2.4.1

**Comment by georgeclaghorn** [comment]
This was fixed in ccac681122db9747fec9512076772bca345e24b9.

**Comment by zumbrunnen** [comment]
Oh, @georgeclaghorn, thanks, you're faster than a :zap:
