### ISSUE TITLE
Rails application is not initialized in Rails::Configuration after_initialize callback

### ISSUE THREAD

**Issue by trushkevich** [rails/rails#32237]
Hello

### Steps to reproduce
1. create a new rails application
2. add to `config/environments/development.rb`:
```ruby
config.after_initialize do
  puts '**************** in config.after_initialize *********************'
  puts "Rails.application.initialized?: #{Rails.application.initialized?}"
  puts '*****************************************************************'
end
```
3. cd to app folder
4. run `rake routes`

Here is a sample app https://github.com/trushkevich/rails-configuration-after-initialize

### Expected behavior
It should print
```
**************** in config.after_initialize *********************
Rails.application.initialized?: true
*****************************************************************
```
### Actual behavior
It prints
```
**************** in config.after_initialize *********************
Rails.application.initialized?: false
*****************************************************************
```
#### Ruby version: 2.5.0

The docs say

https://apidock.com/rails/Rails/Configuration/after_initialize

> Adds a block which will be executed after rails has been fully initialized. Useful for per-environment configuration which depends on the framework being fully initialized.

http://guides.rubyonrails.org/configuring.html

> config.after_initialize takes a block which will be run after Rails has finished initializing the application. That includes the initialization of the framework itself, engines, and all the application's initializers in config/initializers. Note that this block will be run for rake tasks. Useful for configuring values set up by other initializers:

So I would expect `Rails.application.initialized?` to be `true` in `config.after_initialize`, but it is obviously not the case. Is it the expected behavior ?

**Comment by y-yagi** [comment]
This is intentional behavior. 
The `after_initialize` is called at the end of the whole initialize process, but it is part of the initialize process.  Therefore, even if use in `initialized?`, it returns false. 

Note that apidock.com is not an officially supported doc. Also, the information seems to be old. If you want to check about the API, please see http://api.rubyonrails.org. 
Ref: http://api.rubyonrails.org/classes/Rails/Railtie/Configuration.html#method-i-after_initialize

**Comment by trushkevich** [comment]
@y-yagi thanks for your answer. According to http://api.rubyonrails.org/classes/Rails/Railtie/Configuration.html#method-i-after_initialize :

> Last configurable block to run. Called after frameworks initialize.

IMHO if it is called **after** something - then it should not be considered a part of that something. 

I'm not sure which example is good enough, let's consider this: _After breakfast I take a shower_ - is _taking a shower_ a part of _breakfast_ ? Obviously it is not. I believe the same logic should be applied to rails initialization process and `after_initialize` callback.

> The after_initialize is called at the end of the whole initialize process

Neither of the docs says that the callback is run **at the end**, instead all of them say that it is run **after** - there is a significant difference. I would say that the docs are misguiding, but it's not only about that - the callback's name is also confusing. It's all about the word **after** which assumes something to be finished by the moment.
 
So I think that despite the behavior of `Rails.application.initialized?` in `config.after_initialize` callback is intentional, the intention itself is not correct.
