### ISSUE TITLE
`unscoped` not remembering `default_scope` for associations

### ISSUE THREAD

**Issue by project-eutopia** [rails/rails#32235]
See related: #30267

### Steps to reproduce

See gist here: https://gist.github.com/project-eutopia/16ec1e121f8e676a989b68c006521cc6

The basic problem is that `unscoped` with a block does not seem to be removing `default_scope` when using joins.  The above gist has two models defined:

```ruby
class Post < ActiveRecord::Base
  has_many :comments
  default_scope { where(active: true) }
end

class Comment < ActiveRecord::Base
  belongs_to :post
end
```

When runing a command like `Post.unscoped { Comment.joins(:post) }` it excludes comments which have an inactive post in spite of the `unscoped` on `Post`.

When looking at this problem deeper, the result of `Post.unscoped { Comment.joins(:post).count }` and `Post.unscoped { Comment.joins(:post) }.count` I found to be different:

```
[2] pry(#<BugTest>)> Post.unscoped { Comment.joins(:post) }.count
D, [2018-03-12T23:23:51.558830 #21161] DEBUG -- :    (0.2ms)  SELECT COUNT(*) FROM "comments" INNER JOIN "posts" ON "posts"."id" = "comments"."post_id" AND "posts"."active" = ?  [["active", "t"]]
=> 1
[3] pry(#<BugTest>)> Post.unscoped { Comment.joins(:post).count }
D, [2018-03-12T23:23:58.246219 #21161] DEBUG -- :    (0.3ms)  SELECT COUNT(*) FROM "comments" INNER JOIN "posts" ON "posts"."id" = "comments"."post_id"
```

This leads me to believe that the problem might be due to lazy loading.  For instance, running `Post.unscoped { Comment(:post).to_a }` returns an array of the comments I expect, because I have forced it to do the evaluation inside the block.  This problem arises when trying to do something like the following:

```ruby
comments = Post.unscoped { Comment.joins(:post) }
comments.each do |comment|
  # No comments with inactive posts seem to be present here
end
```

### Expected behavior

`Post.unscoped` should return an association that remembers that `Post` is unscoped for the queries inside of the block.

### Actual behavior

The `default_scope` seems to remain when using the association returned by `unscoped`.

### System configuration

**Rails version**: 5.1.4, 5.2.0.rc1, and 6.0.0.alpha
**Ruby version**: 2.5.0

**Comment by pixeltrix** [comment]
@project-eutopia as you've rightly surmised, the point at which you evaluate the scope is important - `unscoped` with a block will only unstop the model for the duration of that block and this is a common  pattern within Rails (e.g. Time.use_zone changes the timezone for the block) and is not a bug.

A better way of achieving what you want is to add another association, e.g:

``` ruby
class Comment < ApplicationRecord
   belongs_to :unscoped_post, -> { unscoped }, class_name: "Post"
end

comments = Comment.joins(:unscoped_post)
comments.each do |comment|
  # Comments with inactive posts here
end
```

Generally I find it's best to use default_scope sparingly - it's easy to add conditions but much harder to remove them.

**Comment by project-eutopia** [comment]
@pixeltrix Thank you for your review and clear explanation of the situation.  I agree with the decision made as to the behavior of `unscoped`, and also with your statement that it is better to avoid `default_scope` whenever possible.

I tried to use your suggestion of using a scope on the `belongs_to` association itself (thanks for teaching me something new about Rails!), but it also seems to be re-applying the `default_scope`:  https://gist.github.com/project-eutopia/e5a4a8448ce7ee7809804af92ca92143.  I hope that this is not due to just another misunderstanding of mine.

**Comment by project-eutopia** [comment]
Small follow up: it works as I expect if I change it to
```ruby
belongs_to :unscoped_post, -> { unscope(where: :active) }, class_name: "Post", foreign_key: "post_id"
```
I updated the gist to reflect this -- it works with `unscope` but not `unscoped`.

**Comment by pixeltrix** [comment]
@project-eutopia sorry, my bad - `unscoped` doesn't work because it'd remove the foreign key condition. You need to `unscope` specific bits like you've discovered.

**Comment by project-eutopia** [comment]
@pixeltrix Oh I see.  That makes things clear now.  Thanks again and sorry for the misunderstanding :bowing_man:
