### ISSUE TITLE
ActiveJob::DeserializationError (Error while trying to deserialize arguments: Can only deserialize primitive arguments: <ActionController::Parameters {"_aj_globalid"=>"gid://app/User/104"} permitted: false>)

### ISSUE THREAD

**Issue by RthiK** [rails/rails#32240]
### Steps to reproduce

(Guidelines for creating a bug report are [available
here](http://guides.rubyonrails.org/contributing_to_ruby_on_rails.html#creating-a-bug-report))

I am using AWS worker for processing the jobs. when I send mailer with the following method(passing object as parameter),
```
def send_otp_to_email
  EmailVerificationMailer.send_email_otp(self).deliver_later
end
```
It sets globalId ({"_aj_globalid"=>"gid://app/User/104"}) , while the worker processes the job (SQS post url)
` ActiveJob::Base.execute(params) `
It throws following error , 
ActiveJob::DeserializationError (Error while trying to deserialize arguments: Can only deserialize primitive arguments: <ActionController::Parameters {"_aj_globalid"=>"gid://app/User/104"} permitted: false>)

(when I execute the created job through console, It executes the job and when I send the object id alone, gobal id is not set and it successfully processes the job at worker) 

### Expected behavior
It should process the job with the globalId 

### Actual behavior
It throws ActiveJob::DeserializationError (Error while trying to deserialize arguments: Can only deserialize primitive arguments: <ActionController::Parameters {"_aj_globalid"=>"gid://app/User/104"} permitted: false>) error

### System configuration
**Rails version**: 5.1.4

**Ruby version**: 2.4.3

**Comment by rafaelfranca** [comment]
You are passing a `ActionController::Parameters` to your job and that can't be deserialized. Make sure you are passing a Hash

**Comment by RthiK** [comment]
When I execute job with same parameters it processes the job.
