### ISSUE TITLE
ActiveStorage direct upload events other than initialize not working in Firefox

### ISSUE THREAD

**Issue by dwightwatson** [rails/rails#32246]
I think this might be a follow-on from #31393 where certain ActiveStorage events would not fire correctly in Firefox. There was a commit referenced - 21417e02e906f6b64f013aafefdc0cb8ea8b5e74 - that appears to have fixed the `direct-upload:initialize` event but I'm still not seeing the other events fire in Firefox.

### Steps to reproduce
Set up a form that uses the [example direct uploads script from the documentation](http://edgeguides.rubyonrails.org/active_storage_overview.html#example) and run it in Chrome and Firefox. 

### Expected behavior
The progress indicators will appear and one-by-one fill until all attached files have been processed and the form submits in both browsers.

### Actual behavior
Firefox will show all the progress indicators but not update as any progress is made. Eventually the form will submit and it will be successful, but the user is left without any loading progress.

### System configuration
**Rails version**: Rails 5.2.0.rc1

**Ruby version**: ruby 2.5.0p0 (2017-12-25 revision 61468) [x86_64-darwin17]

**Comment by michaldarda** [comment]
I couldn't recreate your issue

**Comment by dwightwatson** [comment]
Just created a new fresh project and I can't replicate it either. I stripped the original project I noticed this issue on back to literally just ActiveStorage and the problem persists. I don't know what the cause is but it's definitely something on my end.
