### ISSUE TITLE
Use ActiveStorage from within third party libs

### ISSUE THREAD

**Issue by kstratis** [rails/rails#32251]
This is not a bug and my apologies in advance for polluting the bug tracker with questions but it's becoming increasingly difficult to find documentation or guidance on such a new feature.

So, I was wondering if its possible to use ActiveStorage in conjunction with a third party javascript uploader library like [Uppy](uppy.io) for example.

Here is my use case: 
Say I have a user signup form with the following:

* Email
* Full Name
* Avatar

Using the recommended way of uploading using ActiveStorage and `activestorage.js` (and setting `direct_uploads` to `true`) makes everything work beautifully.

 However if I choose to replace the "ugly" file form field with something more elegant like [Uppy](uppy.io) or [Dropzone](http://www.dropzonejs.com/) I can't think of a way to "programmatically" use ActiveStorage to handle this.

Please note that in such a form my model is not yet created and thus the files need to be uploaded along with the entire form. Any ideas? Thanks. 

Might be related to #32208 .

**Comment by georgeclaghorn** [comment]
You can use the [`DirectUpload`](https://github.com/rails/rails/blob/master/activestorage/app/javascript/activestorage/direct_upload.js) class directly for this purpose. Upon receiving a file from your library of choice, instantiate a `DirectUpload` and call `create` on it. `create` takes a callback that is invoked when the upload completes:

```js
import { DirectUpload } from "activestorage"

// on file selection/drop {
  const url = element.dataset.directUploadUrl
  const upload = new DirectUpload(file, url)

  upload.create((error, blob) => {
    if (error) {
      // Handle the error
    } else {
      // Add an appropriately-named hidden input to the form with a value of blob.signed_id
    }
  })
// }
```

This class is the rare exception to our rule that undocumented APIs are private. We just haven’t gotten around to documenting it yet.

**Comment by kstratis** [comment]
That's awesome! Thanks a lot!

**Comment by kstratis** [comment]
@georgeclaghorn 

Just  a quick followup...
I took a look at the code here:

https://github.com/rails/rails/blob/b3b193f7d65357970e72711d42db8070dcf92ce4/activestorage/app/javascript/activestorage/direct_upload_controller.js#L4-L10

and seems that `DirectUpload` needs to be instantiated with a `DirectUploadController` object.

so in my case, will something along these lines work?

```javascript
class MyClass extends DirectUploadController {
  constructor(input, file) {
    super(input, file)
  }
}
```

Thanks again.

**Comment by georgeclaghorn** [comment]
The delegate (the third argument to the `DirectUpload` constructor) is optional. You can omit it.

**Comment by georgeclaghorn** [comment]
One example of a situation where you’d want to provide a delegate is displaying a progress bar for the upload. Before storing the file, `DirectUpload` calls the delegate’s `directUploadWillStoreFileWithXHR` method. That method can add a progress listener to the upload request:

```javascript
import { DirectUpload } from "activestorage"

class Foo {
  constructor(file, url) {
    this.upload = new DirectUpload(this.file, this.url, this)
  }

  upload(file) {
    this.upload.create((error, blob) => {
      if (error) {
        // Handle the error
      } else {
        // Add an appropriately-named hidden input to the form with a value of blob.signed_id
      }
    })
  }

  directUploadWillStoreFileWithXHR(request) {
    request.upload.addEventListener("progress", event => this.directUploadDidProgress(event))
  }

  directUploadDidProgress(event) {
    // Use event.loaded and event.total to update the progress bar
  }
}
```

**Comment by kstratis** [comment]
Awesome! Thanks for the detailed examples and the whole guidance.

**Comment by BoleLee** [comment]
https://github.com/rails/rails/issues/32251#issuecomment-373050230
@georgeclaghorn How can I get the file uploading progress by this way? I try to use `directUploadWillStoreFileWithXHR` or `directUploadDidProgress` or `progress`, however, it returns error said it is not a function

**Comment by danielricecodes** [comment]
It would be great if the examples could be in plain vanilla JS too.  A lot of developers haven't taken the ES6 plunge yet, so the examples above don't really help all that much.  In fact, they're really confusing.

**Comment by lazaronixon** [comment]
https://gist.github.com/lazaronixon/dca1b48c241422d6347f4b0c93bec739
