### ISSUE TITLE
HashWithIndifferentAccess#[]= returns wrong value when assigning a hash

### ISSUE THREAD

**Issue by jakemack** [rails/rails#32265]
When you assign a regular hash to a key in a HashWithIndifferentAccess, it returns the regular hash but the value stored at the key is a HashWithIndifferentAccess. This is very unexpected.

The following code snippets should all return true but the first one does not:

```ruby
h = {}.with_indifferent_access
val = {}
(h['hi'] = val).object_id == h['hi'].object_id
```
```ruby
h = {}.with_indifferent_access
val = {}.with_indifferent_access
(h['hi'] = val).object_id == h['hi'].object_id
```
```ruby
h = {}.with_indifferent_access
val = []
(h['hi'] = val).object_id == h['hi'].object_id
```

**Comment by rafaelfranca** [comment]
This is how ruby works, assignments always return the argument.
