### ISSUE TITLE
Rails 5.2.0.rc1 Active Support Unable hande Singular Named Controllers

### ISSUE THREAD

**Issue by richjdsmith** [rails/rails#32264]
### Steps to reproduce
Running 5.2.0.rc1 with limited gemset, generated a singularly named controller "DasboardController" with associated helpers etc, and a corresponding view.  Set root to dashboard#index.

### Expected behavior
Would expect to behave as normal, only thing different is the naming style of the controller.

### Actual behavior
While running better_errors, I am able to see that it is failing after running `uninitialized constant DashboardsController`

In particular, it is failing on lines 540 and 541 of _activesupport (5.2.0.rc1) lib/active_support/dependencies.rb_

```
      name_error = NameError.new("uninitialized constant #{qualified_name}", const_name)

      name_error.set_backtrace(caller.reject { |l| l.starts_with? __FILE__ })
```

### System configuration
**Rails version**: 5.2.0.rc1

**Ruby version**:  2.5

I'd fix submit a PR but am just not good enough to know where it is failing and how to fix it. Would love help working through this though so I can help contribute.

**Comment by rafaelfranca** [comment]
Can you please provide a sample application that reproduces the error?

**Comment by kabhinav25** [comment]
Make sure the controller file name is dashboard_controller.rb and not dashboards_controller.rb

**Comment by richjdsmith** [comment]
@rafaelfranca Sure thing, I uploaded a version of it giving me issues here:
https://github.com/richjdsmith/for_5.2.0.rc1_debug


To run it just needs `$yarn install` and a credentials/master.key added to config.

From there, running `$rails s` and visiting localhost:3000/dashboard gets you straight to the issue.

@kabhinav25 I ensured that all controller files and associated files are named singularly, not plural, no luck :/

**Comment by matthewd** [comment]
> ```ruby
>  root 'static_pages#index'
>  resource :dashboard
> ```

That's not "Set root to dashboard#index".

Per [the guide](http://guides.rubyonrails.org/routing.html#singular-resources), when using resourceful routing, controllers are always plural:

> 📔 Because you might want to use the same controller for a singular route (`/account`) and a plural route (`/accounts/45`), singular resources map to plural controllers. So that, for example, `resource :photo` and `resources :photos` creates both singular and plural routes that map to the same controller (`PhotosController`).
