### ISSUE TITLE
Session resets between subdomains

### ISSUE THREAD

**Issue by MattiaMalonni** [rails/rails#32269]
### Steps to reproduce

    # config/initializers/session_store.rb
    Rails.application.config.session_store :cookie_store, key: '_project_session', domain: :all, tld_length: 2
    # OR (which apparently is the same, but more restrictive)
    Rails.application.config.session_store :cookie_store, key: '_project_session', domain: '.lvh.me'

### Expected behavior
Sessions should be shared between subdomains and main domain
    
### Actual behavior
Work great between subdomains and from domain to subdomain (`lvh.me -> jp.lvh.me`) but resets session from subdomain to domain (`jp.lvh.me -> lvh.me`)

### System configuration
**Rails version**: 4.2.10

**Ruby version**: 2.5.0p0

**Comment by pixeltrix** [comment]
@MattiaMalonni can you give some more details? What is the `Set-Cookie` header in the response being set to and what browser(s) are you testing in?

**Comment by MattiaMalonni** [comment]
Sure, 

**Browser**: Chrome

**Set-Cookie:** `lvh.me` _project_session=cFdEa1RqMVNtVWpwK3QzYXh3WWZ6VnNOSE9GRDh3Qm5RTUdGbWUwbWNzbGdVZ0NhN1lqeC82bGNlVm96bk1kOUl5bll3M3lOQTBINE56cHlsTDBXcmZNTXU5YUdJc2RxMXkzaUk0cVpsZXVKOUV1eEVXQjZJVjRNVHRqNmwwL3o1eVFaTzd4b0p0Mjh6VTI5MGF6V1p3PT0tLTFxdmtEa0xMakREUU5IanpEQ0lzUlE9PQ%3D%3D--5ef1acf3708b4fba64d1b51115007d3c213868d0; domain=.lvh.me; path=/; HttpOnly

**Set-Cookie:** `subdomain.lvh.me` _project_session=cWVoL21NV0RIWkhReGFSc1VOb1pzRGVMREMxOStueTAyMFVXZnRpYklYeWplOUUzc214UTVhSGxSeFUwMWtkUWpVUldldXlHcklkUDBuM09jcHViblBVd05EVmd3VFFTbkdkNndDYys2RE10bERIVWdYVitMK1Z1SlpwQTFobFViTU12QzdEYS84NlZTMGZjK1dtVDZRPT0tLVdIVEJLTlQ1N2ZzaktzbzJha2p6OEE9PQ%3D%3D--09ece9f18ad076d77e29d29458bdfd26b2325220; domain=.lvh.me; path=/; HttpOnly

**Comment by MattiaMalonni** [comment]
Just figured out that **Firefox** seems to behave correctly, as well as **Safari** (not tested in IE).

**Comment by pixeltrix** [comment]
@MattiaMalonni have you tried without the leading '.' in Chrome?

**Comment by hananamar** [comment]
@MattiaMalonni why did you close this? did you find a way to solve this in chrome?

**Comment by bmahnke** [comment]
I'm still seeing this behavior in Chrome on my versions of ruby/rails. 

```
rails: 6.0.1
ruby: 2.6.5p114
```

**Comment by noragem** [comment]
I have the same behavior
