### ISSUE TITLE
Cannot set 'on_delete' in migration with MySQL

### ISSUE THREAD

**Issue by nehero** [rails/rails#32263]
### Steps to reproduce

Using gem 'mysql2' for the activerecord adapter

In your migration:

```ruby
class CreateDepthChartPositions < ActiveRecord::Migration[5.1]
  def change
    create_table :depth_chart_positions do |t|
      t.references :position
    end

    add_foreign_key :depth_chart_positions, :position, on_delete: :cascade
  end
end
```

Link to docs http://api.rubyonrails.org/classes/ActiveRecord/ConnectionAdapters/SchemaStatements.html#method-i-add_foreign_key

### Expected behavior
It should set the on delete property on the foreign key

### Actual behavior
On delete is not set

```
CONSTRAINT `fk_rails_c0d08bfee6` FOREIGN KEY (`position_id`) REFERENCES `positions` (`id`)
```

### System configuration
**Rails version**: ~5.4.1~ 5.1.4

**Ruby version**: 2.4.0

**MySQL**: 5.5.5-10.1.14-MariaDB

I've also tried making the second parameter in `add_foreign_key` to the plural table name `:positions`. Still no luck. Have also tried `t.references :position, foreign_key: { on_delete: :cascade }`

**Comment by rafaelfranca** [comment]
Which version of Rails are you using? 5.1.4?

**Comment by nehero** [comment]
Haha yeah that'd be it. Apparently I can't read correctly

**Comment by nehero** [comment]
Ah. Didn't know that rails cached schema in `db/schema.rb`. I think that's the issue. Going to test and come back to close if that's the case

**Comment by nehero** [comment]
Yeah that was the issue. I dropped the db / fixed a migration / reran the migration and it wasn't updating because the `config/schema.rb` had not changed.

Doing:

```
rails db:drop
rails db:create
rails db:schema:dump
rails db:migrate
```

fixed the issue. (Obviously don't do this on production 😆 )
