### ISSUE TITLE
ActiveJob: Remove Qu gem support

### ISSUE THREAD

**Issue by albertoalmagro** [rails/rails#32273]
# Summary
While I was taking a look to `ActiveJob`'s code I found this [TODO](https://github.com/rails/rails/blob/245c1dafa8bab409fbcd780a996c619240df7143/activejob/Rakefile#L5) about the Qu gem. The [Qu gem](https://github.com/bkeepers/qu)'s development seems to be discontinued since its last commit was 4 years ago.

I propose to definitely remove it from the source code and from the documentation. I have already started a branch to remove it, if you give me the OK I will submit a PR with it.

Many thanks.

**Comment by pixeltrix** [comment]
I pinged a tweet to the maintainers - if they confirm its demise then yes, let's remove it.

**Comment by pixeltrix** [comment]
@albertoalmagro okay, looks like there's no plans to bring it up to date so go ahead and create a PR, thanks.

**Comment by albertoalmagro** [comment]
Thanks @pixeltrix for pinging them and confirming it. I will let you know when its ready. Thanks!

**Comment by albertoalmagro** [comment]
@pixeltrix PR is ready: #32300

Thanks in advance.
