### ISSUE TITLE
ActionView::Template::Error: undefined method `rstrip' for nil:NilClass

### ISSUE THREAD

**Issue by yasirrose** [rails/rails#32272]
I am sending email to you user on account creation. 
But rails is throwing following error:

```
ActionView::Template::Error: undefined method `rstrip' for nil:NilClass
    app/mailers/user_mailer.rb:32:in `new_user'
    app/controllers/users_controller.rb:42:in `block (2 levels) in create'
    app/controllers/users_controller.rb:39:in `create'
```
My users controller create method: 
```
  def create
    @user = User.new(user_params)
    respond_to do |format|
      if @user.save
        #render plain:  params[:user][:password]
        UserMailer.new_user(@user, params[:user][:password]).deliver
        format.html {
          redirect_to users_path, notice: "Admin was successfully created."
        }
      else
        format.html { render :new }
      end
    end
  end

```
My users controller new_user method: 
```

def new_user(user, password)
    @user = user
    mail(to: "abc@gmail.com", subject: "You have been added to fanhub")
  end
end
```
it is giving me error on mail function. My email template is: 

`this is test`

Any one can help me that why i am getting this issue and how can i resolve it?

**Comment by joshmn** [comment]
Please use the mailing list or StackOverflow for questions/help, where a wider community will be able to help you. The issues tracker is reserved for issues only.

**Comment by y-yagi** [comment]
Please use the [mailing list](https://groups.google.com/forum/#!forum/rubyonrails-talk) or StackOverflow for questions/help, where a wider community will be able to help you. We reserve the issues tracker for issues only.
