### ISSUE TITLE
Dependent option support for has_and_belongs_to_many association

### ISSUE THREAD

**Issue by kreintjes** [rails/rails#32291]
### Steps to reproduce
HABTM (has_and_belongs_to_many) associations do not support the dependent option, while other association types do. Of course not all dependent options make sense for HABTM associations, but some of them do. Suppose we have an Author that has and belongs to many Books (an Author can write multiple Books, a Book could be written by multiple Authors), then we might want to show an error when trying to destroy an Author that is still linked to Books. 

Suppose we have the following model:

```
class Author < ApplicationRecord
  has_and_belongs_to_many :books, dependent: :restrict_with_error, foo: :bar
end
```

### Expected behavior
When I call destroy on an Author with books, I would expect the destroy to fail and an error message to be set. Or if the dependent option is intentionally unsupported for HABTM association, then I would at least expect an exception when trying to set the option, as is done for unsupported options for other association types.

Furthermore I would expect an error to be triggered for the unsupported option `foo` either way: `ArgumentError: Unknown key: :foo. Valid keys are: : ...`

### Actual behavior
The destroy on the Author with books is not blocked and no error is triggered. Also I don't get an exception setting unsupported options on HABTM associations, while this does happen for other association types.

### Questions
1. Is the dependent option intentionally unsupported for HABTM associations?
2. If not, what values would we like to support for dependent on HABTM associations and how should they behave?
3. Do we want to trigger an exception when trying to set unsupported options on HABTM associations?
4. Any advice on how to implement this? I did a quick study of the code and see HABTM associations behave kind of differently from other (e.g. has_many) associations. They are not an association in it self, but instead use has_many and belong_to association on a fake JoinModel. I could just write new code in the [HasAndBelongsToMany builder class](https://github.com/rails/rails/blob/5-2-stable/activerecord/lib/active_record/associations/builder/has_and_belongs_to_many.rb) to implement this, but it would be nicer if we could somehow reuse the functionality already in place for [has_many associations](https://github.com/rails/rails/blob/5-2-stable/activerecord/lib/active_record/associations/has_many_association.rb) and the [association builder base class](https://github.com/rails/rails/blob/5-2-stable/activerecord/lib/active_record/associations/builder/association.rb).

### System configuration
**Rails version**: 5.2.0.rc1

**Ruby version**: 2.4.1

**Comment by pixeltrix** [comment]
Hi @kreintjes, yes HABTM intentionally doesn't support dependent options because if that's really needed you should probably be using `has_many :through` with a join model as you're probably missing one from your domain model (FYI, HABTM is a custom HMT association). To take your author/book example, the join model you're missing could be a publishing contract. Even if there's no specific model it's likely that you want to add additional attributes to the join which again you need to use a HMT association for.

You're right that we should be raising an exception with invalid options - the reason it doesn't like other association methods is because the builder doesn't inherit from the base association builder - happy to accept a PR that adds an exception for unsupported options.

**Comment by kreintjes** [comment]
I have a real world application where we have some HABTM associations where we are currently using a custom before_destroy callback to prevent the destroy if the association is present (i.e. if the thing we want to destroy is used by some other thing). It would be nice if we could just use the dependent option. I know we could if we use a HMT association with a join model, but we (currently) have no other need for the join model except for setting the dependent. It feels a bit tedious to add the join model and split the associations ourselves, just to set the dependent.

Anyway, thanks for the clarification @pixeltrix! I will try to create a PR for raising an exception on invalid options in the coming days.

**Comment by alaatarek95** [comment]
is this issue solved or still open??
