### ISSUE TITLE
3 failures with Ruby 2.6.0.dev showing "Bad Request"

### ISSUE THREAD

**Issue by yahonda** [rails/rails#32294]
### Steps to reproduce

Recently `GEM=railties` and `GEM=ap, ac` unit tests are failing with ruby-head.

* Last successful build https://travis-ci.org/rails/rails/builds/351113824
* First failures since https://travis-ci.org/rails/rails/builds/351204355

It does not look like these failures triggered by Rails code change. I'm wondering if these failures are related to changes at Ruby.

* Ruby version used at the last successful build
```
$ ruby --version
ruby 2.6.0dev (2018-03-07 trunk 62693) [x86_64-linux]
```

* Ruby version used at the first failed build
```
$ ruby --version
ruby 2.6.0dev (2018-03-09 trunk 62705) [x86_64-linux]
```

Taking a look at Ruby differences between `62693` and `62705` I have found [Revision 62695
](https://svn.ruby-lang.org/cgi-bin/viewvc.cgi?revision=62695&view=revision) at Ruby which changes some encoding behavior. 

I understand it is too early to say what causes these failures, then let me provide steps to reproduce with `ruby 2.6.0dev (2018-03-19 trunk 62840) [x86_64-linux]`

```ruby
$ cd railties
$ bundle exec ruby -Itest test/application/assets_test.rb -n test_precompile_should_handle_utf8_filenames
Run options: -n test_precompile_should_handle_utf8_filenames --seed 26402

# Running:

F

Failure:
ApplicationTests::AssetsTest#test_precompile_should_handle_utf8_filenames [test/application/assets_test.rb:334]:
Expected /not\ an\ image\ really/ to match "Bad Request\n".


bin/rails test test/application/assets_test.rb:318



Finished in 7.297453s, 0.1370 runs/s, 0.5481 assertions/s.
1 runs, 4 assertions, 1 failures, 0 errors, 0 skips
$
```

```ruby
$ cd actionpack
$ bundle exec ruby -Itest test/dispatch/static_test.rb -n test_served_static_file_with_non_english_filename
Run options: -n test_served_static_file_with_non_english_filename --seed 54001

# Running:

F

Failure:
StaticTest#test_served_static_file_with_non_english_filename [test/dispatch/static_test.rb:74]:
--- expected
+++ actual
@@ -1,2 +1,2 @@
-"means hello in Japanese
+"Bad Request
 "



bin/rails test test/dispatch/static_test.rb:73

F

Failure:
StaticEncodingTest#test_served_static_file_with_non_english_filename [test/dispatch/static_test.rb:74]:
--- expected
+++ actual
@@ -1,2 +1,2 @@
-"means hello in Japanese
+"Bad Request
 "



bin/rails test test/dispatch/static_test.rb:73



Finished in 0.048943s, 40.8635 runs/s, 40.8635 assertions/s.
2 runs, 2 assertions, 2 failures, 0 errors, 0 skips
$
```

### Expected behavior
All of them should finish successfully as Ruby 2.5.0 does.

### Actual behavior
3 failures reported above.

### System configuration
**Rails version**:master branch

**Ruby version**:ruby 2.6.0dev (2018-03-19 trunk 62840) [x86_64-linux]

**Comment by pixeltrix** [comment]
Looks like that change broke the `needs_monkeypatch` check in [core_ext/uri.rb][1].

However looking at the implementation of `unescape` I wonder whether the encoding should be forced to UTF-8 before being passed to it since it sets the encoding back to the original and has done since 1.9.2. Not sure whether that should be done in Rack or Rails.

[1]: https://github.com/rails/rails/blob/master/activesupport/lib/active_support/core_ext/uri.rb#L7-L12

**Comment by pixeltrix** [comment]
Looks like this changed recently in #32210 (original bug report is #32183).

**Comment by yahonda** [comment]
Thanks for the update and pointing out the useful information.

since Ruby 2.6.0 including Revision 62695 https://svn.ruby-lang.org/cgi-bin/viewvc.cgi?revision=62695&view=revision will not raise `Encoding::CompatibilityError (incompatible character encodings: UTF-8 and ASCII-8BIT)` for `parser.unescape(str + parser.escape(str).force_encoding(Encoding::UTF_8))`.

Then I have opened #32314 to change the condition for monkey patching will address these 3 failures. 

Going back to the discussion if monkey patched `unescape` encoding should be forced to UTF-8 or not, Actually I do not have a better background for this discussion. Rails 6 nor Ruby 2.6 are not released yet, I think we will have enough time to discuss it between Ruby committers and Rails contributors. let me cc Ruby committer @nurse who committed Revision 62695 to Ruby.

**Comment by nurse** [comment]
I fixed ruby's URI#unescape as Rails monkeypatched at [r62897](https://github.com/ruby/ruby/commit/234a30459cdae6aa7da6e28a1082d9c11f315696).
It's also expected to fix this issue.

**Comment by yahonda** [comment]
Thanks for providing a fix for Ruby revision r62897. I have confirmed r62897 also addresses this issue and opened #32319 to change the condition for monkey patching `URI#unescape`.

**Comment by nurse** [comment]
For non MRI implementations, the current condition of monkey patching seems already fine and better than RUBY_VERSION.

**Comment by rafaelfranca** [comment]
Thanks @nurse and @yahonda!

**Comment by yahonda** [comment]
@nurse I see your point. As of now JRuby is the only one non MRI implementation which can run Rails. The latest JRuby `jruby 9.2.0.0-SNAPSHOT` is compatible with Ruby 2.4 then there is no JRuby version compatible with Ruby 2.6 yet. I have tested how JRuby handles mixed encodings and I think it is safe to handle monkey patching by `RUBY_VERSION`. https://gist.github.com/yahonda/70d54f9725ce81397d7e6f584667a9d7 

I wanted non MRI implementation compatible with Ruby 2.6 will behave like and r62695 and r62897
