### ISSUE TITLE
Backport loofah version 2.2.1 to latest 5.0.x

### ISSUE THREAD

**Issue by jaegerpicker** [rails/rails#32301]
`loofah` reported a XSS/Code injection CVE today for all versions prior to `2.2.1`. Rails version `5.1.5` upgrades to `2.2.1` but rails `5.0.6` is still at `2.2.0`. 

### Expected behavior
patch `5.0.x` to use `loofah` `2.2.1`

**Comment by guilleiguaran** [comment]
Just created an app with 5.0.6 and the bundled version of loofah is 2.2.1:

```
~/src/loofah-demo % rails -v
Rails 5.0.6
~/src/loofah-demo % bundle show loofah
/Users/guillermo-iguaran/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/loofah-2.2.1
```

**Comment by jaegerpicker** [comment]
Hmm... I did a fresh install and it installs `2.2.1` with `5.0.6`. Closing this as I was able to get it working, thanks!
