### ISSUE TITLE
Branch 5-2-stable is missing 5.2.0.rc2

### ISSUE THREAD

**Issue by genezys** [rails/rails#32308]
Sorry if this is a normal behavior for a Rails release but I did not expect it, so I am opening this issue to notify anyone in case this is a mistake. Feel free to close if this is in anyway a misunderstanding on my side.

### Expected behavior

Branch `5-2-stable` should contain the last commit of 5.2.0.rc2 : db7edd81062648281d1e50c8ff9ebfafac5a9c3d

### Actual behavior

Branch `5-2-stable` does not contain the version 5.2.0.rc2 but instead, there is a new branch `5-2-0` containing the commit.

---

Thanks for the great work and congratulations on this 5.2.0.rc2 release 🙂

**Comment by rafaelfranca** [comment]
Yes, that is the correct behavior. 5-2-stable will be 5.2.1, 5-2-0 will be 5.2.0

**Comment by genezys** [comment]
Thank you for taking the time to explain 👍
