### ISSUE TITLE
JRuby 9.2.0 shows `LoadError: no such file to load -- io/console/size`

### ISSUE THREAD

**Issue by yahonda** [rails/rails#32318]
CI with jruby-head for actionpack has been failing at Travis https://travis-ci.org/rails/rails/jobs/356541503

### Steps to reproduce
```ruby
$ cd actionpack
$ bundle install
$ bundle exec ruby -Itest test/journey/routes_test.rb
```

I think this is not specific to `routes_test.rb`. It could reproduce almost every test.

### Expected behavior
Tell us what should happen

### Actual behavior
```ruby
$ bundle exec ruby -Itest test/journey/routes_test.rb
LoadError: no such file to load -- io/console/size
             require at org/jruby/RubyKernel.java:969
    block in require at /home/yahonda/git/rails/activesupport/lib/active_support/dependencies.rb:283
     load_dependency at /home/yahonda/git/rails/activesupport/lib/active_support/dependencies.rb:249
             require at /home/yahonda/git/rails/activesupport/lib/active_support/dependencies.rb:283
              <main> at /home/yahonda/git/rails/actionpack/lib/action_dispatch/routing/inspector.rb:4
             require at org/jruby/RubyKernel.java:969
     block in (root) at /home/yahonda/git/rails/activesupport/lib/active_support/dependencies.rb:1
             require at /home/yahonda/git/rails/activesupport/lib/active_support/dependencies.rb:283
     load_dependency at /home/yahonda/git/rails/activesupport/lib/active_support/dependencies.rb:249
              <main> at /home/yahonda/git/rails/activesupport/lib/active_support/dependencies.rb:283
     block in (root) at /home/yahonda/git/rails/actionpack/lib/action_dispatch/middleware/debug_exceptions.rb:5
              (root) at /home/yahonda/git/rails/actionpack/test/abstract_unit.rb:1
           build_app at /home/yahonda/git/rails/actionpack/test/abstract_unit.rb:105
          initialize at /home/yahonda/git/rails/actionpack/lib/action_dispatch/middleware/stack.rb:47
  <class:initialize> at /home/yahonda/git/rails/actionpack/test/abstract_unit.rb:93
              <main> at /home/yahonda/git/rails/actionpack/test/abstract_unit.rb:103
             require at org/jruby/RubyKernel.java:969
              <main> at /home/yahonda/git/rails/actionpack/test/abstract_unit.rb:115
$
```

### System configuration
**Rails version**:master branch

**Ruby version**:jruby 9.2.0.0-SNAPSHOT (2.4.1) 2018-03-15 36b44df Java HotSpot(TM) 64-Bit Server VM 25.161-b12 on 1.8.0_161-b12 [linux-x86_64]

**Comment by yahonda** [comment]
`GEM=am,amo,aj` is also getting the same `LoadError: no such file to load -- io/console/size` https://travis-ci.org/rails/rails/jobs/356541504

**Comment by yahonda** [comment]
cc @headius @enebo

**Comment by headius** [comment]
A new addition to the io/console library it seems?

**Comment by yahonda** [comment]
Doing `git bisect` and found #32160 requires "io/console/size"

**Comment by enebo** [comment]
@yahonda a more useful reference may be when ruby stdlib included it version-wise.  The fact rails includes it is a big deal though.

**Comment by bogdanvlviv** [comment]
`IO.console_size` was added in https://github.com/ruby/ruby/commit/aef01ee7890bf6b2349c4c87548460ce9534dfb0

**Comment by y-yagi** [comment]
Workaround: 
`IO.console_size` is wrapper for `IO.console.winsize`. Therefore, if can not use `console_size`, can avoid using `console.winsize`. 
Ref: [Workaround for JRuby console size.](https://github.com/ruby/rdoc/pull/518)

**Comment by headius** [comment]
Ahh it's just a pure-Ruby item. We are likely just not copying it from MRI. I'll get that fixed.

**Comment by headius** [comment]
This is now fixed on JRuby master.

**Comment by robin850** [comment]
Awesome folks ! Thanks for reporting @yahonda and thanks for the quick fix @headius !

**Comment by yahonda** [comment]
Validated the fix https://travis-ci.org/rails/rails/jobs/359123642 Thank you.
