### ISSUE TITLE
Active Storage uploading files from a remote location

### ISSUE THREAD

**Issue by ipatovanton** [rails/rails#32327]
Do you have ability to uploading files from a remote location via URL?

**Comment by y-yagi** [comment]
Please use the [mailing list](https://groups.google.com/forum/#!forum/rubyonrails-talk) or StackOverflow for questions/help, where a wider community will be able to help you. We reserve the issues tracker for issues only.

**Comment by redtachyons** [comment]
Duplicate of #30819
