### ISSUE TITLE
5.2.0.rc2, master: `touch(:updated_at)` causes multiple assignments to same column in Postgresql

### ISSUE THREAD

**Issue by khustochka** [rails/rails#32323]
### Steps to reproduce
1. Use Postgresql as DB.
2. Have a Post model with timestamps.
3. Create a post: `post = Post.create!`
4. Call `post.touch(:updated_at)`

### Expected behaviour
Post's updated_at should be changed without error.

### Actual behaviour
Error happens: 

> ActiveRecord::StatementInvalid: PG::SyntaxError: ERROR:  multiple assignments to same column "updated_at"
> : UPDATE "posts" SET "updated_at" = $1, "updated_at" = $2 WHERE "posts"."id" = $3

### Executable test case

https://gist.github.com/khustochka/cab304cfece8752d7d37715013e0cdb8

### System configuration
**Rails version**:
5.2.0.rc2, master

**Ruby version**:
2.5.0

**DB adapter**
Postgresql

### Notes
* This is also reproduced if you have an associated model with `belongs_to :post, touch: :updated_at`
* This can be bypassed with `touch: true` because `updated_at` is the default column to touch.
* But it worked before, not reproducible in 5.2.0.rc1 and prior versions.

**Comment by Edouard-chin** [comment]
If this can help I ran a bisect,  the commit introducing this is https://github.com/rails/rails/commit/37a1dfad39756499305e19620aa97f630d32fc07 

FYI @kamipo

**Comment by kamipo** [comment]
Thanks for the report.


The multiple assignments was caused by 37a1dfa due to lost the `to_s` normalization for given names.

I've fixed in 6aa5cf03ea8232180ffbbae4c130b051f813c670  and backported in 21844bad40c500c4e0c161916006443fc7e9d891.
