### ISSUE TITLE
undefined method `string' for #<Entry:0x00007f56a005c398> Did you mean? String

### ISSUE THREAD

**Issue by amarradi** [rails/rails#32320]
Im writing a Application which has following Model Design

`Model A has_many bs`
`Model B belongs_to a`
b is sigular an bs/BS is plural
a is singular and as/AS is plural
 and i'm using an Admin-controller to define what the users can do

`class Admin::BsController < ApplicationController`
`def create`
 `  @a = A.find(params[:a_id])`
  ` @b = @a.bs.create(entry_params)`
  `  redirect_to a_path(@a)`
  `end`
The form in the view is show.html.erb is generated like
`<%= form_with(model: [:admin, @a,B.new ], local: true) do |f| %>`
...
`<%= end %>`
### Expected behavior
Tell us what should happen
The new DB-entry which belongs_to a should be created.
### Actual behavior
Tell us what happens instead
I get an error

`NoMethodError in Admin::EntriesController#create`
`undefined method ``string' for #<B:0x00007f93a8090450> Did you mean? String`

### System configuration
**Rails version**: Rails 5.1.5

**Ruby version**: Ruby 2.5.0p0

**Comment by rafaelfranca** [comment]
Can you please provide a sample application that reproduces the error?

**Comment by amarradi** [comment]
The bug is in my own sourcecode not in Rails. I used an very old model-code and this code based on an other idea. Sorry! I close this bug. It is solved
