### ISSUE TITLE
Should AR 4.2 and 5.0 support Mysql2 0.5.0??

### ISSUE THREAD

**Issue by lxbrito** [rails/rails#32322]
Gem Mysql2 0.5.0 is out and I couldn't find any technical reason for Rails 4.2 not to support it. 
I tested it with some large Rails 4.2 apps in homolog, after all tests passed, and all went fine.

I know Rails 4.2 is near EOL, But it seems that 5.0 has not been updated.

Thanks

**Comment by rafaelfranca** [comment]
Rails 4.2 is already EOL, and 5.0 is too see http://guides.rubyonrails.org/maintenance_policy.html. They only receive security fixes now.
