### ISSUE TITLE
Initializing with ActiveSupport::TimeZone with Numeric is not consisitent with the given offset

### ISSUE THREAD

**Issue by nobuhikosawai** [rails/rails#32333]
### Steps to reproduce

Example
```rb
tz = ActiveSupport::TimeZone.new(-5 * 3600) #-28800
#=> #<ActiveSupport::TimeZone:0x00007fb4572b3460 @name="Pacific Time (US & Canada)", @tzinfo=#<TZInfo::DataTimezone: America/Los_Angeles>, @utc_offset=nil>

tz.local(2018, 1, 1)
#=> Mon, 01 Jan 2018 00:00:00 PST -08:00
tz.local(2018, 1, 1).utc_offset
# => -28800

tz.local(2018, 8, 1)
#=> Wed, 01 Aug 2018 00:00:00 PDT -07:00
tz.local(2018, 8, 1).utc_offset
# => -25200 #Although this instance is generated by -28800, it is changed unexpectedly.
```
### Expected behavior
Because this instance is created by `-28800`, it should be consistent regardless of summertime or not.

```ruby
tz = ActiveSupport::TimeZone.new(-5 * 3600) #-28800
tz.local(2018, 8, 1).utc_offset
# => -28800
```

One of my sample approach is the gem I have created called [VirtualTimeZoneRails](https://github.com/nobuhikosawai/virtual_time_zone_rails). It returns new TZInfo::Timezone instance which only considers the given offset.

### Actual behavior
ActiveSupport::TimeZone creates instance by referring actual timezone.
https://github.com/rails/rails/blob/6aa5cf03ea8232180ffbbae4c130b051f813c670/activesupport/lib/active_support/values/time_zone.rb#L237
Even developers want to use fixed offset, it depends on  the tiemzone that ActiveSupport::TimeZone finds.

```ruby
tz = ActiveSupport::TimeZone.new(-5 * 3600) #-28800
tz.local(2018, 1, 1).utc_offset
# => -28800
tz.local(2018, 8, 1).utc_offset
# => -25200
```

### System configuration
**Rails version**:
5.2.0 beta2
**Ruby version**:
2.5.0

**Comment by pixeltrix** [comment]
For legacy reasons passing in a numeric will find the actual timezone with that offset (note you can just pass in an hour value too), e.g.

``` ruby
"2018-08-01".in_time_zone(-8).utc_offset # => -25200
```

Since these are named timezones they will follow DST rules and changing this behaviour would be a breaking change. If you really just want to deal with UTC offsets then you can use the `Etc/GMT` set of timezones, e.g:

``` ruby
"2018-08-01".in_time_zone("Etc/GMT+8").utc_offset # => -28800
```

Note that the +/- signs are opposite to what you expect because of rules within the POSIX spec.
