### ISSUE TITLE
Rails Console Sandbox

### ISSUE THREAD

**Issue by adityavarma1234** [rails/rails#32349]
Rails console sandbox is not rolling back database changes.

### Steps to reproduce

`rails c -s`

### Expected behavior
```
rails c -s
User.count => 0
User.create 
User.count => 1
```
--------- Console Exit -----------
```
rails c 
User.count => 0
```

### Actual behavior
```
rails c -s
User.count => 0
User.create 
User.count => 1
```
--------- Console Exit -----------
```
rails c 
User.count => 1
```

### System configuration
**Rails version*: 4.2.4

**Ruby version**:  2.3.3-p222 (x86_64-darwin16)

**Database**: Mongo Version 3.4.9, Mongoid version 5.2

**Comment by simi** [comment]
I just tested our app at `Rails 4.2.9` and it works without problems with `ActiveRecord`.

**Comment by adityavarma1234** [comment]
Thanks for letting me know. Will look into mongoid.

**Comment by matthewd** [comment]
Rails 4.2 is also no longer supported
