### ISSUE TITLE
Feature Request: Reset column information for AR models after every DDL change.

### ISSUE THREAD

**Issue by fresho-app** [rails/rails#32354]
Feature request: Reset column information for AR models after every DDL change.

Ruby 2.4.2
Rails 4.2.10

Where I work, we have a tendency to create and use migration-specific models for performing data migrations. If we use a migration-specific model, add a column, and then attempt to populate that column all in the same run of `rake db:migrate`, the population of the column will fail, and probably fail silently; we discovered this when our `change_column_null` following the data migration proceeded to fail. Of course, this is without using `reset_column_information`. This will also still happen with two different migration models that point at the same table - there's column information centrally cached somewhere in AR.

Example of a migration using migration-specific model that will fail:

```ruby
class MyMigration < ActiveRecord::Migration
  class MyPostModel < ActiveRecord::Base
    self.table_name = 'my_posts'
  end

  def up
    MyPostModel.count # access the table somehow
    
    add_column :my_posts, :short_description, :string

    MyPostModel.find_each do |my_post|
      my_post.new_col = my_post.short_description = my_post.description.truncate(40)
      my_post.save!
    end

    change_column_null :my_posts, :short_description, false # This will fail
  end
end
```

With the addition of `.reset_column_information` this can work:

```ruby
class MyMigration < ActiveRecord::Migration
  class MyPostModel < ActiveRecord::Base
    self.table_name = 'my_posts'
  end

  def up
    MyPostModel.count # access the table somehow
    
    add_column :my_posts, :short_description, :string
    # NEEDED TO CLEAR THE CACHED SCHEMA INFO
    MyPostModel.reset_column_information 

    MyPostModel.find_each do |my_post|
      my_post.new_col = my_post.short_description = my_post.description.truncate(40)
      my_post.save!
    end

    change_column_null :my_posts, :short_description, false # This will fail
  end
end
```

However, this is easy to forget and this is sometimes not discovered until deploying to an environment where multiple migrations are run together (eg. deploying to production).

Now, we know that this way of performing data migration or changes to data is not very fast, but is much easier for some developers to understand - not everybody knows SQL very well.

Our current work-around to stop developers forgetting to use `reset_column_information` is to use a subclass of `ActiveRecord::Migration`, which calls `reset_column_information` after every DDL change, like so:

```ruby
class ApplicationMigration < ActiveRecord::Migration
  %i(
      add_column rename_column add_reference
      change_table create_table change_column
      change_column_default change_column_null
  ).each do |method_name|
    define_method method_name do |table_name, *opts|
      super(table_name, *opts)
      reset_column_information_for(table_name)
    end
  end

  private

  def reset_column_information_for(table_name)
    ActiveRecord::Base.descendants.each do |model|
      if model.table_name.to_s == table_name.to_s
        model.reset_column_information
      end
    end
  end
end
```

**Comment by y-yagi** [comment]
Thanks, but we don’t take feature requests in the issue tracker. Please use the [Rails Core mailing list](https://groups.google.com/forum/#!forum/rubyonrails-core) for feature requests, where a wider community will be able to help you. We reserve the Rails issue tracker only for bugs in Rails.
