### ISSUE TITLE
Set S3 bucket path in Active Storage

### ISSUE THREAD

**Issue by olimart** [rails/rails#32358]
Active Storage - Applicable to S3 config. (maybe others too)

### Expected behavior
It would be great to be able to set path within bucket as an option. Applicable to AWS S3, not sure about the other cloud services.

### Actual behavior
Currently `storage.yml` has no key for path for AWS S3.

### System configuration
**Rails version**: 5.2.0.rc2
**Ruby version**: 2.5

**Comment by georgeclaghorn** [comment]
You’re intended to create a bucket for Active Storage to use exclusively. See #31871.
