### ISSUE TITLE
Unknown encoder in ActionDispatch::IntegrationTest is silently ignored

### ISSUE THREAD

**Issue by jjb** [rails/rails#32353]
### Steps to reproduce

```ruby
get "/mypage", as: :foobar
```

### Expected behavior

Test should have an error when trying to use an encoder which does not exist.

### Actual behavior

Test silently continues.

### System configuration
**Rails version**: 5.1.5

**Ruby version**: 2.5.0

**Comment by jjb** [comment]
`rails c`

```
require "action_dispatch/testing/request_encoder"
cd ActionDispatch::RequestEncoder
@encoders
```

**Comment by rafaelfranca** [comment]
That is by design. If you pass an unknown encoder it will use the identity encoder.

**Comment by jjb** [comment]
@rafaelfranca gotcha. What's the reasoning? It seems to be that if a user passes an encoder, that means that they are under the impression that it exists. Would you be open to a PR to raise an error in this scenario?

**Comment by rafaelfranca** [comment]
The reason is because users can register different encoders so raising when you are not using one of the framework encoders would break that behavior. If we can change it to raise without breaking that I'm open to a PR.

**Comment by jjb** [comment]
By "unknown" I meant unregistered. I just updated the title of this issue to reflect this. 

Here: https://github.com/rails/rails/blob/master/actionpack/lib/action_dispatch/testing/request_encoder.rb#L45-L47

```ruby
def self.encoder(name)
  @encoders[name] || @encoders[:identity]
end
```

`@encoders` is the built-in json encoder + any user-defined encoders.

If a user specifies `as:  :foo`, then they must expect either a built-in or user-added encoder which handles `:foo` to be present, no?

I can't imagine a scenario where `|| @encoders[:identity]` is desirable. It's quite possible I'm not aware of something though! If so let me know.

So, I propose this change:

```ruby
def self.encoder(name)
  encoder = @encoders[name]
  unless encoder
    raise ArgumentError, "There is no encoder registered for name " \
      "#{name}. See `ActionDispatch::IntegrationTest.register_encoder`."
  end
end
```

What do you think?

**Comment by kaspth** [comment]
If we do

```ruby
@encoders.fetch(name) do
  raise ArgumentError, "…"
end
```

I'm all for it 👍

**Comment by jjb** [comment]
@kaspth sounds good. just to be clear -- is that simply a style change or is there also a semantic difference?

**Comment by kaspth** [comment]
In this case it's just a style change to spare the local variable. `fetch` without a block (or a second argument) would raise `KeyError` if the key wasn't present. So it's closer to our intent, but we just override the thrown exception 😊
