### ISSUE TITLE
`.pluck`ing JSONB fields always creates a DB query

### ISSUE THREAD

**Issue by aried3r** [rails/rails#32352]
### Steps to reproduce

Have a model with a JSONB column with nested fields. In my case, it's `image_data` which is used by the [shrine](https://github.com/shrinerb/shrine) gem to store metadata.

Example:
```JSON
{
  "thumb": {
    "id": "randomid",
    "storage": "store",
    "metadata": {
      "size": 23813,
      "width": 368,
      "height": 276,
      "filename": "thumb_5b72287e-29b9-4d6a-a09e-f5864fca0f93.jpg",
      "mime_type": "image/jpeg"
    }
  },
  "original": {
    "id": "thumb_randomid",
    "storage": "store",
    "metadata": {
      "size": 2838519,
      "width": 3968,
      "height": 2976,
      "filename": "5b72287e-29b9-4d6a-a09e-f5864fca0f93.jpg",
      "mime_type": "image/jpeg"
    }
  }
}
```

Now I want to pluck `size` for example.
```Ruby
# Contrived example, since you wouldn't usually call `.all` to load all images into memory
images = Image.all
# SELECT "images".* FROM "images"
images.pluck("image_data -> 'original' -> 'metadata' -> 'size'")
# SELECT  image_data -> 'original' -> 'metadata' -> 'size' FROM "images"
images.pluck("image_data -> 'original' -> 'metadata' -> 'size'")
# SELECT  image_data -> 'original' -> 'metadata' -> 'size' FROM "images"
images.pluck("image_data -> 'original' -> 'metadata' -> 'size'")
# SELECT  image_data -> 'original' -> 'metadata' -> 'size' FROM "images"
```

In this case a `.map { |image| image[:original].size }` would be much faster, since it would use the records from memory.

### Expected behavior
Rails should use the loaded records to retrieve the attributes in the JSONB column.

### Actual behavior
`.pluck` makes a DB query every time. 

Maybe this is similar to https://github.com/rails/rails/pull/25976 and can be fixed similarly, maybe it can't be done or adds too much complexity for this special case but I thought I'd report it anyway.
 
### System configuration
**Rails version**:
5.1.5
**Ruby version**:
2.5.0

**Comment by danhuynhdev** [comment]
I think you need to call `load` to make it actually `loaded`. And IIRC pluck only retrieve attributes directly from loaded association if it is called with only attributes name. eg: `images.pluck(:image_data)`. And I think there is noway rails can parse the SQL above to get the values.

**Comment by pixeltrix** [comment]
Basically what @danhuynhdev said - for Rails to parse the SQL, recognise that it's a JSON path and return that via `dig` or some such means from loaded records isn't feasible in a way that would be performant.

**Comment by aried3r** [comment]
I thought so, thanks for the feedback!
