### ISSUE TITLE
Newline bug when on Windows

### ISSUE THREAD

**Issue by Bernica** [rails/rails#32362]
### Steps to reproduce
- Install Rails on Windows
- Make some requests
- Open default development.log file with Notepad

### Expected behavior
Logging should work the same on Windows as in OS X/Linux

### Actual behavior
Logging doesn't print newlines correctly on Windows

### System configuration
**Rails version**: 5.1.5

**Ruby version**: 2.4.3

Considering that newlines on Windows consist of \r\n (CRLN = carriage return + line feed), the following code would be incorrect:

- `message << "\n\n" if defined?(Rails.env) && Rails.env.development?` in ActionController::LogSubscriber
- `"#{String === msg ? msg : msg.inspect}\n"` in ActiveSupport::Logger::SimpleFormatter

as \n produces no newline, while \r\n does.

Maybe there's more code that relies on \n as newline that should also be changed, I didn't get that far.

Hope this helps!

**Comment by fxn** [comment]
Hey @Bernica. In Ruby and many other languages that follow C-semantics for newlines, `\n` in a double quoted string produces a portable newline. This [article](http://www.onlamp.com/pub/a/onlamp/2006/08/17/understanding-newlines.html) (disclaimer, I am the author) explains how this works in Perl, but the fundamentals apply to Ruby.

The length of the string "\n" is 1 in all systems, but the I/O layer in text mode translates those LFs into CRLFs on the fly on writing, and undo the conversion on reading. So, files have the native convention in all platforms if you print "foo\n", and you get also "foo\n" back (4 characters) if the file is read back from disk in any system.

If Rails is producing lines without the native convention on Windows (which is weird, not a good Windows citizen), it has to be something else. I wonder if we enable binmode or something.

@tenderlove I remember a conversation years ago in which @luislavena also was involved. Could this  be related with that patch?

**Comment by fxn** [comment]
Yes, this was introduced in https://github.com/rails/rails/commit/8f999a3f80284e08804c374cb5690c8bc158e4c1.

I'll leave the resolution of this issue to @tenderlove then.
