### ISSUE TITLE
Bug  on rails console when process is suspended

### ISSUE THREAD

**Issue by rderik** [rails/rails#32367]
### Steps to reproduce
Run `rails c` then suspend it by pressing [Ctrl+z]

### Expected behaviour
The user shoudl be able to suspend the rails console and then the user should be able to use the shell without any interference.

### Actual behaviour
The rails console doesn't seem to be suspended and it is "fighting" with the shell for the input and some input goes to the shell and some to the rails console so it breaks all the workflow. 

you can see a asciinema here: https://asciinema.org/a/pDMvNsyNHek77Ulyx6Z95VTuH

If I can be of any help let me know.

### System configuration
**Rails version**:
Rails 5.1.5
**Ruby version**:
ruby 2.4.1p111 (2017-03-22 revision 58053) [x86_64-darwin17]

**Comment by rafaelfranca** [comment]
This issue was moved to rails/spring#557
