### ISSUE TITLE
Optimistic Locking: ActiveRecord::StaleObjectError exception only raise once

### ISSUE THREAD

**Issue by phanviet** [rails/rails#32368]
### Steps to reproduce

I use the same command for testing Optimistic Locking as below screenshot:

![Image](https://www.evernote.com/shard/s510/sh/85515428-6e78-4194-9023-d7860e8f11df/40102f429df18de1/res/ee46994b-79c8-4e7c-beb2-e22636ae539d/skitch.png)

The first try is good with the exception was raised. I understand why the command at 2nd try don't raise exception but at 3rd try, I think the exception should be raised again.

### Expected behavior
Raise ActiveRecord::StaleObjectError exception when using same command at 3rd try, and 5th, ...

### Actual behavior
Only raise ActiveRecord::StaleObjectError exception at 1st try.

### System configuration
**Rails version**:
Rails 5.1.5

**Ruby version**:
Ruby 2.5.0

**Comment by danhuynhdev** [comment]
I think you your test is working against you here. Try to change the value assigned to the title every time and you gonna see a consistent result. 
```
# first try
a1 = Article.find(1)
a2 = Article.find(1)
a1.title = "a"
a1.save!
a2.title = "b"
a2.save! # fail as expected

# second try
a1 = Article.find(1) # title == "a"
a2 = Article.find(1) # title == "a"
a1.title = "a"
a1.save! # title doesn't change => no update => lock_version doesn't change
a2.title = "b"
a2.save! # title change => update db

# third try
a1 = Article.find(1) # title == "b"
a2 = Article.find(1) # title == "b"
a1.title = "a"
a1.save! # title change => update => lock_version change
a2.title = "b" 
# this time even though the title is set to a value different to the one in DB,
# it is the same value as the one in a2 => no update
a2.save! # no exception but nothing change

# fourth try
a1 = Article.find(1) # title == "a"
a2 = Article.find(1) # title == "a"
...
```

**Comment by phanviet** [comment]
Thank you @danhuynhdev I understood.
