### ISSUE TITLE
the dependency gem mail 2.7.0 occur warning and bug

### ISSUE THREAD

**Issue by YaEvan** [rails/rails#32371]
### Steps to reproduce

(Guidelines for creating a bug report are [available
here](http://guides.rubyonrails.org/contributing_to_ruby_on_rails.html#creating-a-bug-report))

### Expected behavior
run bin/rspec,  the mail v2.7.0 occur error
[mail issues](https://github.com/mikel/mail/pull/1162) 

### Actual behavior
`/Users/evanyang/.rvm/gems/ruby-2.3.1@everydayrails/gems/mail-2.7.0/lib/mail/parsers/content_type_parser.rb:938: warning: statement not reached
/Users/evanyang/.rvm/gems/ruby-2.3.1@everydayrails/gems/mail-2.7.0/lib/mail/parsers/content_type_parser.rb:963: warning: statement not reached
/Users/evanyang/.rvm/gems/ruby-2.3.1@everydayrails/gems/mail-2.7.0/lib/mail/parsers/content_type_parser.rb:1034: warning: mismatched indentations at 'end' with 'while' at 725
/Users/evanyang/.rvm/gems/ruby-2.3.1@everydayrails/gems/mail-2.7.0/lib/mail/parsers/content_type_parser.rb:1035: warning: mismatched indentations at 'end' with 'begin' at 716
/Users/evanyang/.rvm/gems/ruby-2.3.1@everydayrails/gems/mail-2.7.0/lib/mail/parsers/content_type_parser.rb:717: warning: assigned but unused variable - testEof`
Or
`/Users/evanyang/.rvm/gems/ruby-2.3.1@everydayrails/gems/mail-2.7.0/lib/mail/fields/content_type_field.rb:39: [BUG] Segmentation fault at 0x0070000e80b438
ruby 2.3.1p112 (2016-04-26 revision 54768) [x86_64-darwin16]...`

Finanlly, I changed mail version from 2.7.0 to 2.6.6 and fix it.
### System configuration
**Rails version**:
5.1.5 `s.add_dependency "mail", ["~> 2.5", ">= 2.5.4"]`
**Ruby version**:
2.3.1

**Comment by y-yagi** [comment]
It does not seem to be a Rails' issue. Please create an issue with [mail's](https://github.com/mikel/mail) repository.

**Comment by YaEvan** [comment]
thanks
