### ISSUE TITLE
Getting "undefined method each_pair" after edge Rails upgrade if repo has no tests

### ISSUE THREAD

**Issue by jasnow** [rails/rails#32393]
### Steps to reproduce
 1. Clone my repo: https://github.com/jasnow/tic-tac-toe
 2. Run "rake" and see that it is green.
 3. Verify "git diff" to see only difference is new version of edge rails.
 4. Run "bundle update" and see that it failed with this error:
```
NoMethodError: undefined method `each_pair' for "<%= ENV['DATABASE_URL'] %>":String
$HOME/.rvm/gems/ruby-2.6.0-preview1@ruby2.6-rails5.2/bundler/gems/
rails-5616c08401dd/activerecord/lib/active_record/database_configurations.rb:49:in `walk_configs'
```
5. Last clean Rails upgrade was 5 days ago: 614170e96253981c1974b7232cde024dff19010d

### Expected behavior
Tell us what should happen
```
Run options: --seed 20164
# Running:
Finished in 0.001804s, 0.0000 runs/s, 0.0000 assertions/s.
0 runs, 0 assertions, 0 failures, 0 errors, 0 skips
```
### Actual behavior
Tell us what happens instead
 4. Run "bundle update" and see that it failed with this error:
```
NoMethodError: undefined method `each_pair' for "<%= ENV['DATABASE_URL'] %>":String
$HOME/.rvm/gems/ruby-2.6.0-preview1@ruby2.6-rails5.2/bundler/gems/
rails-5616c08401dd/activerecord/lib/active_record/database_configurations.rb:49:in `walk_configs'
```
along with more stack trace lines.

### System configuration
**Rails version**:
6.0.0.alpha

**Ruby version**:
ruby 2.6.0preview1

**Comment by pixeltrix** [comment]
@eileencodes looks like this is related to your changes in 4e663c1e8d1e643783f157f904b5276e62f65589

**Comment by eileencodes** [comment]
Ok I will look at this later, thanks @pixeltrix
