### ISSUE TITLE
Make confirm dialog overridable in rails_ujs

### ISSUE THREAD

**Issue by mathieumahe** [rails/rails#32402]
I would like to override the default confirm dialog in `rails_ujs` to add different possibilities (a nice modal instead of the default box, add a prompt before destroying super-sensitive data like github does with repos, etc.)

One possibility would be to reference the method as `Rails.handleConfirm` instead of using a variable here : https://github.com/rails/rails/blob/896ee2b679462e7bcaa6890c6f5fdbd3b2e2fccb/actionview/app/assets/javascripts/rails-ujs/start.coffee#L45 
Like that, we could override it between the `import` and the call to `Rails.start()`

Even better, if we could extract the code of the confirm call https://github.com/rails/rails/blob/896ee2b679462e7bcaa6890c6f5fdbd3b2e2fccb/actionview/app/assets/javascripts/rails-ujs/features/confirm.coffee#L23 in a method accessible from outside the scope of the file, we could be able to redefine only the code we need. 

What do you think ?

Thanks !

**Comment by y-yagi** [comment]
This is being addressed with #29965. Please wait for it to be merged. Thanks.

**Comment by mathieumahe** [comment]
The pull request doesn't look very active.

Should I create a new one following Rafael's advices ?

**Comment by y-yagi** [comment]
Go ahead :+1:
