### ISSUE TITLE
default_scope concurrency issue.

### ISSUE THREAD

**Issue by meetme2meat** [rails/rails#32422]
We are planning to upgrade our stack to 5.0.0.stable. But in our integration env, we seeing some weird error at times.

> undefined method `default_scope_override' for #<Class:0x7f39ca86>
> 
> Did you mean?  default_scope_override=

It does not happen **frequently** but we are hoping to get it fixed so that we can roll out `AR` updates to our production boxes.

There is an identical issue reported earlier as well https://github.com/rails/rails/issues/27418. But it seems the issue was related to `schema` loading. I see the backport [pull request](https://github.com/rails/rails/pull/29216) in 5.0.0.stable branch as well.

I'm not entirely sure what is causing the issue, But if some can provide me with the context around the issue I can prepare a pull request.

Just an update: Our application is pure Ruby application i.e, not a Rails app.

We can not update AR to 5.2.stable branch. Since the JDBC driver for ActiveRecord 5.2.stable is still not ready, I believe. 

Max, we can upgrade to 5.1.stable and see if the issue is fixed there but that would involve some more testing on integration env side possibly pushing the update to some time further in future.

### Steps to reproduce
I have a sample script, through which I was able to reproduce the issue. The sqlite3 database is also attached with test data. Can be found [here](https://github.com/meetme2meat/default_scope_loading).

### Expected behavior
The script should run without any error. 

### Actual behavior
While I'll be the first to admit. The error is not reported all time(i.e it happen at random). I myself had to restart the script 4-5 to reproduce the issue. If it helps the backtrace of the error looks like this...

> ... Done
> undefined method `default_scope_override' for #<Class:0x7f39ca86>
> Did you mean?  default_scope_override=
> org/jruby/RubyBasicObject.java:1657:in `method_missing'
> /Users/werain/.rvm/gems/jruby-9.1.15.0/gems/activerecord-5.0.6/lib/active_record/dynamic_matchers.rb:21:in `method_missing'
> /Users/werain/.rvm/gems/jruby-9.1.15.0/gems/activerecord-5.0.6/lib/active_record/scoping/default.rb:107:in `build_default_scope'
> /Users/werain/.rvm/gems/jruby-9.1.15.0/gems/activerecord-5.0.6/lib/active_record/scoping/named.rb:43:in `default_scoped'
> /Users/werain/.rvm/gems/jruby-9.1.15.0/gems/activerecord-5.0.6/lib/active_record/scoping/named.rb:28:in `all'
> find_a_bug.rb:24:in `all_addresses'
> find_a_bug.rb:45:in `block in find_a_bug.rb'
> /Users/werain/.rvm/gems/jruby-9.1.15.0/gems/activerecord-5.0.6/lib/active_record/connection_adapters/abstract/connection_pool.rb:398:in `with_connection'
> find_a_bug.rb:43:in `block in find_a_bug.rb'
> undefined method `default_scope_override' for #<Class:0x30d5f2f1>
> Did you mean?  default_scope_override=
> org/jruby/RubyBasicObject.java:1657:in `method_missing'
> /Users/werain/.rvm/gems/jruby-9.1.15.0/gems/activerecord-5.0.6/lib/active_record/dynamic_matchers.rb:21:in `method_missing'
> /Users/werain/.rvm/gems/jruby-9.1.15.0/gems/activerecord-5.0.6/lib/active_record/scoping/default.rb:111:in `build_default_scope'
> /Users/werain/.rvm/gems/jruby-9.1.15.0/gems/activerecord-5.0.6/lib/active_record/scoping/named.rb:47:in `default_extensions'
> /Users/werain/.rvm/gems/jruby-9.1.15.0/gems/activerecord-5.0.6/lib/active_record/associations/association.rb:128:in `extensions'
> /Users/werain/.rvm/gems/jruby-9.1.15.0/gems/activerecord-5.0.6/lib/active_record/associations/collection_proxy.rb:35:in `initialize'
> /Users/werain/.rvm/gems/jruby-9.1.15.0/gems/activerecord-5.0.6/lib/active_record/relation/delegation.rb:101:in `create'
> /Users/werain/.rvm/gems/jruby-9.1.15.0/gems/activerecord-5.0.6/lib/active_record/associations/collection_association.rb:42:in `reader'
> /Users/werain/.rvm/gems/jruby-9.1.15.0/gems/activerecord-5.0.6/lib/active_record/associations/builder/association.rb:111:in `ip_addresses'
> find_a_bug.rb:30:in `only_addrs'
> find_a_bug.rb:25:in `block in all_addresses'
> org/jruby/RubyArray.java:1735:in `each'
> /Users/werain/.rvm/gems/jruby-9.1.15.0/gems/activerecord-5.0.6/lib/active_record/relation/delegation.rb:38:in `each'
> find_a_bug.rb:24:in `all_addresses'
> find_a_bug.rb:45:in `block in find_a_bug.rb'
> /Users/werain/.rvm/gems/jruby-9.1.15.0/gems/activerecord-5.0.6/lib/active_record/connection_adapters/abstract/connection_pool.rb:398:in `with_connection'
> find_a_bug.rb:43:in `block in find_a_bug.rb'
> ... Done
> ... Done

### System configuration
**Rails version**:
5.0.6

**Ruby version**:
jruby-9.1.15.0
OpenJDK 1.8

**Comment by meetme2meat** [comment]
The issue is also reproducible under `activerecord-5.1.6`

Attaching the following backtrace.

> undefined local variable or method `default_scope_override' for #<Class:0x5b9787be>
> Did you mean?  default_scope_override=
> org/jruby/RubyBasicObject.java:1657:in `method_missing'
> /Users/werain/.rvm/gems/jruby-9.1.15.0/gems/activerecord-5.1.6/lib/active_record/dynamic_matchers.rb:22:in `method_missing'
> /Users/werain/.rvm/gems/jruby-9.1.15.0/gems/activerecord-5.1.6/lib/active_record/scoping/default.rb:111:in `build_default_scope'
> /Users/werain/.rvm/gems/jruby-9.1.15.0/gems/activerecord-5.1.6/lib/active_record/scoping/named.rb:43:in `default_scoped'
> /Users/werain/.rvm/gems/jruby-9.1.15.0/gems/activerecord-5.1.6/lib/active_record/scoping/named.rb:28:in `all'
> find_a_bug.rb:24:in `all_addresses'
> find_a_bug.rb:45:in `block in find_a_bug.rb'
> /Users/werain/.rvm/gems/jruby-9.1.15.0/gems/activerecord-5.1.6/lib/active_record/connection_adapters/abstract/connection_pool.rb:408:in `with_connection'
> find_a_bug.rb:43:in `block in find_a_bug.rb'

**Comment by meetme2meat** [comment]
Ok, using ruby tracer(to understand what method are called when I query `ResporgAccountId.first`) I manage to figure what the problem is.
I'm attaching only the relevant... trace output.

> #0:/Users/werain/.rvm/gems/ruby-2.4.2/gems/activerecord-5.1.6/lib/active_record/inheritance.rb:127:ActiveRecord::Inheritance::ClassMethods:<:       end
> #0:/Users/werain/.rvm/gems/ruby-2.4.2/gems/activerecord-5.1.6/lib/active_record/scoping/default.rb:107:ActiveRecord::Scoping::Default::ClassMethods:-:             if default_scope_override.nil?
> #0:/Users/werain/.rvm/gems/ruby-2.4.2/gems/activesupport-5.1.6/lib/active_support/core_ext/class/attribute.rb:90:ActiveRecord::Base:>:           define_method(name) { val }
> #0:/Users/werain/.rvm/gems/ruby-2.4.2/gems/activesupport-5.1.6/lib/active_support/core_ext/class/attribute.rb:90:ActiveRecord::Base:-:           define_method(name) { val }
> #0:/Users/werain/.rvm/gems/ruby-2.4.2/gems/activerecord-5.1.6/lib/active_record/scoping/default.rb:107:ActiveRecord::Base:<:             if default_scope_override.nil?
> #0:/Users/werain/.rvm/gems/ruby-2.4.2/gems/activerecord-5.1.6/lib/active_record/scoping/default.rb:108:ActiveRecord::Scoping::Default::ClassMethods:-:               self.default_scope_override = !Base.is_a?(method(:default_scope).owner)
> #0:/Users/werain/.rvm/gems/ruby-2.4.2/gems/activesupport-5.1.6/lib/active_support/core_ext/class/attribute.rb:87:ActiveRecord::Base:>:       define_singleton_method("#{name}=") do |val|
> #0:/Users/werain/.rvm/gems/ruby-2.4.2/gems/activesupport-5.1.6/lib/active_support/core_ext/class/attribute.rb:88:ActiveRecord::Base:-:         singleton_class.class_eval do
> #0:/Users/werain/.rvm/gems/ruby-2.4.2/gems/activesupport-5.1.6/lib/active_support/core_ext/class/attribute.rb:89:ActiveRecord::Base:-:           remove_possible_method(name)
> #0:/Users/werain/.rvm/gems/ruby-2.4.2/gems/activesupport-5.1.6/lib/active_support/core_ext/module/remove_method.rb:3:Module:>:   def remove_possible_method(method)
> #0:/Users/werain/.rvm/gems/ruby-2.4.2/gems/activesupport-5.1.6/lib/active_support/core_ext/module/remove_method.rb:4:Module:-:     if method_defined?(method) || private_method_defined?(method)
> #0:/Users/werain/.rvm/gems/ruby-2.4.2/gems/activesupport-5.1.6/lib/active_support/core_ext/module/remove_method.rb:5:Module:-:       undef_method(method)
> #0:/Users/werain/.rvm/gems/ruby-2.4.2/gems/activesupport-5.1.6/lib/active_support/core_ext/module/remove_method.rb:7:Module:<:   end
> #0:/Users/werain/.rvm/gems/ruby-2.4.2/gems/activesupport-5.1.6/lib/active_support/core_ext/class/attribute.rb:90:ActiveRecord::Base:-:           define_method(name) { val }
> #0:/Users/werain/.rvm/gems/ruby-2.4.2/gems/activesupport-5.1.6/lib/active_support/core_ext/class/attribute.rb:93:ActiveRecord::Base:-:         if singleton_class?
> #0:/Users/werain/.rvm/gems/ruby-2.4.2/gems/activesupport-5.1.6/lib/active_support/core_ext/class/attribute.rb:105:ActiveRecord::Base:-:         val
> #0:/Users/werain/.rvm/gems/ruby-2.4.2/gems/activerecord-5.1.6/lib/active_record/scoping/default.rb:108:ActiveRecord::Base:<:               self.default_scope_override = !Base.is_a?(method(:default_scope).owner)
> #0:/Users/werain/.rvm/gems/ruby-2.4.2/gems/activerecord-5.1.6/lib/active_record/scoping/default.rb:111:ActiveRecord::Scoping::Default::ClassMethods:-:             if default_scope_override
> #0:/Users/werain/.rvm/gems/ruby-2.4.2/gems/activesupport-5.1.6/lib/active_support/core_ext/class/attribute.rb:90:ResporgAccountId:>:           define_method(name) { val }
> #0:/Users/werain/.rvm/gems/ruby-2.4.2/gems/activesupport-5.1.6/lib/active_support/core_ext/class/attribute.rb:90:ResporgAccountId:-:           define_method(name) { val }
> #0:/Users/werain/.rvm/gems/ruby-2.4.2/gems/activerecord-5.1.6/lib/active_record/scoping/default.rb:111:ResporgAccountId:<:             if default_scope_override
> #0:/Users/werain/.rvm/gems/ruby-2.4.2/gems/activerecord-5.1.6/lib/active_record/scoping/default.rb:118:ActiveRecord::Scoping::Default::ClassMethods:-:             elsif default_scopes.any?
> #0:/Users/werain/.rvm/gems/ruby-2.4.2/gems/activesupport-5.1.6/lib/active_support/core_ext/class/attribute.rb:90:ResporgAccountId:>:           define_method(name) { val }
> #0:/Users/werain/.rvm/gems/ruby-2.4.2/gems/activesupport-5.1.6/lib/active_support/core_ext/class/attribute.rb:90:ResporgAccountId:-:           define_method(name) { val }
> #0:/Users/werain/.rvm/gems/ruby-2.4.2/gems/activerecord-5.1.6/lib/active_record/scoping/default.rb:118:ResporgAccountId:<:             elsif default_scopes.any?
> #0:/Users/werain/.rvm/gems/ruby-2.4.2/gems/activerecord-5.1.6/lib/active_record/scoping/default.rb:119:ActiveRecord::Scoping::Default::ClassMethods:-:               base_rel ||= relation
> #0:/Users/werain/.rvm/gems/ruby-2.4.2/gems/activerecord-5.1.6/lib/active_record/scoping/default.rb:120:ActiveRecord::Scoping::Default::ClassMethods:-:               evaluate_default_scope do
> #0:/Users/werain/.rvm/gems/ruby-2.4.2/gems/activerecord-5.1.6/lib/active_record/scoping/default.rb:140:ActiveRecord::Scoping::Default::ClassMethods:>:           def evaluate_default_scope
> #0:/Users/werain/.rvm/gems/ruby-2.4.2/gems/activerecord-5.1.6/lib/active_record/scoping/default.rb:141:ActiveRecord::Scoping::Default::ClassMethods:-:             return if ignore_default_scope?

Looking at the Trace output it seems very evident why the issue happens.

Every time `ResporgAccountId.first` is called
the `default_scope_override` is method is redefined over [here](https://github.com/rails/rails/blob/5-1-stable/activerecord/lib/active_record/scoping/default.rb#L108).

Which potentially [remove](https://github.com/rails/rails/blob/5-1-stable/activesupport/lib/active_support/core_ext/class/attribute.rb#L89) the method that was defined earlier may be other thread running at the same time.

Given that our code runs in a Multithread env, Hence we are seeing the issue.

Just a side note: With my limited Testing under MRI I was unable to produce the above issue. Thus far.

**Comment by y-yagi** [comment]
#29216 has already backported to 5-1-stable 02926cfff6a403d28f83903b08ae7375fad8e836
Its backport has been released with 5.1.2.

**Comment by meetme2meat** [comment]
@y-yagi Sorry My bad https://github.com/rails/rails/pull/29233

**Comment by meetme2meat** [comment]
I wish we can backport this https://github.com/rails/rails/pull/32608 we are still stuck with this.
