### ISSUE TITLE
`ActiveSupport::JSON.decode` does not decode times

### ISSUE THREAD

**Issue by moubry** [rails/rails#32424]
I’m confused about whether I should be expecting `ActiveSupport::JSON.decode` to decode times. The tests for this feature make it seem like this is expected behavior, but I can’t get it to work.

### Steps to reproduce

```
#!/usr/bin/env ruby

require 'active_support/all'

tests = [
  '2007-01-01 01:12:34 Z',
  '2007-01-01 01:12:34',
  '2009-08-10T19:01:02',
  '2009-08-10T19:01:02Z',
  '2009-08-10T19:01:02+02:00',
  '2009-08-10T19:01:02-05:00',
  '1318996912'
]

tests.each do |test|
  decoded = ActiveSupport::JSON.decode("{\"now\":\"#{test}\"}")['now']
  valid = ActiveSupport::JSON::DATETIME_REGEX.match?(test)
  puts "#{decoded} (valid: #{valid}) => #{decoded.class}"
end
```

Output:

```
2007-01-01 01:12:34 Z (valid: true) => String
2007-01-01 01:12:34 (valid: true) => String
2009-08-10T19:01:02 (valid: true) => String
2009-08-10T19:01:02Z (valid: true) => String
2009-08-10T19:01:02+02:00 (valid: true) => String
2009-08-10T19:01:02-05:00 (valid: true) => String
1318996912 (valid: false) => String
```

### Expected behavior

I expect the decoded ISO 8601 strings to be DateTime objects.

### Actual behavior

They are String objects after decoding.

### System configuration
**Rails version**: `5.1.6`

**Ruby version**: `ruby 2.4.3p205 (2017-12-14 revision 61247) [x86_64-darwin17]`

**Comment by rafaelfranca** [comment]
You need to enable `ActiveSupport.parse_json_times`

**Comment by moubry** [comment]
Oh, boy — I feel dumb now. Thank you, @rafaelfranca. 🙌🏻

For anyone who finds this issue in the future, I had to do three things to get this working in a vanilla Ruby script:

```
#!/usr/bin/env ruby

require 'active_support/all'

Time.zone = 'Eastern Time (US & Canada)'
ActiveSupport::JSON::Encoding.use_standard_json_time_format = true
ActiveSupport.parse_json_times = true

puts ActiveSupport::JSON.decode('{"hi":"2009-08-10T19:01:02Z"}')
```

You can't set `ActiveSupport.parse_json_times` without first explicitly setting `ActiveSupport::JSON::Encoding.use_standard_json_time_format` for some reason. And since `ActiveSupport::JSON.decode` uses `Time.zone.parse`, and `Time.zone` is `nil` by default, you need to set that as well.
