### ISSUE TITLE
ActiveJob::TestHelper methods cause SystemStackError: stack level too deep errors

### ISSUE THREAD

**Issue by katiemccann** [rails/rails#32459]
When I try to use *any* methods from ActiveJob::TestHelper in an integration test, I get a SystemStackError: stack level too deep

### Steps to reproduce
simple_test.rb:
```
require 'test_helper'
include ActiveJob::TestHelper

class SimpleTest < ActionDispatch::IntegrationTest

  test 'simple' do
    perform_enqueued_jobs do
      #do something later
    end
  end
end
```

`$ rails test test/integration/simple_test.rb`

> Running via Spring preloader in process 98102
> Run options: --seed 60371
> 
> Running:
> 
> E
> 
> Error:
> SimpleTest#test_simple:
> SystemStackError: stack level too deep
>     test/integration/simple_test.rb:9:in `block in <class:SimpleTest>'
> 
> 
> bin/rails test test/integration/simple_test.rb:8
> 

### Expected behavior
Test should run  normally

### Actual behavior
Error:
SimpleTest#test_simple:
SystemStackError: stack level too deep
    test/integration/simple_test.rb:9:in `block in <class:SimpleTest>'

### System configuration
**Rails version**:
5.1.6 (also happened on 5.1.4)

**Ruby version**:
 2.5.1 (also happened on 2.3.1)

**Comment by rafaelfranca** [comment]
Can you please provide a sample application that reproduces the error?

**Comment by katiemccann** [comment]
Sure. Wasn't sure how to deliver a sample application so here's an attached .zip file. I just generated this new app using `rails new stack_error` and added a file test/integration/simple_test.rb .

`$ rails test`
[stack_error.zip](https://github.com/rails/rails/files/1877802/stack_error.zip)

> Running via Spring preloader in process 98664
> /Users/katiemccann/Documents/Code/stack_error/db/schema.rb doesn't exist yet. Run `rails db:migrate` to create it, then try again. If you do not intend to use a database, you should instead alter /Users/katiemccann/Documents/Code/stack_error/config/application.rb to limit the frameworks that will be loaded.
> Run options: --seed 21522
> 
> # Running:
> 
> E
> 
> Error:
> SimpleTest#test_simple:
> SystemStackError: stack level too deep
>     test/integration/simple_test.rb:7:in `block in <class:SimpleTest>'
> 
> 
> bin/rails test test/integration/simple_test.rb:6
>

**Comment by rafaelfranca** [comment]
The problem is that you are including `include ActiveJob::TestHelper` to `Kernel` in the line 2 and that includes all its method to all the objects overriding the original `perform_enqueued_jobs` in the queue adapter. You should be including that module in the test class like this:

```
require 'test_helper'


class SimpleTest < ActionDispatch::IntegrationTest
  include ActiveJob::TestHelper

  test 'simple' do
    perform_enqueued_jobs do
      #do something later
    end
  end
end
```

**Comment by rafaelfranca** [comment]
BTW, thank you for the issue. I hope my answer explains it. Let me know if you have any more doubt.

**Comment by katiemccann** [comment]
Thanks for your help! I think I get the explanation (new enough to Ruby/Rails that I didn't actually realize there was a difference in where you included a module).

**Comment by katiemccann** [comment]
Interesting, thanks so much for the detailed explanation 👍
