### ISSUE TITLE
Shopify/bootsnap gem breaks `webpacker:install`

### ISSUE THREAD

**Issue by dwarfmondo** [rails/rails#32452]
### Steps to reproduce

Execute a clean install of a new rails `5.2.0.rc2` app with ruby `2.5.0`. With the following command `rails new webpacker-bootsnap-test --webpack=stimulus`. 

### Expected behavior
Rails spins up a new app with no errors and a clean configuration of webpack with stimulus js.

### Actual behavior
Installation is aborted with an uninitialized constant error and a slew of warnings are logged referring to double loading gems from rbenv and homebrew.

Double-Loading Gems with rbenv and homebrew
https://github.com/Shopify/bootsnap/issues/112

Use realpaths in Cache @path_obj
https://github.com/Shopify/bootsnap/pull/136

Removing the bootsnap gem results in a clean install with expected behavior.

### System configuration
**Rails version**: 5.2.0.rc2

**Ruby version**: 2.5.0

**Comment by rafaelfranca** [comment]
Thanks! that is a bootsnap issue so let's keep tracking it there.

**Comment by dwarfmondo** [comment]
@rafaelfranca my thinking was that the gem should be excluded from the default install until the issue is fixed (PR merged). Since it breaks `webpacker:install`. It cost me a few hours of troubleshooting and frustration. Hopefully someone will find this issue if they run into the same issue.
