### ISSUE TITLE
[SystemTest] driven_by per test with different browser capabilities

### ISSUE THREAD

**Issue by Edouard-chin** [rails/rails#32468]
Drafting this issue in case anyone wants to work on it, otherwise when I find time I will tackle it

### Problem

If you have multiple tests that uses the same driver, but each test suite needs to test with different browser capabilities then SystemTest will keep overriding Capybara default driver.
Example:

```ruby
  class ApplicationSystemTestCase < ActionDispatch::SystemTestCase
    driven_by :selenium, using: :chrome, options: { args: ['--disable-translate'] }
  end

  class RegularChromeTest < ApplicationSystemTestCase
    test 'my test works on chrome' do
      ...
    end
  end

  class TestOnIphoneFour < ApplicationSystemTestCase
    driven_by :selenium, using: :chrome, options: { emulation: { device_name: 'iPhone 4'} }

    test 'my test works on iphone 4' do
      ...
    end
  end
```

<details>
  <summary> Disregard this explanation, this is not the correct one </summary>
The reason is because system test will keep overriding the Capybara driver with the same name `selenium`
https://github.com/rails/rails/blob/d514ce9199fac58e569482dc901e53d0526abdf7/actionpack/lib/action_dispatch/system_testing/driver.rb#L25
</details>

-------------------

I think one solution would be to decouple the driver name (what is currently passed to the `using` keyword) and make use of it only internally to Rails System test, then add an extra option to the `driven_by` method that will be used to register the driver on capybara.

Finally, inside the before_setup method, we would redefine the Capybara current's driver.
```ruby
def before_setup
  # ... old code
  Capybara.current_driver = self.class.driver.driver_name
end
```

**Comment by Edouard-chin** [comment]
The explanation I provided on why this is happening is incorrect, however I confirm that a call to `driven_by` using the same driver's name will leak to other test class.

My previous explanation is incorrect because when **each** test is run the driver is getting properly reset https://github.com/rails/rails/blob/d514ce9199fac58e569482dc901e53d0526abdf7/actionpack/lib/action_dispatch/system_test_case.rb#L104

The root of the problem comes from the fact that SystemTest reuses the same name to register a driver(1 of selenium/webkit/poltergeist) each time `driven_by` is called.


Capybara has the concept of a "session", which to summarize things up is a browser window.
When test runs the same session (or the same browser window) will be reused for each test that needs the same driver. In the example below, because both tests uses the same driver, a single session will be used (you'll only see one browser window getting open)
```ruby
class Test < SystemTest
  test 'test_1' do
  end

  test 'test_2' do
  end
end
```

How does capybara determine which session to get? https://github.com/teamcapybara/capybara/blob/c449772293cc657dc89ed05c7dd97deea00356dc/lib/capybara.rb#L298

The session is memoized inside a hash. And capybara retrieves which session to get from the pool based on the driver's name (as well as the app and session name, but those in our case are always the same).


So in this example
```ruby
class RegularBrowserTest < SystemTest
  driven_by :selenium, window_size: [1024, 768]

  test 'my_test' do
  end
end

class IphoneBrowserTest < SystemTest
  driven_by :selenium, options: { emulation: { device: 'iPhone 4' } }

  test 'my_test' do
  end
end
```
Capybara **should** open 2 sessions (you should see 2 browser window getting open). 1 window will be 1024, 768 size whereas the other will be the size of an iphone screen.

Because of this bug, we are only opening 1 window and every tests runs inside it.
Because the driver_name is in both cases 'selenium', the key used by cabybara to retrieve the session from the pool is the same.

I think the solution to this is the same as what I mentioned in the  issue

> I think one solution would be to decouple the driver name

**Comment by Edouard-chin** [comment]
I'll pickup the issue when I find time

**Comment by rmacklin** [comment]
@Edouard-chin Was there a resolution to this issue since your last comment, or are you working around the issue?

**Comment by rmacklin** [comment]
I see now that this may have been worked around by leveraging https://github.com/rails/rails/pull/35081 (originally opened in https://github.com/rails/rails/pull/32442).

The underlying issue of not being able to call `driven_by` with the same `driver` (e.g. `:selenium`) across different tests still exists, though, and is back under discussion in this issue: https://github.com/rails/rails/issues/42502

**Comment by ngan** [comment]
@cjlarose sorry for resurrecting such an old issue (I hope you're doing well!), but based on [your comment above](https://github.com/rails/rails/issues/32468#issuecomment-946056251), it doesn't align with https://github.com/rails/rails/pull/42511. Specifically, the fix in the PR requires that the `name` is passed through as part of the `options` argument, eg:

```ruby
driven_by :selenium,
          using: :chrome,
          options: {
            args: ['--disable-translate'],
            name: 'chrome_with_translate_disabled'
          }          
```

But based on your comment above, the `name` is suppose to be passed as a top-level argument:
```ruby
driven_by :selenium,
          using: :chrome,
          options: {
            args: ['--disable-translate']
          },
          name: 'chrome_with_translate_disabled'

```

The latter makes more sense to me IMHO. I'm trying to piece together which one you had intended to do?
