### ISSUE TITLE
Implement ApplicationRecord.pluck

### ISSUE THREAD

**Issue by sunnyrjuneja** [rails/rails#32463]
Hi,

I have code that looks like this:

```ruby
class Example < ApplicationRecord
  has_many :team
  has_one :individual

  def notifiers
    if on_team?
      team
    elsif solo?
      individual
    end
  end
end
```

I want to call `Example.new.notifiers.pluck(:email)` but ApplicationRecord  does not define #pluck. I want ApplicationRecord to define pluck that returns ["email@gmail.com"].

I'm aware that I can do `[individual]` but I think this would be a tiny QOL improvement because I sometimes forget.

A possible implementation might be

```ruby
def pluck(**columns)
  colums.map! { |c| c.to_s }
  [attributes.slice(columns).values]
end
```

**Comment by y-yagi** [comment]
Please use the [Rails Core mailing list](https://groups.google.com/forum/#!forum/rubyonrails-core) for feature requests, where a wider community will be able to help you. We reserve the Rails issue tracker only for bugs in Rails. Thanks.

**Comment by kaspth** [comment]
Hmm, I'm not sure. `@post.pluck(:id, :title)` seems weird to me. Especially considering that the new `pick` method is meant to conceptually link with it.

It did remind of some extensions I'd been thinking about, though. So I ended up creating this playground:

```ruby
module Enumerable
  # Mirrors index_by, but assigns the value instead of the key.
  def index_with(value = nil)
    if block_given?
      each_with_object(Hash.new) { |object, hash| hash[object] = yield(object) }
    else
      each_with_object(Hash.new) { |object, hash| hash[object] = value }
    end
  end
end

Post = Struct.new(:title, :description) do
  def slice(*keys)
    keys.index_with { |key| public_send(key) }
  end

  def pluck(*keys)
    keys.collect { |key| public_send(key) }
  end
end

post = Post.new('hey', 'ahoy hoy')

puts post.slice(:title, :description)
puts post.pluck(:title, :description)
puts
puts %i( title description ).index_with(nil)
```

**Comment by kaspth** [comment]
@sunnyrjuneja finally got back to this: http://edgeapi.rubyonrails.org/classes/ActiveRecord/Calculations.html#method-i-pick

**Comment by sunnyrjuneja** [comment]
thank you @kaspth !
