### ISSUE TITLE
Persisting an empty string in an integer field with a default value converts to nil

### ISSUE THREAD

**Issue by gduquesnay** [rails/rails#32467]
### Steps to reproduce
Add a field such as
t.integer "time_limit", default: 0

update(time_limit: '')

This is what happens by default if you use are using an input_field to set this integer and the user clears the field and submits the form

### Expected behavior
Seem like to would be less surprising to set it to the default value

### Actual behavior
It get's set to nil

### System configuration
**Rails version**: 5.1.1

**Ruby version**: 2.5.0

**Comment by pixeltrix** [comment]
@gduquesnay what happens if you set the column to `null: false` ? I believe that will now insert the default.

**Comment by gduquesnay** [comment]
@pixeltrix Thanks.  We actually had tried that it just throws:
```
ActiveRecord::NotNullViolation (PG::NotNullViolation: ERROR:  null value in column "time_limit" violates not-null constraint
```

**Comment by pixeltrix** [comment]
> Thanks. We actually had tried that it just throws

I was probably thinking of an old version of Rails 👴 

I would recommend that you either use a validation to ensure that a user enters a number into the form along with a number field input that ensures that a value is entered: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/number

Another option is just to overwrite the writer method to ensure that a zero is set if null:

``` ruby
def time_limit=(value)
  super
  super(0) if time_limit.blank?
end
```

or even a callback:

``` ruby
before_validation { self.time_limit = 0 if time_limit.blank? }
```

I'm pretty sure that this is working as intended and changing this would likely break people's apps. Also it would make it hard to actually set a nil value when a column has a default.
