### ISSUE TITLE
Scopes and Single Table Inheritance

### ISSUE THREAD

**Issue by aliCamargo** [rails/rails#32460]
### Steps to reproduce
The scopes not working correctly in the STI class, when the scope is execute from child class returns all instances of the parent class.

```Ruby
class Person < ActiveRecord::Base
  scope :order_by_name, ->(order = 'asc') { order(name: order.to_sym)}
end

class LegalPerson < Person
  scope :industrial, -> { where(classification: 'industrial') }
  scope :textile, -> { where(classification: 'textile') }
end

class NaturalPerson < Person
  scope :employee, -> { where(classification: 'employee') }
  scope :independent, -> { where(classification: 'independent') }
end
```

### Expected behavior
The expected behavior is apply the order scope and keep the conditional `WHERE` because the `scope` is executing on `Legal` model.

```Ruby
Legal.order_by_name.to_sql
#=> SELECT persons.* FROM persons WHERE persons.type IN ('LegalPerson') ORDER BY persons.name ASC
```

### Actual behavior
The Actual behavior is applying the order scope but remove the conditional `WHERE` although the `scope` is executing on `LegalPerson` model.

Apparently, the `scope` is applied in the parent class and return `Person` instances including `NaturalPerson`.

```Ruby
LegalPerson.order_by_name.to_sql
#=> SELECT persons.* FROM persons ORDER BY persons.name ASC
```

### System configuration
**Rails version**: Rails 5.1.5

**Ruby version**: ruby-2.5.0

**Comment by keoghpe** [comment]
I created the following script to reproduce the above issue but it appears to be working as expected:

```
# frozen_string_literal: true

begin
  require "bundler/inline"
rescue LoadError => e
  $stderr.puts "Bundler version 1.10 or later is required. Please update your Bundler"
  raise e
end

gemfile(true) do
  source "https://rubygems.org"

  git_source(:github) {|repo| "https://github.com/#{repo}.git"}

  gem 'rails', '5.1.5'
  gem "sqlite3"
end

require "active_record"
require "minitest/autorun"
require "logger"

# This connection will do for database-independent bug reports.
ActiveRecord::Base.establish_connection(adapter: "sqlite3", database: ":memory:")
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  # create_table :persons, force: true do |t|
  create_table :people, force: true do |t|
    t.string :name
    t.string :type
  end
end

class Person < ActiveRecord::Base
  scope :order_by_name, ->(order = 'asc') {order(name: order.to_sym)}
end

class LegalPerson < Person
end


class BugTest < Minitest::Test
  def test_scope
    assert_equal "SELECT \"people\".* FROM \"people\" WHERE \"people\".\"type\" IN ('LegalPerson') ORDER BY \"people\".\"name\" ASC", LegalPerson.order_by_name.to_sql
  end
end

```

I've also tried creating the table `persons` instead of `people` since @aliCamargo mentioned the expected query should be `#=> SELECT persons.* FROM persons WHERE persons.type IN ('LegalPerson') ORDER BY persons.name ASC`. However, when I do this I get the following error when I try to run the script `ActiveRecord::StatementInvalid: Could not find table 'people'` which I believe is the expected behaviour.

I ran the script with **Ruby 2.5** and the assertion passes. @aliCamargo could you try editing the above script to see if you can reproduce your issue?

**Comment by aliCamargo** [comment]
@keoghpe thank you for take some time for review it. I closed this issue, because i found that the reason was in rspec test.

I had: `expect(Person).to receive(:order_by_name).and_call_original`, then this forced that the method was called in the parent class.

Thank you very much!!!  :sweat_smile:
