### ISSUE TITLE
ActionView::Helpers::DateHelper#time_ago_in_words is off by an hour

### ISSUE THREAD

**Issue by ilyakatz** [rails/rails#32470]
### Steps to reproduce

```
irb(main):023:0> Time.now
=> 2018-04-05 22:28:50 +0000
irb(main):024:0> Time.now.in_time_zone
=> Thu, 05 Apr 2018 15:28:55 PDT -07:00
irb(main):025:0> time_ago_in_words(Time.now - 15.hours)
=> "16 hours"
```

### Expected behavior
When using `distance_of_time_in_words_to_now` helper, it should take into account current Timezone, however, it does not

### Actual behavior

Time is off by one hour

### System configuration
**Rails version**:

4.2 but looks like it's the same on master

https://github.com/rails/rails/blob/master/actionview/lib/action_view/helpers/date_helper.rb#L177

This can be resolved by using `Time.now.in_time_zone` in the argument 

**Ruby version**:

2.3

**Comment by pixeltrix** [comment]
@y-yagi the `Time.now` in that method dates from the initial commit (db045dbbf60b53dbe013ef25554fd013baf88134) which predates `Time.current` - it even predates Active Support entirely! Given that, I agree that it should take into account the current timezone.

**Comment by pixeltrix** [comment]
@ilyakatz looking at your example it doesn't make sense - we never return an exact amount of hours from `distance_of_time_in_words`, e.g:

```
Loading development environment (Rails 4.2.10)
>> ENV["TZ"] = "UTC"
=> "UTC"
>> Time.zone = "Pacific Time (US & Canada)"
=> "Pacific Time (US & Canada)"
>> now = "2018-04-05 22:28:50 +0000".to_time
=> "2018-04-05T22:28:50.000+00:00"
>> now.in_time_zone
=> Thu, 05 Apr 2018 15:28:50 PDT -07:00
>> helper.distance_of_time_in_words(now, now - 15.hours)
=> "about 15 hours"
```

I think there's probably an edge case here with Time.now vs. Time.current but your example isn't it - is it possible you went through a daylight saving transition?

**Comment by pixeltrix** [comment]
After looking at this I can't see where it's going to be a problem since `Time.now.to_i` is equivalent to `Time.current.to_i` so when the subtraction in `distance_of_time_in_words` takes place there will be no difference between the two, e.g:

```
>> ENV["TZ"] = "Pacific/Honolulu"
=> "Pacific/Honolulu"
>> Time.zone = "America/Denver"
=> "America/Denver"
>> Time.now
=> "2018-04-07T04:45:31.081-10:00"
>> Time.current
=> Sat, 07 Apr 2018 08:45:35 MDT -06:00
>> Time.now.to_i == Time.current.to_i
=> true
>> Time.now - Time.current
=> -6.0e-06 # this difference is the overhead of fetching the current time
```

Given that `Time.now` is faster than `Time.current` I don't see the point of changing it.
