### ISSUE TITLE
ActiveSupport::NumberHelper:: NumberToHumanConverter uses 'mili' not 'milli' for 10^(-3)

### ISSUE THREAD

**Issue by jufemaiz** [rails/rails#32475]
### Steps to reproduce

I looked through the history for the ActiveSupport::NumberHelper::#number_to_human method for the reasoning behind the use of "mili" as the prefix for 1/1000 of a unit but could not find anything and could not see any notes related for people wanting to know the background of the decision if they implement language packs using the SI prefix of "milli".

See https://github.com/rails/rails/blob/master/activesupport/lib/active_support/number_helper/number_to_human_converter.rb

ISO and NIST prefix standard for 1/1000 is "milli" (Ref: https://www.nist.gov/pml/weights-and-measures/prefixes https://en.wikipedia.org/wiki/Metric_prefix )

### Expected behavior
Use of `milli` in lieu of `mili`

**Comment by pixeltrix** [comment]
Looks like it's been this way since the original patch in the [Lighthouse ticket][1]. Unsure how much breakage we will cause if we change this - is it possible to support both?

[1]: https://rails.lighthouseapp.com/projects/8994/tickets/4239

**Comment by jufemaiz** [comment]
@pixeltrix ah ok. Interesting. Is it an American-english approach to use "mili"?

I'll work on something. It definitely needs to be able to support both to prevent potential regression issues.

**Comment by villu164** [comment]
A hackish solution would be to do this 😄 
```ruby
INVERTED_DECIMAL_UNITS = {:unit=>0, :ten=>1, :hundred=>2, :thousand=>3, :million=>6, :billion=>9, :trillion=>12, :quadrillion=>15, :deci=>-1, :centi=>-2, :milli=>-3, :mili=>-3, :micro=>-6, :nano=>-9, :pico=>-12, :femto=>-15} 
DECIMAL_UNITS = INVERTED_DECIMAL_UNITS.invert
```
