### ISSUE TITLE
ActionDispatch default headers ignored in API only mode

### ISSUE THREAD

**Issue by kddeisz** [rails/rails#32483]
This may have originally been a design decision, but it seems like an odd choice. When an application is running in API only mode, default headers are not merged into the request. Adding the following code (copied straight from the non-API side) to the `ApplicationController` fixes it:

```ruby
def self.make_response!(request)
  ActionDispatch::Response.create.tap do |res|
    res.request = request
  end
end
```

I'd like to open a PR to either:

* push this code up so that both `ActionController::Base` and `ActionController::API` have access to it
* push this code into a module that users can optionally include in their `ApplicationController`

I'd prefer the former, as I don't know why you wouldn't want security headers on your API. Let me know which approach would be preferred, if either.

**Comment by rafaelfranca** [comment]
We can't do the former because we don't want default headers in `Metal` controller. But I'm fine with the latter.

**Comment by kddeisz** [comment]
Sounds good, I'll get started on a PR.

**Comment by guilleiguaran** [comment]
> I'd prefer the former, as I don't know why you wouldn't want security headers on your API. Let me know which approach would be preferred, if either.

Well, many of the security headers are understood by the browsers, so we don't want to have them by default in APIs
