### ISSUE TITLE
klass.ignored_columns.any? crashes on nil.any?

### ISSUE THREAD

**Issue by eiked** [rails/rails#32495]
In rails 5.1.6: active_record/relation/query_methods.rb: build_select(arel):

(sidenote: on the current github, query_methods.rb has been refactored, but the problem might still apply, see below) 

I newly got this error message on some code that did work before for years
(possibly with updating to 5.1.6)

ruby2.5/gems/2.5.0/gems/activerecord-5.1.6/lib/active_record/relation/query_methods.rb:1044:in `build_select': undefined method `any?' for nil:NilClass (NoMethodError)

in the line:
elsif klass.ignored_columns.any?

Under some circumstances "klass.ignored_columns" can be nil.
(this might possibly be caused by the "ignorable" gem)

I'd like to suggest to make this immune against nil,
aka to change that to:
elsif klass.ignored_columns&.any?

One might argue that ignored_columns should never become nil in the first place,
so this might actually be the correct behaviour to fail fast here.

I'd argue that rails should be robust and defensive.
So instead of crashing,  we'd better emit a warning here and go on.

---

This is pretty much along the lines of empty? and blank?

I'd like to suggest that the non-existant quantors on Arrays, Enumerables and Collections
should be forgiving on nil (where appropriate - possibly emiting a warning)

In the context of the ruby language,
there is a well defined difference between the empty collection or nil.

But in the context of rails,
where collections are all around,
there is not much difference between an empty collection or not having a collection at all.

---

Something like any?? or any?! (just joking)

 

### Steps to reproduce

(Guidelines for creating a bug report are [available
here](http://guides.rubyonrails.org/contributing_to_ruby_on_rails.html#creating-a-bug-report))

### Expected behavior
Tell us what should happen

### Actual behavior
Tell us what happens instead

### System configuration
**Rails version**:

**Ruby version**:

**Comment by pixeltrix** [comment]
Since the ignorable gem isn't required for Rails 5.0 and later then I would suggest just removing that gem and use the standard accessor, e.g.

``` ruby
class Product < ApplicationRecord
  self.ignored_columns = [:legacy_sku, :legacy_name]
end
```

We generally don't code around bugs introduced by gems unless absolutely necessary because it would be a maintenance nightmare. Also coding defensively all the time as you suggest makes Rails slower and use more memory so we prefer to catch errors wherever possible during loading as opposed to runtime where it can have the most impact on performance.

Thanks for your interest in trying to make Rails better 👍

**Comment by eiked** [comment]
Hi pixeltrix,
I've added https://github.com/nthj/ignorable/issues/10

Sorry for being so ignorant about this beening included in rails 5,
but then, it still work before 5.1.6, so this was a bit unexpected.

So I believe this issue should now be closed.

However the larger issue of defensive coding
might still be of interest.

I fully agree with fail fast because this makes problems a lot more easy to spot.
But on the other hand, rails is pragmatic so why fail if the semantics stays intact?

---

Looking that up,
rails 5 requires Ruby 2.2.2+
but the save navigation operator was only introduced later in ruby 2.3

I'm looking forward to more nil ignorance in rails 6,
because nil should not make us fail.

---

around the web:
https://en.wikipedia.org/wiki/Russell%27s_paradox
