### ISSUE TITLE
Wrong timezone offset in attributes with time type

### ISSUE THREAD

**Issue by AliSepehri** [rails/rails#32518]
In Tehran most of the time we have +3:30 offset from UTC but after daylight saving time effect, our offset has been +4:30. For example the result of `Time.zone.now` is:
```
Tue, 10 Apr 2018 16:00:00 +0430 +04:30
```

Assume I have following model:
```
  create_table "events", force: :cascade do |t|
    t.time "time_attr"
    t.datetime "datetime_attr"
  end
```

When I initialize `Event` model, `time_attr` with `time` type has wrong offset:
```
Event.new time_attr: Time.zone.now, datetime_attr: Time.zone.now

#<Event:0x00000
time_attr: Sat, 01 Jan 2000 16:00:00 +0330 +03:30,
datetime_attr: Tue, 10 Apr 2018 16:00:00 +0430 +04:30
>
```

**Comment by emad-elsaid** [comment]
I believe this problem is not rails problem but the system tzinfo, did Iran change the DTS settings lately or is your tzinfo package old maybe?

**Comment by AliSepehri** [comment]
@emad-elsaid But why with `datetime` type everything is works right?

**Comment by emad-elsaid** [comment]
@AliSepehri Oh, I didn't see that in the story, in that case it's not the machine problem then.

**Comment by pixeltrix** [comment]
@AliSepehri this is expected behaviour - in SQL the TIME type doesn't have a date so we can't determine whether it should have a DST adjustment or not. Since Ruby doesn't have a equivalent of a time without a date we assume the date to be 1st January, 2000 when DST isn't in effect.

**Comment by AliSepehri** [comment]
@pixeltrix I realize the second part of your answer about lack time equivalent in ruby. About the first part of your answer, I just need to read time in my configured timezone (application.rb) according to DST adjustment of today. I didn't get your answer.

**Comment by pixeltrix** [comment]
@AliSepehri if you want to maintain the same time but change it to the current date then just use the `change` method, e.g:

```
>> Time.zone = "Asia/Tehran"
=> "Asia/Tehran"
>> t = Time.zone.parse('Sat, 01 Jan 2000 16:00:00 +0330 +03:30')
=> Sat, 01 Jan 2000 16:00:00 +0330 +03:30
>> d = Date.current
=> Tue, 10 Apr 2018
>> t.change(year: d.year, month: d.month, day: d.day)
=> Tue, 10 Apr 2018 16:00:00 +0430 +04:30
```

The reason we use a consistent date for SQL TIME columns is that if we just converted to whatever the current date was you could end up with different results depending which day of the year you ran the code.

**Comment by AliSepehri** [comment]
@pixeltrix I got it. Really thanks
