### ISSUE TITLE
Middleware config problems are difficult to trace.

### ISSUE THREAD

**Issue by j3pic** [rails/rails#32516]
### Steps to reproduce

Try to perform a Rails 4 -> 5.1 upgrade on an app that depends on gems
that do the following:

```
  config.middleware.use "Foo::Bar::Baz"
```

### Expected behavior

It would be nice if the resulting error showed the source location where `config.middleware.use` was called. This would require collecting and storing that information when `config.middleware.use` is called. Or perhaps the `use` method could simply check the validity of its arguments before storing them in internal data structures. (I can't make a PR to do that because I can't deduce the full criteria for argument validity from the documentation's [limited examples](http://api.rubyonrails.org/classes/Rails/Configuration/MiddlewareStackProxy.html).)

### Actual behavior

An error occurs when ActionDispatch tries to call `"Foo::Bar::Baz".new`. The stack trace is useless, so extensive reading of Rails internals and use of pry-byebug is required to figure out which gem added the offending middleware:

```
NoMethodError: undefined method `new' for "Foo::Bar::Baz":String
Did you mean?  next
  /Users/j3pic/.rbenv/versions/2.3.7/lib/ruby/gems/2.3.0/gems/actionpack-5.1.6/lib/action_dispatch/middleware/stack.rb:35:in `build'
  /Users/j3pic/.rbenv/versions/2.3.7/lib/ruby/gems/2.3.0/gems/actionpack-5.1.6/lib/action_dispatch/middleware/stack.rb:100:in `block in build'
  /Users/j3pic/.rbenv/versions/2.3.7/lib/ruby/gems/2.3.0/gems/actionpack-5.1.6/lib/action_dispatch/middleware/stack.rb:100:in `each'
  /Users/j3pic/.rbenv/versions/2.3.7/lib/ruby/gems/2.3.0/gems/actionpack-5.1.6/lib/action_dispatch/middleware/stack.rb:100:in `inject'
  /Users/j3pic/.rbenv/versions/2.3.7/lib/ruby/gems/2.3.0/gems/actionpack-5.1.6/lib/action_dispatch/middleware/stack.rb:100:in `build'
  /Users/j3pic/.rbenv/versions/2.3.7/lib/ruby/gems/2.3.0/gems/railties-5.1.6/lib/rails/engine.rb:508:in `block in app'
  /Users/j3pic/.rbenv/versions/2.3.7/lib/ruby/gems/2.3.0/gems/railties-5.1.6/lib/rails/engine.rb:504:in `synchronize'
  /Users/j3pic/.rbenv/versions/2.3.7/lib/ruby/gems/2.3.0/gems/railties-5.1.6/lib/rails/engine.rb:504:in `app'
  /Users/j3pic/.rbenv/versions/2.3.7/lib/ruby/gems/2.3.0/gems/railties-5.1.6/lib/rails/application/finisher.rb:45:in `block in <module:Finisher>'
  /Users/j3pic/.rbenv/versions/2.3.7/lib/ruby/gems/2.3.0/gems/railties-5.1.6/lib/rails/initializable.rb:30:in `instance_exec'
  /Users/j3pic/.rbenv/versions/2.3.7/lib/ruby/gems/2.3.0/gems/railties-5.1.6/lib/rails/initializable.rb:30:in `run'
  /Users/j3pic/.rbenv/versions/2.3.7/lib/ruby/gems/2.3.0/gems/railties-5.1.6/lib/rails/initializable.rb:59:in `block in run_initializers'
  /Users/j3pic/.rbenv/versions/2.3.7/lib/ruby/2.3.0/tsort.rb:228:in `block in tsort_each'
  /Users/j3pic/.rbenv/versions/2.3.7/lib/ruby/2.3.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
  /Users/j3pic/.rbenv/versions/2.3.7/lib/ruby/2.3.0/tsort.rb:431:in `each_strongly_connected_component_from'
  /Users/j3pic/.rbenv/versions/2.3.7/lib/ruby/2.3.0/tsort.rb:349:in `block in each_strongly_connected_component'
  /Users/j3pic/.rbenv/versions/2.3.7/lib/ruby/2.3.0/tsort.rb:347:in `each'
  /Users/j3pic/.rbenv/versions/2.3.7/lib/ruby/2.3.0/tsort.rb:347:in `call'
  /Users/j3pic/.rbenv/versions/2.3.7/lib/ruby/2.3.0/tsort.rb:347:in `each_strongly_connected_component'
  /Users/j3pic/.rbenv/versions/2.3.7/lib/ruby/2.3.0/tsort.rb:226:in `tsort_each'
  /Users/j3pic/.rbenv/versions/2.3.7/lib/ruby/2.3.0/tsort.rb:205:in `tsort_each'
  /Users/j3pic/.rbenv/versions/2.3.7/lib/ruby/gems/2.3.0/gems/railties-5.1.6/lib/rails/initializable.rb:58:in `run_initializers'
  /Users/j3pic/.rbenv/versions/2.3.7/lib/ruby/gems/2.3.0/gems/railties-5.1.6/lib/rails/application.rb:353:in `initialize!'
  /Users/j3pic/.rbenv/versions/2.3.7/lib/ruby/gems/2.3.0/gems/railties-5.1.6/lib/rails/railtie.rb:185:in `public_send'
  /Users/j3pic/.rbenv/versions/2.3.7/lib/ruby/gems/2.3.0/gems/railties-5.1.6/lib/rails/railtie.rb:185:in `method_missing'
  /Users/j3pic/myapp/config/environment.rb:5:in `<top (required)>'
```

### System configuration
**Rails version**:

5.1.5

**Ruby version**:

2.3.7

**Comment by y-yagi** [comment]
Passing strings or symbols to the middleware builder is deprecated in Rails 5.0, and it removed in 5.1. 
So, if you pass strings or symbols to middleware builder in Rails 5.0, the following deprecate message is showed. 

```
DEPRECATION WARNING: Passing strings or symbols to the middleware builder is deprecated, please change
them to actual class references.  For example:

  "Foo::Bar::Baz" => Foo::Bar::Baz 
```

Therefore, I do not think this problem will occur if you do not skip 5.0 and upgrade one by one. 
Since the same thing happens with other functions, we recommend that do not skip the minor version during the upgrade. Please upgrade it one by one. 
Ref: http://guides.rubyonrails.org/upgrading_ruby_on_rails.html#the-upgrade-process

**Comment by j3pic** [comment]
I skipped 5.0 and upgraded directly to 5.1. I saw no deprecation warnings
as a result.

**Comment by j3pic** [comment]
This same problem occurs when upgrading from Rails 4.2 to 5.0. The deprecation warning detects the problem long after the file that caused it was loaded. The stack trace, when I convert the deprecation warning to an exception, is identical to the one I shared here, and the same debugging techniques will be required in order to find out which gem is doing this.
