### ISSUE TITLE
ActiveRecord - has_many through nested with source and polymorphic

### ISSUE THREAD

**Issue by oniram88** [rails/rails#32521]
### Steps to reproduce

```
git clone https://github.com/oniram88/test_nested_through_custom_scope_has_many.git
cd test_nested_through_custom_scope_has_many
docker-compose up 
```
open new terminal

```
ruby nested_through.rb 'pg'
ruby nested_through.rb 'sqlite3'
```

### Expected behavior
I expect that the custom scope of the relation that I inserted in the 
has_many :searchable_essence_texts...
will not replicated in all the conditions of inner joins

### Actual behavior
The query is generated in the same way for sqlite3 and pg but sqlite3, but aren't correct, sqlite3 didn't stop (I don't know) but pg is more accurate and check's (I think correctly) the presence of FROM-clause

the query is for sqlite3:
```
SELECT COUNT(*) FROM "pages"
INNER JOIN "elements" ON "elements"."page_id" = "pages"."id" AND "elements"."position" IS NOT NULL 
INNER JOIN "contents" ON "contents"."element_id" = "elements"."id" 
AND "essence_texts"."searchable" = ? 
AND "elements"."public" = ? 
AND "contents"."essence_type" = ? 

INNER JOIN "essence_texts" ON "essence_texts"."id" = "contents"."essence_id" 
AND "essence_texts"."searchable" = ? 
AND "elements"."public" = ?
```
and the query is for pg:

```
SELECT COUNT(*) FROM "pages" 
INNER JOIN "elements" ON "elements"."page_id" = "pages"."id" AND "elements"."position" IS NOT NULL
 INNER JOIN "contents" ON "contents"."element_id" = "elements"."id" 
AND "essence_texts"."searchable" = $1 
AND "elements"."public" = $2
 AND "contents"."essence_type" = $3 

INNER JOIN "essence_texts" ON "essence_texts"."id" = "contents"."essence_id" 
AND "essence_texts"."searchable" = $4 
AND "elements"."public" = $5
```

this two conditions:
AND "essence_texts"."searchable" = ? 
AND "elements"."public" = ? 

should only appare in the last inner join

### System configuration
**Rails version**: 5.2.0 but checked also in 5.1.x

**Ruby version**: 2.3.3

**Comment by ahorner** [comment]
I've been running into an regression that I believe to be related to this one. I have it down to a fairly isolated case, but don't have the time to stand up a repo for it:

```ruby
class Person < ApplicationRecord
  has_many(
    :timeshares,
    -> { where(expired_at: nil) },
    as: :owner,
    inverse_of: :owner,
  )
  has_many :properties, through: :timeshares
end

class Timeshare < ApplicationRecord
  belongs_to :owner, polymorphic: true, inverse_of: :timeshares
  belongs_to :property, inverse_of: :timeshares
end

class Property < ApplicationRecord
  has_many :timeshares, inverse_of: :property
end

person.properties.to_sql
# Expected (behavior as of 5.1.6):
#
#   SELECT * FROM properties 
#     INNER JOIN timeshares ON properties.id = timeshares.property_id 
#     WHERE timeshares.owner_id = 1 AND timeshares.owner_type = 'Person'
#     AND timeshares.expired_at IS NULL
# 
# Actual (behavior as of 5.2.0):
# 
#   SELECT * FROM properties 
#     INNER JOIN timeshares ON properties.id = timeshares.property_id
#     WHERE timeshares.owner_id = 1 AND timeshares.owner_type = 'Person'
```

The generic form of this problem seems to be that `has_many :through` associations which pass through a polymorphic relationship end up discarding the custom scope information from that polymorphic relationship, leaving them less-scoped than desired.

I'm working around it for now with a redundant custom `merge` that restores the missing clause for the polymorphic association.
