### ISSUE TITLE
Postgres money datatype fails numericality: true ActiveRecord 5.2.0 validation 

### ISSUE THREAD

**Issue by axlekb** [rails/rails#32531]
### Steps to reproduce
Just tried updating to `5.2.0` and found that `postgres` `money` columns are invalid on load from `postgres`.  New records can be created and saved, but on reloading, money column attributes become invalid.

[Script gist](https://gist.github.com/axlekb/6dfbfa45dd5e6137cb172e9cb37f4909)

### Expected behavior
Postgres `money` datatype columns should satisfy `numericality: true` validations in 5.2.0

### Actual behavior
Validation in 5.2.0 returns `false`.  Validation in 5.1.4 returns `true`.

### System configuration
**Rails version**: 5.2.0

**Ruby version**: 2.4.4p296

**Comment by KBalderson** [comment]
I ran git bisect, and it looks like the offending commit is: b3f3d49fd6b91c6573b3e10e3d00f65306638927

**Comment by axlekb** [comment]
I'm not up to speed on frozen string literals, but I _think_ it might be a missed `dup`.

https://github.com/rails/rails/commit/b3f3d49fd6b91c6573b3e10e3d00f65306638927#r28623270
