### ISSUE TITLE
Rails 5.2 cookies persist after removing RAILS_MASTER_KEY

### ISSUE THREAD

**Issue by 9mm** [rails/rails#32535]
I was migrating from 5.1 to 5.2 and decided to do some testing to make sure I migrated properly. My goal was to 'break' a user session by removing `RAILS_MASTER_KEY`, which in turn removes/nullifies `SECRET_KEY_BASE`. I wanted to then see if my valid session would expire. It did not.

I tested this in production on Heroku. I also did a second test locally on a fresh rails app with the same results.

### Steps to reproduce

1. Create a new blank rails 5.2 app which simply stores a value in a session, or outputs the value if it already exists.
2. Refresh a few times to see that its properly reading from the cookie
3. Stop Rails server
4. Delete `master.key`
5. Start rails server again

### Expected behavior

I would expect this would invalidate the current session, because SECRET_KEY_BASE is now changed (to an empty string I would assume?)

### Actual behavior

The actual behavior is that the session is still entirely valid. I can keep refreshing and it reads the session properly.

### System configuration

**Rails version**: 5.2
**Ruby version**: 2.5.1

**Comment by y-yagi** [comment]
`RAILS_MASTER_KEY` is used to read credentials, not affect to sessions. 
Therefore, even if you delete `master.key`, cookies can be read unchanged unless `SECRET_KEY_BASE` has changed. 
If you really want to discard all the session, explicitly change the value of `SECRET_KEY_BASE`.

**Comment by 9mm** [comment]
How does Rails even decrypt it if it doesnt have access to `SECRET_KEY_BASE`?

Also, btw, in my test ... I changed the value of SECRET_KEY_BASE and it still doesn't reset the session. I

**Comment by y-yagi** [comment]
It is impossible to read all the values previously held in session(If refer directly to `session`, nil will be returned). 

> Also, btw, in my test ... I changed the value of SECRET_KEY_BASE and it still doesn't reset the session.  

Have you tried it with development or test environment?  
From Rails 5.2, `secret_key_base` is automatically generated in the above environment, and ENV value is not used.
https://github.com/rails/rails/blob/8b0cdbef8a8606ddd0278d74e08a5674fc1a4a6e/railties/lib/rails/application.rb#L428..L430

If you are testing in the above environments, please test in other environment.

**Comment by 9mm** [comment]
I originally tested in production, that's what made me create this issue. I originally has `RAILS_MASTER_KEY` set (which inside of there includes the production value of `SECRET KEY BASE`)

I logged into my app (which uses the code `session[:user_id] = current_user.id`.

I then removed the `RAILS_MASTER_KEY` ENV variable (there is also no `master.key` in production because it's in my .gitignore).

When I restarted the server, I remain logged in, and it's pulling my current `user_id` right from the session.

I also double checked to make sure it restarted properly by calling... `Rails.application.credentials.read`, both before and after removing `RAILS_MASTER_KEY`.

Before removing it, the value is what you'd expect (the encrypted credential file with `secret_key_base`). After removing it + restarting server/rails, the value is also what you'd expect, an empty `""` string. Yet... when I visit the site I'm still logged in, and nothing is invalidated.

**Comment by y-yagi** [comment]
Can you confirm that the value of `Rails.application.secret_key_base` has changed before and after doing that work?

**Comment by 9mm** [comment]
I'll try again right now

**Comment by 9mm** [comment]
Hmm.. well that is weird. I am using Heroku... and when all my ENV variables are completely gone, my key is still there. Perhaps this is a Heroku security feature to prevent people from accidentally having an empty base key.

1. Deleted entire session cookie in production just to start fresh and get a 'clean slate'
2. Log into the site.. click around a few times. Confirm I'm logged in (it shows my username)
3. Enter production console, run `Rails.application.secret_key_base`, the result is as expected... A 128-character random string. Exit console
4. Leave browser open, enter production terminal, remove the `RAILS_MASTER_KEY` environment variable
5. Restart the server
6. Enter production console again, run `Rails.application.secret_key_base`, the result is the same 128-length string...

Sorry for this ticket, this production effect mixed with the testing locally was what threw me for a loop.
