### ISSUE TITLE
activesupport new version 5.2.0 can't handle attributes in memcache

### ISSUE THREAD

**Issue by akdasari** [rails/rails#32545]
### Steps to reproduce
Code:

chef_gem "activesupport"  -->  in my ruby file defaults to checkout 5.2.0 version
require 'active_support/core_ext/hash/deep_merge'
attrs = attrs.deep_merge(node.default_attrs) unless node.default_attrs.empty?
    attrs = attrs.deep_merge(node.normal_attrs) unless node.normal_attrs.empty?
    attrs = attrs.deep_merge(node.override_attrs) unless node.override_attrs.empty?
recipe_json = "{ \"run_list\": \[ "
    recipe_json << node.run_list.expand(node.chef_environment).recipes.map! { |k| "\"#{k}\"" }.join(",")
    recipe_json << " \] }"
    attrs = attrs.deep_merge(JSON.parse(recipe_json))
<end>

This code should fetch my attributes from cookbook into a json file and used this json in test case later as
Code:
subject { file("#{$node['jenkins']['master']['home']}/.keystore/cacerts") }
  it { should exist }
<End>

(Guidelines for creating a bug report are [available
here](http://guides.rubyonrails.org/contributing_to_ruby_on_rails.html#creating-a-bug-report))

### Expected behavior
should exist

### Actual behavior
 should exist (FAILED - 1)

### System configuration
**Rails version**:

**Ruby version**:
ruby 2.3.3p222
bundler (default: 1.16.1)

but when i used  activesupport 5.1.6 version this test passes, not sure what is changed in 5.2.0 and causing my test fail. can somebody help me?

**Comment by y-yagi** [comment]
Please use the above mentioned template and reproduce the problem you encountered with the file alone. If it is difficult to reproduce it as a single file, it is OK with Rails application. 
Either is okay, please give the steps to reproduce with a script that can be run. 
If they do not exist, can not investigate anything.

**Comment by akdasari** [comment]
i think it is bit difficult for me to reproduce with above template.
as i mentioned in my original post, as part of test case i read 
subject { file("#{$node['jenkins']['master']['home']}/.keystore/cacerts") }

which is a three layer node  jenkins-->master-->home and check .keystore under that, which works fine with activesupport 5.1.6 and doesn't work with 5.2.0. i was checking what could be causing this
it looks like activesupport depends upon activemodel ,might be that not modelling the attributes as i expected?

**Comment by y-yagi** [comment]
You need to give us more information on how to reproduce this issue, otherwise there is nothing we can do. Please read [Reporting an Issue](http://guides.rubyonrails.org/contributing_to_ruby_on_rails.html#reporting-an-issue) section for more information about creating bug reports. Thanks!

**Comment by akdasari** [comment]
not sure to test this individually, what i did is changed the version
my default.rb looks like this
=========================================
chef_gem "activesupport" do
  action :install
  version "5.1.6"
end

require 'pathname'
require 'active_support/core_ext/hash/deep_merge'

ruby_block "dump_node_attributes" do
  block do
    require 'json'

    attrs = {}

    attrs = attrs.deep_merge(node.default_attrs) unless node.default_attrs.empty?
    attrs = attrs.deep_merge(node.normal_attrs) unless node.normal_attrs.empty?
    attrs = attrs.deep_merge(node.override_attrs) unless node.override_attrs.empty?

    recipe_json = "{ \"run_list\": \[ "
    recipe_json << node.run_list.expand(node.chef_environment).recipes.map! { |k| "\"#{k}\"" }.join(",")
    recipe_json << " \] }"
    attrs = attrs.deep_merge(JSON.parse(recipe_json))
    puts "=A====="
    puts JSON.pretty_generate(attrs)
    puts "=Aend="
   
  end
end
==============================================
when i change the version to 5.2.0 i have different result
see i have pasted both 5.1.6 attributes and 5.2.0 attributes
5.1.6
=========
 "jenkins": {
    "java": "/usr/lib/jvm/java-1.8.0/bin/java",
    "executor": {
      "timeout": 240,
      "private_key": null,
      "proxy": null,
      "jvm_options": "-Djavax.net.ssl.trustStore=/var/lib/jenkins/.keystore/cacerts -Dhttp.nonProxyHosts=127.0.0.1\\|localhost\\|169.254.169.254\\|mybitbucket.com\\|master\\|172.27.14.66 -Dhttp.proxyHost=192.168.198.11 -Dhttp.proxyPort=3128 -Dhttps.proxyHost=192.168.198.11 -Dhttps.proxyPort=3128",
      "protocol": "remoting"
    },
    "master": {
      "install_method": "package",
      "version": null,
      "channel": "current",
      "mirror": "https://updates.jenkins.io",
      "source": "https://updates.jenkins.io/current/latest/jenkins.war",
      "checksum": null,
      "jvm_options": "-Djenkins.install.runSetupWizard=false -Djavax.net.ssl.trustStore=$JENKINS_HOME/.keystore/cacerts",
      "jenkins_args": null,
      "user": "jenkins",
      "group": "jenkins",
      "use_system_accounts": true,
      "host": "127.0.0.1",
      "listen_address": "0.0.0.0",
      "port": 8080,
      "endpoint": "http://127.0.0.1:8080",
      "home": "/var/lib/jenkins",
      "log_directory": "/var/log/jenkins",
      "maxopenfiles": 8192,
      "runit": {
        "groups": [
          "jenkins"
        ],
        "sv_timeout": 7
      },
      "ulimits": null,
-------------------------------------------------------------------------------------

5.2.0
========
 "jenkins": {                                                                               
    "java": "java",                                                                          
    "executor": {                                                                            
      "timeout": 240                                                                         
    },                                                                                       
    "master": {                                                                              
      "host": "127.0.0.1",                                                                   
      "channel": "current",                                                                  
      "proxy_host": "192.168.198.11",                                                        
      "proxy_port": "3128",                                                                  
      "no_proxy": "127.0.0.1,localhost,169.254.169.254,mybitbucket.com,master,172.27.14.66"  
    },                                                                                       
    "cacert": {                                                                              
      "password": "changeit"                                                                 
    },                                                                                       
    "node": {                                                                                
      "node_name": "node",                                                                   
      "retries": 20,                                                                         
      "retry_delay": 60                                                                      
    },                                                                                       
    "fqdn": "jenkins.aws.tlg.private"                                                        
  },                                   

why so many attributes which present in  [jenkins][master] missing in 5.2.0?
