### ISSUE TITLE
/storage/.keep is being gitignored, exception missing from .gitignore

### ISSUE THREAD

**Issue by TheAssailant** [rails/rails#32546]
Just ran rails new on a project and noticed the new `storage` folder is being gitignored despite having a `.keep`. Looked at .gitignore and looks like someone forgot to add `!/storage/.keep` under the `/storage/*` line.

I'm assuming this is unintended since `log` and `tmp` are also being ignored minus the `.keep` file, but feel free to close if I'm wrong.

### System configuration
**Rails version**: 5.2.0 stable

**Ruby version**: 2.5.1 stable

**Comment by y-yagi** [comment]
I think your point is correct. Can you open a PR to fix?

**Comment by TheAssailant** [comment]
I opened a PR.
