### ISSUE TITLE
[DOC] Method #end_of_week is missing in active_support/core_ext/date/calculations.rb

### ISSUE THREAD

**Issue by belgoros** [rails/rails#32543]
The [last Rails Guides](http://guides.rubyonrails.org/active_support_core_extensions.html#extensions-to-date) say:

> All the following methods are defined in active_support/core_ext/date/calculations.rb.

```
yesterday
tomorrow
beginning_of_week (at_beginning_of_week)
end_of_week (at_end_of_week)
monday
sunday
weeks_ago
prev_week (last_week)
next_week
months_ago
months_since
beginning_of_month (at_beginning_of_month)
end_of_month (at_end_of_month)
last_month
beginning_of_quarter (at_beginning_of_quarter)
end_of_quarter (at_end_of_quarter)
beginning_of_year (at_beginning_of_year)
end_of_year (at_end_of_year)
years_ago
years_since
last_year
on_weekday?
```
But when checking [calculations.rb](https://github.com/rails/rails/blob/master/activesupport/lib/active_support/core_ext/date/calculations.rb) file, `end_of_week`method does not seem to exist. I didn't check the other ones.

It is in `active_support/core_ext/date_and_time/calculations.rb` if I'm not wrong.

**Comment by matthewd** [comment]
> It is in active_support/core_ext/date_and_time/calculations.rb if I'm not wrong.

Right; a number of methods have been moved there to share across the Date & Time classes.

Want to open a PR to update the guide?

**Comment by belgoros** [comment]
@matthewd with pleasure, sooner or later, - I'll have to start 😄
