### ISSUE TITLE
5.2.0 activesupport problem caching attributes

### ISSUE THREAD

**Issue by akdasari** [rails/rails#32559]
### Steps to reproduce
file used as chef/rspec  --> default.rb
================================
chef_gem "activesupport" do
         action :install
         version "5.1.6"
end
require 'pathname'
require 'active_support/core_ext/hash/deep_merge'

ruby_block "dump_node_attributes" do
  block do
     require 'json'
        attrs = {}
        attrs = attrs.deep_merge(node.default_attrs) unless node.default_attrs.empty?
        attrs = attrs.deep_merge(node.normal_attrs) unless node.normal_attrs.empty?
        attrs = attrs.deep_merge(node.override_attrs) unless node.override_attrs.empty?
    recipe_json = "{ "run_list": [ "
    recipe_json << node.run_list.expand(node.chef_environment).recipes.map! { |k| ""#{k}"" }.join(",")
    recipe_json << " ] }"
        attrs = attrs.deep_merge(JSON.parse(recipe_json))
        puts "=A====="
          puts JSON.pretty_generate(attrs)
       puts "=Aend="
    end
end

### Expected behavior
part of json output where jenkins attributes supposed to be

"jenkins": {
    "java": "/usr/lib/jvm/java-1.8.0/bin/java",
    "executor": {
      "timeout": 240,
      "private_key": null,
      "proxy": null,
      "jvm_options": "-Djavax.net.ssl.trustStore=/var/lib/jenkins/.keystore/cacerts -Dhttp.nonProxyHosts=127.0.0.1\\|localhost\\|169.254.169.254\\|mybitbucket.com\\|master\\|172.27.14.66 -Dhttp.proxyHost=192.168.198.11 -Dhttp.proxyPort=3128 -Dhttps.proxyHost=192.168.198.11 -Dhttps.proxyPort=3128",
      "protocol": "remoting"
    },
    "master": {
      "install_method": "package",
      "version": null,
      "channel": "current",
      "mirror": "https://updates.jenkins.io",
      "source": "https://updates.jenkins.io/current/latest/jenkins.war",
      "checksum": null,
      "jvm_options": "-Djenkins.install.runSetupWizard=false -Djavax.net.ssl.trustStore=$JENKINS_HOME/.keystore/cacerts",
      "jenkins_args": null,
      "user": "jenkins",
      "group": "jenkins",
      "use_system_accounts": true,
      "host": "127.0.0.1",
      "listen_address": "0.0.0.0",
      "port": 8080,
      "endpoint": "http://127.0.0.1:8080",
      "home": "/var/lib/jenkins",
      "log_directory": "/var/log/jenkins",
      "maxopenfiles": 8192,
      "runit": {
        "groups": [
          "jenkins"
        ],
        "sv_timeout": 7
      },
      "ulimits": null,

### Actual behavior
 "jenkins": {                                                                               
    "java": "java",                                                                          
    "executor": {                                                                            
      "timeout": 240                                                                         
    },                                                                                       
    "master": {                                                                              
      "host": "127.0.0.1",                                                                   
      "channel": "current",                                                                  
      "proxy_host": "192.168.198.11",                                                        
      "proxy_port": "3128",                                                                  
      "no_proxy": "127.0.0.1,localhost,169.254.169.254,mybitbucket.com,master,172.27.14.66"  
    },                                                                                       
    "cacert": {                                                                              
      "password": "changeit"                                                                 
    },                                                                                       
    "node": {                                                                                
      "node_name": "node",                                                                   
      "retries": 20,                                                                         
      "retry_delay": 60                                                                      
    },                                                                                       
    "fqdn": "jenkins.aws.tlg.private"                                                        
  },

### System configuration
**Rails version**: 5.2.0

**Ruby version**: 2.3.3

 Missing lot of attributes in version 5.2.0   and works fine with version 5.1.6

**Comment by composerinteralia** [comment]
Is this the same as https://github.com/rails/rails/issues/32545 ? I'm afraid you are going to get the same response this time as you did the last time. If you are unable to reproduce the issue using one of our templates, try sending a link to a repo with step-by-step instructions for how to reproduce the issue there.
