### ISSUE TITLE
Updating (in an after_create callback ) an attribute value declared using store_accessor raises deprecation warning

### ISSUE THREAD

**Issue by kbleabres** [rails/rails#32555]
Trying to change/save a new value in and `after_create` callback for an attribute declared with `store_accessor` generates this deprecation warning:

> DEPRECATION WARNING: The behavior of `attribute_changed?` inside of after callbacks will be changing in the next version of Rails. The new return value will reflect the behavior of calling the method after `save` returned (e.g. the opposite of what it returns now). To maintain the current behavior, use `saved_change_to_attribute?` instead

I found a closed issue stating the same problem but was closed without solution https://github.com/rails/rails/issues/31087

### Steps to reproduce
Code sample: 
```ruby
store_accessor(
  :data_hash,
  :attribute_in_question
)

after_create :set_attibute_value

def set_attribute_value
  update_attributes(attribute_in_question: "value") 
end

```

### Expected behavior
Will run smoothly

### Actual behavior
`update_attributes` line will then trigger the deprecation warning

### System configuration
**Rails version:** 5.1.6
**Ruby version:** 2.3.0

After investigating, this line here is what (I think) causes the deprecation warning.
https://github.com/rails/rails/blob/375a4143cf5caeb6159b338be824903edfd62836/activerecord/lib/active_record/store.rb#L150

**Comment by domangi** [comment]
I traced back where the deprecation warning is generated. 

https://github.com/rails/rails/blob/0ae59ea828ed20141af0d4c9ed9130eb47ce55f3/activemodel/lib/active_model/dirty.rb#L238-L248

https://github.com/rails/rails/blob/0ae59ea828ed20141af0d4c9ed9130eb47ce55f3/activerecord/lib/active_record/attribute_methods/dirty.rb#L225-L228

https://github.com/rails/rails/blob/0ae59ea828ed20141af0d4c9ed9130eb47ce55f3/activerecord/lib/active_record/attribute_methods/dirty.rb#L249-L259

To get rid of it you can could replace attribute_changed? with saved_change_to_attribute? inside the attribute_will_change! method of activemodel. 

https://github.com/domangi/rails/blob/57c8f9eb410004f8379552536ffac53fe8a22389/activemodel/lib/active_model/dirty.rb#L237-L248

If you want to try it in your application you can try this solution using the following branch of my rails fork in your Gemfile:

`
gem 'rails', :git => "git://github.com/domangi/rails.git", :branch => "deprecation-warning-for-store-attributes"
`
