### ISSUE TITLE
Summer time

### ISSUE THREAD

**Issue by YarikST** [rails/rails#32550]
## Steps to reproduce

**config**
`config.time_zone = 'Europe/Kiev'`
db - utc

_create table - fields time_

t = Time.current
r = Table.first
t.field_time = t //15:00 - db save 13:00
Table.where field_time: t - where 12:00

```
2.4.0 :021 > t = Time.zone.now
 => Thu, 12 Apr 2018 19:59:59 EEST +03:00 
2.4.0 :022 > r.check_at = t
 => Thu, 12 Apr 2018 19:59:59 EEST +03:00 
2.4.0 :023 > r.save
   (0.7ms)  BEGIN
  User Load (1.2ms)  SELECT  "users".* FROM "users" WHERE "users"."id" = $1 LIMIT $2  [["id", 3], ["LIMIT", 1]]
  SQL (1.1ms)  UPDATE "report_histories" SET "check_at" = $1, "updated_at" = $2 WHERE "report_histories"."id" = $3  [["check_at", "17:59:59.049908"], ["updated_at", "2018-04-12 17:00:04.734353"], ["id", 1]]
   (7.9ms)  COMMIT
 => true 
2.4.0 :024 > r.reload
  ReportHistory Load (1.1ms)  SELECT  "report_histories".* FROM "report_histories" WHERE "report_histories"."id" = $1 LIMIT $2  [["id", 1], ["LIMIT", 1]]
 => #<ReportHistory id: 1, user_id: 3, absence_reason_id: nil, check: true, check_at: "2000-01-01 17:59:59", description: "d", reported_head: false, created_at: "2018-04-12 16:55:33", updated_at: "2018-04-12 17:00:04", day_of_week: 0> 
2.4.0 :025 > t
 => Thu, 12 Apr 2018 19:59:59 EEST +03:00 
2.4.0 :026 > ReportHistory.find_by check_at: t
  ReportHistory Load (1.1ms)  SELECT  "report_histories".* FROM "report_histories" WHERE "report_histories"."check_at" = $1 LIMIT $2  [["check_at", "2018-04-12 16:59:59.049908"], ["LIMIT", 1]]
 => nil 
2.4.0 :027 > ReportHistory.find_by check_at: t
  ReportHistory Load (1.2ms)  SELECT  "report_histories".* FROM "report_histories" WHERE "report_histories"."check_at" = $1 LIMIT $2  [["check_at", "2018-04-12 16:59:59.049908"], ["LIMIT", 1]]
 => nil 
```

where did the hour go ??? preservation and mischief works normally always 15:00 but the search is not right - probably I do something wrong

### Expected behavior
where 13:00

### Actual behavior
where 12:00

### System configuration
**5.1.5**:

**2.4.0**:

**ways to solve**

- self.skip_time_zone_conversion_for_attributes = [:field_time]
- config.time_zone = 'UTC'

**Comment by pixeltrix** [comment]
Looks like we should be converting the Ruby `Time` instance to 2000-01-01 when we're trying to search an SQL TIME column.

@YarikST the issue is that Ruby doesn't have a native class for a time of day without a date component so we try to normalise the date component to 2000-01-01, unfortunately there seems to be a bug where this isn't being done automatically when searching by that column. You should be able to workaround the problem for now by manually converting time value to 2000-01-01 by using `change`, e.g:

``` ruby
>> t = Time.current
=> Sat, 14 Apr 2018 16:38:49 EEST +03:00
>> t.change(year: 2000, month: 1, day: 1)
=> Sat, 01 Jan 2000 16:38:49 EET +02:00
```

**Comment by pixeltrix** [comment]
Whilst I fixed an issue in 7c479cbf6211d7efadc0a9573cf82c05291f7ef1 which meant that the leading date component wasn't being stripped from the quoted value there's a logic flaw where we use `quoted_date` to create the value first and then strip the date component off the string with `sub`. Unfortunately `quoted_date` will convert the value to UTC on the date component which may be different to the conversion to UTC on 2000-01-01 - to fix we need to use `change` in `quoted_time` to convert it to 2001-01-01 first. The relevant code is here:

https://github.com/rails/rails/blob/662ba236d115d3e2152b04dcdefdc0ee6f1f6102/activerecord/lib/active_record/connection_adapters/abstract/quoting.rb#L115-L134

**Comment by SeanPrashad** [comment]
Hi there, I'd love to pick this bug up as my first one for Rails if it's still available!

**Comment by azbshiri** [comment]
I'll take this. @pixeltrix @rafaelfranca
