### ISSUE TITLE
Example code is not IE11 compatible active_storage_overview.md

### ISSUE THREAD

**Issue by johan-smits** [rails/rails#32564]
### Steps to reproduce

https://github.com/rails/rails/blob/master/guides/source/active_storage_overview.md
The example of `direct_uploads.js` is not IE11 compatible

### Expected behavior
Invalid Javascript code on IE11

### Actual behavior
Example code that works on IE11 or add a disclaimer

### System configuration
**Rails version**: 5.2

**Ruby version**: 2.5.1

**Comment by pixeltrix** [comment]
@johan-smits are you able to say what's not IE11 compatible about the code?

**Comment by guilleiguaran** [comment]
I think template literals and arrow functions aren't supported by IE11 and I'm not sure about consts.

Maybe is ok to add a note saying that the code is ES6 and that you should use a transpiler like Babel or Webpacker.

**Comment by pixeltrix** [comment]
> Maybe is ok to add a note saying that the code is ES6 and that you should use a transpiler like Babel or use Webpacker.

I thought that was assumed - @johan-smits is your problem that it's not compatible without transpiling or that the transpiled code is incompatible?

**Comment by johan-smits** [comment]
The template `literals` and the `const { target, detail } = event` extraction are also not supported.

When you run development and it loads the assets IE complains about the pieces of code. I run with the rails 5.2 defaults for dev and production and it seems to serve the code 1:1.
