### ISSUE TITLE
Improve ActionCable js documentation accessibility

### ISSUE THREAD

**Issue by swrobel** [rails/rails#32567]
The documentation in the ActionCable [js](https://github.com/rails/rails/blob/5-2-stable/actioncable/app/assets/javascripts/action_cable/subscription.coffee) [files](https://github.com/rails/rails/blob/5-2-stable/actioncable/app/assets/javascripts/action_cable/subscriptions.coffee) are fairly well-documented, but that doesn't seem to be surfaced anywhere in the rails docs, or in the most obvious place (to me), the [npm page](https://www.npmjs.com/package/actioncable).

I think there's a way to expose this better than expecting people to open up the source but I'm not sure how Rails handles this for other included js.

### System configuration
**Rails version**: 5.2.0

**Comment by rafaelfranca** [comment]
We don't expose any JavaScript documentation, but maybe we should. @fxn ideas how to handle JavaScript in our API website?

**Comment by sarink** [comment]
👍 x 1000.... How is one to know how to use this thing?

**Comment by ziaulrehman40** [comment]
This is a real issues, just finished wasting hours on search for some docs on JS. But i guess there are none...

At-least mark this a known issue and not closed by bot so someone can start work on this.
