### ISSUE TITLE
web-console causes issues with debug crash page in development mode for out of the box 5.2 install

### ISSUE THREAD

**Issue by Yanchek99** [rails/rails#32578]
### Steps to reproduce
1. `gem install rails -v 5.2.0`
2. `rails new app`
3. Add code that will cause a crash
4. `rails s` In development environment
5. Hit path that will cause crash and observe instead of the normal debugger page we get a 500 error page and a extremely large log dump.

### Expected behavior
Standard development debug crash page

### Actual behavior
500 public page is displayed and an unusable log dump from web-console

### System configuration
**Rails version**:
5.2.0
**Ruby version**:
2.5.1

**Comment by y-yagi** [comment]
Hmm. In my environment, the debug page was displayed correctly. 
Can you upload your log?

**Comment by nikolaokonesh** [comment]
@y-yagi Подтверждаю, после обновлений получаем ошибку 500, это из-за какого-то gem's.

**Comment by Yanchek99** [comment]
@y-yagi I have uploaded a file when triggering a 404

[development.log](https://github.com/rails/rails/files/1911720/development.log)

**Comment by y-yagi** [comment]
Thanks. But this seems to be neither Rails nor web-console issue. 
Your application used remotipart 1.4.0, and remotipart 1.4.0 seems to have an issue with using web-console.
https://github.com/JangoSteve/remotipart/issues/194 

Please try downgrading remotipart. 
Also, this issue does not happen with a simple Rails application. 
If the problem reappears in the Rails application that just did `rails new`, please reopen. Thanks.

**Comment by gsamokovarov** [comment]
Can you report this on the [rails/web-console](https://github.com/rails/web-console) tracker? If you can reproduce it, I'll look into it.

**Comment by nikolaokonesh** [comment]
@gsamokovarov log is very very large
