### ISSUE TITLE
whats whis error undefined method `relation_delegate_class' for Module

### ISSUE THREAD

**Issue by nikolaokonesh** [rails/rails#32579]
![screenshot-2018-4-15 action controller exception caught 1](https://user-images.githubusercontent.com/6263853/38774885-d0c11818-40bd-11e8-8696-ffd94cedb1da.png)
routes.rb
```
  resources :books do
    resources :categories, module: :books do
      resources :posts, module: :categories
    end
  end
```
models
```
class Book < ApplicationRecord
  include Slugged
  belongs_to :user
  has_many :categories, dependent: :destroy
end
class Category < ApplicationRecord
  include Slugged
  belongs_to :user
  belongs_to :book
  has_many :posts, dependent: :destroy
end
class Post < ApplicationRecord
  include Slugged
  belongs_to :user
  belongs_to :category
end

```
**Rails version**: 5.2.0
**Ruby version**: 2.5.0

**Comment by y-yagi** [comment]
Could you create a reproduction script with this template https://github.com/rails/rails/blob/master/guides/bug_report_templates/active_record_master.rb ?

**Comment by nikolaokonesh** [comment]
@y-yagi solved the problem, renamed the book.rb model to edition.rb. Yet, I could not understand what the problem was.

**Comment by sikachu** [comment]
Seems like a constant reference issue. Looks like you have a module name `Book::Category` too, right?

Try setting an explicit model class on your categories association:

```ruby
class Book < ApplicationRecord
  has_many :categories, dependent: :destroy, class_name: “::Category”
end
```
