### ISSUE TITLE
5.2 content security policy settings block js views rendered

### ISSUE THREAD

**Issue by mdesantis** [rails/rails#32577]
I guess that Rails 5.2 should include the nonce by default when rendering a JS view and CSP nonce generator is enabled. Is there any workaround or we should stick with `:unsafe_inline` when rendering a js view?

### Steps to reproduce

1. Create a new Rails 5.2 app
2. Comment out Rails 5.2 default CSP rules
3. Render a js view containing `alert('hello')` after clicking on a `link_to remote: true` link

### Expected behavior

The browser should open an alert window displaying the "hello" message

### Actual behavior

The alert window doesn't spawn up and the browser prints an error message about a script that has been blocked by current CSP configuration settings

### System configuration
**Rails version**: 5.2.0

**Ruby version**: 2.4.4

**Comment by mdesantis** [comment]
Thank you for the reproduce app, I had to do it at first. Anyway, I have to add that I can reproduce the issue **on Firefox**, while on Chrome it works. This is a GIF of the issue on Firefox (59.0.2 on Linux):

![GIF of the issue on Firefox (59.0.2 on Linux)](https://user-images.githubusercontent.com/283320/38802527-f69d2b6c-416c-11e8-9b23-ffd74e09f9dd.gif)

So it could be a Firefox bug?

**Comment by y-yagi** [comment]
Thank you for the information. I was able to reproduce.
I do not know yet whether it is a Firefox issue or a Rails issue, so I will investigate.

**Comment by y-yagi** [comment]
This was an issue with Rails. I fixed this with  #32600. Thank you for the report!
