### ISSUE TITLE
Include Rack::ContentLength by default

### ISSUE THREAD

**Issue by chaffeqa** [rails/rails#32585]
### Steps to reproduce

(Guidelines for creating a bug report are [available
here](http://guides.rubyonrails.org/contributing_to_ruby_on_rails.html#creating-a-bug-report))

### Expected behavior
When deployed to AWS, the best out-of-box experience occurs

### Actual behavior
Gzip behind Cloudfront silently fails

### System configuration
**Rails version**: 5.1

**Ruby version**: 2.5

Cloudfront acts as a quick substitute for nginx, and has a checkbox titled `Compress Objects Automatically`.  I have now in x2 projects been burned by thinking I could just click that and all works.  However, in (the buried documentation)[https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/ServingCompressedFiles.html] the server needs to supply a `content-length` header.

I don't know if the performance hit for enabling this by default is worth it, but I wanted to call it out.  I trust your discretion to make the decision, but the simple solution is:

```ruby
    # Add content length to make sure cloudfront can gzip content
    config.middleware.use(Rack::ContentLength)
```

**Comment by y-yagi** [comment]
This is intentional behaviour. 

Since ContentLength is no longer part of rack's SPEC, Rails is no longer loaded by default. 
If you want it, just add it as a middleware in your config.  

Ref: 56903585a099ab67a7acfaaef0a02db8fe80c450
