### ISSUE TITLE
Document CORS configuration for direct uploads

### ISSUE THREAD

**Issue by georgeclaghorn** [rails/rails#32581]
To use direct uploads with a cloud storage service like S3 or Google Cloud Storage, you must configure the service to accept cross-origin requests from all of your application’s domains. We neglect to mention this in the guides, leaving Active Storage users to stub their toes when direct uploads fail in production.

**Comment by wbotelhos** [comment]
Hi @georgeclaghorn and @lucaong ,

I did not configurate the header to direct upload, but attached a policy to EC2 with `Action: s3:*`, maybe it solved.

Should I let my bucket public for `List objects`? Only with that I could make upload and show works.

**Comment by gaurish** [comment]
fixed via #34028

**Comment by connorshea** [comment]
This just bit me in production, I would really appreciate documentation on this!
