### ISSUE TITLE
ActiveRecord::FinderMethods#last does not respect offset and does not order by primary key

### ISSUE THREAD

**Issue by hnatt** [rails/rails#32588]
### Steps to reproduce

```Ruby
Comment.offset(2).last(2).map(&:id)
```

### Expected behavior

In Rails 5.1, this would generate the following SQL:

```SQL
  Comment Load (0.7ms)  SELECT  "comments".* FROM "comments" ORDER BY "comments"."id" DESC LIMIT $1 OFFSET $2  [["LIMIT", 2], ["OFFSET", 2]]
```

and return the ids of the 4th and 3rd to bottom comments .

### Actual behavior

But in Rails 5.2, the query is:

```SQL
    Comment Load (1.3ms)  SELECT "comments".* FROM "comments" OFFSET $1  [["OFFSET", 2]]
```

(note how it does not add LIMIT to the query).

And the records returned are the 2nd and the 1st from the bottom. In fact `Comment.offset(20).last(2)` would return same 2nd and 1st to bottom records.

### System configuration
**Rails version**: 5.2.0, master

**Comment by hnatt** [comment]
cc: @kamipo

**Comment by bogdanvlviv** [comment]
Thanks for the issue.
Not sure that assertion `assert_equal post.comments.all.reverse.first(4).last(2).reverse, post.comments.offset(2).last(2)` is correct, I guess it should be `assert_equal post.comments.all.reverse.first(4).first(2).reverse, post.comments.offset(2).last(2)`
I can't reproduce any regression in behaviour of using `offset` with `last`. furthermore, seems it should work correctly since 68754d37706f11ca363b3108eda10749b9957817
/cc @kamipo

**Comment by hnatt** [comment]
@bogdanvlviv my previous assertion was confusing. I tried to extract my real world case and did not do a very good job.

Here is a more clear one:

```
  def test_last_on_relation_with_offset
    post = posts("sti_comments")

    assert_not_equal post.comments.offset(0).last(2), post.comments.offset(2).last(2)
  end
```

--that checks that when we have a pagination, adjacent pages should not have same records.

It also passes in https://github.com/rails/rails/commit/a194c527fa7b16840fd1b1250dc9f624c6536546 but fails starting with https://github.com/rails/rails/commit/68754d37706f11ca363b3108eda10749b9957817 and up to current master. Or did it just work wrong before and I was relying on the wrong behavior?

**Comment by bogdanvlviv** [comment]
I think your code was relying on the wrong behavior, but i would like to  know @kamipo's thought about that.
In your case i think using of `.limit(2)` instead of `.last(2)` will fix your problem.

**Comment by hnatt** [comment]
Thanks @kamipo and @bogdanvlviv! Closing this issue then!
