### ISSUE TITLE
Rails cannot find generator templates with .rb extension; they now end with .tt

### ISSUE THREAD

**Issue by nfuller52** [rails/rails#32583]
### Steps to reproduce
I updated a young rails 5.1 application to 5.2, and henceforth I have been unable to use any of the rails generators; including `rails new`. I am using rvm, ruby 2.5.1 and rails 5.2.0.

I've re-installed rails, all my gems, and ruby. I also tried on my other laptop and I still experience this issue. 

1. rails generate controller Publications
-> Could not find "controller.rb" in any of your source paths. Your current source paths are:
/Users/nfuller/.rvm/gems/ruby-2.5.1/gems/railties-5.2.0/lib/rails/generators/rails/controller/templates

### Expected behavior
The rails generator should use template files with .tt extension

### Actual behavior
The rails generators are looking for .rb file extensions

### System configuration
**Rails version**: 5.2.0

**Ruby version**: 2.5.1

**Comment by y-yagi** [comment]
I could not reproduce your issue. 

```
$ ./bin/rails -v
Rails 5.2.0
$ ./bin/rails generate controller Publications
Running via Spring preloader in process 12478
      create  app/controllers/publications_controller.rb
      invoke  erb
      create    app/views/publications
      invoke  test_unit
      create    test/controllers/publications_controller_test.rb
      invoke  helper
      create    app/helpers/publications_helper.rb
      invoke    test_unit
      invoke  assets
      invoke    coffee
      create      app/assets/javascripts/publications.coffee
      invoke    scss
      create      app/assets/stylesheets/publications.scss 
``` 

Can you provide a sample application that reproduces the issue?

**Comment by nfuller52** [comment]
@y-yagi sorry i must not have fully updated gemset with `bundle update`. after running this it works. my apologies!
