### ISSUE TITLE
Rails with SQLite Encrypted

### ISSUE THREAD

**Issue by gabrielwillemann** [rails/rails#32589]
Hello,

I have a question: Can Rails access SQLite database with encrypt?

PS: In SQLiteBrower there is a option to encrypt database file.

**Comment by y-yagi** [comment]
Please use the [mailing list](https://groups.google.com/forum/#!forum/rubyonrails-talk) or StackOverflow for questions/help, where a wider community will be able to help you. We reserve the issues tracker for issues only. Thanks.
