### ISSUE TITLE
ActiveStorage disk service host is missing

### ISSUE THREAD

**Issue by xzdshr** [rails/rails#32590]
Hello! After upgrading from 5.2.0.rc2 to 5.2.0 all service_url calls starts to raise an error:

![1](https://user-images.githubusercontent.com/2665232/38814935-63da04ec-419b-11e8-9096-35c70727fd8f.png)

:host key was removed from storage.yml previously. What is the best approach now to set the disk service host?
Setting `ActiveStorage::Current.host = ENV.fetch('HOST')` before service_url call seems pretty dirty to me...

## System configuration
Rails version: 5.2.0
Ruby version: 2.5.1

**Comment by y-yagi** [comment]
It seems the same issue with https://github.com/rails/rails/pull/32350#issuecomment-380091447 
What happens when use `rails_blob_url` and `rails_representation_url` instead of `service_url`?

**Comment by xzdshr** [comment]
@y-yagi yes it is. Works perfectly with url_helpers, thank you!
I guess we shouldn't use service_url outside of ActiveStorage controllers.

**Comment by oolzpishere** [comment]
@y-yagi How to use rails_representation_url? What argument could pass to? 
I would like to get the variant path.
