### ISSUE TITLE
Setting action_dispatch.default_headers in a file initializer does not work

### ISSUE THREAD

**Issue by uri** [rails/rails#32592]
### Steps to reproduce

1. Set `action_dispatch.default_headers` in a file initializer.

See uri/actionpack-init-test@86139c957b7d8dcdf7ce2d5f417c2f2e91eef93b for a full rails app example or the [action dispatch gem bug template](https://gist.github.com/uri/3fe7c5d061db72ef985b95d84732852c)

### Expected behavior

The new header should appear in the response.

### Actual behavior

The new header does not appear in the response.

### System configuration
**Rails version**: 5.1.6

**Ruby version**: 2.4.2p198 

------

Technically this isn't a bug as the documentation for Rails initialization states that railties run before file initializers. However the experience isn't great. No errors are raised and the intended configuration does not work.

I would speculate that this isn't unique to action_dispatch and affects most railties? I would also be happy to work on improving the experience. Maybe adding some warnings in the docs or, a code change to fix the behavior or make it more obvious.

**Comment by rafaelfranca** [comment]
There is a problem in your bug template. The application needs to be initialized, but in a real life application you are correct. We can't change the `config.action_dispatch` configs after the `ActionDispatch::Railtie` initializers are run. That problem only exists on Action Dispatch configs the other Railties defer the config setting to when the base class of the framework is loaded, and that is after all initializers have run.

We should improve this by freezing the config object after they configs are applied. Mind to open a PR?

**Comment by wenga86** [comment]
Any update on this?

**Comment by rafaelfranca** [comment]
No.

**Comment by uri** [comment]
Still planning on picking it up. I quickly tried freezing the config object in a first attempt but ran into problems. Will explore more when I get a chance.
