### ISSUE TITLE
CSP nonces being added to header after every request indefinitely

### ISSUE THREAD

**Issue by Envek** [rails/rails#32597]
### Steps to reproduce

Set up CSP with nonce generator: 

```ruby
Rails.application.config.content_security_policy do |p|
  p.script_src  :self
end

Rails.application.config.content_security_policy_nonce_generator = -> request { request.uuid[0...8] }
```

See test gist: https://gist.github.com/Envek/b8835b8fb93c8d85c2398df3fab9e0d8

### Expected behavior

CSP header have single different nonce on each request

### Actual behavior

Nonces from old requests are saved, a nonce from the current request is added to the end of `script-src` directive.

Header size grows infinitely after every request:

```
$ curl -I http://localhost:5000
…
Content-Security-Policy: script-src 'self' 'nonce-e07e1ccd' 'nonce-7e9ca9a2' 'nonce-a1b50d07' 'nonce-e26f107a'
```

### System configuration
**Rails version**: 5.2.0, master
**Ruby version**: 2.5.1

### Causing code
https://github.com/rails/rails/pull/32018/files#diff-4b684bb480d7c554fe79bbb4e0f241a7R26

### Notes

I've looked at the code and at the moment can'f figure a way how to fix it without breaking current API (implicit nonce adding). IMO it'd better make it explicit with kind of special symbol like `:nonce` added to DSL.

**Comment by yaroslav** [comment]
Can reproduce on a different application running 5.2.0, with a  `content_security_policy_nonce_generator` proc straight out of a default config.

A simple zsh script of `repeat 20000 { curl -I http://0.0.0.0:3000/ }` makes the printout of response headers (nonce this, nonce that) as big as several terminal screens.
