### ISSUE TITLE
Rails PUMA server crashes on pressing CTRL+Z

### ISSUE THREAD

**Issue by Faizaankhan3** [rails/rails#32601]
### Steps to reproduce
While I am debugging my application by using "binding.pry" in the pry console, if I mistakenly hit the CTRL + Z key , the server is suspended, and the pointer comes back to the command line, though it looks like the server is closed, it actually doesn't close. Trying to start the server again fails.

### Expected behavior
Nothing should probably happen to an abruptly pressed key combination ("ctrl +z" here)  if theirs no feature attached to it.

### Actual behavior
The server runs on the background and theirs no easy way to escape, or restart the server, or get back to the pry console.

### System configuration
**Rails version**: Rails 4.2.10

**Ruby version**: ruby 2.4.1p111 (2017-03-22 revision 58053) [x86_64-linux]

**Comment by y-yagi** [comment]
That is a general behavior when using a shell, and I think that Rails should not take special measures.
If you want to return the suspended job, you can return it immediately by using the `fg` command. Thanks.

**Comment by Faizaankhan3** [comment]
Thanks fg works for me !
