### ISSUE TITLE
redirect_to not working in Safari, Firefox and Chrome Incognito Mode

### ISSUE THREAD

**Issue by drale2k** [rails/rails#32606]
Redirects with redirect_to seem to not be working in the browsers mentioned. Given the simple code:

```ruby
def create
    @operation = Operation.new(operation_params)
    if @operation.save
      redirect_to @operation
    else
      render 'new'
    end
  end

```

The site stays on the same page. The @operation is created properly in the database and the logs show the following output:

```
(0.2ms)  BEGIN
   (0.2ms)  BEGIN
  Operation Exists (0.4ms)  SELECT  1 AS one FROM "operations" WHERE "operations"."name" = $1 LIMIT $2  [["name", "Geht"], ["LIMIT", 1]]
  Operation Exists (0.4ms)  SELECT  1 AS one FROM "operations" WHERE "operations"."name" = $1 LIMIT $2  [["name", "Geht"], ["LIMIT", 1]]
  Operation Create (0.5ms)  INSERT INTO "operations" ("name", "created_at", "updated_at", "encryption_key") VALUES ($1, $2, $3, $4) RETURNING "id"  [["name", "Geht"], ["created_at", "2018-04-16 16:39:20.980613"], ["updated_at", "2018-04-16 16:39:20.980613"], ["encryption_key", "d06f02b2c92feb291036b996156addcecdcd5e0a80c6793a3c209bd8de4f36ad"]]
  Operation Create (0.5ms)  INSERT INTO "operations" ("name", "created_at", "updated_at", "encryption_key") VALUES ($1, $2, $3, $4) RETURNING "id"  [["name", "Geht"], ["created_at", "2018-04-16 16:39:20.980613"], ["updated_at", "2018-04-16 16:39:20.980613"], ["encryption_key", "d06f02b2c92feb291036b996156addcecdcd5e0a80c6793a3c209bd8de4f36ad"]]
   (2.1ms)  COMMIT
   (2.1ms)  COMMIT
Redirected to http://localhost:3000/operations/1a5d7e87-a7e3-4ced-ab2a-1b45a62c0cc5
Redirected to http://localhost:3000/operations/1a5d7e87-a7e3-4ced-ab2a-1b45a62c0cc5
Completed 200 OK in 13ms (ActiveRecord: 5.8ms)
```

According to the console output the redirects are happening but in the browser nothing happens. On the other side when testing with Chrome __normal mode__ it works and the redirect happens properly.

### Tested on (does not work on the following setups)
MacOS 10.13.4, Safari 11.1 (normal mode), Chrome 65 (Incognito Mode) and Firefox 59 (normal mode)
Windows 10 on Chrome 65 Incognito Mode

### Expected behavior
Redirect to given path

### Actual behavior
Instead of a redirect it stays on the page.

### System configuration
5.2.0

**Ruby version**:
2.4.1

**Comment by pixeltrix** [comment]
@drale2k can you create an example repo that exhibits this problem? Does it work in these browsers in non-icognito mode?

**Comment by vivekcoder** [comment]
Did you notice the duplicate requests being sent and to your server? This might also confuse your browser having received multiple 302 responses.

**Comment by villu164** [comment]
Would love to help with debugging. 
Couldn't reproduce the bug.
Did an empty repo to start with. 
https://github.com/villu164/redirect_bug
@drale2k, have you tried using ```pry-rails``` and entering with ```binding.pry``` ?
