### ISSUE TITLE
Make the master.key file private upon generation?

### ISSUE THREAD

**Issue by jlduran** [rails/rails#32604]
### Steps to reproduce

    rails new app

### Expected behavior

The `config/master.key` file should not be world-/group-readable (at least on POSIX-compliant systems).

### Actual behavior

The `config/master.key` is readable by all users in the system.

    ls -l config/master.key
    -rw-r--r--   1 user  group    32 Jan 1 00:00 master.key

### System configuration
**Rails version**: 5.2.0, master

**Ruby version**: 2.5.1

### Suggestion

Perhaps after:

https://github.com/rails/rails/blob/c8dc4f2e41afa07c2b2ec701e2ba4682e5ccdd37/railties/lib/rails/generators/rails/encryption_key_file/encryption_key_file_generator.rb#L11

add:

```ruby
key_path.chmod 0600
```

**Comment by rafaelfranca** [comment]
Sounds good. Mind to open a PR?
