### ISSUE TITLE
ActiveRecord enums querying acts strange with MySQL

### ISSUE THREAD

**Issue by SGospodinov** [rails/rails#32618]
### Steps to reproduce
You can use the following reproduction scrip:
```ruby
# frozen_string_literal: true

begin
  require "bundler/inline"
rescue LoadError => e
  $stderr.puts "Bundler version 1.10 or later is required. Please update your Bundler"
  raise e
end

gemfile(true) do
  source "https://rubygems.org"

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  # Activate the gem you are reporting the issue against.
  gem "activerecord", "5.2.0"
  gem "mysql2"
end

require "active_record"
require "minitest/autorun"
require "logger"

# Ensure backward compatibility with Minitest 4
Minitest::Test = MiniTest::Unit::TestCase unless defined?(Minitest::Test)

# This connection will do for database-independent bug reports.
ActiveRecord::Base.establish_connection(
  adapter: "mysql2",
  #other db credentials
)
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :posts, force: true do |t|
    t.integer :status, default: 0
  end
end

class Post < ActiveRecord::Base
  enum status: [:published, :archived]
end

class UnexistingEnumValueTest < Minitest::Test
  def test_where_with_unpublished_status
    2.times { Post.create!(status: :published) }
    Post.create!(status: :archived)

    assert_equal 0, Post.where(status: :unpublished).count
    assert_equal 0, Post.where(status: "unpublished").count
  end
end
```

### Behaviour
Obviously, this code should return an empty collection, but it returns all of the records with the enum value, which matches 0 at the database (`:published` in this case).
The `where` method executes a query which looks like this `SELECT  posts.* FROM posts WHERE posts.status = 'unpublished'`. I'm not sure if the problem is with `mysql2` gem or with MySQL itself, but the, in my opinion, the problem could be solved at the ActiveRecord level. If the `where` method evaluates the enum params and raises an error if they do not exist (like the `create` method) the query won't be executed, at all.
I tried to reproduce the issue with `sqlite3`, but it was working properly with it.

### System configuration
**Rails version**: 5.2.0 (but I also had it on 5.1.4)
**Ruby version**: 2.5.0
**mysql2 version**: 0.5.1
**MySQL Server version**: 5.7.21-0ubuntu0.16.04.1

**Comment by rafaelfranca** [comment]
This is the expected behavior. If you passed an inexistent enum value to the query it will query that value. It is not the job of active record to be checking what you pass to a query.

MySQL returns something because when you compare a string with a integer column it casts the string to "0"

```
mysql> select 0 = "foo";
+-----------+
| 0 = "foo" |
+-----------+
|         1 |
+-----------+
1 row in set, 1 warning (0.00 sec)

mysql> select 1 = "foo";
+-----------+
| 1 = "foo" |
+-----------+
|         0 |
+-----------+
1 row in set, 1 warning (0.00 sec)

mysql> select 1 = "1foo";
+------------+
| 1 = "1foo" |
+------------+
|          1 |
+------------+
1 row in set, 1 warning (0.00 sec)
```

In SQLite and PostgreSQL it doesn't' try to cast.

**Comment by SGospodinov** [comment]
Thank you @rafaelfranca. That explains a lot, but don't you think that this behaviour has to be documented? I'll be happy to help.
