### ISSUE TITLE
Would love to have search feature on RailsGuide site, please?

### ISSUE THREAD

**Issue by lillers1122** [rails/rails#32615]
### Steps to reproduce
Go to RailsGuide site.

### Expected behavior
Need to find specific information about Rails..would love to have a search feature.

### Actual behavior
No search feature...yet? Thank you!

### System configuration
**Rails version**: 5.0.7

**Ruby version**: 2.5.0

**Comment by arthur-marz** [comment]
I guess, simple search by titles of articles would not suffice. Can we do something full-texty?

**Comment by saiqulhaq** [comment]
it's simple 

use following query in google or duckduckgo

```
site:http://guides.rubyonrails.org yourActualKeywordHere
```

**Comment by sikachu** [comment]
It's impossible to do it with the current infrastructure, as Rails Guide is currently static HTML pages. Adding a full text search functionality would require infrastructure change which I'm not sure if we can support it.

The workaround is definitely just pass `site:http://guides.rubyonrails.org KEYWORD` to your search engine of choice.

Summoning @fxn for more insight on this one.

**Comment by fxn** [comment]
What @sikachu said.

The next foreseable evolution of the guides would be a simplified generation workflow based on Jekyll or something. But a dynamic website is not planned ATM.

Thanks for bringing this up anyway.
