### ISSUE TITLE
RedisCacheStore#delete_matched blocks and causes timeouts

### ISSUE THREAD

**Issue by glebm** [rails/rails#32610]
The current implementation of `delete_matched` in `RedisCacheStore` is this:

https://github.com/rails/rails/blob/6378a386ddd1beb998ec9149a284d5fb13d491c7/activesupport/lib/active_support/cache/redis_cache_store.rb#L232-L241

However, lua scripts in redis are *blocking*, meaning that no other client can execute any commands while the script is running (except `SCRIPT KILL` and `SHUTDOWN NOSAVE`, see https://redis.io/commands/eval#atomicity-of-scripts).

This results in the following exceptions once the number of keys is large enough:

```ruby
BUSY Redis is busy running a script. You can only call SCRIPT KILL or SHUTDOWN NOSAVE.
```

Proposed fix is to avoid a script and `SCAN` then `DEL` in a loop. `SCAN` is a non-blocking alternative to `KEYS`. It has some limitations but they do not matter for this use-case.

/cc @jeremy @fatkodima @georgeclaghorn

**Comment by glebm** [comment]
Proposed implementation:

```ruby
# The maximum number of entries to receive per SCAN call.
SCAN_BATCH_SIZE = 1000
private_constant :SCAN_BATCH_SIZE

def delete_matched(matcher, options = nil)
  instrument :delete_matched, matcher do
    unless String === matcher
      raise ArgumentError, "Only Redis glob strings are supported: #{matcher.inspect}"
    end
    redis.with do |c|
      start = '0'
      pattern = namespace_key(matcher, options)
      while true
        start, keys = c.scan(start, match: pattern, count: SCAN_BATCH_SIZE)
        c.del(*keys) unless keys.empty?
        break if start == '0'
      end
    end
  end
end
```

**Comment by jeremy** [comment]
SCAN+DEL loop makes sense. Moving to your PR. Thanks @glebm!
