### ISSUE TITLE
Postresql index with type casting using CAST AS is non-rollbackable

### ISSUE THREAD

**Issue by tomash** [rails/rails#32621]
### Steps to reproduce

The requirement: adding typecasted index, namely created_at typecasted to DATE type because we're calculating daily statistics and therefore choosing rows with `WHERE payments.created_at::date='2018-03-01'`.

Adding a migration with

`add_index :payments, "CAST(created_at AS date)"`

creates an index and the following entry in schema.rb:

`t.index "((created_at)::date)", name: "index_payments_on_CAST_created_at_AS_date"`

So the migration engine was smart enough to shorthand `CAST AS` syntax into `::` syntax, **BUT** puts the wrong name of newly created index into schema.rb. The actual name of index in the database is also generated based on shorthand form (which is nice and consistent), it's `index_payments_on_created_at_date` in this case.

Unfortunately the naming inconsistency causes the migration to be non-rollbackable, because

```
$ rails db:rollback
== 20180418123502 AddIndexToCreatedAtAsDate: reverting ========================
-- remove_index(:payments, {:column=>"CAST(created_at AS date)"})
rails aborted!
StandardError: An error has occurred, this and all later migrations canceled:

No indexes found on payments with the options provided.
/home/tomek/.rvm/gems/ruby-2.5.0/gems/activerecord-5.1.5/lib/active_record/connection_adapters/abstract/schema_statements.rb:1236:in `index_name_for_remove'
/home/tomek/.rvm/gems/ruby-2.5.0/gems/activerecord-5.1.5/lib/active_record/connection_adapters/postgresql/schema_statements.rb:502:in `remove_index'
```

Or to put it shortly, the index with given name does not exist.

WORKAROUND: use shorthand form in migration, in this case

`add_index :payments, "((created_at)::date)"`

which creates a proper entry in schema.rb:

`t.index "((created_at)::date)", name: "index_payments_on_created_at_date"`

and rolls back like a charm.

### Expected behavior

`CAST AS` form should generate rollback-able migrations.

### System configuration
**Rails version**: 5.1.5

**Ruby version**: 2.5.0

**Comment by tomash** [comment]
Note: I'll make a reproducible test case with [active_record_gem.rb](https://github.com/rails/rails/blob/master/guides/bug_report_templates/active_record_gem.rb) asap.

**Comment by abaldwin88** [comment]
Reproduced case:  https://gist.github.com/abaldwin88/c24db432b7b351fafe56797b97ae6a54

**Comment by abaldwin88** [comment]
For posterity -- The reproduction script is passing against version 7.0.5 (And may potentially succeed for versions after 5.2)
