### ISSUE TITLE
Rails 5.2 generates apps for JRuby that switches rvm to CRuby

### ISSUE THREAD

**Issue by headius** [rails/rails#32639]
### Steps to reproduce

Generate an app for JRuby. It will contain a .ruby-version file that requests "2.3.3", causing rvm to either switch to CRuby 2.3.3 or request that you install it.

### Expected behavior

It should not try to switch you to CRuby.

### Actual behavior

It tries to switch you to CRuby.

### System configuration

Rails version 5.2.0.

JRUBY version 9.1.x.

**Comment by guilleiguaran** [comment]
I think right now the .ruby-version file contains just the output of `RUBY_VERSION` constant.

wdyt about setting this to `#{RUBY_ENGINE}-#{JRUBY_VERSION}` when JRuby is detected?

**Comment by headius** [comment]
Personally I hate .ruby-version, but that may be because I'm constantly testing different versions of JRuby and Ruby. If setting it to `jruby-<jruby version>` seems appropriate, that should be fine. Really, if you want to lock down a generated app to a specific version, I think you should include engine always.

**Comment by headius** [comment]
FWIW, it's a common pattern for JRuby users to also use CRuby for day-to-day development, which a .ruby-version gets in the way of. My vote still goes to removing it altogether.

**Comment by headius** [comment]
Case in point: https://twitter.com/ninkibah/status/987016190433398785

**Comment by guilleiguaran** [comment]
Given the discussion in https://github.com/rails/rails/pull/30016, looks like .ruby-version isn't going to be removed until rbenv understand how to read the .ruby-version from the Gemfile 😓

**Comment by headius** [comment]
@guilleiguaran Yeah that's too bad. I really don't get why people want to have this behavior. I never want my env or path to change just `cd`ing into a directory.

At least we need to get it using a proper Ruby impl specification rather than just Ruby version.
