### ISSUE TITLE
ActiveRecord sometimes saves data with nil attributes

### ISSUE THREAD

**Issue by icecold21** [rails/rails#32631]
### Expected behavior
Saves data with correct attributes.

### Actual behavior
Sometimes data are saved with all attributes set to nil, this happens on production environment with high traffic. Most of the time it happens with the has_many relationship objects when creating them through parent object which accept_nested attributes for them, but I have also experienced parent object created with nil data:

Belows is the example of the saved records.
![image](https://user-images.githubusercontent.com/17531591/38970759-8c1d72cc-43c1-11e8-955e-e32fafdfaf5c.png)

### System configuration
Rails 4.2.4
### Ruby version
Ruby 2.3.1

**Comment by Edouard-chin** [comment]
Hey 👋 , do you mind providing a reproduction script. It's hard to diagnose the problem you are facing without one.

**Comment by pixeltrix** [comment]
@icecold21 this sounds very much like a concurrency issue - are you using a threaded app server like puma? Also 4.2.4 is very out of date - is it possible to upgrade to 4.2.10 and then see whether the problems still exist?

**Comment by vivekcoder** [comment]
Do you have model (presence: true) and DB (not null) validations for TransactionLine? Model validations, however are not run by update_all method. If you can attach a sample params object here, that would help.
