### ISSUE TITLE
Accessing dynamically created form input on Rails controller

### ISSUE THREAD

**Issue by josecordova** [rails/rails#32634]
I have a form that users can dynamically add more items to. The JavaScript gives each input field a name such as quantity1, description1 for the first record, quantity2, description2 for the second record and so on. How can I loop through this on the controller? I am looking for something that looks like this:

@item.quantity = params[:quantity1]
@item.description = params[:description1]

But dynamically in that I can put a counter to go through each item:

@item.quantity = params[":quantity" + @counter] 
@counter += 1

**Comment by vivekcoder** [comment]
Ideally, these items (with quantity, description) should be nested attributes to some parent model, via a has_many or habtm relationship. And hence, you would have one submit button to submit the form for the parent (with items as child forms). Its not clean to try to save multiple models by one submit action and then iterate through them in the controller.

**Comment by rafaelfranca** [comment]
Please use StackOverflow for questions/help, where a wider community will be able to help you. We reserve the issues tracker for issues only.

**Comment by josecordova** [comment]
My apologies. I am new to this platform. Please delete this post so that it does not distract from actual Rails issues.
