### ISSUE TITLE
Bootsnap is broken on JRuby, breaking Rails 5.2 apps

### ISSUE THREAD

**Issue by headius** [rails/rails#32641]
### Steps to reproduce

Attempt to do anything on JRuby with a newly-generated Rails 5.2 app.

### Expected behavior

It should work.

### Actual behavior

Because of Shopify/bootsnap#162, none of JRuby's internal extensions can load. This usually manifests as a failure to find the CGI::Escape constant, since the load of that extension quietly fails inside cgi.rb.

Removing bootsnap from Gemfile and config/boot.rb allows Rails to start up correctly.

### System configuration

Rails 5.2.0.

JRuby any version, they all have internal exts that bootsnap will prevent from loading.

**Comment by headius** [comment]
It seems like bootsnap got a -java gem but was not really tested, since it breaks JRuby pretty severely. Until that's fixed, it probably should be omitted when generating an app for JRuby.

**Comment by guilleiguaran** [comment]
Closed with https://github.com/rails/rails/commit/b10f371366a606310cab26648d798836e030bdc8
