### ISSUE TITLE
The :only option for Hash#as_json is unexpectedly applied to nested hashes

### ISSUE THREAD

**Issue by trliner** [rails/rails#32658]
### Steps to reproduce
The unexpected behavior of `active_support`'s `Hash#as_json` can be reproduced via this [executable test](https://gist.github.com/trliner/8e10e326095437618a6dce132299d0ce):

```ruby
class BugTest < Minitest::Test
  def test_nested_hash_json_key_filtering
    nested_hash = { hash: { key: 'value' }, array: [{ key: 'value' }] }
    assert_equal nested_hash.as_json(only: [:hash]), { hash: { key: 'value' } }
    assert_equal nested_hash.as_json(only: [:array]), { array: [{ key: 'value' }] }
  end
end
```

### Expected behavior
When creating a subset of a hash using the [`:only` option for `as_json`](https://github.com/rails/rails/blob/b8cd9302fe01dcaf4d36cc28cdfb7b9d7db832d8/activesupport/lib/active_support/core_ext/object/json.rb#L161), I expect the filter to be applied to the top-level keys of that hash:

```ruby
pry(main)> { top: { nested: 'value' } }.as_json(only: [:top])
=> {"top"=>{"nested"=>"value"}}
```

### Actual behavior
The filter is also applied to the keys of any nested hashes.

```ruby
pry(main)> { top: { nested: 'value' } }.as_json(only: [:top])
=> {"top"=>{}}
```

### System configuration
**Rails version**:
5.0.6
**Ruby version**:
2.4.4

**Comment by danhuynhdev** [comment]
@trliner I think the API is a bit unintuitive but it's intentional according to this test https://github.com/rails/rails/blob/2b35826389005bdb0af85a4ebb1f0ec213174d13/activesupport/test/json/encoding_test.rb#L201

**Comment by pixeltrix** [comment]
@trliner thanks for opening an issue but as @danhuynhdev points out this is the intended behaviour. If you need to restrict the top level attributes then this is trivial to do using `slice`, e.g.

``` ruby
pry(main)> { top: { nested: 'value' } }.as_json.slice("top")
=> {"top"=>{"nested"=>"value"}}
```

**Comment by trliner** [comment]
@danhuynhdev Thanks for tracking that down. I looked all over for some indication of the intent but didn't see that test.

@pixeltrix Yep. That's the approach I ended up taking. Thanks!

Closing this issue is the correct resolution. Hopefully, it will be helpful to the next person that encounters this unintuitive behavior.
