### ISSUE TITLE
Rails.application.routes.router.visualizer: invalid option: -Tsvg

### ISSUE THREAD

**Issue by Dorian** [rails/rails#32692]
### Steps to reproduce

- Add `gem 'dot'` to `Gemfile`
- Run `Rails.application.routes.router.visualizer`
- Get:

```
/Users/d/.rvm/gems/ruby-2.5.0/gems/dot-0.1.0/bin/dot:91:in `<top (required)>': invalid option: -Tsvg (OptionParser::InvalidOption)
```

### Expected behavior

Output contains SVG of nodes.

### Actual behavior

SVG nodes are missing:

<img width="1434" alt="screen shot 2018-04-23 at 12 16 47 am" src="https://user-images.githubusercontent.com/129149/39100662-6cba8950-468d-11e8-92d8-6a50d53fc956.png">

### System configuration

**Rails version**: 5.2

**Ruby version**: 2.5

(Seemed to work for somebody :) https://speakerdeck.com/vaidehijoshi/re-graphing-the-mental-model-of-the-rails-router-1 )

**Comment by y-yagi** [comment]
`dot` gem does not matter. 
To use it, you need the `dot` executable included in the graphviz package. 
Also, this method is not part of the public API and we don't recommend users to use it.
