### ISSUE TITLE
[ActiveRecord] assign attributes without changes

### ISSUE THREAD

**Issue by khiav223577** [rails/rails#32697]
After using `update_all` to update a bunch of records in one query, I would like to refresh one model object of them. I avoid using `reload` method, since it doesn't have to load the data from database. I can assign the new attributes by using `assign_attributes` method. But in this way the model object is `changed`. For example:

```rb
User.where('').update_all(column => value)

current_user.assign_attributes(column => value)
current_user.changed?
# => true
```
I find a workaround by calling `clear_attribute_changes` method

```rb
current_user.assign_attributes(column => value)
current_user.send(:clear_attribute_changes, column)
current_user.changed?
# => false
```
It's ugly, I think it will be cleaner if we have a `assign_attributes_without_changes` method.
```rb
current_user.assign_attributes_without_changes(column => value)
current_user.changed?
# => false
```

### System configuration
**Rails version**:
4.2.9

**Ruby version**:
2.3.3

**Comment by y-yagi** [comment]
Please use the [Rails Core mailing list](https://groups.google.com/forum/#!forum/rubyonrails-core) for feature requests, where a wider community will be able to help you. We reserve the Rails issue tracker only for bugs in Rails. Thanks.

**Comment by khiav223577** [comment]
Thanks. I just can't find where to post feature requests.
