### ISSUE TITLE
will_save_change_to_attribute? is not an alias of attribute_changed?

### ISSUE THREAD

**Issue by trezona-lecomte** [rails/rails#32694]
The documentation for the `will_save_change_to_attribute?` method says simply "Alias for attribute_changed?". This is provably false, either by looking at the source code of the method definition (it is not an alias but rather has it's own implementation) or by running the steps to reproduce below.

This is dangerously misleading, because `attribute_changed?` is being deprecated so folks will be looking to replace any usages with an equivalent method. Saying that `will_save_change_to_attribute?` is an alias of `attribute_changed?` leads folks down a path of confusion and subtle bugs.

Note that this applies not just to `will_save_change_to_attribute?`, but also for the other methods introduced in 16ae3db5a5c6a08383b974ae6c96faac5b4a3c81 that purport to be aliases of the old AR::Dirty methods.

### Steps to reproduce

```ruby
# frozen_string_literal: true

begin
  require "bundler/inline"
rescue LoadError => e
  $stderr.puts "Bundler version 1.10 or later is required. Please update your Bundler"
  raise e
end

gemfile(true) do
  source "https://rubygems.org"

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  gem "rails", github: "rails/rails", branch: '5-1-stable'
  gem "sqlite3"
  gem 'byebug'
end

require "active_record"
require "minitest/autorun"
require "logger"

# This connection will do for database-independent bug reports.
ActiveRecord::Base.establish_connection(adapter: "sqlite3", database: ":memory:")
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :posts, force: true do |t|
    t.integer :foo
  end
end

class Post < ActiveRecord::Base
  before_validation :before_validation_method

  after_save :after_save_method

  def before_validation_method
    unless !!will_save_change_to_attribute?(:foo) == !!attribute_changed?(:foo)
      raise "will_save_change_to_attribute? is not an alias of attribute_changed?"
    end
  end

  def after_save_method
    validate!
  end
end

class BugTest < Minitest::Test
  def test_that_no_exception_is_thrown
    Post.create!(:foo => 0)
  end
end
```

### Expected behavior
In the steps to reproduce above, no exception should be thrown because `will_save_change_to_attribute?` should always return the same value as `attribute_changed?`.

### Actual behavior
An exception is thrown, because `will_save_change_to_attribute?` is not an alias of `attribute_changed?` and has different behaviour.

In this case, the exception is thrown on the second call to `before_validation_method`, which occurs during the call to `after_save_method`.

It seems reasonably clear that this behaviour was not the intent of the author, as the commit message of 16ae3db5a5c6a08383b974ae6c96faac5b4a3c81 states: "The first set maintains the old behavior", which we can see is not true in all cases.

### System configuration
**Rails version**:
5.1.6 (branch: `5-1-stable`)

**Ruby version**:
2.3.5

### Further Info
It is worth noting that I understand the intent behind the new `will_save_change_to_attribute?` and `saved_change_to_attribute?` methods, and think that this change is a good idea in principle. My concern is twofold:

1. The docs in their current form are incorrect and will mislead people
2. There is no way for us to replace our current usage of `attribute_changed?` in a way that doesn't change existing behaviour

The second point is more complicated, and we may just have to 'deal with it', depending on the outcome of this issue. I see two possible fixes:

1. Update the docs to correctly describe the behaviour of `will_save_change_to_attribute?` and friends
2. Update `will_save_change_to_attribute?` and friends so that they actually are aliases of the old methods

Thanks for your time & help!

**Comment by rafaelfranca** [comment]
Can you submit a PR updating the documentation?

**Comment by trezona-lecomte** [comment]
Hi @rafaelfranca, thanks for the prompt reply.

Sure, I will put together a PR suggesting some changes to the documentation.

Do you think it's worth examining whether the correct course of action might be to update the code to reflect the original author's intent and the intent of the existing docs? It seems to me that a more friendly upgrade path is one that provides equivalent methods for the old AR:Dirty methods. Is there a reason we can't do this?

Thanks.

**Comment by rafaelfranca** [comment]
The current implementation is what we want.

In `after_#{save/create/update}` callbacks `attribute_changed?` and `will_save_change_to_attribute?` return different things in Rails 5.1 to keep the behavior backwards compatible. The former returns all the attribute that will be sent to the database and the ones that already have being sent to the database. This is what is deprecated, you have to either decide if you want the attribute that were already sent to the database (`saved_change_to_attribute?`) or if you want the attributes that were not sent to the database yet (`will_save_change_to_attribute?`). The behavior where both sets are taken in consideration is deprecated and will be removed.

In Rails 5.2 `attribute_changed?` will match the behavior of `will_save_change_to_attribute?` in `after_` callbacks.

**Comment by trezona-lecomte** [comment]
Thanks for the additional explanation, that makes sense. I hadn't realised that `attribute_changed?` is going to change in 5.2. 

Based on your explanation, am I correct in thinking that in 5.1 `will_save_change_to_attribute?(:foo) || saved_change_to_attribute?(:foo)` should return the same result as `attribute_changed?(:foo)` in all scenarios?

**Comment by rafaelfranca** [comment]
yes, that seems to be correct.

**Comment by trezona-lecomte** [comment]
Hi @rafaelfranca,

During the course of trying to fix this documentation (and upgrade our codebase to 5.1), I've encountered a case in which the neither of the new methods give us the same behaviour as the old method:

```ruby
> attribute_was(:closed_at)
nil
> attribute_in_database(:closed_at)
2018-04-30 13:17:23 +1200
> attribute_before_last_save(:closed_at)
2018-04-30 13:17:23 +1200
```

Before I spend time raising an issue for this, can you please clarify if this is an intended loss of behaviour? 

I.e. my understanding is that if we're in the context of an `after` callback then `attribute_before_last_save(:closed_at)` should always give the same answer as `attribute_was(:closed_at)`, while in the context of a `before` validation `attribute_in_database(:closed_at)` should always give the same answer as `attribute_was(:closed_at)`. If this understanding is correct, then I will write up another issue as this is not the behaviour we're seeing.

**Comment by rafaelfranca** [comment]
Yes, that is the expected behavior

**Comment by trezona-lecomte** [comment]
Hi @rafaelfranca, the PR to fix the documentation has been merged, so as far as I'm concerned this issue is resolved. Closing the issue now (I hope that this is the correct process).

Thanks for your time and assistance throughout this issue, I appreciate it. Keep up the great work.
