### ISSUE TITLE
[ActiveRecord] Same queries origin with verbose_query_logs enabled

### ISSUE THREAD

**Issue by kevynlebouille** [rails/rails#32719]
### Steps to reproduce

Fresh rails new app with active storage enabled and used for an avatar in a User model.

### Expected behavior

Every queries from active storage should be logged with their own engine's path origin.

### Actual behavior

Every queries from active storage are logged with the same origin :
[....]/lib/active_record/log_subscriber.rb:98

Same problem with Devise engine's queries

### System configuration
**Rails version**: 5.2.0

**Ruby version**: 2.5.1 (rbenv)

@olivierlacan

**Comment by williamromero** [comment]
Someone have any information about this problem? I got it first time after i delete my DB. I don't know what is happening here.

**Comment by olivierlacan** [comment]
@kevynlebouille Can you give me more info about the context in which your app is running? Docker? rbenv/RVM/chruby? Do you mind sharing your Gemfile or a sample application with a similar Gemfile that reproduces this issue?
