### ISSUE TITLE
ActiveStorage: Attaching images via the API. I get the base64 code, but then I can't get  image.

### ISSUE THREAD

**Issue by vadus1** [rails/rails#32711]
### Steps to reproduce
Setup ActiveStorage with Google Cloud Storage service:

```
class Image < ApplicationRecord
  has_one_attached :image
end
```
(Guidelines for creating a bug report are [available
here](http://edgeguides.rubyonrails.org/contributing_to_ruby_on_rails.html#creating-a-bug-report))

### Expected behavior
```
tempfile = Tempfile.new("fileupload")
tempfile.binmode
tempfile.write(Base64.decode64("base64 code"))
tempfile.rewind()

mime_type = Mime::Type.lookup_by_extension(File.extname('filename.jpg')[1..-1]).to_s
uploaded_file = ActionDispatch::Http::UploadedFile.new(tempfile: tempfile, filename: 'filename.jpg', type: mime_type) 

params[:image][:image] =  uploaded_file

@image = Image.new(image_params)
@image.save
```

### Actual behavior
The object image is saved but is not displayed as a image.
and after save I get the following error.

```
 pry(#<Api::V1::ImagesController>)>   ActiveStorage::Blob Load (0.6ms)  SELECT  "active_storage_blobs".* FROM "active_storage_blobs" WHERE "active_storage_blobs"."id" = $1 LIMIT $2  [["id", 33], ["LIMIT", 1]]
  ↳ /Users/vadus/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/activerecord-5.2.0/lib/active_record/log_subscriber.rb:98
[ActiveJob] [ActiveStorage::AnalyzeJob] [08955c02-b7e0-46f3-8d91-fab839333551] Performing ActiveStorage::AnalyzeJob (Job ID: 08955c02-b7e0-46f3-8d91-fab839333551) from Async(default) with arguments: #<GlobalID:0x00007febc6d59328 @uri=#<URI::GID gid://photo-booth-admin/ActiveStorage::Blob/33>>
[ActiveJob] [ActiveStorage::AnalyzeJob] [08955c02-b7e0-46f3-8d91-fab839333551] Error performing ActiveStorage::AnalyzeJob (Job ID: 08955c02-b7e0-46f3-8d91-fab839333551) from Async(default) in 18.49ms: MiniMagick::Error (`identify -format %[orientation] /var/folders/6q/klncb19s3k33l8k0r2rg5t100000gn/T/ActiveStorage20180424-1609-lbwl7v.jpg[0]` failed with error:
identify: Not a JPEG file: starts with 0x75 0xab `/var/folders/6q/klncb19s3k33l8k0r2rg5t100000gn/T/ActiveStorage20180424-1609-lbwl7v.jpg' @ error/jpeg.c/JPEGErrorHandler/322.
):
```
### System configuration
**Rails version**: 5.2.0

**Ruby version**: 2.5.0

**Comment by y-yagi** [comment]
> identify: Not a JPEG file: starts with 0x75 0xab `/var/folders/6q/klncb19s3k33l8k0r2rg5t100000gn/T/ActiveStorage20180424-1609-lbwl7v.jpg' @ error/jpeg.c/JPEGErrorHandler/322. 

As per this error, you upload invalid binary data as JPEG.
Therefore, it is an error in conversion processing with MiniMagick. I think this is the correct behavior. 

Please try using the correct image file again.

**Comment by MajedBojan** [comment]
@vadus1 Still your facing same issue or you figured out the issue ?

**Comment by MajedBojan** [comment]
uploading and saving but not able to display

**Comment by williamromero** [comment]
Someone could fixed this error?

**Comment by williamromero** [comment]
Maybe this resource can help you: [How to upload images on Base64 and Blob with Active Storage :: In Spanish](https://www.webres-studio.com/es/blog/16-como-cargar-archivos-blob-y-base64-con-active-storage-y-ajax)

**Comment by williamhatch** [comment]
@williamromero the link is broken?

**Comment by williamromero** [comment]
Now is available my friend... :)

**Comment by williamhatch** [comment]
@williamromero many thanks!

**Comment by santib** [comment]
Maybe this gem could help you https://github.com/rootstrap/active-storage-base64
