### ISSUE TITLE
Regression in preloading :through associations with scope in 5.2.0

### ISSUE THREAD

**Issue by codez** [rails/rails#32722]
### Steps to reproduce

```ruby
class CreateModels < ActiveRecord::Migration[5.2]
  def change
    create_table :person do |t|
      t.string :name
      t.belongs_to :company
    end

    create_table :company do |t|
      t.string :name
    end

    create_table :phone do |t|
      t.belongs_to :company
      t.string :number
    end
  end
end

class Person
  belongs_to :company
  has_many :phones, through: :company
end

class Company
  has_many :phones
end

class Phone
  belongs_to :company
end

company = Company.create(name: 'Walt Disney')
Phone.create(number: '123', company: company)
Person.create([{name: 'Mickey', company: company}, {name: 'Minnie', company: company}])

records = Person.all
ActiveRecord::Associations::Preloader.new.preload(records, :phones, Phone.all)
```

### Expected behavior

```
records.first.phones # => [123]
records.last.phones # => [123]
```

### Actual behavior

```
records.first.phones # => [123]
records.last.phones # => []
```
Without the custom scope `Phone.all` as last argument, the association is populated correctly.

The issue appears because the `phones` association on the `company` is reset here: https://github.com/rails/rails/blob/c81a7fcf76663e6d189792d6eed57b1162199635/activerecord/lib/active_record/associations/preloader/through_association.rb#L30

### System configuration
**Rails version**:  5.2.0
**Ruby version**: 2.2.5

**Comment by y-yagi** [comment]
`ActiveRecord::Associations::Preloader` is not public API. 
If you want to preload, please use `QueryMethods#preload`. 
http://api.rubyonrails.org/classes/ActiveRecord/QueryMethods.html#method-i-preload

```ruby 
records = Person.preload(:phones).to_a

p records.first.phones.pluck(:number) # => ["123"]
p records.last.phones.pluck(:number)  # => ["123"]
```
