### ISSUE TITLE
ignored_columns does not apply to `ActiveRecord::Base#attributes`

### ISSUE THREAD

**Issue by jamesstonehill** [rails/rails#32729]
ActiveRecord's `attributes` method returns a hash with ignored columns in it.

This seems counterintuitive and is really annoying when you are trying to remove a column from a codebase that also uses the column.

#### database
```
foos
| id | some_column | some_ignored_column |
|----|-------------|---------------------|
| 1  | asdf        | qwert               |
```
#### Model
```
class Foo < ApplicationRecord
  self.ignored_columns = ['some_ignored_column']
end
```
### Expected behavior
```
Foo.first.attributes = {
  'id' => 1,
  'some_column' => 'asdf'
}
```

### Actual behavior
```
Foo.first.attributes = {
  'id' => 1,
  'some_column' => 'asdf',
  'some_ignored_column' => 'qwert'
}
```

### System configuration
**Rails version**:
5.1.3
**Ruby version**:
2.4.2

**Comment by kamipo** [comment]
Could you create a reproduction script with this template https://github.com/rails/rails/blob/master/guides/bug_report_templates/active_record_master.rb ?

**Comment by utilum** [comment]
The behaviour is epxected and documented:
> The list of columns names the model should ignore. Ignored columns won't have attribute accessors defined, and won't be referenced in SQL queries. 
[API](The list of columns names the model should ignore. Ignored columns won't have attribute accessors defined, and won't be referenced in SQL queries).

So [a simple reproduction script](https://gist.github.com/utilum/a1800fd431ae8d560d34c255020f95fa) raises `ActiveModel::UnknownAttributeError: unknown attribute 'ignored' for Post.`

Perhaps in this case the record was created before `ignored_columns` was added to the code?

**Comment by rafaelfranca** [comment]
@utilum I think he is reporting that `Foo.first.attributes` returns the ignored column where it should not.

**Comment by utilum** [comment]
And here's a [reproduction script](https://gist.github.com/utilum/bbe3e370e6a9518b17e7c61d81bccd43)

**Comment by utilum** [comment]
I think [this last commit](https://github.com/utilum/rails/commit/1a5b7502e68994c53651d1dda2d74b487eafd882) fixes this.
The reproduction script, when pointed to the commit, passes.
I'd like to make a PR, but not sure how to translate the reproduction script into the maze of AR tests...
Advice welcome.

**Comment by eugeneius** [comment]
I think your reproduction script demonstrates a different problem than the one reported in this issue.

```ruby
class Post < ActiveRecord::Base
end
Post.create!(column: 'value', ignored: 'another value')
class Post < ActiveRecord::Base
  self.ignored_columns = [:ignored]
end
```

Calling `Post.create!` loads the schema, [which is where `ignored_columns` is used](https://github.com/rails/rails/blob/be9a32b65ff5e72f54365e79338516d46063e069/activerecord/lib/active_record/model_schema.rb#L466); by the time it's set later in the script, it has no effect.

`reset_column_information` should probably be called in `ignored_columns=`, [as it is in `table_name=`](https://github.com/rails/rails/blob/be9a32b65ff5e72f54365e79338516d46063e069/activerecord/lib/active_record/model_schema.rb#L194).

**Comment by utilum** [comment]
Thank you @eugeneius . 

Calling `reset_column_information` in `ignored_columns=` is a much better solution as it actually prevents querying for the ignored columns, not just the return from `attributes`.

That said, I'm not sure there is a use case for the problem my script demonstrates.
