### ISSUE TITLE
Wrong character

### ISSUE THREAD

**Issue by jixiaoxin666** [rails/rails#32731]
in this passage
>deep_symbolize_keys! 把指定散列及其中嵌套的散列的键全都转换成符号。例如：
{nil => nil, 1 => 1, "nested" => {"a" => 3, 5 => 5}}.deep_symbolize_keys 
=> {nil=>nil, 1=>1, **nested**:{a:3, 5=>5}}

symbol ':'  was lost before **nested**

it should be
```
{nil => nil, 1 => 1, "nested" => {"a" => 3, 5 => 5}}.deep_symbolize_keys 
=> {nil=>nil, 1=>1, :nested:{a:3, 5=>5}}
```

**Comment by utilum** [comment]
`key: value` is shorthand for `:key => value`. nothing lost.

**Comment by victorhazbun** [comment]
👀
