### ISSUE TITLE
[ActiveStorage] Mirror service configuration raises NotImplementedError with direct uploads

### ISSUE THREAD

**Issue by geetfun** [rails/rails#32732]
### Steps to reproduce

* Configure ActiveStorage to use Mirror Service (Example storage.yml: https://gist.github.com/geetfun/4db3c7601a431f62d0a6ceab182a7538)
* Add has_one_attached or has_many_attached to an existing model
* Create a form to accept attachment with the file_field having the direct_upload as true. Eg: `<%= f.file_field :image, direct_upload: true %>`
* Uploading file will raise error: NotImplementedError

### Expected behavior

Mirror service should not raise NotImplementedError.

### Actual behavior

It appears that the current mirror service implementation is not delegating to the primary service. Specifically, the following 2 methods are calling the parent abstract class:
* :url_for_direct_upload
* :headers_for_direct_upload

### System configuration
**Rails version**: 5.2.0

**Ruby version**: Any

### Test and Fix

A test caase and fix have been implemented here: 

https://github.com/geetfun/rails/commit/8b65a9e850fa7f321265b9c11974b4534e8c2bc4#diff-782e58fba2cc58174b7db41d4b74c219

**Comment by georgeclaghorn** [comment]
Fixed in #36312.
