### ISSUE TITLE
ActionCable logger.add_tags 'ActionCable' did not showing in the log

### ISSUE THREAD

**Issue by charleneChen** [rails/rails#32739]
```
def connect
      self.uuid = find_verified_user
      logger.add_tags 'ActionCable', uuid
end
```

I added `logger.add_tags 'ActionCable', uuid`  in ActionCable Connection

And restart app, the new tag `'ActionCable', uuid` not showing

Anything I did wrong?

**Comment by y-yagi** [comment]
Please use the [mailing list](https://groups.google.com/forum/#!forum/rubyonrails-talk) or StackOverflow for questions/help, where a wider community will be able to help you. We reserve the issues tracker for issues only. Thanks!
