### ISSUE TITLE
Arel::SelectManager#distinct_on ActiveRecord implementation

### ISSUE THREAD

**Issue by bradherman** [rails/rails#32734]
### Expected behavior
`ActiveRecord::QueryMethods` implements a [`#distinct`](https://github.com/rails/rails/blob/master/activerecord/lib/active_record/relation/query_methods.rb#L809-L827) method that accepts a truthy value. The implementation just leverages the [`Arel::SelectManager#distinct`](https://github.com/rails/rails/blob/master/activerecord/lib/arel/select_manager.rb#L149-L156) method.  I would expect since `Arel` has a [`#distinct_on`](https://github.com/rails/rails/blob/master/activerecord/lib/arel/select_manager.rb#L158-L165) method as well that `ActiveRecord` would also support that within the query methods, but it doesn't.

### Actual behavior
`ActiveRecord::QueryMethods` supports the `Arel::SelectManager#distinct` method, but not `Arel::SelectManager#distinct_on`

### System configuration
**Rails version**: 5.2
**Ruby version**: Any

**Comment by y-yagi** [comment]
Please use the [Rails Core mailing list](https://groups.google.com/forum/#!forum/rubyonrails-core) for feature requests, where a wider community will be able to help you. We reserve the Rails issue tracker only for bugs in Rails. Thanks.
