### ISSUE TITLE
Helpers.to_form_params can't handle multi leveled nested hash

### ISSUE THREAD

**Issue by andrewyoo** [rails/rails#32730]
### Steps to reproduce
````
irb(main):145:0> h = { a: { b: 1 }, c: 2 }
=> {:a=>{:b=>1}, :c=>2}
irb(main):146:0> helper.send :to_form_params, h
ArgumentError: comparison of String with :c failed
	from (irb):146
````

### Expected behavior
If 'c' is a string, then the sorting of names [here](https://github.com/rails/rails/blob/870dde4710f1492c83233620f343ec414a07a950/actionview/lib/action_view/helpers/url_helper.rb#L646) works.

````
h = { a: { b: 1 }, 'c' => 2 }
=> {:a=>{:b=>1}, "c"=>2}
irb(main):150:0> helper.send :to_form_params, h
=> [{:name=>"a[b]", :value=>"1"}, {:name=>"c", :value=>"2"}]
````

### Actual behavior
When a hash with symbolized keys has multiple levels of depth and sent to `to_form_params`, which transforms the hash into an array of hashes, it converts some values to strings and other may stay as symbols and then symbols and strings are attempted to be sorted.

The recursive method `to_form_params` [sometimes applies a namespace to a `name` attribute and converts to a `string`.](https://github.com/rails/rails/blob/870dde4710f1492c83233620f343ec414a07a950/actionview/lib/action_view/helpers/url_helper.rb#L634)  When no namespace is provided, it just sets the name which retains the object type of symbol in the error case.

### System configuration
**Rails version**:
`Rails 5.1.6`

**Ruby version**:
`ruby 2.4.2p198`

### My suggestion?
Since this method is a helper for setting form names and values, I think all names should be converted to strings since that's what the final html is expecting.

https://github.com/rails/rails/blob/6b7a93d963d80686e9334faa80460bfde9099032/actionview/lib/action_view/helpers/url_helper.rb#L669
````ruby
# just add to_s here
params << { name: namespace.to_s, value: attribute.to_param }
````

### New Unit Test
````
def test_to_form_params_with_multi_leveled_nested_hash_with_symbolized_keys
  assert_equal(
    [{:name=>"country[name]", :value=>"Denmark"}, {:name=>"nationality", :value=>"Danish"}],
    to_form_params(country: { name: "Denmark" }, nationality: "Danish")
  )
 end
````
Other tests would need to be updated.

**Comment by eugeneius** [comment]
https://github.com/rails/rails/pull/31320 contains a fix for this problem.

**Comment by andrewyoo** [comment]
@eugeneius I should have also searched in PRs as well.  Well i'll just close this now I guess.
