### ISSUE TITLE
path helpers fails with modules on models

### ISSUE THREAD

**Issue by israelias94** [rails/rails#32749]
### Steps to reproduce
app/models/
``` ruby
class Foo::Bar; end
class Foo::Baz; end
```
config/routes.rb
``` ruby
  namespace :foo do
    resources :bar do
      resources :baz
    end
  end
``` 
### Actual behavior
and then link_to helpers doesn't work

![image](https://user-images.githubusercontent.com/16140960/39401123-19eff326-4b0c-11e8-9906-63a388f6f63f.png)

### System configuration
**Rails version**:
5.2.0
**Ruby version**:
2.5.0

**Comment by israelias94** [comment]
Actually i solved this by 
``` ruby
= link_to foo_bar_baz(@bar, @baz)
``` 
or something like this.

But ruby and RoR are magics. that helper should take an array [@bar, @baz], common modules and dont concatenate twice the name of module. 

Or... Im losing of something? What do you think?

**Comment by y-yagi** [comment]
This is intentional behavior. 
If do a special behavior by module, it may be unintended behaviors for the user.  

If you want to do special mapping by model, please use `resolve`. 
http://api.rubyonrails.org/classes/ActionDispatch/Routing/Mapper/CustomUrls.html#method-i-resolve
