### ISSUE TITLE
Uncaught exception in ActionCable.Connection

### ISSUE THREAD

**Issue by Mati365** [rails/rails#32743]
When browser tries to connect to previously killed server it raises exception. Maybe it will be better to handle it using disconnect method?

https://github.com/rails/rails/blob/19c80718afea8cf8f56ee68fcfbe325d54c02906/actioncable/app/assets/javascripts/action_cable/connection.coffee#L30

**Comment by Mati365** [comment]
@palkan I want to listen disconnect event but I dont see if ActionCable.WebSocket or Connection class contains disconnect callback to handle it. When browser tries to connect ActionCable.Websocket is throwing unconnected error in console, where can I handle it?

**Comment by palkan** [comment]
> When browser tries to connect ActionCable.Websocket is throwing unconnected error in console, where can I handle it?

There is no specific API for that.
You can try to wrap you Consumer initiation into a `try ... catch ...` block:

```js
try {
  App.cable = ActionCable.createConsumer("ws://example.com");
} catch (e) {
  // handle exception
}
```

But that would work only for the initial connection attempt.

After successful consumer initiation you can do the following:

```js
# `connection` is a wrapper over WebSocket,
# `events` is an object containing events handlers
App.cable.connection.events.error = function(e) { console.log("My error handler:", e) }
```

NOTE: the above API is not public and might change in the future releases.

**Comment by Mati365** [comment]
Do you plan adding that callback in feature?

**Comment by javan** [comment]
> When browser tries to connect to previously killed server it raises exception.

Can you clarify what previously killed server means? Does this happen when restarting your server? What exception is raised?

The line you linked to doesn't show the full context. A connection isn't *supposed* to open if there's already an open connection: https://github.com/rails/rails/blob/276fe661098619239ac90c110b06d72b3fc77b5c/actioncable/app/assets/javascripts/action_cable/connection.coffee#L23-L30

You can run `ActionCable.startDebugging()` in your application or a JavaScript console to turn on more verbose console logging.
