### ISSUE TITLE
ActiveRecord::Associations::CollectionProxy#replace inconsistent behaviour

### ISSUE THREAD

**Issue by fbatista** [rails/rails#32741]
### Steps to reproduce

On both a `has_many association` and a `has_many_through association`, call the `.replace()` method.

### Expected behavior

They should both behave the same way, as described on the rails documentation, and `delete` the records that are not part of the array passed as parameter.

### Actual behavior

`has_many` association ends up nullifying the records.
`has_many_through` deletes the records on the join model / table

Also check the following:
https://github.com/rails/rails/blob/46b46e85c72f78e869a1b0038040849911c7e2c5/activerecord/lib/active_record/associations/has_many_association.rb#L91-L97
https://github.com/rails/rails/blob/46b46e85c72f78e869a1b0038040849911c7e2c5/activerecord/lib/active_record/associations/has_many_through_association.rb#L131-L164

Notice how the fallback behaviour, when there is no `dependent: ` option is different on each case.

### System configuration
**Rails version**:
5.1.4

**Ruby version**:
ruby 2.4.1p111

**Comment by ChrisCoffey** [comment]
This issue still exists in Rails 5.2.3, and can be replicated by the script above.

**Comment by snuggs** [comment]
Having to `delete_all` then set collection. Wondering if this issue is still relevant.
