### ISSUE TITLE
ActionMailer::LogSubscriber logs `Sent Mail` when perform_delivers = false

### ISSUE THREAD

**Issue by marcshaw** [rails/rails#32754]
### Steps to reproduce
1. Set the action mailer perform deliveries configuration to false
`config.action_mailer.perform_deliveries = false`

2. Send an email through action mailer.

### Actual behaviour
When the configuration is set `perform_deliveries = false` and we send a email.  The following is logged.

```
[ActiveJob] [ActionMailer::DeliveryJob] [248fce59-6508-4fa8-91a4-8f9d4d26e8eb] 
Sent mail to test@email.com (6.8ms)
[ActiveJob] [ActionMailer::DeliveryJob] [248fce59-6508-4fa8-91a4-8f9d4d26e8eb] Date: Sun, 15 Apr 2018 18:42:51 +1200
From: example@example.com
Reply-To: noreply@example.com
To: test@email.com
Message-ID: <5ad2f46be9b27_184d93fcc59009050328c8@local>
Subject: Reset password instructions
.....
```

Logging `Sent mail...` could be potentially misleading when we aren't performing the delivery, but logging that we sent it.

This is logged from log subscriber.
https://github.com/rails/rails/blob/master/actionmailer/lib/action_mailer/log_subscriber.rb 

### Expected behaviour

I am interested to know if the actual behaviour is what we would expect. 

### System configuration
**Rails version**:
4.2.1/5.0

**Ruby version**:
2.3.7

**Comment by rafaelfranca** [comment]
Yes, this is the expected behavior. The perform_deliveries controls the delivery to the mail server, but  the action of delivering the mail message is still performed and logged so people can for example see what is going to be delivered in production in an environment that have `perform_deliveries` set as `false`.
