### ISSUE TITLE
useless SELECT all relations in db locks ...

### ISSUE THREAD

**Issue by JokerCatz** [rails/rails#32762]
just demo code , use scaffold to build belongs_to models

    rails new testme
    cd testme
    rails g scaffold User status:integer
    rails g scaffold Post status:integer user:belongs_to
    rake db:migrate
    rails c
    # at console
    u = User.create
    p = Post.create(user:u)
    p.with_lock{p.status ||= 0 ; p.status += 1 ; p.save}
    p = Post.last.lock!
    p.status += 1
    p.save!

the SQL will be like (same happen in SQLite & MySQL ...)

    begin transaction
      SELECT  "posts".* FROM "posts" WHERE "posts"."id" = ? LIMIT ?   [["id", 1], ["LIMIT", 1]]
      SELECT  "users".* FROM "users" WHERE "users"."id" = ? LIMIT ?  [["id", 1], ["LIMIT", 1]]
      UPDATE "posts" SET "status" = ?, "updated_at" = ? WHERE "posts"."id" = ?  [["status", 1], ["updated_at", "2018-04-30 09:54:25.291122"], ["id", 1]]
    commit transaction

I think the relations select (`SELECT users`) is useless ... and this will be a huge performance issue when a model use lock & the model has many relations?

### System configuration
Rails 4.x , Rails 5.x

**Comment by y-yagi** [comment]
This is behavior not related to lock. 
When saving a record using associaton, a check is made as to whether the association exists. 

```
p = Post.first; p.status += 1; p.save
  Post Load (0.2ms)  SELECT  "posts".* FROM "posts" ORDER BY "posts"."id" ASC LIMIT ?  [["LIMIT", 1]]
   (0.1ms)  begin transaction
  User Load (0.1ms)  SELECT  "users".* FROM "users" WHERE "users"."id" = ? LIMIT ?  [["id", 1], ["LIMIT", 1]]
  Post Update (0.8ms)  UPDATE "posts" SET "status" = ?, "updated_at" = ? WHERE "posts"."id" = ?  [["status", 11], ["updated_at", "2018-05-01 23:50:53.607509"], ["id", 1]]
   (77.9ms)  commit transaction
```

This is intentional behavior.
