### ISSUE TITLE
Problems with subsequent request after #32673

### ISSUE THREAD

**Issue by mmoll** [rails/rails#32767]
Given this test:
```ruby
  test "should assign operating system" do
    put :update, params: { :id => @ptable.to_param, :ptable => { :operatingsystem_ids => [operatingsystems(:redhat).to_param] } }
    assert_response :success
    get :show, params: { :id => @ptable.to_param }
    show_response = ActiveSupport::JSON.decode(@response.body)
    assert_equal operatingsystems(:redhat).id, show_response["operatingsystems"].first["id"]
  end
```
After #32673 was backported to 5-2-stable I'm getting
```
Api::V2::PtablesControllerTest#test_0019_should assign operating system:
ActionDispatch::Http::Parameters::ParseError: no implicit conversion of nil into String
    test/controllers/api/v2/ptables_controller_test.rb:187:in `block in <class:PtablesControllerTest>'
```
When I comment out the PUT, the GET succeeds (the asserts after it fail then, of course) and I'm not 100% sure what's happening here, but could it be that the change is clearing a bit too much?

**Comment by y-yagi** [comment]
Could you create a reproduction script with this [template](https://github.com/rails/rails/blob/master/guides/bug_report_templates/action_controller_master.rb)?

**Comment by eugeneius** [comment]
I believe https://github.com/rails/rails/pull/32773 resolves this issue. @mmoll, would you mind testing the patch?
