### ISSUE TITLE
NameError: uninitialized constant DidYouMean::SpellChecker if ruby 2.6.0dev is chosen by rbenv global system

### ISSUE THREAD

**Issue by yahonda** [rails/rails#32779]
### Steps to reproduce

`NameError: uninitialized constant DidYouMean::SpellChecker` reported 7 times at https://travis-ci.org/rails/rails/jobs/373320011

There was a pull request #32752 but it has been closed since it did not reproduce locally.
I think I have found how to reproduce and how not to reproduce this error.

```ruby
$ git clone https://github.com/ruby/ruby.git
$ cd ruby
$ sudo make clean ; autoconf ; ./configure ; make ; sudo make install
$ rbenv global system
$ sudo gem install bundler
$ cd /path/to/rails/railties
$ bundle install
$ bundle exec ruby -w -Itest test/command/spellchecker_test.rb
```

### Expected behavior
It should pass.

### Actual behavior
```ruby
$ rbenv global system
$ rbenv version
system (set by /home/yahonda/.rbenv/version)
$ ruby -v
ruby 2.6.0dev (2018-05-01 trunk 63314) [x86_64-linux]
$ bundle exec ruby -w -Itest test/command/spellchecker_test.rb
Run options: --seed 37507

# Running:

E

Error:
Rails::Command::SpellcheckerTest#test_suggests_a_word_correction_from_dictionary:
NameError: uninitialized constant DidYouMean::SpellChecker
    test/command/spellchecker_test.rb:8:in `block in <class:SpellcheckerTest>'


bin/rails test test/command/spellchecker_test.rb:7



Finished in 0.001387s, 720.7446 runs/s, 0.0000 assertions/s.
1 runs, 0 assertions, 0 failures, 1 errors, 0 skips
$
```

### Here are steps NOT to reproduce this error by using 2.6.0-dev

```ruby
$ rbenv global 2.6.0-dev
$ rbenv version
2.6.0-dev (set by /home/yahonda/.rbenv/version)
$ ruby -v
ruby 2.6.0dev (2018-05-01 trunk 63314) [x86_64-linux]
$ bundle exec ruby -w -Itest test/command/spellchecker_test.rb
Run options: --seed 27357

# Running:

.

Finished in 0.002871s, 348.2873 runs/s, 348.2873 assertions/s.
1 runs, 1 assertions, 0 failures, 0 errors, 0 skips
$
```

### System configuration
**Rails version**:master branch

**Ruby version**:ruby 2.6.0dev (2018-05-01 trunk 63314) [x86_64-linux]

**Comment by yahonda** [comment]
cc @utilum @y-yagi @kamipo who joined discussion at #32752

**Comment by utilum** [comment]
Thank you @yahonda , I fail to reproduce with your precise and detailed steps, test passes both with the manually compiled and installed system ruby, and with today's fresh 2.6.0-dev courtesy of rbenv.

Here's how I _could_ reproduce the error with both these versions of ruby: 

```
$  gem uninstall did_you_mean
Successfully uninstalled did_you_mean-1.2.1
$ bundle exec ruby -w -Itest test/command/spellchecker_test.rb
Run options: --seed 32848

# Running:

E

Error:
Rails::Command::SpellcheckerTest#test_suggests_a_word_correction_from_dictionary:
NameError: uninitialized constant DidYouMean::SpellChecker
    test/command/spellchecker_test.rb:8:in `block in <class:SpellcheckerTest>'

bin/rails test test/command/spellchecker_test.rb:7

Finished in 0.001970s, 507.7085 runs/s, 0.0000 assertions/s.
1 runs, 0 assertions, 0 failures, 1 errors, 0 skips
```

The reason I closed the PR is that I fail to reproduce behavior on the CI, where results have differed from what I saw locally.

**Comment by gsamokovarov** [comment]
I didn't require the lib, because the CI was green. I'll test it with `2.6.0-dev` and send a fix.

**Comment by utilum** [comment]
I'm trying to fix again, with a fallback to missing `did_you_mean`
