### ISSUE TITLE
ActiveRecord::Type::Boolean.new.cast doesn't cast capitalized values

### ISSUE THREAD

**Issue by phspies** [rails/rails#32786]
### Expected behavior
ActiveRecord::Type::Boolean.new.cast("False") produces true

### Actual behavior
ActiveRecord::Type::Boolean.new.cast("False") should produce false

### System configuration
Rails 5.2.0

**Comment by rafaelfranca** [comment]
It doesn't handle capitalized values. Only the values documented here http://api.rubyonrails.org/classes/ActiveModel/Type/Boolean.html
