### ISSUE TITLE
Folder with active storage

### ISSUE THREAD

**Issue by kaluznyo** [rails/rails#32790]
I try to use ActiveStorage to store my images. With paperclip, in S3 bucket we can have product/id_image/*.png. But with ActiveStorage, all is at the root and in the variants folder.

Any pan to hierarchy this with folder, at least one folder by model ? Because brows in FTP with several images is very slow.

**Comment by georgeclaghorn** [comment]
No, sorry.

**Comment by AbhiOnlyOne** [comment]
We hope this feature will be added to ActiveStorage. That would be helpful.

**Comment by ybakos** [comment]
@georgeclaghorn Thanks for all things Rails (OMG I am actually in Philly right now!). Would you mind putting a quick explanation of why "no?" If you do, I am happy to add a few sentences to the ActiveStorage Overview Rails Guide.

At this point, using ActiveStorage means using one bucket per app, rather than being able to use one bucket for a bunch of different Rails apps, with each using their own folder within the bucket.

**Comment by olivierpichon** [comment]
We very much agree with what @ybakos said.

We also totally understand this feature was not selected as a required one for a first version of Active Storage as it must have been a lot of work already! But we kindly do not understand why there would be no plans nor discussion to support this in the future?

As people pointed out, having everything at the root could make browsing files hard. Also, in our case, we are doing a lot of micro-sites for clients (3 sites a fortnight). The corresponding assets need separation. We cannot use buckets to segregate the assets as there is a max of 100 buckets per AWS account. Also, this would mean contacting the infrastructure team every time we want to create a new micro-site. In other words, it would simply not scale for us.

**Comment by rajeshkp** [comment]
Just want to reiterate it would be really helpful to maintain the structure post migration as mentioned in the original description. It would definitely be helpful if the library allows you to segregate data into a separate folder under a bucket and not dump everything under a single bucket.

**Comment by vtm9** [comment]
@georgeclaghorn

**Comment by doberg** [comment]
https://aws.amazon.com/blogs/security/writing-iam-policies-grant-access-to-user-specific-folders-in-an-amazon-s3-bucket/

**Comment by olivierpichon** [comment]
Hey @doberg,

Thank you for your message!

I know how to grant access in AWS, what I don't really get from your message is:

> Can do currently with IAMs and active storage:
S3-BUCKET-ONE/APP_ONE/stage/
S3-BUCKET-ONE/APP_ONE/production/
S3-BUCKET-ONE/APP_TWO/stage/
S3-BUCKET-ONE/APP_TWO/production/

How can you achieve this with ActiveStorage at the moment with a setting which looks like this:

```
amazon:
  service: S3
  access_key_id: ""
  secret_access_key: ""
  region: ""
  bucket: ""
```

It does not look to me that you can setup a system wide folder for an application as the only thing an application takes as a parameter is a `bucket` name. But maybe there's something I am missing?

If it is the case then that's a shame. We did all our homework migrating to Rails 5.2 as we were really excited to use this new feature.

We are grateful many devs like @georgeclaghorn invest time and effort on building Software for everyone to use. We don't really understand on this one instance why [Direct Uploads](http://edgeguides.rubyonrails.org/active_storage_overview.html#direct-uploads) was more a priority than setting up some folders as folders usually comes quickly to people's mind when dealing with File Storage.

As it also does not look like a conversation can take place around this, we had to move to a non-deprecated solution and started using [CarrierWave](https://github.com/carrierwaveuploader/carrierwave)

**Comment by georgeclaghorn** [comment]
100 buckets is the default limit on S3. You can [request a limit increase from AWS support](https://docs.aws.amazon.com/general/latest/gr/aws_service_limits.html).

**Comment by doberg** [comment]
@olivierpichon

If one desires to use only one bucket for whatever reason.
File grouping[sub-folders] would be done by using XYZ credentials. Their would be no need to specify a grouping[sub-folders] within a bucket.

```yaml
stage:
  amazon:
    service: S3
    access_key_id: "APP_ONE_STAGE_KEY_ID"
    secret_access_key: "APP_ONE_STAGE_ACCESS_KEY"
    region: "us-east-2"
    bucket: "s3-bucket-one"


production:
  amazon:
    service: S3
    access_key_id: "APP_ONE_PRODUCTION_KEY_ID"
    secret_access_key: "APP_ONE_PRODUCTION_ACCESS_KEY"
    region: "us-east-2"
    bucket: "s3-bucket-one"
```

@olivierpichon Thank you for being responsive. Yes you can increase this limit via a support request. However very large companies with lots of projects may run into issues still with these limitations. Support requests can take some time and this may not be feasible or desirable for all situations.

**Comment by georgeclaghorn** [comment]
If you really spin up so many applications that you’re frequently hitting the S3 bucket limit, maybe S3 isn’t right for you. Google Cloud Storage doesn’t have a bucket limit.

**Comment by olivierpichon** [comment]
@doberg have you tried this solution yourself? We don't see how it could work.
Using AWS credentials you could say that a first credential can access one folder and a second credential a second folder (just like your configuration example). But the S3 client (here the application) still needs to tell _where_ it wants to store that file (more precisely which key name it wants to use). How could it do so when this location is never a parameter of your application?

In other words, suppose you created your app with a credential that can access two folders on S3. How could your app know in which of those two folders you would like the files to be put unless your application states it. Same goes with a credential that accesses only one folder: there's no such thing as discovery of the only path a credential can access and then write to that specific path: your application needs to _state where it wants the files to be written_, even if it only has access to one of path.

**Comment by milgner** [comment]
There are also reasons to separate data inside a single application. For example for uploads of invoicing-related data, it is very cumbersome to create separate buckets for the PDFs of invoices, credit notes and other related models. With Carrierwave it is no problem to seperate them into different folders of one "accounting" bucket and also to specify their filename, like adding customer number and invoice number, so that they can be identified by other systems.

**Comment by vtm9** [comment]
@georgeclaghorn, what is the main reason for the rejection of this feature?
You need only specify `prefix` in `has_one_attached, has_many_attached` associations, and change one line in this methods: `object_for(key), path_for(key), file_for(key)`.

**Comment by yigitbacakoglu** [comment]
@georgeclaghorn

**Comment by doberg** [comment]
If you want this to work with sub/sub/sub folders and be able to specify anything you desire in a `:prefix` as of today. 
Just use the `proactivestorage` gem. 

https://github.com/doberg/proactivestorage/tree/master/proactivestorage

**Comment by NdaJunior** [comment]
@georgeclaghorn Is it possible to have ActiveStorage save your images on s3 with a custom name (timestamp) followed by a trailing file_format (i.e jpg etc)?

**Comment by quaertym** [comment]
Can you reopen this?

**Comment by InteNs** [comment]
We can't use ActiveStorage without some form of custom directory structure.

It's unreasonable IMO to simply say "no", close the issue, give no explanation of any kind and offer no alternatives besides "increase your bucket limit" and "use a different file storage"

This is not the communication I expect from anything that is merged into rails core.

**Comment by HDLP9** [comment]
We can't use ActiveStorage for multi-tenant applications without having some control over the directory structure. ActiveStorage is a nogo to us.

**Comment by robcarruthers** [comment]
@doberg Thanks for the direction. I tried to install the `proactivestorage` gem and got this error:

```
Could not find gem 'rails (= 5.2.0)' in https://github.com/doberg/proactivestorage (at master@b6d425b).
The source contains 'rails' at: 6.0.0.alpha
```

**Comment by graywolf** [comment]
Was there ever an explanation for the "no"?

**Comment by whalesalad** [comment]
The irony here is that there are really no such thing as directories in S3 ... the path becomes part of the key in a giant flat directory as "foo/bar/baz.txt => file" ... directory structures are simulated.

I am *extremely* surprised at the pushback on this request. Not so much the lack of eagerness to add the functionality, but rather the hard stance suggesting it's not valuable.

**Comment by mizinsky** [comment]
What do you think about that solution?
1) Create a **Blob** with desired pathname structure and uploaded file. 
2) Pass created **Blob** to attach method _(as **create_from_blob** method accepts a Blob)_
[StackOverflow](https://stackoverflow.com/a/52111217/7026694)

**Comment by georgeclaghorn** [comment]
The OP asked a question—whether we planned to add a feature—and I answered it honestly. We do not plan to add the feature in question. The only major Active Storage features I plan to work on in the foreseeable future are validations and support for public files. We also don’t take feature requests on GitHub, which I could have made more clear. I’m sorry for being so curt.

Please feel free to continue exploring the issue in the [rubyonrails-core](https://groups.google.com/forum/#!forum/rubyonrails-core) mailing list. If you’d find this feature useful, I’d love to chat with you about your needs to hone in on a compelling use case and an appropriate implementation. My email address is george@basecamp.com.

**Comment by hishammalik** [comment]
@georgeclaghorn you mentioned that you'd love to chat about compelling use case and appropriate implementation. I see a number of posts in this thread with compelling enough use case example, so why not share your thoughts on appropriate implementation here so that general public can take advantage of it.

In its current implementation, the ActiveStorage implementation is not even SEO-friendly. In my excitement to use Rails 5.2, I used ActiveStorage which I see is perhaps not even mature enough to be added in to rails core. Not sure how decisions to add such a gem to rails core is made when basic SEO considerations are not being managed. With Rails core, I have become accustomed to best practices, with out of the box best solutions keeping in view security and basic standards (SEO certainly being one of them), and ActiveStorage seems to lack it.

Please do take time to share your thoughts as to what I might be missing or misunderstanding. Thank you for your support.

**Comment by BKSpurgeon** [comment]
Having a feature where you can have different buckets per client would be handy from an invoicing perspective, and might be well worth considering incorporating into this gem:

- if you can have only one bucket, then if one client holds: 1TB of data in that bucket, and accesses it all the time, while another client holds  only 1MB, in the same bucket, then that would be difficult from an invoicing perspective. Google/AWS will invoice me for holding ALL the data in that bucket and accessing it, and I in turn will have to invoice both clients separately - but how can one separate those expenses from an invoicing perspective? One client would be responsible for 99% of the Google/AWS expense, but there would be no way to differentiate and allocate the data usage costs to a particular client. IN other words, this would be a nightmare to scale.

**Comment by bradcrawford** [comment]
Hopefully this may help someone else with this problem

```
# lib/active_storage/service/better_s3_service.rb
require 'aws-sdk-s3'
require 'active_storage/service/s3_service'
require 'active_support/core_ext/numeric/bytes'

module ActiveStorage
  class Service::BetterS3Service < Service::S3Service
    attr_reader :client, :bucket, :root, :upload_options

    def initialize(bucket:, upload: {}, **options)
      @root = options.delete(:root)
      super(bucket: bucket, upload: upload, **options)
    end

    private

    def object_for(key)
      path = root.present? ? File.join(root, key) : key
      bucket.object(path)
    end
  end
end
```

**Comment by yoones** [comment]
https://aws.amazon.com/blogs/aws/amazon-s3-path-deprecation-plan-the-rest-of-the-story/

**Comment by GBH** [comment]
@yoones That's has nothing to do with original ask. Amazon just deprecating bucket names as part of the path. Actual object keys still can be of "/foo/bar/baz.png" structure.

**Comment by nitsujri** [comment]
https://groups.google.com/forum/#!searchin/rubyonrails-core/activestorage$20folders%7Csort:date/rubyonrails-core/VqCAEu3IMvE/8_nu_EDIBgAJ

Per DHH, as of Oct, 2018, there are no roadmap'ed features for ActiveStorage.

**Comment by rlugge** [comment]
> https://aws.amazon.com/blogs/aws/amazon-s3-path-deprecation-plan-the-rest-of-the-story/

In regards to this conversation, the title on that article is misleading.

It's not about deprecating path based S3 *keys*, it's about deprecating path-based S3 *bucket* access.

The examples they give actually cover that:

Old Style: https://s3.amazonaws.com/jbarr-public/images/ritchie_and_thompson_pdp11.jpeg
New Style: https://jbarr-public.s3.amazonaws.com/images/ritchie_and_thompson_pdp11.jpeg

You'll note that the 'path' part of the key -- `/images/` remains intact, they're just moving the bucket identifier from the path and into a subdomain.  Presumably, this is to help with routing and load balancing issues.

**Comment by AndyObtiva** [comment]
Give them the benefit of the doubt. The project or feature will fail organically if their lack of support for commonly asked features falters. Thanks for making ActiveStorage available, but I'm either ditching S3 or ditching ActiveStorage as a result of this. Cross your fingers it's S3. :P

**Comment by NewAlexandria** [comment]
@vtm9 re-awakening this issue.  The [above-linked discussion by DHH](https://groups.google.com/forum/#!searchin/rubyonrails-core/activestorage$20folders%7Csort:date/rubyonrails-core/VqCAEu3IMvE/8_nu_EDIBgAJ) directly invites PRs as a way to discuss the addition. 

I'd like to suggest the post-mortem on this conversation is that the mod missed the social/community context of how many people were involved / cared, here on github, and therefore didn't give enough support to move the conversation to the mailing list.  Had they done that, it would have created a more supportive and welcoming environment

**Comment by sposmen** [comment]
> Just use the `proactivestorage` gem.
> https://github.com/doberg/proactivestorage/tree/master/proactivestorage

Hi @doberg, the complementary gem was a good idea, but now the gem is not too active and overriding Rails is not a good idea (I'm using now Rails 6)
☹️

**Comment by justinperkins** [comment]
I take it there's no progress on this? We're building an app and would like to keep it focused on a single bucket, where each environment operates with its own IAM credentials that isolates it to a particular prefix (`my-activestorage-bucket/dev`, `my-activestorage-bucket/prod`, etc). From an AWS Policy perspective, this is all fine and easy to setup. Now ActiveStorage philosophies are getting in the way of finishing the work. 

We are operating in an environment that is at max capacity buckets, just telling everyone to throw more buckets at the problem is ignoring real world use cases. We have legacy environments we're dealing with here. Not everything is green field.

**Comment by abhionlyone** [comment]
> I take it there's no progress on this? We're building an app and would like to keep it focused on a single bucket, where each environment operates with its own IAM credentials that isolates it to a particular prefix (`my-activestorage-bucket/dev`, `my-activestorage-bucket/prod`, etc). From an AWS Policy perspective, this is all fine and easy to setup. Now ActiveStorage philosophies are getting in the way of finishing the work.
> 
> We are operating in an environment that is at max capacity buckets, just telling everyone to throw more buckets at the problem is ignoring real world use cases. We have legacy environments we're dealing with here. Not everything is green field.

You should probably check [Shrine](https://github.com/shrinerb/shrine). It is well maintained and on the whole, it feels much better than active storage

**Comment by justinperkins** [comment]
Thanks @abhionlyone, ended up created a custom Service based on the comment from @bradcrawford above. I prefer small customizations over adding gems to solve small problems. Struggled with a few things, an hour or so of lost time, but it's operational now. If we continue to bang our heads against the wall with ActiveStorage's opinions, we'll give Shrine a shot. Thanks for the quick followup 👍

**Comment by v2lrf** [comment]
> @georgeclaghorn, what is the main reason for the rejection of this feature?
> You need only specify `prefix` in `has_one_attached, has_many_attached` associations, and change one line in this methods: `object_for(key), path_for(key), file_for(key)`.
> 
> ```ruby
> class User < ApplicationRecord
>   has_one_attached :avatar, prefix: 'avatars'
>   has_many_attached :docs, prefix: 'docs'
> end
> ```
Any chance to have new about that ? 

@vtm9 Hey  is there any chance to have more detail about the line of code that we have to change to make that working ? Or is it longer than "a single line of code "? here one of the method that need to be fixed as you wrote.
https://github.com/rails/rails/blob/cf7c27f2ff2a38f90af29162d11c41628600999b/activestorage/lib/active_storage/service/s3_service.rb#L127
https://github.com/rails/rails/blob/352445b2b6db00d040d3fcb6c742f9b2795a68d1/activestorage/lib/active_storage/service/disk_service.rb#L101

Your pattern is elegant.

I'm rigth now working on a kinda patch to get same objective as @kaluznyo and i'm following up that pattern [here](https://stackoverflow.com/a/50471195/7800866)  It's ok but your proposition is really cool.
Let me Know if you have more detail about your proposition. Why not changing it by our own.

**Comment by v2lrf** [comment]
## digital ocean and active storage create dynamically folder and subfolders

just in case if someone is looking to figure an extra solution or option to do surround that lack of :prefix pattern.

i did that kind of code within a model which have one attachment

this is not elegant yet but this is the start point ...

```inside #room.rb```
```ruby
class Room < ApplicationRecord
  include RoomsUploaderHelper
  # some hidden callback not important for that case
  # some hidden emum not important for that case 
  after_create :driver_helper_method
  after_update :driver_helper_method
  has_one_attached :header_image_project

  def numeric_instant
    # some hidden code not important for that case 
  end

  def set_full_address_attributes
     ## some hidden code not important for that case 
  end

  def driver_helper_method
   
    if self.header_image_project.attached? || self.photos.attached? 
      url = self.header_image_project.blob.service_url
      asset = self.header_image_project.blob
      restructure_attachment(
          url,
          asset, 
          {
            id: asset.id,
            key: asset.key,
            filename: asset.filename,content_type: asset.content_type,
            byte_size: asset.byte_size, 
            checksum: asset.checksum
          },
          "new_folder")
    end
  end
end

``` 

```inside #models/concerns/rooms_uploader_helper.rb```
This starting solution code help me to figure a way to protect my cloud asset setup for a future migration to another provider. We never know ... Today I'm often working with digital ocean, this code is based on this cloud setup.

Objectives : Copy asset A to a specific folder based on my logic structure. I'm not trying to move the asset A from a point to another point but at least now I could organize my droplet well (for sure I need then to pas some other params  to create sub folders linked to this one...). 

Bad point : I have all my asset are at lest duplicate two time . But as I explain this my starting point of work.
```ruby
module RoomsUploaderHelper
  extend ActiveSupport::Concern

  # link t.ly/B0gx
  
  def restructure_attachment(url,fullObject, active_storage_object, new_structure)
    
    old_key = active_storage_object[:key]
    config = YAML.load_file(Rails.root.join('config', 'storage.yml'))
    client = Aws::S3::Client.new(
      access_key_id: ENV['access_key_id'],
      secret_access_key: ENV['secret_access_key'],
      endpoint: ENV['endpoint'],
      region: ENV['region']
    )
    objects = client.list_objects({bucket: "your-bucket-name"})
    array = objects.contents.pluck(:key)
    index = array.index(old_key) 
    old_obj = objects.contents[index]
    
    object = client.put_object({
      bucket: "your-bucket-name",
      key: "#{new_structure}/#{old_key}", # this is the creation of the folder new_folder
      body: open(url),
      acl: "public-read"
    })

     # this is not important for the objective but documentation 
     # is very poor about that subject 
     # so adding an example of download is not too bad 
     # (it will download that asset localy to your machin)
    ddd = client.get_object(
      bucket: 'development-cc',
      key: old_key,
      response_target: '/tmp/local-file.jpg'
    )
  
  end
end
```

If some of you have more elegant solution I would be very inserting to have a look on it.

**Comment by earoberson** [comment]
If you're stuck using 6.0 for now, setting the attachment key appropriately for your use case may work as well:

```
class Company < ActiveRecord::Base
  has_one_attached :logo

  before_create :set_logo_attachment_key

  def set_logo_attachment_key
    self.logo.attachment.key = "some_path/filename.jpg"
  end
end
```

**Comment by birthdaycorp** [comment]
While I agree that the functionality should be added, the 

> Hopefully this may help someone else with this problem
> 
> ```
> # lib/active_storage/service/better_s3_service.rb
> require 'aws-sdk-s3'
> require 'active_storage/service/s3_service'
> require 'active_support/core_ext/numeric/bytes'
> 
> module ActiveStorage
>   class Service::BetterS3Service < Service::S3Service
>     attr_reader :client, :bucket, :root, :upload_options
> 
>     def initialize(bucket:, upload: {}, **options)
>       @root = options.delete(:root)
>       super(bucket: bucket, upload: upload, **options)
>     end
> 
>     private
> 
>     def object_for(key)
>       path = root.present? ? File.join(root, key) : key
>       bucket.object(path)
>     end
>   end
> end
> ```
> 
> Then, in `storage.yml` you can simply add
> 
> ```
> s3:
>   service: BetterS3
>   root: 'directory'
> ```

this fix is super helpful! thank you! unfortunately, my rails app is @ 5.2.4, and i need for each model to go into it's own directory via `has_one_attached :thing, service: :s3`. which, sadly (and _confusingly_ 🙄🙄🙄🙄)is not default behavior until Rails 6+.

Looks like I'm moving over to Shrine😒

**Comment by birthdaycorp** [comment]
> Hopefully this may help someone else with this problem
> 
> ```
> # lib/active_storage/service/better_s3_service.rb
> require 'aws-sdk-s3'
> require 'active_storage/service/s3_service'
> require 'active_support/core_ext/numeric/bytes'
> 
> module ActiveStorage
>   class Service::BetterS3Service < Service::S3Service
>     attr_reader :client, :bucket, :root, :upload_options
> 
>     def initialize(bucket:, upload: {}, **options)
>       @root = options.delete(:root)
>       super(bucket: bucket, upload: upload, **options)
>     end
> 
>     private
> 
>     def object_for(key)
>       path = root.present? ? File.join(root, key) : key
>       bucket.object(path)
>     end
>   end
> end
> ```
> 
> Then, in `storage.yml` you can simply add
> 
> ```
> s3:
>   service: BetterS3
>   root: 'directory'
> ```

While this code helped, I also need the `service` option for `has_one_attached`, which isn't available until after Rails 6.

The feature suggested by OP should be the default, and I cannot understand the initial pushback. I need for certain types of user uploaded content to be in a private S3 bucket (or a directory with a specific IAM policy), but I don't need _everything_ to go there. The way things are now, there is no way to set a granular IAM policy on a single bucket with _only one folder_.

**Comment by hvenables** [comment]
I take it there has been no movements on this? im still confused as to why @georgeclaghorn you are so opposed to this idea?

**Comment by justinperkins** [comment]
I could've sworn I read that Rails core saw the light on this, and added support for prefixing, but maybe it was just a dream.

> The way things are now, there is no way to set a granular IAM policy on a single bucket with only one folder.

@birthdaycorp you should be able to setup a custom policy for a bucket that specifies a prefix like (this is just the relevant snippet from the custom policy): 

```json
"Condition": {
  "StringLike": {
    "s3:prefix": ["my-prefix/", "my-prefix/*"]
  }
}
```

**Comment by emilebosch** [comment]
So far I've seen valid points in this issue to sum the pro's here:

- Better organised folders `/customers/12314/invoices/file.pdf`
- Faster performance when browsing the folder
- Easier to backup and to send a tenant/customer their set of data
- Not reliant on the DB to find the file (also for the love of god if you ever lose your db, you can't relate the files)
- Easier for other external systems to find files

All in all, I think there are a bunch of use cases that seem to be valid here. Now who wants to make a PR with me, I dont think @georgeclaghorn  didn't say it wasn't gonna get merged,  just that _core_ didn't do any changes to it afaik.

**Comment by timwis** [comment]
Great to see this in 6.1.0. ([changelog](https://github.com/rails/rails/blob/6-1-stable/activestorage/CHANGELOG.md)). Has anyone figured out how to set the default folder, so we don't have to specify it with each upload?

**Comment by doberg** [comment]
@timwis obviously you can do it by passing a key to the attachment: 
``` code
user.avatar.attach key: "avatars/#{user.id}.jpg",
  io: io, content_type: "image/jpeg", filename: "avatar.jpg"
  ``` 

idk if that would even be possible in the default settings because you need to associate the key with the model somehow to do lookups, but if you figure that out, you can pass `key:` to the `upload:` options: 
  ``` code
  production:
  service: s3
  access_key_id: <%= Rails.application.credentials.dig(:aws, :access_key_id) %>
  secret_access_key: <%= Rails.application.credentials.dig(:aws, :secret_access_key) %>
  region: us-east-1
  bucket: my-bucket
  upload:
    multipart_threshold: <%= 250.megabytes %>
    key: "avatars/#{model_lookup_method}.jpg"
```

**Comment by Thananjaya** [comment]
@doberg the below expression

`user.avatar.attach key: "avatars/#{user.id}.jpg",
  io: io, content_type: "image/jpeg", filename: "avatar.jpg"` 
  
  is used to attach a file that doesn’t arrive via an HTTP request. Please take a look at this [link](https://edgeguides.rubyonrails.org/active_storage_overview.html#attaching-file-io-objects). Is there any way of attaching the file coming from an HTTP request?

**Comment by stevenou** [comment]
@Thananjaya if you're using Direct Uploads in 6.1.0, I was able to achieve this by:

1. Creating my own `DirectUploadsController` and injecting the `key` argument into the call for `create_before_direct_upload!` e.g. 
```
class DirectUploadsController < ActiveStorage::BaseController
  def create
    blob = ActiveStorage::Blob.create_before_direct_upload!(**blob_args.merge(key: custom_key))
    render json: direct_upload_json(blob)
  end

  private

  def custom_key
    # do some logic here to generate a custom key with a custom path
  end
end
```
2. Add routes for your new controller
3. When creating `file_field`, instead of using `direct_upload: true`, manually put the `direct-upload-url`, e.g.
```
file_field_tag :photo, data: { direct_upload_url: direct_uploads_path(maybe_some_param: 'for determining custom key') }
```

If you're not using Direct Uploads, you can probably do something similar but with `create_and_upload!` instead of `create_before_direct_upload!` as they both take the `key` argument, but I haven't looked into it.

However, I am now running into the issue that variants created from a blob do not appear to respect the "prefixing" of the original blob. While my original blobs are saving with the correct key, my variants all show up in the root path. It's kind of confusing to me because `ActiveStorage::Variant#key` method seems to suggest they should be stored at `"variants/#{blob.key}/#{Digest::SHA256.hexdigest(variation.key)}"`, but that's not the case from what I'm experiencing. Does anyone have any insights into this?

**Comment by koolfreak** [comment]
> @doberg the below expression
> 
> `user.avatar.attach key: "avatars/#{user.id}.jpg", io: io, content_type: "image/jpeg", filename: "avatar.jpg"`
> 
> is used to attach a file that doesn’t arrive via an HTTP request. Please take a look at this [link](https://edgeguides.rubyonrails.org/active_storage_overview.html#attaching-file-io-objects). Is there any way of attaching the file coming from an HTTP request?

Hi @doberg , have solve this issue? i am using dropzone to save to google cloud, but i also having issue saving it into particular folder. The question might be, how to create io from http request? 

i tried this: io: params[:file] well it does not worked.

**Comment by koolfreak** [comment]
@doberg nevermind, i already found the solution:

io: File.open(params[:file])

key: "avatars/#{user.id}.jpg", io: io: File.open(params[:file]), content_type: "image/jpeg", filename: "avatar.jpg"

**Comment by v2lrf** [comment]
> If you're not using Direct Uploads, you can probably do something similar but with `create_and_upload!` instead of `create_before_direct_upload!` as they both take the `key` argument, but I haven't looked into it.
> 
> However, I am now running into the issue that variants created from a blob do not respect the "prefixing" of the original blob. While my original blobs are saving with the correct key, my variants all show up in the root path. It's kind of disappointing to me because `ActiveStorage::Variant` uses a key 'relative' to the original's: `"variants/#{blob.key}/#{Digest::SHA256.hexdigest(variation.key)}"`, but that's not the case for `ActiveStorage::VariantWithRecord`

@stevenou,
Thanks for the pattern proposed.
I agree and confirm that it seems tricky to play with the variant(s). 
How to store variants exactly where we want inside our bucket?
Inside folder and provide a specific key?

For some reasons, you are right, `"variants/#{blob.key}/#{Digest::SHA256.hexdigest(variation.key)}"` this line [activestorage/app/models/active_storage/variant.rb#L69](https://github.com/rails/rails/blob/291a3d2ef29a3842d1156ada7526f4ee60dd2b59/activestorage/app/models/active_storage/variant.rb#L69) do not the job.  
I'm on it.
I would expect to figure out an elegant way to organize all variants generated by active storage and gem image_processing. Actually, for now, all variants are stored on the root of my bucket...

If someone has figured it out yet, let us know  ;-)

**Comment by fwuensche** [comment]
I was using Cloudinary and facing the same issue. 

By exploring their API, I figured they accept a folder param, so I tried to dynamically set it from storage.yml:

```yml
cloudinary:
  service: Cloudinary
  folder: <%= Rails.env %>
```

Now, when I upload a file, it'll automatically create folders based on my Rails env: 

![image](https://user-images.githubusercontent.com/1740848/118395575-6d733000-b64b-11eb-91b7-6d84709828eb.png)

Hope this solution can enlight others too ❤️

**Comment by arianf** [comment]
My solution:

```ruby
# https://github.com/rails/rails/blob/5-2-stable/activestorage/app/models/active_storage/blob.rb
Rails.application.config.to_prepare do
  require 'active_storage/blob'
  ActiveStorage::Blob.class_eval do
    def key
      self[:key] ||= "#{foldering}/#{self.class.generate_unique_secure_token}"
    end

    def foldering
      id = Time.now.to_i
      key = id.to_s.rjust(12, '0')
      key = key.reverse
      key = key.chars.each_slice(4).to_a.map(&:join).join('/')

      key
    end
  end
end
```

**Comment by zzak** [comment]
This thread has seen enough life IMO, and ActiveStorage has changed a lot since 2018 including some of the features requested here. If you have a particular issue with the current version, I encourage you to open a new issue to submit a bug report or open a PR and submit a patch. I think [rubyonrails-talk](https://discuss.rubyonrails.org/) might be the best place for these other discussions.
