### ISSUE TITLE
command not found: rake

### ISSUE THREAD

**Issue by frichardben** [rails/rails#32797]
### Steps to reproduce

(Guidelines for creating a bug report are [available
here](http://edgeguides.rubyonrails.org/contributing_to_ruby_on_rails.html#creating-a-bug-report))

### Expected behavior
Tell us what should happen

Wheel solidus application

### Actual behavior
![rake](https://user-images.githubusercontent.com/24980034/39548809-112ad6b0-4e32-11e8-885a-e27b3459a53e.png)

### System configuration
**Rails version**:
Rails 5.1.6
**Ruby version**:
2.4.4
**S.O**
Win10

**Comment by y-yagi** [comment]
Please use the [mailing list](https://groups.google.com/forum/#!forum/rubyonrails-talk) or StackOverflow for questions/help, where a wider community will be able to help you. We reserve the issues tracker for issues only. Thanks.
