### ISSUE TITLE
[ActiveStorage] Attaching a file to a record in consecutive tests causes MySQL to lose connection

### ISSUE THREAD

**Issue by joshforbes** [rails/rails#32794]
### Steps to reproduce
[https://github.com/joshforbes/activestorage](https://github.com/joshforbes/activestorage) - This minimal rails application reproduces the issue. 
- migrate database
- run the test

### Expected behavior
I should be able to have consecutive tests that deal with attaching a file without MySQL losing connection

### Actual behavior
The tests will intermittently lose connection and `ActiveRecord::StatementInvalid: Mysql2::Error: MySQL client is not connected` will be displayed

### System configuration
**Rails version**:
5.2.0

**Ruby version**:
2.5.1

**MySQL Version**:
MySQL 5.7.22 (homebrew)

**Comment by joshforbes** [comment]
Also I should note using `self.use_transactional_tests = false` makes the problem go away.

**Comment by hegwin** [comment]
Same issue and same environment with you:

* Ruby 2.5.1
* Rails 5.2.0
* Mysql 5.7.22
* Rspec 3.7

When I run `rspec spec`, I will get a randomly-appeared error:

```
  26) User 
      Failure/Error: _query(sql, @query_options.merge(options))
      
      ActiveRecord::StatementInvalid:
        Mysql2::Error: MySQL client is not connected: BEGIN
      # /Users/hegwin/.rvm/gems/ruby-2.5.1/gems/mysql2-0.5.1/lib/mysql2/client.rb:131:in `_query'
      # /Users/hegwin/.rvm/gems/ruby-2.5.1/gems/mysql2-0.5.1/lib/mysql2/client.rb:131:in `block in query'
      # /Users/hegwin/.rvm/gems/ruby-2.5.1/gems/mysql2-0.5.1/lib/mysql2/client.rb:130:in `handle_interrupt'
      # /Users/hegwin/.rvm/gems/ruby-2.5.1/gems/mysql2-0.5.1/lib/mysql2/client.rb:130:in `query'
      # ------------------
      # --- Caused by: ---
      # Mysql2::Error:
      #   MySQL client is not connected
      #   /Users/hegwin/.rvm/gems/ruby-2.5.1/gems/mysql2-0.5.1/lib/mysql2/client.rb:131:in `_query
```

I searched some info and tried to update `reaping_frequency `, `pool`and `reconnect` in database.yml. It seems to have some effects but still does’t fix the issue completely.

Currently, I fixed it by using [database_cleaner](https://github.com/DatabaseCleaner/database_cleaner) and  removing `self.use_transactional_tests = true` from `spec/rails_helper.rb`.

**Comment by joshforbes** [comment]
So it turns out setting:

`config.active_job.queue_adapter = :inline`

will also resolve the issue. Hopefully that helps someone debug this.

**Comment by Haniyya** [comment]
This problem still persists in my configuration. Was able to solve it by inlining the jobs as described above.

Ruby 2.5.3
Rails 5.2.2
Mariadb 10.3

**Comment by juanbrein** [comment]
Same here:
Percona 5.7
Rails 5.2.3
Ruby 2.5.1

**Comment by salzig** [comment]
Same here:
Rails 5.2.3
Ruby 2.6.3p62
Database: 10.3.13-MariaDB

Strange situation having hundreds of tests failing because you start using activestorage and wrote a single test.

**Comment by JohnSmall** [comment]
I have the same problem here:
Rails 5.2.3
Ruby 2.5.5p157
Database: mysql  Ver 8.0.19 for osx10.15 on x86_64 (Homebrew)
mysql adapter: mysql2 (0.5.2)
rspec: 3.9.0

Setting `config.active_job.queue_adapter = :inline` makes no difference.

Hundreds of failing tests  because I started using activestorage and wrote a single test.

I'm surprised this ticket isn't more active. Maybe people aren't writing tests for activestorage.
