### ISSUE TITLE
The cookies_jar of ActionDispatch::TestRequest will make dirty cookies values in integration test

### ISSUE THREAD

**Issue by griffinqiu** [rails/rails#32791]
### Steps to reproduce
https://github.com/griffinqiu/rails5_cookies_jar_issue_in_test - This application is a sample demo for reproduce the issue. The test will be random failed. The cookies have been set with signed in integration test, and then the controller test will have some dirty cookie values.

### Expected behavior
The cookies values should be clean in controller test.

### Actual behavior
The cookies values is the last integration test cookies in controller test.

### System configuration
**Rails version**:
5.1.6

**Ruby version**:
2.3.7

**Comment by y-yagi** [comment]
I think that this point is correct. The cookie is certainly left and it is affecting. 

However, I'm feeling something wrong that specify cookies in integration test. 
The integration test is meant to simulate user interactions, and users don't set cookie directly.  

Is it really necessary to specify a cookie in your integration test?
