### ISSUE TITLE
[ActiveRecord] calling 'destroy' on an unsaved model instance calls methods registered via after_create_commit

### ISSUE THREAD

**Issue by xxx** [rails/rails#32806]
### Steps to reproduce

I realize how edge-casey this is, and it should not happen in real code. It popped up in one of our tests.

Call `destroy` on new, unpersisted model instance. It will call anything that was registered via `after_create_commit` (and maybe others, but I haven't checked).

```ruby
class Thing < ActiveRecord::Base
  after_create_commit proc { puts "after_create_commit proc called" }
  after_create_commit :after_create_commit_method

  def after_create_commit_method
    puts 'after_create_commit_method called'
  end
end

Thing.new.destroy
# after_create_commit_method called
# after_create_commit proc called
```

### Expected behavior
Neither registered create callback methods nor procs would be executed.

### Actual behavior
Both registered create callback methods and procs are executed.

### System configuration
**Rails version**: 5.2.0

**Ruby version**: 2.5.1

**Comment by zdennis** [comment]
This is a bit late but this change seems to break after_rollback(s) on :create. E.g.

```ruby
class MyModel < ApplicationRecord
  validates_presence_of :some_field

  after_rollback :wibble, on: :create

  def wibble
    puts "After rollback was called"
  end
end

MyModel.new.save
```

On Rails 5.1.7 this prints out:

> After rollback was called

On Rails 5.2 and 6.0.1 this prints out nothing.
