### ISSUE TITLE
Don't require 'ruby-oci8' warning as soon as I use ruby-oci8 gem

### ISSUE THREAD

**Issue by francescm** [rails/rails#32811]
### Steps to reproduce

    rails new myapp
    cd myapp
    echo "gem 'ruby-oci8'" >> Gemfile
    bundle install

### Expected behavior

I should start coding, no further settings/fixes required.

### Actual behavior

    bundle exec rake -T

returns a warning:

     Don't require 'ruby-oci8'. Use "require 'oci8'" instead. 'ruby-oci8.rb' was added only for 'Bundler.require'.
     Warning: NLS_LANG is not set. fallback to US7ASCII.

Same warning in `rails c` as well.

### System configuration

```
About your application's environment
Rails version             5.2.0
Ruby version              2.5.0-p0 (x86_64-darwin17)
RubyGems version          2.7.3
Rack version              2.0.5
JavaScript Runtime        Node.js (V8)
Middleware                Rack::Sendfile, ActionDispatch::Static, ActionDispatch::Executor, ActiveSupport::Cache::Strategy::LocalCache::Middleware, Rack::Runtime, Rack::MethodOverride, ActionDispatch::RequestId, ActionDispatch::RemoteIp, Sprockets::Rails::QuietAssets, Rails::Rack::Logger, ActionDispatch::ShowExceptions, WebConsole::Middleware, ActionDispatch::DebugExceptions, ActionDispatch::Reloader, ActionDispatch::Callbacks, ActiveRecord::Migration::CheckPending, ActionDispatch::Cookies, ActionDispatch::Session::CookieStore, ActionDispatch::Flash, ActionDispatch::ContentSecurityPolicy::Middleware, Rack::Head, Rack::ConditionalGet, Rack::ETag, Rack::TempfileReaper
Application root          /Users/francesco/sviluppo/rails/oci8
Environment               development
Database adapter          sqlite3
Database schema version   0

```

**Comment by y-yagi** [comment]
This is the issue of `ruby-oci8` 
`ruby-oci8` customizes to not output warnings in case of require from `Bundler.require`. 
https://github.com/kubo/ruby-oci8/blob/master/lib/ruby-oci8.rb

However, if `bootsnap` gem is used, this check will not work properly because `bootsnap` overrides require.
Please report to  https://github.com/kubo/ruby-oci8 what to do about the correspondence in that case. Thanks.

**Comment by guilleiguaran** [comment]
I think you can do this in your Gemfile as well:

```ruby
gem 'ruby-oci8', require: 'oci8'
```

**Comment by francescm** [comment]
thank you, @guilleiguaran
that's working.
