### ISSUE TITLE
Eager-loading through associations: Query joins the same table multiple times

### ISSUE THREAD

**Issue by betesh** [rails/rails#32819]
When I eager-load multiple `has_many through` associations in the same query, and they are all associated through the same table, it seems to me that the table in between them only needs to be `LEFT OUTER JOIN`'ed once in the query.  However, it's in fact joined once for each through association, even if it has already been eager-loaded directly.

I suspect this comes at a cost, since joining the same table twice in the same query means the DB would have to do twice as much work as if it had only had to join that table once.

I can't think of a reason this would be necessary.  If this behavior is necessary, please enlighten me.

### Steps to reproduce

Run the following script.  It generates the SQL used to eager-load multiple through-associations.

```
# frozen_string_literal: true

begin
  require "bundler/inline"
rescue LoadError => e
  $stderr.puts "Bundler version 1.10 or later is required. Please update your Bundler"
  raise e
end

gemfile(true) do
  source "https://rubygems.org"

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  gem "rails", github: "rails/rails"
  gem "sqlite3"
end

require "active_record"
require "minitest/autorun"
require "logger"

# This connection will do for database-independent bug reports.
ActiveRecord::Base.establish_connection(adapter: "sqlite3", database: ":memory:")
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :captains, force: true do |t|
  end

  create_table :ships, force: true do |t|
    t.integer :captain_id
  end

  create_table :sails, force: true do |t|
    t.integer :ship_id
    t.string :color
  end

  create_table :anchors, force: true do |t|
    t.integer :ship_id
  end
end

class Captain < ActiveRecord::Base
  has_many :ships
  has_many :sails, ->{ where(color: :red) }, through: :ships
  has_many :anchors, through: :ships
end

class Ship < ActiveRecord::Base
  belongs_to :captain
  has_many :sails
  has_many :anchors
end

class Sail < ActiveRecord::Base
  belongs_to :ship
end

class Anchor < ActiveRecord::Base
  belongs_to :ship
end

class BugTest < Minitest::Test
  def test_association_stuff
    sql = Captain.eager_load(:ships, :sails, :anchors).to_sql
    puts sql
    assert_equal 1, sql.scan(/LEFT OUTER JOIN "ships"/).length
  end
end
```

### Expected behavior
The query should `LEFT OUTER JOIN "ships"` once and use the resulting association for all through associations.

```
SELECT "captains"."id" AS t0_r0, "ships"."id" AS t1_r0, "ships"."captain_id" AS t1_r1, "sails"."id" AS t2_r0, "sails"."ship_id" AS t2_r1, "sails"."color" AS t2_r2, "anchors"."id" AS t3_r0, "anchors"."ship_id" AS t3_r1 FROM "captains"
LEFT OUTER JOIN "ships" ON "ships"."captain_id" = "captains"."id"
LEFT OUTER JOIN "sails" ON "sails"."ship_id" = "ships"."id" AND "sails"."color" = 'red'
LEFT OUTER JOIN "anchors" ON "anchors"."ship_id" = "ships"."id"
```

### Actual behavior
The query generates a separate `LEFT OUTER JOIN "ships"` for each association that it needs to load through ships.

```
SELECT "captains"."id" AS t0_r0, "ships"."id" AS t1_r0, "ships"."captain_id" AS t1_r1, "sails"."id" AS t2_r0, "sails"."ship_id" AS t2_r1, "sails"."color" AS t2_r2, "anchors"."id" AS t3_r0, "anchors"."ship_id" AS t3_r1 FROM "captains"
LEFT OUTER JOIN "ships" ON "ships"."captain_id" = "captains"."id"
LEFT OUTER JOIN "ships" "ships_captains_join" ON "ships_captains_join"."captain_id" = "captains"."id"
LEFT OUTER JOIN "sails" ON "sails"."ship_id" = "ships_captains_join"."id" AND "sails"."color" = 'red'
LEFT OUTER JOIN "ships" "ships_captains_join_2" ON "ships_captains_join_2"."captain_id" = "captains"."id"
LEFT OUTER JOIN "anchors" ON "anchors"."ship_id" = "ships_captains_join_2"."id"
```

### System configuration
**Rails version**:
 master @ bd53f35
**Ruby version**:
2.4.1

**Comment by shawndodo** [comment]
+1

**Comment by chumakoff** [comment]
@betesh Do you know that you can get what you are expecting like this `Captain.eager_load(ships: {sails: :anchors})`?

**Comment by betesh** [comment]
@chumakoff I realize that but that uses a different set of associations.  A later call to `captains.map(&:sails)` would result in N+1 queries.

**Comment by betesh** [comment]
* Still happens on 5-2-stable
* Still happens on master

**Comment by betesh** [comment]
* Still happens on 5-2-stable
* Still happens on master

**Comment by pedrofurtado** [comment]
@rafaelfranca @pixeltrix  Any news about this issue? :+1:

**Comment by aboelleef** [comment]
we have the same issue after upgrading to rails 5.2

**Comment by pedrofurtado** [comment]
@betesh @aboelleef @rafaelfranca @pixeltrix The issue still happens in Rails 5.2.3 (latest version). It's a great idea to reopen the issue 👍
