### ISSUE TITLE
Scopes created by enum could leverage eager loading

### ISSUE THREAD

**Issue by Drenmi** [rails/rails#32815]
When using `enum` scopes on an eager loaded relation, it doesn't leverage the fact that the records are loaded.

Perhaps I am too anchored to our use case. If so, please widen my perspective. It seems to me that this is a narrow enough class of scopes that it might make sense.

### Steps to reproduce

```ruby
# app/models/foo.rb
class Foo < ApplicationRecord
  has_many :bars
end
```

```ruby
# app/models/bar.rb
class Bar < ApplicationRecord
  belongs_to :foo

  enum qux: [:baz]
end
```

```ruby
foo = Foo.includes(:bars).last

foo.bars
#=> []

foo.bars.baz
# Bar Load (0.4ms)  SELECT "bars".* FROM "bars" WHERE "bars"."foo_id" = $1 AND "bars"."status" = $2 ORDER BY "bars"."created_at" ASC  [["foo_id", 1], ["status", 0]]
#=> []
```

As can be seen, `bars.baz` is a subset of `bars`, all of which are loaded and have their `enum` values available for filtering.

### Expected behavior

It filters from the loaded relation.

### Actual behavior

It creates a new database query every time.

### System configuration
**Rails version**:

Rails 5.1.4

**Ruby version**:

ruby 2.5.1p57

**Comment by phoet** [comment]
This would be super helpful.
