### ISSUE TITLE
uninitialized constant ActiveRecord::ConnectionAdapters::TransactionManager

### ISSUE THREAD

**Issue by xecutioner** [rails/rails#32813]
I am not sure why but active record failed to commit record into the database With following backtrace. I am not sure where to look for in what went wrong. 

> 2018-05-04T06:25:44Z p-11428 t-bkyp0 ERROR: [Exception error=“uninitialized constant ActiveRecord::ConnectionAdapters::TransactionManager” error_class=NameError backtrace=/home/deploy/www/db_service/shared/bundle/ruby/2.4.0/gems/activerecord-5.1.4/lib/active_record/connection_adapters/abstract/database_statements.rb:250:in `reset_transaction',/home/deploy/www/db_service/shared/bundle/ruby/2.4.0/gems/activerecord-5.1.4/lib/active_record/connection_adapters/abstract/database_statements.rb:6:in `initialize’,/home/deploy/www/db_service/shared/bundle/ruby/2.4.0/gems/activerecord-5.1.4/lib/active_record/connection_adapters/abstract/query_cache.rb:48:in `initialize',/home/deploy/www/db_service/shared/bundle/ruby/2.4.0/gems/activerecord-5.1.4/lib/active_record/connection_adapters/abstract_adapter.rb:97:in `initialize’,/home/deploy/www/db_service/shared/bundle/ruby/2.4.0/gems/activerecord-5.1.4/lib/active_record/connection_adapters/postgresql_adapter.rb:212:in `initialize',/home/deploy/www/db_service/shared/bundle/ruby/2.4.0/gems/activerecord-5.1.4/lib/active_record/connection_adapters/postgresql_adapter.rb:38:in `new’,/home/deploy/www/db_service/shared/bundle/ruby/2.4.0/gems/activerecord-5.1.4/lib/active_record/connection_adapters/postgresql_adapter.rb:38:in `postgresql_connection',/home/deploy/www/db_service/shared/bundle/ruby/2.4.0/gems/activerecord-5.1.4/lib/active_record/connection_adapters/abstract/connection_pool.rb:759:in `new_connection’,/home/deploy/www/db_service/shared/bundle/ruby/2.4.0/gems/activerecord-5.1.4/lib/active_record/connection_adapters/abstract/connection_pool.rb:803:in `checkout_new_connection',/home/deploy/www/db_service/shared/bundle/ruby/2.4.0/gems/activerecord-5.1.4/lib/active_record/connection_adapters/abstract/connection_pool.rb:782:in `try_to_checkout_new_connection’,/home/deploy/www/db_service/shared/bundle/ruby/2.4.0/gems/activerecord-5.1.4/lib/active_record/connection_adapters/abstract/connection_pool.rb:743:in `acquire_connection',/home/deploy/www/db_service/shared/bundle/ruby/2.4.0/gems/activerecord-5.1.4/lib/active_record/connection_adapters/abstract/connection_pool.rb:500:in `checkout’,/home/deploy/www/db_service/shared/bundle/ruby/2.4.0/gems/activerecord-5.1.4/lib/active_record/connection_adapters/abstract/connection_pool.rb:374:in `connection',/home/deploy/www/db_service/shared/bundle/ruby/2.4.0/gems/activerecord-5.1.4/lib/active_record/connection_adapters/abstract/connection_pool.rb:405:in `with_connection’,/home/deploy/www/db_service/releases/20180424104611/lib/db_tuple_creator.rb:21:in `work',/home/deploy/www/db_service/shared/bundle/ruby/2.4.0/gems/sneakers-2.6.0/lib/sneakers/worker.rb:61:in `block (3 levels) in do_work’,/home/deploy/www/db_service/shared/bundle/ruby/2.4.0/gems/sneakers-2.6.0/lib/sneakers/metrics/null_metrics.rb:8:in `timing',/home/deploy/www/db_service/shared/bundle/ruby/2.4.0/gems/sneakers-2.6.0/lib/sneakers/worker.rb:56:in `block (2 levels) in do_work’,/usr/local/rvm/rubies/ruby-2.4.0/lib/ruby/2.4.0/timeout.rb:93:in `block in timeout',/usr/local/rvm/rubies/ruby-2.4.0/lib/ruby/2.4.0/timeout.rb:103:in `timeout’,/home/deploy/www/db_service/shared/bundle/ruby/2.4.0/gems/sneakers-2.6.0/lib/sneakers/worker.rb:55:in `block in do_work',/home/deploy/www/db_service/shared/bundle/ruby/2.4.0/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:348:in `run_task’,/home/deploy/www/db_service/shared/bundle/ruby/2.4.0/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:337:in `block (3 levels) in create_worker',/home/deploy/www/db_service/shared/bundle/ruby/2.4.0/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:320:in `loop’,/home/deploy/www/db_service/shared/bundle/ruby/2.4.0/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:320:in `block (2 levels) in create_worker',/home/deploy/www/db_service/shared/bundle/ruby/2.4.0/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:319:in `catch’,/home/deploy/www/db_service/shared/bundle/ruby/2.4.0/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:319:in `block in create_worker’]

**Comment by y-yagi** [comment]
This seems to be related to #26441 and #26273. 

Could you please provide more detailed information on the error situation?
