### ISSUE TITLE
Exception causes db queries

### ISSUE THREAD

**Issue by Linuus** [rails/rails#32810]
### Steps to reproduce

1. Clone https://github.com/linuus/rails-log-bug
2. Run `bundle install` and `bin/rails db:setup`
3. Run `bin/rails s`
4. Go to http://localhost:3000/things/1

### Expected behavior

It should only run _one_ query against the database.

### Actual behavior
It seems to run multiple queries when looking in the log.

**Log:**
```
Started GET "/things/1" for 127.0.0.1 at 2018-05-04 08:21:55 +0200
Processing by ThingsController#show as HTML
  Parameters: {"id"=>"1"}
  Thing Load (0.1ms)  SELECT  "things".* FROM "things" WHERE "things"."id" = ? LIMIT ?  [["id", 1], ["LIMIT", 1]]
  ↳ app/controllers/things_controller.rb:5
  Thing Load (0.2ms)  SELECT  "things".* FROM "things" LIMIT ?  [["LIMIT", 11]]
  ↳ /Users/linus/.asdf/installs/ruby/2.5.0/lib/ruby/gems/2.5.0/gems/activerecord-5.2.0/lib/active_record/log_subscriber.rb:98
  CACHE Thing Load (0.0ms)  SELECT  "things".* FROM "things" LIMIT ?  [["LIMIT", 11]]
  ↳ /Users/linus/.asdf/installs/ruby/2.5.0/lib/ruby/gems/2.5.0/gems/activerecord-5.2.0/lib/active_record/log_subscriber.rb:98
Completed 500 Internal Server Error in 165ms (ActiveRecord: 0.7ms)



  CACHE Thing Load (0.0ms)  SELECT  "things".* FROM "things" LIMIT ?  [["LIMIT", 11]]
  ↳ /Users/linus/.asdf/installs/ruby/2.5.0/lib/ruby/gems/2.5.0/gems/activerecord-5.2.0/lib/active_record/log_subscriber.rb:98
NameError (undefined local variable or method `this_line_will_cause_a_name_error' for #<ThingsController:0x00007fb43f75c830>):

app/controllers/things_controller.rb:7:in `show'
```

Look at https://github.com/Linuus/rails-log-bug/blob/master/app/controllers/things_controller.rb, which looks like this:

```ruby
  def show
    @things = Thing.all

    @thing = @things.find(params[:id])

    this_line_will_cause_a_name_error
  end
```

If I change this to only call `Thing` and not `Thing.all` it only makes _one_ query to the db.

```ruby
  def show
    @things = Thing

    @thing = @things.find(params[:id])

    this_line_will_cause_a_name_error
  end
```

**Log:**
```
Started GET "/things/1" for 127.0.0.1 at 2018-05-04 08:28:43 +0200
Processing by ThingsController#show as HTML
  Parameters: {"id"=>"1"}
  Thing Load (0.2ms)  SELECT  "things".* FROM "things" WHERE "things"."id" = ? LIMIT ?  [["id", 1], ["LIMIT", 1]]
  ↳ app/controllers/things_controller.rb:5
Completed 500 Internal Server Error in 229ms (ActiveRecord: 0.2ms)



NameError (undefined local variable or method `this_line_will_cause_a_name_error' for #<ThingsController:0x00007fb439ba3f20>):

app/controllers/things_controller.rb:7:in `show'
```

Also, if removing the line causing the error, `this_line_will_cause_a_name_error`, only one query is ever executed.

This behaviour seems quite odd to me, is it a bug?

### System configuration
**Rails version**: 5.2.0

**Ruby version**: 2.5.0

**Comment by ryandav** [comment]
Hi @Linuus 

This doesn't look like a bug to me. In your first example you are retrieving all the records into @things then retrieving the record that is associated with the id. So this is two database calls.

If you did Thing.find(params[:id]) then it would do one database query.

**Comment by Linuus** [comment]
@ryandav Sure, but in the `Thing.all` example it makes 4 queries (`Thing.all` is executed 3 times and `@things.find(...)` once) when it errors and 1 when it doesn't (only `@things.find(...)`). Is that expected?

**Comment by ryandav** [comment]
@linuus
This is not doing four database queries. In your code you have made two database queries, one to retrieve all in the database, then one to retrieve a record. Then rails caches each query. How active record works and caching is covered in the Rails guides.

http://guides.rubyonrails.org/active_record_basics.html
http://guides.rubyonrails.org/caching_with_rails.html

**Comment by Linuus** [comment]
@ryandav I know well how AR works :)

Yes, it's 4 queries being triggered. It shows them as cached because the same query is triggered three times.

Also, the `#all` method is lazy (it was eager in older AR versions) which means the DB query is NOT executed unless it is accessed for other things than building another query (which is what I do in my example).

To sum up, yes it is triggering 4 queries when an error is raised and 1 when there is no error...

**Comment by ryandav** [comment]
@linuus I just tried it out locally from your repo and after reading your explanation can see what you are saying now. It generates multiple db queries if there is an error at the end of the controller, but not if there isn't... it seems to be more complex than I originally thought. Hope some of the Rails contributors can shed more light on this one.

**Comment by matthewd** [comment]
If it helps, I can offer the observation that those queries are coming from `inspect` (`LIMIT 11` is the giveaway).

**Comment by Linuus** [comment]
@matthewd That is true, good catch. Perhaps something inspects all instance variables when there’s an error? That would explain why the query is triggered at all. but there stills seems to be an issue with it being triggered multiple times.

**Comment by Linuus** [comment]
It's also odd that it prints the query source as `/Users/linus/.asdf/installs/ruby/2.5.0/lib/ruby/gems/2.5.0/gems/activerecord-5.2.0/lib/active_record/log_subscriber.rb:98` which is where that line itself is printed.

**Comment by Linuus** [comment]
I've been trying to debug this but I'm too unfamiliar with the rails/AR codebase to figure this out...

Perhaps I should watch the talk about debugging rails itself by @sgrif ;)

**Comment by Linuus** [comment]
:(
