### ISSUE TITLE
`render` and `yield` output wrong markup when using xml builder with `cache`

### ISSUE THREAD

**Issue by srghma** [rails/rails#32821]
### Steps to reproduce

```rb
# config/developent.rb
  config.action_controller.perform_caching = true

  config.cache_store = :memory_store
  config.public_file_server.headers = {
    'Cache-Control' => "public, max-age=#{2.days.seconds.to_i}"
  }

```
```rb
# app/controllers/rss_controller.rb
class RssController < ApplicationController
  layout false

  def feed
  end
end
```

```rb
# app/view/feed.rss.builder
render('rss/components/layout', builder: xml) do
  cache("fragment") do
    xml.p "Builder"
  end
end

```

```rb
# app/view/rss/containers/_layout.rss.builder
builder.body do
  yield
end
```

### Expected behavior
1. first page load
```
<body>
  <p>Builder</p>
</body>
```
1. second page load
```
<body>
  <p>Builder</p>
</body>
```

### Actual behavior
1. first page load
```
<body>
  <p>Builder</p>
</body>
```
1. second page load
```
<body>
</body>
```

### System configuration
**Rails version**:
gem 'rails', '5.1.5'

**Ruby version**: 2.4.2

**Comment by yannski** [comment]
Same problem here. When I'm using a cache directive, the rendering is empty after the cache has been warmed up :/

**Comment by dallasrpi** [comment]
I have run into this same issue with Rails 6.  Oddly enough its blank until I put a comment at the end.  Having it magically work with a comment at the bottom doesnt sit well with me so we are just going to convert to erb template.
