### ISSUE TITLE
has_secure_token NoMethodError: undefined method `token?'

### ISSUE THREAD

**Issue by itay-grudev** [rails/rails#32824]
In some situations I am getting a:
```
`NoMethodError: undefined method `token?'`.
```

For example creating an object containing `has_secure_token` with FactoryBot.

I traced the issue to line `32`:

https://github.com/rails/rails/blob/831be98f9a6685da3410b0c9bf4143bd8dd647af/activerecord/lib/active_record/secure_token.rb#L28-L33

Can we instead use something like:

```ruby
self.try("#{attribute}?")
```

instead of

```ruby
send("#{attribute}?")
```

This would bypass the issue and allow for a broader range of scenarios without breaking backwards compatibility.

P.S. Though I'm not sure why exactly the `token?` method is missing, but I don't have time to dig in the ActiveRecord and FactoryBot code.

**Comment by y-yagi** [comment]
Does the `token` column exist in the model using `has_secure_token`? 
If `token` column exists, `send("#{attribute}?")` works correctly. So I think don't need to use `try`.  
If there is a token column and get an error, there may be a issue with the FactoryBot. Please report to FactoryBot's repsitory. Thanks!
