### ISSUE TITLE
undefined method `deliver_now!' for #<Mail::Message:0x00000000027aa470>

### ISSUE THREAD

**Issue by knzudgt** [rails/rails#32834]
I am studying Peter Cooper's book Beginning Ruby.
According to the author ActionMailer can be used independently of Rails.
So I installed the ActionMailer gem and wrote the code below which is an extract from the book:

    require 'action_mailer'

    ActionMailer::Base.smtp_settings = {
	    :address => "smtp.mail.yahoo.com",
	    :port => 465,
	    :authentication => :login,
	    :user_name => "username@yahoo.com",
	    :password => "password",
	    :openssl_verify_mode => :ssl
    }

    class Emailer < ActionMailer::Base
	  def test_email(email_address, email_body)
        mail(to: email_address, from: 'username@yahoo.com', subject: 'action mailer test', body: email_body)
	  end
    end

    emailer = Emailer.new
    emailer.test_email('username@gmail.com', 'This is a test e-mail!').deliver_now

When I run the rb file containing the above code I receive the following error message:

    /home/knzudgt/.rvm/gems/ruby-2.5.1@beginning_ruby/gems/mail-2.7.0/lib/mail/message.rb:1396:in `method_missing': undefined method `deliver_now' for #<Mail::Message:0x0000000002256b68> (NoMethodError)

Why the method `deliver_now` is not recognized?

**Comment by y-yagi** [comment]
You don't need to create Message instance. Call `test_email` directly.

```ruby
Emailer.test_email('username@gmail.com', 'This is a test e-mail!').deliver_now 
``` 

Also, please use the [mailing list](https://groups.google.com/forum/#!forum/rubyonrails-talk) or StackOverflow for questions/help, where a wider community will be able to help you. We reserve the issues tracker for issues only. Thanks.
