### ISSUE TITLE
Installing ActionCable library by yarn with 'autoclean' option

### ISSUE THREAD

**Issue by BEGEMOT9I** [rails/rails#32839]
### Steps to reproduce

`yarn install` for `actioncable` with `autoclean` (https://yarnpkg.com/lang/en/docs/cli/autoclean/)

### Expected behavior
Unknow

### Actual behavior
**`.yarnclean` File example:**
```
# asset directories
docs
doc
website
images
assets
```

By default, `yarn` cleaning all dirs assets from packages. You can, of course, forbid him to delete a folder from your library, but, it seems to me, this is wrong. Is it possible to move the source code to the root of the library?

### System configuration
**Rails version**: any

**Ruby version**: any

**Comment by javan** [comment]
> *Note: This command is considered for advanced use cases only. Unless you are experiencing issues with the amount of files that are installed as part of node_modules it is not recommended to use this command. It will permanently delete files in node_modules which could cause packages to stop working.*
>
> Autoclean functionality is **disabled** by default.

-- https://yarnpkg.com/lang/en/docs/cli/autoclean/

Sorry, I don't think that's something we can reasonably support.
