### ISSUE TITLE
Specific Text is Causing Literal = Equals sign in email after mail.body.encoded is called

### ISSUE THREAD

**Issue by uhrohraggy** [rails/rails#32836]
### Steps to reproduce

Fork https://github.com/uhrohraggy/email-bug (sample app showing mail behavior)
Run the following

```
rails c
UserMailer.test.deliver_now #Shows generating the Email generally
# or
UserMailer.test2.deliver_now #uses built-in mail function
```
It doesn't appear any special characters or encodings are used, but perhaps I'm missing something?

### Expected behavior
Email should be delivered as specified in the Mailer template and without literal equals signs in the email and between characters.

>  Fix height of Parking and Where to MeetFix height of Parking and Where to MeetFix height of Parking and Where to MeetFix height of Parking and Where to MeetFix height of Parking and Where to MeetFix height of Parking and Where to MeetFix height of Parking and Where to MeetFix height of Parking and Where to MeetFix height of Parking and Where to MeetFix height of Parking and Where to MeetFix height of Parking and Where to MeetFix height of Parking and Where to MeetFix height of Parking and Where to MeetFix height of Parking and Where to MeetFix height of Parking and Where to MeetFix height of Parking and Where to MeetFix height of Parking and Where to MeetFix height of Parking and Where to MeetFix height of Parking and Where to MeetFix height of Parking and Where to MeetFix height of Parking and Where to MeetFix height of Parking and Where to MeetFix height of Parking and Where to MeetFix height of Parking and Where to MeetFix height of Parking and Where to MeetFix height of Parking and Where to Meet

### Actual behavior
Email renders with literal equals sign in the email, which is present after mailer internally calls `mail.body.encoded`. 

> Fix height of Parking and Where to MeetFix height of Parking and Where = to MeetFix height of Parking and Where to MeetFix height of Parking and W= here to MeetFix height of Parking and Where to MeetFix height of Parking = and Where to MeetFix height of Parking and Where to MeetFix height of Par= king and Where to MeetFix height of Parking and Where to MeetFix height o= f Parking and Where to MeetFix height of Parking and Where to MeetFix hei= ght of Parking and Where to MeetFix height of Parking and Where to MeetFi= x height of Parking and Where to MeetFix height of Parking and Where to M= eetFix height of Parking and Where to MeetFix height of Parking and Where= to MeetFix height of Parking and Where to MeetFix height of Parking and = Where to MeetFix height of Parking and Where to MeetFix height of Parking= and Where to MeetFix height of Parking and Where to MeetFix height of Pa= rking and Where to MeetFix height of Parking and Where to MeetFix height = of Parking and Where to MeetFix height of Parking and Where to Meet

### System configuration
**Rails version**: Rails 5.1.6

**Ruby version**: ruby 2.4.1p111 (2017-03-22 revision 58053) [x86_64-darwin17]
<img width="1222" alt="screen shot 2018-05-07 at 3 20 57 am" src="https://user-images.githubusercontent.com/3861250/39690001-9637d96c-51a6-11e8-8d42-5ffb1f170a93.png">
<img width="1438" alt="screen shot 2018-05-07 at 3 28 12 am" src="https://user-images.githubusercontent.com/3861250/39690042-bc81f152-51a6-11e8-925b-988f2f3b56c6.png">

**Comment by uhrohraggy** [comment]
<img width="1222" alt="screen shot 2018-05-07 at 3 20 57 am" src="https://user-images.githubusercontent.com/3861250/39690215-533ef7d4-51a7-11e8-8d41-edc1d86e75e2.png">

Just image showing the rendered view from GMail

**Comment by georgeclaghorn** [comment]
This is the expected behavior of the [quoted-printable](https://en.wikipedia.org/wiki/Quoted-printable) encoding. The equals sign escapes the subsequent newline.

**Comment by uhrohraggy** [comment]
@georgeclaghorn thanks for the insanely quick response and link to quoted-printable. I guess then the question I have is why is it rendering with a literal `=` in the email when viewed in GMail? Based on that it looks like `mail.body` has new lines in the middle of words, but the mailer view in the sample app I posted above has that data on one line without any line breaks

**Comment by georgeclaghorn** [comment]
Sorry, I didn’t see your Gmail screenshot. This looks like a bug in the Mail gem: the equals sign should be followed by CRLF (`\r\n`) instead of LF (`\n`). Could you try installing mail v2.7.1.rc1?

**Comment by uhrohraggy** [comment]
Thanks again @georgeclaghorn for speedy isolation - it's unfortunately still reproducing with latest RC, but will follow up with them.

**Comment by uhrohraggy** [comment]
@georgeclaghorn Pardon on bothering you with this further, but took a naive look and appears as though Mail is just calling `[].pack('M')` under the hood, which should correspond to RFC2045 https://www.ietf.org/rfc/rfc2045.txt

```
["Fix height of Parking and Where to MeetFix height of Parking and Where to MeetFix height of Parking and Where to MeetFix height of Parking and Where to MeetFix height of Parking and Where to MeetFix height of Parking and Where to MeetFix height of Parking and Where to MeetFix height of Parking and Where to MeetFix height of Parking and Where to MeetFix height of Parking and Where to MeetFix height of Parking and Where to MeetFix height of Parking and Where to MeetFix height of Parking and Where to MeetFix height of Parking and Where to MeetFix height of Parking and Where to MeetFix height of Parking and Where to MeetFix height of Parking and Where to MeetFix height of Parking and Where to MeetFix height of Parking and Where to MeetFix height of Parking and Where to MeetFix height of Parking and Where to MeetFix height of Parking and Where to MeetFix height of Parking and Where to MeetFix height of Parking and Where to MeetFix height of Parking and Where to MeetFix height of Parking and Where to Meet"].pack('M')


=> "Fix height of Parking and Where to MeetFix height of Parking and Where to=\n MeetFix height of Parking and Where to MeetFix height of Parking and Whe=\nre to MeetFix height of Parking and Where to MeetFix height of Parking an=\nd Where to MeetFix height of Parking and Where to MeetFix height of Parki=\nng and Where to MeetFix height of Parking and Where to MeetFix height of =\nParking and Where to MeetFix height of Parking and Where to MeetFix heigh=\nt of Parking and Where to MeetFix height of Parking and Where to MeetFix =\nheight of Parking and Where to MeetFix height of Parking and Where to Mee=\ntFix height of Parking and Where to MeetFix height of Parking and Where t=\no MeetFix height of Parking and Where to MeetFix height of Parking and Wh=\nere to MeetFix height of Parking and Where to MeetFix height of Parking a=\nnd Where to MeetFix height of Parking and Where to MeetFix height of Park=\ning and Where to MeetFix height of Parking and Where to MeetFix height of=\n Parking and Where to MeetFix height of Parking and Where to Meet=\n" 
```

Would that be on `Mail` to then convert that to \r\rn or on `[].pack('M')`?

**Comment by uhrohraggy** [comment]
Please ignore, I TL;DR; PEBKAC and did not read this was already identified earlier in the Mail thread.

**Comment by uhrohraggy** [comment]
thanks again for all of your help!
