### ISSUE TITLE
"after_commit on: :create" with "save" inside

### ISSUE THREAD

**Issue by vfonic** [rails/rails#32831]
This is the same issue like this one: [after_commit :my_callback, :on => :create fires on update too ](https://github.com/rails/rails/issues/14493)

I'm posting a new issue, as the old one is closed. Should I just use the old issue? Is someone tracking closed issues' comments?

I've spent some time debugging to get to the bottom of this. I didn't know you can't call `save` or `update_attributes!` inside of an `after_commit ..., on: :create` callback.
I think this _is_ a bug and it should be considered for fixing. I can see in the other thread that some rails maintainers also confirmed this is a bug.
There's this PR from 3 years ago that apparently fixes this, but the PR was never merged: https://github.com/rails/rails/pull/18367

@rafaelfranca said:
> `save` inside a `after_commit` with `on: :create` is also inside the `create` lifecycle even if what it is doing is an update. The lifecycle only finish when the last `after_commit` callback runs, so we don't have a way to detect if that `save` is an update or not.

Not sure if we could have callback stack, like there is a function call stack. I'm just shooting an idea here.

How did it work before? This (revert) [commit](https://github.com/rails/rails/commit/9d2146ac6e4c1fdc9cc157d614b1eb9968ac6a2e) seems to revert the changes that introduced this bug. It seems like it's broken again.

### System configuration
**Rails version**:
5.1.5
**Ruby version**:
2.4.2

**Comment by eugeneius** [comment]
> How did it work before? This (revert) commit seems to revert the changes that introduced this bug. It seems like it's broken again.

You have this backwards: https://github.com/rails/rails/pull/6226 _fixed_ the bug, and the commit you linked to reverted the fix because it had other undesirable effects. As far as I can tell, this bug has always been present since `after_commit` callbacks were added to Rails.
