### ISSUE TITLE
ActiveRecord flag ivar corruption after rolled back transactions

### ISSUE THREAD

**Issue by brasic** [rails/rails#32847]
After upgrading from 4.2.10 to 5.1.6 one of our applications started encountering many unusual issues involving transactions.  This report isolates one of the issues that is pretty clearly a bug: after a transaction is rolled back, records that participated in the transaction respond nondeterministically to predicate methods like `new_record?`.   This is particularly bad since `new_record?` is used internally by activerecord to make decisions like whether to create or update a record when saving, so the way this bug manifests can depend on exactly how the application interacts with its records.  It appears that exercising associations may be required to reproduce the bad behavior.
  
### Steps to reproduce
- new up an AR `instance` outside a transaction
- inside a transaction:
  - create an associated record 
  - save both records
  - rollback the transaction
- inspect `instance#new_record?` twice, observe that the value changes on the second call.

Here is a reproduction test case that fails on `v4.2.10`, `v5.0.7`, `v5.1.6`, `v5.2.0` and `master`.  It passes on `v4.1.16`.  `git bisect` between `v4.1.16` and `v4.2.10` indicates that 9ddb9553e336219dcdfe2bdda6120359e33300ee is the first bad commit.
 
```ruby
# frozen_string_literal: true

begin
  require "bundler/inline"
rescue LoadError => e
  $stderr.puts "Bundler version 1.10 or later is required. Please update your Bundler"
  raise e
end

gemfile(true) do
  source "https://rubygems.org"

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  gem "rails", github: 'rails/rails'
  gem "sqlite3"
end

require "active_record"
require "minitest/autorun"
require "logger"

# This connection will do for database-independent bug reports.
ActiveRecord::Base.establish_connection(adapter: "sqlite3", database: ":memory:")
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :posts, force: true do |t|
    t.string :title, null: false
  end

  create_table :comments, force: true do |t|
    t.integer :post_id
    t.string :message, null:false
  end
end

class Post < ActiveRecord::Base
  has_one :comment
end

class Comment < ActiveRecord::Base
  belongs_to :post
end

class BugTest < Minitest::Test
  def test_association_stuff
    post = Post.new
    post.title = "Original title"
    Post.transaction(requires_new: true) do
      comment = post.build_comment
      comment.update!(message: "second")
      post.save!
      raise ActiveRecord::Rollback
    end
    assert_equal(post.new_record?, post.new_record?)
  end
end
```

output:
```
F

Failure:
BugTest#test_association_stuff [inappropriate_rollback.rb:56]:
Expected: false
  Actual: true
```

### Expected behavior
`new_record?` returns the same thing when called twice in a row with no intervening changes.
### Actual behavior
subsequent calls to `new_record?` return different values, appearing to fetch from different prior transaction states.

### System configuration
**Rails version**: master

**Ruby version**: 2.5.1

**Comment by Edouard-chin** [comment]
Related discussion https://github.com/rails/rails/pull/32796#pullrequestreview-117058744

FYI  @gmalette

**Comment by eugeneius** [comment]
> It appears that exercising associations may be required to reproduce the bad behavior.

The minimal reproduction just requires a new record to be saved twice in the same transaction:

```ruby
post = Post.new
Post.transaction do
  post.save!
  post.save!
  raise ActiveRecord::Rollback
end
```

Note that while `assert_equal(post.new_record?, post.new_record?)` demonstrates the problem, it doesn't specify the expected behaviour; before https://github.com/rails/rails/commit/9ddb9553e336219dcdfe2bdda6120359e33300ee, the assertion passes because `new_record?` consistently returns false, which is still incorrect.

If we specify the value we want, it's broken all the way back to at least 3.0:

```ruby
assert_equal true, post.new_record?
```
