### ISSUE TITLE
ActiveRecord associations not correctly cleared after transaction rollback

### ISSUE THREAD

**Issue by brasic** [rails/rails#32848]
Rails 4.2 introduced a regression in transaction rollbacks that continues to exist in master.  When an associated record is created inside a transaction and then the transaction is rolled back, some shell of the associated data sticks around making the original record unsavable.  I thought it might be possible that this was an  intentional change but the data that sticks around is clearly glitchy: it is void of any data and in most real apps will result in constraint violations when activerecord attempts to perform the insert.  I also believe this behavior can't be intentional since it makes composing ActiveRecord transactions with OO design basically impossible: code can't be expected to know if a record it is going to operate on has been poisoned by a rolled-back transaction.

### Steps to reproduce

1. Instantiate and save an AR instance, (`post` in my example)
2. open a transaction
  a. create and persist a record associated to the original instance (`comment` in my example)
  b. roll back the transaction
3. `save!` the original `post` instance again

### Expected behavior
- the `save!` outside the transaction (step 3) should succeed without raising an exception (it should be effectively a no-op)

### Actual behavior
The `post` has been "poisoned" by the rolled back transaction and cannot be saved. 
When calling `post.save!` ActiveRecord first attempts to insert (using `DEFAULT VALUES`) an empty-shell version of the associated `comment` record that was previously created and then discarded in the transaction.  In any nontrivial app with not-null constraints this empty insert will fail with an adapter-dependent exception.  In sqlite the exception raised is

```
ActiveRecord::StatementInvalid: SQLite3::ConstraintException: NOT NULL constraint failed: comments.message: INSERT INTO "comments" DEFAULT VALUES
```

Here is a reproduction test case.  This succeeds in rails `4-1-stable` and fails in all subsequent versions, including master.  I used git bisect to determine that the first commit in which this test fails is 9ddb9553e336219dcdfe2bdda6120359e33300ee.  This is the same commit that caused #32847 and that issue may indeed be related to this one.

```ruby
# frozen_string_literal: true

begin
  require "bundler/inline"
rescue LoadError => e
  $stderr.puts "Bundler version 1.10 or later is required. Please update your Bundler"
  raise e
end

gemfile(true) do
  source "https://rubygems.org"

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  gem "rails", github: "rails/rails"
  gem "sqlite3"
end

require "active_record"
require "minitest/autorun"
require "logger"

# This connection will do for database-independent bug reports.
ActiveRecord::Base.establish_connection(adapter: "sqlite3", database: ":memory:")
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :posts, force: true do |t|
    t.string :title, null: false
  end

  create_table :comments, force: true do |t|
    t.integer :post_id
    t.string :message, null:false
  end
end

class Post < ActiveRecord::Base
  has_one :comment
end

class Comment < ActiveRecord::Base
  belongs_to :post
end

class BugTest < Minitest::Test
  def test_nested_bug
    post = Post.new
    post.title = "title"
    post.save!
    Post.transaction(requires_new: true) do
      comment = post.build_comment
      comment.update!(message: "message")
      post.save!
      raise ActiveRecord::Rollback
    end
    post.save! # implicitly assert no exception.  Should be no-op
  end
end
```

output:
```
E

Error:
BugTest#test_nested_bug:
ActiveRecord::NotNullViolation: SQLite3::ConstraintException: NOT NULL constraint failed: comments.message: INSERT INTO "comments" DEFAULT VALUES



bin/rails test nested_bug.rb:47
```

### System configuration
**Rails version** master

**Ruby version** 2.5.1

**Comment by awangptc** [comment]
I'm still able to reproduce this problem with active record 5.2.0 and 5.2.1

```
  1) Error:
BugTest#test_nested_bug:
ActiveRecord::NotNullViolation: SQLite3::ConstraintException: NOT NULL constraint failed: comments.message: INSERT INTO "comments" DEFAULT VALUES
```

It doesn't look like the referenced issue fixed this.

**Comment by brasic** [comment]
@awangptc I believe the only workaround until this is fixed is never use activerecord instances associated with a rolled back transaction.  If a transaction is rolled back, any records that participated in it must be discarded.

**Comment by awangptc** [comment]
@brasic Should this be re-opened then?  Or should I open a new one?  This particular issue is closed due to the closing of the referenced issue but it doesn't appear to be fixed.

For the case we're seeing, we only have a single use case for the rollback and it occurs on rolling back a failed create.  So i have something like this as a workaround (using your test case)

```  after_rollback :do_foo, on: :create

  def do_foo
    puts "association reference persisted after rollback: #{post.comment.persisted?}"
    puts "model persisted after rollback: #{persisted?}"
    post.comment = nil if post.comment.id == id
  end
```

Interestingly enough, both the model and the association reference come back true on the puts.  I wouldn't expect that on an after_rollback.

**Comment by brasic** [comment]
Yes, it should probably be reopened.

**Comment by awangptc** [comment]
@brasic can you reopen this? Since I didn't report it I don't have the permission to do so.

**Comment by brasic** [comment]
I can confirm that the repro steps still work as of current master (0b6d2189c8d5c5d700877724b66242ce541d511d), but I don't have the ability to reopen this either.

**Comment by awangptc** [comment]
I'll just spin off a new issue then.

**Comment by eugeneius** [comment]
The root cause of the problem described here is already tracked in https://github.com/rails/rails/issues/15018 and https://github.com/rails/rails/issues/30167.

As was the case with https://github.com/rails/rails/issues/32847, this was broken even before https://github.com/rails/rails/commit/9ddb9553e336219dcdfe2bdda6120359e33300ee, just in a different way: after the rollback the post would still have an associated comment which claimed to be persisted, but which no longer existed in the database.
