### ISSUE TITLE
rails new . --with-bootstrap-latest ?

### ISSUE THREAD

**Issue by oystersauce8** [rails/rails#32857]
I've worked with many rails code bases, and very few of them had vue.js
Yet when I generate a new rails application today with rails 5, I can specify vuejs as a framework.

95% of rails apps I come across have some kind of bootstrap integration. So I think it's fair to
say it (bootstrap) is not an exotic framework, many new sites use it.

So it would be nice (imho) if the rails new command somehow provided an option to turn on or off the bootstrap frontend framework. (much like you can say no coffee script) 
Thus avoiding the need for a newly generated app to do the
`mv app/assets/stylesheets/application.css app/assets/stylesheets/application.scss` dance 
and
`@import "bootstrap";`
etc

Whatchu think?

**Comment by y-yagi** [comment]
Please use the [Rails Core mailing list](https://groups.google.com/forum/#!forum/rubyonrails-core) for feature requests, where a wider community will be able to help you. We reserve the Rails issue tracker only for bugs in Rails. Thanks.
