### ISSUE TITLE
Why is structure empty when table_name is not?

### ISSUE THREAD

**Issue by avineshwar** [rails/rails#32869]
https://github.com/rails/rails/blob/375a4143cf5caeb6159b338be824903edfd62836/activerecord/lib/active_record/connection_adapters/sqlite3_adapter.rb#L396

- It raises an exception and essentially I cannot move ahead. Please suggest a reasoning and remediation.

**Comment by matthewd** [comment]
Please use the mailing list or StackOverflow for questions/help, where a wider community will be able to help you. We reserve the issues tracker for issues only.
