### ISSUE TITLE
Activestorrage service_url missing default_url_options[:host]

### ISSUE THREAD

**Issue by johansmitsnl** [rails/rails#32866]
### Steps to reproduce

1. Create a new rails app 5.2.0
2. Add active storrage
3. Add model with attachment
4. Add file to the model
5. Create a helper that calls a on the attachment (or variant) the service_url

### Expected behavior
Give back a service url for the attachment

### Actual behavior
Raises an error that the host is not set

### System configuration
**Rails version**: 5.2.0

**Ruby version**: 2.5.1

Created a new app and activated activestorrage.
I want to create a service_url behind a protected link.

My test code is:
```ruby
User.avatar.variant(resize: '100x100').service_url
```
The error:
```
Missing host to link to! Please provide the :host parameter, set default_url_options[:host], or set :only_path to true
```
Do I miss something because normal url helpers like: `root_url` work as expected. In the documentation it does not mention this and it seems strange that I need to set it while for other url helpers it works fine.

**Comment by y-yagi** [comment]
It seems the same issue with https://github.com/rails/rails/pull/32350#issuecomment-380091447  
You should be using the `rails_blob_url` and `rails_representation_url` helpers to get public urls outside of controllers.

**Comment by johansmitsnl** [comment]
@y-yagi this works thnx, where can I find the documentation for these 2 helpers?

**Comment by y-yagi** [comment]
It is described in the [guide](http://edgeguides.rubyonrails.org/active_storage_overview.html). 
If the information seems to be missing, please create an update PR.

**Comment by johansmitsnl** [comment]
The `rails_representation_url` is not explained in the [guide](http://edgeguides.rubyonrails.org/active_storage_overview.html). But there is a difference in them correct?

I would like to make a PR but I don't understand fully how both helpers work in detail.

**Comment by oolzpishere** [comment]
I also need a document for rails_representation_url.
I use like this: rails_representation_url(image.variant(resize: "150"), only_path: true)
It's work.

**Comment by anasalsalah** [comment]
Hi, I tried using rails_representation_url in:


```
class Attachment < ApplicationRecord
  include Rails.application.routes.url_helpers
  ....  
  def with_uploaded_file
    tempfile = Tempfile.open([file.filename.to_s, File.extname(file.filename.to_s)]) do |file_temp|
      file_temp.binmode unless file.content_type =~ /text/
      require 'open-uri'
      # file_temp.write(open(file.service_url).read)
      file_temp.write(open(rails_representation_url(file, only_path: true)).read)
      file_temp
    end
    begin
      yield(tempfile)
    ensure
      tempfile.unlink
    end
  end
```

But I get this error:
`undefined method 'variation' for #<ActiveStorage::Attached::One:0x00007fe9bef5e560>`
