### ISSUE TITLE
Closed issue  #30566: I just got the same error and can replicate

### ISSUE THREAD

**Issue by iBrooks** [rails/rails#32873]
### Steps to reproduce
1. Create 4 tables:
    -issues
    -grow_issues
    -grows
    -harvests

2. set up the following relationships:
`class Issue < ApplicationRecord`
`has_many :grow_issues`
`has_many :grows, through: :grow_issues`
`has_many :harvests, through: :grows`

`class GrowIssue < ApplicationRecord`
`belongs_to :grow`
`belongs_to :issue`
`has_one :harvest, through: :grow`

`class Grow < ApplicationRecord`
`has_many :grow_issues, dependent: :destroy`
`has_many :issues through: :grow_issues`
`has_one :harvest, dependent: :destroy`

`class Harvest < ApplicationRecord`
`belongs_to :grow`
`has_many :issues, through: :grow`
`accepts_nested_attributes_for :issues`

3. Seed some random data

4. Call `.issues` and `.issue_ids` on your dummy harvest, both of those methods work.

5. Try to set `Harvest.issue_ids = [1, 2]` (or whatever you have for  issue ids), that's when you'll get the error.

### Expected behavior
Be able to establish a has_many-through-belongs_to relationship and read and write values 

### Actual behavior
The relationship works for reading but when trying to set new values an error is raised:
`ActiveRecord::HasManyThroughNestedAssociationsAreReadonly: Cannot modify association 'Harvest#issues' because it goes through more than one other association.`

### System configuration
**Rails version**:
5.1
**Ruby version**:
2.3.3

This issue was raised once before and someone wrote a script to replicate the error, but it doesn't seem to have gone anywhere. I just ran into it again and figured a second case might be helpful.

https://github.com/rails/rails/issues/30566

**Comment by utilum** [comment]
The script still reproduces on master. Why did you close the first issue?

**Comment by utilum** [comment]
Sorry, my mistake. So just to confirm: can reproduce on master.
