### ISSUE TITLE
`rails app:update` overrides `rails new` spring binstubs

### ISSUE THREAD

**Issue by vfonic** [rails/rails#32880]
### Steps to reproduce

1. Create a new rails app:

```sh
rails new summer
cd summer
rails app:update
```

2. Confirm all app:update prompts

### Expected behavior

Spring binstubs don't get removed.

### Actual behavior

Spring binstubs are removed from `/bin/rails` and `bin/rake` files.

### System configuration
**Rails version**:
5.2.0 (the same happens with the latest `master` (6.0.0.alpha)
**Ruby version**:
2.4.4

EDIT: Just by running `rails new` followed by `rails app:update` (both using 5.2.0), I get several changes. You can see the changes here: https://github.com/vfonic/summer/commit/50bf21188637bbfd6e47a6267143fc977013570b
This repo has two commits:
1. `rails _5.2.0 new ae`
2. `rails app:update`

**Comment by y-yagi** [comment]
Thanks for your issue.
This issue is being addressed by #32525. Please wait for the correspondence to be completed. Thanks.
