### ISSUE TITLE
Impossible to reassign HasOneAssociation without saving

### ISSUE THREAD

**Issue by richmolj** [rails/rails#32886]
### Steps to reproduce

Given a `has_one`:

```
class Post < ApplicationRecord
  has_one :author
end

class Author < ApplicationRecord
  belongs_to :post
end
```

This will cause a database update:

```ruby
post = Post.includes("author").first
post.author # id of 1
new_author = Author.last # id of 2
# Uh oh! This will cause a DB update even though false is passed!
post.association(:author).replace(new_author, false)
```

It looks like this is because we hit `transaction_if(save)` which will yield [even if the save argument is false](https://github.com/rails/rails/blob/master/activerecord/lib/active_record/associations/has_one_association.rb#L107).

Note that in other cases we won't save [because there is a guard](https://github.com/rails/rails/blob/master/activerecord/lib/active_record/associations/has_one_association.rb#L43). We only save in this case because [there is no guard when reassigning](https://github.com/rails/rails/blob/master/activerecord/lib/active_record/associations/has_one_association.rb#L37).

I believe the fix is to add `save &&` [here](https://github.com/rails/rails/blob/master/activerecord/lib/active_record/associations/has_one_association.rb#L37). I would be happy to make this change if I can get the go-ahead from this issue.

### Expected behavior

No database update should be made when the `save` flag is `false`

### Actual behavior

AR will make a DB update `nil`ing the foreign key.

### System configuration
**Rails version**: 5.2

**Ruby version**: 2.4.1p111

**Comment by kamipo** [comment]
Why are using `HasOneAssociation#replace` which is internal API directly?

**Comment by richmolj** [comment]
I would use any API that allows me to to assign a new model without causing a DB update. I am a creator if the [JSONAPI Suite](https://jsonapi-suite.github.io/jsonapi_suite) gem which does some automatic query building of the incoming request. We run into this issue in our [activerecord adapter](https://github.com/jsonapi-suite/jsonapi_compliable/blob/master/lib/jsonapi_compliable/adapters/active_record_sideloading.rb#L62-L67).

The premise is to load all the parents in the graph, then load all the children, then associate those objects. I am hitting this problem in trying to associate the objects. Because this is AR/ORM/Datastore agnostic, I do not use `includes`.

**Comment by kamipo** [comment]
How about using `#target`/`#target=`? It is used in eager loading/preloading in the AR internal.

https://github.com/rails/rails/blob/268dd6966ddc6f66bf09fb96046bd435e0515b6e/activerecord/lib/active_record/associations/preloader/association.rb#L43-L51

https://github.com/rails/rails/blob/268dd6966ddc6f66bf09fb96046bd435e0515b6e/activerecord/lib/active_record/associations/join_dependency.rb#L248-L263

**Comment by richmolj** [comment]
Sure, works for me. For your own sanity though, heads up on this behavior as it differs from the `replace` method of HasMany and [seems like it shouldn't work this way](https://github.com/rails/rails/blob/master/activerecord/lib/active_record/associations/has_one_association.rb#L72-L78). But `target` satisfies my need 👍
