### ISSUE TITLE
Bad documentation in ActionController::Parameters#fetch

### ISSUE THREAD

**Issue by Linuus** [rails/rails#32899]
I believe the documentation) for `ActionController::Parameters#fetch` seems to be wrong.

See: http://edgeapi.rubyonrails.org/classes/ActionController/Parameters.html#method-i-fetch where it states: "If the key can't be found, there are several options: [...] **if more arguments are given, then that will be returned**"

### Steps to reproduce

``` ruby
ActionController::Parameters.new(foo: "bar").fetch(:baz, {}).class
```

### Expected behavior

According to the docs, this should happen:

``` ruby
ActionController::Parameters.new(foo: "bar").fetch(:baz, {}).class
=> Hash
```

### Actual behavior
``` ruby
ActionController::Parameters.new(foo: "bar").fetch(:baz, {}).class
=> ActionController::Parameters
```

### System configuration
**Rails version**: 5.2.0

**Ruby version**: 2.5.1

Should it be added to the documentation that the value(s) are converted to an instance of ActionController::Parameters before they are returned?

If so, I can create a PR if you want.

**Comment by y-yagi** [comment]
Your point is correct.  If given arguments match `when Hash`, it converts to `ActionController::Parameters`. 

https://github.com/rails/rails/blob/d7edb8ecd0552635ea9631666abe910199ccf7c1/actionpack/lib/action_controller/metal/strong_parameters.rb#L571-L572 
https://github.com/rails/rails/blob/d7edb8ecd0552635ea9631666abe910199ccf7c1/actionpack/lib/action_controller/metal/strong_parameters.rb#L832-L844 


Can you create a PR?

**Comment by Linuus** [comment]
@y-yagi Done! https://github.com/rails/rails/pull/32925
