### ISSUE TITLE
ActiveStorage: add prefix for s3 bucket

### ISSUE THREAD

**Issue by vtm9** [rails/rails#32894]
Is there any way to add a prefix to bucket in amazon S3?
Something like this:

```ruby
class User < ApplicationRecord
  has_one_attached :avatar, prefix: 'user/avatars'
  has_many_attached :files, prefix: 'user/files'
end
```
Maybe update S3Service method:
```ruby
class Service::S3Service < Service
  def object_for(key, prefix)
    bucket.object("#{prefix}/#{key}")
  end
end
```
or store prefix with key in database?

**Comment by georgeclaghorn** [comment]
No, sorry. (See #32790.)

**Comment by vtm9** [comment]
@georgeclaghorn why no?
It will be very useful.

**Comment by vtm9** [comment]
Or can I change buckets for different models?

**Comment by vtm9** [comment]
@quaertym, use Shrine.It's great https://shrinerb.com/

**Comment by samgreen-spp** [comment]
For anyone that comes across this in Rails 5.2 here's what we did the get around this issue. We have a multi-tenanted system with s3 buckets that house data from multiple sources. Ideally we would love to also have the ability to specify a prefix per attachment but this does enough for our needs currently.
```
# lib/active_storage/service/tenant_s3_service.rb
# extend s3 service
require 'active_storage/service/s3_service'

module ActiveStorage
  class Service::TenantS3Service < Service::S3Service
    private

    def object_for(key)
      current_tenant = ActsAsTenant.current_tenant
      bucket.object File.join('attachments', "#{current_tenant.id}", key)
    end
  end
end
```
And then use this new service:
```
# storage.yml
amazon:
  service: TenantS3
  ...
```

**Comment by agiratech-saranrajg** [comment]
> For anyone that comes across this in Rails 5.2 here's what we did the get around this issue. We have a multi-tenanted system with s3 buckets that house data from multiple sources. Ideally we would love to also have the ability to specify a prefix per attachment but this does enough for our needs currently.
> 
> ```
> # lib/active_storage/service/tenant_s3_service.rb
> # extend s3 service
> require 'active_storage/service/s3_service'
> 
> module ActiveStorage
>   class Service::TenantS3Service < Service::S3Service
>     private
> 
>     def object_for(key)
>       current_tenant = ActsAsTenant.current_tenant
>       bucket.object File.join('attachments', "#{current_tenant.id}", key)
>     end
>   end
> end
> ```
> 
> And then use this new service:
> 
> ```
> # storage.yml
> amazon:
>   service: TenantS3
>   ...
> ```it gives error uninitialized constant ActiveStorage::Service::TenantS3Service::ActsAsTenant

**Comment by od-c0d3r** [comment]
> it gives error uninitialized constant ActiveStorage::Service::TenantS3Service::ActsAsTenant

You should replace it with your `Tenant` model
