### ISSUE TITLE
Ruby Sass End-of-Life: 26 March 2019

### ISSUE THREAD

**Issue by chriseppstein** [rails/rails#32896]
I'm not sure if the sass-rails issue queue is being actively monitored and maintained right now, so I'm filing this here for visibility. Feel free to close.

https://github.com/rails/sass-rails/issues/420

**Comment by guilleiguaran** [comment]
Thank you very much for opening this!!!

I think the current plan is to switch to sassc-rails based in libSass before of Rails 6.0 release

**Comment by guilleiguaran** [comment]
I see and also from sassc-rails:
https://github.com/sass/sassc-rails/blob/master/sassc-rails.gemspec#L26-L28

**Comment by chriseppstein** [comment]
> so that we can reuse portions of the Sprockets template

🤔 

https://github.com/rails/sprockets/blob/master/sprockets.gemspec#L30-L31

and in sprockets.

**Comment by chriseppstein** [comment]
cc: @bolandrm

**Comment by chriseppstein** [comment]
If someone can do a survey of other popular gems in the rails ecosystem and see if they depend on sass, it would be good to know what else has to change beyond the default rails install so there's a reasonable transition plan.

**Comment by matthewd** [comment]
> Rails needs a plan a plan to deal with this before the ruby version becomes unmaintained

I was expecting https://github.com/sass/dart-sass/issues/249 to solve this for us. Is that not a reasonable expectation?

**Comment by chriseppstein** [comment]
@matthewd Dart sass is written in Dart. It compiles to JavaScript. I'm not sure how it helps except to shell out to it or something. `sassc-rails` is Ruby, but it calls into c++ shared library, which has it's own benefits and drawbacks (including being mostly maintained by one developer who we hope doesn't burn out or get hit by a bus). The Ruby community currently has a fully functional, native implementation of Sass with no bugs in it. 65% of web developers use Sass. It's astounding to me that there's no one in the ruby community: no individual, no company, who wants to take up the mantle and help maintain Ruby Sass. But here we are. Whatever the rails team wants to do, we'll support that decision.

**Comment by matthewd** [comment]
> @matthewd Dart sass is written in Dart.

Indeed. My impression, however, was that the linked issue, entitled "Create a Ruby package that embeds Dart Sass", would yield a Ruby package. Am I as fundamentally confused as your reply suggests?

**Comment by chriseppstein** [comment]
@matthewd that doesn’t exist yet and seems aspirational. If rails prefers to use dart-sass over libsass, that’s fine but I think someone on the ruby/rails community needs to own the implementation. There’s certainly time for that project to be built and matured before ruby sass becomes unmaintained.

**Comment by guilleiguaran** [comment]
> 🤔
>
> https://github.com/rails/sprockets/blob/master/sprockets.gemspec#L30-L31
>
> and in sprockets.

Indeed, Sprockets' [SasscProcessor](https://github.com/rails/sprockets/blob/master/lib/sprockets/sassc_processor.rb#L7) and [SasscCompressor](https://github.com/rails/sprockets/blob/master/lib/sprockets/sassc_compressor.rb#L7) are depending on Sass also.

**Comment by xzyfer** [comment]
:wave: LibSass maintainer checking in say we're happy to help and answer an questions

**Comment by aried3r** [comment]
I just saw this and wondered if this decision might also affect https://github.com/rails/rails/pull/33079#issuecomment-400193687 in case no viable replacement option is found for sassc-rails?

**Comment by nex3** [comment]
Please note: the longstanding maintainer for the `sassc-ruby` gem has said [he doesn't currently have any plans](https://github.com/sass/sassc-ruby/issues/75#issuecomment-404610598) to migrate it away from depending on Ruby Sass. If that gem is going to be part of Rails' official support for Sass, someone needs to sign up to maintain it.

**Comment by chriseppstein** [comment]
@nex3 My reading of that issue is that the maintainer of sassc-ruby doesn't seem to be actively maintaining that package anymore. It seems like a bad idea to me for rails to adopt that gem without an active maintainer.

**Comment by oniofchaos** [comment]
I noticed there hasn't been any updates on this thread in a couple months. Has there been any undocumented progress?

Also, it was unclear from the chat, is it just the `sass-rails` gem that is impacted, or are there other gems that are also impacted?

**Comment by nex3** [comment]
> I noticed there hasn't been any updates on this thread in a couple months. Has there been any undocumented progress?

I believe there's progress updating `sassc-ruby` in this pull request: https://github.com/sass/sassc-ruby/pull/85. I don't know if there's any progress getting `sass-rails` updated to use `sassc-ruby`.

> Also, it was unclear from the chat, is it just the `sass-rails` gem that is impacted, or are there other gems that are also impacted?

Any gem that uses Ruby Sass will need to use `sassc-ruby` instead.

**Comment by rafaelfranca** [comment]
sprockets 4 already support sassc-ruby https://github.com/rails/sprockets/blob/master/lib/sprockets/sassc_processor.rb.

sass-rails is only a wrap around sprockets to add support to glob import and erb templates and scss generators. I'm not sure if those features will be things we want to support for the future. Even more if the module system proposal for the sass language is approved.

That being said for Rails 6 we would only need to remove the sass-rails gem and make sure sassc-ruby support in sprockets 4 is working properly.

**Comment by coorasse** [comment]
Rails 6 will also have Webpacker by default, which supports SCSS. This is a valid alternative, and so far is working nicely for me. I wrote a [guide to migrate stylesheets to Webpacker](https://medium.com/@coorasse/goodbye-sprockets-welcome-webpacker-3-0-ff877fb8fa79) if interested. In my last projects I use Webpacker for everything: JS, CSS, images and fonts.

**Comment by n-rodriguez** [comment]
>  In my last projects I use Webpacker for everything: JS, CSS, images and fonts.

Same here. Even in mail templates :)

**Comment by philayres** [comment]
I'm interested to know what is going to happen here. I have noticed in the last week or two that sassc and its dependency libsass have ended up being a requirement in one of my older projects (Rails 4.2) via another gem. This broke a recent upgrade, since the server I was moving to was unable to compile libsass during a bundle install.

The problem was that libsass requires GCC 4.6+ according to its docs. On the CentOS 6 server that I have to use for production, GCC is 4.4. Building a new GCC for this purpose was not an option.

OK, so none of that is actually an issue to be resolved by this discussion, but I would like to raise it.  There may be other very conservative organisations running CentOS 6, which is still supported for 2 years. sassc will be a challenge for those people if older Rails apps suddenly have a requirement for a component they may not be able to build.

**Comment by prusswan** [comment]
@philayres you need to lock to the older versions of respective gems. The centos issue is not new according to https://github.com/sass/libsass/pull/1623

**Comment by philayres** [comment]
@prusswan I missed that issue over on sass. Thanks for pointing it out. 

I only just noticed this issue as there was only a single gem I was using that had the sassc dependency. I'm ok holding that one back, but as the Rails stack starts to move forward I become less comfortable, since I'm sure I'd like the security fixes associated with current versions. If Rails picks sassc it is fine. It would just be nice to have some definitive communication from the team if that is the case. This issue still being active suggests that the final direction is not set yet.

**Comment by gssbzn** [comment]
`sassc-rails` has just added support to jruby as of https://github.com/sass/sassc-rails/pull/113
A less disrupting migration plan than `webpacker` may still be possible

**Comment by guilleiguaran** [comment]
We decided to make sass-rails a thin wrapper for sassc-rails, see https://github.com/rails/sass-rails/pull/424

**Comment by deivid-rodriguez** [comment]
Hi @guilleiguaran, just to make sure we're on the same page. You made `sass-rails` a tin wrapper for `sassc-rails` just to make the transition easier, but the recommended dependenciy for new applications is `sassc-rails` and no further development will be made on `sass-rails` and everything will happen on `sassc-rails`. Is this right?

If this is right, I can make a PR to change the default dependency for rails generators to be `sassc-rails`.
