### ISSUE TITLE
generate model creates bad migration with decimal field

### ISSUE THREAD

**Issue by marko-avlijas** [rails/rails#32891]
### Steps to reproduce

    rails new decimal_test
    cd decimal_test
    rails g model Product name 'price:decimal{12:2}' active:boolean
    
    cat db/migrate/*
    class CreateProducts < ActiveRecord::Migration[5.2]
      def change
        create_table :products do |t|
          t.string :name    
          t.decimal{12 :price
          t.boolean :active
    
          t.timestamps
        end
      end
    end

Just to be sure it's not a shell issue, I've replaced rails with echo

    echo g model Product name 'price:decimal{12:2}' active:boolean
    g model Product name price:decimal{12:2} active:boolean

Same happens if I use `bin/rails` instead of `rails`.

### Actual behavior
Migration contains bad ruby code

    t.decimal{12 :price

### System configuration
**Rails version**:
Rails 5.2.0

**Ruby version**:
ruby 2.4.4p296 (2018-03-28 revision 63013) [x86_64-linux]

**Comment by y-yagi** [comment]
You must use a comma instead of a colon.

```
$ bin/rails g model Product name "price:decimal{12,2}" active:boolean
```
