### ISSUE TITLE
scope argument requires inverse_of

### ISSUE THREAD

**Issue by ybakos** [rails/rails#32903]
### Steps to reproduce

Given I have two classes with a 1:M relationship:

```
class Task < ApplicationRecord
  belongs_to :project
end

class Project < ApplicationRecord
  has_many :tasks, dependent: :destroy
end
```

When I add a lambda literal as a `scope` argument to `has_many`:

```
class Project < ApplicationRecord
  has_many :tasks, -> { order "project_order ASC" }, dependent: :destroy
end
```

And I try to create associated objects and save them:

```
p = Project.new
p.tasks << Task.new
p.save # false, save failed
```

I receive a `false`, the objects are not saved, and none of the primary/foreign keys are set.

However, if I add the :inverse_of option to the `has_many` declaration, saving works as expected.

```
has_many :tasks, -> { order "project_order ASC" }, dependent: :destroy, inverse_of: :project
```

```
p = Project.new
p.tasks << Task.new
p.save # true
```

### Expected behavior

I expect the objects to save as usual.

### Actual behavior

Saving fails, as the validation on the `belongs_to` side does not have its foreign key value set and cannot save.

Successful assignment of primary/foreign keys and successful saving require adding the `:inverse_of` option to the `has_many` declaration.

```
has_many :tasks, -> { order "project_order ASC" }, dependent: :destroy, inverse_of: :project
```

### System configuration
**Rails version**: 5.1.6

**Ruby version**: 2.5.0

**Comment by kamipo** [comment]
It is the expected behavior (limitation) for automatic inverse_of.
See [3.5 Bi-directional Associations](http://guides.rubyonrails.org/association_basics.html#bi-directional-associations):

> Active Record supports automatic identification for most associations with standard names. However, Active Record will not automatically identify bi-directional associations that contain a scope or any of the following options:
>
> - :through
> - :foreign_key
