### ISSUE TITLE
Non-persisted attributes on ActiveRecord models do not properly track changes in Rails 5.2.0

### ISSUE THREAD

**Issue by wiegand** [rails/rails#32904]
In Rails 5.2.0, when defining the following model (following the [docs here](http://api.rubyonrails.org/classes/ActiveModel/Dirty.html), though to be fair this is using the `ActiveModel::Dirty` module directly, which doesn't appear to be broken in 5.2.0):

```ruby
class Person < ActiveRecord::Base
  define_attribute_method :first_name

  attr_reader :first_name

  def first_name=(value)
    first_name_will_change!
    @first_name = value
  end
end
```

I would expect calling `person.first_name = 'First Name'` on a new `Person`, and then calling the `changes` method to return `{  'first_name' => [nil, 'First Name'] }`.

This works as expected in Rails `5.1.5`.

### Steps to reproduce

Test file here: https://gist.github.com/wiegand/e456acaabd8b3fc2aa22d014c08a4005

### Expected behavior

`changes` method includes the model changes.

### Actual behavior

`changes` hash includes the changed attributes but the value is `nil`:

```ruby
person = Person.new
assert_equal person.changed?, false
person.first_name = 'First Name'
assert_equal person.changed?, true
assert_equal person.changes, 'first_name' => [nil, 'First Name']
# fails, actually equals 'first_name' => [nil, nil]
```

See above gist for context.

### System configuration
**Rails version**: 5.2.0

**Ruby version**: ruby 2.5.1p57 (2018-03-29 revision 63029) [x86_64-darwin17]

**Comment by y-yagi** [comment]
You can see following deprecated message when executing your script with Rails 5.1.

``` 
DEPRECATION WARNING: first_name is not an attribute known to Active Record. This behavior is deprecated and will be removed in the next version of Rails. If you'd like first_name to be managed by Active Record, add `attribute :first_name to your class. (called from first_name= at 32904.rb:39) 
```  

As per this message, you need to use `attribute` method. If change `Person` class as following, it works expectly. 

```ruby 
class Person < ActiveRecord::Base
  attribute :first_name
end
``` 
The doc you pointed to is an example when you do not use Active Record, so behavior behaves differently. Thanks.
