### ISSUE TITLE
Unhelpful Error Message after updating to Rails 5.2

### ISSUE THREAD

**Issue by CodingAnarchy** [rails/rails#32909]
### Steps to reproduce

```
class FooBar
    belongs_to :foo
end

class Foo
   has_many :baz, -> { uniq }, through: :qux
end
```

### Expected behavior

Error message to the effect of `uniq` is unsupported in scopes with Rails 5.  (I found this issue after updating from Rails 4.2.10.)

### Actual behavior

```
NoMethodError: undefined method `extending' for #<Array:0x00007fa8f6154b08>
Did you mean?  extend
from /Users/vision/.rvm/gems/ruby-2.5.1/gems/activerecord-5.2.0/lib/active_record/associations/builder/collection_association.rb:75:in `block in wrap_scope'
```

### System configuration
**Rails version**: 5.2.0

**Ruby version**: 2.5.1

**Comment by composerinteralia** [comment]
This might relate to https://github.com/rails/rails/pull/32846

**Comment by rafaelfranca** [comment]
You went straight from 4.2.10 to 5.2.0? I'm pretty sure 5.0 or 5.1 would show you a deprecation message.

**Comment by rafaelfranca** [comment]
Yeah, `uniq` was deprecated in 5.0 and removed in 5.1, so you should see the message. You can't upgrade straight from 4.2 and not expect that things are going to break in unhelpful ways.

**Comment by CodingAnarchy** [comment]
The issue didn't arise from the migration path - which did show me the deprecation message.  It was after the migration, when changes were made to the code based on people used to the Rails 4.2 syntax, and it not being very obvious that is what has happened.

I would expect that if someone used a removed syntax from a version of Rails that hasn't reached EOL, it would fail more cleanly than this, is all.

**Comment by rafaelfranca** [comment]
Ahh. I see, so yeah. I think #32846 would help.

**Comment by arturbersan** [comment]
You can substitute `uniq` to `distinct`

**Comment by tom-brown** [comment]
> You can substitute `uniq` to `distinct`

This did not work for me in Rails 5.2. Same error as uniq.

**Comment by LeoSatch** [comment]
substituing uniq to distinct wokred for me.

Thanks a lot.
