### ISSUE TITLE
Active storage: Image variant boolean options don't work as expected

### ISSUE THREAD

**Issue by lucfranken** [rails/rails#32917]
### Steps to reproduce

Using Rails 5.2.0

When following this example:

http://api.rubyonrails.org/classes/ActiveStorage/Variant.html

`avatar.variant(resize: "100x100", monochrome: true, flip: "-90")`

When I try to disable monochrome:

`avatar.variant(resize: "100x100", monochrome: false, flip: "-90")`

### Expected behavior

Image should be rendered as colored because I change that option.

### Actual behavior

It renders as monochrome.

This might make sense as it's a command line flag without the option to enter a value: 

https://www.imagemagick.org/script/command-line-options.php#monochrome

But that is not clear for the user of the command.

It may relate to minimagick which does support arguments which can be omitted:

https://github.com/minimagick/minimagick#combine-options

```ruby
image.combine_options do |b|
  b.resize "250x200>"
  b.rotate "-90"
  b.flip
end # the command gets executed
```

Here the flip option can be seen as an option without a value.

It's not clear what is the right intended and most logical way in Rails that's why opening this as an issue instead of a PR.

### System configuration
**Rails version**: 5.2.0

**Ruby version**: ruby 2.5.1p57 (2018-03-29 revision 63029) [x86_64-darwin17]

**Comment by kamipo** [comment]
Is this fixed by #32916?

**Comment by jacobsmith** [comment]
@lucfranken Just wanted to let you know I have an open PR to address this issue. If you need it to work sooner, feel free to monkey-patch locally based on the code in that PR. It's a relatively small change ( 4 places where commands can be interpolated - just need to guard against false / nil in those places).

**Comment by jacobsmith** [comment]
fixed via https://github.com/rails/rails/pull/32936
