### ISSUE TITLE
db:drop cannot be reenabled or executed twice

### ISSUE THREAD

**Issue by thisismydesign** [rails/rails#32929]
When executed multiple times or invoked after reenabling `db:drop` doesn't output (and I believe doesn't do) anything. Reproduced with sqlite3, mysql2 and postresql adapters.

### Steps to reproduce

Standalone Ruby gist to reproduce: https://gist.github.com/thisismydesign/737ab1af6154568b24fa4ef5131f9228

Execute via `rspec _rails#32929.rb` (or see `output.txt`).

### Expected behavior

```
Rake::Task["db:drop"].invoke
=> Database 'development' does not exist
Rake::Task["db:drop"].reenable
Rake::Task["db:drop"].invoke
=> Database 'development' does not exist
```

```
Rake::Task["db:drop"].execute
=> Database 'development' does not exist
Rake::Task["db:drop"].execute
=> Database 'development' does not exist
```

### Actual behavior

```
Rake::Task["db:drop"].invoke
=> Database 'development' does not exist
Rake::Task["db:drop"].reenable
Rake::Task["db:drop"].invoke
=> 
```

```
Rake::Task["db:drop"].execute
=> Database 'development' does not exist
Rake::Task["db:drop"].execute
=> 
```

### System configuration
**Rails version**:
Using rake 10.5.0
Using concurrent-ruby 1.0.5
Using i18n 1.0.1
Using minitest 5.11.3
Using thread_safe 0.3.6
Using tzinfo 1.2.5
Using activesupport 5.2.0
Using activemodel 5.2.0
Using arel 9.0.0
Using activerecord 5.2.0
Using bundler 1.16.1
Using diff-lcs 1.3
Using mysql2 0.5.1
Using rspec-support 3.7.1
Using rspec-core 3.7.1
Using rspec-expectations 3.7.0
Using rspec-mocks 3.7.0
Using rspec 3.7.0

**Ruby version**:
ruby 2.5.1p57 (2018-03-29 revision 63029) [x86_64-darwin17]

**Comment by Edouard-chin** [comment]
It's again not related to rails but to the default behavior of rake.

If you look at the code of the `db:drop` tasks 
https://github.com/rails/rails/blob/9f95767979579f5761cb0d2bcccb67f3662349c5/activerecord/lib/active_record/railties/databases.rake#L55-L56

It calls the `db:drop:_unsafe` tasks. Since you are running `db:drop` twice you need to reenable any tasks that gets called by db:drop

```ruby
Rake::Task['db:drop'].invoke
Rake::Task['db:drop'].reenable
Rake::Task['db:drop:_unsafe'].reenable
Rake::Task['db:drop'].invoke
```

I'm not too sure what's your use case but this looks to be a code smell and I'll advise to rethink twice on it :)

**Comment by thisismydesign** [comment]
Oh my.. thanks again!

I'm not sure if there's way to tell whether the task was executed or invoked but if so it might make sense to keep the chain rolling with the appropriate method call. But that is more of a convenience feature request so if no one else cares feel free to close.

My use case is to reproduce another issue with DB tasks using several test cases hence the need to reenable tasks. So nothing I'd do for a product but thanks for the warning. :)
