### ISSUE TITLE
Why plugin not insert to database?

### ISSUE THREAD

**Issue by daitranthanhhoa** [rails/rails#32944]
### Steps to reproduce
I create a plugin from:
http://guides.rubyonrails.org/v5.1/plugins.html

### Expected behavior
<h1><%=  hickwall = Hickwall.new
    hickwall.squawk("Hello World")
    hickwall.last_squawk %></h1>
Result: display: [squawk! Hello World] and insert 1 row to database.

### Actual behavior
Result: only display: [squawk! Hello World]  and not insert to database

### System configuration
**Rails version**: 5.1

**Ruby version**: 2.3.3
OS: Win 7, 64 bit

**Comment by utilum** [comment]
@daitranthanhhoa I am under the impression that you are a little quick to open issues. Have you read the guidelines on [support resources](http://edgeguides.rubyonrails.org/getting_started.html#what-s-next-questionmark) and [Reporting an Issue](http://edgeguides.rubyonrails.org/contributing_to_ruby_on_rails.html#reporting-an-issue) ?

**Comment by robin850** [comment]
Hi @daitranthanhhoa,

@utilum is right ; please only open issues for bugs you encounter with Rails and not specific problems you have with your code base. This issue tracker is only for bugs, thanks.
