### ISSUE TITLE
[ActiveStorage] `url_for` returns path, not URL

### ISSUE THREAD

**Issue by jacobsmith** [rails/rails#32948]
* I'm not sure if this is a bug, me not understanding the API, or something in between. If it is found to be a bug, I'd be happy to work on a PR if some direction can be given as to how to handle what would be a breaking API change.

### Steps to reproduce

Call `url_for` on an active storage object ( `url_for(user.avatar)` )

### Expected behavior

The returned string will be a fully qualified URL. ( eg. `https://myserver.com/rails_storage/blob/foobar` )

### Actual behavior

Only the path is returned:

`/rails_storage/blob/foobar`

### System configuration
**Rails version**: 5.2.0

**Ruby version**: 2.3.3p222

**Comment by georgeclaghorn** [comment]
This is a [documented](http://api.rubyonrails.org/classes/ActionView/RoutingUrlFor.html#method-i-url_for) quirk of `url_for`:

> Note that by default `:only_path` is `true` so you'll get the relative “/controller/action” instead of the fully qualified URL like “example.com/controller/action”.

To generate a fully-qualified URL, use `polymorphic_url(user.avatar)`.

**Comment by jacobsmith** [comment]
Ah, thank you @georgeclaghorn ! I missed that in the documentation somehow. :+1:

**Comment by dvanoni** [comment]
Would it be worthwhile to add a note about this to the Active Storage Overview guide page?

I believe a note about this could be beneficial for those (like myself) using Rails as an API. When returning a JSON response with a URL to a file, a fully-qualified URL probably makes the most sense. It took me a while to hunt down this issue and realize I needed to use `polymorphic_url` instead of `url_for` as the guide describes.

**Comment by michelson** [comment]
It seems rails 5.2.2 [has the oposite default for url_for, the default for only_path is false](https://api.rubyonrails.org/v5.2.2/classes/ActionDispatch/Routing/UrlFor.html#method-i-url_for), so now there is no way to generate relative path for an attachment

**Comment by michelson** [comment]
the following fails:

```
url_for(post.images.first, only_path: true)
```
ArgumentError: wrong number of arguments (given 2, expected 0..1)

**Comment by brunoprietog** [comment]
I agree that it would be good to document this in the overview active storage guide.

**Comment by unRARed** [comment]
thank you! `polymorphic_url` also worked for me. i agree with [brunoprietog](https://github.com/brunoprietog) this quirk should be added from https://edgeguides.rubyonrails.org/active_storage_overview.html. it seems strange to me that `url_for` would ever return a path, seems like that would be `path_for`.
