### ISSUE TITLE
Range#=== behavior changes in Ruby 2.6 revision 63453 triggers 3 failures

### ISSUE THREAD

**Issue by yahonda** [rails/rails#32945]
I already have opened https://bugs.ruby-lang.org/issues/14772 for this issue then I need some more information from Rails community to about Active Support implementation `Range#===`

### Steps to reproduce
* Install Ruby 2.6 dev [revision 63453](https://svn.ruby-lang.org/cgi-bin/viewvc.cgi?revision=63453&view=revision) or higher
```
$ cd activesupport
$ bundle exec ruby -w -Itest test/core_ext/range_ext_test.rb -n /test_should_compare/
```

### Expected behavior
It should pass as Ruby 2.5.1 does.

### Actual behavior
```ruby
$ bundle exec ruby -w -Itest test/core_ext/range_ext_test.rb -n /test_should_compare/
Run options: -n /test_should_compare/ --seed 26931

# Running:

F

Failure:
RangeTest#test_should_compare_other_with_exclusive_end [test/core_ext/range_ext_test.rb:72]:
Expected false to be truthy.


bin/rails test test/core_ext/range_ext_test.rb:71

F

Failure:
RangeTest#test_should_compare_identical_inclusive [test/core_ext/range_ext_test.rb:64]:
Expected false to be truthy.


bin/rails test test/core_ext/range_ext_test.rb:63

F

Failure:
RangeTest#test_should_compare_identical_exclusive [test/core_ext/range_ext_test.rb:68]:
Expected false to be truthy.


bin/rails test test/core_ext/range_ext_test.rb:67



Finished in 0.002792s, 1074.5925 runs/s, 1074.5925 assertions/s.
3 runs, 3 assertions, 3 failures, 0 errors, 0 skips
$
```
### System configuration
**Rails version**:master branch

**Ruby version**:ruby 2.6.0dev (2018-05-21 trunk 63475) [x86_64-linux]

**Comment by matthewd** [comment]
Sounds to me like we want (untested):

```diff
diff --git a/activesupport/lib/active_support/core_ext/range/include_range.rb b/activesupport/lib/active_support/core_ext/range/include_range.rb
index 7ba1011921..73b5f4619c 100644
--- a/activesupport/lib/active_support/core_ext/range/include_range.rb
+++ b/activesupport/lib/active_support/core_ext/range/include_range.rb
@@ -19,6 +19,16 @@ def include?(value)
         super
       end
     end
+
+    def cover?(value)
+      if value.is_a?(::Range)
+        # 1...10 includes 1..9 but it does not include 1..10.
+        operator = exclude_end? && !value.exclude_end? ? :< : :<=
+        super(value.first) && value.last.send(operator, last)
+      else
+        super
+      end
+    end
   end
 end
```

**Comment by yahonda** [comment]
Thanks for the suggestion.  I have implemented https://github.com/yahonda/rails/commit/3f30b14ae4205078c2c633dfd82cd9623c0df8b4 . 
Somehow  the `cover?` method defined in this file is not called.

I was having a similar idea by `alias_method :range?, :include?` https://github.com/yahonda/rails/commit/fb6344a524440fdb37c7d1dfe1d149c9976b7fd9 which also did not help.

**Comment by eugeneius** [comment]
It doesn't work because `===` now calls the native C implementations of `include?` and `cover?` directly, without going through the VM, so overriding those methods in Ruby doesn't change its behaviour.

https://bugs.ruby-lang.org/projects/ruby-trunk/repository/revisions/63453/diff

```ruby
$ RBENV_VERSION=2.5.1 irb
irb(main):001:0> class Range def include?(*) false end end
=> :include?
irb(main):002:0> (1..10).include?(5)
=> false
irb(main):003:0> (1..10) === 5
=> false

$ RBENV_VERSION=2.6.0-dev irb
irb(main):001:0> class Range def include?(*) false end end
=> :include?
irb(main):002:0> (1..10).include?(5)
=> false
irb(main):003:0> (1..10) === 5
=> true
```

https://github.com/rails/rails/pull/32938 seems like the only way we can restore the previous functionality.

**Comment by matthewd** [comment]
Oh, I see... previously `range_eqq` was calling the rubyland `include?` method via `rb_funcall`; it now calls `r_cover_p` directly. We'd need to also override `===` itself.

@nobu I'm not sure why it needs `range_include_internal`... it seems that function implements special cases where `cover?` semantics are allowed (like Integer), but if we're calling cover anyway, is that check still important? (Does this change retain `include?` semantics for strings only?)

(:heart: this change, btw 🙇)
