### ISSUE TITLE
Active Storage deleting files leaves empty directories

### ISSUE THREAD

**Issue by babalooi** [rails/rails#32943]
### Steps to reproduce
Call _delete_ method on the controller with the following code.
This is tested only on local storage.

``` ruby
def delete_document
  project = Project.find(params[:id])
  project.documents.find(params[:document_id]).purge
end
```

### Expected behavior
Folders along with files should be deleted.

### Actual behavior
The file is deleted, but folder remains empty.

### System configuration
**Rails version**: 5.2.0

**Ruby version**: 2.4.2p198

**Comment by georgeclaghorn** [comment]
Can you please elaborate on why this is a problem for you?

**Comment by babalooi** [comment]
After some time uploading and deleting there would be hundreds or thousand empty directories, depending on usage. I don't know just would be cleaner I suppose.

**Comment by arefaslani** [comment]
ActiveStorage name directories by first and second two characters of the blob `key` by default. It's possible that two blobs be similar in this characters, then the files go in the same folder! Besides traversing hundreds of empty directories for finding an image is not a good idea.

**Comment by georgeclaghorn** [comment]
We’re not likely to do anything about this. The empty directories have very little cost.

> It's possible that two blobs be similar in this characters, then the files go in the same directory!

That’s expected. We don’t intend to store only one blob per subdirectory.

> Besides traversing hundreds of empty directories for finding an image is not a good idea.

Active Storage doesn’t do that. 🤷‍♂️

**Comment by georgeclaghorn** [comment]
Sorry, on second read, I think I misinterpreted your comment.

Both of those obstacles are theoretically surmountable—we can tell when another blob is stored in the same directory, and we wouldn’t need to traverse “hundreds” of directories—but we’re still not likely to take on the complexity of cleaning up empty directories for little to no benefit.

**Comment by patleb** [comment]
It is practically surmontable as well and I don't see why freeing inodes would not be worthwhile or keeping a mess is preferable. Using `FileUtils.rmdir` would mitigate the race condition:

```ruby
# active_storage/service/disk_service/with_rmdir.rb
...
  def delete(key)
    super
    base_dir = File.join(root, folder_for(key))
    begin
      FileUtils.rmdir(base_dir)
      FileUtils.rmdir(File.dirname(base_dir))
    rescue Errno::ENOTEMPTY
      # Ignore not empty dir
    end
  end

  def delete_prefixed(prefix)
    super
    base_dir = path_for(prefix)
    begin
      FileUtils.rmdir(base_dir)
    rescue Errno::ENOTEMPTY
      # Ignore not empty dir
    end
  end
...
```

**Comment by patleb** [comment]
I didn't experienced other race conditions but, yes, I think that `IO.copy_stream` could raise an exception between the time the file descriptor is created and `File.mkdir_p` creates the path if the base directory is deleted. So basically you would have this sequence of operations: `FileUtils.mkdir_p`, `FileUtils.rmdir`, `IO.copy_stream` with the 2 first being atomic. So, I would suggest to rescue on the specific exception raised and execute `retry` in the rescue block with something like that:

```ruby
  def upload(*)
    super
  rescue Errno::ENOENT
    retry
  end
```

**Comment by georgeclaghorn** [comment]
Cool. I’m still :-1: on doing any of this to avoid a few empty subdirectories under the service root. You can write a cron job to sweep them up if they bother you.

**Comment by jbwl** [comment]
Leaving potentially hundreds of thousands of empty directories (depending one the scale of the application) is slowing down file system operations considerably.

The hint to purge them from a cronjob isn't helpful -> "race conditions"

**Comment by sebastianhegge** [comment]
another small cleanup script:
```
Dir.glob(Rails.root.join('storage', '**', '*').to_s).sort_by(&:length).reverse.each do |x|
  if File.directory?(x) && Dir.empty?(x)
    Dir.rmdir(x)
  end
end
```

**Comment by lazylester** [comment]
what is the reason a directory hierarchy is created for the stored files, vs. a single directory? This design decision seems to be the root of the issue.

**Comment by jbwl** [comment]
> what is the reason a directory hierarchy is created for the stored files, vs. a single directory? This design decision seems to be the root of the issue.

Have you ever tried to do File I/O in a directory with hundreds of thousands of files? I don't think this is an option, the initial design does make sense.

**Comment by lazylester** [comment]
@jbwl no I haven't tried to do File I/O in a directory with hundreds of thousands of files. What happens in this scenario? Is there a performance issue? How big is the performance issue? Is it mitigated by the same number of files in a directory tree? I don't know how the OS handles these situations.

**Comment by lazylester** [comment]
@jbwl I just tried creating a directory with 1000,000 files, with filenames 1 .. 1000000. I can do `cat 999999` and the contents are dumped with no perceptible delay. Is it possible that the posited performance problem is of little practical concern?

**Comment by sebastianhegge** [comment]
@lazylester getting files into such a structure is completely ok, that's a good approach for many files - and 1.000.000 files are not much. you can also not compare your file system with any other, there are very much parameters for file system performance like the storage system itself and also the file system. to avoid problems with many files, this way is a good software design decision.
but not to clean up with empty directories is a little bit 'dirty' ... but may be it's more expensive to clean up every time you delete a file than not doing this and leave the directories there ...
i think such a thing like a daily cron cleaning up would be the best solution ...

**Comment by lazylester** [comment]
@sebastianhegge I believe there can be a race problem with the cron job containing the script that you have previously suggested.

My 1000,000 file example just shows that, considering that we're talking about transferring files over the internet, the latency of file io in a directory with a large number of files is probably negligible. @jbwl implied that there would be a performance hit at 100's of thousands of files. My experiment does not corroborate that.

**Comment by jbwl** [comment]
> @jbwl implied that there would be a performance hit at 100's of thousands of files. My experiment  does not corroborate that.

Never said anything like that. Please don't misquote.

**Comment by patleb** [comment]
@lazylester, [this](https://stackoverflow.com/questions/466521/how-many-files-can-i-put-in-a-directory) might answer your question. Basically, they split the directory for supporting several file systems (which most are less relevant today, but still are easy to support by simply splitting).

**Comment by joelGarcia93** [comment]
@bsilberberg nice solution guy! :) thank you! it works like a charm

**Comment by lazylester** [comment]
@joelGarcia93 any of the solutions (including @bsilberberg or @sebastianhegge suggestions) that include checking for empty directories and then deleting them if empty have a potential race condition that can result in unintentionally deleting a directory that is not empty. Perhaps your luck will hold. Personally I wouldn't count on it.

**Comment by sebastianhegge** [comment]
@lazylester `Dir.rmdir()` only deletes a Directories if it's empty ([take a look](https://apidock.com/ruby/Dir/rmdir/class)). So the only race condition in my opinion is if a file will be created between the `Dir.empty?()` check and the `Dir.rmdir()` command - but without data lost.
Or do you see any other race condition?

**Comment by lazylester** [comment]
@sebastianhegge yes, that is the race condition as you describe, small but finite.
