### ISSUE TITLE
New feature for mattr_* and cattr_*

### ISSUE THREAD

**Issue by pinewong** [rails/rails#32950]
### Actual behavior
```ruby
module HairColors
  mattr_reader :hair_colors, default: [:brown, :black, :blonde, :red]
end

class Person
  include HairColors
end

Person.new.hair_colors # => [:brown, :black, :blonde, :red]
Person.hair_colors # => NoMethodError
```

### Expected behavior
```ruby
# ...
Person.new.hair_colors # => [:brown, :black, :blonde, :red]
Person.hair_colors # =>  [:brown, :black, :blonde, :red]
```

### Feature
Can we add the expected behavior above for Rails? Maybe we need change some source code:

```ruby
# rails/activesupport/lib/active_support/core_ext/module/attribute_accessors.rb
class_eval(<<-EOS, __FILE__, __LINE__ + 1)
  @@#{sym} = nil unless defined? @@#{sym}
  def self.#{sym}
    @@#{sym}
  end
EOS

# to this
class_eval(<<-EOS, __FILE__, __LINE__ + 1)
  module ClassMethods
    @@#{sym} = nil unless defined? @@#{sym}
    def self.#{sym}
      @@#{sym}
    end
  end

  def self.included(base)
    base.extend ClassMethods
  end

  extend ClassMethods
EOS
```

Is this OK?

### System configuration
**Rails version**: 5.2.0
**Ruby version**: 2.5.2

**Comment by qichunren** [comment]
This is what you want:


      #   class User
      #     include ActiveSupport::Configurable
      #     config_accessor :hair_colors do
      #       [:brown, :black, :blonde, :red]
      #     end
      #   end
      #
      #   User.hair_colors # => [:brown, :black, :blonde, :red]
      #   User.new.hair_colors # => [:brown, :black, :blonde, :red]

**Comment by pinewong** [comment]
@qichunren Thank you.
