### ISSUE TITLE
Supported version documentation inconsistent re security updates for v5.0

### ISSUE THREAD

**Issue by joevandyk** [rails/rails#32954]
https://rubyonrails.org/security/ seems to indicate 5.0 **will** get security updates:

> For major security issues, all release in the current major series, and the last release in the additional major series will receive patches and new versions. This is currently 5.2.x, 5.1.x, 5.0.x and 4.2.x.

http://guides.rubyonrails.org/maintenance_policy.html seems to indicate 5.0 **will not** get security updates.

> The current release series and the next most recent one will receive patches and new versions in case of a security issue.
> 
> These releases are created by taking the last released version, applying the security patches, and releasing. Those patches are then applied to the end of the x-y-stable branch. For example, a theoretical 1.2.3 security release would be built from 1.2.2, and then added to the end of 1-2-stable. This means that security releases are easy to upgrade to if you're running the latest version of Rails.
> 
> Currently included series: 5.2.Z, 5.1.Z.

**Comment by rafaelfranca** [comment]
The version on the guides is outdated because 5.2.1 was not released yet, which includes https://github.com/rails/rails/commit/b162116596b3481b811912c67c9fa9e94f965f8a. When 5.2.1 is released the guide will be updated.

**Comment by joevandyk** [comment]
Perfect, thanks!
