### ISSUE TITLE
Not-So-Intuitive behaviour of `optional: true` when using Inheritance

### ISSUE THREAD

**Issue by gosukiwi** [rails/rails#32953]
### Steps to reproduce

Given this code:

```ruby
class Page < ApplicationRecord
  belongs_to :book
end

class SpecialPage < Page
  belongs_to :book, optional: true
end
```

### Expected behavior
I expect `SpecialPage.new.valid?` to be `true`.

### Actual behavior
`SpecialPage.new.valid?` is `false`, it bubbles up to `Page` and `Page` fails the validation.

To try it, clone [this repo](https://github.com/gosukiwi/rails-bug-demo), then `$ rails c` and try doing `SpecialPage.new.valid?`. If you add `optional: true` to the `Page` `belongs_to` relationship, it works.

    $ git clone git@github.com:gosukiwi/rails-bug-demo.git && cd rails-bug-demo
    $ bundle install && bundle exec rails test test/models/special_page_test.rb

### System configuration
**Rails version**: 5.2.0

**Ruby version**: 2.3.3

**Comment by utilum** [comment]
Your script passes too. No problem validating.

**Comment by gosukiwi** [comment]
Yeah I tried running it myself and it does pass! This is weird. I added a test in [my repo](https://github.com/gosukiwi/rails-bug-demo), it's the same test in your script, but it fails there.

It's using Rails `5.2.0` . I will update that in the issue description.

**Comment by eugeneius** [comment]
The sample application works because it loads the framework defaults for Rails 5.2:
https://github.com/gosukiwi/rails-bug-demo/blob/96ca418733caa73079fd536d2e2151bd59fb4e6f/config/application.rb#L12

This is how `belongs_to_required_by_default` gets set to true:
https://github.com/rails/rails/blob/v5.2.0/railties/lib/rails/application/configuration.rb#L76

Those defaults aren't loaded in the bug report template, so neither of the associations are required.

**Comment by composerinteralia** [comment]
Confirmed this fails with `belongs_to_required_by_default` set to `true`

```rb
# frozen_string_literal: true

begin
  require "bundler/inline"
rescue LoadError => e
  $stderr.puts "Bundler version 1.10 or later is required. Please update your Bundler"
  raise e
end

gemfile(true) do
  source "https://rubygems.org"

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  gem "rails", github: "rails/rails"
  gem "sqlite3"
end

require "active_record"
require "minitest/autorun"
require "logger"

# This connection will do for database-independent bug reports.
ActiveRecord::Base.establish_connection(adapter: "sqlite3", database: ":memory:")
ActiveRecord::Base.logger = Logger.new(STDOUT)
ActiveRecord::Base.belongs_to_required_by_default = true


ActiveRecord::Schema.define do
  create_table :books, force: true do |t|
  end

  create_table :pages, force: true do |t|
    t.integer :book_id
  end
end

class Book < ActiveRecord::Base
end

class Page < ActiveRecord::Base
  belongs_to :book
end

class SpecialPage < Page
  belongs_to :book, optional: true
end

class BugTest < Minitest::Test
  def test_optional_belongs_to_without_association_presence_is_valid
    special_page = SpecialPage.create!

    assert_equal 1, SpecialPage.count
  end
end
```

**Comment by utilum** [comment]
This reproduces!
So a change may be needed to make a specific `optional: true` override `belongs_to_required_by_default`.

**Comment by matthewd** [comment]
> Those defaults aren't loaded in the bug report template, so neither of the associations are required.

That seems worth fixing :confused:

---

I think the answer here is going to be that we just don't support overriding associations by re-defining them in a subclass: to achieve this, you'd need to make the upper association optional, then define a manual validation that varies in the subclass.

**Comment by gosukiwi** [comment]
@matthewd 

> I think the answer here is going to be that we just don't support overriding associations by re-defining them in a subclass: to achieve this, you'd need to make the upper association optional, then define a manual validation that varies in the subclass.

I think that's a valid path. In that case, shouldn't a warning pop up? Something like: "Beware, the override is not doing what you think is doing" or "Avoid overriding relationships in subclasses".

**Comment by bobbytables** [comment]
Just hit this behavior in our application, I do like the idea of a warning if you're trying to override the optional attribute of an association.
