### ISSUE TITLE
 Why occur error: [Uncaught ReferenceError: $ is not defined] with coffee script?

### ISSUE THREAD

**Issue by daitranthanhhoa** [rails/rails#32964]
### Steps to reproduce
2 Unobtrusive JavaScript

> Not very DRY, eh? We can fix this by using events instead. We'll add a data-* attribute to our link, and then bind a handler to the click event of every link that has that attribute:
```
@paintIt = (element, backgroundColor, textColor) ->
  element.style.backgroundColor = backgroundColor
  if textColor?
    element.style.color = textColor
 
$ ->
  $("a[data-background-color]").click (e) ->
    e.preventDefault()
 
    backgroundColor = $(this).data("background-color")
    textColor = $(this).data("text-color")
    paintIt(this, backgroundColor, textColor)
```

`<a href="#" data-background-color="#990000">Paint it red</a><a href="#" data-background-color="#009900" data-text-color="#FFFFFF">Paint it green</a><a href="#" data-background-color="#000099" data-text-color="#FFFFFF">Paint it blue</a>`
--

http://guides.rubyonrails.org/working_with_javascript_in_rails.html

### Expected behavior
Set color when click link.

### Actual behavior
not set color and Occur error when debug: Uncaught ReferenceError: $ is not defined

### System configuration
**Rails version**:5.2

**Ruby version**:2.5

**Comment by y-yagi** [comment]
Please use the [mailing list](https://groups.google.com/forum/#!forum/rubyonrails-talk) or StackOverflow for questions/help, where a wider community will be able to help you. We reserve the issues tracker for issues only. Thanks.
