### ISSUE TITLE
Get remote IP from request using HTTP_X_FORWARDED_FOR merged local IP as well

### ISSUE THREAD

**Issue by Premanandh-S** [rails/rails#32961]
I am trying to get remote IP of the request using following method 
`@request.env["HTTP_X_FORWARDED_FOR"]`

Earlier it returns remote IP like
157.51.103.127

I didn't do any changes in code level and I'm not sure wether rails version is updated in production app. But now it returns remote IP like 
157.51.103.127,172.68.162.40 (remove IP comma local machine IP)

I don't know why **local machine IP** is added with remote IP with comma

Earlier I have load balancer in production app and later we removed load balancer due to SSL related issues and again we have added load balancer few days ago. I'm not sure this may be the reason that local IP is merged with remove IP. 

Rails version: Rails 5.0.3

Ruby version: ruby 2.4.1p111 (2017-03-22 revision 58053) [x86_64-linux]

Thanks in advance

**Comment by ChrisHampel** [comment]
The HTTP_X_FORWARDED_FOR is a comma-separated list in the form: 
client, proxy1, proxy2

please see https://en.wikipedia.org/wiki/X-Forwarded-For for more info

**Comment by matthewd** [comment]
Please use the mailing list or StackOverflow for questions/help, where a wider community will be able to help you. We reserve the issues tracker for issues only.
