### ISSUE TITLE
ActiveRecord: use a thread pool to insert fixtures

### ISSUE THREAD

**Issue by kevinburkeomg** [rails/rails#32960]
Currently activerecord/lib/active_record/fixtures.rb inserts fixtures one table at a time. However, this spends a lot of time waiting for I/O, and we may have/be able to take advantage of multiple connections to the database.

```ruby
        fixture_sets_by_connection.each do |conn, set|
          table_rows_for_connection = Hash.new { |h, k| h[k] = [] }

          set.each do |fs|
            fs.table_rows.each do |table, rows|
              table_rows_for_connection[table].unshift(*rows)
            end
          end
          conn.insert_fixtures_set(table_rows_for_connection, table_rows_for_connection.keys)

          # Cap primary key sequences to max(pk).
          if conn.respond_to?(:reset_pk_sequence!)
            set.each { |fs| conn.reset_pk_sequence!(fs.table_name) }
          end
```

Would it make sense to use a thread pool there, and then wait until the threads are joined? If you have a large number of fixtures and can utilize multiple connections to the database, it seems like this could provide a significant performance improvement.

I'd be happy to try to make the change.

**Comment by rafaelfranca** [comment]
Thank you so much for the issue but we don't take feature request on the issue tracker. We recommend you to try to implement the feature.

**Comment by kevinburkeomg** [comment]
Alright, apologies, I figured it would be better (and faster) to open an issue before trying to open a PR.

**Comment by rafaelfranca** [comment]
It is fine. Yeah, I think that is a good idea (and I think in Shopify we do this, or something similar to this). cc @Edouard-chin
