### ISSUE TITLE
Improves AR Forking Test

### ISSUE THREAD

**Issue by GeminPatel** [rails/rails#32974]
### Steps to reproduce

This gist below is copy of an existing [test case](https://github.com/matthewd/rails/blob/f32cff5563f2188e657aa2fd9f8513f0da4a49ca/activerecord/test/cases/connection_adapters/connection_handler_test.rb#L147) in AR

I suggest we add GC.start before the last assert, to make the test deterministic.
https://gist.github.com/GeminPatel/4c0ef392c754e653bf86411eedfd89d2

### Expected behavior
Should not pass ever on 5.1.0, 4.2.0.

### Actual behavior
The [tests](https://github.com/matthewd/rails/blob/f32cff5563f2188e657aa2fd9f8513f0da4a49ca/activerecord/test/cases/connection_adapters/connection_handler_test.rb#L147) pass sometimes on 5.1.0, 4.2.0. Try by changing the AR version in the gist

### System configuration
**Rails version**: 5.1.0

**Ruby version**: 2.3.1

PS: I am new, so please forgive in case I am over my head and wrong.

**Comment by matthewd** [comment]
Please use a pull request to suggest code changes.

I'm also not immediately following why a GC call there would affect the behaviour we're testing, so some further explanation would be helpful too.

**Comment by GeminPatel** [comment]
@matthewd Currently your [test case](https://github.com/matthewd/rails/blob/f32cff5563f2188e657aa2fd9f8513f0da4a49ca/activerecord/test/cases/connection_adapters/connection_handler_test.rb#L147) is testing that forking no longer affects the connections of parent process. You are able to test this because you handled the parents connection in your [commit](https://github.com/matthewd/rails/commit/f32cff5563f2188e657aa2fd9f8513f0da4a49ca). 

Even if you remove the connection handling, your test case will pass sometimes. I think this is because the parent connection is not always closed when the child process exit. To verify this I tried to add the [test](https://github.com/matthewd/rails/blob/f32cff5563f2188e657aa2fd9f8513f0da4a49ca/activerecord/test/cases/connection_adapters/connection_handler_test.rb#L147) in rails 4.2 and 5.1 and it sometimes pass.

GC.start will remove all the objects references of the child which will indeed close the parent's connection. That way we can sure that the test is testing what it needs to test.

Surely I will add a PR if you can confirm that I am making sense?

**Comment by GeminPatel** [comment]
@matthewd Please ignore. I am not able to reproduce this again in Rails as well as the gist that I provided. Sorry for waste of time.
