### ISSUE TITLE
How to protect from this (Evilginx).

### ISSUE THREAD

**Issue by johnunclesam** [rails/rails#32972]
How to protect from this?

https://breakdev.org/evilginx-advanced-phishing-with-two-factor-authentication-bypass/

I have many websites, in many technologies... I need a way to protect.

I'm wondering if there is just something like a check of suspicious IP activities in the aftermath.?

Just this? Really?

Can I check my SSL certificate? HSTS? Avoid using nginx from serving my site?

**Comment by matthewd** [comment]
Please use the mailing list or StackOverflow for questions/help, where a wider community will be able to help you. We reserve the issues tracker for issues only.
