### ISSUE TITLE
:Error: undefined method `match?'

### ISSUE THREAD

**Issue by Faizaankhan3** [rails/rails#32970]
https://github.com/rails/rails/blob/375a4143cf5caeb6159b338be824903edfd62836/actionpack/lib/action_dispatch/middleware/templates/rescues/invalid_statement.html.erb#L13

Getting below error in Ruby Version 2.3.3 and Rails version 5.2.0
Please have a look 

ActionView::Template::Error: undefined method `match?' for #<String:0x0055f37773e6f8>
Did you mean?  match
 .../.rvm/gems/ruby-2.3.3@*/gems/actionpack-5.2.0/lib/action_dispatch/middleware/templates/rescues/invalid_statement.html.erb:

**Comment by utilum** [comment]
`match?` was added in a later version of Ruby.
We may need to update the [guide](http://guides.rubyonrails.org/getting_started.html#installing-rails) as it currently says:
> Rails requires Ruby version 2.2.2 or later. If the version number returned is less than that number, you'll need to install a fresh copy of Ruby.

**Comment by utilum** [comment]
Added in Ruby 2.4: https://bugs.ruby-lang.org/issues/8110

**Comment by Faizaankhan3** [comment]
I thought ruby version 2.3.3 would be good for Rails 5.2.0. Please update the release note (http://guides.rubyonrails.org/5_0_release_notes.html) which says ruby 2.2.2+ is the requirement.

**Comment by y-yagi** [comment]
We have our own definition of `Regexp#match?` for old Rubies.
https://github.com/rails/rails/blob/5d5cbbe0b7ccb35860d8ee097f4213a807f9e92c/activesupport/lib/active_support/core_ext/regexp.rb#L3..L10

I guess that require is missing.

**Comment by y-yagi** [comment]
Oh, I was misunderstanding. We are defining `Regexp#match?`, but we did not define `String#match?`. In this case, we should not use `String#match?`.

**Comment by Faizaankhan3** [comment]
```# frozen_string_literal: true

class String #:nodoc:
  def match?(string, pos = 0)
    !!match(string, pos)
  end unless //.respond_to?(:match?)
end```

Probably adding a file in (https://github.com/rails/rails/tree/5d5cbbe0b7ccb35860d8ee097f4213a807f9e92c/activesupport/lib/active_support/core_ext/string) would solve the issue.

**Comment by utilum** [comment]
Actually... would it not be solved just by using `include?`

**Comment by faizaankhan** [comment]
@utilum  I saw your recent patch, it would be nice of you, if you could brief a bit to me, I could learn something ;)

```ruby
<% if @exception.message.match? %r{#{ActiveStorage::Blob.table_name}|#{ActiveStorage::Attachment.table_name}} %>
+<% if %r{#{ActiveStorage::Blob.table_name}|#{ActiveStorage::Attachment.table_name}}.match?(@exception.message) %>
```

**Comment by utilum** [comment]
@faizaankhan : as noted by @y-yagi  above, Active Support Core Extensions already support `Regexp#match?`, but not `String#match?`. Rails guide [explains this](http://guides.rubyonrails.org/active_support_core_extensions.html#match-questionmark).
The patch just swaps the expression from `"some_string".match?(/pattern/)` to `/pattern/.match?("some_string")`.
