### ISSUE TITLE
ActiveRecord::NoDatabaseError not raised

### ISSUE THREAD

**Issue by n-rodriguez** [rails/rails#32994]
Hi!

I'd like to know when `ActiveRecord::NoDatabaseError` exception is supposed to be raised?
Because it's not always the case. Sometimes I've got a `PG::ConnectionBad` exception which is pretty unexpected. Here a basic test case with Postgres and Mysql :

```ruby
# frozen_string_literal: true

begin
  require "bundler/inline"
rescue LoadError => e
  $stderr.puts "Bundler version 1.10 or later is required. Please update your Bundler"
  raise e
end

gemfile(true) do
  source "https://rubygems.org"

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  # Activate the gem you are reporting the issue against.
  gem "activerecord", "5.1.6"
  gem "pg"
  gem "mysql2"
end

require "active_record"
require "minitest/autorun"
require "logger"

# Ensure backward compatibility with Minitest 4
Minitest::Test = MiniTest::Unit::TestCase unless defined?(Minitest::Test)

class BugTest < Minitest::Test
  def test_bad_connection_with_postgres
    assert_raises ActiveRecord::NoDatabaseError do # got PG::ConnectionBad instead
      ActiveRecord::Base.establish_connection(adapter: "postgresql", database: "foo")
      ActiveRecord::Base.connection
    end
  end

  def test_bad_connection_with_mysql2
    assert_raises ActiveRecord::NoDatabaseError do
      ActiveRecord::Base.establish_connection(adapter: "mysql2", database: "foo")
      ActiveRecord::Base.connection
    end
  end
end
```

Thank you!

**Comment by utilum** [comment]
@daitranthanhhoa I am under the impression that you are a little quick to open issues. Have you read the guidelines on [support resources](http://edgeguides.rubyonrails.org/getting_started.html#what-s-next-questionmark) and [Reporting an Issue](http://edgeguides.rubyonrails.org/contributing_to_ruby_on_rails.html#reporting-an-issue) ?

**Comment by n-rodriguez** [comment]
> I am under the impression that you are a little quick to open issues. Have you read the guidelines on support resources and Reporting an Issue ?

I did. I don't know if it's actually a bug. But I need so enlightments on how it works as it's not in the documentation.

**Comment by utilum** [comment]
That said: `ActiveRecord::NoDatabaseError` is raised by ActiveRecord, and `PG::BadConnection` by the `pg` gem. What does your test demonstrate? Do you run it without having a database "foo" and get unexpected failures when the error message is `PG::BadConnection` ?

**Comment by n-rodriguez** [comment]
> What does your test demonstrate?

I thought it would raise `ActiveRecord::NoDatabaseError`.
Instead I get `PG::BadConnection`.

**Comment by n-rodriguez** [comment]
> Do you run it without having a database "foo"

Yes and get `PG::BadConnection` instead of a more abstract expection `ActiveRecord::NoDatabaseError`

**Comment by utilum** [comment]
Interesting :)
I see: 
```
  1) Failure:
BugTest#test_bad_connection_with_mysql2 [ri_32994.rb:37]:
[ActiveRecord::NoDatabaseError] exception expected, not
Class: <Mysql2::Error::ConnectionError>
Message: <"Access denied for user 'u'@'localhost' to database 'foo'">
```

time after time.

**Comment by n-rodriguez** [comment]
The case happens with the [Globalize gem](https://github.com/globalize/globalize/blob/master/lib/globalize/active_record/act_macro.rb#L48) when running `rake db:create`

**Comment by utilum** [comment]
When I stop the db servers, both tests fail with `PG::ConnectionBad` and `Mysql2::Error::ConnectionError`.

**Comment by n-rodriguez** [comment]
When running `rake db:setup` on my application during CI tests, it seems that `ActiveRecord::NoDatabaseError` is correctly raised and catched by Globalize, so the DB is correcly created and initialized. When running  `rake db:create` I get `PG::BadConnection` exception which is not catched by Globalize and crash the setup.

**Comment by utilum** [comment]
I don't know how Globalize gets into play, but this does inconsistent behaviour.
Is this a fair summary:
When trying to connect to a database that does not exist, you expect to consistently see either `ActiveRecord::NoDatabaseError`, or an error from the particular adapter gem.

**Comment by utilum** [comment]
By the tests we have for ActiveRecord the expectation is, as expressed in your reproduction, for `ActiveRecord::NoDatabaseError`.
I can reproduce the inconsistency on AR master as well.

However, I see `Mysql2::Error::ConnectionError`. @n-rodriguez sees `PG::ConnectionBad`.

Could this be related to differences in our local setup?

If so, good, because we each have a setup that breaks the expectation for each case :smile: 

For starts:
```
$ mysql --version
mysql  Ver 15.1 Distrib 10.2.14-MariaDB, for Linux (x86_64) using readline 5.1

$ psql -c "SELECT version();"
                                                   version                      
                             
--------------------------------------------------------------------------------
-----------------------------
 PostgreSQL 9.6.9 on x86_64-redhat-linux-gnu, compiled by gcc (GCC) 7.3.1 201803
03 (Red Hat 7.3.1-5), 64-bit
(1 row)
```

**Comment by utilum** [comment]
```
$ psql foo
psql: FATAL:  database "foo" does not exist
$ mysql foo
ERROR 1044 (42000): Access denied for user 'u'@'localhost' to database 'foo'
```

**Comment by n-rodriguez** [comment]
> I don't know how Globalize gets into play

Globalize has nothing to do with the current issue. It has just revealed it as it tries to get early DB access in application boot process.

**Comment by n-rodriguez** [comment]
> When trying to connect to a database that does not exist, you expect to consistently see either ActiveRecord::NoDatabaseError, or an error from the particular adapter gem.

I expect to see `ActiveRecord::NoDatabaseError` and not a PG or MySQL exception. IMHO it looks like a leaky abstraction.

**Comment by n-rodriguez** [comment]
BTW there is already a test to cover absent DB in ActiveRecord : https://github.com/rails/rails/blob/master/activerecord/test/cases/adapters/postgresql/postgresql_adapter_test.rb but as I said depending on what you're calling (`rake db:setup` or `rake db:create`) you got different exceptions.

**Comment by n-rodriguez** [comment]
MySQL:

|                   | DB exists | DB dont exist |
|-------------------|-----------|---------------|
|valid login/pass   |     OK    | Class: <Mysql2::Error::ConnectionError> Message: <"Access denied for user 'foo'@'localhost' to database 'foo2'"> |
|invalid login/pass | Class: <Mysql2::Error::ConnectionError> Message: <"Access denied for user 'foo2'@'localhost' (using password: YES)"> | Class: <Mysql2::Error::ConnectionError> Message: <"Access denied for user 'foo2'@'localhost' (using password: YES)">

**Comment by n-rodriguez** [comment]
Postgresql:

|                   | DB exists | DB dont exist |
|-------------------|-----------|---------------|
|valid login/pass   |     OK    | Class: <PG::ConnectionBad> Message: <"FATAL: database foo2 don't exist"> |
|invalid login/pass | Class: <PG::ConnectionBad> Message: <"FATAL: role foo2 don't exist"> | Class: <PG::ConnectionBad> Message: <"FATAL: role foo2 don't exist"> |

**Comment by n-rodriguez** [comment]
In regards of the tests I've made, errors raised when login/pass are invalid are pretty consistent. 
I don't know if they should be replaced by a more generic exception like `ActiveRecord::ConnectionError` but it's consitent with what's happening.
(About the more generic exception : IMHO when you write a lib that uses ActiveRecord like Globalize, you should not care about the underlying DB unless you really need to).

But I think there is something wrong (or not consistent) in the "valid login/pass with no DB" case.

**Comment by jagnarong** [comment]
How

**Comment by n-rodriguez** [comment]
> How

?

**Comment by n-rodriguez** [comment]
Hi there! The behavior still exists with Rails 5.2.1 : 

```ruby
# frozen_string_literal: true

begin
  require "bundler/inline"
rescue LoadError => e
  $stderr.puts "Bundler version 1.10 or later is required. Please update your Bundler"
  raise e
end

gemfile(true) do
  source "https://rubygems.org"

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  # Activate the gem you are reporting the issue against.
  gem "activerecord", "5.2.1"
  gem "pg"
  gem "mysql2"
end

require "active_record"
require "minitest/autorun"
require "logger"

# Ensure backward compatibility with Minitest 4
Minitest::Test = MiniTest::Unit::TestCase unless defined?(Minitest::Test)

class BugTest < Minitest::Test
  def test_bad_connection_with_postgres
    assert_raises ActiveRecord::NoDatabaseError do # got PG::ConnectionBad instead
      ActiveRecord::Base.establish_connection(adapter: "postgresql", database: "foo")
      ActiveRecord::Base.connection
    end
  end

  def test_bad_connection_with_mysql2
    assert_raises ActiveRecord::NoDatabaseError do
      ActiveRecord::Base.establish_connection(adapter: "mysql2", database: "foo")
      ActiveRecord::Base.connection
    end
  end
end
```

**Comment by matthewd** [comment]
`NoDatabaseError` is raised when we know the database doesn't exist. As you've found, we often don't know that because the DBMS doesn't let us get far enough to find out. 

You did describe one case where the DB server explicitly said the database wasn't there and we still didn't convert to the generic exception. That's because we do a string match for "doesn't exist", which is not what you claim the message was; I'm guessing it actually gave you a localized error which you translated for us and then forgot to mention?

I imagine _that_ can be fixed by having those rescues pass through `translate_exception`, and thus prefer the error code instead of the [possibly localized] message text.

**However**, that doesn't help Globalize, because there are plenty of connection errors that we don't want to cover up. That's better addressed from a different angle: error handling aside, it's very bad form for a model definition to cause a database connection. Globalize is designed incorrectly: it should not cause a database connection when loading the model definition, and should instead hook the model's `load_schema!` to run at the right time.

**Comment by n-rodriguez** [comment]
@matthewd : thanks for your detailed answer.

> I'm guessing it actually gave you a localized error which you translated for us and then forgot to mention?

It seems to be : 

```sh
nicolas@tchoum-desktop:~/PROJECTS/CONCERTO/concerto$ ruby test.rb 
Fetching gem metadata from https://rubygems.org/...............
Resolving dependencies...
Using concurrent-ruby 1.0.5
Using i18n 1.1.0 (was 1.0.1)
Using minitest 5.11.3
Using thread_safe 0.3.6
Using tzinfo 1.2.5
Using activesupport 5.2.1
Using activemodel 5.2.1
Using arel 9.0.0
Using activerecord 5.2.1
Using bundler 1.16.2
Using mysql2 0.5.2
Using pg 1.1.0
Run options: --seed 35988

# Running:

FF

Finished in 0.208430s, 9.5955 runs/s, 9.5955 assertions/s.

  1) Failure:
BugTest#test_bad_connection_with_postgres [test.rb:30]:
[ActiveRecord::NoDatabaseError] exception expected, not
Class: <PG::ConnectionBad>
Message: <"FATAL:  la base de donn\xC3\xA9es \xC2\xAB foo \xC2\xBB n'existe pas\n">
---Backtrace---
/home/nicolas/.rvm/gems/ruby-2.5.1/gems/pg-1.1.0/lib/pg.rb:56:in `initialize'
/home/nicolas/.rvm/gems/ruby-2.5.1/gems/pg-1.1.0/lib/pg.rb:56:in `new'
/home/nicolas/.rvm/gems/ruby-2.5.1/gems/pg-1.1.0/lib/pg.rb:56:in `connect'
/home/nicolas/.rvm/gems/ruby-2.5.1/gems/activerecord-5.2.1/lib/active_record/connection_adapters/postgresql_adapter.rb:684:in `connect'
/home/nicolas/.rvm/gems/ruby-2.5.1/gems/activerecord-5.2.1/lib/active_record/connection_adapters/postgresql_adapter.rb:215:in `initialize'
/home/nicolas/.rvm/gems/ruby-2.5.1/gems/activerecord-5.2.1/lib/active_record/connection_adapters/postgresql_adapter.rb:40:in `new'
/home/nicolas/.rvm/gems/ruby-2.5.1/gems/activerecord-5.2.1/lib/active_record/connection_adapters/postgresql_adapter.rb:40:in `postgresql_connection'
/home/nicolas/.rvm/gems/ruby-2.5.1/gems/activerecord-5.2.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:809:in `new_connection'
/home/nicolas/.rvm/gems/ruby-2.5.1/gems/activerecord-5.2.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:853:in `checkout_new_connection'
/home/nicolas/.rvm/gems/ruby-2.5.1/gems/activerecord-5.2.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:832:in `try_to_checkout_new_connection'
/home/nicolas/.rvm/gems/ruby-2.5.1/gems/activerecord-5.2.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:793:in `acquire_connection'
/home/nicolas/.rvm/gems/ruby-2.5.1/gems/activerecord-5.2.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:521:in `checkout'
/home/nicolas/.rvm/gems/ruby-2.5.1/gems/activerecord-5.2.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:380:in `connection'
/home/nicolas/.rvm/gems/ruby-2.5.1/gems/activerecord-5.2.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:1008:in `retrieve_connection'
/home/nicolas/.rvm/gems/ruby-2.5.1/gems/activerecord-5.2.1/lib/active_record/connection_handling.rb:118:in `retrieve_connection'
/home/nicolas/.rvm/gems/ruby-2.5.1/gems/activerecord-5.2.1/lib/active_record/connection_handling.rb:90:in `connection'
test.rb:32:in `block in test_bad_connection_with_postgres'
---------------

  2) Failure:
BugTest#test_bad_connection_with_mysql2 [test.rb:37]:
[ActiveRecord::NoDatabaseError] exception expected, not
Class: <Mysql2::Error::ConnectionError>
Message: <"Access denied for user 'nicolas'@'localhost' (using password: NO)">
---Backtrace---
/home/nicolas/.rvm/gems/ruby-2.5.1/gems/mysql2-0.5.2/lib/mysql2/client.rb:90:in `connect'
/home/nicolas/.rvm/gems/ruby-2.5.1/gems/mysql2-0.5.2/lib/mysql2/client.rb:90:in `initialize'
/home/nicolas/.rvm/gems/ruby-2.5.1/gems/activerecord-5.2.1/lib/active_record/connection_adapters/mysql2_adapter.rb:22:in `new'
/home/nicolas/.rvm/gems/ruby-2.5.1/gems/activerecord-5.2.1/lib/active_record/connection_adapters/mysql2_adapter.rb:22:in `mysql2_connection'
/home/nicolas/.rvm/gems/ruby-2.5.1/gems/activerecord-5.2.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:809:in `new_connection'
/home/nicolas/.rvm/gems/ruby-2.5.1/gems/activerecord-5.2.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:853:in `checkout_new_connection'
/home/nicolas/.rvm/gems/ruby-2.5.1/gems/activerecord-5.2.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:832:in `try_to_checkout_new_connection'
/home/nicolas/.rvm/gems/ruby-2.5.1/gems/activerecord-5.2.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:793:in `acquire_connection'
/home/nicolas/.rvm/gems/ruby-2.5.1/gems/activerecord-5.2.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:521:in `checkout'
/home/nicolas/.rvm/gems/ruby-2.5.1/gems/activerecord-5.2.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:380:in `connection'
/home/nicolas/.rvm/gems/ruby-2.5.1/gems/activerecord-5.2.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:1008:in `retrieve_connection'
/home/nicolas/.rvm/gems/ruby-2.5.1/gems/activerecord-5.2.1/lib/active_record/connection_handling.rb:118:in `retrieve_connection'
/home/nicolas/.rvm/gems/ruby-2.5.1/gems/activerecord-5.2.1/lib/active_record/connection_handling.rb:90:in `connection'
test.rb:39:in `block in test_bad_connection_with_mysql2'
---------------

2 runs, 2 assertions, 2 failures, 0 errors, 0 skips
```

> I imagine that can be fixed by having those rescues pass through translate_exception, and thus prefer the error code instead of the [possibly localized] message text.

It could be nice :)

> However, that doesn't help Globalize, because there are plenty of connection errors that we don't want to cover up. That's better addressed from a different angle: error handling aside, it's very bad form for a model definition to cause a database connection. Globalize is designed incorrectly: it should not cause a database connection when loading the model definition, and should instead hook the model's load_schema! to run at the right time.

I totally agree.

**Comment by Tensho** [comment]
>  should instead hook the model's load_schema! to run at the right time.
@matthewd Please could you give an example for `load_schema!` hooking? This method is not documented and uses internal API `attributes_to_define_after_schema_loads`.

**Comment by n-rodriguez** [comment]
@Tensho 

> Please could you give an example for `load_schema!` hooking?

I've got one : [royce/schema.rb](https://github.com/jbox-web/royce/blob/master/lib/royce/schema.rb).

It's pretty easy : `load_schema!` is a class method, override it when you need to create something in DB in early stage.
