### ISSUE TITLE
please can you give me advice how to create a new ruby project with post and get documents 

### ISSUE THREAD

**Issue by abderrahmen12345** [rails/rails#32993]
### Steps to reproduce

(Guidelines for creating a bug report are [available
here](http://edgeguides.rubyonrails.org/contributing_to_ruby_on_rails.html#creating-a-bug-report))

### Expected behavior
Tell us what should happen

### Actual behavior
Tell us what happens instead

### System configuration
**Rails version**:

**Ruby version**:

**Comment by rafaelfranca** [comment]
Please use StackOverflow for questions/help, where a wider community will be able to help you. We reserve the issues tracker for issues only.
