### ISSUE TITLE
"Rails 5 requires Ruby 2.2.2 or newer" when running Ruby 2.2.10p489

### ISSUE THREAD

**Issue by delner** [rails/rails#32990]
Attempting to load a Rails 5 environment while running Ruby 2.2.10 results in the following error:

```
Rails 5 requires Ruby 2.2.2 or newer.

    You're running
      ruby 2.2.10p489 (2018-03-28 revision 63023) [x86_64-linux]

    Please upgrade to Ruby 2.2.2 or newer to continue.
```

We encountered this issue while using [Rails 5 in our CI pipeline](https://circleci.com/gh/DataDog/dd-trace-rb/2910)

Problem stems from [this line](https://github.com/rails/rails/blob/32f7491808d2c4e097ed7b3ee875e4d1cea8c442/railties/lib/rails/ruby_version_check.rb#L1) which does a String comparison:

```
if RUBY_VERSION < '2.2.2' && RUBY_ENGINE == 'ruby'
```

When version is `"2.2.10"` or greater, the check fails. If you pass it `"2.2.9"` the check passes.

### Steps to reproduce

1. Run `ruby:2.2.10` Docker image with `docker run -it --rm ruby:2.2.10 /bin/bash`
2. Install Rails
3. Run `irb`
4. Do `"2.2.10" < "2.2.2"`, see that it evaluates to `true`.
4. Do `"2.2.9" < "2.2.2"`, see that it evaluates to `false`.

### Expected behavior

It should not raise an error for Ruby 2.2.10.

### Actual behavior

It raises an error for Ruby 2.2.10 and kills the application.

### System configuration
**Rails version**: 5.1.5

**Ruby version**: 2.2.10 MRI.

**Comment by delner** [comment]
Whoops, this might have already been fixed in https://github.com/rails/rails/commit/b39f89cca44a654d8378f79a2eae15eb02679541#diff-319ab2dfb61a2a5e10fafefb485af272

**Comment by rafaelfranca** [comment]
Thanks for the issue. Yes, it is, and it is already present on 5.1.6. Make sure you are in the last patch release.
