### ISSUE TITLE
Incorrect OR behavior in joins with merge

### ISSUE THREAD

**Issue by dzirtusss** [rails/rails#33002]
### Steps to reproduce
This is extract from more complex model to illustrate:
```
class Listing < ApplicationRecord
  def self.available
    _dead_code = CalendarDay.joins(:listing).merge(Listing.where(some_option: true)).
                   or(CalendarDay.joins(:listing).merge(Listing.where(some_option: true)))
     all
  end
end

Listing.available # works
Listing.joins(:owner).available # raises incompatible join error
```
Above dead code is raising `ArgumentError: Relation passed to #or must be structurally compatible. Incompatible values: [:joins]`

Error happen when:
1. proceeding joins e.g. `Listing.joins(:owner)`
2. using `.or`
3. using `joins(...).merge(Model.where(some_option: ...))`. Originally that was `Model.some_scope` of cause.

Error happen even with *DEAD* code (meaning not chained in scope chain) as shown above.

### Expected behavior

Should not raise error.

### Actual behavior
Above dead code is raising `ArgumentError: Relation passed to #or must be structurally compatible. Incompatible values: [:joins]`

### System configuration
**Rails version**: 5.1.5

**Ruby version**: 2.4.3

**Comment by jagnarong** [comment]
Good

**Comment by y-yagi** [comment]
Can you create a reproduce script with this [template](https://github.com/rails/rails/blob/master/guides/bug_report_templates/active_record_master.rb)?
