### ISSUE TITLE
Documentation on Queuing system contains no details at all about the queuing system

### ISSUE THREAD

**Issue by Tectract** [rails/rails#33011]
Please help. Refer to:

https://github.com/rails/rails/issues/33009
https://github.com/rails/rails/issues/33010
https://stackoverflow.com/questions/29169994/where-do-i-enqueue-jobs-into-activejob-in-rails-4-2/50571535#50571535

I have specifically asked for rafaelfranca not to close this issue. I don't appreciate my issues being force-closed with no help at all and being referred off of github.com for help with this repo.

-------

I'm trying to learn about how to enqueue jobs into Rails as a "background" task, and the documentation on this topic is really not clear. Maybe someone can help me, and help update the docs. From here:

http://guides.rubyonrails.org/active_job_basics.html

    How to enqueue jobs.
    Enqueue a job like so:
    GuestsCleanupJob.perform_later guest

Ok. What file should that function go into? Does it get called when the server starts? When does it get called? I want a function that will get called when the server starts. How do I do that?

    Rails itself only provides an in-process queuing system, which only keeps the jobs in RAM. If the process crashes or the machine is reset, then all outstanding jobs are lost with the default async backend.

Yep, that's exactly what I want. How do I use the "in-process" queuing system to start a function that will run in RAM? There is no detail about that in the docs, it appears. I would like to not have to call every one of my "background" processes by hand when I start my server...

**Comment by rafaelfranca** [comment]
See https://github.com/rails/rails/issues/33009#issuecomment-392588443
