### ISSUE TITLE
User questions are being off-loaded to StackOverflow

### ISSUE THREAD

**Issue by Tectract** [rails/rails#33010]
I don't approve of you guys off-loading user questions and issues about documentation lacking detail onto StackOverflow. 

I think you guys should let the experts, i.e. actual rails devs, answer user questions. I'm really tired of searching on Google and finding a thousand StackOverflow articles, all asking the same or nearly the same question, and being led astray, referred to other sources, being told they need to do something else instead or being questioned about their motivations, or just trailing off and not being addressed or answered for months. StackOverflow is a bad site and their moderators are horrible people, they are deletionists not archivists like Github! That's why we use GITHUB to talk to repo maintainers and code experts involved with a project!

Please, will someone help me instead of just force-closing my issue begging for help?
https://github.com/rails/rails/issues/33009

**Comment by utilum** [comment]
@Tetracat, this is not the place for user questions, but for [issues](http://guides.rubyonrails.org/contributing_to_ruby_on_rails.html#reporting-an-issue).

Have a look at: [support resources](http://guides.rubyonrails.org/getting_started.html#what-s-next-questionmark).

**Comment by Tectract** [comment]
The issue is that there is a major hole in the documentation. You guys are loathe to just answer a simple user question, aren't you? I can't honestly believe you would point new-comers to StackOverflow as a resource. That is like, a total abdication of any responsibility for helping them at all. You should be ashamed, honestly, it's like throwing them to the wolves. "Just use Google" is not a valid answer from the developers of the repository! You were supposed to help us, not insult us and force-close our issues.

**Comment by Tectract** [comment]
Secondly, if you are using StackOverflow to answer user questions, you should stop and start using Github instead, simply for the reason that StackOverflow auto-locks threads and they are deletionists rather than archivists like github. Repo questions should follow the repo and stay with it.

**Comment by rafaelfranca** [comment]
See https://github.com/rails/rails/issues/33009#issuecomment-392588443
