### ISSUE TITLE
Are there alternatives to delegating 'as' to Arel ?

### ISSUE THREAD

**Issue by genezys** [rails/rails#33015]
### Steps to reproduce

I have the following code that allows me to add computed fields to my models in order to sort and search using basic Active Record queries:

```ruby
# in ApplicationRecord
def self.with_computed_column(*selects)
  from select("#{quoted_table_name}.*").select(*selects).as(quoted_table_name)
end

# usage in model User
default_scope do
  with_computed_column("CONCAT(users.firstname, ' ', users.lastname) as fullname")
end

# then
User.where(fullname: "...").order(:fullname)
```

The idea is to replace the original `from` by a sub-SELECT adding the new field. But I need to alias this sub-SELECT using `as(quoted_table_name)` in order to use it with `from`, otherwise ActiveRecord will not find my fields.

This solution works fine but I have lots of warnings about the deprecation of calling `as` on the result of the `select`: `DEPRECATION WARNING: Delegating as to arel is deprecated and will be removed in Rails 6.0.`

Are there any alternatives to using `as` the way I do that will still be compatible with what I want to achieve? 

Or are there any alternatives to how I add computed fields to my models that will still allow me to use ActiveRecord queries?

If not, would it be possible to add an explicit delegation to Arel for `as` that will not trigger the warning, and will be kept in Rails 6?

Thanks

### System configuration
**Rails version**: 5.2.0

**Ruby version**: 2.5.1

**Comment by y-yagi** [comment]
The `as` is a method of Arel, but Arel is not public API of Rails. Behavior when calling directly from Rails is not guaranteed. 
So, please consider modifications that do not use `as`. Thanks.

**Comment by genezys** [comment]
To answer my own question if someone finds it: `from` accepts a second parameter that will be used as the sub-select alias, so ne need to use `as` from Arel.

So instead of:
```ruby
def self.with_computed_column(*selects)
  from select("#{quoted_table_name}.*").select(*selects).as(quoted_table_name)
end
```

Do this:
```ruby
def self.with_computed_column(*selects)
  from select("#{quoted_table_name}.*").select(*selects), quoted_table_name
end
```

**Comment by vbyno** [comment]
If someone need `.as` method but doesn't use `from`, which accepts a second parameter. The relation could be converted to arel before calling `.as`:
```ruby
select("#{quoted_table_name}.*").select(*selects).arel.as(quoted_table_name)
```
