### ISSUE TITLE
Memory leak when render JSON with 'render :inline'

### ISSUE THREAD

**Issue by bitato** [rails/rails#33019]
### Steps to reproduce

On a dummy rails application, define the action:
```rails
def index
    @people = Person.all
    render :inline => @people.to_json
end
```
Stressing the application with this action will cause a Java "out of memory" after few thousands of invocations. By analyzing the memory dump, I see that the GC can't release much of the memory.

### Expected behavior
Expected that this simple action don't cause crash of the application after few thousands of invocations.

### Actual behavior
The memory used by application will grow up indefinitely, and the GC can't release it.
In my application I "fix" this behavior by replacing the "render :inline" with "render :json" (by the way, it seems the most correct way).

### System configuration
**Rails version**: 4.0.13, 4.2.10

**Ruby version**: jruby-1.7.26, jruby-9.1.13

**Comment by y-yagi** [comment]
Rails 4.2 is only supported for severe security issues. 
Can you check whether this issue occurs even with the latest version?

**Comment by bitato** [comment]
Yes, I confirm the same behavior with Rails 5.0.7 and 5.1.6.

**Comment by schneems** [comment]
Can you give me an example application that reproduces the issue?

You can use derailed_benchmarks to profile it. I wrote about this here you have to scroll a bit https://blog.codeship.com/debugging-a-memory-leak-on-heroku/

**Comment by rafaelfranca** [comment]
That is by design. The template object is cached in memory and this why your memory only grows. When you use the inline option it is equivalent to generate a new file inside app/views.
