### ISSUE TITLE
ActionDispatch::Journey::Pattern::MatchData - NoMethodError (undefined method `+' for nil:NilClass)

### ISSUE THREAD

**Issue by jboler** [rails/rails#33026]
### Steps to reproduce
I haven't been able to reproduce this locally. As with #23699 this issue is thread safe related so it's tricky to consistently reproduce. I believe this issue is directly related to #23699 because I'm seeing that error in the logs as well.

In production, after some non-specific amount of time running error free, we start seeing this exception. I'm guessing it starts after the JVM has fully warmed up.

Restarting puma temporarily resolves the issue until it comes back.

### Expected behavior
No exception should be thrown in a multi threaded environment.

### Actual behavior

    NoMethodError (undefined method `+' for nil:NilClass)
    actionpack-5.1.5/lib/action_dispatch/journey/path/pattern.rb:138→ []

Stack trace: https://gist.github.com/jboler/7987bcf1e81ac33c4b83736a9f796552

### System configuration
Rails 5.1.5
jRuby 9.1.17.0
Puma 3.11.4-java in single mode with 16 threads

`config.eager_load = true` is set in production.

**Comment by kkworden** [comment]
Has this since been fixed?

**Comment by jboler** [comment]
The fix is on 5.2.1.rc1

**Comment by prcongithub** [comment]
Is this fix available on 5.2.0? I am getting this same error on JRuby-9.2.6.0, Rails-5.2.0, Puma 3.11.2
