### ISSUE TITLE
Active Storage with config.reload_classes_only_on_change slows the image loading quite a lot

### ISSUE THREAD

**Issue by Pacn91** [rails/rails#33021]
### Steps to reproduce
Vagrant box (ubuntu xenial) with rails (5.2.0) development server 
In development.rb environment config: 

> config.reload_classes_only_on_change = false

### Expected behavior
Until now, I used that command so the box could detect any change on my files and I do not have to restart the server. An expected behavior is using Active Storage to upload images, and getting these images should be pretty fast.

### Actual behavior
Images loading takes up to 40sec to load and the server gets quite slow. If I remove the command above mentioned, the server works fine and the image loading is normal again.
Is there another way to tell vagrant that files changed without that command? 

### System configuration
**Rails version**: 5.2.0

**Ruby version**: 2.3.1p112

**Vagrant Box**: jadesystems/rails-5-2

**Comment by rafaelfranca** [comment]
Most of the core team is not vagrant user so I'd guess you would be very helpful if you could investigate why this is being slow exactly.

**Comment by Pacn91** [comment]
Hi,

After questioning the owner of the box I've been using, he gave me this alternative that works:

At the bottom of the ``config/environments/development.rb`` I did this change:

Find this line at the bottom of the file and comment out:
``config.file_watcher = ActiveSupport::EventedFileUpdateChecker``

Then add this line:
``config.file_watcher = ActiveSupport::FileUpdateChecker``

So it looks like this: 
``# config.file_watcher = ActiveSupport::EventedFileUpdateChecker``
``config.file_watcher = ActiveSupport::FileUpdateChecker``

Now it works properly and I do not have to use this command anymore:
 ``config.reload_classes_only_on_change = true``

Best regards!
