### ISSUE TITLE
Errors#added? API changed from 5.1 to 5.2

### ISSUE THREAD

**Issue by jdzak** [rails/rails#33023]
[rails_5_2_0_errors_added_bug.rb.zip](https://github.com/rails/rails/files/2054921/rails_5_2_0_errors_added_bug.rb.zip)

### Steps to reproduce

1. Create a rails model with a field having a presence validation
2. Don't populate the field
3. Call `model.valid?`
4. Check if the model object has the presence error (it should). `model.errors.added?(:field, :blank) => true` 
5. Copy errors from the model to a form object
6. Check if the form object has the presence error (it should, but it doesn't). `form_object.errors.added?(:field, :blank) => false` 😢 

### Expected behavior
I want to use `form_object.added?(:field, :blank)` to return true if my field has a presence error.

### Actual behavior
In rails 5.2.0, `form_object.added?(:field, :blank)` returns false.
In rails < 5.2.0, `form_object.added?(:field, :blank)` returns true.

### System configuration
**Rails version**: 5.2.0

**Ruby version**: 2.4.3

**Comment by rafaelfranca** [comment]
How are you copying the errors to the form object?

**Comment by rafaelfranca** [comment]
Ah. I see. You are copying the error by iterating over all the errors and reading them to the new object. This will not going to work and it was working before by mistake. The fix is #31117. You should copy the errors using the `details` instead of the `error` messages.

**Comment by jdzak** [comment]
Hmm, I tried to switch to using the `details`, but no luck. Did I do this right?

```
class PostForm
  include ActiveModel::Model
  attr_accessor :text

  def initialize(post)
    @post = post
  end

  def copy_errors
    @post.errors.details.each do |k,v|
      errors.add(k,v)
    end
  end
end
```

**Comment by rafaelfranca** [comment]
Not really `details` returns a hash with arrays as items.

```
person.errors.details
# => {:name=>[{error: :not_implemented}, {error: :invalid}]}
```

So I think it would be:

```
def copy_errors
    @post.errors.details.each do |k,v|
      v.each do |error|
        errors.add(k,error[:error], *error.except(:error))
      end
    end
end
```

Or maybe just

```
def copy_errors
  errors.copy!(@post.errors)
end
```

But this last one is private API of the framework and can change or be removed anytime without notice.

**Comment by jdzak** [comment]
Another option could be to use the `Errors#merge` method (which is public). 

```
def copy_errors
  errors.merge!(object.errors)
end
```
