### ISSUE TITLE
Variant syntax for loading into memory differs from normal image

### ISSUE THREAD

**Issue by CodingAnarchy** [rails/rails#33037]
### Steps to reproduce

```ruby
class Foo
  has_one_attached :image
end

<get foo instance with attached image>
raw_blob = foo.image.variant(resize: "100x100^").processed.download
```

### Expected behavior

The resized image should be loaded into memory (`raw_blob`).

### Actual behavior

`NoMethodError: undefined method 'download' for #<ActiveStorage::Variant:0x00007ff09013a7a8>`

This can be resolved with a `foo.image.variant(resize: "100x100^").processed.blob.download`, but this will actually fetch the newly uploaded file again, so it is a big performance hit to do this.

### System configuration
**Rails version**: 5.2.0

**Ruby version**: 2.5.1

**Comment by georgeclaghorn** [comment]
`ActiveStorage::Variant` doesn’t have a documented `download` method. If you want to add it, please feel free to open a PR.
