### ISSUE TITLE
Passing `head()` an invalid symbol doesn't give a useful error

### ISSUE THREAD

**Issue by searls** [rails/rails#33035]
### Steps to reproduce

Given a conventional controller:

```ruby
class ItemsController < ApplicationController
  def index
    head :invalid_thing
  end
end
```

And a request like:

```
$ curl -I http://localhost:3000/items
```

### Expected behavior

I'd expect an application error like:

```
Error: `:invalid_thing` is an invalid value for the `head()` function. See Rack::Utils::SYMBOL_TO_STATUS_CODE for valid values.
```

Ideally, I'd see this error in both the logs and a rendered HTML error page.

### Actual behavior

A few things:

First, the request (of course) returns a 500 (which is in a twisted way, surprising, given that if someone had called `head :not_authorized` instead of the correct `head :unauthorized`, they might conclude the status code they're getting is just _wrong_ and not that an error occurred in processing the request)

Second, the reason someone might reach the above mistaken conclusion (and why I did, initially) is because the logs only print:

```
Started HEAD "/items" for 127.0.0.1 at 2018-05-31 12:09:13 -0400
Processing by ItemsController#index as */*
Completed 500 Internal Server Error in 0ms
```

Which is virtually identical to a successful call to `head()`:

```
Started HEAD "/items" for 127.0.0.1 at 2018-05-31 12:09:39 -0400
Processing by ItemsController#index as */*
Completed 401 Unauthorized in 0ms
```

Third, if the user visits http://localhost:3000/items in a browser, the typical error page is not rendered, just a blank page. This is different from what a user would experience when other non-HTML requests; for example, a failure in an action that ultimately calls `render :json => {…}` will nevertheless print the stack trace in HTML.

All of this added up to making it really unclear to me that the root cause was I had passed an invalid value  `head()`.

### System configuration
**Rails version**: 5.2.0

**Ruby version**: ruby 2.5.1p57 (2018-03-29 revision 63029) [x86_64-darwin17]

**Comment by pixeltrix** [comment]
Fixed by rack/rack#1034
