### ISSUE TITLE
validates_*_of adds the wrong message symbol to errors.details

### ISSUE THREAD

**Issue by cork** [rails/rails#33038]
```
validates_format_of :content, allow_blank: true, with: Resolv::IPv4::Regex, message: :bad_formatting
validates_format_of :content, with: /\A[[:ascii:]]+\z/, allow_blank: true, message: :none_us_ascii_characters

dns = Dns.new(content: "☀")
dns.valid?
```
rails 5.1
```
dns.added?(:content, :bad_formatting) => true
dns.added?(:content, :none_us_ascii_characters) => true
dns.added?(:content, :invalid) => false
```

rails 5.2
```
dns.added?(:content, :bad_formatting) => false
dns.added?(:content, :none_us_ascii_characters) => false
dns.added?(:content, :invalid) => true # for both validators
```

The change is that .added? now days checks the symbol of details instead of the normalised message. But validators send hardcoded messages symbols instead of the one provided to the validates_*_of line[1] and sends the message symbol provided as options to add.
[1] https://github.com/rails/rails/blob/375a4143cf5caeb6159b338be824903edfd62836/activemodel/lib/active_model/validations/format.rb#L9

This means it isn't possible to check for different validators in tests anymore.

**Comment by y-yagi** [comment]
Thank you for the report.  
There was a issue that the original behavior erroneously detects an error which was not originally added, and it changed with #31117. 

Instead of symbol, it can be checked with an actual error message. 

```ruby 
# frozen_string_literal: true

require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  gem "activerecord", "5.2.0"
  gem "sqlite3"
end

require "active_record"
require "minitest/autorun"
require "logger"

ActiveRecord::Base.establish_connection(adapter: "sqlite3", database: ":memory:")
ActiveRecord::Base.logger = Logger.new(STDOUT)

I18n.backend.store_translations("en",
  errors: { attributes: { content: { bad_formatting: "Bad formatting", none_us_ascii_characters: "none use ascii characters" } } }
)

ActiveRecord::Schema.define do
  create_table :posts, force: true do |t|
    t.string :content
  end
end

class Post < ActiveRecord::Base
  BLOCK = /\d{,2}|1\d{2}|2[0-4]\d|25[0-5]/
  validates_format_of :content, allow_blank: true, with: /\A#{BLOCK}\.#{BLOCK}\.#{BLOCK}\.#{BLOCK}\z/, message: :bad_formatting
  validates_format_of :content, with: /\A[[:ascii:]]+\z/, allow_blank: true, message: :none_us_ascii_characters
end


class BugTest < Minitest::Test
  def test_association_stuff
    post = Post.new(content: "☀")
    post.valid?

    assert post.errors.added?(:content, "Bad formatting")
    assert post.errors.added?(:content, "none use ascii characters")
  end
end
```

**Comment by cork** [comment]
Hmm, my problem isn't with the added? change. It actually fixes another problem I have. My problem is what gets added to errors.details isn't the message provided to the validator, but the standard message that would have been added if no message would have been provided.

So errors.details becomes wrong. Before this wasn't very visible, but now it sticks out quite a lot.
