### ISSUE TITLE
Extensions consisting of digits can not be registered in mime_types

### ISSUE THREAD

**Issue by silverdr** [rails/rails#33043]
### Steps to reproduce
Insert a line like:

    Mime::Type.register "text/plain", '1'

or 

    Mime::Type.register "text/plain", :"1"

into `config/initializers/mime_types.rb`

### Expected behavior
MIME-TYPE gets registered and becomes available for use

### Actual behavior
```
/Users/silverdr/.rbenv/versions/2.4.3/lib/ruby/gems/2.4.0/gems/actionpack-5.0.6/lib/abstract_controller/collector.rb:7:in `class_eval': /Users/silverdr/.rbenv/versions/2.4.3/lib/ruby/gems/2.4.0/gems/actionpack-5.0.6/lib/abstract_controller/collector.rb:8: syntax error, unexpected tINTEGER (SyntaxError)
        def 1(*args, &block)
             ^
	from /Users/silverdr/.rbenv/versions/2.4.3/lib/ruby/gems/2.4.0/gems/actionpack-5.0.6/lib/abstract_controller/collector.rb:7:in `generate_method_for_mime'
	from /Users/silverdr/.rbenv/versions/2.4.3/lib/ruby/gems/2.4.0/gems/actionpack-5.0.6/lib/abstract_controller/collector.rb:19:in `block in <module:Collector>'
	from /Users/silverdr/.rbenv/versions/2.4.3/lib/ruby/gems/2.4.0/gems/actionpack-5.0.6/lib/action_dispatch/http/mime_type.rb:192:in `block in register'
	from /Users/silverdr/.rbenv/versions/2.4.3/lib/ruby/gems/2.4.0/gems/actionpack-5.0.6/lib/action_dispatch/http/mime_type.rb:191:in `each'
	from /Users/silverdr/.rbenv/versions/2.4.3/lib/ruby/gems/2.4.0/gems/actionpack-5.0.6/lib/action_dispatch/http/mime_type.rb:191:in `register'
	from /Users/silverdr/sources/silverdr/aria_main/config/initializers/mime_types.rb:7:in `<top (required)>'
[...]
```

### System configuration
**Rails version**: rails (5.0.6)

**Ruby version**: ruby 2.4.3p205 (2017-12-14 revision 61247) [x86_64-darwin15]

**Comment by y-yagi** [comment]
I do not know why this is necessary, and what merit there is. 
Anyway, please use the [Rails Core mailing list](https://groups.google.com/forum/#!forum/rubyonrails-core) for feature requests, where a wider community will be able to help you. We reserve the Rails issue tracker only for bugs in Rails. Thanks!

**Comment by silverdr** [comment]
Thank you for your response. I would like to kindly ask you to have a closer look at the report and part of stack trace. You may notice that it is clearly no feature request (the feature of registering types is available) but rather a bug report for Rails (said feature has a bug and crashes when given a specific, valid input), which you state yourself Rails issue tracker is reserved for.
