### ISSUE TITLE
ActiveRecord collection cache key with limit and custom select (PG:AmbigousColumn: Error)

### ISSUE THREAD

**Issue by GeorgeKaraszi** [rails/rails#33056]
### Steps to reproduce
```
begin
  require "bundler/inline"
rescue LoadError => e
  $stderr.puts "Bundler version 1.10 or later is required. Please update your Bundler"
  raise e
end

gemfile(true) do
  source "https://rubygems.org"

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  gem "rails", "5.2.0"
  gem "pg"
end

system("dropdb ar_bug_test")
system("createdb ar_bug_test")

require "active_record"
require "minitest/autorun"
require "logger"

# This connection will do for database-independent bug reports.
ActiveRecord::Base.establish_connection(adapter: "postgresql", database: "ar_bug_test")
ActiveRecord::Base.logger = Logger.new(STDOUT)


ActiveRecord::Schema.define do
    create_table :users do |t|
      t.string :email, null: false
      t.timestamps
    end

    create_table :matches do |t|
      t.references :user, foreign_key: true
      t.integer :matched_user_id, foreign_key: true
      t.timestamps
    end
end

class User < ActiveRecord::Base
  has_many :matches, class_name: "Match"
  has_many :matched_users, -> { select("users.*") }, through: :matches, class_name: "User"
end

class Match < ActiveRecord::Base
  belongs_to :user
  belongs_to :matched_user, class_name: "User"
end

class BugTest < Minitest::Test
  def test_cache_key_with_limit
    user  = User.create!(email: 'test@test.com')
    assert user.persisted?
    assert user.matched_users.limit(10).cache_key.present?
  end
end
```

Whenever a HMBTM query is kicked off along with a custom select statement that collects all columns from the desired table, and contains a limit query. Postgres is throwing an error. 

### Expected behavior

When the select query includes `users.*, ..` it should replace that line with the column (in this case `updated_at`) as `users.updated_at`. Or infer from all columns selected from the `users` table

### Actual behavior
It retains the `user.*` portion of the query, and then appends `users.updated_at`, raising the `PG:AmbigousColumn: Error`

```
ActiveRecord::StatementInvalid: PG::AmbiguousColumn: ERROR:  column reference "updated_at" is ambiguous
LINE 1: SELECT COUNT(*) AS "size", MAX(subquery_for_cache_key.update...
                                       ^
: SELECT COUNT(*) AS "size", MAX(subquery_for_cache_key.updated_at) AS timestamp FROM (SELECT  users.*, "users"."updated_at" FROM "users" INNER JOIN "matches" ON "users"."id" = "matches"."matched_user_id" WHERE "matches"."user_id" = $1 LIMIT $2) subquery_for_cache_key
    test.rb:68:in `test_cache_key_with_limit'
```

### System configuration
**Rails version**:

5.2.0

**Ruby version**:

2.5.1

**Comment by fedxgibson** [comment]
The problem appears due to the subquery selecting two updated_at columns ( one from users.* and the other explicitly from users.updated_at ), and then trying to referencing it in the outer query. 

I think the solution is renaming columns in the implementation.

If I use `'SELECT temp.updated_at FROM (SELECT users.*, users.updated_at AS updated_at_2 FROM users) temp'` It works.

I created this PR https://github.com/rails/rails/pull/33075
I just use an alias to avoid this ambiguity.

**Comment by fedxgibson** [comment]
@eileencodes Hi! What do you think of these issue/PR?  I saw a test that failed but it's more like a timeout.

**Comment by davidrouten** [comment]
I'm running into this same issue when using Rails' fragment caching using the following:
- Rails, 5.2.0
- Ruby, 2.5.1
- acts-as-taggable-on, 6.0.0
- will_paginate, 3.1.6

The error only occurs when using acts-as-taggable-on (`tagged_with`) and will_paginate (`paginate`) in the same chain when trying to generate a cache_key.
