### ISSUE TITLE
ActiveRecord updating allowed for non-existent record

### ISSUE THREAD

**Issue by daveknapik** [rails/rails#33059]
### Steps to reproduce

Assuming you have a Thing model:

```ruby
thing1 = Thing.first
thing2 = Thing.first
thing1.destroy!
thing2.update! some_attribute: 'some value'
```

### Expected behavior

I expected the last line above to raise an exception, because the record no longer exists in the database.

### Actual behavior

No exception was raised and it appeared to successfully update the (non-existent) record.

### System configuration
**Rails version**: 5.2.0

**Ruby version**: 2.5.1

Tested with both PostgreSQL and SQLite.

**Comment by giovannibenussi** [comment]
The same happens when trying to save a deleted record:

```ruby
thing1 = Thing.first
thing2 = Thing.first
Thing.count # 1
thing1.destroy!
Thing.count # 0
thing2.foo = 'baz'
thing2.save! # true (performs 'UPDATE "thing" SET "foo" = $1 WHERE "thing"."id" = $2')
Thing.count # 0
```

If you try to modify the destroyed object, it throws an exception:

```ruby
thing1.update! foo: 'baz' # RuntimeError: Can't modify frozen hash
```

If this is effectively an unexpected behavior, I can work around it.

**Comment by giovannibenussi** [comment]
I have investigated this issue a little bit more and I discovered some other things that can be useful for someone investigating this issue.

Please note that [`update!` internally calls `save!`](https://github.com/rails/rails/blob/d690af13fcdae086b08dc0043643f5a66ea8cb06/activerecord/lib/active_record/persistence.rb#L437-L444) so this applied to both.

It looks like when you try to update a record, internally it only fails if the result of the update operation is `false` (`result != false`):

https://github.com/rails/rails/blob/d690af13fcdae086b08dc0043643f5a66ea8cb06/activerecord/lib/active_record/persistence.rb#L703-L708

`_create_record ` returns the id of the created record and `_update_record` returns the number of affected rows.

I try to make this change:

```ruby
def create_or_update(*args, &block)
  _raise_readonly_record_error if readonly?
  return false if destroyed?
  if new_record?
    _create_record(&block) != false
  else
    affected_rows = _update_record(*args, &block)
    if affected_rows
      affected_rows > 0
    else
      false
    end
  end
end
```

But then I get a error in InternalMetadata when I run the ActiveRecord tests:

https://github.com/rails/rails/blob/d690af13fcdae086b08dc0043643f5a66ea8cb06/activerecord/lib/active_record/internal_metadata.rb#L19-L21

I'm investigating why this is happening.

However, I'm not sure if that we can't be checking if the number of affected rows is equal to zero to say that a record is updated or not but I'm gonna try to investigate this further. I would like to know what will be the value of `affected_rows` if you try to update a record with the same values that are in the database (from two different variables that reference the same record for example).

**Comment by 6temes** [comment]
> However, I'm not sure if that we can't be checking if the number of affected rows is equal to zero to say that a record is updated or not but I'm gonna try to investigate this further. I would like to know what will be the value of affected_rows if you try to update a record with the same values that are in the database (from two different variables that reference the same record for example).

This may be a DB dependent behaviour as well.
