### ISSUE TITLE
Duplicated associations in JOINs with Rails 5.2 (PG::DuplicateAlias)

### ISSUE THREAD

**Issue by chalofa** [rails/rails#33063]
Rails 5.2 is throwing a duplicated association error as a regression after this:
https://github.com/rails/rails/commit/249ddd0c39e6f24145ae1150d4c8eec9f11219b1

_(:point_up: `git bisect`ed using the executable code to find that was the first "bad" commit)_

The next example uses 3 tables (`users`, `projects` & `tasks`).  
We want to query all the Projects that matches both:
- associated User is an admin, example: `project.user.admin? == true`.
- associated Task User name exists, example: `project.tasks.first.user.present? == true`.

Probably related to https://github.com/rails/rails/issues/33048, but they mention a `left_outer_joins` & CanCan gem, and my example is Rails only and used to work on Rails 5.1.x.

### Steps to reproduce

**Executable code:**

```rb
# frozen_string_literal: true

begin
  require "bundler/inline"
rescue LoadError => e
  $stderr.puts "Bundler version 1.10 or later is required. Please update your Bundler"
  raise e
end

gemfile(true) do
  source "https://rubygems.org"

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  gem "rails", github: "rails/rails"
  gem "sqlite3"
end

require "active_record"
require "minitest/autorun"
require "logger"

# This connection will do for database-independent bug reports.
ActiveRecord::Base.establish_connection(adapter: 'sqlite3', database: ':memory:')
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :users, force: true do |t|
    t.string :name
    t.boolean :admin, default: false
  end

  create_table :projects, force: true  do |t|
    t.string :name
    t.references :user
  end

  create_table :tasks, force: true do |t|
    t.string :name
    t.references :project
    t.references :user
  end
end

class User < ActiveRecord::Base
  has_many :projects
  has_many :tasks

  scope :with_name, -> { where.not(name: nil) }
  scope :admins_only, -> { where(admin: true) }
end

class Project < ActiveRecord::Base
  belongs_to :user
  has_many :tasks

  scope :tasks_with_user_names, -> { joins(:tasks).merge(Task.with_user_names) }
  scope :for_admin_users, -> { joins(:user).merge(User.admins_only) }
end

class Task < ActiveRecord::Base
  belongs_to :project
  belongs_to :user

  scope :with_user_names, -> { joins(:user).merge(User.with_name) }
end

class BugTest < Minitest::Test
  def test_duplicated_alias
    user      = User.create!(name: 'User', admin: true)
    user_2    = User.create!(name: 'Non Admin', admin: false)
    project_1 = user.projects.create!(name: 'Project 1')
    task_1    = project_1.tasks.create!(name: 'Task 1', user: user)
    project_2 = user_2.projects.create!(name: 'Project 2')
    task_2    = project_2.tasks.create!(name: 'Task 2', user: user)

    assert_equal 1, Project.for_admin_users.tasks_with_user_names.count
  end
end
```

### Expected behavior

- "Namespace" the JOIN generated by `joins(:other).merge(Other.scope)`:

```
INNER JOIN "users" ON "users"."id" = "projects"."user_id" 
INNER JOIN "users" "users_tasks" ON "users_tasks"."id" = "tasks"."user_id" 
```

Rails 5.1 used to "namespace" the 2nd JOIN, doing something like:

```
INNER JOIN "users" ON "users"."id" = "projects"."user_id" 
LEFT OUTER JOIN "users" "users_tasks" ON "users_tasks"."id" = "tasks"."user_id" 
```

With the fix for the LEFT OUTER JOIN sent by @MaxLap, the 2nd should be an INNER JOIN instead.

### Actual behavior

The secondary JOINs are not namespaced, thus throwing an error:
- sqlite: `SQLite3::SQLException: ambiguous column name:`
- PostgreSQL: `PG::DuplicateAlias: ERROR:  table name "users" specified more than once`
- MySQL: `Mysql2::Error: Not unique table/alias: 'users'`

Rails 5.2, after https://github.com/rails/rails/commit/249ddd0c39e6f24145ae1150d4c8eec9f11219b1, generates the next SQL:

```
INNER JOIN "users" ON "users"."id" = "projects"."user_id" 
INNER JOIN "users" ON "users"."id" = "tasks"."user_id" 
```

### System configuration

- Rails 5.2
- Ruby 2.5.1 (also fails in Ruby 2.4.* & 2.3.*)

**Comment by kamipo** [comment]
Fixed by #33066.
