### ISSUE TITLE
JavaScript Client Dynamic Authorization

### ISSUE THREAD

**Issue by audiolion** [rails/rails#33064]
When using the `actioncable` javascript package, if you want to pass an authorization token you need to do so when creating the cable consumer. However, this is not dynamic, ideally you could modify this token after the consumer is created so if the token expires or is refreshed it could be updated.

Currently as a workaround I am defining a custom `get()` property on the consumer.url prop:

```js
const cable = ActionCable.createConsumer(process.env.REACT_APP_API_WS_URL);
const cableUrl = cable.url;

Object.defineProperty(cable, 'url', {
  get: function() {
    const token = Storage.get('token');
    const email = Storage.get('email');
    return `${cableUrl}?token=${token}&email=${email}`;
  },
});
```

But I feel that this is something that should just be supported through the library to modify the URL after creation.

**Comment by rafaelfranca** [comment]
It makes sense to me. Mind to open a PR?

**Comment by audiolion** [comment]
Absolutely 👍 thanks for the quick response, I will take a look next week, got some deadlines this week and wont have time.

**Comment by audiolion** [comment]
Sorry about not submitting a PR here.

When I went to implement this I noticed that the codebase was in CoffeeScript, which has been enough of a blocker for me to not try and attempt this. I have been maintaining my own private javascript fork of this library and using it in production.

I posted on the (Rails Core mailing list](https://groups.google.com/forum/#!searchin/rubyonrails-core/actioncable%7Csort:date/rubyonrails-core/is7wpJuxa2o/8fvrf6ZtBAAJ) about converting the codebase to JavaScript. While I got some positive feedback, I don't want to start this endeavor without approval from at least some Rails Core member that this contribution would be accepted.

**Comment by javan** [comment]
> When I went to implement this I noticed that the codebase was in CoffeeScript, which has been enough of a blocker for me to not try and attempt this.

Not any more! https://github.com/rails/rails/pull/34177

**Comment by javan** [comment]
Can you explain your use case? Why use an auth token instead of the Rails session (cookies)?

>  ideally you could modify this token after the consumer is created so if the token expires or is refreshed it could be updated.

Does your server disconnect WebSocket connections when tokens expire too? Presumably something needs to cause a reconnect to pick up the new URL.

**Comment by audiolion** [comment]
> Does your server disconnect WebSocket connections

Web/Mobile clients disconnect when they lose internet access, or if they put their computer to sleep over the weekend and come back and regain connectivity and the token is expired the websocket will try to re-establish with the same token.

We are not using Rails session cookies in our app, JWT just fits our use-case better, and I don't think actioncable needs to be limited to stateful authentication. That being said, I am also the frontend dev and didn't make the decisions about what method of auth to use and can't do much to change it myself /shrugs

**Comment by audiolion** [comment]
still on my todo to make a PR for this

**Comment by rmacklin** [comment]
We might need to reopen this, see https://github.com/rails/rails/pull/35525#pullrequestreview-213122119

**Comment by rmacklin** [comment]
Or alternatively, perhaps we could revert https://github.com/rails/rails/pull/35525 and leave this closed. The originally proposed solution of:
```js
Object.defineProperty(cable, 'url', {
  get: function() { /* ... */ }
});
```
doesn't seem too unreasonable and doesn't require any changes to ActionCable.

**Comment by audiolion** [comment]
@rmacklin appreciate the input. While my original solution works, it relies on internals of ActionCable and is building functionality that was not intended into it. I feel like needing to pass an updated token string on reconnect is enough of a need for this to be warranted as a feature of ActionCable itself. My personal opinion is that overriding `get` property with a function seems really hacky and unreasonable to expect developers to do if they need to solve this problem. I would love to hear more thoughts on why you are so hesitant to add this feature to ActionCable?

**Comment by rmacklin** [comment]
Sorry if you got the impression that I'm very hesitant to add this feature. I simply noticed that https://github.com/rails/rails/pull/35525 didn't seem to solve the issue and that your original proposal does solve it (and happens to not require any changes to the library).

I don't necessarily think that the `url` property of `Consumer` objects is internal. That property is the single source of truth of what URL the `Consumer` will use to establish a connection. So, I kind of consider it public.

I also didn't think it seemed "really hacky" to define a getter to achieve the result. However, that's definitely just one option -- it could certainly be solved without a getter. For example, the app could instead use an event emitter to set `cable.url` when the token changes:
```js
tokenEmitter.on('update', ({ token }) => { cable.url = `${cableUrl}?token=${token}` })
```

Again, sorry if you got the impression I'm against adding features. Rather, I saw the change when I pulled from `master` today and dug a bit into it and now I'm trying to understand the problem and potential solutions.

**Comment by audiolion** [comment]
> Again, sorry if you got the impression I'm against adding features. Rather, I saw the change when I pulled from master today and dug a bit into it and now I'm trying to understand the problem and potential solutions.

Hey no problem, my bad for misinterpreting you. The reason I felt it is "hacky" is because the number of times I have used `Object.defineProperty` in the past few years has been basically this one time, so I feel this would be non-obvious to other developers.

If you could, check out #33579 and let me know your thoughts on doing it that way? 

I do agree that I could use an event emitter solution, but it feels so much nicer to me to be able to pass a function to `ActionCable.createConsumer()` that grabs the latest token (e.g. from localStorage) when it is needed.
