### ISSUE TITLE
Duplication in active_support/core_ext/object/conversions.rb

### ISSUE THREAD

**Issue by ajitsing** [rails/rails#33068]
While going through the active_support code I came across `activesupport-5.1.4/lib/active_support/core_ext/object/conversions.rb` file which requires all the conversion related files.

```ruby
require "active_support/core_ext/object/to_param"
require "active_support/core_ext/object/to_query"
require "active_support/core_ext/array/conversions"
require "active_support/core_ext/hash/conversions"
```

When I dived into the `to_param` file I saw below code
```ruby
require "active_support/core_ext/object/to_query"
```

`active_support/core_ext/object/to_query` is getting required twice. Once from the `conversions.rb` and then from the `to_param.rb`. I thought its a duplication and must be highlighted. Feel free to close this issue with a comment if its not a duplication and serves some other purpose.

**Comment by matthewd** [comment]
It's a dependency of that file's current implementation, but it also provides visible API that `conversions.rb` needs to load.
