### ISSUE TITLE
Incorrect parameters in scaffold with namespace

### ISSUE THREAD

**Issue by silkeh** [rails/rails#33071]
### Steps to reproduce

 1. Create a Rails API (eg: `rails new temp_api --api`)
 2. Scaffold a namespaced endpoint: `rails g scaffold v1/test name:uniq`
 3. Run migrations: `rails db:migrate`
 4. Start the server (`rails s`) and attempt to create a new item without specifying the root element (example with HTTPie):
    ```
    http POST :3000/v1/tests name=test0
    ```

### Expected behavior
The server should respond with 201 Created.

### Actual behavior
The server responds with 400 Bad Request:

```
param is missing or the value is empty: v1_test
```

### Cause analysis

The cause seems to me that the parameters are wrapped as:

```
{"name"=>"test0", "test"=>{"name"=>"test0"}}
```

While the controller requires it as `v1_test`:

```
def v1_test_params
  params.require(:v1_test).permit(:name)
end
```

### System configuration
**Rails version**: 5.0, 5.1, 5.2, master (no other versions tested)

**Ruby version**: any

**Comment by composerinteralia** [comment]
You are correct that you need to send the params nested under a key of "v1_test". Have you tried that?

I followed your reproduction steps and I am not finding any bug. If I am missing something, could you provide a link to a sample repo that reproduces the bug?

**Comment by silkeh** [comment]
Yes, when nesting it under `v1_test` in the data it works. However, Rails' parameter wrapping *should* take care of this. Ergo: sending `{"name": "test0"}` (which is the example) should be the same as `{"v1_test": {"name": "test"}}`, but it isn't.

(I've edited the issue to make this a bit more clear)

**Comment by y-yagi** [comment]
It seems an issue of `ParamsWrapper`.  
Since `ParamsWrapper` creates a root key using `demodulize`, namespace is lost. 
https://github.com/rails/rails/blob/f4f9147b1e332bfd55fd5fa150af3aad47272a49/actionpack/lib/action_controller/metal/params_wrapper.rb#L138 

```ruby 
V1::Test.to_s.demodulize.underscore
# => "test" 
``` 
As workaround, if define key in controller, I think that it will work as expected. 

```ruby 
class V1::TestsController < ApplicationController
  before_action :set_v1_test, only: [:show, :update, :destroy]
  wrap_parameters :v1_test
end
```
