### ISSUE TITLE
Incorrect offset for Berlin

### ISSUE THREAD

**Issue by abinoda** [rails/rails#33080]
`ActiveSupport::Timezone` is returning an offset of `UTC+01:00` for [Berlin](https://github.com/rails/rails/blob/375a4143cf5caeb6159b338be824903edfd62836/activesupport/lib/active_support/values/time_zone.rb#L90) but this is wrong—Berlin's offset is `UTC+02:00` until October 28.

```
irb(main):003:0> ActiveSupport::TimeZone.new('Berlin').to_s
=> "(GMT+01:00) Berlin"
```

I am using ActiveSupport v5.1.6. My `Gemfile.lock` also shows `tzinfo (1.2.5)` which looks like the most recent version. Should I also open an issue on the [tzinfo](https://github.com/tzinfo/tzinfo) repo?

**Comment by Incognito** [comment]
After reading the code a bit I think the implementation in ruby is possibly the fault but also it could be tzinfo. I'm not a ruby expert.
https://github.com/rails/rails/blob/e6ef1fe056d7da084a4e8d3b817223e9a28e6200/activesupport/lib/active_support/values/time_zone.rb#L317

You can't get a timezone offset without a date and time. It does depend on tzinfo.current_period which seems to use `period_for(Time.now)`, but the behaviour is seemingly not matching that.

**Comment by abinoda** [comment]
I just tried using the [tzinfo-data](https://github.com/tzinfo/tzinfo-data) source which appears to correctly define Berlin. See line 127 of https://github.com/tzinfo/tzinfo-data/blob/master/lib/tzinfo/data/definitions/Europe/Berlin.rb where it changes from offset+2 to offset+1 in October. I am still getting the same problem with `ActiveSupport::TimeZone` which does suggest that the issue is with the Ruby implementation here. 

Trying to run a test now using `TZInfo::DataTimezone` directly.

**Comment by abinoda** [comment]
Looks like [tzinfo](https://github.com/tzinfo/tzinfo) is determining an offset of +`
It looks like `TZInfo::Timezone` is returning the +01:00 offset. Going to open an issue there.

```
irb(main):015:0> tz = TZInfo::Timezone.get 'Europe/Berlin'
=> #<TZInfo::DataTimezone: Europe/Berlin>
irb(main):016:0> tz.current_period.utc_offset
=> 3600
```

**Comment by matthewd** [comment]
This is expected behaviour; that string contains the 'base' offset, not the one in effect at the particular moment it's called, so it remains relatively constant.

Actual calculations that involve a date will use the correct value for the date in question.

**Comment by abinoda** [comment]
@matthewd Are you sure? From what I'm seeing it looks like the string contains the offset based on the current period:
https://github.com/rails/rails/blob/e6ef1fe056d7da084a4e8d3b817223e9a28e6200/activesupport/lib/active_support/values/time_zone.rb#L303-L309

**Comment by Incognito** [comment]
@matthewd please see my previous link to the implementation where it collaborates `tzinfo.current_period` to do exactly that.

**Comment by Incognito** [comment]
Also if that's "operating as intended" this feature is mostly useless.

**Comment by matthewd** [comment]
You're looking for TZInfo's `utc_total_offset`.

**Comment by abinoda** [comment]
@matthewd Sorry I don't fully understand your comment. Is `tzinfo.current_period.utc_offset` not the code that is being executed?

Also see https://github.com/tzinfo/tzinfo/issues/89#issue-330320626

**Comment by abinoda** [comment]
@matthewd That makes sense, I found https://github.com/tzinfo/tzinfo/blob/master/lib/tzinfo/timezone_period.rb#L39-L58
