### ISSUE TITLE
Method find_by returns first when receive {} or []

### ISSUE THREAD

**Issue by rodrigomonteirof** [rails/rails#33081]
### Steps to reproduce

```
MyModel.find_by([])

MyModel Load (157.0ms)  SELECT  "my_models".* FROM "my_models" LIMIT $1  [["LIMIT", 1]]
 => #<MyModel id: 3, created_at: "2018-05-15 20:43:54", updated_at: "2018-05-15 20:43:54"> 
```

### Expected behavior
In this case could be better raise an exception

### Actual behavior
AR Executes query without `where` with `limit 1`

### Verison
Rails 5.2.0

**Comment by composerinteralia** [comment]
Related to #28290 and #31852

**Comment by hidde-jan** [comment]
An empty hash (or array) just means that there are no where conditions. It makes perfect sense (from a mathematical point of view) that it just returns the first object that satisfies those conditions. A hash is just a map of `n` keys to `n` values, where `n >= 0`. Special casing `n = 0` is a weird thing to do. Suppose you generate a hash of conditions programatically:

```
conditions = {}

active_flags_from_somewhere.each do |flag|
  conditions[flag] = true
end

result = SomeModel.where(conditions)
```
If it would raise an error than I'd have to check for the conditions hash being empty:

```
result = if conditions.blank?
  SomeModel.where(conditions)
else
  SomeModel.all
end
```
```

**Comment by rafaelfranca** [comment]
Totally agree. I'll close this issue and related PRs. Thanks
