### ISSUE TITLE
Why is an instance variable used instead of a local variable?

### ISSUE THREAD

**Issue by g13ydson** [rails/rails#33084]
Specifically for the create and index method. Should not it be a local variable since it will not be reused?

```
# GET <%= route_url %>
  def index
    @<%= plural_table_name %> = <%= orm_class.all(class_name) %>

    render json: <%= "@#{plural_table_name}" %>
  end
```

```
# POST <%= route_url %>
  def create
    @<%= singular_table_name %> = <%= orm_class.build(class_name, "#{singular_table_name}_params") %>

    if @<%= orm_instance.save %>
      render json: <%= "@#{singular_table_name}" %>, status: :created, location: <%= "@#{singular_table_name}" %>
    else
      render json: <%= "@#{orm_instance.errors}" %>, status: :unprocessable_entity
    end
  end
```

https://github.com/rails/rails/blob/35730055174c3b4b4dd2b08fc743e425310d5131/railties/lib/rails/generators/rails/scaffold_controller/templates/api_controller.rb.tt#L11

**Comment by y-yagi** [comment]
This was from when it was imported from `rails-api`.
https://github.com/rails/rails/commit/d4fe23c76b3a3307830a19be28aea177e4b96987 

I think that it was probably to make it an instance variable to match other methods, but as you pointed out, I think that there is no problem even if it is not an instance variable. 
But there is no issue with the current behavior, this is not a bug. If you are interested in improving it, please open a PR. 
We reserve the Rails issue tracker only for bugs in Rails. Thanks!
