### ISSUE TITLE
EDITOR="subl --w" bin/rails credentials:edit not opening editor jumps to "new credentials encrypted and saved"

### ISSUE THREAD

**Issue by Bsmoder** [rails/rails#33099]
### Steps to reproduce

I am trying to open credentials file with the following command. 

EDITOR="subl --w" bin/rails credentials:edit

However, terminal responds with "New credentials encrypted and saved" without opening an editor. It sucks. 

### Expected behavior
It should open an editor but not opening it. I tried with rubymine, mate, subl... all of them throwing the same thing. 

### Actual behavior
Tell us what happens instead

### System configuration
**Rails version**:

**Ruby version**:

**Comment by y-yagi** [comment]
`--w` is an invalid option. Please specify `-w` or `--wait`.

**Comment by volkanunsal** [comment]
Same issue here.
