### ISSUE TITLE
JSON serialization behaves incorrectly when a column alias has the same name as an instance method

### ISSUE THREAD

**Issue by RFLaum** [rails/rails#33091]
### Steps to reproduce
1. Have an ApplicationRecord with a function that takes no parameters, named `my_name()`.
2. On a Relation of that class, have a select statement that aliases a column to `my_name`, for instance: `MyModel.where(some_condition).select("field1 AS my_name")`.
3. Render this relation to JSON.

### Expected behavior
The JSON generated should simply be a hash of the results of the select query.

### Actual behavior
The JSON generated overwrites the value of the `my_name` entries with the results of calling the `my_name()` function for each record in the relation.

### System configuration
**Rails version**:
5.1.6

**Ruby version**:
2.5.0

## Example
Here's a simplified version of the code in my project that caused the problem. I'm using PostgreSQL; `time` is stored in the database as an integer representing a number of seconds; this is more suitable for my purposes than an `interval` column.

```
class Jog < ApplicationRecord
  belongs_to :user

  def pretty_time
    logger.debug("pretty_time called")
    "bad value"
  end

  def as_json(options = nil)
    logger.debug("as_json called")
    super(options)
  end
end

class User < ApplicationRecord
  has_many :jogs

  def all_jogs
    self.jogs
        .select(:id, :date, :distance,
                "time * interval '1 second' as pretty_time",
                "ROUND(CAST(distance * 3600 / time as numeric), 3) as speed")
        .order("date DESC")
  end
end

class UsersController < ApplicationController
  def test
    render json: User.find_by_username("Bob").all_jogs
  end
end
```

## Workaround
This can be worked around by overriding `read_attribute_for_serialization`, with something like the following:
```
class Jog < ApplicationRecord
  include ActiveModel::Serialization
  
  def read_attribute_for_serialization(key)
    self.has_attribute?(key) ? self[key] : super(key)
  end
end
```

(Note: you may wonder why one would want to have a column alias that is the same as a method name. The reason is that you may want to perform some post-processing of the stored data before rendering it to JSON. When doing this for a single Record, it's simplest to have a method with that name, and then pass `methods: :my_name`. When rendering a group of records to JSON, however, it's more efficient to have that processing done by the database itself, as part of the select query. Whichever way we do the processing, we want it to have the same key in the generated JSON.)

**Comment by y-yagi** [comment]
Can you please provide a sample application that reproduces the issue?

**Comment by RFLaum** [comment]
Here's the code in my project that caused the problem. I'm using PostgreSQL; `time` is stored in the database as an integer representing a number of seconds; this is more suitable for my purposes than an `interval` column.

```
class Jog < ApplicationRecord
  belongs_to :user

  def pretty_time
    logger.debug("pretty_time called")
    "bad value"
  end

  def as_json(options = nil)
    logger.debug("as_json called")
    super(options)
  end
end

class User < ApplicationRecord
  has_many :jogs

  def all_jogs
    self.jogs
        .select(:id, :date, :distance,
                "time * interval '1 second' as pretty_time",
                "ROUND(CAST(distance * 3600 / time as numeric), 3) as speed")
        .order("date DESC")
  end
end

class UsersController < ApplicationController
  def test
    render json: User.find_by_username("Bob").all_jogs
  end
end
```

If you look at the JSON generated, you'll see that each jog has `"pretty_time":"bad value"`. You can check the log to see that `pretty_time()` is being called each time one of the records is serialized.
