### ISSUE TITLE
Migration not running for test databases automatically 

### ISSUE THREAD

**Issue by faizaankhan** [rails/rails#33109]
### Steps to reproduce
rake db:migrate

### Expected behavior
Migration should run on all databases

### Actual behavior
Migration Running only for development database

### System configuration
**Rails version**: 5.2.0

**Ruby version**: 2.3.3

Please let me know if it is a bug or a feature :/ 
I wasted half my day in it.

**Comment by y-yagi** [comment]
Can you please provide a sample application that reproduces the issue?

**Comment by faizaankhan** [comment]
[Sample Application](https://github.com/faizaankhan/TestApplication)

**Comment by faizaankhan** [comment]
-  `rails db:migrate`
  - `rails dbconsole`
  - `select * from posts;` 
    - result is as expected, empty
  - `.exit`
  -  `RAILS_ENV=test rails dbconsole`
  -  `select * from posts ;`
    -  Error: no such table: posts

-  `RAILS_ENV=test rails db:migrate`  ( Runs migration succesfully)
  -  `RAILS_ENV=test rails dbconsole`
  -  ` select * from posts ;
    -  empty result ( as expected )

**Comment by y-yagi** [comment]
Thanks. This is expected behavior. 
Maintenance for the test database is done automatically only during test execution.  
Ref: http://guides.rubyonrails.org/testing.html#maintaining-the-test-database-schema

**Comment by faizaankhan** [comment]
@y-yagi  It says
> Running the migrations against the development database (bin/rails db:migrate) will bring the schema up to date.

I think this line is misleading
