### ISSUE TITLE
Cannot generate secret_key_base on DigitalOcean Ubuntu

### ISSUE THREAD

**Issue by SylarRuby** [rails/rails#33108]
### Steps to reproduce

(Guidelines for creating a bug report are [available
here](http://edgeguides.rubyonrails.org/contributing_to_ruby_on_rails.html#creating-a-bug-report))

### Expected behavior
```
# Running the below should generate a string inside a file in the config dir:
rails credentials:edit
```

### Actual behavior
```
Missing `secret_key_base` for 'production' environment, set this string with `rails credentials:edit` (ArgumentError)
```

### System configuration
**Rails version**: 5.2.0

**Ruby version**: 2.5.0

Hi all. This is my first time deploying a "naked" server, Ive always used Heroku but needed more dev control. On my local machine, I've removed `config/credentials.yml.enc` from git and wanted to generated that file on the production server but having this issue. Am I missing a config for production. All in well on my local machine. Thanks

**Comment by shootingfly** [comment]
@SylarRuby  
git push to update `credentials.yml.enc`

**Comment by SylarRuby** [comment]
Just leaving this here for reference.

Ensure that the same credentials.yml.enc is the same on server and create a `config/master.key` on the production server or place the key in a variable. I have not read the `production.rb` file.
