### ISSUE TITLE
ActiveStorage not working with errors

### ISSUE THREAD

**Issue by Bistaff** [rails/rails#33100]
### Steps to reproduce
I upgrade Rails from 5.1.4 to 5.2 following the rubyonrails.org guide. I've added Active storage migration and executed them with rails db:migrate.

**[CODE]**
**registrations_controller.rb**
```
def save_image
    au = current_admin_user
    au.update(admin_user_params)
    au.avatar.attach(params[:admin_users][:avatar]) (**2)
end
```

**admin_user.rb**
`has_one_attached :avatar`

**edit.html.erb**
```
<%= form_for(resource, as: resource_name, url: save_image_path(resource_name), method: :put)  do |f| %>
  <div class="field">
    <%= f.file_field :avatar, class: "form-control" %>
  <div class="field">

  <div class="actions">
    <%= f.submit "Update" %>
  </div>
<% end %>
```

### Expected behavior
According to the official guide:
"" Call avatar.attach to attach an avatar to an existing user: 
      user.avatar.attach(params[:avatar]) ""

### Actual behavior
I have this errors (**2) point:
  - NoMethodError (undefined method `deep_symbolize_keys' for false:FalseClass)
I inspect params and **params[:admin_users][:avatar]** is different from **avatar of admin_user**
- LoadError (Unable to autoload constant ActiveStorage::Blob::Analyzable, expected /Users/bistaff/.rvm/gems/ruby-2.4.2/gems/activestorage-5.2.0/app/models/active_storage/blob/analyzable.rb to define it):

### System configuration
**Rails version**:
Rails 5.2.0

**Ruby version**:
ruby 2.4.2p198

Could anyone help me?

**Comment by y-yagi** [comment]
Please use the [mailing list](https://groups.google.com/forum/#!forum/rubyonrails-talk) or StackOverflow for questions/help, where a wider community will be able to help you. We reserve the issues tracker for issues only. Thanks.
