### ISSUE TITLE
Decrement counter trigger twice when associated object removed

### ISSUE THREAD

**Issue by vavgustov** [rails/rails#33117]
### Steps to reproduce

Let's say we have 2 models:

```ruby
class Author < ApplicationRecord
  has_many :books
end
```

```ruby
class Book < ApplicationRecord  
  belongs_to :author, optional: true, counter_cache: true

  accepts_nested_attributes_for :author
end
```

Then:
```ruby
Author.create(name: 'author name')
3.times { Book.create(title: 'book title', author: Author.last) }
Book.last.update(author: nil)
Author.last.books_count
```

### Expected behavior
`Author.last.books_count` should be equal to 2.

### Actual behavior
`Author.last.books_count` equal to 1.

The query below executed twice:
```sql
 UPDATE `authors` SET `books_count` = COALESCE(`books_count`, 0) - 1 WHERE `authors`.`id` = 15
 ```
Screenshot with helpful information:
![rails_counter_twice](https://user-images.githubusercontent.com/312873/41251140-b0f780ae-6dc1-11e8-986b-d206358a78dd.png)

### System configuration
**Rails version**: 5.2.0

**Ruby version**: 2.5.1

**Comment by mohsen-alizadeh** [comment]
@rafaelfranca
