### ISSUE TITLE
Transaction doesn't rollback when using pessimistic locking

### ISSUE THREAD

**Issue by yukideluxe** [rails/rails#33132]
Hello 👋 

I noticed a strange behaviour in my app because a record was committed in the database when it shouldn't (we raise an `ActiveRecord::Rollback` exception in an `after_save` callback) and it seems to happen when using pessimistic locking. Honestly, I don't have any idea what's going on here but I managed to reproduce it! 

Not sure if this is an ActiveRecord issue, a database adapter gem issue, or a database issue (tried with mysql, PostgreSQL and sqlite). I tried to run the SQL output that I see in the tests in MySQL directly (using ROLLBACK instead of COMMIT) and the rollback seems to work.

### Steps to reproduce

https://gist.github.com/yukideluxe/69a9692196393a0621896aaf7006dda2

NOTE: I've used all the documented ways to lock a record!

### Expected behavior
When raising `ActiveRecord::Rollback` from an `after_*` callback  transaction should rollback and no comment should be created. 

### Actual behavior
When using pessimistic locking, the transaction doesn't rollback properly.

### System configuration
**Rails version**:
Tried with latest master, 5.2.0, 5.1.6 and 4.2.10
**Ruby version**: 2.5

PS: Couldn't find a similar issue, sorry if this is duplicated!

**Comment by yukideluxe** [comment]
ohhh I think I see what happens!

The `with_lock` method wraps the instruction in a transaction. It's not enough with raising an exception in the `after_save` callback. I should raise the exception in the transaction block.

This rollbacks successfully.

```
    post.with_lock do
      comment = Comment.new(
        post: post
      )
      unless comment.save
        raise ActiveRecord::Rollback
      end
    end
```

Sorry, I wasn't exception that and I'm sorry because this has nothing to do with the locking 🙈

**Comment by yukideluxe** [comment]
I'm going to close this because I'm still a bit confused and open another issue if I see there's an actual problem 👌 Sorry for the noise!

**Comment by tiendo1011** [comment]
@yukideluxe Your comment helps with one of the issue I got with `with_lock` recently, so it's actually kinda helpful :).

My issue is like this, given this code snippet:
```ruby
# computer.rb
class Computer < ApplicationRecord
  after_commit -> { p [:commit] }
end
```
```ruby
# test.rb
with_lock
  Computer.create!
  p [:done_creating_computer]
end
p [:done_lock]
```

I expect that when I run test.rb, The output would be:
```ruby
[:commit]
[:done_creating_computer]
[:done_lock]
```

But the actual output is:
```ruby
[:done_creating_computer]
[:commit]
[:done_lock]
```

It seems to me that after_commit is fired after the `outmost` transaction is completed, not the one closet to it. Since `with_lock` method wraps the instruction in a transaction, it explains why `[:commit]` is being printed after `[:done_creating_computer]`
