### ISSUE TITLE
Select which queue active storage analyzer jobs are enqueued oen

### ISSUE THREAD

**Issue by mikevic** [rails/rails#33138]
### Steps to reproduce
- Add a file with Active Storage and you will see that it is always enqueued to the `default` queue

### Expected behavior
- Would like to have an option in active storage configurations to select which queue to enqueue to analyze jobs

### Actual behavior
- Be default the jobs are enqueued on to the `default` queue
 
### System configuration
**Rails version**:
5.2

**Ruby version**:
2.5.1p57

**Comment by georgeclaghorn** [comment]
You can change the queue Active Storage jobs use by setting [`config.active_storage.queue`](http://guides.rubyonrails.org/configuring.html#configuring-active-storage).

**Comment by MSCAU** [comment]
How do I skip Active Job (ie. a queue) for Active Storage? I just want to perform the task immediately.

**Comment by factor4** [comment]
I don´t know if it´s possible to skip the Job but you can perform it immediately with `attachment.blob.analyze`. I use `unless attachment.blob.analyzed?` to prevent doing things twice.
