### ISSUE TITLE
validates_inclusion_of exception not working on boolean

### ISSUE THREAD

**Issue by Awatatah** [rails/rails#33144]
### Steps to reproduce
I set `validates_inclusion_of` in my model to validate a `boolean`

```
    class Model < ApplicationRecord
        ...
        validates_inclusion_of :boolean_field, in: [true, false], message: "testing error message"
        ...
    end
```

Then I pass a random string into `:boolean_field` on `update`
```
    class SomeController < ApplicationController
        ...
        def update
            ...
            @object.update_attribute(:boolean_field, "some string")
            ...
        end
    end
```

But no exception was thrown and instead I can see the commit with the string ignored:
```
(1.0ms)  BEGIN
(1.0ms)  COMMIT
=> true
``` 
### Expected behavior
I should have received a RecordInvalid with my message but instead the string was ignored and the commit was executed.

### Actual behavior
Object is saved without validation error

### System configuration
**Rails version**: Rails 5.2.0

**Ruby version**: ruby 2.3.1p112

**Comment by y-yagi** [comment]
`update_attribute` skip the validation. Please check the API doc for details. 
http://api.rubyonrails.org/classes/ActiveRecord/Persistence.html#method-i-update_attribute
