### ISSUE TITLE
Can't add a new key into hash during iteration active_record/scoping.rb:75

### ISSUE THREAD

**Issue by guillec** [rails/rails#33143]
### Steps to reproduce

This is not easily reproducible. 

### Expected behaviour
We should not get this error.

### Actual behaviour
The methods should run without this error.

### System configuration
**Rails version**: 4.2.8

**Ruby version**: 2.4.1

### Extra Info
Our application started throwing this error in different parts of the application. But they all point to
app/vendor/bundle/ruby/2.4.0/gems/activerecord-4.2.8/lib/active_record/scoping.rb:75

We are not doing any fancy concurrency stuff. 
These are happening in background jobs in which we are using delayed jobs.

https://github.com/rails/rails/blob/8ee716182df410052707c3d1eabf8bfd8e0e1c5e/activerecord/lib/active_record/scoping.rb#L75

Here is the first part of the stack trace:
```
can't add a new key into hash during iteration /app/vendor/bundle/ruby/2.4.0/gems/activerecord-4.2.8/lib/active_record/scoping.rb:75:in
`set_value_for' /app/vendor/bundle/ruby/2.4.0/gems/activesupport-4.2.8/lib/active_support/per_thread_registry.rb:50:in 
`set_value_for' /app/vendor/bundle/ruby/2.4.0/gems/activerecord-4.2.8/lib/active_record/scoping.rb:18:in 
`current_scope=' /app/vendor/bundle/ruby/2.4.0/gems/activerecord-4.2.8/lib/active_record/relation.rb:304:in 
`ensure in scoping' /app/vendor/bundle/ruby/2.4.0/gems/activerecord-4.2.8/lib/active_record/relation.rb:304:in 
`scoping' /app/vendor/bundle/ruby/2.4.0/gems/activerecord-4.2.8/lib/active_record/associations/collection_proxy.rb:874:in 
`scoping' /app/vendor/bundle/ruby/2.4.0/gems/activerecord-4.2.8/lib/active_record/relation/delegation.rb:70:in 
`interchange_in' /app/app/views/truck_visits/print.html.slim:1:in 
`_app_views_truck_visits_print_html_slim__3565991189790970065_69972235041980' 
```

Here is a gist of the full stack trace:
https://gist.github.com/guillec/5bb4ce0ea74d57c1dfea9f205e63e0a2

We have looked at the other issues reported about "new key into hash" but they are not hitting the lib/active_record/scoping.rb class.

Any help would be appreciated.

**Comment by y-yagi** [comment]
Please use the [mailing list](https://groups.google.com/forum/#!forum/rubyonrails-talk) or StackOverflow for questions/help, where a wider community will be able to help you. We reserve the issues tracker for issues only. Thanks.
