### ISSUE TITLE
Multithreaded tests vs. testing utils

### ISSUE THREAD

**Issue by palkan** [rails/rails#33146]
Parallel testing feature (https://github.com/rails/rails/pull/31900) provides two implementations: using threads and using processes.

When dealing with threads, we should take care of thread safety. Although Rails codebase itself is a thread-safe **some testing tools are not**.

And the problem is not only with thread-safety but _thread-isolation_.

I've started to collect such potentially problematic places, and ended up with the following list:

- `ActionMailer` test delivery.

Relies on `mail` gem [`TestMailer`](https://github.com/mikel/mail/blob/master/lib/mail/network/delivery_methods/test_mailer.rb) which stores deliveries in a class variable.

- Time travel [helpers](https://github.com/rails/rails/blob/master/activesupport/lib/active_support/testing/time_helpers.rb).

`travel_to` is not thread-safe.

- `ActiveJob` [test adapter](https://github.com/rails/rails/blob/master/activejob/lib/active_job/queue_adapters/test_adapter.rb).

It's not a problem when using with Minitest (i.e., include `ActiveJob::TestHelper`): a new test adapter is created in `before_setup` hook.
However RSpec, for example, provides [its own functionality](https://relishapp.com/rspec/rspec-rails/docs/job-specs/job-spec), and it's a common practice to specify `:test` adapter globally.

- [`ActiveSupport::Cache::MemoryStore`](https://github.com/rails/rails/blob/master/activesupport/lib/active_support/cache/memory_store.rb)

It is pretty often used to test custom caching behavior.  It's thread-safe, but all threads use the same store, which is not what we expect in multithreaded tests.

We need some test-specific cache with a per-thread store.

Not sure that the list is complete. And, of course, there are many third-party testing tools which do not care about threads.

Unfortunately, just fixing this non-thread-aware tools is not enough: we have _system tests_  which could rely on this non-threaded functionality (e.g., sending emails in a server thread and verifying them in the main thread, time-traveling features, etc.). That's the same problem as with the shared  ActiveRecord connection.

That means we need a way to toggle _threaded_ behavior for these tools (and, btw, third-party testing utils too), probably,  through a specific hook:

```ruby
class ActiveSupport::TestCase
  parallelize(workers: 4, with: :threads)

  multithreaded_setup do
    ActionMailer::Base.delivery_method = :threaded_test
  end

  multithreaded_teardown do
    ActionMailer::Base.delivery_method = :test
  end
end
```

Or vice versa – to add a system tests hook (IMO, a better option):

```ruby
system_tests_setup do
  ActionMailer::Base.delivery_method = :shared_test
end
```

I'd like to help with fixing these problems, but first, we should agree on the way to do that.

/cc @eileencodes

**Comment by matthewd** [comment]
Isn't this requirement generally addressed by the `parallelize_setup` / `parallelize_teardown` hooks, as long as you default the global / main process's configuration to the thread-aware alternative?

I'd be reluctant to add a system tests hook for this, because that feels like it permanently gives up ground I'm not yet ready to yield: they're incompatible with threads _at the moment_, but not necessarily forever. Defining "running system tests" = "using process isolation" would make that difficult to change in future.

**Comment by palkan** [comment]
> Isn't this requirement generally addressed by the parallelize_setup / parallelize_teardown hooks, as long as you default the global / main process's configuration to the thread-aware alternative?

If we default to the thread-aware implementations then system tests would break, don't they? Or I didn't understand you correctly.

> I'd be reluctant to add a system tests hook for this because that feels like it permanently gives up ground I'm not yet ready to yield: they're incompatible with threads at the moment, but not necessarily forever. 

Agree. It's too early to give on multithreaded system tests.

As I see, we have three different situations:
- parallelization with processes – just works, doesn't depend on tests types
- parallelization with threads + non-system tests – thread-awareness required
- parallelization with threads + system tests – we need a way to synchronize the current test state with the corresponding requests states running in a separate thread.

The main question is how to properly handle the third case.

Can we run a Capybara server within the same thread as the test itself? Don't think so.

Thus we need some _sharable isolated environment_. That's possible but, IMO, too specific and complicated.

Anyway, we have plenty of time to figure out the better way.

**Comment by matthewd** [comment]
I guess my concern is that the split between 2 & 3 isn't so clean in practice: system tests definitely have multiple threads involved out of the box, but it's not super-improbable for other tests to have threads in flight either.

My current _least-bad_ thought is something that involves hooking `Thread.new` to track thread parentage, and thus reliably link back to the "test thread". (Thread groups could get us most of the way there, but only if the app / other libraries aren't using them.) Actually overriding the method doesn't scare me much, tbh, but useful tracking gets bumpier when libraries' thread pools become involved.

**Comment by palkan** [comment]
> My current least-bad thought is something that involves hooking Thread.new to track thread parentage

`ThreadGroup` with local variables could help (though we don't have local variables for them, it's easy to add them with a little monkey patch: https://bugs.ruby-lang.org/issues/10658).

> ...only if the app / other libraries aren't using them.

We can also monkey-patch `Thread` to check the group variables first and fallback to the thread locals if none exist:

```ruby
Thread.prepend(Module.new do
  def [](key)
    group[key] || super
  end
end)
```

Then we only have to initialize the corresponding group variable in `parallelize_setup`. Thus all thread locals created within a test work without modification, and only locals specified for the group are shared.

**Comment by nateberkopec** [comment]
I think ActionMailer's dependence on a class variable for delivery is a separate issue that could be fixed on it's own. I guess we'll have to fix that in `mail` though. 

I don't see how you can ever make timetravel threadsafe. I opened an issue about this on minitest a while ago and I just don't see a very easy path forward with patching globals but only for a single thread. I think that's fine, just change the parallelize settings for those test classes (I do this a lot for global stubs).

> but all threads use the same store, which is not what we expect in multithreaded tests.

In production, e.g. Puma, do all threads use the same store?

**Comment by palkan** [comment]
@nateberkopec Regarding in-memory cache, consider an example (very synthetic):

```ruby
# global cleanup to make sure there is no global state leaking
teardown do
  Rails.application.cache.clear
end

# test
test "hits DB when is not cached" do
  assert_queries do
    User.fetch(users[:id])
  end
end

test "fetch from cache" do
  # warm-up cache
  User.fetch(users[:id])
  assert_no_queries do
    User.fetch(users[:id])
  end
end
```

There is a race condition (which could make the first test fail).

**Comment by nateberkopec** [comment]
But that's just a thread-unsafe test, not a problem with the framework. You could do the same thing with a hash. That's exactly the kind of race condition I would _like_ to cause with threaded test execution.
