### ISSUE TITLE
Delegation does not work when calling create on association with model

### ISSUE THREAD

**Issue by CodingAnarchy** [rails/rails#33154]
### Steps to reproduce

```
class Foo
  belongs_to :bar
  has_many :zips
  
  delegate :baz, to: :bar

   after_validation :run_baz, on: :create

   def run_baz
      baz
   end

   def zips=(new_zips)
       new_zips.each {|z| z.update(foo: self) }
   end

   def method_that_changes_attributes(new_val)
      self.changing_attribute = new_val
end

class Zip
   belongs_to :foo

   after_update :update_foo, if: :foo_id

   private

   def update_foo
      foo.method_that_changes_attributes(rand())
   end
end

class Bar
  has_many :foos

  def baz
    puts 'baz'
  end
end

bar_instance = Bar.create()
bar_instance.foos.create()
```

### Expected behavior

It should run the `baz` method that is delegated to the `bar_instance` and output `'baz'`.

### Actual behavior

`Foo#baz delegated to bar.baz, but bar is nil`

~~Workaround is presently `Foo.create(bar: bar_instance)` to get it to run correctly.~~. Correction: This workaround only fixed the problem sometimes.

### System configuration
**Rails version**: 5.2.0

**Ruby version**: 2.5.1

**Comment by CodingAnarchy** [comment]
Further details I have discovered in my application.

`bar_instance.foos.create()` FAILS
`Foos.create(zips: <list_of_zips>, bar: bar_instance)` FAILS
`Foos.create(bar: bar_instance: zips: <list_of_zips>)` WORKS

**Comment by yuktikhurana** [comment]
@CodingAnarchy Can you please add relevant error stack trace to help debug it.

**Comment by jagdeepsingh** [comment]
@CodingAnarchy i am **not** able to replicate the bug with Rails **5.2.0** and Ruby **2.5.1**.

This is what i had:

```ruby
class User
  # field :email

  has_many :songs
end

class Song
  belongs_to :user

  delegate :email, to: :user

  after_validation :check_email, on: :create

  private

  def check_email
    puts email
  end
end
```

I don't know why you mentioned a third model `Zip` in your original question (not the comment). There is no use of it while doing `bar_instance.foos.create()`.

Anyway, see the results for me:

```ruby
user = User.create(email: 'jack@demo.com')
 => #<User id: 1, email: "jack@demo.com">

user.songs.create
jack@demo.com    # <--- prints email
 => #<Song id: 1, user_id: 1>
```

So, to me, it **doesn't** look like a bug.

**Comment by AhmedAliIbrahim** [comment]
i'm facing the same issue on rails 5.2.1 , but it works fine when i downgraded to 5.2.0

**Comment by ziaulrehman40** [comment]
Can confirm this issue on rails 4.2 and 5.2 both. Please consider re-opening.
