### ISSUE TITLE
Lowercase ActiveStorage service name in storage.yml leads to unintuitive errors

### ISSUE THREAD

**Issue by hidde-jan** [rails/rails#33157]
### Steps to reproduce

1. Start a new rails app
2. Create a model and add an active storage attachment to it
3. Change config/storage.yml, set the local service to `disk` instead of `Disk`
4. Try to attach a file to an instance of the model

### Expected behavior

Either there should be a clear error message saying you messed up the service name, or it should interpret `disk` as `Disk` and attach the file successfully.

### Actual behavior

You get a NameError that could explain more clearly that your storage service doesn't exist.

```
NameError: Cannot load `Rails.config.active_storage.service`: wrong constant name diskService
```

### System configuration
**Rails version**: rails 5.2.0

**Ruby version**: ruby 2.3.3

**Comment by jvanbaarsen** [comment]
I tried reproducing this on Rails master with ruby 2.5.1 and got the following error (After running the exact steps described in the description)

```
Unable to autoload constant ActiveStorage::Blob::Analyzable, expected /Users/jeroen/Development/rails/activestorage/app/models/active_storage/blob/analyzable.rb to define it
```
