### ISSUE TITLE
Index_errors nested attributes not in the right index

### ISSUE THREAD

**Issue by phandych** [rails/rails#33168]
i have been update my rails v to 5.0.7 today to use index_errors on mode
this my code from model: 
`class Product < ActiveRecord::Base
has_many :product_specifications, index_errors: true
end`

My Product Controller to Create

`def update
if @product.update(product_params)
render json: @product, status: :ok
else
render json: { errors: @product.errors }, status: :unprocessable_entity
end
end`

problem 1: index errors not in right index on errors message on update model. i have try to update nested attributes where error place must be in index [1] but getting in place index [0]. index errors place in existing field, not in the new field.

problem 2: index errors not validate if text empy. if i let existing field (model) empty, then i update the attribute, the not show errors if not cant be empy for validate fields

<img width="1280" alt="screen shot 2018-06-20 at 19 57 09" src="https://user-images.githubusercontent.com/16778350/41697794-bcf8420a-7544-11e8-90d4-b187c2345a91.png">

<img width="1280" alt="screen shot 2018-06-20 at 22 23 12" src="https://user-images.githubusercontent.com/16778350/41668009-8d5cf606-74d8-11e8-8661-c8ed7f01e612.png">

index_errors work fine on create..but not on update (edit)

### System configuration
**Rails version**: 5.0.7

**Ruby version**: 2.3.1p112 

any body can help me for this issue? so stress for this trouble

**Comment by phandych** [comment]
@y-yagi what the mean 5.0 is not supported anymore for anything besides security fixes?
what version ROR u recomended for this problem?especially index_errors

**Comment by y-yagi** [comment]
No, you do not need to update the real application.
Please use [bug report template](https://github.com/rails/rails/blob/master/guides/bug_report_templates/active_record_master.rb) or create a new application to reproduce the issue and check with it.

**Comment by phandych** [comment]
@y-yagi i have try in 5.2.0 version getting same issue..i think the problem its in my ajax..
this my code to push to formdata :
`for (let i = 0; i < product_specifications.length; i++) {
		let specification = product_specifications[i];
		if (specification._destroy) {
			data.append(`product[product_specifications_attributes][${i}][id]`, specification.id);
			data.append(`product[product_specifications_attributes][${i}][_destroy]`, '1');
		} else {
			data.append(`product[product_specifications_attributes][${i}][title]`, specification.title)
		}
		
	}	`


if i update this model, i'm getting double attributes of each item

**Comment by y-yagi** [comment]
Thank you for clarifying the issue. 
The problem with JavaScript seems to be an application's issue, not a Rails's issue. I will close this issue because we reserve the issues tracker for Rails's issues only.

Please use the [mailing list](https://groups.google.com/forum/#!forum/rubyonrails-talk) or StackOverflow for questions/help, where a wider community will be able to help you.  
In that case, I think that if you can provide an application that can actually confirm the problem, it will lead to solution of the issue. Thanks.

**Comment by md5** [comment]
For posterity's sake, I think this may be a duplicate of #24390
