### ISSUE TITLE
--skip-bootsnap option on rails new does not work

### ISSUE THREAD

**Issue by hass-laughingman** [rails/rails#33167]
### Steps to reproduce
running `rails new --skip-bootsnap my_new_project`

### Expected behavior
- The bootsnap gem shouldn't be in the `Gemfile`
- bootsnap shouldn't be required in the `config/boot.rb`

### Actual behavior
Gemfile:
```
# Reduces boot times through caching; required in config/boot.rb
gem 'bootsnap', '>= 1.1.0', require: false
```

config/boot.rb:
```
require 'bootsnap/setup' # Speed up boot time by caching expensive operations.
```

### System configuration
**Rails version**: 5.2.0
**Ruby version**: 2.5.1

**Comment by bogdanvlviv** [comment]
```
$ rails new --help
Usage:
  rails new APP_PATH [options]
...
```
You should provide name of project first and then options like:  `rails new my_new_project --skip-bootsnap`

**Comment by sebroeder** [comment]
I run into the same problem with `--skip-bundle` and `--skip-gemfile`. They only work after `APP_PATH`.
