### ISSUE TITLE
Late change to attributes on parent model breaks attribute inheritance

### ISSUE THREAD

**Issue by nate** [rails/rails#33165]
### Steps to reproduce

1. Create a parent model with a custom attribute.
2. Create a child model (inheriting from that parent) with a custom attribute.
3. Add another attribute to the parent model.

Test that proves this behavior is happening:

https://gist.github.com/nate/b6ea5bbb9e926dbfead3e962ff98978c

### Expected behavior

I would expect the child model to inherit both attributes from the parent model.

### Actual behavior

The child model inherits only attributes added added to the parent model **before** the `attribute` call on the child model.

The cause seems to be that `attributes_to_define_after_schema_loads` is a `class_attribute`, so once the child model sets a new value the child model won't see any changes made by the parent model.

I think we could fix it with something like this:

```ruby
class ActiveRecord::Base
  def self.attributes_to_define_after_schema_loads=(values)
    singleton_class.define_method("attributes_to_define_after_schema_loads"){
      super().merge(values)
    }
  end

  def self.attributes_to_define_after_schema_loads
    {}
  end
end
```

Although if we ever called `ActiveRecord::Base.attributes_to_define_after_schema_loads=` this would break since `ActiveRecord::Base`'s superclass doesn't respond to `attributes_to_define_after_schema_loads`.

### System configuration
**Rails version**: master

**Ruby version**: 2.5.1p57

**Comment by nate** [comment]
I'd like to put together a patch for this, assuming it's something worth fixing, so if you have any advice on how best to solve it...

**Comment by matthewd** [comment]
Hi!

While I certainly don't object to us fixing this in principle, I'm wary that this is true for a lot of similarly inherited values: I think a solution would need to [performantly] address the issue in a general way... and I don't think multiply-nested method redefinitions + hash merges is going to do it.

As some slightly more concrete advice: this feels like it should be a feature (option? separate method?) of `class_attribute` -- storing an empty value (here, a hash) at each level of inheritance, then combining them when read.

**Comment by nate** [comment]
Maybe a simpler way to handle this is to allow custom readers and writers.
 
```ruby
class_attribute :attributes_to_define_after_schema_loads, default: {}, reader: ->(val){ super().merge(val) }, writer: ->(val){ val.with_indifferent_access }
```

The reader results could be cached and when the superclass attribute is changed we can bust the subclass caches so they're recalculated on next access.

**Comment by nate** [comment]
Well I'm not sure what I was thinking but `super()` definitely wouldn't work there. I'm in the process of adding something more like:

```ruby
class_attribute :foo, default: {},
                      inherit: ->(parent, val){ parent.merge(val) },
                      cast: ->(val){ val.with_indifferent_access }
```

I still don't like the names, and maybe they're separate concerns. I'm not sure.

**Comment by nate** [comment]
Ugh, this is no good, either. If we cache the result of the `inherit` block on instances then the only way to bust those caches when the parent changes is either to iterate over ObjectSpace...

**Comment by nate** [comment]
[Here's my first attempt at adding a new method for class-level heritable attributes that can merge in changes to the parent](https://gist.github.com/nate/f22c2f968c63b0483bdfa13cb203c0cf). I didn't include instance accessors because, like I said above, iterating over all of ObjectSpace for all objects created from all classes in a hierarchy for each change to a class' setting seemed bad.
