### ISSUE TITLE
Path Traversal vulnerability Patch in Sprockets blocked by gem dependencies

### ISSUE THREAD

**Issue by hananamar** [rails/rails#33169]
### Expected behavior
Following the recent [Path Traversal vulnerability in Sprockets](http://seclists.org/oss-sec/2018/q2/210), patches have been applied to the Sprockets gem, in versions `4.0.0.beta8`, `3.7.2` and `2.12.5`. 

### Actual behavior
However, `rails 3.2.22.5` depends on `sprockets 2.2.1` (via the `actionpack` gem), not allowing the implementation of this important security patch.

### System configuration
**Rails version**: 3.2.22.5
**Ruby version**: 2.2.6p396

**Comment by matthewd** [comment]
Rails 3.2 has been unsupported, including for security issues, for some time.

**Comment by schneems** [comment]
@hananamar Check out Rails LTS and ask them if they are going to patch or fix this somehow. FWIW this could be patched by monkeypatching Sprockets.

**Comment by hananamar** [comment]
@schneems Thanks

**Comment by mstroming** [comment]
@hananamar Any luck on getting sprockets updated? Seems odd that Sprockets supports 2.12, but not 2.2.

**Comment by mstroming** [comment]
@hananamar Thanks.
