### ISSUE TITLE
Unable to user action_cable.js inside WebWorker

### ISSUE THREAD

**Issue by sanbornhilland** [rails/rails#33163]
### Steps to reproduce
Import `ActionCable` inside a WebWorker

### Expected behavior
Should be able to use ActionCable inside the WebWorker

### Actual behavior
`Uncaught ReferenceError: window is not defined`

WebSockets are available inside web workers but they are attached to `self`, not `window` because there is no `window` inside a worker. Similarly there is no `document` available in a worker context and the JavaScript library has references to the `document`.

Ideally the JS library would be decoupled from the DOM so that it could be used inside WebWorkers. Is there any suggested approach currently for using ActionCable inside a WebWorker?

**Comment by Sexual** [comment]
Can't you just do `window = self`?

**Comment by sanbornhilland** [comment]
@Sexual Unfortunately, it's not so straightforward. `window` needs to be defined before loading the library which makes it particularly difficult to `import` actioncable. In any case, even if you did hack around that problem there are actual DOM references such as in `createWebSocketURL` that just aren't going to work.

**Comment by zspencer** [comment]
This also makes actioncable difficult to use in testing environments such as cucumber-js or other systems where the javascript is not running in a browser (real or imagined).

For now, I have prefixed my test helper with the following two lines, which provide a fake browser as well as a WebSockets implementation:

```
require('browser-env')()
window.WebSocket = require('isomorphic-ws')
```

I'm not entirely sure that this will actually work, but I will report back with what I find.

**Comment by zspencer** [comment]
FYI, the above solution of using browser-env and explicitely defining window.WebSocket appears to work in non-browser use cases; and likely will work in webworkers; however I do not have any webworkers in my application so I cannot guarantee it at this time. 

Here is a PR with it functioning in an OSS codebase: 
https://github.com/wecohere/graphql-rails-example/pull/15/files#diff-8fe99be2765cdff0c7515cd2e81c46b3R5

**Comment by rmacklin** [comment]
Just stumbled onto this old issue. FYI, this won't be the case in rails 6, as of https://github.com/rails/rails/pull/34941
