### ISSUE TITLE
checkout_timeout parsed as string when it congiured from DATABASE_URL

### ISSUE THREAD

**Issue by Muscul** [rails/rails#33177]
### Steps to reproduce

To set the configuration pool and checkout_timeout=1  to the database via DATABASE_URL parameters.
e.g.
DATABASE_URL=mysql2://root@127.0.0.1/cool_development?reconnect=true&pool=1&checkout_timeout=1

Call the Railse exception ConnectionTimeoutError exception by creating multiple connections to the database.

### Expected behavior
The checkout_timeout loaded as integer

### Actual behavior

The checkout_timeout parsed as string, so it raises a exception in wait timeout comparation
# File activerecord/lib/active_record/connection_adapters/abstract/connection_pool.rb

### System configuration
**Rails version**: 3.2.22

**Ruby version**:2.2.4

**Comment by y-yagi** [comment]
Already fixed by #16542. Please upgrade Rails' version.
