### ISSUE TITLE
configuring guide is missing some rails 5.2 options

### ISSUE THREAD

**Issue by thomasdziedzic-pd** [rails/rails#33170]
When I look at this page: http://guides.rubyonrails.org/configuring.html

It seems to be missing an option for `Rails.application.config.active_support.use_authenticated_message_encryption` which is new in rails 5.2.

It also says that `config.action_dispatch.use_authenticated_cookie_encryption` is set to false by default. But in my config/initializers/new_framework_defaults_5_2.rb it lists `Rails.application.config.action_dispatch.use_authenticated_cookie_encryption = true` as the default.

**Comment by utilum** [comment]
That `use_authenticated_cookie_encryption` is set to true by default has been fixed (c8a22bb9eef2654c87a0fdb9139d868caf482ec0) in master, see: http://edgeguides.rubyonrails.org/configuring.html#configuring-action-dispatch. Needs a backport?

`use_authenticated_message_encryption` has not been updated.

**Comment by thomasdziedzic-pd** [comment]
Sure, do I just add it into the 5-2-stable branch?

**Comment by utilum** [comment]
It is usually best to make changes in master, and one of the two missing data you've reported is missing there. So I would suggest fixing _that_ in master and then backporting to 5-2-stable.
