### ISSUE TITLE
.label of formbuilder does not produce "for=" attribute

### ISSUE THREAD

**Issue by Pepan** [rails/rails#33178]
### Steps to reproduce
Project created in Rails 5.1
Just moved to Rails 5.2 following guides
Show HTML of simple form view with form.label :something 
in slim
```
= f.label :code, class: 'col-sm-3'
```
Form is created like this:
```
= form_with model:[:admin, @zone_type], html: { class: 'zone_type'} , local: true do |f|
```

(Guidelines for creating a bug report are [available
here](http://edgeguides.rubyonrails.org/contributing_to_ruby_on_rails.html#creating-a-bug-report))

### Expected behavior
Tell us what should happen
```
<label class="col-sm-3" for="zone_type_code">Kód</label>
```
 taken form project still on Rails 5.1

### Actual behavior
Tell us what happens instead
```
<label class="col-sm-3">Kód</label>
```
- there is ```for="scope_something"``` missing

### System configuration
**Rails version**:  Rails 5.2

**Ruby version**: ruby-2.5.1

**Comment by rafaelfranca** [comment]
When you use form_with the `ids` are not generated anymore and because of this we can't generate the `for` attribute anymore. You can configure this using `config.action_view.form_with_generates_ids`

**Comment by Pepan** [comment]
Thanks for info :)
