### ISSUE TITLE
Error messages should be better formatted and less overwhelming

### ISSUE THREAD

**Issue by jwinnie** [rails/rails#33187]
## Steps to reproduce
1. Make a horrible mistake.
2. Run `rails s`.
3. Load the page.

## Expected behavior
A very nice error message that informs you what is going on without overwhelming you.

**Django:**
![image](https://user-images.githubusercontent.com/20506149/41754567-b3d77ef0-7587-11e8-873d-37fddec39e60.png)

## Actual behavior
![rails](https://user-images.githubusercontent.com/20506149/41754441-2cea2c30-7587-11e8-8594-e257bed22684.png)

Newbie like me: *???*

## System configuration
**Rails version**: 5.2.0
**Ruby version**: 2.4.1p111
**Browser**: Firefox

**Comment by StefSchenkelaars** [comment]
This are not questions you should ask here... But you can already see that your syntax is incorrect in the `/app/views/posts/_form.html.erb`. You should replace `class` with `:class` but actually I should just not help you here. Ever heard of [stackoverflow](https://stackoverflow.com/)?

**Comment by jwinnie** [comment]
I am not talking about my mistake (it doesn't matter what the mistake is), I am talking about the formatting of the error message. The error message is all in one line and in bright red, which, at least in my opinion, is not good for readability.

Something like this would be better:
```
/home/jeremy/Git/testproject/app/views/posts/_form.html.erb, line 36: Syntax Error
    unexpected => m.text_field :body, { class => "form-control" } );
@output_bu ^ /home/jeremy/Git/testproject/app/views/posts/_form.html.erb, line 36: Syntax Error
    unexpected '}', expecting ')' y, {  class => "form-control" } );
@output_buffer.safe_append= ^ /home/jeremy/Git/testproject/app/views/posts/_form.html.erb, line 37: Syntax Error
```

**Comment by matthewd** [comment]
@jwinnie sorry, please ignore @StefSchenkelaars.

Was the ugly red error not followed by a better-formatted version of the same message?

**Comment by jwinnie** [comment]
I couldn't find the original project, so I recreated a similar error on a new project (this time I'm using HAML, but same thing):
![rails_failure](https://user-images.githubusercontent.com/20506149/42070115-d4e3cc16-7b09-11e8-811d-6f0091d912a0.png)
Scrolled down:
![rails_failure2](https://user-images.githubusercontent.com/20506149/42070231-4658f9fc-7b0a-11e8-9dfd-6e1f7c143e0c.png)
Now that I notice it, it is sort of formatted when you scroll down. I would much rather it be like this, however (I just made this with Browser DevTools & CSS):
![rails_failure3](https://user-images.githubusercontent.com/20506149/42070405-046fc6a0-7b0b-11e8-85fc-937b63ae1f4d.png)
Maybe of interest: https://github.com/charliesome/better_errors
I don't know much about Rails so I apologize if this is a bad issue.

**Comment by jwinnie** [comment]
Can still reproduce. Rails is ignoring whitespace in errors when presenting them in the browser.

In the terminal:
```
ActionController::UnknownFormat (MainController#main is missing a template for this request format and variant.

request.formats: ["text/html"]
request.variant: []

NOTE! For XHR/Ajax or API requests, this action would normally respond with 204 No Content: an empty white screen. Since you're loading it in a web browser, we assume that you expected to actually render a template, not nothing, so we're showing an error to be extra-clear. If you expect 204 No Content, carry on. That's what you'll get from an XHR or API request. Give it a shot.):
```

In the browser:
```
MainController#main is missing a template for this request format and variant. request.formats: ["text/html"] request.variant: [] NOTE! For XHR/Ajax or API requests, this action would normally respond with 204 No Content: an empty white screen. Since you're loading it in a web browser, we assume that you expected to actually render a template, not nothing, so we're showing an error to be extra-clear. If you expect 204 No Content, carry on. That's what you'll get from an XHR or API request. Give it a shot.
```

**Comment by jwinnie** [comment]
The code is in `actionpack/lib/action_dispatch/middleware/templates/rescues`
