### ISSUE TITLE
Change image on http://localhost:3000

### ISSUE THREAD

**Issue by bogdanvlviv** [rails/rails#33181]
Hello. Currently, we've changed "Yay! You’re on Rails!" image only in the guides.
We should change this on http://localhost:3000/ too.
Ref: https://github.com/rails/rails/blob/master/railties/lib/rails/templates/rails/welcome/index.html.erb#L65

Follow up https://github.com/rails/rails/pull/32735
/cc @asianmack

**Comment by andrewblum** [comment]
This seems like a good first issue for me, all I need to do is convert the new image to base64 and make a PR, yea? Love to do it :)

**Comment by asianmack** [comment]
Go for it 👍

**Comment by bogdanvlviv** [comment]
@andrewblum I just want to note that it should be  a bit cropped image
> This seems like a good first issue for me, all I need to do is convert the new image to base64 and make a PR, yea? Love to do it :)

**Comment by andrewblum** [comment]
@bogdanvlviv I just made a PR wit this image, let me know if its not the one ya wanted and I'll submit another :) 

http://guides.rubyonrails.org/images/getting_started/rails_welcome.png
