### ISSUE TITLE
Next version of PG will deprecate calling async_exec with params

### ISSUE THREAD

**Issue by SamSaffron** [rails/rails#33185]
async_exec should no longer be called with params and instead async_exec_params needs to be used. This pretty enormous deprecation will hit next time PG gem is released so we really got to get it sorted asap.

`/home/sam/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/activerecord-5.2.0/lib/active_record/connection_adapters/postgresql_adapter.rb:603: warning: forwarding async_exec to async_exec_params and send_query to send_query_params is deprecated`

(anyone using prepared statements will be impacted)

Example gist:

https://gist.github.com/2f3ed36aa4b7ff0875e035634eff3ff2

cc @larskanis

**Comment by matthewd** [comment]
Hmm.. @larskanis this doesn't seem worth immediately deprecating to me?

It's definitely an inconsistency, but I'm not sure it's worth punishing existing callers to clean it up. Fixing Rails master is simple enough, but it's going to discourage people from upgrading `pg` in older Rails releases, which seems unfortunate.

**Comment by larskanis** [comment]
I had this already prepared and opened the change as PR #33188  now.
