### ISSUE TITLE
Behavior of scopes with subqueries

### ISSUE THREAD

**Issue by caiammm** [rails/rails#33195]
### Steps to reproduce
download this project https://github.com/caiammm/rails_5_active_record_sub_queries
set up the project

consider the following scopes:
```
  scope :latest_by_article, -> {
    where(id: Comment.select("DISTINCT ON (article_id) id").
    order("article_id, comments.created_at DESC"))
  }
```
```
  scope :latest_by_article_with_unscoped, -> {
    where(id: Comment.unscoped.select("DISTINCT ON (article_id) id").
    order("article_id, comments.created_at DESC"))
  }
```

in rails console:
```
puts Comment.where(article_id: [1,2]).latest_by_article.to_sql
```

```
puts Comment.where(article_id: [1,2]).latest_by_article_with_unscoped.to_sql
```

### Expected behavior
The first where clause (`where(article_id: [1,2])`) won't affect the subqueries from either scope. 

```
SELECT "comments".* 
FROM "comments" 
==> WHERE "comments"."article_id" IN (1, 2) 
AND "comments"."id" IN (
  SELECT DISTINCT ON (article_id) id 
  FROM "comments" 
  ORDER BY article_id, comments.created_at DESC
)
```

### Actual behavior
The outer where clause (`where(article_id: [1,2])`) affects the subquery in the latest_by_article scope.

```
SELECT "comments".* 
FROM "comments" 
==> WHERE "comments"."article_id" IN (1, 2) 
AND "comments"."id" IN (
  SELECT DISTINCT ON (article_id) id 
  FROM "comments" 
  ==> WHERE "comments"."article_id" IN (1, 2) 
  ORDER BY article_id, comments.created_at DESC
)
```
### System configuration
**Rails version**:
5.2.0
**Ruby version**:
ruby 2.3.5p376

**Comment by microweb10** [comment]
Looking at this issue, and after doing some investigations, a few questions came to my mind. Please allow me to ask:

1. Is this SQL statement valid? Apparently is NOT
```
SELECT "comments".*
FROM "comments"
WHERE "comments"."article_id" IN (1, 2) AND "comments"."id"
IN (
  SELECT DISTINCT ON (article_id) article_id
  FROM "comments"
  ORDER BY article_id, article.created_at DESC
)
```
2. Shouldn't you create the scope you want to achieve in a different/easier way?

3. Is the current behavior actually the expected behavior? Since in the second scope you are actually unscoped the query.

4. Assuming all my previous questions are wrong or not important. And also assuming the SQL was correct. What is the difference between your "expected behavior" and "actual behavior"? Are they not just returning the same result set?

**Comment by caiammm** [comment]
@microweb10 
1 - yea, i saw now that isn't valid... I'm going to update.

2 - well, I don't know... we are using postgresql. DISTINC ON is a really good tool to get the first occurrence given a column. I think it's easy and understandable enough.

3 - No, the actual behaviour is that the `where`s clauses outside is going inside the subquery.

4 - They don't return the same result. Because of the where outside changing the result inside te subquery.

I'll give more steps to show the inconsistency.

```
math = Article.create(name: 'Math article')
english = Article.create(name: 'English article')

c1 = Comment.create(article_id: math.id)
c2 = Comment.create(article_id: math.id)
c3 = Comment.create(article_id: math.id) #this is the last that I Want

c4 = Comment.create(article_id: english.id)
c5 = Comment.create(article_id: english.id)
c6 = Comment.create(article_id: english.id) #this is the last that I Want

ids = [c1.id, c2.id, c3.id, c4.id, c5.id] 


#should not contain the c5 (given that the c6 is the last about the english article)
result = Comment.where(id: ids).latest_by_article.pluck(:id)


#with unscopped in the subquery works. And I think it should be the default behaviour
#returning only the c3
result2 = Comment.where(id: ids).latest_by_article_with_unscoped.pluck(:id)

```

**Comment by microweb10** [comment]
Well, allow me to disagree with you about one thing.

In your initial question you say:
`puts Comment.where(article_id: [1,2]).latest_by_article.to_sql`
So you filter by article_id (NOT by comment.id). And in that case, they 2 queries that you posted will return the same result set. Am I wrong?

Now you say
`result = Comment.where(id: ids).latest_by_article.pluck(:id)`
Which is a completely different thing

Maybe an idea: Have you tried to swap the query and the scope? I think it should work for you:
`result = Comment.latest_by_article.where(id: ids).pluck(:id)`

**Comment by caiammm** [comment]
Yea, the point is to show that the `where` clause is going inside the subquery of the scope.

Changing the order of the query and the scope works, but consider this situation:
Think if you have a relation from other previous queries, which there were many clauses applied. So the subquery shouldn't be influenced by other `where`s. 

My scope is to get the ID from the last comment by each article. Many `where`s clauses from outside can destroy/change the result set from the subquery. 

And I showed it on the previous answer https://github.com/rails/rails/issues/33195#issuecomment-402779848

**Comment by microweb10** [comment]
I know what is your point, but I still think that the fact that the query is going inside the scope will not affect the final result set if the scope is defined correctly. In my opinion, using `unscoped` inside a scope is not a good practice, having in consideration that scope can be applied after some queries. And when you define a scope you should consider that, that you are applying a query to a previous result set. At least that is how I understand scopes. But again, that's only my opinion. Let's see what the Rails guys think about this issue and if they approve it :)

**Comment by cir27** [comment]
Hello i am new on github and i need to lean

**Comment by caiammm** [comment]
keeps happening in version 5.2.3

**Comment by typhoon2099** [comment]
I'm having the same issue in Rails 5.2.0. I have a rather complex query and I'm trying to add multiple scopes, one of which contains a subquery. In this case I end up with an insanely large query which adds a ton of conditions to a large table, causing my database to grind to a halt.

**Comment by j3ck** [comment]
has this been fixed ?
