### ISSUE TITLE
Actions are executed twice if no response is returned from controller method

### ISSUE THREAD

**Issue by peteygao** [rails/rails#33214]
If a controller has `skip_before_action :verify_authenticity_token, if: :action` applied to the `action` method, AND the controller *does not* return an HTTP response (via `head`, `render`, etc.), then the action gets executed *twice* 2️⃣✖️😱!

### Steps to reproduce

Create a new Rails project from scratch:
```bash
rails new double_the_trouble
cd double_the_trouble
rails g controller double
```

Edit `app/controllers/double_controller.rb` and make it look like this:
```ruby
class DoubleController < ApplicationController
  skip_before_action :verify_authenticity_token, if: :double

  def double
    Rails.logger.info "This should only show up once"
  end
end
```

Edit `config/routes.rb` and make it look like this:
```ruby
Rails.application.routes.draw do
  post 'double', to: :double, controller: :double
end
```

Let's go into Rails Console and see this big bad 🐛 in action:
```
$ rails c
Running via Spring preloader in process 89303
Loading development environment (Rails 5.2.0)
irb(main):001:0> app.post('/double')
Started POST "/double" for 127.0.0.1 at 2018-06-24 19:28:55 -0700
Processing by DoubleController#double as HTML
This should only show up once
This should only show up once      <--------- HMMMMM 👻
No template found for DoubleController#double, rendering head :no_content
Completed 204 No Content in 182ms (ActiveRecord: 0.0ms)


=> 204
```

### Expected behavior

The `Rails.logger.info` output "This should only show up once" should show up once.

### Actual behavior

Instead, it shows up twice. Here's the exact output via the request log:
```bash
Started POST "/double" for 127.0.0.1 at 2018-06-24 19:23:11 -0700
Processing by DoubleController#double as HTML
This should only show up once
This should only show up once
No template found for DoubleController#double, rendering head :no_content
Completed 204 No Content in 264ms (ActiveRecord: 0.0ms)
```

Having the `skip_before_action` is crucial to reproduce this bug! Without it, this bug does not occur! I have not tried skipping other actions other than `:verify_authenticity_token`.

It is also crucial that the request DOES NOT return a valid response. If you add `head :ok`, then the bug goes away. As does removing `skip_before_action`.

### System configuration
**Rails version**: 5.2.0

**Ruby version**: 2.5.1p57

**Comment by matthewd** [comment]
Are you looking for `skip_before_action :verify_authenticity_token, only: :action`?

The value for `if:` is a controller instance method that returns a boolean value indicating whether the skip should apply (and will thus always be called in making that decision). Using an action name in there is not expected.

**Comment by peteygao** [comment]
@matthewd Holy smokes, what an elementary mistake... Yes, you're right. Now that you pointed it out, it makes complete sense why it would execute that action "twice"... Once to test for `if` condition, and the second time to actually run the damn thing!

🤦‍♂️ Mega facepalm. Closing this ticket.
