### ISSUE TITLE
What happened to the Arel README quick reference?

### ISSUE THREAD

**Issue by wakproductions** [rails/rails#33228]
When the Arel repo got moved into rails/rails, the README docs disappeared. That doc had a handy quick reference for using the Arel methods. Where is that info now?

Here's what it used to be: https://web.archive.org/web/20170813135529/https://github.com/rails/arel

**Comment by y-yagi** [comment]
Arel was never part of the public API of the framework, so we don't provide public documentation(At least for the moment).
If you want to see Arel's past public API, you can still check with rails/arel. 
https://github.com/rails/arel/blob/v9.0.0/README.md
