### ISSUE TITLE
Rails 5.2 Can't open rails credentials with Sublime Text

### ISSUE THREAD

**Issue by AleksandarTokarev** [rails/rails#33222]
I am using Windows Subsystem for Linux (Ubuntu) with Rails 5.2 and Sublime Text 3. When i do

EDITOR="subl --wait" rails credentials:edit

It says "New credentials encrypted and saved." but does not open the file to be edited with Sublime Text 3. I have subl command set to open Sublime Text 3 in bash profile. Also when trying Visual Studio Code with

EDITOR="code--wait" rails credentials:edit

Visual Studio Code opens but it is empty.

I can only edit the file with VIM and the command EDITOR="vim" rails credentials:edit

The thing is i do not want to edit the file with vim. What is the problem so it does not open the file to be edited with Sublime or VS Code?

I am using Rails 5.2

Thanks a lot in advance
![image](https://user-images.githubusercontent.com/6853997/41876744-22ccc6b8-78cf-11e8-9ddd-e7f67b4f7808.png)

**Comment by y-yagi** [comment]
I tried Sublime Text 3(v3.1.1, Build 31176) with wait option, but it works expected.
So I assumed this is your environment issue. 

Please use the [mailing list](https://groups.google.com/forum/#!forum/rubyonrails-talk) or StackOverflow for questions/help, where a wider community will be able to help you. We reserve the issues tracker for issues only. Thanks.
