### ISSUE TITLE
ActiveRecord::Relation#update! missing?

### ISSUE THREAD

**Issue by jamesstonehill** [rails/rails#33226]
Why is there no `!` version of the [`ActiveRecord::Relation#update` method](https://apidock.com/rails/ActiveRecord/Relation/update)? Seems like its absence defies the convention.

**Comment by rafaelfranca** [comment]
Thank you so much for the issue but we don't take feature request on the issue tracker. We recommend you to try to implement the feature and send us a pull request or if you are in doubt if the feature will be accepts ask in Rails Core mailing list for feedback.

**Comment by sikachu** [comment]
@jamesstonehill please let me know if you plan to submit a patch for this, otherwise I I'll try to write one to target Rails 6.0.

**Comment by jamesstonehill** [comment]
Feel free to work on this, but there is no longer an `ActiveRecord::Relation#update` method, it was removed here https://github.com/rails/rails/commit/9ac7dd47c5e847f7dbfb8d527ee2b917fa9fcd38#diff-eb992cfe9de67b368e9d3736ab1388d8

I think though that area could do with some thought anyway.
