### ISSUE TITLE
Outdated ActiveModel::Serialization guide

### ISSUE THREAD

**Issue by Bartuz** [rails/rails#33235]
In 1.8 section in [ActiveModel Basics guide](http://guides.rubyonrails.org/active_model_basics.html) we can read that

> Attributes must be strings, not symbols.

as far as I know, this is not valid anymore (but I might be very wrong, please correct me). Defining `def attributes` with symbols serializes model properly

**Comment by kamipo** [comment]
Looks like that `only` and `except` options doesn't work if `attributes` returns symbolized keys.

**Comment by rafaelfranca** [comment]
Yes, it should be strings.
