### ISSUE TITLE
Wrong limit results on eager loading with order on secondary table in PostgreSQL

### ISSUE THREAD

**Issue by Envek** [rails/rails#33239]
### Steps to reproduce

Executable test: https://gist.github.com/Envek/69173aad493316881e2d6853181b9166

Create two related (via `has_many`) tables in PostgreSQL database, fill them with the appropriate amount of data (with more records on `has_many side), eager load them with limit and sorting on columns of both tables:
```ruby
Post.eager_load(:comments).order("posts.created_at DESC, comments.created_at ASC").limit(2)
```

### Expected behavior
The number of records of the primary model should be equal to requested by `limit`.

### Actual behavior
The number of records of the primary model is less depending on the count of `has_many` records.

### System configuration
**Rails version**: 5.2.0
**Ruby version**: 2.5.1

### Details

Since some fresh ActiveRecord versions (can't find PR with that change) `limit` on a relation with eager load started to issue two queries: one to find exact ids of records of primary model and second to actually fetch them.

So now one can safely use `eager_load` with `limit` and get correct (expected) results. Yay!

But there is one problematic combination: it is a PostgreSQL database and ordering on both tables (or only eager loaded one).

The reason is PostgreSQL forbids queries with `DISTINCT` and ordering on columns not included in `SELECT` clause:

```
SELECT DISTINCT posts.id 
FROM posts LEFT OUTER JOIN comments ON posts.id = comments.post_id 
ORDER BY posts.id ASC, comments.id ASC 
LIMIT 2;
ERROR:  for SELECT DISTINCT, ORDER BY expressions must appear in select list
LINE 1: ...osts.id = comments.post_id ORDER BY posts.id ASC, comments.i...
```

Because of that somewhere in ActiveRecord (or Arel) columns from order clause are added to select clause, so it is started to behave incorrectly (returns number of `has_many` records, not of the main model ones!):

```
SELECT DISTINCT posts.id AS alias_0, comments.id AS alias_1, posts.id
FROM posts LEFT OUTER JOIN comments ON posts.id = comments.post_id 
ORDER BY posts.id ASC, comments.id ASC 
LIMIT 2;
 alias_0 | alias_1 | id 
---------+---------+----
       1 |       1 |  1
       1 |       2 |  1

       ^ we got two same ids here :-(
```

**This is being done only for PostgreSQL.** SQLite has no such limitation and eager_load with ordering works correctly in it. Didn't test in MySQL.

### Possible solution

For PostgreSQL replace that helper query with a different query using `row_number` window function (exists at least from 8.4 so safe to use everywhere: [docs](https://www.postgresql.org/docs/8.4/static/functions-window.html)):

```sql
SELECT id FROM (
  SELECT 
    posts.id AS id,                                         -- post ids with duplications
    row_number() OVER (PARTITION BY posts.id) AS row_number -- marks unique post ids
  FROM posts LEFT OUTER JOIN comments ON posts.id = comments.post_id 
  WHERE posts.id NOT IN (0)                                 -- any restrictions applied to relation goes here
  ORDER BY posts.position DESC, comments.position ASC       -- requested ordering
) subquery
WHERE row_number = 1  -- takes only unique ids
OFFSET 0 LIMIT 2;     -- here it works as usual and as expected
```
_I've edited SQL as at first try I've proposed wrong one_

---

I would be glad to make a Pull Request with a fix but not even know where to start to dig.

Requesting help and suggestions from @sgrif and @kamipo as people who knows ActiveRecord very well.

Is there any workarounds I can apply as quick band-aid solution?

**Comment by Envek** [comment]
Yes, this is still an issue on 5.2.1 and 6.0.0.alpha (current master). Please remove the stale label.

**Comment by macejmic** [comment]
Running latest `6.1.3` and this is still an issue.

**Comment by eshtiaqahmad** [comment]
We are getting same issue, when we eager load with limit and apply sorting on child tables. It does not render results correctly and skips data rows.

**Comment by daudsd** [comment]
I was having this issue from 3 months and today I saw this reported issue. Maintainers please have a look at this issue. It is causing some serious damage to my search results while using eager loading with order and limit on child tables.

**Comment by Envek** [comment]
Recently I tend to avoid eager loading due to performance implications of LEFT JOIN queries (larger result sets, etc) and use preloading instead.

In case if default scopes (which IMO are evil) or [`has_many` scopes](https://guides.rubyonrails.org/association_basics.html#scopes-for-has-many) can't serve you for that, there is one possible workaround: use [Preloader](https://www.rubydoc.info/docs/rails/ActiveRecord/Associations/Preloader) directly (however this API is not documented: see discussion at #36638):
```
@posts = Post.order(created_at: :desc).limit(2)
ActiveRecord::Associations::Preloader.new.preload(@posts, :comments, Comment.order(created_at: :asc))
```

**Comment by daudsd** [comment]
@Envek I am aware of this solution, but in my case I have to use eager_load because I am sorting my whole records based on children table columns as well which cannot be done using preloading as it fires one query for each association.
