### ISSUE TITLE
:blank? method is broken on Object in activesupport

### ISSUE THREAD

**Issue by frontandstart** [rails/rails#33231]
### System configuration
**Rails version**: 5.2.0
**Ruby version**: 2.5.1

### Steps to reproduce
Create any new model and record or use already exist and try to find record with ActiveRecord in rails console.
Then check with :blank? method 
for example:
`Invoice.last.blank?`
### Expected behavior
:blank? on existing record should return:
`false`
because record exist 
### Actual behavior
return:
`true`
Record exist but active support told me - not. 
I start dig and found that in [active_support/core_ext/object/blank.rb](https://github.com/rails/rails/blob/316513177cf9033d842cc176f8401d4e7c7e7c2a/activesupport/lib/active_support/core_ext/object/blank.rb#L20) use :empty? method
but :empty? its for arrays, hash and for Object we should use nil?
Then I make fast fix in my local gem source to
```ruby
def blank?
  respond_to?(:nil?) ? !!nil? : !self. 
end
```
And now works as expected.
Thanks.

**Comment by sikachu** [comment]
Quoting from my comment in your PR:

> From the documentation:
> 
> > An object is blank if it's false, empty, or a whitespace string.
> 
> I think that is already accurate. `nil` is not false, and `nil` is, surprisingly, is not empty:
> 
> ```ruby
> > nil.empty?
> NoMethodError: undefined method `empty?' for nil:NilClass
> ```

But to be honest, now I wonder if we should make `blank?` exists on object that doesn't respond to `empty?` ... that's another discussion though. 😄
