### ISSUE TITLE
has_many-through-join-model record is incomplete in `after_add` and `before_add` callbacks

### ISSUE THREAD

**Issue by dsager** [rails/rails#33249]
With a `has_many` association defined with a `through` option, the callbacks `before_add` and `after_add` of the join model are called with incomplete data. The second argument is missing the target reference.

This is a problem when one of these callbacks causes the owner object to be saved - the DB raises a not-null constraint violation. I was able to work around this in our code by defining my callbacks on the `has_many` association, but I still think the behavior is confusing.

From a quick debug session, the culprit seems to be 
[`ActiveRecord::Associations::HasManyThroughAssociation#build_through_record`](https://github.com/rails/rails/blob/832b7a7ca330a38235d9bdecb18fa9dbf4ed156f/activerecord/lib/active_record/associations/has_many_through_association.rb#L60-L61). Here, `through_association.build` triggers the callback, but only after that the source record is set. Not sure if including it in `options_for_through_record` would be a possible fix?

### Steps to reproduce

```ruby
# frozen_string_literal: true

begin
  require "bundler/inline"
rescue LoadError => e
  $stderr.puts "Bundler version 1.10 or later is required. Please update your Bundler"
  raise e
end

gemfile(true) do
  source "https://rubygems.org"

  # Activate the gem you are reporting the issue against.
  gem "activerecord", "5.2.0"
  gem "sqlite3"
end

require "active_record"
require "logger"

# This connection will do for database-independent bug reports.
ActiveRecord::Base.establish_connection(adapter: "sqlite3", database: ":memory:")
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :consultants, force: true
  create_table :purposes, force: true
  create_table :consultants_purposes, id: false do |t|
    t.integer :consultant_id
    t.integer :purpose_id
  end
end

class Consultant < ActiveRecord::Base
  has_many :consultants_purposes,
           before_add: ->(_consultant, consultant_purpose) {
             puts '-' * 80, consultant_purpose.attributes, '-' * 80
           },
           after_add: ->(_consultant, consultant_purpose) {
             puts '+' * 80, consultant_purpose.attributes, '+' * 80
           }
  has_many :purposes, through: :consultants_purposes
end

class Purpose < ActiveRecord::Base
  has_many :consultants_purposes
end

class ConsultantsPurpose < ActiveRecord::Base
  belongs_to :consultant
  belongs_to :purpose
end

consultant = Consultant.create!
consultant.purposes << Purpose.create!
# This produces the expected output:
# consultant.consultants_purposes.create(purpose: Purpose.create!)
```

### Expected behavior
The output should include both a valid `consultant_id` and `purpose_id`, for example:
```
--------------------------------------------------------------------------------
{"consultant_id"=>1, "purpose_id"=>1}
--------------------------------------------------------------------------------
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
{"consultant_id"=>1, "purpose_id"=>1}
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
```

### Actual behavior
The `purpose_id` in the output is `nil`:
```
--------------------------------------------------------------------------------
{"consultant_id"=>1, "purpose_id"=>nil}
--------------------------------------------------------------------------------
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
{"consultant_id"=>1, "purpose_id"=>nil}
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
```

### System configuration

**Rails version**: Rails 5.2.0
**Ruby version**: ruby 2.4.1p111 (2017-03-22 revision 58053) [x86_64-linux]

**Comment by dsager** [comment]
I can still reproduce the issue described above with the following versions:
```
activesupport 5.2.1
activemodel 5.2.1
activerecord 5.2.1
```

**Comment by leboshi** [comment]
I'm also having this issue in Rails 5.2.2.1.  I'm making a PR to address the issue.
