### ISSUE TITLE
DEPRECATION WARNING does not show for module in rails 5.2 but works with class

### ISSUE THREAD

**Issue by pvin** [rails/rails#33253]
### Rails 4.1.8 Ruby 2.2.0p0

```
module Fred
  extend self
  def aaa; end
  def bbb; end
  def ccc; end
  def ddd; end
  def eee; end
end

module Bar
  extend self
  def ccc; end
end

ActiveSupport::Deprecation.deprecate_methods(
  Fred, :aaa, bbb: :zzz, ccc: 'use Bar#ccc instead'
)

Fred.aaa

DEPRECATION WARNING: aaa is deprecated and will be removed
  from Rails 4.2. (called from \__pry__ at (pry):15)
#=> nil

```
### Same code tried in rails 5.2.0 but no DEPRECATION WARNING.

So what i'm missing here, DEPRECATION WARNING has new update with rails 5.2.0 and will not warn for module?

**Comment by utilum** [comment]
I can confirm this behvior reproduces locally on master as well. When did it change?

**Comment by Edouard-chin** [comment]
Ran a bisect, the commit that introduced this change was in https://github.com/rails/rails/commit/a982a42d766169c2170d7f100c2a5ceb5430efb1

**Comment by pvin** [comment]
@prathamesh-sonpatki  Thank you
