### ISSUE TITLE
need mysqld.sock

### ISSUE THREAD

**Issue by vignesh080** [rails/rails#33274]
by mistake i delete mysqld.sock..in kali linux so i cant able to anything.please help me what i have to do and i can't able to process metasploit also 
![screenshot from 2018-07-02 14-10-42](https://user-images.githubusercontent.com/39151339/42153942-20a75c4e-7e02-11e8-8690-79a14c764ac2.png)

**Comment by matthewd** [comment]
Please use the mailing list or StackOverflow for questions/help, where a wider community will be able to help you. We reserve the issues tracker for issues only.
