### ISSUE TITLE
issue in metasploit 

### ISSUE THREAD

**Issue by vignesh080** [rails/rails#33275]
how to solve this
![screenshot from 2018-07-02 14-14-53](https://user-images.githubusercontent.com/39151339/42154047-692b8e2c-7e02-11e8-9d07-2e0216477437.png)

**Comment by matass** [comment]
try
`gem install rake`
`bundle install`

**Comment by vignesh080** [comment]
![screenshot from 2018-07-02 14-29-47](https://user-images.githubusercontent.com/39151339/42154835-6ccf91fc-7e04-11e8-9d7e-652487d5a274.png)

**Comment by matthewd** [comment]
Please use the mailing list or StackOverflow for questions/help, where a wider community will be able to help you. We reserve the issues tracker for issues only.
