### ISSUE TITLE
packeges have unmet dependencies

### ISSUE THREAD

**Issue by vignesh080** [rails/rails#33276]
apt-get upgrade
![screenshot from 2018-07-02 14-23-14](https://user-images.githubusercontent.com/39151339/42154536-a5ba282a-7e03-11e8-8d9f-d72147353dac.png)

apt --fix-broken install

![screenshot from 2018-07-02 14-25-50](https://user-images.githubusercontent.com/39151339/42154693-0af9e5e0-7e04-11e8-8c48-e27176ff7695.png)

**Comment by matthewd** [comment]
Please use the mailing list or StackOverflow for questions/help, where a wider community will be able to help you. We reserve the issues tracker for issues only.
