### ISSUE TITLE
Can't complete a bundler install on rails 5

### ISSUE THREAD

**Issue by DanielPeckham** [rails/rails#33279]
I am trying to build my first rails application on windows and it quits when bundling at capybara 3.3.1

It should be fine because I have ruby version 2.5.1p57

It thinks I have Ruby version 2.2.6 

Here is my error:
Gem::InstallError: capybara requires Ruby version >= 2.3.0.
An error occured while installing capybara (3.3.1), and Bundler cannot
continue.
Make sure that `gem install capybara -v '3.3.1'` succeeds before bundling.

I then input the command gem install capybara -v '3.3.1' into my git bash and it succeeds with no problem. Then when I try to re-bundle, it fails with the same error again. Am I missing a step?

**Comment by kamipo** [comment]
Please use the mailing list or StackOverflow for questions/help, where a wider community will be able to help you. We reserve the issues tracker for issues only.
