### ISSUE TITLE
ActiveStorage in Rails API or GraphQL

### ISSUE THREAD

**Issue by arefaslani** [rails/rails#33281]
ActiveStorage is cool. But I think it's premature baby of the Rails framework. It released pretty early IMO. It lacks many features like blob validation. I implemented a [simple validation](https://stackoverflow.com/questions/48158770/activestorage-file-attachment-validation/50997991#50997991) for myself. But I have another problem. I use Rails API with a React SPA as frontend application. Theres no documentation on how to use ActiveStorage with Rails API. Also in RailsConf 2018 I saw Nick introducing GraphQL as the new path for JSON APIs. Isn't it a good idea to document how to use ActiveStorage with Rails API or GraphQL?

**Comment by georgeclaghorn** [comment]
:+1: for demonstrating Active Storage usage in an API-only app.

Rails itself doesn’t support GraphQL—it’s supported by third-party libraries—so we’re unlikely to do anything about that.

**Comment by kaspth** [comment]
> the new path for JSON APIs

You're certainly welcome to use GraphQL, but there's no work being done to consider it the "new" path by Rails as of this writing 😊

I'm also 👍 to demonstrating Active Storage with API-only apps. I'll close this as a "feature" request which we don't keep open on the issues tracker. Thanks!
