### ISSUE TITLE
`t.references` doesn't raise an error on non-existent options

### ISSUE THREAD

**Issue by georgewambold** [rails/rails#33284]
### Steps to reproduce

1. Create a migration
2. Use `create_table` to add a table called `:users` like this:
```
create_table :users, force: true do |t|
end
```
3. Use `create_table` to add a table called `:posts` that references `:users` like this:
```
create_table :posts, force: true do |t|
  t.references :users, nnull: false, uniqe: true 
end
```
 \*\*\*\* NOTE that 'nnull' and 'uniqe' are non-existent options!! \*\*\*\*
 
4. Run the migration

I created a runnable gist to illustrate the issue here: https://gist.github.com/georgewambold/16ee14cb0e5ca77b35ff3c94b4537475

### Expected behavior
An error should be raised

### Actual behavior
The migration changes are commited without raising an error

### System configuration
**Rails version**: 6.0.0.alpha

**Ruby version**: 2.5.1

### Other notes
This is my first issue and I'd love to write the fix if the issue is accepted. 

This issue is similar to [issue 8104](https://github.com/rails/rails/issues/8104) and [PR 32675](https://github.com/rails/rails/pull/32675)

**Comment by sikachu** [comment]
Looks like this is a good use case for [`assert_valid_keys`](http://api.rubyonrails.org/classes/Hash.html#method-i-assert_valid_keys) as long as we make it extendable for other gems owner _just in case_.

Do you plan to submit a PR for this?

**Comment by azbshiri** [comment]
I'd love to work on this.

**Comment by georgewambold** [comment]
@sikachu Yes, I plan on submitting a PR

**Comment by georgewambold** [comment]
Here's a first draft of the PR https://github.com/rails/rails/pull/33347
