### ISSUE TITLE
new_framework_defaults loads too late

### ISSUE THREAD

**Issue by jdelStrother** [rails/rails#33283]
### Steps to reproduce

* Start with a legacy 5.1 rails app with a number of gems that don't obey lazy loading, so cause ActiveRecord::Base/ActionController::Base to load during `Bundler.require :default`
* upgrade it to 5.2, adding the new_frameworks_defaults_5_2.rb file to config/initializers
* flip `Rails.application.config.active_record.cache_versioning` or `Rails.application.config.action_controller.default_protect_from_forgery` to true in the new_frameworks_defaults file.

### Expected behavior
ActionController::Base.default_protect_from_forgery and ActiveRecord::Base.cache_versioning are both set to true.

### Actual behavior
ActionController::Base.default_protect_from_forgery and ActiveRecord::Base.cache_versioning remain at their Rails 5.1 default value of false, because the config values are only applied to the actual class when `Base` is first loaded.

https://github.com/rails/rails/issues/27638 is somewhat related

I'm surprised this isn't a more common problem.  You can avoid it if all your gems are well behaved and don't load AR::Base / AC::Base during boot, but I've seen an awful lot of gems that aren't that careful.  Are we the only ones running into this?

### System configuration
**Rails version**: 5.2

**Ruby version**: 2.3

**Comment by rafaelfranca** [comment]
You are running in bugs in the gems your have. Gems should not load AR::Base / AC::Base during boot, so the right way to fix the problem is open issues in the gems that behaves in this way and fix them.

**Comment by jdelStrother** [comment]
Thanks for confirming.   Is this requirement documented anywhere?   I couldn't seem to find it.

Does the same apply to ActionView::Base & ActionMailer::Base?   Obviously, ideally you wouldn't load those, but it seems easy to load them accidentally.  For instance, Airbrake references ActionDispatch::DebugExceptions, which then loads ActionView::Base (https://github.com/airbrake/airbrake/blob/master/lib/airbrake/rails.rb#L18).

**Comment by rafaelfranca** [comment]
Yes, it is documented here http://guides.rubyonrails.org/engines.html#active-support-on-load-hooks.

It applies to all Rails frameworks that have hooks.
