### ISSUE TITLE
rails db:migrate not giving an error but also not doing any migrations

### ISSUE THREAD

**Issue by CodefulDom** [rails/rails#33290]
### Steps to reproduce
1. Go to the root of the directory
2. Run a new generator with postgresql set as the db
3. Run `rails db:create` completes without issue.
4. Run `rails db:migrate` no errors are in log file or terminal, but there is also no migration file in the project.
5. Run `rails db:migrate:status`no entries under migrations at all

(Guidelines for creating a bug report are [available
here](http://edgeguides.rubyonrails.org/contributing_to_ruby_on_rails.html#creating-a-bug-report))

### Expected behavior
Tell us what should happen
after the project has been created and the command for migration is completed, a migration should be executed and shown in the migration file in the project
### Actual behavior
Tell us what happens instead
No error is given, but no migration is created either
### System configuration
**Rails version**:
5.1.2
**Ruby version**:
2.4.0(also tried with 2.5.1)

<img width="607" alt="screen shot 2018-07-03 at 11 55 50 pm" src="https://user-images.githubusercontent.com/28935096/42257557-a39c1c28-7f1c-11e8-98a6-2fb4cdebc219.png">

<img width="948" alt="screen shot 2018-07-03 at 11 57 17 pm" src="https://user-images.githubusercontent.com/28935096/42257602-d9225a9c-7f1c-11e8-8d1d-9d5444d4985a.png">

<img width="374" alt="screen shot 2018-07-03 at 11 57 48 pm" src="https://user-images.githubusercontent.com/28935096/42257629-08e9ad48-7f1d-11e8-9136-4e7c626ea4e8.png">

<img width="602" alt="screen shot 2018-07-03 at 11 58 21 pm" src="https://user-images.githubusercontent.com/28935096/42257625-001a1aea-7f1d-11e8-8a04-5997927d10b3.png">

https://drive.google.com/file/d/1rD36XR5JHX3ZymrPCf9ewDV22GFaKH0v/view?usp=sharing

**Comment by jashkothari** [comment]
Hey since you already have the database the as in this photograph no migrations will run. Since the ar schema migrations table will have all migrations as run in it.

![](https://user-images.githubusercontent.com/28935096/42257557-a39c1c28-7f1c-11e8-98a6-2fb4cdebc219.png)

Please run the following sequence

+ rails db:drop
+ rails db:create
+ rails db:migrate
+ rails db:migrate:status

And post back the results.

**Comment by CodefulDom** [comment]
Same outcome. No migration created. The server starts fine but I think that is a result of the creation of the tables, correct? I would assume this is something I missed in the setup of the db. I included screenshots of where I think the db information is supposed to be and not seeing any reference to postgres at all
<img width="583" alt="screen shot 2018-07-04 at 12 56 14 am" src="https://user-images.githubusercontent.com/28935096/42259296-74103bf2-7f25-11e8-8597-d42780f2adad.png">
<img width="273" alt="screen shot 2018-07-04 at 12 56 55 am" src="https://user-images.githubusercontent.com/28935096/42259297-779ea542-7f25-11e8-9872-35efc0332e9d.png">
<img width="504" alt="screen shot 2018-07-04 at 12 57 12 am" src="https://user-images.githubusercontent.com/28935096/42259301-7b631172-7f25-11e8-9877-08b8c78f7f90.png">
<img width="599" alt="screen shot 2018-07-04 at 12 57 30 am" src="https://user-images.githubusercontent.com/28935096/42259303-7ed1a990-7f25-11e8-80e0-309238677114.png">
<img width="1198" alt="screen shot 2018-07-04 at 12 41 20 am" src="https://user-images.githubusercontent.com/28935096/42259306-83a37c1e-7f25-11e8-8af6-53efe6a2431c.png">

`ruby '2.4.0'

# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '~> 5.2.0'
# Use postgresql as the database for Active Record
gem 'pg', '>= 0.18', '< 2.0'
# Use Puma as the app server
gem 'puma', '~> 3.11'
# Use SCSS for stylesheets
gem 'sass-rails', '~> 5.0'
# Use Uglifier as compressor for JavaScript assets
gem 'uglifier', '>= 1.3.0'
# See https://github.com/rails/execjs#readme for more supported runtimes
# gem 'mini_racer', platforms: :ruby

# Use CoffeeScript for .coffee assets and views
gem 'coffee-rails', '~> 4.2'
# Turbolinks makes navigating your web application faster. Read more: https://github.com/turbolinks/turbolinks
gem 'turbolinks', '~> 5'
# Build JSON APIs with ease. Read more: https://github.com/rails/jbuilder
gem 'jbuilder', '~> 2.5'
# Use Redis adapter to run Action Cable in production
# gem 'redis', '~> 4.0'
# Use ActiveModel has_secure_password
# gem 'bcrypt', '~> 3.1.7'

# Use ActiveStorage variant
# gem 'mini_magick', '~> 4.8'

# Use Capistrano for deployment
# gem 'capistrano-rails', group: :development

# Reduces boot times through caching; required in config/boot.rb
gem 'bootsnap', '>= 1.1.0', require: false

group :development, :test do
  # Call 'byebug' anywhere in the code to stop execution and get a debugger console
  gem 'byebug', platforms: [:mri, :mingw, :x64_mingw]
end

group :development do
  # Access an interactive console on exception pages or by calling 'console' anywhere in the code.
  gem 'web-console', '>= 3.3.0'
  gem 'listen', '>= 3.0.5', '< 3.2'
  # Spring speeds up development by keeping your application running in the background. Read more: https://github.com/rails/spring
  gem 'spring'
  gem 'spring-watcher-listen', '~> 2.0.0'
end


# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
gem 'tzinfo-data', platforms: [:mingw, :mswin, :x64_mingw, :jruby]`

**Comment by CodefulDom** [comment]
```
current directory: /Users/thedom/.rvm/gems/ruby-2.4.0/gems/puma-3.6.2/ext/puma_http11
/Users/thedom/.rvm/rubies/ruby-2.4.0/bin/ruby -r ./siteconf20180704-53127-7r249p.rb extconf.rb
checking for BIO_read() in -lcrypto... yes
checking for SSL_CTX_new() in -lssl... yes
checking for openssl/bio.h... yes
creating Makefile

current directory: /Users/thedom/.rvm/gems/ruby-2.4.0/gems/puma-3.6.2/ext/puma_http11
make "DESTDIR=" clean

current directory: /Users/thedom/.rvm/gems/ruby-2.4.0/gems/puma-3.6.2/ext/puma_http11
make "DESTDIR="
compiling http11_parser.c
ext/puma_http11/http11_parser.rl:111:17: warning: comparison of integers of different signs: 'long' and 'unsigned long' [-Wsign-compare]
  assert(pe - p == len - off && "pointers aren't same distance");
         ~~~~~~ ^  ~~~~~~~~~
/usr/include/assert.h:93:25: note: expanded from macro 'assert'
    (__builtin_expect(!(e), 0) ? __assert_rtn(__func__, __FILE__, __LINE__, #e) : (void)0)
                        ^
ext/puma_http11/http11_parser.c:43:18: warning: unused variable 'puma_parser_en_main' [-Wunused-const-variable]
static const int puma_parser_en_main = 1;
                 ^
2 warnings generated.
compiling io_buffer.c
compiling mini_ssl.c
mini_ssl.c:90:5: error: incomplete definition of type 'struct dh_st'
  dh->p = BN_bin2bn(dh1024_p, sizeof(dh1024_p), NULL);
  ~~^
/usr/local/opt/openssl@1.1/include/openssl/ossl_typ.h:104:16: note: forward declaration of 'struct dh_st'
typedef struct dh_st DH;
               ^
mini_ssl.c:91:5: error: incomplete definition of type 'struct dh_st'
  dh->g = BN_bin2bn(dh1024_g, sizeof(dh1024_g), NULL);
  ~~^
/usr/local/opt/openssl@1.1/include/openssl/ossl_typ.h:104:16: note: forward declaration of 'struct dh_st'
typedef struct dh_st DH;
               ^
mini_ssl.c:93:10: error: incomplete definition of type 'struct dh_st'
  if ((dh->p == NULL) || (dh->g == NULL)) {
       ~~^
/usr/local/opt/openssl@1.1/include/openssl/ossl_typ.h:104:16: note: forward declaration of 'struct dh_st'
typedef struct dh_st DH;
               ^
mini_ssl.c:93:29: error: incomplete definition of type 'struct dh_st'
  if ((dh->p == NULL) || (dh->g == NULL)) {
                          ~~^
/usr/local/opt/openssl@1.1/include/openssl/ossl_typ.h:104:16: note: forward declaration of 'struct dh_st'
typedef struct dh_st DH;
               ^
mini_ssl.c:197:27: warning: 'DTLSv1_method' is deprecated [-Wdeprecated-declarations]
  conn->ctx = SSL_CTX_new(DTLSv1_method());
                          ^
/usr/local/opt/openssl@1.1/include/openssl/ssl.h:1645:1: note: 'DTLSv1_method' has been explicitly marked deprecated here
DEPRECATEDIN_1_1_0(__owur const SSL_METHOD *DTLSv1_method(void)) /* DTLSv1.0 */
^
/usr/local/opt/openssl@1.1/include/openssl/opensslconf.h:127:34: note: expanded from macro 'DEPRECATEDIN_1_1_0'
# define DEPRECATEDIN_1_1_0(f)   DECLARE_DEPRECATED(f)
                                 ^
/usr/local/opt/openssl@1.1/include/openssl/opensslconf.h:102:53: note: expanded from macro 'DECLARE_DEPRECATED'
# define DECLARE_DEPRECATED(f)    f __attribute__ ((deprecated));
                                                    ^
mini_ssl.c:233:20: warning: implicit conversion loses integer precision: 'long' to 'int' [-Wshorten-64-to-32]
  int verify_err = SSL_get_verify_result(ssl);
      ~~~~~~~~~~   ^~~~~~~~~~~~~~~~~~~~~~~~~~
mini_ssl.c:246:13: warning: implicit conversion loses integer precision: 'unsigned long' to 'int' [-Wshorten-64-to-32]
      err = ERR_get_error();
          ~ ^~~~~~~~~~~~~~~
mini_ssl.c:333:8: warning: unused variable 'buf' [-Wunused-variable]
  char buf[512];
       ^
mini_ssl.c:332:11: warning: unused variable 'err' [-Wunused-variable]
  int ok, err;
          ^
mini_ssl.c:349:11: warning: unused variable 'err' [-Wunused-variable]
  int ok, err;
          ^
mini_ssl.c:350:8: warning: unused variable 'buf' [-Wunused-variable]
  char buf[512];
       ^
mini_ssl.c:349:7: warning: unused variable 'ok' [-Wunused-variable]
  int ok, err;
      ^
8 warnings and 4 errors generated.
make: *** [mini_ssl.o] Error 1

make failed, exit code 2
```
I will also include this for the logged results. I apolgize if this is a dumb question but I do apperciate the  help!

**Comment by jashkothari** [comment]
@CodefulDom 

The references to db will in database.yml file found in config folder.

Do you have any migrations present?

Because I don't see a migrate folder in the db folder.

Please try creating a migration with

**rails g model User name:string age:integer**

and then doing **rails db:migrate**

**Comment by CodefulDom** [comment]
@jashkothari 

That created a migration!

**Comment by jashkothari** [comment]
@CodefulDom  

Since you don't have any migrations on newly created app.

**Comment by jashkothari** [comment]
@CodefulDom  

Since you don't have any migrations on newly created app.

**Comment by CodefulDom** [comment]
I just rubber duck-ed all over github.......

Thanks for your help @jashkothari 

![istock_000019367701_medium](https://user-images.githubusercontent.com/28935096/42261351-9621977e-7f2d-11e8-9403-1913f5f42218.jpg)

**Comment by jashkothari** [comment]
@CodefulDom 

No issues!!

Been there done that!

Since this is resolved lets close the issue

**Comment by CodefulDom** [comment]
Please close! Thanks!!

**Comment by CodefulDom** [comment]
Please close! Thanks!!
