### ISSUE TITLE
Validating numericality <= with interpolated message prevents validation of non numbers

### ISSUE THREAD

**Issue by rachel-carvalho** [rails/rails#33293]
### Steps to reproduce
Executable test case: https://gist.github.com/rachel-carvalho/cb3f321df8453d51bf1fb259848579af

Model:
```ruby
class Number < ActiveRecord::Base
  validates :value, numericality: { less_than_or_equal_to: 10, message: 'gimme less than or eq %{count}' }
end
```
Tests:
```ruby
  # passes as expected
  def test_above
    high_number = Number.new value: 20
    assert high_number.invalid?
    assert_equal ['gimme less than or eq 10'], high_number.errors[:value]
  end

  # fails
  def test_non_number
    non_number = Number.new value: 'd'
    # this raises `I18n::MissingInterpolationArgument: missing interpolation argument :count`
    # but the expected behavior is that it's invalid and the error message be :not_a_number
    assert non_number.invalid?
    assert_equal ['is not a number'], non_number.errors[:value]
  end
```

### Expected behavior
`#invalid?` should return true and the error message should be `:not_a_number`.

There should be a way to set a custom message with ` %{count}` interpolation while keeping the number validation features.

### Actual behavior
`I18n::MissingInterpolationArgument: missing interpolation argument :count` is raised when the field is validated with a non number value.

### System configuration
**Rails version**: 5.2.0

**Ruby version**: 2.5.0 `ruby 2.5.0p0 (2017-12-25 revision 61468) [x86_64-darwin17]`

### Notes

Upon investigating this issue, I realized that this might be a problem with how the `NumericalityValidator` decides which message to use. It will perform the type check validations (`#is_number?` and `#is_integer?`) and ignore other validations. However, when it adds the error to the resource it passes the options which contain a `:message` key, which always overwrites the one passed by the validator (`:not_a_number` or `:not_an_integer`).

This makes me realize that anytime we have multiple numericality validations (`:greater_than_or_equal_to` and `:less_than` for instance), we can never specify custom messages for each type of error. So maybe this is really a design issue rather than a bug?

(Sorry if I shouldn't have added these notes here, but I think they're important for the bug report. I can edit them out into a comment if needed, please let me know.)

**Comment by rafaelfranca** [comment]
Thank you for the issue and nice investigation.

Yes, that is more like a design issue. The message option is for the entire validator no matter witch option you use. The only way to you to customize the message depending on the options is by using the i18n feature.

**Comment by rachel-carvalho** [comment]
Thanks for the quick feedback! 

My codebase is using an i18n key instead of an inline string, but the raised error is the same. In our case, we have different validation rules and messages depending on another field (basically max 800 km but 500 mi). So it's not enough to just override `activerecord.errors.models.my_model.attributes.my_attribute.less_than_or_equal_to` because we need a different message for `km` or `mi`.

The only workaround I see for this is specifying a proc that will perform the type check myself and decide on which message to return. Do you think there would be a way to do it without re-implementing the validation?

https://gist.github.com/rachel-carvalho/b29e3bf13263db59fc19047a4c17d250

```ruby
class Number < ActiveRecord::Base
  validates :value, numericality: { less_than_or_equal_to: 10, message: ->(record, options) { record.send(:custom_message, options) } }

  private

  def custom_message(_options)
    numeric = Kernel.Float(value_before_type_cast).present? rescue false

    return I18n.t(:not_a_number, scope: 'errors.messages') unless numeric
    'gimme less than or eq %{count}'
  end
end
```

And then this passes:
```ruby

  def test_non_number
    non_number = Number.new value: 'd'
    assert non_number.invalid?
    assert_equal ['is not a number'], non_number.errors[:value]
  end
```

**Comment by rafaelfranca** [comment]
we could change rails to always pass the count, even if it is `nil` in the case of a not_integer or not_number validation. But the passing the `message` option the same message will be used for all the numerical validations.
