### ISSUE TITLE
ActiveStorage issue to set `record_type` on `active_storage_attachments`

### ISSUE THREAD

**Issue by SunDi3yansyah** [rails/rails#33300]
I have a problem for ActiveStorage

the case is I have a model named `Setting::Profile` and name of `Admin` table and attachment `:avatar`
for uploading process succeed, but when to get the picture can not be found because at table `active_storage_attachments` in attribute `record_type` stored with name `Setting::Profile`, supposed with name `Admin`

How to add a line to prepare for the `record_type` attribute?
Thanks

**Comment by georgeclaghorn** [comment]
Can you share a minimal sample app that demonstrates the issue?

**Comment by SunDi3yansyah** [comment]
Hi @georgeclaghorn
This my demo: https://github.com/SunDi3yansyah-forks/AppActiveStorage

![screenshot from 2018-07-11 01-24-48](https://user-images.githubusercontent.com/3952281/42530104-808f4212-84aa-11e8-92f9-7c47c6691861.png)

**Comment by SunDi3yansyah** [comment]
Solved https://stackoverflow.com/questions/51200105
