### ISSUE TITLE
Derived secret_key_base in development and testing environment

### ISSUE THREAD

**Issue by mengqing** [rails/rails#33306]
Currently the `secret_key_base` is derived as a MD5 hash from the application name if `config/secrets.yml` is not present. However this is causing an issue for us where we want to share the same session cookie across different applications that happens to have different application names.

We can continue to use the `secret_key_base` in `config/secrets.yml` for session sharing on development / testing, but isn't sure if this is the right way to do

**Comment by prathamesh-sonpatki** [comment]
Please use stackoverflow or other medium for posting questions where a wider community can help you, we reserve the issue tracker for bug reports only, thanks.

**Comment by mengqing** [comment]
Thanks for the feedback but I do consider this as a bug as it was previously working for us but as the result of introducing #30067 this is no longer possible after moving from `secrets` to `credentials`

Currently on the master branch, the documentation for `Rails::Application#secrets` still mentions about storing `secret_key_base` in `secrets.yml` file, yet when you generate a new 5.2 rails app, the `secret_key_base` is stored in `credentials.yml` (for any environments other than development / test). I feel like this is confusing and semi finished.

At the moment my workaround for this is to keep a version of `secrets.yml` just for storing `secret_key_base` for development / test environment, and for any other environments, store in `credentials.yml`. But this is definitely not the proper way to solve this issue in my opinion.

**Comment by kaspth** [comment]
Looks like `secrets` will attempt to read `config.secret_key_base` as well, so you could do:

```ruby
# config/initializers/secret_key_base.rb
if Rails.env.test? || Rails.env.development?
  Rails.application.config.secret_key_base = …
end
```

We could even add in `config.secret_key_base` after the secrets lookup here:

https://github.com/rails/rails/blob/76f22e19d6793c24a570f413e4f6b7b9b5416bf7/railties/lib/rails/application.rb#L430

Please do send a PR to help make this clearer!
