### ISSUE TITLE
Unable to edit scaffold generator 

### ISSUE THREAD

**Issue by nwoow** [rails/rails#33311]
I am trying to edit controller and routes whenever I create a scaffold Ia m trying to edit my controller and add two actions like test or test 1.  I can change my erb files I can overwrite my new.html.erb by adding a folder:

` /lib/template/erb/scaffold/new.html.erb`

It is working I can also edit my model files for that I have created this file under:

`lib/templates/active_record/model/model.rb`

So I have created a file called controller.rb inside:

`lib/templates/scaffold_controller/controller.rb`

And I am pasting this code from [scaffold controller template](https://github.com/rails/rails/blob/master/railties/lib/rails/generators/rails/scaffold_controller/templates/controller.rb.tt)

To edit resource route I have added file resource_route_generator.rb under this folder:

`lib/templates/resource_route/resource_route_generator.rb`

My question is how can I edit controller and two more actions and I need to add those routes in my routes file like this:

`  resources :production_productivity9s do
    collection { post :import }
    collection { get :dropdown }
    collection { get :test }
  end`

I like rails for generators but I am unable to find documents where I can see thee kind of modifications.

**Comment by rafaelfranca** [comment]
Please use the mailing list or StackOverflow for questions/help, where a wider community will be able to help you. We reserve the issues tracker for issues only.
