### ISSUE TITLE
ActiveStorage change default queue

### ISSUE THREAD

**Issue by arefaslani** [rails/rails#33315]
I switched from Carrierwave to ActiveStorage recently. Yesterday when I used `purge_later` method, I saw nothing happend. Then I checked the Sidekiq queue and I saw one Enqueued job. My sidekiq configuration doesn't watch the `default` queue and that was the problem. I checked the ActiveStorage source code and I find [this line](https://github.com/rails/rails/blob/master/activestorage/app/jobs/active_storage/base_job.rb#L4) and [this line](https://github.com/rails/rails/blob/e8682c5bf051517b0b265e446aa1a7eccfd47bf7/activestorage/lib/active_storage/engine.rb#L49). I can change the default queue this way:
```ruby
# application.rb
...
config.active_storage.queue = :active_storage
...
```
I think It's a good idea to document this. Anyway, thanks for the great framework :)

**Comment by kaspth** [comment]
It's mentioned here: http://guides.rubyonrails.org/configuring.html#configuring-active-storage

Thanks for double-checking! 😊

**Comment by MSCAU** [comment]
> It's mentioned here: http://guides.rubyonrails.org/configuring.html#configuring-active-storage
> 
> Thanks for double-checking! 😊

This is no longer correct. The URL you provided @kaspth doesn't list that syntax (any more).

**Comment by georgeclaghorn** [comment]
It explains how to change the queues Active Storage jobs use on the latest version of Rails. Consult older versions of the guides for older versions of Rails (e.g. [here](https://guides.rubyonrails.org/v5.2/configuring.html#configuring-active-storage) for 5.2).

**Comment by MSCAU** [comment]
Thanks. That older doc reference was what I needed.
