### ISSUE TITLE
Any way to make *_ids= methods not save records into DB immediately?

### ISSUE THREAD

**Issue by shiranakatta** [rails/rails#33310]
### Steps to reproduce

```
class User < ApplicationRecord
  has_many :user_tasks
  has_many :tasks, through: :user_tasks

  validates :name, presence: true
end

class UserTask < ApplicationRecord
  belongs_to :user
  belongs_to :task
end

class Task < ApplicationRecord
  has_many :user_tasks
  has_many :users, through: :user_tasks
end
```

Suppose that there are 3 tasks assigned to the first user

```
user = User.first
user.task_ids # => [1, 2, 3]
```

Now I have the following code

```
user.assign_attributes name: '', task_ids: []
user.save
```

### Expected behavior
`user.save` returns `false` and user's name and tasks are not changed

### Actual behavior
`user.save` returns `false`, user's name is not changed but user's tasks are all deleted.

This happens because when `user.task_ids=` is called, it deletes `user.user_tasks` and commits  immediately. Is there any way to prevent this rather than wrapping the code above in a transaction and manually raising `ActiveRecord::Rollback` when `use.save` fails?

### System configuration
**Rails version**: 5.2

**Ruby version**: 2.5

**Comment by kaspth** [comment]
Please use StackOverflow for questions. We reserve the issues tracker for bugs only. Thanks!

**Comment by shiranakatta** [comment]
I updated steps to reproduce. This should be considered as a bug. Why are `_ids=` methods treated differently compared to other `attribute=` methods?

```
# frozen_string_literal: true

begin
  require "bundler/inline"
rescue LoadError => e
  $stderr.puts "Bundler version 1.10 or later is required. Please update your Bundler"
  raise e
end

gemfile(true) do
  source "https://rubygems.org"

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  # Activate the gem you are reporting the issue against.
  gem "activerecord", "5.2.0"
  gem "sqlite3"
end

require "active_record"
require "minitest/autorun"
require "logger"

# Ensure backward compatibility with Minitest 4
Minitest::Test = MiniTest::Unit::TestCase unless defined?(Minitest::Test)

# This connection will do for database-independent bug reports.
ActiveRecord::Base.establish_connection(adapter: "sqlite3", database: ":memory:")
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :users, force: true do |t|
    t.string :name
  end

  create_table :tasks, force: true do |t|
  end

  create_table :user_tasks, force: true do |t|
    t.references :user
    t.references :task
  end
end

class User < ActiveRecord::Base
  has_many :user_tasks
  has_many :tasks, through: :user_tasks

  validates :name, presence: true
end

class Task < ActiveRecord::Base
  has_many :user_tasks
  has_many :users, through: :user_tasks
end

class UserTask < ActiveRecord::Base
  belongs_to :user
  belongs_to :task
end

class BugTest < Minitest::Test
  def test_association_stuff
    user = User.create name: "user"
    3.times do
      task = Task.create
      user.user_tasks.create task: task
    end

    assert_equal 3, user.tasks.count

    user.assign_attributes name: "", task_ids: []
    assert_equal false, user.save

    user.reload

    assert_equal "user", user.name
    assert_equal 3, user.tasks.count
  end
end
```

Test result
```
  1) Failure:
BugTest#test_association_stuff [test.rb:78]:
Expected: 3
  Actual: 0

1 runs, 4 assertions, 1 failures, 0 errors, 0 skips
```

**Comment by kaspth** [comment]
> This should be considered as a bug

Not if it's the documented behavior. 😊

`user.task_ids = []` will replace the collection via `user.tasks = []` which has the caveats described in the "Collections" section here: http://api.rubyonrails.org/classes/ActiveRecord/Associations/ClassMethods.html#module-ActiveRecord::Associations::ClassMethods-label-Unsaved+objects+and+associations

You could try `autosave: false`.

**Comment by shiranakatta** [comment]
Thanks for your suggestion. I tried adding `autosave: false` to each of the following but it didn't work.

- Class User
```
has_many :user_tasks, autosave: false
```

- Class User
```
has_many :tasks, through: :user_tasks, autosave: false
```

- Class Task
```
has_many :user_tasks, autosave: false
```

I think the reason `autosave: false` doesn't help is that `user.task_ids = []` saves records of the join model `UserTask`, not `Task`.

**Comment by ChrisHampel** [comment]
What you want is a database transaction, so you can roll it back if you don't want the changes

**Comment by ryanb** [comment]
While I understand this is documented behavior, I find it causes a lot of unexpected issues. If you set `task_ids` through a form it will save the association even if validation fails. If authorization is done after assigning attributes it allows for an unexpected security breach where anyone can set the association.

The `autosave` config option is for different behavior: it just prevents associations from saving along with the parent (which I think is good behavior). Wrapping the attribute assignments in a transaction gets messy with validations.

I believe all attribute assignments should only be committed when saving the record, including association assignments. I wish the Rails team would take another look at this issue and consider adding lazy id setters.

**Comment by dmitry** [comment]
Here's a clean solution to control association assignment and prevent unexpected saves:

```ruby
class User < ApplicationRecord
 has_many :user_tasks, autosave: true, dependent: :nullify, index_errors: true
 has_many :tasks, through: :user_tasks

 def task_ids=(ids)
   tasks.delete(tasks.where.not(id: ids))
   new_tasks = Task.where(id: ids - task_ids)
   tasks.concat(new_tasks)
 end
end

- Prevents premature database saves
- Maintains validation integrity
- Supports detailed error tracking with index_errors: true
- Full control over association modifications
- Associations only change when parent record is saved

This was a very long-standing problem for me to find a solution. The approach works for all possible association types:
- `has_many`
- `has_many through`
- Even polymorphic associations

I'm planning to create a PR that will provide a new, safe way to handle `collection_ids=` assignment across applications. The key benefits would be:
- Proper validation
- Associations saved only when explicitly requested
- Consistent behavior across different association types

This solution provides a universal method to handle association assignments safely and predictably, addressing many of the current pain points in Rails association management.

**Comment by stv8** [comment]
@dmitry that sounds great, would you please link your PR here when you publish it? 

I too am having issue with this behavior, specifically difficulties around tracking my the changes to the IDs due to the immediate query performed. 

I have posted more details here

https://discuss.rubyonrails.org/t/change-tracking-on-association-ids-when-they-are-set-via-the-collection-singular-ids-ids-method/88603

Looking forward to your PR!
