### ISSUE TITLE
activestorage deadlock

### ISSUE THREAD

**Issue by nppoly** [rails/rails#33327]
[https://github.com/chenkovsky/test_site.git](https://github.com/chenkovsky/test_site.git)
```ruby
# it's ok
rails db:drop db:create db:migrate 
rails db:seed
```

```ruby
# bug appears. it seems that it's deadlock.
rails db:drop db:create db:migrate db:seed
```

**Comment by twitnithegirl** [comment]
Hi @nppoly It's not quite clear what bug it is that you are reporting. I see that you are having some sort of deadlock related to database tasks but it's unclear what circumstances you're operating under . Can you please report the bug in [this format](http://edgeguides.rubyonrails.org/contributing_to_ruby_on_rails.html#create-an-executable-test-case) to make it more clear what is happening and easier for others to reproduce your issue.

**Comment by nppoly** [comment]
the repo I give is the environment that I created for reproducing bug. In that repo, I installed activestorage, created one table, and attached image for that table. when I execute 'rails db:drop db:create db:migrate db:seed', the program cannot exit correctly, I use byebug to debug it, I find that it seems that it's trying to wait a lock.

**Comment by RigoTheDev** [comment]
I ran `rails db:drop db:create db:migrate db:seed` on a sample Rails 5.2.0 app without ActiveStorage & it ran/exited successfully. It seems like it has to do with the file I/O operations.

**Comment by RigoTheDev** [comment]
I can confirm it's the `pic.attach` that's causing the issue. Just added `has_one_attached :pic` to my model & it's now hanging the seeding process.

Adding
```ruby
    config.active_job.queue_adapter = :inline
```
to `config/environments/development.rb` has now fixed the issue.

**Comment by RigoTheDev** [comment]
Created a [new issue](https://github.com/rails/rails/issues/33500) for this.

**Comment by rafaelfranca** [comment]
Duplicate of #33500
