### ISSUE TITLE
PostgreSQL integer datatype fails on validate numericality with lass_than_or_equal_to option

### ISSUE THREAD

**Issue by MagedMilad** [rails/rails#33323]
### Steps to reproduce
Create a PostgreSQL table ex: `post` with `integer` column and add a numerical validation with `less_than_or_equal_to` option, then you can create a new record even with a value larger than specified 
in `less_than_or_equal_to` option

[gist script](https://gist.github.com/MagedMilad/beed7e19ebbf67ea849c31f7d110eb9d)

### Expected behavior
`less_than_or_equal_to` - option should specify the value must be less than or equal to the supplied value. with error message

### Actual behavior
`less_than_or_equal_to` - validation pass even if the supplied value larger than it should be

### System configuration
**Rails version**:  5.2.0
**Ruby version**: 2.4.1p111
**PostgreSQL version**: 9.5.12

**Comment by sikachu** [comment]
You typed `lass_than_or_equal_to` instead of `less_than_or_equal_to` in your example code and in issue title. Please try changing to `less_than_or_equal_to` and see if the problem still exists so we can investigate further.
