### ISSUE TITLE
ActiveSupport notifications won't set status to 500 with process_action.action_controller

### ISSUE THREAD

**Issue by kaspergrubbe** [rails/rails#33335]
### Steps to reproduce

```ruby
# frozen_string_literal: true

begin
  require "bundler/inline"
rescue LoadError => e
  $stderr.puts "Bundler version 1.10 or later is required. Please update your Bundler"
  raise e
end

gemfile(true) do
  source "https://rubygems.org"

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  gem "rails", github: "rails/rails"
end

require "action_controller/railtie"

class TestApp < Rails::Application
  config.root = __dir__
  secrets.secret_key_base = "secret_key_base"

  config.logger = Logger.new($stdout)
  Rails.logger  = config.logger

  routes.draw do
    get "/" => "test#index"
  end
end

class TestController < ActionController::Base
  include Rails.application.routes.url_helpers

  def index
    raise
  end
end

require "minitest/autorun"
require "rack/test"

class BugTest < Minitest::Test
  include Rack::Test::Methods

  def test_returns_success
    @status = nil
    ActiveSupport::Notifications.subscribe("process_action.action_controller") do |_name, _started, _finished, _id, payload|
      @status = payload[:status]
    end
    get "/"
    assert_equal 500, @status
  end

  private
    def app
      Rails.application
    end
end
```

### Expected behavior
I expected that the `payload[:status]` would be set to 500 if exceptions have happened.

### Actual behavior
The `process_action.action_controller`-hook gets executed, but the status value is nil.

### System configuration
**Rails version**: 5.0, 5.2.0 and 6.0.0.alpha

**Ruby version**: 2.4.1 and 2.5.0

**Comment by rafaelfranca** [comment]
It is because the status is not set by the controller, so the payload don't have the information. The status is set by a middleware and the payload have no access to the middleware.

**Comment by kaspergrubbe** [comment]
Hi Rafael,

It is interesting to know why, but I will still consider it a bug, or at least undocumented behaviour. 

It is very unexpected especially after reading the documentation covering active-support notifications that they won't mention that `status` won't be set if the action hits an exception.

This is where I would have expected to see this behaviour mentioned: http://guides.rubyonrails.org/active_support_instrumentation.html#process-action-action-controller

The only remotely related I have been able to find is from: http://api.rubyonrails.org/classes/ActiveSupport/Notifications.html

> If an exception happens during that particular instrumentation the payload will have a key :exception with an array of two elements as value: a string with the name of the exception class, and the exception message. The :exception_object key of the payload will have the exception itself as the value.

Which is also how I do 500 detection now:

```
payload_data[:tags][:http_status] = 500 if payload[:exception_object].present?
```

**Comment by rafaelfranca** [comment]
The status will not be set in the same way that the view runtime will not be set if the exception happens before the view finished to render. An exception inside a notification will always lead to an undefined state in that notification. This is why we provide the exception information in the payload.

**Comment by rafaelfranca** [comment]
To be clear this is not specific for any notification, this is why it is documented in the Notification class. If it is not mentioned in the guide and you think it should feel free to add.

**Comment by kyrylo** [comment]
I am someone who got confused by this behaviour. I feel like it won't hurt mentioning that people should not expect status 500 in these notifications.
