### ISSUE TITLE
HashWithIndifferentAccess as keyword arg

### ISSUE THREAD

**Issue by phillc** [rails/rails#33334]
### Steps to reproduce

This works in rails 5.0, but not 5.1

`def b(c: ); puts c; end; b({"c" => 1}.with_indifferent_access.transform_keys(&:to_sym))`

### Expected behavior
Should be able to use the hash as a keyword arg

### Actual behavior
ArgumentError: wrong number of arguments (given 1, expected 0; required keyword: c)

`def b(c: ); puts c; end; b({"c" => 1}.with_indifferent_access.symbolize_keys)` this does work, so maybe this isn't worth fixing, but it is a regression.

**Comment by rafaelfranca** [comment]
This is by design. `HashWithIndiffereceAccess` only store keys as strings. If you want to change the keys to be symbol you have to transform it in a regular hash before transforming the keys. This is what `symbolize_keys` does.
