### ISSUE TITLE
User is logged out between Rails 5.1.6 and 5.2; possible cookie compatibility issue.

### ISSUE THREAD

**Issue by edzhelyov** [rails/rails#33343]
### Steps to reproduce

I ran our codebase with the current Rails 5.1.6 version and logged in (using ~~devise~~ and cookie based session). After that I switched to the Rails 5.2 branch where `    config.action_dispatch.use_authenticated_cookie_encryption = false
` and refreshed the browser. 

### Expected behavior
I expect the user to be still signed in.

### Actual behavior
User is logged out and redirected to the login page.

### Possible issues
Seems to me that the session information stored in the cookie in 5.1 is not persisted when upgrading to Rails 5.2. I couldn't figure out what causes that, but this means that when we upgrade to 5.2 on production all users will be logged out which is something we want to avoid.

### System configuration
**Rails version**: 5.2.0

**Ruby version**: 2.3

**Comment by prathamesh-sonpatki** [comment]
Can you upload a sample application on Github that reproduces the issue? Thanks.

**Comment by edzhelyov** [comment]
We are not using Devise, my bad. I will have difficulties to come up with a sample application, the codebase is private and quite huge. But I will see what I can do.
Can you confirm that in clean Rails 5.1 upgraded to Rails 5.2 we expect the session to be kept between server restarts?

**Comment by edzhelyov** [comment]
What I can say at the moment is that with 5.1 the cookie generated can be decrypted by using this code:
```
def decrypt_session_cookie(cookie)
  cookie = CGI.unescape(cookie)
  config = Rails.application.config
 
  encrypted_cookie_salt = config.action_dispatch.encrypted_cookie_salt               # "encrypted cookie" by default
  encrypted_signed_cookie_salt = config.action_dispatch.encrypted_signed_cookie_salt # "signed encrypted cookie" by default
 
  key_generator = ActiveSupport::KeyGenerator.new(config.secret_key_base, iterations: 1000)
  secret = key_generator.generate_key(encrypted_cookie_salt)
  sign_secret = key_generator.generate_key(encrypted_signed_cookie_salt)
 
  encryptor = ActiveSupport::MessageEncryptor.new(secret, sign_secret)
  encryptor.decrypt_and_verify(cookie)
end
```
But when I restart the server with 5.2 the cookie is different, shorter and can't be decrypted, raises `ActiveSupport::MessageVerifier::InvalidSignature: ActiveSupport::MessageVerifier::InvalidSignature`

**Comment by kaspth** [comment]
Is `use_authenticated_cookie_encryption` enabled on your 5.2 branch? If it is: the option is incompatible with 5.1, so it should only be enabled once you've verified your 5.2 rollout is stable 😊

**Comment by edzhelyov** [comment]
`config.action_dispatch.use_authenticated_cookie_encryption = false` is explicitly set on false in `config/application.rb`, it's false by default the last time checked in the action_dispatch code. That's the reason I'm filing the issue, it's quite strange given it's false.

**Comment by edzhelyov** [comment]
I'm digging into that deeper and what I've found is that `ActiveSupport::MessageEncryptor` in the `cookies` helper have different `@secret` and `@sign_secret` values on 5.1 and 5.2. Maybe that's the root cause. Any ideas where these are set?

Rails 5.2
```
#<ActionDispatch::Cookies::CookieJar:0x007feeb63b8538
 @committed=false,
 @cookies=
  {"navigator_data"=>"{\"pixel_ratio\":1,\"vendor\":\"Google Inc.\",\"platform\":\"MacIntel\"}",
   "_session"=>
    "zJOYlFmSFhDVGQ1NlM4dG9IZloyL1FqTVl6QVRZWUNJQXJxdCtvN2R1eHcxdGlUV3M1OXlRVk93NjFlREM0KzlBMFNNOEV5U0dCRnFXRFhYU2pLcjUxRFdTVlovNk53VjZnSlFGTGoyQjNadmFVbjVoRDdHK0RONndydDIwYmtKOGNyYjh1MnRVQTlQWTNzakk2UGMyMk5oVWZqSXN0ckwxRnNSTjEvSE9mVkl1Mm5DWVEvVHVIaG9yV3NYenRRNzJMdmJxRCsrdjVDeEpmci9IS1lJYi9ydHVONUtpaXVoL01naW5Hd2hXQ3lmZ2VnSCtjbUxQZmJjM090Z0RVT2VVbjA4dlBjalZmOVlvendMMnJ0MjJiUmpzdXRSN2Z6VmFPU1VGZGJYbWlSOXR2dUJpakloMkkwajFGeUVhdjdieDNsMkJmVmJQWC9ZQmI0Nkx5SUt4T2ZvWlNvVFRvZUJhN2JNOG1RcjNVamU3cVhWU1Y3ZU9ua3ZpMTFYMDgwWGdQNnZFeXQ1S3hJUEhGRVdaMEFCWDYvbnEzZ1pCbnZQVzd0djFDdHE2bUF5S1Vrbms9LS0wVlJQTG5KSkFuK01OM2pMajEwQ2t3PT0=--cf723af0d32812490ccaeaed17bc2d7113a0bd5a"},
 @delete_cookies={},
 @encrypted=
  #<ActionDispatch::Cookies::EncryptedKeyRotatingCookieJar:0x007feeb63b8380
   @encryptor=
    #<ActiveSupport::MessageEncryptor:0x007feeb63b8150
     @aead_mode=false,
     @cipher="aes-256-cbc",
     @digest="SHA1",
     @options={:cipher=>"aes-256-cbc", :serializer=>ActiveSupport::MessageEncryptor::NullSerializer},
     @rotations=[],
     @secret="=\v\xBF\x14\xDE\xEB\x90\xDB,3\xF7A\xE4\xD0\xF8(C5\xE6\x9F\x123\xE3\xC2+",
     @serializer=ActiveSupport::MessageEncryptor::NullSerializer,
     @sign_secret="\xF4\x86\xDC8\xB9\x97\xF5\x12\xC6\xCB\x94\xB0\xC9g\x8A\xE1\xC5\xF6g\x8C 4U\a\xC4\x13\xBDk\xCFTy\f\xEE\es\x7F\xFF\x90\xB5o'\x95:F\xA0e\r\xA5",
     @verifier=
      #<ActiveSupport::MessageVerifier:0x007feeb2da3ec0
       @digest="SHA1",
       @options={:digest=>"SHA1", :serializer=>ActiveSupport::MessageEncryptor::NullSerializer},
       @rotations=[],
       @secret="\xF4\x86\xDC8\xB9\x97\xF5\x12\xC6\xCB\x94\xB0\xC9g\x8A\xE1\xC5\xF6g\x8C 4U\a\xC4\x13\xBDk\xCFTy\f\xEE\es\x7F\xFF\x90\xB5o'\x95:F\xA0e\r\xA5",
       @serializer=ActiveSupport::MessageEncryptor::NullSerializer>>,
   @parent_jar=#<ActionDispatch::Cookies::CookieJar:0x007feeb63b8538 ...>>,
```
Rails 5.1
```
#<ActionDispatch::Cookies::CookieJar:0x007fd163e6bb80
 @committed=false,
 @cookies=
  {"navigator_data"=>"{\"pixel_ratio\":1,\"vendor\":\"Google Inc.\",\"platform\":\"MacIntel\"}",
   "_session"=>
    "zJOYlFmSFhDVGQ1NlM4dG9IZloyL1FqTVl6QVRZWUNJQXJxdCtvN2R1eHcxdGlUV3M1OXlRVk93NjFlREM0KzlBMFNNOEV5U0dCRnFXRFhYU2pLcjUxRFdTVlovNk53VjZnSlFGTGoyQjNadmFVbjVoRDdHK0RONndydDIwYmtKOGNyYjh1MnRVQTlQWTNzakk2UGMyMk5oVWZqSXN0ckwxRnNSTjEvSE9mVkl1Mm5DWVEvVHVIaG9yV3NYenRRNzJMdmJxRCsrdjVDeEpmci9IS1lJYi9ydHVONUtpaXVoL01naW5Hd2hXQ3lmZ2VnSCtjbUxQZmJjM090Z0RVT2VVbjA4dlBjalZmOVlvendMMnJ0MjJiUmpzdXRSN2Z6VmFPU1VGZGJYbWlSOXR2dUJpakloMkkwajFGeUVhdjdieDNsMkJmVmJQWC9ZQmI0Nkx5SUt4T2ZvWlNvVFRvZUJhN2JNOG1RcjNVamU3cVhWU1Y3ZU9ua3ZpMTFYMDgwWGdQNnZFeXQ1S3hJUEhGRVdaMEFCWDYvbnEzZ1pCbnZQVzd0djFDdHE2bUF5S1Vrbms9LS0wVlJQTG5KSkFuK01OM2pMajEwQ2t3PT0=--cf723af0d32812490ccaeaed17bc2d7113a0bd5a"},
 @delete_cookies={},
 @encrypted=
  #<ActionDispatch::Cookies::EncryptedCookieJar:0x007fd163e6a708
   @encryptor=
    #<ActiveSupport::MessageEncryptor:0x007fd163e696a0
     @aead_mode=false,
     @cipher="aes-256-cbc",
     @digest="SHA1",
     @secret="\x8B\xCA\xAZ+\xF5S\x96)\xCC\x03\xF5\x98uy+\xB9%\xD2\xE1B\xD73\xAB\xFD`\n\xAC*\x85c\x82\x14",
     @serializer=ActiveSupport::MessageEncryptor::NullSerializer,
     @sign_secret="\x11\x12}\xAC!A|\eU\xE65\xC3\xC6\b\x1A\xA2\xC6{=\xD1`\x97\xA1\xA3\xE6\x92g\xB67A\xD7\xC1\xA6\x91\xDFx7\xA0ann\xA1\x94\x12\x82\xA5\xC9\xFC\x93\x17'$q\xF5\xB0)\x82\x0F\xEB\xB5\xC2\xC4\xB7p",
     @verifier=
      #<ActiveSupport::MessageVerifier:0x007fd163e53d78
       @digest="SHA1",
       @secret="\x11\x12}\xAC!A|\eU\xE65\xC3\xC6\b\x1A\xA2\xC6{=\xD1`\x97\xA1\xA3\xE6\x92g\xB67A\xD7\xC1\xA6\x91\xDFx7\xA0ann\xA1\x94\x12\x82\xA5\xC9\xFC\x93\x17'$q\xF5\xB0)\x82\x0F\xEB\xB5\xC2\xC4\xB7p",
       @serializer=ActiveSupport::MessageEncryptor::NullSerializer>>,
   @parent_jar=#<ActionDispatch::Cookies::CookieJar:0x007fd163e6bb80 ...>>,
```
_NOTE: Actual secrets and session changed for security reasons_

**Comment by edzhelyov** [comment]
I can confirm that the difference in the `@secret` and `@sign_secret` is causing the issue.

**Comment by edzhelyov** [comment]
The problem is because Rails 5.2 uses auto-generated `secret_key_base` introduced in this [PR](https://github.com/rails/rails/pull/30067) in development which is different from the one set in the config and used by the 5.1.6 version.
The issue is only present when I do the migration in dev environment and won't happen in production. Closing this one.

**Comment by taf2** [comment]
Is there anyway to change the behavior in development to test a migration locally to before testing in production?

**Comment by badosu** [comment]
After a painstaking debugging session through Rails internals trying to figure out why Rails was encrypting sessions without a `secret_key_base` I found that offending PR and worked around using this monkey patch:

```ruby
module Rails
  class Application < Engine
    def secret_key_base
      validate_secret_key_base \
        ENV["SECRET_KEY_BASE"] || credentials.secret_key_base || secrets.secret_key_base
    end
  end
end
```

You should still test it on a `staging` environment to be sure.
