### ISSUE TITLE
ruby: No such file or directory -- bin/rails (LoadError)

### ISSUE THREAD

**Issue by rk134** [rails/rails#33354]
Hello, I have been hit with this error several times only today. Yesterday (11/07/18) it was working fine. But today (12/07/18) it is hitting me with this error when I attempt to load Puma:
C:\Sites>ruby bin/rails server
ruby: No such file or directory -- bin/rails (LoadError)

I'm using CMD with Rails and Ruby.
Please help, as I need to finish my course!
Thanks,
rk134

**Comment by rafaelfranca** [comment]
Please use the mailing list or StackOverflow for questions/help, where a wider community will be able to help you. We reserve the issues tracker for issues only.
