### ISSUE TITLE
is `valid_request_origin?` too strict?

### ISSUE THREAD

**Issue by antpaw** [rails/rails#33355]
### Steps to reproduce

- Host a rails app behind a CDN
- setup `config.action_controller.default_url_options = { host: ENV["CDN_URL"], protocol: 'https://' }`
- Submit a form in (eg safari, or other browsers that will send Location header regardless beeing on the same domain)
- `request.origin == request.base_url` will fail because the cdn's url is different to the app server's url

### Expected behavior
forgery_protection should permit this

### Actual behavior
`valid_request_origin?` will return false and the forgery_protection will falsely fail

### System configuration
**Rails version**: 2.5

**Ruby version**: 5.2

Should [this check](https://github.com/rails/rails/blob/v5.2.0/actionpack/lib/action_controller/metal/request_forgery_protection.rb#L434) permit `default_url_options[:host]` Especial because origin check is now turned on by default and this error only happens on cdns and only on some browsers that send Location headers all the time. This could save a lot of headaches.

**Comment by matthewd** [comment]
Configure `X-Forwarded-Host` so that the application knows true domain that received the request (the CDN's address).
