### ISSUE TITLE
Attachments should be detached when assigned a blank value

### ISSUE THREAD

**Issue by kylefox** [rails/rails#33362]
ActiveStorage allows attachments to be attached by assigning a string representing a blob's `signed_id`. This works _brilliantly_ because it enables the same `params` conventions used when assigning other attributes through forms → controllers → models:

```ruby
params = { user: { image: 'eyJfcmF--e31aef3' } }
```

However, it's surprising that setting the attachment to an empty string does _not_ detach the attachment:

```ruby
params = { user: { image: '' } } # => InvalidSignature
```

It feels more Railsy to treat the empty string as a special case that detaches the attachment.

This would allow attachments to be removed in a way that mirrors how they are added (i.e. posting hidden field values) instead of having to call `@user.image.detach` in a controller.

For example, this would handle both attaching and detaching `@user.image`:

```ruby
@user.update_attributes(params.require(:user).permit(:name, :email, :image))
```

### Steps to reproduce

1. Assign an attachable to the attachment: `@user.image = blob.signed_id`
1. Assign an empty string to the attachment: `@user.image = ''`

### Expected behavior

* The attachment is detached, i.e. `@user.image.detach`.

### Actual behavior

* `ActiveSupport::MessageVerifier::InvalidSignature` is raised.

### System configuration

* **Rails version**: Rails 5.2.0
* **Ruby version**: ruby 2.5.1p57 (2018-03-29 revision 63029) [x86_64-darwin17]

**Comment by kaspth** [comment]
Thanks for the request! We don't keep these on the issue tracker, but on the Rails Core mailing list. If you're interested in trying a PR, here's the line: https://github.com/rails/rails/blob/05bef140519fe3410fd8d352f5ea84fd1a278063/activestorage/lib/active_storage/attached/model.rb#L41

It seems `has_many_attached` already supports being passed nil or an empty array and then clearing out all the attachments.

I can't guarantee we'll accept it even once we see the code, but please do investigate :)

**Comment by kylefox** [comment]
Thanks @kaspth! I submitted it here because it feels more like a bug than feature request  — especially if `has_many_attached` behaves this way. But I'll send it over to the mailing list. 👍

**Comment by kylefox** [comment]
Here's the mailing list link if anyone is interested in continuing the discussion:

* [Attachments should be detached when assigned a blank value
](https://groups.google.com/forum/#!topic/rubyonrails-core/xI5HPnxIAIE)
