### ISSUE TITLE
Consider an alternative to `Time.utc` for drastical performance improvement (Mac OSX)

### ISSUE THREAD

**Issue by Edouard-chin** [rails/rails#33376]
Disclaimer; This isn't a Rails issue but a bug in the MacOS implementation of `tzset`. I'm wondering if we could consider a workaround in Rails

Some benchmarking will give you a first overview of the issue and the slowness of using `Time.utc` **after forking the process**.

<details>
  <summary> Script used </summary>

  ```ruby
require 'benchmark'

def create_utc_time
    100_000.times { Time.utc(2018) }
end

p "Main Process: #{Benchmark.measure { create_utc_time } }"

pid = Process.fork do
    p "Fork Process: #{Benchmark.measure { create_utc_time }}"
end

Process.wait(pid)
  ```
</details>

```
"Main Process:   0.150000   0.000000   0.150000 (  0.147837)"
"Fork Process:  18.840000  10.810000  29.650000 ( 29.692344)"
```

_______________________

I started tracking down this issue after trying to understand why our fixtures were taking so much time to load (it takes around 45 seconds to load...).

My first conclusion led me to think that this was due to spring because the issue was consistently reproducible when the rails command was passed to the spring process. Adding `DISABLE_SPRING=1` was making things way faster (9 seconds versus 50).

Throwing a profiler when fixtures get loaded led me to `AR::Type::DateTime#serialize` that was taking almost all the CPU. This serialization happens in `value_for_database` when Rails try to [generate](https://github.com/rails/rails/blob/379d98dcd40f28fd959f42958d662b5416171eea/activerecord/lib/active_record/connection_adapters/abstract/database_statements.rb#L346) a SQL statement for the fixture.

![untitled](https://user-images.githubusercontent.com/8122246/42795524-d4c75da4-8952-11e8-97f7-76d2f675b0dc.png)

After narrowing down the ruby code, it turned out that `Time.utc` was the problem https://github.com/rails/rails/blob/379d98dcd40f28fd959f42958d662b5416171eea/activemodel/lib/active_model/type/helpers/time_value.rb#L58

I then profiled the C stacktrace to confirm it 
<img width="483" alt="screen shot 2018-07-17 at 12 01 39 am" src="https://user-images.githubusercontent.com/8122246/42795931-ecf265e8-8954-11e8-8658-df6135ac1bee.png">

And finally this led me to this SO post that also confirmed it https://stackoverflow.com/questions/27932330/why-is-tzset-a-lot-slower-after-forking-on-mac-os-x
As well as https://bugs.ruby-lang.org/issues/14435
As I was saying above I first thought this was due to spring, but of course it wasn't. It's just that spring forks the main process.

cc/ @rafaelfranca @csfrancis

**Comment by rafaelfranca** [comment]
This commit fix this issue https://github.com/ruby/ruby/commit/6538f67d4dccc32f1613be188a0748f0d4f90a05#diff-c8a40c09e14497d660b2e094dd439218.

Let's try to get it backported.

**Comment by rafaelfranca** [comment]
This is going to be fixed in the next ruby patch version so I'm closing.
