### ISSUE TITLE
Unwanted query parameter "null=" added to the url in a get request test using as: :json

### ISSUE THREAD

**Issue by silva96** [rails/rails#33388]
### Steps to reproduce
when calling [this method](https://github.com/rails/rails/blob/master/actionpack/lib/action_dispatch/testing/integration.rb#L17) (i'm calling it from rspec request test)

using `as: :json` for a get request (so we can easilly have the json headers) adds a parameter to the url `null=`

This happens because in [this line](https://github.com/rails/rails/blob/master/actionpack/lib/action_dispatch/testing/integration.rb#L236)

it encodes the `nil` parameters as json, and `nil.to_json`  is `null`

I solved it by re registering the json_encoder like this (for now, in an initializer)

```ruby
ActionDispatch::IntegrationTest.register_encoder(
  :json,
  param_encoder: -> params { params ? params.to_json : nil },
  response_parser: -> body { JSON.parse(body) }
)
```

### Expected behavior
It should not add `null=` to the url

### Actual behavior
it adds a  `null=` to the url

### System configuration
**Rails version**: 5.2.0

**Ruby version**: 2.5.1

**Comment by azbshiri** [comment]
I'm working on this. If you don't mind?
