### ISSUE TITLE
Unable to serve raw assets when `public/assets/` exists

### ISSUE THREAD

**Issue by mdkalish** [rails/rails#33397]
### Steps to reproduce

1. Run `bundle exec rake assets:precompile`.
2. Run `bundle exec rails s`.

### Expected behavior

1. Asset dir should be configurable, eg. `config.assets.path = "/app/assets/"` && `config.assets.serve_compiled = false`.
2. Independently, in dev env, if the `public/assets/` exists but is empty, server should not return 404s but fallback to raws in `app/assets/`.

### Actual behavior

1. Rails uncontrollably will serve assets from the `public/assets/`. Imho, this is counterintuitive in dev env – the files just could have been staled there from some work on prod env (eg. cache debugging, etc.). Mind that even though you can cache and compile assets on first request on the fly with sprockets, serving raws is impossible in production env; please correct me if I'm wrong.
2. Even when the dir is empy – then browser will just return 404s.

### System configuration
**Rails version**: 5.1.6

**Ruby version**: 2.4.0

**Comment by rafaelfranca** [comment]
The static assets, inside `public` have precedence over over the dynamic content to match the same behavior that production. Given that and that we don't recommend people to run `assets:precompile` in development we don't consider this a bug.

If you don't want this behavior you can disable it using `config.public_file_server.enabled = false`

 Thank you for the issue.

**Comment by mdkalish** [comment]
> If you don't want this behavior you can disable it using `config.public_file_server.enabled = false` 

@rafaelfranca, if the `public/assets/` is present, this config option does only disable serving from the dir, but it won't enable serving anything else – just no assets will be loaded. And this is what I consider a bug: The only way of fallbacking to `app/assets/` is by removing the `public/assets/`. On a larger scale, there's no native way to control the asset root path.

This option is useful in production when you serve compiled assets from eg. a CDN (along with `config.action_controller.asset_host`), but it is useless in development while the `public/assets/` is there (unless you see any value in not loading assets).
