### ISSUE TITLE
Rails Engine Guide: require_dependency

### ISSUE THREAD

**Issue by esambo** [rails/rails#33398]
The Rails Engine Guide: [6.1.1 A note on Decorators and Loading Code](http://guides.rubyonrails.org/engines.html#a-note-on-decorators-and-loading-code) mentions to use `Rails.root`.
This doesn't work for me unless I change it to `Engine.root`

### Steps to reproduce
Create a mountable engine and try requiring custom files in /lib/engine_name/ and then try using them from the application.

### Expected behavior
Being able to use the constant

### Actual behavior
`LoadError: Unable to autoload constant`

### System configuration
**Rails version**: 
5.1.4

**Ruby version**:
2.4.2

**Comment by rafaelfranca** [comment]
That guide is in work and progress and may have incorrect information.

If the file is inside the engine you need to `Engine.root` if the file is inside the application you can use `Rails.root`.

**Comment by esambo** [comment]
Thanks!
Although I can even use Engine.root in the app like:
`require File.join(EngineName::Engine.root, *%w[lib engine_name file])`

**Comment by rafaelfranca** [comment]
Yeah, you can. What I mean is that if you file is inside the application folder you should `Rails.root`. That is the case in that guide, the file that it is trying to require is inside the application.
