### ISSUE TITLE
Setting Activestorage attachments in fixtures?

### ISSUE THREAD

**Issue by thedarkside** [rails/rails#33404]
Is it possible to define fixtures with attached activestorage files? I'm curious how to setup those because its needed for lets say system tests. when i am enforcing the presence of a file in a model then the code expects an attached file.

The best way would be to specify a file like this:
```yaml
apple:
  picture: path/to/file.jpg
```

**Comment by georgeclaghorn** [comment]
Sorry, that isn’t possible yet. You’ll want to attach files as needed in your tests and delete the test service’s root on teardown.
