### ISSUE TITLE
ujs - AcceptHeaders - json

### ISSUE THREAD

**Issue by slavik117** [rails/rails#33402]
https://github.com/rails/rails/blob/1a0bcc3b49e05eba852912f609a20c36a9656857/actionview/app/assets/javascripts/rails-ujs/utils/ajax.coffee#L12

Is it just a typo? May be, correct line is:
json: 'application/json, text/json'

**Comment by azbshiri** [comment]
There's no mime type called `text/json`. Also `text/javascript` is obsolete and for JSONP we should use `application/javascript`.

**Comment by slavik117** [comment]
Thank you for answer.
