### ISSUE TITLE
Joins through does not cast the correct primary/foreign key types

### ISSUE THREAD

**Issue by stas** [rails/rails#33407]
### Steps to reproduce

1. Create a new model with a polymorphic association of type string.
2. Create a record with the new model using a primary key of a different type (integer or UUID)
3. Add an association to a third model to point to the new polymorphic association using `through`.
4. Try to use the `through` association and you will get an exception.

### Expected behavior

Using a direct association (no `through`) works. I expect this to be consistent is I add intermediary associations. Or at least I would like to have an API I could specify if _auto-casting_ is needed.

### Actual behavior

The intermediary association using `through` ignores the difference in primary/foreign key types.

I prepared a test-case below:
https://gist.github.com/stas/7a9a6cbf76ffe8330059dfda0b5fa57a

I spent some time trying to figure out the issue, but it doesn't look obvious. Could really use some help/directions or a second opinion.

Thanks in advance!

### System configuration

**Rails version**: 4.x

**Ruby version**: 2.3.6

**Comment by twitnithegirl** [comment]
Hi friend, I was able to reproduce your issue locally. Currently the last supported version for bug fixes is 5.2.*

I ran your example against rails master and got the following output. The error message is more useful in this case. I hope this helps.
```
# Running:

D, [2018-07-20T16:00:04.180631 #26704] DEBUG -- :    (0.2ms)  BEGIN
D, [2018-07-20T16:00:04.182028 #26704] DEBUG -- :   Book Create (0.7ms)  INSERT INTO "books" ("title") VALUES ($1) RETURNING "id"  [["title", "Book"]]
D, [2018-07-20T16:00:04.182779 #26704] DEBUG -- :    (0.4ms)  COMMIT
D, [2018-07-20T16:00:04.189049 #26704] DEBUG -- :    (0.2ms)  BEGIN
D, [2018-07-20T16:00:04.190667 #26704] DEBUG -- :   Tag Create (0.7ms)  INSERT INTO "tags" ("title") VALUES ($1) RETURNING "id"  [["title", "Tag"]]
D, [2018-07-20T16:00:04.191574 #26704] DEBUG -- :    (0.5ms)  COMMIT
D, [2018-07-20T16:00:04.206115 #26704] DEBUG -- :    (0.2ms)  BEGIN
D, [2018-07-20T16:00:04.208348 #26704] DEBUG -- :   Tagging Create (1.1ms)  INSERT INTO "taggings" ("taggable_type", "taggable_id", "tag_id") VALUES ($1, $2, $3) RETURNING "id"  [["taggable_type", "Book"], ["taggable_id", "1"], ["tag_id", 1]]
D, [2018-07-20T16:00:04.215072 #26704] DEBUG -- :    (6.4ms)  COMMIT
D, [2018-07-20T16:00:04.223504 #26704] DEBUG -- :    (0.5ms)  SELECT COUNT(*) FROM "taggings" WHERE "taggings"."tag_id" = $1  [["tag_id", 1]]
D, [2018-07-20T16:00:04.243103 #26704] DEBUG -- :    (6.7ms)  SELECT COUNT(*) FROM "books" INNER JOIN "taggings" ON "books"."id" = "taggings"."taggable_id" WHERE "taggings"."tag_id" = $1 AND "taggings"."taggable_type" = $2  [["tag_id", 1], ["taggable_type", "Book"]]
E

Error:
BugTest#test_association_stuff:
ActiveRecord::StatementInvalid: PG::UndefinedFunction: ERROR:  operator does not exist: bigint = character varying
LINE 1: ...ROM "books" INNER JOIN "taggings" ON "books"."id" = "tagging...
                                                             ^
**HINT:  No operator matches the given name and argument type(s). You might need to add explicit type casts.
: SELECT COUNT(*) FROM "books" INNER JOIN "taggings" ON "books"."id" = "taggings"."taggable_id" WHERE "taggings"."tag_id" = $1 AND "taggings"."taggable_type" = $2**
    
bin/rails test my_stuff/tmp.rb:50
```

**Comment by stas** [comment]
Hi @twitnithegirl, thanks for taking a look!

Unfortunately, your reply this doesn't answer my question.

In fact, [the output/error is not the issue](https://gist.github.com/stas/7a9a6cbf76ffe8330059dfda0b5fa57a#gistcomment-2654181). The issue is that ActiveRecord API does not cast and does not provide a way to handle situations where a join query uses different types for foreign keys.

The inconsistency I'm trying to point out is that you can create and query records up to the point where you use a `through` type.
I'm open to alternatives, but I find it frustrating that our ORM doesn't let us run a simple JOIN query. :thinking:

**Comment by ziaulrehman40** [comment]
Any workarounds yet?
Have hit by same :/

**Comment by stas** [comment]
@ziaulrehman40 I created a virtual column that casts the foreign key to the right type. An example would be:

```
class AddStringIdToUserProject < ActiveRecord::Migration
  def up
    execute <<-SQL
      CREATE OR REPLACE FUNCTION string_id(user_projects)
      RETURNS text AS $$
        SELECT $1.id::text
      $$ STABLE LANGUAGE SQL;
    SQL
  end
end
```

More on virtual columns can be found here:
https://www.enterprisedb.com/blog/creating-virtual-columns

**Comment by jhubert** [comment]
@stas and @ziaulrehman40 

I'm exploring a different approach. It seems to work nicely, although I haven't thought through all of the implications of it yet.

I decided to focus on the "no operator exists" part of the error message, which led me to figure out how to define a custom operator. Here is what I've come up with.

As an additional point of complexity, we use postgresql schemas, so these functions and operators need to be defined in the shared schema so that they are available in all of the other schemas.

```ruby
    # Create the functions that convert and compare the provided values
    connection.execute <<~SQL
      CREATE OR REPLACE FUNCTION shared_extensions.myfunc_text_uuid_eq(text, uuid)
        RETURNS boolean AS 'SELECT $1::uuid = $2' LANGUAGE SQL IMMUTABLE STRICT;

      CREATE OR REPLACE FUNCTION shared_extensions.myfunc_text_uuid_ne(text, uuid)
        RETURNS boolean AS 'SELECT $1::uuid <> $2' LANGUAGE SQL IMMUTABLE STRICT;
    SQL

    # Create the operator that makes the string to UUID comparison automatic
    connection.execute <<~SQL
      CREATE OPERATOR shared_extensions.= (
        LEFTARG = text,
        RIGHTARG = uuid,
        PROCEDURE = shared_extensions.myfunc_text_uuid_eq,
        COMMUTATOR = =,
        NEGATOR = <>,
        RESTRICT = eqsel,
        JOIN = eqjoinsel
      );

      CREATE OPERATOR shared_extensions.<> (
        LEFTARG = text,
        RIGHTARG = uuid,
        PROCEDURE = shared_extensions.myfunc_text_uuid_ne,
        COMMUTATOR = <>,
        NEGATOR = =,
        RESTRICT = eqsel,
        JOIN = eqjoinsel
      );
    SQL
```

This command can be run as a migration or as part of a db setup script. What it does is create a new operator to handle the uuid = character varying comparison for both = and <> (which is the same as !=).

With this change, my uuid to polymorphic join queries just work. No other changes required to the standard rails approach.

Warning: I haven't fully tested this in production yet. YMMV.

**Comment by stas** [comment]
Thanks for sharing @jhubert!

**Comment by arcreative** [comment]
> I'm exploring a different approach. It seems to work nicely, although I haven't thought through all of the implications of it yet.

This... is... awesome.  It feels messy in the sense that I might miss out on some odd text/integer comparisons that I probably shouldn't be doing, and secondly that this may not be a good idea for performance reasons, or Postgres would seemingly do this implicitly.  

Having to weigh this against making my double-polymorphic join table bound to a single model, alternatively, which I don't like either.  Guess I'll try this out for now and figure it out later if we have any issues in our project.

**Comment by jhubert** [comment]
@arcreative We're now 4 years running with this in production and no issues. 😄

**Comment by arcreative** [comment]
> @arcreative We're now 4 years running with this in production and no issues. 😄 

Yeah, can confirm this works as intended. Never dug too far into performance benchmarking, but haven't noticed any ill effects of using this on the Postgres side. Definitely eliminates one of my top complaints about Postgres!
