### ISSUE TITLE
ActionCable channel code reloading doesn't work

### ISSUE THREAD

**Issue by mdesantis** [rails/rails#33412]
Probably I'm missing something since a so obvious bug hasn't been reported yet (maybe I'm just bad at searches?), anyway: on my attempts, ActionCable channels code reloading doesn't work.

### Steps to reproduce

1. generate a new Rails app: `rails new channel-reloading && cd channel-reloading`
2. generate a new channel: `rails g channel Foo bar`
3. generate a new controller: `rails g controller Home index`
4. start the Rails server: `rails s`
5. visit `http://localhost:3000/home/index` in the browser
6. run `App.foo.bar()` in the browser web console: it outputs `true` and the server console prints out `FooChannel#bar`
7. open `app/channels/foo_channel.rb` and put `raise 'hello'` within `def bar` method definition
8. run `App.foo.bar()` in the browser web console: it prints out `true` and the server console prints out `FooChannel#bar`
9. restart the Rails server
10. run `App.foo.bar()` in the browser web console: it prints out `false` and the server console prints out `FooChannel#bar` plus the error generated by `raise 'hello'`

### Expected behavior

On step 8. the web console should print out `false` and the server console should print out the error generated by `raise 'hello'` without requiring the Rails server to be restarted

### Actual behavior

On step 8. the web console prints out `true` and the server console prints out `FooChannel#bar`

### System configuration
**Rails version**: 5.2.0

**Ruby version**: 2.5.1

**Comment by palkan** [comment]
> it's not possible to reload for every arriving websocket message.

But we can "reload" (in our case, restart Action Cable server) when `config.reload_classes_only_on_change = true`. That makes sense, doesn't it?

**Comment by mdesantis** [comment]
Hi all, thank you for taking it seriously! Apart from the considerations about the workaround / fix involving the required re-connection (which would be great), could this behaviour be documented in the [ActionCable guide](http://guides.rubyonrails.org/action_cable_overview.html)? In this way it should be more obvious for a developer recognize it as a known behaviour (I've never noticed that note in the Framework Behavior section)

**Comment by jeremy** [comment]
+1 to document Action Cable development in the guide, including how to make changes to your channel classes and see the results reflected in the browser.
