### ISSUE TITLE
ActiveStorage returns 404 using local disk service even though file exists

### ISSUE THREAD

**Issue by feliperaul** [rails/rails#33423]
### Steps to reproduce

```
class Model
  has_many_attached :attachments, dependent: :destroy

# In form
<%= form.file_field :attachments, multiple: true %>

# In controller
def model_request_params
  params.require(:model_name).permit(:title, attachments: [])
end

# In config/storage.yml
local:
  service: Disk
  root: <%= Rails.root.join("storage") %>

# In development.rb
config.active_storage.service = :local

# In view
<%#= image_tag @model_instance.attachments.first %>
```
When I open the browser, the generated HTML is like this:
`http://localhost:3000/rails/active_storage/blobs/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBDZz09IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--3814080e8c7e26964c927840a18034d727c61d87/file.jpg`, but this returns a 404 not found.

The weird thing is that I have a different Rails 5.2.0 project and as soon as this GET is fired, the server console shows Precessing by ActiveStorage::Blobs Controller.

On this project however, I only see this:

`Started GET "/rails/active_storage/blobs/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBDZz09IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--3814080e8c7e26964c927840a18034d727c61d87/file.jpg" for 127.0.0.1 at 2018-07-23 12:15:36 -0300`

It is NOT followed by anything else, not indicating any controller or whatever, but the browser gets a 404 and the image is never loaded. 

I can confirm the attachment is uploaded, because not only `model_instance.attachments[0]` returns a ActiveStorage::Attachment, but the file is also present in my project's `storage/` folder. 

### Expected behavior
Image should load without 404. 

### Actual behavior
Errors with 404. 

### System configuration
**Rails version**: 5.2.0

**Ruby version**: 2.3.6

**Comment by georgeclaghorn** [comment]
What do you get if you open a Rails console and run the following?

```ruby
ActiveStorage::Blob.find_signed("eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBDZz09IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--3814080e8c7e26964c927840a18034d727c61d87")
```

Does `model_instance.attachments.first.signed_id` match the signed ID in the image URL?

**Comment by feliperaul** [comment]
@georgeclaghorn I get the attachment instance when I run that!

```
ActiveStorage::Blob.find_signed("eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBDZz09IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--3814080e8c7e26964c927840a18034d727c61d87")
ActiveStorage::Blob Load (0.5ms)  SELECT  `active_storage_blobs`.* FROM `active_storage_blobs` WHERE `active_storage_blobs`.`id` = 5 LIMIT 1 /*application:Temporadalivre,line:(pry):5:in `<main>'*/
=> #<ActiveStorage::Blob:0x00007f81e27176c0
 id: 5,
 key: "m2QJjh8b4Tk6GGxKkdPCrQe1",
 filename:
  "filename.jpg",
 content_type: "image/jpeg",
 metadata: {"identified"=>true},
 byte_size: 172591,
 checksum: "X1FPHR/URZQMdY3d41w5hQ==",
 created_at: Mon, 23 Jul 2018 12:05:34 -03 -03:00>
```

So I think the issue lies at the controller level or something. The project where the bug occurs was updated from Rails 4.2, and the GET requests are followed by **nothing** on the server terminal, while I have a new project that started on Rails 5.2.0 that I see `Precessing by ActiveStorage::Blobs Controller` after the GET request.

**Comment by georgeclaghorn** [comment]
That’s exactly what the controller does. 😕

I’d recommend stepping through `ActiveStorage::SetBlob#set_blob` and `ActiveStorage::BlobsController#show` with a debugger to see exactly what’s going wrong.

**Comment by feliperaul** [comment]
@georgeclaghorn George, I currently don't have those controllers defined anywhere, since I haven't overwritten them. Do you suggest I define them and use `binding.pry` to see if they are being called and the steps that are happening or something else I didn't understand?

**Comment by georgeclaghorn** [comment]
If you’re able to write a failing test in your app, you can use Pry or Byebug to set breakpoints on those methods.

Alternatively, you can use `bundle open activestorage` to edit your local copy of the gem. Set the `EDITOR` environment variable to your preferred editor, e.g.: `EDITOR="atom --wait" bundle open activestorage`.

Add logging statements to the methods I mentioned earlier to see if they’re being reached and what they’re doing. For example, you might modify `ActiveStorage::SetBlob#set_blob` to look like this:

```ruby
def set_blob
  @blob = ActiveStorage::Blob.find_signed(params[:signed_blob_id] || params[:signed_id])
  logger.debug "@blob = #{@blob.inspect}"
rescue ActiveSupport::MessageVerifier::InvalidSignature
  logger.debug "Failed to set @blob"
  head :not_found
end
```

Then you can use your app and check the logs.

Sorry for the hassle. I’d ask you for a minimal sample app and do this work myself, but I suspect the issue would be difficult to reproduce.

**Comment by feliperaul** [comment]
@georgeclaghorn Geroge, first of all thanks for the detailed instructions.

Here's what I have to report ... the controllers are not being hit at all!

```
class ActiveStorage::BaseController < ActionController::Base
  protect_from_forgery with: :exception

  before_action do
    binding.pry
    Rails.logger.info("Before_action in Base Controller")
    ActiveStorage::Current.host = request.base_url
  end
end
```

That `binding.pry` is never run, neither the logger output is printed in the server terminal.

I did the same with `ActiveStorage::SetBlobg#set_blob`, but that before_action is never run as well. 

To be sure I could read the log output, I tried this:

```
class ActiveStorage::Blob < ActiveRecord::Base
  (...)
  Rails.logger.info("Blobg class definition")
```

And sure enough, saw that output on my server terminal.

I have never modified my gems in anyway whatsoever. But just to be sure, I compared my ActiveStorage's routes.rb with the one in https://raw.githubusercontent.com/rails/rails/master/activestorage/config/routes.rb and they are 100% the same. 

The URL http://localhost:3000/rails/info/routes also displays ActiveStorage routes, so they should be routing, but I don't know why they are not triggering the controller. 

Any idea about what's going on? I checked #32959 but I don't use that gem. 

This might be affecting other people as well.

**Comment by feliperaul** [comment]
@georgeclaghorn George, just figured it out. I'm posting the solution here in 5 min.

**Comment by feliperaul** [comment]
@georgeclaghorn So, here's the culprit, I had this at the very beginning of my routes.rb file:

```
if Rails.env.development?
    scope format: true, constraints: { format: /jpg|png|gif|PNG/ } do
      get '/*anything', to: proc { [404, {}, ['']] }
    end
  end
```

Sorry for wasting your time on this, but I had totally forgotten about this hack. Here's some context:

We frequently dump the production database to our dev machines to have an up-to-date dev environment. But we do NOT copy the entire public/uploads folder because it's crazy huge.

This makes so that many of the pages that link to uploaded assets are VERY slow to load, because each image hits the dev application server which errors out with 404. 

After this slowing us down for years, we found [this excellent solution in a makandra card](https://makandracards.com/makandra/45120-rendering-404s-for-missing-images-via-rails-routes):

> When you load a dump for development, records may reference images that are not available on your machine. Requests to those images may end up on your application, e.g. if a catch-all route is defined that leads to a controller doing some heavy lifting. On pages with lots of missing images, this slows down development response times. You can fix that by defining a Rails route like this:
(code above)
Images are (usually) served directly from public or assets and won't hit your controllers/routes, as long as the files exist. If files are missing, the request will be handled by the above route which instantly responds with an empty HTTP 404 response.

Needless to say, that hacky fix was hijacking the `/rails` routes used by ActiveStorage because they satisfied the constraint. 

I can't comment on makandra cards, but I hope Google will bring people here. 

In the meantime, I changed the hack to this:

```
if Rails.env.development?
    scope format: true, constraints: { format: /jpg|png|gif|PNG/ } do
      get '/*anything', to: proc { [404, {}, ['']] }, constraints: lambda { |request| !request.path_parameters[:anything].start_with?('rails/') }
    end
  end
```

And it works! Thanks a lot.

**Comment by vcavallo** [comment]
@feliperaul You saved me hours, maybe days, and _mountains_ of frustration. I've got a similar globby hack in my routes and I'm not sure I ever would have gotten to the bottom of this if you hadn't first 😆 thanks!

**Comment by swanson** [comment]
I was seeing really similar behavior in my app. The cause was similar (a router issue) but in my case, we were using a gem: https://github.com/substancelab/route_downcaser to downcase urls before they get processed by Rails. This was downcasing the signed id (example: "eyJfcmFpb..." became "eyjfcmfpb...") so `set_blob` in ActiveStorage was failing and thus 404ing.

So the moral of the story, if you're seeing this kind of behavior, double and triple check your `routes.rb` to make sure you aren't doing anything funky.

**Comment by mikeappell** [comment]
Not exactly the same, but very similar. Previously we were explicitly defining our ActiveStorage routes – however, it seems like some behavior relating to AS's paths changed between rails 5.2 and 7 (which was an upgrade I was undertaking), and so I removed these routes from routes.rb. They're added automatically by ActiveStorage (I believe), so having them explicit was unnecessary – and causing errors since the old, manual ones were no longer correct.

However, I started getting very surprising 404s at this point, being caught by our ErrorsController. Took me a few hours to figure out why, and the above post helped point the way. The issue:

```ruby
# routes.rb
# This was the last entry in the file
match '*path' => "errors#show", via: [:get, :post, :head]
```

With the explicit routes removed from our routes file, any requests to our ActiveStorage controller were falling into this glob path. Commenting this last route out fixed the issue right away.

**Comment by shahbazhassan42000** [comment]
@feliperaul You are a saviour, I had the same problem with a wildcard route that interfered with the Active Storage route, thanks a bunch for this post❣️.

**Comment by joel-vl** [comment]
Thanks @swanson! Checking my routes.rb was the solution. For some reason, I had the following in my routes.rb:
`  get '/*a', to: 'application#not_found'`
