### ISSUE TITLE
HTTPS broken on api.rubyonrails.org website

### ISSUE THREAD

**Issue by vramana** [rails/rails#33422]
### Steps to reproduce

Visit https://api.rubyonrails.org

### Expected behavior

Visiting https://api.rubyonrails.org should just work

### Actual behavior

Visiting https://api.rubyonrails.org fails with `ERR_CONNECTION_REFUSED` on Chrome

### System configuration
**Rails version**: Not relevant

**Ruby version**: Not relevant

**Comment by fxn** [comment]
You're right, we need to implement this.

**Comment by fxn** [comment]
This is up:

* https://api.rubyonrails.org
* https://guides.rubyonrails.org
* https://edgeapi.rubyonrails.org
* https://edgeguides.rubyonrails.org
* https://contributors.rubyonrails.org

**Comment by vramana** [comment]
Cool thanks @fxn. Can you add HSTS header as well?

**Comment by vramana** [comment]
Sorry I would love to but I don't want to learn nginx configuration now. Got too much on my plate.

**Comment by RahulMahale** [comment]
@fxn @vramana  here we go https://github.com/rails/rails-docs-server/pull/9 if that helps. :)

**Comment by vramana** [comment]
@RahulMahale Thanks!!! :heart:
