### ISSUE TITLE
NumericalityValidator is reading value before type cast. Expected cast value for Rails Attribute

### ISSUE THREAD

**Issue by cguyer** [rails/rails#33431]
### Steps to reproduce

Create a Rails Attribute API type, in my case it was overriding String to squish value when squish is set to true for the attribute type.
```
class Phone < ApplicationRecord
  attribute :extension, :string, squish: true
  validates :extension, numericality: { only_integer: true }
end
```
On create, the value returned from the rails attribute is valid but when it is an update, NumericalityValidator appears to use the raw value before it is cast by the attribute?

Passes:
```
it "should accept extensions with space" do
    phone = Phone.new(number: '5551231234', extension: '30 ')
    expect(phone).to be_valid
  end
```
Fails:
```
  it "should accept extensions with space on update" do
    phone = Phone.new(number: '5551231234', extension: '30 ')
    expect(phone).to be_valid

    phone.save
    phone.extension = '30 '
    expect(phone).to be_valid
  end
```
```
Phone should accept extensions with space on update
     Failure/Error: expect(phone).to be_valid
       expected #<Phone id: 38, number: "+15551231234", extension: "30" > to be valid, but got errors: Extension must be an integer
```

### Expected behavior
That NumericalityValidator would use the value set by a Rails Attribute.

### Actual behavior
Update call appears to use the raw value.
There appears to have been another issue with #32531 that had a similar issue but that did not resolve my issue.

### System configuration
**Rails version**: Rails 5.2.0
**Ruby version**: ruby 2.4.4p296 (2018-03-28 revision 63013)

**Comment by y-yagi** [comment]
Can you create a reproduces script with this [template](https://github.com/rails/rails/blob/master/guides/bug_report_templates/active_record_master.rb)?

**Comment by cgriego** [comment]
Using the pre-typecast value is behavior that has been a part of the numericality validation since day 1.
https://github.com/rails/rails/commit/838ae35d63c34872d46bee8b006796ebdd9c7722

As a contributor to libraries that rely on ActiveModel, I very much expect that behavior.
