### ISSUE TITLE
Decouple Active Job from Action Mailer

### ISSUE THREAD

**Issue by tylerhunt** [rails/rails#33433]
I'm interested in creating a PR to decouple Active Job from Action Mailer by making it an optional dependency instead of a required one, but I'd like to receive some feedback on doing such work before I begin on it.

The goal would be to have Action Mailer function as it currently does when Active Job is available (i.e. `require 'active_job'` succeeds), but when it isn't allow Action Mailer to be used without all the asynchronous Active Job bits.

My motivation for doing this is to allow the use of Action Mailer in situations where a job queue may not be required or where a queuing library other than Active Job is in use.

Is this sort of change something the core team would be open to?

**Comment by y-yagi** [comment]
Please use the [Rails Core mailing list](https://groups.google.com/forum/#!forum/rubyonrails-core) for feature requests, where a wider community will be able to help you. We reserve the Rails issue tracker only for bugs in Rails. Thanks!

**Comment by matthewd** [comment]
To save you an email:

> Is this sort of change something the core team would be open to?

No. Active Job _is_ the decoupling layer. If you don't want it to use a queue, you can configure it to use either the `async` or `inline` adapter.
