### ISSUE TITLE
Active Record breaks presence validation for null objects

### ISSUE THREAD

**Issue by tf** [rails/rails#33445]
### Steps to reproduce

When overriding an association to return a null object instead of `nil`, `validates_presence_of` no longer reports a validation error when the attribute is not set:

```ruby
class Post < ActiveRecord::Base
  has_many :comments
end

class NullPost
  def blank?
    true
  end

  def marked_for_destruction?
    false
  end
end

class Comment < ActiveRecord::Base
  belongs_to :post

  validates_presence_of :post

  def post
    super || NullPost.new
  end
end

comment = Comment.new
comment.valid?

assert comment.errors[:post].present? # => fails
```

Gist with failing test case:

https://gist.github.com/tf/9be6ac3661ba3dfd5608365229d0ac0b

### Expected behavior

Null objects are treated as blank values.

### Actual behavior

Null objects are treated as present values.

### Reason/Breaking change

This used to work in Rails 4.2 until [this commit](https://github.com/rails/rails/commit/006a4d787e3fad4d142605d49ba4541992c6465b) which changed the way Active Record overrides `validates_presence_of` to

```ruby
    # lib/active_record/validations/presence.rb
    class PresenceValidator < ActiveModel::Validations::PresenceValidator # :nodoc:
      def validate_each(record, attribute, association_or_value)
        if record.class._reflect_on_association(attribute)
          association_or_value = Array.wrap(association_or_value).reject(&:marked_for_destruction?)
        end
        super
      end
    end
```

`Array.wrap` leaves `nil` unchanged, but wraps null objects in an array which is passed on to the Active Model validator, which then comes to the understandable conclusion that the passed array is present. 

**Rails version**: 5.2

**Ruby version**: 2.5

**Comment by rafaelfranca** [comment]
You null object should be defining a `to_ary` method that returns an empty array, otherwise it will not only fail in this validation, but also in any place that is going to wrap it. You chose to beak the contract of the active record associations, so you will have to implement more things to make it work with active record.

**Comment by tf** [comment]
Thank you for your answer. Is this contract documented/made explicit somewhere? Anyway, implementing `to_ary` is fine.

**Comment by rafaelfranca** [comment]
In the documentation only.
