### ISSUE TITLE
ActiveStorage direct upload is not working for 0-byte length files

### ISSUE THREAD

**Issue by denisahearn** [rails/rails#33450]
When I attempt to upload a 0-byte length file to S3 using ActiveStorage's direct upload feature, nothing appears to happen. The file does not get uploaded to S3, and my Rails controller action is not called. 

### Steps to reproduce

Sample Rails app demonstrating the issue is attached. Before running, make sure to add your AWS credentials to `config/storage.yml`.

1. Run the sample Rails app. Default page is a "Posts" page listing posts in the database.
2. Click the "New Post" link.
3. Enter a title, body, and choose a 0-byte length file.
4. Click the"Create Post" button

The UI correctly switches to the "uploading" view, but then nothing further happens.

### Expected behavior
The 0-byte length file should be treated the same as a file containing bytes (i.e. uploaded to the configured S3 bucket, form posted back to the associated Rails controller).

### Actual behavior
The form doesn't post back to the associated Rails controller. I see only the `direct-upload:initialize` and `direct-upload:start` events dispatched in my browser's console window.

### System configuration
**Rails version**: Rails 5.2.0

**Ruby version**: ruby 2.4.1p111 (2017-03-22 revision 58053) [x86_64-darwin16]

[direct_upload.zip](https://github.com/rails/rails/files/2233020/direct_upload.zip)

**Comment by georgeclaghorn** [comment]
Thanks for the report! In fixing this, I discovered that analyzing zero-byte blobs when they’re attached for the first time is also broken. I’ll fix that separately.
