### ISSUE TITLE
Cannot Define Enum with attribute "size"

### ISSUE THREAD

**Issue by jonmchan** [rails/rails#33457]
### Steps to reproduce

Just upgraded from rails 5.1.3 to rails 5.2.0. Had the following model:

```
# app/models/design_attribute.rb
class DesignAttribute < ApplicationRecord
  enum design_type: [ :size, :shape, :color ]
end
```

### Expected behavior
In older versions of rails, size was no issue. 

### Actual behavior
Current version of rails, I get the following error:

```
ArgumentError:
  You tried to define an enum named "design_type" on the model "DesignAttribute", but this will generate a class method "size", which is already defined by ActiveRecord::Relation.
```

### System configuration
**Rails version**: 5.2.0

**Ruby version**: 2.5.1

Is this behavior expected? Is size a reserved name to be avoided when creating enums?

**Comment by y-yagi** [comment]
Thanks for your report. Yes, this is intentional behavior.  
Since Rails 5.2, methods defined in `ActiveRecord::Relation` can not be used for enums. 

Ref: #31179
