### ISSUE TITLE
It disappears when the value of the parameter with the same name as the controller is sent with null

### ISSUE THREAD

**Issue by keitaro-shimoji** [rails/rails#33456]
sorry. i can't english.

### Steps to reproduce

1. edit users_controller.rb
```ruby:users_controller.rb
def update
  pp params
end
```
2. PATCH request
```
{
  "user": null,
  "user_name": "test"
}
```

### Expected behavior
```
<ActionController::Parameters {"user"=>nil, "user_name"=>"test",  "format"=>"json", "controller"=>"users", "action"=>"update", "id"=>"1"} permitted: false>
```
I want to get the 'user' key

### Actual behavior
```
<ActionController::Parameters {"user"=>{"user_name"=>"test"}, "user_name"=>"test", "format"=>"json", "controller"=>"users", "action"=>"update", "id"=>"1"} permitted: false>
```

However, the 'user' key will disappear

### System configuration
**Rails version**: 2.3.1

**Ruby version**: 5.0.2

**Comment by eugeneius** [comment]
This was fixed by https://github.com/rails/rails/pull/29553 - if you upgrade to 5.0.7 it will work correctly.
