### ISSUE TITLE
rails 5.1 and 5.2 do not load on jruby

### ISSUE THREAD

**Issue by fabianfrz** [rails/rails#33462]
### Steps to reproduce

* create a new rails application using jruby **9.2.0.0** and run bundler to install the dependencies.
* run rails s - the application crashes on start

### Expected behavior
rails application should start and listen on its port

### Actual behavior
crashes with a stacktrace that `timeout` (and others) cannot be loaded **which are defined in Java code of jruby**.

### System configuration
**Rails version**: 5.1, 5.2 (tested both)

**Ruby version**: jruby 9.2.0.0 (Ruby 2.5.0)

### Additional:
* jruby ticket: jruby/jruby#5264
* what I think is the cause: bootsnap has C dependencies, so it may not work on jruby but is required
* rails runs on the C implementation of ruby (2.5.1)

**Comment by ahorek** [comment]
https://github.com/Shopify/bootsnap/issues/162

**Comment by y-yagi** [comment]
Thanks for your report. 
If using JRuby, we have fixed not to include bootsnap. 
https://github.com/rails/rails/commit/b10f371366a606310cab26648d798836e030bdc8 

Therefore, this issue does not occur from the next version.  
For Rails 5.2.0, please create the application with the `--skip-bootsnap` option. Thanks.

**Comment by fabianfrz** [comment]
@y-yagi thanks for a quick reply. For now, I've deleted the dependency which works too.
