### ISSUE TITLE
- if current_page?(controller: :articles, action: :edit) (No route match)

### ISSUE THREAD

**Issue by jerome-diver** [rails/rails#33461]
### Steps to reproduce
Install rails-5.2 and haml gem
create a view with a line like:
``` haml
#links
  - if current_page?(controller: :articles, action: :edit)
    .butt= button_to "show", @article, method: "get"
```

### Expected behavior
this code is included inside a partial file ( _form.haml )
if i go inside edit action page view, it is ok, but if i go inside a new action page view, 
It should be a "false" value at condition test, and nothing more should happen (no error should be there).

### Actual behavior
there is this error:
No route matches {:actions=>"edit", :controller=>"articles"}

### System configuration
**Rails version**:5.2

**Ruby version**: 2.5.1

I investigate on this bug and i find this inside your own source code about something you use inside the method "current_page? inside actionviewer-5.2 about request_uri:

``` ruby
# File actionpack/lib/action_dispatch/http/url.rb, line 100
      def request_uri
        ActiveSupport::Deprecation.warn "Using #request_uri is deprecated. Use fullpath instead.", caller
        fullpath
      end
```

Could you try to write codes who is NOT deprecated inside your own last version of rails source code (who is also not a beta release), please ?

I fixed my porblem by use:
``` haml
#links
  - if url_for().split("/").last == "edit"
```
So maybe you can try to use it inside your helpers (it is an idea but maybe not a good one) ?

**Comment by lukesarnacki** [comment]
Hi @jerome-diver, when using `current_page?` rails try to find given route by options you pass to the method. And parameters you pass doesn't represent any define route because for `edit` action you need to provide an id. If you try to generate URL for `controller: :articles, action: :edit` parameters you will get an error. Try this in rails console:

```ruby
> app.url_for(controller: :articles, action: :edit)
Traceback (most recent call last):
        1: from (irb):5
ActionController::UrlGenerationError (No route matches {:action=>"edit", :controller=>"articles"})
```

To generate proper URL you would need to add `id` parameter:

```ruby
> app.url_for(controller: :articles, action: :edit, id: 1)
 => "http://www.example.com/articles/1/edit"
```

So `current_page?` doesn't work, because it doesn't know how to generate an URL from parameters you passed to it, not because it is broken. To fix it, you could write:

```haml
  - if current_page?('/edit')
```

That said, I don't think that documentation is intuitive - maybe this is the place where change could be made.

Also, you are missing a point about `request_uri` deprecation. As you can see, the only thing that `request_uri` does is giving a warning and calling `fullpath`. So besides logging a warning it works just as if you wrote `fullpath` and it is a cosmetic change in this case.

**Comment by sikachu** [comment]
I think @lukesarnacki's explanation is perfect, and since this is a non-issue I'm going to close this.

If this `_form` partial won't be shared, I think you can do `if current_page?(action: :edit)` as well. Based on the doc, that should work. If not, please let us know.

**Comment by lukesarnacki** [comment]
@sikachu controller seems to be default when passing `action: :edit` - that is the biggest misconception. I would assume that it works the way you wrote, but it needs an exact route, because of this line:

https://github.com/rails/rails/blob/5df23a04a31e95beb9a5728851345a68b3bca2ac/actionview/lib/action_view/helpers/url_helper.rb#L553

**Comment by sikachu** [comment]
🤔

Weird. That seems like a bug then due to the documentation here: https://edgeapi.rubyonrails.org/classes/ActionView/Helpers/UrlHelper.html#method-i-current_page-3F

You should be able to write `action :edit` and it should take current path's parameter into account and only change the value that you passed in. I wonder this happened since when.

I'm going to reopen this issue. @lukesarnacki @jerome-diver do you have some time to write a failing test case, and maybe a patch if you want to give this a shot, to fix this issue?

**Comment by jerome-diver** [comment]
@lukesarnacki, thank you for try to explain me and try to understand what i was thinking about this method.
I tryed to remove controller and hold only action, that doesn't works like this inside my application.

@sikachu, try to not jump quick for close without be sure to not really understand what users said please... maybe there is something more for increase quality of something or help someone (if you care about help someone). Also, like you asked, i take time to create a test case application on bitbucket public repo.
Inside this simple test_case application, it seems to works fine (also with controller: option)
That is strange, i start to stick to gem i use (like move sass-rails for sassc-rails) but ok, works again.
It maybe have something collision or whatever with an other one gem maybe ?
then i decide to provide two links:
1. [my current_page_test bitbucket rails app public repo](https://bitbucket.org/jerome___/current_page_test/src)

2. [my public web site rails app where current_page? failed](https://bitbucket.org/jerome___/aquaworks/src)

Well, yes, i'm really confuse with this strange method, because i understood that:
>  there is a ? char at the end of the name of the method, so i was thinking (and that i think to when i read the api doc) that it has to  CHECK if current_page IS on a kind of controller AND action route (AND id ONLY IF id was define). But this is also what it does when it works in the test case application.

**Actually, i don't know why, but it doesn't works in some unknown condition(s)**

For the test case application, method is inside app/views/posts/_form.html.haml

For my own web site application i'm creating actually methods current_page? are iniside:

1. app/views/categories/_form.haml

1. app/views/subjects/_form.haml

1. app/views/articles/_form.haml

@sikachu please, by close it, it make me feeling like you push me out without take time to provide a help. I may be feel it wrong, but please, leave it open as long as we don't find what's happening.

Thank you very much for your investigations.

**Comment by lukesarnacki** [comment]
@jerome-diver it is a standard practice to close an issue when there is a suspicion that it is not a bug - there are a lot of false reports. I know it can make you feel in a certain way, but it makes issues cleaner and as you could see it is reopened as soon as any doubt arises :)

@sikachu I can add a failing test.

**Comment by jerome-diver** [comment]
ok, thank you for that.
i was thinking about maybe devise because of his devise route code inside routes.rb config file.
Also, at devise installation time, i had to change a default config in devise.rg config file for eager_load (who i don't know what is it) because of loop error.
I can use url_for in place of current_page? but i would be very happy to find why this current_page? method failed inside my application code. I have no clue and don't know how to get more debug message deeply (and my knowledge isn't suffisant with Ruby and Rails for find it).
@lukesarnacki maybe if you know how to reproduce for fail test, feel free to create a branch in my public repo i linked above... you are welcome and free to do like you want.

**Comment by lukesarnacki** [comment]
@jerome-diver `current_page?` doesn't work for you because it uses `url_for` and `url_for` needs *all* parameters for exact given route. In your case it means that `:id` parameter is missing on `new` route and rails fails at this point (so this is indeed a bug). To make it work for you, you can use string instead at least for now:

```ruby
  - if current_page?('/edit')
```

**Comment by lukesarnacki** [comment]
@sikachu I thought that this is happening because of `edit` route in particular, but it seems like it fails also when you pass only `:action` parameter with an error (this is in my PR):

```
Error:
UrlHelperTest#test_current_page_with_only_action:
ActionController::UrlGenerationError: No route matches {:action=>"bar"}
```
Can you please check if this test is valid?

**Comment by lukesarnacki** [comment]
I spent more time on this and it seems like the test case fails for different reasons. It seems like in real rails app controller is automatically added whereas in the test case scenario it is not. I guess that this is because of mocking. So while it shows a similar problem (trying to find exact route, while only partial params where provided) it does so for different reasons. I will think about the solution for that problem and we can figure out if given test case is enough or not later.

**Comment by sikachu** [comment]
Thank you for the PR. I've assigned myself to this so I will remember to come back for it.

I honestly believe that this is a regression to the old behavior, but I could be wrong ... so I already pinged other core team if they remember any change regarding to this and what could cause the issue.

**Comment by jerome-diver** [comment]
@lukesarnacki, ok, for my test-case simple application, current_page? is working for new and edit together (and from a partial file _form).
Also, as you said, in my application (not the test case one), it works only when i do:
``` ruby
if current_page?('/edit')
```
and never in other situations.

@sikachu thank you for you time to investigate to.

**Comment by RigoTheDev** [comment]
Correct me if I'm wrong, but I believe `current_page?()` is only URLs like `/edit` or `edit_path`. Not `controller#action` strings.

**Comment by lukesarnacki** [comment]
@RigoTheDev that's what I thought as well (as I wrote in my first comment here), but then @sikachu wrote that it may be a bug ;) This is either a bug or just very misleading documentation for people not knowing rails on high level imo.

**Comment by sikachu** [comment]
@RigoTheDev It doesn't take `controller#action` string unlike route file, but it does take a hash `{ contoller: "foo", action: "bar" }` or a subset of that hash:

https://github.com/rails/rails/blob/v5.2.0/actionview/lib/action_view/helpers/url_helper.rb#L498-L572

**Comment by RigoTheDev** [comment]
@sikachu I see, so I guess the fix to this issue is using a Hash?

**Comment by jerome-diver** [comment]
@lukesarnacki, i'm thinking that all what we are define as "bug" or as "misleading documentation for people who..." can have terribly agnostic interpretations.
For example, in a simple application with no gem installed other than default official rails-5.2 install at create time, there is no "bug". 
But if you use some other gems, it may have a "bug" (not necessary from rails itself... or maybe because rails use something not to much usable by different ways... actually, we don't know why sometime in some situation(s) it doesn't want to works as expected). 
By the time, some people, instead of try to fix things (if they can -- happy us they to have knowledge) try to send the hot patato (a french expression used for talking about somthing boring no-one want t assume/do) as far as possible (not us, we are not like that... and we are actually unable to find the problem).

Also, for a documentation, as clear it can be, every body who know coding and read correct language country (what ever level is) should be able to understand what the doc is talking about (that is a good doc i mean). If not... it should never be the fault of people who are not the devs in charge for construct the framework.

By the fact now, documentation make me feel happy when i use a native new created rails application as long as this method works (and as long as rails doesn't update minor version who break things like it was a major version). There is nothing very complicate to understand and the explication seems to be clear.

@RigoTheDev for me, my little test case application i provide as public bitbucket git repo show that it works as the doc said on fresh install. My public little rails application who has more gem show that in fact, it doesn't works with some bigger config for a/any actually unknown reason(s).
My way to resolve a simple test condition on url part is actually to just get the full_path url and split it (with my application who embed a gem who as uncompatibility).

@sikachu and @lukesarnacki do you know someone who know rails in "high level" who can show power by apply devs high level technics to debug this kind of problem ?
I'm thinking all of us actually are unable to do that (and i see nothing relative to the doc), we need an help by someone who has knowledge for read deep debug log files or strace...

**Comment by jerome-diver** [comment]
@RigoTheDev and also, if  this current_page? method seems to be bugged also on your application, could you please show your Gemfile ? i show mine in the linked own application public repo.
It should have some of them (who are not the original ones) who make something that rails-5.2 doesn't like.
We are investigating as we can...
thank you (i suspect devise)

**Comment by RigoTheDev** [comment]
@jerome-diver I'd love to but I currently have no issues with `current_page?` as I'm only using it with path helpers. I'm just contributing & I came across your issue to try & help

**Comment by jerome-diver** [comment]
@RigoTheDev, yes sure, nevermind my friend, we will find one day or an other one, there is some other solutions by the time.
