### ISSUE TITLE
Generated by default config/initializers/assets.rb could cause the error in assets:precompile for production

### ISSUE THREAD

**Issue by ycherniavskyi** [rails/rails#33477]
### Steps to reproduce
```bash
$ rails new rails-stimulus-app --webpack=stimulus
$ cd rails-stimulus-app
$ RAILS_ENV=production rake assets:precompile
```

### Expected behavior
`RAILS_ENV=production rake assets:precompile` must compile assets without errors.

### Actual behavior
Rake aborted with exception `Uglifier::Error: Unexpected token: punc ({). To use ES6 syntax, harmony mode must be enabled with Uglifier.new(:harmony => true)`.

### System configuration
**Rails version**: 5.2.0

**Ruby version**: 2.5.1p57

### The reason
The source of this issue is `node_modules/@stimulus/core/dist/module/src/application.js` file which found by sprockets because of `Rails.application.config.assets.paths << Rails.root.join('node_modules')` line in `config/initializers/assets.rb` (which generated by default with [assets.rb.tt](https://github.com/rails/rails/blob/8e9e94391902b854662ba5eb06cc006cc4e85212/railties/lib/rails/generators/rails/app/templates/config/initializers/assets.rb.tt#L10)).

### The same issues
rails/webpacker#1285
stimulusjs/stimulus#153

**Comment by y-yagi** [comment]
Temporary solution: 

Please change `config/environments/production.rb` as follows. 

**before**

``` 
config.assets.js_compressor = :uglifier 
``` 

**after** 

```
config.assets.js_compressor = Uglifier.new(harmony: true) 
``` 

By the way, if #33079 is merged, `uglifier` will not be used, so this is no longer necessary.

**Comment by ycherniavskyi** [comment]
@y-yagi yes I saw such workaround for this issue.
But the reason of this issue is not in incorrect `js_compressor` options, it is in incorrect/unnecessary processing of `node_modules/@stimulus/core/dist/module/src/application.js` file (and all other files with `application.js` name in any other modules) because of `Rails.application.config.assets.paths << Rails.root.join('node_modules')`.

**Comment by ycherniavskyi** [comment]
@y-yagi just familiarize with #33079 and yes if sprockets do not process JavaScript then this issue will disappear 🙂.

**Comment by y-yagi** [comment]
@ycherniavskyi  Oh, I misunderstood. Thank you for pointing out.  This is an issue of compiling up to unnecessary files.

**Comment by y-yagi** [comment]
This is a issue with Sprockets' file loading, but seems to have already been fixed in Sprockets 4. 

```diff 
diff --git a/Gemfile b/Gemfile
index 625b742..25a81d0 100644
--- a/Gemfile
+++ b/Gemfile
@@ -62,3 +62,4 @@ end
 
 # Windows does not include zoneinfo files, so bundle the tzinfo-data gem
 gem 'tzinfo-data', platforms: [:mingw, :mswin, :x64_mingw, :jruby]
+gem 'sprockets', '4.0.0.beta8'
diff --git a/Gemfile.lock b/Gemfile.lock
index 7b974e2..eeba696 100644
--- a/Gemfile.lock
+++ b/Gemfile.lock
@@ -161,7 +161,7 @@ GEM
     spring-watcher-listen (2.0.1)
       listen (>= 2.7, < 4.0)
       spring (>= 1.2, < 3.0)
-    sprockets (3.7.2)
+    sprockets (4.0.0.beta8)
       concurrent-ruby (~> 1.0)
       rack (> 1, < 3)
     sprockets-rails (3.2.1)
@@ -211,6 +211,7 @@ DEPENDENCIES
   selenium-webdriver
   spring
   spring-watcher-listen (~> 2.0.0)
+  sprockets (= 4.0.0.beta8)
   sqlite3
   turbolinks (~> 5)
   tzinfo-data 
``` 

``` 
$ RAILS_ENV=production rake assets:precompile
yarn install v1.6.0
[1/4] Resolving packages...
success Already up-to-date.
Done in 0.73s.
I, [2018-07-31T08:27:23.281596 #19865]  INFO -- : Writing /home/yaginuma/program/rails/tmp/rails-stimulus-app/public/assets/manifest-d0ff5974b6aa52cf562bea5921840c032a860a91a3512f7fe8f768f6bbe005f6.js
I, [2018-07-31T08:27:23.281893 #19865]  INFO -- : Writing /home/yaginuma/program/rails/tmp/rails-stimulus-app/public/assets/manifest-d0ff5974b6aa52cf562bea5921840c032a860a91a3512f7fe8f768f6bbe005f6.js.gz
I, [2018-07-31T08:27:23.282129 #19865]  INFO -- : Writing /home/yaginuma/program/rails/tmp/rails-stimulus-app/public/assets/application-bff01c83b21205ab7ba0c04cd9077aee2348f52f179b8b49b46dfd8451152f2c.js
I, [2018-07-31T08:27:23.282308 #19865]  INFO -- : Writing /home/yaginuma/program/rails/tmp/rails-stimulus-app/public/assets/application-bff01c83b21205ab7ba0c04cd9077aee2348f52f179b8b49b46dfd8451152f2c.js.gz
I, [2018-07-31T08:27:23.282498 #19865]  INFO -- : Writing /home/yaginuma/program/rails/tmp/rails-stimulus-app/public/assets/cable-b97f556825620657b62a8a498a15854358d07834783276b6622dffab1a85361c.js
I, [2018-07-31T08:27:23.282835 #19865]  INFO -- : Writing /home/yaginuma/program/rails/tmp/rails-stimulus-app/public/assets/cable-b97f556825620657b62a8a498a15854358d07834783276b6622dffab1a85361c.js.gz
I, [2018-07-31T08:27:23.283081 #19865]  INFO -- : Writing /home/yaginuma/program/rails/tmp/rails-stimulus-app/public/assets/application-5717e7c840171019a4eeab5b79a7f894a4986eaff93d04ec5b12c9a189f594bf.css
I, [2018-07-31T08:27:23.283388 #19865]  INFO -- : Writing /home/yaginuma/program/rails/tmp/rails-stimulus-app/public/assets/application-5717e7c840171019a4eeab5b79a7f894a4986eaff93d04ec5b12c9a189f594bf.css.gz
Webpacker is installed 🎉 🍰
Using /home/yaginuma/program/rails/tmp/rails-stimulus-app/config/webpacker.yml file for setting up webpack paths 
```

I do not know how this can be backported to version 3, but in any case, this seems to be an issue of Sprockets. 
@ycherniavskyi  Can you create an issue to https://github.com/rails/sprockets/issues? Thanks.

**Comment by y-yagi** [comment]
Thanks for creating an issue.  Let's track it.

**Comment by netmanbworker** [comment]
Hello all, I am currently having the frustrating issue with running -
bundle exec rake assets:precompile RAILS_ENV=production 
......and the compile stops with the error - 
rake aborted! Uglifier::Error: Unexpected token: eof (undefined)

After reading numerous forums, and trying different workarounds and fixes...I have upgraded 

gem uglifier from 4.1.17 to 4.1.18
gem sprockets from 3.7.2 to 4.0.0.beta8

modified my app/config/environments/production.rb statement about uglifer from

 config.assets.js_compressor = :uglifier
-to- 
config.assets.js_compressor = Uglifier.new(harmony: true)

Upgrading the sprockets versions required me to create (actually I copied) my assets.rb file from /app/config/initializers/assets.rb  -to - pp/assets/config/manifest.js

and still am getting the rake aborted above.

Does anybody have any suggestions?  Kindly appreciated.

**Comment by ycherniavskyi** [comment]
@netmanbworker, I'm not sure that your error has any relation to the current issue.
This issue was about processing js files from the odd location. But your error seems is about some encoding problem. In any case, there is not enough context to reproduce your situation - it is better to create a separate issue with detailed reproduce instruction.

**Comment by dawidlenkiewicz** [comment]
Does anyone still have the issue after upgrading to sprockets 4?

```
yarn install v1.5.1
[1/4] 🔍  Resolving packages...
success Already up-to-date.
✨  Done in 0.85s.
** Execute assets:precompile
rake aborted!
Uglifier::Error: Unexpected token: keyword (const). To use ES6 syntax, harmony mode must be enabled with Uglifier.new(:harmony => true).
/Users/dawidlenkiewicz/.rvm/gems/ruby-2.5.0@luna/gems/uglifier-4.1.19/lib/uglifier.rb:234:in `parse_result'
/Users/dawidlenkiewicz/.rvm/gems/ruby-2.5.0@luna/gems/uglifier-4.1.19/lib/uglifier.rb:216:in `run_uglifyjs'
/Users/dawidlenkiewicz/.rvm/gems/ruby-2.5.0@luna/gems/uglifier-4.1.19/lib/uglifier.rb:178:in `compile_with_map'
/Users/dawidlenkiewicz/.rvm/gems/ruby-2.5.0@luna/gems/sprockets-4.0.0.beta8/lib/sprockets/uglifier_compressor.rb:58:in `call'
/Users/dawidlenkiewicz/.rvm/gems/ruby-2.5.0@luna/gems/sprockets-4.0.0.beta8/lib/sprockets/uglifier_compressor.rb:30:in `call'
/Users/dawidlenkiewicz/.rvm/gems/ruby-2.5.0@luna/gems/sprockets-4.0.0.beta8/lib/sprockets/processor_utils.rb:84:in `call_processor'
/Users/dawidlenkiewicz/.rvm/gems/ruby-2.5.0@luna/gems/sprockets-4.0.0.beta8/lib/sprockets/processor_utils.rb:66:in `block in call_processors'
/Users/dawidlenkiewicz/.rvm/gems/ruby-2.5.0@luna/gems/sprockets-4.0.0.beta8/lib/sprockets/processor_utils.rb:65:in `reverse_each'
/Users/dawidlenkiewicz/.rvm/gems/ruby-2.5.0@luna/gems/sprockets-4.0.0.beta8/lib/sprockets/processor_utils.rb:65:in `call_processors'
```

**Comment by akostadinov** [comment]
I see same issue with Rails 5.1.7
