### ISSUE TITLE
Outdated info on find_each in the guide

### ISSUE THREAD

**Issue by nicktime** [rails/rails#33473]
https://edgeguides.rubyonrails.org/active_record_querying.html#options-for-find-each
states
"By default, records are fetched in ascending order of the primary key, which must be an integer."
Looks like it's outdated. E.g. https://github.com/rails/rails/issues/5786#issuecomment-260718650

**Comment by sikachu** [comment]
I see. Would you like to submit a PR to fix this documentation?

**Comment by nicktime** [comment]
Sorry, I'm not good with wording:)

**Comment by adityakapoor-homebell** [comment]
@sikachu here you go ^^

**Comment by aditya-kapoor** [comment]
@sikachu here you go

**Comment by sikachu** [comment]
Looks like @kaspth already taken care of this. Thank you for your PR @aditya-kapoor and @nicktime for the report!
