### ISSUE TITLE
Rails 4: ActiveRecord in_batches does not account for primary key correctly

### ISSUE THREAD

**Issue by NoahMCollins** [rails/rails#33476]
### Steps to reproduce

I have a class like the one below:

```
class Item < OtherItem
  def self.primary_key
    'other_id'
  end

  def self.init_with(*args)
    OtherItem.allocate.init_with(*args)
  end
end
```
I use this by doing `Item.find_each`.

### Expected behavior
It should generate SQL like the following given that the last record previous pulled in was item1.

```SQL
SELECT other_items.*
FROM other_items
WHERE other_id > item1.other_id
ORDER BY other_items.other_id
OFFSET batch_size * batch_number
LIMIT batch_size
```

### Actual behavior
It generates the following SQL:

```SQL
SELECT other_items.*
FROM other_items
WHERE other_id > item1.id
ORDER BY other_items.other_id
OFFSET batch_size * batch_number
LIMIT batch_size
```
This doesn't make sense as I am now comparing other_id with id in the WHERE clause.

### System configuration
**Rails version**: 4.2.10

**Ruby version**: 2.4.2

**Comment by rafaelfranca** [comment]
Does it work in Rails 5? Rails 4 is not maintained anymore

**Comment by NoahMCollins** [comment]
@rafaelfranca I don't currently have a codebase in Rails 5 to test this and it is not an option to migrate to it at this time.  If it is not maintained, then I may just fork the latest Rails 4 version and fix that.  Thanks.

**Comment by NoahMCollins** [comment]
@rafaelfranca Based on looking at the latest code, it would still have this problem.  If you take a look at line 225 in the [relations.rb file](https://github.com/rails/rails/blob/6db5b6dc4322d043db4d6eff2cc49de86baf1595/activerecord/lib/active_record/relation/batches.rb), you can see that there is this code: `ids = records.map(&:id)`.

It should be `ids = records.map { |r| r[primary_key] }` instead.

**Comment by rafaelfranca** [comment]
That sql is also strange. What you are calling `item1.other_id` is usually a number corresponding the beginning of the batch.

Could you create a reproduction script with this template https://github.com/rails/rails/blob/4-2-stable/guides/bug_report_templates/active_record_gem.rb?

**Comment by NoahMCollins** [comment]
Here is the minimal code to replicate the issue.  I was able to replicate it using the ActiveRecord 5.2.0 release.

```ruby
require 'active_record'
require 'minitest/autorun'
require 'logger'

# Ensure backward compatibility with Minitest 4
Minitest::Test = MiniTest::Unit::TestCase unless defined?(Minitest::Test)

# This connection will do for database-independent bug reports.
ActiveRecord::Base.establish_connection(adapter: 'sqlite3', database: ':memory:')
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :lists

  create_table :items do |t|
    t.integer :list_id
  end
end

class List < ActiveRecord::Base
  has_many :items
end

class Item < ActiveRecord::Base
  belongs_to :list
end

class ListItem < Item
  def self.primary_key
    'list_id'
  end

  def init_with(*args)
    Item.allocate.init_with(*args)
  end
end

class BugTest < Minitest::Test
  def test_find_each
    20.times {
      list = List.create!
      3.times { list.items.create! }
    }

    # Illustrating that the query works
    processed_count = 0
    ListItem.group(:list_id).each { processed_count+=1 }

    assert_equal 20, processed_count

    # Showing that the find_each does not
    processed_count = 0
    ListItem.group(:list_id).find_each(batch_size: 5) { processed_count+=1 }

    assert_equal 20, processed_count
  end
end
```

The reason why this is a defect is that if you call records.last.id you are calling the primary_key function on the class of the records.  In this case, there is a wrapper class, so the primary_key function would return something different for all the places that call primary_key directly.  This causes a discrepancy in what field is being looked at.

**Comment by rafaelfranca** [comment]
I see. Yes, that is the expected behavior. The primary key of the class of the instance have priority over the primary key of the class where the batch was called. This is implemented this way so instances of models using STI use the right class to determine what is the primary key.

**Comment by NoahMCollins** [comment]
@rafaelfranca Thanks for taking the time to review the issue.  One more item to consider.  If this is expected behavior, then there are inconsistencies in the rest of the function that lead to unexpected behavior.  Here are some examples of the use of `primary_key` from the calling class rather than the collection.

https://github.com/rails/rails/blob/6db5b6dc4322d043db4d6eff2cc49de86baf1595/activerecord/lib/active_record/relation/batches.rb#L229
https://github.com/rails/rails/blob/6db5b6dc4322d043db4d6eff2cc49de86baf1595/activerecord/lib/active_record/relation/batches.rb#L255
https://github.com/rails/rails/blob/6db5b6dc4322d043db4d6eff2cc49de86baf1595/activerecord/lib/active_record/relation/batches.rb#L269
https://github.com/rails/rails/blob/6db5b6dc4322d043db4d6eff2cc49de86baf1595/activerecord/lib/active_record/relation/batches.rb#L273
https://github.com/rails/rails/blob/6db5b6dc4322d043db4d6eff2cc49de86baf1595/activerecord/lib/active_record/relation/batches.rb#L277

If you use the collection's `id` field, then you are possibly using a different field than the field that you sort, limit, and query on.
https://github.com/rails/rails/blob/6db5b6dc4322d043db4d6eff2cc49de86baf1595/activerecord/lib/active_record/relation/batches.rb#L225
