### ISSUE TITLE
Use https://rubyonrails.org/ for the website of this repository instead of http://rubyonrails.org/

### ISSUE THREAD

**Issue by da-edra** [rails/rails#33480]
What I mean with this is that the website description should default to `https` instead of `http` for security purposes.

I can't change it myself since I'm not authorized for it.

![screenshot_2018-07-31_00-08-00](https://user-images.githubusercontent.com/10160626/43438912-367d2c3c-9456-11e8-8ab0-193182cd263f.png)

**Comment by matthewd** [comment]
✅  Thanks!
