### ISSUE TITLE
where.not() with polymorphic association condition is too strict

### ISSUE THREAD

**Issue by njakobsen** [rails/rails#33493]
### Steps to reproduce

Given a model with a polymorphic association...

```ruby
class Vehicle
  belongs_to :owner, polymorphic: true
end
```
...performing a `where.not` query creates a condition that is unnecessarily strict.

```ruby
Vehicle.where.not(owner: Person.find(1)).to_sql
```

### Expected behavior
It is sufficient for _either_ `owner_type` _or_ `owner_id` not to match.

```sql
SELECT `vehicles`.* FROM `vehicles` WHERE (`vehicles`.`owner_type` != 'Person') OR (`vehicles`.`owner_id` != 1)
```
or applying de Morgan's theorem
```sql
SELECT `vehicles`.* FROM `vehicles` WHERE NOT (`vehicles`.`owner_type` = 'Person' AND `vehicles`.`owner_id` = 1)
```

### Actual behavior
Requiring both to match can cause valid results to be excluded if there are other records that match either the type or id of the undesired record.

```sql
SELECT `vehicles`.* FROM `vehicles` WHERE (`vehicles`.`owner_type` != 'Person') AND (`vehicles`.`owner_id` != 1)
```

### System configuration
**Rails version**: 5.1

**Ruby version**: 2.3.0p0

**Comment by kamipo** [comment]
This has been fixed in 5.2. e9ba12f746b3d149bba252df84957a9c26ad170b
