### ISSUE TITLE
Railsinstaller.org is down so cannot install Rails on Windows

### ISSUE THREAD

**Issue by MSCAU** [rails/rails#33496]
### Steps to reproduce
Go to https://guides.rubyonrails.org/getting_started.html. Under heading 3.1, in the sentence:

> Windows users can use **Rails Installer**

Click on the **Rails Installer** link. 

### Expected behavior
I'd expect this website would be available.

### Actual behavior
Chrome says:

"This site can’t be reached railsinstaller.org took too long to respond."

### System configuration
n/a

**Comment by saiqulhaq** [comment]
you should report it [here](https://github.com/railsinstaller) [https://github.com/railsinstaller](https://github.com/railsinstaller)

**Comment by MSCAU** [comment]
Thanks, @saiqulhaq - not fixed since Jan 2017! https://github.com/railsinstaller/website/issues/59

**Comment by emmanuelajaero** [comment]
https://s3.amazonaws.com/railsinstaller/Windows/railsinstaller-3.4.0.exe

you can download it from the link

**Comment by Ruchi0502** [comment]
Thanks much @emmanuelajaero this link actually solved my problem.
