### ISSUE TITLE
ActiveJob::SerializationError during ActiveStorage attach

### ISSUE THREAD

**Issue by regedarek** [rails/rails#33502]
### Steps to reproduce
```
  class Photo < ApplicationRecord
    has_one_attached :file
  end
```
```
  module Services
    class AddPhoto
      include Dry::Monads::Result::Mixin

      # @param params [hash], schema Api::V1::PhotoSchema
      def call(params:)
        base_64_string = params[:photo][:base_64_encoded_file]
        decoded_data = Base64.decode64(base_64_string)

        filename = "temporary_file.jpg"
        tmp_file = Tempfile.new(filename)
        tmp_file.binmode
        tmp_file.write decoded_data
        tmp_file.rewind()

        photo = Photo.new
        photo.file.attach(io: tmp_file, filename: filename)
        photo.save
        tmp_file.unlink

        Success(message: 'New photo was added', photo: photo)
      end
    end
  end
```

### Expected behavior
File has been uploaded, action returned success.

### Actual behavior
I constantly receiving an error `Unsupported argument type: ActiveStorage::Blob`.
![image](https://user-images.githubusercontent.com/656326/43517588-8b6f2f4a-9589-11e8-8233-a70ceb1dcf68.png)

In storage directory I see this image file and also in database all records has been created properly.
![image](https://user-images.githubusercontent.com/656326/43517802-38d202a2-958a-11e8-899c-c114f30536a8.png)

Also when I change order of `photo.save` and `photo.file.attach` last one triggers this error.

### System configuration
**Rails version**: 5.2.0

**Ruby version**: 2.5.1

**Comment by georgeclaghorn** [comment]
Can you share the backtrace for that error?

**Comment by georgeclaghorn** [comment]
The full trace would be helpful. (Click “Full Trace” above the application trace.)

Can you share the source for the Photo model as well?

**Comment by regedarek** [comment]
This are logs from server.
![image](https://user-images.githubusercontent.com/656326/43519873-53a34e86-9591-11e8-9ac7-61cdf30d4b7f.png)

If you are asking for Photo model code its on top.

**Comment by regedarek** [comment]
I just tried to do that from rails console and the same error. So I would exclude controller, service layer.

**Comment by georgeclaghorn** [comment]
I’d still like to see the full backtrace. Click “Full Trace” above the application trace on the error page or disable the backtrace cleaner in an initializer to send the full trace to the logs:

```ruby
Rails.backtrace_cleaner.remove_silencers!
```

**Comment by regedarek** [comment]
Ok, we found a solution. We had to add in application.rb `active_job/railtie`
First we thought why we even need activejob in activestorage, looks like it updates metadata.

Probably would be nice to have this information somewhere in activestorage readme ;).
```
# frozen_string_literal: true

require_relative 'boot'
require 'rails'
require 'active_job'

%w[
  active_job/railtie
  active_record/railtie
  active_storage/engine
  action_controller/railtie
  action_view/railtie
].each do |railtie|
  require railtie
end
```
Thanks for help.

**Comment by harmnot** [comment]
I have this issue as well , I am using latest Rail and Ruby with Delayed Job 
```
ActiveJob::SerializationError (Unsupported argument type: Tempfile):
```

I am suing Active Storage:
```
  def perform(model, new_image, file)
    model.meta_gallery.attach(
          io: new_image, 
          filename: file.original_filename, 
          content_type:   file.content_type
     )
  end
```
