### ISSUE TITLE
Rails Mailers: Setting template_path to file outside of /apps/views directory

### ISSUE THREAD

**Issue by ZASMan** [rails/rails#33504]
I'm working on a rails application with a rather unorthodox file structure.

I'm working on a mailer located in `apps/mailers/my_mailer.rb`, as usual. However, the views for it are located in an unorthodox location. They're not located in `apps/views/`, but in `my_custom_folder/apps/views/mailer_name/mailer_html_file.html.erb`.

I've tried setting the location as so:
```
  # in apps/mailers/my_mailer.rb

  def custom_email
    to = example@example.com
    full_template_path = Rails.root.to_s + "my_custom_folder/apps/views/mailer_name/"
    mail(
      to: to, 
      subject: subject,
      template_path: full_template_path,
      template_name: "custom_email"
    ) do |format| 
      format.html
    end
  end

```

However, it seems to still default to looking in the traditional `app/views/mailer_name` folder.See the text below. I get the following error:
```
ActionView::MissingTemplate: Missing template my_mailer/custom_email, my_mailer/custom_email with {:locale=>[:en], :formats=>[:html], :variants=>[], :handlers=>[:raw, :erb, :html, :builder, :ruby]}. Searched in:
  *** "/home/my_user_name/my_application_name/app/views"
  * "/home/my_user_name/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/devise-4.2.0/app/views"**
```

Anyone have any workarounds?

**Comment by rafaelfranca** [comment]
Please use the mailing list or StackOverflow for questions/help, where a wider community will be able to help you. We reserve the issues tracker for issues only.
