### ISSUE TITLE
ActiveRecord fails to correctly merge scopes containing IN constraints on the same column

### ISSUE THREAD

**Issue by chrisandreae** [rails/rails#33501]
### Steps to reproduce

Merge two ActiveRecord scopes on the same model, each of which expresses a different `IN` constraint on the same column. For example:

```ruby
User.where(id: [2, 3])
  .merge(User.where(id: [1, 2]))
```

This occurs whether the constraint is expressed as an immediate array (e.g. `.where(col: [...])` or `.where(Model.arel_table[:col].in([...]))`), or (more importantly) as a subquery (e.g. `.where(col: OtherModel.where(...).select(:col))`)

Executable test case: 
https://gist.github.com/chrisandreae/be5ad28f14b1f2a0e0c6e0098230f4bc

### Expected behavior

Both `IN` constraints should be expressed in the final query, for example:
```sql
SELECT "users".* FROM "users" WHERE "users"."id" IN (2, 3) AND "users"."id" IN (1, 2)
```

### Actual behavior

Only the merged constraint is expressed in the final query, for example:
```sql
SELECT "users".* FROM "users" WHERE "users"."id" IN (1, 2)
```

### System configuration
**Rails version**: 5.2.0

**Ruby version**: ruby 2.5.1p57

[Edited 20190122: Still fails in rails 6.0.0.beta1 (at master@3f0c7c5)]

**Comment by dominikknafelj** [comment]
Yes, I can reproduce in in a Rails 3.2 and Oracle db environment. Couldn't help but hard code the SQL statement.

**Comment by jychen7** [comment]
I think this is on purpose, not a bug, see this test case

https://github.com/rails/rails/blob/a2b9768792a81e474a8b70d3950cd14ffd491207/activerecord/test/cases/relation/merging_test.rb#L29-L34

```
(byebug) print devs.to_sql
SELECT "developers"."id", "developers"."name", "developers"."salary", "developers"."firm_id", "developers"."mentor_id", "developers"."created_at", "developers"."updated_at", "developers"."created_on", "developers"."updated_on" FROM "developers" WHERE "developers"."salary" = 9000
```

It is similar for `IN` as well. you can verify by adding test `Developer.arel_table[:salary].in([80000])`

**Comment by chrisandreae** [comment]
@jychen7 that is intended behavior only for equality conditions. Because two different equalities on the same column can not both match at the same time (i.e. the developer's salary can't be both 80000 and 9000), the intent appears to be for the later scope to override the former. (Although it would be even more correct to infer that the merged scope can never match any rows, and return an empty scope.)

However, this isn't true for comparisons: the developer's salary _can_ be both `> 3000` and `< 6000`, and ActiveRecord correctly merges scopes with these constraints. Likewise, the developer's salary can be in both the sets `[3000, 4000]` and `[4000, 5000]` - but ActiveRecord fails to correctly merge in this case.

**Comment by jychen7** [comment]
> Although it would be even more correct to infer that the merged scope can never match any rows, and return an empty scope.

I agree

https://api.rubyonrails.org/classes/ActiveRecord/SpawnMethods.html#method-i-merge

> Merges in the conditions from other, if other is an ActiveRecord::Relation. Returns an array representing the intersection of the resulting records with other, if other is an array.

The definition is not clear about how to handle the merge for `=`, `IN` conditions

**Comment by chrisandreae** [comment]
The attached executable test case can still be reproduced on master:

```$ ruby active_record_master.rb
Fetching https://github.com/rails/rails.git
Fetching gem metadata from https://rubygems.org/........
Fetching gem metadata from https://rubygems.org/..........
Fetching gem metadata from https://rubygems.org/..........
Resolving dependencies...
Using rake 12.3.1
Using concurrent-ruby 1.1.3
Using i18n 1.1.1
Using minitest 5.11.3
Using thread_safe 0.3.6
Using tzinfo 1.2.5
Using activesupport 6.0.0.alpha from https://github.com/rails/rails.git (at master@b8b93f5)
Using builder 3.2.3
Using erubi 1.7.1
Using mini_portile2 2.3.0
Using nokogiri 1.8.5
Using rails-dom-testing 2.0.3
Using crass 1.0.4
Using loofah 2.2.3
Using rails-html-sanitizer 1.0.4
Using actionview 6.0.0.alpha from https://github.com/rails/rails.git (at master@b8b93f5)
Using rack 2.0.6
Using rack-test 1.1.0
Using actionpack 6.0.0.alpha from https://github.com/rails/rails.git (at master@b8b93f5)
Using nio4r 2.3.1
Using websocket-extensions 0.1.3
Using websocket-driver 0.7.0
Using actioncable 6.0.0.alpha from https://github.com/rails/rails.git (at master@b8b93f5)
Using globalid 0.4.1
Using activejob 6.0.0.alpha from https://github.com/rails/rails.git (at master@b8b93f5)
Using mini_mime 1.0.1
Using mail 2.7.1
Using actionmailer 6.0.0.alpha from https://github.com/rails/rails.git (at master@b8b93f5)
Using activemodel 6.0.0.alpha from https://github.com/rails/rails.git (at master@b8b93f5)
Using activerecord 6.0.0.alpha from https://github.com/rails/rails.git (at master@b8b93f5)
Using mimemagic 0.3.2
Using marcel 0.3.3
Using activestorage 6.0.0.alpha from https://github.com/rails/rails.git (at master@b8b93f5)
Using bundler 1.16.4
Using method_source 0.9.1
Using thor 0.20.0
Using railties 6.0.0.alpha from https://github.com/rails/rails.git (at master@b8b93f5)
Using sprockets 3.7.2
Using sprockets-rails 3.2.1
Using rails 6.0.0.alpha from https://github.com/rails/rails.git (at master@b8b93f5)
Using sqlite3 1.3.13
-- create_table(:posts, {:force=>true})
   -> 0.0045s
-- create_table(:comments, {:force=>true})
   -> 0.0003s
Run options: --seed 59417

# Running:

.F

Failure:
BugTest#test_merging_in_constraints [active_record_master.rb:75]:
Expected: 1
  Actual: 2


rails test active_record_master.rb:69

F

Failure:
BugTest#test_merging_arel_in_constraints [active_record_master.rb:86]:
Expected: 1
  Actual: 2


rails test active_record_master.rb:79

F

Failure:
BugTest#test_merging_subquery_in_constraints [active_record_master.rb:97]:
Expected: 1
  Actual: 2


rails test active_record_master.rb:90



Finished in 0.018715s, 213.7323 runs/s, 801.4961 assertions/s.
4 runs, 15 assertions, 3 failures, 0 errors, 0 skips
```

**Comment by chrisandreae** [comment]
The attached executable test case can still be reproduced on Rails master at 02b5b8c.

**Comment by chrisandreae** [comment]
The test case can still be reproduced on Rails 6.1.0.alpha on master at https://github.com/rails/rails/commit/31105c81cc82ae829c382a4eee2c5aa362882dea.

**Comment by rafaelfranca** [comment]
Thanks for confirming. This is the expected behavior of how `merge` is implemented. It behaves like `Hash#merge` where, when in conflict, the argument for `merge` takes precedence.

**Comment by chrisandreae** [comment]
Unlike with equality constraints, `IN` set membership constraints on the same column are not necessarily in conflict: there are valid semantics for combining the constraints, and moreover such constraints are presently correctly combined by Rails.. provided that scope `merge` is not used.

In the case of equality constraints, `Developer.where(salary: 50000)` and `Developer.where(salary: 60000)` are inherently in conflict: it's never possible for the salary of any record to be both 50000 and 60000. To merge these scopes, the merge operation makes a decision between the two of these. It's valid and Ruby-like for it to choose the `Hash`-like overriding behaviour.

However, there is no such conflict with constraints on set membership or inequality relations. In both of those cases, there is a straightforward combination of the constraints, but at present Rails' scope `merge` only combines the latter.

* in the case of inequalities, constraints like `Developer.where(Developer.arel_table[:salary].gt(30000))` and `Developer.where(Developer.arel_table[:salary].lt(60000))` are compatible. They are currently correctly combined by `merge` simply by keeping both conditions as `WHERE` clauses and emitting `WHERE salary > 30000 AND salary < 60000`.

* In the case of set membership, constraints like`Developer.where(salary: [20000, 40000])` and `Developer.where(salary: [40000, 50000])`, are also compatible. They could likewise be merged by keeping both conditions: `WHERE salary IN (20000, 40000) AND salary IN (40000, 50000)`.

In fact, in contrast to the behaviour of `merge`, when they are presented as separate `where` clauses to a single scope, set membership constraints are merged as expected:

```
> Developer.where(salary: [30000, 40000]).where(salary: [40000, 50000])
  Developer Load (0.5ms)  SELECT "developers".* FROM "developers" WHERE "developers"."salary" IN ($1, $2) AND "developers"."salary" IN ($3, $4) LIMIT $5  [["salary", 30000], ["salary", 40000], ["salary", 40000], ["salary", 50000], ["LIMIT", 11]]
=> #<ActiveRecord::Relation [#<Developer id: 2, salary: 40000>]>
```

I believe that it's surprising behaviour to find that merging scopes with complementary constraints on a column silently drops one of the constraints, but _especially_ surprising that this only happens on a scope merge operation. It seems to me to be quite a trap, where a developer aiming to refactor a query into merged named parts could end up completely changing the meaning.

**Comment by faucct** [comment]
But the expected behavior of merge conflicts with what its docs say about arrays intersection. It would be great if there would be `Relation#and` really behaving like an intersection.

**Comment by letiesperon** [comment]
Agree. The following should be possible and handled by active record. :

```
User.where(id: [2, 3]).merge(User.where(id: [1, 2]))
```

In my case I spent hours trying to understand how a merge command was adding records to the previous collection other than filtering it:

```
(byebug) ::Reporting::Entry.where(reporting_report_id: []).count
0
(byebug) ::Reporting::Entry.where(reporting_report_id: []).merge(report.entries).count
2
```

**Comment by sudoaza** [comment]
Either this or the documentation should be fixed. What would be the correct way to merge two inclusion scopes on the same column?

**Comment by kamipo** [comment]
Now we can use `Relation#and` in Rails 6.1 (#39558).
