### ISSUE TITLE
ActiveRecord offset remembers last offset and adds up

### ISSUE THREAD

**Issue by array42** [rails/rails#33510]
### Steps to reproduce

Query some data in a console:
```
irb(main):057:0> SomeModel.offset(100_000 + 10).limit(10).pluck(:id)                                                      
=> [601662, 601665, 601668, 601671, 601674, 601677, 601680, 601683, 601686, 601689]
irb(main):058:0> SomeModel.offset(100_000 + 10).limit(10).pluck(:id)                    
=> [701164, 701165, 701166, 701167, 701168, 701169, 701170, 701171, 701172, 701173]
irb(main):059:0> SomeModel.offset(100_000 + 10).limit(10).pluck(:id)                              
=> [800863, 800864, 800865, 800866, 800867, 800868, 800869, 800870, 800871, 800872]
irb(main):060:0> SomeModel.offset(100_000 + 10).limit(10).pluck(:id)                              
=> [900573, 900574, 900575, 900576, 900577, 900578, 900579, 900580, 900581, 900582]

irb(main):061:0> SomeModel.offset(0).limit(10).pluck(:id)                                                             
=> [900250, 900251, 900252, 900253, 900254, 900255, 900256, 900257, 900258, 900259]
irb(main):062:0> SomeModel.offset(0).limit(10).pluck(:id)                                                             
=> [900250, 900251, 900252, 900253, 900254, 900255, 900256, 900257, 900258, 900259]
```

### Expected behavior
I expected the offset to be exact, not some internal state.

### Actual behavior
Offset adds up and the offset persists. I can't find that to be documented that way.

### System configuration
**Rails version**: 5.1.6

**Ruby version**: 2.5.1

**Postgres version**: 10.4

**Comment by jason0415** [comment]
<iframe src="https://giphy.com/embed/11K86exuszh33i" width="480" height="360" frameBorder="0" class="giphy-embed" allowFullScreen></iframe><p><a href="https://giphy.com/gifs/larry-shipper-11K86exuszh33i">via GIPHY</a></p>

**Comment by jason0415** [comment]
![mlb-smile-X6kScsVKJO075A7EFm](https://media2.giphy.com/media/X6kScsVKJO075A7EFm/giphy.gif)

**Comment by georgeclaghorn** [comment]
From [the manual page on `SELECT`](https://www.postgresql.org/docs/current/static/sql-select.html):

> If ORDER BY is not given, the rows are returned in whatever order the system finds fastest to produce.
>
> …
>
> When using LIMIT, it is a good idea to use an ORDER BY clause that constrains the result rows into a unique order. Otherwise you will get an unpredictable subset of the query's rows — you might be asking for the tenth through twentieth rows, but tenth through twentieth in what ordering? You don't know what ordering unless you specify ORDER BY.

Do you receive predictable results if you add an order?

**Comment by jychen7** [comment]
I didn't meet this issue in MySQL

**Comment by array42** [comment]
Actually the system is still up and the query still returns values in the range I showed in the example. I kind of suspect spring to be the reason it still has that same range as it had last time, but the problem itself is somewhere in the offset itself.

Also adding .order(:some_attribute) does only return scattered 'unordered' ids but not a new offset starting from 0. All examples online show offset and limit as one way to page through the dataset.

There is load on the database. I don't think postgres would return me the same weird range and also as you can see, the offset does indeed increase around 100_000 when I add it. When I omit it, the result stays at the fixed offset. Order does not change things.

offset(0) returns the same ids as last time. Order only changes the ids but also returns the same ids. When I omit order its back at the [900250, 900251, 900252, 900253, 900254, 900255, 900256, 900257, 900258, 900259].

Spring preloader probably keeps the weirdness alive..

**Comment by al2o3cr** [comment]
@array42 Can you post the SQL these queries are generating? A quick way to get it is to run `ActiveRecord::Base.logger = Logger.new(STDOUT)` before the commands above to get logging to your terminal.

**Comment by fatihorhan** [comment]
This issue seems to be abandoned by the opener. Using only LIMIT clause and expecting a predetermined order is unreasonable anyway, database engines cannot read minds.

I think it is safe to close this non-issue.
