### ISSUE TITLE
Q about your release strategy (no bug)

### ISSUE THREAD

**Issue by x-itec** [rails/rails#33517]
Do you have rules before releasing a new version of ruby/rails, for example "no more than x bugs" or "no critical bugs" or so? Can I read them somewhere? If you do not have such rules, do you need some help setting up this quality assurance stuff - I could help with that if you like. I think it's more important to publish something stable instead of something fast.

**Comment by kaspth** [comment]
We publish release candidates before any release to catch any regressions as soon as possible. E.g. for the coming 5.2.1, we've just released rc1: https://weblog.rubyonrails.org/2018/7/30/Rails-5-2-1-rc1-has-been-released/

Help is always appreciated, but I don't think we need any for the process setup here. Thanks!

**Comment by x-itec** [comment]
Where can i see details about your regression tests?

**Comment by matthewd** [comment]
You can see our test matrix in Travis CI here: https://travis-ci.org/rails/rails

You'll notice that there are very few tests that are run on JRuby, and even those are marked as "allowed failures". Latest Rails is not currently expected to run on JRuby, and while improving that would be nice, it's not a release blocker. **The JRuby team** are doing great work, within their available time, to bridge that gap -- and once it works, we'll prioritise keeping it working -- but until then, _the problem is that JRuby isn't acting enough like Real Ruby_; we can't fix that.

If you want to see Rails running on JRuby, I'd suggest speaking to the JRuby and/or activerecord-jdbc-adapter teams: they'll have a much better idea of which Rails version they have the best support for at the moment.

**Comment by x-itec** [comment]
a) Why do you not try to code as compatible as possible to jruby? 
b) Do you have any release strategies for QA I can read? As mentioned before , something like "no release if x bugs left" or "no release if critical bugs available" or so?
c) I work in my free time on similar things, too (others) and I know that no one can expect anything, I have only positive impulses and good ideas, a mental attitude to bring things positive forward.
d) Quality for a framework is more important than the next release with n bugs left. The best mix for that can be calculated with a nash equilibrium formula.

**Comment by x-itec** [comment]
I do not understand why you not try to be compatible to the java world, your rails apps could work on apache tomcat or many government contractors allow only java bytecode.
