### ISSUE TITLE
Jruby 9.2 Rails 5.2 incompatibility illegal access

### ISSUE THREAD

**Issue by x-itec** [rails/rails#33516]
### Steps to reproduce

C:\jruby-9.2.0.0\bin\rails _5.2.0_ new CENSORED --skip --database=sqlite3

WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.jruby.runtime.encoding.EncodingService
 to field java.io.Console.cs
WARNING: Please consider reporting this to the maintainers of org.jruby.runtime.
encoding.EncodingService
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflect
ive access operations
WARNING: All illegal access operations will be denied in a future release

###Tell us what should happen
For your QA: 
This should be solved if you release a new ruby/rails version. Its the first issue for you to check, more to come, but step by step. I cannot get anything running on win64 currently with jruby and ruby/rails,  more about that later. 

### How to repeat
Win 10, Jruby 9.2.x, just try it

**Comment by ahorek** [comment]
these are just warnings not errors (java 9, 10 + windows) and it should be fixed in jruby, see https://github.com/jruby/jruby/issues/5223 .

did you skip bootsnap?
```
C:\jruby-9.2.0.0\bin\rails 5.2.0 new CENSORED --skip --skip-bootsnap --database=sqlite3
```

I tested a new application on jruby 9.2.0 + rails 5.2.0 + windows 10 + java 10.0.1+10 and it works fine.

**Comment by x-itec** [comment]
Thanks for testing, I will try it out and let you know the results. Need some hours, out of office currently. Lets say someone is on jruby, the script should detect that and do --skip-bootsnap automagically if it does not work in general.

**Comment by ahorek** [comment]
yeah, it's already in rails 5.2.1, see https://github.com/rails/rails/commit/b10f371366a606310cab26648d798836e030bdc8

**Comment by y-yagi** [comment]
As ahorek already explained, this has already been fixed. This will not happen after Rails 5.2.1. Thanks.
