### ISSUE TITLE
Member route helpers suffix parent name rather than prefixing

### ISSUE THREAD

**Issue by spikeheap** [rails/rails#33518]
### Steps to reproduce

```
# frozen_string_literal: true

begin
  require "bundler/inline"
rescue LoadError => e
  $stderr.puts "Bundler version 1.10 or later is required. Please update your Bundler"
  raise e
end

gemfile(true) do
  source "https://rubygems.org"

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  gem "rails", github: "rails/rails"
end

require "action_controller/railtie"

class TestApp < Rails::Application
  config.root = __dir__
  secrets.secret_key_base = "secret_key_base"

  config.logger = Logger.new($stdout)
  Rails.logger  = config.logger

  routes.draw do
    resources :photos do
      member do
        get 'preview'
      end
    end
  end
end

require "minitest/autorun"
require "rack/test"

class BugTest < Minitest::Test
  include Rack::Test::Methods
  include Rails.application.routes.url_helpers

  def test_photo_preview_path_exists
   assert_equal '/photos/1/preview', photo_preview_path(id: 1)
  end

  def test_suffixed_path_does_not_exist
   refute_equal '/photos/1/preview', preview_photo_path(id: 1)
  end

  private
    def app
      Rails.application
    end
end
```

### Expected behavior
According to https://guides.rubyonrails.org/routing.html#adding-member-routes, adding the following to `routes.rb` will create the `photo_preview_url` and `photo_preview_path` helpers:

```
resources :photos do
  member do
    get 'preview'
  end
end
```

### Actual behavior
The following helpers are generated:

- `preview_photo_url`
- `preview_photo_path`

The containing resource name is a suffix of the member route, rather than a prefix. This is inconsistent with the docs and reads oddly for our use case.

### System configuration
**Rails version**: 5.2.0, also affects 6.0.0.alpha

**Ruby version**: Tested on 2.4.3 and 2.5.1p57

**Comment by sikachu** [comment]
I _think_ this is the case where the documentation is incorrect, and what needs to be fixed is the documentation, not the implementation.

The reason being that `member` is for adding a new action which acts on a single resource. An example of member action is ... `edit`.

The route helper path to `edit` a `user` is `edit_user_path`. Hence, a route helper path for `preview` a `user` would be `preview_user_path`.

Would you like to submit a documentation patch to fix this inconsistency?

Thank you very much for your report.

**Comment by spikeheap** [comment]
Sounds good to me, I'll submit a PR tomorrow 😀
