### ISSUE TITLE
SQLite schema changes lose foreign key references

### ISSUE THREAD

**Issue by jberkel** [rails/rails#33520]
### Steps to reproduce

Run a migration with schema change (anything using `alter_table`) on a SQLite database, e.g. renaming a column which has a foreign key reference set.

### Expected behavior
The column is renamed, the foreign key reference is kept.

### Actual behavior
The column is renamed, the foreign key reference is dropped. This happens on all schema changes which copy the table. The logic to recreate the foreign key in `create_table` seems to be missing.

```
$ sqlite3 test.db
sqlite> CREATE TABLE foo (id INTEGER PRIMARY KEY NOT NULL);
sqlite> CREATE TABLE bar (id INTEGER PRIMARY KEY NOT NULL, foo_id INTEGER NOT NULL REFERENCES foo (id));
sqlite> ^D
$  echo ".schema bar" | sqlite3 test.db
CREATE TABLE bar (id INTEGER PRIMARY KEY NOT NULL, foo_id INTEGER NOT NULL REFERENCES foo (id));

$ bundle exec irb
2.4.1 :001 > require 'active_record'
2.4.1 :002 > ActiveRecord::Base.logger = Logger.new(STDOUT)
2.4.1 :003 > ActiveRecord::Base.establish_connection(adapter:  'sqlite3', database: 'test.db')
2.4.1 :004 > ActiveRecord::Base.connection.rename_column('bar', 'foo_id', 'new_foo_id')
D, [2018-08-02T17:22:54.949390 #4638] DEBUG -- :    (3.4ms)  SELECT sqlite_version(*)
D, [2018-08-02T17:22:54.953112 #4638] DEBUG -- :    (0.1ms)  begin transaction
D, [2018-08-02T17:22:54.953342 #4638] DEBUG -- :    (0.1ms)  PRAGMA foreign_keys
D, [2018-08-02T17:22:54.953501 #4638] DEBUG -- :    (0.1ms)  PRAGMA defer_foreign_keys
D, [2018-08-02T17:22:54.953658 #4638] DEBUG -- :    (0.1ms)  PRAGMA defer_foreign_keys = ON
D, [2018-08-02T17:22:54.953794 #4638] DEBUG -- :    (0.1ms)  PRAGMA foreign_keys = OFF
D, [2018-08-02T17:22:54.954766 #4638] DEBUG -- :    (0.2ms)  CREATE TEMPORARY TABLE "abar" ("id" integer NOT NULL PRIMARY KEY, "new_foo_id" integer NOT NULL)
D, [2018-08-02T17:22:54.955253 #4638] DEBUG -- :    (0.1ms)  INSERT INTO "abar" ("id","new_foo_id")
                     SELECT "id","foo_id" FROM "bar"
D, [2018-08-02T17:22:54.955792 #4638] DEBUG -- :    (0.4ms)  DROP TABLE "bar"
D, [2018-08-02T17:22:54.958514 #4638] DEBUG -- :    (0.2ms)  CREATE TABLE "bar" ("id" integer NOT NULL PRIMARY KEY, "new_foo_id" integer NOT NULL)
D, [2018-08-02T17:22:54.958976 #4638] DEBUG -- :    (0.1ms)  INSERT INTO "bar" ("id","new_foo_id")
                     SELECT "id","new_foo_id" FROM "abar"
D, [2018-08-02T17:22:54.959140 #4638] DEBUG -- :    (0.1ms)  DROP TABLE "abar"
D, [2018-08-02T17:22:54.974059 #4638] DEBUG -- :    (0.1ms)  PRAGMA defer_foreign_keys = 0
D, [2018-08-02T17:22:54.974243 #4638] DEBUG -- :    (0.1ms)  PRAGMA foreign_keys = 1
D, [2018-08-02T17:22:54.975261 #4638] DEBUG -- :    (0.9ms)  commit transaction
2.4.1 :005 > ^D

$ echo ".schema bar" | sqlite3 test.db
CREATE TABLE IF NOT EXISTS "bar" ("id" integer NOT NULL PRIMARY KEY, "new_foo_id" integer NOT NULL);
```

### System configuration
**Rails version**:

master (78992d6f6dfebb5275b5e3b886aeb6908cbe1acb)

**Ruby version**:

2.4.1

**Comment by sikachu** [comment]
Do you mind sharing SQL in the log that got generate from steps 003?

**Comment by sikachu** [comment]
🤔 I must be missing something here since I didn't expect that it'd issue `CREATE_TABLE` instead of `ALTER_TABLE` ... let me see if I understand this correctly.

**Comment by kamipo** [comment]
SQLite3 doesn't support ALTER TABLE, so we emulated by CREATE TABLE and swap tables.

**Comment by sikachu** [comment]
@kamipo right ... Matthew just explained that to me 😭 

So it looks like we forgot to move over the `references` somehow.

Would you mind submitting a failing test case for us to work on, and maybe also a patch if it's not too much to ask?

Thank you very much for your report.

**Comment by jberkel** [comment]
No problem, I'll try to submit a patch. I noticed this bug while writing a Swift schema migration tool using ActiveRecord's migrations as inspiration, and have already fixed it there. The logic for getting the foreign keys is already in place, it's just not used for the schema change.

**Comment by twitnithegirl** [comment]
I'm reading the [SQLite3 page on this](https://www.sqlite.org/lang_altertable.html) and it's wild. So picky. Good find.

**Comment by jberkel** [comment]
@twitnithegirl I hope they will add proper support for `ALTER TABLE` one day. This table copy dance is complicated and error prone. Not sure if this is relevant for Rails but any views and triggers affecting the table also need to be recreated (step 9).

**Comment by jberkel** [comment]
Likewise, when a table is renamed the foreign keys need updating. SQLite can handle this case automatically but only when constraints are enabled, which is not the case during migrations.

The migration should also run `PRAGMA foreign_key_check` after making changes, as suggested by the SQLite docs.

**Comment by yahonda** [comment]
Thanks for the update and useful information. 
I did not know `PRAGMA foreign_key_check` pragma. Would you mind opening a pull request to support this pragma?

**Comment by lzap** [comment]
Can you guys explain what is the current status of sqlite3 foreign key support? It looks like `supports_foreign_keys_in_create?` is `true` but `supports_foreign_keys?` returns `false`. My understanding is that the implementation for sqlite3 is partial, keys are created for new tables but dropped when altering tables.

**Comment by thomthom** [comment]
For what version of ActiveRecord has this fix gone into?

I'm currently using 5.2.3 and when I use `bundle exec rake db:migrate db:test:prepare` I see that the migration first create the table with the foreign key, then it's dropped and recreated without the foreign key.

If I only do `bundle exec rake db:migrate` then the table is created correctly with the foreign key.

**Comment by thomthom** [comment]
I'm also noticing that `schema.rb` doesn't describe foreign keys - should that be the case?
