### ISSUE TITLE
If two controllers have the same before action function name then conflict occur's

### ISSUE THREAD

**Issue by NarenPushparaju** [rails/rails#33534]
### Steps to reproduce

(Guidelines for creating a bug report are [available
here](http://edgeguides.rubyonrails.org/contributing_to_ruby_on_rails.html#creating-a-bug-report))

### Expected behavior
Tell us what should happen

### Actual behavior
Tell us what happens instead

### System configuration
**Rails version**:

**Ruby version**:

**Comment by robin850** [comment]
Hello @NarenPushparaju,

Please give us more context and explanations about your issue or even provide an executable test case, as explained in the guidelines for creating a bug report.

**Comment by NarenPushparaju** [comment]
The following is my Topic Controller
class TopicsController < ApplicationController
  before_action :set_topic, only: [:show, :edit, :destroy, :update]

  def index
    @topics = Topic.all
  end

  def new
    @topic = Topic.new
  end

  def show
  end

  def create
    @topic = Topic.new(topic_params)
    if @topic.save
      redirect_to topics_path
    else
      p @topic.errors
      render 'new'
    end
  end

  def edit
  end

  def destroy
    @topic.destroy
    redirect_to topics_path
  end

  def update
    if @topic.update(topic_params)
      flash[:notice] = "Updated Successfully"
      redirect_to topic_path
    else
      render 'edit'
    end
  end
end

private

def topic_params
  params.require(:topic).permit(:topic)
end

def set_topic
  @topic = Topic.find(params[:id])
end
Here the post Controllerclass PostsController < ApplicationController

  before_action :set_topic
  before_action :set_post, only: [:show, :edit, :destroy, :update]

  def index
    if @topic.present?
      @posts = @topic.posts.all
    else
      @posts = Post.all
    end
    @posts = @posts.paginate(:page => params[:page], :per_page => 6)

  end

  def new
    @post = @topic.posts.new
    @tag = @post.tags.new
    @tag_all = Tag.all
  end

  def show
    @comment = @post.comments
    @tag = @post.tags
    @rate = @post.ratings.group("rate").count
    @rate = Hash[@rate.to_a.reverse]
    @avg_rate = @post.ratings.average(:rate)
  end

  def create

    @post = @topic.posts.new(post_params)
    if @post.save
      flash[:notice] = "Post sent Successfully"
      redirect_to topic_post_path(id: @post.id)
    else
      render 'new'
    end
  end

  def edit
  end

  def rate
    @rate = Rating.new(rate: params[:rate], post_id: params[:post_id])
    if @rate.save
      redirect_to topic_post_path(topic_id: params[:topic_id], id: params[:post_id])
    end
  end

  def destroy
    @post.destroy
    redirect_to topic_posts_path(@post.topic_id)
  end

  def update
    if @post.update(post_params)
      flash[:notice] = "Updated Successfully"
      redirect_to topic_post_path(id: @post.id)
    else
      render 'edit'
    end
  end

end

private

def post_params
  params.require(:post).permit(:title, :description, tag_ids: [],tags_attributes: [:tag, :_destroy, :id])
end

def set_post
  @post = @topic.posts.find(params[:id])
end

def set_topic
  if params[:topic_id].present?
    @topic = Topic.find(params[:topic_id])
  end
end

When i run the server And try to go to post controller It is showing error in topic controller's set action
![screen shot 2018-08-09 at 5 54 10 pm](https://user-images.githubusercontent.com/40913704/43898744-65aa03e6-9bfd-11e8-879b-ddf046294210.png)

**Comment by NarenPushparaju** [comment]
When i give different function name in before action for the controllers  it's fine

**Comment by robin850** [comment]
@NarenPushparaju: That's certainly because your private methods are defined at the top level; you need to put them underneath the class definition otherwise, one definition of your method get overwritten by the other.

**Comment by NarenPushparaju** [comment]
Thank You for your replay !! Solved.
