### ISSUE TITLE
Allow direct linking (no redirect) to files in ActiveStorage

### ISSUE THREAD

**Issue by Qwertie-** [rails/rails#33549]
### Steps to reproduce
Using url_for() on an active storage object gives an indirect url that redirects to the actual file link.
Because of this [firefox bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1346749) it's impossible to use ActiveStorage on a website using CORS. There could be other reasons why you don't want this as well.

### Expected behavior
There should be some way to get the direct link for a file without a redirect. The default behaviour is fine but some alternative method for getting the direct link would be very useful.

### System configuration
**Rails version**:  5.2.0

**Ruby version**: 2.5.1

**Comment by mapeveri** [comment]
I am new and I would like to take this issue, any suggestions?. Thanks!

**Comment by Qwertie-** [comment]
@mapeveri I have a few bits of info.

You can get direct links with this hacky method I found while reading the source

```
ActiveStorage::Current.host = "yourhostname"
attachment_blob = ActiveStorage::Attachment.find_by(record_type: "YourModel", record_id: record.id).blob
direct_url = ActiveStorage::Blob.service.url(
    attachment_blob.key,
    expires_in: 20000,
    disposition: "attachment",
    filename: attachment_blob.filename,
    content_type: attachment_blob.content_type
)
```

This probably isn't super recommended but it works. The main issue is the URL that comes from `ActiveStorage::Blob.service.url` expires which means if you leave the page open or send a link to a friend, by the time it is clicked the url will have died. This is intended, the reason I am told is because it stops users posting direct links to files that need authentication as it forces downloads to run through your app where auth can be checked and then redirected to an external file host.

This is a nice feature but not every app needs this and in the case from my report it breaks so having a way to disable it would be useful.

**Comment by Qwertie-** [comment]
Also pinging @matthewd so he can see the workaround I mentioned to him before.

**Comment by mapeveri** [comment]
@Qwertie- , thanks for the information. I understand that adding a property so that it does not expire, would solve your problem, something like this:

```
ActiveStorage::Current.host = "yourhostname"
attachment_blob = ActiveStorage::Attachment.find_by(record_type: "YourModel", record_id: record.id).blob
direct_url = ActiveStorage::Blob.service.url(
    attachment_blob.key,
    forever_link: true,
    disposition: "attachment",
    filename: attachment_blob.filename,
    content_type: attachment_blob.content_type
)
```

Adding, for example, a property "forever_link" in true? By default it had to be false. I would be ok?

**Comment by Qwertie-** [comment]
@mapeveri Ideally the methods listed in the [guide](https://edgeguides.rubyonrails.org/active_storage_overview.html#linking-to-files) would have an option for no redirect or maybe a config in the initializer. The code I posted above is probably not recommended for external use as it isn't mentioned in any documentation.

**Comment by mapeveri** [comment]
@Qwertie- I understand, a question, in which part do you think it would be useful to put a parameter to know if the url is fixed or not? rails_blob_url it's ok?

**Comment by Qwertie-** [comment]
rails_blob_url seems like a good place. Might be helpful if someone more experienced with ActiveStorage could comment.

**Comment by mapeveri** [comment]
I was watching a bit and if we put for example, something like this:

`rails_blob_url (@blob, {fixed: true})`

Or any parameter, this will arrive like this:

http://www.example.com/rails/active_storage/blobs/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBCZz09IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--6acde8a54f45e255c1b45e084c8510831a1dbe7a/racecar.jpg?fixed=true

Or warse

`rails_blob_url(@blob, true)`

http://www.example.com/rails/active_storage/blobs/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBCdz09IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--20358eca2ec21f700a0b36bf69b3f5d857fa5702/racecar.jpg.true


https://github.com/rails/rails/blob/master/activestorage/config/routes.rb#L6

It arrives as "options"

I think it could add security problems. Maybe in the model would be a better place?

what do you think?

**Comment by kinopyo** [comment]
Is this the same issue as https://github.com/rails/rails/issues/31419? It seems like many people there have provided solutions that monkey patch ActiveStorage to get the direct link of the file without redirection, but no official move has been made yet.

**Comment by Qwertie-** [comment]
@kinopyo It does seem to be a duplicate of that bug.

**Comment by sandrew** [comment]
@Qwertie- 
I believe my small gem https://github.com/sandrew/activestorage_direct_disk will help people with the same problem.
So sad that core developers don't listen to people with needs of direct linking to files :(

**Comment by staycreativedesign** [comment]
> @mapeveri I have a few bits of info.
> 
> You can get direct links with this hacky method I found while reading the source
> 
> ```
> ActiveStorage::Current.host = "yourhostname"
> attachment_blob = ActiveStorage::Attachment.find_by(record_type: "YourModel", record_id: record.id).blob
> direct_url = ActiveStorage::Blob.service.url(
>     attachment_blob.key,
>     expires_in: 20000,
>     disposition: "attachment",
>     filename: attachment_blob.filename,
>     content_type: attachment_blob.content_type
> )
> ```
> 
> This probably isn't super recommended but it works. The main issue is the URL that comes from `ActiveStorage::Blob.service.url` expires which means if you leave the page open or send a link to a friend, by the time it is clicked the url will have died. This is intended, the reason I am told is because it stops users posting direct links to files that need authentication as it forces downloads to run through your app where auth can be checked and then redirected to an external file host.
> 
> This is a nice feature but not every app needs this and in the case from my report it breaks so having a way to disable it would be useful.

How can I enable this feature in my app I dont know where to put this code

**Comment by sandrew** [comment]
> I'm pretty sure rails_blob_url is what you want to use in this case. See https://edgeguides.rubyonrails.org/active_storage_overview.html#linking-to-files

Actually no, this is just a helper that leads to `/blobs/redirect/:signed_id/*filename`

**Comment by staycreativedesign** [comment]
Correct i just want some thing  with a normal link not some active storage
blob
