### ISSUE TITLE
Arel doesn't correctly handle empty string predecations for type integer

### ISSUE THREAD

**Issue by 3limin4t0r** [rails/rails#33544]
When passing an empty string to an Arel predication for a column with type integer it is not correctly converted to `IS NULL` or `IS NOT NULL`, but instead produces `= NULL` or `!= NULL`.

### Steps to reproduce

```
rails new blog
cd blog
bundle install
bundle exec rails generate model Post name:string
bundle exec rails db:migrate
bundle exec rails console
```

### Expected behavior

For an attribute with type string the following code should produce the following output:

```ruby
puts Post.arel_table[:name].eq('').to_sql
# "posts"."name" = ''
puts Post.arel_table[:name].eq(nil).to_sql
# "posts"."name" IS NULL
```

For an attribute with type integer the following code should produce the following output:

```ruby
puts Post.arel_table[:id].eq('').to_sql
# "posts"."name" IS NULL
puts Post.arel_table[:id].eq(nil).to_sql
# "posts"."name" IS NULL
```

### Actual behavior

The result for strings is correct, however for an attribute of integer type this produces the following output:

```ruby
puts Post.arel_table[:id].eq('').to_sql
# "posts"."name" = NULL
puts Post.arel_table[:id].eq(nil).to_sql
# "posts"."name" IS NULL
```

As you can see passing a `nil` value behaves correctly, however passing an empty string doesn't produce the expected result but instead produces `= NULL` instead of `IS NULL`. Similarly Arel produces `!= NULL` when using `#not_eq` and passing an empty string.

### System configuration

**Rails version**: 5.1.6

**Ruby version**: 2.4.1

**Arel version**: 8.0.0

**Comment by y-yagi** [comment]
Arel is not part of the public API of the Rails. Therefore, the behavior when calling Arel's API directly from Rails is not guaranteed. Thanks.
