### ISSUE TITLE
Getter called for validating numericality

### ISSUE THREAD

**Issue by alexkuebo** [rails/rails#33550]
### Steps to reproduce

https://gist.github.com/alexkuebo/dc366487b5f16e2481f191fa003b2986

### Expected behavior
Until rails 5.2.0 the validation of an attribute with overwritten getter succeeded because it uses `#{attr_name}_before_type_cast`.

### Actual behavior
Since rails 5.2.1 (specifically commit https://github.com/rails/rails/commit/c15d8b3a21bf1ae3ca9f09ca9cad8cc3828aa9be) the validation fails because it uses the getter.

### System configuration
**Rails version**: 5.2.1

**Ruby version**: 2.5.1

**Comment by rafaelfranca** [comment]
There we never guarantees that the value before type cast was going to the used in this validation. I personally think this new behavior make sense, but I do agree we should not change the behavior in a stable version.

@kamipo what do you think?

**Comment by kamipo** [comment]
Yeah... I agree too we should not change the behavior in a stable version even if it is not guaranteed unless there is some particular reason.

I've proposed a PR to fix a regression #33603.
