### ISSUE TITLE
Rails generators do not run in tests

### ISSUE THREAD

**Issue by tubbo** [rails/rails#33558]
### Steps to reproduce

1. Generate a generator: `rails generate generator foo`
2. Edit generator to call `generate('scaffold foos')`
3. Edit generator test to `assert_file('app/controllers/foos_controller.rb')`
4. Observe test failure

Demo: https://github.com/tubbo/rails-app-33558

### Expected behavior
The file **app/controllers/foos_controller.rb** should have appeared in the `destination_root`

### Actual behavior
The following output is observed in tests:

```
Run options: --seed 1177

# Running:

/Users/tscott/.rbenv/versions/2.4.3/bin/ruby: No such file or directory -- bin/rails (LoadError)
F

Failure:
FooGeneratorTest#test_generator_generates_generated_generators [/Users/tscott/Code/throwaway/test/lib/generators/foo_generator_test.rb:12]:
Expected file "app/controllers/foos_controller.rb" to exist, but does not


bin/rails test test/lib/generators/foo_generator_test.rb:9



Finished in 0.046933s, 21.3070 runs/s, 21.3070 assertions/s.
1 runs, 1 assertions, 1 failures, 0 errors, 0 skips
```

### System configuration
I've tested this on multiple minor versions of Rails 5 and Ruby 2...

**Rails version**: 5.2.0, 5.1.4

**Ruby version**: 2.4.3, 2.5.1

**Comment by robin850** [comment]
This looks like an issue indeed; [the `generate` method](https://github.com/rails/rails/blob/b031a9a4f44397cfeed1dd74524a44dfbd199be7/railties/lib/rails/generators/actions.rb#L218) ends up trying to invoke `bin/rails` inside the destination directory (i.e. `tmp/generators` here) which is empty when the test runs so this explains the "No such file or directory -- bin/rails" error message.

We should either generate a dummy application structure inside the destination folder or provide a facility to do so. Or at least a comment explaining that the user may need do that can be a good starting point.

**Comment by tubbo** [comment]
@robin850 what's the reasoning behind actually shelling out and calling `bin/rails`? I was thinking we could get away with something like this:

```diff
       def generate(what, *args)
+        load_generators
         log :generate, what
         argument = args.flat_map(&:to_s).join(" ")

-        in_root { run_ruby_script("bin/rails generate #{what} #{argument}", verbose: false) }
+        Generators.invoke(what, argument, behavior: :invoke, destination_root: destination_root)
       end
```

**Comment by robin850** [comment]
@tubbo: Skimming the Git history, it looks like [this has always been shelling out](https://github.com/rails/rails/commit/d57b19380eaad8bda63743107f085e72935343b9#diff-cefc49e0d370edc689226f5720a68f91R198) not for any specific reason ; maybe because the generator API wasn't that easy to use back in the days.

We can maybe simplify this method with something like you provided but we will have to handle cases like `generate 'generator with arguments'`. Even though it's not officially used/supported, people may have code using this syntax (just like your code) but this would end up producing an error since the `what` argument would equal the whole string and `argument` would be empty. I don't know if we need to handle other edge cases though.

Anyway, the *real* problem here is that the `tmp/generators` directory doesn't hold a Rails application folder structure, so the scaffold generator will produce errors anyway since it expects certain files/folders to exist.

**Comment by tubbo** [comment]
that's a good point @robin850, having a dummy app in `tmp/generators` would also make the testing scenarios more realistic. that said, if one was trying to test a generator made in a Rails plugin, I suppose they could just change `destination_root` to `Rails.root` since that is equal to the `tmp/dummy` app directory, right? if you're right about just needing a rails app folder structure in `tmp/generators`, then pointing my generator test's `destination_root` at `tmp/dummy` _should_ work..

**Comment by tubbo** [comment]
@rafaelfranca I have not, but will try it right now.

**Comment by tubbo** [comment]
@rafaelfranca Unfortunately, removing `bin/` doesn't seem to solve it. I was able to modify a unit test in **railties/test/rails/generators/actions_test.rb** to reproduce my error:

```ruby
  def test_generate_should_run_script_generate_with_argument_and_options
    assert_called_with(generator, :run_ruby_script, ["bin/rails generate model MyModel", verbose: false]) do
      action :generate, "model", "MyModel"
    end
    assert_file("app/models/my_model.rb")
  end
```

Changing this to expect "rails generate model MyModel", as well as the code to run `rails` instead of `bin/rails`, causes the following error in `rake test` from within railties:

```
Failure:
ActionsTest#test_generate_should_run_script_generate_with_argument_and_options [test/generators/actions_test.rb:271]:
Expected file "app/models/my_model.rb" to exist, but does not
```

**Comment by rafaelfranca** [comment]
I think this test will not pass because you are mocking the creation of the file with `assert_called_with`

**Comment by tubbo** [comment]
@rafaelfranca thanks for the heads-up! PR incoming.

**Comment by tubbo** [comment]
PR #34420 should handle this
