### ISSUE TITLE
Active Storage Variant Option is not Working as Expected

### ISSUE THREAD

**Issue by Faizaankhan3** [rails/rails#33556]
### Steps to reproduce
```ruby
class Product < ApplicationRecord
   has_many_attached :images
end
```

In view: 
```ruby
<%= image_tag(url_for(@product.images.first.variant(resize: "100x100", flip: "-90"))) %>
```

### Expected behavior
The image is supposed to be shown flipped

### Actual behavior
The image is not loading,

![image](https://user-images.githubusercontent.com/16518466/43844701-fa77f9da-9b47-11e8-95b1-0dae9535f9b6.png)

In Logs I have  
```
MiniMagick::Error (`mogrify -flip -90 /tmp/mini_magick20180808-26054-yjj6f4.jpg` failed with error:
mogrify-im6.q16: unable to open image `-90': No such file or directory @ error/blob.c/OpenBlob/2701.
mogrify-im6.q16: no decode delegate for this image format `' @ error/constitute.c/ReadImage/504.
):
```

while below options work properly
```ruby
<%= image_tag(url_for(@product.images.first.variant(resize: "100x100"))) %>
<%= image_tag(url_for(@product.images.first.variant(resize: "100x100", rotate: "-180"))) %>
<%= image_tag(url_for(@product.images.first.variant(resize: "100x100", rotate: "-180", monochrome: true))) %>
```

### System configuration
**Rails version**: 5.2

**Ruby version**: 2.3.3

**Comment by mbodlund** [comment]
Flip doesn't take any options so to use it leave the value as nil

`<%= image_tag(url_for(@product.images.first.variant(resize: "100x100", flip: nil))) %>`

See https://www.imagemagick.org/script/command-line-options.php#flip

**Comment by faizaankhan** [comment]
@mbodlund  Thanks for the link, it's such a great help to start with. If there's any other documentation than plz forward, and bdw whats better to use RMagick or Minimagick ?? Or does it even matter? The files I need to deal with might be of huge sizes, like in 50-60mbs and may be of .tiff, png or jpeg. 

**Thanks again**

**Comment by georgeclaghorn** [comment]
> so to use it leave the value as nil

Active Storage discards transformations with `nil` arguments. Use `true` instead.

**Comment by faizaankhan** [comment]
@georgeclaghorn  It's not discarding transformations with nil bdw
