### ISSUE TITLE
5.2.1 has breaking change over 5.2.0

### ISSUE THREAD

**Issue by pedrofurtado** [rails/rails#33557]
The method highlighted in this file ( https://github.com/rails/rails/blob/master/activerecord/lib/active_record/associations/join_dependency.rb#L67 ) changed the number of parameters.

However, with this change, the gems ransack, polyamorous and other from activerecord-hackery ( https://github.com/activerecord-hackery ) crashs the application.

Related issues:

activerecord-hackery/ransack#942
activerecord-hackery/polyamorous#46

**Comment by gsamokovarov** [comment]
In Rails, we consider everything that's documented a public API. This file marks the `JoinDependency` class as undocumented, meaning that it's not part of the public API.
 https://github.com/rails/rails/blob/3000c1490565b3a21376d6444cb6fe24dfe4e383/activerecord/lib/active_record/associations/join_dependency.rb#L5

It's too bad that those gems are currently broken, but by using private API's, you're bound to expect changes even across minor releases.

**Comment by rafaelfranca** [comment]
What @gsamokovarov said. Those gems were relying on private API and private API can change between minor version.

**Comment by pedrofurtado** [comment]
@rafaelfranca @gsamokovarov Thanks for feedback! Anyway, I've created some issues in these gems to provide some kind of fix :+1:

**Comment by gregmolnar** [comment]
Indeed, ransack builds on top of private API's and it isn't broken, you just need to use it's master branch with Rails 5.2.1.
