### ISSUE TITLE
Before Action function name conflict issue

### ISSUE THREAD

**Issue by NarenPushparaju** [rails/rails#33565]
The following is my Topic Controller
class TopicsController < ApplicationController
before_action :set_topic, only: [:show, :edit, :destroy, :update]

def index
@topics = Topic.all
end

def new
@topic = Topic.new
end

def show
end

def create
@topic = Topic.new(topic_params)
if @topic.save
redirect_to topics_path
else
p @topic.errors
render 'new'
end
end

def edit
end

def destroy
@topic.destroy
redirect_to topics_path
end

def update
if @topic.update(topic_params)
flash[:notice] = "Updated Successfully"
redirect_to topic_path
else
render 'edit'
end
end
end

private

def topic_params
params.require(:topic).permit(:topic)
end

def set_topic
@topic = Topic.find(params[:id])
end
Here the post Controllerclass PostsController < ApplicationController

before_action :set_topic
before_action :set_post, only: [:show, :edit, :destroy, :update]

def index
if @topic.present?
@posts = @topic.posts.all
else
@posts = Post.all
end
@posts = @posts.paginate(:page => params[:page], :per_page => 6)

end

def new
@post = @topic.posts.new
@tag = @post.tags.new
@tag_all = Tag.all
end

def show
@comment = @post.comments
@tag = @post.tags
@Rate = @post.ratings.group("rate").count
@Rate = Hash[@rate.to_a.reverse]
@avg_rate = @post.ratings.average(:rate)
end

def create

@post = @topic.posts.new(post_params)
if @post.save
  flash[:notice] = "Post sent Successfully"
  redirect_to topic_post_path(id: @post.id)
else
  render 'new'
end
end

def edit
end

def rate
@Rate = Rating.new(rate: params[:rate], post_id: params[:post_id])
if @rate.save
redirect_to topic_post_path(topic_id: params[:topic_id], id: params[:post_id])
end
end

def destroy
@post.destroy
redirect_to topic_posts_path(@post.topic_id)
end

def update
if @post.update(post_params)
flash[:notice] = "Updated Successfully"
redirect_to topic_post_path(id: @post.id)
else
render 'edit'
end
end

end

private

def post_params
params.require(:post).permit(:title, :description, tag_ids: [],tags_attributes: [:tag, :_destroy, :id])
end

def set_post
@post = @topic.posts.find(params[:id])
end

def set_topic
if params[:topic_id].present?
@topic = Topic.find(params[:topic_id])
end
end

When i run the server And try to go to post controller It is showing error in topic controller's set action
![screen shot 2018-08-09 at 5 54 10 pm](https://user-images.githubusercontent.com/40913704/43898901-ed7a2314-9bfd-11e8-95c9-898758bdb032.png)

When i give different before action function name for the controller's it's fine

The error is occurring  not all the time but often
My Rails version is 5.1.6
Ruby version is ruby 2.5.1p57 (2018-03-29 revision 63029) [x86_64-darwin17]

**Comment by y-yagi** [comment]
Please use the [mailing list](https://groups.google.com/forum/#!forum/rubyonrails-talk) or StackOverflow for questions/help, where a wider community will be able to help you. We reserve the issues tracker for issues only. Thanks!
