### ISSUE TITLE
Active Storage variant keys change after rails upgrade. (Disk service)

### ISSUE THREAD

**Issue by mbodlund** [rails/rails#33562]
After updating rails from 5.2.0 to 5.2.1 I noticed that all variants are being recreated. Can see the keys are changed. One test variant before and after update.

5.2.0: variants/vMfxwsSDKPLxNeLwssygXtWq/aff70428e42f943fbadd828ac142400b41da19bcd8ade8941303bf6dcc984456

5.2.1:
variants/vMfxwsSDKPLxNeLwssygXtWq/f697d5b25542c7ae5146f18743b25c90411bcfbb6c70f34f2af1e4225b56bae8

Unsure if this is expected behaviour.

### Steps to reproduce
Upgrade from rails 5.2.0 ro 5.2.1

### Expected behavior
I would expect not having to recreate variants already created.

### Actual behavior
All variants gets recreated after rails upgrade due to variant key being changed.

### System configuration
**Rails version**:  2.4.2

**Ruby version**: 5.2.0 and 5.2.1 - Active Storage with Disk service

**Comment by mbodlund** [comment]
Can verify that the behaviour is the same. After updating Rails from 5.2.0 to 5-2-stable all of my variants are being recreated.

Can se that the ActiveStorage variant key changes. But cant figure out why.

If you have a lot of larger images with already generated variants - it just feels strange to have to regenerate all these.

**Comment by cpunion** [comment]
I can't upgrade rails from 5.2.0 because of this issue. Is there a way to solve it?

**Comment by dwightwatson** [comment]
Has anyone been able to narrow down what code caused the change? I noticed this on 5.2.2 and scoured the ActiveStorage changes between 5.2.1 and 5.2.2 but couldn’t find anything obvious.

**Comment by swrobel** [comment]
I just ran into this upgrading from 6.0 to 6.1. Did anyone have any luck figuring out why it's happening?
