### ISSUE TITLE
belongs_to doesn't support inverse_of via has_many contrary to recent documentation updates

### ISSUE THREAD

**Issue by aleksandrs-ledovskis** [rails/rails#33578]
### Steps to reproduce

```ruby
# frozen_string_literal: true

begin
  require "bundler/inline"
rescue LoadError => e
  $stderr.puts "Bundler version 1.10 or later is required. Please update your Bundler"
  raise e
end

gemfile(true) do
  source "https://rubygems.org"

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  gem "rails", github: "rails/rails"
  gem "sqlite3"
end

require "active_record"
require "minitest/autorun"
require "logger"

# This connection will do for database-independent bug reports.
ActiveRecord::Base.establish_connection(adapter: "sqlite3", database: ":memory:")
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :posts, force: true do |t|
  end

  create_table :notes, force: true do |t|
  end

  create_table :comments, force: true do |t|
    t.integer :post_id
    t.integer :note_id
  end
end

class Post < ActiveRecord::Base
  has_many :comments, inverse_of: :post
end

class Note < ActiveRecord::Base
  has_one :comment, inverse_of: :note
end

class Comment < ActiveRecord::Base
  belongs_to :post, inverse_of: :comments
  belongs_to :note, inverse_of: :comment
end

class BugTest < Minitest::Test
  def test_comment_inverse_of_note
    note = Note.new
    comment = note.build_comment

    assert_equal comment.note, note 
  end

  def test_note_inverse_of_comment
    comment = Comment.new
    note = comment.build_note

    assert_equal note.comment, comment 
  end

  def test_comment_inverse_of_post
    post = Post.new
    comment = post.comments.build

    assert_equal comment.post, post
  end

  ### 
  ### Failing test
  ###
  def test_post_inverse_of_comment
    comment = Comment.new
    post = comment.build_post

    assert_includes post.comments, comment
  end
end
```

### Expected behavior
Either:
1. `Post` object built from `Comment` correctly finds its creator via `#comments` association method.
2. Rails documentation specifies that `belongs_to` doesn't work with `:inverse_of` pointing to inverse `has_many` association

### Actual behavior
`:inverse_of` setting for `belongs_to` is silently ignored and object chain is non-traversable bidirectionally. 

### System configuration
**Rails version**: 6.0.0.alpha (`master`)

**Ruby version**: CRuby 2.5.1

---

Previously (up to https://github.com/rails/rails/pull/27538), Rails Documentation contained following warning

> For `belongs_to` associations, `has_many` inverse associations are ignored.

Also, at the beginning of 2018 another PR [modified](https://github.com/rails/rails/pull/31446/files#diff-a215bfc911ab0913d92695a0f20310efL1068) RDocs to same effect, removing

> inverse associations for #belongs_to associations #has_many are ignored.

**Yet**,  `ActiveRecord::Associations::BelongsToAssociation` [still contains](https://github.com/rails/rails/blob/975fa15b47e4ef47a3b46f0e946860a076167149/activerecord/lib/active_record/associations/belongs_to_association.rb#L108-L113) both the comment warning & `inverse.has_one?` guard:

```ruby
# NOTE - for now, we're only supporting inverse setting from belongs_to back onto
# has_one associations.
def invertible_for?(record)
  inverse = inverse_reflection_for(record)
  inverse && inverse.has_one?
end
```

**Comment by aleksandrs-ledovskis** [comment]
Bumping, not stale.

**Comment by aleksandrs-ledovskis** [comment]
Not stale. Being worked on in #34533

**Comment by aleksandrs-ledovskis** [comment]
Bumped. Not stale

**Comment by aleksandrs-ledovskis** [comment]
Bumped. Not stale

**Comment by dmitry** [comment]
Bumped. Not stale
