### ISSUE TITLE
Documentation error: Testing doc incorrectly refers to setting headers on a session

### ISSUE THREAD

**Issue by chrismanderson** [rails/rails#33579]
The [Testing Rails Applications Rails Guide](https://guides.rubyonrails.org/testing.html) refers to setting the headers on a request within an `ActionDispatch::IntegrationTest` test. That's not supported (as of Rails 5 I believe).

**************
```NOTE: If you followed the steps in the Basic Authentication section, you'll need to add the following to the `setup` block to get all the tests passing:```

```ruby
request.headers['Authorization'] = ActionController::HttpAuthentication::Basic.encode_credentials('dhh', 'secret')
```

https://github.com/rails/rails/blame/45903be1344992b1f0156cd88c351067bdc93726/guides/source/testing.md#L1116
***************

Believe section should either be removed, or changed to demonstrate setting the headers within a request, ala

```ruby
post articles_url, headers: { Authorization: ActionController::HttpAuthentication::Basic.encode_credentials('dhh', 'secret') }, 
                             params: { article: { body: 'Rails is awesome!', title: 'Hello Rails' } }
```

**Comment by y-yagi** [comment]
Thanks for your report! Your point is correct. 
Can you create a PR to fix it?

**Comment by chrismanderson** [comment]
Looks like @darren987469 got it, cheers!
