### ISSUE TITLE
RFC: Developer's use of redirect_to and Ruby's URI makes their apps vulnerable to open redirects too often

### ISSUE THREAD

**Issue by hawe** [rails/rails#33577]
The way that many web developers use `URI#path`, and `URI#relative?` in redirect checks makes their apps vulnerable. Also because authoritative websites recommend these checks. Because this is a widespread issue, I'd propose adding more secure defaults to `redirect_to` for protocol-relative URIs (`//attacker.com`).

## Problem
Many use parameters to carry the start URL or path over and redirect to it (aka `params[:return_url]`). Developers are often unaware of protocol-relative URIs (`//attacker.com`) and (unfortunately) valid URI paths: `https://example.com//attacker.com`.

## Steps to reproduce
- Validation in a controller:
```
# params[:return_url] #=> "//attacker.com"
redirect_to(params[:return_url]) if URI.parse(params[:return_url]).relative? # => //attacker.com
```
Because frankly, 'relative' sounds like a local redirect.

- Remove the host, in a controller. This is a frequent recommendation against open redirect vulnerabilities from authoritative websites like [OWASP](https://www.owasp.org/index.php/Ruby_on_Rails_Cheatsheet#Redirects_and_Forwards), [Codeclimate](https://codeclimate.com/blog/rails-insecure-defaults/#offsite-redirects) and [Brakeman](https://brakemanscanner.org/docs/warning_types/redirect/index.html).

```
cancel_path = params[:cancel_path] # "https://test.com//attacker.com"
redirect_to URI.parse(cancel_path).path # => //attacker.com
```

It's unfortunate that as per the RFC an unlimited number of consecutive slashes are allowed in URI paths.

## Workaround
If you've this in your code right now, make sure it's not a protocol-relative URI, i.e. starts with '//'.

### System configuration
**Rails version**: all
**Ruby version**: all

## How to fix?
Due to the amount of vulnerable apps and vulnerable code examples out there, I'd propose changing the `redirect_to` method. While RFC-compliant, redirecting to a protocol-relative URI isn't very common. We should probably not remove it, but restrict it. Ideas:
- Add a flag `redirect_to_protocol_relative_uris` which defaults to false.
- Add a flag `allow_other_host` (as in `redirect_back`) which defaults to false. Some might find it too restrictive and always enable it.
- A new method `redirect_to_protocol_relative_uri`

Any comments?

Notification: Discussing this security problem in the open with @rafaelfranca.

**Comment by rafaelfranca** [comment]
Agree about the solution. I'd go with "Add a flag allow_other_host (as in redirect_back) which defaults to false."

@gmcgibbon wants to work on it?

**Comment by gmcgibbon** [comment]
👍 I'm on it!

**Comment by nsuchy** [comment]
What do you think about renaming the flag `redirect_to_protocol_relative_uris` to `allow_redirect_to_protocol_relative_uris` to be more clear about what the flag is doing as well as being consistent with the other flag? (Very tiny issue, but curious on other developers thoughts here)

**Comment by Intrepidd** [comment]
Hello !  Just passing by, I wanted to add another example : 

```ruby
# example.com
redirect_to ".br" # Will be redirected to example.com.br
```
