### ISSUE TITLE
ActiveSupport::HashWithIndifferentAccess converting to ActionController::Parameters upon iteration

### ISSUE THREAD

**Issue by morcoteg** [rails/rails#33582]
### Steps to reproduce
(Running Rails 4.2.10/Ruby 2.3.6)

Let's say I have some semi-complicated parameters. In the project I'm working on, there is some accessing of params going on, validating required params, etc.

At the model layer, I am letting my models create from mass assigned parameters, invoking something like `MyModel.create!(params.to_h)`.

I have a `binding.pry` right before this `create!` call, and when I evaluate the `#class` of the `params` here, I get unexpected behavior.

So I dug in with a coworker a little more. Turns out that when we referenced our `params` variable (in a `pry` breakpoint) somewhere along the path to the model layer, simply referencing that variable would invoke `Object or Hash#inspect` which looks like it does some iteration `return rb_exec_recursive(...)` https://ruby-doc.org/core-2.1.1/Object.html#method-i-inspect.

By invoking any sort of iteration along the path to the model, the `params` would come through as `ActionController::Parameters` objects at the model layer. When not invoking ANY iteration or references in `pry`, the `params.class` would evaluate `ActiveSupport::HashWithIndifferentAccess`. This is not ideal, so I read a little more here (even though Rails 5) https://blog.bigbinary.com/2016/07/25/parameters-no-longer-inherit-from-hash-with-indifferent-access-in-rails-5.html,
here --  https://github.com/rails/rails/issues/33044
and the PR for that^ --  https://github.com/rails/rails/pull/33076,

but still not sure why simply referencing or iterating over my params variables would cause such a class change, from `ActiveSupport::HWIA` -> `ActionController::Parmeters`. If anything, I'd expect the opposite.

If anyone has any insight into why this may be occurring, that'd be extremely helpful.

(Guidelines for creating a bug report are [available
here](http://edgeguides.rubyonrails.org/contributing_to_ruby_on_rails.html#creating-a-bug-report))

### Expected behavior
Covered above

### Actual behavior
Covered above

### System configuration
**Rails version**: 4.2.1

**Ruby version**: 2.3.6

**Comment by georgeclaghorn** [comment]
Please open a new issue if you can reproduce in [an executable test case](
https://edgeguides.rubyonrails.org/contributing_to_ruby_on_rails.html#create-an-executable-test-case) with Rails 5.2 or master. Rails 4.2 is [no longer supported](https://edgeguides.rubyonrails.org/maintenance_policy.html).
