### ISSUE TITLE
Added flash types are listed in controller action methods

### ISSUE THREAD

**Issue by Bodacious** [rails/rails#33593]
### Steps to reproduce

1. Subclass `ActionController::Base`
2. Add an additional flash type via `add_flash_types`
3. Inspect that controller's `action_methods`
4. You'll see your flash type included in that set

``` ruby
# frozen_string_literal: true

begin
  require "bundler/inline"
rescue LoadError => e
  $stderr.puts "Bundler version 1.10 or later is required. Please update your Bundler"
  raise e
end

gemfile(true) do
  source "https://rubygems.org"

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  gem "rails", github: "rails/rails"
end

require "action_controller/railtie"

class TestApp < Rails::Application
  config.root = __dir__
  secrets.secret_key_base = "secret_key_base"

  config.logger = Logger.new($stdout)
  Rails.logger  = config.logger

  routes.draw do
    get "/" => "test#index"
  end
end

class TestController < ActionController::Base
  add_flash_types :hype
end

require "minitest/autorun"
require "rack/test"

class BugTest < Minitest::Test
  include Rack::Test::Methods

  def test_returns_success
    assert TestController.action_methods.include?('hype')
  end
end

```

### Expected behavior

Flash types should not be listed as action methods.

### Actual behavior
Flash types are indeed being listed as action methods.

### System configuration
**Rails version**:
Observed in 5.2.1 and edge.

**Ruby version**:
2.5.1

**Comment by p8** [comment]
Hi @Bodacious, are you still interested in fixing this?
If so, could you resubmit your PR based on main instead of master?
Thanks!

**Comment by Bodacious** [comment]
Yes, will do this week!

**Comment by p8** [comment]
Great! 😄

**Comment by Bodacious** [comment]
@p8 I've submitted a fresh PR this morning. Thanks for chasing me up on this.

**Comment by p8** [comment]
Thanks @Bodacious !
