### ISSUE TITLE
ActiveJob test adapter performs jobs inline and calls after_enqueue callback too late

### ISSUE THREAD

**Issue by kreintjes** [rails/rails#33601]
### Steps to reproduce

Consider the following job and test:
```
class SampleJob < ApplicationJob
  before_enqueue { puts "Before enqueue callback: #{arguments.inspect}" }
  after_enqueue { puts "After enqueue callback: #{arguments.inspect}" }

  before_perform { puts "Before perform callback: #{arguments.inspect}" }
  after_perform { puts "After perform callback: #{arguments.inspect}" }

  def perform(message)
    sleep 5 # Do some very complex stuff
    puts "Perform: #{message}"
  end
end
```

```
class SampleTest < ActiveSupport::TestCase
  include ActiveJob::TestHelper

  test "Sample" do
    ActiveJob::Base.queue_adapter = :test

    perform_enqueued_jobs do
      puts "Enqueing..."
      SampleJob.perform_later("Hello")
      puts "Enqueued"
    end
  end
end
```
(issue also occurs when using `ActiveJob::Base.queue_adapter.perform_enqueued_jobs = true` instead of calling `perform_enqueued_jobs` manually)

And run the test: `bin/rails test sample_test.rb`

### Expected behavior
I would expect the job to actually performed later (async) and not immediately (inline), so I would expect the "Enqueued" message before the actual perform. Also I would expect the after enqueue callback to occur before the output of the perform method and callbacks. In other words, I would expect this output:

```
Enqueuing...
Before enqueue callback: ["Hello"]
After enqueue callback: ["Hello"]
Enqueued
Before perform callback: ["Hello"]
Perform: Hello
After perform callback: ["Hello"]
```

### Actual behavior
Perform is called immediately, before the block scheduling the job is finished (prints "Enqueued") and the after enqueue callback is called last (after the perform method/callbacks):

```
Enqueuing...
Before enqueue callback: ["Hello"]
Before perform callback: ["Hello"]
Perform: Hello
After perform callback: ["Hello"]
After enqueue callback: ["Hello"]
Enqueued
```

### Remarks
At the least I would expect the after enqueue callback to be called before the perform. However, 
I also think it should be possible to determine when the job is performed. For example in a system/feature test, I would want the original controller action/request to complete before the job is performed. Otherwise the job is always already finished upon page load, while you expect it to be completed later (and want to test the handling of unfinished jobs). So when using the `perform_enqueued_jobs` helper with a block (containing for example a form submit), I would expect the block to be fully completed before the job is performed. However, maybe it should even be possible to delay the execution of the job until even later (for example visit some other page before the job is performed).

### System configuration
**Rails version**: 5.2.1 (problem also occurs in Rails 5.0.4)

**Ruby version**: 2.4.1

**Comment by y-yagi** [comment]
It is a specification that job is used in inline when using `test` adapter. 
Ref: https://guides.rubyonrails.org/testing.html#testing-jobs 

If you expect to execute job asynchronously in tests, use non-test on adapter. Thanks.

**Comment by kreintjes** [comment]
Hi @y-yagi, thanks for your quick response. Okay, but even if the test adapter is supposed to be run inline, wouldn't you expect the after_enqueue callback to be called before the perform (callbacks)? Otherwise suppose you set a state in the after_enqueue and perform method or callbacks, then the state from perform would be overwritten by the state from the after_enqueue, while in a normal situation the perform would be last.

Also what if you want more control over when the jobs are performed in tests? If I use the async adapter in my tests the jobs could be performed at any moment, potentially before the original action/request is finished, but possibly also after it. You might want to test that at first a "Task will be performed soon" message is shown, then trigger the jobs (manually from the tests using some sort of perform_enqueued_jobs_now helper) and then test the result of the task is shown (after a refresh or an ActionCable load). Any way to achieve this control?
