### ISSUE TITLE
activesupport: Camelize with namespace is not idempotent (so to speak)

### ISSUE THREAD

**Issue by anzak-aleem** [rails/rails#33614]
While calling the `#camelize` on the string with namespace, if one the the namespace is already in the camel case, the camel case is not preserved for last such element.

### Steps to reproduce

```
"Admin/There/Is/CowInTheField".camelize
"adminGuy/there/is/CowInThe/Field".camelize
```

### Expected behavior

Admin::There::Is::CowInTheField
AdminGuy::There::Is::CowInThe::Field

### Actual behavior

Admin::There::Is::Cowinthefield
AdminGuy::There::Is::Cowinthe::Field

### System configuration

**Rails version**:
Rails 5.2.0

**Ruby version**:
ruby 2.5.0p0

**Comment by matthewd** [comment]
This is expected behaviour; if it's not what you want, don't call camelize on an already partially-camelized string.
