### ISSUE TITLE
ActiveStorage returns 404 using local disk service after a while.

### ISSUE THREAD

**Issue by StanlyShauro** [rails/rails#33613]
### Steps to reproduce

I use ActiveStorage disk storage to store video-files. I use MediaElement.js to show controls on a video page. 

When I open a video, it works fine. Rewind and seek works great too. But, I have to seek the video many times with pauses. After a while (several minutes) the video stops seeking. The network request returns 404 in the console.

As far as I'm concerned, the video signature turns 'bad' and the link becomes broken.
When I refresh the page with the video, the video works fine again. 

I expect that the link for video is permanent or works for long time (at least 6 hours).
Or, there must be a way to control that behavior.

### System configuration
**Rails version**:  github: 'rails/rails', :ref => '2d3a28b'

**Ruby version**: 2.5.1

**Comment by georgeclaghorn** [comment]
Download URLs expire after 5 minutes by default. You can adjust for your application by changing `config.active_storage.service_urls_expire_in`. See [Configuring Active Storage](https://edgeguides.rubyonrails.org/configuring.html#configuring-active-storage) for more.

**Comment by mengqing** [comment]
Is it possible to specify the expiry time on a per url basis?

**Comment by leoplct** [comment]
How can I set infinity expiration?
We use Active Storage images for a blog post and images supposed to be there forever.

**Comment by fguillen** [comment]
https://blog.saeloun.com/2021/09/14/rails-7-adds-expiring-urls-to-active-storage/
