### ISSUE TITLE
Duplicate nested records created with `create_with` & `find_or_create_by` for >= rails 5.2

### ISSUE THREAD

**Issue by abrom** [rails/rails#33610]
### Steps to reproduce
I've created a gist that demonstrates the issue, testing:
* 5.1.6 - works as expected
* 5.2.0 - creates duplicate nested record
* 5.2.1 - creates duplicate nested record
* rails master - creates duplicate nested record

Gist tests each of the above in a random order (with the same results)
https://gist.github.com/abrom/e9ff2cda1676d749677e31af7af604c6

### Expected behavior
With the following models:
```
class Foo < ActiveRecord::Base
  has_many :bars
  accepts_nested_attributes_for :bars
end

class Bar < ActiveRecord::Base
  belongs_to :foo
end
```

expect the following to create one `Foo` and one `Bar` record:
```
Foo.create_with(
  bars_attributes: [{ bar_name: 'bar_test' }]
).find_or_create_by!(
  foo_name: 'foo_test'
)
```

### Actual behavior
Rails 5.1.6 (as expected) creates one `Foo` and one `Bar` record:
```
Foo Load (0.2ms)  SELECT  "foos".* FROM "foos" WHERE "foos"."foo_name" = ? LIMIT ?  [["foo_name", "foo_test"], ["LIMIT", 1]]
 (0.1ms)  begin transaction
SQL (0.3ms)  INSERT INTO "foos" ("foo_name") VALUES (?)  [["foo_name", "foo_test"]]
SQL (0.1ms)  INSERT INTO "bars" ("bar_name", "foo_id") VALUES (?, ?)  [["bar_name", "bar_test"], ["foo_id", 2]]
 (0.6ms)  commit transaction
```

Rails >= 5.2 creates one `Foo` but *TWO* `Bar` records
```
Foo Load (0.2ms)  SELECT  "foos".* FROM "foos" WHERE "foos"."foo_name" = ? LIMIT ?  [["foo_name", "foo_test"], ["LIMIT", 1]]
 (0.0ms)  begin transaction
Foo Create (0.4ms)  INSERT INTO "foos" ("foo_name") VALUES (?)  [["foo_name", "foo_test"]]
Bar Create (0.1ms)  INSERT INTO "bars" ("bar_name", "foo_id") VALUES (?, ?)  [["bar_name", "bar_test"], ["foo_id", 3]]
Bar Create (0.0ms)  INSERT INTO "bars" ("bar_name", "foo_id") VALUES (?, ?)  [["bar_name", "bar_test"], ["foo_id", 3]]
 (0.7ms)  commit transaction
```

Also note, if two nested bar attributes are provided, 4 records are created etc. 

### System configuration
**Rails version**:
Various - see above

**Ruby version**:
Tested with Ruby 2.4.4 and 2.5.0

**Comment by mapeveri** [comment]
From what I understand the problem is here: https://github.com/rails/rails/blob/c83e30da27eafde79164ecb376e8a28ccc8d841f/activerecord/lib/active_record/relation.rb#L553 although I do not understand why it comes twice, one with attributes and another with empty attribute parameters.

With this code:

```
def scope_for_create(attributes = nil)
      if attributes
        scope = where_values_hash.merge!(create_with_value.stringify_keys)
        scope.merge!(attributes)
      else
        scope = where_values_hash
      end

      scope
    end
```

The example is fixed, but this not it's ok. The other tests failed :(

**Comment by darwin67** [comment]
@mapeveri oh sorry, i should have mentioned but i was already looking into this.

**Comment by mapeveri** [comment]
@darwin67 No problem, there I am seeing the PR as you fixed it, super interesting. Would you recommend some other issue to begin with? Thanks!
