### ISSUE TITLE
First load in dev environment is extremely slow after upgrading from Rails 5.1 -> 5.2.1

### ISSUE THREAD

**Issue by allaud** [rails/rails#33628]
### Steps to reproduce

Just upgraded Rails and its dependencies from 5.1.0 to 5.2.1. I see the first page load is extremely slow (takes more than 10 minutes). And after that everything works fine and fast enough. 

My Gemfile: https://gist.github.com/allaud/c60788ba96323be4eb50cc86aad22df6
Gemfile.lock: https://gist.github.com/allaud/5deb0d677a33dfbad66d261ad13c751d
Console when it hangs: https://gist.github.com/allaud/f785fc7baf8fc712f8e15790ba1b5f79

### Expected behavior
Page loads in ~1-2 seconds

### Actual behavior
Page loads more then 10 minutes (after the first load all pages load fast enough)

### System configuration
**Rails version**: 5.2.1 

**Ruby version**: ruby 2.4.2p198 (2017-09-14 revision 59899) [x86_64-darwin17]

**Comment by rafaelfranca** [comment]
Can you please provide a sample application that reproduces the error?
