### ISSUE TITLE
Aws::S3::Errors::InvalidRange exception while saving ActiveStorage model with attached 0-byte length file

### ISSUE THREAD

**Issue by denisahearn** [rails/rails#33630]
I have a Rails app that is using ActiveStorage direct upload to upload files to Amazon S3.  If a 0-byte length file is uploaded, the saving of the ActiveStorage model (i.e. has the `has_attached` association) raises an "Aws::S3::Errors::InvalidRange (The requested range is not satisfiable)" exception.  

### Steps to reproduce

Sample Rails app demonstrating the issue is attached. Before running, make sure to add your AWS credentials to config/storage.yml.

Run the sample Rails app. Default page is a "Posts" page listing posts in the database.
Click the "New Post" link.
Enter a title, body, and choose a 0-byte length file.
Click the"Create Post" button
The file is correctly uploaded to S3, and the form is correctly posted to the Rails server, however the following exception happens while saving the ActiveStorage model instance:

```
Aws::S3::Errors::InvalidRange (The requested range is not satisfiable):

app/controllers/posts_controller.rb:36:in `block in create'
app/controllers/posts_controller.rb:35:in `create'
```
### Expected behavior
The ActiveStorage model instance should get saved to the database, and no exception should be raised.

### Actual behavior
The ActiveStorage model instance is not saved to the database. A "Aws::S3::Errors::InvalidRange (The requested range is not satisfiable)" is raised during the saving of the instance.

### System configuration
**Rails version**: Rails 5.2.1

**Ruby version**: ruby 2.4.1p111 (2017-03-22 revision 58053) [x86_64-darwin17]

[direct_upload.zip](https://github.com/rails/rails/files/2293867/direct_upload.zip)

**Comment by SampsonCrowley** [comment]
Why wouldn't this be the expected behavior? What's the use case for uploading a completely empty file?

**Comment by denisahearn** [comment]
Use Case: Someone wants to upload a light-weight semaphore file to S3 that another process detects and acts upon.

This was partially fixed in https://github.com/rails/rails/issues/33450 (and released in Rails 5.2.1). I'm just looking for a complete fix.

**Comment by marceloperini** [comment]
The error is coming from line [43](https://github.com/rails/rails/blob/fc5dd0b85189811062c85520fd70de8389b55aeb/activestorage/lib/active_storage/service/s3_service.rb#L43) of the `activestorage/lib/active_storage/service/s3_service.rb` file, this use the `aws-sdk-core` gem. I am trying to figure out why the method is behaving this way, considering that sending a non 0-byte file, the `range` parameter has the same value.

**Comment by janko-m** [comment]
It's probably coming from `ActiveStorage::Blob::Identifiable#download_identifiable_chunk`, which downloads a fixed size: https://github.com/rails/rails/blob/53eea40d354dafbeda1703aa0e4b4a688bc26017/activestorage/app/models/active_storage/blob/identifiable.rb#L17-L19

This then makes a download request with `range: "bytes=0-4096"`, which blows up with `Aws::S3::Errors::InvalidRange` when the file is smaller than 4KB due to bytes being requested which don't exist. This includes empty files.

**Comment by bogdanvlviv** [comment]
It was fixed by https://github.com/rails/rails/pull/33795. Could you please close this issue?

**Comment by janko-m** [comment]
The fix seems to apply only for 0B files, it seems that files smaller than 4KB will still exhibit the same exception. But technically it solves this particular issue.

**Comment by bogdanvlviv** [comment]
@janko-m It probably should fix that case?
```diff
diff --git a/activestorage/app/models/active_storage/blob/identifiable.rb b/activestorage/app/models/active_storage/blob/identifiable.rb
index 2c17ddc25f..fadc2dcab4 100644
--- a/activestorage/app/models/active_storage/blob/identifiable.rb
+++ b/activestorage/app/models/active_storage/blob/identifiable.rb
@@ -15,10 +15,10 @@ def identify_content_type
     end

     def download_identifiable_chunk
-      if byte_size.positive?
-        service.download_chunk key, 0...4.kilobytes
-      else
-        ""
-      end
+        bytes = 4.kilobytes
+
+        bytes = byte_size if bytes > byte_size
+
+        service.download_chunk key, 0...bytes
     end
 end

```

**Comment by marceloperini** [comment]
@bogdanvlviv I think this was not work either.

This solve the problem:

``` ruby
def download_identifiable_chunk
  if byte_size > 4.kilobytes
    service.download_chunk key, 0...4.kilobytes
  else
    ""
  end
end
```

What do you think? I can submit another pull request containing this fix.

**Comment by marceloperini** [comment]
@denisahearn can you check if this issue persists in the `5-2-stable` branch?

**Comment by denisahearn** [comment]
@marceloperini The issue I was experiencing no longer happens for me with the `5-2-stable` branch. I am now able to upload a 0 byte file to S3, and the associated ActiveStorage records are getting created correctly in the database.

**Comment by marceloperini** [comment]
@denisahearn can you test it for us? Can you try upload a file that has a size smaller than 4KB and bigger than 0bytes? If you can upload this, you could close this issue, please? Otherwise, let us know here, that I'll try to work around the problem.

**Comment by marceloperini** [comment]
@denisahearn did you get tested?

**Comment by denisahearn** [comment]
@marceloperini Sorry about the slow reply.  I just tested the `5-2-stable` branch with a file that is 36 bytes in size, and it uploaded correctly to S3, and was saved to the database correctly as well.  Looks good!  I will close this issue as instructed.
