### ISSUE TITLE
When true is sent to an integer column, it is registered as 1

### ISSUE THREAD

**Issue by keitaro-shimoji** [rails/rails#33641]
Sorry. I can't English.

### Steps to reproduce
POST

```
# request json

{
  "user_name": "test",
  "age": true
}
```

### Expected behavior
400 Error

### Actual behavior
201 Created

```
# response json

{
  "user_name": "test",
  "age": 1
}
```

### System configuration
**Rails version**: 5.0.1

**Ruby version**: 2.3.1

**Comment by y-yagi** [comment]
Please use the [mailing list](https://groups.google.com/forum/#!forum/rubyonrails-talk) or StackOverflow for questions/help, where a wider community will be able to help you. We reserve the issues tracker for issues only. Thanks!
