### ISSUE TITLE
Asset Precompile not properly translating every function call to obfuscated name

### ISSUE THREAD

**Issue by frank184** [rails/rails#33642]
### Steps to reproduce

Not sure how to reproduce this error, hoping that someone a bit more knowledgable can help guide me to re-creating the issue.

### Expected behavior
I expect all minified and obfuscated variables to be called throughout my compiled JS.

### Actual behavior
One of my JS functions is being minified and obfuscated, but later is still calling in an un-minified un-obfuscated manner.

![screen shot 2018-08-17 at 9 56 18 am](https://user-images.githubusercontent.com/10104314/44269941-f5f6e480-a203-11e8-8c2e-b0fbfb086904.png)

![screen shot 2018-08-17 at 9 56 29 am](https://user-images.githubusercontent.com/10104314/44269949-fa230200-a203-11e8-9c46-a1d3d3da7864.png)

### System configuration
**Rails version**:
Rails 5.2
**Ruby version**:
2.3.7p456

**Comment by y-yagi** [comment]
Please report with reproducing steps. Without it, we can not support anything. 
Alternatively, please use the [mailing list](https://groups.google.com/forum/#!forum/rubyonrails-talk) or StackOverflow for questions/help, where a wider community will be able to help you. Thanks!

**Comment by frank184** [comment]
I'll do my best to get some kind of repo together to reproduce the issue.

For now I've gotten away with adding another `window.CookieAccessInfo` definition, since we are now planning to rework/redesign this part of the app anyways.

I should have mentioned that this came about during Rails migration from 4.2 to 5.2.
And that the said assets would precompile properly on 4.2.
