### ISSUE TITLE
localhost/%C0 generates BadRequest (Maybe because of non UTF-8 characters in the url?)

### ISSUE THREAD

**Issue by nadavb** [rails/rails#33665]
localhost/%C0 generates BadRequest (Maybe because of non UTF-8 characters in the url?)

**Rails version**:
4.0.2
**Ruby version**:
2.2.7

Even when I try to catch-all, it doesn't help:

`match '*path' => 'application#raise_not_found!', via: :all`

It should be very simple, yet I can see the solution no where.

**Comment by y-yagi** [comment]
4.0 series are not supported anymore. 
Please check whether the issue can be reproduced with the latest Rails. If you can reproduce, feel free to reopen the issue. Thanks!

**Comment by nadavb** [comment]
Well, I invested two hours to upgrade my localhost version from 4->5, and still got the same error:

`ActionController::BadRequest in ApplicationController#raise_not_found!`

```
actionpack (5.0.0) lib/action_dispatch/http/request.rb:75:in `block in check_path_parameters!'
actionpack (5.0.0) lib/action_dispatch/http/request.rb:72:in `each'
actionpack (5.0.0) lib/action_dispatch/http/request.rb:72:in `check_path_parameters!'
actionpack (5.0.0) lib/action_dispatch/http/request.rb:86:in `controller_class'
actionpack (5.0.0) lib/action_dispatch/routing/route_set.rb:44:in `controller'
actionpack (5.0.0) lib/action_dispatch/routing/route_set.rb:30:in `serve'
actionpack (5.0.0) lib/action_dispatch/journey/router.rb:39:in `block in serve'
actionpack (5.0.0) lib/action_dispatch/journey/router.rb:26:in `each'
actionpack (5.0.0) lib/action_dispatch/journey/router.rb:26:in `serve'
actionpack (5.0.0) lib/action_dispatch/routing/route_set.rb:725:in `call'
```

How do I reopen without create a new issue?
