### ISSUE TITLE
rails generate migration and model not handling singular names correctly

### ISSUE THREAD

**Issue by justcald** [rails/rails#33676]
### Steps to reproduce
I was having issues when attempting to create a migration and getting the model to point to the correct table. For some reason rails thinks `pmta` is plural..

Because at first I thought it was just a model issue I attempted creating a mode using the `rails generate model` tool. I got back some funny results:

```
$ rails generate model TestingPmta
[WARNING] The model name 'TestingPmta' was recognized as a plural, using the singular 'TestingPmtum' instead. 
Override with --force-plural or setup custom inflection rules for this noun before running the generator.
```

Obviously that isn't plural, so I wanted to see what would happen if I attempted to actually make a model that was plural and see what I'd get. 

This is what I got:
```
$ rails generate model TestingPmtas
[WARNING] The model name 'TestingPmtas' was recognized as a plural, using the singular 'TestingPmta' instead. 
Override with --force-plural or setup custom inflection rules for this noun before running the generator.
```

### Expected behavior
I expect that something ending with an `a` to not be recognized as plural. 
Also, if I do end up putting in a plural model name i don't expect it to change it to the same thing I originally attempted but got a plural warning for. 

### Actual behavior
Rails thought `TestingPmta` was plural, so it changed it to this: `TestingPmtum`
Rails correctly recognized `TestingPmtas` as plural, but it changed it back to my original attempt which was `TestingPmta`, even though that didn't originally work. 

### System configuration
**Rails version**: 5.1.5

**Ruby version**: ruby 2.4.1

**Comment by rafaelfranca** [comment]
It is because anything that ends with `ta` rails thinks it is a plural https://github.com/rails/rails/blob/c03dde6117ed995d1ada57736b5b0d44dfe31ed5/activesupport/lib/active_support/inflections.rb#L38.

Unfortunately we can't change that rule without breaking other applications so you will have to define your own rules in your application.
