### ISSUE TITLE
ActiveRecord::Base#dup does not clear memoized GlobalID

### ISSUE THREAD

**Issue by bradleybuda** [rails/rails#33679]
### Steps to reproduce

```ruby
require 'test_helper'

class PostTest < ActiveSupport::TestCase
  test "ActiveRecord dup should not have same global id as source" do
    post = Post.create!
    post_gid = post.to_global_id # memoization happens here

    dup_post = post.dup
    dup_post = post.save!
    dup_post_gid = dup_post.to_global_id

    assert_not_equal post.id, dup_post.id, 'Assertion passes: ActiveRecord clears the model id on dup'
    assert_not_equal post_gid, dup_post_gid, 'Assertion fails: to_global_id is memoized and not cleared on dup'
  end
end
```

### Expected behavior
`post` and `dup_of_post` should have different values for `to_global_id`, but they both have same GlobalID.

### Why it's happening / how to fix

`GlobalID::Identification#to_global_id` [memoizes](https://github.com/rails/globalid/blob/master/lib/global_id/identification.rb#L8) the computed ID. `ActiveRecord::Core#dup` [does not clear it](https://github.com/rails/rails/blob/master/activerecord/lib/active_record/core.rb#L396) (though it does clear some other ivars).

I was about to submit a patch but it's not clear to me if this should be fixed in GlobalID or ActiveRecord. I can think of three ways to fix it (in rough preference order):
1. Remove the memoization. This was [previously done](https://github.com/rails/globalid/commit/67a2b76e03345b7a68ef5fee91e815de49e0bed7) for `to_signed_global_id`.
2. Implement `dup` in `GlobalID::Identification` and have it clear the memoized ivar then call `super`. Need some testing to make sure AR's `dup` and GlobalID's `dup` compose correctly, but it should be doable.
3. Clear `@global_id` in `ActiveRecord::Core#dup`. This is very straightforward but creates a difficult-to-maintain coupling between the two libraries.

I'm happy to send a PR if the Rails team can give me some guidance on the best approach here.

### System configuration
**Rails version**: master
**GlobalID version**: master

I initially ran into this bug on Rails 5.2.1 - the relevant GlobalID code has been in place for 3 years, so this bug likely exists on many Rails versions.

**Comment by y-yagi** [comment]
Thanks for your report.  I think it is good to remove the memoization. Can you send a PR?
(I think that there are opinions of other maintainers. Let discuss with a PR)

**Comment by rafaelfranca** [comment]
We can keep the memoization too and in the `GlobalID::Identification` module implement a `initialize_dup` that set the instance variables to `nil` and call `super`.

**Comment by bradleybuda** [comment]
Opened a PR on GlobalID here: https://github.com/rails/globalid/pull/109
