### ISSUE TITLE
ActiveStorage methods should be defined in a parent module to provide consistent overwriting behavior

### ISSUE THREAD

**Issue by ahharvey** [rails/rails#33690]
ActiveStorage helpers (e.g., `has_one_attached :avatar`) mix certain methods into the parent model. 

When customizing/ overwriting these methods, the fallback behavior is not as expected. The following fails because `avatar=` is not defined on a super class.

```
class User 
  has_one_attached :avatar
  def avatar=(attachable)
    #my custom actions
    super(attachable)
  end
end
```

While there are ways around this, this behavior is not consistent with other parts of Rails. 

Is this by design, or is it an issue that could be addressed by a PR?

**Comment by georgeclaghorn** [comment]
This is fixed in master (#32921).
