### ISSUE TITLE
Cant start rails server on debian OS !

### ISSUE THREAD

**Issue by abdolrhman** [rails/rails#33699]
### System configuration
**Rails version**:
Rails 5.2.1
**Ruby version**:
ruby 2.5.1p57 (2018-03-29 revision 63029) [x86_64-linux-gnu]
-------------------------
am using debian , an Opration system called Parrot
i instaleed every thing working fine , 
when i run

> starting rails s

 
giving me this dam error 

> └──╼ #bin/rails server
> => Booting Puma
> => Rails 5.2.1 application starting in development 
> => Run `rails server -h` for more startup options
> /usr/lib/ruby/vendor_ruby/rack/mime.rb:54: warning: already initialized constant Rack::Mime::MIME_TYPES
> /usr/local/rvm/gems/ruby-2.5.1/gems/rack-2.0.5/lib/rack/mime.rb:49: warning: previous definition of MIME_TYPES was here
> /usr/lib/ruby/vendor_ruby/rack/file.rb:15: warning: already initialized constant Rack::File::ALLOWED_VERBS
> /usr/local/rvm/gems/ruby-2.5.1/gems/rack-2.0.5/lib/rack/file.rb:17: warning: previous definition of ALLOWED_VERBS was here
> /usr/lib/ruby/vendor_ruby/rack/file.rb:16: warning: already initialized constant Rack::File::ALLOW_HEADER
> /usr/local/rvm/gems/ruby-2.5.1/gems/rack-2.0.5/lib/rack/file.rb:18: warning: previous definition of ALLOW_HEADER was here
> /usr/lib/ruby/vendor_ruby/rack/response.rb:23: warning: already initialized constant Rack::Response::CHUNKED
> /usr/local/rvm/gems/ruby-2.5.1/gems/rack-2.0.5/lib/rack/response.rb:26: warning: previous definition of CHUNKED was here
> Exiting
> Traceback (most recent call last):
> 	78: from bin/rails:4:in `<main>'
> 	77: from /usr/local/rvm/gems/ruby-2.5.1/gems/bootsnap-1.3.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:29:in `require'
> 	76: from /usr/local/rvm/gems/ruby-2.5.1/gems/bootsnap-1.3.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:20:in `require_with_bootsnap_lfi'
> 	75: from /usr/local/rvm/gems/ruby-2.5.1/gems/bootsnap-1.3.1/lib/bootsnap/load_path_cache/loaded_features_index.rb:65:in `register'
> 	74: from /usr/local/rvm/gems/ruby-2.5.1/gems/bootsnap-1.3.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `block in require_with_bootsnap_lfi'
> 	73: from /usr/local/rvm/gems/ruby-2.5.1/gems/bootsnap-1.3.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `require'
> 	72: from /usr/local/rvm/gems/ruby-2.5.1/gems/railties-5.2.1/lib/rails/commands.rb:18:in `<main>'
> 	71: from /usr/local/rvm/gems/ruby-2.5.1/gems/railties-5.2.1/lib/rails/command.rb:46:in `invoke'
> 	70: from /usr/local/rvm/gems/ruby-2.5.1/gems/railties-5.2.1/lib/rails/command/base.rb:65:in `perform'
> 	69: from /usr/local/rvm/gems/ruby-2.5.1/gems/thor-0.20.0/lib/thor.rb:387:in `dispatch'
> 	68: from /usr/local/rvm/gems/ruby-2.5.1/gems/thor-0.20.0/lib/thor/invocation.rb:126:in `invoke_command'
> 	67: from /usr/local/rvm/gems/ruby-2.5.1/gems/thor-0.20.0/lib/thor/command.rb:27:in `run'
> 	66: from /usr/local/rvm/gems/ruby-2.5.1/gems/railties-5.2.1/lib/rails/commands/server/server_command.rb:142:in `perform'
> 	65: from /usr/local/rvm/gems/ruby-2.5.1/gems/railties-5.2.1/lib/rails/commands/server/server_command.rb:142:in `tap'
> 	64: from /usr/local/rvm/gems/ruby-2.5.1/gems/railties-5.2.1/lib/rails/commands/server/server_command.rb:147:in `block in perform'
> 	63: from /usr/local/rvm/gems/ruby-2.5.1/gems/railties-5.2.1/lib/rails/commands/server/server_command.rb:51:in `start'
> 	62: from /usr/local/rvm/gems/ruby-2.5.1/gems/railties-5.2.1/lib/rails/commands/server/server_command.rb:89:in `log_to_stdout'
> 	61: from /usr/local/rvm/gems/ruby-2.5.1/gems/rack-2.0.5/lib/rack/server.rb:354:in `wrapped_app'
> 	60: from /usr/local/rvm/gems/ruby-2.5.1/gems/railties-5.2.1/lib/rails/commands/server/server_command.rb:27:in `app'
> 	59: from /usr/local/rvm/gems/ruby-2.5.1/gems/rack-2.0.5/lib/rack/server.rb:219:in `app'
> 	58: from /usr/local/rvm/gems/ruby-2.5.1/gems/rack-2.0.5/lib/rack/server.rb:319:in `build_app_and_options_from_config'
> 	57: from /usr/local/rvm/gems/ruby-2.5.1/gems/rack-2.0.5/lib/rack/builder.rb:40:in `parse_file'
> 	56: from /usr/local/rvm/gems/ruby-2.5.1/gems/rack-2.0.5/lib/rack/builder.rb:49:in `new_from_string'
> 	55: from /usr/local/rvm/gems/ruby-2.5.1/gems/rack-2.0.5/lib/rack/builder.rb:49:in `eval'
> 	54: from config.ru:in `<main>'
> 	53: from config.ru:in `new'
> 	52: from /usr/local/rvm/gems/ruby-2.5.1/gems/rack-2.0.5/lib/rack/builder.rb:55:in `initialize'
> 	51: from /usr/local/rvm/gems/ruby-2.5.1/gems/rack-2.0.5/lib/rack/builder.rb:55:in `instance_eval'
> 	50: from config.ru:3:in `block in <main>'
> 	49: from /usr/local/rvm/gems/ruby-2.5.1/gems/bootsnap-1.3.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:44:in `require_relative'
> 	48: from /usr/local/rvm/gems/ruby-2.5.1/gems/bootsnap-1.3.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:29:in `require'
> 	47: from /usr/local/rvm/gems/ruby-2.5.1/gems/bootsnap-1.3.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:20:in `require_with_bootsnap_lfi'
> 	46: from /usr/local/rvm/gems/ruby-2.5.1/gems/bootsnap-1.3.1/lib/bootsnap/load_path_cache/loaded_features_index.rb:65:in `register'
> 	45: from /usr/local/rvm/gems/ruby-2.5.1/gems/bootsnap-1.3.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `block in require_with_bootsnap_lfi'
> 	44: from /usr/local/rvm/gems/ruby-2.5.1/gems/bootsnap-1.3.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `require'
> 	43: from /home/nasr/Documents/RubyStation/Hellot/config/environment.rb:5:in `<main>'
> 	42: from /usr/local/rvm/gems/ruby-2.5.1/gems/railties-5.2.1/lib/rails/application.rb:361:in `initialize!'
> 	41: from /usr/local/rvm/gems/ruby-2.5.1/gems/railties-5.2.1/lib/rails/initializable.rb:60:in `run_initializers'
> 	40: from /usr/lib/ruby/2.5.0/tsort.rb:205:in `tsort_each'
> 	39: from /usr/lib/ruby/2.5.0/tsort.rb:226:in `tsort_each'
> 	38: from /usr/lib/ruby/2.5.0/tsort.rb:347:in `each_strongly_connected_component'
> 	37: from /usr/lib/ruby/2.5.0/tsort.rb:347:in `call'
> 	36: from /usr/lib/ruby/2.5.0/tsort.rb:347:in `each'
> 	35: from /usr/lib/ruby/2.5.0/tsort.rb:349:in `block in each_strongly_connected_component'
> 	34: from /usr/lib/ruby/2.5.0/tsort.rb:431:in `each_strongly_connected_component_from'
> 	33: from /usr/lib/ruby/2.5.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
> 	32: from /usr/lib/ruby/2.5.0/tsort.rb:228:in `block in tsort_each'
> 	31: from /usr/local/rvm/gems/ruby-2.5.1/gems/railties-5.2.1/lib/rails/initializable.rb:61:in `block in run_initializers'
> 	30: from /usr/local/rvm/gems/ruby-2.5.1/gems/railties-5.2.1/lib/rails/initializable.rb:32:in `run'
> 	29: from /usr/local/rvm/gems/ruby-2.5.1/gems/railties-5.2.1/lib/rails/initializable.rb:32:in `instance_exec'
> 	28: from /usr/local/rvm/gems/ruby-2.5.1/gems/railties-5.2.1/lib/rails/application/finisher.rb:47:in `block in <module:Finisher>'
> 	27: from /usr/local/rvm/gems/ruby-2.5.1/gems/railties-5.2.1/lib/rails/engine.rb:506:in `app'
> 	26: from /usr/local/rvm/gems/ruby-2.5.1/gems/railties-5.2.1/lib/rails/engine.rb:506:in `synchronize'
> 	25: from /usr/local/rvm/gems/ruby-2.5.1/gems/railties-5.2.1/lib/rails/engine.rb:508:in `block in app'
> 	24: from /usr/local/rvm/gems/ruby-2.5.1/gems/railties-5.2.1/lib/rails/application.rb:576:in `default_middleware_stack'
> 	23: from /usr/local/rvm/gems/ruby-2.5.1/gems/railties-5.2.1/lib/rails/application/default_middleware_stack.rb:15:in `build_stack'
> 	22: from /usr/local/rvm/gems/ruby-2.5.1/gems/railties-5.2.1/lib/rails/application/default_middleware_stack.rb:15:in `new'
> 	21: from /usr/local/rvm/gems/ruby-2.5.1/gems/actionpack-5.2.1/lib/action_dispatch/middleware/stack.rb:47:in `initialize'
> 	20: from /usr/local/rvm/gems/ruby-2.5.1/gems/railties-5.2.1/lib/rails/application/default_middleware_stack.rb:58:in `block in build_stack'
> 	19: from /usr/local/rvm/gems/ruby-2.5.1/gems/railties-5.2.1/lib/rails/application/configuration.rb:226:in `session_store'
> 	18: from /usr/local/rvm/gems/ruby-2.5.1/gems/railties-5.2.1/lib/rails/application/configuration.rb:226:in `const_get'
> 	17: from /usr/local/rvm/gems/ruby-2.5.1/gems/bootsnap-1.3.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:29:in `require'
> 	16: from /usr/local/rvm/gems/ruby-2.5.1/gems/bootsnap-1.3.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:20:in `require_with_bootsnap_lfi'
> 	15: from /usr/local/rvm/gems/ruby-2.5.1/gems/bootsnap-1.3.1/lib/bootsnap/load_path_cache/loaded_features_index.rb:65:in `register'
> 	14: from /usr/local/rvm/gems/ruby-2.5.1/gems/bootsnap-1.3.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `block in require_with_bootsnap_lfi'
> 	13: from /usr/local/rvm/gems/ruby-2.5.1/gems/bootsnap-1.3.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `require'
> 	12: from /usr/local/rvm/gems/ruby-2.5.1/gems/actionpack-5.2.1/lib/action_dispatch/middleware/session/cookie_store.rb:4:in `<main>'
> 	11: from /usr/local/rvm/gems/ruby-2.5.1/gems/bootsnap-1.3.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:29:in `require'
> 	10: from /usr/local/rvm/gems/ruby-2.5.1/gems/bootsnap-1.3.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:20:in `require_with_bootsnap_lfi'
> 	 9: from /usr/local/rvm/gems/ruby-2.5.1/gems/bootsnap-1.3.1/lib/bootsnap/load_path_cache/loaded_features_index.rb:65:in `register'
> 	 8: from /usr/local/rvm/gems/ruby-2.5.1/gems/bootsnap-1.3.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `block in require_with_bootsnap_lfi'
> 	 7: from /usr/local/rvm/gems/ruby-2.5.1/gems/bootsnap-1.3.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `require'
> 	 6: from /usr/local/rvm/gems/ruby-2.5.1/gems/actionpack-5.2.1/lib/action_dispatch/middleware/session/abstract_store.rb:9:in `<main>'
> 	 5: from /usr/local/rvm/gems/ruby-2.5.1/gems/actionpack-5.2.1/lib/action_dispatch/middleware/session/abstract_store.rb:10:in `<module:ActionDispatch>'
> 	 4: from /usr/local/rvm/gems/ruby-2.5.1/gems/actionpack-5.2.1/lib/action_dispatch/middleware/session/abstract_store.rb:80:in `<module:Session>'
> 	 3: from /usr/local/rvm/gems/ruby-2.5.1/gems/bootsnap-1.3.1/lib/bootsnap/load_path_cache/core_ext/active_support.rb:42:in `load_missing_constant'
> 	 2: from /usr/local/rvm/gems/ruby-2.5.1/gems/bootsnap-1.3.1/lib/bootsnap/load_path_cache/core_ext/active_support.rb:53:in `rescue in load_missing_constant'
> 	 1: from /usr/local/rvm/gems/ruby-2.5.1/gems/bootsnap-1.3.1/lib/bootsnap/load_path_cache/core_ext/active_support.rb:8:in `without_bootsnap_cache'
> /usr/local/rvm/gems/ruby-2.5.1/gems/bootsnap-1.3.1/lib/bootsnap/load_path_cache/core_ext/active_support.rb:53:in `block in load_missing_constant': uninitialized constant Rack::Session::Abstract::Persisted (NameError)
> 

any Help is apperciated

**Comment by rafaelfranca** [comment]
Can you please provide a sample application that reproduces the error?

**Comment by abdolrhman** [comment]
@rafaelfranca  i have find solution, the system already have ruby , then i installed rvm with its own ruby , so the system was ready the one which is not related with rvm , 
what i did , is purge ruby , and they use the one that rvm give it to me . 
thanks man :)
