### ISSUE TITLE
Why mark_for_destruction sent to each member of a has_many relation doesn't work?

### ISSUE THREAD

**Issue by wladymirputout** [rails/rails#33707]
### Steps to reproduce

```
# frozen_string_literal: true

begin
  require "bundler/inline"
rescue LoadError => e
  $stderr.puts "Bundler version 1.10 or later is required. Please update your Bundler"
  raise e
end

gemfile(true) do
  source "https://rubygems.org"

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  gem "rails", github: "rails/rails", branch: "5-2-stable"
  gem "sqlite3"
end

require "active_record"
require "minitest/autorun"
require "logger"

# This connection will do for database-independent bug reports.
ActiveRecord::Base.establish_connection(adapter: "sqlite3", database: ":memory:")
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :posts, force: true do |t|
  end

  create_table :comments, force: true do |t|
    t.integer :post_id
    t.boolean :status, null: false, default: true
  end
end

class Post < ActiveRecord::Base
  has_many :comments, autosave: true
end

class Comment < ActiveRecord::Base
  belongs_to :post
end

class BugTest < Minitest::Test
  def setup
    @post = Post.create!
    2.times { @post.comments.create! }
  end

  def teardown
    Post.destroy_all
    Comment.destroy_all
  end

  def test_each
    @post.comments.each(&:mark_for_destruction)
    @post.save!
    assert_equal(0, Comment.count)
  end

  def test_where_each
    @post.comments.where(status: true).each(&:mark_for_destruction)
    @post.save!
    assert_equal(0, Comment.count)
  end

  def test_where_find_each
    @post.comments.where(status: true).find_each(&:mark_for_destruction)
    @post.save!
    assert_equal(0, Comment.count)
  end

  def test_where_not_each
    @post.comments.where.not(status: false).each(&:mark_for_destruction)
    @post.save!
    assert_equal(0, Comment.count)
  end
end
```

### Expected behavior
If `@post.comments.each(&:mark_for_destruction)` works perfectly why am I not able to `@post.comments.where(status: true).each(&:mark_for_destruction)` successfully?

### Actual behavior
After the post being saved the objects marked for destruction using a where clause aren't deleted.

### System configuration
**Rails version**: 5.2.1
**Ruby version**: ruby 2.5.0p0 (2017-12-25 revision 61468) [x86_64-darwin17]

**Comment by y-yagi** [comment]
`where` returns a new relation. So you need to reset relations as follows. 

```ruby 
@post.comments = @post.comments.where(status: true).each(&:mark_for_destruction)
@post.save!
assert_equal(0, Comment.count)
```

**Comment by khamusa** [comment]
Just to note that the provided solution will completely clear all comments from post. You're assigning a new array to the collection, so the [default Rails behavior](https://guides.rubyonrails.org/association_basics.html#methods-added-by-has-many-collection-objects) for `collection=` will kick in.

If you want to mark for destruction only the ones where status is true, leaving others untouched, and rely on the @post.save! transaction to do the actual persistence, you should make sure you load the AR association and operate in memory:

```
@post.comments = @post.comments.select(&:status).each(&:mark_for_destruction)
@post.save!
```

Which you may not want to do considering you're handling comments on a post, so they can be numerous. A better solution would be to just `.destroy_all` on the filtered scope and find a way around the fact `@posts.comments` may need to be reloaded.
