### ISSUE TITLE
"where" statement with large array - regression in 5.2 and master

### ISSUE THREAD

**Issue by Mik-die** [rails/rails#33702]
### Steps to reproduce

The below test is failing in master, or "5.2.1" branch, but passes in "5.1.6"

```
begin
  require "bundler/inline"
rescue LoadError => e
  $stderr.puts "Bundler version 1.10 or later is required. Please update your Bundler"
  raise e
end

gemfile(true) do
  source "https://rubygems.org"
  gem 'rails', github: 'rails/rails'
  gem 'arel', github: 'rails/arel'
  # Activate the gem you are reporting the issue against.
  # gem "activerecord", "5.2.1"
  # gem "activerecord", "5.1.6"
  gem 'sqlite3'
end

require "active_record"
require "minitest/autorun"
require "logger"

# Ensure backward compatibility with Minitest 4
Minitest::Test = MiniTest::Unit::TestCase unless defined?(Minitest::Test)

# This connection will do for database-independent bug reports.
ActiveRecord::Base.establish_connection(adapter: "sqlite3", database: ":memory:")
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :authors, force: true do |t|
  end
end

class Author < ActiveRecord::Base
end

class BugTest < Minitest::Test
  def test_large_where
    Author.create!
    # PG::UnableToSend: number of parameters must be between 0 and 65535
    # SQLite3::SQLException: too many SQL variables
    assert Author.where(id: (0..250_000).to_a).to_a
  end
end
```

### Expected behavior

For 250_000 array elements, prepared statements are not used, as we could get `PG::UnableToSend: number of parameters must be between 0 and 65535`, or `SQLite3::SQLException: too many SQL variables` (not tested against MySql). 

### Actual behavior

In 5.1.6, it generates SQL `SELECT "authors".* FROM "authors" WHERE "authors"."id" IN (0, 1, 2 ... 249999, 250000)`, as expected.

In 5.2.1 and current master, it generates `SELECT "authors".* FROM "authors" WHERE "authors"."id" IN (?, ? ... ?, ?)  [["id", 0], ["id", 1] ... ["id", 249999], ["id", 250000]]` which cause `SQLite3::SQLException: too many SQL variables` (or `PG::UnableToSend: number of parameters must be between 0 and 65535` as I faced on my application even against less number of elements)

### System configuration
**Rails version**: 5.2.1

**Ruby version**: 2.5.0

**Postgresql version**: 10.4

**SQLite version**: 3.16.0

**Comment by tgturner** [comment]
It looks like this is the commit that introduced this behavior https://github.com/rails/rails/commit/213796fb4936dce1da2f0c097a054e1af5c25c2c

**Comment by rafaelfranca** [comment]
Rail is doing the right thing. If you want to run those queries without prepared statements you can use `unprepared_statement` around your query.

**Comment by dzohrob** [comment]
@rafaelfranca I know this is already closed, but I'm running into this quite often and having to work around it, so I figured I'd put in one vote for potentially changing the behavior.

It seems strange to put the responsibility on the _caller_ to figure out whether the parameters passed in might exceed the limit of the underlying DB... it feels like exactly the kind of logic that ActiveRecord could handle transparently.

Thanks for taking a look & for your great work on Rails.

**Comment by grokse** [comment]
I've also run into this when using includes.

```
class CreateFoo < ActiveRecord::Migration[5.2]
  def change
    create_table :foos do |t|
      t.belongs_to :bar
    end
  end
end

class CreateBar < ActiveRecord::Migration[5.2]
  def change
    create_table :bars do |t|
    end
  end
end

class Foo < ActiveRecord::Base
  belongs_to :bar
end

class Bar < ActiveRecord::Base; end

65536.times { Foo.create bar: Bar.new }

Foo.includes(:bar).index_by(&:id)
# => ActiveRecord::StatementInvalid
```
