### ISSUE TITLE
SystemTest Transaction not working

### ISSUE THREAD

**Issue by lazaronixon** [rails/rails#33711]
### Steps to reproduce
```
require "application_system_test_case"

class RootTest < ApplicationSystemTestCase

  setup { sign_in_as users(:lazaronixon) }

  test "running test 1" do
    services(:ivan).update!(removed_at: Time.current)
    visit planning_url(plannings(:one))

    assert_selector "[data-removed-service='#{services(:ivan).id}']", visible: false
  end

  test "running test 2" do
    visit planning_url(plannings(:one))

    assert_no_selector "[data-removed-service='#{services(:ivan).id}']", visible: false
  end

end
```

### Expected behavior
All tests should be success runing RootTest or one test per time.

### Actual behavior
I have a list of removed services from same planning, Planning fixture dont have any removed, so i usually mutate it using update, seems that test is not handling rollback after first test. If I run it separally it works.

### System configuration
**Rails version**: 5.2.1

**Ruby version**: 2.5.1

**Comment by y-yagi** [comment]
Can you provide the entire application that reproduces the error, not the test alone?

**Comment by lazaronixon** [comment]
I found the error. It was related to:
```
  def show
    fresh_when etag: @planning
  end
```
How clear cache between system tests?
I tried  but didnt works
```
teardown { Rails.cache.clear }
```

**Comment by rafaelfranca** [comment]
Please use the mailing list or StackOverflow for questions/help, where a wider community will be able to help you. We reserve the issues tracker for issues only.
