### ISSUE TITLE
ActiveRecord: do not include order sql when running counts

### ISSUE THREAD

**Issue by grosser** [rails/rails#33719]
### Steps to reproduce

This query cannot be paginated since counting it includes ordering :(

```
scope = Project.select('projects.*, count(commands.id) as command_count').joins(:build_command).group('projects.id').order('command_count desc')

# SELECT  projects.*, count(commands.id) as command_count FROM `projects` INNER JOIN `commands` ON `commands`.`id` = `projects`.`build_command_id` WHERE `projects`.`deleted_at` IS NULL GROUP BY projects.id ORDER BY command_count desc LIMIT 1
scope.first

# ActiveRecord::StatementInvalid (Mysql2::Error: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '*, count(commands.id) as command_count) AS count_projects_all_count_commands_id_' at line 1: SELECT COUNT(projects.*, count(commands.id) as command_count) AS count_projects_all_count_commands_id_as_command_count, projects.id AS projects_id FROM `projects` INNER JOIN `commands` ON `commands`.`id` = `projects`.`build_command_id` WHERE `projects`.`deleted_at` IS NULL GROUP BY projects.id ORDER BY command_count desc)
scope.count
```

Expected behavior: `.reorder(nil)` is automatically applied when trying to count things

### System configuration
**Rails version**: 5.2.1

**Ruby version**: 2.5.1

**Comment by vbrazo** [comment]
You're right. `.count` doesn't seem to work. Have you tried [`scope.length`](https://github.com/rails/rails/blob/master/activerecord/lib/active_record/result.rb#L52)?

**Comment by grosser** [comment]
.length would load all the records ... that won't work for pagination :)

**Comment by darren987469** [comment]
Does `scope.reorder(nil).count` work? I tried with postgres and it failed.

You can still get project count with `Project.joins(:build_command).count`.

**Comment by grosser** [comment]
I'm trying to pass a scope to pagination, so .count + .all have to both
work on it.
I know there are workarounds, I'm saying the default should not include
ordering since ordering for counting makes no sense.

**Comment by kamipo** [comment]
At least removing ordering when using `group` is a breaking change.

**Comment by grosser** [comment]
since it's counting, how would that change the result ?
maybe with a complicated count that counts where `x=1` + order `x desc` so without ordering x would be different ?

**Comment by kamipo** [comment]
An aggregation method with `group` returns a result like `{ group1 => result1, group2 => result2 }` and it is ordered by the SQL.

https://github.com/rails/rails/blob/b2eb1d1c55a59fee1e6c4cba7030d8ceb524267c/activerecord/test/cases/calculations_test.rb#L720-L736

**Comment by grosser** [comment]
hmm so remove ordering when not grouping ?
... ideally there would be a `give me a count and not a hash` way of doing this to get rid of code like https://github.com/ddnexus/pagy/blob/a8ad3993d9dcd5b7c4e015a81ac3421e1f007b44/lib/pagy/backend.rb#L20 and then we could drop the order even when grouped ...

**Comment by kamipo** [comment]
> hmm so remove ordering when not grouping ?

Right, when not grouping, not limited or offset, not selected specific column.

> Project.select('projects.*, count(commands.id) as command_count').joins(:build_command).group('projects.id').order('command_count desc')

In the first place basically grouping doesn't work without an aggrigation and this query already includes the grouping column `projects.id` (in `projects.*`) and the aggrigation `count(commands.id) as command_count` in the select, it is the reason that `scope.first` works well.

Active Record basically doesn't parse the existed select then couldn't be noticed that query is already aggregated, so trying aggregation for grouping again by itself.

**Comment by rafaelfranca** [comment]
Yes, we are trying to avoid those clever detections in Active Record. Active record build the query that you asked. If you asked a count with an order it will not try to guess that a order doesn't work with count.
