### ISSUE TITLE
Precision value in Time with microsecond sometimes gets offset or inaccurate after AR is created

### ISSUE THREAD

**Issue by calvinchso** [rails/rails#33715]
### Steps to reproduce
Please use the following code to reproduce the issue. Please note the test passes in Rails 4.2.10 but fails in Rails 5.2.1.

```ruby
# frozen_string_literal: true
  
begin
  require "bundler/inline"
rescue LoadError => e
  $stderr.puts "Bundler version 1.10 or later is required. Please update your Bundler"
  raise e
end

gemfile(true) do
  source "https://rubygems.org"

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  gem "rails", '5.2.1'
  gem "sqlite3"
end

require "active_record"
require "minitest/autorun"
require "logger"

# This connection will do for database-independent bug reports.
ActiveRecord::Base.establish_connection(adapter: "sqlite3", database: ":memory:")
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :posts, force: true do |t|
    t.datetime :posted_at, precision: 6
    t.timestamps
  end
end

class Post < ActiveRecord::Base
end

class PrecisionTest < Minitest::Test
  def test_precision
    100.times do
      time_in_str = Time.now.to_f.round(6).to_s
      $stdout.puts "Creating a post record with posted_at = #{time_in_str}"
      time = Time.at(time_in_str.to_f)
      assert_equal time_in_str, time.to_f.to_s
      post = Post.create(:posted_at => time)
      assert_equal time.to_f, post.posted_at.to_f
    end
  end
end
```

### Expected behavior
Precision value in Time with microsecond should be kept accurate after AR is created.

### Actual behavior
Precision value in Time with microsecond sometimes gets offset or inaccurate after AR is created.

As you can see, the first iteration, i.e. the first two assertions with posted_at = "1535128380.190231", has passed but in the next iteration, i.e. the last two assertions with posted_at = "1535128380.203914" has failed.

Please also note that in the second iteration, the generated INSERT statement has already got the wrong precision value, i.e. "2018-08-24 16:33:00.203913" and it should be "1535128380.203914"

```
# Running:

Creating a post record with posted_at = 1535128380.190231
D, [2018-08-24T09:33:00.197604 #59993] DEBUG -- :    (0.1ms)  begin transaction
D, [2018-08-24T09:33:00.198085 #59993] DEBUG -- :   ↳ precision_test.rb:44
D, [2018-08-24T09:33:00.201193 #59993] DEBUG -- :   Post Create (0.1ms)  INSERT INTO "posts" ("posted_at", "created_at", "updated_at") VALUES (?, ?, ?)  [["posted_at", "2018-08-24 16:33:00.190231"], ["created_at", "2018-08-24 16:33:00.198468"], ["updated_at", "2018-08-24 16:33:00.198468"]]
D, [2018-08-24T09:33:00.201512 #59993] DEBUG -- :   ↳ precision_test.rb:44
D, [2018-08-24T09:33:00.202889 #59993] DEBUG -- :    (0.1ms)  commit transaction
D, [2018-08-24T09:33:00.203173 #59993] DEBUG -- :   ↳ precision_test.rb:44
Creating a post record with posted_at = 1535128380.203914
D, [2018-08-24T09:33:00.204247 #59993] DEBUG -- :    (0.0ms)  begin transaction
D, [2018-08-24T09:33:00.204535 #59993] DEBUG -- :   ↳ precision_test.rb:44
D, [2018-08-24T09:33:00.208526 #59993] DEBUG -- :   Post Create (0.2ms)  INSERT INTO "posts" ("posted_at", "created_at", "updated_at") VALUES (?, ?, ?)  [["posted_at", "2018-08-24 16:33:00.203913"], ["created_at", "2018-08-24 16:33:00.205034"], ["updated_at", "2018-08-24 16:33:00.205034"]]
D, [2018-08-24T09:33:00.208948 #59993] DEBUG -- :   ↳ precision_test.rb:44
D, [2018-08-24T09:33:00.210380 #59993] DEBUG -- :    (0.1ms)  commit transaction
D, [2018-08-24T09:33:00.210697 #59993] DEBUG -- :   ↳ precision_test.rb:44
F

Failure:
PrecisionTest#test_precision [/Users/calvin/projects/newapp/precision_test.rb:45]:
Expected: 1535128380.203914
  Actual: 1535128380.203913


bin/rails test precision_test.rb:38



Finished in 0.023380s, 42.7716 runs/s, 171.0864 assertions/s.
1 runs, 4 assertions, 1 failures, 0 errors, 0 skips
```

### System configuration
**Rails version**: 5.2.1

**Ruby version**: ruby 2.5.1p57 (2018-03-29 revision 63029) [x86_64-darwin17]

**Comment by calvinchso** [comment]
Please note the same test passes in Rails 4.2.10

**Comment by kamipo** [comment]
The truncating extra subseconds to avoid saving future time to database by rounding is the expected behavior since #18850.

See also #17239, #18067.

**Comment by calvinchso** [comment]
Thanks. In our case, we're sure the input value is already truncated at the microsecond level, and we don't want the value to be altered somehow. Is there any way / which line should we patch it if we want the expected behavior?

**Comment by why-el** [comment]
This is not really an AR problem. `to_f` will lose some precision for certain time values (as it would with any boundless fraction), and therefore your reconstruction of the value using `Time.at` will not yield the same value. 

I think there is an MR that will make the `Time.zone.at` from Rails match the signature of that of Ruby, in which case, if you already have a datetime you want to pass downstream, you can pass the usec as a second argument, so: 

` (t = Time.now) && (p = Time.at(t.to_i, t.usec)) && t == p`

should pass. 

Or pass the datetime as rational to Time.at, which will keep the desired precision.
