### ISSUE TITLE
Digest not included in rendering of asset helpers

### ISSUE THREAD

**Issue by SeanRoy** [rails/rails#33713]
I am in the process of upgrading our product from rails 4.1 to 5.2.  I'm hung up on what appears to be an asset pipeline related issue.  When I load the app in our browser, I see the following error in the server log and the app is missing all styling and javascript code that it normally has.

```
DEPRECATION WARNING: The asset application.js" is not present in the asset pipeline.Falling back to an asset that may be in the public folder.
This behavior is deprecated and will be removed.
To bypass the asset pipeline and preserve this behavior,
use the `skip_pipeline: true` option.
```

When I wget the index.html of the application, I see that all of the images and javascript urls are lacking the fingerprint digest they should have.  Interestingly enough, they do have the S3 asset_host we have, so they are in fact being processed by the helpers. 

To demonstrate, I have two servers which have identical configurations, but one is running 4.1 and the other 5.2.  On both, I am using S3 as an asset_host and digest is turned on.  I've run the following commands in their consoles:
=== Rails 4 ===
Loading qatest environment (Rails 4.1.0)
irb(main):001:0> Rails.application.config.action_controller.asset_host
=> "https://redacted.s3.amazonaws.com"
irb(main):002:0> Rails.application.config.assets.digest
=> true
irb(main):003:0>  ActionController::Base.helpers.asset_path('application.js')
=> **"https://redacted.s3.amazonaws.com/assets/application-042f2014ca329c79c304ab1332557040d3f7b922247202f40c28acc950f30ef8.js"**

=== Rails 5 ===
Loading sean environment (Rails 5.2.1)
irb(main):001:0> Rails.application.config.action_controller.asset_host
=> "https://redacted.s3.amazonaws.com"
irb(main):002:0> Rails.application.config.assets.digest
=> true
irb(main):003:0> ActionController::Base.helpers.asset_path('application.js')
=> **"https://redacted.s3.amazonaws.com/application.js"**

I've spent quite a bit of time online and poring through the upgrade manuals and release notes to see what may have been deprecated or changed and came up with similar issues, but nothing really matching mine.

**Comment by rafaelfranca** [comment]
`The asset application.js" is not present in the asset pipeline.` That is the reason. Are you sure this asset is listed on the app/assets/config/manifest.js or `Rails.application.config.assets.precompile` list?

Also,  Please use the mailing list or StackOverflow for questions/help, where a wider community will be able to help you. We reserve the issues tracker for issues only.
