### ISSUE TITLE
ActiveStorage direct uploads ActiveRecord::RecordNotUnique

### ISSUE THREAD

**Issue by zackperdue** [rails/rails#33720]
When using Active Storage direct uploads, if I select an image to upload and i've already uploaded that image, when I submit the form I get an ActiveRecord::RecordNotUnique exception.

Is there a way to translate this easily to a validation error if uploads must be unique?

OR, is there a way to remove the unique constraint from image uploads and is it safe?

**Comment by zackperdue** [comment]
Well, i've removed the unique compound index on active_storage_attachments. Will see how it goes. Would still like to hear some feedback from @dhh on this. Is this going to be configurable in the future?

**Comment by georgeclaghorn** [comment]
Can you reproduce this with latest master?

**Comment by georgeclaghorn** [comment]
I confirmed that this is fixed in master.
