### ISSUE TITLE
Eager loading for getting inheritance descendants (STI) fails under development as soon as code is refreshed.

### ISSUE THREAD

**Issue by gobijan** [rails/rails#33738]
### Steps to reproduce

I'm running Rails 5.2.1 and make use of single table inheritance.
I want to get a dynamic list of all descendants of my parent model class.

Normally I would get the descendants names like this:
    MyBaseModel.descendants.map(&:name)

In development mode it returns an empty array: []. This seems to be related to eager loading being disabled in dev.

Therefore I turned on eager loading in _development.rb_ like this:

    config.eager_load = true

Now I get the expected behaviour. 

**BUT**

As soon I make a change somewhere in the code and the hot-reloading kicks in it doesn't eager load and therefore I get the empty array again when asking for the descendants of the parent class.

### Expected behavior
Making code changes when eager loading is on should reload the whole env?

### Actual behavior
Code changes result in eager loading getting thrown away.

### System configuration
**Rails version**: 5.2.1

**Ruby version**: ruby 2.5.1p57 (2018-03-29 revision 63029) [x86_64-darwin17]

Any idea how to work around this issue? Shall one create a static list of descendant classes?

**Comment by rafaelfranca** [comment]
You don't need to create a static list but you can't rely on autoloading anymore. The only way to fix this is by using `require_relative` for the descendants like explained here https://guides.rubyonrails.org/autoloading_and_reloading_constants.html#autoloading-and-sti

**Comment by gobijan** [comment]
Thx for giving the right hint. 👍
