### ISSUE TITLE
Bizarre double transaction BEGIN, when expecting one. 

### ISSUE THREAD

**Issue by ChrisCPO** [rails/rails#33730]
### Intro
I have a stack over flow question [here](https://stackoverflow.com/questions/51937999/rails-5-1-4-psql-activerecord-is-wrapping-actions-in-their-own-transaction) that provides a good description, but I will provide an overview with a ActiveRecord dive here. 

 I have spent hours trying to track down this issue and after diving though stack-traces and digging though gems, this course has finally brought me to active record. 

### Expected behavior
Consider this simple endpoint.

```ruby
def update
  ActiveRecord::Base.transaction do
    @note = Note.last
    @note.update(text: SecureRandom.hex)
    raise
  end
end
```
One would expect the server logs to go 
```
BEGIN
UPDATE
ROLLBACK
```

### Actual behavior
Instead our server logs are going 

```
BEGIN
BEGIN
UPDATE
COMMIT
ROLLBACK
```

Naturally this is causing some data issue, on large requests VERY big data issues. However this is actually not even the weird part.

### Weird part
- This issue is present on a fresh start of a server(`rails s`), but if I edit any part of the code and rails reloads the code base the action acts as expected. 
- Also this is only happening though controllers, taking the same code block and sticking it in a resque job, it works as expected.
- calling the endpoint from the console `app.put "/note"` works as expected. 
- calling `note.update` works as expected
- rspec controller and integration tests work as expected. 
- `Note.transaction` works as expected, though double `BEGIN` is still present in logs
- `Note.last.update` works as expected, though double `BEGIN` is still present in logs

`ActiveRecord::Base.transaction` does **NOT** work as expected.

### Active Record dive
in [connection_adapters/abstract/transaction](https://github.com/rails/rails/blob/184c1a405f58b069e0b9ef79a2ad67f7d7d9e69b/activerecord/lib/active_record/connection_adapters/abstract/transaction.rb#L151)`::TransactionManger#begin_transaction` The @stack` size is always one. Now I have not poked around AR before. I noticed that each `ConnectionAdapters::DatabaseStatements` each has it's own transaction manager. 

I'm going to continue my dive from here.
Any suggestions would be very appreciated. 

Some things to note are we have replicated the issue on our staging servers(heroku) and the issue first came up on our production servers, initially thought is was a weird timeout issue. We could not directly reproduce this on a new rails app. it kinda smells like a gem is monkey patching but I just don't know, how would I even prove that, controller stack trace only has 2 gems besides rails/AR gems, I have already tried removing them. 

The reason I think this might, though loosely an AR issue is the fact the 2nd `BEGIN` is actually the  transaction from [update method](https://github.com/rails/rails/blob/813af4655f9bf3c712cf50205eebd337070cee52/activerecord/lib/active_record/persistence.rb#L280).  The first is from the transaction block in the controller, as expected. The issue in this case might read **models nested update transaction fails to be nested when used in parent transaction**

Any help or direction would be much appreciated. 

### System configuration
**Rails version**:  ruby 2.5.0p0 (2017-12-25 revision 61468) [x86_64-darwin17]

**Ruby version**:  5.1.4

**Comment by y-yagi** [comment]
﻿Can you create a reproduce script with [this template](https://github.com/rails/rails/blob/master/guides/bug_report_templates/active_record_master.rb)?

**Comment by ChrisCPO** [comment]
No I was not able to replicate it. I combined it with [controller bug template](https://github.com/rails/rails/blob/master/guides/bug_report_templates/action_controller_master.rb), because our issue is only from controllers when the server is running. Though I think I can use that to see if I can figure out which gem might be affecting this. Thanks.

**Comment by ChrisCPO** [comment]
**Update**
Stack traces from
[lib/active_record/connection_adapters/postgresql/database_statements.rb:ln 130](https://github.com/rails/rails/blob/813af4655f9bf3c712cf50205eebd337070cee52/activerecord/lib/active_record/connection_adapters/postgresql/database_statements.rb#L130)
I added an puts caller here for the last time it is being called before the update statement is called, in this case:
- 2 for our app
- 1 for the other rails app.

## Our App
```
active_record/connection_adapters/abstract/transaction.rb:130:in `initialize'
active_record/connection_adapters/abstract/transaction.rb:156:in `new'
active_record/connection_adapters/abstract/transaction.rb:156:in `block in begin_transaction'
monitor.rb:226:in `mon_synchronize'
active_record/connection_adapters/abstract/transaction.rb:152:in `begin_transaction'
active_record/connection_adapters/abstract/transaction.rb:193:in `block in within_new_transaction'
ruby/2.5.0/monitor.rb:226:in `mon_synchronize'
active_record/connection_adapters/abstract/transaction.rb:191:in `within_new_transaction'
active_record/connection_adapters/abstract/database_statements.rb:235:in `transaction'
active_record/transactions.rb:210:in `transaction'
active_record/transactions.rb:381:in `with_transaction_returning_status'
active_record/persistence.rb:283:in `update' #ActiveRecord::Base.transaction do
app/controllers/debugging_transactions_controller.rb:18:in `block in update'
active_record/connection_adapters/abstract/database_statements.rb:235:in `block in transaction'
active_record/connection_adapters/abstract/transaction.rb:194:in `block in within_new_transaction'
monitor.rb:226:in `mon_synchronize'
active_record/connection_adapters/abstract/transaction.rb:191:in `within_new_transaction'
active_record/connection_adapters/abstract/database_statements.rb:235:in `transaction'
active_record/transactions.rb:210:in `transaction'
app/controllers/debugging_transactions_controller.rb:12:in `update' # controller def update
```

## New Rails application, same gemfile, gemfile.lock.
```
active_record/connection_adapters/abstract/transaction.rb:130:in `initialize'
active_record/connection_adapters/abstract/transaction.rb:156:in `new'
active_record/connection_adapters/abstract/transaction.rb:156:in `block in begin_transaction'
monitor.rb:226:in `mon_synchronize'
active_record/connection_adapters/abstract/transaction.rb:152:in `begin_transaction'
active_record/connection_adapters/abstract/transaction.rb:193:in `block in within_new_transaction'
monitor.rb:226:in `mon_synchronize'
active_record/connection_adapters/abstract/transaction.rb:191:in `within_new_transaction'
active_record/connection_adapters/abstract/database_statements.rb:235:in `transaction'
active_record/transactions.rb:210:in `transaction'
app/controllers/debugging_transactions_controller.rb:11:in `update' # ActiveRecord::Base.transaction do # there was no log for update action which is on line 6
```

**Comment by y-yagi** [comment]
Apparently it looks like an application's issue, it seems not a issue with Rails.  
We reserve the Rails issue tracker only for bugs in Rails. So I close. Thanks.

**Comment by ChrisCPO** [comment]
@y-yagi I have been comparing logs and stepping my way though this. I figured out the what but not the why. Can I ask you a question, maybe you can offer some insight. 

https://github.com/rails/rails/blob/813af4655f9bf3c712cf50205eebd337070cee52/activerecord/lib/active_record/connection_adapters/abstract/transaction.rb#L151
The 2nd time this is called in a normal rails app The transaction @stack.size is 1 and AR uses a RealTransaction which is joinable. In our application the stack size is zero and it is using a NullTransaction. Which is not joinable which then causes AR to wrap `model.update` aka `      with_transaction_returning_status` in an entirely new transaction. Seems like this is a threading issue or perhaps a connection issue??

**Comment by ChrisCPO** [comment]
So I Figured this out. It was a puma worker configuration which was I believe was causing weird thread/ double connection issues. 

In our `config/puma.rb` file we had 
```ruby
on_worker_boot do
  ApplicationRecord.establish_connection if defined?(ActiveRecord)
end
```

Changing it to this fixed the issue.
```ruby
on_worker_boot do
  ActiveRecord::Base.establish_connection if defined?(ActiveRecord)
end
```

odd that ApplicationRecord#establish_connection != ActiveRecord::Base#establish_connection
