### ISSUE TITLE
action_dispatch/middleware/stack.rb: can't modify frozen Array

### ISSUE THREAD

**Issue by vemv** [rails/rails#33745]
When trying to run `rails c` or such, I encounter the following error: `can't modify frozen Array`.

Traceback: https://gist.githubusercontent.com/vemv/c38896b0366e7b84f708754bd10430e3/raw/f787b4e8a7f4f46c3119ee1db1f4dc745b53b8c5/gistfile1.txt

Gemfile.lock: https://gist.githubusercontent.com/vemv/e7e3eb7821e371a9e95e3f63a2cb5746/raw/db495d8b9536cdbab248cab34fcd7a5e8abf1fab/gistfile1.txt

Gem probably at fault: actionpack-5.2.0

Other people experiencing the same exact issue recently:

* https://github.com/getsentry/raven-ruby/issues/856 
* https://stackoverflow.com/questions/52021758/immediately-after-installing-webpacker-in-rails-5-2-1-i-get-a-cant-modify-fro .

**Comment by vemv** [comment]
Can also reproduce with actionpack-5.2.1 - I just upgraded Rails from 5.2.0 in case that helped.

**Comment by y-yagi** [comment]
This seems to be an issue of `rails_admin`.
https://github.com/sferik/rails_admin/issues/3060

Since it seems that there is no problem with `1.4.0`, try downgrading.

**Comment by vemv** [comment]
There's a problem with rails_admin 1.4.0:

* rails_admin 1.4.0 depends on haml `~> 4`
* Haml 4.x is not compatible with the latest Rails 5, see https://github.com/haml/haml/issues/895

So I need Haml 5.x, but I'm on a deadlock.

On a more general note I don't see rails_admin in my original backtrace, so perhaps there's a root cause to fix rather than having users search a possible workaround.

Thanks - Victor

**Comment by vemv** [comment]
Updated description above, was incorrect.

Fixed by downgrading to 1.3.0. Still, likely something is off on the Rails side.

**Comment by aselder** [comment]
I'm seeing the same error when upgrading to 5.2.1.

We don't have RailsAdmin in our project and are already on Haml 5.x

**Comment by taryneast** [comment]
Likewise I'm trying 5.2 and we do't have rails_admin or Haml

**Comment by mathieujobin** [comment]
Likely this is related to a rails middleware monkey patch done by your app or a gem.
first step is to locate which is involve.

```ruby
    def insert(index, klass, *args, &block)
      puts [index, klass, args].inspect # stack.rb:74 add this line
      index = assert_index(index, :before)
      middlewares.insert(index, build_middleware(klass, args, block))
    end
```

it will print each middleware being loaded, last one before the error is probably the one causing you a problem. then you can consider fixing/removing/upgrading.
