### ISSUE TITLE
Arrays are read incorrectly from Postgres when previously written to using index number

### ISSUE THREAD

**Issue by joallard** [rails/rails#33742]
I'm trying to read back an integer array column after I have written it, in SQL, using the index number.

If table `users` has a column `t.integer :numbers, array: true`, and in SQL, on a row, I set `SET numbers[3] = 10`, then on reading it back in SQL:

```
bug-array-reading=# update users set credit_balances[3] = 10 where id = 1;
UPDATE 1

bug-array-reading=# select * from users;
 id |  numbers
----+------------
  1 | [3:3]={10}
(1 row)

bug-array-reading=# select numbers[3] from users;
 numbers
---------
      10
```

There will be this special array notation. (Presumably not to have to fill a lot of elements with null spaces)

When read in Activerecord, this will not be retained. This means that if I use this array as a numerical associative array, the read will not be correct.

### Reproduction script
This script assumes a postgres db `bug-array-reading`, with the default auth options.

```rb
begin
  require "bundler/inline"
rescue LoadError => e
  $stderr.puts "Bundler version 1.10 or later is required. Please update your Bundler"
  raise e
end

gemfile(false) do
  source 'https://rubygems.org'
  gem 'rails', github: "rails/rails"
  gem 'pg'
  gem 'pry'
  gem 'pry-rescue'
end

require 'active_record'
require 'minitest/autorun'

ActiveRecord::Base.establish_connection(
  adapter: 'postgresql',
  database: 'bug-array-reading',
)
ActiveRecord::Base.logger = Logger.new(STDOUT)

class User < ActiveRecord::Base
end

ActiveRecord::Schema.define do
  create_table :users do |t|
    t.integer :numbers, array: true
  end unless table_exists?(:users)
end


describe "Array reading" do
  before do
    u = User.create!

    User.connection.execute("UPDATE users SET numbers[3] = 10 WHERE id = #{u.id}")
    u.reload
    @u = u
  end

  attr_reader :u

  # SELECT numbers[3] FROM users WHERE id = #{u.id}
  # would give 10

  it "dumps array" do
    assert_equal([nil, nil, nil, 10], u.numbers)
  end

  it "reads index at value" do
    assert_equal(10, u.numbers[3])
  end
end
```

### System configuration
**Rails version**: master

**Ruby version**: 2.5.1

Using Postgres 9.6.1

**Comment by matthewd** [comment]
SQL arrays are 1-indexed while Ruby arrays are 0-indexed, so I think the assertions should be:

```ruby
  it "dumps array" do
    assert_equal([nil, nil, 10], u.numbers)
  end

  it "reads index at value" do
    assert_equal(10, u.numbers[2])
  end
```

**Comment by y-yagi** [comment]
This seems limitation of `pg` gem.

We are using `PG::TextDecoder::Array` for Array's decode, but `PG::TextDecoder::Array` seems to be unable to parse this case.

```ruby 
PG::TextDecoder::Array.new(name: "text[]", delimiter: ',').decode("[3:3]={10}")
# => ["10"]
``` 

As the code comments also show, ignores any dimension decorations preceding the array values. 
https://github.com/ged/ruby-pg/blob/814faa69b1296056c733e4c3a818c3edcdbc15b8/ext/pg_text_decoder.c#L387-L390 

Related to https://bitbucket.org/ged/ruby-pg/issues/272/pg-textdecoder-array-decode-incorrectly
