### ISSUE TITLE
ArgumentError running post method from ActionDispatch::IntegrationTest

### ISSUE THREAD

**Issue by pepibumur** [rails/rails#33746]
### Steps to reproduce
- Create a controller with a single method, e.g. `github` on `WebhooksController`
- Add a test for that method, e.g. `test_github` on `WebhooksControllerTest < ActionDispatch::IntegrationTest`

```
def test_github
  post(github_path, params: {}, as: :json)
end
```

### Expected behavior
`post` method to run the call on the controller and update the `@response` object which I can run assertions on.

### Actual behavior
I get the following error:
```
ArgumentError: Received wrong number of arguments. [{}]
```

### System configuration
**Rails version**: 5.2.0

**Ruby version**: 2.5.1

**Comment by pepibumur** [comment]
Weird, I'll try again today @rafaelfranca

**Comment by wvanbergen** [comment]
The actual source of the error got masked by the backtrace silencer, but it was coming from a gem, rather than the `get` method. We can close this.
