### ISSUE TITLE
Would you accept a PR to override Integer#inspect?

### ISSUE THREAD

**Issue by iHiD** [rails/rails#33754]
Hello :)

I'm working on a project with lots of records. Today I did a `group(...).count` and got some output like:
```ruby
{true: 38382920, false: 48429292}
```

I found it really hard to understand the magnitude of the numbers. I quickly created [a Gem](https://github.com/iHiD/inspectable_numbers/) that overrides `Integer#inspect` to underscore the numbers. So we go from:

```ruby
10000000000
=> 10000000000 
```

to:

```ruby
10000000000
=> 10_000_000_000 
```

My team thought this would be super-useful as a default in Rails and I agree. 

Would you accept a PR to ActiveSupport to add this functionality or do you prefer that it is left as a Gem?

Thanks for doing amazing work 💙

**Comment by rafaelfranca** [comment]
Thank you for the issue. Integer is a Ruby class so maybe propose to the language itself? I don't see any reason why this should be in Active Support and not Ruby.

**Comment by iHiD** [comment]
Yep. That's a fair comment. ActiveSupport has a history of pioneering useful methods on Ruby classes and there are currently other methods defined in AS on Integer (e.g. `multiple_of?`, `months`, `years`), so I figured maybe this was a quick route to get something useful out there, but totally accept that you don't feel it's appropriate.

Thanks for the quick reply :)
