### ISSUE TITLE
Dirty attribute changes for virtual attributes broken between Rails 5.0 and 5.2

### ISSUE THREAD

**Issue by uberllama** [rails/rails#33753]
I encountered this bug with my own gem https://github.com/uberllama/accepts_nested_ids after upgrading from Rails 5.0 to 5.2. At first I thought I was missing one of the many API changes to Dirty, but upon further investigation, this behavior applies to any ActiveRecord model with virtual attributes that you want to track changes for.

### Steps to reproduce

Create models like so:

```ruby
class NotOrder
  include ActiveModel::Dirty

  def number
    @number
  end

  def number=(val)
    attribute_will_change!(:number) unless val == @number
    @number = val
  end
end

class Order < ActiveRecord::Base
  def number
    @number
  end

  def number=(val)
    attribute_will_change!(:number) unless val == @number
    @number = val
  end
end
```
### Expected behavior

`changes` returns delta of changes on virtual attribute whether AR or AM model.

```ruby
# Rails 5.0
norder = NotOrder.new
norder.number = 123
norder.changed # => ["number"]
norder.changes # => { "number" => [nil,123] }

order = Order.new
order.number = 123
order.changed # => ["number"]
order.changes # => { "number" => [nil,123] }
```

### Actual behavior

`changes` returns nil for new value of virtual attribute on AR model.

```ruby
# Rails 5.2
norder = NotOrder.new
norder.number = 123
norder.changed # => ["number"]
norder.changes # => { "number" => [nil,123] }

order = Order.new
order.number = 123
order.changed # => ["number"]
order.changes # => { "number" => [nil,nil] }
```

### System configuration
**Rails version**: 5.2

**Ruby version**: 2.4.1

**Comment by rafaelfranca** [comment]
This is expected. You will see a deprecation message in Rails 5.1 if you do that. https://github.com/rails/rails/blob/v5.1.6/activerecord/lib/active_record/attribute_methods/dirty.rb#L282-L287

**Comment by uberllama** [comment]
@rafaelfranca Thanks, the dangers of jumping versions... That being said, adding an `attribute` declaration for the virtual does not resolve the issue.

**Comment by rafaelfranca** [comment]
I don't remember how to fix this. @sgrif ideas?

**Comment by uberllama** [comment]
@sgrif as per my gem, the primary use case is to handle delayed setting of associations via an `ids` reference, with strong auditability. Think of an interface where you are creating a task and associating user IDs from a dropdown.

```ruby
project = Project.first
project.user_ids = [1,2,3]
project.changes # =>{  "user_ids" => [[], [1,2,3]] }
```

I'll tinker a bit based on your recommendations to see if it takes me anywhere.

**Comment by uberllama** [comment]
@sgrif You are right that in the rudimentary case, there is no need to define the attributes getters and setters. Unfortunately I haven't been able to get this working with my gem yet, where I'm doing a bit of trickery by overriding `some_association_ids` attributes with different behavior (seen above with the `user_ids` example. I may need to get ugly. :(

**Comment by bazzel** [comment]
I ran into the same issue and saw that `lib/active_model/dirty.rb#attribute_will_change!` which calls `_read_attribute(attr)`. The implementation for `_read_attribute` in active_record differs from the one in active_model. I think this change is introduced by 83d6cc4815debe2086073387ecbf38c0f47cfec5

**Comment by sgrif** [comment]
@uberllama I'd need an actual reproduction script that follows the recommendations I gave above to help further.

**Comment by uberllama** [comment]
@sgrif I will try and put that together today. Cheers.

**Comment by uberllama** [comment]
Here you go @sgrif 

The tests will pass with Rails 5.0.0 and fail with 5.2.0

```ruby
# frozen_string_literal: true

begin
  require "bundler/inline"
rescue LoadError => e
  $stderr.puts "Bundler version 1.10 or later is required. Please update your Bundler"
  raise e
end

gemfile(true) do
  source "https://rubygems.org"

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  # Activate the gem you are reporting the issue against.
  gem "activerecord", "5.2.0"
  # gem "activerecord", "5.0.0"
  gem "sqlite3"
end

require "active_record"
require "minitest/autorun"
require "logger"

# Ensure backward compatibility with Minitest 4
Minitest::Test = MiniTest::Unit::TestCase unless defined?(Minitest::Test)

# This connection will do for database-independent bug reports.
ActiveRecord::Base.establish_connection(adapter: "sqlite3", database: ":memory:")
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :projects do |t|
  end

  create_table :project_users do |t|
    t.integer :project_id
    t.integer :user_id
  end

  create_table :users do |t|
  end
end

class Project < ActiveRecord::Base
  has_many :project_users
  has_many :users, through: :project_users

  after_save :persist_nested_ids

  def user_ids
    return @nested_user_ids if defined?(@nested_user_ids)
    super
  end

  def user_ids=(val)
    return if user_ids == val
    attribute_will_change!(:user_ids)
    @nested_user_ids = val
  end

  private

  def persist_nested_ids
    self.users = User.where(id: @nested_user_ids) if @nested_user_ids
  end
end

class ProjectUser < ActiveRecord::Base
  belongs_to :project
  belongs_to :user
end

class User < ActiveRecord::Base
  has_many :project_users
  has_many :projects, through: :project_users
end

class BugTest < Minitest::Test
  def setup
    3.times { User.create! }
    @associated_users = [User.first, User.last]
    @associated_user_ids = @associated_users.map(&:id)
    @project = Project.new
    @project.user_ids = @associated_user_ids
  end

  # This will pass in Rails 5.0 and fail in Rails 5.2:
  #   Expected: [[], [1, 3]]
  #   Actual: [nil, nil]
  def test_changes
    assert_equal [[], @associated_user_ids], @project.changes["user_ids"]
    assert_equal 0, ProjectUser.count
  end

  def test_persistence
    @project.save!
    assert_equal 2, ProjectUser.count
    assert_equal @associated_user_ids, @project.reload.user_ids
    assert_equal @associated_users, @project.reload.users
  end
end
```

**Comment by sgrif** [comment]
Your example completely ignores every comment that has been left here. You cannot call `attribute_will_change!` on something not registered with the attributes API -- There *must* be `attribute :user_ids` if you want that to be managed by Active Record. As I've also said, you should not be using instance variables to deal with something you expect to be managed by Active Record, as it will lead to confusing or incorrect results. Your entire example could be replaced with `attribute :user_ids` and work.

**Comment by sgrif** [comment]
I'm going to close this for the time being as there does not appear to be anything actionable -- I'm happy to reopen if there's a reproduction script that demonstrates a bug in the public API (taking into account the deprecation warnings in 5.1 and the comments on this PR)

**Comment by sgrif** [comment]
Tracking something like association ids through `ActiveRecord::Dirty` is not something that we support. It is meant for attributes which have explicit assignment that we can track the storage of. Or to put it more generally, it's not supported for something that is fully "computed" like association ids

**Comment by bazzel** [comment]
Thanks for your answer, @sgrif.
Does that also mean that @uberllama's test was unintentionally passing in 5.0.0?

**Comment by rafaelfranca** [comment]
It was something that was supported but it is not anymore.

**Comment by danielricecodes** [comment]
> It was something that was supported but it is not anymore.

@rafaelfranca - its been my experience in the past that things that Rails no longer supports is typically moved to a gem, as to easy the pain of upgrading.  

In my case, I am trying to get basic association ID tracking to work in the `paper_trail` gem and it appears Rails dropped any supported mechanism to do that in Rails 5.1.  Tracking association ID's isn't a fringe use case, IMHO.
