### ISSUE TITLE
url_for/link_to in a view raises ArgumentError in production but not development

### ISSUE THREAD

**Issue by coldnebo** [rails/rails#33765]
_NOTE: I'm aware that 4.2 isn't under maintenance, but I'm still opening this issue in case anyone remembers more detail.  I'm not sure this issue continues to be a problem in Rails 5, but we are still in the process of moving our apps to Rails 5.  Even if closed, I hope this will serve as a signpost to others encountering this issue._

### Steps to reproduce

Configure your Rails 4.2 app to run in production.

in any view:
```ruby
<%= url_for(...).html_safe %>
```

### Expected behavior
url_for shouldn't change behavior depending on Rails.env.

### Actual behavior
url_for in development works ok.

url_for in production raises:

>ArgumentError: arguments passed to url_for can't be handled. Please require routes or provide your own implementation

### System configuration
**Rails version**: 4.2.0

**Ruby version**: 2.3.7

## Background

We ran into the issue while porting Rails 3.2 to 4.2.

One of our views includes code that implements generic queries on our routes by removing some of the params:

```ruby
<%= url_for(params.except('sort', 'page', 'order')).html_safe %>
```

When we went to test this app in our stage environment, it suddenly started failing with the following error:

>ArgumentError: arguments passed to url_for can't be handled. Please require routes or provide your own implementation

## Workaround

One workaround is to change the url_for instances in the views from:

```ruby
<%= url_for(params.except('sort', 'page', 'order')).html_safe %>
```

to:

```ruby
<%= controller.url_for(params.except('sort', 'page', 'order')).html_safe %>
```

which effectively uses the controller.url_for that still has the routing behavior we need.

Other workarounds are detailed in the references below:
- include routes.url_helpers
- don't include routes.url_helpers
- include UrlFor (???)

## Investigation

The error is [raised from actionview's url_for](https://github.com/rails/rails/blob/4-2-stable/actionview/lib/action_view/helpers/url_helper.rb#L38), but _only_ when Rails configuration is set (or defaulted) with:

        config.eager_load = true

The [original commit](https://github.com/rails/rails/commit/dc663dd52c99ab6e6c633b54d1a0e836f379bf9f) adding the error 
talks about the reason for refactoring url_for, but doesn't mention eager loading:

>ActionDispatch::Routing::UrlFor was always required in UrlHelpers. This was changed by splitting previous implementation of UrlHelper into 2 modules: ActionView::Helpers::UrlHelper and ActionView::Routing::UrlHelper. The former one keeps only basic implementation of url_for. The latter adds features that allow to use routes and is only required when url_helpers or mounted_helpers are required.

When `eager_load` is false (i.e. the default in development), actionpack's UrlFor [triggers an include](https://github.com/rails/rails/blob/4-2-stable/actionpack/lib/action_dispatch/routing/url_for.rb#L99) on actionview's `_url_for_modules` which does an include of `ActionView::RoutingUrlFor`.  But when `eager_load` is true, this include isn't triggered.

Following the lead about `url_helpers` and `mounted_helpers` lead to [code in ActionView::Rendering](https://github.com/rails/rails/blob/4-2-stable/actionview/lib/action_view/rendering.rb#L44):

```ruby 
include routes.url_helpers(supports_path)
include routes.mounted_helpers 
```

Inspection of this code path with Ruby Tracer revealed that when `eager_load` is false, the first line does `include(*_url_for_modules)`, whereas if `eager_load` is true, it doesn't.

Trying to follow [routes.url_helpers](https://github.com/rails/rails/blob/4-2-stable/actionpack/lib/action_dispatch/routing/route_set.rb#L487) shows a lot of complexity, which seems to be wiring the parts of routing that don't change to the per-request view instances that do change. I'm not exactly sure how all of this works so I'll try investigating other leads before I drill into this one.

(time goes by... so slowly...)

Ok, this is the only lead I have, so I wrapped the include with Tracer and tried diffing the output. Discovered that with `eager_load` true, the following chain of events happens:
1. RouteSet.url_helpers generates a new module, which is included, resulting in a `singleton_class.send(:redefine_method, :_routes) { routes }` call [here](https://github.com/rails/rails/blob/4-2-stable/actionpack/lib/action_dispatch/routing/route_set.rb#L525).
2. this causes ActiveSupport::Concern to [return false early](https://github.com/rails/rails/blob/4-2-stable/activesupport/lib/active_support/concern.rb#L116) because `base < self`, thus skipping `@_dependencies.each { |dep| base.send(:include, dep) }`, which in turn never invokes [the line](https://github.com/rails/rails/blob/4-2-stable/actionpack/lib/action_dispatch/routing/url_for.rb#L99) `include(*_url_for_modules)` from `ActionPack::Routing::UrlFor`.

If `eager_load` is false, then #1 happens, but #2 doesn't return early because `base !< self`, so everything loads.

[\>\_\<](https://media1.tenor.com/images/c5e9478783d39264eb988025e0b25600/tenor.gif?itemid=11294647)

I can see what's causing the issue, but I'm no closer to understanding how to fix this.

Let's go look at some other suggestions.

### ActionPack docs suggest 'include UrlFor'

ActionPack has some [cryptic doc](https://github.com/rails/rails/blob/4-2-stable/actionpack/lib/action_dispatch/routing/url_for.rb#L30) which seems to suggest that we only have to include the proper class to restore routing url_for:

>link_to, and all other functions that require URL generation functionality, actually use ActionController::UrlFor under the hood. And in particular, they use the ActionController::UrlFor#url_for method. One can generate the same path as the above example by using the following code:
 
```ruby
include UrlFor
url_for(controller: 'users',
        action: 'new',
        message: 'Welcome!',
        only_path: true)
```

The example above this is a `link_to` in a view context, so let's assume this code is in a view context:

```ruby
[10] pry(#<#<Class:0x0000555e37673000>>)> include UrlFor
NameError: uninitialized constant ActionView::CompiledTemplates::UrlFor
```

I can't figure out the exact class to include or where to include it.

### Deprecate \*\_path methods in mailers

[Another commit](https://github.com/rails/rails/commit/2bbcca004cc232cef868cd0e301f274ce5638df0) points to removing path helpers from ActionMailer, which motivates the refactoring seen in url_for, but doesn't have anything to do with eager loading.

## References

I was able to find two other references to this error:
1. in the apotomo gem, [issue #131](https://github.com/apotonick/apotomo/issues/131) reports the issue but doesn't provide details.
2. in Rails, [issue #23066](https://github.com/rails/rails/issues/23066) describes the issue in testing contexts, but doesn't have an answer.

SO has a [related question](https://stackoverflow.com/questions/20660604/using-the-correct-url-for-method-in-a-rails-engine-spec) to this issue where the solutions are varied and confusing:
- remove `include Rails.application.routes.url_helpers` from your models.  In our case, it's in a view, not a model.
- another comment says 'adding `Rails.application.routes.url_helpers` in my `ApplicationController`' helped.  

These answers doubtless helped in specific contexts, but they don't shed light on the root cause or how to fix the issue in views.

**Comment by y-yagi** [comment]
Can you please provide a sample application that reproduces the error? 
As you are recognized, 4.2 is not maintained besides severe security fixes.   
Therefore, it is necessary to confirm whether it reproduces even with the latest Rails.

**Comment by coldnebo** [comment]
Sure.

methodology:

```
$ rails -v
Rails 5.2.1

$ rails new url_for_app
$ cd url_for_app
$ rvm 2.3.7@scratch --ruby-version 
$ rails generate controller Welcome index
$ vim app/views/welcome/index.html.erb
<p>Try a <a href="<%= url_for(controller: 'welcome', action: 'index') %>">link to myself</a></p>

$ rake assets:precompile

# confirmed that default ./config/environment/production.rb has 'config.eager_load = true'
$ RAILS_ENV=production RAILS_SERVE_STATIC_FILES=1 RAILS_LOG_TO_STDOUT=1 rails s
```

As I suspected, this works ok in 5.2.1 so I'll close this.

**Comment by FEApaydin** [comment]
Having the exactly same issue in 5.2.2.

**Comment by chuyihuang** [comment]
I got this issue in 5.2.1 and I set config.eager_load to false, it worked!

but that was not i want because eager_load is extreme important to the production mode. Then I found this snippet caused the issue:

    `include Rails.application.routes.url_helpers`

I included this snippet in mailer, but was outside of the class scope:

    include Rails.application.routes.url_helpers
    class ExampleMailer < ApplicationMailer
        ...
    end`

so I changed to 

    class ExampleMailer < ApplicationMailer
      include Rails.application.routes.url_helpers
    end 

everything works as it should be.
this should be the reason causing this issue, the app load this module twice...

**Comment by coldnebo** [comment]
We saw this issue pop up again in a Rails 5.1.7 project.

**Comment by coldnebo** [comment]
This is happening in Rails 5.1.7 for us right now, and is reported on 5.2.  I'm going to reopen and see if anyone in Rails core has a suggestion for a workaround?

**Comment by coldnebo** [comment]
I have verified that this behavior continues in Rails 5.2.4.3, however it's only when using render :file to render another controller's view.

**Comment by coldnebo** [comment]
I've tried to reproduce this in a clean setting a number of different ways, but the basics work.
methodology:

```
$ rails -v
Rails 5.2.4.3

$ rails new url_for_app
$ cd url_for_app
$ rvm 2.6.6@scratch --ruby-version 
$ rails generate controller Welcome index

$ vim app/views/welcome/index.html.erb
<%= render partial: "mypartial" %>

$ vim app/views/welcome/_mypartial.html.erb
<p>Try a <a href="<%= url_for(controller: 'welcome', action: 'index') %>">link to myself</a></p>

$ rails generate controller Another index
$ vim app/controller/another_controller.rb
class AnotherController < ApplicationController
  def index
    append_view_path ::ActionView::FileSystemResolver.new("app/views", "welcome/:action{.:locale,}{.:formats,}{.:handlers,}")
    render file: 'welcome/index'
  end
end

$ rails s  # development mode

# open http://localhost:3000/welcome/index works without error.
# open http://localhost:3000/another/index works without error.

$ rake assets:precompile

# confirmed that default ./config/environment/production.rb has 'config.eager_load = true'
$ RAILS_ENV=production RAILS_SERVE_STATIC_FILES=1 RAILS_LOG_TO_STDOUT=1 rails s

# open http://localhost:3000/welcome/index works without error.
# open http://localhost:3000/another/index works without error.

```
So, I'm left with questioning some of the other assumptions in the app where we see this issue.  There is a lot of metaprogramming and dynamic route dispatch, so it's possible that somehow we get a different url_for implementation from that, but I can't be sure.  Render logic is really confusing.

I have a vague feeling that the ancestors in the singleton_class may be assembled in slightly different orders depending on dynamic dispatch in routing.  But that is really hard to prove.  I'll need a more complex example.

So I'll close this again for now until more info becomes available.

I'd still like to know what the original Rails core member meant by "implement your own", but he hasn't gotten back to me, so as frustrating as this issue is, back to the drawing board.

**Comment by merongivian** [comment]
this is still happening for me, though i haven't been able to reproduce it (mostly happens randomly in specs

![failures_r_spec_example_groups_manage_meeting_with_parties_accepts_a_bias_invitation_without_changing_the_replacement_(through_the_change_replacement_modal)_124](https://user-images.githubusercontent.com/4277403/137725324-2b3a89ea-b17d-48b5-8480-2ddebc0d3acb.png)
)
It's trying to call `UrlFor#url_for` instead of `RouteSet#url_for`
