### ISSUE TITLE
ActiveRecord::StatementInvalid for async_exec

### ISSUE THREAD

**Issue by elliottyson** [rails/rails#33764]
Hello!

I am coding a chatbot. I use sidekiq to run some methods in background jobs so that the user can still speak to the bot while methods are processed.
At the end of the process, I give back my variables to the user, which works.
But I also would like to store those variables in a table that I created and migrated. However when I add the code `Result.create!(first_name: "Elliot", age: 26, city: "Paris")` at the end of the background job I get the following error in Sidekiq:

"error_message":"PG::ConnectionBad: PQconsumeInput() server closed the connection unexpectedly\n\tThis probably means the server terminated abnormally\n\tbefore or while processing the request.\n:

"error_class":"ActiveRecord::StatementInvalid"

SELECT a.attname, format_type(a.atttypid, a.atttypmod),
                     pg_get_expr(d.adbin, d.adrelid), a.attnotnull, a.atttypid, a.atttypmod,
                     c.collname, col_description(a.attrelid, a.attnum) AS comment
                FROM pg_attribute a
                LEFT JOIN pg_attrdef d ON a.attrelid = d.adrelid AND a.attnum = d.adnum
                LEFT JOIN pg_type t ON a.atttypid = t.oid
                LEFT JOIN pg_collation c ON a.attcollation = c.oid AND a.attcollation <> t.typcollation
               WHERE a.attrelid = '"results"'::regclass
                 AND a.attnum > 0 AND NOT a.attisdropped
               ORDER BY a.attnum

WARN: /.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/activerecord-5.1.5/lib/active_record/connection_adapters/postgresql/database_statements.rb:61:in `async_exec'

Many thanks for your help :)

**Rails version**:
Rails 5.1.5

**Ruby version**:
ruby 2.5.1p57

**Comment by y-yagi** [comment]
Please use the [mailing list](https://groups.google.com/forum/#!forum/rubyonrails-talk) or StackOverflow for questions/help, where a wider community will be able to help you. We reserve the issues tracker for issues only. Thanks.
