### ISSUE TITLE
Cannot load such file -- sqlite3/sqlite3_native (LoadError)

### ISSUE THREAD

**Issue by Learning191** [rails/rails#33778]
### Steps to reproduce
- run ` rails new rails_app `
- run ` rails s `

### Actual behavior
   At this time I just updated the ruby ​​to the ruby ​​version `2.5.1p57 (revision 2018-03-29 63029) [i386-mingw32]` update it with `rubyinstaller-devkit-2.5.1-2-x86. exe` , when I try to execute `rails s` shows me this error  :

    $ rails s
    C:/Ruby25/lib/ruby/gems/2.5.0/gems/bootsnap- 
    1.3.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require': cannot load such file -- 
    sqlite3/sqlite3_native (LoadError)
         from C:/Ruby25/lib/ruby/gems/2.5.0/gems/activesupport- 
     5.2.1/lib/active_support/dependencies.rb:287:in `block in require'
         from C:/Ruby25/lib/ruby/gems/2.5.0/gems/activesupport- 
     5.2.1/lib/active_support/dependencies.rb:253:in `load_dependency'
         from C:/Ruby25/lib/ruby/gems/2.5.0/gems/activesupport- 
     5.2.1/lib/active_support/dependencies.rb:287:in `require'
         from C:/Ruby25/lib/ruby/gems/2.5.0/gems/sqlite3-1.3.13-x86-mingw32/lib/sqlite3.rb:6:in `rescue in 
     <top (required)>'
         from C:/Ruby25/lib/ruby/gems/2.5.0/gems/sqlite3-1.3.13-x86-mingw32/lib/sqlite3.rb:2:in `<top 
     (required)>'
         from C:/Ruby25/lib/ruby/gems/2.5.0/gems/bootsnap- 
     1.3.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `require'
         from C:/Ruby25/lib/ruby/gems/2.5.0/gems/bootsnap- 
     1.3.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `block in 
     require_with_bootsnap_lfi'
         from C:/Ruby25/lib/ruby/gems/2.5.0/gems/bootsnap- 
     1.3.1/lib/bootsnap/load_path_cache/loaded_features_index.rb:65:in `register'
         from C:/Ruby25/lib/ruby/gems/2.5.0/gems/bootsnap- 
     1.3.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:20:in `require_with_bootsnap_lfi'
         from C:/Ruby25/lib/ruby/gems/2.5.0/gems/bootsnap- 
      1.3.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:29:in `require'
         from C:/Ruby25/lib/ruby/gems/2.5.0/gems/bundler-1.16.4/lib/bundler/runtime.rb:81:in `block (2 
      levels) in require'
         from C:/Ruby25/lib/ruby/gems/2.5.0/gems/bundler-1.16.4/lib/bundler/runtime.rb:76:in `each'
         from C:/Ruby25/lib/ruby/gems/2.5.0/gems/bundler-1.16.4/lib/bundler/runtime.rb:76:in `block in 
     require'
         from C:/Ruby25/lib/ruby/gems/2.5.0/gems/bundler-1.16.4/lib/bundler/runtime.rb:65:in `each'
         from C:/Ruby25/lib/ruby/gems/2.5.0/gems/bundler-1.16.4/lib/bundler/runtime.rb:65:in `require'
         from C:/Ruby25/lib/ruby/gems/2.5.0/gems/bundler-1.16.4/lib/bundler.rb:114:in `require'
         from C:/users/angulo/projects_ruby/projects_rails/rails_app/config/application.rb:18:in `<top 
     (required)>'
         from C:/Ruby25/lib/ruby/gems/2.5.0/gems/bootsnap- 
     1.3.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `require'
         from C:/Ruby25/lib/ruby/gems/2.5.0/gems/bootsnap- 
     1.3.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `block in 
     require_with_bootsnap_lfi'
         from C:/Ruby25/lib/ruby/gems/2.5.0/gems/bootsnap- 
     1.3.1/lib/bootsnap/load_path_cache/loaded_features_index.rb:65:in `register'
         from C:/Ruby25/lib/ruby/gems/2.5.0/gems/bootsnap- 
     1.3.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:20:in `require_with_bootsnap_lfi'
         from C:/Ruby25/lib/ruby/gems/2.5.0/gems/bootsnap- 
     1.3.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:29:in `require'
         from C:/Ruby25/lib/ruby/gems/2.5.0/gems/activesupport- 
     5.2.1/lib/active_support/dependencies.rb:287:in `block in require'
         from C:/Ruby25/lib/ruby/gems/2.5.0/gems/activesupport- 
     5.2.1/lib/active_support/dependencies.rb:253:in `load_dependency'
         from C:/Ruby25/lib/ruby/gems/2.5.0/gems/activesupport- 
     5.2.1/lib/active_support/dependencies.rb:287:in `require'
         from C:/Ruby25/lib/ruby/gems/2.5.0/gems/railties- 
     5.2.1/lib/rails/commands/server/server_command.rb:145:in `block in perform'
         from C:/Ruby25/lib/ruby/gems/2.5.0/gems/railties- 
     5.2.1/lib/rails/commands/server/server_command.rb:142:in `tap'
         from C:/Ruby25/lib/ruby/gems/2.5.0/gems/railties- 
     5.2.1/lib/rails/commands/server/server_command.rb:142:in `perform'
         from C:/Ruby25/lib/ruby/gems/2.5.0/gems/thor-0.20.0/lib/thor/command.rb:27:in `run'
         from C:/Ruby25/lib/ruby/gems/2.5.0/gems/thor-0.20.0/lib/thor/invocation.rb:126:in ` 
     invoke_command'
         from C:/Ruby25/lib/ruby/gems/2.5.0/gems/thor-0.20.0/lib/thor.rb:387:in `dispatch'
         from C:/Ruby25/lib/ruby/gems/2.5.0/gems/railties-5.2.1/lib/rails/command/base.rb:65:in `perform'
         from C:/Ruby25/lib/ruby/gems/2.5.0/gems/railties-5.2.1/lib/rails/command.rb:46:in `invoke'
         from C:/Ruby25/lib/ruby/gems/2.5.0/gems/railties-5.2.1/lib/rails/commands.rb:18:in `<top 
     (required)>'
         from C:/Ruby25/lib/ruby/gems/2.5.0/gems/bootsnap 
    -1.3.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `require'
          from C:/Ruby25/lib/ruby/gems/2.5.0/gems/bootsnap- 
     1.3.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `block in 
    require_with_bootsnap_lfi'
         from C:/Ruby25/lib/ruby/gems/2.5.0/gems/bootsnap- 
    1.3.1/lib/bootsnap/load_path_cache/loaded_features_index.rb:65:in `register'
         from C:/Ruby25/lib/ruby/gems/2.5.0/gems/bootsnap- 
    1.3.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:20:in `require_with_bootsnap_lfi'
         from C:/Ruby25/lib/ruby/gems/2.5.0/gems/bootsnap- 
    1.3.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:29:in `require'
         from C:/Ruby25/lib/ruby/gems/2.5.0/gems/activesupport- 
    5.2.1/lib/active_support/dependencies.rb:287:in `block in require'
         from C:/Ruby25/lib/ruby/gems/2.5.0/gems/activesupport- 
    5.2.1/lib/active_support/dependencies.rb:253:in `load_dependency'
         from C:/Ruby25/lib/ruby/gems/2.5.0/gems/activesupport- 
    5.2.1/lib/active_support/dependencies.rb:287:in `require'
        from bin/rails:4:in `<main>'

### System configuration
Windows 7 x32 bits

**Rails version**:
- Rails 5.2.1

**Ruby version**:
- ruby ​​version `2.5.1p57 (revision 2018-03-29 63029) [i386-mingw32]`

Clearly does not let me ` require 'sqlite3' `

I try to solve it with issues like : [https://github.com/sparklemotion/sqlite3-ruby/issues/185](url) ,
[https://github.com/sparklemotion/sqlite3-ruby/issues/185](url) , but none of the solutions that this poetry worked for me

I hope it is solved, Thanks for reading

**Comment by y-yagi** [comment]
Perhaps, I think that the dll for sqlite 3 is not installed properly(The phenomenon is similar to https://stackoverflow.com/questions/50249153/cannot-load-such-file-sqlite3-sqlite3-native-loaderror-ruby-on-rails/50680295). Please check the environment.  

Also, please use the [mailing list](https://groups.google.com/forum/#!forum/rubyonrails-talk) or StackOverflow for questions/help, where a wider community will be able to help you. We reserve the issues tracker for issues only. Thanks!
