### ISSUE TITLE
Create #unfreeze_time to complement #freeze_time in ActiveSupport::Testing::TimeHelpers

### ISSUE THREAD

**Issue by ryanwhocodes** [rails/rails#33771]
### Steps to reproduce

https://github.com/rails/rails/blob/master/activesupport/lib/active_support/testing/time_helpers.rb

ActiveSupport::Testing::TimeHelpers has a method called #freeze_time

It could help users if there was a complementary method called #unfreeze_time

(Guidelines for creating a bug report are [available
here](http://edgeguides.rubyonrails.org/contributing_to_ruby_on_rails.html#creating-a-bug-report))

### Expected behavior

This could mean that a developer could write a test that would stub time at Time.now using #freeze_time, then could call #unfreeze_time when they want to unstub Time

### Actual behavior

There is only the #freeze_time method available

### System configuration
**Rails version**: 5.2.1

**Ruby version**: 2.4.1

**Comment by ryanwhocodes** [comment]
@georgeclaghorn If this is something Rails wants to include, I would be interested in working on it. 

I've contributed once before to Rails, and would like to gain more experience. Plus, this is a feature I've been wanting to use in my tests during my job as a developer and could design the implementation in a way that developers would find useful.

**Comment by y-yagi** [comment]
Please use the [Rails Core mailing list](https://groups.google.com/forum/#!forum/rubyonrails-core) for feature requests, where a wider community will be able to help you. We reserve the Rails issue tracker only for bugs in Rails. Thanks!

**Comment by ryanwhocodes** [comment]
Thanks for pointing me to the right place to suggest new features. I've posted the idea in the group, but it hasn't appeared yet because I assume there is a moderation process involved.
