### ISSUE TITLE
--skip-coffee still adds coffee-script to Gemfile and uses it

### ISSUE THREAD

**Issue by JohnMerlino2** [rails/rails#33783]
When creating a new project, I ran this exact command:

$ rails new myapp -T --database=postgresql --skip-coffee

However, in Gemfile, I notice this:

# Use CoffeeScript for .coffee assets and views
gem 'coffee-rails', '~> 4.2'

And when I generated a controller, I also notice this in assets/javascripts:

home.coffee

What gives? The --skip-coffee flag was completely ignored.

**Comment by matthewd** [comment]
Which version of Rails did you use to do the generating? (And just in case, what version did your app then generate as?)

Do you have a `~/.railsrc`?

The only time it's supposed to force coffeescript is if you use `--dev` or `--edge`, which you clearly did not. :confused:

**Comment by JohnMerlino2** [comment]
@matthewd there is no ~/.railsrc in the home directory. I am using Rails 5.1.6 with rvm 1.29.3:

$ rvm-prompt
ruby-2.4.1@personalgemset
$ rails -v
Rails 5.1.6

**Comment by JohnMerlino2** [comment]
And as a side note, why is Rails still defaulting with CoffeeScript? Isn't EcmaScript 6 enough?

**Comment by Istanful** [comment]
I cannot seem to reproduce it with:

```bash
$ rbenv shell 2.4.1
$ rails _5.1.6_ new myapp -T --database=postgresql --skip-coffee
```

Can you reproduce this consistently?

**Comment by oniofchaos** [comment]
```
Dillons-MacBook-Pro:myapp dillonwelch$ rvm-prompt
ruby-2.5.1
Dillons-MacBook-Pro:myapp dillonwelch$ rails -v
Rails 5.2.1
```

I ran `rails new myapp -T --database=postgresql --skip-coffee` and I got a new app that did not have `CoffeeScript` in it.
