### ISSUE TITLE
Successfully attaching a has_one_attached attachment returns nil

### ISSUE THREAD

**Issue by koskoci** [rails/rails#33784]
### Steps to reproduce

Given these models:
```
class Post < ApplicationRecord
  has_many_attached :images
end

class User < ApplicationRecord
  has_one_attached :curriculum_vitae
end
```

Successfully attaching a `has_many_attached` attachment returns an instance of `ActiveStorage::Attachment` while doing the same for a `has_one_attached` attachment returns `nil`.

```
[1] pry(#<PostsController>)> @post.images.attached?
=> false
[2] pry(#<PostsController>)> @post.images.attach(params[:post][:image])
=> [#<ActiveStorage::Attachment:0x00007fb113cd6970 id: 214, name: "images", record_type: "Post", record_id: 1, blob_id: 215, created_at: Mon, 03 Sep 2018 15:03:10 UTC +00:00>]
[3] pry(#<PostsController>)> @post.images.attached?
=> true

[1] pry(#<UsersController>)> @user.curriculum_vitae.attached?
=> false
[2] pry(#<UsersController>)> @user.curriculum_vitae.attach(params[:user][:curriculum_vitae])
=> nil
[3] pry(#<UsersController>)> @user.curriculum_vitae.attached?
=> true
```

This appears to be an inconsistency in the implementation that prevents the following branching in the controller (fairly idiomatic I think?):

```
  # POST /posts/1/images
  def images
    authorize!
    
    if @post.images.attach(params[:post][:image])
      render status: 201, jsonapi: @post, include: :images
    else
      render status: 400, json: { error: @post.errors }
    end
  end
```

### Expected behavior
Calling `attach` on a `has_one_attached` relationship should, if successful, return an instance of `ActiveStorage::Attachment`, just like it does for a `has_many_attached` relationship.
### Actual behavior
Calling `attach` on a `has_one_attached` relationship returns `nil`, even if successful.

### System configuration
**Rails version**: 5.2.0

**Ruby version**: 2.5.1

**Comment by georgeclaghorn** [comment]
`ActiveStorage::Attached::One` is implemented in terms of `ActiveRecord::Base#update` in master, so this will be fixed in Rails 6.
