### ISSUE TITLE
Problem with Rails cache production

### ISSUE THREAD

**Issue by BorisBresciani** [rails/rails#33797]
### Problem

As soon as I make the command: `Rails.cache.fetch('XXXX')` I have this error in production env: 

`NoMethodError (undefined method with for #<Hash:0x000056400ecbe090>)`

Production.rb
```
  config.action_controller.perform_caching = true
  config.cache_store = :redis_cache_store, {
    expires_in: 2.hours,
    redis: { url: ENV['APP_REDIS_URL'], password: ENV['APP_REDIS_PASSWORD'] }
  }
```

Redis runs well.

### System configuration
**Rails version**:
`5.2.1`
**Ruby version**:
`2.5.1`

**Comment by jeremy** [comment]
The `redis:` option expects a Redis instance, not a Hash. Pass those options directly instead, alongside `:expires_in`.

**Comment by BorisBresciani** [comment]
Thank you, i already test this, but i have same error
