### ISSUE TITLE
PG adapter where query is not correct when using enum

### ISSUE THREAD

**Issue by 5hanth** [rails/rails#33790]
### Steps to reproduce

Following is the where clause `models/event.rb`, 
`Participation.where(user_id: args[:user_id], status: [:pending, :approved, :processed]).sum(:amount_invested)
`
above query is present in Event.rb model. not sure why event_id is scoped automatically despite Model is used to make the query in rails.

the query made is,
`SELECT SUM("participations"."amount_invested") FROM "participations" WHERE "participations"."event_id" = $1 AND "participations"."status" = $2 AND "participations"."user_id" = $3 AND "participations"."status" IN (0, 1, 2)  [["event_id", 8], ["status", 2], ["user_id", "1000015"]]`

### Expected behavior
only `AND "participations"."status" IN (0, 1, 2)` condition should exist in query

### Actual behavior
`AND  "participations"."status" = $2` | `"participations"."event_id" = $1` should not appear.

### System configuration
**Rails version**: 5.0.7

**Ruby version**: 2.3.3p222 (2016-11-21 revision 56859) [x86_64-linux]

**Comment by y-yagi** [comment]
Can you create a reproduce script with this [template](https://github.com/rails/rails/blob/master/guides/bug_report_templates/active_record_master.rb)?

**Comment by oniofchaos** [comment]
@5hanth it's a little hard to diagnose the problems with your final query if you don't have the full code from your models posted here.

**Comment by 5hanth** [comment]
I couldn't reproduce this with the template.  It's weird that it happens only with my application code. I have to figure this out.  For now I used raw queries as temporary patch in my application.  We can close this issue. Will reopen when I can reproduce this using template.
