### ISSUE TITLE
ActiveRecord::StatementCache#execute incorrectly binds nil values

### ISSUE THREAD

**Issue by brewski** [rails/rails#33803]
### Steps to reproduce

```ruby
# frozen_string_literal: true

begin
  require "bundler/inline"
rescue LoadError => e
  $stderr.puts "Bundler version 1.10 or later is required. Please update your Bundler"
  raise e
end

gemfile(true) do
  source "https://rubygems.org"

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  # Activate the gem you are reporting the issue against.
  gem "activerecord", "5.2.0"
  gem "sqlite3"
end

require "active_record"
require "minitest/autorun"
require "logger"

# Ensure backward compatibility with Minitest 4
Minitest::Test = MiniTest::Unit::TestCase unless defined?(Minitest::Test)

# This connection will do for database-independent bug reports.
ActiveRecord::Base.establish_connection(adapter: "sqlite3", database: ":memory:")
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :posts, force: true do |t|
    t.integer :group
  end

  create_table :comments, force: true do |t|
    t.integer :group
  end
end

class Post < ActiveRecord::Base
  has_many(:group_comments, class_name: "Comment", foreign_key: :group, primary_key: :group)
end

class Comment < ActiveRecord::Base
end

class BugTest < Minitest::Test
  def test_cache_binding
    post = Post.create!(group: nil)

    assert_equal([post], Post.where(group: nil).to_a)

    cache = ActiveRecord::StatementCache.create(Post.connection) do |params|
      Post.where(group: params.bind)
    end

    assert_equal([post], cache.execute([nil], Post.connection).to_a)
  end

  def test_broken_association
    post = Post.create!(group: nil)
    comment1, comment2 = Comment.create!(group: nil), Comment.create!(group: nil)

    assert_equal(
      post.group_comments.to_a,
      post.group_comments.where("1").to_a
    )
  end
end
```

#### 1 - test cache binding (private API)
The statement cache execution of `Post.where(group: params.bind)` should return the same results as `Post.where(group: nil)` when passing `[nil]` to `#execute`. Both should execute the query:

```sql
SELECT "posts".* FROM "posts" WHERE "posts"."group" IS NULL
```
and both should return the sole `Post` in the database.

#### 2 - test broken association (public API)
Querying an the `post.group_comments.to_a` and `post.group_comments.where(Arel::Nodes::True.new).to_a` should have the exact same results.

#### 1 - test cache binding
`ActiveRecord::StatementCache#execute` incorrectly binds the parameters. The query it executes is:

```sql
SELECT "posts".* FROM "posts" WHERE "posts"."group" = NULL
```
which will always return 0 rows.

#### 2 - test broken association
Because `post.group_comments.to_a` is using `ActiveRecord::StatementCache` (which has the above mentioned bug), it produces the query:

```sql
SELECT "comments".* FROM "comments" WHERE "comments"."group" = NULL
```

When querying the same association, but chained with a `where` (that has no affect on the results returned from the DB), active record is not using the statement cache, and produces a different query:

```sql
SELECT "comments".* FROM "comments" WHERE "comments"."group" IS NULL AND 1
```

The two results are not equal, but they should be. 

### System configuration
**Rails version**: `5.2.0`

**Ruby version**: `ruby 2.3.1p112 (2016-04-26 revision 54768) [x86_64-linux]`

### Additional Notes
This really points to a potential second bug. The second test demonstrating how the public API is broken begs the question: how should associations treat foreign keys / primary keys that are `NULL`?  I'd argue the tables should be joined using strict equality (`=`) and not a null-safe comparison. In other words, if an association is defined with a "primary key" that is nullable (`Post#group` in the case of `Posts#group_comments`), then is is correct to include comments that have a `NULL` group in the association? I'd say no, in which case the bug in `ActiveRecord::StatementCache` would happen to produce the correct results. I'd still argue the bug should be fixed, and then the associations should have special handing when joining records via a `NULL` "primary key".

**Comment by brewski** [comment]
The issue here is likely caused by the way the statement cache is manually binding parameters to the query. Unlike `Post.where(number: nil)`, where ActiveRecord is using Arel to construct the query (which correctly handles generating null-safe sql comparison expressions), the statement cache execution path is manually binding the parameters and doesn't correctly handle the `nil` case.

I'd be willing to work on a patch for this, but I'd like some direction on how best to approach solving the issue.

**Comment by y-yagi** [comment]
`StatementCache` is private API. Please do not use it in the application. 
Ref: 07f4bd5b60d062bda58a45ca5f832a0a6bcdc713

**Comment by brewski** [comment]
@y-yagi I understand that this is a private API. However, this is incorrect behavior that affects the public API causing incorrect results when querying associations. I updated the failing test case in the description to have 2 tests. One demonstrating the bug in `ActiveRecord::StatementCache` and one demonstrating how it is causing issues with active record's public API causing associations to produce incorrect results. Would you please re-open this issue?

**Comment by y-yagi** [comment]
`Arel` is also private API. It should not be used in application. 
Can you create a reproduce test case without using `Arel`?

**Comment by brewski** [comment]
@y-yagi Thanks for reviewing this again. I have updated the example to not use `Arel`.

**Comment by kamipo** [comment]
I've confirmed that case 2 is a bug for nil association value, usually primary key/foreign key isn't to be nil though.
Are you interested to open a PR to fix the issue?

**Comment by brewski** [comment]
I think we should open a PR. The underlying problem in the private api is that the statement cache is creating an incorrect query (it should never be creating expressions like `some_column = NULL`). I agree that the example I provided in case 2 (using only the public API) is is unusual. Having has_many / has_one association where the foreign key is joining to a nullable column on the source table isn't common; however, I think it is a legitimate thing to do and ideally AR should support it. Furthermore, there may be other places where generating queries like `expression = NULL` might cause issues.

My vote would be to:

1) fix the parameter binding so it correctly binds `nil` in a null-safe way in sql (the same way `Arel` correctly handles `nil values)

2) update has_many / has_one associations to gracefully handle the scenario where the "primary key" on the source record happens to be `nil`. I propose that in that case, the association should not return any records and not generate a sql query with a null-safe `foreign_key is null` condition. Perhaps it should add an always-false condition like `WHERE 1=0` the same way `Post.where(id: [])` would?

What are your thoughts on that?

**Comment by brewski** [comment]
Doe anyone have any thoughts on a direction to proceed here? I don't mind working on a PR, but it would be helpful to have some input before digging in too deep.

**Comment by kamipo** [comment]
`StatementCache` does not support all values at least for now.

https://github.com/rails/rails/blob/792fead512be390fdaf219b8bf3e17aa335bd7f4/activerecord/lib/active_record/statement_cache.rb#L111-L115

case 2 is a problem that `StatementCache` is used even though the value is not supported.

We have a workaround force disable `StatementCache` by given empty block (`has_many :group_comments, -> {}`).
Generally it should run consistently regardless of whether caching is enabled or not.
