### ISSUE TITLE
ActionCable too many subscriptions ?

### ISSUE THREAD

**Issue by cdalbergue** [rails/rails#33802]
### Steps to reproduce
I have an appllication in production with about ~500 users a day and after a period of time, the websockets (powered by actioncable) don't run anymore.

I checked all the possible logs. The clients received the http upgrade, the backend handles the request properly but here is the problem : I have over 1000 redis pubsub channel opened. I think that it might be the problem but I'm having a hard time troubleshooting it, hope you can help me.

I need to say that this perfectly works on local environment and on my demo environment (which are exact replicates of my production env except for the physical hardware), so I assume this is a concurrency problem, if you could help me find the bottleneck here...

### Expected behavior
1 oubsub channel for 1 subscription

### Actual behavior
1000 opened channel

I tried to monitor redis pubsub channels and I find some of the channels I defined in my rails app (eg. events-1234)

But when I monitor redis activity, I can see a lot of strange pub/sub action going on:
```
...
1536182471.153479 [0 35.187.45.216:41326] "subscribe" "action_cable/Z2lkOi8vZ2Vyb25pbW8vVXNlci85ODk0OTAz"
1536182471.328922 [0 35.187.45.216:41326] "subscribe" "action_cable/Z2lkOi8vZ2Vyb25pbW8vVXNlci8xMjUyOTE0NzA"
1536182471.500513 [0 35.187.45.216:41326] "subscribe" "action_cable/Z2lkOi8vZ2Vyb25pbW8vVXNlci8zNTU2MDk4"
1536182472.014460 [0 35.187.45.216:41328] "subscribe" "action_cable/Z2lkOi8vZ2Vyb25pbW8vVXNlci8zNTYxNjQz"
...
```

When I do `redis pubsub' i find all this junk:
```
....
30) "action_cable/Z2lkOi8vZ2Vyb25pbW8vVXNlci8xNzEyODYzNzc"
31) "action_cable/Z2lkOi8vZ2Vyb25pbW8vVXNlci8zNTA4MTgy"
32) "action_cable/Z2lkOi8vZ2Vyb25pbW8vVXNlci8xMzExOTA2Njc"
33) "action_cable/Z2lkOi8vZ2Vyb25pbW8vVXNlci8xNjU5MDE4Mw"
34) "action_cable/Z2lkOi8vZ2Vyb25pbW8vVXNlci8xNDA5NjQ2"
35) "action_cable/Z2lkOi8vZ2Vyb25pbW8vVXNlci8xMTgyMzI5"
36) "action_cable/Z2lkOi8vZ2Vyb25pbW8vVXNlci8yMzczNTY5"
37) "action_cable/Z2lkOi8vZ2Vyb25pbW8vVXNlci8zOTc2NjU2MQ"
38) "action_cable/Z2lkOi8vZ2Vyb25pbW8vVXNlci8xOTI1MDQx"
39) "action_cable/Z2lkOi8vZ2Vyb25pbW8vVXNlci8yNDUxOTYwMQ"
40) "action_cable/Z2lkOi8vZ2Vyb25pbW8vVXNlci8xMTYyODUxMjA"
41) "action_cable/Z2lkOi8vZ2Vyb25pbW8vVXNlci8yNDU1MTk0Nw"
....
```

I never subscribe to these channels anywhere in my rails app, so I don't understand if that's normal behaviour or if I'm having a problem.

### System configuration
**Rails version**: 5.0.1

**Ruby version**: 2.3.1

Hope we can fix this together

**Comment by palkan** [comment]
> I never subscribe to these channels anywhere in my rails app, so I don't understand if that's normal behaviour or if I'm having a problem.

These are Action Cable _internal_ streams, one stream per connection (see https://github.com/rails/rails/blob/5-2-stable/actioncable/lib/action_cable/connection/internal_channel.rb).

So, having 1000 pubsub channels for 500 clients is okey (assuming that you subscribe each client to a custom unique stream in your code). 

> the websockets (powered by actioncable) don't run anymore.

Do you mean that connections are closed right after upgrade or do they stay connected but with no messages received?

**Comment by cdalbergue** [comment]
Hi and thanks for your answer.

I didn't know there were these channels.

Please find here an example of my WS debug console:
![image](https://user-images.githubusercontent.com/11771656/45288287-9af69b80-b4ea-11e8-9174-15e5635bff81.png)

There are no frames in the console, client side tries to create a new cable connexion.

Here are my puma logs: (grep websocket)
![image](https://user-images.githubusercontent.com/11771656/45288449-fb85d880-b4ea-11e8-8376-6d00446ff24b.png)

So I assume the connexion is successful, I see no "Error" but my connexion and many of the client connexions don't work. But ome seem to work thaugh, because in the logs of the sidekiq server, I can see this:
![image](https://user-images.githubusercontent.com/11771656/45288588-54ee0780-b4eb-11e8-98c0-afea3c37e24b.png)


So that's why I assume it's a concurrency problem but I juste can't identify the choke point. Right now, the application is at about 700 RPM
Have you got any idea how I could troubleshoot this ?

**Comment by palkan** [comment]
> There are no frames in the console, client side tries to create a new cable connexion.

What is the response status for `/cable` request ("Headers" tab)? How long does it wait before trying to reconnect?

**Comment by cdalbergue** [comment]
Please find here my response codes:
```
Status Code: 101 Switching Protocols
Connection: upgrade
Date: Tue, 11 Sep 2018 08:49:58 GMT
Sec-WebSocket-Accept: XXXXXXX
Sec-WebSocket-Protocol: actioncable-v1-json
Server: nginx
Upgrade: websocket
```

I think it waits about 5 seconds as if the connexion closed unexpectedly

**Comment by palkan** [comment]
That means that at least the heartbeat is not working; probably, event loop is getting stuck for some reason; have no idea 🤷‍♂️

Do you have any app performances metrics information? For example, RAM/CPU usage, the number of open connections, anything that coincides with this cable problem.

**Comment by cdalbergue** [comment]
800RPM at its top
8 Gigs of ram usage
80% CPU peaks with very much variations

Database connections is at about 150

I'm having such a hard time with this I'm considering switching to anycable

**Comment by cdalbergue** [comment]
Solved by switching to anycable and I had a pool size problem.

**Comment by YarikST** [comment]
@palkan hi сould you explain this

`PUBSUB CHANNELS` - Issues a list of channels - for each connection a separate internal channel -
`"action_cable / id_1: id_2: *"`

`PUBSUB NUMSUB "action_cable / id_i"` - always issues 1

my question is what to create a unique channel for the connection?

Example

```
class CallsChannel <ActionCable :: Channel :: Base

  def subscribed
    stream_from CallsChannel.channel_with_prefix (call)

    call.add_member current_user

    PresenceTracker.track (CallsChannel.channel_with_prefix (call), current_user.id)
  end

  def unsubscribed
    stop_all_streams

    PresenceTracker.untrack (CallsChannel.channel_with_prefix (call), current_user.id)

    if count_member == 0
      call.end_call_notify
    end
  end
  
  def self.channel_with_prefix call
    "calls_channel _ # {call.id}"
  end
  
  private

  def count_member
    PresenceTracker.page_users (CallsChannel.channel_with_prefix (call)). Size
  end
end
```

when user 2 user subscribe to _call_target_

`PUBSUB CHANNELS `- Displays 3 channels
```
action_cable / user_id_1
action_cable / user_id_2
calls_channel_call_target
```

`PUBSUB NUMSUB` - for all of them displays 1

why on `"calls_channel_call_target"` - I thought there should be 2 - as two users subscribed to the count

**Comment by palkan** [comment]
> why on "calls_channel_call_target" - I thought there should be 2 - as two users subscribed to the count

Action Cable only subscribes once to a particular stream – only when you want to subscribe to this stream for the first time.
The actual _subscription map_ (stream -> connection) is stored within Ruby, the Redis channel is used to broadcast messages across the multiple instances of the Rails app:

```

                                                                |--> connection
                            |--> Rails app 1 (Redis subscriber)-|--> connection
                            |                                   |--> ...
                            |                             
                            |                                   |--> connection
broadcast (Redis publish) --|--> Rails app 2 (Redis subscriber)-|--> connection
                            |                                   |--> ...
                            |                             
                            |
                            |--> Rails app 3 (Redis subscriber) ...
```

**Comment by aksharj** [comment]
Hi I am facing the same problem in production, we did a recent deploy with ActionCable and noticed after 4 to 5 hours ion deployment, the server crashing.

Any help on how to figure out where the issue is would be really great!

Thanks.

**Comment by project-orcon** [comment]
I think the issue is related to this https://github.com/rails/rails/pull/23715/files  I am trying to work out what version of rails this got included in

**Comment by lucasDechenier** [comment]
Hello, I also have this problem in production, ActionCable is making millions of calls, does anyone have a solution?

Acticable is flooding call machines.

**Comment by kulbirsaini** [comment]
> Hello, I also have this problem in production, ActionCable is making millions of calls, does anyone have a solution?
> 
> Acticable is flooding call machines.

Checkout this thread https://github.com/rails/rails/issues/44652 . The suggested workaround in the thread fixed my problem.
