### ISSUE TITLE
After create commit transaction problem

### ISSUE THREAD

**Issue by metekabak** [rails/rails#33818]
### Steps to reproduce
I`m firing a firebase update application record with after_create_commit when client side gets the update,

It's hitting the endpoint to fetch the updated data.But sometimes, it's getting the old data from the endpoint.

If we wait a little bit and hit the request, It`s getting the correct data.

Isn`t that after_create_commit waits for the transaction? What am I missing here?

### System configuration
**5.2**:

**2.5.1**:

**Comment by y-yagi** [comment]
Please use the [mailing list](https://groups.google.com/forum/#!forum/rubyonrails-talk) or StackOverflow for questions/help, where a wider community will be able to help you. We reserve the issues tracker for issues only.Thanks.
