### ISSUE TITLE
Instance views with default configs

### ISSUE THREAD

**Issue by Skill-Zozo** [rails/rails#33828]
This may not be an issue but for the benefit of the community, I thought it necessary raise it as such.

### Steps to reproduce
Imagine one has created an instance of an action view. And tries to render
```
action_view = ActionView::Base.new(...)
action_view.controller = MyBrandSpankingNewController
action_view.render(layout: "fancy_ass_layout_from_somewhere_far")
```
Now, I also have env configs set under `config/environments/` such as ` config.action_controller.asset_host = https://assets.onmycdn.com` and `config.assets.prefix = folder/to/my/assets`, the issue is when you use rails path helpers like `asset_url` and `asset_path` you would expect them to come with the `asset_host` and `asset.prefix` configs previously set, but this is not the case.

And so the question becomes, should the view carry the default configs or is it something the developer should explicitly set for this new ActionView instance? If it is the latter, how does one go about doing that? 

### Expected behavior
At this point, either the view comes with the default configs set or guideline as to how to make sure your view comes with default config
### Actual behavior
when you use rails path helpers like `asset_path` they ignore the configuration set out in files like `config/environments/sandbox.rb` for example.
### System configuration

**Rails version**:
4.2.10 
**Ruby version**:
2.3.3

(I do think that is happening on latest ruby/rails versions as well, btw)

**Comment by y-yagi** [comment]
I think that you would like to render view outside the controller. In that case, consider using `ActionController::Renderer` (added in Rails 5). It respects the env values.
Also, please use the [mailing list](https://groups.google.com/forum/#!forum/rubyonrails-talk) or StackOverflow for questions/help, where a wider community will be able to help you. We reserve the issues tracker for issues only. Thanks.
