### ISSUE TITLE
Var names master/slave are offensive!

### ISSUE THREAD

**Issue by ZhongCitizen** [rails/rails#33830]
So many slaves in rails code, I feel very uncomfortable while reading these code.

Please read: https://twitter.com/andrestaltz/status/1030200563802230786

Software development still has a lot of terminology with a racist or patriarchal background. Let's change that.

- Blacklist ➡ Denylist
- Whitelist ➡ Allowlist
- Killer app ➡ Beloved app
- Master/slave ➡ primary/replica

Examples:

https://github.com/rails/rails/blob/b2eb1d1c55a59fee1e6c4cba7030d8ceb524267c/railties/test/engine/commands_test.rb#L36

https://github.com/rails/rails/blob/b2eb1d1c55a59fee1e6c4cba7030d8ceb524267c/railties/test/application/server_test.rb#L43

**Comment by schneems** [comment]
For 1 and 2 they’ve already been changed. For 3 there are no “killer app” references for 4 can you give me a PR? There are only 4 references and they’re all in test https://github.com/rails/rails/search?utf8=✓&q=slave&type=

For this case m/s is bad terminology. I’m not actually sure what the second one does the docs say it’s a file but I can’t find any docs of that it’s actually used for. Can change to primary/replica and see if anyone has better ideas.

**Comment by thedumbtechguy** [comment]
I identify as a replicant. We find it offensive to use the word *replica*

**Comment by jeremy** [comment]
Thanks @ZhongCitizen! Please do open PRs with specific changes.
