### ISSUE TITLE
ActionDispatch::IntegrationTest should include ActiveJob::TestHelper, ActionMailer::TestHelper by default

### ISSUE THREAD

**Issue by dhh** [rails/rails#33838]
The point of ActionDispatch::IntegrationTest is to allow you to test the integration of all the pieces called by a controller. Asserting about the emails and jobs queued is part of that. You shouldn't have to configure the test helpers by hand yourself. So let's include these by default via railties, as not to tie ActionDispatch to Active Job or Action Mailer. Could go in the app's generated test_helper.rb, but that feels a little crude?

**Comment by rafaelfranca** [comment]
The best option to implement this would use the railties and the [`action_dispatch_integration_test` load hook](https://guides.rubyonrails.org/engines.html#active-support-on-load-hooks). Added the good-first-patch tag.
