### ISSUE TITLE
Rails Generate Model is incorrectly identifies all words with 's' on the end as plural

### ISSUE THREAD

**Issue by romasks** [rails/rails#33841]
I'm trying to generate a 'UserBonus' model in Rails 5.2.1 and Ruby 2.5.0. 
When I run:

`rails generate model UserBonus`

I get:

`The model name 'UserBonus' was recognized as a plural, using the singular 'UserBonu' instead. Override with --force-plural or setup custom inflection rules for this noun before running the generator.`

Modification of `config/initializers/inflections.rb` doesn't take any useful effect.

P.S. 
I see that this problem has arisen for some time already: [one](https://stackoverflow.com/questions/44354541/rails-generate-model-not-using-inflection-rule), [two](https://github.com/rails/rails/issues/5198)

**Comment by ianfleeton** [comment]
Adding the inflection rules

```
inflect.singular /(bonus)(es)?$/i, '\1'
inflect.plural   /(bonus)$/i, '\1es'
````

is what works for me. I removed the start-of-string regex anchor ^ which is used in the examples and in your second reference. With the ^ only the standalone word "Bonus" can be singularized or pluralized.

**Comment by louim** [comment]
Active Support Inflector rules are what determine how the world will be pluralized / singularized.

You can see all [the inflection rules](https://github.com/rails/rails/blob/82ac7555ab69c1ae11360d2b9bd8dfd723a13485/activesupport/lib/active_support/inflections.rb). They are frozen, meaning new rules won't be added to rails core to prevent existing app from breaking. But you can add you own rules to your app. You should have an intializer here: `app/config/initializers/inflections.rb` where you can add your rules.

For example adding:
```
ActiveSupport::Inflector.inflections(:en) do |inflect|
  inflect.plural(/(bonu)s$/i, '\1ses')
  inflect.singular(/(bonu)(es)?$/i, '\1')
end
```
Would fix inflection of the world bonus.
