### ISSUE TITLE
ActiveStorage Position 

### ISSUE THREAD

**Issue by prwhitehead** [rails/rails#33840]
Firstly thank you for your work on ActiveStorage, It's greatly appreciated. 

I have been using it on a project that has a lot of images and accesses them in a variety of ways. One of the biggest issues I can see is that there is no way to order attachment without yet another join, which means 3 joins/includes to get a single set of images. 

Whilst I appreciate that you probably don't want to bundle Acts as List with rails to deal with this, a simple position column on the ActiveStorage Attachment would help. 

Thank you.

**Comment by georgeclaghorn** [comment]
Thanks for the issue, but we don’t take feature requests in the issue tracker. Please use the [rubyonrails-core](https://groups.google.com/forum/#!forum/rubyonrails-core) mailing list.

**Comment by prwhitehead** [comment]
I thought that might be the case. Sorry to bother you here.
