### ISSUE TITLE
ActionCable Rails 5.2 (Passenger) - WebSocket error occurred: One or more reserved bits are on: reserved1 = 1, reserved2 = 0, reserved3 = 0

### ISSUE THREAD

**Issue by ryzalyusoff** [rails/rails#33845]
I am trying to deploy ActionCable and Rails 5.2 To Production server (DigitalOcean). 
The app was deployed using Phusion Passenger + Nginx + Capistrano.

I have also looked into the production.log on the server and this is the error that was recorded:

`WebSocket error occurred: One or more reserved bits are on: reserved1 = 1, reserved2 = 0, reserved3 = 0
`

### System configuration
**Rails version**: 5.2

**Ruby version**: 2.5.1

### These are my settings:

**/etc/nginx/sites-enabled/default**
```
server {
        listen 80;
        listen [::]:80 ipv6only=on;

        server_name my_server_domain;
        passenger_enabled on;
        rails_env    production;
        root         /home/deploy/my_app_domain/current/public;

        # ActionCabel config (disable this if u r not using it)
        location /cable {
           passenger_app_group_name actioncable_websocket;
           passenger_force_max_concurrent_requests_per_process 0;
        }

        # redirect server error pages to the static page /50x.html
        error_page   500 502 503 504  /50x.html;
        location = /50x.html {
            root   html;
        }
}

```
**production.rb**

```
config.action_cable.url = "/cable"
config.action_cable.allowed_request_origins = ["http://my_app_ip_address"]
```

**cable.js**
```
(function() {
  this.App || (this.App = {});

  App.cable = ActionCable.createConsumer("/cable");

}).call(this);
```

The action cable works just fine locally and only has this issue when deployed to production. I have check my Redis, Nginx settings etc, and they are all fine, thus making me believes that the error is coming from Rails, Passenger or something.

Any idea/help?

**Comment by y-yagi** [comment]
Please use the [mailing list](https://groups.google.com/forum/#!forum/rubyonrails-talk) or StackOverflow for questions/help, where a wider community will be able to help you. We reserve the issues tracker for issues only. Thanks!

**Comment by aksharj** [comment]
Hi, I am facing a similar issue where i see 502 gateway timeout sporadically, any help on how to fix this would be great, thanks.

**Comment by ryzalyusoff** [comment]
> Hi, I am facing a similar issue where i see 502 gateway timeout sporadically, any help on how to fix this would be great, thanks.

Hi, make sure your redis is up and running on your server. That's the reason why I encountered my error :)

**Comment by aksharj** [comment]
@ryzalyusoff, thanks for your reply, the strange thing is why would it happen sporadically? if redis is down would it not work at all? any help in clarifying this would be really great, Thanks.
