### ISSUE TITLE
api.rubyonrails.org uses Ruby favicon

### ISSUE THREAD

**Issue by pwim** [rails/rails#33851]
I noticed that the favicon for https://api.rubyonrails.org/ is currently the Ruby favicon, not the Ruby on Rails one (![favicon.ico](https://api.rubyonrails.org/favicon.ico)).

I took a look for where the favicon was coming from, but it doesn't appear to be from this repo. Perhaps there is a separate build script for generating api.rubyonrails.org?

**Comment by matthewd** [comment]
The API docs are built using `sdoc`. It looks like the icon probably comes from here: https://github.com/zzak/sdoc/tree/master/lib/rdoc/generator/template/rails/resources
