### ISSUE TITLE
Association rollback bug when anything after first associated record raises

### ISSUE THREAD

**Issue by nnc** [rails/rails#33868]
### Steps to reproduce

Attempt to create more then one associated record within an explicit transaction and when second or later associated record raises an error, save the parent record and `ActiveRecord::NotNullViolation` error is raised.

But if first associated record raises an error (with `received_answers = ["", "A", "B"]`), then this test passes.

```ruby
begin
  require "bundler/inline"
rescue LoadError => e
  $stderr.puts "Bundler version 1.10 or later is required. Please update your Bundler"
  raise e
end

gemfile(true) do
  source "https://rubygems.org"

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  # Activate the gem you are reporting the issue against.
  gem "activerecord", github: "rails/rails"
  gem "sqlite3"
end

require "active_record"
require "minitest/autorun"
require "logger"

# Ensure backward compatibility with minitest 4.
Minitest::Test = MiniTest::Unit::TestCase unless defined?(Minitest::Test)

# This connection will do for database-independent bug reports.
ActiveRecord::Base.establish_connection(adapter: "sqlite3", database: ":memory:")
ActiveRecord::Base.logger = Logger.new(STDOUT)
ActiveSupport::LogSubscriber.colorize_logging = false

ActiveRecord::Schema.define do
  create_table :questions, force: :cascade do |t|
    t.string :state, null: false, default: "new"
  end

  create_table :answers, force: :cascade do |t|
    t.belongs_to :question, foreign_key: true
    t.string :text

    t.timestamps
  end
end

class Question < ActiveRecord::Base
  has_many :answers, dependent: :destroy
end

class Answer < ActiveRecord::Base
  belongs_to :question

  validates :text, presence: true
end


class AssociationRollbackBugTest < Minitest::Test
  def test_association_rollback_clears_rollbacked_records
    ActiveRecord::Base.verbose_query_logs = true
    
    received_answers = ["A", "", "B"]
    question = Question.create!

    begin
      ActiveRecord::Base.transaction do
        received_answers.each do |answer_text|
          puts "===== Creating answer for: '#{answer_text}'"
          question.answers.create!(text: answer_text)
        end

        question.update! state: "answered"
      end
    rescue => error
      puts "===== Rescued error: #{error.inspect}"
      puts "===== Current answers: #{question.answers.inspect}"
      
      question.update! state: "error"
    end

    assert_equal "error", question.reload.state
  end
end
```

### Expected behavior
I expected `question.update! state: "error"` in `rescue` block to update the `Question` record, no matter which of the associated `Answer` records raised an error, and not try to save any `Answer` records, as they were all rolled back by the transaction.

### Actual behavior
ActiveRecord tries to save an `Answer` record with no attributes at all, resulting in `INSERT INTO "answers" DEFAULT VALUES` which in turn violates the `NOT NULL` constraint on `answers.created_at`.

Test output of running both cases is [available here](https://gist.github.com/nnc/746488a73e0e75e2580a7581a7a226c3).

### System configuration
**Rails version**:
master and 5.2.1 (didn't test older versions)

**Ruby version**:
2.4.2

**Comment by eugeneius** [comment]
The problem that causes the invalid `INSERT` statement is already tracked in https://github.com/rails/rails/issues/15018 and https://github.com/rails/rails/issues/30167.
