### ISSUE TITLE
[ActionCable] Reduce ActionCable message verbosity to save bandwidth

### ISSUE THREAD

**Issue by ernsheong** [rails/rails#33863]
### System configuration
**Rails version**: 5.1.5
**Ruby version**: 2.4.2

ActionCable sends lots of empty pings that look like the following:

```
{type: "ping", message: 1536823128}
```

Pings are sent every 3 seconds or so, which adds up for high-traffic sites.

Furthermore, ActionCable messages are verbose with keys that can be shortened:

```
{identifier: "{"channel":"PChannel","m":"289"}", message: {c: 289,…}}
```

In above example, identifier could be shortened to just "i". "channel" could be shortened to just "c", "message" could be shortened to just "m".

**Why is this a problem?**
We ([coingecko.com](https://www.coingecko.com)) are currently paying AWS a lot of money just for bandwidth. We have trimmed everything we could already: naming the channel "PChannel" (why can't we name it something even shorter?), subscribe to channels one by one (because providing a long list as the parameters causes the serialized version of that list to become the identifier!!), reducing the payload, etc.

**Possible solutions**

- Make it possible to configure ping intervals (make it longer, without hacks)
- Reduce the key name length for the ActionCable payload
- Use something else as the identifier?
- Allow totally custom payload

**Comment by rafaelfranca** [comment]
Thank you so much for the issue but we don't take feature request on the issue tracker. We recommend you to try to implement the feature and send us a pull request or if you are in doubt if the feature will be accepts ask in Rails Core mailing list for feedback.
