### ISSUE TITLE
Add ability to define versions of images for active_storage

### ISSUE THREAD

**Issue by igorkasyanchuk** [rails/rails#33873]
### Steps to reproduce

Currently we can do something like:

```erb
<%= image_tag user.avatar.variant(resize_to_fit: [100, 100]) %>
OR
<%= image_tag user.avatar.variant(combine_options: {thumbnail: "500x500^", gravity: "center", extent: "500x500"} %>
```

From one side it's cool that you can control image from view, but from other if you want to use same style in other place you need to duplicate it.

In paperclip (and carrierwave) they have a concept of "versions" when you can define differnt versions and use like `user.avatar.version(:thumb).url`.

### Expected behavior

I would like to add ability to define versions in model like this:

```ruby
has_one_attached :avatar, versions: { thumb: { combine_options: {thumbnail: "500x500^", gravity: "center", extent: "500x500"} } }
```

and then use in views `image_tag user.avatar.variant(:thumb) `

I already have code which can do it, but would like to discuss if you want to have a PR with it, below are changes to support it:

https://gist.github.com/igorkasyanchuk/2775123a3fbaf196f43a092e8f4a6931

### Actual behavior

You need to duplicate code.

### System configuration

Rails 5.x and active storage gem.

**Comment by georgeclaghorn** [comment]
I’m not in love with the idea of a big hash of variations. Others have proposed something like this, and I’m open to a PR implementing it:

```ruby
has_one_attached :avatar do
  variation :thumb, thumbnail: "500x500^", gravity: "center", extent: "500x500"
end
```

We don’t take feature requests in the issue tracker, so I’m going to close this. Please use the rubyonrails-core mailing list in the future.
