### ISSUE TITLE
Add Rails.application.credentials.env environmental config lookup interface.

### ISSUE THREAD

**Issue by jgorman** [rails/rails#33890]
Pull #33888 adds the Rails.application.credentials.env interface for Rails.env sensitive
configuration lookups.

The new #env interface is available for all files opened with Rails.application.encrypted()
and EncryptedConfiguration.new().

The #env interface makes it easy to migrate from deprecated encrypted secrets to credentials.
Secrets supported environmentally responsive configurations and #env brings that convenience
to credentials with a lightweight view object.

    development:
      foo: development foo
    production:
      foo: production foo

For example, in development mode.

    Rails.application.credentials.env.foo == "development foo"

The #env interface has been extracted into the credentials_for_rails_env gem to assist with
the migration from secrets to credentials before Rails 6.0 lands.

https://github.com/jgorman/credentials_for_rails_env

**Comment by y-yagi** [comment]
Thank you so much for the issue but we don't take feature request on the issue tracker.  
You have already created PR, so let's track with that. Thanks.
