### ISSUE TITLE
doc bug: no actual example of using "a database-specific locking clause of your own"

### ISSUE THREAD

**Issue by jrochkind** [rails/rails#33894]
Comment docs in ActiveRecord::Locking::Pessimistic say:

https://github.com/rails/rails/blob/d681adbbb5e945994580a4e3b5103081888491b9/activerecord/lib/active_record/locking/pessimistic.rb#L13-L14

However the example provided just calls `lock(true)`, and does not have an example of a database-specific locking clause of your own:

https://github.com/rails/rails/blob/d681adbbb5e945994580a4e3b5103081888491b9/activerecord/lib/active_record/locking/pessimistic.rb#L16-L24

I don't understand locking well enough to provide an example myself, that's in fact why I was consulting the docs on Pessimistic::Locking. :)   I suppose it might as simple as replacing `lock(true)` in the examples with `lock("LOCK IN SHARE MODE")`, but I'm not sure if the example would make any sense to do anything useful. I was looking for an example that would make sense to do something useful myself!

**Comment by sham-sheer** [comment]
hello

**Comment by gmcgibbon** [comment]
Thanks for raising this issue. I'm fairly new to the concept of locking as well. Postgres has some good documentation on it [here](https://www.postgresql.org/docs/11/static/explicit-locking.html#LOCKING-ROWS). I've submitted a PR to fix the example.

**Comment by jrochkind** [comment]
thank you @gmcgibbon !
