### ISSUE TITLE
can't change session_store options

### ISSUE THREAD

**Issue by francescob** [rails/rails#33904]
### Steps to reproduce

in an initializer try to set 
`Rails.application.config.session_store :active_record_store, :key => '_my_app_session'`

or in application.rb  

`config.session_store :active_record_store, :key => '_my_app_session'`

### Expected behavior

session store should be set to active_record_store and key should be called _my_app_session

### Actual behavior
both session store and session key keeps default values (CookieStore)

### System configuration
**Rails version**:
5.2.1
**Ruby version**:
2.5.1

**Comment by francescob** [comment]
Sorry, the problem seems to be with RailsAdmin gem. I'm closing this.

**Comment by ryanmarshall** [comment]
I'm having the same issue without RailsAdmin. 

I'm setting in development.rb
  # session store
  config.session_store = :active_record_store, {
    key: Rails.application.secrets.session_key,
    domain: Rails.application.secrets.domain,
  }

But after app loads, my values in
Rails.application.config.session_store
are default "key' and CookieStore

I'm using active_admin, not sure if that plays any part
