### ISSUE TITLE
The cache_version is not used by dalli when reading and writing keys of objects (memcache client)

### ISSUE THREAD

**Issue by schneems** [rails/rails#33907]
### Update

The `dalli_store` does not work with rails anymore and you should use `mem_cache_store` instead. Bellow is my reproduction and report that I wrote before getting this information.

### Steps to reproduce

```bash
git clone https://github.com/schneems/dalli-cache-bug
cd dalli-cache-bug
bundle install
rails console
```

then run this code:

```ruby
ModelWithKeyAndVersion = Struct.new(:cache_key, :cache_version)
model_1_cache_1 = ModelWithKeyAndVersion.new("model/1", "1")
model_1_cache_2 = ModelWithKeyAndVersion.new("model/1", "2")

Rails.cache.fetch(model_1_cache_1) { "woohoo" }
puts Rails.cache.read(model_1_cache_1) # => "woohoo"
puts Rails.cache.read(model_1_cache_2) # => "woohoo"
```

### Expected behavior
 
Different cache versions should produce different cache keys and therefore different cache results.

### Actual behavior

Instead, dalli does not use the `cache_version` at all so you get the same result even if the `cache_version` changes.

### System configuration

**Rails version**: 5.2.1 && master

**Ruby version**: 2.5.1

## Notes

Other stores implemented directly in Rails such as MemoryStore utilize ActiveSupport::Cache which does manually expand `cache_version` https://github.com/rails/rails/blob/11581afc01927565d57dd0e0156e983f92f8c2e0/activesupport/lib/active_support/cache.rb#L661. 

Right now if you're using dalli and rails then rev-ing the cache_version of an object does not invalidate the cache. 😵🙊🙈🙉😵

## More reproductions

I added a view to my example app to show that this issue does affect view caching and not just `Rails.cache` calls. Details are in the readme. Also, here's a video of me reproducing the behavior in production on [CodeTriage](https://www.codetriage.com).

![screenflow](https://user-images.githubusercontent.com/59744/45695311-c3077f80-bb26-11e8-99f7-6df127e5260d.gif)

**Comment by jacortinas** [comment]
@schneems Would this require modifying dalli?

**Comment by schneems** [comment]
The issue is that `:dalli_store` isn't supported in Rails anymore. You should use `:mem_cache_store` instead. This configuration should raise an error or warn at the least since it's known to not work.

**Comment by brchristian** [comment]
Just chiming in as the author of 
https://github.com/petergoldstein/dalli/pull/700 to mention that there is at least one PR in Dalli to support `cache_versioning`, namely https://github.com/petergoldstein/dalli/pull/698. It is not currently passing CI, so I don’t know what the current status is, but supporting `cache_versioning` in Dalli should theoretically be pretty straightforward, and I expect would only require changing a handful of lines of code.

**Comment by jeremy** [comment]
Upstream issue. At best, Rails could require cache stores to report whether they support cache versioning and raise if not, but that's a separate PR 😊
