### ISSUE TITLE
How to upload file to nested object using ActiveStorage and accepts_nested_attributes_for?

### ISSUE THREAD

**Issue by iczman** [rails/rails#33915]
Sorry this is most likely not a bug, but I couldn't find another avenue to ask this question. My apology in advance.

 - I have `Project` that has many `Tasks`.
 - Each `Task` can have an image uploaded using ActiveStorage.

In my Project new view I have nested forms to create new tasks and file_field to upload an image per task. When the form is submitted I create a new Project along with new tasks from `project_params` in my Project controller. But how can I use ActiveStorage to attach each tasks' image after the Project is created?

**Models**
```ruby
class Project < ApplicationRecord
  has_many :tasks
end

class Task < ApplicationRecord
  belongs_to :project
end
```

**Nested View to upload image for Task**
```erb
<%= form_for @project do |f| %>
    <%= f.fields_for :tasks do |ff| %>
        <%= ff.file_field :image %>
    <% end %>
<% end %>
```

**Project controller**
```ruby
class ProjectController
  def create
    @project = Project.new(project_params)
    @project.save
    ...
    # How should I attach task images here?
  end
end
```

**Params to controller**
```
"tasks_attributes": {
  "0": { "image": ... },
  "1": { "image": ... }
}
```

One way is to loop through each @project.tasks and call .attach on them with image from the params above in the same order. But that seems error prone since params doesn't give me task ID to match with the saved task, so I worry I won't be always attaching the image to the right task. If some of the tasks didn't save to db due to being invalid, the 1-to-1 matching breaks down making this approach even more brittle.

**Comment by iczman** [comment]
For some reason I can upload files with the code I have as is. Not sure why it wasn't working before... maybe I changed something I wasn't aware of 😕

**Comment by sean-gilmore** [comment]
For anyone else stumbling upon this issue, I believe it relates to the model the file is attached to not auto-saving. My fix for this was to pass an additional field value alongside the file upload - for some reason, this caused both the file field & additional field to both be saved.
There seems to be more discussion of this issue happening on https://github.com/rails/rails/issues/37701.
