### ISSUE TITLE
Belongs_to :dependent warning and example conflict on rails guides

### ISSUE THREAD

**Issue by formigarafa** [rails/rails#33914]
### Steps to reproduce

On https://github.com/rails/rails/blob/master/guides/source/association_basics.md#dependent
you can see the message:

> WARNING: You should not specify this option on a belongs_to association that is connected with a has_many association on the other class. Doing so can lead to orphaned records in your database.

A some blocks bellow on https://guides.rubyonrails.org/association_basics.html#options-for-belongs-to an example is given using what the warning suggests to avoid:
```
class Book < ApplicationRecord
  belongs_to :author, dependent: :destroy,
    counter_cache: true
end
```

And again on https://github.com/rails/rails/blob/master/guides/source/association_basics.md#scopes-for-belongs_to you can see this:
```
class Book < ApplicationRecord
  belongs_to :author, -> { where active: true },
                        dependent: :destroy
end
```

### Expected behavior
Documentation should feature examples to be followed and when it is a bad example make it clear on the example that you should not do that. If the example given was a belongs_to where the inverse_of is a has_one association it would be clearer what is the use case of a belongs_to dependent: :destroy.

### Actual behavior
As one of my peers noticed while checking docs, it is not clear what to not do if you go straight to the "Scopes for `belongs_to`" example. It feels like it is encouraged to do such pattern.
Given the examples are made with Authors have many books and books belongs to authors there is no space for giving a proper example using a `has_one` association.

### System configuration
**Rails version**:
Every version since at least v2.0.0.

**Ruby version**:
Any

**Comment by ianfleeton** [comment]
I agree that `dependent: :destroy` doesn't help here, and conflicts with the warning and given example. However it does serve to show where the lambda argument sits. (If that's not important then just removing seems clearer.)

Maybe replace and reuse the `touch: :books_updated_at` from a paragraph or so up as it's safer and has some continuity.
