### ISSUE TITLE
NoMethodError (undefined method `empty?' for #<Order:0x00007f930e89f938>

### ISSUE THREAD

**Issue by cyruscavalcante** [rails/rails#33923]
Json route works fine.
Try to get "/orders/1.xml" response

### Steps to reproduce
 rails new myapp --api --database=postgresql

### My model 

```
class Order < ApplicationRecord
  self.table_name = 'pedidos'
  self.primary_key = 'pedido'

  belongs_to :client, foreign_key: :cliente

  def readonly?
    true
  end

end

```
### My controller
```
      def show
        @order = Order.find(params[:id])
        respond_to do |format| 
          format.xml { render xml: @order }
          format.json { render json: @order }
        end
      end

```
### Actual behavior

NoMethodError (undefined method `empty?' for #<Order:0x00007f930e89f938>):

activemodel (5.2.1) lib/active_model/attribute_methods.rb:430:in `method_missing'
rack (2.0.5) lib/rack/etag.rb:68:in `block in digest_body'
actionpack (5.2.1) lib/action_dispatch/http/response.rb:147:in `each'
actionpack (5.2.1) lib/action_dispatch/http/response.rb:147:in `each_chunk'
actionpack (5.2.1) lib/action_dispatch/http/response.rb:128:in `each'
actionpack (5.2.1) lib/action_dispatch/http/response.rb:76:in `each'
actionpack (5.2.1) lib/action_dispatch/http/response.rb:475:in `each'

### System configuration
**Rails version**: 5.2.1

**Ruby version**: ruby 2.5.1p57

**Comment by y-yagi** [comment]
XML serialization of Active Record models has been cut out to gem.  
https://github.com/rails/activemodel-serializers-xml 

Please try again after `activemodel-serializers-xml` add to Gemfile.
