### ISSUE TITLE
ActiveSupport::Cache compression: add another threshold

### ISSUE THREAD

**Issue by foonlyboy** [rails/rails#33921]
Hi everyone at rails,
I'd like to suggest an improvement for the ActiveSupport::Cache compression.

I got some WARN: 'Value for ... over max size: 1048576 <= 7148178'
which I believe must come from the Cache module.
[sidenote: you might want to clarify the warning, to state that this comes from the Cache module]

I fully agree that too big items should not be put in the cache, to avoid cache pollution.

However, after compression, some of these items might be *a lot* smaller.
They should then be put into the cache (compressed)

Currently the warning is issued on the non compressed size of the item,
(and that item will not be cached)

I'd like to suggest another threshold for the size of the item,
so that we try to compress and then decide if the compressed data fits.

I'd suggest a 7x limit of the uncompressed size as a default.
(this is what we get on compressing big regular structured items)

We are trading memory vs compute.

That big items obviously come from some big computations,
and the cache size constraint is only applied after serializing them,
which takes a lot of compute in itself.

It would be a shame to throw that away.
But compressing that (once we have it, [and that's already serialized])
should be comparably cheap.

More so, these big items tend to be very regular and compress really well.
(which makes them very good candidates to cache them)

I'd like to suggest:
- try to compress big items first, before excluding them from caching
- invent a configurable threshold to exclude too big items from that approach

**Comment by rafaelfranca** [comment]
Thank you for the suggestion but Rails doesn't emit this warning. In fact Rails compress anything over 1 kB.

**Comment by foonlyboy** [comment]
Hi Rafael,
thanks for your reply!

I got this with our sitemap.xml,
both on caching the query and the page.
(which would both finely compress)

That cache compression must be a new feature in rails 5.2.1?
This really makes a lot of sense.

Are you working on that?
~eike

**Comment by foonlyboy** [comment]
Hi Rafael,
This is still open.

**Comment by rafaelfranca** [comment]
Is it? Like I said Rails doesn't emit that warning. In no version that I could look (I went back until Rails 5.1). Are you sure that is Rails that is emitting this warning?

**Comment by rafaelfranca** [comment]
Just found that this is generated by dalli. If you cache store configured to compress entries?

**Comment by foonlyboy** [comment]
Hi Rafael,
Thanks for your hint to dalli, we're using that, it works like a charm.

I now got into caching and compression,
and this really makes a lot of sense,
compressing the cold store in the back.

But we also have some hot caches.
We want to share that in memory within instances.

**Comment by foonlyboy** [comment]
I looked at https://github.com/mezis/viscacha
This always looked a bit too complicated to me.
I'm looking for a 100fold performance for the hot caches.

**Comment by foonlyboy** [comment]
Hi Rafael,
big thanks for your reply, again.

It looks like you are somehow involved with caching in rails?

I found something new in the api docs (can't find it again right now)
which looked to me, that we can now embed dynamic content in cached
snippets?

Whoever came up with this? That's genius.
