### ISSUE TITLE
xml_http_request? in action_dispatch does not return boolean value

### ISSUE THREAD

**Issue by schorsch** [rails/rails#33939]
### Steps to reproduce

https://github.com/rails/rails/blob/master/actionpack/lib/action_dispatch/http/request.rb#L267

The method should return a boolean value, as stated in its comment, but returns an integer.

irb: 
```ruby
'some_string' =~ /abc/  #=> nil
'some_string' =~ /str/   # => 5
```
Since we are matching the whole string a strict solutions is a simple comparison:

```ruby
# i would even drop downcase bcs strict means strict, but i have no idea what js libs & browsers do 
get_header("HTTP_X_REQUESTED_WITH") == 'XMLHttpRequest'.downcase
```

### Expected behavior

should return a boolean value

### Actual behavior

returns nil or integer

### System configuration
**Rails version**: 5.1
**Ruby version**: 2.4.4/2.5.1

**Comment by victorhazbun** [comment]
I will like to fix this.

**Comment by gsamokovarov** [comment]
This has been raised many times before and Rails follows what Ruby's standard library does: returning truthy or falsy values, not strictly the singletons `true` or `false`. See https://github.com/rails/rails/issues/13516#issuecomment-31297634 for an example.

**Comment by schorsch** [comment]
well, the official ruby faq states something different in: https://www.ruby-lang.org/en/documentation/faq/6/

> We recommend that predicate methods (those whose name ends with a question mark) return true or false

but nevermind
