### ISSUE TITLE
Issue with render json

### ISSUE THREAD

**Issue by abith-hussain** [rails/rails#33947]
I am currently developing an api using rails 5.2.1 and i my controller when i try to render json response i am getting error as below

ArgumentError: wrong number of arguments (given 3, expected 0)

here's what i am using 

render :json => { 
    :data => 'XXYY'
}

please help me guys really stuck at this

**Comment by y-yagi** [comment]
Please use the [mailing list](https://groups.google.com/forum/#!forum/rubyonrails-talk) or StackOverflow for questions/help, where a wider community will be able to help you. We reserve the issues tracker for issues only. Thanks.
