### ISSUE TITLE
is there any solution for active storage for single table inheritance？

### ISSUE THREAD

**Issue by Davidzhu001** [rails/rails#33952]
#### in parent class 
```
class Member < ApplicationRecord
  has_one_attached :photo
end
```
#### in child class
```
class Applicant < Member
    default_scope -> { where(status: 'applicant') }
end
  
```

is there any solution for child class inherit parent class photo?  
or should rails provide the option?

### System configuration
**5.2.1**:

**2.4.1**:

**Comment by oniofchaos** [comment]
@Davidzhu001 can you outline the expected behavior vs the actual behavior?
