### ISSUE TITLE
before_update callback not called after find_or_create_by

### ISSUE THREAD

**Issue by SalmaNegm** [rails/rails#33955]
I am trying to create a cart if not exist, then update some attributes

   ```
 cart = Cart.find_or_create_by(cart_id: @cart.id)
    if cart.update(cart_params)
      # statements
    else
       # statements
    end
```

### Expected behavior
I expected it to call before_update call back after finding or creating the cart

### Actual behavior
before_update only called after finding the cart not creating it

### System configuration
**Rails version**: 5.2

**Ruby version**: 2.5-slim

**Comment by y-yagi** [comment]
`before_update` called only when updating an object. 
If you want to use the same callback for creating and updating, use `before_save`.
Ref: https://edgeguides.rubyonrails.org/active_record_callbacks.html#creating-an-object
