### ISSUE TITLE
where_hash_values empty whenever it's not by an equal sign?

### ISSUE THREAD

**Issue by faelsoto** [rails/rails#33950]
### Steps to reproduce

1. Create a model
2. Fetch some records based on its ID and created_at
3. Call `where_values_hash`

```
Post.where(:id => 1).where('created_at < ', Time.zone.now).where_values_hash
```

### Expected behavior

To obtain a hash with two keys, since two conditions were created.

### Actual behavior

We get only one, the ID:

```
2.5.1 :034 > Post.where(:id => 1).where('created_at < ', Time.zone.now).where_values_hash
 => {"id"=>1}
```

### System configuration

**Rails version**: 5.1.6

**Ruby version**: 2.5.1p57

**Comment by ianfleeton** [comment]
The implementation has included only the equalities since before version 3.0.0 (before it was extracted from `scope_for_create`).

It's discussed in #4388 as being internal, and the issue was closed, so maybe it should be `#:nodoc:`'d or have the documentation clarify its usage?

**Comment by oniofchaos** [comment]
Looks like the reasoning for this is because your first where clause is a hash but your second clause is a string, which gets processed differently in the background by ActiveRecord. 

```
[18] pry(main)> Post.where(id: 1).where(name: 'test').where_values_hash
=> {"id"=>1, "email"=>"test"}
[19] pry(main)> Post.where(id: 1).where("name = 'test'").where_values_hash
=> {"id"=>1}
```

Not sure if this is considered a bug or a feature by the maintainers, but that's the state of things 🤷‍♂️ 🤷‍♀️

**Comment by rafaelfranca** [comment]
`where_values_hash` and `where_values` are private API and should not be use in applications.
