### ISSUE TITLE
current_page? not working with trailing slash and parameters

### ISSUE THREAD

**Issue by rien** [rails/rails#33956]
### Steps to reproduce
Call `current_page?` on an URL which has a path that ends with a `/` and has paramters

### Expected behavior
The `current_page?` method should return `true` when called with `/nl/submissions/?course_id=7` if that' the current page.

### Actual behavior
```ruby
(byebug) request.original_fullpath
"/nl/submissions/?course_id=7"
(byebug) request.fullpath
"/nl/submissions?course_id=7"
(byebug) current_page?('/nl/submissions/?course_id=7')
false
(byebug) current_page?('/nl/submissions?course_id=7')
true
```

### System configuration
**Rails version**: 5.2.0

**Ruby version**: 2.5.1

### Possible cause
The [current implementation](https://github.com/rails/rails/blob/master/actionview/lib/action_view/helpers/url_helper.rb#L543) handles trailing slashes with the following code:
```ruby
if url_string.start_with?("/") && url_string != "/"
   url_string.chomp!("/")
   request_uri.chomp!("/")
end
```
Which will not work when `url_string` has a query parameter. I will try to submit a PR resolving this issue.

**Comment by p8** [comment]
Hi @rien, sorry for having to wait this long without a reply. 😞 
I'm closing this as the following test does work on main:
```ruby
  def test_current_page_with_trailing_slash_and_params
    @request = request_for_url("/posts?order=desc")

    assert current_page?("/posts/?order=desc")
  end
```
Thanks for contributing to Rails.

**Comment by rien** [comment]
Well, good to hear this is fixed then :+1:

**Comment by jonathanhefner** [comment]
@p8 I tried adding that test to the suite to prevent a regression, but it did not pass. :confused:

I've opened #42854 to fix it.

**Comment by p8** [comment]
Thanks @jonathanhefner !
