### ISSUE TITLE
touch not triggered in mutilevel 1:n / n:n situation and adding after_commit callback

### ISSUE THREAD

**Issue by ymoxx** [rails/rails#33963]
### Steps to reproduce

The data model looks as follows:

    class Project < ApplicationRecord
      has_and_belongs_to_many :languages, through: :projectlanguages, join_table: :projectlanguages
      has_many :messages
      has_many :projectlanguages
      has_many :projectusers
      has_many :translations, through: :projectlanguages

    class Language < ApplicationRecord
      has_many :projectlanguages
      has_and_belongs_to_many :projects, through: :projectlanguages, join_table: :projectlanguages
      has_many :translations, through: :projectlanguages

    class Projectlanguage < ApplicationRecord
      belongs_to :language
      belongs_to :project, touch: true
      has_many :translations
    
    class Message < ApplicationRecord
      belongs_to :project, touch: true
      has_many :translations, dependent: :destroy
      after_commit do
         # Some code goes here
      end

    class Translation < ApplicationRecord
      belongs_to :projectlanguage, touch: true
      belongs_to :message, touch: true, optional: true
      has_one :language, through: :projectlanguages

Next I update the records:

    m = Message.find(1)
    m.message_number = 'XXX'
    m.save!
 
    for lp in m.project.projectlanguages.includes(:language)
       t = lp.translations.first
      if t
        t.translation = t.translation + 'X'
        t.save!
      else
        Translation.create! message_id: m.id, projectlanguage_id: lp.id, translation: 'XXX'
      end
    end

### Expected behavior
Upon saving a record in translation, I expect that the message, the project and the projecttranslation dependent records get 'touched'.

### Actual behavior
Only project and projecttranslation dependent records get 'touched'. The project record does not get 'touched'.

But: if I remove the after_commit do end block from the Message class, then all dependent records get correctly touched. This happens even if the after_commit block contains no actual code. Just the presence of the commit do end block triggers this behaviour.

Important: This behaviour only happens if the Message record did not change the value, i.e. the value of the field message_number was already 'XXX' before the test.

Output from the log:

     (0.0ms)  begin transaction
    Message Load (0.1ms)  SELECT  "messages".* FROM "messages" WHERE "messages"."message_key" = ? ORDER BY "messages"."id" ASC LIMIT ?  [["message_key", "1"], ["LIMIT", 1]]
    Message Load (0.0ms)  SELECT  "messages".* FROM "messages" WHERE "messages"."id" = ? LIMIT ?  [["id", 2], ["LIMIT", 1]]
    Project Load (0.0ms)  SELECT  "projects".* FROM "projects" WHERE "projects"."id" = ? LIMIT ?  [["id", 2], ["LIMIT", 1]]
    Message Exists (0.1ms)  SELECT  1 AS one FROM "messages" WHERE "messages"."message_key" = ? AND "messages"."id" != ? AND "messages"."project_id" = ? LIMIT ?  [["message_key", "1"], ["id", 2], ["project_id", 2], ["LIMIT", 1]]
    Projectlanguage Load (0.2ms)  SELECT "projectlanguages".* FROM "projectlanguages" WHERE "projectlanguages"."project_id" = ?  [["project_id", 2]]
    Language Load (0.2ms)  SELECT "languages".* FROM "languages" WHERE "languages"."id" = ?  [["id", 2]]
    Translation Load (0.2ms)  SELECT  "translations".* FROM "translations" WHERE "translations"."projectlanguage_id" = ? ORDER BY "translations"."id" ASC LIMIT ?  [["projectlanguage_id", 2], ["LIMIT", 1]]
    Translation Update (0.4ms)  UPDATE "translations" SET "translation" = ?, "translation_coded" = ?, "updated_at" = ?, "lock_version" = ? WHERE "translations"."id" = ? AND "translations"."lock_version" = ?  [["translation", "memeX"], ["translation_coded", "memeX"], ["updated_at", "2018-09-24 13:05:48.585403"], ["lock_version", 1], ["id", 2], ["lock_version", 0]]
    Message Load (0.2ms)  SELECT  "messages".* FROM "messages" WHERE "messages"."id" = ? LIMIT ?  [["id", 2], ["LIMIT", 1]]
    Project Load (0.1ms)  SELECT  "projects".* FROM "projects" WHERE "projects"."id" = ? LIMIT ?  [["id", 2], ["LIMIT", 1]]
    Projectlanguage Update (0.2ms)  UPDATE "projectlanguages" SET "updated_at" = ?, "lock_version" = ? WHERE "projectlanguages"."id" = ? AND "projectlanguages"."lock_version" = ?  [["updated_at", "2018-09-24 13:05:48.588893"], ["lock_version", 2], ["id", 2], ["lock_version", 1]]
    Project Update (0.2ms)  UPDATE "projects" SET "updated_at" = ?, "lock_version" = ? WHERE "projects"."id" = ? AND "projects"."lock_version" = ?  [["updated_at", "2018-09-24 13:05:48.594625"], ["lock_version", 4], ["id", 2], ["lock_version", 3]]
     (0.8ms)  commit transaction

If I remove the after_commit do end block then the expected behaviour kicks in, the log output shows:

     (0.0ms)  begin transaction
      Message Load (0.1ms)  SELECT  "messages".* FROM "messages" WHERE "messages"."message_key" = ? ORDER BY "messages"."id" ASC LIMIT ?  [["message_key", "1"], ["LIMIT", 1]]
    Message Load (0.1ms)  SELECT  "messages".* FROM "messages" WHERE "messages"."id" = ? LIMIT ?  [["id", 2], ["LIMIT", 1]]
    Project Load (0.1ms)  SELECT  "projects".* FROM "projects" WHERE "projects"."id" = ? LIMIT ?  [["id", 2], ["LIMIT", 1]]
    Message Exists (0.1ms)  SELECT  1 AS one FROM "messages" WHERE "messages"."message_key" = ? AND "messages"."id" != ? AND "messages"."project_id" = ? LIMIT ?  [["message_key", "1"], ["id", 2], ["project_id", 2], ["LIMIT", 1]]
    Projectlanguage Load (0.1ms)  SELECT "projectlanguages".* FROM "projectlanguages" WHERE "projectlanguages"."project_id" = ?  [["project_id", 2]]
    Language Load (0.1ms)  SELECT "languages".* FROM "languages" WHERE "languages"."id" = ?  [["id", 2]]
    Translation Load (0.2ms)  SELECT  "translations".* FROM "translations" WHERE "translations"."projectlanguage_id" = ? ORDER BY "translations"."id" ASC LIMIT ?  [["projectlanguage_id", 2], ["LIMIT", 1]]
    Translation Update (0.4ms)  UPDATE "translations" SET "translation" = ?, "translation_coded" = ?, "updated_at" = ?, "lock_version" = ? WHERE "translations"."id" = ? AND "translations"."lock_version" = ?  [["translation", "memeXX"], ["translation_coded", "memeXX"], ["updated_at", "2018-09-24 13:08:33.937974"], ["lock_version", 2], ["id", 2], ["lock_version", 1]]
    Message Load (0.0ms)  SELECT  "messages".* FROM "messages" WHERE "messages"."id" = ? LIMIT ?  [["id", 2], ["LIMIT", 1]]
    Project Load (0.0ms)  SELECT  "projects".* FROM "projects" WHERE "projects"."id" = ? LIMIT ?  [["id", 2], ["LIMIT", 1]]
    Projectlanguage Update (0.1ms)  UPDATE "projectlanguages" SET "updated_at" = ?, "lock_version" = ? WHERE "projectlanguages"."id" = ? AND "projectlanguages"."lock_version" = ?  [["updated_at", "2018-09-24 13:08:33.940610"], ["lock_version", 3], ["id", 2], ["lock_version", 2]]
    Project Update (0.1ms)  UPDATE "projects" SET "updated_at" = ?, "lock_version" = ? WHERE "projects"."id" = ? AND "projects"."lock_version" = ?  [["updated_at", "2018-09-24 13:08:33.943966"], ["lock_version", 5], ["id", 2], ["lock_version", 4]]
    Message Update (0.1ms)  UPDATE "messages" SET "updated_at" = ?, "lock_version" = ? WHERE "messages"."id" = ? AND "messages"."lock_version" = ?  [["updated_at", "2018-09-24 13:08:33.942692"], ["lock_version", 2], ["id", 2], ["lock_version", 1]]
     (0.9ms)  commit transaction

### System configuration
**Rails version**: 5.2.1

**Ruby version**: 2.4.4, 2.5.1, 2.6.0 previews

**Comment by ymoxx** [comment]
Hi Fillman, here the test file.

The critical part are the lines

    after_commit do
      # This is the block that changes the DB update behavour.
      # If this block is removed, all tests succeed
    end

in the class Message.

If you remove these lines and run the test, all tests pass
If you have the lines in the code and run the tests, 2 out of 3 tests fail.
The difference in the log output is that there is no Message update at the end of the transaction.

    # frozen_string_literal: true

    begin
      require "bundler/inline"
    rescue LoadError => e
      $stderr.puts "Bundler version 1.10 or later is required. Please update your Bundler"
      raise e
    end

    gemfile(true) do
      source "https://rubygems.org"

      git_source(:github) { |repo| "https://github.com/#{repo}.git" }

      gem "rails", github: "rails/rails"
      gem "sqlite3"
    end

    require "active_record"
    require "minitest/autorun"
    require "logger"

    # This connection will do for database-independent bug reports.
    ActiveRecord::Base.establish_connection(adapter: "sqlite3", database: ":memory:")
    ActiveRecord::Base.logger = Logger.new(STDOUT)

    ActiveRecord::Schema.define do
      create_table :languages do |t|
        t.string :language
        t.integer :lock_version, null: false, default: 0
        t.timestamps
      end

      create_table :projects do |t|
        t.string :name, null: false
        t.integer :lock_version, null: false, default: 0
        t.timestamps
      end

      create_table :projectlanguages do |t|
        t.references :project, foreign_key: true
        t.references :language, foreign_key: true
        t.integer :lock_version, null: false, default: 0
        t.timestamps
      end

      create_table :messages do |t|
        t.references :project, foreign_key: true
        t.string :message_key, null: false
        t.integer :lock_version, null: false, default: 0
        t.timestamps
      end

      create_table :translations do |t|
        t.references :message, foreign_key: true, null: false
        t.references :projectlanguage, foreign_key: true, null: false
        t.text :translation, null: false
        t.integer :lock_version, null: false, default: 0
        t.timestamps
      end
    end

    # == CLASSES =====================================================

    class Project < ActiveRecord::Base
      has_and_belongs_to_many :languages, through: :projectlanguages, join_table: :projectlanguages
      has_many :messages
      has_many :projectlanguages
      has_many :translations, through: :projectlanguages
    end

    class Language < ActiveRecord::Base
      has_many :projectlanguages
      has_and_belongs_to_many :projects, through: :projectlanguages, join_table: :projectlanguages
      has_many :translations, through: :projectlanguages
      has_many :translationdecodeds
    end

    class Projectlanguage < ActiveRecord::Base
      belongs_to :language
      belongs_to :project, touch: true
      has_many :translations
    end

    class Message < ActiveRecord::Base
      belongs_to :project, touch: true
      has_many :translations, dependent: :destroy

      after_commit do
        # This is the block that changes the DB update behavour.
        # If this block is removed, all tests succeed
      end
    end

    class Translation < ActiveRecord::Base
      belongs_to :projectlanguage, touch: true
      belongs_to :message, touch: true, optional: true
      has_one :language, through: :projectlanguages
    end

    class BugTest < Minitest::Test
      def setup
        # Reset all data
        Translation.destroy_all
        Projectlanguage.destroy_all
        Message.destroy_all
        Project.destroy_all
        Language.destroy_all
        p = Project.create! name: 'Testproject'
        m = Message.create! message_key: '1', project_id: p.id
        l_en = Language.create! language: :en
        l_de = Language.create! language: :de
        pl_en = Projectlanguage.create! project_id: p.id, language_id: l_en.id
        pl_de = Projectlanguage.create! project_id: p.id, language_id: l_de.id
        Translation.create! projectlanguage_id: pl_en.id, message_id: m.id, translation: 'German'
        Translation.create! projectlanguage_id: pl_de.id, message_id: m.id, translation: 'Deutsch'
      end

      def test_without_message_update
        # This test changes the translation record but not the message record#
        # We expect that the message record gets 'touched', i.e. the lock version will increase by 1

        # Read the current lock_version
        m0 = Message.first
        lv = m0.lock_version

        ActiveRecord::Base.transaction do
          m = Message.first

          # Loop through all languages that belong to the project
          m.project.projectlanguages.includes(:language).each do |lp|
            # Read the translation
            t = lp.translations.where(message_id: m.id).first
            t.translation = t.translation + 'X'
            t.save!
          end
        end

        # A translation was changed, hence the parent record MESSAGE should be updated, i.e. lock version increase by 1
        m0.reload
        assert_equal lv + 1, m0.lock_version
      end

      def test_with_message_save_but_no_data_change
        # This test changes the translation record
        # We expect that the message record gets 'touched', i.e. the lock version will increase by 1

        # Read the current lock_version
        m0 = Message.first
        lv = m0.lock_version

        ActiveRecord::Base.transaction do
          m = Message.first
          m.message_key = m.message_key
          m.save!

          # Loop through all languages that belong to the project
          m.project.projectlanguages.includes(:language).each do |lp|
            # Read the translation
            t = lp.translations.where(message_id: m.id).first
            t.translation = t.translation + 'X'
            t.save!
          end
        end

        # Message was saved without change, i.e. no lock_version increase, a translation was changed, hence the parent record MESSAGE should be updated, i.e. lock version increase by 1
        m0.reload
        assert_equal lv + 1, m0.lock_version
      end

      def test_with_message_save_with_data_change
        # This test changes the translation record
        # We expect that the message record gets 'touched', i.e. the lock version will increase by 1

        # Read the current lock_version
        m0 = Message.first
        lv = m0.lock_version

        ActiveRecord::Base.transaction do
          m = Message.first
          m.message_key = m.message_key + 'X'
          m.save!

          # Loop through all languages that belong to the project
          m.project.projectlanguages.includes(:language).each do |lp|
            # Read the translation
            t = lp.translations.where(message_id: m.id).first
            t.translation = t.translation + 'X'
            t.save!
          end
        end

        # Message was saved with change, i.e. lock_version increase, a translation was changed, hence the parent record MESSAGE should be updated, i.e. another lock version increase
        # thus 2 in total
        m0.reload
        assert_equal lv + 2, m0.lock_version
      end
    end

**Comment by fillman** [comment]
Ok, from what I can guess looks like `after_commit` within `save!` inside the transaction marks record as being touched. I debugged the touch method and it never goes there. If you comment out `message.save` leaving after commit hook present it still works. I'm still looking into issue, but the code is very complex :)
