### ISSUE TITLE
Since `save` is wrapped in a transaction, it seems that unnecessary transactions occur when simple validations fail

### ISSUE THREAD

**Issue by morgvanny** [rails/rails#33971]
### Steps to reproduce
Example class:
```
class Thing < ApplicationRecord
  validates :name, presence: true
end
```

`Thing.new.save` results in this:
 (0.1ms)  begin transaction
  (0.1ms)  rollback transaction

Whereas the following code seems to avoid that:
```
if thing.valid?
  thing.save(validate: false)
end
```

I turned off validation within the save, to avoid ever doing that twice. In the case that it's not valid, it seems the useless empty transaction does not occur in my second code example, as opposed to the first.

Would the flow of my second example not be considered desirable default behavior for `save`? I'd rather it check validity and abort immediately, rather than begin/rollback a transaction in which nothing happens.

### System configuration
**Rails version**: 5.2.1
**Ruby version**: 2.5.1

**Comment by y-yagi** [comment]
Thanks for your report. This already fixed with #32647.
