### ISSUE TITLE
Number of seconds in a year

### ISSUE THREAD

**Issue by tasawar-hussain** [rails/rails#33978]
I have migrated my project from rails 4.2.9 to rails 5.1.6. And what i have found is strange behaviour with `ActiveSupport::CoreExtensions::Numeric::Time`. There is difference of 648 seconds. The number of seconds in rails 5 are 648 less than rails 4. approximately 10 mins. Isn't it a notable difference?

### Steps to reproduce
`1.year.to_i` # 31557600 (rails 4.2.9)
`1.year.to_i` #31556952 (rails 5.1.6)

### Expected behavior
There are around 365.25 days in year, so the number of seconds in year are calculated to be as:
`365.25*24*60*60 = 31557600.0`
And this exactly equal to what I get in rails 4.

### Actual behavior
In rails 5 , the seconds calculated are `31556952`.

### System configuration
**Rails version**: 5.1.6

**Ruby version**: 2.4.4

**Comment by prashuchaudhary** [comment]
@tasawar-hussain `1.year` is now provided by `ActiveSupport::Duration` and it follows the Gregorian calendar. Length of a `Gregorian year => 365.2425 days` which amounts to `31556952 seconds`.

What you are talking about is Julian year which is almost  11 minutes longer.

So this is no strange behavior.

**Comment by tasawar-hussain** [comment]
> @tasawar-hussain `1.year` is now provided by `ActiveSupport::Duration` and it follows the Gregorian calendar. Length of a `Gregorian year => 365.2425 days` which amounts to `31556952 seconds`.
> 
> What you are talking about is Julian year which is almost 11 minutes longer.
> 
> So this is no strange behavior.

So how do i switch back to Julian calendar, with minimal changes in my project.

**Comment by prashuchaudhary** [comment]
It was updated here. https://github.com/rails/rails/commit/cb9d0e4864fa68fad9c49b880c32e90ddf0545bd

Reason - `Value of 365.2425 days in Gregorian year is more accurate as it accounts for every 400th non-leap year.`

**Comment by matthewd** [comment]
The simplest solution is to use `365.25.days` if that's the value that you need... but they're all pretty arbitrary. You're generally better off using durations in conjunction with a date/time, which is their primary intended purpose: `Time.current + 1.year` is the same time on the same day next year, which is much more useful than `Time.current + 1.year.to_i`, 31556952 seconds from now, which is 5:49:12 later.

**Comment by matthewd** [comment]
Yeah, that's going to be wrong no matter what the value of `1.year.seconds` is.

Off the top of my head:

```ruby
age = (Date.today - date_of_birth).to_i / 365
age -= 1 while age.years.ago < date_of_birth
```

**Comment by tasawar-hussain** [comment]
> There is always the edge case of 29th of February that complicates things. And in the past, centuries ago, there is a hole in the calendar. I tried to document the behaviour of all relevant methods in those edge cases in the [AS guide](https://guides.rubyonrails.org/active_support_core_extensions.html).
> 
> For computing ages, I normally prefer to be explicit, like
> 
> ```ruby
> age = now.year - birthday.year
> if such and such
>   age += 1
> end
> ```
> 
> with the logic crystal clear expressed in terms of date attributes.

`age -= 1`

I suppose

**Comment by fxn** [comment]
I have prototyped this method (untested):

```ruby
def age(birthday)
  now = Time.current
  years = now.year - birthday.year

  if now.month > birthday.month
    years
  elsif now.month == birthday.month && now.day >= birthday.day
    years
  else
    years - 1
  end
end
```

[According to Wikipedia](https://en.wikipedia.org/wiki/February_29#Born_on_February_29), in non-leap years people born on the 29th of February may celebrate their birthday either on the 1st of March or 28th of Febryary. Also, different countries have different rules for legal-related stuff.

That code assumes March 1st, you've got to assume something I guess unless you have extra information, so the choice that gives simpler code wins!
