### ISSUE TITLE
form_with should replace form_for on Form Helper page

### ISSUE THREAD

**Issue by MSCAU** [rails/rails#33984]
I suspect that the Form Helper page at https://guides.rubyonrails.org/form_helpers.html should be updated to cover **form_with** instead of **form_for**?

**Comment by y-yagi** [comment]
Thanks for your issue. This already fixed with #33523. 
It will be updated in the next release. If you want to check the latest information before release, please refer to edge guide(https://edgeguides.rubyonrails.org/form_helpers.html). Thanks.
