### ISSUE TITLE
Timezonecode for Brasilia does not resolve to BRT when time at the timezone is called

### ISSUE THREAD

**Issue by adhithyan-4k** [rails/rails#33989]
### Steps to reproduce
Go to rails console:
Copy and run the following codes
```
t = ActiveSupport::TimeZone["Brasilia"]
current_time = t.at(Time.now.utc)
```
Now current time will be => Wed, 26 Sep 2018 02:48:49 **-03** -03:00 
I am expecting current time to be => Wed, 26 Sep 2018 02:48:49 **BRT** -03:00

The following code works fine and produces the expected result. 
```
another_t = ActiveSupport::TimeZone["Asia/Kolkata"]
current_time = another_t.at(Time.now.utc)
# current time is  Wed, 26 Sep 2018 11:57:55 IST +05:30 
```
### Expected behavior
Zone code should be always letters like BRT

### Actual behavior
Returns zone code in number instead of letters.

### System configuration
**Rails version**: 4.2.1

**Ruby version**: ruby 2.2.2p95 (2015-04-13 revision 50295) [x86_64-darwin17]

**Comment by prashuchaudhary** [comment]
@adhithyan-4k as far as I know this is not a bug in rails itself. Above test examples for `Yakutsk, Magadan, Yakutsk` as give results in format `Wed, 26 Sep 2018 19:24:20 +12 +12:00`.

Rails use Ruby timezone lib `tzinfo` internally. 

So it might not support conversion for all timezones.
