### ISSUE TITLE
js response wrapped inside default html layout

### ISSUE THREAD

**Issue by koenhandekyn** [rails/rails#33998]
### Steps to reproduce

- a simple format.js with for example inside update.js.erb or create.js.erb a simple `alert('hello')`
- form_with based form

### Expected behavior

an alert is shown after create / update

### Actual behavior

javascript error as the response seems to be wrapped inside the HTML template (layout/application.html.slim) 

### Workaround

doing the render with explicit mentioning of layout false 'fixes' the issue

`format.js { render 'update', layout: false }`

### System configuration
**Rails version**: gem 'rails', github: "rails/rails", branch: "5-2-stable"
**Ruby version**: 2.5.1

- using slim (should not have impact i assume)
- no sprockets pipeline, all with webpack

**Comment by koenhandekyn** [comment]
actually i think i found the answer in this post https://cbabhusal.wordpress.com/2016/05/04/rails-acting-weird-why-layout-is-rendered-when-format-js/ 

it seems that in the end the name of my application layout as application.slim instead of application.html.slim is confusing rails.

still i think that it would be much better if rails doesn't even try to find a template in the first place for js responses, not ?

**Comment by y-yagi** [comment]
This is expected behavior.  
If there is a layout file that does not explicitly specify MIME, it will be used for all MIME types. Please change the file name appropriately.
