### ISSUE TITLE
Migration to active storage extensively time consuming

### ISSUE THREAD

**Issue by skiffb** [rails/rails#33999]
I am running into an issue while migrating an application from paperclip to active storage. We have an application hosting millions of attached files on aws s3 buckets. I cannot seem to find a way to migrate without making millions of time consuming requests to the bucket. I have been looking into using the same object originally stored by paperclip on the bucket, and assigning this already existing key to the active storage blob. This can be done, however I run into issues when computing the checksum. As we do not have the files stored locally, and we do not have the md5 encryption of the file saved in our database, I cannot figure out a way to get the checksum without either downloading each of the millions of files and running an md5 digest on it, or by accessing the eTag with aws sdk. Accessing the eTag saves local storage space, but still involves making millions of requests, which could take many hours or even days for our production database. If I understand everything correctly, there seems to be no way to migrate from paperclip to active storage without an extensively time consuming process, unless you have stored the md5 encryption of the file in your database upon upload. Would it be possible to optionally disable using checksum to make for easier migrations, or am I missing something?

### System configuration
**Rails version**: 5.2.0

**Ruby version**: 2.4.4

**PostrgreSQL version**: 1.0.0

**Comment by skiffb** [comment]
It looks like I am able to migrate the assets in a timely manner by removing null: false constraint on checksum column in my active storage migration and placing a nil value for the files i am migrating from paperclip.

class CreateActiveStorageTables < ActiveRecord::Migration[5.2]
  def change
    create_table :active_storage_blobs do |t|
      t.string   :key,        null: false
      t.string   :filename,   null: false
      t.string   :content_type
      t.text     :metadata
      t.bigint   :byte_size,  null: false
      t.string   :checksum
      t.datetime :created_at, null: false

      t.index [ :key ], unique: true
    end

    create_table :active_storage_attachments do |t|
      t.string     :name,     null: false
      t.references :record,   null: false, polymorphic: true, index: false
      t.references :blob,     null: false

      t.datetime :created_at, null: false

      t.index [ :record_type, :record_id, :name, :blob_id ], name: "index_active_storage_attachments_uniqueness", unique: true
    end
  end
end

**Comment by y-yagi** [comment]
Please use the [mailing list](https://groups.google.com/forum/#!forum/rubyonrails-talk) or StackOverflow for questions/help, where a wider community will be able to help you. We reserve the issues tracker for issues only. Thanks.
