### ISSUE TITLE
Incorrect behavior when adding DateTime and float ActiveSupport::Duration

### ISSUE THREAD

**Issue by erozycki** [rails/rails#34008]
### Steps to reproduce

```
x = DateTime.parse("2018-1-1")
(0...1000).each { x += 0.45.seconds }
x == DateTime.parse("2018-1-1")
=> true
```

### Expected behavior
Because DateTime supports fractional seconds, I would expect x to equal `DateTime.parse("2018-1-1") + 450.seconds` after the loop. Instead, x is unchanged.

In other words, I would expect the code above to work like the code below.

```
x = DateTime.parse("2018-1-1")
(0...1000).each { x += (0.45 / 86000) }
x == DateTime.parse("2018-1-1")
=> false
```

### Actual behavior
The DateTime x is unchanged after repeated additions of fractional ActiveSupport::Durations.

### System configuration
**Rails version**:

Replicated in both 5.2.1, 4.2.6

**Ruby version**:

Replicated in both 2.5.1, 2.2.0

**Comment by Edouard-chin** [comment]
Looks like this behavior changed purposely many moons ago https://github.com/rails/rails/commit/6503da69910beb382b18127c51cd318631245607

I can't find the reason for that. Removing the call to `round` doesn't seem to affect the test suite except the two [assertions](https://github.com/rails/rails/commit/6503da69910beb382b18127c51cd318631245607#diff-00e7cdc87edbc5babf572558d2e72411R115) added in the commit above

**Comment by rafaelfranca** [comment]
Here is the issue that commit fixed http://web.archive.org/web/20071218113720/http://dev.rubyonrails.org:80/ticket/8513

**Comment by Edouard-chin** [comment]
Thanks for archive link, very useful.

The commit state 
> I've also fleshed out numeric_ext_test.rb with DateTime examples, and I snuck in a change to DateTime#since so that it rounds the seconds argument when it's a decimal, instead of raising an error.

Which I'm not sure what the "instead of raising an error" part refers to, `Rational(0.45, 86400)` doesn't raise an error. Maybe it used to on older version of ruby 🤔

**Comment by pixeltrix** [comment]
Looks like that was because `Rational` in Ruby 1.8.x used [`Integer#gcd`][1] in its constructor and so couldn't accept floats for the numerator argument. That's not the case now so almost certainly can be changed for Rails 6.0.

[1]: https://ruby-doc.org/stdlib-1.8.7/libdoc/rational/rdoc/Integer.html

**Comment by Edouard-chin** [comment]
Ohhh thanks for the explanation @pixeltrix ! I'll open a PR to modify it then
