### ISSUE TITLE
Only redirect back when route exists

### ISSUE THREAD

**Issue by tiagotex** [rails/rails#34018]
### Steps to reproduce

I have a resource that only has `:new` and `:create` actions.

The user requests `:new` and is sent to `/resource/new`.

The user doesn't fill in the required form fields so Rails renders the errors using `render :new`, this means the url is now `/resource` but the user is seeing the `:new` form with errors.

The user clicks on an action to change the locale language, this sets the cookie and redirects the user back using `redirect_back(fallback_location: root_path)`.

The user will be redirected to `/resource`, but there is no `:index` action for this resource, so the user will see the error `No route matches [GET] "/resource"`

### Expected behavior

I would expect `redirect_back` to check if the app has a route that fulfills the request, otherwise it should redirect to the fallback_location instead of raising an error.

### Actual behavior

An error is shown because no route matches the request.

### System configuration
**Rails version**:
5.2.1

**Ruby version**:
2.5.1

### Comment

I'm not sure if this is something Rails should support, so I would like your opinion.

I've looked into the `redirect_back` implementation. Maybe this could be activated when `allow_other_host` option is set to false.

```ruby
def redirect_back(fallback_location:, allow_other_host: true, **args)
  referer = request.headers["Referer"]
  redirect_to_referer = referer && (allow_other_host || _url_host_allowed?(referer))
  redirect_to redirect_to_referer ? referer : fallback_location, **args
end
```
Would become:

```ruby
def redirect_back(fallback_location:, allow_other_host: true, **args)
  referer = request.headers["Referer"]
  redirect_to_referer = referer && (allow_other_host || _valid_redirect?(referer) || _url_host_allowed?(referer))
  redirect_to redirect_to_referer ? referer : fallback_location, **args
end

def _valid_redirect?(referer)
  ActionDispatch::Routing::RouteSet.new.recognize_path(referer)
  true
rescue ActionController::RoutingError
  false
end
```

Could you give me some feedback on this?

**Comment by rafaelfranca** [comment]
`redirect_back` redirects to what the `Referer` header says. I don't think we should be resolving routes on every call for `redirect_back`.
I believe it is responsibility of the application to make sure that the user workflow works. In this case, if the route existed the user would be sent to the list of resources not the the form. So either if Rails was checking the route the workflow is still broken.

**Comment by john-denisov** [comment]
If someone is looking for a 'hacky' solution instead of addressing all of possible edgecases in your app:
```ruby
# in your controller that is responsible for locale switching
...
if params[:ignore_referer]
  redirect_to root_path
else
  redirect_back(fallback_location: root_path)
end
...

# in your locale switch link:
...
link_to(locale_name, change_locale_path(locale: locale_code, ignore_referer: !request.get?), method: :put)
...
```
