### ISSUE TITLE
Parent record's values now being reset if association validation fails, even on validate: false

### ISSUE THREAD

**Issue by jasonperrone** [rails/rails#34016]
### Steps to reproduce
This just started with 5.2.1.
So, let's say I have these models:

class Document < ApplicationRecord
  has_many :file_attachments, dependent: :destroy
end

class FileAttachment < ApplicationRecord
  belongs_to :document, optional: true
  validates_presence_of :name
end

Let's say I already have Document object d:

d = Document.find(1)

let's say d has a status attribute which is currently 'a':

d.status => 'a'

I update it.

d.status = 'b'

Now I add an invalid file attachment:

d.file_attachments << FileAttachment.new(name: nil)

Now I save my document without validation:

d.save(validate: false)

Prior to 5.2.1, it saved. As I would expect because validate is false:

d.status => 'b'

Starting with 5.2.1, it does not save, and the attribute is reset to its original value:

d.status => 'a'

### Expected behavior
Well up to 5.2.1, saving a record with an invalid association with validate: false saved the record.

### Actual behavior
Now, if there is an invalid association, validate: false appears to be ignored.

### System configuration
**Rails version**:
5.2.1

**Ruby version**:
2.5.1

**Comment by rafaelfranca** [comment]
Could you create a reproduction script with this template https://github.com/rails/rails/blob/master/guides/bug_report_templates/active_record_master.rb?

**Comment by tgturner** [comment]
Created a reproduction script here:

```ruby
# frozen_string_literal: true

begin
  require "bundler/inline"
rescue LoadError => e
  $stderr.puts "Bundler version 1.10 or later is required. Please update your Bundler"
  raise e
end

gemfile(true) do
  source "https://rubygems.org"

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  gem "rails", git: "git@github.com:rails/rails.git", branch: "master"
  gem "sqlite3"
end

require "active_record"
require "minitest/autorun"
require "logger"

# This connection will do for database-independent bug reports.
ActiveRecord::Base.establish_connection(adapter: "sqlite3", database: ":memory:")
ActiveRecord::Base.logger = Logger.new(STDOUT)


ActiveRecord::Schema.define do
  create_table :documents, force: true do |t|
    t.string :status
  end

  create_table :file_attachments, force: true do |t|
    t.integer :document_id
    t.string :name
  end
end

class Document < ActiveRecord::Base
  has_many :file_attachments, dependent: :destroy
end

class FileAttachment < ActiveRecord::Base
  belongs_to :document, optional: true
  validates_presence_of :name
end

class BugTest < Minitest::Test
  def test_association_stuff
    Document.create!(status: "a")
    d = Document.find(1)
    d.status = "b"

    d.file_attachments << FileAttachment.new(name: nil)
    d.save(validate: false)
    d.reload
    assert_equal "b", d.status
  end
end
```

**Comment by jasonperrone** [comment]
Thank you @tgturner .

Here's that block of code in 5.2.1:
 if autosave != false && (@new_record_before_save || record.new_record?)
                if autosave
                  saved = association.insert_record(record, false)
                elsif !reflection.nested?
                  if reflection.validate?
                    valid = association_valid?(reflection, record, index)
                    saved = valid ? association.insert_record(record, false) : false
                  else
                    association.insert_record(record)
                  end
                end
              elsif autosave
                saved = record.save(validate: false)
              end

Doesn't it seem that if the association is to be validated it calls insert_record with validate false, and if it is not to be validated calls insert_record with validate = true? Seems backwards, doesn't it?

**Comment by tgturner** [comment]
Ok, I think we are still doing the correct thing here:

code says this regarding reflections: https://github.com/tgturner/rails/blame/master/activerecord/lib/active_record/reflection.rb#L560

So `validate: false` doesn't work on `has_many`

Secondly, what is happening in the code you posted, I believe, is that it is first checking if the association is valid, then calling insert_record if we know that the association is already valid, or returning false, if like in our case, it is not valid.

Hope that helps clarify some of this.

**Comment by jasonperrone** [comment]
Except that validate: false was working on has_many <= 5.1.6...
We're missing something...

**Comment by jasonperrone** [comment]
I mean the code does indicate that collections get validated regardless. Maybe something prevented it from working till 5.2.1, but it does leave the question of, fine, how do I say validate the collection when validating the parent, but do not validate the collection when not validating the parent.
