### ISSUE TITLE
Unable to run tests with `bundle exec ruby`

### ISSUE THREAD

**Issue by eatwithforks** [rails/rails#34025]
I was expecting this to work as it does with every other ruby project ... but it did not ... please auto-add `test` to the LOAD_PATH

```
bundle
bundle exec ruby test/cache/stores/mem_cache_store_test.rb
Traceback (most recent call last):
	1: from rails/activesupport/test/cache/stores/mem_cache_store_test.rb:3:in `<main>'
rails/activesupport/test/cache/stores/mem_cache_store_test.rb:3:in `require': cannot load such file -- abstract_unit (LoadError)
```

**Comment by y-yagi** [comment]
Please see https://guides.rubyonrails.org/contributing_to_ruby_on_rails.html#running-tests for instructions on how to run tests. Thanks.
