### ISSUE TITLE
ActiveStorage direct upload fails on gzipped files

### ISSUE THREAD

**Issue by conzett** [rails/rails#34058]
### Steps to reproduce

1. Vanilla ActiveStorage `has_one_attached` file setup using disk storage locally
2. Add `direct_upload: true` for file field like so:
```erb
<%= form_with model: import_file do |form| %>            
  <div class="form-group">                               
    <%= form.label :file, %>            
    <%= form.file_field :file, direct_upload: true, required: true %>                                  
  </div>                                                 
<% end %>
```
3. Gzip a file of any size e.g. `gzip my_file.csv`
4. Upload file via the file input                      

### Expected behavior
Direct upload should process like any other file

### Actual behavior
Get a `422` Unprocessable entity on a subsequent `PUT` request to the ActiveStorage controller. Regular file uploads work and direct uploads work if they are in any other format besides gzipped.

### System configuration
**Rails version**: 5.2.1
**Ruby version**: 2.5

**Comment by jeremy** [comment]
Do you see a validation error or similar in your logs?

**Comment by jeremy** [comment]
Cool, [taking a peek at ActiveStorage::DiskController#update](https://github.com/rails/rails/blob/bfea0af4ba7d717d6a065b4370e3ccfd8869dde6/activestorage/app/controllers/active_storage/disk_controller.rb#L22-L26), can see it's returning a 422 response when the `acceptable_content?` check fails. Looks like the stated [Content-Type and Content-Length don't match](https://github.com/rails/rails/blob/bfea0af4ba7d717d6a065b4370e3ccfd8869dde6/activestorage/app/controllers/active_storage/disk_controller.rb#L63-L65), which does smell like a gzip issue! Something's uncompressing the file, perhaps, or the original byte_size is of the uncompressed file instead of the compressed one?

**Comment by conzett** [comment]
@jeremy that does seem to be the issue! It looks like `token[:content_type]` is set to `"application/x-gzip"` while `request.content_type` is `"application/gzip"`. Content length seems to be correct for both.

It looks like [Rails provides an alias for the gzip mimetype](https://github.com/rails/rails/blob/b2eb1d1c55a59fee1e6c4cba7030d8ceb524267c/actionpack/lib/action_dispatch/http/mime_types.rb#L50) out of the box, so in this case

```ruby
Mime::Type.lookup(request.content_type) == token[:content_type]
```

would do the trick, but I'm not sure if there's a larger with with where the mismatch is happening that would need a more comprehensive change.

**Comment by jeremy** [comment]
Seems like that'd affect other aliased content types, huh?

**Comment by conzett** [comment]
It does appear that way, although I can't find a file type that produces the same result. The response from the initial `POST` to the direct_uploads route is returning `content_type: "application/x-gzip"` in the JSON payload, but I'm not sure where that's coming from as Marcel returns "application/gzip" when running `Marcel::MimeType.for` on the same file.

I'll try and dig in more tomorrow, thanks for the direction!

**Comment by y-yagi** [comment]
Fixed by #34116

**Comment by deepj** [comment]
Can be this backported to Rails 5.2? This patch solves our issue with uploading XML files and ActiveStorage.

**Comment by y-yagi** [comment]
@deepj  Already backported to 5-2-stable 5fb4703471ffb11dab9aa3855daeef9f592f6388
