### ISSUE TITLE
String#parameterize raises Encoding::CompatibilityError for non-Unicode Strings on master

### ISSUE THREAD

**Issue by alimi** [rails/rails#34062]
### Steps to reproduce

Run this script https://gist.github.com/alimi/169f192784c69383272c1258cba65759. The tests with `non_unicode_string` will raise the exception.

Run https://gist.github.com/alimi/b8071867f4611a54eb9647ac5d0241a4 to verify it works on 5.2.

### Expected behavior

Before Rails 6, `String#parameterize` and the underlying methods it calls supported non-Unicode strings. Maybe they still should in Rails 6?

### Actual behavior

`String#parameterize` and the underlying methods it calls no longer support non-Unicode strings. They now raise `Encoding::CompatibilityError`s.

It looks like the change in behavior was introduced in https://github.com/rails/rails/pull/26743. `String#parameterize` eventually calls `ActiveSupport::Unicode::Multibyte#normalize`. `#normalize` [used to do a bunch of stuff](https://github.com/rails/rails/blob/fc5dd0b85189811062c85520fd70de8389b55aeb/activesupport/lib/active_support/multibyte/unicode.rb#L274) and now it's [mostly a wrapper around the native Ruby method](https://github.com/rails/rails/blob/cf608ee34dd833b0357ef4eefa692db33242d2aa/activesupport/lib/active_support/multibyte/unicode.rb#L108).

### System configuration
**Rails version**: master

**Ruby version**: 2.5.0p0

/cc @eileencodes @rafaelfranca @mtsmfm

**Comment by rafaelfranca** [comment]
Good find. Yes, I think we should maintain the behavior. Maybe we can change the encode to utf8 and pass a utf8 string to the Ruby API?

@mtsmfm can you investigate?

**Comment by mtsmfm** [comment]
I'll have a look at

**Comment by mtsmfm** [comment]
I found the previous implementation of `ActiveSupport::Unicode::Multibyte#normalize` doesn't work well with non-unicode strings.

```ruby
# Fullwidth Latin Capital Letter A in Windows 31J
str = "\u{ff21}".encode(Encoding::Windows_31J)
result = ActiveSupport::Multibyte::Unicode.normalize(str)
# This `result` should A ("\u{41}") but got another char, 艠 ("\u{8260}")
puts result # => 艠
p result.codepoints # => [33376]
```

>  I think we should maintain the behavior.

The above example shows unwanted and unexpected result.
So I think current behavior with non-unicode string is not defined.
If so, I think it's ok to raise an error if the string is non-unicode one.
I'll add a test to clarify the behavior.

@rafaelfranca What do you think?

**Comment by vedant1811** [comment]
Looks like this issue slipped through.

@rafaelfranca I agree with @mtsmfm.

**Comment by rafaelfranca** [comment]
@mtsmfm Sounds good. Can you open a PR with the test?

**Comment by mtsmfm** [comment]
Sure!

**Comment by cbothner** [comment]
`String#parameterize` still raises for non-Unicode strings on master. It makes sense that `ActiveSupport::Unicode::Multibyte#normalize` raises in that case, but since parameterize is higher-level, should it not convert to UTF8 automatically?
