### ISSUE TITLE
Missing/wrong information for ActionMailer::Base.smtp_settings.authentication symbols

### ISSUE THREAD

**Issue by BerkhanBerkdemir** [rails/rails#34065]
The documentation says for `ActionMailer::Base.smtp_settings.authentication` can have these three symbols `:plain`, `:login` and `:cram_md5`.

So, is there any difference between `:plain` and `:login` because it says _will send the password Base64 encoded_ for both.

[`ActionMailer::Base`](https://github.com/rails/rails/blob/master/actionmailer/lib/action_mailer/base.rb#L400-L404)

**Comment by rafaelfranca** [comment]
There are differences for the server but both uses Base64 encoded strings.

See http://www.samlogic.net/articles/smtp-commands-reference-auth.htm
