### ISSUE TITLE
url helper work wrong with subdomain, when hole application lives on subdomain

### ISSUE THREAD

**Issue by fanantoxa** [rails/rails#34072]
### Steps to reproduce

```
# do in in a view
root_url 
root_url(subdomain: 'test')
```
### Expected behavior
Hole rails application lives on subdomain ex.: `https://rails.example.com`
I'm trying to generate a link on subdomain and expect to have a link in 3rd level subdomian
```
  root_url # => https://rails.example.com
  root_url(subdomain: 'test') # => https://test.rails.example.com
```
### Actual behavior
But helper removes main subdomain instead
```
  root_url # => https://rails.example.com
  root_url(subdomain: 'test') # => https://test.example.com
```
Same issue with `*_url` to different routes
### System configuration
**Rails version**: 5.1.6

**Ruby version**: 2.5.1

**Comment by pixeltrix** [comment]
Hi @fanantoxa - this is because Rails assumes a top level domain length of 1 when working out what's the domain and subdomain. In your case you want a tld_length of 2, e.g:

``` ruby
root_url(subdomain: "test", tld_length: 2) # => https://test.rails.example.com/
```

If you want it set application-wide you can add it to `default_url_options`, e.g:

``` ruby
# Put this in config/routes.rb
default_url_options host: "https://rails.example.com", tld_length: 2

root_url(subdomain: "test") # => https://test.rails.example.com/
```
