### ISSUE TITLE
travel_to and travel count time differently when dealing with DST change

### ISSUE THREAD

**Issue by cryptogopher** [rails/rails#34082]
### Steps to reproduce
```
  def test_travel
    # this works
    travel_to(Date.new(2018, 5, 1))

    start = Date.current
    travel_to(Date.current - 1.month)
    travel(1.month)
    assert_equal start, Date.current

    # this doesn't work
    travel_to(Date.new(2018, 4, 1))

    start = Date.current
    travel_to(Date.current - 1.month)
    travel(1.month)
    assert_equal start, Date.current
  end
```

### Expected behavior
After traveling back and forward by the same amount of days we should end on the same day we started.

### Actual behavior
There is one day lost on way back. This happens only when there is DST change between endpoints.
```
$ ruby test/integration/issue_recurrences_test.rb --name test_travel
Run options: --name test_travel --seed 18224

# Running:

F

Finished in 0.217769s, 4.5920 runs/s, 9.1840 assertions/s.

  1) Failure:
IssueRecurrencesTest#test_travel [test/integration/issue_recurrences_test.rb:165]:
Expected: Sun, 01 Apr 2018
  Actual: Sat, 31 Mar 2018

1 runs, 2 assertions, 1 failures, 0 errors, 0 skips
```

### System configuration
**Rails version**:
```
$ rails --version
Rails 4.2.10
```
**Ruby version**:
```
$ ruby --version
ruby 2.3.6p384 (2017-12-14 revision 61254) [x86_64-linux]
```

**Comment by y-yagi** [comment]
4.2 series are not supported anymore for anything besides severe security fixes.  
Can you check whether the issue can be reproduced with the latest Rails? 

Also, can you create a reproduce script with this [template](https://github.com/rails/rails/blob/master/guides/bug_report_templates/generic_gem.rb)?

**Comment by cryptogopher** [comment]
Sorry for not providing template results upfront.

Error is not reproducible with:
Ruby: ruby 2.4.4p296 (2018-03-28 revision 63013) [x86_64-linux]
Rails: 6.0.0.alpha from https://github.com/rails/rails.git (at master@c9e0a61)

So I guess it has been fixed in meantime.

Thank you for help!
