### ISSUE TITLE
Incorrect math calculation

### ISSUE THREAD

**Issue by nshganesh** [rails/rails#34090]
### Steps to reproduce
Hello,
We are seeing this unexpected behaviour. when we do multiplication by 100 to multiples of 7.
![screenshot from 2018-10-05 12-55-07](https://user-images.githubusercontent.com/14258513/46521664-e740bb80-c89d-11e8-8a46-8fc45a561adf.png)

### Expected behavior
`0.7*100 = 7.0`
`0.14*100 = 14.0`
`0.28 * 100 = 28.0`

### Actual behavior
`0.7*100 = 7.000000000000001`
`0.14*100 = 14.000000000000002`
`0.28 * 100 = 28.000000000000004`

### System configuration
**Rails version**: Rails 5.1.4 or Rails 5.1.6

**Ruby version**: ruby 2.4.1p111 (2017-03-22 revision 58053)

**Comment by sikachu** [comment]
Thank you for your report. However, this issue is not directly a Rails'. So I'm going to close this.

The issue you reported is a common issue dealing with floating point number, and it's not only in Ruby. You might want to read up why this is happening in https://floating-point-gui.de/.
