### ISSUE TITLE
Stop adding packets that you have developed for your business

### ISSUE THREAD

**Issue by cooldesigns** [rails/rails#34113]
Hey Reader, please comment if you agree.

WHY??
They are not fit for our business.

They are not the best decision for all applications.

ActiveStroage has many logic decides. I am doing all the job on clients and storing a string simply. or I can use Shrine, or prefering a blob microservice.

ActionCable is good, but the comments are valid what I said about ActiveStroage. (Faye is good to)

I prefer jbuilder or GraphQL! Not AMS. It's look like duplicated code. He does not have practical methods.

I couldn't saw benefits of Stimulus. A controller acting nothing than a function. What is magic?
Trix is a small library. Are you aware of the JS has billions of library?

Why I not use webpack alternatives, JS world have better ones and this is a company decision. Why lefting sprockets? Sprockets must evolve as webpack, webpack is not part of rails. We don't like it.

ActionView the most important the magic part of rails, which is making rails powerful has no active development. Why? You are making wrong investment. ActionView need some js, in rails way. We must have state, when we need state. We don't need React, we need a rails way of making state-fully, component based view architecture. ActionView is the foots of rails. Rails can't walk without it.

WHAT IS THE MOST IMPORTANT PROBLEM?
-    There is no difference between core's of rails 4 and rails 6
-    So it's not interesting, no interest = dying

Rails have to evolve for facilitate practical real-time applications. This is world trend. It is helped us for 10 years. It is so good for past time. If we want to keep it alive, We have to stop adding junk packets and change something in it's CORE, we have to make it stronger.

**Comment by jeremy** [comment]
[Rails is omakase](https://rubyonrails.org/doctrine/#omakase)—the chef decides. But you're free to choose, from there. This is a strength.
