### ISSUE TITLE
Getting error in includes associations

### ISSUE THREAD

**Issue by sumit-rvtech** [rails/rails#34124]
Hi,

I am not able to use includes with assosiations:
Book.includes(:chapters)

ArgumentError (wrong number of arguments (given 2, expected 3))

getting error with rails 5.2.0.
Please suggest.

**Comment by gregmolnar** [comment]
Could you please create an executable test case based on this template? https://github.com/rails/rails/blob/master/guides/bug_report_templates/active_record_gem.rb

**Comment by y-yagi** [comment]
Please use the [mailing list](https://groups.google.com/forum/#!forum/rubyonrails-talk) or StackOverflow for questions/help, where a wider community will be able to help you. We reserve the issues tracker for issues only. Thanks.
