### ISSUE TITLE
Unable to use inner_options on application routes inside ActiveStorage controllers

### ISSUE THREAD

**Issue by jhubert** [rails/rails#34121]
This has burned far more hours of my time than I should publicly admit. I still haven't figured out WHY this is happening, but I've at least boiled it down to an executable test.

The issue is that we are overwriting the ActiveStorage::BlobsController class to put it under our ApplicationController so that all of the security before_actions get run on it. But, the url_helpers that are called in the before_actions fail if they contain any inner_options.

For example, `login_path` works while `login_path({})` fails.

I've traced this down and it seems that ActiveStorage creates it's own RouteSet that gets checked, but doesn't seem to check the Rails application RouteSet.

Note that I don't really know what I'm talking about here. I'm a little lost going through this. I'm hoping the test case can help someone more familiar with the routing / engine system shed some light on it. (cc @pixeltrix ?)

I think I've boiled it down to the `login_path` working because it's getting loaded from the OptimizedUrlHelper but the presence of inner_options causes the OptimizedUrlHelper to be skipped.

### Steps to reproduce

GIST: https://gist.github.com/jhubert/f9ce8fc0f8147089a481af1433cdbd69

```ruby
begin
  require 'bundler/inline'
  require 'pry'
rescue LoadError => e
  $stderr.puts 'Bundler version 1.10 or later is required. Please update your Bundler'
  raise e
end

gemfile(true) do
  source 'https://rubygems.org'

  gem 'rails', '5.2.1'
end

require 'rack/test'
require 'active_storage/engine'
require 'action_controller/railtie'

class TestApp < Rails::Application
  config.root = File.dirname(__FILE__)
  config.session_store :cookie_store, key: 'cookie_store_key'
  secrets.secret_token    = 'secret_token'
  secrets.secret_key_base = 'secret_key_base'

  config.eager_load = false
  config.logger = Logger.new($stdout)
  Rails.logger  = config.logger
end

Rails.application.initialize!

TestApp.routes.draw do
  get '/blob' => 'active_storage/blobs#show'
  get '/test' => 'test#show'
  get '/login' => 'sessions#new', as: :login
end

class ApplicationController < ActionController::Base
  before_action :redirect_to_login

  private

  def redirect_to_login
    if params[:inner_options]
      redirect_to login_path({})
    else
      redirect_to login_path
    end
  end
end

class ActiveStorage::BaseController < ApplicationController
  protect_from_forgery with: :exception

  before_action do
    ActiveStorage::Current.host = request.base_url
  end
end

class SessionsController < ApplicationController
  def new
    render text: 'login'
  end
end

class TestController < ApplicationController
  def show
    render text: 'test'
  end
end

class ActiveStorage::BlobsController < ActiveStorage::BaseController
  def show
    render text: 'blob'
  end
end

require 'minitest/autorun'

class TestControllerTest < ActionDispatch::IntegrationTest
  test "should redirect to the login page" do
    get '/test'
    assert_equal 302, response.status
    assert_equal "http://www.example.com/login", response.headers["location"]
  end

  test "should redirect to the login page with inner_options" do
    get '/test?inner_options=1'
    assert_equal 302, response.status
    assert_equal "http://www.example.com/login", response.headers["location"]
  end
end

class ActiveStorage::BlobsControllerTest < ActionDispatch::IntegrationTest
  test "should redirect to the login page" do
    get '/blob'
    assert_equal 302, response.status
    assert_equal "http://www.example.com/login", response.headers["location"]
  end

  test "should redirect to the login page with inner_options" do
    get '/blob?inner_options=1'
    assert_equal 302, response.status
    assert_equal "http://www.example.com/login", response.headers["location"]
  end
end
```

### Expected behavior

I would expect `login_path` and `login_path({})` to have the same behavior, either be found or not found.

### Actual behavior

`login_path` works
`login_path({})` fails with ActionController::UrlGenerationError

### System configuration
**Rails version**: 5.2.1

**Ruby version**: 2.5.1

**Comment by pixeltrix** [comment]
@jhubert yes, you're correct that passing options to a url helper bypasses the optimised helper and the reason that Active Storage has it's own route set is because it's an isolated engine. A lot of the routes in Active Storage use the `direct` and `resolve` methods to map the models and generate custom url helpers so It's possible there's an edge case there where calling from an engine to a main app's custom url helpers is broken - will take a look.
