### ISSUE TITLE
Rails Enum with private, public keyword can't work

### ISSUE THREAD

**Issue by huacnlee** [rails/rails#34129]
For example:

```rb
class Repository
  enum privacy: %i(private public)
class
```

This will raise:

```
ArgumentError (You tried to define an enum named "privacy" on the model "Repository", but this will generate a class method "private", which is already defined by Active Record.)
```

In this case, because of the `private`, `public` is a keywords of Ruby class, but I saw the real reason is this line: https://github.com/rails/rails/blob/v5.2.1/activerecord/lib/active_record/enum.rb#L200

```diff
++ # scope :active, -> { where(status: 0) }
++ klass.send(:detect_enum_conflict!, name, value_method_name, true)
++ klass.scope value_method_name, -> { where(attr => value) }
```

Rails enum wants to define a scope name with `Repository.private`, `Repository.public`, but the `dangerous_class_method?` now allow to uses that keywords.

How about add an option `scope_prefix / scope_suffix` for change the scope name?

```rb
class Repository
  # Repository.privacy_public, Repository.privacy_private
  enum privacy: %i(private public), _scope_prefix: true
  # Repository.in_public, Repository.in_private
  # enum privacy: %i(private public), _scope_prefix: :in
end
```

So, we will still use `enum privacy: %i(private public)`.

```rb
repository.private!
repository.private?
repository.public!
repository.public?
Repository.privacy_public.order("id desc")
Repository.privacy_private.order("id desc")
```

----

I don't want use the other words, in [this case](https://github.com/new), the `private`, `public` are the best and the gracefully choice.

![default](https://user-images.githubusercontent.com/5518/46648453-c347e780-cbc7-11e8-9be7-7e5648ab8f44.png)

**Comment by aniliyidogan** [comment]
Hi @huacnlee 

```
class Conversation < ActiveRecord::Base
  enum status: [:active, :archived], _suffix: true
  enum comments_status: [:active, :inactive], _prefix: :comments
end
```

https://api.rubyonrails.org/v5.2/classes/ActiveRecord/Enum.html
