### ISSUE TITLE
Using formats option with render partial affects subsequent render partial calls

### ISSUE THREAD

**Issue by JasonBarnabe** [rails/rails#34138]
Rails 5.2.1 / 6.0a
Ruby 2.5.1

Test app: https://github.com/kickbooster/PartialFormatTest . [Relevant code is](https://github.com/kickbooster/PartialFormatTest/blob/master/app/views/home/index.html.erb):

```erb
<%= render partial: 'multiformat_partial' %>
<script>
  <%= render partial: 'js_partial', formats: [:js] %>
</script>
<%= render partial: 'multiformat_partial' %>
```

I expect that the first and third `render` calls both render `_multiformat_partial.html.erb`. Instead, the first is rendering `_multiformat_partial.html.erb`, while the third is rendering `_multiformat_partial.js.erb`.

Expected results:
```html
Multiformat partial (HTML)

<script>
  // Some code

</script>
Multiformat partial (HTML)
```

Actual results:
```html
Multiformat partial (HTML)

<script>
  // Some code

</script>
Multiformat partial (JS)
```

**Comment by y-yagi** [comment]
Thanks for your issue. But this is intentional behavior. 
In the partial render, the last used format is used preferentially.
https://github.com/rails/rails/blob/8df7ed3b88fc9f19446d7207a745a331893b81cd/actionview/test/template/render_test.rb#L66-L69 

For more detailed reasons, please see #6626.
