### ISSUE TITLE
ActiveRecord QueryCache is not cleared when reloading associations

### ISSUE THREAD

**Issue by christophemaximin** [rails/rails#34133]
### Steps to reproduce

Failing tests: https://gist.github.com/christophemaximin/049b86053f4f9f54954bd5e8a66d2eb4

### Expected behavior

Cache should be cleared when calling `reload` on associations

### Actual behavior

It isn't.
A fix is present here as a pull request: https://github.com/rails/rails/pull/34094
### System configuration

**Rails version**:
Rails 3 + Rails 4 + Rails 5 + Edge

**Ruby version**:
2.5.1

**Comment by kamipo** [comment]
Fixed by #34094.
