### ISSUE TITLE
`exists` subquery has missing bind param when prepared_statements is false

### ISSUE THREAD

**Issue by CharlesMcMillan** [rails/rails#34183]
### Steps to reproduce

Here is a test showing the issue:
```ruby
   def test_exists_subquery_without_prepared_statements
     liquid = Liquid.create(:name => 'salty')
     ActiveRecord::Base.connection.instance_variable_set(:@prepared_statements, false)
     molecule = liquid.molecules.create(:name => 'molecule_1')
     molecule.electrons.create(:name => 'electron_1')
     molecule.electrons.create(:name => 'electron_2')
     liquids = Liquid.where.not(Molecule.where('molecules.liquid_id = liquid.id').where(molecules: { name: 'test' }).exists)
     assert_equal 1, liquids.length
   end
```

Apologies for the weird setup + turning off of prepared_statements in a very non-standard way 😨 

I am seeing a related issue [here](https://github.com/rails/rails/issues/24893), though that involves directly issuing exec_query directly

### Expected behavior
The relation should not error

### Actual behavior
PG Syntax error:
```
ActiveRecord::StatementInvalid: SQLite3::SQLException: near ")": syntax error: SELECT "liquid".* FROM "liquid" WHERE (NOT (EXISTS (SELECT "molecules".* FROM "molecules" WHERE (molecules.liquid_id = liquid.id) AND "molecules"."name" = )))
```

Note the last missing bind param

### System configuration
**Rails version**: This test fails for me on v5.0.7 and v5.1.6, but it passes on  v5.2.1

**Ruby version**: ruby 2.4.3p205

**Comment by kamipo** [comment]
This is fixed by 213796fb4936dce1da2f0c097a054e1af5c25c2c, but that change is hard to backport to older branch. Use 5.2 please.
