### ISSUE TITLE
ActiveStorage blob.service_url_for_direct_upload should sign content_type?

### ISSUE THREAD

**Issue by patrickdonovan** [rails/rails#34182]
### Steps to reproduce

I am attempting to use AS for direct uploads to GCS. My app uses a graphql api so I am using blob's `service_url_for_direct_upload` / `service_headers_for_direct_upload` methods rather than the included controller's endpoint. When using those values in the client, I run into 403s from GCS that I don't encounter with `curl`. The reason is that the browser is adding a content_type header that AS is not signing.

### Expected behavior
The provided content-type should be included in the call to the bucket's signature and also returned in the headers_for_direct_upload.

### Actual behavior
It is not, and the signed url gets 403s from GCS when used in the browser.

### System configuration
**Rails version**: 5.2.1

**Ruby version**: 2.5.1

### My investigation:

ActiveStorage::Blob's [service_url_for_direct_upload](https://github.com/rails/rails/blob/master/activestorage/app/models/active_storage/blob.rb#L139-L141) calls `service.url_for_direct_upload key, expires_in: expires_in, content_type: content_type, content_length: byte_size, checksum: checksum`

[Service::GCSService's url_for_direct_upload](https://github.com/rails/rails/blob/master/activestorage/lib/active_storage/service/gcs_service.rb#L99-L101) creates signed urls with `bucket.signed_url key, method: "PUT", expires: expires_in, content_md5: checksum`, implemented in GCS's ruby sdk [here](https://github.com/googleapis/google-cloud-ruby/blob/master/google-cloud-storage/lib/google/cloud/storage/bucket.rb#L1354-L1366). AFAICT by looking and by `pry`ing in, content_type is not included by AS in the params to be signed.

This has the result that when using the url from blob.service_url_for_direct_upload in the browser, which adds content-type headers, I get 403s from GCS. As [their docs indicate under "Components of the string that requires signing"](https://cloud.google.com/storage/docs/access-control/signed-urls), content_type is indeed salient.

If I simply change ActiveStorage::Service::GCSService's `url_for_direct_upload`'s signature to include a `content_type:` keyword argument and pass that along to `signed_url` then everything works. Arguably also GCSService's `headers_for_direct_upload` should include the content-type header since it was used in the calculation of the signature.

So - am I missing something about how I should be using these methods and/or making the client's request with the returned values? Or should I open a PR?

cc @rafaelfranca

**Comment by georgeclaghorn** [comment]
Active Storage intends to leave the `Content-Type` on the stored object unset. When it’s set, GCS prevents us from controlling the response `Content-Type` on download via the `response-content-type` URL parameter.

If you’re uploading via JS, take care to strip the `Content-Type` from each `File` before submitting it to GCS. You can do that by calling [`Blob.slice()`](https://developer.mozilla.org/en-US/docs/Web/API/Blob/slice) with no arguments. See e0867b3.
