### ISSUE TITLE
Set method doesn't work with has_many through and where clause in lambda

### ISSUE THREAD

**Issue by danglduy** [rails/rails#34191]
### Steps to reproduce
4 models

`Role`
id: 1 - name: "Actor"
id: 2 - name: "Director"

`Person`
id: 1 - name: "abc"
id: 2 - name: "def"
id: 3 - name: "xyz"

`Film`
id: 1 - name: "Shawshank Redemption"

```Ruby
has_many :film_roles
has_many :people, through: :film_roles
has_many :actors, -> {where "film_roles.role_id = ?", 1},
  class_name: "Person", through: :film_roles, source: :person
```

`FilmRole`

```Ruby
belongs_to :role
belongs_to :film
belongs_to :person
```
--------------
Console (rails c):
```Ruby
Film.first.actor_ids = [1]
```

### Expected behavior
A new record is created in `film_roles` table with information: role_id: 1, person_id: 1, film_id: 1

### Actual behavior
```
Error:
(0.5ms)  ROLLBACK
Traceback (most recent call last):
        1: from (irb):113
ActiveRecord::RecordInvalid (Validation failed: Role must exist)
```

## 2nd Reproduce

`FilmRole`

```Ruby
belongs_to :role, optional: true
belongs_to :film
belongs_to :person
```
--------------
Console (rails c):

```Ruby
Film.first.actor_ids = [1]
```

### Expected behavior
A new record is created in `film_roles` table with information: role_id: 1, person_id: 1, film_id: 1

### Actual behavior
A new record is created in `film_roles` table with information: person_id: 1, film_id: 1

### System configuration
Ubuntu 18.04
**Rails version**: 5.2.1

**Ruby version**: 2.5.1

**Comment by y-yagi** [comment]
Can you create a reproduce script with this [template](https://github.com/rails/rails/blob/master/guides/bug_report_templates/active_record_gem.rb)
