### ISSUE TITLE
Allow `UNLOGGED` Postgres tables when `Rails.env.test?`

### ISSUE THREAD

**Issue by JacobEvelyn** [rails/rails#34192]
[Postgresql documentation](https://www.postgresql.org/docs/current/static/non-durability.html) indicates that there are ways to reduce database durability in exchange for better performance. Obviously this is very dangerous to do in production, but there are a fair number of anecdotes online regarding test speedups people have gotten by reducing their database durability.

Most of these can be accomplished easily outside of Rails, but [creating `UNLOGGED` tables](https://www.postgresql.org/docs/current/static/sql-createtable.html#SQL-CREATETABLE-UNLOGGED) (which, according to the Postgres docs, are "considerably faster than ordinary tables") seems to have a natural fit with the `CREATE TABLE` calls that come from Rails with commands like `rails db:schema:load`.

Would the Rails team support a PR that allows `CREATE TABLE` using the Postgres adapter to become `CREATE UNLOGGED TABLE` when `Rails.env.test?` is true and some optional setting (maybe in `test.rb`?) is enabled?

**Comment by y-yagi** [comment]
Thank you so much for the issue but we don't take feature request on the issue tracker. We recommend you to try to implement the feature and send us a pull request or if you are in doubt if the feature will be accepts ask in [Rails Core mailing list](https://groups.google.com/forum/#!forum/rubyonrails-core) for feedback. Thanks.
