### ISSUE TITLE
config_for returns an empty hash for YAML files without environment keys

### ISSUE THREAD

**Issue by MothOnMars** [rails/rails#34193]
### Steps to reproduce
1. Create a config file without keys per environment:
```
config/foo.yml

bar:
  baz: quux
```
2. Attempt to load the information for the current Rails env:
```
> Rails.application.config_for(:foo)
```

### Expected behavior
TBD. I *think* the desired behavior would be to simply return the YAML values:
```
> Rails.application.config_for(:foo)
{
    "bar" => {
        "baz" => "quux"
    }
}
```
Other options would be to return nil or raise an error. I can put in a PR for whatever the desired behavior is.

### Actual behavior
An empty hash is returned:
```
> Rails.application.config_for(:foo)
{}
```

### System configuration
**Rails version**:
5.1.4

**Ruby version**:
2.3.7

**Comment by luisenrike** [comment]
Why don't just use `foo = YAML.load_file("#{Rails.root.to_s}/config/foo.yml")`?

If you check the source code for `config_for` you'll see that is just a wrapper for `YAML.load_file`

**Comment by y-yagi** [comment]
As documented in doc, `config_for` loads the value associated with the current Rails env. 
https://api.rubyonrails.org/classes/Rails/Application.html#method-i-config_for 

So that is expected behavior.
