### ISSUE TITLE
Misleading documentation on counters within partials

### ISSUE THREAD

**Issue by MSCAU** [rails/rails#34199]
The official Rails Guide on Layouts and Rendering (https://guides.rubyonrails.org/layouts_and_rendering.html#using-partials) contains the following information box:

> Rails also makes a counter variable available within a partial called by the collection, named after the title of the partial followed by _counter. For example, when rendering a collection @products the partial _product.html.erb can access the variable product_counter which indexes the number of times it has been rendered within the enclosing view.

This is not wholly accurate as when using the :as option, the counter within the partial needs to be named after the alias rather than the partial.

For example:

`<%= render partial: 'comment', collection: @post .comments, as: :foobar %>`

requires me to specify the counter in the partial as **foobar_counter**.

**Comment by MSCAU** [comment]
See also https://stackoverflow.com/questions/52772274/rails-5-2-partial-counter-undefined-local-variable-or-method-error/52772518 where I was asking SO for help on this.

**Comment by y-yagi** [comment]
Thanks for creating an issue. 
I think that it is good to add notes when using the `as` option. Can you create a PR?

**Comment by lucasprag** [comment]
I have some time now and I will try to create a PR as soon as possible for this if you guys didn't start working on it yet.
Thanks 😄
