### ISSUE TITLE
CSP with a proc attribute fails in redirection routes.

### ISSUE THREAD

**Issue by viraptor** [rails/rails#34200]
### Steps to reproduce

1. Add a content_security_policy with an option specified via a `proc`. For example:

```
  policy.report_uri(proc { "..." if Random.rand(100.0) < 0.002 })
```

2. Add a route with redirect. For example:

```
get 'author/top_authors', to: redirect('/authors/top')
```

### Expected behavior

I should get a redirect, either with or without the CSP headers.

### Actual behavior

```
RuntimeError at /author/top_authors
Missing context for the dynamic content security policy source: #<Proc:0x007f9c9eb655e8@.../config/initializers/content_security_policy.rb:18>
```
due to missing `request.controller_instance`

### System configuration
**Rails version**:
2.5.1
**Ruby version**:
2.3.3

**Comment by pixeltrix** [comment]
@viraptor is this the case for all of the CSP directives or just `report_uri` ?

**Comment by viraptor** [comment]
I haven't checked them all, but other parameters are affected as well. Making `default_src` and others `proc`s also breaks the redirect.
