### ISSUE TITLE
Include deep_pluck by default in Rails

### ISSUE THREAD

**Issue by mathewbaltes** [rails/rails#34207]
Hi Rails community,

I think we should include `deep_pluck` by default in Rails.  From the publishers website: 

> Allow you to pluck deeply into nested associations without loading a bunch of records.

I have been able to also use this in an application to reduce time from DB->JSON by 80% since `pluck` bypasses the activerecord object allocation and deep_pluck generates a hash representing the data without needing to handle the mapping ourselves.  This is VERY useful for creating fast Rest APIs.

Any chance we could get something like this in Rails?

Website: https://github.com/khiav223577/deep_pluck

**Comment by y-yagi** [comment]
Thank you so much for the issue but we don't take feature request on the issue tracker. We recommend you to try to implement the feature and send us a pull request or if you are in doubt if the feature will be accepts ask in [Rails Core mailing list](https://groups.google.com/forum/#!forum/rubyonrails-core) for feedback.
