### ISSUE TITLE
 Simplified Chinese active_record_callbacks  翻译错误

### ISSUE THREAD

**Issue by 308820773** [rails/rails#34216]
https://ruby-china.github.io/rails-guides/active_record_callbacks.html 
调用回调#increment!, this method not run callbacks

**Comment by sikachu** [comment]
Thank you for your report. However, we actually are not the one who maintain Chinese translation of Rails Guide. I think you will need to report (or contributing a patch) to https://github.com/ruby-china/rails-guides.

/cc @JuanitoFatas if you can help OP out. 😄
