### ISSUE TITLE
Create does not rollback despite failing belongs_to validation

### ISSUE THREAD

**Issue by phoebetse** [rails/rails#34226]
### Steps to reproduce

Comments **belong to** Posts, Posts **have many** Comments.
#### Scenario 1
With Comments that always fail validation:
```
class Comment < ApplicationRecord
  belongs_to :post
  
  validate :fails

  def fails
    errors.add(:text, "failed")
  end
end
```
and with valid Posts:
```
class Post < ApplicationRecord
  has_many :comments
end
```
We *cannot* create a Post with an invalid Comment, as expected:
```
irb(main):009:0> Post.create!(comments: [Comment.new])
   (0.1ms)  begin transaction
   (0.0ms)  rollback transaction
Traceback (most recent call last):
        1: from (irb):9
ActiveRecord::RecordInvalid (Validation failed: Comments is invalid)
```
#### Scenario 2
However, with Posts that always fail validation:
```
class Post < ApplicationRecord
  has_many :comments

  validate :fails

  def fails
    errors.add(:text, "failed")
  end
end
```
And with valid Comments:
```
class Comment < ApplicationRecord
  belongs_to :post
end
```
We *can* create a Comment with an invalid Post, unexpected:
```
irb(main):001:0> Comment.create!(post: Post.new)
   (0.0ms)  begin transaction
  Comment Create (0.9ms)  INSERT INTO "comments" ("created_at", "updated_at") VALUES (?, ?)  [["created_at", "2018-10-15 21:37:04.335596"], ["updated_at", "2018-10-15 21:37:04.335596"]]
   (0.7ms)  commit transaction
=> #<Comment id: 1, post_id: nil, created_at: "2018-10-15 21:37:04", updated_at: "2018-10-15 21:37:04">
```
### Expected behavior
In Scenario 2, expected a rollback when creating a Comment with an invalid Post, especially after this change: https://github.com/rails/rails/pull/18937  

### Actual behavior
In Scenario 2, Comment is created despite having an invalid Post. No rollback occurs.

### System configuration
**Rails version**: 5.2.1

**Ruby version**: 2.3.4 (also produced with  2.5.1)

**Comment by Manfred** [comment]
I believe this is expected behavior and you have to [explicitly require a valid associated object](https://guides.rubyonrails.org/active_record_validations.html#validates-associated).

**Comment by phoebetse** [comment]
oh wow, didn't realize that. thank you for the link!
