### ISSUE TITLE
Array#sum extension breaks on empty Arrays

### ISSUE THREAD

**Issue by loganb** [rails/rails#34230]
https://github.com/rails/rails/blob/e53acfde0ff233fb1d281119856595043bbf207e/activesupport/lib/active_support/core_ext/enumerable.rb#L160

```ruby
2.5.1 :001 > [].sum
 => 0
2.5.1 :002 > RUBY_VERSION
 => "2.5.1"
```
```ruby
2.5.1 :021 > [].sum
Traceback (most recent call last):
        1: from (irb):21
ArgumentError (wrong number of arguments (given 1, expected 0))
2.5.1 :022 > Rails.version
 => "5.1.4"
2.5.1 :023 >
```

The reason is that the default arg to the extended `sum` method is nil and not 0.

**Comment by jeremy** [comment]
Variant of #24796
