### ISSUE TITLE
`rescue_from` is not honoured by the params parsers

### ISSUE THREAD

**Issue by JoshCheek** [rails/rails#34244]
### Explanation

`rescue_from` is not honoured by the params parsers. This means that:

* My API is inconsistent, all my other error messages respond with a specific error schema, bad requests respond in a different one, because they bypass the `rescue_from` block.
* My custom mime types have custom parsers. These parsers can give really helpful feedback about why the request is bad, but because of this bug, I don't get to choose what goes in that response and thus can't make that information available to the caller.

### Expected behavior

In the below code snippet, the parse error should be rescued by the `rescue_from` block in the same way that the `ZeroDivisionError` is.

### Actual behavior

It is not rescued. With the current configuration, it raises out past Rails. Don't get caught up on that config, though, it's a rabbit hole (it behaves differently for different types of bad requests, but that's a separate issue).

### Steps to reproduce

```ruby
require "rails"
require 'action_controller/railtie'

# =====  Versions  =====
Rails::VERSION::STRING # => "5.2.1"
RUBY_VERSION           # => "2.5.1"

# =====  Configuration  =====
Rails.logger = Logger.new $stdout
ActiveSupport::LogSubscriber.colorize_logging = false

class MahApp < Rails::Application
  config.cache_classes                   = true
  config.eager_load                      = false
  config.consider_all_requests_local     = true
  config.serve_static_files              = false
  config.action_dispatch.show_exceptions = false # <-- don't get sidetracked by this
  initialize!
end

# =====  Routes  =====
Rails.application.routes.draw { post '/', to: 'site#whatevz' }

# =====  Controller  =====
class SiteController < ActionController::Base
  def whatevz
    1 / 0
  end

  # this will work
  rescue_from ZeroDivisionError do |exception|
    render json: { custom: true, errors: [exception.message] }
  end

  # this will not
  rescue_from ActionDispatch::Http::Parameters::ParseError do |exception|
    render json: { custom: true, errors: [exception.message] }
  end
end

# ===== Call the app =====
def self.post(body)
  code, headers, body = Rails.application.call(
    "REQUEST_METHOD" => "POST",
    "PATH_INFO" => "/",
    "HTTP_ACCEPT" => 'application/json',
    "CONTENT_TYPE" => 'application/json',
    "CONTENT_LENGTH" => body.bytesize.to_s,
    "rack.input" => StringIO.new(body),
  )
  [code, body.to_a.join]
end

post '{}'           # => [200, "{\"custom\":true,\"errors\":[\"divided by 0\"]}"]
post '{'  rescue $! # => #<ActionDispatch::Http::Parameters::ParseError: 765: unexpected token at '{'>

# ===== Logs =====

# >> I, [2018-10-17T11:22:15.394665 #71976]  INFO -- : Started POST "/" for  at 2018-10-17 11:22:15 -0500
# >> I, [2018-10-17T11:22:15.397135 #71976]  INFO -- : Processing by SiteController#whatevz as JSON
# >> I, [2018-10-17T11:22:15.397771 #71976]  INFO -- : Completed 200 OK in 0ms (Views: 0.3ms)
# >> 
# >> 
# >> I, [2018-10-17T11:22:15.398514 #71976]  INFO -- : Started POST "/" for  at 2018-10-17 11:22:15 -0500
# >> D, [2018-10-17T11:22:15.399077 #71976] DEBUG -- : Error occurred while parsing request parameters.
# >> Contents:
# >> 
# >> {
```

### System configuration
**Rails version**: 5.2.1

**Ruby version**: 2.5.1

**Comment by y-yagi** [comment]
Thanks for your report. Thanks for your report. But this seems to be that expected behavior. 
`rescue_from` rescues exceptions raised in controller actions.  
https://edgeapi.rubyonrails.org/classes/ActiveSupport/Rescuable/ClassMethods.html#method-i-rescue_from
Parsing of the parameters is done in an earlier request process. Therefore, I think that this is expected behavior.

**Comment by JoshCheek** [comment]
Consumers of an API don't care about implementation details like when a framework does one step vs another. The fact of the matter is that they submitted an invalid request according to the content type, and I have a format in which I communicate errors to them, and Rails ignores this entirely and emits some other error format. Rails is not the arbiter of my API. If Rails is ignoring my error format, then Rails is wrong. It doesn't matter that this is how Rails currently behaves, that doesn't make it expected or intentional. Rails is simply wrong here.

Furthermore, distilling my real-world use case down to a piece of code that I could drop into this report led to the discovery of two more bugs in Rails. So lets be transparent: this is a highly neglected aspect of the interface, and "this is what it seems to do" is not an argument that "this is intentional for these thoughtful reasons" or that "this is what it should do".

Rails is a framework, thus it either helps me out or it gets in my way. And right now, it's getting in my way. My clients told me they'd prefer Python, so I especially can't go back to them and say "well, I decided to ignore that and do Rails, which ignores my error handlers and presents an unpredictably inconsistent API". It's simply unacceptable. The API is god. Rails can either facilitate it or not. If it can't, then it's not a viable tool.

**Comment by JoshCheek** [comment]
Reopen this.

Rails is wrong here.

**Comment by jeremy** [comment]
Good points and generally agreed. It is a bit of a chicken/egg problem, but maybe there are some simple resolutions.

Where could we provide a Rack-app-level `rescue_from` that encompasses the app middleware stack? We do rescue exceptions in a middleware, but we don't have a clear place to specify `rescue_from`-like handling *before* a controller action is invoked.

**Comment by JoshCheek** [comment]
### An apology

Y'all, I was frustrated when I posted earlier. Partly b/c I've been fighting with this for a while now and partly b/c there isn't a button to reopen it, so it felt dismissed.

But those reasons don't really matter, I was too harsh in my response, I've edited it to state my argument without being so critical. I should  have cooled off before posting. Also removed the bit about 2 bugs b/c I think 1 of them was configurable and I forgot what the other one was. And wanted to apologize to @y-yagi, you fixed my other bug report and I really appreciate that. I know y'all are doing your best and I know this is a labor of love. Shoutout for that ❤️

### For those who come after me

For anyone who winds up here with the same issue, I'm currently solving it by turning off params parsing and parsing it myself in a before filter. You can see how I did it [here](https://gist.github.com/JoshCheek/93c1f909c8e7342dd2ddb4a57e2050b5#file-api_only_rails_example-rb-L237).

### How can Rails solve it?

> Where could we provide a Rack-app-level rescue_from that encompasses the app middleware stack? We do rescue exceptions in a middleware, but we don't have a clear place to specify rescue_from-like handling before a controller action is invoked.
>
> -- [@jeremy](
https://github.com/rails/rails/issues/34244#issuecomment-431688131)

I'll look into it. IDK when the controller becomes available, if it's available when the params are parsed, then it shouldn't be difficult. If not, then it will be a bit trickier, but should still be doable.

**Comment by JoshCheek** [comment]
Okay, looked into it. This is why it happens:

![screen shot 2018-10-21 at 3 01 39 pm](https://user-images.githubusercontent.com/77495/47272171-22eaaf00-d547-11e8-8249-1ffbc3b734bd.png)

---

After looking around a bit, I figured I'd give it a shot. Not sure where the best place to put the rescue handlers is. I stuck them on `AbstractController::Base#process` because it seemed like the entry point, so I figured it would catch the most errors there. It's a lot more ambitious than just swapping the order of the two methods above, but it works for my test, below:

```ruby
require "rails"
require 'action_controller/railtie'

# =====  Versions  =====
Rails::VERSION::STRING # => "5.2.1"
RUBY_VERSION           # => "2.5.1"


# ===== It works! =====
at_exit do
  # at_exit is so I can show this at the top of the file
  post '{' rescue $! # => #<ActionDispatch::Http::Parameters::ParseError: 765: unexpected token at '{'>
  insert_rescue_handlers!
  post '{'           # => [200, "{\"custom_error\":\"If you see this, it worked!\"}"]
end

# =====  Configuration  =====
Rails.logger = Logger.new $stdout
ActiveSupport::LogSubscriber.colorize_logging = false

class MahApp < Rails::Application
  config.cache_classes                   = true
  config.eager_load                      = false
  config.consider_all_requests_local     = true
  config.serve_static_files              = false
  config.action_dispatch.show_exceptions = false
  initialize!
end

# =====  Routes  =====
Rails.application.routes.draw { post '/', to: 'site#whatevz' }

# =====  Controller  =====
class SiteController < ActionController::Base
  def whatevz
  end
  # our custom rescue handler
  rescue_from ActionDispatch::Http::Parameters::ParseError do |exception|
    render json: { custom_error: "If you see this, it worked!" }
  end
end

# ===== Helper to call the app =====
def self.post(body)
  code, headers, body = Rails.application.call(
    "REQUEST_METHOD" => "POST",
    "PATH_INFO"      => "/",
    "HTTP_ACCEPT"    => 'application/json',
    "CONTENT_TYPE"   => 'application/json',
    "CONTENT_LENGTH" => body.bytesize.to_s,
    "rack.input"     => StringIO.new(body),
  )
  [code, body.to_a.join]
end

# ===== Code to insert the rescue handlers =====
def self.insert_rescue_handlers!
  # Not sure the best place to put it, here we'll go with AbstractController::Base#process
  file, line = AbstractController::Base.instance_method(:process).source_location
  file # => "/Users/josh/.gem/ruby/2.5.1/gems/actionpack-5.2.1/lib/abstract_controller/base.rb"
  process    = File.readlines(file).drop(line-1).take(11)

  # Get the code that currently delegates errors to the rescue handlers
  file, line = ActionController::Rescue.instance_method(:process_action).source_location
  file # => "/Users/josh/.gem/ruby/2.5.1/gems/actionpack-5.2.1/lib/action_controller/metal/rescue.rb"
  resc = File.readlines(file).drop(line+1).take(3).join

  # Insert the rescue handler into the method
  process[-1, 0] = "\n#{resc}".gsub(/^  /, '')

  # Monkey patch our modified AbstractController::Base#process
  AbstractController::Base.class_eval process.join
end


# ===== Logs =====

# >> I, [2018-10-21T15:35:38.929155 #58567]  INFO -- : Started POST "/" for  at 2018-10-21 15:35:38 -0500
# >> D, [2018-10-21T15:35:38.930526 #58567] DEBUG -- : Error occurred while parsing request parameters.
# >> Contents:
# >> 
# >> {
# >> I, [2018-10-21T15:35:38.931856 #58567]  INFO -- : Started POST "/" for  at 2018-10-21 15:35:38 -0500
# >> D, [2018-10-21T15:35:38.932285 #58567] DEBUG -- : Error occurred while parsing request parameters.
# >> Contents:
# >> 
# >> {
```

**Comment by JoshCheek** [comment]
Note that I found another solution which is much simpler than any of the others I've considered: It addresses the most pressing issue of bypassing `rescue_from`, but won't fix that these errors don't get logged. The basic idea is to override all the `process_action` methods with your own that rescues the `ParseError` and put your rescue logic there:

```ruby
class ApplicationController < ActionController::API
  def process_action(*args)
    super
  rescue ActionDispatch::Http::Parameters::ParseError => exception
    render status: 400, json: { errors: [ exception.message ] }
  end
end
```

**Comment by JoshCheek** [comment]
Looks like this is going to get fixed by https://github.com/rails/rails/pull/34341 ❤️

**Comment by estepnv** [comment]
```ruby
# lib/middleware/handle_bad_request.rb

module Middleware
  class HandleBadRequest
    def initialize(app)
      @app = app
    end

    def call(env)
      @app.call(env)
    rescue  ActionDispatch::Http::Parameters::ParseError => exception
      render status: 400, json: { errors: [ exception.message ] }
    end
    
  end
end

# config/initializers/application.rb

config.middleware.insert_after ActionDispatch::DebugExceptions, Middleware::HandleBadRequest
```
actually it would be cool to have it as a part of rails

**Comment by dave105010** [comment]
> Note that I found another solution which is much simpler than any of the others I've considered: It addresses the most pressing issue of bypassing `rescue_from`, but won't fix that these errors don't get logged. The basic idea is to override all the `process_action` methods with your own that rescues the `ParseError` and put your rescue logic there:
> 
> ```ruby
> class ApplicationController < ActionController::API
>   def process_action(*args)
>     super
>   rescue ActionDispatch::Http::Parameters::ParseError => exception
>     render status: 400, json: { errors: [ exception.message ] }
>   end
> end
> ```

I'm having this issue on Rails 6.1.7. We are spammed by bots making repeated GET requests with content-type: "application/json" with a faulty body something like "{ssd#$$fmessage". 

This is great but overriding a Rails method "ApplicationController" seems a bit hacky to me. 
I wish I could just rescue this with a middleware.

**Comment by jrhicks** [comment]
How bad of an idea is this

```
module ActiveSupport
  module JSON
    class <<self
      alias_method :alias_for_decode, :decode
    end

    def self.decode(raw_post)
      self.alias_for_decode(raw_post)
    rescue ::JSON::ParserError => ex
      escaped_tabs = raw_post.gsub("\t", "\\t")
      self.alias_for_decode(escaped_tabs)
    end
  end
end
```
