### ISSUE TITLE
ActiveRecord before query execute hook

### ISSUE THREAD

**Issue by SampsonCrowley** [rails/rails#34267]
Are there any available hooks for the ActiveRecord Query interface to use to hook in right before a query is executed? And if not, is there any method that is always called that could be prepended to achieve the same result?

I want to add a default order to queries, but ONLY if one hasn't been explicitly set.  default_scope is almost always a problematic solution since you have to explicitly remember to unscope it every time

I just want to be able to check if `.order_values` is present before any query is executed and if not, THEN add my default order

**Comment by SampsonCrowley** [comment]
my current solution is:
```
module ActiveRecord
  module QueryMethods
    DEFAULT_VALUES[:default_order] ||= FROZEN_EMPTY_ARRAY

    def default_order_values
      get_value(:default_order)
    end

    def default_order_values=(value)
      set_value(:default_order, value)
    end

    alias og_order! order!

    def default_order(*args)
      spawn.default_order!(*args)
    end

    def default_order!(*args)
      order!(*args)
      self.default_order_values = self.order_values.dup
      self
    end

    def order!(*args)
      if self.default_order_values.any?
        self.default_order_values = []
        reorder!(*args)
      else
        og_order!(*args)
      end
    end
  end
end

class ActiveRecord::Relation::Merger
  def merge_multi_values
    if other.reordering_value
      # override any order specified in the original relation
      relation.reorder!(*other.order_values)
    elsif other.default_order_values.any?
      relation.default_order!(*other.default_order_values)
    elsif other.order_values.any?
      # merge in order_values from relation
      relation.order!(*other.order_values)
    end

    extensions = other.extensions - relation.extensions
    relation.extending!(*extensions) if extensions.any?
  end
end

ActiveRecord::Querying.delegate :default_order, to: :all
```
But I don't like overriding built in methods

**Comment by rafaelfranca** [comment]
Please use the mailing list or StackOverflow for questions/help, where a wider community will be able to help you. We reserve the issues tracker for issues only.

**Comment by SampsonCrowley** [comment]
so unless you are familiar with other people in the community or know how to add it yourself, you can't propose new features? seems like a good way to stifle creativity. especially where rails is supposed to be all about convention, and conventionally repos have a `feature-request` label for tracking requested features.

just my two cents. Rails is still the tool I prefer most often, and I understand and appreciate all the the hard work that goes toward it; but making requesting features obscured to those with a decent idea but not the skill/inside knowledge to implement it feels like a loss for the community. especially since those who might have the same idea don't have a central resource to check if it's something already being picked up and worked on

If there's a reason that I'm missing on why a `feature-request` label can't be used I'd love more insight into the process
