### ISSUE TITLE
Cannot access an ActiveStorage::Variant's metadata

### ISSUE THREAD

**Issue by TheNeikos** [rails/rails#34263]
### Steps to reproduce

1. Create a model with an attachment
2. Attach an image 
3. Create a variant with for example `{resize: "720x1280>"}`
4. Try to get the actual variant's size:
`model.image.variant(thumb_variant).processed.image.metadata`

### Expected behavior
The metadata about the given variant is accessible.

### Actual behavior
The original file is being accessed and used

### System configuration
**Rails version**: 5.2.1

**Ruby version**: 2.5.1

**Comment by y-yagi** [comment]
Thank you so much for the issue but we don't take feature request on the issue tracker. We recommend you to try to implement the feature and send us a pull request or if you are in doubt if the feature will be accepts ask in [Rails Core mailing list](https://groups.google.com/forum/#!forum/rubyonrails-core) for feedback.

**Comment by TheNeikos** [comment]
@y-yagi So does this imply that https://api.rubyonrails.org/classes/ActiveStorage/Variant.html#method-i-image is meant to return the original image? To me the docstring says the opposite.

In that case, it would indeed be a feature request, and I shall take it to the mailing list.

**Comment by georgeclaghorn** [comment]
> So does this imply that https://api.rubyonrails.org/classes/ActiveStorage/Variant.html#method-i-image is meant to return the original image? To me the docstring says the opposite.

It’s meant to return the `Variant` instance on which it was called.

**Comment by AlecRust** [comment]
I don't see how this is a feature request instead of a bug.

If `processed` is supposed to represent the variant image, `processed.metadata` should contain the metadata for that variant?

Right now I see no easy way to retrieve the width and height attributes of a variant?

**Comment by SirNerdBear** [comment]
I have to agree with @AlecRust. I just ran into this problem and the behavior is highly unexpected.

**Comment by paulodeon** [comment]
I just tested this on 6.0.3.4 and it worked as expected: `b.banner.variant(resize_to_limit: [1080, 1080]).processed.blob.metadata[:width]`

**Comment by AlecRust** [comment]
It looks like Rails 6.1 doesn't resolve this. If anyone knows a workaround I'm all ears!

**Comment by AlecRust** [comment]
Workaround: https://stackoverflow.com/a/67228171/312681
