### ISSUE TITLE
AS::Notifications measuring with Time.now vs CPU clock

### ISSUE THREAD

**Issue by kirs** [rails/rails#34271]
At Shopify, we measure and log how much time a request has spent talking to all kinds of external resources: Redis, Memcache, ActiveRecord. Most of that is implemented by wrapping the request into `AS::Notification` subscription and reporting the delta between event's `start` and `end` (which is a `Time` object).

At the same time we have other middlewares that report total request time, which is using a delta between CPU clock (`Process.clock_gettime(Process::CLOCK_MONOTONIC)`).

We've started noticing some weird data in out logs:

```
total=0.457ms
memcache=14.587ms
db=6.930158ms	
```

How come that total request time is 30 times less than time spent _within_ the request?

The difference comes from `total` measured using CPU clock while `memcache` and `db` measured with `AS::Notification` using deltas of `Time.now`. That's what gives us such inaccurate results when comparing two things measured in different ways.

I noticed this has been recently fixed by @eileencodes in https://github.com/rails/rails/pull/33449.

Given that the PR was targeted for 6.0, can we consider this a bug and back port it to 5.2? :pray:

**Comment by kirs** [comment]
cc @rafaelfranca @Edouard-chin @gmcgibbon

**Comment by eileencodes** [comment]
I think we should backport this to 5.2 since we have identified that the current implementation is buggy. If we don't want to include any features we could consider just backporting a portion of the PR that swaps from Time to Process.clock_gettime.

**Comment by jeremy** [comment]
+ Backport! Agree it's a bugfix that monotonic clock fixes.

**Comment by rafaelfranca** [comment]
I backported in 7c4542146f by only applying the change in the clock.

**Comment by kirs** [comment]
❤️ ❤️ ❤️

**Comment by bdmac** [comment]
So now how do you now get the wall clock time for when an event *started* to send to a system like e.g. Influx? I suppose we could just instrument everything in our subscribers using `Time.now` for Influx but to be more accurate we were using `event.time`.
