### ISSUE TITLE
Try from inside a module not responding to private methods

### ISSUE THREAD

**Issue by bardec** [rails/rails#34288]
### Steps to reproduce

(Guidelines for creating a bug report are [available
here](http://edgeguides.rubyonrails.org/contributing_to_ruby_on_rails.html#creating-a-bug-report))

### Expected behavior
From the docs of `try`:

```
Invokes the method identified by the symbol method, passing it any arguments and/or the block specified, just like the regular Ruby Object#send does.

Unlike that method however, a NoMethodError exception will not be raised and nil will be returned instead, if the receiving object is a nil object or NilClass.

If try is called without a method to call, it will yield any given block with the object.
```

### Actual behavior
I'd expect an object to behave irregardless of `send` or `try`, and while `send` raises, `try` should just return `nil`.  If you call `try` on a private method, it returns `nil`, while if you call `send` it works fine. 

Here is a test script that makes it easy to try:

```ruby
# frozen_string_literal: true

begin
  require "bundler/inline"
rescue LoadError => e
  $stderr.puts "Bundler version 1.10 or later is required. Please update your Bundler"
  raise e
end

gemfile(true) do
  source "https://rubygems.org"

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  gem 'activesupport'
end

require "minitest/autorun"
require 'active_support/core_ext/object/try'


# Ensure backward compatibility with minitest 4.
Minitest::Test = MiniTest::Unit::TestCase unless defined?(Minitest::Test)

module Barable
  def bar
    try(:foo) || "failure"
  end
end
class Item
  include Barable

  private

  def foo
    "something"
  end
end

class BugTest < Minitest::Test
  def test_try_for_private
    item = Item.new

    # current behaviour
    assert_equal("failure", item.bar)

    # I would expect try to be able to access private methods from inside the
    # class
    assert_equal("something", item.bar)
  end
end
```

### System configuration
**Rails version**: `activesupport 5.2.1`

**Ruby version**: `ruby 2.3.7`

If the community decides this is unwanted behaviour, i'm happy to either clear up the documentation or (my preference) fix up the `try` method to do what i'd expect - especially from inside a module.

**Comment by rafaelfranca** [comment]
The documentation is wrong. `try` is equivalent to `public_send`. And the official documentation already tells you that. https://api.rubyonrails.org/classes/Object.html#method-i-try
