### ISSUE TITLE
Source code comment correction

### ISSUE THREAD

**Issue by hasandiwan** [rails/rails#34296]
At some point, Rails.application.database_configuration was moved to Rails.application.config.database_configuration. This patch updates the exception message to reflect the change.

**Comment by hasandiwan** [comment]
diff --git a/railties/lib/rails/application/configuration.rb b/railties/lib/rails/application/configuration.rb
index eae902a938..84d5381800 100644
--- a/railties/lib/rails/application/configuration.rb
+++ b/railties/lib/rails/application/configuration.rb
@@ -202,7 +202,7 @@ def database_configuration
               "Please note that YAML must be consistently indented using spaces. Tabs are not allowed. " \
               "Error: #{e.message}"
       rescue => e
-        raise e, "Cannot load `Rails.application.database_configuration`:\n#{e.message}", e.backtrace
+          raise e, "Cannot load `Rails.application.config.database_configuration`:\n#{e.message}", e.backtrace
       end
 
       def colorize_logging

**Comment by sham-sheer** [comment]
ddd
