### ISSUE TITLE
ActiveSupport::TimeZone advancing a week changes timezone.

### ISSUE THREAD

**Issue by frederikspang** [rails/rails#34301]
### Steps to reproduce
I'm seeing some inconsistencies, that I am unable to find information about, in both Rails 5.1.4 and 4.2.10 currently.

    Time.current
     => Tue, 23 Oct 2018 23:38:35 CEST +02:00
    Time.current + 1.week
     => Tue, 30 Oct 2018 23:38:37 CET +01:00

First of all, I'm unsure, why this happens. I have been in sourcecode, and not been able to find anything. One this were, if this would set time to 22:38:37, instead of 23, but the zone changes, meaning it does in fact *not* add a week, but `(1.week - 1.hour)`.

What I'm also seeing is, that this only happens, when crossing two weeks, i.e. sunday-to-monday

    Time.current + 5.days
    => Sun, 28 Oct 2018 00:00:00 CEST +02:00
    Time.current + 6.days
    => Mon, 29 Oct 2018 00:00:00 CET +01:00

However. This does not seem to happen with UTC, in a plain new Rails app.
2.5.1 :012 > Time.current
 => Tue, 23 Oct 2018 21:48:59 UTC +00:00
2.5.1 :013 > Time.current + 1.week
 => Tue, 30 Oct 2018 21:49:04 UTC +00:00

It DOES however, with ONLY config.time_zone = "Europe/Copenhagen" in the config. 

Currently on master branch `7bd7241`

### Expected behavior

Adding multiple days to a ActiveSupport::TimeWithZone should keep the zone

    Time.current + 5.days
    => Sun, 28 Oct 2018 00:00:00 CEST +02:00
    Time.current + 6.days
    => Mon, 29 Oct 2018 00:00:00 CEST +02:00

### Actual behavior
Adding multiple days to a ActiveSupport::TimeWithZone does not keep current timezone.

    Time.current + 5.days
    => Sun, 28 Oct 2018 00:00:00 CEST +02:00
    Time.current + 6.days
    => Mon, 29 Oct 2018 00:00:00 CET +01:00

### System configuration
**Rails version**: 4.2.10, 5.1.4 and master

**Ruby version**: 2.3.3 and 2.4.1 tested.

**Comment by GeniusStorm** [comment]
Its might be because of daylight savings ending in Europe on Sunday, October 28.

https://www.timeanddate.com/news/time/europe-dst-end-2018.html

**Comment by matthewd** [comment]
Yeah, this is expected behaviour.

The whole point of timezone-awareness is that "+1 week" should resolve to the same wall-clock time seven days later. If you want to add exactly 604800 seconds, you can do that directly.
