### ISSUE TITLE
ActiveRecord Errors sometimes include raw SQL in exception message

### ISSUE THREAD

**Issue by nerdrew** [rails/rails#34316]
### Steps to reproduce
There are numerous exceptions that include raw SQL in the exception message. Exception are messages often sent to external systems and should not include un-redacted SQL.

It looks like many exceptions raised by Mysql2. E.g.:
- `ActiveRecord::ValueTooLong: Mysql2::Error: Data too long for column 'class_name' at row 1: UN-REDACTED SQL STATEMENT`
- `Mysql2::Error: Deadlock found when trying to get lock; try restarting transaction: UN-REDACTED SQL STATEMENT`
- `ActiveRecord::StatementInvalid: Mysql2::Error: Incorrect string value: '...' for column 'name' at row 1: UN-REDACTED SQL STATEMENT`
- `ActiveRecord::StatementInvalid: Mysql2::Error: Lock wait timeout exceeded; try restarting transaction: UN-REDACTED SQL STATEMENT`

### Expected behavior
There shouldn't be any un-redacted SQL in exception messages

### Actual behavior
There is un-redacted SQL in exception messages

### System configuration
4.2.x - 5.2.x

**Ruby version**:
2.4.x, 2.5.x

Notes:
This is the method that seems to add the un-redacted SQL: https://github.com/rails/rails/blob/5b5367364f7b17ca89b50a8738e6b0c692bb730f/activerecord/lib/active_record/connection_adapters/abstract_adapter.rb#L583-L593

**Comment by gmcgibbon** [comment]
I'm assuming this is mostly an issue when you don't use prepared statements, right? Otherwise, PII would be obfuscated with substitution parameters.

**Comment by gmcgibbon** [comment]
The default for ActiveRecord is to [enable prepared statements](https://github.com/rails/rails/blob/c4720a25ed8738095bd8e441c1406a7a7471d904/activerecord/lib/active_record/connection_adapters/abstract_adapter.rb#L118), unless you specify otherwise in your configuration.

**Comment by nerdrew** [comment]
Hmmm. I don't see us un-setting it. Is that the default for postgresql only? We are using mysql.

**Comment by kamipo** [comment]
disable by default for mysql2 adapter.

https://github.com/rails/rails/blob/0bbe3409b52d6f7c29a29fbcb9e1acf9d3822406/activerecord/lib/active_record/connection_adapters/mysql2_adapter.rb#L39-L43

**Comment by nerdrew** [comment]
I'm going to toss my opinion out there: I don't think it should matter what kind of SQL generation an app is using, it shouldn't include un-redacted SQL in error messages. (Though, I'd consider prepared statements to be redacted SQL.)

**Comment by gmcgibbon** [comment]
I've updated my PR (linked above) to remove the SQL entirely from `ActiveRecord::StatementInvalid`s and make it a property of the error instead, regardless of prepared statements.
