### ISSUE TITLE
Polymorphic association does not support to compute class

### ISSUE THREAD

**Issue by jackkinsella** [rails/rails#34312]
I seem to be getting a regression after upgrading from Rails 5.0 to Rails 5.1 / 5.2

### Steps to reproduce

```ruby
begin
  require "bundler/inline"
rescue LoadError => e
  $stderr.puts "Bundler version 1.10 or later is required. Please update your Bundler"
  raise e
end

gemfile(true) do
  source "https://rubygems.org"

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  gem "rails", github: "rails/rails"
  gem "sqlite3"
end

require "active_record"
require "minitest/autorun"
require "logger"

# This connection will do for database-independent bug reports.
ActiveRecord::Base.establish_connection(adapter: "sqlite3", database: ":memory:")
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :orders, force: true do |t|
  end
  create_table :products, force: true do |t|
    t.datetime :deleted_at
  end

  create_table :line_items, force: true do |t|
    t.references :order
    t.integer :purchasable_id
    t.string :purchasable_type
  end
end

class Order < ActiveRecord::Base
  has_many :line_items
  has_many :products, through: :line_items, source: :purchasable, source_type: 'Product'
end

class Product < ActiveRecord::Base
  has_many :line_items, as: :purchasable
end

class LineItem < ActiveRecord::Base
  belongs_to :purchasable, -> { where(deleted_at: false) }, polymorphic: true
end

class BugTest < Minitest::Test
  def test_association_stuff
    Product.create!
    assert_equal Order.joins(:products).where(products: {id: nil}).count, 0
  end
end
```

### Expected behavior

The scope should work as it did back in Rails 4.x and Rails 5.0.x.

### Actual behavior

In Rails 5.2.1 I got the following:

```
ArgumentError: Polymorphic association does not support to compute class.
from /.../gems/activerecord-5.2.1/lib/active_record/reflection.rb:420:in `compute_class'
```

However in Rails 5.1.x I got something like this error (taking it from my main codebase, so may not occur exactly in the test case):

```
Exception: NameError: uninitialized constant LineItem::Purchasable
```

### System configuration
**Rails version**:
5.2.1

**Ruby version**:
2.5.0

**Comment by yazumoto** [comment]
This may be intended. 
https://github.com/rails/rails/commit/fb86ecd604a362355827bbf05776b847b0ded9a5

**Comment by Alagaesia93** [comment]
I have the same error. Any idea on how to solve it?

**Comment by mguinada** [comment]
Same here. In my case is coming from a third party gem. Is there any corrective action?

**Comment by marbleappdev** [comment]
same here.

`class Note < ActiveRecord::Base
  belongs_to :subject, polymorphic: true

  has_one :self_ref, :class_name => self, :foreign_key => :id
  has_one :volunteer, :through => :self_ref, :source => :subject, :source_type => 'Volunteer'
end`

`Note.joins(:volunteer)` works on rails 5.0.7, but now getting the same error on 5.2.0

**Comment by jackkinsella** [comment]
@yazumoto Although this error message was _introduced_ in the commit you mentioned, the functionality broke before this. i.e.
* In Rails 5.1 I got the error:
`Exception: NameError: uninitialized constant LineItem::Purchasable`
* In Rails 5.0 it worked with problem.

You can reproduce all the above by modifying the rails gem version in my 'steps to reproduce' section in the parent post.

**Comment by phoet** [comment]
any workarounds or progress on this?

**Comment by jeznag** [comment]
I get this error when the parent record is updated to remove children. See error report https://stackoverflow.com/questions/54778993/polymorphic-association-does-not-support-to-compute-class-when-trying-to-save

It worked fine in rails 4.3

**Comment by alec-horwitz** [comment]
I'm getting this error on rails 5.2

**Comment by etiennebarrie** [comment]
I traced it back to https://github.com/rails/rails/pull/27851.
Before that PR the test case works, after it fails because it tries to filter out deleted line items:
```
ActiveRecord::StatementInvalid: SQLite3::SQLException: no such column: line_items.deleted_at:
SELECT COUNT(*) FROM "orders"
INNER JOIN "line_items" ON "line_items"."order_id" = "orders"."id"
 AND "line_items"."deleted_at" = ?
 AND "line_items"."purchasable_type" = ?
INNER JOIN "products" ON "products"."id" = "line_items"."purchasable_id"
 AND "products"."deleted_at" = ?
WHERE "products"."id" IS NULL
```
(line breaks added for clarity)

More specifically it's that commit which was supposed to fix the very use case of lambda scopes, but applies the scope twice, once for `products` and once `line_items`: https://github.com/rails/rails/pull/27851/commits/e8be3a9016b6c27ead6d5608c3f988c5f72b385b.

**Comment by alessandromacagno** [comment]
**Update** if you reach this page while googling.

Probably you have a polymorphic validation
`validates :polymophic, uniqueness: {scope: :other_model}`

Change it to
`validates :polymorphic_id, uniqueness: { scope: %i[polymorphic_type other_model]}`

**Comment by fabriciofreitag** [comment]
FYI: Had the same issue using the `pg_search` gem and configuring polymorphic associations

**Comment by pacMakaveli** [comment]
Google brought me here after upgrading to Rails 7.
In my case, I was using inverse_of on a polymorphic:

```
  belongs_to :collection, class_name: '::Collection', optional: true, inverse_of: :network, touch: true, dependent: :destroy
```

Removing the `inverse_of: :network` fixed the issue for me.

```
2.7.2 :007 > Collection.last.network
  Collection Load (1.6ms)  SELECT `collections`.* FROM `collections` ORDER BY `collections`.`id` DESC LIMIT 1
  PlayStation::Collection Load (7.4ms)  SELECT `play_station_collections`.* FROM `play_station_collections` WHERE `play_station_collections`.`id` = 493485 LIMIT 1
 =>
#<PlayStation::Collection:0x00007fcf30b4d118
```

```
2.7.2 :008 > XBOX::Collection.find(112564).collection
  XBOX::Collection Load (0.6ms)  SELECT `xbox_collections`.* FROM `xbox_collections` WHERE `xbox_collections`.`id` = 112564 LIMIT 1
  XBOX::Title Load (8.9ms)  SELECT `xbox_titles`.* FROM `xbox_titles` WHERE `xbox_titles`.`title_id` = 2043073184
  XBOX::Game Load (0.7ms)  SELECT `xbox_games`.* FROM `xbox_games` WHERE `xbox_games`.`big_id` = '9PP5G1F0C2B6'
  XBOX::Resourceable Load (0.5ms)  SELECT `xbox_resourceables`.* FROM `xbox_resourceables` WHERE `xbox_resourceables`.`resource_type` = 'XBOX::Genre' AND `xbox_resourceables`.`game_id` = 21034
  Collection Load (0.3ms)  SELECT `collections`.* FROM `collections` WHERE `collections`.`id` = 37083 LIMIT 1
Traceback (most recent call last):
/Users/vlad/.rvm/gems/ruby-2.7.2/gems/activerecord-7.0.0.rc1/lib/active_record/reflection.rb:417:in `compute_class': Polymorphic associations do not support computing the class. (ArgumentError)
```
