### ISSUE TITLE
Feature request:  tsearch_data rules migrations

### ISSUE THREAD

**Issue by irmpow** [rails/rails#34323]
### Steps to reproduce

Have symbols in DB, for example, letters from localized language, that not represented in /usr/share/postgresql/10/tsearch_data/*.rules in names of models. Than use 'unaccent' module of DB to search through that models like that

```ruby
where("unaccent('locallanguage_char', title) ILIKE ?", find_string)
```

### Expected behavior
There must be reminder in guide https://guides.rubyonrails.org/active_record_migrations.html, or functionality to create tsearch_data rules in migrations.

### Actual behavior
unaccent module does not work without manually adding rules

**Comment by y-yagi** [comment]
Thank you so much for the issue but we don't take feature request on the issue tracker. We recommend you to try to implement the feature and send us a pull request or if you are in doubt if the feature will be accepts ask in [Rails Core mailing list](https://groups.google.com/forum/#!forum/rubyonrails-core) for feedback.
