### ISSUE TITLE
What is the ActiveSupport::Cache::FileStore key limit?

### ISSUE THREAD

**Issue by anilmagapu** [rails/rails#34320]
I am using Model caching in my application to store caching data.At the time of generation caching file, i am giving different formats to store data.Because of that it is taking 140-180 length file name
Ex: 1000011_2000014_2000004_2000013_1000006_1000010_2000005_2000001_1000012_2000013_2000012_2000015_2000006_1000006_1000006_1000000_1000008_brand_list 

May i know what is the maximum length for ActiveSupport::Cache::FileStore file  name ??
Please let me know.

Many thanks,
Anil

**Comment by saiqulhaq** [comment]
I think it's depend on the operating system

**Comment by anilmagapu** [comment]
Thank you for very quick reply @saiqulhaq  and @frodsan .
Yes i have found info in in file_store.rb

**Comment by frodsan** [comment]
@anilmagapu No problem, you can close the issue if you found the info you were looking for. Remember that the issues board is for issues only: https://github.com/rails/rails/issues/34190#issuecomment-429148542
