### ISSUE TITLE
Order of JOIN statements not respected when building ActiveRecord query with `merge` and `joins`

### ISSUE THREAD

**Issue by abinoda** [rails/rails#34328]
I'm building a query with ActiveRecord where I do a `LEFT OUTER JOIN` and then use `merge` to do an `INNER JOIN`. When I pass in `GithubPr.joins(:github_user)` as the argument to `merge`, the order of the JOIN statements is not as intended, resulting in a broken SQL query.

### Steps to reproduce

Here's my query with a `.to_sql` to print the generated SQL.

```ruby
GithubPr
        .select('p', 'count(*)')
        .from("generate_series('2018-08-03', '2018-10-26', '1 week') as dates(p)")
        .joins("LEFT OUTER JOIN github_prs on github_prs.created <= p")
        .merge(GithubPr.joins(:github_user))
        .group('p')
        .order('p ASC')
        .to_sql
```

### Expected behavior

The query I would expect would be consistent with the order of the joins I built. I expect the LEFT OUTER JOIN to be first, followed by the INNER JOIN.

```sql
SELECT p, count(*)
FROM generate_series('2018-08-03', '2018-10-26', '1 week') as dates(p)
LEFT OUTER JOIN github_prs on github_prs.created <= p
INNER JOIN "github_users" ON "github_users"."id" = "github_prs"."github_user_id"
GROUP BY p
ORDER BY p ASC
```

### Actual behavior

The query that is generated does not respect the order of my joins. Instead, the INNER JOIN comes before the LEFT OUTER JOIN, which does not work/

```sql
SELECT p, count(*)
FROM generate_series('2018-08-03', '2018-10-26', '1 week') as dates(p)
INNER JOIN "github_users" ON "github_users"."id" = "github_prs"."github_user_id"
LEFT OUTER JOIN github_prs on github_prs.created <= p
GROUP BY p
ORDER BY p ASC
```
### Weird workaround

I've found a weird workaround where if I pass in a custom join like this:

```ruby
merge(joins('INNER JOIN github_users on github_users.id = github_prs.github_user_id'))
```

instead of:

```ruby
merge(GithubPr.joins(:github_user))
```

... then the order is correct and the SQL is valid.

### System configuration

**Rails version**: 5.2.1
**Ruby version**: 2.5.0

**Comment by y-yagi** [comment]
Can you create a reproduce script with this [template](https://github.com/rails/rails/blob/master/guides/bug_report_templates/active_record_gem.rb)?

**Comment by abinoda** [comment]
@y-yagi How's this? It seemed counter-productive to use test assertions on the raw SQL output so I just print out the two examples I mentioned in my original post.

```ruby
# frozen_string_literal: true

begin
  require "bundler/inline"
rescue LoadError => e
  $stderr.puts "Bundler version 1.10 or later is required. Please update your Bundler"
  raise e
end

gemfile(true) do
  source "https://rubygems.org"

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  # Activate the gem you are reporting the issue against.
  gem "activerecord", "5.2.0"
  gem "sqlite3"
end

require "active_record"
require "minitest/autorun"
require "logger"

# This connection will do for database-independent bug reports.
ActiveRecord::Base.establish_connection(adapter: "sqlite3", database: ":memory:")
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :github_prs, force: true do |t|
    t.integer  :github_user_id
    t.datetime :created
  end

  create_table :github_users, force: true do |t|
  end
end

class GithubPr < ActiveRecord::Base
  belongs_to :github_user
end

class GithubUser < ActiveRecord::Base
end

puts "\n\n"

# Using `merge(GithubPr.joins(:github_user))` results in the query's JOIN statements being out of order
puts "Invalid SQL:\n"
puts GithubPr
        .select('p', 'count(*)')
        .from("generate_series('2018-08-03', '2018-10-26', '1 week') as dates(p)")
        .joins("LEFT OUTER JOIN github_prs on github_prs.created <= p")
        .merge(GithubPr.joins(:github_user))
        .group('p')
        .order('p ASC')
        .to_sql

puts "\n\n"
# If I pass in a custom join statement instead, then the query's JOIN statements are in the correct order
puts "Correct SQL:\n"
puts GithubPr
        .select('p', 'count(*)')
        .from("generate_series('2018-08-03', '2018-10-26', '1 week') as dates(p)")
        .joins("LEFT OUTER JOIN github_prs on github_prs.created <= p")
        .merge(GithubPr.joins('INNER JOIN github_users on github_users.id = github_prs.github_user_id'))
        .group('p')
        .order('p ASC')
        .to_sql
```

**Comment by st0012** [comment]
@abinoda what's the `p` in the query stands for? Have you tried using `left_outer_joins` for the left outer join?

**Comment by abinoda** [comment]
@st0012 

> what's the p in the query stands for?

The `p` is selecting the date period from `generate_series('2018-08-03', '2018-10-26', '1 week') as dates(p)`.

> Have you tried using left_outer_joins for the left outer join?

To my knowledge, you can't pass in a string to `left_outer_joins`, but there's no other way to join using the condition`github_prs.created <= p`. `left_outer_joins("github_prs on github_prs.created <= p")` results in an `ArgumentError`.

**Comment by abuisman** [comment]
I can confirm the order of joins getting changed:

```ruby
User.left_joins(:email).joins("INNER JOIN something_cool ON some_prop = haha").to_sql
=> "SELECT \"users\".* FROM \"users\" INNER JOIN something_cool ON some_prop = haha LEFT OUTER JOIN \"emails\" ON \"emails\".\"user_id\" = \"users\".\"id\""
```

This becomes a problem when you want to use something from the 'emails' table in the ON of the second join, which becomes the first join due to re-ordering.

**Comment by bananatron** [comment]
![image](https://github.com/rails/rails/assets/5759818/65aeda89-8ba6-4864-8fb5-8a2f869774af)
