### ISSUE TITLE
It's not possible to chain #left_joins just like #joins method

### ISSUE THREAD

**Issue by sanchez2210** [rails/rails#34332]
### Steps to reproduce
I noticed that it is possible to call a chain of `joins` method on a relation, and each call would append to the initial JOIN clause.

It's not possible to do so with `left_joins`, leading to very long method calls.

### Expected behavior

Being able to chain `left_joins` calls, just like `#joins`.
```
Registration
  .left_joins(:rewards)
  .left_joins(' AND rewards.id = 0')
=> # SELECT * FROM registrations
=> # LEFT JOIN rewards
=> # ON rewards.registration_id = registrations.id
=> # AND rewards.id = 0'
```

### Actual behavior

It raises an error.
```
Registration.left_joins(:rewards).left_joins(' AND rewards.id = 0')
=> # ArgumentError: only Hash, Symbol and Array are allowed.
```

One needs to write the complete initial left_joins clause.
```
Registration.joins('LEFT JOIN rewards ON registrations.id = rewards.registration_id AND rewards.id = 0')
````

`#joins` does not have this issue:

```
Registration.joins(:rewards).joins(' AND rewards.id = 0')
=> # SELECT * FROM registrations
=> # INNER JOIN rewards
=> # ON rewards.registration_id = registrations.id
=> # AND rewards.id = 0'

```

### System configuration
**Rails version**: 5.2.1

**Ruby version**: 2.5.1

I could commit some time to contribute a PR for this if it's not a huge change (hopefully?).

**Comment by robin850** [comment]
It looks like support for String has [not been implemented originally](https://github.com/rails/rails/pull/12071/files#diff-bf6dd6226db3aab589916f09236881c7R964) for this method and never [since then](https://github.com/rails/rails/blob/7d7372c14df4ad5b546f012a82538753c5991905/activerecord/lib/active_record/relation/query_methods.rb#L981).

Also, given #27947 has landed since Rails 5.2, maybe I'm missing something but I don't see why we are still supporting passing Strings with regular `joins`, this is potentially dangerous as well AFAICS.

**Comment by senny** [comment]
The [docs of `join`](https://api.rubyonrails.org/classes/ActiveRecord/QueryMethods.html#method-i-joins) do not specifically mention this use of passing a string to `join`. I'm not sure this behavior was even intended in the first place.

@sanchez2210 did you find references in Rails documentation about this particular use of `join` or did you notice this behavior just by trying?

**Comment by khiav223577** [comment]
I also have similar issues.

### joins
```rb
User.joins(:user_missions, 'AND user_missions.mission_id = 1').count
```
It will generate this:
```sql
SELECT COUNT(*) FROM "users" 
INNER JOIN "user_missions" ON "user_missions"."user_id" = "users"."id" AND user_missions.mission_id = 1
```

### left_joins
```rb
User.left_joins(:user_missions, 'AND user_missions.mission_id = 1').count
```
expect it will generate this:
```sql
SELECT COUNT(*) FROM "users" 
LEFT OUTER JOIN "user_missions" ON "user_missions"."user_id" = "users"."id" AND user_missions.mission_id = 1
```
but it raise `ArgumentError (only Hash, Symbol and Array are allowed)` instead.
