### ISSUE TITLE
ActiveJob and retries API

### ISSUE THREAD

**Issue by kirs** [rails/rails#34337]
`ActiveJob::Exceptions` promotes the following API:

```ruby
class RemoteServiceJob < ActiveJob::Base
  retry_on ActiveRecord::Deadlocked, attempts: 3
  retry_on Net::OpenTimeout, attempts: 10
```

It may seem that the job would be retried 10 times on `Net::OpenTimeout` and 3 times on `ActiveRecord::Deadlocked` - however, since the exceptions counter (`#executions`) is incremented globally but not per exception class, it's currently possible that:

1. First 3 times the job raises with `Net::OpenTimeout`, each time it's retried and `executions` gets incremented to `3`
2. On 4th execution the job raises with `ActiveRecord::Deadlocked` but it won't be retried because `executions` (3) is greater than `attempts` for `ActiveRecord::Deadlocked` class.

IMO this side of the API can be misleading. It also doesn't provide a shortcut to declare "retry any exception N times" other than `retry_on StandardError, attempts: 10` - which is what we'd want many jobs to do to [enforce idempotency](https://github.com/mperham/sidekiq/wiki/Best-Practices#2-make-your-job-idempotent-and-transactional).

At Shopify we have our own Retry module with the following API:

```ruby
class ShopifyJob < AJ::Base
  # we don't want the API to encourage zero retries for idempotency reasons so we offer "minimum" number of retries
  retries :minimum
end

class ShopifyJob < AJ::Base
  # in most of cases developer doesn't have to come up with a custom number of retries, so we support "default" number of retries per platform. In this example they'll be applied exponentially.
  retries :default, backoff: :exponential
end

class ShopifyJob < AJ::Base
  # 10 retries, each with 1 minute backoff
  retries 10, backoff: [1.minute] * 50
end

class ShopifyJob < AJ::Base
  retries 10, backoff: :exponential
  def perform
    # ...
  rescue RecordAlreadyExists
    # don't retry this exception by "swallowing it"
  end
end

class ShopifyJob < AJ::Base
  retries 10, backoff: :exponential
  def perform
    # ...
  rescue StandardError => e
    raise if e == Billing::BackendBusyRetryLaterError
    # retry only one kind of exception, swallow the rest
  end
end
```

Some parts of this API are more flexible than `ActiveJob::Exceptions` but some are less expressive (especially retrying only one exceptions class).

I'd like to discuss options how we could merge the best parts of both APIs and address the misleading parts of `ActiveJob::Exceptions`, and at the same time push all Rails developers to opt-in for idempotency by default.

**Comment by rafaelfranca** [comment]
It is not clear to me what is the expected outcome of this issue. In the beginning you talk about a  possible problem with the way the execution counter is used to determine if the exception would cause the job to be retried or not.

After that you talk about the API not providing any way to declare "retry any exception N times".

Later you talk about a new API and ask how we can merge the current API and this new API.

So am I correct to assume that you want a new API that:

1. Keep different counters based on the exception that was rescued.
2. Have a way to define "retry any exception N times".
3. Have an expressive way to declared retrying only one exception class.
4. Is idempotent by default.

cc @dhh since I think you designed the current API
cc @jeremy since you were reviewing changes to Active Job API and locking so this may related.

**Comment by dhh** [comment]
1. That's how I intended it too. It's a bug that the counters are shared. Should be per declaration.
1. I think "retry_on StandardError" or "retry_on Exception" should provide that already? But I think it's kinda code to deal with all exceptions in this way. You should know why you'd want to retry, and the code should document that knowledge.
1. I don't think this is a good idea. I prefer the syntactic vinegar we currently have in place where it's possible to just do any-exception retries, but it's discouraged.
1. Isn't this already the case?

**Comment by albertoalmagro** [comment]
Shall I further investigate the bug related to the shared counter and submit a PR to fix it?

**Comment by rafaelfranca** [comment]
@albertoalmagro if you want, go ahead.

**Comment by albertoalmagro** [comment]
Yep, I could reproduce it with the following reproduction steps:

```ruby
# frozen_string_literal: true

require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  # Activate the gem you are reporting the issue against.
  gem "activejob", "5.2.0"
end

require "minitest/autorun"
require "active_job"

class CustomException < StandardError; end
class OtherCustomException < StandardError; end

class BuggyJob < ActiveJob::Base
  retry_on CustomException
  retry_on OtherCustomException

  def perform(exceptions)
    puts "Exceptions: #{exceptions}"
    puts "Executions: #{executions}"

    raise exceptions.shift.constantize.new unless exceptions.empty?
  end
end

class BuggyJobTest < ActiveJob::TestCase
  def test_stuff
    exceptions = %w(CustomException CustomException OtherCustomException OtherCustomException)

    assert_raises OtherCustomException do
      perform_enqueued_jobs do
        BuggyJob.perform_later(exceptions)
      end
    end
  end
end
```
When it reaches `OtherCustomException` the value of `executions` is already `3` and it raises. 

Tomorrow I will try to reproduce it in a Rails' test and write a patch (it is already late here in Spain). Cheers!
