### ISSUE TITLE
ignored_columns has surprising behavior for STI

### ISSUE THREAD

**Issue by afn** [rails/rails#34344]
### Steps to reproduce

Suppose you have a `Vehicle` model with subclasses `Car` and `Bicycle`, so there are some columns on the table (e.g. `engine_size`) which are relevant to one subclass but not the other. It would be nice to hide the `engine_size` subclass from `Bicycle`. We can attempt to address this with `ignored_columns`:

```ruby
class Vehicle < ApplicationRecord
  self.ignored_columns = %w(engine_size)
end

class Bicycle < Vehicle
end

class Car < Vehicle
  self.ignored_columns = []
end
```

### Expected behavior

I would expect to be able to call `Vehicle.find(id)` and, depending on the type of vehicle, either have an `engine_size` method available or have the method be undefined.

### Actual behavior

```ruby
Car.create! name: 'Batmobile', engine_size: '3.4L'
Bicycle.create! name: 'bike'
Car.find(1).engine_size
# => "3.4L" (correct)
Bicycle.find(2).engine_size
# => NoMethodError (correct)
Vehicle.find(1).engine_size
# => ActiveModel::MissingAttributeError (incorrect)
```

### Discussion

`ignored_columns` is used in two different places: it's used in [`build_select`](https://github.com/rails/rails/blob/aed7e00039057722f93d33a45d00718f176be05a/activerecord/lib/active_record/relation/query_methods.rb#L1043-L1051) to prevent the ignored columns from being included in the SELECTed columns, and also in the [`load_schema!`](https://github.com/rails/rails/blob/f45267bc423017109e442e5c35a5765dc482b12b/activerecord/lib/active_record/model_schema.rb#L470-L479) method, which prevents the ignored columns from being predefined on new instances.

The problem is that if we're loading the model from the database using the superclass (Vehicle), we don't yet know whether or not the `engine_size` column should be loaded. Therefore, if the model that's being loaded has subclasses which have varying `ignored_columns`, we need to prevent the attributes from being defined *after* the query has returned a result set, when we know the actual type.

I'll submit a pull request shortly. My proposal is to move the handling of ignored columns to a later stage, when the actual type is known:

1. In `load_schema!`, exclude columns that are ignored in either the current class or one of its descendants.
2. In `build_select`, only omit those columns that are ignored by all descendant classes.
3. In the attributes builder, which is called after the records have been loaded and the type is known, exclude columns that are in the current class's `ignored_columns`.

### System configuration
**Rails version**: 5.2.1

**Ruby version**: 2.5.3

**Comment by rafaelfranca** [comment]
See https://github.com/rails/rails/pull/34345#issuecomment-566813819
