### ISSUE TITLE
Avoid hireris because it's unmaintained 

### ISSUE THREAD

**Issue by fidalgo** [rails/rails#34342]
In the [caching documentation,](https://guides.rubyonrails.org/caching_with_rails.html#activesupport-cache-rediscachestore) it's suggested to use hiredis for faster connections, although the code is not maintained any more: https://github.com/redis/hiredis-rb/issues/49 and the last release was from 29 Dec 2015.

If you guys think it would be good to get rid of it, I will later open a PR to remove it.

**Comment by rafaelfranca** [comment]
Do you see anything broken on hiredis now that explain the removal? I only see 1 open PR and 3 open issues in that repository so I'd guess the project is very stable. Also I'm a maintainer of redis and hiredis for a few months already so I'd say that issue is not valid anymore. I just closed.

**Comment by fidalgo** [comment]
@rafaelfranca No, I've just stumbled across the recommendation and checked the hiredis repo and issues... and found that, so if the redis-rb is also the maintainers of redis-rb, this can be closed for good.
