### ISSUE TITLE
ActiveRecord: Inspecting relation in `after_save` hook can cause double save attempt.

### ISSUE THREAD

**Issue by aselder** [rails/rails#34346]
### Steps to reproduce

```
#!/usr/bin/env ruby
# frozen_string_literal: true

begin
  require "bundler/inline"
rescue LoadError => e
  $stderr.puts "Bundler version 1.10 or later is required. Please update your Bundler"
  raise e
end

gemfile(true) do
  source "https://rubygems.org"
  gem "activerecord", git: "https://github.com/rails/rails", branch: "5-2-stable"
  gem "sqlite3"
end

require "active_record"
require "minitest/autorun"

ActiveRecord::Base.establish_connection(adapter: "sqlite3", database: ":memory:")

ActiveRecord::Schema.define do
  create_table :users, force: true do |t|
    t.string :name
  end

  create_table :accounts, force: true do |t|
    t.string :name
    t.integer :owner_id
  end

  create_table :account_memberships, force: true do |t|
    t.integer :account_id
    t.integer :user_id
  end
end

class Account < ActiveRecord::Base
  has_many :account_memberships
  has_many :users, through: :account_memberships
  belongs_to :owner, class_name: "User"
end

class User < ActiveRecord::Base
  has_many :account_memberships
  has_many :accounts, through: :account_memberships
  has_many :accounts_owned, foreign_key: :owner_id, class_name: "Account", inverse_of: :owner
end

class AccountMembership < ActiveRecord::Base
  belongs_to :account, inverse_of: :account_memberships, optional: true
  belongs_to :user, inverse_of: :account_memberships, optional: true

  validates :user_id, uniqueness: { scope: :account_id }
  after_save :look_at_account

  def look_at_account
    #Anything that iterates over user.accounts (.to_a, .reload, etc) will cause the same behavior
    puts user.accounts
  end
end

class  TestDoubleSave < Minitest::Test
  def test_double_save
    user = User.new
    account = user.accounts_owned.build(name: "foo")
    user.account_memberships.build(account: account)  
    user.save! 
  end
end
```

### Expected behavior
The user should be saved without an error.

### Actual behavior
TestDoubleSave#test_double_save:
ActiveRecord::RecordInvalid: Validation failed: User has already been taken

### System configuration
**Rails version**: master, 5-2-stable, 5.2.1

**Ruby version**: 2.4.5

Looking at the code in `autosave_association.rb`, it looks like there's a bug in `#save_collection_association`. When it's iterating the `accounts` relations on user, when you get to line 401:
`if autosave != false && (@new_record_before_save || record.new_record?)`

`record.new_record?` returns `false` for the account record (as it already got saved as part of the account_membership save), but `@new_record_before_save` is true since the parent object being saved (the user) is a new record.

This causes `association.insert_record(record, false)` to be called, which leads to the uniqueness validation error.

Commenting out the `puts` allows the test to pass.

**Comment by aselder** [comment]
This test above passes under ActiveRecord 5.1.1

**Comment by aselder** [comment]
This is a still an issue at least on `5-2-stable`

**Comment by theorygeek** [comment]
We're experiencing this issue as well. In fact, it can create some very perplexing problems for us. In our case, we're getting behavior where ActiveRecord will attempt to _load_ the association (eg, `user.accounts`) and will run a query like `WHERE other_table.id IS NULL`.

It ends up finding the first row that has a null value, thinking that it satisfies the association, and ends up associating the two records together!
