### ISSUE TITLE
Empy string key in enum causing column update when checking instance in conditional

### ISSUE THREAD

**Issue by EByrdS** [rails/rails#34365]
An empty string in the key of an enum hash fails on the correct usage of enum as it will try to create `def !` and `def ?` methods, however, this setup causes silent column updates when checking truthiness of an instance and no headsup is sent to the developer. 

### Steps to reproduce
```ruby
# frozen_string_literal: true

require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  # Activate the gem you are reporting the issue against.
  gem "activerecord", "5.0.0.1"
  gem "sqlite3"
end

require "active_record"
require "minitest/autorun"
require "logger"

# This connection will do for database-independent bug reports.
ActiveRecord::Base.establish_connection(adapter: "sqlite3", database: ":memory:")
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :empty_string_enums, force: true do |t|
    t.integer :state
  end

  create_table :nil_key_enums, force: true do |t|
    t.integer :state
  end
end

class EmptyStringEnum < ActiveRecord::Base
  enum state: { '': 0, 'good': 1 }
end

class BugTest < Minitest::Test
  def test_enum_raises_error
    assert_raises(Exception) { EmptyStringEnum.new }
  end

  def test_truthiness_should_not_update_column
    model = EmptyStringEnum.create state: 'good'
    !model
    assert_equal model.state, 'good'
  end

  def test_model_should_eval_to_true
    model = EmptyStringEnum.create state: 'good'
    assert !!model
  end
end
```

### Expected behavior
1. An error should be raised when trying to create an `enum` with an empty string as one of its keys. 
2. Evaluating truthiness of a model with empty string in one enum should not have side effects.
3. An instance of a model with an empty string in one of its keys should evaluate to true.

### Actual behavior
1. No error is raised.
2. The value of the stated enum column is updated to `nil`.
3. The instance evaluates to false.

### System configuration
**Rails version**: 5.2.1

**Ruby version**: 2.3.1

When solving this behavior, the method names might as well be checked to avoid other collisions like `.nil?`. I would be happy to contribute and solve this. 

Motivation for this behavior is asked and stated in [this StackOverflow question](https://stackoverflow.com/questions/53102936/empy-string-key-in-enum-causing-column-update-when-checking-instance-in-conditio)

**Comment by AroSwift** [comment]
I have also experienced this issue on a production service running Ruby 2.4 and Rails 5.0.6. Furthermore, I can also reproduce the issue on `Ruby 2.5.0` and `Rails 5.2.1`. 

Let me highlight why this should matter to all Rails developers. The method `blank?` and `present?` use the bang (`!`) method. Thus, if one has a model with an empty enumerator key defined, calling one of these methods will cause a save to occur. This utterly baffles the developer who was not provided a warning and has no idea why this happens on some models.

How do we as a community want to resolve this issue? At the very least, we ought to provide documentation explaining the issue. My recommended fix is preventing `def !` and `def ?` from being defined.

I have already created a fix for this by performing a check on the Enum class to prevent `!` and `?` from being defined when a blank enumerator is set, and would be happy to submit a pull request. Although, I have not created tests for this yet. Let me know how I can contribute.
