### ISSUE TITLE
ActiveSupport::Duration#inspect yields incorrect value

### ISSUE THREAD

**Issue by madejejej** [rails/rails#34369]
### Steps to reproduce

```ruby
require 'active_support'
require 'minitest/autorun'

class TestDurationInspect < Minitest::Test
  def test_inspect
    t = Time.parse('Tue, 7 Aug 2018 11:34:13 CDT -05:00')
    t1 = Time.parse('Tue, 31 Jul 2018 11:34:13 CDT -05:00')

    diff1 = t - t1 - 7.days
    diff2 = t - 7.days - t1

    assert_equal 0, diff1
    assert_equal 0, diff2
    assert_equal '0.0', diff1.inspect
    assert_equal '0.0', diff2.inspect
  end
end
```

### Expected behavior
The test should pass. Both diff1 and diff2 should yield the same value for inspect.

### Actual behavior
`diff1.inspect` yields `-7 days and 604800.0 seconds` and `diff2.inspect` yields `0.0`:

```ruby
Failure:
TestDurationInspect#test_inspect [/Users/kmadej/Development/as-duration.rb:14]:
Expected: "0.0"
  Actual: "-7 days and 604800.0 seconds"
```
### System configuration
**Rails version**:
5.2.0

**Ruby version**:
2.5.1p57

**Comment by composerinteralia** [comment]
Also reproducible with:

```rb
require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  # Activate the gem you are reporting the issue against.
  gem "activesupport", "5.2.0"
  gem "byebug"
end

require "active_support"
require "active_support/core_ext/numeric/time"
require "minitest/autorun"
require "byebug"

class TestDurationInspect < Minitest::Test
  def test_inspect
    zero_days = 7.days.to_i - 7.days

    assert_equal 0, zero_days
    assert_equal '0.0', zero_days.inspect
  end
end
``` 

We put together the duration with -7 days and 604800 seconds [here](https://github.com/rails/rails/blob/5821b1fd79eddd3dc8bb7ae919f235963e019442/activesupport/lib/active_support/duration.rb#L55..#L60) and the inspect method is [here](https://github.com/rails/rails/blob/5821b1fd79eddd3dc8bb7ae919f235963e019442/activesupport/lib/active_support/duration.rb#L375-L379)

**Comment by madejejej** [comment]
> It is worth noting that 604800 seconds does amount to 7 days, so this is technically correct even if it looks a little funny. to_s does still give the expected value of "0". inspect is telling us about the internal representation, which in this case is -7 days + 604800 seconds. So perhaps this is the expected behavior?

Great question! I agree that it makes sense once you know the internals of the class. But given that all interactive tools like irb and pry use `inspect` to print the object, this can lead to a lot of confusion. 

There was a bug in one of the codebases that I work with - turned out to be timezone-related. But my first thought when I saw this during debugging was that "there must be something wrong with how the time is being calculated here". 

There's additional confusion when the biggest "part" is negative. Does this say it's -(7 days and 604800 seconds) or -(7 days) and +(604800 seconds)?

Maybe we could show the `#to_s` value when there is more than one part?

```ruby
zero_days = 7.days.to_i - 7.days
zero_days.inspect
# => -7 days and 604800.0 seconds (0)

year = 7.days.to_i - 7.days + 1.year
year.inspect
# => 1 year, -7 days, and 604800 seconds (31556952)

2.days.inspect
# => 2 days
```
