### ISSUE TITLE
System tests do not respect `Capybara.javascript_driver`

### ISSUE THREAD

**Issue by iainbeeston** [rails/rails#34379]
### Steps to reproduce

1. Set `Capybara.javascript_driver` in `test_helper.rb`
2. Create a rails system test (without explicitly calling `driven_by`)
3. Run system test

### Expected behavior

The driver set by `Capybara.javascript_driver` should be used to run the test.

### Actual behavior

The Capybara driver is ignored, and `:selenium` is used as the driver instead.

### System configuration
**Rails version**: 5.2.1

**Ruby version**: 2.5.1

### Notes

Capybara has the ability to [set the default javascript driver](https://github.com/teamcapybara/capybara#selecting-the-driver), but rails system tests do not seem to respect this. This is confusing, especially when upgrading a project to use system tests that has previously used integration tests with Capybara.

I've reproduced the issue on [github](https://github.com/iainbeeston/capybara-test) with failing tests which can be seen on [circleci](https://circleci.com/gh/iainbeeston/capybara-test) (FYI tests are written using rspec rather than test unit). I've included tests that show both the old behaviour in integration tests (feature specs in rspec) and the current behaviour in system tests.

**Comment by albertoalmagro** [comment]
Hi @iainbeeston,

Thanks for your report and the detailed reproduction steps. Unless I'm missing something, I see Rails working as expected in the application you submitted.

If you want to set a default driver, the documentation in `ActionDispatch::SystemTestCase` advices to set it by using `driven_by` at `application_system_test_case.rb`. See [here](https://github.com/rails/rails/blob/master/actionpack/lib/action_dispatch/system_test_case.rb#L46).

As far as I can see, tests are using the driver defined in the place indicated in the documentation.

**Comment by iainbeeston** [comment]
@albertoalmagro thanks for your helpful reply, the link to `SystemTestCase` especially was useful.

My issue is what the default behaviour should be, if you **do not** call `driven_by` in `ApplicationSystemTestCase`. Currently, if you do not call `driven_by` yourself, `SystemTestCase` [defaults](https://github.com/rails/rails/blob/fc5dd0b85189811062c85520fd70de8389b55aeb/actionpack/lib/action_dispatch/system_test_case.rb#L141) the driver to `:selenium`.

Because system tests use Capybara, I would expect them to use Capybara settings unless you have overriden them in your own code. As far as I am aware, system tests always respect Capybara's settings, *except* for the driver, which I find confusing, and I believe isn't obvious for anyone who has used Capybara in integration tests and would expect it to respect your existing Capybara config in system tests as well.

I propose that, rather than hard coding `:selenium` in `SystemTestCase` (ie. `driven_by :selenium`), it should instead use `Capybara.javascript_driver` (ie. `driven_by Capybara.javascript_driver`). The default value for `Capybara.javascript_driver` is `:selenium` (see [here](https://github.com/teamcapybara/capybara/blob/master/lib/capybara/config.rb#L79)), so there should be no visible change to anyone using system tests, unless they are:

1. Not calling `driven_by`
2. Have set `Capybara.javascript_driver`

(If both of those are true, then this change means that the driver would change from selenium to whatever has been passed to `Capybara.javascript_driver`)

I'm happy to make a pull request for this change, if the idea sounds acceptable?

**Comment by albertoalmagro** [comment]
@iainbeeston I see your point. On the other hand, this isn't Capybara alone but its Rails integration.

@eileencodes as you wrote this integration I think you are the best to decide about this. May you please tell us what you think? Thanks!

**Comment by iainbeeston** [comment]
Thinking about this some more, it's not as simple as simply changing the existing default, as that default is evaluated at load time, then copied to each subclass of `SystemTestCase`. It would work if you could guarantee that the Capybara driver is overridden before `SystemTestCase` is loaded, but changing the Capybara driver after that point would have no effect. To reliably make it work the way I suggested would mean refactoring `SystemTestCase` to always look up the Capybara driver at runtime when a spec runs. It's not impossible but it doesn't seem to be a trivial change either, for relatively little gain.

**Comment by jeremy** [comment]
Could have `driven_by` accept a block that's evaluated, too. PR welcome! However, this is working as intended, so closing out the issue.
