### ISSUE TITLE
[ Error While Install Nokogiri 1.8.0

### ISSUE THREAD

**Issue by XSecr3t** [rails/rails#34381]
- [ Error While Instalaling Nokogiri 1.8.0 ]

Excuse Me
Hello sir greetings

I have some problem can anybody help me?

I want install Nokogiri 1.8.0 but cant cause have error like this

> To see why this extension failed to compile, please check the mkmf.log which can be found here:
>/data/data/com.termux/files/usr/lib/ruby/gems/2.5.0/extensions/aarch64-linux/2.5.0/nokogiri-1.8.0/mkmf.log
> extconf failed, exit code 1
> Gem files will remain installed in /data/data/com.termux/files/usr/lib/ruby/gems/2.5.0/gems/nokogiri-1.8.0 for inspection.
Results logged to /data/data/com.termux/files/usr/lib/ruby/gems/2.5.0/extensions/aarch64-linux/2.5.0/nokogiri-1.8.0/gem_make.out

I have already run any command that i see like

> gem install nokogiri -- --use-system-libraries
        [--with-xml2-config=/path/to/xml2-config]
        [--with-xslt-config=/path/to/xslt-config]
Or
> bundle config build.nokogiri --use-system-libraries
    bundle install

But the result still same, exit  ode 1

So what should i do?
I already uninstalled and installed again my termux 10times since 2 day ago
And Rebuild Package but the result still same,error code 1
It sucks for me can anyone help me sir?

It would be pleasure if somebody help me for guide me how to fix this problems.
First time i use termux looks good and everything is fine,but after 3 or 4 month everything has change,i already update every second every files and package but the result still same.

Somebody please help me🙁🙁

Because this problem i cannot run my metasploit again.

> here more error : http://i67.tinypic.com/343maoh.png
http://i67.tinypic.com/2ahz9f9.png
http://i66.tinypic.com/23w08yr.png
http://i67.tinypic.com/4uyk1y.png
http://i65.tinypic.com/2w7ph12.png
http://i68.tinypic.com/2vjph6r.png
http://i67.tinypic.com/20shis5.png

I think someone can help me for solve this,i dont know what i want to do again,,,
I'll do everything but still same

i try to used following command

> LDFLAGS=" -lglob" gem install nokogiri -- --use-system-libraries.

But the result said i installed nokogiri 1.8.5 not 1.8.0 versions,my metasploit needs nokogiri 1.8.0 not 1.8.5

> result :
LDFLAGS=" -lglob" gem install nokogiri -- --use-system-libraries
WARNING: linker: Unsupported flags DT_FLAGS_1=0x8
WARNING: linker: Unsupported flags DT_FLAGS_1=0x8
Building native extensions with: '--use-system-libraries'
This could take a while...
Successfully installed nokogiri-1.8.5
Parsing documentation for nokogiri-1.8.5
Done installing documentation for nokogiri after 10 seconds
1 gem installed
root@Mr.XSecr3t:#

When i run msfconsole result said

> root@Mr.XSecr3t:#msfconsole
Could not find nokogiri-1.8.0 in any of the sources
Run bundle install to install missing gems.
root@Mr.XSecr3t:#

And when i run bundle install the result said

> root@Mr.XSecr3t:#bundle install
WARNING: linker: Unsupported flags DT_FLAGS_1=0x8
WARNING: linker: Unsupported flags DT_FLAGS_1=0x8
Could not locate Gemfile
root@Mr.XSecr3t:#

so can anybody help me fix this problems? i dont know what i want to do,i cant run my metasploit again. 🙁🙁

thanks for helping me and reply my issued!

**Comment by albertoalmagro** [comment]
Sorry @XSecr3t, but we can't help you here with your problem. This section is reserved for Rails' issues only. If you have trouble installing Nokogiri, please try to submit a question on sites like StackOverflow, where a dedicated community will be able to help you.

Thanks and good luck!

**Comment by XSecr3t** [comment]
@albertoalmagro thanks for replying me! Sorry for wasting your time
