### ISSUE TITLE
ActiveRecord: When having a column named 'id' of type text, the ids are forced to integers

### ISSUE THREAD

**Issue by entwanderer** [rails/rails#34380]
## Steps to reproduce
Given a PostgreSQL OR MariaDB database (retested with both) with a table, containing a id of data type text:

### DB Model - table: **machines**
```
# table 'machines'
sid: integer (PRIMARY KEY, DEFAULT: AUTO_INCREMENT)
name: text
id: text (DEFAULT: NULL)
```

### PRY console or IRB
```ruby
require 'active_record'

ActiveRecord::Base.establish_connection(
  :adapter  => "mysql2",
  :host     => "localhost",
  :username => "root",
  :password => "root",
  :database => "test"
)

class Machine < ActiveRecord::Base
end

Machine.primary_key
=> "sid"

Machine.attribute_types
=> {"sid"=>#<ActiveModel::Type::Integer:0x0000000003d541e0 @limit=4, @precision=nil, @range=-2147483648...2147483648, @scale=nil>,
 "name"=>#<ActiveRecord::Type::Text:0x0000000003d6ed10 @limit=65535, @precision=nil, @scale=nil>,
 "id"=>#<ActiveRecord::Type::Text:0x0000000003d6ed10 @limit=65535, @precision=nil, @scale=nil>}

m = Machine.new
=> #<Machine:0x0000000003d2e7b0 sid: nil, name: nil, id: nil>

m.name = "super machine"
m
=> #<Machine:0x0000000003d2e7b0 sid: 0, name: "super machine", id: nil>

m.id = "foo"
m
=> #<Machine:0x0000000003d2e7b0 sid: 0, name: "super machine", id: 0>

m.save
=> true
```

```
# database
| sid | name          | id   |
| 0   | super machine | NULL |
```

## Expected behavior
When i write to attribute 'id' of type string, it should contain the assigned string ("foo").

## Actual behavior
The assigned string value seems to be forced or transformed into integer. (string.to_i) "foo".to_i => 0

## System configuration
**Rails version**:
Not using with rails, using active record separate:
```
    activerecord (5.2.1)
      activemodel (= 5.2.1)
      activesupport (= 5.2.1)
      arel (>= 9.0)
```
**Ruby version**:
`ruby 2.4.4p296 (2018-03-28 revision 63013) [x64-mingw32]`

**Comment by eugeneius** [comment]
The `id=` method [always sets the primary key](https://api.rubyonrails.org/v5.2.1/classes/ActiveRecord/AttributeMethods/PrimaryKey.html#method-i-id-3D), even if the primary key isn't named `id`, and even if another attribute named `id` exists.

This means that when you run `m.id = "foo"` in your reproduction steps, you're actually setting the `sid` attribute, so the value being coerced to an integer is expected.

However, there is a bug here: the output of `inspect` should show the actual value of the `id` attribute, not that of the primary key. I've opened https://github.com/rails/rails/pull/34384 to address that problem.

**Comment by entwanderer** [comment]
I guess closed issues are not observed, so i will create another issue for that.
