### ISSUE TITLE
ActiveSupport::Dependencies#autoload_module! creates a module that doesn't exist

### ISSUE THREAD

**Issue by jcoyne** [rails/rails#34397]
### Steps to reproduce

If there is a path in `myapp/app/javascript/foo/bar` that has nothing but javascript files.
And there are modules `Foo` and `Bar` defined in Ruby:
```ruby
# app/models/foo.rb
module Foo

  def self.hello
     Bar.hello
  end
end
```

```ruby
# app/models/bar.rb
module Bar
  def self.hello
     "hi"
  end
end
```

Then if you call `Foo::Bar` the `Foo::Bar` constant will get defined.

The problem is that when you call `Foo.hello` it resolves `Bar` as `Foo::Bar` rather than `::Bar`

### Expected behavior
No constant should be defined. A name error should be thrown. 

### Actual behavior
the `Foo::Bar` constant will is defined.  This is surprising as it's nowhere in my Ruby code. I believe this happens in https://github.com/rails/rails/blob/master/activesupport/lib/active_support/dependencies.rb#L459

### System configuration
**Rails version**: 5.2.1

**Ruby version**: 2.5.3

**Comment by rafaelfranca** [comment]
How would you think about this behavior if this folder was inside `app/models/foo/bar/baz.rb`? Would you think that that `Foo::Bar` constant makes sense?

**Comment by rafaelfranca** [comment]
Yeah. The real problem is that `app/javascript` and `app/assets` are in the autoload paths. We should remove them.

**Comment by gmcgibbon** [comment]
I'll try to fix this.
