### ISSUE TITLE
The URL module api document is inadequate.

### ISSUE THREAD

**Issue by h-haraguchi** [rails/rails#34396]
In version of 5.2, URL module api document is not described about public instance method. 
https://api.rubyonrails.org/v5.2/classes/ActionDispatch/Http/URL.html
https://api.rubyonrails.org/v5.1/classes/ActionDispatch/Http/URL.html

**Comment by gmcgibbon** [comment]
To clarify, I believe you mean the lack of documentation for `#full_url_for`, `#path_for`, and `#url_for`, is that right?

**Comment by kamipo** [comment]
Somehow 5.2 and edge api doc show only Class Public methods section, don't show Instance Public methods section.

**Comment by gmcgibbon** [comment]
Oh, my mistake. You're right! I'll investigate this today.

**Comment by gmcgibbon** [comment]
It would appear that Ruby 2.4.x has something to do with this issue. Generating locally on 2.5.1 doesn't have this issue whereas 2.4.1, 2.4.5, and 2.4.4 all do. Upgrading our docs server to use 2.5.x should solve this, but I don't really know why. I'll open an issue on rdoc.

**Comment by rafaelfranca** [comment]
@fxn are you ok with me changing the requirements to Ruby 2.5 in the doc server for 5.2 and master?

**Comment by fxn** [comment]
@rafaelfranca absolutely. This week I have two talks to deliver that are eating my spare time, but I could do it afterwards. Of course, if you'd like to upgrade it yourself just go ahead 😄.

**Comment by rafaelfranca** [comment]
Don't worry. I'll take care of it.

**Comment by rafaelfranca** [comment]
Fixed https://edgeapi.rubyonrails.org/classes/ActionDispatch/Http/URL.html
