### ISSUE TITLE
cache_key not changing when using limit, order and offset (e.g. pagination)

### ISSUE THREAD

**Issue by Svelix** [rails/rails#34408]
I know there has already been some tinkering with with cache_key and pagination, but I encountered a new problem:

Given I have some records ordered by some property and paginated:

id | name    | updated_at
-- | ------- | -----------
1  | Alfa    | 12:01
2  | Bravo   | 12:02
3  | Charlie | 12:03
-- | ------- | -----------
4  | Delta   | 12:04
5  | Echo   | 12:06
6  | Foxtrot    | 12:05
-- | ------- | -----------
7  | Golf | 12:07
8  | Hotel    | 12:08
9  | India   | 12:09

In this example I have pages with a limit of 3, so the cache_keys of the 3 pages would be based on the updated_at values like so:
Page 1: 12:03
Page 2: 12:06
Page 3: 12:09

When I now change an entry in a way that it is put onto another page, e.g. I rename Hotel to Alpha2, I get the following pages:

id | name    | updated_at
-- | ------- | -----------
1  | Alfa    | 12:01
8  | Alpha2 | 12:50
2  | Bravo   | 12:02
-- | ------- | -----------
3  | Charlie | 12:03
4  | Delta   | 12:04
5  | Echo   | 12:06
-- | ------- | -----------
6  | Foxtrot    | 12:05
7  | Golf | 12:07
9  | India   | 12:09

And the cache_keys are based on this values:

Page 1: 12:50
Page 2: 12:06
Page 3: 12:09

As you can see the content of all 3 pages did change, but only the cache_key of Page 1 did change. Page 2 and Page 3 do still have the same cache_key.

The workaround I used to fix this in our project is by removing the scope, calculating the cache_key and appending the scope-values to that key:
```
cache_key = "#{products.unscope(:limit, :offset).cache_key}-#{products.limit_value}-#{products.offset_value}"
```

This way every page still has its own cache-entry, but when any product is changed, all the pages are invalidated.

I think this is the only way to ensure correct cache_keys if values of the order column can change.
 
### System configuration
**Rails version**: 5.1.6
**Ruby version**: 2.5.1

**Comment by y-yagi** [comment]
Can you please provide a sample application that reproduces the issue?

**Comment by kamipo** [comment]
Related #27570, #34093.

**Comment by aried3r** [comment]
@Svelix, in case you're using PostgreSQL, I solved it using https://github.com/alekseyl/pg_cache_key. However I'm not sure if using this gem affects the usage of https://github.com/rails/rails/pull/29092.

@kamipo, I think these might also be related:
#21503
#25454
#25496
#26330
#27331
#28075

**Comment by danielwestendorf** [comment]
I can confirm this is a problem on rails 5.2.1, specifically when an item is removed from the collection. My fix was (since I'm using [kaminari](https://github.com/kaminari/kaminari/)) to override the class method `collection_cache_key` in `ApplicationRecord` to include the `#total_count` in the cache key.

```rb
# models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true

  def self.collection_cache_key(collection = all, timestamp_column = :updated_at)
    if collection.respond_to?(:total_count)
      "#{super}-#{collection.total_count}"
    else
      super
    end
  end
end
```

This specifically impacts Russian doll caching when doing something like

```
<% products =  Product.page(params[:page]).per(10) %>
<% cache ["v1", products]" %>
  <%= render partial: "product", collection: products, cache: true %>
<% end %>
```

and one of the products is deleted, as `collection.records.size` will always return 10 when > 10 products.

**Comment by Svelix** [comment]
@danielwestendorf adding the total_count does only help when you add/delete items, doesn't it?
When you move an item from one page to another like I described above the total_count will still be the same.

**Comment by danielwestendorf** [comment]
@Svelix Correct. In my case, the work around was more simple than dealing with the `offset` and `limit` of the query.

**Comment by Svelix** [comment]
I can still reproduce this issue on the 5-2-stable branch **and** on master.
I updated my demo-project.

**Comment by courtsimas** [comment]
It would be really nice to have a solid plan of attack on this. This has been a common problem for years, with many developers and organizations having their own workaround without a general census on the best way to tackle this.

**Comment by Svelix** [comment]
Yep, I agree.
I suggested a possible solution in the original post when I described our work-around.
But I am not sure if anybody of the Rails-team actually reads this, since the issue is marked as stale.

**Comment by saiqulhaq** [comment]
I have this issue too
I added `records.maximum(:updated_at)` to fix it
