### ISSUE TITLE
ActiveRecord: Can not assign any text value to non-primary attribute id of type text

### ISSUE THREAD

**Issue by entwanderer** [rails/rails#34402]
## Steps to reproduce
Given a PostgreSQL OR MariaDB database (retested with both) with a table, containing a id of data type text:

### DB Model - table: **machines**
```
# table 'machines'
sid: integer (PRIMARY KEY, DEFAULT: AUTO_INCREMENT)
name: text
id: text (DEFAULT: NULL)
```

### PRY console or IRB
```ruby
require 'active_record'

ActiveRecord::Base.establish_connection(
  :adapter  => "mysql2",
  :host     => "localhost",
  :username => "root",
  :password => "root",
  :database => "test"
)

class Machine < ActiveRecord::Base
end

Machine.primary_key
=> "sid"

Machine.attribute_types
=> {"sid"=>#<ActiveModel::Type::Integer:0x0000000003d541e0 @limit=4, @precision=nil, @range=-2147483648...2147483648, @scale=nil>,
 "name"=>#<ActiveRecord::Type::Text:0x0000000003d6ed10 @limit=65535, @precision=nil, @scale=nil>,
 "id"=>#<ActiveRecord::Type::Text:0x0000000003d6ed10 @limit=65535, @precision=nil, @scale=nil>}

m = Machine.new
=> #<Machine:0x0000000003d2e7b0 sid: nil, name: nil, id: nil>

m.assign_attributes name: "machine_01", id: "SN123"
=> nil

m
=> #<Machine:0x0000000005894220 sid: 0, name: "machine_01", id: 0>

m.assign_attributes sid: 500
=> nil

m
=> #<Machine:0x0000000003e260c8 sid: 500, name: "machine_01", id: 500>

m.save
=> true
```

```
# database
| sid | name          | id   |
| 500   | machine_01 | NULL |
```

## Expected behavior
When i write to attribute `id` of type string, it should contain the assigned string ("SN123").

When i write to attribute `sid`, the attribute `id` should not be touched or even overwritten by the value of `sid`.

When i save the model to the database, the assigned text value "SN123" is stored in column `id`.

## Actual behavior
The to `id` assigned string value  seems to be forced or transformed into integer - the format of the primary key `sid`.

Any change to `id` changes `sid` and vice versa.

There is no way to handle `id` and `sid` separate.
There is no way to write a string into the non-primary field `id`.

When saving the model to the database, `id` gets (default) value 'NULL'.

## System configuration
**Rails version**:
Not using with rails, using active record separate:
```
    activerecord (5.2.1)
      activemodel (= 5.2.1)
      activesupport (= 5.2.1)
      arel (>= 9.0)
```
**Ruby version**:
`ruby 2.4.4p296 (2018-03-28 revision 63013) [x64-mingw32]`

**Comment by gmcgibbon** [comment]
This is tricky because it goes against conventions. I would suggest redefining all the reader and writer methods [here](https://github.com/rails/rails/blob/023a840f5f10c5a611a0618ff8ea9e16cd771f93/activerecord/lib/active_record/attribute_methods/primary_key.rb) on your model to explicitly use `"id"` instead of `self.class.primary_key` and remove the `sync_with_transaction_state` lines. This, however, may break something.

I think adjusting this behaviour is equally as difficult because it would break apps that depend on it.

**Comment by rafaelfranca** [comment]
Yes. `id` has special meaning in Rails. The column `id` can be of the string type, but it need to be the primary key.
