### ISSUE TITLE
ActiveSupport::HashWithIndifferentAccess works differently from Ruby native Hash

### ISSUE THREAD

**Issue by hananamar** [rails/rails#34404]
Found an anomaly in the behavior of ActiveSupport::HashWithIndifferentAccess when compared to Ruby's native Hash.

### Expected behavior
```
h = Hash.new { |h, k| h[k] = {foo: []} }
# => {}
h[:new_symbol][:foo] << 1
# => [1]
h[:new_symbol][:foo]
# => [1]

```
### Actual behavior
```
h = ActiveSupport::HashWithIndifferentAccess.new { |h, k| h[k] = {foo: []} }
# => {}
h[:new_symbol][:foo] << 1
# => [1]
h[:new_symbol][:foo]
# => []

```
### System configuration
**Rails version**: 5.2.1

**Ruby version**: 2.5.3p105

**Comment by rafaelfranca** [comment]
There is no much we can do. The value that a `=` returns is the same value that you pass as argument to it. So it will be the original `{foo: []}` not the one that will be copied to the `HashWIthIndiferentAccess`. The important thing here is copied. When you assigned a hash to a value of `HashWIthIndiferentAccess` we copy the value so we are not mutating your original object.

This code would make it work:

```
h = ActiveSupport::HashWithIndifferentAccess.new { |h, k| h[k] = {foo: []}; h[k] }
```

**Comment by hananamar** [comment]
Thanks @rafaelfranca.
I guess I understand why the assignment does not work in the HashWithIndifferentAccess's case, but not certain I understand what _does_ make it work in the Hash case.
Do you mind illuminating?

**Comment by rafaelfranca** [comment]
Mostly because hash assignments don't copy the arguments.
