### ISSUE TITLE
Why are has_one through has_one relationships not constructible in the same way that has_many through has_many relationships are? 

### ISSUE THREAD

**Issue by eric-norcross** [rails/rails#34422]
### Steps to reproduce
code example on SO: https://stackoverflow.com/questions/53243674/build-methods-for-has-one-though-has-one/53244188#53244188

Nested `has_many` through `has_many` relationships can be built using the `s.promotions.build` method, but this not the case with `has_one` through `has_one` relationships – `s.build_promotion`

### Expected behavior
building `has_one` through `has_one` relationships should behave the same as building `has_many` through `has_many` relationships

### Actual behavior
While building nested models works with `has_many` through `has_many` relationships (e.g.: `s.promotions.build`) using the equivalent `has_one` method (e.g.: `s.build_promotion`) produces a `NoMethodError (undefined method 'build_promotion' for #<Subscriber:0x00007f9042cbd7c8>)` error.

However, building the initial through relationship (e.g.: `s.build_subscription`) does work

### System configuration
**Rails version**:
5.1.2

**Ruby version**:
2.5.3

**Comment by y-yagi** [comment]
Please use the [mailing list](https://groups.google.com/forum/#!forum/rubyonrails-talk) or StackOverflow for questions/help, where a wider community will be able to help you. We reserve the issues tracker for issues only. Thanks.

**Comment by eric-norcross** [comment]
@y-yagi – I'm happy to use
