### ISSUE TITLE
redirect_to ignores arguments to find matching route

### ISSUE THREAD

**Issue by lacostej** [rails/rails#34427]
### Steps to reproduce

We are reusing controllers in different scopes. They differ by the arguments passed to them.

We have found 2 issues. This is the first one, the second one being #34428.

When using `redirect_to`, rails fails to find the appropriate target even when specifying full information to the redirect_to.

I assume it is related to this note in the routing guide (https://guides.rubyonrails.org/routing.html#defining-defaults)

> You cannot override defaults via query parameters - this is for security reasons.
> The only defaults that can be overridden are dynamic segments via substitution in the URL path.

But it doesn't explain why the routing cannot find the controller.
Given

```ruby

Rails.application.routes.draw do
  [ :en, :fr ].each do |lang|
    scope(lang, defaults: {lang: lang}) do
      get '/', to: "sthg#home"
      get '/page2', to: "sthg#page2"
    end  
  end
```

And 

```
class SthgController < ApplicationController
  before_action :set_lang

  def home
        # None of these work
  	# redirect_to :page2
  	# redirect_to :page2, lang: @lang
  	# redirect_to controller: controller_path, action: :page2, lang: @lang
  end

  def page2
  	render :page2
  end

  private
  def set_lang
  	@lang = params[:lang]
  end
end
```

### Expected behavior
When opening /fr/ we redirected to /fr/page2

### Actual behavior
When opening /fr/ we get redirected to /en/page2

See the 3 different implementations under #home

### System configuration
**Rails version**: 5.2.1

**Ruby version**: 2.5.3

Full repository for #34427 and #34428 available at https://github.com/lacostej/rails_redirect_weirditities

**Comment by rafaelfranca** [comment]
Does `redirect_to controller: "sthg", action: "page2", lang: @lang` work?

**Comment by lacostej** [comment]
@rafaelfranca 

> Does redirect_to controller: "sthg", action: "page2", lang: @lang work?

no.

```
  def home
        # None of these work
  	# redirect_to :page2
  	# redirect_to :page2, lang: @lang
  	# redirect_to controller: controller_path, action: :page2, lang: @lang
  end
```

**Comment by albertoalmagro** [comment]
May I take this one?

**Comment by rafaelfranca** [comment]
Yes. Please do investigate!

**Comment by rafaelfranca** [comment]
Thank you for the detailed investigation.

**Comment by albertoalmagro** [comment]
My pleasure!

**Comment by lacostej** [comment]
Muchas gracias Alberto.

Just for the sake of history. The reason we ended up with this configuration is that we had started with

```ruby
Rails.application.routes.draw do
  [ :en, :fr ].each do |lang|
    scope(lang) do
      get '/', to: "sthg#home", lang: lang
      get '/page2', to: "sthg#page2", lang: lang
      ......
    end
  end
end
```

and after finding 
![screen shot 2018-11-15 at 7 50 56 am](https://user-images.githubusercontent.com/24282/48535319-38839800-e8ab-11e8-9537-304b35a2d005.png)

(from https://guides.rubyonrails.org/routing.html#defining-defaults), we refactored it to

```ruby
Rails.application.routes.draw do
  [ :en, :fr ].each do |lang|
    scope(lang, defaults: {lang: lang}) do
      get '/', to: "sthg#home"
      get '/page2', to: "sthg#page2"
      ....
    end
  end
end
```

It seemed like a natural refactoring but broke the functionality.

We will look into dynamic segments.
