### ISSUE TITLE
redirect_to doesn't work without controller when controller is reused in different scopes

### ISSUE THREAD

**Issue by lacostej** [rails/rails#34428]
### Steps to reproduce

We are reusing controllers in different scopes. They differ by the arguments passed to them.

We have found 2 issues. This is the second one, the second one being #34427 .

When using `redirect_to`, rails fails to find the appropriate target unless we specify the controller.

Given

```ruby

Rails.application.routes.draw do
  [ :en, :fr ].each do |lang|
    scope(lang) do
      get '/', to: "sthg#home", lang: lang
      get '/page2', to: "sthg#page2", lang: lang
    end  
  end
```

And 

```
class SthgController < ApplicationController
  before_action :set_lang

  def home
        # this one doesn't work, acceptable
  	# redirect_to :page2

        # this one works, but is very verbose
  	# redirect_to controller: controller_path, action: :page2, lang: @lang

        # this one doesn't work, why?
  	redirect_to :page2, lang: @lang
  end

  def page2
  	render :page2
  end

  private
  def set_lang
  	@lang = params[:lang]
  end
end
```

### Expected behavior
When opening /fr/ we redirected to /fr/page2

### Actual behavior
When opening /fr/ we get redirected to /en/page2

### System configuration
**Rails version**: 5.2.1

**Ruby version**: 2.5.3

Full repository for #34427 and #34428 available at https://github.com/lacostej/rails_redirect_weirditities

**Comment by rafaelfranca** [comment]
The documentation of [`url_for`](http://api.rubyonrails.org/classes/ActionDispatch/Routing/UrlFor.html#method-i-url_for) contain the explaination for it. http://api.rubyonrails.org/classes/ActionView/RoutingUrlFor.html#method-i-url_for. `:page2` is not a valid route. You either need the named route helper of the `action:, controller:` pair.

**Comment by lacostej** [comment]
doh... My bad. It works with "action: :page2" as well.
