### ISSUE TITLE
url_for: NoMethodError: undefined method `model_name' for #<Array:0x00007fec1c437f28>

### ISSUE THREAD

**Issue by basmoura** [rails/rails#34432]
Hello, everybody :)

I'm trying to update my app to Rails 5.2.1 but I'm having some curious error. My application is working without any problem for now if I access http://localhost:3000, but when I run my test suit I'm facing error related to action-pack.

Basically, all the errors are saying `undefined method `model_name' for #<Array:0x00007fec1c437f28>` for all `url_for`s that I have on my application.

As I said, my application runs OK but my test suit doesn't. 

### Expected behavior
Specs that uses `url_for` works ok.

### Actual behavior
```
       Failure/Error: get url_for([:edit, scope, customer])

       NoMethodError:
         undefined method `model_name' for #<Array:0x00007fec07923e48>
       Shared Example Group: "can edit customer" called from ./spec/requests/shared/customers_request_spec.rb:166
       # /Users/basmoura/.rvm/gems/ruby-2.5.3/gems/actionpack-5.2.1/lib/action_dispatch/routing/polymorphic_routes.rb:171:in `polymorphic_mapping'
       # /Users/basmoura/.rvm/gems/ruby-2.5.3/gems/actionpack-5.2.1/lib/action_dispatch/routing/polymorphic_routes.rb:108:in `polymorphic_url'
       # /Users/basmoura/.rvm/gems/ruby-2.5.3/gems/actionpack-5.2.1/lib/action_dispatch/routing/url_for.rb:186:in `full_url_for'
       # /Users/basmoura/.rvm/gems/ruby-2.5.3/gems/actionpack-5.2.1/lib/action_dispatch/routing/url_for.rb:169:in `url_for'
       # ./spec/requests/shared/customers_request_spec.rb:148:in `block (3 levels) in <top (required)>'
```

### System configuration
**Rails version**: 5.2.1
**Ruby version**: 2.5.3

**Comment by rafaelfranca** [comment]
Can you reproduce this issue without rspec?

**Comment by rafaelfranca** [comment]
Also there is any chance your application has a `Array#to_model` method defined?

**Comment by basmoura** [comment]
No, @rafaelfranca! This error only occurs when I run my tests

**Comment by rafaelfranca** [comment]
I'm almost sure it is something in your app. Rails before calling [`model_name` it checks if the arguments to `url_for` responds to `to_model`](https://github.com/rails/rails/blob/v5.2.1/actionpack/lib/action_dispatch/routing/polymorphic_routes.rb#L170). `Array` doesn't respond to `to_model` so `model_name` should never be called in a normal workflow. Something in your test suite is defining `to_model` in `Array` or making `respond_to?(:to_model)` return true..

**Comment by basmoura** [comment]
@rafaelfranca good point. I will check on my code and test suite if I can find something related to what said.

**Comment by basmoura** [comment]
@rafaelfranca I didn't find any result. An interesting/weird behavior is: if I run just the same file or folder that have broken test, the specs are green. For example:

when I ran `rspec` (the hole suite is tested)
```
  487) Video Conference POST #update_notes when current_expert is different consult expert renders head forbidden
       Failure/Error:
         post url_for([:update_notes, :expert, :consult, :video_conference,
                       :index, consult_id: consult, notes: 'notes'])

       NoMethodError:
         undefined method `model_name' for [:update_notes, :expert, :consult, :video_conference, :index]:Array
       # /Users/basmoura/.rvm/gems/ruby-2.5.3/gems/actionpack-5.2.1/lib/action_dispatch/routing/polymorphic_routes.rb:171:in `polymorphic_mapping'
       # /Users/basmoura/.rvm/gems/ruby-2.5.3/gems/actionpack-5.2.1/lib/action_dispatch/routing/polymorphic_routes.rb:108:in `polymorphic_url'
       # /Users/basmoura/.rvm/gems/ruby-2.5.3/gems/actionpack-5.2.1/lib/action_dispatch/routing/url_for.rb:186:in `full_url_for'
       # /Users/basmoura/.rvm/gems/ruby-2.5.3/gems/actionpack-5.2.1/lib/action_dispatch/routing/url_for.rb:169:in `url_for'
       # ./spec/requests/expert/video_conference_request_spec.rb:62:in `block (4 levels) in <top (required)>'
```

Then if I run only `rspec spec/requests/expert/video_conference_request_spec.rb` (with or without the seed of the specs that brake) I got:

```
Randomized with seed 61999
.................

Finished in 14.87 seconds (files took 15.09 seconds to load)
17 examples, 0 failures
```

**Comment by basmoura** [comment]
@rafaelfranca I'm closing this issue. This is not a issue or bug related to Rails. Thank you for your help!

**Comment by rafaelfranca** [comment]
Glad you found the issue!
