### ISSUE TITLE
Filter out parameters in ActiveJob

### ISSUE THREAD

**Issue by davidpiegza** [rails/rails#34439]
### Steps to reproduce

The arguments passed to the `perform` method are logged by ActvieJob without filtering sensitive data. 

Example:
```ruby
# frozen_string_literal: true

require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  gem "rails", github: "rails/rails"
end

require "active_job"
require "minitest/autorun"

class BuggyJob < ActiveJob::Base
  def perform(params)
    puts "performed"
  end
end

class BuggyJobTest < ActiveJob::TestCase
  def test_stuff
    assert_enqueued_with(job: BuggyJob) do
      BuggyJob.perform_later(sensitive_data: 'secret_value')
    end
  end
end
```

Log output:

```
[ActiveJob] Enqueued BuggyJob (Job ID: c9c3ce52-6b12-45ed-9808-44d924d9a90e) to Test(default) with arguments: {:sensitive_data=>"secret_value"}
```

### Expected behavior
Arguments should be filtered based on the setting `config.filter_parameters` before they are logged. 

The documentation says that Rails is actually filtering the parameters:
> config.filter_parameters used for filtering out the parameters that you don't want shown in the logs, such as passwords or credit card numbers. 

But it probably just applies to request parameters.

The parameters could be filtered in ActiveJob by using `ActiveSupport::ParameterFilter` which is shown in PR #34438.

### Actual behavior
Arguments with sensitive data are logged without filtering.

### System configuration
**Rails version**: 5.2.1

**Ruby version**: 2.5.0

**Comment by rafaelfranca** [comment]
Let's keep the discussion in the PR.
