### ISSUE TITLE
Limit ActiveModel::Type::Date/DateTime year to 9999?

### ISSUE THREAD

**Issue by janosch-x** [rails/rails#34433]
Maybe the `year` value should be [`#clamp`](https://ruby-doc.org/core-2.4.0/Comparable.html#method-i-clamp)ed to be between 0 and 9999 in [`#new_date`](https://github.com/rails/rails/blob/cfbde022eedde2ae45e2dde9e3d8792933f070f4/activemodel/lib/active_model/type/date.rb#L44) and [`#new_time`](https://github.com/rails/rails/blob/cc81cd359c82bfba27388237a455fc345dce3c9f/activemodel/lib/active_model/type/helpers/time_value.rb#L53).

Reasons:

- higher values are allowed by ActiveModel but cause database errors when persisting, e.g. `Mysql2::Error: Incorrect date value: '1971407-07-17`

- it seems unlikely that anyone needs 5-digit or greater years

- min/max year in datetimes for various databases:

mysql: 0 / 9999
pgsql: -4713 / 294276
sqlite: 0 / 9999

Should I provide a PR for this?

**Comment by rafaelfranca** [comment]
Even that datastores can't store it is a valid year so I don't think it worth validating the year range for every assignment of a Date/Time field in every application, even that it is unlikely to happen. If this is important for your application you can add a validation.
