### ISSUE TITLE
Dynamically change the connection used by a thread?

### ISSUE THREAD

**Issue by vtm9** [rails/rails#34447]
How can I change the connection of one thread? I want to do that:
```ruby
conn1 = ActiveRecord::Base.connection_pool.checkout
conn2 = ActiveRecord::Base.connection_pool.checkout

ActiveRecord::Base.connection_pool.with_connection(conn1) do
  SomeService.call
end

ActiveRecord::Base.connection_pool.with_connection(conn2) do
  SomeService.call
end
```

I found this patch in internet: 

```ruby
module ActiveRecord
  module ConnectionAdapters
    class ConnectionHandler
      def retrieve_connection(klass) #:nodoc:
        pool = retrieve_connection_pool(klass)
        raise ConnectionNotEstablished, "No connection pool for #{klass}" unless pool

        conn = Thread.current['connection'] || pool.connection
        raise ConnectionNotEstablished, "No connection for #{klass} in connection pool" unless conn

        conn
      end
    end
  end
end


 Thread.current['connection'] = conn1

```
But i think it's not good. 

Thanks all!!!

**Comment by rafaelfranca** [comment]
Please use the mailing list or StackOverflow for questions/help, where a wider community will be able to help you. We reserve the issues tracker for issues only.

**Comment by vtm9** [comment]
Hi @rafaelfranca.
The question already exists [on StackOverflow](https://stackoverflow.com/questions/28142373/rails-4-2-how-to-dynamically-change-the-connection-used-by-a-thread) for 4 years. But there are no good answers.
I think it's a good idea to manually manage connections in a single Thread.
And if it possible i would like to contribute this feature, that's why I create issue.
