### ISSUE TITLE
Attribute API crashes on has_many :through

### ISSUE THREAD

**Issue by hult** [rails/rails#34445]
### Steps to reproduce

Repo with the bug here: https://github.com/hult/activerecord-attribute-api-bug

If I have a custom attribute

```ruby
class MyStruct < Struct.new(:data)
end

class MyType < ActiveRecord::Type::Value
  def cast(value)
    if value.is_a? MyStruct
      value
    else
      MyStruct.new(value)
    end
  end

  def deserialize(value)
    MyStruct.new(value)
  end

  def serialize(value)
    if value.is_a? MyStruct
      value[:data]
    else
      value
    end
  end
end
```

and a model (with the corresponding tables, `authors(id)`, `blogs(id)`, `posts(id, author_id, blog_id)`)

```ruby
class Author < ApplicationRecord
  # has_many :posts  # Note this is commented out
end

class Blog < ApplicationRecord
  has_many :posts
  has_many :authors, through: :posts

  attribute :id, MyType.new
end

class Post < ApplicationRecord
  belongs_to :blog
  belongs_to :author
end
```

### Expected behavior

I should be able to do `Blog.first.authors`

### Actual behavior

`Blog.first.authors` crashes with the error `TypeError: can't cast MyStruct` in `activerecord-5.2.1/lib/active_record/connection_adapters/abstract/quoting.rb`.

If I add the commented-out line `has_many :posts` to `Author`, everything works fine (it also works, of course, if I comment out `attribute :id, MyType.new` in `Blog`).

### System configuration
**Rails version**: 5.2.1

**Ruby version**: 2.5.3

**Comment by hult** [comment]
I also have an alternative version of the error (that I have found no workaround for) in another branch: https://github.com/hult/activerecord-attribute-api-bug/tree/alternative-error

Here, we introduce another model `Reader`, of which a `Blog` has many and an author has many through its blogs:

```diff
 class Author < ApplicationRecord
-  # has_many :posts # Can't cast MyStruct if we comment this out
+  has_many :posts # Can't cast MyStruct if we comment this out
+  has_many :blogs, through: :posts
+  has_many :readers, through: :blogs
+
+  attribute :id, MyType.new
 end

 class Blog < ApplicationRecord
   has_many :posts
   has_many :authors, through: :posts
+  has_many :readers
- 
-  attribute :id, MyType.new
 end

+class Reader < ApplicationRecord
+  belongs_to :blog
+end
```

In this scenario, `Author.first.readers` crashes with the same error (but goes away if the author id doesn't have the custom type)

**Comment by gmcgibbon** [comment]
This is happening in your first example (with no  `has_many :posts` on `Author`) because the attribute type of `blog_id` (`ActiveModel::Type::Value`) isn't being inferred correctly when attempting to build the SELECT query. With the `has_many :posts` set, it seems to correctly guess it to be a `ActiveRecord::ConnectionAdapters::SQLite3Adapter::SQLite3Integer`. I'm not super familiar with the query building part of ActiveRecord, but I feel like there's something we can do to fix this.

**Comment by gmcgibbon** [comment]
For the second example you need to add `has_many :posts, through: :blog` to your `Reader` model. 

Here's what is going on:

When building the query from author to find their readers, you go through blogs, which goes through posts. In order for the `author_id` on posts to be cast correctly for the query, ActiveRecord must know what kind of attribute it is. `has_many :posts, through: :blog` allows `Reader` to reflect on `Post` so `Reader` can have knowledge of what type `author_id` is ( `ActiveRecord::ConnectionAdapters::SQLite3Adapter::SQLite3Integer`, or `ActiveModel::Type::Value` when the association is not added). It would seem the casting method of the sqlite integer is able to parse your struct whereas by default no casting happens.

Normally, this isn't a problem as plain old numbers don't need to be casted before query building. In light of this, it would appear that your app is not providing rails with enough info to build queries, so this isn't a bug. I'm going to close this for now, but please let me know if I need to do a better job explaining. 😁

**Comment by gmcgibbon** [comment]
> Is there another situation in Rails where you would have to specify associations you never intend to use in code?

I can't think of one off the top of my head, but this is a special case considering you're changing the type of something Rails expects to be a number.

> I've created this library (https://github.com/hult/acts_as_having_string_id) for non-incremental string ids in Rails, and it uses attributes heavily.

I would opt to patch ActiveRecord in your gem to give rails specific knowledge on how to handle `StringId`. You can either do this in `ActiveRecord::ConnectionAdapters::Quoting#_type_cast` or `ActiveModel::Type::Value#cast_value`.
