### ISSUE TITLE
belongs_to associations are now validated unless 'optional: true'

### ISSUE THREAD

**Issue by brentkearney** [rails/rails#34454]
After upgrading from Rails 5.0.7 to Rails 5.1.6, my Schedules model failed to validate when an associated belongs_to model is nil. The error is:

```
ActiveRecord::RecordInvalid:
       Validation failed: Lecture must exist
```

The Schedules model had:

```
belongs_to :lecture
validates_associated :lecture, allow_nil: true
```

After the upgrade, its necessary to add the `optional` option:
```
belongs_to :lecture, optional: true
```

Suggested addition to `/guides/source/upgrading_ruby_on_rails.md`:

## Upgrading from Rails 5.0 to Rails 5.1
...
### belongs_to associations are now automatically required: true
All model's `belongs_to` associations are now treated as if the `required: true` option is present. So if the association is optional, that must be declared, or validation will fail without the presence of the associated model record.
```
belongs_to :user, optional: true
```

**Comment by rafaelfranca** [comment]
Are you sure you are not seeing a deprecation message in Rails 5.1? This change was actually in Ruby 5.0.

**Comment by rafaelfranca** [comment]
And it is here in the upgrading guide https://guides.rubyonrails.org/upgrading_ruby_on_rails.html#new-framework-defaults.

**Comment by bbozo** [comment]
Is there a way to keep the old behavior? It's a pain for legacy applications and I don't validate in the model

**Comment by everton** [comment]
> Is there a way to keep the old behavior? It's a pain for legacy applications and I don't validate in the model

From the guides, as linked by @rafaelfranca we can see:

> config.active_record.belongs_to_required_by_default = true

this gets back the original behavior.

**Comment by samssouza** [comment]
Something to note here also is that rails generators will also add null: false to your migration which will also prevent you from leaving association empty.
