### ISSUE TITLE
options_for_select joins with new line

### ISSUE THREAD

**Issue by Abduvakilov** [rails/rails#34462]
I think `options_for_select` or other methods should not generate new lines (`\n`) at least on production environment.
[Effected line](https://github.com/rails/rails/blob/b13a5cb83ea00d6a3d71320fd276ca21049c2544/actionview/lib/action_view/helpers/form_options_helper.rb#L373)

**Comment by rafaelfranca** [comment]
Thank you for the suggestion but we do want to generate with `\n`. If you want to compact you HTML before sending to the client you can do that in other ways.
