### ISSUE TITLE
Delete using association proxy stored in variable doesn't update first

### ISSUE THREAD

**Issue by Dawnthorn** [rails/rails#34460]
### Steps to reproduce

```
# frozen_string_literal: true

require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  gem "activerecord", "5.2.0"
  gem "sqlite3"
end

require "active_record"
require "minitest/autorun"
require "logger"

# This connection will do for database-independent bug reports.
ActiveRecord::Base.establish_connection(adapter: "sqlite3", database: ":memory:")
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :posts, force: true do |t|
  end

  create_table :comments, force: true do |t|
    t.integer :post_id
  end
end

class Post < ActiveRecord::Base
  has_many :comments
end

class Comment < ActiveRecord::Base
  belongs_to :post
end

class BugTest < Minitest::Test
  def test_delete_through_variable
    post = Post.new
    post.save!
    post.comments.create
    post.comments.create
    comments = post.comments
    first_comment = comments.first
    second_comment = comments.second
    comments.delete(comments.first)
    assert_equal second_comment, comments.first
  end

  def test_delete_through_model
    post = Post.new
    post.save!
    post.comments.create
    post.comments.create
    first_comment = post.comments.first
    second_comment = post.comments.second
    post.comments.delete(post.comments.first)
    assert_equal second_comment, post.comments.first
  end

end
```

### Expected behavior
Since I deleted the first comment from comments, I expect `comments.first` to now return what was the second comment. I expect that `assert_equal` at the end to pass.

### Actual behavior
I expect both of the above tests to pass, but `test_delete_through_variable` fails. When you call `comments.first` that second time after the delete, you expect to get the second comment because it is now first in the list.

### System configuration
**Rails version**: 5.2.0, 5.1.6
**Ruby version**: 2.5.0, 2.2.7

It was working in 5.0.6, but it looks like it doesn't work in 5.1.6 or 5.2.0.

**Comment by gmcgibbon** [comment]
You'll notice that when you call `post.comments.first` it will always execute a query whereas assigning comments to a variable via `comments = post.comments` and then calling `comments.first` will only execute a query once. The thing that bugs me, is that it doesn't tell you that the association is actually loaded via `comments.loaded?`. Regardless, I think there's something that could be improved here.
