### ISSUE TITLE
Word to Pdf conversion with active storage

### ISSUE THREAD

**Issue by yanshney** [rails/rails#34461]
Hi guys,

Thank you so much for your work.

This is a very long shot, but does anyone know if it is somehow possible to convert an uploaded doc/docx to pdf format during the active storage file upload? I am trying to display the uploaded user files inline and it is soo much easier to do it with pdf.

Thank you,
Yan

**Comment by gmcgibbon** [comment]
Please direct your questions to StackOverflow where a wider community can help you out. The rails issue tracker is reserved for issues only. Thanks 😄
