### ISSUE TITLE
ActionCable compiled javascript bundle is out of sync with source

### ISSUE THREAD

**Issue by rmacklin** [rails/rails#34473]
### Steps to reproduce

```sh
# ef5478d326d78d1e2b567c23b4a7c16b69dc72b2 is the current head of master
git checkout ef5478d326d78d1e2b567c23b4a7c16b69dc72b2
cd actioncable
yarn build
git status
```

### Expected behavior
There should be no dirty changes in the repository

### Actual behavior
Observe a dirty change with this diff:
```diff
diff --git a/actioncable/app/assets/javascripts/action_cable.js b/actioncable/app/assets/javascripts/action_cable.js
index 07151b9d25..df60b1fc24 100644
--- a/actioncable/app/assets/javascripts/action_cable.js
+++ b/actioncable/app/assets/javascripts/action_cable.js
@@ -238,8 +238,8 @@
       }, this.getPollInterval());
     };
     ConnectionMonitor.prototype.getPollInterval = function getPollInterval() {
-      var _constructor$pollInte = this.constructor.pollInterval, min = _constructor$pollInte.min, max = _constructor$pollInte.max, multiplier = _constructor$pollInte.multiplier;
-      var interval = multiplier * Math.log(this.reconnectAttempts + 1);
+      var _constructor$pollInte = this.constructor.pollInterval, min = _constructor$pollInte.min, max = _constructor$pollInte.max;
+      var interval = 5 * Math.log(this.reconnectAttempts + 1);
       return Math.round(clamp(interval, min, max) * 1e3);
     };
     ConnectionMonitor.prototype.reconnectIfStale = function reconnectIfStale() {
```

### System configuration
**Rails version**: `master`

**Ruby version**: N/A (any supported version)

**Comment by rmacklin** [comment]
This was caused by https://github.com/rails/rails/pull/34446 which only includes the changes to the compiled bundle (corresponding changes to the source files were not committed).

Here's a PR to get the source files back in sync: https://github.com/rails/rails/pull/34475

**Comment by rmacklin** [comment]
It'd be nice to also prevent this from happening again.

For example, we could add a test that fails if `yarn build` generates a dirty git status. That would mean the test assumes you are running it inside a git repository, though. Is that undesirable?

We could also copy the file to a temp location, run `yarn build`, and then compare the generated file to the copy we made. That wouldn't have a dependency on git.

Those are just two ideas. But I feel like maybe this type of thing has come up before. Is there an existing pattern in the codebase for ensuring that an autogenerated file is in sync with the source files from which it was generated?

In any case, I think we should merge #34475 to fix the dirty state.

**Comment by y-yagi** [comment]
I saw the same issue in Active Storage(#33656). 
I agree that it is preferable to be able to check with the test(or Lint?).

@javan What do you think of the suggestion of @rmacklin ?

**Comment by javan** [comment]
Both of the suggestions in https://github.com/rails/rails/issues/34473#issuecomment-439586208 seem reasonable. I don't have a preference.

**Comment by y-yagi** [comment]
@javan Thanks for your check.
@rmacklin Do you interest a create PR?

**Comment by rmacklin** [comment]
> It'd be nice to also prevent this from happening again.

For posterity, this was done in 2c7ec815be4695780f43c2e1245b380808f7ce2e (https://github.com/rails/rails/pull/37485) and 6b6e10d02e4f1baa15f01d9775b08991ede22390 (https://github.com/rails/rails/pull/37508).
