### ISSUE TITLE
ActionController::UrlGenerationError view root_path using wrong route path causing error

### ISSUE THREAD

**Issue by Roko131** [rails/rails#34479]
Problem : 
At routes there are 2 root_path, one regular, other inside `named parameter` scope.
Using `root_path` in root path view causes error because it is using the wrong root_path- the ones inside the `named parameter` scoped even though the current view is not under `named parameter` scoped

### Steps to reproduce

1. Create new rails 5.2.1
2. At `routes.rb` within `scope` with named parameter add `root` to inside block: 
```ruby
# config/routes.rb
Rails.application.routes.draw do
  scope(path: '/form/:foo') do
    root to: 'welcome#root_with_scope'
  end
  root to: 'welcome#root_without_scope'
end
```
3. Add Controller:
```ruby
#app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def root_without_scope
  end

  def root_with_scope
  end
end
```
4. Add view with root_path:
```erb
#app/views/welcome/root_without_scope.html.erb
<h1>Welcome#root_without_scope</h1>
<%= link_to 'root_without_scope', root_path %>
<p>Find me in app/views/welcome/root_without_scope.html.erb</p>
```
5. Visit root path (just '/')

### Expected behavior
visiting root_url ('/') should show `root_without_scope` view displaying the link with root_url path ('/')

### Actual behavior
This line:
`<%= link_to 'root_without_scope', root_path %>` causes 
`ActionController::UrlGenerationError in Welcome#root_without_scope error`
`No route matches {:action=>"root_with_scope", :controller=>"welcome"}, missing required keys: [:foo]`

It tries to find the `foo` paramter even though it's not under the foo scope path.

### System configuration
**Rails version**: `Rails 5.2.1`

**Ruby version**: `ruby 2.5.3p105 (2018-10-18 revision 65156) [x86_64-linux]`

**Comment by Roko131** [comment]
Thanks for replying.

I used 2 root routes, following Rails docs  [example](https://guides.rubyonrails.org/routing.html#using-root)  that says you can use two (or more?) `root` when using namespaces or scopes:

![image](https://user-images.githubusercontent.com/3532929/48738454-beac2f80-ec59-11e8-82b6-62b58aca5f51.png)

When visiting the `/` path. Rails _determined_ it should use the non scoped routes- It should do the same when the root_path is being used within that view.

Since I have **many** routes inside the `scope` - using `namespace` or an `as:` would force me to change all those routes inside entire application- so less suitable for my application.

I would probably just switch the `root` route inside the scoped with a custom route and "just" change that one.

**Comment by gmcgibbon** [comment]
I see what you are saying, but one approach tries to match a path string to any route and the other is looking up a route by name. I would advise using `as:` when calling `root` to give one of your scoped root a different name. Namespaces don't have this problem because they automatically prefix nested routes for you. I'm working on a PR  that warns the developer when they have route conflicts. This should give more visibility when this issue happens.
