### ISSUE TITLE
ActiveStorage: Resize original image

### ISSUE THREAD

**Issue by marcioJesus** [rails/rails#34484]
### Steps to reproduce
Currently with the ```ActiveStorage:Variant``` has the ```image.variant(resize: '100x100').processed``` method that creates a version of the image without modifying the original image. It would be very useful if there was a method to modify the original image.

### System configuration
**Rails version**: 5.2.1

**Ruby version**: 2.5.3

**Comment by albertoalmagro** [comment]
Hi @marcioJesus,

unless I'm missing something (my apologies if I do) I think this isn't an issue with `ActiveStorage:Variant` per se, but a request for a new method. You are more than welcome to post a new feature request at the [Ruby on Rails: Core mailing list](https://groups.google.com/forum/#!forum/rubyonrails-core).

More about [feature requests](https://guides.rubyonrails.org/contributing_to_ruby_on_rails.html#what-about-feature-requests-questionmark).
