### ISSUE TITLE
Update documentation for has_many: :through association

### ISSUE THREAD

**Issue by julianrubisch** [rails/rails#34485]
### Steps to reproduce
The [Rails guides](https://github.com/rails/rails/blob/master/guides/source/association_basics.md) on `has_many: :through` associations mention that 

> The collection of join models can be managed via the has_many association methods. For example, if you assign:
> 
> physician.patients = patients
> Then new join models are automatically created for the newly associated objects. 

However, on Rails 5.x, the join model collection is marked as invalid on `save`.

This is probably because `belongs_to` has the `required` option set to true as default since Rails 5 (?)

Doing

```
class Appointment < ApplicationRecord
  belongs_to :physician, optional: true
  belongs_to :patient, optional: true
end
```

solved the problem for me.

### Expected behavior
Join models are automatically created

### Actual behavior
The join model collection is invalid

### System configuration
**Rails version**: 5.2.0

**Ruby version**: 2.3.7

**Comment by gmcgibbon** [comment]
Please create a test case that reproduces the issue with the [bug report template](https://github.com/rails/rails/blob/master/guides/bug_report_templates/active_record_master.rb). I wasn't able to reproduce it with [this script](https://gist.github.com/gmcgibbon/85d4c40be9fa00f5a3132fd66edf68b0). Try adding `inverse_of` to your `has_many` associations.

**Comment by julianrubisch** [comment]
Interesting. Have to investigate further... something’s weird here. Definitely had an issue in production code. Please bear with me :)
