### ISSUE TITLE
`nil.try(:blank?)` returns nil, but `nil.blank?` returns true

### ISSUE THREAD

**Issue by PandaWhisperer** [rails/rails#34496]
As per title, calling 

```ruby
nil.blank?
```

returns `true`, but calling

```ruby
nil.try(:blank?)
```

returns `nil`. 

This seems rather surprising, given that the whole idea of `#try` is to *attempt* calling a method on the receiver *if possible*.

### Steps to reproduce

Call `#blank?` on `nil`. It returns `true`. Call `nil.try(:blank?)`. It returns `nil`.

```ruby
nil.blank?        # => true
nil.try(:blank?)  # => nil
```

### Expected behavior

Since `#blank?` is a method that exists on `NilClass` (and returns `true`), calling `nil.try(:blank?)` should return also `true`.

```ruby
nil.blank?        # => true
nil.try(:blank?)  # => true
```

### Actual behavior

Calling `#blank? on `nil` returns `true`, but calling `nil.try(:blank?)` returns `nil`.

```ruby
nil.blank?        # => true
nil.try(:blank?)  # => nil
```

### System configuration

**Rails version**: at least 4.x and up (tested on 5.2.1 & 4.2.10)

**Ruby version**: any (tested on Ruby 2.4.1 / Rails 5, Ruby 2.2.10 / Rails 4.2.10)

**Comment by rafaelfranca** [comment]
This is the expected behavior. `try` calls the method only if the receiver is not `nil`. See http://api.rubyonrails.org/classes/NilClass.html#method-i-try.

**Comment by PandaWhisperer** [comment]
Seems to violate Principle of Least Surprise.

**Comment by guilleiguaran** [comment]
Looks like they work exactly like the default Ruby methods:

```
irb(main):002:0> nil&.nil?
=> nil
irb(main):002:0> nil.nil?
=> true
```

**Comment by PandaWhisperer** [comment]
![MFW](https://i.kym-cdn.com/photos/images/original/000/645/713/888.jpg)

**Comment by user512** [comment]
Looks like it is intentional, for the purpose of `try` chain.
https://github.com/rails/rails/blob/0d4b2e4da6532b07d6321eb158a62ef3924917da/activesupport/lib/active_support/core_ext/object/try.rb#L135-L148
