### ISSUE TITLE
mysql migration stuck

### ISSUE THREAD

**Issue by mogya** [rails/rails#34501]
With mysql database, once failed to create index, user cannot migrate/rollback the migration.

### Steps to reproduce

1. create new rails project with mysql database.

```
$ cd rails_dbissue
$ cat << EOS > Gemfile
source "http://rubygems.org"
gem "rails"
EOS
$ bundle install --path vendor/bundle
$ bundle exec rails new . --skip-bundle -d mysql
$ bundle exec rails db:setup
```
2. write a migration

```
class CreateUser < ActiveRecord::Migration[5.2]
  def change
    create_table :users do |t|
      t.integer :user_id
    end
    add_index :xusers, :user_id  # mistake!
    # add_index :users, :user_id  # correct
  end
end
```

3. migrate

```
$ bundle exec rails db:migrate
dynamically loaded 2.9.4
== 20181121142056 CreateUser: migrating =======================================
-- create_table(:users)
   -> 0.0279s
-- add_index(:xusers, :user_id)
rails aborted!
StandardError: An error has occurred, all later migrations canceled:

Mysql2::Error: Table 'rails_dbissue_development.xusers' doesn't exist: CREATE  INDEX `index_xusers_on_user_id`  ON `xusers` (`user_id`)
```

This is OK because the migration contains a mistake. let's fix it.

```
    # add_index :xusers, :user_id  # mistake!
    add_index :users, :user_id  # correct
```

```
$ bundle exec rails db:migrate
== 20181121142056 CreateUser: migrating =======================================
-- create_table(:users)
rails aborted!
StandardError: An error has occurred, all later migrations canceled:

Mysql2::Error: Table 'users' already exists: CREATE TABLE `users` (`id` bigint NOT NULL AUTO_INCREMENT PRIMARY KEY, `user_id` int)
```

Why? Why rails has made the table?  The migration is failed isn't it?

At this time, I can do nothing on rails. I cannot rollback the transaction(because rails thought the migration is rollbacked), I cannot execute the migration again(because the table already exists.)
All I can do is drop the table by mysql.

### Expected behavior

Rails do not create table and index because an error occurred in the migration. That's the transaction.

### Actual behavior

Rails create table and fail the migration. 

### System configuration
**Rails version**:

Rails 5.2.1

**Ruby version**:

ruby 2.4.2p198 (2017-09-14 revision 59899) [x86_64-darwin16]

```
$ mysql --version
mysql  Ver 14.14 Distrib 5.7.22, for osx10.13 (x86_64) using  EditLine wrapper
```

**Comment by mogya** [comment]
Actually I know what's happen(But I cannot find good solution for this...)

MySQL database Do commit before add_index/remove_index command even we're in the transaction.
http://ftp.nchu.edu.tw/MySQL/doc/refman/5.1/en/implicit-commit.html
(just information it doesn't happen if we use PostgreSQL.)

It means, once add_index/remove_index is failed in a migration, the migration is marked as fail, but the commands before add_index/remove_index is executed and commited!

In next time we call db:migrate, rails try to run this migration again because it was marked as failed, but rails cannnot create users table because it's already exist.

**Comment by rafaelfranca** [comment]
This is a limitation of mysql. Rails can't recover from this kind of situation. You need tp force the deletion of the table using `create_table :users, force: true do |t|`.
