### ISSUE TITLE
ActiveStorage downloads via HTTP 1.0 are truncated

### ISSUE THREAD

**Issue by amiuhle** [rails/rails#34500]
### Steps to reproduce

Download a large ActiveStorage file (> 5MB) via HTTP 1.0 (eg `curl -0`). This also happens when using `nginx` as a reverse proxy, which is using HTTP 1.0 [by default](http://nginx.org/en/docs/http/ngx_http_proxy_module.html#proxy_http_version).

### Expected behavior

The file should be downloaded completely.

### Actual behavior

The download is truncated.

### System configuration
**Rails version**: 5.2.1

**Ruby version**: 2.5.1

**Comment by amiuhle** [comment]
The truncated content seems to be in multiples of 5.0 MB: File > 5 MB will be truncated to 5 MB, whereas a file between 10 and 15 MB would be truncated to 10 MB.

Issue on StackOverflow describing the nginx proxy issue (TLDR: `proxy_http_version 1.1;`): https://stackoverflow.com/questions/53374839/rails-5-2-1-activestorage-file-downloads-with-nginx-puma-are-truncated/53410174?noredirect=1#comment93696067_53410174

**Comment by chrisgeek** [comment]
I suggest you try Using proxy_http_version 1.1;

**Comment by amiuhle** [comment]
That's what I'm doing, see my first comment.

I still think it's a bug though, if requested via HTTP 1.0 the response should be non-streaming and have a `Content-Length` header, or it should fail.

**Comment by rafaelfranca** [comment]
Which backend are you using?

**Comment by paracycle** [comment]
@rafaelfranca the linked question on SO is using the `Disk` service. 

Looking at the code I can see that there is a 5MB chunking going on, which looks suspect: https://github.com/rails/rails/blob/master/activestorage/lib/active_storage/service/disk_service.rb#L131

Not sure why it would create a problem like this though, unless the last chunk is not being returned to the client, or something.

**Comment by amiuhle** [comment]
I'm also using the Disk service.

I created an 11MB test file like this: `StringIO.new(%w(a b c d e f g h i j k).map { |s| s * 1.megabyte }.join())` and downloaded it via HTTP 1.0 and 1.1:

```bash
curl --trace-ascii dump_http_10.txt -L -0 "http://localhost:3000/rails/active_storage/blobs/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBDdz09IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--e90a22adcef04f1c682c88e3f6d92200a34a256e/test.txt?disposition=attachment" > /dev/null
```

[dump_http_10.txt](https://github.com/rails/rails/files/2608062/dump_http_10.txt)

```bash
curl --trace-ascii dump_http_11.txt -L "http://localhost:3000/rails/active_storage/blobs/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBDdz09IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--e90a22adcef04f1c682c88e3f6d92200a34a256e/test.txt?disposition=attachment" > /dev/null
```

[dump_http_11.txt](https://github.com/rails/rails/files/2608063/dump_http_11.txt)

The HTTP 1.1 trace is complete, but when using HTTP 1.0, the client just closes the connection after the first chunk.

When debugging `ActiveStorage::DiskController#show`, I noticed that the server will continue sending the remaining chunks even though curl has closed the connection and exited.

**Comment by y-yagi** [comment]
This can reproduce with 5.2, but not with the master.  
It seems that it was fixed by the influence of 390097531bd17369f05a23eba58c37b850ac95dd. But it is not backported to 5-2-stable.    

@georgeclaghorn Are there any concerns about backporting 390097531bd17369f05a23eba58c37b850ac95dd to 5-2-stable? If not, I will backport it.

**Comment by georgeclaghorn** [comment]
Good catch, @y-yagi. Backporting that change is okay with me.

**Comment by y-yagi** [comment]
@georgeclaghorn Thank you for confirmation! I backported to 5-2-stable 62bb663174e6a16775d619fbe17073408c116113.

@amiuhle This will be fixed in the next version. Thanks for your report!
