### ISSUE TITLE
Result from query differs between MySQL and SQLite3

### ISSUE THREAD

**Issue by eileencodes** [rails/rails#34506]
When running `exec_query` with `INSERT` (or other write commands), MySQL returns `nil`. When run with SQLite3 (and also PostgreSQL) an `ActiveRecord::Result` is returned with an empty row set.

### Steps to reproduce

MySQL script (passes):

```ruby
require "active_record"
require "minitest/autorun"
require "logger"

ActiveRecord::Base.establish_connection({ "adapter" => "mysql2", "username" => "rails", "database" => "activerecord_unittest" })
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :posts, force: true do |t| 
    t.string :name
  end 
end

class Post < ActiveRecord::Base
  has_many :comments
end

class BugTest < Minitest::Test
  def test_association_stuff
    assert_nil ActiveRecord::Base.connection.exec_query("INSERT INTO `posts` (`name`) VALUES ('post title')")
  end 
end
```

Sqlite3 Script (fails):

```ruby
require "active_record"
require "minitest/autorun"
require "logger"

# This connection will do for database-independent bug reports.
ActiveRecord::Base.establish_connection(adapter: "sqlite3", database: ":memory:")
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :posts, force: true do |t| 
    t.string :name
  end 
end

class Post < ActiveRecord::Base
  has_many :comments
end

class BugTest < Minitest::Test
  def test_association_stuff
    assert_nil ActiveRecord::Base.connection.exec_query("INSERT INTO posts (name) VALUES ('post title')")
  end 
end
```

### Expected behavior

I think all the dbs should return nil or an empty set, but not differ between dbs. 

### Actual behavior

MySQL behaves differently from SQLite3 and PostgreSQL

### System configuration
**Rails version**: master

**Ruby version**: 2.5

cc/ @rafaelfranca @tenderlove @matthewd

**Comment by tenderlove** [comment]
I think we should always be returning an empty result object.

**Comment by matthewd** [comment]
Designed from scratch I think I'd prefer an exception if you call a give-me-these-rows method with a non-row-returning query, but that seems an unreasonable change at this point.

Along the same lines I'd slightly lean toward nil as the more representative result here, but I suspect one or more of the currently-Result-returning adapters would struggle to distinguish such a non-result from a regular no-rows result, so empty Result seems fine. :+1:

**Comment by azbshiri** [comment]
I'm having problem with MySQL, more details will be added in a couple of hours/tomorrow. You guys think I can take this over?

**Comment by azbshiri** [comment]
https://github.com/rails/rails/pull/34521 - updated
