### ISSUE TITLE
How to know the duration ，runs，Assertions ，Failures of every test case？

### ISSUE THREAD

**Issue by BUCTwangkun** [rails/rails#34529]
This is my first time to learn about rails. But I'm interested in the data in the Travis CI. In the job log, I the many test cases and just the total runs,failures of the test cases. So could you tell me how to get the failures, runs ..... of every tase case? It`s important to me, thank you ~

**Comment by rafaelfranca** [comment]
Please use the mailing list or StackOverflow for questions/help, where a wider community will be able to help you. We reserve the issues tracker for issues only.
