### ISSUE TITLE
ActiveModel::Dirty and JSONB column with an array value

### ISSUE THREAD

**Issue by gabrieltal** [rails/rails#34537]
The issue is that when using ActiveModel::Dirty with a JSONB column that contains a key with an array value the methods `.changes` and .
### Steps to reproduce
  * Have a model with a JSONB column. (For our purposes let's call this `Profile` model with a `profile_details` JSONB column in its table)
  * Create a store_accessor for it with one key you want to use. (For this case let us say we have in our store_accessor `names` which is an array of names. 
  * Put ActiveModel::Dirty on the Profile model and then in a form include our array column.
  * When not doing any updates on our newly created names array no matter how much we format this array to match what it was previously ActiveModel::Dirty will think there have been changes made.

### Expected behavior
ActiveModel::Dirty should realize that this array inside the JSONB column did not get updated

### Actual behavior
ActiveModel::Dirty thinks there have been changes even after I have formatted the data to look exactly like it was previously which was an empty array. I can do this when inputting a phone_number in a form with dashes and then when in the controller update action I am able to see that it is correctly marking it as having been changed. When I format the phone_number to remove the dashes it recognizes that it has not been changed. This doesn't happen for the array in the JSONB column, however.

### System configuration
**Rails version**: 5.2.1

**Ruby version**: 2.5.1

**Comment by kamipo** [comment]
Can you provide a reproducible script with this template https://github.com/rails/rails/blob/master/guides/bug_report_templates/active_record_master.rb?

**Comment by gabrieltal** [comment]
How is this? Sorry if it isn't right. This is my first time doing something like this. https://gist.github.com/gabrieltal/b036de7b201ea07060c4c504be85263a

**Comment by gmcgibbon** [comment]
This happens for `json`, `jsonb`, `hstore`, and `serialized` attribute types. The change is forced through the attributes API via https://github.com/rails/rails/blob/06ab7b27ea1c1ab357085439abacdb464f6742bf/activerecord/lib/active_record/store.rb#L181 when you write to the accessor so I think this is intentional. Maybe it is because we don't want to diff hashes for performance reasons?

**Comment by gabrieltal** [comment]
Ah that makes sense why that would happen for performance reasons. I figured there was something that was setting it as changed no matter what I just didn't know where to look. Thanks for that. It was bothering me not knowing why it was happening. I'm ok with closing this issue since I don't think there is anything to fix this?

**Comment by gmcgibbon** [comment]
@gabrieltal Correct, thanks for understanding 😄
