### ISSUE TITLE
Ruby 2.6.0 revision 65989 deprecates Object#=~

### ISSUE THREAD

**Issue by yahonda** [rails/rails#34530]
### Steps to reproduce

* Install Ruby 2.6.0 trunk including [revision 65989](https://svn.ruby-lang.org/cgi-bin/viewvc.cgi?revision=65989&view=revision)

```ruby
$ cd activerecord
$ bundle exec ruby -w -Itest test/cases/validations_test.rb -n test_numericality_validation_checks_against_raw_value
```

### Expected behavior
It should pass without warnings.

### Actual behavior
It passes with warnings.

```
$ bundle exec ruby -w -Itest test/cases/validations_test.rb -n test_numericality_validation_checks_against_raw_value
Using sqlite3
Run options: -n test_numericality_validation_checks_against_raw_value --seed 23960

# Running:

/home/yahonda/git/rails/activemodel/lib/active_model/validations/numericality.rb:89: warning: Object#=~ is deprecated; it always returns nil
/home/yahonda/git/rails/activemodel/lib/active_model/validations/numericality.rb:89: warning: Object#=~ is deprecated; it always returns nil
.

Finished in 0.098373s, 10.1654 runs/s, 30.4963 assertions/s.
1 runs, 3 assertions, 0 failures, 0 errors, 0 skips
$
```

### System configuration
**Rails version**: master branch

**Ruby version**: ruby 2.6.0dev (2018-11-26 trunk 65993) [x86_64-linux]

**Comment by rafaelfranca** [comment]
I don't think it is a good idea do deprecate that method. We should comment on the ruby issue.

**Comment by jeremy** [comment]
Nice fix ❤️

**Comment by yahonda** [comment]
@rafaelfranca Thanks for the fix. I do not have a strong feeling if this method should be deprecated or not, mind opening an issue to https://bugs.ruby-lang.org ?
