### ISSUE TITLE
Scopes which don't return relationships

### ISSUE THREAD

**Issue by Ana06** [rails/rails#34532]
From https://guides.rubyonrails.org/active_record_querying.html#scopes:

> All scope methods will return an `ActiveRecord::Relation` object which will allow for further methods (such as other scopes) to be called on it.

But an scope could return something different from an ` ActiveRecord::Relation` object. I can for example do this:

`scope :empty, -> { [] }`

I think the documentation should be updated. Another option would be to raise an exception if the object type is different from `ActiveRecord::Relation`. I think enforicing scopes to only return `ActiveRecord::Relation`s is a good idea, but maybe to destructive in case someone is using this already. At least it would need to be a deprecation first. :thinking:

**Comment by rafaelfranca** [comment]
Yeah, the documentation should be change to `All scope bodies must return an ActiveRecord::Relation or nil`.

While I think we should enforce that by code I don't think the performance overhead of that check is worth. If people is returning non relations on their scope block is on their own risk.

**Comment by Ana06** [comment]
@rafaelfranca 

> While I think we should enforce that by code I don't think the performance overhead of that check is worth. If people is returning non relations on their scope block is on their own risk.

It sound reasonable :+1: and it seems there was already a PR for that: https://github.com/rails/rails/pull/32846

@gmcgibbon thanks for updating the documentation, it is much clearer now :wink:
