### ISSUE TITLE
Abstract polymorphic association accesses inexistent database table

### ISSUE THREAD

**Issue by MrSerth** [rails/rails#34531]
When using an abstract class with a `has_many` association, ActiveRecord tries to access the inexistent table and fails.

#### Example
I have users of different types, say `InternalUser` and `ExternalUser`. Both inherit from the abstract `User` class. Now, I want them to be part of (one or many) `Group`(s). However, I can't define a `Group` and access the (empty) list of users.

##### Test Case:
 - Run [this test case](https://gist.github.com/MrSerth/60ea2b78ba6c4ad27cabf9ecb8a2b310)

##### Rails App:

1. Clone [this repo](https://github.com/MrSerth/has_many_abstract_polymorphic)
2. Prepare dependencies (requires PostgreSQL): `bundle install && rake db:setup`
3. Run web server: `rails s -b 0.0.0.0`
4. Access `http://localhost:3000` (which will execute `ApplicationController#test`

### Expected behavior
```
group = Group.new
=> #<Group id: nil, name: nil, external_id: nil, created_at: nil, updated_at: nil>
group.users.count
=> 0
```

### Actual behavior

```
group = Group.new
=> #<Group id: nil, name: nil, external_id: nil, created_at: nil, updated_at: nil>
group.users.count
=> NoMethodError: undefined method `key?' for nil:NilClass
```

### System configuration
**Rails version**: `Rails 5.2.1`
**Ruby version**: `ruby 2.5.1p57 (2018-03-29 revision 63029) [x86_64-darwin17]`

**Comment by gmcgibbon** [comment]
In your `Group` model you have `has_many :users, through: :group_memberships, source_type: 'InternalUser'`. I don't think you can use an abstract class as a `source_type` for your association because the table you want to query is ambiguous. Having an association for `internal_users` via `has_many :internal_users, through: :group_memberships, source_type: 'InternalUser'` and `external_users` via `has_many :external_users, through: :group_memberships, source_type: 'ExternalUser'` is the right approach.

**Comment by gmcgibbon** [comment]
To further clarify the behaviour you see, you don't have `self.abstract_class = true` on your `User` model, so ActiveRecord assumes that `InternalUser` and `ExternalUser` are STI classes that are present on the `users` table. I think maybe we can resolve this by raising if the class is abstract. This might not be possible though because of autoload. I'll investigate.

**Comment by MrSerth** [comment]
Oh, I forgot adding `self.abstract_class = true` to the test case, it is present in the example app and my own code. After adding it to the test case, the error message slightly changed (reflected in the issue) but it still doesn't work as expected.

I also thought about adding two associations (one for `InternalUser` and another one for `ExternalUsers`) but is there a way to uniformly access both of them in a list? In most cases, I don't care which `User` type I have when dealing with it in my code. Therefore, I would like to reduce specific code tailored to the differentiation.

**Comment by gmcgibbon** [comment]
> is there a way to uniformly access both of them in a list?

A queryable collection/association? No, not that I'm aware of. You can create a method on your model and concat the two collection proxies into an array, but that's an inefficient hack.

> In most cases, I don't care which User type I have when dealing with it in my code.

It sounds to me like you want to be using STI and not polymorphism then. That way you can get multiple user types in one queryable association.

**Comment by MrSerth** [comment]
Thanks for your suggestion to use STI instead of polymorphism. Of course, I could use STI, but it would be complicated because of many different attributes both classes use. I feel more comfortable dealing with those using polymorphism.

In addition, I found out that only the access to some methods is broken (such as `group.users`) but others work fine (e.g. `user.groups`) and (most importantly) the data is always consistent. While not tailored to production usage so far, it shows that some support for that data structure is present in ActiveRecord so far. I am still hoping for full polymorphism support 😉

**Comment by MrSerth** [comment]
Hey @gmcgibbon,
is there anything I might help with regarding the reproducibility of this issue? Or do you have some other news?
Looking forward to find a solution using polymorphism.

**Comment by MrSerth** [comment]
The issue still persists in the newest release of Rails (version `5.2.3`). I updated the test script and test app to match the newest version. 

However, ActiveRecord still tries to access an invalid database. The error message I get from the test case is:

```
ActiveRecord::StatementInvalid: Could not find table ''
```
