### ISSUE TITLE
`autoload_paths#+=` breaks existing paths implicitly

### ISSUE THREAD

**Issue by takumiabe** [rails/rails#34547]
I'm newbie here. :)

I think it is better that `autoload_paths`' methods display warnings it is deprecated.
I didn't check `eagerload: true` case. I'm sorry.

Thanks

### Steps to reproduce

```
rails new project
cd project
mdkir lib/somepath
mdkir lib/somepath2
```

### case A

edit config/application.rb
```
+    config.paths.add Rails.root.join('lib/somepath').to_s, autoload: true
+    config.autoload_paths += [Rails.root.join('lib/somepath2').to_s]
```

### case B (reverse order)

edit config/application.rb
```
+    config.autoload_paths += [Rails.root.join('lib/somepath2').to_s]
+    config.paths.add Rails.root.join('lib/somepath').to_s, autoload: true
```

### Expected behavior

```
bin/rails r 'puts $LOAD_PATH' | grep lib/somepath
```

command shows in case A
```
xxxxx/project/lib/somepath
xxxxx/project/lib/somepath2
```
and 
in case B
```
xxxxx/project/lib/somepath2
xxxxx/project/lib/somepath
```

### Actual behavior

command shows in case A
```
xxxxx/project/lib/somepath
xxxxx/project/lib/somepath2
```
and 
in case B
```
xxxxx/project/lib/somepath2
```

### System configuration
**Rails version**:

```
$ rails -v
5.2.1.1
```

**Ruby version**:
2.5.3

**Comment by rafaelfranca** [comment]
It is not deprecated, and this probably also happen with `eager_load_paths`. This happen because `config.autoload_paths` is memoized so the first time you call it you freeze its value and it is not going to check `config.paths` anymore. This is an unfortunate gotcha of the implementation but fixing it would cause breaking changes. I'd prefer to document this gotcha given it is not so common to do what you are doing.

**Comment by takumiabe** [comment]
@rafaelfranca 
Thank you for comment. 👍 
I understand what's happened.

> I'd prefer to document this gotcha given it is not so common to do what you are doing.

I see. 👍 

Yes, it is not common case. 🙇 
My project has many submodule which accesses to config.paths to load its module.
(These submodules written by each different coder.)

I will show them to use `paths.add` only.

Thank you! 👍
