### ISSUE TITLE
App generator drops the -preview version of Ruby while declaring ruby version in Gemfile

### ISSUE THREAD

**Issue by udaykadaboina** [rails/rails#34549]
### Steps to reproduce
1. Create a new rails app
$ rails new blog
2. Go inside the project
$ cd blog/
Required ruby-2.6.0 is not installed.
To install do: 'rvm install "ruby-2.6.0"'

If the system has preview version of ruby, the app generator is setting ruby version in Gemfile without -preview tag which gives the prompt to install 2.6.0 version when the 2.6.0 version is not available yet.

### Expected behavior
I would expect to keep ruby-2.6.0-preview2 in Gemfile but when someone cd's into the project have the prompt say:

_Using ruby-2.6.0-preview2. Install stable version of Ruby...
To install do: 'rvm install "ruby-2.6.0"'_

### Actual behavior
```
$ rails c
Running via Spring preloader in process 2177
Loading development environment (Rails 5.2.1.1)
2.6.0-preview2 :001 > RUBY_VERSION
 => "2.6.0" 
```

I looked at the [PluginBuilder.gemfile](https://github.com/rails/rails/blob/ac721c855203ac7570545c0e85fe086f8e94d94a/railties/lib/rails/generators/rails/plugin/plugin_generator.rb#L44) method, which uses Gemfile template to create the Gemfile and inside the Gemfile.tt and it has RUBY_VERSION 

To see what the actual value is in IRB, I looked at the RUBY_VERSION in irb, and it gives the right output:

```
$ irb
2.6.0-preview2 :001 > ENV['RUBY_VERSION']
 => "ruby-2.6.0-preview2" 
```

Not sure if ignoring -preview in RUBY_VERSION in Rails is intentional

### System configuration
**Rails version**:
$ rails -v
Rails 5.2.1.1

**Ruby version**:
$ ruby -v
ruby 2.6.0preview2 (2018-05-31 trunk 63539) [x86_64-darwin18]

**Comment by rafaelfranca** [comment]
The `RUBY_VERSION` you are looking is set by rvm. Ruby doesn't give us information about preview releases so we can't automatic generate that.

```
$ irb
>> RUBY_VERSION
=> "2.6.0"
```

Even if we generate the Gemfile with `ruby '2.6.0-preview3'` bundler will not work since that is not a valid `RUBY_VERSION` and it uses it to check, in fact bundler expects 2.6.0 as version. See:

```
[2.6.0-preview3 rails (5-2-stable *)]$ bundle install
Your Ruby version is 2.6.0, but your Gemfile specified 2.6.0.pre.preview3
[2.6.0-preview3 rails (5-2-stable *)]$ head Gemfile
# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby '2.6.0-preview3'

gemspec
```

That being said this is an issue with rvm.
