### ISSUE TITLE
RailsUJS: Right click triggers remote click event on Firefox developer edition

### ISSUE THREAD

**Issue by thomas07vt** [rails/rails#34541]
### Steps to reproduce
Sample Repo showing the issue:
https://github.com/thomas07vt/ujsbug

0. Clone https://github.com/thomas07vt/ujsbug repo
1. Start rails app
2. Navigate to the root page using Firefox Version 64.0b12 (64-bit)
3. Open up the developer tools to the Network tab
4. Right click on the "Remote" link
5. See that the right click actually fired off a remote network request

When I use Chromium, a right click does not trigger remote events.
This only occurs on `remote: true` links

### Expected behavior
No network request should be made

### Actual behavior
A network request is made

### System configuration
**Rails version**: Rails 5.2.1

**Ruby version**: ruby 2.5.1p57 (2018-03-29 revision 63029) [x86_64-linux]

**Comment by aar0nr** [comment]
This happens with regular Firefox* as well.

_* Tested v63.0.3 (64-bit)_

**Comment by thomas07vt** [comment]
I tested on my sample repo and verified that https://github.com/rails/rails/pull/34573 fixes this. Should I close this issue or do you want to wait for some reason?

**Comment by javan** [comment]
Great! Closed via https://github.com/rails/rails/pull/34573 it is.
