### ISSUE TITLE
Space character in custom table name is mis-interpreted as dot and thus breaks ActiveRecord

### ISSUE THREAD

**Issue by LemonAndroid** [rails/rails#34540]
### Steps to reproduce
![image](https://user-images.githubusercontent.com/3209250/49097725-a77acc80-f26d-11e8-89b0-a57723e451a1.png)

### System configuration
**Rails version**:
5.1.6

**Ruby version**:
2.6.0preview3

**Comment by gmcgibbon** [comment]
I don't think we support this use-case: https://edgeguides.rubyonrails.org/active_record_basics.html#naming-conventions

> When using class names composed of two or more words, the model class name should follow the Ruby conventions, using the CamelCase form, while the table name must contain the words separated by underscores

**Comment by LemonAndroid** [comment]
So, people who write applications for legacy databases are expected to change every malformed (in rails ideology) table name before using Rails with it?

**Comment by LemonAndroid** [comment]
@gmcgibbon These are the naming conventions for when not using the custom `table_name` though.

**Comment by gmcgibbon** [comment]
My mistake. This appears to only happen with the postgres adapter, SQLite and MySQL both support spaces in table names. I'll PR a fix once I've found and fixed the issue!
