### ISSUE TITLE
Rails 5.2.1.1 breaks ActiveStorage with Amazon

### ISSUE THREAD

**Issue by gssbzn** [rails/rails#34558]
### Steps to reproduce
After upgrading to 5.2.1.1 I'm getting on three different applications `ArgumentError: unknown keyword: content_type`

Example model:
```ruby
class Post < ApplicationRecord
  has_one_attached :file
end
```

Example controller
```ruby
def create
    @post = Post.new(post_params) 
    @post.save
end
```
### Expected behavior
Successfully save the record and upload the associated file to Amazon S3

### Actual behavior
Save is raising `ArgumentError: unknown keyword: content_type`

### System configuration
**Rails version**: 5.2.1.1

**Ruby version**: ruby 2.5.3p105

**Comment by stevenharman** [comment]
Hi @gssbzn.

This might be a dup of #34550 and #34551.

**Comment by eileencodes** [comment]
Closing as duplicate

**Comment by gssbzn** [comment]
@stevenharman indeed
