### ISSUE TITLE
How can I get url of image variant in model? Active Storage

### ISSUE THREAD

**Issue by ViTVetal** [rails/rails#34571]
I want get url of image variant in my Model. I used Rails app as API for Android app and want send url of resized image to client. I created method in Model for this purpose.

### Expected behavior
I want get url of image variant in my model. 

### Actual behavior
I can get url in model with this code (Active Storage)

    Rails.application.routes.url_helpers.rails_blob_path(picture_of_car, only_path: true)

But I need get url of resized varian

    picture_of_car.variant(resize: "300x300").processed

For example this code

    Rails.application.routes.url_helpers.rails_blob_path(picture_of_car.variant(resize: "300x300").processed, only_path: true)

throw

    NoMethodError (undefined method `signed_id' for #<ActiveStorage::Variant:0x0000000004ea6498>):

### System configuration
**Rails version**: 5.2.1

**Ruby version**: 2.5.0p0

**Comment by rafaelfranca** [comment]
Please use the mailing list or StackOverflow for questions/help, where a wider community will be able to help you. We reserve the issues tracker for issues only.

**Comment by mri-dula** [comment]
@ViTVetal Did you find a solution for this? I am facing the same problem.

**Comment by ViTVetal** [comment]
@mri-dula Hello! Yes https://stackoverflow.com/a/53547638/3194048
