### ISSUE TITLE
Can't set non-PK field called "ID" if another field is set as the primary key

### ISSUE THREAD

**Issue by matt17r** [rails/rails#34574]
### Steps to reproduce
```
# frozen_string_literal: true

require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  # Activate the gem you are reporting the issue against.
  gem "activerecord", "5.2.0"
  gem "sqlite3"
end

require "active_record"
require "minitest/autorun"
require "logger"

# This connection will do for database-independent bug reports.
ActiveRecord::Base.establish_connection(adapter: "sqlite3", database: ":memory:")
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :posts, force: true, id: false do |t|
    t.integer :legacy_pk # lives in external MSSQL DB, auto-incrementing "ID" column
    t.integer :id # from legacy database, identifies a related person not this post
  end
end

class Post < ActiveRecord::Base
  self.primary_key = 'legacy_pk' # this is the primary key, not `id` :(
end

class BugTest < Minitest::Test
  def test_legacy_pk_column_when_non_pk_id_column_present
    post = Post.create(legacy_pk: 123, id: 234)

    assert_equal 123, post.legacy_pk
  end

  def test_setting_non_pk_id_column_via_initialiser
    no_pk_post = Post.new(id: 345)

    assert_nil no_pk_post.legacy_pk
  end

  def test_setting_non_pk_id_column_via_accessor
    empty_post = Post.new

    empty_post.id = 456

    assert 456 != empty_post.legacy_pk
  end

  def test_setting_non_pk_id_column_via_square_brackets
    empty_post_2 = Post.new

    empty_post_2[:id] = 567

    assert 567 != empty_post_2.legacy_pk
  end
end
```

### Expected behavior
Should be able to read and write the `id` attribute in legacy databases when it's not the primary key

### Actual behavior
All attempts to read and write `id` are redirected to whatever the primary key is. See for example `write_attribute(attr_name, value)` defined in `activerecord/lib/active_record/attribute_methods/write.rb`

### System configuration
**Rails version**: 5.1.6, 5.2.1.1

**Ruby version**: 2.5.3p105 (2018-10-18 revision 65156) [x86_64-darwin18]

**Comment by matt17r** [comment]
Upon further digging I can see that `id`, `id=` and `id?` are all defined in `ActiveRecord::AttributeMethods::PrimaryKey`. In other words, it seems this is a feature (deliberate design decision) not a bug.

So now I just need to find some way to get or set the ID column in a third party database without going through those methods 🤔

**Comment by gmcgibbon** [comment]
You are correct, this is a feature. See https://github.com/rails/rails/issues/34402. I'll see if I can add docs or an exception to clarify this behaviour.
