### ISSUE TITLE
Protect enum from overriding key predicate methods (a.k.a overriding `nil?` is bad)

### ISSUE THREAD

**Issue by aselder** [rails/rails#34580]
### Steps to reproduce
[4] pry(main)> class User < ApplicationRecord
[4] pry(main)*   enum task_type: [:nil, :blank, :present, :empty]
[4] pry(main)* end
=> {:task_type=>[:nil, :blank, :present, :empty]}

### Expected behavior
I would expect this to raise an error, as overriding `nil?`, `blank?`, `present?`, `empty?` seems like a dangerous thing that could cause weird, hard to track down bugs.

### Actual behavior
I would expect declaration like this to raise an error similar to what happens if you try to use the value `save`

### System configuration
**Rails version**:
5.2.1.1

**Ruby version**:
2.4.5, 2.5.3

**Comment by rafaelfranca** [comment]
Since none of those methods are part of the active record API I don't think enum should care about them. There is no difference between using enum and defining those methods yourself in instance so I don't think we should special case those methods.

**Comment by aselder** [comment]
@rafaelfranca I get where you're coming from. Perhaps a warning instead of a hard error. This bug got filed as a result of a real life situation where someone who didn't fully appreciate all the methods that `enum` creates. He created an value `blank` and didn't realize he'd overridden `blank?`. You can imagine the weird behavior that accidentally got triggered.
