### ISSUE TITLE
Routes respond differently to symbols and strings within resources

### ISSUE THREAD

**Issue by ardavis** [rails/rails#34608]
Defining a route with a symbol has a different response than with a string. This only seems to apply to the 7 actions that resources would create, and when they are on a **collection**.

### Steps to reproduce
Add the 7 actions as strings and the 7 actions as symbols. Use `only: []` for simplicity.

    resources :products, only: [] do
      collection do
        get 'index' 
        get 'show'
        get 'new'
        get 'create'
        get 'edit'
        get 'update'
        get 'destroy'
      end
    end

    resources :toys, only: [] do
      collection do
        get :index 
        get :show
        get :new
        get :create
        get :edit
        get :update
        get :destroy
      end
    end

Run `rails routes` and you can see that the ones with symbols generated incorrectly. They go to the correct controller/action, but the route itself is missing the term.

### Expected behavior
**Even though it is poor naming**, I would have expected to see the routes for symbols and strings to both function the same.

```
       Prefix Verb URI Pattern                 Controller#Action
     products GET  /products/index(.:format)   products#index
              GET  /products/show(.:format)    products#show
              GET  /products/new(.:format)     products#new
              GET  /products/create(.:format)  products#create
edit_products GET  /products/edit(.:format)    products#edit
              GET  /products/update(.:format)  products#update
              GET  /products/destroy(.:format) products#destroy
         toys GET  /toys/index(.:format)       toys#index
              GET  /toys/show(.:format)        toys#show
              GET  /toys/new(.:format)         toys#new
              GET  /toys/create(.:format)      toys#create
    edit_toys GET  /toys/edit(.:format)        toys#edit
              GET  /toys/update(.:format)      toys#update
              GET  /toys/destroy(.:format)     toys#destroy
```

### Actual behavior
The routes that are generated when running `rails routes` are incorrect.

```
       Prefix Verb URI Pattern                 Controller#Action
     products GET  /products/index(.:format)   products#index
              GET  /products/show(.:format)    products#show
              GET  /products/new(.:format)     products#new
              GET  /products/create(.:format)  products#create
edit_products GET  /products/edit(.:format)    products#edit
              GET  /products/update(.:format)  products#update
              GET  /products/destroy(.:format) products#destroy
         toys GET  /toys(.:format)             toys#index
              GET  /toys(.:format)             toys#show
              GET  /toys(.:format)             toys#new
              GET  /toys(.:format)             toys#create
    edit_toys GET  /toys/edit(.:format)        toys#edit
              GET  /toys(.:format)             toys#update
              GET  /toys(.:format)             toys#destroy
```

### System configuration
**Rails version**:
Rails 5.2.1
**Ruby version**:
ruby 2.5.3p105 (2018-10-18 revision 65156) [x86_64-darwin17]

**Comment by gmcgibbon** [comment]
I believe based on [this section of the routing code](https://github.com/rails/rails/blob/609c58bfa6df58b88e3eadebb1f1d49354541d24/actionpack/lib/action_dispatch/routing/mapper.rb#L1871-L1883) we expect symbols to be controller actions and strings to be paths. The router makes assumptions from there depending on what you pass.

You can fix this in your example by specifying a `path:` for your symbol routes, or just using strings for both resources. Maybe we can clarify this in the documentation somewhere because I don't see this mentioned.

**Comment by ardavis** [comment]
Thank you for the quick response and documentation, @gmcgibbon.
