### ISSUE TITLE
CalculationsTest#test_should_return_nil_as_average fails with Ruby 2.6.0

### ISSUE THREAD

**Issue by yahonda** [rails/rails#34600]
One of Active Record unit test have been failing with ruby-head at Travis CI.
I have not found which Ruby 2.6 change introduces this failure yet, let me report it first.

* The first failed one: https://travis-ci.org/rails/rails/builds/462532899
```
ruby 2.6.0dev (2018-12-02 trunk 66129) [x86_64-linux]
```

* The last successful one: https://travis-ci.org/rails/rails/builds/462285019
```
ruby 2.6.0dev (2018-12-01 trunk 66113) [x86_64-linux]
```

### Steps to reproduce
```ruby
$ cd activerecord
$ bundle exec ruby -w -Itest test/cases/calculations_test.rb -n test_should_return_nil_as_average
```

### Expected behavior
It should pass.

### Actual behavior
```ruby
$ bundle exec ruby -w -Itest test/cases/calculations_test.rb -n test_should_return_nil_as_average
Using sqlite3
Run options: -n test_should_return_nil_as_average --seed 60743

# Running:

F

Failure:
CalculationsTest#test_should_return_nil_as_average [test/cases/calculations_test.rb:61]:
Expected 0.0 to be nil.


rails test test/cases/calculations_test.rb:60



Finished in 0.047892s, 20.8803 runs/s, 20.8803 assertions/s.
1 runs, 1 assertions, 1 failures, 0 errors, 0 skips
$
```

### System configuration
**Rails version**:master branch

**Ruby version**:ruby 2.6.0dev (2018-12-03 trunk 66147) [x86_64-linux]

**Comment by evexoio** [comment]
PS: My PR is definitely not the way to solve this issue.

I just wanted to assign my self to this issue if that works 🙈

I'm doing git bisect on ruby commits to get to the commit that introduced the change that's causing this issue :)

**Comment by evexoio** [comment]
@yahona it should be this commit that caused this error.

https://github.com/ruby/ruby/commit/a0e438cd3c28d2eaf4efa18243d5b6edafa14d88#diff-6b866d482baf2bdfd8433893fb1f6d36R144

**Comment by yahonda** [comment]
Thanks for the fix.
