### ISSUE TITLE
Unexpected behavior when using multiple conditional layouts

### ISSUE THREAD

**Issue by phillipspc** [rails/rails#34614]
Here's an example controller:
```ruby
class PagesController < ApplicationController
  layout "layout_one", only: :one
  layout "layout_two", only: :two

  def one
  end

  def two
  end
end
```
### Expected behavior
Given that `layout` and `before_action` both use the same conditional syntax, I think its reasonable to expect the similar behavior from the two, ie. "layout_one" is used by the "one" action, and "layout_two" is used by "two".

### Steps to reproduce
minimal rails project: https://github.com/phillipspc/layout_test

### Actual behavior
`pages#one` will use the default "application" layout, and `pages#two` will use "layout_two".

I'm aware that I could achieve what I want using a `Proc`, but I think ideally you could declare multiple conditional layouts in your controller and have it work as expected.

**Comment by alfie-max** [comment]
This looks interesting.. 
I'd like to take a try at this

**Comment by alfie-max** [comment]
As per current implementation, it looks like only the last set conditional layout is set, this is because it's set for the entire controller whatever the condition is.

So when you have more than one layout method calls in a controller the second one overrides the first one.

https://github.com/rails/rails/blob/master/actionview/lib/action_view/layouts.rb#L271

**Comment by phillipspc** [comment]
@alfie-max Yeah thats more or less what I figured and was hesitant to call this a "bug". Still feel it would be nice to change this behavior. I was even considering looking into addressing it myself but wanted to open the issue first just in case I was missing something.

**Comment by alfie-max** [comment]
yea... doesn't feel like a bug to me either.. It's just how it's designed.

**Comment by gmcgibbon** [comment]
Agree that its not a bug, but feel free to open a PR to adjust its behaviour.

**Comment by evexoio** [comment]
@gmcgibbon I gave this a go, couldn't get anything right.

Can you point our which hashes I should merge?

**Comment by phillipspc** [comment]
@evexoio @gmcgibbon I also gave this a look and I dont think this would be a small change.

The current implementation essentially has each controller set a single layout (which is essentially why the second line in my example controller overrides the first). So in the case of supplying a layout with a conditional, the logic to determine the layout for a particular action becomes as simple as: 
"action listed in `only` or not listed in `except` ? use the supplied layout : use default layout"

Getting to the point where multiple layouts with conditionals could be used essentially means moving away from this "single layout per controller" approach, and I'm guessing a pretty big change to the overall layout code.

**Comment by gmcgibbon** [comment]
Right, I was thinking of `_layout_conditions.merge!(conditions) { |_, new, old| new + old }`, but that only solves half of the problem. You would have to couple `_layout` and `_layout_conditions` somehow, I think.
