### ISSUE TITLE
Question: any ways to type cast value of enum column in a joined table?

### ISSUE THREAD

**Issue by SzNagyMisu** [rails/rails#34611]
Hi there, I was just wondering if there was a way to type cast an `enum` column's value manually.
Say, I have the following models:

```ruby
class Conversation < ApplicationRecord
  enum status: [ :active, :archived ]
  belongs_to :person
end

class Person < ApplicationRecord
  has_many :conversations
end
```

When I run the following query, I get the values of `conversation_status` un-typecasted, because the returned records are instances of the `Person` model but the `enum` is defined on `Conversation`:

```ruby
@people = Person
  .select('`user`.`name`, `conversations`.`status` AS conversation_status')
  .joins(:conversations)

@people.map &:conversation_status
# => [ 1, 1, 0 ]
```

What I can do to type cast the values seems a bit awkward:

```ruby
@people.map do |person|
  Conversation.statuses.find { |name, ind| ind == person.conversation_status }.first
end
# => [ 'archived', 'archived', 'active' ]
```

#### My question
Is there an official / rails / less awkward way of getting there? Thanks in advance!

(Digging into the source code I found that there is an `ActiveRecord::Enum::EnumType` insatnce that can `deserialize` the value for me, but I  did not find any public way to fetch it.)

**Comment by rafaelfranca** [comment]
Please use the mailing list or StackOverflow for questions/help, where a wider community will be able to help you. We reserve the issues tracker for issues only.
