### ISSUE TITLE
String#underscore should treat the boundaries of alphanumeric and numeric characters as a word break

### ISSUE THREAD

**Issue by cbzehner** [rails/rails#34610]
Thanks for taking the time to look at this. I just ran into this today at work and I believe it's a niche issue that falls on the bug side of the feature request/bug report line. For very specific, semi-common inputs, it seems that the `String#underscore` method does not serve as the reverse of `String#camelize`. This breaks the expected (but not guaranteed) behavior.

This has led to some confusion downstream, see https://github.com/rmosolgo/graphql-ruby/issues/1839

Would you please verify whether or not this is the intended behavior of `String#underscore`?

If not would you be open to a pull request to handle this edge case? I'd be happy to put one up over the holidays.

### Steps to reproduce
Call the `String#underscore` function in Rails console with the output given below.

### Expected behavior
Expect: `String#underscore()` to reverse the effects of `String#camelize`

> As a rule of thumb you can think of `underscore` as the inverse of `camelize`, though there are cases where that does not hold:

```ruby
> input = 'address_1'
> input.camelize(:lower).underscore() == input
=> true
```

Output:

```ruby
> 'address_1'.camelize(:lower)
=> "address1"
> 'address1'.underscore()
=> "address_1"
```

### Actual behavior
Actual: `String#underscore()` does not reverse `String#camelize`

```ruby
> input = 'address_1'
> input.camelize(:lower).underscore() == input
=> true
```

Output:

```ruby
> 'address_1'.camelize(:lower)
=> "address1"
> 'address1'.underscore()
=> "address1"
```

### Other Cases
I would expect this to output `the_4th_of_july`

```ruby
> 'The4thOfJuly'.underscore()
=> "the4th_of_july"
```

### System configuration
**Rails version**: Rails 5.1.4

**Ruby version**: ruby 2.4.3p205 (2017-12-14 revision 61247) [x86_64-darwin18]

**Comment by gmcgibbon** [comment]
I would say this is intended behaviour ([test](https://github.com/rails/rails/blob/bd62389307e138ee0f274a9d62697567a3334ea0/activesupport/test/inflector_test.rb#L151) [coverage](https://github.com/rails/rails/blob/bd62389307e138ee0f274a9d62697567a3334ea0/activesupport/test/inflector_test.rb#L233)). String inflections aren't perfectly usable for all use cases, and I agree that this is a reasonable expectation for yours. Unfortunately, we don't accept patches for inflection because it would break legacy behaviour.

On the bright side, you can try to work around the situation with custom inflections for your app:

```
ActiveSupport::Inflector.inflections(:en) do |inflect|
  inflect.acronym '4th'
  inflect.acronym '1'
end
```

You may also use something like this monkey patch at your own risk:

```
def underscore(camel_cased_word)
  return camel_cased_word unless /[A-Z-]|::/.match?(camel_cased_word)
  word = camel_cased_word.to_s.gsub("::", "/")
  word.gsub!(inflections.acronyms_underscore_regex) { "#{$1 && '_' }#{$2.downcase}" }
  word.gsub!(/([A-Z\d]+)([A-Z][a-z]|\d)/, '\1_\2')
  word.gsub!(/([a-z\d])([A-Z]|\d)/, '\1_\2')
  word.tr!("-", "_")
  word.downcase!
  word
end
```

**Comment by rafaelfranca** [comment]
Also see the note in the documentation http://api.rubyonrails.org/classes/ActiveSupport/Inflector.html#method-i-underscore

> As a rule of thumb you can think of underscore as the inverse of camelize, though there are cases where that does not hold:
