### ISSUE TITLE
distance of time in words should be tweaked

### ISSUE THREAD

**Issue by dieterdreist** [rails/rails#34625]
### Steps to reproduce
according to the docs: 
https://api.rubyonrails.org/classes/ActionView/Helpers/DateHelper.html#method-i-distance_of_time_in_words

everything up to 1 day and 18 hours is counted as 1 day, which will lead to unintuitive results when there are 2 nights in between and generally for time > 36 hours.

Imagine fixing a bug at Saturday 3p.m. and talking about it Monday 8 a.m. Would you say "one day ago" or "two days ago"?

These are 41 hrs and would still be returned as "1 day" with the current code: 

```
23 hrs, 59 mins, 30 secs <-> 41 hrs, 59 mins, 29 secs                     # => 1 day
41 hrs, 59 mins, 30 secs  <-> 29 days, 23 hrs, 59 mins, 29 secs           # => [2..29] days
```

https://github.com/rails/rails/blob/94b5cd3a20edadd6f6b8cf0bdf1a4d4919df86cb/actionview/lib/action_view/helpers/date_helper.rb#L680

### Expected behavior
Should return "2 days"  from Saturday afternoon to Monday morning

### Actual behavior
returns "1 day" from Saturday afternoon to Monday morning

I agree this is not an obvious topic, it might be a question of culture and habit, but currently it clearly is slightly off and should be improved by adjusting the limit, e.g. to something around 36 hours for the shift from 1 day to 2 days. Looking at the nights rather than just the number of hours might improve the results as well.

**Comment by rafaelfranca** [comment]
I get your argument but changing this may break other applications and I'd say it is not required to do given it is documented. That being said I prefer to keep the behavior as is. Thank you for the issue.
