### ISSUE TITLE
Incorrect SQLite statement generated for pluck of an attribute of an associated object

### ISSUE THREAD

**Issue by plindelauf** [rails/rails#34622]
### Steps to reproduce

Given the following models: (**edit:** corrected the typo in the `:inverse_of`)

    class Company < ApplicationRecord
      has_many :users, :inverse_of => :company
    end

    class User < ApplicationRecord
      belongs_to :company, :inverse_of => :users
    end

In SQLite, `pluck` an attribute (with the same name) on the associated object, like so:

    User.where('company_id = 1').includes(:company).pluck(:id, :'companies.id')

### Expected behavior
The generated SQL should look like this:

    SELECT "users"."id", "companies"."id" FROM "users" LEFT OUTER JOIN "companies" ON "companies"."id" = "users"."company_id" WHERE (company_id = 1);

In Ruby the result should then be something like: 

    [[4, 1], [2, 1], [1, 1]

### Actual behavior
Instead the SQLite statement looks like this (note the missing quotes behind `companies` and before `name`:

    SELECT "users"."id", "companies.id" FROM "users" LEFT OUTER JOIN "companies" ON "companies"."id" = "users"."company_id" WHERE (company_id = 1);

In Ruby the result is: 

    [[4, "companies.id"], [2, "companies.id"], [1, "companies.id"]

### System configuration
**Rails version**: 5.1.6

**Ruby version**: 2.4.4p296

**Comment by evexoio** [comment]
Hey @plindelauf, I'm trying to reproduce your issue.

I'm not able to create a `User` and save it, because it needs a company, and when I set it a company it doesn't work because the company wants the user to have an id, and it can't have an id without a company. its like chicken-egg problem. 😭

```
>> u = User.new
=> #<User id: nil, created_at: nil, updated_at: nil>
>> c = Company.new
=> #<Company id: nil, created_at: nil, updated_at: nil>
>> c.save
   (0.2ms)  begin transaction
  Company Create (0.5ms)  INSERT INTO "companies" ("created_at", "updated_at") VALUES (?, ?)  [["created_at", "2018-12-05 11:29:28.463716"], ["updated_at", "2018-12-05 11:29:28.463716"]]
   (2.1ms)  commit transaction
=> true
>> u.company = c
Traceback (most recent call last):
        1: from (irb):23
ActiveModel::MissingAttributeError (can't write unknown attribute `company_id`)
>> u.save
=> false
>> u.errors
=> #<ActiveModel::Errors:0x00007fe6ec7bf068 @base=#<User id: nil, created_at: nil, updated_at: nil>, @messages={:company=>["must exist"]}, @details={:company=>[{:error=>:blank}]}>
>>
```

How can I fix this?

**Comment by plindelauf** [comment]
Well, your `User` model needs a `company_id` to hold the foreign key. And then you can first create a company:

    c = Company.create

And then add users to it:

    u = c.users.create

**Comment by evexoio** [comment]
Here is my models

```
$ cat ./app/models/*.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end
class Company < ApplicationRecord
  has_many :users, :inverse_of => :Company
end
class User < ApplicationRecord
  belongs_to :company, :inverse_of => :users
end
```

And here I executed what you said. I still get an error.

```
>> c = Company.create
   (1.6ms)  SELECT sqlite_version(*)
   (0.0ms)  begin transaction
  Company Create (0.4ms)  INSERT INTO "companies" ("created_at", "updated_at") VALUES (?, ?)  [["created_at", "2018-12-05 12:51:27.472147"], ["updated_at", "2018-12-05 12:51:27.472147"]]
   (1.0ms)  commit transaction
=> #<Company id: 3, created_at: "2018-12-05 12:51:27", updated_at: "2018-12-05 12:51:27">
>> u = c.users.create
Traceback (most recent call last):
        1: from (irb):2
ActiveRecord::InverseOfAssociationNotFoundError (Could not find the inverse association for users (:Company in User))
>>
```

can you push a repo that I can test on?

**Comment by adbatista** [comment]
@evexoio just try with `has_many :users, :inverse_of => :Company` lower case company

**Comment by adbatista** [comment]
example with breaking test

```
# frozen_string_literal: true

require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  gem "activerecord", "5.1.6"
  gem "sqlite3"
end

require "active_record"
require "minitest/autorun"
require "logger"

# This connection will do for database-independent bug reports.
ActiveRecord::Base.establish_connection(adapter: "sqlite3", database: ":memory:")
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :users, force: true do |t|
  	t.integer :company_id, index: true, foreign_key: true
  end

  create_table :companies, force: true do |t|
  end
end

class Company < ActiveRecord::Base
  has_many :users, inverse_of: :company
end

class User < ActiveRecord::Base
  belongs_to :company, inverse_of: :users
end

class BugTest < Minitest::Test
  def test_pluck
    company = Company.create
    user = company.users.create

    assert_equal [[user.id, company.id]], User.where(company_id: company.id).includes(:company).pluck(:id, :'companies.id')
  end
end
```
