### ISSUE TITLE
Autoloading through ancestors

### ISSUE THREAD

**Issue by faucct** [rails/rails#34649]
### Steps to reproduce
```ruby
# app/controllers/v1.rb
module V1
end

# app/controllers/v1/foo.rb
module V1
  module Foo
  end
end

# app/controllers/v2.rb
module V2
  include V1
  Foo
end
```

### Expected behavior
I expect `Foo` to be resolvable in `V2` even when `V1::Foo` is not loaded.

### Actual behavior
I get `uninitialized constant V2::Foo` unless `V1::Foo` is loaded.

**Comment by faucct** [comment]
I think it is an issue of Rails autoload: constant resolving results should not depend on constants being loaded.

**Comment by rafaelfranca** [comment]
Sorry, this is how the autoload is implemented now. It does depends on load order. This is really similar to this gotcha here https://guides.rubyonrails.org/autoloading_and_reloading_constants.html#when-constants-aren-t-missed.

**Comment by faucct** [comment]
The one you've mentioned cannot be fixed since it doesn’t invoke `const_missing`. I believe my issue can be fixed. Do you mind me fixing this?
