### ISSUE TITLE
changes and saved_changes reversed between 5.2.1 and 5.2.2

### ISSUE THREAD

**Issue by donncha** [rails/rails#34645]
In R5.2.1, after creating a record `changes` is empty and `saved_changes` contains the changes persisted to the DB.

However, in R5.2.2 this is reversed.

## Rails 5.2.1
```
[44, 53] in /Users/donncha/development/ftd/test/models/account_status_test.rb
   44:   def test_udpate_attribute
   45:     account_status = AccountStatus.create!(:description => "something")
   46:     assert_not_nil account_status.status_id
   47:     byebug
=> 49:     assert account_status.update_attribute(:description, "banana")
   50:     assert_equal "banana", account_status.description
   51: 
   52:     assert_equal "banana", account_status.reload.description
   53:   end
(byebug) account_status.changes
{}
(byebug) account_status.saved_changes
{"status_id"=>[nil, 29], "description"=>[nil, "something"], "last_updated"=>[nil, Thu, 06 Dec 2018 16:56:31 PST -08:00]}
(byebug) quit
```

## Rails 5.2.2
```
[44, 53] in /Users/donncha/development/ftd/test/models/account_status_test.rb
   44:   def test_udpate_attribute
   45:     account_status = AccountStatus.create!(:description => "something")
   46:     assert_not_nil account_status.status_id
   47:     byebug
=> 49:     assert account_status.update_attribute(:description, "banana")
   50:     assert_equal "banana", account_status.description
   51: 
   52:     assert_equal "banana", account_status.reload.description
   53:   end
(byebug) account_status.changes
{"status_id"=>[nil, 28], "description"=>[nil, "something"], "last_updated"=>[nil, Thu, 06 Dec 2018 16:55:08 PST -08:00]}
(byebug) account_status.saved_changes
{}
(byebug) quit
```

### Expected behavior
The record is persisted to the DB, so `changes` should be empty and `saved_changes` should contain the persisted changes, as happens in R5.2.1.

### Actual behavior
`saved_changes` is empty, so technically the record is still dirty. Subsequent calls to e.g: `update_attribute` then think the `id` is dirty so will append "WHERE record.id IS NULL" to the update query resulting in no update happening.

### System configuration
Rails 5.2.2
Ruby 2.4.4

**Comment by donncha** [comment]
Broken by this [commit](https://github.com/rails/rails/commit/34f075fe5666dcf924606f8af2537b83b7b5139f#diff-2bd7c52253c45ccc631ca0d1199d1201l) which removed the `changes_applied` callbacks and placed them in `_create_record()` and `_update_record()` which are never called.

**Comment by rafaelfranca** [comment]
cc @kamipo

**Comment by donncha** [comment]
Can't duplicate on clean fork of ActiveRecord. Something else in our code base is causing this, so can go ahead close.

Apologies everyone! 😊
