### ISSUE TITLE
ActionDispatch::IntegrationTest#url_options are not being reset within tests

### ISSUE THREAD

**Issue by whiny-nil** [rails/rails#34640]
### Steps to reproduce
* Assume you have a `FoosController` and a `BarsController`, and nested routes set up such that foos_url() and foo_bars_url() exist
* create a test like:

```
class MyIntegrationTest < ActionDispatch::IntegrationTest
  it 'should do some stuff' do
    post foos_url(foo_id: '123'), params: { something: 'Whatev' }
    post foo_bars_url(bar_id: '789'), params: { doesnt: "Matter" }
    # ... etc ...
  end  
end
```

### Expected behavior
The call to `foo_bars_url(bar_id: '789')` should fail because I did not call it with a :foo_id.

### Actual behavior
The call succeeds because the :foo_id which was passed to `foos_url()` in the previous line is still cached in `url_options`

### System configuration
**Rails version**: 5.2.1.1

**Ruby version**: 2.5.1p57 (2018-03-29 revision 63029) [x86_64-darwin17]

**Comment by gmcgibbon** [comment]
I can't seem to reproduce this on `5.2.1.1` or master. Please use the [bug report template](https://github.com/rails/rails/blob/master/guides/bug_report_templates/action_controller_master.rb) or provide a sample app so we can narrow down the issue. Thanks!

**Comment by whiny-nil** [comment]
Hmm, I can't get this to work in a new vanilla app either, though I am definitely seeing it in one of my other apps.  I'm going to have to see if it is more subtle than this, or if it's the result of some other gem / code.

Sorry for the trouble.
