### ISSUE TITLE
Conflict with ISO8601 serializer and parser on ActiveSupport::Duration

### ISSUE THREAD

**Issue by crashtech** [rails/rails#34655]
### Steps to reproduce
```ruby
duration = ActiveSupport::Duration.build(1000000)
duration_iso = duration.iso8601
ActiveSupport::Duration.parse(duration_iso)
```

### Expected behavior
```ruby
{:weeks => 1, :days=>4, :hours=>13, :minutes=>46, :seconds=>40}
```

### Actual behavior
```ruby
ActiveSupport::Duration::ISO8601Parser::ParsingError: Invalid ISO 8601 duration: "P1W4DT13H46M40S" mixing weeks with other date parts not allowed
```

### System configuration
Rails 5.2.1
Ruby 2.3.1

There's an Exception prohibiting mixing weeks with other date pieces. Although it seems a correct Exception, it makes the process confusing since I could measure a duration by "2 months and 1 week" in any other aspect, and it would also provide a correct behavior on ` ActiveSupport::Duration#parse`

The solutions simply remove the exception and allow it to move forward.
https://github.com/rails/rails/blob/master/activesupport/lib/active_support/duration/iso8601_parser.rb#L106

**Comment by quedvi** [comment]
I can confirm this bug is still present in Rails 5.2.3 / Ruby 2.6.3

Checking the ISO8601, mixing of week with other date parts is not allowed. Therefore I would suggest to change the ISO8601Serializer to:
