### ISSUE TITLE
Filename method gives invalid data

### ISSUE THREAD

**Issue by a-ta-ta** [rails/rails#34663]
### Steps to reproduce
I'm on Rails 5.2. My app has  model Image which has one attached :image_file. In production I use GCS.
To make changes to the image (say rotating) I'm downloading the file, change it with MiniMagick and it takes only to update it in the cloud.

I couldn't find a method in ActiveStorage to do that, so it takes using bare `google-cloud-ruby`.
The problem is I can't get filename to  make delete/create operations.

### Expected behavior
I thought it gives the filename in the storage.

### Actual behavior

But I was wrong:
When I use `Image.last.image_file.filename` it gives me 
`=> #<ActiveStorage::Filename:0x007f99446d5918 @filename="pobediteli-fotokonkursa-Dog-Photographer-of-the-Year-2018_5.jpg">`
which seems to be original filename (before downloading the image to the app).
```
irb(main):079:0> file = bucket.file("pobediteli-fotokonkursa-Dog-Photographer-of-the-Year-2018_5.jpg")
Sending HTTP get https://www.googleapis.com/storage/v1/b/pronashevse.ru/o/pobediteli-fotokonkursa-Dog-Photographer-of-the-Year-2018_5.jpg?
404
```

I could be wrong but I see no benefits in having the original filename stored. However, the actual filename could be useful at least for passing it to `google-cloud-ruby`

### System configuration
**Rails version 5.2**:

**Ruby version 2.5.1**:

**Comment by georgeclaghorn** [comment]
Active Storage blobs are [intended to be immutable](https://github.com/rails/rails/tree/cf71f31e2e152eceeb311aea6eadba3f2a814d81/activestorage#compared-to-other-storage-solutions). You can attach a new blob and purge the old one.
