### ISSUE TITLE
Inline SVGs not displayed when loaded from ActiveStorage 5.2.1.1 and 5.2.2

### ISSUE THREAD

**Issue by slecorvaisier** [rails/rails#34665]
Since the Rails 5.2.1.1 update, SVGs from ActiveStorage are considered as `application/octet-stream` and cannot be displayed anymore. It was previously considered as `image/svg+xml` on Rails 5.2.1.0 and worked perfectly.

On Rails 5.2.1.1 / 5.2.2
```
Processing by ActiveStorage::DiskController#show as SVG
  Parameters: {"content_type"=>"application/octet-stream", "disposition"=>"attachment; filename=\"test.svg\"; filename*=UTF-8''test.svg", "encoded_key"=>"{KEY}", "filename"=>"test"}
Completed 200 OK in 1ms (ActiveRecord: 0.0ms)
```

On Rails 5.2.1.0
```
Processing by ActiveStorage::DiskController#show as SVG
  Parameters: {"content_type"=>"image/svg+xml", "disposition"=>"attachment; filename=\"test.svg\"; filename*=UTF-8''test.svg", "encoded_key"=>"{KEY}", "filename"=>"test"}
  Disk Storage (7.2ms) Downloaded file from key: {another_key}
Completed 200 OK in 9ms (ActiveRecord: 0.0ms)
```

### Steps to reproduce
Create a record with an SVG attachment (`has_one_attached: graphic`)
Show the SVG with an image tag
```
= image_tag url_for(my_record.graphic)
```

### Expected behavior
SVG file should be displayed

### Actual behavior
Broken image icon displayed, a click on the link in the src attribute will download the SVG as an attachement

### System configuration
**Rails version**: 5.2.1.1 or 5.2.2

**Ruby version**: 2.4.4

**Comment by SebouChu** [comment]
Same for me,

It happened since Rails 5.2.1.1 with [this commit](https://github.com/rails/rails/commit/54ed6ad8d7468dc3a0b690e629c7c18497552eb8), which makes files with content-type listed in this array : 
```ruby
ActiveStorage::Engine.config.active_storage.content_types_to_serve_as_binary
``` 
forced to be served at binary (`application/octet-stream`)

The only workaround I found is to remove `image/svg+xml` from it in an initializer but I don't know if there is any other way cleaner and prettier so I'm opened to any suggestion 😊

**Comment by rafaelfranca** [comment]
Since SVG+XML can be used as XSS vectors we disabled the possibility to SVG uploaded by users be inlined in the page by default. You still can change the configuration, but be aware that you may be opening your system to XSS type of attacks.

**Comment by crescentrose** [comment]
@rafaelfranca Is it possible to sanitize the incoming SVG file so that XSS attacks are prevented? Similar to [what GitLab does](https://gitlab.com/gitlab-org/gitlab-ce/blob/master/lib/gitlab/sanitizers/svg.rb).

**Comment by crescentrose** [comment]
Well, what I meant by that was more like, if I made a pull request to do that, would it get merged, or is it better done as a separate, per-project thing? :D

**Comment by rafaelfranca** [comment]
ah, got it. Rails will keep SVG in that list. Even that you can sanitize it is very probably that you will add an inline SVG in the page without knowing you need to sanitize. That said, if you want to do that in your application, you can on you own risk, but Rails will include SVG in that list by default.

**Comment by crescentrose** [comment]
Alright, thank you!
