### ISSUE TITLE
parsed_body not working as expected for controller tests

### ISSUE THREAD

**Issue by tbuehlmann** [rails/rails#34676]
### Steps to reproduce

```ruby
# frozen_string_literal: true

require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  # Activate the gem you are reporting the issue against.
  gem "rails", "5.2.2"
end

require "rack/test"
require "action_controller/railtie"

class TestApp < Rails::Application
  config.root = __dir__
  config.session_store :cookie_store, key: "cookie_store_key"
  secrets.secret_key_base = "secret_key_base"

  config.logger = Logger.new($stdout)
  Rails.logger  = config.logger

  routes.draw do
    get "/" => "test#index"
  end
end

class TestController < ActionController::Base
  include Rails.application.routes.url_helpers

  def index
    render json: {'foo' => 'bar'}
  end
end

require "minitest/autorun"

class TestControllerTest < ActionController::TestCase
  def setup
    @routes = TestApp.routes
  end

  def test_returns_success
    get :index, as: :json
    assert_equal response.parsed_body, {'foo' => 'bar'}
  end
end

# Failure:
# TestControllerTest#test_returns_success [test.rb:48]:
# Expected: "{\"foo\":\"bar\"}"
#   Actual: {"foo"=>"bar"}

```

### Expected behavior

`response.parsed_body` parses the body using the json encoder when `as: :json` is given as it's the case with integration tests.

### Actual behavior

The default no-op encoder is used and no JSON parsing is happening.

The response parser is [set](https://github.com/rails/rails/blob/v5.2.2/actionpack/lib/action_dispatch/testing/test_response.rb#L19) when the `ActionDispatch::TestResponse` object is initialized. For integration tests, the CONTENT_TYPE header is passed to the constructor and the response parser can be set correctly. For controller tests, the CONTENT_TYPE header is not passed to the constructor but set at a later time when the response parser is already set (to the no-op encoder). Changing the response parser from being eagerly set to lazily works for me:

```diff
diff --git a/test_response.rb b/test_response.rb
index 1e6b21f..8f5208e 100644
--- a/test_response.rb
+++ b/test_response.rb
@@ -16,7 +16,6 @@ module ActionDispatch
 
     def initialize(*) # :nodoc:
       super
-      @response_parser = RequestEncoder.parser(content_type)
     end
 
     # Was the response successful?
@@ -47,7 +46,11 @@ module ActionDispatch
     end
 
     def parsed_body
-      @parsed_body ||= @response_parser.call(body)
+      @parsed_body ||= response_parser.call(body)
+    end
+    
+    def response_parser
+      @response_parser ||= RequestEncoder.parser(content_type)
     end
   end
 end
```

I'm aware that controller tests are kind of deprecated and that we should favor integration tests over them, so I'm not sure whether this is something we want to change at all.

### System configuration

**Rails version**: 5.2.2

**Ruby version**: 2.5.3

**Comment by rafaelfranca** [comment]
Let's change it. Can you open a PR?

**Comment by tbuehlmann** [comment]
Will do!

**Comment by tbuehlmann** [comment]
It seems the thing was hijacked, I'll wait and see if any good comes out of it before coming up with a separate PR. Weird situation, uncool at the very least.

**Comment by kaspth** [comment]
@tbuehlmann I hadn't caught that @abhisheksarka had just copied your patch over without any credit whatsoever. In the future, once you've already got a stab at a potential fix, feel free to submit a PR with your reproduction script in the description instead of just an issue. That's all fine for us 👍

Feel free to submit your own PR, I am going to close the other one.

**Comment by tbuehlmann** [comment]
Thanks for dealing with this, I'll come up with a PR.
