### ISSUE TITLE
activesupport: Camelize has no option to disable converting slashes to colons

### ISSUE THREAD

**Issue by obahareth** [rails/rails#34685]
Active Support's camelize method transforms slashes to double colons with no option to opt out of that behavior. This behavior seems to be hard coded at [this line](https://github.com/rails/rails/blob/master/activesupport/lib/active_support/inflector/methods.rb#L76). 

### Steps to reproduce

```ruby
"Hello/World".camelize(:lower)
=> "hello::World"
```

### Expected behavior

I expect to at least be able to pass a parameter to not transform slashes into colons.

```ruby
"Hello/World".camelize(:lower, transform_slashes: false)
=> "hello/World"
```

### Actual behavior
Slashes get transformed to double colons.

### System configuration
**Rails version**:
5.1.6.1

**Ruby version**:
2.4.2

I am willing to make a PR for this once we agree on how to proceed.

Thanks!

**Comment by rafaelfranca** [comment]
Thank you for the issue. That is by design, camelize was created with that in mind to map to Ruby modules and we have no plans to add new options to that method.

**Comment by joelmoss** [comment]
@rafaelfranca Would you be open to a PR to add support for this?

I also have a need to disable this feature, so an additional argument (eg. `convert_slashes: false`) would be awesome, and I would be happy to create a PR.

**Comment by rafaelfranca** [comment]
We have no plans to add new options to that method.
