### ISSUE TITLE
ActiveStorage returns 404 using local disk Filter chain halted as :set_blob rendered or redirected

### ISSUE THREAD

**Issue by srinivasan-sandy** [rails/rails#34687]
### Steps to reproduce
module Providers
  class AppointmentsController < BaseController
    require 'action_view'
    before_action :create_room, only: %i[call]
    skip_before_action :verify_authenticity_token, only: %i[update_session_notes end_call]

    def new
      @times = AppointmentTime.new.times
      @patient_options = UserDecorator.wrap(current_user.program_provider.patients).map { |u| [u.name, u.id, {'data-imagesrc'=>view_context.url_for(u.profile_picture) }] }

      render "providers/appointments/new", layout: "modal"
    end

As we can see that signed_id is getting lowercased:

{"data-imagesrc"=>"/rails/active_storage/blobs/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBCdz09IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--7e673e7609a8deb0857ae37a155b8c8acb1ab6b5/team4.jpg"}

Started GET "/rails/active_storage/blobs/eyjfcmfpbhmionsibwvzc2fnzsi6ikjbahbcdz09iiwizxhwijpudwxslcjwdxiioijibg9ix2lkin19--7e673e7609a8deb0857ae37a155b8c8acb1ab6b5/team4.jpg" for 127.0.0.1 at 2018-12-12 13:05:48 +0530
Processing by ActiveStorage::BlobsController#show as JPEG
  Parameters: {"signed_id"=>"eyjfcmfpbhmionsibwvzc2fnzsi6ikjbahbcdz09iiwizxhwijpudwxslcjwdxiioijibg9ix2lkin19--7e673e7609a8deb0857ae37a155b8c8acb1ab6b5", "filename"=>"team4"}
Filter chain halted as :set_blob rendered or redirected
Completed 404 Not Found in 1ms (ActiveRecord: 0.0ms)

ActiveStorage::Blob.find_signed("eyjfcmfpbhmionsibwvzc2fnzsi6ikjbahbcdz09iiwizxhwijpudwxslcjwdxiioijibg9ix2lkin19--7e673e7609a8deb0857ae37a155b8c8acb1ab6b5")
ActiveSupport::MessageVerifier::InvalidSignature: ActiveSupport::MessageVerifier::InvalidSignature

ActiveStorage::Blob.find_signed("eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBCdz09IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--7e673e7609a8deb0857ae37a155b8c8acb1ab6b5")
  ActiveStorage::Blob Load (0.5ms)  SELECT  "active_storage_blobs".* FROM "active_storage_blobs" WHERE "active_storage_blobs"."id" = $1 LIMIT $2  [["id", 2], ["LIMIT", 1]]
=> #<ActiveStorage::Blob:0x00007fed559b7dd8
 id: 2,
 key: "Y65yXrtkb7qARXPmCiCTBXTv",
 filename: "team4.jpg",
 content_type: "image/jpeg",
 metadata: {"identified"=>true},
 byte_size: 127764,
 checksum: "59SXcK/eyUpK6lTeuxm7hg==",
 created_at: Tue, 11 Dec 2018 12:49:45 UTC +00:00,
 archived: false,
 archived_at: nil>

### Expected behavior
Image should load without 404. 

### Actual behavior
Errors with 404 Filter chain halted as :set_blob rendered or redirected.
### System configuration
**Rails version**:
~> 5.2.0
**Ruby version**:
2.5.1

**Comment by gmcgibbon** [comment]
Can you reproduce the problem in a sample app or with the [bug report template](https://github.com/rails/rails/blob/master/guides/bug_report_templates/action_controller_master.rb)?

**Comment by srinivasan-sandy** [comment]
no am unable to reproduce this issue

**Comment by sidkhalidx** [comment]
having the very same error

**Comment by mtHB** [comment]
Someone else had the lowercasing issue: https://github.com/rails/rails/issues/32959

I get the same error, but without lowercased route.

**Comment by archonic** [comment]
People have reported the same issue when using the `route_downcaser` gem. See here: https://github.com/substancelab/route_downcaser/issues/33

**Comment by archonic** [comment]
I've also found that changing the `SECRET_KEY_BASE` env var can invalidate already generated variant URLs. This raises a whole bunch of issues. Once I have a minimal reproduction app, I'll open a new issue.

**Comment by wakproductions** [comment]
> I've also found that changing the `SECRET_KEY_BASE` env var can invalidate already generated variant URLs. This raises a whole bunch of issues. Once I have a minimal reproduction app, I'll open a new issue.

The SECRET_KEY_BASE gave me trouble when migrating my data from a development environment to production. In production, the SECRET_KEY_BASE was different from the development one, so none of the signed keys were recognized when using the files in production.

Under the hood, there's an object called `MessageVerifier` that the ActiveStorage `blob.signed_id` call uses. `MessageVerifier` uses the secret key base to generate the signed ID, but if you are in development it uses a randomly assigned one in `tmp/development_secret.txt`. It's a little sneaky because in development Rails is still using a secret key for things even though you may not be aware of it!

https://github.com/rails/rails/blob/v7.0.4/railties/lib/rails/application.rb#L417
