### ISSUE TITLE
Rails.cache.fetch_multi order of returned keys is non-deterministic

### ISSUE THREAD

**Issue by adamlogic** [rails/rails#34694]
I'm not sure if this is a bug or expected behavior, but I think it's a gotcha nonetheless. If not a bug, it should probably be documented.

### Steps to reproduce
```ruby
# frozen_string_literal: true

require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  gem "rails", github: "rails/rails"
end

require "active_support"
require "active_support/core_ext/object/blank"
require "minitest/autorun"

class BugTest < Minitest::Test
  def setup
    @cache = ActiveSupport::Cache.lookup_store(:memory_store)
  end

  def test_fetch_multi_order_with_partial_miss
    keys = @cache.fetch_multi(*%w(1 3 5)) { |key| key.to_i + 10 }.keys
    assert_equal %w(1 3 5), keys

    keys = @cache.fetch_multi(*%w(1 2 3 4 5)) { |key| key.to_i + 10 }.keys
    assert_equal %w(1 2 3 4 5), keys
    # Actual: 1 3 5 2 4 (cache hits followed by cache misses)
  end
end
```

### Expected behavior

I expected the returned keys to be in the same order they were passed to `fetch_multi`.

### Actual behavior

The order of the returned keys depends on cache hits and misses. The hits come first with the misses appended to the end.

### System configuration
**Rails version**: master

**Comment by al2o3cr** [comment]
Some related PR history:

* #11481 switched `fetch_multi` to returning a Hash. The keys were added in the order requested.

* #29366 refactored the method to explicitly collect the keys that missed, so the whole set could be passed to `write_multi`
