### ISSUE TITLE
Passing an Arel::Nodes::Equality instance built with the arel_table method to where fails to find records properly

### ISSUE THREAD

**Issue by fractaledmind** [rails/rails#34701]
### Steps to reproduce

Simply run the [test script](https://gist.github.com/fractaledmind/693df573d4d5644ccd71801272bf6af6)

### Expected behavior

```ruby
Model.where(data: some_model_instance.data)
Model.where(Model.arel_table[:data].eq(some_model_instance.data))
Model.where(Arel::Table.new(Model.table_name)[:data].eq(some_model_instance.data))
```

should each find `some_model_instance`.

### Actual behavior

Instead, `Model.where(Model.arel_table[:data].eq(some_model_instance.data))` finds nothing, while the other two do find `some_model_instance`.

### System configuration
**Rails version**:
confirmed this issue in both 5.1.6 and 5.2.0
**Ruby version**:
`ruby 2.4.1p111 (2017-03-22 revision 58053) [x86_64-darwin15]`

**Comment by gmcgibbon** [comment]
This works on MySQL and Postgres but appears to be a problem with quoting inserted binary data in the SQLite adapter. Its being inserted as `<16 bytes of binary data>`. I'll try to fix.
