### ISSUE TITLE
report_uri in CSP doesn't allow a "don't set" value

### ISSUE THREAD

**Issue by viraptor** [rails/rails#34703]
### Steps to reproduce
Define `report_uri` for the CSP configuration which computes value on demand:
```
  policy.report_uri(proc { "https://example.net" if some_condition })
``` 

### Expected behavior
When the condition isn't true, the `report_uri` directive is skipped.

### Actual behavior
`report_uri` directive is included and has no value.

### System configuration
**Rails version**: 5.2.2

**Ruby version**: 2.5.1

**Comment by y-yagi** [comment]
Please tell me a little more about your use case. 
If computes `report_uri` on demand, what do you specify to `content_security_policy_report_only`?  
It is possible to not generate `report_uri` according to the condition, but in that case, get a warning from a browser.

**Comment by viraptor** [comment]
According to https://w3c.github.io/webappsec-csp/2/#report_uri you can't use an empty `report-uri` directive, but it's legal to not include it at all.

It's useful to omit the report uri if you want the standard restrictions to still apply, but don't want to get every report. Specifically if you don't want to get every single report, but only a sample of them. (There's a directive for that in the spec, but not yet widely supported, and you still need to trust the client-side to use it)

**Comment by y-yagi** [comment]
First, I understand what you want to do. I am concerned about `Content-Security-Policy-Report-Only` header. 
`report-uri` uses with `Content-Security-Policy-Report-Only` header. If only `Content-Security-Policy-Report-Only` exists, certain browsers(e.g. `Firefox) show a warning. 

![firefox_warning](https://user-images.githubusercontent.com/987638/58518533-909c3f00-81ea-11e9-8163-f1327857d6e3.png)


Therefore, I understand that only emptying `report-uri` dynamically is incomplete, is it not a problem?
