### ISSUE TITLE
Add rails db:change SYSTEM=postgresql|mysql|whatever

### ISSUE THREAD

**Issue by dhh** [rails/rails#34710]
It's common to create a new Rails app without specifying the database system upfront. That means you'll get the sqlite system by default, which is great until you actually have to deploy in production. Then you usually want to swap sqlite out with something else, like MySQL or PostgreSQL. Doing so is too much of a hassle today.

I'd therefore like to see that we add a command that makes this easy. Running `rails db:change SYSTEM=postgresql` should overwrite config/database.yml with the database.yml config that we already keep in Railties for when a new app is started with `--database=postgresql`. It should also replace the `gem "sqlite"` line in the Gemfile with the PostgreSQL line.

**Comment by kaspth** [comment]
We still got Rails commands so it can be `--database` or we can have the database be a positional argument, no need for Rake like env variables.

**Comment by gmcgibbon** [comment]
I'd be happy to work on this if nobody else is.

**Comment by dhh** [comment]
Ah yes, of course, @kaspeth. Let's just go with `rails db:change --system=` then 👍.

Have at it @gmcgibbon 🙏

**Comment by dhh** [comment]
After further consideration, it would be nice to flesh this out a little more. So `rails db:system:change --to=postgresql` and then also have `rails db:system`, which would return the current DB system used on the current environment (if there is only one. If there are multiple, we can either just punt on that or figure out all the different systems if there are multiple).

**Comment by nsuchy** [comment]
I'm not sure if this would be better as a separate issue however while we're on the subject of making it easier to change the database type I have two ideas.

1) `rails db:system` commands should add the ability to specific the environment. For example `--env=production|dev|test`
2) A generated Rails app has the following in `config/database.yml`
```
# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
default: &default
  adapter: sqlite3
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: db/development.sqlite3

# Warning: The database defined as "test" will be erased and
# re-generated from your development database when you run "rake".
# Do not set this db to the same as development or production.
test:
  <<: *default
  database: db/test.sqlite3

production:
  <<: *default
  database: db/production.sqlite3
```
Perhaps as a comment, or even by default. Production should default to Postgresql or a comment that says "SQLite is not recommended for use in production".

Thoughts on these two things?

**Comment by dhh** [comment]
Those are definitely separate issues. I'm not really a big fan of running
different RDMS'es from development to production. Bound to bite you. But I
do like the idea of a log warning if you run sqlite in production.

**Comment by nsuchy** [comment]
Is `1` certainly a different issue. It pertains to this new feature that's being added. Avoiding changing all of the databases at once and allowing you to just toggle production or just toggle development.

As for `2`, I'll create a separate issue discussing that. A log warning sounds great and the less intrusive way to handle this.

**Comment by avosa** [comment]
Been trying the ```rails db:system:chnage --to=postgresql``` for a while now and apparently, I keep encountering the below error. Any walkaround?

![error](https://user-images.githubusercontent.com/31823892/161340537-e6771d0a-c4cb-4aa3-bc9e-91f301168d91.png)

**Comment by ghiculescu** [comment]
@avosa what version of Rails are you using? (`rails --version`)

https://github.com/rails/rails/pull/34832 was added in Rails 6.0.

**Comment by avosa** [comment]
@ghiculescu I'm on rails 6.1.5

**Comment by ghiculescu** [comment]
Hmm. I just tested this on a 6.1.5 app and it worked fine. I would try stopping spring and seeing if that helps.

**Comment by avosa** [comment]
Been doing that and for some reason I'm still encountering the issue. Or was the command changed? Because the error returned is ```invalid option --to=postgresql```

**Comment by ghiculescu** [comment]
No, I don't think so. https://github.com/rails/rails/blob/main/railties/lib/rails/commands/db/system/change/change_command.rb still shows `to` as the argument.

**Comment by avosa** [comment]
Thanks @ghiculescu ! I think it's related to the Operating System, on Mac worked fine but on Ubuntu it doesn't for some reason.

PS: I dropped you TandaHQ related email to [alex@tanda.co](mailto:alex@tanda.co) [h](https://www.workforce.com/).

**Comment by inayuky** [comment]
I encounterd the same problem on Rails 6.1.6.

```
% rails db:system:change --to=postgresql
Running via Spring preloader in process 15906
invalid option: --to=postgresql
```

I think this problem only occurs via 'spring'.

In fact, when I commented out 'spring' in the Gemfile and execute 'bundle update', the db change command works fine.

**Comment by inayuky** [comment]
Probably due to the following spring update.

https://github.com/rails/spring/commit/b85f41be7eed1533c88c38cf1e72628a249ab8e4

This forces to call rake for all db commands, but `db:system:change` should not be a rake task.

```
% rake db:system:change --to=postgresql
invalid option: --to=postgresql
```

**Comment by ghiculescu** [comment]
That could be it. Could you make an issue in the spring repo for this?

**Comment by inayuky** [comment]
@ghiculescu Thank you for your reply. I have made issue for this. https://github.com/rails/spring/issues/678#issue-1251660667
