### ISSUE TITLE
Inconsistent capture of a template fragment

### ISSUE THREAD

**Issue by alaz** [rails/rails#34729]
I have a helper method accepting a block (similar to `link_to`). I would expect it to capture a template fragment inside the block to selectively wrap it or omit based on conditions. But the behaviour differs depending on where this helper method is defined: in a helper module, or in a controller as `helper_method` or in a concern.

### Steps to reproduce

I have prepared a trivial test project [here](https://github.com/alaz/erb_helper_capture). Also I am going to show the most evident parts here in the issue.

I have a helper module

```
module HomeHelper
  def my_link_h(&block)
    link_to '/helper' do
      capture &block
    end
  end
end
```

Then I have a helper method defined in a controller:

```
  helper_method :my_link_hm

  def my_link_hm(&block)
    helpers.link_to '/helper_method' do
      helpers.capture &block
    end
  end
```

and a similar helper defined in a concern:

```
module MyConcern
  extend ActiveSupport::Concern

  included do
    helper_method :my_link_c
  end

  private

  def my_link_c(&block)
    helpers.link_to '/concern/helper_method' do
      helpers.capture &block
    end
  end
end
```

I render all three in a view:

```
<%= my_link_h do %>
  <%= 'inside helper' %>
<% end -%>

<%= my_link_hm do %>
  <%= 'inside helper_method' %>
<% end -%>

<%= my_link_c do %>
  <%= 'inside concern helper_method' %>
<% end -%>
```

### Expected behavior

I would expect all inner fragments to be rendered inside their `<a/>`s.

### Actual behavior

The actual output is

```
<a href="/helper">
  inside helper
</a>

  inside helper_method
<a href="/helper_method">
</a>

  inside concern helper_method
<a href="/concern/helper_method">
</a>
```

### System configuration
**Rails version**: 5.2.2

**Ruby version**: 2.5.3

**Comment by gmcgibbon** [comment]
> Is this documented somewhere?

AFAICT no. While I think calling view helpers in a controller method isn't quite right, it seems to be public API. So, it might be a good idea if we mention this gotcha in the [docs of `helper_method`](https://edgeapi.rubyonrails.org/classes/AbstractController/Helpers/ClassMethods.html#method-i-helper_method). I'll open a PR.
