### ISSUE TITLE
Calling update on an ActiveRecord model class no longer works

### ISSUE THREAD

**Issue by Aesthetikx** [rails/rails#34743]
Looks like you can no longer call `User.update(key: value)`, but must instead call `User.all.update(key: value)`. Not a huge deal to change, but I'm not sure if this was an intentional deprecation?

### Steps to reproduce
Given a model such as `User` with an `archived` boolean, call `User.update(archived: true)`.

### Expected behavior
Basically `each { |record| record.update(attributes) }`, archiving all users.

### Actual behavior
`wrong number of arguments (given 1, expected 2) (ArgumentError)`

### System configuration
**Rails version**: 5.2.2

**Ruby version**: 2.5.3p105

**Comment by Aesthetikx** [comment]
Seemingly caused by 5c65688

**Comment by nynhex** [comment]
doesn’t seem like a big deal but wondering if their was a deprecation warning in earlier releases

**Comment by kamipo** [comment]
Thanks for the report.
I've fixed in #34836 and backported to 5-2-stable since this should not be suddenly happened in a stable version.

**Comment by Aesthetikx** [comment]
Awesome, thanks so much! The joy of coding haha, if it's not one thing it's another.
