### ISSUE TITLE
Feature Proposal: Active Record Time Query Attributes

### ISSUE THREAD

**Issue by giovannibenussi** [rails/rails#34746]
It is common to suffix date, datetime, and time objects with `_on`, `_at`, and `_time` respectively.

A common case is to add a time-like attribute, let's say `read_at` for a notification model. If the attribute is present, then it is read, otherwise it is not read.

Currently I define a `read?` method this way:
```ruby
def read?
  read_at?
end
```

However, this pattern is pretty common so I would like to have a `read?` method automatically available as Active Record does with `read_at?` to indicate if it is present or not. This would also be useful to have methods like `notified?` and `broadcasted?` too.

I would implement this myself (as a my first contribution too!) but I'd like to know your thoughts before.

**Comment by y-yagi** [comment]
Thank you so much for the issue but we don't take feature request on the issue tracker. We recommend you to try to implement the feature and send us a pull request or if you are in doubt if the feature will be accepts ask in [Rails Core mailing list](https://groups.google.com/forum/#!forum/rubyonrails-core) for feedback. Thanks!
