### ISSUE TITLE
Even if overwrite data-confirm event on Internet Exproler it will fire.

### ISSUE THREAD

**Issue by swanmatch** [rails/rails#34759]
### Steps to reproduce
I introduced a data-confirm-modal Gem to replace ActionView data-confirm with bootstrap's Modal.

### Expected behavior
Only the bootstrap modal window appears.

### Actual behavior
There was no problem with Firefox, Chrome, Edge, but InternetExploer 11 only displays bootstrap Modal and browser standard confirm.

Since data-confirm-modal appeared to be return properly, I felt that some modifications to ActionView#rails_ujs were necessary and raised the issue.

Please someone please help me.‥orz

### System configuration
**Rails version**: 5.2.2
**Ruby version**: ruby 2.5.3p105

### Reference URL
https://github.com/rails/rails/blob/master/actionview/app/assets/javascripts/rails-ujs/features/confirm.coffee
https://github.com/ifad/data-confirm-modal/blob/master/vendor/assets/javascripts/data-confirm-modal.js

**Comment by y-yagi** [comment]
Please use the [mailing list](https://groups.google.com/forum/#!forum/rubyonrails-talk) or StackOverflow for questions/help, where a wider community will be able to help you. We reserve the issues tracker for issues only. Thanks.
