### ISSUE TITLE
Strong params being passed to exists? does not work

### ISSUE THREAD

**Issue by urkle** [rails/rails#34752]
### Steps to reproduce
p = params.permit(:user_id, :project_id)
MyModel.exists?(p)

### Expected behavior
it to return whether the specific model exists (based on the filter)

### Actual behavior
It returns false

### System configuration
**Rails version**:
5.2.2
**Ruby version**:
2.4.4

### More information

I debugged through the code and found that the cause is that the construct_relation_for_exists method is checking only for Array and Hash in order to modify the WHERE clause.  Thus it ends up trying to do where(primary_key => conditions) incorrectly.

This issue now exists, of course, due to the modifying of ActionController::Parameters to not inherit from HashWithIndifferentAccess.

To restore the previous (and expected) behavior, we should adjust the case to also include ActionController::Parameters as well as Array,Hash

### Workaround monkey patch
```ruby
module FixARExistsWithStrongParams
  def exists?(conditions = :none)
    if conditions.is_a?(ActionController::Parameters)
      conditions = conditions.to_h
    end
    super(conditions)
  end
end

ActiveRecord::Relation.send :prepend, FixARExistsWithStrongParams
```

**Comment by gmcgibbon** [comment]
Seeing how this works for `#where`, I see no reason why this shouldn't work for `#exists?`. I'll try to fix this.
