### ISSUE TITLE
Add rails db:seed:replant

### ISSUE THREAD

**Issue by dhh** [rails/rails#34765]
When you're iterating over your db/seeds.rb setup, it's common to want to wipe everything in the database to plant those seeds again in a clean state. Right now you have to do `rails db:setup`, which will rebuild the entire db for all envs, and then run `rails db:seed`. Would be nice to have a way to run `db:seed:replant` where the db is wiped and the new seeds are planted, without redoing the db structure.

This should come with protections/confirmations when run in any env except for test/dev.

**Comment by prithvi16** [comment]
We have something similar[1] implemented for a boilerplate we use at our company. It checks wheather the current enviornment is production first and then continues if it is not. Then it loads all models from models directory and iterates over `ApplicationRecord.descendants` to delete data in each table using `Model.delete_all`. The only gotcha here is that you have to check for an order while deleting data from tables to prevent foreign key exceptions. 

[1] https://github.com/bigbinary/wheel/blob/c6a8165f34aced46d73a0638835926c4cbf9ec48/lib/tasks/setup.rake#L26

**Comment by prithvi16** [comment]
Otherwise, we can just use `TRUNCATE` on all tables with foreign key checks disabled for the operation.
I am insterested in taking this issue up.

**Comment by bogdanvlviv** [comment]
:wave: ,
Seems like truncating is a good solution to wipe the database. I just created a draft that potentially could solution for this issue. See https://github.com/rails/rails/pull/34779

**Comment by rafbm** [comment]
@dhh From what I see, `db:reset` has been a single-command equivalent to `db:seed:replant` ever since [seeds were introduced](https://github.com/rails/rails/commit/4932f7b38f72104819022abca0c952ba6f9888cb). Except it does drop and rebuild the schema rather than just truncating. Curious what’s the original motivation for avoiding schema rebuild? Is it just saving a few seconds?

**Comment by dhh** [comment]
This is as much about being clear about your intentions as about outcomes.
You shouldn't have to destroy your databases just to redo the seeds. But
you're right, the outcome isn't vastly different.
