### ISSUE TITLE
Additional_types are not type cast as expected

### ISSUE THREAD

**Issue by rschellhorn** [rails/rails#34760]
### Steps to reproduce

Given the following template. Please note the Postgresql adapter!

```ruby
# frozen_string_literal: true

require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  # Activate the gem you are reporting the issue against.
  gem "activerecord", "5.2.2"
  gem "pg"
end

require "active_record"
require "minitest/autorun"
require "logger"

# This connection will do for database-independent bug reports.
ActiveRecord::Base.establish_connection(adapter: "postgresql", database: "bug")
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :posts, force: true do |t|
    t.text :title
    t.jsonb :comments
  end
end

class MyCustomType < ActiveRecord::Type::Value
  def cast(value)
    "It casts"
  end
end

class Post < ActiveRecord::Base
  attribute :title, MyCustomType.new
  attribute :comments, MyCustomType.new
  attribute :ratings, MyCustomType.new
end

class BugTest < Minitest::Test
  def test_association_stuff
    Post.create!(title: 'The title', comments: { a: 1 })

    post = Post.select("posts.*, to_json('great'::text) as ratings").first

    assert_equal 'It casts', post.title
    assert_equal 'It casts', post.comments
    assert_equal 'great', post.ratings # <-- current behaviour
    assert_equal 'It casts', post.ratings # <-- expected behaviour
  end
end
```

### Expected behavior
All three attributes on `Post` are treated using the same logic no matter how they are queried. Thus they are all type cast using `MyCustomType`.

### Actual behavior
[Additional types](https://github.com/rails/rails/blob/b2eb1d1c55a59fee1e6c4cba7030d8ceb524267c/activemodel/lib/active_model/attribute_set/builder.rb#L108) from the AttributeSet, `ratings` in this case, are not being type cast using the attribute api.

Note that the actual type from the database does not matter. My goal is to use this strategy to unmarshall some jsonb column into a ActiveModel representation.

### System configuration
**Rails version**: 5.2.2

**Ruby version**: 2.5.3

**Comment by kamipo** [comment]
Fixed by 7432e251873690234d0d288e8eb009fbee80b635.
