### ISSUE TITLE
`private_methods(false)` behavior changed in 5.2.2

### ISSUE THREAD

**Issue by kddeisz** [rails/rails#34772]
### Steps to reproduce

```ruby
# frozen_string_literal: true

require 'bundler/inline'

gemfile(true) do
  source 'https://rubygems.org'

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  gem 'rails', github: 'rails/rails', ref: '10679c2cbd25550f6625dcac0d9f813e8e91b2ab'
end

require 'rails/all'
require 'minitest/autorun'

module Scopes
  class << self
    def append_features(base)
      private_methods(false).each do |scope_name|
        base.scope(scope_name, send(scope_name))
      end
    end

    private

    def foo
      -> { all }
    end
  end
end

class User < ActiveRecord::Base
  include Scopes
end

class BugTest < Minitest::Test
  def test_stuff
    assert User.respond_to?(:foo)
  end
end
```

### Expected behavior

Before the commit referenced in the code above, `private_methods(false)` returns `[:foo]`, and after it returns a whole list of private methods for modules.

### Actual behavior

I'd expect that it should only return `[:foo]` based on the docs here (https://www.rubydoc.info/stdlib/core/Object:private_methods) but interestingly `Module.new.private_methods(false)` in a plain irb terminal returns `[:remove_const, :method_added, :method_removed, :append_features, :method_undefined, :extend_object, :using, :prepend_features, :refine, :public, :initialize, :initialize_copy, :initialize_clone, :protected, :module_function, :private, :included, :extended, :prepended]`.

So I'm not actually sure if the behavior that just returns `[:foo]` is correct and so now it's broken or if returning the full list is correct and now it's reverted to correct behavior. Either way this is an odd breaking change for a patch release.

**Comment by kddeisz** [comment]
@kamipo I'm tagging you since https://github.com/rails/rails/commit/10679c2cbd25550f6625dcac0d9f813e8e91b2ab is your commit so you might have more context

**Comment by kamipo** [comment]
I couldn't find any version that `private_methods(false)` returns `[:foo]`.
Can you find the version that behavior changed again?

**Comment by kddeisz** [comment]
@kamipo If you use the template above, the test breaks with `10679c2cbd25550f6625dcac0d9f813e8e91b2ab` but doesn't with `10679c2cbd25550f6625dcac0d9f813e8e91b2ab^` (`90c033984f38e40c2ff53c036d89ee22c88fadab`).

**Comment by kddeisz** [comment]
It breaks with `bug.rb:21:in `remove_const': wrong number of arguments (given 0, expected 1) (ArgumentError)` because it's trying to loop through `private_methods(false)` and getting `remove_const` as one of the options.

**Comment by kamipo** [comment]
Thanks. I've found the minimum code.
This is caused by `prepend` a module on the `Module` class, seems a bug on the Ruby side.

```ruby
class Module
  prepend Module.new
end

module Foo
end

p Foo.private_methods(false)
# => [:remove_const, :method_added, :method_removed, :method_undefined, :prepend_features, :extend_object, :refine, :using, :append_features, :initialize, :initialize_clone, :initialize_copy, :public, :private, :module_function, :protected, :included, :extended, :prepended]

Foo.singleton_class

p Foo.private_methods(false)
# => []
```

**Comment by kddeisz** [comment]
Thanks @kamipo! I'll report it over there.
