### ISSUE TITLE
text_area expects 1..2 arguements while docs say it takes 3 arguements

### ISSUE THREAD

**Issue by evexoio** [rails/rails#34787]
### Steps to reproduce
https://github.com/lobsters/lobsters/pull/625/files

### Expected behavior
https://api.rubyonrails.org/classes/ActionView/Helpers/FormHelper.html#method-i-text_area

### Actual behavior
https://travis-ci.org/lobsters/lobsters/builds/471782389#L828

### System configuration
**Rails version**:
5.2.1

**Ruby version**:
2.3.3

**Comment by y-yagi** [comment]
Thanks for your report.  
You mentioned to `FormHelper#text_area`, but actually using `FormBuilder#text_area`. 
I think that it is a issue that the methods of form builders is not generated in doc. This will fix by #34791.
