### ISSUE TITLE
Active Storage gives Stack too deep error

### ISSUE THREAD

**Issue by fanz1st** [rails/rails#34796]
### Steps to reproduce

1. Create a model and controller for Product with a image attribute
2. Add has_one_attached :image ( for active storage ) 

class Product < ApplicationRecord
	has_one_attached :image
end

class ProductsController < ApplicationController
  def index
    @products = Product.all
  end
  def product_params
      params.require(:product).permit( :image)
  end

end

### Expected behavior
Would like to  read the @products = Product.all in the index as JSON.

### Actual behavior
Get a Stack Too Deep Error.
When you remove the (has_one_attached :image) from the model file and reload you are able to read the son data.

### System configuration
**Rails version**: rails -v 5.2.1 and rails 5.2.2

**Ruby version**:
ruby 2.5.1

**Comment by y-yagi** [comment]
Can you please provide a sample application that reproduces the issue?

**Comment by fanz1st** [comment]
[test app](https://github.com/fanz1st/rails_stack_error)
Install app and try to upload file. then try to view the index json

**Comment by y-yagi** [comment]
Thanks. I could confirm the issue. 
First of all, it is not the correct state that `SystemStackError` happens. But what is this code you are expecting?  
Since `image` is an instance of `ActiveStorage::Attached::One`, it is not suitable for inclusion in JSON. Do you expect URLs?

**Comment by fanz1st** [comment]
Yes want to get the image url  in JSON format

**Comment by y-yagi** [comment]
OK. You need to use `url_for` or `rails_blob_path` as follows. 

```dif 
diff --git a/app/views/users/_user.json.jbuilder b/app/views/users/_user.json.jbuilder
index ba533e5..80f1241 100644
--- a/app/views/users/_user.json.jbuilder
+++ b/app/views/users/_user.json.jbuilder
@@ -1,2 +1,3 @@
-json.extract! user, :id,:image, :created_at, :updated_at
+json.extract! user, :id, :created_at, :updated_at
+json.image_url rails_blob_path(user.image)
 json.url user_url(user, format: :json) 
``` 

Please see [Linking to Files](https://edgeguides.rubyonrails.org/active_storage_overview.html#linking-to-files) for more details. Thanks.
