### ISSUE TITLE
Tests cause ThreadError: already initialized with Ruby 2.6.0

### ISSUE THREAD

**Issue by shirosaki** [rails/rails#34790]
### Steps to reproduce

Test like this causes `ThreadError: already initialized` after updating Ruby 2.6.0.

```ruby
class EmployeesControllerTest < ActionController::TestCase
  def test_list_markup
    get :list
    assert_response(:success)
  end
  ...
end
```

```
EmployeesControllerTest#test_edit_markup:
ThreadError: already initialized
    /home/shirosaki/.rbenv/versions/2.6.0/lib/ruby/2.6.0/monitor.rb:259:in `mon_initialize'
    /home/shirosaki/.rbenv/versions/2.6.0/lib/ruby/2.6.0/monitor.rb:252:in `initialize'
    /home/shirosaki/.rbenv/versions/2.6.0/lib/ruby/gems/2.6.0/gems/actionpack-4.2.11/lib/action_dispatch/http/response.rb:119:in `initialize'
    /home/shirosaki/.rbenv/versions/2.6.0/lib/ruby/gems/2.6.0/gems/actionpack-4.2.11/lib/action_controller/test_case.rb:277:in `recycle!'
    /home/shirosaki/.rbenv/versions/2.6.0/lib/ruby/gems/2.6.0/gems/actionpack-4.2.11/lib/action_controller/test_case.rb:617:in `process'
    /home/shirosaki/.rbenv/versions/2.6.0/lib/ruby/gems/2.6.0/gems/actionpack-4.2.11/lib/action_controller/test_case.rb:67:in `process'
    /home/shirosaki/.rbenv/versions/2.6.0/lib/ruby/gems/2.6.0/gems/actionpack-4.2.11/lib/action_controller/test_case.rb:514:in `get'
    /home/shirosaki/work/master/test/functional/employees_controller_test.rb:24:in `test_edit_markup'
```
### Expected behavior

Not raise ThreadError.

### Actual behavior

Raise ThreadError.

### System configuration
**Rails version**:
4.2.11
**Ruby version**:
2.6.0

The error would be related to this issue.
https://bugs.ruby-lang.org/issues/15000

If I remove `raise ThreadError, "already initialized"` in `lib/monitor.rb`, tests pass.

**Comment by vinistock** [comment]
The error occurs in Rails 4.2.11 and it seems to be only in controller specs.

You can see the error at this [travis job output] for a gem I test against multiple Rails/Ruby versions.

[travis job output]: https://travis-ci.org/vinistock/sail/jobs/472422248

**Comment by y-yagi** [comment]
Thanks for your information.  
As described above, 4.2 only support severe security issues.  
If this only occurs in 4.2, we do nothing. So I close. Thanks.

**Comment by markets** [comment]
Hi @y-yagi @vinistock, I confirm this only happens with Ruby `2.6` and Rails `4.2`.

It only happened to me in controller tests too, while upgrading the CI matrix in https://github.com/markets/maily. 

The weird thing is that those tests were passing for me 1 week ago using `ruby-head` (`2.6`) in Travis.

**Comment by markets** [comment]
Oh! you're totally right @y-yagi, last time it passed (ruby 2.6 + rails 4.2) was in October 12: https://travis-ci.org/markets/maily/jobs/440759767. But I didn't commit anything between October 12 and December 20, so I'm not sure at which point started to fail (at that time ruby 2.6 was in allowed failures). Did you know whether this is a only a problem in controller tests or rails 4.2 doesn't run in ruby 2.6? Thanks!

**Comment by Vasfed** [comment]
@markets this is caused by rails reusing `ActionController::TestResponse` object in tests, can be fixed by this monkeypatch:

```ruby
if RUBY_VERSION>='2.6.0'
  if Rails.version < '5'
    class ActionController::TestResponse < ActionDispatch::TestResponse
      def recycle!
        # hack to avoid MonitorMixin double-initialize error:
        @mon_mutex_owner_object_id = nil
        @mon_mutex = nil
        initialize
      end
    end
  else
    puts "Monkeypatch for ActionController::TestResponse no longer needed"
  end
end
```

**Comment by markets** [comment]
Got it @Vasfed, thanks for the workaround :+1:

**Comment by mikebaldry** [comment]
> @markets this is caused by rails reusing `ActionController::TestResponse` object in tests, can be fixed by this monkeypatch:
> 
> ```ruby
> if RUBY_VERSION>='2.6.0'
>   if Rails.version < '5'
>     class ActionController::TestResponse < ActionDispatch::TestResponse
>       def recycle!
>         # hack to avoid MonitorMixin double-initialize error:
>         @mon_mutex_owner_object_id = nil
>         @mon_mutex = nil
>         initialize
>       end
>     end
>   else
>     puts "Monkeypatch for ActionController::TestResponse no longer needed"
>   end
> end
> ```

If you use streaming/live stuff, you'll also need

```ruby
class ActionController::LiveTestResponse < ActionController::Live::Response
  def recycle!
    @body = nil
    @mon_mutex_owner_object_id = nil
    @mon_mutex = nil
    initialize
  end
end
```

**Comment by timomitchel** [comment]
> ```ruby
> ActionDispatch::TestResponse
> ```

@Vasfed Which file did you put your solution in?

**Comment by Vasfed** [comment]
> @Vasfed Which file did you put your solution in?

somewhere in your test suite setup - test_helper/rails_helper or a separate file that is required from there (in`test/support` or `spec/support` depending on which test framework you're using)
Point is that for patch to work, it should have been run before controller tests

**Comment by timomitchel** [comment]
@Vasfed Thank you so much for the response. This worked for me as a helper in support. 👍

**Comment by danielricecodes** [comment]
> @Vasfed Which file did you put your solution in?

The Rails convention for files like this is `config/initializers`.  Thats where I put mine and I called it `monkey_patches.rb`

**Comment by timomitchel** [comment]
Thanks for the heads up @danielricecodes!

**Comment by mattheworiordan** [comment]
> The Rails convention for files like this is config/initializers. Thats where I put mine and I called it monkey_patches.rb

I would avoid using `config/initializers` and opt for adding something to `spec/support` as @Vasfed has suggested as this will ensure load orders are not compromised.  Using an initializer did not work for me due to some libraries being loaded later than the initializer.

**Comment by mattheworiordan** [comment]
> The Rails convention for files like this is config/initializers. Thats where I put mine and I called it monkey_patches.rb

I would avoid using `config/initializers` and opt for adding something to `spec/support` as @Vasfed has suggested as this will ensure load orders are not compromised.  Using an initializer did not work for me due to some libraries being loaded later than the initializer.

**Comment by Jecoms** [comment]
Are there additional fixes needed for this monkey patch to work for rails 4.2 + ruby 2.7?

**Comment by danielricecodes** [comment]
> > The Rails convention for files like this is config/initializers. Thats where I put mine and I called it monkey_patches.rb
> 
> I would avoid using `config/initializers` and opt for adding something to `spec/support` as @Vasfed has suggested as this will ensure load orders are not compromised. Using an initializer did not work for me due to some libraries being loaded later than the initializer.

Ahhh of course.  This only affects the `test` environment!  Great correction.  I'll correct my original comment as well in case people are finding this thread via search.

**Comment by x-yuri** [comment]
The summary is, there are 2 preconditions here, that if satisfied lead to the error. Rails < 5 reuses (recycles) [`ActionController::TestResponse` objects][1] in [tests][5]. [Starting with Ruby 2.6.0][3] `MonitorMixin` has a guard code that raises an exception if its [`initialize` method is called twice][2]. And in Ruby 2.7.0 they renamed the [`@mon_mutex*` variables][4].

> Are there additional fixes needed for this monkey patch to work for rails 4.2 + ruby 2.7?

So the revised workaround is:

```ruby
# a workaround to avoid MonitorMixin double-initialize error
if Gem::Version.new(RUBY_VERSION) >= Gem::Version.new('2.6.0')
  if Gem::Version.new(Rails.version) < Gem::Version.new('5.0.0')
    class ActionController::TestResponse < ActionDispatch::TestResponse
      def recycle!
        if Gem::Version.new(RUBY_VERSION) >= Gem::Version.new('2.7.0')
          @mon_data = nil
          @mon_data_owner_object_id = nil
        else
          @mon_mutex = nil
          @mon_mutex_owner_object_id = nil
        end
        initialize
      end
    end
  else
    $stderr.puts "Monkeypatch for ActionController::TestResponse is no longer needed"
  end
end
```

Although, I'm considering switching to Ruby 2.6.0, since with Rails 4 and Ruby 2.7.0 the tests' output is swarmed with warnings.

[1]: https://github.com/rails/rails/commit/2b5d309aeb#diff-600d5368b55e46ed961abb4295977ac3L78-L80
[2]: https://bugs.ruby-lang.org/issues/15000?tab=changesets
[3]: https://github.com/ruby/ruby/commit/1eba8ecb66#diff-abcaf64fd274b3e9f1a2ff6ba8f73820R259
[4]: https://github.com/ruby/ruby/commit/caac5f777a#diff-5721376d6552f0650a0c040bd1c8aa48R241-R242
[5]: https://github.com/rails/rails/blob/v4.2.11.3/actionpack/lib/action_controller/test_case.rb#L617

**Comment by lilole** [comment]
In case there are still poor souls on Rails 4.2 with Ruby 2.6/2.7, this is the full file working for my team, required from `rails_helper.rb`.

```ruby
# From https://github.com/rails/rails/issues/34790
#
# This is required because of an incompatibility between Ruby 2.6 and Rails 4.2, which the Rails team is not going to fix.

rb_version = Gem::Version.new(RUBY_VERSION)

if rb_version >= Gem::Version.new('2.6') && Gem::Version.new(Rails.version) < Gem::Version.new('5')
  if ! defined?(::ActionController::TestResponse)
    raise "Needed class is not defined yet, try requiring this file later."
  end

  if rb_version >= Gem::Version.new('2.7')
    puts "Using #{__FILE__} for Ruby 2.7."

    class ActionController::TestResponse < ActionDispatch::TestResponse
      def recycle!
        @mon_data = nil
        @mon_data_owner_object_id = nil
        initialize
      end
    end

    class ActionController::LiveTestResponse < ActionController::Live::Response
      def recycle!
        @body = nil
        @mon_data = nil
        @mon_data_owner_object_id = nil
        initialize
      end
    end

  else
    puts "Using #{__FILE__} for Ruby 2.6."

    class ActionController::TestResponse < ActionDispatch::TestResponse
      def recycle!
        @mon_mutex = nil
        @mon_mutex_owner_object_id = nil
        initialize
      end
    end

    class ActionController::LiveTestResponse < ActionController::Live::Response
      def recycle!
        @body = nil
        @mon_mutex = nil
        @mon_mutex_owner_object_id = nil
        initialize
      end
    end

  end
else
  puts "#{__FILE__} no longer needed."
end
```

**Comment by arshekas** [comment]
Hello everyone, 
Hope you are all good!

We added this and our RSpec tests seems to run fine which is good

```
if RUBY_VERSION>='2.6.0'
  if Rails.version < '5'
    class ActionController::TestResponse < ActionDispatch::TestResponse
      def recycle!
        # hack to avoid MonitorMixin double-initialize error:
        @mon_mutex_owner_object_id = nil
        @mon_mutex = nil
        initialize
      end
    end
  else
    puts "Monkeypatch for ActionController::TestResponse no longer needed"
  end
end
```

However, we are experiencing the error below while running cucumber feature tests. 

```
Feature: Address
  A user should be able to manage addresses

  Background:            # features/admin/address.feature:4
    Given I am logged in # features/step_definitions/session_steps.rb:1
      undefined method `<<' for #<Hash:0x00007f7c7dc4b908>
      Did you mean?  < (NoMethodError)
      ./features/step_definitions/session_steps.rb:4:in `/^I am logged in$/'
      features/admin/address.feature:5:in `Given I am logged in'
      /Users/arsh/.rbenv/versions/2.6.6/lib/ruby/2.6.0/net/protocol.rb:264:in `writing'
      /Users/arsh/.rbenv/versions/2.6.6/lib/ruby/2.6.0/net/protocol.rb:247:in `write'
      /Users/arsh/.rbenv/versions/2.6.6/lib/ruby/2.6.0/net/http/generic_request.rb:335:in `write_header'
 ```
session_steps.rb
```
Given (/^I am logged in$/) do
  user = FactoryGirl.create(:user)

  visit '/session/new'

  fill_in 'Email', with: user.email
  fill_in 'Password', with: 'password'

  click_button('Submit')
end
```
address.feature
```
Feature: Address
  A user should be able to manage addresses

  Background:
    Given I am logged in
   ```
   
Here are the tests gems and versions we are using
     
    ruby '2.6.6'
    'rails', '4.2.10
    
    gem 'rspec-rails', '~> 3.4.2'
    gem 'guard-rspec'
    gem 'factory_girl', '4.5.0'
    gem 'capybara', '2.5.0'
    gem 'capybara-webkit'
    gem 'selenium-webdriver', '2.53.0'
    gem 'chromedriver-helper'
    gem 'cucumber-rails', '1.4.3', require: false
    gem 'rspec_junit_formatter'
    gem 'database_cleaner', '1.5.1'
     
     
     We tried updating gems versions related to the cucumber and changing some configurations, but we have had no luck. 
     Any help would be appreciated!
     
     Thanks

**Comment by jpa57** [comment]
Thanks @lilole .  I'm one of those poor souls.   In a project with Jruby 9.3.10.0 which is Ruby 2.6.8, the code in monitor.rb is looking at @mon_data, and worse, it's checking with `if defined?(@mon_data)` instead of `if(@mon_data)` so the solution that got me past the ThreadError is shorter because I don't need older support any more:
```ruby
rb_version = Gem::Version.new(RUBY_VERSION)

if rb_version >= Gem::Version.new('2.6.8') && Gem::Version.new(Rails.version) < Gem::Version.new('5')
  if ! defined?(::ActionController::TestResponse)
    raise "Needed class is not defined yet, try requiring this file later."
  end


    puts "Using #{__FILE__} to workaround thread already initialized"
    class ActionController::TestResponse < ActionDispatch::TestResponse
      def recycle!
        remove_instance_variable(:@mon_data) if defined?(@mon_data)
        remove_instance_variable(:@mon_data_owner_object_id ) if defined?(@mon_data_owner_object_id)
        initialize
      end
    end

    class ActionController::LiveTestResponse < ActionController::Live::Response
      def recycle!
        remove_instance_variable(:@body ) if defined?(@body)
        remove_instance_variable(:@mon_mutex) if defined?(@mon_mutex)
        remove_instance_variable(:@mon_data) if defined?(@mon_data)
        remove_instance_variable(:@mon_mutex_owner_object_id) if defined?(@mon_mutex_owner_object_id)
        initialize
      end
    end

else
  puts "#{__FILE__} no longer needed."
end
```
Having said that, due to some unfortunate dependencies on Devise, we're dropping our controller specs going forward.   At least that's today's plan.  I haven't tested the LiveTestResponse version -- not sure it's even close to be honest.
