### ISSUE TITLE
BUG in 5.1 and 5.2 test: Mysql adapter count number of deleted rows outside of @lock.synchronize block

### ISSUE THREAD

**Issue by mqchau** [rails/rails#34798]
### Steps to reproduce
Run a selenium test that has puma server with 2+ thread.
The test must turn on `use_transactional_tests = true`. This PR #28083 made running selenium test in transaction possible.

Thread 1: `Comment.delete_all`
Thread 2: `Post.create!`

Both threads try to obtain locks at https://github.com/rails/rails/pull/28083/files#diff-c226a4680f86689c3c170d4bc5911e96R610 simultaneously. 

Thread 1 wins and execute and release the lock. Thread 2 obtains the lock later and execute.

### Expected behavior
Both thread finishes successfully.

### Actual behavior
Thread 1 runs into Mysql exception at 
https://github.com/rails/rails/blob/96dee0e7e5a8dd6ce42999b13d0bd0623073e229/activerecord/lib/active_record/connection_adapters/mysql/database_statements.rb#L45

### The issue
The statement `@connection.affected_rows` is executed outside of the lock obtained from https://github.com/rails/rails/pull/28083/files#diff-c226a4680f86689c3c170d4bc5911e96R610 
So by the the time thread 1 wants to count the number of deleted comment, the connection is already used by thread 2 to create post.

### Proposed solution
Wrap function https://github.com/rails/rails/blob/96dee0e7e5a8dd6ce42999b13d0bd0623073e229/activerecord/lib/active_record/connection_adapters/mysql/database_statements.rb#L45
in a block of `@lock.synchronize`

### System configuration
**Rails version**: 5.1 or 5.2
**Ruby version**: 2.3.3
**Database**: MySQL 5.6

**Comment by efiguerc** [comment]
Hi there,

I'm experiencing exactly this same behaviour, so trying to bring more light to the problem, I hit this running feature specs using capybara, the problem happens intermittently, and as you can see below, adding to the thesis of a race condition, it happens when trying to update the number of rows affected.

Also, I can confirm that implementing the suggested change in [PR#34800](https://github.com/rails/rails/pull/34800) works for me.

gems/2.5.0/gems/rails-5.2.2
gems/2.5.0/gems/activerecord-5.2.2
gems/2.5.0/gems/capybara-3.12.0
gems/2.5.0/gems/rspec-3.8.0
gems/2.5.0/gems/rspec-rails-3.8.2

```
Some feature spec running
Capybara starting Puma...
* Version 3.12.0 , codename: Llamas in Pajamas
* Min threads: 0, max threads: 4
* Listening on tcp://127.0.0.1:40597
2019-01-24 08:28:11 -0600: Rack app error handling request { POST /some/route }
Mysql2::Error
/.../lib/ruby/gems/2.5.0/gems/activerecord-5.2.2/lib/active_record/connection_adapters/mysql/database_statements.rb:45:in `affected_rows'
/.../lib/ruby/gems/2.5.0/gems/activerecord-5.2.2/lib/active_record/connection_adapters/mysql/database_statements.rb:45:in `block in exec_delete'
/.../lib/ruby/gems/2.5.0/gems/activerecord-5.2.2/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:196:in `execute_and_free'
/.../lib/ruby/gems/2.5.0/gems/activerecord-5.2.2/lib/active_record/connection_adapters/mysql/database_statements.rb:45:in `exec_delete'
/.../lib/ruby/gems/2.5.0/gems/activerecord-5.2.2/lib/active_record/connection_adapters/abstract/database_statements.rb:162:in `update'
/.../lib/ruby/gems/2.5.0/gems/activerecord-5.2.2/lib/active_record/connection_adapters/abstract/query_cache.rb:21:in `update'
/.../lib/ruby/gems/2.5.0/gems/activerecord-5.2.2/lib/active_record/persistence.rb:195:in `_update_record'
/.../lib/ruby/gems/2.5.0/gems/activerecord-5.2.2/lib/active_record/persistence.rb:479:in `update_columns'
/.../app/models/some_model.rb:177:in 'some_method'
```

```
Failures:

  1) Some feature spec
     Failure/Error:
       update_columns(
         one_column:      user.id,
         other_column:    Time.zone.now
       )
     
     Mysql2::Error:
```

**Comment by harmdewit** [comment]
We're experiencing a similar issue with the same issue in feature specs although with the addition of `database_cleaner` with truncation (probably no longer necessary now transactions are supported). The error occurs randomly, probably because of the race condition. The PR seems to fix it.



```
rails (5.1.6.1)
activerecord (= 5.1.6.1)
capybara (3.4.2)
rspec (3.7.0)
rspec-rails (3.7.2)
capybara (3.4.2)
database_cleaner (1.7.0)
```

Relevant config:

```ruby
  config.use_transactional_fixtures = true

  config.after(:each, type: :feature)do
    DatabaseCleaner.clean_with(:truncation)
  end
```

Error trace:

```
Failures:

  1) Logging in using two-factor authentication succeeds when entering a valid code
     Failure/Error: DatabaseCleaner.clean_with(:truncation)
     Mysql2::Error:
     # /Users/harm.dewit/.gem/ruby/2.4.5/gems/activerecord-5.1.6.1/lib/active_record/connection_adapters/mysql/database_statements.rb:43:in `affected_rows'
     # /Users/harm.dewit/.gem/ruby/2.4.5/gems/activerecord-5.1.6.1/lib/active_record/connection_adapters/mysql/database_statements.rb:43:in `block in exec_delete'
     # /Users/harm.dewit/.gem/ruby/2.4.5/gems/activerecord-5.1.6.1/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:223:in `execute_and_free'
     # /Users/harm.dewit/.gem/ruby/2.4.5/gems/activerecord-5.1.6.1/lib/active_record/connection_adapters/mysql/database_statements.rb:43:in `exec_delete'
     # /Users/harm.dewit/.gem/ruby/2.4.5/gems/activerecord-5.1.6.1/lib/active_record/connection_adapters/abstract/database_statements.rb:140:in `update'
     # /Users/harm.dewit/.gem/ruby/2.4.5/gems/activerecord-5.1.6.1/lib/active_record/connection_adapters/abstract/query_cache.rb:17:in `update'
     # /Users/harm.dewit/.gem/ruby/2.4.5/gems/activerecord-5.1.6.1/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:182:in `disable_referential_integrity'
     # /Users/harm.dewit/.gem/ruby/2.4.5/gems/database_cleaner-1.7.0/lib/database_cleaner/active_record/truncation.rb:235:in `clean'
     # /Users/harm.dewit/.gem/ruby/2.4.5/gems/database_cleaner-1.7.0/lib/database_cleaner/base.rb:48:in `clean_with'
     # /Users/harm.dewit/.gem/ruby/2.4.5/gems/database_cleaner-1.7.0/lib/database_cleaner/configuration.rb:91:in `block in clean_with'
     # /Users/harm.dewit/.gem/ruby/2.4.5/gems/database_cleaner-1.7.0/lib/database_cleaner/configuration.rb:91:in `each'
     # /Users/harm.dewit/.gem/ruby/2.4.5/gems/database_cleaner-1.7.0/lib/database_cleaner/configuration.rb:91:in `clean_with'
     # ./spec/spec_helper.rb:76:in `block (2 levels) in <top (required)>'

``

**Comment by cjlarose** [comment]
This problem causes flakiness in my application's system test suite after migrating to use transaction tests there.

My colleague @moyuanhuang and I applied this patch in an initializer (based on @mqchau's PR) and it seems to have fixed the issue for us.

```ruby
module DatabaseStatementsSynchronizedUpdateAndDelete
  def exec_delete(sql, name = nil, binds = [])
    if without_prepared_statement?(binds)
      execute_and_free(sql, name) do
        @lock.synchronize { @connection.affected_rows }
      end
    else
      exec_stmt_and_free(sql, name, binds) { |stmt| stmt.affected_rows }
    end
  end
  alias :exec_update :exec_delete
end

ActiveRecord::ConnectionAdapters::Mysql2Adapter.prepend DatabaseStatementsSynchronizedUpdateAndDelete
```
