### ISSUE TITLE
ActiveRecord wants to force a GROUP when none is needed.

### ISSUE THREAD

**Issue by iandouglas** [rails/rails#34793]
### Steps to reproduce

postgresql table via migration looks like this:
```ruby
     create_table :order_items do |t|
      t.references :order, foreign_key: true
      t.references :item, foreign_key: true

      t.integer :quantity
      t.decimal :price
      t.boolean :fulfilled, default: false

      t.timestamps
    end
```

Ultimate goal here is to use an item_id in that table to calculate how long it took to "fulfill" that item by subtracting the timestamp fields if the fulfilled boolean field is set to true.

postgresql query:
```
select avg(updated_at - created_at) from order_items where item_id=98 and fulfilled='t';
          avg
------------------------
 4 days 18:24:00.000046
```

What I would expect would work as ActiveRecord in an instance method of my Item class:
```ruby
def average_fulfillment_time
  OrderItem.select("avg(updated_at - created_at) as avg_f_time").where(item: self, fulfilled: true)
end
```
... or some other combination that utilizes the has_many between the instance of my item and its many order_items entries, something like:
`self.order_items..select("avg(updated_at - created_at) as avg_f_time").where(fulfilled: true)`

### Expected behavior

I would expect that the ActiveRecord parser would examine the use of `avg` in the ActiveRecord commands above, realize no GROUP BY is needed since the common data is found in the item_id in the where clause, execute the query, and return a single row showing me the average in string format as postgresql would generate it as I pasted above.

### Actual behavior

ActiveRecord's parsing ends up requiring a GROUP BY on the primary key `id` column, which in this scenario makes no sense. (if I add `.group(:id)` the following error goes away, but then nothing gets averaged)

```
OrderItem.select("avg(updated_at - created_at) as avg_f_time").where(item: self, fulfilled: true).first
ActiveRecord::StatementInvalid: PG::GroupingError: ERROR:  column "order_items.id" must appear in the GROUP BY clause or be used in an aggregate function
LINE 1: ...= 152 AND "order_items"."fulfilled" = $1 ORDER BY "order_ite...
                                                             ^
: SELECT  avg(updated_at - created_at) as avg_f_time FROM "order_items" WHERE "order_items"."item_id" = 152 AND "order_items"."fulfilled" = $1 ORDER BY "order_items"."id" ASC LIMIT $2
from /Users/id/.rbenv/versions/2.4.5/lib/ruby/gems/2.4.0/gems/activerecord-5.1.6.1/lib/active_record/connection_adapters/postgresql_adapter.rb:616:in `async_exec'
Caused by PG::GroupingError: ERROR:  column "order_items.id" must appear in the GROUP BY clause or be used in an aggregate function
LINE 1: ...= 152 AND "order_items"."fulfilled" = $1 ORDER BY "order_ite...
                                                             ^

from /Users/id/.rbenv/versions/2.4.5/lib/ruby/gems/2.4.0/gems/activerecord-5.1.6.1/lib/active_record/connection_adapters/postgresql_adapter.rb:616:in `async_exec'
[3] pry(#<Item>)> exit
```

### System configuration
**Rails version**: 5.1.6

**Ruby version**: 2.4.5p335 (2018-10-18 revision 65137) [x86_64-darwin16]

**Comment by iandouglas** [comment]
As an aside, you can do something like this:
`OrderItem.where(fulfilled: true, item: self).average("updated_at - created_at")` which actually generates the correct SQL query:
`SELECT AVG(updated_at - created_at) FROM "order_items" WHERE "order_items"."fulfilled" = $1 AND "order_items"."item_id" = 97`
but this AR command chain returns a numeric value indicating a number of days only, and loses the resolution of hours, minutes and seconds. Instead of a string of "4 days 18:24:00.000046" we'd get back "4" which isn't accurate enough for our needs.

**Comment by phoet** [comment]
@iandouglas did you work around this issue? i'm currently working on upgrading to 6.0.0.rc2 and had some tests failing. it looks like `FinderMethods.first` was updated to order the columns by default. so a very simple example that fails looks like this:


```ruby
User.select('min(created_at)').first.min
#  User Load (0.9ms)  SELECT  min(created_at) FROM "users" ORDER BY "users"."id" ASC LIMIT  $1  [["LIMIT", 1]]
# ActiveRecord::StatementInvalid (PG::GroupingError: ERROR:  column "users.id" must appear in # the GROUP BY clause or be used in an aggregate function)
# LINE 1: SELECT  min(created_at) FROM "users" ORDER BY "users"."id" A...
#                                                       ^
# : SELECT  min(created_at) FROM "users" ORDER BY "users"."id" ASC LIMIT $1
```
```ruby
User.select('min(created_at)').to_a.first.min
#  User Load (0.5ms)  SELECT min(created_at) FROM "users"
# => 2019-07-12 12:00:27 UTC
```

**Comment by iandouglas** [comment]
@phoet No, we never found a workaround in 5.1. Calling `.to_a` to convert to an array would return all items, where `.first` chained to the `.select` call in my example would issue a `.limit(1)` on the return (I wonder if you substituted a limit call instead of to_a would work for you in v6?). Also, if you've converted to an array and grabbed the first thing, the `.min` in your workaround would be iterating over a single item to find that minimum thing.

**Comment by phoet** [comment]
calling `.to_a` always returns 1 result in this case because of the `min()` function. this is also just an example for some more complicated `select` call from within a library.

**Comment by phoet** [comment]
@iandouglas it looks like there was a workaround prior to `6.0.0.rc2` which was to use `.reorder('')` i created a gist to show the regression https://gist.github.com/phoet/f393635dfd78f31c9dec8ce36a231236

**Comment by iandouglas** [comment]
@phoet interesting, thanks for the gist.

I still see this as a bit of a kludge though, having to force an override of an otherwise-absent `.order` call by chaining `.reorder` first. :)

**Comment by phoet** [comment]
and it will stop working with rc2, so not a really good kludge

**Comment by AlexBrodianoi** [comment]
i found this issue in rails 6.0.2.1
