### ISSUE TITLE
ActionController::ParamsWrapper#process_action catches too many errors

### ISSUE THREAD

**Issue by gmcgibbon** [rails/rails#34811]
In https://github.com/rails/rails/pull/34341, we made `ActionController::ParamsWrapper` catch all exceptions in its override of `#process_action`. This can cause unexpected behaviour if we accidentally catch an error we aren't expecting (like an interrupt).

I think we need to refactor the `ensure return super` part of `ActionController::ParamsWrapper#process_action` by using an explicit `rescue` for parameter parsing errors instead.

**Comment by JoshCheek** [comment]
Makes sense, I also like the proposed solution based on a quick look @ the code.

**Comment by hahmed** [comment]
If it's all good, I don't mind taking this as my first contribution to rails.

**Comment by gmcgibbon** [comment]
@hahmed Please feel free to submit a patch. Thanks!

**Comment by Atul9** [comment]
@gmcgibbon I have opened up a PR for this - #34883
