### ISSUE TITLE
Rails 6.0 alpha install issue with ruby 2.5.3p105

### ISSUE THREAD

**Issue by kirantpatil** [rails/rails#34815]
### Steps to reproduce
$ git clone --depth 1 https://github.com/rails/rails

$ ruby rails/railties/exe/rails new fooapp --dev

### Expected behavior
New rails project with folder fooapp should create.

### Actual behavior

> $ ruby rails/railties/exe/rails new fooapp --dev
> Traceback (most recent call last):
> 	8: from ./rails/railties/exe/rails:10:in `<main>'
> 	7: from /home/smitha/.rvm/rubies/ruby-2.5.3/lib/ruby/site_ruby/2.5.0/rubygems/core_ext/kernel_require.rb:54:in `require'
> 	6: from /home/smitha/.rvm/rubies/ruby-2.5.3/lib/ruby/site_ruby/2.5.0/rubygems/core_ext/kernel_require.rb:54:in `require'
> 	5: from /home/smitha/Documents/kiran/rails/railties/lib/rails/cli.rb:12:in `<top (required)>'
> 	4: from /home/smitha/.rvm/rubies/ruby-2.5.3/lib/ruby/site_ruby/2.5.0/rubygems/core_ext/kernel_require.rb:54:in `require'
> 	3: from /home/smitha/.rvm/rubies/ruby-2.5.3/lib/ruby/site_ruby/2.5.0/rubygems/core_ext/kernel_require.rb:54:in `require'
> 	2: from /home/smitha/Documents/kiran/rails/railties/lib/rails/command.rb:8:in `<top (required)>'
> 	1: from /home/smitha/.rvm/rubies/ruby-2.5.3/lib/ruby/site_ruby/2.5.0/rubygems/core_ext/kernel_require.rb:54:in `require'
> /home/smitha/.rvm/rubies/ruby-2.5.3/lib/ruby/site_ruby/2.5.0/rubygems/core_ext/kernel_require.rb:54:in `require': cannot load such file -- thor (LoadError)

### System configuration
$ rails -v
bash: rails: command not found

$ ruby -v
ruby 2.5.3p105 (2018-10-18 revision 65156) [x86_64-linux]

$ bundler --version
Bundler version 1.17.3

**Comment by y-yagi** [comment]
As the error indicates, I think that installation of gem is insufficient. 
Please run bundle install on clone repository and try again.

**Comment by kirantpatil** [comment]
Yes, bundle install resolved the issue.

**Comment by kirantpatil** [comment]
Yay! I am on rails 6! 

Rails 6 and Ruby 6  :1st_place_medal: :vulcan_salute: 

Thank you and Happy new year in advance.

![screenshot from 2018-12-28 15-34-18](https://user-images.githubusercontent.com/1178055/50512091-33bf2000-0ab6-11e9-8bab-91f99e19fbb3.png)
