### ISSUE TITLE
ActiveStorage::InvariableError when given an HEIC image

### ISSUE THREAD

**Issue by dwightwatson** [rails/rails#34821]
### Steps to reproduce
This is likely similar in fashion to #34698 but opened a second issue in case it's different.

Current iPhones in certain circumstances will output photos taken in a format with the extension `.HEIC`. This format still appears to have the standard image type.

To reproduce grab an `.HEIC` file and upload it into an app, then call `variable?` on it and also attempt to generate a variant.

From my quick Googling it doesn't look like ImageMagick supports `.HEIC` and progress on adding it has been slow. So I suspect `variable?` may need to take into file suffixes into account?

### Expected behavior
I call `@attachment.variable?` on a blob that is a `.HEIC` file and it returns false. I won't attempt to call `@attachment.variant(...)` on it.

### Actual behavior
I call `@attachment.variable?` on a blob that is a `.HEIC` file and it returns true. I attempt to call `@attachment.variant(...)` on it and get an `ActiveStorage::InvariableError`.

### System configuration
**Rails version**: 5.2.2

**Ruby version**: 2.5.3

**Comment by lucianosousa** [comment]
According to [caniuse.com](https://caniuse.com/#feat=heif) none browser support this extension, even Safari(this image is generated only by iPhone these days)
I'm not sure how ActiveStorage is supposed to deal with it, but we are gonna to ended up with an image not rendered by any browser if this extension is added as valid one

**Comment by georgeclaghorn** [comment]
I can’t reproduce this in Chrome or Safari. When I upload a HEIC file, the new blob’s content type is `image/heif` and `ActiveStorage::Blob#variable?` returns false.

Do you have a particular image that causes the unexpected behavior? What browser are you using to upload it? What’s the resulting blob’s content type?

**Comment by dwightwatson** [comment]
I no longer have the original uploaded file because we deleted it. 

I just tried with a HEIC file I pulled from my iPhone and it worked as expected (`variable?` returns false, it doesn't try to generate a variant). 

I suppose the original file that caused this issue on our end may have been wonky in some way.

Thanks for getting back to me, sorry about the noise.
