### ISSUE TITLE
Documentation on ActiveRecord::Associations::CollectionProxy could be clearer

### ISSUE THREAD

**Issue by richiethomas** [rails/rails#34829]
### Steps to reproduce
Navigate to [the RDoc documentation for the ActiveRecord::Associations::CollectionProxy class](https://api.rubyonrails.org/v5.0/classes/ActiveRecord/Associations/CollectionProxy.html).  Compare the documentation with that found on the [ActiveRecord::Associations::AssociationProxy](https://apidock.com/rails/ActiveRecord/Associations/AssociationProxy) page.  It appears to overlap quite heavily, perhaps implying that the CollectionProxy docs actually describe the AssociationProxy class.

### Expected behavior
It might be helpful to replace the current lead paragraph with a description of the CollectionProxy class itself.

Alternatively (or perhaps additionally), the docs could explain the relationship between association proxies and the CollectionProxy class, specifically that the CollectionProxy instance contains an `@association` instance variable, which itself includes `@owner`, `@target`, and `@reflection`.  Additionally, some example code (such as the example below) could be added to the docs, making it clearer how to access these instance variables from the `ActiveRecord::Associations::CollectionProxy` class:

```
class Post < ApplicationRecord
  has_many :comments do
    def number_five
      if @association.owner.is_a? Post
	Comment.where(id: 5, post: self)
      end
    end
  end
end
```

The above code can be workshopped to a more canonical example of `@association`'s usage in the real-world.  But hopefully this at least gives an idea of the change that this issue report is intended to suggest.

### Actual behavior
[The RDoc documentation for the ActiveRecord::Associations::CollectionProxy class](https://api.rubyonrails.org/v5.0/classes/ActiveRecord/Associations/CollectionProxy.html) begins by describing the definition and usage of association proxies.  I would expect this page to begin by explicitly describing the CollectionProxy class.  As the page currently reads, it's not clear to me what the connection is between CollectionProxy and association proxies.  Indeed, it appears that this documentation duplicates some of the info found on the [ActiveRecord::Associations::AssociationProxy](https://apidock.com/rails/ActiveRecord/Associations/AssociationProxy) page.

For context, this issue report sprung from a discussion on [this StackOverflow post](https://stackoverflow.com/questions/53974500/why-is-my-call-to-owner-in-a-has-many-relationship-not-working/53974860#53974860).

### System configuration
**Rails version**: verified on docs for Rails versions 5.0 and 5.2.

**Ruby version**: not applicable

NOTE- I'm happy to take this issue and submit a PR as well.

**Comment by gmcgibbon** [comment]
The page on apidock you're referencing applies to Rails 3.0. You shouldn't use apidock for anything, we don't own it and its hopelessly out of date. AFAICT [`ActiveRecord::Associations::Association`](https://github.com/rails/rails/blob/bb75d68fe2262199a16973c09a8b2749542c7590/activerecord/lib/active_record/associations/association.rb#L20) (private API) and [`ActiveRecord::Associations::CollectionProxy`](https://github.com/rails/rails/blob/bb75d68fe2262199a16973c09a8b2749542c7590/activerecord/lib/active_record/associations/collection_proxy.rb#L32) are the two modern equivalent classes.

Further, resorting to using `@association` in your models isn't encouraged as its an implementation detail. I would recommend using ActiveRecord scopes instead decorating an association with methods.

I don't see the same issues in the current docs, so I'm going to close this. Please let me know if I've missed something, or you have issues with the current docs. Thank you for reporting!
