### ISSUE TITLE
ActiveRecord::Base#dup does not include dynamic attributes

### ISSUE THREAD

**Issue by urkle** [rails/rails#34823]
### Steps to reproduce

```ruby
# give MyModel which simply has id:pk, field:string, and timestamp fields
records = MyModel.group(:field).select(:field, Arel.sql('count(*) as total'))
record = records.first
puts record.to_json
# output: {"id":null,"field":"one", "total": 1}
n = record.dup
puts n.to_json
# output: {"id":null,"field: "one","created_at":null,"updated_at":null}
```

### Expected behavior
in Rails 4.2.x duplicating the record would retain/dup the "selected" attributes
Thus the second puts would output
```ruby
puts n.to_json
# output: {"id":null,"field":"one", "total": 1}
```

### Actual behavior

lib/active_record/core.rb#initialize_dup correctly duplicates the `@attributes` (as it did in Rails 4.2.x)
However
lib/active_model/dirty.rb#initialize_dup is obliterating the already duplicated by only pulling in fields defined in the MyModel._default_attributes

### System configuration
**Rails version**:
5.2.2
**Ruby version**:
2.4.3

**Comment by urkle** [comment]
Yes this still occurs on 5-2-stable. I've already included details on where the offending code is.. Right now we have resorted to manually handling duping because of the broken rails AR code.

**Comment by rafaelfranca** [comment]
Since you know where the offending code is, what do you thing about opening a PR?

**Comment by urkle** [comment]
@rafaelfranca I can do that sometime next week.

**Comment by urkle** [comment]
This is still an issue.. Just unsure on how to cleanly address it with all the layered modules in AR.

**Comment by urkle** [comment]
Yes this is still a valid issue as rails 6 has not changed the dup behavior.

Would an acceptable fix for this be to have a guard in the #dirty module that the AR dup can flip to prevent the dirty duplication from running ?

**Comment by rafaelfranca** [comment]
Can we just dup the dirty state?

**Comment by urkle** [comment]
> Can we just dup the dirty state?

Not exactly sure what you mean by this.

So right now with an AR model we have two places that dup the attributes.. AR::Core does a simple deep_dup

https://github.com/rails/rails/blob/master/activerecord/lib/active_record/core.rb#L396

And then AM::Dirty it only duplicates _default_attributes (which is just the schema defined keys)
https://github.com/rails/rails/blob/master/activemodel/lib/active_model/dirty.rb#L130

So what happens is #dirty's initialize_dup calls super (which eventually chains up to AR::Core#initialize_dup which does the proper deep_dup only to then completely replace it with only the schema defined attributes of the model.

So it's not the dirty state even..   It's really that teh AM::Dirty#initialize_dup is only duplicating defined columns instead of all attributes.

So my thinking was to have AM::Dirty provide a means to allow AR::Core to set some state so that AM::DIrty will know "ok I din't nee to dup attributes as someone else already did"

Another approach would be to fully extract out the attribute duplicating functionality to another concern in AM that does it simply the deep_dup way (so only one place is doing the dup) and remove it from AR::Core and AM::Dirty.

**Comment by rafaelfranca** [comment]
If the deep does the proper thing, why we need the remaining of dirty?

**Comment by urkle** [comment]
@rafaelfranca So I dug in a little more and added a test for the scenario.

( added to activerecord/test/cases/dup_test.rb
```ruby
    def test_dup_with_custom_attributes
      topic = Topic.select('topics.*, 1 as extra').first
      duped = topic.dup
      assert_respond_to topic, :extra, 'Original responds to extra'
      assert_respond_to duped, :extra, 'Duplicate responds to extra'
    end
```

Doing my naive quick fix that simply "skips" the dup going on in AM::Dirty yes passes that test but completely breaks other tests. Specifically test_dup_with_changes in that same test suite.

Why?

Because the deep_dup literally just deep dups, thus the context of "has this attribute changes" is also copied.  So all attributes end up being treated as not changed. 

And due to the initialization order the AR::Core#initialize_dup does extra work after the attribute duplication.

I'm going to push up a PR and link it here with what I have right now and do a fixup commit adjusting to another possible way to handle things so the "changes" functionality works correctly.

**Comment by urkle** [comment]
@rafaelfranca I pushed up the PR for comments from you.

**Comment by urkle** [comment]
Yes this is still an issue.  I've rebased the PR against master.

**Comment by urkle** [comment]
I re-rebased the branch against master

**Comment by urkle** [comment]
This is still an issue.
