### ISSUE TITLE
Remote form submit requests not rendering response when there's validation errors

### ISSUE THREAD

**Issue by budu** [rails/rails#34839]
### Steps to reproduce

Build a new Rails app with a simple scaffold:

```
rails new testapp
cd testapp
rails g scaffold User name:string
rails db:create
rails db:migrate
rails s
```

Modify generated form to remove `local: true` option.

Add validation to the model: `validates :name, presence: true`

Create a new user without a name.

### Expected behavior

It should render the response. 

The request is properly sent and the response is the one expected.

### Actual behavior

It does nothing.

### System configuration

**Rails version**: 5.2.2
**Ruby version**: 2.5.3

**Comment by budu** [comment]
The issue is coming from turbolinks as described in this issue: https://github.com/turbolinks/turbolinks/issues/85

The (temporary) solution is to include a third-party gem by https://github.com/jorgemanrubia as explained in that comment: https://github.com/turbolinks/turbolinks/issues/85#issuecomment-398191163

**Comment by y-yagi** [comment]
Thanks for your report. But this is not Rails's issue.  I'm closing.

**Comment by shanecav84** [comment]
I think this is a Rails issue. Rails includes Turbolinks by default which breaks error message rendering on failed form submissions. Either Rails should not include Turbolinks, or Rails should update UJS to properly integrate with Turbolinks.
