### ISSUE TITLE
[Rails 6 alpha] Sprockets::FileNotFound 

### ISSUE THREAD

**Issue by kirantpatil** [rails/rails#34840]
### Steps to reproduce
1) Create Rails 6 app
2) yarn add onsenui
3) Add below lines to "app/assets/stylesheets/application.css"
     
```
     *= require onsenui/css/onsenui
     *= require onsenui/css/onsen-css-components
```
4) Create a sample view as below

```
<ons-page>
  <div style="text-align: center; margin-top: 30px;">
    <p>
      <ons-input id="username" modifier="underbar" placeholder="Username" float></ons-input>
    </p>
    <p>
      <ons-input id="password" modifier="underbar" type="password" placeholder="Password" float></ons-input>
    </p>
    <p style="margin-top: 30px;">
      <ons-button onclick="login()">Sign in</ons-button>
    </p>
  </div>
</ons-page>
```
 
5) Access that page 

### Expected behavior
Page should render without error.

### Actual behavior

> $ rails s
> => Booting Puma
> => Rails 6.0.0.alpha application starting in development 
> => Run `rails server --help` for more startup options
> Puma starting in single mode...
> * Version 3.12.0 (ruby 2.5.3-p105), codename: Llamas in Pajamas
> * Min threads: 5, max threads: 5
> * Environment: development
> * Listening on tcp://0.0.0.0:3000
> Use Ctrl-C to stop
> Started GET "/pages/auth" for 127.0.0.1 at 2019-01-02 12:17:55 +0530
>    (5.7ms)  SELECT sqlite_version(*)
> Processing by PagesController#auth as HTML
>   Rendering pages/auth.html.erb within layouts/application
>   Rendered pages/auth.html.erb within layouts/application (Duration: 2.9ms | Allocations: 350)
> Completed 500 Internal Server Error in 377ms (ActiveRecord: 0.0ms | Allocations: 287951)
> 
> 
>   
> ActionView::Template::Error (couldn't find file 'onsenui/css/onsenui' with type 'text/css'
> Checked in these paths: 
>   /home/smitha/Documents/kiran/fooapp/app/assets/config
>   /home/smitha/Documents/kiran/fooapp/app/assets/images
>   /home/smitha/Documents/kiran/fooapp/app/assets/stylesheets
>   /home/smitha/Documents/kiran/rails/actioncable/app/assets/javascripts
>   /home/smitha/Documents/kiran/rails/activestorage/app/assets/javascripts
>   /home/smitha/Documents/kiran/rails/actionview/app/assets/javascripts
>   /home/smitha/.rvm/gems/ruby-2.5.3/gems/turbolinks-source-5.2.0/lib/assets/javascripts):
>      5:     <%= csrf_meta_tags %>
>      6:     <%= csp_meta_tag %>
>      7: 
>      8:     <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
>      9:     <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
>     10:   </head>
>     11: 
>   
> app/assets/stylesheets/application.css:14
> app/views/layouts/application.html.erb:8
> 

### Screenshot from browser
![screenshot from 2019-01-02 12-31-17](https://user-images.githubusercontent.com/1178055/50582737-99caef00-0e8a-11e9-973f-1216f8b51aa0.png)

### System configuration
**Rails version**: Rails 6.0.0.alpha

**Ruby version**: ruby 2.5.3p105

**Comment by y-yagi** [comment]
Please use the [mailing list](https://groups.google.com/forum/#!forum/rubyonrails-talk) or StackOverflow for questions/help, where a wider community will be able to help you. We reserve the issues tracker for issues only. Thanks.

**Comment by kirantpatil** [comment]
I raised this issue here, since it is working in Rails 5.2.1.

**Comment by kirantpatil** [comment]
Resolved the issue by adding "Rails.application.config.assets.paths << Rails.root.join('node_modules')" to config/initializers/assets.rb

**Comment by kartik362** [comment]
> Resolved the issue by adding "Rails.application.config.assets.paths << Rails.root.join('node_modules')" to config/initializers/assets.rb

thanks brother. I was also getting same error.
