### ISSUE TITLE
ActiveRecord Calculations average returns 0 instead of `nil` when there are no rows

### ISSUE THREAD

**Issue by johannesluedke** [rails/rails#34850]
### Steps to reproduce
```
Person.average(:age) 
```
on a table with no rows

### Expected behavior
returns `nil` https://apidock.com/rails/ActiveRecord/Calculations/average

### Actual behavior
returns `0.0`

### System configuration
**Rails version**: 5.1.6.1

**Ruby version**: 2.6.0

## Note

I think the reason could be this commit in bigdecimal https://github.com/ruby/bigdecimal/commit/3d1bdee3766b7eb611a2d845012f0eedaa3a790c#diff-a94632d0c7a3bcb163ce0724c2785ca1 

because ActiveRecord checks for `respond_to?(:to_d)` which returns false on a rails console in ruby 2.5.1 but true on 2.6.0

**Comment by albertoalmagro** [comment]
@johannesluedke I can take over this if you want to.

**Comment by albertoalmagro** [comment]
@johannesluedke it will return `nil` as it did before and as you expected it to be 😉 Thanks for reporting this 👍

**Comment by Blaze34** [comment]
1. When it'll be released? 
2. Will 5.1 contain this fix?
Thanks
