### ISSUE TITLE
Unexpected behaviour of `class_attribute` from `ActiveSupport`

### ISSUE THREAD

**Issue by emilioforrer** [rails/rails#34868]
### Steps to reproduce

`class_attribute` is sharing the reference from the parent class.

Check this comparison against `Uber::Inheritable Attr` 

```ruby
class A
  class_attribute :form_action_clasess
  self.form_action_clasess = {
    create: 'CreateForm',
    update: 'UpdateForm'
  }
end

class B < A
  self.form_action_clasess[:create] = 'Custom'
end

class C < A
  
end

class A1
  extend Uber::InheritableAttr
  inheritable_attr :form_action_clasess

  self.form_action_clasess = {
    create: 'CreateForm',
    update: 'UpdateForm'
  }
end

class B1 < A1
  self.form_action_clasess[:create] = 'Custom'
end

class C1 < A1
  
end

puts 'A subclasses:', A.form_action_clasess.inspect, B.form_action_clasess.inspect, C.form_action_clasess.inspect, 'A1 subclasses', A1.form_action_clasess.inspect, B1.form_action_clasess.inspect, C1.form_action_clasess.inspect

# Output:
# A subclasses:
# {:create=>"Custom", :update=>"UpdateForm"}
# {:create=>"Custom", :update=>"UpdateForm"}
# {:create=>"Custom", :update=>"UpdateForm"}
# A1 subclasses
# {:create=>"CreateForm", :update=>"UpdateForm"}
# {:create=>"Custom", :update=>"UpdateForm"}
# {:create=>"CreateForm", :update=>"UpdateForm"}
```

### Expected behavior

A subclasses:

{:create=>"CreateForm", :update=>"UpdateForm"}
{:create=>"Custom",        :update=>"UpdateForm"}
{:create=>"CreateForm", :update=>"UpdateForm"}

### Actual behavior

A subclasses:

{:create=>"Custom", :update=>"UpdateForm"}
{:create=>"Custom", :update=>"UpdateForm"}
{:create=>"Custom", :update=>"UpdateForm"}

### System configuration
**Rails version**: 5.2.1

**Ruby version**: 2.5.3

**Comment by rafaelfranca** [comment]
Thank you for the issue. This is the expected behavior. Unless you set the value of a `class_attribute` in the subclasses they do share the value of the superclass.
