### ISSUE TITLE
comparing time attributes against date ranges needs casting 

### ISSUE THREAD

**Issue by foonlyboy** [rails/rails#34895]
### System configuration
**Rails version**:

**Ruby version**:

**Comment by rafaelfranca** [comment]
You need to give us more information on how to reproduce this issue, otherwise there is nothing we can do. Please read CONTRIBUTING.md file for more information about creating bug reports. Thanks!

**Comment by foonlyboy** [comment]
Comparing a database column of sql type TIME against a Range of (Date .. Date)
does not work as expected.

I use postgresql wit Rails 5.1

Example:
`  where(created_at: (Date.today .. Date.today))
`
returns nothing, while the expected behaviour would be to return all records created today.

It translates to SQL:
`WHERE ("user"."created_at" BETWEEN '2019-01-08' AND '2019-01-08')
`
The database converts the DATE arguments to TIME, both becoming 2019-01-08T00:00:00,
leading to no records being found.

This is all correct behaviour on everyone involved, but it leads to unexpected results.

There are 3 ways around this:
- extend the end of the Range by one day
  but then the Range would be wrong on the ruby side

- convert the Range to Time on the ruby side
  workable, but this can have subtle effects due to local time and time zone changes
this would translate to SQL:

- CAST the database TIME attribute to DATE on the database side
  `WHERE (CAST("user"."created_at" AS DATE) BETWEEN '2019-01-08' AND '2019-01-08')
  `

But I fear any such change would break existing code.

While I was playing around with this, one solution came to my mind:
`where(cast(:created_at,Date) => (Date.today .. Date.today))
`

which should translate to:
  `WHERE (CAST("user"."created_at" AS DATE) BETWEEN '2019-01-08' AND '2019-01-08')
  `

I believe this could be quite straight forward and should not break legacy code.

The cast() method would return a new class like CastedAttribute,
which would need to be handled all down the line down to Arel to build the SQL,
but I believe this is doable.
Please let me know if there already is such a feature in Arel anyways?

Maybe, there are even more use cases for a feature like this,
when we want to modify the *left* side of the WHERE clause?

Obviously all this can be done with resorting to plain sql,
but it would be nice to have this builtin.

**Comment by foonlyboy** [comment]
Hi rafael,
you closed it while I was still writing.

I later came up with that suggestion to enrich the *left* side of the where(),
and I still believe that to be a good idea.

**Comment by rafaelfranca** [comment]
What you described seems to be the expected behavior at Active Record, given the SQL generated is correct by the data provided, so we can't consider this an issue.

The third way around it seems like a good idea to introduce as public API but we don't take feature requests in the issue tracker. Arel right now is private API of the framework and we don't recommend people to use it, so while the casting function could be something we support in the framework its usage is too niche right now to require a public API for it.

Thank you for the issue.

**Comment by foonlyboy** [comment]
Hi  Rafael,

The best of the thing that you told me: Arel is not a public api in Rails.

All that query api is bitched up, laden with loads of legacy.

It works quite well for simple queries,
but it's not up to the task, when queries get more complex.

I never got Arel -- nobody ever got Arel.

I worked a lot with WebObjects,
maybe there is still something to be learned from that?

anyways
new year is a good year
https://www.youtube.com/watch?v=4cia_v4vxfE
