### ISSUE TITLE
Rails 6.0.0.alpha - ActionText - couldn't find file 'trix/dist/trix' with type 'text/css'

### ISSUE THREAD

**Issue by petermumford** [rails/rails#34897]
After installing actiontext from your guides with the following command `rails action_text:install` I get the below error.

```
ActionView::Template::Error (couldn't find file 'trix/dist/trix' with type 'text/css'
Checked in these paths:
  /Users/petermumford/code/buzzy/app/assets/config
  /Users/petermumford/code/buzzy/app/assets/images
  /Users/petermumford/code/buzzy/app/assets/stylesheets
  /Users/petermumford/.rbenv/versions/2.6.0/lib/ruby/gems/2.6.0/bundler/gems/rails-29bb990f9781/actioncable/app/assets/javascripts
  /Users/petermumford/.rbenv/versions/2.6.0/lib/ruby/gems/2.6.0/bundler/gems/rails-29bb990f9781/activestorage/app/assets/javascripts
  /Users/petermumford/.rbenv/versions/2.6.0/lib/ruby/gems/2.6.0/bundler/gems/rails-29bb990f9781/actionview/app/assets/javascripts
  /Users/petermumford/.rbenv/versions/2.6.0/lib/ruby/gems/2.6.0/gems/turbolinks-source-5.2.0/lib/assets/javascripts
  /Users/petermumford/code/buzzy/node_modules):
     5:     <%= csrf_meta_tags %>
     6:     <%= csp_meta_tag %>
     7:
     8:     <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
     9:     <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    10:   </head>
    11:
```
I found this issue #rails/actiontext/issues/40, which was closed a few days ago and the solution is what I've got. However, I've noticed in my yarn.lock file actiontext doesn't have any dependencies and I would expect Trix to be one? Trix also doesn't appear in my `node_modules` folder. The version of actiontext seems to be wrong as well?

```
"actiontext@https://github.com/rails/actiontext":
  version "0.0.0"
  resolved "https://github.com/rails/actiontext#b67ab5bc62c630c6d58c49eaa2282e186431d760"
```

### System configuration
**Rails version**: 6.0.0.alpha
**Ruby version**: 2.6.0

**Comment by georgeclaghorn** [comment]
Yarn resolved [rails/actiontext](https://github.com/rails/actiontext) to the [commit](b67ab5bc62c630c6d58c49eaa2282e186431d760) where the source code was removed. Until the first beta release scheduled for next week, you can install from the old repository’s archive branch:

```shell
$ yarn add https://github.com/rails/actiontext#archive
```

**Comment by rafaelfranca** [comment]
Closing since this will be fixed in the beta release.

**Comment by georgeclaghorn** [comment]
Update: @javan published an alpha release of the [@rails/actiontext](https://www.npmjs.com/package/@rails/actiontext) NPM package. You can use that instead of pinning to the archive branch of the old repository.
