### ISSUE TITLE
Metum is not a word.

### ISSUE THREAD

**Issue by CodyEngel** [rails/rails#34914]
### Steps to reproduce
'meta'.singularize => 'metum'

### Expected behavior
'meta'.singularize => 'meta'

### Actual behavior
'meta'.singularize => 'metum'

### System configuration
Stemming from this post: https://github.com/emberjs/ember-inflector/issues/67

**Comment by rafaelfranca** [comment]
Thank you for the issue.

The current set of inflection rules is frozen. This means, we do not change them to become more complete or correct.

This is a safety measure to keep existing applications from breaking.
