### ISSUE TITLE
Wrong calculations with ActiveSupport::Duration

### ISSUE THREAD

**Issue by barbolo** [rails/rails#34920]
### Steps to reproduce

```ruby
Time.now - (1.hour / 2)
```

### Expected behavior
Evaluates to the `Time` corresponding to 30 minutes ago

### Actual behavior
Evaluates to current time (`Time.now`)

### System configuration
**Rails version**: 5.2.2

**Ruby version**: 2.4.4

**Comment by y-yagi** [comment]
Thanks for your report. This is duplicated with #33179. Let's track that issue.
You can avoid this issue by using `Float` instead of `Integer`. 

```ruby 
Time.now - (1.hour / 2.0)
```
