### ISSUE TITLE
Rails::Secrets.parse is giving NoMethodError: undefined method deep_symbolize_keys for Hash

### ISSUE THREAD

**Issue by smndiaye** [rails/rails#34929]
### Steps to reproduce
I have been facing a `NoMethodError: undefined method 'deep_symbolize_keys' for Hash` while rails secrets are being parsed (capistrano deploy). This error is occurring after upgrading i18n gem but it seems like it might be on `railties` side so please allow me to fill up an issue in here as well.

Steps to reproduce can be found here 👉[related issue url](https://github.com/ruby-i18n/i18n/issues/461)

### Expected behavior
parse rails secrets without error

### Actual behavior
```
NoMethodError: undefined method `deep_symbolize_keys' for #<Hash:0x00007fd2b49d5c40>
/Users/xxx/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/railties-5.1.6.1/lib/rails/secrets.rb:30:in `block in parse'
/Users/xxx/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/railties-5.1.6.1/lib/rails/secrets.rb:24:in `each'
/Users/xxx/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/railties-5.1.6.1/lib/rails/secrets.rb:24:in `each_with_object'
/Users/xxx/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/railties-5.1.6.1/lib/rails/secrets.rb:24:in `parse'
config/deploy.rb:45:in `<top (required)>'
/Users/xxx/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/capistrano-3.11.0/lib/capistrano/setup.rb:27:in `load'
```
### System configuration
**Rails version**: 5.1.4

**Ruby version**: 2.5.3

**config/deploy.rb:45**: `set :secrets, Rails::Secrets.parse([Rails::Secrets.send(:path)],  env: fetch(:stage).to_s)`

**Comment by y-yagi** [comment]
`Rails::Secrets.parse` is private API. Please do not use it in an application. Thanks

**Comment by GeminPatel** [comment]
I am getting this same issue for a very simple line:

YAML.load_file('./config/infra.yml').deep_symbolize_keys

Says: NoMethodError: undefined method `deep_symbolize_keys' for #<Hash:0x00000001f1b0c0>

This is so confusing. It works in rails console.

My rails is 5.1.7 and ruby is 2.4.1
