### ISSUE TITLE
Migration: change column type from text to text[]

### ISSUE THREAD

**Issue by ThomBian** [rails/rails#34938]
### Steps to reproduce
```ruby
class CreateErrorTable < ActiveRecord::Migration[5.2]
  def up
    create_table :error_tables do |t|
      t.text :column_text, default: 'rails,ruby'
    end

    change_column :error_tables, :column_text, :text, array: true, default: [], using: "(string_to_array(column_text, ','))"
  end

  def down
    drop_table :error_tables
  end
end
```

### Expected behavior
Serializes properly the `default` value into an array. 

### Actual behavior
This raises  a `Can't quote Array` error.

### Note
This seems to work fine in 5.1. (I have migrations that run with this syntax)

### System configuration
**Rails version**: 5.2

**Ruby version**:  2.5.3

**Comment by robzolkos** [comment]
Can confirm this behaviour (although this migration doesn't run in 5.1 either)

5.1.6.1 errors message `PG::DatatypeMismatch: ERROR:  default for column "column_text" cannot be cast automatically to type text[]`

5.2.2 error message `TypeError: can't quote Array`

It's possible this isn't a Rails bug but more a Postgres type casting issue with default - the following steps do work

1.  remove the default from the column _before_ changing the type
2.  change the type
3. add the new default in

The following migration _does_ work.

```
class CreateErrorTable < ActiveRecord::Migration[5.2]
  def up
    create_table :error_tables do |t|
      t.text :column_text, default: 'rails,ruby'
    end

    # remove the default from the existing table
    change_column_default(:error_tables, :column_text, nil)

    # change the column type and convert existing data
    change_column :error_tables, :column_text, :text, array: true, using: "(string_to_array(column_text, ','))"

    # add defaults in (or put [] if you just want a blank array)
    change_column_default(:error_tables, :column_text, ['rails', 'ruby'])
  end

  def down
    drop_table :error_tables
  end
end
```

**Comment by marceloperini** [comment]
@robzolkos @ThomBian this error happens with SQLite to. I think it's really a Rails bug.
