### ISSUE TITLE
expires_in and expires_now should use no-store instead of no-cache

### ISSUE THREAD

**Issue by luisenrike** [rails/rails#34942]
The problem is that `expires_now` and `expires_in` are doing `Cache-Control: no-cache`, they should do `Cache-Control: no-store` instead.

According to https://apidock.com/rails/ActionController/ConditionalGet/expires_now 

**expires_now()**

> Sets a HTTP 1.1 Cache-Control header of no-cache so no caching should occur by the browser or intermediate caches (like caching proxy servers).

but when using `no-cache` the browser will use the cached resource if the ETag is the same

From https://developers.google.com/web/fundamentals/performance/optimizing-content-efficiency/http-caching

> "no-cache" indicates that the returned response can't be used to satisfy a subsequent request to the same URL without first checking with the server if the response has changed. As a result, if a proper validation token (ETag) is present, no-cache incurs a roundtrip to validate the cached response, but can eliminate the download if the resource has not changed.

`no-store` it's a better fit for `expires_now`

> By contrast, "no-store" is much simpler. It simply disallows the browser and all intermediate caches from storing any version of the returned response—for example, one containing private personal or banking data. Every time the user requests this asset, a request is sent to the server and a full response is downloaded.

![51202026-b1af6380-18cb-11e9-8944-ee4187b9e3d3_png__png_image__919 x 300_pixels_](https://user-images.githubusercontent.com/12720974/51202643-3353c100-18cd-11e9-8c33-b2d8193d8414.png)

### Steps to reproduce

1. Create a new rails project (`rails new demo`)
2. Create a home controller

When inspecting with the chrome's developer console make sure to uncheck the "Disable cache" checkbox.
```
class HomeController < ApplicationController
  def a
    expires_now
    render html: "A"
  end

  def b
    render html: "B"
  end
end
```
3. Add these routes
```
  root "home#a"
  get "/b", to: "home#b"
```

4. Go to http://localhost:3000
5. Go to http://localhost:3000/b
6. Click the browser's back button

### Expected behavior
The browser shouldn't use the cached version of `a`

### Actual behavior
The browser is serving `a` from the disk cache

### System configuration
**Rails version**: 5.2.2

**Ruby version**: ruby 2.5.0p0 (2017-12-25 revision 61468) [x86_64-darwin17]

**Comment by gmcgibbon** [comment]
Apidock is highly outdated and we don't own it. Please don't use it. According to the [current documentation](https://api.rubyonrails.org/v5.2.2/classes/ActionController/ConditionalGet.html#method-i-expires_now):

`
Sets an HTTP 1.1 Cache-Control header of no-cache. This means the resource will be marked as stale, so clients must always revalidate. Intermediate/browser caches may still store the asset.
`

This seems aligned to the behaviour that you are seeing. Though, there doesn't seem to be support for using `no-store` and `no-cache` in these methods. I wouldn't be against seeing and option for that like we do for `must-revalidate`.
