### ISSUE TITLE
ActionDispatch default headers are not sent with API mode

### ISSUE THREAD

**Issue by mengu** [rails/rails#34940]
### Steps to reproduce
```ruby
# frozen_string_literal: true

require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  gem "rails", "5.2.2"
end

require "rails"
require "action_controller/railtie"

class TestApp < Rails::Application
  config.load_defaults 5.2

  config.root = __dir__
  secrets.secret_key_base = "secret_key_base"

  config.logger = Logger.new($stdout)
  Rails.logger  = config.logger

  config.action_dispatch.default_headers = {
    'X-Frame-Options' => 'DENY'
  }

  config.api_mode = true

  routes.draw do
    get "/" => "test#index"
  end
end

class TestController < ActionController::API
  include Rails.application.routes.url_helpers

  def index
    render plain: "Home"
  end
end

require "minitest/autorun"
require "rack/test"

class BugTest < Minitest::Test
  include Rack::Test::Methods

  def test_returns_failure
    get "/"
    assert last_response.ok?
    assert last_response.headers.include? 'X-Frame-Options'
  end

  private
    def app
      Rails.application
    end
end

```

### Expected behavior
`ActionDispatch::Response.default_headers` are present in responses sent when using `ActionController::Base` however they are not when using `ActionController::API`.  [this pr](https://github.com/rails/rails/pull/32484/files) was merged for this work on april 2018.

### Actual behavior
X-Frame-Options header set in the config is not present in response headers.

### System configuration
**Rails version**: Rails 5.2.0 & Rails 5.2.2

**Ruby version**: Ruby 2.5.1 & Ruby 2.6.0

**Comment by y-yagi** [comment]
This is a problem of the bug report templates. 
`default_headers` sets in initializer process, but bug report templates not called it.  
This issue does not occur in the real application. I confirmed with a [sample applicationtion](https://github.com/y-yagi/default_header_with_api). Thanks.

**Comment by y-yagi** [comment]
Oh, sorry. Your point is correct. I misunderstood. I will investigate.

**Comment by y-yagi** [comment]
OK. That feature added in Rails 6.0.0. 
I updated to sample application to 6.0.0.beta1 and it works expected.

```bash
$ curl -I localhost:3000/users
HTTP/1.1 200 OK
X-Frame-Options: DENY
Content-Type: application/json; charset=utf-8
ETag: W/"4f53cda18c2baa0c0354bb5f9a3ecbe5"
Cache-Control: max-age=0, private, must-revalidate
X-Request-Id: b64fc845-3b11-4644-b916-0817bc64ee84
X-Runtime: 0.023213 
```
