### ISSUE TITLE
Fallback to unprepared statement does not check for `in_clause_length`

### ISSUE THREAD

**Issue by wpolicarpo** [rails/rails#34945]
rails#33878 allowed `ActiveRecord` to fallback to unprepared statements if `bind_params_length ` was reached, but it does not consider if `in_clause_length` limit was also reached.

### Steps to reproduce

Imagine that a 3rd party adapter has the following configuration:

- `bind_params_length` = `2_000`
- `in_clause_length` = `10_000`

If you execute a query like the one below, `ActiveRecord` will fallback to unprepared statements because `bind_params_length` was reached, but it would fail because `in_clause_length` was also reached.

```ruby
MyModel.where(id: (1..20_000).to_a)
```
### Expected behavior

I'm not sure, to be honest. Should we try to identify such cases and fail fast or it should be the user responsibility to deal with it?

### System configuration
**Rails version**: `>= 5.2.2`
**Ruby version**: `any`

**Comment by tommeier** [comment]
Note for others: this also affects other more implied calls such as `Model.includes(:other_association)`
