### ISSUE TITLE
Sometime channel not updating UI/Not receiving message on Production(Heroku)

### ISSUE THREAD

**Issue by Bhalani** [rails/rails#34957]
### Steps to reproduce
--

### Expected behavior
Should Receive message from broadcaster to subscriber everytime.

### Actual behavior
I'm facing issue on production.
Sometime channel don't receive message/update UI.

I don't see any error on browser console or rails log.
Production is on Heroku.(Is there any issue ActionCable on Heroku?)

Just need help to implement something to get the log/error message when it's not updating the UI.
Is there any way to achieve that?

### System configuration
2 web dynos (Puma)
2 worker dynos
1 Encoding workers

**Rails version**:
5.2.2

**Ruby version**:
2.5.3

**Comment by rafaelfranca** [comment]
Can you please provide a sample application that reproduces the error?

**Comment by Bhalani** [comment]
Even I'm trying to reproduce it for three days but the thing is I can not reproduce it in my local environment.

and not even producing on production everytime, sometime users reporting me that the page neither getting update nor error message.

I'm not getting any error in Bug Monitor.

If there is any way I can trace the failure of broadcasting/receiving I can store the system usage/ server log and can get if it's coding  *side issue or server side or memory issue*.

**Comment by rafaelfranca** [comment]
Have you tried to attach some bug monitor to the javascript in the client side?

**Comment by Bhalani** [comment]
Nope, I didn't tried.

I'm not even sure that if the issue is on subscriber(JS) side or Publisher side(Backend).

**Comment by rafaelfranca** [comment]
Unfortunately there is no much we can help. If we can't reproduce or at least know what is broken we can't fix or help.

**Comment by Bhalani** [comment]
Suppose the message get broadcasted, can we check if that is delivered to the receiver or not?

**Comment by Bhalani** [comment]
Will try to implement on javascript side If I can get something will add here, but not 100% sure if that is case or channel get busy.

Would like to know if there is any limits of number of channel at a time can receive the message or data size of message?

**Comment by Bhalani** [comment]
What I can to implement the WebSocket Fallback in this case, may that can help me.
