### ISSUE TITLE
Nested includes with active storage

### ISSUE THREAD

**Issue by yanshney** [rails/rails#34950]
Hi guys,

Thank you for all your work!
For some reason I can't think about the best way to solve the following problem: I have a list of messages and next to each message I display its sender's (user's) profile image. Each message belongs to a user. A profile image is attached to each user using active_storage's has_one_attached :image. 

How would I  query the database so it would get me all the messages so that each message would include its user and its user's profile photo? 

Thank you,
Yan

**Comment by y-yagi** [comment]
Please use the [mailing list](https://groups.google.com/forum/#!forum/rubyonrails-talk) or StackOverflow for questions/help, where a wider community will be able to help you. We reserve the issues tracker for issues only. Thanks.
