### ISSUE TITLE
Unexpected argument passed to generator

### ISSUE THREAD

**Issue by jcoyne** [rails/rails#34979]
### Steps to reproduce

I believe this change: https://github.com/rails/rails/commit/f173ec77fc35ce57e94398310308e868689366bb#diff-5036eb99239f9418c0458f2a2ec4f496R228
introduced a regression whereby `RAILS_ENV=test` is added as an argument to the generator.  This is only apparent if the generator uses arguments.  One generator that does so is the `devise` generator. See https://github.com/plataformatec/devise/issues/5007

### Expected behavior

It should not pass RAILS_ENV as an argument to the generator

### Actual behavior

it is passing RAILS_ENV as an agrument

### System configuration
**Rails version**: 6.0.0.beta1

**Ruby version**: 2.6.0

**Comment by y-yagi** [comment]
Thanks for your report. I will fix.
