### ISSUE TITLE
Redirect to ActiveStorage backed attachment fails with "Unsafe redirect"

### ISSUE THREAD

**Issue by Masa331** [rails/rails#34987]
### Steps to reproduce
Setup User model with ActiveStorage backed avatar attachment configured to be stored on some other host than where app is running. So not local but AWS or Azure etc. Link to this file with `url_for(@user.avatar)`. Visit the generated url.

I created a repo with freshly generated Rails 6.0.0.beta1 app which demonstrates it [here](https://github.com/Masa331/redirect_bug_reproduce). It's prepared to store avatars on AWS but whoever would want to try it has to setup his AWS account in `config/storage.yml`...
To see the problem create yourself a user with some avatar. The avatar should be visible on the user's show page but it's not.

### Expected behavior
App redirects/shows to user avatar image.

### Actual behavior
App fails with `ArgumentError "Unsafe redirect"` from "actionpack (6.0.0.beta1) lib/action_controller/metal/redirecting.rb:128:in `block in _compute_safe_redirect_to_location'"
![screenshot_2019-01-19 action controller exception caught](https://user-images.githubusercontent.com/4116146/51432443-54534380-1c38-11e9-889a-bb6a79b7243f.png)

### System configuration
**Rails version**: 6.0.0.beta1

**Ruby version**: 2.6

I think the problem is from recent change to `actionpack/lib/action_controller/metal/redirecting.rb` in this [commit](https://github.com/rails/rails/commit/9dde7d8de047b55ec636c4c7cba89ec95324d492#diff-1b71368a5be51400d75dda0a5a0b9409) where it seems to me it's now explicitly needed to state that redirect is allowed other hosts. And since the option is not set in https://github.com/rails/rails/blob/master/activestorage/app/controllers/active_storage/blobs_controller.rb where ActiveStorage itself uses `redirect_to` to redirect to the original avatar on different host it fails.

**Comment by Masa331** [comment]
Erm it looks like somebody is already working on it: https://github.com/rails/rails/pull/34982

**Comment by Ramiro6** [comment]
I have the same problem when i use cdn

`Unsafe redirect "https://any.cloudfront.net/variants/"`

i didn't have this problem with the version '--edge actiontext' 😃 

**System configuration**

Rails version: 6.0.0.beta1
ruby 2.5.3

**Comment by georgeclaghorn** [comment]
Closing because #34982 has been merged.
