### ISSUE TITLE
New arel beta version for Rails 6.0.0.beta1

### ISSUE THREAD

**Issue by doits** [rails/rails#34983]
I want to try out newest Rails 6.0.0.beta1 in one of my (bigger) existing projects, though I get the following error:

```
rails aborted!
NoMethodError: undefined method `arel_node?' for Arel:Module
/.../.rbenv/versions/2.6.0/lib/ruby/gems/2.6.0/gems/activerecord-6.0.0.beta1/lib/active_record/attribute_methods.rb:188:in `block in disallow_raw_sql!'
```

I traced this down to `Arel` ([new helper was added](d0d1cd3d45f14e8423ee8ee3f4c19e999a69b96c)) and noticed it was merge into active record. I still have a gem though that depends on `Arel` explicitly ([pg_search](https://rubygems.org/gems/pg_search)).

I think what happens is that the latest released version of `Arel`, currently `9.0.0`, is used, instead of the one bundled with active record. But active record 6 needs this newer version.

Can you please release a beta version of arel with the latest changes, compatible to Rails 6?

**Comment by king601** [comment]
I'm also getting this in my Rails 5.2 app I tried to upgrade.

I can bypass this error by turning off the check for migrations in the development.rb

``` 
  config.active_record.migration_error = false # it was previously :page_load
```

**Comment by remomueller** [comment]
@nertzy made the changes here: https://github.com/Casecommons/pg_search/commit/90cd56442fe920cdc2f9411d80ad2159da22f98d

Looks like it'll be included in a future release for [pg_search](https://rubygems.org/gems/pg_search). For the meantime if you're testing upgrading to Rails 6.0.0.beta1, you can link to the latest commit for `pg_search` to get past the Arel error. I did the following in my `Gemfile` and it worked.

```
# gem "pg_search", "~> 2.1.3"
gem "pg_search", git: "git://github.com/Casecommons/pg_search.git", ref: "bd070786a014f6ea4f2767e0abd0d818861116ab"
```

**Comment by dbackeus** [comment]
We hit this error via explicit `arel` dependency in the `dossier` gem. It would at least be worth warning about this situation in the Rails 6.0 upgrade guide.
