### ISSUE TITLE
Errno::ENOENT: No such file or directory @ rb_file_s_mtime after feature tests

### ISSUE THREAD

**Issue by randoum** [rails/rails#34989]
When running feature Rspecs, I receive the following error (full trace at the bottom of this message)
```
Failure/Error: last_modified = ::File.mtime(path).httpdate
     
Errno::ENOENT:
No such file or directory @ rb_file_s_mtime - /path/to/rails/app/tmp/storage/va/ri/variants/FY3ZZxaPB7CUR2t98XnYRnqg/110e017d16925dc7c50728c9c154a420079aa6e5fcc435db3e6e97b1380ecec8
```

The error triggers after the tests, so I cannot associate it with some lines of my code. 

During the test a form is displaying an attached file like this : `= image_tag url_for(image.variant(resize: "120x120"))`. If I comment out this line, the error does not occur anymore. And If I do not use a variant, the error still occurs.

The trace indicates that `ActiveStorage::DiskController.serve_file` triggers the errors. Is it that ActiveStorage app is not shutting down gracefully ?

I'm using `active_storage.service = :test` configuration, but `:file` gives the same errors.

### System configuration
**Rails version**: 5.2.2

**Ruby version**: ruby 2.5.3p105 (2018-10-18 revision 65156) [x86_64-linux]

**Rbenv version**: rbenv 1.1.1-39-g59785f6

**Rspec related versions**: rspec 3.8.0 - capybara 3.12.0 - selenium-webdriver 3.141.0

### Full trace
```
     # /opt/rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/rack-2.0.6/lib/rack/file.rb:63:in `mtime'
     # /opt/rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/rack-2.0.6/lib/rack/file.rb:63:in `serving'
     # /opt/rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/activestorage-5.2.2/app/controllers/active_storage/disk_controller.rb:42:in `serve_file'
     # /opt/rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/activestorage-5.2.2/app/controllers/active_storage/disk_controller.rb:12:in `show'
     # /opt/rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/actionpack-5.2.2/lib/action_controller/metal/basic_implicit_render.rb:6:in `send_action'
     # /opt/rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/actionpack-5.2.2/lib/abstract_controller/base.rb:194:in `process_action'
     # /opt/rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/actionpack-5.2.2/lib/action_controller/metal/rendering.rb:30:in `process_action'
     # /opt/rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/actionpack-5.2.2/lib/abstract_controller/callbacks.rb:42:in `block in process_action'
     # /opt/rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/activesupport-5.2.2/lib/active_support/callbacks.rb:132:in `run_callbacks'
     # /opt/rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/actionpack-5.2.2/lib/abstract_controller/callbacks.rb:41:in `process_action'
     # /opt/rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/actionpack-5.2.2/lib/action_controller/metal/rescue.rb:22:in `process_action'
     # /opt/rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/actionpack-5.2.2/lib/action_controller/metal/instrumentation.rb:34:in `block in process_action'
     # /opt/rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/activesupport-5.2.2/lib/active_support/notifications.rb:168:in `block in instrument'
     # /opt/rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/activesupport-5.2.2/lib/active_support/notifications/instrumenter.rb:23:in `instrument'
     # /opt/rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/activesupport-5.2.2/lib/active_support/notifications.rb:168:in `instrument'
     # /opt/rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/actionpack-5.2.2/lib/action_controller/metal/instrumentation.rb:32:in `process_action'
     # /opt/rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/actionpack-5.2.2/lib/action_controller/metal/params_wrapper.rb:256:in `process_action'
     # /opt/rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/activerecord-5.2.2/lib/active_record/railties/controller_runtime.rb:24:in `process_action'
     # /opt/rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/actionpack-5.2.2/lib/abstract_controller/base.rb:134:in `process'
     # /opt/rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/actionview-5.2.2/lib/action_view/rendering.rb:32:in `process'
     # /opt/rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/actionpack-5.2.2/lib/action_controller/metal.rb:191:in `dispatch'
     # /opt/rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/actionpack-5.2.2/lib/action_controller/metal.rb:252:in `dispatch'
     # /opt/rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/actionpack-5.2.2/lib/action_dispatch/routing/route_set.rb:52:in `dispatch'
     # /opt/rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/actionpack-5.2.2/lib/action_dispatch/routing/route_set.rb:34:in `serve'
     # /opt/rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/actionpack-5.2.2/lib/action_dispatch/journey/router.rb:52:in `block in serve'
     # /opt/rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/actionpack-5.2.2/lib/action_dispatch/journey/router.rb:35:in `each'
     # /opt/rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/actionpack-5.2.2/lib/action_dispatch/journey/router.rb:35:in `serve'
     # /opt/rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/actionpack-5.2.2/lib/action_dispatch/routing/route_set.rb:840:in `call'
     # /opt/rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/rack-2.0.6/lib/rack/tempfile_reaper.rb:15:in `call'
     # /opt/rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/rack-2.0.6/lib/rack/etag.rb:25:in `call'
     # /opt/rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/rack-2.0.6/lib/rack/conditional_get.rb:25:in `call'
     # /opt/rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/rack-2.0.6/lib/rack/head.rb:12:in `call'
     # /opt/rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/actionpack-5.2.2/lib/action_dispatch/http/content_security_policy.rb:18:in `call'
     # /opt/rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/rack-2.0.6/lib/rack/session/abstract/id.rb:232:in `context'
     # /opt/rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/rack-2.0.6/lib/rack/session/abstract/id.rb:226:in `call'
     # /opt/rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/actionpack-5.2.2/lib/action_dispatch/middleware/cookies.rb:670:in `call'
     # /opt/rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/actionpack-5.2.2/lib/action_dispatch/middleware/callbacks.rb:28:in `block in call'
     # /opt/rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/activesupport-5.2.2/lib/active_support/callbacks.rb:98:in `run_callbacks'
     # /opt/rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/actionpack-5.2.2/lib/action_dispatch/middleware/callbacks.rb:26:in `call'
     # /opt/rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/actionpack-5.2.2/lib/action_dispatch/middleware/debug_exceptions.rb:61:in `call'
     # /opt/rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/actionpack-5.2.2/lib/action_dispatch/middleware/show_exceptions.rb:33:in `call'
     # /opt/rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/railties-5.2.2/lib/rails/rack/logger.rb:38:in `call_app'
     # /opt/rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/railties-5.2.2/lib/rails/rack/logger.rb:26:in `block in call'
     # /opt/rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/activesupport-5.2.2/lib/active_support/tagged_logging.rb:71:in `block in tagged'
     # /opt/rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/activesupport-5.2.2/lib/active_support/tagged_logging.rb:28:in `tagged'
     # /opt/rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/activesupport-5.2.2/lib/active_support/tagged_logging.rb:71:in `tagged'
     # /opt/rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/railties-5.2.2/lib/rails/rack/logger.rb:26:in `call'
     # /opt/rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/actionpack-5.2.2/lib/action_dispatch/middleware/remote_ip.rb:81:in `call'
     # /opt/rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/actionpack-5.2.2/lib/action_dispatch/middleware/request_id.rb:27:in `call'
     # /opt/rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/rack-2.0.6/lib/rack/method_override.rb:22:in `call'
     # /opt/rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/rack-2.0.6/lib/rack/runtime.rb:22:in `call'
     # /opt/rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/activesupport-5.2.2/lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'
     # /opt/rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/actionpack-5.2.2/lib/action_dispatch/middleware/executor.rb:14:in `call'
     # /opt/rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/actionpack-5.2.2/lib/action_dispatch/middleware/static.rb:127:in `call'
     # /opt/rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/rack-2.0.6/lib/rack/sendfile.rb:111:in `call'
     # /opt/rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/railties-5.2.2/lib/rails/engine.rb:524:in `call'
     # /opt/rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/rack-2.0.6/lib/rack/urlmap.rb:68:in `block in call'
     # /opt/rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/rack-2.0.6/lib/rack/urlmap.rb:53:in `each'
     # /opt/rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/rack-2.0.6/lib/rack/urlmap.rb:53:in `call'
     # /opt/rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/capybara-3.12.0/lib/capybara/server/middleware.rb:48:in `call'
     # /opt/rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/puma-3.12.0/lib/puma/configuration.rb:225:in `call'
     # /opt/rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/puma-3.12.0/lib/puma/server.rb:658:in `handle_request'
     # /opt/rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/puma-3.12.0/lib/puma/server.rb:472:in `process_client'
     # /opt/rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/puma-3.12.0/lib/puma/server.rb:332:in `block in run'
     # /opt/rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/puma-3.12.0/lib/puma/thread_pool.rb:133:in `block in spawn_thread'
     # 
     #   Showing full backtrace because every line was filtered out.
     #   See docs for RSpec::Configuration#backtrace_exclusion_patterns and
     #   RSpec::Configuration#backtrace_inclusion_patterns for more information.
     # ------------------
     # --- Caused by: ---
     # Capybara::CapybaraError:
     #   Your application server raised an error - It has been raised in your test code because Capybara.raise_server_errors == true
     #   /opt/rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/capybara-3.12.0/lib/capybara/session.rb:147:in `raise_server_error!'
```

**Comment by y-yagi** [comment]
Can you please provide a sample application that reproduces the issue?

**Comment by randoum** [comment]
Sorry I cannot. I tried but cannot reproduce the problem in a newly created application. 

Though after analyzing the logs I strongly assume there is a bug which is not coming from my code. I hope I'm right on that point. Anyhow perhaps we can figure this out together. Let me show you where I'm at:

**A** There are 4 tests running, and they all display one partial which displays one attachment. Here is the code I'm using:

```
- puts "view is displaying key #{f.object.blob.key}. Count: #{ActiveStorage::Blob.where(key: f.object.blob.key).count}"
= image_tag url_for(f.object)
```

Note : f.object is an ActiveStorage::Attachment

**B** in each of my 4 tests, I output to the console the name of the test, so we can see in the debug output where each test starts. That's for conveniency:

```
before { puts "========== STARTING TEST NUMBER 1"}
```

**C** In activestorage-5.2.2/app/controllers/active_storage/disk_controller.rb, in ActiveStorage::DiskController#show I added a debug output like so :

```
def show
  if key = decode_verified_key
    puts "-----\nAvailable keys: #{ActiveStorage::Blob.pluck :key}\nRef key=#{key} path=#{disk_service.path_for(key[:key])}"
    serve_file disk_service.path_for(key[:key]), content_type: key[:content_type], disposition: key[:disposition]
  else
    ...
```

And in ActiveStorage::DiskController#serve_file I added the following debug output:

```
def serve_file(path, content_type:, disposition:)
  puts "   serving #{path} - Exist ? #{File.exist? path}"
  Rack::File.new(nil).serving(request, path).tap do |(status, headers, body)|
    ...
```

**D** In activestorage-5.2.2/lib/active_storage/service/disk_service.rb, in ActiveStorage::Service::DiskService#delete I added the debug output:

```
instrument :delete, key: key do
  begin
    puts "Deleting file with key #{key}"
    File.delete path_for(key)
  rescue Errno::ENOENT
    ...
```
---
And here is the output: https://gist.github.com/randoum/66997bd4eca1d93d73760a7098dc808a

How come the DiskController is serving blobs with keys "Bu2uThFaTo6n8GEVvDStkSPP" and "ePXbFPbKERn1a1Jqwg3e6c8M" (lines 31 and 35 of my gist) ; given that was the form was displaying 2 attachments with different blob keys (lines 27 and 28)?

Is there some kind of cache issue ?

I'm sure of my code, I mean my form is displaying an attachment for which blob key exists in the database. But the DiskController is receiving a different key, which is a key that was existing in the previous test.

**Comment by randoum** [comment]
Yes https://github.com/randoum/as_bug

```
git clone git@github.com:randoum/as_bug.git
cd as_bug
bundle
bundle exec rake db:create
bundle exec rake db:migrate
bundle exec rspec
```

I advise you to display the key of the blob being served in ActiveStorage::DiskController#show because when the second test runs, the keys from the first tests are served. And as one of them was deleted (as in spec/features/product_spec.rb lines 14 and 24) the error triggers

**Comment by Nuru** [comment]
I would say this is more of an annoyance than an actual bug, but it is enough of an annoyance that maybe someone should come up with a standard workaround and publish it.

The issue is that the public URL for an attachment is based only on its `id` (database primary key), and in the course of running Rspecs, the database keeps getting reset and so attachments keep reusing IDs. This causes URLs to be reused but with different meaning, which is a problem because URLs are cached for the life of the service URL, which defaults to 5 minutes. 

- At the start of the test, and attachment is made.
- The browser fetches the URL for the attachment, which is a [blob URL](https://github.com/rails/rails/blob/7dd9916c0d5e5d149bdde8cbeec42ca49cf3f6ca/activestorage/config/routes.rb#L5) keyed only on `blob.id` and `filename`. `filename` is the sanitized file name and has nothing to do with the name of the file or whatever is storing the data. In radoum's case, `filename` is always `image.png`, and this is completely reasonable for a test.
- By design, ActiveStorage responds to the URL with a 302 redirect to a service URL where the browser can actually get the file. This lets the server generate a limited lifetime authenticated URL such as you might want to use to download a file from S3. By default, the lifetime of the service URL is 5 minutes, and the 302 is given a cache life of equal length (e.g. `Cache-Control: max-age=300`).
- With the Disk Service, the service URL is a [disk URL](https://github.com/rails/rails/blob/7dd9916c0d5e5d149bdde8cbeec42ca49cf3f6ca/activestorage/config/routes.rb#L9) keyed off the actual filename on disk, which is randomly generated. The browser caches the 302 redirect for 5 minutes, meaning that for the next 5 minutes, the browser will automatically replace that blob URL with that disk URL without contacting the server. 
- At the end of a test, the files are deleted and the database cleaned. 
- The next test recreates the just deleted URLs, recreating the blob URL. Unfortunately, the disk URL is not recreated but rather a new disk URL is generated.
- Now when the browser is served the reused blob URL it goes directly to the now invalid disk URL which generates a server error because the browser presented a valid signed unexpired URL but the Disk Service could not find the corresponding file. 


Off the top of my head, I think a reasonable solution would be to have an option to include the blob key or the attachment creation time in milliseconds in the generated URL, such option only to be used in test environments where IDs get rapidly reused. You can't just set the life of the service URL to 0 seconds because then it could be invalid by the time it is used.

**Comment by randoum** [comment]
Thanks to your input, I tested the solution to comment out the cache expiration statement in ActiveStorage::BlobsController#show, and all tests pass.

```
def show
  # expires_in ActiveStorage::Blob.service.url_expires_in
  redirect_to @blob.service_url(disposition: params[:disposition])
end
```

Submitted PR #35097 to propose a fix.

Cheers
