### ISSUE TITLE
Calling methods in .erb files can cause a confusing error when a parenthesis is missing

### ISSUE THREAD

**Issue by erose** [rails/rails#34995]
This issue is about the error message that you see when you write an html.erb template with a helper call that is missing a parenthesis, something like this:

```
<%= render(
  'test_partial',
   locals: {
    foo: 1,
    bar: 2,
   },
%>
```

Here the `render` call is missing a parenthesis. This is a real bug that afflicted me during development, leading to much confusion. I thought others might have encountered this before.

### Steps to reproduce
I've created a minimal example here (https://github.com/erose/rails-render-partial-gives-confusing-error-when-parenthesis-is-missing).

1. Clone the repository.
2. Run `rails s`.
3. Visit `localhost:3000/`. You should see the error screen.

### Expected behavior
Because the error is in code that I wrote, I'd expect to see an error message referring to the line that is missing a parenthesis, perhaps telling me where it expected to find the parenthesis.

### Actual behavior
Instead, I see the following error screen:

![image](https://user-images.githubusercontent.com/1514487/51441402-1ccbb200-1c9f-11e9-91f7-ac577147fa01.png)

While now that I know what the issue is, I can see why this screen would have been generated, at the time it was very confusing because 1) it refers to line 10 of `index.html.erb`, but that file only has 7 lines, and 2) it refers to `ensure`, but that's nowhere in the code I wrote.

### System configuration
**Rails version**:
Rails 5.2.2

**Ruby version**:
Ruby 2.5.1

I'm happy to work on a fix for this issue -- first I'd like to understand which project it should belong in. At first blush it seems like this might be in the domain of [erubi](https://github.com/jeremyevans/erubi), Rails's ERB engine, but that project doesn't appear to do any kind of error handling so I had a feeling it would be considered out of scope there. (I thought I might get more attention with this issue by asking it here, rather than there.)

Any guidance would be appreciated!

**Comment by erose** [comment]
Hi @hahmed -- with that advice, I can find that the source of the issue appears to be https://github.com/rails/rails/blob/master/actionview/lib/action_view/template.rb. (Although the `index.html.erb:12` doesn't refer to a real line in my code.)

My question is: is this kind of error something it's in the scope of Rails or Erubi to guard against? Or is it in the scope of neither?

**Comment by hahmed** [comment]
This error is raised from ruby when parsing your syntax.

**Comment by erose** [comment]
Yep. What I'm wondering is: is this something Rails *should* provide a friendly error message for?

**Comment by sikachu** [comment]
Yep, I think it's worth fixing.

The fix should probably have to be done on Rails side, as that error template you see is generated by Rails. I think we have enough information from Ruby exception to pinpoint which line is causing the error, and we should be able to rewrite the error message to be more friendly and showing the relevant code down there.

I'll be looking forward to your patch then. Let me know if we can be any help!

**Comment by erose** [comment]
Thanks @sikachu -- I'll see if I can make progress on catching and displaying the error more intelligently.

**Comment by erose** [comment]
Hey @sikachu -- I opened a PR here: https://github.com/rails/rails/pull/35308. Feedback welcome!
