### ISSUE TITLE
Undocumented feature in passing variables to partials

### ISSUE THREAD

**Issue by MSCAU** [rails/rails#35000]
According to the Guide (https://guides.rubyonrails.org/layouts_and_rendering.html#using-partials), this is the correct way to pass parameters to a partial:

`<%= render partial: "node", locals: {node: n} %>`

However, there is another way of doing so which is more elegant yet it is not documented:

`<%= render "node", node: n %>`

I see this in Rails 5.2. Is there any subtle difference between the two? If not, I would be grateful if the Guide were updated accordingly.

**Comment by hahmed** [comment]
There is a small snipped in that heading: `<%= render article, full: true %>`

**Comment by MSCAU** [comment]
Thanks, I see that. A passing reference is not the same as documenting the syntax fully.

**Comment by rafaelfranca** [comment]
The guides are not the only documentation. They are as the name say guides to guide you though features but they are not going to included every single option and every single possibility.

What you are looking for is here: http://api.rubyonrails.org/classes/ActionView/PartialRenderer.html

**Comment by MSCAU** [comment]
Thanks for the link, @rafaelfranca. I had never seen that page before. Is there any reason why this page also uses the more long-winded syntax? Given that Rails is all about code brevity, it is presumably a legacy syntax?

**Comment by rafaelfranca** [comment]
The reason is because it is explaining each option individually so it needs to use the options explicitly.
