### ISSUE TITLE
ActionText: silently fails without Yarn installed

### ISSUE THREAD

**Issue by sosodev** [rails/rails#35003]
Running `rails action_text:install` without Yarn installed throws no errors it just fails to load the assets on the client side later on. I'm assuming this is because `Rails new` checks for Yarn, but it isn't checked for whenever you upgrade from Rails 5.2.

**Comment by markvanlan** [comment]
I just installed ActionText, and image uploading is not working because I did not include the JS, and am not using webpacker on this application. There are no warnings that I saw, and it failed silently.

**Comment by ghiculescu** [comment]
I believe https://github.com/rails/rails/pull/35085/files#diff-f51857a740406dbabf716f431d1b2801e959f195a6ef1e4833fd35652eedfcb2R15-R16 would have fixed this. Closing based on that, but if it's still an issue let me know.
