### ISSUE TITLE
Add better external host security approach to redirect_to

### ISSUE THREAD

**Issue by gmcgibbon** [rails/rails#35019]
In https://github.com/rails/rails/pull/34412, we made a change to `redirect_to` that disallowed redirection to external hosts by default to mitigate risk of [open redirect attacks](https://www.owasp.org/index.php/Unvalidated_Redirects_and_Forwards_Cheat_Sheet). While more secure, this approach adds unwanted complexity for legitimate external host redirects. As this safety was meant primarily for the case where we want to redirect based on parameters from the user, we should evaluate an alternative approach that is more params-focused.

### TODO

- [x] Revert https://github.com/rails/rails/pull/34412
- [ ] Use strong parameters to permit external host redirection via params

**Comment by tegon** [comment]
Has anyone picked this up yet? I'm interested in working on it if not.

**Comment by gmcgibbon** [comment]
No work has been done (sorry, I had forgotten I assigned myself to this). There's more of a complete discussion on the problem in https://github.com/rails/rails/issues/39643, so I'm closing this issue in favour of that one.
