### ISSUE TITLE
Gitignore file for new Rails 6.0.0.beta1 app does not reference packs folder or node_modules folder 

### ISSUE THREAD

**Issue by murdoch** [rails/rails#35014]
### Steps to reproduce
Create a new rails 6.0.0.beta1 app with `rails new yolo`

### Expected behavior

Since webpacker is the default on Rails 6, I was expecting the .gitignore file to reference the `/node_modules` folder and any other webpacker/yarn related files/directories

i.e. it should contain:

/public/packs
/public/packs-test
/node_modules
/yarn-error.log
yarn-debug.log*
.yarn-integrity

### Actual behavior

The .gitignore file does not contain the mentioned files. Apologies if I've got this wrong.

### System configuration
**Rails version**: 6.0.0.beta1

**Ruby version**: 2.6

**Comment by murdoch** [comment]
Ahh thanks @bogdanvlviv , I think you've solved the riddle, `rails webpacker:install` was running in production environment for some reason. I think this will likely be my own fault, and not a rails bug. I'm closing the ticket. Thanks.

**Comment by ratahtatah** [comment]
@murdoch .gitignore should also include the `.yarn/` folder by default.

**Comment by jakeNiemiec** [comment]
If you see a `.yarn/` folder, you have the wrong version of yarn installed. Webpacker only works with `yarn@^1`
