### ISSUE TITLE
send_data not working as expected in IE11 with rails-5.2.0

### ISSUE THREAD

**Issue by Trupti-Baliga** [rails/rails#35013]
### Steps to reproduce

Code: `send_data SomeData, type: pdf, disposition: inline`

### Expected behavior

On the IE11 browser, this should ideally result in file getting downloaded and user seeing both OPEN and SAVE options. ( Works this way in rails-5.1.6.1)
<img width="987" alt="screen shot 2019-01-22 at 1 27 48 pm" src="https://user-images.githubusercontent.com/22428065/51520687-63a9db00-1e4a-11e9-96ef-efabbb574882.png">

### Actual behavior

User does NOT see the OPEN option. So, user has to navigate to file saved location and open it from there.  (works in this manner from rails-5.2.0 onwards)
<img width="986" alt="screen shot 2019-01-22 at 12 37 56 pm" src="https://user-images.githubusercontent.com/22428065/51520779-a23f9580-1e4a-11e9-8c17-25f9d564dca2.png">
<img width="1048" alt="screen shot 2019-01-22 at 1 24 24 pm" src="https://user-images.githubusercontent.com/22428065/51520788-a8ce0d00-1e4a-11e9-8187-4b64f8b2096e.png">

### System configuration
**Rails version**:
rails-5.2.0

**Ruby version**:
ruby-2.5

**Comment by runwaldarshu** [comment]
With rails 5.2.2 as well seeing the same issue

**Comment by Trupti-Baliga** [comment]
This issue persists only with the IE11 browser. 
Tested in other browsers like chrome and firefox, and it seems to be working as expected.

**Comment by rafaelfranca** [comment]
Rails generates standard HTTP headers. If something is not working in the browser it seems to be a problem in the browser. Can you please investigate why IE doesn't respect those standard headers?

**Comment by runwaldarshu** [comment]
So exact same code if we use rails 5.1.X IE-11 works as expected and with 5.2.X version IE-11 behaves differently so shouldn't there be some difference in the headers sent which made same browser behave differently with 2 different versions of rails ?

**Comment by Trupti-Baliga** [comment]
Here are the response headers and request headers:

RAILS-5.1.6.1
<img width="1680" alt="screen shot 2019-01-23 at 4 32 03 pm" src="https://user-images.githubusercontent.com/22428065/51657316-69c6c580-1fca-11e9-9d1e-8ffb4d72c625.png">


RAILS-5.2.0
<img width="1680" alt="screen shot 2019-01-23 at 3 49 47 pm" src="https://user-images.githubusercontent.com/22428065/51657329-7814e180-1fca-11e9-85b3-ced6b5950c04.png">

**Comment by Trupti-Baliga** [comment]
I observed the following changes:
Response Headers:

Header | Rails-5.1 | Rails-5.2
-- | -- | --
Referrer Policy | Absent | Present
X-Permitted-Cross-Domain-Policies | Absent | Present


Request Headers:

Header | Rails-5.1 | Rails-5.2
-- | -- | --
Referrer | Present | Absent

**Comment by schuetzm** [comment]
This was apparently changed in https://github.com/rails/rails/commit/5d7b70f4336d42eabfc403e9f6efceb88b3eff44 by @guilleiguaran. Unfortunately the commit doesn't include a reasoning for this change; presumably it was for security?

You should be able to work around this by adjusting `config.action_dispatch.default_headers`.

**Comment by rafaelfranca** [comment]
Yes. It was added for security

**Comment by esparta** [comment]
@schuetzm it is for security reasons:

https://blogs.msdn.microsoft.com/ie/2008/07/02/ie8-security-part-v-comprehensive-protection/
