### ISSUE TITLE
Deprecate using the global rails command for in-app operations

### ISSUE THREAD

**Issue by dhh** [rails/rails#35011]
We shouldn't be relying on global commands and gem versions for operations inside an application that already has its own bundled Rails. The binstubs provide a clear guarantee that the rails command you're running via bin/rails is the one that goes with this particular app. The delegation from a global command to the local rails command is a confusing indirection.

(This is mostly a matter of documentation updates.)

**Comment by hahmed** [comment]
I can take this issue.
