### ISSUE TITLE
ActionText in Rails 6.0.0.beta1: Could not find or build blob: expected attachable, got #<ActionText::Attachables::RemoteImage...>

### ISSUE THREAD

**Issue by imWildCat** [rails/rails#35026]
### Steps to reproduce

> I was trying to copy online HTML contents including images and paste these contents in to the Trix editor provided by ActionText.

1. Create a new Rails 6 project: `rails new demo`
2. Create a demo model with ActionText's rich text support. For example, using this demo provided by the edge doc: https://edgeguides.rubyonrails.org/action_text_overview.html
3. Copy some web contents including images, for example: https://en.wikipedia.org/wiki/Ruby_(programming_language)
![image](https://user-images.githubusercontent.com/2396817/51585410-39bceb00-1f14-11e9-8901-0213f9cac7cb.png)
4. Paste these contents into the Trix editor in the demo project.
5. Save or create the record
6. Exception:
```html
ArgumentError in XXXController#create
Could not find or build blob: expected attachable, got #<ActionText::Attachables::RemoteImage:0x00007f8b8f6e23b0 @url="https://upload.wikimedia.org/wikipedia/commons/thumb/7/73/Ruby_logo.svg/100px-Ruby_logo.svg.png", @content_type="image", @width="100", @height="100">
```

### Expected behavior
ActionText might support the pasted RemoteImage.

### Actual behavior
Contents with RemoteImage cannot be saved into the database.

### System configuration
**Rails version**: `Rails 6.0.0.beta1`

**Ruby version**: `ruby 2.6.0p0 (2018-12-25 revision 66547) [x86_64-darwin18]`

**Comment by y-yagi** [comment]
This fixed by #35057.
