### ISSUE TITLE
under certain circumstances app initializers run before gem initializers 

### ISSUE THREAD

**Issue by bughit** [rails/rails#35025]
### Steps to reproduce
- run `rake initializers` in https://github.com/bughit/init_order_bug
- the output is https://github.com/bughit/init_order_bug/blob/master/init_order_with_less
- note that `InitOrderBug::Application.load_config_initializers` is before  `Geocoder::Railtie.geocoder.insert_into_active_record`
- if you take out `less-rails`, `load_config_initializers` is after `geocoder`: https://github.com/bughit/init_order_bug/blob/master/init_order_without_less

### Expected behavior
app initializes should run after gems

### Actual behavior
app initializes run before geocoder

### System configuration
**Rails version**: 5.2.2

**Ruby version**: 2.5.3

**gem -v**: 3.0.2

**bundle -v**: 2.0.1

**Comment by bughit** [comment]
Judging by metaskills/less-rails#68 this may be triggered by https://github.com/metaskills/less-rails/blob/master/lib/less/rails/railtie.rb#L28

If so, logically that code does not appear to make it impossible to maintain the guarantee that app initializers run after gems

**Comment by rafaelfranca** [comment]
That is not how initializers works. It is true that under certain circumstances app initializers run before gem initializers, and that is by design. We want to give gem and applications the flexibility to chose when the initializers should run.

**Comment by bughit** [comment]
@rafaelfranca 

> It is true that under certain circumstances app initializers run before gem initializers

Ok, but this case should not be one of those circumstances.

less-rails does: `initializer 'less-rails.before.load_config_initializers', :before => :load_config_initializers, :group => :all`

Geocoder does: `initializer 'geocoder.insert_into_active_record'`

Please explain why geocoder should run after app initializes, it's not asking for that.

**Comment by rafaelfranca** [comment]
Right, that is an issue on less-rails that is forcing the rails initializer to run before it was made to. Please report to them.

**Comment by bughit** [comment]
So requesting `:before => :load_config_initializers` causes load_config_initializers to run too early?

It seems like that constraint can be satisfied without moving :load_config_initializers, or rejected, because no gem should have the power to so disrupt the initialization process.

**Comment by rafaelfranca** [comment]
Yes. We use the TSort algorithm to know which order the initializers should run. If an early initializer add a requirement to other initializer the algorithm will move the initializer to satisfy that constraint if needed.

Gem should have this power to change the initialization process, but they also have to responsibility to make sure what they are doing is not disruption anything. This is why this is an issue in less-rails.

**Comment by rafaelfranca** [comment]
> The expectation that gems are fully initialized by the time app initializers run

This expectation in invalid and it is not something the framework wants to guarantee.

Yes, this is still normal. The initializers are run in the order they are defined unless you change the order using `after` or `before`.

```
initializer 'first', after: 'some_other_think'
initializer 'second'
```

will be executed in the order of:

```
some_other_thing
first
second
```

But if some other thing has things before it and after it those things are going to be kept executing in the same order so

In the end the order is:

```
everything defined before some_other_thing
some_other_thing
everything defined after some_other_thing
first
second
```

If `first` and `second` are defined in a gem and `some_other_thing` in the application it means that the application initializers will run before the gem initializers.

**Comment by bughit** [comment]
> This expectation in invalid

Please consider the implication of that.

It seems perfectly natural to put app initialization code into an initializer. And it also seems perfectly natural for such initializer code to call into app code (e.g. set a class attribute or call a class method). But without this expectation holding, your app code will fail to load if it depends on a particular gem being fully initialized and integrated into rails.

This can be worked around with after_initilize, but you must admit that no-one will realize this upfront.
