### ISSUE TITLE
caching collections is slow

### ISSUE THREAD

**Issue by foonlyboy** [rails/rails#35037]
### Steps to reproduce
I have a view that renders a collection of about 50 objects with a partial.

When I cache the rendering of the partial by using the objects as cache keys,
then this adds ~9ms to the render time of the view (on cache miss)

Without the cache clause the view only takes only ~0.2ms longer than the render of the collection.

I'd suspect that the time is lost in computing the cache key of that 50 objects

### System configuration
**Rails version**: Rails 5.2.2

**Ruby version**: ruby 2.5.3p105

**Comment by rafaelfranca** [comment]
You need to give us more information on how to reproduce this issue, otherwise there is nothing we can do. Please read CONTRIBUTING.md file for more information about creating bug reports. Thanks!

**Comment by rafaelfranca** [comment]
No, I really don't know what you talking about, as if I was going to be lazy I could just close this issue since there is no information of what is slow and how we can reproduce it. Without that there is nothing we can do with.

**Comment by foonlyboy** [comment]
I need to cache on I18n.locale,
we need to localize, sorry David

But then then collections partials cache does not work any more.
While it is so super fast when it hits.
We should improve on that.

The cache clause should take a block to compute the cache key.
I believe that would fix all problems

~eike
