### ISSUE TITLE
action cable crash javascript on simple "hello world"

### ISSUE THREAD

**Issue by richardjuan** [rails/rails#35039]
### Steps to reproduce
[github notes](https://github.com/richardjuan/notsnotes/blob/master/rails_windows.md)

### Expected behavior
show a simple hello page with an "hello" alert in javascript

### Actual behavior
show the hello page but the javascript is not executed cause of action_cable bug

"Uncaught TypeError: Cannot read property 'message_types' of undefined"

code around:
```javascript
e=u.INTERNAL,i=e.message_types,n=e.protocols,o=2<=n.length?
```

### System configuration
**Rails version**: ruby '2.5.3'
**Ruby version**: gem 'rails', '~> 5.2.2'
[app.zip](https://github.com/rails/rails/files/2790769/app.zip)

**Comment by richardjuan** [comment]
I removed action cable as follow to fix it but it's ducktape stuff
```powershell
rails new my-app-name --skip-action-cable
```

**Comment by gmcgibbon** [comment]
To be clear, I think this is a windows specific issue. Asset compilation on windows can be a little tricky. I would wager its something to do with the `duktape` gem in your gemfile. I'll take a closer look at this when I'm on a windows machine, but in the meantime, try switching out your JavaScript runtime for Node.

**Comment by gmcgibbon** [comment]
After some investigation, I realized you are referring to the deployment of your app to Heroku. While your app was generated on windows, it doesn't seem to be a windows or duktape related problem. If you downgrade the `uglifier` gem to `4.1.19` (from `4.1.20`) your assets are minified properly, so I'm certain its an uglifier/uglifyjs issue. AFAICT, [this commit](https://github.com/lautis/uglifier/commit/ba103e851d76610dc2278a942c9287b120d0ac90) is causing the problem. 

As this is not an issue with Rails, I'm going to close this. I would suggest opening an issue on `uglifier` or `uglifierjs` if you want to figure out exactly why things aren't working. Thank you for the report!
