### ISSUE TITLE
ActiveStorage "Parent" Model Callback

### ISSUE THREAD

**Issue by jasonivers** [rails/rails#35044]
### Steps to reproduce
Update the attachment on a record that has_one_attached.

### Expected behavior
"Parent" record should receive some sort of callback, so that any operations that should happen when the "parent" is updated can happen.

Example:  There should be an activity feed item created when a user changes their profile picture.

Right now there is no means of detecting in the model that the attachment changed... user.changed? is false, user.avatar.changed? is false, user.avatar.blob.changed? is false, and the User model's ActiveRecord callbacks are not called (I don't expect the normal callbacks, like after_save, to be called, really, but there should be _some_ means of knowing the attachment changed).

### Actual behavior
The attachment is updated with no way of knowing that in the model that has the attachment.

### System configuration
**Rails version**: 5.2.2

**Ruby version**: 2.5.3

**Comment by Alxzu** [comment]
It would be nice to have some sort of `after_attachment_update` & `after_attachment_destroy` on the holder.

**Comment by c2ofh** [comment]
Untill Rails adds a callback to `Attachment`, I've build a monkey patch and added another callback to convert an image directly after upload.

**app/models/active_storage**
```ruby
after_create_commit :analyze_blob_later, :identify_blob, :convert_image!
...
def convert_image!
    return if record.is_a?(::Attachment)

    record.convert_image!
end
````

**Comment by kaspth** [comment]
Attachment has a polymorphic relationship to the parent record and is also marked touch true. See what that does here https://api.rubyonrails.org/classes/ActiveRecord/Associations/ClassMethods.html#method-i-belongs_to

That means we’re triggering after_touch, after_commit and after_rollback on the record. How do those work for the use cases?

**Comment by jasonivers** [comment]
Unless those callbacks (after_touch, etc.) have a means of seeing what was updated, and a reference to the object that triggered them (didn't see anything about that in the linked doc), it's not really enough... Otherwise, in my specific use case above, all I know is that something changed, and I can't create an item that says the avatar was updated, just that SOMETHING about the user changed.

**Comment by collimarco** [comment]
@kaspth I am using Rails 6.0 and the `purge` on the attachment doesn't update the `updated_at`... so it seems that `touch` is not invoked on the parent model!

This also creates bugs with the cache...

**Comment by sandrods** [comment]
How am I suposed to invalidate cache on attachment destoy? Do I have to manually touch the parent?
