### ISSUE TITLE
Rails 5 Strong Params returning status 200 when failing require

### ISSUE THREAD

**Issue by CodingAnarchy** [rails/rails#35048]
### Steps to reproduce

Have a controller with:

```ruby
def foo_params
   params.require(:foo)
end
```

and submit parameters:

```
{ foo: {} }
```

### Expected behavior

Status 422 Unprocessable Entity response. 

### Actual behavior

```
(byebug) response.status
200
(byebug) response.body
"{\"status\":\"unprocessable_entity\",\"data\":\"foo is required.\"}"
```

### System configuration
**Rails version**: 5.2.2
**Ruby version**: 2.5.3

**Comment by rafaelfranca** [comment]
Can you provide an example application that reproduce the issue?

**Comment by CodingAnarchy** [comment]
In trying to find an example application, I instead found an obscure location in the app where the strong parameters exception was being caught and the result modified.  I'll close this as an error.
