### ISSUE TITLE
around_update without yield makes save! fail silently

### ISSUE THREAD

**Issue by grapevinegizmos** [rails/rails#35058]
Very confusing to those not familiar with _around__ callbacks that failure to yield inside the callback will, when _save!_ is called with an updated attribute, return true and not raise an exception, but nevertheless the record will not be persisted.   

I believe it would be good to resolve this by either: (a)  _around-_ callbacks without yield would raise an exception on when _save_ or _save!_ is called on a model object, or( b) around callbacks without a yield would behave like _before__ callbacks.   I believe (a) would be best.  

A silently failing _save!_ or _save_ that return true, but do not complete are likely to lead to painful bugs, particularly with those not familiar with the (sparsely documented) around callback mechanism.

### Steps to reproduce

````
class Foo < ApplicationRecord
  around_update :check

  private

  def check
    if self.name=="goo"
      logger.warn "Foo named goo!"
    end
  end
````
 
### Expected behavior

Exception "around callback does not yield" should be raised when the record is saved with an update.

### Actual behavior

````
>> f = Foo.new(name: "Jim")
=> #<Foo id: nil, name: "Jim", age: nil, tag: nil, birthday: nil, created_at: nil, updated_at: nil>
>> f.save!
=> true
>> f.name = "Roger"
=> "Roger"
>>  f.save!
=> true
>> f.reload 
=> #<Foo id: 2, name: "Jim", age: nil, tag: nil, birthday: nil, created_at: "2019-01-26 04:04:14", updated_at: "2019-01-26 04:04:14">
````
### System configuration
**Rails version**:
5.2.1
**Ruby version**:
ruby 
ruby 2.5.0p0 (2017-12-25 revision 61468) [x86_64-darwin17]

**Comment by jvillarejo** [comment]
Hi! 

The documentation states that: 
```
When defining an around callback remember to yield to the block, otherwise it won't be executed
```
https://api.rubyonrails.org/classes/ActiveModel/Callbacks.html

**Comment by grapevinegizmos** [comment]
Fair enough but when I read that I thought it meant the callback wouldn’t execute, not that any save on the model wouldn’t execute


Sent from my iPhone

On Feb 15, 2019, at 4:01 PM, Juani Villarejo <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi!

The documentation states that:

When defining an around callback remember to yield to the block, otherwise it won't be executed


https://api.rubyonrails.org/classes/ActiveModel/Callbacks.html

**Comment by grapevinegizmos** [comment]
I think it’s a bigger problem than documentation.   Having save return true when in fact the object doesn’t save is an error in my view not a documentation problem.



Sent from my iPhone

On Feb 18, 2019, at 7:30 AM, Juani Villarejo <notifications@github.com<mailto:notifications@github.com>> wrote:


Maybe it would be good to improve the documentation. How would you write it so it explains correctly the current behavior ?

**Comment by fishinakleinbottle** [comment]
I agree with both the above arguments. Documentation should make it clear that the save will not succeed, along with raising an exception / return false if there there is no yield inside `around_` callbacks.
