### ISSUE TITLE
Implement blank? and present? directly in ActiveRecord::Base

### ISSUE THREAD

**Issue by SamSaffron** [rails/rails#35059]
Per twitter a question was raised about this Discourse patch:

https://twitter.com/nateberkopec/status/1088874644415934466

https://github.com/discourse/discourse/blob/master/lib/freedom_patches/performance_fixes.rb

My original commit message in Discourse is pretty crummy, but the bottom line is that this makes `Topic.new.blank?` way faster per:

https://gist.github.com/SamSaffron/c8bbc8c7b6bf3b0148760c887df18b55

Any objections to patching AR with this so we can kill our monkey patch @tenderlove  / @matthewd ?

**Comment by matthewd** [comment]
I guess this is avoiding the `respond_to?(:empty)` in: https://github.com/rails/rails/blob/8ae241401a2bff25f70befd2adcb35d541b9bc07/activesupport/lib/active_support/core_ext/object/blank.rb#L18-L20

.. because this makes it slow? https://github.com/rails/rails/blob/8ae241401a2bff25f70befd2adcb35d541b9bc07/activerecord/lib/active_record/dynamic_matchers.rb#L6-L13

**Comment by SamSaffron** [comment]
Yeah its hard to enter my old time machine, I am really upset with myself for having such a bad original commit message in Discourse with no followup, but this sounds very very familiar.

**Comment by rafaelfranca** [comment]
My opinion is still the same as this one here 
https://github.com/rails/rails/pull/23394. Code that calls present or blank in an active record instance is an anti-pattern, to not say wrong. Making it faster is to legitimate that anti-pattern. This should be discouraged, so being slow is a good think in my opinion. If we would implement something I'd prefer to raise an error.

**Comment by kamipo** [comment]
This was proposed as #23394 before, and we as Arm Treasure Data also have the same monkey patch.

![image](https://user-images.githubusercontent.com/12642/51783352-bb628200-217b-11e9-8d9f-3f979837ecf2.png)

**Comment by SamSaffron** [comment]
>  If we would implement something I'd prefer to raise an error. 

I guess this is one of the big reasons Matz is less enthused about adding a "blank" / "present" protocol in Ruby. It is very hard to define what the "right" thing is to do. Are instances even allowed to raise with this global protocol? Clearly it is not nonsensical but that a `topic` is `present` so an exception does not "feel" right. Maybe a depreciation that guides you towards the happy path? Even that does not feel particularly nice. 

What we found is back in the early days of Discourse @eviltrout far preferred using:

```
if topic.present? 
   # do stuff
end
```

Cause stuff like this "feels" less descriptive: 

```
if topic
   # do stuff
end 
```

These days we get around using this a fair bit by using `&.` so I see `if topic.present?` a lot less, but it still happens. 

In the context of Discourse we could probably get away with disallowing `topic.present?` but it would be a shame to lose out on the whole protocol `my_topic = topic.presence || other_topic`

I think `presence` @rafaelfranca makes it compelling enough to just speed it up in core.

**Comment by SamSaffron** [comment]
I can be swayed either way I guess but I think we got to do something here. Maybe @dhh should make the call here? 

I totally get the desire to call this out as an anti pattern, the correct pattern is going to be faster than the proposed patch. We are erasing a method call, doing nothing is going to be faster than calling a method that returns true or false. 

I guess we have 4 options here:

1. Patch the methods on AR::Base so they return true / false and we bypass the slow path. 
2. Patch the methods on AR::Base so they raise
3. Patch the methods on AR::Base so we call out deprecations
4. Do nothing

My pref is around (1) with (2) as my second choice, (3) as my third ... and (4) as far far far down the line options. 

People who use this pattern today are being punished unnecessarily in a very very hard to diagnose way. Picking some sort of side is very important here.

**Comment by SampsonCrowley** [comment]
If I might add an opinion, adding the methods directly can drastically speed them up and make the methods more useful in more places with not a lot of extra code. Even if it helps people using an anti-pattern, it's not hurting anyone to add it.

I also agree with @raphaelfranca that the insane stacktrace is the bigger issue here that should be examined more closely

If it were put to a vote, my vote would be to both add the methods directly (1) and investigate into what can be done to shorten the call stack for `respond_to?`

**Comment by dhh** [comment]
#present? for new_record? doesn't make sense to me. Because you could do Topic.new(title: "something").present? and to me that should definitely return true. So I'd rather just stick with the fact that for AR, present? is always true. 

We only offer the idea that present? isn't true for a subset of value types, like string, hash, array. Everything else is present? unless it's nil.
