### ISSUE TITLE
Rails 6.0.0.beta1- ActionText - couldn't find file 'trix/dist/trix' with type 'text/css' 

### ISSUE THREAD

**Issue by EchoUrandom** [rails/rails#35069]
I upgraded to rails 6 to take advantage of Action Text and so I've been following the [edge guides](https://edgeguides.rubyonrails.org/action_text_overview.html#examples). All is fine and good until rails tries to load this
```
 //= require trix/dist/trix
```
With the error
`couldn't find file 'trix/dist/trix' with type 'text/css'` 

I have been searching around other issues in the repo to see if this was solved previously, and sadly these were already solved and included in previous edge versions for different reasons.
https://github.com/rails/actiontext/issues/40
and
https://github.com/rails/rails/issues/34897

### System configuration
I'm using Rails 6.0.0.beta1
With Ruby 2.5.1

**Comment by rafaelfranca** [comment]
Can you provide an example application that reproduce the issue?

**Comment by EchoUrandom** [comment]
Okay. Bear with me as I'm new. I could be wrong, or this could be an actual bug. Let me know if I'm missing something.

Routes
```
  resources :books do
    resources :chapters
  end
```
Models
```
class Book < ApplicationRecord
  has_many :chapters, dependent: :destroy
  validates :title, presence: true
end
```
```
class Chapter < ApplicationRecord
  belongs_to :book
  has_rich_text :content
end

```

Chapter Controller
```
...
  def new
    @book = Book.find(params[:book_id])
    @chapter = @book.chapters.new
  end
  def create
    @book = Book.find(params[:book_id])
    @chapter = @book.chapters.create(chapter_params)
    #@chapter = Chapter.new(chapter_params)
    if @chapter.save
      redirect_to books_path
    else
      logger.debug @chapter.errors.full_messages
      redirect_to books_path
    end
  end
...
  private
  def chapter_params
    params.require(:chapter).permit(:book_id, :title, :content)
  end
```

Book Controller
```
...
  def show
    @book = Book.find(params[:id])
    @chapters = @book.chapters.all
    @chapter = Chapter.new
  end
...
  private
  def book_params
    params.require(:book).permit(:title, :description, :genre, :rating, :language, :status, :franchise, :image)
  end
end

```

Book#show
```
...
  <% @book.chapters.each do |c| %>
    <div class="chapter-view">
      <%= c.title %>
      <%= c.content %>
    </div>
  <% end %>
...
```

**Comment by hahmed** [comment]
@EchoUrandom I could not reproduce this issue, managed to get it working just now with v6.0.0.beta1 and ruby 2.6. Can you create a repo, and link that please? That way we could look at the `assets.rb`, yarn.lock. 

If you have a look at the path `node_modules/trix/dist/` assuming you can see 3 files? `trix.js`, `trix.css` and `trix-core.js`

**Comment by y-yagi** [comment]
I suppose missing to add `node_modules` to the assets paths. 

How about add following line to `config/initializers/assets.rb`?

```ruby 
Rails.application.config.assets.paths << Rails.root.join('node_modules')
```

**Comment by EchoUrandom** [comment]
@y-yagi that line already exists in the assets.rb file.

Anyway, @hahmed I do have a repo online already that you can clone and check. https://gitlab.com/jorrellh/freefiction

**Comment by y-yagi** [comment]
Thanks for your sample application. 

Your application missing required packages. Perhaps, I think that Yarn is not installed. 
If Yarn is not installed, install Yarn and run `action_text:install` again.

The packages required for `package.json` will be added as below. 

```diff 
diff --git a/package.json b/package.json
index ba8ff4d..e71cdee 100644
--- a/package.json
+++ b/package.json
@@ -1,5 +1,8 @@
 {
   "name": "freefiction",
   "private": true,
-  "dependencies": {}
+  "dependencies": {
+    "@rails/actiontext": "^6.0.0-beta1",
+    "trix": "^1.0.0"
+  }
 }
```  

The issue when Yarn is not installed is track with #35003.

Thanks.

**Comment by EchoUrandom** [comment]
Thanks!
