### ISSUE TITLE
A copy of has been removed from the module tree but is still active!

### ISSUE THREAD

**Issue by alencarandre** [rails/rails#35066]
### Steps to reproduce

Well, I opened this issue https://github.com/influitive/apartment/issues/580 on apartment gem, but the behavior seems to me that the problem can be on rails.

I created a Rack to change postgres schemas, and when I save any file, except view or js, break with this message:

`A copy of Pzcommerce::Elevator has been removed from the module tree but is still active!`

![image](https://user-images.githubusercontent.com/20287544/51807376-293aa680-226d-11e9-83b8-c8098a3736f0.png)

**Class elevator (Rack)**

Saved on `app/middleware/pzcommerce/elevator.rb`

```ruby
class Pzcommerce::Elevator < Apartment::Elevators::Generic
  def parse_tenant_name(request)
    host = request.host

    request_discovery = Pzcommerce::RequestDiscovery.new(request)

    domain = request_discovery.domain
    subdomain = request_discovery.subdomain
    master_domain = request_discovery.master_domain

    tenant = nil
    tenant_group = nil

    if "#{domain}" == "#{master_domain}"
      if "#{subdomain}" != "master"
        tenant_group = TenantGroup.find_by(subdomain: subdomain)
        raise_route_error(request) if tenant_group.blank?
      end
    else
      host = domain if "#{subdomain}" == "www"

      tenant = Tenant.unscoped.find_by(domain: host)
      raise_route_error(request) if tenant.blank?

      tenant_group = tenant.tenant_group
    end

    TenantGroup.current = tenant_group
    Tenant.current = tenant

    return Tenant.current.try(:apartment_name) || 'public'
  end

  private

  def raise_route_error(request)
    raise ActionController::RoutingError, "Domain #{request.host} Not Found"
  end
end
```

**Configuring rack**

Saved on `config/initializers/apartment.rb`

```ruby
require 'apartment/elevators/generic'

Apartment.configure do |config|
  config.excluded_models = %w{ Tenant TenantGroup }
  config.tenant_names = lambda { Tenant.pluck :apartment_name }
end

Rails.application.config.middleware.use Pzcommerce::Elevator
```
Application Initialize

```ruby
require_relative 'boot'

require 'rails/all'

Bundler.require(*Rails.groups)

module PzcommerceRails
  class Application < Rails::Application
    config.load_defaults 6.0

    config.middleware.delete ActionDispatch::HostAuthorization
  end
end
```

I found this issue https://github.com/rails/rails/issues/16806, but seems to me different problem becouse this error is caused when save some file, changing my middleware or not.

### Expected behavior

Edit and save my project without restart server

### Actual behavior

I need to restart server each save file (except js and views)

### System configuration
**Rails version**: 6.0.0.beta1
**Ruby version**: ruby 2.6.0p0 (2018-12-25 revision 66547) [x86_64-linux]

**Comment by matthewd** [comment]
Please use the mailing list or StackOverflow for questions/help, where a wider community will be able to help you. We reserve the issues tracker for issues only.
