### ISSUE TITLE
ActiveStorage Unpermitted parameter: :images with has_many_attached :images

### ISSUE THREAD

**Issue by francesco-loreti** [rails/rails#35072]
### System configuration
**Rails version**: Rails 6.0.0.1.beta1 

**Ruby version**: Ruby 2.6
```
application.js
require("@rails/activestorage").start()
```
```
class Model < ActiveRecord::Base
has_many_attached :images
```
```
_form.html.haml
= f.file :images, direct_upload: true, multiple: true
```
```
uploads_controller.rb
def upload_params
   params.require(:upload).permit( images: [] )
end
```

Error:
```
Unpermitted parameter: :images
```

Can you help me? Thanks!

**Comment by TrishaPatel** [comment]
I am getting same error. Can you tell where is mistake?

**Comment by gustavoelizalde** [comment]
Same error here... what did you did to fix it @francesco-loreti ?

**Comment by francesco-loreti** [comment]
> Same error here... what did you did to fix it @francesco-loreti ?

Hi, it's been a long time but I think I solved it by setting `direct_upload: 'false'` in the form. 
Hope the example below can clarify:

```
room.rb
class Room < ActiveRecord::Base
has_many_attached :images
```
I have not set `accepts_nested_attributes_for :images` in the model because it didn't work for me.

```
_form.html.haml
= f.file_field :images, multiple: true, direct_upload: 'false'
```

```
rooms_controller.rb
def update
    if @room.update(room_params)
      @room.images.attach(room_params[:images]) if room_params[:images].present?
      ...
    else
      ...
    end
end
def room_params
   params.require(:room).permit( :title, :body, images: [] )
end
```
Tell me if you solve.

Regards
