### ISSUE TITLE
question regarding has_secure_password and has_secure_token namespace differences

### ISSUE THREAD

**Issue by a-ross-cohen** [rails/rails#35075]
Apologies if this is the incorrect forum for this (it's not a bug). If there is a more appropriate way to discuss please let me know.

ActiveModel::SecurePassword and ActiveRecord::SecureToken are extremely similar in use however they are implemented in different places. It appears advantageous to have them both live in ActiveModel as it is used by non-ActiveRecord ORM/ODM/etc and would make it cleaner for other libraries to use the functionality.

I noticed this because I was using Mongoid and had to add imports for ActiveRecord to get has_secure_token to work, which seems odd and avoidable since it works smoothly with has_secure_password out of the box.

I wouldn't mind generating a PR for it but I was unsure if there was an actual reason for SecureToken to live in ActiveRecord and wanted to ask first.

Thanks

**Comment by rafaelfranca** [comment]
SecureToken relies in APIs that are only present on Active Record like `before_create` and `update!`. While I can see we moving it to Active Model it would mean increase the minimal interface a class have to implement to be an Active Model so I think this is not worth it. The implementation of `SecureToken` itself is really small and most of the things are already present in most ORMs so it would not hard to implement it again in other ORMs.
