### ISSUE TITLE
Rails 6.0.0.beta1 can not load database configuration when the URL (or database) is nil

### ISSUE THREAD

**Issue by msdundar** [rails/rails#35091]
### Steps to reproduce

Here is a part of the database configuration we use:

```ruby
<% name = 'my_fancy_app'
   url = "postgresql://#{name}:#{name}@localhost/#{name}_%{environment}" %>

default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000
  encoding: unicode

development:
  <<: *default
  url: <%= format url, environment: 'development' %>

test:
  <<: *default
  url: <%= format url, environment: 'test' %>

production: &production
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
  pool: <%= ENV.fetch('RAILS_MAX_THREADS', 40) %>

beta:
  <<: *production
```

In Rails 5.2.2 when I call `ActiveRecord::Base.configurations['production']` it returns:

```
{"adapter"=>"postgresql", "pool"=>40, "timeout"=>5000, "encoding"=>"unicode", "url"=>nil}
```

However, in Rails 6.0.0.beta1 `ActiveRecord::Base.configurations['production']` it returns:

```
nil
```

### Expected behavior

`ActiveRecord::Base.configurations` should return the existing database variables as it was in Rails 5.2.2.

### Actual behavior

Rails 6.0.0.beta1 returns `nil` when the `url` (or `database`) is `nil` somehow.

### System configuration

**Rails version**:

- Rails 6.0.0.beta1

**Ruby version**:

Tested with both:

- ruby 2.5.1p57 (2018-03-29 revision 63029) [x86_64-linux]
- ruby 2.6.0p0 (2018-12-25 revision 66547) [x86_64-linux]

**Comment by msdundar** [comment]
Somehow this caused a test suite fail in CircleCI. The logs were stating a fail to read database configuration for `beta` and `production` environments, even I can verify `ENV['DATABASE_URL']` is defined and accessable. As a workaround I added `database: foo_bar` line to the configuration and it worked well.

**Comment by gmcgibbon** [comment]
Given that URL configurations [do this](https://github.com/rails/rails/blob/94d54fa4ab641a0ddeb173409cb41cc5becc02a9/activerecord/lib/active_record/database_configurations/url_config.rb#L63), I think this use-case is no longer supported. There's [special code for `ENV["DATABASE_URL"]`](https://github.com/rails/rails/blob/94d54fa4ab641a0ddeb173409cb41cc5becc02a9/activerecord/lib/active_record/database_configurations.rb#L110) that transforms the current environment's config to a URL config, so if you remove the `url:` setting in production and add `database: ""`, that should work, but that seems like a hack.

cc @eileencodes

**Comment by eileencodes** [comment]
What does `ActiveRecord::Base.configurations` return? In Rails 6 configurations aren't a hash, they're an object so `ActiveRecord::Base.configurations['production']` won't work anymore. It was an unfortunate change we had to make to improve the overall problem. 

You can instead use `ActiveRecord::Base.configurations.configs_for(env_name: "production")` to get production configurations back.

**Comment by msdundar** [comment]
`ActiveRecord::Base.configurations.configs_for(env_name: "production")` returns `nil` when the `url` is `nil`. However there are other parameters available for the production configuration, and it totally omits them.

- database.yml:

```ruby
<% name = 'my_fancy_app'
   url = "postgresql://#{name}:#{name}@localhost/#{name}_%{environment}" %>

default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000
  encoding: unicode

development:
  <<: *default
  url: <%= format url, environment: 'development' %>

test:
  <<: *default
  url: <%= format url, environment: 'test' %>

production: &production
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
  pool: <%= ENV.fetch('RAILS_MAX_THREADS', 40) %>

beta:
  <<: *production
```

```ruby
ActiveRecord::Base.configurations.configs_for(env_name: "development")
```

=> 

```
[#<ActiveRecord::DatabaseConfigurations::UrlConfig:0x00005568d23caee8
  @config=
   {"adapter"=>"postgresql",
    "pool"=>5,
    "timeout"=>5000,
    "encoding"=>"unicode",
    "username"=>"my_fancy_app",
    "password"=>"my_fancy_app",
    "database"=>"my_fancy_app_development",
    "host"=>"localhost"},
  @env_name="development",
  @spec_name="primary",
  @url="postgresql://nokul:nokul@localhost/nokul_development">]
```

```ruby
ActiveRecord::Base.configurations.configs_for(env_name: "production")
```

=> 

```
nil
```

I could expect something like this instead of `nil` when `ENV['DATABASE_URL']` is `nil`:

```
[#<ActiveRecord::DatabaseConfigurations::UrlConfig:0x00005568d23caee8
  @config=
   {"adapter"=>"postgresql",
    "pool"=>5,
    "timeout"=>5000,
    "encoding"=>"unicode",
    "username"=>"my_fancy_app",
    "password"=>"my_fancy_app",
    "database"=>nil,
    "host"=>nil},
  @env_name="production",
  @spec_name="primary",
  @url=nil>]
```

**Comment by eileencodes** [comment]
I'm confused, why are you using the production configuration if the database url isn't set?

**Comment by msdundar** [comment]
Actually I noticed the changing behavior when I'm trying to make a deploy to Dokku. After the Rails 6.0.0.beta1 upgrade, during the `bundle exec rake assets:precompile` stage, the container started to complain as follows:

```
ActiveRecord::AdapterNotSpecified: The `beta` database is not configured for the `beta` environment.

Available databases configurations are:

development
test
```

We have never changed the `database.yml`, it is working without any problems when the app in Rails 5.2.2. We only upgraded to Rails 6.0.0 and it started to fail. So I believe that this is something related with the modified behaviour?

**Comment by eileencodes** [comment]
Ok I was able to reproduce this and am working on a fix. One thing I'd like clarification on is I'm guessing the beta in 5.2 doesn't blow up but doesn't work either because without the database url it would not be able to connection right? Can you tell me what happens with the beta connection in 5.2.2? Thanks!
