### ISSUE TITLE
Rails 6.0.0.beta1 and Devise: ActionDispatch::IllegalStateError: header already sent

### ISSUE THREAD

**Issue by tirdadc** [rails/rails#35100]
### Steps to reproduce
This very basic controller spec is now failing following an upgrade from 5.2 to 6.0.0.beta1. This seems very similar to [this issue that was previously resolved](https://github.com/rails/rails/issues/25269).

```
describe "GET #index" do
    it 'redirects to login if not logged in' do
      get :index
      expect(response).to redirect_to(new_user_session_url)
    end
end
```

### Expected behavior
Spec should pass.

### Actual behavior
Spec fails with this error:

```
1) Admin::ReleasesController GET #index redirects to login if not logged in
     Failure/Error: get :index

     ActionDispatch::IllegalStateError:
       header already sent
     # ./spec/controllers/admin/releases_controller_spec.rb:21:in `block (3 levels) in <top (required)>'
```

### System configuration
**Rails version**: 6.0.0.beta1
**Ruby version**: 2.6.0
**devise**: 4.5.0
**rspec-rails**: 3.8.2
**rails-controller-testing**: 1.0.4

**Comment by y-yagi** [comment]
Can you please provide a sample application that reproduces the issue?

**Comment by alexanderbird** [comment]
Same issue for me -- sorry, I don't have time just now to make a sample application -- but maybe this helps:

My setup was:
 - `rails new` with 6.0.0.beta1
 - `rails generate scaffold .....`
 - install devise, add `before_action :authenticate_user!` to the scaffolded controller
    - tests fail with ` Devise::MissingWarden:`
 - add `config.include Devise::Test::ControllerHelpers, type: :controller` to `rails_helper.rb`
    - tests fail with ` ActionDispatch::IllegalStateError:       header already sent`

I'm using rspec.

**Comment by y-yagi** [comment]
@alexanderbird Thanks. But that is a devise's issue. Ref: https://github.com/plataformatec/devise/pull/5002
