### ISSUE TITLE
Invalid routes with scope below resources

### ISSUE THREAD

**Issue by schuetzm** [rails/rails#35113]
``` ruby
Rails.application.routes.draw do
    resources :examples, only: [] do
        scope ':oid' do
            resources :foos, only: :show
        end 
        member do
            scope ':oid' do
                resources :bars, only: :show
            end
        end
    end 
end
```

This produces the following routes:
```
     Prefix Verb URI Pattern                                   Controller#Action
example_foo GET  /:oid/examples/:example_id/foos/:id(.:format) foos#show
        bar GET  /examples/:id/:oid/bars/:id(.:format)         bars#show
```
The first route has the `:oid` segment at the beginning instead of after `:example_id`, which doesn't reflect the nesting of the route definitions.
The second route gets the order of segments right, but it has the wrong name (`bar` instead of `example_bar`), and it uses `:id` twice (the first occurrence should be `:example_id`).

That's what the result should be IMO:
```
example_bar GET  /examples/:example_id/:oid/bars/:id(.:format) bars#show
```
Note that this can be worked around, but it might be worth fixing it nevertheless as far as it can be done without breaking existing apps (especially the duplicated `:id`):
```ruby
    scope 'examples/:example_id/:oid', as: :example do
        resources :bars, only: :show
    end
```

**Rails version**: `master`, apparently going back to `v5.0.0`
**Ruby version**: 2.5.1

**Comment by pixeltrix** [comment]
@schuetzm defining the routes like this fixes your problem:

``` ruby
Rails.application.routes.draw do
  resources :examples, only: [] do
    nested do
      scope ':oid' do
        resources :foos, only: :show
      end 
    end
  end 
end
```

```
example_foo    GET /examples/:example_id/:oid/foos/:id(.:format)    foos#show
```

When you use nested `resources` calls it implicity creates a nested scope but if you need to add anything before the nested resource you'll need to explicitly define the nested scope before using `scope` to add to the path.
