### ISSUE TITLE
rails new plugin doesn't load lib/gem_name/tasks/*.rake by default

### ISSUE THREAD

**Issue by byterussian** [rails/rails#35124]
Hi,

### Steps to reproduce

run:
```
$ rails plugin new my_plugin  --skip-test-unit --dummy-path=spec/dummy
```

edit lib/tasks/my_plugin_tasks.rake:
```
desc "Explaining what the task does"
task :my_task do
  puts "test"
end
```

then go in spec/dummy and list all tasks
```
cd spec/dummy
rake -T
```

### Actual behavior

`my_task` doesn't show up in rake task list.

### System configuration
**Rails version**: 5.1.6

**Ruby version**: 2.5.1

Are you interested in a PR?

**Comment by utilum** [comment]
I can reproduce this with master.

Don't no if you need the options:`rails plugin new my_plugin` reproduces.

**Comment by rafaelfranca** [comment]
Only engines load tasks by default. By default the plugin generator generates railties, not engines. So only plugins generated with `--full`, `--mountable` and `--engine` options load take tasks by default.
