### ISSUE TITLE
klass returns nil for OID type and ActiveRecord type column objects

### ISSUE THREAD

**Issue by ashish91** [rails/rails#35123]
### Steps to reproduce
With `ActiveRecord::Type::Integer`
```
[30] pry(main)> b = ActiveRecord::Type::Integer.new
=> #<ActiveRecord::Type::Integer:0x000000000e2574d0 @limit=nil, @precision=nil, @range=-2147483648...2147483648, @scale=nil>
[31] pry(main)> x = ActiveRecord::ConnectionAdapters::PostgreSQLColumn.new('id', nil, b, 'integer')
=> #<ActiveRecord::ConnectionAdapters::PostgreSQLColumn:0x000000000df699d0
 @array=false,
 @cast_type=#<ActiveRecord::Type::Integer:0x000000000e2574d0 @limit=nil, @precision=nil, @range=-2147483648...2147483648, @scale=nil>,
 @default=nil,
 @default_function=nil,
 @name="id",
 @null=true,
 @sql_type="integer">
[32] pry(main)> x.klass
=> nil
```
With `ActiveRecord::ConnectionAdapters::PostgreSQL::OID::Integer`, this is a `private` method so don't know if this is actually an issue since it's not expected to be called outside activerecord.
```
[44] pry(main)> type = ActiveRecord::Base.connection.send :get_oid_type, 20, -1, "id", "id"
=> #<ActiveRecord::ConnectionAdapters::PostgreSQL::OID::Integer:0x0000000007d38c48 @limit=nil, @precision=nil, @range=-2147483648...2147483648, @scale=nil>
[45] pry(main)> column = ActiveRecord::ConnectionAdapters::PostgreSQLColumn.new("id", nil, type, "integer")
=> #<ActiveRecord::ConnectionAdapters::PostgreSQLColumn:0x000000000c287588
 @array=false,
 @cast_type=#<ActiveRecord::ConnectionAdapters::PostgreSQL::OID::Integer:0x0000000007d38c48 @limit=nil, @precision=nil, @range=-2147483648...2147483648, @scale=nil>,
 @default=nil,
 @default_function=nil,
 @name="id",
 @null=true,
 @sql_type="integer">
[46] pry(main)> column.klass
=> nil
```

### Expected behavior
`column.klass` should return the class of the postgres column. The transformation happened [here](https://github.com/rails/rails/commit/c4245c31c6b83c9d70b5ca29f6fd820b9ed7fb14#diff-2524057922ad16b58e6b18b2f35b5de2L53).

### Actual behavior
`column.klass` returns `nil` since the `klass` method was removed in this [commit](https://github.com/rails/rails/commit/8a6e7631d31b2261f5a9dc6f0adefbe3e72f79d5#diff-1d10f31143116d2b2a11ec743f1738a4).

### System configuration
**Rails version**: Rails 4.2.11

**Ruby version**: Ruby 2.3.8p459

Is there no case where `klass` method is being used in postgres column object ? Or maybe it's just used for [date.rb](https://github.com/rails/rails/blob/4-2-stable/activerecord/lib/active_record/type/date.rb#L8) and [time_value.rb](https://github.com/rails/rails/blob/4-2-stable/activerecord/lib/active_record/type/time_value.rb#L4).
We're upgrading our app from Rails 4.1.x to 4.2.x and we're using PostgresColumn objects heavily to generate reports.

**Comment by y-yagi** [comment]
4.2 series are not supported anymore for anything besides severe security fixes. 
Please check whether the issue can be reproduced with the latest Rails. If you can reproduce, feel free to reopen the issue. Thanks!
