### ISSUE TITLE
style-src should not have a nonce when you enable application.config.content_security_policy_nonce_generator

### ISSUE THREAD

**Issue by terracatta** [rails/rails#35137]
This problem is related to PR #32932. Since this PR was merged nonces are now applied to both the `style-src` and `script-src` rules when a `Rails.application.config.content_security_policy_nonce_generator` strategy is defined.

Unfortunately, when you add a nonce to the source list of `style-src` (which you must do if you want nonces for `script-src` for UJS) the `unsafe-inline` can no longer be used.

Specifically, the browser will produce the following message:

```
Refused to apply inline style because it violates the following Content Security Policy directive: "style-src 'unsafe-inline' 'self' https: 'nonce-Vu7/HxbRiwfIoYDk42J8rg=='". Note that 'unsafe-inline' is ignored if either a hash or nonce value is present in the source list.
```

It's very possible I am missing something obvious here, but I feel at a total loss. I have several vendored JS libraries that apply inline styles, I'm not sure how I can get them to work _and_ still use UJS.

### Steps to reproduce

1. Setup a CSP Policy using the following code (note how nonce generations is enabled):

```
Rails.application.config.content_security_policy do |policy|
  policy.default_src :self
  policy.font_src    :self, :data
  policy.img_src     :self, :https, :data
  policy.object_src  :none
  policy.script_src  :self
  policy.style_src   :unsafe_inline, :self, :https
  policy.base_uri    :self
end

Rails.application.config.content_security_policy_nonce_generator = -> request { SecureRandom.base64(16) }
```

2. Import a JS library that needs `unsafe-inline` for style-src to run properly `jquery.sparkline.js` appears to be one.

3. Load the app in the browser

### Expected behavior
All of the dynamically set inline CSS styles load because I have `unsafe-inline` in my `style-src` directive.

### Actual behavior
The dev console in the browser complains with

```
Refused to apply inline style because it violates the following Content Security Policy directive: "style-src 'unsafe-inline' 'self' https: 'nonce-Vu7/HxbRiwfIoYDk42J8rg=='". Note that 'unsafe-inline' is ignored if either a hash or nonce value is present in the source list.

```

### System configuration
**Rails version**: 6.0.0 beta1

**Ruby version**: 2.6.0

**Comment by y-yagi** [comment]
Thanks for your report. Can you please provide a sample application that reproduces the issue?

**Comment by y-yagi** [comment]
Thanks for creating a sample application. In cases that `unsafe_inline` is explicitly specified, we may need to invalidate the nonce. I will investigate.

**Comment by terracatta** [comment]
Just in case anyone needs a quick fix to get around this, I am currently using the following Monkey Patch that essentially undos PR #32932


in config/initializers/content_security_policy.rb
```ruby
module ActionDispatch
  class ContentSecurityPolicy
    private
    def nonce_directive?(directive)
      %w[script-src].include?(directive)
    end
  end
end
```

**Comment by connorshea** [comment]
Yup, this one is biting me after upgrading to rails 6.0.0.beta2. Thanks for the fix @terracatta!

**Comment by pixeltrix** [comment]
@y-yagi are you still looking at this or shall I pick it up?

**Comment by y-yagi** [comment]
@pixeltrix I have put this in my TODO, but have not done it yet. Can you please pick up?

**Comment by pixeltrix** [comment]
@y-yagi okay, I will do

**Comment by connorshea** [comment]
Any progress on this issue? :)

**Comment by pixeltrix** [comment]
Was planning to do it this weekend but been a bit busy 😂 

https://www.independent.co.uk/news/uk/politics/brexit-petition-article-50-revoke-record-website-deal-theresa-may-latest-a8836536.html

**Comment by y-yagi** [comment]
If you have no time, I can pick up ;)

**Comment by pixeltrix** [comment]
@y-yagi thanks, but things are calming down now so I'm hoping to do it tomorrow evening.

**Comment by connorshea** [comment]
Apologies for bumping this again, but seeing as the release candidates seem to be coming soon I figured I should. 🙇

**Comment by CHTJonas** [comment]
Bumping this ticket again - sorry! This is an annoying little issue that is actually quite unintuitive when you're trying to override an existing CSP:
```ruby
class LegacyContentController < ApplicationController
  content_security_policy do |policy|
    policy.script_src  :self, :unsafe_inline
    policy.style_src   :self, :unsafe_inline
  end
end
```

@pixeltrix are you still considering a PR for this?
