### ISSUE TITLE
Can't localize ActiveRecord::XXXXErrors

### ISSUE THREAD

**Issue by kazuooooo** [rails/rails#35147]
### Steps to reproduce
set rails locale other than :en

```rb:config/applicaton.rb
config.i18n.default_locale = :ja
```

and run this code
```rb
begin 
  User.find_by!(name:  'not exist user')
rescue ActiveRecord::RecordNotFound => e
  p(e.message) #=>  "Couldn't find User" (this is not localized)
end
```

### Expected behavior
I want localized message from e#message

```rb
begin 
  User.find_by!(name:  'not exist user')
rescue ActiveRecord::RecordNotFound => e
  p(e.message) #=>  "ユーザーが見つかりません。" (expect localized message)
end
```
### Actual behavior
raw english message returned.
Looks raw string used
https://github.com/rails/rails/blob/8ca6bd2e942f9a2652ec20c0c419e9b08f25c2e1/activerecord/lib/active_record/core.rb#L209

### System configuration
**Rails version**:
5.0.2

**Ruby version**:
 2.4.1p111

I would be grateful if someone know other good way :)
thanks,

**Comment by rafaelfranca** [comment]
The exception messages are not going to be localized. The Active Model errors are, and if you need to localize exceptions you can write the code in the application using I18n.

Thank you for the issue.
