### ISSUE TITLE
InvalidAuthenticityToken when following Getting Started guide

### ISSUE THREAD

**Issue by utilum** [rails/rails#35151]
Following the Getting Started guide, in [5.3 Creating articles](https://edgeguides.rubyonrails.org/getting_started.html#creating-articles) after defining `ArticlesController#create` and submitting the form I encounter `ActionController::InvalidAuthenticityToken in ArticlesController#create`.

Not sure how we want to address this, but we don't want a new user to encounter an unexpected unexplained error this early.

**Comment by regularmike** [comment]
I was unable to reproduce this issue with Rails 5.2.3 or 5.2.2 (which you might have been using back in February). Are you able to verify that `<input type="hidden" name="authenticity_token"`... appears in the rendered HTML inside the `<form>` element?

**Comment by utilum** [comment]
I was using master.

**Comment by regularmike** [comment]
This does not seem to be a common problem today or with the version that was current when you opened this issue. If this is still happening check for the hidden input tag mentioned above and share some additional details about your setup and environment.

**Comment by utilum** [comment]
Thank you. I no longer see the error.
