### ISSUE TITLE
Show Action Mailbox Inbound emails Setup instruction initially

### ISSUE THREAD

**Issue by Gaurav2728** [rails/rails#35155]
### Steps to reproduce
1. Create a new Rails application with Rails 6.0.0.beta1 `rails _6.0.0.beta1_ new demo`
2. Go into the `demo` app directory, run `bundle install`
3. Start the `rails server` and check Rails routes - http://localhost:3000/rails/info/routes
4. Route points to - `/rails/conductor/action_mailbox/inbound_emails`

### Expected behavior
When a user creating a new rails application; it should show the message to set up or configure the Action Mailbox.
Various gems show the message post installation. Like - `run  bundle exec spring binstub --all`

### Actual behaviour
Currently, when we are trying to open http://localhost:3000/rails/conductor/action_mailbox/inbound_emails it's showing `no such table action_mailbox_inbound_emails`
![screen shot 2019-02-03 at 7 28 45 pm](https://user-images.githubusercontent.com/1284716/52238906-2be36e80-28f3-11e9-80c5-c059106e205f.png)
![screen shot 2019-02-04 at 5 35 58 pm](https://user-images.githubusercontent.com/1284716/52238907-2be36e80-28f3-11e9-9a00-0bae7262b988.png)

### System configuration
**Rails version**:
Rails 6.0.0.beta1

**Ruby version**:
2.5.1

**Comment by y-yagi** [comment]
Fixed by #35581.
