### ISSUE TITLE
Action Text: Unable to consistently update has_rich_text field using accepts nested attributes

### ISSUE THREAD

**Issue by mike1o1** [rails/rails#35159]
### Steps to reproduce
I had trouble creating a one-file script to support loading ActionText, so I've created a barebones repository here: https://github.com/mike1o1/action-text-test with passing/failing tests in [message_test.rb](https://github.com/mike1o1/action-text-test/blob/2217a264fb0e68142f8bfec8294437467d820ad3/test/models/message_test.rb)

It seems that if I have a model with a `has_one/has_many` relationship to an item that has rich text, then if I attempt to update only the rich text using `accepts_nested_attributes_for`, then the text is never updated. It seems as if the model doesn't realize there were changes, and so the write to the database never takes place.

If I update another attribute along with the rich text, then the update saves correctly.

Here is an example, with basic models:

```ruby
class Message < ApplicationRecord
    has_rich_text :content

	# also occurs with `has_many`
    has_one :post

    accepts_nested_attributes_for :post
end

class Post < ApplicationRecord
    belongs_to :message

    has_rich_text :content
end
```

And the corresponding unit test:

```ruby
test "can update post from within message" do
    message = Message.create!(title: "Seasons")
    post = message.create_post!

    # test updating post directly from the message
    message.update!(post_attributes: { content: "Test content", id: post.id })

    # it appears that everything updated?
    assert_equal "Test content", message.post.content.to_plain_text

    # let's reload the model and double check
    message.reload

    # this fails. The content is never saved. Uhoh
    assert_equal "Test content", message.post.content.to_plain_text
end
```

I'm not sure if I'm not using things correctly, but this is really subtle issue of things not working as I would have expected.

Even more confusingly, if I update another attribute on my `Post` model, then the rich text is saved correctly.

```ruby
# rich text is updated correctly
message.update!(post_attributes: { content: "Test content", id: post.id, title: "Plain text" })
```

### Expected behavior
I would expect that if I am updating a child object which contains rich text, then it would update correctly when using `accepts_nested_attributes_for`.

### Actual behavior
The rich text is not updated, unless *another* property on the model is also updated at the same time.

As a workaround, I save the child model directly if the `update` succeeds. This seems to force the database write.

### System configuration
**Rails version**: 6.0.0.beta1

**Ruby version**: 2.5.1, 2.6.0 and 2.6.1

**Comment by azbshiri** [comment]
@mike1o1 Make it PR please or I will :D

**Comment by mike1o1** [comment]
@azbshiri go for it! I’m not sure where to start.
