### ISSUE TITLE
Requests sent by js don't come through a controller

### ISSUE THREAD

**Issue by a-ta-ta** [rails/rails#35163]
### Steps to reproduce

This form is used to show other forms (below) for different  types of posts:
		        <%= form_with(url: show_post_type_form_for_users_path, id: "my_form", method: :get) do |form| %>
		            <%= form.select :post_type_id, @post_types.map { |e| [e.title, e.id] }, {  }, { class: "grn_sel w-100", onchange: "selectFilter()" } %>
		        <% end %>

I'm submitting the form by js with:
    @selectFilter = ->
      $.get($('#my_form').attr('action'), $('#my_form').serialize(), 'script')

### Expected behavior
The controller performs all the requests as expected and then the view is rendered  with all the data got by controller's requests.

### Actual behavior

The request doesn't come through a controller! I even tried to remove the action entirely, but everything "works" even without it!
I say "works", but no requests were performed.
So it just goes directly to the view with all the errors caused by empty variables.

### System configuration
**Rails version**:
I'm on Rails 5.2.1. 

**Ruby version**:
2.5.1

**Comment by y-yagi** [comment]
Please use the [mailing list](https://groups.google.com/forum/#!forum/rubyonrails-talk) or StackOverflow for questions/help, where a wider community will be able to help you. We reserve the issues tracker for issues only. Thanks.
