### ISSUE TITLE
Disable 'deprecation warnings for Rails' not working

### ISSUE THREAD

**Issue by Sega100500** [rails/rails#35164]
Linux Debian 8
Apache 2.4
Rubu 2.6.1
Rails 5.0 & 5.1

in ``config/environment``
set ``config.active_support.deprecation = :silence`` not working

still show warnings:
```warning: BigDecimal.new is deprecated; use BigDecimal() method instead```

**How disable deprecation messages in Rails???**

**Comment by vipulnsward** [comment]
This is has been fixed in https://github.com/rails/rails/pull/31460 and will be available in next release.

**Comment by Sega100500** [comment]
@vipulnsward 

Ok, next release
But... How about Rails 5.0.x & Rails 5.1.x ???

**Comment by kaspth** [comment]
That warning is coming from Ruby not Rails, and I don’t recall that that deprecation config removes any Ruby warnings.

**Comment by Sega100500** [comment]
@kaspth 
Which one 'that deprecation config removes any Ruby warnings' ???
config option not working to disable deprecation messages
Or I can create a configuration only for Ruby?

**Comment by kaspth** [comment]
The one you mentioned: `config.active_support.deprecation = :silence`. That’s to silence deprecation warnings that have been deprecated with ActiveSupport::Deprecation, it’s not for Ruby warnings.

You’ll have to upgrade Rails or do your own backport per https://guides.rubyonrails.org/maintenance_policy.html#unsupported-release-series

There’s nothing I can do, thanks.

**Comment by Sega100500** [comment]
@kaspth 
Then maybe it makes sense to fix Rails 5.0.x and Rails 5.1.x ?

**Comment by rafaelfranca** [comment]
Those two versions are not supported anymore for any bug fixes.

**Comment by kaspth** [comment]
@Sega100500 please read up on the entire maintenance policy I linked. Though it does boil down to what @rafaelfranca said 😊

**Comment by nkanumoori** [comment]
add `gem 'warning'` to **_Gemfile_**
Then, add below code in _**application.rb**_ 
```
require 'warning'
Gem.path.each do |path|
  Warning.ignore(//, path)
end

```
