### ISSUE TITLE
display the loaded image actiontext

### ISSUE THREAD

**Issue by nikolaokonesh** [rails/rails#35185]
Hello! Help me, please, I use actiontext, and I try to display the loaded image, here are my attempts to show in the partial

attention to this: <% ActiveStorage::Attachment.where(record: post.body.id).limit(1).each do |img| %>

```
_post.html.erb

<% cache post do %>
  <%= link_to [post.posttable, post], class: 'card--article' do %>

    <% ActiveStorage::Attachment.where(record: post.body.id).limit(1).each do |img| %>
      <% if img.blob.representable? %>
        <%= image_tag img.blob.representation(resize_to_fill: [ 50, 50 ]) %>
      <% end %>
    <% end %>

    <span class="leading-none">
      <%= content_tag :span, icon('fas', 'crown'), class: 'text-yellow-dark' if post.subscribe == true %>
      <%= sanitize(strip_tags(post.title)) %>
    </span>
    <small class="inline-block">
      <%= content_tag :span, icon('fas', 'comment-dots', post.comments.count), class: 'pr-1' if post.comments.present? %>
      <%= icon('far', 'calendar-alt', time_tag(post.created_at, :format=>'%d %B %Y г.')) %>
    </small>
  <% end %>
<% end %>
```
How to do it right?
Thanks!

**Rails version**: 6.0.0.beta1
**Ruby version**: 2.6.0

**Comment by y-yagi** [comment]
Please use the [mailing list](https://groups.google.com/forum/#!forum/rubyonrails-talk) or StackOverflow for questions/help, where a wider community will be able to help you. We reserve the issues tracker for issues only. Thanks.
