### ISSUE TITLE
Railties raises an error using the old secret_key_base syntax in v>=5.2

### ISSUE THREAD

**Issue by Arepo** [rails/rails#35192]
### Steps to reproduce
(I'm never quite sure how to fill in this section when the issue is a non-isolatable part of the app, especially since this is a legacy app, not all of whose parts I understand!). Anyway, in this case, I have an app I've just been updating from Rails 4.2.11 up to Rails 5.2.2 (also tested on 5.1.6 where this issue doesn't occur and 5.2.0 where it does), in all cases using Ruby 2.5.1.

We have an existing config/secrets.yml file, with the following content:

development:
  secret_key_base: hardcodeddevkey
test:
  secret_key_base: hardcodedtestkey
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>

And we're using CircleCI/Convox/AWS for deployment

### Expected behavior
When I deploy to 'production' (our staging site, but we don't differentiate in the code), our Dockerfile executes the command `bundle exec rake assets:precompile --trace`. This is part of the legacy logic - I've never interacted with this line, so I'm not totally sure of its purposes - though it looks like it creates secure filenames of our assets? In any case, it should resolve without error

### Actual behavior
It raises this error and the deployment fails:
    ArgumentError: Missing `secret_key_base` for 'production' environment, set this string with `rails credentials:edit`

Full stack trace/error message at the bottom.

I'm going to try setting up the credentials to fix the problem, but from what I've read our current method is deprecated, but should in principle still work.

### System configuration
**Rails version**:
5.2+ (tested with 5.2.0, and 5.2.2, where the error occurs, and with 5.1.6, where it doesn't)

**Ruby version**:
2.5.1

The full error message/stack trace:

** Invoke assets:precompile (first_time)
** Invoke assets:environment (first_time)
** Execute assets:environment
** Invoke environment (first_time)
** Execute environment
** [Raven] Raven 0.15.6 configured not to send errors.
** [Raven] Event not sent due to excluded environment: production
rake aborted!
ArgumentError: Missing `secret_key_base` for 'production' environment, set this string with `rails credentials:edit`
/usr/local/bundle/gems/railties-5.2.2/lib/rails/application.rb:585:in `validate_secret_key_base'
/usr/local/bundle/gems/railties-5.2.2/lib/rails/application.rb:432:in `secret_key_base'
/usr/local/bundle/gems/railties-5.2.2/lib/rails/application.rb:176:in `key_generator'
/usr/local/bundle/gems/railties-5.2.2/lib/rails/application.rb:205:in `message_verifier'
/usr/local/bundle/gems/activestorage-5.2.2/lib/active_storage/engine.rb:81:in `block (2 levels) in <class:Engine>'
/usr/local/bundle/gems/activesupport-5.2.2/lib/active_support/lazy_load_hooks.rb:69:in `block in execute_hook'
/usr/local/bundle/gems/activesupport-5.2.2/lib/active_support/lazy_load_hooks.rb:62:in `with_execution_control'
/usr/local/bundle/gems/activesupport-5.2.2/lib/active_support/lazy_load_hooks.rb:67:in `execute_hook'
/usr/local/bundle/gems/activesupport-5.2.2/lib/active_support/lazy_load_hooks.rb:52:in `block in run_load_hooks'
/usr/local/bundle/gems/activesupport-5.2.2/lib/active_support/lazy_load_hooks.rb:51:in `each'
/usr/local/bundle/gems/activesupport-5.2.2/lib/active_support/lazy_load_hooks.rb:51:in `run_load_hooks'
/usr/local/bundle/gems/railties-5.2.2/lib/rails/application/finisher.rb:75:in `block in <module:Finisher>'
/usr/local/bundle/gems/railties-5.2.2/lib/rails/initializable.rb:32:in `instance_exec'
/usr/local/bundle/gems/railties-5.2.2/lib/rails/initializable.rb:32:in `run'
/usr/local/bundle/gems/railties-5.2.2/lib/rails/initializable.rb:61:in `block in run_initializers'
/usr/local/lib/ruby/2.5.0/tsort.rb:228:in `block in tsort_each'
/usr/local/lib/ruby/2.5.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
/usr/local/lib/ruby/2.5.0/tsort.rb:431:in `each_strongly_connected_component_from'
/usr/local/lib/ruby/2.5.0/tsort.rb:349:in `block in each_strongly_connected_component'
/usr/local/lib/ruby/2.5.0/tsort.rb:347:in `each'
/usr/local/lib/ruby/2.5.0/tsort.rb:347:in `call'
/usr/local/lib/ruby/2.5.0/tsort.rb:347:in `each_strongly_connected_component'
/usr/local/lib/ruby/2.5.0/tsort.rb:226:in `tsort_each'
/usr/local/lib/ruby/2.5.0/tsort.rb:205:in `tsort_each'
/usr/local/bundle/gems/railties-5.2.2/lib/rails/initializable.rb:60:in `run_initializers'
/usr/local/bundle/gems/railties-5.2.2/lib/rails/application.rb:361:in `initialize!'
/app/config/environment.rb:5:in `<top (required)>'
/usr/local/bundle/gems/activesupport-5.2.2/lib/active_support/dependencies.rb:291:in `require'
/usr/local/bundle/gems/activesupport-5.2.2/lib/active_support/dependencies.rb:291:in `block in require'
/usr/local/bundle/gems/activesupport-5.2.2/lib/active_support/dependencies.rb:257:in `load_dependency'
/usr/local/bundle/gems/activesupport-5.2.2/lib/active_support/dependencies.rb:291:in `require'
/usr/local/bundle/gems/railties-5.2.2/lib/rails/application.rb:337:in `require_environment!'
/usr/local/bundle/gems/railties-5.2.2/lib/rails/application.rb:520:in `block in run_tasks_blocks'
/usr/local/bundle/gems/rake-12.3.2/lib/rake/task.rb:273:in `block in execute'
/usr/local/bundle/gems/rake-12.3.2/lib/rake/task.rb:273:in `each'
/usr/local/bundle/gems/rake-12.3.2/lib/rake/task.rb:273:in `execute'
/usr/local/bundle/gems/rake-12.3.2/lib/rake/task.rb:214:in `block in invoke_with_call_chain'
/usr/local/lib/ruby/2.5.0/monitor.rb:226:in `mon_synchronize'
/usr/local/bundle/gems/rake-12.3.2/lib/rake/task.rb:194:in `invoke_with_call_chain'
/usr/local/bundle/gems/rake-12.3.2/lib/rake/task.rb:183:in `invoke'
/usr/local/bundle/gems/sprockets-rails-3.2.1/lib/sprockets/rails/task.rb:62:in `block (2 levels) in define'
/usr/local/bundle/gems/rake-12.3.2/lib/rake/task.rb:273:in `block in execute'
/usr/local/bundle/gems/rake-12.3.2/lib/rake/task.rb:273:in `each'
/usr/local/bundle/gems/rake-12.3.2/lib/rake/task.rb:273:in `execute'
/usr/local/bundle/gems/rake-12.3.2/lib/rake/task.rb:214:in `block in invoke_with_call_chain'
/usr/local/lib/ruby/2.5.0/monitor.rb:226:in `mon_synchronize'
/usr/local/bundle/gems/rake-12.3.2/lib/rake/task.rb:194:in `invoke_with_call_chain'
/usr/local/bundle/gems/rake-12.3.2/lib/rake/task.rb:238:in `block in invoke_prerequisites'
/usr/local/bundle/gems/rake-12.3.2/lib/rake/task.rb:236:in `each'
/usr/local/bundle/gems/rake-12.3.2/lib/rake/task.rb:236:in `invoke_prerequisites'
/usr/local/bundle/gems/rake-12.3.2/lib/rake/task.rb:213:in `block in invoke_with_call_chain'
/usr/local/lib/ruby/2.5.0/monitor.rb:226:in `mon_synchronize'
/usr/local/bundle/gems/rake-12.3.2/lib/rake/task.rb:194:in `invoke_with_call_chain'
/usr/local/bundle/gems/rake-12.3.2/lib/rake/task.rb:183:in `invoke'
/usr/local/bundle/gems/rake-12.3.2/lib/rake/application.rb:160:in `invoke_task'
/usr/local/bundle/gems/rake-12.3.2/lib/rake/application.rb:116:in `block (2 levels) in top_level'
/usr/local/bundle/gems/rake-12.3.2/lib/rake/application.rb:116:in `each'
/usr/local/bundle/gems/rake-12.3.2/lib/rake/application.rb:116:in `block in top_level'
/usr/local/bundle/gems/rake-12.3.2/lib/rake/application.rb:125:in `run_with_threads'
/usr/local/bundle/gems/rake-12.3.2/lib/rake/application.rb:110:in `top_level'
/usr/local/bundle/gems/rake-12.3.2/lib/rake/application.rb:83:in `block in run'
/usr/local/bundle/gems/rake-12.3.2/lib/rake/application.rb:186:in `standard_exception_handling'
/usr/local/bundle/gems/rake-12.3.2/lib/rake/application.rb:80:in `run'
/usr/local/bundle/gems/rake-12.3.2/exe/rake:27:in `<top (required)>'
/usr/local/bundle/bin/rake:23:in `load'
/usr/local/bundle/bin/rake:23:in `<top (required)>'
/usr/local/lib/ruby/gems/2.5.0/gems/bundler-1.16.6/lib/bundler/cli/exec.rb:74:in `load'
/usr/local/lib/ruby/gems/2.5.0/gems/bundler-1.16.6/lib/bundler/cli/exec.rb:74:in `kernel_load'
/usr/local/lib/ruby/gems/2.5.0/gems/bundler-1.16.6/lib/bundler/cli/exec.rb:28:in `run'
/usr/local/lib/ruby/gems/2.5.0/gems/bundler-1.16.6/lib/bundler/cli.rb:424:in `exec'
/usr/local/lib/ruby/gems/2.5.0/gems/bundler-1.16.6/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
/usr/local/lib/ruby/gems/2.5.0/gems/bundler-1.16.6/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
/usr/local/lib/ruby/gems/2.5.0/gems/bundler-1.16.6/lib/bundler/vendor/thor/lib/thor.rb:387:in `dispatch'
/usr/local/lib/ruby/gems/2.5.0/gems/bundler-1.16.6/lib/bundler/cli.rb:27:in `dispatch'
/usr/local/lib/ruby/gems/2.5.0/gems/bundler-1.16.6/lib/bundler/vendor/thor/lib/thor/base.rb:466:in `start'
/usr/local/lib/ruby/gems/2.5.0/gems/bundler-1.16.6/lib/bundler/cli.rb:18:in `start'
/usr/local/lib/ruby/gems/2.5.0/gems/bundler-1.16.6/exe/bundle:30:in `block in <top (required)>'
/usr/local/lib/ruby/gems/2.5.0/gems/bundler-1.16.6/lib/bundler/friendly_errors.rb:124:in `with_friendly_errors'
/usr/local/lib/ruby/gems/2.5.0/gems/bundler-1.16.6/exe/bundle:22:in `<top (required)>'
/usr/local/bin/bundle:23:in `load'
/usr/local/bin/bundle:23:in `<main>'
Tasks: TOP => environment
The command '/bin/sh -c bundle exec rake assets:precompile --trace' returned a non-zero code: 1
ERROR: build error: exit status 1
ERROR: build error: exit status 1
ERROR: build failed
Exited with code 1

**Comment by eileencodes** [comment]
Hey @Arepo it's pretty difficult to debug without a reproduction. I recall in the 3.2 to 5.2 upgrade we did at GitHub that 5.2 worked fine going from 4.2 and I don't think we had any issues with the `secret_key_base` after 4.2. However we don't use sprockets so maybe that's a key to the issue.

Can you double triple check that your staging environment has `SECRET_KEY_BASE` set in the env? Also check that you've not configured your application to use encrypted secrets if you aren't actually using them by looking for `config.require_master_key = true` and `config.read_encrypted_secrets = true` and also checking you didn't create an encrypted secrets file `config/credentials.yml.enc`

**Comment by Arepo** [comment]
Hey Eileen, I'll check through those questions and report back.

Meanwhile, having tried to step through a guide to implementing the new credentials approach (
* run `bundle exec rake assets:precompile --trace`
* save the file
* add the contents of master.key to to the env var `RAILS_MASTER_KEY`
* redeploy)

I'm getting this result:

RUN bundle exec rake assets:precompile --trace
 ---> Running in a11b5c221b30
** Invoke assets:precompile (first_time)
** Invoke assets:environment (first_time)
** Execute assets:environment
** Invoke environment (first_time)
** Execute environment
** [Raven] Raven 0.15.6 configured not to send errors.
Missing encryption key to decrypt file with. Ask your team for your master key and write it to /app/config/master.key or put it in the ENV['RAILS_MASTER_KEY'].

So now I'm wondering if there's something in the upgrade that has caused our production environment to be unable to find the env variables at all - but can't think of a way to test the theory at the moment, since the deploy failing means the previous version has remained in place.

**Comment by eileencodes** [comment]
I don't think anything would strip the environment variables. Did you check if they were set on staging and production? IIRC Rails 4.2 didn't use them unless they were set but did warn you if they weren't set.
