### ISSUE TITLE
schema.rb does contain references to foreign keys

### ISSUE THREAD

**Issue by ultrawebmarketing** [rails/rails#35207]
When reloading your database using `schema.rb` with `rake db:drop db:schema:load`, the schema.rb files does not contain any reference to foreign keys. The only way to regenerate foreign keys is to run the migrations again. This is the exact opposite of what rails recommends as quoted from the schema.rb file iteslf:

```
# Note that this schema.rb definition is the authoritative source for your
# database schema. If you need to create the application database on another
# system, you should be using db:schema:load, not running all the migrations
# from scratch. The latter is a flawed and unsustainable approach (the more migrations
# you'll amass, the slower it'll run and the greater likelihood for issues).
```

### Steps to reproduce
```
# run the following at the command prompt
rails g model companies name:string
rails g model users name:string company:references
rake db:migrate

# the following migrations will be created 
class CreateCompanies < ActiveRecord::Migration[5.2]
  def change
    create_table :companies do |t|
      t.string :name

      t.timestamps
    end
  end
end

# notice the foreign_key: true. 
class CreateUsers < ActiveRecord::Migration[5.2]
  def change
    create_table :users do |t|
      t.string :name
      t.references :company, foreign_key: true

      t.timestamps
    end
  end
end
```
Run the migrations with `rake db:migrate` and you will see that sqlite actually creates foreign keys reference in the database.

However if you look at the schema.rb file, there are no references to any foreign keys, as such if you recreated your database with `rake db:drop db:schema:load` the database would be created without any foreign keys.

```
ActiveRecord::Schema.define(version: 2019_02_09_180421) do
  create_table "companies", force: :cascade do |t|
    t.string "name"
    t.datetime "created_at", null: false
    t.datetime "updated_at", null: false
  end

  create_table "users", force: :cascade do |t|
    t.integer "company_id"
    t.string "name"
    t.datetime "created_at", null: false
    t.datetime "updated_at", null: false
    t.index ["company_id"], name: "index_users_on_company_id"
  end
end
```

### Expected behavior
Running `rake db:schema:load` should recreate foreign keys.

### Actual behavior
No foreign keys are created

### System configuration
Rails: 5.2.1
Ruby: ruby 2.3.7p456 (2018-03-28 revision 63024) [i686-linux]

**Comment by jcarlson** [comment]
Can this fix be back-ported to Rails 5? Upgrading to Rails 6 to fix this regression seems like overkill.
