### ISSUE TITLE
ActionText: actiontext/lib/action_text/content.rb#to_s

### ISSUE THREAD

**Issue by hahmed** [rails/rails#35225]
### Steps to reproduce
At the moment `actiontext/lib/action_text/content.rb#to_s` delegates to `to_rendered_html_with_layout` which means every time an attribute with `has_rich_text` is called a layout is rendered. 

```
class Post < ApplicationRecord
  has_rich_text :description
end
```

Let's say I want to pull out all posts and save off the descriptions into a csv, I feel like we don't really need to render the layout for every model pulled from the db. The tag helper `actiontext/app/helpers/action_text/tag_helper.rb` editable_value calls out to `value&.body.try(:to_trix_html)` which means in the views the expected behaviour will occur, I'm happy to open a PR and make the fix if this sounds reasonable?

cc/ @georgeclaghorn 

```
irb(main):010:0> posts = Post.all.with_rich_text_description
  Post Load (0.3ms)  SELECT "posts".* FROM "posts" LIMIT ?  [["LIMIT", 11]]
  ActionText::RichText Load (0.3ms)  SELECT "action_text_rich_texts".* FROM "action_text_rich_texts" WHERE "action_text_rich_texts"."record_type" = ? AND "action_text_rich_texts"."name" = ? AND "action_text_rich_texts"."record_id" = ?  [["record_type", "Post"], ["name", "description"], ["record_id", 1]]
=> #<ActiveRecord::Relation [#<Post id: 1, title: "Jumpin' Jacobin", message_id: 4, created_at: "2019-02-08 07:59:15", updated_at: "2019-02-08 07:59:15">]>
irb(main):011:0> posts.first.description
  Post Load (0.4ms)  SELECT "posts".* FROM "posts" ORDER BY "posts"."id" ASC LIMIT ?  [["LIMIT", 1]]
  ActionText::RichText Load (0.3ms)  SELECT "action_text_rich_texts".* FROM "action_text_rich_texts" WHERE "action_text_rich_texts"."record_type" = ? AND "action_text_rich_texts"."name" = ? AND "action_text_rich_texts"."record_id" = ?  [["record_type", "Post"], ["name", "description"], ["record_id", 1]]
  Rendered /Users/haroon/projects/rails-dev-box/rails/actiontext/app/views/action_text/content/_layout.html.erb (Duration: 3.6ms | Allocations: 474)
=> #<ActionText::RichText id: 1, name: "description", body: #<ActionText::Content "<div class=\"trix-conte...">, record_type: "Post", record_id: 1, created_at: "2019-02-08 07:59:15", updated_at: "2019-02-08 07:59:15">
```

### Expected behavior
Should not render the layout?

### Actual behavior
`rails/actiontext/app/views/action_text/content/_layout.html.erb` get's rendered.

### System configuration
**Rails version**: master

**Ruby version**: 2.6.0

**Comment by georgeclaghorn** [comment]
This is the intended behavior. The common case is rendering rich text in HTML views. If you don’t want fully-rendered HTML, use `ActionText::Content#to_html`.
