### ISSUE TITLE
db:structure:dump chokes on Regexp in ActiveRecord::SchemaDumper.ignore_tables

### ISSUE THREAD

**Issue by m-bucher** [rails/rails#35220]
### Steps to reproduce
Add Regexp to ActiveRecord::SchemaDumper.ignore_tables, e.g.
`ActiveRecord::SchemaDumper.ignore_tables << /^dynflow_.*$/`

Try to dump structure by doing `rake db:structure:dump`

### Expected behavior
Either ignore Regexp values in db:structure:dump altogether, or try to resolve it to actually existing tables in the db and use the actual table-names as cmd-line parameter

### Actual behavior
Fails with TypeError (conversion of Regexp to String), because it creates a command-line that receives the ignored_tables as Parameter (e.g. `pg_dump`).
```
TypeError: no implicit conversion of Regexp into String
activerecord-5.2.1/lib/active_record/tasks/postgresql_database_tasks.rb:117:in `system'
activerecord-5.2.1/lib/active_record/tasks/postgresql_database_tasks.rb:117:in `run_cmd'
activerecord-5.2.1/lib/active_record/tasks/postgresql_database_tasks.rb:78:in `structure_dump'
activerecord-5.2.1/lib/active_record/tasks/database_tasks.rb:228:in `structure_dump'
activerecord-5.2.1/lib/active_record/railties/databases.rake:287:in `block (3 levels) in <main>'
...
```

### System configuration
**Rails version**: 5.2.1

**Ruby version**: 2.5.1

**Comment by bjeanes** [comment]
I can still reproduce this on Rails 5.2 and Rails 6.1. This is still an issue.
