### ISSUE TITLE
`adapter_name()` in migration logs 

### ISSUE THREAD

**Issue by palkan** [rails/rails#35224]
### Steps to reproduce

Run `rails db:migrate` with some migrations. 

### Actual behavior

The migration log contains a lot of `adapter_name()` lines:

```
== 20190114215416 CreatePosts: migrating =============================
-- adapter_name()
   -> 0.0000s
-- adapter_name()
   -> 0.0005s
-- adapter_name()
   -> 0.0001s
-- create_table(:posts, {:id=>:integer})
   -> 0.0445s
== 20190114215416 CreatePosts: migrated (0.0486s) ====================
```

Is this intentional?

### System configuration
**Rails version**: 6.0.0.beta1

**Ruby version**: 2.5.3

**Comment by rafaelfranca** [comment]
I just create a new Rails application and could not reproduce this. 
Can you provide an example application that reproduce the issue?

**Comment by palkan** [comment]
> Can you provide an example application that reproduce the issue?

Sure.

**Comment by kamipo** [comment]
Thanks for the report. It is only happened in the migration compatibility.
That internal method call is not intended to be logged. I've fixed in eb7c71bcd3d0c7e079dffdb11e43fb466eec06aa.

**Comment by kaspth** [comment]
It seems like we could accidentally add back the delegation in another commit in the future. I wonder if there’s a way to prevent that.

**Comment by kamipo** [comment]
Yeah... probably the compatibility implementation should not be built on the subclass of the migration class to prevent that.

**Comment by kaspth** [comment]
I think the subclassing is pretty handy and probably why @matthewd made it that way. I don’t think he knew the adapter_name would be logged though.

Hm, we can’t really override connection in those compatibility layers. The other option would be to make the logging selective. But by then the cure may be worse than the disease.
