### ISSUE TITLE
`deliver.action_mailer` message not getting sent

### ISSUE THREAD

**Issue by pezholio** [rails/rails#35234]
### Steps to reproduce

I'm trying to add some logging to my mailers, and I thought hooking into the `deliver.action_mailer` message would be a good way forward. As part of my initial investigations, I've added a hook that just runs `binding.pry`, so I can see what gets sent as part of the payload and added it as a file to my config/initializers folder like so:

```ruby
# config/initializers/audit_subscriptions.rb
ActiveSupport::Notifications.subscribe 'deliver.action_mailer' do |*args|
  binding.pry
end
```

I'm then `deliver`ing my mailer in my existing rspec tests suite like so:

```ruby
let(:mail) { SubscriptionMailer.daily_alert(subscription.id, vacancies.pluck(:id)) }
...
it 'runs the hook' do
  mailer.deliver!
end
...
```

### Expected behavior

When running my tests, I would expect to be dropped into a `pry` console when the `runs the hook` test gets run

### Actual behavior

I don't get dropped into a console, and the code in `config/initializers/audit_subscriptions.rb` appears not to run at all.

### System configuration
**Rails version**: 5.2.1

**Ruby version**: 2.4.1

**Comment by y-yagi** [comment]
Please use `deliver_now(!)` or `deliver_later(!)`. Since `deliver!` is not a method of Action Mailer, the event is not called.
