### ISSUE TITLE
I am getting this "Rails ExecJS::ProgramError in Pages#home"

### ISSUE THREAD

**Issue by theshashiverma** [rails/rails#35231]
I am getting this "Rails ExecJS::ProgramError in Pages#home" error in browser, when i go to the root path which is pages#home. I am using windows 10. untill i dont add the bootstrap it works fine but after adding bootstrap and jquery i get this error . I follow this article to add bootstrap in my project https://www.rubydoc.info/gems/bootstrap/4.2.1

**Comment by sikachu** [comment]
Closing this to continue the discussion on #35233
