### ISSUE TITLE
Why I am getting this "Rails ExecJS::ProgramError in Pages#home"? What is the REASON??

### ISSUE THREAD

**Issue by theshashiverma** [rails/rails#35233]
I am getting this "Rails ExecJS::ProgramError in Pages#home" error in browser, when i go to the root path which is pages#home. I am using windows 10. untill i dont add the bootstrap it works fine but after adding bootstrap and jquery i get this error . I follow this article to add bootstrap in my project https://www.rubydoc.info/gems/bootstrap/4.2.1

AND WHY I AM GETTING THIS ERROR ? WHILE USING UBUNTU I DID NOT FACE THAT BUT WHY IN WINDOWS(10)?

**Comment by sikachu** [comment]
Thank you for your report. That error comes up from the ExecJS gem, which is what Rails uses to figure out how to compile your JavaScript files.

I think a lot of Rails contributors aren't using Windows 10 as a development environment, so something like this could slip through the cracks. So, thanks again for your report.

I did some quick search and it seems like https://stackoverflow.com/a/14118913 would fix the problem. Would you mind trying it out and see if it solves your issue? 

Regardless, I'm going to close this issue and let's move to ExecJS repository so we can keep the issue contained there. We definitely want to fix the issue if Rails and asset pipeline no longer working under Windows 10. So, would you mind creating a new issue in https://github.com/rails/execjs/issues/new providing the simple reproducible steps?
