### ISSUE TITLE
Can't authenticate incoming email to ActionMailbox from Amazon Ingress

### ISSUE THREAD

**Issue by manufaktor** [rails/rails#35243]
### Steps to reproduce
1. Fresh install of Rails 6.0.0.beta1
2. Configure `action_mailbox.ingress = :amazon`, follow the steps in https://edgeguides.rubyonrails.org/action_mailbox_basics.html#configuration
3. Post to `/rails/action_mailbox/amazon/inbound_emails`   
`curl -v -X POST http://localhost:3000/rails/action_mailbox/amazon/inbound_emails`

### Expected behavior
The `verifier` accessed in `ActionMailbox::Ingresses::Amazon::InboundEmailsController#authenticate` is an `Aws::SNS::MessageVerifier`

### Actual behavior
The `verifier` is `nil`
Ingresses::Amazon::InboundEmailsController.prepare is never called

### System configuration
**Rails version**:
6.0.0.beta1

**Ruby version**:
2.6.0

### Repo to reproduce:

https://github.com/manufaktor/mailbox-test

Added an Integration test (run `bin/rails test`) but without assertion, since I was playing around with the code to figure out what it should be doing in the first place. The `POST` already raises the issue though. 

Tried to get this running with an SNS post to mailbox endpoint because I needed to access the SNS confirmation, but got stuck along the way because the verifier wasn't called in the first place. 

It looks like the `self.prepare` method in `ActionMailbox::Ingresses::Amazon::InboundEmailsController#authenticate` is never called, because `config.to_prepare` in https://github.com/rails/rails/blob/7432e251873690234d0d288e8eb009fbee80b635/actionmailbox/lib/action_mailbox/engine.rb#L35 seems to never be called (at least in Development, didn't test production yet)

**Comment by georgeclaghorn** [comment]
Thanks for the report! This is fixed in ef602f8.
