### ISSUE TITLE
Unexpected behaviour for Rails.env.X?

### ISSUE THREAD

**Issue by franzen** [rails/rails#35250]
### Steps to reproduce
```bash
$ rails c
Loading development environment (Rails 5.2.2)
[1] pry(main)> Rails.env.testX
NoMethodError: undefined method `testX' for "development":ActiveSupport::StringInquirer
from /Users/nils/.rvm/gems/ruby-2.5.3/gems/activesupport-5.2.2/lib/active_support/string_inquirer.rb:30:in `method_missing'
[2] pry(main)> Rails.env.testX?
=> false
[3] pry(main)> 
```

### Expected behavior
I expect "NoMethodError" exception for both cases

The problem with current behavior is that I cannot find misspelled __Rails.env.testX?__ when running unit tests.

### Actual behavior
testX? returns false instead of throwing "NoMethodError"

### System configuration
**Rails version**:  5.2.2
**Ruby version**: 2.5.3p105 (2018-10-18 revision 65156) [x86_64-darwin18]

**Comment by vinistock** [comment]
The StringInquirer simply allows you to invoke any method ending with "?" and then checks if the method name you passed matches the string.

```ruby
ActiveSupport::StringInquirer.new("development").something? # false because "development" is not equal to "something"
ActiveSupport::StringInquirer.new("development").development? # true because "development" is equal to "development"
```

Even for valid environments, if you try to invoke it without the "?", it will always throw a NoMethodError.

```ruby
ActiveSupport::StringInquirer.new("development").development # also throws NoMethodError
```
