### ISSUE TITLE
Edit/remove note about learning RDBMS and SQL in Active Record Basics?

### ISSUE THREAD

**Issue by danielcompton** [rails/rails#35260]
I was reading the [Active Record Basics](https://edgeguides.rubyonrails.org/active_record_basics.html) guide having just watched [DHH's FIXME talk](https://www.youtube.com/watch?v=zKyv-IGvgGE). In it he talks about conceptual compression and praising not needing to know SQL to get started with Rails. I was surprised by this note in the guide:

<img width="673" alt="NOTE: If you are not familiar enough with relational database management systems (RDBMS) or structured query language (SQL), please go through this tutorial(or this one) or study them by other means. Understanding how relational databases work is crucial to understanding Active Records and Rails in general." src="https://user-images.githubusercontent.com/811954/52680841-d700c180-2f9e-11e9-91b1-797cc3b0488d.png">

> 

I wondered if it might be better to change the language here a little bit? Perhaps to suggest it as something you can look at if you're interested but is not necessary to get started with Active Record/Rails? It's still useful information to be sure, so you may not want to remove it entirely.

**Comment by gmcgibbon** [comment]
I agree. I think knowing the basics about relational data is what is most important. I can try to reword this.
