### ISSUE TITLE
case_sensitive_comparison fails and case_insensitive_comparison succeeds on same input

### ISSUE THREAD

**Issue by brchristian** [rails/rails#35264]
### Steps to reproduce

```ruby
 def test_case_sensitive_comparison
    post1 = Post.create!(title: 'foo')
    post2 = Post.create!(title: 'bar')

    @model_class = Post
    @field = 'name'
    @value = 'foo'

    cic = @model_class.connection.case_insensitive_comparison(
      @model_class.arel_table,
      @field,
      @model_class.columns_hash[@field],
      @value
    )

    csc = @model_class.connection.case_sensitive_comparison(
      @model_class.arel_table,
      @field,
      @model_class.columns_hash[@field],
      @value
    )

    assert_equal post1, Post.where(cic).first
    assert_equal post1, Post.where(csc).first
  end
```

### Expected behavior
Both tests should pass with all database adapters.

### Actual behavior
In MySql, the first test will pass and the second test will fail with the following message:

```
Arel::Visitors::UnsupportedVisitError (Unsupported argument type: String. Construct an Arel node instead.)
```

### System configuration
**Rails version**: 5.2.2

**Ruby version**: 2.6.0

(See also the original discussion which began in https://github.com/binarylogic/authlogic/issues/654 before identifying that the problem resided in AR.)

**Comment by brchristian** [comment]
FWIW, I think that the Rails contributor most qualified to look into this would be @kamipo as I know he has worked in this area.

Rails used to have a MySql-specific `case_insensitive_comparison`, for instance, before it was removed in https://github.com/rails/rails/commit/4da96789273077e6afbee156803ecac846188c90.

The MySql-specific `case_sensitive_comparison` remains. This may explain why `case_sensitive_comparison` succeeds and `case_insensitive_comparison` fails in MySql.

**Comment by rafaelfranca** [comment]
Those methods are private API of the framework and should not be used in libraries and applications.

**Comment by brchristian** [comment]
@rafaelfranca If these are intended to be private methods, should we make them `private` methods?

**Comment by rafaelfranca** [comment]
Private methods are about method visibility not API visibility. Every single method in Rails that is not in the documentation site is private API. If a method have a `# :nodoc:` on its side on it is inside a constant with `# nodoc`. it is private API and doesn't show in the documentation site exactly to enforce their "internal to AT" nature.

See https://github.com/rails/rails/blob/79b8b626216b4f8f24b5606f3edd43d5b14cd2a6/activerecord/lib/active_record/connection_adapters/abstract_adapter.rb#L513 as example

**Comment by brchristian** [comment]
@rafaelfranca Thanks for taking the time to explain! Okay, I will work on moving some libraries away from using these methods.
