### ISSUE TITLE
Allow a way of disabling `yarn install` on assets:precompile

### ISSUE THREAD

**Issue by mobilutz** [rails/rails#35272]
The rails application I am working on uses webpack (together with yarn install) before running assets precompiling on its own. So we don't depend on precompile to install yarn or do anything with webpack.

Therefore I would request an option to disable the rake task enhancement here:
https://github.com/rails/rails/blob/5-2-stable/railties/lib/rails/tasks/yarn.rake#L17

I thought about doing it myself by including some `if ENV.fetch("NO_YARN")` or something similar to the linked line, but I don't know if that would be the best way to do it.

During our capistrano deployement, we get this fortunately not deployment failing error:
```
03:35 deploy:assets:precompile
      01 /home/app/app/rvm1scripts/rvm-auto.sh . bundle exec rake assets:precompile
      01 /usr/share/yarn/lib/cli.js:45726
      01   let {
      01       ^
      01
      01 SyntaxError: Unexpected token {
      01     at exports.runInThisContext (vm.js:53:16)
      01     at Module._compile (module.js:374:25)
      01     at Object.Module._extensions..js (module.js:417:10)
      01     at Module.load (module.js:344:32)
      01     at Function.Module._load (module.js:301:12)
      01     at Module.require (module.js:354:17)
      01     at require (internal/module.js:12:17)
      01     at Object.<anonymous> (/usr/share/yarn/bin/yarn.js:24:13)
      01     at Module._compile (module.js:410:26)
      01     at Object.Module._extensions..js (module.js:417:10)
      01 yarn install v1.12.3
      01 warning You are using Node "4.2.6" which is not supported and may encounter bugs or unexpected behavior. Yarn supports the following semver range: "^4.8.0 || ^5.7.0 || ^6.2.2 || >=8.0.0"
      01 [1/5] Validating package.json...
      01 error app@18.0.0: The engine "node" is incompatible with this module. Expected version "8.15.0". Got "4.2.6"
      01 error Found incompatible module
      01 info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
      01 Yarn executable was not detected in the system.
      01 Download Yarn at https://yarnpkg.com/en/docs/install
```

PS: Yes, we could solve the error by just installing node directly on the server, but for node we use nvm in previous capistrano steps, and adding node just to make precompile happy is not an option right now. And the yarn install is not even needed for us by precompile.

**Comment by jakeNiemiec** [comment]
Are you trying to destructure something? `let {` seems like the issue. 

> `You are using Node "4.2.6" which is not supported and may encounter bugs or unexpected behavior.`

Node is warning that the version you are using is not supported. Node@4 is from 2015, it's no surprise that is doesn't work. Is `nvm install 10` not an option?

**Comment by mobilutz** [comment]
@jakeNiemiec We are using `nvm` for our normal webpack generation. But rails `yarn install` is not using any nvm call.
See:
https://github.com/rails/rails/blob/5-2-stable/railties/lib/rails/tasks/yarn.rake#L11

That is why I asking if there would be a way to disable the `yarn install` completely during assets precompiling.

And just to reinforce this: This is not a bug report, as our precompile works and our JS is correct, we just don't need the additional system call from rails.

**Comment by smeriwether** [comment]
Although this is a good idea (I could certainly use this), the issue tracker isn't the place for feature requests. See [Section 1.4 of Contributing to Rails](https://edgeguides.rubyonrails.org/contributing_to_ruby_on_rails.html#what-about-feature-requests-questionmark).

This is the message given by members of the Rails team regarding feature requests:
```
We recommend you to try to implement the feature and send us a pull request or if you are in doubt if the feature will be accepts ask in Rails Core mailing list for feedback.
```

**Comment by mobilutz** [comment]
@smeriwether Thanks for writing the information here. I did not know beforehand, where to put such a question. But now I know and I will go to the rails-core mailing list and add the idea there.
