### ISSUE TITLE
Add method to build on a collection proxy without adding to the collection

### ISSUE THREAD

**Issue by eloyesp** [rails/rails#35275]
Currently, when you build an child_object using the collection proxy `build` method it does two different things, it does initialize a new model (without persisting it) and it is added to the collection.

One usual problem is that we need to build the child but we don't want to add it to the target, for example to setup a form or to check permisions. The problem arise when after that we try to use the collection and we find the empty model there.

For example:

``` erb
<%= form_for @blog.comments.new do |f| %>
  ...
<% end %>

<% @blog.comments.each do |c| %>
  <!-- something that would fail with an unpersisted comment -->
<% end %>
```

## Why it happens

This does happen within [this code](https://github.com/rails/rails/blob/master/activerecord/lib/active_record/associations/collection_association.rb#L108):

``` ruby
def build(attributes = {}, &block)
  if attributes.is_a?(Array)
    attributes.collect { |attr| build(attr, &block) }
  else
    add_to_target(build_record(attributes, &block))
  end
end
```

## Possible solutions:

On one hand, we can add a method  on collection proxy to build without attaching like: `@blog.comments.build_record` or add a second optional argument to build for something like: `@blog.comments.new(attach: false)`.

On the other hand, we can add a method to ignore unpersisted childs: `@blog.comments.persisted.each`.

There is also an option to make build and new behave different, but that might be confusing.

## Handmade solutions

Currently is not that hard to solve this manually, but I think it adds some random noise, I've used mainly two methods:

``` erb
<%= form_for Comment.new(blog: @blog) do |f| %>
  ...
<% end %>

<% @blog.comments.map(&:persisted).each do |c| %>
  <!-- something that would fail with an unpersisted comment -->
<% end %>
```

What are your thoughts on this?

**Comment by jvillarejo** [comment]
I prefer to call the resource model class on the action of same resource controller. For example If the this is the new action of the Comments controller I prefer to assign the instance variable like  ```@comment = Comment.new(blog: @blog)``` calling directly the model class and not the association. 

But If you like to call the ```@blog.comments.new``` you can also do: 
```ruby
<%= form_for @blog.comments.new do |f| %>
  ...
<% end %>

<% @blog.comments.reload.each do |c| %>
  <!-- something that would fail with an unpersisted comment -->
<% end %>
```

**Comment by rafaelfranca** [comment]
What @jvillarejo said.

Thank you for the issue.

**Comment by eloyesp** [comment]
@jvillarejo I understand there are multiple handmade solutions to this, and I've already given two handmade solutions for this, but they add noise.

In the examples you give, for example: `@blog.comments.reload.each` adds an actual SQL query (on the view layer) just to remove un-persisted records.

On the first solution you are adding a new instance variable on the view ([Sandy Metz recommends](https://thoughtbot.com/blog/sandi-metz-rules-for-developers) not adding more than one) and you miss some interesting features like [scoped attributes](https://guides.rubyonrails.org/association_basics.html#scopes-for-has-many-where).

The problem I see is that the build method is doing two different things (build + add) and is hiding the build method (that is already there except for the indirection) resulting in doing (build + add - add) adding more work than needed.

Also, I've never see one time where that "adding to the collection" feature were actually used, except when adding empty fields on nested model forms.

**Comment by jvillarejo** [comment]
Yes I understand the trade-off on the the SQL query with the ```reload``` and that there are multiple ways to do it. 

However that the ```build``` doesn't add object to the association also has some caveats as for example a validation that limits the number of comments on the blog. If it the build doesn't adds to the association the validation might pass. 

You can also call ```Comment.new(@blog.comments.scope_attributes)```  to use the scoped attributes as you recall. 

Also following Sandy Metz rule you could use the ```@blog``` as facade and implement a method specific for ```new_comment``` or ```build_comment``` that internally do ```Comment.new(@blog.comments.scope_attributes)```

```ruby
<%= form_for @blog.build_comment do |f| %>
  ...
<% end %>

<% @blog.comments.each do |c| %>
  <!-- something that would fail with an unpersisted comment -->
<% end %>

class Blog < ApplicationRecord
  has_many :comments
  
  def build_comment
    Comment.new(comments.scope_attributes)
  end
end
```

I don't see enough reasons for adding more complexity to the ```build``` method in my opinion.

**Comment by eloyesp** [comment]
I'm not proposing changing the build method, but adding a new method, it seems that something like this makes the trick:

``` ruby
module ActiveRecord
  module Associations
    class CollectionProxy < Relation
      def build_record(attributes = {}, &block)
        @association.build_without_add(attributes, &block)
      end
    end

    class Association
      def build_without_add(attributes = {}, &block)
        if attributes.is_a?(Array)
          attributes.collect { |attr| build_without_add(attr, &block) }
        else
          record = build_record(attributes)
          yield(record) if block_given?
          record
        end
      end
    end
  end
end
```

On the other hand, this method is simpler than the one that is already there.

**Comment by andrewculver** [comment]
@eloyesp I agree with you and I've run into this issue many times. I'm surprised more people don't. I think there should be an additional method for this specific purpose. Have you submitted a PR by chance?

The solution suggested above (e.g. where you modify the behavior of the loop that is iterating over the collection) seem unideal to me... even Rails' default scaffolded logic for the index `<table>` doesn't take into account whether an empty object was incidentally added to the collection, so if for some reason a developer adds that `can? :create, @object.collection.build` check before the table is displayed, all the sudden they will encounter this issue... and I'm not sure it would be very clear why it's happening to them. 

It seems to me that if we add a standard method for `@object.collection.build_independently` or `build_without_add` (as you suggested) or something similar, then the documentation around those authorization libraries like CanCanCan could provide better example logic for people to use, and everyone will be happier and experience more joy in their life. 🤷🏻‍♂️

**Comment by andrewculver** [comment]
Considering this suggestion: 

> `can? :create, Comment.new(@blog.comments.scope_attributes)`

I mean, yes, you can write that... but does it read very naturally as "am I able to create a comment on this blog?" I don't think so. But this does:

`can? :create, @blog.comments.new`. That's what I would write intuitively, but it has the same issue of automatically adding the new object to the collection.

However, that gets me thinking that maybe the solution is updating CanCanCan to support something like `can? :create, @blog.comments` and let it handle the object creation and avoidance of having that object added to the collection. (That syntax doesn't appear to work right now.)

**Comment by andrewculver** [comment]
@eloyesp I know this is specific to the one use case of checking permissions, but for myself I've added the following helper for now and will investigate pushing this upstream later:

```
  # enable `if can? :create, @blog.comments`
  def can?(action, object)
    if object.is_a?(ActiveRecord::Associations::CollectionProxy)
      object = object.model.new(object.scope_attributes)
    end
    super action, object
  end
```

**Comment by jeropaul** [comment]
@andrewculver did you ever investigate pushing this upstream into cancancan?  seems like a very good addition

> @eloyesp I know this is specific to the one use case of checking permissions, but for myself I've added the following helper for now and will investigate pushing this upstream later:
> 
> ```
>   # enable `can? :create, @blog.comments`
>   def can?(action, object)
>     if object.is_a?(ActiveRecord::Associations::CollectionProxy)
>       object = object.model.new(object.scope_attributes)
>     end
>     super action, object
>   end
> ```
> 
> (Thanks @jvillarejo for pointing out `scope_attributes`. I wasn't aware of that!)
