### ISSUE TITLE
Wrong protocol returned from rails_blob_url Active Storage

### ISSUE THREAD

**Issue by vivektiwary** [rails/rails#35283]
### Steps to reproduce
use `rails_blob_url(active_storage.file)` in the jbuilder view.

### Actual behavior
It is returning URL with `HTTP` as protocol even when the application is running on `HTTPs`.

### System configuration
**Rails version**: Rails 5.2.1

**Ruby version**: ruby 2.5.1p57 (2018-03-29 revision 63029) [x86_64-darwin17]

**Comment by connorshea** [comment]
Does this happen with `force_ssl` enabled in the rails config?

**Comment by vkeziah** [comment]
@connorshea not with force_ssl.

I have the same issue on my rails 6.1.x
