### ISSUE TITLE
[feature request] Remove a Validation

### ISSUE THREAD

**Issue by krtschmr** [rails/rails#35282]
Overriding an activerecord model from a gem ist really annoying when it comes down to validations. 
If we need to remove a validation we either remove all validations and then write the new ones in a class_eval or we just replace the entire class in our code. (i'm not aware of other methods).

ActiveRecord should provide a method `remove_validation`

Usage would be

`remove_validation :first_name, :presence`

benefitial would also be conditional option

`remove_validation :first_name, :presence, if: :is_a_robot?`

Thoughts?

**Comment by rafaelfranca** [comment]
Thank you so much for the issue but we don't take feature request on the issue tracker. We recommend you to try to implement the feature and send us a pull request or if you are in doubt if the feature will be accepts ask in Rails Core mailing list for feedback.
