### ISSUE TITLE
SQLite no longer works when using table_name with a dot ex: "foo.bar"

### ISSUE THREAD

**Issue by MaxLap** [rails/rails#35292]
### Steps to reproduce
The following fails on master.
[sqlite_master_demo.txt](https://github.com/rails/rails/files/2871394/sqlite_master_demo.txt)
But the same code ran against rails 5.2, and all version since 4, will pass:
[sqlite_521_demo.txt](https://github.com/rails/rails/files/2871396/sqlite_521_demo.-.Copy.txt)

Without using a complicated file (or creating any table), the following makes it easy to try:
```
class Post < ActiveRecord::Base
  self.table_name = "bar.posts"
end
Post.first
```
In 6.0.0, SQLite whines of a syntax error, while on 5.2.1, it whine of a table that doesn't exist (as expected).

### Expected behavior
When using a "schema" or an "attached database", (names change based on which DB), things normally just work by using a simple `self.table_name = "bar.posts"`. This is no longer the case for SQLite3 in rails 6.0.0.

For the example with Post.first above, the generated SQL should be:
`SELECT  "foo.bar".* FROM "foo.bar" ORDER BY "foo.bar"."id" ASC LIMIT ?`

### Actual behavior
Since 6.0.0, it now does:
`SELECT "foo"."bar".* FROM "foo"."bar" ORDER BY "foo"."bar"."id" ASC LIMIT ?`

### System configuration
**Rails version**: 6.0.0.beta1

**Ruby version**: 2.5.0

### More details
This is the PR that introduced this bug: https://github.com/rails/rails/pull/34626

**Comment by gmcgibbon** [comment]
Here's a [failing test case](https://gist.github.com/gmcgibbon/3fd8695b623b3ea938111b09ab7e7b1f).  This is hard to solve with my quoting patch in place. We might have to try solving the join problem at a different level ([maybe around here](https://github.com/rails/rails/blob/64ef5e2f9e854a7f988227d629a699f11a998b17/activerecord/lib/active_record/relation/query_methods.rb#L1053)). I'll see what I can do!

**Comment by MaxLap** [comment]
Not sure about that test case. I just tried in on 5.2.1 and while it doesn't fail, the returned objects don't have id... Things seems to go somewhat wrong. While using the `ATTACH DATABASE`, things actually work.

So while it does find objects, I wouldn't put much weight onto it. I feel the test case i provided in my post is a better representation (I mean the files I joined, not the embeded code) (the only different between the 2 files is the gem dependencies)

**Comment by MaxLap** [comment]
Ok, so I just discovered that the distinction of if the id is nil or not when you create something comes from using `ActiveRecord::Schema.define` with `create_table`. Just using `execute` to create the table seems to mess things up somewhere.

I figured out a possible solution. Making a PR at the moment.

**Comment by gmcgibbon** [comment]
Sorry, I think that was PG syntax. The query should've been `("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL)`. I've updated the test case.

Either way the test case displays the problem. You shouldn't have to PR anything, you can see the difference in the SQL `create_table` generates. I only used `exec_query` because you can't create tables with dots in the using the schema DSL AFAIK.

**Comment by kamipo** [comment]
Can we close this?
