### ISSUE TITLE
Rails routes "constraints" - feature or bug?

### ISSUE THREAD

**Issue by kapso** [rails/rails#35295]
### Steps to reproduce
I am using `constraints` in the routes...

```ruby
# constraints Subdomain::Admin do # Tried the module approach too, with matches? method
constraints subdomain: 'admin' do
  namespace :admin, path: nil do
    get '*path', to: 'home#show', constraints: ->(request) { request.format.html? }
  end
end

constraints subdomain: 'app' do
  namespace :app, path: nil do
    get '*path', to: 'home#show', constraints: ->(request) { request.format.html? }
  end
end
```

### Expected behavior
- When I go to `admin.domain.com/some/path` => `Admin::HomeController#show` should be invoked.
- When I go to `app.domain.com/some/path` => `App::HomeController#show` should be invoked. 

### Actual behavior
- When I go to `admin.domain.com/some/path` => `Admin::HomeController#show` is invoked 👍 
- When I go to `app.domain.com/some/path` => `Admin::HomeController#show` is invoked 👎why?

Is the `constraints` in `get '*path'` overriding `constraints subdomain: 'admin'` ?? Is this by design or a bug?

### System configuration
**Rails version**: 5.2.2

**Ruby version**: 2.6.1

**Comment by bruno-b-martins** [comment]
Please help me understand your doubt.

You weren't expecting for `Admin::HomeController#show` to be invoked even though you have `to: 'home#show'` in that route?

**Comment by kapso** [comment]
@bruno-b-martins 

`admin.domain.com/some/path` goes to `Admin::HomeController#show` which is as expected 👍 

but why does `app.domain.com/some/path`invoke `Admin::HomeController#show` ??

Note the difference in subdomain for the 2 requests. 

Based on how I have setup the routes, I am expecting that `app.domain.com/some/path` should invoke `App::HomeController#show`

**Comment by bruno-b-martins** [comment]
Thanks for clarifying it! Didn't noticed the difference before. Sorry for that :-P

**Comment by dennym** [comment]
Should be answered over here: https://stackoverflow.com/a/54846844/1202324
