### ISSUE TITLE
ZeitWerk's config.autoloader raises uninitialized method when configuring logger.

### ISSUE THREAD

**Issue by why-el** [rails/rails#35306]
### Steps to reproduce

```
# frozen_string_literal: true

require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  gem "rails", github: "rails/rails", branch: :master
end

require "action_controller/railtie"

class TestApp < Rails::Application
  config.root = __dir__
  config.hosts << "example.org"
  secrets.secret_key_base = "secret_key_base"

  config.logger = Logger.new($stdout)
  Rails.logger  = config.logger
  # byebug
  Rails.autoloader.logger = method(:puts)

  routes.draw do
    get "/" => "test#index"
  end
end

class TestController < ActionController::Base
  include Rails.application.routes.url_helpers

  def index
    render plain: "Home"
  end
end

require "minitest/autorun"
require "rack/test"

class BugTest < Minitest::Test
  include Rack::Test::Methods

  def test_returns_success
    get "/"
    assert last_response.ok?
  end

  private
    def app
      Rails.application
    end
end
```

### Expected behavior

It works, per instructions found at https://github.com/rails/rails/pull/35235. 

### Actual behavior

Raises undefined method: `bug.rb:24:in `<class:TestApp>': undefined method `autoloader' for Rails:Module (NoMethodError)
`

### System configuration
**Rails version**:

Master. Tip: `907280d`

**Ruby version**:

`2.5.3`

cc @fxn.

**Comment by fxn** [comment]
Hey! It was changed to `Rails.autoloaders.main`, and `Rails.autoloaders.once` in https://github.com/rails/rails/commit/870377915af301c98a54f7f588e077610b2190aa. Sorry, slightly in flux while it is in `master`. Documentation will come once it is out.

Alternatively, you can now `Zeitwerk::Loader.default_logger = method(:puts)` to see the activity of all Zeitwerk instances, or

```ruby
ActiveSupport::Dependencies.verbose = true
```

to see the traces of the two created by Rails (`rails.main`, and `rails.once`). I believe this last one has the chances to become the Rails interface to it.

**Comment by why-el** [comment]
Cool, thanks for the prompt response.
