### ISSUE TITLE
action text  genrate test/fixtures even test skiped in new app

### ISSUE THREAD

**Issue by reckerswartz** [rails/rails#35305]
### Steps to reproduce
 New rails app skip mini test with  -T option: `rails new my_app -T`
 add  action text : `rails action_text:install`
### Expected behavior
should  not generate test cases
### Actual behavior
test/fixtures/action_text/rich_texts.yml
is genrated
### System configuration
**Rails version**:
6.0.0 beta1
**Ruby version**:
2.6.1

**Comment by abhaynikam** [comment]
This issue is fixed in #35085 and can be closed. Tested it locally. `test/fixtures` are skipped when `-T` option is used.

**Comment by jonathanhefner** [comment]
Good catch @abhaynikam!  Thank you!
