### ISSUE TITLE
 PG::UniqueViolation: ERROR:  duplicate key value violates unique constraint "index_user_roles_on_name"

### ISSUE THREAD

**Issue by imrrahul** [rails/rails#35300]
### Steps to reproduce
on Running rails db:seed I am getting this error 
`
rails aborted!
ActiveRecord::RecordNotUnique: PG::UniqueViolation: ERROR:  duplicate key value violates unique constraint "index_user_roles_on_name"
`
### System configuration
**Rails version**:
Rails 5.2.0
**Ruby version**:
ruby 2.6.1p33 (2019-01-30 revision 66950) [x86_64-linux]

**Comment by Petercopter** [comment]
What's in the seed file? Are you running against a fresh database?

**Comment by imrrahul** [comment]
It contain all the record creation needed to seed the database with its default values and tables which I have to create,  data can then be loaded with the rails db:seed command (or created alongside the database with db:setup)

**Comment by erhimanshugoyal** [comment]
@imrrahul, this error is on the index, does the seed file also create unique index on the name column, and are there any duplicate entries in your seed file?

**Comment by imrrahul** [comment]
@erhimanshugoyal thanks but I got the solution by removing the existing data which was create by running `rails db:setup`
