### ISSUE TITLE
Counter Cache for Many to Many

### ISSUE THREAD

**Issue by cooldesigns** [rails/rails#35317]
Rails generates more queries on many to many counter caches. There is a post about this. I think it must be re-implemented in rails@6

https://coderwall.com/p/muvy9w/forget-counter-cache-for-many-to-many-associations-in-rails

**Comment by y-yagi** [comment]
Please use the [Rails Core mailing list](https://groups.google.com/forum/#!forum/rubyonrails-core) for feature requests, where a wider community will be able to help you. We reserve the Rails issue tracker only for bugs in Rails. Thanks!
