### ISSUE TITLE
After upgrading to rails 6 experiencing "Unknown key: :on. Valid keys are: :if, :unless, :prepend (ArgumentError)" on callbacks

### ISSUE THREAD

**Issue by atstockland** [rails/rails#35329]
### Steps to reproduce
I'm not exactly sure.  All I did to induce this was upgrade from rails 5.2 to rails 6.  I'm not sure if this is a Rails bug, or a bug in my app.  I would assume the later...however, it did not surface until upgrading.  I'm still looking at it and will update if I get more useful information.

### Expected behavior
No change from Rails 5 on callback methods using :on.

### Actual behavior
callbacks not accepting :on option.  :on results in "Unknown key: :on. Valid keys are: :if, :unless, :prepend (ArgumentError)"

### System configuration
Rails 6.0.0.beta1

**Ruby version**:
ruby 2.6.1p33 (2019-01-30 revision 66950) [x86_64-darwin18]

**Comment by atstockland** [comment]
This appears to be related to [pr](https://github.com/rails/rails/pull/30919).  Rails 6 must have gotten more strict on this...I never encountered it until now.

**Comment by Zyphrax** [comment]
Today I was working on upgrading to Rails 6 RC and encountered this issue.
Perhaps this should be mentioned in the upgrade guide?

@atstockland Can you reopen this issue?

**Comment by atstockland** [comment]
Chances are the callbacks you are calling on for, are not using the on option anyways.  At least that was my experience.  I was calling on, which was silently being ignored...until I upgraded and then it wasn't silent anymore.  In reviewing my code, there were smarter callback options available that didn't need to specify the on option.  This forced me to clean a few things up, and fix this issue.  

What callback methods do you have that are using the on option?

**Comment by Zyphrax** [comment]
I was using the `after_save` to update the `deleted_at` of related entities. A bit like a cascading soft delete. It was only relevant to trigger the `after_save` on update, but that was probably a bit of an unnecessary optimization.

**Comment by sikachu** [comment]
It sounds like `after_update` would be fitting for your use case? https://guides.rubyonrails.org/active_record_callbacks.html#available-callbacks

And yes, I think `:on` has no effect ever on `after_save` and being ignored silently, but #30919 raises an error so you won't miss it.

**Comment by Zyphrax** [comment]
@sikachu Thanks, I'll look into `after_update`, that sounds like exactly what I need.

**Comment by akaspick** [comment]
I'm upgrading my app to Rails 6 and I'm getting the `Unknown key: :on. Valid keys are: :if, :unless, :prepend` error when using `after_save` in a `with on: :custom_context` block.  So when I do `rec.save(context: :custom_context)` the `after_save` callback would only run within that custom context.  

```
with_options on: :shipping do
  after_save :send_shipping_email
end
```

```
rec.save(context: shipping)
```

I'm not sure what the migration path is here when using custom contexts.  Is there a way to obtain the current validation context for use in an `:if` block?  If needed I suppose I can set a custom attribute on my record that my `after_save` callback can check, but the custom contexts were a nice way to avoid doing that.

 Allowing the `:on` option for custom contexts sure is handy.
