### ISSUE TITLE
ActiveStorage 5.2.1 migration fails - Mysql 5.7 - Specified key was too long; max key length is 1000 bytes

### ISSUE THREAD

**Issue by slavajacobson** [rails/rails#35328]
### Steps to reproduce

Installed software:
MySQL 5.7
Rails 5.2.1

Steps taken:
1) Initialize activestorage

2) configure database.yml:

production:
  adapter: mysql2
  encoding: utf8mb4
  collation: utf8mb4_unicode_ci
  reconnect: false
  database: xxxxxxxxxxxxxxx
  pool: 5
  username: xxxxxxxxxxxxxxx
  password: xxxxxxxxxxxxxxx
  host: localhost

I've also tried using encoding utf8

3) Run migration

### Expected behavior
Migration should run successfully

### Actual behavior
MySQL Error:
Mysql2::Error: Specified key was too long; max key length is 1000 bytes: CREATE TABLE `active_storage_attachments` (`id` bigint NOT NULL AUTO_INCREMENT PRIMARY KEY, `name` varchar(255) NOT NULL, `record_type` varchar(255) NOT NULL, `record_id` bigint NOT NULL, `blob_id` bigint NOT NULL, `created_at` datetime NOT NULL,  INDEX `index_active_storage_attachments_on_blob_id`  (`blob_id`), UNIQUE INDEX `index_active_storage_attachments_uniqueness`  (`record_type`, `record_id`, `name`, `blob_id`))

### System configuration
**Rails version**: 5.2.1

**Ruby version**: 2.3

**Comment by slavajacobson** [comment]
Switching ActiveStorage's Table's engine to InnoDB has fixed it.

    create_table :active_storage_blobs**, :options => 'ENGINE=InnoDB'** do |t|
      t.string   :key,        null: false
      t.string   :filename,   null: false
      t.string   :content_type
      t.text     :metadata
      t.bigint   :byte_size,  null: false
      t.string   :checksum,   null: false
      t.datetime :created_at, null: false

      t.index [ :key ], unique: true
    end

    create_table :active_storage_attachments**, :options => 'ENGINE=InnoDB'** do |t|
      t.string     :name,     null: false
      t.references :record,   null: false, polymorphic: true, index: false
      t.references :blob,     null: false

      t.datetime :created_at, null: false

      t.index [ :record_type, :record_id, :name, :blob_id ], name: "index_active_storage_attachments_uniqueness", unique: true
    end

**Comment by jasonfb** [comment]
is that really a good fix?
