### ISSUE TITLE
Rails Guides - 5.6 Replace "@article = Article.new(params[:article])" with "@article = Article.new(article_params)" to avoid ERROR: Forbidden Attributes Error

### ISSUE THREAD

**Issue by DrCool2** [rails/rails#35365]
When following the Getting Started Guide, I ran into the Forbidden Attributes Error.
Please correct me if I am wrong, as I am new to Rails and Programming.
Link: https://guides.rubyonrails.org/getting_started.html#saving-data-in-the-controller

TL;DR (Short) Version:
Broken Code: @article = Article.new(params[:article])
Fixed Code: @article = Article.new(article_params)

Long Version:
  ### Currently Broken
        @article = Article.new(params[:article])
  ### Error
        ActiveModel::ForbiddenAttributesError in ArticlesController#create
        ActiveModel::ForbiddenAttributesError
 ### Steps to Reproduce the Error

1.         Attempt to create a New Article
2.         Fill out Title and Text with appropriate responses
3.         Click Create Article
4.         ERROR - ForbiddenAttributesError

### Suggested Resolution
        @article = Article.new(article_params)
###   Location of Error
5.6 Saving data in the controller
      https://guides.rubyonrails.org/getting_started.html#saving-data-in-the-controller

**Comment by abhaynikam** [comment]
@DrCool2: I think that is expected. If you scroll down a bit in the guides you would find the same error mentioned. The purpose of it is to show that Rails has several security features. 

Try finding following line in the guides here(https://guides.rubyonrails.org/getting_started.html#saving-data-in-the-controller)
```
If you now go to http://localhost:3000/articles/new you'll almost be able to create an article. Try it! You should get an error that looks like this:
```

You would be able to see the same issue mentioned.

**Comment by DrCool2** [comment]
> @DrCool2: I think that is expected. If you scroll down a bit in the guides you would find the same error mentioned. The purpose of it is to show that Rails has several security features.
> 
> Try finding following line in the guides here(https://guides.rubyonrails.org/getting_started.html#saving-data-in-the-controller)
> 
> ```
> If you now go to http://localhost:3000/articles/new you'll almost be able to create an article. Try it! You should get an error that looks like this:
> ```
> You would be able to see the same issue mentioned.

AH! I think you are correct. 
Thank you

**Comment by nikkiricks** [comment]
It's not expected though as it doesn't tell the reader to expect the error when they run it.
