### ISSUE TITLE
Reproduce:  EDITOR='atom --wait' bin/rails credentials:edit

### ISSUE THREAD

**Issue by ThomasConnolly** [rails/rails#35378]
Reproduce:  EDITOR='atom --wait' bin/rails credentials:edit
Expect: editor to open existing credentials.yml file to be edited
Actual: editor creates and immediately saves a new credentials.yml file in temporary folder, leaving the existing encrypted credentials file alone.
Configuration: Ubuntu 18.04, Rails 5.2.2 Ruby 2.5.3

_Originally posted by @ThomasConnolly in https://github.com/rails/rails/issues/35377#issuecomment-466671186_

**Comment by kaspth** [comment]
Yes, that’s expected behavior. So we don’t lose the data in the real credentials file or accidentally write it unencrypted which people could end up comitting.
