### ISSUE TITLE
Schema is unable to set both default value and not null constraint on uuid column

### ISSUE THREAD

**Issue by StefanoDeVuono** [rails/rails#35373]
### Steps to reproduce
On Rails 4.2.11 load a schema that defines a default value for the `uuid` column as the `uuid_generate_v1()` function and set the column to `null: false`

The test case is [here](https://gist.github.com/StefanoDeVuono/1c237faf723ae4ffa65a9aa08c97048e).
### Expected behavior
The `uuid` column should then have _both_ the default value and a not null constraint

### Actual behavior
Only the default value gets set. _No null constraint is set on the DB._

### System configuration
**Rails version**: 4.2.11

**Ruby version**: 2.5.1p57

**Comment by y-yagi** [comment]
Thanks for your report. This already fixed with 5.0 series. Please consider an upgrade. Thanks.

**Comment by StefanoDeVuono** [comment]
@y-yagi Will this be back ported to a version 4 release? 

A Rails 5 upgrade is a valid consideration, but there are going to be Rails 4 applications out there in the world for some time.

**Comment by y-yagi** [comment]
Unfortunately, it is not possible. 4.2 series are not supported anymore for anything besides severe security fixes.
