### ISSUE TITLE
ActiveRecord leaks scope when using first_or_create on relations

### ISSUE THREAD

**Issue by Bombasarkadian** [rails/rails#35398]
This issue seems related to #17577 which was fixed in #35186. But the similar problem still exists when scope is created on relation

### Steps to reproduce
```ruby
# frozen_string_literal: true

require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  gem "rails", github: "rails/rails"
  gem "sqlite3"
end

require "active_record"
require "minitest/autorun"
require "logger"

# This connection will do for database-independent bug reports.
ActiveRecord::Base.establish_connection(adapter: "sqlite3", database: ":memory:")
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :owners, force: true do |t|
    t.string :name
    t.timestamps
  end

  create_table :pets, force: true do |t|
    t.references :owner
    t.string :name
    t.timestamps
  end
end

class Owner < ActiveRecord::Base
  has_many :pets, inverse_of: :owner

  def first_pet_name
    pets.first.name
  end
end

class Pet < ActiveRecord::Base
  belongs_to :owner
end

class BugTest < Minitest::Test
  def test_association_scopes_in_block
    owner = Owner.create!(name: 'TestOwner')
    old_pet = Pet.create!(owner: owner, name: 'TestPet')

    assert_equal(owner.first_pet_name, old_pet.name)

    new_pet = owner.pets.where('created_at < ?', 1.year.ago).first_or_create! do |pet|
      pet.name = owner.first_pet_name
    end
    
    assert_equal(new_pet.name, old_pet.name)
  end
end
```

### Expected behavior
`new_pet` is a Pet with `name` set to `owner.pets.first.name` and both asserts pass.
`owner.pets` relation in `Owner#first_pet_name` method has no scope and returns all Pets with a valid `owner_id`

### Actual behavior
Scope create when using `first_or_create` is still present when using `owner.pets` relation in `Owner#first_pet_name` method. It's filtered both by `owner_id` (which is expected) and `created_at` (which was used in `first_or_create`).
This causes application to fail with:
```
BugTest#test_association_scopes_in_block:
NoMethodError: undefined method `name' for nil:NilClass
    test.rb:39:in `first_pet_name'
    test.rb:55:in `block in test_association_scopes_in_block'
    test.rb:54:in `test_association_scopes_in_block'
``` 

### System configuration
**Rails version**:
`6.0.0.beta1 at master@f4bef91`

**Ruby version**:
`ruby 2.5.1p57 (2018-03-29 revision 63029) [x86_64-darwin17]`

**Comment by bparanj** [comment]
Verified this failure on:
 
**Ruby version**: 2.6.1p33 (2019-01-30 revision 66950) [x86_64-darwin17]
**Rails version**: 6.0.0.beta1 at master@f4bef91

```ruby
Error:
BugTest#test_association_scopes_in_block:
NoMethodError: undefined method `name' for nil:NilClass
    test_case.rb:39:in `first_pet_name'
    test_case.rb:55:in `block in test_association_scopes_in_block'
    test_case.rb:54:in `test_association_scopes_in_block'


rails test test_case.rb:48
```

**Comment by Sora233** [comment]
https://github.com/rails/rails/blob/0a0f115031b64b5335fa88543c40df4194dfb428/activerecord/lib/active_record/relation.rb#L698-L700
It seems the ```scope``` here is not proper.
called from :
https://github.com/rails/rails/blob/0a0f115031b64b5335fa88543c40df4194dfb428/activerecord/lib/active_record/relation.rb#L329-L331
here the ```self``` should drop the unnecessary scope but not.
