### ISSUE TITLE
Additional queries when attaching files in ActiveStorage

### ISSUE THREAD

**Issue by agborrego92** [rails/rails#35409]
### Expected behavior

`article.images.attach(io: File.open(path_to_file), filename: 'file1.txt', metadata: { analyzed: true })`

The file should be attached with no extra queries. Only 2 queries should be executed(it's this way in Rails 5.2.2), one for inserting into active_storage_blobs and the other for active_storage_attachments

### Actual behavior

Two more queries are executed. This will become a performance issue when one model has too many attached files.

```
irb(main):005:0> article.images.attach(io: File.open(path_to_file), filename: 'file1.txt', metadata: { analyzed: true })
  ActiveStorage::Blob Load (0.5ms)  SELECT "active_storage_blobs".* FROM "active_storage_blobs" INNER JOIN "active_storage_attachments" ON "active_storage_blobs"."id" = "active_storage_attachments"."blob_id" WHERE "active_storage_attachments"."record_id" = ? AND "active_storage_attachments"."record_type" = ? AND "active_storage_attachments"."name" = ?  [["record_id", 1], ["record_type", "Article"], ["name", "images"]]
   (0.1ms)  begin transaction
  ActiveStorage::Attachment Load (0.2ms)  SELECT "active_storage_attachments".* FROM "active_storage_attachments" WHERE "active_storage_attachments"."record_id" = ? AND "active_storage_attachments"."record_type" = ? AND "active_storage_attachments"."name" = ?  [["record_id", 1], ["record_type", "Article"], ["name", "images"]]
  ActiveStorage::Blob Create (1.1ms)  INSERT INTO "active_storage_blobs" ("key", "filename", "content_type", "metadata", "byte_size", "checksum", "created_at") VALUES (?, ?, ?, ?, ?, ?, ?)  [["key", "i1ynjy63h2443xyd3mla9s01h1d3"], ["filename", "file1.txt"], ["content_type", "text/plain"], ["metadata", "{\"analyzed\":true,\"identified\":true}"], ["byte_size", 19], ["checksum", "Ck6/YHwwp0mVwwRKAZs8sg=="], ["created_at", "2019-02-25 20:50:20.665843"]]
  ActiveStorage::Attachment Create (0.3ms)  INSERT INTO "active_storage_attachments" ("name", "record_type", "record_id", "blob_id", "created_at") VALUES (?, ?, ?, ?, ?)  [["name", "images"], ["record_type", "Article"], ["record_id", 1], ["blob_id", 1], ["created_at", "2019-02-25 20:50:20.669117"]]
  Article Update (0.1ms)  UPDATE "articles" SET "updated_at" = ? WHERE "articles"."id" = ?  [["updated_at", "2019-02-25 20:50:20.670961"], ["id", 1]]
   (2.0ms)  commit transaction
  Disk Storage (0.7ms) Uploaded file to key: i1ynjy63h2443xyd3mla9s01h1d3 (checksum: Ck6/YHwwp0mVwwRKAZs8sg==)
=> true
irb(main):006:0>
```

### System configuration
**Rails version**: Rails 6.0.0.beta1

**Ruby version**: 2.5.1

**Comment by krunalcp** [comment]
I have **product** model and can have many **photos**. When I try to attach new photo with product it fires N queries of **active_storage_blobs**. Here N is number of photos already attached.

I have tried with includes(so can eager load blobs) it gives me 500 error.

**Comment by arr-dev** [comment]
This is still an issue in Rails 7.0.4.3. I had few thousands attachments on a record and that caused significant performance downgrade of calling `attach`.  It's not just the queries that are the problem, but it actually loads all blobs records.

I understand this interface is to be able to support tracking changes, but there should be at least an alternative interface so we can attach files without the overhead.

**Comment by arr-dev** [comment]
Just to post alternative interface to attaching files when there is large number of attachments, skipping changes tracking, but speeds up uploads dramatically.

```rb
class Article < ApplicationRecord
  has_many_attached :images

  def attach_alternative(io, filename)  
    ActiveStorage::Blob.create_and_upload!(io: io, filename: filename).tap do |blob|
      images_attachments.create!(record: self, blob: blob)
    end
end
```
