### ISSUE TITLE
don't panic on missing tmp cache permissions 

### ISSUE THREAD

**Issue by foonlyboy** [rails/rails#35405]
### Steps to reproduce
I uploaded some modifications in config/locales,
restarted nginx aka the passenger,
got a FATAL

FATAL I18n::InvalidLocaleData (can not load translations from /srv/rack/rockers/releases/2019-02-22/config/locales/models.de.yml: #<Errno::EACCES: Permission denied - bs_fetch:atomic_write_cache_file:open>):

I could fix this easily by a chmod/chown on tmp/

But I'd like to propose that this could be improved:

- The error message is misleading
- No reason to fail FATAL here

This should go to the team at I18n

- improve the error message (no write permission to tmp/cache)
- don't fail FATAL if you can't write a cache (just log an ERROR)

I did not research that in depth,
this was a bit unexpected to me.

I believe I just uploaded an a new localisation,
which should be fine to be read only.

I have fixed the problem with chown/chmod on tmp,
but which I believe was ok before.

I have seen this problem before.
Maybe it's just caused by my faults.

But anyway,
the error message needs to be improved.

---
I would not write an issue,
but I smell a bug around there.

---
Please forward to the I18n team:
- I18n is very important.
- but it should never break on that

The I18n should be really forgiving on any problems
Please do not throw Exceptions from I18n, no matter what.

We'll understand each others anyways,
even if the translation is missing,
and we give a shit on permission problems.

Translation is a best effort,
not a reason to fail.

**Comment by y-yagi** [comment]
I think that raise an exception is an appropriate behavior because processing can not be continued if a cache cannot be generated. But this is judged by developers of i18n gem.
Please create an issue to https://github.com/ruby-i18n/i18n. Thanks.
