### ISSUE TITLE
[actionview] Add name of template for "Single arity template handlers are deprecated." warning

### ISSUE THREAD

**Issue by localhostdotdev** [rails/rails#35413]
### Steps to reproduce

- Have a slim template
- Run `rails server`
- See warning:

```
DEPRECATION WARNING: Single arity template handlers are deprecated.  Template handlers must
now accept two parameters, the view object and the source for the view object.
Change:
  >> #<Class:0x00007fe2d32ac160>#call(template)
To:
  >> #<Class:0x00007fe2d32ac160>#call(template, source)
```

### Expected behavior

- Warning indicates the cause without having to edit the rails's source code

### Actual behavior

- Warning doesn't indicate what's causing the warning

### System configuration

**Rails version**: latest from Github (rails6.beta2)

**Ruby version**: 2.5.0

(I've reported the warning to slim: https://github.com/slim-template/slim/issues/827)

**Comment by rafaelfranca** [comment]
This is actually an issue on slim. It doesn't define a name for its template class so we can't show in the message.

Can you please open an issue on slim repository about that? Here is where they create anonymous class.

https://github.com/judofyr/temple/blob/master/lib/temple/mixins/template.rb#L19
