### ISSUE TITLE
Allow saving the record even if one of a has_many associations fails using nested attributes

### ISSUE THREAD

**Issue by abdelbk** [rails/rails#35427]
Here is my case scenario:

- Model Parent accepts nested attributes for a has_many association Child.
- Model Child has some validations.
- My form is building multiple instances of the model Child using nested attributes.
- After submitting the form, on of the children's validations fail.
- The Parent fails to save and of all the valid associations are not created.

Is it possible to allow saving the Parent even if one of the associations fail to save using accepts_nested_attributes_for ?

**Comment by rafaelfranca** [comment]
Thank you so much for the issue but we don't take feature request on the issue tracker. We recommend you to try to implement the feature and send us a pull request or if you are in doubt if the feature will be accepts ask in Rails Core mailing list for feedback.
