### ISSUE TITLE
ActionMailer: Using multiple self-signed certificates

### ISSUE THREAD

**Issue by K-Sato1995** [rails/rails#35433]
I found [this question](https://stackoverflow.com/questions/36518887/actionmailer-smtp-certificate-verify-failed) about how to use a self-signed certificate with ActionMailer on StackOverflow.
According to an answer, it can be done with the code below.

```ruby
config.action_mailer.smtp_setting = {
    ...
    ssl: true
    enable_starttls_auto: false,
    openssl_verify_mode: OpenSSL::SSL::VERIFY_PEER,
    ca_file: "/etc/ssl/certs/ca-certificates.crt",
    ...
} 
```

As you can see, a ca_file can be specified with this line `ca_file: "/etc/ssl/certs/ca-certificates.crt"`.

Though the answer is really concise and helped me figure out how to send emails with a self-signed certificate using ActionMailer, it still left me the two following questions.

1) Is it possible to set more than one ,in my case three, different self-signed certificates? If the answer is yes, how?

2) Is it possible to use a `.der` file as a self-signed certificate instead of a `.crt` file? or Should I always convert a `.der` file into a `.crt` file when I use it as a self-signed certificate?

I couldn't find much information regarding this matter, I would appreciate any help!!

**Comment by rafaelfranca** [comment]
Please use StackOverflow for questions/help, where a wider community will be able to help you. We reserve the issues tracker for issues only.
