### ISSUE TITLE
password_confirmation validation provided by has_secure_password doesn't run when password is blank but not empty/nil

### ISSUE THREAD

**Issue by amangano86** [rails/rails#35444]
### Steps to reproduce
1. Start a new rails project
2. Add 'bcrypt' to Gemfile
3. Install gems
`bundle install`
4. Create model with password_digest field
`bundle exec rails g model User password_digest:string`
5. Run migrations
`bundle exec rails db:migrate`
6. Call `has_secure_password` in the model generated in step 4
```ruby
class User < ApplicationRecord
  has_secure_password
end
```
7.) Open rails console and run the following code
```ruby
u = User.new
u.password = "   "
u.password_confirmation = "123"
u.valid?
#=> true
u.password = "1"
u.valid?
#=> false
```
### Expected behavior
The password_confirmation validation should run and render the model invalid when password_confirmation doesn't match password.

### Actual behavior
The password confirmation validation does not run when password is set to a blank but not empty/nil string (like "   "), and therefore the model is valid even when password_confirmation is set to a string that doesn't match.

### System configuration
**Rails version**: 5.1.6 and 5.2.2
**Ruby version**: 2.5.3

**Comment by wenderjean** [comment]
I created a test case to reproduce this on version `6.0.0.beta2` and also do a deep dive into __ActiveModel__ to understand what exactly happens when you set a non empty String using __spaces__ and those are my conclusions:

```ruby
begin
  require "bundler/inline"
rescue LoadError => e
  $stderr.puts "Bundler version 1.10 or later is required. Please update your Bundler"
  raise e
end

gemfile(true) do
  source "https://rubygems.org"

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  gem "activemodel", "~> 6.0.0.beta2"
  gem "activerecord", "~> 6.0.0.beta2"
  gem 'bcrypt', '~> 3.1.7'
  gem "sqlite3", "~> 1.3.0"
end

require "active_record"
require "minitest/autorun"
require "logger"

# Ensure backward compatibility with Minitest 4
Minitest::Test = MiniTest::Unit::TestCase unless defined?(Minitest::Test)

# This connection will do for database-independent bug reports.
ActiveRecord::Base.establish_connection(adapter: "sqlite3", database: ":memory:")
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :users do |t|
    t.string :password_digest

    t.timestamps
  end
end

class User < ActiveRecord::Base
  has_secure_password
end

class BugTest < Minitest::Test
  def test_pay_validation
    user = User.new
    user.password = '     '
    user.password_confirmation = '123'

    assert_equal user.valid?, false
  end
end
```

I realized that the current behaviour is:

1. https://github.com/rails/rails/blob/master/activemodel/lib/active_model/secure_password.rb#L80
    Once your password is not a `nil` value or even an `empty` one, __ActiveModel__ is gonna invoke the `BCrypt` and generates an encrypted value for `password_digest`.
2. https://github.com/rails/rails/blob/master/activemodel/lib/active_model/secure_password.rb#L113
    The __password_digest__ field is actually present here.

But I don't think this is in fact a problem since this behavior is predicted in tests, look:

https://github.com/rails/rails/blob/master/activemodel/test/cases/secure_password_test.rb#L45

I cannot state this but probably __ActiveModel__ rely on your own `presence` and `length` validations for user's `password` field.

**Comment by amangano86** [comment]
@wenderjean, thanks for taking a look. 

To be clear, the problem here is that when **both** password and password_confirmation are provided, the confirmation validation is not run if the password is blank but not nil/empty. This scenario is **not** predicted by the test that you linked to above. That test shows that passwords consisting of all spaces are allowed, but it doesn't test the confirmation validation. Consider the folllowing:
```ruby
u = User.new
u.password = "   "
u.password_confirmation = "123"
u.valid? #=> true
```
In this example, the model should be invalid since the password_confirmation value doesn't match the password value, but that is not currently the case.

This behavior may be the result of the `allow_blank` option being passed to the confirmation validation that is setup by the `has_secure_password` method here: https://github.com/rails/rails/blob/master/activemodel/lib/active_model/secure_password.rb#L117

**Comment by wenderjean** [comment]
Yep! You're right about `allow_blank` option in `secure_password.rb:117`

When updating a model `password` and `password_confirmation` may be blank according to the specs.

```ruby
# https://github.com/rails/rails/blob/master/activemodel/test/cases/secure_password_test.rb#L120

test "updating an existing user with validation and a blank password and password_confirmation" do
  @existing_user.password = ""
  @existing_user.password_confirmation = ""
  assert @existing_user.valid?(:update), "user should be valid"
end
```

**Comment by amangano86** [comment]
The key issue is that setting password to a `blank` string, like "   " **can** change the value of the `password_digest`, which is stored in the database. Setting it to an `empty` string, as is done in the test that you referenced above, does **not** change the digest. See https://github.com/rails/rails/blob/v5.2.2/activemodel/lib/active_model/secure_password.rb#L117

I think we should definitely be running the confirmation validation in cases where the `password_digest` would be changed. This would probably involve replacing the usage of `allow_blank` in https://github.com/rails/rails/blob/v5.2.2/activemodel/lib/active_model/secure_password.rb#L80 with an `if`/`unless` condition that more closely reflects the conditions where `password_digest` would be changed. Perhaps something like `unless: lambda { self.password.nil? || self.password.empty? }`?
