### ISSUE TITLE
Migration with create_join_table fails in Rails 6, 'you can't define an already defined column'

### ISSUE THREAD

**Issue by connorshea** [rails/rails#35448]
### Steps to reproduce

I have a migration that worked in Rails 5.2.2 but causes an error when run on Rails 6.0.0.beta2. Unfortunately I don't know exactly what causes it, but I can reproduce it pretty easily.

I made a reproducible test case here, you can just run it to get the migration failure:

```ruby
# frozen_string_literal: true

require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  gem "rails", github: "rails/rails"
  gem "sqlite3"
end

require "active_record"
require "minitest/autorun"
require "logger"

# This connection will do for database-independent bug reports.
ActiveRecord::Base.establish_connection(adapter: "sqlite3", database: ":memory:")
ActiveRecord::Base.logger = Logger.new(STDOUT)

class Genre < ActiveRecord::Base
end

class CreateGenres < ActiveRecord::Migration[5.2]
  def change
    create_table :genres do |t|
      t.text :name, null: false, default: ""

      t.timestamps
    end

    create_join_table :games, :genres do |t|
      t.integer :game_id
      t.integer :genre_id
    end
  end
end


class BugTest < Minitest::Test
  def test_migration_up
    CreateGenres.migrate(:up)
  end
end
```

For comparison, you can see that the same migration succeeds on Rails 5.2.2 (the only changed lines are in the gemfile bit):

<details>
<summary>Rails 5 version</summary>

```ruby
# frozen_string_literal: true

require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  gem "rails", '~> 5.2.2'
  gem "sqlite3", '~> 1.3.5'
end

require "active_record"
require "minitest/autorun"
require "logger"

# This connection will do for database-independent bug reports.
ActiveRecord::Base.establish_connection(adapter: "sqlite3", database: ":memory:")
ActiveRecord::Base.logger = Logger.new(STDOUT)

class Genre < ActiveRecord::Base
end

class CreateGenres < ActiveRecord::Migration[5.2]
  def change
    create_table :genres do |t|
      t.text :name, null: false, default: ""

      t.timestamps
    end

    create_join_table :games, :genres do |t|
      t.integer :game_id
      t.integer :genre_id
    end
  end
end


class BugTest < Minitest::Test
  def test_migration_up
    CreateGenres.migrate(:up)
  end
end
```
</details>

### Expected behavior
The migration should succeed like it did when run on Rails 5.2.

### Actual behavior
The migration fails with `ArgumentError: you can't define an already defined column 'game_id'.`

I can provide more information if needed to get this fixed. Hopefully the test cases help!

### System configuration
**Rails version**: 6.0.0.beta2

**Ruby version**: 2.6.1

**Comment by connorshea** [comment]
Actually, it looks like this failure was added intentionally? https://github.com/rails/rails/commit/7ef9849e3d51c1f4a37af368b770d8fdb41883cd#diff-21d4fbe002689dc4b0ab29f021585457

I'm not sure if this issue is valid then, but generally my understanding is that migrations shouldn't be changed after their initial creation, so how would I go about resolving this?

**Comment by connorshea** [comment]
Per the docs, changing existing migrations is discouraged: https://guides.rubyonrails.org/active_record_migrations.html

Would this be a case where it’s acceptable (since the scheme wouldn’t be changed at all) or should this error be changed to a warning for Migrations with versions `< 6.0`?

**Comment by eileencodes** [comment]
Hey @connorshea, I looked at this and I think it's working as intended. We discourage changing migrations but we at GitHub do it all the time to deal with upgrades. To have less headache we've started deleting migrations.

I think you should change your migration to look like this

```
# frozen_string_literal: true

require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  gem "rails", github: "rails/rails"
  gem "sqlite3"
end

require "active_record"
require "minitest/autorun"
require "logger"

# This connection will do for database-independent bug reports.
ActiveRecord::Base.establish_connection(adapter: "sqlite3", database: ":memory:")
ActiveRecord::Base.logger = Logger.new(STDOUT)

class Genre < ActiveRecord::Base
end

class CreateGenres < ActiveRecord::Migration[5.2]
  def change
    create_table :genres do |t|
      t.text :name, null: false, default: ""

      t.timestamps
    end

    create_join_table :games, :genres
  end
end


class BugTest < Minitest::Test
  def test_migration_up
    CreateGenres.migrate(:up)
  end
end
```

**Comment by connorshea** [comment]
Fair enough, thanks for looking into it :)

**Comment by eileencodes** [comment]
To clarify we recommend not changing migrations but that's for not changing behavior. In this case you'd be fixing an incorrect migration but that doesn't change the behavior or tables it creates.
