### ISSUE TITLE
Nested scopes cause wrong root route in 5.2.2

### ISSUE THREAD

**Issue by radubatori** [rails/rails#35440]
### Steps to reproduce

Having a routing config like:

```ruby
Rails.application.routes.draw do
  scope "(:locale)", locale: /en|fr/ do
    scope "(:country)", country: /ie|gb/ do
      root to: 'pages#homepage'
    end
  end
end
```

### Expected behavior

Generates the following route in 5.2.1.1:

```
root GET  (/:locale)(/:country)(.:format) pages#homepage {:locale=>/en|fr/, :country=>/ie|gb/}
```

### Actual behavior

The route generated in 5.2.2 is:

```
root GET  /(/:locale)(/:country)(.:format) pages#homepage {:locale=>/en|fr/, :country=>/ie|gb/}
```

Notice the leading forward slash.

A route like `/en/gb` is no longer matched. Also, `root_path(locale: :en, country: :gb)` produces `//en/gb`.

### System configuration
**Rails version**: 5.2.2
**Ruby version**: 2.6.1

**Comment by st0012** [comment]
This can be reproduced at `6.0.0.beta1` as well

**Comment by st0012** [comment]
After some investigation, this issue seemed appreared after https://github.com/rails/rails/commit/7670d60977a7de3d11a8a9004b8a7a1c60383ee7. But it's not that the change introduced a bug. I think it's caused by incorrect route AST tree and the commit just made it surface.

To be more clear, this issue only happens when
1) The scopes are optional `(:locale)`
2) Defined with options `locale: /en|fr/`
3) The scopes are nested (>= 2 levels)

@gmcgibbon maybe you want to take a look?

**Comment by szaszolak** [comment]
We are experiencing this issue also in `6.0.0.rc1`

**Comment by apauly** [comment]
We also faced this problem during an upgrade from 5.1 to 5.2.
Here is a small test case that reproduces the issues:

https://gist.github.com/apauly/e503c46d053db9382ce94c3d9031f95f

I can also confirm that this issues was introduced with 7670d60

**Comment by apauly** [comment]
Quick update on this one:

The [reproduction script](https://gist.github.com/apauly/e503c46d053db9382ce94c3d9031f95f) that I linked above is still failing on Rails 6.0 but it's actually working again with 6.1 👍

**Comment by ghiculescu** [comment]
Rails 5.2 and 6.0 are no longer supported except for severe security issues (per https://guides.rubyonrails.org/maintenance_policy.html)

Thanks so much for the repro script. Can confirm it passes on 6.1 and 7.

Please do reopen this (or make a new issue) if this is still causing issues on 7.
