### ISSUE TITLE
ActionDispatch swallowing NameError and giving misleading end error

### ISSUE THREAD

**Issue by morgoth** [rails/rails#35453]
During upgrade to Rails 6.0.0.beta2 I encountered a problem with disappearing instance methods that are defined on controller class. It revealed itself when switching autoloader to zeitwerk, however together with @fxn we investigated the case (and also reproduced) and found that underlying problem is in Rails. You can follow the discussion here: https://github.com/fxn/zeitwerk/issues/14

`NameError` here https://github.com/rails/rails/blob/f4a30d2a0706f278a20c63a3d99288de79b52e5f/actionpack/lib/action_dispatch/http/parameters.rb#L100-L104 is silently swallowed, which resulted in half-defined controller.

You can find sample app (with deeper description in readme) that reproduces the problem here https://github.com/morgoth/bug
As the end error is totally misleading, it would be good to find a way to not catch all `NameError` errors.
Not sure why it is there, but when I tried to remove it, many actiondispatch tests were failing.

**Comment by fxn** [comment]
I am on a family trip now, but can work on it next week.

I didn’t check, but off the top of my head a smaller app showing the issue could be a scaffold that defines a helper method in the controller, and references an unknown constant in the body of its helper module.

I suspect we need to understand through the test suite the original intention of that `rescue` clause (or blame and ask who wrote it), and try to relax it so that legit exceptions are reraised.

**Comment by morgoth** [comment]
it is still a problem

**Comment by fxn** [comment]
I don't seem to be able to reproduce in `6-0-stable` or `master`. Can you?

**Comment by morgoth** [comment]
Yes, looks like by mistake I disabled the error in this commit https://github.com/morgoth/bug/commit/de7d922e7d2d962e6346ca1d13547e01fbe40314#diff-303cd7048a8a723474be211734e54399L2

I pushed it again and updated to Rails 6 stable https://github.com/morgoth/bug where it still is showing up

**Comment by fxn** [comment]
Reproduced, thanks.

**Comment by fxn** [comment]
Heads up.

So far, I have not been able to reproduce in a regular application, `NameErrors` bubble up just fine.

The sample app does too many things. Is `helper_method` needed? No. Other existing macros? No. To which extent do we need so many ancestors in the target controller to reproduce? Which helpers are needed? Do we need helpers at all?

We need a minimal way to reproduce.

**Comment by fxn** [comment]
Let me add that [the patch](https://github.com/rails/rails/compare/do-no-shallow-name-errors) is ready. But the minimal app should show the core of the problem, and would be added as test coverage.

**Comment by morgoth** [comment]
I tried to simplify it a bit, but that is all I got https://github.com/morgoth/bug/commit/e2a9ea1faf3ecfac94101f9deb02b0663a4784c2

I cannot reproduce it without vendored engine.

**Comment by eugeneius** [comment]
For posterity: this problem was fixed in https://github.com/rails/rails/pull/37834.
