### ISSUE TITLE
ActiveStorage S3Service does not allow connection config parameters

### ISSUE THREAD

**Issue by erkie** [rails/rails#35466]
### Steps to reproduce
The following line:
https://github.com/rails/rails/blob/c5b71c9baea4959c096774c763e558df2979a9db/activestorage/lib/active_storage/service/s3_service.rb#L12

```ruby
class Service::S3Service < Service
  # ...

  def initialize(bucket:, upload: {}, **options)
    @client = Aws::S3::Resource.new(**options)
    # ....
  end
end
```

The documentation example:

```
amazon:
    service: S3 
    access_key_id: ""
    secret_access_key: ""
    region: ""
    bucket: ""
--

Add the aws-sdk-s3 gem to your Gemfile:

gem "aws-sdk-s3", require: false
```

### Expected behavior
One would assume that `access_key_id`, `secret_access_key` etc are passed into the Aws::S3::Client connection parameters.

Looking at the `aws-sdk-s3` gem, one can see that the `Aws::S3::Resource` class does not even take these as parameters for its initialization, and is instead expecting a `client` object, which is impossible to construct via YAML config. It used to in a previous version (the V2 of the SDK, but the Rails documentation points to using the V3 SDK)

right now it works because it falls back to AWS SDK's default connection behaviour to look through `config/aws.yaml` and ENV variables.

### Actual behavior
The connection parameters should be configurable as expected and outlined by documentation.

I had to write a custom ActiveStorage to work around this:

```ruby
require "active_storage/service/s3_service"

class ActiveStorage::Service::CustomS3Service < ActiveStorage::Service::S3Service
  def initialize(bucket:, upload: {}, **options)
    credentials = Aws::Credentials.new(options[:access_key_id], options[:secret_access_key])

    @client = Aws::S3::Resource.new(
      client: Aws::S3::Client.new(
        **{ credentials: credentials }.merge(options)
      )
    )

    @bucket = @client.bucket(bucket)

    @upload_options = upload
end
```

### System configuration
**Rails version**: 5.2.2

**Ruby version**: 2.6.1

**aws-sdk-s3**: 

```
    aws-sdk-s3 (1.30.1)
      aws-sdk-core (~> 3, >= 3.39.0)
      aws-sdk-kms (~> 1)
      aws-sigv4 (~> 1.0)
```

**Comment by y-yagi** [comment]
I may not be able to understand your problem correctly, but it seems to work as expected in my environment with that setting.   

The options specified for `Aws::S3::Resource` are passed to `Aws::S3::Client` as is, `Aws::S3::Client` seems to support those options.
https://github.com/aws/aws-sdk-ruby/blob/61e46612a857f59bbcd14b0f323cde36732b95b6/gems/aws-sdk-s3/lib/aws-sdk-s3/resource.rb#L14 
https://github.com/aws/aws-sdk-ruby/blob/61e46612a857f59bbcd14b0f323cde36732b95b6/gems/aws-sdk-s3/lib/aws-sdk-s3/client.rb#L110 

Does this issue occur even in newly created applications?

**Comment by erkie** [comment]
@y-yagi the problem is how AWS SDK loads config options. I found this because we're using a different set of access keys for uploads, and another set for for other things like sending e-mails with SES etc.  When other global credentials have been registered with for example:

```ruby
Aws.config.update({
  credentials: Aws::Credentials.new("initial_key", "secret_key")
})
```

Because the credentials are not properly passed in they are not overriding the defaults.

Here is a failing test example:

```ruby
require 'test_helper'

class AwsCredentialsTest < ActiveSupport::TestCase
  test 'check aws credentials' do
    Aws.config.update({
      credentials: Aws::Credentials.new("initial_key", "initial_secret")
    })

    assert ActiveStorage::Blob.service.is_a? ActiveStorage::Service::S3Service

    activestorage_s3_service = ActiveStorage::Blob.service

    assert_equal "a_secret_access_key", activestorage_s3_service.client.client.config.credentials.access_key_id
  end
end
```

` storage.yml`
```yaml
amazon:
  service: S3
  access_key_id: "a_test_key"
  secret_access_key: "a_secret_access_key"
  region: us-east-1
  bucket: your_own_bucket
```

Failure:

```
Failure:
AwsCredentialsTest#test_check_aws_credentials [test/models/aws_credentials_test.rb:13]:
Expected: "a_secret_access_key"
  Actual: "initial_key
```
