### ISSUE TITLE
after_commit on: :destroy callback order is wrong with child records

### ISSUE THREAD

**Issue by h0jeZvgoxFepBQ2C** [rails/rails#35470]
I'm not sure if I missed something, but following behaviour looks wrong to me, and right now I have a project which relies on the correct callback order. 

As it seems, the ```after_commit``` deletion callback applies the wrong order when child records are taken into account, see the example below.

### Steps to reproduce

```ruby
# frozen_string_literal: true
require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  gem "rails", "~> 5.2.3"
  gem "sqlite3", "~> 1.3.6"
end

require "active_record"
require "minitest/autorun"
require "logger"

ActiveRecord::Base.establish_connection(adapter: "sqlite3", database: ":memory:")

ActiveRecord::Schema.define do
  create_table :owners, force: true do |t|
    t.string :name
    t.timestamps
  end

  create_table :pets, force: true do |t|
    t.references :owner
    t.string :name
    t.timestamps
  end
end

class Owner < ActiveRecord::Base
  has_many :pets, inverse_of: :owner, dependent: :destroy

  after_destroy do
    puts "#{self.class}_#{self.id} after_destroy"
  end
  after_commit on: :destroy do
    puts "#{self.class}_#{self.id} after_commit on: :destroy (<== should occur after the child destroy commits!)"
  end
end

class Pet < ActiveRecord::Base
  belongs_to :owner

  after_destroy do
    puts "#{self.class}##{self.id} after_destroy"
  end
  after_commit on: :destroy do
    puts "#{self.class}##{self.id} after_commit on: :destroy"
  end
end

class BugTest < Minitest::Test
  def test_after_commit_on_destroy_child_record_order
    
    owner = Owner.create!(name: 'TestOwner')
    old_pet1 = Pet.create!(owner: owner, name: 'TestPet1')
    old_pet2 = Pet.create!(owner: owner, name: 'TestPet2')
    old_pet3 = Pet.create!(owner: owner, name: 'TestPet3')

    owner.destroy
  end
end
```

### Expected behavior

As far as I know, the deletion of the parent model (owner) should be executed at last. The ```after_destroy``` callback is outputting also the correct order:

```ruby
# correct order
Pet#1 after_destroy
Pet#2 after_destroy
Pet#3 after_destroy
Owner_1 after_destroy
Pet#1 after_commit on: :destroy
Pet#2 after_commit on: :destroy
Pet#3 after_commit on: :destroy
Owner_1 after_commit on: :destroy
```

### Actual behavior

```ruby
# incorrect order
# Running:

Pet#1 after_destroy
Pet#2 after_destroy
Pet#3 after_destroy
Owner_1 after_destroy
Owner_1 after_commit on: :destroy (<== should occur after the child destroy commits!)
Pet#1 after_commit on: :destroy
Pet#2 after_commit on: :destroy
Pet#3 after_commit on: :destroy
```
### System configuration
**Rails version**: 5.2.3

**Ruby version**: 2.5.3

**Comment by h0jeZvgoxFepBQ2C** [comment]
This issue is still occuring in version 5.2.3. I've updated the test again.
Would be great to get any confirmation or suggestion (if I'm wrong or not).. @rafaelfranca maybe? 
Thank you!

**Comment by why-el** [comment]
@h0jeZvgoxFepBQ2C this issue is solved in Rails 6.0.0rc1. According to [the maintenance policy](https://guides.rubyonrails.org/maintenance_policy.html#bug-fixes), this will most likely not be backported to your version, unless you get someone from the Core Team to agree it is serious enough. I myself think it might not be, but I don't know what you are trying to do exactly. Perhaps you can rewrite your logic to support your case until you are on 6.0? 

Evidence that it works: 

```
# frozen_string_literal: true
require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  gem "rails", "~> 6.0.0.rc1"
  gem 'sqlite3'
end

require "active_record"
require "minitest/autorun"
require "logger"

ActiveRecord::Base.establish_connection(adapter: "sqlite3", database: ":memory:")

ActiveRecord::Schema.define do
  create_table :owners, force: true do |t|
    t.string :name
    t.timestamps
  end

  create_table :pets, force: true do |t|
    t.references :owner
    t.string :name
    t.timestamps
  end
end

class Owner < ActiveRecord::Base
  has_many :pets, inverse_of: :owner, dependent: :destroy

  after_destroy do
    puts "#{self.class}_#{self.id} after_destroy"
  end
  after_commit on: :destroy do
    puts "#{self.class}_#{self.id} after_commit on: :destroy (<== should occur after the child destroy commits!)"
  end
end

class Pet < ActiveRecord::Base
  belongs_to :owner

  after_destroy do
    puts "#{self.class}##{self.id} after_destroy"
  end
  after_commit on: :destroy do
    puts "#{self.class}##{self.id} after_commit on: :destroy"
  end
end

class BugTest < Minitest::Test
  def test_after_commit_on_destroy_child_record_order
    
    owner = Owner.create!(name: 'TestOwner')
    old_pet1 = Pet.create!(owner: owner, name: 'TestPet1')
    old_pet2 = Pet.create!(owner: owner, name: 'TestPet2')
    old_pet3 = Pet.create!(owner: owner, name: 'TestPet3')

    owner.destroy
  end
end
```

**Comment by h0jeZvgoxFepBQ2C** [comment]
First of all, thank you for your feedback, great to hear that there is really an issue and it's not that I just did something wrong :)

We are actually more or less dependent on the correct order, since we are creating a changestream with the ```after_commit``` callbacks, which we use for some mobile device replication. If the order is incorrect from the deletions, we can't replicate the deletions correctly to our mobile devices.

Right now we are using the ```after_destroy``` callback as a workaround, since it has the correct order - and hope there isn't something going wrong before ```on_commit``` is called.

**Comment by why-el** [comment]
Great, so I think you should close this issue? Since it's fixed in master? once you update you can drop your reliance on the hack you mentioned.
