### ISSUE TITLE
session_store :mem_cache_store requires memcached server on assets:precompile

### ISSUE THREAD

**Issue by mtsmfm** [rails/rails#35476]
`config.session_store :mem_cache_store` requires memcached server on `assets:precompile` despite `config.cache_store = :mem_cache_store` doesn't require.

Is this intentional?

### Steps to reproduce

```ruby
require 'bundler/inline'

gemfile(true) do
  source 'https://rubygems.org'

  gem 'rails', '5.2.2', require: 'sprockets/railtie'
  gem 'dalli', '2.7.9'
end

class TestApp < Rails::Application
  secrets.secret_key_base = 'secret_key_base'
end

Rails.application.configure do
  config.load_defaults 5.2
  config.eager_load = true
  config.logger = ActiveSupport::Logger.new(STDOUT)
  config.cache_store = :mem_cache_store
  config.session_store ENV['SESSION_STORE'].to_sym
end

puts ?- * 10
puts <<~STR
$ SESSION_STORE=#{ENV['SESSION_STORE']} ruby test.rb
STR

Rails.application.initialize!
Rails.application.load_tasks

Rake::Task["assets:precompile"].invoke

puts 'success'

__END__
----------
$ SESSION_STORE=mem_cache_store ruby test.rb
Dalli::Server#connect localhost:11211
localhost:11211 failed (count: 0) Errno::EADDRNOTAVAIL: Cannot assign requested address - connect(2) for "localhost" port 11211
Traceback (most recent call last):
        29: from hi.rb:27:in `<main>'
        28: from /usr/local/bundle/gems/railties-5.2.2/lib/rails/application.rb:361:in `initialize!'
        27: from /usr/local/bundle/gems/railties-5.2.2/lib/rails/initializable.rb:60:in `run_initializers'
        26: from /usr/local/lib/ruby/2.6.0/tsort.rb:205:in `tsort_each'
        25: from /usr/local/lib/ruby/2.6.0/tsort.rb:226:in `tsort_each'
        24: from /usr/local/lib/ruby/2.6.0/tsort.rb:347:in `each_strongly_connected_component'
        23: from /usr/local/lib/ruby/2.6.0/tsort.rb:347:in `call'
        22: from /usr/local/lib/ruby/2.6.0/tsort.rb:347:in `each'
        21: from /usr/local/lib/ruby/2.6.0/tsort.rb:349:in `block in each_strongly_connected_component'
        20: from /usr/local/lib/ruby/2.6.0/tsort.rb:431:in `each_strongly_connected_component_from'
        19: from /usr/local/lib/ruby/2.6.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
        18: from /usr/local/lib/ruby/2.6.0/tsort.rb:228:in `block in tsort_each'
        17: from /usr/local/bundle/gems/railties-5.2.2/lib/rails/initializable.rb:61:in `block in run_initializers'
        16: from /usr/local/bundle/gems/railties-5.2.2/lib/rails/initializable.rb:32:in `run'
        15: from /usr/local/bundle/gems/railties-5.2.2/lib/rails/initializable.rb:32:in `instance_exec'
        14: from /usr/local/bundle/gems/railties-5.2.2/lib/rails/application/finisher.rb:47:in `block in <module:Finisher>'
        13: from /usr/local/bundle/gems/railties-5.2.2/lib/rails/engine.rb:506:in `app'
        12: from /usr/local/bundle/gems/railties-5.2.2/lib/rails/engine.rb:506:in `synchronize'
        11: from /usr/local/bundle/gems/railties-5.2.2/lib/rails/engine.rb:510:in `block in app'
        10: from /usr/local/bundle/gems/actionpack-5.2.2/lib/action_dispatch/middleware/stack.rb:101:in `build'
         9: from /usr/local/bundle/gems/actionpack-5.2.2/lib/action_dispatch/middleware/stack.rb:101:in `inject'
         8: from /usr/local/bundle/gems/actionpack-5.2.2/lib/action_dispatch/middleware/stack.rb:101:in `each'
         7: from /usr/local/bundle/gems/actionpack-5.2.2/lib/action_dispatch/middleware/stack.rb:101:in `block in build'
         6: from /usr/local/bundle/gems/actionpack-5.2.2/lib/action_dispatch/middleware/stack.rb:37:in `build'
         5: from /usr/local/bundle/gems/actionpack-5.2.2/lib/action_dispatch/middleware/stack.rb:37:in `new'
         4: from /usr/local/bundle/gems/actionpack-5.2.2/lib/action_dispatch/middleware/session/mem_cache_store.rb:24:in `initialize'
         3: from /usr/local/bundle/gems/actionpack-5.2.2/lib/action_dispatch/middleware/session/abstract_store.rb:23:in `initialize'
         2: from /usr/local/bundle/gems/dalli-2.7.9/lib/rack/session/dalli.rb:91:in `initialize'
         1: from /usr/local/bundle/gems/dalli-2.7.9/lib/dalli/client.rb:240:in `alive!'
/usr/local/bundle/gems/dalli-2.7.9/lib/dalli/ring.rb:46:in `server_for_key': No server available (Dalli::RingError)
----------
$ SESSION_STORE=cookie_store ruby test.rb
success
```

### Expected behavior

`$ SESSION_STORE=mem_cache_store ruby test.rb` finishes successfully.

### Actual behavior

`$ SESSION_STORE=mem_cache_store ruby test.rb` fails.

### System configuration
**Rails version**: 5.2.2

**Ruby version**: 2.6.1

**Comment by y-yagi** [comment]
Unlike cache store, session store is provided as Rack middlware. Rack middlware is built at application boot time. This is intentional behavior.
https://edgeapi.rubyonrails.org/classes/Rails/Application.html#class-Rails::Application-label-Booting+process 

In Rails,  just call dalli's initialization. Whether or not to actually connect to the server is dependent on dalli, so I think that Rails can not deal with it.

**Comment by mtsmfm** [comment]
> Whether or not to actually connect to the server is dependent on dalli, so I think that Rails can not deal with it.

Hmm, this option is `:mem_cache_store`, not `:dalli_store`.
It's abstracted.
So I think Rails should decide the ideal behavior.

**Comment by mtsmfm** [comment]
I think we have these options.
@y-yagi What do you think?

## 1. Make sure memcache server is available on the initializing process for cache_store as well

### Pros

Rails can keep consistency about `:mem_cache_store`.

### Cons

`Errno::EADDRNOTAVAIL` will be raised on `assets:precompile` especially developers who use Docker.

## 2. Avoid raising the error by applying monkey patch

### Pros

Rails can keep consistency about `:mem_cache_store`.

### Cons

We need to watch Dalli's change carefully.

## 3. Avoid raising the error by re-implement `ActionDispatch::Session::MemCacheStore`

### Pros

Rails can keep consistency about `:mem_cache_store`.
In addition, Rails can control every behavior.

### Cons

We just want to suppress the error.
It's overspec.

## 4. Keep as is

### Pros

Easy

### Cons

Rails users who use mem_cache_store for both cookie_store and session_store maybe confused.

To run `assets:precompile` on isolated env (ex. Docker) requires a workaround.
In my case, I added a flag:

```ruby
unless ENV['NO_MEMCACHE_CONNECTION']
  config.session_store = :mem_cache_store
end
```

## Additional information

It seems Dalli had this check to improve error message:
https://github.com/petergoldstein/dalli/pull/423

For `Rack::Session::Memcache`, this commit implemented such check but I can't find further context:
https://github.com/rack/rack/commit/78ad4dac6abb42b52c9cbbd5e38278d0a032a9bf

**Comment by y-yagi** [comment]
In my personal opinion, I think that `ActionDispatch::Session::MemCacheStore` should not have any special behavior for this purpose. 
However, similar issues are reported(master key, DB, etc). #32947, #25246. 
There may be flags to control the behavior of `assets:precompile`, like `initialize_on_precompile` before.
