### ISSUE TITLE
Scaffolding can only run once per reboot

### ISSUE THREAD

**Issue by EthanZeigler** [rails/rails#35483]
### Steps to reproduce

- Create a new project with `rails new abc`
- Generate scaffolding with `rails generate scaffold example title:string description:text`
- Delete the project
- Create the project again
- Generate scaffolding again

### Expected behavior
Scaffolding generates successfully

### Actual behavior
- Scaffolding hangs permanently. SIGINT and SIGKILL are both ignored.
- Seems the only way to be able to run scaffolding again is to reboot the computer
- Reproduced on both Ubuntu 18 and macOS 10.14.2

### System configuration
**Rails version**: 5.2.2

**Ruby version**: 2.6.0p0

**Comment by y-yagi** [comment]
Thanks for your report. This is an issue of spring. Please see https://github.com/rails/spring/issues/247 for more detail.  
Temporary solution: You stop the spring process or kill it so that you can execute the command again. Thanks.
