### ISSUE TITLE
Overriding scopes with STI, getting useless warnings

### ISSUE THREAD

**Issue by guyzmo** [rails/rails#35499]
### Steps to reproduce

let's consider those classes:

```ruby
def ParentModel < ApplicationRecord
  scope :foobar, -> { where(some_attribute: true).where(another_attribute: true) }
end

def AChildModel < ParentModel
  scope :foobar, -> { where(some_attribute: true) }
end

def BChildModel < ParentModel
  scope :foobar, -> { where(another_attribute: true) }
end
```

I'm using inheritance so `AChildModel` and `BChildModel` share a same interface (and part of the model), which is implemented in `ParentModel`, but there's a part of the interface that's different from the parent, so I'm specializing it. And thus, I also need to specialize some scopes.

### Expected behavior

when intended, overriding scope behaviour should be fine without annoying warnings.

### Actual behavior

I'm getting warnings like:

```
Creating scope :foobar. Overwriting existing method AChildModel.foobar.
Creating scope :foobar. Overwriting existing method BChildModel.foobar.
```

This is caused by [this method in ActiveRecord::Scoping::Named](https://github.com/rails/rails/blob/b414ca3f17c76fb1cc43d79fbffd2f3ed95acdde/activerecord/lib/active_record/scoping/named.rb#L208,L213), and it looks like aside from disabling the logger, I have no way of telling ActiveRecord that I know what I'm doing, and it's fine!

So, shall I use class methods instead, even though as it _is_ a scope, as it will be used as a scope?

Maybe would it be a good idea to add an argument to `scope` so that it disables the warning?
Something like:

```ruby
scope :foobar, -> { ... }, overrides: true
```

### System configuration
**Rails version**: 5.2

**Ruby version**: 2.5

**Comment by guyzmo** [comment]
As a temporary solution I'm monkey patching the private method:

```ruby
module ActiveRecord::Scoping::Named::ClassMethods
  private def valid_scope_name?(name) end
end
```

as it's not really a good solution, as it will hide the warning for non-intended scopes shadowing.

I'd be happy to write a small PR to implement that, if that's ok!

A quick git blame shows that in 2016, for v5 @amatsuda reverted a commit by @jonleighton that removed that feature in 2012 for v4. Why not make a compromise between the two 😉

**Comment by JhottMaster** [comment]
I have this issue as well. Our solution was similar to @guyzmo, with the exception that we only muted the error for all our existing cases, not future. We didn’t want to completely mute the warning.

**Comment by brodock** [comment]
Is there any objection on implementing a override flag like proposed above? I can work on a PR.

**Comment by brodock** [comment]
@rafaelfranca could you weight here on the proposal? Do you think it's fine to use an optional flag to disable the warning? (the whole thing already works, so we are only removing the guardrails)

also could you please reopen the issue? :)

**Comment by fschwahn** [comment]
I also run into this warning from time to time. I added the following to `ApplicationRecord`:
```ruby
  def self.redefine_scope(name, body)
    singleton_class.undef_method(name)
    scope(name, body)
  end
```

and use `redefine_scope` where appropriate.

**Comment by reedstonefood** [comment]
In case it wasn't clear to anyone else, the above line links to an issue which eventually links to https://github.com/rails/rails/commit/0e8432e97404edf5a259374e6aa0cf47ce009273 which shows the code that created these warnings was removed from rails in version 7.0.
