### ISSUE TITLE
insert_all throws `ActiveRecord::NotNullViolation` for timestamps

### ISSUE THREAD

**Issue by abhaynikam** [rails/rails#35493]
### Steps to reproduce
```
# frozen_string_literal: true

require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  gem "rails", github: "rails/rails"
  gem "sqlite3"
end

require "active_record"
require "minitest/autorun"
require "logger"

# This connection will do for database-independent bug reports.
ActiveRecord::Base.establish_connection(adapter: "sqlite3", database: ":memory:")
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :posts, force: true do |t|
    t.string :content

    t.timestamps
  end
end

class Post < ActiveRecord::Base
end

class BugTest < Minitest::Test
  def test_insert_all
    Post.insert_all([
      { content: "first" },
      { content: "second" }
    ])
  end
end
```

### Expected behavior
I think insert_all should auto set the timestamp value unless explicitly given.

### Actual behavior
If a Model has `t.timestamps` then it by default add `NOT NULL` constraint on `created_at` and `updated_at` due to which insert_all fails unless `created_at` and `updated_at` values are given.

### System configuration
**Rails version**: `6.0.0.beta1`

**Ruby version**: `v2.6.0-dev`

**Comment by abhaynikam** [comment]
I would love to work on this issue if the expectation is valid 😄

**Comment by sikachu** [comment]
Yep, I agree. That might be an oversight. Would you mind working on a patch?

**Comment by abhaynikam** [comment]
I am done with the patch. Working on adding some test cases. Will raise PR shortly. Thanks, @sikachu

**Comment by boblail** [comment]
For this use-case, I would suggest giving the timestamp columns a default value: (c.f. #20005)

```diff
- t.timestamps
+ t.timestamps default: -> { 'CURRENT_TIMESTAMP' }
```

* * *

I think `insert_all` **_shouldn't_** autofill timestamps for a couple of reasons:

1. It's a sister to `update_all`, which does not
2. It's a "close to the metal" experience so it should do as little as possible:
    - because its leanness is the quality you want when you're optimizing a bottleneck and picking `insert_all` over `create`
    - because it's natural to have more "road feel" at that level (i.e. fewer manipulations of the inputs you pass to the INSERT that gets generated, fewer buffers between you and the database's constraints and validations)

**Comment by abhaynikam** [comment]
Thanks for your response @boblail .  Adding timestamps feels necessary to me because 

- If we are choosing over `insert_all` over `create` then we might need to write down migration just to add `default: -> { 'CURRENT_TIMESTAMP' }` which does not feel right to me. 
- While writing a migration to add default `'CURRENT_TIMESTAMP'` to timestamp. I did face a weird issue. Default was only added to `updated_at` and not to `created_at`. Might be I am doing something wrong here 😄 
```
change_column_default :messages, :created_at, -> { 'CURRENT_TIMESTAMP' }
change_column_default :messages, :updated_at, -> { 'CURRENT_TIMESTAMP' }
```
- > It's a sister to update_all

Here the timestamp not null constraint is already satisfied so even if it doesn't update it won't fail but in case of `insert_all` it would until set default. If setting timestamp is not option may good error message when NotNullViolation is thrown for timestamps. 

Maybe Rails team member could guide us here. cc/ @sikachu @kaspth

**Comment by kaspth** [comment]
My thinking is that a great use case for `insert_all` is importing data from a CSV which might not have columns for created_at/updated_at, so I think it does make sense for Rails to have your back there as it does for `create`/`update` via `ActiveRecord::Timestamp`.

On the other hand, if people are using upserts we don't know if a record exists in the db beforehand, so we don't know if we should provide created_at too. But that's perhaps a larger problem with `upsert_all`.

 Having a way to provide defaults ala `insert_all(data, defaults: { created_at: Time.now, updated_at: Time.now })` could also work.

How does `insert_all` fare as a relation? For instance, does `author.posts.insert_all(data)` infer `:author_id`?

**Comment by boblail** [comment]
> How does insert_all fare as a relation? For instance, does author.posts.insert_all(data) infer :author_id?

It does not, but that's a great idea! :+1:

(I think it would be important for `author_id` to be `merge`d into the data and not `reverse_merge`d — more on that below.)

> Having a way to provide defaults ala `insert_all(data, defaults: { created_at: Time.now, updated_at: Time.now })` could also work.

The concept of **Defaults** gives me a squishy feeling: It's a non-negotiable requirement of the database that every row have the same keys and values. Currently, the bulk-insert methods point this out to you by raising an `ArgumentError` if members of the `inserts` list are mismatched. If my `inserts` _are_ mismatched, I'd rather get an exception up-front than for something (other than the database) to "smartly" backfill default values:
- Because I wouldn't want part of the logic that determines what values are inserted to be _hidden_
- Because after using Rails for 10 years, I've been coming around to the viewpoint that I _much_ prefer troubleshooting exceptions at the moment when ambiguous data would be inserted than working backward from a _How did the data get like this?_ moment.

:point_up: Having said that (lol), I like that, in your proposal, @kaspth, `defaults:` are explicit (i.e. anything that would be `reverse_merge`d is explicit) and a user like me could choose to leave them out and take his or her lumps up front when preparing `data` to be passed to `insert_all`!

**Comment by boblail** [comment]
(:thinking: The more I think about it, the more I love the idea of `author.posts.insert_all(data)` inferring `:author_id`...  :heart: ... and picking up attributes from `create_with`)

**Comment by simi** [comment]
I have prepared solution for this based on https://github.com/rails/rails/pull/35631 and https://github.com/rails/rails/pull/35635.

With those code changes it should be easier, but still transparent how to handle `created_at`/`updated_at` columns during `upsert`/`upsert_all`.

```ruby
now = Time.now
defaults = { created_at: now, updated_at: now }
row = { slug: 'new-title', post: 'New post' }

Post.upsert(row1,
            unique_by: { columns: [:slug]},
            defaults: { created_at: now, updated_at: now },
            updatable_columns: [:post, :updated_at])
```

It looks similar to me `update_all` where you need to specify `updated_at` value manually as well if you need to update it:

```ruby
Post.update_all(post: 'deleted', updated_at: Time.now)
```

**Comment by kaspth** [comment]
https://github.com/rails/rails/pull/35635#issuecomment-478360317

**Comment by ansonhoyt** [comment]
@kaspth shouldn't this be re-opened, but just kept outside the 6.0 milestone? Even though it didn't make the Rails 6.0 release, it still seems to be an issue.

Also, the [insert_all](https://api.rubyonrails.org/classes/ActiveRecord/Persistence/ClassMethods.html#method-i-insert_all) docs don't show timestamps having to be passed, but this issue leads me to believe they do need to be provided.

**Comment by kaspth** [comment]
No, I don't think we should support automatic inference of timestamps and prefer `Post.where(created_at: Time.now).insert_all(posts)` as mentioned in the comment.

> Also, the [insert_all](https://api.rubyonrails.org/classes/ActiveRecord/Persistence/ClassMethods.html#method-i-insert_all) docs don't show timestamps having to be passed, but this issue leads me to believe they do need to be provided.

That suggests the documentation needs to be updated. Please do investigate.

**Comment by ansonhoyt** [comment]
Hmm, tried the `where(created_at: Time.now)` but still had to supply `created_at: Time.now` in the attributes array.

**Comment by kaspth** [comment]
I'm stating what the API should be, not what it is. I'm not looking to work on `insert_all` or review PRs for it for a good while. Maybe there's more interest from the rest of core, but I'm passing ✌️

**Comment by ansonhoyt** [comment]
Ahh, thanks for clarifying! ...and congrats on 6.0

**Comment by rusikf** [comment]
@simi Does this behaviour will be in release ? I dont see ability to set defaults option in last rails: 6.0.3 

```
.7.1 :006 > now = Time.now; Node.upsert_all([{ id: 638, position_x: 100, position_y: 125 }], defaults: {})
Traceback (most recent call last):
        2: from (irb):5
        1: from (irb):6:in `rescue in irb_binding'
ArgumentError (unknown keyword: :defaults)

```

**Comment by simi** [comment]
@rusikf no, that feature was rejected

**Comment by rusikf** [comment]
ok thanks for fast reply and description! @simi  :+1:

**Comment by Darsh560** [comment]
for the latest version of the rails, you can use the **create_with** option for default attributes.

` Post.create_with(created_at: Time.now, updated_at: Time.now).insert_all([
      { content: "first" },
      { content: "second" }
    ])
`
refer to this: https://api.rubyonrails.org/classes/ActiveRecord/Persistence/ClassMethods.html#method-i-insert_all
