### ISSUE TITLE
Zeitwerk "warning: previous definition of <x>" where <x> is a controller inheriting from ActionController::Metal

### ISSUE THREAD

**Issue by terracatta** [rails/rails#35502]
### Steps to reproduce
In my app I have a controller for a JSON RPC endpoint.  The top portion of the controller looks like this...

```ruby
class Launcher::JsonRpcController < ActionController::Metal
  ActionController::API.without_modules(
    :ForceSSL, :UrlFor, :Redirecting, :StrongParameters, :DataStreaming
  ).each { |left| include left }
```

When my Rails 6 beta 2 app has zeitwerk enabled and has been stopped/restarted several times, occasionally the Rails will throw an exception when this controller is accessed by a request and Puma will spit out a warning to stdout that looks like the following

```
/Users/jmeller/.rvm/gems/ruby-2.6.1/gems/activesupport-6.0.0.beta2/lib/active_support/inflector/methods.rb:282: warning: previous definition of Launcher was here
```

This happens no matter what I name the controller (I initially assumed this was a name conflict issue) and it does not happen in classic mode.

It also doesn't happen reliably, but from what I can tell it happens more often than not when the first request into my app after restarting the server is into this controller.

I am still working on reproduction steps but I think the following is pretty close.

1. Generate a new rails app and create two routes, one that is handled by a controller that inherits from `ApplicationController`, and another that is handled by a controller that inherits from `ActionController::Metal`)

1. Boot the rails server and send requests to both routes.

1. Restart the rails server and send one request to the route that is handled by the controller that inherits from `ApplicationController`

1. Restart the rails server again and send one request to the route that is handled by the controller that inherits from `ActionController::Metal`.

### Expected behavior
The request is handled normally (which it is when the app is `config.autoloader = :classic`

### Actual behavior

Rails produces an exception and emits the following in stdout

```
/Users/jmeller/.rvm/gems/ruby-2.6.1/gems/activesupport-6.0.0.beta2/lib/active_support/inflector/methods.rb:282: warning: previous definition of Launcher was here
```

### Additional Notes
I apologize for the lack of reliable reproduction steps. I have a feeling my issue is very obscure and outside the normal usage of Rails. While I cannot use the new autoloader on my new app because of this bug, I am not sure how important this issue will be for others (or if there is even a real bug here)

My intention in publishing the bug is perhaps someone else who hits this issue eventually will be able to compare their usage to mine and find commonalities so we can zero in on the true root cause.

### System configuration
**Rails version**: 6.0.0.beta2

**Ruby version**: 2.6.1

**Comment by fxn** [comment]
Hi @terracatta!

How is the `Launcher` namespace defined? Is it autovivified or defined in a file? If so, where?

Could you please enable logging

```ruby
# config/application.rb
config.load_defaults 6.0
Rails.autoloaders.logger = method(:puts)
```

and share the trace if you are able to reproduce?

**Comment by terracatta** [comment]
@fxn if "autovivified" means defined through the folder hierarchy, then it is that :)

I will add the logger and report back when the issue presents itself again. Thank you!

**Comment by fxn** [comment]
For the same price, could you please upgrade to the just released 1.3.2? It does not solve any bug or anything, but since we need to debug, it will be better to run what is current.

**Comment by fxn** [comment]
Have you tried this with RC1?

**Comment by terracatta** [comment]
I have, and I haven't had the issue since. I am going to close this, but will let you know right away if I see any problems with that controller.
