### ISSUE TITLE
Autoreloading nested structures does not work since Zeitwerk

### ISSUE THREAD

**Issue by remofritzsche** [rails/rails#35500]
Starting with beta2, I'm experiencing autoloading issues that prevent my files from being loaded properly and I think this is something specific to Rails. Thanks a bunch for having a look at this :)

### Steps to reproduce

[Sample rails application](https://github.com/remofritzsche/zeitwerk-rails-test)

Create a blank Rails 6.0.0.beta2 application and create / adapt the following files:

```ruby
# lib/foo.rb
module Foo
end

# lib/foo/bar.rb
module Foo
  class Bar
  end
end

# config/application.rb (inside Application class)
config.autoload_paths << Rails.root.join('lib')
```

To check:

```
bin/rails runner 'Foo::Bar'
```

### Expected behavior

The class `Foo::Bar` should be resolved correctly. When I create a blank non-rails setup with Zeitwerk, it works as expected.

### Actual behavior

```
uninitialized constant Foo::Bar
```

The autoreloader loads `lib/foo.rb` but does not load `lib/foo/bar.rb`. When I remove `lib/foo.rb`, it works fine (but I can't do that since I need the module `Foo` to have additional stuff in it).

### System configuration

**Rails version**: 6.0.0.beta2

**Ruby version**: 2.5.0-p0

**Comment by fxn** [comment]
I am pretty sure this is due to https://github.com/rails/rails/issues/35475.

**Comment by remofritzsche** [comment]
@fxn Good catch, when removing `bootsnap`, it works as expected. Thanks for your quick response and your brilliant work on Zeitwerk - I love it (besides this issue of course)!

Shall we leave this issue open or is it completely covered by #35475?

**Comment by fxn** [comment]
@remofritzsche thanks for the kind words :).

Yeah, I think we can close here and leave #35475 as one canonical ticket for this problem.

**Comment by remofritzsche** [comment]
Thanks.
