### ISSUE TITLE
Installing Rails 4.2 with Bundler 2.0 fails

### ISSUE THREAD

**Issue by pgwillia** [rails/rails#35518]
"bundle install" fails in my project because bundler 2.0 was released on January 03, 2019, and rails 4.2.11 gem require bundler gem < 2.0 .

Would it be possible to change the constraint?
https://github.com/rails/rails/blob/7a48f5869e7b9723cf94b5366ccaeb1e17060807/rails.gemspec#L30

**Comment by y-yagi** [comment]
4.2 series are not supported anymore for anything besides severe security fixes. Please consider upgrading your application. Thanks.

**Comment by kangkyu** [comment]
You can specify bundler version like `bundle _1.15.4_ install` @pgwillia
