### ISSUE TITLE
save! returns nil for invalid model

### ISSUE THREAD

**Issue by fschwahn** [rails/rails#35528]
### Steps to reproduce
```ruby
begin
  require "bundler/inline"
rescue LoadError => e
  $stderr.puts "Bundler version 1.10 or later is required. Please update your Bundler"
  raise e
end

gemfile(true) do
  source "https://rubygems.org"

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  # Activate the gem you are reporting the issue against.
  # gem "activerecord", "~> 5.1.0"
  # gem "activerecord", "~> 5.2.0"
  gem "activerecord", "~> 6.0.0.beta2"
  gem "sqlite3", "~> 1.3.13"
end

require "active_record"
require "minitest/autorun"
require "logger"

# Ensure backward compatibility with Minitest 4
Minitest::Test = MiniTest::Unit::TestCase unless defined?(Minitest::Test)

# This connection will do for database-independent bug reports.
ActiveRecord::Base.establish_connection(adapter: "sqlite3", database: ":memory:")
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :posts, force: true do |t|
    t.string :name
  end

  create_table :comments, force: true do |t|
    t.integer :post_id
    t.string :author
    t.text :comment
  end
end

class Post < ActiveRecord::Base
  has_many :comments, validate: true
end

class Comment < ActiveRecord::Base
  belongs_to :post

  validates_uniqueness_of :author, scope: [:post_id]
end

class BugTest < Minitest::Test
  def test_save_bang_not_raising
    post = Post.new(name: "test")
    author = "Fabian"
    post.comments.build(author: author)
    post.comments.build(author: author)

    # This should raise (because post is invalid) but it does not
    assert_raises { post.save! }

    # Actual behavior
    # assert_nil post.save!
    # assert post.errors.any?
    # refute post.persisted?
  end
end
```

### Expected behavior
When an associated model is invalid because of a uniqueness validation, I'd expect `save!` to raise `ActiveRecord::RecordInvalid`.

### Actual behavior
`save!` returns `nil` and does not save the record. This does not happen with other validations (eg. a presence validation), everything works as expected for those.

Maybe just the documentation is wrong (because it says about `save!`: "Unless an error is raised, returns true."), but I think ideally this should raise the exception as the other validations do.

### System configuration
**Rails version**: 6.0.0.beta2, but also observable in 5.2.

**Ruby version**: 2.5.3

**Comment by alexcameron89** [comment]
For more context, It looks like this issue might be experiencing the same issue as the one in https://github.com/rails/rails/issues/31718, which closed due to staleness.

@meinac mentioned in that issue that it might be related to an problem in a specific module of Active Record:

> The problem is in the AutosaveAssociation module. It does not validate the child records while automatically saving them.

**Comment by fschwahn** [comment]
> The problem is in the AutosaveAssociation module. It does not validate the child records while automatically saving them.

This was true in rails 5.1, but this changed beginning with rails 5.2, so it seems a bug was fixed there. If you look at my test case above, in rails 5.1 this would have played out as follows:

```ruby
class BugTest < Minitest::Test
  def test_save_bang_not_raising
    post = Post.new(name: "test")
    author = "Fabian"
    post.comments.build(author: author)
    post.comments.build(author: author)

    # Behavior in rails 5.1
    assert_equal post.save!, true
    assert_equal post.comments.reload.size, 1
  end
end
```

That means it would have saved the parent record, and one of the associated records (but not the second one, for which this validation failed).

In Rails 5.2 nothing is saved to database anymore if one of the validations fails, but no error is raised either by `save!`.
