### ISSUE TITLE
db:system:change to postgresql not updating gem version in Gemfile

### ISSUE THREAD

**Issue by yaodong** [rails/rails#35520]
### Steps to reproduce

```shell
rails new example
cd example/
bin/rails db:system:change --to=postgresql
bundle install
```

The Gemfile was updated from

```shell
gem 'sqlite3', '~> 1.3', '>= 1.3.6'
```

to 

```shell
gem 'pg', '~> 1.3', '>= 1.3.6'
```

The version was not updated.

### Expected behavior

I had expected

```shell
gem 'pg', '~> 1.1', '>= 1.1.4'
# or
gem 'pg'
```

So that the gem `pg` can be installed. 

### Actual behavior

```shell
Could not find gem 'pg (~> 1.3, >= 1.3.6)' in any of the gem sources listed in your Gemfile.
```

### System configuration

**Rails version**: Rails 6.0.0.beta2
**Ruby version**: ruby 2.6.0p0 (2018-12-25 revision 66547) [x86_64-darwin18]

**Comment by gmcgibbon** [comment]
The Gemfile gsub only subs out the database gem name for another one. I believe we locked SQLite to a specific version after the DB switching feature was implemented and merged. I think all we need to do is adjust https://github.com/rails/rails/blob/a62683f3e4326b222b6ad95b8b2dfcc31026d227/railties/lib/rails/generators/rails/db/system/change/change_generator.rb#L47-L50 to match version strings and add a test for it. I can fix this.
