### ISSUE TITLE
ActiveStorage fails to make an url inside Sidekiq's workers

### ISSUE THREAD

**Issue by a-ta-ta** [rails/rails#35540]
### Steps to reproduce
Quite a lot. And I doubt it really makes sense, because there's quite a lot stuff inside(Sidekiq, ActionCable) which is not related to the issue directly.

### Expected behavior

ActiveStorage makes url for image_tag in Sidekiq's worker as normally.

### Actual behavior
ActiveStorage ignores all the possible configs and uses the default host (example.org)
In my opinion, it is caused by `ActiveStorage::Current` which sets the host to request's host.
Unfortunately, in a worker we don't have a request anymore. So it requests all the expected images from example.org with predictable result :(

Finally, I got `service_url` working, but this type of url is not the result I expected.
Got service_url working by 

```
       ActiveStorage::Current.set(host: "https://mydomain.com") do
         avatar = message.user.avatar.service_url
       end
```
When I use rails_blob_path from this issue: [https://github.com/rails/rails/issues/31581](https://github.com/rails/rails/issues/31581), it makes url which is not being converted to rails/active_storage/representations and just stays as 'dead' link to rails/active_storage/blob/*.

### System configuration
**Rails version**: 5.2.1

**Ruby version**: 2.5.1

**Comment by orangedsoft** [comment]
Any suggested workarounds? I'm using ActionCable to send chat messages, which can includes images hosted by ActiveStorage. Changing the defaults in application_controller_renderer.rb doesn't seem to do anything. Everything just shows up at example.org

**Comment by a-ta-ta** [comment]
Do you use Sidekiq in message processing?

**Comment by the-siegmeister** [comment]
I use ActionCable and sidekiq to enqueue messages w/ attachments as well. After a job, I broadcast a partial w/ a link to the attachment. I'm getting this `example.org` problem, but only on broadcast. When I do a page refresh (assuming this page is a list of partials that has links to the attachments) everything is well, it points to my host.

**Comment by the-siegmeister** [comment]
Wrapping `blob.representation` in a `url_for` worked out for me.

**Comment by tpritc** [comment]
With the approach @j-sieg laid out getting more and more popular now that we've got [Turbo Streams in Hotwire](https://turbo.hotwire.dev/reference/streams) (which, by the sounds of it will be bundled with Rails 7?), it might be worth revisiting this so it can be rendered as-expected in a worker. It'd be nice if it worked out of the box.

**Comment by archonic** [comment]
Could anyone elaborate on what "wrapping `blob.representation` in a url_for`" means?

A `blob.representation` is the same class as `avatar.variant` and calling this from a background worker is hitting this redirect to example.org issue:

```
url_for( user.avatar.variant(resize_to_limit: [44, nil]) )
```
