### ISSUE TITLE
Update Document 'Error loading the 'sqlite3''

### ISSUE THREAD

**Issue by baramatsubonzo** [rails/rails#35551]
### Steps to reproduce

In case of Rails 5.2.2, many people seem to face [this problem](https://github.com/rails/rails/issues/35153)
### Expected behavior
Please post the solution to this problem on README or other documents .

#### example
In case of rails 5.2.2
in Gemfile you update gem sqlite3
`gem 'sqlite3', '~> 1.3.6'`
after that, run
`$ bundle install`
##### Related Issue
- see also [#35153](https://github.com/rails/rails/issues/35153)

thank you very much.
### Actual behavior
nothing to explain .
### System configuration
**Rails version**:5.2.2

**Ruby version**:2.5.1

**Comment by zzz6519003** [comment]
So embarrassing for new user to bump into error

2019-03-24 20:26:10 +0800: Rack app error handling request { GET / }
#<LoadError: Error loading the 'sqlite3' Active Record adapter. Missing a gem it depends on? can't activate sqlite3 (~> 1.3.6), already activated sqlite3-1.4.0. Make sure all dependencies are added to Gemfile.>

**Comment by rafaelfranca** [comment]
Make sure you are using the latest version of Rails. This issue was already fixed.
