### ISSUE TITLE
Rails::Application::Configuration::Custom - option relative_url_root appearing

### ISSUE THREAD

**Issue by robbytobby** [rails/rails#35561]
### Steps to reproduce
1. create a new default rails app
2. rails generate scaffold foo name:string
3. create an initilizer test.rb
```
Rails.configuration.x.foo =  Rails::Application::Configuration::Custom.new
```
4. define a helper method to access it and name the method config
```
module ApplicationHelper
  def config
    Rails.configuration.x.foo
  end
end
```
5. call the foos controller
 
and you'll get a Error
` no implicit conversion of nil into String`
extracted source:
```
<head>
  <title>Testapp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %> ###highlighted
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
```
The Error is thrown at (line number is for rails 4.2.8, its line 206 in rails 5.2.2)
`actionview  lib/action_view/helpers/asset_url_helper.rb:140:in join`
because magically there's a configuration option appearing:
```
[1] pry(#<#<Class:0x007fe1a64bfc28>>)> Rails.configuration.x.foo
=> #<Rails::Application::Configuration::Custom:0x00000004112c50 @configurations={:relative_url_root=>{}}>
```
Just renaming the helper method solves the problem (took me hours to find that)

The problem was introduced with rails 4.2.8 and still persists in rails 5.2.2. 
All versions tested with ruby 2.3.3

**Comment by y-yagi** [comment]
`Rails::Application::Configuration::Custom` is an internal class, and it is not intended for user use. Avoid using it in your application. Thank you.
