### ISSUE TITLE
Active Storage: mogrify error without message on representation controller and variant.processed

### ISSUE THREAD

**Issue by purple-sinhyeok** [rails/rails#35563]
### Steps to reproduce
Send request for showing variant image to representations controller
(**variant image not yet processed**)

`GET /rails/active_storage/representations/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBYnc9IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--baa3ee2763d8213bdca1dee45705607825bfebe1/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaDdCam9MY21WemFYcGxTU0lQTVRBNE1IZzBNRGsyUGdZNkJrVlUiLCJleHAiOm51bGwsInB1ciI6InZhcmlhdGlvbiJ9fQ==--5fdb58bfb1f6fa9dd38ff1dc821c383ab3733627/detail_img_190125@3x.png`

![스크린샷 2019-03-11 오후 3 47 10](https://user-images.githubusercontent.com/44961659/54106066-55267b80-4418-11e9-838c-c9637426b117.png)

### Expected behavior
Detail error message and error code

### Actual behavior
MiniMagick::Error
`mogrify -resize 1080x4096> /tmp/mini_magick20190311-7-1mcpgov.png` failed with error:
**(nil)**

![스크린샷 2019-03-11 오후 3 59 10](https://user-images.githubusercontent.com/44961659/54106042-493ab980-4418-11e9-8295-26d229a64b66.png)

### System configuration
**Rails version**:
5.2.2

**Ruby version**:
2.5.3

**Comment by y-yagi** [comment]
Can you please provide a sample application that reproduces the issue?
