### ISSUE TITLE
Destroying nested object does not propagate errors

### ISSUE THREAD

**Issue by hidroo** [rails/rails#35584]
We have these classes:
```
class Group < ApplicationRecord
  has_many :group_users, dependent: :destroy
end

class GroupUser < ApplicationRecord
  belongs_to :group
  before_destroy :stop_destroy

  def stop_destroy
    errors.add(:error, "Don't destroy me!")
    throw :abort
  end
end
```

And when I say:
`group_user.destroy`
It says I cannot destroy it, and `group_user.errors` gives me a list of all the errors.

But, If I had a group, that has a group_user. And say:
`group.destroy`
It says I cannot destroy it, but `group.errors` does not give me the errors of the group_user in the previous step. It does not give me **any** errors at all!

We added a little workaround:

```
class Group < ApplicationRecord
  has_many :group_users, dependent: :destroy
end

class GroupUser < ApplicationRecord
  belongs_to :group
  before_destroy :stop_destroy
  after_rollback : propagate_error_message

  def stop_destroy
    errors.add(:error, "Don't destroy me!")
    throw :abort
  end

  def propagate_error_message
    self.group.errors.add("group_user.error", "Don't destroy me!")
  end
end
```

And now when I say
`group.destroy`
It says I cannot destroy it, and `group.errors` gives me the `"group_user.errors"` errors.

Is this the way it is supposed to be, we were wondering with this for close to a week.
We are thinking of implementing a base that does that automagically - adds all the errors of a child, to object that it `belongs_to`. But before that we decided to write this issue. Maybe there is a thinking behind this.

P.S 
We have a lot of nested models, and when we add errors to a nested object thought an `update`, or `save` it propagates the errors on the above object. We are struggling with the destroy.

Best wishes,
Michael

**Comment by y-yagi** [comment]
Can you create a reproduce script with this [template](https://github.com/rails/rails/blob/master/guides/bug_report_templates/active_record_gem.rb)?

**Comment by hidroo** [comment]
Hello, @y-yagi 

I did not know how to attach the code, so:

With problem.
https://pastebin.com/3Yu1YuAL

Our 'hacky' solution, that we particularly don't like.
https://pastebin.com/5ecqBzQp

**Comment by hidroo** [comment]
@y-yagi Did you manage to find a solution to our problem or are we doing something wrong?

Best wishes,
Michael

**Comment by y-yagi** [comment]
Thanks for your create a reproduce script. 
First, errors are added in manually do not propagate to parent. So I think your `propagate_error_message` is the correct approach.

By the way, why you want to stop destroy in children? If you do not want to delete records that have children, can you not use `restrict_with_exception` dependent?

**Comment by shadydealer** [comment]
The #stop_destroy is used in the group user to simulate a validation error on the model. So when you attempt to destroy the group and when ActiveRecord attempts to destroy its group users they would raise errors.

**Comment by hidroo** [comment]
@y-yagi Is there a way for manually added errors to be propagated to the parent object? 

I our project a lot of things are created, and destroyed using nested sets. When using nested sets we destroy, create, update children of parent object. And we expect that, when the child has a problem the parent should know.

It works with create and update, only the destroy is the problem. We want to know when something has happened to a child object.

We expect it to work the same at the validations, but it doesn't.

**Comment by Tao-Galasse** [comment]
It seems to still be a problem today; and worst, in rails 6 the workaround proposed by @hidroo seems to not working as well, I can't even enter in the after_rollback method 😞

**Comment by Flixt** [comment]
I also tried how this could be integrated into ActiveRecord here: https://github.com/Flixt/rails/tree/propagate-errors-on-destroy-to-parent not sure if would be worth a PR which has a chance to be merged.

**Comment by Zifro** [comment]
Hello, fellow Ruby on Rails enthusiasts. I ran into the same issue as described today (while still running Rails 7.2, for the record), and I tentatively used @Flixt 's solution based on `destroyed_by_association`.

My case is slightly different because the destruction happens through the parent's model `accepts_nested_attributes_for`. As a consequence, `destroyed_by_association` is `nil`. I solved my issued using [`ActiveModel/Errors#import`](https://api.rubyonrails.org/classes/ActiveModel/Errors.html#method-i-import) to import the error set on the child object to its parent:
```ruby
# Parent model (simplified)
class Meeting < ApplicationRecord
  belongs_to :invoice, optional: true

  has_many :meeting_treatments
  accepts_nested_attributes_for :meeting_treatments, allow_destroy: true
end

# Child model (simplified)
class MeetingTreatment < ApplicationRecord
  belongs_to :meeting

  before_destroy :prevent_from_destroying_if_meeting_is_invoiced

  def prevent_from_destroying_if_meeting_is_invoiced
    if meeting.invoice_id
      errors.add(:base, :delete_denied_meeting_is_invoiced)
      meeting.errors.import(errors.first)
      throw(:abort)
    end
  end
end
```
