### ISSUE TITLE
Unable to use partial locals when using 'render partial' shorthand

### ISSUE THREAD

**Issue by taylorthurlow** [rails/rails#35592]
Consider the following two ways of rendering a partial `_table.html.erb`:

~~~erb
<%= render 'table', locals: { things: @things } %>
~~~

~~~erb
<%= render partial: 'table', locals: { things: @things } %>
~~~

In the first example, the local variable `things` does not exist within the partial. After adding the `partial: `, locals are properly passed into the partial. If this is intended (it might be, given the fact that `render` itself is not just for rendering partials), then it would be helpful if the first example didn't silently swallow the `locals` option.

### System configuration
**Rails version**: 5.2.2
**Ruby version**: 2.6.1

**Comment by rafaelfranca** [comment]
In the first case `things` is inside the partial as `locals[:things]`. When you use the shortcut syntax `locals` is not needed to pass variables. See the "Rendering the default case" section in http://api.rubyonrails.org/classes/ActionView/PartialRenderer.html
