### ISSUE TITLE
AutLoad Broken on Windows with Ruby 2.6

### ISSUE THREAD

**Issue by cfis** [rails/rails#35609]
Rails autoloading is broken on Windows due to this Ruby 2.6 bug:

https://bugs.ruby-lang.org/issues/15649

Having said that, is there any reason Rails is combining the glob patterns into a string and doing this:

`Dir["{D:/zerista/app/app/**/*.{rb},D:/zerista/app/app/models/data_sources/**/*.{rb}}"]`

Versus passing in an array, so doing this:

`Dir.glob(["D:/zerista/app/app/**/*.{rb}","D:/zerista/app/app/models/data_sources/**/*.{rb}"])`

That second option still works as expected on Windows.

Relevant code is here:

https://github.com/rails/rails/blob/25620f91ca0ab261fbc883763040ec58d205514e/activesupport/lib/active_support/file_update_checker.rb#L150

And here:

https://github.com/rails/rails/blob/25620f91ca0ab261fbc883763040ec58d205514e/activesupport/lib/active_support/file_update_checker.rb#L105

Happy to make a pull request if this sounds like a good change.

**Comment by fxn** [comment]
ACK!

**Comment by daniel-rikowski** [comment]
As a workaround you can switch to ` ActiveSupport::EventedFileUpdateChecker` which also improves request times with large applications. (Because not every file has to be checked on every request, which is quite slow on Windows)

**Comment by cfis** [comment]
Ah interesting, will give that a try.
