### ISSUE TITLE
Make ActiveJob::Base more composable

### ISSUE THREAD

**Issue by azbshiri** [rails/rails#35608]
### Steps to reproduce
Currently I'm using a super class called `Notifier` and inject push notification service as a dependency 

```ruby
# frozen_string_literal: true

class TestDriver
  def self.deliveries
    @deliveries ||= 0
  end

  def self.call(message, device_uids, params)
    @deliveries += 1
  end
end

RSpec.describe Notifier, type: :job do
  Notifier.driver = TestDriver

  it 'should send notfication using different drivers' do
    expect { Notifier.notification("foo", ["invalid_uid"], {}).perform_now }.to change(TestDriver, :deliveries).by(1)
  end
end
````

```ruby
class notifier < activejob::base
  def self.driver=(driver)
    @driver = driver
  end

  def self.driver
    @driver ||= OneSignalDriver
  end

  def initialize(message, device_uids, params = {})
    @message = message
    @device_uids = device_uids
    @params = params
  end

  def self.notification(message, device_uids, params = {})
    new(message, device_uids, params)
  end

  def perform
    self.class.driver.call(@message, @device_uids, @params)
  end
end
```

But I cannot use perform_later on a instance of a class that inheritances from `ActiveJob::Base` due it's been defined on eigenclass. Is there a way so that I can call `perform_later` on a class method that inheritances from `ActiveJob::Base`.

### Expected behavior
```ruby
Notifier.notification(:new_mission, ["some_device_uid"], {}).perform_later
```

### Actual behavior
```ruby
Notifier.notification(:new_mission, ["some_device_uid"], {}).perform_later
```
```
NoMethodError: undefined method `perform_later' for #<Notifier:0x00007f90767d6000>
```

### System configuration
**Rails version**:
5.2.1

**Ruby version**:
2.5.3

**Comment by gmcgibbon** [comment]
In Active Job, you receive arguments through the perform method `def perform(arg, another_arg, etc)`. Overriding `#initialize` and assigning ivars won't work. Please read the [guide for Active Job](https://guides.rubyonrails.org/active_job_basics.html) and refer usage questions to the mailing list or StackOverflow where a wider community can assist you. The issue tracker is reserved for bugs only. Thanks!
