### ISSUE TITLE
Active Storage Module::DelegationError: size delegated to attachment, but attachment is nil

### ISSUE THREAD

**Issue by RailsCod3rFuture** [rails/rails#35613]
### Steps to reproduce
**post.rb**

`has_one_attached :photo`

**posts_controller.rb**

```
def create
  @post = current_user.posts.build(post_params)
  @post.insight_photo.attach(params[:post][:photo])
  respond_to do |format|
    if @post.save
      format.js
      format.html {redirect_to posts_path}
    end
  end
end
```

**rails console**

```

>> @post = Post.new(id: 8, user_id: 1, body_text: "Testing photos in console", photo: File.open(Rails.root.join('app', 'assets', 'images', 'fallback', 'user_profile_bg_default.png')), created_at: Time.now)
#<Post id: 8, body_text: "Testing photos in console", photo: nil, user_id: 1, post_id: nil, created_at: "2019-03-14 20:05:50", updated_at: nil, impressions_count: nil, hash_id: nil, cached_votes_total: 0, cached_votes_score: 0, cached_votes_up: 0, cached_votes_down: 0, cached_weighted_score: 0, cached_weighted_total: 0, cached_weighted_average: 0.0, posts_count: 0>
>> @post.save
   (31.2ms)  BEGIN
  User Load (33.1ms)  SELECT  "users".* FROM "users" WHERE "users"."id" = $1 LIMIT $2  [["id", 1], ["LIMIT", 1]]
   (15.6ms)  ROLLBACK
Module::DelegationError: size delegated to attachment, but attachment is nil
	from (irb):17

```

### Expected behavior
The post should save with the photo attached.

### Actual behavior
The post is rolling back with _a size delegated to attachment, but attachment is nil_ error.

### System configuration
**Rails version**:

`rails 5.2.0`

**Ruby version**:

`ruby 2.4.4`

**Comment by gmcgibbon** [comment]
Can you provide an example application that reproduces the error? Also, to attach a raw file with ActiveStorage, you need to do something like this:

```
Post.create(photo: { io: Rails.root.join("public", "something.jpg").open, filename: "picture.jpg"  })
```

[See docs](https://edgeguides.rubyonrails.org/active_storage_overview.html#attaching-file-io-objects)

**Comment by RailsCod3rFuture** [comment]
After tinkering with the partial file that leads to this issue. I was able to get past this error, momentarily. The next Issue I have, is Active Storage is not saving the image when the form is posted through AJAX. I can understand the delay between the form POST and the server waiting for Active Storage to retrieve an image. But, no image is saved at all. (I'm using the latest remotipart gem)

_form.html.erb

```
<%= simple_form_for(@post, html: {multipart: true}, method: :post, remote: true, authenticity_token: true) do |f| %>
  <%= f.error_notification %>
  <div class="row">
    <div class="col">
      <div class="post-textarea">
          <%= f.input :body_text, as: :text, class: 'form-control post-placeholder post-txt-area', label: false, placeholder: 'Write a new Post, style: "overflow: hidden; resize: none;", input_html: {:maxlength => 400}  %>
        </div>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col-md-5">
      <%= f.button :submit, 'Post', class: 'form-control submit-button bttn-gradient bttn-md bttn-royal', :data => {:disable_with => 'Posting now...'} %>
    </div>
    <div class="col-md-5">
      <label class="bttn-minimal bttn-md bttn-royal">
        Add Photo
        <span style="display:none;">
                <%= f.input :photo, as: :file, label: false, input_html: {accept: 'image/*'} %>
                </span>
      </label>
      <% if f.object.photo.attached? %>
        <%= image_tag(url_for(f.object.photo), class: 'img-responsive img-thumbnail') %>
      <% end %>
      <div class="post-preview-container">
        <img id="img_prev" width="100" height="100" src="#" alt="preview" class="img-thumbnail d-none"/> <br/>
        <a href="#" id="cancel_img_btn" class="d-none" onclick="return !(document.getElementById('post_photo').innerHTML=document.getElementById('post_photo').innerHTML);">Cancel
          Upload</a>
      </div>
    </div>
  </div>
<% end %>
```

**create.js.erb**

```
$("#container_posts").prepend("<%= escape_javascript render partial: "career_insights/#{@career_insight.career_insight_type}", locals: {career_insight: @career_insight } %>");
$("#career_insight_<%= @career_insight.id %>").hide().fadeIn(1000);
$("#no-career-insight-posts").hide().fadeOut();
$("#career_insight_body_text").val("");
$("#img_prev").hide().fadeOut();
$("#cancel_img_btn").hide().fadeOut();

alert('success!');
<% if remotipart_submitted? %>
alert('submitted via remotipart')
<% else %>
alert('submitted via native jquery-ujs')
<% end %>

```

The form submits, but forgets the photo was being uploaded. @gmcgibbon

**Comment by RailsCod3rFuture** [comment]
I just need simple ajax functionality for images to work. I see that you can do it with the JS Direct Upload events. But, how would I implement it into my current solution?

**Comment by gmcgibbon** [comment]
For usage questions, please refer to the mailing list or StackOverflow where a wider community can assist you. This also seems like it might be a problem related to the `remotipart` gem, which isn't maintained by rails. The issue tracker is reserved for bugs only. Thanks!

**Comment by ziaulrehman40** [comment]
I am also randomly facing this issue, some records save all fine some end up with this error.

My files are also being posted by AJAX request. Something is going on, any help with debugging will be great.

**Comment by ziaulrehman40** [comment]
I think I found it, this issue can occur if your table PK type is not int/bigint, in our case that type is uuid, closer inspection seems to suggest that it kidn fo calls `to_i` on whatever the id type is(at-least thats the behavior for our uuid keys) for insertion in `active_storage_attachments`'s `record_id` column.

Which works for some UUIDs and does not for other. Even when it works that;s not reliable.

There are issues like https://github.com/rails/rails/issues/35746 which can be of help.
