### ISSUE TITLE
MemCacheStore uses a TTL (expires_in) longer than specified

### ISSUE THREAD

**Issue by johnmaxwell** [rails/rails#35625]
The maximum expiration period supported by memcached is 2592000 (30 days: `60*60*24*30`). For some reason, when I instantiate a MemCacheStore with that period and try to write keys, I get a warning that 2592300 exceeds the maximum Memcache TTL.

Why is MemCacheStore attempting to use a TTL that is 5 minutes longer than specified?

### Steps to reproduce
```ruby
mc_store = ActiveSupport::Cache::MemCacheStore.new(
  "localhost:11211", expires_in: 2592000
 )
mc_store.write('abc', '123')
# Dalli::Server#connect localhost:11211
# Expiration interval (2592300) too long for Memcached, converting to an expiration timestamp

dalli_store = ActiveSupport::Cache::DalliStore.new(
  "localhost:11211", expires_in: 2592000
 )
dalli_store.write('abc', '123')
# Cache write: abc
# Dalli::Server#connect localhost:11211
```
### Expected behavior
Expect it to cache for 2592000, the maximum TTL allowed by memcached, without warning or conversion to timestamp. This is what ActiveSupport::Cache::DalliStore seems to do.

### Actual behavior
Emits warning "Expiration interval (2592300) too long for Memcached, converting to an expiration timestamp" when executing a write.

### System configuration
**Rails version**: ~~5.1.6.2~~ ~~5.2.3~~ **6.0.1**

**Ruby version**: ~~2.5.1~~ **2.6.5**

**Dalli version**: ~~2.7.9~~ **2.7.10**
`
$ date
Fri Mar 15 13:09:18 EDT 2019
`

**Comment by y-yagi** [comment]
It seems to be for the support of `:race_condition_ttl`. 
https://github.com/rails/rails/blob/8ed636511779ed1472f4f88362ded34f61005f4a/activesupport/lib/active_support/cache/mem_cache_store.rb#L154-L156 
Ref: https://github.com/rails/rails/pull/7913 

I think that it is necessary to take some fix such as adding some options or not adding values if the 30-days limit is exceeded.

**Comment by johnmaxwell** [comment]
@rails-bot Confirmed still an issue on 6.0.1. Will update description.
