### ISSUE TITLE
ActiveStorage Race Condition After Upgrading to Rails 6.0.0.beta3

### ISSUE THREAD

**Issue by weilandia** [rails/rails#35624]
### Steps to reproduce
[Here](https://github.com/weilandia/active_storage_race_condition/blob/master/test/models/quote_test.rb) is a pared down test similar to a test I have in my app that tests a service meant for combining attachments into a flatfile for search indexing.

In my application, this test is now consistently failing indeterminately after upgrading to  Rails 6.0.0.beta3 from Rails 5.2.2.

In the new Rails 6.0.0.beta3 application linked above, it failed once out of about 50 runs, so I'm not sure that counts as recreating, but just hoping someone might have some insight on a change that might be causing a new race condition when attaching files with Active Storage.

As a side note, when running the test linked above, I noticed that it was significantly slower to run the test with `parallelize(workers: :number_of_processors)` on my machine (1 year old standard mac pro). Without  `parallelize(workers: :number_of_processors)` the test runs consistently under half a second, while with  `parallelize(workers: :number_of_processors)` it averages around 11 seconds.

### Expected behavior
The linked test should pass. I should be able to reliably add multiple attachments in tests and assert they've been attached.

### Actual behavior
Attachments intermittently do not attach before the assertion.

### System configuration
**Rails version**: Rails 6.0.0.beta3

**Ruby version**: 2.6.1

Thanks!

**Comment by gmcgibbon** [comment]
I'm unable to make your test case fail. I would suggest working on getting the failure reproducible, even if that means monkey patching thread sleeps into ActiveStorage etc. 

The only thing I can think of is the analysis job that gets enqueued and processed asynchronously, but it only updates metadata on blobs. Maybe try wrapping your `attach` calls in [`perform_enqueued_jobs`](https://edgeapi.rubyonrails.org/classes/ActiveJob/TestHelper.html#method-i-perform_enqueued_jobs) or setting your test queue_adapter to `:inline`?

**Comment by weilandia** [comment]
Thanks @gmcgibbon. I'll close for now and try to get a better test case.

**Comment by weilandia** [comment]
![spacex-81773-unsplash](https://user-images.githubusercontent.com/13652979/55107818-741b4380-508f-11e9-953b-c1c19a5a9fad.jpg)
