### ISSUE TITLE
PROPOSAL to return frozen values from Rails.application.secrets

### ISSUE THREAD

**Issue by koenhandekyn** [rails/rails#35630]
We had a serious issue in production that was caused by a (once noticed) very very obvious bug. We were fetching values from the Rails.application.secrets object and where overwriting the values without being aware of it elsewhere. A classic one an very much aware that it is an obvious bug.  But it's a bug which is not always very trivial to test for or notice (some issues only appear in combination with multi threading).

From the Rails Framework one could however 'help' the developer make unintended mistakes by returning immutable (frozen) values. From a performance perspective I assume the freeze approach would be preferred. 

My current feeling is that it's in general safer to follow the functional programming style approach and have the values as read only, which probably corresponds to the 99% case, and also to the 'intend' of the framework and help avoid nasty bugs. The main drawback would be a minor performance penalty in the case when one really would need/want to mutate values from the secrets file, as one would be forced to dup first, though that probably is a very good thing in most of the cases. 

I wanted to share one possible solution for a root cause of a rather serious incident we had in production as a proposal but maybe i'm now still blinded by the issue and I might miss some good reason to not freeze the values. 

#### Example

fetch some config from Rails.application.secrets and (ab)use it somewhere else 

         config = Rails.application.secrets.some_config

         # ... and somewhere else in a galaxy far far away ...
         # ... it's easily forgotten that one is changing a 'global const'
         default_config[:key] = object.some_value

**Comment by morgoth** [comment]
`secrets` is deprecated in favor of `credentials` now https://github.com/rails/rails/blob/master/railties/lib/rails/commands/secrets/secrets_command.rb#L58

**Comment by rafaelfranca** [comment]
Thank you so much for the issue but we don't take feature request on the issue tracker. We recommend you to try to implement the feature and send us a pull request or if you are in doubt if the feature will be accepts ask in Rails Core mailing list for feedback.
