### ISSUE TITLE
rails accepts_nested_attributes_for can't update

### ISSUE THREAD

**Issue by Woner1** [rails/rails#35641]
**Rails version**: 5.2.2

**Ruby version**: 2.6.0

**I Using accepts_nested_attributes_for to update has_many nested tables, Why not update but insert**

**diaries_controller.rb**

```
def update
  @diary=Diary.find(params[:id])
  if @diary.update(update_diary_params)
    render_ok
  else
    render_err :update_error
  end
end


  def update_diary_params
      params.require(:diary).permit(:date,:weather,:remark, :diary_pictures_attributes=> [:diary_picture,:clothing_picture,:id,:_destroy])
  end
```

**model/diary.rb**

```
class Diary < ApplicationRecord
  has_many :diary_pictures,dependent: :destroy

  accepts_nested_attributes_for :diary_pictures,allow_destroy: true

end
```

**model/diary_picture.rb**

```
class DiaryPicture < ApplicationRecord
  belongs_to :diary
  validates_presence_of :diary
end
```

[https://i.stack.imgur.com/Gzt9S.png](url)

**Comment by adbatista** [comment]
@Woner1 make sure the request is sending the diary picture id

**Comment by gmcgibbon** [comment]
@adbatista is correct, you need to `id:` with your nested attributes in order to get them to update.

For further usage questions, please refer to the mailing list or StackOverflow where a wider community can assist you. The issue tracker is reserved for bugs only. Thanks!

**Comment by RaymondFallon** [comment]
I was having the same problem (with Ruby `2.4.4` and Rails 5.1.6.2`) and adding `id` to the permitted, nested parameters solved it for me.

**Comment by anisssoudki** [comment]
> @Woner1 make sure the request is sending the diary picture id

thank you i found this to be very helpful
