### ISSUE TITLE
Can't install Webpacker and Action Text on rails 6.0.0.beta3

### ISSUE THREAD

**Issue by Klashe** [rails/rails#35640]
I recently upgraded to  6.0.0.beta3 on my windows 10 computer but every time I tried installing **Webpacker** and **Action Text** on the existing app, i get this error:

    C:\Users\hp\Documents\Locker\APP\storyadvanced>rails webpacker:install:stimulus
    rails aborted!
    NoMethodError: undefined method `strip_heredoc' for #<String:0x0000000005b57d68>
    C:/Users/hp/Documents/Locker/APP/storyadvanced/config/application.rb:7:in `<top (required)>'
    C:/Users/hp/Documents/Locker/APP/storyadvanced/Rakefile:4:in `require_relative'
    C:/Users/hp/Documents/Locker/APP/storyadvanced/Rakefile:4:in `<top (required)>'
    bin/rails:9:in `require'
    bin/rails:9:in `<main>'
    (See full trace by running task with --trace)

![Screenshot (52)](https://user-images.githubusercontent.com/26233134/54470103-25c29680-47ab-11e9-9cca-8d09f1d2c1f3.png)

i did `rails webpacker:install:stimulus` and `rails action_text:install`

I have bundle updated my app
I have ruby v2.5.1 and rails 6.0.0.beta3 and gem 'webpacker', '>= 4.0.0.rc.3'  installed
and also gem 'webpacker', '>= 4.0.0.rc.3'

**Comment by y-yagi** [comment]
Your error came from `rails_admin`. It seems `rails_admin` has an issue with Rails 6.0.0. Ref https://github.com/sferik/rails_admin/issues/3116.
