### ISSUE TITLE
Could not find "javascript/channel.coffee" in any of your source paths.

### ISSUE THREAD

**Issue by localhostdotdev** [rails/rails#35648]
### Steps to reproduce

- Have a Rails 5.2 app
- Upgrade to Rails 6.0
-  `rails g channel updates`

### Expected behavior

Generates the files for a new channel

### Actual behavior

```
Could not find "javascript/channel.coffee" in any of your source paths.
```

### System configuration

**Rails version**: Rails 6.0.0.beta2
**Ruby version**: ruby 2.6.0p0 (2018-12-25 revision 66547) [x86_64-darwin17]

`rails g channel` should be backward compatible with the `app/assets/javascripts` directory.

Also `rails app:upgrade` should move `app/assets/javascripts` to `app/javascripts` (edit: not possible probably).

edit: I ran `spring stop` and now `rails g channel` works but it's creating file in `app/javascript` not in `app/assets/javascripts`. Might be related to having updated `application.rb` with `load_defaults 6.0` instead of `5.2`.

I'm actually confused as to if `app/javascript` or `app/assets/javascripts` is the canonical place to put js files.

edit2: Ok must be sprockets in `assets/javascripts` vs webpack in `javascript`. If it's possible to not use webpack that would be nice (e.g. detect that webpacker is not installed / detect use of `app/assets/javascripts`, etc.). I'm getting so many different errors when trying it.

**Comment by tambakoo** [comment]
@localhostdotdev were you able to find a solution here ?

**Comment by isteel** [comment]
For anyone else having this issue, I resolved it when upgrading from Rails 5.x to Rails 6.x by adding:

Add config.generators.javascript_engine = :js to your application.rb

It appears you need to tell the generators to stop producing coffeescript.

See https://stackoverflow.com/questions/47784650/how-to-disable-coffeescript-on-rails-5

**Comment by mathieujobin** [comment]
Thanks for the tip @isteel 

I wonder if one hits the same problem but still want to use coffeescript, 

especially without webpack. I wonder what would be the way?
