### ISSUE TITLE
relation "active_storage_attachments" does not exist

### ISSUE THREAD

**Issue by localhostdotdev** [rails/rails#35647]
### Steps to reproduce

- Have a Rails 5.2 app without active storage installed (no tables)
- `rails app:update`
- `rake db:migrate`

### Expected behavior

Should not try to add a foreign key to a non-existent table

### Actual behavior

Tries to add a foreign key to a non-existent table

### System configuration

**Rails version**: Rails 6.0.0.beta2
**Ruby version**: ruby 2.6.0p0 (2018-12-25 revision 66547) [x86_64-darwin17]

Generated migration causing this error:

```ruby
# This migration comes from active_storage (originally 20180723000244)
class AddForeignKeyConstraintToActiveStorageAttachmentsForBlobId < ActiveRecord::Migration[6.0]
  def up
    unless foreign_key_exists?(:active_storage_attachments, column: :blob_id)
      add_foreign_key :active_storage_attachments, :active_storage_blobs, column: :blob_id
    end
  end
end
```

**Comment by sharang-d** [comment]
This is probably fixed with https://github.com/rails/rails/pull/35620.

**Comment by localhostdotdev** [comment]
Thanks @sharang-d, I guess as a side note I think this migration should not be created unless the project has active storage tables.

**Comment by deepj** [comment]
I have the same issue while trying one Rails 5.2 app to Rails 6.0 RC1.

**Comment by localhostdotdev** [comment]
@deepj you can just delete the migration if you are not using active storage

**Comment by deepj** [comment]
This app uses ActiveStorage
