### ISSUE TITLE
Conflicting documentation on cookies/sessions

### ISSUE THREAD

**Issue by Medvezo** [rails/rails#35650]
Quoting https://edgeapi.rubyonrails.org/classes/ActionController/Base.html:

> Sessions are stored by default in a browser cookie that's cryptographically signed, but unencrypted. This prevents the user from tampering with the session but also allows them to see its contents.

Is it the case for Rails 5.2 / 6.0? (i.e. user seeing the innards of cookies)

Quoting: https://edgeguides.rubyonrails.org/security.html

> The CookieStore uses the encrypted cookie jar to provide a secure, encrypted location to store session data. Cookie-based sessions thus provide both integrity as well as confidentiality to their contents.

Seems like these 2 paragraphs conflict each other.

**Comment by DarknessCatt** [comment]
I believe CookieStore encrypts and saves the data in the client, so you can easily restore sessions:

(Quoting https://edgeguides.rubyonrails.org/security.html#session-storage)
> Rails CookieStore saves the session hash in a cookie on the client-side. The server retrieves the session hash from the cookie and eliminates the need for a session ID. That will greatly increase the speed of the application, but it is a controversial storage option and you have to think about the security implications and storage limitations of it:

The session itself (stored in the browser cookie, cryptographically signed, but unencrypted) are server side.

These are the conclusions I took after reading the documentation, I don't have much experience myself.
