### ISSUE TITLE
image_path without extension

### ISSUE THREAD

**Issue by gadikotamohan** [rails/rails#35651]
### Steps to reproduce
- Add a image helper as follows

`<%= image_tag image_path("sample/olivia"), class: 'img img-raised' %>`
and run in development and it works without any errors. But if I run in production I would get 

`F, [2019-03-17T18:36:37.568202 #25602] FATAL -- : [1c06c250-3a3e-46f4-8dbb-10686d28d26f] ActionView::Template::Error (The asset "sample/olivia" is not present in the asset pipeline.):`

### Expected behavior
- Should set actual path with digest / find the asset path with give name.

### Actual behavior
- Throws internal server error

### System configuration
**Ruby version**: 2.5.3

**Rails version**: 5.2.2

**Comment by arvind02** [comment]
I hope you meant 

**Rails Version - 5.2.2**
**Ruby Version - 2.5.3**

**Comment by himanshu-myupchar** [comment]
@gadikotamohan  have you precompiled the assets?

**Comment by gadikotamohan** [comment]
> @gadikotamohan have you precompiled the assets?

Yes, even asset those files in the asset pipeline as well.

**Comment by gadikotamohan** [comment]
> I hope you meant
> 
> **Rails Version - 5.2.2**
> **Ruby Version - 2.5.3**

yes, sorry my bad corrected my post.

**Comment by lachlanjc** [comment]
To clarify, do you have a file with no extension? Can you say why? If the content type isn’t set correctly, won’t that be an issue for browsers as well?

**Comment by gadikotamohan** [comment]
@lachlanjc  Um.. there need to be consistency of asset url helpers behavior between environment ie; when generating image path in development it is returning correct path but in production mode we get 500 error saying file is not part of asset precompile list.

This can re-produced in https://github.com/gadikotamohan/image_test project

**In production mode:**
![Screenshot 2019-07-10 at 1 35 37 AM](https://user-images.githubusercontent.com/2775013/60919398-3abfba00-a2b3-11e9-8237-91a2113ff8df.png)

**In development mode**
![Screenshot 2019-07-10 at 1 36 49 AM](https://user-images.githubusercontent.com/2775013/60919445-57f48880-a2b3-11e9-808f-74502ee1a86f.png)
![Screenshot 2019-07-10 at 1 36 43 AM](https://user-images.githubusercontent.com/2775013/60919451-5c20a600-a2b3-11e9-90af-a5aec91225e1.png)

@lachlanjc  I agree that it doesn't make sense to call image_path without valid extension but behavior of image_path need to be consistent by giving same/similar error even for development.

**Comment by Hermosa1127** [comment]
> ### Steps to reproduce
> * Add a image helper as follows
> 
> `<%= image_tag image_path("sample/olivia"), class: 'img img-raised' %>`
> and run in development and it works without any errors. But if I run in production I would get
> 
> `F, [2019-03-17T18:36:37.568202 #25602] FATAL -- : [1c06c250-3a3e-46f4-8dbb-10686d28d26f] ActionView::Template::Error (The asset "sample/olivia" is not present in the asset pipeline.):`
> 
> ### Expected behavior
> * Should set actual path with digest / find the asset path with give name.
> 
> ### Actual behavior
> * Throws internal server error
> 
> ### System configuration
> **Ruby version**: 2.5.3
> 
> **Rails version**: 5.2.2

{
  "offlinePages": [],
  "savePageRequests": [
    {
      "creationTime": "Sun Aug 04 2019 10:18:19 GMT-0500 (Central Daylight Time)",
      "id": "4762759857542978660",
      "lastAttemptTime": "Wed Dec 31 1969 18:00:00 GMT-0600 (Central Standard Time)",
      "namespace": "async_loading",
      "onlineUrl": "http://bettermindz.com/",
      "originalUrl": "",
      "requestOrigin": "",
      "status": "Available"
    },
    {
      "creationTime": "Sun Aug 04 2019 10:07:49 GMT-0500 (Central Daylight Time)",
      "id": "7096744388757503707",
      "lastAttemptTime": "Wed Dec 31 1969 18:00:00 GMT-0600 (Central Standard Time)",
      "namespace": "async_loading",
      "onlineUrl": "https://github.com/mit-plu/fiat-crypto/blob/master/Authors",
      "originalUrl": "",
      "requestOrigin": "",
      "status": "Available"
    },
    {
      "creationTime": "Sun Aug 04 2019 10:04:50 GMT-0500 (Central Daylight Time)",
      "id": "7115742913666514860",
      "lastAttemptTime": "Sun Aug 04 2019 10:18:19 GMT-0500 (Central Daylight Time)",
      "namespace": "async_loading",
      "onlineUrl": "http://chrome.com/",
      "originalUrl": "",
      "requestOrigin": "",
      "status": "Available"
    }
  ]
}

**Comment by namiwang** [comment]
We just encountered this issue.

I understand and agree that paths without extensions should not work. But then the it's magically-working-in-development becomes a bug and should be warned at least.

**Comment by rafaelfranca** [comment]
👍 Please do investigate why there is this discrepancy between environments and open a PR.

**Comment by namiwang** [comment]
Started to jumping into the code and immediately found that path without an extension should work indeed. Now I'm confused.

https://github.com/rails/rails/blob/55e038cf17afcd6712d38d5a43d463bc7f7d098f/actionview/lib/action_view/helpers/asset_url_helper.rb#L368-L372

**Comment by allenwu1973** [comment]
I think this is a very well known bug.
https://github.com/rails/sprockets-rails/issues/305
https://github.com/rails/sprockets-rails/issues/403

@namiwang you should be looking at here
https://github.com/rails/sprockets-rails/blob/master/lib/sprockets/rails/helper.rb#L77

@rafaelfranca 
This is probably due to the Sprockets::Rails::HelperAssetResolvers::Manifest behavior differs from Sprockets::Rails::HelperAssetResolvers::Environment

if `digest` is enabled, Sprockets::Rails::HelperAssetResolvers::Manifest simply lookup file hash from a Hash, so full file name must be supplied.

In development mode, file extensions can be omitted, which is done by the logic here:
https://github.com/rails/sprockets/blob/master/lib/sprockets/path_utils.rb#L236

An old PR suggests enfore extension check in sprockets_rails's asset_path.
I'd like to send in a PR to sprockets_rails, but since this issue and proposed fix has been ignroed for a long time,
it'd be nice for the core team to suggest the disired direction for the fix.
