### ISSUE TITLE
PostgreSQL adapter: breaking change in boolean parameter parsing in 5.2.1

### ISSUE THREAD

**Issue by Drenmi** [rails/rails#35676]
Between 5.2.0 and 5.2.1, boolean parameter parsing in queries saw a breaking change. Consider the following:

```ruby
Post.where(published: :false)
```

In 5.2.0, this creates the following query:

```sql
SELECT "posts".* FROM "posts" WHERE "posts"."published" = 'false'
```

In 5.2.1, the query is instead:

```sql
SELECT "posts".* FROM "posts" WHERE "posts"."published" = TRUE
```

the result of which is the opposite of the former. (Postgres interprets `"false"` as `FALSE`.)

While I think that having any truthy value parse to `TRUE` is a sensible default, it is a breaking change that could have potentially disastrous consequences.

### Steps to reproduce

```ruby
ActiveRecord::Schema.define do
  create_table :posts, force: true do |t|
    t.boolean :published
  end
end

class Post < ActiveRecord::Base
end

class BugTest < Minitest::Test
  def test_boolean_querying
    Post.create!(published: true)

    assert_equal Post.where(published: false).count, Post.where(published: :false).count
  end
end
```

### Expected behavior

Query results are consistent between patch (and minor) versions.

### Actual behavior

Query results change between patch (and minor) versions.

### System configuration
**Rails version**:

5.2.1

**Ruby version**:

2.6.2

**Comment by y-yagi** [comment]
I tried but not reproduce. 

```ruby 
# frozen_string_literal: true

require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"
  gem "activerecord", "5.2.1"
  gem "pg"
end

require "active_record"
require "minitest/autorun"
require "logger"

ActiveRecord::Base.establish_connection(adapter: "postgresql", database: "activerecord_unittest")
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :posts, force: true do |t|
    t.boolean :published, default: false
  end
end

class Post < ActiveRecord::Base
end

class BugTest < Minitest::Test
  def test_boolean_querying
    Post.create!(published: true)
    assert_equal Post.where(published: false).count, Post.where(published: "false").count
    pp Post.where(published: "false").to_sql
  end
end 
```

```bash 
$ ruby 35676.rb
Fetching gem metadata from https://rubygems.org/...............
Resolving dependencies...
Using concurrent-ruby 1.1.5
Using i18n 1.6.0
Using minitest 5.11.3
Using thread_safe 0.3.6
Using tzinfo 1.2.5
Using activesupport 5.2.1
Using activemodel 5.2.1
Using arel 9.0.0
Using activerecord 5.2.1
Using bundler 2.0.1
Using pg 1.1.4
-- create_table(:posts, {:force=>true})
D, [2019-03-21T08:00:27.844087 #14750] DEBUG -- :    (16.0ms)  DROP TABLE IF EXISTS "posts"
D, [2019-03-21T08:00:27.889423 #14750] DEBUG -- :    (44.2ms)  CREATE TABLE "posts" ("id" bigserial primary key, "published" boolean DEFAULT FALSE)
   -> 0.0735s
D, [2019-03-21T08:00:27.924893 #14750] DEBUG -- :   ActiveRecord::InternalMetadata Load (0.3ms)  SELECT  "ar_internal_metadata".* FROM "ar_internal_metadata" WHERE "ar_internal_metadata"."key" = $1 LIMIT $2  [["key", "environment"], ["LIMIT", 1]]
D, [2019-03-21T08:00:27.930703 #14750] DEBUG -- :    (0.1ms)  BEGIN
D, [2019-03-21T08:00:27.931462 #14750] DEBUG -- :    (0.1ms)  COMMIT
Run options: --seed 4449

# Running:

D, [2019-03-21T08:00:27.946626 #14750] DEBUG -- :    (0.1ms)  BEGIN
D, [2019-03-21T08:00:27.947741 #14750] DEBUG -- :   Post Create (0.6ms)  INSERT INTO "posts" ("published") VALUES ($1) RETURNING "id"  [["published", true]]
D, [2019-03-21T08:00:27.971139 #14750] DEBUG -- :    (23.0ms)  COMMIT
D, [2019-03-21T08:00:27.973159 #14750] DEBUG -- :    (1.1ms)  SELECT COUNT(*) FROM "posts" WHERE "posts"."published" = $1  [["published", false]]
D, [2019-03-21T08:00:27.973827 #14750] DEBUG -- :    (0.3ms)  SELECT COUNT(*) FROM "posts" WHERE "posts"."published" = $1  [["published", false]]
"SELECT \"posts\".* FROM \"posts\" WHERE \"posts\".\"published\" = FALSE"
.

Finished in 0.046576s, 21.4703 runs/s, 21.4703 assertions/s.

1 runs, 1 assertions, 0 failures, 0 errors, 0 skips 
```

Can you create a reproduce script with this [template](https://github.com/rails/rails/blob/master/guides/bug_report_templates/active_record_gem.rb)? And, what is the version of pg gem and PostgreSQL?

**Comment by Drenmi** [comment]
Sorry @y-yagi. The regression seems to be when you pass a symbol, `:false`. I have updated the issue. 🙇

**Comment by y-yagi** [comment]
Thanks for your update. I confirmed. 

This is the effect of 4858cd1e6d994820ebd4505871a859745adfd79d. This is to handle boolean attribute correctly when querying. 
We do not treat `:false` as a `false` value. Only `[false, 0, "0", "f", "F", "false", "FALSE", "off", "OFF"]` is considered as `false`, the others are `true`.
https://edgeapi.rubyonrails.org/classes/ActiveModel/Type/Boolean.html 

I totally agree that breaking changes should be avoided. But this is buggy. 
However, I think that this was originally unintended behavior, and it became correct behavior by this.

**Comment by rafaelfranca** [comment]
Is there any reason why `:false` is not `false`?

@kamipo what do you think?

**Comment by kamipo** [comment]
Symbol `:false` is mostly a developer's mistake (user's input basically comes as a string), so seems fine that `:false` would be included in `FALSE_VALUES` in future version of Rails.

BTW we had enabled `Lint/BooleanSymbol` cop to detect that developer's mistake in our apps.

https://rubocop.readthedocs.io/en/latest/cops_lint/#lintbooleansymbol

**Comment by kamipo** [comment]
As another approach to fix this issue, ensure `to_s` before cast value if a value is a Symbol.

```diff
diff --git a/activemodel/lib/active_model/type/boolean.rb b/activemodel/lib/active_model/type/boolean.rb
index f6c6efbc87..722785a891 100644
--- a/activemodel/lib/active_model/type/boolean.rb
+++ b/activemodel/lib/active_model/type/boolean.rb
@@ -27,6 +27,8 @@ def serialize(value) # :nodoc:
       private
 
         def cast_value(value)
+          value = value.to_s if value.is_a?(Symbol)
+
           if value == ""
             nil
           else
```

**Comment by rafaelfranca** [comment]
good point about the cop. I think we should add to `FALSE_VALUES`, but checking if the object is a symbol on every cast call seems too much to me.

**Comment by Drenmi** [comment]
Just to chime in, I am almost certain this was a mistake on the original author's end. Somehow it went unnoticed in our codebase until I upgraded Rails. It's not ideal to have to support `:false`, but in the interest of not breaking existing Rails applications, it might be a necessary evil. At least until the next major version. 🙂

**Comment by rafaelfranca** [comment]
I'm fine with allowing `:false`.
