### ISSUE TITLE
[actioncable] compatibility with React Native

### ISSUE THREAD

**Issue by localhostdotdev** [rails/rails#35674]
### Steps to reproduce

- Have a rails app and a react-native app
- Use the actioncable npm package in the react-native app (and setup action cable in the rails app)
- `can't find variable 'self'`

### Expected behavior

Works.

### Actual behavior

Errors on the use of `self` (e.g. self.console, self.WebSocket)

### System configuration

**Rails version**: 6.0.0beta
**Ruby version**: 2.7.0dev

Source: https://www.reddit.com/r/rails/comments/b31g2b/actioncable_with_react_native_app/

Full disclosure: Didn't reproduce it, I wanted to share the issue of an user on Reddit.

**Comment by NRauh** [comment]
I don't know if this is any help, but using `6.0.0-rc1` I was able to keep react native from blowing up about `self` or `document` being undefined as long as I created the consumer passing in a websocket url `ActionCable.createConsumer('ws://localhost:3000/cable')`.

However, I immediately disconnects because the client wasn't getting a subprotocol back (which I think is an issue with react native).

**Comment by rafaelfranca** [comment]
Thank you so much for the issue but we don't take feature request on the issue tracker. We recommend you to try to implement the feature and send us a pull request or if you are in doubt if the feature will be accepts ask in Rails Core mailing list for feedback.

**Comment by Rudiney** [comment]
Hey folks, just want to drop here that i found fairy simple to have this working today with React Native and Expo by working around 2 main problems:

1. [The wierd fix for IE](https://github.com/rails/rails/blob/v6.0.3.2/actioncable/app/javascript/action_cable/consumer.js#L65) using document to create an A element to replace the socket url from `http` to `ws`
2. [Global usage of browser's event system](https://github.com/rails/rails/blob/v6.0.3.2/actioncable/app/javascript/action_cable/connection_monitor.js#L24)

**Here is how i managed to use @rails/actioncable js package(v6.0.3-2) in a React Native(v16.9) project with Expo(SDK v37) to connect to a Rails 6 backend:**

1. Make sure you create the consumer sending an URL that already starts with `ws` or `wss`. (To bypass the wierd IE fix)
2. Add a global replay for `addEventListener` and `removeEventListener`. I used [react-native-event-listeners](https://github.com/meinto/react-native-event-listeners)

**Show me tha code:**

```js
import { createConsumer } from "@rails/actioncable";
import { EventRegister } from "react-native-event-listeners";

global.addEventListener = EventRegister.addEventListener;
global.removeEventListener = EventRegister.removeEventListener;

class WsNotificationsHandler extends React.Component {
  componentDidMount() {
    this._connect();
  }

  componentWillUnmount() {
    this._disconnect();
  }

  _connect() {
    const cable = createConsumer(`wss://YOURRAILSURL.com/cable?token=${access_token}`);
    this.channel = cable.subscriptions.create("NotificationsChannel", {
      received: this._gotNotification,
      //... 
    });
  }

  _gotNotification = (payload) => {
    console.log("BOOM! Notification:", payload)
  };

  _disconnect() {
    this.channel?.unsubscribe?.();
  }

  render() {
    return null
  }
}
```

here are the versions at my package.json:
```json
"@rails/actioncable": "^6.0.3-2",
"react-native-event-listeners": "^1.0.7",
"react-native": "https://github.com/expo/react-native/archive/sdk-37.0.1.tar.gz",
"expo": "^37.0.0",
```


As far as i could get, the only side effect with "mocking" the global event system is that we lost @rails/actioncable handling of stale conections for not visible browsers tab. But that shouldnt be a problem.

Hope that helps!
