### ISSUE TITLE
Improve docs for Active Record Query Interface

### ISSUE THREAD

**Issue by marko-avlijas** [rails/rails#35681]
Please put `rails generate model` commands needed to create the models from the guide so that we can follow along and try it out in the console. 

I am very confused how to create the Order class for example, what fields should it contain and  especially the price field and how it's summed up. Is the class maybe misnamed and should be named OrderLine or OrderItem?

Honestly I just spent 15 minutes on trying to figure out what fields to put in Order class and it doesn't help that word `order` is found 155 times on that page. Before that I had to scan the docs for all usage of Client class so that I can create that model too. And there are 2 more classes used in examples.

https://guides.rubyonrails.org/active_record_querying.html

**Comment by simi** [comment]
Good idea, would you like to contribute this? You can find sources for that guide at https://github.com/rails/rails/blob/master/guides/source/active_record_querying.md.

**Comment by localhostdotdev** [comment]
Seems like `Order` has (I searched for `Order.` and `orders`): updated_at/created_at (default timestamps), price, reference to `Client` (e.g. `client_id`), status (string).

So something like `rails generate model Order price:integer client:references status`.

**Comment by marko-avlijas** [comment]
Thanks @localhostdotdev

@simi  - Yes I can create a commit, will do it tomorrow.

**Comment by danielricecodes** [comment]
@marko-avlijas - I've been programming Ruby and Rails for 10 years and I'm still learning new things.  You'll get the hang of it, but not after only 15 minutes.  Sorry the guides are confusing to you, but they are meant to show examples of how the Query Interface works, not be used as step by step training guides AFAIK.  There are plenty of supplemental guides available for Rails too, like [The Rails 5 Way](https://www.amazon.com/Rails-Way-Addison-Wesley-Professional-Ruby/dp/0134657675) if you prefer book learning, and even [interactive training for Zombies](https://www.pluralsight.com/courses/code-school-rails-for-zombies).

There are LOTS of Rails resources out there other than Rails' own documentation.  I suggest you try them out!
