### ISSUE TITLE
Class definitions inherit from ActiveRecord::Core by default?

### ISSUE THREAD

**Issue by dennym** [rails/rails#35684]
I am in a gem that is in some part does not require rails. I have a spec that checks if the a class is `present?` after running some method. Turns out the class method `present?` comes from rails. So I just required `active_record` on top and the class definition responds to `.present?`.

### Steps to reproduce
```
# test_wo.rb
class FooBar
end
FooBar.present? #=> undefined method present? for FooBar::Class

#test_w.rb
require 'active_record'
class FooBar
end
FooBar.present? #=> true
```

Why does FooBar::Class respond to `.present?` although it does not inherit from ActiveRecord::Cor? 

### System configuration
**Rails v**: 5.2.2

**Ruby v**: 2.6.x

**Comment by fxn** [comment]
All Rails components load [this file](https://github.com/rails/rails/blob/master/activesupport/lib/active_support/rails.rb) with some AS stuff that they are going to use one way or another.

The class responds to `present?` because the predicate is defined in [`Object`](https://github.com/rails/rails/blob/master/activesupport/lib/active_support/core_ext/object/blank.rb) in particular.

**Comment by alexcameron89** [comment]
Here's a reproducible script related to @fxn's response that shows you where you can find `#present?`'s source location:
```ruby
gemfile(true) do
  source "https://rubygems.org"

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  gem "activerecord", github: "rails/rails"
end

require "active_record"
require "minitest/autorun"
require "logger"

class Post
end

class IntrospectionTest < Minitest::Test
  def test_present_source_location
    method = Post.method(:present?)
    assert_equal Object, method.owner
    assert method.source_location[0].include? "activesupport/lib/active_support/core_ext/object/blank.rb"
  end
end
```

**Comment by dennym** [comment]
@fxn You linked method is the instance method, isn't it? The class method is over [here](https://github.com/rails/rails/blob/c82705b15faaf12d568272e86afb6ad2c151007f/activerecord/lib/active_record/core.rb) 

I came to the conclusion about  requiring `active_record` because `require 'active_support'` didn't work.

```
# test_w.rb
require 'active_support'
class FooBar
end
FooBar.present? #=> undefined method present? for FooBar::Class
```
This should work then right? Because I remember using it this way back in 4.xx times

**Comment by fxn** [comment]
@dennym `FooBar` evaluates to an object, an object of the class `Class`. That object responds to anything in `Object`, let me break it down for you:

```ruby
obj = FooBar
obj.display
```

**Comment by dennym** [comment]
@fxn ah thanks that makes sense.

```
require 'active_support'
class FooBar
end
FooBar.present?
```
 Should work then since [this](https://github.com/rails/rails/blob/master/activesupport/lib/active_support/rails.rb) is required then too, right?

**Comment by fxn** [comment]
Ah, Active Support is different, that gem does not load that file by default.

**Comment by dennym** [comment]
Ahh just read the comment in the linked file :)

> # This file is loaded by every Rails component except Active Support itself,
> # but it does not belong to the Rails public interface. It is internal to
> # Rails and can change anytime.

Thanks for the input and clarification.
