### ISSUE TITLE
rails credentials:edit fails if credentials file has trailing newline

### ISSUE THREAD

**Issue by kieraneglin** [rails/rails#35693]
### Steps to reproduce

1. Create a new Rails project (tested on 5.2.2.1)
2. Use `rails credentials:edit` and add valid YAML to your credentials file
3. Save encrypted credentials
3. Add a blank line at the end of `credentials.yml.enc`

### Expected behavior
I can start my Rails application, edit credentials again, etc.

### Actual behavior
Rails panics with `ActiveSupport::MessageEncryptor::InvalidMessage`

### Notes
Many code editors automatically append a newline at the end of a file.  In this case, simply viewing the `credentials.yml.enc` file may result in your Rails application no longer starting.  In many cases, it can be irritating to remove this trailing newline and it's often unclear as to why the error is occurring.
 
However, the only thing stopping me from making a PR is the thought that this may be intentional.  One may not want to introduce any leniency when it comes to message encryption, so being very rigid about the format of these encrypted credentials may be a benefit.

If this is indeed a bug, I can create a PR that strips leading and trailing whitespace from the credentials file before reading.  If it's intentional, I'll leave it be.

### System configuration
**Rails version**: 5.2.2.1

**Ruby version**: 2.4.2

**Comment by localhostdotdev** [comment]
:+1: Sounds annoying. This is what the patch could look like: (this would apply to all encrypted files, and tests would be needed too)

```diff
diff --git a/activesupport/lib/active_support/encrypted_file.rb b/activesupport/lib/active_support/encrypted_file.rb
index 2b7db568a5..288b4d8a4f 100644
--- a/activesupport/lib/active_support/encrypted_file.rb
+++ b/activesupport/lib/active_support/encrypted_file.rb
@@ -40,7 +40,7 @@ def key

     def read
       if !key.nil? && content_path.exist?
-        decrypt content_path.binread
+        decrypt content_path.binread.rstrip
       else
         raise MissingContentError, content_path
       end
```

**Comment by y-yagi** [comment]
Basically, the behavior when editing xx directly with an editor is not guaranteed. I think that this is intentional and that no special processing should be done for it. Also, I do not think that adding line breaks is a common behavior.
I'm curious, why you open `credentials.yml.enc` with an editor?

**Comment by localhostdotdev** [comment]
@y-yagi No the author but I've opened even binary files in text editors many times (instead of cat / less / strings / file). For instance here I would be curious if `.yml.enc` is base64 encoded or just a binary and open it quickly to check.

**Comment by kieraneglin** [comment]
@y-yagi I agree with the other commentor's conclusion.  I personally discovered this issue when was trying to resolve a nasty merge conflict between two branches which had each altered our encrypted credentials significantly.  Since this file doesn't play nice with the traditional means of resolving conflicts, I had to do the following:

1. Copy unencrypted credentials from branch A into a tempfile
2. Copy unencrypted credentials from branch B into a tempfile
3. Manually fix the YAML to include all credentials from both branches and save this to `credentials.yml.enc`
4. (here was my mistake) Once I had the new encrypted payload, I tried copying-pasting _that_ in both branches A and B so that they were in parity.  In doing so, my editor added a trailing newline which was difficult to debug.

Even though I went about this in an odd way (copying the encrypted payload vs. copying the unencrypted YAML and saving), I don't think I was completely out to lunch in expecting it to work without a hitch.  Debugging was made doubly hard by the fact that I had edited the contents of `credentials.yml.enc`, so catching the newline was less obvious when running a diff

**Comment by y-yagi** [comment]
Thanks for your detail.  
I think that the root cause of that is that it is hard to understand the contents of the change of credential. It will be improved by #32445.  
Anyway, I think that I should not care about files that were edited in a way that was not originally supposed. Thanks.

**Comment by allisonphillips** [comment]
While I think EncryptedFile should be smart enough to strip the content before trying to decrypt it, you can get around this in vscode by configuring those file extensions to use a specific Language Mode and then disable the setting for that Language Mode:
```javascript
// .vscode/settings.json
{
  "editor.tabSize": 2,
  "editor.indentSize": "tabSize",
  "files.insertFinalNewline": true,
  "files.trimTrailingWhitespace": true,
  "files.trimFinalNewlines": true,
  "files.associations": {
    "*.enc": "shellscript",
    "*.key": "shellscript"
  },
  "[shellscript]": {
    "files.insertFinalNewline": false
  }
}
```

Note: The [settings documentation] leaves something to be desired, but you effectively need to use an identifier recognized as a VScode valid Language Mode (i.e., the feature that VScode uses to determine which syntax highlighting to use for your file. I am using `shellscript` here, which is VScode's identifier for the `Shell Script` Language Mode.

[settings documentation]: https://code.visualstudio.com/docs/getstarted/settings

**Comment by ibrahima** [comment]
I realize this is old, but FWIW I seem to have run into the same issue when using `meld` to resolve merge conflicts with credentials files, even though all I used it for was to select the REMOTE copy of the credentials. It's very annoying when this happens because there's no indication as to what happened.
