### ISSUE TITLE
Need to downgrade Sqlite3, Rails 5.2.2.1 Locks Sqlite at ~> 1.3.6

### ISSUE THREAD

**Issue by natetech333** [rails/rails#35725]
### Expected behavior
Rails should install the correct sqlite3 version for a brand new skeleton app

### Actual behavior
sqlite3 is locked in Gemfile.lock to version (~> 1.3.6)

### System configuration
**Rails version**: 5.2.2.1

**Ruby version**:
ruby 2.6.1p33 (2019-01-30 revision 66950) [x86_64-darwin15]

Error Message

/Users/nathan/.rbenv/versions/2.6.1/lib/ruby/2.6.0/bundler/rubygems_integration.rb:408:in `block (2 levels) in replace_gem': Error loading the 'sqlite3' Active Record adapter. Missing a gem it depends on? can't activate sqlite3 (~> 1.3.6), already activated sqlite3-1.4.0. Make sure all dependencies are added to Gemfile. (LoadError)

Steps
1. rails new myapp --skip-spring
2. gem list | grep sqlite3
sqlite3 (1.4.0)
3. grep -r "sqlite3" Gemfile.lock

nathans-MacBook:myapp nathan$ grep -r "sqlite3" Gemfile.lock
Gemfile.lock:    sqlite3 (1.4.0)
Gemfile.lock:  sqlite3

2. rails g scaffold Message content:string

/Users/nathan/.rbenv/versions/2.6.1/lib/ruby/2.6.0/bundler/rubygems_integration.rb:408:in `block (2 levels) in replace_gem': Error loading the 'sqlite3' Active Record adapter. Missing a gem it depends on? can't activate sqlite3 (~> 1.3.6), already activated sqlite3-1.4.0. Make sure all dependencies are added to Gemfile. (LoadError)

activesupport-5.2.2.1 is throwing the depedency error

Workaround:
1. uninstall sqlite3
2. remove Gemfile.lock
3. change the Gemfile to:
gem 'sqlite3', '~> 1.3.6'
4. bundle install
5. rails g scaffold Message content:string

**Comment by gudetimes1234** [comment]
Following the repro steps I'm seeing this same error after running `rails g scaffold Message content:string`

**Rails** 5.2.2.1
**Ruby** 2.6.0preview2 (2018-05-31 trunk 63539) [x86_64-darwin18]

**Comment by gudetimes1234** [comment]
I'd like to try to create a PR for this if we want a patch

**Comment by y-yagi** [comment]
This already fixed with 5.2.3.rc1. Please see #35153 for more details. Thanks.
