### ISSUE TITLE
Remove X-Download-Options header

### ISSUE THREAD

**Issue by Medvezo** [rails/rails#35728]
`X-Download-Options` prevents auto-opening files for IE8. Rails hvave already started to remove features for IE8 (see https://github.com/rails/rails/pull/32125 or https://github.com/rails/rails/pull/32104), so there is hardly any reasons to send this header.

**Rails version**:
6.0.0

**Comment by sikachu** [comment]
Nice find. Would you like to submit a PR to implement this?

**Comment by ashish91** [comment]
@sikachu Created https://github.com/rails/rails/pull/35730 for this. Please let me know if any other changes are required in it. Thanks.

**Comment by rafaelfranca** [comment]
I'm confused about this issue. @Medvezo do you want to remove that because you want  auto-opening files in IE8 or because you think we should remove support to IE8?

**Comment by Medvezo** [comment]
hello @rafaelfranca

I simply get the impression that Rails (and world at large) is moving away from IE8 support, so there is no need to transmit this header anymore

You have accepted the PR (#32125) that sets `Rails.application.config.action_controller.default_enforce_utf8` to `false` by default in Rails 6, which kind of signals that you want to move away from older IE versions, v8 being one of them

**Comment by rafaelfranca** [comment]
Yeah, that is the goal, but this one as it is security related I'd be more careful to remove. Sending that header for a few years will not hurt anyone.

**Comment by ashish91** [comment]
I agree with @rafaelfranca, this option was introduced for [IE8](https://blogs.msdn.microsoft.com/ie/2008/07/02/ie8-security-part-v-comprehensive-protection) and it's available in IE8+.
Maybe they've fixed the underlying issue in IE8+ so that any HTML file is not executed in the context of the website. However I couldn't find any article from MS that supports that statement. 
If the underlying issue is fixed then it makes sense to remove this option. Otherwise it's better to leave it be.

**Comment by Medvezo** [comment]
@rafaelfranca sounds reasonable

 @ashish91 i found two things related to this: 
1) https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/18488178/
2) https://github.com/Fyrd/caniuse/issues/3388

should i close the issue??

**Comment by rafaelfranca** [comment]
Right now, I'm sure which is the earliest IE version that Rails supports. Maybe IE8. It is being a while since I looked on this. @javan do you know?

**Comment by Medvezo** [comment]
Closing it for now.

**Comment by javan** [comment]
> Right now, I'm sure which is the earliest IE version that Rails supports.

@rafaelfranca, AFAIK the JavaScript in Rails only supports IE11+
