### ISSUE TITLE
Replace chromedriver-helper with webdrivers

### ISSUE THREAD

**Issue by xdmx** [rails/rails#35731]
Chromedriver-helper is currently a gem added by default, and it will be [deprecated](https://github.com/flavorjones/chromedriver-helper/issues/83) at the end of March.

It should be replaced by [webdrivers](https://github.com/titusfortner/webdrivers) instead

**Comment by bronxi47** [comment]
In the Gemfile and then run "bundle install" again? or what's the best way? Thanks!

**Comment by flavorjones** [comment]
@bronxi47 Yes, you should be able to simply update the gem dependency from `chromedriver-helper` to `webdrivers` and things should Just Work™.

**Comment by bronxi47** [comment]
I made that and it worked very well, thanks!
