### ISSUE TITLE
Dependent restrict options ignore pending destruction of associated records

### ISSUE THREAD

**Issue by Aesthetikx** [rails/rails#35759]
This scenario is somewhat contrived, but I didn't want to stray far from the issue template. In the case I am looking at the odd placement of foreign keys and associations seems more reasonable, but the structure is the same.

Imagine `Post has_many :comments`.

Additionally, each post has a computed `top_comment`, which in a background job has been determined to be the most interesting comment. To cache this result, `Post belongs_to :top_comment` (it has the key), which is a reference to one of its comments.

To prevent nil errors when displaying the post's `top_comment`, we have specified `dependent: :restrict_with_exception` to prevent the removal of the top comment.

Now, this all works in practice just fine, until you try to remove the Post. A user would see 'comment cannot be destroyed because dependent top commenting post exists'.

Perhaps this is an edge case that is not worth fixing or an abuse of relations and validations, but since the 'top commenting post' is about to be destroyed, should the restriction still be triggered?

### Steps to reproduce
```
# frozen_string_literal: true

require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  gem "rails", github: "rails/rails"
  gem "sqlite3"
end

require "active_record"
require "minitest/autorun"
require "logger"

# This connection will do for database-independent bug reports.
ActiveRecord::Base.establish_connection(adapter: "sqlite3", database: ":memory:")
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :posts, force: true do |t|
    t.integer :top_comment_id
  end

  create_table :comments, force: true do |t|
    t.integer :post_id
  end
end

class Post < ActiveRecord::Base
  has_many :comments, dependent: :destroy
  belongs_to :top_comment, class_name: 'Comment'
end

class Comment < ActiveRecord::Base
  belongs_to :post
  has_one :top_commenting_post, inverse_of: :top_comment,
                                foreign_key: :top_comment_id,
                                class_name: 'Post',
                                dependent: :restrict_with_exception
end

class BugTest < Minitest::Test
  def test_association_stuff
    post = Post.create!
    comment = post.comments.create!

    # Specify comment as the best comment of it's post
    post.update!(top_comment: comment)

    # Example of bidirectional association
    assert_equal post.top_comment.top_commenting_post, post

    # Cannot delete comment due to dependent option, as expected
    assert_raises(ActiveRecord::DeleteRestrictionError) do
      comment.destroy!
    end

    # However, should be able to destroy post with comments?
    # Raises ActiveRecord::DeleteRestrictionError
    post.destroy!
  end
end
```

### Expected behavior
I think the `Post` and associated `Comment`s should be destroyed, even though comment restricts posts destruction, because they are both getting destroyed.

### Actual behavior
`Post#destroy!` raises `ActiveRecord::DeleteRestrictionError`

### System configuration
**Rails version**: master

**Ruby version**: 2.6.2

**Comment by gmcgibbon** [comment]
I think this is expected behaviour due to the kind of callbacks you are applying to your models. In order to fix it, you might add another callback to `Post` to remove a `top_comment` before destroying (eg. `before_destroy(prepend: true) { update(top_comment: nil) }`). You could also try using `has_many :comments, dependent: :delete_all` on `Post` to sidestep comment callbacks entirely when deleting posts.

Since I don't see a bug here, I'm going to close. Thank you for your report!
