### ISSUE TITLE
Broken documentation for ActiveRecord

### ISSUE THREAD

**Issue by IvanDelsinne** [rails/rails#35757]
The README in `/activerecord/` contains a Learn More link that points to the following link, which is dead.

https://github.com/rails/rails/blob/v5.2.2/activerecord/classes/ActiveRecord/Migration.html

Any activerecord-specific documentation?

**Comment by vipulnsward** [comment]
https://github.com/rails/rails/issues/28608#issuecomment-290277451

**Comment by kamipo** [comment]
https://api.rubyonrails.org/files/activerecord/README_rdoc.html
