### ISSUE TITLE
activestorage 5.2.3 is not published

### ISSUE THREAD

**Issue by yskkin** [rails/rails#35777]
### Steps to reproduce
`bundle update rails`

### Expected behavior
exit without error

### Actual behavior

```
Bundler could not find compatible versions for gem "activestorage":
  In Gemfile:
    rails (~> 5.2.3) was resolved to 5.2.3, which depends on
      activestorage (= 5.2.3)

Could not find gem 'activestorage (= 5.2.3)', which is required by gem 'rails (~> 5.2.3)', in any of the sources.
```

At the time of submitting this, 5.2.3 is not listed in https://rubygems.org/gems/activestorage

I'm not sure whether release process is completed or not.
Please just close this if publishing is in progress

**Comment by sikachu** [comment]
ACK. We're looking into it now.

**Comment by rafaelfranca** [comment]
It is there now. Thank you for reporting
