### ISSUE TITLE
Unexpected behaviour of Rails-UJS data-confirm feature

### ISSUE THREAD

**Issue by vtno** [rails/rails#35779]
### Steps to reproduce

1. Create a form with input that has html5 validation.
2. Use `data-confirm` on the submit button.
3. Input invalid value on the input and click the submit button.

### Expected behavior

The html5 errors should show up on the respective input field after click confirm in the dialog box.

### Actual behavior

The dialog box is shown and when I clicked `confirm` the form is not submitted but the HTML5 validation does not show up (see gif below)

![2019-03-28 at 14 59](https://user-images.githubusercontent.com/2187352/55140229-1e679980-516a-11e9-806c-993a2e9495d0.gif)

Removing `data-confirm` from the submit button does solve the problem. (see gif below)

![2019-03-28 at 14 57](https://user-images.githubusercontent.com/2187352/55140137-f2e4af00-5169-11e9-86f6-828888de26f3.gif)

I think adding another check for input validity before `stopEverything` would solve the issue.

### System configuration
**Rails version**:
5.2.2.1

**Ruby version**:
2.6.0p0

**Browser**:
Chrome version 72.0.3626.121 (Official Build) (64-bit)

**Comment by WoH** [comment]
This seems like it's connected to Chromium (reproduction without UJS below).

I can reproduce the behaviour on 
> Chrome Version 73.0.3683.86 (Official Build) (64-bit)
> Brave Version 0.61.52 Chromium: 73.0.3683.86 (Official Build) (64-bit)

Works on 
> Firefox 66.0.2 (64-bit)

```html
<!DOCTYPE html>
<html lang="en">
<body>
  <form>
    <input type="number" value="0" min="1">
    <button type="submit" id="submit-button">Submit</button>
  </form>


  <script>
    document.addEventListener('DOMContentLoaded', () => {
      let submitButton = document.getElementById('submit-button')

      submitButton.addEventListener('click', () => {
      	// Just display the confirm dialog, that's enough to break validation
        confirm()
      })
    })
  </script>
</body>
</html>
```


You could avoid the issue by displaying the confirm dialog on the form's 'submit' event since it will only be fired after the validation.
Maybe it's worth moving `handleConfirm()` up to the form's submit event?

**Comment by y-yagi** [comment]
@WoH Thanks for your useful information. 
I'm not sure this is expected behavior or not. So I reported to bugs.chromium.org. I will watch that.
https://bugs.chromium.org/p/chromium/issues/detail?id=951697

**Comment by bparanj** [comment]
This bug is related to browser issue. This is not a valid Rails bug.

**Comment by vtno** [comment]
Yep, seems like a chromium issue. Closing this.
