### ISSUE TITLE
Throw error when passing a block to a method that doesn't use the block

### ISSUE THREAD

**Issue by localhostdotdev** [rails/rails#35773]
I'm seeing a lot of beginners and myself sometimes passing blocks to methods that don't accept any.

### Steps to reproduce

- `User.first { |user| puts user }`

### Expected behavior

I would expect an error to be thrown.

### Actual behavior

Block is silently ignored.

### System configuration

**Rails version**: all
**Ruby version**: all

I know this would be a vast change, I'm also thinking a ruby "strict mode" would solve this in the more general case: https://bugs.ruby-lang.org/issues/15732

Could be something as simple as `throw MethodDoesntAcceptBlocks if block_given?` on select methods.

**Comment by rafaelfranca** [comment]
Thank you for the issue but are not to defensively check for this on every method. Ruby is changing this behavior in Ruby 2.7.

**Comment by localhostdotdev** [comment]
Thanks, didn't know about this, it even got linked in the ruby bug: https://bugs.ruby-lang.org/issues/15554
