### ISSUE TITLE
URLs with special characters like * : ~ break routing

### ISSUE THREAD

**Issue by xithan** [rails/rails#35786]
After the upgrade from rails 5.2.2.1 to 5.2.3 routing for urls with non-word characters like `/*foo` doesn't work anymore if the routes are defined in an engine and the engine is mounted to `/`. 
I couldn't find anything related to that in the docs, [changelogs](https://github.com/rails/rails/releases/tag/v5.2.3) and [code diffs](https://github.com/rails/rails/compare/v5.2.2...v5.2.3).

### Steps to reproduce
````ruby
# frozen_string_literal: true

require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  # Activate the gem you are reporting the issue against.
  gem "rails", "5.2.3"
end

require "rack/test"
require "action_controller/railtie"

class Engine < ::Rails::Engine
  # to avoid 'Could not find root path for...':
  def self.find_root(from); from; end
      
  routes.draw do
    get ":mark" => "test#index"
  end
end
  

class TestApp < Rails::Application
  config.root = __dir__
  config.session_store :cookie_store, key: "cookie_store_key"
  secrets.secret_key_base = "secret_key_base"

  config.logger = Logger.new($stdout)
  Rails.logger  = config.logger
end

class TestController < ActionController::Base
  include Rails.application.routes.url_helpers

  def index
    render plain: "Home"
  end
end

require "minitest/autorun"

class BugTest < Minitest::Test
  include Rack::Test::Methods
  
  def test_engine_route   
    TestApp.routes.draw do
      mount Engine => "/engine"
    end 
    
    get "/engine/*foo"
    assert last_response.ok?
  end
  
  def test_app_route
    TestApp.routes.draw do
      get ":mark" => "test#index"
    end
    
    get "/*foo"
    assert last_response.ok?
  end
  
  def test_engine_route_mounted_to_root  # this one fails
    TestApp.routes.draw do
      mount Engine => "/"
    end
    
    get "/*foo"
    assert last_response.ok?
  end

  private
    def app
      Rails.application
    end
end
````
### Expected behavior
GET request for `/*foo` should work

### Actual behavior
error `No route matches [GET] "/*foo"`

### System configuration
**Rails version**: 5.2.3 (works in <= 5.2.2.1)

**Ruby version**: 2.6.1, 2.4.1

**Comment by xithan** [comment]
I figured out that this regex change ([ccc0597](https://github.com/rails/rails/commit/ccc0597bb6079b7d86abeb21ed7fbdeff2f74ae3#diff-67940fe9af75d2f6ec9596b2d13998c7L122) by @tenderlove and @rafaelfranca) is responsible for my issue:
````ruby
def accept(node)
  %r{\A#{visit node}(?:\b|\Z)}  # used to be %r{\A#{visit node}}
end
````

**Comment by xithan** [comment]
I don't know anything about how routing is implemented but I checked the path normaIize methods and it seems to me that "/" is the only path that can end with "/". 
So maybe this is a valid solution:
````ruby
def accept(node)
  route = visit(node)
  route == "/" ? %r{\A\/} : %r{\A#{route}(?:\b|\Z)}
end
````

**Comment by rafaelfranca** [comment]
A conditional to remove the word boundary seems strange. I think we need to understand why the word boundary break that code. Given you already have the test case it should not be hard to understand the cause for that route not be recognized anymore.

**Comment by xithan** [comment]
The word boundary breaks the code because there is no word boundary in this case. The regex has to match the "/" part of "/\*foo" to find the route to the engine. Since "\*" and "/" are both not a word character there is no word boundary between them. 

I understand that that special conditional doesn't look pretty in that general place but since it's a very special case I don't see a better way to handle it. 

There is another case that will also break with the word boundary check for a similar reason: If you mount an engine to a path that ends with a non-word character, for example  "/engine*". Then "/engine\*foo" would be routed to the engine but not "/engine\*/foo". This one could easily be fixed by changing the regex to `(?:\b|/|\Z)`. I don't know why `\b` was chosen. Maybe just checking for slashes with `(?:/|\Z)` is also an option.

Unless somebody has a better approach than my conditional I'm happy to make a pull request.

**Comment by rafaelfranca** [comment]
:+1: go ahead with the PR.
