### ISSUE TITLE
ActiveStorage for Rails with own controller and routes.

### ISSUE THREAD

**Issue by phlegx** [rails/rails#35787]
Hi!

I have a normal Rails app that exposes also an API and I want to have my own routes and controllers for `ActiveStorage`. This don't work out of the box because I cannot override URL helpers like `rails_service_blob`, `rails_direct_uploads`, etc. 

Is there a way to disable `ActiveStorage` routes, so that a developer can provide own controllers? The named `url_helpers` cannot be changed, because they are hardcoded in some `ActiveStorage` .rb files like here: [lib/active_storage/service/disk_service.rb#L112](https://github.com/rails/rails/blob/b75192845a6aa89b35c857e9f3de443ae1a0fbd5/activestorage/lib/active_storage/service/disk_service.rb#L112)

**Generated routes.rb**

```
rails_service_blob GET        /rails/active_storage/blobs/:signed_id/*filename(.:format)                               active_storage/blobs#show
rails_blob_representation GET /rails/active_storage/representations/:signed_blob_id/:variation_key/*filename(.:format) active_storage/representations#show
rails_disk_service GET        /rails/active_storage/disk/:encoded_key/*filename(.:format)                              active_storage/disk#show
update_rails_disk_service PUT /rails/active_storage/disk/:encoded_token(.:format)                                      active_storage/disk#update
rails_direct_uploads POST     /rails/active_storage/direct_uploads(.:format)                                           active_storage/direct_uploads#create
```

**Comment by rafaelfranca** [comment]
Please use StackOverflow for questions/help, where a wider community will be able to help you. We reserve the issues tracker for issues only. If what you want is a feature request, we don't take feature request on the issue tracker. We recommend you to try to implement the feature and send us a pull request or if you are in doubt if the feature will be accepts ask in Rails Core mailing list for feedback.
