### ISSUE TITLE
Link to edgeapi when browsing edgeguides

### ISSUE THREAD

**Issue by Medvezo** [rails/rails#35809]
### Steps to reproduce
When reading https://edgeguides.rubyonrails.org, all links to the Rails API should point to https://edgeapi.rubyonrails.org, not https://api.rubyonrails.org

Here is the sample link: https://edgeguides.rubyonrails.org/form_helpers.html

Pay attention to the link in the first note ("This guide is not intended...")

**Comment by saiqulhaq** [comment]
I am working on this issue
