### ISSUE TITLE
Polymorphic association with custom primary key does not build correctly from v5.2

### ISSUE THREAD

**Issue by LeandroSNunes** [rails/rails#35803]
### Steps to reproduce
When performing Rails update in my application some specs have broken and I have noticed the following behavior; Polymorphic associations do not assign the custom primary key with `model.associations.build`, already with` model.associations.create` works perfectly.

```ruby
begin
  require 'bundler/inline'
rescue LoadError => e
  $stderr.puts 'Bundler version 1.10 or later is required. Please update your Bundler'
  raise e
end

gemfile(true) do
  source "https://rubygems.org"
  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  gem 'activerecord', '5.2.0'
  gem 'sqlite3', '~> 1.3.6'
end

require 'active_record'
require 'minitest/autorun'
require 'logger'

ActiveRecord::Base.establish_connection(adapter: 'sqlite3', database: ':memory:')
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :pictures do |t|
    t.string  :name
    t.references :imageable, polymorphic: true, index: true
    t.timestamps
  end

  create_table :products do |t|
    t.string  :name
    t.integer :code
    t.timestamps
  end
end

class Picture < ActiveRecord::Base
  belongs_to :imageable, polymorphic: true
end

class Product < ActiveRecord::Base
  has_many :pictures, as: :imageable, primary_key: :code, inverse_of: :imageable
end

class BugTest < Minitest::Test
  def test_association_with_build
    product = Product.create! name: 'Product 01', code: 234
    picture = product.pictures.build name: 'My Picture'
    picture.save
    assert product.pictures.present?
    product.reload
    assert product.pictures.present?
  end

  def test_association_with_create
    product = Product.create! name: 'Product 02', code: 567
    product.pictures.create name: 'My Picture'
    assert product.pictures.present?
    product.reload
    assert product.pictures.present?
  end
end
```

### Expected behavior
I hope that the `test_association_with_build` test passes after the reload of the product object is performed and that it has in the` imageable_id` the value of the field that I set in the `primary_key` option  using AR with version >= 5.2

### Actual behavior
I currently use version 5.1.7 and get the expected behavior, as the value of the primary key is used both in the `build` method and in`create`

I used this test above with versions below 5.2 and all the `asserts` have passed.

### System configuration
**Rails version**:
5.2.0

**Ruby version**:
2.5.1

**Comment by nipe0324** [comment]
I don't know why `build` method do not work. But if you add `primary_key = :code` to `Product model`, fix tests code.

```rb
class Product < ActiveRecord::Base
  # Add primary_key
  self.primary_key = :code

  has_many :pictures, as: :imageable, primary_key: :code, inverse_of: :imageable
end
```

**Comment by nipe0324** [comment]
maybe, due to this pr.
https://github.com/rails/rails/commit/a84c76573fa776e377c087930dcbdc3a07eb8603#diff-70a6ae5e7130f11468e33ca4dd010e6fR25

call `target=` method and the primary key value of `Product` (`id`)  is set into foreign key of `Picture` (`imageable_id`) on `replace_keys` method.

**Comment by LeandroSNunes** [comment]
@nipe0324 Thank you for your tips!

In my case I can not change the primary key generically, among all relationships within the model, only one has the custom primary key.

This has_many option would be precisely to be specific in customizing the desired relationship. This worked well before v5.2

**Comment by nipe0324** [comment]
@LeandroSNunes I created a pull request https://github.com/rails/rails/pull/35832.
I'm considering how it fix because I think the solution isn't good. but, are you ok if like below.

```rb
class Picture < ActiveRecord::Base
  # you have to set `inverse_of` option.
  belongs_to :imageable, polymorphic: true, inverse_of: :pictures
end

class Product < ActiveRecord::Base
  has_many :pictures, as: :imageable, primary_key: :code, inverse_of: :imageable
end
```

**Comment by LeandroSNunes** [comment]
Thanks, @nipe0324! This is still blocking my migration.
I also believe that forcing `belongs_to` to add an option would not be a good idea.

**Comment by nipe0324** [comment]
How about this fix?

```rb
class Picture < ActiveRecord::Base
  belongs_to :imageable, polymorphic: true
  belongs_to :product_imageable, foreign_type: 'imageable_type', foreign_key: 'imageable_id', primary_key: :code, polymorphic: true
end

class Product < ActiveRecord::Base
  has_many :pictures, as: :imageable, primary_key: :code, inverse_of: :product_imageable
end
```
