### ISSUE TITLE
ruby-head translated to 2.7.0 in .ruby-version and ruby directive in Gemfile

### ISSUE THREAD

**Issue by localhostdotdev** [rails/rails#35806]
### Steps to reproduce

- `rails new goodname`
- `cd goodname`

### Expected behavior

No warning, no errors, everything works fine.

### Actual behavior

```
Required ruby-2.7.0 is not installed.
```

### System configuration

**Rails version**: Rails 6.0.0.beta3
**Ruby version**: ruby 2.7.0dev (2019-03-18 trunk 67296) [x86_64-darwin17]
**RVM version**: rvm 1.29.7 (latest)

`rvm list`:

```
   jruby-9.2.5.0 [ x86_64 ]
   ruby-2.5.3 [ x86_64 ]
   ruby-2.6.0 [ x86_64 ]
   ruby-2.6.1 [ x86_64 ]
   ruby-2.6.2 [ x86_64 ]
=* ruby-head [ x86_64 ]
```

`.ruby-version`:

```
ruby-2.7.0
```

`Gemfile`:

```
...
ruby '2.7.0'
...
```

Maybe it's a bundler issue, not sure.

Considering 2.7.0 is not released. Also that `ruby-head` could be any ruby version, but at least it would work.

Could also be considered a RVM issue because it could pick up `ruby-head` by detecting it's `2.7.0dev` but debatable.

**Comment by prathamesh-sonpatki** [comment]
@localhostdotdev Can you see if this issue happens on master as well? Because https://github.com/rails/rails/commit/1aace5e2cc7784799c2b91fb3feb2bd285c0e628 should have fixed it on master branch.

**Comment by localhostdotdev** [comment]
@prathamesh-sonpatki `rvm_ruby_string` is not defined in my ENV (that commit is from a year ago)

```
>> ENV["rvm_ruby_string"]
=> nil
>> RUBY_ENGINE
=> "ruby"
>> RUBY_ENGINE_VERSION
=> "2.7.0"
```

**Comment by prathamesh-sonpatki** [comment]
@localhostdotdev Yup, it is set by `rvm capistrano` plugin if it is used in your app. I feel this issue is related to RVM and we can't do much. 

Please see https://github.com/rails/rails/issues/34549 https://github.com/rvm/rvm/issues/4541
