### ISSUE TITLE
Activestorage/rails 6.0.0.beta3 : Multiple file upload on updating a record purge existing attachments

### ISSUE THREAD

**Issue by mairea** [rails/rails#35817]
Hi everyone, 

Here is a problem that I noticed while playing around with Rails 6.0.0.beta3 and Activestorage. 
I'm not sure if this is a bug or the normal behiavor since it works perfectly on Rails 5.2.2
Please see the explaination below.  

### Steps to reproduce

Start by a regular install of Rails with : 

```console
rails new my_app
cd my_app
bundle install
rails active_storage:install
rails g scaffold User name:string
rails db:migrate
rails s
```
`Then add active_storage fields to models/user.rb : `

```ruby
class User < ApplicationRecord
	has_one_attached :avatar
	has_many_attached :images
end
```

`then edit the views/users/_form.html.erb to handle upload`
```ruby
  <div class="field">
    <%= form.label :images %>
    <%= form.file_field :images, multiple: true %>
  </div>
```

then create a user with images and edit that user to add more images. This is where the issue
happens

Also, on create I have this error 
```console
Error performing ActiveStorage::AnalyzeJob
```

### Expected behavior

When I upload new images to an existing user, I expect that existing attachments remain and new images to be uploaded  

### Actual behavior

When I upload multiple images to an existing user (update), existing attachments are purged and replaced by the last uploaed images.

When I upload a single imagest to an existing user, everything works fine. Images are added properly and not purged on update.

### Workaround

I got it to work with thoses  changes : 

`model/user.rb`

```ruby
class User < ApplicationRecord
	has_one_attached :avatar
	has_many_attached :images

	attr_accessor :my_images
end
```

`controllers/users_controller.rb`

```ruby
  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)

        @user.images.attach(params[:user][:my_images])


        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end
```
`views/users/_form.html.erb`

```ruby
<div class="field">
    <%= form.label :my_images %>
    <%= form.file_field :my_images, multiple: true %>
  </div>
```
with thoses changes, Upload with multiples files works fine.

### System configuration
**Rails version**: Rails 6.0.0.beta3
**Ruby version**: ruby 2.6.2p47 (2019-03-13 revision 67232) [x86_64-linux]

**Comment by georgeclaghorn** [comment]
This is the expected behavior, though it has changed from Rails 5.2. I’m leaving this open because we need to document the behavior change in the 6.0 release notes.

**Comment by prathamesh-sonpatki** [comment]
@mairea Do you want to send a PR to update the release notes?

**Comment by mairea** [comment]
> @mairea Do you want to send a PR to update the release notes?
I don't have any PR to send. :/

**Comment by jrnk** [comment]
If this is expected behaviour, what should be the recommended way to keep old attachments around when adding new attachments with `multiple: true` ? Add the current attachments in hidden_fields in the form?

**Comment by kaspth** [comment]
@prathamesh-sonpatki do you want to send a PR for this?

**Comment by prathamesh-sonpatki** [comment]
Sure I will take a look and send

**Comment by prathamesh-sonpatki** [comment]
Update: I was able to replicate this issue locally on Rails 5.2 and 6.0.0.beta3 apps

**Comment by georgeclaghorn** [comment]
What’s the issue besides the missing documentation?

**Comment by kaspth** [comment]
@georgeclaghorn I don't know, I've just been going by your first comment in this thread: https://github.com/rails/rails/issues/35817#issuecomment-478690333

But yes, that just mentions documentation. I wasn't sure which behavior change you were referring to.

**Comment by georgeclaghorn** [comment]
The behavior change is that `@user.update!(images: [ ... ])` used to add to images and now it replaces. That’s what needs mentioning in the release notes.

**Comment by tbcooney** [comment]
Glad I found this issue logged sooner rather than later. Not how I remembered it from Rails 5.2 but applying this logic works.

**Comment by limitlessmind** [comment]
So why did this change? This still doesn't answer the question about how it worked in 5 and now in 6 it purges everything and does a replace? How do we get the 5 behavior back? I have sites that use this right now.

**Comment by limitlessmind** [comment]
My apologies if this isn't the right place for this. I'm doing my best to learn more Rails each year. Regarding my last comment. I did some testing and 6.0.0.rc1 caused my images to be deleted and replaced. I went to 6.0.0.rc2 and it worked like it originally did in 5.2.3. FYI.

**Comment by georgeclaghorn** [comment]
Yes, we restored the 5.2 behavior for upgraded apps in RC2. See #36716.

**Comment by anthonymidili** [comment]
This change in default behavior makes NO SENSE for an update action. If I wanted to replace my previously uploaded files on update, I would purge them. What steps do I need to do in order to keep my previously uploaded files???

**Comment by archonic** [comment]
Shipping this change without updating guides was a big pain point for me.

**Comment by swedishpotato** [comment]
Is there any news on when this might be fixed? I just pulled down the latest version of rails 6.0.0 and it still obliterates all the old attachments when adding more - which seems counter-intutive to me I'm afraid. Is the work-around still to have hidden fields in the meantime, or what? I see @georgeclaghorn has kindly made the fix so this no longer happens, but it is not clear to me where this fix is, or how I might implement it in my rails app?

**Comment by dgleba** [comment]
It makes no sense to just make the existing documents disappear. 
I just tried this with rails 6.0.0 and it removes existing attachments.

**Comment by fwolfst** [comment]
> If this is expected behaviour, what should be the recommended way to keep old attachments around when adding new attachments with `multiple: true` ?

We could propose an API in the direction of this: `form.file_field :files, multiple: true, keep: :hidden` that expands to the snippet @jrnk has given

> <% if @product.photos.attached? %>
>   <% @product.photos.each do |ph| %>
>     <%= f.hidden_field :photos, multiple: true, value: ph.signed_id %>
>   <% end %>
> <% end %>

I also find the current behaviour counter-intuitive. An alternative to above proposal could be `form.add_file_field :images, multiple: true` and `form.replace_file_field :images, multiple: true`.

**Comment by goncalvesjoao** [comment]
Glad I found this issue, wish this example was in the docs:

> <% @product.photos.each do |ph| %>
>   <%= f.hidden_field :photos, multiple: true, value: ph.signed_id %>
> <% end %>

Any way, does this works for me but does anyone know how to still keep your new files during an invalid form?

With carrierwave we can, and I just assumed this was a given in active_storage... upon submitting a form that has errors, ```@product.photos``` is populated but not every photo is persisted, how can we still keep this photos without having to ask the user to upload them again?

**Comment by bboennemann** [comment]
Was this fixed? I have a new rails app with active storage 3.0.3 and it still behaves this way. Is there a way to set the configuration to "do not overwrite" manually?

**Comment by limitlessmind** [comment]
This is what I added to application.rb in config folder.

# Need this setting so Active Storage doesn't overwrite files.
    config.active_storage.replace_on_assign_to_many = false

**Comment by pedromschmitt** [comment]
> # Need this setting so Active Storage doesn't overwrite files. config.active_storage.replace_on_assign_to_many = false

It worked for me on Rails 6.0.2.2 and ActiveAdmin Upload of a has_many_attached. Now it does not purge the older attachments when uploading a new one.

**Comment by bboennemann** [comment]
Amazing. This fixed it. It's worth noting that you still need something along these lines:
`model.attachment.attach(params[:attachment_value])
`
Not ideal but we are getting there. This should really be the default behavior 
Thanks guys, I feel much better about this feature now.
