### ISSUE TITLE
Active Storage models ignore table_name_prefix

### ISSUE THREAD

**Issue by gr8bit** [rails/rails#35811]
### Steps to reproduce
1. `rails new astest`
2. `cd astest/`
3. Edit `config/application.rb` and add set a general table prefix with `config.active_record.table_name_prefix = 'abc_'`
4. Create ActiveStorage models `bundle exec rake active_storage:install db:migrate`

Observe: tables are created with prefix (`abc_active_storage_attachements` and `*_blobs`).

5. Create a user model via `bundle exec rails generate model User name:string` and attach an avatar to it
```
class User < ApplicationRecord
  has_one_attached :avatar
end
```
6. Add an Avatar via console
```
2.6.1 :002 > u.avatar.attach(io: File.open(Rails.root.join('public', 'apple-touch-icon.png')))
Traceback (most recent call last):
        1: from (irb):2
ActiveRecord::StatementInvalid (Could not find table 'active_storage_attachments')
```

Observe: ActiveRecord cannot find its table.

### Expected behavior
ActiveStorage::Attachment should use the prefixed table name the migration created previously.

### Actual behavior
ActiveStorage::Attachment cannot find its table as it looks for the non-prefixed table name.

Which is hardcoded in ActiveStorage::Attachment [here](https://github.com/rails/rails/blob/d2542882b20f6205e1c40ab34ff075eefc2d589c/activestorage/app/models/active_storage/attachment.rb#L9) and in ActiveStorage::Blob [here](https://github.com/rails/rails/blob/d2542882b20f6205e1c40ab34ff075eefc2d589c/activestorage/app/models/active_storage/blob.rb#L27)

### System configuration
**Rails version**: 5.2.3
**Ruby version**: 2.6.1

**Comment by prathamesh-sonpatki** [comment]
I tried reproducing this issue but the migration generated for Active Storage tables have correct names.

<details>
cat db/migrate/20190401081542_create_active_storage_tables.active_storage.rb
# This migration comes from active_storage (originally 20170806125915)
class CreateActiveStorageTables < ActiveRecord::Migration[5.2]
  def change
    create_table :active_storage_blobs do |t|
      t.string   :key,        null: false
      t.string   :filename,   null: false
      t.string   :content_type
      t.text     :metadata
      t.bigint   :byte_size,  null: false
      t.string   :checksum,   null: false
      t.datetime :created_at, null: false

      t.index [ :key ], unique: true
    end

    create_table :active_storage_attachments do |t|
      t.string     :name,     null: false
      t.references :record,   null: false, polymorphic: true, index: false
      t.references :blob,     null: false

      t.datetime :created_at, null: false

      t.index [ :record_type, :record_id, :name, :blob_id ], name: "index_active_storage_attachments_uniqueness", unique: true
      t.foreign_key :active_storage_blobs, column: :blob_id
    end
  end
end

</details>

Here is the repro app https://github.com/prathamesh-sonpatki/rails-35811/blob/master/config/application.rb#L19

**Comment by gr8bit** [comment]
Not the migration is the issue, the AS tables ARE created correctly, but they cannot be accessed afterwards (see points 5. and 6. above)

**Comment by prathamesh-sonpatki** [comment]
Thanks, I am working on a fix.

**Comment by brendon** [comment]
Just wondering why `active_storage_variant_records` is missed out on this one? Also `active_storage_variant_records` doesn't even have a `run_load_hooks` so overriding anything is much more hacky.

Would you consider adding both of these things and releasing this in the 6.1 series?

**Comment by zzak** [comment]
It seems like @prathamesh-sonpatki had a PR but was closed and needs to be rebased since the default branch change. Would you be interested in picking this back up? 🙏

**Comment by brendon** [comment]
You're right, I misinterpreted things :D

I'll look at adding that extra load hook first, then think about the other problem. The issue is that the default behaviour when setting the table name is for that to override any prefix or affix settings if I understand rightly? The problem is rails is internally using an external API that then makes it hard to override.

**Comment by brendon** [comment]
Here's the first PR to add the hook: https://github.com/rails/rails/pull/42307

**Comment by brendon** [comment]
In terms of the other problem, I've tried:

```ruby
class ActiveStorage::Record < ActiveRecord::Base #:nodoc:
  self.abstract_class = true

  class << self
    def model_name
      ActiveModel::Name.new(self, nil, name.demodulize)
    end
  end
end

ActiveSupport.run_load_hooks :active_storage_record, ActiveStorage::Record
```

All of the existing tests pass except for two that test URL creation. `polymorphic_url` generation relies on the existence of the namespace to namespace the route:

```
test "attachment" do
  attachment = ActiveStorage::Attachment.new(blob: @blob)
  assert_dom_equal %(<img src="#{polymorphic_url attachment}" />), image_tag(attachment)
end
```

```
test "blob" do
  assert_dom_equal %(<img src="#{polymorphic_url @blob}" />), image_tag(@blob)
end
```

I'm not trying to find out if there's a way to fix route lookup for a model without messing with the `model_name` itself.

**Comment by brendon** [comment]
Actually it's as easy as adding:

```
self.table_name_prefix = 'active_storage_'
```

to the abstract base class and removing the explicit table names from the child classes. My current assumption is that this prefix will also be prefixed by the rails application configuration of the same.

Just need to figure out how to test this.

**Comment by brendon** [comment]
@zzak, this one is getting a bit weird. All the tests pass even after removing the table name declarations, e.g.:

```
self.table_name = "active_storage_blobs"
```

It seems rails already adds `active_storage` because that's the namespace of the model. That'd be fine as it is, but I've now noticed that setting a `table_name_prefix` in `ActiveStorage::Record` doesn't have any effect, but changing it to `table_name_suffix` does work. It's so strange. Makes me feel like it's being overridden from elsewhere.

Even if I put this inside of `ActiveStorage::Blob` itself:

```
self.table_name_prefix = "something_"
```

It still doesn't have any effect. I wonder if the autogenerated module prefix obliterates any other setting? I thought it would append to the prefix.

**Comment by brendon** [comment]
See: https://github.com/brendon/rails/tree/active-storage-table-name for the change plus a failing test.

**Comment by brendon** [comment]
This should be re-opened BTW because the other PR didn't fix this particular issue. @pixeltrix

**Comment by chaadow** [comment]
@brendon I'm glad to inform you that I've solved the mystery of why setting the prefix has no effect, while setting the suffix works. the explanation is here! : https://github.com/rails/rails/pull/50167#discussion_r1405175059
