### ISSUE TITLE
Set samesite property for session cookies

### ISSUE THREAD

**Issue by Medvezo** [rails/rails#35822]
Set `SameSite` attribute for the session cookie in the production environment. This is mainly to protect from some CSRF vulnerabilities. There are two values that could be set for this attribute: `Lax` and `Strict`. I think setting `Lax` is enough, as `Strict` is little too aggressive to begin with.

Older clients that [do not support this property,](https://caniuse.com/#search=samesite) simply ignore it.

Django has this feature starting from their 2.1 release (iirc): https://code.djangoproject.com/ticket/27863

Github also uses this attribute on their session cookie `__Host-user_session_same_site`

Some resources:
* https://tools.ietf.org/html/draft-ietf-httpbis-cookie-same-site-00
* https://www.sjoerdlangkemper.nl/2016/04/14/preventing-csrf-with-samesite-cookie-attribute/
* https://www.owasp.org/index.php/SameSite

EDIT: To clarify, this could already be set manually: `config.session_store :cookie_store, key: '...', same_site: :lax`

I am talking about doing this by default in Rails 6.

**Comment by ignisf** [comment]
@rafaelfranca, sorry for bumping a closed issue, but I'd like to point @Medvezo to the already existing PR for this feature: https://github.com/rails/rails/pull/28297

**Comment by ndvbd** [comment]
Does writing manually:

`config.session_store :cookie_store, key: '...', same_site: :lax`

work in Rails 4.2?

**Comment by mattlaoruckus** [comment]
is this same_site attribute configureable for rails 4 apps?

**Comment by pierre-alain-b** [comment]
In Rails 5.2.x, adding `same_site: :lax ` to the session_store.rb file does work and makes the deprecation warning sent by Firefox vanish.

**Comment by mark100net** [comment]
In Rails '6.0.3.2', setting it in `session_store.rb` had no effect. I had to pass it each time I set an individual cookie to get rid of the warning.

**Comment by abhionlyone** [comment]
> In Rails 6.0.3.2, setting it in `session_store.rb` had no effect. I had to pass it each time I set an individual cookie to get rid of the warning.

Hi @mark100net,  What do you mean by "pass it each time I set an individual cookie"?

**Comment by rebuilt** [comment]
@mark100net I'd also like to know how you did that.

**Comment by mark100net** [comment]
@abhionlyone @rebuilt When I set a cookie I did this:

    cookies[:mycookie] = {:value => 'my_value', :expires => 1.year.from_now, :same_site => :lax}

**Comment by bf4** [comment]
Added to Rails 6.1.0 in https://github.com/rails/rails/commit/7ccaa125ba396d418aad1b217b63653d06044680  there's also a https://github.com/pschinis/rails_same_site_cookie gem (not an endorsement)
