### ISSUE TITLE
Exceptions raised in `parallelize_setup` do not result in `rails test` failing  

### ISSUE THREAD

**Issue by aricwalker** [rails/rails#35835]
While working on an application running `6.0.0.beta3` we noticed that our tests continued to pass even though numerous exceptions were being raised within the `paralleize_setup` block.

### Steps to reproduce

- Create a new rails application using `6.0.0.beta3` - `rails new parallel-tests`
  - (I'm guessing any version w/ parallel testing will work here)
- Create a new test file that implements `parallelize_setup` (See __Example Test__ below)
- Ensure that the block passed to `parallelize_setup` will raise an exception
- `cd` into application directory & run `rails test`

__Example Test:__
```ruby
class TestClass < ActiveSupport::TestCase
  parallelize_setup do |worker|
    raise "Expected to fail `rails test`"
  end

  def test_something
    assert false
  end
end
```

### Expected behavior

Running `rails test` completes but exits with a non-zero exit code, `1`, marking tests as a failure.

### Actual behavior

Running `rails test` completes and exits with an exit code of `0`, marking tests as a success.

```
Finished in 0.222651s, 0.0000 runs/s, 0.0000 assertions/s.
0 runs, 0 assertions, 0 failures, 0 errors, 0 skip

$ echo $?
0
```

### System configuration
**Rails version**: 6.0.0.beta3
**Ruby version**: 2.5.5

**Example application:**: https://github.com/aricwalker/parallel-tests

/cc @eileencodes @tenderlove @jhawthorn

**Comment by eileencodes** [comment]
Working with @aricwalker on this internally.
