### ISSUE TITLE
Where query string syntax requires parens with IN

### ISSUE THREAD

**Issue by LandonSchropp** [rails/rails#35837]
### Steps to reproduce

Create a Rails application with a `Banana` model that uses a UUID as its ID and uses Postgres as its database.

### Expected behavior

This is a contrived example but it applies to a real-world use case in our application.

In the Rails console, I would expect to be able to run this:

```
Banana.where("id IN ?", [ "cc226ac6-fc97-4a73-9a51-35a49078bb33" ])
```

### Actual behavior

When I run this, I get this error:

```
ActiveRecord::StatementInvalid (PG::SyntaxError: ERROR:  syntax error at or near "'cc226ac6-fc97-4a73-9a51-35a49078bb33'")
```

I can fix this by wrapping the `?` in parentheses, but it feels like rails should do this for me when generating the SQL.

### System configuration

**Rails version**: 5.2.2.1
**Ruby version**: 2.6.1

**Comment by rafaelfranca** [comment]
That you for the issue. Rails generate the parentheses if you don't use the SQL literal syntax. If you do, you have to add the parentheses since Rails doesn't parse SQL to know if developers are writing valid SQL or not, and neither it plans to do.

**Comment by LandonSchropp** [comment]
@rafaelfranca Thanks for the reply. Just for my own clarification, are the parentheses part of the serialization of the array into a list in SQL or part of the `IN` expression?

**Comment by rafaelfranca** [comment]
That is a good question. I'd think it is part of the `IN` expression but you could try to see which one it is.
