### ISSUE TITLE
"has_many through" association doesn't behave consistently when using a custom-typed PK column

### ISSUE THREAD

**Issue by lucascaton** [rails/rails#35839]
### Steps to reproduce

```ruby
require 'bundler/inline'

gemfile(true) do
  source 'https://rubygems.org'

  gem 'rails', github: 'rails/rails'
  gem 'sqlite3'
  gem 'uuidtools'
end

require 'active_record'
require 'minitest/autorun'
require 'logger'

ActiveRecord::Base.establish_connection(adapter: 'sqlite3', database: ':memory:')
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table 'tokens', id: :binary, limit: 16, force: true
  create_table 'users', force: true

  create_table 'token_users', force: true do |t|
    t.integer 'user_id'
    t.binary 'token_id', limit: 16, null: false
  end
end

class UuidType < ActiveRecord::Type::Binary
  def serialize(value)
    super(cast_to_uuid(value)&.raw)
  end

  def deserialize(value)
    cast_to_uuid(super(value)).to_s
  end

  def cast_value(value)
    cast_to_uuid(value).to_s
  end

  private

  def cast_to_uuid(value)
    return if value.nil?

    case value.size
    when 16 then UUIDTools::UUID.parse_raw(value) # From `uuidtools` gem
    when 36 then UUIDTools::UUID.parse(value)     # From `uuidtools` gem
    end
  end
end

class User < ActiveRecord::Base
end

class Token < ActiveRecord::Base
  attribute :id, UuidType.new, default: SecureRandom.uuid

  has_many :token_users
  has_many :users, through: :token_users
end

class TokenUser < ActiveRecord::Base
  attribute :token_id, UuidType.new

  belongs_to :user
  belongs_to :token
end

class IssueTest < Minitest::Test
  def test_association_with_uuid
    token = Token.create!
    token.users << User.create!

    assert_equal 1, token.reload.token_users.count
    assert_equal 1, token.reload.users.count
  end
end
```

### Expected behavior

The SQL `where` clause generated for `has_many` is similar to the following and works perfectly:
```sql
WHERE column = x'4e254953bcdb4793a485ac04131565a7'
```

I would expect the one generated for `has_many :through` to be similar...

### Actual behavior

But instead, it generates:
```sql
WHERE column = '4e254953-bcdb-4793-a485-ac04131565a7'
```

The problem is that the second one (`has_many :through`) doesn't include the `x` prefix and also doesn't remove the hyphens (If I manually do that, it solves the issue).

It doesn't return any error, but also **doesn't return any results**.

### System configuration

**Rails version**: `6.0.0.beta3` (master)

**Ruby version**: `2.6.2`

I was able to replicate the issue with both **MySQL** and **SQlite** and both **Rails 5** and **6**.

Thank you.

**Comment by gmcgibbon** [comment]
The attribute type of `token_id` doesn't seem to be used when building the `INNER JOIN` (hence why you see an uncasted string value in the `WHERE`). I'm still trying to identify where the query building goes wrong, but it is definitely a bug.

**Comment by azbshiri** [comment]
I looked through examples in `activerecord` codebase and I think your `ActiveRecord::Type` implementation is wrong otherwise it works fine. 

**Steps to reproduce (works)**

```ruby
require 'bundler/inline'

gemfile(true) do
  source 'https://rubygems.org'

  gem 'rails', github: 'rails/rails'
  gem 'sqlite3'
  gem 'uuidtools'
  gem 'byebug'
end

require 'active_record'
require 'minitest/autorun'
require 'logger'
require 'byebug'

ActiveRecord::Base.establish_connection(adapter: 'sqlite3', database: ':memory:')
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table 'tokens', id: :binary, limit: 16, force: true
  create_table 'users', force: true

  create_table 'token_users', force: true do |t|
    t.integer 'user_id'
    t.binary 'token_id', limit: 16, null: false
  end
end

class UuidType < ActiveRecord::Type::Binary
  def serialize(value)
    cast_to_uuid(value).to_s
  end

  def deserialize(value)
    cast_to_uuid(value).to_s
  end

  def cast_value(value)
    cast_to_uuid(value).to_s
  end

  private

  def cast_to_uuid(value)
    return if value.nil?

    case value.size
    when 16 then UUIDTools::UUID.parse_raw(value) # From `uuidtools` gem
    when 36 then UUIDTools::UUID.parse(value)     # From `uuidtools` gem
    end
  end
end

class User < ActiveRecord::Base
end

class Token < ActiveRecord::Base
  attribute :id, UuidType.new, default: SecureRandom.uuid

  has_many :token_users
  has_many :users, through: :token_users
end

class TokenUser < ActiveRecord::Base
  attribute :token_id, UuidType.new

  belongs_to :user
  belongs_to :token
end

class IssueTest < Minitest::Test
  def test_association_with_uuid
    token = Token.create!
    token.users << User.create!

    assert_equal 1, token.reload.users.count
  end
end
```

@gmcgibbon @lucascaton

**Comment by azbshiri** [comment]
I think your implementation of `ActiveRecord::Type::Value` interface is wrong

```ruby
  def serialize(value)
    cast_to_uuid(value).to_s
  end
```

above change makes the test pass also your query doesn't appear as hex literal `x''` but instead a "<16 bytes of binary data>"

**Comment by gmcgibbon** [comment]
@azbshiri The hex literal is present if you disable prepared statements on the adapter. There is still a type inconsistency on the join. Implementation aside, if you use `:binary` instead of the UUID type it will fail, and I don't think that's expected.

**Comment by gmcgibbon** [comment]
I found the issue after looking at Active Record's predicate builder. You need to specify `has_many :token_users` on your `User` model for type casting to work. When building the WHERE on the join [it reflects on associations here](https://github.com/rails/rails/blob/a8aca0235092c33527aedea6ce8bf82766f8cec1/activerecord/lib/active_record/table_metadata.rb#L48). If there's no association on the other end of the join, we can't ask the join table for type/casting info.

I feel like I've seen this once before in another issue. We should try taking some kind of action to prevent this scenario for other people. 🤔

**Comment by lucascaton** [comment]
Thanks a lot, @gmcgibbon! 🙂
It solved the issue indeed.

**Comment by lucascaton** [comment]
I can confirm the issue still happens.
I was able to replicate it by using the code from the description, against `master` branch:

```sh
Failure:
IssueTest#test_association_with_uuid [issue.rb:76]:
Expected: 1
  Actual: 0

Finished in 0.029758s, 33.6044 runs/s, 67.2088 assertions/s.
1 runs, 2 assertions, 1 failures, 0 errors, 0 skips
```
