### ISSUE TITLE
Shouldn't the webpacker gem be a dependency of Action Text? Or is there a way to use Action Text without webpack?

### ISSUE THREAD

**Issue by arye-dov-eidelman** [rails/rails#35845]
## Shouldn't the webpacker gem be a dependency of Action Text? Or is there a way to use Action Text without webpack?

When upgrading to rails 6 and installing Action Text. If webpack is not installed, (as was the default in Rails 5) all of the yarn packages required by Action Text are not loaded on the form and there is no indication in the logs or documentation that webpack is a requirement for action text.

### Steps to reproduce

1. Upgrade an existing Rails 5.2 application that doesn't have webpacker installed to rails 6.0.0.beta3.

    - Change the Gemfile rails version to `gem 'rails', '~> 6.0.0.beta3'`.
    ```bash
    bundle update rails
    rails app:update
    rails db:migrate
    ```
2. Install Action Text
    ```
    rails action_text:install
    rails db:migrate
    ```

3. Add `has_rich_text :content` to a model.
4. Add `<%= f.rich_text_area :content %>` to a form_with that model.
5. Add `:content` to the permitted strong_params.

### Expected behavior

The action text javascript should load when the form is accessed.
- Either because it was added to the app/assets/javascripts folder and handled by sprockets. In this case, webpacker would not be a dependency.
- or because webpacker is a gem dependency and Running `rails action_text:install` logs "To finish installing action text, install webpack by running `rails webpack:install`."

### Actual behavior
JavaScript files for Action Text are not loaded.
![image](https://user-images.githubusercontent.com/7709411/55511980-f081c980-562f-11e9-8e62-1eba820b2f56.png)
### System configuration
**Rails version**: upgrade from 5.2.2.1 to 6.0.0.beta3

**Ruby version**: 2.5.3

**Comment by arye-dov-eidelman** [comment]
### Another issue:
If you install action text before wepacker it will skip the following 2 steps
```
Adding trix to app/javascript/packs/application.js
      append  app/javascript/packs/application.js
Adding @rails/actiontext to app/javascript/packs/application.js
      append  app/javascript/packs/application.js
```
Which adds the following to app/javascript/packs/application.js
```
require("trix")
require("@rails/actiontext")
```
Running rails action_text:install a second time will add the missing requirments.

Perhaps action_text:install should fail hard if webpacker is not installed with a message that webpacker needs to be installed before you install action text?

**Comment by kaspth** [comment]
Ehhh, I just wanted to get ideas from either @javan or @georgeclaghorn — didn't need the assignment sorry 😄

**Comment by abhaynikam** [comment]
I took a stab at this today and was able to add an alert message if `webpacker` gem was not added in gemfile. I was not able to add webpacker gem via task so added a message for now. 

Can I open a PR for this? I am just working on the writing a good message.

**Comment by kaspth** [comment]
> I took a stab at this today and was able to add an alert message if `webpacker` gem was not added in gemfile. I was not able to add webpacker gem via task so added a message for now.

A message is secondary. Figuring out if Action Text should depend on Webpacker is the first order of business.

You're welcome to try a PR that adds `s.add_dependency "webpacker", ">= 4.0"` just to see it. Not sure if 4.0 is the minimum requirement — we definitely don't want an upper version bound though.

**Comment by javan** [comment]
Webpacker isn't a hard dependency, really. Action Text doesn't use any of its Ruby APIs, and Action Text's JavaScript is compatible with other asset bundlers.

I think a better solution is to warn when `app/javascript/packs/application.js` is missing and suggest either installing Webpacker or adding the two `require()` lines to your JavaScript bundle (that may be bundled by a tool other than Webpacker) manually. That would happen in an `else` condition here: https://github.com/rails/rails/blob/0f39a7488ed736a76cc6cee166fba01d1e3c5686/actiontext/lib/templates/installer.rb#L24-L32

**Comment by kaspth** [comment]
@javan cool, then that's the way we're going! @abhaynikam you're free to have at it with that message 👍

**Comment by abhaynikam** [comment]
Cool. I am on it. Raising PR shortly

**Comment by arye-dov-eidelman** [comment]
Can someone clarify what that wou look like with sprockets.

```
//= require trix
//= require actiontext
```

Or

```
//= require trix
//= require @rails/actiontext
```

**Comment by javan** [comment]
I'm pretty sure it won't work with Sprockets since it doesn't know how to bundle JavaScript modules.

**Comment by arye-dov-eidelman** [comment]
If you'd get this warning and choose to go the webpack route, wouldn't you also need to add the require lines?

**Comment by kaspth** [comment]
@arye-dov-eidelman yes, see #36019 where both those cases are explained. If you find any of the suggestions not clear enough on there, do say so! 😊

**Comment by arye-dov-eidelman** [comment]
Thanks, it looks good better now.👍
