### ISSUE TITLE
Rubocop warning: Bundler/OrderedGems

### ISSUE THREAD

**Issue by Medvezo** [rails/rails#35857]
### Steps to reproduce
Run `rubocop`

### Expected behavior
Ideally, Rubocop shouldn't complain about the `Gemfile`. Reorder gems in `development` group if there isn't a particular reason why `listen` gem should precede the `web-console` gem

### Actual behavior

> Gemfile:38:3: C: Bundler/OrderedGems: Gems should be sorted in an alphabetical order within their section of the Gemfile. Gem listen should appear before web-console.
>   gem 'listen', '>= 3.0.5', '< 3.2'
>   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

### System configuration
**Rails version**: 6.0.0
**Rubocop version**: 0.66

**Comment by kaspth** [comment]
We don't follow Rubocop warnings for Rails apps. You're free to install it and use it though. Thanks!
