### ISSUE TITLE
complaint

### ISSUE THREAD

**Issue by natetech333** [rails/rails#35859]
I have 20+ screenshots of moderators running Slack channels (1000's of members in Rails) who are using Slack as their personal bully pulpit. Last night was the last straw for me. I saw a moderator call a girl a troll after another guy made sexist comments to her. The moderators are acting like bullies. I love Rails. But I am going to drop it like a hot potato if the creators of Ruby and Rails don't come up with some way to establish specific CoC's. Right now, moderators are going around calling people names like trolls, cursing left and right and causing arguments. Then they accuse everyone else of what they started. There needs to be some kind of controls and certifications that is granted as an authorized representative of Rails before anyone can open a group under the copyright. A lot of the Rails groups have chat rooms for politics and unrelated matters. Yet, half the CoC forbids talking about those things. I've seen entire Rails groups where a few friends of the moderators use it as their political pulpit. Then they lure people into discussions and ban them when they don't agree.

This is just 1 example of how a moderator talks to people.

![image](https://user-images.githubusercontent.com/4573756/55576276-ea96f180-56de-11e9-96bf-ee91f6edd312.png)

I have not seen this level of behavior on any other community. Not Python, NYC, Clojure, Java etc... It's only been on Rails/Elixir groups over the past 2 years.

**Comment by rafaelfranca** [comment]
I'm sorry this situation is happening and I feel very sad about those people behavior.

Unfortunately, we don't have control over user created slacks and forums. While Rails, the project, follow a code of conduct in its official channels (GitHub organization, website, blog and the Rails core mailing list), we can't force other groups to do so. @dhh controls the trademark of the name Rails, but I think we can't use it to enforce users groups to not use the name Rails.
