### ISSUE TITLE
routes.rb

### ISSUE THREAD

**Issue by bartozz** [rails/rails#35879]
# I've the following routes in routes.rb
# How get the optional parameters in the EventsController.?
# In Django is the following
# def events(city = None, type_event = None)
# if city and type_event == None:

Rails.application.routes.draw do 
  resources :events do 
    get "/" => "events#index"
    get "/(:city)/(:type_event)" => "events#index"
  end 
end

**Comment by gadikotamohan** [comment]
@bartozz  if I understand your query correctly

```
Rails.application.routes.draw do
  resources :events
  get "/:city/:type_event" => "events#index"
end

# Your controller.
class EventsController < ApplicationController
  def index
    Rails.logger.info "City -> #{params[:city]}"
    Rails.logger.info "type_event -> #{params[:type_event]}"
  end
end
```

Having said, your question was more related to **howto**. Please use stackoverflow or quora platform to resolve your query.  Use this platform to report any issues related to rails project.
   Would suggest you to look-into the documentation which rails has already provided. https://edgeguides.rubyonrails.org/getting_started.html

**Comment by y-yagi** [comment]
As pointed by gadikotamohan, please use the [mailing list](https://groups.google.com/forum/#!forum/rubyonrails-talk) or StackOverflow for questions/help, where a wider community will be able to help you. We reserve the issues tracker for issues only.
