### ISSUE TITLE
Get optionals parameters of Rails routing file.

### ISSUE THREAD

**Issue by bartozz** [rails/rails#35877]
# I've the following routes in routes.rb
# How get the optional parameters in the EventsController.?
# In Django is the following
# def events(city = None, type_event = None)
# if city and type_event == None:

Rails.application.routes.draw do 
  resources :events do 
    get "/" => "events#index"
    get "/(:city)/(:type_event)" => "events#index"
  end 
end

**Comment by gadikotamohan** [comment]
@bartozz  duplicate of https://github.com/rails/rails/issues/35879
