### ISSUE TITLE
[activerecord] something_id is translated to "Something can't be blank" even if there is no "something"

### ISSUE THREAD

**Issue by localhostdotdev** [rails/rails#35889]
### Steps to reproduce

- `rails new rails-bug-1`
- `rails g model MyModel something_id:string`
- `validates :something_id, presence: true`
- `MyModel.create!`

https://github.com/localhostdotdev/rails-bug-1

### Expected behavior

```
ActiveRecord::RecordInvalid (Validation failed: Something ID can't be blank)
# or
ActiveRecord::RecordInvalid (Validation failed: something_id can't be blank)
# or anything really that says "id"
```

### Actual behavior

```
ActiveRecord::RecordInvalid (Validation failed: Something can't be blank)
```

### System configuration

**Rails version**: `Rails 6.0.0.beta3`
**Ruby version**: `ruby 2.6.2p47 (2019-03-13 revision 67232) [x86_64-darwin17]`

I understand the rationale where the vast majority of the time `[name]_id` represents a foreign key and `[name]` describes the issue correctly.

In my case I have both `something` and `something_id` as fields (`something` is a `jsonb` field, `something_id` a string). Thus showing `Something can't be blank` mislead me in thinking the `something` attribute was blank when it was the `something_id` attribute.

I know there is quite some history behind this because it's using `.humanize` or `.titleize` (I think) and it's a visible client output.

What I'm asking is: would be it okay if humanize was not used (maybe `.camelize`?) when the `something` exists and is not an association.

Maybe my use case is too specific though, not sure.

**Comment by bparanj** [comment]
This is not a valid bug. If you want to check the presence of a foreign key, you can customize the error message to override the default error message.

**Comment by localhostdotdev** [comment]
I guess I was expecting some "convention over configuration", but might be that _id is the convention of foreign keys, so I might fall on the configuration side I guess

**Comment by rafaelfranca** [comment]
Yes. This is exactly that case. The convention is the foreign key, since it is not what you want you will need to configure the message.
