### ISSUE TITLE
`private_constant` macro doesn't work unless both eager_load and cache_classes are true

### ISSUE THREAD

**Issue by bcgraham** [rails/rails#35898]
### Steps to reproduce
```sh
rails new private_constant_test ./ --skip-spring --edge
cd private_constant_test
echo 'class A; end' > app/models/a.rb
mkdir app/models/a
echo 'class A; class B; end; private_constant :B; end' > app/models/a/b.rb
bin/rails runner -e development 'puts A::B'
bin/rails runner -e test 'puts A::B'
bin/rails runner -e production 'puts A::B'
```

### Expected behavior
Referencing `A::B` should raise a `NameError` with the message `private constant A::B referenced`

### Actual behavior
It only raises an error in typical production environments, not in typical development or test environments

### System configuration
**Rails version**: 5.2.3 (also tested on 5.2.2.1)

**Ruby version**: ruby 2.6.0p0 (2018-12-25 revision 66547) [x86_64-darwin18]

### Notes
Possibly related to #25813. That was a bug in Ruby and seems to have been fixed. #25813 references https://bugs.ruby-lang.org/issues/11055, which is still open, but https://bugs.ruby-lang.org/issues/14469 appears to be a duplicate, and is closed.

The `--skip-spring` isn't necessary; it just made it more repeatable locally. 

When both `eager_load` and `cache_classes` are true, Rails behaves as expected. Otherwise, private constants can be accessed like public constants.

This seems to originate from [`ActiveSupport::Dependencies#load_missing_constant`](https://github.com/rails/rails/blob/master/activesupport/lib/active_support/dependencies.rb#L524-L526):
```ruby
if from_mod.const_defined?(const_name, false)
  log("constant #{qualified_name} autoloaded from #{expanded}.rb")
  return from_mod.const_get(const_name)
else
  raise LoadError, "Unable to autoload constant #{qualified_name}, expected #{file_path} to define it"
end
```
Neither `const_defined?` and `const_get` discern whether the constant is private.

**Comment by trcarden** [comment]
FWIW if you can make it to rails 6 and the zeitwerk autoloader this starts working again (or at least we had the same problem and simply going through the upgrade process resolved it without having to rework the classic autoloader.
