### ISSUE TITLE
ActiveRecord::Tasks::DatabaseTasks no longer works outside of Rails

### ISSUE THREAD

**Issue by jhollinger** [rails/rails#35902]
### Steps to reproduce
Clone example project from https://github.com/jhollinger/rake-record and use the **activerecord-6** branch.

    bundle install
    bundle exec rake db:setup
    NameError: uninitialized constant ActiveRecord::Tasks::DatabaseTasks::Rails 
    ...

### Expected behavior
With proper configuration (i.e. manually setting `db_dir`, `root`, `migrations_paths`, `database_configuration`, etc) `ActiveRecord::Tasks::DatabaseTasks` should be usable when `Rails` is not defined. This works as expected in the master branch of the above project (on Rails 5.X).

    bundle install
    bundle exec rake db:setup
    Created database 'data/development.sqlite3'
    -- create_table("widgets", {:force=>:cascade})
       -> 0.0122s

### Actual behavior
Calls to `DatabaseTasks.for_each` (such as those made in `lib/active_record/railties/databases.rake`) raise:

    NameError: uninitialized constant ActiveRecord::Tasks::DatabaseTasks::Rails

In recent Rails 4- 5 this file has always wrapped things in `if defined? Rails`, but there are now a few `Rails` references outside of those checks.

### System configuration
**Rails version**: 6.0.0.beta3

**Ruby version**: 2.5.1p57

**Comment by douglasrosa0110** [comment]
And with ```rails db:setup```  @jhollinger ?

**Comment by jhollinger** [comment]
@douglasrosa0110 I'm not sure I understand. The `rails` command certainly wouldn't work w/o the rails gem.

**Comment by rafaelfranca** [comment]
hmmm, that is true since the multi-database support in https://github.com/rails/rails/pull/32274. @eileencodes do you think we can decouple those tasks from the `railtie` framework?

**Comment by gmcgibbon** [comment]
I believe `Rails.env` can be subbed out for `ActiveRecord::ConnectionHandling::DEFAULT_ENV.call` but I'm not sure about `Rails.application.config.load_database_yaml`, we might have to conditionally call that if Rails is defined and use something else otherwise.

**Comment by eileencodes** [comment]
I've been out this week but can look at this early next week.
