### ISSUE TITLE
failing yarn install does not stop further steps

### ISSUE THREAD

**Issue by dreyks** [rails/rails#35929]
### Steps to reproduce

- have a wrong package url in package.json or no network connection
- run `rails assets:precompile`
### Expected behavior

rake task fails completely
### Actual behavior

task proceeds to precompiling resulting in possible runtime errors
### System configuration
**Rails version**:
5.2
**Ruby version**:
2.6.2

the issue is with 
https://github.com/rails/rails/blob/43288a053feecf7cdbe74e61f3ca2038d976e9f4/railties/lib/rails/tasks/yarn.rake#L11
we should probably add `or exit!` to this line. I can craft a PR if you're ok with this

**Comment by y-yagi** [comment]
I think `raise` is more appropriate than `exit!`. This allows to switch to the using `exception: true` option when only support Ruby >= 2.6.  Anyway, I agree that it should be an error. Can you create a PR?

**Comment by dreyks** [comment]
#36015
