### ISSUE TITLE
ActiveStorage Feature Request - Support for CDN (Cloudfront)

### ISSUE THREAD

**Issue by eaconway** [rails/rails#35926]
Hello Rails team,

**Disclaimer: this is my first Github issue, so apologies if I'm missing something.

I've spent a fair amount of time researching and trialing how to setup Active Storage to leverage Cloudfront. There are a number of issues like:
- https://github.com/rails/rails/issues/31419 (Primary source)
- https://github.com/rails/rails/issues/33052
- https://stackoverflow.com/questions/52292961/using-cloudfront-with-active-storage

And even some pieces on other projects:
- https://github.com/spree/spree/issues/9043

But can't seem to find a clear solution, or one sanctioned from Rails/Active Storage itself, so I believe this is still a bug. I'm looking for confirmation that this will be resolved in Rails 6 release (hopefully), or feedback from the team. Thanks!

### Steps to reproduce

Setup basic rails project with Active storage. Set asset host to Cloudfront CDN (tried pointing CDN to S3 and project, or simply back to project itself). Unfortunately, Active Storage ignores asset_host and pulls directly from S3 regardless.

### Expected behavior

When using a CDN to host files for site, specifically those user uploaded through Active Storage, Active Storage should run requests through CDN first when making download requests. Uploads should be through Active Storage current pathways, but once asset_host is set, downloads should flow through CDN.

### Actual behavior

Currently, everything flows through Active Storage when trying to download/retrieve blobs, resulting in slow load times

### System configuration
**Rails version**: 5.2.2

**Ruby version**: 2.5.1

**Comment by rafaelfranca** [comment]
Thank you so much for the issue but we don't take feature request on the issue tracker. We recommend you to try to implement the feature and send us a pull request or if you are in doubt if the feature will be accepts ask in Rails Core mailing list for feedback.

**Comment by collimarco** [comment]
Any updates on this with Rails 6? We also want to use Cloudfront in front of S3, as recommended by Amazon.

**Comment by collimarco** [comment]
Here's my final solution:
https://stackoverflow.com/a/59107484/51387

Basically for now I use `sub` on `service_url`.

**Comment by joshuacronemeyer** [comment]
Every once in awhile I come back to check on "ActiveStorage CDN support" and google always finds this rails issue. Active development on this can be found here. https://github.com/rails/rails/pull/34477

**Comment by equivalent** [comment]
I've found article where one dude manage to introduce CDN  https://lipanski.com/posts/activestorage-cdn-rails-direct-route I've didn't try it yet (will do that in couple of weeks) Just posting it here if anyone find it useful

**Comment by joshuacronemeyer** [comment]
@equivalent Rails active storage docs have a section on using a CDN. https://edgeguides.rubyonrails.org/active_storage_overview.html#putting-a-cdn-in-front-of-active-storage It's probably better to look there.

**Comment by zzak** [comment]
See: #42305
