### ISSUE TITLE
WHERE IN doesn't support array of pairs

### ISSUE THREAD

**Issue by Ana06** [rails/rails#35925]
I had expected that:

```ruby
BsRequestAction.where('(target_project, target_package) IN (?)', [['target_project1','target_package1'], ['target_project2','target_package2']])
```
produces the following SQL query:

```sql
SELECT  `bs_request_actions`.* FROM `bs_request_actions` WHERE ((target_project, target_package) IN (('target_project1','target_package1'), ('target_project2','target_package2')))
```

being equivalent to:

```ruby
BsRequestAction.where("(target_project, target_package) IN ((target_project1','target_package1'), ('target_project2','target_package2'))")
```
Instead, it produces the following error:

```ruby
Traceback (most recent call last):
        1: from (irb):510
TypeError (can't quote Array)
```

This forces me to write code like:

```ruby
projects_and_packages = [['target_project1','target_package1'], ['target_project2','target_package2']]
query_string = projects_and_packages.map { |project, package| "(#{project},#{package})" }.join(",")
BsRequestAction.where("(target_project, target_package) IN (#{query_string})")
```
:see_no_evil: :see_no_evil: :see_no_evil: 

I would like to suggest that Rails supports arrays of pairs for WHERE IN queries as it is expected and allow to write much nicer code. :bowtie: 

### System configuration
**Rails version**: Rails 5.2.3

**Ruby version**: ruby 2.5.5p157 (2019-03-15 revision 67260) [x86_64-linux-gnu]

**Comment by rafaelfranca** [comment]
Thank you so much for the issue but we don't take feature request on the issue tracker. We recommend you to try to implement the feature and send us a pull request or if you are in doubt if the feature will be accepts ask in Rails Core mailing list for feedback.

**Comment by Ana06** [comment]
I am not sure if this a new feature request. I would say this is a bug report. I find the behavior broken.

**Comment by simi** [comment]
@ana06 hello! Is there any official documentation mentioning this should work? Otherwise it is probably not supported behaviour. Anyway it looks like interesting use-case to support, but I'm not sure if this will not be in conflict with currently supported behaviours. Feel free to open discussion at mail list as Rafael recommended.

**Comment by Ana06** [comment]
@simi 

> Is there any official documentation mentioning this should work?

Well, the [`where` documentation](https://apidock.com/rails/ActiveRecord/QueryMethods/where) does mention the following:

> the first element of the array is treated as a template, and the remaining elements are inserted into the template to generate the condition. Active Record takes care of building the query to avoid injection attacks, and will **convert from the ruby type to the database type where needed**. Elements are inserted into the string in the order in which they appear.

There is nothing else (at least that I have seen) reading not supported ruby types.

@simi 

> Anyway it looks like interesting use-case to support, but I'm not sure if this will not be in conflict with currently supported behaviours.

I think it doesn't conflict with current supported behaviours. My main concern are the databases which doesn't support pairs. I think for example SQLlite doesn't support it. But I think in that case it would be enough with an exception or an small trick like:

```sql
SELECT  `bs_request_actions`.* FROM `bs_request_actions` WHERE  target_project || '-' || target_package IN ('target_project1-target_package1', 'target_project2-target_package2')
```

Anyway, I can send that email anyway. :wink:

**Comment by Ana06** [comment]
Email sent! Although it doesn't seen to appear in the group list... maybe it needs to be approved :thinking:

**Comment by simi** [comment]
@rafaelfranca I think (as @Ana06 described) it can be a little confusing while reading documentation. Maybe it can be fixed on documentation side for now.
