### ISSUE TITLE
Content Security Policy: report-uri is deprecated

### ISSUE THREAD

**Issue by Medvezo** [rails/rails#35937]
CSP's `report-uri` directive [has been deprecated](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy#Reporting_directives) and will be replaced by `report-to` directive. Unfortunately, `report-to` [is only supported](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/report-to) by Chrome 70+. In  order to keep backwards compatability, send both `report-uri` and `report-to`.

Now this should probably happen behind the scenes as Rails already supports `report_uri` directive (i.e. by setting `policy.report_uri`, Rails will send both `report-to` and `report-uri` directives)

**Comment by jeremy** [comment]
Looks like report-to introduces a new reporting API, new report content type, and more. Indicating report-to means the report endpoint will need to understand how to parse the new content type, so this isn't necessarily backward compatible.

Sounds like this should be a new feature to support the reporting API: https://w3c.github.io/reporting/

PR welcome! In the meantime, we're good to continue using report-uri for compatibility during the (long) deprecation period.
