### ISSUE TITLE
No headers available in env when using Rack::MockRequest

### ISSUE THREAD

**Issue by bobvanderlinden** [rails/rails#35943]
### Steps to reproduce

The documentation (https://guides.rubyonrails.org/testing.html#setting-headers-and-cgi-variables) says I can do the following in my tests (Minitest):

```
get '/', params: {}, headers: { 'Authorization' => 'Bearer 123' }
```

When I have middleware like the following:

```
class MyMiddleware
  def call(env)
    pp env
    @app.call(env)
  end
end
```

The output shows:

```
{"rack.version"=>[1, 3],
 "rack.input"=>#<StringIO:0x00007f98fae19890>,
 "rack.errors"=>#<StringIO:0x00007f98fae19a70>,
 "rack.multithread"=>true,
 "rack.multiprocess"=>true,
 "rack.run_once"=>false,
 "REQUEST_METHOD"=>"GET",
 "SERVER_NAME"=>"example.org",
 "SERVER_PORT"=>"80",
 "QUERY_STRING"=>"",
 "PATH_INFO"=>"/",
 "rack.url_scheme"=>"http",
 "HTTPS"=>"off",
 "SCRIPT_NAME"=>"",
 "CONTENT_LENGTH"=>"0"}
```

I expect `HTTP_AUTHORIZATION` to be in `env`, but it isn't.

Additionally, whenever I run `bundle exec rails server` and do a curl like the following:

```
curl http://localhost:3000/ --header "Authorization: Bearer 123"
```

I do the call to the actual server it _does_ show up. Here is part of the output:

```
...
 "HTTP_ACCEPT"=>"*/*",
 "HTTP_AUTHORIZATION"=>"Bearer 123",
 "rack.version"=>[1, 3],
...
```

Digging through the code, I was surprised that `Rack::MockRequest.env_for` did not mention any `opts[:headers]` in its implementation:

https://github.com/rack/rack/blob/4c0708582e27c588764c6273d04a377ff72dd4fc/lib/rack/mock.rb#L91

It only supports passing through string-based env variables and not headers.

I was expecting it would handle the `headers:` values and possibly convert them to `HTTP_*` `env` variables. Is this intentional, or is this something for which a PR is welcome?

### System configuration
**Rails version**:

```
Rails 5.2.2.1
```

**Ruby version**:

```
ruby 2.5.3p105 (2018-10-18 revision 65156) [x86_64-darwin18]
```

**Comment by bparanj** [comment]
Looking at the test in http_token_authentication_test.rb I see:

```ruby
  test "successful authentication request with Bearer instead of Token" do
    @request.env["HTTP_AUTHORIZATION"] = "Bearer lifo"
    get :index

    assert_response :success
  end
```

It seems like a documentation bug. Can you set the token as in the code above and see if you still have the problem?

**Comment by bobvanderlinden** [comment]
Yes, that example works fine, but it isn't actually what I want to test for in an integration test. I actually want to test for the headers that a client would be sending to the app and not how CGI variables are being handled.

If this is a documentation bug, is using 'real' header names something that should be avoided?

**Comment by DKRetzlaff** [comment]
@bobvanderlinden you could use: 
`Rack::MockRequest.env_for(url, headers)`

This will add to the `env` variable all the keys inside the headers hash. I dont know if this is the best approach, but can solve the missing of headers in the middleware call as we can see in the `env_for` method: https://github.com/rack/rack/blob/4c0708582e27c588764c6273d04a377ff72dd4fc/lib/rack/mock.rb#L147
