### ISSUE TITLE
third select options not validating arguments

### ISSUE THREAD

**Issue by localhostdotdev** [rails/rails#35942]
### Steps to reproduce

- `= form_for User.new do |f|`
- `f.select(:name, ['a', 'b'], class: '1')`

### Expected behavior

I expected to have a `class="1"`, but actual expected behavior should be that it raises an error because I'm using the third argument instead of the fourth, e.g.: 

https://api.rubyonrails.org/v5.1/classes/ActionView/Helpers/FormOptionsHelper.html#method-i-select

```
select(object, method, choices = nil, options = {}, html_options = {}, &block)
```

### Actual behavior

silently ignores what I pass

### System configuration

**Rails version**: 6.0.0.beta3
**Ruby version**: 2.6.2

------

it's obviously not a new problem, but a very annoying one.

even more annoying when `select_tag` works just fine

https://api.rubyonrails.org/v5.1/classes/ActionView/Helpers/FormTagHelper.html#method-i-select_tag

```
select_tag(name, option_tags = nil, options = {})
```

**Comment by rafaelfranca** [comment]
Thank you for the issue. This is unfortunately how Ruby works and there is nothing we can do. `class: '1'` is a valid choice too, so we can't raise an error when you pass it.

**Comment by localhostdotdev** [comment]
```
= f.select(:name, ['a', 'b'], abcdef: '1', data: 1, class: 1, guyhigyftdrcvuihouy: 1)
```

those are all valid options that could be used by the tag? then why are they all ignored?

as far I know, here are the options:

selected, disabled, + select_content_tag options (include_blank, prompt, include_hidden) +  add_options (include_blank, prompt).

looks like a closed list to me

**Comment by rafaelfranca** [comment]
Sorry, I got confused with the signature you posted

```
select(object, method, choices = nil, options = {}, html_options = {}, &block)
```

In that case `class: '1'` would be the `choices` argument and that is valid, but the signature of the method you are using is:

```
select(method, choices = nil, options = {}, html_options = {}, &block)
```

In that case indeed `class` is not a valid option by default, but, we can't limit which options are valid because it is possible to define custom tags and if we validate the options it become harder for those custom tags to add more options without monkey patch the base classes.

One of the libraries that define custom tags is https://github.com/plataformatec/simple_form. And it expect that options not handled by default by rails inputs are ignored instead of raising errors.

**Comment by localhostdotdev** [comment]
see, even you got confused :)

> if we validate the options it become harder for those custom tags to add more options without monkey patch the base classes

oh ok I see, wouldn't people base their custom tags on `ActionView::Helpers::InstanceTag` though? (that would be a breaking I guess as tags are public apis)

anyway, I understand the decision, but it's just yet another place where parameters get silently ignored

**Comment by rafaelfranca** [comment]
To be fair I totally agree with you. This is why I think simple_form API is easier to understand. I even have a long time wish to change our form helpers to use named parameters instead of positioned parameters.

```
f.select(:name, collection: ['a', 'b'], html: { class: 1 })
```

**Comment by localhostdotdev** [comment]
OMG that would be so great!
