### ISSUE TITLE
#deep_dup duplicates classes

### ISSUE THREAD

**Issue by darthjee** [rails/rails#35948]
### Steps to reproduce
I ran the following code

```ruby
klass = Class.new
hash = { key1: klass, key2: String }
hash.deep_dup
```

this creates a new hash where none of the values are the original classes
```
 {:key1=>#<Class:0x0000000478f560>, :key2=>#<Class:0x0000000478f510>}
```

### Expected behavior
I expected that at least the named class `String` would not be duplicated

### Actual behavior
Both were duplicate

I would understand that no named classes are duplicated but should we be duplicating named classes?

### System configuration
ruby 2.4.0p0 (2016-12-24 revision 57164) [x86_64-linux]
aactivesupport (5.2.3)

### Solution

I was thinking
```ruby
class Class
  def duplicable?
    name.nil?
  end
end
```

but that would mean that `#duplicable?` would respond differently depending on the type of class, and I don't know what would be really intended 

Thanks,
~Fernando Favini

**Comment by rafaelfranca** [comment]
Classes are duplicable, so we can't return `nil` for it.

```
>> String.object_id
=> 70177660436020
>> String.dup.object_id
=> 70177656086120
```

The behavior you are getting is what is expected in Ruby given a class can de duplicated.
