### ISSUE TITLE
Multiple has_one relation to same model create error

### ISSUE THREAD

**Issue by thib44** [rails/rails#35954]
Hello all, I encountered an error about has_one relation. I found a solution, but I'm not sure it's that it's relevant. 

### Steps to reproduce
I've got trouble with a model wich have two has_one relation to a same model :
```ruby
class ProfessionalStatus < ApplicationRecord
 # Association(s):
  has_one :candidate,
    foreign_key: 'current_professional_status_id',
    inverse_of: :current_professional_status,
    dependent: :nullify

  has_one :candidate,
    foreign_key: 'wished_professional_status_id',
    inverse_of: :wished_professional_status,
    dependent: :nullify
end
```

```ruby
class Candidate < ApplicationRecord
  belongs_to :current_professional_status,
    class_name: 'ProfessionalStatus',
    foreign_key: 'current_professional_status_id',
    inverse_of: :candidate,
    optional: true

  belongs_to :wished_professional_status,
    class_name: 'ProfessionalStatus',
    foreign_key: 'wished_professional_status_id',
    inverse_of: :candidate,
    optional: true
end
```
### Expected behavior
I want when I update a professional status, that the reference to professional_status continue to be the same :
- current_professional_status_id : do not change
- wished_professional_status_id: do not change

### Actual behavior
My issue is that when I update the `ProfessionalStatus` relative to the `wished_professional_status_id`, the `current_professional_status_id` change and take the same id that `wished_professional_status_id`.

To avoid this issue I have to do :

```ruby
class ProfessionalStatus < ApplicationRecord
  # Association(s):
  has_one :current_candidate,
    class_name: 'Candidate'
    foreign_key: 'current_professional_status_id',
    inverse_of: :current_professional_status,
    dependent: :nullify

  has_one :wished_candidate,
    class_name: 'Candidate',
    foreign_key: 'wished_professional_status_id',
    inverse_of: :wished_professional_status,
    dependent: :nullify
end
```

```ruby
class Candidate < ApplicationRecord
 belongs_to :current_professional_status,
    class_name: 'ProfessionalStatus',
    foreign_key: 'current_professional_status_id',
    inverse_of: :current_candidate,
    optional: true

  belongs_to :wished_professional_status,
    class_name: 'ProfessionalStatus',
    foreign_key: 'wished_professional_status_id',
    inverse_of: :wished_candidate,
    optional: true
end
```
But it's not really natural to do ! 

### System configuration
**Rails version**:  5.2.0

**Ruby version**: 2.5.5

**Comment by bparanj** [comment]
This is not a valid bug. You cannot have two:

```ruby
has_one :candidate
```

with different foreign keys. You have to give different names as you have done in the actual behavior.

**Comment by gmcgibbon** [comment]
@bparanj is correct. This sounds like more of a naming problem than a bug. For usage questions, please refer to the mailing list or StackOverflow where a wider community can assist you. The issue tracker is reserved for bugs only. Thanks!
