### ISSUE TITLE
Unable to analyze blob before saving record

### ISSUE THREAD

**Issue by claudiogn** [rails/rails#35976]
### Steps to reproduce
On Rails 6.0.0.beta3 create a new App and then create a model with an Active Storage Attachment. This model also has width and height attributes (both integer). Those attributes come from the image we upload for the record, so before saving it we need to analyze its blob:

```ruby
class Model < ApplicationRecord
  has_one_attached :image
  before_validation :set_record_dimensions
  validates :width, :height, presence: true

  private

  def set_record_dimensions
    image.blob&.analyze
    self.width = image&.metadata['width']
    self.height = image&.metadata['height']
  end
end
```

### Expected behavior
I have an App on Rails 5.2 (Ruby 2.5.3) that does the same thing. So we are able to set the record dimensions using the attachment dimensions with the `set_record_dimensions` callback.

### Actual behavior
On Rails 6.0.0.beta3 on the other hand we are unable to do this, we keep getting this exception instead:   
```ruby
ActiveStorage::FileNotFoundError
```
I'd would like to know if this is the expected behaviour of the new Rails version or is some kind of bug.
Any ideas on how to do it?

### System configuration
**Rails version**: 6.0.0.beta3

**Ruby version**: 2.6.2

**Comment by prathamesh-sonpatki** [comment]
Can you upload a sample application on Github that reproduces the issue? Thanks.

**Comment by sian-izm** [comment]
I reproduced it by 6.0.0 rc1
```
irb(main):001:0> model = Model.new(height: 1, width: 1)
   (0.9ms)  SELECT sqlite_version(*)
=> #<Model id: nil, width: 1, height: 1>
irb(main):002:0> model.image.attach(io: File.open('db/fixtures/dummy.jpg'), filename: 'dummy.jpg')
=> #<ActiveStorage::Attached::Changes::CreateOne:0x00007ff1afbb6f90 @name="image", @record=#<Model id: nil, width: 1, height: 1>, @attachable={:io=>#<File:db/fixtures/dummy.jpg>, :filename=>"dummy.jpg"}>
irb(main):003:0> model.save!
   (0.1ms)  begin transaction
  Disk Storage (0.6ms) Downloaded file from key: ffit9ky2kz3q7fgl6nvskw5tcfrw
   (0.1ms)  rollback transaction
Traceback (most recent call last):
        2: from (irb):3
        1: from app/models/model.rb:9:in `set_record_dimensions'
ActiveStorage::FileNotFoundError (ActiveStorage::FileNotFoundError)
```
The code is following.
https://github.com/sian-izm/rails_issue_35976/commit/9eb1d050e49ef1774fd3e0f5b0ed3b869bde4ba4

It seems to occur at here.
https://github.com/rails/rails/blob/6-0-stable/activestorage/lib/active_storage/service/disk_service.rb#L130

Probably, the reference file at `/storage` hasn't been created when analyze.

**Comment by kaspth** [comment]
In Rails 6 attachments aren't uploaded until the associated record is saved. https://github.com/rails/rails/pull/33303
