### ISSUE TITLE
`ActiveJob` `exception_executions` may cause incorrect / unexpected retry behavior during upgrade

### ISSUE THREAD

**Issue by cpruitt** [rails/rails#35986]
I'm opening this in hopes of getting some feedback and opinions about a potential issue sites may encounter during upgrade. I have a "soft" opinion, but no preferred hard-and-fast solution. I'm also very open to someone pointing out that my understanding is wrong and that this is a non-issue entirely.

**TL/DR;**

* I'm hoping to get some feedback about whether this is really an issue and what is the best thing to be done about it if it is.

* `ActiveJob` execution counts and `retry_on` logic is handled differently for Rails 5 and Rails 6. This can potentially pose problems in a downgraded or temporarily mixed production environment.

* During testing with production data or final rollout to production, Rails 5 and 6 applications can fight over what counter data should be serialized for the job and how to handle retries. This can happen if the app is production tested with Rails 6 and then rolled back to Rails 5 or when Rails 6 is deployed to production and Rails 5 workers have not yet finished deploying.

* It may be better for Rails 6.0 to support both the rails 5 retry method as well as Rails 6 and allow the application to opt in when Rails 6 workers are deployed and ready to handle the new retry method.

**PR History**

1. Last November: https://github.com/rails/rails/pull/34352 added `exception_executions` to `ActiveJob`and allowed `ActiveJob` to correctly track execution count based on the exceptions passed to `retry_on`. (Fixed https://github.com/rails/rails/issues/34337)

2. Last January: https://github.com/rails/rails/pull/34731 fixed an issue in which Rails 6 workers processing jobs queued by Rails 5 would error because `exception_executions` was `nil`. The fix here was to initialize `exception_executions` as needed if it was found to be missing.

3. Last Week (April): https://github.com/rails/rails/pull/35956 addressed calculating the correct delay time for retries. This changed the delay to be based on `exception_executions` instead of the global `executions` count.

**The Nature of the Problem**

The November PR is a fix for what DHH noted was a bug (https://github.com/rails/rails/issues/34337#issuecomment-434004236), however current production applications still expect the current (buggy) retry behavior. The process of migrating from Rails 5 to 6 with jobs in the production queue has the potential to be problematic and produce unexpected results with retries.

A couple of issues to consider:

* `ActiveJob` instances queued by Rails 6 applications need to be reliably run by Rails 5 worker applications and vice versa.

* When testing for Rails 6 begins in production, the Rails 6 application will be touching production data. The way it stands now, Rails 5 and Rails 6 serialization methods will be fighting over whether or not `exception_executions` is part of the serialized data, and whether or not to keep retrying the job based on one of two different execution counts.

* It will be impossible to deploy to all production servers at exactly the same time, so there will necessarily be some amount of time in which the main application and the background workers are on two different versions. If testing is done in a way where Rails 6 is rolled out, tested, and reverted to Rails 5, then the mismatch can be in either direction.

**Based on the current behavior, it seems to me that the following has potential to occur:**

* A job enqueued with Rails 5 will have a global `executions` counter and not a `exception_executions` counter.

* If Rails 6 tries to perform the job, the counter will be found missing, initialized (set to zero), and not fail. However, previous execution counts will be ignored, such that if the job failed `2` times already, it will now have an exception-specific execution count of `0`.

* On the next failure, the Rails 6 worker will save updates to both the `executions` and `exception_executions` counts. (the global count functionality is not lost)

* If a Rails 5 worker then tries to run the job, such as after rolling back from a production test, it will do so using the global `executions` counter, which may be higher than normal because Rails 6 allows multiple exceptions to reach their own maximum number but still increments the global execution count. This will revert to the Rails 5 behavior and, if the global counter is > the max exceptions allowed, it will stop retrying the job. (This is probably expected and reasonable behavior.)

* Jobs enqueued with Rails 6, or run by a Rails 6 worker (e.g. during production testing) will have both `executions` and `exception_executions`. Rails 5 workers that subsequently run the job will remove the `exception_executions` key from the serialized data, effectively turning it back into a Rails 5 job. If a Rails 6 worker then picks it up.... (repeat)

**I believe the root of the concern may be that:**

1. When upgrading to rails 6, the new retry behavior is immediately enforced, without giving any time to allow existing queued jobs to finish being filtered through the pipeline or for Rails 6 upgrade deploys to fully finish rolling out to all servers / workers.

2. When Rails 6 encounters a job enqueued by Rails 5, it attempts to update it's `exception_executions` value and make the job Rails 6 compatible instead of continuing to run the job "the Rails 5 way".

I think there may be a case to say that:

* Rails 6.0 retry behavior should accommodate both global and per-exception counts and be executed in the way expected at the time the job was added to the queue instead of based on the version of Rails running the job.

* Rails 6.0 jobs should default to the old execution behavior when adding to the queue and allow the application to opt into the new behavior when there are Rails 6 workers ready to handle the newly queued jobs. Or at least, allow the application to opt out of the new behavior until ready.

* Rails the 5 retry process should be deprecated in Rails 6.0 and removed in Rails 6.1.

I'd really love to hear additional opinions on this and whether or not the original PR authors have any thoughts on handling the upgrade transition in a more graceful way.

CC PR Authors: @albertoalmagro, @rosa, @mrhead

**Comment by mrhead** [comment]
@cpruitt I don't think that I'll helpful here and I can't comment on how the migration (upgrade) should work. I was just reading the code, saw some inconsistency so I fixed it.

**Comment by cpruitt** [comment]
@mrhead Not a problem! Thanks for the reply. 🙂

**Comment by rosa** [comment]
@cpruitt, first of all, thank you for writing such a detailed and careful description of the issue 👏 👏 
I'll try to help by addressing each of the points you brought up:

>A job enqueued with Rails 5 will have a global `executions` counter and not a `exception_executions` counter.
> If Rails 6 tries to perform the job, the counter will be found missing, initialized (set to zero), and not fail. However, previous execution counts will be ignored, such that if the job failed 2 times already, it will now have an exception-specific execution count of 0.

Correct. We were aware of this when we upgraded but having jobs that could be potentially retried more times than expected wasn't a problem for us. The kind of retries we do and the limits we set for them (normally up to 5 or 10 times) allow for having some extra retries and this being a non-issue. The majority of our failing, retriable jobs succeed after 1 retry.

> On the next failure, the Rails 6 worker will save updates to both the `executions` and `exception_executions` counts. (the global count functionality is not lost)
> If a Rails 5 worker then tries to run the job, such as after rolling back from a production test, it will do so using the global `executions` counter, which may be higher than normal because Rails 6 allows multiple exceptions to reach their own maximum number but still increments the global execution count. This will revert to the Rails 5 behavior and, if the global counter is > the max exceptions allowed, it will stop retrying the job. (This is probably expected and reasonable behavior.)

Yes, I think this is expected and perfectly reasonable. After all, the job reached its maximum number of allowed retries (it did _more_). 

> Rails 6.0 retry behavior should accommodate both global and per-exception counts and be executed in the way expected at the time the job was added to the queue instead of based on the version of Rails running the job.

I'd defer to Rails maintainers on the decision about this. In my particular case this wasn't necessary  for any of the apps we upgraded. The reason is that the footprint of the change was really small. It only affects jobs that have been enqueued on one version of Rails, _failed_, and then executed again after at least one retry on a different version of Rails. This was a very small amount of jobs for us, most enqueued jobs wouldn't fail and thus this change was transparent for them. For the jobs that did fail and got retried, having one or more extra retries on the change from Rails 5 to Rails 6 because of starting again on `exception_executions` being 0 was totally fine in our case as I mentioned above.

**Comment by rafaelfranca** [comment]
> * Rails 6.0 jobs should default to the old execution behavior when adding to the queue and allow the application to opt into the new behavior when there are Rails 6 workers ready to handle the newly queued jobs. Or at least, allow the application to opt out of the new behavior until ready.

I'm happy to accept a PR for this. I think we should make this configurable at least while the rollout of the new version is being made.

**Comment by albertoalmagro** [comment]
@cpruitt Thanks for the detailed description of the problem and for letting me know about this. I think that although this might not be an issue in most cases, it's interesting to make it configurable for the cases were it could be problematic 👍

**Comment by dhh** [comment]
(tracked via the open PR)
