### ISSUE TITLE
"Dangerous query method" warning is triggered by ActiveRecord::Sanitization methods

### ISSUE THREAD

**Issue by januszm** [rails/rails#35993]
### Steps to reproduce
```ruby
ActiveRecord::Base.sanitize_sql_for_order(["FIELD (id, ?)", special_ids_array])
> DEPRECATION WARNING: Dangerous query method (method whose arguments are used as raw SQL) called with non-attribute argument(s): "FIELD (id, ?)" ...
```

### Expected behavior
No warnings. `sanitize_sql_for_order` and other `ActiveRecord::Sanitization` methods return `Arel::Nodes::SqlLiteral` that can be used as an argument to `order()` without the deprecation warning.

### Actual behavior
It works, but it generates the following warning:

```
DEPRECATION WARNING: Dangerous query method (method whose arguments are used as raw SQL) called with non-attribute argument(s): "FIELD (id, ?)" ...
```

This warning can be "silenced" by wrapping the "FIELDS" code with `Arel.sql`, but it looks like an overkill:

```ruby
ActiveRecord::Base.sanitize_sql_for_order([Arel.sql("FIELD (id, ?)"), article_ids_array])
> No warning
```

### System configuration
**Rails version**: 5.2.3

**Ruby version**: 2.6.2

RDBMS: MySQL

====

@rafaelfranca please have a look at the examples below. 

1. Legacy Rails app code before upgrade to 5.2 and refactoring

```ruby
# "Dangerous query method" warning, "possible" SQL injection
MyModel.order("FIELD(id, #{featured_ids_string})")
```

2. After the upgrade to 5.2 and with `Arel.sql()`
```ruby
# No "Dangerous query" warning, but tools like `brakeman` would still print a warning about possible SQL injection
MyModel.order(Arel.sql("FIELD(id, #{featured_ids_string})"))
```

3. Added `sanitize_sql_array(condition)` (via `sanitize_sql_for_order`) to, hopefully, remove both the "Dangerous query" and SQL injection warnings
```ruby
MyModel.order(MyModel.sanitize_sql_for_order(["FIELD(id, ?)", featured_ids_array]))
```

In example 3. I'd expect that "Dangerous query method" warning will no longer appear, because `sanitize_sql_for_order` already returns an `Arel::Nodes::SqlLiteral`.

https://github.com/rails/rails/blob/5-2-stable/activerecord/lib/active_record/sanitization.rb#L74

```ruby
def sanitize_sql_for_order(condition)
  if condition.is_a?(Array) && condition.first.to_s.include?("?")
    enforce_raw_sql_whitelist([condition.first],
      whitelist: AttributeMethods::ClassMethods::COLUMN_NAME_ORDER_WHITELIST
    )

    # Ensure we aren't dealing with a subclass of String that might
    # override methods we use (eg. Arel::Nodes::SqlLiteral).
    if condition.first.kind_of?(String) && !condition.first.instance_of?(String)
      condition = [String.new(condition.first), *condition[1..-1]]
    end

    Arel.sql(sanitize_sql_array(condition))
  else
    condition
  end
end
```

**Comment by rafaelfranca** [comment]
I'm not sure about this. @matthewd would know more about what is the expectation of that method. But for what I'm seeing, the behavior you are seeing is the behavior that was implemented. Mostly because `order` always call `sanitize_sql_for_order` so your example 3 is the same as:

```ruby
MyModel.order(["FIELD(id, ?)", featured_ids_array])
```

and that requires the string to be wrapped on `Arel.sql`. I believe the name `sanitize_sql_for_order` is just miss leading and I don't think it is intended to return a order clause that is free from SQL injection.

**Comment by januszm** [comment]
Thanks, I missed that part in `def order`:

```ruby
order_args.map! do |arg|
  klass.sanitize_sql_for_order(arg)
end
```

`MyModel.sanitize_sql_for_order` from my example can be removed.

Regarding the topic of this issue, which should now be changed to something like `"Dangerous query method" warning is triggered when passing Array Conditions to order`,
it seems that passing an Array Condition with "?", as an argument to `order` should not trigger the deprecation warning.
