### ISSUE TITLE
Missing documentation for `add_index`

### ISSUE THREAD

**Issue by achempion** [rails/rails#35991]
I've found out there is no mention of `algorithm: :concurrently` option in the [documentation](https://api.rubyonrails.org/classes/ActiveRecord/ConnectionAdapters/SchemaStatements.html#method-i-add_index) of `add_index` method.

Also, it'll be great to refer to the docs of `disable_ddl_transaction!` in addition to `:algorithm` option.

**Comment by itsWill** [comment]
Hey @achempion I agree we should probably document this one, I can take a stab at it, later on today.
