### ISSUE TITLE
Migration exception message is misleading and not accurate for foreign key errors

### ISSUE THREAD

**Issue by imechemi** [rails/rails#36013]
### Steps to reproduce
1. Create a new rails app using MySQL as database

        rails new sample_app -d mysql

2. Generate **User**  and **Account** model with migration as follows:
```ruby
class CreateUsers < ActiveRecord::Migration[5.2]
  def change
    create_table :users do |t|
      t.string :name
      
      t.timestamps
    end
  end
end
```

```ruby
class CreateAccounts < ActiveRecord::Migration[5.2]
  def change
    create_table :accounts do |t|
      t.references :user, foreign_key: true, index: true
      # t.references :category, foreign_key: true, index: true
      t.timestamps
    end
  end
end
```

As you can see, the reference column for category is commented in the migration. And we don't have categories table yet. 

3. Run db:migrate with the commented code, it works fine. 

        rails db:drop db:create db:migrate

4. Uncomment and re-run migrate again.

        rails db:drop db:create db:migrate

```log
Caused by:
ActiveRecord::MismatchedForeignKey: Column `user_id` on table `accounts` does not match column `id` on `users`, which has type `bigint(20)`. To resolve this issue, change the type of the `user_id` column on `accounts` to be :bigint. (For example `t.bigint :user_id`).
Original message: Mysql2::Error: Cannot add foreign key constraint: CREATE TABLE `accounts` (`id` bigint NOT NULL AUTO_INCREMENT PRIMARY KEY, `user_id` bigint, `category_id` bigint, `created_at` datetime NOT NULL, `updated_at` datetime NOT NULL,  INDEX `index_accounts_on_user_id`  (`user_id`),  INDEX `index_accounts_on_category_id`  (`category_id`), CONSTRAINT `fk_rails_b1e30bebc8`
FOREIGN KEY (`user_id`)
  REFERENCES `users` (`id`)
, CONSTRAINT `fk_rails_4031758f4d`
FOREIGN KEY (`category_id`)
  REFERENCES `categories` (`id`)
)
```

### Expected behavior
Exception with a message `categories table does not exist` 

### Actual behavior
Exception message blaming `user_id` column which works fine as we know.

### System configuration
**Rails version**:
5.2.3

**Ruby version**:
2.5.0

**Comment by imechemi** [comment]
I ran the sql in **rails dbconsole**, and now I seem to understand why error can't be accurate. 

```sql
mysql> CREATE TABLE `accounts` (`id` bigint NOT NULL AUTO_INCREMENT PRIMARY KEY, `user_id` bigint, `category_id` bigint, `created_at` datetime NOT NULL, `updated_at` datetime NOT NULL,  INDEX `index_accounts_on_user_id`  (`user_id`),  INDEX `index_accounts_on_category_id`  (`category_id`), CONSTRAINT `fk_rails_b1e30bebc8`
    -> FOREIGN KEY (`user_id`)
    ->   REFERENCES `users` (`id`)
    -> , CONSTRAINT `fk_rails_4031758f4d`
    -> FOREIGN KEY (`category_id`)
    ->   REFERENCES `categories` (`id`)
    -> );
ERROR 1215 (HY000): Cannot add foreign key constraint
```

It seems like the database itself does not have verbose information on the error. It just mentions `Cannot add foreign key constraint`. But, does rails by default blaming it on the first foreign key? i.e `user_id` in my case.

**Comment by kamipo** [comment]
Yes, for now Active Record assumes the cause of the foreign key constraint violation from the `CREATE TABLE` statement by the regex, so if the `CREATE TABLE` have multiple foreign key definitions it is hard to distinguish which definition (or both) is the cause.

**Comment by imechemi** [comment]
I think now the question would be "Why to give misinformation in this case?". I am sure many thoughts have gone into designing ActiveRecord to interface with various database systems and this isn't a critical issue or a bug, but would definitely save time to let the developer figure out the detail than to create confusion.

**Comment by kamipo** [comment]
It is just a bug, is not by design.

**Comment by yoones** [comment]
Digging on this issue, I find that it is specific to MariaDB. MySQL actually says `Mysql2::Error: Failed to open the referenced table 'some_table_name'`

**Comment by imechemi** [comment]
@yoones If this helps, I have shared what I used for reporting this issue:
```bash
➜  sample_app git:(master) ✗ mysql -u root -p
Enter password: 
Welcome to the MySQL monitor.  Commands end with ; or \g.
Your MySQL connection id is 712
Server version: 5.7.21 Homebrew

Copyright (c) 2000, 2018, Oracle and/or its affiliates. All rights reserved.

Oracle is a registered trademark of Oracle Corporation and/or its
affiliates. Other names may be trademarks of their respective
owners.

Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.

mysql>
```

**Comment by imechemi** [comment]
Yes, I am still able to reproduce this with the following configuration (same):

**Rails**: 5.2.3
**Ruby**: 2.5.3

Here is a fresh repo I've created to reproduce this issue: https://github.com/imechemi/sample_app
