### ISSUE TITLE
ArgumentError: Invalid route name, already in use: 'root' 

### ISSUE THREAD

**Issue by arni1981** [rails/rails#36020]
### Steps to reproduce
Upgraded my Gemfile to 6.0.0.beta3 and `bundle update` ran smoothly
Running `rails app:update` however stumbles with this error

> ArgumentError: Invalid route name, already in use: 'root' 

```
# routes.rb
root to: 'system/frontpage#index', constraints: lambda { |req| req.session[:user_id].nil? }
root to: 'welcome#index', constraints: lambda { |req| req.session[:user_id].present? }
```
### Expected behavior:
This should not cause an error I believe since this is a valid configuration and I haven't gotten this error before on previous versions.

### System configuration
**Rails version**:
6.0.0.beta3

**Comment by rafaelfranca** [comment]
This is a valid error. Before the `root_url` would be overridden by the last declaration, now Rails is telling you that you have this problem on your routes file and that you should chose a different name for one of them.

**Comment by arni1981** [comment]
Ok I see your point, these are however pointing to two different actions depending on logged in or not. A basic way of doing what Device gem does with

  authenticated :user do
    root 'secret#index', as: :authenticated_root
  end

  root "home#index"

Anyway, I'm not going to pursue this trivial case further, I know there are more pressing issues, Rails 6 is shaping up to be a great release :)

**Comment by sikachu** [comment]
You can work around this problem by override the path name of one of the route definition using `as: false`.

```ruby
root to: 'system/frontpage#index', constraints: lambda { |req| req.session[:user_id].nil? }
root to: 'welcome#index', constraints: lambda { |req| req.session[:user_id].present? }, as: false
```

This will prevent the "name collision" error to happen, and everything should work as normally as a call to `root_path` should still return `"/"` regardless if `session[:user_id]` is nil or not.

**Comment by arni1981** [comment]
@sikachu That's brilliant, thank you :)

**Comment by kalashnikovisme** [comment]
OR you can give names to your root routes. Something like that.

```ruby
root to: 'system/frontpage#index', constraints: lambda { |req| req.session[:user_id].nil? }, as: :system
root to: 'welcome#index', constraints: lambda { |req| req.session[:user_id].present? }, as: :welcome
```
