### ISSUE TITLE
Add fragment view rendering using Websocket (e.g. LiveView)

### ISSUE THREAD

**Issue by azbshiri** [rails/rails#36032]
We already have one of the most productive web frameworks why shouldn't we implement a killer feature like LiveView (Phoenix) easily on Rails?

 I'm happy to implement it but I have a couple of issues with `.html.erb` diffing, what do you think?

**Comment by azbshiri** [comment]
Sorry to mention you @dhh but I'm so curios to know your feedback on this if possible

Thanks

**Comment by simi** [comment]
from https://guides.rubyonrails.org/contributing_to_ruby_on_rails.html#what-about-feature-requests-questionmark

> If you'd like feedback on an idea for a feature before doing the work to make a patch, please send an email to the rails-core mailing list. 

Anyway I don't see any reason why to not built this as a gem first.

**Comment by rafaelfranca** [comment]
Closed since we don't take feature requests in the issue tracker.
