### ISSUE TITLE
When saving ActiveStorage record parent model previous_changes are empty in 6.0.0.rc1

### ISSUE THREAD

**Issue by artur79** [rails/rails#36035]
### Steps to reproduce

```[code=ruby]
  it 'test previous_changes issue rails5 != rails6' do
      user = create :user
      params = { email: 'foo@bar.com', avatar: avatar_uploaded_file }
      user.attributes = params
      user.save

      puts 'pc1: ' + user.previous_changes.inspect

      user = create :user
      params = { email: 'lorem@ipsum.com' }
      user.attributes = params
      user.save

      puts 'pc2: ' + user.previous_changes.inspect
   end
```
Avatar uploaded file is just the fixture loaded like:
```
   def avatar_uploaded_file
       Rack::Test::UploadedFile.new(picture_fixture_path, 'image/png')
   end
```

### Expected behavior
It should return previous changes for email in both cases.

### Actual behavior
Here is the spec output, in the first case when we change avatar together with email, email change is lost:

```
pc1: {}
pc2: {"email"=>["prev_email@foobar.com", "lorem@ipsum.com"], "updated_at"=>[Fri, 19 Apr 2019 10:26:17 UTC +00:00, Fri, 19 Apr 2019 10:26:17 UTC +00:00]}
```

### System configuration
**Rails version**:
6.0.0beta3, master 2733a68f8b8a
**Ruby version**:
2.6.1

**Comment by artur79** [comment]
Just tested and it still fails in 6.0.0.rc1

**Comment by nocivus** [comment]
Tested the same inside after_commit hook in a normal ActiveModel. No previous_changes are present, even though they are after the after_commit callback has ended (in rspec).

**Comment by ubugnu** [comment]
This issue is still present
