### ISSUE TITLE
--skip-activerecord not respected on rails master due to actionmailbox and actiontext dependencies

### ISSUE THREAD

**Issue by samphippen** [rails/rails#36030]
### Steps to reproduce
`rails new --skip-active-record` on master

### Expected behavior
No activerecord dependency to be loaded, because `config/database.yml` isn't created, if an eventual dependency exists, an `Could not load database configuration. No such file - [\"config/database.yml\"]` is created.

### System configuration
**Rails version**:
Master
**Ruby version**:
2.6

**Comment by y-yagi** [comment]
A newly generated application does not load `action_mailbox/engine` and `action_text/engine` when specied `--skip-activerecord` option.
https://github.com/rails/rails/blob/16dae7684edc480ee3fe65dfff8e19989402c987/railties/lib/rails/generators/rails/app/templates/config/application.rb.tt#L14-L15
https://github.com/rails/rails/blob/16dae7684edc480ee3fe65dfff8e19989402c987/railties/lib/rails/generators/app_base.rb#L238-L244 

Is this reproduced with the newly created application, and can you get a trace of the error in that case?

**Comment by samphippen** [comment]
this was due to RSpec weirdness.
