### ISSUE TITLE
Plucking associated data from an enum column returns nil

### ISSUE THREAD

**Issue by GBH** [rails/rails#36042]
Very confusing bug where values produced by a pluck return nils if attribute happens to be an enum. Here's conditions for it to happen:

- Parent model `Foo` needs to have enum column like `enum` with allowed values: `a, b, c`
- Related model `Bar` needs to have enum column **also** called `enum` but with **different** allowed values like `x, y, z`

When you try to pluck stuff, like `Foo.includes(:bars).pluck("bars.enum")` you are going to get all nils even though values are in the database. Generated SQL that can be observed in the logs is correct and should fetch actual values.

Here's a failing test:

```
# frozen_string_literal: true

require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  gem "rails", github: "rails/rails"
  gem "sqlite3"
end

require "active_record"
require "minitest/autorun"
require "logger"

# This connection will do for database-independent bug reports.
ActiveRecord::Base.establish_connection(adapter: "sqlite3", database: ":memory:")
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :posts, force: true do |t|
    t.string :status
  end

  create_table :comments, force: true do |t|
    t.integer :post_id
    t.string :status
    t.string :not_enum
  end
end

class Post < ActiveRecord::Base
  enum status: {
    a: "a",
    b: "b",
    c: "c"
  }
  has_many :comments
end

class Comment < ActiveRecord::Base
  enum status: {
    red: "red",
    green: "green",
    blue: "blue"
  }
  belongs_to :post
end

class BugTest < Minitest::Test
  def test_association_stuff
    post = Post.create!(status: "a")
    post.comments << Comment.create!(status: "blue", not_enum: "blue")
    
    expected = [["a", "blue", "blue"]]
    actual = Post.includes(:comments).pluck(:status, "comments.status", "comments.not_enum")
    assert_equal expected, actual
  end
end
```

```
Failure:
BugTest#test_association_stuff [untitled:59]:
Expected: [["a", "blue", "blue"]]
  Actual: [["a", nil, "blue"]]
```

I'm guessing there's some magic with pluck's allowed attributes and casting.

**Comment by st0012** [comment]
Your assumption is correct, let's look at this problem from different levels

1) the result from database is correct, this is the def of `pluck` method
```ruby
    def pluck(*column_names)
      ......

      if has_include?(column_names.first)
        relation = apply_join_dependency
        relation.pluck(*column_names)
      else
        klass.disallow_raw_sql!(column_names)
        relation = spawn
        relation.select_values = column_names
        # here's the raw result
        result = skip_query_cache_if_necessary { klass.connection.select_all(relation.arel, nil) }
        # here's the problem
        result.cast_values(klass.attribute_types)
      end
    end
```

And the result is correct

```
#<ActiveRecord::Result:0x00007facad3cae18
 @column_types={},
 @columns=["status", "status", "not_enum"],
 @hash_rows=nil,
 @rows=[["a", "blue", "blue"]]>
```

2) Let's check what `cast_values` does

```ruby
   def cast_values(type_overrides = {}) # :nodoc:
      ......

        types = columns.map { |name| column_type(name, type_overrides) } # see here

        rows.map do |values|
          Array.new(values.size) { |i| types[i].deserialize(values[i]) }
        end
    end
```

The problem here is that `result.columns` returns an array with only attribute names, like `["status", "status", "not_enum"]`. This makes Rails to cast `Comment`'s `status` with `Post`'s `status` attribute type since it doesn't know the `status` is from `Comment`

```
> result.send(:column_type, "status", klass.attribute_types).deserialize("a")
=> "a"
> result.send(:column_type, "status", klass.attribute_types).deserialize("blue")
=> nil
````

I haven't came up with any good colution for this though. I think it requires some more work to pass around the missing informations.

**Comment by albertoalmagro** [comment]
Link to [Ruby on Rails: core mail list discussion](https://groups.google.com/forum/#!topic/rubyonrails-core/Issh4-vyHrk) about this topic.

**Comment by st0012** [comment]
Update:

I asked for @matthewd's opinion few days ago, and he suggested that one possible direction is to only cast the original model's attributes (in this case, `Post`). And returning raw values for joined table attributes.

So it'd be something like

```ruby
Book.joins(:book_reviews).pluck(:status, "book_reviews.status") #=> [["written", 0]]
```

I think this is the most suitable approach, and I'm experimenting it right now.
