### ISSUE TITLE
Namespaced concerns seem to be broken in Rails 6

### ISSUE THREAD

**Issue by posiczko** [rails/rails#36054]
Hello,

Long time listener, first time caller.  I believe I found a small issue within Rails 6.

### Steps to reproduce

Including namespaced concern in `application_controller.rb` results in `uninitialized constant ApplicationController::Concerns`:

```ruby
# app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # include Bar
  include Concerns::Baz

  def foo
    puts "foo"
  end
end
```

with baz.rb being defined as:

```ruby
# app/controllers/concerns/baz.rb
require 'active_support/concern'

module Concerns
  module Baz
    extend ActiveSupport::Concern
    def baz_function
    end
  end
end
```

See [sample Rails 6 app](https://github.com/posiczko/bug-concerns-6) with a [commit introducing namespaced concern](https://github.com/posiczko/bug-concerns-6/commit/29d556dc2051a1f85fd998e229f9652caae45b04).

Non-namespaced concerns are working fine:

```
module Bar
  extend ActiveSupport::Concern

  def bar_function
  end
end
```

### Expected behavior

Tried to comb through the changelog, but I have not found any announced changes to the way concerns work:

IMHO, concerns should work the same way as they did in Rails 5, (see [identical sample Rails 5 app](https://github.com/posiczko/bug-concerns-5) working fine, not generating an error [introducing the namespaced concern](https://github.com/posiczko/bug-concerns-5/commit/70b36bf16c518a4b817b03f8ce0f0bf43c7318b6)).

### Actual behavior

Including namespaced concerns via `include Concerns::Baz` should work, right?

```log
Puma caught this error: uninitialized constant ApplicationController::Concerns
Did you mean?  Concurrent (NameError)
/Users/pablo/Projects/example-concerns-6/app/controllers/application_controller.rb:4:in `<class:ApplicationController>'
/Users/pablo/Projects/example-concerns-6/app/controllers/application_controller.rb:2:in `<main>'
/Users/pablo/.rbenv/versions/2.6.2/lib/ruby/gems/2.6.0/gems/bootsnap-1.4.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require'
/Users/pablo/.rbenv/versions/2.6.2/lib/ruby/gems/2.6.0/gems/bootsnap-1.4.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `block in require_with_bootsnap_lfi'
/Users/pablo/.rbenv/versions/2.6.2/lib/ruby/gems/2.6.0/gems/bootsnap-1.4.3/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
/Users/pablo/.rbenv/versions/2.6.2/lib/ruby/gems/2.6.0/gems/bootsnap-1.4.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `require_with_bootsnap_lfi'
/Users/pablo/.rbenv/versions/2.6.2/lib/ruby/gems/2.6.0/gems/bootsnap-1.4.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
/Users/pablo/.rbenv/versions/2.6.2/lib/ruby/gems/2.6.0/gems/zeitwerk-1.4.3/lib/zeitwerk/kernel.rb:16:in `require'
/Users/pablo/.rbenv/versions/2.6.2/lib/ruby/gems/2.6.0/gems/activesupport-6.0.0.beta3/lib/active_support/dependencies.rb:297:in `block in require'
...
```

### System configuration
**Rails version**: 2.6.2

**Ruby version**: 6.0.0beta3

Thank you for all the work on Rails!

Pawel

**Comment by kaspth** [comment]
I'm surprised `Concerns` works on older Rails versions! — and the fact that it did seems incidental. Since `app/controllers/concerns` is in Rails' `autoload_paths` that folder is a root to load constants from. For example, `app/models` is in `autoload_paths` too which is why we write plain `Post` instead of `Models::Post`. This is specifically about namespacing with the name `Concerns`, I doubt you'd see a problem with `Namespaced::Baz` in `app/controllers/concerns/namespaced/baz.rb`.

If you really want to keep the `Concerns` namespace, you can either remove the directory from `autoload_paths` or add `app/controllers/concerns/concerns/baz.rb` 😅

In Rails 6 @fxn added Zeitwerk for autoloading, which a new Rails 6 generated app uses automatically.
Perhaps the old `ActiveSupport::Dependencies` auto-defines a `Concerns` module on Rails 5.2? @fxn can you confirm this theory?

=========================

I'll close for now since the usage example wasn't correct on Rails 5.2, sorry!

**Comment by fxn** [comment]
@kaspth exactly.

In `:classic` mode, `Concerns` works as a side-effect of the implementation of dependencies.rb, but it was not an intended usage. I checked a while back about their introduction, and nesting them as autoload paths within other autoload paths was an overlook indeed.

In `:zeitwerk` mode, this anomaly has [explicit support](https://github.com/fxn/zeitwerk/blob/6fbfd8e559a0cc37516eb540668099aed831d421/lib/zeitwerk/loader.rb#L466-L472). On one hand Zeitwerk, supports nested autoload paths (would not have added this feautre without the existence of concerns in Rails). On the other hand, the compromise is that you cannot use `Concerns` as a namespace.

This was mentioned in the [Backwards Compatibility](https://weblog.rubyonrails.org/2019/2/22/zeitwerk-integration-in-rails-6-beta-2/#backwards-incompatibility) section of the annoucement blog post, and will be also mentioned in the upgrading guide or autoloading guide.

**Comment by kaspth** [comment]
> This was mentioned in the [Backwards Compatibility](https://weblog.rubyonrails.org/2019/2/22/zeitwerk-integration-in-rails-6-beta-2/#backwards-incompatibility) section of the annoucement blog post, and will be also mentioned in the upgrading guide or autoloading guide.

Nice! With specific mention of `Concerns` as the very first item 😄

**Comment by posiczko** [comment]
Many thanks for taking time to look at it and pointing me to the right changelog.  😄

**Comment by kul1** [comment]
@kaspth "If you really want to keep the Concerns namespace, you can either remove the directory from autoload_paths or add app/controllers/concerns/concerns/baz.rb 😅"

What file/directory you mean to "remove" 
In case I want include all method in concern directory files.
Right it worked in Rails 5.2 but not in 6.0.3
Thanks

**Comment by prateekvyas2121** [comment]
so the conncludion is 'Concerns::SomeConstant' will be treated like 'SomeConstant'!
it took me almost an hour to figure this out, may be disadvantages of not learning the documentation first LoL
