### ISSUE TITLE
rails new with --skip-javascript still generates JS related code

### ISSUE THREAD

**Issue by namiwang** [rails/rails#36050]
### Steps to reproduce

1. rails new --skip-javascript test

### Expected behavior

- no webpacker related code generated

### Actual behavior

- webpacker still occurs in `Gemfile`
- still got `javascript/packs/application.js`
- javascript_pack_tag still takes place in `layout/application.erb.html`

### System configuration
**Rails version**:

6.0.0.beta3

**Ruby version**:
2.6.2

**Comment by prathamesh-sonpatki** [comment]
The command should be used as `rails new APP_PATH [options]` If the options are given before the APP_PATH, it does not work as expected.
