### ISSUE TITLE
Rails new fails with bootsnap error on webpacker install

### ISSUE THREAD

**Issue by sblackstone** [rails/rails#36068]
### Summary
Running ```rails new blarg``` causes an error when webpacker tries to install.

I was able to work around this by removing ```require: false``` from the Gemfile entry for ```bootsnap``` and then manually doing ```rails webpacker:install``` and ```rails webpacker:install:react```

### Steps to reproduce

rails new blarg

.railsrc:
```
--skip-turbolinks
--skip-coffee
--skip-spring
-d mysql
--webpack=react
```

### Expected behavior
It should install successfully..

### Actual behavior
```
       rails  webpacker:install
Traceback (most recent call last):
	3: from bin/rails:3:in `<main>'
	2: from bin/rails:3:in `require_relative'
	1: from /Users/sblackstone/code/blarg/config/boot.rb:4:in `<top (required)>'
/Users/sblackstone/code/blarg/config/boot.rb:4:in `require': cannot load such file -- bootsnap/setup (LoadError)
       rails  webpacker:install:react
Traceback (most recent call last):
	3: from bin/rails:3:in `<main>'
	2: from bin/rails:3:in `require_relative'
	1: from /Users/sblackstone/code/blarg/config/boot.rb:4:in `<top (required)>'
/Users/sblackstone/code/blarg/config/boot.rb:4:in `require': cannot load such file -- bootsnap/setup (LoadError)
```
### System configuration
**Rails version**: 5.2.3

**Ruby version**: 2.6.2

Bundler version 1.17.2

**Comment by y-yagi** [comment]
I can't reproduce in my environment with those options. Is this reproduce? And what is your OS?

**Comment by waiting-for-dev** [comment]
I think this happens when you run `rails new` with `--skip-bundle` but without `--skip-webpack-install`
