### ISSUE TITLE
Rails assets javascript stacktrace / debugging

### ISSUE THREAD

**Issue by ndvbd** [rails/rails#36062]
When there is an exception in javascript (which was precompiled, on production environment), and we set a global exception handler (onerror), we get the filename of the problematic script (which is the bundled .js asset) and the line number and column.

The problem is, that it's very hard to get from the line/col, since the file is minified (or uglified, in production) back to which source file and line is the problematic one.

We need a simple option, to run the 
`bundle exec rake assets:precompile RAILS_ENV=production`
again, but this time specify line+col, and then the rake will output what is the source file + line which corresponds to that asset line+col. This way we can easily debug exceptions that are being catched on the client side (and that are sent to the server for monitoring purposes).

Is there such thing?

**Comment by rafaelfranca** [comment]
Please use StackOverflow for questions/help, where a wider community will be able to help you. We reserve the issues tracker for issues only.
