### ISSUE TITLE
AR PG opclass schema dumper regex extracts wrong opclass when opclass does not end with _ops

### ISSUE THREAD

**Issue by zealot128** [rails/rails#36075]
### Steps to reproduce

- install an postgresql extension, like proonga, https://pgroonga.github.io/ that uses a special type of opclass, that name does not end with "_ops"
- create index 
```
add_index :autocomplete_terms, "word", 
  opclass: :pgroonga_text_term_search_ops_v2, 
  using: "pgroonga", 
  name: :autocomplete_terms_fti
```
- migrate/schema:dump/run tests - wrong opclass is dumped and used (pgroonga_text_term_search_ops). That opclass does not exists and produces other errors.

### Expected behavior

db/schema reproduces line from migration, like:

```
t.index ["word"], name: "autocomplete_terms_fti", opclass: :pgroonga_text_term_search_ops_v2, using: :pgroonga
```

### Actual behavior

db/schema includes just "proonga_text_term_search_ops", an opclass that does not exists and produces errors later on:

```
t.index ["word"], name: "autocomplete_terms_fti", opclass: :pgroonga_text_term_search_ops, using: :pgroonga
```

### System configuration

**Rails version**: 5.2.1.latest
**Ruby version**: 2.5

After doing a little bit of digging, I think the regex in 

https://github.com/rails/rails/blob/master/activerecord/lib/active_record/connection_adapters/postgresql/schema_statements.rb#L127 is the reason, that Regex just looks for everything ending in "_ops".

In my scenario, changing the regex to:

```/(?<column>\w+)\s?(?<opclass>\w+_ops(_\w+)?)?\s?(?<desc>DESC)?\s?(?<nulls>NULLS (?:FIRST|LAST))?/``` 

fixes the problem.  (adding the group (_\w+)? right after ops).
Not sure about the ramifications for other codes or which test to a add.

**Comment by zealot128** [comment]
Problem is still present in 5.2

**Comment by matt17r** [comment]
🤔 Rather than using a regex to infer what the opclass is by parsing the output of [pg_get_indexdef(index_oid)](https://www.postgresql.org/docs/9.5/functions-info.html), is it possible to query it explicitly?

**Comment by keineahnung2345** [comment]
As an expediancy, I directly edit `db/schema.rb`, add `pgroonga_text_term_search_ops` with `_v2` suffix, then run my `RAILS_ENV=production rake db:reset DISABLE_DATABASE_ENVIRONMENT_CHECK=1 --trace` again to solve my problem.
