### ISSUE TITLE
6.0.0.rc1 database.yml no longer supports arbitrary ERB output?

### ISSUE THREAD

**Issue by anamba** [rails/rails#36088]
### Steps to reproduce

For many years, I have had a line like this in my `database.yml`:
```
  <%= ENV['MYSQL_HOST'] ? 'host: ' + ENV['MYSQL_HOST'] : 'socket: /var/run/mysqld/mysqld.sock' %>
```

Now, that works most of the time, except when using rake tasks in the db namespace:

```
rails db:migrate
rails aborted!
Psych::SyntaxError: (<unknown>): could not find expected ':' while scanning a simple key at line 6 column 3
/usr/local/rvm/gems/ruby-2.6.2/gems/railties-6.0.0.rc1/lib/rails/application/configuration.rb:207:in `load_database_yaml'
...
```
Where `line 6 column 3` refers to the line excerpted above.

This appears to be related to #35497.

### Expected behavior

Previously, this used to output a host key and value when `ENV['MYSQL_HOST']` is set and a socket key and value otherwise.

### Actual behavior

`Psych::SyntaxError` shown above.

I know I can work around this, but reading through the PR made me think that this is probably going to bite other people as well, so I thought I'd open an issue.

### System configuration

**Rails version**: 6.0.0.rc1

**Ruby version**: 2.6.2

**Comment by rafaelfranca** [comment]
is:

```
foo: dummy_key: dummy_value
```

valid yaml? If it is we can make the `DummyERBCompiler` always return `"dummy_key: dummy_value"`
