### ISSUE TITLE
ActiveSupport::Autoload same name different name space conflict

### ISSUE THREAD

**Issue by jonstorer** [rails/rails#36085]
### Steps to reproduce
```ruby
module Auth
  extend ActiveSupport::Autoload

  eager_autoload do
    autoload_under "o_auth2" do
      autoload :Grant
      autoload :Response

      autoload_under "o_auth2/grant" do
        autoload :AuthorizationCode
      end

      autoload_under "o_auth2/response" do
        autoload :AuthorizationCode
      end
    end
  end

  eager_load!
end

throw "fail" unless Auth::OAuth2::Grant.const_defined?("AuthorizationCode")
```
### Expected behavior
Constants with the same name in different namespaces should autoload correctly.

### Actual behavior
Loading constants with the same name, but in two namespaces fails.

In this situation, Auth::OAuth2::Response::AuthorizationCode will load & Auth::OAuth2::Grant::AuthorizationCode will not load. The hash in `@_autoloads` is overwriting the first entry for `AuthorizationCode` when the constant with the same name is autoloaded from a different namespace.

### System configuration
**Rails version**:
5.2.2.1
**Ruby version**:
2.5.1p57

**Comment by rafaelfranca** [comment]
`autoload_under` just change the path where the constant will be autoload, it doesn't set the namespace of the constant so either, so both calls to `autoload :AuthorizationCode` are defining the same constant, `Auth::AuthorizationCode`

**Comment by jonstorer** [comment]
@rafaelfranca not true. The constants have different files paths to load from.

**Comment by jonstorer** [comment]
@rafaelfranca Here's some sample code showing the issue. https://github.com/jonstorer/autoload
