### ISSUE TITLE
Bundler could not find compatible versions for gem "activemodel":

### ISSUE THREAD

**Issue by oystersauce8** [rails/rails#36084]
As of today, I'm seeing this when doing a new rails application using the github master branch:
 
Bundler could not find compatible versions for gem "activemodel":
  In Gemfile:
    rails was resolved to 6.1.0.alpha, which depends on
      activemodel (= 6.1.0.alpha)
    web-console was resolved to 3.7.0, which depends on
      activemodel (>= 5.2)

Any ideas..

**Comment by rafaelfranca** [comment]
Rails master is not 6.1 and your gems probably don't support Rails 6.1 just yet. You can change to the 6-0-stable branch.
