### ISSUE TITLE
uninitialized constant UniformNotifier::HoneybadgerNotifier::Honeybadger

### ISSUE THREAD

**Issue by elduglas** [rails/rails#36096]
### Steps to reproduce

- rails active_storage:install
- rails db:migrate

```
Model:   has_many_attached :photos
Controller: photos: [] to permit (pet_params)
Form: = f.file_field :photos, class: 'form-control', multiple: true   
Show: - @pet.photos.each do |photo|
            = image_tag photo
```

![image](https://user-images.githubusercontent.com/9750729/56757854-dcc31200-675a-11e9-9f8d-232c7caffb1f.png)

### Expected behavior

![image](https://user-images.githubusercontent.com/9750729/56758090-5f4bd180-675b-11e9-9b3c-88f09c35d553.png)

### Actual behavior

![image](https://user-images.githubusercontent.com/9750729/56758117-74286500-675b-11e9-9ade-03ddfc7e7f51.png)

### System configuration
**Rails version**: 5.3.2

**Ruby version**: 2.5.3 and tested with ruby 2.6.0

**Comment by fxn** [comment]
The constants that are not found do not seem to belong to Rails.

Can you share the source code of `UniformNotifier` and `UniformNotifier::HoneybadgerNotifier`? Does `Honeybadger` (the constant not found) belong to some namespace?

**Comment by elduglas** [comment]
> The constant that is not found does not seem to belong to Rails.
> 
> Can you share the source code of `UniformNotifier` and `UniformNotifier::HoneybadgerNotifier`? Does `Honeybadger` (the constant not found) belong to some namespace?

Hi fxn.

This is the project
https://github.com/helpetproject/webapp/blob/i5/

https://github.com/helpetproject/webapp/blob/i5/app/controllers/pets_controller.rb
https://github.com/helpetproject/webapp/blob/i5/app/models/pet.rb
https://github.com/helpetproject/webapp/blob/i5/app/views/pets/show.html.haml

I don't use UniformNotifier

**Comment by flyerhzm** [comment]
@elduglas what's your bullet configs?

If you don't use honey_badger, please don't enable it.
