### ISSUE TITLE
Truncate helper doesn't always return frozen string

### ISSUE THREAD

**Issue by jordanthomas** [rails/rails#36106]
### Steps to reproduce
```ruby
"foobar".truncate(6).frozen?
=> false
"foobar".truncate(5).frozen?
=> true
```

### Expected behavior
Strings returned from `truncate` (or any ActionView helper) should consistently return a frozen string.

### Actual behavior
When the string is not long enough to be truncated the original, unfrozen, string is returned. When it is long enough to be truncated a new frozen string is returned. 

### System configuration
**Rails version**: 5.2.3

**Ruby version**:  2.5.3

**Comment by rafaelfranca** [comment]
That makes sense. Mind to open a PR?

**Comment by jordanthomas** [comment]
I'll give it a shot! It's been a couple years. ;)
