### ISSUE TITLE
Zeitwerk breaks override pattern

### ISSUE THREAD

**Issue by jasl** [rails/rails#36100]
### Steps to reproduce

Follow <https://edgeguides.rubyonrails.org/engines.html#overriding-models-and-controllers> create an override (monkey patch) for a class

This works before 6.0.0.rc1 (including 6.0.0.beta2, 6.0.0.beta3)

### Expected behavior

Class should be patched

### Actual behavior

```
/Users/jasl/.rvm/gems/ruby-2.6.3/gems/zeitwerk-2.1.5/lib/zeitwerk/loader/callbacks.rb:15:in `on_file_autoloaded': expected file /Users/jasl/Workspaces/Ruby/cybros/app/overrides/doorkeeper/application_override.rb to define constant Doorkeeper::ApplicationOverride, but didn't (NameError)
```

### System configuration

**Rails version**: 6.0.0.rc1

**Ruby version**: 2.6.3

**Comment by jasl** [comment]
@fxn could you please to give some advice?

**Comment by fxn** [comment]
Could you please try adding this?

```ruby
# config/application.rb
load_defaults "6.0"
Rails.autoloaders.main.ignore("#{Rails.root}/app/overrides")
```

?

**Comment by jasl** [comment]
@fxn 
Thank you, It works!
I'll send a PR to update the doc

**Comment by fxn** [comment]
Awesome!

**Comment by aleksandrs-ledovskis** [comment]
>  I'll send a PR to update the doc

Didn't seem to happen. @fxn's suggested fix needs broader exposure as `Rails.autoloaders.main.ignore` isn't adequately documented anywhere else.

**Comment by jasl** [comment]
> > I'll send a PR to update the doc
> 
> Didn't seem to happen. @fxn's suggested fix needs broader exposure as `Rails.autoloaders.main.ignore` isn't adequately documented anywhere else.

It happened long ago, but didn't merge yet, see #36102

**Comment by aleksandrs-ledovskis** [comment]
@jasl Thanks for pointing out the link I've missed
