### ISSUE TITLE
Rails Choosing wrong controller action

### ISSUE THREAD

**Issue by shivendrasape** [rails/rails#36101]
I made GET request with the following url in postman

`localhost:8091/trade/search?side=SELL`

### Expected behavior
Rails should have triggered searchTrade action
`get '/trade/search/:commodity/:side/:counterparty/:location' => 'tradeservice#searchTrade'`

### Actual behavior
Rails misinterpreted the route as: 
`match '/trade/:id', to: 'tradeservice#getTradeById', via: :get`

### Logs
![image](https://user-images.githubusercontent.com/33520090/56786164-94b4f580-6815-11e9-8fef-63888c868e64.png)

### System configuration
**Rails version**:
5.1.7
**Ruby version**:
2.3.3.p222

This is definitely a bug, how do i fix this ??

**Comment by sikandartariq1** [comment]
It seems like change in the route order will resolve the issue... 
I believe currently you have this order 
```
match '/trade/:id', to: 'tradeservice#getTradeById', via: :get
get '/trade/search/:commodity/:side/:counterparty/:location' => 'tradeservice#searchTrade'
```
try revesing the order like this 
```
# put trade/search above trade/:id
get '/trade/search/:commodity/:side/:counterparty/:location' => 'tradeservice#searchTrade'
match '/trade/:id', to: 'tradeservice#getTradeById', via: :get
```

**Comment by shivendrasape** [comment]
@sikandartariq1 already tried this .. still didn't worked :(

**Comment by sikandartariq1** [comment]
I get it...
you have mentioned `:commodity/:side/:counterparty/:location` these parameters but not passing them in url
try this url in postmn `http://localhost:8091/trade/search/1/1/1/1`

**Comment by shivendrasape** [comment]
@sikandartariq1  thats right, i purposefully have done that, these params should be optional. I can pass any one, all or none, or any number of params. The api is used for search feature.

**Comment by sikandartariq1** [comment]
as in the screenshots, you're passing `side` as a query string and as you said all of them are optional so I think it'll be fine for you to just remove  `:commodity/:side/:counterparty/:location` segments from route and pass them as query string.
`get '/trade/search/', to: 'tradeservice#searchTrade'`
important is that you place this above `tade/:id` route

**Comment by shivendrasape** [comment]
@sikandartariq1  that's good idea, can point me to relevant docs ? so that i can pass them as query strings.
Thanks. 
You can close this issue. 👍

**Comment by kaspth** [comment]
Just to sum this up. There's no bug here.

Your route has four required parameters (`:commodity` etc.):

```ruby
get '/trade/search/:commodity/:side/:counterparty/:location' => 'tradeservice#searchTrade'
```

Rails can't match `/trade/search?bla=bla` because it doesn't have the 4 required parameters.

In Rails/Ruby camelcasing is generally discouraged. And Rails has conventions for the route naming, you can get Rails' standard naming with the below. E.g. pluralize controller names, use `show` for `getTradeById`, call `searchTrade` just `search`.

```ruby
resources :tradeservices, path: 'trade', only: :show do
  get :search, on: :collection
end

# Generates:
#               Prefix Verb URI Pattern             Controller#Action
# search_tradeservices GET  /trade/search(.:format) tradeservices#search
#         tradeservice GET  /trade/:id(.:format)    tradeservices#show
```

@sikandartariq1 thanks for jumping in too!
