### ISSUE TITLE
Timezone for Volgograd should be UTC +04:00, not  UTC +03:00

### ISSUE THREAD

**Issue by deda** [rails/rails#36119]
### Steps to reproduce
rake time:zones:all

### Expected behavior
ActiveSupport should return UTC +04:00 timezone  for Volgograd according to 
[time zone update](https://time.is/time_zone_news/volgograd_will_jump_one_hour_ahead)

### Actual behavior
rake time:zones:all
_skipped_ 
* UTC +03:00 *
Baghdad
Istanbul
Kuwait
Minsk
Moscow
Nairobi
Riyadh
St. Petersburg
**Volgograd**

* UTC +03:30 *
Tehran

* UTC +04:00 *
Abu Dhabi
Baku
Muscat
Samara
Tbilisi
Yerevan
### System configuration
**Rails version**:
Rails 5.2.3
**Ruby version**:
ruby 2.6.2p47 (2019-03-13 revision 67232) [x86_64-linux]

**Comment by y-yagi** [comment]
Rails don't have Time Zone data itself. In the case of Linux, it depends on Time Zone Data holds by Linux.  

```
$ zdump Europe/Volgograd
Europe/Volgograd  Fri May  3 04:48:34 2019 +04  

$ ./bin/rails r 'p ActiveSupport::TimeZone.new("Volgograd").formatted_offset'
"+04:00"
```

Probably Timezone Data is old in your env. Please update data.
