### ISSUE TITLE
[actionview] content_for / content_for? / yield don't act correctly on non-strings

### ISSUE THREAD

**Issue by localhostdotdev** [rails/rails#36114]
### Steps to reproduce

- have `content_for(:something} { false }`, or `{}`, `{ a: 1 }`, `[1, 2, 3]`, etc. in a view
- call `content_for(:something)` or `yield(:something)`
- see `nil` and `""` respectively

more examples at: https://gist.github.com/localhostdotdev/0e81e6f0a5ba662fe040cc1f2f99b84f

full repo: https://github.com/localhostdotdev/bug/tree/content-for-false

### Expected behavior

see what was passed in the block (not sure about when it's not "present?" but would expect to receive even "blank?" values)

### Actual behavior

ignores anything that isn't a "present?" string

### System configuration

**Rails version**: rails 6.0.0.beta3 and rails 6.0.0.rc1

**Ruby version**: ruby 2.6.2p47 (2019-03-13 revision 67232) [x86_64-darwin17]

------

initially saw it because my view wasn't picking on a `false` value, then realized it generalizes to other cases.

documentation: [ActionView/Helpers/CaptureHelper](https://edgeapi.rubyonrails.org/classes/ActionView/Helpers/CaptureHelper.html) (doesn't mention it)

the code has things like `if content` and `@view_flow.get(name).present?`.

maybe the instance variable approach is better suited but I liked the idea of the `content_for` / `yield` better.

**Comment by rafaelfranca** [comment]
This is the expected behavior. It is a method to use stored content to be displayed in the view, if there is no content to be displayed in the view it will not return anything. Thank you for the issue.

**Comment by rafaelfranca** [comment]
As per documentation it say: `Calling content_for stores a block of markup in an identifier for later use.`. So if there is no markup it is not stored.

**Comment by localhostdotdev** [comment]
should be named `html_content_for` then
