### ISSUE TITLE
Installation instructions using Tokaido should not be described

### ISSUE THREAD

**Issue by shingonnw** [rails/rails#36118]
### Expected behavior
When installing Rails with getting started guide, latest version should be installed.

### Actual behavior
When installing using "Tokaido", it was installed with Rails 4.2.1.

I expected to be able to install the latest version,
Please review the description of the installation procedure.

**Comment by yoones** [comment]
Shouldn't this issue be opened on https://github.com/tokaido/tokaidoapp/issues ?

**Comment by prathamesh-sonpatki** [comment]
Yup, please open issue on https://github.com/tokaido/tokaidoapp. This issue is not Rails codebase related.

**Comment by okuramasafumi** [comment]
I kinda disagree.
Tokaido's last commit was 4 years ago, which means they probably won't update anymore.
Using `gem i rails` makes perfect sense, so it seems removing Tokaido is reasonable.

**Comment by androbtech** [comment]
Sorry about that! 

Six Tokaido Releases today (Ruby 2.4.3, 2.5.5, and 2.6.3). Rails 5.1.7 for each one as well as Rails 5.2.3. Go to releases page and pick any.

What version of Rails are you looking to get up and running?

**Comment by shingo-nakanishi** [comment]
@androbtech  You are mistaken for a mention. Right is @shingonnw.

**Comment by okuramasafumi** [comment]
@androbtech Thanks for your work!

**Comment by shingonnw** [comment]
@androbtech Thank you for your work and response!
I choose Tokaido 2.6.1. (Ruby 2.6.3, Rails 5.2.3)

**Comment by androbtech** [comment]
> @androbtech Thank you for your work and response!
> I choose Tokaido 2.6.1. (Ruby 2.6.3, Rails 5.2.3)

Please [read this](https://github.com/tokaido/tokaidoapp/issues/88) @shingonnw . Sorry about that.
