### ISSUE TITLE
problem with local date thats possibly empty

### ISSUE THREAD

**Issue by micha2261** [rails/rails#36123]
in a view i have a date field "date_fulfilled".
It is displayed localized; with the "l".
<pre>
   <p>
    <strong>eingelöst am: </strong>
    <%= l @recipe.date_fulfilled %>
  </p>
</pre>

### Expected behavior
When this field is empty there should be an empty field displayed

### Actual behavior
I get the following error:
Object must be a Date, DateTime or Time object. nil given.
Extracted source (around line #29): 
29 | <%= l @recipe.date_fulfilled %>

### System configuration
**Rails version**: Rails 5.2.3

**Ruby version**: ruby 2.5.1p57 (2018-03-29 revision 63029) [x86_64-linux-gnu]

**Comment by composerinteralia** [comment]
I think that is the expected behavior. You can use `<%= l @recipe.date_fulfilled, default: nil %>` if you want to default to showing nothing. See https://github.com/ruby-i18n/i18n/blob/master/test/i18n_test.rb#L313-L319 for details.
