### ISSUE TITLE
The validations of an association, which is self-join relation, always raise errors

### ISSUE THREAD

**Issue by flavono123** [rails/rails#36138]
### Steps to reproduce
In self-reference with a table, the creation of invalid association must raise errors even the option `dependent: :restirct_with_error` is on.

Run the following script:
https://gist.github.com/flavono123/e1aed1ffb71da626ead325c4b132bd29

### Expected behavior
Without rasing an error, `post1.errors` exists, since the option `dependent: :restirct_with_error`

### Actual behavior
The exception raised:
```
E

Error:
BugTest#test_association_stuff:
ActiveRecord::RecordInvalid: Validation failed: Child post has already been taken
```
---
In this case, I think it runs in the following condition:
https://github.com/rails/rails/blob/83f7c25dfc441945dfc9eaab7e7880da24d3c026/activerecord/lib/active_record/associations/has_many_through_association.rb#L27-L29

### System configuration
**Rails version**:
5.2.3
**Ruby version**:
2.6.2

**Comment by j1hwang** [comment]
`restrict_with_error` 가 있으면 relation 삭제 등에는 raise 를 하는 것으로 알고 있었는데, 예시로 들어주신 경우에는 raise 를 하는 것이 잘못된 동작인가요?
