### ISSUE TITLE
Use of monotonic_time in ActiveSupport::Notifications is a breaking change

### ISSUE THREAD

**Issue by cpruitt** [rails/rails#36145]
PR https://github.com/rails/rails/pull/35984 ("Various fixes in ActiveSupport::Notifications::Event") changes `ActiveSupport::Notifications::Fanout::Subscribers::Timed` to use `Concurrent.monotonic_time` (`Float`) for start and end values. Previously instances of `Time` were used.

Although I agree that monotonic time is probably the best way to track the passage of elapsed time, at GitHub we are finding this to be a pretty significant breaking change.

The values for event start / end times are used as Time instances in our app in various ways apart from just calculating event difference (duration) between the two values. For example, in some cases the start/end Time values are stored as information in background Jobs which then use the values as event time information to perform work when the job is run. This presents multiple problems.

* First, monotonic time only represents elapsed time, not wall-clock time. The use of these values as `Time` instances elsewhere in our codebase either yields incorrect values or raises errors and there is no good way to convert from the monotonic float back to a `Time` value.

* Second, if one were to attempt to recalculate an approximate `Time` instance from a monotonic time `Float` value stored in a Job, we can't ever have reasonable assurance that the job is running on the same machine that generated the value, nor that the machine hasn't had it's monotonic clock starting point reset.

* At this point the Edge Rails API documentation still indicates that `start` and `finish` are `Time` objects indicating "Time, when the instrumented block started|ended execution". I think it's reasonable to assume that they may be being used as such by applications (GitHub included).

I'm open to suggestions & welcome ideas but I think my suggestion would be to roll back the above PR, restoring the previous behavior, and provide a separate opt-in means or API for using monotonic time. There was some discussion here about subclassing `ActiveSupport::Notifications::Fanout::Subscribers::Timed` with a new `ActiveSupport::Notifications::Fanout::Subscribers::MonotonicTimed` class, as well as providing a `ActiveSupport::Notifications.monotonic_subscribe` method to take advantage of it. Alternatively we might just add a flag parameter to the existing `subscribe` but that might make things less clear and complicate the method signature a bit.

CC @ksolo, @eileencodes for visibility

**Comment by vishaltelangre** [comment]
I am working on a PR to introduce `ActiveSupport::Notifications::Fanout::Subscribers::MonotonicTimed` along with `ActiveSupport::Notifications.monotonic_subscribe` as discussed here.
