### ISSUE TITLE
ActiveStorage attached file not found in after_create

### ISSUE THREAD

**Issue by thomasdarde** [rails/rails#36141]
### Steps to reproduce

When trying to update to rails 6 rc1 we found an issue with the code below.
In rails 5 we used include ActiveStorage::Downloading but it is now removed , this is the only change

``
class ImportedFile < ApplicationRecord
  has_one_attached :file
  after_create :use_file

def use_file
      self.file.blob.open { |file| file.path }
end

end
``

### Expected behavior
We sould be able to use the file in the after_create (service is :test or :disk) ?
Or do we have to wait for another callback completion ?

### Actual behavior
ActiveStorage::FileNotFoundError is thrown

### System configuration
**Rails version**: 6.0.0-rc1

**Ruby version**: 2.5.1

**Comment by georgeclaghorn** [comment]
> Or do we have to wait for another callback completion ?

You have to wait until after the transaction commits via `after_create_commit`. Attached files are uploaded to storage after commit as of #33303.

**Comment by sofianeOuafir** [comment]
even when using ``after_create_commit`` it doesn't work. I get the following error OpenURI::HTTPError Exception: 404 Not Found.
```
 after_create_commit :foo

def foo
open(file.service_url)
end 
```

**Comment by nelyj** [comment]
hey @sofianeOuafir you can fixed this issue with this https://github.com/rails/rails/issues/37304#issuecomment-546246357
