### ISSUE TITLE
Integration test errors raise instead of responding with 500 page

### ISSUE THREAD

**Issue by sambostock** [rails/rails#36156]
### Steps to reproduce

Create and route to a controller action which raises.

<details><summary>Reproduction code</summary>

```ruby
# frozen_string_literal: true

require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  gem "rails", github: "rails/rails"
end

require "action_controller/railtie"

class TestApp < Rails::Application
  config.root = __dir__
  config.hosts << "example.org"
  secrets.secret_key_base = "secret_key_base"

  config.logger = Logger.new($stdout)
  Rails.logger  = config.logger

  routes.draw do
    get "/raise_error" => "test#raise_error"
    get "/render_error" => "test#render_error"
  end
end

class TestController < ActionController::Base
  include Rails.application.routes.url_helpers

  def raise_error
    raise 'boom'
  end

  def render_error
    render plain: 'error', status: :internal_server_error
  end
end

require "minitest/autorun"
require "rack/test"

class BugTest < Minitest::Test
  include Rack::Test::Methods

  def test_raise_error_responds_with_error
    get "/raise_error"
    refute last_response.ok?
  end

  def test_render_error_responds_with_error
    get "/render_error"
    refute last_response.ok?
  end

  private

  def app
    Rails.application
  end
end
```

</details>

### Expected behavior

The error should cause a `500 Internal Server Error` response, which could be checked for via `assert_response :error`.

### Actual behavior
The error bubbles up into the test, and must be checked for via `assert_raises`, which is not the desired test behaviour.

### System configuration
**Rails version**:
- `6.1.0.alpha` (`master`)
- `5.2.3`

**Ruby version**:
- `2.5.3`

**Comment by rafaelfranca** [comment]
That is the desired behavior depending on your configuration in `config/environments/test.rb`. If you set [this config](https://github.com/rails/rails/blob/51a481fa7400772ca23c0e8e658523d78f8d8305/railties/lib/rails/generators/rails/app/templates/config/environments/test.rb.tt#L32) to `true` you will get the behavior of rendering the page. By default Rails raises exception.
