### ISSUE TITLE
Proposal: ActionCable return promises on async events

### ISSUE THREAD

**Issue by baweaver** [rails/rails#36173]
### Proposal: ActionCable - Return Promises on async events

I'd like to propose (and subsequently volunteer to implement) a change to the ActionCable API to return promises instead of boolean values for asyncronous operations, such as connections.

#### Example: Connection

Currently ActionCable methods that establish connections and other asyncronous events [return a boolean value](https://github.com/rails/rails/blob/master/actioncable/app/javascript/action_cable/connection.js#L41), ex:

```javascript
// action_cable/connection.js

open() {
  if (this.isActive()) {
    // ...
    return false
  } else {
    // ...
    return true
  }
}
```

Returning `true` or `false` will indicate the success of potentially establishing a connection here, but the issue is that sometimes you would like to perform a series of actions predicated on the connection actually being active.

#### Draft Solution

What I would propose is that methods like open would return Promises instead, allowing users to chain onto them:

```javascript
// ? - Async helpers

function waitUntil(condition, interval = 500) {
  return new Promise((resolve, reject) => {
    const isTimedOut = timedOut(10000);

    const waitInterval = setInterval(() => {
      if (condition()) {
        clearInterval(waitInterval);
        return resolve();
      }

      if (isTimedOut()) {
        clearInterval(waitInterval);
        return reject('Request timed out!');
      }
    }, interval);
  });
}

function waitUntilConnected (channel) {
  return waitUntil(() => channel.consumer.connection.isOpen());
}

// action_cable/connection.js
open() {
  if (this.isActive()) return Promise.resolve(connection)

  return waitUntilConnected(this);
}
```

This is only a draft proposal, but something I had used in projects to predicate actions on a connection being open. I'd used it like this:

```javascript
const somethingChannel = new SomethingChannel();

somethingChannel.connect().then(() => {
  // predicated actions
});
```

A custom class was made to wrap the ActionCable API so I could wrap some of the actions in promises.

#### Interest?

Would this be an item of interest? I'd discovered some of these items working on a RailsConf talk that used ActionCable a lot, and would like to upstream some of these findings to Rails core if that's of interest to the team.

**Comment by palkan** [comment]
I've been thinking about adding a Promise-based API (or `async/await`, it's the _modern_ thing, right 😉?) for JS client for a while, that seems natural for async functionality.

But... ~~at what cost~~ a few things always stopped me:
- the existing library works _just fine_ and is used by many people =>
- adding async API would be hard without breaking changes =>
- adding a proper async interface would mean adding yet another version seating in a tree with the original one.

Thus, from my perspective, I see the two non-exclusive options here:
- create a separate, third-party, library with an async API and 
- plan a _grand refactoring_ of the core library based on that experience (or just merging this into core).

Probably, the mailing list is a better place for this discussion: https://github.com/rails/rails/blob/master/CONTRIBUTING.md#do-you-intend-to-add-a-new-feature-or-change-an-existing-one

**Comment by baweaver** [comment]
Fair point, I'll start building a side-package on NPM that does this and report back later.
