### ISSUE TITLE
request.headers whitlist 'api_key' in rails 6 API mode 

### ISSUE THREAD

**Issue by thrikal-vakilsearch** [rails/rails#36171]
### Expected behavior
Rails API application deployed to a server and it is running in https://some-example.com, While doing post request with payload as JSON and sending api_key, api_token as headers params, In application controller cannot get request.headers["HTTP_API_KEY"]. I have printed request.headers.each { |key, value|  Rails.logger.info key }, But cannot see HTTP_API_KEY. 

### Actual behavior
 When sending 'api_key' as header params, I should able to get request.headers["HTTP_API_KEY"]

### System configuration
**Rails version**: Rails 6.0.0.beta3

**Ruby version**: ruby 2.6.1p33

**Comment by y-yagi** [comment]
Please use the [Rails Core mailing list](https://groups.google.com/forum/#!forum/rubyonrails-core) for feature requests, where a wider community will be able to help you. We reserve the Rails issue tracker only for bugs in Rails. Thanks!
