### ISSUE TITLE
Zeitwerk causes a hard crash when running Rails Generators that constantize a recently created controller's name

### ISSUE THREAD

**Issue by johnmcdowall** [rails/rails#36188]
I've come across a strange issue which does not happen in previous versions of Rails. I have a project which has several Generators which do various things. Under Rails 6.0.0.RC I get a hard crash under the following circumstances: invoke creating a controller, then try to `constantize` the name of the controller you just created. The exception seems to come from Rails' Inflector which AFAIK Zeitwerk is patching. 

Calling `Rails.autoloaders.main.reload` directly after invoking creating the controller causes everything to work. 

### Steps to reproduce
Full repo with reproduction case here: https://github.com/kiso-io/zeitwerk_generators_crash_test

General outline: 

0. Create a rails generator
1. Have the generator create a controller of a given name
2. Attempt to constantize that controller name string for later use in an `inject_into_class` call
3. See that a hard crash occurs. 
4. Uncomment Line 13 in https://github.com/kiso-io/zeitwerk_generators_crash_test/blob/master/zeitwork_generators_crash/lib/generators/zeitwork_generators_crash/controller_generator.rb#L13 which enables a call to `Rails.autoloaders.main.reload`
5. Try the generator again, see that it works. 

EDIT: Also, switching the `config.autolaoder` to `:classic` also fixes the issue.

### Expected behavior
When running a Rails Generator, I should be able to invoke create a controller, then constantize a string of its name.

### Actual behavior
A hard crash occurs unless a call to `Rails.autoloaders.main.reload` is made directly after creating the controller. 

### System configuration
**Rails version**: 6.0.0.RC1

**Ruby version**: ruby 2.6.2p47

<details>
<summary>Exception Stack Trace</summary>
zeitwork_generators_test master % bin/rails g zeitwork_generators_crash:controller test
Running via Spring preloader in process 28586
      create  app/controllers/test_controller.rb
Traceback (most recent call last):
	37: from -e:1:in `<main>'
	36: from /Users/jmd/.asdf/installs/ruby/2.6.2/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	35: from /Users/jmd/.asdf/installs/ruby/2.6.2/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	34: from /Users/jmd/.asdf/installs/ruby/2.6.2/lib/ruby/gems/2.6.0/gems/bootsnap-1.4.4/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:54:in `load'
	33: from /Users/jmd/.asdf/installs/ruby/2.6.2/lib/ruby/gems/2.6.0/gems/bootsnap-1.4.4/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:54:in `load'
	32: from /Users/jmd/code/tmp/zeitwork_generators_crash_test/zeitwork_generators_test/bin/rails:9:in `<main>'
	31: from /Users/jmd/.asdf/installs/ruby/2.6.2/lib/ruby/gems/2.6.0/gems/activesupport-6.0.0.rc1/lib/active_support/dependencies.rb:302:in `require'
	30: from /Users/jmd/.asdf/installs/ruby/2.6.2/lib/ruby/gems/2.6.0/gems/activesupport-6.0.0.rc1/lib/active_support/dependencies.rb:268:in `load_dependency'
	29: from /Users/jmd/.asdf/installs/ruby/2.6.2/lib/ruby/gems/2.6.0/gems/activesupport-6.0.0.rc1/lib/active_support/dependencies.rb:302:in `block in require'
	28: from /Users/jmd/.asdf/installs/ruby/2.6.2/lib/ruby/gems/2.6.0/gems/zeitwerk-2.1.6/lib/zeitwerk/kernel.rb:23:in `require'
	27: from /Users/jmd/.asdf/installs/ruby/2.6.2/lib/ruby/gems/2.6.0/gems/bootsnap-1.4.4/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
	26: from /Users/jmd/.asdf/installs/ruby/2.6.2/lib/ruby/gems/2.6.0/gems/bootsnap-1.4.4/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `require_with_bootsnap_lfi'
	25: from /Users/jmd/.asdf/installs/ruby/2.6.2/lib/ruby/gems/2.6.0/gems/bootsnap-1.4.4/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
	24: from /Users/jmd/.asdf/installs/ruby/2.6.2/lib/ruby/gems/2.6.0/gems/bootsnap-1.4.4/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `block in require_with_bootsnap_lfi'
	23: from /Users/jmd/.asdf/installs/ruby/2.6.2/lib/ruby/gems/2.6.0/gems/bootsnap-1.4.4/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require'
	22: from /Users/jmd/.asdf/installs/ruby/2.6.2/lib/ruby/gems/2.6.0/gems/railties-6.0.0.rc1/lib/rails/commands.rb:18:in `<main>'
	21: from /Users/jmd/.asdf/installs/ruby/2.6.2/lib/ruby/gems/2.6.0/gems/railties-6.0.0.rc1/lib/rails/command.rb:46:in `invoke'
	20: from /Users/jmd/.asdf/installs/ruby/2.6.2/lib/ruby/gems/2.6.0/gems/railties-6.0.0.rc1/lib/rails/command/base.rb:65:in `perform'
	19: from /Users/jmd/.asdf/installs/ruby/2.6.2/lib/ruby/gems/2.6.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	18: from /Users/jmd/.asdf/installs/ruby/2.6.2/lib/ruby/gems/2.6.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	17: from /Users/jmd/.asdf/installs/ruby/2.6.2/lib/ruby/gems/2.6.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	16: from /Users/jmd/.asdf/installs/ruby/2.6.2/lib/ruby/gems/2.6.0/gems/railties-6.0.0.rc1/lib/rails/commands/generate/generate_command.rb:26:in `perform'
	15: from /Users/jmd/.asdf/installs/ruby/2.6.2/lib/ruby/gems/2.6.0/gems/railties-6.0.0.rc1/lib/rails/generators.rb:276:in `invoke'
	14: from /Users/jmd/.asdf/installs/ruby/2.6.2/lib/ruby/gems/2.6.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
	13: from /Users/jmd/.asdf/installs/ruby/2.6.2/lib/ruby/gems/2.6.0/gems/thor-0.20.3/lib/thor/group.rb:232:in `dispatch'
	12: from /Users/jmd/.asdf/installs/ruby/2.6.2/lib/ruby/gems/2.6.0/gems/thor-0.20.3/lib/thor/invocation.rb:133:in `invoke_all'
	11: from /Users/jmd/.asdf/installs/ruby/2.6.2/lib/ruby/gems/2.6.0/gems/thor-0.20.3/lib/thor/invocation.rb:133:in `map'
	10: from /Users/jmd/.asdf/installs/ruby/2.6.2/lib/ruby/gems/2.6.0/gems/thor-0.20.3/lib/thor/invocation.rb:133:in `each'
	 9: from /Users/jmd/.asdf/installs/ruby/2.6.2/lib/ruby/gems/2.6.0/gems/thor-0.20.3/lib/thor/invocation.rb:133:in `block in invoke_all'
	 8: from /Users/jmd/.asdf/installs/ruby/2.6.2/lib/ruby/gems/2.6.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	 7: from /Users/jmd/.asdf/installs/ruby/2.6.2/lib/ruby/gems/2.6.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	 6: from /Users/jmd/code/tmp/zeitwork_generators_crash_test/zeitwork_generators_crash/lib/generators/zeitwork_generators_crash/controller_generator.rb:17:in `set_layout'
	 5: from /Users/jmd/.asdf/installs/ruby/2.6.2/lib/ruby/gems/2.6.0/gems/activesupport-6.0.0.rc1/lib/active_support/core_ext/string/inflections.rb:68:in `constantize'
	 4: from /Users/jmd/.asdf/installs/ruby/2.6.2/lib/ruby/gems/2.6.0/gems/activesupport-6.0.0.rc1/lib/active_support/inflector/methods.rb:280:in `constantize'
	 3: from /Users/jmd/.asdf/installs/ruby/2.6.2/lib/ruby/gems/2.6.0/gems/activesupport-6.0.0.rc1/lib/active_support/inflector/methods.rb:280:in `inject'
	 2: from /Users/jmd/.asdf/installs/ruby/2.6.2/lib/ruby/gems/2.6.0/gems/activesupport-6.0.0.rc1/lib/active_support/inflector/methods.rb:280:in `each'
	 1: from /Users/jmd/.asdf/installs/ruby/2.6.2/lib/ruby/gems/2.6.0/gems/activesupport-6.0.0.rc1/lib/active_support/inflector/methods.rb:282:in `block in constantize'
/Users/jmd/.asdf/installs/ruby/2.6.2/lib/ruby/gems/2.6.0/gems/activesupport-6.0.0.rc1/lib/active_support/inflector/methods.rb:282:in `const_get': uninitialized constant TestController (NameError)
</details>

**Comment by fxn** [comment]
Strange, I could not reproduce:

```
bin/rails g zeitwork_generators_crash:controller test
The name 'TestController' is either already used in your application
or reserved by Ruby on Rails. Please choose an alternative and run
this generator again.
```

Nevertheless, in the generator you do not need the class object, you can pass the constant name as a string. So instead of

```ruby
controller_const_name = "#{name.camelize}Controller".constantize
```

just write

```ruby
controller_const_name = "#{name.camelize}Controller"
```

Generators are mainly about strings with file contents and file names, application classes are not a natural data to manipulate.

**Comment by johnmcdowall** [comment]
@fxn There may be a mistake in the repro instructions. Delete the `TestController.rb` file so that the generator proceeds and you should see the crash.  

Thanks for the info on the class name!

**Comment by johnmcdowall** [comment]
@fxn Yes, sorry I had checked in zeitwork_generators_test/app/controllers/test_controller.rb which will cause that message you encountered to show and halt the generator before the crash. I just checked in an update, or you can remove zeitwork_generators_test/app/controllers/test_controller.rb

**Comment by fxn** [comment]
I've looked into this.

Reason this happens is that `:classic` finds anything created in the middle of the execution, because it performs the lookup in autoload paths when the constant is missing and `const_missing` is triggered.

`:zeitwerk` mode is different, it first scans to set autoloads. If you add files afterwards, you need to reload to scan again.

On the other hand, if you change or delete an existing file in `:classic` mode, you need to reload anyway. Adding files in the middle of a script or console session is a special case of changing the project structure that happens to escape the need to reload as a consequence of the way `:classic` is implemented.

It is important to highlight that if this happens during a web request with reloading enabled, the project is reload in both modes.

All in all, I consider this one necessary edgy difference between the two of them. That is fine. And since this is about generators, better work with strings. I suggest to store an actual constant name in  `controller_const_name`, not a class object:

```ruby
controller_const_name = "#{name.camelize}Controller"
```

That matches the variable name, indeed.
