### ISSUE TITLE
ActiveModel numericality validation fails with floats with a large number of significant decimal digits

### ISSUE THREAD

**Issue by nfm** [rails/rails#36207]
### Steps to reproduce

```ruby
# frozen_string_literal: true

require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  # Activate the gem you are reporting the issue against.
  gem "activerecord", "6.0.0.rc1"
  gem "sqlite3"
end

require "active_record"
require "minitest/autorun"
require "logger"

# This connection will do for database-independent bug reports.
ActiveRecord::Base.establish_connection(adapter: "sqlite3", database: ":memory:")
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :numbers, force: true do |t|
    t.float :value
  end
end

MAX_VALUE = 1.0

class Number < ActiveRecord::Base
  validates :value, numericality: { less_than_or_equal_to: MAX_VALUE }
end

class BugTest < Minitest::Test
  def test_max_value
    value = MAX_VALUE
    # Value passes ActiveModel numericality validation as expected
    assert Number.new(value: value).valid?
  end

  def test_much_higher_than_max_value
    value = MAX_VALUE + 0.5
    # Value fails ActiveModel numericality validation as expected
    assert !Number.new(value: value).valid?
  end

  def test_a_little_higher_than_max_value
    value = MAX_VALUE + Float::EPSILON
    # Sanity check value is indeed >= MAX_VALUE
    assert_operator value, :>=, MAX_VALUE
    # However, value doesn't fail ActiveModel numericality validation
    assert !Number.new(value: value).valid?
  end
end
```

### Expected behavior
`1.0000000000000002 >= 1.0`, so the ActiveModel validation should fail.

### Actual behavior
ActiveModel validation passes

### More details

This is a regression in Rails 5.2.3, which was introduced in https://github.com/rails/rails/pull/32852. It's still busted in Rails 6.0.0.rc1.

The new `parse_as_number` method calls `raw_value.to_d`, which converts the float `1.0000000000000002` to the BigDecimal `0.1e1`, which effectively rounds it to `1.0`. However, the value `1.0000000000000002` can be persisted in a database float column.

### Fix

`raw_value.to_d` creates a BigDecimal with precision of `Float::DIG`, which is not high enough to represent `Float::EPSILON`. We could potentially specify a higher precision, although I'm not sure what the knock-on effects of this would be.

/cc @gmcgibbon for thoughts :heart:

**Comment by gmcgibbon** [comment]
Sorry I'm late. This is a tough one... I can change the casting precision here to `Float::EPSILON`, but it breaks other tests. Plus, I am willing to bet that increasing precision will only make validation slower for the majority of simpler cases.

I think the best solution for this is to only support floats up to 15 decimal places (`Float::DIG`), and say that if you need to convert anything higher than that, use a `BigDecimal` because `Float`s are unreliable. I'll create a PR to update the validation documentation.

For your use-case specifically, I think you can add a `before_validation` hook that does the `Float#to_d` casting with your desired precision.

**Comment by rafaelfranca** [comment]
Can we use the precision of the column in the database to know how we should handle the input? If `1.0000000000000002` after typecasted to store in the database become 1.0 the validation should pass.

**Comment by gmcgibbon** [comment]
Sure, I'll see if I can use the column precision and then default to `Float::DIG` for Active Models.

**Comment by nfm** [comment]
This is still reproducible on master (as of 53a1e44a55bc63d7ce3ce5732a3c9edd709b0ad9):

```ruby
# frozen_string_literal: true

require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  gem "rails", github: "rails/rails"
  gem "sqlite3"
end

require "active_record"
require "minitest/autorun"
require "logger"

# This connection will do for database-independent bug reports.
ActiveRecord::Base.establish_connection(adapter: "sqlite3", database: ":memory:")
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :numbers, force: true do |t|
    t.float :value
  end
end

MAX_VALUE = 1.0

class Number < ActiveRecord::Base
  validates :value, numericality: { less_than_or_equal_to: MAX_VALUE }
end

class BugTest < Minitest::Test
  def test_max_value
    value = MAX_VALUE
    # Value passes ActiveModel numericality validation as expected
    assert Number.new(value: value).valid?
  end

  def test_much_higher_than_max_value
    value = MAX_VALUE + 0.5
    # Value fails ActiveModel numericality validation as expected
    assert !Number.new(value: value).valid?
  end

  def test_a_little_higher_than_max_value
    value = MAX_VALUE + Float::EPSILON
    # Sanity check value is indeed >= MAX_VALUE
    assert_operator value, :>=, MAX_VALUE
    # However, value doesn't fail ActiveModel numericality validation
    assert !Number.new(value: value).valid?
  end
end
```

**Comment by nfm** [comment]
The above reproduction still works on master (as of 797ae91).

**Comment by simi** [comment]
Isn't this related to https://github.com/rails/rails/issues/35426?

**Comment by nfm** [comment]
@simi these do look related to me, I haven't dug into enough detail on #35426 to be certain though. Does running your reproduction for that issue against @gmcgibbon's PR (https://github.com/rails/rails/pull/36664) resolve it?
