### ISSUE TITLE
Iterating over Enumerator::ArithmeticSequence generated by Range.step(ActiveSupport::Duration) is extremely slow.

### ISSUE THREAD

**Issue by klamathix** [rails/rails#36209]
### Steps to reproduce
```ruby
require 'active_support/all'

(0..500000).step(1.hour).each do |x|
  puts x
end
```

### Expected behavior
Should print multiples of 3600 in the given range (138 of them) almost instantly. 

### Actual behavior
Output behaves as expected, but it runs **very** slowly. The time gap between two consecutive prints _seems_ to grow exponentially.

### System configuration
**Rails version**:
Rails 5.2.3
Rails 5.1.7

**Ruby version**:
2.6.0

Disclaimer: I am somewhat new to Ruby/Rails, apologies for any mistakes on my end regarding this issue.

The code runs fine on Ruby 2.5.0. I would guess this is connected to [Enumerator::ArithmeticSequence](url=https://ruby-doc.org/core-2.6.0.preview2/Enumerator/ArithmeticSequence.html).

Using an integer argument as opposed to ActiveSupport::Duration leads to normal behaviour:

```ruby
require 'active_support/all'

(0..500000).step(3600).each do |x|
  puts x
end
```

**Comment by y-yagi** [comment]
Duplicated with #34888 and already fixed with #34899. Thanks.
