### ISSUE TITLE
Nested attributes use default id is :id when custom id for nested model

### ISSUE THREAD

**Issue by nhatdt-1507** [rails/rails#36208]
### Steps to reproduce
[https://github.com/rails/rails/blob/master/activerecord/lib/active_record/nested_attributes.rb#L492](https://github.com/rails/rails/blob/master/activerecord/lib/active_record/nested_attributes.rb#L492)

### Expected behavior
attribute_ids = attributes_collection.map { |a| a["id"] || a[:id] }.compact
### Actual behavior
attribute_ids = attributes_collection.map { |a| a[association.klass.primary_key] }.compact

I waste all of my day to find out why nested attribute always create new record instead of edit old one when I custom primary key of nested model.

**Comment by eileencodes** [comment]
Hi @nhatdt-1507 can you make a reproduction script using the bug report template here https://github.com/rails/rails/blob/master/guides/bug_report_templates/active_record_master.rb. That will make it easier for us to debug and fix the issue you're seeing. Thanks!
