### ISSUE TITLE
Unexpected nested transaction rollback behavior with explicit ActiveRecord::Rollback

### ISSUE THREAD

**Issue by jakecraige** [rails/rails#36229]
### Steps to reproduce
Raise an `ActiveRecord::Rollback` exception in a transaction (without a savepoint) that is nested in another one which has joinable set to true (the default).

### Expected behavior
The parent and child transaction should be rolled back.

### Actual behavior
Nothing is rolled back

### System configuration
**Rails version**: master, 5.2.2.1, (many more)
**Ruby version**: 2.5.5p157

### Reproduction Code

```ruby
# frozen_string_literal: true
# run with `ruby this_file.rb`

begin
  require "bundler/inline"
rescue LoadError => e
  $stderr.puts "Bundler version 1.10 or later is required. Please update your Bundler"
  raise e
end

gemfile(true) do
  source "https://rubygems.org"

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  gem "rails", github: "rails/rails"
  gem "sqlite3"
end

require "active_record"
require "minitest/autorun"
require "logger"

# This connection will do for database-independent bug reports.
ActiveRecord::Base.establish_connection(adapter: "sqlite3", database: ":memory:")
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :posts, force: true do |t|
    t.string :title, null: false
  end
end

# Uncomment this module to apply patch to test how it affects test results.
#
# module ActiveRecordPatch
  # def transaction(requires_new: nil, isolation: nil, joinable: true)
    # if !requires_new && current_transaction.joinable?
      # if isolation
        # raise ActiveRecord::TransactionIsolationError, "cannot set isolation when joining a transaction"
      # end

      # yield
    # else
      # transaction_manager.within_new_transaction(isolation: isolation, joinable: joinable) { yield }
    # end
  # rescue ActiveRecord::Rollback
    # # NOTE: This is what was added to the original implementation
    # raise if !requires_new && current_transaction.joinable?
  # end
# end
# module ActiveRecord
  # module ConnectionAdapters # :nodoc:
    # class SQLite3Adapter
      # prepend ActiveRecordPatch
    # end
  # end
# end

class Post < ActiveRecord::Base
end

class MyError < StandardError
end

class BugTest < Minitest::Test
  def test_rollback_error
    ActiveRecord::Base.transaction do
      Post.create(title: 'first')
      ActiveRecord::Base.transaction do
        Post.create(title: 'second')
        raise ActiveRecord::Rollback
      end
      Post.create(title: 'last')
    end

    assert_nil(Post.find_by(title: 'first'))
    assert_nil(Post.find_by(title: 'second'))
    assert_nil(Post.find_by(title: 'last'))
  end
end
```

I've included a sample fix in the snippet above but I don't know enough about the AR internals to know if that's a reasonable solution to this issue.

**Comment by vishaltelangre** [comment]
This seems to be the expected behavior. As per the docs, the exception `ActiveRecord::Rollback` raised in a nested transaction block doesn't trigger a ROLLBACK. It happens since all the nested statements are executed under the parent transaction up to which the `ActiveRecord::Rollback` exception raised inside the nested block is not propagated. Please check for more details  https://github.com/rails/rails/blob/6394f9da6938d0dccfd8c95f10b2fb7ee98ab953/activerecord/lib/active_record/transactions.rb#L135-L174.

I am not an expert on this, therefore I am not really sure the rationale behind this behavior. 

Raising `ActiveRecord::Rollback` in a non-nested transaction block does issue a silent ROLLBACK though.

As a workaround for your nested case, raising any other exception other than `ActiveRecord::Rollback` should trigger a full ROLLBACK as expected. This exception (which is not an `ActiveRecord::Rollback`) is propagated outside the parent transaction block if not rescued.

**Comment by jakecraige** [comment]
Oh great find on that part of the documentation. So this is known surprising behavior 😄

As I was looking at documentation I was referencing the docs on the method itself [`ActiveRecord::ConnectionAdaptersDatabaseStatements#transaction`](https://api.rubyonrails.org/classes/ActiveRecord/ConnectionAdapters/DatabaseStatements.html#method-i-transaction) which mentions nested transactions but does not call out this behavior.

If this is not something that we want to fix, perhaps we should update the docs for that method to at call this out too?

**Comment by vishaltelangre** [comment]
I have updated the appropriate documentation in https://github.com/rails/rails/pull/36240 accordingly.

**Comment by eugeneius** [comment]
I don't think this behaviour is expected or desirable; the fact that it's currently documented is the result of a misunderstanding, according to the discussion on https://github.com/rails/rails/issues/14698. Given that, I don't think documenting it more prominently is the right solution here.

@jakecraige The fix you suggested looks equivalent to https://github.com/rails/rails/pull/15017, which means it will probably cause the same tests to fail. If you're interested in submitting a patch, the next step would be to run the Active Record test suite locally and try to fix the failures.
