### ISSUE TITLE
Rails 6 RC1: Migration was not run notification doesn't seem to work anymore

### ISSUE THREAD

**Issue by skatkov** [rails/rails#36232]
### Steps to reproduce
1. Have a Rails 6 RC 1 project
2. Ask someone to create a new column/migration and push to your git repo
3. Pull those changes to your machine
4. execute `rails s`

### Expected behavior
Before, Rails would halt and throw and error asking to run migration first.

### Actual behavior
Rails ended up working just fine, without any warnings.

### System configuration
**Rails version**: Rails 6.0.0.rc1

**Ruby version**: ruby 2.5.5p157 (2019-03-15 revision 67260) [x86_64-darwin18]

**Comment by yoones** [comment]
I failed to reproduce the bug.

When you run `bundle exec rails db:migrate:status`, do you see your new migration? If you do, is it up or down?

**Comment by vishaltelangre** [comment]
Accessing the app when there exist pending migration(s) shows the following screen (learn more about this feature here - https://github.com/rails/rails/pull/34788).

![image](https://user-images.githubusercontent.com/876195/57569986-a9e77200-741a-11e9-9820-406f9e0c0e96.png)

Aren't you getting something like this?

**Comment by skatkov** [comment]
@vishaltelangre yeah, I was not getting this page. But can't reproduce this on a clean rails app.

I'll try to reproduce it on our app again.

**Comment by skatkov** [comment]
Our application was misconfigured and this is not a rails bug. I'm closing this! Sorry.
