### ISSUE TITLE
Fix ArgumentError with Rails 5.2.x ActiveRecord subclass constructor arguments.

### ISSUE THREAD

**Issue by bkuhlmann** [rails/rails#36236]
### Steps to reproduce

Save the following code to a file (i.e. `example.rb`) and run it as `ruby example.rb`. *You might need to confirm you have no other versions of Rails uninstalled first*.

``` ruby
# frozen_string_literal: true

begin
  require "bundler/inline"
rescue LoadError
  abort "Bundler 1.10 or later is required."
end

gemfile true do
  source "https://rubygems.org"
  gem "rails", "~> 5.2"
  gem "sqlite3", "~> 1.4"
end

require "sqlite3"
require "active_record"

ActiveRecord::Base.establish_connection adapter: "sqlite3", database: ":memory:"

ActiveRecord::Schema.define do
  self.verbose = false

  create_table :posts, force: true do |table|
    table.string :label
  end
end

class Post < ActiveRecord::Base
end

class Example < Post
  def initialize one, two
    @one = one
    @two = two
    super()
  end

  private

  attr_reader :one, :two
end

Example.new 1, 2
```

Note that the Rails 5.1.x and Rails 5.2.x implementations differ slightly:

- [Rails 5.1.x](https://github.com/rails/rails/blob/5-1-stable/activerecord/lib/active_record/inheritance.rb#L49)
- [Rails 5.2.x](https://github.com/rails/rails/blob/5-2-stable/activerecord/lib/active_record/inheritance.rb#L50)

### Expected behavior

I would not expect to get an `ArgumentError` in this situation.

### Actual behavior

Here is there error I see:

``` 
~/.gem/ruby/2.6.3/gems/activerecord-5.2.3/lib/active_record/inheritance.rb:50:in `new': wrong number of arguments (given 2, expected 0..1) (ArgumentError)
```

This behavior *does not* happen on Rails 5.1.6 so only started seeing this when upgrading to Rails 5.2.3.

### System configuration

**Rails version**: 5.2.3

**Ruby version**: 2.6.3 (but I've seen this as far back as Ruby 2.4.4 too)

**Comment by sharang-d** [comment]
I see the exception on master too.

```ruby
# frozen_string_literal: true

require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  gem "rails", github: "rails/rails"
  gem "sqlite3"
end

require "active_record"
require "minitest/autorun"
require "logger"

# This connection will do for database-independent bug reports.
ActiveRecord::Base.establish_connection(adapter: "sqlite3", database: ":memory:")
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :posts, force: true do |t|
  end
end

class Post < ActiveRecord::Base
end

class Example < Post
  def initialize one, two
    @one = one
    @two = two
    super()
  end

  private

  attr_reader :one, :two
end

class BugTest < Minitest::Test
  def test_this_bug
    Example.new(1, 2)
  end
end
```

Output:
```
Error:
BugTest#test_this_bug:
ArgumentError: wrong number of arguments (given 2, expected 0..1)
```

I'm curious: what's the use case?

**Comment by bkuhlmann** [comment]
:bow: @sharang-d for digging into this.

Yeah, I have a client I'm upgrading from Rails 5.1.x to 5.2.x that likes to use subclasses in order to tweak attributes on the instance for testing purposes. I'm not saying I agree with this methodology but, regardless, I think it's odd one can't subclass as this breaks Ruby inheritance every developer understands.

As a workaround, while this is being investigated, I'm planning to refactor the code to not use subclasses for testing purposes. :wink:

**Comment by bkuhlmann** [comment]
:information_source: Discovered another use case for this. In addition to the example above, I ran into a situation where ActiveRecord subclasses were using the constructor to set virtual attributes. There wasn't a public API exposed for setting these attributes directly so the only way to do what was via the constructor.

**Comment by rafaelfranca** [comment]
If you are planning to override a method of the subclass you should make sure it follows the interface of it. Rails don't support overriding initializers for Active Record objects.

**Comment by FumiyaShibusawa** [comment]
#new method has only one argument to be passed, usually a Hash object.

```ruby
module ActiveRecord
  module Inheritance
    module ClassMethods
      def new(attributes = nil, &block)
      …
      end
  end
end
```

I would do a tweak like below if I had to, but you can assign attributes via #attr_*** after initializing.

```ruby
ActiveRecord::Schema.define do
  create_table :vehicles, force: true do |t|
    t.string :type
    t.string :name
  end
end

class Vehicle < ActiveRecord::Base
end

class Bike < Vehicle
  attr_reader :one, :two

  def initialize(one:, two:, **attributes)
    @one = one
    @two = two
    super(attributes)
  end
end

Bike.new(one: 1, two: 2, name: "bob")
=> #<Bike:0x0000556e36e2b298 id: nil, type: "Bike", name: "bob">
```
