### ISSUE TITLE
feature requests portal

### ISSUE THREAD

**Issue by celesteking** [rails/rails#36234]
There should be some way to request features and get them implemented. 

Something like Patreon or Kickstarter, or whatever site that would allow you to post a feature request and then that request would gather likes/claps/stars/money/coder interest, and then the ones that have gained significant support would be worked upon and finally merged into core.

Having a 1980 newsgroup aka maillist for such a thing is definitely not good enough for 2020.

Tell me what you think.

**Comment by fxn** [comment]
Open source is not a democracy, you don't get into core what gets more votes. You get into core what the core team believes is worthwhile according to their perspective and future vision of the project. One thing is to listen to users, and a different thing is to be driven by popularity.

The mailing list is the channel that we like for feature requests.
