### ISSUE TITLE
Result of ActiveStorage #attach is different from 5.2.3 to 6.0 and is not documented

### ISSUE THREAD

**Issue by weilandia** [rails/rails#36238]
### Steps to reproduce
Run the tests in the following app and then change the Rails version to 5.2.3 and run the tests again.

https://github.com/weilandia/active-storage-attach-change

### Expected behavior
In 5.2.3, #attach returns the array of attachments, while in 6.0 it returns `true`.   I'm guessing it has to do with https://github.com/rails/rails/pull/33303/files#diff-60af6faf13016eb62a7885e5eecd9b34 but I'm not sure if it is intended.

If it is intended, should we document the change? Is there a suggested way to get the attachment objects after calling #attach? i.e. to accomplish something similar to:

`file = user.files.attach(params[:signed_id])[0]`

### System configuration
**Rails version**:
6.0.0rc1
**Ruby version**:
2.6.2

**Comment by georgeclaghorn** [comment]
`#attach` has never been documented as returning anything, which means you ought not rely on its return value.

> Is there a suggested way to get the attachment objects after calling #attach? i.e. to accomplish something similar to:

`user.files.first` and `user.files[0]` should both work after calling `#attach`.

**Comment by sinankeskin** [comment]
Hi.

I have a JSON API and users upload images via direct upload.

Here is my create method before this change:
```ruby
# POST /images
def create
    result = @images.attach(image_params[:signed_id])

    if result&.any?
        render json: result.first, root: 'company_image', status: :created
    else
        render json: { errors: ['Image attachment failed'] },
                status: :unprocessable_entity
    end
end
```
and here is my create method after this change.

```ruby
# POST /images
def create
  result = @images.attach(image_params[:signed_id])

  if result
    render json: @images.last, root: 'company_image', status: :created
  else
    render json: { errors: ['Image attachment failed'] },
            status: :unprocessable_entity
  end
end
```
Here is the scenario:
We have an Ember app that uses this api.

User selects 2 or more images to upload and submits to this create method and in this scenario sometimes **race condition** happening.

Second image result returns true for attach method but @images.last returning previous attachment somehow.

Ember throws an exception which basicaly says you cannot create multiple models with same id.

This was ok before Rails 6.0. I guess I can't guarantee the result, right?.

Any suggestion?

Thank you.

**Comment by sinankeskin** [comment]
Hi @georgeclaghorn 

Any help to resolve this?

Because after upgrading to rails 6 this is still happening time to time.
