### ISSUE TITLE
select column name as alias gives different output format

### ISSUE THREAD

**Issue by jainankita90** [rails/rails#36231]
### Steps to reproduce

step 1.) connect to rails console: 
 expected that row with id=1 exist in table
step 2.)
 TableName.where(id:1).select("created_at as request_date").first.request_date
returns mysql::time object
#<Mysql::Time:2019-02-11 14:25:09>  (object of Mysql::Time)
step 3.)
 TableName.where(id:(1..2)).select(“created_at as request_date”).first.request_date
 returns ActiveSupport::Time object
2019-02-11 14:25:09 +0530 (object of Time)

### Expected behavior
should be  time object
### Actual behavior
returns mysql::time object
### System configuration
**Rails version**:
Rails 4.2.1
**Ruby version**:
ruby 2.1.2p95 (2014-05-08 revision 45877) [x86_64-linux]
database 
**mysql  Ver 14.14 Distrib 5.5.62, for debian-linux-gnu (x86_64) 
** mysql gem
mysql (2.9.1)

**Comment by y-yagi** [comment]
4.2 series are not supported anymore for anything besides severe security fixes. 
Please check whether the issue can be reproduced with the latest Rails. If you can reproduce, feel free to reopen the issue. Thanks!
