### ISSUE TITLE
Optimistic locking does not handle nulls properly

### ISSUE THREAD

**Issue by engwan** [rails/rails#36264]
This is related to https://github.com/rails/rails/issues/26024. https://github.com/rails/rails/pull/26050 fixes that bug partially but it is still broken in some cases.

When the column is null in the database, update succeeds when the `lock_version` is not specified by the user. When a `lock_version` of `0` is given, this should still succeed because `NULL` means the same as `0` in this case (first version) but the update fails.

The reason for this is that `previous_lock_value = read_attribute_before_type_cast(locking_column)` in https://github.com/rails/rails/blob/v5.1.7/activerecord/lib/active_record/locking/optimistic.rb#L83 returns `nil` when the user did not provide a `lock_version` but when the attribute is set, it returns that value.

### Steps to reproduce

```ruby
def test_lock_version_without_default_value_when_form_submit
  ActiveRecord::Base.connection.execute("insert into posts(name) VALUES('Mark')")

  p1 = Post.find(1)
  p1.update(name: "Bob", lock_version: "0")
  p1.save
end
```

### Expected behavior

Record is updated 

### Actual behavior

A `ActiveRecord::StaleObjectError` is raised

### System configuration
**Rails version**: 5.1.7

**Ruby version**: 2.6.3

**Comment by bogdanvlviv** [comment]
We can't apply the fix mentioned in https://github.com/rails/rails/pull/26050#discussion_r75713005 despite it fixes your case, it will break a case when "lock_version" in database is `0`:
```ruby
  ActiveRecord::Base.connection.execute("insert into posts(name, lock_version) VALUES('Mark', '0')")

  p1 = Post.find(1)
  p1.update(name: "Bob", lock_version: "0")
  p1.save
```

Probably, Rails should generate query like
```sql
UPDATE "posts" SET "title" = "Bob", "updated_at" = "2019-07-27 15:34:12.150557", "lock_version" = 1 WHERE "posts"."id" = 1 AND ("posts"."lock_version" IS NULL OR "posts"."lock_version" = "0")
```
in those both cases.

**Comment by engwan** [comment]
Yes, we actually have this in our code right now to do that:

```ruby
# Patched because when `lock_version` is read as `0`, it may actually be `NULL` in the DB.
possible_previous_lock_value = previous_lock_value.to_i == 0 ? [nil, 0] : previous_lock_value

affected_rows = self.class.unscoped.where(
  locking_column => possible_previous_lock_value,
  self.class.primary_key => id_in_database
).update_all(
  attributes_with_values_for_update(attribute_names)
)
```

We couldn't use `_update_record` because it doesn't work with array values since it uses `attr.eq` in https://github.com/rails/rails/blob/0196551e6039ca864d1eee1e01819fcae12c1dc9/activerecord/lib/active_record/persistence.rb#L379
