### ISSUE TITLE
rails_blob_path disregards `disposition: :inline` option

### ISSUE THREAD

**Issue by rodrei** [rails/rails#36277]
### Steps to reproduce

* Generate a URL using `rails_blob_path(@user.avatar, disposition: :inline)`
* When visiting the generated URL the `Content-Disposition` header is still set to `attachment`

### Expected behavior
The `Content-Disposition` header should be set to `inline`

### Actual behavior
`Content-Disposition` is set to `attachment`

### System configuration
**Rails version**: ~~5.2.0~~ 5.2.3
**Ruby version**: 2.5.1p57

**Comment by rodrei** [comment]
Update: This is not a bug, the `Content-Disposition` header was being forced to `attachment` because a default configuration of ActiveStorage. I found these configs by looking at the source code, it may be a good idea to add document them.

After updating Rails to version 5.2.3, I managed to solve the issue by adding this to `application.rb`:

```
  config.active_storage.content_types_allowed_inline << "image/svg+xml"
  config.active_storage.content_types_to_serve_as_binary -= ["image/svg+xml"] 
```

**Comment by SampsonCrowley** [comment]
@rodrei I really don't think you should have closed this

**Comment by SampsonCrowley** [comment]
an *undocumented* ActiveStorage config that ignores what is given in the docs is definitely a bug

**Comment by SampsonCrowley** [comment]
@rafaelfranca can we reopen this? active storage should not be discretely overriding user input with no documentation

**Comment by rodrei** [comment]
I can reopen this if if helps. I do think at the very least there should be documentation about this.

**Comment by SampsonCrowley** [comment]
I definitely was baffled until I found your issue

**Comment by rjhancock** [comment]
Definitely a bug. Didn't realize there was configuration options and had to work around them on a project to get attached files to appear inline.

**Comment by rodrei** [comment]
I looked into this and found out that the reason AS doesn't allow to serve inline SVGs by default is to prevent [XSS attacks](https://digi.ninja/blog/svg_xss.php) (SVGs can contain javascript). 

In my case end users are not the ones making the uploads, so it's not a risk for us. I believe this is a good default to have in place, but we should add documentation to allow to change this default behaviour when needed.

**Comment by rodrei** [comment]
I correct myself, there is actually existing documentation on these configs here:
https://guides.rubyonrails.org/configuring.html#configuring-active-storage
