### ISSUE TITLE
Error during delete_all with include/references association

### ISSUE THREAD

**Issue by leandronsp** [rails/rails#36287]
### Steps to reproduce
I'm trying to `delete_all` records containing in a `references` association model. 

```
records = MyModel.where(id: ids).includes(:some_association).references(:some_association)
records.delete_all
```

### Expected behavior
Delete all records in the desired query

### Actual behavior
```
PG::UndefinedTable:
ERROR:  missing FROM-clause entry for table
LINE 1: DELETE FROM "my_models" WHERE "some_association"."model_id" = ...
```

### System configuration
**Rails version**: `5.1.4`

**Ruby version**: `2.4.2`

-------------------------------
My guess is that AR does not know how to build the query `DELETE FROM table WHERE id IN (...)` somehow. 

A temporary overcome would be:
```
records = MyModel.where(id: ids).includes(:some_association).references(:some_association)
MyModel.where(id: records.pluck(:id)).delete_all
```
But would be nice to have it in AR out-of-the-box. Using `joins` is not an option here because we want it to be eager loaded. 

There's already some plan on it or is it something I could help on?

Thanks!

**Comment by kamipo** [comment]
Fixed by 8a2ee3d8c6921ce34e597658e3f2b43b41423d1d
