### ISSUE TITLE
rails new my-app --skip-webpack-install results in broken app

### ISSUE THREAD

**Issue by zarqman** [rails/rails#36280]
### Steps to reproduce

`$ rails new my-app --skip-webpack-install`
`$ rails server`

### Expected behavior

`rails server` and `rails console` should work by default when using `--skip-webpack-install`.

### Actual behavior

```
$ rails server
RAILS_ENV=development environment is not defined in config/webpacker.yml, falling back to production environment
Exiting
Traceback (most recent call last):
	15: from ~/.rvm/gems/ruby-2.6.2/gems/railties-6.0.0.rc1/lib/rails/initializable.rb:61:in `block in run_initializers'
	14: from ~/.rvm/gems/ruby-2.6.2/gems/railties-6.0.0.rc1/lib/rails/initializable.rb:32:in `run'
	13: from ~/.rvm/gems/ruby-2.6.2/gems/railties-6.0.0.rc1/lib/rails/initializable.rb:32:in `instance_exec'
	12: from ~/.rvm/gems/ruby-2.6.2/gems/webpacker-4.0.2/lib/webpacker/railtie.rb:84:in `block in <class:Engine>'
	11: from ~/.rvm/gems/ruby-2.6.2/gems/webpacker-4.0.2/lib/webpacker.rb:27:in `bootstrap'
	10: from ~/.rvm/gems/ruby-2.6.2/gems/webpacker-4.0.2/lib/webpacker/commands.rb:14:in `bootstrap'
	 9: from ~/.rvm/gems/ruby-2.6.2/gems/webpacker-4.0.2/lib/webpacker/manifest.rb:18:in `refresh'
	 8: from ~/.rvm/gems/ruby-2.6.2/gems/webpacker-4.0.2/lib/webpacker/manifest.rb:83:in `load'
	 7: from ~/.rvm/gems/ruby-2.6.2/gems/webpacker-4.0.2/lib/webpacker/configuration.rb:47:in `public_manifest_path'
	 6: from ~/.rvm/gems/ruby-2.6.2/gems/webpacker-4.0.2/lib/webpacker/configuration.rb:43:in `public_output_path'
	 5: from ~/.rvm/gems/ruby-2.6.2/gems/webpacker-4.0.2/lib/webpacker/configuration.rb:39:in `public_path'
	 4: from ~/.rvm/gems/ruby-2.6.2/gems/webpacker-4.0.2/lib/webpacker/configuration.rb:80:in `fetch'
	 3: from ~/.rvm/gems/ruby-2.6.2/gems/webpacker-4.0.2/lib/webpacker/configuration.rb:84:in `data'
	 2: from ~/.rvm/gems/ruby-2.6.2/gems/webpacker-4.0.2/lib/webpacker/configuration.rb:88:in `load'
	 1: from ~/.rvm/gems/ruby-2.6.2/gems/webpacker-4.0.2/lib/webpacker/configuration.rb:88:in `read'
~/.rvm/gems/ruby-2.6.2/gems/webpacker-4.0.2/lib/webpacker/configuration.rb:88:in `read': No such file or directory @ rb_sysopen - ~/Sites/my-app/config/webpacker.yml (Errno::ENOENT)
```

### System configuration
**Rails version**: 6.0.0.rc1
**Ruby version**: 2.6.2

### Discussion

The default Gemfile includes `webpacker`, however when `webpacker` is present but `config/webpacker.yml` is missing, `rails server` and `rails console` are broken by default.

#35484 suggests that including `webpacker` when using `--skip-webpack-install` is intentional. If this remains true, then either `config/webpacker.yml` also needs to be created or `webpacker` needs to quietly accommodate a missing `config/webpacker.yml`. Alternatively, the decision to include `webpacker` could be revisited.

I am of course presuming that a broken, non-functioning new rails app is not the intended outcome when using `--skip-webpack-install`. :)

**Comment by yoones** [comment]
This is related to https://github.com/rails/rails/issues/35484

**Comment by y-yagi** [comment]
This is an intentional behavior. `config/webpacker.yml` is generated by `webpacker:install`, and an error occurs because `webpacker:install` is skipped. 
Running `webpacker:install` manually solves the error. Thanks.

**Comment by dgmora** [comment]
A flag that makes you new app start broken is a pretty odd intentional behavior 🤷‍♂
