### ISSUE TITLE
Error using Rails 6 parallel testing and system tests: `ChildProcess::LaunchError: Text file busy - /home/circleci/.webdrivers/chromedriver`

### ISSUE THREAD

**Issue by rmacklin** [rails/rails#36288]
I'm experimenting with Rails 6 parallel testing and I've found an issue that others might run into. I've been able to work around it, but I thought it would be helpful to open an issue here to see if we want to do something within rails to address it.

### Steps to reproduce

In the https://github.com/rmacklin/rails_parallel_testing_experiments repository, I created a new rails 6.0.0.rc1 app and added a dummy system test. I configured it to run tests in parallel, and set it up to run on CircleCI.

### Expected behavior

The tests pass on CI

### Actual behavior

The tests can fail on CI with the following error:
```
ChildProcess::LaunchError: Text file busy - /home/circleci/.webdrivers/chromedriver
    test/system/sample_system_test.rb:19:in `block in <class:SampleSystemTest>'
```

Example CI build: https://circleci.com/gh/rmacklin/rails_parallel_testing_experiments/16

### System configuration
**Rails version**: 6.0.0.rc1

**Ruby version**: 2.6.1

I think the error stems from multiple forked processes trying to update chromedriver in parallel. I've configured the sample app to use 2 parallel workers, but it follows that this error will be more common as more parallel workers are used.

My workaround was to explicitly trigger a chromedriver update before parallel processes are forked: https://github.com/rmacklin/rails_parallel_testing_experiments/commit/4b3b06bbeb34ec57277c8b37ad3804cd659539db

That appears to make the issue go away, but I wanted to discuss whether or not we think this is something to address within Rails.

---

cc @eileencodes since you are the mastermind behind both [parallel testing](https://github.com/rails/rails/pull/31900) and [system tests](https://weblog.rubyonrails.org/2017/4/27/Rails-5-1-final/#system-tests)

**Comment by eileencodes** [comment]
Your fix makes sense to me, can you send a PR?

**Comment by rmacklin** [comment]
Sure, I've opened https://github.com/rails/rails/pull/36292. I started with an issue because I wasn't sure if there was a more appropriate alternative solution.

**Comment by btyy77c** [comment]
https://github.com/btyy77c/rails_docker/pull/1/files

I wasn't able to get the `Webdrivers::Chromedriver.update` command to work.  I ended up just removing the `webdrivers` gem.  

I think think webdriver gem may require the `listen` gem and some other tools to work correctly.

**Comment by jhawthorn** [comment]
Fixes are now backported to 6-0-stable

**Comment by rmacklin** [comment]
Thanks!
