### ISSUE TITLE
Singleton method caching causing strange behavior when checking parent data

### ISSUE THREAD

**Issue by ted-hanson** [rails/rails#36297]
### Steps to reproduce
1) Create two models: Account and User
2) Setup relationship: User belongs_to Account and Account has_many Users
3) Create two Accounts
4) Add the following singleton method to the User model
```
def self.test
  self.account.id
end
```
5) `Account.find(1).users.test == Account.find(2).users.test` returns true!

### Expected behavior
`self.account` should be unique per call to the singleton method

### Actual behavior
`self.account` is being cached and causing strange issues w/ multi-tenancy 

### System configuration
**Rails version**: 5.0.7.2

**Ruby version**: 2.5.3p105

**Comment by ted-hanson** [comment]
This seems like a pretty big bug and I see it happening all the way in 5.0.0 so it has been around awhile... Let me know if I'm completely missing something.

**Comment by eileencodes** [comment]
@ted-hanson can you write a script that reproduces this error? You can use the sample scripts in https://github.com/rails/rails/blob/master/guides/bug_report_templates/active_record_master.rb to do that. Thanks!

**Comment by ted-hanson** [comment]
found the problem there was caching in our code
