### ISSUE TITLE
`select_tag` helper modifies input parameters without documenting it

### ISSUE THREAD

**Issue by adjam** [rails/rails#36295]
`select_tag` method on ActionView::Helpers::ForrmTagHelper class modifies one of its parameters (`options`, in the third position), but does not document this.  This can lead to unexpected behavior.

### Steps to reproduce

1. Create default, intended to be reused options parameter (e.g. as a constant on a helper class), e.g.

```ruby
class MyHelper < ApplicationHelper

   DEFAULT_OPTIONS = { 
     required: true,
     id: nil,
     include_blank: 'Please select an option'
   }
  # ...
end
```
2. pass `DEFAULT_OPTIONS` into `select_tag` as the third parameter
3. See `include_blank` option displayed first time form is rendered
4. Reload page
5. Blank option is no longer displayed.

This can be mitigated by use of  `.freeze` and/or `.dup` in calling code but the behavior is unexpected.

The key line appears to be

https://github.com/rails/rails/blob/master/actionview/lib/action_view/helpers/form_tag_helper.rb#L140

### Expected behavior

The `options` parameter passed in by the caller is not modified, or at least the fact that it will be modified is clearly documented.  One possible fix is to `dup` the input parameter before attempting to modify it, and then only passing the copy to subsequent methods that do not expect the `:include_blank` entry.

### Actual behavior
The `:include_blank` entry in the `options` hash is deleted if it is present.

### System configuration
**Rails version**:

5.2.3 at least.

**Comment by chukitow** [comment]
@adjam Fixed on https://github.com/rails/rails/pull/36311
