### ISSUE TITLE
ActionCable - Not returning {type: welcome} and auto unsubscribing

### ISSUE THREAD

**Issue by jgoodall628** [rails/rails#36301]
I am using actioncable to return progress bars for jobs running in the background. But for some reason the websockets are closing automatically without returning any data. Here is my cable.yml. 

```
production:
  adapter: redis
  url: <%= ENV['REDIS_URL'] %>
```

Using redis-cli I can see the the channels being subscribe and unsubscribed almost immediately.

```
1558197435.541736 [0 IP1:49930] "subscribe" "action_cable/Z2lkOi8vdGFwZ29vZHMtcmFpbHMtYXBpL0N1c3RvbWVyLzQzNzI2"
1558197437.161858 [0 IP2:53244] "unsubscribe" "action_cable/Z2lkOi8vdGFwZ29vZHMtcmFpbHMtYXBpL0N1c3RvbWVyLzQ5NDg3"
1558197438.225530 [0 IP1:49930] "subscribe" "action_cable/Z2lkOi8vdGFwZ29vZHMtcmFpbHMtYXBpL0VtcGxveWVlLzYxNA"
1558197441.321176 [0 IP3:47912] "unsubscribe" "action_cable/Z2lkOi8vdGFwZ29vZHMtcmFpbHMtYXBpL0VtcGxveWVlLzE2NA"
1558197441.422143 [0 IP3:47912] "subscribe" "action_cable/Z2lkOi8vdGFwZ29vZHMtcmFpbHMtYXBpL0VtcGxveWVlLzE2NA"
1558197442.525788 [0 IP4:35504] "INFO"
1558197444.783024 [0 IP5:42194] "subscribe" "action_cable/Z2lkOi8vdGFwZ29vZHMtcmFpbHMtYXBpL0VtcGxveWVlLzQwMw"
1558197453.946923 [0 IP2:53244] "subscribe" "action_cable/Z2lkOi8vdGFwZ29vZHMtcmFpbHMtYXBpL0VtcGxveWVlLzYwNQ"
1558197457.525826 [0 IP4:35504] "INFO"
1558197458.174370 [0 IP5:42194] "unsubscribe" "action_cable/Z2lkOi8vdGFwZ29vZHMtcmFpbHMtYXBpL0N1c3RvbWVyLzQ3ODEx"
1558197462.764152 [0 IP6:34240] "unsubscribe" "action_cable/Z2lkOi8vdGFwZ29vZHMtcmFpbHMtYXBpL0VtcGxveWVlLzYwNQ"
1558197463.751407 [0 IP3:47912] "subscribe" "action_cable/Z2lkOi8vdGFwZ29vZHMtcmFpbHMtYXBpL0VtcGxveWVlLzQwMw"
1558197467.604734 [0 IP3:47912] "unsubscribe" "action_cable/Z2lkOi8vdGFwZ29vZHMtcmFpbHMtYXBpL0VtcGxveWVlLzYwNQ"
1558197468.775929 [0 IP5:42194] "subscribe" "action_cable/Z2lkOi8vdGFwZ29vZHMtcmFpbHMtYXBpL0VtcGxveWVlLzYwNQ"
1558197469.454133 [0 IP6:34240] "unsubscribe" "action_cable/Z2lkOi8vdGFwZ29vZHMtcmFpbHMtYXBpL0N1c3RvbWVyLzQ3ODEx"
1558197472.525857 [0 IP4:35504] "INFO"
1558197473.737430 [0 IP1:49930] "unsubscribe" "action_cable/Z2lkOi8vdGFwZ29vZHMtcmFpbHMtYXBpL0VtcGxveWVlLzQ2OQ"
1558197474.661381 [0 IP6:34240] "subscribe" "action_cable/Z2lkOi8vdGFwZ29vZHMtcmFpbHMtYXBpL0VtcGxveWVlLzE2NA"
1558197475.338343 [0 IP3:47912] "subscribe" "action_cable/Z2lkOi8vdGFwZ29vZHMtcmFpbHMtYXBpL0VtcGxveWVlLzYwNQ"
1558197476.896516 [0 IP6:34240] "subscribe" "action_cable/Z2lkOi8vdGFwZ29vZHMtcmFpbHMtYXBpL0N1c3RvbWVyLzQ3ODEx"
```

Below is a screen shot of the opening and closing websockets form the chrome inspector:
<img width="1528" alt="Screen Shot 2019-05-18 at 11 44 16 AM" src="https://user-images.githubusercontent.com/7774849/57972604-751b7380-7962-11e9-815b-e78c169d60e4.png">

Our staging environment works just fine but for some reason this only happens on production.
Please let me know if you have any ideas. 

Thanks!

### Expected behavior

When creating an action cable consumer, it should create the connection and keep the websocket open to return messages

### Actual behavior

Websocket is opened and then immediately closed with no error message or reason why.

### System configuration
**Rails version**:
5.2.3
**Ruby version**:
 2.5.1p57

redis (3.3.5)
redis-actionpack (5.0.2)
redis-activesupport (5.0.7)
redis-rack (2.0.5)
redis-rails (5.0.2)
redis-store (1.6.0)

**Comment by palkan** [comment]
Hey @jgoodall628!

Could you please share the logs of WebSocket request frames? (click on the request in the Chrome Dev tools logs, there should be the "Messages" tab). And `Headers` tab contents could also be useful.

> Using redis-cli I can see the the channels being subscribe and unsubscribed almost immediately.

These are _internal channels_ (one per connection, [created right after the `connect` call](https://github.com/rails/rails/blob/2e6030d07386895e58ee08bd3bfdbca174add070/actioncable/lib/action_cable/connection/base.rb#L171-L172)); that seems that from the Action Cable perspective connection was initialized successfully.

**Comment by jgoodall628** [comment]
There is nothing within the messages tab on any of the requests.

**Comment by palkan** [comment]
@jgoodall628 Thanks!

What about the server logs? Do you see something like this there:

```
Started GET "/cable/" [WebSocket] for ::1 at 2019-05-18 19:33:44 -0400
Successfully upgraded to WebSocket (REQUEST_METHOD: GET, HTTP_CONNECTION: Upgrade, HTTP_UPGRADE: websocket)
An unauthorized connection attempt was rejected
Failed to upgrade to WebSocket (REQUEST_METHOD: GET, HTTP_CONNECTION: Upgrade, HTTP_UPGRADE: websocket)
Finished "/cable/" [WebSocket] for ::1 at 2019-05-18 19:33:44 -0400
```

Could you, please, provide an example?

**Comment by jgoodall628** [comment]
```
21:10:10
I, [2019-05-19T21:10:10.427664 #30] INFO -- : [af793ad9-9cd2-4a3a-8f2b-ca73352ced30] Started GET "/cable?access-token=-ZXUJwHr_Ge6ORVZwAvKMQ&client=rUq7q5kzXTjhu8gUTFeEFw&uid=example@example.com" for 66.196.214.134 at 2019-05-19 21:10:10 +0000

21:10:10
I, [2019-05-19T21:10:10.429295 #30] INFO -- : [af793ad9-9cd2-4a3a-8f2b-ca73352ced30] Started GET "/cable/?access-token=-ZXUJwHr_Ge6ORVZwAvKMQ&client=rUq7q5kzXTjhu8gUTFeEFw&uid=example@example.com" [WebSocket] for 66.196.214.134 at 2019-05-19 21:10:10 +0000

21:10:10
I, [2019-05-19T21:10:10.429396 #30] INFO -- : [af793ad9-9cd2-4a3a-8f2b-ca73352ced30] Successfully upgraded to WebSocket (REQUEST_METHOD: GET, HTTP_CONNECTION: upgrade, HTTP_UPGRADE: websocket)

21:10:10
I, [2019-05-19T21:10:10.453500 #30] INFO -- : [67420549-128d-4e83-a01e-09b80051f94b] Started GET "/cable?access-token=-ZXUJwHr_Ge6ORVZwAvKMQ&client=rUq7q5kzXTjhu8gUTFeEFw&uid=example@example.com" for 66.196.214.134 at 2019-05-19 21:10:10 +0000

21:10:10
I, [2019-05-19T21:10:10.455055 #30] INFO -- : [67420549-128d-4e83-a01e-09b80051f94b] Started GET "/cable/?access-token=-ZXUJwHr_Ge6ORVZwAvKMQ&client=rUq7q5kzXTjhu8gUTFeEFw&uid=example@example.com" [WebSocket] for 66.196.214.134 at 2019-05-19 21:10:10 +0000

21:10:10
I, [2019-05-19T21:10:10.455105 #30] INFO -- : [67420549-128d-4e83-a01e-09b80051f94b] Successfully upgraded to WebSocket (REQUEST_METHOD: GET, HTTP_CONNECTION: upgrade, HTTP_UPGRADE: websocket)

21:10:10
I, [2019-05-19T21:10:10.477314 #30] INFO -- : [f4565307-4fa3-4fda-8870-642977720e9b] Started GET "/cable?access-token=-ZXUJwHr_Ge6ORVZwAvKMQ&client=rUq7q5kzXTjhu8gUTFeEFw&uid=example@example.com" for 66.196.214.134 at 2019-05-19 21:10:10 +0000

21:10:10
I, [2019-05-19T21:10:10.478729 #30] INFO -- : [f4565307-4fa3-4fda-8870-642977720e9b] Started GET "/cable/?access-token=-ZXUJwHr_Ge6ORVZwAvKMQ&client=rUq7q5kzXTjhu8gUTFeEFw&uid=example@example.com" [WebSocket] for 66.196.214.134 at 2019-05-19 21:10:10 +0000

21:10:10
I, [2019-05-19T21:10:10.478776 #30] INFO -- : [f4565307-4fa3-4fda-8870-642977720e9b] Successfully upgraded to WebSocket (REQUEST_METHOD: GET, HTTP_CONNECTION: upgrade, HTTP_UPGRADE: websocket)

```

**Comment by palkan** [comment]
@jgoodall628 Thanks!

Could you please grep your logs for a single request (using the UUID, e.g. `af793ad9-9cd2-4a3a-8f2b-ca73352ced30`) and show all the logs for this request? In the snippet above there is no `Finished  "/cable?..."` line; do you have such lines?

Also, let's do the following to figure out at which end (client or server) a connection is closed (the built-in JS client re-opens the connection if it hasn't received pings in 3s):
- open the app page in the browser
- try to initiate a websocket connection from the console:
```js
new WebSocket("ws://<hostname>/cable?access-token=<valid token>&client=<valid client id>&uid=simple-client@example.com")
```
- check the "Network" tab for this connection: is it getting closed or staying alive? are there any incoming messages?

That could help us to find whether server closes connections or they get stucked.

And a few additional questions:
- You said that the problem only occurs in production, but not in staging: what is the difference in these two environments? (maybe, proxy servers, etc.)
- What application server do you use? (e.g. Puma, Unicorn)

**Comment by jgoodall628** [comment]
Thank you so much for your help! I have determined the issue. Apparently, when a connection is rejected by action cable it does not send an error message or anything. The client side also does not log anything it just retries the connection if it gets disconnected. We had a bug in our code causing some users to be improperly rejected, but rails should return some sort of message on the client side if the connection is rejected. Thanks again @palkan

**Comment by palkan** [comment]
> There should also be a way to stop actioncable from reattempting as well

That has been fixed in Rails 6: https://github.com/rails/rails/pull/34194
