### ISSUE TITLE
Rails 6.0.0.rc1 Missing Deprecation SourceAnnotationExtractor::Annotation

### ISSUE THREAD

**Issue by nvick** [rails/rails#36313]
I discovered this issue while upgrading a small app that uses `haml_rails` which is using `SourceAnnotationExtractor::Annotation` in version 1.

https://github.com/indirect/haml-rails/blob/86a48a59d7c31fcaacd35fdffa17551fb24e131c/lib/haml-rails.rb#L49

Here is the PR that introduced the changes https://github.com/rails/rails/pull/32065

### Steps to reproduce
```ruby
# frozen_string_literal: true

require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  # Activate the gem you are reporting the issue against.
  gem 'rails', '6.0.0.rc1'
end

require "active_support"
require "active_support/core_ext/object/blank"
require "rails/source_annotation_extractor"
require "minitest/autorun"

def extractor
  SourceAnnotationExtractor
end

def annotation
  SourceAnnotationExtractor::Annotation
end

class SourceAnnotationExtractorTest < ActiveSupport::TestCase
  test 'test_stuff' do
    assert_not_nil extractor
  end
  test 'more_stuff' do
    assert_not_nil annotation
  end
end
```

### Expected behavior
I would expect both tests to pass with a Deprecation warning pointing to the updated module info.

### Actual behavior
The main class SourceAnnotationExtractor has the warning, but ::Annotation outputs `TypeError: Rails::SourceAnnotationExtractor is not a class/module`

### System configuration
**Rails version**:
6.0.0.rc1
**Ruby version**:
2.6.2p47

**Comment by prathamesh-sonpatki** [comment]
@nvick This is how similar issue in rspec was fixed: https://github.com/rspec/rspec-rails/blob/f227983ba2ec8c666d073f40f5a5f517510bd058/lib/rspec-rails.rb#L13
and it seems to have been fixed in haml-rails as well https://github.com/indirect/haml-rails/blob/548fa4d7140ebc39dd4a2f2fec1eb25f4ac8dc98/lib/haml-rails.rb#L51

But the fix is present in version 2 of haml-rails. This is not an Rails issue so closing it.

**Comment by nvick** [comment]
I believe this is a Rails issue. The Annotation subclass is not being deprecated and it is a documented subclass so it needs to follow the Rails deprecation policy.

**Comment by nvick** [comment]
@prathamesh-sonpatki This was caused by moving `SourceAnnotationExtractor` under the Rails module. The top-level class was deprecated but the sub-class was not. Could you explain how you determined this is not a Rails issue?

**Comment by prathamesh-sonpatki** [comment]
@nvick I went by the comments in https://github.com/rails/rails/pull/32065 and fixes made to other repos when similar issues were reported. But I will open it so others can weigh in.

**Comment by sikachu** [comment]
This is legit break. I still owe a fix to https://github.com/rails/rails/pull/32065 ... so I'm assigning myself again and will be working on this.

**Comment by y-yagi** [comment]
@sikachu Are you still looking at this? If not, shall I pick up?

**Comment by sikachu** [comment]
Sorry about the delay, I just opened https://github.com/rails/rails/pull/36557 to address the issue.
