### ISSUE TITLE
Rails 5.2 Breaks `protect_with_forgery` in Rails Engine Controllers

### ISSUE THREAD

**Issue by drcapulet** [rails/rails#36317]
PR #29742 enables CSRF protection in controllers by default, which is great!

Unfortunately since it calls `protect_from_forgery` in an initializer, if you have an engine with a controller like:

```ruby
class EngineController < ActionController::Base
  protect_from_forgery with: :exception, unless: :should_skip_csrf_checks?
end
```

If you open up a console and run:

```ruby
EngineController._process_action_callbacks.detect { |c| c.filter == :verify_authenticity_token }
```

You'll notice the `@if` and `@unless` fields are empty.

The only way I've found to fix this is to create an initializer in your engine like so:

```ruby
initializer 'csrf-protection', after: 'action_controller.request_forgery_protection' do |app|
  EngineController.class_eval do
    protect_from_forgery with: :exception, unless: :should_skip_csrf_checks?
  end
end
```

**Comment by rafaelfranca** [comment]
Can you provide an example application that reproduce the issue?

**Comment by drcapulet** [comment]
I've uploaded an example engine [here](https://github.com/drcapulet/rails-csrf-test-engine) and an example engine [here](https://github.com/drcapulet/rails-csrf-test-app). If you clone the app, run `bundle install`, and then start up a Rails console you'll get:

```ruby
$ bundle exec rails c
Loading development environment (Rails 5.2.3)
[1] pry(main)> Rails::Csrf::Test::Engine::EngineController._process_action_callbacks.detect { |c| c.filter == :verify_authenticity_token }
=> #<ActiveSupport::Callbacks::Callback:0x00007faf0b483980
 @chain_config=
  {:scope=>[:kind],
   :terminator=>#<Proc:0x00007faf0c5b9790@/Users/alexc/.rbenv/versions/2.4.6/lib/ruby/gems/2.4.0/gems/actionpack-5.2.3/lib/abstract_controller/callbacks.rb:34 (lambda)>,
   :skip_after_callbacks_if_terminated=>true},
 @filter=:verify_authenticity_token,
 @if=[],
 @key=:verify_authenticity_token,
 @kind=:before,
 @name=:process_action,
 @unless=[]>
[2] pry(main)>
```

If you switch to the local installation of `rails-csrf-test-engine` and uncomment [this block](https://github.com/drcapulet/rails-csrf-test-engine/blob/master/lib/rails/csrf/test/engine/engine.rb#L10-L15) and comment [this line](https://github.com/drcapulet/rails-csrf-test-engine/blob/master/lib/rails/csrf/test/engine/engine_controller.rb#L10) and reopen a console you see the behavior is now fixed:

```ruby
$ bundle exec rails c
Loading development environment (Rails 5.2.3)
[1] pry(main)> Rails::Csrf::Test::Engine::EngineController._process_action_callbacks.detect { |c| c.filter == :verify_authenticity_token }
=> #<ActiveSupport::Callbacks::Callback:0x00007fad66c7b378
 @chain_config=
  {:scope=>[:kind],
   :terminator=>#<Proc:0x00007fad67cd03b8@/Users/alexc/.rbenv/versions/2.4.6/lib/ruby/gems/2.4.0/gems/actionpack-5.2.3/lib/abstract_controller/callbacks.rb:34 (lambda)>,
   :skip_after_callbacks_if_terminated=>true},
 @filter=:verify_authenticity_token,
 @if=[],
 @key=:verify_authenticity_token,
 @kind=:before,
 @name=:process_action,
 @unless=[:should_skip_csrf_checks?]>
[2] pry(main)>
```

**Comment by drcapulet** [comment]
@rafaelfranca Anything else you need here from me?

**Comment by tgxworld** [comment]
@drcapulet I had a look into this and it seems like you're facing the issue because you're using a [rails plugin](https://guides.rubyonrails.org/plugins.html) as a [rails engine](https://guides.rubyonrails.org/engines.html). I've not quite sure if the following way you're using is the recommended way of adding a Rails controller via an engine.

```
# frozen_string_literal: true

require 'rails'
require 'action_controller'

require 'rails/csrf/test/engine/engine'
require 'rails/csrf/test/engine/engine_controller'
require 'rails/csrf/test/engine/version'
```

**Comment by drcapulet** [comment]
@tgxworld Ah yeah that's the underlying issue - thanks! It'd be nice if there was a warning on this, but I'll close this out.
