### ISSUE TITLE
ActiveRecord::Base.cache_versioning is false even tough Rails.application.config.active_record.cache_versioning set to true

### ISSUE THREAD

**Issue by feliperaul** [rails/rails#36322]
### Steps to reproduce
```
Loading development environment (Rails 5.2.2.1)
[1] pry(main)> Rails.application.config.active_record.cache_versioning
=> true
[2] pry(main)> ActiveRecord::Base.cache_versioning
=> false
```

### Expected behavior
`ActiveRecord::Base.cache_versioning` should match `Rails.application.config.active_record.cache_versioning` defined in `initializers.new_framework_defaults_5_2.rb`

Looking through past issues, I found #33283 which describes the exact same issue. However, it was closed with "You are running in bugs in the gems your have. Gems should not load AR::Base / AC::Base during boot, so the right way to fix the problem is open issues in the gems that behaves in this way and fix them."

I strongly think this needs reconsideration. If I tell Rails in an initializer that I want my setting to be some way, I expect this to be respected regardless of a gem does or doesn't do during boot, specially because we can't know which gems are causing this and even if we did it's not a reasonable solution. 

The way this stands, how am I supposed to use cache_versioning if Rails doesn't respect what I tell it to in the config files? Should I force `ActiveRecord::Base.cache_versioning = true` in an initializer?

### System configuration
**Rails version**: 5.2.2.1

**Ruby version**: 2.5.3

**Comment by y-yagi** [comment]
This is intentional behavior and should fix gems. Of course, it is also possible to specify a value directly to `ActiveRecord::Base.cache_versioning`. Specify it temporarily, and let's fix gems. Thanks.
Ref: #23589.
