### ISSUE TITLE
6.0.0.rc1 javascript_include_tag missing in layouts.html.erb file when using rails plugin new myenginename --mountable

### ISSUE THREAD

**Issue by bradpotts** [rails/rails#36332]
Not sure if this was on purpose but the application layouts file (also test/dummy layouts file) is missing the include Java Script tag (javascript_include_tag) when generating an engine. Was I supposed to include an extra helper to generate the javascript_include_tag ?

### Steps to reproduce
rails plugin new myenginename --mountable

### Expected behavior
JavaScript Include Tag in layouts.html.erb
<%= javascript_include_tag "my_engine_name/application" %>

### Actual behavior
The JavaScript Include Tag is Missing
<%= javascript_include_tag "my_engine_name/application" %>

### System configuration
Rails 6.0.0.rc1

**Comment by bradpotts** [comment]
This maybe related with previous reported issue.

### Steps to reproduce
rails plugin new myenginename --mountable

### Expected behavior
js Entry in the myenginename_manifest.js:

     //= link_directory ../javascripts/myenginename .js

js Folder and  File application.js:

    app/assets/javascripts/myenginename/application.js

### Actual behavior
In the myenginename_manifest.js
Missing the Manifest Entry:
      
     //= link_directory ../javascripts/myenginename .js

Missing js Folder and appliction.js File:

     app/assets/javascripts/myenginename/application.js

### System configuration

Rails 6.0.0.rc1

**Comment by abhaynikam** [comment]
After a lot of debugging found that JS was not included in the plugin because of this commit -> https://github.com/rails/rails/pull/33079/commits/ea3972c50d2fccda0c4392fe78d128633204f72d

It was removed on purpose. It is not clear to me why it was removed. I can work on reverting it.

**Comment by dhh** [comment]
I don't recall why it was removed from plugins either. Doesn't seem like a good reason.

**Comment by dhh** [comment]
Actually, I recall now. We've moved all JavaScript work going forward to Webpacker. The javascript_include_tag uses the asset pipeline. You can still use that manually, but it's no longer the recommended path, so we shouldn't be generating that going forward.
