### ISSUE TITLE
can't rename webpacker directory

### ISSUE THREAD

**Issue by andrewkress** [rails/rails#36339]
### Steps to reproduce
`rails new rails6-webpack`
rename app/javascript to app/webpack
change config/webpacker.yml to point to this directory
add `config.autoloader = :classic` to config/application.rb
run `rails zeitwerk:check`

Everything works as expected if I leave the directory named javascript.

### Expected behavior
`rails zeitwerk:check` should return "All is good!"

### Actual behavior
`rails zeitwerk:check` returns an an error:
```
......................................................................

expected app/webpack/channels to define Channels
expected app/webpack/packs to define Packs

Please revise the reported mismatches. You can normally fix them by adding
acronyms to config/initializers/inflections.rb or renaming the constants.
```

### System configuration
**Rails version**:
6.0.0.rc1

**Ruby version**:
2.6.3

**Comment by abhaynikam** [comment]
@andrewkress : I did debug this issue and it looks like `zeitwerk:check` doesn't eager_load `app/javascript` but when it is renamed to `app/webpack` then it eager_load all the directories within `app` directory. It excludes `assets, javascripts` -> https://github.com/rails/rails/blob/master/railties/lib/rails/engine/configuration.rb#L43

Reference: https://github.com/rails/rails/blob/master/railties/lib/rails/engine/configuration.rb#L41-L43

We could exclude the `app/webpack` from eager loading by doing the following but it still throws an warning message on `zeitwerk:check`
```
# config/environments/development.rb
config.eager_load_paths = config.eager_load_paths.reject{ |s| s.include?("app/webpack") }
```

Warning message after excluding directory.
```
WARNING: The files in these directories cannot be checked because they
are not eager loaded:

  <dir>/issue-36339/app/webpack

You may verify them manually, or add them to config.eager_load_paths
in config/application.rb and run zeitwerk:check again.
```

**Comment by andrewkress** [comment]
It be easy enough to read the configured directory from webpacker.yml there instead of hard coding 'javascript'?  I could put a PR together for this if that is sufficient.

Would any changes be required to zeitwerk as well?

**Comment by fxn** [comment]
Zeitwerk 2.1.8 makes possible a better `zeitwerk:check`, I have rewritten the task and this is no longer an issue.

It could be discussed if processing `config/webpacker.yml` to better adjust application paths is a good idea, or if the user should be responsible for it. But, in any case, the issue itself is solved, and we are focused on wraping up for final, so I'm going to close.
