### ISSUE TITLE
Rails 6rc1 connected_to(database: ...) leaks connections.

### ISSUE THREAD

**Issue by SteffanPerry** [rails/rails#36330]
We are using rails 6 rc1 and the new connected_to method to perform report queries against a replica DB. This does work, however, the below seems to be making a brand new connection pool for every single query we send. This looks to be causing leaked DB connections.

We have monkey patched this in our code for now.

It appears this line is establishing a new connection every time:
https://github.com/rails/rails/blob/9c5135ce6a10c8318e25a587620c8cde4563f348/activerecord/lib/active_record/connection_handling.rb#L129

We fixed by changing this line to:
`handler.establish_connection(config_hash) unless handler.connected?(config_hash[:name])`

However, this probably won't work for everyone as the value of config_hash[:name] will currently always be "primary" (which is ok for us)

Is this intended behavior or am I missing something possibly?

### Steps to reproduce
```
10.times do
    ActiveRecord::Base.connected_to(database: :slow_replica) do
        ActiveRecord::Base.exec(QUERYHERE)
    end
end
```

### Expected behavior
Should connect to the database `slow_replica` once.

### Actual behavior
Creates a new connection pool for every call

### System configuration
**Rails version**: 6.0.0rc1

**Ruby version**: 2.6.2

**Comment by rafaelfranca** [comment]
cc @eileencodes

**Comment by jhawthorn** [comment]
This seems to only happen when using `connected_to(database: ...)` rather than `connected_to(role: ...)`

**Comment by jhawthorn** [comment]
I wrote a test (maybe the worst test ever) to bisect and find when this changed.

``` ruby
# Establish a connection
pool = @handler.establish_connection(@config)
original_ref = WeakRef.new(pool)

# Re-establish the same connection, overwriting it
pool = @handler.establish_connection(@config)

GC.start

# Ensure the connection pool can be GC'd
assert_not original_ref.weakref_alive?
```

The bisect found me 9027fafff6da932e6e64ddb828665f4b01fc8902, which I think suggests that this has always been a problem (that the Reaper thread leaks connection pools), that commit just enabled idle connection handling by default. It also suggests this is not directly related to `connected_to(database:)` (with `database:` is a shorthand for establish_connection vs `role:` just switches pools), but is an existing problem with `establish_connection`.
