### ISSUE TITLE
CI does not run any tests for active storage for any cloud providers on pull requests

### ISSUE THREAD

**Issue by peterzhu2118** [rails/rails#36361]
### Steps to reproduce

Add a failing test to any of the cloud services [here](https://github.com/rails/rails/tree/master/activestorage/test/service) (like `gcs_service_test.rb`) in a pull request and the CI will not fail because the test is not ran. These tests however appear to be ran on master. This makes it difficult to test changes made to the cloud providers in a PR.

### Expected behavior

The tests should be ran in CI in pull requests.

### Actual behavior

The tests are not ran.

This is seen in the CI:
```
Skipping S3 Direct Upload tests because no S3 configuration was supplied
Skipping GCS Direct Upload tests because no GCS configuration was supplied
Skipping Azure Storage Direct Upload tests because no Azure Storage configuration was supplied
Skipping Azure Storage Service tests because no Azure configuration was supplied
Skipping GCS Service tests because no GCS configuration was supplied
Skipping S3 Service tests because no S3 configuration was supplied
```

### System configuration
**Rails version**: master

**Ruby version**: N/A

**Comment by matthewd** [comment]
Thanks for the report, but this is by design: we don't expose the cloud provider credentials to third party PRs.
