### ISSUE TITLE
There should be a reminder message to backup your master.key file

### ISSUE THREAD

**Issue by phillipspc** [rails/rails#36366]
Considering how important this file is to your credentials (and that it is gitignored by default), I think a simple reminder message to create a backup of it would help a lot of people out, especially those coming from older versions of Rails who may not be familiar with this feature.

Perhaps after `rails new`? Or perhaps after editing credentials? Not sure what makes the most sense.

**Comment by kaspth** [comment]
Thanks, we don't take feature requests on the issue tracker. Try the rubyonrails-core mailing or submit a PR. Our old moniker of please do investigate (PDI) fits well here! 😊
