### ISSUE TITLE
Add property or modify cookie

### ISSUE THREAD

**Issue by RadoslavMarinov** [rails/rails#36360]
Rails: 5.1.5

I have a cookie set in my code like this:
`cookies[:profile_id] = @profile.id`
and later in the code (few lines below for example) I want to add a flag to that cookie whose value is already set (`@profile.id` ).

So I tried this way: 
` cookies[:profile_id] = << ; HttpOnly` - didn't work.

Then I tried this way:
`cookies[:profile_id] = {value: "#{cookies[:profile_id]} ; HttpOnly"}` - didnt work either.

What is the correct way to set or modify a cookie property value, after the cookie is being set/initialized?

**Comment by y-yagi** [comment]
Please use the [mailing list](https://groups.google.com/forum/#!forum/rubyonrails-talk) or StackOverflow for questions/help, where a wider community will be able to help you. We reserve the issues tracker for issues only. Thanks.
