### ISSUE TITLE
Active Storage has_many_attached attachments get destroyed when subsequent files are attached

### ISSUE THREAD

**Issue by jasonswett** [rails/rails#36374]
### Steps to reproduce
1. Create a new Rails 6.0.0.rc1 application
2. Generate a scaffold
3. Run `rails db:create` and `rails db:migrate`
4. Run `rails active_storage:install`
5. Run `rails db:migrate` to create the Active Storage tables
6. Add a `has_many_attached` to the scaffold's model
7. Add `<%= form.file_field :files, multiple: true %>` to that scaffold's form
8. Add `files: []` as an attribute to that scaffold's controller's strong params
9. In the browser, create an instance of the scaffold that includes a file upload
10. In the browser, edit that same instance and include a different file upload

### Expected behavior
The original file upload should be preserved. At the end of the above steps, the model instance should have both the original file and the subsequently-uploaded file.

### Actual behavior
The original upload gets blown away when the subsequent file is uploaded. All that's left is the newer file.

Note: it could conceivably be argued that the current behavior is the way the feature ought to work. However, the current Rails 6.0.0.rc1 behavior differs from the behavior I've observed in Rails 5.2.2.1. It seems to me that the new behavior constitutes a bug because it differs from the previous behavior.

### System configuration
**Rails version**: 6.0.0.rc1

**Ruby version**: 2.5.3

**Comment by jasonswett** [comment]
BTW I'm happy to potentially help contribute to a fix, although before investing time in that I'd like to get some confirmation that this is indeed a legitimate bug. This is my first Rails bug report so I'm not sure how it all works.

**Comment by georgeclaghorn** [comment]
If you’re doing something like `record.update!(message_params)`, this is the intended behavior—but I think we need to put it behind a config flag. The change from 5.2 is too dangerous.

**Comment by jasonswett** [comment]
You mean the config flag would control whether existing attachments get destroyed or preserved, right?

**Comment by georgeclaghorn** [comment]
Yes.

**Comment by jasonswett** [comment]
Do you think it would make sense for that flag to be set to "destroy" or "preserve" by default in 6.0?

If destroy, it seems like it would break the 5.2 behavior. If preserve, it seems like it would make the fact that the new behavior is the default pointless if you have to explicitly turn it on (which kind of makes the new behavior not the default after all). Between the two, it seems to me that the latter would make more sense. I don't feel strongly about that though.

**Comment by georgeclaghorn** [comment]
It’d be destroy by default for apps generated with 6.0 or newer and preserve by default for all other apps (by way of [`Rails::Application::Configuration#load_defaults`](https://github.com/rails/rails/blob/b6e17b6a4b67ccc9fac5fe16741c3db720f00959/railties/lib/rails/application/configuration.rb#L121-L149)).

**Comment by jasonswett** [comment]
Ahhh, I see.

**Comment by aximuseng** [comment]
Is there a workaround for this until the configuration option gets added?

**Comment by jasonswett** [comment]
@aximuseng I can confirm that a workaround is possible, although unfortunately the code I wrote for a workaround is sufficiently mixed in with other application code of mine that I can't easily just copy/paste the solution.

If memory serves, the workaround I wrote involves extending `ActiveRecord::Base#update` such that it re-attaches any existing attachments before doing anything else, thereby preserving the originals.

**Comment by jrnk** [comment]
@aximuseng another workaround is attaching the current attachments as hidden fields, see https://github.com/rails/rails/issues/35817#issuecomment-484158884

**Comment by koenhandekyn** [comment]
on activestorage (6.0.1) I'm seeing occasional but frequent cases where the attachment's are 'lost' somehow. I'm attaching them in batch like suggested above, which reduces that occurrence of the issue but it's still appearing. I've switched to a very recent and pretty fast MacBook so I'm wondering if there isn't a race condition still somewhere possible?

**Comment by nameisvijay** [comment]
How to enable this behavior of purging old attachment during update for rails upgraded from 5.2 ?

**Comment by nameisvijay** [comment]
Ok got it. I upgraded to rails 6.0 and load_defaults automatically sets replace_on_assign_to_many to true. So it shall automatically purge replaced files. It is just that I didn't know that activestorage is using separate sidekiq queues to enque purge job. All working fine now. Thanks for this great framework and active storage. It made life easy. However, chapter on activestorage on rails guide needs to link to chapter on rails configuration for activestorage.

**Comment by meaguile** [comment]
Hi, I encountered this problem with config.active_storage.replace_on_assign_to_many = false [#41862](https://github.com/rails/rails/issues/41862), is this the expected behavior?

**Comment by rlogwood** [comment]
> Hi, I encountered this problem with config.active_storage.replace_on_assign_to_many = false [#41862](https://github.com/rails/rails/issues/41862), is this the expected behavior?
config.active_storage.replace_on_assign_to_many = false
