### ISSUE TITLE
Autoloading guides revamp

### ISSUE THREAD

**Issue by fxn** [rails/rails#36391]
_Issue created to have this documentation included in the milestone._

We need a new guide for `:zeitwerk` mode, and tweaks to the previous one covering `:classic` mode.

**Comment by Tom-LawsonChase** [comment]
Hi Guys,
 I have ab open vacancy with a Fintech organisation Based in the the city of London for A Ruby Developer, very attractive salary with 2 days working from home. (There is also a position in Cardiff if anyone is interested as well)
tstones@lawsonchase.com
Thanks!

**Comment by fxn** [comment]
There is a first version of these docs up. Documentation is never finished, but let's consider it good for final mod last minute tweaks.
