### ISSUE TITLE
Reaper does not collect stale connections

### ISSUE THREAD

**Issue by aclarembeau** [rails/rails#36403]
### Steps to reproduce

Clone the following git directory: 
https://github.com/aclarembeau/rails-issue
Configure postgres instance on database.yml 
Run: `bundle exec puma -C config/puma.rb`

Then, execute `ruby benchmark.rb` (this will take a while) 
After 2 minutes, the script will stop (with an error message). 
Then, wait 1 more minute. 

Afterwise, call `curl localhost:3000`

### Expected behavior
After the script finished running, the connection pool is collected by the reaper. 
So, subsequent requests will not fail. 

### Actual behavior
After the script finished running, the connection pool is still empty. 
So, all subsequent requests will fail with `Cannot obtain a connection from the pool within 5000sec`

### System configuration
**Rails version**: 5.2.3

**Ruby version**: 2.4.2

### Additional details 

To reproduce the issue, we created an empty rails project, which consists of a single endpoint: / , that makes long (100 seconds) operation on a Postgres database. 
The server is set up to kill the requests that take more than 15 seconds (using rack timeout). 

Then, we've built a script that continuously queries the server for two minutes. 

As the requests go, and the timer expires, rack timers are continuously killing the request threads, leaving them in inconsistent states. This creates pending connections that should normally be connected by the Reaper, which is connected to reap every 10 seconds. 

But, we've constated that after a while, connections still hold, even though all threads have been killed and the reaper ran multiple times.

**Comment by itsWill** [comment]
👋 I had a 👀 into this and I think I have grasp at whats going on. 

When I runt the test app with the `benchmark.rb` script and adding the `use Rack::Timeout, service_timeout 15000` in `config.ru`, I can observe the same problem: requests time out and then all the subsequent requests fail with a `ActiveRecord::ConnectionTimeoutError`. 

When I perform the above and run `pg_top` I see something interesting, I see the number of `idle` connections to postgres increasing: 

```
84021 memo  0    0    0K    0K run     0:00 -0.00%  0.00% postgres: memo experiments ::1(60101) idle
84023 memo  0    0    0K    0K run     0:00 -0.00%  0.00% postgres: memo experiments ::1(60101) idle
```

What I think is happening is that even though the request is killed the database connection lingers on as the connection hasn't thrown an error so its still `in_use?`, and therefore the reaper doesn't reap it. 

If I do something like `ActiveRecord::Base.connection.execute("SET statement_timeout=5000"), a number lower than the rack timeout, there are no longer new `idle` connections being shown on `pg_top`. 

What I believe happens here is the database connections fail and are correctly checked back in the pool and we no longer create more idle connections on postgresql. 

It seems the reaper is just to manage connections that are created within dead threads. 

So the fix here is to set the `statment_timeout`  and use that to manage the database timeouts as opposed to a general request timeout.  

This seems like the correct behaviour, but indicates we can improve the documentation on reaping.

**Comment by rafaelfranca** [comment]
Yes, the reaper collects connections from dead threads, but it doesn't collect connections that were left in a strange state because rack-timeout. Like rack-timeout's documentation alerts [Timing Out is Inherently Unsafe](https://github.com/sharpstone/rack-timeout/blob/master/doc/risks.md#timing-out-is-inherently-unsafe). To the reaper the connections are still in user and the owner (the thread that created the connection) is alive, so it can't reap it.

**Comment by mendescamara** [comment]
@rafaelfranca,

in that case if `in_use?` from `ActiveRecord::ConnectionAdapters::AbstractAdapter` checked the `.alive?` from the Owner instead of checking if the Thread exists, wouldn't it solve it?

I have this problem and create a MonkeyPatch to solve it and it initially worked!

```
module ActiveRecord
  module ConnectionAdapters
    class AbstractAdapter
      alias :in_use_old? :in_use?

      def in_use?
        owner&.alive?
      end
    end
  end
end
```

Do you believe it is worth opening a PR with this suggestion?
