### ISSUE TITLE
Edit credentials.yml.enc will remove the Symbolic Link

### ISSUE THREAD

**Issue by partwith** [rails/rails#36411]
### Steps to reproduce

create a Symbolic Link for credentials.yml.enc
ln -s /shared/config/credentials.yml.enc  /current/config/credentials.yml.enc
The eidt the current/config/credetnials.yml.enc and save
### Expected behavior

credentials.yml.enc -> /shared/config/credentials.yml.enc
### Actual behavior

credentials.yml.enc
The symbolic link has been removed
### System configuration
**OS version**:
NAME="Amazon Linux AMI"
VERSION="2018.03"
ID="amzn"
ID_LIKE="rhel fedora"
VERSION_ID="2018.03"
PRETTY_NAME="Amazon Linux AMI 2018.03"
ANSI_COLOR="0;33"
CPE_NAME="cpe:/o:amazon:linux:2018.03:ga"
HOME_URL="http://aws.amazon.com/amazon-linux-ami/"
**Rails version**:
5.2.1
**Ruby version**:
2.4.4
### Releated Code
activesupport/lib/active_support/encrypted_file.rb

def write(contents)
  IO.binwrite "#{content_path}.tmp", encrypt(contents)
  FileUtils.mv "#{content_path}.tmp", content_path
end

That mv make the credentials.yml.enc become a new file, which will remove the symbolic link

**Comment by andrewmcodes** [comment]
What OS are you using?

**Comment by partwith** [comment]
> What OS are you using?

I try both macOS High Sierra and amazon AMI

**Comment by corny** [comment]
I have the same issue with Rails `6.0` on the master branch. It is relevant if you use capistrano to deploy your Rails application, you are symlinking the `credentials.yml.enc` and you edit the file using `rails credentials:edit`.

**Comment by pedrofurtado** [comment]
In which rails version this fix will be available?

**Comment by pedrofurtado** [comment]
@marciojg @willradi
