### ISSUE TITLE
`rails db:migrate RAILS_ENV=test` somehow deletes indexes from tables

### ISSUE THREAD

**Issue by github0013** [rails/rails#36410]
### Steps to reproduce

```rb
class CreateUsers < ActiveRecord::Migration[5.2]
  def change
    create_table :users do |t|
      t.string :name, null: false, index: true
      t.string :some_id, null: false
      t.timestamps

      t.index :some_id
      t.index [:name, :some_id], unique: true
    end
  end
end

```

This will create below in schema.rb by running `rails db:migrate`

```rb
  create_table "users", force: :cascade do |t|
    t.string "name", null: false
    t.string "some_id", null: false
    t.datetime "created_at", null: false
    t.datetime "updated_at", null: false
    t.index ["name", "some_id"], name: "index_users_on_name_and_some_id", unique: true
    t.index ["name"], name: "index_users_on_name"
    t.index ["some_id"], name: "index_users_on_some_id"
  end

```

However, if `rails db:migrate RAILS_ENV=test` is run followed by the command above, 
```diff
  create_table "users", force: :cascade do |t|
    t.string "name", null: false
    t.string "some_id", null: false
    t.datetime "created_at", null: false
    t.datetime "updated_at", null: false
-    t.index ["name", "some_id"], name: "index_users_on_name_and_some_id", unique: true
    t.index ["name"], name: "index_users_on_name"
    t.index ["some_id"], name: "index_users_on_some_id"
  end

```

some indexes will be deleted.   (it seems unique indexes and multiple column indexes are deleted)

### Expected behavior

`rails db:migrate RAILS_ENV=test` should not delete the indexes.

### Actual behavior

`rails db:migrate RAILS_ENV=test` deletes indexes.

### System configuration
**Rails version**:
Rails 5.2.3

**Ruby version**:
ruby 2.6.2p47 (2019-03-13 revision 67232) [x86_64-darwin16]

**Comment by y-yagi** [comment]
This is a issue that occurs because the test DB and the development DB are not properly synchronized. Make sure that the indexes are defined in the migration files, and then re-create the test DB. Thanks.
