### ISSUE TITLE
Scaffolding: force-plural is ignored in controller identifier

### ISSUE THREAD

**Issue by MicMicMon** [rails/rails#36418]
### Steps to reproduce
Run
```sh
rails generate scaffold table_name_nouns column_name:string --force-plural
```
In the controller, the helper functions retrieving the parameters through a white list has a non-plural-forced identifier (notice `:table_name_noun` instead of `:table_name_nouns`):
```ruby
# Only allow a trusted parameter "white list" through.
def v1_model_sec_achievements_mission_params
  params.require(:table_name_noun).permit(:column_name)
end
```
Same for other snippets such as the `set_*` method or variables names.

### Expected behavior
Should output `:table_name_nouns` because `force-plural` is used:
```ruby
# Only allow a trusted parameter "white list" through.
def v1_model_sec_achievements_mission_params
  params.require(:table_name_nouns).permit(:column_name)
end
```

### System configuration
**Rails version**: 5.2.3

**Ruby version**: 2.6.3

**Comment by andrewmcodes** [comment]
I may be, and probably am, missing something but it seems that this works exactly as it should. Check this commit and the associated tests: https://github.com/rails/rails/commit/4ddca325eeef46e640a225efb9b297260e1e8e7d.

Is this a bug or is just not working the way you expect it to? Can you provide an example repo?

**Comment by MicMicMon** [comment]
Yeah, it might be just a perception gap. I expect that `table_name_nouns` be a plural in the `params.require`, because otherwise it behaves the sames as without `force-plural`.

But you're right, maybe it's just the expected behaviour and you need to customize that to your taste afterwards.

My guess though is that the `force-plural` was forgotten in the name generations **inside** the code of the generated controller. (For variables names it is just cosmetic because that's inside the code - but for the `require` part, it has an impact on the published API).

**Comment by rafaelfranca** [comment]
This is worth fixing. Can you open a PR?

**Comment by MicMicMon** [comment]
> This is worth fixing. Can you open a PR?

Ok! Probably not before end of August though, just to let you know.
