### ISSUE TITLE
render_to_string in AbstractController::Rendering always returns nil?

### ISSUE THREAD

**Issue by RohanSharma1994** [rails/rails#36425]
https://github.com/rails/rails/blob/b2eb1d1c55a59fee1e6c4cba7030d8ceb524267c/actionpack/lib/abstract_controller/rendering.rb#L44

It calls render_to_body which is defined as empty.

I found this issue when upgrading to Rails 4 from Rails 3.2.

**Comment by y-yagi** [comment]
Please use the [mailing list](https://groups.google.com/forum/#!forum/rubyonrails-talk) or StackOverflow for questions/help, where a wider community will be able to help you. We reserve the issues tracker for issues only. Thanks.
