### ISSUE TITLE
Error installing rails in NETRUNNER LINUX

### ISSUE THREAD

**Issue by wesleymontaigne** [rails/rails#36421]
### Steps to reproduce
 

To see why this extension failed to compile, please check the mkmf.log which can be found here:

  /var/lib/gems/2.3.0/extensions/x86_64-linux/2.3.0/nokogiri-1.10.3/mkmf.log

extconf failed, exit code 1

Gem files will remain installed in /var/lib/gems/2.3.0/gems/nokogiri-1.10.3 for inspection.
Results logged to /var/lib/gems/2.3.0/extensions/x86_64-linux/2.3.0/nokogiri-1.10.3/gem_make.out

### Expected behavior

install

### Actual behavior

can't install 

### System configuration
**Rails version**:

**Ruby version**:

**Comment by wesleymontaigne** [comment]
to fix this I ran this command : 

sudo apt-get install libpng-dev
sudo apt-get install --reinstall zlibc zlib1g zlib1g-dev


it's work for me.

**Comment by y-yagi** [comment]
Please use the [mailing list](https://groups.google.com/forum/#!forum/rubyonrails-talk) or StackOverflow for questions/help, where a wider community will be able to help you. We reserve the issues tracker for issues only. Thanks.
