### ISSUE TITLE
Session variable set via ajax request not accessible on next request.

### ISSUE THREAD

**Issue by ankurkiyada** [rails/rails#36430]
### Steps to reproduce
* Making an ajax call to server and setting session variable using below method.
controller

def some_method
     session[:key]= "something"
end

* Making new http request and trying to access that session variable

def access_key
    p session[:key] #printing nil value
end

** CSRF token is set. 
** In AJAX response, i am not able to get response cookie.

### Expected behavior
It should print the session value stored in ajax request

### Actual behavior
Session variable is not passed on ajax response header.

### System configuration
**Rails version**: 5.2.3

**Ruby version**: 2.5.3

**Comment by chukitow** [comment]
@ankurkiyada I just created a new project with the System configuration that you shared but I was not able to reproduce your issue https://github.com/chukitow/rails_issue_36430

**Comment by chrismitchell** [comment]
@ankurkiyada were you able to figure anything out here? I'm currently running into this issue as well.

**Comment by KyawswarThant** [comment]
I'm also getting that issue right now!
