### ISSUE TITLE
Generated controller test does not pass due to undefined url local variable.

### ISSUE THREAD

**Issue by aryyya** [rails/rails#36436]
This generated test does not pass because `api_v1_graph_show_url` is not defined.

How do you get the route of the controller that you are testing?

```ruby
require "test_helper"

class Api::V1::GraphControllerTest < ActionDispatch::IntegrationTest
  test "should get show" do
    get api_v1_graph_show_url
    assert_response :success
  end
end
```

---

### Steps to reproduce

Generate a controller and relevant test:

```bash
rails generate controller api/v1/graph show
```

Execute the test:

```bash
rake test
```

### Expected behavior
The test should pass.

### Actual behavior
The test fails with an error:

```
Error:
Api::V1::GraphControllerTest#test_should_get_show:
NameError: undefined local variable or method `api_v1_graph_show_url' for #<Api::V1::GraphControllerTest:0x00007fc8fb7b90f0>
    test/controllers/api/v1/graph_controller_test.rb:5:in `block in <class:GraphControllerTest>'
```

### System configuration
**Rails version**: 5.2.3

**Ruby version**: 2.6.3

**Comment by y-yagi** [comment]
I can't reproduce your issue.

```bash
$ rails _5.2.3_ new app_36436
$ cd app_36436
$ ./bin/rails generate controller api/v1/graph show
Running via Spring preloader in process 15170
      create  app/controllers/api/v1/graph_controller.rb
       route  namespace :api do
  namespace :v1 do
    get 'graph/show'
  end
end
      invoke  erb
      create    app/views/api/v1/graph
      create    app/views/api/v1/graph/show.html.erb
      invoke  test_unit
      create    test/controllers/api/v1/graph_controller_test.rb
      invoke  helper
      create    app/helpers/api/v1/graph_helper.rb
      invoke    test_unit
      invoke  assets
      invoke    coffee
      create      app/assets/javascripts/api/v1/graph.coffee
      invoke    scss
      create      app/assets/stylesheets/api/v1/graph.scss

$ ./bin/rails t
2019-06-07 10:57:53 WARN Selenium [DEPRECATION] Selenium::WebDriver::Chrome#driver_path= is deprecated. Use Selenium::WebDriver::Chrome::Service#driver_path= instead.
Running via Spring preloader in process 15228
2019-06-07 10:57:54 WARN Selenium [DEPRECATION] Selenium::WebDriver::Chrome#driver_path= is deprecated. Use Selenium::WebDriver::Chrome::Service#driver_path= instead.
/home/yaginuma/program/rails/tmp/app_36436/db/schema.rb doesn't exist yet. Run `rails db:migrate` to create it, then try again. If you do not intend to use a database, you should instead alter /home/yaginuma/program/rails/tmp/app_36436/config/application.rb to limit the frameworks that will be loaded.
Run options: --seed 8391

# Running:

.

Finished in 0.563240s, 1.7754 runs/s, 1.7754 assertions/s.
1 runs, 1 assertions, 0 failures, 0 errors, 0 skips 
```

Can you please provide a sample application that reproduces the issue?

**Comment by aryyya** [comment]
I've narrowed down where the issue is occurring.

This configuration results in the test error:

```ruby
# config/routes.rb

Rails.application.routes.draw do
  namespace :api do
    namespace :v1 do
      get "graph/:category", to: "graph#show"
    end
  end
end
```

If I change `get "graph/:category", to: "graph#show"` to `get "graph/show"`, the test passes and the variable is defined.

But I need to access the `:category` parameter. The documentations suggests that this is the correct syntax to use here. The controller works fine, but the controller test doesn't have `api_v1_graph_show_url` defined.

Any idea where I'm going wrong?

I seem to have described the issue improperly as I did change the default `config/routes.rb` file. Please close this issue if it is no longer necessary.

**Comment by y-yagi** [comment]
This is not a generator issue. You edited the generated `routes.rb`, but the content is incorrect.
Please use the [mailing list](https://groups.google.com/forum/#!forum/rubyonrails-talk) or StackOverflow for questions/help, where a wider community will be able to help you. We reserve the issues tracker for issues only. Thanks.
