### ISSUE TITLE
Sass::SyntaxError: Invalid CSS after " *= require_self": expected "{", was ""

### ISSUE THREAD

**Issue by guestOK101** [rails/rails#36446]
### Actual behavior
RAILS_ENV='production' bundle exec rake assets:precompile   (fails)

error message:

Sass::SyntaxError: Invalid CSS after " *= require_self": expected "{", was ""

the only lines I have in my app/assets/stylesheets/application.css are these two lines:

 *= require main
 *= require_self

Can anyone help me troubleshoot this? My server works fine in development mode, but not in production mode. 

### System configuration
**Rails version**: 4.2.10

**Ruby version**: 2.4.5

**Comment by guestOK101** [comment]
hmmmmmm I just removed those two lines from app/assets/stylesheets/application.css and it seems ok... weird I could have sworn I was having an issue with that...

**Comment by y-yagi** [comment]
Please use the [mailing list](https://groups.google.com/forum/#!forum/rubyonrails-talk) or StackOverflow for questions/help, where a wider community will be able to help you. We reserve the issues tracker for issues only. Thanks.
