### ISSUE TITLE
Sass::SyntaxError: Invalid CSS after " *= require_self": expected "{", was ""

### ISSUE THREAD

**Issue by reason2019** [rails/rails#36445]
### Steps to reproduce
I'm not sure why this is happening.

### Expected behavior
RAILS_ENV='production' bundle exec rake assets:precompile   (should succeed)

### Actual behavior
RAILS_ENV='production' bundle exec rake assets:precompile   (fails)

error message:

Sass::SyntaxError: Invalid CSS after " *= require_self": expected "{", was ""

the only lines I have in my app/assets/stylesheets/application.css are these two lines:

 *= require main
 *= require_self

Can anyone help me troubleshoot this? My server works fine in development mode, but not in production mode. 

### System configuration
**Rails version**: 4.2.10

**Ruby version**: 2.4.5

**Comment by y-yagi** [comment]
Please use the [mailing list](https://groups.google.com/forum/#!forum/rubyonrails-talk) or StackOverflow for questions/help, where a wider community will be able to help you. We reserve the issues tracker for issues only. Thanks.
