### ISSUE TITLE
#except does not work with Hashie::Mash

### ISSUE THREAD

**Issue by philipbjorge** [rails/rails#36444]
### Steps to reproduce
```
foo = Hashie::Mash.new(x: 1, y: 2)
foo.except(:x)
# => {"x"=>1, "y"=>2}
```

This is a change in behavior from rails 5 to 6 related to this change: https://github.com/rails/rails/commit/32db884967a8af0409bfcb2158ee948cd7ef619c

### Expected behavior
Return a new Hashie object with its `:x` key removed.

### Actual behavior
Returns a new hash that contains the `x` key still

### System configuration
**Rails version**: rails 6.0.0.rc1

**Ruby version**: ruby 2.6.3p62 (2019-04-16 revision 67580) [x86_64-darwin18]

---

Associated Hashie issue
https://github.com/intridea/hashie/issues/476

**Comment by y-yagi** [comment]
It seems Hashie's issue. Please fix with Hashie's side. Thanks!
