### ISSUE TITLE
rails db:migrate not giving an error but not showing up on web

### ISSUE THREAD

**Issue by lialeon84** [rails/rails#36450]
It's supposed to show restaurant name and place. I was trying to change the name of the restaurant and used rake db:rollback after that everything disappeared.  

<img width="1391" alt="Screen Shot 2019-06-09 at 7 48 37 PM" src="https://user-images.githubusercontent.com/50724307/59166467-9bf74080-8aef-11e9-94d4-4f67090a45a7.png">

**Comment by akhil-gautam** [comment]
@lialeon84 
Please elaborate on your issue.
