### ISSUE TITLE
ActiveSupport core extension blows up when using include? on endless range

### ISSUE THREAD

**Issue by aldhsu** [rails/rails#36451]
### Steps to reproduce
```ruby
# frozen_string_literal: true

require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  gem "rails", github: "rails/rails"
end

require "active_support"
require "active_support/core_ext/object/blank"
require "active_support/core_ext/range/include_time_with_zone"
require "minitest/autorun"

class BugTest < Minitest::Test
  def test_endless_ranges
    assert (0..).include? 2
  end
end

```
### Expected behavior
- `include?` on endless range should not raise error

### Actual behavior
- raises error
```
RangeError: cannot get the last element of endless range
```

### System configuration
**Rails version**: master@5267753

**Ruby version**:  2.6.0

Problem is in ActiveSupport here:
https://github.com/rails/rails/blob/5267753f6494d969b416ba9c044c2177db5e5caf/activesupport/lib/active_support/core_ext/range/include_time_with_zone.rb#L14

**Comment by aldhsu** [comment]
Issue still exists in master as of 13f9803215.

**Comment by pond** [comment]
This misses some other cases - see https://github.com/rails/rails/issues/37172 and comments therein. I'll take the approach established by this PR for tests etc., & get a patch together to fill in the rest of the gaps.
