### ISSUE TITLE
ActionText SQLite3::ConstraintException: UNIQUE constraint failed: action_text_rich_texts.record_type, action_text_rich_texts.record_id, action_text_rich_texts.name

### ISSUE THREAD

**Issue by ekr990011** [rails/rails#36459]
### Steps to reproduce
Create a `has_rich_text` attribute for two separate models with the same attribute field.

My issue is mainly a question since I think I understand why I am getting the error.
Why does action text make the field you put on a model unique? It seems to merely check that the name is unique within the `action_text_rich_texts` table.

```
create_table "action_text_rich_texts", force: :cascade do |t|
    t.string "name", null: false
    t.text "body"
    t.string "record_type", null: false
    t.integer "record_id", null: false
    t.datetime "created_at", precision: 6, null: false
    t.datetime "updated_at", precision: 6, null: false
    t.index ["record_type", "record_id", "name"], name: "index_action_text_rich_texts_uniqueness", unique: true
end
```

This means that if you have say the attribute `:article` on two different Models you get a Unique Constraint violation. I am curious why it was implemented this way and if perhaps I am just missing something or I always do have to have a unique attribute name for the rich text field.

I assume for the faster search by indexing it I guess?

I got around my issue by changing one of my Models from:
`has_rich_text :article`
to
`has_rich_text :article_body`
### System configuration
**Rails version**: Rails 6.0.0.rc1

**Ruby version**: ruby 2.5.3p105

**Comment by y-yagi** [comment]
Since model name is stored in ` record_type`, a record is unique for each model. So there should be no issue if different models have the same attribute. 

I specified the same attribute name in different models, it didn't matter. 
Can you please provide a sample application that reproduces the issue?

**Comment by ekr990011** [comment]
Yea let me get one up

**Comment by ekr990011** [comment]
Taking a second look and making a test app I don't seem to get the problem. My only guess is I must have accidentally used the same model in the other controller. I am glad I am wrong thank you for your time sorry I wasn't able to reproduce, although that is good.
