### ISSUE TITLE
ActiveStorage permanent S3 URL

### ISSUE THREAD

**Issue by johncox00** [rails/rails#36468]
### Steps to reproduce
Use ActiveStorage.

### Expected behavior
I'd expect my app to behave like most other apps on the web when it comes to providing a `src` property to an `img` tag: `<img src="https://s3-us-west-2.amazonaws.com/my-app/assets/files/000/008/581/medium/foobar.png?1534272229" />`

### Actual behavior
I can only route requests for static assets through my [single-threaded] Rails app to get URLs that last a maximum of 1 week. It's proving to be challenging on many levels to not have the option to go directly to the source. Am I missing something?

### System configuration
**Rails version**: 5.2.3

**Ruby version**: 2.4.0

**Comment by peterzhu2118** [comment]
There's discussions about allowing permanent URLs in Active Storage from the service in issue #31419 with various workarounds and proposed solutions.
