### ISSUE TITLE
zeitwerk:check fails due to file in ActiveSupport::Dependencies.autoload_paths

### ISSUE THREAD

**Issue by zaben903** [rails/rails#36461]
### Steps to reproduce

1. `rails new zeitwerk`
2. `rails generate channel EventsChannel`
3. Set `config.autoloader = :classic` in `application.rb` 
4. Run `rails zeitwerk:check`

### Expected behavior
zeitwerk:check should pass.

### Actual behavior
fails with `Errno::ENOTDIR: Not a directory @ dir_initialize - {Rails.root}/app/channels/events_channel.rb`

### Suspected Issue
File: `railties-6.0.0.rc1/lib/rails/engine/configuration.rb`
In `def paths` the path for channels is added with `glob: **/*_channel.rb` this causes files in `app/channels` with the format `**/*_channel.rb` to be added to `ActiveSupport::Dependencies.autoload_paths`
For example:
`["{Rails.root}/app/channels",
 "{Rails.root}/app/controllers",
 "{Rails.root}/app/controllers/concerns",
 "{Rails.root}/app/datatables",
 "{Rails.root}/app/helpers",
 "{Rails.root}/app/jobs",
 "{Rails.root}/app/mailers",
 "{Rails.root}/app/models",
 "{Rails.root}/app/models/concerns",
 "{Rails.root}/ops-db/app/services",
 "{Rails.root}/app/channels/events_channel.rb",
...omitted...]`

### System configuration
Rails.6.0.0.rc1
Ruby 2.5.1

**Comment by fxn** [comment]
This is not right, `autoload_paths` have to be directories.

**Comment by liamwhite** [comment]
Confirmed. Before even setting any paths in my config/application.rb, `config.eager_load_paths` has these extraneous file entries:
```rb
(byebug) pp config.eager_load_paths
[ # ...
 "/vagrant/app/channels/bots_channel.rb",
 "/vagrant/app/channels/notification_channel.rb"]
```
That most likely comes from here:
https://github.com/rails/rails/blob/186edaedfcfe1f33414808ebf91a4b6201c6c46e/railties/lib/rails/engine/configuration.rb#L46
