### ISSUE TITLE
upload works in dev - not in production if larger than a few KB

### ISSUE THREAD

**Issue by wdiechmann** [rails/rails#36464]
### Steps to reproduce
All code is at https://github.com/wdiechmann/sucker.git

### Expected behavior
I would like https://sucker.alco.dk/messages/new to be able to accept multiple larger files/images

### Actual behavior
In development I can upload any number of files, but in production - I can get away with one file, if it is not larger than a few (8-ish) KB

### System configuration
**Rails version**: 5.2.3

**Ruby version**: 2.5.1

**Comment by jbosse** [comment]
My guess is nginx is the problem not a Rails limitation. If you can find the `nginx.conf` file on your host, look for `client_max_body_size` to see if it is large enough, for example `100M`.

**Comment by wdiechmann** [comment]
I wish it was but sadly - like it says in the repo/config/sucker.nginx.conf
```
  server_name _FQDN_;
  client_max_body_size 4G;
```
and the only reason why I barked up the Rails tree is that I have it in production (not the sucker obviously, that's just the gist of it) on another VM and the only thing to divide the two is that on this little fellow ActionCable actually works (so in my reasoning I can either have cable or storage) 👶

**Comment by y-yagi** [comment]
Please use the [mailing list](https://groups.google.com/forum/#!forum/rubyonrails-talk) or StackOverflow for questions/help, where a wider community will be able to help you. We reserve the issues tracker for issues only.

**Comment by wdiechmann** [comment]
I know this is closed - and rightfully so - but in the (unlikely event) that someone should browse by, allow me to attach a link to [this repo](https://github.com/wdiechmann/sucker/blob/master/README.md) where I explain what was the issue (file permissions really)
