### ISSUE TITLE
ConnectionPool.connections provides public unsynchronized access to @connections

### ISSUE THREAD

**Issue by jeffdoering** [rails/rails#36465]
ConnectionPool documentation is very crisp on the need to synchronize access to @connections but also states that public methods do not require synchronization:

https://github.com/rails/rails/blob/96f142ae76b04f5ffe6e4c33550f5b04739f4f56/activerecord/lib/active_record/connection_adapters/abstract/connection_pool.rb#L96

But this attribute reader appears to blur that definition by creating a public method that directly exposes @connections

https://github.com/rails/rails/blob/96f142ae76b04f5ffe6e4c33550f5b04739f4f56/activerecord/lib/active_record/connection_adapters/abstract/connection_pool.rb#L362

This method shows what looks like the correct access pattern.

https://github.com/rails/rails/blob/96f142ae76b04f5ffe6e4c33550f5b04739f4f56/activerecord/lib/active_record/connection_adapters/abstract/connection_pool.rb#L470

`synchronize { @connections.any? }`

The documentation should either clarify the requirement to synchronize around access to connections or the public connections reader should be replaced with a method that copies the array so that concurrent enumeration is safe (albeit holding connections in arbitrary states).

We noticed this because DataDog is searching for connections by object_id on Rails < 6 when this PR gave direct access: [Pass the `connection` to the `@instrumenter.instrument` method call #34602](https://github.com/rails/rails/pull/34602)

The original need was described here: [Pass the `connection` to the `@instrumenter.instrument` method call #34568](https://github.com/rails/rails/pull/34568)

But with that method added the fallback code is doing:

`::ActiveRecord::Base.connection_handler.connection_pool_list
                     .flat_map(&:connections).find { |c| c.object_id == connection_id }`

https://github.com/DataDog/dd-trace-rb/blob/2e0a3b2d6b8dbf4aa609c1e47ddd4ec2a45a018f/lib/ddtrace/contrib/active_record/utils.rb#L46

Old (ancient) notes even suggested this kind of pattern:

[Include the database configuration in activerecord notifications. #11284](https://github.com/rails/rails/pull/11284)

The reference to DataDog here is just a concrete example. The request here is to either clarify the documentation on safe public methods or change the way `connections` is implemented so it meets the current documentation.

**Comment by rafaelfranca** [comment]
I believe we should implement the method to copy the original array. Can you open a PR?
