### ISSUE TITLE
Updating an attribute to a symbol value with update_columns and reading attribute causes a change on that attribute to be falsely reported

### ISSUE THREAD

**Issue by TylerRick** [rails/rails#36463]
### Steps to reproduce

```ruby
require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"
  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  gem "rails", github: "rails/rails"
  gem "sqlite3"
end

require "active_record"
require "minitest/autorun"
require "logger"

ActiveRecord::Base.establish_connection(adapter: "sqlite3", database: ":memory:")
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :comments, force: true do |t|
    t.string :something
  end
end

class Comment < ActiveRecord::Base
end

class BugTest < Minitest::Test
  def test_association_stuff
    comment = Comment.create!
    comment.update_column :something, :anything
    comment.something  # or comment.attributes
    assert_nil comment.something_change
  end
end
```

### Expected behavior

I expect `update_column :something, :anything` to behave the same as `update_column :something, 'anything'`.

I expect reading the attribute (with `comment.something`, `comment.read_attribute(:something)`, or `comment.attributes`), to have no effect on `comment.something_change` or `comment.changes`.

### Actual behavior

The test case above fails with:
```
Failure:
BugTest#test_association_stuff [update_columns_with_symbol_value_bug.rb:37]:
Expected ["anything", "anything"] to be nil.
```

However, if you change the value from a symbol to a string, it passes:
```ruby
    comment.update_column :something, 'anything'
```

Or, if you remove this line, it passes:
```ruby
    comment.something  # or comment.attributes
```

The workaround appears to be to only use string values with `update_column` on string columns, but this seems like a buggy behavior nonetheless and could easily surprise users who aren't aware of this subtle caveat. It has caused some breakage in an app I'm upgrading from Rails 5.1.

In either case (setting to a string or a symbol), it generates the same SQL:
```
UPDATE "comments" SET "something" = ? WHERE "comments"."id" = ?  [["something", "anything"], ["id", 1]]
```

and in either case the attribute's value ends up being cast to a string:
```ruby
  assert_equal 'anything', comment.something
```

So what happens differently when setting to a symbol value, and how does the combination of setting to a symbol and then reading the attribute(s), cause dirty-tracking/change-tracking to get confused??

### System configuration
**Rails version**: Observed this behavior on 5.2, 6.0.rc1, and master. This behavior is _not_ present on 5.1 (tested against `5-1-stable` branch).

**Ruby version**: `ruby 2.6.0p0`

**Comment by wjessop** [comment]
I bisected and it looks like c342d58446defad94f26c067b19003c9941f2470 introduced the change in behavior.
