### ISSUE TITLE
rails db:prepare fails when pending migrations exist

### ISSUE THREAD

**Issue by Medvezo** [rails/rails#36474]
### Steps to reproduce
`bin/rails db:rollback`
`bin/rails db:drop`
`bin/rails db:prepare`

### Expected behavior
It is more of a problem with a `bin/rails db:setup` that `db:prepare` calls internally.

### Actual behavior
`bin/setup` fails
```
Created database 'weblog_development'
Created database 'weblog_test'
You have 1 pending migration:
  20190613143205 CreatePosts
Run `rails db:migrate` to update your database then try again.
```

### System configuration
**Rails version**: 6.0.0rc1

**Ruby version**: 2.6.3

**Comment by morgoth** [comment]
@Medvezo could you try Rails from "6-0-stable" branch? Hope to be fixed in https://github.com/rails/rails/pull/36416

**Comment by Medvezo** [comment]
@morgoth tried with `gem 'rails', github: 'rails/rails', branch: '6-0-stable'`

This time, `bin/rails db:prepare` created the database, seeded it, but didn't run migrations. Is this the expected behavior?

**Comment by morgoth** [comment]
hmm, but looks like it is in inconsistent state - you have pending migration, thus it was not yet added to "schema.rb" and then you drop db. 
"db:setup" task just loads the schema as it should have the current state of the db reflected already in it.
I would say it's expected :-)

**Comment by Medvezo** [comment]
@morgoth Gotcha! Thanks for your time!
