### ISSUE TITLE
javascript_pack_tag and stylesheet_pack_tag(s) not rendering correctly in RAILS_ENV=production

### ISSUE THREAD

**Issue by nwclouddev** [rails/rails#36489]
### Steps to reproduce
When creating a fresh rails 6 instance via rails new exampleapp, javascript_pack_tag and stylesheet_pack_tag are not routing the resources properly when in Production environment. vanilla Webpacker.yml file indicates the proper routes below:

default:
  source_path: app/javascript
  source_entry_path: packs
  public_root_path: public
  public_output_path: packs
  cache_path: tmp/cache/webpacker
  check_yarn_integrity: false
  webpack_compile_output: false
  resolved_paths: &ref_0 []
  cache_manifest: false
  extract_css: false
  static_assets_extensions: &ref_1
    - .jpg
    - .jpeg
    - .png
    - .gif
    - .tiff
    - .ico
    - .svg
    - .eot
    - .otf
    - .ttf
    - .woff
    - .woff2
  extensions: &ref_2
    - .mjs
    - .js
    - .sass
    - .scss
    - .css
    - .module.sass
    - .module.scss
    - .module.css
    - .png
    - .svg
    - .gif
    - .jpeg
    - .jpg
development:
  source_path: app/javascript
  source_entry_path: packs
  public_root_path: public
  public_output_path: packs
  cache_path: tmp/cache/webpacker
  check_yarn_integrity: true
  webpack_compile_output: false
  resolved_paths: *ref_0
  cache_manifest: false
  extract_css: false
  static_assets_extensions: *ref_1
  extensions: *ref_2
  compile: true
  dev_server:
    https: false
    host: localhost
    port: 3035
    public: 'localhost:3035'
    hmr: false
    inline: true
    overlay: true
    compress: true
    disable_host_check: true
    use_local_ip: false
    quiet: false
    headers:
      Access-Control-Allow-Origin: '*'
    watch_options:
      ignored: '**/node_modules/**'
test:
  source_path: app/javascript
  source_entry_path: packs
  public_root_path: public
  public_output_path: packs-test
  cache_path: tmp/cache/webpacker
  check_yarn_integrity: false
  webpack_compile_output: false
  resolved_paths: *ref_0
  cache_manifest: false
  extract_css: false
  static_assets_extensions: *ref_1
  extensions: *ref_2
  compile: true
production:
  source_path: app/javascript
  source_entry_path: packs
  public_root_path: public
  public_output_path: packs
  cache_path: tmp/cache/webpacker
  check_yarn_integrity: false
  webpack_compile_output: false
  resolved_paths: *ref_0
  cache_manifest: true
  extract_css: true
  static_assets_extensions: *ref_1
  extensions: *ref_2
  compile: true
### Expected behavior
Assets are served properly from path /public/packs/js/*.js/.css, and pack_tags should render
<link rel="stylesheet" media="all" href="/packs/css/application-c4bf5b4d.css" data-turbolinks-track="reload" />
    <script src="/packs/js/application-9e745cebc1d18929e108.js" data-turbolinks-track="reload"></script>

### Actual behavior
However, when ran in production the pack_tags are generated as follows:
<link rel="stylesheet" media="all" href="/public/packs/css/application-c4bf5b4d.css" data-turbolinks-track="reload" />
    <script src="/public/packs/js/application-9e745cebc1d18929e108.js" data-turbolinks-track="reload"></script>

Additionally if public_root_path: public is modified to public_root_path: "" then the following error is thrown during the GET request

ActionView::Template::Error (Webpacker can't find application in exampleapp/packs/manifest.json when the path should resolve to exampleapp/javascript/packs/manifest.json 

I can't locate the source code for the javascript_include_tag that gets called in javascript_pack_tag, but I am theorizing there is an alias issue for the root path that is depended on environment being production

### System configuration
**Rails version**:
6.0.0.rc1

**Ruby version**:
ruby 2.6.3p62 (2019-04-16 revision 67580) [x86_64-linux]

**Comment by y-yagi** [comment]
Please use the [Rails Core mailing list](https://groups.google.com/forum/#!forum/rubyonrails-core) for feature requests, where a wider community will be able to help you. We reserve the Rails issue tracker only for bugs in Rails. Thanks!

**Comment by nwclouddev** [comment]
I'm not sure if you meant your response for this issue. I am not making a feature request. The handling of webpacker asset handling seems to be behaving incorrectly out of of the box in production environment. I am deploying to an AWS EB instance, and for all I can tell, all webpacker parameters are configured per the documentation.

**Comment by y-yagi** [comment]
Oh, I'm sorry. Apparently, I was wrong in the issue to comment. But anyway this issue is closed.

Please use the [mailing list](https://groups.google.com/forum/#!forum/rubyonrails-talk) or StackOverflow for questions/help, where a wider community will be able to help you. We reserve the issues tracker for Rails' issues only. Thanks!

**Comment by louim** [comment]
@nwclouddev the webpacker behaviour you describe is the correct one. Normally as part of the deploy process, [assets should be precompiled with `rails assets:precompile`](https://github.com/rails/webpacker#deployment). Tools like Capistrano will do so automatically while deploying. If you deploy with something else / manually, you may have to run the command in your production environment. ex `RAILS_ENV=production bin/rails assets:precompile`.
