### ISSUE TITLE
What can be the reason of “Unable to find subscription with identifier” in Rails ActionCable?

### ISSUE THREAD

**Issue by RobertS92** [rails/rails#36480]
Hello Everyone,

We have the iOS Application in which we are using the action cable to give me fast response as user like something or comment on any post. Few days bas everything is working fine. But from last few days action cable is not working. And my iOS application is live on the App Store. When ever my back end developer broadcast from her side. I will not get the response. When I hit  the action cable multiple times. Then I get the single response out of 4 of them.

Now if any body help me what can I do right now. 

What can be the reason of “Unable to find subscription with identifier” in Rails ActionCable?

Unable to find subscription with identifier: {"channel":"CommonChannel","auth_token":"zoRGfSZhS3mH6UxENVcJ"}]

We have a single channel in which we have multiple actions because I cannot subscribe the channel every time and then hit any function it makes me irritate to do every time subscribe the channel and then call the function.

Does any body has the solution for this issue. We have tried the wait loop as well after subscribing any channel.

Please anybody help us. I hate action cable.

Thanks in advance.

**Comment by RobertS92** [comment]
![PHOTO-2019-06-14-10-43-36](https://user-images.githubusercontent.com/20169616/59484944-7f615c80-8e91-11e9-8b39-33c36c61e6b9.jpg)

See this image,, we are getting runtime error on Action Cable.

**Comment by y-yagi** [comment]
Please use the [mailing list](https://groups.google.com/forum/#!forum/rubyonrails-talk) or StackOverflow for questions/help, where a wider community will be able to help you. We reserve the issues tracker for issues only. Thanks.
