### ISSUE TITLE
Delegate does not fail for has_many dependent destroy

### ISSUE THREAD

**Issue by nyddogghr** [rails/rails#36485]
### Steps to reproduce
The following files show two models, Bar belonging to Foo. When destroying a Foo, it destroys associated Bars, that trigger a delegated method as after_commit.

The issue is that the delegate doesn't fail properly with a `Module::DelegationError` *unless* using any scope on the relation, such as `has_many :bars, -> { order 'bars.id' }, dependent: :destroy`.

```rb
class Bar < ActiveRecord::Base
  belongs_to :foo
  delegate :foobar, to: :foo
  after_commit :foobar
end
```
```rb
class Foo < ActiveRecord::Base
  has_many :bars, dependent: :destroy
  def foobar
    puts "foobar #{self.id}"
  end
end
```
```rb
class AddFooAndBar < ActiveRecord::Migration[5.2]
  def change
    create_table :foos do
    end

    create_table :bars do |t|
      t.references :foo
    end
  end
end
```

### Expected behavior
When destroying the Foo object, it should raise an error.
We can see it when using `has_many :bars, -> { order 'bars.id' }, dependent: :destroy`:
```rb
[1] pry(main)> foo = Foo.create!
   (0.1ms)  BEGIN
  Foo Create (0.3ms)  INSERT INTO "foos" DEFAULT VALUES RETURNING "id"
   (1.8ms)  COMMIT
=> #<Foo:0x0000560643d9dce0 id: 9>
[2] pry(main)> bar = Bar.create!(foo: foo)
   (0.2ms)  BEGIN
  Bar Create (0.9ms)  INSERT INTO "bars" ("foo_id") VALUES (9) RETURNING "id"
   (1.8ms)  COMMIT
  Foo Load (0.4ms)  SELECT  "foos".* FROM "foos" WHERE "foos"."id" = 9 LIMIT 1
foobar 9
=> #<Bar:0x0000560643e0c230 id: 9, foo_id: 9>
[3] pry(main)> foo.destroy!
   (0.3ms)  BEGIN
  Bar Load (0.5ms)  SELECT "bars".* FROM "bars" WHERE "bars"."foo_id" = 9 ORDER BY bars.id
  Bar Destroy (0.2ms)  DELETE FROM "bars" WHERE "bars"."id" = 9
  Foo Destroy (0.2ms)  DELETE FROM "foos" WHERE "foos"."id" = 9
   (2.0ms)  COMMIT
  Foo Load (0.3ms)  SELECT  "foos".* FROM "foos" WHERE "foos"."id" = 9 LIMIT 1
Module::DelegationError: Bar#foobar delegated to foo.foobar, but foo is nil: #<Bar id: 9, foo_id: 9>
from /home/flof/Git/ottsm/app/models/bar.rb:3:in `rescue in foobar'
Caused by NoMethodError: undefined method `foobar' for nil:NilClass
from /home/flof/Git/ottsm/app/models/bar.rb:3:in `foobar'
```

### Actual behavior
Instead, the delegated method is executed
```rb
[1] pry(main)> foo = Foo.create!
   (0.1ms)  BEGIN
  Foo Create (0.3ms)  INSERT INTO "foos" DEFAULT VALUES RETURNING "id"
   (1.6ms)  COMMIT
=> #<Foo:0x0000562d5ef68100 id: 11>
[2] pry(main)> bar = Bar.create!(foo: foo)
   (0.1ms)  BEGIN
  Bar Create (0.5ms)  INSERT INTO "bars" ("foo_id") VALUES (11) RETURNING "id"
   (1.6ms)  COMMIT
foobar 11
=> #<Bar:0x0000562d5efde5f8 id: 11, foo_id: 11>
[3] pry(main)> foo.destroy!
   (0.2ms)  BEGIN
  Bar Load (0.4ms)  SELECT "bars".* FROM "bars" WHERE "bars"."foo_id" = 11
  Bar Destroy (0.3ms)  DELETE FROM "bars" WHERE "bars"."id" = 11
  Foo Destroy (0.2ms)  DELETE FROM "foos" WHERE "foos"."id" = 11
   (1.8ms)  COMMIT
foobar 11
```

### System configuration
**Rails version**: Rails 5.2.3

**Ruby version**: ruby 2.5.5p157 (2019-03-15 revision 67260) [x86_64-linux]

**Comment by Everett1025** [comment]
The behavior is correct and runs as expected.  When you destroy an instance of Foo the local instance is frozen not deleted.  Though the record in the database is deleted.  Therefore, foobar will have access to the local instance even after the record has been deleted from the database.  This also does not guarantee your object has been completely deleted from memory. Ruby garbage collection does not run until all references to the object in memory have been lost.

https://apidock.com/rails/v5.2.3/ActiveRecord/Persistence/destroy%21

**Comment by eugeneius** [comment]
As mentioned above, destroying a record doesn't remove it from other records' loaded associations, so this is expected behaviour. Adding a scope to the `bars` association is causing automatic inverse detection to be disabled, so the Bar doesn't try to load the Foo until after it's destroyed.
