### ISSUE TITLE
ActiveRecord::Base.descendants / ActiveRecord::Base.subclasses broken?

### ISSUE THREAD

**Issue by EverardB** [rails/rails#36496]
### Steps to reproduce
rails new app
cd app
rails g model Model1
rails g model Model2
rails c
irb> ActiveRecord::Base.descendants
irb> ActiveRecord::Base.subclasses

### Expected behavior
Should return all ActiveRecord models

### Actual behavior
Only one model (or empty array) is returned

### System configuration
**Rails version**: 6.0.0.rc1
**Ruby version**: 2.6.3p62

**Comment by fxn** [comment]
Ruby only knows classes that have been loaded, it doesn' scan the disk. In development mode, code is loaded on demand (autoloaded):

```
→ app (master)$ bin/rails c
Running via Spring preloader in process 34549
Loading development environment (Rails 6.0.0.rc1)
irb(main):001:0> ActiveRecord::Base.descendants
=> []
irb(main):002:0> ActiveRecord::Base.subclasses
=> []
irb(main):003:0> Model1; Model2
=> Model2 (call 'Model2.connection' to establish a connection)
irb(main):004:0> ActiveRecord::Base.descendants
=> [ApplicationRecord(abstract), Model1 (call 'Model1.connection' to establish a connection), Model2 (call 'Model2.connection' to establish a connection)]
irb(main):005:0> ActiveRecord::Base.subclasses
=> [ApplicationRecord(abstract)]
```

**Comment by vizo** [comment]
Any way to preload them in development mode?

**Comment by chaadow** [comment]
With zeitwerk I managed to find a way in development mode by running this : 
`Zeitwerk::Loader.eager_load_all` 
I used to run `Rails.application.eager_load!` in "classic mode"
