### ISSUE TITLE
Rails installation error because ruby installer cannot find openssl

### ISSUE THREAD

**Issue by zendevil** [rails/rails#36498]
I'm trying to install Ruby 2.6.3 from source for ruby on rails on WSL. Here are the steps I'm taking:
First I check the location of openssl using 
```
type -a openssl
```
and I get 
```
openssl is /usr/bin/openssl
```

so in the ruby src directory I run 
```./configure --with-openssl-dir=/usr/bin```
Then I run ```make```
But I get this message somewhere during the make process:

```
openssl:
        Could not be configured. It will not be installed.
        /mnt/c/Users/MyUserName/Desktop/ruby-2.6.3/ext/openssl/extconf.rb:97: OpenSSL library could not be found. You might want to use --with-openssl-dir=<dir> option to specify the prefix where OpenSSL is installed.
        Check ext/openssl/mkmf.log for more details.

```
Regardless of this warning, I run in the rails src directory the following:

```
gem install rails
```
and get the error:
 
```
`require': cannot load such file -- openssl (LoadError)
```

**Comment by yoones** [comment]
@zendevil this is not related to Rails.

Ensure your openssl version works for the ruby version you want to install. If you're sure there's an issue to resolve, this probably should be submitted on ruby's bugtracker, not rails'.

**Comment by andrewmcodes** [comment]
What’s your OS? I have hit this on MacOS a few times but usually it’s an issue with Xcode.

**Comment by eileencodes** [comment]
Hey @zendevil I'm going to close this because this isn't an issue with Rails but with Ruby and we only use the issue tracker for Rails bugs.
