### ISSUE TITLE
Mirroring upload jobs require every app to configure it

### ISSUE THREAD

**Issue by mperham** [rails/rails#36499]
The new mirror upload feature added by @georgeclaghorn creates background jobs to upload.  It puts those jobs in a new queue `active_storage_mirror`.  The problem is that Sidekiq (maybe other providers?) requires every queue to be pre-declared for processing so any app that wants to use this feature will need to add `-q active_storage_mirror` to their Sidekiq config also, likely after spending hours debugging why their mirroring is not working.

https://github.com/rails/rails/pull/36312/files#diff-c76fb6202b7f95a08fe12f40c4999ac9R7

I would suggest this feature follow a different pattern: don't specify the queue **unless** the user configures it otherwise. This way the feature will automatically work with every app without any custom configuration.  Use convention over configuration.

**Comment by georgeclaghorn** [comment]
Closing in favor of #40730.

**Comment by andrezimpel** [comment]
@mperham I am running into the same issue. I am using delayed job. Mirror Jobs won't show up at all. :/
