### ISSUE TITLE
Attribute method won't be defined by composed_of for ActiveRecord

### ISSUE THREAD

**Issue by Samemura** [rails/rails#36501]
### Steps to reproduce
Refer to [composed_of](https://github.com/rails/rails/blob/6a033a06855f0b7a407ff8edbfc9f9aa45527edc/activerecord/lib/active_record/aggregations.rb#L102), it looks attribute method like `Customer#address_street` will be generated automatically. But it won't be generated.

I was using below example code to check behaviour.
```
class Customer < ActiveRecord::Base
  composed_of :address, mapping: [ %w(address_street street), %w(address_city city) ]
end

class Address
  attr_reader :street, :city
  def initialize(street, city)
    @street, @city = street, city
  end

  def close_to?(other_address)
    city == other_address.city
  end

  def ==(other_address)
    city == other_address.city && street == other_address.street
  end
end
```

### Expected behavior
`Customer#address_street` to be defined.

### Actual behavior
`Customer#address_street` was not define.

If it was intended original behaviour, I hope the description will be changed.

### System configuration
rails (5.2.3)
activerecord (= 5.2.3)
ruby '2.6.3'

**Comment by Everett1025** [comment]
I was able to regenerate the problem.  I am looking into it.
