### ISSUE TITLE
Form submit appears to be Ajax by default

### ISSUE THREAD

**Issue by KernelDeimos** [rails/rails#36500]
### Steps to reproduce
Created project with `rails new`, created a controller,
created a form with some manually written form elements. Something like this:
```
<%= form_with url: "sets/view" do |form| %>
	<input type="text" name="values[]" /><br>
	<input type="text" name="values[]" /><br>
	<input type="text" name="values[]" /><br>

	<%= form.submit value: "first_action" %>
<% end %>
```

This view is for the endpoint `sets/definition`, where the user enters values to get to `sets/view`.

### Expected behavior
Form submits and the user is redirected to `sets/view` with the results. (Right now, just a literal array defined in the controller with no additional logic)

### Actual behavior
Form is submitted. Data is sent to the browser but as if an Ajax request was performed. I've also tried adding `remote: false` to both the form and the submit button. The page where the user entered values is still displayed.

I also tried disabling UJS by removing the `//=require rails_ujs` line from application.js. This produces an error with the token (`ActionController::InvalidAuthenticityToken`).

### System configuration
**Rails version**: 5.2.3
**Ruby version**: ruby 2.5.1p57 (2018-03-29 revision 63029) [x86_64-linux-gnu]

**Comment by robzolkos** [comment]
Rails sends an XHR request by default for forms.  Put local: true to disable this behaviour.

**Comment by KernelDeimos** [comment]
Just to clarify my understanding, is there a specific reason `remote: false` doesn't do this? I read that `remote: true` was used to enable XHR so I expected `remote: false` to do the opposite

**Comment by robzolkos** [comment]
`form_for` uses `remote` (and its off by default) and `form_with` uses `local`   

`form_with` is the newer style and XHR is enabled by default.
