### ISSUE TITLE
activestorage sometimes return wrong file URL.

### ISSUE THREAD

**Issue by mehnazb3** [rails/rails#36505]
I am using activestorage to upload file in my project. Sometimes I get wrong url, though the actual file is saved in s3 but url does not match the saved file. Its happens randomly.

I am using below ruby and rails versions
**Rails version**: 5.2.1

**Ruby version**: 2.5.1

Does anyone facing similar issue? Any help if much appreciated.

**Comment by y-yagi** [comment]
Can you provide an example application that reproduces the issue?
