### ISSUE TITLE
Misleading route definition should produce warning

### ISSUE THREAD

**Issue by jaredbeck** [rails/rails#36516]
Here is a way we can help people understand routes better!

### Steps to reproduce

```
# config/routes.rb
namespace :checkout do
  get '/review', controller: 'review', action: 'show'
```

The slash is misleading. No pun intended (it's a "leading" slash) ok now there's a pun, sorry

### Expected behavior

Produce a warning like:

> Misleading route:
> namespace :checkout do .. get '/review' looks like it responds to /review but
> actually it responds to /checkout/review
> Please write get 'review' instead (without the slash)

This warning could be produced by `rake routes`, or by `rails server`, or both.

### Actual behavior

No warning is produced.

### System configuration
**Rails version**: 5.2.3
**Ruby version**: 2.6.3

**Comment by jaredbeck** [comment]
I'm happy to work on this if a committer will approve it.

**Comment by rafaelfranca** [comment]
Thank you so much for the issue but we don't take feature request on the issue tracker. We recommend you to try to implement the feature and send us a pull request or if you are in doubt if the feature will be accepts ask in Rails Core mailing list for feedback.

**Comment by jaredbeck** [comment]
>> I'm happy to work on this if a committer will approve it.

> .. if you are in doubt if the feature will be accepts ask in Rails Core mailing list for feedback.

@rafaelfranca I'd love to join the mailing list, but it requires a Google account, which, for personal reasons, I don't want to have. Sorry to be a bother. Is there an alternative way for me to get feedback? Thanks.
