### ISSUE TITLE
Need to access active_model_serializer object into rails controller

### ISSUE THREAD

**Issue by naziahashim** [rails/rails#36517]
### Steps to reproduce

I tried to access by ModelSerializer.new(Model.first) in my controller to get serializer value into my controller but no show.
### System configuration
**Rails version**:
5

**Ruby version**:
2.3

**Comment by y-yagi** [comment]
Please use the [mailing list](https://groups.google.com/forum/#!forum/rubyonrails-talk) or StackOverflow for questions/help, where a wider community will be able to help you. We reserve the issues tracker for issues only.
