### ISSUE TITLE
AR: `self.implicit_order_column` not always respected 6.0.0.rc1

### ISSUE THREAD

**Issue by vfonic** [rails/rails#36536]
// related to [Make it possible to override the implicit order column #34480
](https://github.com/rails/rails/pull/34480)

### Steps to reproduce

1. `git clone https://github.com/vfonic/martian-library`
2. `bundle install`
3. `rails db:create db:migrate db:seed`
4. Edit `app/models/item.rb` => `self.implicit_order_column = 'title'`
5. Run `rails console` and query for items: `Item.pluck(:title)`

(`Item.all` also doesn't apply correct ordering.)
(`Item.first`, `Item.last` returns correct ordering.)

### Expected behavior

Item titles are returned in alphabetical order.

### Actual behavior

The default ordering is returned.

### Extra details

Here are some more issues/things I've tried:

```ruby
self.implicit_order_column = :title # works
self.implicit_order_column = 'title DESC' # doesn't work
self.implicit_order_column = 'title ASC' # doesn't work
self.implicit_order_column = title: :desc # doesn't work
self.implicit_order_column = { title: :desc } # doesn't work
```

It would be great if these would work as well, just like they work when doing `Item.order(title: :desc)`. I understand this is easier said than done, though...

/cc @tekin 

### System configuration
**Rails version**:
Rails 6.0.0.rc1
**Ruby version**:
ruby 2.6.3p62 (2019-04-16 revision 67580) [x86_64-darwin18]

**Comment by rafaelfranca** [comment]
Thank you for the issue. As the config say, it points to a column, so it is not an config to also change the order direction. If you need to change the direction as well a default scope is more suited.

**Comment by vfonic** [comment]
Thanks for reviewing this issue.

What about `Item.all` and `Item.pluck(:title)` not returning items ordered by title? I think making this a public API, it should account for those cases as well.

**Comment by rafaelfranca** [comment]
This only change `first` and `last` that are the method that have an implicit order.

**Comment by vfonic** [comment]
Ah I see. I thought this is a substitute for ordering via `default_scope`. Thank you!
