### ISSUE TITLE
HashWithIndifferentAccess doesn't work with % format operator

### ISSUE THREAD

**Issue by tikh** [rails/rails#36533]
### Steps to reproduce

In Rails 5.2.3: 
```
2.3.8 :001 > "%{a}" % {"a" => 1}.with_indifferent_access
KeyError: key{a} not found
	from (irb):1:in `%'
	from (irb):1
```

Whereas in Rails 4.2.11:
```
2.3.8 :001 > "%{a}" % {"a" => 1}.with_indifferent_access
 => "1"
```

For both Rails version I tried to create an empty Rails app to avoid the influence from other gems.

### Expected behavior
`%` format operator should work with `HashWithIndifferentAccess` objects the same way as with `Hash`'s with symbol keys.  

### Actual behavior
`%` is not able to find an element in the instance of `HashWithIndifferentAccess`. 

### System configuration
**Rails version**:
Works in Rails 4.2.11 but broken in 5.2.3.
**Ruby version**:
Ruby 2.3.8

**Comment by kaspth** [comment]
Hey, I'm sorry but Rails 4.2 isn't supported for bug fixes any longer. It's too long back to consider this a real regression. If you can prove that Rails 5.1 had the same behavior as 4.2 we can revisit, otherwise the ship has unfortunately sailed. I'll close for now, thank you 😊

**Comment by tikh** [comment]
@kaspth I've tested with Rails 5.1 and it doesn't work too. Thanks for explaining the policy regarding the regressions.
