### ISSUE TITLE
Rails image_tag does not generate the digest in production

### ISSUE THREAD

**Issue by john-999** [rails/rails#36539]
### Steps to reproduce
0. In ```environments/development.rb```, set: ```config.assets.prefix = "/dev-assets"```
1. In ```environments/production.rb```, set: ```config.assets.compile = false```
2. Precompile the assets: ```rails assets:precompile```

### Expected behavior
In production, the following tag should generate a "digest" for the asset path:
```<%= image_tag('tom.jpg') %>```

### Actual behavior
The tag does NOT generate a "digest" for the asset path.

Thus, the asset can not be loaded and Rails' production log file mistakenly thinks:

```"ActionView::Template::Error (The asset "tom.jpg" is not present in the asset pipeline.)"```

The digest is only generated when in ```environments/production.rb```, we set: ```config.assets.compile = true``` (which would be wrong, given the fact that we want to precompile only).

### System configuration
**Rails version**: ```Rails 5.2.3```

**Ruby version**: ```ruby 2.6.3p62```

**Comment by jeremy** [comment]
Sounds like you have `config.assets.digest = false` by some means. Could you do some troubleshooting to understand whether that's set?

Also, do these steps reproduce the issue with a newly generated app, or are they a summary of a scenario you're seeing in an existing app?

**Comment by john-999** [comment]
There is no explicit setting of this variable to be found in any of the environment files or elsewhere.

But when I put ```<%= Rails.application.config.assets.digest %>``` in a view, I get ```true``` (in both development and production mode).

(I currently don't have the time to investigate with a newly generated app - urgent deadline in front of me...)

**Comment by saschagehlich** [comment]
I'm getting the `The asset "..." is not present in the asset pipeline.` error, too. I've also set `config.assets.digest` to `false`, but `image_tag` should still work, shouldn't it?

**Comment by tylerklose** [comment]
I was running into the same exact issue. The problem seemed to be that I forgot to include `config.assets.resolve_with = %i[manifest]` in `config/environments/production.rb`
