### ISSUE TITLE
none.except(:where) does not work as expected

### ISSUE THREAD

**Issue by akimd** [rails/rails#36549]
### Steps to reproduce
A query such as `User.where(id: 1).except(:where)` behaves like `User.all`.
Unfortunately, `User.none.except(:where)` does not behave like `User.all`, it behaves like `User.none`.

### Expected behavior
Behave like `all`.

### Actual behavior
Behaves like `none`.

### System configuration
**Rails version**: 5.2.3

**Ruby version**: 2.3.7

Cheers!

**Comment by rafaelfranca** [comment]
Thank you for the issue. This is by design. `none` is a special scope that can't be reverted. If you want to make it a valid relation again it is better to use call `User.all` instead of `User.none.except(:where)`

**Comment by akimd** [comment]
Hi Rafael, thanks for your answer!

> `none` is a special scope that can't be reverted.

Yes, it is very special.  Just like 0 is very special among integers, yet it's an integer, and like ∅ among sets, yet it's a set (weirdly even, it's a super set :-).

The fact that it does not fully behave like a scope creates loopholes that can easily be avoided.  For instance, to "or" two scopes, I run this:

```
sc_base = sc1.except(:where, :having)
        .merge(sc2.except(:where, :having))
        .except(:limit, :offset, :distinct)
sc = sc_base.merge(sc1.only(:where, :having))
        .or(sc_base.merge(sc2.only(:where, :having)))
```

Unfortunately, `all OR none` behaves like `none`, because `none.except(:where)` does return `all`.  If it did, then `none` would be a better relation, instead of being half of one.

On the other hand, if Rails were to provide something similar to the piece of code above, I would probably not have to do that.

> If you want to make it a valid relation again it is better to use call User.all instead of User.none.except(:where)

:) :) :)

Yes, of course.  And actually, since `none` returns an empty array, you could just remove `none` and tell users to directly use an empty array :)  But the beauty of 0 being an integer and ∅ being a set, is that there's no special case to take into account.

Cheers!
