### ISSUE TITLE
Database config options being discarded when merged with DATABASE_URL

### ISSUE THREAD

**Issue by adamlogic** [rails/rails#36559]
We found this issue running the Rails 6 RC in production when the `pool` size we specified in `database.yml` was not being used. In our case, this manifested itself as `ActiveRecord::ConnectionTimeoutError` because our database pool was too small for the number of Sidekiq threads running.

It appears that when `DATABASE_URL` is set, all other options in `database.yml` are discarded UNLESS there is a [single option with a string value](https://github.com/rails/rails/blob/f6db8b8d8286730757570a8b0f92e6b6be779fa8/activerecord/lib/active_record/database_configurations.rb#L144).

Note that this behavior _seems_ to be covered by an [existing test](https://github.com/rails/rails/blob/f6db8b8d8286730757570a8b0f92e6b6be779fa8/activerecord/test/cases/connection_adapters/merge_and_resolve_default_url_config_test.rb#L247-L260), but that test happens to hit the magic scenario of a single string value. I added some test cases below that are very similar but exhibit the problematic behavior.

I spent some time attempting a fix, but [this line](https://github.com/rails/rails/blob/f6db8b8d8286730757570a8b0f92e6b6be779fa8/activerecord/lib/active_record/database_configurations.rb#L144) seems like it does something important... I'm just unclear on the intent.

### Steps to reproduce

```ruby
# frozen_string_literal: true

require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  gem "rails", github: "rails/rails"
  gem "sqlite3"
end

require "active_record"
require "minitest/autorun"
require "logger"

# This connection will do for database-independent bug reports.
# ActiveRecord::Base.establish_connection(adapter: "sqlite3", database: ":memory:")
ActiveRecord::Base.logger = Logger.new(STDOUT)

class DatabaseConnectionTest < Minitest::Test
  def resolve_config(config)
    configs = ActiveRecord::DatabaseConfigurations.new(config)
    configs.to_h
  end

  def test_merge_no_conflicts_with_database_url_and_numeric_pool
    ENV["DATABASE_URL"] = "postgres://localhost/foo"

    config   = { "default_env" => { "pool" => 5 } }
    actual   = resolve_config(config)
    expected = { "default_env" =>
                  { "adapter"  => "postgresql",
                    "database" => "foo",
                    "host"     => "localhost",
                    "pool"     => 5
                  }
                }
    assert_equal expected, actual

    ENV["DATABASE_URL"] = nil
  end

  def test_merge_no_conflicts_with_database_url_and_adapter
    ENV["DATABASE_URL"] = "postgres://localhost/foo"

    config   = { "default_env" => { "adapter" => "postgresql", "pool" => "5" } }
    actual   = resolve_config(config)
    expected = { "default_env" =>
                  { "adapter"  => "postgresql",
                    "database" => "foo",
                    "host"     => "localhost",
                    "pool"     => "5"
                  }
                }
    assert_equal expected, actual

    ENV["DATABASE_URL"] = nil
  end
end
```

### Expected behavior
The `DATABASE_URL` value should be merged with any other options, such as `pool`, `timeout`, `variables`, etc.

### Actual behavior
All options from `database.yml` are discarded.

### System configuration
**Rails version**: master  
**Ruby version**: 2.6.1

**Comment by adamlogic** [comment]
Oh, forgot to mention that there is a workaround—manually adding the `url` config.

```yaml
production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
```

...but I think this will bite a lot of folks who don't even know it's happening.

**Comment by eileencodes** [comment]
Thanks @adamlogic, I'm working on a fix!
