### ISSUE TITLE
Using `puts` to block argument with `with_options` raises an exception

### ISSUE THREAD

**Issue by okuramasafumi** [rails/rails#36551]
### Steps to reproduce

```rb
require 'active_support/core_ext/object'

class Foo
  with_options bar: 42 do |arg|
    puts arg
  end
end
```

### Expected behavior

Nothing happens.

### Actual behavior

It raises an exception:
`/Users/okuramasafumi/.gem/ruby/2.6.3/gems/activesupport-6.0.0.rc1/lib/active_support/option_merger.rb:24:in 'to_s': wrong number of arguments (given 1, expected 0) (ArgumentError)`

### System configuration
**Rails version**: `6.0.0.rc1`

**Ruby version**: `2.6.3`

**Comment by kamipo** [comment]
Thanks for reporting the issue, but looks like this is a limitation for `with_options`.

`puts arg` will call `arg.to_s` then `with_options` will push the option `bar: 42` to `arg.to_s` (i.e. `arg.to_s(bar: 42)`. It is hard to address the case about `arg` is not a most outside receiver.
