### ISSUE TITLE
ActiveRecord::AttributeMethods.attribute_names returns a memoized modifiable array

### ISSUE THREAD

**Issue by jcmfernandes** [rails/rails#36567]
### Steps to reproduce

```ruby
> Product.ancestors.include?(ActiveRecord::Base)
=> true
> Product.attribute_names
=> [:id, :name]
> Product.attribute_names[-1] = nil
=> nil
> Product.attribute_names
=> [:id, nil]
> instance = Product.last
=> #<Product id: ....>
> instance.attribute_names
=> [:id, :name]
> instance.attribute_names[-1] = nil
=> nil
> instance.attribute_names
=> [:id, :name]
```

### Expected behavior

`ActiveRecord::AttributeMethods.attribute_names` should return a `dup` of what it's currently returning.

### Actual behavior

It returns a memoized modifiable array.

### System configuration
**Rails version**: 5.2.2.1

**Ruby version**: trunk

**Comment by rafaelfranca** [comment]
Thank you for the issue but changing Rails to return a copy of the that array is just being defensive to people abusing the framework and have performance impact on applications so we usually don't do this.

**Comment by jcmfernandes** [comment]
Shouldn't that at least be stated in the documentation of the method? I get your/rails rationale but it doesn't seem right to me to have 2 methods with the same name, documentation, and apparent behavior while telling nothing to users about their differences.
