### ISSUE TITLE
Error during WebSocket handshake: 'Connection' header is missing

### ISSUE THREAD

**Issue by shibli786** [rails/rails#36569]
I am working on to implement Real Time notification using Action Cable, which is working fine on my local and when I deployed it on EC2 instance then I am getting this error. I googled a lot to resolve this issue but no luck. Any help will be appreciated.

WebSocket connection to 'ws://example.com/cable' failed: Error during WebSocket handshake: 'Connection' header is missing

However, when I checked the application log I found protocol is successfully upgraded to WebSocket.

Started GET "/cable/" [WebSocket] for -------IP----- at 2019-06-28 13:20:59 +0000
Successfully upgraded to WebSocket (REQUEST_METHOD: GET, HTTP_CONNECTION: upgrade, HTTP_UPGRADE: websocket)

### Expected behavior

Response that i am expecting from the server for handshake is

Sec-WebSocket-Accept:+/zbSswOvE7fwpUWN19gZDUMBfA=
Sec-WebSocket-Protocol:actioncable-v1-json
Server:Apache/2.4.29 (Ubuntu)
Status:101 Switching Protocols
Transfer-Encoding:chunked
Upgrade:websocket
**Connection:Upgrade**      (this header is missing)

### Actual behavior

Actual Response is and Connection header is missing here
Sec-WebSocket-Accept:+/zbSswOvE7fwpUWN19gZDUMBfA=
Sec-WebSocket-Protocol:actioncable-v1-json
Server:Apache/2.4.29 (Ubuntu)
Status:101 Switching Protocols
Transfer-Encoding:chunked
Upgrade:websocket

### System configuration
**Web Server:**  Apache/2.4.29 (Ubuntu)
**App Server** Phusion Passenger 6.0.2
**Rails version**:5.2

**Ruby version**:2.6.0

**Comment by y-yagi** [comment]
Please use the [mailing list](https://groups.google.com/forum/#!forum/rubyonrails-talk) or StackOverflow for questions/help, where a wider community will be able to help you. We reserve the issues tracker for issues only. Thanks!

**Comment by mathieujobin** [comment]
Did you endup finding a solution, or posting your question somewhere else?
its a shame we can't get help in here.
I am having the same issue with Rails 6

**Comment by mathieujobin** [comment]
I just found out
ActionCable is not supported under Passenger+Apache

https://www.phusionpassenger.com/library/config/apache/action_cable_integration/

I am so sad, as it is my favorite server setup, but I can't use ActionCable ;(
