### ISSUE TITLE
ActionText's Trix editor is incompatible with CSP when using nonces

### ISSUE THREAD

**Issue by will-in-wi** [rails/rails#36577]
Test case: https://github.com/will-in-wi/action-text-csp-test-case

Related bug: https://github.com/basecamp/trix/issues/377

### Steps to reproduce

* Create a new application using actiontext.
* Enable default content security policy plus ujs nonces

### Expected behavior
Should not raise CSP errors.

### Actual behavior
Raises CSP errors.

If you disable UJS nonces, you can add `:unsafe_inline` to `policy.script_src` and `policy.style_src` and make it work. However, you cannot use `unsafe-inline` and nonces together.

At this point, you can only have at most two of CSP, UJS, and ActionText.

### System configuration
**Rails version**: Rails 6.0.0.rc1

**Ruby version**: ruby 2.6.3p62 (2019-04-16 revision 67580) [x86_64-darwin18]

**Comment by y-yagi** [comment]
In the Rails side, this will fix with #36534.

@javan Are there any plans to fix anything in Trix? https://github.com/basecamp/trix/issues/377#issuecomment-289857728

**Comment by y-yagi** [comment]
In the Rails side's issue, this fixed with #36534.
For Trix side, let's confirm with https://github.com/basecamp/trix/issues/377. Thanks!
