### ISSUE TITLE
errors.added? for :id seems to be broken

### ISSUE THREAD

**Issue by krtschmr** [rails/rails#36573]
5.2.3 + 2.6.0

having a string as an ID

    create_table :assets, id: :string do |t|
      #...

     class Asset
       validates :id, presence: true, uniqueness: true

creating one Asset, then see if the validation is working

    asset = Asset.create(id: "AAA")
    dup = Asset.new(id: "AAA")
    dup.valid? #=>false
    dup.errors.added?(:id, taken) #=> false
    dup.errors.details[:id]
    => [{:error=>:taken, :value=>"AAA"}]

on other fields, this way of testing which exact error happened is working, seems to not work for `:id`

**Comment by y-yagi** [comment]
This issue can reproduce with Rails 5.2, 6.0. But not reproduce with master branch. Maybe related to #32313.

```ruby 
# frozen_string_literal: true

require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  # gem "rails", github: "rails/rails"
  gem "activerecord", "6.0.0.rc1"
  gem "sqlite3"
end

require "active_record"
require "minitest/autorun"
require "logger"

# This connection will do for database-independent bug reports.
ActiveRecord::Base.establish_connection(adapter: "sqlite3", database: ":memory:")
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :assets, id: :string do |t|
    t.string :name
  end
end

class Asset < ActiveRecord::Base
  validates :id, presence: true, uniqueness: true
end

class BugTest < Minitest::Test
  def test_association_stuff
   asset = Asset.create(id: "AAA")
   dup = Asset.new(id: "AAA")

   refute dup.valid?
   assert dup.errors.added?(:id, :taken)
  end
end 
```

**Comment by vishaltelangre** [comment]
Fixed in https://github.com/rails/rails/pull/36961.

**Comment by krtschmr** [comment]
@vishaltelangre  thanks. i'll close this issue now
