### ISSUE TITLE
QueryCache not working in Capybara transactional tests

### ISSUE THREAD

**Issue by engwan** [rails/rails#36587]
### Steps to reproduce

When `transactional_tests` are enabled, requests to the Capybara web server don't have query cache enabled.

In the controller, `ActiveRecord::Base.connection.query_cache_enabled` is `false`

### Expected behavior

The connection has query cache enabled

### Actual behavior

The query cache middleware enables query caching on the pool. But since we have `transactional_tests`, when we get a connection, we return the shared connection (based on `@lock_thread`) instead of checking out a connection from the pool.

I think this means https://github.com/rails/rails/blob/master/activerecord/lib/active_record/connection_adapters/abstract/query_cache.rb#L13 would not be triggered, causing query cache to not be enabled for the request

### Additional information

We want query cache enabled in test so that it is closer to what happens in development / production. We have tests that check for the number of uncached queries that are now failing after enabling `transactional_tests`.

### System configuration
**Rails version**: 5.1.7

**Ruby version**: 2.6.3

**Comment by engwan** [comment]
cc @eileencodes I'm not sure if this is intended behavior?

**Comment by engwan** [comment]
Having this patch fixes the issue:

```ruby
module ActiveRecord
  module ConnectionAdapters
    module QueryCache
      module ConnectionPoolConfiguration
        def enable_query_cache!
          @query_cache_enabled[connection_cache_key(@lock_thread || Thread.current)] = true
          connection.enable_query_cache! if active_connection?
        end

        def disable_query_cache!
          @query_cache_enabled.delete connection_cache_key(@lock_thread || Thread.current)
          connection.disable_query_cache! if active_connection?
        end

        def query_cache_enabled
          @query_cache_enabled[connection_cache_key(@lock_thread || Thread.current)]
        end
      end
    end

    class ConnectionPool
      def active_connection?
        @thread_cached_conns[connection_cache_key(@lock_thread || Thread.current)]
      end
    end
  end
end
```

**Comment by eileencodes** [comment]
Do you want to send a PR @engwan?

**Comment by engwan** [comment]
Sure. I'll look at adding tests for this and send a PR
