### ISSUE TITLE
Missing the broadcast method in ActiveSupport::Logger online documentation

### ISSUE THREAD

**Issue by ecbrodie** [rails/rails#36586]
Apologies in advance for abandoning the issue template.

I noticed an issue in the [ActiveSupport::Logger online documentation](https://api.rubyonrails.org/classes/ActiveSupport/Logger.html). The [class method `.broadcast`](https://github.com/rails/rails/blob/master/activesupport/lib/active_support/logger.rb#L23) was missing. I would normally just try to fix it myself and create a PR. However, I am unsure why the generated rdoc for this class is not documenting this method. Besides a code issue inside of this particular Ruby file, I am unsure of where else a change would need to be made.

**Comment by y-yagi** [comment]
This is because `broadcast` is an internal API. The `:nodoc:` means an internal API and users shouldn't depend on this API. 
Please see  https://edgeguides.rubyonrails.org/api_documentation_guidelines.html#method-visibility for more details. Thanks.
