### ISSUE TITLE
Rubocop 0.72.0  error: obsolete `EnforcedStyle: rails`

### ISSUE THREAD

**Issue by tenshiAMD** [rails/rails#36584]
### Steps to reproduce
Run `rubocop` on any rails app with rubocop `0.72.0`

### Expected behavior
It should run `rubocop` command properly without the error below.

### Actual behavior
An error occured when executing rubocop command:
```
Error: obsolete `EnforcedStyle: rails` (for Layout/IndentationConsistency) found in .rubocop-https---raw-githubusercontent-com-rails-rails-master--rubocop-yml
`EnforcedStyle: rails` has been renamed to `EnforcedStyle: indented_internal_methods`
```

### System configuration
`rails >= 5.2.3`
`rubocop >= 0.72.0`

**Comment by fxn** [comment]
Who writes that config file for RuboCop?

**Comment by koic** [comment]
This is a RuboCop issue, not a Rails issue.
Please update `EnfocedStyle` name of `Layout/IndentationConsistency` as follows.

```diff
  Layout / IndentationConsistency:
-   EnforcedStyle: rails
+   EnforcedStyle: indented_internal_methods
```

**Comment by matthewd** [comment]
> `.rubocop-https---raw-githubusercontent-com-rails-rails-master--rubocop-yml`

This is not a default -- or supported -- setup.

**Comment by tenshiAMD** [comment]
@fxn I'm inheriting the `.rubocop.yml` in one my repositories then I noticed that error.

@koic, yeah but this will be an issue to `rails` when RuboCop `0.72.0` will be used.

**Comment by fxn** [comment]
@tenshiAMD this is unrelated to the Rails project. RuboCop has renamed that setting, and you have to change your config files.

Maybe you're confused by the cop. RuboCop used `rails` in that one for historical reasons, it is the way Rails indents its source code, but that doesn't mean Rails is responsible for the rename.
