### ISSUE TITLE
Rails 5.0 missing column in column name list

### ISSUE THREAD

**Issue by HienNguyenAsnet** [rails/rails#36596]
### Steps to reproduce
I'm upgrading my project from rails 4.2 to 5.0 (ruby upgrade from 2.2.1 to 2.5.5) follow
https://hashrocket.com/blog/posts/how-to-upgrade-to-rails-5#9-test-http-request-methods
https://edgeguides.rubyonrails.org/upgrading_ruby_on_rails.html#upgrading-from-rails-4-2-to-rails-5-0
I got below issue
My model name is Specialty with columns:
- id: integer
- created_at: datetime
- updated_at: datetime
- verified: boolean
- indexed: boolean
- name: string
- info: text

After upgrading Specialty model missing column `name` and `info` in the column name list. The column still in the database but missing in `column_names` and no type. It makes an issue with `ransack` gem when search `name_cont`

![Screen Shot 2019-07-04 at 3 29 33 PM](https://user-images.githubusercontent.com/5277254/60651731-00988780-9e71-11e9-8841-a24af7830545.png)
![Screen Shot 2019-07-04 at 3 33 40 PM](https://user-images.githubusercontent.com/5277254/60651803-24f46400-9e71-11e9-9eeb-ffa268d1e880.png)

Schema file
<img width="511" alt="Screen Shot 2019-07-04 at 3 35 48 PM" src="https://user-images.githubusercontent.com/5277254/60651934-6e44b380-9e71-11e9-937c-81bc71ecbc8e.png">

### System configuration
**Rails version**: 5.0.7.2

**Ruby version**: 2.5.5

**Comment by y-yagi** [comment]
Rails 5.0 only support for severe security issues, not support bug fix. Please check your issue can reproduce or not with 5.2. If can reproduce, feel free to reopen. Thanks.
