### ISSUE TITLE
Allow rename_column to take an index

### ISSUE THREAD

**Issue by alec-implicitdesign** [rails/rails#36597]
### Steps to reproduce
Renaming a column to a sufficient size so that the newly generated index would be too long.

### Expected behavior
`rename_column` should allow the user to pass through an `index`.

### Actual behavior
`rename_column` fails on trying to automatically create the index because it is too long.

### System configuration
**Rails version**:
5.2.2
**Ruby version**:
2.5.3

**Comment by y-yagi** [comment]
Please use the [Rails Core mailing list](https://groups.google.com/forum/#!forum/rubyonrails-core) for feature requests, where a wider community will be able to help you. We reserve the Rails issue tracker only for bugs in Rails. Thanks!
