### ISSUE TITLE
support for mysql datatype 'point' and other geo spatial datatypes

### ISSUE THREAD

**Issue by rahil-helios** [rails/rails#36598]
### System configuration
**Rails version**:

**Ruby version**:

**Comment by sikachu** [comment]
We generally do not accept feature request on our issue board per our [Contributing Guideline](https://github.com/rails/rails/blob/master/CONTRIBUTING.md). If you would like to see this feature in Rails, please feel free to submit a pull request that implement the feature with test coverage, or you may try to ask in rubyonrails-core mailing list to see if there is anyone who's willing to work on it. Thank you.
