### ISSUE TITLE
System Tests don't easily allow for https sessions

### ISSUE THREAD

**Issue by trcarden** [rails/rails#36608]
### Steps to reproduce

1. Configure Puma to run SSL for System tests (https://github.com/teamcapybara/capybara/pull/2028)
```ruby
   Capybara.server = :puma, { Host: "ssl://#{Capybara.server_host}?key=<key_file>&cert=<cert_file>"
```

2. Configure App Host to use HTTPS
```ruby
   Capybara.app_host = "https://#{Capybara.server_host}" 
```

3. Run Trivial System Test
```ruby
it 'shows correct version of home page' do
    visit root_path
    expect(page).to have_content('anything')
end
```

### Expected behavior
It should pass test if "anything" is on that page

### Actual behavior
Chrome browser boots, test hangs, and eventually fails due to timeout

After chasing it down I found that the new system testing framework forcefully overrides the host used in the test suite to a `DEFAULT_HOST` hardcoded to `http://127.0.0.1` (https://github.com/rails/rails/blob/master/actionpack/lib/action_dispatch/system_testing/test_helpers/setup_and_teardown.rb#L14)

### Additional Notes

I believe that if someone configures `Capybara` to a specific app_host that Rails shouldn't override it.

### Workaround for others

I found that If I simply defined my own before hook and override the host I get the behavior I want.

```ruby
  config.before :each, type: :system do
    Capybara.app_host = "https://#{Capybara.server_host}"
  end
```

### System configuration
**Rails version**: 5.2.3

**Ruby version**: ruby 2.6.2

**Comment by trcarden** [comment]
@twalpole Maybe related to issues reported here https://github.com/teamcapybara/capybara/pull/2028 

Maybe there is a way to get Capybara to drive without specifying the app_host (as you alluded to) however forcing the app_host that is overridden by rails here seemed to work

**Comment by twalpole** [comment]
@trcarden If `Capybara.app_host` is left unset then Capybara defaults to the interface, port, and protocol it started the application under test on. However, if `Capybara.app_host` is set then Capybara assumes the user knows what they're doing and uses `app_host` as the base for any URLs visited.  For some reason (I either don't remember or never knew) Rails system tests chose to default to always setting `Capybara.app_host` rather than letting Capybara manage/detect it.  Because of that for SSL you will need to always reset it (setting to `nil` would probably also work) in a before/setup block. 

Another thing to note is you appear to be using RSpec System specs which adds another layer (rspec-rails gem) on top of Rails system tests - I don't think rspec-rails does anything with `app_host` but it's been a while since I looked so I could be out of date on that.

**Comment by georgeclaghorn** [comment]
> For some reason (I either don't remember or never knew) Rails system tests chose to default to always setting `Capybara.app_host` rather than letting Capybara manage/detect it.

We need a host for URL generation and `Capybara.app_host` is `nil` if it’s not set.

Where is this behavior documented, and how can we get the host Capybara actually ends up using? I’ve tried `Capybara.default_host` and `Capybara.current_session.current_host`.

**Comment by twalpole** [comment]
@georgeclaghorn `Capybara.app_host` is an override designed for use when running against an app not started by Capybara.  When it's left nil (which it generally should be when Capybara is running the AUT) Capybara defaults to where the server was started - https://github.com/teamcapybara/capybara/blob/master/lib/capybara/session.rb#L261 - which is `Capybara.current_session.server.host` once the server is started -https://github.com/teamcapybara/capybara/blob/master/lib/capybara/session.rb#L867
Capybara determines which interface to start the server on from `Capybara.server_host` or more specifically `Capybara.current_session.config.server_host`

**Comment by georgeclaghorn** [comment]
It seems less than ideal to have to reimplement that chain of decisions in Rails (and we do if we’re not setting `Capybara.app_host` ourselves). Can Capybara expose the actual app host/base URI it ends up using somewhere?

**Comment by twalpole** [comment]
@georgeclaghorn As it is Rails actually isn't setting to the correct thing if Capybara.server_host is changed by the user.  As stated, Capybara.app_host could be set by users if they're testing an external app, so Rails using any value of that wouldn't be correct either. I believe Rails should either just have it's own hostname setting for URL generation or be using `Capybara.server_host` (or Capybara.current_session.config.server_host if supporting Capybaras "threadsafe" mode - really just per session config), but it really shouldn't be setting `app_host`

**Comment by twalpole** [comment]
@georgeclaghorn The next release of Capybara will have `Session#server_url` as part of the public API - It's been a private API method since at least 3.7.0 so you could technically use that for a wider support range.
