### ISSUE TITLE
ActionText::RichText#present? returns false when an attachment is present

### ISSUE THREAD

**Issue by brian-kephart** [rails/rails#36607]
### Steps to reproduce
In any rich text area, add an image attachment but no text. Calling `present?` on the ActionText::RichText object returns `false`.

### Expected behavior
`ActionText::RichText#present?` should return `true` if there is an attachment, even if there is no text.

### System configuration
**Rails version**: 6.0.0rc1

**Ruby version**: 2.6.3

**Comment by y-yagi** [comment]
I think it seems like it makes sense to consider attachments in `ActionText::Content#present?`.
But `ActionText::Content#present?` is not a public API in the first place.
https://edgeapi.rubyonrails.org/classes/ActionText/Content.html

Why do you need this API in your application?

**Comment by brian-kephart** [comment]
Thanks for the fast response!

> ActionText::Content#present? is not a public API in the first place.

Since `Object#present?` is public API this defies expectation IMO.

Here is a basic use case for a notification with heading and optional content:
```ruby
class Notification < ActiveRecord::Base
  has_rich_text :content
  # there is also a string column :heading

  def content_or_heading
    content.presence || heading
  end
end
```

This was my code when `:content` was a string, and it continued to work when I changed `:content` to rich text, except for the attachment issue.

**Comment by y-yagi** [comment]
> Since Object#present? is public API this defies expectation IMO.

Ruby's public API and Rails' public API are different things. 

Anyway, thanks for sharing your case.  It sounds like a reasonable use case.

**Comment by brian-kephart** [comment]
I just realized I incorrectly referred to `ActionText::Content` in the issue title and comments when it should have been `ActionText::RichText`. I've updated those where I could. Sorry for any confusion.

**Comment by georgeclaghorn** [comment]
You’re not intended to attach embeds directly to an `ActionText::RichText` without referencing them in the HTML content. Use [`ActionText::Content#append_attachables`](https://edgeapi.rubyonrails.org/classes/ActionText/Content.html#method-i-append_attachables) to do that:

```ruby
message.update! content: message.content.append_attachables(blob)
```

**Comment by brian-kephart** [comment]
@georgeclaghorn thank you for your response. I want to make we understand each other correctly.

My code for creating and showing the model is nothing more complicated than what's in the [Action Text Overview](https://edgeguides.rubyonrails.org/action_text_overview.html#examples).

From your comment, I am not sure if you're *telling* me to take extra steps beyond what is in the overview, or if you're *assuming* that I am already doing something extra with the embeds and telling me that I should do it differently. I want to be clear that I am not manipulating embeds in my code in any way, or attaching previously saved files, or anything like that. I am dropping an image into a rich text field within the browser as part of a form.

I'm saying that if I drop an image into a rich text field `:content` in a form for `@notification`, with nothing else in the field, that when I call `@notification.content.present?` I expect it to return `true`. Using `<%= @notification.content %>` in the view renders the the appropriate HTML for the image, even though the `:present?` method on the same object returns `false`. This seems illogical to me.

Is this the intended behavior?

**Comment by georgeclaghorn** [comment]
> From your comment, I am not sure if you're *telling* me to take extra steps beyond what is in the overview, or if you're *assuming* that I am already doing something extra with the embeds and telling me that I should do it differently.

It was the latter, so this is a bug and I can reproduce it. Sorry for misunderstanding!

I have a different fix in mind, though—I’ll push it in a minute.

**Comment by brendon** [comment]
Slightly related to this is the case where a custom attachment is added to the document that has neither a `caption` or a `filename`. This still results in a 'blank?` returning true for the rich text row.

In my case I'm validating the presence of this rich text field with a standard:

```
has_rich_text :body
validates :body, presence: true
```

For now I guess I'll make a more complicated validator as I didn't realise `present?` checked the plain text transformation of the content.

Would you consider this still to be a bug? I'd assume any attachment in the document to result in the document no longer being blank.

**Comment by brendon** [comment]
In followup, the solution was to add the following to the custom attachment's model:

```
def attachable_plain_text_representation(caption)
  "[YouTube Video ID #{id}]"
end
```

In my case it was an in-memory class used to turn a YouTube ID into either a thumbnail (when editing) or the actual video `iframe` when viewing.

Hopefully that helps others. I'm not sure if it needs to be addressed in Rails proper, though by default custom attachments without a `caption` will not render as plain text.
