### ISSUE TITLE
ActiveRecord PostgreSQL adapter method `index_name_exists?` checks the wrong schema

### ISSUE THREAD

**Issue by vldcmp** [rails/rails#36628]
### Steps to reproduce

```ruby
        def index_name_exists?(table_name, index_name)
          table = quoted_scope(table_name)
          index = quoted_scope(index_name)

          query_value(<<~SQL, "SCHEMA").to_i > 0
            SELECT COUNT(*)
            FROM pg_class t
            INNER JOIN pg_index d ON t.oid = d.indrelid
            INNER JOIN pg_class i ON d.indexrelid = i.oid
            LEFT JOIN pg_namespace n ON n.oid = i.relnamespace
            WHERE i.relkind = 'i'
              AND i.relname = #{index[:name]}
              AND t.relname = #{table[:name]}
              AND n.nspname = #{index[:schema]}
          SQL
        end
```

The `index_name_exists?` method in the PostgreSQL adapter extracts the schema name from `index_name` instead of `table_name`. This leads to different problems as `add_index` uses `index_name_exists?` when determining whether it should create the index or not. We have the following scenario when we try to create indexes with the same name in different schemas, same table names:

```ruby
  create_schema "some_schema"

  create_table "table" do |t|
    t.string :foo
  end

  create_table "some_schema.table" do |t|
    t.string :bar
  end

  # This will work.
  add_index "table", "foo", name: "index_name"

  # This will crash with the following exception 
  # as it will end up looking in the 'public' schema and finding 
  # index "index_name" in table "table"
  #
  # ArgumentError: Index name 'index_name' on table 'some_schema.table' already exists 
  add_index "some_schema.table", "bar", name: "index_name"
```
Check the following unit test: https://gist.github.com/vldcmp/3fcc9795ff40b1981a02fcad6053ec9e

The broader problem is that unlike other RDBMS, PostgreSQL constraints index name uniqueness per schema, not per table, so we can end up in this situation:

```ruby
  create_table "table" do |t|
    t.string :foo
  end

  create_table "another_table" do |t|
    t.string :bar
  end

  # This will work.
  add_index "table", "foo", name: "index_name"

  # This will crash with a PG exception
  # PG::DuplicateTable: ERROR: relation "index_name" already exists
  #
  # Note that PG stores tables, views, indexes etc as "relations" objects in `pg_class` catalog
  # Hence the not-so-usual error message
  add_index "another_table", "bar", name: "index_name"
```

The conclusion is that `add_index` should check for the given index_name in all the schema where table_name resides, as only looking in the table is not sufficient for validation. Nevertheless, one should expect for `index_name_exists?` to work properly, given a table_name and index_name. 

Pull request on the way.

### Expected behavior
PostgreSQL `index_name_exists?` should extract the schema name from the table_name and check the index_name in the correct table

### Actual behavior
The schema name is extracted from the index_name leading to wrong schema lookup

### System configuration
**Rails version**: 6.1.0.alpha

**Ruby version**: 2.6.3

**Comment by skipkayhil** [comment]
Fixed in #45518
