### ISSUE TITLE
after_action doesn't fire after rescue_block

### ISSUE THREAD

**Issue by ekampp** [rails/rails#36636]
### Steps to reproduce

I have an after_action, where I log the response body that was generated by the controller.

```ruby
class TestController < ApplicationController
  after_action :log_response

  rescue_from ActiveRecordRecordNotFound do |e|
    render json: { code: 404, detail: e.message }, status: 404
  end

  def show
    user = User.find params[:id]
    render json: user, status: 200
  end

  private

    def log_response
      Rails.logger.debug response.body
    end
end
```

If I supply a valid ID for a user I see the response body from the `log_response` method in the Rails logs. 

If I supply an invalid ID, the `efter_action` doesn't fire and log the error response body.

If this is in fact expected behavior, what's the recommended way to go about defining an after_action that will fire even if the response was generated in a rescue_from block? 

### Expected behavior

I would expect the after_action callbacks to fire regardless of the action raising an error or not.

### Actual behavior

the after_action callback only fires when the action renders "correctly", e.i. doesn't raise any errors.

### System configuration
**Rails version**: 5.2.3

**Ruby version**: 2.6.3

Thanks,
Emil

**Comment by yelvert** [comment]
I think the correct way to do this is to use `around_action` instead.

```ruby
around_action :log_response

def log_response
  yield
ensure
  Rails.logger.debug response.body
end
```
