### ISSUE TITLE
Can not rescue ArgumentError with enum assign

### ISSUE THREAD

**Issue by marocchino** [rails/rails#36643]
### Steps to reproduce

```rb
class Good < ApplicationRecord
  enum status: [ :active, :archived ]
end
g = Good.new
g.status = 'unknown' rescue 1
```
### Expected behavior

```
=> 1
```

### Actual behavior

```
ArgumentError: 'unknown' is not a valid status
from /Users/marocchino/.asdf/installs/ruby/2.6.3/lib/ruby/gems/2.6.0/gems/activerecord-5.2.3/lib/active_record/enum.rb:140:in `assert_valid_value'
```

### System configuration
**Rails version**: 5.2.3

**Ruby version**: 2.6.3

**Comment by dongapplyboard** [comment]
@marocchino Would you be able to elaborate on how you solved this?

**Comment by marocchino** [comment]
@dongapplyboard 

I'm ashamed of making a mistake, but it was operator priority.

`=` Has a higher priority than `rescue`. So `g.status = 'unknown' rescue 1` is actually interpreted as `g.status = ('unknown' rescue 1)`, not `(g.status = 'unknown') rescue 1`.

**Comment by dongapplyboard** [comment]
> @dongapplyboard
> 
> I'm ashamed of making a mistake, but it was operator priority.
> 
> `=` Has a higher priority than `rescue`. So `g.status = 'unknown' rescue 1` is actually interpreted as `g.status = ('unknown' rescue 1)`, not `(g.status = 'unknown') rescue 1`.

Oh okay I see. It might be related but I'm still trying to figure out how to rescue all `ArgumentErrors` that are produced by the enums without overriding the `ArguementErrors` erors that rails produces for non-enum related errors which is what brought me to this issue.
