### ISSUE TITLE
ActiveSupport::CurrentAttributes attributes doesn't pass down to child thread 

### ISSUE THREAD

**Issue by leomao10** [rails/rails#36646]
### Steps to reproduce
I tried to use concurrent-ruby in one of my controller, and here are the simplify code that can be reproducable with Rails 5.2.2:

```ruby
# jwt_current.rb
class JwtCurrent < ActiveSupport::CurrentAttributes
  attribute :jwt
end

# api_service.rb
class ApiService
  def execute
    futures = 100.times.map do
      Concurrent::Future.execute do
        puts JwtCurrent.jwt #=> nil
      end
    end
    futures.map(&:value)
  end
end

# tests_controller.rb
class TestsController < ActionController::Base
  before_action :set_jwt

  def index
    puts JwtCurrent.jwt #=> "Some JWT"
    ApiService.new.execute
  end

  def set_jwt
    JwtCurrent.jwt = "Some JWT"
  end
end
```

I would expect ActiveSupport::CurrentAttributes would pass down the attributes set in `before_action` to its child thread in the context of same request-response cycle. As in the document, it state that it would "allows you to keep all the per-request attributes easily available to the whole system.". 

However, it seems `ActiveSupport::CurrentAttributes` rely on `Thread.current[]`, and it would set to empty when child thread is create.

Wondering if this is the designed behavior, and if so, what would be the suggested way to pass down request related data to the model

### System configuration
**Rails version**: 5.2.2

**Ruby version**: 2.4.3

**Comment by rafaelfranca** [comment]
Yes, that is by design. If you want to pass down the value to a children thread you need to set the value again inside the thread

**Comment by leomao10** [comment]
Thanks for the reply @rafaelfranca  Didn't aware your reply until now. 

If it is by design, then `ActiveSupport::CurrentAttributes` is not really pre-request attributes, shall we update the doc to warn the other devs? I guess spin up a new thread within controller is a common practise, esp in microservices environment.

Also, is it possible for Rails to provide a config section to help passing value to child thread? Maybe like this :
```
config.before_child_thread_start do |context|
  context.value :trace_context, { Google::Cloud::Trace.get }
end

config.after_child_thread_start do |context|
  Google::cloud::Trace.set context = trace_ctx
end
```
Otherwise, app developer have to setup values for every gem that need to use `thread.current`, and sometimes it is hard to maintain, here is what we doing at the moment, but it feels very hacky:
```
class ConcurrentFutureWithContext < SimpleDelegator
  def self.execute(*args)
    request_info = Rails.logger.request_info if Rails.logger.is_a?(Google::Cloud::Logging::Logger)
    trace_context = Google::Cloud::Trace.get if define?(Google::Cloud::Trace)
    future = Concurrent::Future.execute do
      Rails.application.executor.wrap do
        # This is a fix for Google Cloud Logger, it will assign request_info to child thread
        Rails.logger.add_request_info(info: request_info) if Rails.logger.is_a?(Google::Cloud::Logging::Logger)
        Google::Cloud::Trace.set(trace_context) if define?(Google::Cloud::Trace)
        yield(*args)
      end
    end
    self.new(future)
  end
end
```
