### ISSUE TITLE
ActiveStorage::BlobsController controller security concern.

### ISSUE THREAD

**Issue by ChrisCPO** [rails/rails#36641]
Security-through-obscurity factor for active storage blobs is a little concerning. It is somewhat easy to get a pre-signed url to the document, also the fact that the endpoint is there regardless is also a concern. If hacker X knows that application Y is a rails app. It would be quite possible to brute force this especially because anything can be passed for the filename param. 

```
rails_service_blob GET    /rails/active_storage/blobs/:signed_id/*filename(.:format)    active_storage/blobs#show 
```

https://github.com/rails/rails/blob/60809e0e1f36da730d0765a1dd781c52366053fb/activestorage/app/controllers/active_storage/blobs_controller.rb#L7

Really this affects most of the `ActiveStorage` controllers.

### System configuration
**Rails version**: Rails 5.2.3

**Ruby version**: ruby 2.6.1p33 (2019-01-30 revision 66950)

**Comment by pathenelam** [comment]
Thanks for submitting the issue

**Comment by louim** [comment]
@ChrisCPO wouldn't you need to know the secret key of the Rails application to generate the blob's `signed_id` externally? 

https://github.com/rails/rails/blob/d5a2f7ec148726d7547e367d7a968e3b4be9b509/activestorage/app/models/active_storage/blob.rb#L95-L97

https://github.com/rails/rails/blob/60809e0e1f36da730d0765a1dd781c52366053fb/activestorage/app/controllers/concerns/active_storage/set_blob.rb#L12

If you meant that somebody with prior knowledge of the `signed_id` of a blob could access it already, I think this is implied:
https://github.com/rails/rails/blob/60809e0e1f36da730d0765a1dd781c52366053fb/activestorage/app/controllers/active_storage/blobs_controller.rb#L3-L6
So if you want private upload handling, you would need to implement authorization yourself.

**Comment by ChrisCPO** [comment]
@louim don't think so, I think the encryption is only to obscure the data base id as well as prevent tampering. However I do not think this would stop a brute force attack, still obscure. 

## App 1
```
[6] pry(main)> ActiveStorage.verifier.generate("1", purpose: :blob_id)
1 => "eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaEpJZ1l4QmpvR1JWUT0iLCJleHAiOm51bGwsInB1ciI6ImJsb2JfaWQifX0=--2391e2400e813ebc9a7b102f10a03bb485c320b2"
```

## App 2
```
[2] pry(main)> ActiveStorage.verifier.generate("1", purpose: :blob_id)
2 => "eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaEpJZ1l4QmpvR1JWUT0iLCJleHAiOm51bGwsInB1ciI6ImJsb2JfaWQifX0=--026c55bada6bd3801be304b1712fe669f8667795"
```

## App 3
```
[2] pry(main)> ActiveStorage.verifier.generate("1", purpose: :blob_id)
3 => "eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaEpJZ1l4QmpvR1JWUT0iLCJleHAiOm51bGwsInB1ciI6ImJsb2JfaWQifX0=--ef3ec6719d970cdfc95a163888b3007cc87c2b68"

```

# compare
```
1 => "eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaEpJZ1l4QmpvR1JWUT0iLCJleHAiOm51bGwsInB1ciI6ImJsb2JfaWQifX0=--2391e2400e813ebc9a7b102f10a03bb485c320b2"
2 => "eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaEpJZ1l4QmpvR1JWUT0iLCJleHAiOm51bGwsInB1ciI6ImJsb2JfaWQifX0=--026c55bada6bd3801be304b1712fe669f8667795"
3 => "eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaEpJZ1l4QmpvR1JWUT0iLCJleHAiOm51bGwsInB1ciI6ImJsb2JfaWQifX0=--ef3ec6719d970cdfc95a163888b3007cc87c2b68"
```

Only the last 40 characters are different, really depends how many blobs are in
the database, I guess. 

really is nothing to stop something like this.
```
[1..].each do |number|
  number_signed = ActiveStorage.verifier.generate(number, purpose: :blob_id)[0...-40]
  rand_chars = SecureRandom.hex(20)

  hacky_hacky(number_signed + rand_chars)
end
```

**Comment by louim** [comment]
@ChrisCPO This first part is not changing because it is the _message_ (in your case, `"1"`).
The message is the first part of the signed_id. It is simply a hash that is Base64'd.

https://github.com/rails/rails/blob/6e40b131d2c7208e116d267e4b40dcf621f8b442/activesupport/lib/active_support/message_verifier.rb#L186-L189

```
irb(main):001:0> ActiveStorage.verifier.generate("1", purpose: :blob_id)
=> "eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaEpJZ1l4QmpvR1JWUT0iLCJleHAiOm51bGwsInB1ciI6ImJsb2JfaWQifX0=--9ba2449bdc9450e735abb918df0556d6fba628dd"

irb(main):002:0> Base64.strict_decode64("eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaEpJZ1l4QmpvR1JWUT0iLCJleHAiOm51bGwsInB1ciI6ImJsb2JfaWQifX0=")
=> "{\"_rails\":{\"message\":\"BAhJIgYxBjoGRVQ=\",\"exp\":null,\"pur\":\"blob_id\"}}"

irb(main):003:0> Marshal.load(Base64.strict_decode64("BAhJIgYxBjoGRVQ="))
=> "1"
```

The second part is the _digest_. The digest is generated from the _message_ using the secret key from your application. By default, it is generated using the SHA1 algorithm:
https://github.com/rails/rails/blob/6e40b131d2c7208e116d267e4b40dcf621f8b442/activesupport/lib/active_support/message_verifier.rb#L200-L203

A SHA1 HMAC digest is 160 bits (20 bytes) of entropy. You would need to break that to find the correct `rand_chars` in your example. This is [not currently feasible](https://crypto.stackexchange.com/questions/1145/how-much-would-it-cost-in-u-s-dollars-to-brute-force-a-256-bit-key-in-a-year/1148#1148).

**Comment by georgeclaghorn** [comment]
What @louim said.
