### ISSUE TITLE
Durations do not check underlying quantity

### ISSUE THREAD

**Issue by lukaso** [rails/rails#36644]
### Steps to reproduce
```sh
$ rails c
Running via Spring preloader in process 4754
Loading development environment (Rails 5.1.6.2)
$> 1.month
=> 1 month
$> 1.month.class
=> ActiveSupport::Duration
$> 1.month.month
=> 2629746 months
```

### Expected behavior
```sh
$> 1.month.month
=> 1 month
```

or

```sh
$> 1.month.month
TypeError "no implicit conversion of #{other.class} into ActiveSupport::Duration"
```

### Actual behavior
`ActiveSupport::Duration` applies the `month` transformation again, after converting into seconds.

### System configuration
**Rails version**: 5.1.6.2

**Ruby version**: ruby 2.6.2p47 (2019-03-13 revision 67232) [x86_64-darwin18]

**Comment by dineshpanda** [comment]
Thanks @lukaso for the bug report.
I have checked this against master branch and it is giving the exact result as it is mentioned by @lukaso .

Although I am not very sure, whether it is a bug or intended behavior by ActiveSupport::Duration.
I would expect the result to be `1 month` when we execute `1.month.month` and this can be done changing this [piece of code](https://github.com/rails/rails/blob/727da1d8cdcab3ff50e399053faf7ba84e05ce03/activesupport/lib/active_support/duration.rb#L424) to `parts.values[0].public_send(method, *args, &block)`

However it breaks this [test](https://github.com/rails/rails/blob/727da1d8cdcab3ff50e399053faf7ba84e05ce03/activesupport/test/core_ext/duration_test.rb#L293) after the above changes.

**Comment by lukaso** [comment]
I think the problem arises in the fact that the existing duration is not checked to be a duration, so it's value of seconds per month is converted to the number of months at this [line of code](https://github.com/rails/rails/blob/727da1d8cdcab3ff50e399053faf7ba84e05ce03/activesupport/lib/active_support/duration.rb#L170). I don't have time to test, but the method missing should probably should check if we already have a duration, and throw an exception (because I don't know how `2.weeks.months` should behave, other than throw an exception).

**Comment by lukaso** [comment]
The linked pull request resolves this issue. It should be merged. Otherwise this issue will continue to exist.

**Comment by lukaso** [comment]
This solution is much better than the existing situation. At least the method will fail instead of returning very unexpected results. This issue will occur on both the `6-0-stable` branch or on `master`.

**Comment by lukaso** [comment]
This issue remains in `6-0-stable`, well at least `6.0.2.1`. See output:

```shell
$ rails c
Running via Spring preloader in process 31597
Loading development environment (Rails 6.0.2.1)
irb(main):001:0> 1.year
=> 1 year
irb(main):002:0> 1.year.year
=> 31556952 years
```

I will update if my clone of rails works (on a slow and flaky network connection).

**Comment by lukaso** [comment]
This issue remains on `master` as well:

```
rails (master=) $ tools/console
irb(main):001:0> 1.years
=> 1 year
irb(main):002:0> 1.years.years
=> 31556952 years
```

**Comment by eugeneius** [comment]
@lukaso what were you trying to achieve when you discovered this behaviour? Could you share something more representative of your actual code than `1.month.month` / `1.year.year`?

Whether https://github.com/rails/rails/pull/36794 is the right solution depends on what real use case led to this problem.

**Comment by lukaso** [comment]
From my perspective #36794 is a good enough solution.

In our case (remembering this is some time ago, so memory is a bit hazy), we had a test that in a `let` statement had done something like:

`let (:duration) { 1.month }`

and then later in the test done something like:

`expect(calculated_month_weeks).to eq(duration.weeks)`

The value of `duration.weeks` was of course totally unexpected, and therefore the test was invalid. I would far rather that the call had exploded than that it had given a misleading answer. You can imagine an even worse case where someone does `1.year.days` and expects `365` although of course that would be ignoring leap year.

**Comment by kaspth** [comment]
Appreciate the explanation @lukaso, but I don't think it should be in the purview of `ActiveSupport::Duration` to handle this particular case. It strikes me as too much of an edge case given that it was a value extracted to a `let` in a test case and not app code, the duration is still off so it should be possible to see there was an error. Thanks for the suggestion!

**Comment by lukaso** [comment]
@kaspth I agree my exact situation doesn't particularly warrant concern. Though the person who wrote the code (it wasn't me) had clearly not noticed the error. I do think the logic in `ActiveSupport::Duration` is faulty when used on itself and the PR fixes it without restricting useful behaviour. I'm not a fan of functionality that behaves in unexpected ways, as this does.
In my view, the fact it was in test code is incidental, don't you think? Is your point that this class is used so rarely that no one will encounter the bug, since it is highly unlikely that someone would apply a duration to a duration object?
Anyway, glad to help when I can!

**Comment by kaspth** [comment]
> I'm not a fan of functionality that behaves in unexpected ways, as this does.

Calling `1.month.month` and it returning a whole month of months is quite expected and straightforward, I'd say. Your problem seems to stem from the indirection of the call, and I don't want to use that as justification for changing this. That's my take.
