### ISSUE TITLE
ActiveSupport::LogSubscriber documentation is missing some information

### ISSUE THREAD

**Issue by janko** [rails/rails#36657]
### Steps to reproduce

Following the steps from the [documentation](https://api.rubyonrails.org/classes/ActiveSupport/LogSubscriber.html):

```rb
require "active_support/all"

class ActiveRecord
  class LogSubscriber < ActiveSupport::LogSubscriber
    def sql(event)
      p event
    end
  end
end

ActiveRecord::LogSubscriber.attach_to :active_record

ActiveSupport::Notifications.instrument("sql.active_record") do
  # some work
end
```

### Expected behavior

I expected `ActiveRecord::LogSubscriber#sql` method to have been called, and the event object printed out.

### Actual behavior

The `ActiveRecord::LogSubscriber#sql` method is not being called.

### System configuration

**Rails version**: 6.0.0.rc1

**Ruby version**: 2.6.0

**Comment by gmcgibbon** [comment]
If you're outside of Rails, [this doesn't work by default](https://github.com/rails/rails/blob/a8dfec903bd8cd3b7df9f9d5fbb7100520049302/activesupport/lib/active_support/log_subscriber.rb#L103). Try setting a logger via `ActiveSupport::LogSubscriber.logger =`. I'll see if I can clarify that in the docs.
