### ISSUE TITLE
URL helper methods are generated differently on collection routes

### ISSUE THREAD

**Issue by lxxxvi** [rails/rails#36662]
Hello community!

I have more like a question rather than reporting an issue.
It's about nested routes.

Let's consider this example:

```ruby
Rails.application.routes.draw do
  resources :fruit, only: [] do
    resources :vitamins, only: %w[new create], module: :fruit
  end
end
```

this creates the routes and the helpers as expected, meaning that it concatenates `fruit` and `vitamin` in the helper methods, thus `new_fruit_vitamin`. Sparkling!

```shell
$ bin/rails routes | grep fruit
     fruit_vitamins POST   /fruit/:fruit_id/vitamins(.:format)           fruit/vitamins#create
  new_fruit_vitamin GET    /fruit/:fruit_id/vitamins/new(.:format)       fruit/vitamins#new
```

If we'd like to do something similar with a collection route, it does not generate these helpers the same way.

```ruby
Rails.application.routes.draw do
  resources :fruit, only: [] do
    collection do
      resource :cocktail, only: %w[new create], module: :fruit
    end
  end
end
```

Now the helper methods do _not_ contain `fruit` (but the routing itself seems OK).

```shell
$ bin/rails routes | grep fruit
       new_cocktail GET    /fruit/cocktail/new(.:format)                 fruit/cocktails#new
           cocktail POST   /fruit/cocktail(.:format)                     fruit/cocktails#create
```

Is this behavior expected?

I know there's a workaround by adding `, as: :fruit_cocktail`, but I think it would be nice to see the same result for collection. What do you think?

Also, if someone can point me to the code where this could be changed/improved, I'd love to try that by myself.

Thanks
Mario

### Steps to reproduce

Create a resourceful collection route:

```ruby
Rails.application.routes.draw do
  resources :fruit, only: [] do
    collection do
      resource :cocktail, only: %w[new create], module: :fruit
    end
  end
end
```

### Expected behavior

Helper methods should be nested, like `new_fruit_cocktail`.

### Actual behavior

Helper methods are not nested, like `new_cocktail`.

### System configuration

**Rails version**: `~> 6.0.0.rc1`

**Ruby version**: `2.6.3`

**Comment by chukitow** [comment]
@lxxxvi not sure why you are adding a `resource` inside the `collection` block, according to the documentation example, you only need to add extra routes using methods like `post/get/put/etc`

You can change your resource declaration inside a namespace in order to get the result that you are expecting

```ruby
 namespace :fruit do
   resource :cocktail, only: %w[new create]
 end
```

**Comment by gmcgibbon** [comment]
@chukitow is correct. You want to use `namespace` for this situation.

For further questions, please refer to the mailing list or StackOverflow where a wider community can assist you. The issue tracker is reserved for bugs only. Thanks!
