### ISSUE TITLE
Rails 6.0.0.rc1  config.paths['public'] not working

### ISSUE THREAD

**Issue by shlima** [rails/rails#36670]
### Steps to reproduce

```ruby
module App
  class Application < Rails::Application
     config.paths['public'] << 'static'
  end
end
```

### Expected behavior
Rails serves static files from `/static` folder

### Actual behavior
It does not (raises an `ActionController::RoutingError: No route matches`)

### System configuration
**Rails version**: ruby 2.6.3p62 (2019-04-16 revision 67580) [x86_64-darwin18]
**Ruby version**: Rails 6.0.0.rc1

**Comment by wjessop** [comment]
@shlima Rails already serves files from the /static directory (public/static) using these steps:

`rails new foo --skip-git --skip-action-mailer --skip-action-mailbox --skip-action-text --skip-active-record --skip-active-storage --skip-action-cable --skip-sprockets --skip-spring --skip-javascript --skip-turbolinks --skip-test --skip-system-test --skip-bootsnap`

```
$ cd foo
$ mkdir public/static
$ cat > public/foo.txt
FOO
$ cat > public/static/bar.txt
BAR
$ ls -lR public/
total 40
-rw-r--r--  1 will  staff  1722 13 Jul 22:24 404.html
-rw-r--r--  1 will  staff  1705 13 Jul 22:24 422.html
-rw-r--r--  1 will  staff  1635 13 Jul 22:24 500.html
-rw-r--r--  1 will  staff     0 13 Jul 22:24 apple-touch-icon-precomposed.png
-rw-r--r--  1 will  staff     0 13 Jul 22:24 apple-touch-icon.png
-rw-r--r--  1 will  staff     0 13 Jul 22:24 favicon.ico
-rw-r--r--  1 will  staff     4 13 Jul 22:26 foo.txt
-rw-r--r--  1 will  staff    98 13 Jul 22:24 robots.txt
drwxr-xr-x  3 will  staff    96 13 Jul 22:26 static

public//static:
total 8
-rw-r--r--  1 will  staff  4 13 Jul 22:26 bar.txt
```

`bin/rails s` in another terminal, then:

```
$ curl localhost:3000/foo.txt
FOO
$ curl localhost:3000/static/bar.txt
BAR
```

Can you describe what you are trying to do in more detail?

**Comment by y-yagi** [comment]
For the public path, the first value of `config.paths ['public']` is used. So `config.paths['public'] << 'static'` does not work expected (the default value is used). 
Please change to `config.paths['public'] = 'static'`.

**Comment by shlima** [comment]
> Can you describe what you are trying to do in more detail?

@y-yagi 

With Rails 4/5 I was able to **extend** `config.paths['public']` so Rails able to serve static files from **multiple** destinations, this behaviour was very handy and logical. 

Rails 6 breaks this behavior

**Comment by shlima** [comment]
@wjessop 

> Can you describe what you are trying to do in more detail?

I have `/public` folder for the regular use and `/help` folder with documentation in *.md format. Documentation is compilablable for production and editable in markdown. 

Images are served by Rails in development mode through the `/help` folder. And Github or Gitlab displays images correctly in webview if you wish to read or edit documentation through the repository.

I was able to achieve this by **expanding** `config.paths['public']` in development mode.

**Comment by wjessop** [comment]
I am not on the core team so I have no real idea if a PR to change the behaviour of `config.paths['public']` back to the old behaviour would be accepted, but could you move the files outside /public into the public dir as a workaround?

**Comment by y-yagi** [comment]
Hmm, in my understanding, this behavior does not change from 5.2.
https://github.com/rails/rails/blob/661cf57906743a0965edc31443a28181cee348d6/railties/lib/rails/application/default_middleware_stack.rb#L25

@shlima Can you please provide a sample application that reproduces the issue?
