### ISSUE TITLE
Action Text - ApplicationRecord::dup leaves rich_content fields empty

### ISSUE THREAD

**Issue by camiloforero** [rails/rails#36683]
### Steps to reproduce

1. Create a new instance of a model with a `has_rich_text` field and save it
2. Modify the rich text field of the new instance
2. Call `.dup` to get a copy of that instance
3. Save the copy
4. Check the contents of the rich text field of the newly saved copy

### Expected behavior
The copy's rich text field contents should be the same as the old one

### Actual behavior
The copy's rich text field contents are empty

### System configuration
6.0.0.rc1
2.6.2

**Comment by willianveiga** [comment]
As a workaround, you could overwrite the `dup` method:

```
class Animal < ApplicationRecord
  has_rich_text :description

  def dup
    super.tap do |object|
      object.description = description.dup
      object.description.record_id = nil
    end
  end
end
```

Meanwhile, I am trying to fix it. :smile:

**Comment by willianveiga** [comment]
Unfortunately, I am not sure how to fix it properly.

I feel that it need to be fixed but I'm not sure if it should be fixed. [`dup` is not a deep object copy by design](https://edgeapi.rubyonrails.org/classes/ActiveRecord/Core.html#method-i-dup).

What do you guys think about it?

**Comment by alexpooley** [comment]
`has_rich_text` is creating an association under the hood.

https://github.com/rails/rails/blob/0196551e6039ca864d1eee1e01819fcae12c1dc9/actiontext/lib/action_text/attribute.rb#L37

There's a test to show that dup does not copy associations.

https://github.com/rails/rails/blob/0196551e6039ca864d1eee1e01819fcae12c1dc9/activerecord/test/cases/base_test.rb#L788

The docs for `has_rich_text` state that a "dependent RichText model" is used, but not as an association. I guess the association is implied if you know what a RichText model means in Rails.

This is not a code fix. Perhaps the `has_rich_text` docs could be more explicit to highlight the association.
