### ISSUE TITLE
What's the point of argument *table_names for #references method in ActiveRecord::QueryMethods?

### ISSUE THREAD

**Issue by mistpointz** [rails/rails#36680]
### Steps to reproduce
```
User.includes(:posts).where("posts.name = 'foo'").references(:posts)

User.includes(:posts).where("posts.name = 'foo'").references(:abcd)
User.includes(:posts).where("posts.name = 'foo'").references(nil)
User.includes(:posts).where("posts.name = 'foo'").references(123)
User.includes(:posts).where("posts.name = 'foo'").references('anything you want')
```

### Expected behavior
Four last cases should produce error. Or why does this method need the *table_names argument? Maybe it would be a good idea to remove it? Basically you can give anything to it.

### Actual behavior
Everything works. The only case when it doesn't work is when we pass 'users' (or :users).

### System configuration
**Rails version**: 5.2.3

**Ruby version**: 2.5.1p57

**Comment by rafaelfranca** [comment]
It is used just to give Active Record a hint of which table is being references in a SQL string. It does accept anything because you can call your table with any name. See the documentation of the method.

**Comment by mistpointz** [comment]
I can't agree with you. It's bad when method accepts anything.
