### ISSUE TITLE
Unable to add gemfile entry through custom Rails::Generators::AppGenerator

### ISSUE THREAD

**Issue by matthewmcgarvey** [rails/rails#36699]
### Steps to reproduce
https://gist.github.com/matthewmcgarvey/27b1602b4aed944b8f380504f77eb575
Run the [`temp_generator.rb`](https://gist.github.com/matthewmcgarvey/27b1602b4aed944b8f380504f77eb575#file-temp_generator-rb) found in the gist and the `aws-sdk-lambda` entry will not be added.  Now update `Gemfile.tt` in the rails library like I did [here](https://gist.github.com/matthewmcgarvey/27b1602b4aed944b8f380504f77eb575#file-gemfile-tt-L10) with a puts or something else and run `temp_generator.rb` again and it will be added. 
### Expected behavior
The `#gemfile_entry` should update the Gemfile as desired.

### Actual behavior
The `gemfile_entries` contains the gem but it is not in the resulting template.

### System configuration
**Rails version**: 5.2.3

**Ruby version**: 2.6.3

**Comment by rafaelfranca** [comment]
Thank you for the issue. `AppGenerator` is private API of the framework and it is only meant to be used by it. If you want to create a custom app generator use the application template feature

**Comment by rafaelfranca** [comment]
Regardless of the API there is a bug in our code if the gemfile entry doesn't have a comment it appends to the same line as the previous gem. If you execute your code you will see the entry for aws-sdk-lambda is there. It is just in the same line as redis.

**Comment by roramirez** [comment]
Hi @rafaelfranca
I've taking a look for the #gemfile_entry for AppGenerator and this one don't in use. This was introduce in 3f2230b but I can't see the sense why we need to keep it at this time.

I'll can send a PR with the change but I'm need to know if we'll need to remove for all or deprecate the private method. What should I'll do?
