### ISSUE TITLE
Single method for digit grouping and leading zeros

### ISSUE THREAD

**Issue by cup** [rails/rails#36707]
Rails can do digit grouping:

~~~rb
require 'active_support'
ActiveSupport::NumberHelper.number_to_delimited(1234)
~~~

but to also have leading zeros, two method calls must be used:

~~~rb
ActiveSupport::NumberHelper.number_to_delimited('%05d' % 1234)
~~~

other languages can do it with a single method call, like JavaScript:

~~~js
(1234).toLocaleString(0, {minimumIntegerDigits: 5});
~~~

Python:

~~~py
format(1234, '06,')
~~~

Go:

~~~go
package main
import "golang.org/x/text/language"
import "golang.org/x/text/message"
func main() {
   message.NewPrinter(language.Und).Printf("%05d\n", 1234)
}
~~~

I think some more generic method should be available, perhaps
`number_to_format`, that can perform different types of task, and not just the
one specific delimiting task.

**Comment by dineshpanda** [comment]
```
ActiveSupport::NumberHelper.number_to_delimited(1234.to_s.rjust(7,'0'))
=> "0,001,234"
```
is this what you are looking for ?

**Comment by cup** [comment]
yes thank you

**Comment by cup** [comment]
@dineshpanda actually sorry no, that solution is not robust:

~~~
irb(main):001:0> -1.to_s.rjust(3, '0')
=> "0-1"
~~~

**Comment by cup** [comment]
Here is a workaround for negative numbers:

~~~rb
puts ActiveSupport::NumberHelper.number_to_delimited('%06d' % -1234)
~~~

However I would prefer to leave this open, as the other languages listed above
can all do this with a single method call, while Ruby requires two. I will edit
the title to reflect that.

**Comment by cup** [comment]
@dineshpanda sorry for the trouble, but I changed the question to more
accurately reflect what I am looking for, thank you

**Comment by matthewd** [comment]
Please use the mailing list or StackOverflow for questions/help, where a wider community will be able to help you. We reserve the issues tracker for issues only.

**Comment by cup** [comment]
> Please use the mailing list

@matthewd I dont know where that is

**Comment by cup** [comment]
This does it:

~~~rb
require 'active_support/all'
puts 1234.5.to_s(:rounded, delimiter: ',', precision: 2)
~~~
