### ISSUE TITLE
ActionText ContentHelper stripping inline style from rich text content

### ISSUE THREAD

**Issue by macavon** [rails/rails#36725]
Trix editor can be customized by defining new text attributes to apply to selected text. These are implemented as inline styles (`span`s with a `style` attribute).  The `style` attribute is stripped out when the content is displayed.

### Steps to reproduce
Define a custom text attribute, e.g.

~~~
Trix.config.textAttributes.textColour = {
	styleProperty: "color",
  inheritable: true
 }
~~~

and apply it

~~~
trix_element.editor.activateAttribute("textColour", event.target.value)
~~~

(see this [demo app](https://github.com/macavon/action_text_style) for an example with context.)

### Expected behavior
The text to which the attribute has been applied should be displayed with the corresponding styling.

### Actual behavior
The styling is shown in the `rich_text_area` both when first applied and when subsequently edited. The `style` attribute is stored in the DB, but, when the text content is displayed (e.g. in a typical `show` action), it disappears.

This is because `ActionText::ContentHelper#render_action_text_content` sanitizes its argument using a white list of attributes that does not include `style`.

### Workround and Fix

`ActionText::ContentHelper.allowed_attributes` allows the whitelist to be extended. I added this to `config/application.rb`:

~~~
    config.after_initialize do
      ActionText::ContentHelper.allowed_attributes.add 'style'
    end
~~~

However, this is a bit obscure for something that is a feature of Trix editor. Is there any reason not to add `style` to the default whitelist ` ActionText::Attachment::ATTRIBUTES`?

### System configuration
**Rails version**: 6.0.0.rc1

**Ruby version**: 2.6.3

**Comment by javan** [comment]
> However, this is a bit obscure for something that is a feature of Trix editor

It's a feature that you can opt in to by setting a custom `Trix.config.textAttributes` (like you've done), not a default. So, customizing your application's sanitizer configuration (like you've also done) seems appropriate.

**Comment by rossinkiwi** [comment]
I had this same problem and the following did NOT work:
```
    # config/initalizers/action_text.rb
    Rails.application.config.after_initialize do
        ActionText::ContentHelper.allowed_attributes.add 'style'
    end
````
What DID work is:
````
    # config/application.rb
    module R5
      class Application < Rails::Application
        config.load_defaults 6.0
        ...
        ActionText::Attachment::ATTRIBUTES << "style"
      end
    end
````
This feels smelly (pardon the synaesthesia)? Any idea what I'm doing wrong?

**Comment by macavon** [comment]
It’s been a while since I did this one, so I’m not 100% certain what was going on. I do remember that I had a lot of trouble getting the ActionText::ContentHelper.allowed_attributes.add call to execute at the right time. Despite best practice, if you look at my demo on GitHub you’ll see I ended up doing it in config/application.rb, not in its own initialiser as you tried. In effect, I did the same as you, just using the ContentHelper instead of assigning the extra attributes explicitly.

I think it’s all about having things done in the right order, but that’s as much as I can say right now.

**Comment by rossinkiwi** [comment]
@macavon: thank you!  I tried placing the "ActionText::ContentHelper.allowed_attributes.add..." inside my config/application.rb and it didn't work there either (sigh).  I think it would be very helpful if someone from the rails team were to provide a documented best practice for adding tags and attributes to the ActionText:ContentHelper sanitizer to help others avoid all this trial and error fiddling.  

The default trix editor is not sufficient for many use cases, so many of us will be working to extend it's functionality by adding buttons, styles, etc.  It would be great if we could have some confidence that these extensions will continue to work as rails/trix/actionText move forward. For example, we've been using  [lazaronixon/trix-extensions](https://github.com/lazaronixon/trix-extensions) as a template for customizing our own trix editor, but because of the lack of official Trix documentation, I'm a little concerned that the interfaces might change out from under us in a future release of Trix/ActionText.

**Comment by tbcooney** [comment]
I have a custom partial being rendered for an attachment and need to use the `data-*` attribute to embed custom data. `ActionText::ContentHelper.allowed_attributes.add 'data'` didn't work but declaring the full data-attribute worked - `ActionText::ContentHelper.allowed_attributes.add 'data-smart_text_attr'`. I agree that it would be very helpful if someone from the rails team were to provide a documented best practice for adding tags and attributes to the ActionText:ContentHelper sanitizer to avoid this rigmarole.

**Comment by seanharmer** [comment]
I've just hit something similar when trying to do youtube embeds via an iframe and Wistia video embeds that work via script tags.

I ended up creating a custom scrubber class and asking ActionText to use that. This way you can have full control over the sanitizing of your HTML. For e.g. if you want to accept script tags but only with src from a set of known URLs.

Example code in this gist: https://gist.github.com/seanharmer/0b687c7f866abe58eb641511ee005b28

**Comment by radhab** [comment]
Hi  I just tried to apply style to span and strong elements in trix editor by changing my application.rb as below
 # config/initalizers/action_text.rb
    Rails.application.config.after_initialize do
        ActionText::ContentHelper.allowed_attributes.add 'style'
    end

I was able to get my styles applied to span and strong elements correctly. But when both strong and italic are applied my style property is being stripped. In database I could see them being saved correctly.   HTML code is as below
<strong style="color: rgb(113, 76, 76);"><em>adsgsg</em></strong>
In this case style is not being applied. Any suggestion about this is helpful. Thank You
