### ISSUE TITLE
SQLite3::DatabaseStatements#begin_db_transaction and exec_rollback_db_transaction methods executed from other database adapters

### ISSUE THREAD

**Issue by yahonda** [rails/rails#36722]
### Steps to reproduce

SQLite3::DatabaseStatements#begin_db_transaction and exec_rollback_db_transaction methods executed from other database adapters like `mysql2` and `postgresql` adapters.

```ruby
$ git clone -b called_from_other_database_adapters https://github.com/yahonda/rails.git
$ cd rails/activerecord
$ bundle install
$ bundle exec rake test_mysql2
$ bundle exec rake test_postgresql
```

* `called_from_other_database_adapters` branch difference with `master` branch
```diff
$ git diff master
diff --git a/activerecord/lib/active_record/connection_adapters/sqlite3/database_statements.rb b/activerecord/lib/active_record/connection_adapters/sqlite3/database_statements.rb
index 85053acf91..c90f9774ba 100644
--- a/activerecord/lib/active_record/connection_adapters/sqlite3/database_statements.rb
+++ b/activerecord/lib/active_record/connection_adapters/sqlite3/database_statements.rb
@@ -73,6 +73,7 @@ def exec_delete(sql, name = "SQL", binds = [])
         alias :exec_update :exec_delete

         def begin_db_transaction #:nodoc:
+          p "SQLite3::DatabaseStatements#begin_db_transaction is called"
           log("begin transaction", "TRANSACTION") { @connection.transaction }
         end

@@ -81,6 +82,7 @@ def commit_db_transaction #:nodoc:
         end

         def exec_rollback_db_transaction #:nodoc:
+          p "SQLite3::DatabaseStatements#exec_rollback_db_transaction is called"
           log("rollback transaction", "TRANSACTION") { @connection.rollback }
         end

$
```
### Expected behavior

These outputs are not reported.  
"SQLite3::DatabaseStatements#exec_rollback_db_transaction is called"
"SQLite3::DatabaseStatements#begin_db_transaction is called"

### Actual behavior
`SQLite3::DatabaseStatements#exec_rollback_db_transaction` and `SQLite3::DatabaseStatements#begin_db_transaction` are executed by `test_postgresql` and `test_mysql2` because these outputs are reported.  
"SQLite3::DatabaseStatements#exec_rollback_db_transaction is called"
"SQLite3::DatabaseStatements#begin_db_transaction is called"

### System configuration
**Rails version**: master branch

**Ruby version**:ruby 2.6.3p62 (2019-04-16 revision 67580) [x86_64-darwin18]

**Comment by y-yagi** [comment]
This is because that some test of `connection_handlers_multi_db_test` uses sqlite3 adapter regardless of current adapter.
https://github.com/rails/rails/blob/121551b80a89d3c5c74e235e0978e44c351a7935/activerecord/test/cases/connection_adapters/connection_handlers_multi_db_test.rb#L33

I think that tests use sqlite3 adapter should not be run on other adapters.

**Comment by yahonda** [comment]
Thanks for the information. Closing this issue because it does not happen with actual applications.
