### ISSUE TITLE
Actionpack: potential breaking change in rack-test

### ISSUE THREAD

**Issue by dennissivia** [rails/rails#36737]
We are currently discussing [a potential change](https://github.com/rack-test/rack-test/issues/241#issue-406963889) to [rack-test](https://github.com/rack-test/rack-test) which is s a [dependency of actionpack](https://github.com/rails/rails/blob/master/actionpack/actionpack.gemspec#L35).

The user suggested that rack-test should cause a test-failure when the rack-response does not conform to the rack-spec. 

## Example:

Creating a response like 
```ruby
["200", {}, "hello world"] #string instead of an enumerable as last argument
```
would pass the tests, but fail on a real request. The full example is included in the linked issue.

## Benefit
The primary benefits are primarily 
* confidence in the test-suite. Green tests for a completely broken response are not an ideal experience
* Fast feedback. In case rack-test would immediately fail tests with a malformed response, we could significantly shorten the time until the bug is discovered

## Compatibility
Implementing the suggestion would be a breaking change that might impact a lot of downstream libraries and applications. 
In reality, most production apps with a recent ruby/rack version should have a correct implementation, which would mean that the change should have a low impact.

I would love to learn about the implications of such a breaking change from the rails and rack perspective so that I can take that into consideration for the decision.

`cc` @eileencodes @tenderlove

**Comment by dentarg** [comment]
@eileencodes I don't think this should have been closed?

**Comment by skipkayhil** [comment]
Closing as the upstream issue was closed.
