### ISSUE TITLE
Rails RC2 regression in multiple datbases

### ISSUE THREAD

**Issue by morgoth** [rails/rails#36736]
This commit https://github.com/rails/rails/commit/f2ad69fe7a605b01bb7c37eeac6a9b4e7deb488e inlcuded in Rails RC2 caused a regression in case where multiple database are used and `DATABASE_URL` environment variable is set.

Reproduction of the bug is here https://github.com/morgoth/mdbug (details in commit https://github.com/morgoth/mdbug/commit/048db246bf2ec5d30bf141ac17dc68c699730514) and can be seen by running `DATABASE_URL="sqlite3:db/development.sqlite3" bin/rails r "Dog.count"` which throws an error:
```
The `animals` database is not configured for the `development` environment. (ActiveRecord::AdapterNotSpecified)

Available databases configurations are:

default
development
test
```

When running `bin/rails r "Dog.count"` all is working fine.
It doesn't matter if `DATABASE_URL` env is used in the config file or not, it's only the fact that is set as env variable.

/cc @eileencodes

**Comment by eileencodes** [comment]
Thanks @morgoth! Working on a fix.

**Comment by saslani** [comment]
still not working. I have multiple databases. None are replicas:

```
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
  establish_connection :primary
end

.

class ObsRecord < ActiveRecord::Base
  self.abstract_class = true
  establish_connection :obs
end

.

class AbcRecord < ActiveRecord::Base
  self.abstract_class = true
  establish_connection :abc
end

```

database.yml
```
```

**Comment by morgoth** [comment]
@saslani This fix is not yet released - did you try `6-0-stable` branch?

**Comment by isantoshsingh** [comment]
Hey @morgoth 
I am too facing this issue while deploying to heroku.
any workaround?

**Comment by wjessop** [comment]
@isantoshsingh Did you try 6-0-stable?

**Comment by isantoshsingh** [comment]
@wjessop yes and issue solved after adding below code in my gemfile
Gemfile
`gem 'rails', :git => 'https://github.com/rails/rails.git', :branch => '6-0-stable'`
