### ISSUE TITLE
[rails6.0.0-rc1] Actioncable.server.broadcast not work at `Rails console` environment

### ISSUE THREAD

**Issue by windy** [rails/rails#36734]
### Steps to reproduce

When I make a new project with rails 6, trying configure action cable feature.

Create a channel

```ruby
// app/channels/pad_channel.rb
class PadChannel < ApplicationCable::Channel
  def subscribed
    stream_from "pad"
  end
end
```

```javascript
// app/javascript/channels/pad_channel.js
import consumer from './consumer'

export default consumer.subscriptions.create({ channel: "PadChannel" }, {
  received: function(data){
    console.log(data)
  }
})
```

When I open a new terminal with `rails c`:

```bash
>>> ActionCable.server.broadcast("pad", '222')
```

I found chrome browser has print cable connect log:

```
{"type":"welcome"} | 18 | 17:17:57.438
-- | -- | --
{"command":"subscribe","identifier":"{\"channel\":\"PadChannel\"}"} | 67 | 17:17:57.440
{"identifier":"{\"channel\":\"PadChannel\"}","type":"confirm_subscription"}
```

But I can't see `222` log in chrome browser console.

### Expected behavior

It should print `222` log in chrome browser console

### Actual behavior

Not found.

### System configuration
**Rails version**:

6.0.0-rc1

**Ruby version**:

2.5.3

**Comment by piecehealth** [comment]
Check your `config/cable.yml`, if the adapter is `async` (the default value), your browser could only receive broadcasting from `rails server` process.

**Comment by mahfuz10** [comment]
I changed `config/cable.yml` for `development` environment. Now it works.

```
development:
  adapter: redis
  url: redis://localhost:6379/1
```

**Comment by activeliang** [comment]
> Check your `config/cable.yml`, if the adapter is `async` (the default value), your browser could only receive broadcasting from `rails server` process.

it works!!! thanks 🎉🎉🎉

**Comment by AlexBug1982** [comment]
@mahfuz10 
Thanks, that solved my problem as well
