### ISSUE TITLE
Add support for NOT using secrets.

### ISSUE THREAD

**Issue by gothrek22** [rails/rails#36730]
### Steps to reproduce
Set  RAILS_ENV to production.
Set:
```
  config.require_master_key = false
  config.read_encrypted_secrets = false
```

Have credentials.yml.enc file.

Start the app, it will crash due to credentials decoding error.

### Expected behavior
Rails shouldn't try to open credentials and init it's content. Using this form of credential storage should be an option (even if it's the default option). There should be a way to disable the behaviour. 

### Actual behavior
The app tries to decode credentials even when the master key is not set and then crashes.

### System configuration
**Rails version**: 5.2.3

**Ruby version**: 2.6.2

### Reasoning
For local envs and dev, we are using credentials via the above mentioned mechanism and all works fine. Above dev, we're using kubernetes secrets that are provided as env vars to containers and don't need a `special` mechanism for providing envs for a single stack, it's inconsistent. There should be a way to disable this mechanism on produciton without trying to work around the issue.

**Comment by andrewkress** [comment]
In my testing, it is crashing when trying to validate the SECRET_KEY_BASE.  If that is provided as an environment variable, the server does not crash.

**Comment by gothrek22** [comment]
I've worked around this issue by creating a wrapper script that pulls env vars before rails starts. But that's more of a workaround than a real solution. 

We've also tried implementing Hashicorp Vault in rails itself to provide secrets as a better way to manage them, but found next to impossible(and/or hacky) to provide the required secrets during bootstrap. Is there any way to NOT provide SECRET_KEY_BASE during bootstrap and still use production env settings? Yes, I'm aware that it will break things like cookie encryption, but it's a bit of a secondary issue with proper cookie scoping and properly setup SSL.

**Comment by andrewkress** [comment]
would [Figaro](https://github.com/laserlemon/figaro) or [dotenv](https://github.com/bkeepers/dotenv) be useful to provide a SECRET_KEY_BASE?

I am not sure of the entire impact of removing it entirely, but if its not a concern of including it in your source code, one of the above gems should be able to add it as an environment variable during boot.

**Comment by gothrek22** [comment]
I have no idea what should be the approach, but requirements such as these should be possible to turn off only and if the user explicitly states so. 

In my understanding due to the SECRET_KEY_BASE being initialized early in the bootstrap process it's a pain to try providing it in a really secure way. In the case of docker and env vars, it's not really secure, as anyone with access to the docker daemon can see the "secrets". 

If it was possible to provide them via a secure process that would be a net benefit to more advanced use cases.
