### ISSUE TITLE
Rails.logger is not fiber safe

### ISSUE THREAD

**Issue by cmrd-senya** [rails/rails#36752]
similar to #20490

### Steps to reproduce

1. Change `Rails.logger.local_level` inside a Ruby Fiber
2. Check `Rails.logger.level` in another Fiber

Example code:
```rb
Rails.logger.level = 1
p "Main is debug? #{Rails.logger.debug?}"

Fiber.new {
  Rails.logger.local_level = 0
  p "Thread is debug? #{Rails.logger.debug?}"
}.resume

p "Main is debug? #{Rails.logger.debug?}"
```

### Expected behavior
Logger local level is changed only inside the Fiber

Expected output:
```
=> "Main is debug? false"
=> "Thread is debug? true"
=> "Main is debug? false"
```

### Actual behavior
Logger local level is changed for all Fibers in current Thread

Expected output:
```
=> "Main is debug? false"
=> "Thread is debug? true"
=> "Main is debug? true"
```

### System configuration
**Rails version**: 5.2.2.1

**Ruby version**: 2.6.2

This issue makes particular sense if you use a Rails application with a FiberPool ([rack-fiber_pool](https://github.com/alebsack/rack-fiber_pool)). Let's say you want to change log level at rutime for one request but not for all requests which run in the same app/thread.

Fibers have their own isolated container for `Thread.current[]` so why can't we make the Rails.logger set the local_level per Fiber and not per Thread?

Rails uses `Thread.current.__id__` in order to differentiate between Threads ([source code link](https://github.com/rails/rails/blob/5-2-stable/activesupport/lib/active_support/logger_thread_safe_level.rb#L14)).

`Fiber.current.__id__` is unique in new Threads too so can we just use `Fiber.current.__id__` there instead?

**Comment by rafaelfranca** [comment]
Yes. Can you open a PR?

**Comment by cmrd-senya** [comment]
Yes, we will.
