### ISSUE TITLE
The direct-upload-url is having wrong hostname in Staging env but a correct one in Development env

### ISSUE THREAD

**Issue by aelkoussy** [rails/rails#36750]
### Expected behavior
The direct-upload-url shall be correct in all different environments with different hosts

### Actual behavior

direct-upload-url is built correctly in dev environment, but in the staging environment it is built with wrong hostname

Dev env:
`data-direct-upload-url="https://localhost:3000/rails/active_storage/direct_uploads"
`

Staging env:
`data-direct-upload-url="https://localhost/rails/active_storage/direct_uploads"
`

Which was expected to be (and works well if I manually adjust that in html) 
`data-direct-upload-url="https://**_hostName_**/rails/active_storage/direct_uploads"
`

in my erb file it is:
`<%= f.file_field :logo, direct_upload: true , accept: 'image/png,image/gif,image/jpeg'%>
`

### System configuration
**Rails version**:
5.2.3
**Ruby version**:
ruby 2.6.2p47

**Comment by rafaelfranca** [comment]
Can you provide an example application that reproduce the issue?

**Comment by aelkoussy** [comment]
Hey Rafael, I just found the cause of the issue & it is not a problem in Activestorage, but more of the hidden magic of building a url in the direct-url 
I have posted an answer for this on stackoverflow & will close this issue keep it for reference of others who might face the same
