### ISSUE TITLE
Adding Documentation for CSFR in rails

### ISSUE THREAD

**Issue by ajn123** [rails/rails#36768]
the [Rails Javascript Guide](https://guides.rubyonrails.org/working_with_javascript_in_rails.html) does not hint or say anything about how to procure a CSFR token when sending or making a form yourself.

Would it be a good idea to update the documentation to explain what the token is as well as how to use it ?

I am a first time commiter to Rails and I think it would be a good idea to explain the 

```javascript
var token = $('meta[name=csrf-token]').attr('content');

// javascript
var token = document.getElementsByName('csrf-token')[0].content

```

**Comment by rafaelfranca** [comment]
That is a good idea. Feel free to send a PR. Closing since we don't take feature requests in the issue tracker. Thank you
