### ISSUE TITLE
Rails 6 RC2 regression with webpacker and staging env

### ISSUE THREAD

**Issue by iggant** [rails/rails#36799]
### Steps to reproduce
We have staging env, but there is no staging in the config/webpacker.yml because webpacker should fallback to production env. And we prefer to have 100% similar js code in staging. 
But https://github.com/rails/rails/pull/36354 introduce regression 

### Expected behavior
We can deploy application successfully

### Actual behavior
```
 DEBUG [dcbcd044] 	rake aborted!

 DEBUG [dcbcd044] 	NoMethodError: undefined method `[]' for nil:NilClass

 DEBUG [dcbcd044] 	/capistrano_shared/bundle/ruby/2.6.0/bundler/gems/rails-01da19cb7669/railties/lib/rails/engine/configuration.rb:92:in `webpacker_path'

```

**Comment by rafaelfranca** [comment]
Fixed. Thank you for reporting.
