### ISSUE TITLE
how to connection multiple hosts in rails 5?

### ISSUE THREAD

**Issue by viewnaw** [rails/rails#36796]
Rails version 5.1.6
Ruby version 2.3.3
I have a ruby on rails application working fine and connected to a host. Now i want to connect to a different host from the same application. The data model can be exactly the same. In fact if i connect to the different host the application works fine. However I want to connect to two different host. Is it possible in ruby on rails?

**Comment by viewnaw** [comment]
- I want to connection multiple database with two host?

**Comment by eileencodes** [comment]
Hi @viewnaw, Multiple databases don't work well without a gem or custom code in Rails 5.2 or below. You will need to use Rails 6.0 to have built-in multiple database support. 

The Rails team reserves the Rails issues tracker for Rails bugs and don't usually answer How To questions here so I'm closing this issue. Good luck with your app!
