### ISSUE TITLE
Rails 6 rc2 regression: reorder('') does not stop AR to generate a ORDER BY clause with first

### ISSUE THREAD

**Issue by phoet** [rails/rails#36802]
### Steps to reproduce

created a gist to reproduce the issue https://gist.github.com/phoet/f393635dfd78f31c9dec8ce36a231236

TLDR

```ruby
# broken in rc2
Post.select('min(created_at) as min').reorder('').first.min
# ActiveRecord::StatementInvalid: PG::GroupingError: ERROR:  column "posts.id" must appear in the GROUP BY clause or be used in an aggregate function
# LINE 1: ...LECT min(created_at) as min FROM "posts" ORDER BY "posts"."i...
```

### Expected behavior
when using `reorder('')` it used to not generate a `GROUP BY` clause when calling `.first` on a relation

### Actual behavior
it does generate a group by, causing postgres to error

https://github.com/rails/rails/issues/34793#issuecomment-516028145

**Comment by kamipo** [comment]
Related https://github.com/rails/rails/commit/1340498d2102423665cc5cfe7be7cdba32c72928#r33986510.

After #5153, if `.first` returns a result non-deterministic ordered somehow, it is considered a bug to me.
Use `.take` as the non-deterministic (legacy `.first`) version  instead.

Specifically in this case, you can use `Post.minimum(:created_at)`.

**Comment by phoet** [comment]
@kamipo thanks for the suggestion. this is a simplified version of the problem which itself is part of a 3rd party gem. 

for reference https://github.com/FortySource/forty_facets/blob/9ef15eb3f100654f93fa9276da28e710e747e2ee/lib/forty_facets/filter/range_filter_definition.rb#L24
