### ISSUE TITLE
`COMMENT ON EXTENSION xxx` in Structure.sql causing problems when loading db on Heroku and other services

### ISSUE THREAD

**Issue by concept47** [rails/rails#36816]
### Expected behavior

We should be able to run `rake db:structure:load` without any trouble on any server where you can run `rake db:schema:load` without issues. 

### Actual behavior

the rake `db:structure:load` fails on the line `COMMENT ON EXTENSION plpgsql IS 'PL/pgSQL procedural language';`

[More of an explanation here (essentially super user access is not available)](https://help.heroku.com/AHH2KNSR/why-do-i-get-postgres-extension-errors-when-i-run-rake-db-structure-load-or-rake-db-setup) this also tends to happen on amazon RDS where super user access is similarly not available. However running `rake db:schema:load` on the same system would seem to work just fine. 

### Other Notes
The only reason I decided to file this is that I just noticed [a precedent for it in this Pull request](https://github.com/aripollak/rails/commit/df050484cd3b5e888b50d2e0554a4077407459a8)

I think it would be a good fix to strip out those comments from structure.sql because ... 

- they don't seem to add anything to the db:structure:load process, but are added since [Rails seems to shell out to pg:dump to create them](https://github.com/rails/rails/blob/master/activerecord/lib/active_record/tasks/postgresql_database_tasks.rb#L78) and the rest of structure.sql
- generated schema.rb seems to do just fine without them

### System configuration
**Rails version**:
6.0 RC1

**Ruby version**:
2.6.3

**Comment by prathamesh-sonpatki** [comment]
Looks like PostgreSQL 11 and above [supports](https://commitfest.postgresql.org/14/1155/) `--no-comment` flag.

If the version is lower, we can remove the comments manually.

**Comment by simonrussell** [comment]
This is still a thing, btw.  We're not using Rails 6 yet, but if it hasn't been fixed there then this still presents a problem using `structure.sql` in a bunch of places.

**Comment by bendilley** [comment]
An option that could work for you is to add this to your `development` database definition in `config/database.yml`:
```yaml
  schema_search_path: public
```
This does usually strip out the extensions altogether (and obviously anything else not in the `public` schema) but that might well be just what you want. It can be "a string of comma-separated schema names" according to [the API docs](https://api.rubyonrails.org/classes/ActiveRecord/ConnectionAdapters/PostgreSQL/SchemaStatements.html#method-i-schema_search_path-3D) if you have a more involved setup.

**Comment by simonrussell** [comment]
Thanks @bendilley, spot on, that fixes the issue.  No fancy DB setup here, so that is probably good general advice for a lot of people; thanks.  Hopefully this comment trail is useful for future readers...

**Comment by dbarrionuevo** [comment]
I adjusted @bendilley solution a bit to keep changes at minimum in my `db/structure.sql`, i.e. keeping `$user` in the schema search path like:
```
schema_search_path: '"$user", public'
```

**Comment by sspread** [comment]
To remove comments in structure without stripping extensions, add to an initializer:

```
if Rails.env.development?
  ActiveRecord::Tasks::DatabaseTasks.structure_dump_flags = ['--no-comment']
end
```
