### ISSUE TITLE
Rails 6.0.0.rc2 sqlserver no method alias_method_chain

### ISSUE THREAD

**Issue by BookOfGreg** [rails/rails#36832]
### Steps to reproduce
```
rails new prototype --database=sqlserver -C -S
```

### Expected behavior
```
Install succeeds
```

### Actual behavior
During install
```
         run  bundle exec spring binstub --all
* bin/rake: Spring inserted
* bin/rails: Spring inserted
       rails  webpacker:install
/home/me/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/railties-6.0.0.rc2/lib/rails/app_loader.rb:53: warning: Insecure world writable dir /home/greg/.rbenv/versions in PATH, mode 040777
rails aborted!
NoMethodError: undefined method `alias_method_chain' for #<Class:ActiveRecord::Base>
Did you mean?  alias_method
/mnt/c/source-wsl/prototype/config/application.rb:20:in `<main>'
```
Running any command such as: rails webpack:install
```
/home/me/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/activerecord-sqlserver-adapter-2.3.8/lib/active_record/connection_adapters/sqlserver_adapter/core_ext/active_record.rb:13:in `singleton class': undefined method `alias_method_chain' for #<Class:ActiveRecord::Base>
Did you mean?  alias_method (NoMethodError)
        from /home/me/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/activerecord-sqlserver-adapter-2.3.8/lib/active_record/connection_adapters/sqlserver_adapter/core_ext/active_record.rb:12:in `included'
```

### System configuration
**Rails version**: 6.0.0rc2

**Ruby version**: 2.6.3

**Comment by yahonda** [comment]
activerecord-sqlserver-adapter Rails 6.0 support is work in progress at https://github.com/rails-sqlserver/activerecord-sqlserver-adapter/pull/690 .  I do not think this is an issue with Rails itself.

**Comment by BookOfGreg** [comment]
Looking at my own error above, looks like it pulled in V2.3.8 of that gem when it's on V5. Not sure why bundler selected that but you're right in that it would be a gem issue.
Thanks for your thoughts.

**Comment by Li357** [comment]
@BookOfGreg Did you find out how to use v5 with the CLI? I can't seem to keep it from installing 2.3.8 even with 5.2.0 installed locally. Or do I have to downgrade to Rails v5.2?

**Comment by BookOfGreg** [comment]
https://github.com/bundler/bundler-features/issues/20
Rails isn't the problem, the sqlserver gem is. The TLDR of it is fork the gem, remove the restriction in the gemspec and hope for the best.
sqlserver isn't well supported.

If you have any choice in the matter you would be using Postgresql anyway 😉
