### ISSUE TITLE
How to map already uploaded s3 image with ActiveStorage

### ISSUE THREAD

**Issue by souravongit** [rails/rails#36842]
### My workflow

- I have created a bucket in s3.
- When somebody drops an image over there an SNS notification comes to my rails app in response got the image name.
- By the image name, I can get the user info
- Now I need to create an active storage relation with the user which will map that s3 URL in active storage table.
 
Any help will be appreciated.

Thanks

**Comment by chukitow** [comment]
@souravongit I think you can use the mailing list or StackOverflow for questions/help. Rails contributors reserve the issues tracker for issues only.
