### ISSUE TITLE
Feature Request: Support for dynamic email - amp4email

### ISSUE THREAD

**Issue by jayshahalma** [rails/rails#36840]
I tried sending an email with a valid amp-html content but still it is not being interpreted by Gmail as dynamic email.
My guess is ActionMailer needs to add support for Content-Type: text/x-amp-html; charset="UTF-8" and provide a way to differentiate between normal html content and dynamic html content.

**Comment by chukitow** [comment]
@jayshahalma I recommend you to update your description to include:

- Expected behavior.
- Actual behavior.
- An example app/script where the issue is reproducible.
- System Configuration.

Otherwise, this issue might be closed

**Comment by georgeclaghorn** [comment]
Thanks for your interest, but we don’t take feature requests in the issue tracker. Please use the [rubyonrails-core](https://groups.google.com/forum/#!forum/rubyonrails-core) mailing list to discuss possible additions to Rails or open a pull request.
