### ISSUE TITLE
ActiveSupport::TestCase is devastatingly polluting Ruby

### ISSUE THREAD

**Issue by amatsuda** [rails/rails#36844]
Currently, requiring `ActiveSupport::TestCase` loads too many Active Support components including dozens of language core monkey patches.

Here's a list of what's loaded from `core_ext` as of 6.0.0.rc2.

```
$ ruby -ractive_support/test_case -e 'puts $LOADED_FEATURES.grep(/active_support\/core_ext/)'
.../activesupport-6.0.0.rc2/lib/active_support/core_ext/array/extract_options.rb
.../activesupport-6.0.0.rc2/lib/active_support/core_ext/kernel/singleton_class.rb
.../activesupport-6.0.0.rc2/lib/active_support/core_ext/module/redefine_method.rb
.../activesupport-6.0.0.rc2/lib/active_support/core_ext/class/attribute.rb
.../activesupport-6.0.0.rc2/lib/active_support/core_ext/kernel/reporting.rb
.../activesupport-6.0.0.rc2/lib/active_support/core_ext/string/filters.rb
.../activesupport-6.0.0.rc2/lib/active_support/core_ext/module/delegation.rb
.../activesupport-6.0.0.rc2/lib/active_support/core_ext/module/deprecation.rb
.../activesupport-6.0.0.rc2/lib/active_support/core_ext/hash/deep_merge.rb
.../activesupport-6.0.0.rc2/lib/active_support/core_ext/hash/except.rb
.../activesupport-6.0.0.rc2/lib/active_support/core_ext/hash/slice.rb
.../activesupport-6.0.0.rc2/lib/active_support/core_ext/string/multibyte.rb
.../activesupport-6.0.0.rc2/lib/active_support/core_ext/string/inflections.rb
.../activesupport-6.0.0.rc2/lib/active_support/core_ext/date_time/calculations.rb
.../activesupport-6.0.0.rc2/lib/active_support/core_ext/object/blank.rb
.../activesupport-6.0.0.rc2/lib/active_support/core_ext/hash/keys.rb
.../activesupport-6.0.0.rc2/lib/active_support/core_ext/object/to_query.rb
.../activesupport-6.0.0.rc2/lib/active_support/core_ext/object/to_param.rb
.../activesupport-6.0.0.rc2/lib/active_support/core_ext/array/conversions.rb
.../activesupport-6.0.0.rc2/lib/active_support/core_ext/object/acts_like.rb
.../activesupport-6.0.0.rc2/lib/active_support/core_ext/time/conversions.rb
.../activesupport-6.0.0.rc2/lib/active_support/core_ext/module/attribute_accessors.rb
.../activesupport-6.0.0.rc2/lib/active_support/core_ext/date_and_time/compatibility.rb
.../activesupport-6.0.0.rc2/lib/active_support/core_ext/time/acts_like.rb
.../activesupport-6.0.0.rc2/lib/active_support/core_ext/date_and_time/zones.rb
.../activesupport-6.0.0.rc2/lib/active_support/core_ext/time/zones.rb
.../activesupport-6.0.0.rc2/lib/active_support/core_ext/object/try.rb
.../activesupport-6.0.0.rc2/lib/active_support/core_ext/date_and_time/calculations.rb
.../activesupport-6.0.0.rc2/lib/active_support/core_ext/date/zones.rb
.../activesupport-6.0.0.rc2/lib/active_support/core_ext/date/calculations.rb
.../activesupport-6.0.0.rc2/lib/active_support/core_ext/time/calculations.rb
```

You see, I didn't run anything. Just required the file. And 31 core_ext files out of 119 that we have in 6.0.0.rc2 has been loaded.

## So, what's wrong with this?

These core extensions are all monkey-patches that changes the behavior of the Ruby language core classes. And all those .rb files are implemented to immediately do the monkey-patching without any additional trigger.<br>
This means, `ActiveSupport::TestCase` changes the behavior of the most fundamental part of not only the framework but also **the test target** just by being loaded.

This behavior is way worse than RSpec 2.x. RSpec <= 2 used to be based on global monkey-patches on `Object`, and the team changed that design because they didn't like that aspect of the framework (but for me personally this tiny set of monkey-patches was acceptable trade off for the DSL because I wouldn't write an application that has such weird methods like `should` etc.).

In SimpleCov, we once had a problem where the coverage result merger was globally adding a method on `Array` and `Hash`. https://github.com/colszowka/simplecov/pull/449<br>
Sure, that was not something that a testing tool should do, but I suppose that it probably never caused an actual problem in real world apps.

I remember that the same kind of thing was happening in IRB, but that was just one method named `default_src_encoding`, so I suppose that method also never actually conflicted or did any harm on Ruby users.
https://github.com/ruby/ruby/commit/88de87c2952b08d7f264c7788069a9b6c2fa9309

But in our case here, the pollution prevails on Kernel, Object, Module, Class, ... and everywhere!

## So, what's the actual problem for the users?

For demonstrating how this would be a problem in real application testing, I brought a very simple one line "application" with a testcase.

Here's the app:

```ruby
puts Time.zone
```

Here's a test code for the app:

```ruby
Class.new(ActiveSupport::TestCase) { def test_time_zone() assert_nothing_raised { p Time.zone }; end }
```

We can even run the test as a oneliner to make sure that the app is healthly running.

```
$ ruby -rminitest/autorun -ractive_support -ractive_support/test_case -e 'Class.new(ActiveSupport::TestCase) { def test_time_zone() assert_nothing_raised { p Time.zone }; end }'
Run options: --seed 8456

# Running:

nil
.

Finished in 0.002033s, 491.8839 runs/s, 0.0000 assertions/s.

1 runs, 0 assertions, 0 failures, 0 errors, 0 skips
```

Now that the test is green, we can confidently run the code in production!

```
$ ruby -e 'p Time.zone'
Traceback (most recent call last):
-e:1:in `<main>': undefined method `zone' for Time:Class (NoMethodError)
```

... :boom::boom::boom:!

I can easily provide dozens of more example applications. For just one more example, here's an example of how we can build a neat command line app that prints the date of beginning of this month with TDD.

```
$ ruby -rminitest/autorun -ractive_support -ractive_support/test_case -e 'Class.new(ActiveSupport::TestCase) { def test_time_zone() assert p(Date.current.beginning_of_month); end }'
Run options: --seed 50066

# Running:

#<Date: 2019-08-01 ((2458697j,0s,0n),+0s,2299161j)>
.

Finished in 0.002045s, 488.9976 runs/s, 488.9976 assertions/s.

1 runs, 1 assertions, 0 failures, 0 errors, 0 skips
```

Again, this app works perfectly in the test, but miserably results in the same `NoMethodError`.

## What happend (or how I broke the CI) in the Rails repo yesterday

While I was navigating the codebase of Active Model, I found a silly test file that requires `active_support/all`. https://github.com/rails/rails/blob/d21e5fbc70c54e31b71483452d975448659fac67/activemodel/test/cases/validations/inclusion_validation_test.rb#L4<br>
According to the git log, that single line was rudely added by a thoughtless programmer in [this commit](https://github.com/rails/rails/commit/68db6bc431fbff0b2291f1f60ccf974b4eece596) back in 6.years.ago.

Since Active Model is designed to be a general purpose O/R mapping abstraction layer, it's implemented not by requiring `active_support/all` inside its codebase.<br>
So, putting `active_support/all` in a test file is absolutely a silly deed. This line changes the way how everything works. 

And, as I removed that `require "active_support/all"` line and run the test, I saw some tests were failing with `NoMethodError: undefined method year' for 1:Integer`.<br>
We were lucky enough that the `1.year` invocation was included only in the tests, so I could fix it by simply adding `require "active_support/core_ext/integer/time"` in the test helper. 03018cb79be301fb40a57c9ac92a392b1eb8ee61<br>
I said we were lucky because there was a possibility of calling something that is not required from the Active Model codebase but included in `active_support/all`, and in that case it could have been a cause of `NoMethodError` in the users' apps.

And, while working on this bug, I noticed that the test enviroment already has too many Active Support components turned on, even though the Active Model codebase seems not to be requring that much things. Then I came to realize the real problem (which I wrote at the top of this issue).

And so I started working on gradually cleaning up the fat `ActiveSupport::TestCase` class, finding dozens of missing `require` calls here and there.<br>
One funny change I made was this: 12959dee0f19a8e050dd1236b031c2c690729905<br>
I removed a line requiring `active_support/time` from `active_support/core_ext/hash/conversions.rb` because nothing in that file seems to require Time manipulation. I ran Active Support tests locally and it passed, so I pushed the commit. Then, the CI started to fail (I'm so sorry for that!) in several other unexpected places, like [actionview](4b4bed83e2c68bcd7fb62cb3eb2aa75733043a92), [activejob](dd16e208a61ee19846ee791e851ceaa491f4a8ee), [actionpack](847ad98e0721fd67d0646dfd58f90e643e4a5ca8), and [actionview](92cb55ce19b3d6d308318f15fdc43b1e5fa67f46).

All those CI failures could be fixed by adding `require` calls in each appropriate place. But why did this happen? I didn't change anything in those places. I just changed a line in `active_support/core_ext/hash/conversions.rb`, but actionview nor activejob actually do not implicitly `require` that file!

The answer for that question in an actionview case is that the `actionview abstract_unit.rb` for the testing is depending on `action_dispatch integration_test.rb` via implicit autoloading, https://github.com/rails/rails/blob/f3c68c59ed57302ca54f4dfad0e91dbff426962d/actionview/test/abstract_unit.rb#L99<br>
then in `action_dispatch integration_test.rb` it references a constant named `ActionController::TemplateAssertions` https://github.com/rails/rails/blob/f3c68c59ed57302ca54f4dfad0e91dbff426962d/actionpack/lib/action_dispatch/testing/integration.rb#L625<br>
and that takes us to `action_controller/test_case.rb` via explicit autoloading https://github.com/rails/rails/blob/f3c68c59ed57302ca54f4dfad0e91dbff426962d/actionpack/lib/action_controller.rb#L58<br>
and then finally in `action_controller/test_case.rb` we're routed to `active_support/core_ext/hash/conversions.rb`. https://github.com/rails/rails/blob/f3c68c59ed57302ca54f4dfad0e91dbff426962d/actionpack/lib/action_controller/test_case.rb#L4

So, that was a long story showing you the fact that the whole testing environment is that much fragile because it randomly depends on core language extensions without any guideline.

## Conclusion

This is what we're currently providing. We're providing a testing toolkit that pollutes all Ruby world objects, for the users to test their apps.<br>
Also, we're providing a set of framework components none of which explicitly requires all Active Support features but tested only with the monkey-patch full environment (`require "active_support/all"` is called only in railtie boot process, and each component in rails such as activesupport, activemodel, activerecord, etc. are designed to be able to selectively included without railtie).<br>
Nothing is relyable so far as being tested on a broken test environment like this.

We should immediately fix this situation. We have to make a 100% clean testing base class for the users, and run our tests with that for truly "isolated" tests.<br>
Our goal is to make sure that none of these dependencies listed here does not pollute Ruby.
https://github.com/rails/rails/blob/f3c68c59ed57302ca54f4dfad0e91dbff426962d/activesupport/lib/active_support/test_case.rb#L5-L15

So far as I roughly investigated, at least these ones are dirty. We probably have to create a cleaner alternative or get rid of each of them.
```
require "active_support/testing/setup_and_teardown"
require "active_support/testing/deprecation"
require "active_support/testing/constant_lookup"
require "active_support/testing/time_helpers"
require "active_support/testing/parallelization"
```

I tried to solve this by myself, but I'm almost giving up.<br>
So I'd like to hear your, especially the core members' opinions. /cc @dhh @jeremy @rafaelfranca and the @rails/committers team

**Comment by dhh** [comment]
I appreciate the deep dive, but I disagree with the premise. First of all, I don't consider Active Support's extensions to be pollution, but rather beautification 😄. Active Support offers a Rails-tinted dialect of Ruby, which not only makes the language more pleasant for Rails programmers, but strikes to the very essence of why I love Ruby. That this is possible!

So in fact, I'm inclined to go the opposite direction: All of Active Support included all of the time! I don't have much interest in micromanaging the dependencies of Active Support for the frameworks within Rails. I think it's completely reasonable to say that any framework included in Rails is free to rely on any aspect of the Ruby dialect that is Active Support. And that any application that wish to use a Rails framework need to accept that this usage comes with an acceptance of this Ruby dialect.

**Comment by amatsuda** [comment]
Thank you David for a quick and clear answer as always.

Maybe I chose a wrong word, but please don't get me wrong. I do strongly love the way Active Support works and everything Active Support provides.

So just to be clear, let me repeat my point again.

The problem is not whether Active Support is "pollution" or "beautification". The problem here is that we're testing things with half baked random set of Active Support core extensions.

I'm fine with including everything from `ActiveSupport::TestCase`. I've never seen such a testing framework, that's probably against the theory, but at least it guarantees total consistency.

So, if we do so, another problem remaining is that we're testing the Rails core components with fully loaded Active Support where we're allowing the users to build Active-Support-free applications. We are not testing what we are providing. The difference there is not just about beautification but more seriously about the way objects behave (like I showed in the "real application" examples above).

If we're going to that direction, the only consistent solution that I can come up withe is to officially `require "active_support/all"` from every piece of the Rails core components.
And, I suppose this is what you meant by "All of Active Support included all of the time!", right?

**Comment by dhh** [comment]
Yes, I do think that we're better off saying "if you use a Rails framework, you're getting all of Active Support". That's a clear expectation. I fully accept that there'll be people who don't like that approach, but at least it's clear.

The only part that I do think is fair is that for Active Support ITSELF to be piecemeal, as far as that goes. So that you could require, say, the TZ extensions, and you'd only get a partial amount of AS. But to be honest, that optimization is pretty low my list of priorities. I'd not be willing to give up very much to allow piecemeal inclusion of Active Support extensions to get it.

**Comment by amatsuda** [comment]
Thanks for the clarification! I like that decision!

> The only part that I do think is fair is that for Active Support ITSELF to be piecemeal, as far as that goes.

Indeed. I'm not sure at this point if we can correctly test Active Support modules with that environment. I'll start investigating in that direction.
