### ISSUE TITLE
How get webm or png variant for gif attachment from ActiveStorage?

### ISSUE THREAD

**Issue by Kein1945** [rails/rails#36851]
### Problem
I need to show static thumbnail for resized GIF.

### Steps to reproduce
Add GIF image attachment for model.
I've tried different methods call vairants method: convert: 'webm', 'delete': '1--1', etc no one works
My last solution for correct gif but with animation:
``
url_for(video.cover.variant(coalesce: true, resize: Video.medium, deconstruct: true).processed)
``

### Expected behavior
variant get preview link for static image

### Actual behavior
I got error:
mogrify -convert webm /tmp/mini_magick20190803-1208-10uy9b0.gif` failed with error:
mogrify-im6.q16: unrecognized option `-convert' @ error/mogrify.c/MogrifyImageCommand/4501.

### System configuration
**Rails version**: 5.2.3

**Ruby version**: ruby 2.5.5p157

**Comment by st0012** [comment]
Can you port your code into a new Rails app and put the link here? It'll help a lot if we can actually reproduct this error.

**Comment by Kein1945** [comment]
@st0012 done. https://github.com/Kein1945/active_storage_test
There is two gifs in repostirory root. `first.gif` and `broken.gif` - animation will be broken in thumbnail without `coalesce: true, resize: "100x100", deconstruct: true`

**Comment by kirs** [comment]
> I got error:
> mogrify -convert webm /tmp/mini_magick20190803-1208-10uy9b0.giffailed with error: mogrify-> im6.q16: unrecognized option-convert' @ error/mogrify.c/MogrifyImageCommand/4501.

Have you looked at the full stack trace (including one from activestorage) to see where exactly is the code that forms mogrify command with "unrecognized option"?

You might also want to try reproducing it on the latest Rails (6.0.0) to see if the behaviour is different there.
