### ISSUE TITLE
ActiveRecord::Base.serialize could chain serialization coders

### ISSUE THREAD

**Issue by notEthan** [rails/rails#36855]
hello, Rails friends. I'm opening this issue to begin discussion of an enhancement to ActiveRecord::Base.serialize that I have been working on. At the moment I have implemented this as a gem, but I hope it might be considered to become part of Rails itself.

ARMS [Active Record Multiple Serialization] is the gem, and it implements an interface which allows a user to chain together any number of coders (each of which responds to #load and #dump) between a record attribute and a database column, using `.arms_serialize` in place of `.serialize`. it is on github here: https://github.com/notEthan/arms - I have just released [v0.0.1](https://rubygems.org/gems/arms).

I think that supporting this behavior with the stock `.serialize` method of ActiveRecord::Base would be desirable. however, as it is currently implemented, `arms_serialize` does not suport all behavior of ActiveRecord's `.serialize`. in particular, the handling for an invocation like `serialize 'mycolumn', MyClass` where `MyClass` is passed to `ActiveRecord::Coders::YAMLColumn.new` is not implemented. for backwards compatibility, a workaround to support this would be possible, but it seems to me to be an unintuitive way to specify a serialization, and I hope that it might be deprecated (in a minor version) and removed (in a major version).

### Steps to reproduce

attempt to chain multiple coders which implement #load and #dump together on a model.

### Expected behavior

it would be cool to be able to do that.

### Actual behavior

I cannot do that without writing a custom coder which implements #load and #dump, likely duplicating existing code and ending up with less flexibilty to serialize objects between an ActiveRecord attribute and a database column.

### conclusion

if this seems like behavior that is best implemented by an extension, I will maintain the `arms` gem to do this and the issue may be closed. if the rails maintainers think it would be a good addition to activerecord itself, I'd love to hear feedback on the interface, and discuss the path to inclusion and talk about compatibility.

**Comment by notEthan** [comment]
thanks for the feedback. I am curious if you might have a chance to look at the `arms` gem and whether it is relevant to workflows at github that have required custom serializers.

while I'm considering the task of reconfiguring serialize, I think it might also be good to add an argument to #load and #dump indicating the record for which the serialization is occurring. I have had times when I could not use a serializer because the object I'm serializing needs to know something about the record (for example: a serializer encrypting `record.secret_data` needs access to `record.secret_iv` but cannot get this without knowing the `record`).

that might be a separate issue to open, but I'll mention it here for now.

**Comment by rafaelfranca** [comment]
Thank you so much for the issue but we don't take feature request on the issue tracker. We recommend you to try to implement the feature and send us a pull request or if you are in doubt if the feature will be accepts ask in Rails Core mailing list for feedback.

**Comment by rafaelfranca** [comment]
Can you explain why we chaining multiple coders is a good idea? Is not implementing a custom coder that does chain different coders already supported?

```
serialize :foo, CustomCoder

class CustomCoder
  def dump(object)
    JSON.dump(object)
  end

    def load(object)
      JSON.load(object).with_indiferent_hash
    end
  end
```

**Comment by notEthan** [comment]
I would say this is a not feature request. I have written the code (see gem `arms`) complete with 100% test coverage. but I'd like to have a discussion before I attempt to integrate/PR with rails itself - see if this is desirable functionality. if the rails core mailing list is a more appropriate place for that discussion I will take it there.

as for why chaining together coders rather than just writing one is better: I feel like your example illustrates this pretty well. JSON and indifferent access are well-supported throughout rails, but to get them both applied when loading my database column, I have to learn the coder interface, and write a whole new class in my project - likely duplicating code that others have done before. instead of just saying `serialize 'preferences', :indifferent_access, :json`.

and there's no reason why a coder that offers indifferent access to hashes (or encryption, or instantiating data as another class, or any of the infinite possibilities serialization offers) should care whether the underlying database column is native json, or strings of yaml, or marshal-dumped. a coder should be able to do one thing.

when I've needed a coder that does more than one thing, I've hacked together this in a couple different forms. one has my coder take an option like `string: :json` or `string: :yaml`, but I'd rather write a coder that doesn't care what happens underneath. another option I've used is to specify an option like `next_coder: ActiveRecord::Coders::YAMLColumn.new('preferences')`. my coder checks if there is a coder to follow and calls it if so. this frankly sucks, for any number of reasons.

when I have to write a new coder class I always end up having it do too many things. one coder doing one thing, and flexible stacking of them, is better.

**Comment by rafaelfranca** [comment]
I agree with that but we don't need to introduce this feature to rails. You can stack coders by using the decorator patter.

```
serialize :foo, IndiferrentHashCoder.new(JsonCoder.new)
```

Thank you for the suggestion though.

**Comment by notEthan** [comment]
I'm not sure what you're talking about. no existing coder takes another coder to call after it. that might not be a bad pattern to implement, but it's not one that is in practice.

thanks for the feedback. I will focus on the gem implementation for this instead of activerecord itself.
