### ISSUE TITLE
ActionText: Hooking into 'trix-attachment-remove' event to purge the file

### ISSUE THREAD

**Issue by andreibondarev** [rails/rails#36853]
I've noticed that there aren't any event handlers for the `trix-attachment-remove` event in `ActionText`. Would it make sense to create an event handler, a `ActiveStorage::DirectUploadsController#destroy` method to purge the attachment when a user remove the attachment or simple clicks 'undo' in the Trix editor?

In my own app, I send back the `ActiveStorage::Blob` `id` once it's saved and save it in the Trix JS attachment object by calling `attachment.setAttributes({ blob_id: data.id })`. 

I've got the following event handler:
```
document.addEventListener("trix-attachment-remove", function(event) {
  var attachment = event.attachment;
  if (attachment.file) {
    return destroyAttachment(attachment.getAttribute('blob_id'));
  }
});
```
`destroyAttachment()` issues a DELETE `/uploads/:blob_id` request.

Controller:
```
  def destroy
    blob = ActiveStorage::Blob.find(params[:blob_id])
    blob.purge
  end
```

I'm happy to try and create a pull request here.

**Comment by andreibondarev** [comment]
@javan I think you may be the best person to review this.

**Comment by javan** [comment]
Purging attachments when they're removed from the editor breaks the ability to undo that change (e.g. clicking the undo button in the toolbar) to restore them. You're better off running a recurring job to clean up [unattached](https://github.com/rails/rails/blob/5f3848a979e6be15a4d8bedcb9c68587094094fe/activestorage/app/models/active_storage/blob.rb#L36) blobs. Something like:
```ruby
ActiveStorage::Blob.unattached.where("active_storage_blobs.created_at > ?", 5.days.ago).find_each(&:purge_later)
```

**Comment by andreibondarev** [comment]
If you click 'undo', the `trix-attachment-add` event is triggered and you re-upload the attachment back up. 

Scenario: A user drags an attachment over into the Trix editor, "oops wrong attachment", removes it and drags over a new one. Don't think we need to persist the first attachment that was uploaded?

**Comment by javan** [comment]
Trix doesn't hold references to `File` objects after they're uploaded so they won't be re-uploaded in that scenario.

**Comment by javan** [comment]
> Scenario: A user drags an attachment over into the Trix editor, "oops wrong attachment", removes it and drags over a new one. Don't think we need to persist the first attachment that was uploaded?

Sure, now imagine a follow-up scenario: User realizes the first attachment was the correct one and hits undo.

**Comment by javan** [comment]
You are, of course, free to implement a `trix-attachment-remove` handler in your application, but for the reasons listed above I don't think it belongs in Action Text.

**Comment by andreibondarev** [comment]
@javan From what I can tell Trix does hold a reference to the File object.

**Comment by andreibondarev** [comment]
![Aug-04-2019 13-08-02](https://user-images.githubusercontent.com/541665/62426908-0627fe00-b6b9-11e9-9895-bb70c13d63fa.gif)

**Comment by andreibondarev** [comment]
![Aug-04-2019 13-23-44](https://user-images.githubusercontent.com/541665/62427075-2658bc80-b6bb-11e9-993f-cf0180b483c7.gif)

**Comment by andreibondarev** [comment]
```
document.addEventListener("trix-attachment-add", function(event) {
  var attachment = event.attachment;
  if (attachment.file) {
    console.log('trix-attachment-add TRIGGERED');
    console.log(attachment.file);
  }
});

document.addEventListener("trix-attachment-remove", function(event) {
  var attachment = event.attachment;
  if (attachment.file) {
    console.log("trix-attachment-remove TRIGGERED");
    console.log(attachment.file);
  }
});
```

**Comment by javan** [comment]
That may be unintended behavior with non-image attachments. Try dragging an image in and doing the same.

**Comment by andreibondarev** [comment]
> That may be unintended behavior with non-image attachments. Try dragging an image in and doing the same.

It works with images as well.

**Comment by andreibondarev** [comment]
![Aug-04-2019 13-33-29](https://user-images.githubusercontent.com/541665/62427144-86039780-b6bc-11e9-8f47-e604639cc287.gif)

**Comment by javan** [comment]
Are you actually uploading and storing those files? Their overlaid progress bars (at 0%) suggest not.

**Comment by andreibondarev** [comment]
@javan I am, I just commented it out to illustrate the point in the GIFs above. Here's the full JS file I'm using: https://gist.github.com/andreibondarev/9329fa2edd47d1aebd7fa2b7a2013ceb

**Comment by javan** [comment]
Like I said, Trix doesn't hold references to `File` objects **after they're uploaded**. So, commenting out your upload masks the issue.

Here's the relevant code path in Trix: [`Attachment#setAttributes`](https://github.com/basecamp/trix/blob/6e0807951f187fc94735710382d66e0c6006b405/src/trix/models/attachment.coffee#L35-L39) → [`Attachment#didChangeAttributes`](https://github.com/basecamp/trix/blob/6e0807951f187fc94735710382d66e0c6006b405/src/trix/models/attachment.coffee#L43-L45) → [`Attachment#preloadURL`](https://github.com/basecamp/trix/blob/6e0807951f187fc94735710382d66e0c6006b405/src/trix/models/attachment.coffee#L137-L138) → [`Attachment#releaseFile`](https://github.com/basecamp/trix/blob/6e0807951f187fc94735710382d66e0c6006b405/src/trix/models/attachment.coffee#L108-L110), at which point there is no longer a reference to the file.

And here's code that illustrates it:
```js
function logEvent(event) {
  const { id, file } = event.attachment
  console.log(event.type, { id, file })
}

addEventListener("trix-attachment-add", logEvent)
addEventListener("trix-attachment-remove", logEvent)
```

![undo-attachment](https://user-images.githubusercontent.com/5355/62428210-08945300-b6cd-11e9-9b2b-f6eab9c78ee0.gif)
