### ISSUE TITLE
ActiveSupport 5.2 Can't convert Hash with similar String keys to JSON without losing data

### ISSUE THREAD

**Issue by danielricecodes** [rails/rails#36861]
### Steps to reproduce
Run the following in a Rails console (e.g. `rails console`)

```ruby
hash = Hash.new.tap do |hsh|
  hsh.compare_by_identity
  hsh['item'] = { name: 'widget', price: 10.00, currency: 'usd'} 
  hsh['item'] = { name: 'foobar', price: 12.34, currency: 'usd'}
end

hash.to_json
```

### Expected behavior
`.to_json` on this type of Hash should return the JSON representation of this kind of Hash.

`"{\"item\":{\"name\":\"widget\",\"price\":10.0,\"currency\":\"usd\"},\"item\":{\"name\":\"foobar\",\"price\":12.34,\"currency\":\"usd\"}}"`

### Actual behavior
This will return a String thats missing all but the last key/value pair from the original Hash.

`"{\"item\":{\"name\":\"foobar\",\"price\":12.34,\"currency\":\"usd\"}}"`

### System configuration
**Rails version**: 5.2.3

**Ruby version**: 2.6.3

**Comment by danielricecodes** [comment]
The actual use case is supporting Authorize.net's JSON API, which they admit is not actually a real JSON API but an XML API that converts from JSON to XML behind the scenes.  There is one p

I have some tweaks I've made to ActiveSupport that fixes this for me.  I'm seeking the community's support to tell me if these tweaks are something that could get merged into Rails.  If not, is there another way convert from Standard Ruby objects into the JSON below?  

```json
{
        "createTransactionRequest": {
            "merchantAuthentication": {
                "name": "XXXXXXXXX",
                "transactionKey": "XXXXXXXXXXXXXXXX"
            },
            "refId": "123456",
            "transactionRequest": {
                "transactionType": "authCaptureTransaction",
                "amount": "45",
                  "profile": {
        		  	"customerProfileId": "27388924",
        		  	"paymentProfile": { "paymentProfileId": "25000332" }
      			},
                "lineItems": {
                    "lineItem": {
                      "itemId": "1",
                      "name": "vase",
                      "description": "Cannes logo",
                      "quantity": "18",
                      "unitPrice": "45.00"
                    },
                    "lineItem": {
                      "itemId": "2",
                      "name": "flowers",
                      "description": "Roses",
                      "quantity": "12",
                      "unitPrice": "3.50"
                    }
                }
            }
        }
    } 
```

See: https://developer.authorize.net/api/reference/#payment-transactions-charge-a-customer-profile

**Comment by danielricecodes** [comment]
Screenshot of my code changes to ActiveSupport 5.2:

<img width="1393" alt="json_rb_—_activesupport-5_2_3" src="https://user-images.githubusercontent.com/169038/62493351-dfdc8e00-b79e-11e9-8c04-ac6021182727.png">

I can make this a PR, but I haven't forked Rails nor have I written test cases.  Just the test cases in my app are passing now :)

**Comment by notEthan** [comment]
this is a very odd use case. the [spec for JSON](https://tools.ietf.org/html/rfc7159) says

> The names within an object SHOULD be unique.

that's not a MUST, though I didn't know any json library would load identical string keys mapped to multiple objects (except now I guess I know whatever library authorize.net uses will do this).

supporting this behavior on dumping json might raise a question of how and whether identical string keys should be handled when loading, for consistency. trying to support that on load sounds like probably a bad idea though, given the obscurity of the use case and the recommendation against it in the spec; ambiguity in what implementing it would entail; potential backwards compatibility issues; etc.

I'm not sure whether supporting this behavior on dump sounds like a good idea, but also I have no say in that as I'm not a maintainer, just a random guy putting his opinion in a comment section on the internet.

**Comment by danielricecodes** [comment]
> potential backwards compatibility issues

Yep, I've already noticed one. `JSON.parse` can not reverse the serialization either.  `JSON.parse` loses the "duplicates" also.  So the classic Serialize/Deserialize test doesn't work, even with my tweaks.  The rabbit hole goes a bit deeper I'm afraid.  

I guess my real question is what alternatives do I have?  Patching Rails seems like a Bad Item ™️ / unlikely to get much community support.  I suppose this one endpoint can use XML, however I was really hoping to use JSON across the board.

**Comment by rafaelfranca** [comment]
What it is the hehavior if you use `Json.dump` in that hash?

**Comment by danielricecodes** [comment]
@rafaelfranca - that appears to work!  I'd need to test a bit more but its possible I could use `JSON.dump(big_ugly_request_hash)` instead of `big_ugly_request_hash.to_json` 

```
[3] pry(main)> JSON.dump hash
=> "{\"item\":{\"name\":\"widget\",\"price\":10.0,\"currency\":\"usd\"},\"item\":{\"name\":\"foobar\",\"price\":12.34,\"currency\":\"usd\"}}"
```

**Comment by notEthan** [comment]
out of curiosity as to whether JSON.parse could do this, I came up with the following:

```ruby
class HashByIdentity < Hash
  def initialize(*a, &b)
    super
    compare_by_identity
  end
end

JSON.parse('{"a":"a","a":"b"}', object_class: HashByIdentity)
# => {"a"=>"a", "a"=>"b"}
```
