### ISSUE TITLE
Add blank to "isdeprecated" warning

### ISSUE THREAD

**Issue by jasnow** [rails/rails#36875]
### Steps to reproduce

cd rails ; git grep "isdeprecated"

## Expected behavior
DEPRECATION WARNING: warning: white_list_sanitizer is deprecated, please use safe_list_sanitizer instead.

### Actual behavior
DEPRECATION WARNING: warning: white_list_sanitizer isdeprecated, please use safe_list_sanitizer instead.

*Rails version**:
Rails 6.0.0.rc2

*Ruby version**:
ruby 2.7.0preview1

**Comment by abhaynikam** [comment]
The missing space was coming from [rails/rails-html-sanitizer](https://github.com/rails/rails-html-sanitizer) and that is fixed in https://github.com/rails/rails-html-sanitizer/commit/21da0389eae482818d6991eb1bba025c8b116927 commit.
