### ISSUE TITLE
There is a missing release note about AR::Dirty methods changed inside of after_(create|update|save) callbacks

### ISSUE THREAD

**Issue by wildjcrt** [rails/rails#36874]
### Steps to reproduce
According to PR https://github.com/rails/rails/pull/25337, there is a table list AR::Dirty methods changed. It marked DEPRECATION WARNING at 5.1 and old methods were removed at 5.2 (020abadf047997cb3df18a59d210dfe4406cf166). Since there are many public APIs changing, it would be better to add back in 5.2 and put a hint in 6.0 release notes.

I copied the changing table from PR https://github.com/rails/rails/pull/25337#issuecomment-225166796

Prior Name | New Name | Meaning
-- | -- | --
attribute_was(attr_name) | *attribute_in_database(attr_name) | current database value of attribute
attribute_change(attr_name) | *attribute_change_to_be_saved | => the changed value for attribute
attribute_changed?(attr_name) | *will_save_change_to_attribute?(attr_name) | was attribute modified since last save
  | attribute_before_last_save(attr_name) | => attribute value from before last save
changed | *changed_attribute_names_to_save | => name of attributes with changed values since last save
changes | *changes_to_save | => the changes to be saved to DB
changed? | *has_changes_to_save? | are there any changes to be saved to the DB?
changed_attributes | *attributes_in_database | => Hash of attribute names & new unsaved values
changed? | has_changes_to_save? | record has unsaved changes
  | saved_changes? | did last save change record attributes?
  | saved_changes | => Hash of all changes in last save
  | saved_change_to_attribute?(attr_name) | did attribute change when record last saved?
  | saved_change_to_attribute(attr_name) | => array of original & saved value from last save

### Expected behavior
* [Rails 5.1 CHANGELOG](https://github.com/rails/rails/blob/5-1-stable/activerecord/CHANGELOG.md)
* Mark AR::Dirty methods changing table in [Rails 5.2 CHANGELOG](https://github.com/rails/rails/blob/5-2-stable/activerecord/CHANGELOG.md)
* Also list changes on [Ruby on Rails upgrading guide](https://guides.rubyonrails.org/upgrading_ruby_on_rails.html) and [5.2 release notes](https://guides.rubyonrails.org/5_2_release_notes.html)

**Comment by uuuyyttu** [comment]
[this post](https://www.levups.com/en/blog/2017/undocumented-dirty-attributes-activerecord-changes-rails51.html) wrote about this issue in detail

**Comment by wildjcrt** [comment]
Someone also raise issue https://github.com/rails/rails/issues/32991 1 year ago. Is it possible that @sgrif can help?

**Comment by rafaelfranca** [comment]
That ship has sailed so we won't be adding those method again even more in a version that is almost not supported anymore, but I'm fine with documentation PRs mentioning those changes. Can you take a look on upgrading the documentation?

**Comment by kinsomicrote** [comment]
I'm not a rails expert, but I'll be willing to submit a PR for this if it still has not been resolved.

**Comment by st0012** [comment]
@kinsomicrote I think this hasn’t been picked up by anyone yet, so you can start it if you want to.

**Comment by foxsoftltd** [comment]
These changes still do not appear to be mentioned in the 5.1 or 5.2 release notes

**Comment by defsdoor** [comment]
These changes still do not appear to be mentioned in the 5.1 or 5.2 Rails release notes - if these are being used as a source for upgrade steps this appears to be a major omission ?
