### ISSUE TITLE
6.1.0.alpha, Active Storage, Turbolinks: After deletion of post with image, Turbolinks try to GET deleted blob

### ISSUE THREAD

**Issue by efojs** [rails/rails#36887]
### Steps to reproduce
Sample app with recreated issue: https://github.com/efojs/act_storage_test
* create post with image (with `has_one_attached :image`) (via POST)
* delete post (via DELETE)
* check logs

### Expected behavior
```
No error
```

### Actual behavior
Chrome console:
```
turbolinks.js:443
GET http://localhost:3000/rails/active_storage/blobs/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBEZz09IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--e2ad5b6b6dce1925d3aa9dac8ef472414b1c7396/8adtfjh3noe01.jpg 
404 (Not Found)
```

Logs:
```
<...>
[ActiveJob] [ActiveStorage::PurgeJob] [58908630-f2b6-4404-aff1-5261260debf2]   TRANSACTION (4.0ms)  COMMIT
Completed 200 OK in 106ms (Views: 101.4ms | ActiveRecord: 1.0ms | Allocations: 11541)

Started GET "/rails/active_storage/blobs/eyJf <...>
Completed 404 Not Found in 11ms (ActiveRecord: 0.6ms | Allocations: 1964)

ActiveRecord::RecordNotFound (Couldn't find ActiveStorage::Blob with 'id'=8):

rails (d44fdd29690a) activerecord/lib/active_record/core.rb:177:in `find'
<...>
puma (3.12.1) lib/puma/thread_pool.rb:135:in `block in spawn_thread'
[ActiveJob] [ActiveStorage::PurgeJob] [14c40f01-dc06-4c56-88e1-a76cad27308b]   S3 Storage (225.3ms) Deleted file from key: h6pee418lw42w2dur9hqfw6oto0f
[ActiveJob] [ActiveStorage::PurgeJob] [14c40f01-dc06-4c56-88e1-a76cad27308b]   S3 Storage (101.9ms) Deleted files by key prefix: variants/h6pee418lw42w2dur9hqfw6oto0f/
[ActiveJob] [ActiveStorage::PurgeJob] [14c40f01-dc06-4c56-88e1-a76cad27308b] Performed ActiveStorage::PurgeJob (Job ID: 14c40f01-dc06-4c56-88e1-a76cad27308b) from Async(active_storage_purge) in 563.3ms
```

### System configuration
**Rails version**: 6.1.0.alpha (master@d44fdd2)

**Ruby version**: 2.5.5

**Comment by georgeclaghorn** [comment]
I can only reproduce this in Safari 12.1.2 and Safari Tech Preview—not in Chrome or Firefox—but it is reliably reproducible nonetheless. What version of Chrome are you running and what OS?

**Comment by efojs** [comment]
**Crome:** Version 76.0.3809.100 (Official Build) (64-bit)  
**OS**: macOS 10.14.5 (18F132) Mojave

Was not reproduced one (first) time in incognito mode, but then appeared.
Can not reproduce in Firefox 68.0.1 (64-bit) and Safari 12.1.1 (14607.2.6.1.1)

**Comment by efojs** [comment]
Found that it's not reproduced in Chrome (normal and incognito) **with closed console**.

**Comment by gentcys** [comment]
|   Reproduce   | Safari(12.1.2) | Chrome(76.0.3809.100) | Firefox(68.0.2) |
|:-------------:|:--------------:|:---------------------:|:---------------:|
|  Enable Cache |       Yes      |           No          |        No       |
| Disable Cache |       Yes      |          Yes          |        No       |

**OS**: macOS 10.14.6

**Comment by efojs** [comment]
> I don't know why different browser with cache enabled and disabled perform differences.

@gentcys, moreover I'm far from understanding why:

- if I close Chrome console, I don't get this error **both** in Chrome console and server logs,
- in Safari I get this error **only** in open console, but never in server logs.

Chrome: 76.0.3809.100 (Official Build) (64-bit)
Safari: 12.1.1 (14607.2.6.1.1)

**Comment by gentcys** [comment]
@efojs I get this error no matter console opened or not in Safari, but only get this error while console opened in Chrome.

**Comment by gentcys** [comment]
> Turbolinks saves a copy of the current page to its cache just before rendering a new page. Note that Turbolinks copies the page using cloneNode(true), which means any attached event listeners and associated data are discarded.

quoted form [Understanding Caching](https://github.com/turbolinks/turbolinks#understanding-caching)

analyze visit actions step by step:

1. visit index page with posts list.
2. click delete link which send a XHR.
3. returned `Turbolinks.clearCache()Turbolinks.visit("http://localhost:3000/", {"action":"replace"})` and which send a request for index page.
4. response returned and before load it Turbolinks will cache index page in step1 which contain posts with images.
5. `cloneNode(true)` attempt to fetch the image deleted by the XHR in step2 and returned 404 error.

So you can add an event listener for `turbolinks:before-cache`:

```javascript
document.addEventListener("turbolinks:before-cache", function () {
  console.log("hello")
  if (posts = document.getElementById("posts")) {
    posts.remove()
    console.log("removed")
  }
})
```
and wrap posts in div tag with an id
```ruby
<div id="posts">
  <% @posts.each do |p| %>
    <div>
      <%= image_tag p.image %><br>
      <%= link_to "Delete post...", destroy_post_path(id: p.id), method: :delete, remote: true %>
    </div>
  <% end %>
```

@efojs I hope this can help you.

**Comment by javan** [comment]
More than anything, this is a Safari issue. I touched on it in https://bugs.webkit.org/show_bug.cgi?id=6656#c18
> Additionally (this may be a separate issue), cloning `<img>` elements causes them to load *again* even if the cloned node is detached from the DOM. For example, running `document.body.cloneNode(true)` reloads all of its images. This affects our Turbolinks (https://github.com/turbolinks/turbolinks) library, which stores “snapshots” of pages by cloning them.

Turbolinks *might* be able to help by improving it's redirect-after-form-submission behavior. The code referenced above in step 3 (`Turbolinks.clearCache(); Turbolinks.visit(…)`) doesn't prevent the page you're currently on from getting cached, and when it does, Safari ends up re(loading) the page's images.

You could work around it by removing posts from the DOM (with JavaScript) when clicking the *Delete* link. That will ensure images doesn't get cached by Turbolinks and loaded again.

I don't think Active Storage can help here. It's not responsible and is dutifully returning 404s for deleted images.
