### ISSUE TITLE
ActiveSupport::MessageEncryptor (undefined method `split' for nil:NilClass)

### ISSUE THREAD

**Issue by fwininger** [rails/rails#36890]
### Steps to reproduce

I recently update the configuration of my Rails Application from 5.1 to 5.2.

I notice a change of behaviour with nil value

```ruby
secret_key = "0000"
salt = "0000"
key = ActiveSupport::KeyGenerator.new(secret_key).generate_key(salt, 32)
crypt = ActiveSupport::MessageEncryptor.new(key)
d = crypt.decrypt_and_verify(nil)
```
=> raise ```NoMethodError (undefined method `split' for nil:NilClass)```

```ruby
secret_key = "0000"
salt = "0000"
key = ActiveSupport::KeyGenerator.new(secret_key).generate_key(salt, 32)
crypt = ActiveSupport::MessageEncryptor.new(key, cipher: 'aes-256-cbc')
d = crypt.decrypt_and_verify(nil)
```
=> raise `ActiveSupport::MessageVerifier::InvalidSignature`

### Expected behavior

I think in the both case, we need to raise : `ActiveSupport::MessageVerifier::InvalidMessage`

### Actual behavior

With the default configuration : 
- in Rails 5.1 we raise : `ActiveSupport::MessageVerifier::InvalidSignature`
- in Rails 5.2 we raise : ```NoMethodError (undefined method `split' for nil:NilClass)```

### System configuration
**Rails version**: 5.2

**Ruby version**: 2.6

**Comment by fwininger** [comment]
Can you considers the issue and the associate PR ?

**Comment by fwininger** [comment]
Can you considers the issue and the associate PR ?

**Comment by fatkodima** [comment]
Works on `main`.
