### ISSUE TITLE
Mail with AMP-HTML body is not rendering correctly on email - ActionMailer 

### ISSUE THREAD

**Issue by jayshahalma** [rails/rails#36891]
### Steps to reproduce

I want to send amp html mail with ActionMailer which has content-type 'text/x-amp-html'. In order to send this I have added mime type in mime_types.rb for .amp files and made method in mailer and I am adding amp body with fallback of html and text body when sending a mail. After that Mail has been sent successfully to recipients.

### Expected behaviour

Dynamic amp content should be render.

### Actual behavior

Rather rendering dynamic amp email, it is rendering fallback html version and when I am opening format object of mail amp body has content type of 'text/x-amp-html' but it isn't rendering. AMP body is tested on amp developer playground and sender's email is whitelisted.

### System configuration
**Rails version**:
Rails 5.2.3
**Ruby version**:
ruby 2.5.1p57

**Comment by rafaelfranca** [comment]
Action Mailer doesn't affect rendering of email. If the content type is correct and the body as well so it is not an issue in Action Mailer. If you find someone that points to a problem in Action Mailer please let us know and we will reopen the issue.

Thank you
