### ISSUE TITLE
Misleading documentation for rendering a collection of hashes

### ISSUE THREAD

**Issue by krusty3002** [rails/rails#36897]
On https://api.rubyonrails.org/classes/ActionView/PartialRenderer.html it says

> NOTE: Due to backwards compatibility concerns, the collection can't be one of hashes. Normally you'd also just keep domain objects, like Active Records, in there.

I doubt this i still true. I can render a collection of hashes without problems:

`= render :partial => "info_row", :collection => my_collection, :as => :d `

`my_collection` is an Array with Hash elements.

### System configuration
**Rails version**: 5.2.3

**Comment by rafaelfranca** [comment]
Can you open a PR to remove it?
