### ISSUE TITLE
Silencing logging with Ruby 2.3.8 Syslog::Logger in Rails 4.2.11.1 gives no "superclass method 'local_level='"

### ISSUE THREAD

**Issue by Fornacula** [rails/rails#36898]
### Steps to reproduce

1. Configure Rails logger to use Ruby's Syslog logger:
```ruby
module Logging
  class Configurator
      def self.configure!(config)
          config.logger = Syslog::Logger.new('syslog_logger')
      end
  end
end
```
2. User Rails logger (which is configured to use Ruby's Syslog::Logger) to silence certain operation
```ruby
Rails.logger.silence do
  puts "Silence!"
end
```
### Expected behavior
`puts "Silence!"` would be silenced in syslog and no error occures.

### Actual behavior
```ruby
irb(main):002:0> Rails.logger.silence do
irb(main):003:1* puts "Silence!"
irb(main):004:1> end
NoMethodError: super: no superclass method `local_level=' for #<Syslog::Logger:0x000055f3f69d0888>
	from /home/vagrant/.bundle/ruby/2.3.0/gems/activesupport-4.2.11.1/lib/active_support/logger.rb:57:in `block (2 levels) in broadcast'
	from /home/vagrant/.bundle/ruby/2.3.0/gems/activesupport-4.2.11.1/lib/active_support/logger_silence.rb:21:in `ensure in silence'
	from /home/vagrant/.bundle/ruby/2.3.0/gems/activesupport-4.2.11.1/lib/active_support/logger_silence.rb:21:in `silence'
	from /home/vagrant/.bundle/ruby/2.3.0/gems/activesupport-4.2.11.1/lib/active_support/logger.rb:64:in `block (3 levels) in broadcast'
	from /home/vagrant/.bundle/ruby/2.3.0/gems/activesupport-4.2.11.1/lib/active_support/logger_silence.rb:19:in `silence'
	from /home/vagrant/.bundle/ruby/2.3.0/gems/activesupport-4.2.11.1/lib/active_support/logger.rb:62:in `block (2 levels) in broadcast'
	from (irb):2
	from /home/vagrant/.bundle/ruby/2.3.0/gems/railties-4.2.11.1/lib/rails/commands/console.rb:110:in `start'
	from /home/vagrant/.bundle/ruby/2.3.0/gems/railties-4.2.11.1/lib/rails/commands/console.rb:9:in `start'
	from /home/vagrant/.bundle/ruby/2.3.0/gems/railties-4.2.11.1/lib/rails/commands/commands_tasks.rb:68:in `console'
	from /home/vagrant/.bundle/ruby/2.3.0/gems/railties-4.2.11.1/lib/rails/commands/commands_tasks.rb:39:in `run_command!'
	from /home/vagrant/.bundle/ruby/2.3.0/gems/railties-4.2.11.1/lib/rails/commands.rb:17:in `<top (required)>'
	from bin/rails:4:in `require'
	from bin/rails:4:in `<main>'
```

### System configuration
**Rails version**: 4.2.11.1

**Ruby version**: 2.3.8

### Additional insight
I understand the error comes from [here](https://github.com/rails/rails/blob/v4.2.11.1/activesupport/lib/active_support/logger.rb#L57). This change seems to be introduced in [Rails 4.2.7](https://github.com/rails/rails/blob/v4.2.7/activesupport/lib/active_support/logger.rb#L44). Looks like Rails assumes `Syslog::Logger` has the method `local_level=` which it doesn't, meanwhile Rails itself has it:
```ruby
irb(main):001:0> Rails.logger.respond_to?(:local_level=)
=> true
irb(main):002:0> Syslog::Logger.respond_to?(:local_level=)
=> false
```

Not sure if posting here is the correct way to address this, but at least seems to me that this is an incompatibility issue between Rails and Ruby. Since it is caused due to change in Rails code I thought I'll start from here :)

**Comment by wjessop** [comment]
You might struggle to get this looked at, Rails 4.2 is currently only receiving [severe security support](https://guides.rubyonrails.org/maintenance_policy.html) support. You should consider upgrading or you [risk getting left behind](https://www.youtube.com/watch?v=atxQiNpC29s).

**Comment by Fornacula** [comment]
Thanks @wjessop for the quick reply! Understandable, I made a quick fix as a workaround and wrote an override to `local_level=` and `local_level`. Latter method was also missing from Ruby's Syslog::Logger.

```ruby
class Syslog::Logger
  def local_level
    level
  end
  def local_level=(level)
    self.level = level
  end
end
```
