### ISSUE TITLE
Rails goes down because of become incapable for new tech needs

### ISSUE THREAD

**Issue by cooldesigns** [rails/rails#36908]
See phoenix framework, it has live view now.
https://github.com/phoenixframework/phoenix_live_view

Many other things are missed. I don't want to say these again and again.

**Comment by kaspth** [comment]
I’m sorry you must be having a bad day, why don’t you go play with the great and all powerful LiveView since it’s so much better instead? 😊✌️

**Comment by cooldesigns** [comment]
Rails is dead because of core members fixed-headed. Okey I am moving projects in my company. Goodbye rails.

**Comment by cooldesigns** [comment]
@kaspth Look it. It is the response of needs. https://github.com/hopsoft/stimulus_reflex
I've already left rails, but you can play in the children's playground. It's not safe for you out there.

**Comment by kaspth** [comment]
You chose to shift all your company's projects because of one comment from me? Probably not safe for you out there 😂 But hey, hope it works out! Let's cut your training wheels too, I'll lock the conversation ✌️
