### ISSUE TITLE
Rails logger local_level only allows silencing logs but not verbose

### ISSUE THREAD

**Issue by cmrd-senya** [rails/rails#36919]
### Steps to reproduce

Run in the rails console:
```rb
Rails.logger.level = 1
Rails.logger.debug 'not visible'
Rails.logger.local_level = 0
Rails.logger.debug 'visible'
```

### Expected behavior

Output must be 'visible'

### Actual behavior

There is no output

### System configuration
**Rails version**: 5.2.2.1

**Ruby version**: 2.6.2

### Notes

It doesn't happen when you try to "silence" log level, by setting `local_level` to higher values. The root cause is that Ruby logger makes a comparison with a value of instance variable `@level`:
```rb
  # ...
  def add(severity, message = nil, progname = nil)
    severity ||= UNKNOWN
    if @logdev.nil? or severity < @level
      return true
    end
  # ...
```
https://github.com/ruby/logger/blob/master/lib/logger.rb#L459

And `@level` here is a global (not the thread safe) value.

### Solution?

I was able to overcome this issue by including the following module to `ActiveSupport::Logger`:
```rb
module LoggerFix
  class LevelDelegator < SimpleDelegator
    def initialize(object, fallback)
      super(object)
      @fallback = fallback
    end

    def __getobj__
      @delegate_sd_obj.local_level || @fallback
    end
  end

  def level=(level)
    super
    @level = LevelDelegator.new(self, @level)
  end
end

ActiveSupport::Logger.include LoggerFix
```

Thus the Ruby logger will use the delegator instance as `@level` instead of the plain value and therefore will operate on the `local_level` thread safe value. It works, but I wonder if it is actually something which could be considered a proper fix for this issue? Are there any better suggestions which could be used to fix it on Rails level? Should that be fixed on the Rails level at all?

**Comment by cmrd-senya** [comment]
I wonder if it's actually possible to fix it on the level of Ruby logger by replacing usage of the instance variable `@level` with a method call `level`

**Comment by eugeneius** [comment]
This was fixed in https://github.com/rails/rails/pull/37195.
