### ISSUE TITLE
Time attribute changes from Time to ActiveRecord::Type::Time::Value

### ISSUE THREAD

**Issue by tjallingvanderwal** [rails/rails#36910]
### Steps to Reproduce

Pseudo code here. Executable test case below.

```ruby
model = Model.last
# => <#Model id:...>
model.time_attribute.class
# => Time
model.save
# => true
model.time_attribute.class
# => ActiveRecord::Type::Time::Value
```

### Actual behavior
`model.time_attribute.class` changes from `Time` to `ActiveRecord::Type::Time::Value` after calling `model.save`. 

This is a problem if the code later tries to do arithmetic with the time attribute.

### Expected behavior
`model.time_attribute.class` is still `Time` after saving the record.

### System configuration
**Rails version**: 6.0.2.rc1 (using `config.load_defaults 5.2`)
**Ruby version**: 2.6.3

### Executable Test Case
```ruby
# frozen_string_literal: true

require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  gem "rails", '= 6.0.2.rc1'
  gem "sqlite3"
end

require "active_record"
require "minitest/autorun"
require "logger"

# This connection will do for database-independent bug reports.
ActiveRecord::Base.establish_connection(adapter: "sqlite3", database: ":memory:")
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :events, force: true do |t|
    t.time :start
    t.time :stop
  end
end

class Event < ActiveRecord::Base
end

class BugTest < Minitest::Test

  # Failure:
  # BugTest#test_attribute_types [test.rb:51]:
  # --- expected
  # +++ actual
  # @@ -1 +1 @@
  # -Time
  # +ActiveRecord::Type::Time::Value
  def test_attribute_types
    Event.create!(start: '10:00')
    event = Event.last

    assert_equal Time.parse('2000-01-01 10:00:00 UTC'), event.start
    assert_equal Time, event.start.class

    event.save

    assert_equal Time.parse('2000-01-01 10:00:00 UTC'), event.start
    assert_equal Time, event.start.class
  end

  def test_subtract_before_save
    Event.create!(start: '10:00', stop: '11:00')
    event = Event.last

    duration = event.stop - event.start
    assert_equal 3600, duration
  end

  # Error:
  # BugTest#test_subtract_after_save:
  # TypeError: can't convert ActiveRecord::Type::Time::Value into an exact number
  #     test.rb:72:in `test_subtract_after_save'
  def test_subtract_after_save
    Event.create!(start: '10:00', stop: '11:00')
    event = Event.last

    event.save

    duration = event.stop - event.start
    assert_equal 3600, duration
  end

end
```

### My Theory 

* `Time.change` will [implicitly convert](https://github.com/rails/rails/blob/9a2e00e27b87632be3528b53efb8bba504688711/activesupport/lib/active_support/core_ext/time/calculations.rb#L140) `ActiveRecord::Type::Time::Value -> Time` because it always creates a new `Time` instance, whether the receiver of the `change` call is actually a `Time` or not. `ActiveRecord::Type::Time::Value` is [a wrapper](https://github.com/rails/rails/blob/9a2e00e27b87632be3528b53efb8bba504688711/activerecord/lib/active_record/type/time.rb#L8) around `Time`.

* The optimisation introduced in https://github.com/rails/rails/pull/36352/files#diff-79171cddece55f1eaa32d6bcab3c52c9R31-R35, has created a code path that does not "unpack" 
`ActiveRecord::Type::Time::Value` to become a `Time` again.

**Comment by woahdae** [comment]
I'm upgrading my app from 4.2 to 5.0 and hit the same issue. Not sure if this was fixed in 5.1+ and it's a regression in 6.0 or if it's always been this way, but +1 nonetheless.

**Comment by tjallingvanderwal** [comment]
Verified that this behaviour still happens using `6.0.2.rc1` (updated description).

I've tried to fix this in #36914, but I don't think that fix has a chance of being accepted (it is more an investigation, and involves probing if an object is a delegator). The bug arises as a result of a combination of behaviour from ActiveModel and ActiveRecord combined, and where the fix should be made is unclear. 

@kamipo, since you've self-assigned this, I'd like to ask if you think this behaviour is something that will be fixed / should be fixed, or is just something we'll have to work around. 
If there is something I can do to move this along, I'd be glad to do so.

**Comment by tjallingvanderwal** [comment]
For those stumbling across this issue, we decided to monkey patch: 
```ruby
raise 'Reevaluate if this patch is still needed' if Rails.gem_version >= Gem::Version.new("6.1")

ActiveModel::Type::Helpers::TimeValue.module_eval do
  def apply_seconds_precision(value)
    return value unless precision && value.respond_to?(:nsec)

    number_of_insignificant_digits = 9 - precision
    round_power = 10**number_of_insignificant_digits
    rounded_off_nsec = value.nsec % round_power

    if rounded_off_nsec > 0
      value.change(nsec: value.nsec - rounded_off_nsec)
    else
      # Look superfluous and is ugly, but guarentees both
      # branches return the same class.
      value.change(nsec: 0)
    end
  end
end
```

**Comment by tjallingvanderwal** [comment]
I confirmed our test suite doesn't need the monkey path anymore to work.
Thank you for fixing this.
