### ISSUE TITLE
ActiveSupport::Cache::Store#delete doesn't support pass multi keys

### ISSUE THREAD

**Issue by ouyangshi95** [rails/rails#36923]
### Steps to reproduce

```
Rails.cache.write(:a, :a, expires_in: 5.minutes)
Rails.cache.write(:b, :b, expires_in: 5.minutes)
Rails.cache.delete([:a, :b])
Rails.cache.read(:a)
Rails.cache.read(:b)
```
### Expected behavior

`Rails.cache.delete([:a, :b])  => 2`

### Actual behavior

`Rails.cache.delete([:a, :b])  => 0`

### System configuration
**Rails version**: 3.2 to latest version

### Comment
I kowned ActiveSupport::Cache::Store#delete_matched, but I want to delete keys is specific. I don't want use match, because I use cache is redis and it is single thread, I'm afraid it will affect the online service

**Comment by peterzhu2118** [comment]
I opened a pull request to add this feature in #36927.

**Comment by ouyangshi95** [comment]
> I opened a pull request to add this feature in #36927.

I read the pr carefully, it is very good.

**Comment by jeremy** [comment]
Feature request. Moved to implementation at #36927
