### ISSUE TITLE
The list of enable_extension calls in db/schema.rb reorders itself depending on the developer's setup

### ISSUE THREAD

**Issue by dbalatero** [rails/rails#36926]
### Steps to reproduce

Depending on which order a developer has added a Postgres extension, `rake db:schema:dump` will output the `enable_extension` calls in a differing order. This is a bit hard to reproduce but I can dig further if you want more information.

### Expected behavior

Running `rake db:schema:dump` from machine to machine creates consistent `db/schema.rb` files without churn in `git diff`.

### Actual behavior

The `enable_extension` list reorders itself. Check out this screenshot:

![Screenshot 2019-08-13 12 00 03](https://user-images.githubusercontent.com/59429/62969737-c4870980-bdc2-11e9-9583-d102c276f0fc.png)

As you can see, `fuzzystrmatch` is moved to the end of the list of extensions, which creates an unnecessary diff.

My solution to this would be to always sort the extension list, to ensure only adding/removing extensions created a `git diff`. E.g.:

```ruby
enable_extension "ext_a" 
enable_extension "ext_b" 
enable_extension "ext_c" 
```

### System configuration

**Rails version**: 5.1.4
**Ruby version**: 2.6.3
**Postgres version**: 9.6.3

**Comment by dbalatero** [comment]
I'm happy to open a PR for this that sorts the `enable_extension` list if it feels like a good solution to Rails core!

**Comment by rafaelfranca** [comment]
Seems good to me. Please open the PR.

**Comment by dbalatero** [comment]
@rafaelfranca It looks like this is actually handled in `master` so I'm going to try updating gems first:

https://github.com/dbalatero/rails/blob/8ab4fd12f18203b83d0f252db96d10731485ff6a/activerecord/test/cases/schema_dumper_test.rb#L332-L346
