### ISSUE TITLE
A protected action is ignored quietly. Is this a desirable behaviour ?

### ISSUE THREAD

**Issue by kriom** [rails/rails#36924]
Is it normal that protected action are not call quietly ?

### Steps to reproduce
create a new application
generate a controller `rails generate controller Welcome index`
Replace : 
```
  def index
  end
```
by
```
  def index
    raise "Hi!"
  end
```
run server `rails s`
go to : `http://127.0.0.1:3000/welcome/index`
it displays :
```
------
RuntimeError in WelcomeController#index
------

Hi! 

------
Extracted source (around line #3): 
class WelcomeController < ApplicationController
  def index
    raise "Hi!"
  end
end
------
```

Now add `protected` before `def index`
```
  protected def index
    raise "Hi!"
  end
```

it displays :
```
Welcome#index

Find me in app/views/welcome/index.html.erb
```

go to : `http://127.0.0.1:3000/welcome/index`

### Expected behavior
I would have preferred the framework to raise an exception stating that the action is protected, right?

### Actual behavior
It does not raise exception

### System configuration
**Rails version**:
discovered with `rails 4.2.11.1`
and tested with `rails 6.0.0-rc2`

**Ruby version**:
`ruby 2.6.2p47`

**Comment by rafaelfranca** [comment]
This is desired behavior. It is the same as not implementing the action. Only public methods are considered actions and actions are optional if you have a template with the same name. If you don't have a template, neither an action, the framework will raise an error.

**Comment by kriom** [comment]
OK Thank you for this answer.

I discovered this behaviour after a merge that added a protected line above an action method. Therefore the action method was ignored and variables were not initialized for the view. 
What I mean is that, perhaps, a non-existent method and a protected method should be handled differently.

Have a nice day
