### ISSUE TITLE
ActionView::MissingTemplate in Rails 5.2.0

### ISSUE THREAD

**Issue by randhson** [rails/rails#36935]
### Expected behavior
After sending the file, the controller executes the render nothing: true, and should show the registered image on the screen.

### Actual behavior
In a show view, to add a banner field image to a banner category, when uploading the file after refresh, has ActionView :: MissingTemplate response error and headers error 500.

![headers](https://user-images.githubusercontent.com/5396596/63025610-f5794400-be7f-11e9-83c5-638b751d9d09.png)
![preview](https://user-images.githubusercontent.com/5396596/63025611-f611da80-be7f-11e9-8f22-0c82b4ae3381.png)

### System configuration
**Rails version**:
  5.2.0
**Ruby version**:
  2.4.4p296

**Comment by louim** [comment]
Have you tried `head :no_content`? https://guides.rubyonrails.org/layouts_and_rendering.html#using-head-to-build-header-only-responses

**Comment by randhson** [comment]
thanks @louim, but I was able to change and render nothing: true, to render json: nil, status :: ok
