### ISSUE TITLE
`after_commit on: :update` sometimes called even when validation failed

### ISSUE THREAD

**Issue by janko** [rails/rails#36934]
### Steps to reproduce

Run the following self-contained script:

```rb
require "bundler/inline"

gemfile(true) do
  gem "activerecord", "6.0.0.rc2"
  gem "sqlite3"
end

require "active_record"

ActiveRecord::Base.establish_connection(adapter: "sqlite3", database: ":memory:")
ActiveRecord::Base.connection.create_table(:users) do |t|
  t.text :name
end

class User < ActiveRecord::Base
  validates :name, length: { maximum: 6 }

  after_commit on: :update do
    puts "after_commit"
  end
end

user = User.create(name: "short")
user.save # this is required to reproduce

user.name = "too_long"
User.transaction { user.save } # transaction is required to reproduce
```

### Expected behavior

I expected `after_commit` message to be printed once, on the first `user.save`, since the second `user.save` will have failed due to validation errors.

### Actual behavior

The `after_commit` message is printed twice, on the first `user.save`, and on the `User.transaction { user.save }`.

If I remove either the first `user.save`, or the  `User.transaction { ... }`, the bug doesn't occur – both are needed. In other words, the following code doesn't produce this bug:

```rb
user = User.create(name: "short")
user.name = "too_long"
user.save
```

### System configuration

**Rails version**: 6.0.0.rc2, 5.2.3

**Ruby version**: 2.6.0

cc @v-kolesnikov

**Comment by Everett1025** [comment]
Rails transactions are a way to ensure that a set of database operations only occur if all of them succeed.  If you wish to error and rollback action you must use" save!". A normal save does not raise errors, therefore not triggering the rollback in the transaction.

![Capture](https://user-images.githubusercontent.com/25075623/63142926-e9919d00-bfb9-11e9-8945-0665ff858209.PNG)

**Comment by janko** [comment]
@Everett1025 Yes, but sometimes people don't want an exception to be raised. An `after_commit on: :save` callback should have the contract that it's only executed after a successful save, not every time a transaction is committed.

Moreover, the fact the `after_commit on: :save` callback is being executed falsely only in some specific circumstances indicates a bug in Active Record's state management, regardless of the intention behind the code posted above. If it was supposed to not handle using an outer transaction, then the following should also trigger it (and it doesn't):

```rb
user = User.create(name: "short")
user.name = "too_long"
User.transaction { user.save } # transaction is required to reproduce
```

**Comment by latortuga** [comment]
[Per the docs:](https://guides.rubyonrails.org/active_record_callbacks.html#transaction-callbacks)

> When a transaction completes, the after_commit or after_rollback callbacks are called for all models created, updated, or destroyed within that transaction. However, if an exception is raised within one of these callbacks, the exception will bubble up and any remaining after_commit or after_rollback methods will not be executed. As such, if your callback code could raise an exception, you'll need to rescue it and handle it within the callback in order to allow other callbacks to run.

You have to think of `after_commit` as applying to transactions, not to models. If you don't rollback the transaction, it will commit which means after_commits will run. With a single model, Rails knows enough to not run after_commits. But when you make your own transaction, it commits by default and you have to cause it to roll back with an exception.

**Comment by janko** [comment]
If we look at model saving and transactions separately (which I agree makes sense), I would expect `after_commit on: :update` to mean "register this transaction commit hook if the record has been successfully updated". And this actually *is* the case with the following script:

```rb
user = User.create(name: "short")
# user.save

user.name = "too_long"
User.transaction { user.save } # transaction is required to reproduce
```

The problem is that extra `user.save`, which seems to corrupt the model state, because the behaviour is different afterwards. And looking at `ActiveRecord::Transactions` source code this doesn't surprise me; it maintains a lot of internal state which I expect is difficult to keep in sync:

* `@_new_record_before_last_commit`
* `@_committed_already_called`
* `@_start_transaction_state`
* updates many existing instance variables

I think it would help in general to go in the direction of decoupling transactions and transaction callbacks from the model state. Sequel is for me the ideal example; there transactions and transaction hooks are completely decoupled from models:

```rb
class User < Sequel::Model
  # Called only when record was successfully updated.
  def after_update
    super
    # After commit hook is registered on the database object,
    # which doesn't have any knowledge about models.
    DB.after_commit do
      # ...
    end
  end
end
```
