### ISSUE TITLE
Calling ActiveSupport::TimeZone['UTC'].parse on a non-existant date returns a different, valid date

### ISSUE THREAD

**Issue by molenick** [rails/rails#36950]
### Steps to reproduce
[Executable test case](https://gist.github.com/molenick/7911a77a374f83950f5bfec89d09d9bf)

When calling parse with a date that does not exist, the method returns an existing date that overflows forward into the next month.

Some examples:
`ActiveSupport::TimeZone['UTC'].parse('20190231')` returns: 
Sun, 03 Mar 2019 00:00:00 UTC +00:00

`ActiveSupport::TimeZone['UTC'].parse('20190431')` returns: 
Wed, 01 May 2019 00:00:00 UTC +00:00

`ActiveSupport::TimeZone['UTC'].parse('20190631')` returns: 
Mon, 01 Jul 2019 00:00:00 UTC +00:00

### Expected behavior
I think that calling one of these examples should result in an error rather than silently parsing it without issue or notice.  Attempting to parse a string with a day value greater than 31 results in an ArgumentError:
```
ActiveSupport::TimeZone['UTC'].parse('20190332')
Traceback (most recent call last):
        1: from (irb):16
ArgumentError (argument out of range)
```
The same could be done here, though it would require knowing about months, leap years, etc.

### Actual behavior
It returns a different value than one would expect from its input.

### System configuration
**Rails version**:
5.2.3
**Ruby version**:
2.5.3p105
2.6.3

**Comment by rafaelfranca** [comment]
Thank you for the report. This method doesn't function as a validator for dates. It behaves in the same way as `Date._parse`. See http://ruby-doc.org/stdlib-2.6.3/libdoc/date/rdoc/Date.html#method-c-_parse.

```
>> Date._parse('20190231')
=> {:year=>2019, :mon=>2, :mday=>31}
```
