### ISSUE TITLE
Maintenance Policy Guide needs updating for 6.0 release

### ISSUE THREAD

**Issue by jrochkind** [rails/rails#36957]
https://guides.rubyonrails.org/maintenance_policy.html
https://edgeguides.rubyonrails.org/maintenance_policy.html

Contains specific version ranges, for instance says:

> Bug fixes... Currently included series: 5.2.Z.

That should obviously be 6.0.Z. 

I *think* if I understand the policy right the other ones should be:

Security issues: Rails 6.0 and Rails 5.2

Severe security issues: Rails 6.0 and Rails 5.2

(that is, 4.2., 5.0, and 5.1 now entirely out of maintenance support). 

But I'm not certain I'm understanding the policy right, is what keeps me from just doing a PR... (this also is why it's good the guide includes the actual current ranges, rather than just a policy that you have to apply yourself, it can be confusing to be sure you are understanding it correctly and the same as everyone else!)

**Comment by composerinteralia** [comment]
@rafaelfranca the new maintenance policy is showing up correctly on edgeguides, but not https://guides.rubyonrails.org/maintenance_policy.html.

**Comment by rafaelfranca** [comment]
Yes. It will only show on the stable guide when a new release is made.

**Comment by jrochkind** [comment]
I think it's probably a "bug" that it's not showing up on the 6.0 guide, since it applies to 6.0. Is there any way to backport it?
