### ISSUE TITLE
6.0 Migration Guide does not mention config.hosts

### ISSUE THREAD

**Issue by csuhta** [rails/rails#36959]
### Steps to reproduce

While upgrading an app to 6.0, I ran into an issue with needing to specify `config.hosts` for the `HostAuthorization` middleware. That is not mentioned anywhere in the 6.0 migration guide as far as I can tell. 

https://guides.rubyonrails.org/upgrading_ruby_on_rails.html#upgrading-from-rails-5-2-to-rails-6-0

### Expected behavior

Should it? Everyone using a domain in local development and in production will need to set this new config unless they only interface in the default/localhost ways.

### System configuration
**Rails version**: 6.0
**Ruby version**:  2.6.3

**Comment by reesecode** [comment]
Good comment I found on it that could be added to the docs for sure: 

> 

If you’re upgrading to Rails 6 you may find the following error in your browser:

To allow requests to hostname, add the following to your environment configuration:

config.hosts << "hostname"

You ran into Host Authorization, new middleware included in Rails to prevent against DNS rebinding attacks.

By default this feature allows requests from 0.0.0.0, ::, and localhost. There are basically two ways to work around this.

The first option is to whitelist the development hostname in config/environments/development.rb.

Rails.application.configure do
  # Whitelist one hostname
  config.hosts << "hostname"
  # Whitelist a test domain
  config.hosts << /application\.local\Z/
end

The second option is to clear the entire whitelist, which lets through requests for all hostnames.

Rails.application.configure do
  config.hosts.clear
end

Never whitelist everything in production as it essentially turns off the feature.

**Comment by gaffneyc** [comment]
Ran into this today as well. Incredibly annoying that it isn't documented _and_ will break your app if it's not configured.

**Comment by PlugIN73** [comment]
Still not added to docs.

**Comment by jonathanhefner** [comment]
@PlugIN73  See #38140.
