### ISSUE TITLE
ActiveSupport::Cache::MemoryStore internal values can be mutated externally

### ISSUE THREAD

**Issue by jonhyman** [rails/rails#36956]
### Steps to reproduce
Using ActiveSupport 5.1.7 but this bug appears to still exist on master:

```ruby
cache = ActiveSupport::Cache::MemoryStore.new(:size => 1000)
=> <#ActiveSupport::Cache::MemoryStore entries=0, size=0, options={:size=>1000}>

cache.write("test", {"foo" => "bar"})
=> true

data = cache.read("test")
=> {"foo"=>"bar"}

data["foo"] = "xyz"
=> "xyz"

data2 = cache.read("test")
=> {"foo"=>"xyz"}
```

### Expected behavior

Data in the cache should remain unmodified since when it was added to the cache.

### Actual behavior
Data in the cache can be modified by modifying the referenced object.

When data goes into the cache, it is added via `Entry#dup_value!` which Marshal dumps and loads the object for a deep dup. However, because that process is not repeated on cache reads, it possible for a calling method to read from the cache and modify the object by reference. That would be consistent with other cache types, such as `ActiveSupport::Cache::MemCacheStore`.

### System configuration
**Rails version**:
5.1.7

**Ruby version**:
Reproducible on 2.5.5 and 2.6.3.

**Comment by rafaelfranca** [comment]
Can you see you can reproduce with Rails 6? Rails 5.1 is not supported anymore.

**Comment by jonhyman** [comment]
Confirmed. It's still an issue with ActiveSupport 6.0.0.

**Comment by lmansur** [comment]
@jonhyman Do you intend to submit a PR with a fix? I'd like to work on it, if you don't want to.

**Comment by jonhyman** [comment]
I had to step away as we had to patch our own implementation of how we did caching once we realized we ran into this issue. If you want to do something in the next few days feel free. If I worked on it I would store the marshaled string in @data on write, and unmarshal it in read. I believe that would be more analogous to another cache provider such as memcached.

**Comment by kirs** [comment]
Should `AS::Cache#read` always return frozen value?
I think that would solve the issue.

**Comment by jonhyman** [comment]
I don't think it should return frozen values because you may be caching something that can mutate under the hood through its own usage and you could end up causing code paths to break. For us, we were caching the output of a [`Liquid::Template`](https://github.com/Shopify/liquid). It turns out that calling `render` on a Template will modify some internal state. Pseudocode like this would be bad if it returned frozen values:

```ruby
template = cache.read("template_key")
if !template
  template = Liquid::Template.parse("some_text")
  cache.write("template_key", template)
end

# This line would break if the Liquid::Template returned from the cache was frozen.
# It'd be particularly pernicious if this call happens farther away from this cache read.
template.render()
```

In my opinion, the thing to store in the cache is the marshal'd object and unmarshal on read.

**Comment by jonhyman** [comment]
I'd suggest that the solution make both of these tests pass, as they will with will other stores such as `MemCacheStore`:

```ruby
def test_cache_not_mutated
    item = {"foo" => "bar"}
    key = "test_key"
    @cache.write(key, item)

    read_item = @cache.read(key)
    read_item["foo"] = "xyz"
    assert_equal item, @cache.read(key)
  end

  def test_cache_different_object_ids
    item = {"foo" => "bar"}
    key = "test_key"
    @cache.write(key, item)

    read_item = @cache.read(key)
    assert_not_equal item.object_id, read_item.object_id
    assert_not_equal read_item.object_id, @cache.read(key).object_id
  end
```

**Comment by lmansur** [comment]
@jonhyman I took a stab at the fix but wasn't very pleased with my solution. It added significant overhead to a cache entry (275 to 404) and I still had some tests failing.

Feel free to submit that PR.

For what is worth, cache entries that actually get compressed by the `AS::Cache` are already being serialized, so we won't see this issue in this case.

**Comment by jonhyman** [comment]
@lmansur I gave this a shot at https://github.com/rails/rails/pull/36973.

**Comment by jonhyman** [comment]
@rafaelfranca would #36973 be entertained as a solution? I need to fix conflicts in that pull now but would like to know if it's possible to get eyes on it. In my opinion, this is a very severe bug because it can lead to data leakage and incorrect results.

**Comment by jonhyman** [comment]
@rafaelfranca I improved the pull at https://github.com/rails/rails/pull/37210 by only now using dup vs. writing the marshalled version to the cache.

**Comment by jonhyman** [comment]
Thank you!
