### ISSUE TITLE
What is the reasoning of removing Rails 5.0 and 5.1 from "Severe Security Issues" section ?

### ISSUE THREAD

**Issue by JesseChavez** [rails/rails#36960]
I thought with the release of Rails 6.0 the "Severe Security Issues" section in the maintenance policy guide would  look like:

### 4 Severe Security Issues

For severe security issues all releases in the current major series, and also the last major release series will receive patches and new versions. The classification of the security issue is judged by the core team.

**Currently included series:**  `6.0.Z`, `5.2.Z`, `5.1.Z`, `5.0.Z`.

**Comment by nateberkopec** [comment]
I think the guide is incorrect. Rubyonrails.org says: 

> For major security issues, all releases in the current major series, and the last release in the additional major series will receive patches and new versions.

**Comment by nateberkopec** [comment]
I agree that the wording can be confusing. I think the guide should define what the "last major release series" is, because what it _means_ is "only 5.2.z" but I can see how you would _think_ that it's "only 5.y.z"

**Comment by JesseChavez** [comment]
Thanks for the feedback @nateberkopec,  based on your comments  and the previous maintenance policy the changes are consistent.

https://guides.rubyonrails.org/v5.0.0/maintenance_policy.html
https://guides.rubyonrails.org/v5.1.0/maintenance_policy.html

Recently I upgraded some rails 4.2 apps to 5.0 and 5.1 and I just freaked out seeing my upgraded apps won't get severe security patches, anyway I guess I have no choice but upgrade to rails 5.2

**Comment by orenyk** [comment]
Just out of curiosity - what is the reason for distinguishing between `Security Issues` and `Severe Security Issues` if they both apply to the same versions? Thanks!

**Comment by henrik** [comment]
@orenyk As I understand it after looking at https://github.com/rails/rails/pull/37060/files:

If we were currently at 6.3, then "Security Issues" would be released for 6.3 and 6.2. But not 6.1 or 5.2.

Whereas "Severe Security Issues" would be released for 6.3, 6.2, 6.1 as well as 5.2. But not 5.2.
