### ISSUE TITLE
Rails 6.0.0 performance regression because of ActionText::Engine hook

### ISSUE THREAD

**Issue by amatsuda** [rails/rails#36963]
I realized that a vanilla Rails 6.0.0 app consumes much memory than the previous version for handling each request.

Here's what I did for measuring the memory usage for a simple action that returns a "200 OK" HEAD response.

`% rails new rails6_app --skip-spring --skip-bootsnap`

`% rails g controller top index`

```diff
# app/controllers/top_controller.rb
@@ -1,4 +1,5 @@
 class TopController < ApplicationController
   def index
+    head :ok
   end
 end
```

* Bundle `memory_profiler` gem

```diff
# app/controllers/application_controller.rb
 class ApplicationController < ActionController::Base
+  def process_action(*)
+    MemoryProfiler.report { super }.pretty_print(retained_strings: 0, allocated_strings: 0, detailed_report: false)
+  end
 end
```

`% curl http://localhost:3000/top/index`

And here are the results from the Rails 6.0.0 app.

* Rails 6.0.0 results
```
Total allocated: 33819 bytes (267 objects)
Total retained:  10776 bytes (56 objects)

Total allocated: 33819 bytes (267 objects)
Total retained:  10736 bytes (55 objects)

Total allocated: 33859 bytes (268 objects)
Total retained:  10736 bytes (55 objects)

Total allocated: 33313 bytes (264 objects)
Total retained:  10046 bytes (51 objects)

Total allocated: 33043 bytes (262 objects)
Total retained:  9920 bytes (49 objects)

Total allocated: 33353 bytes (265 objects)
Total retained:  10006 bytes (50 objects)
```

Next, I created exactly the same app on Rails version 5.2.3, and here are the results.

* Rails 5.2 results
```
Total allocated: 25406 bytes (247 objects)
Total retained:  6816 bytes (52 objects)

Total allocated: 25446 bytes (248 objects)
Total retained:  6816 bytes (52 objects)

Total allocated: 25406 bytes (247 objects)
Total retained:  6816 bytes (52 objects)

Total allocated: 25406 bytes (247 objects)
Total retained:  6816 bytes (52 objects)

Total allocated: 25446 bytes (248 objects)
Total retained:  6816 bytes (52 objects)
```

You see, Rails 6.0.0 consumes 30% more memory than 5.2.3.

I investigated a little bit deeper and found that the culprit was a `before_action` added via ActionText::Engine. https://github.com/rails/rails/blob/7dfd9d2387e3253f3abd85f7699ca44c338dc77f/actiontext/lib/action_text/engine.rb#L50

In fact, with this simple one-line deletion,

```diff
# .../gems/actiontext-6.0.0/lib/action_text/engine.rb
@@ -47,7 +47,6 @@ module ActionText
       end

       ActiveSupport.on_load(:action_controller_base) do
-        before_action { ActionText::Content.renderer = ApplicationController.renderer.new(request.env) }
       end
     end
   end
```

the Rails 6.0.0 app now responds with almost the same memory consumption as the 5.2.3 app.

* Rails 6.0.0 with the patch results
```
Total allocated: 25664 bytes (249 objects)
Total retained:  6856 bytes (53 objects)

Total allocated: 25664 bytes (249 objects)
Total retained:  6816 bytes (52 objects)

Total allocated: 24848 bytes (243 objects)
Total retained:  6000 bytes (46 objects)

Total allocated: 24848 bytes (243 objects)
Total retained:  6000 bytes (46 objects)

Total allocated: 25198 bytes (247 objects)
Total retained:  6086 bytes (47 objects)
```

The line I deleted was a `before_action` hook that instantiates a renderer for Action Text. This hook runs before every action in every controller even if the action does not use Action Text feature.
And there's no way we can skip this hook because the hook has no name.

I did not attach a patch because I'm not very much familiar with Action Text code base, but I guess there can be some approaches for fixing this issue. Maybe Action Text should instantiate the renderer on demand.

And, for those of you who are running your apps on Rails 6.0.0, the only way that you can avoid this performance regression for now is to stop requiring `action_text/railtie` by doing something like this.

```diff
# config/application.rb
@@ -1,6 +1,23 @@
 require_relative 'boot'

-require 'rails/all'
+%w(
+  active_record/railtie
+  active_storage/engine
+  action_controller/railtie
+  action_view/railtie
+  action_mailer/railtie
+  active_job/railtie
+  action_cable/engine
+  action_mailbox/engine
+  rails/test_unit/railtie
+  sprockets/railtie
+).each do |railtie|
+  begin
+    require railtie
+  rescue LoadError
+  end
+end
```

**Comment by dhh** [comment]
@javan Thoughts on how we can make this instantiation lazy? Maybe just set a reference to the env we need on ActionText::Content, and then allow it to instantiate from that if a renderer is needed?

**Comment by hadees** [comment]
@amatsuda is this still the best solution now that `zeitwerk` can be enabled?

```diff
# config/application.rb
@@ -1,6 +1,23 @@
 require_relative 'boot'

-require 'rails/all'
+%w(
+  active_record/railtie
+  active_storage/engine
+  action_controller/railtie
+  action_view/railtie
+  action_mailer/railtie
+  active_job/railtie
+  action_cable/engine
+  action_mailbox/engine
+  rails/test_unit/railtie
+  sprockets/railtie
+).each do |railtie|
+  begin
+    require railtie
+  rescue LoadError
+  end
+end
```
