### ISSUE TITLE
Memoization issue with `take` resulting in returning wrongly memoized ActiveRecord object on query using find_by/where

### ISSUE THREAD

**Issue by anmolarora** [rails/rails#36977]
### Script to reproduce

```ruby
# frozen_string_literal: true

require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"
  ruby "2.6.3"

  gem "sqlite3"
  gem "rails", '6.0.0'
end

require "active_record"
require "minitest/autorun"

# This connection will do for database-independent bug reports.
ActiveRecord::Base.establish_connection(adapter: "sqlite3", database: "bug_test")
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :posts, force: true do |t|
    t.string :name
  end
end

class Post < ActiveRecord::Base
end

class BugTest < Minitest::Test
  def setup
    10.times do |idx|
      Post.create!(name: idx.to_s)
    end
    @posts = Post.all
    # Pick any arbitrary post using take
    @cached_post = @posts.take
  end

  def test_issue_with_where
    10.times do |idx|
      post_name = idx.to_s
      # Skip for cached post name
      next if post_name == @cached_post.name

      # Get the specific post with name `idx`
      # The post returned will be the cached one since rails is caching the
      # output of take on https://github.com/rails/rails/blob/b9ca94caea2ca6a6cc09abaffaad67b447134079/activerecord/lib/active_record/relation/finder_methods.rb#L504
      idx_post = @posts.where(name: post_name).take

      # This assertion should fail whereas it's passing right now because of
      # memoization by take
      assert_equal post_name, idx_post.name

      # Since memoized post is being returned by take, object_id will be same
      assert @cached_post.object_id != idx_post.object_id
    end
  end

  def test_issue_with_find_by
    10.times do |idx|
      post_name = idx.to_s
      # Skip for cached post name
      next if post_name == @cached_post.name

      idx_post = @posts.find_by(name: post_name)

      # This assertion should fail whereas it's passing right now because of
      # memoization by take
      assert_equal post_name, idx_post.name

      # Since memoized post is being returned by take, object_id will be same
      assert @cached_post.object_id != idx_post.object_id
    end
  end
end
```
All the assertions in the above script should be false whereas they are true because of the bug

Problem is with this line
https://github.com/rails/rails/blob/b9ca94caea2ca6a6cc09abaffaad67b447134079/activerecord/lib/active_record/relation/finder_methods.rb#L504

### Expected behavior

Every time `find_by` or `where` is called on an ActiveRecord relation, it should query the DB every time

### Actual behavior

Querying ActiveRecord relation returns the ActiveRecord object memoized by `take` if `take` was called on the relation before query using `find_by` or `where`

### System configuration
**Rails version**:
6.0.0

**Ruby version**:
2.6.3

**Comment by eileencodes** [comment]
@anmolarora are these assertions supposed to fail on 6.0? They're passing for me.

**Comment by anmolarora** [comment]
The assertions are supposed to pass instead they are passing. @eileencodes

**Comment by eileencodes** [comment]
Ok. This passes on all versions of Rails I tested, 5.2, 6.0, and master. Is this a change in behavior or just a bug you noticed?

**Comment by anmolarora** [comment]
This is a bug. As I've mentioned that `take` is memoizing the ActiveRecord object and after calling `take` every `where/find_by` query is returning the memoized object on the relation

**Comment by eileencodes** [comment]
Is there a version of Rails this script should fail in?

**Comment by anmolarora** [comment]
I've updated the script to make it fail. This should make the bug clearly visible.

**Comment by matthewd** [comment]
It looks like this has been broken forever / since 1379375f93c53d4c49fa8592b6117c3ade263f2e :confused:

`@take` should be cleared in `ActiveRecord::Relation#reset`: https://github.com/rails/rails/blob/6b40767df8635125c62b550d2652074d2e6daf03/activerecord/lib/active_record/relation.rb#L638-L645
