### ISSUE TITLE
Can't resolve @rails/ujs

### ISSUE THREAD

**Issue by afuno** [rails/rails#36991]
**Rails version**: 6.0.0
**Ruby version**: 2.6.3

---

**package.json:**

```json
"@rails/ujs": "^6.0.0-alpha",
```

**app/javascript/packs/application.js:**

```js
require("@rails/ujs").start()
```

I get an error:

> Module not found: Error: Can't resolve '@rails/ujs' in '/app/javascript/packs'

The `@rails/ujs` directory is present in `node_modules`.

For example — other libraries are imported normally:

```js
// app/javascript/packs/application.js

import Lodash from 'lodash'
```

Why is this happening?

**Comment by shailesh-kalamkar** [comment]
@afuno Please check - https://github.com/rails/webpacker/issues/2199

**Comment by afuno** [comment]
@shailesh-kalamkar I do not understand what the author had in mind when he closed his issue.

**Comment by shailesh-kalamkar** [comment]
@afuno You can certainly comment on that issue. I believe this issue is related to the https://github.com/rails/webpacker and not https://github.com/rails/rails

**Comment by afuno** [comment]
https://github.com/rails/webpacker/issues/2244
