### ISSUE TITLE
ActiveJob::TestHelpers#serialize_args_for_assertion Missing in Rails 5.2.2

### ISSUE THREAD

**Issue by edmondchui** [rails/rails#37020]
### Steps to reproduce
`ActiveJob::TestHelpers#serialize_args_for_assertion` used to be in Rails 5.2.1.1. Since Rails 5.2.2 it has been missing. It would be great if it can be added back.

### Expected behavior
`ActiveJob::TestHelpers#serialize_args_for_assertion` is expected to be available as a test helper.

### Actual behavior
`ActiveJob::TestHelpers#serialize_args_for_assertion` is missing since Rails 5.

### System configuration
**Rails version**: 5.2.2

**Ruby version**: 2.4.4

**Comment by y-yagi** [comment]
Rails' public API is only the API showed in https://api.rubyonrails.org/.
`ActiveJob::TestHelpers#serialize_args_for_assertion` is not shown, and this mean `ActiveJob::TestHelpers#serialize_args_for_assertion` is an internal API. Rails do not guarantee the behavior of an internal API. Please avoid using an internal API. Thanks.
