### ISSUE TITLE
[Documentation] no migration notice on legacy npm repository

### ISSUE THREAD

**Issue by baptooo** [rails/rails#37024]
Hello ! thank you for the great job, I am opening this issue to enhance the documentation on npm :)

### Steps to reproduce

Go to https://www.npmjs.com/package/actioncable

### Expected behavior

Add a mention to inform the user about the new repository.

### Actual behavior

There is no mention that the package is now updated on https://www.npmjs.com/package/@rails/actioncable

### System configuration
**Rails version**: N/A

**Ruby version**: N/A

**Comment by sinsoku** [comment]
@baptooo You can find updated information for npm packages by `yarn outdated` command.
Will this information help you?

```console
$ yarn outdated
yarn outdated v1.19.1
info Color legend :
 "<red>"    : Major Update backward-incompatible updates
 "<yellow>" : Minor Update backward-compatible features
 "<green>"  : Patch Update backward-compatible bug fixes
Package              Current Wanted Latest Package Type    URL
@rails/actioncable   6.0.0   6.0.1  6.0.1  dependencies    http://rubyonrails.org/
@rails/activestorage 6.0.0   6.0.1  6.0.1  dependencies    http://rubyonrails.org/
@rails/ujs           6.0.0   6.0.1  6.0.1  dependencies    http://rubyonrails.org/
@rails/webpacker     4.0.7   4.2.0  4.2.0  dependencies    https://github.com/rails/webpacker
webpack-dev-server   3.8.0   3.9.0  3.9.0  devDependencies https://github.com/webpack/webpack-dev-server#readme
✨  Done in 1.41s.
```
