### ISSUE TITLE
Session cookie read should not cause the session cookie to be output

### ISSUE THREAD

**Issue by julik** [rails/rails#37039]
### Steps to reproduce

Largely similar to #3129 but with some more information on why this is a problem.

Run the following test script: https://gist.github.com/julik/d59f51b6c6047776e7a91582f00d73c8

From running it we can see that Rack::Session::Cookie has a provision to not set the session cookie again if the data in the cookie has not been modified, or the cookie options stay the same. Rails however does reencrypt and re-send the session cookie even if it didn't change at all.

### Expected behavior

Reading an arbitrary key from `session` (or from `rack.session` which Rails shares with other apps in the Rack stack) does not cause the session to be re-encrypted and re-output, because there is a check for the session contents on the Rack side. Rack _will_ re-output the session cookie if any options change or the cookie carries expiry, but this is not the case in the provided example. This means that unless an action / Rack application actually changes the session data, the session cannot overwrite a session on the browser side which the browser has obtained _after_ having made the request we are replying to.

This is also the behaviour that Rack::Cookie::Session implements.

### Actual behaviour

Rails regenerates the session cookie, and it is a problem. Here is why: this subtle trait causes race conditions when one wants to use the Rails CSRF protection with multiple frames or with AJAX requests. When in effect, the CSRF token has to be read from the Rails session cookie, which causes it to be overwritten. This creates subtle race conditions when  session authentication is used, because reading the CSRF token (which happens as a side effect of performing any non-idempotent request) overwrites the session. Imagine we have 2 requests in progress, one to an unrelated endpoint like `/search` and another to `/login`:

```
[POST /search] ----------------
                              |
                  (read _csrf_token)
[POST /login]----             |
                |             |
    (add user_id to session)  |
  <-------------              |
  <---- (Set-Cookie: ...)------
```

Additionally, I do suspect that this is not only the case for the the cookie session store but might also be the case for server-side session stores. I haven't verified that assumption.

Given the above (the fact that very subtle bugs can be the case on end applications, the behavior unnecessarily diverges from the behavior of Rack and it has purely to do with Rails' implementation of the cookies) I am inclined not to agree with the conclusion in #3129 in that this is not, in fact, a feature request but a bug.

It _might_ be that this happens because of a side effect that the same data gets re-encrypted, say, with a different `IV` and the string getting generated is then different, even though effectively the same payload is getting encrypted. But I wonder whether it makes sense even from the cryptographic standpoint - because if the data being received is the same as the data that would be getting sent out, revealing the "another encoding" of the same plaintext only gives the hypothetical attacker more data to work with.

## Digression on authentication methods 

Session cookie authentication in apps that are SPAs is not ideal indeed. But it is hard to reasonably expect all today's apps not to be "a little SPA" at least to some extent. Also, migrating to token authentication is a huge endeavour and it is not necessarily accessible to all applications - you need one-time tokens, refresh tokens etc. So if at least life can be made less painful for "semi-SPA" apps I believe it is worth the effort.

### System configuration
**Rails version**: 5.2.3

**Ruby version**: 2.6.3

@tenderlove @rafaelfranca if you are OK with this definition I can try to make a fix for this (given you were the last commenting on the ticket). I see many, may people on the cookie session store file :-)

**Comment by rafaelfranca** [comment]
Go for it! If you want to solve the problem, right now I see no reason to not fix it.

**Comment by julik** [comment]
Alright, expect PR 🚀

**Comment by julik** [comment]
I'm certain it is still reproducible, but I didn't get to making a PR yet
