### ISSUE TITLE
Rails 6 migrations: `t.timestamps` adds `precision: 6`

### ISSUE THREAD

**Issue by 6temes** [rails/rails#37031]
### Steps to reproduce

When creating a new migration in Rails 6:

```
class CreateProducts < ActiveRecord::Migration[6.0]  
  def change    
    create_table :products do |t|      
      t.string :name
      t.timestamps    
    end 
  end
end
```

A new option, `precision` is created:

```
    t.datetime "created_at", precision: 6, null: false
    t.datetime "updated_at", precision: 6, null: false
```

The change was introduced in this PR: 

https://github.com/rails/rails/pull/34970

Following this discussion:

https://github.com/rails/rails/pull/34956#discussion_r248841394

It seems that, initially, the goal was to solve a problem with MySQL version updates, but for some reason, the subsequent PR targetted all Databases, including Postgres.

My question is: Is there any good reason to explicitly specify the precision of the timestamps by default in Postgres? If so, would it be possible to document the reasons somewhere?

### System configuration
**Rails version**: 6.0
**Ruby version**: 2.6.3

**Comment by yahonda** [comment]
If you want `timestamps` attributes behaves like Rails 5.2 or older, you can specify ` ActiveRecord::Migration[5.2]` at the first line of your migration file as follows.

* Migration file
```ruby
class CreateProducts < ActiveRecord::Migration[5.2]
  def change
    create_table :products do |t|
      t.string :name

      t.timestamps
    end
  end
end
```

* db/schema.rb 

```ruby
$ more db/schema.rb
# This file is auto-generated from the current state of the database. Instead
# of editing this file, please use the migrations feature of Active Record to
# incrementally modify your database, and then regenerate this schema definition.
#
# This file is the source Rails uses to define your schema when running `rails
# db:schema:load`. When creating a new database, `rails db:schema:load` tends to
# be faster and is potentially less error prone than running all of your
# migrations from scratch. Old migrations may fail to apply correctly if those
# migrations use external dependencies or application code.
#
# It's strongly recommended that you check this file into your version control system.

ActiveRecord::Schema.define(version: 2019_08_24_111757) do

  # These are extensions that must be enabled in order to support this database
  enable_extension "plpgsql"

  create_table "products", force: :cascade do |t|
    t.string "name"
    t.datetime "created_at", null: false
    t.datetime "updated_at", null: false
  end

end
```

**Comment by 6temes** [comment]
Hi!

Thank you very much for your answer.

My question was not about how to make migrations behave as in Rails 5.2, but rather to understand the reasons that motivated the change, as they are not very clear for me, following the history of PR.

**Comment by emptyflask** [comment]
This causes problems when overriding default datatypes, for instance, forcing timestamps to always use `WITH TIME ZONE` (which IMHO should be default behavior anyway, since Rails doesn't always write UTC times) -- Rails will construct the SQL incorrectly as `TIMESTAMP WITH TIME ZONE(6)`.

Anyway, here's a temporary solution for anyone else running into this:

```ruby
# Add time zones by default
require 'active_record/connection_adapters/postgresql_adapter'

module ActiveRecord
  module ConnectionAdapters
    class PostgreSQLAdapter

      # override default rails 6 behavior so we can add precision to the
      # correct part of the data type (see below)
      def supports_datetime_with_precision?
        false
      end

      NATIVE_DATABASE_TYPES.merge!(
        datetime:  { name: "TIMESTAMP(6) WITH TIME ZONE" },
        timestamp: { name: "TIMESTAMP(6) WITH TIME ZONE" }
      )
    end
  end
end
```

**Comment by jcoleman** [comment]
I also wondered why this was changed and [asked](https://github.com/rails/rails/pull/34970#issuecomment-885189513) on the original PR with no response.

It seems very weird that this change was made to fix MySQL, the discussion said it should not be for PostgreSQL, but then the implementation did exactly the opposite (made it apply everywhere).
