### ISSUE TITLE
Maintenance guide is out of date (should be replaced by edge guide)

### ISSUE THREAD

**Issue by henrik** [rails/rails#37058]
Hi! https://guides.rubyonrails.org/maintenance_policy.html seems out of date after the Rails 6 release.

https://edgeguides.rubyonrails.org/maintenance_policy.html looks more correct (actually mentions Rails 6), though it also looks a little off – shouldn't 5.1 and 5.0 also be included under "Severe Security Issues"?

**Comment by henrik** [comment]
Made a PR to add 5.1 and 5.0: https://github.com/rails/rails/pull/37059

**Comment by eugeneius** [comment]
As mentioned in https://github.com/rails/rails/issues/36957#issuecomment-523073282, the guides are only updated when a new version is published. The maintenance policy update was backported in https://github.com/rails/rails/commit/4c8c8cd8b4c692a3186a78e1e587f416820d1b1d, and will be reflected in the stable guides when 6.0.1 is released.

**Comment by henrik** [comment]
Thanks, @eugeneius!
