### ISSUE TITLE
Changing collate and charset in a mysql table column  is not updating in schema.rb

### ISSUE THREAD

**Issue by vaidhyanathan-ananthakrishnan** [rails/rails#37076]
### Steps to reproduce
We wanted to change the collate option ( from default to *utf8_bin*)for a column in MySQL table. 
Changes were made using Active record migration inside which alter table was used.
The changed collate is not getting updated in the schema.rb 

### Expected behaviour
Schema.rb should store the collation and character set for the changed column

### Actual behaviour
Schema.rb ignoring the collation and character set changes in MySQL. Causing the schema:load behaving wrongly. 

### System configuration
**Rails version**:
3.2.22.5
**Ruby version**:
ruby 2.3.7p456 (2018-03-28 revision 63024) [x86_64-darwin18]

I dont think the support for this is provided in recent version also.

**Comment by kamipo** [comment]
Fixed by #17574.
