### ISSUE TITLE
ActionText Missing partial error when using prepend_view_path

### ISSUE THREAD

**Issue by jeffblake** [rails/rails#37072]
### Steps to reproduce

If I have a controller as such:

```
class MyController < ApplicationController
  prepend_view_path 'app/views/frontend'
end
```

And I attempt to use Action Text's helper `render_action_text_content`, I get an error `ActionView::MissingTemplate Missing partial frontend/action_text/attachables/_remote_image`

The error is pretty clear, and copying the views from the actiontext gem into the `frontend` directory fixes it.

 

### Expected behavior

The default view templates in the actiontext gem are used. Instead of looking for the `frontend/action_text/attachables/_remote_image` partial in `app/views/frontend`, it should be looking for the `action_text/attachables/_remote_image` partial in `app/views/frontend`, `app/views`, `"/Users/blake/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/actiontext-6.0.0/app/views"` and finally finding it in the gem directory.

### Actual behavior

Missing partial error

### System configuration
**Rails version**: 6

**Ruby version**: 2.6.3

**Comment by abhaynikam** [comment]
@jeffblake : I could not reproduce this issue on master and on Rails 6.0. `render_action_text_content` is working fine for me with `prepend_view_path ` in controller. PFA screenshot of logs of sample application I tried in

<img width="1425" alt="issue-37072" src="https://user-images.githubusercontent.com/7736232/64754274-498d4c00-d544-11e9-8fb7-9f5a84dc36e5.png">

**Comment by marceloperini** [comment]
@jeffblake I can provide more information about this problem?

**Comment by jeffblake** [comment]
Closing this, I think it was related to a helper I created (that called `render_action_text_content` directly) to render content differently based on whether the text was saved by Froala editor, or ActionText.
