### ISSUE TITLE
Add` presence: true` option to Model by default.

### ISSUE THREAD

**Issue by 100010** [rails/rails#37074]
If you add the `null: false` option to the migration file, it is unlikely that you will not use the` presence: true` option in the Model.

So if the `null: false` option is present in the migration file,
I want the Model with the option `presence: true` by default.

How about this?
Thanks.

**Comment by eileencodes** [comment]
Hey @100010 we reserve the issues tracker for bug reports and generally it's easier to discuss a behavior change on a PR. This sounds useful if you'd like to implement it!
