### ISSUE TITLE
Bug after forgetting to rollback before `rails d`

### ISSUE THREAD

**Issue by ezii123** [rails/rails#37082]
Couldn't the migration id be a hash of the changeset and order of the migration somehow? 

Because:

When I generate a scaffold, run the migration and then delete it and generate just the migration, I forgot to rollback before generating just the migration. Sometimes this can happen.

Then my only option is dropping the database and re-creating it.

**Comment by y-yagi** [comment]
Thanks for your issue. But we reserve the Rails issue tracker only for bugs in Rails. 
Please use the [Rails Core mailing list](https://groups.google.com/forum/#!forum/rubyonrails-core) for feature requests, where a wider community will be able to help you. Thanks!
