### ISSUE TITLE
Feature request:  generate a credentials.yml.example template file after credentials:edit

### ISSUE THREAD

**Issue by KelseyDH** [rails/rails#37087]
Rails secret credentials is great, but if you're on a team working on multiple git branches who are both editing `credentials.yml.enc`, because that file is encrypted it appears impossible to know what credentials have been added or modified when you rebase.  (You only know the file has changed.)

On a smaller team this doesn't matter, but on a bigger team this could result in one team having credentials that are needed for their branch to work getting deleted, when another team rebases their changes to `credentials.yml.enc` against another branch.

So it would be nice if `rails credentials:edit` could save/update a blank `credentials.yml.example` after every edit that only contains blank YAML keys about the structure of the `credentials.yml.enc` file, so that when git conflicts occur team members can know exactly which credentials they need to add in, along with their changes, when fixing merge conflicts for this file.

Additionally having a `credentials.yml.example` file automatically generated would also help team members recover from losing a key, by providing a reference of all the keys that need to get replaced, and/or set up, to get their clone of the rails app running.

### System configuration
**Rails version**: 6.0

**Ruby version**: 2.6.6

**Comment by kaspth** [comment]
Credentials in 6.1 can be diffed: https://github.com/rails/rails/blob/ffd74f58b0837e91815152d4fb4cfcfc0b6b4a1c/railties/lib/rails/commands/credentials/USAGE#L33-L46

So I don't think we'll move forward with a separate manifest file. Thanks!

(We don't take feature requests on the issue tracker by the way, use the rails-core mailing list in the future)
