### ISSUE TITLE
Rails Action Text for existing text field

### ISSUE THREAD

**Issue by aryalsan** [rails/rails#37089]
I am upgrading one of my news app to Rails 6.0.0. While working around I got a problem using Rich Text. My app is pointing the rich text body field instead of the my existing table body field.

Is it possible to use the existing table text field for the rich text, so that I can edit the archive contents whenever I need it. Like for new posts I can use the action_text_rich_texts table but for the existing posts I want to use the existing table body field.

**Comment by matheussfsc** [comment]
I think that's not possible yet, but meanwhile you can do workaround like the following:
`
require_relative "app/models/notice.rb"
​
puts " - Starting script"
puts " - Updating field: Text from Blogs"
​
Blog.find_each do |blog|
  if blog.text.body.nil?
    puts "Updating Text for Blog ID: #{blog.id}"
    blog.update_attribute(:text, blog.text_before_type_cast)
  end
end`

**Comment by y-yagi** [comment]
Thanks for your issue. This issue is duplicated with #35002. So let's track that. Thanks.
