### ISSUE TITLE
Feature Request: Picture Tag

### ISSUE THREAD

**Issue by trcarden** [rails/rails#37086]
With the increased usage of "modern" image formats like webp there is a need for multiple image formats depending on browser support. The standard way of doing this looks to be the <picture> tag (https://developer.mozilla.org/en-US/docs/Web/HTML/Element/picture). 

Ideally this tag would work like the select_tag or another multi item view helper.

The three prevailing formats: webp, Jpeg 2000, and JPEGXR have fragmented browser support:
https://caniuse.com/#feat=jpeg2000
![image](https://user-images.githubusercontent.com/460530/63980408-615acf80-ca70-11e9-888b-50e6fa5c82d3.png)

https://caniuse.com/#feat=webp
![image](https://user-images.githubusercontent.com/460530/63980413-6881dd80-ca70-11e9-90cd-05152a25dea8.png)

https://caniuse.com/#feat=jpegxr
![image](https://user-images.githubusercontent.com/460530/63980369-3a040280-ca70-11e9-9deb-86f441ed39fd.png)

**Comment by eileencodes** [comment]
Hey @trcarden - we appreciate the suggestion, but we don't take feature requests on the issues tracker. We reserve it for bug reports in supported versions of Rails.

You can either propose the feature on the Rails mailing list or open a PR for discussion. 

You can read more about contributing to Rails on the [guides](https://edgeguides.rubyonrails.org/contributing_to_ruby_on_rails.html)

Thanks for understanding!

**Comment by trcarden** [comment]
Yeah no worries @eileencodes. I'll see about putting it in the right place
