### ISSUE TITLE
ActiveJob: changing `queue_name_prefix` in one Job affects all other jobs.

### ISSUE THREAD

**Issue by lmansur** [rails/rails#37084]
### Steps to reproduce
```ruby
# frozen_string_literal: true

require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  gem "activejob", "6.0"
end

require "minitest/autorun"
require "active_job"

class HelloJob < ActiveJob::Base
  def perform
    puts "Hello!"
  end
end

class PrefixedJob < ActiveJob::Base
  self.queue_name_prefix = "production"

  def perform
    puts "Hello again!"
  end
end

class QueueNamePrefixJobTest < ActiveJob::TestCase
  def test_queue_name_prefix
    assert_equal "production", PrefixedJob.queue_name_prefix
    assert_nil HelloJob.queue_name_prefix
  end
end
```

### Expected behavior
When setting `queue_name_prefix` inside a `Job`, I expect only that job to have the prefix.

### Actual behavior
All `Job`s use the `queue_name_prefix` that was given to a single `Job`

### System configuration
**Rails version**: 5.1, 5.2, 6.0 (probably also present <5.0)

**Ruby version**: 2.6.3p62

### Additional context

This looks very similar to issue #16960 (fixed in #16992).

My application currently uses `Sidekiq` as the `queue_adapter`. However, we now need to also use `Shoryuken` for some jobs. For the `Sidekiq` jobs, we don't need any prefixes, but we need them for the `Shoryuken` jobs. Changing the prefix only in the `Shoryuken` jobs is changing the prefix in all jobs.

Happy to try and fix this if this really isn't the intended behavior.

**Comment by louim** [comment]
According to the documentation, this is the expected behavior:
https://guides.rubyonrails.org/active_job_basics.html#queues

>You can prefix the queue name for all your jobs using config.active_job.queue_name_prefix in application.rb:

Since it is a class variable it will affect all jobs independently or where you define it. But maybe like the issue you mentioned, the behavior could be changed.

In your case, you could probably use [`queue_as`](https://api.rubyonrails.org/classes/ActiveJob/QueueName/ClassMethods.html#method-i-queue_as) to configure the name of the queue you want depending of your adapter.

**Comment by lmansur** [comment]
> In your case, you could probably use [`queue_as`](https://api.rubyonrails.org/classes/ActiveJob/QueueName/ClassMethods.html#method-i-queue_as) to configure the name of the queue you want depending of your adapter.

That's what we are currently doing, interpolating the prefix with the name, but I feel like it defeats the purpose of having a prefix setter.
