### ISSUE TITLE
Link in HTTP and not in HTTPS

### ISSUE THREAD

**Issue by patriarch** [rails/rails#37098]
### Steps to reproduce
Have a server in HTTP with a load balancer in HTTPS

### Expected behavior
Link to files in S3 in HTTPS

### Actual behavior
Link to files in S3 in HHTP

Is it possible to force the link of files in HTTPS ???

**Comment by ekampp** [comment]
Where are you linking from? ActoveStorage? In which case you can use the service_url method to get the S3 link directly.

**Comment by y-yagi** [comment]
Please use the [mailing list](https://groups.google.com/forum/#!forum/rubyonrails-talk) or StackOverflow for questions/help, where a wider community will be able to help you. We reserve the issues tracker for issues only. Thanks.
