### ISSUE TITLE
Active Record locks connections to threads that checked them out

### ISSUE THREAD

**Issue by janko** [rails/rails#37092]
### Steps to reproduce

```rb
require "active_record"

ActiveRecord::Base.establish_connection(
  adapter:          "sqlite3",
  database:         ":memory:",
  pool:             5, # default
  checkout_timeout: 5, # default
)

threads = 10.times.map do
  Thread.new do
    ActiveRecord::Base.connection.execute "SELECT 1"
  end
end

threads.each(&:join)
```

### Expected behavior

I expected the above code to complete without errors.

The connection pool is intentionally smaller than the number of threads, but since we're executing cheap queries, I expected connections to be immediately checked back into the pool, so that other threads can use them.

### Actual behavior

I get connection timeout from 6 threads:

```
ActiveRecord::ConnectionTimeoutError: could not obtain a connection
from the pool within 5.000 seconds (waited 5.001 seconds);
all pooled connections were in use
```

This is because, once Active Record checks out a connection, it **locks** it to the thread that checked it out, so only that thread can continue to use it. Once the main thread + 4 other threads checked out their 5 connections, the other 6 threads didn't have any connections available.

### Current workarounds

Historically, Active Record users have been recommended to either

1. clear out active connections with `AR::Base.clear_active_connections!`
2. manually check out the connection with `AR::Base.connection_pool.with_connection { ... }`

In Rails, this has been managed automatically. Originally, there was a `ConnectionManagement` middleware that called `AR::Base.clear_active_connections!` after each request, releasing locked connections back into the pool. Today, this is surprisingly done by [AR::QueryCache](https://github.com/rails/rails/blob/01cc0c183dfa7e4235cd58aa4f41deef215b8ebe/activerecord/lib/active_record/query_cache.rb#L43), which makes it appear as if though this functionality is only needed for query caching, when in fact it affects Active Record usage in general.

In other web frameworks such as [Sinatra](https://github.com/janko/sinatra-activerecord/blob/0f079e6000d2b3b00c642ab9af971466e401ba90/lib/sinatra/activerecord.rb#L33), you need to call manually `AR::Base.clear_active_connections!` after each request. In background jobs, it's recommended to use `AR::Base.connection_pool.with_connection { ... }`.

### Rationale

I believe Active Record's connection pool should automatically check connections back into the pool after queries are finished, available for any other thread to use it. Basically, what `AR::Base.connection_pool.with_connection { ... }` does.

This is how Sequel's connection pool works. If we run the same script using Sequel, it will complete without errors:

```rb
require "sequel"

DB = Sequel.sqlite(max_connections: 5, pool_timeout: 5)

threads = 10.times.map do
  Thread.new do
    DB.run "SELECT 1"
  end
end

threads.each(&:join)
```

I believe this change would reduce the chance of people running out of connections. For example, they wouldn't need to remember to use `ActiveRecord::Base.connection_pool.with_connection { ... }` in background jobs. Yes, users _should_ configure sufficiently large pools, but maybe at some point they start using threads inside background jobs, and don't realize that this requires them to increase the pool size even more.

I also believe this could reduce the load on the database, because it would allow using the smaller number of connections in certain cases. A pool of 50 background workers could theoretically use only 10 connections if the queries are fast.

### System configuration

**Rails version**: master, 6.0.0, and probably any other version before

**Ruby version**: 2.6.0

**Comment by p8** [comment]
I can confirm the test fails on stable-4-2, stable-5-0, stable-5-1 and stable-5-2 branches.

**Comment by p8** [comment]
Reading the documentation of ConnectionPool it looks like connections are cached in `@thread_cached_conns`
```ruby
      def connection
        @thread_cached_conns[connection_cache_key(current_thread)] ||= checkout
      end
```
I guess creating connections is expensive and you don't want to delete the query cache:
> This variable tracks the cache of threads mapped to reserved connections, with the
sole purpose of speeding up the +connection+ method. It is not the authoritative
registry of which thread owns which connection.

https://github.com/rails/rails/blob/01cc0c183dfa7e4235cd58aa4f41deef215b8ebe/activerecord/lib/active_record/connection_adapters/abstract/connection_pool.rb#L393

**Comment by janko** [comment]
Yes, connections should definitely stay cached. But they don't need to stay assigned to any thread, they can be made available "for grabs" by any thread.

**Comment by janko** [comment]
The original script still reproduces the failure on `6-0-stable`.

**Comment by abrisse** [comment]
I encountered the same issue and had to explicitely use `ActiveRecord::Base.clear_active_connection!` in all the threads I manually create.

Just saw that issue, so to give my 2 cents, I find it really counter-intuitive since that's not how a standard pool works. I guess the current design may be related to some threaded cache in AR.

**Comment by notactuallytreyanastasio** [comment]
We are experiencing this on Rails 6.0.3.4 currently.

I would be happy to explore this issue if it is something that folks are open to.

We currently will be exploring ways to work around it tomorrow, but we are processing some 5 digit number of sidekiq jobs and keep getting this when we use any code with `ActiveRecord::Base.connection.execute` in our worker jobs (or, atleast, that is the current leading theory, we need to validate this in the morning).

I can provide a more detailed diagnostic run of the issue once I have some more time to analyze it if anyone else considers this issue to be worth re-exploring.

**Comment by Ben-Fenner** [comment]
I've run into this exact issue just now and would love to know the current thinking on this matter. Does the Fiber-safe ticket shown above take this issue and run with it? I'll need to give it  abetter read...
