### ISSUE TITLE
active_support/message_encryptor.rb:169:in `key=': key must be 16 bytes (ArgumentError)

### ISSUE THREAD

**Issue by filosofisto** [rails/rails#37099]
### Steps to reproduce
Up to version 5.1.7, always when I try to create a new rails project the error occour:

activesupport-6.0.0/lib/active_support/message_encryptor.rb:169:in `key=': key must be 16 bytes (ArgumentError)

I am using a macOS Mojave version 10.14.6, and using rbenv.

### System configuration
**Rails version**: Rails 6.0.0 (but all versions from 5.1.7 was tested, but just versions less or equals to 5.1.7 works)

**Ruby version**: 2.6.4p104 (2019-08-28 revision 67798) [x86_64-darwin18]

Any helps?

**Comment by filosofisto** [comment]
Just to improve error details, here is stack trace:

Traceback (most recent call last):
	29: from /Users/Eduardo/.rbenv/versions/2.6.4/bin/rails:23:in `<main>'
	28: from /Users/Eduardo/.rbenv/versions/2.6.4/bin/rails:23:in `load'
	27: from /Users/Eduardo/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/railties-6.0.0/exe/rails:10:in `<top (required)>'
	26: from /Users/Eduardo/.rbenv/versions/2.6.4/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	25: from /Users/Eduardo/.rbenv/versions/2.6.4/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	24: from /Users/Eduardo/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/railties-6.0.0/lib/rails/cli.rb:18:in `<top (required)>'
	23: from /Users/Eduardo/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/railties-6.0.0/lib/rails/command.rb:46:in `invoke'
	22: from /Users/Eduardo/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/railties-6.0.0/lib/rails/command/base.rb:65:in `perform'
	21: from /Users/Eduardo/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	20: from /Users/Eduardo/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	19: from /Users/Eduardo/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	18: from /Users/Eduardo/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/railties-6.0.0/lib/rails/commands/application/application_command.rb:26:in `perform'
	17: from /Users/Eduardo/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
	16: from /Users/Eduardo/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/thor-0.20.3/lib/thor/group.rb:232:in `dispatch'
	15: from /Users/Eduardo/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/thor-0.20.3/lib/thor/invocation.rb:133:in `invoke_all'
	14: from /Users/Eduardo/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/thor-0.20.3/lib/thor/invocation.rb:133:in `map'
	13: from /Users/Eduardo/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/thor-0.20.3/lib/thor/invocation.rb:133:in `each'
	12: from /Users/Eduardo/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/thor-0.20.3/lib/thor/invocation.rb:133:in `block in invoke_all'
	11: from /Users/Eduardo/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	10: from /Users/Eduardo/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	 9: from /Users/Eduardo/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/railties-6.0.0/lib/rails/generators/rails/app/app_generator.rb:331:in `create_credentials'
	 8: from /Users/Eduardo/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/railties-6.0.0/lib/rails/generators/app_base.rb:156:in `build'
	 7: from /Users/Eduardo/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/railties-6.0.0/lib/rails/generators/rails/app/app_generator.rb:177:in `credentials'
	 6: from /Users/Eduardo/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/railties-6.0.0/lib/rails/generators/rails/credentials/credentials_generator.rb:30:in `add_credentials_file_silently'
	 5: from /Users/Eduardo/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/activesupport-6.0.0/lib/active_support/encrypted_configuration.rb:29:in `write'
	 4: from /Users/Eduardo/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/activesupport-6.0.0/lib/active_support/encrypted_file.rb:50:in `write'
	 3: from /Users/Eduardo/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/activesupport-6.0.0/lib/active_support/encrypted_file.rb:76:in `encrypt'
	 2: from /Users/Eduardo/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/activesupport-6.0.0/lib/active_support/message_encryptor.rb:151:in `encrypt_and_sign'
	 1: from /Users/Eduardo/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/activesupport-6.0.0/lib/active_support/message_encryptor.rb:169:in `_encrypt'
/Users/Eduardo/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/activesupport-6.0.0/lib/active_support/message_encryptor.rb:169:in `key=': key must be 16 bytes (ArgumentError)

Best,
Eduardo

**Comment by filosofisto** [comment]
I have changed to RVM (before I was using rbenv), and with some effort, it works.

Thanks,
Eduardo

**Comment by karimmtarek** [comment]
@filosofisto care to share what did you do to resolve this? I'm on Rails 6.0.2.2, Ruby 2.7.1 and RVM 1.29.1

**Comment by phlegx** [comment]
I have the same error.

**Comment by macsimacsi** [comment]
Thanks for the help!
