### ISSUE TITLE
Active Storage video preview fails to process correctly in active job

### ISSUE THREAD

**Issue by iraszl** [rails/rails#37124]
### Steps to reproduce

1. Create a Rails 5 or 6 project.
2. Create a model. For example: `rails g Post title:string body:text`
3. Install active storage.
4. Add an :image and :video field to the model, and redirect to index page instead of post show page in controller for easier testing.
5. Test that you can upload and display both the image and video fields.
6. Add a variant to the image, as: `image_tag @post.image.variant(resize_to_limit: [200,200]).processed`
7. Add a preview to the video, as `image_tag @post.video.preview(resize_to_limit: [200,200]).processed`
8. Test that they generate correctly on the fly with the show action.
9. Now, put both the image and video into active jobs to pre-generate the variant and the preview so it doesn't need to be generated on the fly, instead generate them in advance.
10. Example for the image:
```
class ImagevariantJob < ApplicationJob
  queue_as :default

  def perform(post)
    post.image.variant(resize_to_limit: [200,200]).processed
  end
end
```
11. Example for the video:
```
class VideopreviewJob < ApplicationJob
  queue_as :default

  def perform(post)
    post.video.preview(resize_to_limit: [200,200]).processed
  end
end
```
12. Create a post and note that both the image and video active job runs successfully.
13. When you load the show action, you will notice in the logs that while the image variant has been loaded instantly without the need to generate it on the fly (because it has been pre-generated).
14. Here is the problem: **Note that the video preview has to be generated on the fly even though it has theoretically been pre-generated. It looks like the path or (something else) for the preview file generated in the active job is different from the file generated on the fly in the show action.**

### Expected behavior
I expect the video preview to be pre-generated in the active job, the same way as it is pre-generates image variants.

### Actual behavior
Instead, I can only pre-generate image variants in active job, not video previews. Even though the video preview file generates in the active job, it's different from the file that is required on the show page, so it has to be generated again on the fly. After which the preview file is saved correctly and it doesn't need to be regenerated every time.

For some reason calling `post.video.preview(resize_to_limit: [200,200]).processed` from Active Job doesn't create an image file that will be used when calling `image_tag @post.video.preview(resize_to_limit: [200,200]).processed` from a view.

### System configuration
5.x and 6.x

**Ruby version**:
2.5.3

**Comment by iraszl** [comment]
If anyone comes across this problem looking for a solution, there is a good way to resolve this problem: Generate the thumbnail from the video in the background job, and save the image to another field. For example, the active job could look something like this:

```
class VideoPreprocessJob < ApplicationJob
  queue_as :default

  def perform(post_id)
    post = Post.find(post_id)
      thumb = post.video.preview(resize: '200x200').processed
      file_path = ENV['BASE_DOMAIN'].to_s + Rails.application.routes.url_helpers.rails_representation_url(thumb, only_path: true).to_s
      post.thumbnail.attach(io: open(file_path), filename: 'video_thumbnail.jpg', content_type: 'image/jpg')
    end
  end
end
```

**Comment by patrickespake** [comment]
I'm using Rails 7.0.8, and I had the same issue.
