### ISSUE TITLE
ActiveStorage fails silently when used on a model with a non_integer id

### ISSUE THREAD

**Issue by camiloforero** [rails/rails#37128]
### Steps to reproduce
Generate a model with a string primary key and a has_one_attached file,
Create a new record
Attach a file to that new record

### Expected behavior
Trying to assign a `string` id value to the `Integer` type `record_id` will raise an error immediately, which will be quickly noticed and fixed by the developer

### Actual behavior
As described in this comment: https://github.com/rails/rails/pull/32466#issuecomment-460105791

If the ID starts with a number, the attachment will still be accessible from the record (but not the other way around)

If the ID starts with any other character, it will be cast into a `nil` and then into a `0`, which will still not fail during the initial saving operation.

This inconsistent behaviour causes all kinds of fun and exciting bugs (some attachments will work, some attachments won't work, and if two records have IDs `83ab` and `83cd`, a file attached to one will be accessible from the other. This was difficult to debug and pinpoint
### System configuration
**Rails version**: 6.0.0

**Ruby version**: 2.6.2

### Additional information
Here is the log of the database operations that ran when saving the record after assigning the `signed_id` to it

![rails bug](https://user-images.githubusercontent.com/6606686/64154676-f2ee8680-ce4e-11e9-8161-bb274b689d05.PNG)

Note how the `record_id` starts as `nil` and then gets a value of `0`, I believe the whole issue starts there

**Comment by ziaulrehman40** [comment]
How to reopen this issue?

This is insane, there are multiple issues closed for this bug. I am seeing a lot of such corner case issues relating different things which are closed automatically without a resolution. This I think is hurting framework's health.

How can we help in the scenarios like this?

**Comment by ziaulrehman40** [comment]
@camiloforero Can you update the title:
```
ActiveStorage silently saves corrupted data when used on a model with a non_integer id
```
