### ISSUE TITLE
Is it possible for me to extend the model by adding an image using Active Storage 6.0.0?

### ISSUE THREAD

**Issue by gordienko** [rails/rails#37126]
Is it possible for me to extend the model by adding an image using Active Storage 6.0.0?

For activestorage-5.2.3, I did like this:

```ruby
ActsAsTaggableOn::Tag.class_eval do
    extend ActiveStorage::Attached::Macros
    has_one_attached :image
end
```

**Comment by georgeclaghorn** [comment]
`ActiveStorage::Attached::Macros` was renamed to `ActiveStorage::Attached::Model` in 6.0, if that’s what you’re asking.

**Comment by gordienko** [comment]
I added to the rails application initialization config/initializers/acts_as_taggable_on.rb:

```ruby
ActsAsTaggableOn::Tag.class_eval do
    extend ActiveStorage::Attached::Model
    has_one_attached :image
end
```
When I start the application, I get the following error,
gems/activerecord-6.0.0/lib/active_record/dynamic_matchers.rb:22:in `method_missing': undefined method `has_one_attached' for #<Class:0x00007f81c4173520> (NoMethodError).

With rails 5.2, everything worked.

**Comment by georgeclaghorn** [comment]
You want to `include` it, not `extend` it.

**Comment by gordienko** [comment]
George, when I use include:

```ruby
ActsAsTaggableOn::Tag.class_eval do
    include ActiveStorage::Attached::Model
    has_one_attached :image
end
```
I get the following error:

gems/activerecord-6.0.0/lib/active_record/reflection.rb:44:in `reflection_class_for': Unsupported Macro: has_one_attached (RuntimeError)

**Comment by International** [comment]
@gordienko probably the initializer from 'active_storage/reflection' did not run. Look in the engine class, is this code:

```
    initializer "active_storage.reflection" do
      ActiveSupport.on_load(:active_record) do
        include Reflection::ActiveRecordExtensions
        ActiveRecord::Reflection.singleton_class.prepend(Reflection::ReflectionExtension)
      end
    end

```

**Comment by gordienko** [comment]
> @gordienko probably the initializer from 'active_storage/reflection' did not run. Look in the engine class, is this code:
> 
> ```
>     initializer "active_storage.reflection" do
>       ActiveSupport.on_load(:active_record) do
>         include Reflection::ActiveRecordExtensions
>         ActiveRecord::Reflection.singleton_class.prepend(Reflection::ReflectionExtension)
>       end
>     end
> ```

Thanks Georg for the help! 
So it happened:

```ruby
ActsAsTaggableOn::Tag.class_eval do
    include ActiveStorage::Reflection::ActiveRecordExtensions
   ActiveRecord::Reflection.singleton_class.prepend(ActiveStorage::Reflection::ReflectionExtension)
    include ActiveStorage::Attached::Model
    has_one_attached :image
end
```
