### ISSUE TITLE
--skip-webpack-install doesn't skip webpack install

### ISSUE THREAD

**Issue by stevensona** [rails/rails#37130]
### Steps to reproduce
`rails new --skip-webpack-install useful_app`

### Expected behavior
Webpack install doesn't run.

### Actual behavior
Webpack install does run.

### System configuration
**Rails version**: 6.0.0

**Ruby version**: ruby 2.6.4p104 (2019-08-28 revision 67798) [x86_64-linux]

I understand that the Webpacker is the default JavaScript compiler for Rails 6, however perhaps the option should be removed if it doesn't do anything?

**Comment by bogdanvlviv** [comment]
See https://github.com/rails/rails/issues/35484#issuecomment-469798114

**Comment by stevensona** [comment]
> [we added `--skip-webpack-install`](https://github.com/rails/rails/pull/34071) to be able to prevent running `rails webpacker:install` when generating new rails app.

This is why I opened the issue. The `--skip-webpacker-install` flag *doesn't do that*. `rails webpacker:install` still runs. It's entirely possible I'm misunderstanding something.

```
rails new --skip-webpack-install useful_app
...
       rails  webpacker:install
...
Webpacker successfully installed
```

**Comment by bogdanvlviv** [comment]
`rails --help` here is the pattern of how to create new rails app it `rails new APP_PATH [options]` - `rails new` receives an app name first and then options:

Try executing `rails new useful_app --skip-webpack-install`, this should work as expected.

**Comment by stevensona** [comment]
Ugh :slightly_frowning_face: Thank you, sir.
