### ISSUE TITLE
Rails migration guide does not mention the removal of render :text

### ISSUE THREAD

**Issue by Qwertie-** [rails/rails#37145]
`render :text` was [removed in 5.1](https://github.com/rails/rails/commit/79a5ea9eadb4d43b62afacedc0706cbe88c54496) but it is not mentioned in the [upgrading guide for 5.1](https://guides.rubyonrails.org/upgrading_ruby_on_rails.htm). It is mentioned that it is discouraged under the 4.0 to 4.1 upgrade but it would be useful to see it mentioned on the release it was removed from.

**Comment by gmcgibbon** [comment]
Fixed in https://github.com/rails/rails/pull/37197
