### ISSUE TITLE
Using `select("DISTINCT ON (something) *").update_all` updates all records, not just distinct ones

### ISSUE THREAD

**Issue by briankung** [rails/rails#37140]
### Steps to reproduce
See repo: https://github.com/briankung/rails_distinct_update_all_bug

Essentially do a `select("DISTINCT ON (something) *").update_all`. I can't personally get the executable test case working since it hangs on fetching dependencies, but theoretically it is as follows:

```rb
# frozen_string_literal: true

require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  gem "rails", github: "rails/rails"
  gem "sqlite3"
end

require "active_record"
require "minitest/autorun"
require "logger"

# This connection will do for database-independent bug reports.
ActiveRecord::Base.establish_connection(adapter: "sqlite3", database: ":memory:")
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :posts, force: true do |t|
    t.text :username
    t.boolean :updated, default: false
  end
end

class Post < ActiveRecord::Base
end

class BugTest < Minitest::Test
  test "update_all on distinct on (attribute) updates only distinct records" do
    ["Bob", "Alice"].each do |username|
      10.times { Post.create(username: username, updated: false) }
    end

    distincts = Post.select("DISTINCT ON (username) *")
    number_of_posts = Post.count
    number_selected = distincts.length
    number_updated = distincts.update_all(updated: true)

    # This passes, so we know the number selected != the number of posts
    refute_equal(number_selected, number_of_posts)

    # Each of the following fails, however
    refute_equal(number_updated, number_of_posts)
    refute(Post.pluck(:updated).all? {|updated| updated == true})
  end
end
```

### Expected behavior
It should update only the records selected with the `DISTINCT ON` query, instead of all of the records

### Actual behavior
It updates all of the records

### System configuration
**Rails version**: 6.0.0

**Ruby version**: ruby 2.6.0p0 (2018-12-25 revision 66547) [x86_64-darwin18]

**Database**: psql (PostgreSQL) 11.4

**Comment by latortuga** [comment]
`update_all` does not work the same as other AR query interfaces, because it does not operate on each item in the collection. Instead, it uses `where` and `order` from the current scope and the updates you pass in to construct a single SQL query to b executed. Importantly for your situation, `select` is ignored by this API. I think this is intended behavior.

Some options for you would be to use [`execute`](https://api.rubyonrails.org/classes/ActiveRecord/ConnectionAdapters/DatabaseStatements.html#method-i-execute) or [`exec_update`](https://api.rubyonrails.org/classes/ActiveRecord/ConnectionAdapters/DatabaseStatements.html#method-i-exec_update) to run your custom SQL.

**Comment by vnhnhm** [comment]
> I think this is intended behavior.

Just wondering, is this documented somewhere @latortuga?

**Comment by simi** [comment]
@vnhnhm seems it is not - https://api.rubyonrails.org/classes/ActiveRecord/Relation.html#method-i-update_all.

I think it is related to this code: https://github.com/rails/rails/blob/09fbee82dc765496a9ab8dbdc9542676447132fc/activerecord/lib/arel/visitors/to_sql.rb#L803-L816. It doesn't preserve `projections`.
