### ISSUE TITLE
DOCXAnalyzer NameError. Is referenced in guides.

### ISSUE THREAD

**Issue by archonic** [rails/rails#37148]
I was seeing undefined method `analyze` for blobs for docx uploads, and found this:

https://api.rubyonrails.org/classes/ActiveStorage/Blob/Analyzable.html#method-i-analyze

However referencing DOCXAnalyzer gets a NameError. It appears to only exist in the guides. Does anyone know if I need to install something and what to get a DOCX analyzer?

**Comment by georgeclaghorn** [comment]
The reference to `DOCXAnalyzer` is in an example of registering a custom analyzer—one that’s hypothetically implemented in your app or a third-party gem.
