### ISSUE TITLE
ActiveRecord::Base.connected_to(database: :replica) { } causes connections to replica outside of block

### ISSUE THREAD

**Issue by trevorrjohn** [rails/rails#37158]
I have two databases, one called primary and one called replica, replica is readonly naturally. When I use `ActiveRecord::Base.connected_to` to connect to the replica it connects properly and I can read the data. However once I enable this in one of my controllers I start seeing `ActiveRecord::ReadOnlyError` raised in our error logs on controllers that do not try to connect to the replica. I have tried to upload the relevant code snippets. Happy to supply more details as needed. 

### Steps to reproduce
```ruby
class AdminController < ApplicationController
  def index
    ActiveRecord::Base.connected_to(database: :replica) { @users = User.order(:created_at).limit(10) } 
  end
end

class UsersController < ApplicationController
  def update
     user = User.find(params[:id])
     user.update(user_params)
  end
end

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
 
  connects_to database: { writing: :primary, reading: :primary }
end

class User < ApplicationRecord
  # do not define connects_to
end

# database.yml
...
production:
  primary:
    <<: *default
  replica:
    <<: *default
    port: <%= ENV.fetch('DB_REPLICA_PORT', 5433) %>
    replica: true
```

### Expected behavior
ActiveRecord should never connect to the `replica` database unless inside the block. 

### Actual behavior
I see `ActiveRecord::ReadOnlyError` raised in our error log from the `UsersController`.

### System configuration
**Rails version**:
6.0
**Ruby version**:
2.6.3

**Comment by eileencodes** [comment]
Hey @trevorrjohn are you using the middleware Rails provides? If you are and you'll need to make sure to call `while_preventing_writes(false)` until 6.0.1 is released (or build yourself from source). This sounds like you're hitting the issue I fixed in https://github.com/rails/rails/pull/37065

**Comment by eileencodes** [comment]
Oh your setup is incorrect as well. This should be:

```ruby
class AdminController < ApplicationController
  def index
    ActiveRecord::Base.connected_to(role: :reading) { @users = User.order(:created_at).limit(10) } 
  end
end

class UsersController < ApplicationController
  def update
     user = User.find(params[:id])
     user.update(user_params)
  end
end

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
 
  connects_to database: { writing: :primary, reading: :replica }
end

class User < ApplicationRecord
  # do not define connects_to
end

# database.yml
...
production:
  primary:
    <<: *default
  replica:
    <<: *default
    port: <%= ENV.fetch('DB_REPLICA_PORT', 5433) %>
    replica: true
```

**Comment by trevorrjohn** [comment]
Thanks @eileencodes, I am using Rails middleware. However I am not configuring the connection here.

Regarding the setup: I am still experimenting with this I didn't want to have reads always go to the replica so that is why my config is the way that it is. Maybe I am misunderstanding how the `:reading` option works though. My understanding is by changing `reading: :replica` any select statements would now go to the `replica`,  where I only want to read from the replica in my admin controller (for the time being).

I will try calling `while_preventing_writes` in my block, it does sound like that might be the issue? However I don't quite get why my other controller would try to connect to the replica.

**Comment by trevorrjohn** [comment]
This seems related actually: https://github.com/rails/rails/issues/36830#issuecomment-523517821

**Comment by eileencodes** [comment]
>  I didn't want to have reads always go to the replica so that is why my config is the way that it is

In that case I'd recommend setting up the connections for writing/reading to the primary/replica and turning off the middleware until you're ready. Using `connected_to(database x)` is for one-off connections, not for connections during requests and since it re-establishes a connection every time it'll cause problems.

**Comment by chipset508** [comment]
@eileencodes Im upgrading rails 5.2 to 6.0.6 and my case is exactly like @trevorrjohn described, my approach is just adding one more role `reading_from_replica`, and using that in the controller/service/etc... 

```ruby
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
 
  connects_to database: { writing: :primary, reading: :primary, reading_from_replica: :replica }
end

class AdminController < ApplicationController
  def index
    ActiveRecord::Base.connected_to(role: :reading_from_replica) { @users = User.order(:created_at).limit(10) } 
  end
end

```
just wondering if that is the correct approach? thank you

**Comment by chipset508** [comment]
@aksharj yep, it works
