### ISSUE TITLE
Rails 5.2+ enum field validation failed: is not a number

### ISSUE THREAD

**Issue by agate** [rails/rails#37150]
### Steps to reproduce

1. Save this to a ruby file. Like `test.rb`. And run `ruby test.rb` in your terminal.

```ruby
# frozen_string_literal: true

begin
  require "bundler/inline"
rescue LoadError => e
  $stderr.puts "Bundler version 1.10 or later is required. Please update your Bundler"
  raise e
end

gemfile(true) do
  source "https://rubygems.org"

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  gem "rails", "5.1.7" # pass
  # gem "rails", "5.2.3" # fail
  # gem "rails", "6.0.0" # fail
  gem "sqlite3"
end

require "active_record"
require "minitest/autorun"
require "logger"

ActiveRecord::Base.establish_connection(adapter: "sqlite3", database: ":memory:")
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :users, force: true do |t|
    t.integer :status, default: 0, null: false
  end

end

class User < ActiveRecord::Base
  enum status: %w[foo bar hello world]
  validates :status, presence: true, numericality: { only_integer: true, greater_than_or_equal_to: 0, less_than_or_equal_to: 3 }
end

class BugTest < Minitest::Test
  def test_save_user
    user = User.new
    result = user.save

    puts "------------------------------"
    puts "ERRORS: #{user.errors.inspect}"
    puts "------------------------------"

    assert_equal true, result
  end
end
```

2. Uncomment rails 5.2.3 or 6.0.0 line and comment the rails 5.1.7 line for testing different version behavior.

### Expected behavior

I expect Rails 5.2.3 should also able to pass the test.

### Actual behavior

Test failed. And user's errors shows:
`ERRORS: #<ActiveModel::Errors:0x000055b0f41a5ab8 @base=#<User id: nil, status: "foo">, @messages={:status=>["is not a number"]}, @details={:status=>[{:error=>:not_a_number, :value=>"foo"}]}>`

### System configuration
**Rails version**:
5.2.3, 6.0.0
**Ruby version**:
2.6.4

**Comment by eugeneius** [comment]
This behaviour changed in https://github.com/rails/rails/commit/fe9547b6fb60d92af181c8613166fa4322f8e307. Previously the validation operated on the raw value from the database (0), but now it uses the type cast value ("foo").

I don't think numericality validations on enum attributes make sense; from the application's point of view, the attribute has string values, not integers. An inclusion validation would be a better choice:

```ruby
validates :status, inclusion: { in: statuses }
```

I can't see why that validation would ever be necessary, though, as enum attributes reject invalid values on assignment:

https://github.com/rails/rails/blob/v6.0.0/activerecord/lib/active_record/enum.rb#L140-L144

Let me know if I've overlooked something, but I don't think this we need to support this usage.

**Comment by agate** [comment]
@eugeneius Thanks for the quick response! I think 

> from the application's point of view, the attribute has string values, not integers

Make sense to me.

Closing this.
