### ISSUE TITLE
Rollback in after_commit resets id to nil

### ISSUE THREAD

**Issue by Tolsto** [rails/rails#37152]
Rails 5.2 will return an object with `id: nil` when the after commit triggers a rollback.

Consider the following example:

```
class Test < ApplicationRecord

  after_commit :remove_foo

  validates :foo, presence: true

  def remove_foo
    self.foo = nil
    save
  end
end
```

```
irb(main):001:0> Test.create(foo: 'bar').id
   (0.1ms)  begin transaction
  Test Create (0.3ms)  INSERT INTO "tests" ("foo") VALUES (?)  [["foo", "bar"]]
   (4.1ms)  commit transaction
   (0.0ms)  begin transaction
   (0.0ms)  rollback transaction
=> nil
```

The behaviour was introduced in this change https://github.com/rails/rails/commit/9029884ecba3dde2248a923d7d1857beef263518 by @kamipo 

Is this now the expected behaviour? Rails 5.1 would return an object with the actual id of the created record.

**Comment by eugeneius** [comment]
This is not the expected behaviour. Here's an executable test case:

```ruby
# frozen_string_literal: true

require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  gem "rails", github: "rails/rails"
  gem "sqlite3"
end

require "active_record"
require "minitest/autorun"
require "logger"

# This connection will do for database-independent bug reports.
ActiveRecord::Base.establish_connection(adapter: "sqlite3", database: ":memory:")
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :users, force: true do |t|
    t.string :name, null: false
  end
end

class User < ActiveRecord::Base
  validates :name, presence: true
  after_commit -> { update(name: nil) }
end

class BugTest < Minitest::Test
  def test_rollback_in_after_commit
    user = User.create!(name: "foo")
    refute_nil user.id
    refute user.new_record?
  end
end
```

Even though 5f8115a1859ee883b3289c1e5ed8e5924e4a61b4 did introduce the problem for `id`, the second assertion fails even before that, so there's a deeper problem here.

**Comment by dahal** [comment]
I don't think it's being rolled back, looks like commit does happen, but `ActiveModel::Errors` prolly has something do with it.


<img width="685" alt="Screen Shot 2019-09-11 at 11 22 56 PM" src="https://user-images.githubusercontent.com/3684236/64759167-3d28d500-d4eb-11e9-94ac-45f871920907.png">
