### ISSUE TITLE
String inflection method  underscore giving wrong output

### ISSUE THREAD

**Issue by praveendhawan** [rails/rails#37163]
### Steps to reproduce
Open up rails console and type - 

`"ActLikeStar".underscore` gives you `'act_like_star'`  which is correct.

Now Type - 
`"AB".undescore` . which gives you `'ab'` which seems to be incorrect.

### Expected behavior

It should give output like this `'a_b'`

### Actual behavior

Its giving output as `'ab'`

Is this expected behavior?

### System configuration
**Rails version**: 5.0.7

**Ruby version**: 2.6.1

**Comment by p8** [comment]
This is expected behaviour. So we can do:
```    
   "HTMLTidy".underscore re "html_tidy"
```
https://github.com/rails/rails/blob/892c30d0250319c6218ba54b3b94c65f4247550d/activesupport/test/inflector_test_cases.rb#L140

**Comment by y-yagi** [comment]
As @p8 explained, this is expected behavior. If it is expressed only in uppercase letters, almost case expect it to not include an underscore. Thanks.
