### ISSUE TITLE
Rails Guide for ActiveStorage test file cleanup seems incompatible with parallel testing

### ISSUE THREAD

**Issue by matpowel** [rails/rails#37160]
We've just implemented in Rails 6 production and are busy writing a pile of tests. We very much want to take advantage of the new parallel testing option but have hit a concern when it comes to integration and system tests that use ActiveStorage down in the app somewhere.  Basically, the [Edge Guides](https://edgeguides.rubyonrails.org/active_storage_overview.html#discarding-files-stored-during-system-tests) suggest doing an rm -rf on the test storage dir but of course if the forked testing processes are executing on the same file system that will cause the risk of all sorts of indeterminate race conditions.

### Steps to reproduce
* Create a series of test cases that proceed to attach files via active storage and rely on using those attached files within the app and/or test assertions
* Implement the recommended rm -rf method in the Edge Active Storage Guide in the teardown method.
* Run the tests in parallel mode with as many threads/processes as possible, at some point a race condition will occur wherein thread 1 tries to read a file that was previously attached but then wiped by the teardown of another thread

### Expected behavior
* The official Rails Guides should specify a way to only delete files attached within the current thread/test run
* One possible solution would be to allow the active storage dir in test mode to append the process/thread number, just like happens with the databases
* Another solution would be to run blocks which will eventually result in activestorage attachments being created within a method that tracks all attachments and wipes the files afterwards. Something like:

`ensure_storage_cleanup { code_that_creates_attachments }`

### Actual behavior
* Implementing the recommended teardown method of removing test files will cause race conditions

### System configuration
**Rails version**: 6.x

**Ruby version**: Any

**Comment by henrypoydar** [comment]
I'm not sure the solution should be ActiveStorage-specific, since there are a number of ways (using CarrierWave for example) to run into the same problem.  Some sort of Rails-native after :suite hook would be my preference. (`Minitest.after_run { ... }` still fires for each worker).

**Comment by matpowel** [comment]
@henrypoydar I agree with the fix being more related to parallel testing than AS as such, however I think the ActiveStorage specific piece of this is that a) ActiveStorage is one of the more likely testing areas to write files out to disk and b) the documentation that needs changing is the in the AS specific Guide. Maybe the immediate "fix" is to change the text in the Guide to at least warn of the incompatibility of parallel testing and this method of cleanup?

FWIW I really like the idea of an after_suite type hook.
