### ISSUE TITLE
Rails 6 / Ruby 2.6.4 - ActiveSupport's `#include?`, `#cover?`, `===` extensions break if invoked on endless ranges with a range parameter

### ISSUE THREAD

**Issue by pond** [rails/rails#37177]
Related:

* https://github.com/rails/rails/issues/36451
* https://github.com/rails/rails/pull/36460
* https://github.com/rails/rails/issues/37172

### Steps to reproduce

* Ensure https://github.com/rails/rails/pull/36460 is applied
* Create any new Rails 6 project
* `bundle exec rails c` to access console
* Execute statement `(1..).include?(2..4)` (or use `#cover?`, or use `===`)

### Expected behavior

* Evaluates to `true`

### Actual behavior

* The statement leads to the exception `RangeError (cannot get the last element of endless range)` being raised.

### System configuration

**Rails version**: 6.0.0 patched with https://github.com/rails/rails/pull/36460
**Ruby version**: 2.6.4

### Discussion

#36451 noted an issue with specifically `#include?` and only that method, when given a non-range parameter. I reported this under #37172 having not found that original report, as it was already closed - fixed by #36460. Unfortunately this didn't fix a set of similar faults which arise when the extension methods are called with a _range_ as an input parameter.

**Comment by pond** [comment]
Patch submission: https://github.com/rails/rails/pull/37178

**Comment by pond** [comment]
Bump on this - simple enough PR, important fix, all wrapped up as requested into a single commit & ready to go. Just waiting for the merge pretty much.

**Comment by kaspth** [comment]
Backported this to 6-0-stable in https://github.com/rails/rails/compare/11885f26bd...2bc6a948a2
