### ISSUE TITLE
ActionText forces all apps to include an ActionController::Base subclass

### ISSUE THREAD

**Issue by mperham** [rails/rails#37183]
In 6.0.0, ActionText adds an executor run hook which depends on ApplicationController.

https://github.com/rails/rails/blob/66cabeda2c46c582d19738e1318be8d59584cc5b/actiontext/lib/action_text/engine.rb#L42

In a background job process, where I am doing no web processing, this executor hook still runs. Is this intended or necessary? Can I disable ActionText somehow?

**Comment by georgeclaghorn** [comment]
It’s definitely not intentional to require applications to define `ApplicationController`. We’ve been looking to fix this for a while.
