### ISSUE TITLE
Zeitwerk handles constructor functions oddly

### ISSUE THREAD

**Issue by bhaibel** [rails/rails#37198]
### Steps to reproduce

A repository whose tests reproduce the bug is available here:
https://github.com/bhaibel/zeitwerk_misses_constructors

If I define a `BigDecimal`-style class constructor in the same file as its class, and the class is nested inside a module, then Zeitwerk can't autoload it.

So, concretely: I have the following file at `app/models/namespace/klass_with_constructor.rb`:

```
module Namespace
  class KlassWithConstructor
  end
end

def Namespace::KlassWithConstructor
  Namespace::KlassWithConstructor.new
end
```

and I invoke `Namespace::KlassWithConstructor()` elsewhere.

### Expected behavior
`Namespace::KlassWithConstructor()` should return an instance of the class.

### Actual behavior
`undefined method `KlassWithConstructor' for Namespace:Module`.

However, if I include a reference to `Namespace::KlassWithConstructor` in `app/models/namespace.rb`, that's sufficient to force Zeitwerk to load the other file and the undefined method errors go away.

### System configuration
**Rails version**: 6.0.0

**Ruby version**: 2.6.3

**Comment by fxn** [comment]
Rails provides _constant_ autoloading. In `Namespace::KlassWithConstructor()`, `KlassWithConstructor` is a method name, not a constant name. Like `Integer()`.

**Comment by fxn** [comment]
Since `KlassWithConstructor()` is a method that belongs to `Namespace`, the normal place to have it defined is in `namespace.rb`:

```ruby
module Namespace
  def self. KlassWithConstructor
    KlassWithConstructor.new
  end
end
```

That is idiomatic and flows well with constant autoloading.

**Comment by bhaibel** [comment]
Yes, I'm quite aware that `KlassWithConstructor` is a method as well as a constant -- that's why I knew that invoking the constant to force Zeitwerk to load its file would be an effective workaround.

However, your suggested alternate solution doesn't seem idiomatic to me. Whenever I've encountered constructor functions, I've seen them defined in the same file as the class they construct. This makes sense organizationally -- they don't have anything to do with the functionality of the larger module, they have to do with the class they construct.

**Comment by fxn** [comment]
I understand you prefer to define the method in the other file, but the fact is a missing method name is not going to autoload the file where the method name is defined, no matter how it looks.

That is not an oddity of Zeitwerk, Rails provides autoloading of constants, that's the feature that you have to autoload code.

**Comment by matthewd** [comment]
> Rails provides autoloading of constants, that's the feature that you have to autoload code

While it's certainly not a bug, for all the above reasons... I do see the argument that it organizationally makes more sense to put such a magic constructor with its corresponding constant. (I'd personally stop short of "idiomatic", just because I don't think I've seen enough instances.)

I think I'd be interested to consider the code impact of supporting this (in Rails, not Zeitwerk), as a distinct bonus autoloading behaviour. At first glance, it seems like it might be pretty achievable, self-contained, and low-impact. _If_ that's true, I like the idea of giving a good experience to, and in turn subtly encouraging the use of, the constant-named-method construct for things like value objects.

**Comment by fxn** [comment]
Oh yes, my point of view is that this is not common enough to be supported by Rails or Zeitwerk, but that you can do it yourself.

To show this is doable, the idea of the implementation could be something like this:

```ruby
module ConstructorAutoloader
  def method_missing(name, *args)
    if name.match?(/\A[A-Z]/)
      begin
        const_get(name)
      rescue NameError
        super
      else
        send(name, *args)
      end
    else
      super
    end
  end
end

class Module
  include ConstructorAutoloader
end
```

**Comment by fxn** [comment]
I have edited the draft above the partial error handling. That way the core idea is clear, and the incompleteness of the example also more apparent.

From there to a robust solution, whether you want `respond_to?` or not, etc. is left to be filled.
