### ISSUE TITLE
[Parallel Testing] byebug crashing on new Rails project

### ISSUE THREAD

**Issue by chrismaltais** [rails/rails#37207]
### Steps to reproduce
1. Create a new Rails project: `rails new project-foobar --database=mysql --api`
2. Create database: `rake db:create`
3. Generate a new model: `rails g model FruitFarm apple:string orange:string`
4. Migrate database: `rake db:migrate`
5. Uncomment out sample test in `/test/models/fruit_farm_test.rb`, add a `byebug` statement before `assert true`
```ruby
require 'test_helper'

class FruitFarmTest < ActiveSupport::TestCase
  test "the truth" do
    byebug
    assert true
  end
end
```
6. Test application: `rails test`
7. When in the `byebug` shell, press `c` to continue with the program.

Do steps 6 & 7 (i.e. keep re-testing), ~5-10 times, the error shows up inconsistently.

### Expected behavior
The test suite should continue to completion without an issue!

### Actual behavior
Getting the following error:
```
Traceback (most recent call last):
	19: from /Users/chrismaltais/.rvm/rubies/ruby-2.6.0/lib/ruby/gems/2.6.0/gems/minitest-5.11.3/lib/minitest.rb:63:in `block in autorun'
	18: from /Users/chrismaltais/.rvm/rubies/ruby-2.6.0/lib/ruby/gems/2.6.0/gems/minitest-5.11.3/lib/minitest.rb:133:in `run'
	17: from /Users/chrismaltais/.rvm/gems/ruby-2.6.0/gems/activesupport-6.0.0/lib/active_support/testing/parallelization.rb:74:in `start'
	16: from /Users/chrismaltais/.rvm/gems/ruby-2.6.0/gems/activesupport-6.0.0/lib/active_support/testing/parallelization.rb:74:in `map'
	15: from /Users/chrismaltais/.rvm/gems/ruby-2.6.0/gems/activesupport-6.0.0/lib/active_support/testing/parallelization.rb:74:in `each'
	14: from /Users/chrismaltais/.rvm/gems/ruby-2.6.0/gems/activesupport-6.0.0/lib/active_support/testing/parallelization.rb:74:in `times'
	13: from /Users/chrismaltais/.rvm/gems/ruby-2.6.0/gems/activesupport-6.0.0/lib/active_support/testing/parallelization.rb:75:in `block in start'
	12: from /Users/chrismaltais/.rvm/gems/ruby-2.6.0/gems/activesupport-6.0.0/lib/active_support/testing/parallelization.rb:75:in `fork'
	11: from /Users/chrismaltais/.rvm/gems/ruby-2.6.0/gems/activesupport-6.0.0/lib/active_support/testing/parallelization.rb:95:in `block (2 levels) in start'
	10: from /Users/chrismaltais/.rvm/rubies/ruby-2.6.0/lib/ruby/2.6.0/drb/drb.rb:1138:in `method_missing'
	 9: from /Users/chrismaltais/.rvm/rubies/ruby-2.6.0/lib/ruby/2.6.0/drb/drb.rb:1158:in `with_friend'
	 8: from /Users/chrismaltais/.rvm/rubies/ruby-2.6.0/lib/ruby/2.6.0/drb/drb.rb:1139:in `block in method_missing'
	 7: from /Users/chrismaltais/.rvm/rubies/ruby-2.6.0/lib/ruby/2.6.0/drb/drb.rb:1213:in `open'
	 6: from /Users/chrismaltais/.rvm/rubies/ruby-2.6.0/lib/ruby/2.6.0/drb/drb.rb:1213:in `synchronize'
	 5: from /Users/chrismaltais/.rvm/rubies/ruby-2.6.0/lib/ruby/2.6.0/drb/drb.rb:1216:in `block in open'
	 4: from /Users/chrismaltais/.rvm/rubies/ruby-2.6.0/lib/ruby/2.6.0/drb/drb.rb:1216:in `each'
	 3: from /Users/chrismaltais/.rvm/rubies/ruby-2.6.0/lib/ruby/2.6.0/drb/drb.rb:1218:in `block (2 levels) in open'
	 2: from /Users/chrismaltais/.rvm/rubies/ruby-2.6.0/lib/ruby/2.6.0/drb/drb.rb:1262:in `alive?'
	 1: from /Users/chrismaltais/.rvm/rubies/ruby-2.6.0/lib/ruby/2.6.0/drb/drb.rb:1005:in `alive?'
/Users/chrismaltais/.rvm/rubies/ruby-2.6.0/lib/ruby/2.6.0/drb/drb.rb:1005:in `wait_readable': Bad file descriptor (Errno::EBADF)
Traceback (most recent call last):
	2: from /Users/chrismaltais/.rvm/rubies/ruby-2.6.0/lib/ruby/gems/2.6.0/gems/minitest-5.11.3/lib/minitest.rb:63:in `block in autorun'
	1: from /Users/chrismaltais/.rvm/rubies/ruby-2.6.0/lib/ruby/gems/2.6.0/gems/minitest-5.11.3/lib/minitest.rb:140:in `run'
/Users/chrismaltais/.rvm/gems/ruby-2.6.0/gems/activesupport-6.0.0/lib/active_support/testing/parallelization.rb:118:in `shutdown': Queue not empty, but all workers have finished. This probably means that a worker crashed and 1 tests were missed. (RuntimeError)
```

### System configuration
**Rails version**: `6.0.0`

**Ruby version**: `2.6.0p0`

### Note
Related issues found online and pretty recent:
1. [StackOverflow](https://stackoverflow.com/questions/57863565/running-rails-test-is-throwing-bad-file-descriptor-errnoebadf-error)
2. [Qiita](https://qiita.com/amatsukix/items/08fba074dbdf08551c72)
3. [Qiita 2](https://qiita.com/miyashiiii/items/60139ca3319c20bb1d29)

**Comment by chrismaltais** [comment]
After some digging, it seems like the issue here is with parallelized testing. 
It works if we edit `/test/test_helper.rb`:
```ruby 
ENV['RAILS_ENV'] ||= 'test'
require_relative '../config/environment'
require 'rails/test_help'

class ActiveSupport::TestCase
  # Run tests in parallel with specified workers
  # OLD: parallelize(workers: :number_of_processors)  <--
  parallelize(workers: 1)
  # OR just comment the line above out completely <--

  # Setup all fixtures in test/fixtures/*.yml for all tests in alphabetical order.
  fixtures :all

  # Add more helper methods to be used by all tests here...
end
```

When looking for answers I found [this question asking about breakpoint functionality with `byebug` and multiple processes](https://github.com/rails/rails/pull/31900#issuecomment-363952083). It was answered [here with regards to threads... but not forked processes](https://github.com/rails/rails/pull/31900#issuecomment-364241326)

### Follow-up
1. When I add more tests, if I run the program with `parallelize(workers: 2)` it will **always** throw the error in the issue. 

**It seems there is an intuitive hurdle in the ability to run tests in parallel and continue to use `byebug`.** Are there any docs available for this?

**Comment by eileencodes** [comment]
I don't think there's a solution for this. Rails / parallel tests can't know that you set a byebug breakpoint before we hit it. We wouldn't be able to ignore a byebug/pry breakpoint without doing an ugly hack to override methods in those gems. If you need byebug / pry running with an entire suite or test file it may break before you need it anyway so I don't think it makes sense for us to pursue a fix.

Would you like to open a PR documenting that byebug/pry are unsupported? I think that's the best we can do other than turn off parallelization for local tests.

**Comment by talpava** [comment]
Я упоминал до зтого, я просматриваю разные версии потому что пропали мои деньги,( число и время на чеке далее) это был обмен" рубли --втс" сразу! , не более 2секунд как я получил втс  произошёл сбой по связи с интернетом,Бельше на ту страницу мне не попастьхотя  странно есо говорилось что номен кошелька один постоянный! А у меня другой номерстал , куда и почему пропали деньги!!!!!!!!!!!!!!!20:07, 22 сентября 2019 г., "Eileen M. Uchitelle" <notifications@github.com>:I don't think there's a solution for this. Rails / parallel tests can't know that you set a byebug breakpoint before we hit it. We wouldn't be able to ignore a byebug/pry breakpoint without doing an ugly hack to override methods in those gems. If you need byebug / pry running with an entire suite or test file it may break before you need it anyway so I don't think it makes sense for us to pursue a fix.
Would you like to open a PR documenting that byebug/pry are unsupported? I think that's the best we can do other than turn off parallelization for local tests.

—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or mute the thread.
Отправлено из мобильной Яндекс.Почты: http://yandex

**Comment by chrismaltais** [comment]
Thanks for the input, I'll put up a PR to update the documentation in the next couple of days.

**Comment by ahoglund** [comment]
I don't believe this is an issue directly with introducing a breakpoint into parallelized tests.  I've run across this same `Bad file descriptor (Errno::EBADF)` issue when running both the full test suite or an individual test file.  

I've only ever encountered this in local development on MacOS.  Even running the suite in a linux Docker env "fixes" the issue locally.  Not sure if that is really important, as I've not exhaustively testing platforms.

It seems that the parent ruby process is having an issue peforming the `fork` here:

https://github.com/rails/rails/blob/804a4c144e5d800e5937c022d456994fe8803f0f/activesupport/lib/active_support/testing/parallelization.rb#L77-L116

Dropping a `rescue Errno::EBADF` after line 102 will make the error "go away", of course the test suite still fails with `Queue not empty, but all workers have finished.` though.

One thing I've noticed is that `spring` is definitely involved in causing this error.  For example, if I

1. `rm bin/spring`
2. `pkill -9 -f spring`
3. `bin/rails test` (with `parallelize(workers: :number_of_processors)`)

This will essentially "fix" the issue, and i'm able to run the test suite successfully. I still haven't dug into _why_ spring is causing this though...

**Comment by eileencodes** [comment]
> One thing I've noticed is that spring is definitely involved in causing this error

Oh yea I do not recommend using spring with parallel tests.

**Comment by ahoglund** [comment]
> I do not recommend using spring with parallel tests.

Ah ok.  What is the recommended way to run parallel tests?  `bin/rake test`,  `bin/rails test` and `bundle exec [rails|rake] test`  will use spring by default.

**Comment by moray95** [comment]
I am seeing the same issue, and able to consistently reproduce it without using any breakpoint:

```
$ rails new project-foobar  --api
      create  
      create  README.md
      create  Rakefile
      create  .ruby-version
      create  config.ru
      create  .gitignore
      create  Gemfile
         run  git init from "."
Initialized empty Git repository in /private/tmp/project-foobar/.git/
      create  app
      create  app/assets/config/manifest.js
      create  app/assets/stylesheets/application.css
      create  app/channels/application_cable/channel.rb
      create  app/channels/application_cable/connection.rb
      create  app/controllers/application_controller.rb
      create  app/helpers/application_helper.rb
      create  app/javascript/channels/consumer.js
      create  app/javascript/channels/index.js
      create  app/javascript/packs/application.js
      create  app/jobs/application_job.rb
      create  app/mailers/application_mailer.rb
      create  app/models/application_record.rb
      create  app/views/layouts/application.html.erb
      create  app/views/layouts/mailer.html.erb
      create  app/views/layouts/mailer.text.erb
      create  app/assets/images/.keep
      create  app/controllers/concerns/.keep
      create  app/models/concerns/.keep
      create  bin
      create  bin/rails
      create  bin/rake
      create  bin/setup
      create  bin/yarn
      create  config
      create  config/routes.rb
      create  config/application.rb
      create  config/environment.rb
      create  config/cable.yml
      create  config/puma.rb
      create  config/spring.rb
      create  config/storage.yml
      create  config/environments
      create  config/environments/development.rb
      create  config/environments/production.rb
      create  config/environments/test.rb
      create  config/initializers
      create  config/initializers/application_controller_renderer.rb
      create  config/initializers/assets.rb
      create  config/initializers/backtrace_silencers.rb
      create  config/initializers/content_security_policy.rb
      create  config/initializers/cookies_serializer.rb
      create  config/initializers/cors.rb
      create  config/initializers/filter_parameter_logging.rb
      create  config/initializers/inflections.rb
      create  config/initializers/mime_types.rb
      create  config/initializers/new_framework_defaults_6_0.rb
      create  config/initializers/wrap_parameters.rb
      create  config/locales
      create  config/locales/en.yml
      create  config/master.key
      append  .gitignore
      create  config/boot.rb
      create  config/database.yml
      create  db
      create  db/seeds.rb
      create  lib
      create  lib/tasks
      create  lib/tasks/.keep
      create  lib/assets
      create  lib/assets/.keep
      create  log
      create  log/.keep
      create  public
      create  public/404.html
      create  public/422.html
      create  public/500.html
      create  public/apple-touch-icon-precomposed.png
      create  public/apple-touch-icon.png
      create  public/favicon.ico
      create  public/robots.txt
      create  tmp
      create  tmp/.keep
      create  tmp/pids
      create  tmp/pids/.keep
      create  tmp/cache
      create  tmp/cache/assets
      create  vendor
      create  vendor/.keep
      create  test/fixtures
      create  test/fixtures/.keep
      create  test/fixtures/files
      create  test/fixtures/files/.keep
      create  test/controllers
      create  test/controllers/.keep
      create  test/mailers
      create  test/mailers/.keep
      create  test/models
      create  test/models/.keep
      create  test/helpers
      create  test/helpers/.keep
      create  test/integration
      create  test/integration/.keep
      create  test/channels/application_cable/connection_test.rb
      create  test/test_helper.rb
      create  storage
      create  storage/.keep
      create  tmp/storage
      create  tmp/storage/.keep
      remove  app/assets
      remove  lib/assets
      remove  tmp/cache/assets
      remove  app/helpers
      remove  test/helpers
      remove  app/views/layouts/application.html.erb
      remove  public/404.html
      remove  public/422.html
      remove  public/500.html
      remove  public/apple-touch-icon-precomposed.png
      remove  public/apple-touch-icon.png
      remove  public/favicon.ico
      remove  app/javascript
      remove  config/initializers/assets.rb
      remove  config/initializers/cookies_serializer.rb
      remove  config/initializers/content_security_policy.rb
      remove  config/initializers/new_framework_defaults_6_0.rb
      remove  bin/yarn
         run  bundle install
The dependency tzinfo-data (>= 0) will be unused by any of the platforms Bundler is installing for. Bundler is installing for x86_64-darwin-19, ruby but the dependency is only for x86-mingw32, x86-mswin32, x64-mingw32, java. To add those platforms to the bundle, run `bundle lock --add-platform x86-mingw32 x86-mswin32 x64-mingw32 java`.
Ignoring ruby-debug-ide-0.7.0.beta7 because its extensions are not built. Try: gem pristine ruby-debug-ide --version 0.7.0.beta7

$ cd project-foobar 
$ rails test
Run options: --seed 28850

# Running:

/private/tmp/project-foobar/db/schema.rb doesn't exist yet. Run `rails db:migrate` to create it, then try again. If you do not intend to use a database, you should instead alter /private/tmp/project-foobar/config/application.rb to limit the frameworks that will be loaded.
/private/tmp/project-foobar/db/schema.rb doesn't exist yet. Run `rails db:migrate` to create it, then try again. If you do not intend to use a database, you should instead alter /private/tmp/project-foobar/config/application.rb to limit the frameworks that will be loaded.
/private/tmp/project-foobar/db/schema.rb doesn't exist yet. Run `rails db:migrate` to create it, then try again. If you do not intend to use a database, you should instead alter /private/tmp/project-foobar/config/application.rb to limit the frameworks that will be loaded.
/private/tmp/project-foobar/db/schema.rb doesn't exist yet. Run `rails db:migrate` to create it, then try again. If you do not intend to use a database, you should instead alter /private/tmp/project-foobar/config/application.rb to limit the frameworks that will be loaded.
Traceback (most recent call last):
	2: from /private/tmp/project-foobar/vendor/bundle/ruby/2.6.0/gems/minitest-5.13.0/lib/minitest.rb:68:in `block in autorun'
	1: from /private/tmp/project-foobar/vendor/bundle/ruby/2.6.0/gems/minitest-5.13.0/lib/minitest.rb:145:in `run'
/private/tmp/project-foobar/vendor/bundle/ruby/2.6.0/gems/activesupport-6.0.1/lib/active_support/testing/parallelization.rb:118:in `shutdown': Queue not empty, but all workers have finished. This probably means that a worker crashed and 4 tests were missed. (RuntimeError)
```

Ruby version: 2.6.5
Rails version: 6.0.1

**Comment by moray95** [comment]
Btw I'm not sure if this is related to spring. I'm getting the same issue when I add `--skip-spring` to `rails new`.

**Comment by andre-lgf** [comment]
> 
> 
> I am seeing the same issue, and able to consistently reproduce it without using any breakpoint:
> 
> ```
> $ rails new project-foobar  --api
>       create  
>       create  README.md
>       create  Rakefile
>       create  .ruby-version
>       create  config.ru
>       create  .gitignore
>       create  Gemfile
>          run  git init from "."
> Initialized empty Git repository in /private/tmp/project-foobar/.git/
>       create  app
>       create  app/assets/config/manifest.js
>       create  app/assets/stylesheets/application.css
>       create  app/channels/application_cable/channel.rb
>       create  app/channels/application_cable/connection.rb
>       create  app/controllers/application_controller.rb
>       create  app/helpers/application_helper.rb
>       create  app/javascript/channels/consumer.js
>       create  app/javascript/channels/index.js
>       create  app/javascript/packs/application.js
>       create  app/jobs/application_job.rb
>       create  app/mailers/application_mailer.rb
>       create  app/models/application_record.rb
>       create  app/views/layouts/application.html.erb
>       create  app/views/layouts/mailer.html.erb
>       create  app/views/layouts/mailer.text.erb
>       create  app/assets/images/.keep
>       create  app/controllers/concerns/.keep
>       create  app/models/concerns/.keep
>       create  bin
>       create  bin/rails
>       create  bin/rake
>       create  bin/setup
>       create  bin/yarn
>       create  config
>       create  config/routes.rb
>       create  config/application.rb
>       create  config/environment.rb
>       create  config/cable.yml
>       create  config/puma.rb
>       create  config/spring.rb
>       create  config/storage.yml
>       create  config/environments
>       create  config/environments/development.rb
>       create  config/environments/production.rb
>       create  config/environments/test.rb
>       create  config/initializers
>       create  config/initializers/application_controller_renderer.rb
>       create  config/initializers/assets.rb
>       create  config/initializers/backtrace_silencers.rb
>       create  config/initializers/content_security_policy.rb
>       create  config/initializers/cookies_serializer.rb
>       create  config/initializers/cors.rb
>       create  config/initializers/filter_parameter_logging.rb
>       create  config/initializers/inflections.rb
>       create  config/initializers/mime_types.rb
>       create  config/initializers/new_framework_defaults_6_0.rb
>       create  config/initializers/wrap_parameters.rb
>       create  config/locales
>       create  config/locales/en.yml
>       create  config/master.key
>       append  .gitignore
>       create  config/boot.rb
>       create  config/database.yml
>       create  db
>       create  db/seeds.rb
>       create  lib
>       create  lib/tasks
>       create  lib/tasks/.keep
>       create  lib/assets
>       create  lib/assets/.keep
>       create  log
>       create  log/.keep
>       create  public
>       create  public/404.html
>       create  public/422.html
>       create  public/500.html
>       create  public/apple-touch-icon-precomposed.png
>       create  public/apple-touch-icon.png
>       create  public/favicon.ico
>       create  public/robots.txt
>       create  tmp
>       create  tmp/.keep
>       create  tmp/pids
>       create  tmp/pids/.keep
>       create  tmp/cache
>       create  tmp/cache/assets
>       create  vendor
>       create  vendor/.keep
>       create  test/fixtures
>       create  test/fixtures/.keep
>       create  test/fixtures/files
>       create  test/fixtures/files/.keep
>       create  test/controllers
>       create  test/controllers/.keep
>       create  test/mailers
>       create  test/mailers/.keep
>       create  test/models
>       create  test/models/.keep
>       create  test/helpers
>       create  test/helpers/.keep
>       create  test/integration
>       create  test/integration/.keep
>       create  test/channels/application_cable/connection_test.rb
>       create  test/test_helper.rb
>       create  storage
>       create  storage/.keep
>       create  tmp/storage
>       create  tmp/storage/.keep
>       remove  app/assets
>       remove  lib/assets
>       remove  tmp/cache/assets
>       remove  app/helpers
>       remove  test/helpers
>       remove  app/views/layouts/application.html.erb
>       remove  public/404.html
>       remove  public/422.html
>       remove  public/500.html
>       remove  public/apple-touch-icon-precomposed.png
>       remove  public/apple-touch-icon.png
>       remove  public/favicon.ico
>       remove  app/javascript
>       remove  config/initializers/assets.rb
>       remove  config/initializers/cookies_serializer.rb
>       remove  config/initializers/content_security_policy.rb
>       remove  config/initializers/new_framework_defaults_6_0.rb
>       remove  bin/yarn
>          run  bundle install
> The dependency tzinfo-data (>= 0) will be unused by any of the platforms Bundler is installing for. Bundler is installing for x86_64-darwin-19, ruby but the dependency is only for x86-mingw32, x86-mswin32, x64-mingw32, java. To add those platforms to the bundle, run `bundle lock --add-platform x86-mingw32 x86-mswin32 x64-mingw32 java`.
> Ignoring ruby-debug-ide-0.7.0.beta7 because its extensions are not built. Try: gem pristine ruby-debug-ide --version 0.7.0.beta7
> 
> $ cd project-foobar 
> $ rails test
> Run options: --seed 28850
> 
> # Running:
> 
> /private/tmp/project-foobar/db/schema.rb doesn't exist yet. Run `rails db:migrate` to create it, then try again. If you do not intend to use a database, you should instead alter /private/tmp/project-foobar/config/application.rb to limit the frameworks that will be loaded.
> /private/tmp/project-foobar/db/schema.rb doesn't exist yet. Run `rails db:migrate` to create it, then try again. If you do not intend to use a database, you should instead alter /private/tmp/project-foobar/config/application.rb to limit the frameworks that will be loaded.
> /private/tmp/project-foobar/db/schema.rb doesn't exist yet. Run `rails db:migrate` to create it, then try again. If you do not intend to use a database, you should instead alter /private/tmp/project-foobar/config/application.rb to limit the frameworks that will be loaded.
> /private/tmp/project-foobar/db/schema.rb doesn't exist yet. Run `rails db:migrate` to create it, then try again. If you do not intend to use a database, you should instead alter /private/tmp/project-foobar/config/application.rb to limit the frameworks that will be loaded.
> Traceback (most recent call last):
> 	2: from /private/tmp/project-foobar/vendor/bundle/ruby/2.6.0/gems/minitest-5.13.0/lib/minitest.rb:68:in `block in autorun'
> 	1: from /private/tmp/project-foobar/vendor/bundle/ruby/2.6.0/gems/minitest-5.13.0/lib/minitest.rb:145:in `run'
> /private/tmp/project-foobar/vendor/bundle/ruby/2.6.0/gems/activesupport-6.0.1/lib/active_support/testing/parallelization.rb:118:in `shutdown': Queue not empty, but all workers have finished. This probably means that a worker crashed and 4 tests were missed. (RuntimeError)
> ```
> 
> Ruby version: 2.6.5p114
> Rails version: 6.0.1

According to the given error message, you forgot to run the `rails db:migrate` command to create the development and test databases and perform the pending migrations before running the tests:

**/private/tmp/project-foobar/db/schema.rb doesn't exist yet. Run `rails db:migrate` to create it, then try again. If you do not intend to use a database, you should instead alter /private/tmp/project-foobar/config/application.rb to limit the frameworks that will be loaded.**

**Comment by moray95** [comment]
> According to the given error message, you forgot to run the rails db:migrate command to create the development and test databases and perform the pending migrations before running the tests

True, but tbh I don't think it's a valid reason for rails to crash in such a way. Btw running the migrations did in fact fix the issue for this case. I am still seeing the issue on a real project though, but I'm not sure on how to reproduce it in a sample project.

**Comment by blackpond** [comment]
Spring is causing my parallel tests to crash as well.  I'm also getting multiple databases created 

app_name_test
app_name_test-0
app_name_test-1
app_name_test-2
app_name_test-3
app_name_test-4
app_name_test-5

When I remove Spring everything works.  Odd that parallel tests and Spring are both defaults if they are not compatible.

**Comment by blackpond** [comment]
```
Finished in 0.623262s, 3.2089 runs/s, 0.0000 assertions/s.
2 runs, 0 assertions, 0 failures, 2 errors, 0 skips
andrew@3ABM584 dispatch2 % rails test
Running via Spring preloader in process 23031
Run options: --seed 53887

# Running:

Traceback (most recent call last):
	28: from -e:1:in `<main>'
	27: from /Users/andrew/.rvm/rubies/ruby-2.6.5/lib/ruby/site_ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	26: from /Users/andrew/.rvm/rubies/ruby-2.6.5/lib/ruby/site_ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	25: from /Users/andrew/.rvm/gems/ruby-2.6.5/gems/spring-2.1.0/lib/spring/application/boot.rb:19:in `<top (required)>'
	24: from /Users/andrew/.rvm/gems/ruby-2.6.5/gems/spring-2.1.0/lib/spring/application.rb:139:in `run'
	23: from /Users/andrew/.rvm/gems/ruby-2.6.5/gems/spring-2.1.0/lib/spring/application.rb:139:in `loop'
	22: from /Users/andrew/.rvm/gems/ruby-2.6.5/gems/spring-2.1.0/lib/spring/application.rb:145:in `block in run'
	21: from /Users/andrew/.rvm/gems/ruby-2.6.5/gems/spring-2.1.0/lib/spring/application.rb:175:in `serve'
	20: from /Users/andrew/.rvm/gems/ruby-2.6.5/gems/spring-2.1.0/lib/spring/application.rb:175:in `fork'
	19: from /Users/andrew/.rvm/gems/ruby-2.6.5/gems/minitTraceback (most recent call last):
est-5.14.0/lib/minitest.rb:68:in `block in autorun'
	18: from /Users/andrew/.rvm/gems/ruby-2.6.5/gems/minitest-5.14.0/lib/minitest.rb:138:in `run'
	17: from /Users/andrew/.rvm/gems/ruby-2.6.5/gems/activesupport-6.0.2.1/lib/active_support/testing/parallelization.rb:74:in `start'
	28: from -e:1:in `<main>'
	27: from /Users/andrew/.rvm/rubies/ruby-2.6.5/lib/ruby/site_ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	16: from /Users/andrew/.rvm/gems/ruby-2.6.5/gems/activesupport-6.0.2.1/lib/active_support/testing/parallelization.rb:74:in `map'
	26: from /Users/andrew/.rvm/rubies/ruby-2.6.5/lib/ruby/site_ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	15: from /Users/andrew/.rvm/gems/ruby-2.6.5/gems/activesupport-6.0.2.1/lib/active_support/testing/parallelization.rb:74:in `each'
	25: from /Users/andrew/.rvm/gems/ruby-2.6.5/gems/spring-2.1.0/lib/spring/application/boot.rb:19:in `<top (required)>'
	14: from /Users/andrew/.rvm/gems/ruby-2.6.5/gems/activesupport-6.0.2.1/lib/active_support/testing/parallelization.rb:74:in `times'
	24: from /Users/andrew/.rvm/gems/ruby-2.6.5/gems/spring-2.1.0/lib/spring/application.rb:139:in `run'
	13: from /Users/andrew/.rvm/gems/ruby-2.6.5/gems/activesupport-6.0.2.1/lib/active_support/testing/parallelization.rb:75:in `block in start'
	23: from /Users/andrew/.rvm/gems/ruby-2.6.5/gems/spring-2.1.0/lib/spring/application.rb:139:in `loop'
	12: from /Users/andrew/.rvm/gems/ruby-2.6.5/gems/activesupport-6.0.2.1/lib/active_support/testing/parallelization.rb:75:in `fork'
	22: from /Users/andrew/.rvm/gems/ruby-2.6.5/gems/spring-2.1.0/lib/spring/application.rb:145:in `block in run'
	11: from /Users/andrew/.rvm/gems/ruby-2.6.5/gems/activesupport-6.0.2.1/lib/active_support/testing/parallelization.rb:95:in `block (2 levels) in start'
	21: from /Users/andrew/.rvm/gems/ruby-2.6.5/gems/spring-2.1.0/lib/spring/application.rb:175:in `serve'
	10: from /Users/andrew/.rvm/rubies/ruby-2.6.5/lib/ruby/2.6.0/drb/drb.rb:1138:in `method_missing'
	20: from /Users/andrew/.rvm/gems/ruby-2.6.5/gems/spring-2.1.0/lib/spring/application.rb:175:in `fork'
	 9: from /Users/andrew/.rvm/rubies/ruby-2.6.5/lib/ruby/2.6.0/drb/drb.rb:1158:in `with_friend'
	19: from /Users/andrew/.rvm/gems/ruby-2.6.5/gems/minitest-5.14.0/lib/minitest.rb:68:in `block in autorun'
	 8: from /Users/andrew/.rvm/rubies/ruby-2.6.5/lib/ruby/2.6.0/drb/drb.rb:1139:in `block in method_missing'
	18: from /Users/andrew/.rvm/gems/ruby-2.6.5/gems/minitest-5.14.0/lib/minitest.rb:138:in `run'
	 7: from /Users/andrew/.rvm/rubies/ruby-2.6.5/lib/ruby/2.6.0/drb/drb.rb:1213:in `open'
	17: from /Users/andrew/.rvm/gems/ruby-2.6.5/gems/activesupport-6.0.2.1/lib/active_support/testing/parallelization.rb:74:in `start'
	 6: from /Users/andrew/.rvm/rubies/ruby-2.6.5/lib/ruby/2.6.0/drb/drb.rb:1213:in `synchronize'
	16: from /Users/andrew/.rvm/gems/ruby-2.6.5/gems/activesupport-6.0.2.1/lib/active_support/testing/parallelization.rb:74:in `map'
	 5: from /Users/andrew/.rvm/rubies/ruby-2.6.5/lib/ruby/2.6.0/drb/drb.rb:1216:in `block in open'
	15: from /Users/andrew/.rvm/gems/ruby-2.6.5/gems/activesupport-6.0.2.1/lib/active_support/testing/parallelization.rb:74:in `each'
	 4: from /Users/andrew/.rvm/rubies/ruby-2.6.5/lib/ruby/2.6.0/drb/drb.rb:1216:in `each'
	14: from /Users/andrew/.rvm/gems/ruby-2.6.5/gems/activesupport-6.0.2.1/lib/active_support/testing/parallelization.rb:74:in `times'
	13: from /Users/andrew/.rvm/gems/ruby-2.6.5/gems/activesupport-6.0.2.1/lib/active_support/testing/parallelization.rb:75:in `block in start'
	 3: from /Users/andrew/.rvm/rubies/ruby-2.6.5/lib/ruby/2.6.0/drb/drb.rb:1218:in `block (2 levels) in open'
	12: from /Users/andrew/.rvm/gems/ruby-2.6.5/gems/activesupport-6.0.2.1/lib/active_support/testing/parallelization.rb:75:in `fork'
	 2: from /Users/andrew/.rvm/rubies/ruby-2.6.5/lib/ruby/2.6.0/drb/drb.rb:1262:in `alive?'
	11: from /Users/andrew/.rvm/gems/ruby-2.6.5/gems/activesupport-6.0.2.1/lib/active_support/testing/parallelization.rb:95:in `block (2 levels) in start'
	 1: from /Users/andrew/.rvm/rubies/ruby-2.6.5/lib/ruby/2.6.0/drb/drb.rb:1005:in `alive?'
	10: from /Users/andrew/.rvm/rubies/ruby-2.6.5/lib/ruby/2.6.0/drb/drb.rb:1138:in `method_missing'
/Users/andrew/.rvm/rubies/ruby-2.6.5/lib/ruby/2.6.0/drb/drb.rb:1005:in `wait_readable': 	 9: from /Users/andrew/.rvm/rubies/ruby-2.6.5/lib/ruby/2.6.0/drb/drb.rb:1158:in `with_friend'
	 8: from /Users/andrew/.rvm/rubies/ruby-2.6.5/lib/ruby/2.6.0/drb/drb.rb:1139:in `block in method_missing'
Bad file descriptor (	 7: from /Users/andrew/.rvm/rubies/ruby-2.6.5/lib/ruby/2.6.0/drb/drb.rb:1213:in `open'
Errno::EBADF	 6: from /Users/andrew/.rvm/rubies/ruby-2.6.5/lib/ruby/2.6.0/drb/drb.rb:1213:in `synchronize'
	 5: from /Users/andrew/.rvm/rubies/ruby-2.6.5/lib/ruby/2.6.0/drb/drb.rb:1216:in `block in open'
)	 4: from /Users/andrew/.rvm/rubies/ruby-2.6.5/lib/ruby/2.6.0/drb/drb.rb:1216:in `each'

	 3: from /Users/andrew/.rvm/rubies/ruby-2.6.5/lib/ruby/2.6.0/drb/drb.rb:1218:in `block (2 levels) in open'
	 2: from /Users/andrew/.rvm/rubies/ruby-2.6.5/lib/ruby/2.6.0/drb/drb.rb:1262:in `alive?'
	 1: from /Users/andrew/.rvm/rubies/ruby-2.6.5/lib/ruby/2.6.0/drb/drb.rb:1005:in `alive?'
/Users/andrew/.rvm/rubies/ruby-2.6.5/lib/ruby/2.6.0/drb/drb.rb:1005:in `wait_readable': Bad file descriptor (Errno::EBADF)
Traceback (most recent call last):
	5: from -e:1:in `<main>'
	4: from /Users/andrew/.rvm/rubies/ruby-2.6.5/lib/ruby/site_ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	3: from /Users/andrew/.rvm/rubies/ruby-2.6.5/lib/ruby/site_ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	2: from /Users/andrew/.rvm/gems/ruby-2.6.5/gems/minitest-5.14.0/lib/minitest.rb:68:in `block in autorun'
	1: from /Users/andrew/.rvm/gems/ruby-2.6.5/gems/minitest-5.14.0/lib/minitest.rb:145:in `run'
/Users/andrew/.rvm/gems/ruby-2.6.5/gems/activesupport-6.0.2.1/lib/active_support/testing/parallelization.rb:118:in `shutdown': Queue not empty, but all workers have finished. This probably means that a worker crashed and 2 tests were missed. (RuntimeError)
```

**Comment by mikesvystun** [comment]
Check your fixtures. If it's a new app, your fixtures probably look like this 

```
#one: {}
#two: {}
```

Commenting one of them out should fix the issue with Parallel testing.

**Comment by tdak** [comment]
I've come across this error a number of times now. Today's is the most recent one. 

Two things I noticed, about 2 hours prior to the error, I was getting too many files open exception. This happened randomly when I was browsing the app. I restarted the dev server and it was working fine. 

Second, probably not related, I ran a rake db:migrate and after that all my tests were failing to run with the above error. (I am using guard).

Reading through this thread, I decided to restart spring. My spring server had been running for 334 hours. 

I stoped spring server started it again. And all is working now.

**Comment by asadakbar** [comment]
When I read your note I thought you were referring to having too many files open. I closed all my open files in vscode and restarted the console and ran the method where byebug was being hit and lo and behold no more error. 

I realize now that you were referring to the actual exception itself, and not the context of having too many files open, but regardless, somehow closing my open files worked.

> I've come across this error a number of times now. Today's is the most recent one.
> 
> Two things I noticed, about 2 hours prior to the error, I was getting too many files open exception. This happened randomly when I was browsing the app. I restarted the dev server and it was working fine.
