### ISSUE TITLE
Unable to compile assets when Rails.credentials are used during app load

### ISSUE THREAD

**Issue by jmadkins** [rails/rails#37202]
My issue is that a `NoMethodError: undefined method '[]' for nil:NilClass` is being thrown whenever the credentials are accessed during Rails loading. 

For my first workaround, I followed this [suggestion](https://medium.com/@kaygeee/avoid-getting-a-nomethoderror-undefined-method-for-nil-nilclass-by-doing-c8925f7623cd) and accessed credentials via the `dig` method. 

This worked but several gems then complained about empty strings for the values that should have been set from the credentials. As a workaround, I'm now building assets in my Dockerfile by running `RUN ASSETS_PRECOMPILE=1 SECRET_KEY_BASE=1 RAILS_ENV=production bundle exec rake assets:precompile`. Then, in every initializer that uses a credential I added `return if ENV['ASSETS_PRECOMPILE'].present?`

I wasn't able to deploy my app for a week until I got this issue taken care of using a hack. This needs more attention.

_Originally posted by @jmadkins in https://github.com/rails/rails/issues/32947#issuecomment-531508722_

**Comment by andrewjaanuu** [comment]
+1
