### ISSUE TITLE
Redis cache store should raise an error if it cannot connect to Redis

### ISSUE THREAD

**Issue by collimarco** [rails/rails#37205]
### Steps to reproduce

Suppose that you have the following line in the production environment:

```
config.cache_store = :redis_cache_store, { url: "redis://192.168.0.10:6379/0" }
```

If the url is incorrect and the connection fails, Rails should raise an exception.

In the last week we moved some servers to a new datacenter and the url was no longer valid. The result was that Puma took a long time (90s) to restart, empty migrations took a long time to run (90s), etc. We couldn't really figure out what was causing that. After several hours of investigation we found that the issue was in the above line, which caused the boot to hang for a long time. Raising an exception would have saved our day.

### Expected behavior
An exception should be raised.

Otherwise, if you want a lazy behavior, please don't try to connect during boot.

### Actual behavior
The process waits for the connection for a very long time (> 60s), then no exception is raised.

### System configuration
**Rails version**: 5.2
**Ruby version**: 2.6.4

**Comment by y-yagi** [comment]
Currently, it is intentional behavior that cache store does not raise an exception. 
But you can customize error handling(also timeout setting). Please see https://edgeguides.rubyonrails.org/caching_with_rails.html#activesupport-cache-rediscachestore for more details. Thanks.
