### ISSUE TITLE
upgrading_ruby_on_rails.md has a typo

### ISSUE THREAD

**Issue by jlhg** [rails/rails#37219]
https://github.com/rails/rails/blob/a1b6c1669fc99e20439d6a8cada36392c82c48a8/guides/source/upgrading_ruby_on_rails.md#active-storage-assignment-behavior-change

```
user.higlights.count # => 1
```

Should be 

```
user.highlights.count # => 1
```

**Comment by kamipo** [comment]
Thanks for the report. Fixed by fba75f0ae332636cb46a97474bf682c442b6ee2b.
