### ISSUE TITLE
Resume file upload when Internet connection is back

### ISSUE THREAD

**Issue by iamabhyas** [rails/rails#37220]
https://stackoverflow.com/questions/57968817/resume-file-upload-when-internet-connection-is-back

I have a requirement in a ROR project where I need to resume file upload when Internet Connection is back.

My understanding is we can resume file upload only if we are transferring a file chunk by chunk. So I explored this library (https://fineuploader.com/) which supports file upload in chunks.

Now I need to handle it at server side, for which as of now I am clueless. I have found many server-side examples where Fine Uploader library(https://github.com/FineUploader/server-examples) is used. For Rails there are two methods (https://github.com/FineUploader/server-examples/wiki/Rails---CarrierWave) - (Method A) Use hacked StringIO -(Method B) Use rack-raw-upload middleware

However none of it is supporting file upload in chunks. Please suggest

**Comment by dmitry** [comment]
@iamabhyas I strongly recommand to use shrine as it has great modular system, it supports almost everything you can imagine for file uploads, and for sure you can use resumable uploads with it. Check out this tutorial: https://github.com/shrinerb/shrine/wiki/Adding-Resumable-Uploads

It's using https://github.com/janko/tus-ruby-server which could be mounted in rails routes.

**Comment by kaspth** [comment]
We reserve the issues tracker for bugs, thanks. Active Storage is Rails’ built in answer for file uploads, but you’re welcome to use (or help improve) whatever you like. ✌️

**Comment by iamabhyas** [comment]
@dm1try @kaspth Thanks for the advice.
