### ISSUE TITLE
Cannot attach a PDF while keeping HTML body

### ISSUE THREAD

**Issue by altjx** [rails/rails#37233]
**Steps to reproduce**

When sending an email that contains a PDF attachment, the body of the email is automatically converted to plaintext. If you specify a "content-type" of "text/html" within the body, then the PDF attachment is inserted and included within the HTML body of the email.

**Expected Behavior**

When sending an email that has HTML body, and including an attachment, the expected behavior is for the body of the email to be HTML and the attachment to **not** be included within the body, but as an attachment instead.

**Actual Behavior**

The body contains both the HTML as well as the PDF attachment.

**System Configuration**

Rails 5.2.3

**Other**

Here's is my mailer code:

```
class QuickMailerMailer < ApplicationMailer
	def send_mail(smtp_settings, mail_options, attachment=nil)
		unless attachment.nil?
			attachments[attachment[0]] = File.read(attachment[1])
		end
		mail(from: mail_options[:from],
			to: mail_options[:to],
			subject: mail_options[:subject],
			body: "Hello World"
			)
	end
end
```

According to https://guides.rubyonrails.org/action_mailer_basics.html#complete-list-of-action-mailer-methods, it specifically states:

> When the mail method will be triggered, it will send a multipart email with an attachment, properly nested with the top level being multipart/mixed and the first part being a multipart/alternative containing the plain text and HTML email messages.

However, it actually does NOT include HTML messages when including an attachment.

The only two options that I am able to see when including an attachment are:

1. The attachment is included within the body of the email and the body of the email is rendered as HTML.
2. The attachment is included as a normal attachment, but the body of the email is forced as plaintext.

**Comment by JohnSmall** [comment]
I can get this to work when I sent an *.xslx file. We send out weekly price lists as HTML for viewing in a browser, with an Excel spreadsheet attached. So that works. I wonder if the problem is specific to pdfs. I'll try sending a pdf and see what happens.
