### ISSUE TITLE
Unexpected behavior from CollectionProxy when target is "partially loaded"

### ISSUE THREAD

**Issue by staii** [rails/rails#37239]
### Steps to reproduce
From a fresh Rails app, setup with:
```
rails g scaffold Parent name:string
rails g scaffold Child name:string parent:references
echo "class Parent < ApplicationRecord; has_many :childs, autosave: true; end" > ./app/models/parent.rb
rails db:migrate
rails runner 'p = Parent.create!(name: "parent"); c1 = Child.create!(parent: p, name: "child1"); c2 = Child.create!(parent: p, name: "child2")'
```
Then try the following in `rails c`:
```
p = Parent.first
c = p.childs.first
c.name += "extra"
p.save! # It's a no-op.
```

### Expected behavior
`p` should save `c` since `autosave: true` is set on the association.

### Actual behavior
`p.save!` is a no-op.

### System configuration
**Rails version**: Rails 5.2.3
**Ruby version**: ruby 2.5.3p105 (2018-10-18 revision 65156) [x86_64-linux]

### Digging a little deeper

Notice that if instead the target of the association is loaded before `c` is set, the behavior is as expected:
```
p = Parent.first
p.childs.load_target
c = p.childs.first
c.name += "extra"
p.save! # Saves the child.
```

The underlying problem is that `CollectionProxy` does not _remember_ it gave out a reference to the last element, and then when `p.save!` is called, it checks if any of the associated `childs` is `changed?`, but none is since the changed object isn't any of the loaded targets (i.e. `c.object_id.in?(p.childs.map(&:object_id))` is false).

**Comment by carlosantoniodasilva** [comment]
Thanks for the steps. I believe this is related to the fact that calling `first` or `last` on an association doesn't actually load it, but simply queries for the first/last records, as you can see:

```ruby
>> p = Parent.first
   (1.5ms)  SELECT sqlite_version(*)
  Parent Load (0.2ms)  SELECT "parents".* FROM "parents" ORDER BY "parents"."id" ASC LIMIT ?  [["LIMIT", 1]]
=> #<Parent id: 1, name: "parent", created_at: "2019-09-19 23:58:01", updated_at: "2019-09-19 23:58:01">
>> c = p.childs.first
  Child Load (0.1ms)  SELECT "children".* FROM "children" WHERE "children"."parent_id" = ? ORDER BY "children"."id" ASC LIMIT ?  [["parent_id", 1], ["LIMIT", 1]]
=> #<Child id: 1, name: "child1", parent_id: 1, created_at: "2019-09-19 23:58:01", updated_at: "2019-09-19 23:58:01">
>> c.name += "extra"
=> "child1extra"
>> p.save! # It's a no-op.
=> true
>> p.childs.loaded?
=> false
```

Which is why calling `load_target` in your example worked, or simply `load`:

```ruby
>> p.childs.load
  Child Load (1.0ms)  SELECT "children".* FROM "children" WHERE "children"."parent_id" = ?  [["parent_id", 1]]
=> #<ActiveRecord::Associations::CollectionProxy [#<Child id: 1, name: "child1", parent_id: 1, created_at: "2019-09-19 23:58:01", updated_at: "2019-09-19 23:58:01">, #<Child id: 2, name: "child2", parent_id: 1, created_at: "2019-09-19 23:58:01", updated_at: "2019-09-19 23:58:01">]>
>> p.childs.loaded?
=> true
>> c = p.childs.first
=> #<Child id: 1, name: "child1", parent_id: 1, created_at: "2019-09-19 23:58:01", updated_at: "2019-09-19 23:58:01">
>> c.name += "extra"
=> "child1extra"
>> p.save! # It's a no-op.
   (0.3ms)  begin transaction
  Child Update (1.0ms)  UPDATE "children" SET "name" = ?, "updated_at" = ? WHERE "children"."id" = ?  [["name", "child1extra"], ["updated_at", "2019-09-20 00:00:20.143070"], ["id", 1]]
   (1.0ms)  commit transaction
=> true
```

There's no concept of partially loading an association, by calling `first` it will grab the first record from the DB if the association isn't loaded yet. So, I'd argue this behavior is expected, since the association is not loaded, the autosave functionality is not triggered, we just need to be careful when to load it and when not to.
