### ISSUE TITLE
form_for ignoring namespace while generating form URL

### ISSUE THREAD

**Issue by Guri-ksolves** [rails/rails#37237]
### Steps to reproduce
I have two routes like
```
namespace :admin do
  resources :roles
end
scope module: :company do
  resources :roles
end
```

My controllers are:

```
class Admin::RolesController < Admin::ApplicationController
  ...
  ...
  def create
    ...
  end

  def update
    ...
  end
end

class Company::RolesController < Company::ApplicationController
  ...
  ...
  def create
    ...
  end

  def update
    ...
  end
end
```
And I have some common views for these controllers in let's say
```views/shared/roles```

When I use form_for for creating and updating a Role record from the admin/roles_controller.rb, the form_for generates a URL which always points to company/roles_controller.rb
 i.e.  ```/roles```  and  ```/roles/:id``` 
instead of  ```/admin/roles```  and  ```/admin/roles/:id```
```
<%= form_for @role do |f| %>
  ...
  ...
<% end %>
```
### Expected behavior
Form_for should generate form_url based on the namespace  ```params[:controller]```  so that we don't have to pass the namespace dynamically like ``` form_for [:namespace, resource]```
### Actual behavior
Already mentioned in steps to reproduce

### System configuration
**Rails version**:
5.2

**Ruby version**:
2.6.3

**Comment by carlosantoniodasilva** [comment]
Passing a model to `form_for` will infer the URL from the model, not from the context around the request/controller, or at least I don't think it has ever worked differently. If you want namespaced inference, you need to give it there like you said: `[:admin, @role]`.

To confirm: is this a change in behavior from a previous version of Rails (I can't seem to remember it behaving that way honestly, so I don't think it's something that changed), or more like a feature request to change that behavior?

Also, thinking the other way around, how would you have a form from the admin page that can infer the URL from the model, pointing to the main `/roles` or `/roles/:id`, if we were to apply the routing namespace in that context/scenario?

**Comment by Guri-ksolves** [comment]
Okay, thanks for the reply @carlosantoniodasilva 
I just only want to use the same form for two different controllers one from the admin namespace and the other one from the company namespace.
Currently, I am checking the current user type to dynamically pass the parameters to ``` form_for```
like for  an admin user, I am passing  ``` [:admin, @role]``` and for a normal user just ```@role```
I was wondering if this could be figured out by rails itself.

**Comment by carlosantoniodasilva** [comment]
In that case, the way you are doing might be just fine.

Alternatively, I'll assume that each controller has its own view, and from there you're rendering the form as a partial: you could pass in the form object as a local to the partial then, instead of relying on the sharing/existence of `@role`, which could make it more contained and allow you to remove the need to check for current user.

I'll consider this one close then. Thanks!
