### ISSUE TITLE
Wrong singularisation rule for "reserves"

### ISSUE THREAD

**Issue by DevelopMan** [rails/rails#37236]
### Steps to reproduce

```
rails new test_singularize
cd test_singularize/
rails c
```
Then in the rails console:
```
2.6.3 :001 > "reserves".singularize
 => "reserf"
```
The main issue is when I use the name "Reserve" as a model and then in other model I am trying to configure relation 'has_many :reserves' I have an error, because `singularize` method return wrong result. With relation it solved by specify class_name, but it will be better to fix it.

### Expected behavior
I expected see "reserve"

### Actual behavior
Singularize method of string "reserves" gave me "reserf"

### System configuration
**Rails version**: 5.2.3 as well as in 4.2.10

**Ruby version**: 2.6.3p62

My investigations of this issue gave me that the error is in the rules described here:
lib/active_support/inflections.rb
"reserves" wrongly processed by this rule `/([lr])ves$/i, '\1f')`

My English not so good to fix it by myself. Sorry, guys.

**Comment by louim** [comment]
Hey!

Inflexions are handled by ActiveSupport::Inflector. To quote the doc:

> The Rails core team has stated patches for the inflections library will not be accepted in order to avoid breaking legacy applications which may be relying on errant inflections. If you discover an incorrect inflection and require it for your application or wish to define rules for languages other than English, please correct or add them yourself (explained below).

Taken from https://api.rubyonrails.org/classes/ActiveSupport/Inflector.html#method-i-singularize

To fix the problem in your application, you would need to add to the `config/initializers/inflections.rb` the following:

```
ActiveSupport::Inflector.inflections(:en) do |inflect|
  inflect.irregular "reserve", "reserves"
end
```
You will find more details about how the inflexion rules work here: https://api.rubyonrails.org/classes/ActiveSupport/Inflector/Inflections.html#method-i-irregular

**Comment by DevelopMan** [comment]
@louim Thanks it will solve this issue!
