### ISSUE TITLE
Feature Request to support parsing msgpack parameters natively

### ISSUE THREAD

**Issue by hiradyazdan** [rails/rails#37238]
I'd like to request to support parsing MsgPack parameters along with other already available parsers (i.e. json and xml parsers).

Thanks

**Comment by y-yagi** [comment]
Please use the [Rails Core mailing list](https://groups.google.com/forum/#!forum/rubyonrails-core) for feature requests, where a wider community will be able to help you. We reserve the Rails issue tracker only for bugs in Rails. Thanks!
