### ISSUE TITLE
ActionText questions regarding n+1 queries

### ISSUE THREAD

**Issue by apauly** [rails/rails#37249]
I'm using ActionText in some new smaller projects now and the preloading mechanisms (e.g. `with_rich_text_content_and_embeds`) are not working as I'd expect them to do.

Eventhough I am calling these methods, I'm still seeing individual queries for `ActiveStorage::Blob` when rendering the rich text content as the blobs are loaded via the signed global id. Is this expected or am I just holding it wrong?

I played around with it a bit and came up with something like this:
https://gist.github.com/apauly/e732e2a63c3098d7585de26c181624cc
_(It seems there are some problems with the gists indentation when using Safari)_

I don't know the current roadmap of ActionText - however I could work on a PR if this is a desired feature.

**Comment by georgeclaghorn** [comment]
It’s expected but worth improving. See #36177.
