### ISSUE TITLE
[ActionText] Custom attribute or custom WYSIWYG

### ISSUE THREAD

**Issue by GeorgesLeYeti** [rails/rails#37271]
Hi,

I have a custom HTML formated like: 
```
<word start='10'>Hello </word>
<word start='20'>World !</word>
```
First of all I cannot change this format. 
I wanted to allow with action text the tag "word" and the attribute "start". I fianly succed to allow the tag name but not the attribute. 
I already open an issue on trix editor git repo about that : https://github.com/basecamp/trix/issues/683#issue-494571992

After I read some other issues like mine it seems the answer is : "It's not possible"

So I have 2 questions :
- Do you think it's possible to add a custom attribute ?
- If not, do you think it could be possible to choose a different WYSIWYG editor for action text ? Like Summernote, ckeditor... 
Just like in active storage where you could choose your storage solution : Local / S3 / Azure ....

This issue is really a Go/No Go issue with action text. If there no soultion then I cannot use action text.

### System configuration
**Rails version**: 6.0

**Ruby version**: 2.6.3

**Comment by surver** [comment]
I need similar. Add a div tag with specific class.

**Comment by josephecombs** [comment]
Trix is not fully featured enough and we need the ability to plug different editors into ActionText.

**Comment by KonnorRogers** [comment]
I know this is super old, but I have a RTE using https://TipTap.dev under the hood and produces ActionText compatible HTML.

https://rhino-editor.vercel.app/
