### ISSUE TITLE
Invalid method name assert_broadcasts_on in ActionCable test_case docs

### ISSUE THREAD

**Issue by fanktom** [rails/rails#37272]
Hey there,

I just stumbled over the documentation of testing broadcasting in ActionCable.

Current documentation says the method should be called `assert_broadcasts_on`.
https://github.com/rails/rails/blob/34d426b4e57aafc14d9fcca6153c359f1f478ecf/actioncable/lib/action_cable/channel/test_case.rb#L162
However, based on https://api.rubyonrails.org/v6.0.0/classes/ActionCable/Channel/TestCase/Behavior.html#method-i-assert_broadcast_on, I think it should probably be either `assert_broadcast_on` or `assert_broadcasts`.

Possible fix: Rename `assert_broadcasts_on` to `assert_broadcast_on`.

If you are interested I can make a (very) short PR ;)

**Comment by eugeneius** [comment]
>  I can make a (very) short PR

Go for it. 👍
