### ISSUE TITLE
uninitialized constant ActiveHash (NameError)

### ISSUE THREAD

**Issue by saydulk** [rails/rails#37286]
when i run sudo rails server -b 0.0.0.0
it shows /home/deploy/project/config/initializers/activerecord.rb:7:in `<top (required)>': uninitialized constant ActiveHash (NameError)

![Screenshot from 2019-09-24 13-31-51](https://user-images.githubusercontent.com/1058663/65490921-d682be80-decf-11e9-99e0-6b9398cd8471.png)

**Comment by fxn** [comment]
That is a custom initializer in your application, and `active_hash` a [3rd party gem](https://github.com/zilkey/active_hash).

Looks like a bug in the application, not in Rails.
