### ISSUE TITLE
Bigint column validates as integer 4 bytes

### ISSUE THREAD

**Issue by sunnmas** [rails/rails#37283]
Rails 5.2.3 + postgresql 11.5 + gem 'pg', '1.1.4'. My first migration:

```
class CreateTmpUsers < ActiveRecord::Migration[5.2]
  def change
    create_table(:tmp_users) do |t|
      t.integer :external_id
      ...
    end
    add_index ...
  end
end
```
second migration:

```
class MigrateToRails52 < ActiveRecord::Migration[5.2]
  def up
    change_column :tmp_users, :external_id, :bigint
...
end
```
schema.db after rails db:migrate:

```
create_table "tmp_users", force: :cascade do |t|
    t.bigint "external_id"
    ...
end
```
schema.db after rails db:schema:dump

```
create_table "tmp_users", force: :cascade do |t|
    t.bigint "external_id"
    ...
end
```
inside pgadmin I see: Type: bigint

TmpUser.inspect gives:

`TmpUser(id: integer, external_id: integer, name: strin...`
Save through ActiveRecord gives:

```
TmpUser.create external_id: 392169714724389808
message: 392169714724389808 is out of range for ActiveModel::Type::Integer with limit 4 bytes error class: ActiveModel::RangeError
```

Must be 8 bytes, but got 4 in validation

**Comment by imechemi** [comment]
I tried to reproduce this locally with the following setup:

```
Rails: 5.2.3
postgresql: 11.5 
gem 'pg', '1.1.4'
ruby 2.6.3
```

I am able to create a TmpUser with `TmpUser.create external_id: 392169714724389808`.

**Comment by kamipo** [comment]
`change_column` is an unsafe operation for running app.
Restart app or `reset_column_information` after the migration.
