### ISSUE TITLE
zeitwerk:check task reports wrong filename in gems

### ISSUE THREAD

**Issue by sbull** [rails/rails#37285]
### Steps to reproduce
Create an app at a common prefix, say `/app`. If an error is detected in zeitwerk:check in some gems, the wrong path may be reported. This was noticed in Devise https://github.com/plataformatec/devise/issues/5140

### Expected behavior
The correct path should be reported.

### Actual behavior
Part of the path (`/app`) is removed:
```
Hold on, I am eager loading the application.
expected file /usr/local/bundle/gems/devise-4.7.1mailers/devise/mailer.rb to define constant Devise::Mailer,
```
It should be `.../devise-4.7.1/app/mailers/...`

### System configuration
**Rails version**: 6.0.0

**Ruby version**: 2.6.3

**Comment by sbull** [comment]
Probably an anchor in the following line in `zeitwerk.rake` would fix it:
```ruby
     abort $&.sub(/#{Regexp.escape(Rails.root.to_s)}./, "")
```

**Comment by fxn** [comment]
Fixed and backported. Thanks!
