### ISSUE TITLE
ActiveStorage file doesn't exist in after_create and after_create_commit method

### ISSUE THREAD

**Issue by ErikDeBruijn** [rails/rails#37304]
### Steps to reproduce
When I upgrade to Rails 6.0.0 I get a ActiveStorage::FileNotFoundError when trying to access an attachment. Since #33303 it seems that people are getting the same error as I am, but reading through those threads I haven't been able to find a solution that gets things working again. Sorry if have missed something, this is my first bug report.

I have this model:
```
class CDRFile < ApplicationRecord
  has_one_attached :excel_file

  after_create_commit :create_sessions_from_xls

  def create_sessions_from_xls
    filename = ActiveStorage::Blob.service.path_for(excel_file.key)
    puts "#{filename} "+(File.exist?(filename) ? "exists": "doesn't exist")
    f = File.open(ActiveStorage::Blob.service.path_for(excel_file.key))
[... etc ...]
```
I upgrade from 5.2.2 to rails 6.0.0 (`bundle update`).
Then I do this on the `bundle exec rails console`:
```
cdr_file = CDRFile.new
cdr_file.excel_file.attach(filename: "test.xls", io: File.open(Rails.root.join("spec", "fixtures", "cdr_example.xls")))
cdr_file.save
```

Sidenote: I did try to create a single page ruby file to reproduce this, but the templates don't include activestorage and I wasn't able to figure out how to include that.

### Expected behavior
I expected that at least with switching from `after_create` to `after_create_commit` I should be able to find the path on disk that leads to an existing file, like with Rails 5.2.2:
```
   (0.2ms)  BEGIN
  CDRFile Create (0.4ms)  INSERT INTO "cdr_files" ("created_at", "updated_at") VALUES ($1, $2) RETURNING "id"  [["created_at", "2019-09-26 08:36:14.958389"], ["updated_at", "2019-09-26 08:36:14.958389"]]
  ActiveStorage::Attachment Create (0.8ms)  INSERT INTO "active_storage_attachments" ("name", "record_type", "record_id", "blob_id", "created_at") VALUES ($1, $2, $3, $4, $5) RETURNING "id"  [["name", "excel_file"], ["record_type", "CDRFile"], ["record_id", 6], ["blob_id", 6], ["created_at", "2019-09-26 08:36:14.960100"]]
  CDRFile Update (0.5ms)  UPDATE "cdr_files" SET "updated_at" = $1 WHERE "cdr_files"."id" = $2  [["updated_at", "2019-09-26 08:36:14.961709"], ["id", 6]]
   (1.0ms)  COMMIT
/path/to/my/storage/Na/9d/Na9dKgQ5vYCNzDNmigwjYE4k exists
```

### Actual behavior
Instead, after running `cdr_file.save!` I got:
```
rb(main):003:0> cdr_file.save
   (0.2ms)  BEGIN
  CDRFile Create (0.6ms)  INSERT INTO "cdr_files" ("created_at", "updated_at") VALUES ($1, $2) RETURNING "id"  [["created_at", "2019-09-26 09:11:55.055168"], ["updated_at", "2019-09-26 09:11:55.055168"]]
  ActiveStorage::Blob Load (0.7ms)  SELECT "active_storage_blobs".* FROM "active_storage_blobs" INNER JOIN "active_storage_attachments" ON "active_storage_blobs"."id" = "active_storage_attachments"."blob_id" WHERE "active_storage_attachments"."record_id" = $1 AND "active_storage_attachments"."record_type" = $2 AND "active_storage_attachments"."name" = $3 LIMIT $4  [["record_id", 9], ["record_type", "CDRFile"], ["name", "excel_file"], ["LIMIT", 1]]
  ActiveStorage::Attachment Load (0.2ms)  SELECT "active_storage_attachments".* FROM "active_storage_attachments" WHERE "active_storage_attachments"."record_id" = $1 AND "active_storage_attachments"."record_type" = $2 AND "active_storage_attachments"."name" = $3 LIMIT $4  [["record_id", 9], ["record_type", "CDRFile"], ["name", "excel_file"], ["LIMIT", 1]]
  ActiveStorage::Blob Create (0.4ms)  INSERT INTO "active_storage_blobs" ("key", "filename", "content_type", "metadata", "byte_size", "checksum", "created_at") VALUES ($1, $2, $3, $4, $5, $6, $7) RETURNING "id"  [["key", "bg6otind6q8s1t93g5zsamyxzjn2"], ["filename", "test.xls"], ["content_type", "application/vnd.ms-excel"], ["metadata", "{\"identified\":true}"], ["byte_size", 27648], ["checksum", "E7kCcan1Ry2Fwe7pKd1W6g=="], ["created_at", "2019-09-26 09:11:55.144920"]]
  ActiveStorage::Attachment Create (0.5ms)  INSERT INTO "active_storage_attachments" ("name", "record_type", "record_id", "blob_id", "created_at") VALUES ($1, $2, $3, $4, $5) RETURNING "id"  [["name", "excel_file"], ["record_type", "CDRFile"], ["record_id", 9], ["blob_id", 10], ["created_at", "2019-09-26 09:11:55.146274"]]
  CDRFile Update (0.4ms)  UPDATE "cdr_files" SET "updated_at" = $1 WHERE "cdr_files"."id" = $2  [["updated_at", "2019-09-26 09:11:55.147303"], ["id", 9]]
   (0.9ms)  COMMIT
/path/to/my/storage/bg/6o/bg6otind6q8s1t93g5zsamyxzjn2 doesn't exist
Traceback (most recent call last):
        2: from (irb):3
        1: from app/models/cdr_file.rb:19:in `create_sessions_from_xls'
IOError (file /path/to/my/storage/bg/6o/bg6otind6q8s1t93g5zsamyxzjn2 does not exist)
```

### System configuration
**Rails version**: 6.0.0
**Ruby version**: 2.6.1p33

Let me know if you need anything to reproduce. Thanks for any help!

**Comment by jankeesvw** [comment]
I ran into the exact same problem and I got it working by reversing the two lines.

Can you verify if this works:

```ruby
class CDRFile < ApplicationRecord
  after_create_commit :create_sessions_from_xls

  has_one_attached :excel_file
```

I got this right clue from this https://github.com/rails/rails/issues/36994#issuecomment-541256797.

**Comment by ErikDeBruijn** [comment]
@jankeesvw yes, this fixes it, just changing the order of those two lines.
![image](https://user-images.githubusercontent.com/191236/67553059-a287fc80-f70c-11e9-8db8-8a65e59ea5b6.png)

**Finally** we have upgraded to Rails 6!!! This was the one thing that was blocking it.

Thank you so much. The only thing that should happen is that this somehow follows from the Rails upgrade documentation when you wish to upgrade to Rails 6. So that's why I don't think it's closed.

**Comment by mihael** [comment]
Had this issue, attachment was not accessible and throwing 
```
     ActiveStorage::FileNotFoundError:
       ActiveStorage::FileNotFoundError
     # .../activestorage-6.0.0/lib/active_storage/service/disk_service.rb:34:in `rescue in block in download'
     # ...activestorage-6.0.0/lib/active_storage/service/disk_service.rb:32:in `block in download'
     # ...activestorage-6.0.0/lib/active_storage/service.rb:126:in `instrument'
     # ...activestorage-6.0.0/lib/active_storage/service/disk_service.rb:31:in `download'
     # ...activestorage-6.0.0/app/models/active_storage/blob.rb:189:in `download'
```

<img width="869" alt="Screenshot 2019-12-18 at 11 33 17" src="https://user-images.githubusercontent.com/7082/71078756-4b415e00-218a-11ea-9db5-1680ac55a3c5.png">

Moving `has_one_attached` after the callback definition worked!

Many thanks to @ErikDeBruijn for reporting and @jankeesvw for the fix suggestion.

**Comment by drale2k** [comment]
This is still an issue. Can we please leave this open until it's fixed?

**Comment by kaspth** [comment]
Consider volleying a PR instead. `after_commit` callbacks run in reverse order, so reordering or passing `prepend: true` to your custom callbacks fixes it. Potential fix could involve adding `prepend: true` to Active Storage's hook: https://github.com/rails/rails/blob/4d0c335cbb7d16bbd5d24106365caff14c4f53ff/activestorage/lib/active_storage/attached/model.rb#L69

Please do investigate ✌️

**Comment by vovimayhem** [comment]
FYI Currently on `main` (7.1x), the order required for this to work has somehow reversed, so watch out:

```ruby
  # Before 7.1x (edge)
  after_create_commit :do_something_with_uploaded_file
  has_one_attached :uploaded_file
  
  # 7.1x (edge):
  has_one_attached :uploaded_file
  after_create_commit :do_something_with_uploaded_file
```

**Comment by skipkayhil** [comment]
#46992 added configuration for that: `config.active_record.run_after_transaction_callbacks_in_order_defined`.  The default is the existing behavior, so the order should not change unless you uncomment that configuration in `new_framework_defaults` or switch to `load_defaults 7.1`.

If the switch is necessary without setting that configuration to `true` or using `load_defaults 7.1`, then that it a bug and you should create a new issue.

**Comment by NazarK** [comment]
I think you could create Thread and wait there for the file to appear (worked for me)
```
Thread.new { 
  while !File.exists?(filename) do
     sleep 0.2
  end
  #your further code
}
```

**Comment by vilarsttiago** [comment]
Insira esse fix no /config/initializers, vai resolver o problema


      class ActiveStorageRaceConditionMiddleware
        def initialize(app)
          @app = app
        end
      
        def call(env)
          # Intercepta as requisições direcionadas para os arquivos do ActiveStorage
          if env['PATH_INFO'].include?('/rails/active_storage/')
            retries = 0
            
            begin
              status, headers, response = @app.call(env)
              
              # Se der 404 (arquivo ainda gravando em disco), força uma nova tentativa interna
              if status == 404 && retries < 6
                retries += 1
                sleep 0.5
                raise "ActiveStorage local file write delay retry ##{retries}"
              end
              
              [status, headers, response]
            rescue StandardError
              retry
            end
          else
            @app.call(env)
          end
        end
      end
