### ISSUE TITLE
Blob not found errors if attachable rewritten before analyze job completes

### ISSUE THREAD

**Issue by jackkinsella** [rails/rails#37305]
Not sure how much of a core vs. fringe issue this is, but I thought I'd bring it to your attention in case it has any value. I have an application where I scrub certain sensitive data out of attached files as soon as I receive them. 

With the job queue disabled, run something like the following:

```ruby
class Document
  has_one_attached :data
end

document = Document.new
document.data.attach(io: File.open("Gemfile"), filename: "Gemfile.fakename") 
document.save # queues an Analyze job
document.data.attach(io: File.open("Gemfile"), filename: "Gemfile.otherfakename") 
document.save # queues Purge and a new Analyze job
```

Now, when you run the job queue _out of order_ (since order is usually not guaranteed with a job queue), you sometimes get errors as shown below.

```
# force an unlucky ordering
Delayed::Job.where(queue: "active_storage_purge").each &:invoke_job
Delayed::Job.where(queue: "active_storage_analysis").each &:invoke_job

=> ActiveJob::DeserializationError: Error while trying to deserialize arguments: Couldn't find ActiveStorage::Blob with 'id'=x
```

**Comment by syakovyn** [comment]
Actually, it does not fix the original issue. The exception thrown from the Active Job is `ActiveJob::DeserializationError` not `ActiveRecord::RecordNotFound` which `ActiveJob::DeserializationError` wraps.

**Comment by syakovyn** [comment]
Looks like I was wrong. The issue I have is due to Airbrake plugs in:
```ruby
        rescue_from(Exception) do |exception|
          Airbrake::Rails::ActiveJob.notify_airbrake(exception, self)
        end
```
`discard_on ActiveRecord::RecordNotFound` relies on cause chaining and Airbrake overrides that by handling all the previously unmatched Exceptions directly.

**Comment by syakovyn** [comment]
Fixed redefining `ActiveStorage::AnalyzeJob`. Added
```ruby
  discard_on ActiveJob::DeserializationError do |_job, error|
    raise error unless error.cause.is_a? ActiveRecord::RecordNotFound
  end
```
to it.
