### ISSUE TITLE
bug with enum and scoping : "Class level methods will no longer inherit scoping" deprecation

### ISSUE THREAD

**Issue by ngouy** [rails/rails#37306]
ActiveRecord 'issue'

Hello there. I have a weird deprecation poping when coupling a enum scoped model (`MyModel.my_enum_scope`) with `find_or_initialize_by` and a block itself containing a call to a scope to to the same model/enum . Pseudo code : 
```rb
MyModel.my_enum_value_scope.find_or_initialize_by(...) do
	# throw deprecation
	MyModel.another_enum_value_scope
end
```

### Steps to reproduce
Let's  have a model

```rb
# attributes : 
# my_enum: :integer
# title:  :string

class MyModel < ApplicationRecord
  enum my_enum: { text:           0,
                  comment:        1,
                }
end
```

Now if I use a scope into a find_or_create_by block (him self scoped), I have a deprecation warning.
> I know the code makes no sense, it's just the shortest show case to make it understandable

```rb
MyModel.text.find_or_initialize_by(title: SecureRandom.uuid) do |my_new_model|
    # the following line is producing a warning deprecation
	my_new_model.title = MyModel.comment.first.title
end
```

this output the exact following : 
```
DEPRECATION WARNING: Class level methods will no longer inherit scoping
from new in Rails 6.1. To continue using the scoped relation,
pass it into the block directly. To instead access the full
set of models, as Rails 6.1 will, use `MyModel.unscoped`.
```

Here is an (ugly, pardon me) [repl.it sandbox link](https://repl.it/@ngouy/SnarlingZestyShareware). click on play, wait, and watch the logs (scroll a bit to top).
> The file which execute this code is index.html.erb (gosh)

### Expected behavior
I don't even understand why it will fail in rails 6.1 so I don't know what should be the expected behaviour

### Actual behavior
No warning ?

If it's the desired behaviour, and indeed it will broke in 6.1, I am sorry. Though is it possible to clarify the "why?"

### System configuration
**Rails version**:
6.0.0
**Ruby version**:
2.5.5

**Comment by kamipo** [comment]
It is the expected behavior, see #35186 and #35280 for more details.

**Comment by ngouy** [comment]
Thank you @kamipo, sorry then.

**Comment by kamipo** [comment]
Yes, it's the desired behavior and the expected behavior for Rails 6.1, but Rails 6.0 doesn't it.
