### ISSUE TITLE
Support covering indexes in PostgreSQL

### ISSUE THREAD

**Issue by tjwallace** [rails/rails#37307]
[PostgreSQL 11 supports covering indexes](https://www.postgresql.org/docs/11/indexes-index-only-scans.html). It would be great if `add_index` supports an `:include` option to generate `INCLUDE (foo, bar)` on indexes.

```ruby
add_index :table, :column, include: %i[foo bar]
# CREATE INDEX index_table_on_column ON table (column) INCLUDE (foo, bar);
```

**Comment by vnhnhm** [comment]
I took this and I'm working on a PR to introduce support for PostgreSQL covering indexes.

How would you handle projects using older versions of PostgreSQL (< 11) that don't support covering indexes?

**Comment by vnhnhm** [comment]
I've just created a [PR](https://github.com/rails/rails/pull/37515) to add support for covering indexes.

I'll really appreciate any feedback.

**Comment by simi** [comment]
:thinking: I think this one can be closed:

1. it is not issue, but feature request
2. there's PR addressing this feature request
