### ISSUE TITLE
Cannot Monkeypatch Require with Rails 6

### ISSUE THREAD

**Issue by schneems** [rails/rails#37308]
### Steps to reproduce

I made a reproduction example repo with directions: https://github.com/schneems/rails_monkeypatch_require_issue

The script loads a tiny rails app, then monkeypatches `require` then it uses `require` in a way that should demonstrate that the monkeypatch was successful. Here's the contents:

```ruby
require 'bundler/setup'
require 'rails'
Bundler.require :default

module Dummy
  class Application < Rails::Application
    config.cache_classes = true
  end
end

Dummy::Application.initialize!

module Kernel
  module_function # rubocop:disable Style/ModuleFunction

  def require(path)
    raise "require"
  end
end

begin
  require 'rake'
rescue => e
  puts e.message
  puts "Worked AS EXPECTED !!!!!!!!!" if e.message == "require"
else
  raise "Did not work, expected an exception from our monkeypatch"
end
```
 
### Expected behavior

When I monkeypatch `Kernel.require` it should work. You will see:

```
$ bundle exec ruby main.rb
# ...
Worked AS EXPECTED !!!!!!!!!
```

### Actual behavior

When using Rails 6, monkeypatching `Kernel.require` does not work. You will see:

```
$ bundle exec ruby main.rb
#...
main.rb:27:in `<main>': Did not work, expected an exception from our monkeypatch (RuntimeError)
```

### System configuration

**Rails version**: 6.0.0

**Ruby version**: 2.6.4

**Comment by rafaelfranca** [comment]
You are monkey patching `require` after the application is initialized. At that point all classes are already loaded.

**Comment by rafaelfranca** [comment]
Ah, but you call a new require after.

**Comment by schneems** [comment]
@rafaelfranca correct, I could perhaps improve the example script to show that I'm executing another require. I wasn't sure on the best way to illustrate that.

@fxn any chance you can take a look at this? It's not a critical blocker, but if you have any extra information on what might be causing the failure mode or how it could be worked around I would be very grateful.

**Comment by fxn** [comment]
Hey, I am at a conference.

Can't get into it right now, but I think your hypothesis about `exclude_from` could be good.

If you compare `Object.method(:require).source_location` and `Object.method(:require).source_location`, you'll see they are different. The one in `Object` points to the [original monkeypatch in Zeitwerk](https://github.com/fxn/zeitwerk/blob/master/lib/zeitwerk/kernel.rb#L13) (could be any other of the existing ones, it is not relevant to which lib it belongs to).

In Rails 6 [we unhook AS dependencies](https://github.com/rails/rails/blob/bfc9065d58508fb19dd1a4170406604dd3b3234a/activesupport/lib/active_support/dependencies/zeitwerk_integration.rb#L101) in `zeitwerk` mode, to disable classic autoloading altogether. That executes those `exclude_from`.

That also happens by default in `production` mode in previous Rails versions, [there is a finalizer that unhooks](https://github.com/rails/rails/blob/02ecdf61d151ec3c852585c93942d0ea2ed2bd22/railties/lib/rails/application/finisher.rb#L245) (see actual flags checked in the linked code). So, if the hunch is good, I believe we should be able to reproduce in Rails 5 in `production` mode.

**Comment by schneems** [comment]
Thanks for the response. This is what I'm seeing after my code executes

```
Kernel.method(:require).source_location.inspect: ["main.rb", 16]
Object.method(:require).source_location.inspect: nil
```

I did find that I can work around this temporarily by defining the method explicitly on object:

```ruby
class Object
  def require(path)
    raise "require"
  end
end
```

Though ideally, I would like to not have to maintain two different duplicate sets of code paths. 

> So, if the hunch is good, I believe we should be able to reproduce in Rails 5 in production mode.

I tried running my repro app with Rails 5.2.3 and the issue doesn't reproduce, perhaps some other config settings need to be toggled.

Thanks again for your reply. Hope you have/had a good conf!

**Comment by BKSpurgeon** [comment]
> I tried running my repro app with Rails 5.2.3 and the issue doesn't reproduce, perhaps some other config settings need to be toggled.

That's very interesting: I've tried it on 5.2.3 and it works as expected, regardless of whether `config.eager_load` is set to true or false or nil. 

Would be interested to know how one would go about about debugging these types of issues?

**Comment by schneems** [comment]
I think we can close this. The method's correct visibility is private and since keeping it private fixes this bug, it's fine to close.
