### ISSUE TITLE
Controller `#stale?` does not work as expected with ActiveRecord::Relations

### ISSUE THREAD

**Issue by mpospelov** [rails/rails#37310]
After updating to rails 6 my test suite failed because of breaking changes of `#stale?(active_record_relation)` method. The new feature was introduced in rails 6 https://github.com/rails/rails/pull/34378

So whenever we update one of `active_record_relation` elements the cache key stays the same. The cache key retrieval happens there inside this method:
https://github.com/rails/rails/blob/master/activesupport/lib/active_support/cache.rb#L94-L102

And because there is no definition of `cache_key_with_version` it uses `cache_key` for `ActiveRecord::Relation` which breaks the behaviour described in the documentation for collections https://api.rubyonrails.org/classes/ActionController/ConditionalGet.html#method-i-stale-3F

### Steps to reproduce
```
# Controller
def index
  @articles = Article.all

  if stale?(@articles)
    @statistics = @articles.really_expensive_call
    respond_to do |format|
      # all the supported formats
    end
  end
end

# Test
it "updates cache when one of articles is updated" do
  all_articles = create_list(:article, 10)
  response = get '/articles'
  etag = response.headers['ETag']
  expect(response.status).to eq(200)
  get '/articles', headers: { 'HTTP_IF_NONE_MATCH' => etag }
  expect(response.status).to eq(304)
  all_articles.sample.touch
  get '/articles', headers: { 'HTTP_IF_NONE_MATCH' => etag }
  # HERE on next line assert will fail because server will respond with 304, 
  # because cache key for ActiveRecord::Relation will stay the same  
  expect(response.status).to eq(200) # => 304 💥💥💥
end
```
### Expected behaviour
Check tests section last assert

### Actual behavior
Check tests section last assert

### System configuration
**Rails version**: 6.0.0

**Ruby version**: 2.6.3

**Comment by andyatkinson** [comment]
I believe I have reproduced this issue on `6.0.2.2` as well. Details:

https://github.com/rails/rails/pull/37311#issuecomment-628229260
