### ISSUE TITLE
ActiveJob: Seems that `retry_on` calls on a base class (a.k.a. ApplicationJob) have no effect?

### ISSUE THREAD

**Issue by andreynering** [rails/rails#37324]
Hi everybody,

Ruby v2.5.3 and Rails v5.2.3 here. I'm using Resque as the backend.

I have been trying to do something like this:

```ruby
class ApplicationJob < ActiveJob::Base
  retry_on Resque::DirtyExit
end
```

```ruby
class MyOtherJob < ApplicationJob
  # other retry_on calls here
end
```

But I couldn't get it to work (i.e. only retries declared the on job class work, not those on the base class).

I couldn't find in the documentation if this is supposed to work, but it makes sense for me.

**Comment by georgeclaghorn** [comment]
Active Job never sees `Resque::DirtyExit`s, so it can’t retry them. Resque records them after the corresponding workers have already exited.

**Comment by andreynering** [comment]
Oh

It works with bare Resque. It'd be nice to have an alternative.

Thanks anyway!
