### ISSUE TITLE
 uninitialized constant Datagrid::Filters (NameError)

### ISSUE THREAD

**Issue by saydulk** [rails/rails#37323]
### Expected behavior

when i run $ rails server it shows:  uninitialized constant Datagrid::Filters (NameError)

### System configuration
**Rails version**:
5.2
**Ruby version**:
ruby 2.5.0p0

**Comment by kaspth** [comment]
This sounds like it’s coming from a gem in your Gemfile. Datagrid doesn’t appear in Rails’ source: https://github.com/rails/rails/search?utf8=✓&q=Datagrid&type=

Thanks!
