### ISSUE TITLE
Config autoload_paths cannot be modified by environment configurations

### ISSUE THREAD

**Issue by aldhsu** [rails/rails#37331]
### Steps to reproduce
1. Configure environment eg. "test" to add a new autoload path

### Expected behavior
1. Autoload paths is changed for the environment 
I was assuming autoload paths can be changed based on environment as that would be consistent with other `config`

### Actual behavior
1. Autoload paths is not changed as it is already frozen
2. Even if you duplicate the autoload paths it is not respected because ActiveSupport::Dependencies.autoload_paths has already been set, you can modify this yourself but the guide says not to do so:
```
Please, do not mutate ActiveSupport::Dependencies.autoload_paths, the public interface to change autoload paths is config.autoload_paths
```

### System configuration
Rails: Master as of 57ae917
Ruby: 2.6

### Preliminary Investigation
- `set_load_paths` and `set_autoload_paths` happens before the `load_environment_config`
https://github.com/rails/rails/blob/57ae917e9d52c9472fd37adbfa47d6de93dd01bf/railties/lib/rails/engine.rb#L575-L615
- moving the `set_load_paths` `set_autoload_paths` after the environment seems to work
  - Possibly makes sense since with Zeitwerk autoloading in initializers is deprecated, you receive the warning: `DEPRECATION WARNING: Initialization autoloaded the constants`

**Comment by fxn** [comment]
I think this suggested change makes sense. Conceptually, the configuration set in `config/environments/*` is like the one in `config/application.rb`, only the former can override the latter.

With this change, applications won't be able to autoload from `config/application.rb`, but that shouldn't be possible anyway.

Would you like to open a PR?

**Comment by eugeneius** [comment]
Fixed in https://github.com/rails/rails/commit/43863bfc5716d8bd2f5be59920239aee1470465a.
