### ISSUE TITLE
Rails console enhancements like irb brought by ruby 2.7 

### ISSUE THREAD

**Issue by silva96** [rails/rails#37355]
Ruby 2.7 will bring cool and useful features for irb 

among them there is syntax highlighting, multiline editing, display documentation on double tab, enable auto indent, etc.

Is this something rails console can/will inherit or replicate?

Find more info in this blog post (not mine)

https://blog.saeloun.com/2019/09/23/new-irb-features.html

**Comment by georgeclaghorn** [comment]
The Rails console more or less *is* IRB, so we’ll get these improvements automatically.
