### ISSUE TITLE
Run system tests from specific file

### ISSUE THREAD

**Issue by benjaminwols** [rails/rails#37354]
I try to run a specific system test file when adding new system tests, but it always runs all tests.

### Steps to reproduce
Run `rails test:system /path/to/system/test.rb`

### Expected behavior
Only system tests in file are run

### Actual behavior
All system tests are run

### System configuration
**Rails version**:6.0

**Ruby version**:2.6.3

**Comment by vinistock** [comment]
I believe that's expected because the rake task "test:system" probably doesn't accept arguments. Have you tried `rails test /path/to/system/test.rb`?

**Comment by kaspth** [comment]
Yeah, the general test command is what's needed here. The scoped tests commands are more just about running everything in the scope.

Perhaps we could change that, but internally `test:system` ends up using Rake::TestTask iirc (whereas `rails test` is a custom Rails command) so there's a limit to how much we're going to change this. Thanks!
