### ISSUE TITLE
[Guides] Overflow text in box containing chapter names

### ISSUE THREAD

**Issue by juliettech13** [rails/rails#37363]
### Steps to reproduce
Go to [Caching with rails (rails guides)](https://guides.rubyonrails.org/caching_with_rails.html)

### Expected behavior
The **text** inside` #subCol` (the white box containing all chapters on the right side of the page) should not overflow the size of the div.  

### Actual behavior
Because the text is all one word, it overflows it's container size
<img width="1440" alt="Screenshot 2019-10-04 at 1 24 25 PM" src="https://user-images.githubusercontent.com/19226636/66207295-5831d380-e6aa-11e9-8f98-7fc9a3e2ee63.png">

### System configuration
**Browser**: Firefox Quantum 69.0.1
**Operating System**: Macbook Pro Mojave 10.14.1
**Device Screen Size**: 13 inches

**Comment by ramonpm** [comment]
I'm on it!

**Comment by BhumikaSaini** [comment]
This issue still persists (verifiable by visiting the page [Caching with Rails: An Overview](https://guides.rubyonrails.org/caching_with_rails.html)).

**Comment by p8** [comment]
@BhumikaSaini It is fixed on edgeguides: https://edgeguides.rubyonrails.org/caching_with_rails.html
