### ISSUE TITLE
Ordering with includes no longer works in 6.0

### ISSUE THREAD

**Issue by portwood** [rails/rails#37376]
### Expected behavior
In 5.2.3:

    @company.departments
            .includes(:people)
            .group(:id)
            .order(:display_name)
            .count(:people)

properly sorts the departments by display_name

### Actual behavior
in 6.0.0:
The records are not ordered.
The workaround seems to be to change the includes to a joins.

### System configuration
**Rails version**:
6.0.0
**Ruby version**:
2.6.5

**Comment by sinsoku** [comment]
@portwood Can you write steps to reproduce using [this template](https://github.com/rails/rails/blob/master/guides/bug_report_templates/active_record_master.rb)?
Since there is no table definition or association information in the pull request description, you should write in a comment.
