### ISSUE TITLE
Copying migration from engine causes EmptyLineAfterMagicComment Rubocop violation

### ISSUE THREAD

**Issue by ztmeyer** [rails/rails#37371]
### Steps to reproduce
1. Write a migration in your engine, something like:
```ruby
# frozen_string_literal: true

class AddMyColumnToMyTable < ActiveRecord::Migration[5.2]
  def change
    add_column :my_table, :my_column, :string
  end
end
```

2. Run the task to copy migrations from your engine to your main app:
`bundle exec rake my_cool_engine:install:migrations`

3. The migration at the top level will look something like this (note the 2nd line):
```ruby
# frozen_string_literal: true
# This migration comes from my_cool_engine (originally 20191004211152)

class AddMyColumnToMyTable < ActiveRecord::Migration[5.2]
  def change
    add_column :my_table, :my_column, :string
  end
end
```

4. The copied migration will fail Rubocop
```
Offenses:

db/migrate/20191004211356_add_my_column_to_my_table.my_cool_engine.rb:2:1: C: Layout/EmptyLineAfterMagicComment: Add an empty line after magic comments.
# This migration comes from my_cool_engine (originally 20191004211152)
^
```

Specifically:
`Layout/EmptyLineAfterMagicComment: Add an empty line after magic comments`

### Expected behavior
If a magic comment is present, I would expect a blank line to be inserted between the magic comment and the inserted comment ("This migration comes from ...").

It looks like Rails already has support to handle magic comments in migrations being copied from engines:
https://github.com/rails/rails/blob/master/activerecord/lib/active_record/migration.rb#L913

Is it reasonable to fix this in Rails? We could change Rubocop instead, but it seemed strange to ignore magic comment violations in migrations copied from engines. 

If we should handle this in Rails, we may be able to fix this by changing the `.sub!` to pick up the optional newline (adding a `(\n?)` onto the end of the regex).

### Actual behavior
There is no blank line after the magic comment.

### System configuration
**Rails version**:
Rails 5.2

**Ruby version**:
Ruby 2.6.3

**Comment by georgeclaghorn** [comment]
See https://github.com/rails/rails/pull/37373#issuecomment-539800425.
