### ISSUE TITLE
SettingFile: An internal feature proposal

### ISSUE THREAD

**Issue by krainboltgreene** [rails/rails#37378]
So today I spent 45m with another senior engineer trying to figure out why `bin/rails console` failed with a YAML parse exception. You can see here: https://gist.github.com/cacheflow/f16e1551a5a4a51c698d5962a7e7116b

In my opinion there are four important points to make:

  1. The exception message is disastrously long considering the actual issue. It's also very un-googable.
  2. The problem is near impossible to detect normally, but easily detectable programmatically. Even a IDE doesn't show the issue.
  3. The problem is incredibly easy to stumble into: Just copy some YAML from Notes.app or similar. Every new and senior engineer has done this.
  4. How rails loads and evaluates settings files seems to be very manual for every time:
    - https://github.com/rails/rails/blob/master/activerecord/lib/active_record/fixture_set/file.rb#L52-L70
    - https://github.com/rails/rails/blob/master/activerecord/lib/active_record/railties/databases.rake#L369
    - https://github.com/rails/rails/blob/master/activerecord/test/support/config.rb#L15-L26
    - https://github.com/rails/rails/blob/master/activestorage/lib/active_storage/service_registry.rb#L17-L30
    - https://github.com/rails/rails/blob/master/activestorage/test/test_helper.rb#L26-L34
    - https://github.com/rails/rails/blob/master/railties/lib/rails/application.rb#L229-L244
    - And loads more

The benefits of turning this into a singular interface, to me, are clear:

  1. We can detect common mistakes that new and veteran engineers will want to know about.
  2. We can be safer about our loading of YAML
  3. We can share the rescue that many of these snippets use
  4. Future rewrites will be much easier

As a first approach I've created https://github.com/krainboltgreene/rails/pull/1/files which is both a first pass at an API and also a first rewrite.

We don't have to rewrite all the snippets, we can gradually improve the interface.

By the way, if you haven't figured out the issue in the gist, it's that the indentations had non-breaking space characters (http://www.fileformat.info/info/unicode/char/a0/index.htm).

**Comment by kaspth** [comment]
> So today I spent 45m with another senior engineer trying to figure out why `bin/rails console` failed with a YAML parse exception.

We only consider it an actual bug if people have spent more than 3 hours on it. 🙈😅 — just kidding, let's do something about it! 😄 Appreciate the well written and clearly explained issue, it was easy to make a decision on 🙏

We already have `ActiveSupport::EncryptedConfiguration`, so maybe `ActiveSupport::ConfigurationFile` would be a good name. As for your sample PR, don't think we want it as a module with a module function. I'd probably make it a class with `def self.read` for ease of use.

So, whip up a starting PR and we can take it from there, I'll just close this up front in anticipation. We could scope it to cleanup just AS occurrences first too, for example.
