### ISSUE TITLE
ActionDispatch::Request remote_ip setter doesn't clear memoization

### ISSUE THREAD

**Issue by normprovost** [rails/rails#37383]
### Steps to reproduce

After ActionDispatch::Request remote_ip is set once, the attribute setter no longer does anything. The setter is setting a header and not clearing out the memoized value in the getter.

[Relevant code](https://github.com/normprovost/rails/blob/master/actionpack/lib/action_dispatch/http/request.rb#L279-L285)

### Failing test
 
```ruby
# frozen_string_literal: true

require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  gem "rails", github: "rails/rails"
end

require "minitest/autorun"
require "rack/test"

class BugTest < Minitest::Test
  include Rack::Test::Methods

  def test_set_remote_ip
    request = ActionDispatch::Request.empty
    request.remote_ip = '123.123.123.123'
    assert request.remote_ip == '123.123.123.123'
    request.remote_ip = '234.234.234.234'
    assert request.remote_ip == '234.234.234.234'
  end
end

```

### Expected behavior
I would expect that setting the `remote_ip` either updates the value or throws an error if it's not a valid action.

### Actual behavior
The setter sets the `action_dispatch.remote_ip` header but does not clear the memoized value, so the getter returns the value that was set first.

### System configuration
**Rails version**: 6.0.0

**Ruby version**: 2.5.5p157

**Comment by eugeneius** [comment]
Fixed by https://github.com/rails/rails/pull/37384! ✌️🤓
