### ISSUE TITLE
Add support for rendering partials using relative paths

### ISSUE THREAD

**Issue by kaisbe** [rails/rails#37386]
Hello,

I know this is a duplicate of #1143, but I think this issue is quite important and deserves enough attention.

Code Reuse and DRY principle are important, more particularly being able to re-use partials on different views. However this is not currently possible since it depends on rendering partials based on relative paths, and this feature is not supported yet.

### Steps to reproduce
1. Let's consider a page located at `app/views/myview/index.html.haml`
2. Write a partial under the path `app/views/_mypartial.html.haml`
3. Clear the contents of the page `app/views/myview/index.html.haml`
4. Edit the code of `app/views/myview/index.html.haml` as: `= render :partial '../mypartial'`, in order to be able to render the partial from the parent directory using a relative path.
5. Start rails server
6. Go to the address of the page mapped to `app/views/myview/index.html.haml`

### Expected behavior

The page gets displayed successfully.

### Actual behavior

An exception occurs, saying:

> Missing partial ../_mypartial with {:locale=>[:en], :formats=>[:html], :variants=>[], :handlers=>[:erb, :builder, :raw, :ruby, :coffee, :haml]}

However it is not the case, after changing the partial path to an absolute one which is 'mypartial.html.haml' (under the same directory) and creating a hard link using the command `ln ../_mypartial.html.haml _mypartial.html.haml`.

### System configuration
**Rails version**:
5.2.3
**Ruby version**:
2.5.5p157

**Comment by kaspth** [comment]
It's being worked on in https://github.com/rails/rails/pull/22473, thanks.

**Comment by fwolfst** [comment]
Afaict this does not work anymore in Rails 7(.0.1.3).

**Comment by SimBed** [comment]
I don't see the relative path syntax working either (Rails 7.0.7). It would be very useful. Unsure why it was indicated this issue was being worked on and then closed as completed. Did it work for a while in 2019?
