### ISSUE TITLE
Should not re-migrate everytime specs are run

### ISSUE THREAD

**Issue by Haelle** [rails/rails#37407]
### Steps to reproduce
A repository is available here : https://github.com/Haelle/rails_db_rights_error
Follow the README to reproduce the error

### Expected behavior
Spec should run without re-migrating

### Actual behavior
Rails re-run migration because `ActiveRecord::InternalMetadata[:schema_sha1]` is not updated after every migration

### System configuration
**Rails version**: 6
**Ruby version**: 2.6.2

#### Situation
An extension of PostgreSQL is enabled (visible `enable_extension "pgcrypto"` in `schema.rb`)
But this extension is enabled via a script (cf README) an not via Rails because Rails user _should not_ have this right (SUPERUSER !)

#### Problem
Cannot run specs since Rails 6, because it tries to re-prepare the database and it does not have the right (SUPERUSER)
_I saw that [this section/logic](https://github.com/rails/rails/blob/cb495ab250a03e80262e268c28c7f7eebd7e2b22/activerecord/lib/active_record/migration.rb#L629) of code had a lot of changes between Rails 5 & 6._

#### Details
Everything starts in `spec/rails_helper.rb` => `ActiveRecord::Migration.maintain_test_schema!`

When it arrives in `load_schema_if_pending`, `need_update` is set to `true` and then it tries to do `db:test:prepare` and of course if fails when because it does not have the rights to create the extension.
https://github.com/rails/rails/blob/cb495ab250a03e80262e268c28c7f7eebd7e2b22/activerecord/lib/active_record/migration.rb#L606-L627

But it should not `need_update` (`schema_up_to_date?` return `false`) but it is up to date !

`schema_up_to_date?` returns `false` because of this test : 
https://github.com/rails/rails/blob/feefcb869e4418d2ec366ae8a9149ac7a4ef2a39/activerecord/lib/active_record/tasks/database_tasks.rb#L347

The field `schema_sha1` is not set at all, it is only set in `load_schema` and as its name says it's only called in `db:schema:load`
https://github.com/rails/rails/blob/feefcb869e4418d2ec366ae8a9149ac7a4ef2a39/activerecord/lib/active_record/tasks/database_tasks.rb#L310

So if I run `rails db:schema:load` it works, but if I add a new migration it fails again.

#### Conclusion
Everything would work fine if there wasn't this limitation in the rights of the DB user.
It would `need_update`, run the migration again and then run the tests
But the the database is up to date and should not need to re-migrate !

#### Proposition
Update `ActiveRecord::InternalMetadata[:schema_sha1]` after any migration

**Comment by zeitnot** [comment]
I have the same problem.

**Comment by marvinthepa** [comment]
Still present in Rails 6 and quite annoying.

**Comment by berniechiu** [comment]
Any solution here?

**Comment by janospapp** [comment]
Nice finding. I am upgrading from rails 5.2.3 to 6.1, and the same problem broke my specs.

I commented out `ActiveRecord::Migration.maintain_test_schema!` from `rails_helper.rb` that solved the problem (I recreate my test db before calling rspec anyway).

**Comment by zeitnot** [comment]
@janospapp The following setup works for me:

```ruby
begin
  ActiveRecord::Base.connection.migration_context.needs_migration? and raise ActiveRecord::PendingMigrationError.new
  # This is buggy after Rails 6
  # ActiveRecord::Migration.maintain_test_schema!
rescue ActiveRecord::PendingMigrationError => e
  puts e.to_s.strip
  exit 1
end
```

**Comment by Loschcode** [comment]
I've this exact same problem as well. It's definitely still present and breaks my tests. Took me hours to find this issue

```
bin/rails:4:in `<main>'
Tasks: TOP => db:test:load => db:test:purge
```

This is running but it wasn't when I was on Rails 5.2.

**Comment by marvinthepa** [comment]
> If you can still reproduce this error on the `6-0-stable` branch or on `master`, please reply with all of the information you have about it in order to keep the issue open.

Still an issue.

**Comment by kazufusa** [comment]
I solved this problem by `./bin/rails db:schema:load RAILS_ENV=test` every time before CI test.

**Comment by yusakuhomma** [comment]
I solved this problem by writing this in `spec/rails_helper.rb`.

```ruby:spec/rails_helper.rb
RSpec.configure do |config|
  config.before :suite do
    Rails.application.load_seed  # Add this line
  end
end
```

**Comment by alexpapworth** [comment]
Just ran into this problem on `7.0.0`, but not sure how to reproduce.

**Comment by carter-thaxton** [comment]
Until this is fixed, here's a workaround.  Create a new file called `config/initializers/database_tasks_schema_up_to_date.rb`, with these contents.  It monkey-patches the `schema_up_to_date?` method to handle the case where `ActiveRecord::InternalMetadata[:schema_sha1]` has not yet been set.

```
# Avoid considering the schema out of date, if the schema_sha1 hasn't already been loaded
# This prevents the test database from being dropped every time cucumber tests are run
# https://github.com/rails/rails/issues/37407
module ActiveRecord
  module Tasks
    module DatabaseTasks

      def schema_up_to_date?(configuration, format = ActiveRecord::Base.schema_format, file = nil, environment = env, spec_name = "primary")
        file ||= dump_filename(spec_name, format)

        return true unless File.exist?(file)

        ActiveRecord::Base.establish_connection(configuration)
        return false unless ActiveRecord::InternalMetadata.table_exists?
        return true unless ActiveRecord::InternalMetadata[:schema_sha1]  # Added to workaround issue when this is called without first loading schema
        ActiveRecord::InternalMetadata[:schema_sha1] == schema_sha1(file)
      end

    end
  end
end

```

**Comment by carter-thaxton** [comment]
And just coming back here to note a fix for Rails 7, where the implementation of `schema_up_to_date?` has changed a bit.
I still need this to make Cucumber tests work without crashing, and leaving the test database in an inconsistent state.

```
# Avoid considering the schema out of date, if the schema_sha1 hasn't already been loaded
# This prevents the test database from being dropped every time cucumber tests are run
# https://github.com/rails/rails/issues/37407
module ActiveRecord
  module Tasks
    module DatabaseTasks
      def schema_up_to_date?(configuration, format = ActiveRecord.schema_format, file = nil)
        db_config = resolve_configuration(configuration)

        file ||= schema_dump_path(db_config)

        return true unless file && File.exist?(file)

        ActiveRecord::Base.establish_connection(db_config)

        return false unless ActiveRecord::InternalMetadata.enabled?
        return false unless ActiveRecord::InternalMetadata.table_exists?

        return true unless ActiveRecord::InternalMetadata[:schema_sha1]  # Added to workaround issue when this is called without first loading schema

        ActiveRecord::InternalMetadata[:schema_sha1] == schema_sha1(file)
      end
    end
  end
end
```
