### ISSUE TITLE
rich_text_area_tag causes embedded images to be deleted on *edit*, unlike form.rich_text_area

### ISSUE THREAD

**Issue by eadz** [rails/rails#37405]
### Steps to reproduce

I have made an example repo, but it's pretty simple:

1) Use `rich_text_area_tag 'model[field]', model.field` in place of `form.rich_text_area :field`
2) Use the image attachment function, and save
3) Edit the field, and save
4) The attachment has been deleted

Example Repo where editing a rich text field causes the images to be deleted.

https://github.com/eadz/RichTextAreaBug

Undo this commit and it works:

https://github.com/eadz/RichTextAreaBug/commit/27225206f01867bbc7ebc40fb7fc7797f7f68bee

### Expected behavior

The attachements should not be deleted

### Actual behavior

The attachments are deleted.

### System configuration

Rails 6, ruby 2.5

**Comment by eadz** [comment]
@georgeclaghorn just tagging you in case you missed this, please let me know if there is any more information required.

**Comment by eadz** [comment]
Hi,
This issue is still unresolved. I've made an example repo and patch to demonstrate the problem.

**Comment by eadz** [comment]
Just asking if this is an issue for anyone else?

**Comment by bgracie** [comment]
Yep, I'm experiencing this issue as well.

**Comment by rafaelfranca** [comment]
Thank you for reporting the issue. Given you already have a way to reproduce could you try to investigate it and fix?

**Comment by eadz** [comment]
@rafaelfranca I did try but could not work out the problem
