### ISSUE TITLE
106 MByte nodes_modules

### ISSUE THREAD

**Issue by hadmut** [rails/rails#37416]
Hi,
I just gave rails 6.0 a first try and was shocked to see that just a simple
rails new example
creates a rails app directory of 108 MByte because of a subfolder node_modules of 106 MByte, where former releases of rails created simple apps of less than 2MByte. 

Apps occupy more than 50 times as much disk space now and bloat containers. 

Is this a bug or is this really intended and part of the design? I can't believe to have an interpreter language like ruby but start with 108 MByte without having anything done yet, just the empty app. That's horrible. 

**Rails version**: 6.0.0

**Ruby version**: 2.5.1

**Comment by andrewkress** [comment]
rails ships with webpacker now which would add the node_modules directory.  If you wish to skip webpacker, generate a new app with the _--skip-webpack-install_ option.
