### ISSUE TITLE
activestorage blob isn't created with ArgumentError when initialized by nested attributes

### ISSUE THREAD

**Issue by metheglin** [rails/rails#37411]
### Steps to reproduce

First, create has_many association between `:shops` and `:members` with nested attributes and activestorage declaration.

```ruby
class CreateShops < ActiveRecord::Migration[6.0]
  def change
    create_table :shops do |t|
      t.string :name
    end
    create_table :members do |t|
      t.bigint :shop_id
      t.string :name
    end
  end
end
class Shop < ApplicationRecord
  has_many :members
  accepts_nested_attributes_for :members
end
class Member < ApplicationRecord
  belongs_to :shop
  has_one_attached :image
end
```

Then, creating blob with nested attributes always fails with ArgumentError, while direct creation gets success.

```ruby
Shop.create!(name: :hello)

Member.create!(name: :test, shop_id: Shop.first.id, image: {io: StringIO.new('test'), filename: :test})
# => success

Shop.create!(
  name: :shop,
  members_attributes: [
    {name: :test1, image: {io: StringIO.new('test1'), filename: :test1}},
    {name: :test2, image: {io: StringIO.new('test2'), filename: :test2}}
  ]
)
# => ArgumentError (wrong number of arguments (given 1, expected 0; required keywords: io, filename))
```

I guess the cause is with nested attributes it converts arguments to indifferent access hash.

https://github.com/rails/rails/blob/66cabeda2c46c582d19738e1318be8d59584cc5b/activerecord/lib/active_record/nested_attributes.rb#L500

While, building methods of ActiveStorage::Blob expect keyword arguments.

https://github.com/rails/rails/blob/66cabeda2c46c582d19738e1318be8d59584cc5b/activestorage/app/models/active_storage/blob.rb#L60

### Expected behavior

Create, associate, upload blob successfully using nested attributes.

### Actual behavior

Fail with the following error.
`ArgumentError (wrong number of arguments (given 1, expected 0; required keywords: io, filename))`

### System configuration
**Rails version**:
6.0.0
**Ruby version**:
2.5.1p57

I'm not sure the best way to fix this issue, but please check this behavior once.

**Comment by ImOnMars** [comment]
Also getting this issue, not sure how to properly do nested model attachments

**Comment by heaven** [comment]
@metheglin were you able to resolve this?

**Comment by metheglin** [comment]
@heaven Sorry, I just stuck on this issue at checking the behavior of activestorage. Not in actual code. You may be able to resolve this issue by avoiding nested attributes like below.

```ruby
shop = Shop.new(name: :shop)
shop.members.build(name: :test1, image: {io: StringIO.new('test1'), filename: :test1})
shop.members.build(name: :test2, image: {io: StringIO.new('test2'), filename: :test2})
shop.save!
```

**Comment by choznerol** [comment]
I made a PR #39908 to fix this

Meanwhile, another workaround to continue using nested attributes could be:
```diff
Shop.create!(
  name: :shop,
  members_attributes: [
-    {name: :test1, image: {io: StringIO.new('test1'), filename: :test1}},
-    {name: :test2, image: {io: StringIO.new('test2'), filename: :test2}}
+    {name: :test1, image: ActiveStorage::Blob.build_after_unfurling(io: StringIO.new('test1'), filename: :test1)},
+    {name: :test2, image: ActiveStorage::Blob.build_after_unfurling(io: StringIO.new('test2'), filename: :test2)}
  ]
)
```
