### ISSUE TITLE
Activestorage doesn't dirty the object

### ISSUE THREAD

**Issue by victorlcampos** [rails/rails#37412]
### Steps to reproduce
```
module Vinvoice
  class TaxDocument < ApplicationRecord
     has_one_attached :document_pdf
   end
end

tax_document = Vinvoice::TaxDocument.first
tax_document.document_pdf = nil
tax_document.changed? # false
```

### Expected behavior
tax_document.changed? return true

### Actual behavior
tax_document.changed? return false

### System configuration
6.0.0

**Ruby version**:
2.6.3

**Comment by joshmn** [comment]
It does, just not where you expect. See `attachment_changes` 

This might be deserving of some attention on the docs.

**Comment by victorlcampos** [comment]
But this don't make object be save when i call tax_document.save

**Comment by joshmn** [comment]
I'm not sure how much this will break the rest of Rails, but if you need it, drop this in an initializer:

```
module ActiveStorage
  module Attached::Model
    def self.has_one_attached(name, dependent: :purge_later)
      super
      generated_association_methods.class_eval <<-CODE, __FILE__, __LINE__ + 1
      def #{name}_changed?
        attachment_changes[name.to_s].present?
      end
      CODE
    end
  end
end

module ActiveModel::Dirty
  def attachment_changes
    @attachment_changes ||= {}
  end
  def reload(*)
    super.tap { @attachment_changes = nil }
  end
  def changed?
    mutations_from_database.any_changes? || attachment_changes.any?
  end
end

```

**Comment by victorlcampos** [comment]
In my case I fix it making tax_document.updated_at = Time.zone.now to force dirty the object 

But I think it is a strange behavior don’t save nested object if it only change attachment

**Comment by joshmn** [comment]
Is your intended behavior to purge the attachment?

**Comment by victorlcampos** [comment]
Not really, my intended behavior is call save on nested object when it only change the attachment 

a has one b
b has attachment 

a.attributes = { b_attributes: {attachament: nil }}

a.save did not save b

**Comment by victorlcampos** [comment]
It’s the save if am adding a file

**Comment by K1N5L4Y3R** [comment]
I agree that if `#attachment_changes` is to be _the way_ to check if one or more attachments changed, it should be documented.
