### ISSUE TITLE
pretty_print breaks when a json field hash key is an integer

### ISSUE THREAD

**Issue by phoet** [rails/rails#37428]
### Steps to reproduce
https://gist.github.com/phoet/37f206376b90df31fc47b98325e0a49f

see https://github.com/smartinez87/exception_notification/issues/483 for reference

### Expected behavior
`pp(model)` should work for a hash with an int key

### Actual behavior
it raises `TypeError: no implicit conversion of Integer into String`

### System configuration
**Rails version**: 6.0.0

**Ruby version**: 2.6.4

**Comment by abhaynikam** [comment]
@phoet : I was able to reproduce this issue on Rails 6.0 and master branch as well. Following are my findings after debugging the issue. 

1. This issue arises when `filter_attributes` are added. filter_attributes adds a regex here(https://github.com/rails/rails/blob/master/activesupport/lib/active_support/parameter_filter.rb#L84) as `(?i-mx:password)`.
2. For a JSON data type, value for keys is filtered here(https://github.com/rails/rails/blob/master/activesupport/lib/active_support/parameter_filter.rb#L116) which recursively calls the value of the JSON keys. So in case of `{ 11: {} }` the key received is  `11` which is integer when tried to match against the filter_attributes regex(ie: `(?i-mx:password)` ) it fails with a TypeError

```
/(?i-mx:password)/.match?(11)
```

To solve this we can convert the keys to strings while regex match on this line(https://github.com/rails/rails/blob/master/activesupport/lib/active_support/parameter_filter.rb#L111). I will raise PR for it but I am not certain if that is the correct solution.

**Comment by phoet** [comment]
updated the example to use master, the bug is still present

https://gist.github.com/phoet/37f206376b90df31fc47b98325e0a49f

**Comment by erotte** [comment]
![image](https://media.giphy.com/media/FLo0LIBIUeI6c/giphy.gif)

**Comment by kamipo** [comment]
Fixed by #37435.

**Comment by emezac** [comment]
This issue **is already fixed** with this commit  339d1cdc279d6e7d76e6c807fa4a00ac5306df8b by  Ryuta Kamizono <kamipo@gmail.com>
