### ISSUE TITLE
Confused about rails credentials

### ISSUE THREAD

**Issue by resistorsoftware** [rails/rails#37427]
-> rails credentials: edit

    aws: 
      access_key_id: 12345ABCDEF12345ABCDEF

save this file... 

-> rails credentials:show
    # aws:
    #   access_key_id: 123 
    #   secret_access_key: 345

\# Used as the base secret for all MessageVerifiers in Rails, including the one protecting cookies.
secret_key_base: 9c875e4137b4538fe4a0a2c39d56fb92c6610abe6bcc631f06d0d6472b0858880980e6685fd0336622fa435b781cbcbb0d42982875680915b43c8323b4740d70
-> % rails c
Running via Spring preloader in process 15116
Loading development environment (Rails 6.0.0)
[1] pry(main)> Rails.application.credentials.dig(:aws, :access_key_id)
=> nil

### Expected behavior

Rails.application.credentials.dig(:aws, :access_key_id)
=> 12345ABCDEF123345BCDEFD

### Actual behavior

[1] pry(main)> Rails.application.credentials.dig(:aws, :access_key_id)
=> nil

### System configuration
Rails 6.0.0

**Ruby version**:
Ruby 2.6.2

Why is that using the rails credentials:edit does not save the credentials? All I get is nil for the keys I save. There is a config/master.key. Seems like I am better off reverting to using ENV variables which defeats the purpose the new credentials operations. What to do to get this working?

**Comment by abhaynikam** [comment]
@resistorsoftware : I am able to edit the credentials on Rails 6.0 and dig it as well. Works as expected for me on Rails 6.0. Maybe try using an editor to edit the credentials

```
EDITOR="nano" bin/rails credentials:edit
```

**Comment by resistorsoftware** [comment]
@abhaynikam 

Thanks for that. I used vim instead of nano, and it worked. So now my question is, how do people use something like VSCode to accomplish the same? 

When I use the command rails credentials:edit, VSCode kicks in and shows me an empty file to edit. 

There must be a simple way to use VSCode without trouble?

**Comment by abhaynikam** [comment]
I did a quick google search and found this(https://www.dailysmarty.com/posts/command-for-opening-rails-encrypted-credentials-in-vs-code) for VSCode but I haven't used VSCode for editing credentials. Maybe somebody else could help you in that. Thanks 😊 

```
EDITOR='code --wait' rails credentials:edit
```

**Comment by resistorsoftware** [comment]
Interesting. When I tried that before, it failed, but trying it again now, it worked. OK... closing the issue. Thanks
