### ISSUE TITLE
Segmentation Fault on gem pg with ruby 2.4.3 and rails 5.0.2

### ISSUE THREAD

**Issue by ChunAllen** [rails/rails#37433]
### Steps to reproduce
I'm currently using `ruby 2.4.3` and `rails 5.0.2` and `gem pg, '0.21.0'`
and I'm getting Segmentation Fault when running rake db:migrate 

I installed ruby using rvm 

### Expected behavior
There should be no problem when running `rake db: migrate`

### Actual behavior
```
deploy:migrating
      ~/.rvm/bin/rvm 2.3.4@sample_app do bundle exec rake db:migrate
      /srv/www/sample_app/shared/bundle/ruby/2.3.0/gems/pg-0.21.0/lib/pg.rb:56: [BUG] Segmentation fault at 0x00000000000000
      01 ruby 2.3.4p301 (2017-03-30 revision 58214) [x86_64-linux]
```

### System configuration
**Rails 5.0.2**:

**Ruby 2.4.3**:

**Comment by rdavis0** [comment]
@ChunAllen I'm also having this issue. Did you find a solution?

**Comment by ChunAllen** [comment]
@rdavis0 I just upgraded my rails and ruby version
