### ISSUE TITLE
ApplicationController.render doesn't render erb templates

### ISSUE THREAD

**Issue by majksner** [rails/rails#37436]
### Steps to reproduce
1. Create file test.erb in root of your Rails project with content `<%= @foo %>`
2. Run `rails c`
3.  Paste `ApplicationController.render(assigns: {foo: 'bar'}, file: Rails.root + 'test.erb', layout: false)` in console

### Expected behavior
`=> "bar\n"`

### Actual behavior
`=> "<%= @foo %>\n"`

### System configuration
**Rails version**: 6.0

**Ruby version**: 2.6.5

Note that using `inline` works fine:

```
[14] pry(main)> ApplicationController.render(assigns: {foo: 'bar'}, inline: '<%= @foo %>')
  Rendering inline template
  Rendered inline template (Duration: 0.3ms | Allocations: 77)
=> "bar"
```

P.S. Same code works fine with Rails 5.2.3 and Ruby 2.6.5

**Comment by joshmn** [comment]
What happens if you omit the extension?

`ApplicationController.render(assigns: {foo: 'bar'}, file: Rails.root + 'test', layout: false)`

**Comment by majksner** [comment]
It works without extension.
