### ISSUE TITLE
Rails 6.0.0: image_tag fails with: "Can't resolve image into URL"

### ISSUE THREAD

**Issue by john-999** [rails/rails#37459]
File available:
```/assets/images/my_picture.jpg```

In view:
```<%= image_tag('my_picture.jpg') %>```

Leads to error message: 
```Can't resolve image into URL: undefined method `start_with?' for /flags\/flag\d\d(?:_semi)?\.png$/:Regexp```

With trace:
```actionview (6.0.0) lib/action_view/helpers/asset_tag_helper.rb:457:in `rescue in resolve_image_source'
actionview (6.0.0) lib/action_view/helpers/asset_tag_helper.rb:450:in `resolve_image_source'
actionview (6.0.0) lib/action_view/helpers/asset_tag_helper.rb:345:in `image_tag' ```

With system configuration:
- Rails: ```6.0.0```
- Ruby: ```ruby 2.6.3p62 (2019-04-16 revision 67580)```

**Comment by maschiner** [comment]
The issue has been fixed in the `world-flags` gem:
https://github.com/kristianmandrup/world-flags/commit/1cbd22abc322f10acadfad865015dbf4bac2f7ba

Adding `gem 'world-flags', github: 'kristianmandrup/world-flags', branch: 'master'` to the Gemfile fixed it for me.

**Comment by john-999** [comment]
Awesome, you're a life saver! Thank you so much!

**Comment by HungOm** [comment]
@maschiner Can you please explain what is the root cause and what exactly the `world-flags` does to resolves it? Thanks

**Comment by pavanshriffle007** [comment]
@maschiner please explain it?

**Comment by istana** [comment]
you can't add regexp to precompile list, but have to add each item separately
