### ISSUE TITLE
has_many with conditions not saving nested associations (rails 6)

### ISSUE THREAD

**Issue by owen2345** [rails/rails#37495]
### Steps to reproduce
```
class ArticleAttribute < ApplicationRecord
  has_many :options, -> { order(position: :asc) }, as: :owner, dependent: :destroy
  accepts_nested_attributes_for :options, allow_destroy: true
end

class Option < ApplicationRecord 
  belongs_to :owner, polymorphic: true
end

attr = ArticleAttribute.create(name: 'test', options_attributes: [{name: 'option1'}])
```

### Expected behavior
```attr``` must be saved

### Actual behavior
```attr``` is not saved because owner is required "Options owner must exist".
By removing the condition ```order(position: :asc)``` from ```has_many :options``` it works well.

### System configuration
**Rails version**: 6.0.0

**Ruby version**: 2.6.3

**Comment by wonda-tea-coffee** [comment]
It seems that inverse_name could not be solved by the following conditions.

https://github.com/rails/rails/blob/6-0-stable/activerecord/lib/active_record/reflection.rb#L651

Commit on addition (2 Mar 2013):
https://github.com/rails/rails/commit/26d19b4661f3d89a075b5f05d926c578ff0c730f#diff-1663e5f930ac83fef235d7e2aa5edf65R462

According to the comment for that method:

```
Anything with a scope can additionally ruin our attempt at finding an inverse, so we exclude reflections with scopes.
```

It seems.
I don't understand the detailed intention ... 🙏

**Comment by owen2345** [comment]
Fixed using :inverse_of
