### ISSUE TITLE
Firefox can cause an exception to be thrown with http basic authentication

### ISSUE THREAD

**Issue by dhh** [rails/rails#37506]
It seems like Firefox will send a malformed encoded Authorization header if you don't fill in username/password on the prompt. The header can look like this `Authorization: Basic YTo=`, which in turn produces this failure when we secure_compare:

<img width="1029" alt="Screen Shot 2019-10-18 at 4 13 32 PM" src="https://user-images.githubusercontent.com/2741/67133628-89d68e80-f1c2-11e9-951e-f8a5c3cddf9f.png">

This doesn't seem to happen with Safari and Chrome.

**Comment by louim** [comment]
Hey!
I tried with Firefox `69.0.3` and `70.0`, but I was not able to reproduce the issue.

Here is what I tried:
`gem 'rails', '~> 6.0.0'`
and
`gem 'rails', github: 'rails/rails'`

I was running ruby `2.6.4`

```
class ApplicationController < ActionController::Base
  http_basic_authenticate_with name: "user", password: "password"
end
```
I tried both empty fields
```
Authorization: Basic Og==
# which decodes to `:`
```
 and
```
Authorization: Basic YTo=
# which decodes to `a:`
```

Maybe there is something else that I didn't take into account?

**Comment by dhh** [comment]
Thanks for attempting to reproduce. I’ll verify what my details were on this happening. It’s possible that this was either on a prerelease Firefox or on the dev version. Maybe they just have a temporary bug. Will confirm.
