### ISSUE TITLE
uninitialized constant ActionView::Template::SyntaxErrorInTemplate

### ISSUE THREAD

**Issue by ccasabona** [rails/rails#37512]
### Steps to reproduce
Accidentally enter a conditional in an erb view statement as an expression (note the = sign before the if):

```
<%= if @instance.errors.any? do %>
  <%= tag.h2 'Error' %>
<% end %>
```
### Expected behavior
I'm not sure what should happen.  I've had occasion to do this in previous versions of rails, and I don't recall getting this uninitialized constant error.

### Actual behavior
ActionView::Template::Error: uninitialized constant ActionView::Template::SyntaxErrorInTemplate
Did you mean?  ActionView::SyntaxErrorInTemplate

see lib/action_view/template.rb line 346

### System configuration
Rails 6.0.0

**Ruby version**:
2.6.5

**Comment by chiastolite** [comment]
It looks a little mistake.

```diff
-<%= if @instance.errors.any? do %>
+<% if @instance.errors.any? %>
   <%= tag.h2 'Error' %>
 <% end %>
```

How about this?

**Comment by ccasabona** [comment]
You are quite right, there is a mistake in the view code, and thank you for help making this clear to to others who read this post.  

The point of making this issue was to show was that when this basic mistake is made, the uninitialized constant error message returned by Rails 6 seems to indicate another problem in the Rails code.

**Comment by jonathanhefner** [comment]
I tried to reproduce that exact error, but instead I got the expected error: `ActionView::SyntaxErrorInTemplate (Encountered a syntax error while rendering template: check ...`

Can you post a minimal app that reproduces the issue?

**Comment by ccasabona** [comment]
Thank you for trying to reproduce this error.  

On a new rails 6 app, I discovered that you need to add the better_errors gem to get this uninitialized constant error.  I will open an issue there.

**Comment by obromios** [comment]
I am seeing the same puzzling error message with this mistake
`<%= javascript_pack_tag 'application''data-turbolinks-track': 'reload' %>	`
i.e. just leaving out comma between 'application' and 'data-turbolinks-track'

**Comment by eugeneius** [comment]
This problem is already fixed on master, I've opened https://github.com/rails/rails/pull/38065 to backport it to 6-0-stable.
