### ISSUE TITLE
Inline ActiveJob clears `CurrentAttributes` erroneously

### ISSUE THREAD

**Issue by jpcody** [rails/rails#37526]
### Steps to reproduce

1. Set a value during seeding in a class that inherits from `ActiveSupport::CurrentAttributes`
2. Run code that enqueues a job via `ActiveJob` (e.g. uploading a file via `ActiveStorage`)
3. Note that the value from step 1 is cleared

Because the database is [seeded with the inline adapter](https://github.com/rails/rails/pull/34953), jobs run inline in seeding. When the job is run, the executor [resets all current attributes](https://github.com/rails/rails/blob/master/activesupport/lib/active_support/railtie.rb#L23). Here's [a commit](https://github.com/jpcody/activejob-currentattributes/commit/4363b36277950bc79a06ff2dfa0142ed91eee4bd) that exhibits the issue.

In my app, I'm iterating over customers and seeding a logo for each then seeding users for each. The iteration uses `Current.set(customer: customer) { yield }`, and within the yield we attach a logo. After that logo is attached, `Current.customer` is reset to nil because `ActiveStorage::AnalyzeJob.perform_later(self)` runs .

### Expected behavior
Jobs run inline should not clear `CurrentAttributes`.

### Actual behavior
`CurrentAttributes` are cleared.

### System configuration
**Rails version**: Rails 6.0.0
**Ruby version**: ruby 2.6.5p114

**Comment by kaspth** [comment]
The inline adapter part is working as expected. We want it to clear values so it works like an async job would in production.

What seems to be the problem here is that the seed file’s current values are cleared due to the inline adapter running in the same thread.

Maybe the inline adapter could use something like Thread.new.join instead? cc @gmcgibbon

**Comment by gmcgibbon** [comment]
This way inline jobs essentially have their own `Thread.current` right? That seems like a good idea to me.
