### ISSUE TITLE
Upgrade ruby on rails application

### ISSUE THREAD

**Issue by florent6001** [rails/rails#37527]
Hi,

I have build a Rails application with Ruby 2.6.3. I have change my computer and i'm now on ruby 2.6.4 and i can't make work my application.

I have an error telling me my Ruby Version is not available on "bundle install" and when i try to launch the server using "rails s" i have this error : cannot load such file mysql2. I tryied "gem install mysql2" that telling me i have to install mysql2.X.X with the command -v 2.X.X. And when i do it it's telling me the same things, i can't install it anyway.

I hope someone can help me.

### System configuration
**Rails version**: 6.0.0

**Ruby version**: 2.6.4

Thank you

**Comment by arunagw** [comment]
Please use the [mailing list](https://groups.google.com/forum/#!forum/rubyonrails-talk) or StackOverflow for questions/help, where a wider community will be able to help you. We reserve the issues tracker for issues only. Thanks.
