### ISSUE TITLE
ActiveSupport::TaggedLogging does not persist context in a Fiber

### ISSUE THREAD

**Issue by rafadc** [rails/rails#37535]
### Steps to reproduce
In a new Rails application in the console just type:

```ruby
logger = ActiveSupport::TaggedLogging.new(Logger.new(STDOUT))
logger.tagged('TAG') { Fiber.new{logger.info 'Stuff'}.resume }
```

This is similar (but not equal) to: https://github.com/rails/rails/issues/28156 In that issue the conversation is around threads.

### Expected behavior
That should output:

```
[TAG] Stuff
```

### Actual behavior

The output is
```
Stuff
```

and the tags are lost

### Comments

The behaviour for threads is tested in: https://github.com/rails/rails/blob/v6.0.0/activesupport/test/tagged_logging_test.rb#L75-L84

but there is no information for Fibers. The current implementation does not pass the tags for threads (and probably it is not easy to do) but making it work for Fibers probably should be just changing this method https://github.com/rails/rails/blob/88fe8d9e7ca687f4253090bcc2c634595a19d203/activesupport/lib/active_support/tagged_logging.rb#L51-L55 to use `Thread.current.current_variable_set` and `Thread.current.current_variable_get`instead because:

```ruby
Thread.current[:fiber_local_var] = 'Result'
Fiber.new do
  puts Thread.current[:fiber_local_var]
end.resume
# => <Empty output>

Thread.current.thread_variable_set(:thread_local_var, 'Result')
Fiber.new do
  puts Thread.current.thread_variable_get(:thread_local_var)
end.resume
# => "Result"
```

I can create the PR myself but I'd first love to know if what I am saying makes sense or you explicitly don't want this to work for Fibers. In such case I can PR a test that intentionally excludes  Fibers so it is explicit. 

### System configuration
**Rails version**: 6.0.0

**Ruby version**: 2.6.2p47

Thanks a lot!

**Comment by rafadc** [comment]
The issue is still relevant in Rails 6.0.2.1

**Comment by leehambley** [comment]
The issue is still relevant in 6.0.2.2
