### ISSUE TITLE
has_one where statement generates incorrect sql

### ISSUE THREAD

**Issue by benjaminwood** [rails/rails#37531]
### Steps to reproduce
```ruby
require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  gem "rails", github: 'rails/rails'
  gem "sqlite3"
end

require "active_record"
require "minitest/autorun"
require "logger"

# This connection will do for database-independent bug reports.
ActiveRecord::Base.establish_connection(adapter: "sqlite3", database: ":memory:")
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :posts, force: true do |t|
  end

  create_table :comments, force: true do |t|
    t.integer :post_id
  end
end

class Post < ActiveRecord::Base
  has_one :comment
end

class Comment < ActiveRecord::Base
  belongs_to :post
end

class BugTest < Minitest::Test
  def test_association_stuff
    assert_equal Post.where(comment: 123).to_sql, 'SELECT "posts".* FROM "posts" WHERE "posts"."comment" = 123'
  end
end
```

### Expected behavior
While the `where` statement is not expected to produce sql that will scope posts by comment_id, it is expected that AR would do something other than silently generate sql that is incorrect but does not result in a sql error.

Consider the following statement:

```ruby
Post.where(abc: 123).to_sql
```

Results in

```sql
SELECT "posts".* FROM "posts" WHERE "posts"."abc" = 123
```

But when executed would result in a `sql` error `no such column: posts.abc`.

It is expected that `Post.where(comment: 123).to_sql` would result in:

```sql
SELECT "posts".* FROM "posts" WHERE "posts"."comment" = 123
```

### Actual behavior

At master, the generated sql is:

```sql
SELECT "posts".* FROM "posts" WHERE "posts"."id" = 123
```

Somehow the result is that the post.id is 123, which is incorrect. This will not result in a sql error, potentially allowing a bug to exist which causes the query to return incorrect results without warning.

### System configuration
**Rails version**: Variations of this bug have occurred from Rails 3.2 -> master

**Ruby version**: 2.6

**Comment by benjaminwood** [comment]
This is still reproducible on the master branch, I confirmed today using the code I shared above :point_up:

**Comment by AHBruns** [comment]
I am still able to reproduce this bug. I've shared details as well as a reproduction repo in this rails-talk post: https://discuss.rubyonrails.org/t/is-there-a-bug-with-where-on-polymorphic-has-one-associations/79680/3
