### ISSUE TITLE
Force isn't working for generators

### ISSUE THREAD

**Issue by danielthesoto** [rails/rails#37538]
### Steps to reproduce

`rails g model User name`

`rails g model User name age -f` 

Says

> The name 'User' is either already used in your application or reserved by Ruby on Rails. Please choose an alternative and run this generator again.

### Expected behavior

Allows me to overwrite the existing generated.

### Actual behavior

Not letting me use the `force` option.

### System configuration
**Rails version**: 6.0.0

**Ruby version**: 2.5.3

**Comment by joshmn** [comment]
Fixed by #37404
