### ISSUE TITLE
restrict_with_exception/restrict_with_error fail if related record is already destroyed

### ISSUE THREAD

**Issue by fsateler** [rails/rails#37536]
### Steps to reproduce

```ruby
class User < ApplicationRecord
  belongs_to :permission_role, inverse_of: :user, optional: true

  after_destroy do
    permission_role.destroy!
  end
end

class PermissionRole < ApplicationRecord
  has_one :user, inverse_of: :permission_role, dependent: :restrict_with_exception
end


 permission_role = create(:permission_role)
 user = create(:normal_user, permission_role: permission_role, person_id: nil)

 user.destroy
 permission_role.destroy # => Raises ActiveRecord::DeleteRestrictionError
```

### Expected behavior

Because the related user is already destroyed, `restrict_with_exception` should allow the destroy to go through.

Similar thing happens with `restrict_with_error`, but one needs to check if the record was destroyed (it isn't). 

### Actual behavior

The destroy was not allowed because a related record existed, even if that record was already destroyed.

### System configuration
**Rails version**: 5.1.7

I have checked the code has not changed in master. I will repro it there ASAP.

**Ruby version**: 2.5

**Comment by fsateler** [comment]
Reproduced with versions 6.0.0 and git master (d775176d3a20). The problem is still there.

**Comment by fsateler** [comment]
I have reproduced the error with commit f78fb42b51c2226b5e87d5c637604f1d85b68b14

**Comment by fsateler** [comment]
I have updated the reproduction case. The actually failing line is the one destroying the `permission_role`, not the user.


I have verified this against 41758964e9515ae879fce0be687da2f5953bc950 and latest rails 6.0 as published on rubygems.

**Comment by yoon** [comment]
@fsateler Why there is there an `after_destroy` in `User`? Wouldn't that mean that `permission_role` gets destroyed when you destroy `user`?

**Comment by fsateler** [comment]
Yes, that is the idea. While the specific example was only for testing purposes, my use case is a 1-1 relation. If any of the sides of the relation is destroyed, the other must be destroyed as well.

**Comment by dmitry** [comment]
@fsateler have you found a solution for this specific issue?
