### ISSUE TITLE
Db:migrate fails when when we are modifying both schema & data in an environment with DB replication

### ISSUE THREAD

**Issue by knagode** [rails/rails#37546]
### Steps to reproduce
  - [Configure primary & follower database in yml file](https://github.com/knagode/app_with_replication/blob/master/config/database.yml)
  - [Setup reading & writing roles for a model](https://github.com/knagode/app_with_replication/blob/master/app/models/my_model.rb)
  - [Run a migration which is changing DB schema and then modifying some data on a model which is using replication](https://github.com/knagode/app_with_replication/blob/master/db/migrate/20191023135623_failing_migration.rb)

### Expected behavior
2 step migration (STEP 1 = schema modification, STEP 2 = data modification) should be processed and completed without failures

### Actual behavior

STEP 1 (schema modification): Each migration wraps itself inside DB transaction using default DB connection. Since we are modifying DB schema - operations which are changing data from other DB connections will be on hold until migration (transaction) is completed. 

STEP 2 (data modification) Since we are trying to run a write query on a model which is using connection roles new DB connection will be opened however database will not execute this query before previous transaction is completed. This results in a deadlock (or timeout). 

When I am inspecting  DB connection using `select *from pg_stat_activity`. I see that the following query is being on hold: 

```
SELECT a.attname, format_type(a.atttypid, a.atttypmod),
       pg_get_expr(d.adbin, d.adrelid), a.attnotnull, a.atttypid, a.atttypmod,
       c.collname, col_description(a.attrelid, a.attnum) AS comment
  FROM pg_attribute a
  LEFT JOIN pg_attrdef d ON a.attrelid = d.adrelid AND a.attnum = d.adnum
  LEFT JOIN pg_type t ON a.atttypid = t.oid
  LEFT JOIN pg_collation c ON a.attcollation = c.oid AND a.attcollation <> t.typcollation
 WHERE a.attrelid = '"my_models"'::regclass
   AND a.attnum > 0 AND NOT a.attisdropped
 ORDER BY a.attnum
```

I think the root of evil lies in a fact that Rails is opening multiple connections to the `:primary` database. 

While debugging this issue I also got concerned about number of connections to the `:primary`
 database on production servers. Queries which do not need replication (we are OK with using `:primary` database) are using another connection than queries on which we specifically require `:primary` database using `role: :writing`). 

I wanted to use the replication because it would offload the most expensive select query from `:primary` database to `follower` database. In one specific case I need to execute a query on another connection but this is opening up so strange questions. I expect that anybody who needs DB replication has same expectations as me - this should and could be a simple task.   

Problem disappears with removing `connects_to database: { writing: :primary, reading: :follower }` from the model. 

### System configuration
**Rails version**: 6.0

**Ruby version**: ruby 2.6.1

**Comment by eileencodes** [comment]
Hey @knagode thanks for opening this issue and providing a test application. It made it a lot easier to figure out what was wrong.

The underlying issue is your `connects_to` is in the wrong place. As noted [in the guides](https://guides.rubyonrails.org/active_record_multiple_databases.html) it needs to be in the abstract class, not the underlying models otherwise you'll end up with duplicate connections. I've pushed a PR to your repo to demonstrate. Once I moved the connection code the migration ran fine.

**Comment by knagode** [comment]
Thanks @eileencodes. I thought this is not important if there is only one model in the schema. 

Your hint helped me figure out the issue in live project too! 

In my case: some models were extending `ActiveRecord::Base` but I thought this is not important as those Models were not meant to use replication database. I fixed this everywhere and now I don't have problems anymore ..
