### ISSUE TITLE
Cache key with alias attribute

### ISSUE THREAD

**Issue by xyingsoft** [rails/rails#37554]
### Steps to reproduce
Steps to reproduce
I a simple model

```
class Movie < ActiveRecord::Base
  alias_attribute :updated_at, :modified_date
  alias_attribute :created_at, :create_date
end
```
### Expected behavior
```
movie = Playback.new
movie.modified_date = Time.zone.now
movie.cache_key
# expected `movies/1-xxxxxxxxx`, but got `movies/1`
```
It should include `modified_date` in cache_key

### Actual behavior
It doesn't include the modified_date into the cache_key

### System configuration
**Rails version**:
6.0.0rc2
**Ruby version**:
2.6.1

**Comment by georgeclaghorn** [comment]
Cache keys don’t include timestamps by default since [recyclable cache keys](https://github.com/rails/rails/pull/29092). Is `modified_date` reflected in `movie.cache_version` or `movie.cache_key_with_version`?
