### ISSUE TITLE
Active Storage in production, set to :amazon key, has bad YAML in storage.yml

### ISSUE THREAD

**Issue by resistorsoftware** [rails/rails#37550]
Used the rails task credentials:edit and credentials:show to ensure the credentials are set properly so that we can use the Rails.application.credentials methods.

### Steps to reproduce

Upload to Heroku. At the step *heroku.detecting.config.for.active_storage.service=amazon*
the output stops on an error reading the storage.yml file. Says the YAML is not formatted correctly. It seems correct with no tabs, no extra spaces, just data that it should have.

    amazon:
      service: S3
        access_key_id: <%= Rails.application.credentials.dig(:aws, :access_key_id) %>
        secret_access_key: <%= Rails.application.credentials.dig(:aws, :secret_access_key) %>
        region: <%= Rails.application.credentials.dig(:aws, :region) %>
        bucket: <%= Rails.application.credentials.dig(:aws, :bucket) %>

### Expected behavior

Rails App should get credentials from the credentials file, and active storage should be able to deal with storage.yml fine in production

### Actual behavior

Boot process dies complaining that storage.yml is not good yaml. First key after service: S3 is the culprit, meaning the Rails.application.credentials dig probably failed? Odd as the credentials:show task shows them as all being set fine.

### System configuration
**Rails version**:  6.0.0

**Ruby version**:  2.6.5

**Comment by georgeclaghorn** [comment]
The keys after `service` are all indented one level too deep in your example. Does fixing that help?

**Comment by resistorsoftware** [comment]
Yes! Thanks!
