### ISSUE TITLE
6.0.0 rake db:drop RAILS_ENV=development ignores the environment

### ISSUE THREAD

**Issue by krtschmr** [rails/rails#37559]
```
 rake db:drop RAILS_ENV=development
Dropped database 'db_development'
Dropped database 'db_test'
```

### Expected behavior
Only drop db_development

### Actual behavior
dropped both

### System configuration
6.0.0 + 2.6.3

**Comment by eugeneius** [comment]
This is intentional behaviour; see https://github.com/rails/rails/issues/27299.

**Comment by ioquatix** [comment]
This is a scary default behaviour.
