### ISSUE TITLE
Errno::ENOENT: No such file or directory - osascript

### ISSUE THREAD

**Issue by saydulk** [rails/rails#37567]
I have a Rails app which i am trying to deploy in Ubuntu 18.04 LTS Linux. 'bundle install' run ok but when I run 'bundle exec rake secret' it shows Errno::ENOENT: No such file or directory - osascript

myappuser@ubuntu:/var/www/myapp/code$ bundle exec rake secret
rake aborted!
Errno::ENOENT: No such file or directory - osascript
/home/myappuser/.rvm/gems/ruby-2.5.0/gems/webconsole-0.2.1/lib/webconsole/lib/module.rb:95:in ``'
/home/myappuser/.rvm/gems/ruby-2.5.0/gems/webconsole-0.2.1/lib/webconsole/lib/module.rb:95:in `run_applescript'
/home/myappuser/.rvm/gems/ruby-2.5.0/gems/webconsole-0.2.1/lib/webconsole/lib/module.rb:10:in `application_exists'
/home/myappuser/.rvm/gems/ruby-2.5.0/gems/webconsole-0.2.1/lib/webconsole.rb:9:in `<top (required)>'
/var/www/myapp/code/config/application.rb:7:in `<top (required)>'
/var/www/myapp/code/Rakefile:5:in `require'
/var/www/myapp/code/Rakefile:5:in `<top (required)>'
/home/myappuser/.rvm/gems/ruby-2.5.0/bin/ruby_executable_hooks:24:in `eval'
/home/myappuser/.rvm/gems/ruby-2.5.0/bin/ruby_executable_hooks:24:in `<main>'
(See full trace by running task with --trace)

### System configuration
**Rails version**:
Rails 4.2.11.1

**Ruby version**:
ruby 2.5.0p0 (2017-12-25 revision 61468) [x86_64-linux]

Need help

**Comment by y-yagi** [comment]
Please use the [mailing list](https://groups.google.com/forum/#!forum/rubyonrails-talk) or StackOverflow for questions/help, where a wider community will be able to help you. We reserve the issues tracker for issues only. Thanks.
