### ISSUE TITLE
Jbuilder doesn't compile when url has queries in Rails 6

### ISSUE THREAD

**Issue by modusss** [rails/rails#37577]
### Steps to reproduce

1) create rails app with ruby 2.6.5 and rails 6.0.0

> rails new todo

2) 

> rails g scaffold Todo task:string

3) 

> rails db:migrate

4) adding jquery:

4.1) yarn add jquery
4.2) add on environments.js:

```
 const webpack = require('webpack')
 environment.plugins.prepend('Provide',
   new webpack.ProvidePlugin({
     $: 'jquery/src/jquery',
     jQuery: 'jquery/src/jquery'
   })
 )

```
5) create the first task
6) Go to "/todos/1"
7)  Type on browser console:

```
 $.ajax({
   url: window.location.href + ".json",
   dataType: 'json',
   async: false
 });
```

You get the json response:
![image](https://user-images.githubusercontent.com/20300214/67679329-9a77c900-f967-11e9-991c-046afb800bf8.png)

> Started GET "/todos/1.json" for ::1 at 2019-10-28 13:55:54 -0300
> Processing by TodosController#show as JSON
>   Parameters: {"id"=>"1"}
>   Todo Load (0.3ms)  SELECT "todos".* FROM "todos" WHERE "todos"."id" = ? LIMIT ?  [["id", 1], ["LIMIT", 1]]
>   ↳ app/controllers/todos_controller.rb:67:in `set_todo'
>   Rendering todos/show.json.jbuilder
>   Rendered todos/_todo.json.jbuilder (Duration: 1.0ms | Allocations: 125)
>   Rendered todos/show.json.jbuilder (Duration: 2.2ms | Allocations: 306)
> Completed 200 OK in 10ms (Views: 3.9ms | ActiveRecord: 0.3ms | Allocations: 1565)

Now you just change the url to "/todos/1?q=foo", refresh the page and try to see the json response:

![image](https://user-images.githubusercontent.com/20300214/67679372-b0858980-f967-11e9-8354-756de6e31d04.png)

> Started GET "/todos/1?q=foo.json" for ::1 at 2019-10-28 13:55:44 -0300
> Processing by TodosController#show as JSON
>   Parameters: {"q"=>"foo.json", "id"=>"1"}
>   Todo Load (0.2ms)  SELECT "todos".* FROM "todos" WHERE "todos"."id" = ? LIMIT ?  [["id", 1], ["LIMIT", 1]]
>   ↳ app/controllers/todos_controller.rb:67:in `set_todo'
>   Rendering todos/show.html.erb within layouts/application
>   Rendered todos/show.html.erb within layouts/application (Duration: 0.7ms | Allocations: 89)
> Completed 200 OK in 25ms (Views: 21.3ms | ActiveRecord: 0.2ms | Allocations: 6547)

### Expected behavior
Show the json response even when url has queries "/todos/1?q=foo"

from:

**show.json.jbuilder**
json.partial! "todos/todo", todo: @todorails db:migrate

### Actual behavior
No response data from Rails 6.0.0 and this bug doesn't exist in rails 5.2.3 and ruby 2.4.5

### System configuration
Rails 6.0.0
Ruby 2.6.5

**Comment by ryanb** [comment]
I ran into this too. If the JSON request is through the `Accept: application/json` header Rails 6 doesn't appear to select the proper template. The `resond_to` call is necessary, but you can use the shorthand without the block.

```
respond_to :html, :json
```

Calling this at the controller level did not work for me so it needs to be called in each action.

**Comment by route** [comment]
@rafaelfranca this is still an issue for latest Rails 6.0.3.2, why was it closed?

**Comment by route** [comment]
All good, this was fixed by https://github.com/rails/rails/pull/37557
