### ISSUE TITLE
2.7.0-preview2 triggers 'TypeError: no implicit conversion of nil into String'

### ISSUE THREAD

**Issue by jasnow** [rails/rails#37572]
### Steps to reproduce

 1. Clone https://github.com/jasnow/Practice-Git-with-Rails5edge
 2. Run "cd Practice-Git-with-Rails5edge"
 3. Add .rvmrc as "rvm use 2.7.0-preview1@ruby2.7-rails6.1 --create"
 4. Run "cd ..; cd Practice-Git-with-Rails5edge" to set .rvmrc.
 5. Run "rake" to see it runs cleanly.

 6. Changed .rvmrc to "rvm use 2.7.0-preview2@ruby2.7-rails6.1 --create"
 7. Run "cd ..; cd Practice-Git-with-Rails5edge" to set .rvmrc.
 8. Run "rake" to see issue. For more details, see gist:
    * https://gist.github.com/jasnow/733a7824b9d9927e8596db3fa5258a35
      * 71 lines associated with rails-54f3e6717224 gem
      *  2 lines associated with tzinfo-1.2.5 gem (warnings)
Hope this helps.

### Expected behavior

See step 5 above to pre-2.7.0-preview2 "rake" behavior.

### Actual behavior

See step 8 above for 2.7.0preview2 "rake" behavior.

### System configuration

**Rails version**: 6.1.0.alpha

**Ruby version**: ruby 2.7.0preview2 (2019-10-22 master 02aadf1032) [x86_64-darwin16]

**Comment by eugeneius** [comment]
This should be fixed by https://github.com/rails/rails/pull/37504. Could you try that branch?

**Comment by jasnow** [comment]
@eugeneius - Changed Gemfile to 
```
gem 'rails', git: 'https://github.com/utilum/rails', branch: 'no_implicit_conversion_of_nil'
```
and above errors went away. Thanks.

**Comment by eugeneius** [comment]
It looks like this error will be downgraded to a warning for Ruby 2.7: https://github.com/ruby/ruby/pull/2637

I left a comment on https://github.com/rails/rails/pull/37504 about one `match?` call that was missed.

**Comment by jasnow** [comment]
@eugeneius - I thought this needed to be fixed in the Rails code base #37504 ?

**Comment by eugeneius** [comment]
Rails will be fixed, but it's less urgent now that it's no longer an error. Please be patient 🙂

**Comment by jasnow** [comment]
Verified and you are welcome.

**Comment by jasnow** [comment]
Will Ruby 2.7.0+ work on Rails pre-6.1 projects?

**Comment by stanleeDK** [comment]
Hello,

Can you please remove Stan Lee from this repo. Is email is associated with
our domain but he no longer works here, so the updates are spamming our
support inbox. Thank you!

**Comment by jasnow** [comment]
@stanleeDK - I can't but you might be able to click on the unsubscribe link at the end of your previous post.
