### ISSUE TITLE
Artifact system test screenshot + buildkite doesn't use the right path

### ISSUE THREAD

**Issue by robotdana** [rails/rails#37584]
system test screenshots artifact output need to use the relative path rather than the absolute path.
(at least when using buildkite docker, this is possibly not generally true) 

I'm assuming buildkite is supported because the documentation directly mentions buildkite: 
> "display the screenshot in the terminal, using the terminal artifact format (buildkite.github.io/terminal-to-html/inline-images/)."

### Steps to reproduce

There's a lot of setup obviously, i don't even have a public buildkite to share unfortunately.

### Expected behavior

it shows the screenshot

### Actual behavior

buildkite's output shows 
```
[Image artifact '/app/tmp/screenshots/failures_blah_blah_blah.png' not found]
```

https://github.com/rails/rails/blob/master/actionpack/lib/action_dispatch/system_testing/test_helpers/screenshot_helper.rb#L113

changing the line `message << "\e]1338;url=artifact://#{absolute_image_path}\a\n"` to `              message << "\e]1338;url=artifact://#{image_path}\a\n"` works for me, but might not work in a general situation, perhaps this just needs more configurability so i don't have to override the whole of `ActionDispatch::SystemTesting::TestHelpers::ScreenshotHelper.display_image` in my app?

### System configuration
**Rails version**: I'm running 5.2.3 but the offending line is the same in master 

**Ruby version**: 2.5.1

**Comment by Edouard-chin** [comment]
FYI Buildkite also supports embedded iTerm-style images (what Rails calls "inline"). If you modify the RAILS_SYSTEM_TESTING_SCREENSHOT env var to be `inline` it should work. We use buildkite and we don't have issue displaying system test screenshot failures

**Comment by robotdana** [comment]
it does work (i’ve tried it) but buildkite recommends against it preferring artifact links, ideally it’d be customisable with a proc i’ll make a pr in a couple of days

**Comment by Edouard-chin** [comment]
> but buildkite recommends against it,

Good to know, thanks!
