### ISSUE TITLE
AS::Cache::Store fetch + block fails when constants are renamed

### ISSUE THREAD

**Issue by thegedge** [rails/rails#37580]
### Steps to reproduce
This was observed when removing some exceptional autoloading cases, so we were changing acronyms to be properly camel cased. Given the following scenario:

```ruby
class MyAPI; end

Rails.cache.fetch("some_key:#{id}") do
  find_my_api(id) # returns an instance of MyAPI
end
```

* Run the above code so that an instance associated with `MyAPI` is stored.
* Rename `MyAPI` → `MyApi`, restart server
* 💥 `uninitialized constant FooAPI (NameError)`

### Expected behavior
`NameError` is rescued during deserialization, and the result of the block to `fetch` (in the above example, `find_my_api(id)`) is computed and returned.

This allows an application to (more easily) degrade instead of fail. More generally, rescuing as much as possible from "poisoned" cache values seems like a desirable and expected property.

### Actual behavior
`NameError` is raised and bubbles up to the application

### System configuration
**Rails version**:
1811e841166198bf86ae6de18d0971df77b932b4

**Ruby version**:
2.6.5

**Comment by casperisfine** [comment]
cc @rafaelfranca

**Comment by thegedge** [comment]
One thing we realized: we're using https://github.com/Shopify/memcached_store/blob/0b2b0594ce0b5c669e076565cbc26c9c62d5d04f/lib/active_support/cache/memcached_store.rb#L271-L275

which doesn't rescue like the memcached store in AS:

https://github.com/rails/rails/blob/966d3a7bf2c08c5c20213d29686cbb409a07734a/activesupport/lib/active_support/cache/mem_cache_store.rb#L199

This may not be an issue. When I tried using `mem_cache_store` I ended up with something like this when changing the constant name:

```
DalliError (No server available): No server available
cache miss
DalliError (No server available): No server available
test
```

Note, the `DalliError` goes away if I use the constant name that has been stored in the cache, so it's a bit of a red herring.

Unless I'm missing something, this could simply be an issue that has been dealt with in AS but not in `Shopify/memcached_store`. Can close if we agree.
