### ISSUE TITLE
Action Text: Rich text field predicate form to check if not blank

### ISSUE THREAD

**Issue by rickychilcott** [rails/rails#37594]
### Steps to reproduce
1. Create application with actiontext
2. Create a model named `Information` with `has_rich_text :notes` 

### Expected behavior

Should be able to use the predicate form of the rich text field (i.e. `?`)

```ruby
class Information < ApplicationRecord
  has_rich_text :notes
end


i = Information.new
i.notes? # => Expect `false`

i.notes = "Some sample text"
i.notes? # => Expect `true`
```

### Actual behavior
```ruby
class Information < ApplicationRecord
  has_rich_text :notes
end

i = Information.new
i.notes?
```

Raises error:
```log
NoMethodError: undefined method `notes?' for #<Information:0x00007fb9c5141dc0>
Did you mean?  notes
               notes=
```

### System configuration
**Rails version**: 6.0

**Ruby version**: 2.6.3

I'm very happy to put in a PR, but want to make sure this is in line with expected ActionText behavior. I propose defining a method that would be something like this for `notes`:

```ruby
def notes?
  !notes.blank?
end
```

**Comment by t0yohei** [comment]
I think it works if you add the code below at this area.
https://github.com/rails/rails/blob/master/actiontext/lib/action_text/attribute.rb#L27
```
def #{name}?
  rich_text_#{name}.present?
end
```

I'm making a pull request.

**Comment by rickychilcott** [comment]
For sure @t0yohei! Thanks for hopping on this. I think we'll need a test for this too.
