### ISSUE TITLE
ActiveModel::Serializers::JSON#as_json BigDecimal changes

### ISSUE THREAD

**Issue by CGA1123** [rails/rails#37604]
#31503 affects not only timestamp fields but also any fields that are cast to `BigDecimal` (and perhaps others).

I _don't_ think this is a bug, it makes sense (as per the original PR description) that
`object.as_json == JSON.parse(object.to_json)`

However, it would be good to point out that this change does not impact only timestamps 😄

Not sure if it worth editing the changelog or having this issue being searchable is enough.

### Steps to reproduce
`RAILS_VERSION=5.2.3 ruby ar_test.rb # passes`
`RAILS_VERSION=6.0.0 ruby ar_test.rb # fails`

```ruby
# File: ar_test.rb
# frozen_string_literal: true

require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  # Activate the gem you are reporting the issue against.
  gem "activerecord", ENV['RAILS_VERSION']
  gem "sqlite3"
end

require "active_record"
require "minitest/autorun"
require "logger"

# This connection will do for database-independent bug reports.
ActiveRecord::Base.establish_connection(adapter: "sqlite3", database: ":memory:")
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :posts, force: true do |t|
    t.decimal :price
  end
end

class Post < ActiveRecord::Base; end

class BugTest < Minitest::Test
  def test_as_json_big_decimal
    post = Post.new(price: 1)
    price_as_json = post.as_json.fetch('price')

    assert_equal price_as_json.class, BigDecimal
  end
end
```

### System configuration
**Rails version**: 5.2.3 / 6.0.0

**Ruby version**: ruby 2.6.3p62

**Comment by mounab** [comment]
I'm facing the same problem after upgrading to rails 6.0.3.1, is there a why to rollback the old behavior ?? HELP

**Comment by SamiDghim** [comment]
i have the same issue with rails 6.0.3.1, help me please any news ? @mounab

**Comment by seifeddinhaj** [comment]
same shitt for me i think it's related  to `as_json` any news @mounab ??

**Comment by rassas** [comment]
i had the same issue, so i declared a method `as_json_5_2` in `ApplicationRecord` class, and called it instead of `as_json`

```
# app/models/application_record.rb

  def as_json_5_2(options = nil)
    root = if options && options.key?(:root)
      options[:root]
    else
      include_root_in_json
    end
    if root
      root = model_name.element if root == true
      { root => serializable_hash(options) }
    else
      serializable_hash(options)
    end
  end
```
