### ISSUE TITLE
Initial setup of Mandrill for Action Mailbox requires a specific token

### ISSUE THREAD

**Issue by cromulus** [rails/rails#37609]
### Steps to reproduce
Create a brand new rails install, and configure action mailbox to use mandrill.
Specify a secure mandrill_ingress_api_token, and deploy to a public URL. Mandrill will not be able to create the inbound email unless you configure your token to be "test-webhook".

### Expected behavior
I expect the process of creating a new mandrill inbound route from the mandrill api to be seamless. I should be able to create a new route and the rails app should respond to mandrill's test web hook successfully so that we can proceed to configure the inbound web hook.

### Actual behavior
Mandrill makes a request to the endpoint to validate that it a) exists, b) is secured with https, and b) that it validates signatures correctly. In order to do this, it signs this first request with the same token "test-webhook".

What I *think* should occur is that if we receive a web hook that validates against the token "test-webhook",  rails should consider it a no-op, and return 200, such that the inbound email can be created on the mandrill side.

### System configuration
Rails: 6.0.0
Ruby: 2.6.5

**Comment by andreibondarev** [comment]
@cromulus Thank you for this! Just spent 4 hours debugging this...

**Comment by cromulus** [comment]
Additionally, Mandrill makes a HEAD request that 404's to 
`/rails/action_mailbox/mandrill/inbound_emails`

Might be a good idea to respond with a `200` just to be safe.
