### ISSUE TITLE
 Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory

### ISSUE THREAD

**Issue by medicharlachiranjeevi** [rails/rails#37611]
Hi please let me know any solution
RAILS_ENV=production bundle exec rake assets:precompile

### Expected behavior
It should compile asserts
### Actual behavior
Compiling…
Compilation failed:
FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory
 1: 0x7f8dce174568 node::Abort() [/usr/lib/x86_64-linux-gnu/libnode.so.64]
 2: 0x7f8dce1745b1  [/usr/lib/x86_64-linux-gnu/libnode.so.64]
 3: 0x7f8dce335d22 v8::Utils::ReportOOMFailure(v8::internal::Isolate*, char const*, bool) [/usr/lib/x86_64-linux-gnu/libnode.so.64]
 4: 0x7f8dce335f78 v8::internal::V8::FatalProcessOutOfMemory(v8::internal::Isolate*, char const*, bool) [/usr/lib/x86_64-linux-gnu/libnode.so.64]
 5: 0x7f8dce6b75f2  [/usr/lib/x86_64-linux-gnu/libnode.so.64]
 6: 0x7f8dce6c8023 v8::internal::Heap::PerformGarbageCollection(v8::internal::GarbageCollector, v8::GCCallbackFlags) [/usr/lib/x86_64-linux-gnu/libnode.so.64]
 7: 0x7f8dce6c8936 v8::internal::Heap::CollectGarbage(v8::internal::AllocationSpace, v8::internal::GarbageCollectionReason, v8::GCCallbackFlags) [/usr/lib/x86_64-linux-gnu/libnode.so.64]
 8: 0x7f8dce6cb07d v8::internal::Heap::AllocateRawWithLigthRetry(int, v8::internal::AllocationSpace, v8::internal::AllocationAlignment) [/usr/lib/x86_64-linux-gnu/libnode.so.64]
 9: 0x7f8dce6cb0d2 v8::internal::Heap::AllocateRawWithRetryOrFail(int, v8::internal::AllocationSpace, v8::internal::AllocationAlignment) [/usr/lib/x86_64-linux-gnu/libnode.so.64]
10: 0x7f8dce699a74 v8::internal::Factory::NewFillerObject(int, bool, v8::internal::AllocationSpace) [/usr/lib/x86_64-linux-gnu/libnode.so.64]
11: 0x7f8dce903ca5 v8::internal::Runtime_AllocateInNewSpace(int, v8::internal::Object**, v8::internal::Isolate*) [/usr/lib/x86_64-linux-gnu/libnode.so.64]
12: 0x164b9295452b 

### System configuration
**Rails version**:6.0.0

**Ruby version**:2.6.1

**Comment by mwallba** [comment]
Try running the task with:

`NODE_OPTIONS=--max_old_space_size=4096 RAILS_ENV=production bundle exec rake assets:precompile`

if that fails, make sure you don't have an infinite loop creating objects in your JS

**Comment by matthewd** [comment]
Please use the mailing list or StackOverflow for questions/help, where a wider community will be able to help you. We reserve the issues tracker for issues only.

**Comment by medicharlachiranjeevi** [comment]
Its wont work update node >12 is working for me.
