### ISSUE TITLE
rails 5.2 redis cache store write_multi missing transaction

### ISSUE THREAD

**Issue by FlowerWrong** [rails/rails#37618]
### Steps to reproduce

When using redis as cache_store, I found `Rails.cache.write_multi` missing transaction, but `Rails.cache.fetch_multi` has. See `redis-cli monitor` log below.

```
# Rails.cache.write_multi a: 'cd', b: 'cc'
1572591421.108458 [0 [::1]:53783] "set" "a" "\x04\bo: ActiveSupport::Cache::Entry\t:\x0b@valueI\"\acd\x06:\x06ET:\r@version0:\x10@created_atf\x161572591421.108299:\x10@expires_in0"
1572591421.108636 [0 [::1]:53783] "set" "b" "\x04\bo: ActiveSupport::Cache::Entry\t:\x0b@valueI\"\acc\x06:\x06ET:\r@version0:\x10@created_atf\x171572591421.1083121:\x10@expires_in0"

redis-cli FLUSHALL
# Rails.cache.fetch_multi(*['a', 'b']) { |key| 'tmp' + key }
1572591494.688594 [0 [::1]:53783] "mget" "a" "b"
1572591494.688913 [0 [::1]:53783] "multi"
1572591494.688990 [0 [::1]:53783] "set" "a" "\x04\bo: ActiveSupport::Cache::Entry\t:\x0b@valueI\"\ttmpa\x06:\x06ET:\r@version0:\x10@created_atf\x161572591494.688746:\x10@expires_in0"
1572591494.689015 [0 [::1]:53783] "set" "b" "\x04\bo: ActiveSupport::Cache::Entry\t:\x0b@valueI\"\ttmpb\x06:\x06ET:\r@version0:\x10@created_atf\x171572591494.6888058:\x10@expires_in0"
1572591494.689037 [0 [::1]:53783] "exec
```

### Expected behavior

`Rails.cache.write_multi` redis commands within one transaction.

### Actual behavior

no transaction

### System configuration
**Rails version**: 5.2.3

**Ruby version**: 2.6.3

**Comment by casperisfine** [comment]
> `Rails.cache.write_multi` redis commands within one transaction.

Actually, one could argue that it's `fetch_multi` that shouldn't use a transaction. The two `SET` are totally independent, if one were to fail, there's no reason to rollback the other one.

Redis transactions are more costly on the server than a simple pipelined call, and cause issue with proxies, and I don't see them as justified here.

**Comment by casperisfine** [comment]
Also this was changed in 6.0 (now it uses `mget / mset`), and it doesn't seem like a bug per say, at least not bad enough to justify a fix on a stable branch.

I would suggest to close.

**Comment by FlowerWrong** [comment]
Thanks a lot.
