### ISSUE TITLE
ActionCable will always read from the primary database when using multiple databases

### ISSUE THREAD

**Issue by blakestoddard** [rails/rails#37615]
When using multiple databases (say a remote primary and local replica) via the new native support for them in Rails 6, ActionCable will always read from the primary database, even though it is only issuing `SELECT`s and should be reading from the defined replica. This occurs with no manual connection switching via `ActiveRecord::Base.connected_to(role: :writing)`.

Further, it looks like the ActionCable `SELECT`s cause the Puma worker (in our case) that issued the queries to sticky to the primary for the length of time defined in `config.active_record.database_selector[:delay]`, which causes subsequent requests (even `GET`s!) to have all of their queries sent to the primary if it's within the delay value.

[Here's a log excerpt](https://gist.github.com/blakestoddard/6b82fc3eb76e4d299b12ee2d4dba8e7e) showing the issue where a page was loaded (not shown), there were a series of ActionCable transmissions that hit the primary database in the remote site (noticeable because the remote site is 70ms away from the primary database that the queries were ran on), and then another request within 1 second (our defined switch delay) of the `SELECT`s from ActionCable where the queries from the new request were also sent to the primary when they should've been sent to the local replica (<1ms away).

Is this intended?

### System configuration
**Rails version**: 6.1.0.alpha

**Ruby version**: 2.6.3

**Comment by eileencodes** [comment]
> ActionCable will always read from the primary database, even though it is only issuing SELECTs and should be reading from the defined replica

The only automatic switching implemented was in the middleware which relies on the request type, not on the sql statement. So while not intentional, if nothing was setup to send queries to the replica, Rails will default to the writer.
