### ISSUE TITLE
DEPRECATION WARNING: Class level methods will no longer inherit scoping from `get_employee` in Rails 6.1.

### ISSUE THREAD

**Issue by ayza-hamid** [rails/rails#37629]
### DEPRECATION WARNING: 
Class level methods will no longer inherit scoping from `get_employee` in Rails 6.1. To continue using the scoped relation, pass it into the block directly. To instead access the full set of models, as Rails 6.1 will, use `Employee.unscoped`.

### Steps to reproduce
 > scope :get_employee, ->(employee_id) { find(employee_id) }

### Expected behavior
It should return employee.

### Actual behavior
 ActiveRecord::RecordNotFound Exception: Couldn't find Employee with 'id'=xyz
Though the employee exists in database.

### System configuration
**Rails version**: 6.0.0

**Ruby version**:  2.6.5

**Comment by louim** [comment]
I was not able to reproduce the problem, do you have more details?

Here's what I tried:
```ruby
# frozen_string_literal: true

require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  # Activate the gem you are reporting the issue against.
  gem "activerecord", "6.0.0"
  gem "sqlite3"
end

require "active_record"
require "minitest/autorun"
require "logger"

# This connection will do for database-independent bug reports.
ActiveRecord::Base.establish_connection(adapter: "sqlite3", database: ":memory:")
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :employees, force: true do |t|
  end
end

class Employee < ActiveRecord::Base
  scope :get_employee, ->(employee_id) { find(employee_id) }
end

class BugTest < Minitest::Test
  def test_scoping
    employee = Employee.create!

    assert_equal 1, Employee.count
    assert_equal employee, Employee.get_employee(employee.id)
  end
end
```

**Comment by ayza-hamid** [comment]
I used the obfuscate_id gem
`scope :get_employee, ->(employee_id) { find(employee_id) }` didn't deobfuscate the id in the scope as it did in rails 5. It rather gave me the deprecation warning.

**Comment by kamipo** [comment]
It is considered an issue for the obfuscate_id gem.
Please raising an issue on that gem.
