### ISSUE TITLE
InvalidMimeType exception on a newly created app

### ISSUE THREAD

**Issue by dilshod** [rails/rails#37620]
### Steps to reproduce

How to reproduce:
On a newly created server app, run:
curl -v -H "Accept: text/html,image/apng*/*;q=0.8" http://localhost:3000

I've got a client with this request headers:
    * HTTP_ACCEPT                                             : text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng*/*;q=0.8
    * HTTP_ACCEPT_ENCODING                                    : gzip, deflate
    * HTTP_ACCEPT_LANGUAGE                                    : en-US,en;q=0.8
    * HTTP_USER_AGENT                                         : Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/61.0.3163.79 Safari/537.36
    * HTTP_VERSION                                            : HTTP/1.1

### Expected behavior

It should work, maybe it should ignore invalid mime types.
If this is right behavior, then why not to respond with "400 Bad Request"?

### Actual behavior

Exception happens:
Mime::Type::InvalidMimeType ("image/apng*/*" is not a valid MIME type):
  
actionpack (6.0.0) lib/action_dispatch/http/mime_type.rb:235:in `initialize'
...

### System configuration
**Rails version**: 6.0.0

**Ruby version**: 2.6.3

**Comment by tyler-boyd** [comment]
This does look a bit odd. Why is the client sending a malformed `Accept` header? (There should be a comma after `image/apng` before `*/*`)

Rendering a `400` here sounds reasonable, but I'm not qualified to say if that's a good idea.

**Comment by matt17r** [comment]
I’m not 100% sure how it’s intended to be used but reading through the `lib/action_dispatch/http/mime_type.rb` code it doesn’t seem unreasonable to me to raise that exception and let the consumer of the API decide how to handle it... whether that’s a HTTP 400 or 415.

On the other hand, this does seem like the sort of thing Rails would normally have an opinion about...

**Comment by dilshod** [comment]
Yes, it seems odd, I got only one request like that so far, maybe we can ignore it

**Comment by eugeneius** [comment]
That exception is already mapped to 406: Not Acceptable; see https://github.com/rails/rails/pull/35753.

**Comment by tomrossi7** [comment]
We are having this problem on Rails `6.0.2.rc1`. @eugeneius how can I see what version of Rails that commit made it into?

**Comment by RaviAsnani** [comment]
I'm having the same problem with rails (6.0.0). A bunch of our GET request fail with an Mime::Type::InvalidMimeType exception 

One Example:
Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/62.0.3202.62 Safari/537.36

"HTTP_ACCEPT" => "text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng*/*;q=0.8",

Mime::Type::InvalidMimeType: "image/apng*/*" is not a valid MIME type
 [GEM_ROOT]/gems/actionpack-6.0.0/lib/action_dispatch/http/mime_type.rb:235 :in `initialize`
 [GEM_ROOT]/gems/actionpack-6.0.0/lib/action_dispatch/http/mime_type.rb:143 :in `new`
 [GEM_ROOT]/gems/actionpack-6.0.0/lib/action_dispatch/http/mime_type.rb:143 :in `lookup`
 [GEM_ROOT]/gems/actionpack-6.0.0/lib/action_dispatch/http/mime_type.rb:125 :in `block in sort!`
 [GEM_ROOT]/gems/actionpack-6.0.0/lib/action_dispatch/http/mime_type.rb:125 :in `map!`
 [GEM_ROOT]/gems/actionpack-6.0.0/lib/action_dispatch/http/mime_type.rb:125 :in `sort!`

**Comment by RaviAsnani** [comment]
@eugeneius What would be the correct way to handle this? If some browser is sending a malformed HTTP_ACCEPT header, the end result is bad for our users and us.

**Comment by Envek** [comment]
In our case we had sent `*.*` instead of correct `*/*` and Rails before 6.0 just didn't notice that. Now there is an exception and it's correct, as for me.

**Comment by justisb** [comment]
Has anyone figured out a way to ignore invalid accept headers (and just default to text/html)? Have a handful of users raise this exception every day because of invalid/malformed mime types. This was not an issue before Rails 6.

**Comment by jrochkind** [comment]
@eugeneius  says:

> That exception is already mapped to 406: Not Acceptable;

Indeed a Rails 6.0.3.2 does return an HTTP 406 in this condition. However, it's logged to the log as if it were an uncaught exception, and caught/reported by my error handling service. 

Does anyone know the easiest way to stop having it show up in logs/error handling services as if it were an uncaught exception?

**Comment by dbackeus** [comment]
We also started seeing all kinds of InvalidMimeType errors after upgrading our app to Rails 6. This behaviour appears to be intentional and was added to the mime type parser in https://github.com/rails/rails/pull/35604. Unfortunately this breaking change was never mentioned in the CHANGELOG.

**Comment by richardonrails** [comment]
+1 for looking for a way to simply reject bad mime types without triggering an error. My error collection service is full of "errors" like `Mime::Type::InvalidMimeType: "../../../../../../../../etc/passwd{{" is not a valid MIME type` when I wish Rails would just quietly reject these requests without logging an error.

**Comment by jrochkind** [comment]
I can't figure out any way to avoid the exception showing up in logs (and being caught by most custom error handling code). 

The relevant code is in ActionDispatch::Http::MimeNegotiation. 

Specifically usually here: https://github.com/rails/rails/blob/77fc1c2b8ee95d5ee92224639aa41b91127d20c4/actionpack/lib/action_dispatch/http/mime_negotiation.rb#L47

But if the user-agent sent no `Accept` header at all, but sent a mal-formed `Content-Type` header (I have this exception in my logs too), it might be from here: https://github.com/rails/rails/blob/77fc1c2b8ee95d5ee92224639aa41b91127d20c4/actionpack/lib/action_dispatch/http/mime_negotiation.rb#L23

As far as I can tell, you can not use a `rescue_from` to rescue the errors raised; I think they are raised too early or something for rescue_from to be able to rescue from them. Even if you could, I don't nessarily want to resccue *every* `Mime::Type::InvalidMimeType`. 

If the user-agent supplies *no* `Accept` or `Content-Type`, the Rails app does not raise an exception, but proceeds assuming a default content-type. 

My guess is this is what Rails did pre-6.0 for a malformed Accept/Content-Type. Personally I would consider it a bug that it now reports an error to logs instead. 

I think this behavior can probably be changed with a PR to `ActionDispatch::Http::MimeNegotiation`.  There is some existing code precedent for it [rescuing certain exceptions in another place](https://github.com/rails/rails/blob/77fc1c2b8ee95d5ee92224639aa41b91127d20c4/actionpack/lib/action_dispatch/http/mime_negotiation.rb#L161-L163), but that logic doesn't come into play here (and `Mime::Type::InvalidMimeType` isn't listed as a rescueable exception  anyway). 

I could spend some time trying to figure out a PR to make it so `ActionDispatch::Http::MimeNegotiation` treats a malformed accept or content-type as if the header were not present, instead of raising an exception. But there might be a reason the behavior was changed?  Alternately, perhaps it should return an http 406 without logging an error -- how to accomplish that is less clear to me. 

If Rails maintainers do not see this as a bug, as indicated by ticket being closed, then I'm not motivated to try to figure out the right PR, as it seems likely to just be rejected? It might be tricky anyway, there might be layers within layers here.

**Comment by bbugh** [comment]
@eugeneius can this be re-opened? While the `Mime::Type::InvalidMimeType` exception catch was added in https://github.com/rails/rails/pull/35604, it did not fix this error. There's more discussion about it there as well. 

As @jrochkind said, it does not look like `rescue_from` can be used to catch these errors. Even if we add `rescue_from Mime::Type::InvalidMimeType, with: :render_404` to our application controller, it does not capture these mime type exceptions.

**Comment by eugeneius** [comment]
I can certainly reopen this issue, although I'm not yet convinced that there's anything to fix here. How do your applications deal with `ActionController::RoutingError` exceptions, which similarly can't be intercepted by `rescue_from`? Surely requests for nonexistent paths are much more common than requests with invalid Accept headers?

**Comment by jrochkind** [comment]
> How do your applications deal with ActionController::RoutingError exceptions

One way is to add a catch-all route routing to 404.  at the end of routes.rb, `match '*path', via: :all, to: 'pages#error_404'` I *think* that still works, it's something some people have been doing for years and can be found in blog posts going back a decade. 

That it's in so many blog posts shows that there's demand for this sort of thing. There is at least a hacky way to get rid of 404's from your error log; there is no way to get rid of InvalidMimeType. So it is different in that respect. 

But it is kind of hacky; and I don't think I do it myself. Which makes me think... why aren't 404's showing up in my error tracker? I'm guessing it's defaulting to ignoring them (I don't think I ever configured it). Perhaps various error tracking services just need to catch up to defaulting to ignoring the new InvalidMimeType errors, like they possibly do 404. Not sure what I think, need to think about it/investigate more. 

But it's definitely a popular thing to want to do (as is suppressing the 404's as errors!) -- if there *were* a clean/supported way to allow it to be configured or overridden, it would clearly be appreciated. Not sure.

**Comment by jrochkind** [comment]
Aha, wait, it gets more complicated though. So, honeybadger (one popular error tracker/reporter) [does by default](https://github.com/honeybadger-io/honeybadger-ruby/blob/adf226763dec1b9c2e8b76fa3a6dd21a2d367868/lib/honeybadger/config/defaults.rb#L8-L9) ignore `ActionController::RoutingError` and `AbstractController::ActionNotFound`. 

This shows that this is a popular thing to want to do, that it's honeybadger's default. 

But also, these are very fairly errors, by ignoring them, we are ignoring  exaclty what we want, basically "404s" and not a lot else. 

I was about to go PR adding `Mime::Type::InvalidMimeType` to the honeybadger default list, but realized... nope, that would be far too expansive, I definitely don't want to ignore *any time* `Mime::Type::InvalidMimeType` is raised. It's raised _whenever_ you do (eg) a `Mime::Type.lookup("invalid type")`. 

It seems a bit too rash to ignore all of these. 

So maybe what is needed is for Rails to be (re-)raising a more specific type, so it's easy to ignore exactly what's wanted?  

That is: the cases where a user-agent is supplying an invalidly formatted content-type and Rails is already returning a 406, but is also raising the error to be logged as an uncaught exception. 

What if it instead raised something like `::ActionDispatch::Http::MimeNegotiation::InvalidMimeType`?  

Then it would be more analagous to the 404 case, and it could be more specifically targetted to be ignored the same way 404s are. 

What do you think @eugeneius ? And thanks for re-opening and dialoging.

**Comment by eugeneius** [comment]
That sounds like a good change - calling `Mime::Type.lookup` from application code is [documented](https://github.com/rails/rails/blob/345de17caf82f215b2a9a94e80eabf2473177e3a/actionpack/lib/action_dispatch/http/mime_type.rb#L60), and the fact that passing an invalid argument in code like that currently results in a 406 response seems wrong. Are you interested in writing a PR?

**Comment by jrochkind** [comment]
I potentially could. 

As I think about it... I really feel like it would be better if it were not logging an error at all, but just treating invalid content-type as if the header were missing entirely. (A missing header does not raise an exception). I feel like it's a bug if any user input can produce an uncaught exception. 

However, this is indeed not Rails existing philosophy with `RoutingError` and may be a more controversial idea, possilby for good reason, there may be good reasons. I don't really understand why it was changed to be the way it is, haven't tracked down an explanation in commit messages or PRs, so hard to evaluate it. 

So... ok, I can try to work on that PR, if it seems likely to be acceptable. I guess the new exception class can even still `<  Mime::Type::InvalidMimeType` for backwards compat. As usual the hardest part may be the tests.

**Comment by rafaelfranca** [comment]
Closed by #40353 and f2caed1e73

**Comment by jrochkind** [comment]
Thanks for the extra clean-up on the things I missed in my commit @rafaelfranca , your familiarity with the corners of the architecture is impressive and appreciated.

**Comment by julienchabanon** [comment]
I am still having this issue with rails 6.0.3.4.

**Comment by rafaelfranca** [comment]
@julienchabanon this is only released on 6.1.0.rc1. But you can try the `6-0-stable` branch. The fix is also included there.

**Comment by anklos** [comment]
I am still having this issue at Rails '6.1.3.2'

**Comment by jeffss99** [comment]
we are still having this issue with `Rails '6.1.7.6'`

**Comment by shoaib-iqbal** [comment]
we are still having this issue with `Rails 6.1.7.6`
