### ISSUE TITLE
rails form_with No route matches {:action=>"show", :controller=>"questionstatus", :format=>nil}, missing required keys: [:id]

### ISSUE THREAD

**Issue by chinachaijin** [rails/rails#37637]
**my error prompt**

Showing /home/ubuntu/engineeringmanagement/app/views/questionstatus/_form.html.erb where line # 9 raised: 

No route matches {:action=>"show", :controller=>"questionstatus", :format=>nil}, missing required keys: [:id]

**my error routes**

questionstatus_index_path | GET | /questionstatus(.:format) | questionstatus#index
-- | -- | -- | --
  | POST | /questionstatus(.:format) | questionstatus#create
new_questionstatus_path | GET | /questionstatus/new(.:format) | questionstatus#new
edit_questionstatus_path | GET | /questionstatus/:id/edit(.:format) | questionstatus#edit
questionstatus_path | GET | /questionstatus/:id(.:format) | questionstatus#show
  | PATCH | /questionstatus/:id(.:format) | questionstatus#update
  | PUT | /questionstatus/:id(.:format) | questionstatus#update
  | DELETE | /questionstatus/:id(.:format) | questionstatus#destroy

**my controller**

`  def new
    @questionstatu = Questionstatu.new
  end`

**my views**

`<%= form_with model: Questionstatu.new do |form| %>
<% end %>`

**my routes**

`resources :questionstatus`

**my Resolvent**

`<%= form_with scope: :questionstatu, url: questionstatus_index_path do |form| %>`

**Comment by y-yagi** [comment]
Please use the [mailing list](https://groups.google.com/forum/#!forum/rubyonrails-talk) or StackOverflow for questions/help, where a wider community will be able to help you. We reserve the issues tracker for issues only. Thanks.
