### ISSUE TITLE
credentials:edit/show commands ignores custom content_path and key_path

### ISSUE THREAD

**Issue by MatthieuBarthel** [rails/rails#37631]
### Steps to reproduce
In `application.rb`, configure custom credentials content_path and key_path:
```
config.credentials.content_path = Rails.root.join('config', "credentials.custom.yml.enc")
config.credentials.key_path = Rails.root.join('config', "master.custom.key")
```

Rename your existing credentials files to the new names we've just configured.
`rails s` and `rails c` should work fine with your existing credentials.

### Expected behavior
`rails credentials:edit` and `rails credentials:show` should work with the custom paths, but it doesn't.

### Actual behavior
`rails credentials:edit` will generate new credentials files (`credentials.yml.enc` and `credentials.yml.enc`) instead of editing our current credentials with custom paths.

`rails credentials:show` also ignores custom paths.

### System configuration
**Rails version**: 6.0.0

**Ruby version**: 2.6.5

**Comment by xenyal** [comment]
I'd like to validate my interpretation of the issue at hand before taking a stab at it (I've yet to put up a PR to rails yet but I'm looking for opportunities) 😃 

In the railties subdirectory, within `application.rb` we're given the option of overriding `config.credentials.content_path` and `config.credentials.key_path` where `credentials` is being defined initially. However, in `Rails::Command::CredentialsCommand` the `content_path` being used by `rails credentials:show` and `rails credentials:edit` seems to be hardcoded to the evaluation of `options[:environment] ? "config/credentials/#{options[:environment]}.yml.enc" : "config/credentials.yml.enc"`. So, any overrides passed into `Rails::Application` will get ignored.

Would an adequate solution be to add more guards inside of `Rails::Command::CredentialsCommand` that will first check against `config.credentials.content_path` and `config.credentials.key_path` before trying `environment.yml.enc` and `credentials.yml.enc`, and then adding the corresponding unit tests for those cases?

**Comment by xenyal** [comment]
It looks to me that the design made in `Rails::Command::CredentialsCommand` is specific towards only supporting `config/credentials/:environment.yml.enc` and `config/credentials/:environment.key` if an environment option is given, otherwise defaulting to the static path of `config/credentials.yml.enc`. I'd like to double check that overriding those paths with a custom one on the application configuration level is actually supported before starting.

**Comment by MatthieuBarthel** [comment]
Thanks for your help, here are some links about the paths override :
https://edgeapi.rubyonrails.org/classes/Rails/Application.html#method-i-credentials
https://github.com/rails/rails/issues/34535#issuecomment-441790866

**Comment by bmt34** [comment]
Hi, I hope you don't mind if I add a bit to this issue, as I would expect that the paths can also be set on a per-environment basis in config/environments/<environment>.rb, as with most/all other configuration settings.
