### ISSUE TITLE
Revisiting the inconsistency in enums: raises ArgumentError when making an assignment with invalid value, but returns wrong results when querying

### ISSUE THREAD

**Issue by feliperaul** [rails/rails#37630]
I think it's about time we revisit #13918 and #37172

### Steps to reproduce

```
class Order < ActiveRecord::Base

  enum status: {
    active: 0,
    cancelled: 1
  }

end

order = Order.new

order.status = 'canceled'

# This will (as expected!) raise an ArgumentError: 'canceled' is not a valid status

# However, it doesn't protect me if I screw up on the query. It's even worse:
# in this example, using MySQL, it will bug silently, because it will return
# active orders instead of cancelled ones.
Order.where(status: 'canceled')

```

### Expected behavior
I know we have scopes like `Order.cancelled`, but the official docs clearly encourage using the query directly.

![image](https://user-images.githubusercontent.com/743879/68119533-b89e7580-fee1-11e9-811c-1de63866150a.png)

Using .where directly is also indispensable if you are querying for multiple enums simultaneously, like `.where(status: ['cancelled', 'active'])`. 

**IMHO, the current situation doesn't make sense**: it will protect you from a wrong assignment (which is great), but it will NOT protect you from a wrong query, and worse: will return plain wrong results, resulting in silent bugs.

Currently we have decided to only use enums starting from integer `1` and up, to avoid the `.to_i` converting wrong strings to `0` at the database level and give us wrong results. At least a typo will return 0 results which will give us some warning.

The sheer number of github issues (all closed) regarding this shows that it's not working great for users the way it is. 

### System configuration
**Rails version**: 6.0.0

**Ruby version**: 2.5.3

**Comment by james-em** [comment]
We have been annoyed by this behavior recently. As a workaround, we wrote an initializer (Should support Rails 5 to 7 but we only tested it with Rails 7) to overcome this behavior.

```
##
# Enable this initializer if you want to replace Rails behavior when an invalid value
# is assigned to an enum.
#
# i.e user.role = "invalid" will raise ArgumentError exception by default. This
# behavior can be replaced by a standard validation.
#
# Drawback: If validations are skipped, it's possible to assign an invalid value
# to an enum column. An invalidation value is loaded as nil by ActiveRecord.
#

class ValidatableEnumType < ActiveRecord::Enum::EnumType
  # Override Rail's assert_valid_value() to supress <ArgumentError>
  # We return the value and depend on our own validation
  def assert_valid_value(value)
    value
  end
end

module ValidatableEnum
  extend ActiveSupport::Concern

  included do
    def self.enum(name = nil, values = nil, **options) # rubocop:disable Metrics/MethodLength, Metrics/AbcSize
      super

      name ||= options.keys.first.to_s

      if ::ActiveRecord.version >= ::Gem::Version.new("7.0.0")
        attribute(name) do |subtype|
          ValidatableEnumType.new(name, defined_enums.fetch(name.to_s), subtype)
        end
      elsif ::ActiveRecord.version >= ::Gem::Version.new("6.1.0")
        decorate_attribute_type(name.to_s) do |subtype|
          ValidatableEnumType.new(name, defined_enums.fetch(name.to_s), subtype)
        end
      else
        decorate_attribute_type(name, :validatable_enum) do |subtype|
          ValidatableEnumType.new(name, defined_enums.fetch(name.to_s), subtype)
        end
      end

      validates name, inclusion: { in: defined_enums.fetch(name.to_s).keys }
    end
  end
end

ActiveRecord::Base.include ValidatableEnum
```
