### ISSUE TITLE
ActiveRecord fails to parse BCE (negative) dates in PostgreSQL time ranges

### ISSUE THREAD

**Issue by chrisandreae** [rails/rails#37647]
### Steps to reproduce

Executable test case:
https://gist.github.com/chrisandreae/cfac1fe1e2e2b2b987e3aa826f803c86

* Create an ActiveRecord model for a table with a `tsrange` column
* Create and persist a record with a time range including a BCE (negative) year.
  `m = Model.create(period: (::DateTime.new(-1000, 1, 1, 0, 0) .. Time.now.utc))`
* Reload the model and observe that the `begin` of the loaded range has been changed to a positive date:
  `> model.reload.period.begin`
  `=> 1001-01-01 00:00:00 UTC`

This is caused by missing handling for nested quoting of range values in `ActiveRecord::ConnectionAdapters::PostgreSQL::OID::Range`.

### Expected behavior
The tsrange attribute should be reloaded with the same `DateTime` values as when persisted.

### Actual behavior
The tsrange attribute is reloaded with the absolute value of the year stored in
the database: for example, the year `-1000` is persisted as `1001 BC`, and so loaded as
`1001`.

### System configuration
**Rails version**:
`master` as of 803c6ba

**Ruby version**:
ruby 2.5.5p157

**Comment by kevingriffin** [comment]
I would love to see this merged.

**Comment by kevingriffin** [comment]
Is there any way the PR can be improved to move towards a merge?

**Comment by simi** [comment]
I think this can be closed and we can continue in pull requests. I think mainly it is missing tests now.

**Comment by chrisandreae** [comment]
I added the requested tests a couple of months ago. I've rebased the PR again today. Is there anything further required to progress with this?
