### ISSUE TITLE
Parenthesis in directory name prevents rails from finding templates

### ISSUE THREAD

**Issue by justinh24** [rails/rails#37641]
### Steps to reproduce
Create a Rails application in a folder within a path that includes parenthesis.  Why would you do this? The business version of dropbox adds (Personal) and (Bizname) to your dropbox directories. (i.e. /home/baz/Dropbox (Personal)/dev/) on MacOS.
```
mkdir /tmp/appdir \(bad\)/
cd /tmp/appdir \(bad\)/
rails new myapp
cd myapp
rails generate scaffold product name 'price:decimal{7,2}'
rails db:create
rails db:migrate
rails s

Request http://localhost:3000/products
```

### Expected behavior
Expect to be able to create and work on a rails app on this valid although odd path.  Expect templates to be found and rendered.

### Actual behavior
Received the following error when requesting a view:
```Missing template products/index, application/index with {:locale=>[:en], :formats=>[:html], :variants=>[], :handlers=>[:raw, :erb, :html, :builder, :ruby, :jbuilder]}. Searched in: * "/Users/baz/test (aa)/testapp/app/views" * ...
### System configuration
**Rails version**:
6.0.1
**Ruby version**:
2.5.1

**Comment by fxn** [comment]
The error message is

```
Processing by ProductsController#index as HTML
Completed 406 Not Acceptable in 7ms (ActiveRecord: 0.0ms | Allocations: 2293)



ActionController::MissingExactTemplate (ProductsController#index is missing a template for request formats: text/html):

actionpack (6.0.1) lib/action_controller/metal/implicit_render.rb:45:in `default_render'
actionpack (6.0.1) lib/action_controller/metal/basic_implicit_render.rb:6:in `block in send_action'
actionpack (6.0.1) lib/action_controller/metal/basic_implicit_render.rb:6:in `tap'
actionpack (6.0.1) lib/action_controller/metal/basic_implicit_render.rb:6:in `send_action'
actionpack (6.0.1) lib/abstract_controller/base.rb:196:in `process_action'
...
```

This is definitely a bug. Application directories should be valid constant names once camelized, but the parent directories of the application root should have no restrictions.

**Comment by justinh24** [comment]
I think this comes from the new Rails 6 optimized OptimizedFileSystemResolver... 
adding parens to escape_entry in actionview/lib/action_view/template/resolver seems to fix the issue but I am not familiar enough with actionview to know what else this might affect.
```
def escape_entry(entry)
    entry.gsub(/[*?\(\){}\[\]]/, '\\\\\\&')
end
```

**Comment by justinh24** [comment]
Looks like this might have been addressed in this pull request:
https://github.com/rails/rails/pull/37119
