### ISSUE TITLE
cookies.delete does not remove cookies for subsequent requests in ActionController::TestCase

### ISSUE THREAD

**Issue by percysnoodle** [rails/rails#37653]
### Steps to reproduce
Write an `ActionController::TestCase` which:
- makes a request that sets a cookie
- makes a second request that deletes a cookie
- makes a third request 
- asserts that the cookie is gone in the third response

For example, see [this test](https://github.com/percysnoodle/rails-action-controller-test-cookies/blob/master/test/controllers/cookies_controller_test.rb) which tests [this controller](https://github.com/percysnoodle/rails-action-controller-test-cookies/blob/master/app/controllers/cookies_controller.rb).

### Expected behavior
The cookie should not be present in either the second or third response, so test should pass.

### Actual behavior
The cookie is absent for the second response, but it is back in the third, so the test fails.

### System configuration
**Rails version**: 6.0.1

**Ruby version**: 2.6.3p62

### Notes

If I set up the same test as in the linked example project, using `ActionDispatch::IntegrationTest` instead of `ActionController::TestCase`, the test passes.

This was discovered as a result of hitting rspec/rspec-rails#1574

Possibly related: #18222, #27584

**Comment by joshbuker** [comment]
This is still broken today, and sent me down a rabbit hole that only ended when I found https://github.com/rspec/rspec-rails/issues/1574#issuecomment-373345096.

Porting some legacy controller specs is how I found this issue. That said, controller specs are deprecated, so if this is fixed for system specs / whatever the replacement for controller specs is, then this isn't worth addressing considering there is a viable workaround.

Workaround:
```ruby
cookies.update(response.cookies)
```
