### ISSUE TITLE
Webpack is not installable or usable inside a Rails 6 Engines

### ISSUE THREAD

**Issue by AfolabiOlaoluwa** [rails/rails#37656]
### Steps to reproduce
I created a Rails 6 app and for a Modular Monolith Application and here are my steps:

- `rails new ModularTodo` 

- `cd ModularTodo && rails plugin new todo --mountable`

- `mkdir engines && mv todo ./engines`

### Expected behaviour
Inside the Rails Engine, I am supposed to have a directory for javascript so that I can use Webpack in each engine I create.

### Actual behaviour
It created a Rails 6 Engine inside the parent's rails app but doesn't come with javascript directory, so I cant use Webpack in each miniature engine.

### System configuration
**Rails version**: Rail 6.0.0

**Ruby version**: Ruby 2.6.2

**Image**
You can see the engine doesn't come with javascript folder and I cant use Webpack on it. I tried to cd in that engine and install Webpack manually, it didn't allow. Any help to do this will be appreciated.

<img width="314" alt="Screenshot 2019-11-07 at 13 43 44" src="https://user-images.githubusercontent.com/15254043/68390025-af710b00-0164-11ea-9c46-fcf2ba5469aa.png">

**Comment by abhaynikam** [comment]
@AfolabiOlaoluwa : Currently, Rails does not add Webpack in the engine. You can add it to the engine following the steps mentioned here: https://github.com/rails/webpacker/blob/master/docs/engines.md

We did some work here https://github.com/rails/rails/pull/36364 but I was not able to followup on it more. I'll try to work on it this or coming weekend :)

**Comment by AfolabiOlaoluwa** [comment]
> https://github.com/rails/webpacker/blob/master/docs/engines.md

Okay, I will try to do that. Thanks.

**Comment by mhoad** [comment]
Anyway to get this merged https://github.com/rails/webpacker/pull/1694 ? It seems like it would go long way towards this

**Comment by jakeNiemiec** [comment]
Related: https://github.com/rails/webpacker/issues/348
