### ISSUE TITLE
Unable to understand ActiveJob/Sidekiq behaviour when redis is down

### ISSUE THREAD

**Issue by Arafatk** [rails/rails#37659]
Cross Posting from [Sidekiq Repo Issue](https://github.com/mperham/sidekiq/issues/4356)

Sidekiq / Pro / Enterprise version(s): 6.0.0
ActiveJob Version: 6.0.0
I am using `ActiveJob` with queue_adapter `sidekiq`.     
In the wiki, it's  mentioned that Sidekiq uses [Redis for enqueuing job](https://github.com/mperham/sidekiq/wiki/Using-Redis).   So when redis is down the Jobs should either stop enqueuing(+raise error) when doing [perform_later](https://github.com/mperham/sidekiq/wiki/Active-Job#usage) or they should perform inline(Or maybe something else?).        

### Steps to reproduce
I am trying to write some tests and I can't figure out what happens when Redis is down(I am simulating redis down using [ToxiProxy](https://github.com/Shopify/toxiproxy-ruby)). 
![image](https://user-images.githubusercontent.com/11155207/68078176-46c21100-fda7-11e9-80a8-e0edb1b9a8ee.png)

### Expected behavior

`perform_now` does inline analysis so it shouldn't give any errors when redis is down while `perform_later` should raise an error because it fails in enqueuing the job.   

### Actual behavior

 I do a `perform_later` call locally, and it just returns a job object when I do the `perform_now` call then I get `Redis::CannotConnectError: ` instead.     

Debugging Steps
------

I even looked at the [testing wiki](https://github.com/mperham/sidekiq/wiki/Testing) and disabled sidekiq so that it enqueues that job but even then the perform_later command worked (while the redis was down ).    

I tried a sidekiq push(while keeping redis down with toxiproxy)
```
Sidekiq::Client.push(
  'class' => 'NonExistentWorker',
  'queue' => 'other',
  'args' => [1]
)
```

This one failed and raised a redis connection error(while it worked perfectly when redis was up). This proves that atleast my toxiproxy setup is correct but something seems very weird with the way activejob interacts with sidekiq and then with redis. 

The main reason I am asking this question is because I want to be able to do inline analysis for my jobs incase redis is down and I can't seem to figure out how to do that.   

 
Is this a known issue or is something wrong with my configuration?

### System configuration
**Rails version**:
```
Rails 6.0.0
```

**Ruby version**:
```
ruby 2.5.3p105 (2018-10-18 revision 65156) [x86_64-darwin18]
```

**Comment by Edouard-chin** [comment]
> I do a perform_later call locally, and it just returns a job object

That's a bug in Rails related to https://github.com/rails/rails/pull/33171 that we should fix. The logging message you get is a red herring, your job didn't get through redis.

> when I do the perform_now call then I get Redis::CannotConnectError: instead.

`perform_now` doesn't send your job through the enqueuing adapter, it's not possible that redis get involved, unless your job itself do sth with redis
