### ISSUE TITLE
guides.rubyonrails.org hasn't been republished since the release of Rails 6.0.1

### ISSUE THREAD

**Issue by rmacklin** [rails/rails#37668]
### Steps to reproduce
Visit https://guides.rubyonrails.org

### Expected behavior
I expected to see the guides generated from these source files:
https://github.com/rails/rails/tree/v6.0.1/guides

As an example, I expected to see the change from https://github.com/rails/rails/commit/26aabdcce88e952c9189766bae3d32d5c6448963 reflected in the first sentence on the page.

### Actual behavior
I am still seeing the guides generated from these source files:
https://github.com/rails/rails/tree/v6.0.0/guides

The first sentence still reads:
> These are the new guides for Rails 5.2 based on v6.0.0

rather than
> These are the new guides for Rails 6.0 based on v6.0.1

Screenshot:
![image](https://user-images.githubusercontent.com/1863540/68521134-e3c2f500-0252-11ea-926f-9ebe83765f28.png)

### System configuration
**Rails version**: N/A

**Ruby version**: N/A

**Comment by fxn** [comment]
Problem is that `git pull` did not fetch the new tag `v6.0.1`:

```
rails@cantor:~/master$ git tag | grep 6.0
v6.0.0
v6.0.0.beta1
v6.0.0.beta2
v6.0.0.beta3
v6.0.0.rc1
v6.0.1.rc1
```

and stable docs generation is triggered by the presence of a new release tag.

I had to manually fetch them:

```
rails@cantor:~/master$ git fetch --tags
remote: Enumerating objects: 7, done.
remote: Counting objects: 100% (7/7), done.
remote: Total 12 (delta 7), reused 7 (delta 7), pack-reused 5
Unpacking objects: 100% (12/12), done.
From https://github.com/rails/rails
 * [new tag]               v6.0.0.rc2 -> v6.0.0.rc2
 * [new tag]               v6.0.1     -> v6.0.1
```

Same happened in my laptop:

```
~/prj/rails-dev-box/rails [master] % git fetch --tags
remote: Enumerating objects: 28, done.
remote: Counting objects: 100% (28/28), done.
remote: Total 42 (delta 28), reused 28 (delta 28), pack-reused 14
Unpacking objects: 100% (42/42), done.
From github.com:rails/rails
 * [new tag]               v5.2.0.beta1 -> v5.2.0.beta1
 * [new tag]               v5.2.0.beta2 -> v5.2.0.beta2
 * [new tag]               v6.0.0.rc2   -> v6.0.0.rc2
 * [new tag]               v6.0.1       -> v6.0.1
```

Not sure why, first time this happens in the docs server. Indeed, Rails contributors has a similiar logic for the [releases page](https://contributors.rubyonrails.org/releases) and it got v6.0.1 just fine.

Perhaps I add fetching tags after pulling to play safe.

**Comment by rmacklin** [comment]
Interesting. Thanks for looking into it and getting the new guides published!
