### ISSUE TITLE
How to permit concurrent loads in Rails 4.2?

### ISSUE THREAD

**Issue by vaibhavatul47** [rails/rails#37675]
### Steps to reproduce
When writing a multithreaded application it is advised to enable concurrent loads to avoid deadlock during autoloading.
``` ruby
ActiveSupport::Dependencies.interlock.permit_concurrent_loads
```
[link to guide](https://guides.rubyonrails.org/threading_and_code_execution.html#permit-concurrent-loads)

The example in the guide is for Rails 5, how can I achieve this in Rails 4.2? I couldn't find `interlock.rb` file inside `active_support/dependencies` directory.

### Expected behavior
``` ruby
  futures = @current_user.posts.map do |p|
      Concurrent::Promises.future(p) do |post|
        ActiveRecord::Base.connection_pool.with_connection do
          post.cleanup_comments # Calls an API which takes ~2minutes
          post.destroy
        end
      end
    end

    responses = futures.map(&:value)
```
This code should be able to destroy all posts of current-user concurrently.

### Actual behavior
When I execute this code I get: `Circular dependency detected while autoloading constant` error

Note: I was able to solve this problem by putting these two lines in my `config/application.rb` file, but I'm not sure if thats the correct way to solve this circular dependency deadlock issue.
``` ruby
config.cache_classes = true
config.eager_load = true
```

### System configuration
**Rails version**: rails -v # Rails 4.2.8

**Ruby version**: ruby -v # ruby 2.3.4p301 (2017-03-30 revision 58214) [x86_64-darwin18]

**Comment by kaspth** [comment]
You can’t because it was added for Rails 5.0 iirc. Rails 4.2 is unsupported now, so the only to be able to enable that is to upgrade your Rails app. Thanks!
