### ISSUE TITLE
railties syntax error in test.rb.tt

### ISSUE THREAD

**Issue by ashleyHutton** [rails/rails#37680]
### Steps to reproduce

I'm having issues creating a new project in Rails.

`rails new my-project`

### Actual behavior
```
/Users/Ashley/.rbenv/versions/2.5.0/lib/ruby/2.5.0/erb.rb:885:in `eval': /Users/Ashley/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/railties-6.0.1/lib/rails/generators/rails/app/templates/config/environments/test.rb.tt:10: syntax error, unexpected ')', expecting end-of-input (SyntaxError)
);  if spring_install?
```

### System configuration
**Rails version**:
```
rails -v
Rails 6.0.1
```
**Ruby version**:
```
ruby -v
ruby 2.5.0p0 (2017-12-25 revision 61468) [x86_64-darwin17]
```

Potentially line 9 of [test.rb.tt](https://github.com/rails/rails/blob/v6.0.1/railties/lib/rails/generators/rails/app/templates/config/environments/test.rb.tt):
`<%-# Spring executes the reloaders when files change. %>`

Which was changed in [this commit](https://github.com/rails/rails/commit/27cf7125b5d036987522103fc02ebe50beddff80#diff-baf003b809c4c8418bb20022759cf80c).

I was able to successfully create a new rails project using version `6.0.0`.

**Comment by louim** [comment]
Hey! Are you able to reproduce the issue with another ruby version? I tried with Ruby 2.6.5 and ruby 2.5.3 but I was not able to reproduce the problem with those version? Maybe it's a bug specific with that ruby version?

**Comment by y-yagi** [comment]
This issue only happens in Ruby 2.5.0 due to a backward-incompatible change of ERB.  https://bugs.ruby-lang.org/issues/14243 
This was fixed with Ruby 2.5.1. https://github.com/ruby/ruby/commit/887dced42e51e79734c75e77bdfb69c56493e6e3

**Comment by ashleyHutton** [comment]
@y-yagi thanks! I'll update my Ruby version.

I'm closing since there doesn't seem to be any action that can be taken besides changing versions.

**Comment by jonatasteixeira** [comment]
You can fix it doing this:

Open the file:

> ~/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/railties-6.0.1/lib/rails/generators/rails/app/templates/config/environments/test.rb.tt

And then, go to line `10` and edit like bellow:

From:
`10:    <%-# Spring executes the reloaders when files change. %>`

To:
`10:     <%-# Spring executes the reloaders when files change. -%>`

**Comment by reiz** [comment]
I had the same issue with Ruby 2.5.0. After upgrading to 2.5.1 the issue disappeared.
