### ISSUE TITLE
redirect route fails with subdomain for ipv6 host

### ISSUE THREAD

**Issue by doooby** [rails/rails#37705]
### Steps to reproduce
I've forked and added tests to show the fail:
https://github.com/doooby/rails/commit/c9664cb84c49680673e99919a445764bd9da58ad

### Expected behavior
I'm not gonna say how this *should* behave, but at least there **should not be a difference between IPv4 and IPv6 host** when redirecting with subdomain like this:

```ruby
constraints subdomain: false do
  get "*path", to: redirect(subdomain: 'www')
end
```

### Actual behavior
for IPv4 host `127.0.0.1:3000` it ends up redirected to `http://127.0.0.1:3000/`
but for IPv6 `[::1]:3000` it's `http://www.[::1]:3000/` which fails on `URI::InvalidURIError`

### System configuration
**Rails version**: found on 5.2, present on master
**Ruby version**: irrelevant?

### The Issue
We've encountered this probably as some sort of host header attack (not sure when it even makes sense for the host to be IP) but as I've dug deeper, it surely is nothing that should be too controversial. There's even this `ActionDispatch::Http::URL.named_host?` method to recognize the host is "named" as operations with subdomain(s) should be ignored in case it's IP. but the `IP_HOST_REGEXP  = /\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3}$/` only tests for IPv4. Meaning **IPv6 is internally treated as "named" host**.

My sticking point is that our server fails on this so we have to patch it, but it's not that straight forward within the route redirection itself and also it sure is unexpected. I haven't even found any good way to recognizet if a host is IPv6 - not in Rails at least.

Is this some gray area? Or is this reasonable and IPv6 should not yield an error? 
Would you accept a PR to support IPv6 in this case?

**Comment by pixeltrix** [comment]
@doooby yes, seems perfectly reasonable that IPv6 shouldn't be treated as a named host so please do create a PR, thanks.
