### ISSUE TITLE
Rails 6 changes implicit template fallback handling

### ISSUE THREAD

**Issue by pwim** [rails/rails#37717]
### Steps to reproduce

Given the following files:

```
comments/index.html.erb
comments/new.html.erb
comments/new.js.erb
```

Where `comments/index.html.erb`  contains

```erb
<%= render template: "comments/new" %>
```

Then I load comments/index.html.erb via xhr.

### Rails 5.2 behavior
`render template: "comments/new"` will render `comments/new.html.erb`

### Rails 6.0 behavior
`render template: "comments/new"` will render `comments/new.js.erb`

I can work around this by explicitly specifying the formats like

~`render template: "client/event_comments/new", formats: [:html]`~

```ruby
render template: "comments/new", formats: [:html]
```

### Bug or intentional?

I skimmed [actionview's Changelog](https://github.com/rails/rails/blob/6-0-stable/actionview/CHANGELOG.md), but didn't see anything about it, leading me to think it is a side effect of another change.

**Comment by kassio** [comment]
Can you provide an example app? I wasn't able to replicate with the following steps:
1. rails new foo
2. cd foo && rails g controller testc index
3. echo "JS" > app/views/testc/new.js.erb
4. echo "HTML" > app/views/testc/new.html.erb
5. echo "<%= render template: 'testc/new' %>" > app/views/testc/index.html.erb
6. rails server
7. open http://localhost:3000/testc/index in the browser I saw: "HTML".

On your workaround you said that it worked with:
```
render template: "client/event_comments/new", formats: [:html]
```
But the template path on this example is different, can you confirm that, please?

**Comment by Edouard-chin** [comment]
This is due to the fix made in https://github.com/rails/rails/pull/35229

Explicitly specifying the format like you did is the proper way to use a template with a different format

**Comment by pwim** [comment]
@kassio The workaround just had a typo in it. I was trying to simplify my example from the production code. Thanks for coming up with the example app. There's two more steps to reproducing it:

1. The html needs to be loaded via xhr.
2. For the new html template, it needs to have a different handler than the js template (my real app uses haml to render html templates, whereas I'm using erb for js templates; however, this issue isn't haml specific).

To take this into account, I modified your example app to the following:

```
rails new foo
cd foo 
rails g controller testc index
echo "JS" > app/views/testc/new.js.erb
echo "HTML" > app/views/testc/new.html
echo "<%= render template: 'testc/new' %>" > app/views/testc/index.html.erb
yarn add jquery 
echo '$ = require("jquery")' >> app/javascript/packs/application.js
rails g controller load_via_xhr index  
echo '<%= javascript_tag(%q{$("body").load("/testc/index")}) %>' > app/views/load_via_xhr/index.html.erb
rails server
```

If I visit http://localhost:3000/load_via_xhr/index, "JS" is displayed (i.e., when `app/views/testc/index.html.erb` is rendered via xhr). If I visit http://localhost:3000/testc/index, "HTML" is displayed.

Furthermore, if I change the html template to be erb:

```
mv app/views/testc/new.html app/views/testc/new.html.erb
```

Now  http://localhost:3000/load_via_xhr/index will display "HTML" (so the same behaviour as Rails 5.2).

Given this inconsistency in behaviour based on whether the template handlers are different or not, I think this is a bug.
