### ISSUE TITLE
Setting config.log_level results in console not matching log files

### ISSUE THREAD

**Issue by anderscarling** [rails/rails#37728]
When setting `config.log_level` to anything other than the default value of :debug, the console will ignore the assigned log level.

### Steps to reproduce
* Configure `config.log_level = :info`
* Start rails console
* Log something on log level debug.
```
Loading production environment (Rails 6.0.1)
[1] pry(main)> Rails.logger.level # Inspect current log level (1 == :info)
=> 1
[2] pry(main)> Rails.logger.debug("Test") # This should be filtered, but is not
Test
=> true
[3] pry(main)> Rails.logger.level = 1 # This looks like it would be a noop, but will change behavior of the STDERR-logger.
=> 1
[4] pry(main)> Rails.logger.debug("Test") # With the log level assigned, everything works as expected
=> true
```

### Expected behavior
When the Active Record Railtie extends Rails.logger with a new STDERR-logger, it should copy `Rails.logger.level` to the new logger.

### Actual behavior
The ActivieRecord Railtie never assigns `Logger#level` on the new logger.

[activerecord/lib/active_record/railtie.rb#L61](https://github.com/rails/rails/blob/dcaa388badf49423fb8613bc02652e448890f879/activerecord/lib/active_record/railtie.rb#L61)

### System configuration
**Rails version**: 6.0.1
**Ruby version**: 2.6.5

### Related issues
This issue #15470 tracks a related - but seemingly more complicated - issue of `config.log_formatter` not being carried over to the console logger. In a merged but later reverted patch for that issue, this issue was also fixed.

**Comment by anderscarling** [comment]
The current behavior created a problem for me as a third party gem was logging to Rails.logger on the debug level, and it took me quite a while and some searching through rails sources files before I understood why the output was not suppressed by the log level. This was especially confusing since `Rails.logger.level` returns log level for the file logger (as demonstrated in steps to reproduce).

An alternative solution to carrying over `Rails.logger.level` would probably be to add a new configuration option `config.console_log_level` or similar.

**Comment by interlinked** [comment]
Is there any quick workaround for this @anderscarling?  I'm having the same issue and it's making me nutty!

**Comment by anderscarling** [comment]
Basically anything that sets Rails.logger.level to desired level after console startup would fix it.

Maybe something like this in `~/.irbrc`:

```
if defined?(::Rails)
  ::Rails.logger.level = :info 
end
```

**Comment by Piyush-Chaudhary** [comment]
Does anyone find a solution? I am also having the problem of logger_level on production.
I have defined logger_level=:info but it's throwing debug level logs, although in staging with the same in staging.rb giving the right logs.

**Comment by anderscarling** [comment]
This is the workaround I use:

`config/initializers/console.rb`:
```ruby
if defined?(::Rails::Console)
  # Workaround for https://github.com/rails/rails/issues/37728
  Rails.logger.level = Rails.logger.level
end
```
