### ISSUE TITLE
SQLite3Adapter#copy_table should not include `default` for primary keys

### ISSUE THREAD

**Issue by peterkovacs** [rails/rails#37722]
### Steps to reproduce

The method `copy_table` includes this column definition:

```ruby
        def copy_table(from, to, options = {})
          create_table(to, **options) do |definition|
            columns(from).each do |column|
              @definition.column(column_name, column.type,
                limit: column.limit, default: column.default,
                precision: column.precision, scale: column.scale,
                null: column.null, collation: column.collation,
                primary_key: column_name == from_primary_key
              )
            end
        end
```

However, `ActiveRecord::ConnectionAdapters::TableDefinition#integer_like_primary_key?` tests the *presence* of `:default` in the options has to determine if the *type* of the column should be `primary_key` or `integer`. By including `:default` in this options hash, the generated primary key no longer has the `AUTOINCREMENT` attribute.

I suggest an edit such as:

```ruby
            column_options = {
              limit: column.limit,
              precision: column.precision,
              scale: column.scale,
              null: column.null,
              collation: column.collation,
              primary_key: column_name == from_primary_key
            }

            unless column_options[:primary_key]
              column_options[:default] = column.default
            end

            @definition.column(column_name, column.type, column_options)
```

However, I'm not sure how this would interact with tables with multiple primary keys.

### Expected behavior

The primary key on the copied table should include the AUTOINCREMENT attribute.

### Actual behavior

The primary key is created without the AUTOINCREMENT attribute.

### System configuration
**Rails version**: 6.0

**Ruby version**: 2.4.6

**Comment by gulaschsippl** [comment]
This can still be reproduced on latest Rails release 7.0.4.2.

As far as I see, this affects all SQLite3Adapter schema statements that use `alter_table` internally, i.e. `change_column_default`, `change_column_null`, etc.

If a table was created with an integer primary key with option `autoincrement` (which is the default), after running one of these schema statements, the `autoincrement` option is not defined anymore on that table.

The following examples shows the SQL statements which are executed, if there are two migrations, the first for creating the table and the second for changing the column null:
```sql
CREATE TABLE "users" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "mail" varchar, "created_at" datetime(6) NOT NULL, "updated_at" datetime(6) NOT NULL)
CREATE TEMPORARY TABLE "ausers" ("id" integer NOT NULL PRIMARY KEY, "mail" varchar DEFAULT NULL, "created_at" datetime(6) NOT NULL, "updated_at" datetime(6) NOT NULL)
CREATE TABLE "users" ("id" integer NOT NULL PRIMARY KEY, "mail" varchar NOT NULL, "created_at" datetime(6) NOT NULL, "updated_at" datetime(6) NOT NULL)
```

The example shows how the `autoincrement` definition is lost during the `alter_table` (via `change_column_null`).

Can this issue be addressed?

**Comment by skipkayhil** [comment]
> This can still be reproduced on latest Rails release 7.0.4.2.

Can you open a new issue with a reproduction script using something like this: https://github.com/rails/rails/blob/8231a4c61e649ab84877053de9b03b4896edf1d1/guides/bug_report_templates/active_record_migrations_main.rb

That would make it super easy for us to help fix the issue

**Comment by gulaschsippl** [comment]
It will take me a few days till I find time for it, but then I will gladly do that, yes.

**Comment by gulaschsippl** [comment]
I opened the new issue here: #47400.
