### ISSUE TITLE
ActiveRecord variants using convert end up with wrong content_type

### ISSUE THREAD

**Issue by dbackeus** [rails/rails#37737]
### Steps to reproduce

- Create new rails app (either current rails version `6.0.1` or edge `6.1.alpha`)
- Uncomment the `gem 'image_processing'` directive in Gemfile and `bundle install`
- `rails active_storage:install`
- `rails generate model image`
- `rails db:migrate`
- Add `has_one_attached :image` to the `Image` model
- Select any `.jpg` image on your computer and copy it to the rails app folder as `test.jpg`
- Start a `rails console` and run the following:

```ruby
image = Image.create!
image.image.attach(io: File.open("test.jpg"), filename: "test.jpg")
image.image.variant(convert: "webp").blob
# => #<ActiveStorage::Blob id: 2, key: "ru7j7ly6jom97fnl8vv3x15g4x2b", filename: "test.jpg", content_type: "image/jpeg", metadata: {"identified"=>true}, byte_size: 120405, checksum: "0IGXr0/9sYh3sqguuEsRNg==", created_at: "2019-11-17 11:22:12">
```

### Expected behavior

The `content_type` should be `image/webp` and the filename extension should probably be changed to `.webp` as well.

### Actual behavior

The `content_type` remains `image/jpeg` and filename extension `.jpg` which is now incorrect and will not be correctly handled by browsers.

### Why is this important?

Serving optimized webp versions of images is a best practice for the modern web. Also as long as ActiveStorage claims to officially support all the conversion options available in `image_processing` the `convert` directive should be gracefully handled.

### System configuration

**Rails version**: 6.0.1 as well as the current 6.1.alpha

**Ruby version**: 2.6.5

**Comment by artur-beljajev** [comment]
Though it seems `product.images.first.file.variant(resize_to_fill: [300, 450], convert: 'webp')` is served with the correct mime type of `image/webp`.

**Comment by sam-f** [comment]
I have found that variant(convert: 'webp') in Rails 6.1.1 still does not serve in correct mime type, original JPG as well as PNG

**Comment by MichalRemis** [comment]
> Though it seems `variant(resize_to_fill: [300, 450], convert: 'webp')` is served with the correct mime type of `image/webp` in Rails 6.1. The original file is JPEG.

It still doesn't work for me in Rails 6.1.7.3. The image is converted to webp, but content_type and extension remains jpeg
