### ISSUE TITLE
Need To Rename "node_modules" folder

### ISSUE THREAD

**Issue by elmatadoor** [rails/rails#37739]
why not to renam "node_modules" folder to "npm" or "node" or "node_mods" or somme thing shorter 
because "node_modules" is a long name and take place in my editor side bare ?
is it possible to do it manualy by my self ?

**Comment by louim** [comment]
Hey! `node_modules` is actually a convention for NodeJS/ package managers and cannot be changed. You could hide the folder in your editor, since you normally don't have to interact with that folder manually.

**Comment by y-yagi** [comment]
As @louim described, this is not Rails's issue. Please check your editor's config.

**Comment by elmatadoor** [comment]
thanks for you all
