### ISSUE TITLE
Unknown keyword: has_one_attached with service

### ISSUE THREAD

**Issue by hudadiaz** [rails/rails#37740]
### Steps to reproduce
Add `service: :alt_service` option to `has_one_attached`

### Expected behavior
Specified alternate service should be used by ActiveStorage

### Actual behavior
Exception thrown
```
ArgumentError (unknown keyword: service)
```

### System configuration
**Rails version**: rubyRails 6.0.0

**Ruby version**: ruby 2.6.3p62 (2019-04-16 revision 67580) [x86_64-darwin18]

**Comment by hshimoyama** [comment]
`service` option on `has_one_attached` was added by this commit.
https://github.com/rails/rails/commit/e7f798c3f549502d696167e9b29f18106cf2cbe0#diff-fc054319f93d887d4427a7a728670ba9
But it's not released yet.

**Comment by hudadiaz** [comment]
That's a bummer.

**Comment by danielpowell4** [comment]
@hshimoyama do you know if this is [still] intentional?

I know a **ton** of work goes into each release, but it seems odd to have it in the docs when it's not live.

See last code sample here:

https://edgeguides.rubyonrails.org/active_storage_overview.html#has-one-attached

Seems like this issue shouldn't be closed

**Comment by georgeclaghorn** [comment]
Those are the edge guides for latest master (note the subdomain). The guides for the latest stable release are at [guides.rubyonrails.org](https://guides.rubyonrails.org/).

**Comment by birthdaycorp** [comment]
The [edge guides](https://edgeguides.rubyonrails.org/active_storage_overview.html#what-is-active-storage-questionmark) say to update to 5.2, and then [later on](https://edgeguides.rubyonrails.org/active_storage_overview.html#has-one-attached) say that the `service` option` works with `has_one_attached`. Should this doc be updated to reflect that fact that it does not work until 6+?
