### ISSUE TITLE
raise_on_type_mismatch! in ActiveRecord::Associations::BelongsToAssociation

### ISSUE THREAD

**Issue by hiphapis** [rails/rails#37752]
### Steps to reproduce

Define complicated relation option in Model
```ruby
class Account < ApplicationRecord
  belongs_to :currency, class_name: 'Currency', primary_key: :name, foreign_key: :currency
  scope :usd, -> { where(currency: 'usd').order(id: :desc) }
end

#
Account.usd # it's work. no problem but
Account.usd.new # then meet raise_on_type_mismatch!
```

### Expected behavior
Return new Account Object

### Actual behavior
raise ActiveRecord::AssociationTypeMismatch
message is
```
ActiveRecord::AssociationTypeMismatch: Currency(#70166672595800) expected, got "usd" which is an instance of String(#70166591741680)
.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/activerecord-5.1.4/lib/active_record/associations/association.rb:250:in `raise_on_type_mismatch!'
```

I knew, it's not a normal case and not rails conventions. I wanna change DB Scheme also. but it's another team's role ;(
Anyway, I was check `raise_on_type_mismatch!` method. (`activerecord-5.1.4/lib/active_record/associations/association.rb`)
`raise_on_type_mismatch!` get 1 parameter `record`
in this case `record` is 'usd'
```ruby
def raise_on_type_mismatch!(record)
  unless record.is_a?(reflection.klass)
    fresh_class = reflection.class_name.safe_constantize
    unless fresh_class && record.is_a?(fresh_class)
      message = "#{reflection.class_name}(##{reflection.klass.object_id}) expected, "\
        "got #{record.inspect} which is an instance of #{record.class}(##{record.class.object_id})"
      raise ActiveRecord::AssociationTypeMismatch, message
    end
  end
end

```

### System configuration
**Rails version**:
5.1.4

**Ruby version**:
2.4.2

**Comment by eugeneius** [comment]
Rails 5.1 is no longer supported. Can you reproduce the problem on the latest version (6.0.1)?

**Comment by diskkid** [comment]
@hiphapis I think the root issue is that you use the same name for `belongs_to` and `foreign_key`, that is not a Rails bug. I recommend you to use a different name for `belongs_to` like `belongs_to :currency_object` (or just use `currency_id` for the column name).

I ran the same code on Rails 6.0.1, and got the following result. Even `Account.usd` does not work because of the name conflict.

```irb
Running via Spring preloader in process 22837
Loading development environment (Rails 6.0.1)
irb(main):001:0> Account.create(currency: Currency.create(name: 'usd'))
   (0.7ms)  SELECT sqlite_version(*)
   (0.2ms)  begin transaction
  Currency Create (0.5ms)  INSERT INTO "currencies" ("name", "created_at", "updated_at") VALUES (?, ?, ?)  [["name", "usd"], ["created_at", "2019-11-22 11:32:32.566242"], ["updated_at", "2019-11-22 11:32:32.566242"]]
   (8.3ms)  commit transaction
   (0.1ms)  begin transaction
  Account Create (0.4ms)  INSERT INTO "accounts" ("currency", "created_at", "updated_at") VALUES (?, ?, ?)  [["currency", "usd"], ["created_at", "2019-11-22 11:32:32.590014"], ["updated_at", "2019-11-22 11:32:32.590014"]]
   (5.4ms)  commit transaction
=> #<Account id: 1, currency: "usd", created_at: "2019-11-22 11:32:32", updated_at: "2019-11-22 11:32:32">
irb(main):002:0> Account.usd
Traceback (most recent call last):
        2: from (irb):2
        1: from app/models/account.rb:3:in `block in <class:Account>'
SystemStackError (stack level too deep)
```

**Comment by hiphapis** [comment]
@eugeneius @diskkid Thanks for comments.
I was wrong. The problem was using same name db field and relationship name
`accounts` table had `currency` field already(i didn't knew that) and define relationship `currency`
Sorry bother you. and close this ticket
