### ISSUE TITLE
Trouble using has_secure_password validations attribute with STI models

### ISSUE THREAD

**Issue by bynarlogic** [rails/rails#37755]
I'm not sure if this is a bug or if there is a better way to do this. I would like to be able to create GuestUsers without passwords but require passwords for normal Users. 

It looks like GuestUser is still getting the has_secure_password behavior from the parent class. I also tried checking the class name in the parent class and setting the validations flag dynamically. This didn't work either. 

```
class User < ApplicationRecord
  has_secure_password :password, validations: self.class == GuestUser ? false : true
end
```

### Steps to reproduce
```
class User < ApplicationRecord
  has_secure_password
end

class GuestUser < User
  has_secure_password :password, validations: false
end  
```

### Expected behavior
` $ gu = GuestUser.new`
`$ gu.save => true`
`$ u = User.new`
`$ u.save => false`

### Actual behavior
` $ gu = GuestUser.new`
`$ gu.save => false`

### System configuration
Rails 6.0.1

**Ruby version**:
Ruby 2.5.1p57

**Comment by K-S-A** [comment]
Hi @bynarlogic!

I believe, that the current behavior is expected. But you have a few options to achieve the one you need.

Add initializer to your project and overwrite existing `.has_secure_password` method. Here is the ad-hoc solution (not tested in a real project):

```
module StiCompatibleSecurePassword
  extend ActiveSupport::Concern
  
  class_methods do
    # https://github.com/rails/rails/blob/v6.0.0/activemodel/lib/active_model/secure_password.rb#L61-L88
    # Usage: `has_secure_password validations: ->(o) { !o.is_a?(GuestUser) }`
    def has_secure_password(options = {})
      begin
        require "bcrypt"
      rescue LoadError
        $stderr.puts "You don't have bcrypt installed in your application. Please add it to your Gemfile and run bundle install"
        raise
      end

      include ActiveModel::SecurePassword::InstanceMethodsOnActivation

      validations = options.fetch(:validations, true)

      if validations
        include ActiveModel::Validations

        validate do |record|
          next unless validations.respond_to?(:call) ? validations.call(record) : validations

          record.errors.add(:password, :blank) unless record.password_digest.present?
        end

        validates_length_of :password, maximum: ActiveModel::SecurePassword::MAX_PASSWORD_LENGTH_ALLOWED
        validates_confirmation_of :password, allow_blank: true
      end
    end
  end
end

ApplicationRecord.include(StiCompatibleSecurePassword)
```

I recommend adding custom validation instead of the default one as the above patch may require additional updates for new rails versions.
