### ISSUE TITLE
Randomly getting `undefined local variable or method 'mutations_from_database'`

### ISSUE THREAD

**Issue by fjaeger** [rails/rails#37768]
### Steps to reproduce
Unfortunately, this behavior is hard to reproduce and only happens randomly in our production environment. For some of our `ActiveRecord` models (inheriting from `ApplicationRecord`), we sometimes see the following errors:

`undefined local variable or method 'mutations_from_database'`
`undefined method 'partial_writes?'`
`undefined method 'assign_attributes'`

Somehow it seems that basic functionality that should be inherited from ActiveRecord is not available to our model instances. 
Could this be some kind of issue with application loading?

### Expected behavior
These errors should not appear as our model classes inherit from `ApplicationRecord`, which itself inherits from `ActiveRecord::Base`.

### Actual behavior
We see these errors appearing from time to time. Only in production and impossible to reproduce.

### System configuration
**Rails version**: 5.2.3

**Ruby version**: 2.5.7

**Comment by eileencodes** [comment]
Hey @fjaeger I understand that this is a hard issue to reproduce but there's not much here for us to go on to figure out what the issue could be. What webserver are you using? Do you have any gems that could be interfering? Can you add some instrumentation to your production instance to gather some data?

Unfortunately we don't have other reports of this. More information will give us some clues where the problem could be coming from. Thanks!

**Comment by fjaeger** [comment]
We use `puma` as the webserver with 5 threads. We have New Relic implemented in the production environment, but unfortunately it is not giving us any hints why this might happen from time to time.
I cannot think of any gem that could potentially interfere with basic `ActiveRecord` functionality – randomly :-(

**Comment by fjaeger** [comment]
We investigated the `ancestors` of the instance and it seems that `ActiveModel::Dirty` is not in that list – even though `ActiveRecord::Dirty` is. Any idea why this could happen?
If `ActiveModel::Dirty` was not available at boot time (not yet loaded), the `include` statement would have already thrown an error, right?

**Comment by Auralcat** [comment]
@fjaeger do you still experience this problem in your app with recent Rails versions? Can you please provide a sample application that reproduces the error, with the Ruby and Rails version you're using?

You can also create an executable test case following the instructions [here](https://guides.rubyonrails.org/contributing_to_ruby_on_rails.html#create-an-executable-test-case).

**Comment by kiawizard** [comment]
Exactly the same issue on latest 6.0.3.3
After running for several days/weeks, production environment Rails app throws:
NoMethodError (undefined method `partial_writes?' for #<User:0x00007fdb6170f5f0>)

Using nginx & Passenger latest, CentOS 8, Ruby 2.7.1p83

**Comment by n-rodriguez** [comment]
> Exactly the same issue on latest 6.0.3.3
> After running for several days/weeks, production environment Rails app throws:
> NoMethodError (undefined method `partial_writes?' for #User:0x00007fdb6170f5f0)
> 
> Using nginx & Passenger latest, CentOS 8, Ruby 2.7.1p83

Did you try to run your app with Puma?

**Comment by kiawizard** [comment]
Hi, n-rodriguez, thank you for the hint. I haven't tried Puma in production, using it in development only. I will arrange switching to Puma in production to see if it helps, but we'll get the results of this test after a while, maybe weeks

**Comment by kiawizard** [comment]
1 month of running Puma instead of Passenger, issue doesn't occur
