### ISSUE TITLE
ActionRecord::Sanitization, replace_named_bind_variables raises exception if timestamp format text present

### ISSUE THREAD

**Issue by f3ndot** [rails/rails#37779]
### Steps to reproduce

1. Have any database that is supported by Rails and has time formatting functions. (Postgres' `to_timestamp(text, text)` for example)
2. Connect to rails console and execute the following:

```ruby
raw_sql = "SELECT TO_TIMESTAMP(:date_str, 'YYYY/MM/DD HH12:MI:SS');"
ActiveRecord::Base.sanitize_sql([raw_sql, date_str: '2017/08/02 10:59:00'])
```

### Expected behavior

It should return, if given some form of escaping strategy (ie `::` or `\:`):

```ruby
"SELECT TO_TIMESTAMP('2017/08/02 10:59:00', 'YYYY/MM/DD HH12:MI:SS');"
```

### Actual behavior

Raises the following exception:

```ruby
ActiveRecord::PreparedStatementInvalid: missing value for :MI in SELECT TO_TIMESTAMP(:date_str, 'YYYY/MM/DD HH12:MI:SS');
from /Users/justin/.rbenv/versions/2.5.5/lib/ruby/gems/2.5.0/gems/activerecord-5.2.2.1/lib/active_record/sanitization.rb:198:in `block in replace_named_bind_variables'
```

### System configuration
**Rails version**: 5.2.2.1, 6.0.1

**Ruby version**: 2.5.5, 2.6.5

### Discussion

The issue at hand is due to [`replace_named_bind_variables`](https://github.com/rails/rails/blob/v6.0.1/activerecord/lib/active_record/sanitization.rb#L182-L192) providing no mechanism to escape the `:` character when it is not intended to be a named bind variable placeholder.

One workaround is to use non-named parameter binding (rely on `?`). This is a non-starter in my opinion as it doesn't take many variables for this to get confusing. Especially if you're using the same parameter multiple times throughout a large SQL query.

### Solution

I propose an escape character to indicate that a `:` is intended to be literal and not a placeholder for a variable.

For example:

```ruby
raw_sql = "SELECT TO_TIMESTAMP(:date_str, 'YYYY/MM/DD HH12\\:MI\\:SS');"
ActiveRecord::Base.sanitize_sql([raw_sql, date_str: '2017/08/02 10:59:00'])
# => "SELECT TO_TIMESTAMP('2017/08/02 10:59:00', 'YYYY/MM/DD HH12:MI:SS');"
```

Or, alternatively

```ruby
raw_sql = "SELECT TO_TIMESTAMP(:date_str, 'YYYY/MM/DD HH12::MI::SS');"
ActiveRecord::Base.sanitize_sql([raw_sql, date_str: '2017/08/02 10:59:00'])
# => "SELECT TO_TIMESTAMP('2017/08/02 10:59:00', 'YYYY/MM/DD HH12:MI:SS');"
```

**Comment by f3ndot** [comment]
Looks like [sqlalchemy prefers the backslash](https://docs.sqlalchemy.org/en/13/core/sqlelement.html#sqlalchemy.sql.expression.text):

> For SQL statements where a colon is required verbatim, as within an inline string, use a backslash to escape:
>
> ```
> t = text("SELECT * FROM users WHERE name='\:username'")
> ```

**Comment by f3ndot** [comment]
Verified `master` still has no approach for this scenario. I wrote a suggested approach in https://github.com/rails/rails/pull/37797

**Comment by vinayak-mehta** [comment]
@f3ndot We're also facing the same issue. What did you end up going with to solve this?

**Comment by f3ndot** [comment]
> @f3ndot We're also facing the same issue. What did you end up going with to solve this?

@vinayak-mehta I believed I copied my proposed solution as an initializer to override the ActiveRecord::Sanitization class, which isn't a great option but it allowed us to get our work done.

**Comment by skipkayhil** [comment]
I verified the reproduction still works on `main`
