### ISSUE TITLE
Rails 5.2 Multiple Databases Issue in Rails Console

### ISSUE THREAD

**Issue by bpirtle-nova** [rails/rails#37785]
### Steps to reproduce

Create a model that inherits from an abstract class model with a connection to a new database as the following example illustrates:
```
# models/icm_db_base.rb
class IcmDbBase < ActiveRecord::Base
  self.abstract_class = true
  establish_connection :icm_production
end
```
```
# models/icm_task.rb
class IcmTask < IcmDbBase
... model code here
end
```

### Expected behavior

The model inheriting from the class connected to database number 2 (In this case, :icm_production from the database.yml file) should be actually connected to database number 2 

### Actual behavior

Inside rails console, the models that should be connected to database number 2 is actually connected to database number 1 (The database that loads by default for ActiveRecord::Base).

Running IcmTask.establish_connection :icm_production in the console DOES connect properly to the :icm_production database after load, but we can't be doing this at runtime or the app is going to crash due to way too many connection pools being created.

Importantly, the models are loading the proper connection inside our puma web server and in sidekiq, just not in rails console.

Here is some testing to show the issue from rails console (I was able to reproduce both on production and development):
```
Loading development environment (Rails 5.2.3)
2.6.4 :001 > IcmTask.connection_config
=> DATABASE CONNECTION CONFIG FOR ActiveRecord::Base (DB number 1)

2.6.4 :002 > IcmTask.superclass
 => IcmDbBase(abstract) 

2.6.4 :003 > IcmDbBase.connection_config
 => DATABASE CONNECTION CONFIG FOR IcmDbBase (DB number 2 )
```

Additionally our rake tasks are not working in the same manner as rails console.

### System configuration
**Rails version**:
5.2.3

**Ruby version**:
2.6.4

**Comment by bpirtle-nova** [comment]
Turns out the innkeeper gem was overriding this connection inheritance behavior out of the box (Just by having it installed) so when I removed the gem it behaves as expected.

**Comment by Ankk98** [comment]
> Turns out the innkeeper gem was overriding this connection inheritance behavior out of the box (Just by having it installed) so when I removed the gem it behaves as expected.

Removing active_record_shards v4 beta 9 gem solved this issue for me.
