### ISSUE TITLE
Active Storage direct uploads specify key on pre signed url

### ISSUE THREAD

**Issue by Tiltorito** [rails/rails#37787]
Hello, 

I apologise for asking this question through Github but I can't seem to find an answer anywhere else. 

For active storage it looks like there is no validations for direct uploads and that makes sense since it goes directly to cloud. What I can't seem to find is a way to handle the generation of pre signed urls so I can enforce a file name, file size and other properties that cloud storage providers allow.

Is active storage used in production? If yes, how do people validate direct uploads?

**Comment by goalaleo** [comment]
@Tiltorito would writing you own validation work? e.g.
```
validate :file_not_too_large

def file_not_too_large
  if file.attached?
    if file.blob.byte_size > MAX_FILE_SIZE
      errors[:base] << 'Too big'
    end
  end
end
```
Or are you having problems with the file being uploaded even if the validations fail? If so, then it should be fixed in https://github.com/rails/rails/commit/e8682c5bf051517b0b265e446aa1a7eccfd47bf7

**Comment by chase439** [comment]
I think the OP was referring to authentication via pre-signed url to direct upload to the Cloud Storage as most people would configure bucket policies to prevent everyone from uploading to it. I'm having similar issues right now and may have to open a ticket if I can't figure it out.
