### ISSUE TITLE
WrongScopeError exception with edge rails

### ISSUE THREAD

**Issue by jasnow** [rails/rails#37783]
This morning (11/23/2019) I'm getting a new error with 3 repos. Here is an example repo.

### Steps to reproduce

 1. Clone this repo: https://github.com/jasnow/show-me-the-food5edge.git
 2. Run "rake" and it will cleanly:
```
Finished in 0.95708 seconds (files took 3.19 seconds to load)
1 example, 0 failures
```
 3. Run "bundle update" to get latest edge rails code.
 4. Run "rake" and get WrongScopeError exception. See details:
    https://gist.github.com/jasnow/2edc53d905d26870bb2e77221c71ab29
 5. This error did not occur on 11/22/2019.

### Expected behavior

Expect "rake" to run with no errors/exceptions. See step 2 above.

### Actual behavior

See step 4 above.

### System configuration

**Rails version**: 6.1.0.alpha

**Ruby version**: ruby 2.7.0preview2 (2019-10-22 master 02aadf1032) [x86_64-darwin16]

**Comment by jasnow** [comment]
Do ya'll need any more information?

**Comment by geetfun** [comment]
Temporary workaround if you must use edge rails and rspec:

- Add to your development and test groups in your Gemfile: `gem 'database_cleaner', '~> 1.7'`
- Modify your rails_helper.rb and add:

`  config.before(:suite) do
    DatabaseCleaner.strategy = :transaction
    DatabaseCleaner.clean_with(:truncation)
  end

  config.around(:each) do |example|
    DatabaseCleaner.cleaning do
      example.run
    end
  end`

- Comment out:

`config.fixture_path = "#{::Rails.root}/spec/fixtures"` and `config.use_transactional_fixtures = true` in rails_helper.rb

I'm not well versed enough on rspec's or the rails test framework internal workings, but this seemed to have helped in the interim for me.

**Comment by jasnow** [comment]
This appears to be the commit that introduced the "name" variable https://github.com/rails/rails/commit/d4367eb72601f6e5bba3206443e9d141e9753af8
@Edouard-chin

**Comment by Edouard-chin** [comment]
ACK, let me think of a way to fix it. Didn't know RSpec used `method_name` :(

**Comment by jasnow** [comment]
@Edouard-chin  - Rspec might be using "name" as a variable.

**Comment by Edouard-chin** [comment]
Attempted a fix in rspec-rails https://github.com/rspec/rspec-rails/pull/2215 as I don't think the fix should be in Rails itself.

**Comment by jasnow** [comment]
@Edouard-chin - Thanks for following up on this issue.

**Comment by eugeneius** [comment]
This has been addressed in https://github.com/rspec/rspec-rails/pull/2215.
