### ISSUE TITLE
StringInquirer for Rails.env is unnecessarily heavy

### ISSUE THREAD

**Issue by headius** [rails/rails#37803]
### Steps to reproduce
Call `Rails.env.development?` from any code.

### Expected behavior
It should not have to dispatch through `method_missing`.

### Actual behavior
It dispatches through `method_missing`

### System configuration
**Rails version**: 5+

**Ruby version**: all

In order to allow using `Rails.env.development?` instead of `Rails.env == 'development'`, the env string is currently forced into a StringInquirer instance:

https://github.com/rails/rails/blob/1ccc407e9dc95bda4d404c192bbb9ce2b8bb7424/railties/lib/rails.rb#L67-L81

StringInquirer in turn uses `method_missing` to turn the `development?` call into `self == "development"` by cropping off the `?`.

https://github.com/rails/rails/blob/1ccc407e9dc95bda4d404c192bbb9ce2b8bb7424/activesupport/lib/active_support/string_inquirer.rb

This is unnecessarily heavy:

* Dispatching through method_missing is generally more expensive than calling a simple method.
* A new string object must be constructed for each call.

This is also doing work for each call that is unnecessary; the content of the string does not change over time, so performing the check once would be sufficient.

In the application I was benchmarking, Redmine, this call was made at least once per request, and multiple times in some cases. I have heard anecdotal evidence from others that their apps may use `production?` and `test?` heavily to allow minor behavioral diffferences in those environments.

I believe this env string should instead use a subclass of String that defines proper methods for at least the standard three environments (development, test, and production), and if possible it should define such methods for all configurable environments in the boot configs.

```
class EnvironmentString < StringInquirer
  def initialize(env)
    @development = env == 'development'
    @test = env == 'test'
    @production = env == 'production'
  end

  def development?; @development; end
  def test?; @test; end
  def production?; @production; end
end
```

A more aggressive optimization would define these as singleton methods specific to the incoming env string; this would only be done once at env-setting time and therefore the singleton would not be any more significant in memory than having a specific named class for this purpose.

**Comment by tenderlove** [comment]
I think this kind of optimization is fine. OTOH people should not be examining Rails.env at runtime. Rather, they should configure things (like strategy objects etc) in the applicable environments configuration file.

IOW, adding this kind of optimization seems fine, but apps shouldn't need it in general.

**Comment by headius** [comment]
> IOW, adding this kind of optimization seems fine, but apps shouldn't need it in general.

I agree it's not great form to check env in application code, particularly code that runs on every request. But someone at some point added this convenience specifically so it's easy to query the current env. It should at least be as low-cost as possible.

**Comment by Tankard** [comment]
> I think this kind of optimization is fine. OTOH people should not be examining Rails.env at runtime. Rather, they should configure things (like strategy objects etc) in the applicable environments configuration file.
> 
> IOW, adding this kind of optimization seems fine, but apps shouldn't need it in general.

I complete agree that apps shouldn't need it in general. But a lot of apps that i worked on have those checks and it would be nice to benefit from such an optimization.

**Comment by vipulnsward** [comment]
Here's example from one of our Apps(many others do too): https://monosnap.com/file/aYYdp0WH6u6W8oKiB0TR2T0A3NNqdg

Think at this point, its a widely used check.

**Comment by headius** [comment]
I can put together a PR for the conservative impl later today.

**Comment by nirvdrum** [comment]
@headius It might be worthwhile dynamically defining the method the first time it passes through `method_missing`. Then you'd account for arbitrary environment names. Possibly with a cap on that so runaway apps don't blow up creating methods.

**Comment by headius** [comment]
@nirvdrum I chose not to do that in my upcoming patch since the main three environments will cover 99% of cases, and you can call literally anything against this object. It doesn't seem worth the extra complexity for nonstandard environments.

**Comment by nirvdrum** [comment]
@headius I'm not sure staging environments count as non-standard or only account for a tiny percentage of Rails usage. They just don't have a convenient name because there often is more than one of them in a given team. But, if the extra complexity doesn't pay for itself, so be it.

**Comment by bogdan** [comment]
We can use that amazing `define_method` inside `method_missing` strategy that is used quite actively in ActiveRecord.

**Comment by headius** [comment]
I am not opposed to defining the methods on the fly. I do not know the proper way to limit how many methods get defined, or if that's a concern for this case.

**Comment by headius** [comment]
Minor issues with defining on the fly:

* New singleton class for every instance of env. Usually there will only be one.
* Unlimited method definition unless we limit it in some way.

My preference would be to query configs for known environments and define them all on a non-singleton class at boot, but I do not know if that is possible.

**Comment by jeremy** [comment]
This is a fine special-case improvement to consider. Let's see the code and perf impact in a PR. Thanks for raising this and digging in, @headius!

**Comment by eregon** [comment]
@headius Does that relate to your tweet https://twitter.com/headius/status/1197972352488767489 ?
> Amazing how well JRuby works with so many optimizations still missing. I just added very basic caching of method_missing and improved Redmine requests/s by about 15%.

**Comment by headius** [comment]
I have pushed #37808 to address this. Open for discussion!

@eregon Not really.
