### ISSUE TITLE
rspec breaks on Rails head

### ISSUE THREAD

**Issue by geetfun** [rails/rails#37813]
### Steps to reproduce
Please clone test repo at https://github.com/geetfun/rspec_error for a demonstration of the error.

The repo's Gemfile has both references to a working commit and the latest Rails head. Using the last working commit and the latest commit, you'll be able to see the spec passing or failure, respectively, when running `bundle exec rspec`.

Last working commit: https://github.com/rails/rails/commit/3f1473379ce3eafc6f8a9912a7c4fb410745cac6

A simple rspec spec was written to demonstrate the breaking of specs.

Step-by-step instructions are in the repo's README.

### Expected behavior
rspec should continue to work

### Actual behavior
rspec breaks 

### System configuration
**Rails version**: Rails head

**Ruby version**: Ruby 2.6.5

**Comment by eugeneius** [comment]
This looks like it might be a duplicate of https://github.com/rails/rails/issues/37783.

**Comment by geetfun** [comment]
Yup -- https://github.com/rails/rails/issues/37783 does look like the same one.

Thanks @eugeneius.
