### ISSUE TITLE
User got session_id of another one

### ISSUE THREAD

**Issue by aurelien-reeves** [rails/rails#37812]
Hi,

We recently faced an issue where users was suddenly identified as another one.

- Rails 5.1.7
- Ruby 2.6.3
- Devise 4.7.1 with cookie store
- Puma 4.1.1

The issue appeared when we have deployed our first feature that used action-cable. The action-cable app is mounted inside the rails-app.

We think the issue is due to the following code that can still be found easily over the Internet:

```
module ApplicationCable
  class Connection < ActionCable::Connection::Base
    identified_by :current_user    def connect
      self.current_user = find_verified_user
    end    private    def find_verified_user
      if current_user = env['warden'].user
        current_user
      else
        reject_unauthorized_connection
      end
    end
  end
end
```

The thing is, we are not able to reproduce the issue, and we do not understand what is happening. We understand the code is not right and we will use a proper one using cookies, but we do not understand how that code led to user getting another session.

Does anyone have any idea to reproduce the issue we faced in a controlled environment?
Does anyone can explain how mixing action-cable and warden can led to user sessions being changed to another one?

**Comment by aurelien-reeves** [comment]
I allow myself to up that issue

We had some users able to show data from other ones, and still no idea how to reproduce it

**Comment by erykrozdolski** [comment]
We've encountered the same issue – after submiting a POST user became logged in as another user (who was using the system at the time too). This seems like a very serious security issue. 

We're not using action-cable ourselves, but it does appear in our Gemfile.lock. 

* Rails 6.0.0
* Ruby 2.6.3
* Phusion Passenger 6.0.4

We have no idea how to reproduce it and seems to be rare, but it has happened yesterday twice in a span of about an hour for the same user.

**Comment by aurelien-reeves** [comment]
Indeed I feel like it is a very serious security issue too.
We still have no clue on how to reproduce that. When it happened, we indeed had some users impacted. We were able to fix the issue by deactivating ActionCable but the fact that you do not have it puzzles me.

**Comment by jonathanhefner** [comment]
Unfortunately, without a reproduction script, we can't really help debug this issue.

However, this reminded me of an issue for the Clearance authentication gem.  Specifically, [this comment](https://github.com/thoughtbot/clearance/issues/781#issuecomment-372639938).  I know you said you're using Devise, but perhaps the discussion there is still relevant?

**Comment by aurelien-reeves** [comment]
That's the point of that issue: trying to find a way to reproduce the hijacking of user sessions to be able to have an automated test on it.

We still did not understand what happened. We just assumed this is because of using the following code into a `Connection < ActionCable::Connection::Base` mounted inside the rails app:
```
current_user = env['warden'].user
```

Also we can see the following in the Action Cable documentation (https://guides.rubyonrails.org/action_cable_overview.html#notes)
> The WebSocket server doesn't have access to the session

We are pretty sure this is related, but we do not know why or how it is related, and wy simply using a dedicated cookie seems to make it work.

**Comment by matthewford** [comment]
This happened to me with 7.0
