### ISSUE TITLE
Rails 6.0.2.rc1: Custom module in environment initializer not autoloaded anymore

### ISSUE THREAD

**Issue by doits** [rails/rails#37828]
In my `config/environments/development.rb` I use a custom module `MyModule`:

```rb
# config/environments/development.rb

Rails.application.configure do
  MyModule.do_something
end
```

`MyModule` lives at `app/domain/my_module.rb`.

Before 6.0.2.rc1 it was picked up by autoloader, now it raises a `NameError: uninitialized constant MyModule`.

The commit that introduced this is dede40ecadf632f72a1143396043a1994e65c839.

I think this a regression in a minor version change. It could be deprecated, but imo this should happen with `6.1` at the earliest, even if the behaviour of autloading such constants in environments was wrong and not intended.

---

I can work around it by having a ...

```rb
require Rails.root.join('app/domain/my_module')
```

... at the top of the file, but not sure if it has any side effects with the autoloader.

**Comment by fxn** [comment]
That should have been disallowed, but it was not (Rails 6 prints a warning if constants are autoloaded during boot).

You need to do that in a `to_prepare` callback so that it happens after boot, and the block of code is executed again on reload:

```ruby
Rails.application.config.to_prepare do
  MyModule.do_something
end
```

The second aspect is important because when you reload after editing `MyModule`, you want `MyModule.do_something` to execute the new code.

Now, if you do not want to reload `MyModule`, the `require` is good. It is also a good practice to declare that particular file is handled by you manually:

```ruby
Rails.autoloader.main.ignore("#{Rails.root}/app/domain/my_module.rb")
```

**Comment by doits** [comment]
My example was a bit misleading, of course I set some configuration based on my module I only want to have in that env ...

```rb
# config/environments/development.rb

Rails.application.configure do
  config.action_mailer.default_url_options = { host: MyModule.development_host }
end
```

> That should have been disallowed, but it was not (Rails 6 prints a warning if constants are autoloaded during boot).

There is no warning for me on Rails 6.0.1, so I'm not sure if the missing warning message is a bug or the constant is correclty loaded/reloaded?

> The second aspect is important because when you reload after editing MyModule, you want MyModule.do_something to execute the new code.

Yeah, with regards to my new example I knew that the config was not updated if I edited `MyModule.development_host` (which is reasonable).

> Now, if you do not want to reload MyModule, the require is good. It is also a good practice to declare that particular file is handled by you manually:

I want to reload it, it is used on other places, too (where reloading it makes sense).

**Comment by fxn** [comment]
Whether reloading is going to work depends on the booting internals.

In this case, it depends on what happens to `config.action_mailer.default_url_options`. Some railties read the config on boot to translate it into their own internal status when the app boots in initializers. Initializers do not run again when code is reloaded (the app is not rebooted).

In any case, I believe we can close?

**Comment by doits** [comment]
Not exactly sure if we can close it - is the workaround to require it ...

```rb
require Rails.root.join('app/domain/my_module')
```

... correct if I want to:

- Use that constant in an initializer
- Have it reloaded in development (used at other places) when edited?

If yes, I can live with that work around.

But anyway I still think that the missing error message about the constant is a bug then, because clearly it uses the constant (otherwise it would not raise a `NameError` in 6.0.2.rc1). But on 6.0.1 there is no deprecation message about it.

And if this is only *deprecated*, shouldn't it still continue work but be removed in the next version, not break on a minor version without any depraction message in versions before?

**Comment by fxn** [comment]
Reloading was not working before in your application.

In order to have something in that file that is reloaded, you need _at least_ to wrap the code in a `to_prepare` block (and do not write the `require`). But, that is not enough, you need also the cooperation of the railtie, which I probably has no public contract about what happens if you assign a different value in the configuration interface after booting the application. Event if it worked, you would be relying on undocumented behavior.

My recommendation is to not reload that class, or at least whatever provides the host name.

If there was no warning, yes that is something should be looked into.

**Comment by doits** [comment]
> Reloading was not working before in your application.

If you specifially mean `config.action_mailer.default_url_options` was not changed after I changed the code of `MyModule.development_host`, then you are right.

But otherwise `MyModule` was reloaded correctly. I just tested it on 6.0.1 in two ways:

1. Open `rails console`
2. `pp MyModule.development_host`
3. Edit `MyModule.development_host` method with text editor to return something different
4. `reload!` in console
5. `pp MyModule.development_host` returns the edited value

Second way:

1. In any controller action add a `pp MyModule.development_host`
2. Trigger that action - value is printed
3. Edit `MyModule.development_host` method with text editor to return something different
4. Trigger that action again - different value is printed

So for me it seems reloading `MyModule` works, even though it is used in the environment configuration block - or am I missing something?

Of course in both cases `config.action_mailer.default_url_options[:host]` still hat the old value, which makes sense and was no problem for me.

---

I just tried out the following (probably what you mean with wrapping it in a `to_prepare` block):

```rb
# config/environments/development.rb

Rails.application.configure do
  config.to_prepare do
    Rails.application.config.action_mailer.default_url_options = { host: MyModule.development_host }
  end
end
```

This now works with 6.0.2.rc1 and even changes `config.action_mailer.default_url_options[:host]` when I edit `MyModule.development_host` (because I assume the prepare block is executed every time a reload happens).

But I think this is now exactly what you mean with "no public contract about what happens if you assign a different value in the configuration interface after booting the application", right? So this cannot be the solution.

---

Thinking back about the reason why I use `MyModule` there and it is because it parses a config file (`config.yml`) where also the development host is written in (besides other configuration that is used all over the app) - so it has some complicated logic to extract the value I need in the environment initializer.

Does it mean I should never have used own modules or classes to configure Rails like this? I mean in my specific case I could parse the `config.yml` in the initializer to extract the host instead of using `MyModue`, but it does not feel clean.

And am I the only one doing this with Rails - is this so specific and uncommon that it will not break for others, too?

**Comment by doits** [comment]
I was curious about that if I am the only person doing this and wanted to look at some bigger rails projects, and the first one I looked at was discourse and it [has this](https://github.com/discourse/discourse/blob/1b8be069e5c43053b2b31b2e4f81a0d6b5fe2066/config/environments/development.rb#L61):

```rb
# config/environments/development.rb

Discourse::Application.configure do
  if emails = GlobalSetting.developer_emails
    ...
  end
end
```

`GlobalSetting` lives at `app/models/global_setting` and it worked, even when I updated the Rails app to 6.0.2.rc1, which confused me at first. I think it works because they [require the file](https://github.com/discourse/discourse/blob/87be6fe98c184bac0c9a50a988bff4be618da059/config/application.rb#L32) in `config/application.rb`

```rb
# config/application.rb

require_relative '../app/models/global_setting'
```

I then tested to see if `GlobalSetting` is reloaded in development - and it is not. I assume it is because it is manually required?

Finally I did the same in my app (requiring `MyModule` inf `config/application.rb`) and I could boot up my application with 6.0.2.rc1. Though now reloading `MyModule` in development was not working anymore.

---

So if I put everything together correctly, the outcome is:

Starting with Rails 6.0.2.rc1 own constants used in an environment initializer must be required manually beforehand. This has the side effect that they will not be reloaded in development.

With Rails 6.0.1 own constants in an environment initializer were autoloaded and reloaded automatically in development.

If this is really how it should be from now on (remember it is a minor version change), maybe at least it should be documented somewhere.

---

Maybe I am making too much noise about this because I am the only one who used it like this, but it broke my app - and I think that is exactly what you want to hear when people test out new rcs :-)

**Comment by fxn** [comment]
Hey! Quick reply from my phone.

There is a previous comment in which I show how to use a `to_prepare` block.

It is not uncommon to see constants autoloaded in initializers (now
deprecated), but in my experience doing so in the env configs is rare.

For development, what I’ve seen more frequently for your use case is to
hard-code the value in dev and test, and use env vars for staging,
production, etc.

If you want to have it in a config file, another option is to have that
accessible via a `Config` manager that loads things early, and from which
you can take the host in that spot. If you change the configuration, you
reboot the server.

Indeed, what I meant re the existing app was that reloading did not update
the host, but the module is certainly reloaded.
-- 
Sent from Gmail Mobile

**Comment by fxn** [comment]
Hey, after sleeping on this, I believe that patch should be reverted on 6-0-stable.

I treated not being able to change autoload paths in env files as a bug, but probably not having this breaking consequence is a better trade off in this branch.

I’ll do that soon, @rafaelfranca let me /cc you just to be coordinated for the next release.

**Comment by doits** [comment]
:+1:, glad to hear I have some more time until I need to refactor my config parsing :-) I think this is the right decision to not include this in a minor version bump - not because it affects *my* app but thinking as a product manager.

Maybe adding a deprecation message in such cases would be a good thing, though, but not sure how hard that is.

**Comment by fxn** [comment]
This has been reverted in `6-0-stable` and in `6-0-2`.

I'll investigate separately the warnings about autoloaded constants on boot, [they should be reported](https://github.com/rails/rails/blob/67b79238c4ab320427f03486c0b9b525f7b53e44/railties/lib/rails/application/finisher.rb#L51-L64).

I'll report back about what I find for completeness, but will close the ticket since the original issue has been solved.
