### ISSUE TITLE
Fix docs about etag

### ISSUE THREAD

**Issue by collimarco** [rails/rails#37829]
Currently [the example](https://github.com/rails/rails/blob/09a2979f75c51afb797dd60261a8930f84144af8/actionpack/lib/action_controller/metal/conditional_get.rb#L25) for **etag** is wrong and misleading. It generates a subtle bug that happens only in some circumstances / with some browsers and that it is very difficult to find (I have spent an entire day to find this bug).

Basically you should use this:

```
fresh_when etag: @article # correct
```

and not what you wrote in the docs:

```
fresh_when @article # incorrect
```

The problem with the second version is that a *Last Modified* header is also sent to the browser, making useless the **etag** declaration, since the _Last Modified_ does not consider the current user id!

**Comment by bollbollboll** [comment]
@collimarco 
It seems have fixed by https://github.com/rails/rails/pull/37921.
Could you close this?
