### ISSUE TITLE
URL helpers based on url_for ignore default_locale and default_url_options within tests

### ISSUE THREAD

**Issue by cseelus** [rails/rails#37820]
### Steps to reproduce
- Create a new Rails 6.0.1 application (`rails new myapp`)
- Scaffold a `Post` (`rails g scaffold post title:string content:text`)
- Confirm that all tests pass
- Follow the Rails Guides for the *Rails Internationalization (I18n) API*, in this example [*2.2 Managing the Locale across Requests*](https://guides.rubyonrails.org/i18n.html#managing-the-locale-across-requests) and [*2.2.2 Setting the Locale from URL Params*](https://guides.rubyonrails.org/i18n.html#setting-the-locale-from-url-params) (Set `config.i18n.available_locales` and `config.i18n.default_locale` via `application.rb`; Add `default_url_options` and `switch_locale` methods to `ApplicationController`; Add `scope` with locale to `routes`)
- Run the generated tests

[Sample application](https://github.com/cseelus/rails601default_locale)

### Expected behavior
All tests should (still) be green, as `config.i18n.default_locale` is set and `I18n.locale` is set via `default_url_options`.

### Actual behavior
Some URL helpers based on the url_for helper (`post_url(@post)` or `post_path(Post.first)`) raise an `ActionController::UrlGenerationError`:

```
ActionController::UrlGenerationError: No route matches {:action=>"show", :controller=>"posts", :locale=>#<Post id: 980190962, title: "MyString", content: "MyText", created_at: "2019-11-27 22:50:33", updated_at: "2019-11-27 22:50:33">}, missing required keys: [:id]
```

### System configuration
**Rails version**: 6.0.1

**Ruby version**: 2.6.5

**Comment by cseelus** [comment]
This is still an issue with Rails 6.0.2 and Rails `master`.

**Comment by cseelus** [comment]
… updated the sample app. @pixeltrix or anyone, can this be reopened?

**Comment by viktorianer** [comment]
Should be reopened. Still an issue in Rails system and integration tests.

Also, missing docs for this, see https://github.com/rails/rails/pull/46645
