### ISSUE TITLE
Multiple database method connected_to closes outer transaction

### ISSUE THREAD

**Issue by one-more-alex** [rails/rails#37837]
### Steps to reproduce
Simple setup with 2 write roles database with :primary and :secondary databases.
MySql2.

```ruby
User.transaction do 
 [User.count, User.connected_to(database: :secondary) { User.count }]; 
end
```

### Expected behaviour
Output count of users in database. Same number without errors.

### Actual behaviour
Erring by closing connection transaction on exit from #connected_to closes block.
Output like this:

```
User.transaction do [User.count, User.connected_to(database: :secondary) do User.count; end]; end
2019-11-29 22:01:47.481 [DEBUG]  (0.4ms)  BEGIN /*application:app*/ (pid:16917)
2019-11-29 22:01:47.515 [DEBUG]  (2.8ms)  SELECT COUNT(*) FROM `users` WHERE `users`.`active` = TRUE /*application:app*/ (pid:16917)
2019-11-29 22:01:47.565 [DEBUG]  (0.6ms)  SET NAMES utf8 COLLATE utf8_general_ci,  @@SESSION.sql_mode = CONCAT(CONCAT(@@sql_mode, ',STRICT_ALL_TABLES'), ',NO_AUTO_VALUE_ON_ZERO'),  @@SESSION.sql_auto_is_null = 0, @@SESSION.wait_timeout = 2147483 /*application:app*/ (pid:16917)
2019-11-29 22:01:47.607 [DEBUG]  (2.8ms)  SELECT COUNT(*) FROM `users` WHERE `users`.`active` = TRUE /*application:app*/ (pid:16917)
2019-11-29 22:01:47.628 [DEBUG]  (1.1ms)  COMMIT /*application:app*/ (pid:16917)
2019-11-29 22:01:47.641 [DEBUG]  (0.7ms)  ROLLBACK /*application:app*/ (pid:16917)
Traceback (most recent call last):
        1: from (irb):3
ActiveRecord::StatementInvalid (Mysql2::Error: MySQL client is not connected)
```

Interesting that User.connected_to(database: :primary) runs once correctly in Rails console, but the next runs fail with same error.

### System configuration
**Rails version**:
Rails 6.0.1
**Ruby version**:
ruby 2.6.3p62 (2019-04-16 revision 67580) [x86_64-linux]

**Comment by eileencodes** [comment]
Hey @one-more-alex thanks for the report. There's not enough information here for me to debug this problem. Please provide a sample application with steps to reproduce.

Without this the only thing I can guess at is you're not using the connections correctly. `connected_to` with the database key is specifically for one-off connections, and you should be using the `role` key in your application. The `database` key will establish a new connection every time and is not to be used in requests, as noted in the docs.

**Comment by eileencodes** [comment]
I don't think this is a bug per say. `connected_to` with the `database` kwarg will create a new connection so to use that inside a transaction is a bad idea.

Since I've had a lot of non-bug bug reports with the database key feature I've deprecated it in 6.1 and it will be removed in 6.2.  See https://github.com/rails/rails/pull/37874

**Comment by one-more-alex** [comment]
Thank you for explanation.
I agree, that naming of that method is confusing.

Currently will try to keep Octopus in code (did some patches of it to work in Rails 6 for myself in GIT fork https://github.com/one-more-alex/octopus).
Just expected to see in Rails 6 support of independent connection. Not sure if it called sharding.
Need to have ability to operate with database through independent established connections. I was thinking it is rather trivial thing.
As I remember, establish_connection changes whole Rails operate with that new connection. But I need it to work with two independent connections (actually to same database).

Thank you for your work to implement multiple database support in Rails.

**Comment by eileencodes** [comment]
> Need to have ability to operate with database through independent established connections. I was thinking it is rather trivial thing.

Yea, it's not trivial because previously there was no way to establish multiple connection to a database through one model. The underlying implementation to make that possible was done in https://github.com/rails/rails/pull/37622 which will be in 6.1 but the public facing API hasn't been completed yet (also aiming for 6.1). I think by 6.1 Rails will have everything you need to accomplish your goals.
