### ISSUE TITLE
ActionMailbox extends Mail, but extensions aren't used or documented

### ISSUE THREAD

**Issue by pwim** [rails/rails#37831]
ActionMailbox includes a number of undocumented extensions to the Mail gem. 

From my perusal of the source code, `action_mailbox/mail_ext/from_source.rb` and `action_mailbox/mail_ext/recipients.rb` are used internally. However, it appears the rest of them are not.

Is the intention for them to be used individual Rails applications, and documentation for them are just missing?

**Comment by georgeclaghorn** [comment]
> Is the intention for them to be used individual Rails applications, and documentation for them are just missing?

Yes, but we also intended to upstream the extensions to Mail proper. See rails/actionmailbox#6 and mikel/mail#1298. PRs welcome!

**Comment by pwim** [comment]
Awesome, thanks for clarifying!
