### ISSUE TITLE
PG::NotNullViolation: ERROR: null value in column "created_at"

### ISSUE THREAD

**Issue by chmich** [rails/rails#37840]
unbelievable!

Hi beloved Rails-Team!
may this be a rails-bug?

strange thing:

When i execute that code

```
def column_names
    case @import.group
    when 'antenna_project'
      col_names = Project.column_names
      theese_not = ['closed']
    when 'address'
      col_names = Address.column_names + Person.column_names
      theese_not = []
    end
    a = (['id',
          'created_at',
          'latitude',
          'longitude',
          'to_geocode',
          'updated_at',
          'created_by',
          'import_id',
          'location_string',
          'uid',
          'confirmed',
          'options',
          '100',
          'creation_time',
          'person_id',
          'active',
          'commited_helper'] + theese_not)
    # b = []
    # col_names.each {|cn| b.push(cn) unless a.include?(cn)}
    a.each {|e| col_names.delete(e)}
    res = (['-'] + col_names)
    res
end
```

and execute than, `Project.create(name: 'hello')`, i receipt `PG::NotNullViolation: ERROR: null value in column "created_at"`.
I spent days to find this, and tried soulutions like that: https://github.com/rails/rails/issues/24219.
I switched from mariadb (mysql2) to postgre, similar behaviour.

at the end i changed the last lines to

```
...
          'creation_time',
          'person_id',
          'active',
          'commited_helper'] + theese_not)
    b = []
    col_names.each {|cn| b.push(cn) unless a.include?(cn)}
    #a.each {|e| col_names.delete(e)}
    res = (['-'] + b)
    res
```

and now my app runs fine and creates records.
for me, it seems that the step `...delete(e)}` affects the Projects-model, but how can that be? 
`col_names` is a array.

Best regards,
Chris

**Comment by K-S-A** [comment]
Hi, @chmich!

Can you provide a minimal reproduction script or application?

**Comment by K-S-A** [comment]
From the first sight, I can say, that this might cause the problem:

```
col_names = Project.column_names
# => ['id', 'created_at', 'latitude', ...]
col_names.delete('created_at')
# => 'created_at'
Project.column_names
# => ['id', 'latitude', ...]
```
You're directly modifying cached class attribute https://github.com/rails/rails/blob/v6.0.0/activerecord/lib/active_record/model_schema.rb#L403-L405

**Comment by chmich** [comment]
Dear K-S-A,
that was the whole method.
but, to make it clearer, i added the first line `def ..` and the last line `end` to the code above.
it is a sub-method of a controller-method.

**Comment by K-S-A** [comment]
Try to rewritethis line: `col_names = Project.column_names.dup`

**Comment by K-S-A** [comment]
Yeah, I'm sure, that it will fix your problem.

**Comment by chmich** [comment]
Thanks K-S-A, `.dup` was the soulution!
Now, it runs with the original code.

Interesting, because `col_names` is browsed by the debugger as a simple array. That it is a cashed class-attribute, was new for me.

**Comment by K-S-A** [comment]
Yes, `col_names` was pointed to the same Array as `Project.column_names`. You can check it by calling `object_id` method on both of them.

In the case of `Address.column_names + Person.column_names` the result was a new Array and it worked just fine.

**Comment by chmich** [comment]
Thanks, Sergii!
