### ISSUE TITLE
Active-storage API only and ActiveStorage::Current.host

### ISSUE THREAD

**Issue by Tiltorito** [rails/rails#37841]
Active storage won't work out of the box with API only mode in rails.

```ruby
class ActiveStorage::BaseController < ActionController::Base
  protect_from_forgery with: :exception

  before_action do
    ActiveStorage::Current.host = request.base_url
  end
end
```
 
 ``` protect_from_forgery with: :exception ```

introduces problems on API only

``` ActiveStorage::Current.host = request.base_url ```

introduces problems when rails is behind a proxy because current host is used to generate the url path for the direct upload

**Comment by Auralcat** [comment]
@Tiltorito Do you still have this problem with recent Rails versions? Can you please provide a sample application that reproduces the error, with the Ruby and Rails version you're using in this case?

You can also create an executable test case as detailed [here.](https://guides.rubyonrails.org/contributing_to_ruby_on_rails.html#create-an-executable-test-case)
