### ISSUE TITLE
number_to_currency, negative zero when precision is 0

### ISSUE THREAD

**Issue by sporto** [rails/rails#37846]
### Steps to reproduce

```
> require 'action_view
> include ActionView::Helpers::NumberHelper
> number_to_currency -0.1, precision: 0

>  "-$0"
```

Negative zero is an unexpected format for users.

### Expected behavior
Only get "$0"

### Actual behavior
Return  "-$0"

### System configuration
**Rails version**:
6.0.0

**Ruby version**:
2.6.1

**Comment by hectorbus** [comment]
Hi @sporto! Can I solve this issue?

**Comment by eugeneius** [comment]
Closing as https://github.com/rails/rails/pull/37865 was merged.
