### ISSUE TITLE
First attempt to read from cache fails

### ISSUE THREAD

**Issue by spemmons** [rails/rails#37854]
### Steps to reproduce

- Start the Rails console
- Use Rails.cache.fetch to capture something in a Redis-based cache
- Use Rails.cache.read to confirm existence in the cache
- Use Redis client to enumerate the keys, and note that the key exists, also use Redis.get to confirm the value stored at the key
- Exit the Rails console
- Use Rails.cache.read to access the cached value -- result is nil
- Use Rails.cache.read to access the cached value again  - result is the expected value

### Expected behavior
The initial attempt to read the cached value should succeed

### Actual behavior
First attempt to read a cached value returns nil when an actual value exists

### System configuration
**Rails version**: 5.2.2.1

**Ruby version**: 2.6.5

**Comment by Auralcat** [comment]
Do you still experience this problem with Rails 6? Can you please provide a sample application that reproduces the error? I couldn't tell if this problem happens with a brand new app or if there are models or specific databases involved to reproduce the issue.
