### ISSUE TITLE
New Feature (Coded locally), ActiveSupport - new utility method similar to `except`

### ISSUE THREAD

**Issue by luke-hill** [rails/rails#37855]
I was looking through the guides and have started using `except` a lot on ActiveSupport

However, I'm working a lot with JSONAPI in my work, and have spent the best part of 2 days trying to get something to work that would work recursively and also inside nesting.

I've finally got it working and was just wondering whether it's worth committing it to ActiveSupport?

I do a fair amount in cucumber / selenium. But not sure of the policy here on Rails as I don't use it much (I'm a Senior QA Engineer)

Looking for someone who would review and critique / accept the PR or advise me against doing it.

Examples attached below
```
hash = {a: 1, b: 2, c: 3, d: { da: 1, db: 2}, e: 5, f: {fa: 1, fb:2, fc: 3}}

hash.except(:a) # => {b: 2, c: 3, d: { da: 1, db: 2}, e: 5, f: {fa: 1, fb:2, fc: 3}}
hash.except(:d) # => {a: 1, b: 2, c: 3, e: 5, f: {fa: 1, fb:2, fc: 3}}

# This one doesn't work
hash.except(:da) # => {a: 1, b: 2, c: 3, d: { da: 1, db: 2}, e: 5, f: {fa: 1, fb:2, fc: 3}}

# New code I've written
hash.except_nested(:da) # => {a: 1, b: 2, c: 3, d: {db: 2}, e: 5, f: {fa: 1, fb:2, fc: 3}}
hash.except_nested(:fc) # => {a: 1, b: 2, c: 3, d: {da: 1, db: 2}, e: 5, f: {fa: 1, fb:2}}
```

Any queries / questions hit me up!

**Comment by kaspth** [comment]
Thanks for bringing this up, I don't think this has a wide enough use case to be a fit for many applications. We do have some nesting/deep related methods, but I think we should leave it at the existing set.
