### ISSUE TITLE
 Routing Error No route matches [POST] "/establishments/15"

### ISSUE THREAD

**Issue by shivabhusal** [rails/rails#37864]
### Steps to reproduce
In Firefox, 

```ruby
# in routes.rb
resources :establishments
```
for this form code
```ruby
= form_for establishment do |f|
  = render 'images', establishment: establishment, f: f
  .row
    .form-group.col-md-6
      = f.label :name, 'Name *'
      = f.text_field :name, class: 'form-control'
      = f.error_message_for(:name)
    .form-group.col-md-6
      = f.label :kind, 'Kind *'
      = f.text_field :kind, class: 'form-control'
      = f.error_message_for(:kind)
    .form-group.mx-auto.mb-0.mt-4
      - if establishment.persisted?
        = f.submit 'Update', class: 'btn btn-primary btn-md'
      - else
        = f.submit 'Add', class: 'btn btn-primary btn-md'

javascript:
    window.mustang.est_kinds = #{est_kinds.to_json.html_safe};


```

---
#### Problem Description
**There is no problem in Safari and chrome, but there is in Firefox**

There are two ways to go to `establishments/:id/edit`page which uses `dashboard.slim` layout:- 
1) from `establishments/:id/`; this uses `application.slim` layout
2) from `dashboards/` page; this uses `dashboard.slim` layout

its ok when I use method 2, but when i use method 1, i see this error

<img width="480" alt="image" src="https://user-images.githubusercontent.com/8004593/70019958-3de57a80-15b3-11ea-8055-fa0908ce1ef4.png">

and in the form generated I see
```html
<input type="hidden" name="_method" value="WkWDJMUJKj9koDpS9Lx1hrxqG6Jkg7My6zlWmUSbdEinRCsMkLKklEo0nmlekVk+TUpxKjErfUrryiRw09b79A==">
```
when it should be

```html
<input type="hidden" name="_method" value="patch">
```

### System configuration
Problem is in Firefox only

**Rails version**:
5.2.3

**Ruby version**:
2.6.3

**Comment by eileencodes** [comment]
Hi @shivabhusal thanks for the report. Can you make a new application that demonstrates this issue without using slim? If it is only reproducible with slim then you should open an issue with that gem. Thanks!

**Comment by shivabhusal** [comment]
new thing; I turned off `Turbolinks` and the problem is gone; I am still digging deeper to know more.

**Comment by shivabhusal** [comment]
Also, I upgraded Rails from `5.2.3` to `rails (6.0.1)`; and still the problem persists.

**Comment by scd31** [comment]
```
<input type="hidden" name="_method" value="WkWDJMUJKj9koDpS9Lx1hrxqG6Jkg7My6zlWmUSbdEinRCsMkLKklEo0nmlekVk+TUpxKjErfUrryiRw09b79A==">
```
Is this code present in Safari/Chrome as well?

**Comment by shivabhusal** [comment]
@scd31 it is only present in firefox, not in other browsers like `chrome`, `safari`, `ie`

**Comment by scd31** [comment]
Very odd. Could it be a caching issue? Try refreshing the page with shift+f5

**Comment by shivabhusal** [comment]
refreshed and even cleared the cache; it weird

**Comment by scd31** [comment]
I'd recommend putting up a repo so that we can attempt to reproduce it.

**Comment by cspeer** [comment]
I had/have the same issue in Firefox (73.0.1 (64-bit), MacOS) @shivabhusal has.
I quit the browser, restarted it in safe mode, then the issue was gone. So I figured might have been an extension. But upon restarting Firefox in normal mode the issue was gone as well. Very weird.

Looks like base64 encoding

**Comment by duleorlovic** [comment]
Also on Firefox 73.0.1 on Ubuntu, hidden input was set to some long string (but it should be `patch`) and since Firefox keep all inputs, the problem stays after refresh.
```
<input type="hidden" name="_method" value="ASD13WLBQQDSeB7XC246cD9Y/LOsfXhq0ijuHtehEJ4RRH7oG1nzydVMHK6a2R">
```
Only hard refresh helps (hold shift while refreshing with mouse or keyboard). Next time I notice this I will try to reproduce...

**Comment by pzac** [comment]
Had the same issue with Firefox 74 on Mac. A hard refresh fixed the issue, soft refresh wasn't enough

**Comment by FFEVER** [comment]
I had the same issues. Firefox Developer 75.0b11 (64-bit) macOS Catalina
It renders a wired encoded string instead of `patch`. Hard refresh also helps.

**Comment by mkamensky** [comment]
Same problem here, with FF75. If I add `autocomplete=off` to the form, the problem goes away

**Comment by jonathanhefner** [comment]
I believe this issue is caused by a Firefox bug which has unfortunately been closed due to inactivity: https://bugzilla.mozilla.org/show_bug.cgi?id=520561.

**Comment by archonic** [comment]
Wow. @mkamensky you're a lifesaver. As if a 12 year old bug is what's causing this.

**Comment by dvodvo** [comment]
I can also confirm said behaviour and linked to Firefox (Mac).  Clearing cookies - or signing out, then back in - will reset matters in working order. A FF bug.  Exists to the day of this posting.    

Had not tried `Command(⌘)-Shift-R` *will try to remember to do so...*

**Comment by Akash3081** [comment]
check resourcesful routes
