### ISSUE TITLE
WSL problems with manual creation of views

### ISSUE THREAD

**Issue by JeanSikorski** [rails/rails#37877]
### Steps to reproduce
Manually creating a View - html.erb - file of the expected name for a given route, say "Show" in this case.

### Expected behavior
Well, the html page should render.

### Actual behavior
The lovely "No template for interactive request - nameOfControllerController#show is missing a template for request formats: text/html" error shows up.
Sometimes, not sure why I get a "We're sorry, but something went wrong" error.

### System configuration
Using WSL - Ubuntu 18.4 LTS on a Windows10 machine
Editing via Visual Code Studio
Testing with Firefox via localhost:3000
Created using `rails new blog --skip-spring --skip-listen`
Using `rails server -u webrick`
Ruby -v 2.6.3p62
Rails -v 6.0.1

Additional information I suppose might be useful
I'm very new to Rails, and was following the "Getting Started with Rails" steps.
With the command `rails g controller NameOfController nameOfView` the automatically created view works wonders. However, if I already have a controller I'm unable to add views to it via this command, given how it already exists, unless I destroy it and well, that's just no good. So what I'm doing is right clicking the file structure at the appropriate folder (e.g. apps/views/articles/) and creating the file show.html.erb.

Here's my file structure and the `routes.rb` file
![fileStructure](https://user-images.githubusercontent.com/58498075/70111636-a5daa600-1631-11ea-880c-4948338721a4.PNG)

Here's the terminal output from launching the server to the error
![terminalOutput](https://user-images.githubusercontent.com/58498075/70111642-abd08700-1631-11ea-9063-6ddb4221e32a.PNG)

Here's the ArticlesController file
![articleController](https://user-images.githubusercontent.com/58498075/70111743-f5b96d00-1631-11ea-8c4e-0c558b4649ea.PNG)

I am losing my mind, for everywhere I look people seem to do this and it just works.

If anyone needs further information I'll happily provide.
Thank you for your help and have a nice day.

**Comment by khiav223577** [comment]
Maybe there is file permission issue? Try copy `new.html.erb` and rename it to `show.html.erb`.

**Comment by bikramwp** [comment]
Not entirely sure about your reported error, but I've seen the error "We're sorry, but something went wrong." happen when I created the Rails project using `--skip-keeps` and then deleted the `app/assets/images` directory. Maybe you are missing that or some other directory used by the asset pipeline (sprockets) ?

**Comment by jonathanhefner** [comment]
I don't use Windows, so I'm not sure how much help I can offer, but it might be easier to debug if you post an app here on GitHub that reproduces the problem.  Note that git tracks file permissions, so if it is a permissions issue, it may become more obvious.
