### ISSUE TITLE
Not able to db:create. Error You may have encountered a bug in the Ruby interpreter or extension libraries.. 

### ISSUE THREAD

**Issue by teekenl** [rails/rails#37880]
### Steps to reproduce

I have setup from rails apps and bundle install to download all necessary extension libraries. And then i i have also install postgres and postgis via Homebrew. However, I have an issue when I ran `bin/rake db:create` 

I encountered the issue in the below.
<img width="627" alt="Screen Shot 2019-12-04 at 7 15 40 pm" src="https://user-images.githubusercontent.com/13831887/70138113-7cba2400-16ca-11ea-89f9-544f4cc2838a.png">

### Expected behavior

it should be able to create database/table.

### Actual behavior

But I encountered unknown interpreter bug that I could not figure what's wrong with my configuration and environment.

### System configuration
**Rails version**:
4.2.7 

**Ruby version**:
2.3.7

**Postgres version**
11.6

**Comment by Edouard-chin** [comment]
Without more detail we can't help you much sadly. Also note that you are using a very old version of Rails which isn't supported nor maintained. Same for the ruby version which isn't supported by Rails anymore.
I'd suggest upgrading your ruby version to at least 2.5 and Rails to 6.0 and try if you can reproduce the issue

**Comment by teekenl** [comment]
@Edouard-chin  i found out the issue it was because `spring loader` was using incompatible version of rake that is different from `Gemfile.lock` I will close down this issue
