### ISSUE TITLE
Getting Started Guide: Error caused by http_basic_authentication_with

### ISSUE THREAD

**Issue by samwarring** [rails/rails#37887]
### Steps to reproduce

I'm following the "Getting Started Guide" [here](https://guides.rubyonrails.org/getting_started.html). Everything works fine until I reach [9.1 Basic Authentication](https://guides.rubyonrails.org/getting_started.html#basic-authentication). The guide says to add the following line to articles_controller.rb:

`http_basic_authenticate_with name: "dhh", password: "secret", except: [:index, :show]`

This leaves my articles_controller.rb looking like this:

```
class ArticlesController < ApplicationController

    http_basic_authentication_with name: "dhh", password: "secret", except: [:index, :show]

    def index
        @articles = Article.all
    end

    def show
        @article = Article.find(params[:id])
    end

   # .... truncated ....
```

### Expected behavior

The guide explains that by adding this line, attempts to delete existing articles will produce a user/password prompt:
![image](https://user-images.githubusercontent.com/3435114/70189049-12dc5300-16a7-11ea-9e96-3f69b4b2905b.png)

### Actual behavior

When I add the `http_basic_authenticate_with` line, attempts to visit the article index page (`x.x.x.x:3000/articles`) produce the following error:
![image](https://user-images.githubusercontent.com/3435114/70189229-9bf38a00-16a7-11ea-8885-9128f2b083b8.png)

### System configuration
**Rails version**: 6.0.1

**Ruby version**: ruby 2.5.1p57 (2018-03-29 revision 63029) [x86_64-linux-gnu]

I'm sorry if this is too noob a question, or if it belongs in another forum. I'm brand new to rails and web development in general. I'm probably missing something obvious. Any help is appreciated! :-)

**Comment by georgeu2000** [comment]
It's a good question (I think) and the answer is

    except: [:index,

This bypasses the basic auth for the index action.

`@articles = Article.all` will set the `@articles` variable and not raise the error. Most likely it is misspelled in the controller or view.
