### ISSUE TITLE
Migrations containing an array of int4range don't set column default correctly

### ISSUE THREAD

**Issue by durkie** [rails/rails#37909]
### Steps to reproduce
Create a postgresql database `rangetest`.
Run the code at https://gist.github.com/durkie/3ac9169c830accb56bdfc5880dec9779

### Expected behavior
When creating a database migration to add a column of `int4range[]`, setting the column default to `[]` (as with other array types) should work (it doesn't).

When working around this by setting the column default to `'{}'`, that value should persist across migrations.

### Actual behavior
After adding the column of `int4range[]` with a column default of `[]`, a `TypeError` is raised with the message "can't quote Array" and the migration doesn't complete.

After adding the column of `int4range[]` with a column default of `'{}'`, the migration completes successfully, but the column default gets converted to `[]` when dumping the schema (which in turn raises the "can't quote Array" error if you try to create a new database from that schema)

### System configuration
**Rails version**: 6.0.1

**Ruby version**: 2.6.5

**Comment by durkie** [comment]
Tested again: this still seems to occur on Rails 6.0.2.1

**Comment by durkie** [comment]
Is there a way to re-open this?

**Comment by fatkodima** [comment]
@durkie Can you verify this is still happening on the latest version? Works for me.
