### ISSUE TITLE
API scaffold generator doesn't reference jbuilder partials correctly when namespaced

### ISSUE THREAD

**Issue by joshleblanc** [rails/rails#37925]
### Steps to reproduce
1. Create a new rails project
2. Run `rails generate scaffold api/user email:uniq password:digest --api`
3. Look at `app/views/api/users/index.json.jbuilder`, it references `api_users/api_user`, not `api/users/api_user`

### Expected behavior
The partial references should be `api/users/api_user`

### Actual behavior
The partial referenced is `api_users/api_user`, which doesn't exist.

### System configuration
**Rails version**: Rails 6.0.1

**Ruby version**: ruby 2.6.5p114 (2019-10-01 revision 67812) [x64-mingw32]

**Comment by joshmn** [comment]
Might want to open this in [jbuilder](https://github.com/rails/jbuilder); the generator which you mention lives there.

**Comment by joshleblanc** [comment]
Thanks, I've posted it there
