### ISSUE TITLE
Passing custom options to enqueuing callbacks

### ISSUE THREAD

**Issue by shqear93** [rails/rails#37949]
### Steps to reproduce
Allow passing options to activejob enqueuing callbacks, something like this should be supported :
`MyJob.set(message_group_id: some_id).perform_later(something)` 
Check [enqueuing.rb](https://github.com/rails/rails/blob/efbab359290d73fc7270599f4e05a59862f8080a/activejob/lib/active_job/enqueuing.rb#L55-L57) file

Please check this issue, integrating with shoryuken
https://github.com/phstc/shoryuken/issues/4

### Expected behavior
Send message to the queue with custom options

### Actual behavior
* Only wait, wait_until, queue and priority are supported, everything else are ignored
* Send message to the queue with custom options

### System configuration
**Rails version**:
Rails 5.1.3

**Ruby version**:
ruby 2.4.4p296 (2018-03-28 revision 63013) [x86_64-linux]

**Comment by kaspth** [comment]
This template is for bug reports not feature requests. In the future, we don't take feature requests on the issues tracker, try the rubyonrails-core mailing list then.

Don't think we want to support this, pass the argument to perform somewhere in the argument list `MyJob.perform_later(message_group)` (note missing `_id` to take advantage of GlobalID) and extract it like `before_enqueue { |job| group = job.arguments.first }` or add a `def self.schedule(message_group); perform_later(message_group) if message_group.whatever?; end` to conditionally enqueue it.
