### ISSUE TITLE
Trix editor's text alignment and image alignment support [Feature request]

### ISSUE THREAD

**Issue by gvpmahesh** [rails/rails#37952]
It's a good move that Trix is integrated into Rails natively via Action Text. Thanks for that. I would love to see the alignment of text and images so that it can be made more accessible to people who like to work with aligning items. Also image resize would be a nice to have

There are couple of issues related to the items I specified in the Trix repo. But those are closed and in some case, maintainer's the Trix repo mentioned they would not be working on them
https://github.com/basecamp/trix/issues/289
https://github.com/basecamp/trix/issues/136
https://github.com/basecamp/trix/issues/578

So since rails integrated Trix, would any of the rails community will be working on them? While I understand

```
Trix is a WYSIWYG editor for writing messages, comments, articles, and lists—the simple documents most web apps are made of.
```

But having alignment to things would make Trix and Rails awesome IMHO

Sorry in advance if this is not relevant

**Comment by CarlosCD** [comment]
I have the need to support right-aligned languages, as well as left-aligned. This would be a great feature to have.

**Comment by ChenMorStory** [comment]
Me too. That'd be spectacular!

**Comment by rafaelfranca** [comment]
Thank you so much for the issue but we don't take feature request on the issue tracker. We recommend you to try to implement the feature and send us a pull request or if you are in doubt if the feature will be accepts ask in Rails Core mailing list for feedback.

**Comment by Slowwie** [comment]
I am just new to trix. That's not possible to enable text-alignment is kind of sad. 
So I have to use ckEditor again.
Hope this feature will be added in the future.
