### ISSUE TITLE
@rails/* of package.json have not updated in rails new template

### ISSUE THREAD

**Issue by taketo1113** [rails/rails#37964]
### Steps to reproduce

- Generate new rails app with `rails new`

### Expected behavior

- It should be latest version of npm package of @rails/* in package.json

I think it should use version number with `Rails::VERSION::STRING` in template of package.json for package of @rails/*
  - https://github.com/rails/rails/blob/master/railties/lib/rails/generators/rails/app/templates/package.json.tt

### Actual behavior

- The packages of @rails/* is old version(6.0.0) in package.json

```
{
  "name": "rails_sample",
  "private": true,
  "dependencies": {
    "@rails/actioncable": "^6.0.0",
    "@rails/activestorage": "^6.0.0",
    "@rails/ujs": "^6.0.0",
  },
  "version": "0.1.0"
}
```

### System configuration
**Rails version**: 6.0.2

**Ruby version**: 2.6.5

**Comment by mikekolganov** [comment]
I think current behaviour is correct. `^6.0.0` in semver (package.json is using semver) means "any version greater or equal 6.0.0 is accepted but less than 7.0.0". When you doing `npm install` for first time after generating app npm will fetch latest version of `@rails/...` packages for you.

**Comment by taketo1113** [comment]
> `^6.0.0` in semver (package.json is using semver) means "any version greater or equal 6.0.0 is accepted but less than 7.0.0".

I know a versioning of 'semver' in package.json.
but, I think it's clear to be going to use latest version, when use version number with `^6.0.2` (rails version) in package.json.
