### ISSUE TITLE
Postgres adapter raises error when using a cursor with a read replica

### ISSUE THREAD

**Issue by dlangevin** [rails/rails#37960]
Read replicas are not allowed to create cursors in the Postgres adapter.  This should be allowed as Postgres has no problem doing this with a replicated database.  It looks like the problem is in `active_record/connection_adapters/postgresql/database_statements.rb:70`

```ruby
        READ_QUERY = ActiveRecord::ConnectionAdapters::AbstractAdapter.build_read_query_regexp(
          :begin, :commit, :explain, :select, :set, :show, :release, :savepoint, :rollback, :with
        ) # :nodoc:
        private_constant :READ_QUERY

        def write_query?(sql) # :nodoc:
          !READ_QUERY.match?(sql)
        end
```

The `build_read_query_regexp` should allow the following keywords:
```ruby
:declare,
:fetch,
:move,
:open,
:close
```

Happy to submit a PR if you agree with that approach

### Steps to reproduce
Attempt to declare a cursor when using a read replica (I used `postgresql-cursor`, but you could re-create this with raw SQL as well).  Test case reproducing this below:
```ruby
# frozen_string_literal: true

require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  # Activate the gem you are reporting the issue against.
  gem "activerecord", "6.0.1"
  gem "pg"
  gem "postgresql_cursor"
end

require "active_record"
require "pg"
require "postgresql_cursor"
require "minitest/autorun"
require "logger"



ActiveRecord::Base.logger = Logger.new(STDOUT)

class Post < ActiveRecord::Base
end

class BugTest < Minitest::Test
  def setup
    ActiveRecord::Base.configurations = {
      default_env: {
        primary: {
          adapter: "postgresql",
          database: "ar_test_1"
        },
        replica: {
          adapter: "postgresql",
          database: "ar_test_1",
          replica: true
        }
      }
    }
    ActiveRecord::Base.establish_connection
    ActiveRecord::Base.connects_to(database: { writing: :primary, reading: :replica })
    ActiveRecord::Schema.define do
      create_table :posts, force: true do |t|
      end
    end
  end

  def teardown
    Post.delete_all
  end

  def test_association_stuff
    Post.create!
    ActiveRecord::Base.connected_to(role: :reading) do
      assert_equal([{ "id" => 1 }], Post.all.each_hash.map { |hash| hash })
    end
  end
end
```

### Expected behavior
The reads should execute as expected

### Actual behavior
The following error is raised: `ActiveRecord::ReadOnlyError: Write query attempted while in readonly mode: declare cursor_CURSORNAME no scroll cursor for SELECT...`

### System configuration
**Rails version**:
6.0.1

**Ruby version**:
2.6.5

**Comment by simi** [comment]
> Happy to submit a PR if you agree with that approach

@dlangevin according to #37902 seems like valid approach.

**Comment by eileencodes** [comment]
I'm going to rework this code so I'll add these in when I do that.
