### ISSUE TITLE
Strong Parameters + Nested URL resources

### ISSUE THREAD

**Issue by gurkanoluc** [rails/rails#37982]
### Steps to reproduce

Have nested resources in your `routes.rb`

```ruby
resources :products do
    resources :reviews
  end
```

When I do `rails routes` I get

```ruby
 POST   /products/:product_id/reviews(.:format)                                                    products#create
```

In the UI, I make the request to `/products/1/reviews` with `Accept` header set to `application/json`. Post body is like 

```json
{ "body": "fooooobar" }
```

In the rails s output it's shown as

```
Started POST "/products/1/reviews" for 83.100.141.1 at 2019-12-16 06:49:03 +0000
Processing by ReviewsController#create as JSON
  Parameters: {"body"=>"fooooobar", "product_id"=>"1"}
```

### Actual behavior

In the Rails server output, I get

```
Unpermitted parameter: :product_id
```

### Expected behavior

Since I have defined the routes intentionally, shouldn't `product_id` be already permitted? 

It does go away if I permit `product_id` explicitly.

### System configuration

**Rails version**: 6.0.1

**Ruby version**: ruby 2.6.3-p62

**Comment by DSKonstantin** [comment]
Hi @gurkanoluc. I'm not sure, but it looks like your parameters should have wrapper? 

`Parameters: { "products"=>{"body"=>"fooooobar"}, "product_id"=>"1"}`

**Comment by gurkanoluc** [comment]
Hey there,

It was something I disabled explicitly, would it affect that?

**Comment by DSKonstantin** [comment]
You need to have:

```
def create
  @review = Review.new(review_params)
  if @review.save
    ....
  else
    ....
  end
end

private

def review_params
  params.fetch(:review, {}).permit(:body, .......)
end
```


end try use params like it:
`Parameters: {"review"=>{"body"=>"fooooobar"}, "product_id"=>"1"}
`
