### ISSUE TITLE
UTC offset is backwards for Etc/GMT-* timezones?

### ISSUE THREAD

**Issue by aardvarkk** [rails/rails#37989]
### Steps to reproduce

```
pry(main)> ActiveSupport::TimeZone['Europe/Rome'].utc_offset
=> 3600
pry(main)> ActiveSupport::TimeZone['Etc/GMT+1'].utc_offset
=> -3600
```

### Expected behavior

These values should both be 3600, since that's the offset *from* UTC *to* the given time zone. Rome is "one hour ahead" of GMT, which seems to match with common interpretations on sites like this: https://24timezones.com/time-zone/gmt+1

### Actual behavior

The 'ETC'-prefaced timezones seem to have the opposite interpretation of the offset, describing the offset from the timezone *to* UTC.

### System configuration
**Rails version**: 5.2.3

**Ruby version**: 2.6.5

**Comment by eugeneius** [comment]
This is reproducible without Rails:

```ruby
irb(main):001:0> require "tzinfo"
=> true
irb(main):002:0> TZInfo::Timezone.get("Europe/Rome").current_period.utc_offset
=> 3600
irb(main):003:0> TZInfo::Timezone.get("Etc/GMT+1").current_period.utc_offset
=> -3600
```

It seems to be expected behaviour: https://github.com/eggert/tz/blob/2019c/etcetera#L37-L43
