### ISSUE TITLE
Key (blob_id)=(13) is not present in table "active_storage_blobs"

### ISSUE THREAD

**Issue by mukeshpatel12** [rails/rails#37984]
I am upgrading `rails 5.2` to `rails 6`. In our application, we were already using active storage. Now as it rails 6 for active storage it adds a migration but it's giving me error for an existing record

### Steps to reproduce

1. Install active storage in rails 5.2 application
2. Updated ruby `ruby 2.6.3p62` and rails `6.0.2.rc2` version
3. run `rails app:update task`
4. run rails db:migrate (to run migration created for actove storage`

### Expected behaviour

Migration should be run successfully on existing records and for new records

### Actual behaviour

Getting an error `PG::ForeignKeyViolation: ERROR:  insert or update on table "active_storage_attachments" violates foreign key constraint "fk_rails_c3b3935057"
DETAIL:  Key (blob_id)=(13) is not present in table "active_storage_blobs"`

### System configuration
**Rails version**:
`Rails 6.0.2.rc2`

**Ruby version**:
`ruby 2.6.3p62 (2019-04-16 revision 67580)`

This migration comes from active_storage (originally 20180723000244)
```
class AddForeignKeyConstraintToActiveStorageAttachmentsForBlobId < ActiveRecord::Migration[6.0]
  def up
    return if foreign_key_exists?(:active_storage_attachments, column: :blob_id)
    if table_exists?(:active_storage_blobs)
      add_foreign_key :active_storage_attachments, :active_storage_blobs, column: :blob_id
    end
  end
end
```

**Comment by prathamesh-sonpatki** [comment]
Looks like you have some records in `active_storage_attachements` with `blob_id` 13 but corresponding record with `id` 13 is no longer present in the `active_storage_blobs` table.

You can solve this by taking a careful look at the data and deleting orphan records from the `active_storage_attachments` table. I am closing this issue as it is not really a Rails issue but a data issue in your application.

**Comment by mukeshpatel12** [comment]
@prathamesh-sonpatki this is is the old blob issue which was not getting purge properly which was suppose to be fix on rails 6. Even if I delete this it will have same issue will occur for some other records.

**Comment by enowmbi** [comment]
I had the same issue after updating from rails 5.2 to 6.0.2.2. I ran a check between active_storage_attachments and active_storage_blobs and noticed that in active_storage_attachments there was an entry with blob_id 13 but there was no record in active_storage_blobs with an id of 13.  I deleted the record in active_storage_attachments and ran the migration. it was successful.
