### ISSUE TITLE
Any rails action failing with undefined method 'plain_specs'

### ISSUE THREAD

**Issue by jasondborneman** [rails/rails#37993]
### Steps to reproduce
Any rails action `rails s`, `rails c`, `rake db:create`, `rake db:migrate`

This started over the weekend sometime between 12/13-1216. Don't recall installing any updates in that time but it's possible a forced upgrade was done from corporate when I rebooted this morning. I tried updating rubygems from 3.0.x to 3.1.1 and that did not alter the problem.

This is happening on my development Mac (Mojave) as well as on AWS Linux EC2 machines that were working as of 4 days ago as well.

### Expected behavior
The commands in question should work as expected.

### Actual behavior
Errors
```
/Users/XXXXX/.rvm/rubies/ruby-2.3.3/lib/ruby/gems/2.3.0/gems/rubygems-bundler-1.4.5/lib/rubygems-bundler/noexec.rb:84:in `setup': undefined method `plain_specs' for #<Bundler::RubygemsIntegration:0x007fa6279f59f0> (NoMethodError)
        from /Users/XXXXX/.rvm/rubies/ruby-2.3.3/lib/ruby/gems/2.3.0/gems/rubygems-bundler-1.4.5/lib/rubygems-bundler/noexec.rb:124:in `check'
        from /Users/XXXXX/.rvm/rubies/ruby-2.3.3/lib/ruby/gems/2.3.0/gems/rubygems-bundler-1.4.5/lib/rubygems-bundler/noexec.rb:131:in `<top (required)>'
        from /Users/XXXXX/.rvm/rubies/ruby-2.3.3/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:168:in `require'
        from /Users/XXXXX/.rvm/rubies/ruby-2.3.3/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:168:in `rescue in require'
        from /Users/XXXXX/.rvm/rubies/ruby-2.3.3/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:178:in `require'
        from /Users/XXXXX/.rvm/rubies/ruby-2.3.3/lib/ruby/gems/2.3.0/gems/rubygems-bundler-1.4.5/lib/rubygems_executable_plugin.rb:4:in `block in <top (required)>'
        from /Users/XXXXX/.rvm/rubies/ruby-2.3.3/lib/ruby/gems/2.3.0/gems/executable-hooks-1.6.0/lib/executable-hooks/hooks.rb:50:in `block in run'
        from /Users/XXXXX/.rvm/rubies/ruby-2.3.3/lib/ruby/gems/2.3.0/gems/executable-hooks-1.6.0/lib/executable-hooks/hooks.rb:49:in `each'
        from /Users/XXXXX/.rvm/rubies/ruby-2.3.3/lib/ruby/gems/2.3.0/gems/executable-hooks-1.6.0/lib/executable-hooks/hooks.rb:49:in `run'
        from /Users/XXXXX/.rvm/gems/ruby-2.3.3@tacos/bin/ruby_executable_hooks:10:in `<main>'
```

### System configuration
**Rails version**: 5.2.3

**Ruby version**: 2.3.3

**Rubygems version**: 3.1.1

**Comment by louim** [comment]
It seems to be an issue with RVM and the `rubygems-bundler` gem. See here: https://github.com/bundler/bundler/issues/7488

**Comment by jasondborneman** [comment]
Hmm. rubygems-bundler is not installed in my gemset being used, nor is it in my Gemfile. So perhaps it is with them but just removing that is a red herring on my problem at least.

**Comment by jasondborneman** [comment]
Fixed it locally at least. I had to delete rubygems-bundler from the GLOBAL gemset.
https://github.com/bundler/bundler/issues/7488#issuecomment-566249802
