### ISSUE TITLE
ActiveJob retry jitter produces unexpected results when jitter set to 0.0

### ISSUE THREAD

**Issue by cpruitt** [rails/rails#37990]
https://github.com/rails/rails/pull/37923 allows the configuration of the random jitter for ActiveJob retry delays. Specifying a jitter value of `0.0` for exponential retries seems like it should result in no randomness being added to the retry delay. Instead, as it currently is, a jitter value of zero ends up adding a fractional second. This is because a jitter value `0.0` ends up passing `0.0` into `Kernel.rand` here: https://github.com/rails/rails/blob/master/activejob/lib/active_job/exceptions.rb#L133 in `Kernel.rand((executions**4) * jitter)`.

This is additionally unexpected given that any other jitter value (e.g. 0.01) will produce a random integer, not a fractional float. This prevents the ability to fully disable jitter by configuring a zero value. It seems that a jitter value of `0.0` (or a falsey value like `nil` or `false`) should bypass jitter entirely.

Related: There may be similiar issues with passing `ActiveSupport::Duration` and `Integer` values into `determine_delay`.

I'm happy to open a PR for this but wanted to open an issue first because @kaspth mentioned working on some changes that sound like they may directly impact this. See: https://github.com/rails/rails/pull/37923#discussion_r357445670

cc @kaspth / @jeremy to avoid stepping on work in progress. 🙂
cc @eileencodes for visibility

**Comment by jeremy** [comment]
Nice catch! Zero/falsey should def. disable.

**Comment by kaspth** [comment]
@cpruitt sorry I wasn't clear in that comment, I actually gave up there and wanted to post how far I had gotten as a help. Please look into this 🙏

**Comment by cpruitt** [comment]
@kaspth no worries. Sorry I misunderstood. I'm happy to take a pass at it. 🙂

**Comment by kaspth** [comment]
Cool, I’m happy to help review 😄
