### ISSUE TITLE
Confusing protect_from_forgery/before_action behavior can lead to CSRF

### ISSUE THREAD

**Issue by Becojo** [rails/rails#37992]
### Steps to reproduce
Given those controllers
```ruby
class ApplicationController < ActionController::Base
  protect_from_forgery with: :null_session

  before_action :ensure_logged_in

  def ensure_logged_in
    unless session[:user_id]
      raise 'Not logged in'
    end
  end
end
```

```ruby
# scaffolded controller
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  protect_from_forgery with: :null_session
  # [...]
end
```

When a request comes in to a non-GET action of the `ProductsController` that does not contain a valid CSRF token, the `before_action :ensure_logged_in` is executed with a valid session even though both controller asks for a null session when an invalid CSRF token is provided.

This code doesn't look like it's skipping CSRF protection but it does have the same effect. 

### Expected behavior
I expect `ensure_logged_in` to be executed with a null session.

### Actual behavior
I expect `ensure_logged_in` is executed with a valid session, bypassing CSRF protection.

### System configuration
**Rails version**: Rails 6.0.2

**Ruby version**: 2.6.5p114

**Comment by Edouard-chin** [comment]
When you add the `protect_from_forgery with: :null_session` the second time (in the ProductsController), it overrides the previously defined one (in the ApplicationController) which had precedence over all `before_action` callbacks.

To fix your issue you have 2 options:

1. Move the `protect_from_forgery` call in the ProductsController before all before_action callback defined
2. Add `prepend: true` when calling `protect_from_forgery`

https://github.com/rails/rails/blob/6cde5fd30a367b3fcfb9144e1d946525813e0181/actionpack/lib/action_controller/metal/request_forgery_protection.rb#L124-L126

**Comment by Becojo** [comment]
I'm aware they are ways to fix the code I gave. It's a common bug pattern.

>It is by design that the CSRF check get run at the location it was called

Does it make sense that a child class redefining the forgery protection settings bumps up the verify_authenticity_token before_action into the callback chain by default? Even with `prepend: true`, it would move it at the beginning of the callback chain (right?) which could also have unexpected results if the parent class expects it to be in between other callbacks. 

My main issue here is that this has security consequences as it is so easy to mess up. When inheriting from a controller that puts a CSRF check first, I expect the child and parent controllers to also have this behavior. Calling `protect_from_forgery` again in a child should probably raise a warning that you are exposing your parent controller to CSRF.

**Comment by chitrarani** [comment]
@Becojo , protect_from_forgery always execute before your callbacks unless you have prepend: true. I think, there is no point to include 'protect_from_forgery' in two places.

this blog 'https://www.veracode.com/blog/managing-appsec/when-rails-protectfromforgery-fails'  explains the confusing part of the protect_from_forgery.

**Comment by chitrarani** [comment]
@Becojo , protect_from_forgery always execute before your callbacks unless you have prepend: true.
As this method prepends the verify_authenticity_token check before all controller actions.
By default protect_from_forgery protects your session with :null_session method, which provides an empty session during request but doesn't reset it completely.
If you want reset your session completely then use with option :reset_session.

If we make a non get request with invalid CSRF token, verify_authenticity_token method gives us the warning message "Can't verify CSRF token authenticity", it does not halt the execution unless you attempt to modified the db with request params.

This blog explains the good explanation of how protect_from_forgery works - 'https://www.veracode.com/blog/managing-appsec/when-rails-protectfromforgery-fails'.
