### ISSUE TITLE
Activerecord not working

### ISSUE THREAD

**Issue by prathap442** [rails/rails#37996]

**Comment by prathap442** [comment]
This happens after i have updated the rails app from the 3.2 to 5 version

**Comment by eugeneius** [comment]
Rails 5 isn't supported for bug fixes any more, can you test whether this happens on Rails 6.0?

You'll also need to provide a sample application that reproduces the problem.

**Comment by prathap442** [comment]
No we cannot push to rails 6.0 as that is not the requirement that comes. Here is some more information that we have done we have changed all the models to inherit from the applicationRecord instead of the ActiveRecord::Base and then created the model application_record.rb





app/models/application_record.rb
```
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end
````

and now every model inherits from the ApplicationRecord

**Comment by prathap442** [comment]
> I have a class by name video and have some associations also being defined but it seems like when i create the objects out of the model Video then they behave in a wiered way
> ### Expected behaviour
> 
> @videos.first.guid
> 
> ```
>     12345678
> ```
> 
> ### Actual behavior
> 
> ```
> D, [2019-12-17T14:11:46.867619 #32358] DEBUG -- :   Video Load (1.2ms)  SELECT  videos.*, 
>           UPPER(videos.title), 
>           UPPER(videos.publisher_name) FROM "videos" WHERE (videos.purged_at IS NULL) AND (1=1) AND (1=1) AND (1=1) AND (1=1) AND (videos.deleted_at IS NULL AND videos.status IN ('complete', 'inprogress')) ORDER BY videos.created_at DESC NULLS LAST, videos.id LIMIT $1  [["LIMIT", 1]]
> D, [2019-12-17T14:11:46.875742 #32358] DEBUG -- :   Library Load (0.5ms)  SELECT "libraries".* FROM "libraries" WHERE "libraries"."id" = 5
> => #<Video:0x00005605c9df9100
>  id: 10,
>  title: "Sample Video",
>  status: "inprogress",
>  description: "A sample video to get you started!",
>  user_id: nil,
>  created_at: Mon, 16 Dec 2019 05:30:30 UTC +00:00,
>  upload_finished: false,
>  publisher_name: "sample",
>  company_id: 5,
>  guid: "12345678",
>  main_asset_id: nil,
>  container_type: nil,
>  codec: nil,
>  library_id: 5,
>  deleted_at: nil,
>  purged_at: nil,
>  hits_count: 0,
>  hidden: false,
>  plays_count: 0,
>  updated_at: Mon, 16 Dec 2019 05:30:30 UTC +00:00,
>  upload_protocol: nil,
>  main_screenshot_id: nil,
>  parent_id: nil,
>  upload_method: nil,
>  youtube_id: nil,
>  tubemogul_id: nil,
>  album_id: nil,
>  audio_insight: nil,
>  visual_insight: nil,
>  audio_insight_duration: nil>
> ```
> 
> ```
> [2]pry(#<VideosController>)>  @videos.first.guid
> => nil
> ```
> 
> ### System configuration
> 
> Rails 5
> 
> **Ruby version**:
> 2.6.3

**Comment by prathap442** [comment]
The things worked fine as there where some file requiring that are going wrong
