### ISSUE TITLE
'rails new project' command returns error code 1 even if successful as of 6.0.2

### ISSUE THREAD

**Issue by geerlingguy** [rails/rails#38001]
### Steps to reproduce

```
$ rails new demo
      create  
      create  README.md
      create  Rakefile
      create  .ruby-version
      create  config.ru
      create  .gitignore
      create  Gemfile
         run  git init from "."

$ echo $?
1
```

### Expected behavior

The return code should be `0`, if the project is created successfully.

### Actual behavior

As of Rails 6.0.2, the return code is `1`, even though there are no errors when creating the project.

I was first alerted to this when one of my automation CI jobs started failing a few days ago, on the `rails new demo` task which creates a demo project to use for testing: https://travis-ci.org/geerlingguy/ansible-role-passenger/builds/625131105#L644

In all previous rails releases, the return code was `0`.

### System configuration
**Rails version**: 6.0.2

**Ruby version**: 2.5.1p57

**Comment by scd31** [comment]
I was unable to reproduce this.

```
>rails -v
Rails 6.0.2.1

>rails new test123
...

>echo $?
0
```

**Comment by geerlingguy** [comment]
I just ran locally:

```
 15:02:34 ~/Downloads/test $ rails -v
Rails 6.0.2.1

 15:03:47 ~/Downloads/test $ rails new demo
      create  
...
Using webpacker 4.2.2
Bundle complete! 17 Gemfile dependencies, 75 gems now installed.
Use `bundle info [gemname]` to see where a bundled gem is installed.
         run  bundle binstubs bundler
The dependency tzinfo-data (>= 0) will be unused by any of the platforms Bundler is installing for. Bundler is installing for ruby but the dependency is only for x86-mingw32, x86-mswin32, x64-mingw32, java. To add those platforms to the bundle, run `bundle lock --add-platform x86-mingw32 x86-mswin32 x64-mingw32 java`.
         run  bundle exec spring binstub --all
* bin/rake: Spring inserted
* bin/rails: Spring inserted
       rails  webpacker:install
Yarn not installed. Please download and install Yarn from https://yarnpkg.com/lang/en/docs/install/

 15:04:02 ~/Downloads/test $ echo $?
1
```

It's still failing inside the CI test environment too :/

Note that I ran it multiple times (`rm -rf demo` then `rails new demo` again) and it keeps giving me an rc of `1`. This is on a Mac on Catalina, and I also ran it in two different Dockerized environments.

**Comment by scd31** [comment]
To me, that seems to be pretty clearly failing. It is complaining that yarn is not installed.

**Comment by vipulnsward** [comment]
> Yarn not installed. Please download and install Yarn from https://yarnpkg.com/lang/en/docs/install/

Is failing on yarn not being found. Else will look like so:

> ✨  Done in 5.88s.
> Webpacker successfully installed 🎉 🍰
> ➜  echo $?
> 0

**Comment by geerlingguy** [comment]
Locally that seems to have fixed it. I didn't realize pre-installing yarn was a new requirement for Rails 6. After installing yarn via `brew install yarn`, `rails new` exits cleanly locally after setup is complete (though it seems to download about 10x more stuff than before for a fresh project—150 MB for 20,000 files just to get started :P).

However I'm still getting rc 1 on my CI builds, so I'm going to dig in and see why that's happening.

**Comment by Kutala-Abhiram** [comment]
My rails version is 6.0.2.1
**Before installing yarn:**New project got created but it showed me
      run  bundle exec spring binstub --all
* bin/rake: Spring inserted
* bin/rails: Spring inserted
       rails  webpacker:install
Yarn not installed. Please download and install Yarn from https://yarnpkg.com/lang/en/docs/install/
So, i installed Yarn
**After installing yarn:**I'm getting
rails new demo
      create  
      create  README.md
      create  Rakefile
      create  .ruby-version
      create  config.ru
      create  .gitignore
      create  Gemfile
         run  git init from "."

Anyone help me, thanks in advance

**Comment by gafanhoto1234** [comment]
> My rails version is 6.0.2.1
> **Before installing yarn:** New project got created but it showed me
> run bundle exec spring binstub --all
> 
> * bin/rake: Spring inserted
> * bin/rails: Spring inserted
>   rails  webpacker:install
>   Yarn not installed. Please download and install Yarn from https://yarnpkg.com/lang/en/docs/install/
>   So, i installed Yarn
>   **After installing yarn:** I'm getting
>   rails new demo
>   create
>   create  README.md
>   create  Rakefile
>   create  .ruby-version
>   create  config.ru
>   create  .gitignore
>   create  Gemfile
>   run  git init from "."
> 
> Anyone help me, thanks in advance

sudo apt install git 
sudo apt install yarn
sudo apt install nodejs
🐱
