### ISSUE TITLE
already initialized constant issue

### ISSUE THREAD

**Issue by kockok** [rails/rails#38014]
This is for a freshly generated rails app, not yet modified. 

# Steps to reproduce
`gem install rails`
`rails new testapp`
`cd testapp`
`rails s`

### Expected behavior
no such kind of warnings

### Actual behavior
multiple lines of warnings in the console.

### System configuration
**Rails version**:
6.0.2
**Ruby version**:
2.6.5

<details>
<summary>Click to expand</summary>
> /Users/jason/.rbenv/versions/2.6.5/lib/ruby/2.6.0/x86_64-darwin19/etc.bundle: warning: already initialized constant Etc::SC_AIO_LISTIO_MAX
> /Users/jason/.rbenv/versions/2.6.5/lib/ruby/2.6.0/x86_64-darwin19/etc.bundle: warning: already initialized constant Etc::SC_AIO_MAX
> /Users/jason/.rbenv/versions/2.6.5/lib/ruby/2.6.0/x86_64-darwin19/etc.bundle: warning: already initialized constant Etc::SC_AIO_PRIO_DELTA_MAX
> /Users/jason/.rbenv/versions/2.6.5/lib/ruby/2.6.0/x86_64-darwin19/etc.bundle: warning: already initialized constant Etc::SC_ARG_MAX
> /Users/jason/.rbenv/versions/2.6.5/lib/ruby/2.6.0/x86_64-darwin19/etc.bundle: warning: already initialized constant Etc::SC_ATEXIT_MAX
> /Users/jason/.rbenv/versions/2.6.5/lib/ruby/2.6.0/x86_64-darwin19/etc.bundle: warning: already initialized constant Etc::SC_BC_BASE_MAX
> /Users/jason/.rbenv/versions/2.6.5/lib/ruby/2.6.0/x86_64-darwin19/etc.bundle: warning: already initialized constant Etc::SC_BC_DIM_MAX
> /Users/jason/.rbenv/versions/2.6.5/lib/ruby/2.6.0/x86_64-darwin19/etc.bundle: warning: already initialized constant Etc::SC_BC_SCALE_MAX
> /Users/jason/.rbenv/versions/2.6.5/lib/ruby/2.6.0/x86_64-darwin19/etc.bundle: warning: already initialized constant Etc::SC_BC_STRING_MAX
> /Users/jason/.rbenv/versions/2.6.5/lib/ruby/2.6.0/x86_64-darwin19/etc.bundle: warning: already initialized constant Etc::SC_CHILD_MAX
> /Users/jason/.rbenv/versions/2.6.5/lib/ruby/2.6.0/x86_64-darwin19/etc.bundle: warning: already initialized constant Etc::SC_CLK_TCK
> /Users/jason/.rbenv/versions/2.6.5/lib/ruby/2.6.0/x86_64-darwin19/etc.bundle: warning: already initialized constant Etc::SC_COLL_WEIGHTS_MAX
> /Users/jason/.rbenv/versions/2.6.5/lib/ruby/2.6.0/x86_64-darwin19/etc.bundle: warning: already initialized constant Etc::SC_DELAYTIMER_MAX
> /Users/jason/.rbenv/versions/2.6.5/lib/ruby/2.6.0/x86_64-darwin19/etc.bundle: warning: already initialized constant Etc::SC_EXPR_NEST_MAX
> /Users/jason/.rbenv/versions/2.6.5/lib/ruby/2.6.0/x86_64-darwin19/etc.bundle: warning: already initialized constant Etc::SC_HOST_NAME_MAX
> /Users/jason/.rbenv/versions/2.6.5/lib/ruby/2.6.0/x86_64-darwin19/etc.bundle: warning: already initialized constant Etc::SC_IOV_MAX
> /Users/jason/.rbenv/versions/2.6.5/lib/ruby/2.6.0/x86_64-darwin19/etc.bundle: warning: already initialized constant Etc::SC_LINE_MAX
> /Users/jason/.rbenv/versions/2.6.5/lib/ruby/2.6.0/x86_64-darwin19/etc.bundle: warning: already initialized constant Etc::SC_LOGIN_NAME_MAX
> /Users/jason/.rbenv/versions/2.6.5/lib/ruby/2.6.0/x86_64-darwin19/etc.bundle: warning: already initialized constant Etc::SC_NGROUPS_MAX
> /Users/jason/.rbenv/versions/2.6.5/lib/ruby/2.6.0/x86_64-darwin19/etc.bundle: warning: already initialized constant Etc::SC_GETGR_R_SIZE_MAX
> /Users/jason/.rbenv/versions/2.6.5/lib/ruby/2.6.0/x86_64-darwin19/etc.bundle: warning: already initialized constant Etc::SC_GETPW_R_SIZE_MAX
> /Users/jason/.rbenv/versions/2.6.5/lib/ruby/2.6.0/x86_64-darwin19/etc.bundle: warning: already initialized constant Etc::SC_MQ_OPEN_MAX
> /Users/jason/.rbenv/versions/2.6.5/lib/ruby/2.6.0/x86_64-darwin19/etc.bundle: warning: already initialized constant Etc::SC_MQ_PRIO_MAX
> /Users/jason/.rbenv/versions/2.6.5/lib/ruby/2.6.0/x86_64-darwin19/etc.bundle: warning: already initialized constant Etc::SC_OPEN_MAX
> /Users/jason/.rbenv/versions/2.6.5/lib/ruby/2.6.0/x86_64-darwin19/etc.bundle: warning: already initialized constant Etc::SC_ADVISORY_INFO
> /Users/jason/.rbenv/versions/2.6.5/lib/ruby/2.6.0/x86_64-darwin19/etc.bundle: warning: already initialized constant Etc::SC_BARRIERS
> /Users/jason/.rbenv/versions/2.6.5/lib/ruby/2.6.0/x86_64-darwin19/etc.bundle: warning: already initialized constant Etc::SC_ASYNCHRONOUS_IO
> /Users/jason/.rbenv/versions/2.6.5/lib/ruby/2.6.0/x86_64-darwin19/etc.bundle: warning: already initialized constant Etc::SC_CLOCK_SELECTION
> /Users/jason/.rbenv/versions/2.6.5/lib/ruby/2.6.0/x86_64-darwin19/etc.bundle: warning: already initialized constant Etc::SC_CPUTIME
> /Users/jason/.rbenv/versions/2.6.5/lib/ruby/2.6.0/x86_64-darwin19/etc.bundle: warning: already initialized constant Etc::SC_FSYNC
> /Users/jason/.rbenv/versions/2.6.5/lib/ruby/2.6.0/x86_64-darwin19/etc.bundle: warning: already initialized constant Etc::SC_IPV6
> /Users/jason/.rbenv/versions/2.6.5/lib/ruby/2.6.0/x86_64-darwin19/etc.bundle: warning: already initialized constant Etc::SC_JOB_CONTROL
> /Users/jason/.rbenv/versions/2.6.5/lib/ruby/2.6.0/x86_64-darwin19/etc.bundle: warning: already initialized constant Etc::SC_MAPPED_FILES
> /Users/jason/.rbenv/versions/2.6.5/lib/ruby/2.6.0/x86_64-darwin19/etc.bundle: warning: already initialized constant Etc::SC_MEMLOCK
> /Users/jason/.rbenv/versions/2.6.5/lib/ruby/2.6.0/x86_64-darwin19/etc.bundle: warning: already initialized constant Etc::SC_MEMLOCK_RANGE
> /Users/jason/.rbenv/versions/2.6.5/lib/ruby/2.6.0/x86_64-darwin19/etc.bundle: warning: already initialized constant Etc::SC_MEMORY_PROTECTION
> /Users/jason/.rbenv/versions/2.6.5/lib/ruby/2.6.0/x86_64-darwin19/etc.bundle: warning: already initialized constant Etc::SC_MESSAGE_PASSING
> /Users/jason/.rbenv/versions/2.6.5/lib/ruby/2.6.0/x86_64-darwin19/etc.bundle: warning: already initialized constant Etc::SC_MONOTONIC_CLOCK
> /Users/jason/.rbenv/versions/2.6.5/lib/ruby/2.6.0/x86_64-darwin19/etc.bundle: warning: already initialized constant Etc::SC_PRIORITIZED_IO
> /Users/jason/.rbenv/versions/2.6.5/lib/ruby/2.6.0/x86_64-darwin19/etc.bundle: warning: already initialized constant Etc::SC_PRIORITY_SCHEDULING
> /Users/jason/.rbenv/versions/2.6.5/lib/ruby/2.6.0/x86_64-darwin19/etc.bundle: warning: already initialized constant Etc::SC_RAW_SOCKETS
> /Users/jason/.rbenv/versions/2.6.5/lib/ruby/2.6.0/x86_64-darwin19/etc.bundle: warning: already initialized constant Etc::SC_READER_WRITER_LOCKS
> /Users/jason/.rbenv/versions/2.6.5/lib/ruby/2.6.0/x86_64-darwin19/etc.bundle: warning: already initialized constant Etc::SC_REALTIME_SIGNALS
> /Users/jason/.rbenv/versions/2.6.5/lib/ruby/2.6.0/x86_64-darwin19/etc.bundle: warning: already initialized constant Etc::SC_REGEXP
> /Users/jason/.rbenv/versions/2.6.5/lib/ruby/2.6.0/x86_64-darwin19/etc.bundle: warning: already initialized constant Etc::SC_SAVED_IDS
> /Users/jason/.rbenv/versions/2.6.5/lib/ruby/2.6.0/x86_64-darwin19/etc.bundle: warning: already initialized constant Etc::SC_SEMAPHORES
> /Users/jason/.rbenv/versions/2.6.5/lib/ruby/2.6.0/x86_64-darwin19/etc.bundle: warning: already initialized constant Etc::SC_SHARED_MEMORY_OBJECTS
> /Users/jason/.rbenv/versions/2.6.5/lib/ruby/2.6.0/x86_64-darwin19/etc.bundle: warning: already initialized constant Etc::SC_SHELL
> /Users/jason/.rbenv/versions/2.6.5/lib/ruby/2.6.0/x86_64-darwin19/etc.bundle: warning: already initialized constant Etc::SC_SPAWN
> /Users/jason/.rbenv/versions/2.6.5/lib/ruby/2.6.0/x86_64-darwin19/etc.bundle: warning: already initialized constant Etc::SC_SPIN_LOCKS
> /Users/jason/.rbenv/versions/2.6.5/lib/ruby/2.6.0/x86_64-darwin19/etc.bundle: warning: already initialized constant Etc::SC_SPORADIC_SERVER
> /Users/jason/.rbenv/versions/2.6.5/lib/ruby/2.6.0/x86_64-darwin19/etc.bundle: warning: already initialized constant Etc::SC_SS_REPL_MAX
> /Users/jason/.rbenv/versions/2.6.5/lib/ruby/2.6.0/x86_64-darwin19/etc.bundle: warning: already initialized constant Etc::SC_SYNCHRONIZED_IO
> /Users/jason/.rbenv/versions/2.6.5/lib/ruby/2.6.0/x86_64-darwin19/etc.bundle: warning: already initialized constant Etc::SC_THREAD_ATTR_STACKADDR
> /Users/jason/.rbenv/versions/2.6.5/lib/ruby/2.6.0/x86_64-darwin19/etc.bundle: warning: already initialized constant Etc::SC_THREAD_ATTR_STACKSIZE
> /Users/jason/.rbenv/versions/2.6.5/lib/ruby/2.6.0/x86_64-darwin19/etc.bundle: warning: already initialized constant Etc::SC_THREAD_CPUTIME
> /Users/jason/.rbenv/versions/2.6.5/lib/ruby/2.6.0/x86_64-darwin19/etc.bundle: warning: already initialized constant Etc::SC_THREAD_PRIO_INHERIT
> /Users/jason/.rbenv/versions/2.6.5/lib/ruby/2.6.0/x86_64-darwin19/etc.bundle: warning: already initialized constant Etc::SC_THREAD_PRIO_PROTECT
> /Users/jason/.rbenv/versions/2.6.5/lib/ruby/2.6.0/x86_64-darwin19/etc.bundle: warning: already initialized constant Etc::SC_THREAD_PRIORITY_SCHEDULING
> /Users/jason/.rbenv/versions/2.6.5/lib/ruby/2.6.0/x86_64-darwin19/etc.bundle: warning: already initialized constant Etc::SC_THREAD_PROCESS_SHARED
> /Users/jason/.rbenv/versions/2.6.5/lib/ruby/2.6.0/x86_64-darwin19/etc.bundle: warning: already initialized constant Etc::SC_THREAD_SAFE_FUNCTIONS
> /Users/jason/.rbenv/versions/2.6.5/lib/ruby/2.6.0/x86_64-darwin19/etc.bundle: warning: already initialized constant Etc::SC_THREAD_SPORADIC_SERVER
> /Users/jason/.rbenv/versions/2.6.5/lib/ruby/2.6.0/x86_64-darwin19/etc.bundle: warning: already initialized constant Etc::SC_THREADS
> /Users/jason/.rbenv/versions/2.6.5/lib/ruby/2.6.0/x86_64-darwin19/etc.bundle: warning: already initialized constant Etc::SC_TIMEOUTS
> /Users/jason/.rbenv/versions/2.6.5/lib/ruby/2.6.0/x86_64-darwin19/etc.bundle: warning: already initialized constant Etc::SC_TIMERS
> /Users/jason/.rbenv/versions/2.6.5/lib/ruby/2.6.0/x86_64-darwin19/etc.bundle: warning: already initialized constant Etc::SC_TRACE
> /Users/jason/.rbenv/versions/2.6.5/lib/ruby/2.6.0/x86_64-darwin19/etc.bundle: warning: already initialized constant Etc::SC_TRACE_EVENT_FILTER
> /Users/jason/.rbenv/versions/2.6.5/lib/ruby/2.6.0/x86_64-darwin19/etc.bundle: warning: already initialized constant Etc::SC_TRACE_EVENT_NAME_MAX
> /Users/jason/.rbenv/versions/2.6.5/lib/ruby/2.6.0/x86_64-darwin19/etc.bundle: warning: already initialized constant Etc::SC_TRACE_INHERIT
> /Users/jason/.rbenv/versions/2.6.5/lib/ruby/2.6.0/x86_64-darwin19/etc.bundle: warning: already initialized constant Etc::SC_TRACE_LOG
> /Users/jason/.rbenv/versions/2.6.5/lib/ruby/2.6.0/x86_64-darwin19/etc.bundle: warning: already initialized constant Etc::SC_TRACE_NAME_MAX
> /Users/jason/.rbenv/versions/2.6.5/lib/ruby/2.6.0/x86_64-darwin19/etc.bundle: warning: already initialized constant Etc::SC_TRACE_SYS_MAX
> /Users/jason/.rbenv/versions/2.6.5/lib/ruby/2.6.0/x86_64-darwin19/etc.bundle: warning: already initialized constant Etc::SC_TRACE_USER_EVENT_MAX
> /Users/jason/.rbenv/versions/2.6.5/lib/ruby/2.6.0/x86_64-darwin19/etc.bundle: warning: already initialized constant Etc::SC_TYPED_MEMORY_OBJECTS
> /Users/jason/.rbenv/versions/2.6.5/lib/ruby/2.6.0/x86_64-darwin19/etc.bundle: warning: already initialized constant Etc::SC_VERSION
> /Users/jason/.rbenv/versions/2.6.5/lib/ruby/2.6.0/x86_64-darwin19/etc.bundle: warning: already initialized constant Etc::SC_V6_ILP32_OFF32
> /Users/jason/.rbenv/versions/2.6.5/lib/ruby/2.6.0/x86_64-darwin19/etc.bundle: warning: already initialized constant Etc::SC_V6_ILP32_OFFBIG
> /Users/jason/.rbenv/versions/2.6.5/lib/ruby/2.6.0/x86_64-darwin19/etc.bundle: warning: already initialized constant Etc::SC_V6_LP64_OFF64
> /Users/jason/.rbenv/versions/2.6.5/lib/ruby/2.6.0/x86_64-darwin19/etc.bundle: warning: already initialized constant Etc::SC_V6_LPBIG_OFFBIG
> /Users/jason/.rbenv/versions/2.6.5/lib/ruby/2.6.0/x86_64-darwin19/etc.bundle: warning: already initialized constant Etc::SC_2_C_BIND
> /Users/jason/.rbenv/versions/2.6.5/lib/ruby/2.6.0/x86_64-darwin19/etc.bundle: warning: already initialized constant Etc::SC_2_C_DEV
> /Users/jason/.rbenv/versions/2.6.5/lib/ruby/2.6.0/x86_64-darwin19/etc.bundle: warning: already initialized constant Etc::SC_2_CHAR_TERM
> /Users/jason/.rbenv/versions/2.6.5/lib/ruby/2.6.0/x86_64-darwin19/etc.bundle: warning: already initialized constant Etc::SC_2_FORT_DEV
> /Users/jason/.rbenv/versions/2.6.5/lib/ruby/2.6.0/x86_64-darwin19/etc.bundle: warning: already initialized constant Etc::SC_2_FORT_RUN
> /Users/jason/.rbenv/versions/2.6.5/lib/ruby/2.6.0/x86_64-darwin19/etc.bundle: warning: already initialized constant Etc::SC_2_LOCALEDEF
> /Users/jason/.rbenv/versions/2.6.5/lib/ruby/2.6.0/x86_64-darwin19/etc.bundle: warning: already initialized constant Etc::SC_2_PBS
> /Users/jason/.rbenv/versions/2.6.5/lib/ruby/2.6.0/x86_64-darwin19/etc.bundle: warning: already initialized constant Etc::SC_2_PBS_ACCOUNTING
> /Users/jason/.rbenv/versions/2.6.5/lib/ruby/2.6.0/x86_64-darwin19/etc.bundle: warning: already initialized constant Etc::SC_2_PBS_CHECKPOINT
> /Users/jason/.rbenv/versions/2.6.5/lib/ruby/2.6.0/x86_64-darwin19/etc.bundle: warning: already initialized constant Etc::SC_2_PBS_LOCATE
> /Users/jason/.rbenv/versions/2.6.5/lib/ruby/2.6.0/x86_64-darwin19/etc.bundle: warning: already initialized constant Etc::SC_2_PBS_MESSAGE
> /Users/jason/.rbenv/versions/2.6.5/lib/ruby/2.6.0/x86_64-darwin19/etc.bundle: warning: already initialized constant Etc::SC_2_PBS_TRACK
> /Users/jason/.rbenv/versions/2.6.5/lib/ruby/2.6.0/x86_64-darwin19/etc.bundle: warning: already initialized constant Etc::SC_2_SW_DEV
> /Users/jason/.rbenv/versions/2.6.5/lib/ruby/2.6.0/x86_64-darwin19/etc.bundle: warning: already initialized constant Etc::SC_2_UPE
> /Users/jason/.rbenv/versions/2.6.5/lib/ruby/2.6.0/x86_64-darwin19/etc.bundle: warning: already initialized constant Etc::SC_2_VERSION
> /Users/jason/.rbenv/versions/2.6.5/lib/ruby/2.6.0/x86_64-darwin19/etc.bundle: warning: already initialized constant Etc::SC_PAGE_SIZE
> /Users/jason/.rbenv/versions/2.6.5/lib/ruby/2.6.0/x86_64-darwin19/etc.bundle: warning: already initialized constant Etc::SC_PAGESIZE
> /Users/jason/.rbenv/versions/2.6.5/lib/ruby/2.6.0/x86_64-darwin19/etc.bundle: warning: already initialized constant Etc::SC_THREAD_DESTRUCTOR_ITERATIONS
> /Users/jason/.rbenv/versions/2.6.5/lib/ruby/2.6.0/x86_64-darwin19/etc.bundle: warning: already initialized constant Etc::SC_THREAD_KEYS_MAX
> /Users/jason/.rbenv/versions/2.6.5/lib/ruby/2.6.0/x86_64-darwin19/etc.bundle: warning: already initialized constant Etc::SC_THREAD_STACK_MIN
> /Users/jason/.rbenv/versions/2.6.5/lib/ruby/2.6.0/x86_64-darwin19/etc.bundle: warning: already initialized constant Etc::SC_THREAD_THREADS_MAX
> /Users/jason/.rbenv/versions/2.6.5/lib/ruby/2.6.0/x86_64-darwin19/etc.bundle: warning: already initialized constant Etc::SC_RE_DUP_MAX
> /Users/jason/.rbenv/versions/2.6.5/lib/ruby/2.6.0/x86_64-darwin19/etc.bundle: warning: already initialized constant Etc::SC_RTSIG_MAX
> /Users/jason/.rbenv/versions/2.6.5/lib/ruby/2.6.0/x86_64-darwin19/etc.bundle: warning: already initialized constant Etc::SC_SEM_NSEMS_MAX
> /Users/jason/.rbenv/versions/2.6.5/lib/ruby/2.6.0/x86_64-darwin19/etc.bundle: warning: already initialized constant Etc::SC_SEM_VALUE_MAX
> /Users/jason/.rbenv/versions/2.6.5/lib/ruby/2.6.0/x86_64-darwin19/etc.bundle: warning: already initialized constant Etc::SC_SIGQUEUE_MAX
> /Users/jason/.rbenv/versions/2.6.5/lib/ruby/2.6.0/x86_64-darwin19/etc.bundle: warning: already initialized constant Etc::SC_STREAM_MAX
> /Users/jason/.rbenv/versions/2.6.5/lib/ruby/2.6.0/x86_64-darwin19/etc.bundle: warning: already initialized constant Etc::SC_SYMLOOP_MAX
> /Users/jason/.rbenv/versions/2.6.5/lib/ruby/2.6.0/x86_64-darwin19/etc.bundle: warning: already initialized constant Etc::SC_TIMER_MAX
> /Users/jason/.rbenv/versions/2.6.5/lib/ruby/2.6.0/x86_64-darwin19/etc.bundle: warning: already initialized constant Etc::SC_TTY_NAME_MAX
> /Users/jason/.rbenv/versions/2.6.5/lib/ruby/2.6.0/x86_64-darwin19/etc.bundle: warning: already initialized constant Etc::SC_TZNAME_MAX
> /Users/jason/.rbenv/versions/2.6.5/lib/ruby/2.6.0/x86_64-darwin19/etc.bundle: warning: already initialized constant Etc::SC_XOPEN_CRYPT
> /Users/jason/.rbenv/versions/2.6.5/lib/ruby/2.6.0/x86_64-darwin19/etc.bundle: warning: already initialized constant Etc::SC_XOPEN_ENH_I18N
> /Users/jason/.rbenv/versions/2.6.5/lib/ruby/2.6.0/x86_64-darwin19/etc.bundle: warning: already initialized constant Etc::SC_XOPEN_REALTIME
> /Users/jason/.rbenv/versions/2.6.5/lib/ruby/2.6.0/x86_64-darwin19/etc.bundle: warning: already initialized constant Etc::SC_XOPEN_REALTIME_THREADS
> /Users/jason/.rbenv/versions/2.6.5/lib/ruby/2.6.0/x86_64-darwin19/etc.bundle: warning: already initialized constant Etc::SC_XOPEN_SHM
> /Users/jason/.rbenv/versions/2.6.5/lib/ruby/2.6.0/x86_64-darwin19/etc.bundle: warning: already initialized constant Etc::SC_XOPEN_STREAMS
> /Users/jason/.rbenv/versions/2.6.5/lib/ruby/2.6.0/x86_64-darwin19/etc.bundle: warning: already initialized constant Etc::SC_XOPEN_UNIX
> /Users/jason/.rbenv/versions/2.6.5/lib/ruby/2.6.0/x86_64-darwin19/etc.bundle: warning: already initialized constant Etc::SC_XOPEN_VERSION
> /Users/jason/.rbenv/versions/2.6.5/lib/ruby/2.6.0/x86_64-darwin19/etc.bundle: warning: already initialized constant Etc::SC_PHYS_PAGES
> /Users/jason/.rbenv/versions/2.6.5/lib/ruby/2.6.0/x86_64-darwin19/etc.bundle: warning: already initialized constant Etc::SC_NPROCESSORS_CONF
> /Users/jason/.rbenv/versions/2.6.5/lib/ruby/2.6.0/x86_64-darwin19/etc.bundle: warning: already initialized constant Etc::SC_NPROCESSORS_ONLN
> /Users/jason/.rbenv/versions/2.6.5/lib/ruby/2.6.0/x86_64-darwin19/etc.bundle: warning: already initialized constant Etc::CS_PATH
> /Users/jason/.rbenv/versions/2.6.5/lib/ruby/2.6.0/x86_64-darwin19/etc.bundle: warning: already initialized constant Etc::CS_POSIX_V6_ILP32_OFF32_CFLAGS
> /Users/jason/.rbenv/versions/2.6.5/lib/ruby/2.6.0/x86_64-darwin19/etc.bundle: warning: already initialized constant Etc::CS_POSIX_V6_ILP32_OFF32_LDFLAGS
> /Users/jason/.rbenv/versions/2.6.5/lib/ruby/2.6.0/x86_64-darwin19/etc.bundle: warning: already initialized constant Etc::CS_POSIX_V6_ILP32_OFF32_LIBS
> /Users/jason/.rbenv/versions/2.6.5/lib/ruby/2.6.0/x86_64-darwin19/etc.bundle: warning: already initialized constant Etc::CS_POSIX_V6_ILP32_OFFBIG_CFLAGS
> /Users/jason/.rbenv/versions/2.6.5/lib/ruby/2.6.0/x86_64-darwin19/etc.bundle: warning: already initialized constant Etc::CS_POSIX_V6_ILP32_OFFBIG_LDFLAGS
> /Users/jason/.rbenv/versions/2.6.5/lib/ruby/2.6.0/x86_64-darwin19/etc.bundle: warning: already initialized constant Etc::CS_POSIX_V6_ILP32_OFFBIG_LIBS
> /Users/jason/.rbenv/versions/2.6.5/lib/ruby/2.6.0/x86_64-darwin19/etc.bundle: warning: already initialized constant Etc::CS_POSIX_V6_LP64_OFF64_CFLAGS
> /Users/jason/.rbenv/versions/2.6.5/lib/ruby/2.6.0/x86_64-darwin19/etc.bundle: warning: already initialized constant Etc::CS_POSIX_V6_LP64_OFF64_LDFLAGS
> /Users/jason/.rbenv/versions/2.6.5/lib/ruby/2.6.0/x86_64-darwin19/etc.bundle: warning: already initialized constant Etc::CS_POSIX_V6_LP64_OFF64_LIBS
> /Users/jason/.rbenv/versions/2.6.5/lib/ruby/2.6.0/x86_64-darwin19/etc.bundle: warning: already initialized constant Etc::CS_POSIX_V6_LPBIG_OFFBIG_CFLAGS
> /Users/jason/.rbenv/versions/2.6.5/lib/ruby/2.6.0/x86_64-darwin19/etc.bundle: warning: already initialized constant Etc::CS_POSIX_V6_LPBIG_OFFBIG_LDFLAGS
> /Users/jason/.rbenv/versions/2.6.5/lib/ruby/2.6.0/x86_64-darwin19/etc.bundle: warning: already initialized constant Etc::CS_POSIX_V6_LPBIG_OFFBIG_LIBS
> /Users/jason/.rbenv/versions/2.6.5/lib/ruby/2.6.0/x86_64-darwin19/etc.bundle: warning: already initialized constant Etc::CS_POSIX_V6_WIDTH_RESTRICTED_ENVS
> /Users/jason/.rbenv/versions/2.6.5/lib/ruby/2.6.0/x86_64-darwin19/etc.bundle: warning: already initialized constant Etc::PC_FILESIZEBITS
> /Users/jason/.rbenv/versions/2.6.5/lib/ruby/2.6.0/x86_64-darwin19/etc.bundle: warning: already initialized constant Etc::PC_LINK_MAX
> /Users/jason/.rbenv/versions/2.6.5/lib/ruby/2.6.0/x86_64-darwin19/etc.bundle: warning: already initialized constant Etc::PC_MAX_CANON
> /Users/jason/.rbenv/versions/2.6.5/lib/ruby/2.6.0/x86_64-darwin19/etc.bundle: warning: already initialized constant Etc::PC_MAX_INPUT
> /Users/jason/.rbenv/versions/2.6.5/lib/ruby/2.6.0/x86_64-darwin19/etc.bundle: warning: already initialized constant Etc::PC_NAME_MAX
> /Users/jason/.rbenv/versions/2.6.5/lib/ruby/2.6.0/x86_64-darwin19/etc.bundle: warning: already initialized constant Etc::PC_PATH_MAX
> /Users/jason/.rbenv/versions/2.6.5/lib/ruby/2.6.0/x86_64-darwin19/etc.bundle: warning: already initialized constant Etc::PC_PIPE_BUF
> /Users/jason/.rbenv/versions/2.6.5/lib/ruby/2.6.0/x86_64-darwin19/etc.bundle: warning: already initialized constant Etc::PC_2_SYMLINKS
> /Users/jason/.rbenv/versions/2.6.5/lib/ruby/2.6.0/x86_64-darwin19/etc.bundle: warning: already initialized constant Etc::PC_ALLOC_SIZE_MIN
> /Users/jason/.rbenv/versions/2.6.5/lib/ruby/2.6.0/x86_64-darwin19/etc.bundle: warning: already initialized constant Etc::PC_REC_INCR_XFER_SIZE
> /Users/jason/.rbenv/versions/2.6.5/lib/ruby/2.6.0/x86_64-darwin19/etc.bundle: warning: already initialized constant Etc::PC_REC_MAX_XFER_SIZE
> /Users/jason/.rbenv/versions/2.6.5/lib/ruby/2.6.0/x86_64-darwin19/etc.bundle: warning: already initialized constant Etc::PC_REC_MIN_XFER_SIZE
> /Users/jason/.rbenv/versions/2.6.5/lib/ruby/2.6.0/x86_64-darwin19/etc.bundle: warning: already initialized constant Etc::PC_REC_XFER_ALIGN
> /Users/jason/.rbenv/versions/2.6.5/lib/ruby/2.6.0/x86_64-darwin19/etc.bundle: warning: already initialized constant Etc::PC_SYMLINK_MAX
> /Users/jason/.rbenv/versions/2.6.5/lib/ruby/2.6.0/x86_64-darwin19/etc.bundle: warning: already initialized constant Etc::PC_CHOWN_RESTRICTED
> /Users/jason/.rbenv/versions/2.6.5/lib/ruby/2.6.0/x86_64-darwin19/etc.bundle: warning: already initialized constant Etc::PC_NO_TRUNC
> /Users/jason/.rbenv/versions/2.6.5/lib/ruby/2.6.0/x86_64-darwin19/etc.bundle: warning: already initialized constant Etc::PC_VDISABLE
> /Users/jason/.rbenv/versions/2.6.5/lib/ruby/2.6.0/x86_64-darwin19/etc.bundle: warning: already initialized constant Etc::PC_ASYNC_IO
> /Users/jason/.rbenv/versions/2.6.5/lib/ruby/2.6.0/x86_64-darwin19/etc.bundle: warning: already initialized constant Etc::PC_PRIO_IO
> /Users/jason/.rbenv/versions/2.6.5/lib/ruby/2.6.0/x86_64-darwin19/etc.bundle: warning: already initialized constant Etc::PC_SYNC_IO
> /Users/jason/.rbenv/versions/2.6.5/lib/ruby/2.6.0/x86_64-darwin19/etc.bundle: warning: already initialized constant Struct::Passwd
> /Users/jason/.rbenv/versions/2.6.5/lib/ruby/2.6.0/x86_64-darwin19/etc.bundle: warning: already initialized constant Struct::Group
</details>

**Comment by rafaelfranca** [comment]
Thank you for the issue. This is somehow related to you Ruby installation.
