### ISSUE TITLE
ActiveStorage has_many_attached leaves orphaned files and `ActiveStorage::Blob` records when parent is destroyed.

### ISSUE THREAD

**Issue by dvjones89** [rails/rails#38021]
## Description of issue:
I have recently started work on a new Rails 6.0.2 project. One of my models, `vlog.rb`, can have multiple associated files, hence the `has_many_attached :files` declaration defined in `app/models/vlog.rb`.

Following the [ActiveStorage instructions](https://edgeguides.rubyonrails.org/active_storage_overview.html) I'm able to successfully upload multiple files through the web browser in the development environment, which writes the files to `storage/` as expected. Unfortunately, if I then destroy a Vlog record through the web UI, I observe that only **one** of the uploaded files is removed from the `storage/` directory, with the additional file(s) remaining on the local file system. I've also observed that whilst all `ActiveStorage::Attachment` records are deleted from the database, some of the `ActiveStorage::Blob` records fail to be removed, which I assume shares the same root cause.

## Steps to reproduce:
1) Clone [this repository](https://github.com/dvjones89/activestorage_troubleshooting) to your computer. This is a super-simple Rails 6.0.2 app with the minimal number of changes required to reproduce the issue.
1) Run `bundle install` to fetch the dependencies of a stock Rails 6.0.2 app.
1) Run `rails db:migrate` to setup your local database.
1) Run the rails server locally, `rails server`
1) Visit http://localhost:3000/vlogs/new, press `Choose files` and select **two** files from your computer for upload to the Rails app.
1) In your file browser, open the `storage`  directory and observe that **two** directories have been created, each of which contains a subdirectory and then a copy of the file you uploaded.
1) Back in your web browser, visit http://localhost:3000/vlogs, locate the Vlog you just created and press `Destroy`
1) Revisit the `storage`  directory in your file browser and count the number of files that remain on your file system.

## Expected behaviour
1) Both (**2**) of the uploaded files has been deleted from `storage` since their parent (Vlog resource) has been destroyed. Zero files remain.

## Actual behaviour
1) Only **1** of the uploaded files has been deleted from the local `storage` directory, essentially leaving the secondary file orphaned (since the parent Vlog resource has been destroyed). One file remains.

### System configuration
**Rails version**: 6.0.2
**Ruby version**: 2.6.5

### Additional Notes:
After deleting a Vlog resource I've observed that ActiveStorage::Attachment.count reliably returns `0`, as you'd expected. If you run ActiveStorage::Blob.count, however, you'll see that this returns `1`, which I suspect relates to the file that remains within the storage directory.

**Comment by dvjones89** [comment]
I suspect this issue is a regression within Rails 6. Following the above steps using Rails 5.2.4 behaves as expected (no orphaned files of `ActiveStorage::Blob` records.

**Comment by dvjones89** [comment]
Thanks for taking the time to triage this, @rafaelfranca. Please let me know if there's anything further I can do to isolate / troubleshoot the issue, I'm keen to help.

**Comment by dvjones89** [comment]
I've recently spotted some `SQLite3::BusyException` errors in my development console. The errors were being raised whilst running `ActiveStorage::PurgeJob` jobs, making me wonder if I'd found the cause of the orphaned files being left in ActiveStorage. To test my theory I've switched from SQLite3 to PostgreSQL and, sure enough, this issue can no longer be reproduced locally. As far as I know I have a default installation of SQLite3, though it appears that attempts to delete multiple associated files in Rails 6 can give rise to `SQLite3::BusyException` errors. Since SQLite3 is the default development database in Rails 6, it feels like this warrants further investigation.

I hope this helps and please let me know if I can do more to help!

**Comment by Gooner91** [comment]
I am facing the same issue with `Rails 5.2.0` and `Postgres` in my local environment. If a record that has `has_many_attached :files` is given a single attachment, deleting the record would destroy the associated attachment. However, in case of more than one attachment, I am facing the same behavior when trying to delete the parent record.

**Comment by Gooner91** [comment]
I am facing the same issue with `Rails 5.2.0` and `Postgres` in my local environment. If a record that has has_many_attached :files is given a single attachment, deleting the record would destroy the associated attachment. However, in case of more than one attachment, I am facing the same behavior when trying to delete the parent record.

**Update**
I have my rails api running on `localhost:3001` and a reactjs app running on `localhost:3000`. I have noticed this a couple of times now that as I restart my node server for react app or kill it, deleting record purges all the attachments associated with it but in some cases when both the servers are running, the purge job seems to hang which i eventually have to kill leaving orphaned records.

**Comment by intrip** [comment]
@dvjones89 this is definitely a SQlite issue related to the fact that we are running multiple write transaction [which is not supported by SQLite](https://www.sqlite.org/lang_transaction.html#:~:text=SQLite%20supports%20multiple%20simultaneous%20read,allows%20both%20reading%20and%20writing.), I don't think we can do much to deal with it unless serialising all the operations.

This is a general problem of SQLite though not an ActiveStorage issue from my POV.

**Comment by dvjones89** [comment]
OK, thanks for sharing your thoughts, @intrip . Hopefully having a record of this behaviour will help other people who find their way to this issue report from Google 😄  Appreciate your time and all you do for Rails 🙏

**Comment by zzak** [comment]
@intrip Do you think it's worth adding something to the documentation?

It sounds like this is a non-rails issue so this can be closed 🙏

**Comment by intrip** [comment]
@zzak We already [discourage the usage of SQLite in production](https://github.com/rails/rails/pull/42191) and honestly I think that's enough, but if you have any advice of where we could add such info I'm more then open of adding it 🙂.

Agree on closing this issue.
