### ISSUE TITLE
`rails new` silently fails without git

### ISSUE THREAD

**Issue by znz** [rails/rails#38035]
### Steps to reproduce

`docker run --rm -it ruby:2.6.5 /bin/bash -c 'apt purge -y git && gem i rails && rails new foo; ls foo'`

### Expected behavior

Show `git: command not found` error or fallback to `--skip-git`.

### Actual behavior

```
%  docker run --rm -it ruby:2.6.5 /bin/bash -c 'apt purge -y git && gem i rails && rails new foo; ls foo'
(snip)
Successfully installed rails-6.0.2.1
40 gems installed
      create
      create  README.md
      create  Rakefile
      create  .ruby-version
      create  config.ru
      create  .gitignore
      create  Gemfile
         run  git init from "."
Gemfile  README.md  Rakefile  config.ru
```

### System configuration
**Rails version**:6.0.2.1

**Ruby version**:2.6.5

**Comment by Jayklutch** [comment]
This has had my production pc dead for a week. Why the hell is git making this all fall over?
Adding --skip-git now allows rails to build directories where is was unable to before.

**Comment by martijn** [comment]
I'd love to tackle this, but I can't for the life of me figure out where the `run` method at https://github.com/rails/rails/blob/master/railties/lib/rails/generators/rails/app/app_generator.rb#L71 is defined.

**Comment by rafaelfranca** [comment]
Fixed on master and 6-0-stable
