### ISSUE TITLE
Cannot set property 'isOutOfGrid' of undefined

### ISSUE THREAD

**Issue by LaxmanTelang** [rails/rails#38032]
Drag and drop the widget and resize the widget and a new widget is drag to the page  -->

got the errir
![Issue](https://user-images.githubusercontent.com/34305830/71158326-c0379500-2269-11ea-899a-87791ff075c6.PNG)

**Comment by rafaelfranca** [comment]
You need to give us more information on how to reproduce this issue, otherwise there is nothing we can do. Please read CONTRIBUTING.md file for more information about creating bug reports. Thanks!
