### ISSUE TITLE
Add support for xid(guid) in config.log_tags

### ISSUE THREAD

**Issue by valarpirai** [rails/rails#38031]
### Expected behavior
Rails configuration has support for uuid in log_tags. In the same way, I want to add support for xid in log_tags. Xid is a Globally Unique ID Generator.

Xid Spec:
- Size 
   - 12 bytes as binary
   - 20 bytes as string

- 4-byte value representing the seconds since the Unix epoch,
- 3-byte machine identifier,
- 2-byte process id, and
- 3-byte counter, starting with a random value.

[Github repo](https://github.com/valarpirai/ruby_xid)
[Ruby Gem](https://rubygems.org/gems/ruby_xid)

**Comment by rafaelfranca** [comment]
Thank you for the issue. It should be easy to you to write a gem that add xid support to log tags. You only need to create a subclass of the `ActionDispatch::RequestId` middleware that generates xid instead of uuid. We have no interest on adding this by default in the framework.
