### ISSUE TITLE
Unexpected frozen string literal produced by Array helpers.

### ISSUE THREAD

**Issue by AndrewSouthpaw** [rails/rails#38044]
I'm new to contributing to the Rails source, so forgive me if this conversation is super old hat...

Right now

```ruby
['foo', 'bar'].to_sentence.frozen? # => true
```

I would've expected it to not produce a frozen string, or to at least clarify this in the docs. I wasn't seeing any obvious places where it's mentioned. Only after digging in the source for a while did I notice the `frozen_string_literals: true` at the top of the Array `conversions.rb` file, and then it all made sense.

It seems a bit unexpected to be forcing folks into using frozen string literals without making it obvious.

BUT maybe it *is* obvious to the whole world and I'm just behind the times, in which case please forgive my ignorance. 😅 

### System configuration
**Rails version**: 5.2.3

**Ruby version**: 2.5.5

**Comment by eugeneius** [comment]
Frozen string literal magic comments were added to Active Support in https://github.com/rails/rails/pull/29728; this seems like an unintended consequence of that change. This behaviour is, in fact, a brand new hat! 🎩 

If you're interested in submitting a PR, https://github.com/rails/rails/pull/36109 is essentially the same fix for another method.

**Comment by nicolasdular** [comment]
@AndrewSouthpaw I hope it's okay, but I took the opportunity and created a PR https://github.com/rails/rails/pull/38117. /cc @eugeneius

**Comment by AndrewSouthpaw** [comment]
Darn, I was hoping to turn that into my first PR for rails. Better luck next time. 😅

Thanks @eugenebolshakov for offering thorough advice and @nicholassm for resolving the issue!
