### ISSUE TITLE
Getting Error:  Cannot set property '_grid' of undefined

### ISSUE THREAD

**Issue by LaxmanTelang** [rails/rails#38047]
Below is my code for gridstck:
  var options = {
            animate: true,
            float: false,
            verticalMargin: 0,
            removable: '.trash',
            removeTimeout: 100,
            alwaysShowResizeHandle: /Android|webOS|iPhone|iPad|iPod|BlackBerry|IEMobile|Opera Mini/i.test(navigator.userAgent),
            acceptWidgets: '.chart-thumbnail',
            resizable: {
                handles: 'e, se, s, sw, w'
            },
            disableResize: false
        };

        $('#DashboardGridStack').gridstack(_.defaults({
            float: true
        }, options));
        var gridStackInstance = $('#DashboardGridStack').data('gridstack');

Drag and Drop function:
        $('#DashboardGridStack').on('dropped', function (event, previousWidget, newWidget) {
            if ($("#vizSearchInput").css("display") == "block")
                $("#vizSearchInput").hide();

### Expected behavior
I want to drag and drop the widget but when i change the postion of draged widget i am not able to drag other widget Iam getting this error.

Iam using Jquery 1.11.4 min.js
And gridstck v0.4
![GridStack](https://user-images.githubusercontent.com/34305830/71238801-06086200-232b-11ea-962e-952b69a008ad.PNG)
![ezgif-3-6b7b013a1c1d](https://user-images.githubusercontent.com/34305830/71239667-1cafb880-232d-11ea-9b40-082446ad83c7.gif)

**Comment by eileencodes** [comment]
Hey @LaxmanTelang thanks for the report. I think you have the wrong open source project and this doesn't sound like a Rails bug. We don't include gridstack. If I'm mistaken please provide a sample Rails application that reproduces the error you're seeing.
