### ISSUE TITLE
ActiveRecord::StatementInvalid: SQLite3::SQLException: incomplete input

### ISSUE THREAD

**Issue by foonlyboy** [rails/rails#38066]
Hi everyone,
I did setup a fresh rails project (--api)
Rails 5.2.4

wrote some routes,
wrote some assert_routing tests,
everything was fine.

generated a model "releases"
all tests immediately did fail with:
ActiveRecord::StatementInvalid: SQLite3::SQLException: incomplete input: INSERT INTO "releases"

The culprit was fixtures/releases.yml
When I removed that file, that error messages vanished.

---

I'd like to suggest to improve the error messages of running "rails test"
to make it more easy to diagnose the root causes of the problems.

My error message must have come from deep down of the sqlite adapter as an exception.
But it was triggered from some rails code working with fixtures.

I'd suggest to catch exceptions and wrap them,
so to annotate where they where invoked from.

---

the breaking fixture was:
one: {}
two: {}

I never needed fixtures, yet.
I don't even know what they are good for, yet.

So why was that code generated in the first place?
to only break my workflow and all my tests?

Again, that bad thing for me was the error message:
ActiveRecord::StatementInvalid: SQLite3::SQLException: incomplete input

I'm sure we can improve on that.
Let's make it a test case first,
so that we can reliabably trigger that error message again.

I have to go on,
my workaround was to delete the fixtures/<model> file

~eike 

### Steps to reproduce
generate a fresh rails project
cz
generate a model
(obviously some of my intermediate steps which I can not yet reproduce made this fails)
x
### System configuration
**Rails version**:

**Ruby version**:

**Comment by avit** [comment]
Fixtures are used for test data. They are described in the Rails guides:

https://guides.rubyonrails.org/testing.html#the-low-down-on-fixtures

If you aren't using fixtures, you can generate models without fixture files using `--skip-fixtures`

**Comment by foonlyboy** [comment]
Hi Andrew,

Thanks for your reply.
Let's get in contact.

~eike

**Comment by marceloperini** [comment]
@foonlyboy I tried to reproduce this problem using rails 6.0.2.1 and found no errors. Can you provide more informations?

**Comment by shekhar-amura** [comment]
@foonlyboy I tried to reproduce is an issue using rails 5.4.2 and ruby 2.4 but I did not get any error. Please provide some more information to reproduce this issue.

**Comment by shekhar-patil** [comment]
@foonlyboy I tried to reproduce is an issue using rails 5.4.2 and ruby 2.4 but I did not get any error. Please provide some more information to reproduce this issue.

**Comment by peterb** [comment]
I have also attempted to reproduce this with the version, flag, and fixture mentioned (5.2.4, --api), generating a `releases` scaffold and corresponding empty fixtures, and then adding a column to `releases`, but the test suite ran normally.

I'm guessing it's a test in his test suite (not included in the report) that is causing the bug.

**Comment by peterb** [comment]
@rafaelfranca Would it make sense to close this issue? It seems as though none of us can reproduce it and it could be re-opened in the future should more information become available.

**Comment by lfv89** [comment]
Everything working here.

```
❯ rbenv local
2.6.0

❯ rails --version
Rails 5.2.4.2
```

```
❯ bin/rails g model release
❯ bin/rake db:setup                                                                                                                                                                    
❯ bin/rake db:migrate                                                                                                                                                                  ❯ bin/rake test                                                                                                                                                                        
Running via Spring preloader in process 7194
Run options: --seed 61176

# Running:



Finished in 0.001070s, 0.0000 runs/s, 0.0000 assertions/s.
1 runs, 1 assertions, 0 failures, 0 errors, 0 skips
```

**Comment by foonlyboy** [comment]
close it
