### ISSUE TITLE
cache_key for AR relations is broken for usage in ConditionalGet API

### ISSUE THREAD

**Issue by le0pard** [rails/rails#38078]
### Steps to reproduce

Lets get some relation and check `cache_key` for it:

```ruby
2.6.3 :001 > ActiveRecord::Base.collection_cache_versioning
 => true
2.6.3 :002 > user = User.first
  User Load (1.0ms)  SELECT "users".* FROM "users" ORDER BY "users"."id" ASC LIMIT $1  [["LIMIT", 1]]
 => #<User id: >
2.6.3 :003 > user.cors_domains.ordered.count
   (1.5ms)  SELECT COUNT(*) FROM "cors_domains" WHERE "cors_domains"."user_id" = $1  [["user_id", 1]]
 => 3
2.6.3 :004 > user.cors_domains.ordered.maximum(:updated_at)
   (0.7ms)  SELECT MAX("cors_domains"."updated_at") FROM "cors_domains" WHERE "cors_domains"."user_id" = $1  [["user_id", 1]]
 => 2019-12-23 11:58:23 UTC
2.6.3 :005 > user.cors_domains.ordered.cache_key
   (0.8ms)  SELECT COUNT(*) AS "size", MAX("cors_domains"."updated_at") AS timestamp FROM "cors_domains" WHERE "cors_domains"."user_id" = $1  [["user_id", 1]]
 => "cors_domains/query-199f662dcd4578830fd25ee2ac98eef5"
```

Looks good. Now lets remove one record from `cors_domains` table and check `cache_key` again:

```ruby
2.6.3 :007 > user.cors_domains.ordered.count
   (0.7ms)  SELECT COUNT(*) FROM "cors_domains" WHERE "cors_domains"."user_id" = $1  [["user_id", 1]]
 => 2
2.6.3 :008 > user.cors_domains.ordered.maximum(:updated_at)
   (0.7ms)  SELECT MAX("cors_domains"."updated_at") FROM "cors_domains" WHERE "cors_domains"."user_id" = $1  [["user_id", 1]]
 => 2019-12-23 11:58:23 UTC
2.6.3 :009 > user.cors_domains.ordered.cache_key
   (0.7ms)  SELECT COUNT(*) AS "size", MAX("cors_domains"."updated_at") AS timestamp FROM "cors_domains" WHERE "cors_domains"."user_id" = $1  [["user_id", 1]]
 => "cors_domains/query-199f662dcd4578830fd25ee2ac98eef5"
```

As we can see, in results we have the same value **"cors_domains/query-199f662dcd4578830fd25ee2ac98eef5"**, which is incorrect and influence on https://api.rubyonrails.org/classes/ActionController/ConditionalGet.html methods. 

Like this example will not work correctly:

```ruby
def index
  @articles = Article.all
  fresh_when(@articles)
end
```

Because `ActiveSupport::Cache.expand_cache_key(Article.all)` will be the same all the time. You can rewrite in this way, so it will work correctly (but it is not effective):

```ruby
def index
  @articles = Article.all
  fresh_when(etag: @articles.to_a, last_modified: @articles.maximum(:updated_at))
end
```

### Expected behavior

https://github.com/rails/rails/blob/v6.0.2.1/activerecord/lib/active_record/relation.rb#L316 should calculate `cache_key` based on `COUNT(*) AS "size", MAX("cors_domains"."updated_at")`, but it ignore this information.

### Actual behavior

https://github.com/rails/rails/blob/v6.0.2.1/activerecord/lib/active_record/relation.rb#L316 instead it just calculating hexdigest based on query text:

```
    def compute_cache_key(timestamp_column = :updated_at) # :nodoc:
      query_signature = ActiveSupport::Digest.hexdigest(to_sql)
      key = "#{klass.model_name.cache_key}/query-#{query_signature}"

      if cache_version(timestamp_column)
        key
      else
        "#{key}-#{compute_cache_version(timestamp_column)}"
      end
    end
```

Also `cache_version(timestamp_column)` not used for key, only in condition check. This lead, that:

```ruby
[4] pry(#<CorsDomain::ActiveRecord_AssociationRelation>)> to_sql
=> "SELECT \"cors_domains\".* FROM \"cors_domains\" WHERE \"cors_domains\".\"user_id\" = 1 ORDER BY \"cors_domains\".\"id\" ASC"
[5] pry(#<CorsDomain::ActiveRecord_AssociationRelation>)> ActiveSupport::Digest.hexdigest(to_sql)
=> "199f662dcd4578830fd25ee2ac98eef5"
[6] pry(#<CorsDomain::ActiveRecord_AssociationRelation>)> ActiveSupport::Digest.hexdigest(to_sql)
=> "199f662dcd4578830fd25ee2ac98eef5"
```

The same `cache_key`, even if relation have different records.

### System configuration
**Rails version**: 6.0.1
**Ruby version**: 2.6.3p62

**Comment by le0pard** [comment]
Possible solution:

```
--- a/activerecord/lib/active_record/relation.rb
+++ b/activerecord/lib/active_record/relation.rb
@@ -317,8 +317,8 @@ def compute_cache_key(timestamp_column = :updated_at) # :nodoc:
       query_signature = ActiveSupport::Digest.hexdigest(to_sql)
       key = "#{klass.model_name.cache_key}/query-#{query_signature}"

-      if cache_version(timestamp_column)
-        key
+      if (key_cache_version = cache_version(timestamp_column))
+        "#{key}-#{key_cache_version}"
       else
         "#{key}-#{compute_cache_version(timestamp_column)}"
       end
```

But I don't know, what idea was behind caching based on `sql query` only.

**Comment by alipman88** [comment]
I think the behavior you're describing is the intended behavior, not a bug.

If `ActiveRecord::Base.collection_cache_versioning` is set to true, the volatile info (max updated_at timestamp & collection size) will not be included in the key returned by `ActiveRecord::Relation#cache_key` - instead, `ActiveRecord::Relation#cache_version` will provide that info:

```ruby
ActiveRecord::Base.collection_cache_versioning = true
# => true

Post.all.cache_key
# => "posts/query-00644b6a00f2ed4b925407d06501c8fb"

Post.all.cache_version
# => "1-20191224145617382316"
```

If `ActiveRecord::Base.collection_cache_versioning` is set to false (the default), `ActiveRecord::Relation#cache_key` will include the volatile information, and `ActiveRecord::Relation#cache_version` will return nil:

```ruby
ActiveRecord::Base.collection_cache_versioning = false
# => false

Post.all.cache_key
# => "posts/query-00644b6a00f2ed4b925407d06501c8fb-1-20191224145617382316"

Post.all.cache_version
# => nil
```

(Refer to https://guides.rubyonrails.org/configuring.html#configuring-active-record, under "config.active_record.collection_cache_versioning")

Please let me know if I'm misunderstanding this issue.

**Comment by le0pard** [comment]
@alipman88 

I am ok with this behaviour, but ConditionalGet ( https://api.rubyonrails.org/classes/ActionController/ConditionalGet.html ) methods use `ActiveSupport::Cache.expand_cache_key`, which resolve to `cache_key` for relations. Example from documentation:

```ruby
def index
  @articles = Article.all
  fresh_when(@articles)
end
```

Relations doesn't have methods `cache_key_with_version`, so it use `cache_key `:

https://github.com/rails/rails/blob/77a416c84f6d34a62ee55af329113152d4e3b5a0/activesupport/lib/active_support/cache.rb#L94-L102

This lead, that "Etag" header never change and static for any number of records or changes in this records. In this case `ActiveRecord::Base.collection_cache_versioning = true` cannot be used with HTTP caching in rails, because it is fully break ConditionalGet API. 

Do you understand the issue?

**Comment by le0pard** [comment]
So we should create `cache_key_with_version` for AR relations or fix `cache_key` method ConditionalGet API @alipman88

**Comment by le0pard** [comment]
Also not clear why https://github.com/rails/rails/blob/v6.0.2.1/activerecord/lib/active_record/relation.rb#L316 calculate `cache_version` and use it for condition

**Comment by le0pard** [comment]
To be clear more about this issue, I created repo: https://github.com/le0pard/conditional_get_and_ar_relations

Here controller: https://github.com/le0pard/conditional_get_and_ar_relations/blob/master/app/controllers/users_controller.rb

And here tests: https://github.com/le0pard/conditional_get_and_ar_relations/blob/master/spec/requests/users_controller_spec.rb

Here here how it failing (`ActiveRecord::Base.collection_cache_versioning` true by default for rails):

```
$ rspec spec/requests/users_controller_spec.rb 
.......F..F

Failures:

  1) UsersController GET #index with HTTP cache after adding a new user and same if-none-match in header #status is expected to eq 200
     Failure/Error: it { is_expected.to eq(200) }

       expected: 200
            got: 304

       (compared using ==)
     # ./spec/requests/users_controller_spec.rb:75:in `block (5 levels) in <top (required)>'

  2) UsersController GET #index with HTTP cache after adding a new user and same if-none-match in header #body #size is expected to be > 0
     Failure/Error: it { is_expected.to be > 0 }

       expected: > 0
            got:   0
     # ./spec/requests/users_controller_spec.rb:89:in `block (6 levels) in <top (required)>'

Finished in 0.12924 seconds (files took 1.58 seconds to load)
11 examples, 2 failures

Failed examples:

rspec ./spec/requests/users_controller_spec.rb:75 # UsersController GET #index with HTTP cache after adding a new user and same if-none-match in header #status is expected to eq 200
rspec ./spec/requests/users_controller_spec.rb:89 # UsersController GET #index with HTTP cache after adding a new user and same if-none-match in header #body #size is expected to be > 0
```

![123](https://user-images.githubusercontent.com/98444/71442061-f020e580-270c-11ea-8027-c2512ca56bcc.png)

This part is not pass by tests:

https://github.com/le0pard/conditional_get_and_ar_relations/blob/master/spec/requests/users_controller_spec.rb#L65-L91

Maybe my logic wrong, just correct me about HTTP cache usage.

**Comment by alipman88** [comment]
Thanks for the clarification and apologies for my earlier misunderstanding. I'd like some time to familiarize myself with ConditionalGet before responding more in depth, but at first glance I think you've identified a bug.

Quickly responding to this point:

> Also not clear why
>
> https://github.com/rails/rails/blob/v6.0.2.1/activerecord/lib/active_record/relation.rb#L320-L321
>
>    calculate cache_version and use it for condition: we still waste resources for sql query about COUNT(*) AS "size", MAX("cors_domains"."updated_at"), but not use it for cache key generation.

I'm noticing the same thing, an unnecessary SQL query is getting triggered - line 320 of `activerecord/lib/active_record/relation.rb` should be changed from `if cache_version(timestamp_column)` to `if collection_cache_versioning`, and the following test could be added to `activerecord/test/cases/collection_cache_key_test.rb`:

```
test "it doesn't trigger any query if collection_cache_versioning is enabled" do
  with_collection_cache_versioning do
    developers = Developer.where(name: "David")
    assert_no_queries { developers.cache_key }
  end
end
```

I'll plan on submitting that as a pull request and credit you as a co-author, unless you'd like to take the lead.

**Comment by le0pard** [comment]
@alipman88 I ok, if you get all credits, because you will write fix (I just point to bug). Just add tests for ConditionalGet API for AR relations, so it will not be break in future :)

**Comment by alipman88** [comment]
Thanks for the example repo.

I've written an executable test case:

```ruby
# frozen_string_literal: true

require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  gem "rails", github: "rails/rails"
  gem "sqlite3"
end

require "action_controller/railtie"
require "active_record"

class TestApp < Rails::Application
  config.root = __dir__
  config.hosts << "example.org"
  secrets.secret_key_base = "secret_key_base"

  config.logger = Logger.new($stdout)
  Rails.logger  = config.logger

  routes.draw do
    get "/" => "test#index"
  end

  config.middleware.use ActionDispatch::Flash
end

class TestController < ActionController::Base
  include Rails.application.routes.url_helpers

  def index
    @posts = Post.all
    fresh_when @posts
    render json: @posts
  end
end

require "minitest/autorun"
require "rack/test"

ActiveRecord::Base.establish_connection(adapter: "sqlite3", database: ":memory:")
ActiveRecord::Base.logger = Logger.new(STDOUT)
ActiveRecord::Base.collection_cache_versioning = true # use unversioned cache keys

ActiveRecord::Schema.define do
  create_table :posts, force: true do |t|
    t.timestamps
  end
end

class Post < ActiveRecord::Base
end

class BugTest < Minitest::Test
  include Rack::Test::Methods

  def test_etag_changes
    Post.create
    response_1 = get("/")
    etag_1 = response_1.headers["ETag"]

    Post.create
    response_2 = get("/")
    etag_2 = response_2.headers["ETag"]

    refute_equal etag_1, etag_2
  end

  private
    def app
      Rails.application
    end
end
```

> So we should create cache_key_with_version for AR relations or fix cache_key method for ConditionalGet API in rails

I think adding a `cache_key_with_version` method to `ActiveRecord::Relation` is the way to go, given that pattern is already used in [activerecord/lib/active_record/integration.rb](https://github.com/rails/rails/blob/master/activerecord/lib/active_record/integration.rb).

> Just add tests for ConditionalGet API for AR relations, so it will not be break in future :)

Will do! I'm still considering how to add something equivalent to the above test to Rails' test suite, but I'll plan on submitting a pull request that patches this (and adds tests to catch future regressions) in the next week or two.

**Comment by le0pard** [comment]
@alipman88 thanks for help. 

Keep me posted and ping me if you need any help.
