### ISSUE TITLE
Rails 6.0.2.1 server fails to start with ruby 2.7.0-rc2

### ISSUE THREAD

**Issue by atstockland** [rails/rails#38074]
I have been running rails 6.0 with ruby 2.7.0-preview1 for a while.   6.0.2.1 also runs fine with ruby 2.7.0-preview1.  However, ruby 2.7.0-preview2, 2.7.0-preview3, 2.7.0-rc1, and 2.7.0-rc2 all fail with the same error; "cannot load such file -- scanf"....which seems to be related to Bootsnap.

### System configuration
**Rails version**: 6.0.2.1

**Ruby version**: 2.7.0-rc2

**Stack trace**:

......... bin/rails s
/Users/adam_ant/.rbenv/versions/2.7.0-rc2/lib/ruby/gems/2.7.0/gems/sinatra-2.0.7/lib/sinatra/base.rb:1641: warning: The last argument is used as keyword parameters; maybe ** should be added to the call
/Users/adam_ant/.rbenv/versions/2.7.0-rc2/lib/ruby/gems/2.7.0/gems/mustermann-1.0.3/lib/mustermann.rb:62: warning: The called method `new' is defined here
/Users/adam_ant/.rbenv/versions/2.7.0-rc2/lib/ruby/gems/2.7.0/gems/mustermann-1.0.3/lib/mustermann/pattern.rb:59: warning: The last argument is used as keyword parameters; maybe ** should be added to the call
/Users/adam_ant/.rbenv/versions/2.7.0-rc2/lib/ruby/gems/2.7.0/gems/mustermann-1.0.3/lib/mustermann/regular.rb:22: warning: The called method `initialize' is defined here
/Users/adam_ant/.rbenv/versions/2.7.0-rc2/lib/ruby/gems/2.7.0/gems/sinatra-2.0.7/lib/sinatra/base.rb:1604: warning: The last argument is used as keyword parameters; maybe ** should be added to the call
/Users/adam_ant/.rbenv/versions/2.7.0-rc2/lib/ruby/gems/2.7.0/gems/sinatra-2.0.7/lib/sinatra/base.rb:1621: warning: The called method `compile!' is defined here
/Users/adam_ant/.rbenv/versions/2.7.0-rc2/lib/ruby/gems/2.7.0/gems/mustermann-1.0.3/lib/mustermann/pattern.rb:59: warning: The last argument is used as keyword parameters; maybe ** should be added to the call
/Users/adam_ant/.rbenv/versions/2.7.0-rc2/lib/ruby/gems/2.7.0/gems/mustermann-1.0.3/lib/mustermann/regexp_based.rb:17: warning: The called method `initialize' is defined here
/Users/adam_ant/.rbenv/versions/2.7.0-rc2/lib/ruby/gems/2.7.0/gems/mustermann-1.0.3/lib/mustermann/ast/compiler.rb:43: warning: The last argument is used as keyword parameters; maybe ** should be added to the call
/Users/adam_ant/.rbenv/versions/2.7.0-rc2/lib/ruby/gems/2.7.0/gems/mustermann-1.0.3/lib/mustermann/ast/compiler.rb:49: warning: The called method `pattern' is defined here
/Users/adam_ant/.rbenv/versions/2.7.0-rc2/lib/ruby/gems/2.7.0/gems/sinatra-2.0.7/lib/sinatra/base.rb:1348: warning: The last argument is used as keyword parameters; maybe ** should be added to the call
/Users/adam_ant/.rbenv/versions/2.7.0-rc2/lib/ruby/gems/2.7.0/gems/sinatra-2.0.7/lib/sinatra/base.rb:1359: warning: The called method `add_filter' is defined here
/Users/adam_ant/.rbenv/versions/2.7.0-rc2/lib/ruby/gems/2.7.0/gems/sinatra-2.0.7/lib/sinatra/base.rb:1360: warning: The last argument is used as keyword parameters; maybe ** should be added to the call
/Users/adam_ant/.rbenv/versions/2.7.0-rc2/lib/ruby/gems/2.7.0/gems/sinatra-2.0.7/lib/sinatra/base.rb:1621: warning: The called method `compile!' is defined here
Traceback (most recent call last):
bin/rails: Bootsnap::LoadPathCache::FallbackScan
	47: from bin/rails:9:in `<main>'
	46: from /Users/adam_ant/.rbenv/versions/2.7.0-rc2/lib/ruby/gems/2.7.0/gems/activesupport-6.0.2.1/lib/active_support/dependencies.rb:325:in `require'
	45: from /Users/adam_ant/.rbenv/versions/2.7.0-rc2/lib/ruby/gems/2.7.0/gems/activesupport-6.0.2.1/lib/active_support/dependencies.rb:291:in `load_dependency'
	44: from /Users/adam_ant/.rbenv/versions/2.7.0-rc2/lib/ruby/gems/2.7.0/gems/activesupport-6.0.2.1/lib/active_support/dependencies.rb:325:in `block in require'
	43: from /Users/adam_ant/.rbenv/versions/2.7.0-rc2/lib/ruby/gems/2.7.0/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
	42: from /Users/adam_ant/.rbenv/versions/2.7.0-rc2/lib/ruby/gems/2.7.0/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `require_with_bootsnap_lfi'
	41: from /Users/adam_ant/.rbenv/versions/2.7.0-rc2/lib/ruby/gems/2.7.0/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
	40: from /Users/adam_ant/.rbenv/versions/2.7.0-rc2/lib/ruby/gems/2.7.0/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `block in require_with_bootsnap_lfi'
	39: from /Users/adam_ant/.rbenv/versions/2.7.0-rc2/lib/ruby/gems/2.7.0/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require'
	38: from /Users/adam_ant/.rbenv/versions/2.7.0-rc2/lib/ruby/gems/2.7.0/gems/railties-6.0.2.1/lib/rails/commands.rb:18:in `<main>'
	37: from /Users/adam_ant/.rbenv/versions/2.7.0-rc2/lib/ruby/gems/2.7.0/gems/railties-6.0.2.1/lib/rails/command.rb:46:in `invoke'
	36: from /Users/adam_ant/.rbenv/versions/2.7.0-rc2/lib/ruby/gems/2.7.0/gems/railties-6.0.2.1/lib/rails/command/base.rb:69:in `perform'
	35: from /Users/adam_ant/.rbenv/versions/2.7.0-rc2/lib/ruby/gems/2.7.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	34: from /Users/adam_ant/.rbenv/versions/2.7.0-rc2/lib/ruby/gems/2.7.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	33: from /Users/adam_ant/.rbenv/versions/2.7.0-rc2/lib/ruby/gems/2.7.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	32: from /Users/adam_ant/.rbenv/versions/2.7.0-rc2/lib/ruby/gems/2.7.0/gems/railties-6.0.2.1/lib/rails/commands/server/server_command.rb:138:in `perform'
	31: from /Users/adam_ant/.rbenv/versions/2.7.0-rc2/lib/ruby/gems/2.7.0/gems/railties-6.0.2.1/lib/rails/commands/server/server_command.rb:138:in `tap'
	30: from /Users/adam_ant/.rbenv/versions/2.7.0-rc2/lib/ruby/gems/2.7.0/gems/railties-6.0.2.1/lib/rails/commands/server/server_command.rb:141:in `block in perform'
	29: from /Users/adam_ant/.rbenv/versions/2.7.0-rc2/lib/ruby/gems/2.7.0/gems/activesupport-6.0.2.1/lib/active_support/dependencies.rb:325:in `require'
	28: from /Users/adam_ant/.rbenv/versions/2.7.0-rc2/lib/ruby/gems/2.7.0/gems/activesupport-6.0.2.1/lib/active_support/dependencies.rb:291:in `load_dependency'
	27: from /Users/adam_ant/.rbenv/versions/2.7.0-rc2/lib/ruby/gems/2.7.0/gems/activesupport-6.0.2.1/lib/active_support/dependencies.rb:325:in `block in require'
	26: from /Users/adam_ant/.rbenv/versions/2.7.0-rc2/lib/ruby/gems/2.7.0/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
	25: from /Users/adam_ant/.rbenv/versions/2.7.0-rc2/lib/ruby/gems/2.7.0/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `require_with_bootsnap_lfi'
	24: from /Users/adam_ant/.rbenv/versions/2.7.0-rc2/lib/ruby/gems/2.7.0/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
	23: from /Users/adam_ant/.rbenv/versions/2.7.0-rc2/lib/ruby/gems/2.7.0/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `block in require_with_bootsnap_lfi'
	22: from /Users/adam_ant/.rbenv/versions/2.7.0-rc2/lib/ruby/gems/2.7.0/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require'
	21: from /Users/adam_ant/Library/Mobile Documents/com~apple~CloudDocs/Sites/FlightRecord/config/application.rb:14:in `<main>'
	20: from /Users/adam_ant/.rbenv/versions/2.7.0-rc2/lib/ruby/2.7.0/bundler.rb:174:in `require'
	19: from /Users/adam_ant/.rbenv/versions/2.7.0-rc2/lib/ruby/2.7.0/bundler/runtime.rb:58:in `require'
	18: from /Users/adam_ant/.rbenv/versions/2.7.0-rc2/lib/ruby/2.7.0/bundler/runtime.rb:58:in `each'
	17: from /Users/adam_ant/.rbenv/versions/2.7.0-rc2/lib/ruby/2.7.0/bundler/runtime.rb:69:in `block in require'
	16: from /Users/adam_ant/.rbenv/versions/2.7.0-rc2/lib/ruby/2.7.0/bundler/runtime.rb:69:in `each'
	15: from /Users/adam_ant/.rbenv/versions/2.7.0-rc2/lib/ruby/2.7.0/bundler/runtime.rb:74:in `block (2 levels) in require'
	14: from /Users/adam_ant/.rbenv/versions/2.7.0-rc2/lib/ruby/gems/2.7.0/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
	13: from /Users/adam_ant/.rbenv/versions/2.7.0-rc2/lib/ruby/gems/2.7.0/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `require_with_bootsnap_lfi'
	12: from /Users/adam_ant/.rbenv/versions/2.7.0-rc2/lib/ruby/gems/2.7.0/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
	11: from /Users/adam_ant/.rbenv/versions/2.7.0-rc2/lib/ruby/gems/2.7.0/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `block in require_with_bootsnap_lfi'
	10: from /Users/adam_ant/.rbenv/versions/2.7.0-rc2/lib/ruby/gems/2.7.0/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require'
	 9: from /Users/adam_ant/.rbenv/versions/2.7.0-rc2/lib/ruby/gems/2.7.0/gems/scrypt-3.0.6/lib/scrypt.rb:6:in `<main>'
	 8: from /Users/adam_ant/.rbenv/versions/2.7.0-rc2/lib/ruby/gems/2.7.0/gems/activesupport-6.0.2.1/lib/active_support/dependencies.rb:325:in `require'
	 7: from /Users/adam_ant/.rbenv/versions/2.7.0-rc2/lib/ruby/gems/2.7.0/gems/activesupport-6.0.2.1/lib/active_support/dependencies.rb:291:in `load_dependency'
	 6: from /Users/adam_ant/.rbenv/versions/2.7.0-rc2/lib/ruby/gems/2.7.0/gems/activesupport-6.0.2.1/lib/active_support/dependencies.rb:325:in `block in require'
	 5: from /Users/adam_ant/.rbenv/versions/2.7.0-rc2/lib/ruby/gems/2.7.0/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:26:in `require'
	 4: from /Users/adam_ant/.rbenv/versions/2.7.0-rc2/lib/ruby/gems/2.7.0/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:40:in `rescue in require'
	 3: from /Users/adam_ant/.rbenv/versions/2.7.0-rc2/lib/ruby/gems/2.7.0/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `require_with_bootsnap_lfi'
	 2: from /Users/adam_ant/.rbenv/versions/2.7.0-rc2/lib/ruby/gems/2.7.0/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/loaded_features_index.rb:89:in `register'
	 1: from /Users/adam_ant/.rbenv/versions/2.7.0-rc2/lib/ruby/gems/2.7.0/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `block in require_with_bootsnap_lfi'
/Users/adam_ant/.rbenv/versions/2.7.0-rc2/lib/ruby/gems/2.7.0/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require': cannot load such file -- scanf (LoadError)

**Comment by maximeg** [comment]
`scanf` as of `2.7.0-preview2` is no longer a bundled gem with Ruby. It is now distributed alone by Rubygems.

You have to add it to your Gemfile.

See https://github.com/ruby/ruby/blob/v2_7_0_preview2/NEWS#compatibility-issues-excluding-feature-bug-fixes

**Comment by atstockland** [comment]
When I add gem 'scanf', '~> 1.0' to the gem file, and "require 'scanf'" to application.rb, ruby  crashes.  I've attached the crash report log if you are curious to see it.

Bootsnap seems to be what is calling scanf, not my app.  Perhaps I just need to wait for 2.7.0 and a future release fo rails...and, this will be ironed out.  Thanks @maximeg !

[ruby_2019-12-25-091657_Hamburglar.pdf](https://github.com/rails/rails/files/4000622/ruby_2019-12-25-091657_Hamburglar.pdf)

**Comment by akshaymohite** [comment]
As Ruby 2.7.0 is [released](https://www.ruby-lang.org/en/news/2019/12/25/ruby-2-7-0-released/), I was able to run Rails 6.0.2.1 on Ruby 2.7.0

**Comment by huobazi** [comment]
@akshaymohite, many warning was output with Rails 6.0.2.1  on Ruby 2.7.0

**Comment by akshaymohite** [comment]
@huobazi  yes, there are warnings with Rails 6.0.2.1.

Those warnings have been taken care of. To run edge rails with master branch:
```ruby
gem 'rails', github: 'rails/rails', branch: 'master'
```

**Comment by alaarab** [comment]
still getting these warnings on 2.7.0 with latest rails

```
rails-3eb1f1dd105a/activerecord/lib/active_record/associations.rb:1368: warning: The called method `has_many' is defined here
rails-3eb1f1dd105a/activerecord/lib/active_record/associations.rb:1824: warning: The called method `has_and_belongs_to_many' is defined here
rails-3eb1f1dd105a/activerecord/lib/active_record/associations.rb:1368: warning: The called method `has_many' is defined here
rails-3eb1f1dd105a/activerecord/lib/active_record/associations.rb:1368: warning: The called method `has_many' is defined here
rails-3eb1f1dd105a/activesupport/lib/active_support/rescuable.rb:51: warning: The called method `rescue_from' is defined here
rails-3eb1f1dd105a/activerecord/lib/active_record/associations.rb:1508: warning: The called method `has_one' is defined here
```

**Comment by eugeneius** [comment]
The original problem here (LoadError when requiring `scanf`) was explained in https://github.com/rails/rails/issues/38074#issuecomment-568862326.

The discussion has now drifted to Ruby 2.7 warnings, which we don't need to track with an issue. They'll be fixed in a future release of Rails, but they don't prevent you from running your app today.

**Comment by atstockland** [comment]
I'm still having trouble getting 2.7.0 to run with rails 6.0.2.1.  It may be the pg gem buggering me up.  I have isolated that gem as being problematic (in my app).  pg version '~> 1.1', '>= 1.1.4' works, but version 1.2.0 does not.

I'll post back here if I find the reason why I can't run 2.7.0 with rails 6.0.2.1.

**Comment by atstockland** [comment]
I'm up and running on 6.0.2.1 and 2.7.0.  I just wanted to follow up in case it helps someone else.   The only change I made from other unsuccessful upgrade attempts was upgrading my Postgresql.app (which upgraded Postgres to 12.1).  Might be coincidence, might not.  I upgraded my other gems first, then upgraded pg gem to 1.2.0, then upgraded ruby to 2.7.0.  And, things are working.

**Comment by diegodev9** [comment]
same problem here.. but got it fixed.. 
solution in gemfile:
gem 'pg', '1.2.2'
