### ISSUE TITLE
having a class named "Transaction"

### ISSUE THREAD

**Issue by seb-sykio** [rails/rails#38089]
i just tried to update to rails 6.x , but I have a problem with one of my class named "Transaction".
Until update to rails 6, everything was working fine, but now I get "undefined method" for each call to a method in my class Transaction.
Is it not allowed anymore to have a class "Transaction" ?
thanks

**Comment by eugeneius** [comment]
I wasn't able to reproduce this in a new Rails 6.0.2.1 application:

```
$ rails new blabbedy --skip-javascript
$ cd blabbedy
$ rails generate scaffold transaction
$ rails db:migrate
$ rails runner 'Transaction.create!'
```

Could you provide a sample application that demonstrates the problem?

**Comment by seb-sykio** [comment]
with something in the model like

`validate :my_method`
I get 

> undefined method my_method

**Comment by javierojeda94** [comment]
@seb-sykio can you provide a project or code example to run? I couldn't reproduce neither

**Comment by eileencodes** [comment]
I'm going to close this one out since there hasn't been a response in almost 2 weeks. @seb-sykio if you're able to reproduce in a sample application please reopen and provide a link to that application. Without a reproduction we'll be unable to help further.
