### ISSUE TITLE
Can't use "is null" within .order()

### ISSUE THREAD

**Issue by stgm** [rails/rails#38087]
### Background

I have a table where the order of display is determined by users, but some elements may not actually have order assigned. To be able to order these items nicely, I used the following clause:

    @psets = Pset.order('"psets"."order" is null, "psets"."order"')

Using this way of ordering is encouraged by [other developers](https://stackoverflow.com/questions/5826210/rails-order-with-nulls-last) and makes the "unordered" items come after all other. (Nevermind that I used a SQL keyword as a column name...)

### Actual behavior

Now currently on Rails 6.0, I am warned that I shouldn't use this way of querying anymore:

    DEPRECATION WARNING: Dangerous query method (method whose arguments are used as raw SQL) called with non-attribute argument(s): "\"psets\".\"order\" is null, \"psets\".\"order\"". Non-attribute arguments will be disallowed in Rails 6.1. This method should not be called with user-provided values, such as request parameters or model attributes. Known-safe values can be passed by wrapping them in Arel.sql(). (called from show at /Users/martijn/dev/course-site2/app/controllers/user_controller.rb:26)

I'm not quite sure why this warning is triggered, because the docs seem to actually propose this kind of syntax: [order in QueryMethods](https://api.rubyonrails.org/classes/ActiveRecord/QueryMethods.html#method-i-order).

Looking for a non-workaround solution I came up with the following:

    @psets = Pset.order(order: "is null", order: :asc)

Which does not work for ordering, but doesn't give an error either! However, when I switch the elements of the parameter hash, I do get an error:

    @psets = Pset.order(order: :asc, order: "is null")
    ArgumentError (Direction "is null" is invalid. Valid directions are: [:asc, :desc, :ASC, :DESC, "asc", "desc", "ASC", "DESC"]):

### Expected behavior

I would suggest that an `is null` "direction" is indeed added as a possibility for the order clause, and that one would be able to write such a query like this:

    @psets = Pset.order(order: :null, order: :asc)

If this does indeed seem a reasonable suggestion given the QueryMethods architecture, I could try building a PR.

### System configuration

**Rails version**: 6.0.1
**Ruby version**: 2.6.5p114

**Comment by maximeg** [comment]
What's you're trying to sort on is not the column `order` with a special thing, but the expression `order IS NULL` which is evaluated to a boolean that the DB sort in `ASC` order (`false` then `true`).

So an appropriate writing would be:

```ruby
@psets = Pset.order(Arel.sql("order IS NULL"), :order)
# or if explicit is wanted
@psets = Pset.order(Arel.sql("order IS NULL") => :asc, :order => :asc)
```

For those using, postgres, `order ASC` defaults to `order ASC NULLS LAST` so that this trick is unnecessary.

**Comment by stgm** [comment]
Thanks @maximeg. I see (also in other discussions) that the decision was made to not allow any kind of SQL expression, so your suggestion is the only solution.

I've made a PR https://github.com/rails/rails/pull/38092 to improve on the deprecation warning, because it was quite confusing and roundabout, especially in this case, where no user-provided data is inserted into the argument string and as such, it should be "safe" anyway.
