### ISSUE TITLE
Encoding of headers for ActionDispatch::Http::UploadedFile

### ISSUE THREAD

**Issue by pedros007** [rails/rails#38080]
When I upload a file with a `file_field` where the filename has UTF-8 characters (i.e. `Município_SP.shp`), an `ActionDispatch::Http::UploadedFile` object is created. The object looks like this:
```#<ActionDispatch::Http::UploadedFile:0x00007fe0f0598c00
     @content_type="application/octet-stream",
     @headers="Content-Disposition: form-data; name=\"aoi[vector_file]\"; filename=\"Munici\xCC\x81pio_SP.shp\"\r\n" + "Content-Type: application/octet-stream\r\n",
     @original_filename="Município_SP.shp",
     @tempfile=#<File:/tmp/RackMultipart20191223-20-jmab4k.shp>>
```

`original_filename` is encoded `UTF-8` (see #869). However, the `headers` are encoded in `ASCII-8BIT`.  I think `headers` should be given the same encoding as `original_filename`, which could come from the form parameter `"utf8"=>"✓"`.

Why does this matter? I instrument my code with `ActiveSupport::Notifications.subscribe` subscribed to `process_action.action_controller` and I log all my requests and parameters as JSON blobs.  Calling `payload.to_json`  raises the exception:

    Encoding::UndefinedConversionError: "\xCC" from ASCII-8BIT to UTF-8

This seems to be coming from `UploadedFile#headers`.

```
$ rails --version 
Rails 5.2.4
$ ruby --version
ruby 2.5.3p105 (2018-10-18 revision 65156) [x86_64-linux]
```

**Comment by drLoom** [comment]
Have exact situation.

While waiting for the resolve, consider to use this workaround:
1) As **before_action**
```
  before_action :encode_upload_header

  def encode_upload_header(_params = nil)
    return unless request.content_mime_type&.symbol == :multipart_form

    _params ||= params

    _params.each do |_k, v|
      case v
      when ActionController::Parameters
        encode_upload_header(v)
      when ActionDispatch::Http::UploadedFile
        headers = v.headers

        begin
          headers.encode!(Encoding::UTF_8)
        rescue EncodingError
          headers.force_encoding(Encoding::UTF_8)
        end
      end
    end
  end
```
2) Or as **middlware**

```
class EncodeUploadHeaders
  def initialize(app)
    @app = app
  end

  def call(env)
    request = Rack::Request.new(env)
    params  = request.params

    encode_head(params) if params

    @app.call(env)
  end

  private

  def encode_head(params)
    params.each do |k, v|
      if k == :file && v.is_a?(Hash) && v[:head]
        head = v[:head]

        begin
          head.encode!(Encoding::UTF_8)
        rescue EncodingError
          head.force_encoding(Encoding::UTF_8)
        end
      elsif v.is_a?(Hash)
        encode_head(v)
      end
    end
  end
end
```

**Comment by brunoarueira** [comment]
I've got the same issue on rails 6.0.3.5, I'll submit a pr following the same logic made to address the issue on #869 and suggested by OP too.

@rafaelfranca I guess this issue should be reopened
