### ISSUE TITLE
Issue when upload file and images to amazon s3 by active storage

### ISSUE THREAD

**Issue by Saleh-Salem** [rails/rails#38096]
0

Issue when upload file and images to amazon s3 by active storage

issue undefined method `upload' for nil:NilClass"

in local is working but when using it in server development is getting issue undefined method `upload' for nil:NilClass

I am creating an app with Rails 5.2 API and using active storage 5.2.3 to upload images and files to s3.

My configuration:

in config/environments/development.rb:

config.active_storage.service = :amazon

in config/storage.yml:

amazon:
  service: S3
  access_key_id: <%= Rails.application.credentials.dig(:aws, :access_key_id) %>
  secret_access_key: <%= Rails.application.credentials.dig(:aws, :secret_access_key) %>
  region: <%= Rails.application.credentials.dig(:aws, :s3_region) %>
  bucket: <%= Rails.application.credentials.dig(:aws, :bucket) %>
in models:

has_one_attached :avatar

or

has_many_attached :images

in controller:

params.permit(:name, avatar)

or

params.permit(:name, images: [])

**Comment by eugeneius** [comment]
Rails 5.2 is no longer supported for bug fixes. Can you reproduce the error on Rails 6.0?

If so, can you create a sample application that demonstrates the problem?
