### ISSUE TITLE
ActionCable GET requests High Response Time

### ISSUE THREAD

**Issue by birthdaycorp** [rails/rails#38095]
I get High Response Time on the `/cable` endpoint when using ActionCable with Puma server and a 512MB dyno on Heroku.

Here is an example of one such request. All requests to the `/cable` endpoint take a *very* long time:

    25 Dec 2019 14:13:31.061299 <158>1 2019-12-25T22:13:28.421009+00:00 heroku router - - at=info method=GET path="/cable" host=www.######.com request_id=#### fwd="####" dyno=web.1 connect=1ms service=531114ms status=101 bytes=174 protocol=https High Response Time

I've seen maybe max 3-4 other people experiencing this, but none of them seem to have any solution. They just stopped working with the Rails app. I'm looking into AnyCable, but it seems weird that an app that is currently only being used by myself is experiencing such high response time.

### Expected behavior
`/cable` requests should be processed in a few ms.

### Actual behavior
`/cable` requests are taking hundreds of seconds to process

### System configuration
Ruby version: 2.5.0
Rails version: 5.2.0
Puma version: 4.3.1

**Comment by scottrobel** [comment]
Ive had the same issue!

**Comment by birthdaycorp** [comment]
> Ive had the same issue!

Have you been able to fix it?

**Comment by youssef1337** [comment]
Anyone found a solution?

**Comment by birthdaycorp** [comment]
> Anyone found a solution?

Sort of. This alert isn't an issue at all, and it's to be expected. The `/cable` connection needs to be open so that it can send and receive messages. Heroku's Logentries add-on is just miscategorizing it, so I turned that alert off.
