### ISSUE TITLE
Regression with parallel tests connected to SQLite in Rails 6.1?

### ISSUE THREAD

**Issue by mcgregordan** [rails/rails#38104]
I have an app that uses the default `test.sqlite3` database for its test suite. We use parallelised testing (again, the Rails default — `parallelize(workers: :number_of_processors)`) and in Rails 6.0 everything works great.

In 6.1, however, the tests don’t reliably run parallelised. They run without parallelisation. But when parallelised the database locks, and you get this error several times:

```
ActiveRecord::StatementInvalid: SQLite3::BusyException: database is locked
```

On a (model-heavy) test suite of ~40 tests and ~340 lines of test code, the entire suite won’t run at all without the database locking. On smaller test suites, the error is more sporadic. But I’ve seen it on a 5- or 6-test suite with maybe 30 lines of test code (as measured by `rails stats`).

I know SQLite isn’t really meant to be used for concurrency. But it is convenient in tests, is the Rails default — and I haven’t encountered any issues until 6.1. That said, if I change the test db to postgres, the tests run as expected. (I am expecting to change the test adapter to postgres, just not quite so soon.)

Is this a bug? Has something changed for 6.1 that might be responsible for the SQLite errors?

### Steps to reproduce
I have created a simple demo app — https://github.com/mcgregordan/parallel_dbs_on_rails_61

### System configuration
**Rails version**: 6.1.0.alpha (https://github.com/rails/rails/commit/1f29b2dd5c634a6953a636ce1b01b7a4c3a0a89f)
**Ruby version**: 2.6.5
**SQLite version**: 3.30.1

**Comment by rafaelfranca** [comment]
Please do investigate. You know the version that it works, the version that it doesn't work and you have an example application. You did most of the work already.

**Comment by mcgregordan** [comment]
I think I’ve found the root cause. But I’m completely stumped by it.

`ActiveRecord::TestDatabases` sets up various different databases for use during parallel testing — eg, `db/test.sqlite3-0`, `db/test.sqlite3-1` etc. But in `database.yml` you define your database name as just `db/test.sqlite3`. The issue seems to lie in going from `test.sqlite3` to `.sqlite-0` (etc).

#38029 changed the way test databases are set up. Before that PR, the test databases were set up by modifying the configuration hash (what seems to come from `database.yml` for the test env). Specifically, `test.sqlite3` was transformed into various files (`.sqlite-0` etc). But #38092 froze the config object — that was its goal — so the way the `.sqlite-0` (etc) files were configured had to change.

Now we merge the (frozen) hash with the desired test (`-0` etc) files to generate a new instance with the correct values. The result is identical to the mutated hash we had before.

Yet because of that, we seem, somehow, to have this issue. The offending change seems to be [here](https://github.com/rails/rails/pull/38029/files#diff-f805b0bd5cd3d1472437b2bdc70a7982L15-L17). I can successfully implement the other changes in #38029 without causing this issue. Weirdly, I can only reproduce the issue if we *don’t* modify the original hash.

I’m at a loss as to why.

cc/ @eileencodes @seejohnrun [so sorry for cc’ing in holiday season]

**Comment by eileencodes** [comment]
Thanks for the report and ping. This is really strange. I’m off work until the 6th so I’ll look then. If you figure something out before that please update this issue.

**Comment by khustochka** [comment]
I am also experiencing this issue, and it is reproduced not only for SQLite. I am using Postgres.

It was indeed introduced in 154abcab6e0ee67d6527f613e354df41119c8c9d.

And yes, the parallel DBs (postfixed with -0, -1 etc) and just not created.

Demo app is here: https://github.com/khustochka/parallel_demo

Thank you.

**Comment by khustochka** [comment]
At some point `ActiveRecord::Base.configurations.configs_for(env_name: env_name)` just returns []

**Comment by seejohnrun** [comment]
I found the issue here and created a PR to fix it: https://github.com/rails/rails/pull/38151 🎉

**Comment by mcgregordan** [comment]
Thanks @seejohnrun. I did notice this while investigating but completely forgot to mention or PR it (🤦‍♂️).

After discovering this, I thought this would be the fix. Yet last week I *thought* I could still reproduce the issue.

But I think I was wrong. Having tried out your patch, everything seems to work now. 🙏

**Comment by mcgregordan** [comment]
Thanks @seejohnrun. I did notice this issue while investigating last week but completely forgot to mention or PR it (🤦‍♂️). I also thought, when I noticed this, it would fix the issue. Sadly I don”t think it does. (That said, I think — for what it’s worth — your PR is valid and should be merged.) I’ve published a branch on my demo app — https://github.com/mcgregordan/parallel_dbs_on_rails_61/tree/pr-38151 — that pulls in your patch and can reproduce the issue, although perhaps less frequently.

I have spent another 5 mins on this. Again, I’ve arrived at something that makes no sense to me. I can no longer reproduce if you apply #38151 and then unfreeze the hash (I get why we don’t want to do this!) and add back in this in TestDatabases:

```ruby
db_config.configuration_hash[:database] += "-#{i}"
```

That makes no sense! The database name generated for `db_config_copy` is identical! But — and maybe I’m wrong — that seems to be what’s what.

**Comment by seejohnrun** [comment]
Thanks @mcgregordan, what steps should I take on that branch to reproduce the issue you're seeing?

**Comment by mcgregordan** [comment]
`rails test` sporadically fails for me. On a more substantial (real-world) test suite, it fails every run.

**Comment by seejohnrun** [comment]
I see the issue now / It's that in the `ensure` isn't resetting to the updated database configuration. Will push another change to my branch in a few

**Comment by hasko** [comment]
I am seeing exactly the originally described behavior in Rails 6.1.4.1. Am I missing something? Was this fixed?

**Comment by milgner** [comment]
Seeing something very similar in Rails 7. See #41176 . Were there any findings from this issue that might be applicable?

**Comment by dirkjonker** [comment]
I think this is related to #13908 where SQLite is trying to upgrade a read lock to a write lock but is unable to. I experience this sometimes when running my tests in parallel, running 346 tests in 10 processes. Maybe 1 in 20 runs or so, but it is always annoying when it fails when your own code cannot help it.
