### ISSUE TITLE
Tests do not run in new Rails app

### ISSUE THREAD

**Issue by weilandia** [rails/rails#38121]
### Steps to reproduce
- Create a new rails app
- Run tests

### Expected behavior
- Tests should run

### Actual behavior
- Tests do not run because of `cannot load such file -- zip` in `2.6.0/gems/selenium-webdriver-3.142.7/lib/selenium/webdriver/common/zipper.rb:20:in <main>'`

- This issue is introduced in rubyzip 2.0.0 and can be resolved by pegging rubyzip at `gem 'rubyzip', '~> 1'`

### System configuration
**Rails version**:
Rails 6.0.2.1

**Ruby version**:
Ruby 2.6.5

**Comment by weilandia** [comment]
Bumping selenium-webdriver to `gem 'selenium-webdriver', '~> 4.0.0.alpha3'` also works because the update the deps from `rubyzip >= 1.2.2` to `rubyzip ~> 1.2` in version 4.

**Comment by weilandia** [comment]
Pull to selenium to fix the issue https://github.com/SeleniumHQ/selenium/pull/7902

**Comment by rafaelfranca** [comment]
Thank you for the report. Closing since this is an issue on selenium
