### ISSUE TITLE
Error installing Rails 6 with MYSQL

### ISSUE THREAD

**Issue by SylarRuby** [rails/rails#38138]
Postgres installs ok but not with mysql.

Ruby: 2.7.0
Rails 6.0.2.1
OS: Ubuntu 18

Command:

`rails new doo --api -d mysql`

Results:

```
To see why this extension failed to compile, please check the mkmf.log which can be found here:

  /home/deploy/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/extensions/x86_64-linux/2.7.0/mysql2-0.5.3/mkmf.log

extconf failed, exit code 1

Gem files will remain installed in /home/deploy/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/mysql2-0.5.3 for inspection.
Results logged to /home/deploy/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/extensions/x86_64-linux/2.7.0/mysql2-0.5.3/gem_make.out

An error occurred while installing mysql2 (0.5.3), and Bundler cannot continue.
Make sure that `gem install mysql2 -v '0.5.3' --source 'https://rubygems.org/'` succeeds before bundling.

In Gemfile:
  mysql2
         run  bundle binstubs bundler
Could not find gem 'mysql2 (>= 0.4.4)' in any of the gem sources listed in your Gemfile.
         run  bundle exec spring binstub --all
Could not find gem 'mysql2 (>= 0.4.4)' in any of the gem sources listed in your Gemfile.
Run `bundle install` to install missing gems.
```

**Comment by guilhermeyo** [comment]
I think your error is in install of gem mysql2 because I followed your command to install with ruby 2.6.5 and 2.7.0 and I have success in both.

Command:
`bundle exec rails new ~/Projects/test2-7 --api -d mysql`

Ruby: 2.6.5 and 2.7.0
Rails 6.0.2.1
OS: macOS Catalina 10.15.2

Output result in 2.7.0:
https://pastebin.com/Crw77iFG

**Comment by eileencodes** [comment]
This is missing some of the information so I'm not sure what library mysql is choking on but this isn't a Rails bug. I had a whole bunch of issues with libxml2 and openssl on Catalina. 

This post may help you https://www.rakeroutes.com/bundle-install-for-rails-6/

**Comment by sinsoku** [comment]
I tried using ubuntu:18.04 in Dockerfile.

```console
$ cat Dockerfile
FROM ubuntu:18.04

RUN apt-get update
RUN apt-get install -y \
      ruby \
      ruby-dev \
      build-essential \
      libmysqlclient-dev \
      libssl-dev \
      git
RUN gem i rails
RUN rails new doo --api -d mysql
$ docker build -t rails_38138 .
Successfully tagged rails_38138:latest
```

libmysqlclient-dev and libssl-dev are required to build mysql2 gem.

**Comment by SylarRuby** [comment]
Oh this works on Macs. I installed this on an Ubuntu server. Running the `new` command then `bundle install` I get the error. If it's a mysql gem issue then their is an issue with the install process using `-d mysql` command.

**Comment by simi** [comment]
Seems like problem installing mysql2 gem, feel free to open issue at https://github.com/brianmario/mysql2. Anyway looks not related to Rails itself.
