### ISSUE TITLE
dalli required for testing activesupport

### ISSUE THREAD

**Issue by dvzrv** [rails/rails#38134]
Hi! I'm currently packaging ruby-activesupport for Arch Linux. During testing I ran into a missing dependency for ruby-dalli.

### Steps to reproduce
* Install gems mentioned in `activesupport.gemspec`.
* Run `gem build activesupport.gemspec`.
* Run `rake test`.

### Expected behavior
Gemfile or .gemspec specify what is required to test activesupport.

### Actual behavior
Only Rakefile specifies (by failing during `rake test`) what is required to run the test.

### System configuration
**Rails version**: 6.0.2.1

**Ruby version**:
2.7.0

**Comment by rafaelfranca** [comment]
dalli is a optional dependency of active support, so it will not be added to the gemspec. It is already in the Gemfile of the Rails framework. See https://github.com/rails/rails/blob/6aad3b01506677d134fb4512b31177c44aa9ee77/Gemfile#L43

**Comment by dvzrv** [comment]
Okay. What is dalli used for though (in regards to being an optional dependency)? Is it used at runtime?
This doesn't become clear in the mentioned rails Gemfile.

I'm trying to understand whether I need to package this right away, or whether it can wait.

Furthermore: Wouldn't it be easier/ more granular to state the dependencies where they are actually used? When looking at the gems ecosystems it seems, that there are gems depending on e.g. only activesupport, but not on the rest of the rails framework.
Having a more granular setup allows for easier packaging and higher visibility in terms of what is required to build/test/use a gem such as activesupport (at least from my perspective).

**Comment by simi** [comment]
AFAIK it is used for one of `ActiveSupport::Cache::Store` implementations. There is also `Redis` based implementation. Do you face the same problem with that?

I think it will be reasonable to skip those tests when `Dalli` not available since it is not needed in runtime by default. @rafaelfranca would that contribution will be welcomed?

Alternatively any reason to not include that as a development/test dependency in gemspec?

**Comment by rafaelfranca** [comment]
We can skip the tests if it is not present. In fact we should do that.

Adding development dependencies to the gemspec just create confusion for people that believes the library depends on those gems. We prefer to not add them to the gemspec and only add them to the Gemfile.
