### ISSUE TITLE
Getting AbstractController::ActionNotFound instead of NameError when controller module is not defined

### ISSUE THREAD

**Issue by john-denisov** [rails/rails#38149]
### Steps to reproduce

1) define a simple controller that includes missing module

```ruby
# app/controllers/showcase_include_bug_controller.rb
class ShowcaseIncludeBugController < ApplicationController
  include MadeUpModuleName

  def index
  end
end

# config/routes.rb
# ...
get "showcase_include_bug", to: "showcase_include_bug#index"
# ...
```

2) launch rails server and go to http://localhost:3000/showcase_include_bug

### Expected behavior

Rails should raise `NameError (uninitialized constant MadeUpModuleName)`
### Actual behavior

Rails raises `AbstractController::ActionNotFound (The action 'index' could not be found for ShowcaseIncludeBugController)` or uses ancestor's implementation of index action (if present).

### System configuration
**Rails version**: 6.0.2.1
**Ruby version**: 2.6.5

**Comment by rafaelfranca** [comment]
Have you tried with the 6-0-stable branch or the master branch. I believe this problem was already fixed in https://github.com/rails/rails/pull/37834.
