### ISSUE TITLE
[Request] Out of box notification solution

### ISSUE THREAD

**Issue by cooldesigns** [rails/rails#38143]
Mailbox, Action View, Active Storage, Action Cable, Action Text... and then now? What is the next?

I think the next candidate should: Action Notification, and second Active Role, third Active GraphQL.

User notification with adapter. Example for sms: Amazon SNS or Twilio, Example for ActionCable rails-engine/notifications

Application notification: Across workers, threads, objects with notification and subscribe capabilities, storing delivery status. Maybe top on a popular message bus.

https://evilmartians.com/chronicles/crafting-user-notifications-in-rails-with-active-delivery
https://github.com/palkan/abstract_notifier
https://github.com/rails-engine/notifications
https://github.com/rails-engine/role_core

**Comment by rafaelfranca** [comment]
Thank you so much for for the suggestions, but so far we have no need for those new components. If the core team see needs for similar new components we will  build them.
