### ISSUE TITLE
Backport sqlite3 version pin to 4.x and 5.x

### ISSUE THREAD

**Issue by abitrolly** [rails/rails#38154]
https://github.com/rails/rails/commit/d9601fd622a08b8ef5346c10f00fb13328d34d76 needs to be backported to 4.x and probably 5.x because rails 4.x is unable to load sqlite3 1.4 version.

### Steps to reproduce

Get `rails 4.x` and try to run test app.

$ rails new testapp --skip-bundle
$ cd testapp
$ bundle install --path ./vendor/bundle
$ rails server

### Actual behavior

Gem::LoadError (Specified 'sqlite3' for database adapter, but the gem is not loaded. Add `gem 'sqlite3'` to your Gemfile (and ensure its version is at the minimum required by ActiveRecord).):

### System configuration
**Rails version**:
Rails 4.2.11.1

**Ruby version**:
ruby 2.6.5p114 (2019-10-01 revision 67812) [x86_64-linux]

**Comment by rafaelfranca** [comment]
Rails 4 and Rails 5 is not supported anymore.
