### ISSUE TITLE
Generating a new Mailer yields a zeitwerk warning

### ISSUE THREAD

**Issue by colinxfleming** [rails/rails#38156]
### Steps to reproduce
Hi, I spent some time looking thru the zeitwerk related issues but possible I missed, it, so I apologize if this is redundant to something that's already been opened and dealt with.

I've been slowly porting some stuff over to rails 6 and I noticed that zeitwerk was throwing some surprising-to-me warnings about actionmailer preview stuff. Per [docs](https://guides.rubyonrails.org/action_mailer_basics.html#walkthrough-to-generating-a-mailer) `rails g mailer XxxMailer` puts a preview utility in `test/mailers/previews/xxx_mailer_preview.rb` and zeitwerk doesn't know quite what to do with that, spitting out a warning about eager loading.

I've put it in a sample app (rails new + a commit to generate a mailer) here: https://github.com/colinxfleming/zeitwerk_actionmailer_check That uses rails 6.0-stable to demonstrate that this is happening on fresh rails apps.

FWIW this isn't stopping me from doing anything, but wanted to raise a flag about it since it was a bit surprising to me. I'm happy to try to make tweaks if it's helpful, but don't really know what direction to push on. (Sorry I can't be more helpful!)

### Expected behavior
`rails zeitwerk:check` should come back clean after generating a mailer. I think?

### Actual behavior
running `rails g mailer WarningMailer` and then `rails zeitwerk:check` yields a warning:

```
MacBook-Air:zeitwerk_actionmailer_check colin$ rails g mailer WarningMailer
Running via Spring preloader in process 36729
      create  app/mailers/warning_mailer.rb
      invoke  erb
      create    app/views/warning_mailer
      invoke  test_unit
      create    test/mailers/warning_mailer_test.rb
      create    test/mailers/previews/warning_mailer_preview.rb
MacBook-Air:zeitwerk_actionmailer_check colin$ rails zeitwerk:check
Hold on, I am eager loading the application.

WARNING: The files in these directories cannot be checked because they
are not eager loaded:

  /Users/colin/repos/zeitwerk_actionmailer_check/test/mailers/previews

You may verify them manually, or add them to config.eager_load_paths
in config/application.rb and run zeitwerk:check again.

Otherwise, all is good!
```

### System configuration
**Rails version**:
 6-0-stable@633059a (which per #36461 includes a fix for an unrelated zeitwerk issue still present on 6.0.2.1); also saw this on the 6.0.1 app I've been working on

**Ruby version**:
2.6.5

**Comment by rafaelfranca** [comment]
cc @fxn. I think we should ignore mailer previews from that task.

**Comment by fxn** [comment]
Interesting, those files do not follow the conventions.

**Comment by colinxfleming** [comment]
I'm happy to roll up a fix if it's helpful. If we want to ignore mailer previews as @rafaelfranca suggests, could probably add another `reject` under https://github.com/rails/rails/blob/master/railties/lib/rails/tasks/zeitwerk.rake#L65 ?

**Comment by fxn** [comment]
I think ignoring the files is not a good direction to address this one.

The purpose of `zeitwerk:check` is to ensure that if file _f_ is autoloadable, it autoloads correctly. Unfortunately, this is not done syntactically, it is done loading the file, and that introduces compromises. In particular, it doesn't load files that are not in the eage load paths, to be conservative, and warns the user.

So, if `test/mailers/previews/warning_mailer_preview.rb` is ignored and has a typo in the name of the class it defines, the task would say everything is good if the rest is, but it should not say so. That is why I believe previews should not be ignored.

Possible alternative solutions:

* Users can add previews to the eager load paths as explained in the warning message if they want the warning to be silenced.
* Action Mailer could add previews to the eager load paths in addition to the autoload paths (probably I would not do this, but it is an option technically).
* The task could have an option to force eager loading of everything in the autoload paths, disabled by default.
* The task could have a way to silence warnings, disable at your own risk.

**Comment by fxn** [comment]
Perhaps a fifth option is to improve the warning message, perhaps it was confusing because the compromise explained above is not obvious if you do not know how the task works, and it is unexpected that Rails generates something whose correctness cannot be verified.

**Comment by colinxfleming** [comment]
yeah, like you said @fxn I think the surprise for me was that it was happening on a fresh rails app after generating a mailer - e.g. I hadn't had a chance to mess anything up yet 😂 , just ran `rails new` and `rails g mailer` and `rails zeitwerk:check`.

please let me know if I should step out of this conversation and let the rails team hash it out, but my preference would be some kind of a solution where running a generator doesn't result in code with warnings. Definitely possible that I should just chill though, so let me know if that's the case too.

**Comment by fxn** [comment]
@colinxfleming hey! no, no, the conversation is very welcome, the issue is open and some decision of some kind has to be taken. It just may take a bit because of my OSS backlog.

**Comment by colinxfleming** [comment]
@fxn  ah, I got you! This is the first time I've opened an issue on rails so I wanted to make sure I wasn't accidentally being rude or anything 😂 thanks much.

**Comment by colinxfleming** [comment]
bumped my demo repo to see if this was still going down on stable (it is). Not news to you all I'm sure, but in the unlikely event that you needed independent confirmation!

**Comment by colinxfleming** [comment]
solid, thanks @fxn and @peterb !
