### ISSUE TITLE
ActiveStorage custom storage path configuration per Model attribute

### ISSUE THREAD

**Issue by frantisekrokusekpa** [rails/rails#38161]
## Context
Hello Rails Team!
First of all I want to thank you for all job that you make here!!! Rails is a wonderful framework to work with.

I am creating an issue because I am not sure I have understood all functionalities of ActiveStorage. My pull request is not quite ready...

Here is my issue: **ActiveStorage custom storage path configuration per Model attribute**

Here is our business issue: *We use the [apartment gem](https://github.com/influitive/apartment) to split our datas on a client basis and we want to make the same with uploaded files and store them in separate folders.*

Rails versions: >5.2

**thoughtbot** has made a wonderfull [paperclip gem](https://github.com/thoughtbot/paperclip), but since it is deprecated we are in the process of switching to ActiveStorage all our attachments management.

In Paperclip there is a fine feature where you can choose a [specific storage path](https://github.com/thoughtbot/paperclip) for each of the model attachable attribute and interpolate values in it as follows:

```ruby
# app/models/user.rb

# in Paperclip
has_attached_file :avatar,
                  path: ':tenant/users/:user_id/:hash/:filename'
```

### Expected behaviour
Being able to configure a custom path.
The idea is to make this possible in ActiveStorage too and have something like that:

```ruby
# app/models/user.rb

# in future ActiveStorage
has_one_attached :avatar,
                 path: ':tenant/users/:id/:unique_secure_token'
```

### Our current solution
For the moment we have made a *monkey_patching* to implement those storage path by changing the `ActiveStorage::Blob#key`.

```ruby
# app/models/user.rb

def document=(attachable)
  document.attach(create_blob(attachable))
end

def attachable_storage_path
  [
    Apartment::Tenant.current.parameterize,
    'users',
    id,
    ActiveStorage::Blob.generate_unique_secure_token
  ].compact.join('/')
end
```

```ruby
# app/models/application_record.rb

def attachable_storage_path
  raise NotImplementedError
end

def create_blob(attachable)
  return if attachable.nil?

  ActiveStorage::Blob.new.tap do |blob|
    blob.filename = attachable.original_filename
    blob.key = attachable_storage_path
    blob.upload(attachable)
    blob.save!
  end
end
```

### Future solution
I have began to make a PR on ActiveStorage but want to have your feedback on this feature before digging deeper in this problematic and validate the right direction! Some questions to guide:
- Is the `ActiveStorage::Blob#key`the right attribute to integrate this feature?
- Do you think it is worth to make it `interpolable` as in Paperclip, to avoid being requested to create an `#attachable_storage_path` method?

Here it is: [ActiveStorage custom storage path configuration](https://github.com/frantisekrokusekpa/rails/pull/1/files)

Thank you for your feedback and advices!

### Actual behavior
Not possible.

### System configuration
**Rails version**: > 5.2

**Ruby version**: > 2.6.5

**Comment by georgeclaghorn** [comment]
> * Is the `ActiveStorage::Blob#key` the right attribute to integrate this feature?
> * Do you think it is worth to make it `interpolable` as in Paperclip, to avoid being requested to create an `#attachable_storage_path` method?

Yes and yes.

**Comment by Dhirendra24** [comment]
Are we planning to implement it ?

**Comment by frantisekrokusekpa** [comment]
> Are we planning to implement it ?

I hope so, I am working on it!

**Comment by frantisekrokusekpa** [comment]
Linked PR https://github.com/rails/rails/pull/41004, do not hesitate to upvote if interested!

**Comment by jamesst20** [comment]
Looking forward to this @frantisekrokusekpa ! 

I went for another approach in the mean time. I will share in case in can be useful to someone else.

I created a model concern:
```

module ActiveStoragePath
  extend ActiveSupport::Concern

  class_methods do
    def has_one_attached_with(name, path:) # rubocop:disable Naming/PredicateName
      has_one_attached name

      define_method "#{name}=" do |attachable|
        action = super attachable

        return action unless action.is_a? ActiveStorage::Attached::Changes::CreateOne
        return action unless action.blob.service_name == 'amazon'

        # This is how it is generated by default
        original_key = action.blob.class.generate_unique_secure_token

        # The key is used for path + filename when Amazon S3 is used. Append path + file extension
        action.blob.key = File.join(instance_exec(&path), "#{original_key}#{File.extname(action.blob.filename.to_s)}")

        action
      end
    end
  end
end
```

Usage

```
class MyModel < ApplicationRecord
  # has_one_attached :my_file
  has_one_attached_with :my_file, path: -> { "folder_name" }
  ...
end
```

**Comment by gabriel-cardoso** [comment]
Looking forward for this feature too.

On my side, I created an initializer `config/initializers/active_storage_custom_key.rb` with the following code

```ruby
Rails.application.config.to_prepare do
  require 'active_storage/blob'
  ActiveStorage::Blob.class_eval do
    def key
      self[:key] ||= File.join(self.class.generate_unique_secure_token, filename.to_s)
    end
  end
end
```

This generates keys with the form `SZJLX7fLpsv1dzzj2PhRg7ve/my_filename.jpg`

**Comment by frantisekrokusekpa** [comment]
Nice trick @gabriel-cardoso! Sadly though it's app wide and not model specific 😢 

Feel free to review and comment!

**Comment by pandancode** [comment]
> Looking forward to this @frantisekrokusekpa !
> 
> I went for another approach in the mean time. I will share in case it can be useful to someone else.
> 
> I created a model concern:
> 
> ```
> 
> module ActiveStoragePath
>   extend ActiveSupport::Concern
> 
>   class_methods do
>     def has_one_attached_with(name, path:) # rubocop:disable Naming/PredicateName
>       has_one_attached name
> 
>       define_method "#{name}=" do |attachable|
>         action = super attachable
> 
>         return action unless action.is_a? ActiveStorage::Attached::Changes::CreateOne
>         return action unless action.blob.service_name == 'amazon'
> 
>         # This is how it is generated by default
>         original_key = action.blob.class.generate_unique_secure_token
> 
>         # The key is used for path + filename when Amazon S3 is used. Append path.
>         action.blob.key = File.join(instance_exec(&path), original_key)
> 
>         action
>       end
>     end
>   end
> end
> ```
> 
> Usage
> 
> ```
> class MyModel < ApplicationRecord
>   include ActiveStoragePath
> 
>   # has_one_attached :my_file
>   has_one_attached_with :my_file, path: -> { "folder_name" }
>   ...
> end
> ```

Would love to see this one included in standard rails!

**Comment by rietta** [comment]
Is anyone else having trouble with this trick in Rails 7?
