### ISSUE TITLE
Postgres connection adaptor disable_referential_integrity should account for table ownership

### ISSUE THREAD

**Issue by justinkillen** [rails/rails#38165]
In AWS RDS, permissions are restricted in such a way that the command "ALTER TABLE #{quote_table_name(name)} DISABLE TRIGGER ALL" is not allowed (as is implemented in rails/activerecord/lib/active_record/connection_adapters/postgresql/referential_integrity.rb).  Alternative solutions exist, such as tweaking the variable session_replication_role (https://dba.stackexchange.com/questions/96961/how-to-temporarily-disable-foreign-keys-in-amazon-rds-postgresql), but that leads to unexpected consequences, as that is a session level change, and causes tests to fail where the trigger is expected to fire.

There should be an alternative to instead drop the constraint (and later re-create it).  This could be automated via something like:

select kcu.table_schema || '.' ||kcu.table_name as foreign_table,
       '>-' as rel,
       rel_tco.table_schema || '.' || rel_tco.table_name as primary_table,
       string_agg(kcu.column_name, ', ') as fk_columns,
       kcu.constraint_name
from information_schema.table_constraints tco
join information_schema.key_column_usage kcu
          on tco.constraint_schema = kcu.constraint_schema
          and tco.constraint_name = kcu.constraint_name
join information_schema.referential_constraints rco
          on tco.constraint_schema = rco.constraint_schema
          and tco.constraint_name = rco.constraint_name
join information_schema.table_constraints rel_tco
          on rco.unique_constraint_schema = rel_tco.constraint_schema
          and rco.unique_constraint_name = rel_tco.constraint_name
where tco.constraint_type = 'FOREIGN KEY'
group by kcu.table_schema,
         kcu.table_name,
         rel_tco.table_name,
         rel_tco.table_schema,
         kcu.constraint_name
order by kcu.table_schema,
         kcu.table_name;

(https://dataedo.com/kb/query/postgresql/list-foreign-keys).

Alternatively (and naively), it seems like we're creating the constraints just to disabled them - perhaps there could be an option to just not create the foreign keys to begin with, or maybe just after the tests are completed?

### Steps to reproduce

* Set test database to an AWS RDS postgres instance
* run rake test

### Expected behavior

DB tests should succeed

### Actual behavior

DB tests fail

### System configuration
**Rails version**: Current

**Ruby version**: Current

**Comment by yahonda** [comment]
As far as I remember, there was a pull request to support disabling foreign keys without superuser privileges https://github.com/rails/rails/pull/27636/files, It had been merged then reverted due to https://github.com/rails/rails/issues/28888 .

**Comment by justinkillen** [comment]
Forgive my ignorance here, but what is the rationale for disabling the constraints?
