### ISSUE TITLE
Mailer classes do not load until console is reloaded (reload! is called)

### ISSUE THREAD

**Issue by tambakoo** [rails/rails#38174]
### Steps to reproduce
Create a mailer using generator or manually. Add methods to this class. Start rails console and try to use these methods from this class on the console.
Example
```
class ReportMailer < ApplicationMailer
  def daily_report(args)
     #do stuff
   end
end
```

### Expected behavior
Method should have worked.

### Actual behavior
`NameError (uninitialized constant ReportMailer)` my mailer is called ReportMailer

### System configuration
Rails 6.0.1
Ruby 2.5.0

**Comment by rafaelfranca** [comment]
Can you explain a little bit better how are you trying to run the code? Are you trying to use a class in a console that was started before the class was added to the codebase?

**Comment by tambakoo** [comment]
> Can you explain a little bit better how are you trying to run the code? Are you trying to use a class in a console that was started before the class was added to the codebase?

Add Mailer -> Start console -> Call method -> Error

**Comment by fxn** [comment]
Suspicious, mailers are application code like anything else.

Can you please provide a step by step reproduction?

**Comment by fxn** [comment]
And the title says, "until console is reloaded". If the console was not already started, in which sense it is reloaded?

**Comment by rafaelfranca** [comment]
Calling `reload!` in the console.

**Comment by tambakoo** [comment]
> And the title says, "until console is reloaded". If the console was not already started, in which sense it is reloaded?

`reload!` I called. Sorry I made it clear.

**Comment by fxn** [comment]
I cannot reproduce.

```
% bin/rails g mailer MyMailer
Running via Spring preloader in process 7162
      create  app/mailers/my_mailer.rb
      invoke  erb
      create    app/views/my_mailer
      invoke  test_unit
      create    test/mailers/my_mailer_test.rb
      create    test/mailers/previews/my_mailer_preview.rb
```

Now I open `app/mailers/my_mailer.rb` and add

```ruby
def foo; :foo; end
```

and launch a console:

```
% bin/rails c
Running via Spring preloader in process 7314
Loading development environment (Rails 6.0.2.1)
irb(main):001:0> MyMailer.new.foo
=> :foo
```

Could you please provide reproduction steps?

**Comment by tambakoo** [comment]
> I cannot reproduce.
> 
> ```
> % bin/rails g mailer MyMailer
> Running via Spring preloader in process 7162
>       create  app/mailers/my_mailer.rb
>       invoke  erb
>       create    app/views/my_mailer
>       invoke  test_unit
>       create    test/mailers/my_mailer_test.rb
>       create    test/mailers/previews/my_mailer_preview.rb
> ```
> 
> Now I open `app/mailers/my_mailer.rb` and add
> 
> ```ruby
> def foo; :foo; end
> ```
> 
> and launch a console:
> 
> ```
> % bin/rails c
> Running via Spring preloader in process 7314
> Loading development environment (Rails 6.0.2.1)
> irb(main):001:0> MyMailer.new.foo
> => :foo
> ```
> 
> Could you please provide reproduction steps?

These are the steps that I followed but I too am not able to reproduce this error. :/ 
Do you think having multiple rails consoles open on different projects had anything to do here ? Or any other piece of code that is shared between versions (I'm just guessing).

**Comment by fxn** [comment]
> Do you think having multiple rails consoles open on different projects had anything to do here ? Or any other piece of code that is shared between versions (I'm just guessing).

If the consoles are opened for different projects, in principle that would not matter.

If you had two consoles opened for the same project, loaded the mailer in one, and then forgot you did it later on, that one would not reflect the changes until reloading. That is because consoles do not reload automatically like web requests do (you probably know that).

**Comment by tambakoo** [comment]
> > Do you think having multiple rails consoles open on different projects had anything to do here ? Or any other piece of code that is shared between versions (I'm just guessing).
> 
> If the consoles are opened for different projects, in principle that would not matter.
> 
> If you had two consoles opened for the same project, loaded the mailer in one, and then forgot you did it later on, that one would not reflect the changes until reloading. That is because consoles do not reload automatically like web requests do (you probably know that).

I understand. While I was encountering this error I had eliminated human errors like these and the console was still not identifying the class. 
I'll close this issue for now.

**Comment by fxn** [comment]
Excellent, weird though. Let's close to keep issues low (so to speak, haha), but please reopen if you find a way to reproduce.

**Comment by tdeck** [comment]
I've just observed this same behavior - got the uninitialized constant and found this bug. Calling reload! works every time. Definitely had only one console open. In my case and it's reproduceable. I'm not sure how I can help debug it other than that I'm using Rails 6.0.2 and my project is quite simple.

**Comment by fxn** [comment]
If it is reproducible, the best way to help is to describe the reproduction steps in a minimal app.

**Comment by fxn** [comment]
I cannot reproduce this, and people use mailers routinely. Please, if you find a way to reproduce feel free to followup.

**Comment by alea12** [comment]
I found a way to reproduce. The minimal example from `rails new` is as follows:

```
$ ruby -v
ruby 2.7.0p0 (2019-12-25 revision 647ee6f091) [x86_64-darwin19]
$ rails -v
Rails 6.0.2.1
```

```
$ rails new console_mailer_load_test
$ cd console_mailer_load_test
$ rails g mailer User notification
$ bin/rails c
```

```
Running via Spring preloader in process *****
Loading development environment (Rails 6.0.2.1)
irb(main):001:0> UserMailer
Traceback (most recent call last):
        1: from (irb):1
NameError (uninitialized constant UserMailer)
irb(main):002:0> reload!
Reloading...
=> true
irb(main):003:0> UserMailer
=> UserMailer
irb(main):004:0>
```

I haven't had time to examine this in detail yet, but I wish you can kindly re-open this issue. @fxn

**Comment by alea12** [comment]
Further notes: when I run in `production` mode, it works fine.

```
$ bin/rails c -e production
Running via Spring preloader in process *****
WARNING: Spring is running in production. To fix this make sure the spring gem is only present in `development`
 and `test` groups in your Gemfile and make sure you always use `bundle install --without development test` in 
production
Loading production environment (Rails 6.0.2.1)
irb(main):001:0> UserMailer
=> UserMailer
```

**Comment by fxn** [comment]
@alea12 could you please try disabling Spring?

```
rails new console_mailer_load_test --skip-spring
```

**Comment by alea12** [comment]
@fxn Thanks for your agile response! Disabling Spring seemed to work for my environment:

```
$ rails new console_mailer_load_test_without_spring --skip-spring
$ cd console_mailer_load_test_without_spring
$ bin/rails c
Loading development environment (Rails 6.0.2.1)
irb(main):001:0> UserMailer
=> UserMailer
```

In addition, temporarily removing the gems `spring` and `spring-watcher-listen` from my `Gemfile` (in `development` section) and re-bundling resolved my project repository from causing the `uninitialized constant FooBarMailer` issue in the console.

**Comment by fxn** [comment]
Interesting, thanks!

I have some busy days, but will eventually dig into this.

**Comment by fxn** [comment]
Hey! Heads up, I have been able to reproduce something weird that seems probably related (irrelevant output cut):

```
% rails new issue_38714 --no-rc
% cd issue_38714
% spring status
Spring is not running.
% rails g mailer MyMailer
Running via Spring preloader in process 34902
% rails r MyMailer
Running via Spring preloader in process 35110
uninitialized constant MyMailer
```

If you then do something as simple as

```
% echo "Foo = 1" > app/models/foo.rb
```

The constant `Foo` is not found:

```
% rails r Foo
uninitialized constant Foo
```

I have added some traces and the problem is that, for some reason, Spring does not notice the project has changed and it does not trigger a reload.

If you stop Spring, or perform that process with Spring disabled, this does not happen.

It does seem related to mailers, because if you try to do the same steps with an innocent

```
% rails g job foo
```

`FooJob` is found as usual. Same with models, etc.

**Comment by fxn** [comment]
Ah, let me underline I do not claim Spring is the culprit. I do not know who is, only saying so far that Spring does not reload.

**Comment by alea12** [comment]
@fxn Thanks for the update! I've trailed the same procedure and noticed that after my first `rails g mailer foo`, whatever you generate with the rails generator will not be loaded from that point. Here is an example:

```
$ rails new issue_38714 --no-rc
$ cd issue_38714
$ rails g model foo
$ rails r Foo
Running via Spring preloader in process 8024
```
```
$ rails g mailer bar
$ rails r BarMailer
Running via Spring preloader in process 8054
uninitialized constant BarMailer
```
```
$ rails g model baz
$ rails r Baz
Running via Spring preloader in process 8083
uninitialized constant Baz
```

My guess is that something might be wrong with the rails generator (especially the mailer) or the spring loader which is responsible for detecting file / object changes among the mailer classes.

**Comment by trivedi** [comment]
Yup, this is happening to me too. @fxn / @alea12 comment on disabling Spring was the workaround for me as well.

**Comment by chrislintw** [comment]
I have same problem too. 
try `spring stop` . It works for me. 

```
> rails g mailer Happy
> rails r HappyMailer
uninitialized constant HappyMailer
> spring stop
Spring stopped.
> rails c
2.7.1 :001 > HappyMailer
 => HappyMailer
```

```
Rails 6.0.3.2
Ruby 2.7.1p83
```

**Comment by jonathanhefner** [comment]
This issue occurs because [**all** listeners are stopped](https://github.com/rails/rails/blob/v6.0.0/activesupport/lib/active_support/evented_file_update_checker.rb#L118) (but not all restarted) when a previously non-existent watched directory is created, e.g. `test/mailers/previews`.  I intend to fix this, but guard/listen#476 needs to be resolved first, which I am working on.

**Comment by michael-lins** [comment]
> I have same problem too.
> try `spring stop` . It works for me.
> 
> ```
> > rails g mailer Happy
> > rails r HappyMailer
> uninitialized constant HappyMailer
> > spring stop
> Spring stopped.
> > rails c
> 2.7.1 :001 > HappyMailer
>  => HappyMailer
> ```
> 
> ```
> Rails 6.0.3.2
> Ruby 2.7.1p83
> ```

yep, worked like a charm, I just love  this community 😭

**Comment by cheesam** [comment]
I had the same issue and `spring stop` was the resolution. This has been driving me crazy, so I wanted to say thanks for this!

**Comment by mariagroves** [comment]
I also had this issue and `spring stop` works.

**Comment by jmzbond** [comment]
Same issue. More nefariously... as other people have commented, once a mailer is added, then other things that are added are also not available in console. Specifically for me, new environment variables added to `application.yml` were not available, and moreover, running `reload!` in console did not work. I had to `spring stop` to get the new environment variables to be available

**Comment by fxn** [comment]
@jmzbond are those environment variables Unix environment variables or normal entries in that `application.yml`? If the former, that is expected, you need a new Unix process to receive new variables. If the latter, when does your application load that config file?

**Comment by jmzbond** [comment]
@fxn the latter, I'm not sure, I'm guessing whenever config generally is loaded? Just a standard Rails app

**Comment by fxn** [comment]
@jmzbond A file called `application.yml` is custom, either your application loads it manually, or it uses some gem to manage this configuration.

Normally, such file is loaded when the application boots, and it does not run again ever. The `reload!` command only reloads _application code_, does not reboot the whole application and not having the configuration updated is expected. Same if you are running the server. In that case, you need to quit and launch the console or server again to see the configuration updated.

**Comment by jmzbond** [comment]
I'm using the `figaro` gem. Yes I see what you're saying. The issue is, quit/relaunch console also did NOT get the variables to be available, of course that's what I always have to do. I literally had to use `spring stop`

**Comment by fxn** [comment]
@jmzbond Cool. So yes, that is not related to what this issue is about, just to clarify. The README of the gem has[ a section about Spring](https://github.com/laserlemon/figaro/blob/6ae998e8209a08f91a165822abecffc0a0626814/README.md#spring-configuration), that's what you need.

**Comment by fxn** [comment]
Ah, if you removed Spring, then you're already good 👍.

**Comment by jmzbond** [comment]
ah d'oh! well if helpful I can delete these comments ! thanks for your help!

**Comment by fxn** [comment]
@jmzbond no worries :), happy new year!
