### ISSUE TITLE
Route helpers don't work for resources :apps

### ISSUE THREAD

**Issue by joshleblanc** [rails/rails#38175]
### Steps to reproduce
1. clone `https://github.com/joshleblanc/rails-url-helpers`
2. create the database, migrate, etc
3. run `bundle exec ruby -Itest .\test\controllers\apps_controller_test.rb --name /test_should_get_index/`

### Expected behavior
The tests should pass

### Actual behavior
The url helpers aren't defined

### System configuration
**Rails version**: 6.0.2.1

**Ruby version**: 2.5.5

**Comment by rafaelfranca** [comment]
It is probably because of `@app = apps(:one)`. [`@app` is a reserved name of the framework](https://github.com/rails/rails/blob/master/actionpack/lib/action_dispatch/testing/integration.rb#L331). Can you see if removing that fixes it?

**Comment by joshleblanc** [comment]
It does indeed! Good to know.
