### ISSUE TITLE
nested field and uniqueness

### ISSUE THREAD

**Issue by seb-sykio** [rails/rails#38181]
```
class Company < ApplicationRecord
  has_many :company_users, dependent: :destroy, inverse_of: :company

  accepts_nested_attributes_for :company_users, allow_destroy: true, reject_if: :all_blank
end
```

```
class CompanyUser < ApplicationRecord
  
  
  belongs_to :user, inverse_of: :company_users
  belongs_to :company, inverse_of: :company_users
  validates :email, :uniqueness => { :scope => [:company_id]}

end	
```

I have a form a create/update a company in which you can also add company_users

when I submit it, with two same email for CompanyUser.email, here what rails receives :

> Processing by CompaniesController#create as HTML
>   Parameters: {"utf8"=>"✓", "authenticity_token"=>"xxx", "company"=>{"name"=>"hljkhlkj", "company_users_attributes"=>{"0"=>{"email"=>"SAMEEMAIL@example.com"}, "1"=>{"email"=>"SAMEEMAIL@example.com"}}}}

  
and here how rails deals with it

 

>   (0.3ms)  BEGIN
>   CompanyUser Exists? (0.3ms)  SELECT 1 AS one FROM "company_users" WHERE "company_users"."email" = $1 AND "company_users"."company_id" IS NULL LIMIT $2  [["email", "SAMEEMAIL@example.com"], ["LIMIT", 1]]
> 
>   CACHE CompanyUser Exists? (0.0ms)  SELECT 1 AS one FROM "company_users" WHERE "company_users"."email" = $1 AND "company_users"."company_id" IS NULL LIMIT $2  [["email", "SAMEEMAIL@example.com"], ["LIMIT", 1]]
>   Company Create (2.8ms)  INSERT INTO "companies" ("name", "created_at", "updated_at") VALUES ($1, $2, $3) RETURNING "id"  [["name", "hljkhlkj"], ["created_at", "2020-01-07 22:34:25.830443"], ["updated_at", "2020-01-07 22:34:25.830443"]]
>   CompanyUser Create (0.7ms)  INSERT INTO "company_users" ("user_id", "company_id", "email", "created_at", "updated_at") VALUES ($1, $2, $3, $4, $5, $6) RETURNING "id"  [["user_id", 308156], ["company_id", 1], ["email", "SAMEEMAIL@example.com"], ["created_at", "2020-01-07 22:34:25.842994"], ["updated_at", "2020-01-07 22:34:25.842994"]]
>   CompanyUser Create (0.6ms)  INSERT INTO "company_users" ("user_id", "company_id", "email", "accepted_at", "created_at", "updated_at") VALUES ($1, $2, $3, $4, $5, $6, $7) RETURNING "id"  [["user_id", 308156], ["company_id", 1], ["email", "SAMEEMAIL@example.com"], ["accepted_at", "2020-01-07 22:34:25.822034"], ["created_at", "2020-01-07 22:34:25.848704"], ["updated_at", "2020-01-07 22:34:25.848704"]]
>    (1.0ms)  COMMIT

Rails seems to check at the beginning ONLY if the email exists, so it creates 2 CompanyUser object with the same email and same company (even though validates :email, :uniqueness => { :scope => [:company_id]}),  whereas it should check after each insert and still respects the uniqueness validation on email

**Comment by louim** [comment]
Hey!

It seems to be the same issue described in https://github.com/rails/rails/issues/20676.
Rails 6 repro:
```ruby
# frozen_string_literal: true

require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  # Activate the gem you are reporting the issue against.
  gem "activerecord", "6.0.0"
  gem "sqlite3"
end

require "active_record"
require "minitest/autorun"
require "logger"

# This connection will do for database-independent bug reports.
ActiveRecord::Base.establish_connection(adapter: "sqlite3", database: ":memory:")
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :companies, force: true do |t|
    t.string :name
  end

  create_table :company_users, force: true do |t|
    t.integer :company_id
    t.string :email

    t.index [:email, :company_id], unique: true
  end
end

class Company < ActiveRecord::Base
  has_many :company_users, dependent: :destroy

  accepts_nested_attributes_for :company_users, allow_destroy: true, reject_if: :all_blank
end

class CompanyUser < ActiveRecord::Base
  belongs_to :company
  validates :email, uniqueness: { scope: [:company_id] }
end

class BugTest < Minitest::Test
  def test_association_stuff
    company = Company.new(name: "a name", company_users_attributes: { "0": { "email": "SAMEEMAIL@example.com" }, "1": { "email": "SAMEEMAIL@example.com" } })
    company.save!
  end
end
```

**Comment by Llambi** [comment]
```
ActiveRecord::Schema.define do
  create_table :companies, force: true do |t|
    t.string :name
  end

  create_table :company_users, force: true do |t|
    t.integer :company_id
    t.string :email

    t.index [:email, :company_id], unique: true
  end
end
```

Shouldn't you add the reference to the foreingkey? like: 

`add_foreign_key "company_users", "companies"`

**Comment by dmitry** [comment]
@Llambi it should work even without it.
