### ISSUE TITLE
ActionMailer - enable Email logging

### ISSUE THREAD

**Issue by FireFart** [rails/rails#38180]
It would be nice for ActionMailer to support logging of sent emails. Currently there is only a way with using callbacks which can be hard when using third party gems like devise.

I would propose to have this configurable in the `config.action_mailer.` section

**Comment by rafaelfranca** [comment]
It is already supported. See https://github.com/rails/rails/blob/master/actionmailer/lib/action_mailer/log_subscriber.rb#L20. You only need to set the Action Mailer logger to debug.
