### ISSUE TITLE
ActiveRecord::Persistence#increment! used to be recorded in ActiveModel::Dirty#previous_changes

### ISSUE THREAD

**Issue by bughit** [rails/rails#38192]
### Steps to reproduce
4.2
```rb
# Activate the gem you are reporting the issue against.
gem 'activerecord', '4.2.8'
require 'active_record'
require 'minitest/autorun'
require 'logger'

# Ensure backward compatibility with Minitest 4
Minitest::Test = MiniTest::Unit::TestCase unless defined?(Minitest::Test)

# This connection will do for database-independent bug reports.
ActiveRecord::Base.establish_connection(adapter: 'sqlite3', database: ':memory:')
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :posts do |t|
    t.integer :int1
  end
  
end

class Post < ActiveRecord::Base
  has_many :comments
end

class BugTest < Minitest::Test
  def test_association_stuff
    post = Post.create!(int1: 0)
    post.reload
    post.increment!(:int1)
    assert post.previous_changes.include?(:int1)
  end
end
```

6.0
```rb
# frozen_string_literal: true

require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"
  
  git_source(:github) { |repo| "https://github.com/#{repo}.git" }
  
  # Activate the gem you are reporting the issue against.
  gem "activerecord", "6.0.2.1"
  gem "sqlite3"
end

require "active_record"
require "minitest/autorun"
require "logger"

# This connection will do for database-independent bug reports.
ActiveRecord::Base.establish_connection(adapter: "sqlite3", database: ":memory:")
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :posts, force: true do |t|
    t.integer :int1
  end
  
end

class Post < ActiveRecord::Base

end


class BugTest < Minitest::Test
  def test_association_stuff
    post = Post.create!(int1: 0)
    post.reload
    post.increment!(:int1)
    assert post.previous_changes.include?(:int1)
  end
end
```
### Expected behavior
for increment! to be recorded in previous_chnages

### Actual behavior
incrememt! is not recorded

### System configuration
**Rails version**: 5.2.4.1, 6.0.2.1

**Ruby version**: 2.6.5

**Comment by joshmn** [comment]
Might be the offender? https://github.com/rails/rails/blob/dec4dca0dc6739f7e01943c9f72b0114d9a91f79/activerecord/lib/active_record/persistence.rb#L704-L710

(708 specifically)

4.2 just called `update_attribute`, https://github.com/rails/rails/blob/4-2-stable/activerecord/lib/active_record/persistence.rb#L321-L323

**Comment by bughit** [comment]
probably `clear_attribute_change(attribute) # eww 1`

**Comment by gmcgibbon** [comment]
`clear_attribute_change(attribute)` is used to clear the current `changes` hash, not the previous one.

We do this because we call `increment` which increments in memory via the attribute API. As the comments of this method point out, `increment!` is meant to bypass validations and callbacks and save the new value directly to the DB. Because the new value is already saved, we need to forget the initial change recorded by the attributes API.

Since we're opting to make this incrementing method invisible to the attributes API, I think we should leave it as-is. Thank you for reporting! 😄

**Comment by bughit** [comment]
>  Since we're opting to make this incrementing method invisible to the attributes API

increment! was initially saved by update_attribute. The change was done by #11410 to "Make AR#increment! AR#decrement! concurency safe"

There was no explicit goal to hide it from previous_change, so it's a breaking change introduced inadvertently. You can not say you "opted" to do this, as that can justify any breaking change, just point to the commit that accidentally introduced it and say, "it's clearly opting to make this change" The change thus becomes its own justification.
