### ISSUE TITLE
Warning: Using the last argument as keyword parameters is deprecated

### ISSUE THREAD

**Issue by wellington1993** [rails/rails#38202]
### Steps to reproduce
- Install latest Ruby 2.7 from Rbenv
- Try to use `rails s`
- Error on `activesupport-6.0.2.1`

### Expected behavior
No errors or deprecation messages. 

### Actual behavior
Warnings:
```
/home/wellington/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/activesupport-6.0.2.1/lib/active_support/option_merger.rb:24: warning: Using the last argument as keyword parameters is deprecated; maybe ** should be added to the call
/home/wellington/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/activesupport-6.0.2.1/lib/active_support/core_ext/class/attribute.rb:87: warning: The called method `class_attribute' is defined here
```

- `warning: Using the last argument as keyword parameters is deprecated; maybe ** should be added to the call` from `activesupport-6.0.2.1/lib/active_support/option_merger.rb:24`
- `warning: The called method class_attribute is defined here` from `activesupport-6.0.2.1/lib/active_support/core_ext/class/attribute.rb:87`

### System configuration
**Rails version**:
`Rails 6.0.2.1`

**Ruby version**:
`ruby 2.7.0p0 (2019-12-25 revision 647ee6f091) [x86_64-linux]`

### Other problems

```
/home/wellington/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/actionpack-6.0.2.1/lib/action_dispatch/middleware/stack.rb:37: warning: Using the last argument as keyword parameters is deprecated; maybe ** should be added to the call
/home/wellington/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/actionpack-6.0.2.1/lib/action_dispatch/middleware/static.rb:110: warning: The called method `initialize' is defined here
```

- `warning: Using the last argument as keyword parameters is deprecated; maybe ** should be added to the call` from `actionpack-6.0.2.1/lib/action_dispatch/middleware/stack.rb:37`
- `warning: The called method initialize is defined here` from `actionpack-6.0.2.1/lib/action_dispatch/middleware/static.rb:110`

Thanks!

**Comment by joshmn** [comment]
It's just a warning. It's on the radar of plenty and won't cause any side effects to your application.

**Comment by CurtisMorice** [comment]
follow this guide https://piechowski.io/post/last-arg-keyword-deprecated-ruby-2-7/
 and add ** to the def() in youractionpack-6.0.2.1/lib/action_dispatch/middleware/stack.rb:37:
where it is pointing. 
like this 
```
    def initialize(**args)
      @middlewares = []
      yield(self) if block_given?
    end
```
I added the extra * to the args and the error went away... Why? It explains in the url .. GL

**Comment by fguillen** [comment]
For the moment I am using this: 

     export RUBYOPT='-W:no-deprecated'

**Comment by martinstreicher** [comment]
Line to change is Line 70 in 6.0.2.2.

**Comment by rafaelfranca** [comment]
Upgrade to Rails 6.0.3 and it should be gone.

**Comment by jakehockey10** [comment]
I'm on Rails 6.0.3 and I'm still seeing it

**Comment by VitaliiLazebnyi** [comment]
Rails 6.0.3
`~/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/rails-controller-testing-1.0.4/lib/rails/controller/testing/integration.rb:13: warning: Using the last argument as keyword parameters is deprecated; maybe ** should be added to the call
`

**Comment by rafaelfranca** [comment]
But are those warnings inside Rails? Can you copy those warnings here so we can see it?

**Comment by nedenwalker** [comment]
@rafaelfranca The warnings we see with ruby 2.7.1 and rails 6.0.3 are similar to the ones shown in this issue: https://github.com/rails/rails/issues/39227

Basically all the deprecation warnings are displaying.

**Comment by RaviAsnani** [comment]
`.rvm/gems/ruby-2.7.0/gems/activesupport-6.0.3.1/lib/active_support/cache.rb:330: warning: Passing the keyword argument as the last hash parameter is deprecated`
and
`/Users/raviasnani/.rvm/gems/ruby-2.7.0/gems/activesupport-6.0.3.1/lib/active_support/cache.rb:710: warning: The called method `get_entry_value' is defined here`

**Comment by nathanhinchey** [comment]
I am still getting this deprecation warning, with sprockets 4.0.2, sprockets-rails 3,2,1, and rails 6.0.3.2

**Comment by brandondrew** [comment]
> But are those warnings inside Rails? Can you copy those warnings here so we can see it?

The warnings appear in the `rails console`, basically making it unusable.  (They don't only appear after entering a command, but rather just repeatedly appear every few moments.)

**Comment by HtetAungHlaingGIC** [comment]
how to solve Using the last argument as keyword parameters is deprecated; maybe ** should be added to the call this error
