### ISSUE TITLE
Rails migration can't run correctly my SQL function

### ISSUE THREAD

**Issue by boriscy** [rails/rails#38201]
### Steps to reproduce

Create a migration and add the following function that runs correctly in SQL console
```ruby
def up
    execute <<-SQL
CREATE OR REPLACE FUNCTION cast_to_int(val TEXT)
RETURNS integer AS $BODY$
DECLARE d integer;
BEGIN
  IF val ~ '^\d+$' THEN
    d := (val)::INT;
  ELSE
    d := 0;
  END IF;

  RETURN d;
END;
$BODY$ LANGUAGE plpgsql;
    SQL
  end

  def down
    execute "DROP FUNCTION IF EXISTS cast_to_int;"
  end
```

### Expected behavior

Whe run this query it should convert to integer
```sql
select cast_to_int('2');
-- 2
select cast_to_int('a');
-- 0
```

### Actual behavior
Always return 0
```sql
select cast_to_int('2');
-- 0
select cast_to_int('a');
-- 0
```

### System configuration
**Rails version**: 6.0.1
**Ruby version**: 2.6.5

**Comment by eikes** [comment]
This is not a rails issue.

You are constructing the SQL heredoc string incorrectly. The ```\d``` becomes a simple ```d``` when you look at the function this migration creates. From the [documentation](https://ruby-doc.org/core-2.6.5/doc/syntax/literals_rdoc.html):

> A heredoc allows interpolation and escaped characters. You may disable interpolation and escaping by surrounding the opening identifier with single quotes.

So you need to use the ```execute <<-'SQL'``` notation:

```ruby
def up
    execute <<-'SQL'
CREATE OR REPLACE FUNCTION cast_to_int(val TEXT)
RETURNS integer AS $BODY$
DECLARE d integer;
BEGIN
  IF val ~ '^\d+$' THEN
    d := (val)::INT;
  ELSE
    d := 0;
  END IF;

  RETURN d;
END;
$BODY$ LANGUAGE plpgsql;
    SQL
  end

  def down
    execute "DROP FUNCTION IF EXISTS cast_to_int;"
  end
```

Alternatively you could double escape the ```\d``` as ```\\d```.

**Comment by boriscy** [comment]
Thanks for your response I will make changes.
