### ISSUE TITLE
ActiveStorage broken with rack 2.1.0

### ISSUE THREAD

**Issue by thedanbob** [rails/rails#38214]
### Steps to reproduce
Update to rack 2.1.0

### Expected behavior
No change

### Actual behavior
ActiveStorage crashes when trying to serve a file

### System configuration
**Rails version**: 5.2.4.1

**Ruby version**: 2.3.3

Rack::File (now Rack::Files) no longer accepts nil as a first parameter per this commit: https://github.com/rack/rack/commit/8f85307711ca5e7a4729641fda1552890ffa129a. `File.expand_path` throws a TypeError.

This breaks the ActiveStorage file server: https://github.com/rails/rails/blob/master/activestorage/app/controllers/concerns/active_storage/file_server.rb#L6

**Comment by rafaelfranca** [comment]
This is an issue on rack. Can you open an issue there? I'll keep this one so we track it.
