### ISSUE TITLE
log_error fails when exception.annotated_source_code is nil

### ISSUE THREAD

**Issue by polley1** [rails/rails#38213]
### Steps to reproduce

Not sure how to create a cut down test case for this yet but iaction_dispatch/middleware/debug_exceptions.rb in the method log_error, message.concat(exception.annotated_source_code) will fail if exception.annotated_source_code is nil.

Changing the line to:
message.concat(exception.annotated_source_code || []) if exception.respond_to?(:annotated_source_code)
fixes the issue.

### Expected behavior

ActionView::Template::Error (undefined method `start_with?' for /\.(?:svg|eot|woff|ttf)$/:Regexp):
  
sprockets (4.0.0) lib/sprockets/uri_utils.rb:78:in `valid_asset_uri?'
sprockets (4.0.0) lib/sprockets/resolve.rb:27:in `resolve'
sprockets (4.0.0) lib/sprockets/base.rb:79:in `find_asset'
sprockets (4.0.0) lib/sprockets/base.rb:88:in `find_all_linked_assets'
sprockets (4.0.0) lib/sprockets/manifest.rb:125:in `block (2 levels) in find'
concurrent-ruby (1.1.5) lib/concurrent/executor/safe_task_executor.rb:24:in `block in execute'
concurrent-ruby (1.1.5) lib/concurrent/synchronization/mutex_lockable_object.rb:41:in `block in synchronize'
concurrent-ruby (1.1.5) lib/concurrent/synchronization/mutex_lockable_object.rb:41:in `synchronize'
concurrent-ruby (1.1.5) lib/concurrent/synchronization/mutex_lockable_object.rb:41:in `synchronize'
concurrent-ruby (1.1.5) lib/concurrent/executor/safe_task_executor.rb:19:in `execute'
concurrent-ruby (1.1.5) lib/concurrent/promise.rb:563:in `block in realize'
concurrent-ruby (1.1.5) lib/concurrent/executor/ruby_thread_pool_executor.rb:348:in `run_task'
concurrent-ruby (1.1.5) lib/concurrent/executor/ruby_thread_pool_executor.rb:337:in `block (3 levels) in create_worker'
concurrent-ruby (1.1.5) lib/concurrent/executor/ruby_thread_pool_executor.rb:320:in `loop'
concurrent-ruby (1.1.5) lib/concurrent/executor/ruby_thread_pool_executor.rb:320:in `block (2 levels) in create_worker'
concurrent-ruby (1.1.5) lib/concurrent/executor/ruby_thread_pool_executor.rb:319:in `catch'
concurrent-ruby (1.1.5) lib/concurrent/executor/ruby_thread_pool_executor.rb:319:in `block in create_worker'

### Actual behavior
No error message is generated for the log.

### System configuration
**Rails version**:
6.0.1

**Ruby version**:
ruby 2.6.3p62

**Comment by rafaelfranca** [comment]
This was fixed by e2cfa05218fd8e5ca273e2b0331265fa4cf6d6c2
