### ISSUE TITLE
How to create fake request with controller object?

### ISSUE THREAD

**Issue by BKDruby** [rails/rails#38228]
I need to use render_to_string method outside the controller.
So I create controller instance like:

>       controller = class_name.constantize.new
>       controller.params = params
>       controller.action_name = 'index'
>       controller.create_global_current_user user
>       index_render_options = controller.send('index_render_options')
>       controller.send('render_to_string', index_render_options)

But it fails because request object inside is nil. Could you help me with it? how to create fake request for controller object?

**Comment by rafaelfranca** [comment]
Please use StackOverflow for questions/help, where a wider community will be able to help you. We reserve the issues tracker for issues only.
