### ISSUE TITLE
Rails 6 upgrade after get JSON::ParserError Mime::Type::InvalidMimeType

### ISSUE THREAD

**Issue by vilusa** [rails/rails#38224]
### Steps to reproduce
Rails 6 upgrade after get JSON parse error at Rspec Spec tests. But rails 5 version spec test successfully run

### Actual behavior
JSON::ParserError:
        767: unexpected token at 'Mime::Type::InvalidMimeType

<img width="421" alt="Screen Shot 2020-01-13 at 11 47 37 AM" src="https://user-images.githubusercontent.com/8127141/72242438-8b192b00-35fa-11ea-959d-10678ce47311.png">

### System configuration
**Rails version**:
6.0.2.1
**Ruby version**:
2.6.5

**Comment by pavanshriffle007** [comment]
please help us for same issue
