### ISSUE TITLE
Inconsistent test failures.

### ISSUE THREAD

**Issue by guycall** [rails/rails#38221]
Are other people random different test failures?

I triggered multiple builds by just making comment changes and got lots of varying failures:

https://buildkite.com/rails/rails/builds/66400
https://buildkite.com/rails/rails/builds/66396
https://buildkite.com/rails/rails/builds/66389
https://buildkite.com/rails/rails/builds/66380
https://buildkite.com/rails/rails/builds/66326

**Comment by kamipo** [comment]
Fixed by #38216.
