### ISSUE TITLE
Rails 6 : config.require_master_key=true doesn't raise an error if key does not exist

### ISSUE THREAD

**Issue by rally25rs** [rails/rails#38234]
### Steps to reproduce

config/environments/production.rb
```
config.require_master_key = true
```

try to get a config value
```
$ RAILS_ENV=production bundle exec rails console

Loading production environment (Rails 6.0.1)

irb(main):001:0> Rails.configuration.require_master_key
=> true

irb(main):002:0> Rails.application.credentials
=> #<ActiveSupport::EncryptedConfiguration:0x000055c73184b158 @key_path=#<Pathname:/usr/src/app/config/master.key>, @content_path=#<Pathname:/usr/src/app/config/credentials.yml.enc>, @env_key="RAILS_MASTER_KEY", @raise_if_missing_key=false, @config={}, @options={}>

irb(main):003:0> Rails.application.credentials.dig(:user)
=> nil
```

Note that `@raise_if_missing_key=false` but it should probably be `true` because `config.require_master_key = true`

ensure no master key exists
```
irb(main):003:0> ENV["RAILS_MASTER_KEY"]
=> nil
```
```
$ cat /usr/src/app/config/master.key
cat: /usr/src/app/config/master.key: No such file or directory
```

### Expected behavior
Because `config.require_master_key = true` I would expect attempts to access `rails.application.credentials` to raise an error.

### Actual behavior
No error is raised and `rails.application.credentials.dig(...)` returns `nil`

### System configuration
**Rails version**: 6.0.1

**Ruby version**: 2.6.1-p33

-----

A bit of debugging info:

https://github.com/rails/rails/blob/c0d91a4f9da10094ccdb80e34d1be42ce1016c9a/railties/lib/rails/application.rb#L468

is where the `ActiveSupport::EncryptedConfiguration` is created.

If I set a breakpoint in that file and in `config/environments/production.rb`, the application railtie is hit first, before env specific configuration is loaded. That causes `config.require_master_key` to still be `false` at the time that the `ActiveSupport::EncryptedConfiguration` object is created.

**Comment by joshmn** [comment]
What does `Rails.app.credentials.key` return?

**Comment by rally25rs** [comment]
@joshmn it is `nil`

```
irb(main):002:0> Rails.application.credentials.key
=> nil
```

**Comment by jonathanhefner** [comment]
I cannot reproduce this using either Rails 6.0.1 or 6.0.2.  Could you upload a minimal app that reproduces the issue?

**Comment by yao0204** [comment]
Hi, 
I have the same problem. I set config.require_master_key = true but when I do  Rails.application.credentials I have @raise_if_missing_key=false 
Is this normal?

**Comment by rafaelivan** [comment]
This was happening to my app (Rails 6.0.3.2). Removing all the references to `Rails.application.credentials` from `application.rb` made `config.require_master_key = true` (set on `production.rb`) work as expected.

Maybe referencing `Rails.application.credentials` from the `application.rb` creates the credentials object before the config on `production.rb` is loaded.

**Comment by toncid** [comment]
> Maybe referencing Rails.application.credentials from the application.rb creates the credentials object before the config on production.rb is loaded.

Yes, confirmed. This seems to be the repro case.
