### ISSUE TITLE
puts from EM within a thread seem to be missing linefeed when run in ruby 2.7.0 console

### ISSUE THREAD

**Issue by jmaino** [rails/rails#38233]
Dup'ed from issue report #905 at eventmachine github.

This is strange, and I'm hoping I explain it sufficiently - but I've upgraded to ruby 2.7.0 and I'm seeing missing linefeeds in puts outputs from EM that's within a thread.

I did not see this problem when running in ruby 2.6.5's console output - it seems to be related to my move to 2.7.0.

I've simplified this to reproduce this as folllows. If I run the following EM without being inside of a thread, then I get an OK output - example:

irb(main):042:1* EventMachine.run do
irb(main):043:1* EM.add_periodic_timer(1) { puts "Tick ..." }
irb(main):044:1*
irb(main):045:2* EM.add_timer(3) do
irb(main):046:2* puts "I waited 3 seconds"
irb(main):047:2* EM.stop_event_loop
irb(main):048:1* end
irb(main):049:0> end
Tick ...
Tick ...
I waited 3 seconds
=> nil

Note all of the strings that are output from the puts commands within the EM loop are fully left-justified in the output.
But if I wrap this in a thread, the output lines appear to be missing the linefeed, but do have the CR - such that the successive puts strings are not left justified as they sequence, and build from the X-offset that ended the previous puts string output.

irb(main):001:1* Thread.new do
irb(main):002:2* EventMachine.run do
irb(main):003:2* EM.add_periodic_timer(1) { puts "Tick ..." }
irb(main):004:2*
irb(main):005:3* EM.add_timer(3) do
irb(main):006:3* puts "I waited 3 seconds"
irb(main):007:3* EM.stop_event_loop
irb(main):008:2* end
irb(main):009:1* end
irb(main):010:0> end
=> #<Thread:0x000055cf1a8482c8 (irb):1 run>
irb(main):011:0> Tick ...
_________________________Tick ...
_______________________________ I waited 3 seconds

Is there something that's known to have changed that is causing this?
Can others reproduce this as well?
I can't tell is this is EM's or ruby's - so any help would really be appreciated.

I only see this from puts statements within the EM loop within a Thread.
If the wrapping Thread is not there, there's no issue.
If there's just a sequence of puts in a Thread and no EM loop, there's no issue.

It seems as if there's something about the combo of a Thread wrapping an EM loop that's making the underlying puts misbehave.

Thanks,
-Jim

**Comment by eileencodes** [comment]
This doesn't sound like a Rails issue, you should probably report this to EventMachine and/or Ruby. That Event Machine issue is from 2011 so it's probably no longer relevant to what you're experiencing. If you can reproduce the issue in Rails without Event Machine please let us know. Thanks!

**Comment by jmaino** [comment]
Thanks Eileen - the issue from EM was actually only filed (by me) 2-day ago - but I will follow-up w/ Ruby directly.
Thanks,

**Comment by eileencodes** [comment]
This issue that you linked is from 2011? https://github.com/rails/rails/issues/905

**Comment by jmaino** [comment]
Sorry for the confusion - but this was eventmachine's #905, not rails - sorry if that was unclear in my initial report text
