### ISSUE TITLE
Using .scoping from a descendant class doesn't apply the STI constraint

### ISSUE THREAD

**Issue by stem** [rails/rails#38248]
### Steps to reproduce
Setup STI with 2 classes and use `scoping` from a descendant with the block calling the parent class directly:
```
# frozen_string_literal: true

require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  # Activate the gem you are reporting the issue against.
  gem "activerecord"
  gem "sqlite3"
end

require "active_record"
require "minitest/autorun"
require "logger"

# This connection will do for database-independent bug reports.
ActiveRecord::Base.establish_connection(adapter: "sqlite3", database: ":memory:")
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :shops, force: true do |t|
    t.string :type
    t.string :name
  end
end

class Shop < ActiveRecord::Base
  scope :deliverable, -> { all }
end

class Market < Shop
end

class BugTest < Minitest::Test
  def test_scoping_sti
    shop = Shop.create!(name: 'Test')

    assert_equal 1, Shop.deliverable.size
    assert_equal 1, Shop.where(name: 'Test').scoping { Shop.deliverable.size }
    assert_equal 0, Shop.where(name: 'Other test').scoping { Shop.deliverable.size }

    assert_equal 0, Market.deliverable.size
    assert_equal 0, Shop.where(type: 'Market').scoping { Shop.deliverable.size }
    assert_equal 0, Market.all.scoping { Shop.deliverable.size }
  end
end
```

As you can see, I know I can do `Shop.where(type: 'Market').scoping { Shop.all.size }` but I do find it a lot more cryptic than what I'm trying to do.
I've managed to have a passing test using the following monkey patch, but I have not idea of what it might breaks 😞 
```
class ActiveRecord::Base
  class << self
    private

    def relation
      relation = ActiveRecord::Relation.create(self.base_class)

      if finder_needs_type_condition? && !ignore_default_scope?
        relation.where!(type_condition)
        relation.create_with!(inheritance_column.to_s => sti_name)
      else
        relation
      end
    end
  end
end
```

### Expected behaviour
I assume that the scoped block will be executed within the subclass constraint, even if we query the base class directly.

### Actual behaviour
The subclass scope is ignored and the resulting records contain all types of `Shop` instead of only `Market` ones.

### System configuration
**Rails version**: 5.2.4.1, but I've reproduced it with 5.1, 5.2, 6.0

**Ruby version**: 2.6.5p114

**Comment by DevelopMan** [comment]
Did anybody solve this issue? We have the same with
Rails 5.2.4.4
ruby 2.6.6
And right now I see only one way - move all scopes to methods, however, this is not a good solution.
