### ISSUE TITLE
Rails test command on Windows runs all tests in a file instead of just the test specified by a line number

### ISSUE THREAD

**Issue by heynan0** [rails/rails#38243]
### Steps to reproduce

Open cmd and create a new Rails app:

```
rails new test-app
```

Change directory to the app:

```
cd test-app
```

Create a new test file at `test\sample_test.rb`:

```
require "test_helper"

class SampleTest < ActiveSupport::TestCase
  test "this is the first one" do
    assert true
  end

  test "this is the second one (will fail)" do
    assert false
  end

  test "this is the third one" do
    assert_not false
  end

  test "this is the fourth one (will fail)" do
    assert_not true
  end
end
```

Go back to cmd and run the test at a specific line number:

```
rails test test\sample_test.rb:4
```

### Expected behavior

According to [the Rails Guide](https://guides.rubyonrails.org/testing.html), when you run the rails test command on a file, specifying the line number, only the test at that line number should run.

### Actual behavior

When you run the rails test command on a file, specifying the line number, all the tests in the file are run.

In the example presented, the following output was generated:

```
Run options: --seed 25537

# Running:

F

Failure:
SampleTest#test_this_is_the_second_one_(will_fail) [C:/Users/myusername/rails/test-app/test/sample_test.rb:9]:
Expected false to be truthy.


rails test test/sample_test.rb:8

.F

Failure:
SampleTest#test_this_is_the_fourth_one_(will_fail) [C:/Users/myusername/rails/test-app/test/sample_test.rb:17]:
Expected true to be nil or false


rails test test/sample_test.rb:16

.

Finished in 0.064904s, 61.6299 runs/s, 61.6299 assertions/s.
4 runs, 4 assertions, 2 failures, 0 errors, 0 skips
```

You can see that it did not run only the test at line 4. It went on to run all the tests.

If you change the line number to 12, it does the same thing and includes preceding tests as well as the ones afterward.

### System configuration

**Operating System**: Windows 10 Enterprise Version 1909
**Command Line**: cmd.exe
**Ruby Version**: `ruby 2.6.5p114 (2019-10-01 revision 67812) [x64-mingw32]`
**Rails Version**: Rails 6.0.2.1

**Comment by jonathanhefner** [comment]
If you change your command to `rails test test/sample_test.rb:4` (with a **forward** slash), does it work as expected?

Also, if you add another test file and run `rails test test\sample_test.rb` (with a **back** slash), do both test files get executed anyway?

**Comment by heynan0** [comment]
@jonathanhefner,

1) It works with a forward slash.

2) Yes, if I add another test file and use the command with backslash, both test files will be run.

**Comment by jonathanhefner** [comment]
@heynan0 Thank you for verifying!

The cause of this issue is that the test runner only considers an argument to be a file path [if it contains a forward slash](https://github.com/rails/rails/blob/ab18f60841c11427948be444ee5ff0008fd4c3fb/railties/lib/rails/test_unit/runner.rb#L83-L85).  The fix would be to also recognize back slashes.  However, this might open up a can of worms.  Ruby (and Windows) can typically handle either slash without problems, but I'm not sure if there are other parts of Rails that expect forward slashes only when processing paths.

@kaspth  What do you think about this?  Should I create a PR to accept Windows-style paths in the test runner?

**Comment by kaspth** [comment]
Feels like a worthy shot to me 👍
