### ISSUE TITLE
No migration path for calling `.all` in an `after_create` callback

### ISSUE THREAD

**Issue by sgrif** [rails/rails#38241]
### Steps to reproduce
<details>
    <summary>Repro script</summary>

```
# frozen_string_literal: true

require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  # Activate the gem you are reporting the issue against.
  gem "activerecord", "6.0.0"
  gem "sqlite3"
end

require "active_record"
require "minitest/autorun"
require "logger"

# This connection will do for database-independent bug reports.
ActiveRecord::Base.establish_connection(adapter: "sqlite3", database: ":memory:")
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :posts, force: true do |t|
    t.text :title
    t.text :content
  end
end

class Post < ActiveRecord::Base
  after_create :call_all

  def call_all
    self.class.all
  end
end

class BugTest < Minitest::Test
  def test_association_stuff
    ActiveSupport::Deprecation.behavior = :raise
    Post.create_with(content: :foo).find_or_create_by!(title: :bar)
  end
end
```
</details>

This is especially problematic for gems, which may want to respect `default_scope`. There doesn't appear to be a way to do so. Even if there was, the deprecation appears to be overly aggressive, and triggers on harmless methods like `create_with`.

### Expected behavior

There is a migration path for apps using `.all` or any other relation method in an `after_create` callback, that respects default scopes, or the deprecation warning only triggers when the inherited scope would actually affect the method being called.

### Actual behavior

The deprecation is raised an there's no clear path forward

### System configuration
**Rails version**: 6.0

**Ruby version**: 2.6

**Comment by kamipo** [comment]
In this case, the `self.class.all` should be replaced with `self.class.default_scoped` to prepare for Rails 6.1 (#37727, https://github.com/robinbortlik/validates_overlap/pull/52).

```diff
diff --git a/activerecord/foo.rb b/activerecord/foo.rb
index 0869473f4c..1f872d12bf 100644
--- a/activerecord/foo.rb
+++ b/activerecord/foo.rb
@@ -39,7 +39,7 @@ class Post < ActiveRecord::Base
   after_create :call_all
 
   def call_all
-    self.class.all
+    self.class.default_scoped
   end
 end
 
```

Even if `create_with`, leaking scope would be accidental (unintentional), so it has a side-effect whether user is aware or not if user will use `all.find_or_create_by(...)` in create callbacks.

I think that this deprecation is similar with #25337, to fix frequently reported scoping bugs. I admit finding a way to maintain default scopes was not clear before #37727.

If users still think hard to find migration path on their code, I can help to find a way for the migration.

**Comment by sgrif** [comment]
`default_scoped` seems fine, but that method is not currently part of the public API. Should it be documented and made public?
