### ISSUE TITLE
Has many :through association is cached improperly

### ISSUE THREAD

**Issue by jhottenstein** [rails/rails#38251]
### Steps to reproduce
https://gist.github.com/jhottenstein/b87fbd690b3b102166c4d9f9461f0dd0

Given
```
class Author < ActiveRecord::Base
  has_many :books, inverse_of: :author
  has_many :publishers, through: :books
end

class Book < ActiveRecord::Base
  belongs_to :author
  belongs_to :publisher
end

class Publisher < ActiveRecord::Base
  has_many :books, inverse_of: :publisher
end

author = Author.new
author.books.build(publisher: Publisher.new)
author.publishers.to_a
author.save!
author.publishers.size => should be 1
```

### Expected behavior
After adding records to a has_many relationship, loading a has_many :through relationship and saving the parent record, the associated has_many :through relationship returns the added records.

### Actual behavior
After adding records to a has_many relationship, loading a has_many :through relationship and saving the parent record, the associated has_many :through relationship does not return the added records.

### System configuration
**Rails version**:
5.1 through master
**Ruby version**:
2.6.5

**Comment by joshmn** [comment]
I believe that's expected behavior: You're calling `size` on `author` as it was originally queried and cached; calling `author.reload`  after `author.save!` will give you the result you're looking for.

**Comment by jhottenstein** [comment]
Thanks for the quick response!

`reload` (and `reset`) certainly does fix this issue.  The confusing part about this (and why I opened a bug) is that the behavior is different for the converse case (passing test in [gist](https://gist.github.com/jhottenstein/b87fbd690b3b102166c4d9f9461f0dd0)).  

Loading the has_many relationship and saving the parent record makes the association correct in memory and calling size will return the correct value without calling reload.

The caching docs simply say:
> But what if you want to reload the cache, because data might have been changed by some other part of the application?

In both cases, it seems like I shouldn't have to call reload because I'm only modifying the current record in memory.
