### ISSUE TITLE
Performance degradation for `#first` when nested relation is preloaded

### ISSUE THREAD

**Issue by lordhx** [rails/rails#38252]
During the upgrade from 5.07 to 5.1.7 we've noticed the performance degradation in one of our jobs.

### Steps to reproduce
<details>
<summary>script to reproduce</summary>

```ruby
require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  # Activate the gem you are reporting the issue against.
  gem 'activerecord', '5.1.7'
  gem "sqlite3"
end

require "active_record"
require "logger"

# This connection will do for database-independent bug reports.
ActiveRecord::Base.establish_connection(adapter: "sqlite3", database: ":memory:")
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :posts, force: true do |t|
  end

  create_table :comments, force: true do |t|
    t.integer :post_id
  end

  create_table :likes, force: true do |t|
    t.integer :comment_id
  end

end

class Post < ActiveRecord::Base
  has_many :comments
end

class Comment < ActiveRecord::Base
  belongs_to :post
  has_many :likes
end

class Like < ActiveRecord::Base
  belongs_to :post
end

10.times { Post.create! }
30.times { |i| Comment.create!(post_id: 1 + i % 10) }
150.times { |i |Like.create!(comment_id: 1 + i % 30) }

post = Post.includes(comments: :likes).last

result = Benchmark.measure do
  100.times { post.comments.each { |c| c.likes.first.id } }
end

puts result

result = Benchmark.measure do
  100.times { post.comments.each { |c| c.likes.to_a.first.id } }
end

puts result
```

Results:
```
.first       0.023444   0.000693   0.024137 (  0.024844)
.to_a.first  0.000604   0.000005   0.000609 (  0.000607)
```
</details>

Given 3 models: Product, Variant and OptionValue. Product has_many Variants, and Variant has many OptionValues.
```
product = Product.includes(variants: :option_values).find_by!(catalog_number: 'G640')

Benchmark.benchmark do
  100.times { product.variants.each { |v| v.option_values.first.name } }
end
```
https://github.com/sdtechdev/rails-5.1-performance-test - you can also use this repo to reproduce the issue

### Actual behavior
```
Rails 5.0.7: 0.248867000000000 | 0.00147900000000023 | 0.0 | 0.0 | 0.25183700001798
Rails 5.1.7: 8.444056000000003 | 0.07617300000000027 | 0.0 | 0.0 | 8.66250299999956
```

### Expected behavior
Performance should be similar

### System configuration
**Rails version**: 5.17 
**Ruby version**: 2.6.0

### Details
Several methods including `#first` were removed in this commit https://github.com/rails/rails/commit/592e6b7e894e0fff07ab8233fce4bf77968ee8b6 and implementation has been changed and uses methods from `ActiveRecord::Relation`.

Degradation is caused by `find_nth`, however `find_nth_with_limit(index, limit)` works fast as Rails 5.0.7 https://github.com/rails/rails/blob/663206d20aec374a28a24bb43bc7b1233042ed9b/activerecord/lib/active_record/relation/finder_methods.rb#L520
```
find_nth            | 8.796847 | 0.1429990000000001 | 0.0 | 0.0 | 9.1316720000468
find_nth_with_limit | 0.272821 | 0.0022189999999997 | 0.0 | 0.0 | 0.2769989999942
```

here is the call sequence
`#find_nth` -> `#offset_index` -> `#offset_value` -> `#scope`
https://github.com/rails/rails/blob/663206d20aec374a28a24bb43bc7b1233042ed9b/activerecord/lib/active_record/associations/association.rb#L85
Here we come to the method that consumes a lot of time because it merges two scopes and even builds scopes from scratch

Worth to mention that issue still exists in Rails 6.0 and `.to_a.first` works as fast as Rails 5.0.7.
```
.first 6.0 | 4.07416199999999 | 0.103387 | 0.0 | 0.0 | 4.485593999968842
to_a.first | 0.16330200000000 | 0.001011 | 0.0 | 0.0 | 0.16510099999140948
```

**Comment by fabriziobertoglio1987** [comment]
[38313][1]

[1]: https://github.com/rails/rails/issues/38313#issuecomment-586697352
