### ISSUE TITLE
Rails silently fails save or update of new field after migration in production

### ISSUE THREAD

**Issue by tinco** [rails/rails#38265]
### Steps to reproduce

  1. Have your app in production
  2. Create a migration that adds a field but don't run it yet
  3. Create a controller action that saves a value to the new field (possibly using `update!`)
  4. Deploy the new controller action to production
  5. Run the migration
  6. Hit the controller

### Expected behavior
The new field should be written to, in the `DEBUG` log there should be an update statement that updates the field in the database.

### Actual behavior
There is an update statement sent to the database, but it does not have the new field in it. This behavior only happens in production, and also not on the terminal. So it seems to be diffing the update statement to some sort of cache of the database columns. Restarting the rails app fixes the issue.

### System configuration
**Rails version**: 5.2.3

**Ruby version**: 2.6.3

I'm mostly submitting this issue to document the behavior, I've ran into this a couple of times now and it's a little bit hard to debug, especially for novices. It's a symptom of us not deploying correctly, obviously it would be better to first run the migration and only then deploy the new version of the app.

**Comment by joshmn** [comment]
What app server are you using, and in what configuration?

**Comment by tinco** [comment]
Hi @joshmn, it's in Passenger, in a Docker container on Kubernetes. The database I'm using is a standard Postgresql installation with the standard driver, I'd have to look up the version number if that's relevant.
