### ISSUE TITLE
Recommended way to change autoload paths

### ISSUE THREAD

**Issue by janko** [rails/rails#38264]
I know usage questions are for StackOverflow or the google group, but I believe this might be a bug in the documentation.

I'm trying to add `lib/` directory to autoload paths in my Rails 6.0 app. Reading [Autoloading and Reloading Constants](https://guides.rubyonrails.org/autoloading_and_reloading_constants.html#autoload-paths), I see the following statements:

> You do not configure Zeitwerk manually in a Rails application. Rather, you configure the application using the portable configuration points explained in this guide, and Rails translates that to Zeitwerk on your behalf.

> The array of autoload paths can be extended by mutating `config.autoload_paths`, in `config/application.rb`, but nowadays this is **discouraged**.

> Please, do not mutate `ActiveSupport::Dependencies.autoload_paths`, the public interface to change autoload paths is `config.autoload_paths`.

So, to me the documentation discourages changing Zeitwerk, `config.autoload_paths` and `ActiveSupport::Dependencies.autoload_paths`, but it doesn't suggest what we *should* use. I believe `config.autoload_paths` is meant to be used, as this was the API pre-Zeitwerk, but I'm wondering why it's discouraged.

**Comment by rafaelfranca** [comment]
Because autoload_paths are not eager loaded in production environment which means that files will be loaded after the server is started and you may have deadlock problems. You should be using `eagear_load_paths` but `lib` should not be inside `eager_load_paths` since you may have files there that should not be loaded in production.
