### ISSUE TITLE
When constructed from a date, ActiveSupport's DateAndTime::Calculations#all_* ranges exclude time values that should match.

### ISSUE THREAD

**Issue by inopinatus** [rails/rails#38282]
### Expected behavior

The ranges derived from a date by `DateAndTime::Calculations#all_*` methods, should cover all time values on any date in the ranges returned.

### Actual behavior

The generated range silently fails to match times within the final day of that range, when `#cover?` is called with a time or time-like parameter, or when the range is supplied as the value in a hash condition to `where` on a datetime attribute.

### Steps to reproduce

Sample case at https://gist.github.com/inopinatus/8d2ba72a7aa825f95b263cfa2c9f6910 

### Discussion

This boundary glitch is fundamentally a type issue and occurs because, for example, `DateAndTime::Calculations#all_year` is defined as `beginning_of_year..end_of_year`.

For dates, that's pronounced "from first date of the year, to the last date of the year", which silently and unfortunately becomes "from midnight at the start of the year, to **midnight at the start of the last day of the year**" when compared with a time value.

### Possible alternatives

For the year (and similarly for any other duration), there's

1. `beginning_of_year...(beginning_of_year.next_year)`. Note the use of `...`. This leads to correct results from `#cover?` and arguably correct inequalities from the predicate builder, assuming you work in UTC.

2. `(beginning_of_year.beginning_of_day)..(end_of_year.end_of_day)` which also leads to correct results from `#cover?`; and the `where` predicate respects current time zone. With the downside that it's a Time range from a Date object which may be the Totally Wrong Thing in other contexts.

3. Throw an ArgumentError because this whole problem was a type blunder and just shouldn't be allowed at all. I don't agree with this as a response, but it's one some folks might reach for.

(1) is using a half-open interval*, and those are the correct means to subdivide data distributed over a continuous quantity, since this avoids both missing any records, and inadvertent double-counting. It's the approach I'll take in my own PR for this issue, and c.f. Edgar Dijkstra's note on range specification, _[Why numbering should start at zero](https://www.cs.utexas.edu/users/EWD/transcriptions/EWD08xx/EWD831.html)_.

I also think there's space for an upgrade to the handling of date ranges as `where` values when the attribute column is a datetime, perhaps by converting their bounds to time values appropriately. Not sure if that's a separate PR or part of the same resolution.

### System configuration

**Rails version**: master  
**Ruby version**: 2.7.0

<sub>\* beware of this analogy in general: the semantics & taxonomy of Ruby's ranges, even for numerics, aren't perfectly bijective to those of intervals. it's correct here though, I think.</sub>

**Comment by fig** [comment]
+1 for option(1).  Can't see any drawbacks.

**Comment by zrzka** [comment]
* Ruby 3.0.1
* Rails 6.1.3.2

Experienced this yesterday and was scratching my head for a while.

* `where(some_at: Date.new(2020).all_year)` - 2020-12-31 excluded
* `where(some_at: DateTime.new(2020).all_year)` - 2020-12-31 included

The fix was easy, but it wasn't immediately obvious to me. I read `all_year` and expected the whole year.

**Comment by zzak** [comment]
@zrzka Thanks for sharing your solution! We would prefer to discuss application changes in [the forum](https://discuss.rubyonrails.org/) where more people are able to follow along.

I realize you probably got here from Google, but just FYI.
