### ISSUE TITLE
Unable to rescue_from ActionDispatch::Http::Parameters::ParseError

### ISSUE THREAD

**Issue by jeffblake** [rails/rails#38285]
### Steps to reproduce

1. `rails new bugreport`
2. `rails g controller home`
3. Add `rescue_from` in https://github.com/jeffblake/paramsparserbug/blob/master/app/controllers/home_controller.rb
4. See test case: https://github.com/jeffblake/paramsparserbug/blob/master/test/controllers/home_controller_test.rb

Bug repo here: https://github.com/jeffblake/paramsparserbug

### Expected behavior

According to this pull request, https://github.com/rails/rails/pull/34341
rescuing from `ActionDispatch::Http::Parameters::ParseError` should be possible in the controller.

### Actual behavior
`ActionDispatch::Http::Parameters::ParseError` is not caught by the `rescue_from` in the controller.

### System configuration
**Rails version**: latest 6.0.2.1

**Ruby version**: 2.6.5

**Comment by freaz** [comment]
@jeffblake there is an existing workaround: https://github.com/rails/rails/issues/34244#issuecomment-433365579

**Comment by mikekreeki** [comment]
I came up with another (similar, yet maybe more elegant) workaround. Since the problem seems to be originating from `ParamsWrapper` being included into `ActionController::Base` after `Rescue`, one might include another `Rescue` after `ParamsWrapper` to catch it's errors like this `ActionController::Base.include(ActionController::Rescue.dup)` (to be placed in an initializer).

**Comment by jonathanhefner** [comment]
When running `rails test` for the reproduction app, I can confirm seeing:

```
Error:
HomeControllerTest#test_invalid_json_returns_bad_request:
ActionDispatch::Http::Parameters::ParseError: 767: unexpected token at '{'
    test/controllers/home_controller_test.rb:6:in `block in <class:HomeControllerTest>'
```

However, I'm wondering if this may be a configuration issue.  Rails still has a [test for rescuing `ParseError`](https://github.com/rails/rails/blob/v6.0.2.2/actionpack/test/controller/rescue_test.rb#L298-L304) which passes.  Also, to make sure there was no difference between `ActionController::TestCase` and `ActionDispatch::IntegrationTest`, I wrote an [additional test](https://github.com/jonathanhefner/rails/commit/2bb652921fe41d7a06fd054b48fd79201ffbc57c) in an experimental branch, and it passes as well.

**Comment by jonathanhefner** [comment]
> However, I'm wondering if this may be a configuration issue.

Indeed, if you add `Rails.application.config.action_dispatch.show_exceptions = true` to the test in the reproduction app, it passes.

**Comment by kruppel** [comment]
@jonathanhefner I've found that a similar test fails by removing `as: :json`, which would change the `Content-Type` header.

**Comment by andrepcg** [comment]
I have the same issue. Any news on this?

**Comment by dan-jensen** [comment]
The special `rescue_from` handling (introduced in [PR #34341](https://github.com/rails/rails/pull/34341)) no longer works, but @JoshCheek's [workaround](https://github.com/rails/rails/issues/34244#issuecomment-433365579) still does.

**Comment by pfemo** [comment]
Perhaps someone wants to re-open this issue? It seems that this still persists. 
Having to override proceed or introduce middleware seems silly considering this was previously acknowledged and addressed?

**Comment by rafaelfranca** [comment]
Can you open a new issue and provide what "no longer works" means? We have test to assert that it does work, so it is possible it doesn't work in your application because some gem or some code of your application. Please include proper backtrace in the issue as well.

**Comment by jeffblake** [comment]
@rafaelfranca My bug report includes steps to reproduce and a sample repo with tests.

**Comment by rafaelfranca** [comment]
I see that, but the issue in your bug report was fixed, and we have tests for it https://github.com/rails/rails/pull/34341/files#diff-ebe00936903e0620cc18b73ca852eb5570f60bbb156f03109b9a6bf4b1360646R73. Did you check if the same steps in your bug report fail in a Rails version with that fix?

**Comment by rafaelfranca** [comment]
Ah sorry, just saw it uses 6.0. Let me take a look.

**Comment by rafaelfranca** [comment]
It was broken by #34894. I'm fixing.

**Comment by rafaelfranca** [comment]
Now it is fixed and the test take care of making sure this specific problem don't have regressions.

**Comment by coorasse** [comment]
This is currently breaking our Middleware that was supposed to catch the `ParseError`s. The exception is no longer raised and just catched by https://github.com/wbotelhos/rails/commit/2cdf756808f43c9ee0ae2b83d4f06e93b8d9e763#diff-3834450d445e54f361a0cd4e9d6814c29d1279ca6dab4e99a0c88855e7689daeR287

**Comment by dave105010** [comment]
https://github.com/rails/rails/issues/34244#issuecomment-1247247924

> > Note that I found another solution which is much simpler than any of the others I've considered: It addresses the most pressing issue of bypassing `rescue_from`, but won't fix that these errors don't get logged. The basic idea is to override all the `process_action` methods with your own that rescues the `ParseError` and put your rescue logic there:
> > ```ruby
> > class ApplicationController < ActionController::API
> >   def process_action(*args)
> >     super
> >   rescue ActionDispatch::Http::Parameters::ParseError => exception
> >     render status: 400, json: { errors: [ exception.message ] }
> >   end
> > end
> > ```
> 
> I'm having this issue on Rails 6.1.7. We are spammed by bots making repeated GET requests with content-type: "application/json" with a faulty body something like "{ssd#$$fmessage".
> 
> This is great but overriding a Rails method "ApplicationController" seems a bit hacky to me. I wish I could just rescue this with a middleware.
> 
> The middleware solution above doesn't work and we cannot rescue from that error that way.


As mentioned here, there is no way to rescue this in some middleware. 

Is there a better way to handle this case rather than overriding the ApplicationController?

**Comment by rafaelfranca** [comment]
Defining a `rescue_from`?

**Comment by dave105010** [comment]
> Defining a `rescue_from`?

Ah sorry, it's hard to decipher what changed overtime. Thank you for bringing this up.
Let me drop this code snippet below so hopefully it helps the next person when they find this GitHub issue after a google search.

```ruby
class ApplicationController < ActionController::Base

…

  rescue_from ActionDispatch::Http::Parameters::ParseError do |exception|
    render status: 400, json: { errors: [ exception.message ] }
  end

```

This resolve the issue on Rails 6.1.7
