### ISSUE TITLE
Parallel testing - crashes when running

### ISSUE THREAD

**Issue by BKSpurgeon** [rails/rails#38281]
### Steps to reproduce
- I've created a minimal app to reproduce the issue, with reproduction instructions here - please click on the link and review the repo's readme. You can download the app and try and reproduce those issues locally:

https://github.com/BKSpurgeon/parallelisation-failure

### Expected behavior
Tests should run and should either pass or fail.

### Actual behavior
I'm getting a series of errors: 

1. `parallelization.rb:118:in `shutdown': Queue not empty, but all workers have finished. This probably means that a worker crashed and 1 tests were missed. (RuntimeError)`

2. `/home/koshy/.rbenv/versions/2.6.5/lib/ruby/2.6.0/drb/drb.rb:1738:in `current_server': DRb::DRbServerNotFound (DRb::DRbConnError)`

3. `/home/koshy/.rbenv/versions/2.6.5/lib/ruby/2.6.0/drb/drb.rb:1738:in `current_server': DRb::DRbServerNotFound (DRb::DRbServerNotFound)`

4. `/home/koshy/.rbenv/versions/2.6.5/lib/ruby/2.6.0/drb/drb.rb:565:in `dump': no _dump_data is defined for class PG::Connection (TypeError)`

### System configuration
**Rails version**: Rails 6.0.2.1

**Ruby version**: ruby 2.6.5p114 (2019-10-01 revision 67812) [x86_64-linux]

### Similar issues:
#37207

**Comment by eileencodes** [comment]
Are you and @thornomad working on the same app? You both reported the same experience within 2 hours of each other. I'm going to close this one since @thornomad has more detail.

**Comment by thornomad** [comment]
@eileencodes - no, we are not!  Coincidence. Thanks for the quick replies.
