### ISSUE TITLE
Bug with domains like "example.com.br"

### ISSUE THREAD

**Issue by cubaraphael** [rails/rails#38286]
#### 1. Update your `/etc/hosts` with this configuration below:
```sh
# Change xxx.xxx.x.x  to your current local ip
xxx.xxx.x.x             www.example.com
xxx.xxx.x.x             pro.example.com

xxx.xxx.x.x             www.example.com.br
xxx.xxx.x.x             pro.example.com.br
```
#### 6. Access the following url's and see the results
The 3 sequence steps is the natural behavior expected when all is working fine.
* Access the url `http://www.example.com:3000/` and see "Normal" text response.
* Access the url `http://www.example.com.br:3000/` and see "Normal" text response.
* Access the url `http://pro.example.com:3000/pro` and see "PRO" text response.
* Access the url `http://pro.example.com:3000/pro/home` and see "PRO" text response.

Here is the bug (the unique difference is the ".br" on domain)"
* Access the url `http://pro.example.com.br:3000/pro` and receive 404 error.
* Access the url `http://pro.example.com.br:3000/pro/home` and receive 404 error.

The same behavior above happens when I'm using this project on Heroku.
The application only works when my domain sounds like "domain.ext". Domains like "domain.ext.ext" doesn't working.

I've tested using passenger and puma and no one working.

### Expected behavior
My expectations is to access all the pages listed above without receive 404 response.

### Actual behavior
I receive 404 error page, but all is configured right.

### System configuration
**Rails version**:
6.0.2.1 (but occur with versions 5.2 too).
**Ruby version**:
2.6.5

**Comment by georgeguimaraes** [comment]
Hi, I just checked your app.
You have to use `request.subdomain(2)` on your `ProConstraint`. This is not a bug in Rails.
