### ISSUE TITLE
Reasons why save(validate: false) would be ignored in 5.0.2 but not 4.2.11.1?

### ISSUE THREAD

**Issue by andyd0** [rails/rails#38287]
### Steps to reproduce
Given the complexity of the code, I cannot provide an example.  We use `save(validate: false)` in our rspec tests when we don't need validations to be checked since it's not testing what needs to be tested. In most cases, this works. For a few tests it will return a validation failed error

### Expected behavior
example.save(validate: false) should always ignore validations

### Actual behavior
` ActiveRecord::RecordInvalid:
       Validation failed: User must exist, User can't be blank...`

### System configuration
**Rails version**:
5.0.2

**Ruby version**:
2.6.5

**Comment by rafaelfranca** [comment]
You need to give us more information on how to reproduce this issue, otherwise there is nothing we can do. Please read CONTRIBUTING.md file for more information about creating bug reports. Thanks!

Could you create a reproduction script with this template https://github.com/rails/rails/blob/master/guides/bug_report_templates/active_record_master.rb?

**Comment by andyd0** [comment]
Yeah I read that but I'm not sure if I'll be able to due to the complexity of the code but I'll give it a shot now

**Comment by andyd0** [comment]
I don't think I'll be able to replicate the issue. Below is my attempt and it doesn't fail.

```
# frozen_string_literal: true

require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  gem "rails", github: "rails/rails"
  gem "sqlite3"
end

require "active_record"
require "minitest/autorun"
require "logger"

# This connection will do for database-independent bug reports.
ActiveRecord::Base.establish_connection(adapter: "sqlite3", database: ":memory:")
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :locations, force: true do |t|
    t.string :name
  end

  create_table :products, force: true do |t|
    t.string :name
  end

  create_table :users, force: true do |t|
    t.string :name
  end

  create_table :sales, force: true do |t|
    t.integer :user_id
    t.integer :product_id
    t.integer :location_id
  end
end

class Sale < ActiveRecord::Base
  belongs_to :product, inverse_of: :sales, required: true
  belongs_to :user, inverse_of: :sales, required: true
  belongs_to :location, inverse_of: :sales, required: true  
end

class Product < ActiveRecord::Base
  has_many :sales, inverse_of: :product
end

class Location < ActiveRecord::Base
  has_many :sales, inverse_of: :location
  has_many :products, inverse_of: :location
  has_many :users, inverse_of: :location
end

class User < ActiveRecord::Base
  has_many :sales, inverse_of: :user
end


class BugTest < Minitest::Test
  def test_association_stuff
    location = Location.create!(name: "wherever")
    product = Product.create!(name: "whatever")
    sale = Sale.new(location: location, product: product)

    sale.save(validate: false)
  end
end

```

**Comment by andyd0** [comment]
I'll close this...

1. The likely reason why this doesn't work is because callbacks are firing off when they didn't in 4
2. Not clear how to skip callbacks for tests only but in this case not sure why we were even saving the sale - replaced with a fabricator instead
