### ISSUE TITLE
Logs are outputed into the Rails console

### ISSUE THREAD

**Issue by martinos** [rails/rails#38284]
### Steps to reproduce
In the console
```
Rails.logger.info("test")
```
### Expected behavior

I think that the Rails console should not output logs to the console (as it was prior to Rails 5), or at least give a way to disable this behavior.

### Actual behavior
`test` will be outputted the console. 

This causes me a lot of headache because when I call some methods on objects that are logging, my console gets flooded of logs. 

### System configuration
Rails 5.2.2 and Rails 6.0.1

**Ruby version**: 2.6.3

**Comment by Edouard-chin** [comment]
Rails doesn't output log on STDOUT in development and in test. It only does in production when the `RAILS_LOG_TO_STDOUT` environment variable is set, this is intended

**Comment by martinos** [comment]
@Edouard-chin, I don't understand what you are saying. I logged in a development console on a brand new rails app and here's what I've got:

```
~/tmp/app_rails -$ rails c
RRunning via Spring preloader in process 98447
aLoading development environment (Rails 6.0.2.1)
iirb(main):001:0> Rails.logger.info("coco")
coco
=> true
irb(main):002:0> ENV["RAILS_LOG_TO_STDOUT"]
=> nil
irb(main):003:0>
```

**Comment by Edouard-chin** [comment]
Weird, I just created a brand new app and I don't have the same result

```
❯ bin/rails c
Running via Spring preloader in process 1668
Loading development environment (Rails 6.0.2.1)
irb(main):001:0> Rails.logger.info('hello')
=> true
```

Can you shard the Github link of your test app ?

**Comment by martinos** [comment]
Here is my app:

git remote add origin git@github.com:martinos/app_rails.git
git push -u origin master

**Comment by Edouard-chin** [comment]
Ah ok yeah sorry, my app didn't have ActiveRecord. 

ActiveRecord broadcast logs to STDOUT https://github.com/rails/rails/blob/40c7c5e9912e3afd36b7c62748f7c11b9042df18/activerecord/lib/active_record/railtie.rb#L61 when inside the Rails console

**Comment by martinos** [comment]
I've found a hack around that:

```
ActiveRecord::Railtie.instance_variable_set(:@load_console, [])
```
But I feel that forcing people to have logs shown in their console is a bit extreme.  In my case it was really problematic.
