### ISSUE TITLE
ActiveModel 6.0.0 Argument Error from base.delegate

### ISSUE THREAD

**Issue by gupta-pratik** [rails/rails#38291]
### Error/Issue
I am trying to extend `ActiveModel::Naming` in one of the class that I have created. But its throwing following error:
`wrong number of arguments (given 2, expected 1)` from forwardable.rb file.
Stacktrace:
```
Application Trace | Framework Trace | Full Trace
/usr/local/lib/ruby/2.6.0/forwardable.rb:133:in `instance_delegate'
activemodel (6.0.0) lib/active_model/naming.rb:238:in `extended'
lib/presenter.rb:3:in `extend'
lib/presenter.rb:3:in `<class:Presenter>'
lib/presenter.rb:1:in `<top (required)>'
activesupport (6.0.0) lib/active_support/dependencies.rb:511:in `load'
activesupport (6.0.0) lib/active_support/dependencies.rb:511:in `block in load_file'
activesupport (6.0.0) lib/active_support/dependencies.rb:702:in `new_constants_in'
activesupport (6.0.0) lib/active_support/dependencies.rb:510:in `load_file'
activesupport (6.0.0) lib/active_support/dependencies.rb:407:in `block in require_or_load'
activesupport (6.0.0) lib/active_support/dependencies.rb:40:in `block in load_interlock'
activesupport (6.0.0) lib/active_support/dependencies/interlock.rb:14:in `block in loading'
activesupport (6.0.0) lib/active_support/concurrency/share_lock.rb:151:in `exclusive'
activesupport (6.0.0) lib/active_support/dependencies/interlock.rb:13:in `loading'
activesupport (6.0.0) lib/active_support/dependencies.rb:40:in `load_interlock'
activesupport (6.0.0) lib/active_support/dependencies.rb:390:in `require_or_load'
activesupport (6.0.0) lib/active_support/dependencies.rb:545:in `load_missing_constant'
activesupport (6.0.0) lib/active_support/dependencies.rb:214:in `const_missing'
app/presenters/webform_presenter.rb:1:in `<top (required)>'
```

![image](https://user-images.githubusercontent.com/22120990/72975940-a99bd500-3df7-11ea-9361-77e583e70c2d.png)

![image](https://user-images.githubusercontent.com/22120990/72976000-c3d5b300-3df7-11ea-88ee-99e528bde727.png)
### This is how my class looks like:

```
class Presenter
  extend Forwardable
  extend ActiveModel::Naming
  include ActiveModel::Conversion

  def persisted?
    ! self.new_record?
  end

  def new_record?
    ! self.id.present?
  end

  def to_param
    self.id
  end

  def id
    # TODO: Overwrite this
  end

  def initialize(options = {})
    options[:params].each_pair do |attribute, value|
      self.send :"#{attribute}=", value
    end unless options[:params].nil?
  end
end
```

### NOTE

> This issue started coming up after we migrate to rails `6.0.0`. It was working fine with rails `3.2.21`

### System configuration
**Rails version**: 6.0.0

**Ruby version**: 2.6.5

**Comment by ak15** [comment]
Hi,
I was digging to this code and found following points which might help you
1. [Ruby /Forwardable delegate method](https://github.com/rails/rails/blob/master/activesupport/lib/active_support/core_ext/module/delegation.rb#L171)
2. [Delegate in Rails](https://github.com/rails/rails/blob/master/activesupport/lib/active_support/core_ext/module/delegation.rb#L171)

Since Delegate defined in Forwardable is overriding the one defined in rails , you are getting this error.
You may try  remove Forwardable and test, it might work.

**Comment by gupta-pratik** [comment]
Hi @ak15 ,
Thanks for replying. I tried removing `Forwardable` but then some other issue started coming up.
