### ISSUE TITLE
ActiveRecord::StatementInvalid: PG::UndefinedTable: ERROR:  relation "view_people" does not exist

### ISSUE THREAD

**Issue by thornomad** [rails/rails#38302]
I am in the process of updating an app from 5.2 to 6.0 that uses postgresql@10.11.  The app relies on a number of postgres views and functions.  These views and functions are created in migrations.

_In the 5.2 series, postgres views and functions (and data seeded during a migration) persist between test runs._  **However, in 6.0 the views and functions are being wiped between tests (which breaks almost our entire test suite because the models in the app rely on them).**

I created two repos that demonstrate the different behavior between versions.  I would appreciate any insight or advice on the expectations of this behavior going forward and whether this is indeed a 'bug' or if it will be the new way of doing testing business and suggestions for moving forward.

### Two repositories that demonstrate the difference between 5.2 and 6.0

* [Rails 5 - passing](https://github.com/thornomad/issue-38279-rails-5)
* [Rails 6 - failing](https://github.com/thornomad/issue-38279-rails-6)

_I tried a Docker approach (first time) in case there is something unique about my setup.  You should be able to test this without docker, however._

```fish
# Download the repo, install, migrate, run tests
git clone git@github.com:thornomad/issue-38279-rails-5.git # or 6.git
cd issue-38279-rails-5
bundle install
bundle exec rake db:create RAILS_ENV=test
bundle exec rake db:migration RAILS_ENV=test
bundle exec rake

# DOCKER approach
git clone git@github.com:thornomad/issue-38279-rails-5.git  # or 6.git
cd issue-38279-rails-5
docker-compose build
docker-compose run --rm app bundle install
docker-compose run --rm app rails db:create RAILS_ENV=test
docker-compose run --rm app rails db:migrate RAILS_ENV=test
docker-compose run --rm app rake

# Tests pass in the 5 repo, but not the 6 given the same migration and test file
```

Both repos just contain a single migration and test file (identical) which I will include here.

### Example migration that creates a view and seeds data

```ruby
# db/migrate/xxxx_create_table_and_view_for_testing.rb
class CreateTableAndViewForTesting < ActiveRecord::Migration[5.2] # or [6.0] !
  class Person < ApplicationRecord; end

  def up
    create_table :people do |t|
      t.string :name
    end

    # Simple view that should persist
    connection.execute <<-SQL
      DROP VIEW IF EXISTS view_people;
      CREATE OR REPLACE VIEW view_people AS
        SELECT id, name
        FROM people
    SQL

    # Seed the database with some values
    (1..5).each { |i| Person.create!(name: "Person ##{i}") }
  end

  def down
    connection.execute <<-SQL
      DROP VIEW IF EXISTS view_people;
    SQL
    drop_table :people
  end
end
```

### Test that expects to find the view and seeded data from migration

```ruby
# test/models/person_test.rb
require 'test_helper'

class PersonTest < ActiveSupport::TestCase

  class Person < ApplicationRecord; end

  class ViewPerson < ApplicationRecord
    self.table_name = 'view_people'
  end

  test 'there are five seeded people' do
    assert_equal 5, Person.count
  end

  test 'there are five people in the view' do
    assert_equal 5, ViewPerson.count
  end

end
```

### Expected behavior
I would expect the tests to pass in 6.0, as they do in the 5.2 app.

### Actual behavior
In the 6.0 app the tests fail.  It appears the test suite is wiping any custom postgres view or function as well as clearing any seeded data from a migration.  This does not happen in 5.2.

### Appreciate your help

Thank you!

### System configuration
**Rails version**: 6.0.2.1 (I pinned it at a specific forward reference in the 6-0-stable branch to eliminate an unrellated exception, so the test repo is actually slightly ahead of this version)

**Ruby version**: 2.6.3
See the single migration file and the single test, committed seperately.  These
tests are failing in 6.0 but passing in 5.2 under the same conditions.

**Comment by eileencodes** [comment]
Looking at the logs I really don't think the test suite is dropping these views. There is no logs for a destroy on this table/relation.

When I run this on Rails 5 with my copy I get this:

```
PersonTest#test_there_are_five_people_in_the_view:
ActiveRecord::StatementInvalid: PG::UndefinedTable: ERROR:  relation "view_people" does not exist
LINE 8:                WHERE a.attrelid = '"view_people"'::regclass
                                          ^
:               SELECT a.attname, format_type(a.atttypid, a.atttypmod),
                     pg_get_expr(d.adbin, d.adrelid), a.attnotnull, a.atttypid, a.atttypmod,
                     c.collname, col_description(a.attrelid, a.attnum) AS comment
                FROM pg_attribute a
                LEFT JOIN pg_attrdef d ON a.attrelid = d.adrelid AND a.attnum = d.adnum
                LEFT JOIN pg_type t ON a.atttypid = t.oid
                LEFT JOIN pg_collation c ON a.attcollation = c.oid AND a.attcollation <> t.typcollation
               WHERE a.attrelid = '"view_people"'::regclass
                 AND a.attnum > 0 AND NOT a.attisdropped
               ORDER BY a.attnum
```

This feels a lot more like a postgres client version issue.

**Comment by eileencodes** [comment]
I changed the title of the issue because I don't think it's test suite related and the error is easier for others to search for.

**Comment by thornomad** [comment]
Ah, logs!  Back on the **Rails 6** repo ... if I take these steps let me show you what I am seeing:

```
bundle exec rake db:drop
bundle exec rake db:migrate RAILS_ENV=test
rm log/test.log
# <---- database is cleanly reset and logs are clear
bundle exec rake 
cat log/test.log
```

### Rails 6 log/test.log

<img width="1030" alt="image" src="https://user-images.githubusercontent.com/124717/73105542-25585900-3eae-11ea-815f-708a866c0939.png">

I can see that it is logging a complete DROP of the database table, creation of it and then re-creating it (from the schema it would appear to me).

It's worth noting: _this is only happening on the *first* test run after the migration._. Subsequent test runs do not trigger a database drop.  So if you are checking logs later you won't see it.  Just the first time.

### Rails 5 logs, same steps as above

<img width="547" alt="image" src="https://user-images.githubusercontent.com/124717/73106006-32c21300-3eaf-11ea-9b34-5df2cd21809d.png">

There is no dropping or re-creating the database on Rails 5 that I can see. 

I guess I disagree with the assessment that it's related to the error in the title.  What I see is that in Rails 6 we have dropping and re-creating the test database after a migration; and in Rails 5 it did not seem to do that.  The error is a byproduct of that.

PS: I wish I could peek over your shoulder with the Rails 5 version because I am quite certain of its behavior!  Smile.  Did you try the docker image?  After you start with a clean test database and run the migration, can you confirm that the view does indeed exist in your database (as it should at that time)?  Can you see the `view_people` Postgres view having been created after you run the migration the first time?  We use this method to create Postgres views quite extensively ...

**Comment by eileencodes** [comment]
The database is reset in parallel testing and I'm not arguing that. But you said you can reproduce with parallel testing turned off so I think you need to capture logs with parallel testing turned off.

**Comment by thornomad** [comment]
Thanks for taking the time to work with me on this.  

If I **disable** parallelization by commenting out the line here:

```diff
diff --git a/test/test_helper.rb b/test/test_helper.rb
index d5300f8..413ece9 100644
--- a/test/test_helper.rb
+++ b/test/test_helper.rb
@@ -4,7 +4,7 @@ require 'rails/test_help'

 class ActiveSupport::TestCase
   # Run tests in parallel with specified workers
-  parallelize(workers: :number_of_processors)
+  # parallelize(workers: :number_of_processors)

   # Setup all fixtures in test/fixtures/*.yml for all tests in alphabetical order.
   fixtures :all
```

I still see the same behavior when I run the tests. That is: the first test run after the migration is logging the DROP and subsequent runs do not.  On a side note,  I originally am encountering this problem using spec, which I do not believe leverages the parallelization feature (at least I think this to be true).  I just created the test repos and leveraged the build in test framework to demonstrate it.

<img width="641" alt="image" src="https://user-images.githubusercontent.com/124717/73108428-3062b780-3eb5-11ea-9a65-b27866236616.png">

Is there a way for me to find out what parts of the codebase are actually writing to the log file?

**Comment by rafaelfranca** [comment]
Just to be sure. Are you using the rb or sql format for the schema? If it is the rb format, when the test run `db:test:prepare` your view will not be in the schema since I don't think Rails store views when the rb format is used. `db:test:prepare` happens every time a test process starts if the schema file and the database are in a different state.

If you are using the rb format and you want to use view you need to change it to the SQL format.

**Comment by thornomad** [comment]
> If you are using the rb format and you want to use view you need to change it to the SQL format.

Ah!  That definitely is part of the problem—I added this to `config/application.rb`:

```ruby
config.active_record.schema_format = :sql
```

And the views and functions persist!  Thank for you for that tip.

Now I need to figure out how to persist the seeded data between test runs after this upgrade.  Obviously the way it was working in Rails 5 is not going working anymore.  This was a big first step though, thank you everyone who helped me out.

**Comment by thornomad** [comment]
Just a final follow-up as I believe I cracked the last part of the puzzle of what is different from Rails 5 to Rails 6 in terms of the test database and having pre-seeded data.

There is a new record/row being added to the `ar_internal_metadata` table in Rails 6 which indicates whether or not the schema for the test database is up to date.  The row has a key of `schema_sha1` and includes a hash that can be checked against the current `schema.rb` or `structure.rb` file.  This check is new in Rails 6.

https://github.com/rails/rails/blob/6-0-stable/activerecord/lib/active_record/tasks/database_tasks.rb#L341-L367

If the `schema_sha1` hash is missing or doesn't match when the tests are being run, it will purge the database and reload the schema before continuing.  

This new bit is what was tripping me up ... because I was creating the database, migrating, then seeding and running tests.  In Rails 6, without loading the structure before seeding, the seeds are going to be wiped out the first test run until the schema gets loaded and that `schema_sha1` key/hash gets set. 

Hope this helps the next wanderer.

**Comment by AndreyBartnovskiy** [comment]
@thornomad You my hero! Thx for solution:D
Only this sequence of commands could help me 🥇
