### ISSUE TITLE
Rails 6 - RangeError not raised while interacting with ActiveRecord

### ISSUE THREAD

**Issue by yosiat** [rails/rails#38309]
### Steps to reproduce

Running this script will yield:

```ruby
# frozen_string_literal: true

require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  # Activate the gem you are reporting the issue against.
  gem "activerecord", "6.0.2.1"
  gem "pg"
end

require "active_record"
require "minitest/autorun"
require "logger"

ActiveRecord::Base.establish_connection(
  adapter: "postgresql",
  database: "rails_bug_report"
)
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :posts, force: true do |t|
  end
end

class Post < ActiveRecord::Base
end

class BugTest < Minitest::Test
  OUT_OF_RANGE_ID = "123456789123456111111"
  def test_find_raise_record_not_found_with_out_of_range_message
    error = assert_raises ActiveRecord::RecordNotFound do
      Post.find(OUT_OF_RANGE_ID)
    end
    assert_match /out of range value/, error.message
  end

  def test_where_fails_with_range_error
    assert_raises ActiveModel::RangeError do
      Post.where(id: OUT_OF_RANGE_ID).first
    end
  end
end
```

**Rails 6**
```
# Running:

FD, [2020-01-25T15:08:55.489939 #76656] DEBUG -- :   Post Load (0.3ms)  SELECT "posts".* FROM "posts" WHERE 1=0 ORDER BY "posts"."id" ASC LIMIT $1  [["LIMIT", 1]]
F

Finished in 0.006088s, 328.5151 runs/s, 657.0302 assertions/s.

  1) Failure:
BugTest#test_find_raise_record_not_found_with_out_of_range_message [rails_bug.rb:39]:
Expected /out of range value/ to match "Couldn't find Post with 'id'=123456789123456111111".

  2) Failure:
BugTest#test_where_fails_with_range_error [rails_bug.rb:43]:
ActiveModel::RangeError expected but nothing was raised.

2 runs, 4 assertions, 2 failures, 0 errors, 0 skips
```

**Rails 5.2.4**
```
# Running:

..

Finished in 0.006761s, 295.8142 runs/s, 591.6285 assertions/s.

2 runs, 4 assertions, 0 failures, 0 errors, 0 skips
```

### Expected behavior

Should match Rails 5.2.4:

- No queries should be executed against DB since it should fail as validation error: in rails 6 I am seeing: `SELECT "posts".* FROM "posts" WHERE 1=0 ORDER BY "posts"."id" ASC LIMIT $1  [["LIMIT", 1]]`
- Exact error message: instead of `ActiveRecord::RecordNotFound` with "can't find XX" I would like to see "value out of range"
 

### Actual behavior

Described in expected behaviour, I can elaborate more if needed.

### System configuration
**Rails version**: 6.0.2.1 (the tests pass on 5.2.4, and fails on 6.0.0 and 6.0.2.1)
**Ruby version**: 2.6.3

**Comment by thiaguerd** [comment]
> All of queries should return correct result even if including large number

[PR#30000](https://github.com/rails/rails/pull/30000)


When you set up a query with a large number it will not be inserted in the where of sql, as the query is invalid, so clause "1=0" is added to ensure that there is no result

**Comment by yosiat** [comment]
I saw that PR and open this issue for discussion...
I understand that `1=0` will ensure there is no result but: this is a waste of queries running against DB and we are not raising the relevant issue.

**Comment by thiaguerd** [comment]
I agree with you
[here is talked about it](https://youtu.be/yN1rGZbwn9k?t=1245)
I believe that none sql must be run if is identified that is invalid

**Comment by yosiat** [comment]
@kamipo can you address this issue please?

**Comment by yosiat** [comment]
Thanks, @kamipo for the PR!

I assume it won't fix the RangeError, I will still get RecordNotFound but no queries are going to be executed, which is ok for me!

Thanks again!
