### ISSUE TITLE
#send_data should support StringIO

### ISSUE THREAD

**Issue by fschwahn** [rails/rails#38304]
### Steps to reproduce
When I have a class which generates some (binary) file (eg. an excel report), it's usual that this result is returned as a `StringIO`. If use `send_data` to send this the client receives a string `"#<StringIO:0x00007fcd9c8d3a58>"` instead of the content of the `StringIO`. For some reason I expected this to work and was rather surprised that it didn't.

I'd be willing to put a PR together which adds support for that if wanted.

### Expected behavior
I'd expect `send_data` to read the content of `StringIO`.

### Actual behavior
`send_data` calls `to_s` on `StringIO`, returning a useless result.

### System configuration
**Rails version**: 5.2.3
**Ruby version**: 2.6.5

**Comment by fschwahn** [comment]
I still think this is unexpected.

**Comment by simi** [comment]
IMHO this is not "bug". Looking at `send_data` [docs](https://api.rubyonrails.org/classes/ActionController/DataStreaming.html#method-i-send_data)

> This method is similar to render plain: data...

And looking at render [docs](https://api.rubyonrails.org/classes/ActionController/Renderer.html#method-i-render) there's no IO support mentioned.

If you would like to stream IO, you can use approach similar to https://coderwall.com/p/kad56a/streaming-large-data-responses-with-rails.

If you would like to use `send_data` with `StringIO`, you need to cast it back to string like `StringIO.new('ABC').string #=> "ABC"`.

Alt. `render` could be extended to support IO objects with syntax like `render io: StringIO.new('ABC')`. But I have no idea if that would be accepted and merged to Rails.

**Comment by fschwahn** [comment]
> IMHO this is not "bug". Looking at send_data docs

I agree, I just assumed that this worked without even looking at the docs. So this is clearly my fault. This is more about if this expectation of mine was unreasonable or not. I just expected to be able to use `send_data` with any IO-like.

> If you would like to use send_data with StringIO, you need to cast it back to string like StringIO.new('ABC').string #=> "ABC".

Yes, that's what I did.

**Comment by simi** [comment]
> I agree, I just assumed that this worked without even looking at the docs. So this is clearly my fault.

Then I suggest to close the issue.
