### ISSUE TITLE
Action Mailbox `service_name` is null on Heroku with Amazon S3

### ISSUE THREAD

**Issue by rikkipitt** [rails/rails#38306]
### Steps to reproduce

I'm using Action Mailbox with S3 storage on Heroku. While I've never had storage issues previously (using it for file upload), Action Mailbox inbound mail is failing to save. A rollback is occurring as `service_name` is coming through as null.

Can anyone advise? Thanks, folks!

### Expected behavior
I expect the mailbox record to save when using Amazon S3.

### Actual behavior
`ActiveRecord::NotNullViolation (PG::NotNullViolation: ERROR:  null value in column "service_name" violates not-null constraint)` error occurs and rolls back the whole transaction.

### System configuration
**Rails version**: 6.0.2.1

**Ruby version**: 2.6.3

**Comment by sunny** [comment]
I don't know if this fixed it for you @rikkipitt, but for the lost souls that stumble upon this error, running `rails app:update` may provide you with the required migrations for this to work correctly.
