### ISSUE TITLE
String#sql_safe flag (equivalent to html_safe)

### ISSUE THREAD

**Issue by avit** [rails/rails#38301]
## Goal 

Avoid a potential injection pattern by promoting safer SQL string composition.

## Problem

In ActiveRecord conditions, it's possible to pass a relation object to compose a subquery:

```
Feature.where(project_id: Project.active.select(:id))
```

However, this is limited to relations that can be built with the ActiveRecord query interface. Once it becomes necessary to construct that fragment using raw SQL, the only option for querying it becomes:

```
Feature.where("features.project_id IN(#{complex_ids_sql})")
```

This style of string interpolation naturally looks suspicious, and is warned by static analysis tools like Brakeman. Ideally we should be able to pass a known-safe SQL literal fragment to querying methods like `where` and avoid this pattern.

## Proposal

Internally, `Arel.sql("str")` exists for defining a SqlLiteral fragment. This style of wrapping to declare the string as a valid SQL fragment could be exposed as `"str".sql_safe`, analogous to what happens with SafeBuffer and `html_safe`.

When a SqlLiteral is passed instead of a String, the following patterns could be supported:

```
complex_ids_sql = QUERY.sql_safe
where(project_id: complex_ids_sql)
where("project_id IN (?)", complex_ids_sql)
where("project_id IN (%s)", complex_ids_sql)
```

These would result in having the SQL fragment interpolated to the predicate—instead of quoting it as a string literal. The resulting query would be the same as just building the string using today's `#{}` interpolation.

## Benefits

1. It can simplify the `"project_id IN (?)"` syntax construction for us, and let the relation provide the disambiguated table name by using the hash argument format (`project_id: sql`)
2. It makes it very clear that there is no injection, given that the SQL fragment is properly sanitized and declared "SQL safe" at its source.

I would be happy to provide a PR for further review of this idea if the core team is interested.

**Comment by olliebennett** [comment]
I think the proposal makes sense (and your stated goal is great), however `sql_safe` (like `html_safe`) could be a new avenue for potential bugs and allows for lazier bypassing of SQL checks. By making it simpler to whitelist code, `sql_safe` could become the go-to solution without developers thinking through alternative implementations.

RuboCop's [Rails/OutputSafety](https://github.com/rubocop-hq/rubocop-rails/blob/master/lib/rubocop/cop/rails/output_safety.rb) cop already protects against use of `html_safe`.

You also mention Brakeman flagging the problem. At least for now there is a workaround of adding the code signature to your `brakeman.ignore` configuration. I wonder if it's possible to make Brakeman more context-aware so it can avoid flagging safe usage.

I suspect the introduction of this change would only move the "ignore" config from Brakeman to either RuboCop (assuming `sql_safe` constituted an OutputSafety violation) or the code, without necessarily achieving your stated goal.

**Comment by matthewd** [comment]
The intention was for `Arel.sql` to _be_ the public spelling of "this string is valid/safe SQL, I promise" -- partly to avoid another domain-specific set of String extension methods, but also in an attempt to avoid the known misinterpretation where people expect `html_safe` to be "make this safe" instead of "this is already safe".

In principle I'd like to support additional natural usages, like those you suggest. PRs in that direction (and/or supporting documentation to make it more clearly an official usage) are welcome.

**Comment by tenderlove** [comment]
Just echoing @matthewd here.  `Arel.sql("str")` is public API, please feel free to use it.

**Comment by simi** [comment]
Just wondering, shouldn't be this closed according to Rails issues policy since it is not bug report or pull request?

**Comment by tenderlove** [comment]
@simi sure!

**Comment by avit** [comment]
Thanks for the feedback everyone, I will prepare a PR to make this work with `Arel.sql`. 

I just wanted to see if this made sense before I jump into it. :+1:
