### ISSUE TITLE
Uninitialized ActiveStorage CreateTables

### ISSUE THREAD

**Issue by ZairaZafar** [rails/rails#38321]
I recently integrated amazon s3 into my rails application and had to install active storage gem for it. After including active storage in my gem file and running `bundle install`, I created active storage directories by running 'rails activestorage:install' which gave me below output

[
<img width="725" alt="Screenshot 2020-01-27 at 12 06 41 PM" src="https://user-images.githubusercontent.com/30323054/73155767-8d50ae80-40fd-11ea-8cac-d011e43cfd35.png">
](url)

On the output's instructions I ran `rails db:migrate`. Migrations should have run successfully instead it resulted in the error below:
<img width="712" alt="Screenshot 2020-01-27 at 12 11 34 PM" src="https://user-images.githubusercontent.com/30323054/73156027-34cde100-40fe-11ea-8a3d-642d7759518c.png">

After wasting hour or so searching the internet I found nothing. I decided to distrust the library and went to look at the migration file and saw that the migration file was named as `xxxxxxx_active_storage_create_tables.rb` and the file code looked as follows:
<img width="493" alt="Screenshot 2020-01-27 at 12 10 07 PM" src="https://user-images.githubusercontent.com/30323054/73156112-7bbbd680-40fe-11ea-8996-6887fa6b378f.png">

When I corrected the file code to picture below and ran `rake db:migrate` again and it worked this time.
<img width="718" alt="Screenshot 2020-01-27 at 12 16 34 PM" src="https://user-images.githubusercontent.com/30323054/73156223-f684f180-40fe-11ea-91f4-7984c89f00e0.png">

### System configuration
**Rails version**:
5.1.7

**Ruby version**:
2.4.1

**Comment by eileencodes** [comment]
Are you sure you're using Rails 5?1 ActiveStorage wasn't added until Rails 5.2.

**Comment by ZairaZafar** [comment]
Yes. I attached an image below that shows my rails version
<img width="606" alt="Screenshot 2020-01-27 at 6 59 12 PM" src="https://user-images.githubusercontent.com/30323054/73180501-3d8ed900-4137-11ea-9bc7-214d7590c777.png">

**Comment by eileencodes** [comment]
Are you using a separate gem for Active Storage? I'm thinking maybe you have a Rails 5.1 app and included the original gem that was separate from Rails. That code no longer exists and there is no incorrect ActiveStorageCreateTables migration in the Rails source code.

I'm closing this issue because Rails 5.1 is also no longer supported for bug fixes so we recommend you upgrade to 5.2 or 6.0. Since 5.2 will also end support for bug fixes when 6.1 is released (probably around May 2020) 6.0 is ideal.

**Comment by jrgriffiniii** [comment]
Many, many thanks @ZairaZafar, I'm working on adding some features to a Rails 5.1.z application, and I've needed to install `activestorage` 0.1 - this saved me much time!
