### ISSUE TITLE
What about removing `Rack::Runtime` from the default middleware stack?

### ISSUE THREAD

**Issue by kevinnio** [rails/rails#38325]
Hi, guys. Just wanted to hear your thoughts about this.

We recently found a vulnerability in our app in which hackers can tell if a user email is in our database or not by checking the value included in the `X-RUNTIME` response header while brute-forcing the login form. Basically, a valid email consistently provides a higher value:

```
Valid -> X-Runtime: 1.303640
Invalid -> X-Runtime: 0.027483
```

This header is inserted into every response by `Rack::Runtime`, which is included in the default middleware stack (at least for Rails 4). Is there any particular reason to include it as default? And if not, why not remove it to prevent vulnerabilities like this? Most people don't notice `Rack::Runtime` is there so they don't remove it while also most out-of-the-box authentication gems don't account for it, so they're affected by the vulnerability.

What do you guys think?

**Comment by joshmn** [comment]
This is probably best for the mailing list https://groups.google.com/forum/#!forum/rubyonrails-talk

For your application, you can remove it pretty easily. https://guides.rubyonrails.org/rails_on_rack.html#deleting-a-middleware

```
# config/application.rb
config.middleware.delete Rack::Runtime
```

**Comment by kevinnio** [comment]
Of course, we ended up removing it. I'll send a message to the mailing list about this. Thanks!

**Comment by rafaelfranca** [comment]
Not against this. @tenderlove @eileencodes @matthewd?

**Comment by matthewd** [comment]
It's my understanding that it's well-established that even trivial timing differences can be detected across remote web requests: if you have a timing vulnerability that's exposed by the X-Runtime header, when you remove the header, you still have a timing vulnerability.

To me, it's a somewhat useful value to have easy access to when your application is inevitably being slower-than-expected in production, and there's no actual exposure because it just makes it easier to access information an attacker could already derive. 

That said, I don't feel strongly about it -- just seems like removing it doesn't actually solve anything. 🤷🏻‍♂️

**Comment by tenderlove** [comment]
I'm OK removing it, but if I remember correctly we tried to do it once and people were depending on it being in the middleware stack.  That might have just been on the Rails side though, but give me some time to investigate

**Comment by tenderlove** [comment]
Sorry, I thought this was the Rack repo >_<

Yes, we tried to remove it once here: https://github.com/rails/rails/commit/37423e4ff883ad5584bab983aceb4b2b759a1fd8

Then ended up reverting that here: https://github.com/rails/rails/commit/24f9c03d52ad4c7f081cc7a9561946109b3ad500

I'd like to remove it, but commit comment details the issue.

**Comment by kevinnio** [comment]
What about replacing `Rack::Runtime` with a dummy placeholder, then raise warnings about it being removed in a future version? That would give people time to migrate their engines out of using that constant.

**Comment by tenderlove** [comment]
@kevinnio that sounds like a good plan!

**Comment by SValkanov** [comment]
If I'm understanding the idea correctly, what is the best place to extract the `Rack::Runtime` in method with deprecation warning? `DefaultMiddlewareStack` / `Rails::Application::Configuration`?

**Comment by tenderlove** [comment]
I think any mutation or manipulation of the middleware stack that passes in `Rack::Runtime` would need to display a warning.  But you would also have to check to see if the user manually added `Rack::Runtime` as to prevent false positives.  Probably `MiddlewareStackProxy`

**Comment by SValkanov** [comment]
What about adding initializer in `Finisher` which will run after `build_middleware_stack` and check if `Rack::Runtime` is included in the built stack?

**Comment by byroot** [comment]
This was done 3 weeks ago. Closing.
