### ISSUE TITLE
[ActiveRecord] Failing to reconnect to Postgres Database

### ISSUE THREAD

**Issue by marcoadkins** [rails/rails#38324]
### Steps to reproduce

1. Create a rails application.
2. Connect to a RDS Aurora Postgres Instance
3. Restart postgres
4. After the restart the rails application will then raise a `PG::UnableToSend: no connection to the server` error on queries to the database.

Stacktrace:
```
["/usr/local/bundle/gems/activerecord-6.0.2.1/lib/active_record/connection_adapters/postgresql_adapter.rb:686:in `exec_prepared'",
 "/usr/local/bundle/gems/activerecord-6.0.2.1/lib/active_record/connection_adapters/postgresql_adapter.rb:686:in `block (2 levels) in exec_cache'",
 "/usr/local/bundle/gems/activesupport-6.0.2.1/lib/active_support/dependencies/interlock.rb:48:in `block in permit_concurrent_loads'",
 "/usr/local/bundle/gems/activesupport-6.0.2.1/lib/active_support/concurrency/share_lock.rb:187:in `yield_shares'",
 "/usr/local/bundle/gems/activesupport-6.0.2.1/lib/active_support/dependencies/interlock.rb:47:in `permit_concurrent_loads'",
 "/usr/local/bundle/gems/activerecord-6.0.2.1/lib/active_record/connection_adapters/postgresql_adapter.rb:685:in `block in exec_cache'",
 "/usr/local/bundle/gems/activerecord-6.0.2.1/lib/active_record/connection_adapters/abstract_adapter.rb:718:in `block (2 levels) in log'",
 "/usr/local/lib/ruby/2.6.0/monitor.rb:230:in `mon_synchronize'",
 "/usr/local/bundle/gems/activerecord-6.0.2.1/lib/active_record/connection_adapters/abstract_adapter.rb:717:in `block in log'",
 "/usr/local/bundle/gems/activesupport-6.0.2.1/lib/active_support/notifications/instrumenter.rb:24:in `instrument'",
 "/usr/local/bundle/gems/activerecord-6.0.2.1/lib/active_record/connection_adapters/abstract_adapter.rb:708:in `log'",
 "/usr/local/bundle/gems/activerecord-6.0.2.1/lib/active_record/connection_adapters/postgresql_adapter.rb:684:in `exec_cache'",
 "/usr/local/bundle/gems/activerecord-6.0.2.1/lib/active_record/connection_adapters/postgresql_adapter.rb:655:in `execute_and_clear'",
 "/usr/local/bundle/gems/activerecord-6.0.2.1/lib/active_record/connection_adapters/postgresql/database_statements.rb:98:in `exec_query'",
 "/usr/local/bundle/gems/activerecord-6.0.2.1/lib/active_record/connection_adapters/abstract/database_statements.rb:491:in `select_prepared'",
 "/usr/local/bundle/gems/activerecord-6.0.2.1/lib/active_record/connection_adapters/abstract/database_statements.rb:68:in `select_all'",
 "/usr/local/bundle/gems/activerecord-6.0.2.1/lib/active_record/connection_adapters/abstract/query_cache.rb:107:in `select_all'",
 "/usr/local/bundle/gems/activerecord-6.0.2.1/lib/active_record/querying.rb:46:in `find_by_sql'",
 "/usr/local/bundle/gems/activerecord-6.0.2.1/lib/active_record/statement_cache.rb:134:in `execute'",
 "/usr/local/bundle/gems/activerecord-6.0.2.1/lib/active_record/core.rb:175:in `find'",
 "/usr/src/app/lib/../authenticate_user.rb:11:in `authenticate_user'"]
```

### Expected behavior

Rails should reconnect to Postgres with raising an error.

### Actual behavior

Rails throws an error and does not reconnect until the rails application is restarted.

### System configuration
**Rails version**: 6.0.2.1

**Ruby version**: 2.6.1

**PG Gem Version**: 1.2.2

**PG Database Version**:10.7

### Additional Questions
- Is auto-reconnect supposed to be handled by active record? 
- If not is there a working example of how to achieve auto reconnect with active record and Postgres?

**Comment by tamvm** [comment]
Hi @madkin10, 

Seems that we are having some problems, is there any fix that you have applied? 

Thank you,

**Comment by madkin10** [comment]
Hey @tamvm,

We do have a fix of sorts. We are deploying our application using Kubernetes so are using a readiness endpoint that Kubernetes sends a request to every few seconds to sense and recover from lost database connections.

```ruby
def readiness
  if connected_to_database?
    render json: "APP is ready"
  else
    reconnect_to_database
    render json: "APP is not ready", status: :service_unavailable
  end
end

def connected_to_database?
  ActiveRecord::Base.logger.silence do
    ActiveRecord::Base.connection.execute('SELECT 1;')
  end
  true
rescue => exception
  handle(exception, Rails.logger)
  false
end

def reconnect_to_database
  ActiveRecord::Base.connection.reconnect!
rescue => exception
  handle(exception, Rails.logger)
end
```

**Comment by tjoyal** [comment]
Experiencing the same on Heroku managed PostgreSQL where I suspected it could be linked to a maintenance window.

Here is some local repro steps (osx).

Terminal 1:
```
irb(main):014:0> ActiveRecord::Base.connection.execute('SELECT 1;')
   (0.3ms)  SELECT 1;
=> #<PG::Result:0x00007fede6358988 status=PGRES_TUPLES_OK ntuples=1 nfields=1 cmd_tuples=1>
```

Terminal 2:
```
$ brew services restart postgresql
Stopping `postgresql`... (might take a while)
==> Successfully stopped `postgresql` (label: homebrew.mxcl.postgresql)
==> Successfully started `postgresql` (label: homebrew.mxcl.postgresql)
```

Back to terminal 1:
```
irb(main):015:0> ActiveRecord::Base.connection.execute('SELECT 1;')
   (0.3ms)  SELECT 1;
ActiveRecord::StatementInvalid (PG::UnableToSend: server closed the connection unexpectedly)
	This probably means the server terminated abnormally
	before or while processing the request.

irb(main):016:0> ActiveRecord::Base.connection.execute('SELECT 1;')
   (0.2ms)  SELECT 1;
ActiveRecord::StatementInvalid (PG::UnableToSend: no connection to the server)

irb(main):017:0> ActiveRecord::Base.connection.execute('SELECT 1;')
   (0.3ms)  SELECT 1;
ActiveRecord::StatementInvalid (PG::UnableToSend: no connection to the server)

irb(main):018:0> ActiveRecord::Base.connection.reconnect!
=> [#<PG::Result:0x00007feda6bad588 status=PGRES_COMMAND_OK ntuples=0 nfields=0 cmd_tuples=0>]

irb(main):019:0> ActiveRecord::Base.connection.execute('SELECT 1;')
   (161.1ms)  SELECT 1;
=> #<PG::Result:0x00007fedc6376b38 status=PGRES_TUPLES_OK ntuples=1 nfields=1 cmd_tuples=1>
```

**Comment by tjoyal** [comment]
Reading rails connection pool code and https://github.com/rails/rails/issues/29189, it looks like it is behaving as expected?

> it's unsafe to reconnect in the middle of a request, because the connection may have state we can't reproduce.

Totally make sense to me.

On my end, my issue was in a permanent background worker that didn't go through the full rails stack, only AR. I tried to track down how rails controllers handle this between requests. AFAIK there is some reconnection logic between web requests? If anyone could point it out I would really appreciate and would use it as best practice.

@marcoadkins are your issues through a web request or some other background worker?

**Comment by marcoadkins** [comment]
@tjoyal Its been while since experiencing this but I think our issues were being triggered through both web requests or background processes. After database connection loss the application throw the `PG::UnableToSend: no connection to the server` until restarted. The workaround I posted above has been working for us for about 6 months now without any more issues.

**Comment by bilbof** [comment]
I hit the same problem – what looks like dead connections in a pool not getting reaped when postgres or pgbouncer have a non-graceful exit.

From what I gather work is being done to improve the situation, but as it stands you can't currently rely on ActiveRecord quickly reconnecting in these situations, regardless of db.config like a lower `reaping_frequency`. Instead you need to force a reconnection with `ActiveRecord::Base.connection.reconnect!`.

Although it would be nice for it to be handled internally as described in https://github.com/rails/rails/issues/37092#issue-487643657, I tested the workaround with both postgres and pgbouncer (with a rails app running in kubernetes with a readiness probe like https://github.com/rails/rails/issues/38324#issuecomment-611560590) and it works great.  I can lose the primary postgres node and not have any downtime, just 15s query latency in the worst case.
