### ISSUE TITLE
cannot require file in lib folder

### ISSUE THREAD

**Issue by SampsonCrowley** [rails/rails#38343]
### Steps to reproduce

Follow the Docs: https://guides.rubyonrails.org/testing.html#using-separate-files

```ruby
# lib/test/authenticated_test_helper.rb
module AuthenticatedTestHelper
  def sign_in(email, password)
    post account_login_url(email: email, password: password)
  end

  def admin_sign_in(email, password)
    post admin_session_url(email: email, password: password)
  end
end
```

```ruby
# test/controllers/admin/samples_controller_test.rb
require 'test_helper'
require 'test/authenticated_test_helper' # << throws: `cannot load such file -- lib/test/authenticated_test_helper

module Admin
  module SamplesControllerTest < ActionDispatch::IntegrationTest
    ...
    ...
  end
end
```

### Expected behavior

It should find the file since it's defined in EXACTLY the location that's recommended

### Actual behavior

```bash
30: from -e:1:in `<main>'
        29: from -e:1:in `require'
        28: from /home/samps/.gem/ruby/2.6.5/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:54:in `load'
        27: from /home/samps/.gem/ruby/2.6.5/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:54:in `load'
        26: from /home/samps/sites/cannabislims/bin/rails:9:in `<main>'
        25: from /home/samps/.gem/ruby/2.6.5/gems/zeitwerk-2.2.2/lib/zeitwerk/kernel.rb:23:in `require'
        24: from /home/samps/.gem/ruby/2.6.5/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
        23: from /home/samps/.gem/ruby/2.6.5/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `require_with_bootsnap_lfi'
        22: from /home/samps/.gem/ruby/2.6.5/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
        21: from /home/samps/.gem/ruby/2.6.5/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `block in require_with_bootsnap_lfi'
        20: from /home/samps/.gem/ruby/2.6.5/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require'
        19: from /home/samps/.gem/ruby/2.6.5/gems/railties-6.0.2.1/lib/rails/commands.rb:18:in `<main>'
        18: from /home/samps/.gem/ruby/2.6.5/gems/railties-6.0.2.1/lib/rails/command.rb:46:in `invoke'
        17: from /home/samps/.gem/ruby/2.6.5/gems/railties-6.0.2.1/lib/rails/command/base.rb:69:in `perform'
        16: from /home/samps/.gem/ruby/2.6.5/gems/thor-1.0.1/lib/thor.rb:392:in `dispatch'
        15: from /home/samps/.gem/ruby/2.6.5/gems/thor-1.0.1/lib/thor/invocation.rb:127:in `invoke_command'
        14: from /home/samps/.gem/ruby/2.6.5/gems/thor-1.0.1/lib/thor/command.rb:27:in `run'
        13: from /home/samps/.gem/ruby/2.6.5/gems/railties-6.0.2.1/lib/rails/commands/test/test_command.rb:33:in `perform'
        12: from /home/samps/.gem/ruby/2.6.5/gems/railties-6.0.2.1/lib/rails/test_unit/runner.rb:39:in `run'
        11: from /home/samps/.gem/ruby/2.6.5/gems/railties-6.0.2.1/lib/rails/test_unit/runner.rb:50:in `load_tests'
        10: from /home/samps/.gem/ruby/2.6.5/gems/railties-6.0.2.1/lib/rails/test_unit/runner.rb:50:in `each'
         9: from /home/samps/.gem/ruby/2.6.5/gems/railties-6.0.2.1/lib/rails/test_unit/runner.rb:50:in `block in load_tests'
         8: from /home/samps/.gem/ruby/2.6.5/gems/zeitwerk-2.2.2/lib/zeitwerk/kernel.rb:23:in `require'
         7: from /home/samps/.gem/ruby/2.6.5/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
         6: from /home/samps/.gem/ruby/2.6.5/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `require_with_bootsnap_lfi'
         5: from /home/samps/.gem/ruby/2.6.5/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
         4: from /home/samps/.gem/ruby/2.6.5/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `block in require_with_bootsnap_lfi'
         3: from /home/samps/.gem/ruby/2.6.5/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require'
         2: from /home/samps/sites/cannabislims/test/controllers/admin/samples_controller_tests/authenticated_test.rb:2:in `<main>'
         1: from /home/samps/.gem/ruby/2.6.5/gems/zeitwerk-2.2.2/lib/zeitwerk/kernel.rb:23:in `require'
/home/samps/.gem/ruby/2.6.5/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:33:in `require': cannot load such file -- lib/test/authenticated_test_helper (LoadError)
```
### System configuration
**Rails version**: 6.0.2.1

**Ruby version**: 2.6.5p114 (2019-10-01 revision 67812) [x86_64-linux]

**Comment by SampsonCrowley** [comment]
If i change to `require 'lib/test/authenticated_test_helper'` nothing changes
but changing to `require Rails.root.join('lib', 'test', 'authenticated_test_helper')` suddenly it works

**Comment by eileencodes** [comment]
Your test helpers should live in `test/` not in `lib/`. `lib` is not autoloaded, which is why `require 'lib/test/authenticated_test_helper'` doesn't work.

You are right though the docs are confusing. I believe they wrote a typo and meant write to store your helpers in `test/lib`, I usually put them in `test/test_helper/`. 

I have fixed the documentation in e7514128a6a5ca11385abfa7f699cc4fd9ceefd1 and 9082609a33531cf671c62231712d9a21a7facef6. The guides will be updated on the next release of Rails.

---

As an aside, you have more than one issue open on this repo that feels a bit like you're yelling at us. I get that you're new to Rails and are frustrated, but most of the folks here are volunteers and no one is purposefully making your life hard. ❤️

**Comment by SampsonCrowley** [comment]
@eileencodes what's the point of the lib folder if I can't require files from it? that has always been the standard folder to place code that doesn't belong in `app`

**Comment by SampsonCrowley** [comment]
@eileencodes I don't see how opening a separate issue when I find one is yelling at you. I have been using rails since rails 3. I don't see anything in either issue where I'm blaming anyone or getting angry, but i am starting to get sick of library maintainers taking bug reports as personal attacks

**Comment by eileencodes** [comment]
> but i am starting to get sick of library maintainers taking bug reports as personal attacks

If this happens a lot consider whether you're contributing to that? 

It's the all caps you're using on multiple issues I take issue with, not opening new issues. I asked you super nicely to chill a little, that's all. 😕

**Comment by SampsonCrowley** [comment]
Capital letters are for **emphasis** not because I'm angry about it

**Comment by SampsonCrowley** [comment]
I wasn't upset even in the slightest until you decided to take this discussion off-topic over one capital word. I have *never* assumed someone was angry at me for trying to report a bug in any of the libraries I maintain, so I get irked when someones else's first response to someone trying to help improve the library is "pull requests welcome" (no shit it's open source. we know, we're just trying to make you aware of the issue) or the *assumption* that because we found an error we're mad about it or expect a free library to be perfect
