### ISSUE TITLE
has_many :through no longer works with UUID primary keys or custom type PKs

### ISSUE THREAD

**Issue by travisp** [rails/rails#38340]
### Steps to reproduce
Create an application using ActiveStorage and UUIDs

Sample application modeled off guide:

https://github.com/travisp/sample-activestorage-app

Run a server, and then visit /users/new and try to create a user with an avatar attached.

### Expected behavior
Everything works correctly. The official Ruby on Rails guide for Active Storage suggests that UUIDs can be used.

### Actual behavior
Error is received while trying to create attachment:
```
In order to correctly type cast User.id, ActiveStorage::Blob needs to define a :avatar_attachment association.
```

Trace:
```
rails (f207e00eb25b) activerecord/lib/active_record/reflection.rb:772:in `block in klass'
rails (f207e00eb25b) activerecord/lib/active_record/reflection.rb:767:in `tap'
rails (f207e00eb25b) activerecord/lib/active_record/reflection.rb:767:in `klass'
rails (f207e00eb25b) activerecord/lib/active_record/associations/association.rb:139:in `klass'
rails (f207e00eb25b) activerecord/lib/active_record/associations/association.rb:246:in `find_target?'
rails (f207e00eb25b) activerecord/lib/active_record/associations/association.rb:163:in `load_target'
rails (f207e00eb25b) activerecord/lib/active_record/associations/association.rb:68:in `reload'
rails (f207e00eb25b) activerecord/lib/active_record/associations/singular_association.rb:9:in `reader'
rails (f207e00eb25b) activerecord/lib/active_record/associations/builder/association.rb:102:in `avatar_blob'
rails (f207e00eb25b) activestorage/lib/active_storage/attached/changes/create_one.rb:42:in `public_send'
rails (f207e00eb25b) activestorage/lib/active_storage/attached/changes/create_one.rb:42:in `find_attachment'
rails (f207e00eb25b) activestorage/lib/active_storage/attached/changes/create_one.rb:38:in `find_or_build_attachment'
rails (f207e00eb25b) activestorage/lib/active_storage/attached/changes/create_one.rb:15:in `attachment'
rails (f207e00eb25b) activestorage/lib/active_storage/attached/changes/create_one.rb:32:in `save'
```

If ActiveStorage::Blob is monkey patched to have an avatar_attachment association, a new error appears between variant and blob:

NotImplementedError (In order to correctly type cast ActiveStorage::VariantRecord.id, ActiveStorage::Blob needs to define a :image_attachment association.):

### System configuration
**Rails version**: 6.1.0.alpha, ref: "f207e00"
In rails 6.0.2, this error did not occur

**Ruby version**: 2.7.0

### Other notes:
This is related to this bug report https://github.com/rails/rails/issues/36984 and was reported in a comment https://github.com/rails/rails/pull/36847#issuecomment-521897696
There was a fix https://github.com/rails/rails/pull/37120 but it did not fix activestorage

**Comment by travisp** [comment]
BTW, I'm unsure if this should be 1) considered an ActiveStorage issue, 2) considered an issue with the changes for rails 6.1 in #36847 that were not very UUID friendly, or 3) if UUIDs are not to be considered supported for ActiveStorage primary keys. If someone can help by pointing me to what might be the best resolution of this, I'd be happy to take a stab at creating a PR to fix it.

**Comment by crispinheneise** [comment]
I think this must be related to #36847, which raises an exception on all has_many :through associations when the pk is a uuid.

**Comment by crispinheneise** [comment]
Here's a test script to reproduce the error: 

```rb
# frozen_string_literal: true

require 'bundler/inline'

gemfile(true) do
  source 'https://rubygems.org'

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  # Activate the gem you are reporting the issue against.
  gem 'rails', github: 'rails/rails'
  gem 'pg'
end

require 'active_record'
require 'minitest/autorun'
require 'logger'

`dropdb active_record_gem_template`
`createdb -E UTF8 -T template0 active_record_gem_template`

# This connection will do for database-independent bug reports.
ActiveRecord::Base.establish_connection(adapter: 'postgresql', database: 'active_record_gem_template')
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  enable_extension 'pgcrypto'

  create_table :documents, id: :uuid, force: true do |t|
  end

  create_table :sections, id: :uuid, force: true do |t|
    t.references :document, null: false, foreign_key: true, type: :uuid
  end

  create_table :paragraphs, id: :uuid, force: true do |t|
    t.references :section, null: false, foreign_key: true, type: :uuid
  end
end

class Document < ActiveRecord::Base
  has_many :sections
  has_many :paragraphs, through: :sections
end

class Section < ActiveRecord::Base
  belongs_to :document
  has_many :paragraphs
end

class Paragraph < ActiveRecord::Base
  belongs_to :section
end

class BugTest < Minitest::Test
  def test_document_has_many_paragraphs_through_sections
    document = Document.create!
    section =  Section.create!(document: document)
    paragraph =  Paragraph.create!(section: section)

    assert_equal 1, document.sections.count
    assert_equal 1, document.paragraphs.count
  end
end
```

**Comment by crispinheneise** [comment]
Here's a link to the block that's causing the error: 

https://github.com/rails/rails/blob/99b607e6ad681b17de40d6cc55aa3af7989305db/activerecord/lib/active_record/reflection.rb#L772-L780

**Comment by crispinheneise** [comment]
@travisp I think this is an ActiveRecord issue related to that PR you mentioned, unrelated to ActiveStorage.

**Comment by ekampp** [comment]
I raised [my concerns](https://github.com/rails/rails/pull/36847#issuecomment-522696484) about that specific if-statement that @crispinheneise [mentions here](https://github.com/rails/rails/issues/38340#issuecomment-598953255) before because it seems disproportionately complex and the tests surrounding the code are sparse, so any changes here will almost inevitably have unforeseen consequences.

**Comment by jeremy** [comment]
Anyone familiar with the issue feeling motivated to work up a PR that expand support for non-integer PKs?

**Comment by gmcgibbon** [comment]
For historical context, this is all rooted in this problem: https://github.com/rails/rails/issues/35839#issuecomment-480064841

While you can subclass or monkey patch `ActiveStorage::Blob` and add the association to fix this problem, it is inconvenient to do so. Regarding the test case in https://github.com/rails/rails/issues/38340#issuecomment-598952864, that appears to be a case where we need to singularize the name to inflect properly. I'll take a closer look at this 🤔 

The problem with non-integer types is we don't know if they need to be quoted or not. We can flip the logic on its head and permit everything _except_ cases where we know quoting is needed (eg. binary PKs), but that doesn't seem quite right to me. We should be raising if we can't resolve the type information for the through relation.

**Comment by crispinheneise** [comment]
@gmcgibbon I think you are right. When the relationship is a `has_many through` shortcut, the value of the key in `klass.reflections` is singular. 

I did an experiment by adding a condition to singularize `options[:through]`, and it worked as expected. However, I'm not sure if this is the best way because it adds another line of complexity to an already complex statement: 

```rb
    @klass ||= delegate_reflection.compute_class(class_name).tap do |klass|
      if !parent_reflection.is_a?(HasAndBelongsToManyReflection) &&
         !(klass.reflections.key?(options[:through].to_s) ||
           (klass.reflections.key?(options[:through].to_s.pluralize) ||
            klass.reflections.key?(options[:through].to_s.singularize))) && # << Singularize
         active_record.type_for_attribute(active_record.primary_key).type != :integer
        raise NotImplementedError, <<~MSG.squish
          In order to correctly type cast #{active_record}.#{active_record.primary_key},
          #{klass} needs to define a :#{options[:through]} association.
        MSG
      end
    end
```

**Comment by gmcgibbon** [comment]
I made a test case to capture the issue a little more precisely:

```ruby
# frozen_string_literal: true

require 'bundler/inline'

gemfile(true) do
  source 'https://rubygems.org'

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  # Activate the gem you are reporting the issue against.
  gem 'rails', path: '../rails'
  gem 'sqlite3'
  gem 'byebug'
end

require "active_record"
require "active_storage/engine"
require "minitest/autorun"
require "logger"

ROOT = Pathname.new(__dir__)

class Dummy < Rails::Application; end

Rails.configuration.tap do |config|
  config.eager_load = false
  config.logger = Logger.new(STDOUT)

  config.class_eval do
    def database_configuration
      { development: { adapter: "sqlite3", database: ":memory:" } }
    end
  end

  config.active_storage.service_configurations = {
    development: { service: "Disk", root: ROOT.join("tmp/storage") }
  }
  config.active_storage.service = :development
end

Rails.application.initialize!

ActiveRecord::Schema.define do
  def binary_id
    ActiveRecord::Base.connection.quote(SecureRandom.uuid)
  end

  create_table :users, id: :binary, default: -> { binary_id } do |t|
    t.timestamps
  end

  create_table :active_storage_blobs do |t|
    t.string   :key,          null: false
    t.string   :filename,     null: false
    t.string   :content_type
    t.text     :metadata
    t.string   :service_name, null: false
    t.bigint   :byte_size,    null: false
    t.string   :checksum,     null: false
    t.datetime :created_at,   null: false

    t.index [ :key ], unique: true
  end

  create_table :active_storage_attachments do |t|
    t.string     :name,     null: false
    t.references :record,   null: false, polymorphic: true, index: false, type: :binary
    t.references :blob,     null: false

    t.datetime :created_at, null: false

    t.index [ :record_type, :record_id, :name, :blob_id ], name: "index_active_storage_attachments_uniqueness", unique: true
    t.foreign_key :active_storage_blobs, column: :blob_id
  end

  create_table :active_storage_variant_records do |t|
    t.belongs_to :blob, null: false, index: false
    t.string :variation_digest, null: false

    t.index %i[ blob_id variation_digest ], name: "index_active_storage_variant_records_uniqueness", unique: true
    t.foreign_key :active_storage_blobs, column: :blob_id
  end
end

class User < ActiveRecord::Base
  has_one_attached :avatar
end

class BugTest < Minitest::Test
  def test_through_cast
    avatar = ROOT.join("tmp", "image.png")
    user = User.create!
    user.avatar.attach(io: avatar.open, filename: "image.png")
    blob = user.avatar.blob

    assert_equal blob, user.reload.avatar_blob
  end
end
```
This revealed two interesting this:

1. From the reflection point in the predicate builder mentioned in https://github.com/rails/rails/issues/35839#issuecomment-480064841, we are trying to inflect on the table name, which is `active_storage_attachments`. Because the table name is prefixed and the associations aren't, there's no way this can work AFAICT.

2. Later down the line, the column type is inferred [here](https://github.com/rails/rails/blob/dd2acd5ec6d747ee4be00d9125e93c1a1a6dd8a7/activerecord/lib/active_record/relation/predicate_builder.rb#L60), which makes casting work in my test case (and probably 99% of usages of Active Storage using non-int IDs). The case  I'm concerned about [here](https://github.com/rails/rails/blob/99b607e6ad681b17de40d6cc55aa3af7989305db/activerecord/lib/active_record/reflection.rb#L772-L780) is when the type cannot be inferred by the table's column type. The logic is wrong, we only need to raise this error when the PK attribute type has been overridden. That should significantly cut down on false positives.

**Comment by josh-m-sharpe** [comment]
I just just testing the new proxy helpers for ActiveStorage using 6.1.0-alpha (00c2d3e1e61093451a00b1b70548cfd9ae549c53) and ran into this issue.

Should this issue be added to the 6.1 milestone? https://github.com/rails/rails/issues?q=is%3Aopen+is%3Aissue+milestone%3A6.1.0
