### ISSUE TITLE
Flash doesn't disappear when redirected

### ISSUE THREAD

**Issue by oshiro3** [rails/rails#38344]
### Steps to reproduce

rails 5 had worked as expected, but the following phenomenon occurred by updating to rails 6.

* Create a session using the following
  * sessions_controller.rb

  ```ruby
  def signin
  if authentication
    redirect_to :root
  else
    case error
    when INVALID_CREDENTIAL  then
      redirect_to :sessions, alert: "invalid credential"
      return
    when INVALID_ACCOUNT then
      redirect_to :sessions, alert: "this account is invalid"
      return
    end
  end
  ```

  * application.html.erb

  ```ruby
    <% if notice %>
      <p class="alert alert-success">
      <%= notice %>
      </p>
    <% elsif alert %>
      <p class="alert alert-danger"><%= alert %></p>
    <% end %>
  ```

* Session management is implemented by redis.
* Occurs when updating to rails5.2 -> 6.

### Expected behavior

* Alert is displayed if signin fails, but alert is not displayed if signin is successful.

### Actual behavior

* The alert will display once you fail to signin, and it never disappear.
* Alert messages are updated when new alerts occur.

### System configuration

**Rails version**: 6.0.2.1

**Ruby version**: 2.6.0

### Interim measures

* The alert message was deleted by the following method, but it is not the same operation as rails5.

```ruby
def success_signin(info)
  ...
  xxx
  ...
  flash[:alert] = nil
end
```

**Comment by tekniklr** [comment]
Seeing the same behavior. Also using redis, rails 6.0.2.1, ruby 2.6.3.

**Comment by tekniklr** [comment]
Update, seems to be related to a commit of redis-rack that was later reverted ( https://github.com/redis-store/redis-rack/commit/ea734a2dfcdad68fa100fd60ae094c7c2242bdda )

`gem 'redis-rack', '=2.1.0'` causes flash to clear again as expected!

**Comment by oshiro3** [comment]
Thank you for investigating the cause.
Changing the version of redis-rack as per the comment now works as expected.

**Comment by kamipo** [comment]
Closing since this is not Rails issue.
