### ISSUE TITLE
Rails New 6.0.2.1 rails_ujs is not working out of the box

### ISSUE THREAD

**Issue by cgibsonmm** [rails/rails#38353]
### Steps to reproduce
``` 
$ rails new App
$ rails g scaffold Item title
$ rails db:migrate
```

head to your Item create an Item and then try to delete it through the link built by the scaffold Unless I am missing something Rails_UJS is not working right. For me, the only thing that happens is Rails links to the item path, but it never calls the js functions 

### Expected behavior
When I generate a new project and scaffold a table Rails should build a view with ujs built in the JS.

### Actual behavior
Clicking on a delete link just routs to the item and does not run the JS

### System configuration
**Rails version**:
Rails 6.0.2.1

**Ruby version**:
Ruby 2.6.5p114

**Comment by vipulnsward** [comment]
This works as expected on Rails 6.0.2.1 (Following the steps you posted): https://monosnap.com/file/m4jsJL7yfS5d8XmQx48owxAIo2CBPT

You can push a sample application to GitHub that others can check for any specific issues with your application.
