### ISSUE TITLE
ActionController: Restful downloads feature produces HTML rather than expected content

### ISSUE THREAD

**Issue by joallard** [rails/rails#38364]
### Steps to reproduce
Given the following controller action served at `/records`:

```rb
class RecordsController < ApplicationController
  def index
    respond_to do |format|
      format.html
      format.csv{ render csv: "foo,bar\n1,2" }
    end
  end
end
```

And given `app/views/records/index.html.erb` exists,

When I visit `/records.csv`

### Expected behavior
`"foo,bar\n1,2"` is served with `Content-type: text/csv`

### Actual behavior
`ActionView::MissingTemplate` is raised

> `Missing template records/index, application/index with {:locale=>[...], :formats=>[:csv], :variants=>[], :handlers=>[:raw, :erb, :html, :builder, :ruby, :coffee, :jbuilder, :haml]}`

### System configuration
**Rails version**: 6.0.2.1
**Ruby version**: 2.6.3

---

Alternate case:

```gherkin
Given the same controller
Given 'app/views/records/index.haml' exists  # Not .html.haml
When I visit /records.csv
Then view 'index.haml' is served
```

---

The test case reflects the usage the ActionController documentation on ["Restful downloads"](https://guides.rubyonrails.org/action_controller_overview.html#restful-downloads) recommends.

It is quite unintuitive to go looking for a template view when content is provided with a string.

It also confused [this Stackoverflow user](https://stackoverflow.com/questions/7682096/rails-restful-downloads) in 2011.

I would also suggest that the API documentation on `#render` is a bit unclear on a lot of things, including a case like this. It does however suggest that calling `render html: string` or `render json: string` will render that string.

I do understand that there is some question about the logic of looking for a view or not. I would opine that when content is provided directly, it should not render a view.

Current workaround: Using `send_data` and re-specifying filename and mime-type manually.

**Comment by fabriziobertoglio1987** [comment]
`ActionController::Renderers.add` will add each mime type

This is done inside [`ActionController::Renderers`][1] for `:json`, `:js` and `:xml`.

```ruby
add :js do |js, options|
  self.content_type = Mime[:js] if media_type.nil?
  js.respond_to?(:to_js) ? js.to_js(options) : js
end
```

The `self.add` method includes comments explaining how to create a `csv` rendered. I summarize

```ruby
# Creates a csv renderer
ActionController::Renderers.add :csv do |obj, options|
  filename = options[:filename] || 'data'
  str = obj.respond_to?(:to_csv) ? obj.to_csv : obj.to_s
  send_data str, type: Mime[:csv],
    disposition: "attachment; filename=#{filename}.csv"
end
```

then you can use the `csv` renderer in a controller action as explained [here][3]

```ruby
def show
 @csvable = Csvable.find(params[:id])
 respond_to do |format|
   format.html
   format.csv { render csv: @csvable, filename: @csvable.name }
 end
end
```
Probably I am wrong, but I wanted to help. Please correct me.

[1]: https://github.com/rails/rails/blob/master/actionpack/lib/action_controller/metal/renderers.rb#L156-L180
[2]: https://github.com/rails/rails/blob/master/actionpack/lib/action_controller/metal/renderers.rb#L75-L78
[3]: https://github.com/rails/rails/blob/master/actionpack/lib/action_controller/metal/renderers.rb#L66-L74

**Comment by vipulnsward** [comment]
Yes, this is not a `respond_to` or restful issue. If you have:

```ruby
def index
   render csv: "foo,bar\n1,2" 
end
```
If will still fail, since it did not find suitable template to render, or a proper renderer to support the string -> csv render you were expecting out of the box.

> Current workaround: Using send_data and re-specifying filename and mime-type manually.

This or adding a renderer would solve your issue. We can improve the docs on this probably, will close for now.

**Comment by joallard** [comment]
Yep, the docs are pretty much wrong on this for now.
