### ISSUE TITLE
Rails error with 500 error page in development with duplicate data attributes

### ISSUE THREAD

**Issue by salex** [rails/rails#38368]
### Steps to reproduce

This is a user error(me), but thought I'd point it out

Don't know is it is Rails or Slim, but I made a mistake in changing an element in a slim template.

The element was:

```
   progress.w3-white[value="0" max="30" id="progressBar" style="width:100%"
      data-target="pickTicket.progressBar" 
      data-action="load->pickTicket#startTimer"]
```
This is using Stimulus.js and had a problem using getElementById and changed it to a data-target, but forgot I already had it in the element.

```
    progress.w3-white[value="0" max="30" data-target="pickTicket.progressBar" style="width:100%"
      data-target="pickTicket.progressBar" 
      data-action="load->pickTicket#startTimer"]
```
So I had two data-target="pickTicket.progressBar"

Rails balked, not just with an error, but a public 500.error page in development.

Took a little while to find it in that the log did not give much help in finding the problem,
Removing the duplicate made things right. I also posted this on the Rails-Slim GitHub page.

### Expected behavior

A pretty error page telling me where to find the error:-)

### System configuration
**Rails version**:  6.0.2.1

**Ruby version**:  2.5.3

**Comment by eileencodes** [comment]
Thanks for the report @salex - this was fixed in #38222
