### ISSUE TITLE
ActiveSupport::CurrentAttributes with name attribute causes stack level too deep error

### ISSUE THREAD

**Issue by tommyschaefer** [rails/rails#38369]
Hi there! 😄

I was experimenting with `ActiveSupport::CurrentAttributes` this afternoon and was puzzled for a while with a `stack level too deep` error. After tinkering a bit, I was able to narrow it down to a specific case...

### Steps to reproduce

```ruby
# frozen_string_literal: true

require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  gem "activesupport", "6.0.0"
end

require "active_support"
require "active_support/core_ext/object/blank"
require "minitest/autorun"

class CurrentlyWorking < ActiveSupport::CurrentAttributes
  attribute :name_
end

class CurrentlyNotWorking < ActiveSupport::CurrentAttributes
  attribute :name
end

class BugTest < Minitest::Test
  def test_currently_working
    CurrentlyWorking.name_ = "a name"

    assert_equal "a name", CurrentlyWorking.name_
  end

  # Produces SystemStackError: stack level too deep
  def test_currently_not_working
    CurrentlyNotWorking.name = "a name"

    assert_equal "a name", CurrentlyNotWorking.name
  end
end
```

### Expected behavior

I was initially expecting this to work with no error, but after looking into the [implementation](https://github.com/rails/rails/blob/cb6f25c7578911d21476aa65ef324a98e72008fc/activesupport/lib/active_support/current_attributes.rb#L98) a bit, it seems like this might be related to the use of `name` in the definition of `attribute`. I haven't confirmed this, so I'm not 100% confident that this is the actual issue. If it is, I would probably expect one of:

  - `name` is an allowed attribute that does not cause a `stack level too deep error`

  - `name` is a reserved attribute and an error is raised if you try and use it, similar to [`ActiveRecord::DangerousAttributeError`](https://github.com/rails/rails/blob/6504d51a78a86a0994aa0f461e769e68d217361f/activerecord/lib/active_record/attribute_methods.rb#L83)s or [reserved app names](https://github.com/rails/rails/blob/fe006083ea0843ee37fb0259fb706a9ac5562066/railties/lib/rails/generators/app_name.rb#L40-L43).

### Actual behavior

A `SystemStackError` is raised. When running the `BugTest` above, I got the following output.

```
Fetching gem metadata from https://rubygems.org/...............
Resolving dependencies...
Using concurrent-ruby 1.1.5
Using i18n 1.8.2
Using minitest 5.14.0
Using thread_safe 0.3.6
Using tzinfo 1.2.6
Using zeitwerk 2.2.2
Using activesupport 6.0.0
Using bundler 2.1.2
Run options: --seed 63846

# Running:

E.

Finished in 0.004777s, 418.6728 runs/s, 209.3364 assertions/s.

  1) Error:
BugTest#test_currently_not_working:
SystemStackError: stack level too deep
    /Users/tommyschaefer/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/activesupport-6.0.0/lib/active_support/current_attributes.rb:94:in `instance'
    /Users/tommyschaefer/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/activesupport-6.0.0/lib/active_support/current_attributes.rb:113:in `block (2 levels) in attribute'
    /Users/tommyschaefer/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/activesupport-6.0.0/lib/active_support/current_attributes.rb:94:in `instance'
    /Users/tommyschaefer/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/activesupport-6.0.0/lib/active_support/current_attributes.rb:113:in `block (2 levels) in attribute'
    ...
    /Users/tommyschaefer/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/activesupport-6.0.0/lib/active_support/current_attributes.rb:117:in `block (2 levels) in attribute'
    test_case.rb:33:in `test_currently_not_working'

2 runs, 1 assertions, 0 failures, 1 errors, 0 skips
```

### System configuration
**Rails version**: `Rails 6.0.2.1`

**Ruby version**: `ruby 2.7.0p0 (2019-12-25 revision 647ee6f091) [x86_64-darwin19]`

---

Thank you so much for your time! I really appreciate it 😄

**Comment by kaspth** [comment]
Thanks, let’s consider `name` out of bounds for a current attribute since it’s already a method on class or module. Don’t think it’s worth the extra code to warn about this ✌️

**Comment by danielricecodes** [comment]
@kaspth - I think you should reconsider this and let others attempt to fix this.  There is nothing wrong with having a field on any ActiveRecord model called `name`.  In fact, I'd argue it is probably one of *the most common* attribute names there is.

In my case, I ran into this unfortunate bug serializing an AR model with `has_one_attached`.  Simply ignoring the ActiveStorage attachment worked.  

```
[1] pry(main)> Item.first.as_json
  Item Load (0.6ms)  SELECT "items".* FROM "items" ORDER BY "items"."id" ASC LIMIT $1  [["LIMIT", 1]]
  ActiveStorage::Attachment Load (0.6ms)  SELECT "active_storage_attachments".* FROM "active_storage_attachments" WHERE "active_storage_attachments"."record_id" = $1 AND "active_storage_attachments"."record_type" = $2 AND "active_storage_attachments"."name" = $3 LIMIT $4  [["record_id", 1], ["record_type", "Item"], ["name", "photo"], ["LIMIT", 1]]
  ActiveStorage::Blob Load (0.6ms)  SELECT "active_storage_blobs".* FROM "active_storage_blobs" WHERE "active_storage_blobs"."id" = $1 LIMIT $2  [["id", 10], ["LIMIT", 1]]
SystemStackError: stack level too deep
from /Users/danielrice/.rvm/gems/ruby-2.6.6@myportertwooh/gems/activerecord-6.0.3.2/lib/active_record/attribute_methods/primary_key.rb:49:in `attribute_method?'
[2] pry(main)> Item.first.as_json(except: :photo)
  Item Load (0.6ms)  SELECT "items".* FROM "items" ORDER BY "items"."id" ASC LIMIT $1  [["LIMIT", 1]]
=> {"id"=>1,
 "user_id"=>5,
 "name"=>"Domestic robot",
 "description"=>"Hodor? Hodor.",
 "created_at"=>"2020-08-13T23:31:20.703-04:00",
 "updated_at"=>"2020-08-13T23:31:20.716-04:00",
 "migrated_at"=>nil}
```

**Comment by kaspth** [comment]
Yeah, it's fine on Active Records and that works, doesn't it? Here we're talking about ActiveSupport::CurrentAttributes though, which is quite different.

You're welcome to investigate the Active Storage issue in another issue.

**Comment by simi** [comment]
> let’s consider name out of bounds for a current attribute since it’s already a method on class or module. Don’t think it’s worth the extra code to warn about this 

@kaspth :thinking: this approach makes this concern (ActiveSupport::CurrentAttributes) really hard to use in my eyes since it is potentially full of surprises like this one. I'm using Rails (also) for having high-quality code baked in only and well maintained. Current `CurrentAttributes` implementations looks more a concept to me.

I think it should be considered to:
1. make it first class citizen and fix reported problems (like this one, at least with comment in documentation, warning on reserved name used or better to prevent any conflicts with alternative implementation)
2. gemify this and remove from Rails codebase

_PS: I'm not sure this is the best place to discuss this. Should I better open this topic at forums?_

**Comment by kaspth** [comment]
Not every Rails user has to use everything in Rails or even agree with particulars of it. Core has vouched for this, and what level we'd like to maintain here. Thanks.

**Comment by simi** [comment]
Sure, those were just my 2 cents on this.
