### ISSUE TITLE
Querying for `.not(attribute: [nil, ""])` on DATETIME always brings back no results in Rails > 5.2

### ISSUE THREAD

**Issue by jsilasbailey** [rails/rails#38360]
### Steps to reproduce
~Seems to be only an issue when running on mariadb as it doesn't occur with postgres.~
When querying for records that have a *non-empty* AND *non-null* attribute on a column that is

~1. Of type `VARCHAR`~
1. Of type `datetime`
2. `NULL`-able

No records are ever returned despite records existing that should be returned. 
Also, even if you just want to query for records with an empty attribute, `where(attribute: "")`, incorrect SQL is generated.

Is this a choice in behavior or unexpected?
Rails before version ~6~ 5.2 generates expected SQL below.

### Expected behavior
```ruby
Model.where.not(datetime_attribute: [nil, ""]).to_sql
#=> SELECT ... WHERE NOT (datetime_attribute IS NULL OR datetime_attribute = "")
```
```ruby
Model.where(datetime_attribute: "").to_sql
#=> SELECT ... WHERE datetime_attribute = ""
```

### Actual behavior
```ruby
Model.where.not(datetime_attribute: [nil, ""]).to_sql
#=> SELECT ... WHERE NOT (datetime_attribute IS NULL OR datetime_attribute = NULL)
```
```ruby
Model.where(datetime_attribute: "").to_sql
#=> SELECT ... WHERE datetime_attribute = NULL
```

### System configuration
**Rails version**: : 6.0.2.1

**Ruby version**: 2.5.7

**MariaDb version**: 10.1

**Comment by kamipo** [comment]
Can you provide a reproduction script with this template https://github.com/rails/rails/blob/master/guides/bug_report_templates/active_record_master.rb?

**Comment by fabriziobertoglio1987** [comment]
```ruby
Model.where(attribute: "").to_sql
#=> SELECT ... WHERE attribute = NULL
```

The issue may be related to the module `ActiveRecord::Sanitization::ClassMethods` method [.quote_bound_value][2] 

```ruby
Model.connection
=> #<ActiveRecord::ConnectionAdapters::PostgreSQLAdapter:0x00007fee4044d140
 @config=
  {:adapter=>"postgresql",
   :host=>"localhost",
   :encoding=>"unicode",
   :pool=>10,
   :timeout=>5000,
   :database=>"db/development_surfcheck"},
 @connection=#<PG::Connection:0x00007fee40426338>,
Model.send(:sanitize_sql_for_conditions, (["attribute=?", ""]))
=> "attribute=''"
```
as explained in this [comment][1] in postgresql connection [`.quote_bound_value`][2] return `NULL` for `nil`

```ruby
=> #<ActiveRecord::ConnectionAdapters::PostgreSQLAdapter:0x00007fee4044d140
 @config=
  {:adapter=>"postgresql",
   :host=>"localhost",
   :encoding=>"unicode",
   :pool=>10,
   :timeout=>5000,
   :database=>"db/development_surfcheck"},
 @connection=#<PG::Connection:0x00007fee40426338>,
Model.connection.quote(nil)
=> NULL
```
I guess `Mariadb` returns `""` for `nil`

```ruby
Model.connection.quote(nil)
=> ""
```

The [`_quote`][5] method from in `ActiveRecord::ConnectionAdapter::Quoting` is responsible for converting the `nil` into `"NULL"` for postgresql.

```ruby
def _quote(value)
  case value
  when String, ActiveSupport::Multibyte::Chars, Type::Binary::Data
    "'#{quote_string(value.to_s)}'"
  when true       then quoted_true
  when false      then quoted_false
  when nil        then "NULL"
  # BigDecimals need to be put in a non-normalized form and quoted.
  when BigDecimal then value.to_s('F')
  when Numeric, ActiveSupport::Duration then value.to_s
  when Type::Time::Value then "'#{quoted_time(value)}'"
  when Date, Time then "'#{quoted_date(value)}'"
  when Symbol     then "'#{quote_string(value.to_s)}'"
  when Class      then "'#{value}'"
  else raise TypeError, "can't quote #{value.class.name}"
  end
end
```

The key to the solution may be in the [`mysql/quoting.rb` blame][6]
I would be happy to receive some feedback. Thanks
I currently don't know the solution to this issue and I did not run a test example with mariadb

[1]: https://github.com/rails/rails/issues/35135#issuecomment-459938507
[2]: https://github.com/rails/rails/blob/5-0-stable/activerecord/lib/active_record/sanitization.rb#L206-L216
[3]: https://github.com/rails/rails/blob/ac6aa32f7cf66264ba87eabed7c042bb60bcf3a2/activerecord/lib/active_record/connection_adapters/abstract/quoting.rb#L9-L21
[4]: https://github.com/rails/rails/blob/ac6aa32f7cf66264ba87eabed7c042bb60bcf3a2/activerecord/lib/active_record/connection_adapters/abstract/quoting.rb#L4
[5]: https://github.com/rails/rails/blob/master/activerecord/lib/active_record/connection_adapters/abstract/quoting.rb#L217-L233
[6]: https://github.com/rails/rails/blame/master/activerecord/lib/active_record/connection_adapters/mysql/quoting.rb

**Comment by jsilasbailey** [comment]
I went back and looked at this again and I realized the report was wrong and the column type was `datetime` not `varchar`

To me that means the results make _slightly_ more sense in some ways, but also I might expect there to still be results for the case below?

```ruby
# frozen_string_literal: true

require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  gem "rails", "~> 5.2.0"
  gem 'sqlite3', '~> 1.3.6'
end

require "active_record"
require "minitest/autorun"
require "logger"

# This connection will do for database-independent bug reports.
ActiveRecord::Base.establish_connection(adapter: "sqlite3", database: ":memory:")
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :posts, force: true do |t|
  end

  create_table :comments, force: true do |t|
    t.integer :post_id
    t.datetime :reposted_at, null: true
  end
end

class Post < ActiveRecord::Base
  has_many :comments
end

class Comment < ActiveRecord::Base
  belongs_to :post
end

class BugTest < Minitest::Test
  def test_reposted_comments
    post = Post.create!
    post.comments << Comment.create!(reposted_at: "")
    post.comments << Comment.create!(reposted_at: "")
    post.comments << Comment.create!(reposted_at: 1.day.ago)

    reposted_comments = Comment.where.not(reposted_at: [nil, ""])

    assert_equal(1, reposted_comments.count)
    # => Expected: 1, Got: 0
  end
end
```

**Comment by fabriziobertoglio1987** [comment]
You opened this issue because your mariadb database datetime column has some `blank` entries.  Below if your `comments` table:


![Screen Shot 2020-02-07 at 14 56 32](https://user-images.githubusercontent.com/24992535/74035205-23b48800-49ba-11ea-97e1-94de0309849a.png)

I read this post from [Tim Biegeleisen][1] saying that mariadb columns can not be empty strings.

>If the column is `datetime`, then assigning empty string is simply **not permitted**. Most likely, the queries were running previously because InspectionDate was a text column.

Tim Biegelesen quotes the mariadb [datetime][2] documentation.

If you run your example, you will see that those columns are stores as `nil` and not `''`
Currently we do not have a reproducible example.

```ruby
pry> Comment.create!(reposted_at: "")
D, [2020-02-07T14:44:55.627573 #8505] DEBUG -- :    (0.1ms)  begin transaction
D, [2020-02-07T14:44:55.628308 #8505] DEBUG -- :   Comment Create (0.1ms)  INSERT INTO "comments" DEFAULT VALUES
D, [2020-02-07T14:44:55.628673 #8505] DEBUG -- :    (0.0ms)  commit transaction
=> #<Comment:0x00007fe5c654b538 id: 7, post_id: nil, reposted_at: nil>
```
then 
```ruby
pry> Comment.first
D, [2020-02-07T14:45:29.161163 #8505] DEBUG -- :   Comment Load (0.1ms)  SELECT  "comments".* FROM "comments" ORDER BY "comments"."id" ASC LIMIT ?  [["LIMIT", 1]]
=> #<Comment:0x00007fe5ca398228 id: 7, post_id: nil, reposted_at: nil>
```

This scenario could be reproduced by generating a `varchar` column and then changing the datatype to `datetime`. The previously empty strings would be stored as `''` in the `datetime` column, but I believe that is just a mistake in the database which should been accompanied with data migration and translating `''` into `null` values.

[1]: https://stackoverflow.com/a/41817700/7295772
[2]: https://mariadb.com/kb/en/datetime/

**Comment by jsilasbailey** [comment]
@fabriziobertoglio1987 I've satisfied the hypothesis that the column type was changed leaving empty values. The correct step in this instance was to `NULL` those out and change the query to be
```ruby
Model.where.not(attribute: nil)
```

I'll close this issue.

One last thing that is still slightly unsettling to me though is that you can break the results of the query by including the blank string when the attribute is backed by a datetime column
```ruby
Model.where.not(attribute: [nil, ""])
```
Though I suppose this case is rare enough it won't cause much trouble.

**Comment by fabriziobertoglio1987** [comment]
@jsilasbailey **thanks for the help**
