### ISSUE TITLE
Admin namespace stops being autovivified after some reloads

### ISSUE THREAD

**Issue by fxn** [rails/rails#38365]
[Opening a new issue with the contents of [this comment](https://github.com/rails/rails/issues/35475#issuecomment-581001842).]

Having eliminated all helpers with a name starting with ```admin_```,  I am still intermittently seeing this problem.  Below is a file with the output with ```Rails.autoloaders.log!``` enabled.

The exception occurs at line 556.  The file that is causing the exception contains the following:

```
module Admin::ProfessionalContactsHelper
end
```

This occurs intermittently when I start ```rails console```. It can also happen in a rspec test, but if I stop spring and rerun the test it is fixed.

I am not sure if it is related, but I am also having another[ issue ](https://stackoverflow.com/q/60014745/1299362)with the loading process.

[temp_zeitwert.txt](https://github.com/rails/rails/files/4142259/temp_zeitwert.txt)

**Comment by fxn** [comment]
@obromios which version of Ruby, Rails, and Zeitwerk?

The log that you attached has several reloads. Would it be possible to get a clean log when you start the console and this happens, for example? Or maybe you can trigger one doing

```
bin/rails runner Admin::ProfessionalContactsHelper
```

?

**Comment by obromios** [comment]
I have tried
`bin/rails runner Admin::ProfessionalContactsHelper`
and it does give
`uninitialized constant Admin`
but I do not see any output from autoloaders.log.  I do have this turned on, because when I run ```rails  s``` I do see the autoloader.log output.  I have checked the ```development.log``` and there is no autoloader output there either.

**Comment by fxn** [comment]
That is something, you should see traces in stdout.

Can we try with `spring` disabled just in case?

```
spring stop
export DISABLE_SPRING=1
```

**Comment by obromios** [comment]
I did forget to restart spring, so that fixed the lack of autoloaders.log output.  It also fixed the ```uninitialized constant Admin``` exception.  See attached file:
[temp_admin.txt](https://github.com/rails/rails/files/4150290/temp_admin.txt)
