### ISSUE TITLE
Add ActionCable::Channel.stream_or_reject_for

### ISSUE THREAD

**Issue by dhh** [rails/rails#38371]
This is a very common pattern:

```ruby
class MyChannel < ApplicationCable::Channel
  def subscribed
    if box = identity.boxes.find_by(id: params[:id])
      stream_for box
    else
      reject
    end
end
```

You're looking for a record based on a parameter, and if you find it, you'll start streaming. If the record isn't there, you reject the connection. We should extract `Add ActionCable::Channel.stream_or_reject_for` so you can just write:

```ruby
class MyChannel < ApplicationCable::Channel
  def subscribed
    stream_or_reject_for identity.boxes.find_by(id: params[:id])
end
```

Implementation:

```ruby
def stream_or_reject_for(record_or_nil)
  if record = record_or_nil
    stream_for record
  else
    reject
  end
end
```

Needs testing, documentation, etc.

**Comment by Atul9** [comment]
@dhh I would like take this up.

**Comment by dhh** [comment]
Have at it! You can reference this ticket in your PR 🙏❤️

On Sun, Feb  2, 2020 at  7:50 PM "github.com" <notifications@github.com> wrote:
“@dhh I would like take this up.
