### ISSUE TITLE
Enum scope combined with sum/pluck maybe more get unscoped.

### ISSUE THREAD

**Issue by kinnrot** [rails/rails#38373]
### Steps to reproduce
For a model with enumeration for example
```
class GameAsset < ApplicationRecord
  enum status: %i[draft pending approved]
end
```

Lets say we got 2 approved with 1 unit each and 1 draft. 
When running (units is integer)
>GameAsset.approved.sum(:units)
> returns 3
And 
>GameAsset.approved.sum(&:units)
>return 2
Expecting to get same result, but first one returns sum of all GameAsset, (its unscoped for some reason)

### Expected behavior
both should return 2 of the approved status only

### Actual behavior
when running sum as a part of the query, for some reason gets unscoped.

### System configuration
**Rails version**:
5.2.4.1

**Ruby version**:
2.6.5

**Comment by vipulnsward** [comment]
I am unable to reproduce this on the version you have specified(5.2.4.1): https://gist.github.com/vipulnsward/6a7270fba69db4cd95c60af88f974633

Do you have any other overriding scopes, etc?

**Comment by kinnrot** [comment]
> I am unable to reproduce this on the version you have specified(5.2.4.1): https://gist.github.com/vipulnsward/6a7270fba69db4cd95c60af88f974633
> 
> Do you have any other overriding scopes, etc?

See comment in gist

**Comment by vipulnsward** [comment]
You need to use `joins` instead of an `includes`(first one is a join other is an left outer join), which is causing the issue:

```
# frozen_string_literal: true

require 'bundler/inline'

gemfile(true) do
  source 'https://rubygems.org'

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  # Activate the gem you are reporting the issue against.
  gem 'activerecord', '5.2.4.1'
  gem 'sqlite3', '1.4.2'
end

require 'active_record'
require 'minitest/autorun'
require 'logger'

# This connection will do for database-independent bug reports.
ActiveRecord::Base.establish_connection(
    adapter: 'sqlite3', database: ':memory:'
)
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :authors, force: true do |t|
    t.string :name
  end

  create_table :posts, force: true do |t|
    t.integer :status
    t.integer :units, default: 1
    t.bigint 'author_id'
  end
end

class Post < ActiveRecord::Base
  enum status: %i[draft pending approved]
  belongs_to :author

  default_scope { order(:status, :id) }
end

class Author < ActiveRecord::Base
  has_many :posts
end

class BugTest < Minitest::Test
  def test_enum_stuff
    author = Author.create(name: 'x')
    Post.create!(author: author, status: Post.statuses[:draft])
    Post.create!(author: author, status: nil)
    Post.create!(author: author, status: Post.statuses[:approved])
    Post.create!(author: author, status: Post.statuses[:approved])

    assert_equal 2,
                 Post.includes(author: :posts).where('authors.id': 1).approved
                     .sum(&:units)
    assert_equal 2,
                 Post.joins(:author).where('authors.id': 1).approved
                     .sum(:units)
  end
end

```
