### ISSUE TITLE
Feature request: allow both up/down AND change in migrations

### ISSUE THREAD

**Issue by axos88** [rails/rails#38376]
Allow both up/down and change in migrations.

I find myself doing this quite often:

```
class AddReservationAcknowledged < ActiveRecord::Migration[5.2]
  def ch
    add_column :reservations, :acknowledged, :boolean, null: false, default: false
  end

  def up
    ch
    execute "UPDATE reservations SET acknowledged = true"
  end

  def down
    revert { ch }
  end
end
```

For this pattern to be reusable I would expect `up` and `down` to `yield` when the `change`  needs to be executed/reverted, like so:

```
class AddReservationAcknowledged < ActiveRecord::Migration[5.2]
  def change
    add_column :reservations, :acknowledged, :boolean, null: false, default: false
  end

  def up
    yield
    execute "UPDATE reservations SET acknowledged = true"
  end
end
```

If either up or down is not defined, only execute/revert the `change`.

**Comment by DmitryDrobotov** [comment]
The order is not clear then. Should it be `#change` and then `#up` or vice versa? What about rollback (`#down` -> `#change`)? 

From my point of view, migration is not a place that requires adherence to DRY. So, it much better to duplicate the things that add transparency.

**Comment by matthewd** [comment]
We added `up_only` to address this use case:

```ruby
class AddReservationAcknowledged < ActiveRecord::Migration[5.2]
  def change
    add_column :reservations, :acknowledged, :boolean, null: false, default: false

    up_only do
      execute "UPDATE reservations SET acknowledged = true"
    end
  end
end
```

(if you need both `up` and `down` variants, look at `reversible` instead.)
