### ISSUE TITLE
Issue for documentation - `RequestForgeryProtection` doc seems has wrong guide

### ISSUE THREAD

**Issue by HanguChoi** [rails/rails#38388]
There is a wrong guide in [RequestForgeryProtection comment](https://github.com/rails/rails/blob/08e4a71d02ee8556e5a7ebc4b0f8c364e0b8abd6/actionpack/lib/action_controller/metal/request_forgery_protection.rb) and [documentation](https://api.rubyonrails.org/classes/ActionController/RequestForgeryProtection.html)

```ruby
class ApplicationController < ActionController::Base
  protect_from_forgery unless: -> { request.format.json? }
end
```

> It is generally safe to exclude XHR requests from CSRF protection (like the code snippet above does), because XHR requests can only be made from the same origin.

However, as I know same origin policy cannot protect CSRF attack because [it does not prevent sending requests.](https://stackoverflow.com/a/33324803/2566679)

> ... one origin is permitted to send information to another origin, but one origin is not permitted to receive information from another origin   [Same Origin Policy
](https://www.w3.org/Security/wiki/Same_Origin_Policy)

If this is true, I think this guide must be modified, soon.

**Comment by Tomy0498** [comment]
`[class  ApplicationController <ActionController :: Base    protect_from_forgery a menos que:  -> {solicitud. formato .json? }  fin](https://github.com/rails/rails/issues/38388) `

**Comment by eugeneius** [comment]
Thanks for reporting this, I've opened https://github.com/rails/rails/pull/39488 to address it.
