### ISSUE TITLE
has_many with through: and dependent: :destroy options destroys join table

### ISSUE THREAD

**Issue by AlistairNorman** [rails/rails#38380]
### Steps to reproduce

In this example I create two models, books and authors, that are associated through the join table BookAuthor. I added an association to Author using the through: and dependent: :destroy options. I found the behaviour of dependent destroy to be unexpected because it destroys the BookAuthor instead of the Book when the Author is destroyed.

```ruby
# frozen_string_literal: true

require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  # Activate the gem you are reporting the issue against.
  gem "activerecord", "6.0.0"
  gem "sqlite3"
end

require "active_record"
require "minitest/autorun"
require "logger"

# This connection will do for database-independent bug reports.
ActiveRecord::Base.establish_connection(adapter: "sqlite3", database: ":memory:")
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table "authors", force: :cascade do |t|
    t.datetime "created_at", null: false
    t.datetime "updated_at", null: false
  end

  create_table "book_authors", force: :cascade do |t|
    t.integer "author_id"
    t.integer "book_id"
    t.datetime "created_at", null: false
    t.datetime "updated_at", null: false
    t.index ["author_id"], name: "index_book_authors_on_author_id"
    t.index ["book_id"], name: "index_book_authors_on_book_id"
  end

  create_table "books", force: :cascade do |t|
    t.datetime "created_at", null: false
    t.datetime "updated_at", null: false
  end
end

class Book < ActiveRecord::Base
  has_many :book_authors
  has_many :authors, through: :book_authors
end

class Author < ActiveRecord::Base
  has_many :book_authors
  has_many :books, through: :book_authors, dependent: :destroy
end

class BookAuthor < ActiveRecord::Base
  belongs_to :book
  belongs_to :author
end

class BugTest < Minitest::Test
  def test_association
    book = Book.create!
    author = Author.create!
    book_author = BookAuthor.create!(book_id: book.id, author_id: author.id)

    author.destroy

    # This test fails but I expected it to pass.
    assert_equal 0, Book.count
  end
end
```

### Expected behavior

I expected in this example that destroying an author would destroy a book.

### Actual behavior

It appears that using the dependent: :destroy and through: options on has_many associations causes the join table to be destroyed.

### System configuration

**ActiveRecord version**: 6.0.0

**Ruby version**: 2.6.1

**Comment by louim** [comment]
Hey!
This is the expected behavior, and it is documented here: [what gets deleted](https://api.rubyonrails.org/classes/ActiveRecord/Associations/ClassMethods.html#module-ActiveRecord::Associations::ClassMethods-label-What+gets+deleted-3F)

**Comment by AlistairNorman** [comment]
Ah, I couldn't find that documentation before. Thanks for the explanation!

**Comment by adammcnamara** [comment]
I think this violates the Principle of Least Surprise. The author explicitly declared that when the `Author` is deleted, their `Books` should be destroyed as well: `has_many :books, through: :book_authors, dependent: :destroy` That makes logical sense.

IMO, the `dependent` flag should not be ignored.
