### ISSUE TITLE
ActiveRecord::Associations::Preloader does not eager load with conditions

### ISSUE THREAD

**Issue by 23tux** [rails/rails#38395]
### Steps to reproduce

```
# active_record_master.rb
require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  gem "rails", github: "rails/rails"
  gem "sqlite3"
end

require "active_record"
require "minitest/autorun"
require "logger"

# This connection will do for database-independent bug reports.
ActiveRecord::Base.establish_connection(adapter: "sqlite3", database: ":memory:")
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :posts, force: true do |t|
  end

  create_table :comments, force: true do |t|
    t.integer :post_id
    t.boolean :active
  end
end

class Post < ActiveRecord::Base
  has_many :comments
end

class Comment < ActiveRecord::Base
  belongs_to :post
end

class BugTest < Minitest::Test
  def setup
    Comment.destroy_all
    Post.destroy_all
    post1 = Post.create!
    post1.comments << Comment.create!(active: true)
    post2 = Post.create!
    post2.comments << Comment.create!(active: true)
    @posts = Post.all
    @sql_calls = []
  end

  def collect_sql
    ActiveSupport::Notifications.subscribe("sql.active_record") do |name, started, finished, unique_id, payload|
      @sql_calls.push(payload[:sql])
    end
  end

  def test_eager_loading
    ActiveRecord::Associations::Preloader.new.preload(@posts, :comments)
    collect_sql
    comments = @posts.map { |a| a.comments.to_a }.flatten
    assert_equal 2, comments.count
    assert_equal [], @sql_calls
  end

  def test_eager_loading_with_conditions
    ActiveRecord::Associations::Preloader.new.preload(@posts, :comments, Comment.where(active: true))
    collect_sql
    comments = @posts.map { |post| post.comments.where(active: true).to_a }.flatten
    assert_equal 2, comments.count
    assert_equal [], @sql_calls
  end
end
```

```
ruby active_record_master.rb
```

### Expected behavior

When using a scope as third argument to `ActiveRecord::Associations::Preloader#preload` it should eager load that relation and doesn't trigger any SQL calls when iterating over posts and comments, therefore preventing n+1 queries.
(the `test_eager_loading` case is for reference, that it works WITHOUT a scope)

### Actual behavior

It eager loads all posts, but also triggers SQL queries for every post that loads it's comments. This results in one MORE SQL call than it would when you don't eager load.

```
D, [2020-02-06T10:18:42.045847 #20067] DEBUG -- :   Post Load (0.0ms)  SELECT "posts".* FROM "posts"
D, [2020-02-06T10:18:42.046368 #20067] DEBUG -- :   Comment Load (0.1ms)  SELECT "comments".* FROM "comments" WHERE "comments"."active" = ? AND "comments"."post_id" IN (?, ?)  [["active", 1], ["post_id", 3], ["post_id", 4]]
D, [2020-02-06T10:18:42.046827 #20067] DEBUG -- :   Comment Load (0.1ms)  SELECT "comments".* FROM "comments" WHERE "comments"."post_id" = ? AND "comments"."active" = ?  [["post_id", 3], ["active", 1]]
D, [2020-02-06T10:18:42.047171 #20067] DEBUG -- :   Comment Load (0.0ms)  SELECT "comments".* FROM "comments" WHERE "comments"."post_id" = ? AND "comments"."active" = ?  [["post_id", 4], ["active", 1]]
```

In Rails 5.2.4.1 this works, but only if you don't apply the scope when iterating over posts and comments:

```
  def test_eager_loading_with_conditions
    ActiveRecord::Associations::Preloader.new.preload(@posts, :comments, Comment.where(active: true))
    collect_sql
    comments = @posts.map { |a| a.comments.to_a }.flatten # <------------ here you can't apply the .where(active: true) scope
    assert_equal 2, comments.count
    assert_equal [], @sql_calls
  end
```

I think you should be able to eager load on the same association with different scopes:

```
# these trigger 2 SQL calls for the eager load
ActiveRecord::Associations::Preloader.new.preload(@posts, :comments, Comment.where(active: true))
ActiveRecord::Associations::Preloader.new.preload(@posts, :comments, Comment.where(active: false))

# these should NOT trigger more SQL calls
@posts.map { |a| a.comments.where(active: true).to_a }
@posts.map { |a| a.comments.where(active: false).to_a }
```

### System configuration
**Rails version**: master branch

**Ruby version**: 2.6.5

**Comment by eugeneius** [comment]
`ActiveRecord::Associations::Preloader` is not public API. Is it possible to reproduce this problem using only classes and methods documented on https://api.rubyonrails.org/?

**Comment by 23tux** [comment]
@eugeneius I was wondering why I didn't find any documentation for it, now it makes sense.

The graphql-batch gem from Shopify uses it in it's examples
https://github.com/Shopify/graphql-batch/blob/master/examples/association_loader.rb#L38

I didn't find any public classes / methods to reproduce this functionality. I think making it public would be a huge step?

**Comment by dhiachou** [comment]
@23tux I believe  `ActiveRecord::QueryMethods#includes` can help you achieve what you are trying to do.
Check the following links for more information.
- https://apidock.com/rails/ActiveRecord/QueryMethods/includes
- https://guides.rubyonrails.org/active_record_querying.html#eager-loading-associations

**Comment by fabriziobertoglio1987** [comment]
I believe this queries are ok. They are part of `ActiveRecord` **lazy evaluation** which runs the db sql query when the result is required.

Your test case is using another api `ActiveSupport::Notifications`, but does not take in consideration:

1) with `.includes` the first test will fail as the sql is lazy executed when `.map` is called

```ruby
  def test_eager_loading
    @posts = Post.includes(:comments)
    @sql_calls = []
    ActiveSupport::Notifications.subscribe("sql.active_record") do |name, started, finished, unique_id, payload|
      @sql_calls.push(payload[:sql])
    end
    comments = @posts.map { |a| a.comments.to_a }.flatten
    assert_equal 2, comments.count
    assert_equal [], @sql_calls
  end
```
and `@sql_calls` is equal to:
```sql
+["SELECT \"posts\".* FROM \"posts\"", "SELECT \"comments\".* FROM \"comments\" WHERE \"comments\".\"post_id\" IN (?, ?)"]
```

2) That the sql output is correct as specified in the [documentation][1] 

The first test fails for the following sql
```sql
+["SELECT \"posts\".* FROM \"posts\"", "SELECT \"comments\".* FROM \"comments\" WHERE \"comments\".\"post_id\" IN (?, ?)"]
```
The second test fails the following sql

```sql
+["SELECT \"posts\".* FROM \"posts\"", "SELECT \"comments\".* FROM \"comments\" WHERE \"comments\".\"post_id\" IN (?, ?)", "SELECT \"comments\".* FROM \"comments\" WHERE \"comments\".\"post_id\" = ? AND \"comments\".\"active\" = ?", "SELECT \"comments\".* FROM \"comments\" WHERE \"comments\".\"post_id\" = ? AND \"comments\".\"active\" = ?"]
```

3) The test does not take in consideration `lazy evaluation` in `ActiveRecord`.
Essentially the test set `@posts`, but not sql is executed.

```ruby
    @posts = Post.all
    @sql_calls = []
```
then you `subscribe` for notifications, but yet not sql was triggered (`lazy evaluation`):

```ruby
    ActiveSupport::Notifications.subscribe("sql.active_record") do |name, started, finished, unique_id, payload|
      @sql_calls.push(payload[:sql])
    end
``` 
once the result is required, `ActiveRecord` performs the `sql` query to the database

```ruby
    comments = @posts.map { |a| a.comments.to_a }.flatten
```
I could be wrong and I would really need some help in understanding this issue. Thanks a lot

[1]: https://www.rubydoc.info/docs/rails/ActiveRecord/Associations/Preloader
