### ISSUE TITLE
Webpacker issues with Rails 6.0.2.1

### ISSUE THREAD

**Issue by AleCx4** [rails/rails#38414]
### Steps to reproduce
Generate a new rails application.
Run `rails s` to run the application.

### Expected behavior
Application executes and a development server is activated

### Actual behavior
```
=> Booting Puma
=> Rails 6.0.2.1 application starting in development 
=> Run `rails server --help` for more startup options


========================================
  Your Yarn packages are out of date!
  Please run `yarn install --check-files` to update.
========================================


To disable this check, please change `check_yarn_integrity`
to `false` in your webpacker config file (config/webpacker.yml).


Usage Error: Couldn't find a script named "check".

$ yarn run <scriptName> ...


Exiting
```

### System configuration
**Rails version**: 6.0.2.1

**Ruby version**: ruby 2.5.7p206 (2019-10-01 revision 67816) [x86_64-linux]
**Yarn Version**:2.0.0-rc.27

### Additional notes

What's more, whenever I run the prompted command to check for the files installed through yarn I get:
```
Unknown Syntax Error: Unsupported option name ("--check-files").

$ yarn install [--json] [--immutable] [--immutable-cache] [--check-cache] [--inline-builds] [--cache-folder #0]
```

I cannot find any recommendations online for what to do in this case. What's more, I tried changing the `check_yarn_integrity=true` to `false` and the application does run. But say for example that I generate a controller, and once I added in a view I get:

```
Webpacker::Manifest::MissingEntryError in Articles#index

Webpacker can't find application in /<path>/manifest.json. Possible causes:
1. You want to set webpacker.yml value of compile to true for your environment
   unless you are using the `webpack -w` or the webpack-dev-server.
2. webpack has not yet re-run to reflect updates.
3. You have misconfigured Webpacker's config/webpacker.yml file.
4. Your webpack configuration is not creating a manifest.
Your manifest contains:
{
}

```

For which no manifest.json file exists to begin with. Some people recommended removing:

```
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
```

But I really don't like the idea of removing defaults that should be working to begin with. This was an issue that I had never seen on version 5.1x, so I am not entirely sure why this is happening. And I can't find any other issue for people not being able to run the `--check-files` command.

Thanks for any input guys!

**Comment by AleCx4** [comment]
Found the issue. Was not using the recommended yarn version installed globally.

Cheers.

**Comment by jakeNiemiec** [comment]
@AleCx4 Thanks, this should be improved with https://github.com/rails/webpacker/pull/2454.
