### ISSUE TITLE
Parenthesis in directory name causes a ' is missing a template for request formats: text/html' error

### ISSUE THREAD

**Issue by rempargo** [rails/rails#38415]
Related to #37719
I normally don't use parenthesis in my app name, but since Dropbox Business users have to cope with them, I want to show it us pure the 'parenthesis' that causing the problem, and not Dropbox itself.

### Steps to reproduce
    cd ~
    mkdir "my(app)"
    cd my\(app\)/
    rails new .
    rails generate scaffold Post title:string body:text
    rails db:migrate    
    rails s

### Expected behavior
When going to the following page, you would see a normal page with a simple form
    /posts/new.html
   
### Actual behavior
When trying to make a new item e.g.
    /posts/new.html

You will get the following error messages:

    No template for interactive request
    PostsController#new is missing a template for request formats: text/html

### log output

    Started GET "/posts/new" for ::1 at 2020-02-09 10:21:52 +0100
    (0.6ms)  SELECT sqlite_version(*)
    (0.4ms)  SELECT "schema_migrations"."version" FROM "schema_migrations" ORDER BY "schema_migrations"."version" ASC
    Processing by PostsController#new as HTML
    Completed 406 Not Acceptable in 15ms (ActiveRecord: 0.6ms | Allocations: 6137)
 
    ActionController::MissingExactTemplate (PostsController#new is missing a template for request formats: text/html):
  
    actionpack (6.0.2.1) lib/action_controller/metal/implicit_render.rb:45:in `default_render'
    actionpack (6.0.2.1) lib/action_controller/metal/basic_implicit_render.rb:6:in `block in send_action'
    actionpack (6.0.2.1) lib/action_controller/metal/basic_implicit_render.rb:6:in `tap'
    actionpack (6.0.2.1) lib/action_controller/metal/basic_implicit_render.rb:6:in `send_action'
    actionpack (6.0.2.1) lib/abstract_controller/base.rb:196:in `process_action'
    actionpack (6.0.2.1) lib/action_controller/metal/rendering.rb:30:in `process_action'
    actionpack (6.0.2.1) lib/abstract_controller/callbacks.rb:42:in `block in process_action'
    activesupport (6.0.2.1) lib/active_support/callbacks.rb:135:in `run_callbacks'
    actionpack (6.0.2.1) lib/abstract_controller/callbacks.rb:41:in `process_action'
    actionpack (6.0.2.1) lib/action_controller/metal/rescue.rb:22:in `process_action'
    actionpack (6.0.2.1) lib/action_controller/metal/instrumentation.rb:33:in `block in process_action'
    activesupport (6.0.2.1) lib/active_support/notifications.rb:180:in `block in instrument'
    activesupport (6.0.2.1) lib/active_support/notifications/instrumenter.rb:24:in `instrument'
    activesupport (6.0.2.1) lib/active_support/notifications.rb:180:in `instrument'
    actionpack (6.0.2.1) lib/action_controller/metal/instrumentation.rb:32:in `process_action'
    actionpack (6.0.2.1) lib/action_controller/metal/params_wrapper.rb:245:in `process_action'
    activerecord (6.0.2.1) lib/active_record/railties/controller_runtime.rb:27:in `process_action'
    actionpack (6.0.2.1) lib/abstract_controller/base.rb:136:in `process'
    actionview (6.0.2.1) lib/action_view/rendering.rb:39:in `process'
    actionpack (6.0.2.1) lib/action_controller/metal.rb:191:in `dispatch'
    actionpack (6.0.2.1) lib/action_controller/metal.rb:252:in `dispatch'
    actionpack (6.0.2.1) lib/action_dispatch/routing/route_set.rb:51:in `dispatch'
    actionpack (6.0.2.1) lib/action_dispatch/routing/route_set.rb:33:in `serve'
    actionpack (6.0.2.1) lib/action_dispatch/journey/router.rb:49:in `block in serve'
    actionpack (6.0.2.1) lib/action_dispatch/journey/router.rb:32:in `each'
    actionpack (6.0.2.1) lib/action_dispatch/journey/router.rb:32:in `serve'
    actionpack (6.0.2.1) lib/action_dispatch/routing/route_set.rb:837:in `call'
    rack (2.1.2) lib/rack/tempfile_reaper.rb:17:in `call'
    rack (2.1.2) lib/rack/etag.rb:27:in `call'
    rack (2.1.2) lib/rack/conditional_get.rb:27:in `call'
    rack (2.1.2) lib/rack/head.rb:14:in `call'
    actionpack (6.0.2.1) lib/action_dispatch/http/content_security_policy.rb:18:in `call'
    rack (2.1.2) lib/rack/session/abstract/id.rb:269:in `context'
    rack (2.1.2) lib/rack/session/abstract/id.rb:263:in `call'
    actionpack (6.0.2.1) lib/action_dispatch/middleware/cookies.rb:648:in `call'
    activerecord (6.0.2.1) lib/active_record/migration.rb:567:in `call'
    actionpack (6.0.2.1) lib/action_dispatch/middleware/callbacks.rb:27:in `block in call'
    activesupport (6.0.2.1) lib/active_support/callbacks.rb:101:in `run_callbacks'
    actionpack (6.0.2.1) lib/action_dispatch/middleware/callbacks.rb:26:in `call'
    actionpack (6.0.2.1) lib/action_dispatch/middleware/executor.rb:14:in `call'
    actionpack (6.0.2.1) lib/action_dispatch/middleware/actionable_exceptions.rb:17:in `call'
    actionpack (6.0.2.1) lib/action_dispatch/middleware/debug_exceptions.rb:32:in `call'
    web-console (4.0.1) lib/web_console/middleware.rb:132:in `call_app'
    web-console (4.0.1) lib/web_console/middleware.rb:28:in `block in call'
    web-console (4.0.1) lib/web_console/middleware.rb:17:in `catch'
    web-console (4.0.1) lib/web_console/middleware.rb:17:in `call'
    actionpack (6.0.2.1) lib/action_dispatch/middleware/show_exceptions.rb:33:in `call'
    railties (6.0.2.1) lib/rails/rack/logger.rb:38:in `call_app'
    railties (6.0.2.1) lib/rails/rack/logger.rb:26:in `block in call'
    activesupport (6.0.2.1) lib/active_support/tagged_logging.rb:80:in `block in tagged'
    activesupport (6.0.2.1) lib/active_support/tagged_logging.rb:28:in `tagged'
    activesupport (6.0.2.1) lib/active_support/tagged_logging.rb:80:in `tagged'
    railties (6.0.2.1) lib/rails/rack/logger.rb:26:in `call'
    sprockets-rails (3.2.1) lib/sprockets/rails/quiet_assets.rb:13:in `call'
    actionpack (6.0.2.1) lib/action_dispatch/middleware/remote_ip.rb:81:in `call'
    actionpack (6.0.2.1) lib/action_dispatch/middleware/request_id.rb:27:in `call'
    rack (2.1.2) lib/rack/method_override.rb:24:in `call'
    rack (2.1.2) lib/rack/runtime.rb:24:in `call'
    activesupport (6.0.2.1) lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'
    actionpack (6.0.2.1) lib/action_dispatch/middleware/executor.rb:14:in `call'
    actionpack (6.0.2.1) lib/action_dispatch/middleware/static.rb:126:in `call'
    rack (2.1.2) lib/rack/sendfile.rb:113:in `call'
    actionpack (6.0.2.1) lib/action_dispatch/middleware/host_authorization.rb:83:in `call'
    webpacker (4.2.2) lib/webpacker/dev_server_proxy.rb:23:in `perform_request'
    rack-proxy (0.6.5) lib/rack/proxy.rb:57:in `call'
    railties (6.0.2.1) lib/rails/engine.rb:526:in `call'
    puma (4.3.1) lib/puma/configuration.rb:228:in `call'
    puma (4.3.1) lib/puma/server.rb:681:in `handle_request'
    puma (4.3.1) lib/puma/server.rb:472:in `process_client'
    puma (4.3.1) lib/puma/server.rb:328:in `block in run'
    puma (4.3.1) lib/puma/thread_pool.rb:134:in `block in spawn_thread'

### Solution
renaming the app path folder to something without parentheses, will fix this issue immediately    
(not a solution for Dropbox Business Users).

### Comment 
How much I dislike Dropbox imposing the use of parentheses, I think Rails should work with any possible filename.

### System configuration
**Rails version**: 6.0.2.1

**Ruby version**: 2.6.5

**Comment by Winstijn** [comment]
Confirmed. 

Did a test on my own Dropbox Business account and I got the same result. A file name with parentheses (e.g.`~/Dropbox (Company)/dev/my_app`) in the path makes Rails unable to find the template. Move 'my_app' to another folder (e.g.` ~/Documents/ `) and it works again. 

Many problems caused by the parentheses in the Dropbox file path can be resolved using a symlink without parentheses. However, this does not solve the problem as described above.

**Comment by rempargo** [comment]
#37641 already mentioned this

**Comment by rempargo** [comment]
I wanted to double checked if this issue came up with Rails 6 or was already existing on a previous versions of Rails.

I checked Rails 5.2.4.1 and that version **can** handle an app name with parenthesis or spaces on macOS.

Checked also if Rails 6.0.2.1 can handle spaces in appname, and that also **works**, so it is only an issue with parenthesis.

**Comment by eileencodes** [comment]
Thanks for the report and investigation @rempargo. This test https://github.com/rails/rails/pull/37119/files#diff-16ebc2563790ac61841e627eac861805R83 indicates it can handle parenthesis. Can you write a test that demonstrates a case where this is broken in 6.0?

**Comment by rempargo** [comment]
When running `rails test` in a rails app with a directory like `my(app)`, I get 4 errors.
When running `rails test` in a rails app with a directory like `test +()[]{}`, like is described in the test that @eileencodes mentions, the test doesn't even finish the whole task, I get the following error:

    Running via Spring preloader in process 92136
    Traceback (most recent call last):
    	13: from -e:1:in `<main>'
    	12: from /Users/johndoe/.rvm/rubies/ruby-2.6.5/lib/ruby/site_ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
    	11: from /Users/johndoe/.rvm/rubies/ruby-2.6.5/lib/ruby/site_ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
    	10: from /Users/johndoe/.rvm/gems/ruby-2.6.5@six_zero/gems/spring-2.1.0/lib/spring/application/boot.rb:19:in `<top (required)>'
    	 9: from /Users/johndoe/.rvm/gems/ruby-2.6.5@six_zero/gems/spring-2.1.0/lib/spring/application.rb:139:in `run'
    	 8: from /Users/johndoe/.rvm/gems/ruby-2.6.5@six_zero/gems/spring-2.1.0/lib/spring/application.rb:139:in `loop'
    	 7: from /Users/johndoe/.rvm/gems/ruby-2.6.5@six_zero/gems/spring-2.1.0/lib/spring/application.rb:145:in `block in run'
    	 6: from /Users/johndoe/.rvm/gems/ruby-2.6.5@six_zero/gems/spring-2.1.0/lib/spring/application.rb:175:in `serve'
    	 5: from /Users/johndoe/.rvm/gems/ruby-2.6.5@six_zero/gems/spring-2.1.0/lib/spring/application.rb:175:in `fork'
    	 4: from /Users/johndoe/.rvm/gems/ruby-2.6.5@six_zero/gems/spring-2.1.0/lib/spring/application.rb:215:in `block in serve'
    	 3: from /Users/johndoe/.rvm/gems/ruby-2.6.5@six_zero/gems/spring-2.1.0/lib/spring/command_wrapper.rb:38:in `call'
    	 2: from /Users/johndoe/.rvm/gems/ruby-2.6.5@six_zero/gems/spring-2.1.0/lib/spring/commands/rails.rb:6:in `call'
    	 1: from /Users/johndoe/.rvm/gems/ruby-2.6.5@six_zero/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:58:in `load'
    /Users/johndoe/.rvm/gems/ruby-2.6.5@six_zero/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:58:in `expand_path': no implicit conversion of nil into String (TypeError)

**Comment by jonathanhefner** [comment]
@rempargo The fix from #37119 was not backported to v6.0.2.1 (see https://github.com/rails/rails/blob/v6.0.2.1/actionview/lib/action_view/template/resolver.rb#L361).  Could you try again with Rails' master branch to see if the issue persists?

As for the error you posted when using a name like `test +()[]{}`, that error is coming from Spring, rather than Rails itself.  Specifically from https://github.com/rails/spring/blob/647b8c31356f31a22c3d783aae824d41ab579a57/lib/spring/commands/rails.rb#L6.  The `[]` in the directory name trips up the `Dir.glob` on that line.  I will submit a PR for that sometime in the near future.

**Comment by rempargo** [comment]
@jonathanhefner you're right, the issue is fixed at master c29afa3872a1, so now I learned to install rails from master, didn't do that before (got a small issue when `rails new . --dev`, it crashed at `rails  webpacker:install`, but when I tried that step again, it's just went on normally).

so I will close this issue.

**Comment by jonathanhefner** [comment]
@rempargo Thank you for verifying! :+1: 

p.s. The `webpacker:install` issue is being tracked in #38459.
