### ISSUE TITLE
Namespacing Issues

### ISSUE THREAD

**Issue by jblac** [rails/rails#38416]
### Steps to reproduce
Create a new rails application, I used ` rails new sampleapp --skip-bundle --skip-webpack-install --skip-test --system-test --database=mysql --no-skip-sprockets`

I then removed webpack from the gemfile (because it's unnecessary)

Create a new model and migration:
```
class CreateSpecies < ActiveRecord::Migration[6.0]
  def change
    create_table :species do |t|
      t.string :name
      t.string :scientific_name
      t.string :genus
      t.string :family

      t.timestamps
    end
  end
end
```

```
class CreateSpecies < ActiveRecord::Migration[6.0]
  def change
    create_table :species do |t|
      t.string :name
      t.string :scientific_name
      t.string :genus
      t.string :family

      t.timestamps
    end
  end
end
```

Now, create a controller in a namespace:
```
class Admin::SpeciesController < ApplicationController
  before_action :set_admin_species, only: [:show, :edit, :update, :destroy]
   # GET /admin/species
  # GET /admin/species.json
  def index
    @admin_species = Species.all
  end
end
```

and create your views in the namespace (`views/admin/*`):
```
<p id="notice"><%= notice %></p>

<h1>Admin Species</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Scientific name</th>
      <th>Genus</th>
      <th>Family</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @admin_species.each do |admin_species| %>
      <tr>
        <td><%= admin_species.name %></td>
        <td><%= admin_species.scientific_name %></td>
        <td><%= admin_species.genus %></td>
        <td><%= admin_species.family %></td>
        <td><%= link_to 'Show', admin_species %></td>
        <td><%= link_to 'Edit', edit_admin_species_path(admin_species) %></td>
        <td><%= link_to 'Destroy', admin_species, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Admin species', new_admin_species_path %>
```

and lastly, add your route:
```
namespace :admin do
  resources :species
end
```

### Expected behavior
It should take you to the index page.

### Actual behavior
It throws an error, because the routing is decided from the model location.   The error is with the `Show` link

`undefined method `species_path' for #<#<Class:0x00005575b70d6290>:0x00007fbbf60ba090>`

### Workaround that opens up other problems
Add a new model at `admin/species.rb` and make that inherit from `Species`   and re-route the controller to use this instead. This fixes most problems, but introduces an issue with form_with in this specific case where the singular and plural are the same.   

For this problem, the "new" form works, but the "edit" form produces the incorrect path in `polymorphic_routes.rb` at line `267` ie: `model.model_name.singular_route_key` which returns `admin_specy_path` instead of `admin_species_path`

Should be noted that adding the inflection for `admin_species` into the initializer for this did work to fix it, but that could grow exponentially with words that rails can't properly depict the singular (or plural)

### System configuration
**Rails version**: Rails 6.0.2.1

**Ruby version**: ruby 2.6.3p62 (2019-04-16 revision 67580) [x86_64-linux]

**Comment by aar0nr** [comment]
The routing is working as expected. You need to change your show route to either:

```rhtml
<%= link_to 'Show', [:admin, admin_species] %>
```

or

```rhtml
<%= link_to 'Show', admin_species_path(admin_species) %>
```

Now having said that, the naming is probably  confusing you. Just because you are working with the species model under an admin namespace, doesn't mean you need to call it ```@admin_species```. e.g.:

```ruby
class Admin::SpeciesController < ApplicationController
  before_action :set_species, only: [:show, :edit, :update, :destroy]

  def index
    @species = Species.all
  end
end
```

```rhtml
<p id="notice"><%= notice %></p>

<h1>Admin Species</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Scientific name</th>
      <th>Genus</th>
      <th>Family</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @species.each do |species| %>
      <tr>
        <td><%= species.name %></td>
        <td><%= species.scientific_name %></td>
        <td><%= species.genus %></td>
        <td><%= species.family %></td>
        <td><%= link_to 'Show', admin_species_path(species) %></td>
        <td><%= link_to 'Edit', edit_admin_species_path(species) %></td>
        <td><%= link_to 'Destroy', admin_species_path(species), method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Admin species', new_admin_species_path %>
```
