### ISSUE TITLE
Rack 2.2.1 introduces Action Pack behavior changes

### ISSUE THREAD

**Issue by yahonda** [rails/rails#38420]
Rack 2.2.1 introduces these two test failures. The first one is triggered by https://github.com/rack/rack/commit/6ff4d2084aaf63e6fd9b36ff3e2305f3cf9b083e and the second one is done by https://github.com/rack/rack/commit/d2e608e8d54b76ec7e52bb7c6508c5a5259c934e. I'm not so familiar with these behavior yet, then I'm not sure they should be fixed by Rake or Rails.

### Steps to reproduce
```ruby
% rm Gemfile.lock
% bundle install
% cd actionpack
% bundle exec ruby -w -Itest test/dispatch/request_test.rb -n test_cookie_syntax_resilience
% bundle exec ruby -w -Itest test/dispatch/ssl_test.rb -n test_keeps_original_headers_behavior
```

### Expected behavior
Both of these tests should pass.

### Actual behavior
```ruby
%  bundle exec ruby -w -Itest test/dispatch/request_test.rb -n test_cookie_syntax_resilience
Run options: -n test_cookie_syntax_resilience --seed 14725

# Running:

F

Failure:
RequestCookie#test_cookie_syntax_resilience [test/dispatch/request_test.rb:599]:
{"_session_id"=>"c84ace847,96670c052c6ceb2451fb0f2", "is_admin"=>"yes"}.
--- expected
+++ actual
@@ -1 +1 @@
-"c84ace847"
+"c84ace847,96670c052c6ceb2451fb0f2"



rails test test/dispatch/request_test.rb:591



Finished in 0.063482s, 15.7525 runs/s, 47.2575 assertions/s.
1 runs, 3 assertions, 1 failures, 0 errors, 0 skips
% bundle exec ruby -w -Itest test/dispatch/ssl_test.rb -n test_keeps_original_headers_behavior

Run options: -n test_keeps_original_headers_behavior --seed 59049

# Running:

F

Failure:
SecureCookiesTest#test_keeps_original_headers_behavior [test/dispatch/ssl_test.rb:226]:
Expected: "close"
  Actual: ["close"]


rails test test/dispatch/ssl_test.rb:224



Finished in 0.047466s, 21.0677 runs/s, 21.0677 assertions/s.
1 runs, 1 assertions, 1 failures, 0 errors, 0 skips
%
```
### System configuration
**Rails version**: master

**Ruby version**:ruby 2.7.0p0 (2019-12-25 revision 647ee6f091) [x86_64-darwin19]

**Comment by ioquatix** [comment]
Thanks for the report. What do you think we should do?

**Comment by kaspth** [comment]
The second one was fixed in https://github.com/rails/rails/pull/38422

**Comment by kaspth** [comment]
Omitted the other failing test just to get our suite back to green for now: 5bd29afeb4

**Comment by kaspth** [comment]
As for what to do both changes seem sensible to me. Cookies can last a long time though, e.g. `cookies.permanent` sets the expiry to 10 years. Not sure about the reach and it seemed like clients passed commas in cookies, so if they all stopped doing that years ago? No issue.

I don't know how to find out that. @yahonda or @vipulnsward do any of you know? 😊

**Comment by ioquatix** [comment]
Even if a cookie is persisted for 10 years, the browser shouldn't be sending or formatting it as it may have been 10 years ago.

**Comment by kaspth** [comment]
Right, good point 👍 Can't see an issue with this, though I've only given this a cursory glance for the record, so I may have missed something. Thanks for work here @yahonda @vipulnsward and of course for shepherding Rack @ioquatix 🙏
