### ISSUE TITLE
Ruby 2.7 support for 5.2.x?

### ISSUE THREAD

**Issue by utkarsh2102** [rails/rails#38426]
Hi,

Would you intend to extend Ruby2.7 support to 5.2.x versions?
Also, I hope rails work with all versions of bundler? Particularly the latest one?

**Comment by kaspth** [comment]
You'll have to upgrade for 2.7 support. There's too many wide-reaching deprecation warnings thrown on 2.7 that it doesn't make sense to do so. We're adding it to 6-0-stable though, iirc.

Bug reports and PRs welcome against master. ✌️
