### ISSUE TITLE
Make ActiveSupport::Concern also prepend ClassMethods

### ISSUE THREAD

**Issue by elia** [rails/rails#38439]
We do a lot of prepending within Solidus stores and I've found, over time, that a number of bugs and false expectations can arise when ClassMethods are included in the singleton class (using `extend`) instead of being prepended. 

The code we end up with usually looks like this:

```rb
module PostDecorator
  module ClassMethods
    def some_scope
      puts 'calling some_scope'
      super
    end
  end
  
  def title
    super.upcase
  end
  
  Post.prepend self
  Post.singleton_class.prepend self::ClassMethods
  # vs.
  # def self.prepended(base)
  #   base.extend ClassMethods
  # end
end
```

This revealed to be way less error-prone, and the behavior most developer expect when prepending. 

I can send a PR for this change if this is something that makes sense for the core-team as well.

_Originally posted in https://github.com/rails/rails/pull/37174#issuecomment-584119258_

**Comment by rafaelfranca** [comment]
👍
