### ISSUE TITLE
Action Mailbox: Live ingress BCC?

### ISSUE THREAD

**Issue by rikkipitt** [rails/rails#38446]
### Steps to reproduce
Using Postmark, Mailgun, or Sendgrid, the BCC recipients are not passed through to Action Mailbox. Although, they may be sent in the overall payload from the providers.

### Expected behavior
I expect `mail.recipients` or `mail.recipients_addresses` to include the BCC recipients.

Advice for allowing this to work correctly would be awesome. Would I instead have to modify/override the ingress controller behaviour? E.g. save the BCC's separately?

In the case of Postmark, the BCC addresses are included in the payload I believe, but we're only saving/parsing the raw email. The raw emails tend not to have the bcc in the header. Or so I think.

https://postmarkapp.com/developer/user-guide/inbound/parse-an-email

### Actual behavior
Only the main `to` and any `cc` recipients are included.

### System configuration
**Rails version**: 6.0.2.1

**Ruby version**: 2.6.3

**Comment by rikkipitt** [comment]
I think it can be done by manually parsing the `received` header for BCC addresses...

**Comment by rikkipitt** [comment]
Okay, I think it depends on who/how the email is sent to and how Mailgun parses the emails.

If I send a test email with a BCC from my email client, all works okay.

If I send an email via SendGrid, due to how they send on the BCC information, Mailgun parses the and sends the BCC on as a "recipient" field at the same level as the ingress-parsed json "body-mime" parameter... i.e. it's not in the mail.recipients as such.

Any idea of how we can also grab the "recipient" field in the Mailgun json and include it in the `mail.recipients` so we can catch all these potentially valid emails?

Cheers!
Rikki

**Comment by jeremy** [comment]
I'd recommend developing a PR that accounts for the `recipient` and `sender` parameters, which are from the SMTP envelope rather than the MIME message itself:
https://github.com/rails/rails/blob/99b607e6ad681b17de40d6cc55aa3af7989305db/actionmailbox/app/controllers/action_mailbox/ingresses/mailgun/inbound_emails_controller.rb#L48-L50

Other ingresses assume these have been added to the MIME message as `X-Original-To` (recipient) and `Return-Path` (sender). Postfix local delivery does this automatically, for example.

**Comment by rikkipitt** [comment]
Thanks, @jeremy. 

As I understand it, the `ActionMailbox::InboundEmail` record is created, but later routed via a background job. Essentially at the moment, the extra data in the dump from the email provider is lost. Only the _eml_ is stored. A PR would have to account for that extra information and save it to a new column.

Before I get started on a PR for this, does the above sound viable for getting merged into Rails? What would the best way of doing this be? Save the whole json payload or something else?

I'd really appreciate your advice on this if you get the time. Thanks again.

**Comment by jeremy** [comment]
> A PR would have to account for that extra information and save it to a new column.

That's right. Need to preserve the SMTP envelope sender and recipient.

> Before I get started on a PR for this, does the above sound viable for getting merged into Rails? What would the best way of doing this be? Save the whole json payload or something else?

Recommend mimicking what Postfix does: add them to the MIME message as X-Original-To and Return-Path headers.

**Comment by rikkipitt** [comment]
Thanks. So to clarify, something along the lines of this for the Mailgun ingress?

`mail.header['X-Original-To'] = params.require("recipient")`

Cheers for the help on this one! Appreciated.

**Comment by kaspth** [comment]
Yeah, that looks like it. But no clue what params Mailgun sends, so you may need to tweak things. But you’ll see, code will reveal it 😄🙌

**Comment by rikkipitt** [comment]
Thanks, @kaspth! I need this functionality on one of my projects so I'll be working on this very soon.

Ref: https://documentation.mailgun.com/en/latest/user_manual.html (search for _body-mine_ to see all the params).

Appreciate the input, both.

**Comment by rikkipitt** [comment]
Hi folks,

I took a look at this today. Seems to be going well, but I have a slight concern regarding the existing tests. Specifically: https://github.com/rails/rails/blob/fba1064153d8e2f4654df7762a7d3664b93e9fc8/actionmailbox/test/controllers/ingresses/mailgun/inbound_emails_controller_test.rb#L24

I was planning on taking the `body-mime` param, parsing with it https://github.com/mikel/mail, then assigning the `X-Original-To` header with the Mailgun `recipient` param.

This all works, but it'll break the above test as the `raw_email` will end up being modified... Also, the `to_s` method of Mail will output the raw_email differently too.

Would love to hear your thoughts on a decent way forward with this potential PR.

Cheers, Rikki.

**Comment by kaspth** [comment]
> Would love to hear your thoughts on a decent way forward with this potential PR.

Let's upgrade this to a real PR and take the discussion there 😄 You can always close it in case you don't feel like moving forward with it, no problem

**Comment by rikkipitt** [comment]
Sounds good to me. I'll get it ready tomorrow so you can see what I mean.

Thank you.
