### ISSUE TITLE
Support bundler 2.1.4 with rails 5.x

### ISSUE THREAD

**Issue by utkarsh2102** [rails/rails#38451]
Hi,

Can we have support for bundler 2.1.4 with the latest 5.x series?

**Comment by kaspth** [comment]
Please see our maintenance policy: https://guides.rubyonrails.org/maintenance_policy.html#bug-fixes

**Comment by kaspth** [comment]
Also ref: https://github.com/rails/rails/issues/38426#issuecomment-584378944

Please don't open new issues asking for things on 5.2. That ship's sailed unfortunately ✌️

**Comment by rokumatsumoto** [comment]
@utkarsh2102 Do you remember what error did you get at that time?

**Comment by utkarsh2102** [comment]
Hi @rokumatsumoto,

I am sorry I do not have the logs anymore but building rails 5.2.x with bundler 2.1.4 should reproduce them I guess!
