### ISSUE TITLE
Doc links pointing to a 404 page on github

### ISSUE THREAD

**Issue by dhiachou** [rails/rails#38460]
The concerned files seem to be `activemodel/README.rdoc` and `activerecord/README.rdoc`
### Steps to reproduce
Click on any "Learn more" link on https://github.com/rails/rails/tree/master/activerecord.

### Expected behavior
Take you to the documentation page of the corresponding class.

### Actual behavior
Page not found error.

**Comment by rafaelfranca** [comment]
Duplicate of #28608

**Comment by dhiachou** [comment]
@rafaelfranca  according to https://edgeguides.rubyonrails.org/ruby_on_rails_guides_guidelines.html#linking-to-the-api it seems that links to the API should be absolute in order to be processed by the guides generator. 
I see no harm however in these files displaying correctly on github.

**Comment by rafaelfranca** [comment]
That is about the rails guides. The api generation itself doesn't process the links
