### ISSUE TITLE
ActionMailbox Mailgun needs signing key

### ISSUE THREAD

**Issue by Matthijsy** [rails/rails#38471]
### Steps to reproduce
- Create a mailgun account
- Refresh the API key
- Send an email to the ActionMailbox ingress endpoint

Now you have an account with a different API key and signing key

### Expected behavior
You can still use the ActionMailbox ingression method.

### Actual behavior
When using the ActionMailbox ingress function 401 errors are returned. This is due to the fact that it will use the API key (which you should configure according to the documentation https://guides.rubyonrails.org/action_mailbox_basics.html#mailgun) but for validation you need to use the signing key. 

This validation happens here: https://github.com/rails/rails/blob/master/actionmailbox/app/controllers/action_mailbox/ingresses/mailgun/inbound_emails_controller.rb#L99

Mailgun also specifies that you need to use the signing key for webhook validation and not the API key https://documentation.mailgun.com/en/latest/user_manual.html#webhooks

### System configuration
**Rails version**: 6.0.2.1

**Ruby version**: 2.6.5p114

**Comment by georgeclaghorn** [comment]
Nice catch, @Matthijsy! Looks like the switch from API key to signing key happened recently. Interested in opening a PR?

**Comment by georgeclaghorn** [comment]
Fixed in #38529.
