### ISSUE TITLE
Parallel test databases still exist after testing

### ISSUE THREAD

**Issue by mibradev** [rails/rails#38470]
### Steps to reproduce

- `rails new my-app`
- `cd my-app`
- `rails db:create`
- `rails db:migrate`
- `rails test`
- `ls db`

### Expected behavior

Not finding test databases created in parallel, because `rails db:drop` task has nothing to do with those databases after that.

### Actual behavior

Parallel databases like:

- test.sqlite3-0
- test.sqlite3-1
- test.sqlite3-2
- test.sqlite3-3

are still there.

### System configuration
**Rails version**: 6.0.2.1

**Ruby version**: 2.7.0

**Comment by eugeneius** [comment]
This is intentional, so that subsequent test runs don't have to load the schema again.
