### ISSUE TITLE
Having trouble with getting definitions from the database and dumping it to a text file

### ISSUE THREAD

**Issue by smehdi2-hub** [rails/rails#38486]
Hi everyone. 
So i am using my terminal and atom 4 to create a ruby on rails project. 
I am stuck on the configuring a project section of the course.
When i run the following command:
rails db:schema:dump (in my terminal) i get the following error:

Somairas-MacBook-Pro:simple_cms shahvezmehdi$ rails db:schema:dump
The dependency tzinfo-data (>= 0) will be unused by any of the platforms Bundler is installing for. Bundler is installing for ruby but the dependency is only for x86-mingw32, x86-mswin32, x64- ....etc

Hope someone can help with this! searched online and not really able to find anything for rails db:schema:dump.
### System configuration
Rails version: Rails 6.0.2.1
Ruby version: ruby 2.7.0p0

**Comment by smehdi2-hub** [comment]
<img width="1673" alt="Screen Shot 2020-02-17 at 11 29 16 AM" src="https://user-images.githubusercontent.com/61162426/74681641-c74f2680-5178-11ea-9c45-ccdb577dcaa6.png">
 
This is an uploaded screenshot of what i'm going through!

**Comment by peterb** [comment]
That's just a Bundler warning, there seems to be a syntax error in your database.yml, can you verify and attach it?

**Comment by smehdi2-hub** [comment]
<img width="1105" alt="Screen Shot 2020-02-17 at 12 06 38 PM" src="https://user-images.githubusercontent.com/61162426/74683505-0469e780-517e-11ea-88af-fa15758938d8.png">

**Comment by kaspth** [comment]
Please use the Ruby on Rails talk mailing list or StackOverflow for questions/help, where a wider community will be able to help you. We reserve the issues tracker for issues only.

Though it seems like you'd want to put a space after ":" on your password line, or perhaps put your password in quotes, e.g.: `password: "secret123"`. Hope that helps!

**Comment by smehdi2-hub** [comment]
IT WORKED! thank you and also thanks for the info!

**Comment by smehdi2-hub** [comment]
Hi guys i've posted on StackOverFlow and had no luck. Im having trouble with rails server.
When i run the rails server command i get the following error. 

<img width="1653" alt="Screen Shot 2020-02-17 at 4 00 52 PM" src="https://user-images.githubusercontent.com/61162426/74693011-b2858980-519e-11ea-8d4d-e5ca8dc997f1.png">
<img width="1234" alt="Screen Shot 2020-02-17 at 4 02 18 PM" src="https://user-images.githubusercontent.com/61162426/74693044-e52f8200-519e-11ea-8884-237a3c632bb4.png">
<img width="1233" alt="Screen Shot 2020-02-17 at 4 03 06 PM" src="https://user-images.githubusercontent.com/61162426/74693072-02645080-519f-11ea-8179-567949ba184f.png">
