### ISSUE TITLE
Activerecord with table prefix does not infere correct column name

### ISSUE THREAD

**Issue by HDLP9** [rails/rails#38481]
### Steps to reproduce

```
require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  gem "rails", github: "rails/rails"
  gem "sqlite3"
end

require "active_record"
require "minitest/autorun"
require "logger"

# This connection will do for database-independent bug reports.
ActiveRecord::Base.establish_connection(adapter: "sqlite3", database: ":memory:")
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :rails_posts, force: true do |t|
  end

  create_table :rails_comments, force: true do |t|
    t.integer :post_id
  end
end

class Post < ActiveRecord::Base
  self.table_name_prefix = 'rails_'
  has_many :comments
  
end

class Comment < ActiveRecord::Base
  self.table_name_prefix = 'rails_'
  belongs_to :post
end

class BugTest < Minitest::Test
  def test_association_stuff
    post = Post.create!
    post.comments << Comment.create!

    assert_equal 1, Post.joins(:comments).where(rails_comments: { post: Post.first }).size
  end
end
```
### Expected behavior

Rails should infere from the hash condition the correct column name for post, with is post_id in this case. If the same test is executed without table prefix it passes without any errors.

```
SELECT COUNT(*) 
FROM "rails_posts" INNER JOIN "rails_comments" ON "rails_comments"."post_id" = "rails_posts"."id" 
WHERE "rails_comments"."post_id" = ?
```
In rails doc it says that:

```
author = Author.find(1)

# The following queries will be equivalent:
Post.where(author: author)
Post.where(author_id: author)
```

### Actual behavior

We get the following SQL:

```
SELECT COUNT(*) 
FROM "rails_posts" INNER JOIN "rails_comments" ON "rails_comments"."post_id" = "rails_posts"."id" 
WHERE "rails_comments"."post" = ?
```
That throws an error that does not find "post" column

### System configuration
**Rails version**: tried in 6.0.2.1 and latest 5

**Ruby version**: 2.6.5

### Note
This gets even worse if used with Polymorfic tables, were getting an error in rails table_metadata.rb:

https://github.com/rails/rails/blob/f33d52c95217212cbacc8d5e44b5a8e3cdc6f5b3/activerecord/lib/active_record/table_metadata.rb#L45

saying that cannot find method _reflect_on_association in nil class.

**Comment by biggeektx** [comment]
When you're doing a `join` with a `where` clause on the joined table, you have to specify the correct table and column names as they are in the schema/db.
Just like how you specify the table in your example here:
```
Post.joins(:comments).where(rails_comments: { post: Post.first }).size
```
You join on the relation, `:comments`, but specify the actual table name, with prefix, `rails_comments`. It's the same with the column name.

The Post/Author examples you gave:
```
# The following queries will be equivalent:
Post.where(author: author)
Post.where(author_id: author)
```
are looking up columns on the primary model (Post), so it uses the known relations for the lookup, translating `author` to `author_id` in ActiveRecord. This isn't the same as a lookup on a joined table/model.

**Comment by HDLP9** [comment]
@biggeektx but the following example works perfectly with a join with a where passing post instead of column post_id...

```
class BugTest < Minitest::Test
  def test_association_stuff
    post = Post.create!
    post.comments << Comment.create!

    assert_equal 1, Post.joins(:comments).where(comments: { post: Post.first }).size
  end
end
```
If table_prefixes are used with polymorphic tables the error in rails table_metadata.rb class in still a problem.
