### ISSUE TITLE
rails server issue

### ISSUE THREAD

**Issue by smehdi2-hub** [rails/rails#38493]
Hi everyone!
Im having trouble launching the rails server.
when i do i get the following:
MacBook-Pro:simple_cms shahvezmehdi$ rails server
The dependency tzinfo-data (>= 0) will be unused by any of the platforms Bundler is installing for. Bundler is installing for ruby but the dependency is only for x86-mingw32, x86-mswin32, x64-mingw32, java. To add those platforms to the bundle, run `bundle lock --add-platform x86-mingw32 x86-mswin32 x64-mingw32 java`.
=> Booting Puma
=> Rails 6.0.2.1 application starting in development
=> Run `rails server --help` for more startup options
Exiting
Traceback (most recent call last):.....etc
I have also attached screenshots of the code/error.
Hope someone can help.
Thanks.
<img width="1270" alt="Screen Shot 2020-02-17 at 3 40 17 PM" src="https://user-images.githubusercontent.com/61162426/74693443-bd411e00-51a0-11ea-861a-e6fd4cc3fffc.png">
<img width="1279" alt="Screen Shot 2020-02-17 at 3 40 49 PM" src="https://user-images.githubusercontent.com/61162426/74693445-c0d4a500-51a0-11ea-964e-143519322ce0.png">
<img width="1278" alt="Screen Shot 2020-02-17 at 3 41 15 PM" src="https://user-images.githubusercontent.com/61162426/74693450-c4682c00-51a0-11ea-9c85-3436d7084b83.png">

**Comment by smehdi2-hub** [comment]
I tried posting this issue on StackOverFlow but i was not able to get any help!

**Comment by kaspth** [comment]
Sorry, you won't be able to here either, this tracker is for bugs only. Maybe the rubyonrails-talk mailing list is worth a try?

(Alternatively the last line in your output says "Please run `rails webpacker:install`")
