### ISSUE TITLE
Rails: Creating new Rails App - timing / execution issue

### ISSUE THREAD

**Issue by luke-hill** [rails/rails#38502]
### Steps to reproduce
- Our CI in cucumber-rails creates a new rails app in a lot of cucumber tests.
- When running our CI suite with rails `6.0.0` it runs and passes cleanly. See https://travis-ci.org/cucumber/cucumber-rails/jobs/607131809#L509 for an example
- When running our CI suite with rails `6.0.1` it fails. See https://travis-ci.org/cucumber/cucumber-rails/jobs/621663113#L506 for an example

### Expected behavior
Running `bundle exec rails new test_app --skip-bundle --skip-test-unit --skip-spring --skip-bootsnap` Should not throw any errors.

### Actual behavior
We get either a timeout or a failure on the above. It's worth noting we are running this inside an aruba process (So perhaps this affects the issue). And given the fact it's a serious issue, I would put money on this being the issue. So if it's not a core issue, then apologies. Any assistance would be greatly appreciated.

### System configuration
**Rails version**:
Mentioned above
**Ruby version**:
Ruby 2.5 and Ruby 2.6

**Comment by kaspth** [comment]
This is a fairly specific and uncommon CI setup. Sounds fairly out of scope for what we can consider a bug here, hope you figure it out 💪
