### ISSUE TITLE
Rollback migrations in a multiple database application.

### ISSUE THREAD

**Issue by eprusakov** [rails/rails#38513]
### Steps to reproduce
When trying to rollback migration that was added to secondary Database it rollback migration from primary Database. 

My secondary Database named 'logger'. I'm trying to execute following command in bash

`rails db:rollback:logger`

but I get

> Don't know how to build task 'db:rollback:logger' (See the list of available tasks with `rails --tasks`)
Did you mean?  db:rollback

But in it's turn `rails db:rollback` only reverts primary Database.

### Expected behavior

`rails db:rollback`

Should rollback latest migration even if this migration was added to the secondary Database.

Or I would like do something, like:

`rails db:rollback:secondary`

### Actual behavior

`rails db:rollback`

Always reverted migration from primary Database

### System configuration
Rails 
"6.0.2.1"

Ruby
"2.6.5"

**Comment by alec-joy** [comment]
Can you run rails -T and post the output?

**Comment by eprusakov** [comment]
> Can you run rails -T and post the output?

> rails about                              # List versions of all Rails frameworks and the environment
rails amorail:check                      # Check Amorail configuration
rails annotate_models                    # Add schema information (as comments) to model and fixture files
rails annotate_routes                    # Adds the route map to routes.rb
rails anonymize                          # Create dev version
rails app:template                       # Applies the template supplied by LOCATION=(/path/to/template) or URL
rails app:update                         # Update configs and some other initially generated files (or use just update:configs or update:bin)
rails assets:clean[keep]                 # Remove old compiled assets
rails assets:clobber                     # Remove compiled assets
rails assets:environment                 # Load asset compile environment
rails assets:precompile                  # Compile all the assets named in config.assets.precompile
rails autoprefixer:info                  # Show selected browsers and prefixed CSS properties and values
rails cache_digests:dependencies         # Lookup first-level dependencies for TEMPLATE (like messages/show or comments/_comment.html)
rails cache_digests:nested_dependencies  # Lookup nested dependencies for TEMPLATE (like messages/show or comments/_comment.html)
rails check_listings                     # Run listings limit checker for each active listing
rails check_sitemap                      # Make requests for each url from sitemap list
rails create_pretty_links                # create_pretty_links
rails create_trial_subscription_item     # create_trial_subscription_item
rails db:create                          # Creates the database from DATABASE_URL or config/database.yml for the current RAILS_ENV (use db:create:all to create all databases in the config). Without RAILS_ENV or when R...
rails db:create:logger                   # Create logger database for current environment
rails db:create:primary                  # Create primary database for current environment
rails db:drop                            # Drops the database from DATABASE_URL or config/database.yml for the current RAILS_ENV (use db:drop:all to drop all databases in the config). Without RAILS_ENV or when RAILS_E...
rails db:drop:logger                     # Drop logger database for current environment
rails db:drop:primary                    # Drop primary database for current environment
rails db:environment:set                 # Set the environment value for the database
rails db:fixtures:load                   # Loads fixtures into the current environment's database
rails db:migrate                         # Migrate the database (options: VERSION=x, VERBOSE=false, SCOPE=blog)
rails db:migrate:logger                  # Migrate logger database for current environment
rails db:migrate:primary                 # Migrate primary database for current environment
rails db:migrate:status                  # Display status of migrations
rails db:migrate:status:logger           # Display status of migrations for logger database
rails db:migrate:status:primary          # Display status of migrations for primary database
rails db:prepare                         # Runs setup if database does not exist, or runs migrations if it does
rails db:rollback                        # Rolls the schema back to the previous version (specify steps w/ STEP=n)
rails db:schema:cache:clear              # Clears a db/schema_cache.yml file
rails db:schema:cache:dump               # Creates a db/schema_cache.yml file
rails db:schema:dump                     # Creates a db/schema.rb file that is portable against any DB supported by Active Record
rails db:schema:load                     # Loads a schema.rb file into the database
rails db:seed                            # Loads the seed data from db/seeds.rb
rails db:seed:replant                    # Truncates tables of each database for current environment and loads the seeds
rails db:setup                           # Creates the database, loads the schema, and initializes with the seed data (use db:reset to also drop the database first)
rails db:structure:dump                  # Dumps the database structure to db/structure.sql
rails db:structure:load                  # Recreates the databases from the structure.sql file
rails db:version                         # Retrieves the current schema version number
rails delete_plus                        # delete plus
rails dev                                # Create dev version
rails fake                               # Generate fake data
rails geocode:all                        # Geocode all objects without coordinates
rails geocoder:maxmind:geolite:download  # Download MaxMind GeoLite City data
rails geocoder:maxmind:geolite:extract   # Extract (unzip) MaxMind GeoLite City data
rails geocoder:maxmind:geolite:insert    # Load/refresh MaxMind GeoLite City data
rails geocoder:maxmind:geolite:load      # Download and load/refresh MaxMind GeoLite City data
rails heroku:config:load[app]            # Snappconfig task to load configuration into Heroku from YAML file(s)
rails log:clear                          # Truncates all/specified *.log files in log/ to zero bytes (specify which logs with LOGS=test,development)
rails metro_stations_coordinates         # Fill empty coordinates columns in MetroStations
rails middleware                         # Prints out your Rack middleware stack
rails pghero:analyze                     # Analyze tables
rails pghero:autoindex                   # Autoindex tables
rails pghero:capture_query_stats         # Capture query stats
rails pghero:capture_space_stats         # Capture space stats
rails pghero:clean_query_stats           # Remove old query stats
rails reindex_all                        # Reindex elastic
rails remove_annotation                  # Remove schema information from model and fixture files
rails remove_routes                      # Removes the route map from routes.rb
rails remove_tags                        # Remove html tags from latest posts
rails restart                            # Restart app by touching tmp/restart.txt
rails restart_listings_views_counts      # restart_listings_views_counts
rails restore_streets                    # Resotre streets
rails rollbar:test                       # Verify your gem installation by sending a test exception to Rollbar
rails searchkick:reindex                 # reindex model
rails searchkick:reindex:all             # reindex all models
rails secret                             # Generate a cryptographically secure secret key (this is typically used to generate a secret for cookie sessions)
rails sitemap:clean                      # Delete all Sitemap files in public/ directory
rails sitemap:create                     # Generate sitemaps but don't ping search engines
rails sitemap:install                    # Install a default config/sitemap.rb file
rails sitemap:refresh                    # Generate sitemaps and ping search engines
rails sitemap:refresh:no_ping            # Generate sitemaps but don't ping search engines
rails spec                               # Run all specs in spec directory (excluding plugin specs)
rails spec:controllers                   # Run the code examples in spec/controllers
rails spec:models                        # Run the code examples in spec/models
rails spec:requests                      # Run the code examples in spec/requests
rails spec:routing                       # Run the code examples in spec/routing
rails spec:services                      # Run the code examples in spec/services
rails stats                              # Report code statistics (KLOCs, etc) from the application or engine
rails test                               # Runs all tests in test folder except system ones
rails test:db                            # Run tests quickly, but also reset db
rails test:system                        # Run system tests only
rails time:zones[country_or_offset]      # List all time zones, list by two-letter country code (`rails time:zones[US]`), or list by UTC offset (`rails time:zones[-8]`)
rails tmp:clear                          # Clear cache, socket and screenshot files from tmp/ (narrow w/ tmp:cache:clear, tmp:sockets:clear, tmp:screenshots:clear)
rails tmp:create                         # Creates tmp directories for cache, sockets, and pids
rails update_date_listing                # Update date in listing with last version
rails update_metro_distance              # Update distance to metro
rails versions_filter                    # Delete empty records in PaperTrail::Version table
rails webpacker                          # Lists all available tasks in Webpacker
rails webpacker:binstubs                 # Installs Webpacker binstubs in this application
rails webpacker:check_binstubs           # Verifies that webpack & webpack-dev-server are present
rails webpacker:check_node               # Verifies if Node.js is installed
rails webpacker:check_yarn               # Verifies if Yarn is installed
rails webpacker:clean[keep]              # Remove old compiled webpacks
rails webpacker:clobber                  # Remove the webpack compiled output directory
rails webpacker:compile                  # Compile JavaScript packs using webpack for production with digests
rails webpacker:info                     # Provide information on Webpacker's environment
rails webpacker:install                  # Install Webpacker in this application
rails webpacker:install:angular          # Install everything needed for Angular
rails webpacker:install:coffee           # Install everything needed for Coffee
rails webpacker:install:elm              # Install everything needed for Elm
rails webpacker:install:erb              # Install everything needed for Erb
rails webpacker:install:react            # Install everything needed for React
rails webpacker:install:stimulus         # Install everything needed for Stimulus
rails webpacker:install:svelte           # Install everything needed for Svelte
rails webpacker:install:typescript       # Install everything needed for Typescript
rails webpacker:install:vue              # Install everything needed for Vue
rails webpacker:verify_install           # Verifies if Webpacker is installed
rails webpacker:yarn_install             # Support for older Rails versions
rails yarn:install                       # Install all JavaScript dependencies as specified via Yarn
rails zeitwerk:check                     # Checks project structure for Zeitwerk compatibility

**Comment by eileencodes** [comment]
See https://github.com/rails/rails/pull/34078 where we tried to implement this but hit an issue with figuring out _what_ should happen on rollback.

**Comment by eprusakov** [comment]
@eileencodes  Thank you for the answer.

**Comment by rsl** [comment]
would also love to see a solution. we're using multiple databases and one is a legacy remote database which absolutely should not be migrated up and down. the inability to run db:rollback per database [or tell it to only rollback on primary] is really hurting. i may play around with using a local definition similar to https://github.com/rails/rails/pull/34078 though. thanks for linking that.

**Comment by eileencodes** [comment]
I've come up with a solution to this issue here https://github.com/rails/rails/pull/38770

**Comment by courtsimas** [comment]
@rsl @eprusakov a temporarily solution until this is officially in place in rails 6.1 is `rails db:migrate:down:secondary VERSION=<version>` and it'll rollback your secondary database (or whatever it's called) to the version you specify.

**Comment by czeise** [comment]
> @rsl @eprusakov a temporarily solution until this is officially in place in rails 6.1 is `rails db:migrate:down:<secondary db name> VERSION=<version>` and it'll rollback your secondary database (or whatever it's called) to the version you specify.

Kind of late to the party, but I'm sure there are plenty of others who haven't updated to 6.1 yet. I just wanted to point out that `rails db:migrate:down:secondary_db_name VERSION=<version>` Will revert the specified migration. So if you want to perform a `rails db:rollback STEP=3`, you'd actually need to run the above command for the 3 migrations you want to rollback.
