### ISSUE TITLE
ActiveSecret module request

### ISSUE THREAD

**Issue by tomsfernandez** [rails/rails#38522]
Hi! It would be great if Rails had a pluggable secrets/configuration architecture. It would be great if the user could choose where to load the app's secrets from and how.

A nice example is Spring framework's "Spring Cloud Config" that can use Github to store configurations and secrets.
Another use case is to use a secret server as the unique source of truth of secrets like Hashicorp Vault.

**Comment by eugeneius** [comment]
Thanks for the issue, but we don't accept feature requests on GitHub:

https://guides.rubyonrails.org/contributing_to_ruby_on_rails.html#what-about-feature-requests-questionmark
