### ISSUE TITLE
[Feedback Requested] Enabling/Disabling Rails Components requires config changes

### ISSUE THREAD

**Issue by mvastola** [rails/rails#38544]
So I'm hoping to make a PR to fix what is for me an occasional annoyance, but I wasn't sure what approach (if any) would be preferred. I was hoping to get feedback as to this before I get started on the PR.

### The Problem
When disabling certain rails components within `rails new`, the default configuration entries for these disabled components are not set in `config/environments/*.rb`. 

Further, when disabling components later on (by changing the `require`s inside `config/application.rb`), errors in `config/environments/*.rb` are often unavoidable because [`Rails::Railtie::Configuration#method_missing`](https://github.com/rails/rails/blob/8dca5162f9a213fb03b5a74f67924df1c23755e4/railties/lib/rails/railtie/configuration.rb#L90) will raise an error that -- for example, `config.action_mailer` -- does not exist.

The a similar issue occurs in reverse when enabling a rails component that wasn't enabled when `rails new` was run -- the default configuration for this new component is not readily available and a user is left with copying the default config from another app, or some similar process.

Instead, zero configuration changes should be needed to disable a component, or to get the default configuration for a new component, and I am hoping to make a PR to change this.

### Possible Fixes

I can think of a bunch of ways to fix this problem, but they go in different directions, so I wanted to know which is preferred:

#### Solution 0
Add rake tasks to enable/disable components. Disabling can optionally either comment or remove current settings, and enabling can optionally either uncomment or add default settings.

##### Pros
1. Quick and easy
2. Solves problem entirely
##### Cons
1. Users will have to learn to run the rake task this rather than simply remove the line in `config/application.rb`
2. Requires adding a bunch of rake tasks, and I'm not sure if the enable rake task can be defined inside the component (not sure if it will be listed if the component isn't loaded).
3. The syntax for passing arguments to rake tasks is a bit awkward.

#### Solution 1
Modify [`Rails::Railtie::Configuration#method_missing`](https://github.com/rails/rails/blob/8dca5162f9a213fb03b5a74f67924df1c23755e4/railties/lib/rails/railtie/configuration.rb#L90) to add and return an empty `ActiveSupport::OrderedOptions`  if the requested key is not present.

*(NB: The same must also be done in `ActiveSupport::OrderedOptions`, as many config values are nested.)*

##### Pros
1. Quick and easy
2. Solves problem entirely
3. No issues with readability

##### Cons
1. Errors will no longer be thrown for typoed component names (though typos are already silently ignored when the typo occurs in the last part of the setting's name).
2. Can cause issues if the truthiness of a value that doesn't have an initial value is queried anywhere. (Possible workarounds: use `#blank?` in place of checking truthiness; initialize all supported variables; add a predicate method to `Configuration`/`OrderedOptions` classes and use this instead; disable the change after initialization is done)

#### Solution 2
Refactor `config/environments` to contain `config/environments/[RAILS_ENV].d/[COMPONENT_NAME].rb` folders/files and split each component's configuration into its own file. Then only read the files corresponding to components that have been enabled (as well as, of course, `config/environments/[RAILS_ENV].rb`).
##### Pros
1. Clean, easy, intuitive, modular solution (and quick after setup).
2. Solves problem entirely
3. No issues with readability
4. This could actually lead to the simplification of config because there might be some modules that share the same configuration across environments (Could potentially make an `config/environment.d` folder for non-env-specific defaults.)
5. Simplifies merge conflicts when config is changed.
##### Cons
1. Arguably needlessly modular since most files will only contain a couple of lines (though this is also the case in `config/initializers`).
2. Some additional coding will need to be done if we're to help port users' config to the new system.
3. Users won't be able to re-order the reading of the files easily in rare cases where that's a need (though we could support prefixing the filenames with `[0-9]+-`).

#### Solution 3
Surround all config options for disable-able components in `if defined?(...`
##### Pros
1. Quick and easy
2. Solves problem completely
##### Cons
1. Makes configuration much less readable and will probably double the size of the files

#### Solution 4
Add config for disabled components as comments in `config/environments/*.rb`
##### Pros
1. Quick and easy
##### Cons
1. Still requires manual work when enabling/disabling components

**Comment by rafaelfranca** [comment]
I'm not sure this is a problem that needs a solution. You only remove or add a component once, so I think it is ok to method_missing raise an error for configs that are not valid anymore.

In terms of adding new components, most defaults are already the default, so you don't even need to configure the components. If they are not that is what we should be fixing.

**Comment by simi** [comment]
IMHO the only thing we can do in here is to properly document this behaviour (the same way we do in here for example - https://guides.rubyonrails.org/i18n.html#providing-translations-for-internationalized-strings - when you add new locales file).

I don't think there's any guide realted to enabling/disabling part of framework, but maybe we can consider introduce one explaining this problem as well.

**Comment by mvastola** [comment]
> In terms of adding new components, most defaults are already the default, so you don't even need to configure the components. If they are not that is what we should be fixing.

@rafaelfranca, This would be a good solution, but is that true re: most defaults? AFAIK, components don't initialize to different configs based on `RAILS_ENV`, but they probably should. 

This would allow making the initial settings placed in the `config/environments/*.rb` files the default. Then those files could be left completely commented out, so users can see what defaults are set and have the ability to simply uncomment to set a new value.

**Comment by mvastola** [comment]
@simi, I'd say this is a bit different though. There is much more of a template to the environment configs than there is to i18n translations. Yeah, we could make documentation for this (and perhaps there should be to some extent), but you don't want to require people to copy/paste from the docs into 3 different files whenever they enable a component.
