### ISSUE TITLE
 Improper example sentence about javascript_tag

### ISSUE THREAD

**Issue by erysk** [rails/rails#38556]
The `<javascript>` tag that does not include the `src` attribute must not add the `defer` attribute.
So isn't the following example inappropriate?

https://github.com/rails/rails/blob/d2ae2c3103e93783971d5356d0b3fd1b4070d6cf/actionview/lib/action_view/helpers/javascript_helper.rb#L49-L66

I think this example should be written in [`#javascript_include_tag`](https://github.com/rails/rails/blob/d2e8b839d2e7236b5f85797f239b01ca2e783024/actionview/lib/action_view/helpers/asset_tag_helper.rb#L86).

**Comment by gmcgibbon** [comment]
You are [correct](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/script), this is a bad example. I'll fix it!

As for `javascript_include_tag`, the docs mention this: https://github.com/rails/rails/blob/d2e8b839d2e7236b5f85797f239b01ca2e783024/actionview/lib/action_view/helpers/asset_tag_helper.rb#L35-L36
I think that's hint enough that you can use defer (and other attributes with it.
