### ISSUE TITLE
ActionText: Doesn't support Rails6 multiple databases properly

### ISSUE THREAD

**Issue by pnomolos** [rails/rails#38567]
### Steps to reproduce
Run `rails action_text:install` and move migrations to your `db/blogs_db` folder.

Model with the following:
```ruby
class BlogPost
  connects_to database: {writing: :blogs_db, reading: :blogs_db}
  has_rich_text :content
end
```

### Expected behavior
Should load the rich text content without an error.

### Actual behavior
Because rich text is stored in a separate table and `ActionText::RichText` is used as the class for all of these, lookups always happen in the primary DB.

```
> BlogPost.first.content
ActiveRecord::StatementInvalid: PG::UndefinedTable: ERROR:  relation "action_text_rich_texts" does not exist
LINE 8:  WHERE a.attrelid = '"action_text_rich_texts"'::regclass
```

### System configuration
**Rails version**: 6.0.2.1

**Ruby version**: 2.6.5-p114

**Sidenote:** Can someone explain the architectural justification for storing all the rich text elements in a separate table as opposed to on the model's table?  Is it to make configuration simpler so that you don't have to define a relationship for the purposes of `ActiveStorage`? (Presumably if things were stored on the table then you'd have to have some way of referencing the blobs for each rich text field?)

**Comment by pnomolos** [comment]
For anyone finding this, at the time of writing I worked around by doing the following:

1. Creating a subclass of `ActionText::RichText` that reference the secondary database directly
2. Copy the method definition from https://github.com/rails/rails/blob/6a5c8b91998c56e50b5cc934d968947cd319f735/actiontext/lib/action_text/attribute.rb#L26 into a base model and changing the `class_name` attribute:


```ruby
module BlogsDb
  class ApplicationModel < ActiveRecord::Base
    extend ActiveSupport::Concern

    self.abstract_class = true
    connects_to database: {writing: :blogs_db, reading: :blogs_db}

    class_methods do 
      def has_rich_text(name)
        class_eval <<-CODE, __FILE__, __LINE__ + 1
          def #{name}
            rich_text_#{name} || build_rich_text_#{name}
          end
          def #{name}=(body)
            self.#{name}.body = body
          end
        CODE

        has_one :"rich_text_#{name}", -> { where(name: name) },
          class_name: "BlogsModels::ActionText::RichText", as: :record, inverse_of: :record, autosave: true, dependent: :destroy

        scope :"with_rich_text_#{name}", -> { includes("rich_text_#{name}") }
        scope :"with_rich_text_#{name}_and_embeds", -> { includes("rich_text_#{name}": { embeds_attachments: :blob }) }
      end
    end
  end

  class ActionText::RichText < ActiveRecord::Base
    connects_to database: {writing: :blogs_db, reading: :blogs_db}
  end
end
```

**Comment by StanGC** [comment]
I encountered a similar problem.

My current workaround is to add an initializer file for the specific ActionText::RichText connection.

```ruby
# config/initializers/action_text.rb

Rails.application.config.to_prepare do
  ActionText::RichText.establish_connection(:blogs_db)
end
```

**System configuration**
- Rails version: 6.1.7.3
- Ruby version: 3.0.5
