### ISSUE TITLE
.present? on an ActiveRecord object triggering after_save callback

### ISSUE THREAD

**Issue by usamanasirqb** [rails/rails#38561]
### Steps to reproduce
Hi, I am currently working on a project in rails and I have two models, `Foo` and `Bar`. Their relation is `Foo` belongs to `Bar`.

### Expected behavior
Whenever I try to call `.present?`, it shall tell me that specific object is present or not? For my given scenario, `Foo.first.bar.present?` shall only tell me if `bar` for for that `foo` is present or not.

### Actual behavior
Calling `Foo.first.bar.present?` is triggering `.save` on `bar` object which is making difficulties for me as there are some callbacks which may take time updating heavy data after saving a specific `bar` object. Screenshot link available below 
https://share.getcloudapp.com/d5u0bykB

### System configuration
**Rails version**:
Rails 5.0.7.2
**Ruby version**:
ruby 2.4.4p296 (2018-03-28 revision 63013) [x86_64-darwin18]

**Comment by qumberali22** [comment]
Facing same issue

**Comment by gmcgibbon** [comment]
Please provide a test case demonstrating the issue. You can use [this template](https://github.com/rails/rails/blob/master/guides/bug_report_templates/active_record_master.rb).

**Comment by fabriziobertoglio1987** [comment]
[`.present?` belongs to `ActiveSupport`][1], I will investigate the relationship between the scope `.pending_po` and the `.present?` method. 

Any idea on how the Rails Source Code does that?

Thanks

[1]: https://stackoverflow.com/a/13186788/11452286

**Comment by gmcgibbon** [comment]
@fabriziobertoglio1987  [here is where present? is defined](https://github.com/rails/rails/blob/6d0895a4894724e1a923a514daad8fb3c9ac2c28/activesupport/lib/active_support/core_ext/object/blank.rb#L25). Also, there's [an active record override](https://github.com/rails/rails/commit/cc2d614e6310337a9d34ede3e67d634d84561cde#diff-8b4f70704dff8af7822a94f8d6b570f4) but that isn't in Rails 5, only 6. I don't see any relation to  save callbacks, so the issuer is likely dealing with a monkey-patch in their codebase.

**Comment by fabriziobertoglio1987** [comment]
@gmcgibbon thanks for the explanation and I agree with you.
