### ISSUE TITLE
Blocking transactions in test environment with row locks

### ISSUE THREAD

**Issue by fanktom** [rails/rails#38578]
Hey there,

I want to create a simple worker/job queue like system with threads, based on db row level locks `SELECT FOR UPDATE SKIP LOCKED` on a postgres database. When I run the described code in the dev environment, e.g. via `rails runner` everything works fine, when I run the same code in a test, the second transaction blocks until the first has finished.

Are transactions in the test environment behaving differently?
Does this have to do with test parallelization settings?
Thanks a lot for any hint!

I know I could use `ActiveJob`, however our use case is much more complicated than the illustrated question.

### Steps to reproduce
1. Create a simple `Job` model, attributes are irrelevant - empty is enough
2. Create two worker threads that select a job using locks. This code works if run with `rails runner` but not if in a test suite (default rails minitest):

```ruby
raise "there should be 1 job" unless Job.count == 1

# used to signal between threads
mux = Mutex.new

# actually a worker, but to simplify just a thread
Thread.new do
  mux.lock
  ActiveRecord::Base.connection_pool.with_connection do
    ActiveRecord::Base.transaction do
      raise "should own the mux" unless mux.owned?

      # claim a job
      job = Job.lock("FOR UPDATE SKIP LOCKED").first
      raise "job is nil" if job.nil?

      # signal other thread we are processing
      mux.unlock

      # simulate processing of job
      sleep 10
    end
  end
end

# allow first thread to lock the mutex
sleep 2

# actually a worker, but to simplify just a thread
Thread.new do
  ActiveRecord::Base.connection_pool.with_connection do
    ActiveRecord::Base.transaction do
      # wait for other thread to unlock "process a job"
      mux.lock

      # claiming a job should return nil
      job = Job.lock("FOR UPDATE SKIP LOCKED").first
      raise "job is not nil" unless job.nil?
    end
  end
end.join
```

### Expected behavior
- Both transactions should be run in parallel
- The first transaction should lock the row for 10 seconds
- The second transaction should respond with `nil`
- This is exactly the behavior when running in the rails console or with rails runner

### Actual behavior
- The first transaction locks the row for 10 seconds
- The second call `Job.lock...` blocks until the 10 seconds are over, then it is able to lock the row itself
- This happens only when run with the normal rails test suite

### System configuration
**Rails version**: 6.0.2.1

**Ruby version**: 2.6.5p114

**Comment by eileencodes** [comment]
> Are transactions in the test environment behaving differently?

Yea, transactions in a test env are very different from a production / development env. For starters transactions remain open for the life of a test so they can rollback data. Try setting `self.use_transactional_tests = false`

> Does this have to do with test parallelization settings?

Did you try turning parallelization off? Set `PARALLEL_WORKERS=0` or comment out the code in the test helper.

**Comment by fanktom** [comment]
Oh, you are a genius! I extracted the test case into an explicit test class and set `self.use_transactional_tests = false` as you suggested, and it worked perfectly!

Thank you very much!

One question: Can we maybe add this information into the rails testing guide in https://guides.rubyonrails.org/testing.html ?
Currently, there is no mention (CMD+F) of transactions at all, maybe a simple sentence like:

> When testing transactional code, be aware that the test environment may behave different than other environments as each test is already wrapped into a transaction. This can be changed with `self.use_transactional_tests = false` when needed.

But maybe its just me missing this :)

**Comment by eileencodes** [comment]
Glad that solve your problem 😊 

> Oh, you are a genius! I extracted the test case into an explicit test class and set self.use_transactional_tests = false as you suggested, and it worked perfectly!

FYI you will need to delete the data this test creates/updates because it will live across tests since there's no transaction to roll it back.

> One question: Can we maybe add this information into the rails testing guide in https://guides.rubyonrails.org/testing.html ?

Sure thing. Do you want to open a PR? Otherwise I can get to it later today. Guides content lives here https://github.com/rails/rails/tree/master/guides/source

**Comment by fanktom** [comment]
Cool, sure I can open a PR. I will not be able to submit it today (different timezone :) but tomorrow should work.

Thanks a lot!

**Comment by fanktom** [comment]
@eileencodes I created a PR https://github.com/rails/rails/pull/38602 and added a section on parallel testing of transactions.

Can I improve it somehow?
Please feel free to change and adapt it to your likes and thanks a lot for your help!

**Comment by fanktom** [comment]
Thanks a lot for your help!
