### ISSUE TITLE
Rollback transaction does not clean created :has_one relationships

### ISSUE THREAD

**Issue by jpac-run** [rails/rails#38579]
### Steps to reproduce

Given 3 models, `Post`, `Avatar` and `User`:

```ruby
class User < ApplicationRecord
  has_one :avatar
  has_many :posts
end

class Avatar < ApplicationRecord
  belongs_to :user
end

class Post < ApplicationRecord
  belongs_to :user
end
```

And a script that creates some posts and an avatar to a user:

```ruby
def execute_test
  create_a_user
  
  @user = User.last
  
  ActionRecord::Base.transaction do
    add_some_posts_and_avatar
  end
rescue Exception => e
  puts e.message
ensure
  @user.avatar.imagename # will return "my_avatar.png"
  @user.posts # will return []
end

def create_a_user
  User.create(name: "John Doe")
end

def add_some_posts_and_avatar  
  ActiveRecord::Base.transaction do
    Post.create(title: "Post 1", user: @user)
    Post.create(title: "Post 2", user: @user)
    Avatar.create(imagename: "my_avatar.png", user: @user)
    raise Exception
  end
end

execute_test
```

### Expected behavior

When accessing the `@user` instance inside the `ensure` block, an empty relationship of `Post` and no instance of `Avatar` should be returned, after the transaction rollback.

Both `has_many` and `has_one` relations are cleaned.

### Actual behavior

When accessing the `@user` instance inside the `ensure` block, an empty relationship of `Post` is returned (`@user.posts`) __but__ an instance of `Avatar` still exist (`@user.avatar`) with no `id`. The `has_many` relationship is cleaned but not the `has_one`, after a rollback occurs.

### System configuration
**Rails version**:
5.2.4.1 or master
**Ruby version**:
2.5.7

**Comment by sic-f** [comment]
Was able to reproduce this with Rails 6.0.2.2 and Ruby 2.6.5

**Comment by sic-f** [comment]
> Was able to reproduce this with Rails 6.0.2.2 and Ruby 2.6.5
> 
> `@user.avatar.imagename` returns `"my_avatar.png"`
> `@user.posts` returns `#<ActiveRecord::Associations::CollectionProxy []>`

Actually, tested this again but now the expected behaviour is working. (Rails 6.0.2.2, Ruby 2.6.5). Can't reproduce the said bug anymore and now seems to be working fine, as expected.

**Comment by jonathanhefner** [comment]
Thank you for investigating this issue.  In order to debug issues, it is helpful for Rails volunteers to have a reproduction script to work with.  Here is a [reproduction script template](https://github.com/rails/rails/blob/master/guides/bug_report_templates/active_record_gem.rb) for Active Record-related issues.  I've filled it out for this particular issue, and can confirm the behavior you are seeing:

<details>
  <summary>Reproduction script for non-nil has_one</summary>

  ```ruby
  # frozen_string_literal: true

  require "bundler/inline"

  gemfile(true) do
    source "https://rubygems.org"

    git_source(:github) { |repo| "https://github.com/#{repo}.git" }

    # Activate the gem you are reporting the issue against.
    gem "activerecord", "6.0.2.2"
    gem "sqlite3"
  end

  require "active_record"
  require "minitest/autorun"
  require "logger"

  # This connection will do for database-independent bug reports.
  ActiveRecord::Base.establish_connection(adapter: "sqlite3", database: ":memory:")
  ActiveRecord::Base.logger = Logger.new(STDOUT)

  ActiveRecord::Schema.define do
    create_table :users, force: true do |t|
      t.string :name
    end

    create_table :avatars, force: true do |t|
      t.string :imagename
      t.references :user
    end

    create_table :posts, force: true do |t|
      t.string :title
      t.references :user
    end
  end

  class User < ActiveRecord::Base
    has_one :avatar
    has_many :posts
  end

  class Avatar < ActiveRecord::Base
    belongs_to :user
  end

  class Post < ActiveRecord::Base
    belongs_to :user
  end


  class BugTest < Minitest::Test
    def test_it
      user = User.create!(name: "John Doe")

      ActiveRecord::Base.transaction do
        Post.create(title: "Post 1", user: user)
        Post.create(title: "Post 2", user: user)
        Avatar.create(imagename: "my_avatar.png", user: user)

        raise ActiveRecord::Rollback
      end

      assert_empty user.posts # this passes
      assert_nil user.avatar # this fails
    end
  end
  ```
</details>

However, I think this is actually correct behavior.  At least, it is consistent with how attributes behave after rollback (see #35987).

I believe the unexpected behavior is that the `has_many` association is "cleared".  But I think this is just an unfortunate effect of how `ActiveRecord::Associations::CollectionProxy` works.  If, instead, you add records directly to the association, they will remain as unpersisted records after the rollback:

```ruby
def test_retain_has_many
  user = User.create!

  ActiveRecord::Base.transaction do
    user.posts << Post.new(title: "foo")
    raise ActiveRecord::Rollback
  end

  assert_nil user.posts[0].id
  assert_equal "foo", user.posts[0].title
end
```
