### ISSUE TITLE
keeps on generating new thread for ActiveRecord establish connection

### ISSUE THREAD

**Issue by kumaranubhaw** [rails/rails#38582]
### Steps to reproduce
when establish_connection is called, thread will be generated to communicate to the database. once the database transaction completes the thread is still active.

ActiveRecord::Base.establish_connection db_config

### Expected behavior
once the database transaction completes the thread should get killed and on calling establish_connection again, should generate new thread.

### Actual behavior
On establish_connection by active record, the thread generated is not killed after database transaction completes and when again establish_connection is called another new thread is generating. So the thread count keeps on increasing unless restarting server.

### System configuration
**Rails version**: 5.2.3

**Ruby version**: 2.6.5

**Comment by rafaelfranca** [comment]
Every time you call `establish_connection` you are creating a connection poll and connection pools don't die when you create a new one. Each connection pool has a connection reaper thread that reclaim unused connections inside that pool. If you don't want those reaper threads to be created, you can set the `reaping_frequency` config in your database to `0`.

If you still want the reaper running but don't want to have all the connection pools running you should disconnect the pools before connecting to a new one.

https://api.rubyonrails.org/classes/ActiveRecord/ConnectionAdapters/ConnectionPool.html#method-i-disconnect

**Comment by kumaranubhaw** [comment]
Thank you @rafaelfranca  it worked fine.
