### ISSUE TITLE
ActiveJob perform_enqueued_jobs filters out enqueued jobs

### ISSUE THREAD

**Issue by dmitry** [rails/rails#38584]
ActiveJob `perform_enqueued_jobs` must not filter out jobs which should go to the enqueued jobs list.

### Steps to reproduce

```ruby
# frozen_string_literal: true

require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  # Activate the gem you are reporting the issue against.
  gem "activejob", "6.0.0"
end

require "minitest/autorun"
require "active_job"

class PerformJob < ActiveJob::Base
  def perform
    puts "performed"
  end
end

class EnqueueJob < ActiveJob::Base
  def perform
    puts "performed"
  end
end

class EnqueueJobTest < ActiveJob::TestCase
  def test_stuff
    perform_enqueued_jobs(only: PerformJob) do
      assert_enqueued_with(job: EnqueueJob) do
        PerformJob.perform_later
        EnqueueJob.perform_later
      end
    end
  end
end
```

### Expected behavior

While using `perform_enqueued_jobs` enqueued jobs must be stored for the later check with `assert_enqueued_with`.

### Actual behavior

Current behaviour filters out all the jobs which are not being performed. Because of that you are not able to make an `assert_enqueued_with` of the jobs were not included in `only` option.

### System configuration
**Rails version**: 6.0
**Ruby version**: 2.6.1

**Comment by rafaelfranca** [comment]
That makes sense. Are you willing to investigate and write a PR to fix it? Thanks!

**Comment by dmitry** [comment]
@rafaelfranca please let me know if everything is fine or it requires any changes.

**Comment by dmitry** [comment]
@rafaelfranca please let me know if everything is fine or it requires any changes.

**Comment by dmitry** [comment]
@rafaelfranca please let me know if everything is fine or it requires any changes.
