### ISSUE TITLE
ActionView::Template::Error: Missing host to link to! in production

### ISSUE THREAD

**Issue by tee** [rails/rails#38596]
First, I'd like to say this is the first issue I have listed with Rails so I apologize if this is in the wrong place. 

I am currently using Sidekiq with Action Mailer to send emails. About 8 or 9 days ago I started getting the following error message:
`ActionView::Template::Error: Missing host to link to! Please provide the :host parameter, set default_url_options[:host], or set :only_path to true`

My application is hosted on Heroku so I booted into a console and checked out the config with Rails.application.config.action_mailer.default_url_options. The result, `{:host=>"pdtracker.syllabushq.com", :protocol=>"https"}`, shows that there is indeed a host.

I will also say this app is hosted on Heroku, I filed a ticket with them and they claim this is a Rails issue related to ActionView as the error suggests. I have attempted to add the following to my `production.rb` file and it threw the same error when trying to process the job.

`Rails.application.routes.default_url_options[:host] = 'pdtracker.syllabushq.com'`

### Steps to reproduce

My ActionMailer config is as follows:
```
config.action_mailer.default_url_options = { host: 'pdtracker.syllabushq.com' }
config.action_mailer.delivery_method = :smtp
config.action_mailer.perform_deliveries = true
config.action_mailer.raise_delivery_errors = false
config.action_mailer.smtp_settings = {
    port:                        587,
    address:                 'smtp.gmail.com',
    user_name:            ENV['EMAIL_USERNAME'],
    password:              ENV['EMAIL_PASSWORD'],
    domain:                  'syllabushq.com',
    enable_starttls_auto: true,
    authentication:       'login'
}
```
I see there are existing issues related to this that have been marked as closed but they seem to be related to the test env, not production. 

### Expected behavior

I expect Sidekiq to process the job in such a way that makes the mail send to the correct user.

### Actual behavior

I get the following error message when I create a Sidekiq job that sends an email.
`ActionView::Template::Error: Missing host to link to! Please provide the :host parameter, set default_url_options[:host], or set :only_path to true`

### System configuration
**Rails version**: 6.0.2.1

**Ruby version**: ruby 2.7.0p0

**Comment by cupnoodle** [comment]
@tee do you manage to fix or find a workaround for this? I am facing the same issue

**Comment by tee** [comment]
@cupnoodle Oddly enough, Heroku was appending a new line `\n` at the end of one of my ENV vars that was causing this issue. I was able to just delete the entire ENV var within Heroku itself and add it back. That fixed my issue. I hope that helps.
