### ISSUE TITLE
Rails 5.1.4 active storage MissingModelIdError

### ISSUE THREAD

**Issue by prasanna-munnangi** [rails/rails#38607]
Hey folks,
Rails newbie here. I am trying to upload a file to S3 via active storage through a background job. Set up everything as mentioned in this article [(https://keithpblog.org/post/active-storage-on-amazon-s3/.)](url)
When I run the background job I get this error. Searched google but I couldn't find anything relevant.
Can someone please help me out?

The below is how my model looks

```
class ReportOutput < ApplicationRecord
  has_one_attached :output_file
end
```

This is how I am calling it. (not sure if this is correct). Pretty sure the file exists.

`ReportOutput.new.output_file.attach(io: File.open('./test.xlsx'), filename: 'test.xlsx')
`
### Expected behavior
Should upload the file and store in the active storage tables on local ( thats what I think it should do?)

### Actual behavior
`Job exception: #<URI::GID::MissingModelIdError: Unable to create a Global ID for ReportOutput without a model id.>`

### System configuration
**Rails version**: 5.1.4

**Ruby version**: 2.5.3

**Comment by joshmn** [comment]
The design of `attach` expects `ReportOutput` to persist (be saved to the database already).

**Comment by prasanna-munnangi** [comment]
@joshmn , ok do you happen to know whats the correct way to actually upload a file to active storage through a background job process?

**Comment by joshmn** [comment]
@prasanna-munnangi because ActiveStorage expects a persisted record to attach a/file(s) to it wouldn't be the most optimal approach, but if you want to use it you could simply have an `Upload` AR class, create a new record, save it, and then attach a file to it.

Again there are more optimal solutions but that would be the most straightforward for your use-case.
