### ISSUE TITLE
Could not find gem 'sqlite3 (~> 1.4) x64-mingw32' in any of the gem sources listed in your Gemfile.

### ISSUE THREAD

**Issue by alakameljebali** [rails/rails#38626]
### Steps to reproduce

Create new Ruby on Rail project by running "rails new blog"
### Expected behavior

Creating project without any error or exception
### Actual behavior

Cli throw an error:
"Could not find gem 'sqlite3 (~> 1.4) x64-mingw32' in any of the gem sources listed in your Gemfile.
Run `bundle install` to install missing gems."
### System configuration
**Rails version**: Rails 6.0.2.1
**Ruby version**: ruby 2.6.5p114 (2019-10-01 revision 67812) [x64-mingw32]

**Comment by rafaelfranca** [comment]
Thank you for the issue but this is not an issue on Rails. Make sure your environment is correct. I also think this is an issue on sqlite3 that doesn't released a gem for the x64-mingw32 platform. Please report there.

**Comment by EmeraldNZ** [comment]
I had the same error and fixed it this way if I remember correctly :)  First, I ran gem install sqlite3 -v 1.4 on terminal. Then, I downloaded Yarn from https://classic.yarnpkg.com/en/docs/install/#windows-stable

My system configuration

ruby 2.6.5p114 (2019-10-01 revision 67812) [x64-mingw32]
Rails 6.0.2.2
Bundler version 1.17.2

C:\Users\User>gem -v
3.0.3

C:\Users\User>yarn -v
1.22.4

Retrived from https://stackoverflow.com/questions/54611615/error-could-not-find-sqlite3-1-4-0-in-any-of-the-sources

**Comment by codessive** [comment]
I had a similar issue. I ran bundle install in terminal it was resolved.

**Comment by thel0ner** [comment]
maybe you should choose a aqlite3 gem version which is compatible with your ruby env? [stackoverflow](https://stackoverflow.com/questions/54611615/error-could-not-find-sqlite3-1-4-0-in-any-of-the-sources)

**Comment by naagaraa** [comment]
i got same issue when first starting project. this step what i do

```
choco upgrade msys2 # run with administrator at powershell
ridk install # update choose 3 , 2 , 1
bundle update
bundle install

=========== and then ==============

rails secret
rails server
```

**Comment by khaledmv** [comment]
Update ruby version
-> update the ruby version on Gemfile like -- ruby "3.1.2"
-> bundle update
-> add Gemfile  --   gem "tzinfo-data"
-> bundle install 

I hope it will work perfectly
