### ISSUE TITLE
Activerecord loose parameters in mysql requests in RACK_ENV=production

### ISSUE THREAD

**Issue by se0ga** [rails/rails#38622]
We are trying to migrate from rails 4 to rails 5 and
have an error, where it says we have a null violation for one of our fields: created_at
in this code:

    version_set.each_with_index do |version_from_set, index|
      ...
      version_name = version_from_set['version_name']
      new_version = Version.new
      new_version.name = version_name
      new_version.save
      ...
    end
Error:
> ActiveRecord::NotNullViolation (Mysql2::Error: Field 'created_at' doesn't have a default value: INSERT INTO versions (updated_at) VALUES ('2020-02-25 10:55:50')) We are thinking about upgrading mysql - but not convinced that this is the issue. And it's not easy to upgrade it in AWS Elastic Beanstalk Schema.db

Its working fine with RACK_ENV=development but error appear in RACK_ENV=production.

Error with stack of requests in RACK_ENV=production:
[![enter image description here][1]][1]

1. Error
2. Requests should be the same but every request was cut of of one parameter
and in the last request there are only one parameter.

This is how it looks with RACK_ENV=development. All parameters was provided:

[![enter image description here][2]][2]

We desperate. We spend couple weeks trying to track this error. Any suggestions?
Rails 5.0.7.2 (5.2.4.1 the same)
mysql2 0.4.10(0.5.2 the same)
Ruby 2.6.5

  [1]: https://i.stack.imgur.com/3FqYV.png
  [2]: https://i.stack.imgur.com/Z91GA.png

**Comment by eileencodes** [comment]
I don't think this has anything to do with RACK_ENV. It has to do with your mysql version + Rails.

The error means that the created_at field requires a value and you don't have a default value. Your last request is inserting a version with an updated at and no created at, so it throws an error. You didn't say what version of MySQL you're using but if you're using 5.6 or higher you can use NOW() as your default.

This isn't a Rails bug so I'm going to close this. Good luck and hope that helps.
