### ISSUE TITLE
ActiveJob::Serializers::ObjectSerializer documentation error

### ISSUE THREAD

**Issue by kwerle** [rails/rails#38629]
The arguments listed in the serialize and deserialize methods are reversed.

https://api.rubyonrails.org/classes/ActiveJob/Serializers/ObjectSerializer.html#method-i-deserialize
says `deserialize(_argument)` should say `deserialize(hash)`

https://api.rubyonrails.org/classes/ActiveJob/Serializers/ObjectSerializer.html#method-i-serialize
says `serialize(hash)` should say `serialize(argument)`

**Comment by rafaelfranca** [comment]
Where are you seeing that?

The documentation show:

```
class MoneySerializer < ActiveJob::Serializers::ObjectSerializer
  def serialize(money)
    super("amount" => money.amount, "currency" => money.currency)
  end

  def deserialize(hash)
    Money.new(hash["amount"], hash["currency"])
  end

  private

    def klass
      Money
    end
end
```

And that is correct. Isn't?

**Comment by rafaelfranca** [comment]
Ah. I see what you mean. The documentation is still correct. `ObjectSerializer#serialize` expects a hash. And `ObjectSerializer#deserialize` expects one argument, but it can be anything since that method is abstract.

**Comment by kwerle** [comment]
@rafaelfranca 
`serialize` serializes an object *to* a hash (as shown in the example)
`deserialize` deserializes a hash to an object.

The sample code gets it correct.  The actual code parameters are less correct.

**Comment by rafaelfranca** [comment]
> `serialize` serializes an object _to_ a hash (as shown in the example)

The `serialize` of your superclass, yes, but the serialize of `ActiveJob::Serializers::ObjectSerializer` receives an hash and return a hash. This is why you can call `super` with a hash in the example implementation (`super("amount" => money.amount, "currency" => money.currency)`)

The `deserialize` method indeed accepts a hash, but `_argument` can also be a hash, so it is not incorrect. It could be more specific though. And I'm fine with changing that one if you want to open a PR.
