### ISSUE TITLE
ActiveRecord Attributes is better returning HashWithIndifferentAccess

### ISSUE THREAD

**Issue by yoelblum** [rails/rails#38621]
### Steps to reproduce

`user.attributes[:name]`

### Expected behavior

It's better if attributes returned HashWithIndifferentAccess so user[:name] works.
I had a long head scratching until I figured out what was wrong. Looking at the first comment here https://apidock.com/rails/ActiveRecord/Base/attributes , I do see that this is happening to other people. Rails controller params are HashWIthIndifferentAccess (or at least complying with it's api) , so it's very possible it's adding to the confusion. I think that if Rails chose to use HashWithIndifferentAccess to some of it's hashes, it's best to be consistent.
### Actual behavior

```
user[:name] # nil
user['name'] #joe
```
### System configuration
**Rails version**:

**Ruby version**:

**Comment by kaspth** [comment]
Not everything has to be an HWIA and `attributes` isn't. Don't think we should add this, thanks!

**Comment by yoelblum** [comment]
OK, thanks for the clarification.
But maybe in the future the core team should give thought to what should
and shouldn't be HWIA, this is very confusing and causes annoying bugs.
