### ISSUE TITLE
NullStore caches values despite "development mode no longer being cached"

### ISSUE THREAD

**Issue by topalovic** [rails/rails#38638]
Rails Guides [state](https://edgeguides.rubyonrails.org/caching_with_rails.html#caching-in-development) that "Rails provides the rails command dev:cache to easily toggle caching on/off".

This is not entirely true since `NullStore` still caches via `LocalCache`, so there is no way to disable low-level cache within the scope of a single web request, regardless of the toggle.

The [low-level caching docs](https://edgeguides.rubyonrails.org/caching_with_rails.html#low-level-caching) don't really help since they provide a model-level example, giving the impression of a generic mechanism independent of web requests or Rack middleware.

My questions are:

1. Why does `NullStore` implement the local cache strategy? Shouldn't it be a veritable bit bucket?
2. Why isn't `ActiveSupport::Cache::Strategy::LocalCache` also toggled via `rails dev:cache`?
3. At the very least, shouldn't this caveat be mentioned in Rails Guides, stating clearly that low-level cache still kicks in within the scope of a web request?

### Steps to reproduce

Create a new Rails app and make sure to disable local caching:

```
$ bin/rails dev:cache
Development mode is no longer being cached.
```

Add the following to the application layout or any view:

```
<pre>
<%= Rails.cache.fetch('foo') { rand } %>
<%= Rails.cache.fetch('foo') { rand } %>
</pre>
```

Run `bin/rails s` and visit the modified view.

### Expected behavior

I'd expect `Rails.cache.fetch` to return different values given that "development mode is no longer being cached".

### Actual behavior

`Rails.cache.fetch` still caches values.

### System configuration

**Rails version**: 6.0.2.1

**Ruby version**: 2.7.0p0

**Comment by jonathanhefner** [comment]
I believe the reason for this behavior is to prevent apps from behaving differently in development versus production (within the scope of a single request).  Anything can happen in cache blocks, so evaluating a block multiple times in development, but not in production, could lead to unexpected outcomes.

However, I agree the guide is misleading, so I submitted #39575.  Do you feel like those changes would alleviate confusion in the future?

**Comment by topalovic** [comment]
@jonathanhefner Hey Jonathan. I checked the PR and it looks good, thanks for addressing this 👍
