### ISSUE TITLE
plain 'rails new' raises while creating files

### ISSUE THREAD

**Issue by frenesim** [rails/rails#38639]
### Steps to reproduce
use ruby 2.5.0
gem install bundler:2.1.4
gem install rails:6.0.2.1
rails new r6 --skip-bundle

### Expected behavior
A new 'r6' folder with all rails files 

### Actual behavior
It raises an error while creating config/environments/test.rb.
`ruby/2.5.0/erb.rb:885:in` `eval': /home/hpinto/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/railties-6.0.2.1/lib/rails/generators/rails/app/templates/config/environments/test.rb.tt:10: syntax error,
 unexpected ')', expecting end-of-input (SyntaxError)
);  if spring_install? `

### Solution
I will create a PR to address this.

**Comment by rafaelfranca** [comment]
@frenesim thank you for the issue. Can you create the PR against the rails/rails repo? I'll merge it.
