### ISSUE TITLE
Public access on Disk service

### ISSUE THREAD

**Issue by lacf95** [rails/rails#38632]
### Steps to reproduce
1. Use `public` property on **Disk** service entry on `config/storage.yml` file.
1. Use any blob path/url helper that uses that storage service.

There is no reference on the guides nor on the code that dictates that Disk services don't support public/private access functionality.

https://edgeguides.rubyonrails.org/active_storage_overview.html#public-access

Anyway, if I update `activestorage/lib/active_storage/service/disk_service.rb` to allow extra options to be passed the url will be generated but won't create a different url than the existing one (kind of expected).

```ruby
def initialize(root:, **options)
  @root = root
end
```

### Expected behavior

Generates the public url for the given entity or document that there is no support for public/private access files on disk services.
### Actual behavior

Yields unknown keyword error:
```
ArgumentError: Cannot load `Rails.config.active_storage.service`:
unknown keyword: public
```
### System configuration
**Rails version**:
6.0.2.1
**Ruby version**:
2.5.7

**Comment by eileencodes** [comment]
The edge guides are for master and the feature isn't in 6.0 because we don't backport features. This feature was merged manually in https://github.com/rails/rails/commit/94584c2510743a45d9030d1b94dd33a074518b17 in October, so after 6.0 was released. It will be in 6.1 release, or you can build your gem from master.

**Comment by lacf95** [comment]
Thanks for your time @eileencodes , isn't a really urgent feature for me (no use of the disk service on production env).  I'll wait for 6.1 patiently
