### ISSUE TITLE
Following the guides and create a new project with ruby 2.5.0 fails

### ISSUE THREAD

**Issue by frenesim** [rails/rails#38649]
### Steps to reproduce
use ruby 2.5.0
gem install rails
rails new universe

### Expected behavior
A universe app is created

### Actual behavior
crashs during rails new script in `rails webpacker:install` with
`       rails  webpacker:install                                                                                                               `                                                                                           
`rails aborted!                                                                                                                                     `                                                                                      
`NameError: uninitialized constant URI::Generic                                                                               `                                                                                                            
`/home/hpinto/workspace/universe/config/application.rb:3:in `<top (required)>' `

### System configuration
Rails 6.0.2.1
Ruby 2.5.0

#### Proposal
I have tried with 2.5.1 and it works, so a fast and lazy fix is update the guides and replace the ruby version 2.5.0 to version 2.5.1.

If you agree I would create a PR for this guide update.

**Comment by rafaelfranca** [comment]
Do you have the full backtrace. This could be just a bug in Ruby 2.5.0 or a problem in your setup and Rails is not wrong about which version it supports.

**Comment by frenesim** [comment]
Yes. From the backtrace it seems to be a ruby bug, I have tried in different machines with different ubuntu version, to reduce the probability of being from my setup.
Should I tried to reproduce this in the ruby stack and report on ruby repo? If I succeed we still have the rails guides pointing to a crash in the meantime.
The impact is on newcomers sense and feel.

The first task to crash is webpacker installer. I remove bootsnap to reduce the amount of lines.
`
$ rails webpacker:install --trace                                                                                                                                                                  20-03-07 10:19  
rails aborted!                                                                                                                                                                                                     
NameError: uninitialized constant URI::Generic                                                                                                                                                                     
/home/humberto/.rbenv/versions/2.5.0/lib/ruby/2.5.0/uri/ftp.rb:23:in `<module:URI>'                                                                                                                                
/home/humberto/.rbenv/versions/2.5.0/lib/ruby/2.5.0/uri/ftp.rb:13:in `<top (required)>'                                                                                                                            
/home/humberto/.rbenv/versions/2.5.0/lib/ruby/2.5.0/uri.rb:107:in `<top (required)>'                                                                                                                               
/home/humberto/.rbenv/versions/2.5.0/lib/ruby/2.5.0/uri/rfc2396_parser.rb:13:in `<top (required)>'                              
/home/humberto/.rbenv/versions/2.5.0/lib/ruby/2.5.0/uri/common.rb:13:in `<top (required)>'                                             
/home/humberto/.rbenv/versions/2.5.0/lib/ruby/2.5.0/uri/generic.rb:12:in `<top (required)>'                                    
/home/humberto/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/activesupport-6.0.2.1/lib/active_support/core_ext/object/json.rb:6:in `<top (required)>'
/home/humberto/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/activesupport-6.0.2.1/lib/active_support/core_ext/object.rb:13:in `<top (required)>'
/home/humberto/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/railties-6.0.2.1/lib/rails/configuration.rb:4:in `<top (required)>'
/home/humberto/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/railties-6.0.2.1/lib/rails/railtie/configuration.rb:3:in `<top (required)>'
/home/humberto/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/railties-6.0.2.1/lib/rails/railtie.rb:223:in `config'
/home/humberto/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/railties-6.0.2.1/lib/rails/railtie.rb:127:in `config'
/home/humberto/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/activesupport-6.0.2.1/lib/active_support/i18n_railtie.rb:10:in `<class:Railtie>'
/home/humberto/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/activesupport-6.0.2.1/lib/active_support/i18n_railtie.rb:9:in `<module:I18n>'                                                                       
/home/humberto/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/activesupport-6.0.2.1/lib/active_support/i18n_railtie.rb:8:in `<top (required)>'
/home/humberto/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/activesupport-6.0.2.1/lib/active_support/railtie.rb:4:in `<top (required)>'
/home/humberto/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/railties-6.0.2.1/lib/rails.rb:18:in `<top (required)>'
/home/humberto/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/railties-6.0.2.1/lib/rails/all.rb:5:in `require'
/home/humberto/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/railties-6.0.2.1/lib/rails/all.rb:5:in `<top (required)>'
/home/humberto/workspace/rails6/config/application.rb:3:in `require'
/home/humberto/workspace/rails6/config/application.rb:3:in `<top (required)>'                                                                                                                                     
/home/humberto/workspace/rails6/Rakefile:4:in `require_relative'
/home/humberto/workspace/rails6/Rakefile:4:in `<top (required)>'
/home/humberto/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/rake-13.0.1/lib/rake/rake_module.rb:29:in `load'                                                                                                    
/home/humberto/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/rake-13.0.1/lib/rake/rake_module.rb:29:in `load_rakefile'
/home/humberto/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/rake-13.0.1/lib/rake/application.rb:703:in `raw_load_rakefile'
/home/humberto/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/rake-13.0.1/lib/rake/application.rb:104:in `block in load_rakefile'
/home/humberto/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/rake-13.0.1/lib/rake/application.rb:186:in `standard_exception_handling'
/home/humberto/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/rake-13.0.1/lib/rake/application.rb:103:in `load_rakefile'
/home/humberto/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/railties-6.0.2.1/lib/rails/commands/rake/rake_command.rb:22:in `block in perform'
/home/humberto/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/rake-13.0.1/lib/rake/application.rb:186:in `standard_exception_handling'
/home/humberto/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/railties-6.0.2.1/lib/rails/commands/rake/rake_command.rb:20:in `perform'
/home/humberto/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/railties-6.0.2.1/lib/rails/command.rb:48:in `invoke'
/home/humberto/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/railties-6.0.2.1/lib/rails/commands.rb:18:in `<top (required)>'
/home/humberto/workspace/rails6/bin/rails:9:in `require'
/home/humberto/workspace/rails6/bin/rails:9:in `<top (required)>'
/home/humberto/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/spring-2.1.0/lib/spring/client/rails.rb:28:in `load'
/home/humberto/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/spring-2.1.0/lib/spring/client/rails.rb:28:in `call'
/home/humberto/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/spring-2.1.0/lib/spring/client/command.rb:7:in `call'
/home/humberto/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/spring-2.1.0/lib/spring/client.rb:30:in `run'
/home/humberto/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/spring-2.1.0/bin/spring:49:in `<top (required)>'
/home/humberto/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/spring-2.1.0/lib/spring/binstub.rb:11:in `load'
/home/humberto/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/spring-2.1.0/lib/spring/binstub.rb:11:in `<top (required)>'
/home/humberto/.rbenv/versions/2.5.0/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
/home/humberto/.rbenv/versions/2.5.0/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
/home/humberto/workspace/rails6/bin/spring:15:in `<top (required)>'
bin/rails:3:in `load'
bin/rails:3:in `<main>'
`

**Comment by rafaelfranca** [comment]
Given it is a bug in Ruby, that is likely to be platform dependent, unless the guide is saying install Ruby 2.5.0, I don't think we need to change anything. Changing the required version will force people to upgrade, which they don't need to if their applications are working fine.

Is there anything in the guides indicating that newcomers should be using 2.5.0 and not 2.5.7? If there is, we should change that without changing the required ruby version.

**Comment by frenesim** [comment]
Understood. I personally use the latest stable for everything and it's probably the case for the majority. I'm dealing with some resistant to switch from .net core and it's leaving me paranoid.
I will try to contribute with something useful for the community.
Thanks for your time (and your work of course).
