### ISSUE TITLE
Referencing a non-existent asset with an accent in the filename causes a 500 error & no backtrace

### ISSUE THREAD

**Issue by matthewbloch** [rails/rails#38651]
This seems similar to #38056.

### Steps to reproduce

rails new accent_test
cd accent_test
rails webpacker:install
rails g controller test test
echo '<%= image_tag "problème" %>' >>app/views/test/test.html.erb 
rails server -p 3131 &
curl http://localhost:3131/test/test

### Expected behavior

I'd expect an ActionView::TemplateError on the helpful Rails error page. That's what happens if I don't put the accent in the filename, e.g. if I change the above to use "problem" instead of "problème":

```
ActionView::Template::Error (The asset "problem" is not present in the asset pipeline.):
    1: <h1>Test#test</h1>
    2: <p>Find me in app/views/test/test.html.erb</p>
    3: <%= image_tag "problem" %>
```

### Actual behavior

It looks like the "early stage" Rails error page instead, with no helpful information either on the page:

```
...
<body class="rails-default-error-page">
  <!-- This file lives in public/500.html -->
  <div class="dialog">
    <div>
      <h1>We're sorry, but something went wrong.</h1>
    </div>
    <p>If you are the application owner check the logs for more information.</p>
  </div>
</body>
</html>
```

...Or in the development log, which only shows:

```
Started GET "/test/test" for 127.0.0.1 at 2020-03-05 13:26:57 +0000
Processing by TestController#test as */*
  Rendering test/test.html.erb within layouts/application
  Rendered test/test.html.erb within layouts/application (Duration: 4.7ms | Allocations: 3825)
Completed 500 Internal Server Error in 6ms (ActiveRecord: 0.0ms | Allocations: 4154)
```

### System configuration
**Rails version**:
Rails 6.0.2.1

**Ruby version**:
ruby 2.6.3p62 (2019-04-16 revision 67580) [x86_64-linux]

**Comment by eileencodes** [comment]
Hey @matthewbloch thanks for the report. This was fixed in #38222 and will be released in 6.0.3
