### ISSUE TITLE
Enhancement: shorten the default index name on polymorphic references

### ISSUE THREAD

**Issue by lukeredpath** [rails/rails#38655]
Not a bug but more of a small enhancement - I'm willing to submit a PR for this but wanted some feedback first before I spent any time on it.

### Steps to reproduce

When you create a polymorphic reference in a migration, Rails will generate an index by default using a combination of the ID and type column as the index name (the default behaviour when specifying an index over multiple columns):

```
create_table :widgets do |t|
  t.references :factory, polymorphic: true
end
```

This will produce an index named `index_factories_on_widget_type_and_widget_id`.

Postgres has a limit of only 63 characters for its index name. The above index name is already 44 characters and your table and association names don't need to be much longer before you increase the likelihood of it failing due to the index name length. This happened to me today and it's happened to me on numerous occasions before in this specific scenario.

### Desired behavior

It's easily worked around by setting an explicit index name but in the name of "convention over configuration" it would make more sense if the default when using `references` was for it to use the *reference name*, making the index name in the above scenario:

`index_factories_on_widget`.

That's a 17 character difference and greatly reduces the chance of this happening in the first place (you typically only realise once you've run the migration, it's failed and then you need to go back and change your migration);

### System configuration

**Rails version**: 6.0.2.1
**Ruby version**: 2.6.5

**Comment by dmitry** [comment]
I had many times the same situation, which results in a:

`t.references :factory, polymorphic: true, index: {name: 'index_factories_on_widget'}`

Would be great to see that fixed in the following rails versions.

**Comment by rafaelfranca** [comment]
I'm up for it. Please open a PR.

**Comment by lukeredpath** [comment]
Please re-open - I have a pending PR for this issue.

**Comment by lukeredpath** [comment]
@jonathanhefner @eugeneius thanks for re-opening - please let me know if anymore work is required on the PR to get it merged (besides rebasing and fixing conflicts).
