### ISSUE TITLE
RailsInstaller not compatible with today's Rails

### ISSUE THREAD

**Issue by jdashton** [rails/rails#38654]
The prod and edge versions of "Getting Started with Rails" both point to RailsInstaller as a great way to get started on Windows. However, RailsInstaller is offering only Ruby 2.2 and 2.3. When you get to the `bundle install` step, multiple of the standard gems now require at least Ruby 2.4. If we have a relationship with Engine Yard, perhaps a request from the right member of the team would move them to release more current versions of the RailsInstaller downloadables.

**Comment by kaspth** [comment]
Yeah! @olivierlacan is on this 😊

**Comment by jdashton** [comment]
I agree with this patch. If Engine Yard won't step up, the change given here is better than being directed to install something that no longer functions.

However, this change would be a net loss for new programmers. The assertion that 
> Others can find installation instructions at the [SQLite3 website](https://www.sqlite.org).

is difficult to verify, if true. The Windows binaries are available at that website, true, but I failed to find any word of what to do with them.

Given that this guide is "for beginners who want to get started with a Rails application from scratch," telling the reader to find installation instructions at a site that seems to contain no installation instructions may present a significant impediment to them.

The Rails Installer from Engine Yard was valuable not least because it solved this problem.
