### ISSUE TITLE
ActiveStorage direct upload inserts blob even though upload to aws s3 fails when aws bucket region is wrong

### ISSUE THREAD

**Issue by nameisvijay** [rails/rails#38664]
DirectUpload to aws s3 fails when bucket region is wrong in storage.yml. But it inserts blob even though upload of file fails. 
### Steps to reproduce

1. create a bucket in aws-s3 in "ap-south-1" region
2. Mention (incorrect) region in storage.yml as "us-east-1"
3. Upload a file in a form using `multiple: true, direct_upload: true` as usual.
4. Check log in rails console, Bob gets inserted
5. No file gets uploaded to bucket.
6. ActiveStorage::Blob.count is 1 in rails console
7. ActiveStorage::Attachment.count is 0 in rails console

### Expected behavior
Blob should not be inserted when upload to s3 fails using directupload. Blob shall only insert when file uploaded to bucket.

### Actual behavior
Blob gets inserted in database without any file uploaded to aws-s3 bucket.

### System configuration
**Rails version**:
Rails 6.0.2.1
**Ruby version**:
ruby 2.7.0p0 (2019-12-25 revision 647ee6f091) [x86_64-linux]

**Comment by georgeclaghorn** [comment]
This is intended. The blob record has to be created to reserve its key.
