### ISSUE TITLE
May I know how to solve with "dependency tzinfo-data (>= 0) will be unused" from the root cause

### ISSUE THREAD

**Issue by ckc** [rails/rails#38678]
### Steps to reproduce

just rails new project, possible webpacker related dependancies?
Checked with old similar issue: [rubygems/bundler#5337](https://github.com/rubygems/bundler/issues/5337)

Could anyone please tell me how to resolve it? Like modify or update `rails new` template? If possible, may I know which should be its default location?

Thank you all so much!
```
Using webpacker 4.2.2
Bundle complete! 17 Gemfile dependencies, 75 gems now installed.
Use `bundle info [gemname]` to see where a bundled gem is installed.
         run  bundle binstubs bundler
The dependency tzinfo-data (>= 0) will be unused by any of the platforms Bundler is installing for. Bundler is installing for ruby but the dependency is only for x86-mingw32, x86-mswin32, x64-mingw32, java. To add those platforms to the bundle, run `bundle lock --add-platform x86-mingw32 x86-mswin32 x64-mingw32 java`.
         run  bundle exec spring binstub --all
The dependency tzinfo-data (>= 0) will be unused by any of the platforms Bundler is installing for. Bundler is installing for ruby but the dependency is only for x86-mingw32, x86-mswin32, x64-mingw32, java. To add those platforms to the bundle, run `bundle lock --add-platform x86-mingw32 x86-mswin32 x64-mingw32 java`.
* bin/rake: Spring inserted
* bin/rails: Spring inserted
       rails  webpacker:install
The dependency tzinfo-data (>= 0) will be unused by any of the platforms Bundler is installing for. Bundler is installing for ruby but the dependency is only for x86-mingw32, x86-mswin32, x64-mingw32, java. To add those platforms to the bundle, run `bundle lock --add-platform x86-mingw32 x86-mswin32 x64-mingw32 java`.
The dependency tzinfo-data (>= 0) will be unused by any of the platforms Bundler is installing for. Bundler is installing for ruby but the dependency is only for x86-mingw32, x86-mswin32, x64-mingw32, java. To add those platforms to the bundle, run `bundle lock --add-platform x86-mingw32 x86-mswin32 x64-mingw32 java`.
      create  config/webpacker.yml
Copying webpack core config
```

### Expected behavior

no need to run `bundle lock --add-platform x86-mingw32 x86-mswin32 x64-mingw32 java
` every single time when `rails new`
### Actual behavior

```The dependency tzinfo-data (>= 0) will be unused by any of the platforms Bundler is installing for. Bundler is installing for ruby but the dependency is only for x86-mingw32, x86-mswin32, x64-mingw32, java. To add those platforms to the bundle, run `bundle lock --add-platform x86-mingw32 x86-mswin32 x64-mingw32 java`.```
### System configuration
**Rails version**:
Rails 6.0.2.1
**Ruby version**:
ruby 2.7.0p0 (2019-12-25 revision 647ee6f091) [x86_64-darwin18]
PS. macOS 10.14

**Comment by khustochka** [comment]
These warnings are annoying but if I am not mistaken they are just warnings, i.e. they do not cause the app to fail.

IMHO, two main options are:
1. Ignore the warnings
2. Remove tzinfo-data from your Gemfile if you are not going to use it on Windows or with JRuby.

**Comment by jeremy** [comment]
Agree that's a poor experience. Confusing warning to anyone not already very familiar with how Bundler works. Here's a thorough rundown of how to address it: https://github.com/tzinfo/tzinfo-data/issues/12#issuecomment-279554001

Including tzinfo-data by default may be worthwhile for new Rails apps.

Ref. #21606

**Comment by eugeneius** [comment]
It looks like this warning will be removed in Bundler 2.2 via https://github.com/rubygems/bundler/pull/7580.

**Comment by hifron** [comment]
In bundler 2.3.11 I get errors with irb: Gem.Platforms I have on Windows:
=> ["ruby", #<Gem::Platform:0x0000026eebe0e7a8 @cpu="x64", @os="mingw", @version="ucrt">]

New users are confused...
