### ISSUE TITLE
`FrozenError: can't modify frozen Array` when reusing callback arguments

### ISSUE THREAD

**Issue by khustochka** [rails/rails#38679]
### Steps to reproduce
I sometimes use the following pattern:

````
class PostsController < ApplicationController
  administrative only: [:new, :create, :edit, :update, :destroy]
end
````

where
````
def self.administrative(options = {})
  before_action :verify_admin, options
  before_action :set_something, options
end
````

This is now failing on edge Rails with `FrozenError: can't modify frozen Array` on the line where the **second** callback is defined.

This was apparently introduced in 0740adb379.

### Executable test case

https://gist.github.com/khustochka/e7f0764890ab3fb554b87b8355a2d704

### Expected behavior
It does not fail, two or more callbacks can reuse provided `options` hash.

### Actual behavior
Fails with `FrozenError: can't modify frozen Array` on the line where the **second** callback is defined. It looks like the first `before_action` call modifies the `options` hash adding an `:if` key to it, which is a frozen Array, and the call to the second `before_action` tries to add an additional condition into this array.

Stacktrace:
````
rails (e00f9c8aaea3) actionpack/lib/abstract_controller/callbacks.rb:75:in `unshift'
rails (e00f9c8aaea3) actionpack/lib/abstract_controller/callbacks.rb:75:in `_normalize_callback_option'
rails (e00f9c8aaea3) actionpack/lib/abstract_controller/callbacks.rb:68:in `_normalize_callback_options'
rails (e00f9c8aaea3) actionpack/lib/abstract_controller/callbacks.rb:93:in `_insert_callbacks'
rails (e00f9c8aaea3) actionpack/lib/abstract_controller/callbacks.rb:200:in `block (2 levels) in <module:ClassMethods>'
````

### System configuration
**Rails version**:
Edge (ec69083cf3352c78f840de50fdf20ef30334e0b1)
**Ruby version**:
2.6.5

**Comment by natematykiewicz** [comment]
It looks like it’s frozen to pretty drastically improve performance. I think the better fix is for you to call `deep_dup` on `options`. That should solve your problem, without sacrificing performance for everyone else.

```
def self.administrative(options = {})
  before_action :verify_admin, options.deep_dup
  before_action :set_something, options.deep_dup
end
```

**Comment by khustochka** [comment]
@natematykiewicz Thank you for your comment! As much as I appreciate performance, I think the current behaviour severely violates the principle of least surprise. 

After all `options` is just a Hash. I can tolerate that a call to a method modifies its argument. But I find it very problematic that it modifies it in a way that makes it unusable in exactly the same context. And above all, the error message does not exactly help to understand what is the problem, without thorough investigation.

Anyway, your suggestion gave me another idea how to fix the issue - by duplicating the options inside `_insert_callbacks`. Unfortunately I assume this brings up the number of allocations (this is the area I am not very familiar with).

**Comment by khustochka** [comment]
I will probably take the liberty to ask the original author of the change:

@byroot , if you have time to look at this:
Do you think this is a bug?
If yes do you think the correct way to fix it is by:
- not freezing the conditionals array (https://github.com/rails/rails/compare/master...khustochka:fix-38679-frozen-array)
- duplicating the callback options (https://github.com/rails/rails/compare/master...khustochka:fix-38679-dup-options)
- any other way to fix?

Thank you.

**Comment by natematykiewicz** [comment]
@khustochka Hmm, that all seems like a fair argument. I'm struggling to understand why `conditions` was frozen at all. Freezing an array after you've allocated it doesn't give you any performance benefit to my knowledge. I think it's totally fair and legitimate that the `EMPTY_ARRAY` constant is frozen. But I don't understand the `conditionals.freeze`.

This PR makes sense to me. I'd be curious to see a benchmark, but I don't think it hurts performance or safety at all.
https://github.com/rails/rails/compare/master...khustochka:fix-38679-frozen-array

This PR definitely will allocate a lot more objects. How big of a performance hit it is, I'm unsure. But I would stay away from the `deep_dup` like that. I think the overwhelming majority of `before_action` (and friends) usages are people just typing a literal hash in the code that's never reused anywhere else, so to blindly dup is a bad idea I think (but you already knew that).
https://github.com/rails/rails/compare/master...khustochka:fix-38679-dup-options

I'm now really curious why the `freeze` was added in the first place. I hope @byroot can shed some light on that!

**Comment by byroot** [comment]
> Do you think this is a bug?

Yes, it is.

> I'm now really curious why the freeze was added in the first place.

For consistency. If the default value is frozen, custom values should be frozen as well. Otherwise it's too easy to be surprised by it.

As for what I think the fix should be, I'll take a closer look tomorrow, but we should indeed dup the received object before freezing it. Not because surprise or anything, just because it's bad to mutate the objects you receive like this.

As fro the performance, this patch is about retained memory (what's never collected), so no huge deal if this cause a little bit more allocations, since it happens on boot.

**Comment by byroot** [comment]
> we should indeed dup the received object before freezing it

Like not a full `deep_dup`, just the `:if` and `:unless` arrays: `conditions.frozen? ? conditions : conditions.dup.freeze`.

**Comment by byroot** [comment]
cc @casperisfine

**Comment by natematykiewicz** [comment]
@byroot Gotcha. I’m trying to learn more about performance here.

So your point is, if `:if` or `:unless` are blank, then we can share a single frozen array as opposed to allocating 1-2N new arrays and keeping those in memory for the life of the app, right? That’s the huge savings?

```ruby
before_action :foo
before_action :bar
before_action :baz
```

Before your commit, that code would have allocated and _retained_ 6 empty arrays in memory for the life of the app, where now it shares a single frozen constant. Am I understanding that right?

But then duping the present ones before freezing isn’t a big deal because the rest of the callback code will be using a different instance than what was handed in — so while it will generate a new array every time you call `before_action` (with a present `:if` or `:unless`), the new array only happens on app boot and is garbage collected quickly, so it’s not a big deal.

Am I understanding this correctly?

**Comment by byroot** [comment]
>  as opposed to allocating 1-2N new arrays and keeping those in memory for the life of the app, right? That’s the huge savings?

I wouldn't go as far as huge (75KB on Redmine is maybe 0.7% of total memory), but yeah that's a nice easy saving, without much downside (besides the small bug you reported).

> Before your commit, that code would have allocated and _retained_ 6 empty arrays in memory for the life of the app, where now it shares a single frozen constant. Am I understanding that right?

Yes.

> Am I understanding this correctly?

Yep.

**Comment by natematykiewicz** [comment]
Thanks for the explanation @byroot

**Comment by casperisfine** [comment]
Ok, so after looking a bit deeper into this, duping does fix the error, however I think this whole thing uncovered another minor bug, running your test cases with the `.freeze` removed:

```ruby
# Running:

[#<Proc:0x00007f86d9c55348@/Users/byroot/src/github.com/Shopify/rails/actionpack/lib/abstract_controller/callbacks.rb:74>]
[#<Proc:0x00007f86d9c54ce0@/Users/byroot/src/github.com/Shopify/rails/actionpack/lib/abstract_controller/callbacks.rb:74>, #<Proc:0x00007f86d9c55348@/Users/byroot/src/github.com/Shopify/rails/actionpack/lib/abstract_controller/callbacks.rb:74>]
```

```ruby
      def _normalize_callback_option(options, from, to) # :nodoc:
        if from = options[from]
          _from = Array(from).map(&:to_s).to_set
          from = proc { |c| _from.include? c.action_name }
          options[to] = Array(options[to]).unshift(from)
        end
      end
```

If you use the same array for multiple callbacks, you end up with multiple similar procs.

I'm looking for a fix for that one as well.
