### ISSUE TITLE
WebSocket error occurred: Broken pipe Actioncable, Rails 5.2.1 x Puma x nginx

### ISSUE THREAD

**Issue by fills27** [rails/rails#38688]
### Steps to reproduce
I open puma.error.log and i am getting this error
<pre>
    [no-account] [ActionCable] [67013258-2a6e-4a6e-97cb-fc45a202a095]   CACHE User Load (0.0ms)  SELECT  `users`.* FROM `users` WHERE `users`.`id` = 1 LIMIT 1  [["id", 1], ["LIMIT", 1]]
    [no-account] [ActionCable] [67013258-2a6e-4a6e-97cb-fc45a202a095]   Open Load (0.2ms)  SELECT `opens`.* FROM `opens` WHERE `opens`.`conversation_id` IS NOT NULL AND `opens`.`conversation_id` = 3
    [no-account] [ActionCable] [67013258-2a6e-4a6e-97cb-fc45a202a095] Registered connection (Z2lkOi8vY2hhdC1hcHAvVXNlci8x)
    [no-account] [ActionCable] [67013258-2a6e-4a6e-97cb-fc45a202a095] WebSocket error occurred: Broken pipe
    [no-account] [ActionCable] [67013258-2a6e-4a6e-97cb-fc45a202a095] Finished "/cable/" [WebSocket] for 162.158.167.53 at 2020-03-10 05:59:48 +0000
    [no-account] [ActionCable] [67013258-2a6e-4a6e-97cb-fc45a202a095]   Member Load (0.7ms)  SELECT  `members`.* FROM `members` WHERE `members`.`user_id` = 1 AND `members`.`company_id` = 1 ORDER BY `members`.`id` ASC LIMIT 1
    [no-account] [ActionCable] [67013258-2a6e-4a6e-97cb-fc45a202a095]   CACHE Member Load (0.0ms)  SELECT  `members`.* FROM `members` WHERE `members`.`user_id` = 1 AND `members`.`company_id` = 1 ORDER BY `members`.`id` ASC LIMIT 1
    [no-account] [ActionCable] [67013258-2a6e-4a6e-97cb-fc45a202a095]    (0.2ms)  BEGIN
    [no-account] [ActionCable] [67013258-2a6e-4a6e-97cb-fc45a202a095]   Company Load (0.4ms)  SELECT  `companies`.* FROM `companies` WHERE `companies`.`id` = 1 LIMIT 1
    [no-account] [ActionCable] [67013258-2a6e-4a6e-97cb-fc45a202a095]   User Load (0.4ms)  SELECT  `users`.* FROM `users` WHERE `users`.`id` = 1 LIMIT 1
</pre>

chrome warning
`WebSocket connection to 'wss://web.upflics.com/cable' failed: WebSocket is closed before the connection is established.`

nginx.conf
<pre>
upstream puma {
  server unix:///home/deploy/chatapp/shared/tmp/sockets/chatapp-puma.sock;
}

server {
  listen 80;
  listen [::]:80;
  server_name upflics.com;

  root /home/deploy/chatapp/current/public;
  access_log /home/deploy/chatapp/current/log/nginx.access.log;
  error_log /home/deploy/chatapp/current/log/nginx.error.log info;

  location /cable {
    proxy_pass http://puma;
    proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection "Upgrade";
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header Host $http_host;
    proxy_redirect off;
    proxy_set_header X-Forwarded-Proto $scheme;
  }

  location ~ ^/(assets|packs) {
    gzip_static on;
    expires max;
    add_header Cache-Control public;
  }

  try_files $uri/index.html $uri @puma;
  location @puma {
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header Host $http_host;
    proxy_redirect off;

    proxy_pass http://puma;
  }

  error_page 500 502 503 504 /500.html;
  client_max_body_size 100M;
  keepalive_timeout 10;
}
</pre>

redis configuration
<pre>
production:
  adapter: redis
  url: <%= ENV.fetch("REDIS_URL") { "redis://localhost:6379/1" } %>
</pre>

production.rb
<pre>
  config.action_cable.disable_request_forgery_protection = true
  config.action_cable.allowed_request_origins = ['https://web.upflics.com']
  config.action_cable.url = "wss://web.upflics.com/cable" 
</pre>

### Expected behavior
The connection using ActionCable works well

### Actual behavior
broken pipe in puma.error log
`[no-account] [ActionCable] [67013258-2a6e-4a6e-97cb-fc45a202a095] WebSocket error occurred: Broken pipe`
chrome warning
`WebSocket connection to 'wss://web.upflics.com/cable' failed: WebSocket is closed before the connection is established.`

### System configuration
Rails version Rails 5.2.1
Ruby version ruby 2.7.0p0 (2019-12-25 revision 647ee6f091) [x86_64-darwin17]

**Comment by gingerlime** [comment]
@syafilm did you manage to solve this?

**Comment by syafilm** [comment]
Nope, not yet @gingerlime i recommend you to use other services instead, like pusher, twilio, or etc

**Comment by gingerlime** [comment]
thanks, we actually transitioned from pusher to actioncable :) (although our use case was pretty minimal, and that's a big part of the reason: reduce another 3rd party in the chain, even though it worked well for us).
