### ISSUE TITLE
Rails commands being aborted with no output log

### ISSUE THREAD

**Issue by NicosKaralis** [rails/rails#38683]
### Steps to reproduce

- Clone a working project
- Type any rails command and the output will be:

    [1]    72060 abort      rails [command]

### Expected behavior

The command should run, or at least output the error that prevented it to run

### Actual behavior

There is no output, no error, nothing, the command is just aborted

### System configuration
The problem hapenned on the versions bellow, these are the only ones we have so I can't test on other versions

**Rails version**:

- 5.2.3
- 5.2.4.1

**Ruby version**:

- ruby 2.5.3p105 (2018-10-18 revision 65156) [x86_64-darwin19]
- ruby 2.5.1p57 (2018-03-29 revision 63029) [x86_64-darwin19]

**Rvm version**: rvm 1.29.9 (latest) by Michal Papis, Piotr Kuczynski, Wayne E. Seguin [https://rvm.io]
----

The command `rails new [name]` works fine. And after a project is created the rails commands work fine, only on the cloned projects give this error

**Comment by louim** [comment]
I'm afraid this is a problem specific with your setup, and not directly related to Rails 😕. Maybe check your system logs?

**Comment by NicosKaralis** [comment]
Where can I find logs for this error? There is no indication of what is going on

I can't find anything that could be causing this
I've already reinstalled ruby, rvm, tryied to upgrade ruby version. Nothing makes the app work

**Comment by npickelny** [comment]
Im facing the same issue. I dont know how to see the logs either or any other info.
+1 for any ideas on what to try
