### ISSUE TITLE
ajax stop method is not working in rails 6 with colorbox.

### ISSUE THREAD

**Issue by jawadakram20** [rails/rails#38692]
`$(document).ajaxStop(function () {
      alert("Ss");
});`

**Comment by madmax** [comment]
This is because rails ujs not longer use jQuery. 

Here are my solution for this. 

dom.coffee
```
class window.Dom
  @ajaxComplete: (callback) =>
    document.addEventListener("ajax:before", (event) ->
      event.target.addEventListener("ajax:complete", callback)
    )
```

Now you can use Dom.

```
Dom.ajaxComplete -> alert("Ss")
```

**Comment by eugeneius** [comment]
As @madmax said, Rails no longer includes jQuery by default - you'll have to add it yourself if you want to use it.
