### ISSUE TITLE
[ActiveModel] ActiveModel::EachValidator name conflicts with 3rd party gem

### ISSUE THREAD

**Issue by oliverswitzer** [rails/rails#38703]
### Steps to reproduce

* Create a sample rails app
* Define a class `EmailValidator` in that app that implements `ActiveModel::EachValidator`. Add a very specific error to the model if this validation fails so that you can differentiate it from other email validators later.
* Install any gem that implements its own `ActiveModel::EachValidator` and calls it `EmailValidator` (there are a lot that use this name). 
  * Here is [one called `validates_email`](https://github.com/perfectline/validates_email) - it declares an `EmailValidator` that inherits from ActiveModel::EachValidator [here](https://github.com/perfectline/validates_email/blob/master/lib/validate_email.rb). 
  * [Here is another called `valid_email`](https://github.com/hallelujah/valid_email) - it declares an `EmailValidator` that inherits from `ActiveModel::EachValidator` [here](https://github.com/hallelujah/valid_email/blob/fd4f11bc4deb7fe16f6528f8c9c41a0b91d7d81e/lib/valid_email/email_validator.rb).
* Create an active record model that uses email validation:

```.rb
class User
   validates :email, email: true
end
```

* Now try to save that user with an invalid email that should cause the `EmailValidator` that you defined in your Rails app to fail.

### Expected behavior
* I would expect my own `EmailValidator` (i.e. the one that I defined in *my* rails app, and not a 3rd party gem) to be run against this field.

### Actual behavior
* Notice that instead of the validation in the sample Rails app failing, the `EmailValidator` defined in the 3rd party gem are getting run instead

### Extra notes: 

This behavior still occurs with transitive dependencies. I.e. if I depend on a gem that depends on a gem that depends on an email validation gem, then I will still see this behavior... the [`apple_id` gem](https://github.com/nov/apple_id) is a good example of this. I actually originally opened up [an issue](https://github.com/nov/apple_id/issues/5) in that repo before I understood the root of the problem seemed to lie with ActiveModel instead.

### System configuration
**Rails version**:
5.1.0

**Ruby version**:
`ruby 2.6.2p47 (2019-03-13 revision 67232) [x86_64-darwin16]`

**Comment by rafaelfranca** [comment]
This is how ruby works. Constants are global and defining constants with the same name will cause Ruby to reopen the first loaded constant and override the behavior. There is nothing we can do in Rails to change that.

The good news is that your class doesn't need to be called `ActiveModel::Validations::EmailValidator`. You can define inside your own module or with a different name. The same goes for the gems. They could call their classes `ValidatesEmail::EmailValidator`.

This issue is in reality an issues in the gems.

Thank you for reporting.

**Comment by oliverswitzer** [comment]
@rafaelfranca thank you for the prompt response.

I understand that if you re-declare a class with the same name that it will override the behavior of the first loaded constant.

However, [the "magic" way in which ActiveModel looks up validations](https://github.com/rails/rails/blob/7fa807d63673286dde63c41bed0e58c61488abf5/activemodel/lib/active_model/validations/validates.rb#L115-L119) when you declare `validates :email, email: true` makes it *very* unclear to the user how for `EachValidator`s or where they are declared. 

To fix my issue, I tried what you said with namespacing:

module MyApp
  class EmailValidator < ActiveModel::EachValidator
  ...
  end
end

But I then had to specify in my model to use that validator in the following way:

```.rb
validates :email, 'MyApp::Email': true
```

I cannot specify that the weird namespaced string is a validator, so any other person who is not 100% familiar with the inner workings of ActiveModel::EachValidator will be puzzled as to what the heck this means.

I'm not proposing a change to ruby or gems, but proposing that we be a little bit more specific about how we specify our validations when making use of a `EachValidator`. I think this could greatly reduce the chance of other people running into this namespacing issue that Ruby/gems have sadly left us with.

Instead of doing the fancy lookup by appending 'Validator' to the key provided, why can't we just specify it explicitly:

```.rb
validates :email, 'MyApp::EmailValidator': true
```

Or even:

```.rb
validates :email, validator => 'MyApp::EmailValidator'
```

(it's unclear to me what the `true` value does...)

I understand this is now bordering on a feature request. However, I think this is an example where we could just say its the fault of the language, or actually try to make a confusing API somewhat simpler and less difficult to understand, as well as more stable for any users that depend on gems that have transitive dependencies on email validator gems... (I can imagine that this is actually quite a few people)

**Comment by oliverswitzer** [comment]
Also would like to say that [the docs for `ActiveModel::EachValidator`](https://api.rubyonrails.org/v3.2.13/classes/ActiveModel/EachValidator.html) never specify that you need to have `Validator` appended to your class name or else it won't get used...

**Comment by rafaelfranca** [comment]
> validates :email, 'MyApp::EmailValidator': true

This is easy to implement and I'm ok with it. Mind to open an PR?

**Comment by oliverswitzer** [comment]
@rafaelfranca will try to open a PR on Friday :+1:

**Comment by oliverswitzer** [comment]
@rafaelfranca [this](
https://github.com/rails/rails/compare/master...oliverswitzer:activemodel-specify-validator?expand=1) is my initial (admittedly very simplistic) pass. Would love your thoughts/feedback

**Comment by kaspth** [comment]
Think the `validates` docs are already fairly clear on what to do: https://api.rubyonrails.org/classes/ActiveModel/Validations/ClassMethods.html#method-i-validates

The first sentence even says "ending in `Validator`". Perhaps we could link to `validates` from the EachValidator docs?

**Comment by oliverswitzer** [comment]
@kaspth I definitely think linking to `validates` from the `EachValidator` docs could help. 

I also feel that specifying a namespace for a `EachValidator` this way is somewhat confusing:

`validates :name, :'film/title' => true`

I was able to specify it this way

`validates :name, 'Film::Title': true`

Which I feel is a little more concrete. But truthfully, I feel like it would help most developers have the option to specify a concrete class as a parameter. That way, any IDE using ctags/with click through ability will be able to go right to the class, without any ambiguity. 

I wouldn't make such a fuss out of this if I had not experienced having gem's dependency update email validations for my entire application just by being added to my Gemfile. Had I not had test coverage around this I could've shipped a build to production that would've allowed scrapers and potential mass account creation attacks to occur (which our own email EachValidator was protecting us from)

While we can't patch the way that ruby or gems work, it would be nice to have an escape hatch API that's a little bit more informative. Even adding this:

`validates :name, 'Film::Title': true`

to the docs feels like a step in the right direction. However, I'm not sure that I see what was wrong with the solution that I created.

**Comment by kaspth** [comment]
This doesn't strike me as bad honestly, and I like the aesthetics just fine:

```ruby
validates :name, 'film/title': true
```

Matches our autoloading naming scheme fairly well (e.g. `"Film::Title".underscore # => "film/title"`).

Then again we don't have `has_many :posts, class_name: "author/posts"`, so allowing "Film::Title" seems fine, and if not there's also `validates_with` though the required interface is slightly different.
