### ISSUE TITLE
`insert_all` does not work properly with enums as it does not cast types

### ISSUE THREAD

**Issue by ayufan** [rails/rails#38716]
### Steps to reproduce

```ruby
class BulkInsertItem < ActiveRecord::Base
    enum enum_value: {
     value_A: 1
    }
end

ActiveRecord::Schema.define do
  create_table :bulk_insert_items, force: true do |t|
    t.integer :enum_value, null: false
  end
end

BulkInsertItem.insert_all!([
   { enum_value: "value_A" }
]) # this results in in ability to insert enum value, as `string` tries to be converted to `integer`

BulkInsertItem.insert_all!([
   { enum_value: 1 }
]) # it requires to performing manual conversion, as `enum` decorates an attribute type
```

### Expected behavior

That the convenient form does work properly for `insert_all`:

```ruby
BulkInsertItem.insert_all!([
   { enum_value: "value_A" }
])
```

### The problem

It appears that problem lies in https://github.com/rails/rails/blob/master/activerecord/lib/active_record/insert_all.rb#L184.

We serialise data using a type as declared by the DB schema,
but we completely ignore `decorate_attribute_type` there.

It appears that the line should rather be:

```ruby
keys.index_with { |key| type_for_attribute(columns[key]) }
```

This would return a decorator type, or database type and allow to properly serialise
it's representation, in the same way as `.save!` is doing.

### System configuration
**Rails version**: `6.0.2`

**Comment by rafaelfranca** [comment]
That makes sense. Can you work in a PR?

**Comment by varentsov** [comment]
I have the same issue

**Comment by simi** [comment]
There's PR (https://github.com/rails/rails/pull/38763) already. I think this can be closed. We can continue in there.
