### ISSUE TITLE
[ActiveStorage] ActiveSupport::MessageVerifier::InvalidSignature 

### ISSUE THREAD

**Issue by Tiltorito** [rails/rails#38715]
### Steps to reproduce

Given that you have a model: 

```ruby
class Course < ApplicationRecord
  has_one_attached :image
end
```
having the following code in the controller

```ruby
  def create
    @course = Course.new(course_params)
    if @course.save
      render :show, status: :created
    else
      render json: @course.errors, status: :unprocessable_entity
    end
  end
 
  def course_params
    params.require(:course).permit(:name, :disabled, :image)
  end
```
### Expected behavior
If image is not present or "null" or any invalid string it should default to nil when you set the value to has_one_attached. If there was an already attached image, it should be purged.

### Actual behavior
it will raise an ActiveSupport::MessageVerifier::InvalidSignature. After some debugging, this is due that the params are strings. If Image is sent as null from the frontend the course_params[:image] will contains "null". This is assigned on the image property on the model and because it is a string is interpreted as blob_id and somehow the exception is raised. 

### System configuration
**Rails version**:
gem 'rails', '~> 6.0.1'
**Ruby version**:
ruby '2.6.5'

**Comment by Tiltorito** [comment]
Looking on the source code, the method responsible for exception seems to be [find_or_build_blob](https://github.com/rails/rails/blob/master/activestorage/lib/active_storage/attached/changes/create_one.rb#L51)

**Comment by jeremy** [comment]
> If image is not present or "null" or any invalid string it should default to nil when you set the value to has_one_attached. If there was an already attached image, it should be purged.

If you set `image` to `nil`, it is deleted.

If you pass invalid junk, that is exceptional, and an exception is expected. We wouldn't ignore an invalid argument and treat it as nil. That'd lead to data loss.

**Comment by Tiltorito** [comment]
@jeremy I disagree. In this sense, we either have to have exception handling between every controller action that deals with assigning active storage attachments or let the backend return 500 errors if the frontend decides to pass invalid string as blob id.

I am pretty sure you can pass string to Boolean active record record attributes and it will translate to false. Is this considered data loss as well?

**Comment by Tiltorito** [comment]
@Jeremy Also, how can you remove an attachment for a record. For me it makes sense that you pass a null as parameter on the attachment. When null is passed from the frontend it gets translated as "null" which has the problem discussed earlier.

If you don't agree with all this, could you please provide me a snippet of using active storage from my controller, because I can't see a **rails** way of doing it.

Kind regards

**Comment by uxxman** [comment]
+1 

also facing same issue

**Comment by Vicky099** [comment]
I am facing same issue by passing `signed_id` in hidden form parameters, when there is model validations. Have any one find out the solution?

**Comment by divyaraj-atharva** [comment]
+1
