### ISSUE TITLE
Loading module and namespaced classes from directory structure

### ISSUE THREAD

**Issue by fxn** [rails/rails#38726]
_(Moved from https://github.com/fxn/zeitwerk/issues/113, with description edited to reflect that we are talking about directories and files below `app/models`.)_

As someone with a Rails background, I am accustomed for this to work:

```
# app/models/mymodule.rb
module Mymodule
end
```

```
# app/models/mymodule/myclass.rb
module Mymodule
  class Myclass
  end
end
```

Now that Rails 6 uses Zeitwerk, when trying to autoload `Mymodule::Myclass`, it stops looking after finding `app/models/mymodule.rb`, raises a `NameError` and does not descend into the subfolder anymore.

It works after deleting the empty module file, but that's only possible as long as it remains empty: usually this file is used to override defaults like table name prefixes for classes of the module.

Is it a user error, bug or maybe just a problem of the integration of Zeitwerk into Rails?

**Comment by fxn** [comment]
This report is strange, since this routinely works correctly. We are awaiting a log report.

**Comment by fxn** [comment]
We've not heard from this one for a while.

I am pretty confident autoloading handles namespaces correctly and was waiting to help debugging. Going to close to keep the issue tracker under control.

Of course, feel free to followup.

**Comment by FelipeRiveraC** [comment]
Hello, have you found any workaround for this issue?

I am having this exact same problem. A solution would be having a namespace unique by name and defining the table names in each record.

This breaks a little the point of namespaces.

Do you have any other solutions?

**Comment by fxn** [comment]
@FelipeRiveraC as it was said, there is no workaround because there is no issue to workaround.

Could you please open a new issue explaining your use situation and tag me?
