### ISSUE TITLE
Upgrading from 5.2 to Rails 6: #<ActionView::Template::Error: undefined method `start_with?' for /\.(?:svg|eot|woff|ttf)$/:Regexp>

### ISSUE THREAD

**Issue by ultrawebmarketing** [rails/rails#38723]
### Steps to reproduce
Upgrade an existing 5.2 application to Rails 6. 

### Expected behavior
The upgrade should work I guess.

### Actual behavior
Seems that any asset that is called from stylesheet_link_tag that contains a link to a file with an extension of svg, eot, woff, ttf causes a 500 error to be thrown. In my case I'm using a template that is calling the fontawesome
```
 * --- FontAwesome
 *= require @fortawesome/fontawesome-free/css/brands.css
 *= require @fortawesome/fontawesome-free/css/regular.css
 *= require @fortawesome/fontawesome-free/css/solid.css
 *= require @fortawesome/fontawesome-free/css/fontawesome.css
```
Even stranger thing is that in order to even see this error I had to use byebug and step through everything since when the error is trigger the public/500.html page is displayed instead of the standard development error page. Also nothing shows up in the development logs about the error. 

```
  Rendering dashboard/index.html.erb within layouts/application
  Rendered dashboard/index.html.erb within layouts/application (Duration: 2.9ms | Allocations: 2386)
Completed 500  in 2884ms (ActiveRecord: 121.0ms | Allocations: 256788)
```
### System configuration
**Rails version**: 6.0.2.1

**Ruby version**: 2.5.3p105

**Comment by louim** [comment]
Hey!

Would you happen to use the `bootstrap-sass` or a similar gem? I found an issue that look like your's here: https://github.com/rails/sprockets/issues/578

**Comment by rafaelfranca** [comment]
This happened because your upgrade process also upgraded sprockets to the version 4 and you have gems, or code in your application that doesn't support sprockets 4 yet.

You need to either lock the sprockets version to stay on 3.x or change the problematic gems/code.

Thank you for the report.
