### ISSUE TITLE
Webpacker makes Rails not fun any longer

### ISSUE THREAD

**Issue by EugZol** [rails/rails#38730]
### Steps to reproduce

1. `gem install rails`
2. `rails new test_app`
3. Try to add custom JS, CSS, images and/or fonts with webpacker

### Expected behavior

1. It just works
2. Have fun

### Actual behavior

1. It doesn't
2. Be frustrated

### System configuration
**Rails version**: 6+

**Ruby version**: 2.6+

I've started using Rails ~ a decade ago as a solution to make applications instead of writing boilerplate code (as any other framework/language combination available at that time would require you to do).

Since Rails 6, it is fun no longer, for a single reason: webpacker.

Let's consider a simple, universal and straightforward scenario of adding Bootstrap (for example) to Rails application.

With sprockets it was bad enough already, because we have to choose between the following options:

1. Adding CSS/JS as direct links to a CDN
2. Downloading minified versions to `public/...` and linking from there
3. Downloading minified versions to `assets/...` and linking from there
4. Downloading SCSS bundle into `assets`
5. Installing some gem which would do some magic (which one? how does the magic work?)
6. Using "rails assets" (https://rails-assets.org/) and its magic

...I'm sure these are not all of the ways. And none of the points above could be dismissed as obsolete, irrelevant or *a-priory* unusable — all of them should be considered any time you start a new project.

With the introduction of webpacker a painful decision-making point (and too large amount of boilerplate code which is required to make most of the solutions above work) turned into a catastrophe with no exit.

**In addition** to **all of the above** (because Rails 6 doesn't remove sprockets or, at least, explicitly marks them as deprecated — hell, even the docs/guides on "Asset pipeline" are still on the main RoR website and webpacker isn't even mentioned once) now we should consider the following:

1. Do I add bootstrap JS (continuing the example — but specific library doesn't matter) in packs or in assets?
2. How do I add bootstrap CSS?
3. Why should I place my CSS files into `app/javascripts`?
4. Should I use `assets/...` in parallel with `packs/...`? If not, why both are enabled in new app by default?
3. Where do I place my custom JS code and how do I make it work?

Basic features require following complex multi-step undocumented process in order to set up half-working environment: https://medium.com/@coorasse/goodbye-sprockets-welcome-webpacker-3-0-ff877fb8fa79 (this is not my guide, just in my opinion one of the good ones)

Surely, it is not even half that complex when building standalone React/Angular/... application. Rails, which started as a framework with (almost) no boilerplate and zero configuration somehow managed to overdo even JS ecosystems in the amount of boilerplate and configuration required to set up basic environment.

My suggestions is to remove webpacker from stable branch of Rails until proper documentation, default configuration and supplementary tools are made. "Half a product is better than half-assed product".

**Comment by jeremy** [comment]
Appreciate your post, and your motivation to keep Rails fun. Blog posts and tweets are appropriate for this sort of advocacy. Please do keep it up! Let's use this forum for specific issues and pull request proposals.
