### ISSUE TITLE
Missing HTTPS on rubyonrails.org links

### ISSUE THREAD

**Issue by jbampton** [rails/rails#38740]
<img width="811" alt="Screen Shot 2020-03-16 at 5 40 05 am" src="https://user-images.githubusercontent.com/418747/76709259-410f0b80-6749-11ea-8a89-3f9bed2697cd.png">

<img width="826" alt="Screen Shot 2020-03-16 at 5 42 39 am" src="https://user-images.githubusercontent.com/418747/76709275-5dab4380-6749-11ea-8dbc-a1dddc7afa56.png">

**Comment by rafaelfranca** [comment]
Fixed. Thanks
