### ISSUE TITLE
Unable to set primary_key_type to false for active_record orm

### ISSUE THREAD

**Issue by cookopotamus** [rails/rails#38744]
Due to [this line of code](https://github.com/rails/rails/blob/541ec328aa30802b1ba820423e6388217b384a83/activerecord/lib/rails/generators/active_record/migration.rb#L22), and assuming that it must be symbol. (not to mention, it'll check false and see its falsey... 'false' outputs :false though).

I'm sure this was probably coded only for setting specific values, but I thought might be able to use false to speed up migration generations while using UUIDs as primary keys for MySQL (since it doesn't support uuid directly). See the following config I was going for in _application.rb_:
```ruby
config.generators do |g|
      g.orm :active_record, primary_key_type: false
end
```

**Comment by rafaelfranca** [comment]
Thank you for the report. Are you able to open a PR fixing the issue?

**Comment by rishav-csenitjsr** [comment]
Hi @cookopotamus , I want to work on this issue as it might be a good start towards contributing to rails and increases my knowledge of rails. Can you please elaborate what is the issue you are facing ?

**Comment by cookopotamus** [comment]
@rishav-csenitjsr,

This is technically fixable by using custom generator templates with [this ](https://github.com/rails/rails/blob/master/activerecord/lib/rails/generators/active_record/migration/templates/create_table_migration.rb.tt#L3) as a base... I'm not sure if what I was proposing is a change that we want made here.

I ended up making the decision to switch to POSTGRESQL from MySQL, since PGSQL has built-in features to support UUIDs.

What we could do here, though, if we wanted to allow for a 'primary_key: false' attribute is check if the _primary_key_type_ value is 'false' or ':false' and proceed accordingly for that specific case to make it print out 'primary_key: false' instead of 'primary_key: :false.

**Comment by gentcys** [comment]
@rishav-csenitjsr  I'm so sorry about that before starting my job about contribution i didn't post a comment, and it lead to you to do the duplicated job.
If you don't mind, i will invite you to collaborate to fix this issue.
Or you can give me some feedback about the PR, i'll appreciate.

**Comment by rishav-csenitjsr** [comment]
@gentcys I also started looking into this. But there is no issue, anyone can contribute. Thanks for making the PR. If you want any collaboration on this PR please feel free to ping me. Thanks.
