### ISSUE TITLE
(re)-add ability to `unset` config keys from `database.yml` with the contents of `DATABASE_URL` query options

### ISSUE THREAD

**Issue by PaulCharlton** [rails/rails#38748]
(re)-add ability to `unset` config keys from `database.yml` with the contents of `DATABASE_URL` query options

This is needed when the default config within a docker containerized application is incompatible with the deployment environment, and it is desirable to use an environment variable set during container launch to (1) override config key value [works], and/or (2) remove config key [doesn't work] settings incompatible with the deployment environment.

Note that the "unset" behavior existed in previous versions of rails [see comments here](https://github.com/rails/rails/issues/9097#issue-10385771) -> #9097, and that the current behavior comes from => [Source Code here](https://github.com/rails/rails/blob/2562d133702787553ce9305e8e0765369fdeea22/activerecord/lib/active_record/database_configurations/connection_url_resolver.rb#L39)

### Steps to reproduce
set a config "key=value" in `database.yml`
create an exported ENV variable such as `DATABASE_URL=sqlserver://host/db?key=&foo=name`

```
cat config/database.yml
development:
  adapter: sqlite3
  database: NOT_my_database
  host: localhost
  zapme: "delete_this_config"
  baz: "preserved"
 
$ echo $DATABASE_URL
postgresql://localhost/my_database?zapme=&foo=bar
 
$ bin/rails runner 'puts ActiveRecord::Base.configurations'
{"development"=>{"adapter"=>"postgresql", "host"=>"localhost", "database"=>"my_database","zapme"=>"delete_this_config","foo"=>"bar","baz"=>"preserved"}}
```

### Expected behavior
config key=value from `database.yml` -- key should be removed from hash if the URL has query parameter such as `?key=` (empty string for value)

expect to see:
```
$ bin/rails runner 'puts ActiveRecord::Base.configurations'
{"development"=>{"adapter"=>"postgresql", "host"=>"localhost", "database"=>"my_database","foo"=>"bar","baz"=>"preserved"}}
```

### Actual behavior
config key=value from `database.yml` is unchanged in the config resulting from the merge of `database.yml` with the contents of `DATABASE_URL` containing "key=" {empty string}, as shown in the output above under "Steps to Reproduce"

### System configuration
`#head`

**Comment by eileencodes** [comment]
@PaulCharlton can you write a test or provide a test app with reproduction steps? This test in Rails https://github.com/rails/rails/blob/master/activerecord/test//cases/connection_adapters/merge_and_resolve_default_url_config_test.rb is a good place to provide a reproduction so we can get this fixed. Do you know what version of Rails this broke in?

**Comment by PaulCharlton** [comment]
@eileencodes I will research when it broke and which commit did the deed and whether it was oversight or well considered.

I am happy to write the test cases as a PR, and also to submit a PR to change the behavior.
