### ISSUE TITLE
Active Storage and multiple databases

### ISSUE THREAD

**Issue by schodevio** [rails/rails#38755]
Is is possible to use active storage with multi databases in rails? I have the following models:

### Steps to reproduce

```
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end


class OtherRecord < ActiveRecord::Base
  self.abstract_class = true

  connects_to database: { writing: :other_db }
end


class SomeModel < OtherRecord
  has_many_attached :files
end
```

I've added active storage migrations scoped to the secondary database and necessary tables were created there but ActiveStorage seems to look for tables in primary database. Have anyone a solution for that?

### Expected behavior
I should have an option to point active storage to use secondary database.

### Actual behavior
ActiveStorage seems to look for tables in primary database.

### System configuration
**Rails version**:
gem 'rails', '~> 6.0.2.1'

**Ruby version**:
ruby-2.7

**Comment by sydneyitguy** [comment]
This is a blocker for my project as well.
Is there any work-around for this issue for now?

**Comment by georgeclaghorn** [comment]
Active Storage doesn’t currently support multiple databases.

Can you elaborate on what you’re looking for here? If you just want to keep all of Active Storage’s data in a separate database, you can monkey-patch that in:

```ruby
# config/initializers/active_storage.rb
ActiveSupport.on_load(:active_storage_blob) do
  # Assumes the activestorage_primary and activestorage_replica DBs are configured in config/database.yml.
  connects_to writing: :activestorage_primary, reading: :activestorage_replica
end
```

That’s trivial to add first-class support for, too.

If you want Active Storage to look in different DBs for attachments to different records, that’s probably going to require framework support.

**Comment by sydneyitguy** [comment]
@georgeclaghorn Thanks for the clarification.
I tried with your monky-patch solution and it didn't work in my case
This worked for me:
```ruby
module ActiveStorageAttachmentExtension
  extend ActiveSupport::Concern

  included do
    connects_to database: { writing: : activestorage_primary, reading: : activestorage_replica }
  end
end

Rails.configuration.to_prepare do
  ActiveStorage::Attachment.include ActiveStorageAttachmentExtension
  ActiveStorage::Blob.include ActiveStorageAttachmentExtension
end
```

**Comment by georgeclaghorn** [comment]
Oops, yes, you need to monkey-patch `ActiveStorage::Attachment`, too. I updated my example.

**Comment by rept** [comment]
Are there any plans to support this in the framework?

Wouldn't it be logical that if the following line was included in the class:

    connects_to database: { writing: :other_db }

it would be valid for 

    has_one_attached :source_image

That is later used in the model?

Or maybe have an option to include in has_one_attached?

**Comment by rept** [comment]
@georgeclaghorn the patch is no longer working with Rails 6.1

    Uncaught exception: unknown keywords: writing, reading

Also changing it to:

    connects_to database: { writing: :datawarehouse, reading: :datawarehouse }

Doesn't work but returns:

    Uncaught exception: `connects_to` can only be called on ActiveRecord::Base or abstract classes

**Comment by Toucouleur66** [comment]
@georgeclaghorn it doesn't work either using Rails 6.0.13

**Comment by dapi** [comment]
> @georgeclaghorn the patch is no longer working with Rails 6.1
> 
> ```
> Uncaught exception: unknown keywords: writing, reading
> ```
> 
> Also changing it to:
> 
> ```
> connects_to database: { writing: :datawarehouse, reading: :datawarehouse }
> ```
> 
> Doesn't work but returns:
> 
> ```
> Uncaught exception: `connects_to` can only be called on ActiveRecord::Base or abstract classes
> ```

Same things

**Comment by dapi** [comment]
This works for me with rails 6.1.3:

```
module ActiveStorageAttachmentExtension
  extend ActiveSupport::Concern

  included do
    connects_to database: { writing: :reports }
  end
end

Rails.configuration.to_prepare do
  ActiveStorage::Record.include ActiveStorageAttachmentExtension
end
```

**Comment by andykallhoff** [comment]
I just want to confirm that this is still functioning as you all expect. I am having this same issue with a few differences. 
Rails: 6.1.3
Ruby: 2.7.1
Mysql2

```ruby
#/models/application_record.rb
self.abstract_class = true
connects_to shards: { 
  db_one: { writing: :db_one },
  db_two: { writing: :db_two },
}

#/models/something.rb
class Something < ApplicationRecord
  has_one_attached :picture
  has_many_attached :files
end
```

When creating/updating a `Something` record, the attachment/blob records are created with no issue. 
```
ActiveStorage::Blob Create (0.2ms)  
  INSERT INTO `active_storage_blobs` (`key`, `filename`, `content_type`, `metadata`, `byte_size`, `checksum`, `created_at`, `service_name`) VALUES ('762ocbjpaynewo05f23l35pycbfi', 'screenpng.png', 'image/png', '{\"identified\":true}', 175891, 'Zy6fB8QnDxCoEgmu601cAQ==', '2021-06-17 07:42:13', 'local')
↳ app/controllers/somethings_controller.rb:42:in `update'
ActiveStorage::Attachment Create (0.2ms)  
  INSERT INTO `active_storage_attachments` (`name`, `record_type`, `record_id`, `blob_id`, `created_at`) VALUES ('picture', 'Something', 1, 1, '2021-06-17 07:42:13')
↳ app/controllers/somethings_controller.rb:42:in `update'

Disk Storage (1.6ms) Uploaded file to key: 762ocbjpaynewo05f23l35pycbfi (checksum: Zy6fB8QnDxCoEgmu601cAQ==)
Enqueued ActiveStorage::AnalyzeJob (Job ID: b227126d-2503-444a-8349-983153909d39) to Resque(default) with arguments: #<GlobalID:0x00007f866f6d04a0 @uri=#<URI::GID gid://derp/ActiveStorage::Blob/1>>
```

Quick check in rails console to confirm what I would expect.
```
#rails console

ActiveStorage::Blob.count
   (0.3ms)  SELECT COUNT(*) FROM `active_storage_blobs`
 => 0 
 
ActiveStorage::Attachment.count
   (0.2ms)  SELECT COUNT(*) FROM `active_storage_attachments`
 => 0 

ActiveRecord::Base.connected_to(role: :writing, shard: :db_one) do ActiveStorage::Blob.count end
   (0.6ms)  SELECT COUNT(*) FROM `active_storage_blobs`
 => 1 

ActiveRecord::Base.connected_to(role: :writing, shard: :db_one) do ActiveStorage::Attachment.count end
   (0.7ms)  SELECT COUNT(*) FROM `active_storage_attachments`
 => 1 

ActiveRecord::Base.connected_to(role: :writing, shard: :db_one) do Something.find(1).picture.attached? end
  Something Load (0.2ms)  SELECT `somethings`.* FROM `somethings` WHERE `somethings`.`id` = 1 LIMIT 1
  ActiveStorage::Attachment Load (0.4ms)  SELECT `active_storage_attachments`.* FROM `active_storage_attachments` WHERE `active_storage_attachments`.`record_id` = 1 AND `active_storage_attachments`.`record_type` = 'Something' AND `active_storage_attachments`.`name` = 'picture' LIMIT 1
 => true 
```

The issue that I do have however is trying to show them. It seems I can fetch the attachments in a `rails console`, but not on the site itself.
```
#from the server log
Started GET "/rails/active_storage/blobs/redirect/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBCZz09IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--d24786bc1059f30aae41497dccf03272a96c9434/screenpng.png" for ::1 at 2021-06-17 07:42:13 -0600
Processing by ActiveStorage::Blobs::RedirectController#show as PNG
  Parameters: {"signed_id"=>"eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBCZz09IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--d24786bc1059f30aae41497dccf03272a96c9434", "filename"=>"screenpng"}
  ActiveStorage::Blob Load (1.3ms)  SELECT `active_storage_blobs`.* FROM `active_storage_blobs` WHERE `active_storage_blobs`.`id` = 1 LIMIT 1
Completed 404 Not Found in 4ms (ActiveRecord: 1.3ms | Allocations: 1545)
```

Now I _can_ get this to work by changing my `ApplicationRecord` and creating a `class Shard < ApplicationRecord` for the shard connections. The below is the server log with it working.
```
#from the server log with changes just mentioned that work
Started GET "/rails/active_storage/blobs/redirect/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBCZz09IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--d24786bc1059f30aae41497dccf03272a96c9434/screenpng.png" for ::1 at 2021-06-17 07:52:23 -0600
Processing by ActiveStorage::Blobs::RedirectController#show as PNG
  Parameters: {"signed_id"=>"eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBCZz09IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--d24786bc1059f30aae41497dccf03272a96c9434", "filename"=>"screenpng"}
  ActiveStorage::Blob Load (0.3ms)  SELECT `active_storage_blobs`.* FROM `active_storage_blobs` WHERE `active_storage_blobs`.`id` = 1 LIMIT 1
  Disk Storage (0.7ms) Generated URL for file at key: rpzoiq3c6m3yv81qm4cb95ppr0ad (http://localhost:3000/rails/active_storage/disk/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaDdDVG9JYTJWNVNTSWhjbkI2YjJseE0yTTJiVE41ZGpneGNXMDBZMkk1TlhCd2NqQmhaQVk2QmtWVU9oQmthWE53YjNOcGRHbHZia2tpUldsdWJHbHVaVHNnWm1sc1pXNWhiV1U5SW5OamNtVmxibkJ1Wnk1d2JtY2lPeUJtYVd4bGJtRnRaU285VlZSR0xUZ25KM05qY21WbGJuQnVaeTV3Ym1jR093WlVPaEZqYjI1MFpXNTBYM1I1Y0dWSklnNXBiV0ZuWlM5d2JtY0dPd1pVT2hGelpYSjJhV05sWDI1aGJXVTZDbXh2WTJGcyIsImV4cCI6IjIwMjEtMDYtMTdUMTM6NTc6MjMuNDA2WiIsInB1ciI6ImJsb2Jfa2V5In19--d681dfeaee589b40e320b7b166644885b5b8c60f/screenpng.png)
Redirected to http://localhost:3000/rails/active_storage/disk/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaDdDVG9JYTJWNVNTSWhjbkI2YjJseE0yTTJiVE41ZGpneGNXMDBZMkk1TlhCd2NqQmhaQVk2QmtWVU9oQmthWE53YjNOcGRHbHZia2tpUldsdWJHbHVaVHNnWm1sc1pXNWhiV1U5SW5OamNtVmxibkJ1Wnk1d2JtY2lPeUJtYVd4bGJtRnRaU285VlZSR0xUZ25KM05qY21WbGJuQnVaeTV3Ym1jR093WlVPaEZqYjI1MFpXNTBYM1I1Y0dWSklnNXBiV0ZuWlM5d2JtY0dPd1pVT2hGelpYSjJhV05sWDI1aGJXVTZDbXh2WTJGcyIsImV4cCI6IjIwMjEtMDYtMTdUMTM6NTc6MjMuNDA2WiIsInB1ciI6ImJsb2Jfa2V5In19--d681dfeaee589b40e320b7b166644885b5b8c60f/screenpng.png
Completed 302 Found in 4ms (ActiveRecord: 0.3ms | Allocations: 1560)

Started GET "/rails/active_storage/disk/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaDdDVG9JYTJWNVNTSWhjbkI2YjJseE0yTTJiVE41ZGpneGNXMDBZMkk1TlhCd2NqQmhaQVk2QmtWVU9oQmthWE53YjNOcGRHbHZia2tpUldsdWJHbHVaVHNnWm1sc1pXNWhiV1U5SW5OamNtVmxibkJ1Wnk1d2JtY2lPeUJtYVd4bGJtRnRaU285VlZSR0xUZ25KM05qY21WbGJuQnVaeTV3Ym1jR093WlVPaEZqYjI1MFpXNTBYM1I1Y0dWSklnNXBiV0ZuWlM5d2JtY0dPd1pVT2hGelpYSjJhV05sWDI1aGJXVTZDbXh2WTJGcyIsImV4cCI6IjIwMjEtMDYtMTdUMTM6NTc6MjMuNDA2WiIsInB1ciI6ImJsb2Jfa2V5In19--d681dfeaee589b40e320b7b166644885b5b8c60f/screenpng.png" for ::1 at 2021-06-17 07:52:23 -0600
Processing by ActiveStorage::DiskController#show as PNG
  Parameters: {"encoded_key"=>"eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaDdDVG9JYTJWNVNTSWhjbkI2YjJseE0yTTJiVE41ZGpneGNXMDBZMkk1TlhCd2NqQmhaQVk2QmtWVU9oQmthWE53YjNOcGRHbHZia2tpUldsdWJHbHVaVHNnWm1sc1pXNWhiV1U5SW5OamNtVmxibkJ1Wnk1d2JtY2lPeUJtYVd4bGJtRnRaU285VlZSR0xUZ25KM05qY21WbGJuQnVaeTV3Ym1jR093WlVPaEZqYjI1MFpXNTBYM1I1Y0dWSklnNXBiV0ZuWlM5d2JtY0dPd1pVT2hGelpYSjJhV05sWDI1aGJXVTZDbXh2WTJGcyIsImV4cCI6IjIwMjEtMDYtMTdUMTM6NTc6MjMuNDA2WiIsInB1ciI6ImJsb2Jfa2V5In19--d681dfeaee589b40e320b7b166644885b5b8c60f", "filename"=>"screenpng"}
Completed 200 OK in 1ms (ActiveRecord: 0.0ms | Allocations: 236)
```
The reason I do not want to do this is because the blobs are now globally accessible, where I want them to be tenant specific.

The only difference that I can see between the one that is working vs the one that isn't is on the `ActiveStorage::Blob Load`. Tt doesn't appear to be connected to the correct shard? Therefore it doesn't find the blob?

**Comment by andykallhoff** [comment]
I figured out my issue. I understand it might not be the best solution, but it at least works the way we need it to for now. My quickfix explained:

```ruby
# app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
  connects_to shard: {
    db_one:  {writing: :db_one},
    db_two:  {writing: :db_two},
    db_three:  {writing: :db_three}
  }
end
```

Now as stated above my `ActiveStorage::Blob load` appeared to not be connecting to the proper database or shard. My fix assumes you already have some handler that is managing your connection for the tenant upon your blob load. For our app we are utilizing Devise and have an around action in the `application_controller` in order to get the tenant from the user.
If you somehow have access to the shard you can simply create the initializer and add the correct connection to the `set_blob` method here https://github.com/rails/rails/blob/1993496d7f661f6da35be093c8eff276b407c01e/activestorage/app/controllers/concerns/active_storage/set_blob.rb#L11
```ruby
# config/initializers/active_storage.rb
module ActiveStorage::SetBlob #:nodoc:
  ...
  
  def set_blob
    # get your shard here and wrap the `@blob` in that connection
    shard = :some_way_for_you_to_get_the_shard
    ActiveRecord::Base.connected_to(role: :writing, shard: shard) do
      @blob = ActiveStorage::Blob.find_signed!(params[:signed_blob_id] || params[:signed_id])
    end
  rescue ActiveSupport::MessageVerifier::InvalidSignature
    head :not_found
  end
end
```
I needed a little more than this though due to various reasons. So I _DID NOT_ do the above, but if you are storing all your attachments in a separate single db, this might be helpful.

If you noticed in my post above, the `GET` calls are happening separately all on their own. So I instead overwrote the `ActiveStorage::BaseController` inheritance to be our `ApplicationController`. https://github.com/rails/rails/blob/1993496d7f661f6da35be093c8eff276b407c01e/activestorage/app/controllers/active_storage/base_controller.rb#L4
```ruby
# app/controllers/active_storage/base_controller.rb
class ActiveStorage::BaseController < ApplicationController
  # I now have access to everything as a regular controller would
  # do whatever special devise authorization checks I need
  check_authorization except: [:example]
  
  include ActiveStorage::SetCurrent

  protect_from_forgery with: :exception

  self.etag_with_template_digest = false

  private
    def stream(blob)
      blob.download do |chunk|
        response.stream.write chunk
      end
    ensure
      response.stream.close
    end
end
```

Anyway, hope this helps someone!

**Comment by chaffeqa** [comment]
in addition to https://github.com/rails/rails/issues/38755#issuecomment-864170122 here is how we solved it:

```rails
%i[ active_storage_blob active_storage_attachment action_text_rich_text ].each do |slug|
  ActiveSupport.on_load(slug) do
    class_eval do
      connects_to(database: { writing: :db1, reading: :db1 })
    end
  end
end
```

**Comment by bessey** [comment]
> If you want Active Storage to look in different DBs for attachments to different records, that’s probably going to require framework support.

@georgeclaghorn are you open to a PR for this functionality? We are likely to face this exact use case soon. We are considering using Rails multi-DB support to respect data sovereignty requirements by keeping models that store user generated data in regional DBs, but still using a single globally replicated shared database for all other models.

I would envision this working something like this:

```ruby
class GlobalAttachment < ActiveStorage::Attachment
  connects_to(database: { writing: :global, reading: :global })
end

# I am a regional model
class User < ApplicationRecord
  # just uses ActiveStorage::Attachment, which uses the default regional DB
  has_one_attached :picture
end

# I am a global model
class BlogPost < ApplicationRecord
  connects_to :global
  has_one_attached :picture, class: GlobalAttachment
end
```

I think this has other use cases though - keeping business domains well isolated from each other might be one. Spinning out sections of an application into their own separate apps is another.
