### ISSUE TITLE
Disable creation of ar_internal_metadata table

### ISSUE THREAD

**Issue by nburns** [rails/rails#38750]
### Background Information
When using Rails with a database shared between multiple rails services it would be useful to have a way to disable the use of the InternalMetadata table. While migrating from legacy architecture, we have several microservices that read and write to a shared legacy database. These services can modify records in the database but none of them actually own said database, and so should never be migrating it.

### Steps to reproduce
Starting from an application with multiple databases ex:

```
  primary:
    adapter: postgresql
    url: postgresql://localhost/primary
  other:
    adapter: mysql2
    url: mysql://user@localhost/other
```

Where the database user for the `other` database has no permissions to create or modify tables, but has permission to insert, delete, select, and update individual records.

### Expected behavior
It should be possible to connect to and use the `other` database without rails attempting to create or read from the `ar_internal_metadata` table. (the env var `DISABLE_DATABASE_ENVIRONMENT_CHECK` does not disable interaction with this table, just the env check)

### Actual behavior
There is no way I know of to tell rails to not create this table.
`ActiveRecord::StatementInvalid: Mysql2::Error: CREATE command denied to user 'newuser'@'localhost' for table 'ar_internal_metadata'`

### System configuration
**Rails version**: Rails 6.0.2.1
**Ruby version**: ruby 2.5.7p206 (2019-10-01 revision 67816) [x86_64-darwin19]

**Comment by lsantobuono** [comment]
For some reason adding this flag to false in the test environment slowed significantly our RSpec load files time. 

Before this, it would take around 40 seconds the first time, and 3/4 seconds after that. I believe this variation has to do with spring caching the files.

After adding the flag, it took 40 seconds on every run. 

Still, I imagine this flag isn't probably intended to be added in test env but it might happen to someone else, so I wanted to share this.
