### ISSUE TITLE
api.rubyonrails.org is clipping the left panel on chrome/chromium linux

### ISSUE THREAD

**Issue by JoeDupuis** [rails/rails#38768]
### Steps to reproduce
Open https://api.rubyonrails.org/ on chromium or chrome on linux.
I will test on windows later today and update.

### Expected behavior
See correct behavior on firefox:
![20200319145114_b757b0945a](https://user-images.githubusercontent.com/1518299/77103631-1b0b9480-69f1-11ea-9221-b1e842a3ebfb.png)

### Actual behavior
On chrome the left menu is clipped
![20200319145209_236f4c86c9](https://user-images.githubusercontent.com/1518299/77103734-442c2500-69f1-11ea-91b5-f66fe2f4c4e8.png)

### System configuration
Chrome/Chromium Version 80.0.3987.116 (Official Build) (64-bit)
On nixos 19.09

### Other
Removing `overflow-x: hidden;` on `div#panel`
"fix" it.
![20200319145011_2v7vhdh2iq6u3oi6zv6](https://user-images.githubusercontent.com/1518299/77103976-9d945400-69f1-11ea-961f-fd3be2509b23.png)

**Comment by JoeDupuis** [comment]
Must be this : 
https://github.com/zzak/sdoc/commit/c80c3d1061f803973b37adeb8f165da991ca5541

**Comment by eugeneius** [comment]
This is fixed on master via https://github.com/rails/rails/pull/38731. You can see this in action on the edge docs: https://edgeapi.rubyonrails.org/

The stable docs at https://api.rubyonrails.org/ are only updated when a new release is published, so the problem will be fixed there when 6.0.3 is released.

**Comment by rafaelfranca** [comment]
This will be fixed in the next releases of all stable branches. Thank you for reporting.

**Comment by Ecco** [comment]
> The stable docs at https://api.rubyonrails.org/ are only updated when a new release is published, so the problem will be fixed there when 6.0.3 is released.

Well, I think it would have been better to publish a fixed version earlier (see the number of duplicate bugs). Hopefully 6.0.3 isn't too far away 😄

**Comment by josh-m-sharpe** [comment]
Checked this today.  Had to shift-refresh to get the 6.0.3 docs as my browser still had the 6.0.2.2 docs cached.  Seems fixed.  Thanks!
