### ISSUE TITLE
in_time_zone. Problem with +12 timezone. 

### ISSUE THREAD

**Issue by Corsten** [rails/rails#38765]
### Steps to reproduce

I have string '2020-03-18 11:00:00' with date time.
I use method .to_date for convert to DateTime format. 
After that i want to convert to timezone. I use in_time_zone method.

`my_datetime_string = '2020-03-18 06:00:00'
  my_datetime = my_datetime_string.to_datetime
  result_datetime = my_datetime.in_time_zone(12)
`
Method return Wed, 18 Mar 2020 19:00:00 NZDT +13:00
But I expect in +12 timezone.

If i use method in_time_zone and send timezone name it work fine. For example:

`my_datetime.in_time_zone('Kamchatka')`

Result: Wed, 18 Mar 2020 23:00:00 +12 +12:00

### Expected behavior
Expected result:  Wed, 18 Mar 2020 18:00:00 PETT +12:00

### Actual behavior
Actual result: Wed, 18 Mar 2020 19:00:00 NZDT +13:00

### System configuration
**Rails version**:
rails -v: 6.0.0
**Ruby version**:
ruby -v: ruby 2.6.2p47

**Comment by rishav-csenitjsr** [comment]
@rafaelfranca I was working around the fix for the above issue.
Just got stuck, can you please tell me which method gets invoked after **initialize** 
i.e. https://github.com/rails/rails/blob/master/activesupport/lib/active_support/time_with_zone.rb#L52
when we call ActiveSupport::TimeWithZone.new(time.utc? ? time : time.getutc, zone)
as we creating a new instance for TimeWithZone. So, it will call the **initialize** method but at the same time. It is also printing  this value Wed, 18 Mar 2020 19:00:00 NZDT +13:00
can you please help from where it is printing this value?

**Comment by Corsten** [comment]
As far as I understand, this issue may reproduce for timezone with Daylight Savings Time.
We have method 'dst?' for check this flag. https://apidock.com/rails/ActiveSupport/TimeWithZone/dst%3F

**Comment by rishav-csenitjsr** [comment]
yeah @Corsten you are right. I can reproduce it. Since **.in_time_zone(12)** is pointing to Auckland and **'.dst?'** is returning true for that.

**Comment by jonathanhefner** [comment]
Although perhaps surprising, I believe this is intended behavior.  The alternative would be that `in_time_zone` behaves differently at different times of the year.  (For a related discussion, see comments in #38081.)

Is there a reason you prefer not to specify the time zone by name?

Alternatively, you can use [DateTime#new_offset](https://docs.ruby-lang.org/en/2.6.0/DateTime.html#method-i-new_offset):
```ruby
"2020-03-18 06:00:00".to_datetime.new_offset("+1200")
# == Wed, 18 Mar 2020 18:00:00 +1200
```

**Comment by rishav-csenitjsr** [comment]
@jonathanhefner agreed with you. but, time zone by name is having the same behaviour when I am passing “Auckland” due to dst. So, the ideal way is to use Datetime#new_offset @Corsten

**Comment by Corsten** [comment]
Thanks. 
In my case I will use: 
`date.in_time_zone("Etc/GMT-#{utc_offset}").`
And it work properly.
