### ISSUE TITLE
Action Text doesn't update retroactively

### ISSUE THREAD

**Issue by cd-rum** [rails/rails#38764]
### Steps to reproduce
Add Action Text to a model _with existing records_ and try to update the Action Text column.

```
class Post < ApplicationRecord
  has_rich_text :new_body
end

=> Post.all.each { |post| post.new_body = 'test'; post.save }
```

### Expected behavior
The Action Text record should be created.

### Actual behavior
Gives an `undefined method 'render_action_text_content'` error.

### System configuration
Rails 6.0.2.1
Ruby 2.6.5

**Comment by jeremy** [comment]
@cd-rum, could you please provide a minimal Rails app that reproduces the issue you're seeing? (The information here isn't enough to offer any diagnosis.)

**Comment by danieldimitrov** [comment]
@cd-rum Unfortunately, can't replicate. Check [guides](https://guides.rubyonrails.org/contributing_to_ruby_on_rails.html#creating-a-bug-report), there are templates you can use for bug reports that will provide more info.
