### ISSUE TITLE
[guides] Explain how to use Webpacker for Javascript, or mention it exists

### ISSUE THREAD

**Issue by vdegove** [rails/rails#38767]
For now, there is no mention of Webpack in the official guides – neither on edge guides – except for Ruby on Rails 6 release notes and upgrade guide. The documentation of the Webpacker gem is quite good, but a newcomer to Rails wouldn't know at first that he needs to have a look to it.

Specifically, it would be good to have a mention of Webpack in the following guides:
* The Asset Pipeline
* Working with JavaScript in Rails

In case of more than a simple mention, there could be a quite thorough explanation of the current state of the recommended use of the Rails asset pipeline together with Webpack – e.g. use asset pipeline for normal CSS and images, and use Webpack for JS. It would be good also to mention that Turbolinks and UJS are (now) just Yarn packages.

Also, because of Webpack, Rails now depend on having a JS runtime on your computer and Yarn. This is briefly mentionned in the Getting Started guide, section Starting up the Web Server, but it could be more explicit in the Installing Rails part.

**Comment by eugeneius** [comment]
Webpacker should absolutely be covered in the Working With JavaScript guide, I'd be happy to see someone with experience using it in a real application take a stab at an update 😊 

The last point was already addressed by https://github.com/rails/rails/pull/38477 - the stable guides won't be republished until the next release, but you can see the updated content on the edge guides today:

https://edgeguides.rubyonrails.org/getting_started.html#installing-node-js-and-yarn

**Comment by mitchell-frost** [comment]
I am new to open source. Can I work on this?

**Comment by eugeneius** [comment]
Hey @mitchell-frost, thanks for offering to help!

There's a discussion on this topic happening at the moment on the forum:
https://discuss.rubyonrails.org/t/javascript-documentation-coordination/74970/9

@noelrappin has set up https://github.com/noelrappin/rails_javascript_documention_drafts as a place to collaborative on a guide focused on Webpacker, I think that's the best place to pitch in.

**Comment by vdegove** [comment]
Reopening the issue, as the guide being outdated when it comes to frontend is pretty annoying. @noelrappin guide would be a good start to reintegrate into official guides.

**Comment by vdegove** [comment]
(Hu, I can't reopen the issue myself.)
