### ISSUE TITLE
Usage of OpenSSL low level API by Digest breaks FIPS support

### ISSUE THREAD

**Issue by nahumcohen** [rails/rails#38791]
### Steps to reproduce

1. Make sure that ruby is running with OpenSSL FIPS complaint version. E.g. [OpenSSL_1_0_2u](https://github.com/openssl/openssl/tree/OpenSSL_1_0_2u/)
2. Enable FIPS mode in your application by adding the following:
```
OpenSSL.fips_mode = true
```
3. Enable SHA1 mitigation instead of MD5
[Rails documentation](https://guides.rubyonrails.org/configuring.html#configuring-active-support)
``` 
Rails.application.config.active_support.use_sha1_digests = true
```
4. Invoke rails method that using low level API. I.e. 'Digest::' without OpenSSL prefix
Use case: invoke ActiveSupport digest function. This is using the [activesupport gem](https://github.com/rails/rails/tree/master/activesupport)
```
class StatusController < ApplicationController
  def index
    OpenSSL.fips_mode = true
    # This commented line solves the issue of low level API in ActiveSupport gem
    # ActiveSupport::Digest.hash_digest_class = OpenSSL::Digest::SHA256.new
    # Notice: can use SHA1 instead of SHA256
    Rails.application.config.active_support.use_sha1_digests = true
    puts ActiveSupport::Digest.hexdigest("hello friend")
  end
end
```

### Expected behavior

Perform a valid Rails action for our use case display hash rendered by SHA256 algorithm.

### Actual behavior

The Fatal low level API exception is thrown
`sha256.c(34): OpenSSL internal error, assertion failed: Low level API call to digest SHA256 forbidden in FIPS mode!`

### System configuration
**Rails version**:
5.2.4.1

**Ruby version**:
2.5.7p206

We started to mitigate by patching several classes.
We can open a pull request if this is the right way.

**Comment by vipulnsward** [comment]
Do the failures on your App also include these uses: https://github.com/rails/rails/blob/3e0cdbeaf4e769ebd356a2c06dfae13d22283b7c/actionpack/lib/action_controller/metal/http_authentication.rb#L231
https://github.com/rails/rails/blob/c76a8c72d550734fc55877deecba0bf5dcc63c17/activesupport/lib/active_support/security_utils.rb#L27
?

**Comment by nahumcohen** [comment]
The workaround that worked for us is adding the following overriding Digest lines
```Digest::SHA256 = OpenSSL::Digest::SHA256
Digest::SHA1 = OpenSSL::Digest::SHA1```

**Comment by nahumcohen** [comment]
> Do the failures on your App also include these uses:
> 
> https://github.com/rails/rails/blob/3e0cdbeaf4e769ebd356a2c06dfae13d22283b7c/actionpack/lib/action_controller/metal/http_authentication.rb#L231
> 
> 
> https://github.com/rails/rails/blob/c76a8c72d550734fc55877deecba0bf5dcc63c17/activesupport/lib/active_support/security_utils.rb#L27
> 
> 
> ?

We didn't investigate these methods but they won't work for sure since they are using low level API and MD5.
