### ISSUE TITLE
Arel documentation

### ISSUE THREAD

**Issue by nicolas-brousse** [rails/rails#38790]
Does any documentation about Arel exist somewhere?
Each time I want to found documentation I have to go on https://github.com/rails/arel/tree/v8.0.0. Even in api there is not a log of information https://edgeapi.rubyonrails.org/classes/Arel.html.

If not I may work on a PR to do it 🙂

**Comment by kaspth** [comment]
Arel is still private API, so we don't publish the docs. Thanks!

**Comment by nicolas-brousse** [comment]
Ah! I didn't notice that. Thanks for your answer.

Does Arel will be a public API in (close) future?

**Comment by kaspth** [comment]
> Does Arel will be a public API in (close) future?

No plans for that at the moment. You'd be better off suggesting individual feature PRs with better wrapping APIs for what you find missing. Arel isn't Active Record, though it is part of the implementation, so just making that public feels like a design cop-out. But hey, a cogent argument could sway opinions 😉

Also with beginless/endless ranges in Ruby 2.7, I think we've already cleared a good chunk of why people resorted to Arel.
