### ISSUE TITLE
v6.0.2.2 tagged but not released?

### ISSUE THREAD

**Issue by nedenwalker** [rails/rails#38809]
### Steps to reproduce
Navigate to: https://github.com/rails/rails/releases
Notice that Latest Release is 6.0.2.1.

### Expected behavior
Latest Release is 6.0.2.2.

### Actual behavior
While 6.0.2.2 has been tagged, it does not appear to be Released. It should be Released?

### System configuration
**Rails version**: 6.0.2.2

**Comment by rafaelfranca** [comment]
Thank you for reporting. I'm fixing it.

**Comment by rafaelfranca** [comment]
Done https://github.com/rails/rails/releases/tag/v6.0.2.2

**Comment by nedenwalker** [comment]
Thank you for your service :) /wave to hometown Ottawa

**Comment by nedenwalker** [comment]
Hi there @rafaelfranca
This has occurred again with 6.0.3 and 6.0.3.1, where 6.0.3.1 was tagged but not released. We saw Rails released on Ruby Blog site and also in RubyGems, so we upgraded to 6.0.3.1.

We just happen to have a Concourse Pipeline that verifies our current release version with the Github Release version to determine if we are out of date and need to update. Back in March and again now, our pipeline failed since it actually thinks we have a Release from the future! (since Github thinks latest is 6.0.3)

I say all this because I am curious as to whether we should instead change to match against RubyGems Releases instead?

**Comment by rafaelfranca** [comment]
Not sure how GitHub thinks latest is 6.0.3, if it is using the "Last Release" ribbon like in the page I'd not use that because it depends on when a tag was created. For example I just tagged 5.2.4.3 and it thinks that is the latest release.
