### ISSUE TITLE
Do you have plan releases?

### ISSUE THREAD

**Issue by xxx44yyy** [rails/rails#38804]
### System configuration
**Rails version**:

**Ruby version**:

**Comment by kaspth** [comment]
Sure, Rails 6.0.3 and Rails 6.1 are both in the works. No official release dates yet.

**Comment by xxx44yyy** [comment]
> Sure, Rails 6.0.3 and Rails 6.1 are both in the works. No official release dates yet.

I'm wait... Good luck with release!
