### ISSUE TITLE
Mime-Type of S3 object is null

### ISSUE THREAD

**Issue by ksbek** [rails/rails#38817]
### Steps to reproduce
This is what I did for uploading css files to S3.
 ```@brand.compiled_css.attach(io: File.open(compressed_file), filename: "brand-#{@brand.id}.css", content_type: 'text/css')```

### Expected behavior
It is uploaded to s3 bucket correctly. I expected Content-type of S3 object is 'text/css'.

### Actual behavior
But it(Content-type) is empty. 
So I'm getting `SEC7113 "CSS was ignored due to mime type mismatch` error on IE 11. The page is completely broken.
Is this normal or just a bug?
And also why the key of S3 object is random string, not just filename?

### System configuration
**Rails version**:
5.2
**Ruby version**:
2.6.2

**Comment by georgeclaghorn** [comment]
This is expected. We didn’t start setting the Content-Type on the uploaded S3 object until 6.0.

**Comment by ksbek** [comment]
@georgeclaghorn thank you for your reply.
So if I upgrade Rails version to 6.0, Content-Type will be set?

**Comment by georgeclaghorn** [comment]
Yep, should be.

**Comment by sgmamsys** [comment]
Its not working even in rails 6

**Comment by Aliahmad486** [comment]
It is not working even in rails 7.1.3
