### ISSUE TITLE
ActiveSupport::Rescuable in a model doesn't seem to work

### ISSUE THREAD

**Issue by dudo** [rails/rails#38828]
### Steps to reproduce
```
module HandlesError
  extend ActiveSupport::Concern

  included do
    include ActiveSupport::Rescuable

    rescue_from StandardError, with: :handle_exception

    def handle_exception
      puts 'nah...'
    end
  end
end

class Service
  include HandlesError

  def self.boom?
    raise StandardError, 'BOOM'
  end
end
```

### Expected behavior
    > Service.new.boom?
    nah...

### Actual behavior
    > Service.new.boom?
    StandardError: BOOM

### System configuration
**Rails version**: Rails 5.2.4.1

**Ruby version**: ruby 2.5.5p157

Maybe my assumption is off, and this module is only useful in singletons like controllers? Can this be included in models successfully?

**Comment by kaspth** [comment]
It can. You have to call `rescue_with_handler` though. See the docs here https://api.rubyonrails.org/classes/ActiveSupport/Rescuable/ClassMethods.html

That's what Action Controller et al. does. Feel free to search here on GitHub to see it. Thanks!
