### ISSUE TITLE
Unexpected result when adding units to DateTime instance

### ISSUE THREAD

**Issue by kennethy** [rails/rails#38824]
It seems like the type on the unit is lost after arithmetic operations, and the units will be treated as days instead.

### Steps to reproduce

```ruby
# 1. setup
now = DateTime.now
(4 * 1.hour) == (4.hour) # true
```

### Expected behavior

The arithmetics are logically equivalent and thus should return identical result

```ruby
(now + 4 * 1.hour) == (now + 4.hour) # expected true
```

### Actual behavior

```ruby
(now + 4 * 1.hour) == (now + 4.hour) # returned false
```

It looks like `4 * 1.hour` (14400) are added as days instead.

### System configuration
**Rails version**:
4.1.16

**Ruby version**:
2.3.8p459

**Comment by eugeneius** [comment]
Rails 4.1 is no longer supported. See the maintenance policy: https://rubyonrails.org/maintenance/

If this is reproducible on master or 6-0-stable, we can reopen it.
