### ISSUE TITLE
belongs_to silences NOT NULL constraint in the foreign key

### ISSUE THREAD

**Issue by janko** [rails/rails#38845]
### Steps to reproduce

```rb
require "active_record"

ActiveRecord::Base.establish_connection(
  adapter: "sqlite3",
  database: ":memory:",
)

# this is the default in Rails
ActiveRecord::Base.belongs_to_required_by_default = true

ActiveRecord::Schema.define do
  create_table :artists do |t|
  end

  create_table :albums do |t|
    t.references :artist, foreign_key: true, null: false
  end
end

class Artist < ActiveRecord::Base
end

class Album < ActiveRecord::Base
  belongs_to :artist
end

Album.create
```

### Expected behavior

I would expect the `NOT NULL` constraint to raise an exception telling me I didn't set the foreign key column.

### Actual behavior

Instead, ActiveRecord converts the missing associated record into a validation error. This is the default in Rails.

This worries me, because it means that in production if my code didn't set an association by mistake, instead of me reading it in my exception tracker, the user will read it in their validation errors. The user will be confused, because they weren't asked to enter such resource in the form (let's assume that's the case), and I won't know about it.

I know this has been the default since I believe Rails 5.0, but that sounds like a dangerous default. Why is it desirable to mix associations with validations?

I know I can disable this behaviour by setting `ActiveRecord::Base.belongs_to_required_by_default` to `false`, but I'm concerned that it's enabled by default.

### System configuration

**Rails version**: 6.0.2.2

**Ruby version**: 2.6.5

**Comment by simi** [comment]
@janko I think I understand your concern, anyway this works the same for each validation. You need to ensure that UI provided for user to do model change (usually form) can pass related validations as well.

In your case you should probably access `album` thru `artist` in controller.

Alternatively I can imagine to mark `Album` model as not "top-level one" and prevent calling `create` method directly on that (raise on call).

```ruby
class Album < ActiveRecord::Base
  belongs_to :artist, enforce: true
  accessible_only_through :artist # would deserve better name
end

Album.create #=> raise as this should not be called directly (currently it will just add validation error)
@artist.create_album => properly scoped album created
Album.create(artist: @artist) #=> what do here?
```
But that seems really application related. Also it would be hard to support multiple `belongs_to` at the same time and probably impossible to make this default. `belongs_to_required_by_default` balances already on the edge of sane default IMHO.

**Comment by yoelblum** [comment]
@janko I never used this gem but it aims to bridge your validations with the database https://github.com/gregnavis/active_record_doctor#detecting-missing-presence-validations . Not sure it works for the association u need though

**Comment by janko** [comment]
@yoelblum Thanks, for this I would prefer to only have the NOT NULL constraint, because my particular foreign key isn't set by the user in a form, but it's set by the business logic. In this case a validation error would not be appropriate, because I could easily miss it if I use `save` instead of `save!`.

**Comment by yoelblum** [comment]
@janko Ah I see your pain now. I still think for most apps ActiveRecord::Base.belongs_to_required_by_default = true is the way to go . Maybe some external gem can fix this pain point in a nice way like @simi suggested

**Comment by swelltrain** [comment]
I might be missing something obvious, but isn't `.create` behaving as expected?

https://api.rubyonrails.org/classes/ActiveRecord/Persistence/ClassMethods.html#method-i-create
specifically: `Creates an object (or multiple objects) and saves it to the database, if validations pass.`.  Your validation does not pass so there is no chance for the db to raise based on the null constraint.  

There is the bang version `create!` which will indeed raise ActiveRecord::RecordInvalid.

**Comment by janko** [comment]
Yes, I’m not claiming there is a bug, I’m saying that for me belongs_to creating a validation is a dangerous default. It can cause the user to get a validation error that’s not related to their input, and the developer to not know they forgot to set the association.

**Comment by schuetzm** [comment]
I think you could use strict validations here:
https://apidock.com/rails/ActiveModel/StrictValidationFailed

They are for those cases where the failed validation isn't due to a user error, but due to a bug in your code, i.e. not correctable by the user. Unfortunately it's not possible to distinguish those two automatically, so there's probably no way for Rails to do the right thing in all cases; some kind of manual specification will be required.

Currently, you'll probably have to do it like this:

``` ruby
belongs_to :artist, optional: true
validates_presence_of :artist, strict: true
```

Maybe this could be simplified by adding an option to `belongs_to`:

``` ruby
belongs_to :artist, required: {strict: true}
# or
belongs_to :artist, strict: true
```
