### ISSUE TITLE
update habtm docs to note that optional: true is always set for both sides

### ISSUE THREAD

**Issue by modosc** [rails/rails#38855]
i would have thought that `belongs_to_required_by_default` would override this but it doesn't:

https://github.com/rails/rails/blob/3dff30c14fa25f211088d62da26611616ab5616f/activerecord/lib/active_record/associations/builder/has_and_belongs_to_many.rb#L40

it would be good to update the docs, i'll open a separate pr.

**Comment by sandip-mane** [comment]
@modosc I am new to open sourcing, could I take this as my first one?

**Comment by modosc** [comment]
@sandip-mane go for it! do you understand the problem i wanted to document?

**Comment by sandip-mane** [comment]
Yes
