### ISSUE TITLE
Sql injection from brakeman for Order by field in rails

### ISSUE THREAD

**Issue by sharmilasivakumar** [rails/rails#38860]
Rails version: 5.1.7

Getting Brakeman vulnerability warning for order by field with where clause query in rails 
Can, anyone help me to resolve this issue?
Thanks in advance

Query for your reference:
 DropdownValue.where(:dropdown_id => PreferenceValue.find(params[:id]).preference.dropdown_id).order("field(id, #{PreferenceValue.find(params[:id]).dropdown_value_ids.join(",")})")

**Comment by kaspth** [comment]
Please use the [rubyonrails-talk Discourse](https://discuss.rubyonrails.org/c/rubyonrails-talk/7) or StackOverflow for questions/help, where a wider community will be able to help you. We reserve the issues tracker for issues only. Rails 5.1 is also unsupported now, thanks.
