### ISSUE TITLE
Better error message for not-null constraint violations?

### ISSUE THREAD

**Issue by gilbert** [rails/rails#38884]
### Steps to reproduce

1. Create a model/migration with a non-null column constraint on the database level
2. Create a rails fixture that is missing that column
3. Run the tests

### Current behavior

```
ERROR["test_should_get_show", #<Minitest::Reporters::Suite:0x00007f8fb34ba308 @name="CommentsControllerTest">, 0.25182299996959046]
 test_should_get_show#CommentsControllerTest (0.25s)
DRb::DRbRemoteError:         DRb::DRbRemoteError: PG::NotNullViolation: ERROR:  null value in column "username" violates not-null constraint
        DETAIL:  Failing row contains (1032517720, 980190962, 663665735, null, null, null, 2020-04-06 16:11:26.165387, 2020-04-06 16:11:26.165387).
         (ActiveRecord::NotNullViolation)
```

### Desired behavior

The error message should display **which table** that the constraint violation is coming from. Either that or the fixture file it is occurring in.

### System configuration
**Rails version**: 6.0.2.1

**Ruby version**: 2.7.0p0

**Comment by gilbert** [comment]
Still active

**Comment by fatkodima** [comment]
Works as expected on latest version.
