### ISSUE TITLE
Rails 6, Zeitwerk, Act_as_helper

### ISSUE THREAD

**Issue by ph03n1x** [rails/rails#38896]
### Steps to reproduce

I ran my deploy command for capistrano and in the puma restart/start step, the issue pops up.

### Actual behavior

=== puma startup: 2020-04-07 21:22:19 +0000 ===
bundler: failed to load command: puma (/var/www/home/shared/bundle/ruby/2.5.0/bin/puma)
Zeitwerk::NameError: expected file app/helpers/acts_as_helpers.rb to define constant ActsAsHelpers, but didn't
  /var/www/home/shared/bundle/ruby/2.5.0/gems/zeitwerk-2.3.0/lib/zeitwerk/loader/callbacks.rb:17:in `on_file_autoloaded'
  /var/www/home/shared/bundle/ruby/2.5.0/gems/zeitwerk-2.3.0/lib/zeitwerk/kernel.rb:17:in `block in require'
  /var/www/home/shared/bundle/ruby/2.5.0/gems/zeitwerk-2.3.0/lib/zeitwerk/kernel.rb:16:in `tap'
  /var/www/home/shared/bundle/ruby/2.5.0/gems/zeitwerk-2.3.0/lib/zeitwerk/kernel.rb:16:in `require'
  /var/www/home/shared/bundle/ruby/2.5.0/gems/zeitwerk-2.3.0/lib/zeitwerk/loader.rb:381:in `const_get'
  /var/www/home/shared/bundle/ruby/2.5.0/gems/zeitwerk-2.3.0/lib/zeitwerk/loader.rb:381:in `block (2 levels) in eager_load'
  /var/www/home/shared/bundle/ruby/2.5.0/gems/zeitwerk-2.3.0/lib/zeitwerk/loader.rb:723:in `block in ls'
  /var/www/home/shared/bundle/ruby/2.5.0/gems/zeitwerk-2.3.0/lib/zeitwerk/loader.rb:720:in `foreach'
  /var/www/home/shared/bundle/ruby/2.5.0/gems/zeitwerk-2.3.0/lib/zeitwerk/loader.rb:720:in `ls'
  /var/www/home/shared/bundle/ruby/2.5.0/gems/zeitwerk-2.3.0/lib/zeitwerk/loader.rb:376:in `block in eager_load'
  /var/www/home/shared/bundle/ruby/2.5.0/gems/zeitwerk-2.3.0/lib/zeitwerk/loader.rb:368:in `synchronize'
  /var/www/home/shared/bundle/ruby/2.5.0/gems/zeitwerk-2.3.0/lib/zeitwerk/loader.rb:368:in `eager_load'
  /var/www/home/shared/bundle/ruby/2.5.0/gems/zeitwerk-2.3.0/lib/zeitwerk/loader.rb:483:in `each'
  /var/www/home/shared/bundle/ruby/2.5.0/gems/zeitwerk-2.3.0/lib/zeitwerk/loader.rb:483:in `eager_load_all'
  /var/www/home/shared/bundle/ruby/2.5.0/gems/railties-6.0.2.2/lib/rails/application/finisher.rb:122:in `block in <module:Finisher>'
  /var/www/home/shared/bundle/ruby/2.5.0/gems/railties-6.0.2.2/lib/rails/initializable.rb:32:in `instance_exec'
 /var/www/home/shared/bundle/ruby/2.5.0/gems/railties-6.0.2.2/lib/rails/initializable.rb:32:in `run'
  /var/www/home/shared/bundle/ruby/2.5.0/gems/railties-6.0.2.2/lib/rails/initializable.rb:61:in `block in run_initializers'
  /home/ubuntu/.rbenv/versions/2.5.0/lib/ruby/2.5.0/tsort.rb:228:in `block in tsort_each'
  /home/ubuntu/.rbenv/versions/2.5.0/lib/ruby/2.5.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
  /home/ubuntu/.rbenv/versions/2.5.0/lib/ruby/2.5.0/tsort.rb:431:in `each_strongly_connected_component_from'
  /home/ubuntu/.rbenv/versions/2.5.0/lib/ruby/2.5.0/tsort.rb:349:in `block in each_strongly_connected_component'
  /home/ubuntu/.rbenv/versions/2.5.0/lib/ruby/2.5.0/tsort.rb:347:in `each'
  /home/ubuntu/.rbenv/versions/2.5.0/lib/ruby/2.5.0/tsort.rb:347:in `call'
  /home/ubuntu/.rbenv/versions/2.5.0/lib/ruby/2.5.0/tsort.rb:347:in `each_strongly_connected_component'
  /home/ubuntu/.rbenv/versions/2.5.0/lib/ruby/2.5.0/tsort.rb:226:in `tsort_each'
  /home/ubuntu/.rbenv/versions/2.5.0/lib/ruby/2.5.0/tsort.rb:205:in `tsort_each'
/var/www/home/shared/bundle/ruby/2.5.0/gems/railties-6.0.2.2/lib/rails/initializable.rb:60:in `run_initializers'
  /var/www/home/shared/bundle/ruby/2.5.0/gems/railties-6.0.2.2/lib/rails/application.rb:363:in `initialize!'
  /var/www/home/current/config/environment.rb:5:in `<top (required)>'
  /var/www/home/current/config.ru:3:in `require'
  /var/www/home/current/config.ru:3:in `block in <main>'
  /var/www/home/shared/bundle/ruby/2.5.0/gems/rack-2.2.2/lib/rack/builder.rb:116:in `eval'
  /var/www/home/shared/bundle/ruby/2.5.0/gems/rack-2.2.2/lib/rack/builder.rb:116:in `new_from_string'
  /var/www/home/shared/bundle/ruby/2.5.0/gems/rack-2.2.2/lib/rack/builder.rb:105:in `load_file'
  /var/www/home/shared/bundle/ruby/2.5.0/gems/rack-2.2.2/lib/rack/builder.rb:66:in `parse_file'
  /var/www/home/shared/bundle/ruby/2.5.0/gems/puma-3.12.4/lib/puma/configuration.rb:320:in `load_rackup'
  /var/www/home/shared/bundle/ruby/2.5.0/gems/puma-3.12.4/lib/puma/configuration.rb:245:in `app'
  /var/www/home/shared/bundle/ruby/2.5.0/gems/puma-3.12.4/lib/puma/runner.rb:147:in `load_and_bind'
  /var/www/home/shared/bundle/ruby/2.5.0/gems/puma-3.12.4/lib/puma/single.rb:98:in `run'
 /var/www/home/shared/bundle/ruby/2.5.0/gems/puma-3.12.4/lib/puma/launcher.rb:186:in `run'
  /var/www/home/shared/bundle/ruby/2.5.0/gems/puma-3.12.4/lib/puma/cli.rb:80:in `run'
  /var/www/home/shared/bundle/ruby/2.5.0/gems/puma-3.12.4/bin/puma:10:in `<top (required)>'
  /var/www/home/shared/bundle/ruby/2.5.0/bin/puma:23:in `load'
  /var/www/home/shared/bundle/ruby/2.5.0/bin/puma:23:in `<top (required)>'

### System configuration
**Rails version**: 6.0.2.2

**Ruby version**: ruby 2.5.0p0 (2017-12-25 revision 61468) [x86_64-linux]

I have these lines at the top of my act_as_helper.rb file

require 'active_support/concern'

module Socialization
  module ActsAsHelpers
    extend ActiveSupport::Concern

**Comment by kaspth** [comment]
Usage questions are out of scope here. Please use the [rubyonrails-talk Discourse](https://discuss.rubyonrails.org/c/rubyonrails-talk/7) or StackOverflow for questions/help, where a wider community will be able to help you. We reserve the issues tracker for issues only.

Either do app/helpers/socialization/acts_as_helpers.rb or remove the wrapping Socialization module. Thanks!
