### ISSUE TITLE
Polymorphic association scope produces conditions out of order

### ISSUE THREAD

**Issue by zach-taylor** [rails/rails#38892]
### Steps to reproduce
Reproduction script: https://gist.github.com/zach-taylor/0d4455dec25291978b37b8098cb90ad5

or with Rails new:

```
rails new my-test-app
cd my-test-app
rails g model User name
rails g model Report name owner:references{polymorphic}:index
rails db:migrate
```
```ruby
# user.rb
class User < ApplicationRecord
  has_many :reports, as: :owner
end

# report.rb
class Report < ApplicationRecord
  belongs_to :owner, polymorphic: true
end
```

```
rails c
> user = User.create!(name: 'Josh')
> Report.create!(name: 'test report', owner: user)
> puts user.reports.to_sql
> puts User.joins(:reports).to_sql
```

### Expected behavior

Querying a polymorphic `has_many` association should place the _type column before the _id column in association queries such `user.reports`. The _type column should come before the _id column based on the discussion in #14143 where the change was made to generate multi-column indexes with the _type column first. You are much more likely to query by just the _type column than with just the _id column.

I would expect the SQL output to be:

```sql
SELECT "reports".* FROM "reports" WHERE "reports"."owner_type" = 'User' AND "reports"."owner_id" = 1
```

and for something like `User.joins(:reports).to_sql`:

```sql
SELECT "users".* FROM "users" INNER JOIN "reports" ON "reports"."owner_type" = 'User' AND "reports"."owner_id" = "users"."id"
```

### Actual behavior

The _id column condition is placed before the _type condition:

```sql
SELECT "reports".* FROM "reports" WHERE "reports"."owner_id" = 1 AND "reports"."owner_type" = 'User'
```

and:

```sql
SELECT "users".* FROM "users" INNER JOIN "reports" ON "reports"."owner_id" = "users"."id" AND "reports"."owner_type" = 'User'
```

### System configuration
**Rails version**: master and 6.0.2.2

**Ruby version**: 2.7.1

I've started working on a fix, but I am running into some test failures and am not very familiar with the AR code, so it could take a while.

**Comment by yoelblum** [comment]
I know it may be db implementation dependent, but is there an actual performance/EXPLAIN difference between the two queries ?

`SELECT "reports".* FROM "reports" WHERE "reports"."owner_type" = 'User' AND "reports"."owner_id" = 1`

And 

`SELECT "reports".* FROM "reports" WHERE "reports"."owner_id" = 1 AND "reports"."owner_type" = 'User'`

**Comment by zach-taylor** [comment]
@yoelblum after checking those out on my app's DB, there does not seem to be an EXPLAIN difference between those two queries, at least for Postgres, so this may not actually be a problem (besides consistency). Queries involving just a single condition ( `owner_id = ?` or `owner_type = ?`) seem to also be able to use the index. PG docs for this: https://www.postgresql.org/docs/current/indexes-multicolumn.html

 I do want to double check the explain for join queries and possibly some conditions other than equality `=`, so I'll get back to you on those.

**Comment by adlugopolski** [comment]
Looks like this change was introduced in https://github.com/rails/rails/commit/2c81e32aaa455ae89c557458c79b6fd4b305b887 There is little to no impact on performance, however consistency might be a problem here. We noticed because we do a consistency check on complex queries generated by Rails and after upgrade plenty of tests failed due to this change.

**Comment by adlugopolski** [comment]
@zach-taylor Do you still plan on fixing this issue? Do you have any code related to this bug available in a public fork?

**Comment by zach-taylor** [comment]
@adlugopolski I started an attempt at a fix, but got stuck. I think that commit https://github.com/rails/rails/commit/2c81e32aaa455ae89c557458c79b6fd4b305b887 fixed the join scenario in my reproduction script, but the other one still shows the `owner_id` before `owner_type`.
