### ISSUE TITLE
rename-column ignore column property except type.

### ISSUE THREAD

**Issue by DevStarSJ** [rails/rails#38897]
### Steps to reproduce
create_table :addresses do |t|
      t.string :raod_address, comment: 'full address'
end

rename_column :addresses, :raod_address, :road_address

then delete comment

### Expected behavior
I want to comment will be retained.

### Actual behavior
Comment deleted

### System configuration
**Rails version**: 6.0.2.2

**Ruby version**: 2.7

**Comment by eugeneius** [comment]
Which database adapter are you using?

**Comment by DevStarSJ** [comment]
I used mysql2 gem.
