### ISSUE TITLE
Rails 6.0.2.2 'new' command fails silently if 'git' is not available

### ISSUE THREAD

**Issue by slowaak49** [rails/rails#38894]
### Steps to reproduce

Run rails in a Fedora 31 Docker container and run `rails new` in that container.
```
cat >Dockerfile <<EOH
FROM fedora

RUN dnf install -y less which
RUN dnf group install -y "C Development Tools and Libraries"
RUN dnf install -y ruby-devel zlib-devel
RUN dnf install -y redhat-rpm-config
RUN dnf install -y rubygem-nokogiri

RUN dnf install -y patch
RUN gem install rails
RUN dnf install -y sqlite
EOH

docker build .
docker run --rm -it $(docker  build .) /bin/bash
rails new my-app
```
Note that Git is not installed, the Fedora image is Fedora 31 with minimal stuff installed.
The rails script stops silently just after stating that is running `git init`.  Looking in the generated directory there is no `.git` directory so obviously `git init` was not run successfully but there are no warning or error messages printed.

### Expected behavior
`rails new` should print a message when Git is missing similar to the message printed if NodeJS or Yarn are missing.

### Actual behavior
No messages printed after the 'Run git init' and the script returns to the command prompt.  The generated directory has only a few files and none of the subdirectories.

### System configuration
**Rails version**: 6.0.2.2

**Ruby version**: 2.6.5p114

**Comment by eugeneius** [comment]
Thanks for the report - this has been fixed in https://github.com/rails/rails/pull/38115, which will be released in 6.0.3.
