### ISSUE TITLE
Invoke a callback before retrying a job

### ISSUE THREAD

**Issue by Hirurg103** [rails/rails#38907]
I want to save current job retry number into a model. I could not figure out how to do this with current AJ API.

### Steps to reproduce:

```ruby
require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  gem "activejob", "6.0.2.2"
  gem "activerecord", "6.0.2.2"
  gem "sqlite3", "1.4.2"
end

require "active_record"
ActiveRecord::Base.establish_connection(adapter: "sqlite3", database: ":memory:")
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table "messages", force: :cascade do |t|
    t.text "text", null: false
    t.integer "notify_retries_count", default: 0
  end
end

require "global_id"
GlobalID.app = "AJ"
class Message < ActiveRecord::Base
  include GlobalID::Identification
end

class NetworkError < StandardError; end

require "active_job"
class DeliverMessageJob < ActiveJob::Base
  retry_on NetworkError, attempts: 2

  def perform(message)
    raise NetworkError.new('Bad request')
  end
end

require "minitest/autorun"
class InvokeCallbackOnRetryFailureTest < ActiveJob::TestCase

  def setup
    @message = Message.create!(text: 'I am Bob')
  end

  def test_increment_retries_count
    assert_raises NetworkError do
      perform_enqueued_jobs do
        DeliverMessageJob.perform_later @message
      end
    end

    assert_equal 2, @message.reload.notify_retries_count
  end

  def teardown
    @message.destroy
  end

end
```

### Expected behavior

I want to configure `before_retry` callback that increments `notify_retries_count` on a message when a deliver message job fails. Like this

```ruby
  retry_on(
    NetworkError,
    attempts: 2,
    before_retry: proc do |job|
      message = job.arguments[0]
      message.increment!(:notify_retries_count)
    end
  )
```

### Current implementation

For now I am using [active-job-retry](https://github.com/isaacseymour/activejob-retry) gem to achieve this:

```ruby
class DeliverMessageJob < ActiveJob::Base
  include ActiveJob::Retry.new(
    strategy: :constant,
    limit: 2,
    delay: 1.minute,
    callback: proc { |e| on_error(e) }
  )
  # ...
end
```

Also I tried to increment `notify_retries_count` in the `rescue_from` block:

```ruby
class DeliverMessageJob < ActiveJob::Base
  retry_on NetworkError, attempts: 5

  rescue_from NetworkError do |e|
    message = @arguments[0]
    message.increment! :notify_retries_count

    raise e
  end
  # ...
end
```
, but it is called only once when using with `retry_on`.

Do you have any idea how can I call code before a job retry? Thank you

**Comment by Hirurg103** [comment]
What do you think about adding `before_retry`, `after_retry` [AJ callbacks](https://api.rubyonrails.org/classes/ActiveJob/Callbacks/ClassMethods.html)?

**Comment by kaspth** [comment]
Since `retry_on` uses `rescue_from` internally, your last sample may be order dependent. Try moving your `rescue_from` above `retry_on` first or ditch `retry_on` here to manually call `retry_job` inside your `rescue_from`. Otherwise there's an avenue with `before_perform { |job| job.arguments.first.increment! :notify_retries_count }` that's worth exploring too.

I'm not keen on adding those suggested callbacks or this particular use case for them. Hope you figure it out, thanks!
