### ISSUE TITLE
Engine assets guide

### ISSUE THREAD

**Issue by fastengineer** [rails/rails#38908]
### Steps to reproduce
Create an rails engine
Test it with spec
Fails about assets

### Expected behavior
Guide says https://guides.rubyonrails.org/engines.html#separate-assets-precompiling
```ruby
initializer "blorgh.assets.precompile" do |app|
  app.config.assets.precompile += %w( admin.js admin.css )
end
```

It not works. I solved it with
```ruby
initializer "blorgh.assets.precompile" do |app|
  app.config.assets.precompile += %w( engine_name/admin.js engine_name/admin.css )
end
```

### System configuration
**Rails version**: 6

**Ruby version**: 2.7

**Comment by bekicot** [comment]
On latest rails (`6.0.2.2`) and ruby `2.6.6` & ruby `2.7.1`, the guides works fine to me.
