### ISSUE TITLE
Edit (but not create) Forms rendered through javascript using ERB appear to have their contents come after the close </form> tag, not within the form as expected

### ISSUE THREAD

**Issue by jasonfb** [rails/rails#38919]
### Steps to reproduce
download this sample app:
https://github.com/jasonfb/nested-forms-issue1

Using Ruby 2.6.4 (or change ruby version in file), do the following:
1) Start the rails server
2) navigate to /things

![Screen Shot 2020-04-10 at 10 20 22 AM](https://user-images.githubusercontent.com/59002/78997630-ed5bcc00-7b14-11ea-9b5d-e3e4a2120910.png)

3) Click "New Thing" (fancy javascript animation opens the new thing section)
![Screen Shot 2020-04-10 at 10 21 01 AM](https://user-images.githubusercontent.com/59002/78997671-02d0f600-7b15-11ea-8315-705678ad2cc5.png)

4) Give your New Thing a name and color  & click save
(sorry the page reloads here because I was lazy but this is not the bug)

5) Your list of things now looks like
![Screen Shot 2020-04-10 at 10 21 49 AM](https://user-images.githubusercontent.com/59002/78997728-1d0ad400-7b15-11ea-89f5-759195908b09.png)

6) 

Now click "Edit" next to the thing you want to edit. You now see this:
![Screen Shot 2020-04-10 at 10 22 22 AM](https://user-images.githubusercontent.com/59002/78997762-314ed100-7b15-11ea-89cc-d4cec34bf155.png)

7) Open Chrome inspector
and examine the row that looks editable to your

![Screen Shot 2020-04-10 at 10 23 43 AM](https://user-images.githubusercontent.com/59002/78997937-8db1f080-7b15-11ea-8834-b811c9e95a21.png)

8) Notie the ```<form ...></form> ```element is immediately closed, **leaving the contents that is supposed to be inside the form to be rendered after the ``` </form>``` close**

![2020-04-10@10-24 - DevTools - 127 0 0 13000things(1)](https://user-images.githubusercontent.com/59002/78997955-9b677600-7b15-11ea-8dfa-e8312bb0306f.png)

9) You will notice that the "Save" button does nothing when you click it, because of course, it is not inside the form like it is supposed to be

### Expected behavior
- the nested input elements render WITHIN the form, not after it. 
- the "Save" button, rendered correctly inside of the form, submits the form

### Actual behavior
- the nested input elements render OUTSIDE the form after its close tag
- the "Save" button does nothing

### System configuration
**Rails version**:
6.0.2.2
**Ruby version**:
2.6.4

**Comment by jasonfb** [comment]
Fixed!

My problem was that I was rendering into a table row <tr> content that was not inside of a <td>

this malformed content was breaking the form, making the contents come outside of the form as explained above

**Comment by 2called-chaos** [comment]
@jasonfb 
> My problem was that I was rendering into a table row content that was not inside of a
> My problem was that I was rendering into a table row &lt;tr&gt; content that was not inside of a &lt;td&gt;

Markdown eats your `<tr>` and `<td>` if you don't escape or backtick them ;)

**Comment by jasonfb** [comment]
right. but in my case I was actually just rendering raw HTML into a `<TR>` without using a `<TD>` (dirty I know) which looked from the browser's perspective as-if it worked, but actually caused this weird side-effect of spilling the form contents out to outside of the form. in fact it had nothing to do with Rails.
