### ISSUE TITLE
The purpose of code in the retry_on block is not evident

### ISSUE THREAD

**Issue by Hirurg103** [rails/rails#38911]
For me it is not evident that code that sits inside `retry_on` block will be called when all retry attempts fail until I read the documentation.

For me is more clear to put this code into a named keyword argument like this:

```ruby
retry_on(
  NetworkError,
  attempts: 3,
  on_all_attempts_fail: proc do |job, err|
    custom_code
  end
)

# or

retry_on NetworkError, attempts: 3, on_all_attempts_fail: :custom_method
```

For me the syntax above follows the [Least Surprise Principle](https://en.wikipedia.org/wiki/Principle_of_least_astonishment). What do you think about it?

**Comment by kaspth** [comment]
I should have mentioned it in https://github.com/rails/rails/issues/38907#issuecomment-611651781 but we don't take feature requests on the issues tracker.

> until I read the documentation.

It's fine that there's occasional API, or like here an option of an API, that's not immediately evident, anonymous blocks potentially have that in their very nature. Our documentation is there to bridge that gap and provide context. I also liked Matz' interpretation of Principle of Least Surprise, which I think is a fairly close fit to our usage, here: https://www.artima.com/intv/ruby.html
