### ISSUE TITLE
HABTM sort order

### ISSUE THREAD

**Issue by foonlyboy** [rails/rails#38921]
has_and_belongs_to_many
should be extended
to optionally preserve the order of elements

c is a Set by concept.
But many times, ordering is needed.

I'd like to suggest to extend has_and_belongs_to_many
to specify an ordering column.

That might read like:
has_and_belongs_to_many :foo, order:true

This would involve a new column in the relation table.
Let's call this 'sort_order' for the discussion ahead.
aka: has_and_belongs_to_many :foo, order:true, order_key:'sort_order'

By declaring a habtm like this,
- the ordering should be persisted on saving the relation
- the ordering should be restored on loading the relation

---

There might already be a cool gem to do that,
but I really want to bring this into the rails core.
with ease

~eike

**Comment by kaspth** [comment]
You can pass a scope to the definition:

`has_and_belongs_to_many :foos, -> { order(‘sort_order’) }`

**Comment by foonlyboy** [comment]
Hi Kasper,

Thanks for you reply
I was aware of this.

but I'm asking to *write* that sort_order column,
automatically by convention

**Comment by kaspth** [comment]
I got that, but there isn't anything to gain from that "convention". It'll be highly association specific anyway. Passing a scope is just the right amount of gel here: it makes your use-case possible without opening the door to also having to consider a boatload of other configurations. Something like `includes: %i[ author ]` or whatever else is already implemented on relation comes to mind. We'll pass, thanks.

**Comment by foonlyboy** [comment]
Hi Kasper,
thanks for your reply.

I'm aware that that a lot if it might be use specific, but this is not the
scope today.

I'm asking for a common case.
In rails, an association is mapped to the Array type.
Arrays are ordered.

It's really easy to map m:n relations with rails by declaration:
it's called the HABMT (has_and_belongs_to_many)

However, the order is lost.

I fully understand that habtm declares a Relation which by definition is a
Set and is not ordered.
But in my daily live, ordering is important.
Sidenote: The big pro in ruby is, that even hashes are ordered, and all
operations keep order.

I know how to achieve the ordering with making it a has_and_belongs trough:
but this always needs extra boiler code, which spreads out.

This is a long standing problem.

I'd like to suggest that the habtm should be optionally extended,
to include a column in the join table,
to save the order of the related items,
so that the association can be reloaded in the same order as it was saved.

This needs a new integer column in the join table,
which should be set upon saving the relation array
and should reload that association by that ordering.

Maybe this has been discussed before a many times,
I fear there must be many pitfalls in the details.

I'm pretty much aware about relational algebra,
but the customers want to have it ordered.

I tried to find a gem for this,
but to no avail.

I know this must be a hard problem,
othwerwise it would already have been fixed.

Let's talk about
~eike

**Comment by foonlyboy** [comment]
Hi Kasper,

I'm aware of the scopes.
works like a charme.

But I want to make this automatic.
I want to write ordering by declaration.

I'm sure this can be done quite easily.
Maybe I'm just to shy to get into that.

Please suggest a good default name for the column.

~eike
