### ISSUE TITLE
Selectively skipping schema dumps after running migrations (multi-db)

### ISSUE THREAD

**Issue by david-pm** [rails/rails#38927]
### Steps to reproduce

Not a bug really, but I am trying to gauge the community interest. ActiveRecord exposes:
`config.active_record.dump_schema_after_migration = false`
for skipping the schema dump after running migrations. It works great!

I have multiple databases in a Rails6 project and would like to be able to skip the schema dump for one of them but not the others. Unfortunately, this is an all or nothing situation. I'm currently hacking around it the old fashioned way by dropping the `db:schema:dump` task and recreating by hand. Not great.

For those curious, I'm basically copy pasting [the source here and slipping in this line](https://github.com/rails/rails/blob/f33d52c95217212cbacc8d5e44b5a8e3cdc6f5b3/activerecord/lib/active_record/railties/databases.rake#L390-L391):
```ruby
next if db_config.config['database'].match /my_special_snowflake_db/
```

### Expected behavior

It would be incredible if I could specify a list of schema names or something to the configuration. Is there anyone else out there that agrees? Just me? I'm betting with the addition of multi-db support I am not alone.

### Actual behavior

Setting: `config.active_record.dump_schema_after_migration = false`
skips the dump for _all_ databases in your application and there is no clean way to selectively skip databases without hacking around in your rake tasks (which is my solution) or forking rails itself.

### System configuration
**Rails version**:
<kbd>6.0.2.1</kbd>
**Ruby version**:
<kbd>2.6.6</kbd>

**Comment by eileencodes** [comment]
This is kind of a feature and kind of a bug. I can't promise to have time to fix this for 6.1 but will consider getting it in for 6.2. Thanks for the report.

**Comment by lfv89** [comment]
@eileencodes,

would you go with such interface?
```
config.active_record.dump_schema_after_migration = { primary: true, snowflake_db: false }
```

I'm considering jumping into this one, any input would be much appreciated.

**Comment by eileencodes** [comment]
@lfv89  I think your interface would work as long as adding `primary: true` to the hash wasn't required. I think it should default to assuming they are all true unless specified.

The other option is not make this an app option, but rather make this a database configuration option.  I actually kind of prefer this since we recently added one for metadata table support. https://github.com/rails/rails/pull/38751 

That way it would mean using the config option it's on/off for every database, otherwise add specific settings in the database configuration. What do you think?

**Comment by lfv89** [comment]
> The other option is not make this an app option, but rather make this a database configuration option. I actually kind of prefer this since we recently added one for metadata table support. #38751

It really looks more appropriated.

After adding it as a database configuration option, I'm thinking that would make sense to make the app config have precedence over the more granular database configuration, would you agree?

**Comment by eileencodes** [comment]
> I'm thinking that would make sense to make the app config have precedence over these more granular database configuration, would you agree?

Yup that sounds good.

**Comment by nPaul** [comment]
I think good idea do it in configuration database file
example
production:
    primary:
        migrations_paths: db/migrate
        dump_schema_after_migration: true
        database: qwe
        username: qweqwe
    another_read_only_database:
        migration: false # DISABLE MIGRATION becouse database is read only
        migrations_paths: db/migrate_qweqweqwe #  WHY it need if database only read?
        dump_schema_after_migration: false # 
        database: qwe
        username: qweqwe
......

**Comment by januszm** [comment]
There is one case where you probably want to set this `dump_schema_after_migration` to `false` for all databases - production environment.
I just experienced how the lack of this setting (missing `dump_schema_after_migration` line) in production can cause locks on tables. What do you think about having this option always turned off outside the development environment?

**Comment by marcelolx** [comment]
@eileencodes Since https://github.com/rails/rails/pull/42804 has been merged I think we can close this one, right?
