### ISSUE TITLE
ActiveRecord::Calculations#calculate doesn't respect valid order clasues

### ISSUE THREAD

**Issue by alimi** [rails/rails#38936]
### Steps to reproduce

Run the following test

```ruby
# frozen_string_literal: true

require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  gem "rails", github: "rails/rails"
  gem "sqlite3"
end

require "active_record"
require "minitest/autorun"
require "logger"

# This connection will do for database-independent bug reports.
ActiveRecord::Base.establish_connection(adapter: "sqlite3", database: ":memory:")
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :posts, force: true do |t|
    t.string :author
  end

  create_table :comments, force: true do |t|
    t.integer :post_id
  end
end

class Post < ActiveRecord::Base
  has_many :comments
end

class Comment < ActiveRecord::Base
  belongs_to :post
end

class BugTest < Minitest::Test
  def setup
    Post.create!(author: "Ali")
    Post.create!(author: "Bob")
    Post.create!(author: "Charlie")
  end

  def test_group_by_with_order_by_and_limit
    expected = { "Charlie" => 0, "Bob" => 0 }
    actual = Post.includes(:comments).group(:author).order(author: :desc).limit(2).count("comments.id")
    assert_equal expected, actual
  end
end
```

This is heavily inspired by an existing test.

https://github.com/rails/rails/blob/3a255ab0724fd6752e2a54fb50024cdf5da5a2ca/activerecord/test/cases/calculations_test.rb#L790-L794

### Expected behavior

I would expect the test to pass because `actual` should be ordered by `author: :desc`.

### Actual behavior

The test fails because the order clause isn't being applied. We can see it's missing in the logs.

```
D, [2020-04-13T13:52:12.459530 #74945] DEBUG -- :    (0.7ms)  SELECT COUNT(DISTINCT comments.id) AS count_comments_id, "posts"."author" AS posts_author FROM "posts" LEFT OUTER JOIN "comments" ON "comments"."post_id" = "posts"."id" GROUP BY "posts"."author" LIMIT ?  [["LIMIT", 2]]
```

The order clause gets stripped out for all databases here:

https://github.com/rails/rails/blob/887d4e1df53309e63096b43a16c3475bac87bbb2/activerecord/lib/active_record/relation/calculations.rb#L138-L139

It looks like this change was made because some count queries generate invalid SQL(https://github.com/rails/rails/pull/35850). Would it be possible to keep valid order clauses?

Note: I noticed this while working with CockroachDB. [This test](https://github.com/rails/rails/blob/3a255ab0724fd6752e2a54fb50024cdf5da5a2ca/activerecord/test/cases/calculations_test.rb#L790-L794) fails against CockroachDB because it won't inherently order by the group clause.

### System configuration
**Rails version**: master

**Ruby version**: 2.5.3

**Comment by rafaelfranca** [comment]
cc @kamipo
