### ISSUE TITLE
Feature: DSL: normalize :column

### ISSUE THREAD

**Issue by foonlyboy** [rails/rails#38949]
Hi at rails,
I'm aware that this not the channel to write about new features, so please excuse.

I'd like to suggest a new feature for the rails dsl:

Example:
{{{normalize :some_column, -> {|value| value&.strip} }}}

This pertains to both, writing and reading the value.

As of today this should be done in the controller in the first place,
or it must be done in the model by overwriting the r/w accessors manually.

Im aware that this will open a new can of worms in many places.
But then, it would be so striking, to just declare it that easily.

**Comment by kaspth** [comment]
> I'm aware that this not the channel to write about new features, so please excuse.

Sorry, we simply can't. That's our boundary for now.

> But then, it would be so striking, to just declare it that easily.

We've got the attributes API, so you can register a Stripped type and do `attribute :value, :stripped` which will do all that. Think this is just outside the bounds of core, could be a great fit for a gem. Thanks ✌️

**Comment by foonlyboy** [comment]
Hi Kasper,

I wrote to the wrong channel,
please excuse

But then this makes us contact.
~eike
