### ISSUE TITLE
Same Javascript pack loaded multiple times

### ISSUE THREAD

**Issue by woniesong92** [rails/rails#38941]
I noticed from the console that the same JavaScript pack was loaded multiple times. It looks like the source file is different though: one from the actual source file and the other from the webpack bundle. This is causing an unexpected behavior when I try to render a react component in a loaded DOM.

![loaded_multiple_times](https://user-images.githubusercontent.com/2935309/79171276-75a4d000-7da6-11ea-9cbb-33caec45bfc1.png)

Can anyone explain why this is happening and what I can do to fix it?

Repro:

```
// edit.html.erb
<%= javascript_pack_tag 'SomeEdit', 'data-turbolinks-track': 'reload' %>

// SomeEdit.js
console.log("I'm loaded!")
console.log(true)
```

**Comment by eileencodes** [comment]
The `javascript_pack_tag` is defined by Webpacker, please report the bug over in https://github.com/rails/webpacker. Thanks!
