### ISSUE TITLE
100% CPU usage in development

### ISSUE THREAD

**Issue by rusikf** [rails/rails#38944]
### Steps to reproduce
Go to any route in browser

### Expected behavior
Not 100% cpu usage
### Actual behavior

100% cpu usage often

**May be this related to sprockets ? When I run `top` I see 100% puma cpu usage , but can't see detailed logs.**

### System configuration
**Rails version**:
Rails 5.1
**Ruby version**:

ruby 2.4.6p354 (2019-04-01 revision 67394) [x86_64-linux]

**Comment by eileencodes** [comment]
Hey @rusikf thank for the report. Unfortunately there's not enough information here for us to determine whether this is a bug. We don't have other reports of this.

Can you reproduce this on a supported Rails verison?

**Comment by Lewiscowles1986** [comment]
I have experienced a similar bug, as has @mroderick when working on a Rails 5 application, which I notice this is.

I ceased experiencing it when moving to an i5 & i7 processor with 16GB RAM. I took this as a signal that whatever was happening (existing application, we did not author) it was programmer induced, not framework induced.

The machine I experienced this on had an i3 processor, and I believe the machine @mroderick was using was a modern macbook air around 2018/2019.

I'm fairly certain docker was also a part of the behavior we observed. Running shared services such as postgres and a queue in docker, alongside our application (not in container).

1. I'm not sure this is Rails, alone
2. I think hardware plays a part in this

Would you be able to share your Gemfile and be able to provide further information about the hardware you're running on, and some general details around setup (db, docker, queue)?

We no longer have access to the codebase we experienced this with.

**Comment by mroderick** [comment]
This was the commit that fixed it.

> add delay config for local sqs queue
>
> by default shoryuken queues have a delay value of `0`, which means it is
> constantly checking for new messages. This was causing very high cpu
> usage in my development environment.
>
> so I have added a config file for local development, and set shoryuken
> to only check for new messages every 5 seconds.

In `config/shoryuken.yml`

```yml
delay: 5
queues:
  - [some_queue_local, 1]
```

This solved the issue for myself and for the original author of the fix.
