### ISSUE TITLE
Feature: cached tables

### ISSUE THREAD

**Issue by foonlyboy** [rails/rails#38951]
I'd like to suggest a new feature:
I want to mark tables as 'cached'

Rationale:
I have many tables with constants that don't ever change.
It would be good enough, to read the whole table only once,
put them in some long lasting hash,
and then never need to go back to the database for query,
aka not needing a round trip to the database just to satisfy that well know values.

As of now, I'm doing this with handcrafted code.
I believe there could be a DSL for that.

Obviously, caching is not easy.
We should start naive: just cache the table once.
(take care to really deep freeze it)

I'd then expect that #find, #find_by 
should depend on the cached version of the table.

More importantly though,
resolving the Relations to these tables,
should use the cache.

Things get a lot more complicated
once we start with updatable caches,
think: find_or_create!

I'd suggest, we should start with a very limited definition of what a cacheable table can do.
But even that might prove useful for many use cases.

---
Who told you that rails is slow?
I just added cacheable: true

In my case this saves a lot of roundtrips to the database.
I did optimize all the preloads.

Guess what?
A hash lookup is a lot faster than a request to the database.

**Comment by rafaelfranca** [comment]
Thank you so much for the issue but we don't take feature request on the issue tracker. We recommend you to try to implement the feature and send us a pull request or if you are in doubt if the feature will be accepts ask in Rails Core mailing list for feedback.

**Comment by foonlyboy** [comment]
Hi Raffaele,

sorry for writing this.
but then, let's talk about it.

Please excuse me writing 3 issues,
nice to get in contact.

~eike
