### ISSUE TITLE
core methods

### ISSUE THREAD

**Issue by foonlyboy** [rails/rails#38952]
Hi at the rails team,

once, when I was with NeXT,
we learned somthing about Collections:
reduce it to only the fewest verbs and attributes possible.

But in the codebase,
sometimes it's take or take!
(do I need to rewrite take or take!)

Throughout the codebase,
there is now too much entaglement.

I'm asking all of you, to make a cleanup.

**Comment by rafaelfranca** [comment]
This is a final warning. We already tried to tell you which are the rules of engagement of this issue tracker. If you continue to open issues with feature requests and not actual problems we will have to ban you.

About `take` or `take!` this is by design and we don't need to cleanup anything.

**Comment by kaspth** [comment]
Based on: https://github.com/rails/rails/issues/38951, https://github.com/rails/rails/issues/38949, https://github.com/rails/rails/issues/38921

**Comment by foonlyboy** [comment]
Sorry, please don't close me.
Excuse
~eike

**Comment by kaspth** [comment]
> Excuse

You can't keep disregarding what we're telling you and then just saying "excuse" as if that fixes anything. We can look past things if the behavior changes, but if doesn't the excuse is meaningless.

The fact that it took a warning for you to hear us, should be eye-opening for you. You're more than welcome to contribute in the future, but your current path is unfortunately not constructive to put it mildly. Please do introspect 🙏

**Comment by foonlyboy** [comment]
Hi Kasper,
I'm looking forward to work with you.

You do make some communications,
let's work together, to promote the good things.

---

as of today, your acting is off roads.
don'f fuck me.

what you think you kid?
tell me who you are, tell me what you did.
