### ISSUE TITLE
AR `update_column` arguments are not intuitive

### ISSUE THREAD

**Issue by terracatta** [rails/rails#38969]
### Steps to reproduce
1. Write some model code that uses `update()` ex `Thing.update(cool: true)`
1. Realize you don't want callbacks to fire so you change it to `Thing.update_column(cool: true)`
1. Waste time because you forgot `update_column` takes 2 arguments, not an options hash
1. Arbitrarily discuss with co-workers that we should be using `update_column` vs `update_columns`
1. Realize that `update_column` just calls `update_columns` in the Rails code-base
1. Feel silly

### Expected behavior
`update_column` does not exist (or is deprecated) and only `update_columns` exists so that future Rails developers do not have to learn this painful lesson.

While `update_column` is burned into my brain and I will forever type it, I think removing it for the benefit of new Rails devs is worthwhile. In my workflow I frequently convert `update` to a non-callback version of `update` and don't even think about changing the arguments.

I have been writing rails for over 10 years and I have made this mistake maybe 20 - 30 times. I just made it today, and I've reached the threshold where I am filing an issue so we can deprecate this API and maybe delete it in Rails 7.

Curious if others have this problem.

### System configuration
**Rails version**: 6.0.2.2

**Comment by simi** [comment]
@terracatta would it be possible to support both variants for `update_column`? Isn't that syntax somehow in conflict?

**Comment by rafaelfranca** [comment]
`update_column` is equivalent to `update_attribute` that also takes two arguments, no to `update`.

That being said, while I can see why you make this mistake I don't think it warrants changing the API of `update_column`
