### ISSUE TITLE
[ActiveStorage] Error stream download in some S3 provider (range exceeded content-length)

### ISSUE THREAD

**Issue by ukolovda** [rails/rails#38961]
### Steps to reproduce
Some S3 provider give error on ActiveStorage Preview operation.

It appears because ActiveStorage::Service::S3Service try download big chunks (5 megabytes):

```
      def stream(key)
        object = object_for(key)

        chunk_size = 5.megabytes
        offset = 0

        raise ActiveStorage::FileNotFoundError unless object.exists?

        while offset < object.content_length
          yield object.get(range: "bytes=#{offset}-#{offset + chunk_size - 1}").body.string.force_encoding(Encoding::BINARY)
          offset += chunk_size
        end
      end
```

### Expected behavior
`object.get(range:xxx)` should not exceed content length.

### Actual behavior
It request chunk by 5 megabytes.

### System configuration
**Rails version**:
6.0.2.2, Master

**Ruby version**:
2.6.5

**Comment by jonathanhefner** [comment]
Relevant PR: #38962.

**Comment by eugeneius** [comment]
Closing per https://github.com/rails/rails/pull/38962#issuecomment-615954927.

**Comment by ukolovda** [comment]
Ok, I understand, thank you.
S3 provider have fixed API now.
