### ISSUE TITLE
rails-ujs breaks cross-domain remote forms (jquery-ujs works)

### ISSUE THREAD

**Issue by DavidJLee** [rails/rails#38960]
### Steps to reproduce
Submit a "remote" form cross-domain using rails-ujs. same-domain submissions work as expected, however cross-domain submissions are broken.

Note that this does require proper cross-domain security headers to be in place so the request can reach the server. 

### Expected behavior
Using rails-ujs should behave in the same way as jquery-ujs across domains.
When using a "remote" form the data should be submitted via rails-ujs, and rails will respond with js which is then executed by rails-ujs ("remote" form handling should work across domains). 

### Actual behavior
The remote form submits data via rails-ujs, but the rails application responds with HTML instead of js, meaning the response is *not* executed by rails-ujs. It instead generates an error of: `Refused to get unsafe header X-Xhr-Redirect`

### System configuration
**Rails version**: 6.0.2.2 (I believe this impacts all versions that use rails-ujs instead of jquery-ujs)

**Ruby version**: 2.5.5

### Quick Summary of root cause

The `Accept` header generated by jquery-ujs differs from the header generated by rails-ujs

### Details
Where code in `/actionpack/lib/action_dispatch/http/mime_negotiation.rb` handles the "formats" method used to respond to these requests with js.

Data submitted cross domain does not include the `X-Requested-With` header. This is true for both rails-ujs *and* jquery-ujs implementation. Because the header does not exist, `xhr?` is not true

This means the Accept header is compared to `BROWSER_LIKE_ACCEPTS`

In jquery-ujs the Accept header is set as:
`*/*;q=0.5, text/javascript, application/javascript, application/ecmascript, application/x-ecmascript`

Which does *not* match the `BROWSER_LIKE_ACCEPTS` regex, causing the code to properly return the js format

However, in rails-ujs the Accept header is set as:
`text/javascript, application/javascript, application/ecmascript, application/x-ecmascript, */*; q=0.01`

Which *does* match the `BROWSER_LIKE_ACCEPTS` regex, causing the code to *always* return html format only, even though clearly it should be js based on the Accept header.

### Possible Fixes

The `BROWSER_LIKE_ACCEPTS` header is ignoring `*/*;q=0.5` at the start of Accept header strings. Is this intentional?  If so, rails-ujs should prepend the `*/*; q=0.01` to the accept header as opposed to appending it. (code at `/actionview/app/assets/javascripts/rails-ujs/utils/ajax.coffee`) this would mimic the jquery-ujs behavior, and I believe be the ideal solution since it makes rails-ujs behave closer to the code it replaced.

I'm unclear why rails-ujs should append or prepend `*/*` at all, given that rails prefers accept strings *without* the wildcard. So removing the addition of the wildcard might be a sane approach as well.

However, if `BROWSER_LIKE_ACCEPTS` is *supposed* to be catching `*/*` at the start of an Accept header string the regex would need to be changed. I don't think this is a valid solution however. First, I'm not clear why the accept header gets thrown out if a wildcard exists (especially when it's weighted less than other values). Second, I'm not sure how one would "remote" submit a form across domains as the return type would always be HTML, from either rails-ujs or jquery-ujs.

**Comment by SughoshRao** [comment]
@DavidJLee Did you end up resolving this issue? Looks like this is still an issue on Rails 6.0.3..

**Comment by DavidJLee** [comment]
I have not tried to reproduce with a more recent version of Rails. I have a workaround in place, which works for me, but ideally rails-ujs should be fixed up. I can submit a pull request, but I'm not clear if the change was intentional, or the reasoning behind the current implementation of the accept header handling. 

The workaround is to include the format in the form target (e.g. /path/to/form.js), which circumvents the accept header handling.

**Comment by SughoshRao** [comment]
Thank you @DavidJLee, your workaround helped.

This is still an issue with rails-ujs and this issue should be reopened based on your original description.
