### ISSUE TITLE
Dumps with multi-db configurations are not updated after execution rake db:migrate for single DB

### ISSUE THREAD

**Issue by alvir** [rails/rails#38976]
I've checked this in code and I've noticed that we don't create [any dumps](https://github.com/rails/rails/blob/v6.0.2.2/activerecord/lib/active_record/railties/databases.rake#L114).

### Steps to reproduce

1. We have to DBs `primary` and `secondary`
1. Execute `rake db:migrate:secondary` first time

### Expected behavior

The file `secondary_schema.rb` exists and actual

### Actual behavior

The file `secondary_schema.rb` is absent.

### System configuration
**Rails version**: 6.0.2.2

**Ruby version**: 2.7.1

**Comment by alvir** [comment]
@eileencodes

Probably you know everything about it

**Comment by alvir** [comment]
I haven't found a quick fix for it.

**Comment by eileencodes** [comment]
This was fixed in https://github.com/rails/rails/pull/38449

**Comment by alvir** [comment]
Thanks a lot. I skipped these changes in this PR

**Comment by alvir** [comment]
@eileencodes I found fix in #38586. I had to check `master`. Sorry.
