### ISSUE TITLE
error on running rails version 5.2.4.2 using ruby version 2.2.2

### ISSUE THREAD

**Issue by designedev** [rails/rails#38972]
### Steps to reproduce
run rails console using command
rails c

### Expected behavior

rails console run successrully and shows prompt.
### Actual behavior

when run rails console, rails show error message below and stop.
`/gems/activesupport-5.2.4.2/lib/active_support/dependencies.rb:291:in require': /Users/Geralt/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/actionpack-5.2.4.2/lib/action_dispatch/request/session.rb:96: syntax error, unexpected '.'
          id&.public_id
              ^ (SyntaxError)
`

i found this problem fixed at link below : 
https://github.com/rails/rails/commit/892eab777c418135ce0646e91bc9ebb08a29ab9b#diff-0dd82841c763273551965fc0ea292a1b

but the code not fixed my local Gem location :
https://github.com/rails/rails/blob/v5.2.4.2/actionpack/lib/action_dispatch/request/session.rb

i installed rails using Gemfile like this.
`gem 'rails', '~> 5.2', '>= 5.2.4.2'`

### System configuration
**Rails version**:
5.2.4.2
**Ruby version**:
2.2.2p95

**Comment by louim** [comment]
@designedev There hasn't been a release of 5.2 since that fix was made. If you want the fix, you should get the gem from the stable branch like so:
```
gem "rails", github: "rails/rails", branch: "5-2-stable"
```

**Comment by louim** [comment]
Aditionnally, you should consider updating your version of ruby to a supported one: https://www.ruby-lang.org/en/news/2018/06/20/support-of-ruby-2-2-has-ended/
https://www.ruby-lang.org/en/downloads/

**Comment by jonathanhefner** [comment]
I think the point of confusion was that 892eab777c418135ce0646e91bc9ebb08a29ab9b was committed on 2019-12-18, and Rails 5.2.4.2 was released on 2020-03-19.  But 5.2.4.2 was just a security patch release which only included b5aeef5703dab7da9ebb47cc20e4c8b64f7f5866.  Rails 5.2.5 will be the release that includes 892eab777c418135ce0646e91bc9ebb08a29ab9b, if I'm not mistaken.
