### ISSUE TITLE
Routing helper generate wrong path with namespace exception

### ISSUE THREAD

**Issue by tjustino** [rails/rails#38973]
### Steps to reproduce
Create any scaffold:
`rails generate scaffold Movie name:string`

Edit config/routes.rb like this:
```
Rails.application.routes.draw do
  scope :admin do
    resources :movies, except: :show
  end

  resources :movies, only: :show
end
```

### Expected behavior
`movie_path` should generate the path `/movies/:id`

### Actual behavior
`movie_path` generate the path `/admin/movies/:id`

### System configuration
**Rails version**: 6.0.2.2
**Ruby version**: 2.7.1p83

**Comment by harirajv** [comment]
@tjustino could you please post the output of rake routes ?

**Comment by harirajv** [comment]
@tjustino modifying routes this way will provide expected behaviour,
```
scope :admin do
  resources :movies, except: [:show, :update, :destroy]
end
resources :movies, only: [:show, :update, :destroy]
```

**Comment by tjustino** [comment]
@harirajv routes seems good:
```
    Prefix  Verb    URI Pattern                       Controller#Action
    movies  GET     /admin/movies(.:format)           movies#index
            POST    /admin/movies(.:format)           movies#create
 new_movie  GET     /admin/movies/new(.:format)       movies#new
edit_movie  GET     /admin/movies/:id/edit(.:format)  movies#edit
     movie  PATCH   /admin/movies/:id(.:format)       movies#update
            PUT     /admin/movies/:id(.:format)       movies#update
            DELETE  /admin/movies/:id(.:format)       movies#destroy
            GET     /movies/:id(.:format)             movies#show
```
but clinking on `<%= link_to 'Show', movie %>` generate this error:
```
ActionController::RoutingError (No route matches [GET] "/admin/movies/1")
```

Your proposal works but I'm a bit confusing about this behavor.
Anyway, thanks for your workaround 🙏

**Comment by alipman88** [comment]
I'm able to replicate the behavior reported by @tjustino.

There are a few workarounds to avoid running into this. But I think the current underlying behavior (regardless of any scoping) is unexpected:

Adding `resources :movies, except: :show` creates a `movie_path` helper, despite the `except: :show` keyword.

**Comment by alipman88** [comment]
Executable test case

```ruby
# frozen_string_literal: true

require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  gem "rails", github: "rails/rails"
end

require "action_controller/railtie"

class TestApp < Rails::Application
  routes.draw do
    scope :admin do
      resources :movies, except: [:show]
    end
    
    resources :movies, only: [:show]
  end
end

require "minitest/autorun"

class BugTest < Minitest::Test
  def test_path_helper
    assert_equal Rails.application.routes.url_helpers.movie_path(1), "/movies/1"
  end
end

# Failure:
# BugTest#test_path_helper [route.rb:28]:
# Expected: "/admin/movies/1"
#   Actual: "/movies/1"
```

**Comment by alipman88** [comment]
After reading through the Rails code and documentation a little more thoroughly, I'm noting that even when `show` is excluded from a `:movies` resource's actions, a `movie_path` helper will still be created by the `udpate` and `delete` actions, as demonstrated by harirajv's solution.

@tjustino, an alternate solution might be to namespace your app's routes (using `namespace :admin` instead of `scope :admin) to avoid interference:

```ruby
Rails.application.routes.draw do
  namespace :admin do
    resources :movies, except: :show
  end

  resources :movies, only: :show
end
```

Check out this section of the docs for an example that hopefully helps clarify Rails' behavior: https://guides.rubyonrails.org/routing.html#controller-namespaces-and-routing

If that makes sense, I think this issue can be closed!

**Comment by tjustino** [comment]
Indeed, using namespace can be a better practice.
Thanks for your reply!
