### ISSUE TITLE
find_by: repeated code

### ISSUE THREAD

**Issue by foonlyboy** [rails/rails#38986]
ActiveRecord.find_by  # File activerecord/lib/active_record/relation/finder_methods.rb, line 80
ActiveRecord.find_by! # File activerecord/lib/active_record/relation/finder_methods.rb, line 86

Currently these methods are using nearly identical code,
except one uses take while the other uses take!

So the difference in behaviour of these two method
(find_by returns nil while find_by! raises)
is burried one level deeper in take vs/ take!

I suggest that find_by should be rewritten based on find_by!:
{{{
def find_by(arg, *args)
  find_by!(arg, *args)
  rescue nil
end
}}}

The same theme applies auite some other api:
see: find_or_create_by vs/ find_or_create_by!
(near duplicate code there as well)

This pertains to a lot of methods that have both,
a bang, and a non bang version.

Maybe historically the non bang versions where first,
so than later on, then bang versions were tagged on.

So we now have two versions of every api call,
with the sole difference, that one api call raises while the other one returns nil.

---

I suggest to make this easy again:

The non bang (nil returning) versions of the api calls
should be rewritten in terms of the bang (rasing excpetion) methods.
This needs to be stated in the documentation.

**Comment by rafaelfranca** [comment]
Thank you for the suggest but raising and rescuing exceptions are expensive in ruby and there is no advantage to do that in this case. 

Also this is not an issue and would be categorized as cosmetic change so please stop opening issues that don’t follow the guidelines for contributions to the framework.
