### ISSUE TITLE
Variant key makes DiskService key segmentation useless

### ISSUE THREAD

**Issue by RISCfuture** [rails/rails#38985]
Variant keys are defined at https://github.com/rails/rails/blob/master/activestorage/app/models/active_storage/variant.rb#L73

As you can see, the key always starts with `variant/`.

DiskService segmentation is done at https://github.com/rails/rails/blob/master/activestorage/lib/active_storage/service/disk_service.rb#L149

As you can see, the keys are segmented into subdirectories by the first four characters of the key. This means all variants would be stored under the path `va/ri/`, which makes for an uneven distribution of blobs within these subdirectories.

**Comment by georgeclaghorn** [comment]
I think this is fixed by variant tracking (#37901), which turns variants into ordinary blobs with random keys of their own.
