### ISSUE TITLE
NoMethodError: undefined method `match?' for #<ActiveSupport::TimeZone:0x00007ff040196008>

### ISSUE THREAD

**Issue by smondal** [rails/rails#38996]
### Steps to reproduce

Running rake task on activemodel following test cases are failing
ActiveModel::Type::DateTimeTest#test_string_to_time_with_timezone:
NoMethodError: undefined method `match?' for #<ActiveSupport::TimeZone:0x00007ff040196008>
/Users/smondal/sandip/github/ruby/rails/activemodel/lib/active_model/type/helpers/timezone.rb:10:in `is_utc?'
/Users/smondal/sandip/github/ruby/rails/activemodel/lib/active_model/type/helpers/time_value.rb:56:in `new_time

### Expected behavior

This should not show any error
### System configuration
**Rails version**:
Master branch
**Ruby version**:
ruby 2.6.5p114

**Comment by eugeneius** [comment]
`ActiveSupport::TimeZone#match?` is defined here:

https://github.com/rails/rails/blob/0fac4559e1ccbdba1be8a4457dc666b3e560de94/activesupport/lib/active_support/values/time_zone.rb#L333-L338

The error you're seeing shouldn't be possible, and I can't reproduce it. 🤔

Can you ensure that your git repo had no local changes, in particular to that file?

**Comment by smondal** [comment]
If I running following test cases on activemodel, I am see the above issue
ruby -Ilib:test activemodel/test/cases/type/date_time_test.rb 

falling on following file
https://github.com/rails/rails/blob/master/activemodel/test/cases/type/date_time_test.rb#L23

type.cast("Wed, 04 Sep 2013 03:00:00 EAT") 
*** NoMethodError Exception: undefined method `match?' for #<ActiveSupport::TimeZone:0x00007f907c8b28b0>

**Comment by eugeneius** [comment]
You're seeing that error because `ActiveSupport::TimeZone` is being loaded from an installed version of the gem, not the version from the repo. Prepending `bundle exec` will fix it.
