### ISSUE TITLE
Usage of silence_redefinition_of_method

### ISSUE THREAD

**Issue by tiendo1011** [rails/rails#39007]
Here is a portion of code inside `activesupport/lib/active_support/core_ext/class/attribute.rb`:
```
silence_redefinition_of_method def #{name} (1)
end
```
Which uses `silence_redefinition_of_method`.
Here is the definition of `silence_redefinition_of_method`:
```
  def silence_redefinition_of_method(method)
    if method_defined?(method) || private_method_defined?(method)
      alias_method method, method
    end
  end
```

It seems to me that silence_redefinition_of_method doesn't do anything, it just aliases a method to itself, so why do we need to use it in (1)?

I removed `silence_redefinition_of_method` in (1) & ran the test & it still passed.
If this is obsolete, I'd be happy to send a PR to delete it.

**Comment by kaspth** [comment]
Ruby spits out a "method redefined warning" which `silence_redefinition_of_method` silences, hence the name. It's intended.
