### ISSUE TITLE
rails console error

### ISSUE THREAD

**Issue by coopeu** [rails/rails#39004]
### Steps to reproduce
LAMP in Debian 9 installation (development and production), than can't run rails console as usual. 
The rest of rails command tasks (dbconsole, db, secrets, webpacker,...) are working fine.
This error was appearing from old versions (months ago maybe since updating to ruby 2.5.2)  
We have already tried all potential googling and github/rails proposed solutions and updating to last released ruby/rails versions without success.  

### Expected behavior
rails console working normally

### Actual behavior
$ rails c
Running via Spring preloader in process 10772
Loading development environment (Rails 6.0.2.2)
▽
(Blocking the ssh session requiring another new)
$ rails info
(ActiveRecord::AdapterNotSpecified) `resolve_connection'

### System configuration
Rails 6.0.2.2
ruby 2.7.1
RubyGems version          3.1.2
Rack version              2.2.2
rvm 1.29.10

**Comment by fxn** [comment]
Does `irb` run normally in that setup?

**Comment by coopeu** [comment]
The same error
$ irb
▽
But all the rest is working perfectly. 
Five websites in development and one in production.

**Comment by fxn** [comment]
Then, you may have to debug something in that machine. You could try other REPLs like `python` or `node` in case there is a pattern.

In any case, does not seem related to the Rails console itself.

Salutacions!
