### ISSUE TITLE
ActiveStorage direct uploads to S3 are not using public-read ACL for public buckets

### ISSUE THREAD

**Issue by mikelkew** [rails/rails#39006]
### Steps to reproduce
When configuring an Amazon S3 service with the new `public: true` option introduced in  #36729, direct uploads are not using the correct ACL and are being stored as private.

### Expected behavior
If the Amazon S3 service is configured with `public: true`, the `upload_options` (which includes the required `public-read` ACL) should be being used in the `url_for_direct_upload` method to generate the correct upload url.

To get this working, I've had to override [that method](https://github.com/rails/rails/blob/5ae3b01e971949900a1d10dc3bc8b4624150b69e/activestorage/lib/active_storage/service/s3_service.rb#L82) and pass `**upload_options` as an argument to `object_for(key).presigned_url`.

### Actual behavior
Currently in master, files uploaded to S3 with the direct upload option are not being stored with public-read access. I haven't yet tested to see if this is also a problem with other services.

### System configuration
**Rails version**: 6.1.0.alpha

**Ruby version**: 2.7.1

**Comment by peterzhu2118** [comment]
👋 Author of #36729 here! Did you [enable public access to the bucket](https://docs.aws.amazon.com/AmazonS3/latest/user-guide/block-public-access-bucket.html) as per [the docs](https://edgeguides.rubyonrails.org/active_storage_overview.html#public-access)?

**Comment by mikelkew** [comment]
Hi Peter, thanks for the quick response. Yes, the bucket has public access as shown in the screenshot below. Uploads are correctly being set as public if I don't use the direct upload feature, but private if I do.

<img width="927" alt="as_assets_test_public_access" src="https://user-images.githubusercontent.com/4648467/79942878-0ff1cb80-84ab-11ea-8c63-33a52547950f.png">

<img width="2474" alt="as_assets_test_public_access_settings" src="https://user-images.githubusercontent.com/4648467/79942963-20a24180-84ab-11ea-98f1-202c98a5a54c.png">

<img width="713" alt="as_assets_test_public_access_cors" src="https://user-images.githubusercontent.com/4648467/79942992-2730b900-84ab-11ea-9e37-1c05d6d99571.png">

**Comment by mikelkew** [comment]
Using this patch seems to get it working as expected for me though:

```ruby
module ActiveStorage
  class Service::S3Service < Service

    ## Force ACL to be passed to presigned_url for direct uploads
    def url_for_direct_upload(key, expires_in:, content_type:, content_length:, checksum:)
      instrument :url, key: key do |payload|
        generated_url = object_for(key).presigned_url :put,
                                                      expires_in: expires_in.to_i,
                                                      content_type: content_type,
                                                      content_length: content_length,
                                                      content_md5: checksum,
                                                      **upload_options

        payload[:url] = generated_url

        generated_url
      end
    end
  end
end
```

**Comment by peterzhu2118** [comment]
Yeah I think what you're suggesting makes sense. I also noticed the lack of tests for direct uploading with public services. If you'd PR it that would be great!

**Comment by mikelkew** [comment]
Sure, would be happy to. I'd like to also check the other services as part of the PR, should have some time to work on it within the next couple of days.

**Comment by mikelkew** [comment]
Just created PR #39055. Looks like it was only an issue with S3 and not the other services.

**Comment by uurcankaya** [comment]
@mikelkew  @peterzhu2118  This does not work on DigitalOcean spaces. acl value has no effect there. Not sure if it is DO bug.  Any ideas?

**Comment by astrocket** [comment]
@uurcank 

Anyone facing this issue with Digital Ocean, it's because DO requires `acl` in the request headers. [check in do community](https://www.digitalocean.com/community/questions/how-to-set-permission-of-all-files-in-a-bucket-as-public-on-every-upload)

To fix this, you can snitch the ActiveStorage's `directUploadWillStoreFileWithXHR` implementation to append extra header for acl.
Working example below.

```javascript
                const upload = new DirectUpload(file, "/rails/active_storage/direct_uploads", {
                  directUploadWillStoreFileWithXHR: (xhr) => {
                    console.log(xhr);
                    xhr.setRequestHeader('x-amz-acl', 'public-read');
                  }
                });

                upload.create((error, blob) => {
                  if (error) {
                    // Handle the error
                  } else {
                    // Add an appropriately-named hidden input to the form with a
                    //  value of blob.signed_id so that the blob ids will be
                    //  transmitted in the normal upload flow
                    console.log(blob);
                  }
                });
```

**Comment by aeadbhard** [comment]
@astrocket I am having this issue with Rails 6.0.3.2, direct upload and a Digital Ocean Spaces bucket. Direct uploads are created as private files in the bucket, even when I have this in storage.yml:

upload:
     acl: "public-read"   

I see your working example but I can't figure out what should I do to implement it in my Rails app. Is this JavaScript code just to be added to the views?

Thanks!

**Comment by astrocket** [comment]
@aeadbhard Can I see your DirectUpload javascript code?

**Comment by connorshea** [comment]
I just ran into the same issue with my Rails app 😓 

Thank you so much for the fix @astrocket 🙇

**Comment by lylo** [comment]
@astrocket is there any more information you could share about how to override ActionText to add this additional `x-amz-acl` header to direct uploads?

**Comment by astrocket** [comment]
> @astrocket is there any more information you could share about how to override ActionText to add this additional `x-amz-acl` header to direct uploads?

I am sorry I have never used ActionText with thos configuration before.

Should not be a big tweak from the above example I wrote. Try to find ActionText’s upload function.

**Comment by lylo** [comment]
> I am sorry I have never used ActionText with this configuration before.
> 
> Should not be a big tweak from the above example I wrote. Try to find ActionText’s upload function.

No worries! I opened another issue for discussion with a proposed way forward https://github.com/rails/rails/issues/41070

**Comment by current-username** [comment]
Hello everybody, I am still facing the same issue.

System configuration
```
$ rails about
About your application's environment
Rails version             6.1.3.1
Ruby version              ruby 3.0.0p0 (2020-12-25 revision 95aff21468) [x86_64-linux]
RubyGems version          3.2.3
Rack version              2.2.3
```

```
# /myapp/config/storage.yml
digitalocean_dev:
  service: S3
  access_key_id: <%= Rails.application.credentials.dig(:spaces, :access_key_id) %>
  secret_access_key: <%= Rails.application.credentials.dig(:spaces, :secret_access_key) %>
  endpoint: https://___.digitaloceanspaces.com
  region: ___
  bucket: ___-development
  public: true
```

Thanks to @astrocket , I almost solve my problem by adding this lines :

```
// /myapp/app/javascript/packs/direct_upload.js

import { DirectUpload } from "@rails/activestorage"

addEventListener("direct-upload:initialize", event => {
  // uploaded with the correct header. Otherwise they will end up being
  // private files.
  const upload = new DirectUpload(file, "/rails/active_storage/direct_uploads", {
    directUploadWillStoreFileWithXHR: (xhr) => {
      xhr.setRequestHeader('x-amz-acl', 'public-read');
    }
  });
})

```
Results:
I have now two files uploaded to my bucket.
The file managed by ActiveStorage is private.
The file managed by new DirectUpload (js) is public.

My questions:
How can I avoid uploading twice the same file and make public the file uploaded public ?
Is there a way to avoid that "patch" and directly solve the problem in ActiveStorage ?
