### ISSUE TITLE
Parallel tests crashes when using Minitest::Spec::DSL

### ISSUE THREAD

**Issue by Pungsnigel** [rails/rails#39021]
Tests seem to crash when using parallel tests in combination with Minitest spec syntax. Disabling parallelize call is enough to make test suite run successfully.

### Steps to reproduce
* Init new rails project
* require 'minitest/spec' from test_helper.rb
* Write some test case using Minitest::Spec::DSL syntax
* Make sure parallelize is called from test_helper

[Example app](https://github.com/Pungsnigel/parallel_test_bug) - Note that disabling parallelize makes tests run successfully.

### Expected behavior
Tests should successfully run

### Actual behavior
Tests crashes with "DRb::DRbServerNotFoundDRb::DRbServerNotFound ( (DRb::DRbConnErrorDRb::DRbConnError))"

### System configuration
**Rails version**: 6.0.2.2

**Ruby version**: 2.6.2

**Comment by abhaynikam** [comment]
I think this is similar to issue #38342

**Comment by hahmed** [comment]
I had a look into this issue and it seems to have originated from this commit https://github.com/rails/rails/commit/758ba117a008b6ea2d3b92c53b6a7a8d7ccbca69

The method `with_info_handler` seems to be the issue for spec based tests. Not been able to figure out why, not sure if its related to minispec or rails.

```
# does not work
result = klass.with_info_handler reporter do
  Minitest.run_one_method(klass, method)
end

# works
result = Minitest.run_one_method(klass, method)
```

I also had a look into #38342 and I think these are both different issues.

**Comment by hahmed** [comment]
Actually, it looks like the fix I mentioned above will work for both of the issues...

**Comment by KapilSachdev** [comment]
A minimal reproduction script.

```ruby
# frozen_string_literal: true

require 'bundler/inline'

gemfile(true) do
  source 'https://rubygems.org'

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  gem 'rails', github: 'rails/rails'
  # gem 'minitest-parallel_fork'
end

require 'minitest/autorun'

class DRbServerNotFoundTest < ActiveSupport::TestCase
  extend Minitest::Spec::DSL
  parallelize(workers: 2)
  # parallelize(workers: 2, with: :threads)

  describe 'DRbServerNotFound' do
    it 'should run' do
    end
  end
end
```

Looks like a marshalling issue.

**Comment by KapilSachdev** [comment]
/cc @eileencodes How can this be resolved?

```ruby
result = klass.with_info_handler reporter do
  Minitest.run_one_method(klass, method)
end
```

**Comment by hahmed** [comment]
To me this looks like it's related to https://github.com/seattlerb/minitest/pull/716

**Comment by KapilSachdev** [comment]
I think they are unrelated, but will try to verify if it can solve the issue reported here.

**Comment by jensljungblad** [comment]
Also running into this.. Did anyone get it to work?

**Comment by pkoch** [comment]
Still running into this. My repro is very similar to @KapilSachdev's:
```ruby
require 'bundler/inline'

gemfile(true) do
  source 'https://rubygems.org'

  gem 'rails'
end

require 'minitest/autorun'

class DRbServerNotFoundTest < ActiveSupport::TestCase
  extend Minitest::Spec::DSL
  parallelize

  describe 'DRbServerNotFound' do
    (ActiveSupport.test_parallelization_threshold + 1).times do |i|
      it i.to_s do
        assert true
      end
    end
  end
end
```

@hahmed's [fix](https://github.com/rails/rails/issues/39021#issuecomment-622482804) also works for me. I do, however, see a warning:
```
Minitest::Runnable#marshal_dump is deprecated. You might be violating internals. From /home/pkoch/.rbenv/versions/3.2.2/lib/ruby/3.2.0/drb/drb.rb:571:in `dump'
```
