### ISSUE TITLE
Allow column_name:type:unique as an alias for column_name:type:uniq

### ISSUE THREAD

**Issue by anhari** [rails/rails#39025]
### Steps to reproduce

Run the following in a new Rails app

```
bin/rails generate model article title:string:unique
```

### Expected behavior
Generates a column with a unique index:

``` ruby
class CreateArticles < ActiveRecord::Migration[6.0]
  def change
    create_table :articles do |t|
      t.string :title

      t.timestamps
    end
    add_index :articles, :title, unique: true
  end
end
```

### Actual behavior

Generates a column without a unique index:

``` ruby
class CreateArticles < ActiveRecord::Migration[6.0]
  def change
    create_table :articles do |t|
      t.string :title

      t.timestamps
    end
  end
end
```

### System configuration
**Rails version**: 2.6.5p114

**Ruby version**: 6.0.2.2

**Comment by dainmiller** [comment]
I'd be down to take this one on. I think this could be the beginning of extending the `rails g` generators to have some awesome config extensions.
