### ISSUE TITLE
"Stack level too deep" when `inject`ing a lot of activerecord relations via `#or`

### ISSUE THREAD

**Issue by trushkevich** [rails/rails#39032]
### Steps to reproduce
execute a file in the following gist https://gist.github.com/trushkevich/9d8cdc3c7466e7bc793ae7075534db4f
```ruby
ruby inject_or_stack_level_too_deep.rb
```
### Expected behavior
`test_ok` passes
`test_parser_stack_overflow` passes
`test_stack_level_too_deep` passes

### Actual behavior
`test_ok` passes
`test_parser_stack_overflow` fails
`test_stack_level_too_deep` fails

### System configuration
**Rails version**:
5.2.3, 6.1.0.alpha

**Ruby version**:
2.4.1, 2.6.3

**Comment by jonathanhefner** [comment]
Related: #34776
