### ISSUE TITLE
Module.parent: NoMethodError for String#squish

### ISSUE THREAD

**Issue by sshaw** [rails/rails#39042]
Deprecation warning uses it. It lives in `active_support/core_ext/string/filters.rb` but it's never required. 

### Steps to reproduce

```
~/code/ruby/class2 >ruby -ractive_support/version -e'p ActiveSupport.version'
#<Gem::Version "6.0.2.2">
```
---
```
~/code/ruby/class2 >ruby -ractive_support/core_ext/module -e'Module.new.parent_name'
Traceback (most recent call last):
	1: from -e:1:in `<main>'
/Users/sshaw/.rvm/gems/ruby-2.5.2/gems/activesupport-6.0.2.2/lib/active_support/core_ext/module/introspection.rb:20:in `parent_name': undefined method `squish' for #<String:0x00007fbd819c8510> (NoMethodError)
```

### Expected behavior

Deprication warning

### Actual behavior

`NoMethodError`

### System configuration
**Rails version**: NA

**Ruby version**: 2.5.2

**Comment by sshaw** [comment]
This applies to `Module.parent` and `Module.parent_name`

**Comment by fxn** [comment]
Thanks!
