### ISSUE TITLE
Ayuda! Problema para agregar un segundo modelo /Ruby on Rails

### ISSUE THREAD

**Issue by JIMMYMONTOYA** [rails/rails#39054]
Hola a todos tengo problema para crear mi primera aplicación, partí siguiendo las indicaciones en el siguiente enlace:
https://guides.rubyonrails.org/getting_started.html

Todo estaba bien hasta que llegue al punto 6
(6 Adding a Second Model) - 6 Agregar un segundo modelo

Si pueden apoyarme a solucionar este inconveniente.

![image](https://user-images.githubusercontent.com/43454901/80296371-0df46a80-8740-11ea-9957-d2a8e614246b.png)

**Comment by redencion** [comment]
Hola @JIMMYMONTOYA  saludos! 
Según veo en el punto 6 debes realizar primero migraciones y luego establecer relaciones entre ambos modelos article y comment. ¿Ya lo hiciste?

**Comment by JIMMYMONTOYA** [comment]
¡Lo conseguí..!
Gracias por tu ayuda.
Saludos
