### ISSUE TITLE
AR#first is inconsistent

### ISSUE THREAD

**Issue by phuongnd08** [rails/rails#39061]
### Steps to reproduce

```
collection = User.where(condition)
collection.length
collection.first
```

### Expected behavior
AR#first always return the resource with lowest id

### Actual behavior
AR#first returns `@records[0]` if the collection is preloaded, but sort the collection by id then take the first element if the collection is not loaded. 

### System configuration
**Rails version**: 4.2.10 (but I find rails 5 and 6 have same issue

**Ruby version**: 2.5.

### My proposal:
We should not magically sort `first` to keep its behavior consistently `inconsistent`.
User who really need `first` to be consistent should `sort` their relation. AR may provide default scope `id_asc` (which is `order(id: :asc)`) for those who need .first to return the record with lowest id.

**Comment by phuongnd08** [comment]
I wrote a gem [id_asc](https://github.com/phuongnd08/id_asc) as a temporary aid for this issue.

**Comment by dallasgoldswain** [comment]
I tried this as for me couldnt reproduce, here is a snippet from the console
```
irb(main):020:0> collection = User.where("created_at > '2020-04-30'")
  User Load (0.4ms)  SELECT "users".* FROM "users" WHERE (created_at > '2020-04-30') LIMIT $1  [["LIMIT", 11]]
=> #<ActiveRecord::Relation [#<User id: 1, name: "Elvina Pfannerstill",......
```
and then
```
irb(main):021:0> collection.length
  User Load (1.2ms)  SELECT "users".* FROM "users" WHERE (created_at > '2020-04-30')
=> 100
irb(main):022:0> collection.first
=> #<User id: 1, name: "Elvina Pfannerstill",.....
```

I am new to all this but I always get ID 1, Rails 6.0.2.2, Ruby 2.65.
If i am missing something I am happy to learn.

**Comment by rafaelfranca** [comment]
`first` will order by the id if the collection is not loaded. If you want the unordered version use `take`.

**Comment by phuongnd08** [comment]
@rafaelfranca `first` will order by the id if the collection is not loaded. But `first` will not do it if the collection is loaded. This is what programmer called inconsistency I think.

**Comment by phuongnd08** [comment]
@dallasgoldswain Postgres may return records without respecting `id` order. It doesn't happen all the time - that's why it's hard to notice and you will be pulling your hair out when it happens.
