### ISSUE TITLE
Plus operator turns an ActiveSupport::Duration into an Integer

### ISSUE THREAD

**Issue by RKushnir** [rails/rails#39079]
### Motivation

Yesterday I spent some time debugging a test that fails during the daylight saving time change. The important part of the setup looks like this:
```ruby
create_shipment(delivery_time_offset: - 1.day  + 2.hours)
create_shipment(delivery_time_offset: + 5.days + 30.minutes)
```

I took my DeLorean back to the end of October 2019 and started debugging. I was puzzled because when I tried `Time.current + 5.days + 30.minutes` it was giving me time 14:30, which was expected. But somehow the shipment was being created with 13:30. What is going on?!

Finally, I was able to figure out that problem is in the space in `+ 5.days`. Someone wanted to make a nice alignment, so they added a plus and a space to match the alignment of other lines. Adding a plus is safe, it doesn't change anything. Or does it?

```ruby
> 5.days
=> 5 days

> +5.days
=> 5 days

> + 5.days
=> 432000
```

For some reason the last value is displayed differently, but that's probably a quirk of the console. It shows that 5 days is 432000 seconds, which is true.

Except that twice a year 5 days can be 435600 seconds or 428400 seconds. And then the test suddenly fails.

Curious that this doesn't happen with minus, because the `-@` operator is oveloaded for `ActiveSupport::Duration`. So I think we should do the same with the `+@`.

### Steps to reproduce
Test:
```ruby
assert_equal(
  Time.zone.local(2019, 10, 26, 4) + 1.day,
  Time.zone.local(2019, 10, 26, 4) + (+ 1.day)
)
```

### Expected behavior
`+5.days` and `+ 5.days` should produce the same value.

### Actual behavior
`+5.days` is an `ActiveSupport::Duration`, `+ 5.days` is an `Integer`.

### System configuration
**Rails version**: 6.0.2.2

**Ruby version**: 2.6.5p114 (2019-10-01 revision 67812) [x86_64-darwin18]

**Comment by eugeneius** [comment]
Thanks for the detailed and clear bug report!

> So I think we should do the same with the `+@`.

I agree. Since you've already done most of the work, are you interested in opening a pull request?

**Comment by RKushnir** [comment]
@eugeneius Done. Please, have a look when you have a moment.
