### ISSUE TITLE
Rails Warning: Creating scope :<scope_name>. Overwriting existing method <model_name>.<scope_name>

### ISSUE THREAD

**Issue by cerenaracli** [rails/rails#39078]
**Steps to reproduce**
We have a model called Brochure, which has an published scope:
  scope :published, -> { where(status: Brochure.statuses[:published]) }

When we start our app, we are seeing the following console warning:
   Creating scope :published. Overwriting existing method Brochure.published.

We upgraded our rails version from 4.2.10 to 5.0.7 and our gemfile list. Gem(audited-activerecord) we used before is not used with rails 5.0.7 but 'audited' is used so we changed it.
In our project this gem and Brochure model are connected with each other.

What are your thoughts on this warning?

Thank you very much!!!

**System configuration**
**Rails version**: 5.0.7

**Ruby version**: 2.4.0

**Comment by simi** [comment]
It seems you're using `enum` and that scope already exist (is created by `enum` in the background). Check `enum` [docs](https://api.rubyonrails.org/classes/ActiveRecord/Enum.html).
