### ISSUE TITLE
Missing deep_transform_keys for ActionController::Parameters 

### ISSUE THREAD

**Issue by sloneorzeszki** [rails/rails#39081]
### Steps to reproduce
Use `params.deep_transform_keys(&:underscore)` anywhere in a controller.

Not sure if this qualifies as an issue, but the method (along with `deep_transform_keys!`) was implemented almost a year ago (https://github.com/rails/rails/pull/36294), but is not available on the latest stable releases, only `master`.

### Expected behavior
To find the method and transform the keys.

### Actual behavior
```
NoMethodError:
       undefined method `deep_transform_keys!' for #<ActionController::Parameters:0x00005556f3268f78>
```

### System configuration
**Rails version**: 6.0.2.2

**Ruby version**: 2.6.5

**Comment by kaspth** [comment]
It’ll be in Rails 6.1, we consider it a feature so we won’t backport it. Thanks

**Comment by peterfebin** [comment]
> ### Steps to reproduce
> Use `params.deep_transform_keys(&:underscore)` anywhere in a controller.
> 
> Not sure if this qualifies as an issue, but the method (along with `deep_transform_keys!`) was implemented almost a year ago (#36294), but is not available on the latest stable releases, only `master`.
> 
> ### Expected behavior
> To find the method and transform the keys.
> 
> ### Actual behavior
> ```
> NoMethodError:
>        undefined method `deep_transform_keys!' for #<ActionController::Parameters:0x00005556f3268f78>
> ```
> 
> ### System configuration
> **Rails version**: 6.0.2.2
> 
> **Ruby version**: 2.6.5

How about `params.as_json.deep_transform_keys(&:underscore)` ?

**Comment by sylvain-farnault** [comment]
Waiting for 6.1 Rails gem, what should we do to go through this error?

**Comment by kaspth** [comment]
Use Rails 6.1.rc1, and help test if there's any issues.
