### ISSUE TITLE
Getting started guide(6.0.2.2): app/ content - Javascript folder is missing in documentation

### ISSUE THREAD

**Issue by jhadeepakkumar14** [rails/rails#39085]
### Steps to reproduce

![Screenshot 2020-04-30 at 12 16 15 AM](https://user-images.githubusercontent.com/3532367/80634281-d7885980-8a77-11ea-8672-1c72bc70cd3f.png)

### Expected behavior

Contains the controllers, models, views, helpers, mailers, channels, javascript, jobs, and assets for your application. You'll focus on this folder for the remainder of this guide.

Note: **Javascript folder need to be added in the folder list.**
### Actual behavior

Contains the controllers, models, views, helpers, mailers, channels, jobs, and assets for your application. You'll focus on this folder for the remainder of this guide.

Note: **Javascript folder is missing here**
### System configuration
**Rails version**: 6.0.2.2

**Ruby version**:

Note: **This is very small issue but it can confuse new comers who just started learning rails**

**Comment by Baron-burton** [comment]
This must have been overlooked seeing as the javascript folder was previously included under `assets/`. 

If I think back to being a new developer, I'd definitely like the docs to be as explicit as possible just so I know what to expect. 

If it's worth anything, I agree with the suggested change.

**Comment by Baron-burton** [comment]
@jhadeepakkumar14, I forgot to mention, you should submit a PR to fix the issue. You can check out how to do that using the [Rails guide on contributing to documentation](https://edgeguides.rubyonrails.org/contributing_to_ruby_on_rails.html#contributing-to-the-rails-documentation)
