### ISSUE TITLE
wrong resource generated in rails scaffold

### ISSUE THREAD

**Issue by prdk0** [rails/rails#39093]
when scaffold command ran for generating person resource, it generated people resource instead of person.

![Screenshot at 2020-04-30 16-04-31](https://user-images.githubusercontent.com/1553889/80723644-841d1680-8b1e-11ea-9e27-10118c9d11d7.png)

### Steps to reproduce
`rails generate scaffold person`

### Expected behavior
It should generate person resource.

### Actual behavior
generated people resource.

### System configuration
**Rails version**:  6.0.2.1

**Ruby version**: 2.6.3p62

**Comment by eileencodes** [comment]
Hey @prdk0 this isn't a bug, this is intended behavior. Rails pluralizes the model for controllers and resource routes.

**Comment by prdk0** [comment]
> Hey @prdk0 this isn't a bug, this is intended behavior. Rails pluralizes the model for controllers and resource routes.

**All right. Thanks for the clarification.**
