### ISSUE TITLE
request.remote_ip does not consider X-Forwarded-For IPs if they have port numbers attached

### ISSUE THREAD

**Issue by duncanjbrown** [rails/rails#39092]
`request.remote_ip` does not consider IPs in the `X-Forwarded-For` header if the IPs have port numbers attached. It isn't common practice to attach a port number to `X-Forwarded-For` IPs but some platforms do, for example Microsoft Azure’s App Service.

I believe the `ips_from` method in `ActionDispatch::RemoteIp::GetIp` is filtering out the IPs with ports because `IPAddr.new` will reject them.

https://github.com/rails/rails/blob/8544c9c23687964ab754c06a7745215a5369a4e0/actionpack/lib/action_dispatch/middleware/remote_ip.rb#L160-L172

`rack` decided to have `Rack::Request` strip ports from IPs in this position (https://github.com/rack/rack/pull/1251) but `ActionDispatch::Request`, which `GetIp` depends on, doesn't do that. Should it?

### Steps to reproduce

Make a request to the application with an `X-Forwarded-For` header including the port number in the IP address.

```ruby
# frozen_string_literal: true

require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  # Activate the gem you are reporting the issue against.
  gem "rails", "6.0.2.2"
end

require "rack/test"
require "action_controller/railtie"

class TestApp < Rails::Application
  config.root = __dir__
  config.hosts << "example.org"
  config.session_store :cookie_store, key: "cookie_store_key"
  secrets.secret_key_base = "secret_key_base"

  config.logger = Logger.new($stdout)
  Rails.logger  = config.logger

  routes.draw do
    get "/" => "test#index"
  end
end

class TestController < ActionController::Base
  include Rails.application.routes.url_helpers

  def index
    render plain: request.remote_ip
  end
end

require "minitest/autorun"

class BugTest < Minitest::Test
  include Rack::Test::Methods

  def test_returns_x_forwarded_for_without_port
    header 'X-Forwarded-For', '1.2.3.4'

    get "/"

    assert_equal '1.2.3.4', last_response.body
  end

  def test_returns_x_forwarded_for_with_port
    header 'X-Forwarded-For', '1.2.3.4:123'

    get "/"

    refute_equal '1.2.3.4', last_response.body
  end

  private
    def app
      Rails.application
    end
end
```

### Expected behavior
`request.remote_ip` should return the port-less IP from the X-Forwarded-For header.

### Actual behavior
`request.remote_ip` does not return the IP from the X-Forwarded-For header.

### System configuration
**Rails version**: `6.0.2.2`

**Ruby version**: `ruby 2.6.6p146 (2020-03-31 revision 67876) [x86_64-darwin18]`

**Comment by sagium** [comment]
@duncanjbrown Since `X-Forwarded-For` is not standard in any way, I think keeping the basic behavior would be the best. You can always override the method for specific usage but as seen here

https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-Forwarded-For
https://docs.aws.amazon.com/elasticloadbalancing/latest/classic/x-forwarded-headers.html

`X-Forwarded-For` is reserved for IPv4 and IPv6 and
`X-Forwarded-Port` is where we could expect on some cases the port.

Another concern is the performance penalty on running regexes or string comparisons on every incoming request. We could filter out a lot of garbage from many headers but this will slow down the app.

**Comment by duncanjbrown** [comment]
@sagium, thank you very much! 

As I understand [the decision to clean up this header in Rack](https://github.com/rack/rack/pull/1251), the argument there was that RFC 7293 — which ?seems to be the closest we get to a standard for `X-Forwarded-For` — [says that a port on the end of the IP is admissable](https://tools.ietf.org/html/rfc7239#section-6). A _well-intentioned_ proxy (like Azure's, presumably) may decide to attach a port to an IPv4 in this header with a reasonable expectation that downstream services will be able to consume it.

**Comment by sagium** [comment]
@duncanjbrown I did a git blame to `rack/request.rb` to see the progress on this.

Maybe the following method is what you are looking for
https://github.com/rack/rack/blob/master/lib/rack/request.rb#L330-L336

Try this in your controller and you should get something similar.

```
$ curl --header "X-Forwarded-For: 192.168.0.2,192.168.1.4:2343" localhost:3000

----  on debugger ----

0> request.forwarded_for
=> ["192.168.0.2", "192.168.1.4"]

0> request.x_forwarded_for
=> "192.168.0.2,192.168.1.4:2343"
```

The above run with

```
rack (2.2.2)
rails (6.0.2.2)
ruby 2.7.1p83 (2020-03-31 revision a0c7c23c9c) [x86_64-linux]
```

**Comment by sagium** [comment]
If you want to make a PR for the `remote_ip` method, I think you can do something here 

https://github.com/rails/rails/blob/4c724df058aea8e972707677cd9e917e9ac88fb3/actionpack/lib/action_dispatch/middleware/remote_ip.rb#L112-L118

@tenderlove used the `x_forwarded_for` string back in 2015, I don't know the reason for that choice, maybe Rack didn't provide those helper methods back then.

**The regex is already done on the Rack level so we might actually gain some speed here!!**

Beware `@req.forwarded_for` returns `Array` or `NilClass` (not an empty array)

```
      def calculate_ip
        # Set by the Rack web server, this is a single value.
        remote_addr = ips_from(@req.remote_addr).last

        # Could be a CSV list and/or repeated headers that were concatenated.
        client_ips = ips_from(@req.client_ip).reverse

        # @req.forwarded_for is pre-filtered by the Rack web server
        forwarded_ips = validated_ips(@req.forwarded_for).reverse
         ...
    
    private
      def ips_from(header) # :doc:
        return [] unless header
        # Split the comma-separated list into an array of strings.
        ips = header.strip.split(/[,\s]+/)
        validated_ips(ips)
      end

      def validated_ips(addresses)
        return [] unless addresses

        addresses.select do |ip|
          # Only return IPs that are valid according to the IPAddr#new method.
          range = IPAddr.new(ip).to_range
          # We want to make sure nobody is sneaking a netmask in.
          range.begin == range.end
        rescue ArgumentError
          nil
        end
      end
```

**Comment by duncanjbrown** [comment]
Thank you @sagium — I'll open a PR shortly :+1:.

**Comment by sagium** [comment]
You are welcome @duncanjbrown 

And a small test here `rails/railties/test/application/middleware/remote_ip_test.rb` could be one like that

```
test "remote_ip works with HTTP_X_FORWARDED_FOR with optional ports inside the header" do
  make_basic_app
  assert_equal "4.2.42.42", remote_ip("REMOTE_ADDR" => "1.1.1.1", "HTTP_X_FORWARDED_FOR" => "4.2.42.42:4567")
  assert_equal "5.2.42.41", remote_ip("REMOTE_ADDR" => "1.1.1.1", "HTTP_X_FORWARDED_FOR" => "4.2.42.42:4567, 5.2.42.41:4467")
end
```

**Comment by sagium** [comment]
I take back my comment about better performance.. :disappointed: 

Turns out they don't memoize the `forwarded_for()` result used in `ip()` on `Rack::Request`, https://github.com/rack/rack/blob/f9ad97fd69a6b3616d0a99e6bedcfb9de2f81f6c/lib/rack/request.rb#L362

But even if they did, the `Rack::Request` `ip()` method is not called on `ActionDispatch::RemoteIp` so `forwarded_for()` will have to run and calculate the regex.
https://github.com/rack/rack/blob/f9ad97fd69a6b3616d0a99e6bedcfb9de2f81f6c/lib/rack/request.rb#L330-L336

---

So, the performance penalty is there. The question is do we need to rely on `Rack::Request` for every header filtering decisions etc?

My answer would be yes, why replicate behavior already implemented on the included class `Rack::Request::Helpers`?
