### ISSUE TITLE
ActiveStorage::FileNotFoundError in AnalyzeJob due to enqueue-before-upload

### ISSUE THREAD

**Issue by andrewhamon** [rails/rails#39107]
We started using ActiveStorage in production recently and immediately started getting a large volume of FileNotFound errors in Analyze jobs. We are not using direct-to-S3 uploads, we are sending the files to our rails controller.

I noticed in a rails console, when attaching an IO directly and saving, the AnalyzeJob is enqueued before the file is uploaded:

This would explain the errors. Latency in our sidekiq queue is usually quite low, so I suspect the issue is that the analysis job runs before the image is fully uploaded. From what I can tell, the jobs usually succeed on retry.

### Steps to reproduce

- directly attach an io
- save
- observe that enqueue occurs before the upload is complete

![image](https://user-images.githubusercontent.com/5134584/80838952-03f2c180-8baf-11ea-96e6-daec0ff2ca32.png)

### Expected behavior
Analyze job shouldn't be enqueued until the upload is complete. 

### Actual behavior
Analyze job is enqueued before the upload is complete

### System configuration
**Rails version**: 6.0.2.2

**Ruby version**: 2.6.2

**Comment by georgeclaghorn** [comment]
I couldn’t reproduce this in [a fresh app](https://github.com/georgeclaghorn/rails-issue-39107). The `ActiveStorage::AnalyzeJob` is correctly enqueued after the blob is uploaded:

```
   (1.4ms)  commit transaction
  ↳ app/controllers/people_controller.rb:30:in `block in create'
  Disk Storage (5.6ms) Uploaded file to key: p0i5b9tqv30s10ptt2g6h7mjit5m (checksum: wI+kt3K2vhQkYl8Mum3jHw==)
[ActiveJob] Enqueued ActiveStorage::AnalyzeJob (Job ID: e0432842-bf66-4feb-9534-a52f207aabea) to Async(active_storage_analysis) with arguments: #<GlobalID:0x00007f9002857c50 @uri=#<URI::GID gid://sandbox/ActiveStorage::Blob/1>>
```

Can you please share a minimal sample app that demonstrates the issue?

**Comment by teekaytech** [comment]
Hi, @andrewhamon I'm having this exact challenge. I will be glad if you can guide me through how you later fixed this issue.
Thanks.

**Comment by carlos-ssh** [comment]
> Hi, @andrewhamon I'm having this exact challenge. I will be glad if you can guide me through how you later fixed this issue. Thanks.

Did you solve it?.

**Comment by teekaytech** [comment]
> > Hi, @andrewhamon I'm having this exact challenge. I will be glad if you can guide me through how you later fixed this issue. Thanks.
> 
> Did you solve it?.

Not yet.

**Comment by jon-sully** [comment]
Rails 7.0.2.2, Ruby 2.7.4

I believe I'm seeing this as well. Just getting our app onto Active Storage and seeing what feels like an out-of-order'ness on the Analyze job. Upon switching to direct upload via the rails npm package things are in the correct order, but without using direct uploads I'm getting the FileNotFoundError and the job appears to be queueing before the upload is complete. I actually am on decently delayed internet so it could very well be a race thing, but here are pertinent logs..

```
20:41:11 log.1            |   ActiveStorage::Blob Create (2.3ms)  INSERT INTO `active_storage_blobs` (`key`, `filen... etc
...
20:41:11 log.1            |   ActiveStorage::Attachment Create (1.1ms)  INSERT INTO `active_storage_attachments` (`name`, `record...etc
...
20:41:11 log.1            | [ActiveJob] Enqueued ActiveStorage::AnalyzeJob (Job ID: a9644203-3...etc
...
(job errors, also at 20:41:11)
...
...
20:41:15 log.1            |   S3 Storage (4595.6ms) Uploaded file to key: fnkllypvg...etc
```

My connection isn't _that_ bad 😅 surprised it's taking 4+ seconds to upload.. but regardless I'm not sure why the job is being queued before the file is actually uploaded. 

I saw another issue mention it (though that issue now eludes me) so FWIW this does happen regardless of `:inline` or `:sidekiq` queue adapters.

**Comment by jon-sully** [comment]
Ah, the other issue I was referencing was #42003. Notably @brenogazzola's notes:

> Yeah, this is out of order. It should be create blob, upload file, create attachment.

I started looking into the Rails code for ActiveStorage but have yet to make a lot of headway. TBD for my own efforts 😆

**Comment by teekaytech** [comment]
I was able to fix this issue. For me, the problem is as a result of one of the queries in my PGSearch configuration. I don't really know why, but it looks like the said query keeps disrupting the background job. You might want to check other methods in your model and see if any of them uses sidekiq for background job processing. I hope this helps someone :wink:

**Comment by charlie-prezzano** [comment]
Rails 7.0.2.3, Ruby 3.0.3

I have the same issue, and stuck. If I find an answer I'll post here.

**Comment by CringeDeveloper** [comment]
I don't know is it correct way but it fix error.
We can monkey patch analyze_later and switch it to analyze and it should work

  module ActiveStorage::Blob::Analyzable
    def analyze_later
      analyze
    end
  end

**Comment by brenogazzola** [comment]
Notice for all those who are integrating Active Storage into other front end libs, like react/vue: This error might be caused if your frontend code is submitting the form without waiting for the upload to complete.

@jon-sully You said your file upload takes 4 seconds, but from your logs the blob and the attachment are created in less than 1 second. This means that whatever is happening in your frontend is probably not waiting for the upload to complete
