### ISSUE TITLE
Action Cable not working in Safari on IOS

### ISSUE THREAD

**Issue by speamy** [rails/rails#39104]
I want to exchange information about action cable in Ruby on Rails 6.0.2.

*On my desktop this also works great.*

But unfortunately in Safari on my IPhone and IPad (IOS 13.4) the connection to the websocket is not established. 

Neither the 'connected' nor the 'received' function is called.  I have no errors or infos in the Developer Tools console of Safari on my IPhone (connected via cable).

### Steps to reproduce

I have all relevant files here again, they are mostly standard generated by rails.

**app/javascript/channels/test_channel.js**
```js
import consumer from "./consumer"
consumer.subscriptions.create("TestChannel", {
  connected() {
    console.log("connected")
  },

  disconnected() {
    console.log("disconnected")
  },

  received(data) {
    console.log("received")
  }
});
```

**app/javascript/channels/consumer.js**
```js
import { createConsumer } from "@rails/actioncable"

export default createConsumer()
```

**app/javascript/channels/index.js**
```js
const channels = require.context('.', true, /_channel\.js$/)
channels.keys().forEach(channels)
```

**app/javascript/channels/index.js**
```js
const channels = require.context('.', true, /_channel\.js$/)
channels.keys().forEach(channels)
```

**app/javascript/packs/application.js** 
```js
require("@rails/ujs").start()
require("turbolinks").start()
require("@rails/activestorage").start()
require("channels")
```

**package.json**
```json
{
  "name": "...",
  "private": true,
  "dependencies": {
    "@rails/actioncable": "^6.0.0",
    "@rails/activestorage": "^6.0.0",
    "@rails/ujs": "^6.0.0",
    "@rails/webpacker": "4.2.2",
    "turbolinks": "^5.2.0"
  },
  "version": "0.1.0",
  "devDependencies": {
    "webpack-dev-server": "^3.10.3"
  }
}
```

**app/channels/test_channel.rb**
```ruby
class TestChannel < ApplicationCable::Channel
  def subscribed
    stream_from "some_channel"
  end

  def unsubscribed
    # Any cleanup needed when channel is unsubscribed
  end
end
```
**ngnix Config**   (It does not work locally in development either)
```
....

location /cable {
  passenger_app_group_name test_app_action_cable;
  passenger_force_max_concurrent_requests_per_process 0;
}

```

### System configuration
**Rails version**: 6.0.2

**Ruby version**: 2.6.5

**Comment by georgeclaghorn** [comment]
I can’t reproduce this. I created a fresh Rails 6.0.2 app with `rails new sandbox` and added the following:

```ruby
# config/routes.rb
Rails.application.routes.draw do
  root to: "root#show"
end
```

```ruby
# app/controllers/root_controller.rb
class RootController < ApplicationController
  def show
  end
end
```

```erb
<%# app/views/root/show.html.erb %>
Hello, world!
```

```ruby
# app/channels/test_channel.rb
class TestChannel < ApplicationCable::Channel
end
```

```js
// app/javascript/channels/test_channel.js
import consumer from "./consumer"

consumer.subscriptions.create("TestChannel", {
  connected() {
    alert("Connected")
  },

  disconnected() {
    alert("Disconnected")
  },

  received(data) {
    alert("Received")
  }
})
```

```ruby
config/environments/development.rb
config.hosts << "#{my_local_ip_address}.xip.io"
```

I started Puma with `rails s -b 0.0.0.0` and loaded the app on my phone via [xip.io](http://xip.io). The “Connected” alert appeared as expected:

<img src="https://user-images.githubusercontent.com/94129/80869665-b7bb8600-8c6f-11ea-883c-ab69e8bf7e30.PNG" height="400">

The Puma logs indicated that Safari on my phone had connected via WebSocket:

```
Started GET "/cable/" [WebSocket] for 192.168.0.131 at 2020-05-02 12:17:12 -0400
Successfully upgraded to WebSocket (REQUEST_METHOD: GET, HTTP_CONNECTION: Upgrade, HTTP_UPGRADE: websocket)
TestChannel is transmitting the subscription confirmation
```

Do you have any other JS dependencies that could be interfering? Can you share a complete (but minimal) sample app that demonstrates the issue for you?

**Comment by speamy** [comment]
Ok, es war mein Fehler. In mein Safari war unter den den Experimental Features 'NSURLSession WebSocket' angewählt. Nach dem ich dies ausgemacht habe, hat es funktioniert. Die Option findet man unter:

**Launch Settings > Scroll down to find Safari, and tap it. >  Scroll down to click the Advance option. Then you will see the Experimental Features > Tap it**

![IMG_18DA4CCF411E-1](https://user-images.githubusercontent.com/3890561/80909122-09bee300-8d26-11ea-903d-9b07d81acf62.png)
