### ISSUE TITLE
`render_to_string` from Rails 5.2 to Rails 6 breaking change

### ISSUE THREAD

**Issue by pedrofs** [rails/rails#39118]
### Steps to reproduce
# On Rails 6
```bash
$ rails new test_app
$ cd test_app
$ echo "<%= foo =>" > test.html.erb
$ rails c
irb(main) > ActionController::Base.render(file: Rails.root.join('test.html.erb'), locals: { foo: 'bar' })
=> "<%= foo %>"
```

### Expected behavior (As for rails 5.2)
```base
irb(main) > ActionController::Base.render(file: Rails.root.join('test.html.erb'), locals: { foo: 'bar' })
=> "bar"
```

### Actual behavior
```base
irb(main) > ActionController::Base.render(file: Rails.root.join('test.html.erb'), locals: { foo: 'bar' })
=> "<%= foo %>"
```

Looking at the code it looks like the `file` options on Rails 6 uses a new `Template::RawFile` instance for rendering on [ActionView::TemplateRenderer](https://github.com/rails/rails/blob/d1d98f3a2404b61457403cc0220fe1a06f3e6acb/actionview/lib/action_view/renderer/template_renderer.rb#L27).

I didn't find any mention to this change on Rails 6 changelog [here](https://edgeguides.rubyonrails.org/6_0_release_notes.html).

Disregard if it is the expected behavior.

Thanks.

**Comment by SebouChu** [comment]
Hello !

It's actually the expected behavior ! From https://guides.rubyonrails.org/layouts_and_rendering.html#rendering-raw-file :
```
This renders the raw file (it doesn't support ERB or other handlers). By default it is rendered within the current layout.
```

If you want to render a ERB template :
1. Put your test template in `app/views` and render it as template
  `ActionController::Base.render(template: 'test', ...)`
2. Read the file and render the string as inline
  `ActionController::Base.render(inline: File.read(Rails.root.join('test.html.erb')), ...)`

As you may think, the first choice is better 😁
Also, in your example, you print `<%= foo =>` instead of `<%= foo %>` in your file, maybe a typo?

Have a good day, and may the 4th be with you 😉

**Comment by pedrofs** [comment]
Thanks for the info.

I'm currently using the `inline` solution.

Closing this then!

**Comment by mldoscar** [comment]
> Hello !
> 
> It's actually the expected behavior ! From https://guides.rubyonrails.org/layouts_and_rendering.html#rendering-raw-file :
> 
> ```
> This renders the raw file (it doesn't support ERB or other handlers). By default it is rendered within the current layout.
> ```
> 
> If you want to render a ERB template :
> 
> 1. Put your test template in `app/views` and render it as template
>    `ActionController::Base.render(template: 'test', ...)`
> 2. Read the file and render the string as inline
>    `ActionController::Base.render(inline: File.read(Rails.root.join('test.html.erb')), ...)`
> 
> As you may think, the first choice is better 😁 Also, in your example, you print `<%= foo =>` instead of `<%= foo %>` in your file, maybe a typo?
> 
> Have a good day, and may the 4th be with you 😉

My solution based on your proposal, using rails 6.1.4

```ruby
lookup_context = ActionView::LookupContext.new(ActionController::Base.view_paths)
context = ActionView::Base.with_empty_template_cache.new(lookup_context, { some: '1', other: '2', parameters: '3' }, nil)
renderer = ActionView::Renderer.new(lookup_context)
rendered_content = renderer.render(context, { inline: File.read(Rails.root.join("app", "views", "whateverfile.html.erb")) })
```

Worked like charm. Thank you
