### ISSUE TITLE
Should Update latest version of babel 

### ISSUE THREAD

**Issue by smondal** [rails/rails#39114]
### Steps to reproduce

We can see there are old version of babel-core, babel-plugin-external-helpers, babel-preset-env in activestorage and actioncable . We should updated this with latest babel 7.9.0.
https://github.com/rails/rails/blob/master/activestorage/package.json#L24
https://github.com/rails/rails/blob/master/actioncable/package.json#L26

Rails webpacker already maintaining latest version of babel.
https://github.com/rails/webpacker/blob/master/package.json#L15

### Expected behavior
We should updated this with  latest babel 7.9.0.

### System configuration
**Rails version**:
Master branch
**Ruby version**:

**Comment by georgeclaghorn** [comment]
Feel free to open a PR (preferably with an evaluation of the specific benefits of each upgrade).
