### ISSUE TITLE
PostgreSQL Date type casting broken on aggregate functions (edge)

### ISSUE THREAD

**Issue by khustochka** [rails/rails#39110]
### Steps to reproduce
- Use PostgreSQL
- Define column of type `date` in a table
- Use aggregate function (e.g. maximum) on this column 

### Expected behavior
Function returns a value of class Date.
(This is how it behaves in Rails 6.0.2 - see [successful test case](https://gist.github.com/khustochka/7b1f6f09a67c3218a2ae43334e8ecad3))

### Actual behavior
Function returns a value of class String.

Failing test case: https://gist.github.com/khustochka/3698dd1af4ba12eeb9e00b2fa3dc66e9

This issue was introduced in the following commit: e10765cfa5e05a655d208e6c598a32b8dce64752

### System configuration
**Rails version**:
Edge (7669dc219675e81d38736c3cf0b0e8cef699a37c)

**Ruby version**:
2.6.6

**Comment by kamipo** [comment]
Thanks for the report, it should be fixed by #39111.

**Comment by khustochka** [comment]
Thank you!
