### ISSUE TITLE
Missing/misspelled methods in views produce newbie-unfriendly errors

### ISSUE THREAD

**Issue by avdi** [rails/rails#39129]
One of the things I like about Rails is that I can generally write "the code I wish existed" and then the next error will point me in the direction of where to add the missing code. E.g. I can add a `resources :foos` route and point a browser at it and rails will be like "I couldn't find a FoosController!" and now I know what to do next.

But then there's this:

```
undefined local variable or method `foo` for #<#<Class:0x012345012345>:<0x012345012345>
```

Showing the raw generated inspect info for an anonymous generated class (`#<#<Class:0x012345012345>:<0x012345012345>`) doesn't add any information, and it doesn't provide any guidance on where to look for the correctly-spelled method and/or where to add a missing method.

I'm thinking of making a PR for this; pointers for prior art are welcome 😀

**Comment by p8** [comment]
I saw your tweet and was trying to see if I could help.
I think the anonymous class is created here:
https://github.com/rails/rails/blob/d9bfafd9b8af6d3ee099d6a3d431744b70666aac/actionview/lib/action_view/rendering.rb#L64

**Comment by p8** [comment]
It seems to have been recently changed for performance reasons: https://github.com/rails/rails/commit/f9bea6304dfba902b1937b3bc29b1ebc2f67e55b

**Comment by avdi** [comment]
Tagging @dhh by request

**Comment by dhh** [comment]
Big 👍 for fixing those. That error is entirely unhelpful.
