### ISSUE TITLE
Implementation of `String#blank?` fails on invalid UTF-8 string

### ISSUE THREAD

**Issue by jwilger** [rails/rails#39146]
### Steps to reproduce

```ruby
require 'active_support/core_ext/object/blank'

# This works fine
"Ren\xE9e".force_encoding("ISO-8859-1").blank?

# But if for some reason Ruby thinks the string is UTF-8 it raises an exception
"Ren\xE9e".force_encoding("UTF-8").blank?
```

### Expected behavior
If the string isn't blank, regardless of whether it is properly encoded, then `#blank?` should return false.

### Actual behavior
The second line (with UTF-8 encoding) raises an exception: `ArgumentError (invalid byte sequence in UTF-8)`

### System configuration
**Rails version**: 6.0.2.2 (issue present at least as far back as 5.0.2)

**Ruby version**: 2.6.0

**Comment by eugeneius** [comment]
A patch to make `blank?` behave this way was recently rejected: https://github.com/rails/rails/pull/38722

If the input isn't valid, preventing `blank?` from blowing up won't make your application behave correctly - you're presumably going to do something else with it once `blank?` returns false.
