### ISSUE TITLE
`rails db:migrate:{namespace}` does not work with shards defined in ApplicationRecord

### ISSUE THREAD

**Issue by manasa-se** [rails/rails#39157]
Running namespaced migrations in multi-db apps does not work when shards are defined in the ApplicationRecord model.
[This line of code](https://github.com/rails/rails/blob/master/activerecord/lib/active_record/connection_handling.rb#L224) seems to be the problem as referencing ApplicationRecord here runs the [connects_to](https://github.com/rails/rails/blob/master/activerecord/lib/active_record/connection_handling.rb#L81) method which is resetting it to the default connection. This can be reproduced on a rails console in addition to testing it by setting breakpoints while running a migration (`rails db:migrate:primary_shard_one`).

<img width="722" alt="Screen Shot 2020-05-05 at 6 30 24 PM" src="https://user-images.githubusercontent.com/1896520/81122497-f74bd180-8efe-11ea-8bb8-6c8a70963825.png">

![image](https://user-images.githubusercontent.com/1896520/81123491-32e79b00-8f01-11ea-99f2-168fe7bc2675.png)

### Steps to reproduce

- Create 2 databases - primary and primary_shard_one - and set their migration paths
- Add ApplicationRecord and setup the shard connections using [connects_to](https://github.com/rails/rails/pull/38531/files#diff-1ed2907b3b8f148c2533558a77673ffaR21)
- Create a migration under primary_shard_one
- Run rails db:migrate:primary_shard_one

### Expected behavior

Migrates primary_shard_one database

### Actual behavior

Migrates primary database and adds the migration defined in the `primary_shard_one` folder to `primary` schema_migrations

### System configuration
**Rails version**:
Rails 6.1.0.alpha

**Ruby version**:
ruby 2.6.3p62

**Database*
mysql2, TBD if the migration runs on the wrong shard on sqlite and other dbs

**Comment by eileencodes** [comment]
I think your app is setup incorrectly. If you're sharding the main database then shards should share the same migrations path because their schemas are the same. If you want to shard the main ApplicationRecord connection then your app should look like this:

```yml
# config/database.yml

development:
  primary:
    database: "my_db"
  primary_shard_one:
    database: "my_db_shard_one
```

```ruby
# app/models/application_record.rb

class ApplicationRecord < ActiveRecord::Base
  connects_to shards: {
    default: { writing: :primary },
    shard_one: { writing: :primary_shard_one }
  }
```

If this doesn't solve the problem for you please provide a sample application that demonstrates the issue.

**Comment by eileencodes** [comment]
I'm going to close this since I haven't heard back. Thanks for the report, hope my suggestion worked 😄

**Comment by manasa-se** [comment]
Hi @eileencodes, I was able to reproduce the issue specifically with rolling back the database. Here's a sample setup - https://github.com/manasa-se/rails_shard_test_app

I have tested with sqlite and mysql so far and this issue happens on mysql. Let me know if I can provide more information and I will try to reproduce a failing test on rails.

**Comment by eileencodes** [comment]
Are you seeing an error or is it just not running?

**Comment by eileencodes** [comment]
I think I know what the issue is but I won't be able to work on this until next week. In the mean time `db:migrate` will run for all shards and I verified that works.

**Comment by manasa-se** [comment]
Thanks for looking into it! `db:migrate` works but the issue happens specifically with `db:rollback:<namespace>`
I've added the issue description to the readme of the example app for reference - 

> There is an issue specifically with rolling back the database when mysql is used and the ApplicationRecord model is setup to connect to shards (https://github.com/manasa-se/rails_shard_test_app/blob/master/app/models/application_record.rb). On issuing rails db:rollback:primary_shard_one, it still connects to primary and rolls back the migration in the primary database. This issue does not occur when using sqlite. It also can be circumvented by using a new abstract class and defining the connections there instead of in ApplicationRecord.
> 
> Steps to reproduce --
> 
> rails db:migrate
> rails db:rollback:primary_shard_one
> rails db:rollback:primary
> Step 3 will not show any output as Step 2 has rolled back primary already.
