### ISSUE TITLE
ActionDispatch::SystemTestCase would not require Selenium::Webdriver by default

### ISSUE THREAD

**Issue by deepj** [rails/rails#39154]
Hello,
I use [apparition](https://github.com/twalpole/apparition) as a Capybara's driver in my system tests. Not selenium webdriver.

```ruby
# frozen_string_literal: true

require 'test_helper'
require 'capybara/apparition'

Capybara.register_driver :apparition do |app|
  Capybara::Apparition::Driver.new(app, browser_logger: nil, window_size: [1440, 900])
end

class ApplicationSystemTestCase < ActionDispatch::SystemTestCase
  include Devise::Test::IntegrationHelpers

  driven_by :apparition
end
```

Unfortunately, I can't remove `selenium-webdriver` because `ActionDispatch::SystemTestCase` requires it here https://github.com/rails/rails/blob/3e0cdbeaf4e769ebd356a2c06dfae13d22283b7c/actionpack/lib/action_dispatch/system_test_case.rb#L7

So I can't remove it from my `Gemfile`. For me it is only something extra and useless gem. This gem would be optional and Rails would let an user to set a Capybara's driver chosen by a user

### System configuration
**Rails version**: 6.0.3.rc1

**Ruby version**: 2.7.1

**Comment by jonathanhefner** [comment]
Fixed by #39179.
