### ISSUE TITLE
activestorage.js errors when imported [v5.2.4][JS]

### ISSUE THREAD

**Issue by jackscotti** [rails/rails#39176]
### Steps to reproduce
Go to https://npm.runkit.com/activestorage and click 'run'

### Expected behavior
The package should be imported without error

### Actual behavior
Errors with: 
`ReferenceError: File is not defined`  at: `activestorage/app/assets/javascripts/activestorage.js — line 438`

I get the same error when importing the package in Next.js app. 

### System configuration
**Rails version**: 
Irrelevant

**Ruby version**: 
Irrelevant

**Comment by santib** [comment]
I think that `File` refers to the DOM File API https://developer.mozilla.org/en-US/docs/Web/API/File , not sure if there is something to do here 🤔

**Comment by eugeneius** [comment]
See https://github.com/rails/rails/issues/34586; activestorage.js isn't intended to run in a Node.js environment.

**Comment by AdnanTheExcellent** [comment]
If anyone is trying to get activestorage working with server side rendering, you can do the following:

create a file activestorageStub.js (or ts) that has the following line:

```javascript
export const DirectUpload = null;
```

then in webpack, add it as an alias:

```javascript
if (ssr) {
  resolve.alias = {
    activestorage: path.resolve(PATH, 'TO, FILE, 'activestorageStub.ts'),
  }
}
```
