### ISSUE TITLE
ActiveRecord `relation.distinct.sum(:column)` turns into surprising `SELECT SUM(DISTINCT "column")`

### ISSUE THREAD

**Issue by Qqwy** [rails/rails#39177]
### Steps to reproduce

We have a model with a numeric field that has a couple instances saved in the table. Say an `Order` with a `:price` column.

We can then run `some_orders.sum(:price)` to get the sum of order prices for a scope or relation.

In this example, let's choose `some_orders = Order.all.distinct`. 
In practice, of course we'd use `distinct` only when e.g. joining orders through some othert table, say `my_shop.orders.joins(:products).where(product: my_shop.products.premium).distinct`.

However, for this example it is enough to realize that we get different behaviour when using `Order.all.distinct` vs `Order.all`, even if there are no duplicate orders in the relation or scope.

### Expected behavior

I would expect a `SELECT DISTINCT SUM("price") FROM "orders"`. In other words: I'd expect the `DISTINCT` to work just as when not using `ActiveRecord::Calculations` on removing duplicate _rows_.

### Actual behavior
The actual query that is executed is a `SELECT  SUM(DISTINCT "price") FROM "orders"`.

This means that `some_orders.sum(:price) / some_orders.count != some_orders.average(:price)` which is very confusing.

The fact that a hidden `#distinct` (which usually works to reduce the set to distinct _rows_) can alter the behaviour of `ActiveRecord::Calculations` to suddenly work on distinct _values_ is confusing. 

At the very least, we should document this behaviour in its (`#calculate`'s) documentation.

Personally, I'd be in favour of removing this way of using `#distinct` and instead add an option to `ActiveRecord::Calculation#calculate` that allows you to specify that you want the calculation to use only distinct values.

**Comment by sinsoku** [comment]
Related to #16791, #33082
