### ISSUE TITLE
Different results when grouping by same column in 6.0.3

### ISSUE THREAD

**Issue by ankane** [rails/rails#39171]
### Steps to reproduce

Not sure how common this is, but noticed it when tests in one of my projects broke.

```ruby
# frozen_string_literal: true

require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  # Activate the gem you are reporting the issue against.
  gem "activerecord", "6.0.3"
  gem "sqlite3"
end

require "active_record"
require "minitest/autorun"
require "logger"

# This connection will do for database-independent bug reports.
ActiveRecord::Base.establish_connection(adapter: "sqlite3", database: ":memory:")
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :posts, force: true do |t|
    t.string :name
  end
end

class Post < ActiveRecord::Base
end

class BugTest < Minitest::Test
  def test_bug
    Post.create!(name: "Test")
    assert_equal({["Test", "Test"] => 1}, Post.group(:name).group(:name).count)
  end
end
```

### Expected behavior

Multiple group statements return array keys (same as in < 6.0.3)

```ruby
{["Test", "Test"] => 1}
```

### Actual behavior

```ruby
{"Test" => 1}
```

### System configuration
**Rails version**: 6.0.3

**Ruby version**: 2.7.1

**Comment by jonathanhefner** [comment]
This change was made by #38145, so I believe the new behavior is intended.  Could you share more context about why this behavior wouldn't be desirable?

**Comment by rafaelfranca** [comment]
I'm not sure if this behavior would be desirable but it should not change in a patch release. With `group` this caused a change in result, so if we really want to change this behavior it should be reverted from 6.0 and in 6.1 we should deprecate receiving the same argument twice.

**Comment by rafaelfranca** [comment]
cc @kamipo

**Comment by kamipo** [comment]
hmm... I wasn't aware of `group(...).count` result is very fragile. I'll work to fix it anyway.

**Comment by ankane** [comment]
Hey @jonathanhefner, thanks for sharing. Was trying to see if it was intentional, but didn't come across that. I personally find it more intuitive that multiple group statements would always stack up for consistency (even if they're going to return the same value), but this specific case seems pretty uncommon.

Thanks all for the quick responses and update!
