### ISSUE TITLE
update_columns doesn't work with strong parameters

### ISSUE THREAD

**Issue by bendilley** [rails/rails#39180]
### Steps to reproduce
```ruby
record.update_columns ActionController::Parameters.new(approval_state: 'denied').permit(:approval_state)
```

### Expected behavior
I would expect `update_columns` to accept attributes from an instance of `ActionController::Parameters` in the same way as `update_attributes` does.

### Actual behavior
```
NoMethodError: undefined method `each_key' for #<ActionController::Parameters:0x00007f9eb9827a80>
Did you mean?  each_pair
from ~/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/activerecord-5.2.4.2/lib/active_record/persistence.rb:472:in `update_columns'
```

### System configuration
**Rails version**: 5.2.4.2

**Ruby version**: 2.6.4

**Comment by santib** [comment]
I get your point, on the other hand if we add that, we'd make `ActiveRecord` know about `ActionController` which is something currently doesn't happen. So, I'd say to not add that, and maybe clarify in the documentation that you should do `.to_h` to the strong parameters before calling `update_columns`. Thoughts?

**Comment by eugeneius** [comment]
This works since https://github.com/rails/rails/pull/33758, where `each_key` was added to `ActionController::Parameters`.

**Comment by santib** [comment]
@eugeneius I don't think it's working.. I just tried it in a fresh Rails 6 app:

```
irb(main):003:0> Post.first.update_columns(ActionController::Parameters.new(title: 'b').permit(:title))
  Post Load (0.4ms)  SELECT "posts".* FROM "posts" ORDER BY "posts"."id" ASC LIMIT ?  [["LIMIT", 1]]
Traceback (most recent call last):
        1: from (irb):3
NoMethodError (undefined method `map' for <ActionController::Parameters {"title"=>"b"} permitted: true>:ActionController::Parameters)
```

Should we add `map` (or Enumerable?) to `ActionController::Parameters` too?

**Comment by eugeneius** [comment]
Whoops! I tested this in a real application, where it's only working because of a monkey patch 😅 

Rather than adding more methods to `ActionController::Parameters`, I think the right solution here is to pass the argument through `sanitize_for_mass_assignment` before using it.

**Comment by rafaelfranca** [comment]
There is a reason for `update_columns` not call `sanitize_for_mass_assignment`. It is considered low level API and it has less features than `update`. Not sure if we should add mass assignment check to it. It should not receive unsafe inputs from end-users.

If developers want to pass `ActionController::Parameters` to it anyway, I don't see why they can't do `record.update_columns ActionController::Parameters.new(approval_state: 'denied').permit(:approval_state).to_h`.

**Comment by santib** [comment]
@rafaelfranca Would something like https://github.com/rails/rails/pull/39189 be ok? Or do you think it can be harmful in any situation?

**Comment by rafaelfranca** [comment]
I think @kaspth already answered that. In my opinion it is more intention revealing that you call `to_h` when mass assignment protection is not supported.

But I think there is something to be changed here. Do we need to skip `sanitize_for_mass_assignment` in `update_columns`? Would it passing a permitted `ActionController::Parameters` to `update_columns` be more dangerous than passing to `update`?

I can't think in any case where you would end up in trouble if you pass a permitted `ActionController::Parameters` to `update_columns` that you wouldn't have if you pass to `update_attributes` so I think it is fine to add mass assignment check there.

I'd not add support to this in `exec_query` and other lower level APIs, but I think in `update_columns` is fine. Can you open a PR doing that? If possible I'd like to see what is the impact on performance when you don't pass a `ActionController::Parameters` instance with this new patch.

**Comment by santib** [comment]
@rafaelfranca I just opened a PR. Let me know if you'd like to benchmark it in some other way (multiple columns, or something else).
