### ISSUE TITLE
new_record? returns nil

### ISSUE THREAD

**Issue by HugoMochao** [rails/rails#39182]
### Steps to reproduce
Since it is a relatively big project, I don't know for sure what are the exact conditions to reproduce. I can leave here the github link to the project. 
https://github.com/HugoMochao/KiMoSys-2.0

Trying to create a user, for example:

```
irb(main):002:0> user1 = User.new(email: "johndoe@gmail.com", first_name: "john", last_name: "doe", affiliation: "test", research_interests: "test", home_page: "test")
=> #<User id: nil, email: "johndoe@gmail.com", created_at: nil, updated_at: nil, admin: nil, first_name: "john", last_name: "doe", affiliation: "test", research_interests: "test", home_page: "test">
irb(main):003:0> user1.new_record?
=> nil
```

new_record? returns nil

### Expected behavior

I was facing a problem when trying to create new records and put them in the database (using function save). The database instead of doing an Insert, was trying to do an update on new records. After some time, and using ruby console to try to figure out what was wrong, because save was returning true without any errors, I discovered that new_record? was returning nil.

new_record? should return true if the record to be inserted in the database is not there yet, and false if it is there already. So, it should do an insert if new_record==true, and an update if new_record==false

### Actual behavior
new_record is returning nil, so when I try to introduce new data to the database, instead of doing an insert, it tries to do an update.

For example:

```
irb(main):002:0> user1 = User.new(email: "johndoe@gmail.com", first_name: "john", last_name: "doe", affiliation: "test", research_interests: "test", home_page: "test")
=> #<User id: nil, email: "johndoe@gmail.com", created_at: nil, updated_at: nil, admin: nil, first_name: "john", last_name: "doe", affiliation: "test", research_interests: "test", home_page: "test">
irb(main):003:0> user1.new_record?
=> nil
irb(main):004:0> user1.save
   (0.1ms)  begin transaction
  User Exists? (0.2ms)  SELECT 1 AS one FROM "users" WHERE "users"."email" = ? AND "users"."id" IS NOT NULL LIMIT ?  [["email", "johndoe@gmail.com"], ["LIMIT", 1]]
  User Update (0.8ms)  UPDATE "users" SET "updated_at" = ?, "confirmation_token" = ?, "confirmation_sent_at" = ?, "unconfirmed_email" = ?, "first_name" = ?, "last_name" = ?, "affiliation" = ?, "research_interests" = ?, "home_page" =
 ? WHERE "users"."id" IS NULL  [["updated_at", "2020-05-07 15:12:13.588179"], ["confirmation_token", "HjHenAWotkWLgHtrnAJx"], ["confirmation_sent_at", "2020-05-07 15:12:13.588334"], ["unconfirmed_email", "johndoe@gmail.com"], ["firs
t_name", "john"], ["last_name", "doe"], ["affiliation", "test"], ["research_interests", "test"], ["home_page", "test"]]
   (0.0ms)  commit transaction
=> true
```
(I use devise gem, so I thought that maybe it was a problem with it, but then I followed the exact same steps with another model and the result was the same)

I have tried to look for similar errors, but all I managed to find was this (from 2008): https://rails.lighthouseapp.com/projects/8994-ruby-on-rails/tickets/1219-new_record-not-set-when-using-joins

Using the fix, presented in that link, in application_record.rb file:

```
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
  def new_record?
    (answer = super).nil? ? true : answer
  end
end
```
I was able to find a temporary solution. 

And now I did a migration from paperclip to ActiveStorage, and the problem arose again because Active Storage models are not related to application_record.rb. I believe that new_record? is returning nil again, although I did not test that yet. So, when I try to insert a new attachment,  this occurs.

```
Started POST "/rails/active_storage/direct_uploads" for ::1 at 2020-05-07 14:59:55 +0100
Processing by ActiveStorage::DirectUploadsController#create as JSON
  Parameters: {"blob"=>{"filename"=>"relatoria (2).pdf", "content_type"=>"application/pdf", "byte_size"=>69998, "checksum"=>"ghsmHAMwBPwwfCMWu0SIPA=="}, "direct_upload"=>{"blob"=>{"filename"=>"relatoria (2).pdf", "content_type"=>"ap
plication/pdf", "byte_size"=>69998, "checksum"=>"ghsmHAMwBPwwfCMWu0SIPA=="}}}
   (0.0ms)  begin transaction
  ActiveStorage::Blob Update (0.4ms)  UPDATE "active_storage_blobs" SET "filename" = ?, "content_type" = ?, "byte_size" = ?, "checksum" = ? WHERE "active_storage_blobs"."id" IS NULL  [["filename", "relatoria (2).pdf"], ["content_typ
e", "application/pdf"], ["byte_size", 69998], ["checksum", "ghsmHAMwBPwwfCMWu0SIPA=="]]
   (0.0ms)  commit transaction
Completed 500 Internal Server Error in 47ms (ActiveRecord: 1.1ms | Allocations: 17056)




URI::GID::MissingModelIdError (Unable to create a Global ID for ActiveStorage::Blob without a model id.):

```
This was exactly what was happening before I introduced that "fix" in application_record.rb. The database tries to do an UPDATE where model.id IS NULL

### System configuration
**Rails version**: 6.0.0

**Ruby version**: ruby 2.6.5p114 

**SQLite version**: 3.30.1

**gem 'sqlite3' version**: '1.4.1'

**Comment by rafaelfranca** [comment]
This seems to be caused by some gem. Can you try to remove some of the gems in the project to see which one is causing it?

**Comment by rafaelfranca** [comment]
My bet is on `protected_attributes_continued`, since it is missing setting `@new_record` in the `initialize` here https://github.com/westonganger/protected_attributes_continued/blob/master/lib/active_record/mass_assignment_security/core.rb#L5`.

**Comment by HugoMochao** [comment]
You are absolutely right! I removed some of the gems as you said, and after removing `protected_attributes_continued ` , new_record? returned true
