### ISSUE TITLE
Cache_Control Header

### ISSUE THREAD

**Issue by muhammedtufekyapan** [rails/rails#39188]
### Steps to reproduce
I want to set default cache_control header of Active Storage objects.

### Expected behavior
 I try to add upload controls in **storage.yml** like this;

`google:
service: GCS
project: "<bucket_name>"
credentials: <%= Rails.root+"credentials.json" %>
bucket: "<bucket>"
upload:
cache_control: "public, max-age=31536000"`

### Actual behavior

I got

`unknown keyword: upload`

error.
### System configuration
**Rails version**: 6.0.2.1

**Ruby version**: 2.6.3

**Comment by jonathanhefner** [comment]
Thank you for the issue, but this seems to be a feature request, and we don't take feature requests on the issue tracker.

It is worth noting that this feature was recently added by #39000, however, it has been tentatively reverted.

**Comment by maleblond** [comment]
Support for a cache_control setting for a GCS service has been added in #42509 .
