### ISSUE TITLE
Cookie “_rails6_session” will be soon rejected because it has the “sameSite” attribute set to “none” or an invalid value, without the “secure” attribute.

### ISSUE THREAD

**Issue by evolve2k** [rails/rails#39190]
Firefox 76 console warning:
_Cookie “_rails6_session” will be soon rejected because it has the “sameSite” attribute set to “none” or an invalid value, without the “secure” attribute. To know more about the “sameSite“ attribute, read https://developer.mozilla.org/docs/Web/HTTP/Cookies new._

Chrome 83 console warning: (Added 29 May)
_"A cookie associated with a cross-site resource at <URL> was set without the `SameSite` attribute. A future release of Chrome will only deliver cookies with cross-site requests if they are set with `SameSite=None` and `Secure`. You can review cookies in developer tools under Application>Storage>Cookies and see more details at <URL> and <URL>."_ 

### Steps to reproduce
This error shows in the web console in Firefox (76.0) and Firefox Dev Edition (76.0b8).
Does not show in Firefox (75.0) or Chrome (81.0.4044.129).

Seems to be occurring due to a change in Firefox 76.

### Expected behavior
Warning seems to be referencing a Rails 6 internal.

### Actual behavior
Address warning so it does not show in Firefox 76.

### System configuration
Warning shows with ruby 2.6.5 and rails 6.0.2.
I upgraded to latest ruby 2.7.1 and rails 6.0.3 and error still occurs.

**Comment by rafaelfranca** [comment]
Didn't Google decide to revert the SameSite change? https://blog.chromium.org/2020/04/temporarily-rolling-back-samesite.html.

I think Firefox is wrong here.

**Comment by evolve2k** [comment]
Thanks for the update. I use Firefox Dev Edition for development and it was showing as a warning and I couldn't find any reference to it elsewhere especially as it was referring to rails6_session. Yes seems its come through to latest Firefox.

That might be the case that it's delayed, but sounds like it should still be addressed within rails, especially knowning that the changes, while delayed are still coming.

**Comment by ekampp** [comment]
> Didn't Google decide to revert the SameSite change? https://blog.chromium.org/2020/04/temporarily-rolling-back-samesite.html.
> 
> I think Firefox is wrong here.

While Mozilla may have bad timing, they're not alone in wanting to make this change, and they're not wrong. 

The article also clearly states that the pause in rollout I a temporary one related to covid19.

The sameSite change is coming (just like winter).

**Comment by jamesw** [comment]
I am seeing this also on the latest release of Firefox 76.0 (64-bit) Mozilla Firefox for Linux Mint - 1.0
This is not a development build

**Comment by evolve2k** [comment]
> Didn't Google decide to revert the SameSite change? https://blog.chromium.org/2020/04/temporarily-rolling-back-samesite.html.

As of today, Google has announced its [Resuming SameSite Cookie Changes in July](https://blog.chromium.org/2020/05/resuming-samesite-cookie-changes-in-july.html).

So thanks @rafaelfranca, appreciate you adding it to [6.0.4](https://github.com/rails/rails/milestone/75) milestone.

**Comment by silviorelli** [comment]
Take a look at [this recent post](https://hacks.mozilla.org/2020/08/changes-to-samesite-cookie-behavior/) from Mozilla.

**Comment by ryanfb** [comment]
Currently, in Rails <6.1 I believe the default is to set no `SameSite` value. The warning arises from a specific set of browser versions which would default this to `SameSite=None` and warn about a potential deprecation in combining that without `Secure`, but in the future when actual enforcement against setting `None` without `Secure` will happen will default to `Lax` instead.

If we assume `SameSite=Lax` defaults in the browser (what Chrome and Firefox are now planning), what does closing this issue look like on the Rails side? Explicitly setting `SameSite` (with `Lax` defaults) on the Rails side is already slated for 6.1 (there's some extensive discussion [here](https://github.com/rails/rails/pull/28297)).

**Comment by evolve2k** [comment]
>  Explicitly setting SameSite (with Lax defaults) on the Rails side is already slated for 6.1
Awesome! AFAIK it was slated from this thread. See post 8 May.
Thanks for the link to the other discussion.

I expect this thread will stay open until 6.1 is delivered or other issues arise with this.

**Comment by rafaelfranca** [comment]
Given this is fixed on Rails 6.1 there is no reason to keep this open. Rails 6.1 will be released in the next weeks.

**Comment by laneystroup** [comment]
>Explicitly setting `SameSite` (with `Lax` defaults) on the Rails side is already slated for 6.1 (there's some extensive discussion [here](https://github.com/rails/rails/pull/28297)).

@ryanfb , one footnote: it looks like the default in Rails 6.1 will be "None" unless/until they flip the default: https://github.com/rails/rails/blob/5394c94a2b8fa3b24893f00b2fc20d6554bf31c9/railties/lib/rails/generators/rails/app/templates/config/initializers/new_framework_defaults_6_1.rb.tt#L26. Is this what you meant?

**Comment by ryanfb** [comment]
@laneystroup another [later commit](https://github.com/rails/rails/commit/7ccaa125ba396d418aad1b217b63653d06044680) than the PR linked above changes the default to lax (and the template there has commented-out initializers that show what the default value should be). You can see it set [here](https://github.com/rails/rails/blob/94ba417ecec8272700805268b76be7de9a470a59/railties/lib/rails/application/configuration.rb#L179) and tested [here](https://github.com/rails/rails/blob/211564c6385bcc6ccf5e32804554a6c96c662220/railties/test/application/configuration_test.rb#L2336-L2340).

**Comment by ambethia** [comment]
> Rails 6.1 will be released in the next weeks.

😭

**Comment by evolve2k** [comment]
Where are we at? I'm getting a little lost.

Right now do we expect this warning message to go away in Rails 6.1 or not?

**Comment by kimpastro** [comment]
Any news? Using rails 6.0.0 and can't find way to make this work.

**Comment by ryanfb** [comment]
The commits which fix this are included in Rails v6.1.0.rc1. You can enable them by specifying the RC in your `Gemfile`:
```
gem 'rails', git: 'https://github.com/rails/rails.git', tag: 'v6.1.0.rc1'
```
Then run `bundle`, then `rails app:update`. Afterwards, set `Rails.application.config.action_dispatch.cookies_same_site_protection = :lax` appropriately in your config, and you shouldn't get any browser warnings.

**Comment by evolve2k** [comment]
**To clarify, with the full release of Rails 6.1 do we expect this warning to go away?** 
And I mean to be gone in a way that does not require any user intervention such as changing any settings like above.

**Comment by rafaelfranca** [comment]
If you generate a new application, yes. If you are updating an existing application you still need to change the `cookies_same_site_protection` configuration, or use the Rails 6.1 default configurations.

See https://github.com/rails/rails/blob/38998af1d9035d529e553251ae441f0c09b7e8ab/railties/lib/rails/generators/rails/app/templates/config/initializers/new_framework_defaults_6_1.rb.tt#L22-L26
