### ISSUE TITLE
`ActiveRecord::ReadOnlyError` occurs even though it is in the `connected_to(role: :writing)` block

### ISSUE THREAD

**Issue by sinsoku** [rails/rails#39205]
### Steps to reproduce

I create a repo to reproduce a issue.
https://github.com/sinsoku/rails_issue_readonly_error

The outline of the repo is as follows.

1. Create an app with `rails new`
2. Create a model with `rails g model user name`
3. Configure for multiple databases to use replica(https://github.com/sinsoku/rails_issue_readonly_error/commit/230a0fda2f7494f9f5627af481017639de2c7d0a)
4. Run the test after disabling fixtures(https://github.com/sinsoku/rails_issue_readonly_error/commit/84212487fb0e53a31452af808c3c6c158b3271e6)

Here is the test code I put in the repository.

```ruby
test "should not raise ActiveRecord::ReadOnlyError" do
  ActiveRecord::Base.connected_to(role: :reading) do
    User.first

    assert_nothing_raised do
      ActiveRecord::Base.connected_to(role: :writing) { User.create! }
    end
  end
end
```

The test fails with `ActiveRecord::ReadOnlyError`.

```console
$ bin/rails test
Running via Spring preloader in process 22117
Run options: --seed 65401

# Running:

E

Error:
UserTest#test_should_not_raise_ActiveRecord::ReadOnlyError:
ActiveRecord::ReadOnlyError: Write query attempted while in readonly mode: INSERT INTO "users" ("created_at", "updated_at") VALUES (?, ?)
    test/models/user_test.rb:9:in `block (4 levels) in <class:UserTest>'
    test/models/user_test.rb:9:in `block (3 levels) in <class:UserTest>'
    test/models/user_test.rb:8:in `block (2 levels) in <class:UserTest>'
    test/models/user_test.rb:5:in `block in <class:UserTest>'

rails test test/models/user_test.rb:4

Finished in 0.149822s, 6.6746 runs/s, 0.0000 assertions/s.
1 runs, 0 assertions, 0 failures, 1 errors, 0 skips
```

### Use case

- Use `ActiveRecord::Middleware::DatabaseSelector`
- Create a record when a request is GET
- Use [factory_bot](https://github.com/thoughtbot/factory_bot) instead of fixtures

I found the issue under these conditions.

### Expected behavior

`ActiveRecord::ReadOnlyError` should not raise.

### Actual behavior

`ActiveRecord::ReadOnlyError` raises.

### System configuration
**Rails version**: 6.0.3

**Ruby version**: 2.7.1

### Related issues

https://github.com/rails/rails/issues/37765

**Comment by eileencodes** [comment]
Thanks for the report. I've verified this is accurate and I believe it has to with how fixtures work. If you ensure that a query is done on the writing connection before reading connections the rest of the test will work. It's partially due to lazy loading and partially due to fixtures.

I won't be able to work on this until next week, if you need to get unblocked you can rewrite your test like this

```ruby
class UserTest < ActiveSupport::TestCase
  test "should not raise ActiveRecord::ReadOnlyError" do
    ActiveRecord::Base.connected_to(role: :writing) { User.first }

    ActiveRecord::Base.connected_to(role: :reading) do
      User.first

      assert_nothing_raised do
        ActiveRecord::Base.connected_to(role: :writing) do
          User.create!
        end 
      end 
    end 
  end 
end
```

If you're interested in working on a fix the problem is probably in the `setup_shared_connection_pool` in `activerecord/lib/active_record/test_fixtures.rb`

**Comment by jji-fieldwire** [comment]
I believe I'm experiencing the same issue, I'm using Rspec. The ReadOnlyErrors disappear when I do
```Ruby
ActiveRecord::Base.connected_to(database: :primary) do
  Account.count
end
```
before every test, but don't with `.connected_to(role: :writing) do`

**Comment by selivandex** [comment]
Exact same problem when using rails 6.1 with `config.active_record.legacy_connection_handling = false`
