### ISSUE TITLE
Conflicting text  in 6.0 upgrade guide for has_many_attached changes

### ISSUE THREAD

**Issue by cpanderson** [rails/rails#39213]
Does the following text in the upgrade guide contradict the rails 6.0 defaults?...

"Opt in to the new default behavior by setting config.active_storage.replace_on_assign_to_many to true. The old behavior will be deprecated in Rails 6.1 and removed in a subsequent release."

If not, I find it confusing as it implies it's optional and had to double check the behaviour in an existing app I'm upgrading to make sure the new default was indeed true.

**Comment by georgeclaghorn** [comment]
Sorry, I’m having trouble understanding your question.

`config.active_storage.replace_on_assign_to_many` is opt-in for existing <6.0 apps upgrading to 6.0. You can set it to `true` to get the new behavior. If you don’t, you get the existing 5.2 behavior.

It’s on by default for new 6.0+ apps. The upgrading guide doesn’t apply to new apps. See [this section](https://guides.rubyonrails.org/configuring.html#for-6-0-new-defaults-from-previous-versions-below-and) of the configuration guide for other configuration options that have different defaults for new apps generated on 6.0 versus existing apps upgrading to 6.0.

**Comment by jonathanhefner** [comment]
@cpanderson I made an attempt to improve the wording in #39215.  Could to take a look, and let me know if that clears things up?

**Comment by cpanderson** [comment]
Hi @georgeclaghorn,

I can understand why someone might want to apply new config defaults to their existing apps but I don’t see where the upgrade guide gives any clear direction on doing this as an optional step. In my case I created a separate branch and followed the guide to upgrade to version 6 straight away so I could work through any issues or conflicts in parallel and found the guide could benefit from a bit more clarity in this regard.

Thanks @jonathanhefner the change you made looks good to me.

**Comment by jonathanhefner** [comment]
> I don’t see where the upgrade guide gives any clear direction on doing this as an optional step. In my case I created a separate branch and followed the guide to upgrade to version 6 straight away

I'm unclear on what you meant by this.  When you upgraded, did you toggle the settings one-by-one in `new_framework_defaults.rb` as [described here](https://guides.rubyonrails.org/upgrading_ruby_on_rails.html#configure-framework-defaults)?  Or did you immediately set `config.load_defaults = "6.0"`?

> Thanks @jonathanhefner the change you made looks good to me.

You're welcome!  Would you say those changes would have prevented your original confusion?  Or should we iterate on them a bit more?

**Comment by cpanderson** [comment]
That definitely provides more clarity.

**Comment by jonathanhefner** [comment]
@cpanderson Great!  Thank you for the feedback!
