### ISSUE TITLE
belongs_to relationship silently returns nil when an invalid foreign key is provided

### ISSUE THREAD

**Issue by beirigo** [rails/rails#39214]
This report is related to [this post](https://discuss.rubyonrails.org/t/invalid-belongs-to-association-silently-returns-nil/74585) on the "A May of WTFs" forum topic.

The main point that I raised is that `belongs_to` and `has_one` behave differently when set up incorrectly. While `has_one` raises a `NameError`, `belongs_to` simply returns `nil`.

### Steps to reproduce
1. add a `belongs_to` relationship that can't be mapped to a model
2. add a `has_one` relationship that can't be mapped to a model
```ruby
# Neither Foo or Bar are defined
class Post < ActiveRecord::Base
  belongs_to :foo
  has_one :bar
end
```

bug report gist: https://gist.github.com/beirigo/24c5e09a735aaf69942ae832448c712a
### Expected behavior

```ruby
post = Post.create!

post.foo
#=> NameError: uninitialized constant Foo

post.bar
#=> NameError: uninitialized constant Bar
```

### Actual behavior

```ruby
post = Post.create!

post.foo
#=> nil

post.bar
#=> NameError: uninitialized constant Bar
```
### System configuration
**Rails version**:
master, 6.0.0, 5.0.0
I couldn't test versions older than 5 because trying to setup the native dependencies became a nightmare :(
**Ruby version**:
2.7.0

### My findings
I narrowed this down to the respective implementation of `find_target?` on each association.
While both implementations check that the `klass` is defined, that check is at the very end of a boolean expression and therefore has low precedence:
```ruby
# BelongsToAssociation
#  foreign_key_present? is false so klass is never invoked 
def find_target?
  !loaded? && foreign_key_present? && klass
end

# HasOneAssociation (deferred to ActiveRecord::Associations)
def find_target?
  !loaded? && (!owner.new_record? || foreign_key_present?) && klass
end
```
I believe that at some point, `has_one`'s implementation of `foreign_key_present?`
tries to load the target class through reflection, somehow raising a `NameError`.

Would moving the `klass` check to the beginning of those boolean expressions be a viable solution? what would the implications of such change be?

**Comment by fedeagripa** [comment]
@beirigo I would call that the `NameError` error comes from the `!owner.new_record?` in the `association.rb#find_target?` (thats not present in the belongs_to overwritten `find_target?`)

**Comment by beirigo** [comment]
@fedeagripa yeah at first glance that would be the first thing to investigate. But`!owner.new_record?` is just making sure the owner of the association has been persisted. 

`HasOne`'s `foreign_key_present?` has to infer the target class in order to check if the foreign key is present (because the foreign key lives in the target table for a `has_one` relationship) raising `NameError` in the process.
