### ISSUE TITLE
ActiveRecord should allow updates with subqueries

### ISSUE THREAD

**Issue by camilova** [rails/rails#39244]
When I update some model attribute with a value resulting of a subquery, `activerecord` makes two queries, one to get the value and one to make the update. It would be very nice in my opinion if `activerecord` could recognize that the value part is an object that can be translated to sql. For example:

`supply.update(stock: histories.sum(:quantity))`

It will hit 2 queries, the first to get the `sum` of `quantities` on `histories`, and a second to update `stock` attribute of a `Supply` instance.

`select sum(:quantity) from histories`
`update supplies set stock = $sum where id = $id`

But, it can be made with only one sql query:

`update supplies.stock = (select sum(quantity) from histories) where id = $id`

It could have a way to tell `activerecord` that `histories.sum(:quantity)` should be an sql part of the whole query, I was thinking something like wrapping the subquery inside `Arel.sql` or some `Arel.subquery` method.

You can generate a valid sql subquery so:

`subquery = histories.select('SUM(quantity)').to_sql`

And set it to the value to update, for example:

`supply.update(stock: subquery)`

It will not work because subquery will trated as a `string`, but what if we can wrap it into `Arel.sql`? to tell `activerecord` that its a sql.

`supply.update(stock: Arel.sql(subquery))`

I'm using **Rails 5.2.3**

**Comment by gabrielmansour** [comment]
I'm interested in seeing this too

**Comment by juliofalbo** [comment]
up

**Comment by ahmedmos3ad** [comment]
up
