### ISSUE TITLE
gem install activesupport, is still installing tzinfo v1.1

### ISSUE THREAD

**Issue by mdost** [rails/rails#39258]
### Steps to reproduce
When I install activesupport, it installs activesupport-6.0.3 but the tzinfo version is installed as 1.2.7. 

```
$ gem install activesupport
Fetching: tzinfo-1.2.7.gem (100%)
Successfully installed tzinfo-1.2.7
Fetching: activesupport-6.0.3.gem (100%)
Successfully installed activesupport-6.0.3
Parsing documentation for tzinfo-1.2.7
Installing ri documentation for tzinfo-1.2.7
Parsing documentation for activesupport-6.0.3
Installing ri documentation for activesupport-6.0.3
Done installing documentation for tzinfo, activesupport after 4 seconds
2 gems installed
```

I know the version has been updated here:
https://github.com/rails/rails/blob/master/activesupport/activesupport.gemspec#L37
On the ruby gem repository it still says the runtime dependency for `tzinfo` is v1.2.7:
https://rubygems.org/gems/activesupport

Can someone please update the gem in the ruby repository to pull the latest master code.

### Expected behavior
tzinfo should be upgraded to v2.0 and not use 1.1

### Actual behavior
Seems like it is still installing tzinfo v1.2.7

**Comment by eugeneius** [comment]
The master branch tracks the upcoming Rails 6.1 release, which will depend on tzinfo 2.0.
