### ISSUE TITLE
Viewport meta tag removed from application layout during `rails new`

### ISSUE THREAD

**Issue by jduff** [rails/rails#39270]
### Steps to reproduce
1. run `rails new whatever`
2. cat whatever/app/views/layouts/application.html.erb

### Expected behavior
`<meta name="viewport" content="width=device-width,initial-scale=1">` tag is in the template

### Actual behavior
Tag is not in the generated template. It is in the base template but being removed during the generation process somewhere https://github.com/rails/rails/blob/master/railties/lib/rails/generators/rails/app/templates/app/views/layouts/application.html.erb.tt#L5

### System configuration
**Rails version**: 6.0.3

**Ruby version**: 2.6.6p146

**Comment by matthewd** [comment]
Hi!

Blame shows that line was added in f1cfe1ee7017d5fe7c1e14fc44f40df70e0b5df3 / #36634

While that does slightly pre-date the 6.0.0 release, we were in release candidates at that time.

The line in question is not present in any released version: https://github.com/rails/rails/blob/6-0-stable/railties/lib/rails/generators/rails/app/templates/app/views/layouts/application.html.erb.tt#L5

It'll be there in 6.1.

**Comment by jduff** [comment]
👍 thanks @matthewd !
