### ISSUE TITLE
ActionText should provide a way to validate client side, otherwise what is the point in using it?

### ISSUE THREAD

**Issue by lhobbs22** [rails/rails#39279]
### Steps to reproduce

There is a lack of documentation and support for ActionText. We should be able to validate client side, it is not good to have to rely on the server side validations as forms get cleared

### Expected behavior
ActionText rich_text_area should accept a way of setting validate: true

### Actual behavior
It is currently not supported, there are no workarounds i.e. using the client_side_validations gem, or by setting attributes on the elements directly via JS

There have been discussions about this but "this isn't supported, sorry" doesn't really help anyone

https://github.com/maclover7/trix/issues/24
https://stackoverflow.com/questions/57455653/trix-editor-validation
https://stackoverflow.com/questions/58646144/rails-6-action-text-form-validation-errors

### System configuration
**Rails version**:
6.0.2.1
**Ruby version**:
6.2.5

**Comment by barkozavr** [comment]
Waiting for an update
