### ISSUE TITLE
Querying association with unscope(:where) from instance removes conditions

### ISSUE THREAD

**Issue by dvandersluis** [rails/rails#39275]
Related to #38811. Trying to access an association of an AR instance where the association unscopes `where` no longer raises an exception, but still removes association conditions from the query.

### Steps to reproduce

```ruby
class Post < ActiveRecord::Base
  has_many :comments, -> { unscope(:where) }
end

class Comment < ActiveRecord::Base
  belongs_to :post

  default_scope { where(locale: :en) }
end

post = Post.create!
post.comments << Comment.create!(locale: nil)
post.comments.to_sql #=> SELECT "comments".* FROM "comments"
```

See https://gist.github.com/dvandersluis/86eb48649747c763dd06fb1bc35a4321 for a failing test.

### Expected behavior
`post.comments.to_sql` should return
```sql
SELECT "comments".* FROM "comments" WHERE "comments"."post_id" = 1
```

### Actual behavior
Unscopes association where clause

```sql
SELECT "comments".* FROM "comments"
```

### System configuration
**Rails version**: 6.0.3

**Ruby version**: 2.6.2

**Comment by dvandersluis** [comment]
I'd be happy to add a PR if someone can point me in the right direction of where the `unscope` is applied.

**Comment by kamipo** [comment]
I had also tried to fix it in #38929, but some tests expects to unscope required conditions for now.

**Comment by dvandersluis** [comment]
@kamipo maybe those tests don't make sense then?

**Comment by dvandersluis** [comment]
@kamipo i saw #38929 was merged does that mean this was fixed?
