### ISSUE TITLE
`fixture_file_upload` cannot locate file (Edge rails)

### ISSUE THREAD

**Issue by khustochka** [rails/rails#39278]
### Steps to reproduce
In my app I have a file, e.g. "test/fixtures/files/tules.jpg". I used to use `fixture_file_upload("files/tules.jpg")`. 

Now on edge Rails (ac65e560db598c7a8b1b6aaea1e5656ff3b27f08), this gives me the following deprecation message:

````
Please modify the call from
`fixture_file_upload(files/tules.jpg)` to `fixture_file_upload(tules.jpg)`
````

Ok, I changed the call to `fixture_file_upload("tules.jpg")`.  Now it fails with the following error:

````
RuntimeError: /<...>/test/fixtures/tules.jpg file does not exist
```` 

(note it looks for the `fixtures/tules.jpg` file, not `fixtures/files/tules.jpg`)

### Expected behavior
`fixture_file_upload` works if file exists in fixtures/files

### Actual behavior
`fixture_file_upload` fails with `file does not exist error`, trying to find the file under fixtures/.

### Demo application:
https://github.com/khustochka/fixture_file_path

See `test/controllers/files_controller_test.rb` for the test file. 

### Investigation

This seems to be introduced in https://github.com/rails/rails/pull/39086.

If we look here: https://github.com/rails/rails/blob/master/actionpack/lib/action_dispatch/testing/test_process.rb#L21 it seems that the path is still constructed relative to `self.class.fixture_path`, not `self.class.file_fixture_path`.

### System configuration
**Rails version**:
2.6.6
**Ruby version**:
Edge (ac65e560db598c7a8b1b6aaea1e5656ff3b27f08)

**Comment by georgeclaghorn** [comment]
I ran into this, too.

/cc @Edouard-chin

**Comment by Edouard-chin** [comment]
Sorry for that and thanks for reporting the bug. https://github.com/rails/rails/pull/39303 will fix it

**Comment by kul-p** [comment]
I tried v. 6.1.4 still not include this bug fixed. Which branch/version ? include this fix/Thanks

**Comment by zzak** [comment]
@kul-p It looks like the patch was applied to 6.1.4 but if you can [reproduce](https://guides.rubyonrails.org/contributing_to_ruby_on_rails.html#create-an-executable-test-case) it please feel free to open a new issue. 🙏

**Comment by kul-p** [comment]
@zzak Thanks, will check and update again.
