### ISSUE TITLE
ActiveStorage new ProxyController raises missing template error

### ISSUE THREAD

**Issue by brenogazzola** [rails/rails#39286]
### Steps to reproduce
I have a page that lists products for sale, and each product has a image stored using active storage. I also have a system test for that page, that opens it and adds a product to a cart.

After updating from `6.0.3` to `6.1.0-alpha` and switching to `resolve_model_to_route = :rails_storage_proxy` that test now raises the following error when the page is opened

```
ERROR -- :   Couldn't find template for digesting: active_storage/representations/proxy/show
```

If I leave the default `redirect_controller` I don't get the error message.

### Expected behavior
No error messages

### Actual behavior
An error message about missing template is shown

### System configuration
**Rails version**: af831a0963695376a29ca62272c841385a39e02f
**Ruby version**: 2.6.6

**Comment by evgeniy-r** [comment]
Hello, can I take this issue?
I will give some feedback about my progress in a day or two.

**Comment by evgeniy-r** [comment]
It seems I got it.
I will prepare PR with a fix.
