### ISSUE TITLE
Dirty state after `update_column` in failed transaction

### ISSUE THREAD

**Issue by iHiD** [rails/rails#39295]
Hello lovely Rails people. 

This is an issue to do with the state models are left in after a failed `update_column` in a transaction, and how it differs from if you use `model.column = new_val; model.save!`

I am unsure as to whether it is considered a bug, or something that needs extra documentation, or just PEBCAC (and I should just redo everything after a failed transaction), but I could see it causing bugs and unintended consequences, and I've spent enough time making sense of it that I thought at the very least someone else might benefit from finding the issue even if you decide it's not worth pursuing further :)

### Steps to reproduce

I think the easiest way to explain is to read this short code example. The model is irrelevant but for this example, let's presume we have a `SomeModel` with a `status` enum on it that's initially set to `pending` and that we want to set to `fulfilled`.

```
obj = SomeModel.find(1)

obj.status
#=> "pending"

ActiveRecord::Base.transaction do
  obj.update_column(:status, :fulfilled)
  raise
rescue
end

# The transaction has rolled back so the status in
# the database is still "pending"
SomeModel.find(1).status
#=> "pending"

# However the object thinks it's got the new status of 
# fulfilled, and that there is nothing to write to the db.
obj.status
#=> "fulfilled"

obj.changed?
#=> false

obj.has_changes_to_save?
#=> false

# Where this becomes really problematic is that if I 
# try to set the value and save, the save method returns as if
# it's worked, but the database is not updated.
obj.status = :fulfilled
obj.save!
obj.status
# => 'fulfilled'

SomeModel.find(1).status
# => 'pending'
```

If I had used `obj.status = :fulfilled; obj.save!` within the initial transaction, then the model would have been correctly marked as having changes and need saving, and the rest of the flow would be as I would expect.

### System configuration
**Rails version**: Rails 6.0.2.2
**Ruby version**: ruby 2.7.1p83 (2020-03-31 revision a0c7c23c9c) [x86_64-darwin19]

Thanks for all your work 💙

**Comment by p8** [comment]
Hi @iHiD, thanks for the bug report.

I think this is by design. `#save` and `#destroy` are automatically wrapped in a transaction using the `#with_transaction_returning_status` method. Besides running everything in a transaction, this method will also rollback changes if the transaction fails. See: https://github.com/rails/rails/blob/master/activerecord/lib/active_record/transactions.rb#L343

`#update_columns` is run without transactions and callbacks by design. You can wrap it in a transaction block, but you'll miss the rollback callbacks.

**Comment by iHiD** [comment]
@p8 Sorry for the slow reply. And thanks for the explanation.

I guess my concern is that the object has internal inconsistencies at this stage.

The last bit that I commented on is specifically problematic, where a new value is set and the object saved, but that change is then not reflected. This could easily result in data loss. If the internal state of the object is effectively corrupted after a transaction fails, do you think there should be another flag that can be used to check that, or that a subsequent `save!` raises an exception?
