### ISSUE TITLE
ActiveRecord::SecureToken v6.0.3 different from master one

### ISSUE THREAD

**Issue by v0rs4** [rails/rails#39294]
I was wondering why [Rails v6.0.3](https://github.com/rails/rails/blob/b738f1930f3c82f51741ef7241c1fee691d7deb2/activerecord/lib/active_record/secure_token.rb) `ActiveRecord::SecureToken` is different from [the master one](https://github.com/rails/rails/blob/master/activerecord/lib/active_record/secure_token.rb)?

The master one allows you to specify length of a token while the v6.0.3 still doesn't.

**Comment by georgeclaghorn** [comment]
The master branch is targeting 6.1.0. 6.0.x are released from the `6-0-stable` maintenance branch.
