### ISSUE TITLE
Need clarification on the underscore in resource url

### ISSUE THREAD

**Issue by Jegannathan** [rails/rails#39306]
> As per "[REST Standard](https://restfulapi.net/resource-naming/) " and  RFC [RFC3986](https://tools.ietf.org/html/rfc3986#appendix-D.2) we should avoid the underscore in resource url right? Why rails still encouraging to use underscore ?Any reason behind this.

**Comment by kaspth** [comment]
We aren’t following the REST standard to the letter and don’t plan to. Anyway, this ship has sailed a long time ago, let’s see if browsers deprecate before we recommend anything different ✌️
