### ISSUE TITLE
Incorrect singular word

### ISSUE THREAD

**Issue by vivekapex** [rails/rails#39315]
### Steps to reproduce

Refer below code. Reflection @class_name not picking correct singular word.
```
2.5.1 :069 > reflection
 => #<ActiveRecord::Reflection::HasManyReflection:0x00007fd184d4d598 @name=:ncd_tranches, @scope=nil, @options={:dependent=>:destroy}, @active_record=ModeOfApplication(id: integer, mode_name: string, created_at: datetime, updated_at: datetime), @klass=nil, @plural_name="ncd_tranches", @type=nil, @foreign_type="ncd_tranches_type", @constructable=true, @association_scope_cache={}, @scope_lock=#<Thread::Mutex:0x00007fd184d4cd28>, @class_name="NcdTranch"> 
2.5.1 :070 > 'ncd_tranches'.singularize
 => "ncd_tranch" 
2.5.1 :071 > 'ncd_tranches'.singularize.classify
 => "NcdTranch" 
```

### Expected behavior
Correct class name or singular word should be _**NcdTranche**_

### Actual behavior
Returning _**NcdTranch**_

### System configuration
**Rails version**: 5.1.4

**Ruby version**: 2.5.1

**Comment by eugeneius** [comment]
See https://github.com/rails/rails/pull/36698, the built-in inflection rules are frozen. You can add the rule to your own application:

https://api.rubyonrails.org/classes/ActiveSupport/Inflector/Inflections.html

**Comment by vivekapex** [comment]
Thanks a lot.
