### ISSUE TITLE
Run rails t with a folder name, not working as expected.

### ISSUE THREAD

**Issue by zw963** [rails/rails#39324]
### Steps to reproduce

Assume we have a folder, `test/scraping/ikyu`, some test file live in it.

Run test with:

```sh
$: rails t test/scraping/ikyu/
```

### Expected behavior
Run only test in folder test/scraping/ikyu/

### Actual behavior
Run all test in test/

But it working when remove trail back slash. e.g.

```sh
$ rails t test/scraping/ikyu # => working as expected
```

### System configuration
**Rails version**:
Rails 5.2.3

**Ruby version**:
ruby 2.6.1p33

**Minitest version**:

```
 ╰─ $ bundle list |grep minitest
  * guard-minitest (2.4.6)
  * minitest (5.14.0)
  * minitest-reporters (1.3.6)
  * minitest-stub_any_instance (1.0.2)
```

**Comment by jonathanhefner** [comment]
Thank you for the issue report!  This was fixed by #38814, which will be included in Rails 6.1.
