### ISSUE TITLE
`with_options` and nested routes broken

### ISSUE THREAD

**Issue by abrom** [rails/rails#39343]
### Steps to reproduce
Example app behaviour testable with: https://gist.github.com/abrom/e939a92604f2e398c10bb012e8e11c8d

In short, it looks like 6.0.3 introduced an issue where nested routes in resources wrapped in `with_options` will result in invalid routes being generated for subsequent resources. In the following example, the 'foo' and 'foo/qux' routes would be generated correctly, however the 'bar' and 'bar/qux' routes are not generated. 
```
  with_options only: %i[show], controller: :tests do
    resource :foo, baz: '123' do
      get :qux
    end
    resource :bar, baz: '456' do
      get :qux
    end
  end
```

If the `with_options` is wrapped in a `scope` block, then both of the routes are generated, however subsequent routes are attributed to the wrong controller. ie `foo` is attributed to the `tests` controller, however `bar` is attributed to a `bars` controller (as if it is not getting the options from the wrapping `with_options` block).
```
scope :tests
  with_options only: %i[show], controller: :tests do
    resource :foo, baz: '123' do
      get :qux
    end
    resource :bar, baz: '456' do
      get :qux
    end
  end
end
```

A bisect showed that [this commit](https://github.com/rails/rails/commit/a55620f3fa89d957817349e5170f686d505eeee4) was the change that altered this behaviour. FYI @kamipo 

### Expected behavior
Without a wrapping scope  (both foo and bar routes exist and are attributed to the `tests` controller
```
$ rails routes | grep tests
qux_foo GET    /foo/qux(.:format)          tests#qux {:baz=>"123", :only=>[:show]}
    foo GET    /foo(.:format)              tests#show {:baz=>"123"}
qux_bar GET    /bar/qux(.:format)          tests#qux {:baz=>"456", :only=>[:show]}
    bar GET    /bar(.:format)              tests#show {:baz=>"456"}
```

With a wrapping scope (both foo and bar routes exist and are attributed to the `tests` controller
```
qux_foo GET    /tests/foo/qux(.:format)          tests#qux {:baz=>"123", :only=>[:show]}
    foo GET    /tests/foo(.:format)              tests#show {:baz=>"123"}
qux_bar GET    /tests/bar/qux(.:format)          tests#qux {:baz=>"456", :only=>[:show]}
    bar GET    /tests/bar(.:format)              tests#show {:baz=>"456"}
```

### Actual behavior
Without a wrapping scope  (the /bar route is not rendered at all)
```
qux_foo GET    /foo/qux(.:format)        tests#qux {:baz=>"123", :only=>[:show]}
    foo GET    /foo(.:format)            tests#show {:baz=>"123"}
```

With a wrapping scope  (the /tests/bar route is rendered, but attributed to the wrong controller)
```
$ rails routes | grep tests
qux_foo GET    /tests/foo/qux(.:format)      tests#qux {:baz=>"123", :only=>[:show]}
    foo GET    /tests/foo(.:format)          tests#show {:baz=>"123"}
qux_bar GET    /tests/bar/qux(.:format)      bars#qux {:baz=>"456", :only=>[:show]}
    bar GET    /tests/bar(.:format)          bars#show {:baz=>"456"}
```

### System configuration
**Rails version**:
6.0.3.1

**Ruby version**:
2.6.5

**Comment by abrom** [comment]
Sorry, I should have also clarified, the following routes will work 'as expected':
```
  with_options only: %i[show], controller: :tests do
    resource :foo, baz: '123'
    resource :bar, baz: '456'
  end
```

It appears to be the introduction of the inner resources specifying blocks to define other sub-routes that is breaking this

**Comment by samstickland** [comment]
I have ran into what I believe is a related issue with `with_options` on 6.0.3. It seems that in 6.0.3 the same hash is passed to all of the methods invoked in the block. For example:

```
with_options virtual: true do |f|
  f.property :name
  f.property :email
end
```

In 6.0.3 the same hash (same object_id) `{virtual: true}` will be passed to both `property` calls, whereas prior to 6.0.3 it was a different hash every time.

If the calls in block mutate the hash the hash, the mutated hash will be passed down the list of calls within the block
