### ISSUE TITLE
#number_to_currency is broken for negative values with custom #to_s

### ISSUE THREAD

**Issue by jaynetics** [rails/rails#39349]
### Steps to reproduce

This happens when using the [money](https://github.com/RubyMoney/money) gem and German locale, which has `,` instead of `.` as separator, but affects simple Strings and maybe other libraries as well.

### Expected behavior
```ruby
number_to_currency('-1,11') # => "$-1,11"
```

### Actual behavior
```ruby
number_to_currency('-1,11') # => "$-1,00"
```

caused by https://github.com/rails/rails/commit/f8cf66caf4b098b4f51a0a75249dde8de9fb8b5b#diff-5713d143cff3211aecc069086bf43071R12

because `"-1,11".to_f == -1`

### System configuration
**Rails version**: 6.0.3.1

**Ruby version**: 2.7

**Comment by Qwertie-** [comment]
Has this actually been fixed? I have tested in the rails console with Rails 6.0.3.4 and the test case in this issue is still broken despite a merged PR to fix it.

**Comment by nikolai-b** [comment]
@Qwertie- it was merged in https://github.com/rails/rails/pull/39350/commits/31575b39ca4d5f8bb7dc1d5cd98dd1e974069259 so you'd need Rails v6.1.0.rc1 or higher
