### ISSUE TITLE
ActiveStorage attach() expecting to return ActiveStorage::Blob

### ISSUE THREAD

**Issue by acetinick** [rails/rails#39352]
### Steps to reproduce

Attach any file using the .attach method provided by ActiveStorage, and it will simply return true or false if saved successfully.

eg.

```
  def create_file
    for file in create_file_params[:attachments]
      @record.attachments.attach(file)
    end
  end
```

### Expected behavior

I expect attach method to return an instance of ActiveStorage::Blob if saved successfully, with generated saved ID of model,  so I can use for additional behaviour.  eg.  Adding event in user timeline.

If unsuccessfully saved, should return nil.

### Actual behavior

attach returns true

### System configuration

Rails 6.0.3
Ruby 2.6.6

**Comment by lukas-conlance** [comment]
This is still an issue in Rails 6.0.3. It would be really helpful to get some identifier after the attachment.

**Comment by acetinick** [comment]
I guess its more of a improvement rather than issue, but yea using 6.0.3.3 and behaviour is same.

**Comment by yorzi** [comment]
I encountered this same issue, but I found there is a solution from this post: https://waynechu.cc/posts/393-activestorage-attach-has-different-return-value-between-v5-and-v6 In case someone wants it.

**Comment by muhammad-sayed-mahdy** [comment]
Why did the behavior change without notice ?
