### ISSUE TITLE
ActiveSupport::KeyGenerator : replace SHA1 by SHA256

### ISSUE THREAD

**Issue by fwininger** [rails/rails#39373]
### Expected behavior

Use FIPS-180 algorithm. In 2020, SHA1 is deprecated due security weakness.

https://github.com/rails/rails/blob/master/activesupport/lib/active_support/key_generator.rb#L23

```diff
    # Returns a derived key suitable for use.  The default key_size is chosen
    # to be compatible with the default settings of ActiveSupport::MessageVerifier.
-   # i.e. OpenSSL::Digest::SHA1#block_length
-   def generate_key(salt, key_size = 64)
-     OpenSSL::PKCS5.pbkdf2_hmac_sha1(@secret, salt, @iterations, key_size)
+   # i.e. OpenSSL::Digest::SHA256#block_lengt
+   def generate_key(salt, key_size = 64, hash= 'SHA256')
+     OpenSSL::KDF.pbkdf2_hmac(@secret, salt: salt, iterations: @iterations, length: key_size, hash: hash)
    end
```

### Actual behavior

This code aren't FIPS-180 compliant

https://github.com/rails/rails/blob/master/activesupport/lib/active_support/key_generator.rb#L23

### System configuration
**Rails version**: 6.X

**Ruby version**: 2.7

**Comment by mhoad** [comment]
Not sure if it is worth reviewing any other instances of SHA-1 usage throughout the code base while we are at it?

https://github.com/rails/rails/search?p=2&q=sha1&unscoped_q=sha1

There looks to be a few but it's not clear to me which ones are potentially problematic.

**Comment by byroot** [comment]
https://github.com/rails/rails/pull/41043 made SHA-256 the default. I believe we can close.
