### ISSUE TITLE
CSP: policy.script_src_elem raise ActionDispatch::ContentSecurityPolicy NoMethodError

### ISSUE THREAD

**Issue by axcr** [rails/rails#39388]
Adding policy.script_src_elem to my csp rules raise ActionDispatch::ContentSecurityPolicy NoMethodError.

### Steps to reproduce
Add policy.script_src_elem to Rails.application.config.content_security_policy

### Expected behavior
Should accept settings.

### Actual behavior
Raise ActionDispatch::ContentSecurityPolicy NoMethodError.

### System configuration
Rails 6.0.3
Ruby 2.7

**Comment by vinistock** [comment]
I believe this has already been added [here](https://github.com/rails/rails/blob/e4b6c719cd1df3dd2bf16645dbe7780dd541ec78/actionpack/lib/action_dispatch/http/content_security_policy.rb#L141), but has not yet been released. Should probably be available in the next Rails release.

**Comment by jonathanhefner** [comment]
Yes, @vinistock is correct.  (Thank you @vinistock!)  This was fixed by #36703, and will be included in Rails 6.1.
