### ISSUE TITLE
in_time_zone giving +08 in place of timezone code for singapore

### ISSUE THREAD

**Issue by mani3522** [rails/rails#39380]
### Steps to reproduce
Time.zone.now.in_time_zone("Singapore")

### Expected behavior
Thu, 21 May 2020 11:30:10 SGT +08:00

### Actual behavior
Thu, 21 May 2020 11:30:10 +08 +08:00

For other timezone we are getting proper value timezone string, for singapore we are getting +08.

### System configuration
**Rails version**: 5.0.7.2

**Ruby version**: 2.3.1

**Comment by jonathanhefner** [comment]
Thank you for the issue, but unfortunately this is out of Rails' control.  See https://github.com/tzinfo/tzinfo/issues/68#issuecomment-290866845 for an explanation (different time zone, but same issue).  It looks like "SGT" was replaced with "+08" by https://github.com/eggert/tz/commit/1b99dcde6342dd10969041b32b00b813d4f4a36e#diff-cffe819d4413b95dd8c35c0085930789R2738.
