### ISSUE TITLE
Rails 4.2.11.3 PDF generation issue: solved

### ISSUE THREAD

**Issue by lesliev** [rails/rails#39381]
Just a heads-up - we were surprised that upgrading from Rails 4.2.11.1 to 4.2.11.3 broke our PDF generation. We construct the ActionView::Base object manually to render HTML for PDFKit.

### Steps to reproduce

We were doing this:
```
def to_pdfkit
  view = ActionView::Base.new(ActionController::Base.view_paths)
  ...
  html = view.render(template: template, layout: 'layouts/pdf', locals: locals)
  PDFKit.new(html)
end
```
And setting `locals` like this:
```
locals = { :@organisation => current_organisation }
```
But after the upgrade, none of those locals were defined in the view any more.

To work around this, we changed to passing the locals like this:
```
def to_pdfkit
  view = ActionView::Base.new(ActionController::Base.view_paths, locals)
  ...
  html = view.render(template: template, layout: 'layouts/pdf')
  PDFKit.new(html)
end
```
And setting `locals` without the `@` like this:
```
locals = { :organisation => current_organisation }
```

### System configuration
**Rails version**: 4.2.11.3

**Ruby version**: 2.5.7

**Comment by rafaelfranca** [comment]
Thank you for the heads-up. This was a security related change, and unfortunately there was no way to avoid this breaking change.
