### ISSUE TITLE
issue installing rails

### ISSUE THREAD

**Issue by caduguedess** [rails/rails#39425]
Seems like it installs but don't recognize after installing.
```
carlos@cadu:~$ gem install rails
Successfully installed rails-6.0.3.1
Parsing documentation for rails-6.0.3.1
Done installing documentation for rails after 0 seconds
1 gem installed
carlos@cadu:~$ rails --version
Command 'rails' not found, but can be installed with:
sudo apt install ruby-railties
```
Should I re-install rails through ruby-railties or it could cause a version conflit?
I installed ruby through asdf
```
[carlos@cadu:~$ which ruby
/home/carlos/.asdf/shims/ruby
carlos@cadu:~$ ruby -v
ruby 2.7.1p83 (2020-03-31 revision a0c7c23c9c) [x86_64-linux]](url)
```
Any advice is appreciated.

**Comment by DaniG2k** [comment]
Try to `cd` into a project with Rails and try again. For example:

```bash
rails new myproject
cd myproject
rails --version
```

I think you're missing the binary when you just call `rails --version` in a random directory, hence the error message.

**Comment by jonathanhefner** [comment]
@caduguedess I don't think this is a Rails issue.  I'm not particularly familiar with asdf-vm / asdf-ruby, but if you run `asdf reshim ruby`, does `rails --version` work?
