### ISSUE TITLE
Enum column is returning integer value instead of string value when plucked from associated object

### ISSUE THREAD

**Issue by akankshajain9290** [rails/rails#39422]
### Steps to reproduce
I have a model Subprocess that has` has_many` association with SpecimensSubprocess model.
SpecimenSubprocess has enum column 
```
enum state: {
    active: 0,
    finished: 1,
    cancelled: 2,
  }
```
Now if I execute `SpecimensSubprocess.where(specimen_id: specimen_ids).pluck(:state)`
Output: ["cancelled", "cancelled"]
But if I execute `subprocess.reload.specimens_subprocesses.where(specimen_id: specimen_ids).pluck(:state)`
Output: [2, 2]

### Expected behavior
On executing `subprocess.reload.specimens_subprocesses.where(specimen_id: specimen_ids).pluck(:state)` should return ["cancelled", "cancelled"]

### System configuration
**Rails version**: 6.0.3.1

**Ruby version**: 2.5.1

**Comment by eugeneius** [comment]
I suspect this is fixed on master via https://github.com/rails/rails/pull/39264. Could you write an executable test case to confirm?

https://guides.rubyonrails.org/contributing_to_ruby_on_rails.html#create-an-executable-test-case

**Comment by chetan-vineti** [comment]
@eugeneius Seems like changes in PR - [#39264](https://github.com/rails/rails/pull/39264/files) are not available in Rails `6.0.3.1`. When can we expect them?

**Comment by kaspth** [comment]
6.1 👍 (though you'd probably want to write the executable test case @eugeneius mentioned or otherwise confirm the fix works for you)

**Comment by akanksha-jain-vineti** [comment]
@eugeneius @kaspth : Please find below the  executable test cas

`require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  # Activate the gem you are reporting the issue against.
  gem "activerecord", "6.0.3.1"
  gem "sqlite3"
  gem "byebug"
end

require "active_record"
require "minitest/autorun"
require "logger"

# This connection will do for database-independent bug reports.
ActiveRecord::Base.establish_connection(adapter: "sqlite3", database: ":memory:")
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :specimens, force: true do |t|
  end

  create_table :subprocesses, force: true do |t|
  end

  drop_table(:specimens_subprocesses, if_exists: true)

  create_join_table :specimens, :subprocesses do |t|
    t.integer :state, default: 0, index: true

    t.index [:specimen_id, :subprocess_id]
    t.index [:subprocess_id, :specimen_id]
  end
end

class Subprocess < ActiveRecord::Base
  has_many :specimens_subprocesses
  has_and_belongs_to_many :specimens
end

class SpecimensSubprocess < ActiveRecord::Base
  belongs_to :subprocess
  belongs_to :specimen

  enum state: {
    active: 0,
    finished: 1,
    cancelled: 2,
  }
end

class Specimen < ActiveRecord::Base
  self.table_name = "specimens"

  has_many :specimens_subprocesses
  has_many :subprocesses, through: :specimens_subprocesses
end


class BugTest < Minitest::Test
  def test_associated_enum_column_stuff
    subprocess = Subprocess.create!
    specimen = Specimen.create!(subprocesses: [subprocess])

    SpecimensSubprocess.where(subprocess_id: subprocess.id).update_all(state: :cancelled)

    assert_equal [2], subprocess.reload.specimens_subprocesses.pluck(:state)

    # for this condition test fails
    assert_equal ['cancelled'], subprocess.reload.specimens_subprocesses.pluck(:state)
  end
end
`

**Comment by akankshajain9290** [comment]
@eugeneius @kaspth : Please find below the  executable test case:
https://gist.github.com/akanksha-jain-vineti/8f3bc5f09ae6a2150ce101fe01201cf0

**Comment by akankshajain9290** [comment]
@kaspth @eugeneius - Please refer this [executable test case](https://gist.github.com/akankshajain9290/488b869dd5ebd92dd4b2ee4245bddf8c)

**Comment by kaspth** [comment]
Nice, then you want to point that at `github: "rails/rails"` which will fetch the master branch, so you can confirm that #39264 does indeed fix your issue.

**Comment by kamipo** [comment]
This is a limitation for `has_and_belongs_to_many`.

`has_and_belongs_to_many` defines an anonymous through association, in this case it will override the `has_many :specimens_subprocesses` definition.

If we have a concrete model for through association, `has_and_belongs_to_many` should not be used.

Recommended fix:

```diff
diff --git a/activerecord/hoge.rb b/activerecord/hoge.rb
index ec3d73b05e..87086f1469 100644
--- a/activerecord/hoge.rb
+++ b/activerecord/hoge.rb
@@ -45,7 +45,7 @@
 
 class Subprocess < ActiveRecord::Base
   has_many :specimens_subprocesses
-  has_and_belongs_to_many :specimens
+  has_many :specimens, through: :specimens_subprocesses
 end
 
 class SpecimensSubprocess < ActiveRecord::Base
```

Works though (because `has_many :specimens_subprocesses` overrride an anonymous through association definition):

```diff
diff --git a/activerecord/hoge.rb b/activerecord/hoge.rb
index ec3d73b05e..a95ff1b56a 100644
--- a/activerecord/hoge.rb
+++ b/activerecord/hoge.rb
@@ -44,8 +44,8 @@
 end
 
 class Subprocess < ActiveRecord::Base
-  has_many :specimens_subprocesses
   has_and_belongs_to_many :specimens
+  has_many :specimens_subprocesses
 end
 
 class SpecimensSubprocess < ActiveRecord::Base
```
