### ISSUE TITLE
Confusion with the installation in getting started doc

### ISSUE THREAD

**Issue by ezezezezez** [rails/rails#39436]
![image](https://user-images.githubusercontent.com/48516031/82900356-fb639000-9f8e-11ea-909f-cbdd1ff1155d.png)
In the Rails Installer page
![image](https://user-images.githubusercontent.com/48516031/82900496-3665c380-9f8f-11ea-8e3b-59e09f97d8f7.png)
Shouldn't this be updated? Or specify the Rails Installer is for quickly installing lower versions of rails and if user wants the newest version of rails they should follow the following installation instructions?
![image](https://user-images.githubusercontent.com/48516031/82901086-04a12c80-9f90-11ea-88f3-8446f89ce4f0.png)

**Comment by eugeneius** [comment]
This was addressed in https://github.com/rails/rails/pull/38662 by recommending [Ruby Installer](https://rubyinstaller.org/) instead. I've backported that change in https://github.com/rails/rails/commit/3f3d767499d240c1bbe75af43a8ef73563167a3f, and the guides site will be updated with the next stable release.
