### ISSUE TITLE
Bring Sprockets back as default

### ISSUE THREAD

**Issue by tdak** [rails/rails#39443]
### Steps to reproduce
rails new {app_name}

### Expected behavior
Rails setup with Sprockets as the default.  

### Actual behavior
 Rails installs webpacker and runs all sorts of unnecessary stuff

### System configuration
Rails 6.x

All ruby versions

### EXPLANATION ###

This whole webpacker business is too awkward.  Everything is a javascript element? CSS and Images are not javascript. Ruby doesn't treat CSS and Images or other files as javascript. 

Keep them separate. Maybe there is a better way to integrate Yarn and nodejs with sprockets.  Even React Developers are starting to turn against it. 

Mixing javascript apps with rails apps is not a good idea. What happened to separation of concerns, microservices architectures, etc.   Mixing javascript and css and images is just not cool people. It's not the Ruby way.  What happened to the being opinionated and tell the world to what you think rather then following some incoherent framework/tool/methodology. 

Rails way of minimal javascript, convention over configuration, Ruby's simplicity and elegant way of doing things. Webpacker and the whole javascript craze is so convoluted and complicated.  Keep things simple, if people want to build javascript apps that live with rails, make it a plugin system, i.e. like a rails engine, where it sits, and lives separately, but still accessible.

**Comment by jeremy** [comment]
Hey @tdak! This is under active discussion in the [May of WTFs](https://weblog.rubyonrails.org/2020/5/7/A-May-of-WTFs/). Check out the thread [here](https://discuss.rubyonrails.org/t/webpacker-presents-a-more-difficult-oob-experience-for-js-sprinkles-than-sprockets-did/75345).
