### ISSUE TITLE
Issue with accepts_nested_attributes_for

### ISSUE THREAD

**Issue by khacluan** [rails/rails#39447]
### Steps to reproduce
I have 2 models

```ruby
class TalkingPointTemplate < ApplicationRecord
  has_many :talking_points, as: :resource, dependent: :destroy

  accepts_nested_attributes_for :talking_points, allow_destroy: true
end

# and

class TalkingPoint < ActiveRecord::Base
  belongs_to :resource, polymorphic: true
end

```
When I try to update a model with its associations, the ActionController::Parameters has merged the new attribute to the old one that doesn't have the content attribute

Please see belove for more detail:

This is the params I submit
```ruby
        {
          talking_point_template: {
            id: 123,
            name: 'Engineering',
            description: 'For devs only',
            talking_points_attributes: [
              { id: 1,  content: "[Updated] How's life outside of work?" },
              { id: 2, _destroy: true },
              { content: 'New question' }
            ]
          }
        }
```

In the controller I will permit the params like this
```ruby
      def update_params
        params.require(:talking_point_template).permit(
          :id,
          :name,
          :description,
          talking_points_attributes: %i[id content _destroy]
        )
      end
```

When I call this `update_params` it returns the unexpected result
Thanks for reading the issue

### Expected behavior
```ruby
<ActionController::Parameters {"id"=>123, "name"=>"Engineering", "description"=>"For devs only", "talking_points_attributes"=>[<ActionController::Parameters {"id"=>1, "content"=>"[Updated] How's life outside of work?"} permitted: true>, <ActionController::Parameters {"id"=>2, "_destroy"=>"true"} permitted: true>, <ActionController::Parameters {"content"=>"New question"} permitted: true>]} permitted: true>
```
### Actual behavior
```ruby
<ActionController::Parameters {"id"=>123, "name"=>"Engineering", "description"=>"For devs only", "talking_points_attributes"=>[<ActionCo
ntroller::Parameters {"id"=>1, "content"=>"[Updated] How's life outside of work?"} permitted: true>, <ActionController::Parameters {"i
d"=>2, "content"=>"New question", "_destroy"=>"true"} permitted: true>]} permitted: true>
```

### System configuration
**Rails version**: Rails 6.0.2.2

**Ruby version**: ruby 2.6.5p114 (2019-10-01 revision 67812) [x86_64-darwin18]

**Comment by piotrj** [comment]
@khacluan I tried to look at your problem but I was unsuccessful with reproducing it. I have a suspicion that the problem is more with the way you send those parameters than there is a bug in rails. Where you successful with reproducing the problem with sending a curl request. If so can you share it?

Also can you say few words on how you end up with this request? Is this an API call or do you do it with a form on a page? If form on a page, how does that form look like.

**Comment by jonathanhefner** [comment]
@piotrj Thank you for trying to reproduce!!

@khacluan Could you create a reproduction script from one of [these templates](https://github.com/rails/rails/tree/master/guides/bug_report_templates) (perhaps [this one](https://github.com/rails/rails/blob/master/guides/bug_report_templates/action_controller_gem.rb))?
