### ISSUE TITLE
Partial matching of redirects with `assert_redirected_to` is broken.

### ISSUE THREAD

**Issue by onlynone** [rails/rails#39446]
### Steps to reproduce

1. Write code that does a redirect to `/a/b` when `/a/c` is requested (where `b` and `c` are actions on the `a` controller).
2. Create a test case asserts a partial redirect match like:
   ```
   assert_redirected_to(controller: "a")
   ```

### Expected behavior

I expected that this assertion should succeeded when a request to `/a/b` is made inside a test, based on the documentation found here:

 * https://guides.rubyonrails.org/testing.html#rails-specific-assertions
 * https://api.rubyonrails.org/v6.0.3.1/classes/ActionDispatch/Assertions/ResponseAssertions.html#method-i-assert_redirected_to
 * https://github.com/rails/rails/blob/db543ba728a9bd38a08f62ebb93ec9eca802a987/actionpack/lib/action_dispatch/testing/assertions/response.rb#L41

All saying:

> Asserts that the redirection options passed in match those of the redirect called in the latest action. **This match can be partial, such that `assert_redirected_to(controller: "weblog")` will also match the redirection of `redirect_to(controller: "weblog", action: "show")` and so on.** You can also pass named routes such as `assert_redirected_to root_path` and Active Record objects such as `assert_redirected_to @article`.

### Actual behavior

It fails with something along the lines of:

```
Minitest::Assertion: Expected response to be a redirect to <https://www.example.com/a/c> but was a redirect to <https://www.example.com/a>.
Expected "https://www.example.com/a" to be === "https://www.example.com/a/c".
```

This is because the partial matching feature was deprecated in: https://github.com/rails/rails/commit/7f1f16c01fd42701747daf9f3399dcdd300125f4

And fully removed in: https://github.com/rails/rails/commit/3900f4007ee6463b8936af23c04017a900673866 . Even though there are [github comments on this last commit](https://github.com/rails/rails/commit/3900f4007ee6463b8936af23c04017a900673866#commitcomment-20606) saying that the feature should have been re-instated. 

### System configuration
**Rails version**:
3.0 to 6.0
**Ruby version**:
2.6

**Comment by jonathanhefner** [comment]
I fixed the documentation in #39462.  Because of the way redirect URLs are matched now, it is unlikely that the old behavior will be brought back.  However, for your use case, I think a regular expression might suffice:

```ruby
assert_redirected_to %r"/a/"
```
