### ISSUE TITLE
strong parameter method expects to define method name as per the controller name

### ISSUE THREAD

**Issue by rhunals** [rails/rails#39459]
### Steps to reproduce
1. Define one parent controller as `LocalityController`
```
class LocalityController < ApplicationController
  def create
    locality = model_name.new(locality_master_params)
    respond_to do |format|
      if locality.save
        format.html { redirect_to locality, notice: 'Record was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

  private
  def model_name
    "#{controller_name.titleize.delete(' ').singularize}".constantize
  end

  def locality_params
    @locality_params = %i|name code status|
  end

  def locality_master_params
    params.require("#{controller_name.singularize}".to_sym).permit(locality_params)
  end
end
```
2. Inherit `StateMastersController` from `LocalityController`
```
class StateMastersController < LocalityController
  private
  def locality_params
    @locality_params = %i|name code status country_code|
  end
end
```
### Purpose
country-state-city controllers should be inherited from one controller and manage same templates, methods for all those controllers to DRY. 

### Expected behavior
It should permit `locality_master_params`

### Actual behavior
It gives `ActiveModel::ForbiddenAttributesError`

It works fine if I write `alias_method :state_master_params, :locality_master_params` in `state_masters_controller.rb`

### System configuration
**Rails version**: 5.2.2.1
**Ruby version**: 2.5.0p0

**Comment by vipulnsward** [comment]
Hi @rhunals can you create a reproduction script using this template: https://github.com/rails/rails/blob/master/guides/bug_report_templates/action_controller_gem.rb, so that it's easier for others to debug.
