### ISSUE TITLE
Asset host should default to default_url options

### ISSUE THREAD

**Issue by Ecco** [rails/rails#39456]
I think `config.action_mailer.asset_host`, when undefined, should default to `config.action_mailer.default_url_options`.

See #34223 for more details.

**Comment by Ecco** [comment]
Yes, it's still reproductible.

**Comment by Ecco** [comment]
Sorry, still reproducible… The state of Rails is sad, really…

**Comment by ghiculescu** [comment]
@Ecco you can use [config.asset_host](https://guides.rubyonrails.org/configuring.html#rails-general-configuration) to set the same `asset_host` for Action Controller and Action Mailer.

```ruby
# config/environments/development.rb

config.asset_host = 'http://assets.example.com'
```

```
% rails c
Running via Spring preloader in process 1012
Loading development environment (Rails 6.0.3.2)
2.7.2 :001 > Rails.application.config.asset_host
 => "http://assets.example.com"
2.7.2 :002 > Rails.application.config.action_controller.asset_host
 => "http://assets.example.com"
2.7.2 :003 > Rails.application.config.action_mailer.asset_host
 => "http://assets.example.com"
```
