### ISSUE TITLE
Calling `associations.new` results in an unexpected change in behavior of `.first`, `.last`

### ISSUE THREAD

**Issue by rovr** [rails/rails#39455]
### Steps to reproduce
```
class Example
  has_many :items
end

class Item
  belongs_to :example
end


example = Example.first

example.items.first 
=> Item Load (1ms)  SELECT "items".* FROM "items" WHERE "items"."example_id" = $1 LIMIT $2  [["example_id", 1], ["LIMIT", 1]`

example.items.new 
example.items.first 
=> Item Load (50ms)  SELECT "items".* FROM "items" WHERE "items"."example_id" = $1  [["example_id", 1]]

```

### Expected behavior
When we call `.first` on an association we expect it to only load a single item.

### Actual behavior
Instead it loads every object in the database that satisfies the criteria and then applies `.first` on the resulting array, leading to a massive memory usage increase.

### System configuration
**Rails version**:
'6.0.2.1'
**Ruby version**:
'2.7.0'

**Comment by alipman88** [comment]
Hmm, I'm noticing there's a test that ensures this behavior in [activerecord/test/cases/associations/has_many_associations_test.rb](https://github.com/rails/rails/blob/master/activerecord/test/cases/associations/has_many_associations_test.rb), (test_calling_first_or_last_on_existing_record_with_build_should_load_association, currently line 2154).

So this appears intentional, or at least it was 12 years ago when that test was [added](https://github.com/rails/rails/commit/73c59638549686fccc749ffd3ac53cb533c5fd61).

I don't quite grasp the reasoning behind this. There may be a valid reason, but I'm not seeing it.

**Comment by kamipo** [comment]
The reason for is that target records are considered as `[persisted records, on-memory records]`.

So we could change to avoid loading records for the `.last` if on-memory records exists, but for the `.first`, it will change the behavior if loading records is avoided.

**Comment by rovr** [comment]
>but for the .first, it will change the behavior if loading records is avoided.

Could we load a single record as well, so that at least for the `.first` and `.last` the target records are [first persisted record, last on-memory record]? 

The lack of `LIMIT 1` on that `.first` was a real memory killer for us and took quite some time to figure out. The code looked fine and worked fine in dev, but in prod was loading hundreds of thousands of large objects in some cases. Everything still worked, but with x3 memory usage. Ours is probably an extreme case with a lot of heavy objects, so it makes me wonder how many more people are getting caught by this `.new` - `.first`/`.last` combo without even knowing.

**Comment by alipman88** [comment]
Maybe we can preserve the existing behavior without loading an entire dirty association by passing new records to `.find_nth_with_limit`, and pad them to that method's result as needed to reach the limit.

Something like this very rough draft: https://github.com/alipman88/rails/commit/183d94bf7526f17b6ed5b8f286ee159187397fd3

Breaks a couple tests for dirty associations with modified, non-new records, but I have a hunch that can be rectified and the behavior could be extended to other methods in collection_proxy.rb that follow the `load_target if find_from_target?` pattern.

Could be a dead end, but I plan on exploring this a little further.
