### ISSUE TITLE
Rails 5.2.4.3 broke our ActiveStorage direct uploads to S3

### ISSUE THREAD

**Issue by ajporterfield** [rails/rails#39451]
### Steps to reproduce

We attempted to update Rails from 5.2.4.2 to 5.2.4.3 last Thursday, but had to rollback b/c it broke our ActiveStorage direct uploads.

### Expected behavior

ActiveStorage direct uploads to S3 that work in 5.2.4.2 should continue to work in 5.2.4.3.

### Actual behavior

In the js console, we get this error "POST https://our.appsdomain.com/rails/active_storage/direct_uploads 500"

We use Honeybadger for exception handling, and the specific error we're getting on the server is "ArgumentError in active_storage/direct_uploads # create" with the message "ArgumentError: unexpected value at params[:whitelist_headers]"

Here's a screenshot of the backtrace...
<img width="1112" alt="Screen Shot 2020-05-27 at 12 05 44 PM" src="https://user-images.githubusercontent.com/2551544/83044656-77eb8280-a012-11ea-8749-b915aebd60de.png">

Here are the params...
<img width="661" alt="Screen Shot 2020-05-27 at 12 15 15 PM" src="https://user-images.githubusercontent.com/2551544/83045598-c77e7e00-a013-11ea-959a-5b72e9604f63.png">

We are using aws-sdk-core (3.95.0) and aws-sdk-s3 (1.17.1).

I'm assuming it has something to do with https://groups.google.com/forum/#!topic/rubyonrails-security/PjU3946mreQ.

### System configuration
**Rails version**: 5.2.4.3

**Ruby version**: 2.3.8

**Comment by eugeneius** [comment]
This was addressed in https://github.com/rails/rails/pull/39355, which I've just backported to 5-2-stable in https://github.com/rails/rails/commit/92fd1c202bc6cdb945c110b23f9879de0fbd9b0e. Rails 5.2 is only receiving security maintenance though, so there may never be another bugfix release.

You can fix this in your own app by upgrading the aws-sdk-s3 gem 1.48.0 or greater.

**Comment by ajporterfield** [comment]
Thanks @eugeneius!  Upgrading aws-sdk-s3 worked.
