### ISSUE TITLE
enum type cast not working with nested conditions

### ISSUE THREAD

**Issue by viveksoundrapandy** [rails/rails#39460]
Reopening https://github.com/rails/rails/issues/34639 as its closed due to inactivity but the issue persists

**Steps to reproduce**
Given the following models
```

class Topic < ActiveRecord::Base
  has_many :posts
end

class Post < ActiveRecord::Base
  belongs_to :topic
  has_many :comments
end

class Comment < ActiveRecord::Base
  belongs_to :post
  enum state: %i[ hidden visible ]
end
```
if I try to query topics with hidden comments

Topic.joins(posts: :comments).where(comments: { state: :hidden })
it does not type cast the enum value, so I get

SELECT "topics".* FROM "topics"
INNER JOIN "posts" ON "posts"."topic_id" = "topics"."id"
INNER JOIN "comments" ON "comments"."post_id" = "posts"."id"
WHERE "comments"."state" = 'hidden'
**Expected behavior**
The value of the enum column should be type casted to its database value (0) resulting in a query with where clause like this:

SELECT ... WHERE "comments"."state" = 0
**Actual behavior**
It does not type cast the value of the enum column resulting in a where clause:

`SELECT ... WHERE "comments"."state" = 'hidden'
`The more interesting is that if Topic has a has_many :comments, through: :posts relation, it makes the whole thing work, so not only

`Topic.joins(:comments).where(comments: { state: :hidden })
`but even

`Topic.joins(posts: :comments).where(comments: { state: :hidden })
`has the correct sql query generated.

From what it seems to me that type casting the value of the enum column works only if the target model (Topic) has an own relation with the queried model (Comment).

**System configuration**
Rails version: 5.2.4 (its happening 6 as well)

Ruby version: 2.6

**Comment by viveksoundrapandy** [comment]
@kamipo is the fix for rails 6 only or for 5-2-stable as well?

**Comment by kamipo** [comment]
Only for 6.1, since it relies on several refactorings on master.
