### ISSUE TITLE
Possible bug with new delegated_type pattern

### ISSUE THREAD

**Issue by mhoad** [rails/rails#39471]
### Steps to reproduce
I was playing around with the new [delegated_type pattern](https://github.com/rails/rails/blob/62288e55a4aa47b17fda0810102c8a19084e5764/activerecord/lib/active_record/delegated_type.rb) and I came across some strange behavior.

The models involved are defined as follows:

**schema.rb** [Actual File](https://github.com/mhoad/activitypub-rails/blob/master/db/schema.rb)
```ruby
create_table "activity_streams_objects_actors_actors", id: :uuid, default: -> { "gen_random_uuid()" }, force: :cascade do |t|
  t.string "type"
  t.datetime "created_at", precision: 6, null: false
  t.datetime "updated_at", precision: 6, null: false
end

create_table "activity_streams_objects_objects", id: :uuid, default: -> { "gen_random_uuid()" }, force: :cascade do |t|
  t.string "objectable_type", null: false
  t.integer "objectable_id", null: false
  t.string "content"
  t.string "name"
  t.datetime "created_at", precision: 6, null: false
  t.datetime "updated_at", precision: 6, null: false
end
```
**actor.rb** [Actual File](https://github.com/mhoad/activitypub-rails/blob/master/app/models/activity_streams/objects/actors/actor.rb)
```ruby
module ActivityStreams
  module Objects
    module Actors
      # Represents an individual person. 
      # https://www.w3.org/ns/activitystreams#Person
      class Person < Actor
        
      end
    end
  end
end
```
**object.rb** [Actual File](https://github.com/mhoad/activitypub-rails/blob/master/app/models/activity_streams/objects/object.rb)
```ruby
module ActivityStreams
  module Objects
    # Describes an object of any kind. The Object type serves as the base 
    # type for most of the other kinds of objects defined in the 
    # Activity Vocabulary, including other Core types such as Activity, 
    # IntransitiveActivity, Collection and OrderedCollection. 
    class Object < ApplicationRecord
      delegated_type :objectable, 
        types: %w[ 
          ActivityStreams::Objects::Actors::Actor 
          ActivityStreams::Objects::Activities::Activity 
        ], 
        dependent: :destroy
    end
  end
end
```

**objectable.rb**  [Actual File](https://github.com/mhoad/activitypub-rails/blob/master/app/models/concerns/activity_streams/objects/objectable.rb)
```ruby
module ActivityStreams
  module Objects
    module Objectable
      extend ActiveSupport::Concern
    
      included do
        has_one :object, as: :objectable, touch: true
      end
    end
  end
end
```

When attempting to verify these links in the Rails console I am able to get the `objectable` reference on an `Object` depending on how I access it and I can't tell if I am doing something wrong or this is a bug.

### Expected behavior
Inside of the Rails console:
```ruby
# Create an actor object
my_actor = ActivityStreams::Objects::Object.create!(
objectable: ActivityStreams::Objects::Actors::Actor.new, 
name: "Joe Blogs"
)

# Can get the Actor object through the Base object using the objectable method
my_actor.objectable
#<ActivityStreams::Objects::Actors::Actor id: "e086cae3-758e-4c7e-87e1-c548e8b0bda5", type: nil, created_at: "2020-05-29 12:46:00.589145000 +0000", updated_at: "2020-05-29 12:46:00.589145000 +0000">

# Can lookup the base object and expect the same result from Objectable
ActivityStreams::Objects::Object.find(my_actor.id).objectable
#<ActivityStreams::Objects::Actors::Actor id: "e086cae3-758e-4c7e-87e1-c548e8b0bda5", type: nil, created_at: "2020-05-29 12:46:00.589145000 +0000", updated_at: "2020-05-29 12:46:00.589145000 +0000">
```

### Actual behavior
Inside of the Rails console:
```ruby
# Create an actor object
my_actor = ActivityStreams::Objects::Object.create!(
objectable: ActivityStreams::Objects::Actors::Actor.new, 
name: "Joe Blogs"
)

# Can get the Actor object through the Base object using the objectable method
my_actor.objectable
#<ActivityStreams::Objects::Actors::Actor id: "e086cae3-758e-4c7e-87e1-c548e8b0bda5", type: nil, created_at: "2020-05-29 12:46:00.589145000 +0000", updated_at: "2020-05-29 12:46:00.589145000 +0000">

# Can lookup the base object and expect the same result from Objectable
ActivityStreams::Objects::Object.find(my_actor.id).objectable
# => nil
```
**Colorized Logging of Actual Output**
<img width="1107" alt="Screen Shot 2020-05-29 at 2 20 11 pm" src="https://user-images.githubusercontent.com/133005/83264124-8f17a500-a1b7-11ea-925a-e016ac052187.png">

### System configuration
**Rails version**: 6.1.0.alpha

**Ruby version**: 2.7.1

**Comment by mcgregordan** [comment]
I think this is a problem resulting from using uuids as primary keys, not a bug.

I don’t use uuid keys, but is the problem that in 'ActivityStreams::Objects::Object' you have `objectable_id` as an integer but the id that it’s actually passed isn’t an integer but a uuid? Your console screenshot suggests what’s passed as `objectable_id` in the database query is nil.

Anyway, I couldn’t reproduce this in a sample app (using boring old integers as ids).
