### ISSUE TITLE
Enabling connection pooling on RedisCacheStore requires overriding/repeating default values

### ISSUE THREAD

**Issue by bbugh** [rails/rails#39479]
### Steps to reproduce

In the [edge guides for "Caching with Rails"](https://edgeguides.rubyonrails.org/caching_with_rails.html#connection-pool-options) it says that to enable connection pooling for redis, you have to specify `pool_size` and/or `pool_timeout`, and that the default values for each is `5`.

It appears that the only way to actually enable connection pooling is to specify one or both of these values, even though the convention defaults are sensible values. It might be better to have a way to enable connection pooling that doesn't require specifying values that are already defined.

```ruby
config.cache_store = :redis_cache_store, {
   # no pool settings, so it won't use the connection pool
}
```

```ruby
config.cache_store = :redis_cache_store, {
   pool_size: 5 # but this is the default value, don't set it again!
}
```

Looking up the pool options returns an empty hash if neither of those values are set:

https://github.com/rails/rails/blob/a5d1628c79ab89dfae57ec1e1aeca467e29de188/activesupport/lib/active_support/cache.rb#L168-L173

And in the redis cache store code, it checks if the hash of options is empty, which it is if neither value is set:

https://github.com/rails/rails/blob/9b4aef4be3dc58eb08f694387857b52be8050954/activesupport/lib/active_support/cache/redis_cache_store.rb#L185-L192

So no connection pooling. :(

### Expected behavior

Connection pooling can be enabled without having to override the defaults. Perhaps a `pool` option that can either be a boolean or an options hash? 

```ruby
# just turn on connection pooling

config.cache_store = :redis_cache_store, {
   pool: true
}

# OR set specific options

config.cache_store = :redis_cache_store, {
  pool: {
    size: 8, # now I can override
    timeout: 15 # and override
  }
}
```

### Actual behavior

I have to override the defaults to enable connection pooling!

### System configuration
**Rails version**: 6.0.3.1

**Ruby version**: 2.6.5

**Comment by eugeneius** [comment]
`pool: true` sounds like a clear improvement, if you want to work on a patch. 👍 

Passing pool options as a nested hash would be more coherent with `pool: true`, but we'd have to consider existing apps: do we deprecate the top level options? What happens if I set both, but to different values? If that stuff doesn't get too hairy though, it sounds like a good idea too.

**Comment by tgxworld** [comment]
@eugeneius Actually I think being intentional here at least with the pool size is a good thing. When used in the context of puma, the pool size should at least be equal to the number of puma threads. Perhaps the docs should be updated instead to recommend the pool size to use based on the user’s configuration?

**Comment by jon-sully** [comment]
Ran into this one in an older Rails app that never implemented pooling; not sure what the right answer is here (enabled and configured by default? called out? etc.) but it's pretty tricky to trace down that _this_ may be the underlying issue when using Rails Cache _without_ the pooling enabled. Not sure I have a constructive, direction-based comment (sorry!) but would like to see some movement here for the betterment of the community :)

**Comment by fatkodima** [comment]
That was an oversight from my side in https://github.com/rails/rails/pull/31447. I would like to improve this and + for memcached adapter too.
@byroot Wdyt on this? Yay or nay?

**Comment by byroot** [comment]
@fatkodima not too sure what you have in mind exactly, but yes it would be good to have both of those default to `RAILS_MAX_THREADS` like Active Record's connection pool.

**Comment by fatkodima** [comment]
@byroot I mean instead of `pool_size` and `pool_timeout` to have `pool: true` or `pool: { size: something, timeout: something }` - like structure. 

Like described in the issue, currently to use pooling, we need to override (repeat) the defaults.

**Comment by byroot** [comment]
Ah I see. Yes go ahead.
