### ISSUE TITLE
Invalid cache results of Active Record records

### ISSUE THREAD

**Issue by koenpunt** [rails/rails#39486]
### Steps to reproduce

I don't know if this is consistently reproducible, but I like to bring this issue under attention to see if someone knows what's going on.

My Rails (6.0.3.1) application has a controller:

```ruby
class TagsController < ApplicationController

  # ...

  def batch
    ids = params.require(:ids).split(',').sort
    @tags = Rails.cache.fetch(['tags-batch', ids], expires_in: 1.day) do
      Tag.where('id IN(?)', ids).load
    end
    respond_with @tags
  end
end
```

With the following views:

```jbuilder
# batch.json.jbuilder
json.cache! @tags do
  json.tags @tags, partial: 'tags/tag', as: :tag
end

# _tag.json.jbuilder
json.extract! tag, :id, :body, :slug
```

And since the tag ids in this batch call are arbitrary, I've added the `Rails.cache` block around it.

### Expected behavior

It should render a JSON object like:

```json
{
  "tags": [
    {
      "id": 2171,
      "body": "mislukt",
      "slug": "mislukt"
    },
    {
      "id": 2961,
      "body": "maandag",
      "slug": "maandag"
    },
    {
      "id": 8791,
      "body": "fail",
      "slug": "fail"
    }
  ]
}
```

### Actual behavior

It sometimes resulted in (note the `null` for `id`):

```json
{
  "tags": [
    {
      "id": null,
      "body": "mislukt",
      "slug": "mislukt"
    },
    {
      "id": null,
      "body": "maandag",
      "slug": "maandag"
    },
    {
      "id": null,
      "body": "fail",
      "slug": "fail"
    }
  ]
}
```

Since this is running with multiple instances I'm not entirely sure if this is only happening on a single instance, but what I do know, is that when I remove the `Rails.cache` block, it works as expected.

### System configuration
**Rails version**: 6.0.3.1

**Ruby version**: 2.6.5p114

**Comment by eugeneius** [comment]
Can you create a sample application that reproduces the issue?

From a quick first look, the issue might be passing a relation to Jbuilder's `cache!` method.

**Comment by koenpunt** [comment]
After having the code running for sometime without using `Rails.cache` in the controller, the problem arises again. 

>  the issue might be passing a relation to Jbuilder's `cache!` method.

But that is supposed to work, passing a relation to Jbuilder's `cache!` method, right?

**Comment by koenpunt** [comment]
I'll see if I can make a same app with reproduction, but I think it's going to be difficult, since it is intermittent..
