### ISSUE TITLE
Query cache not taking schema_search_path into account

### ISSUE THREAD

**Issue by NielsKSchjoedt** [rails/rails#39508]
### Steps to reproduce
1. Create an postgresql database with two schemas (`a` and `b`) which holds a table (`my_table`) with the same name in each schema. 
2. Insert a different amount of records in each table.
3. Then run a query against table in one schema e.g. 
`connection.schema_search_path=a`
`connection.execute('SELECT count(*) from my_table')`
4. Then change the search path for the connection like so : `connection.schema_search_path=b` and run the same query: `connection.execute('SELECT count(*) from my_table')`

### Expected behavior
It should return two different counts

### Actual behavior
It returns the same count (from table `a.my_table`) for both queries.

### System configuration
**Rails version**: 5.2.4.2
**Ruby version**: 2.6.5

### Suggestion
It should either `connection.clear_query_cache` on calling `connection.schema_search_path=` (I think that's the best) or alternatively include the `connection.schema_search_path` in the query cache key.

My suggestion:

```ruby
def schema_search_path=(schema_csv)
   if schema_csv
     execute("SET search_path TO #{schema_csv}", "SCHEMA")
     clear_query_cache if @query_cache_enabled
     @schema_search_path = schema_csv
  end
end
```

**Comment by vipulnsward** [comment]
From documentation https://github.com/rails/rails/blob/1944a7e74c6c1b7a6234414a00d294412c05fde1/activerecord/lib/active_record/connection_adapters/postgresql/schema_statements.rb#L223

AFAICT this is not supposed to be called manually.

We can add `clear_query_cache` to fix the issue you mentioned(or you can manually call the clear cache), but not sure if it would add a 100% support for this usage.

**Comment by NielsKSchjoedt** [comment]
Well, Yes, it's not mean to be called manually, but if you use a multi-tenancy strategy using postgresql (like the one https://github.com/influitive/apartment provides), this is the way it's done for 1000s of people. So, I suggest we do that. Should I submit a PR?

**Comment by tgxworld** [comment]
It seems like apartment handles clearing the query cache? 

https://github.com/influitive/apartment/blob/5585dac0665d44b29369bedd8f02cd61e64fdd46/lib/apartment/adapters/abstract_adapter.rb#L72

**Comment by NielsKSchjoedt** [comment]
Yeah, but that should be an external responsibility, should it, I mean, would there EVER be a reason why query cache should not get cleared when changing search_path in postgresql?

**Comment by tgxworld** [comment]
I think the problem here is that the `schema_search_path=` method was not designed to be called manually and it is only called whenever a new PG connection is being made. Also, the `query_cache` is present at the connection level so `clear_query_cache` will probably not be sufficient, it'll have to clear the `query_cache` of all the connections in the connection pool like so

https://github.com/rails/rails/blob/master/activerecord/lib/active_record/connection_handling.rb#L198-L204

**Comment by NielsKSchjoedt** [comment]
Hmm, interesting. However the statement "was not designed for" seems a bit odd, since it's a public method and can perfectly be invoked on the connection outside initialization so why not just clear that cache?
