### ISSUE TITLE
Query cache not getting reset between requests

### ISSUE THREAD

**Issue by NielsKSchjoedt** [rails/rails#39510]
### Steps to reproduce
After upgrading to rails 5.2 from rails 4.2 we have encountered this: https://github.com/rails/rails/issues/39508 However that should not have been an issue in the first place, because we only change `schema_search_path=` in a rack middleware based on the domain name on each request. In rails 4.2 Active record query cache seems to get cleared on every request, however that does not seem to be the case in rails 5.2 - isn't that a bug?

### Expected behavior
Query cache should be cleared between web requests (no persistence between two separate requests)

### Actual behavior
We see the query cache being invoked across requests.

### System configuration
**Rails version**: 2.6.5
**Ruby version**: 5.2.4.2
We are using unicorn:  5.5.4

**Comment by NielsKSchjoedt** [comment]
https://github.com/rails/rails/issues/39508

**Comment by tgxworld** [comment]
Hi can you confirm or reproduce if this is the case? I investigated a little and it does not seem like this has regressed. 

https://github.com/rails/rails/blob/661da266b94909574426fd1121ef13b800e01b9a/activerecord/lib/active_record/query_cache.rb#L28-L50

**Comment by vikasnair** [comment]
@NielsKSchjoedt have you figured out this issue?

I’m also upgrading from rails 4.2 to 5.2 + on Unicorn, and seeing same behavior of active record query cache seemingly not clearing between actions

**Comment by NielsKSchjoedt** [comment]
@vikasnair See the link to the issue in my description. Apparently for the use case we had, rails was not designed to do this automatically on models where we have changed e.g. the search path. So we ended up doing it manually instead on those connections
