### ISSUE TITLE
10.1 Custom credentials from docs result in "key=': key must be 16 bytes"

### ISSUE THREAD

**Issue by thebravoman** [rails/rails#39528]
### Steps to reproduce
Go to https://guides.rubyonrails.org/security.html#custom-credentials
Text there is 
```
To add new secret to credentials, first run rails secret to get a new secret. Then run rails credentials:edit to edit credentials, and add the secret. Running credentials:edit creates new credentials file and master key, if they did not already exist.
```
So i run them and I get an error.

```
$ rails secret
f1b304c646d5d5fd525875c3eb520b946afe0fa6ae2552467fd7a5c89ddd3a946c8a23aaf0c9639f714d46070f15c8ced4c130853f4908db519bb5b34debc18e
$ EDITOR="nano --wait" bin/rails credentials:edit
Traceback (most recent call last):
  28: from bin/rails:3:in `<main>'
  27: from bin/rails:3:in `load'
  26: from /home/user/project/bin/spring:15:in `<top (required)>'
  25: from /home/user/.rvm/rubies/ruby-2.6.5/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
  24: from /home/user/.rvm/rubies/ruby-2.6.5/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
  23: from /home/user/.rvm/gems/ruby-2.6.5/gems/spring-2.1.0/lib/spring/binstub.rb:11:in `<top (required)>'
  22: from /home/user/.rvm/gems/ruby-2.6.5/gems/spring-2.1.0/lib/spring/binstub.rb:11:in `load'
  21: from /home/user/.rvm/gems/ruby-2.6.5/gems/spring-2.1.0/bin/spring:49:in `<top (required)>'
  20: from /home/user/.rvm/gems/ruby-2.6.5/gems/spring-2.1.0/lib/spring/client.rb:30:in `run'
  19: from /home/user/.rvm/gems/ruby-2.6.5/gems/spring-2.1.0/lib/spring/client/command.rb:7:in `call'
  18: from /home/user/.rvm/gems/ruby-2.6.5/gems/spring-2.1.0/lib/spring/client/rails.rb:28:in `call'
  17: from /home/user/.rvm/gems/ruby-2.6.5/gems/spring-2.1.0/lib/spring/client/rails.rb:28:in `load'
  16: from /home/user/project/bin/rails:9:in `<top (required)>'
  15: from /home/user/project/bin/rails:9:in `require'
  14: from /home/user/.rvm/gems/ruby-2.6.5/gems/railties-6.0.3.1/lib/rails/commands.rb:18:in `<top (required)>'
  13: from /home/user/.rvm/gems/ruby-2.6.5/gems/railties-6.0.3.1/lib/rails/command.rb:46:in `invoke'
  12: from /home/user/.rvm/gems/ruby-2.6.5/gems/railties-6.0.3.1/lib/rails/command/base.rb:69:in `perform'
  11: from /home/user/.rvm/gems/ruby-2.6.5/gems/thor-1.0.1/lib/thor.rb:392:in `dispatch'
  10: from /home/user/.rvm/gems/ruby-2.6.5/gems/thor-1.0.1/lib/thor/invocation.rb:127:in `invoke_command'
   9: from /home/user/.rvm/gems/ruby-2.6.5/gems/thor-1.0.1/lib/thor/command.rb:27:in `run'
   8: from /home/user/.rvm/gems/ruby-2.6.5/gems/railties-6.0.3.1/lib/rails/commands/credentials/credentials_command.rb:30:in `edit'
   7: from /home/user/.rvm/gems/ruby-2.6.5/gems/railties-6.0.3.1/lib/rails/commands/credentials/credentials_command.rb:62:in `ensure_credentials_have_been_added'
   6: from /home/user/.rvm/gems/ruby-2.6.5/gems/railties-6.0.3.1/lib/rails/generators/rails/credentials/credentials_generator.rb:30:in `add_credentials_file_silently'
   5: from /home/user/.rvm/gems/ruby-2.6.5/gems/activesupport-6.0.3.1/lib/active_support/encrypted_configuration.rb:29:in `write'
   4: from /home/user/.rvm/gems/ruby-2.6.5/gems/activesupport-6.0.3.1/lib/active_support/encrypted_file.rb:50:in `write'
   3: from /home/user/.rvm/gems/ruby-2.6.5/gems/activesupport-6.0.3.1/lib/active_support/encrypted_file.rb:76:in `encrypt'
   2: from /home/user/.rvm/gems/ruby-2.6.5/gems/activesupport-6.0.3.1/lib/active_support/message_encryptor.rb:151:in `encrypt_and_sign'
   1: from /home/user/.rvm/gems/ruby-2.6.5/gems/activesupport-6.0.3.1/lib/active_support/message_encryptor.rb:169:in `_encrypt'
/home/user/.rvm/gems/ruby-2.6.5/gems/activesupport-6.0.3.1/lib/active_support/message_encryptor.rb:169:in `key=': key must be 16 bytes (ArgumentError)

```

### Expected behavior
Probably more information in the documentation on why such an error might occur, and how to resolve it. 

### Actual behavior
Just looking at the documentation results in an error.

I found https://github.com/rails/rails/issues/33528 which is closed with suggestion to ask at stackoverflow, but it is not making clear how and why the error occurs and it is not clear from the documentation which is this issue. 

Running with 
```
$ RAILS_MASTER_KEY=b4a9730f5bb1cc962e23a6fb97138af7b462af34ca5436b729b62b4470b0a73965e0eec7b9aeca734e5b2ce90d9376fdf9365b4107b4fd730ba3a088de710887 EDITOR="nano --wait" bin/rails credentials:edit
```
again returns a result - note that this is as the documentation suggest - run rails secret and them rails credentials:edit so probably you should use the secret as a credential

Running as
```
$ RAILS_MASTER_KEY=b4a9730f5bb1cc96 EDITOR="nano --wait" bin/rails credentials:edit
```
because I though - let's make it 16 symbols - again is an error

Tried also with 8. 

Tried with adding similar values to config/master.key as mentioned in the documentation but with no success. 

I have tried to debug it and there is value that is reaching the message_encryptor
```
.rvm/gems/ruby-2.6.5/gems/activesupport-6.0.3.1/lib/active_support/message_encryptor.rb
   165:     private
   166:       def _encrypt(value, **metadata_options)
   167:         cipher = new_cipher
   168:         cipher.encrypt
   169:         byebug
=> 170:         cipher.key = @secret
   171: 
   172:         # Rely on OpenSSL for the initialization vector
   173:         iv = cipher.random_iv
   174:         cipher.auth_data = "" if aead_mode?
(byebug) @secret
"h\x9Ad\xF1"
(byebug) 
```
But how do I make this value 16 bytes is unclear.

### System configuration
**Rails version**: 6.0.3.1

**Ruby version**: 2.6.5

**Comment by jonathanhefner** [comment]
At first, I could not reproduce this because I was confused about the circumstances.  It turns out this specific error only occurs when master key is set with an invalid length *and there is no credentials file*.  When the credentials file *does exist*, a friendly "Couldn't decrypt config/credentials.yml.enc. Perhaps you passed the wrong key?" error is shown.

I've created #39554 to improve the error message in the original scenario.  I've also created #39553 to clarify that running `rails secret` is not necessary to generate either `config/credentials.yml.enc` nor `config/master.key`.

> I guess the config/master.key was invalid/corrupt, but now we've lost the credentials as we don't have the master key.

@thebravoman  I don't believe that is the case.  I think what happened is that you manually created `config/master.key`, but did not have a `config/credentials.yml.enc` yet.  When you ran `rails credentials:edit`, Rails could not use the specified key to generate a new `config/credentials.yml.enc`, resulting in the error you reported.  Can you verify?

**Comment by thebravoman** [comment]
I also think the master key was somehow available for this project. Despite
all the notes of.not commiting this file it was committed and I did not
expect that.

I can confirm there was a master key.
