### ISSUE TITLE
number_to_human_size(2861) gives undefined method `new' for BigDecimal:Class

### ISSUE THREAD

**Issue by Znow** [rails/rails#39576]
### Steps to reproduce
Use the "number_to_human_size" helper in a view, and ie. with "2861" as value.

Then try to just have "286" as value, and it then outputs "286 Bytes" correctly.

### Expected behavior
Should print out the correct translated output

### Actual behavior
undefined method `new' for BigDecimal:Class

### System configuration
**Rails version**:
5.1.7
**Ruby version**:
2.4.10

**Comment by jonathanhefner** [comment]
Thank you for the issue, but Rails 5.1 is no longer supported (per Rails' [maintenance policy](https://guides.rubyonrails.org/maintenance_policy.html)), and I could not reproduce this issue on master.

However, you might try verifying that you are actually running on Ruby 2.4 (e.g. by inspecting the `RUBY_VERSION` constant in your app).  `BigDecimal.new` was deprecated in Ruby 2.6 and removed in Ruby 2.7, but it should still be defined in Ruby 2.4.
