### ISSUE TITLE
Unexpected behaviour when calling Class.any?(&:method) when method uses has_many association

### ISSUE THREAD

**Issue by xDavan** [rails/rails#39572]
### Steps to reproduce

I created a project that reproduces the issue [here](https://github.com/xDavan/testapp), but I put the main parts of the code below. I originally tested this issue in Rails version 5.1.7, but upgraded to 6.0.3.1 and the issue is still present.

```
class WelcomeController < ApplicationController
  def index
    Article.any?(&:find_citation)
    puts 'Will this execute'
  end
end
```

```
class Article < ApplicationRecord
  has_many :citations

  def find_citation
    citations.where(text: 'another test text')
  end
end
```

Articles
`#<ActiveRecord::Relation [#<Article id: 1, title: "Why", text: "test text", created_at: "2020-06-05 20:52:32", updated_at: "2020-06-05 20:52:32">]>`

Citations
`#<ActiveRecord::Relation [#<Citation id: 1, article_id: 1, text: "another test text">]>`

### Expected behavior
It should render the welcome page and print "Will this execute" in the console without having to refresh the page.

### Actual behavior
It does not render the welcome page and it does not print "Will this execute" in the console. If the page is refreshed, it will render the welcome page and print "Will this execute".

**Observations:**
* calling `Article.any?(&:find_citation)` in the console for the first time will not return anything. calling it again will return `true` as expected
* calling `Article.any? { |article| article.find_citation }` will return `nil`, which is wrong, but it will still render the page and print the string without having to refresh.
* replacing `citations.where(...)` with `Citation.where(article_id: id, text: 'another test text')` will result in the expected behavior
* replacing `Article.any?(...)` with `Article.all.to_a.any?(...)` will result in the expected behavior

### System configuration
**Rails version**: 5.1.7 and 6.0.3.1

**Ruby version**: 2.5.1

**Comment by eugeneius** [comment]
This looks like a duplicate of https://github.com/rails/rails/issues/33625. Does upgrading to Ruby 2.5.4 or greater fix it?

**Comment by xDavan** [comment]
> This looks like a duplicate of #33625. Does upgrading to Ruby 2.5.4 or greater fix it?

Upgrading Ruby past 2.5.4 worked. Thank you.
