### ISSUE TITLE
ActiveRecord::Base#with_lock opening transaction with options

### ISSUE THREAD

**Issue by bvicenzo** [rails/rails#39579]
Here https://github.com/rails/rails/pull/4531 was added the method ActiveRecord::Base#with_lock.

However, it always creates a [transaction](https://github.com/rails/rails/blob/34991a6ae2fc68347c01ea7382fa89004159e019/activerecord/lib/active_record/connection_adapters/abstract/database_statements.rb#L273) using the default options.

Is it possible to add an optional param to this method to receive transaction options

### Expected behavior
```rb
class Order < ActiveRecord::Base
  def cancel!
    with_lock(true, isolation: :serializable) do
      # ... cancelling logic
    end
  end
end
```
Or...
```rb
class Order < ActiveRecord::Base
  def cancel!
    with_lock(true, transaction_options: { isolation: :serializable }) do
      # ... cancelling logic
    end
  end
end
```

### Actual behavior
```rb
class Order < ActiveRecord::Base
  def cancel!
    with_lock do
      # ... cancelling logic
    end
  end
end
```

**Comment by simi** [comment]
AFAIK with_lock will reuse transaction if currently in transaction block:

```ruby
irb(main):006:0> u = User.first
=> #<User id: 1, first_name: "Dev", last_name: "User", account_id: 1, email: "user@example.com", 
irb(main):007:0> u.transaction(isolation: :serializable) { u.with_lock { }}
=> nil
```

```
  User Load (0.9ms)  SELECT "users".* FROM "users" ORDER BY "users"."id" ASC LIMIT $1 /*application:Reporting*/  [["LIMIT", 1]]
created_at: "2020-06-08 09:15:44", updated_at: "2020-06-08 09:15:44", time_zone: nil>
   (0.5ms)  BEGIN /*application:Reporting*/
   (0.4ms)  SET TRANSACTION ISOLATION LEVEL SERIALIZABLE /*application:Reporting*/
  User Load (1.5ms)  SELECT "users".* FROM "users" WHERE "users"."id" = $1 LIMIT $2 FOR UPDATE /*application:Reporting*/  [["id", 1], ["LIMIT", 1]]
   (1.2ms)  COMMIT /*application:Reporting*/
```

**Comment by bvicenzo** [comment]
Thanks, @simi. It seems that it works...
However, wouldn't it be better to use the transaction method just one time, inside the `with_lock` method?

**Comment by simi** [comment]
Personally I do not see any reason for that. `with_lock` has already one argument (true, false) and additional keyword arguments do not play nicely with that. Anyway it could be useful to update documentation to make explicit transaction will be reused if already opened.
