### ISSUE TITLE
Unable to read from secondary database if `writing` option is omitted or nil

### ISSUE THREAD

**Issue by cguess** [rails/rails#39580]
When setting up multiple databases on a Rails 6 app the logical way to mark a model as "read only" would be to omit the `writing` key on the `connects_to` function within a model, while keeping the `reading` key. However, this doesn't work, and not only does it not work, but depending on the way you set it up, the failure paths are wildly different and none are descriptive.

### Steps to reproduce

1. Create a wrapper that is supposed to read from a secondary database, but not one you'd like to write to. Logically it would look like this:
```
# Model for accessing the secondary database
class SecondaryDbBase < ApplicationRecord
  self.abstract_class = true
  connects_to database: { reading: :secondary }
end
```
2. Inherit from the wrapper in another model, setting the proper `table_name`
```
class Secondary < SecondaryDbBase
    self.table_name = "original_model_name"
end
```
3. Set up the secondary database with some environment variables that point to a valid Postgres DB
```
secondary: &secondary
  host: <%= ENV.fetch("SECONDARY_DB_HOST") %>
  database: <%= ENV.fetch("SECONDARY_DB_NAME") %>
  username: <%= ENV.fetch("SECONDARY_USERNAME") %>
  password: <%= ENV.fetch("SECONDARY_PASSWORD") %>
  encoding: utf8
  adapter: postgresql

```
3. Run the rails console, expecting to be able to read.
```
$ rails c

Running via Spring preloader in process 90539
Loading development environment (Rails 6.0.3.1)

irb(main):005:0> Secondary.first
Traceback (most recent call last):
        2: from (irb):4
        1: from (irb):5:in `rescue in irb_binding'
ActiveRecord::ConnectionNotEstablished (No connection pool with 'SecondaryDbBase' found.)
```
Whoops, pretty weird error. Let's try it by putting the `writing` key in such that `connects_to database: { writing: nil, reading: :secondary }`
```
$ rails c

Running via Spring preloader in process 90539
Loading development environment (Rails 6.0.3.1)

irb(main):005:0> Secondary.first

   (1.0ms)  SELECT sqlite_version(*)
  Secondary Load (0.4ms)  SELECT "facts".* FROM "facts" ORDER BY "facts"."id" ASC LIMIT ?  [["LIMIT", 1]]
Traceback (most recent call last):
        1: from (irb):1
ActiveRecord::StatementInvalid (SQLite3::SQLException: no such table: original_model_name)
```

OK... so it's an entirely different error, despite, intuitively, it's doing the same thing. Let's just try adding the proper `writing` key in such that `connects_to database: { writing: :secondary, reading: :secondary }`

```
$ rails c

Running via Spring preloader in process 90539
Loading development environment (Rails 6.0.3.1)

irb(main):005:0> Secondary.first

  Secondary Load (28.2ms)  SELECT "original_model_name".* FROM "original_model_name" ORDER BY "original_model_name"."id" ASC LIMIT $1  [["LIMIT", 1]]
=> #<MODEL STUFF THAT'S CORRECT>
```
Now it works! But we can still write to a database we don't want to.

### Expected behavior

The best option would be to make the db connection read-only if no `writer` parameter is provided. This is what I'm trying to do right now.

In lieu of that (I could see some compelling arguments that silently not-writing would be an issue) I would expect either a proper error indicating that the `writer` key is required and missing, or at least the failure path to be the same whether setting `writer` to `nil` or omitting it completely.

### Actual behavior

If `writer` is set to nil the error is `ActiveRecord::StatementInvalid (SQLite3::SQLException: no such table: original_model_name)` (which is odd because though I'm using SQLite for the primary database, I'm using Postgres for the secondary database)

If `writer` is omitted the error is `ActiveRecord::ConnectionNotEstablished (No connection pool with 'SecondaryDbBase' found.)`

### System configuration
**Rails version**:
6.0.3.1
**Ruby version**:
2.7.1

### Workaround ###
Set up Postgres (or other db) credentials to be "readonly" and then still set the database as a `writer`. This works, however, it also doesn't reflect reality in the code and configuration, which could get messy quickly.

### Extra ###
I've created a sample app demonstrating this at https://github.com/cguess/Rails6MultpleDBBugDemo

To test create a `.env` file and set the following in it:
```
SECONDARY_BASE_URL=https://www.example.co
SECONDARY_DB_HOST=example.co
SECONDARY_DB_NAME=dbname
SECONDARY_USERNAME=username
SECONDARY_PASSWORD=password
```

**Comment by rolandasb** [comment]
I've stumbled upon this issue as well. In my case I'm building an admin interface which reads customer data through direct database connection. Using readonly database user and doing no writes in application code seems to do the trick, but I'm having a hard time with rake tasks—they execute across both databases by default, so when doing `rake db:reset` for example, it drops both databases while I need it to drop only primary one.

I played around with overriding rake tasks, but maybe there's a better way to approach this?
