### ISSUE TITLE
`assert_enqueued_with` somewhat unexpectedly raises `ActiveJob::DeserializationError`

### ISSUE THREAD

**Issue by BrentWheeldon** [rails/rails#39606]
### Steps to reproduce

[Failing test](https://gist.github.com/BrentWheeldon/12844b2aeb4c0b5ed4a6b4a8b96657ac)

I've tried to explain this in words a couple of times and can't find a succinct way of explaining it. Essentially `assert_enqueued_with` will fail with a `ActiveJob::DeserializationError` if there is a job whose arguments won't deserialize (for example, the arguments contain a deleted ActiveRecord model) in the `enqueued_jobs` array before the job that we're trying to assert was enqueued.

### Expected behavior

The assertion passes - we don't blow up if some earlier job in the `enqueued_jobs` array has arguments that can't be be deserialized

### Actual behavior

`ActiveJob::DeserializationError` is raised from [`ActiveJob::TestHelper#deserialize_args_for_assertion `](https://github.com/rails/rails/blob/49baf092439fc74fc3377b12e3334c3dd9d0752f/activejob/lib/active_job/test_helper.rb#L694)

### System configuration
**Rails version**:

`master@49baf09`

**Ruby version**:

`ruby 2.7.1p83 (2020-03-31 revision a0c7c23c9c) [x86_64-darwin19]`

**Comment by jeffwidman** [comment]
I wish this were closed as "not done" rather than "completed" to reduce confusion... 

At GitHub we have an internal test that has a workaround for this test... As of now, the test still fails without the workaround, so it looks like this is still an open bug.
