### ISSUE TITLE
Unable to provide custom key while uploading document in Rails 6.0.3.1

### ISSUE THREAD

**Issue by vinodprak** [rails/rails#39604]
Hi

Am trying to build a tree like structure in s3, where I want to maintain certain category documents under each customer. I found that ` Rails 6.0.3.1 ` enables us to upload file directly to folder instead at the root level. So I have updated my application to ` Rails 6.0.3.1 ` and am facing couple of issues.

1. Unable to provide custom key while upload.
2. Deprecated method ` service_url ` is still working for me, even after updating rails version.

Please do let me know how to proceed on this.

### Steps to reproduce

1. Create a new rails application ` rails _6.0.3.1_ new rails_6_active_storage `
2. Added ` gem "aws-sdk-s3" ` to Gemfile
3. Configured s3 storage.
4. Attaching document with custom key is resulting in Error. If I try uploading the document without custom key it is working fine.

### Expected behavior

```ruby 
user.document.attach io: File.open(file_path),  filename: "3.png",  key: "uuid/dumrvdf4xfmt6o8ytjihm1is6o8y" 
```
after running the above code the document should be placed in the defined path (key) 

### Actual behavior

```ruby 
user.document.attach io: File.open(file_path),  filename: "3.png",  key: "uuid/dumrvdf4xfmt6o8ytjihm1is6o8y" 
```
running the above code resulted in ` ArgumentError (unknown keyword: key) `

### System configuration
**Rails version**: Rails 6.0.3.1

**Ruby version**: ruby 2.6.1p33

**Comment by jonathanhefner** [comment]
Rails 6.0.3.1 does not have this feature.  It was added by 4dba136c83cc808282625c0d5b195ce5e0bbaa68 to `master` branch and not backported to `6-0-stable`.  It will be released in Rails 6.1.
