### ISSUE TITLE
ActiveRecord `eager_load` causes `select` to forget database column type

### ISSUE THREAD

**Issue by bbascarevic-tti** [rails/rails#39605]
When using `ActiveRecord::QueryMethods#select` together with `ActiveRecord::QueryMethods#eager_load`  then the resulting relation, when enumerated, "forgets" actual database types and uses types from the raw row instead, for columns used in `select`. This happens even when `eager_load` relations are empty.

### Steps to reproduce
```
value1 = AnyNonEmptyModel                   .select('CAST(0.0 AS DECIMAL) AS f').first.f
value2 = AnyNonEmptyModel  .eager_load([])  .select('CAST(0.0 AS DECIMAL) AS f').first.f
puts value1.class
puts value2.class
```
### Expected behavior
```
BigDecimal
BigDecimal
```
### Actual behavior
```
BigDecimal
String
```
It's the same when using dates, `value1` is a Date, `value2` is a String. Not reproducible on SQLite3 since decimals are floats and dates are strings.

### System configuration
**Rails version**:
6.0.3.1
**Ruby version**:
2.6.4

**Comment by tgxworld** [comment]
It looks like this has already been fixed 

```
# frozen_string_literal: true

require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  # Activate the gem you are reporting the issue against.
  # gem "activerecord", "6.0.3.1"
  gem "rails", git: "https://github.com/rails/rails.git"
  gem "pg"
end

require 'pg'
require "active_record"
require "minitest/autorun"
require "logger"

# This connection will do for database-independent bug reports.
ActiveRecord::Base.establish_connection("postgresql://user@localhost:5432/activerecord_unittest")
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :posts, force: true do |t|
  end
end

class Post < ActiveRecord::Base
end

Post.create!

class BugTest < Minitest::Test
  def test_select_with_alias
    assert_equal 0.0, Post.eager_load([]).select("CAST(0.0 AS DECIMAL) AS f").first.f
  end
end
```

Maybe @kamipo would know?

**Comment by kamipo** [comment]
Seems https://github.com/rails/rails/commit/e10765cfa5e05a655d208e6c598a32b8dce64752#diff-cc31fc1dd1e78db64638200f710b2f59R897 fixed for the case of decimal.

**Comment by tgxworld** [comment]
I guess this can be closed? :)
