### ISSUE TITLE
Dynamic Views/Controllers through Scaffold generator

### ISSUE THREAD

**Issue by douglasrosa0110** [rails/rails#39609]
Now the Scaffold generates specific global variables and needs to edit each of view of the CRUD for each new column migrated in the database.  

Of course, a correct implementation of the inputs HTML will be sensitive to the type of column (if integer, datetime, etc)

**What the community think about?**

### Expected behavior
Similarly to this gist: https://gist.github.com/douglasrosa0110/8b68f4e5389972f1884aebe62fdf1617

### Actual behavior
Generate specific names and fields

### System configuration
**Rails version**: Actual
**Ruby version**: Actual

**Comment by hahmed** [comment]
I personally like the fact that each controller and view has the class name explicitly declared.

We can always create our own generators and the scaffolds can use them?

**Comment by p8** [comment]
I agree with @hahmed. There is a whole section in the guides for customizing your templates: https://guides.rubyonrails.org/generators.html#customizing-your-workflow-by-changing-generators-templates

Dynamically creating paths makes it harder to understand for beginners. The example in the gist also doesn't work for namespaced routes.

Sending unfiltered parameters to objects is not recommended and will generate a warning in Brakeman:
This https://brakemanscanner.org/docs/warning_types/dangerous_send/
