### ISSUE TITLE
Presence validation of associations validating non-valid non-persisted associations.

### ISSUE THREAD

**Issue by patrickneugebauer** [rails/rails#39617]
### Steps to reproduce
executable test case:
https://gist.github.com/patrickneugebauer/6cd48c71835cf03aa2a332871f26efdf

### Expected behavior
`validates_presence_of :record` will not allow save if `record` is not persisted and cannot be persisted.

### Actual behavior
`validates_presence_of :record` allows save if `record` is not persisted and cannot be persisted.

### System configuration
**Rails version**: Rails 6.0.3.1

**Ruby version**: ruby 2.7.1p83 (2020-03-31 revision a0c7c23c9c) [x86_64-linux]

### Did you write a patch that fixes a bug?
No, wondering if this is expected before I dig in further.
Should people just know to use `validated_presence_of :record, :record_id` together to ensure integrity of connections?

I checked the documentation and it is not technically wrong, but I feel it could be improved by adding detail about what is expected.

https://guides.rubyonrails.org/active_record_validations.html#presence

> If you want to be sure that an association is present, you'll need to test whether the associated object itself is present, and not the foreign key used to map the association. This way, it is not only checked that the foreign key is not empty but also that the referenced object exists.
```
class LineItem < ApplicationRecord  
  belongs_to :order  
  validates :order, presence: true
end
```

**Comment by eugeneius** [comment]
The API documentation has a note about this:

https://api.rubyonrails.org/v6.0.3.1/classes/ActiveRecord/Validations/ClassMethods.html#method-i-validates_presence_of

> NOTE: This validation will not fail while using it with an association if the latter was assigned but not valid. If you want to ensure that it is both present and valid, you also need to use [validates_associated](https://api.rubyonrails.org/v6.0.3.1/classes/ActiveRecord/Validations/ClassMethods.html#method-i-validates_associated).

I'd be okay with adding a similar note to the guides.

**Comment by theasteve** [comment]
@patrickneugebauer would yo be working on a PR to update the docs?
