### ISSUE TITLE
ActiveSupport::Notifications not unsubscribe symbol pattern

### ISSUE THREAD

**Issue by ifyouseewendy** [rails/rails#39610]
### Steps to reproduce

Add the following test case to [activesupport/test/notifications_test.rb](https://github.com/rails/rails/blob/master/activesupport/test/notifications_test.rb), and run by `bundle exec rake test TEST=test/notifications_test.rb TESTOPTS="--name=test_unsubscribe_symbol"`

```rb
module Notifications
  # new test case
  class SubscribeToSymbolPattern < TestCase
    def test_unsubscribe_symbol
      notifier = ActiveSupport::Notifications::Fanout.new
      symbol = :foo

      subscriber = notifier.subscribe(symbol) { |*_| }
      assert_equal [subscriber], notifier.listeners_for(symbol)

      notifier.unsubscribe(symbol)
      assert_equal [], notifier.listeners_for(symbol)
    end
  end
end
```

### Expected behavior

Test pass

### Actual behavior

```
Failure:
Notifications::Notifications::SubscribeToSymbolPattern#test_unsubscribe_symbol [/Users/wendi/Workspace/rails/activesupport/test/notifications_test.rb:213]:
--- expected
+++ actual
@@ -1 +1 @@
-[#<ActiveSupport::Notifications::Fanout::Subscribers::Timed:0xXXXXXX @pattern=#<ActiveSupport::Notifications::Fanout::Subscribers::Matcher:0xXXXXXX @pattern=:foo, @exclusions=#<Set: {}>>, @delegate=#<Proc:0xXXXXXX@/Users/wendi/Workspace/rails/activesupport/test/notifications_test.rb:212>, @can_publish=false>]
+[]
```

### System configuration
**Rails version**: 6.1.0.alpha
**Ruby version**: 2.7

### Analysis

I'm using `ActiveSupport::Notifications` in a project for instrumentation, and I've noticed that by using a symbol pattern name, it worked well for `subscribe`, but not for `unsubscribe`.

By looking into the code here,

https://github.com/rails/rails/blob/49baf092439fc74fc3377b12e3334c3dd9d0752f/activesupport/lib/active_support/notifications/fanout.rb#L24-L56

both `subscribe` and `unsubscribe` _only_ check `String` as named subscriptions and leave the symbol name as "other" subscriptions, which are supposed to be regex or nil pattern name. The bug is hidden as subscription with symbol name works well, accidentally. It only runs into trouble with unsubscription.

I think a proper fix is to handle `Symbol` as `String` in the code. I can help throw a fix if the analysis sounds valid.

**Comment by tgxworld** [comment]
It looks like this has been raised before and there are no plans to support symbols here https://github.com/rails/rails/pull/36748#issuecomment-514667641

**Comment by ifyouseewendy** [comment]
👋  My ticket is not about supporting symbol as a feature, but more for having inconsistency or unexpected behaviour in the current code base. If it doesn't support symbol by design, it'd better explain it in the doc or prevent the usage in the code. However, it's in a weird state now that, both `subscribe` and `instrument` work well symbol pattern name. Only `unsubscribe` fails silently. It takes me half a day to figure out this hidden problem. Not sure if other people share the same issue, or maybe not even realizing it.

**Comment by tgxworld** [comment]
The doc currently does state that it only accepts a String or Regexp only but I do agree with you that the code should probably prevent it. 

> [You can subscribe to events by passing a String to match exact event names, or by passing a Regexp to match all events that match a pattern.](https://api.rubyonrails.org/classes/ActiveSupport/Notifications.html#method-c-subscribe)

Perhaps we should raise an error if `pattern` isn't a String or a Regexp?

**Comment by vipulnsward** [comment]
Think this is a regression from https://github.com/rails/rails/commit/de13ed9ec740feaa5fdb48f338d36581d7ce2e3f

Symbols *were* kind of supported when doing 

```
@other_subscribers.reject! { |s| s.matches?(subscriber_or_name) }
```

Easier to get that behavior back in case of *other* non-string subscribers.

**Comment by ifyouseewendy** [comment]
> The doc currently does state that it only accepts a String or Regexp only but I do agree with you that the code should probably prevent it.

Sorry, I missed that 👍 

> Symbols were kind of supported when doing
> @other_subscribers.reject! { |s| s.matches?(subscriber_or_name) }

Yeah, this would work. But it's a little awkward to consider symbol usage as other subscribers. It seems more like a mirror case as string subscribers to me.

- - -

So we may either explicitly prevent the symbol usage or simply support it like string subscribers. Which way you guys think we should go?

**Comment by vipulnsward** [comment]
>  Think this is a regression from de13ed9

My mistake, this does does not work on 5.x versions as well, not a regression.
