### ISSUE TITLE
ActiveJob::Serializers::TimeWithZoneSerializer fails serializing time with ms

### ISSUE THREAD

**Issue by Hugo-Hache** [rails/rails#39648]
### Steps to reproduce
```
time = Time.zone.parse('2020-06-18 08:50:53.429276 UTC')
serialized_time = ActiveJob::Serializers::TimeWithZoneSerializer.serialize(time)
deserialized_time = ActiveJob::Serializers::TimeWithZoneSerializer.deserialize(serialized_time)
raise('Serialization failed') if time != deserialized_time
```

### Expected behavior
Serialization should handle times with ms.

### Actual behavior
Serialization ignores ms by serializing with `iso8601` instead of `utc` which is used in `<=>` of Time.

https://github.com/rails/rails/blob/b1646a48fafd7a2d2c2aad3b3fc77764d7a37bed/activejob/lib/active_job/serializers/time_with_zone_serializer.rb#L7

**Comment by tgxworld** [comment]
This seems to be intentional from what @gmcgibbon mentioned in https://github.com/rails/rails/pull/35713

> We can fix this by adding precision (now = Time.now; Time.iso8601(now.iso8601(20)) == now), but that adds unnecessary size to job payloads.

**Comment by Hugo-Hache** [comment]
😲 the testing tools was even modified to accommodate it. From my perspective it was such a very unexpected behavior, that I thought it was an issue. 

Though I understand the performance issue, in my mind performance concerned projects could have used representations with the adequate precision for their need.

@gmcgibbon what do you think of truncating precision only when it won't break equality, i.e. non-zero ms?

**Comment by pixeltrix** [comment]
We have a similar issue when serializing JSON and there we have a setting `ActiveSupport::JSON::Encoding.time_precision` which defaults to 3 - perhaps a similar setting for Active Job makes sense too?

**Comment by tgxworld** [comment]
This isn't stale as there is a PR attached.
