### ISSUE TITLE
ActionView::Template::Error (wrong number of arguments (0 for 1)) - Fails on constantize in ActiveSupport's inflector methods 

### ISSUE THREAD

**Issue by RubyBhaktan** [rails/rails#39655]
### Steps to reproduce
Upgrade Rails 4.1.8 -> 4-2 stable

### Expected behavior
It works on localhost but once deployed to Heroku, it fails to load the initial form for signup and the app crashes. 

### Actual behavior
ActionView::Template::Error (wrong number of arguments (0 for 1))
    1: h2 Sign in
    2: 
    3: = form_for(resource, as: resource_name, url: session_path(resource_name)) do |f|
    4:   fieldset
    5:     = f.label :email
    6:     = f.email_field :email, autofocus: true, placeholder: 'Email address'
   app/views/devise/sessions/new.html.slim:3:in `_app_views_devise_sessions_new_html_slim___2338823100077562730_46979003087900'

**Framework Trace:** 
constantize
activesupport (4.2.11.3) lib/active_support/inflector/methods.rb, line 250
default_form_builder_class
actionview (4.2.11.3) lib/action_view/helpers/form_helper.rb, line 1215
instantiate_builder
actionview (4.2.11.3) lib/action_view/helpers/form_helper.rb, line 1209
form_for
actionview (4.2.11.3) lib/action_view/helpers/form_helper.rb, line 443

### System configuration
**Rails version**:
4.2.11.3
**Ruby version**:
2.4.0

**Gemfile** 
source 'https://rubygems.org'
ruby "2.4.0"

gem 'rails', ' 4.2.11.3'

gem 'unicorn'
gem 'pg', '~> 0.17'

gem 'sass-rails', '~> 4.0.0'

gem 'slim'

gem 'uglifier', '>= 1.3.0'

gem 'coffee-rails', '~> 4.0.0'

gem 'jquery-rails'

gem 'foundation-rails', '~>5.5.2'

gem 'sprockets', '<= 2.11.0'

gem 'turbolinks'

gem 'jbuilder', '~> 1.2'

group :doc do
  gem 'sdoc', require: false
end
gem 'activeresource', require: 'active_resource'
gem "activeresource-response"
gem 'devise', '= 3.5.1'
gem 'devise_invitable', '= 1.5.1'
gem 'will_paginate'
gem 'faraday'
gem 'rest-client'
group :development, :test do
  gem 'rspec-rails', '~> 3.8.0'
  gem 'rspec-activemodel-mocks'
  gem 'rspec-given'
  gem 'pry'
  gem 'pry-rails'
  gem 'simplecov'
  gem 'test-unit'
end

group :staging, :production do
  gem 'rails_12factor'
  gem 'airbrake', '= 4.0.0'
end

I followed the official upgrade guide but wondering what went wrong that form_for stopped working. Any help is much appreciated.

**Comment by chizzel36** [comment]
Code of Conduct

**Comment by jonathanhefner** [comment]
Unfortunately, Rails 4.2 is no longer supported, as per [Rails' Maintenance Policy](https://guides.rubyonrails.org/maintenance_policy.html).

Since you say you have it working locally, you might try proceeding with incremental upgrades (i.e. 4.2 -> 5.0 -> 5.1 -> ...), and seeing if the problem persists.
