### ISSUE TITLE
Change ssl redirect status from - 307 Temporary Redirect - To - 308 Permanent Redirect

### ISSUE THREAD

**Issue by obenda** [rails/rails#39654]
https://github.com/rails/rails/blob/661da266b94909574426fd1121ef13b800e01b9a/actionpack/lib/action_dispatch/middleware/ssl.rb#L136

When we redirect from the http versions to the https version the purpose of it is to disable the use of the http version, it is permanent and we would like search engines to stop going through the http version anyway. So we need to mark it as permanent.
 
Need to change the 307 status (in the line mentioned above) to 308 (or better, use the `Rack::Utils::SYMBOL_TO_STATUS_CODE[:permanent_redirect]` instead)
or
give the option to set it from outside
Suggestion (in /config/environments/production.rb) :
`config.ssl_options = { redirect: { status: Rack::Utils::SYMBOL_TO_STATUS_CODE[:permanent_redirect] } }`

The change to the 307 was made at the time 308 was not yet supported by all browsers
Now it is being supported by all browsers as can be seen here
https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/308

**Comment by tgxworld** [comment]
@obenda I investigated the issue and it does seem like a `308` response code is more desirable here. I have a [PR](https://github.com/rails/rails/pull/39656) opened for the proposed change. 

> give the option to set it from outside

Are you not able to do this? This is already supported.
