### ISSUE TITLE
Hash#to_query does not handle nil parameters correctly

### ISSUE THREAD

**Issue by jsmartt** [rails/rails#39662]
... or maybe it's a parsing issue. Either way, I think the behavior should be consistent.

### Steps to reproduce

```ruby
hash = { a: nil, b: 'abc' }
query = hash.to_query
# => "a=&b=abc"

Rack::Utils.parse_nested_query(query)
# => {"a"=>"", "b"=>"abc"}

CGI::parse(query)
# => {"a"=>[""], "b"=>["abc"]}
```

### Expected behavior
The output from `Hash#to_query` should be parseable back into the same values as were given, with respect to nil values. Here are a few options I can think of to solve this:
- Rails can correctly parse the query string `"a&b=abc"`, so why not have to_query output that? If it's a compatibility concern with other server types, I'd like to see an option to be able to control the behavior (e.g. `hash.to_query(compatibility: :rails)`)
- Encode nil to the ASCII null value: `%00`, and likewise be able to decode it properly.

From my brief research, I understand this is a complicated issue, and there likely isn't a solution that will work for every server type. That said, wouldn't Rails prioritize compatibility with Rails?

### Actual behavior
`nil` query param values from a hash are converted to empty strings in the eyes of Rack & CGI.

Currently, a Rails app will have issues trying to query another Rails app, because the server receiving the request will not be receiving it accurately. When transformed into a DB filter, `Model.where(a: '', b: 'abc')` is very different from `Model.where(a: nil, b: 'abc')`.

### System configuration
**Rails version**: 5.2.4.3

**Ruby version**: 2.4.5p335

Related to #28129

**Comment by vipulnsward** [comment]
Related https://github.com/rails/rails/pull/31845
