### ISSUE TITLE
Out-of-date docs ranking high in Google - why not redirect?

### ISSUE THREAD

**Issue by semicolonandsons** [rails/rails#39689]
I was Googling for Rails screencasts and encountered [this page](https://rails.github.io/) about Rails 4. I'm assuming the page is official due to the presence of the Basecamp logo.

Anyway, this page could prove confusing because it provides dated information to newer users. I would suggest you consider redirecting to more modern docs.

**Comment by p8** [comment]
These docs use github pages:
https://github.com/rails/rails.github.com
It's possible to add redirects:
https://help.github.com/en/enterprise/2.13/user/articles/redirects-on-github-pages

**Comment by p8** [comment]
Searching on "deploying ruby on rails" on duckduckgo lists https://rails.github.io/deploy/ as the first result.
