### ISSUE TITLE
create_or_find_by/! does not work as expected when run within an existing repeatable read transaction

### ISSUE THREAD

**Issue by mzruya** [rails/rails#39691]
[`ActiveRecord::Base.create_or_find_by/!`](https://apidock.com/rails/v6.0.0/ActiveRecord/Relation/create_or_find_by) attempts to improve on [`ActiveRecord::Base.find_or_create_by/!`](https://apidock.com/rails/v6.0.0/ActiveRecord/Relation/find_or_create_by) by avoiding race conditions that the previous implementation was susceptible to.

`create_or_find_by` attempts to first create the record while relying on the database uniqueness constraint to inform us if it already exists.
When the record does exist, it catches an exception and finds the record using the attributes provided. 

My initial expectation of the method was that if used properly, it's expected to always return a record, even in concurrent situations.

The new strategy is still susceptible to race conditions which are not mentioned in the docs, the behavior in these cases is dependent on the database isolation level. 

More concretely, `create_or_find_by` could raise a `RecordNotFound` if called from within an existing transaction in a repeatable reads isolation level.

Given how common it is for application code to run within an existing transaction (For example, code inside AR callbacks), and the fact that repeatable reads is the default isolation level for mysql, I think this is a fairly common use case.

### Reproduction

Repeatable read guarantees a consistent snapshot of the database, in InnoDB, the snapshot is established during the [first read](https://dev.mysql.com/doc/refman/8.0/en/innodb-transaction-isolation-levels.html). This means that if our transaction performed a read before a record is created by another transaction, we won't "see" it. In respect to uniqueness constraints, if we try inserting a record that violates it, the database would still protect us, but if we try querying for the record, it'll seem like it doesn't exist.

In the context of [`ActiveRecord::Base.create_or_find_by/!`](https://apidock.com/rails/v6.0.0/ActiveRecord/Relation/create_or_find_by), this would manifest as a uniqueness error being raised, but the record not existing.

```ruby
def create_or_find_by(attributes, &block)
  transaction(requires_new: true) { create(attributes, &block) }
rescue ActiveRecord::RecordNotUnique 
  # exception caught, but we can't see the record because it's not present in our snapshot 
  find_by!(attributes)
end
```

I created a few [test cases](https://gist.github.com/mzruya/603f722ede1615fd7957cfd95a4d466c#file-test_create_or_find_by_race_condition-rb-L101-L127) that demonstrate the issue.

### Suggestions
It doesn't seem like it's possible to fix this behavior, the database isolation level would always prevent us from returning something that another connection committed. 

I do think that there's a misconception (at least I had it) that `ActiveRecord::Base.create_or_find_by` is meant to be atomic and work correctly in concurrent situations. 

Therefore it probably makes sense to document this behavior a bit more thoroughly and mention these caveats in the [docs](https://apidock.com/rails/v6.0.0/ActiveRecord/Relation/create_or_find_by).

I'll gladly take on improving the current documentation if that seems reasonable.
But I'd also love to hear if anyone has any other thoughts on this behavior.

Thank you!

**Comment by pixeltrix** [comment]
@mzruya are you talking specifically about using `create_or_find_by!` inside a nested transaction - the issue title is a little unclear? If so, yes adding a note about the outer transaction's isolation level being set to 'read committed' would be useful.

**Comment by mzruya** [comment]
> are you talking specifically about using create_or_find_by! inside a nested transaction
@pixeltrix. Yes. by nested transactions, I'm referring to cases where `create_or_find_by` is invoked within the context of an existing repeatable reads transaction, but not necessarily inside a save point. 

> the issue title is a little unclear?
I updated the title.

> yes adding a note about the outer transaction's isolation level being set to 'read committed' would be useful.
Would it be more accurate to mention that this method does not work well in 'repeatable read'? I think it'll be fine in any other isolation level.

**Comment by smridge** [comment]
@mzruya I just ran into this issue as well. Curious if you have found any workarounds or are using an alternative method to combat?
