### ISSUE TITLE
Building associations before create breaks saved_changes after create

### ISSUE THREAD

**Issue by glennfu** [rails/rails#39706]
### Steps to reproduce
```ruby
# frozen_string_literal: true

require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  gem "rails", github: "rails/rails"
  gem "sqlite3"
end

require "active_record"
require "minitest/autorun"
require "logger"

# This connection will do for database-independent bug reports.
ActiveRecord::Base.establish_connection(adapter: "sqlite3", database: ":memory:")
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :posts, force: true do |t|
    t.string :name
    t.integer :owner_id
  end

  create_table :owners, force: true do |t|
    t.string :name
  end
end

class Post < ActiveRecord::Base
  belongs_to :owner, optional: true, inverse_of: :post
end

class Owner < ActiveRecord::Base
  has_one :post, inverse_of: :owner
end

class BugTest < Minitest::Test
  def test_good_association_stuff
    post = Post.new(name: "foo")
    post.save

    refute_predicate post.saved_changes, :empty?
    assert_equal post.saved_change_to_name, [nil, "foo"]
  end

  def test_bad_association_stuff
    post = Post.new(name: "foo")
    post.build_owner(name: "bar")
    post.save

    refute_predicate post.saved_changes, :empty?
    assert_equal post.saved_change_to_name, [nil, "foo"]
  end
end
```

### Expected behavior
I would expect both tests to pass. Dirty state on the `name` attribute should have nothing to do with whether or not an association was built before that point.

### Actual behavior
It seems that after `save` (on create) the `saved_changes` gets emptied out entirely in this case, instead of reporting correct change values.

### System configuration
**Rails version**: 6.0.3.1

**Ruby version**: 2.6.3

**Comment by martijn** [comment]
What I've noticed is that in the 'bad' case there are more callbacks executed on Post, what causes two calls to `ActiveModel::Dirty.changes_applied`. On the second invocation (the update callback) no changes were applied, so the saved changes are emptied.

I can't find the reason why this is happening, but I did notice the problem does not appear if you disable autosave on the association:

```ruby
class Owner < ActiveRecord::Base
  has_one :post, inverse_of: :owner, autosave: false
end
```

```ruby
  def test_bad_association_stuff
    post = Post.new(name: "foo")
    post.build_owner(name: "bar")
    post.owner.save
    post.save

    refute_predicate post.saved_changes, :empty?
    assert_equal post.saved_change_to_name, [nil, "foo"]
  end
```

I haven't investigated whether the [autosave logic](https://github.com/rails/rails/blob/master/activerecord/lib/active_record/autosave_association.rb#L479) is actually the culprit.
