### ISSUE TITLE
ActiveRecord::Base.validate - allow validate_ prefix on methods

### ISSUE THREAD

**Issue by lukeredpath** [rails/rails#39709]
I'd like to propose a small enhancement for this API and am willing to submit a PR pending feedback from the core team.

It's common to define a custom validation in a model like this:

```ruby
class WidgetFactory < ApplicationRecord
  validate :widgets_have_not_expired

  # lots of code

  private

  def widgets_have_not_expired

  end
end
```

Whilst the validation reads nicely at the `validate` call-site, it the validation method itself seems a little odd in isolation as it no longer reads imperatively like it does when used as a symbol with the `validate` method. It can often read like a query method which is misleading as it normally has behaviour (e.g. it can manipulate your record's errors).

A workaround for this that I've seen on many projects is to adopt the convention of prefixing the validation method with `validate_` so it reads better in isolation, thus:

```ruby
class WidgetFactory < ApplicationRecord
  validate :validate_widgets_have_not_expired

  # lots of code

  private

  def validate_widgets_have_not_expired

  end
end
```

It's now entirely clear what the purpose of the method is when you're looking through your code but you're left with the double "validate" at the `validate` call site - gross.

### Expected behavior

This is a trivial problem for Ruby to solve - by convention, the `validate` method could check for methods with and without the `validate_` prefix allowing you to adopt the style above without sacrificing readability, allowing you to do this:

```ruby
class WidgetFactory < ApplicationRecord
  validate :widgets_have_not_expired

  # lots of code

  private

  def validate_widgets_have_not_expired

  end
end
```

This would be a backwards-compatible change because the previous unprefixed method behaviour would work just as it does now.

**Comment by pixeltrix** [comment]
Thanks for the suggestion but after discussion with other core team members, we feel that the behaviour would be confusing and introduce backward compatibility issues. Additionally, having to do the check at runtime could result in a performance hit (albeit a small one).
