### ISSUE TITLE
[ActiveRecord] Preloader not loading through association if middle association is already loaded

### ISSUE THREAD

**Issue by msbit** [rails/rails#39717]
### Steps to reproduce
```ruby
require 'bundler/inline'

gemfile(true) do
  source 'https://rubygems.org'

  gem 'activerecord', '5.2.4.3'
  gem 'sqlite3'
end

require 'active_record'
require 'minitest/autorun'

ActiveRecord::Base.establish_connection(adapter: 'sqlite3', database: ':memory:')

ActiveRecord::Schema.define do
  create_table(:grandparents, force: true)
  create_table(:parents, force: true) { |t| t.integer :grandparent_id }
  create_table(:children, force: true) { |t| t.integer :parent_id }
end

class Grandparent < ActiveRecord::Base
  has_many :parents
end

class Parent < ActiveRecord::Base
  belongs_to :grandparent
  has_many :children
end

class Child < ActiveRecord::Base
  belongs_to :parent
  has_one :grandparent, through: :parent
end

class BugTest < Minitest::Test
  def test_preload_through_association_with_middle_association_loaded
    grandparent = Grandparent.create!

    parent = grandparent.parents.create!

    3.times do
      parent.children.create!
    end

    children = Child.all.to_a
    children.each(&:parent)

    ActiveRecord::Associations::Preloader.new.preload(children, :grandparent)

    children.each { |c| assert c.grandparent }
  end
end
```

### Expected behavior

I would expect that running `ActiveRecord::Associations::Preloader.new.preload` for a `through` association would load both the middle association and the ultimate target association.

### Actual behavior

Loading the middle association for each record to be passed into the preloader (`children.each(&:parent)` in the above example) results in any association that runs through it to not be loaded.

From what I can tell, this runs afoul of the check at:
https://github.com/rails/rails/blob/7b5cc5a5dfcf38522be0a4b5daa97c5b2ba26c20/activerecord/lib/active_record/associations/preloader.rb#L180
which in the example is called when determining which preloader to return for the `Child#parent` association (after a previous run through which returns a `ThroughAssociation` loader for `Child#grandparent`). As a result of the association being already loaded for all records, an `AlreadyLoaded` loader is returned.

If not all of the records have that association loaded (eg replacing `children.each(&:parent)` with `children.first.parent`), then an `Association` loader is correctly returned.

### System configuration

Rails 5.2.4.3

ruby 2.6.6p146 (2020-03-31 revision 67876) [x86_64-darwin17]

**Comment by composerinteralia** [comment]
Thank you for the issue! The reproduction script you provided passes on Rails 6. Since Rails 5.2 is no longer receiving bug fixes (see the [Maintenance Policy](https://guides.rubyonrails.org/maintenance_policy.html)), we are going to close this issue. If you are able to reproduce the bug on a recent version of Rails, please feel free to reopen the issue.

**Comment by msbit** [comment]
Ah, you're right @composerinteralia! I didn't think to check with 6, but doing so now I can see it's not tripping up.

Thanks for taking a look, in any case.
