### ISSUE TITLE
Model.from("..").delete_all always delete everything. 

### ISSUE THREAD

**Issue by yxhuvud** [rails/rails#39767]
### Steps to reproduce

Given an activerecord model (lets call it `User`), and the following code: 
```
User
  .from("(SELECT * FROM users WHERE id = 1) AS users")
  .delete_all
```
Running this has the result that all users in the system are deleted. 

Yes, I know this particular query can be rewritten in a simpler way that doesn't fail. It is a reduced reproduction from a much more complicated case that deleted all records of a particular kind in our production database. 

### Expected behavior
As I see it, one of two behaviors would be expected here. 
Either, the user with id = 1 should be deleted. 
OR 
delete_all could be smart enough to realize that the query is built in a way that it doesn't handle, and would then error out. 

I'd expect the latter choice to be the most feasible to implement. But perhaps it is possible to generate something like 
`DELETE FROM users WHERE id IN (SELECT id FROM #{complete scope})` :man_shrugging: 

### Actual behavior

The generated SQL is: 
```
DELETE FROM "users"
```
This deletes all data in the user table, which obviously is neither expected or wanted behavior. 
### Workaround
Wrap it in another level of where: 
```
scope = User
  .from("(SELECT * FROM users WHERE id = 1) AS users")
  .delete_all
User.where(id: scope)
  .delete_all
```
### System configuration
**Rails version**:
Rails 5.2.4.3
**Ruby version**:
2.6.5

**Comment by eileencodes** [comment]
Does that format of `from` work? When I tested it locally without the `delete` all `User.from("SELECT * FROM users WHERE id = 1")` returns a SQL syntax error. The docs show it's supposed to be used in conjunction with `select`. See https://edgeapi.rubyonrails.org/classes/ActiveRecord/QueryMethods.html#method-i-from

It does seem odd that while `User.from` throws a syntax error that `User.from.delete_all` would ignore the syntax error and delete everything. Rather than working though I think this should throw the same syntax error when trying to do `delete_all` . I suspect in the case of `from` we're not passing along the scope to `delete_all` which is why we're not seeing a syntax error or the SQL from `from`.

**Comment by yxhuvud** [comment]
Good point. It seems I simplified too much. I'll be back shortly with a working reproduction.

**Comment by yxhuvud** [comment]
@eileencodes Sorry about that. Updated the example.

**Comment by eileencodes** [comment]
For `from` the docs say: "Specifies table from which the records will be fetched."

I don't think you're supposed to pass SQL selects to `from`, that's what `select` is for. I've never used from but all the tests in Rails use it either to specify a table name or specify a table name and index. None of the examples or usage of `from` expects a sql select. I don't think this is a bug. I think this is how it's supposed to behave.

**Comment by yxhuvud** [comment]
Well. Lets ignore the part where I use a SQL query then. That may have been an unintended behavior from some part of the AR stack (though it is very convenient escape hatch for injecting complex filtering subqueries into a relation so that it can be used like any other relation despite having some complex parts in it that can't be expressed in AR).

The same behavior still happens if used like `User.from(User.some_filtering_scope).delete_all`. 

As for `select` being for passing selects into, all impressions, both from docs and blog posts around the net is that `select` is what you use when you want to select which columns to select (including computed columns and other random stuff). In other words, `select` modifies what you get on a column level whereas `from` modifies the `FROM` part of the query. Or very simply said, `select` describe how the returned record looks like, while `from` describe which records you get in the answer.

**Comment by matthewd** [comment]
> Specifies table from which the records will be fetched.

In the general case it's going to be impossible for us to delete from whatever arbitrary table-expression was supplied to `from`, so all we really know is that the rows are _not_ coming from our base table. On that basis:

> delete_all could be smart enough to realize that the query is built in a way that it doesn't handle, and would then error out.

:+1:

Seems reasonable to me that `delete_all` (indeed, all the relation-level mutator methods) should raise if any `from` has been set.

**Comment by yxhuvud** [comment]
> impossible for us to delete from whatever arbitrary table-expression was supplied to `from`,

On the other hand, that reasoning also apply to invoking `destroy` on the instantiated entries too - there is no way to know if the id value the instances get populated with is actually sane.

**Comment by eileencodes** [comment]
> As for select being for passing selects into, all impressions, both from docs and blog posts around the net is that

Look, I had a long week and I wrote the wrong method name.

**Comment by yxhuvud** [comment]
@eileencodes I'm sorry if my tone came along wrong there. I was simply trying to verify that my understanding was correct. What method name did you mean to write?

**Comment by tgxworld** [comment]
@eileencodes Do you mind reopening this? The fix was reverted in https://github.com/rails/rails/pull/40202 and the discussion of why it was reverted can be found in https://github.com/rails/rails/pull/40178
