### ISSUE TITLE
Letter "S" disappearing in Browser's Rails Console

### ISSUE THREAD

**Issue by juancarlosasensio** [rails/rails#39760]
### Steps to reproduce
Added this to an html.erb file
`<%= console %>`

### Expected behavior
Expected the console to work properly.

### Actual behavior
Instead, the letter "S" cannot be typed into the console. Everything else works as expected.

### System configuration
**Rails version**:
`'rails', '~> 6'`

**Ruby version**:
`ruby '2.7.0'`

**Comment by jonathanhefner** [comment]
I am unable to reproduce this behavior.  You might check if you have other JavaScript code that is capturing the keystrokes.  If the problem persists, please open an issue at [web-console](https://github.com/rails/web-console), which is the repo for `console`.  And please include additional information such as the version of `web-console` in your `Gemfile.lock`, your browser / OS version, and your keyboard layout (e.g. US, EU, etc).
