### ISSUE TITLE
ActionController::DataStreaming#send_file_headers! and ActionDispatch::Http::ContentDisposition results in incorrect file names

### ISSUE THREAD

**Issue by tenpaiyomi** [rails/rails#39772]
### Steps to reproduce
Utilizing Rails 5.2.4.3, [ActionController::DataStreaming#send_file_headers!:134](https://github.com/rails/rails/blob/7b5cc5a5dfcf38522be0a4b5daa97c5b2ba26c20/actionpack/lib/action_controller/metal/data_streaming.rb#L134) would set up its disposition utilizing the filename passed in to generate a `Content-Disposition` header string and accompanying filename.

As of Rails 6.x, from PR [#33829](https://github.com/rails/rails/pull/33829) , [ActionController::DataStreaming#send_file_headers!:135](https://github.com/rails/rails/blob/66cabeda2c46c582d19738e1318be8d59584cc5b/actionpack/lib/action_controller/metal/data_streaming.rb#L135) now utilizes [ActionDispatch::Http::ContentDisposition#format](https://github.com/rails/rails/blob/v6.0.0/actionpack/lib/action_dispatch/http/content_disposition.rb) which generates the filename via both an `ascii` and `utf8` filename in the [#to_s](https://github.com/rails/rails/blob/66cabeda2c46c582d19738e1318be8d59584cc5b/actionpack/lib/action_dispatch/http/content_disposition.rb#L29) method.

The same code was utilized both before and after the Rails update.

```
send_data(file_data, disposition: 'attachment', filename: file_name)
```

In this case, `file_data` is simply binary data for a zip file, and `file_name` is `plan.zip`

This was tested utilizing the latest version of Chrome, Firefox, and IE11, all resulting in the improper file names.  After the workaround implemented below, the filenames are properly recognized by the browser.

### Expected behavior
The browser should open a download dialog with a filename of `plan.zip`

### Actual behavior
The browser opens a download dialog with a filename of `plan.zip; filename_=UTF-8''plan.zip`

### Workaround
For now, what I have had to do in order to properly send data and file names to clients is generate the full `Content-Disposition` header within the `disposition` option:

```
send_data(file_data, disposition: "attachment; filename=\"#{file_name}\"")
```

### Proposed solution

Revert of PR #33829.  While the changes are in accordance with RFC 5987 and RFC 6266, and the tests themselves pass, the browser implementation does not seem to be in accordance and results in improperly named files for downloads (at least when utilized via `send_data`).

### System configuration
**Rails version**: 6.0.3

**Ruby version**: 2.7.1

**Comment by georgeclaghorn** [comment]
I can’t reproduce in a minimal app that does `send_data "", disposition: :attachment, filename: "plan.zip"`. Chrome and Firefox both download a file named `plan.zip`.

Can you provide a minimal sample app that demonstrates the issue?

**Comment by cizmarty** [comment]
This issue is currently still relevant to me.

- Rails version: 7.0.3
- Ruby version: 3.1.2
- Chrome version: 102.0.5005.61 (Official Build) (x86_64)

Sample code in controller:

`send_data 'text', filename: 'name.txt', disposition: :download`

Header it sends:
`Content-Disposition: download; filename="name.txt"; filename*=UTF-8''name.txt`

This creates file with the name:
`name.txt; filename_=UTF-8''name.txt`

As suggested, the only workaround is to omit filename and manually set disposition:
`send_data 'text', disposition: 'download; filename=name.txt'`

This produces correctly file with the name:
`name.txt`

**Comment by glaszig** [comment]
same here in safari 17.2.1 (17617.1.17.11.12, 17617), rails 7.1.3. 

it completely ignores the filename attribute value and gives the file the name of the link.

workaround:

```rb
send_stream disposition: "attachment; filename=#{I18n.transliterate(csv_filename)}", filename: nil, type: :csv do |stream|
  # ...
end
```

works in firefox though. i guess vendor implementation is flaky.
