### ISSUE TITLE
ActiveRecord has_many associations are not being cached

### ISSUE THREAD

**Issue by erickrom** [rails/rails#39778]
I am working on a Rails 6 application (v 6.0.3.2) and ActiveRecord `has_many` associations are not being cached.  According to https://guides.rubyonrails.org/v6.0/association_basics.html#tips-tricks-and-warnings associations should be cached.  

### Steps to reproduce
Create authors and books tables:
```ruby
class AddAuthorAndBooks < ActiveRecord::Migration[6.0]
  def change
    create_table :authors do |t|
      t.string :name
      t.timestamps
    end

    create_table :books do |t|
      t.belongs_to :author
      t.datetime :published_at
      t.timestamps
    end
  end
end
```
Models:
```ruby
class Author < ApplicationRecord
  has_many :books
end

class Book < ApplicationRecord
  belongs_to :author
end
```

In console, turn on ActiveRecord debug logs and call `author.books` multiple times.  It makes a fetch to the database each time.  It does not happen on the `belongs_to` side of the association.

```ruby
2.6.3 :004 > author.books
D, [2020-07-02T11:19:54.914819 #15599] DEBUG -- :   Book Load (0.2ms)  SELECT `books`.* FROM `books` WHERE `books`.`author_id` = 1 LIMIT 11
 => #<ActiveRecord::Associations::CollectionProxy [#<Book id: 1, author_id: 1, published_at: "1520-07-02 18:18:06", created_at: "2020-07-02 18:18:06", updated_at: "2020-07-02 18:18:06">]> 
2.6.3 :005 > author.books
D, [2020-07-02T11:19:58.095811 #15599] DEBUG -- :   Book Load (0.2ms)  SELECT `books`.* FROM `books` WHERE `books`.`author_id` = 1 LIMIT 11
 => #<ActiveRecord::Associations::CollectionProxy [#<Book id: 1, author_id: 1, published_at: "1520-07-02 18:18:06", created_at: "2020-07-02 18:18:06", updated_at: "2020-07-02 18:18:06">]> 
2.6.3 :006 > book.author
D, [2020-07-02T11:20:01.594088 #15599] DEBUG -- :   Author Load (0.2ms)  SELECT `authors`.* FROM `authors` WHERE `authors`.`id` = 1 LIMIT 1
 => #<Author id: 1, name: "Will Shakespare", created_at: "2020-07-02 18:16:35", updated_at: "2020-07-02 18:16:35"> 
2.6.3 :007 > book.author
 => #<Author id: 1, name: "Will Shakespare", created_at: "2020-07-02 18:16:35", updated_at: "2020-07-02 18:16:35">
```

### Expected behavior
It should not make a database fetch until you call reload on the association.

### Actual behavior
It fetches from the database each time.

### System configuration
**Rails version**: 6.0.3.2

**Ruby version**: 2.6.3

**Comment by victorperez** [comment]
The documentation is misleading because `author.books` doesn't load the association at that point due to lazy loading and calling `inspect` no longer causes it to become loaded https://github.com/rails/rails/pull/28592.

Try using `author.books.load` instead and after that `author.books` should use the association cache.

**Comment by kamipo** [comment]
Fixed the doc by #39794.

**Comment by kdiogenes** [comment]
I just would like to comment that SQL cache is something that happens in the context of a request: https://guides.rubyonrails.org/caching_with_rails.html#sql-caching

In the console, you can control SQL caching using the [QueryCache module](https://api.rubyonrails.org/classes/ActiveRecord/ConnectionAdapters/QueryCache.html#method-i-cache), for example:
```ruby
ActiveRecord::Base.connection.cache do
  # block that will cache queries
end
# or
ActiveRecord::Base.connection.enable_query_cache!
# code that will cache queries
ActiveRecord::Base.connection.disable_query_cache!
```

**Comment by erickrom** [comment]
Thank you all, I now see that the console was not supposed to do SQL caching, although I had an old Rails 5 app that did seem to be doing it, but tested making a request and logging the SQL statements and was able to confirm that it is not re-executing the query in the context of the request.
