### ISSUE TITLE
ActiveJob logger outputs incorrect tags (with Sidekiq)

### ISSUE THREAD

**Issue by jcbpl** [rails/rails#39779]
### Steps to reproduce

Run some concurrent ActiveJobs using Sidekiq. 

1. Create a file named `active_job_test_case.rb`:

```ruby
# frozen_string_literal: true

require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  gem "rails", github: "rails/rails"
  gem "sidekiq", "6.1.0"
end

require "active_job"

ActiveJob::Base.queue_adapter = :sidekiq

class ParentJob < ActiveJob::Base
  def perform
    ChildJob.perform_later
  end
end

class ChildJob < ActiveJob::Base
  def perform; end
end

class OtherJob < ActiveJob::Base
  def perform; end
end

20.times do
  ParentJob.perform_later
  OtherJob.perform_later
end
```

2. Run Sidekiq with this file:

```sh
$ bundle exec sidekiq -r ./active_job_test_case.rb
````

### Expected behavior

Because ChildJob is only enqueued from ParentJob, I expect every "Enqueued ChildJob" message to be prefixed with [ParentJob] log tags, like this:

```log
[ActiveJob] [ParentJob] [2202f1df-778e-406b-a840-8ea403c2306e] Enqueued ChildJob (Job ID: 4997c7b2-4f5f-481f-b4db-1d4c2937dc1b) to Sidekiq(default)
```

### Actual behavior

Depending on job execution, some `ParentJob` output will instead be tagged with the tags for a different concurrent `[OtherJob]` or `[ChildJob]`:

```log
[ActiveJob] [OtherJob] [24e318f1-5054-4c27-8352-477ab4a65d1f] Enqueued ChildJob (Job ID: e75e3a61-d111-4182-ba97-0c06c3512607) to Sidekiq(default)
[ActiveJob] [ChildJob] [a408ba55-777d-41f3-89cc-ea14101092a8] Enqueued ChildJob (Job ID: 0bdf05b9-8989-4d10-9e03-5318bfd6e8fd) to Sidekiq(default)
```

I've found that this test case consistently reproduces the problem, but it's not limited to "Enqueued" messages or enqueuing jobs from other jobs—I've also observed it in production with output generated by [`ActiveJob::LogSubscriber#perform`](https://github.com/rails/rails/blob/master/activejob/lib/active_job/log_subscriber.rb#L52-L68).

From what I've been able to tell, it seems like the [thread-local variable](https://github.com/rails/rails/blob/86480e71faea7ed152efcba633f0011a7c21ee33/activesupport/lib/active_support/tagged_logging.rb#L63) in `ActiveSupport::TaggedLogging` may be loading tags from a separate concurrently enqueued or executed job.

### System configuration
**Rails version**: `edge (master)`. I haven't reproduced with the released gem.

**Ruby version**: `ruby 2.6.5p114`

**Comment by jcbpl** [comment]
Looks like it may be related to [memoization](https://github.com/rails/rails/blob/86480e71faea7ed152efcba633f0011a7c21ee33/activesupport/lib/active_support/tagged_logging.rb#L67-L74) added in 05060ddba170ccb3ba9ce48555ed45400fe1ea96:

```ruby
def tags_text
  @tags_text ||= begin
    tags = current_tags
    if tags.one?
      "[#{tags[0]}] "
    elsif tags.any?
      tags.collect { |tag| "[#{tag}] " }.join
    end
  end
end
```

Seems like the cached result of `current_tags` is being shared between threads. If I undo that change locally I'm no longer able to repro.

**Comment by eugeneius** [comment]
I reverted https://github.com/rails/rails/commit/05060ddba170ccb3ba9ce48555ed45400fe1ea96 in https://github.com/rails/rails/commit/c3913e580cccfd076d92cb78346b4e849ab50066, and added a regression test in https://github.com/rails/rails/commit/19d85783614b6d96600aa39aab88791d0c66a78f. Thanks for reporting this!

**Comment by jcbpl** [comment]
Thanks for the quick fix!
