### ISSUE TITLE
rake task data_cleanup:find_known_invalidations fails when validating OrgIdentifier

### ISSUE THREAD

**Issue by nicolasfranck** [rails/rails#39796]
### Steps to reproduce

```
bundle exec rake data_cleanup:find_known_invalidations
```

### Actual behavior

```
[..]
Checking OrgIdentifier records
      0 records that are not unique per (identifier_scheme_id, org_id)
    rake aborted!
    ActiveRecord::StatementInvalid: Mysql2::Error: Unknown column 'org_identifiers.identifier_id' in 'on clause': SELECT COUNT(*) FROM `org_identifiers` LEFT OUTER JOIN identifiers ON identifiers.id = org_identifiers.identifier_id WHERE `identifiers`.`id` IS NULL
```

Inspecting the task, it looks like it fails in the function `check_presence`.
I think because attribute `identifier` of OrgIdentifier is an exception?

### System configuration

**branch**: master
**Ruby version**: 2.4

**Comment by victorperez** [comment]
This looks like an error with database 

If you review the error it suggest that `identifier_id` column is not available in your database: `Mysql2::Error: Unknown column 'org_identifiers.identifier_id...'` so make sure to review you database to ensure `identifier_id` is available to allow the association to retrieve the data.

Also let you know that the issue tracker is reserved for bugs in Rails itself, would be better to use stackoverflow for this kind of issues: https://stackoverflow.com/questions/tagged/ruby-on-rails

**Comment by nicolasfranck** [comment]
Ah sorry, I reported an issue on the wrong issue list ;-)
