### ISSUE TITLE
def false(...), syntax error, unexpected ..., expecting ')' on upgrading to 6.0.3.1 using docker

### ISSUE THREAD

**Issue by joicemj08** [rails/rails#39811]
### Actual behavior
A syntax error occurs after starting the rails app after upgrading to 6.0.3.1 using ruby 2.7. Works fine in 6.0.2.2
/usr/local/bundle/gems/activerecord-6.0.3.1/lib/active_record/relation/delegation.rb:64:in `module_eval': /usr/local/bundle/gems/activerecord-6.0.3.1/lib/active_record/relation/delegation.rb:65: syntax error, unexpected ..., expecting ')' (SyntaxError)
            def false(...)
                       ^~~

### System configuration

Docker and docker-compose

**Rails version**: 6.0.3.1

**Ruby version**: 2.7.0

**Comment by kamipo** [comment]
Fixed by #39280.
