### ISSUE TITLE
Setting `deliver_later_queue_name` does not take effect in some scenarios

### ISSUE THREAD

**Issue by Zajn** [rails/rails#39810]
In trying to find out why our application had both a `mailer` and `mailers` job queue, I encountered some strange behavior with setting the value of `deliver_later_queue_name` in an initializer. It seems that if you reference `ActionMailer::Base.deliver_later_queue_name` prior to setting `config.action_mailer.deliver_later_queue_name`, then the value you set it to does not take effect.

Note that we addressed this issue by moving our configuration setting from an initializer `config/initializers/mailer.rb` to `application.rb`. Once we set the value of `config.action_mailer.deliver_later_queue_name` there, everything worked as expected and the value we set it to was being used as the default queue for mail.

This still stuck out as unexpected behavior to me, so I thought I would open an issue. Please let me know if I'm overlooking something simple or if this is intentional behavior.

### Steps to reproduce

1. Checkout https://github.com/Zajn/mailer-initializer-test
2. Follow steps in README

### Expected behavior

I would expect that `ActionMailer::Base.deliver_later_queue_name` would match what I set it to in the initializer.

### Actual behavior

The value of `ActionMailer::Base.deliver_later_queue_name` retains the default value of `:mailers` despite setting `config.action_mailer.deliver_later_queue_name` to something different.

### System configuration
**Rails version**:
6.0.3.2
**Ruby version**:
2.7.1

**Comment by tgxworld** [comment]
You should either set `config.action_mailer.deliver_later_queue_name = 'default'` in `application.rb` or use `ActionMailer::Base.deliver_later_queue_name = 'default'` in your initializer. 

>    Application configuration can go into files in config/initializers
>    -- all .rb files in that directory are automatically loaded after loading
>    the framework and any gems in your application.

Since your initializer is only loaded after the framework, setting `config.action_mailer.deliver_later_queue_name` will not have any effect.
