### ISSUE TITLE
ActiveRecord::Calculations.average returns BigDecimal error

### ISSUE THREAD

**Issue by gentlemich** [rails/rails#39814]
### Steps to reproduce
I have a table with a "rating" column (integer) and I would like to know the average of those values.

I run `Review.average(:rating)` and I am then getting an error.

### Expected behavior
It should compute the average of the values

### Actual behavior
It returns an error: `*** NoMethodError Exception: undefined method `new' for BigDecimal:Class`

### System configuration
**Rails version**: 6.0.3.2

**Ruby version**: 2.7.1

**Comment by AndresGarciadelaHuerta** [comment]
Hi @gentlemich ! How did you solve this issue? I'm facing the same problem 😄

**Comment by gentlemich** [comment]
@AndresGarciadelaHuerta somehow it magically worked after I upgraded to Rails 6.0.3.3

**Comment by AndresGarciadelaHuerta** [comment]
> @AndresGarciadelaHuerta somehow it magically worked after I upgraded to Rails 6.0.3.3

Great! Thanks for the quick reply 👍
