### ISSUE TITLE
NoMethodError: undefined method `find_all'

### ISSUE THREAD

**Issue by dragosv** [rails/rails#39822]
### Steps to reproduce

When trying to save a record that has has_many associations an error is raised. Was not able to reproduce yet the error.

### Expected behavior

No error should be raised

### Actual behavior

NoMethodError: undefined method `find_all' for nil:NilClass or NoMethodError: undefined method `find_all' for <Class:...>
~/.rvm/gems/ruby-2.6.5/gems/activerecord-6.0.3.2/lib/active_record/autosave_association.rb line 278 (method associated_records_to_validate_or_save)

### System configuration
**Rails version**:
6.0. It does not happens in Rails 3.2. It started happening in Rails 4.2

**Ruby version**:
Ruby 2.6.5

**Comment by joshmn** [comment]
I believe this method was deprecated in 4 and then removed in 4.2 or 5. I may be wrong though.

**Comment by ddcmendoza** [comment]
For those of you who will see this issue, I think this [issue](https://github.com/rails/rails/issues/34454) is related.

Adding the `optional: true` to the associated model's `belongs_to` fixed the problem for me.
I had the same error with my `User` and `Role` model where `User` has `belongs_to :role` association and `Role` has `has_many :users` association.
