### ISSUE TITLE
The results of boolean column are sometime true, and sometime 1

### ISSUE THREAD

**Issue by kousuke** [rails/rails#39831]
### Steps to reproduce
DB is mysql, and enable is 
| enable                | tinyint(1)   | NO   |     | 1       | 

I executed this and the results are true
```
irb(main):046:0> Student.select("students.enable").limit(2).each do |r|
irb(main):047:1*   puts "#{r.enable}"
irb(main):048:1> end
  Student Load (1.6ms)  SELECT students.enable FROM `students` LIMIT 2
true
true
=> [#<Student id: nil, enable: true>, #<Student id: nil, enable: true>]
```

After then, I execute this(select same column with joining) and result are 1
```
irb(main):043:0> SchoolClass.joins(:student).select("students.enable").limit(2).each do |r|
irb(main):044:1*   puts "#{r.enable}"
irb(main):045:1> end
  SchoolClass Load (1.5ms)  SELECT students.enable FROM `school_classes` INNER JOIN `class_students` ON `class_students`.`school_class_id` = `school_classes`.`id` INNER JOIN `students` ON `students`.`id` = `class_students`.`student_id` LIMIT 2
1
1
=> [#<SchoolClass id: nil>, #<SchoolClass id: nil>]
```

### Expected behavior
I hope all results are same, true or 1.

### Actual behavior
I wrote it on above. 

### System configuration
**Rails version**:
```
# rails -v
Rails 6.0.2.1
```

**Ruby version**:
```
# ruby -v
ruby 2.6.3p62 (2019-04-16 revision 67580) [x86_64-linux]
```

**Comment by kamipo** [comment]
It is because `Student` has attribute types cache from `students` table, but `SchoolClass` doesn't have `enable` attribute and doesn't know that `enable` attribute should have which type.

It is harder to resolve in Active Record side for now.

Can you use `cast_booleans` which is config for mysql2 gem?

https://github.com/brianmario/mysql2#casting-boolean-columns

```yaml
default: &default
  adapter: mysql2
  encoding: utf8mb4
  cast_booleans: true
```

**Comment by kousuke** [comment]
Thanks for your comment.

I understand that this is the spec of AR right now and I may have a solution which you showed. 
I will try using it
