### ISSUE TITLE
Add `attach_base64` to ActiveStorage::Attachment

### ISSUE THREAD

**Issue by alirezaly** [rails/rails#39837]
### Steps to reproduce
Right now if you're willing to upload a file from Stimlus.js you need to encode it in Base64 and decode and pass the blog to the `attach` method.

### Actual behavior

```ruby
      content_type = data.split(",")[0].split("\;").first.split(":").second
      blob = ActiveStorage::Blob.create_after_upload!(
          io: StringIO.new((Base64.decode64(data.split(",")[1]))),
          filename: "#{SecureRandom.hex}.#{Rack::Mime::MIME_TYPES.invert[content_type]}",
          content_type: content_type,
          )
     golfer.avatar.attach(blob)
```

### Expected behavior
```ruby
golfer.avatar.attach_base64(data)
```

### System configuration
**Rails version**:
Rails 6.0

**Ruby version**:
Ruby 2.7.1

**Comment by georgeclaghorn** [comment]
I’d suggest using [`FormData`](https://developer.mozilla.org/en-US/docs/Web/API/FormData) to build a multipart request in JS. Then you can directly attach the file parameter.

**Comment by alirezaly** [comment]
Unfortunately this is not the case over ActionCable (we're using it on Stimulus Reflex) or @georgeclaghorn if you have other solutions that'd be good.

**Comment by georgeclaghorn** [comment]
I don’t understand why you need to upload files via WebSocket. Can you issue a plain-old HTTP request?

**Comment by georgeclaghorn** [comment]
Either way, if Stimulus Reflex requires you to base64-encode uploaded files, decoding them doesn’t seem like Rails’s responsibility—it’s Stimulus Reflex (if it’s doing the encoding) or yours (if you are).

**Comment by georgeclaghorn** [comment]
More constructively… if we want to support uploading files over Action Cable, we should probably modify Action Cable to support that transparently (rather than requiring people to Base64-encode file data to fit in JSON messages).

I’m still having a hard time seeing the benefit of uploading over Action Cable versus HTTP requests, except maybe that it’s more consistent in apps where everything is done over Action Cable.
