### ISSUE TITLE
NoMethodError: undefined method `destroyed?|' for #<Array...>

### ISSUE THREAD

**Issue by dragosv** [rails/rails#39843]
### Steps to reproduce

Active Records with belong_to and has_many pointing to same class

https://gist.github.com/dragosv/4df3d3e1b19f926a448ce651cb30b6e3

### Expected behavior
No error should be raised

### Actual behavior
NoMethodError: undefined method `destroyed?|' for #<Array...>

### System configuration
**Rails version**:
6.0 and Edge

**Ruby version**:
2.6.5

**Comment by alexcameron89** [comment]
Hey @dragosv, I haven't dug into the code other than your script, but I think part of the issue is the fact that there are relations with the same name on Product and they're likely conflicting:

```ruby
class Product < ActiveRecord::Base
  belongs_to :labels

  has_many :labels
end
```

I changed the `belongs_to` to `:label` locally and the script passes.

```ruby
class Product < ActiveRecord::Base
  belongs_to :label

  has_many :labels
end
```

**Comment by dragosv** [comment]
Yes, this is the cause of the issue, conflicting relations, leading to the error.

**Comment by tgxworld** [comment]
@dragosv Can this issue be closed?

**Comment by alexcameron89** [comment]
> Yes, this is the cause of the issue, conflicting relations, leading to the error.

Okay, I see now that you described that in the "Steps to Reproduce". Did this behavior work on a previous version of Rails and is now broken? If not, then I don't think being able to have two relations of the same name in a Model is expected behavior from Rails.

**Comment by dragosv** [comment]
My issue is with the error is that is being cryptic and not representative of the issue. Would like to know there is a relation issue.
