### ISSUE TITLE
Wrong success message in scaffolded destroy method

### ISSUE THREAD

**Issue by hadmut** [rails/rails#39848]
### Steps to reproduce
Use rails 5, 
create new rails app, 
add simple model like bin/rails g scaffold person name:string

add to model

  before_destroy :xxx

  def xxx
    self.errors.add(:base,"something went wrong")
    warn "in xxx"
    throw(:abort)
  end

rake db:migrate
start server
create an object and try to destroy. 

as expected, throw(:abort) prevents from destroying, but the scaffolded controller still reports "was successfully destroyed" and no error messages.

What would be the correct way to determine from the controller wehther the object really was successfully destroyed? A fresh query?

### System configuration
**Rails version**:

**Ruby version**:

**Comment by victorperez** [comment]
> What would be the correct way to determine from the controller wehther the object really was successfully destroyed? A fresh query?

You can do something like this:

```
def destroy
  respond_to do |format|
    if @person.destroy
      format.html { redirect_to people_url, notice: 'Person was successfully destroyed.' }
      format.json { head :no_content }
    else
      format.html { redirect_to people_url, alert: 'Person could not be destroyed.' }
      format.json { render json: @person.errors, status: :unprocessable_entity }
    end
  end
end
```

**Comment by tgxworld** [comment]
Like what @victorperez said, you'll need to alter your controller to check if `@person.destroy` returns `true` or `false` and decide accordingly what you want the controller to do. 

You may check out the discussion in https://github.com/rails/rails/pull/36165 for more context on why this is the default.

**Comment by hadmut** [comment]
Yes, it works. Thanks. 

I wasn't aware and didn't find in the docs, that #destroy gives a reliable return value telling about success or failure.

Shouldn't the proposed code be part of the scaffold boilerplate code?

**Comment by tgxworld** [comment]
> Shouldn't the proposed code be part of the scaffold boilerplate code?

As I understand from https://github.com/rails/rails/pull/35735#issuecomment-659576111, it shouldn't because the code generated by the scaffold does not add any validation that would allow `Model#destroy` to fail
