### ISSUE TITLE
Thor options not getting populated when Rails::Generators.invoke is run.

### ISSUE THREAD

**Issue by geekodour** [rails/rails#39859]
### Steps to reproduce
Basically was trying to use invoke a generator programatically using:
```ruby
Rails::Generators.invoke generator, @args, behavior: :invoke, destination_root: Rails::Command.root
```
the args look something like this:
```ruby
 @args = ["Peeper",
"-l abc xyz",
"-u name:string email:string",
"-r timezone:string currency:string",
"-b something"]

```
As see here:
https://github.com/rails/rails/blob/bcfa51fba6ee529fbe357a183fd5bc8bebf13513/railties/lib/rails/commands/generate/generate_command.rb#L26

### Expected behavior
The generator is run successfully as would have been with `rails g generatorname arg1 --something1 s1 --something2 s2 --something3 s3`

### Actual behavior
The generator does run successfully, but the thor `options` hash does not get populated. So if a generator is not making use of `options` it will not see any issue, but if it is using `options` it will not produce intended results.

If I try to print the `options` hash, I get this:
```
{"skip_namespace"=>false, "something1"=>[], "something2"=>[], "something3"=>[]}
```
Here `something1`,`something2` and `something3` are specified using `class_option` [as described in the official guide.](https://guides.rubyonrails.org/generators.html#adding-command-line-arguments)

While the same would have been populated if I were using `rails g generatorname arg1 --something1 s1 --something2 s2 --something3 s3`

### System configuration
**Rails version**: Rails 6.0.3.2

**Ruby version**: ruby 2.6.5p114 (2019-10-01 revision 67812) [x86_64-linux]

I am suspecting this has to do something with the `load_generators` call: 
https://github.com/rails/rails/blob/bcfa51fba6ee529fbe357a183fd5bc8bebf13513/railties/lib/rails/commands/generate/generate_command.rb#L22

If this is a bug, would love to work on it, if some direction is provided. Otherwise please suggest what am I doing wrong :)

**Comment by composerinteralia** [comment]
There may be something off with the way you set up `@args`. I would expect that to look more like `ARGV`, with each space-separated value as a separate element of the array:

```rb
 @args = ["Peeper",
"-l", "abc", "xyz",
"-u", "name:string", "email:string",
"-r", "timezone:string", "currency:string",
"-b", "something"]
```

If that doesn't help, then please try to [create an executable test case](https://guides.rubyonrails.org/contributing_to_ruby_on_rails.html#create-an-executable-test-case) to help us investigate.

**Comment by composerinteralia** [comment]
I'm going to close this for now, since I think this was bug in the usage rather than in Rails itself. Thanks for the issue!
