### ISSUE TITLE
rails new myapp has unmet peer depedency warning for webpack 

### ISSUE THREAD

**Issue by rlogwood** [rails/rails#39870]
### Steps to reproduce
Create a new rails app `% rails new myapp`

### Expected behavior
create a new rails app with no javascript dependency errors

### Actual behavior
there are several javascript warnings as shown below:
```
...
info fsevents@2.1.3: The platform "linux" is incompatible with this module.
info "fsevents@2.1.3" is an optional dependency and failed compatibility check. Excluding it from installation.
info fsevents@1.2.13: The platform "linux" is incompatible with this module.
info "fsevents@1.2.13" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
warning "webpack-dev-server > webpack-dev-middleware@3.7.2" has unmet peer dependency "webpack@^4.0.0".
warning " > webpack-dev-server@3.11.0" has unmet peer dependency "webpack@^4.0.0 || ^5.0.0".
...
```

### System configuration
Operating system: Ubuntu 20.04 LTS

**Rails version**:6.0.3.2

**Ruby version**:2.7.1p83

**Comment by vipulnsward** [comment]
This is a webpacker related issue. See discussion and possible solutions here: https://github.com/rails/webpacker/issues/1078

**Comment by rlogwood** [comment]
Hi @vipulnsward, I think it would great to resolve this issue in the code base before closing it or #1078 and I'm happy to volunteer to do that. I've responded on the #1078 here https://github.com/rails/webpacker/issues/1078#issuecomment-660653962. Thank You
