### ISSUE TITLE
Js rendering bug

### ISSUE THREAD

**Issue by fastengineer** [rails/rails#39879]
Latest ruby and latest rails.

A simple rendering with remote: true option on view doesn't works like expected.
It is rendering json.

Expected:
Controller fetches photos to @photos variable
A publicindex.html.haml renders collection of _photos.html.haml partial
_photos.html.haml renders collection of _tag.html.haml

Result.
```
Started GET "/ansail?page=2" for ::1 at 2020-07-19 15:34:38 +0300
Processing by PhotosController#publicindex as JS
  Parameters: {"page"=>"2", "instagram_name"=>"ansail"}
  Rendering photos/publicindex.js.erb
  Rendered collection of photos/_photo.json.jbuilder [16 times] (Duration: 24.4ms | Allocations: 10042)
  Rendered photos/_photos.html.haml (Duration: 28.7ms | Allocations: 11244)
  Rendered photos/publicindex.js.erb (Duration: 29.5ms | Allocations: 11991)
Completed 200 OK in 43ms (Views: 28.6ms | ActiveRecord: 5.2ms | Allocations: 17208)
```

If I delete my _photo.json.jbuilder file it renders photos but renders tags as json instead of js.
_photos.html.haml file below
`= render @photos || "There are no photos available."`

**Comment by gregmolnar** [comment]
Can you provide an executable test case based on this template? https://github.com/rails/rails/blob/master/guides/bug_report_templates/action_controller_master.rb
