### ISSUE TITLE
Change HTTP error message type

### ISSUE THREAD

**Issue by chongfai13** [rails/rails#39884]
### Expected behavior
Overly Detailed Internal Error Messages

### Actual behavior
Is it possible to hide or change the HTTP error messages type? like 404, 403 

### System configuration
Rails 6.0.0

ruby 2.5.7p206 (2019-10-01 revision 67816) [x86_64-linux]

**Comment by victorperez** [comment]
It is possible to change the `log_level` to provide less level of detail. Here you have more information: https://guides.rubyonrails.org/debugging_rails_applications.html

Also let you know that the issue tracker is reserved for issues in Rails itself. Please use the [rubyonrails-talk](https://discuss.rubyonrails.org/c/rubyonrails-talk) Discourse or StackOverflow (https://stackoverflow.com/questions/tagged/ruby-on-rails) for questions/help, where a wider community will be able to help you.
