### ISSUE TITLE
db:migrate error because database do not support GET_LOCK

### ISSUE THREAD

**Issue by aldifirmansyah** [rails/rails#39892]
I am using Percona-XtraDB-Cluster which separate write nodes and read nodes. It can reach its maximum potential by not support GET_LOCK feature. But most of the time I execute `rails db:migrate`, it execute GET_LOCK that produce error. Are there any way for me to bypass `rails db:migrate` to execute GET_LOCK?

**Comment by louim** [comment]
Hey!
You are probably looking for the [`advisory_locks` configuration available in Rails 6 +](https://guides.rubyonrails.org/configuring.html#configuring-a-mysql-or-mariadb-database). This feature was added in https://github.com/rails/rails/pull/33691.

**Comment by aldifirmansyah** [comment]
Yes thanks a lot, that's what I needed
