### ISSUE TITLE
Rails 6.0.3.2 : has_many with order scope => Triggers unwanted validation/error

### ISSUE THREAD

**Issue by john-999** [rails/rails#39896]
### Steps to reproduce
    class Book < ApplicationRecord
      has_many :pages, -> { order("page_number") }, dependent: :destroy
      accepts_nested_attributes_for :pages, allow_destroy: true
    end

Submit (create) a new Book via a book form containing one or more nested Page forms.

### Expected behavior
No validation should be triggered, thus no error message should appear.

### Actual behavior
Upon form submission, the validation error ```Pages book is required``` appears.
If I remove the order scope ```-> { order("page_number") }```, then the error does not appear, thus the validation seems not to be triggered.

### System configuration
**Rails version**: Rails 6.0.3.2

**Ruby version**: ruby 2.7.0p0

**Comment by louim** [comment]
Hey!

Can you make a reproducible example [using this template](https://github.com/rails/rails/blob/master/guides/bug_report_templates/active_record_gem.rb)?

**Comment by abhikanojia** [comment]
I found the same issue, unfortunately it is not reproducible on the given template, but it is reproducible on rails App either via console or on minitest.

**Comment by KapilSachdev** [comment]
You have defined `scope` with the `has_many` association and thus an inverse_of relationship with book will not be established.
And if `inverse_of` is not there, `presence` validation will fail as the `association` is not available.

https://github.com/rails/rails/blob/11f54e12b992f6c8d29fd9bedd89ac438a928a2f/activerecord/lib/active_record/reflection.rb#L637-L644

You just need to define `inverse_of: :book` to has_many.
This behaviour has been reported few times and has been asked on [stackoverflow](https://stackoverflow.com/questions/46848627/how-to-prevent-nested-create-failing-with-scoped-has-many-in-activerecord) too.
Duplicate of #20451 (coincidentally an issue by @john-999, though not much related can also be traced back to this #20451)

I think we can add this to documentation.
I would be happy add it if that's something that might get accepted.
