### ISSUE TITLE
Making a where statement on an included association changes the associations on the resulting records

### ISSUE THREAD

**Issue by b-nik** [rails/rails#39893]
### Steps to reproduce
```ruby
# frozen_string_literal: true

require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  gem "rails", github: "rails/rails"
  gem "sqlite3"
end

require "active_record"
require "minitest/autorun"
require "logger"

# This connection will do for database-independent bug reports.
ActiveRecord::Base.establish_connection(adapter: "sqlite3", database: ":memory:")
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :tasks
  create_table :users
  create_join_table :tasks, :users
end

class Task < ActiveRecord::Base
  has_and_belongs_to_many :users
end

class User < ActiveRecord::Base
  has_and_belongs_to_many :tasks
end

class BugTest < Minitest::Test
  def test_association_stuff
    task = Task.create!
    3.times { task.users.create! }

    a = Task.where(id: task.id).map(&:user_ids)
    b = Task.where(id: task.id).includes(:users).where(users: { id: User.first.id }).map(&:user_ids)

    assert_equal a, b
  end
end
```

### Expected behavior
Making a where statement shouldn't change the associations of the returned records from what they are in the database.

### Actual behavior
The returned records have the queried associations changed. It seems like they are filtered by the where statement, but I think saying something like "task.user_ids" from the resulting object should return what is actually stored in the database.

### System configuration
**Rails version**: master, 6, 5

**Ruby version**: 2.5.5

**Comment by drssdinblck** [comment]
In my opinion this is expected behavior. So first I would ask what’s happening under the hood. The includes in combination with the where statement triggers a join with the users table. Of course the result will be filtered by user_id as you specified that in the where clause. Now filtering associations by specific users is a very valid use case. How else would you like to achieve this? If you would follow the logic of what you expect, you would have to do the filtering in app space and not via a db query.

**Comment by b-nik** [comment]
I'm not so sure. When I'm iterating on the results, and i say task.user_ids (and this can be in a context that might be different from how I got that collection of tasks), I'm expecting that I get the user_ids that correspond to that task I'm looking at.

> Also consider what would happen if you returned all the associated objects. 

> Also consider what would happen if you returned all the associated objects. Then you would need to throw away the where clause which you explicitly specified before. 

I think it's perfectly valid to say "I want to see the tasks that are assigned to user A (my where statement), and for each of them see all the users assigned to them (calling user_id for each one at some later point)"

**Comment by b-nik** [comment]
Still an issue with the latest master.
