### ISSUE TITLE
Using non-integer enum types should still be read

### ISSUE THREAD

**Issue by HParker** [rails/rails#39897]
### Steps to reproduce

```ruby
rozen_string_literal: true

require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  gem "rails", github: "rails/rails"
  gem "mysql2"
end

require "active_record"
require "minitest/autorun"
require "logger"

# This connection will do for database-independent bug reports.
ActiveRecord::Base.establish_connection(adapter: "mysql2", username: "rails", database: "activerecord_unittest")
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :posts, force: true do |t|
    t.column :state, "TINYINT(1)"
  end
end

class Post < ActiveRecord::Base
  attribute :unread, :integer
  enum state: {
         start: 0,
         middle: 1,
         finish: 2
       }
end

class BugTest < Minitest::Test
  def test_association_stuff
    p = Post.create(state: :middle)

    assert_equal "middle", p.state # FAILS WITH p.state => nil
  end
end
```

Behavior changed with: https://github.com/rails/rails/pull/39820

Specifically changing

```
decorate_attribute_type(attr, :enum) do |subtype|
```
to
```
attribute(attr, **default) do |subtype|
```

CC: @kamipo 

### Expected behavior
The enum should be read and cast to the correct value

### Actual behavior
The column is always nil

### System configuration
**Rails version**: edge

**Ruby version**: 2.7

**Comment by eileencodes** [comment]
@kamipo we hit this in our app at GitHub and this is our reproduction script. I know it's a little odd to have a tinyint as an enum column but this seems to have caused a change in behavior. Do you have any ideas about that?

**Comment by fduan** [comment]
We use rails 6.1.6 but this did not work for us.

However, using "attribute" API mentioned in the following article did the trick:
https://world.hey.com/jorge/rails-attributes-an-essential-api-you-can-probably-ignore-27147cc2
