### ISSUE TITLE
Can 'rails console' pass '--nomultiline' to IRB?

### ISSUE THREAD

**Issue by dgutov** [rails/rails#39909]
Since there is no environment variable that would affect IRB's editor module in latest versions, the only way to disable the "multiline" stuff is by passing `--nomultiline` as an argument to it.

`rails console` could handle such arguments and set `IRB.conf[:USE_MULTILINE] = false`, for instance.

Also see https://github.com/ruby/irb/issues/113.

**Comment by composerinteralia** [comment]
It is certainly possible to add a `--nomultiline` option, but it seems slightly awkward to me to have an option that no-ops when using another console like pry. Setting `IRB.conf[:USE_MULTILINE] = false` in `.irbrc` seems like an OK way to go here for folks that need to disable this behavior. If that is not suitable then I still think we should wait until there is some resolution in ruby/irb#113 before adding additional options to Rails.

**Comment by dgutov** [comment]
Using `.irbrc` is suboptimal when `rails console` is launched by a program, and not by the user directly. So as an escape hatch it's okay, but asking every user to read the docs from now on and edit their `.irbrc` is too much, I think.

> I still think we should wait until there is some resolution in ruby/irb#113

I could certainly use help with some liaison to the Ruby team. They don't seem to be particularly active on the issue tracker. Or just don't respond to my reports.

**Comment by composerinteralia** [comment]
> They don't seem to be particularly active on the issue tracker. 

In many cases the folks maintaining open source have limited time to do that, so sometimes issues sit around without much activity for longer than we would like). If you are up for it, writing some code and open a PR sometimes gets you further faster. I assume the code change would be similar in spirit to https://github.com/ruby/irb/pull/105/files.

**Comment by dgutov** [comment]
> folks maintaining open source have limited time to do that

Don't need to tell me that.

> I assume the code change would be similar in spirit to

I can do that. But that PR has been sitting for 2 months with no action as well. :-) And as far as changes go, it's a trivial one.

**Comment by dgutov** [comment]
Anyway, it seems like Rails actually has the necessary capability starting with 5.1.4: https://github.com/rails/rails/pull/29010

`rails console -- --nomultiline` works fine (nor does it break `pry-rails` when present).

Thanks for the chat!

**Comment by composerinteralia** [comment]
That's great! Nice find.
