### ISSUE TITLE
action_text using active_admin won't work properly

### ISSUE THREAD

**Issue by aditya2muley** [rails/rails#39913]
am using active admin and active text with rails 6 when I inserted image inside `rich_text_area` using active admin `(f.rich_text_area)` then it appears inside text area immediately but when I tried to save the same then in log file I found `img tag` is not included in parameter. so when I press edit button of article then no image appears.

I have successfully install active_storage and active_text please find below details

model:
```rb
class Article < ApplicationRecord
  belongs_to :category
  has_rich_text :body
end

admin/article.rb:
form do |f|
    f.inputs do
      f.input :title
      f.rich_text_area :body
    end
    f.actions
  end
```

adding image to text_area and after saving the data will produce log :-
```rb
Parameters: {"authenticity_token"=>"xxxxxxxxxxxxxx", "article"=>{"title"=>"bccvb",  "body"=>"<div></div>"}
```

no image, if you edit then also you find there is no image

**Comment by strobilomyces** [comment]
Do you have ImageMagick installed on your server?

**Comment by aditya2muley** [comment]
Yes, it works properly if form is normal but in case of active admin it won’t work properly

**Comment by prathamesh-sonpatki** [comment]
Hi @aditya2muley 

I created a sample app here with minimal setup of Active Admin and ActionText and I am able to upload the files.

https://github.com/prathamesh-sonpatki/active-admin-actiontext-integration

Here is the log from the application - 

```
Started POST "/admin/articles" for ::1 at 2020-07-24 20:53:17 +0530
Processing by Admin::ArticlesController#create as HTML
  Parameters: {"authenticity_token"=>"mEKBhH9PdTIlSKdVm4rx5nWYdpvIVzR8AtidOD52MBy1GoM/Y9EXXhE3oSc1O4+Bx7CNCz/m+lr06/7UlX1m4Q==", "article"=>{"body"=>"<div><figure data-trix-attachment=\"{&quot;contentType&quot;:&quot;image/png&quot;,&quot;filename&quot;:&quot;carbon (26).png&quot;,&quot;filesize&quot;:243664,&quot;height&quot;:930,&quot;sgid&quot;:&quot;BAh7CEkiCGdpZAY6BkVUSSI0Z2lkOi8vYXBwMzk5MTMvQWN0aXZlU3RvcmFnZTo6QmxvYi8xP2V4cGlyZXNfaW4GOwBUSSIMcHVycG9zZQY7AFRJIg9hdHRhY2hhYmxlBjsAVEkiD2V4cGlyZXNfYXQGOwBUMA==--67d29b3a33f65604049d2b47b16ac241be8fd313&quot;,&quot;url&quot;:&quot;http://localhost:3000/rails/active_storage/blobs/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBCZz09IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--6fb1a79cb5a2dc1959b10b435c8c3c5b7591e6ec/carbon%20(26).png&quot;,&quot;width&quot;:1790}\" data-trix-content-type=\"image/png\" data-trix-attributes=\"{&quot;presentation&quot;:&quot;gallery&quot;}\" class=\"attachment attachment--preview attachment--png\"><img src=\"http://localhost:3000/rails/active_storage/blobs/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBCZz09IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--6fb1a79cb5a2dc1959b10b435c8c3c5b7591e6ec/carbon%20(26).png\" width=\"1790\" height=\"930\"><figcaption class=\"attachment__caption\"><span class=\"attachment__name\">carbon (26).png</span> <span class=\"attachment__size\">237.95 KB</span></figcaption></figure></div>"}, "commit"=>"Create Article"}
```

This is how it looks when clicked on edit

![image](https://user-images.githubusercontent.com/621238/88407810-47e11580-cdf0-11ea-901b-958da6f7f90d.png)


Can you check my reproduction app and see if you are doing something different?

**Comment by aditya2muley** [comment]
@prathamesh-sonpatki :- Here is my code I compare both I don't find any difference but still this code is not working
https://github.com/aditya2muley/active_admin_action_text
could you please check and correct me where I'm getting wrong.
