### ISSUE TITLE
ActiveStorage redirect url does not account for relative root 

### ISSUE THREAD

**Issue by farhatahmad** [rails/rails#39918]
### Steps to reproduce

1. Add a relative root to your application (`config.relative_url_root = "/test` in your `development.rb` file)
2. Setup ActiveStorage 
3. Create a model with `has_one_attached :image`
4. Attach a file using file upload
5. Call `rails_blob_url(model.image)`

### Expected behavior
It should return a link to the attached image

### Actual behavior
The initial URL is in the correct form `http://example.com/test/rails/active_storage/......` but once that link is clicked, the link redirects to `http://example.com/rails/active_storage/......` (note the missing relative root).

In situations where multiple applications are present on the same system, this causes the url to return a 404

### System configuration
**Rails version**: 5.2.4.3

**Ruby version**: 2.5.1

**Comment by SamuelCodes** [comment]
I can't reproduce this. Check out this Gist and see if that solves your problem. Apparently relative_url_root only works on asset pipeline by default.

https://gist.github.com/ebeigarts/5450422

**Comment by farhatahmad** [comment]
I'll take a look. Thank you
