### ISSUE TITLE
Upsert_all - unique_by index name - Undefined method `map' 

### ISSUE THREAD

**Issue by leoplct** [rails/rails#39926]
### Steps to reproduce
**function**
`Item.upsert_all(records, unique_by: "unique_null_column_b_column_a")`

**Schema.rb**
`t.index "profile_id, column_a, ((column_b IS NULL))", name: "unique_null_column_b_column_a", unique: true, where: "(column_b IS NULL)"`

### Actual behavior

> NoMethodError (undefined method `map' for "profile_id, column_a, ((column_b IS NULL))":String)

### System configuration
**Rails version**: 6.0

**Ruby version**: 2.7.1

**Comment by eugeneius** [comment]
This problem has been fixed in https://github.com/rails/rails/pull/39517, and will be released in 6.0.4.
