### ISSUE TITLE
What do you think about the sidekiq queue auto-configuration in Rails6?

### ISSUE THREAD

**Issue by wonderer80** [rails/rails#39922]
ActiveJob supports Sidekiq, but ActiveStorage or ActionMailer could not be used properly without specific queue settings. ([https://mikerogers.io/2019/06/06/rails-6-sidekiq-queues](https://mikerogers.io/2019/06/06/rails-6-sidekiq-queues))

I think it would be very convenient if the queues were automatically added when queue_adapter was set to sidekiq.

what do you think that?

**Comment by saeedhassam90** [comment]
ok

**Comment by victorperez** [comment]
Hi @wonderer80 - The issue tracker is reserved for issues in Rails itself. Please use the [rubyonrails-core](https://discuss.rubyonrails.org/c/rubyonrails-core) Discourse to discuss technical Ruby on Rails changes where the core team will be able to review it and give you feedback.

Contributions guide: https://guides.rubyonrails.org/contributing_to_ruby_on_rails.html#what-about-feature-requests-questionmark

**Comment by wonderer80** [comment]
@victorperez Okay, Thank you!
