### ISSUE TITLE
Caching multiple associations to same join table

### ISSUE THREAD

**Issue by wedgex** [rails/rails#39936]
I ran into a scenario where there are multiple `has_one` associations to and through the same join table. If I reference the "through" association before creating the join record, then check the "through" association again after, it is unaware that the join record has been created and still returns nil.

### Steps to reproduce
[Executable test case](https://gist.github.com/wedgex/dad0cbed576659c0c9d3992d80c3a62e)

### Expected behavior

`user.current_organziation` returns the associated record once the join record has been created.

### Actual behavior

`user.current_organization` is `nil`

### System configuration
**Rails version**: 6.0.3

**Ruby version**: 2.6.2p47

**Comment by composerinteralia** [comment]
Thanks for the issue, and for a clear executable test case.

I think this may have to do with some limitations in the way ActiveRecord determines whether an association is stale. For through associations, it looks like we only know how to figure out the target is stale if we are going through a belongs_to.

https://github.com/rails/rails/blob/4a1b57ce70bfbbb73663b4ba68db38cbf9b6a9d4/activerecord/lib/active_record/associations/through_association.rb#L77-L83

That note above the method also makes me wonder if you have hit on one of the cases that we are not capturing.

**Comment by composerinteralia** [comment]
I should also mention that you should be able to work around by manually reloading the user, e.g. `user.reload.current_organization`

**Comment by wedgex** [comment]
Thanks, I had noticed that comment when I was investigating what could be wrong initially. Part of my motivation in opening this was just to see if this is a case that should be expected work or not at all. 

I ended up working around the issue by referencing `user.organization_membership.organization` instead of `user.current_organization`. Unfortunately for us the code that initially loaded the cache, added the new organization, and then tried to check the organization were all in different classes making it not obvious that you should have to reload.

I wish there was some sort of warning as to what was happening, but that's probably not any more feasible than checking for the stale association.
