### ISSUE TITLE
Is there a way to tell `rails` to treat a query as a read query in multi-db setup?

### ISSUE THREAD

**Issue by anmolarora** [rails/rails#39932]
I have a setup where the app generally read/write to primary DB but at some places, I want to read from replica to offload some read load from the primary.
I'm using cursors to fetch data from replica but since rails doesn't treat `declare cursor` query as a read query I have no option but to monkey patch the code https://github.com/rails/rails/blob/fbe2433be6e052a1acac63c7faf287c52ed3c5ba/activerecord/lib/active_record/connection_adapters/postgresql/database_statements.rb#L70 and add `declare cursor` & `fetch forward` to the `READ_QUERY` regex.

Is there is a better way instead of overriding the private constant which I'm currently doing?
### Steps to reproduce
```
class Post
  connects_to database: { writng: :primary, reading: :replica }
end 

Post.connected_to(role: :reading) do
  # raises ActiveRecord::ReadOnlyError
  ActiveRecord::Base.connection.execute("DECLARE test_cursor CURSOR for SELECT * FROM posts")
end
```

### Expected behavior
Error is not raised on `declare cursor` query

### Actual behavior
Error is raised on `declare cursor` query

### System configuration
**Rails version**:
6.0.3.2

**Ruby version**:
2.6.5

**Comment by eugeneius** [comment]
I just backported https://github.com/rails/rails/pull/38042 to 6-0-stable, which means it should be released in 6.0.4.

To answer your question: I'm not sure we should expose a documented way to alter the read query detection. If there's a pattern we're still missing, I'd prefer to see a pull request to improve the behaviour in Rails instead.
