### ISSUE TITLE
warning: instance variable @controller not initialized

### ISSUE THREAD

**Issue by ioquatix** [rails/rails#39937]
I don't know how to reproduce this outside the context of the private application I'm working on, but we have a simple routing spec like:

``` ruby
RSpec.describe FooController, type: :routing do
  it "routes to #index" do
    expect(:get => "/foo").to route_to("foo#index")
  end
```

And with warnings switched on, we get:

```
gems/actionpack-6.0.3.2/lib/action_dispatch/testing/assertions/routing.rb:201: warning: instance variable @controller not initialized
```

It seems to come from this line:

https://github.com/rails/rails/blob/70c9f39039e790c65236a2057fdbcb34002dfa62/actionpack/lib/action_dispatch/testing/assertions/routing.rb#L202

I checked and `@controller` is not defined.

``` ruby
> defined? @controller
=> nil
```

**Comment by ioquatix** [comment]
One quick hack solution would be something like this:

```
controller = @controller if defined? @controller
request = ActionController::TestRequest.create controller&.class
```

**Comment by composerinteralia** [comment]
Reproducible with:

```rb
# frozen_string_literal: true

require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  # Activate the gem you are reporting the issue against.
  gem "rails", github: "rails/rails"
  gem "byebug", require: true
end

require "rack/test"
require "action_controller/railtie"

class TestApp < Rails::Application
  config.root = __dir__
  config.hosts << "example.org"
  config.session_store :cookie_store, key: "cookie_store_key"
  secrets.secret_key_base = "secret_key_base"

  config.logger = Logger.new($stdout)
  Rails.logger  = config.logger

  routes.draw do
    get "/" => "test#index"
  end
end

class TestController < ActionController::Base
  include Rails.application.routes.url_helpers

  def index
    render plain: "Home"
  end
end

require "minitest/autorun"
require "action_controller/test_case"
require "action_dispatch/testing/assertions"

class BugTest < Minitest::Test
  include Rack::Test::Methods
  include ActionDispatch::Assertions::RoutingAssertions

  def setup
    @routes = app.routes
  end

  def test_returns_success
    assert_recognizes({controller: "test", action: "index"}, "/")
  end

  private
    def app
      Rails.application
    end
end
```

We already check `defined? @controller` in a bunch of places in that file, so that may be an acceptable solution for now.

**Comment by kamipo** [comment]
Or, initialize `@controller` in `setup` like as `@routes`.

**Comment by KapilSachdev** [comment]
The hack will work though however, adding `@controller` in the initialize does not get rid of the warning for me as `setup` is not involved in the process while using `assert_recognizes`.  Am i missing something?

_Tested with the rspec by @ioquatix  and minitest by @composerinteralia._

**Comment by composerinteralia** [comment]
@KapilSachdev that's probably because my example included:

```rb
  def setup
    @routes = app.routes
  end
```

If you call super there you should hit the setup block in action_dispatch/testing/assertions/routing.rb

```rb
  def setup
    @routes = app.routes
    super
  end
```

**Comment by KapilSachdev** [comment]
Yes, thats fine (and i too used `super` in your example while testing locally), but will there always be a call to `super`? is it mandatory?
Like particularly using `rpsec`, the warning  does not disappear because rspec calls [`assert_recognizes`](https://github.com/rspec/rspec-rails/blob/2c781aa148942df60aafe4fe855c50f0662cbccd/lib/rspec/rails/matchers/routing_matchers.rb#L27) and `setup` is not involved.

**Comment by KapilSachdev** [comment]
`actionpack/test/dispatch/routing_assertions_test.rb` uses `assert_recognizes` without `setup` being involved, and currently defines `@controller` here.

https://github.com/rails/rails/blob/3c500511e9e822fb9491f215ac6815272ae1b3c1/actionpack/lib/action_controller/test_case.rb#L520

So as already pointed out, checking `defined? @controller` in the `routing.rb` before
```ruby
request = ActionController::TestRequest.create @controller.class 
```
 would be fine as of now.

**Comment by KapilSachdev** [comment]
@composerinteralia should i create a PR for this? or we are looking into more possibilities?

**Comment by composerinteralia** [comment]
Yeah, I think it is worth opening a PR for this. Thanks!
