### ISSUE TITLE
Collection cached not working with `cached` option

### ISSUE THREAD

**Issue by lanzhiheng** [rails/rails#39940]
### Expected behavior
According to the [document](https://guides.rubyonrails.org/caching_with_rails.html#collection-caching), we could let Fragment Caching happen by

```
<%= render partial: 'home/post', collection: lastest_posts, cached: true %>
```

### Actual behavior

Actually, it doesn't happen as expected.  

![image](https://user-images.githubusercontent.com/8858472/88659238-5177bf80-d107-11ea-81d4-db6ef85acf4b.png)

After changing my code to

```
      <% lastest_posts.each do |post| %>
      <% cache post do %>
      <%= render partial: 'home/post', object: post %>
      <% end %>
      <% end %>
```

![image](https://user-images.githubusercontent.com/8858472/88659177-35741e00-d107-11ea-8d26-d1ded422bd35.png)

it works fine. Is it any bug in Rendering Collections with the option `cached`?

### System configuration

**Rails version**:
6.0.3.2

**Ruby version**:
2.7.1

**Comment by lanzhiheng** [comment]
I push the code in my repo but not working. You can check it from my [source code](https://github.com/lanzhiheng/stone/blob/master/app/views/home/index.html.erb)

**Comment by victorperez** [comment]
@lanzhiheng I have downloaded your app and after some testing caching works as expected:

1. I have downloaded the app and set it up
2. I have enabled caching locally (`rails dev:cache`)
3. I have created 15 pots

Then rendered the homepage, the first time the cache hits are 0 (this is expected since the cache has to be generated):

```
  Rendered collection of home/_post.html.erb [0 / 15 cache hits] (Duration: 127.2ms | Allocations: 34073)
  Rendered home/index.html.erb within layouts/application (Duration: 164.5ms | Allocations: 41947)
```

The second time the homepage is rendered the cache is hit as expected.

```
  Rendered collection of home/_post.html.erb [15 / 15 cache hits] (Duration: 1.4ms | Allocations: 657)
  Rendered home/index.html.erb within layouts/application (Duration: 5.7ms | Allocations: 1917)
```

All seems to be working as expected and not bug is found.

**Comment by lanzhiheng** [comment]
@victorperez Oh, I double checked them in my local environment, they work fine now. Thank you very much. 😄 

I think I ignored the cached message `[0 / 15 cache hits]`. 😢 

Closed the Issue.
