### ISSUE TITLE
Exceptions raised in handlers do propagate

### ISSUE THREAD

**Issue by mdavidn** [rails/rails#39962]
https://github.com/rails/rails/blob/4c8e9a3e0872be3de120becd1c2fa9894202aca8/activesupport/lib/active_support/rescuable.rb#L50

The above comment in the `ActiveSupport::Rescuable` documentation, added alone in 2c136ae, appears incorrect. The following demonstration _does_ propagate the exception raised in the handler. I think the behavior is correct, so the documentation is unclear.

```rb
require 'active_support/rescuable'

class MyRescuable
  include ActiveSupport::Rescuable

  rescue_from ArgumentError do
    raise 'in handler'
  end

  def test
    raise ArgumentError, 'test'
  rescue => exception
    rescue_with_handler(exception) || raise
  end
end

MyRescuable.new.test
```

```
Traceback (most recent call last):
        1: from my_rescuable.rb:17:in `<main>'
my_rescuable.rb:11:in `test': test (ArgumentError)
        7: from my_rescuable.rb:17:in `<main>'
        6: from my_rescuable.rb:10:in `test'
        5: from my_rescuable.rb:13:in `rescue in test'
        4: from [redacted]/2.6.5/lib/ruby/gems/2.6.0/gems/activesupport-6.0.3.2/lib/active_support/rescuable.rb:165:in `rescue_with_handler'
        3: from [redacted]/2.6.5/lib/ruby/gems/2.6.0/gems/activesupport-6.0.3.2/lib/active_support/rescuable.rb:92:in `rescue_with_handler'
        2: from [redacted]/2.6.5/lib/ruby/gems/2.6.0/gems/activesupport-6.0.3.2/lib/active_support/rescuable.rb:114:in `block in handler_for_rescue'
        1: from [redacted]/2.6.5/lib/ruby/gems/2.6.0/gems/activesupport-6.0.3.2/lib/active_support/rescuable.rb:114:in `instance_exec'
my_rescuable.rb:7:in `block in <class:MyRescuable>': in handler (RuntimeError)
```

**Comment by composerinteralia** [comment]
I agree this is unclear. I wonder if it was meant to indicate that you won't be able to rescue_from an error raised in another rescue_from handler? Like in this case somebody might expect they could rescue_from `MyError` raised in the `ArgumentError` handler, but that won't work.

```rb
require 'active_support/rescuable'

class MyError < StandardError; end

class MyRescuable
  include ActiveSupport::Rescuable

  rescue_from ArgumentError do
    raise MyError
  end

  rescue_from MyError do
    puts "we won't get here"
  end

  def test
    raise ArgumentError, 'test'
  rescue => exception
    rescue_with_handler(exception) || raise
  end
end

MyRescuable.new.test
```

Any interest in trying to improve that documentation a bit? I would be happy to give you an initial review if you do that.

I also noticed that the [documentation mentions that this is meant for rescuing exceptions in controller](https://github.com/rails/rails/blame/4c8e9a3e0872be3de120becd1c2fa9894202aca8/activesupport/lib/active_support/rescuable.rb#L17), but this isn't really specific to controllers at this point. We also use it in [Action Mailer](https://github.com/rails/rails/blob/b2eb1d1c55a59fee1e6c4cba7030d8ceb524267c/actionmailer/lib/action_mailer/rescuable.rb#L16-L20), [Active Job](https://github.com/rails/rails/blob/40b7d93c5bf04974cfd0201a8e391c499c046f0b/activejob/lib/active_job/execution.rb#L41-L52), [Action Mailbox](https://github.com/rails/rails/blob/440aea595890e89f792c7b7decc760fb225e411e/actionmailbox/lib/action_mailbox/base.rb#L80-L89), and [Action Cable](https://github.com/rails/rails/blob/d9bfafd9b8af6d3ee099d6a3d431744b70666aac/actioncable/lib/action_cable/channel/base.rb#L264-L274). And your commit shows that it can be used in a general purpose way.
