### ISSUE TITLE
Rotating SECRET_KEY_BASE leads to a nested encrypted cookie key and possible overflows

### ISSUE THREAD

**Issue by aprescott** [rails/rails#39964]
### Steps to reproduce

(Largely inspired by https://blog.kmkonline.co.id/rotating-ruby-on-rails-secret-key-base-9a4dcdf0d817 but for an app still using aes-256-cbc.)

1. Set `action_dispatch.use_authenticated_cookie_encryption = false`. (Not technically necessary, but it is to line up with the code below.)
1. Make sure encrypted and signed cookie-backed session storage is in use, with `Rails.application.config.secret_key_base = ENV.fetch("SECRET_KEY_BASE")` (or similar).
1. Set `session[:foo] = "xyz"` in a basic controller action.
1. Set an alternate secret key base in `SECRET_KEY_BASE_ALTERNATE`.
1. Add the below initializer to `config/initializers/cookie_rotation.rb`, setting up key rotation.
1. Stop the server. Swap `SECRET_KEY_BASE` and `SECRET_KEY_BASE_ALTERNATE`. Restart the server.
1. Send a request to a controller action that displays `session.to_h`. (Cookie rotation will have applied just before the inspection.)

```ruby
# config/initializers/cookie_rotation.rb

Rails.application.config.action_dispatch.cookies_rotations.tap do |cookies|
  # All pulled from EncryptedKeyRotatingCookieJar in the aes-256-cbc branch
  # on v5.2.4.3.
  salt = "encrypted cookie"
  sign_salt = "signed encrypted cookie"
  encrypted_cookie_cipher = "aes-256-cbc"

  alternate_secret_key_base = ENV.fetch("SECRET_KEY_BASE_ALTERNATE")

  # `iterations: 1000` matching the Rails session default KeyGenerator params.
  key_generator = ActiveSupport::KeyGenerator.new(alternate_secret_key_base, iterations: 1000)
  key_len = ActiveSupport::MessageEncryptor.key_len(encrypted_cookie_cipher)
  secret = key_generator.generate_key(salt, key_len)
  sign_secret = key_generator.generate_key(sign_salt)

  cookies.rotate :encrypted, secret, sign_secret
end
```

### Expected behavior

`session.to_h` in the final step should equal `{ "session_id" => ..., "foo" => "xyz" }`.

### Actual behavior

`session.to_h` instead has this structure:

```ruby
{
  session_id: "...",
  foo: "xyz",
  value: "NESTED_VALUE",
  path: "/"
}
```

Where `NESTED_VALUE` is itself an encrypted session cookie, and `path: "/"` seems to be part of a `cookies` option (even though we're not dealing with `cookies`, only `session` — `session` shouldn't need `"path"` or `"value"` here).

Note this helper method:

```ruby
def decrypt_and_verify(value:, secret_key_base:)
  key_len = ActiveSupport::MessageEncryptor.key_len("aes-256-cbc")
  generator = ActiveSupport::KeyGenerator.new(secret_key_base, iterations: 1000)

  # EncryptedKeyRotatingCookieJar for the aes-256-cbc branch
  encryptor = ActiveSupport::MessageEncryptor.new(
    generator.generate_key("encrypted cookie", key_len), # secret
    generator.generate_key("signed encrypted cookie"), # sign secret
    cipher: "aes-256-cbc",
    serializer: Marshal
  )

  encryptor.decrypt_and_verify(Rack::Utils.unescape(value))
end
```

Then decrypt `NESTED_VALUE`, and you'll see it's `nil`:

```ruby
# `SECRET_KEY_BASE` and `SECRET_KEY_BASE_ALTERNATE` were swapped
# so the "original" is now `SECRET_KEY_BASE_ALTERNATE`.
original_secret_key_base = ENV.fetch("SECRET_KEY_BASE_ALTERNATE")
decrypt_and_verify(value: "NESTED_VALUE", secret_key_base: original_secret_key_base)
#=> nil
```

The `"value"` and `"path"` keys are present as if we're setting those options on `cookies` instead of `session`, run through an encryption step.

In fact, if you keep swapping `SECRET_KEY_BASE` and `SECRET_KEY_BASE_ALTERNATE` with a request to read `session[:foo]` between each swap, then the `session` cookie will keep growing as each cookie rotation adds another level of `:value` wrapping.

In a production environment where the `SECRET_KEY_BASE`/`SECRET_KEY_BASE_ALTERNATE` swap is only present in part of the available servers, then requests might be processed with "old" and "new" session cookies, repeatedly. The nesting eventually will eventually cookie overflow.

If you manually insert a [`raise if options[:value] == nil` inside of `EncryptedKeyRotatingCookieJar#commit`](https://github.com/rails/rails/blob/v5.2.4.3/actionpack/lib/action_dispatch/middleware/cookies.rb#L647) between steps 6 and 7 above (to catch the rotation logic mid-execution), can determine part of the call chain from the backtrace:

1. [`EncryptedKeyRotatingCookieJar#parse`](https://github.com/rails/rails/blob/v5.2.4.3/actionpack/lib/action_dispatch/middleware/cookies.rb#L638) is called.
1. `SerializedCookieJars#deserialize` is called, [`yield`ing with `-> { rotate = true }`](https://github.com/rails/rails/blob/v5.2.4.3/actionpack/lib/action_dispatch/middleware/cookies.rb#L540) (to the [`Rotator`](https://github.com/rails/rails/blob/v5.2.4.3/activesupport/lib/active_support/messages/rotator.rb#L20)).
1. Rotation took place, so [`self[name] = serialize.load(value)` runs](https://github.com/rails/rails/blob/v5.2.4.3/actionpack/lib/action_dispatch/middleware/cookies.rb#L547), with `serialize.load(value) == { "session_id" => "...", "foo" => "abc" }` (the value within the cookie being rotated).
1. `[]=` calls `commit(options)`, which tries to `encrypt_and_sign` the value of `options[:value]`.
1. Since `options` is `{ "session_id" => "...", "foo" => "abc" }`, there is no `:value` in the hash, so `value: nil` is assigned.

The same issue would seem to apply to `SignedKeyRotatingCookieJar` (since it ostensibly has the same `parse`-`deserialize`-`commit` sequence) although I can't confirm that.

### System configuration

**Rails version**: 5.2.4.3

**Ruby version**: 2.6.5

**Comment by aprescott** [comment]
> In fact, if you keep swapping `SECRET_KEY_BASE` and `SECRET_KEY_BASE_ALTERNATE` with a request to read `session[:foo]` between each swap, then the `session` cookie will keep growing as each cookie rotation adds another level of `:value` wrapping.

A knock-on effect of this behavior is that any prior `session[:value]` value will undergo a level of encryption+signing. If I have `session[:value] == "123"` before the app starts rotating, then `session[:value]` is mapped to (pseudo-code) `encrypted_and_signed("123")`. If an app depends on `session[:value]`, then `session` is effectively broken after rotation is applied.

**Comment by CodeSammich** [comment]
I am also encountering this issue. Please do not close it.

**Comment by CodeSammich** [comment]
Bump

**Comment by skipkayhil** [comment]
> Bump

Closed issues will not receive much attention. If you have a reproducible test case, please open a new issue.
