### ISSUE TITLE
Pass EventObject to new method during Instrumentation

### ISSUE THREAD

**Issue by igbanam** [rails/rails#39976]
### Steps to reproduce

- Create a listener — as a class — for `ActiveSupport::Notifications`
  - this listener class should have one method defined as `def call(event)`
- Subscribe to an event using this new listener class

### Expected behavior

ActiveSupport::Notifications should pass the event to the listener class …as an object.

### Actual behavior

`ActiveSupport::Notifications` passes the event to the listener class as component details of the event. This expects the method to be defined as `def call(name, started, finished, unique_id, data)`. 

### System configuration
**Rails version**: 6

**Ruby version**: 2.6.3

## The Background Story

Following changes in Rails 6, this is possible

```
ActiveSupport::Notifications.subscribe('some_event') do |event|
  puts "Reacting to #{event.name}"
end
```

This convenience is possible because of the [EventObject](https://github.com/rails/rails/blob/fbe2433be6e052a1acac63c7faf287c52ed3c5ba/activesupport/lib/active_support/notifications/fanout.rb#L193) used in instrumentation to wrap the event.

I attempted the below refactor, and it broke because of the number of arguments the method expected

```
ActiveSupport::Notifications.subscribe('some_event', SomeReactor.new)

class SomeReactor
  def call(event)
    puts "Reacting to #{event.name}"
  end
end
```

The idea was to work with an EventObject as the block does. Having a global instrumentation file filled with blocks of listeners just feels wrong.

## The Current Workaround

So I took a peek here 👇 

https://github.com/rails/rails/blob/fbe2433be6e052a1acac63c7faf287c52ed3c5ba/activesupport/lib/active_support/notifications/fanout.rb#L97

…and modified my listener class to read

```
class SomeReactor
  def call(event)
    puts "Reacting to #{event.name}"
  end

  def parameters
    [[:opt]]
  end
end
```

This parameters method is unnecessary to the listener class. It's only there because we cannot currently work with `EventObject`s in listener classes. Thus the ask: we should be able to pass the event object as an argument to the listener class during instrumentation.

**Comment by composerinteralia** [comment]
Yeah, I think it is possible to get this working without you needing to add a `parameters` method. I will open a PR and see what folks think.
