### ISSUE TITLE
Change default semantics for dealing with GET requests with payload

### ISSUE THREAD

**Issue by tgxworld** [rails/rails#39974]
### Steps to reproduce

Currently, Rails merges both request and query parameters irregardless of the HTTP method being used. 

https://github.com/rails/rails/blob/843898c57ac152f6c4a108f3e8b5bd25200efc06/actionpack/lib/action_dispatch/http/parameters.rb#L49-L64

However, this is not a semantics defined in the HTTP specs for `GET`, `HEAD` and `DELETE`.

> [A payload within a GET request message has no defined semantics;
   sending a payload body on a GET request might cause some existing
   implementations to reject the request.](https://tools.ietf.org/html/rfc7231#section-4.3.1) 

The problem with Rails' default semantics specifically for `GET` requests is that the response can't be cached based on the URI since the request body is allowed to inject parameters as well. Digging through the history, the merging has been done ever since the [initial commit of Rails](https://github.com/rails/rails/commit/db045dbbf60b53dbe013ef25554fd013baf88134#diff-c0ab12d3a78d2d5c94a119984d27ed8eR19-R21) but I suspect it was done to support POST requests like `/posts/:id` so that the `id` and the parameters in the request's body can be accessible via a single method call to `parameters`.

### Expected behavior

`ActionDispatch::Http::Parameters#parameters` should not merge in request parameters for `GET`, `HEAD` and `DELETE` requests. 

### Actual behavior

`ActionDispatch::Http::Parameters#parameters` merges request parameters for `GET`, `HEAD` and `DELETE` requests. 

### System configuration
**Rails version**: Rails 6.0.3.2

**Ruby version**: ruby 2.7.1p83 (2020-03-31 revision a0c7c23c9c) [x86_64-linux]

**Comment by rafaelfranca** [comment]
I don't think we have enough arguments to change this behavior. I have seems countless applications that needs to support GET request that accept the request body.

As the RFC says, this behavior has no defined semantics and I think it is ok for Rails to define that the semantic is to merge both.

**Comment by AdamGold** [comment]
Hey! Adam from [Snyk](https://snyk.io) here. If I can just chime in and give my two cents:

Using this source code:
```
class WelcomeController < ApplicationController
  def index
    expires_in 10.seconds, :public => true
    params.each do |key,value|
      Rails.logger.warn "Param #{key}: #{value}"
    end
  end
end
```

While it is not possible to **override** query parameters with GET body parameters, the `params` variable does not distinguish between GET query parameters and body parameters, which can lead to parameter injection that might cause a denial of service in some implementations.
I understand that fixing this is not trivial as ignoring GET body parameters might break many existing implementations, but a solution might be to ignore GET body parameters only when using the ambiguous variable (`params` in this case), while still allowing developers to explicitly use other methods for retrieving body params in GET requests.

**Comment by jub0bs** [comment]
I second @AdamGold's comment above. There should at the very least be an option to discard/ignore GET body parameters. Otherwise, putting Rails behind the like of Cloudflare is a recipe for disaster.

**Comment by rafaelfranca** [comment]
Requiring all users to select which method they want to use based on the the request method the action is seems unnecessary overhead for people that don't plan to put Rails behind something like Cloudfare. If you plan to do that, you can already use `query_parameters` and `request_parameters`.
