### ISSUE TITLE
driven_by discards the 'Capybara.register_driver :selenium' register

### ISSUE THREAD

**Issue by shadydealer** [rails/rails#39987]
I've been trying to get a test which downloads a csv file up and running with the :selenium driver but i can't seem to get it to work.

### Steps to reproduce

```Ruby
specified_driver = ENV["DRIVEN_BY"].try(:to_sym) 
RSpec.configure do |config|
  config.before(:each, type: :system) do
    driven_by specified_driver.blank? ? :rack_test : specified_driver
  end

  config.before(:each, type: :system, js: true) do
    driven_by specified_driver.blank? ? :selenium_headless : specified_driver
  end
end

chrome_prefs = {
  "download.prompt_for_download": false,
  "download.default_directory": Rails.root.join("tmp/downloads/")
}
chrome_options = ::Selenium::WebDriver::Chrome::Options.new(prefs: chrome_prefs)

Capybara.register_driver :selenium do |app|
  Capybara::Selenium::Driver.new(app, browser: :chrome, options: chrome_options)
end
```

### Expected behavior

calling:

```
DRIVEN_BY=selenium rspec spec/...
```

To download the file to the specified path, e.g. `Rails.root.join("tmp/donwloads/")`

### Actual behavior

Downloads it to the browsers default download path

### System configuration
**Rails version**:
 rails (6.0.3.2)

**Ruby version**:
ruby-2.6.5

Going down the stack when calling `driven_by`:

```Ruby
def driven_by(driver, **driver_options, &blk)
   @driver = ::ActionDispatch::SystemTestCase.driven_by(driver, **driver_options, &blk).tap(&:use)
end
```

Then in ActionDispatch::SystemTesting::Driver:

```Ruby
def use
   register if registerable?

   setup
end

...

def registerable?
  [:selenium, :poltergeist, :webkit].include?(@name)
end

def register
  define_browser_capabilities(@browser.capabilities)

  Capybara.register_driver @name do |app|
    case @name
    when :selenium then register_selenium(app)
    when :poltergeist then register_poltergeist(app)
    when :webkit then register_webkit(app)
    end
  end
end

...

def register_selenium(app)
  Capybara::Selenium::Driver.new(app, **{ browser: @browser.type }.merge(browser_options)).tap do |driver|
    driver.browser.manage.window.size = Selenium::WebDriver::Dimension.new(*@screen_size)
  end
end
```

I think the problem is that the `#registerable?` method should also check if the driver has already been registered, like this:

```Ruby
def registerable?
  Capybara.drivers[@name].nil? && [:selenium, :poltergeist, :webkit].include?(@name)
end
```

Running the spec with the modified `#registerable?` downloads the file to the specified path, e.g. `Rails.root.join("tmp/downloads/")`

**Comment by thebravoman** [comment]
With version 6.0.3.2 we have done some debugging on our side and this is how we managed to workaround this. We are returning the capabilities in the options method.

```
RSpec.configure do |config|
  config.before(:each, type: :system) do
    
    # NOTE:
    # Monkey patching the class here until we have a new implementation with 
    # rails next rails
    ::ActionDispatch::SystemTesting::Browser.class_eval do# :nodoc:
      def options
        case name
        when :headless_chrome
          headless_chrome_browser_options
        when :headless_firefox
          headless_firefox_browser_options
        else 
          capabilities
        end
      end
    end

```

I have seen https://github.com/rails/rails/commit/769188e1c32069b67f3c22c5521163c898acc60f which changes the implementation in the ActionDispatch::SystemTesting::Browser, yet I am not sure it which release should include this change.

**Comment by thebravoman** [comment]
Here is actually https://github.com/rails/rails/pull/37792 in which it is discussed.

**Comment by eileencodes** [comment]
It's hard for me to tell if this is the same as #37792, I'm not sure that @shadydealer's problem is the same as @thebravoman described. @shadydealer can you reproduce this in an application without Rspec so someone can debug and check if the linked PR fixes the issue you're seeing.

**Comment by KapilSachdev** [comment]
@shadydealer You can also point rails to master in your Gemfile (`gem 'rails', github: 'rails/rails'`) and verify if it is no more reproducible.

**Comment by shadydealer** [comment]
Hi @eileencodes, we were debugging it together with @thebravoman and we got to the conclusion that I could pass a block to the `driven_by` method, which would solve my problem to override the options, but it didn't seem to work because of we have the action_dispatch code prior to #37792. 
I was just following [Capybara's readme](https://github.com/teamcapybara/capybara#configuring-and-adding-drivers) which said we can override the driver registration, but since `driven_by` registers the driver on it's own it never actually executed the registration block i've defined. So in short- yes #769188e should fix my issue.

**Comment by shadydealer** [comment]
@KapilSachdev i will try it ASAP and get back to you on that

**Comment by KapilSachdev** [comment]
@shadydealer does using master resolves the issue?

**Comment by shadydealer** [comment]
@KapilSachdev @eileencodes Hello again and very sorry for the late response. I just sat down and reproduced it in a new application and pointing rails to the master branch does fix our issue. Thanks for the help!
