### ISSUE TITLE
Excessive ReadIOPS on the database after upgrade from 5.0.7 to 5.1.7 and 5.2.4.3

### ISSUE THREAD

**Issue by Kiza** [rails/rails#39991]
After upgrade from 5.0.7 to 5.1.7 and 5.2.4.3, our DB experiences heavy ReadIOPS. We have to downgrade back to rails 5.0.7. For the purpose of this comparison, we only upgraded rails packages, and leave other packages untouched, and removed packages which are tied to a specific rails version. 

### Steps to reproduce
After upgrade rails from 5.0.7(RPOD) to 5.1.7 and 5.2.4.3, there are a heavy ReadIOPS on the DB.

### Expected behavior

Before the upgrade (rails 5.0.7), the ReadIOPS required are in the range of hundreds. 

![rails-5 0 7-vs-prod](https://user-images.githubusercontent.com/2462821/89500138-c3c95d80-d7f3-11ea-8989-3bc47045419c.png)

### Actual behavior
Below data is collected when we mirror PROD (5.0.7) traffic to 5.1.7 and 5.2.4.3 servers. 

The ReadIOPS required are few thousands more per second after the upgrade. 

![rails-5 1 7-vs-prod](https://user-images.githubusercontent.com/2462821/89499673-fc1c6c00-d7f2-11ea-9cad-86fc1a0ba521.png)

![rails-5 2 4 3-vs-prod](https://user-images.githubusercontent.com/2462821/89499676-fe7ec600-d7f2-11ea-90b0-95030bfd8523.png)

### System configuration
**Rails version**: 5.1.7 and 5.2.4.3

**Ruby version**: 2.5.3

**Comment by tgxworld** [comment]
I'm not sure if the information provided here is sufficient for the Rails team to act on. Is there more information that you can provide like a reproduction script or application?

**Comment by Kiza** [comment]
@tgxworld 

We were trying to pinpoint the exact cause of problem, but we have a real hard time to correlate high ReadIOPS to a specific query or API endpoint. 

We cannot reproduce it in our DEV / STG environment either. Only seems to be an issue when they server start to take heavy load.

I cannot really share our source code here. 

Just want to check whether any changes could lead to this behaviour?
