### ISSUE TITLE
ActiveRecord::Migration::CheckPending middleware is slow when lots of migration files are present

### ISSUE THREAD

**Issue by jviney** [rails/rails#39994]
### Steps to reproduce

* Add a few hundred files to `db/migrate`
* Request durations in any environment with `config.active_record.migration_error = :page_load` increase significantly.

This is due to the `ActiveRecord::Migration::CheckPending` middleware adding around 8-10 milliseconds per request in my testing of a project with >300 migrations.

If others agree this is an issue, I can submit a patch. We can run this middleware much more efficiently.

### Expected behavior

Request duration should not be as affected by the number of migration files.

### Actual behavior

Requests slow down when lots of migration files are present.

### System configuration
**Rails version**: 5.2.2. The `ActiveRecord::Migration::CheckPending` middleware and `MigrationContext` don't appear to have changed much in Rails 6, so I'm pretty confident the problem exists there too.

**Ruby version**: 2.6.6

**Comment by eugeneius** [comment]
The performance of this middleware was improved a lot in https://github.com/rails/rails/pull/37395, which will be released in Rails 6.1.
