### ISSUE TITLE
 ActiveStorage::FileNotFoundError  after submit but the file is storing but not validating

### ISSUE THREAD

**Issue by Xavihernandez93** [rails/rails#39997]
hi team ,
iam trying to upload pdf file and validation to accept pdf files only with less than 1 mb but when i click submit it returns me an error like :

ActiveStorage::FileNotFoundError in PdfsController#create
 ActiveStorage::FileNotFoundError 

but the file is getting uploaded but its not validating the size or returns me the show page

my model.rb 
```
class Pdf < ApplicationRecord
  after_commit :attachment1
  #after_commit(on: %i[ create update ]) { attachment_changes.delete(name.to_s).try(:upload) }



	has_one_attached :attachment

	validates :attachment, presence: true, blob: { content_type: ['application/pdf']  }
  validates :attachment, presence: true, size: { less_than: 1.megabytes , message: 'PDF should be less than 1 MB' }
  #validates :attachment, presence: true, size: { less_than: 1000000.bytes , message: 'PDF should be less than 1 MB' }


  def attachment1
    attachment_path = "#{Dir.tmpdir}/#{attachment.filename}"
      File.open(attachment_path, 'wb') do |file|
      ile.write(attachment.download)
  end   

  private

    def check_file_type
      if attachment.attached? && !attachment.content_type.in?(%w(application/msword application/pdf))
          errors.add(:attachment, 'Must be a PDF or a DOC file')
      end
    end

  end

end
```

### System configuration
**Rails version 2.71 **:

**Ruby version 6**:

**Comment by KapilSachdev** [comment]
_Please correct your ruby and rails version info in the description._

Issue reports two errors, one for `ActiveStorage::FileNotFoundError` and other for validations not working

As the correct rails version is not provided, I;m supposing you are using `6.0.3.2` version and `active_storage` as of now [does not](https://github.com/rails/rails/issues/33741) have any validators.
A [PR](https://github.com/rails/rails/pull/35390) in progress for that (though closed being stale).

Based on the validators in the code, i think you are using [active_storage_validations](https://github.com/igorkasyanchuk/active_storage_validations).
Please confirm if `active_storage_validations` is added to your `Gemfile`

For `ActiveStorage::FileNotFoundError` can you please provide a reproduction using this [template](https://github.com/rails/rails/blob/master/guides/bug_report_templates/active_storage_gem.rb) or maybe a rails app.

_Prima-facie the issue  it does not seems like a rails issue and should either be reported in `active_storage_validations` issue tracker or `stackoverflow`._

**Comment by KapilSachdev** [comment]
@Xavihernandez93, were you able to fix the issue or still encountering it?

**Comment by Xavihernandez93** [comment]
yeah we can close this
