### ISSUE TITLE
Npm registry availability issues

### ISSUE THREAD

**Issue by freiden** [rails/rails#39993]
Hi, it seems like the last versions of the javascript project maintained by the Basecamp team are unavailable on npm registry including Stimulus:

### Steps to reproduce

`npm install @stimulus/polyfills` or `npm install @rails/webpacker` or `npm install @rails/ujs`

### Expected behavior

The selected dependency is installed

### Actual behavior

> npm ERR! code E404
> npm ERR! 404 Not Found - GET https://registry.npmjs.org/@rails%2fujs - Not found
> npm ERR! 404
> npm ERR! 404  '@rails/ujs@latest' is not in the npm registry.
> npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
> npm ERR! 404
> npm ERR! 404 Note that you can also install from a
> npm ERR! 404 tarball, folder, http url, or git url.

### System configuration
Latest versions of `@stimulus/polyfills` or `@rails/webpacker` or `@rails/ujs`

I created a matching ticket on the [Stimulus](https://github.com/stimulusjs/stimulus/issues/323) project.

**Comment by adrienpoly** [comment]
The issues is on the side of NPM
https://status.npmjs.org/incidents/cksjqc1w11v5

**Comment by freiden** [comment]
Thanks @adrienpoly
