### ISSUE TITLE
`ruby2_keywords` acts differently in ruby 2.8

### ISSUE THREAD

**Issue by leequarella** [rails/rails#40004]
In ruby 2.8, Methods using `ruby2_keywords` will no longer keep empty keyword splats, those are now removed just as they are for methods not using `ruby2_keywords`. (https://docs.ruby-lang.org/en/master/NEWS_md.html)

Rails uses `ruby2_keyworks` to pass through args in a number of places, this could cause issue in end user code that depends on receiving those empty hashes.

Example usage in rails:
https://github.com/rails/rails/blob/master/activejob/lib/active_job/enqueuing.rb#L20-L24

### Actual Behavior

In ruby 2.7: `MyJob.perform_later("foo", **empty_hash) #=> *args == ["foo", {}]`
In ruby 2.8: `MyJob.perform_later("foo", **empty_hash) #=> *args == ["foo"]`

### Expected Behavior

In ruby 2.7: `MyJob.perform_later("foo", **empty_hash) #=> *args == ["foo", {}]`
In ruby 2.8: `MyJob.perform_later("foo", **empty_hash) #=> *args == ["foo", {}]`

### System Configuration
**Rails version**: 6.0.3.2.af01810

**Ruby version**: 2.8.0-dev

---

This script passes in 2.7 and fails in 2.8:
([gist](https://gist.github.com/leequarella/e0549158f53e9d2563c75c8fe42a0a77)) 
```ruby
# frozen_string_literal: true

require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  gem "rails", github: "rails/rails"
end

require "active_job"
require "minitest/autorun"

class BuggyJob < ActiveJob::Base
  def perform
    puts "performed"
  end
end

class BuggyJobTest < ActiveJob::TestCase
  def test_stuff
    assert_enqueued_with(
      job: BuggyJob,
      args: [{}]
    ) do
      BuggyJob.perform_later(**{})
    end
  end
end
```

---

Simplified ruby example showing `ruby2_keywords` behavior:

```ruby
require "minitest/autorun"
require "logger"

class Testington
  def a(options = {})
    b(**options)
  end

  def b(*args)
    return args
  end
  ruby2_keywords(:b) if respond_to?(:ruby2_keywords, true)
end

class TestTest < Minitest::Test
  def test_fails_in_2_8
    assert_equal Testington.new.a, [{}]
  end
end
```

**Comment by HParker** [comment]
The normal case we ran into at GitHub is when we pass `**kwargs` to a job from a method that takes an options hash, for example:

```ruby
def do_some_work(id, options = {})
  MyJob.perform_later(id, **options)
end

class MyWorker
  def perform(id, work_hard: false)
    # ...
  end
end
```

This can be updated to pass on both ruby versions by only passing the keyword arguements the job uses.
For example:

```ruby
def do_some_work(id, options = {})
  MyJob.perform_later(id, work_hard: options[:work_hard])
end

class MyWorker
  def perform(id, work_hard: false)
    # ...
  end
end
```

It seems like the new behavior is ok, it might make sense to add a deprecation warning when we see someone is passing empty hash keyword arguments to `assert_enqueued_with` and say this behavior is not supported.
