### ISSUE TITLE
ActiveRecord::Migration::CheckPending middleware can cause deadlocks when autoloading (using the classic autoloader)

### ISSUE THREAD

**Issue by cjlarose** [rails/rails#40009]
### Steps to reproduce

1. Add some code in an initializer that'll be invoked whenever a database connection is checked out of the pool. In my application, it was something like the code that follows. The implementation of `SystemStats` is left out, but the only thing that's important is that `SystemStats` is defined in an autoloaded directory.

```ruby
module DbConnectionPoolStatsReporter
  def self.report(pool)
    pool_stats = pool.stat
    tags = ["spec_name:#{pool.spec.name}"]
    [:size, :connections, :busy, :dead, :idle, :waiting, :checkout_timeout].each do |stat|
      SystemStats.report_gauge stat: "db_connection_pool.#{stat}",
                               value: pool_stats[stat],
                               tags: tags
    end
  end
end

ActiveRecord::ConnectionAdapters::Mysql2Adapter.set_callback :checkout, :after do |conn|
  DbConnectionPoolStatsReporter.report conn.pool
end

ActiveRecord::ConnectionAdapters::Mysql2Adapter.set_callback :checkin, :after do |conn|
  DbConnectionPoolStatsReporter.report conn.pool
end
```

2. Modify a file in an autoloaded directory and make some concurrent web requests

### Expected behavior

All web requests complete as expected

### Actual behavior

Concurrent requests can deadlock. The particular interleaving that causes it to happen is something like this:

```
| Thread A                       | Thread B                                |
|--------------------------------|-----------------------------------------|
| gets interlock share lock      |                                         |
|                                | gets interlock share lock               |
|                                | gets CheckPending lock                  |
|                                | tries to autoload SystemStats           |
|                                | tries to upgrade to exclusive interlock |
| tries to get CheckPending lock |                                         |
|                                |                                         |
```

Thread A wants the CheckPending lock, but holds a shared lock on the Interlock, while Thread B wants an exclusive lock on the Interlock, but holds the CheckPending lock. Neither thread can make progress and the server stalls.

This is similar to the deadlock condition described in #34310, just with a different lock. The lock described in that issue was related to database connections, and this one refers to the lock used in the CheckPending middleware introduced in #37395

### System configuration
**Rails version**: 5d3b9f7c8753d74132bf312fdc10356e1d9a0b33 (`master` at the time of reporting). The new CheckPending middleware implementation isn't in a released version of Rails yet.

**Ruby version**: 2.6.1

**Comment by cjlarose** [comment]
I'm not really sure what the right fix is here, but just to brainstorm:

1. Can the `@mutex` be removed safely from the CheckPending middleware? If so, that would allow threads to make progress, allowing concurrent threads to eventually acquire the exclusive interlock.
2. If the `@mutex` in CheckPending can't be removed, maybe it can be made into a `LoadInterlockAwareMonitor` instead, though I'm not sure if that'd help
3. Should users just be dissuaded from adding and code that references autoloaded constants in ActiveRecord connection adapter callbacks?
4. Should we ignore this issue since it's probably not a problem when using zeitwerk?

**Comment by eileencodes** [comment]
Hey @cjlarose thanks for the report. Can you make a new application that reproduces this bug? It's easier for us to debug / determine next steps than trying to make sure we're implementing the steps correctly. Thanks!

**Comment by cjlarose** [comment]
@eileencodes of course! I've created https://github.com/cjlarose/rails-check-pending-migrations-deadlock, a minimal new Rails app that reliably generates the bug.

When creating the app, I found one additional requirement: `actiontext` has to be disabled. Otherwise, a _different_ deadlock problem rears its head. That deadlock problem is described separately in #36810.

So that brings the list of requirements for reproducing the problem to this:

* Use a version of Rails that has the cool new fast implementation of `ActiveRecord::Migration::CheckPending` as introduced in #37395
* Use the classic autoloader (not zeitwerk)
* Disable the use of `actiontext` (just don't load it at all)
* Perform some reference to autoloaded constants while the mutex in `CheckPending` is held.

**Comment by tgxworld** [comment]
@cjlarose Thank you for the application. I was able to reliably reproduce the problem and submitted a fix in https://github.com/rails/rails/pull/40022. It resolves the issue you described locally but it'll be good if you can try out the fix as well in case I missed something.

**Comment by cjlarose** [comment]
@tgxworld Thanks for taking a look! I'll leave feedback in the PR itself.

**Comment by cjlarose** [comment]
Opened up my own solution to the problem in #40032

**Comment by tgxworld** [comment]
@cjlarose I was thinking about this yesterday I don't think the problem lies with the `CheckPending` migrations middleware. The root cause of the problem for your case is that any mutex around `ActiveRecord::Base.connection` will cause the problem because checking out a connection may result in an autoload. A mutex around `ActiveRecord::Base.connection` can happen in the framework code or in another library so I don't think this is a bug in the framework at the moment. 

I'm not that familiar with code reloading in Rails but something from the [docs for the classic autoloader](https://guides.rubyonrails.org/threading_and_code_execution.html#permit-concurrent-loads) stood out  

> Other blocking operations performed inside the Executor block (which includes all application code), however, can needlessly retain the running lock. If another thread encounters a constant it must autoload, this can cause a deadlock.

**Comment by cjlarose** [comment]
As far as I understand it, the classic autoloader isn't threadsafe by default, but with very careful application of tools like the Load Interlock, `LoadInterlockAwareMonitor`, and `permit_concurrent_loads`, it's possible to use the classic autoloader safely in multithreaded environments.

The problem with the `CheckPending` middleware, I think, is that it lacks the appropriate safeguards to make it compatible with the classic autoloader in multithreaded environments. But the tools exist to make it work and are already employed in different parts of Rails. It's just a matter of figuring out what tools we can employ in this particular situation to prevent deadlocks, while keeping the implementation efficient.

**Comment by cjlarose** [comment]
I updated my example app that reproduces this issue: https://github.com/cjlarose/rails-check-pending-migrations-deadlock

This issue is still reproducible on Rails master at commit a750b0cf8fe362ef762f34972e2d1ec302795174

**Comment by cjlarose** [comment]
This is still an active issue in Rails on branch `main` at commit 59b3d372a8f7da5b3f50471575bd8189c531b3ab

I [updated](https://github.com/cjlarose/rails-check-pending-migrations-deadlock/commit/8721322f8210af510c1fec4122f07018cbf5105e) my reproducible example as a demonstration

**Comment by cjlarose** [comment]
@eileencodes I was able to reproduce this problem on that latest `main`. I rebased my PR https://github.com/rails/rails/pull/40032 and was able to verify that it still fixes the problem.

Let me know if there's anything I can do to help this along.
