### ISSUE TITLE
[Angular Universal + ActionCable] ERROR TypeError: ActionCable.WebSocket is not a constructor

### ISSUE THREAD

**Issue by arpansac** [rails/rails#40002]
### Steps to reproduce
- Add ActionCable to your Angular 2+ application
- Setup Angular Universal from [angular.io](https://angular.io)
- Setup ActionCable js and make a connection in the <app-root> component itself. Run it with `ng s`, should run fine
- Add this line to server.ts `(global as any).WebSocket = require('ws');` and install ws with `npm i ws`
- Run: `npm run dev:ssr` to build and serve for SSR (server side rendering)
- It will build successfully (hopefully)
- Open the home page and the console will show an error: ERROR TypeError: ActionCable.WebSocket is not a constructor

### Expected behavior
- It should render the page smoothly without errors

### Actual behavior
- Displays: ERROR TypeError: ActionCable.WebSocket is not a constructor

### System configuration
**Rails version**: 6

**Ruby version**: 2.5

**Angular version**: 10

**Comment by KapilSachdev** [comment]
Can you provide a sample app that reproduces the issue.

**Comment by arpansac** [comment]
I solved this, the socket has to be connected once the app loads in the browser. 
It'd be great to have some documentation for Angular and Actioncablejs, probably a sample app.

**Comment by KapilSachdev** [comment]
Issue tracker like these (and even platforms like `stackoverflow`) can be thought of as an `unofficial` documentation as people get answer to their issues, code behaviours (and much more) via these, which may or may not get place in the `official` documentation.

So if you have solved this, please add more details like how you solved your build issues with `ssr` and `actioncable` (as `It will build successfully (hopefully)` feels like there might be) and the actual resolution of your issue with code script or boilerplate app.

This might be helpful for anyone looking for similar issues that might get stumble upon here .

**Comment by arpansac** [comment]
Hey @KapilSachdev 
As mentioned briefly I just needed to check if the platform is browser and then connect the socket. Here's some more details:

The root cause of the problem
- In Angular Universal, since I am rendering the page on the server side before sending it to the browser, we can't make the socket connection before the browser loads the page. But in my code, the socket connection was being initiated during the loading of <app-component> itself.

The solution
- @Inject(PLATFORM_ID) private platformId: Object   ---> In the constructor
- isBrowser: boolean = isPlatformBrowser(this.platformId); -- > Just a variable which is set to true when the browser gets loaded

Initiate the socket connection when isBrowser is true (use an if condition)

I agree that issue trackers can be thought of as an unofficial documentation, but then having an official one puts a stamp of confirmation on it and is always better. More so, writing documentation for React, Angular and Vue would help us a lot. 

Let me see if I can make a PR for this. :)
