### ISSUE TITLE
Rails 6.0.1.3 rendering .haml file as plain text instead of html (react-rails)

### ISSUE THREAD

**Issue by Geesu** [rails/rails#40026]
### Steps to reproduce

Create a show.haml file with a react component (using react-rails gem) which has its arguments rendered. Example:

```
= react_component("MyComponent", render(template: 'javascript/my_component.jbuilder'))
```

This entire file will be rendered as plain text instead of as html. I suspect it is due to `render(template: 'javascript/my_component.jbuilder')`. I did some digging but couldn't narrow it down to a PR which caused this change, but I did discover the following:

In rails 6.0.1.3, `template.format` [here](https://github.com/rails/rails/blob/v6.0.3.2/actionview/lib/action_view/renderer/template_renderer.rb#L11) now returns nil.

But in Rails 5.2.4.2, `template.formats` [here](https://github.com/rails/rails/blob/v5.2.4.3/actionview/lib/action_view/renderer/template_renderer.rb#L12) would return an array including `html`.

### Expected behavior
I would expect the template to be rendered as html.

### Actual behavior
The template is rendered as plain text.

### System configuration
**Rails version**: 6.0.1.3

**Ruby version**: 2.7.1

**Comment by composerinteralia** [comment]
Are you able to link to a sample repo that reproduces this? That would help folks help debug what is going on here, and to verify whether the behavior is still broken on master. If that is not possible, you could also try doing a bisect to find the commit that changed this behavior (either by pointing your Gemfile to a local copy of rails and running `git bisect`, or manually by pointing your Gemfile to a commit in the middle of 5.2.4.2 and 6.0.1.3 and seeing if it works, then doing the same thing halfway in one direction or the other, etc.)
