### ISSUE TITLE
Initializers will be loaded twice if it is required by other initializers

### ISSUE THREAD

**Issue by khiav223577** [rails/rails#40021]
Similar to #19690, but I wonder whether it also does not have to require other files in initializers in my case, too. 

Is using `require` in initializers a bad practice?

### Steps to reproduce

1. Add the following two files into the `initializers` folder.
2. Run Rails console.

```rb
# initializers/extensions/module/enumerator_method.rb

puts "load enumerator_method.rb"

class Module
  if method_defined?(:enumerator_method)
    warn 'Module#enumerator_method is defined'
  else
    def enumerator_method(*methods)
      methods.each do |method|
        origin_method = :"#{method}_without_enumerator_method"
        next if method_defined?(origin_method)
        alias_method(origin_method, method)

        define_method(method) do |*args, &block|
          next enum_for(__method__, *args) if !block
          next send(origin_method, *args, &block)
        end
      end
    end
  end
end
```

```rb
# initializers/extensions/enumerable.rb

require_relative 'module/enumerator_method'

module Enumerable
  if method_defined?(:filter_map)
    warn 'Enumerable#filter_map is defined'
  else
    def filter_map
      result = []
      each do |elem|
        mapped_elem = yield(elem)
        result << mapped_elem if mapped_elem
      end
      return result
    end

    enumerator_method :filter_map
  end
end
```

### Expected behavior

The `enumerator_method.rb` should be loaded only once.

### Actual behavior

`enumerator_method.rb` is loaded twice. See:

```
$ spring stop
Spring stopped.

$ rails c
load enumerator_method.rb
load enumerator_method.rb
Module#enumerator_method is defined
Running via Spring preloader in process 15113
Loading development environment (Rails 5.2.4.3)
2.5.5 :001 > 
```

### System configuration
**Rails version**:
5.2.4.3

**Ruby version**:
2.5.5

**Comment by p8** [comment]
I think initializers are loaded alphabetically. So `initializers/extensions/enumerable.rb` is loaded before `initializers/extensions/module/enumerator_method.rb`.
You could add another `puts` to  `initializers/extensions/enumerable.rb`

**Comment by composerinteralia** [comment]
Initializers are loaded with `load`, rather than `require`, so they will load again even if you already required them. Given that, I would not advise requiring one initializer from another.

https://github.com/rails/rails/blob/459db0a69e1537ac484c26b252ff40543dc0aaed/railties/lib/rails/engine.rb#L668-L672
