### ISSUE TITLE
ActionDispatch(?) does not process multiple files when existing records are sent with the same request

### ISSUE THREAD

**Issue by benben** [rails/rails#40036]
### Steps to reproduce
```
class Product < ApplicationRecord
  has_many :images
  accepts_nested_attributes_for :images
end
```
```
class Image < ApplicationRecord
  has_one_attached :file
end
```

Now imagine the product form can change existing images and uploading new ones. For this I would have an input like
```
<input type"text" name="product[images_attributes][1][caption]" ?>
```
Be aware of the `[1]` to refer to an existing record, which will lead to the following params:
```
{"plant"=>{"images_attributes"=>{"1"=>{"caption"=>"new value"}}}}
```
If I would want to upload new images in the same request, I would need to create a file field which looks like this
```
<input multiple="multiple" type="file" name="product[images_attributes][2][file]" />
```
since using only `product[images_attributes][][file]` would try to create an array, which does not work with the existing record pattern from above.

### Expected behavior
When selecting multiple files in this scenario, multiple files get created and the existing image gets updated.

### Actual behavior
When selecting multiple files in this scenario, only the last file gets created and the existing image gets updated.

When only new images are created, using
```
<input multiple="multiple" type="file" name="product[images_attributes][][file]" />
```
is working and is creating multiple images correctly. (But cannot be used together with updating an existing record as described above)

### System configuration
**Rails version**: 6.0.3.2

**Ruby version**: 2.7.1p83 (2020-03-31 revision a0c7c23c9c) [x86_64-darwin19]

**Comment by composerinteralia** [comment]
Thanks for the issue. I am not sure I am fully understanding what you are trying to accomplish. Could you provide a sample application that reproduces this bug?

**Comment by benben** [comment]
Hi @composerinteralia,

Thanks for waiting for my late reply!
I've created a repo here: https://github.com/benben/myshop

Here are the steps I took to create it:
```
➜ ruby -v
ruby 2.7.1p83 (2020-03-31 revision a0c7c23c9c) [x86_64-darwin19]
➜ rails -v
Rails 6.0.3.2
➜ rails new myshop
➜ rails g scaffold product name:string
➜ rails g model Image caption:string product_id:bigint
➜ rails active_storage:install
➜ rails db:migrate
 ```

Then change the product form to `multipart: true` and adding this to it:

```
<input multiple="multiple" type="file" name="product[images_attributes][][file]" id="product_images_attributes_files" />

  <%= form.fields_for :images do |images_form| %>
      <li>
        <%= images_form.label :caption %>
        <%= images_form.text_field :caption %>

        <%= images_form.label :file %>
        <%= images_form.file_field :file %>
      </li>
  <% end %>
```
as per https://edgeguides.rubyonrails.org/form_helpers.html#nested-forms

Now try the following:

1) Create a product and add some images (works!)
2) edit a product with some images and set some image captions (works!)
3) try to add more pictures to a product with already existing images and you will get

```
Invalid or incomplete POST params
Started POST "/products/1" for ::1 at 2020-08-28 09:41:36 +0200

ActionController::RoutingError (No route matches [POST] "/products/1"):

actionpack (6.0.3.2) lib/action_dispatch/middleware/debug_exceptions.rb:36:in `call'
web-console (4.0.4) lib/web_console/middleware.rb:132:in `call_app'
web-console (4.0.4) lib/web_console/middleware.rb:28:in `block in call'
web-console (4.0.4) lib/web_console/middleware.rb:17:in `catch'
web-console (4.0.4) lib/web_console/middleware.rb:17:in `call'
actionpack (6.0.3.2) lib/action_dispatch/middleware/show_exceptions.rb:33:in `call'
railties (6.0.3.2) lib/rails/rack/logger.rb:37:in `call_app'
railties (6.0.3.2) lib/rails/rack/logger.rb:26:in `block in call'
activesupport (6.0.3.2) lib/active_support/tagged_logging.rb:80:in `block in tagged'
activesupport (6.0.3.2) lib/active_support/tagged_logging.rb:28:in `tagged'
activesupport (6.0.3.2) lib/active_support/tagged_logging.rb:80:in `tagged'
railties (6.0.3.2) lib/rails/rack/logger.rb:26:in `call'
sprockets-rails (3.2.1) lib/sprockets/rails/quiet_assets.rb:13:in `call'
actionpack (6.0.3.2) lib/action_dispatch/middleware/remote_ip.rb:81:in `call'
actionpack (6.0.3.2) lib/action_dispatch/middleware/request_id.rb:27:in `call'
rack (2.2.3) lib/rack/method_override.rb:24:in `call'
rack (2.2.3) lib/rack/runtime.rb:22:in `call'
activesupport (6.0.3.2) lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'
actionpack (6.0.3.2) lib/action_dispatch/middleware/executor.rb:14:in `call'
actionpack (6.0.3.2) lib/action_dispatch/middleware/static.rb:126:in `call'
rack (2.2.3) lib/rack/sendfile.rb:110:in `call'
actionpack (6.0.3.2) lib/action_dispatch/middleware/host_authorization.rb:82:in `call'
webpacker (4.3.0) lib/webpacker/dev_server_proxy.rb:23:in `perform_request'
rack-proxy (0.6.5) lib/rack/proxy.rb:57:in `call'
railties (6.0.3.2) lib/rails/engine.rb:527:in `call'
puma (4.3.5) lib/puma/configuration.rb:228:in `call'
puma (4.3.5) lib/puma/server.rb:713:in `handle_request'
puma (4.3.5) lib/puma/server.rb:472:in `process_client'
puma (4.3.5) lib/puma/server.rb:328:in `block in run'
puma (4.3.5) lib/puma/thread_pool.rb:134:in `block in spawn_thread'
```
Since the file field uses an array for `images_attributes` while the existing images use a hash for `images_attributes`.

**Comment by composerinteralia** [comment]
Thanks for the sample application. That helps a lot.

The problem here is that Rack is not unable to parse these parameters since, as you mentioned, one of them is an array and the other a hash:

```rb
parser = Rack::QueryParser.new(Rack::QueryParser::Params, 17, 4)

parser.parse_nested_query("product[images_attributes][][caption]=value")
#=> {"product"=>{"images_attributes"=>[{"caption"=>"value"}]}}

parser.parse_nested_query("product[images_attributes][][caption]=value")
#=> {"product"=>{"images_attributes"=>{"0"=>{"caption"=>"value"}}}}

parser.parse_nested_query("product[images_attributes][][caption]=value&product[images_attributes][0][caption]=value")
#=> Rack::QueryParser::ParameterTypeError (expected Hash (got Array) for param `images_attributes')

parser.parse_nested_query("product[images_attributes][0][caption]=value&product[images_attributes][][caption]=value")
#=> Rack::QueryParser::ParameterTypeError (expected Array (got Rack::QueryParser::Params) for param `images_attributes')
```

`images_attributes` can't be both a hash and an array at the same time, so it makes sense to me that Rack would raise an error here.

You should be able to address this in your application by making sure you use an array all the time, perhaps like this:

```erb
<input multiple="multiple" type="file" name="product[images_attributes][<%= product.images.length %>][file]" id="product_images_attributes_files" />
```

---

I think there still may be a bug here though: your example is returning a 404 rather than a 400 for invalid params. If we make a `GET` request with similar params (.e.g /?product[]=a&product[0]=b), we do indeed get a 400 response. But in this case, since we aren't able to parse the params and identify this is a `PATCH` request (via the `_method` param), it gets treated as a `POST` and so we see an unexpected 404 `No route matches [POST] "/products/1"`.

**Comment by composerinteralia** [comment]
@jonathanhefner I see your 👀 on this. I have a possible fix in the works, but would be happy to chat with you about it. Basically I think it we make any reference to request.parameters before we get into routing we could get a 400 instead.

**Comment by jonathanhefner** [comment]
> I see your :eyes: on this.

You caught me!  I meant to say, "Very interesting!  Excellent investigating!" :smile:

> I threw in a new middleware to verify it would fix the problem and it does: https://github.com/rails/rails/compare/master...composerinteralia:check-params?expand=1. It might also make sense to incorporate a check into one of the existing middlewares, or directly into the routes app.

I haven't delved deeply into the Action Dispatch code, so I can't offer an informed opinion at the moment.  A new middleware to validate the format for the params is an interesting approach.  My first thought would have been to make the current param parsing code raise a specific error that could be translated to a 400, but it sounds like the order of operations (i.e. when we resolve the route) might make that difficult?

**Comment by composerinteralia** [comment]
> You caught me! I meant to say, "Very interesting! Excellent investigating!" 😄

Haha. You mean we don't all interpret emoji reactions the same way. 😆

**Comment by benben** [comment]
Thanks for working on that!

Wouldn't it be better if the `file_field` form helper just adds an index to the field like in @composerinteralia's example fix?

**Comment by composerinteralia** [comment]
> Wouldn't it be better if the file_field form helper just adds an index to the field

As you say this back to me, I realize my example doesn't actually work if you add more than one file at a time 😭, so we can't do that.

**Comment by benben** [comment]
> As you say this, I realize my example doesn't actually work if you add more than one file at a time 😭, so we can't do that.
AS you say this, I realize that that was the actual problem I am facing. If the file field would split out multiple files as an hash, rather than an array, everything would be awesome!

**Comment by benben** [comment]
Because rails can digest hashes always, not matter if existing or not. But arrays only work if there is no objects yet.

**Comment by benben** [comment]
Any news on this? Do I understand it correctly: While @composerinteralia's fix will make the error more understandable, the problem will still exist?

**Comment by composerinteralia** [comment]
Yup, my PR is only meant to improve the error. I don't see much else we can do on the Rails side. You might still be able to get the desired behavior by using two totally separate fields, one for updating and another for the new files, then doing some extra work server side to turn them into what you need.
