### ISSUE TITLE
create_with overwrites scope attributes when creating a new record

### ISSUE THREAD

**Issue by humphreyja** [rails/rails#40034]
Maybe I am not treating the `create_with` function correctly but I use it primarily to set default values and to inherit values from related records on create. I've found that it overwrites scope attributes set by where clauses even though they are AFTER the `create_with` statement. This leads to some surprising behavior as seen below.

### Steps to reproduce

```ruby
# frozen_string_literal: true

begin
  require 'bundler/inline'
rescue LoadError => e
  warn 'Bundler version 1.10 or later is required. Please update your Bundler'
  raise e
end

gemfile(true) do
  source 'https://rubygems.org'

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  gem 'rails', '6.0.3.2'
  gem 'sqlite3'
end

require 'active_record'
require 'minitest/autorun'
require 'logger'

# This connection will do for database-independent bug reports.
ActiveRecord::Base
  .establish_connection(adapter: 'sqlite3', database: ':memory:')
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :parents, force: true do |t|
    t.string :first_name
    t.string :last_name
  end

  create_table :kids, force: true do |t|
    t.integer :parent_id
    t.string :first_name
    t.string :last_name
  end
end

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

class Parent < ApplicationRecord
  has_many :kids

  def children
    kids.create_with(last_name: self.last_name)
  end
end

class Kid < ApplicationRecord
  belongs_to :parent
end

class BugTest < Minitest::Test
  def test_association_stuff
    parent = Parent.create!(first_name: 'Joe', last_name: 'Dirt')

    kid = parent.children.where(last_name: 'Anderson').first_or_create
    
    assert_equal kid.last_name, 'Anderson'
  end
end
```

### Expected behavior
`kid.last_name == 'Anderson'`

### Actual behavior
`kid.last_name == 'Dirt'`

### System configuration
**Rails version**: 6.0.3.2

**Ruby version**: 2.6.6

**Comment by composerinteralia** [comment]
Nice reproduction script! I can confirm that this fails the way you described: the attributes specified in `create_with` will always take precedence to those specified in `where`. This is because when [building the scope](https://github.com/rails/rails/blob/b68eea379524b2690117977562fbd195f52a4fc6/activerecord/lib/active_record/relation.rb#L687-L692) we start with all the `where` values (i.e. `where_values_hash`), then after that we apply the `create_with` values (i.e. `create_with_value`). I dug through the history a bit, and while I don't see it explicitly mentioned I don't get the impression applying `where` conditions after `create_with` was ever meant to work in this way.

**Comment by humphreyja** [comment]
Ok interesting. I didn't know about the `where_values_hash` attribute/method. I might be able to use that with `create_with_value` to satisfy my use case for this. 

I think the confusing part with this is that it does allow you to keep chaining the scope. It feels like to me as a `default_value` for the new record. So I would most likely use `create_with` very early on in the chain before further scoping and modifying it (maybe with additional `create_with` calls). 

But I do see the use case for a `persistent_create_with` that will not change no matter what the scope is. I would probably use a method like that to automatically assign a record to a particular user account so that in another part of the software I don't accidentally set that to nil or maliciously gets set to a different user account.

Additionally, I would find it beneficial for the attributes that will be applied to a newly created record to be available to an existing record.  So calling something like `first_or_initialize(:with_new_attributes)` for example so that an existing record and a new record can be in the exact same state before continuing.

Just some thoughts on it
