### ISSUE TITLE
Idea / Warn when using ActionCable with async adapter from the rails console

### ISSUE THREAD

**Issue by aclarembeau** [rails/rails#40038]
Hi Rails team and thanks for the awesome work you're doing, 

Sorry in advance if I'm formatting this improperly, but I found no place for ideas/suggestions. 
When we create a new Rails project, the default adapter for ActionCable is async, which means that we cannot use it from the rails console to communicate with the main application (see this Stackoverflow issue: https://stackoverflow.com/questions/42554323/actioncable-broadcast-not-working-from-console-in-rails). 

I think this could be a problem for newcomers that try to understand ActionCable using the default setup. 
So, I'm wondering: would it be possible to add a warning when using action cable from rails console when configured with an Async Adapter? 

Best,

**Comment by composerinteralia** [comment]
Hey there! Rails uses the issue tracker mostly for bug reports, which should generally include a script or sample application that reproduced the bug (see the [contributing guide](https://guides.rubyonrails.org/contributing_to_ruby_on_rails.html) for details). The place to discuss ideas is the [rails-core mailing list](https://discuss.rubyonrails.org/c/rubyonrails-core/5).
