### ISSUE TITLE
Deprecation Warning in ActiveSupport::Cache::Store#fetch with block

### ISSUE THREAD

**Issue by mc962** [rails/rails#40064]
### Steps to reproduce
I'm observing a deprecation warning that seems to be originating from ActiveSupport::Cache::Store#fetch. 
```
...active_support/cache.rb warning: Passing the keyword argument as the last hash parameter is deprecated
...active_support/cache.rb warning: The called method `get_entry_value` is defined here
```
I think I can see how my code is getting there, I don't see why it's triggering the deprecation warning.

The code calls fetch like:
```ruby
Rails.cache.fetch("some_key_namespace.some-key") do
  some_cache_refresh_method
end
```
I'm fairly certain, after stepping through with a RubyMine debugger, that it's happening in the #fetch method itself and not caused by anything in the method within the fetch block.
The warning appears to be triggered by `get_entry_value`, which seems to be called called when a previously cached entry is retrieved.
In particular, this is for the in-memory MemoryStore implementation that comes with Rails.
This particular get_entry_value call that triggers the deprecation warning has arguments that look like:
- `entry` =  `ActiveSupport::Cache::Entry`
  This was some existing entry, with values like:
  - created_at - Some Float timestamp
  - expires_in - nil
  - `s` - some integer
  - vaue - some integer
  - version - nil
- `name` = `'some_namespace.some-key'`
- `options` = `{}`
I'm guessing that `options` is somehow triggering this warning, but I would have thought that a blank options Hash would not trigger this warning.
Note that this code path is only executed when a block is passed to #fetch, otherwise it simply calls #read, which doesn't have this issue.

**Reproduced in a blank application**
[Github Repo](https://github.com/mc962/active_support_deprecation_warning)

- Generate basic new Rails application rails new active_support_deprecation_warning --skip-template --skip-active-record
- Generate some new controller with a method bundle exec rails g controller static_pages home
- Add to StaticPagesController#home
```
Rails.logger.info 'BEFORE FIRST FETCH'
Rails.cache.fetch(:a) do
    Random.rand(10)
end
Rails.logger.info 'BETWEEN FIRST AND SECOND FETCH'
Rails.cache.fetch(:a) do
    Random.rand(10)
end
Rails.logger.info 'AFTER SECOND FETCH'
```
- Enable caching with `bundle exec rails dev:cache`
- Start server with `bundle exec rails server`
- Navigate to `localhost:3000/static_pages/home`

**Log Message**
```
Started GET "/static_pages/home" for ::1 at 2020-08-18 10:45:43 -0400
Processing by StaticPagesController#home as HTML
SEPARATOR
Started GET "/static_pages/home" for ::1 at 2020-08-18 10:49:07 -0400
Processing by StaticPagesController#home as HTML
BEFORE FIRST FETCH
BETWEEN FIRST AND SECOND FETCH
/home/my_user/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/activesupport-6.0.3.2/lib/active_support/cache.rb:330: warning: Passing the keyword argument as the last hash parameter is deprecated
/home/my_user/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/activesupport-6.0.3.2/lib/active_support/cache.rb:710: warning: The called method `get_entry_value' is defined here
AFTER SECOND FETCH
  Rendering static_pages/home.html.erb within layouts/application
  Rendered static_pages/home.html.erb within layouts/application (Duration: 0.4ms | Allocations: 185)
/home/my_user/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/sprockets-rails-3.2.1/lib/sprockets/rails/helper.rb:355: warning: Using the last argument as keyword parameters is deprecated; maybe ** should be added to the call
/home/my_user/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/sprockets-4.0.2/lib/sprockets/base.rb:118: warning: The called method `[]' is defined here
[Webpacker] Everything's up-to-date. Nothing to do
Completed 200 OK in 16ms (Views: 10.7ms | Allocations: 7351)
```

### Expected behavior
No deprecation warning is expected to be triggered.

### Actual behavior
The following deprecation warning is triggered:
```
...active_support/cache.rb warning: Passing the keyword argument as the last hash parameter is deprecated
...active_support/cache.rb warning: The called method `get_entry_value` is defined here
```

### System configuration
Rails 6.0.3.2
  activesupport 6.0.3.2  

Ruby 2.7.1

**Comment by KapilSachdev** [comment]
Can you check against the `6-0-stable` branch?
I think its already fixed as mentioned in [comment](https://github.com/rails/rails/issues/39227#issuecomment-631166466).
Looks like a duplicate of #39227.

**Comment by mc962** [comment]
Thanks for pointing that out, you're right that it does fix it.

I'll go ahead and close this one then.
