### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by jdobkins** [rails/rails#40060]
Hi!

I want to let you know that I found a broken link on this page: 

https://doc.bccnsoft.com/docs/rails-guides-3.2-en/getting_started.html

It's a link to a Rails tutorial.

If you are interested, here is a good tutorial you can link to instead : https://www.theblogstarter.com/intro-to-ruby-on-rails/

Hope you are doing well during this strange time in the world.

Regards,
Melissa

### System configuration
**Rails version**:

**Ruby version**:

**Comment by KapilSachdev** [comment]
Thanks for the report.
The [page](https://doc.bccnsoft.com/docs/rails-guides-3.2-en/getting_started.html) described is not maintained by rails community.
This issue tracker is meant for the bug reports in the rails source code. So this is not a good place for this issue. 

You should consider following [latest stable version rails guides](https://guides.rubyonrails.org/getting_started.html)
