### ISSUE TITLE
Integration test path helper doubles after request

### ISSUE THREAD

**Issue by ConnorSheremeta** [rails/rails#40078]
### Steps to reproduce

- Create an a mountable engine and mount it onto an app with a path (mount Blorgh::Engine, at: "/path")
- Set up a route inside of the engine to the engine's root
- Create an integration test in the app calling the route helper of the engine
- Notice that after the request is made the path helper (***_path) now doubles the path ("/path/path")
### Expected behavior
The path helper should not double the path after a request has been made.

### Actual behavior
The path helper doubles the path after a request has been made.

### System configuration
**Rails version**:
6.0.3.2
**Ruby version**:
ruby 2.7.0p0

**Comment by ConnorSheremeta** [comment]
_Might_ be related to https://github.com/rails/rails/issues/21459

**Comment by Adrian-Hirt** [comment]
@ConnorSheremeta  I think I'm having a similar issue. Is it the path of the engine that's doubled, or is the application itself running in a path and that path gets doubled?

My application is running under /app_path, and I have a mountable engine running in /engine, so it should be accessable via /app_path/engine.

However, using `blorgh.*_path` doubles the **app path** to /app_path/app_path/engine.

Weird enough, if I use `Blorgh::Engine.routes.url_helpers.*_path`, the url is correct with `/app_path/engine`.

What's the behaviour if you use `Blorgh::Engine.routes.url_helpers.*_path`?

If that's also the case for you, I can see if I'm able to create a reproduction script or application to reproduce it, else I'll open an issue for my problem.
