### ISSUE TITLE
translation missing: en.number.nth.ordinalized when using number ordinalize in rails 6

### ISSUE THREAD

**Issue by geekontheway** [rails/rails#40084]
### Steps to reproduce
2.6.2 :022 > 2.ordinalize
 => "translation missing: en.number.nth.ordinalized"

### Expected behavior
2.6.2 :022 > 2.ordinalize
 => "2st"

### System configuration
**Rails version**:
6.0.3.2
**Ruby version**:

ruby 2.6.2p47 (2019-03-13 revision 67232) [x86_64-linux]

**Comment by KapilSachdev** [comment]
It does not looks like a rails bug, but rather an issue with application locales.
Can you verify if `en.number` or `en.number.nth` is not overridden.

**Comment by jonathanhefner** [comment]
@geekontheway I believe @KapilSachdev is correct.  A quick to verify would be to run the following in the Rails console:

```ruby
I18n.load_path.reverse!
I18n.backend.load_translations
2.ordinalize
```

And see if you get the correct result.  If so, one of your locales files must be overriding the entries from `/home/leslie/.rvm/gems/ruby-2.6.2/gems/activesupport-6.0.3.2/lib/active_support/locale/en.rb`.

**Comment by KapilSachdev** [comment]
@geekontheway Were you able to verify using the code provided by @jonathanhefner ?

**Comment by geekontheway** [comment]
@KapilSachdev  @jonathanhefner sorry i  forgot to look back here, it works now, thanks you all.

**Comment by KapilSachdev** [comment]
Glad to hear. We close the issue as it's resolved.
