### ISSUE TITLE
ActiveStorage potentially leaks information by including the original filename in URLs

### ISSUE THREAD

**Issue by wilg** [rails/rails#40090]
Not sure the best way to frame this issue, but there is a potential leak of personal or private information that occurs when uploading files via ActiveStorage.

Users may not expect the filename they used when uploading a file to be retained, but ActiveStorage always includes the original file name in _all_ URLs associated with it – whether it's a variant, on a CDN, etc.

This could allow information included in the filename to be distributed to other people without the user's intent.

I would recommend that by default ActiveStorage not include the filename information in generated URLs, and possibly just don't upload it in the first place. The existing behavior could be opt-in which would also allow for backwards compatibility.

Sort of a small thing, but you could imagine some sneaky ways this could bite users:

- A user downloads a document from one service and uploads it to a Rails app using ActiveStorage. But, maybe that service stored the document with an internal identifier or authentication key in the filename. An attacker could recover that information, which may not be present in the document itself, just by viewing the URL or getting access to a database dump and use it to compromise another service.
- A user might upload a profile photo to some service, but the filename could be something like `anne_johnson_summer_in_havana_2002.jpg` which could reveal their full name, whereabouts, and past activities when they did not intend to.

If there is an opportunity to not save potentially sensitive information, it's probably good to avoid it by default.

### System configuration
**Rails version**: 6.0.3.2

**Ruby version**: 2.7.1

**Comment by iraszl** [comment]
This assumes that users expect the filename to be kept confidential, while they upload a file that is meant to be public. I'm not sure that's a typical expectation, but surely there will be some people who have this expectation. And there will be people who make the mistake you described. But there will also be people who have the opposite expectation.

There is a significant benefit to include the filename in the URL for SEO reasons. Google and other search engines use filenames as part of the indexing process. In your example the name of the person and the name of the city in the filename will help google understand the context better, which will bring more relevant traffic to the site.

**Comment by wilg** [comment]
According to the docs "By default, Active Storage assumes private access to services", which implies a private-by-default approach that should extend to the filename metadata, and would also break SEO. Privacy is more important than SEO, but both use cases can easily be handled by allowing the current behavior as opt-in. Right now it is simply not possible to avoid capturing and broadcasting the filename.

**Comment by wilg** [comment]
This is still present as far as I know.

**Comment by nickjj** [comment]
I wouldn't mind seeing a solution to let us choose the file name of the uploaded file before it's written out so we can perform this action without having to make a 2nd update query to update the file name in the active storage table.

From a practical sense it seems reasonable to want to control the content that ends up on our servers. For example someone can upload a file with a repulsive file name to attract weird SEO results to your site as a form of attack. It also subjects everyone to be able to see these file names if they view the source of your site.

For me it boils down to wanting to control what ends up being presented on my site. An end user shouldn't have that much power and there's no easy way to override this with Active Storage. In most cases I'd want the file to be a hashid of the user id or something that's super quick to calculate but will guarantee no duplicates.
