### ISSUE TITLE
Issue with custom validation message

### ISSUE THREAD

**Issue by airled** [rails/rails#40102]
### Steps to reproduce
Create new rails app.
Create model:
```ruby
class CreateMymodels < ActiveRecord::Migration[6.0]
  def change
    create_table :mymodels do |t|
      t.text :myfield
      t.timestamps
    end
  end
end

class Mymodel < ApplicationRecord
  validates :myfield,
            format: {with: /[\d+]/, message: I18n.t('custom_error') }
end
```
Allow several locales in `application.rb`:
```ruby
config.i18n.available_locales = [:ru, :en]
config.i18n.default_locale = :ru
```
Create messages for different locales:
`ru.yml`:
```yml
ru:
  custom_error: 'ru error'
```
`en.yml`:
```yml
en:
  custom_error: 'en error'
```
Go to rails console and try this:
```ruby
irb(main):001:0> I18n.locale
=> :ru
irb(main):002:0> m = Mymodel.create
irb(main):003:0> m.errors.full_messages
=> ["Myfield ru error"]
irb(main):004:0> I18n.locale = :en
irb(main):005:0> I18n.locale
=> :en
irb(main):006:0> m = Mymodel.create
irb(main):007:0> m.errors.full_messages
=> ["Myfield ru error"]
```

### Expected behavior
`m.errors.full_messages` should return `["Myfield en error"]` with `:en` locale

### Actual behavior
`m.errors.full_messages` returns `["Myfield ru error"]` with `:en` locale

---------------

It works absolutely fine, if I pass proc instead of direct message:
```ruby
class Mymodel < ApplicationRecord
  validates :myfield,
            format: {with: /[\d+]/, message: proc { I18n.t('custom_error') }}
end
```
Console:
```ruby
irb(main):001:0> I18n.locale
=> :ru
irb(main):002:0> m = Mymodel.create
irb(main):003:0> m.errors.full_messages
=> ["Myfield ru error"]
irb(main):004:0> I18n.locale = :en
irb(main):005:0> I18n.locale
=> :en
irb(main):006:0> m = Mymodel.create
irb(main):007:0> m.errors.full_messages
=> ["Myfield en error"]
```

### System configuration
**Rails version**:
```
bundle exec rails -v 
Rails 6.0.3.2
```
**Ruby version**:
```
ruby -v
ruby 2.7.1p83 (2020-03-31 revision a0c7c23c9c) [x86_64-linux]
```

**Comment by composerinteralia** [comment]
Thanks for the issue!

The behavior you are describing does match what I would expect. In your example your call  `I18n.t('custom_error')` at the time the `Mymodel` class first loads. So the translation will match whatever the locale was when the class was loaded.

Consider how Ruby will execute this line:

```rb
  validates(:myfield, format: {with: /[\d+]/, message: I18n.t('custom_error') })
```

To call the `validates` method, Ruby needs to evaluate the arguments first. And to construct hash for the for `format` keyword argument it needs to evaluate `I18n.t('custom_error')`. So if the locale is `:en` when the file loads, you can think of that line as first evaluating to:

```rb
  validates(:myfield, format: {with: /[\d+]/, message: 'en error' })
```

At that point changing the locale has no effect.

Using a block, as in your later example makes sense. Or you can use a symbol, which has roughly the same effect:

```rb
  validates(:myfield, format: {with: /[\d+]/, message: :custom_error })
```

There may be some room for documentation improvements here, either in the [internationalization docs](https://guides.rubyonrails.org/i18n.html#translations-for-active-record-models) or the [validations docs](https://guides.rubyonrails.org/active_record_validations.html#message). This is not the first time I have seen folks use I18n at class definition time, which probably does not work quite how they intended.

**Comment by airled** [comment]
@composerinteralia Thank you for explanation! Now it makes sense to me. I thought, `validate` method evaluates message on every request and now i see that it does not. So the right choice here will be to use proc since it evaluates block on every validation call. Right?

**Comment by composerinteralia** [comment]
> So the right choice here will be to use proc since it evaluates block on every validation call. Right?

Yup, a block should work.

I usually use a symbol (as in my last example), which also resolves on every validation call. I think the one constraint with the symbol approach is that your translation needs to be in one of the standard locations (I usually write the symbol, then let the error message tell me where I am supposed to put the translation 😄).

**Comment by airled** [comment]
@composerinteralia OK. Thank you so much! Absolutely clear for me now!
