### ISSUE TITLE
Actionable PendingMigrationError does not dump schema

### ISSUE THREAD

**Issue by philipbjorge** [rails/rails#40105]
### Steps to reproduce
1. Create a pending migration
2. Visit localhost:3000
3. See a `PendingMigrationError` error screen with a button to run migrations
4. Click the button

### Expected behavior
Migrations are executed and the schema/structure.sql is dumped

### Actual behavior
Migrations are executed

### System configuration
**Rails version**: 6.0.3.2

**Ruby version**: 2.6.6

**Comment by philipbjorge** [comment]
@gsamokovarov --
This seems like the sort of PR I could reasonably contribute to Rails.

It looks like the current exception defines an action that runs the migrate task.
https://github.com/rails/rails/blob/master/activerecord/lib/active_record/migration.rb#L137

My hunch is that I could expand that to include this sort of command:
```
      if ActiveRecord::Base.dump_schema_after_migration
        ActiveRecord::Tasks::DatabaseTasks.dump_schema(db_config.config, ActiveRecord::Base.schema_format, db_config.spec_name)
      end
```

My question to you... Was there any reason for _not_ having this behavior in the original implementation?
It's causing some troubles for our team as folks that run via the actionable errors UI are forgetting to commit schema/structure.sql changes.

**Comment by eugeneius** [comment]
Thank you for the report! There's already an open pull request that fixes this problem though: https://github.com/rails/rails/pull/40001

**Comment by philipbjorge** [comment]
Thank you @eugeneius -- I can leave this issue open to track it (I searched issues but not PRs) or can close it.
LMK or close it yourself -- Thanks!
