### ISSUE TITLE
Is this the same issue as #34613 ?

### ISSUE THREAD

**Issue by ghost23719** [rails/rails#40111]
Is this the same issue as #34613 ?

_Originally posted by @pixeltrix in https://github.com/rails/rails/issues/40109#issuecomment-680769985_

**Comment by ghost23719** [comment]
https://github.com/rails/rails/issues/40091#issue-684093514Shopify:stop-checking-schema-cache-version

**Comment by composerinteralia** [comment]
Closing this issue, since the issues you linked to are enough to track the bug.

**Comment by ferdi2005** [comment]
How is #40091 related? @ghost23719
