### ISSUE TITLE
exists? documentation for has_and_belongs_to_many is incorrect

### ISSUE THREAD

**Issue by alan-pie** [rails/rails#40128]
### Steps to reproduce
[Association Basics 4.4.1.14 collection exists?(...)](https://guides.rubyonrails.org/association_basics.html#methods-added-by-has-and-belongs-to-many-collection-exists-questionmark) says
> The collection.exists? method checks whether an object meeting the supplied conditions exists in the collection.

but this is not true. It returns whether an object meeting the supplied conditions exists **in the _table_** not in the collection.

There is inconsistency in the API as to whether methods account for objects that have not been saved to the table or not. `first`, `last`, `collection_singular_ids`, and `include?` account for objects that have not been saved, but `find`, `exists?`, and `find_by` do not. Ideally, this inconsistency would be resolved, but at a minimum the documentation should be clarified.

The code below demonstrates it as well as this [repository](https://github.com/alan-pie/rails-exists-5).

```ruby
class Foo < ApplicationRecord
end

class Bar < ApplicationRecord
  has_and_belongs_to_many :foos
end

RSpec.describe Bar, type: :model do
  describe 'a new Bar with a foo in foos' do
      let(:foo) { Foo.new }
      let(:bar) { Bar.new(foos: [foo]) }

      it 'foos.exists?(foo.id) is true' do
        expect(bar.foos.exists?(foo.id)).to be true
      end
  end
end
```

### System configuration
**Rails version**:
5.x and 6.x
**Ruby version**:
2.7

**Comment by tgxworld** [comment]
@alan-pie Can this be closed by https://github.com/rails/rails/pull/40129 ?

**Comment by alan-pie** [comment]
Yes. Thank you for the help!
