### ISSUE TITLE
activerecord 5.2.3 gives Arel "Dangerous query method" warning when .pluck() is passed array of two strings each <table>.<col>

### ISSUE THREAD

**Issue by TJamesCorcoran** [rails/rails#40132]
### Steps to reproduce

I have a large set of ActiveRecord subclasses, with relations.

Code, hugely simplified, looks like this

```
    ctds = CustomerTransactionDetail.joins(:customer_transaction).joins(:customer_transaction).joins(:order).joins(:reservations)
    ctds = ctds.merge( Reservation.start_on_or_after("2020-05-05")).merge( Reservation.start_on_or_before("2020-12-12"))
    ctds = ctds.distinct("customer_transaction_details.id")  
    ctds = ctds.credit   # a scope
    ctds = ctds.charges  # a scope
        # Q: why 'pluck' at all?
        # A: to avoid instantiating ActiveRecord objects(speed!)
        #
        # Q: why pluck with two args? e.g. .pluck([:id, :amount]) 
        # A: because pluck() applies .uniq to results, and just :amount will collapse entries w identical :amounts to 1
        #       e.g.  [ 12.30, 12.30 ] -> we get [ 12.30]
        #    so we ask for [:id, :amount] and get
        #       e.g. [[1, 12.30], [2, 12.30]]
        #    and then we ignore the first entry in each tuple
        #
        # Q: why specify <table>.<col> instead of just <col>?
        # A: because some col names are shared w other tables in the join
        #

    x = ctds.pluck(  ["customer_transaction_details.id", "customer_transaction_details.amount"]).inject(0) { |sum, pair| sum + pair[1] }
```

the last line results in a deprecation warning
`
DEPRECATION WARNING: Dangerous query method (method whose arguments are used as raw SQL) called with non-attribute argument(s): ["customer_transaction_details.id", "customer_transaction_details.amount"]. Non-attribute arguments will be disallowed in Rails 6.0. This method should not be called with user-provided values, such as request parameters or model attributes. Known-safe values can be passed by wrapping them in Arel.sql(). (called from block (2 levels) in util_create_hash at FILE )`

Wrapping each string in Arel.sql() does not help.

The problem seems to in `gems/ruby-2.5.7/gems/activerecord-5.2.3/lib/active_record/attribute_methods.rb`

in method `enforce_raw_sql_whitelist`.  Reading the code

Note that table `customer_transaction_details` exists and has columns `id` and `amount` . The code WORKS.  It just triggers the deprecation warning.  I just now realized that I can work around this by replacing the array with a single string 

"customer_transaction_details.id, customer_transaction_details.amount"

but as the array is a valid format, the deprecation warning should not fire.

### Expected behavior

No deprecation warning.

### Actual behavior

A deprecation warning.

### System configuration
**Rails version**: 5.2.3

**Ruby version**: 2.5.7

**Comment by jonathanhefner** [comment]
`pluck` expects [multiple columns to be specified as multiple args](https://api.rubyonrails.org/classes/ActiveRecord/Calculations.html#method-i-pluck).  In other words, the following should work without a deprecation warning:

```ruby
ctds.pluck("customer_transaction_details.id", "customer_transaction_details.amount")
```

Or, if those columns are stored in an Array:

```ruby
ctds.pluck(*columns_array)
```

> but as the array is a valid format, the deprecation warning should not fire.

Passing an Array works in your scenario by accident of the [implementation](https://github.com/rails/rails/blob/v5.2.3/activerecord/lib/active_record/relation/query_methods.rb#L1053-L1065), but it may not work in all scenarios.  I recommend using the expected arg format.
