### ISSUE TITLE
ActiveStorage video duration missing from VideoAnalyzer metadata

### ISSUE THREAD

**Issue by gregblass** [rails/rails#40130]
### Expected behavior
When I call `ActiveStorage::Analyzer::VideoAnalyzer.new(blob).metadata` on a video, I'm expecting there to be a duration in there.

### Actual behavior
The duration is missing. I'm only seeing width, height, and aspect ratio. FFmpeg is installed on my system (Mac OS) and is accessible from Rails.

Here's a simple demonstration in the console:

```
irb(main):009:0> video
=> #<ActiveStorage::Attached::One:0x00007fb61b788ee8 @name="video", @record=#<Video id: 103, account_id: 2, user_id: 13, name: "Aug 28 2020 @  1:36pm", length: nil, created_at: "2020-08-28 17:36:23", updated_at: "2020-08-28 17:36:23", deleted_at: nil>>
irb(main):010:0> video.blob
=> #<ActiveStorage::Blob id: 183, key: "yta8z1q34qygxjbh9kbyo7uqktc3", filename: "1598312549343.webm", content_type: "video/webm", metadata: {"identified"=>true, "width"=>1280.0, "height"=>720.0, "display_aspect_ratio"=>[16, 9], "analyzed"=>true}, byte_size: 997051, checksum: "Gk/o6VluCUsiNZ5lSwHzcA==", created_at: "2020-08-28 17:36:23">
irb(main):011:0> video.analyzed?
=> true
irb(main):012:0> video.metadata
=> {"identified"=>true, "width"=>1280.0, "height"=>720.0, "display_aspect_ratio"=>[16, 9], "analyzed"=>true}
```

If anyone has any insight here, that would be greatly appreciated. Thank you!

### System configuration
**Rails version**: 6.0.3.2

**Ruby version**: 2.5.7

**Comment by jonathanhefner** [comment]
@gregblass This is due to the way duration information is stored in WebM videos.  I opened #40135 to address the problem.  However, some "raw" WebM files don't include duration information in their container either, so you may want to check if `ffprobe -show_format -v error your_video.webm` shows a `duration` for the video(s) in question.

**Comment by gregblass** [comment]
@jonathanhefner Thank you very much!
