### ISSUE TITLE
Active Storage and S3 with granular IAM policy/ACL

### ISSUE THREAD

**Issue by birthdaycorp** [rails/rails#40139]
Similar to [this](https://github.com/rails/rails/issues/32790), I have switched from Paperclip to Active Storage. While Active Storage is great, it presents a new set of problems. Paperclip let me set a bucket directory (or even a new bucket), whereas Active Storage dumps everything into the root of a single bucket. I fear that this could create security issues. Improperly set IAM policies are an easy to make no-no, and my app had been using two buckets to avoid the problem: one for public content, and one for private admin accessible content.

In making that two bucket setup work with Active Storage, I tried to use the `service` option for `has_one_attached`. However, I get an ArgumentError: `unknown keyword: service`. The [edge guide](https://edgeguides.rubyonrails.org/active_storage_overview.html#setup) implies that this option works in Rails 5.2, but the [guide for 5.2.4](https://guides.rubyonrails.org/v5.2.4/active_storage_overview.html#has-one-attached) doesn't mention the `service` option at _all_.

I can see that the official response to the request for supporting a directory structure was "no," but...exactly how does one go about locking down access to certain S3 files while being less restrictive with everything else? That is, without switching to something else entirely, like Shrine?

**Comment by composerinteralia** [comment]
The service option to `has_one_attached` was added in https://github.com/rails/rails/commit/e7f798c3f549502d696167e9b29f18106cf2cbe0, so it is not available in an official release yet.

**Comment by composerinteralia** [comment]
Since it doesn't seem like there is any bug with the `service` option, I am going to close this issue.

If there are still aspects of Active Storage you would like to discuss that are not necessarily bugs, the best place to do that is on the [rails-core mailing list](https://discuss.rubyonrails.org/c/rubyonrails-core/5).
