### ISSUE TITLE
Some ActiveStorage::Blob records persists without parent ActiveStorage::Attachment.

### ISSUE THREAD

**Issue by alejandrodevs** [rails/rails#40150]
### Steps to reproduce
I'm using sidekiq workers like the following:

```ruby
class ReportWorker
  include Sidekiq::Worker

  def perform
    evaluations = # Get evaluations.

    batch.jobs do
      evaluations.each do |evaluation_id|
        IndividualReportWorker.perform_async(evaluation_id)
     end
  end
end

class IndividualReportWorker
  include Sidekiq::Worker

  def perform(evaluation_id)
    evaluation = Evaluation.find(evaluation_id)
    IndividualReportService.new(evaluation).call
  end
end

class IndividualReportService
  attr_reader :evaluation

  def initialize(evaluation)
    @evaluation = evaluation
  end

  def call
    report.files.attach({
      metadata: metadata,
      filename: report_name,
      io: StringIO.new(pdf.to_pdf),
      content_type: 'application/pdf'
    })
  end

  private

  def metadata
    # some metadata
  end

  def pdf
    # Pdf instance
  end
end

class Report < ApplicationRecord
  has_many_attached :files
end
```

### Expected behavior
All the active storage blobs have an ActiveStorage::Attachment as a parent.

### Actual behavior
There are some ActiveStorage::Blob (with the file saved correctly) without a parent ActiveStorate::Attachment. I do not know if it is related with concurrency or I'm missing something.

### System configuration
**Rails version**: 6.0.3.2
**Ruby version**: 2.7.1
**Sidekiq concurrency**: 5

**Comment by KapilSachdev** [comment]
I haven't checked the example properly, but just wanted to confirm what do you mean by `parent` here?
`attachment` belongs_to `blob` and `active_storage_attachments` has a `foreign_key` `blob_id`, so a `blob` may not have an `attachment` but an attachment must have a `blob`.

Also if you think this is a rails issue, can you please add a reproduction [script](https://github.com/rails/rails/blob/master/guides/bug_report_templates/active_storage_gem.rb), that would be helpful in debugging.

**Comment by alejandrodevs** [comment]
If I run the `attach` method it should create a blob and an attachment right?
In my previous example after I run the IndividualReportWorker with some evaluations, let say 50 evaluations, I run this `report.files_blobs.count`. Sometimes I get 49, sometimes 48, sometimes 50. But I do not know if it is something related with the concurrency.

**Comment by alejandrodevs** [comment]
Look at this example:

```ruby
class Report < ApplicationRecord
  has_many_attached :files
end

class IndividualReportWorker
  include Sidekiq::Worker

  def perform
    IndividualReportService.new.call
  end
end

class IndividualReportService
  def call
    Report.first.files.attach({
      filename: 'report.pdf',
      io: File.open('some_file')
    })
  end
end
```

And then:

```ruby
report = Report.create

# With worker
50.times { IndividualReportWorker.perform_async }
puts report.files_blobs.count # => 46

# Without worker
50.times { IndividualReportService.new.call }
puts report.files_blobs.count # => 50
```

**Comment by cristofer** [comment]
@alejandrodevs do you also have errors like this one?

`PG::ForeignKeyViolation: ERROR:  insert or update on table "active_storage_attachments" violates foreign key constraint "fk_rails_c3b3935057"
DETAIL:  Key (blob_id)=(266780) is not present in table "active_storage_blobs".`

We are getting super tire of them, we have many, and it is quite hard to debug. We check those IDs and we do not see them in neither `active_storage_blobs` nor `active_storage_attachments`.

The point you are mentioning is quite valid, and with the code you shared it is clear there is something wrong when running the jobs in the background, as we also do, so perhaps both scenarios are related.

A shame you have not received an answer yet :(

**Comment by alejandrodevs** [comment]
@KapilSachdev can you reproduce it?

**Comment by KapilSachdev** [comment]
Hello @alejandrodevs, I didn't debugged it further and might be able to for a while as well.
_Actually i was not so sure if this is even a rails bug_

 Pinging @jonathanhefner and @composerinteralia for feedback !

**Comment by composerinteralia** [comment]
I also won't have much time to debug this (I am newly a parent), but a reproduction script or sample application that reproduces the bug would be helpful. Otherwise I don't have much feedback. I don't have any hunches after glancing at the code snippets provided here.
