### ISSUE TITLE
Deprecation warnings from autoprefixer-rails

### ISSUE THREAD

**Issue by johnpitchko** [rails/rails#40155]
### Steps to reproduce
Created a fresh install of Rails.
Was happily coding and writing tests using Minitest.
When running tests, I encounter multiple deprecation warnings:
```
DEPRECATION WARNING: autoprefixer-rails was deprected. Migration guide:
https://github.com/ai/autoprefixer-rails/wiki/Deprecated (called from run at /usr/local/lib/ruby/gems/2.7.0/gems/autoprefixer-rails-9.8.6.1/lib/autoprefixer-rails/sprockets.rb:22)
```

Tried updating sprockets and sprockets-rails, but both are using the most recent version. Not sure if others are experiencing this issue or if something in my config is incorrect.

### System configuration
**Rails version**: 2.7.1p83

**Ruby version**: 6.0.3.2

**Sprockets-rails version**: 3.2.1

**Sprockets version**: 4.0.2

**Comment by composerinteralia** [comment]
Rails doesn't add `autoprefixer-rails` to the Gemfile (I searched this repo and found no references to `autoprefixer-rails`, and I also created a new Rails project and I do not see `autoprefixer-rails` anywhere in the Gemfile.lock), so I don't think this is a Rails bug.

Are you able to share your Gemfile.lock? That could help identify which library is relying on `autoprefixer-rails`.

**Comment by composerinteralia** [comment]
You can also find more details about the deprecation on the [autoprefixer-rails wiki](https://github.com/ai/autoprefixer-rails/wiki/Deprecated)

**Comment by johnpitchko** [comment]
My apologies @composerinteralia !!! Looking more closely, the [issue](https://github.com/twbs/bootstrap-rubygem/issues/196) is with the [bootstrap-ruby](https://github.com/twbs/bootstrap-rubygem) gem.

Anyways thanks for the guidance to dig deeper!
