### ISSUE TITLE
ActiveStorage .attached? method causes incorrect Attachment record_id when duplicating

### ISSUE THREAD

**Issue by robvitaro** [rails/rails#40166]
### Steps to reproduce

See [this gist](https://gist.github.com/robvitaro/1b9ad26b685d7881d17ed9acd48ba7dd) for the executable test case. First test does not use `.attached?`, so it passes. Second test does use `.attached?`, and it fails.

### Expected behavior

I need to duplicate a user record and its attachment, if it has one. Prior to duplicating, I use the `.attached?` method to see if it has an attachment. I duplicate the user, I duplicate the user's attachment blob, then I attach the duplicated blob to the duplicated user. The new ActiveStorage::Attachment record should have a record_id matching the id of the duplicated user id.

### Actual behavior

The new ActiveStorage::Attachment record has a record_id matching the id of the original user id.

### System configuration
**Rails version**:
6.0.3.2
**Ruby version**:
 2.7.1p83

**Comment by jonathanhefner** [comment]
Thank you for the report!  This issue has been fixed in `master` by #39399, and backported to `6-0-stable` by 33c87282493d6691d71b604fe58c10997ac50d66.  Both Rails 6.0.4 and Rails 6.1 will include the fix.
