### ISSUE TITLE
locals used when rendering a view do not behave the same in Rails 4.2.11.3 vs 4.2.11.1

### ISSUE THREAD

**Issue by abepetrillo** [rails/rails#40161]
### Steps to reproduce
Run thus script: https://gist.github.com/abepetrillo/a0126bd67665e6b685302ddbc7ed3a63

### Expected behavior
Instance variable should be injected into the view

### Actual behavior
the instance variable is now evaluated to nil

### System configuration
**Rails version**: 4.2.11.3

**Ruby version**:
2.6.2 (but doesn't seem to be relevant here).

**Comment by composerinteralia** [comment]
We no longer apply bug fixes to Rails 4.2 (you can read more about this in the [maintenance policy](https://edgeguides.rubyonrails.org/maintenance_policy.html)). I'm going to close this issue for now. If this is a bug you can reproduce on Rails 6.0 then I can reopen. Thanks!

**Comment by abepetrillo** [comment]
On further investigation, this seems to have been introduced in Rails 4.2.11.2 although raised a but more nosie:
```
 [2020-09-02T22:37:49.034169 #20212] FATAL -- : 
ActionView::Template::Error (uninitialized constant Module::DELEGATION_RESERVED_METHOD_NAMES):
  actionview (4.2.11.2) lib/action_view/template.rb:317:in `locals_code'
  actionview (4.2.11.2) lib/action_view/template.rb:276:in `compile'
  actionview (4.2.11.2) lib/action_view/template.rb:245:in `block (2 le
```

**Comment by abepetrillo** [comment]
@composerinteralia this release was made May 16 2020 as a security fix. Given how recent this is, and that it is a regression I would have thought we'd be more open to fixing it?

**Comment by abepetrillo** [comment]
Seems to be the regex here does not allow locals prefixed with `@`
https://github.com/rails/rails/blob/11f2bdf75a888682b34df0f9be03b94f54fc6796/actionview/lib/action_view/template.rb#L318

**Comment by abepetrillo** [comment]
My understanding of regex is somewhat limited but this works:
`\A(?![A-Z0-9])(?:[[:alnum:]_@]|[^\0-\177])+\z`
I can submit a PR if there are no issues with it?

**Comment by composerinteralia** [comment]
It looks like a regression was fixed on the [4-2-stable branch](https://github.com/rails/rails/commits/4-2-stable) after the 4.2.11.3 release went out. Does your problem go away if you update your Gemfile to point to that commit?

For example:

```rb
gem "rails", github: "rails/rails", branch: "4-2-stable"
```

**Comment by abepetrillo** [comment]
The script above stil seems to fail using the branch.

**Comment by p8** [comment]
Never knew passing local variables prefixed with @ would assigned them to instance variables. 😄 
As this is the only reported issue I think it's rarely used and not public API.
Being able to set any instance variables (@current_user_id) is probably not what we want.
The correct fix here would be to change the locals to non instance variables.

**Comment by abepetrillo** [comment]
Given this is an unintended change in behavior on a version of Rails that is no longer maintained, I think we should fix it.

**Comment by p8** [comment]
This did get fixed in 5-0-stable:
https://github.com/rails/rails/commit/86bcd2d81b2b723894daacbbbda2430415fd6eb5

**Comment by abepetrillo** [comment]
@p8 Would updating my PR to match the updated regex speed up the process? Not sure what the next steps are from here.

**Comment by p8** [comment]
I don’t see this getting merged at all. There is too much cost in time (reviewing the changes with a broken build), with too much risk for introducing a new bug, for the benefit of just one application. 

I think you have 3 options: upgrade to a maintained version of Rails, refactor the views to not use instance vars, or run a monkey patched version of 4.2.13.

**Comment by abepetrillo** [comment]
That decision seems to have already been made to make changes on a failing build and introduced a bug.
The same bug as been fixed in Rails 5 so I don't really see how we can say the app I am using is unique in the app's use of this pattern.
Although the build is broken it is passing on certain versions of Ruby, so I'm not sure the build is a completely lost cause.
Will be some time before I'm given time to invest in a rails 5 upgrade, so I will do a monkey patch for now. Disappointing.

**Comment by Nowaker** [comment]
For reference, the fix is in here: https://github.com/rails/rails/pull/40165
