### ISSUE TITLE
Cosmetic issue on custom action routes output when generating controller

### ISSUE THREAD

**Issue by alexpapworth** [rails/rails#40174]
### Steps to reproduce
Run `rails destroy controller CreditCards open debit credit close` in your terminal.

### Expected behavior
Should indent custom routes inline with the rest of the generate output.

### Actual behavior
Outputs custom routes with with no indentation.

<img width="815" alt="Screenshot 2020-09-03 at 20 45 37" src="https://user-images.githubusercontent.com/25950768/92160231-98538600-ee26-11ea-991d-2259a3d063f3.png">

### System configuration
**Rails version**: 2.7.1

**Ruby version**: 6.0.3.2

Definitely a minor issue, but thought I'd report regardless. Would love to create a PR for this, if someone can point me in the direction of where this `rails generate` output code lives!

**Comment by jonathanhefner** [comment]
Thank you for the report!  This is the same issue as described by #38387.   In my opinion, it would be best to fix this in Thor itself, so I opened erikhuda/thor#714.

**Comment by alexpapworth** [comment]
Ah, excellent. Glad to see it's been spotted before! Going to close this one as a duplicate :)
