### ISSUE TITLE
dirty methods of ActiveRecord::Store

### ISSUE THREAD

**Issue by RALIST** [rails/rails#40170]
### Steps to reproduce
Let model User stored profile_data as jsonb column in PostgreSQL as
`{ "profile_data": { "first_name": "John", "last_name": "Snow" }`

so we can use ActiveRecord::Store
 `store_acessors :profile_data, :first_name, :last_name`

### Expected behavior
When update stored as json attributes
```
user.last_name = "Stark"
user.save
```
Should be
`user.saved_change_to_last_name? == true`
`user.saved_change_to_last_name == ['Snow', 'Stark']`
`user.last_name_before_last_save == 'Snow'`

### Actual behavior
`user.saved_change_to_last_name? == false`
`user.saved_change_to_last_name == [nil, nil]`
`user.last_name_before_last_save == nil`

it seems problem inside ActiveRecord::Store#store_accessor
it defines such methods:
```
define_method("saved_change_to_#{accessor_key}?") do
   return false unless saved_change_to_attribute?(store_attribute)
   prev_store, new_store = saved_change_to_attribute(store_attribute)
   prev_store&.dig(key) != new_store&.dig(key)
end
```
`prev_store` and `new_store` are Hashes, but it seems should be HashWithIndifferentAccess, because key is a Symbol, but in hash we have string keys.
### System configuration
**Rails version**: 6.0.2

**Ruby version**: 2.6.5

**Comment by esparta** [comment]
Will be helpful if you can add a reproducible script for this issue: https://guides.rubyonrails.org/contributing_to_ruby_on_rails.html#create-an-executable-test-case

**Comment by tgxworld** [comment]
> [NOTE: If you are using structured database data types (eg. PostgreSQL hstore/json, or MySQL 5.7+ json) there is no need for the serialization provided by .store. Simply use .store_accessor instead to generate the accessor methods. Be aware that these columns use a string keyed hash and do not allow access using a symbol.](https://api.rubyonrails.org/classes/ActiveRecord/Store.html)

There is a note in the API docs about this. What you need to do instead is to use string keys for `store_accessor` instead.

```
store_accessor "profile_data", "first_name", "last_name"
```

That being said, it does seem to be weird that on assignment the hash is actually converted to a `HashWithIndifferentAccess`.
