### ISSUE TITLE
sometimes adding code while server is running doesn't do anything

### ISSUE THREAD

**Issue by scratchoo** [rails/rails#40179]
### Expected behavior
updating a model (or controller etc...) should reflect changes on the fly (while the server is running)

### Actual behavior
Don't get me wrong, it works, for example, I have a custom validation method in my model, I'm testing the app, navigating and saving the form, everything is fine, but sometimes (while the server is running) I add throw "hello" to that validation method or to my controller, and I try to submit the form, but it never throws the error until I restart the server.

I'm not sure how to reproduce this is, it happens when I do a lot of navigation and form submissions!

Here is another example, where I had a line that `throw "kkkk"` then I replaced it with another line, but when I sent the form again, it still remembers of that `throw "kkkkk"` I had previously !!! =====> http://i.imgur.com/qDCQNfU.png

Once I restarted the server, and re-submit again using Ctrl+r that `throw "kkkkk"` disappeared.

it's like there is some kind of cache but for code lol

### System configuration
**Rails 6.0.3.2**:

**Ruby 2.7.0p0**:

**UPDATE:**

Not sure if this will reproduce the issue for you but here is what I noticed and it seems to happen every time:

I have a form that submits to some controller, in my case ProjectsController, then in the ProjectsController#create I have something like this

```
def create
   params[:name] = params[:name].gsub('project', '')
   throw params
  # some code ...
end
```
Once the form is submitted I get the params throwing on my screen correctly, I go back to my text editor, I move `throw params` before the line that is before it, I save and I go to the browser then I click Ctrl+r on my keyboard to refresh which shows me a message that says the data will be re-sent... I accept and the form is re-submitted

I keep doing this process of moving or changing the `throw "something"` a few times and suddenly the issue fire up!

**Comment by esparta** [comment]
You can try disabling/removing spring from your app.

**Comment by scratchoo** [comment]
I still have weird errors happening... mostly when I have a form that I submit, and in the create method I **throw** something like `throw params`

I just got an error today saying `uninitialized constant ProjectsController` while the ProjectsController is there, once I restarted the server it started working again!

Too much magic may lead to magical errors!

**Comment by p8** [comment]
Are you using Zeitwerk or the classic autoloader?

**Comment by scratchoo** [comment]
@p8  Zeitwerk I'm using the last Rails version
