### ISSUE TITLE
Cannot install ActionText due to missing binstubs

### ISSUE THREAD

**Issue by stevenbuccini** [rails/rails#40184]
### Steps to reproduce
1. Create a new Rails app off of rails master using `rails new`
2. `bundle install`
3. `bin/rails action_text:install` as described on the Edge Guides.

### Expected behavior
Rails should run the ActionText generator. Note that on `master@e53f5ff`, I was able to run the generator after overcoming the issue described in #37824.

### Actual behavior
```
$ bin/rails action_text:install
       rails  app:binstub:yarn
rails aborted!
Don't know how to build task 'app:binstub:yarn' (See the list of available tasks with `rails --tasks`)

(See full trace by running task with --trace)
```

### System configuration
**Rails version**: master@942c41806443

**Ruby version**: 2.7.1

**Comment by eugeneius** [comment]
Thanks for reporting this! `git bisect` leads to https://github.com/rails/rails/pull/40143. @jonathanhefner it looks like we might need to use your [backup plan](https://github.com/rails/rails/pull/40143#issuecomment-683444296).

**Comment by stevenbuccini** [comment]
@eugeneius Do you mind sharing the steps you took to use `git bisect` to find the commit? I'm having trouble doing it on my own. This will help me report issues more accurately in the future. Thansk!

**Comment by eugeneius** [comment]
Sure: I generated a new application and changed the Gemfile to use my local checkout of Rails:

```ruby
gem 'rails', path: '../../lib/rails'
```

I switched the Rails repository to the commits you mentioned, and verified that running `bin/rails action_text:install` in the test application worked on the first commit and failed on the second.

Then I used `git bisect` in the Rails repository, running `bin/rails action_text:install` in the test application for each commit to check whether it was good or bad.

Let me know if that works for you!

**Comment by jonathanhefner** [comment]
Looks like we found [what made me think `load "rails/tasks.rb"` was necessary when implementing](https://github.com/rails/rails/issues/40136#issuecomment-683445489) #39137.  :upside_down_face:

**Comment by abhaynikam** [comment]
To tackle such issues, I went ahead and wrote some specs for the ActionText generator here #39317. If we could consider or alteast close it(if not required) I'll be happy to see some closure 😊

**Comment by jonathanhefner** [comment]
@abhaynikam In this case, I don't think #39317 would have helped because it stubs the call to `app:binstub:yarn`.  But I think it would be nice to have more test coverage anyway, so I left a few comments there. :+1:
