### ISSUE TITLE
Signed ID doesn't work with STI

### ISSUE THREAD

**Issue by uxxman** [rails/rails#40187]
### Sample test

```ruby
# frozen_string_literal: true

require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  gem "rails", github: "rails/rails"
  gem "sqlite3"
end

require "active_record"
require "minitest/autorun"
require "logger"

# This connection will do for database-independent bug reports.
ActiveRecord::Base.establish_connection(adapter: "sqlite3", database: ":memory:")
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :users, force: true do |t|
    t.string :type
  end
end

SIGNED_ID_VERIFIER_TEST_SECRET = "This is normally set by the railtie initializer when used with Rails!"
ActiveRecord::Base.signed_id_verifier_secret = SIGNED_ID_VERIFIER_TEST_SECRET

class User < ActiveRecord::Base
end

class Student < User
end

class Teacher < User
end

class BugTest < Minitest::Test
  def test_signed_id_sti
    User.create(type: 'Student')

    signed_id = User.first.signed_id

    assert_equal User.first, User.find_signed(signed_id)
  end
end
```

### Expected behavior
Should find first user (Student)

### Actual behavior
Finds nil

### Notes
Issue is related to using class.name for MessageVerifier purpose https://github.com/rails/rails/blob/722ca6ba353cf44e3b66d77a6e174a2715c8cd5a/activerecord/lib/active_record/signed_id.rb#L93

### Suggested Solution
What if we use base_class.name instead. Will handle all cases. If this is ok, I can create a PR for it.
https://api.rubyonrails.org/classes/ActiveRecord/Inheritance/ClassMethods.html#method-i-base_class
 
### System configuration
**Rails version**: master (6.1.0.alpha)

**Ruby version**: 2.71

**Comment by composerinteralia** [comment]
Nice work on the reproduction script. I can confirm the problem, and that using `base_class.name` seems to fix it without breaking any of the other signed_id tests. Since you already have a test case and the code that fixes it, I would recommend going ahead and opening the PR now. That could save some back and forth if the team does want to accept this change.

**Comment by uxxman** [comment]
Thanks @composerinteralia for looking into this, As you suggested, I have opened up a PR for this
