### ISSUE TITLE
Arel union with "limit" or "order by" generates invalid SQL

### ISSUE THREAD

**Issue by dleavitt** [rails/rails#40181]
### Steps to reproduce
Create a `UNION` or `UNION ALL` of any query containing a `ORDER BY` or `LIMIT` clause with any other query.

```ruby
t = Arel::Table.new(:users)
# valid SQL
working = t.project(t[:id]).union(t.project(t[:id]))

# with limit clause - invalid SQL
with_limit = t.project(t[:id]).take(1).union(t.project(t[:id]))

# with order clause - invalid SQL
with_order = t.project(t[:id]).order(t[:id]).union(t.project(t[:id]))
```

### Expected behavior
These queries should generate valid SQL.

```ruby
with_limit.to_sql
# => ( ( SELECT "users"."id" FROM "users" LIMIT 1 ) UNION SELECT "users"."id" FROM "users" )
```

### Actual behavior

Missing parens around first query are an SQL syntax error (at least in PG and MSSQL.)

```ruby
with_limit.to_sql
# => ( SELECT "users"."id" FROM "users" LIMIT 1 UNION SELECT "users"."id" FROM "users" )
# (invalid SQL)
```
```ruby
ActiveRecord::Base.connection.exec_query(with_limit.to_sql)
# ActiveRecord::StatementInvalid: PG::SyntaxError: ERROR:  syntax error at or near "UNION"
# LINE 1: ( SELECT "users"."id" FROM "users" LIMIT 1 UNION SELECT "use...
#
# from /.../2.6.5/lib/ruby/gems/2.6.0/gems/activerecord-6.0.3.2/lib/active_record/connection_adapters/postgresql_adapter.rb:675:in `exec_params'
# Caused by PG::SyntaxError: ERROR:  syntax error at or near "UNION"
# LINE 1: ( SELECT "users"."id" FROM "users" LIMIT 1 UNION SELECT "use...
```

Same error occurs with the `with_order` query.

### Prior Art
- It's probably what [this FIXME note](https://github.com/rails/rails/blob/3d428777b05701ca7211a1be723cb1ee0e094bd9/activerecord/test/cases/arel/select_manager_test.rb#L286) refers to.
- Originally brought up in #1015 way back in 2011, as well as mentioned [in a mailing list thread.](https://discuss.rubyonrails.org/t/arel-union-does-not-support-order-or-limit/58373)
- Possibly related to #34437.

### System configuration
**Rails version**:
6.0.3.2

**Ruby version**:
2.6.5

**Comment by yoelblum** [comment]
`begin
  require "bundler/inline"
rescue LoadError => e
  $stderr.puts "Bundler version 1.10 or later is required. Please update your Bundler"
  raise e
end

gemfile(true) do
  source "https://rubygems.org"
  gem "activerecord"
  gem "mysql2"
end

require "active_record"
require "minitest/autorun"
require "logger"

# This connection will do for database-independent bug reports.
ActiveRecord::Base.establish_connection(adapter: "mysql2", database: "test")
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :users do |t|
    t.integer :user_type
  end
end

class User < ActiveRecord::Base
  
end

t = Arel::Table.new(:users)
# valid SQL
working = t.project(t[:id]).union(t.project(t[:id])).to_sql

# with limit clause - invalid SQL
with_limit = t.project(t[:id]).take(1).union(t.project(t[:id])).to_sql
with_order = t.project(t[:id]).order(t[:id]).union(t.project(t[:id])).to_sql
puts "working: #{working}"
puts "with_limit: #{with_limit}"
puts "with_order: #{with_order}"
`

**Comment by yoelblum** [comment]
```
begin
  require "bundler/inline"
rescue LoadError => e
  $stderr.puts "Bundler version 1.10 or later is required. Please update your Bundler"
  raise e
end

gemfile(true) do
  source "https://rubygems.org"
  gem "activerecord"
  gem "mysql2"
end

require "active_record"
require "minitest/autorun"
require "logger"

# This connection will do for database-independent bug reports.
ActiveRecord::Base.establish_connection(adapter: "mysql2", database: "test")
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :users do |t|
    t.integer :user_type
  end
end

class User < ActiveRecord::Base
  
end

t = Arel::Table.new(:users)
# valid SQL
working = t.project(t[:id]).union(t.project(t[:id])).to_sql

# with limit clause - invalid SQL
with_limit = t.project(t[:id]).take(1).union(t.project(t[:id])).to_sql
with_order = t.project(t[:id]).order(t[:id]).union(t.project(t[:id])).to_sql
puts "working: #{working}"
puts "with_limit: #{with_limit}"
puts "with_order: #{with_order}"
```

**Comment by rafaelfranca** [comment]
Can you reproduce this issue without using Arel directly? Arel is private API of the framework and direct usage in applications is not supported by the Rails core. This means that we will not work in a fix for the issue ourselves. If you want to fix we are happy to accept.
