### ISSUE TITLE
Activestorage Direct Upload Mime type check failing on codecs parameter

### ISSUE THREAD

**Issue by kayamy** [rails/rails#40180]
### Steps to reproduce

I'm trying to upload some recordings made with the `MediaRecorder` api inside of [Uppy](https://uppy.io/).
The content type for these resulting files look like this `video/webm; codecs="vp8, opus"`

The first request `POST /rails/active_storage/direct_uploads` seems to work, when I look in the database I can see an entry with the file and its content type like `video/webm; codecs="vp8, opus"`.

The second call `PUT "/rails/active_storage/disk/` fails because of the following check:  https://github.com/rails/rails/blob/master/activestorage/app/controllers/active_storage/disk_controller.rb#L52

The content type on the request is missing the codec parameters. Looking at the actual request that is sent by my browser I was able to verify that the content type is correctly being set on the request:

![Screenshot 2020-09-04 at 17 42 18](https://user-images.githubusercontent.com/53950754/92257791-17ec5e00-eed6-11ea-976e-6636e62cfbfc.png)

It basically boils down to `Mime::Type.lookup("video/webm") == 'video/webm; codecs="vp8, opus"'` which returns `false` while I was expecting it to return `true`.

Should this be solved client side in the case of direct uploads? (eg. stripping the codec params) Or should this mapping be handled by active storage? 

I'm new to Rails and the ecosystem so apologies if any of this is vague. I was sure to check out all of the similar issues beforehand but wasn't able to find the answer unfortunately. Thanks!

### System configuration
**Rails version**:
6.1.0.alpha
**Ruby version**:
 2.7.1

**Comment by georgeclaghorn** [comment]
I think we can just change that line:

https://github.com/rails/rails/blob/3d428777b05701ca7211a1be723cb1ee0e094bd9/activestorage/app/controllers/active_storage/disk_controller.rb#L52

to:

```ruby
token[:content_type] == request.content_type && token[:content_length] == request.content_length
```

We’re recording the full Content-Type in the token, so we ought to check against the request’s full Content-Type header.

The question is whether we should be recording the full Content-Type with parameters and reflecting it wholesale on download. I think the answer’s yes, tentatively, but I’m wary that parts of ASt assume `ActiveStorage::Blob#content_type` is just a media type.

**Comment by fullpointer** [comment]
Thanks for the quick help george :)

While looking for answers earlier I found this PR https://github.com/rails/rails/pull/34116/files
It seems that it used to be that way but got changed to support another case, so changing it back would likely break that again.

I'm happy to open a PR with some tests to ensure those cases keep working if you think it's the right way to go!

**Comment by knajjars** [comment]
any updates regarding this issue?
