### ISSUE TITLE
config.action_view.form_with_generates_remote_form is `nil` by default?

### ISSUE THREAD

**Issue by bsodmike** [rails/rails#40195]
### Steps to reproduce
As per the latest guides this should be `true` by default.  Instead, launch a new Rails 6 app and jump into the console.

```
[7] pry(main)> Rails.application.config.action_view
=> {:debug_missing_translation=>true}
```

That's odd right?

```
[6] pry(main)> Rails.application.config.action_view.form_with_generates_remote_form
=> nil
```
### Expected

It should be `true` by default.

What's going on here?

### System configuration
**Rails version**:
[9] pry(main)> Rails.version
=> "6.0.3.2"

**Ruby version**:
-> % ruby --version
ruby 2.7.1p83 (2020-03-31 revision a0c7c23c9c) [x86_64-darwin18]

**Comment by composerinteralia** [comment]
The [value gets deleted from the application config after initialization](https://github.com/rails/rails/blob/580eefe1bc5d7241a4b2f3ee863523c5b8fd2f80/actionview/lib/action_view/railtie.rb#L24-L27). Do you get the value you expected if you run `ActionView::Helpers::FormHelper.form_with_generates_remote_forms`?

**Comment by bsodmike** [comment]
> The [value gets deleted from the application config after initialization](https://github.com/rails/rails/blob/580eefe1bc5d7241a4b2f3ee863523c5b8fd2f80/actionview/lib/action_view/railtie.rb#L24-L27). Do you get the value you expected if you run `ActionView::Helpers::FormHelper.form_with_generates_remote_forms`?

That works!

```ruby
[1] pry(main)> ActionView::Helpers::FormHelper.form_with_generates_remote_forms
=> true
```

**Comment by bsodmike** [comment]
> The [value gets deleted from the application config after initialization](https://github.com/rails/rails/blob/580eefe1bc5d7241a4b2f3ee863523c5b8fd2f80/actionview/lib/action_view/railtie.rb#L24-L27). Do you get the value you expected if you run `ActionView::Helpers::FormHelper.form_with_generates_remote_forms`?

We have an older Rails 5 codebase, that during upgrade we have to explicitly enable this to `true`.  Strange 🤔

**Comment by bsodmike** [comment]
In the upgraded app:

```ruby
Loading development environment (Rails 6.0.3.2)
[1] pry(main)> ActionView::Helpers::FormHelper.form_with_generates_remote_forms
=> nil
```

**Comment by composerinteralia** [comment]
Have you set 'config.load_defaults`? If not, you can read more about it in the [upgrading guide](https://guides.rubyonrails.org/upgrading_ruby_on_rails.html#configure-framework-defaults).

**Comment by bsodmike** [comment]
> Have you set `config.load_defaults`? If not, you can read more about it in the [upgrading guide](https://guides.rubyonrails.org/upgrading_ruby_on_rails.html#configure-framework-defaults).

That was it, thanks so much!
