### ISSUE TITLE
Cookie store configured with domain all, fail for 3-letter domains with a 2-letter TLD

### ISSUE THREAD

**Issue by hovsater** [rails/rails#40200]
### Expected behavior

When the cookie store has been configured using `domain: :all`, the cookie domain for `whatever.abc.se` should resolve to `.abc.se`.

### Actual behavior

it resolves to `.whatever.abc.se`. This is due to the following regexp

https://github.com/rails/rails/blob/7af59e16a255da5aee2863af0eefaa9f0cfd857d/actionpack/lib/action_dispatch/middleware/cookies.rb#L298

and to the fact that the regexp also handle TLDs such as `com.au` or `co.uk`.

https://github.com/rails/rails/blob/7af59e16a255da5aee2863af0eefaa9f0cfd857d/actionpack/lib/action_dispatch/middleware/cookies.rb#L287-L288

A quick fix would be to set the `tld_length` option to `2` which causes the resolution to proceed as expected, but at the same time I'd expect the default case to either "just work" or otherwise make the configuration explicit.

As it stands right now, Rails is making arbitrary assumptions, and if those assumptions happen to be invalid, it resolves the domain incorrectly without the user even knowing.

### System configuration

**Rails version**: 4.2 (should be present in Rails 6 as well)

**Ruby version**: 2.7

**Comment by p8** [comment]
Maybe we should be using https://github.com/weppos/publicsuffix-ruby instead

**Comment by KevinSjoberg** [comment]
I've added a draft pull request with a failing test case. See #40217.

**Comment by p8** [comment]
Looking at https://github.com/weppos/publicsuffix-ruby/blob/master/data/list.txt I see for example that both `co.uk` and `caxias.br` are public suffixes. 
```
"example.co.uk" =~ DOMAIN_REGEXP && ".#{$&}" => ".example.co.uk"
"example.caxias.br" =~ DOMAIN_REGEXP && ".#{$&}" => ".caxias.br"
```
Having the cookie domain resolve to ".caxais.br" will mean all *.caxias.br domains can access the cookie.
I think we should either add a dependency like 'public-suffix' (an extra dependency requiring more memory) or make the `tld_length` required as @KevinSjoberg suggested.

**Comment by p8** [comment]
Maybe good to pick this up after https://github.com/rails/rails/issues/39566 gets merged.

**Comment by KevinSjoberg** [comment]
Still an issue I'd like to address.

**Comment by kevinsjoberg** [comment]
Still an issue I'd like to address.

**Comment by kevinsjoberg** [comment]
Still an issue I'd like to address.

**Comment by hovsater** [comment]
Still an issue I'd like to address.
