### ISSUE TITLE
6.0.3.3: Unknown GPG key B6078D32557ABC13 signed the tag, unknown list of verified maintainers

### ISSUE THREAD

**Issue by dvzrv** [rails/rails#40211]
### Steps to reproduce
Hi! I'm packaging ruby-activesupport for Arch Linux.
For verifying the sources of upstreams (such as yourself) we usually use checksums (for source tarballs) and/or GPG signatures (of source tarballs, git tags or commits).

In regards to this we follow the [TOFU](https://en.wikipedia.org/wiki/Trust_on_first_use) principle. E.g. the first known GPG key signing a tag/ release tarball is trusted.

Further people allowed to tag releases should be mentioned in a user-facing document (e.g. AUTHORS or README) alongside their respective GPG keys. Changes to such a document should (ideally) be done by the first signing authority/ the maintainer to establish a [chain of trust](https://en.wikipedia.org/wiki/Chain_of_trust) (and later by anyone in that document).

@rafaelfranca I would be very happy if this could be implemented so that for downstreams (e.g. distributions) it becomes more clear who is verified and allowed to do releases to fend off [supply chain attacks](https://en.wikipedia.org/wiki/Supply_chain_attack).

Additionally I think it would make sense to extend the [release document](https://github.com/rails/rails/blob/master/RELEASING_RAILS.md) by information on the necessity of the release manager's public key being valid and available on the keyservers.

Currently I am unable to package 6.0.3.3 as I am unable to verify the tag as the GPG key in use (`B6078D32557ABC13`) is not available on the keyservers.

### Expected behavior

* be able to retrieve list of release maintainers for rails
* be able to retrieve GPG public key of each release maintainer from keyservers
* be able to `git verify-tag v6.0.3.3`

### Actual behavior

* unable to retrieve list of release maintainers for rails
* unable to retrieve the public key of `B6078D32557ABC13` (@georgeclaghorn), that signed the tag `v6.0.3.3`

### System configuration
**Rails version**: 6.0.3.3

**Ruby version**: 2.7.1

**Comment by georgeclaghorn** [comment]
I’ve submitted my new GPG key to keys.gnupg.net, pgp.mit.edu, and keys.openpgp.org. Let me know if need the key in a different keyserver pool.
