### ISSUE TITLE
Change the default branch name for new Rails projects from `master` to `main`

### ISSUE THREAD

**Issue by jayqui** [rails/rails#40214]
### Steps to reproduce

```bash
$ rails new temp_experiment
# app is created
$ cd temp_experiment
$ cat .git/HEAD
ref: refs/heads/master
```

### Expected behavior
.git/HEAD should contain `ref: refs/heads/main`

###### References
* https://github.com/github/roadmap/issues/63
* https://github.com/github/renaming
* Rationale: https://dev.to/afrodevgirl/replacing-master-with-main-in-github-2fjf

### Actual behavior
.git/HEAD contains `ref: refs/heads/master`

### System configuration
**Rails version**: 6.0.3.3

**Ruby version**: 2.7.1p83

**Comment by eileencodes** [comment]
Hey @jayqui thanks for opening this. We discussed this as a team awhile back and decided to wait until GitHub was finished building out the feature to make the transition smooth. We have a lot of open PRs and changing the branch name would mean none of those PRs are mergable without intervention from the original author which can cause quite a bit of friction. I will leave this issue open until we've made the switch. Thanks again!

**Comment by eileencodes** [comment]
@jayqui I misunderstood you were also talking about what happens when you build a new Rails project. I think we can change that without waiting for the GitHub feature. Do you want to open a PR?

**Comment by matthewd** [comment]
Ah, I'd missed that distinction too.

I slightly worry about ignoring someone's explicitly configured `init.defaultBranch=trunk`, or whatever... but that's something we could explore on a PR.

(If the report is that we _ignore_ a relevant `~/.gitconfig`, then that's 110% a bug, but I don't think that's the case here?)

**Comment by prateekkish** [comment]
@eileencodes Here's a PR https://github.com/rails/rails/pull/40254

I've taken into account the user's `.gitconfig` as per @matthewd's comment.

**Comment by kitty-alt** [comment]
I had some concerns about the approach here in this issue that I wrote about on the PR, I'll post them here as well.

> If init.defaultBranch is already set rails new already creates a project with the custom default branch name. I think changing the default behaviors for a new project created with rails new that differs from git init would be undesirable because it would be unexpected. It's likely that most users wanting a custom default branch name would have already set init.defaultBranch, whereas those leaving it unset likely expect master to be the default.

Basically I think it's already viable to easily switch to `main` as a default for new projects, it already *just works*, but doing a change like this would mess with workflows that need to use `master` (for example deployment scripts).

**Comment by jayqui** [comment]
[Discussion is ongoing](https://github.com/rails/rails/pull/40254#issuecomment-760338123) in the PR. I'm new around here and unsure whether this issue should be re-opened. In any event, I cannot find a way to re-open it, so perhaps there's my answer.
