### ISSUE TITLE
Rails Initialization Process should mention config/initializers explicitly

### ISSUE THREAD

**Issue by alan-pie** [rails/rails#40218]
config/initializers is a pretty important part of initializing most Rails applications, but the Initialization guide doesn't clearly state when those will be run. "Initializer" seems like an overloaded term in Rails. Clearly distinguishing between "Config Initializers" and other initializers would be helpful, along with links to the appropriate section in the Configuring Rails guide.

**Comment by p8** [comment]
This section recently had some changes. Did you look at the latest version (edge)?
https://edgeguides.rubyonrails.org/configuring.html#using-initializer-files

**Comment by alan-pie** [comment]
That is in the Configuring guide as opposed to the Initialization guide. Maybe we just need to link there from the Initialization guide somewhere? Maybe this section which is where the terminology gets confusing:
https://edgeguides.rubyonrails.org/initialization.html#railties-lib-rails-application-rb
