### ISSUE TITLE
Add "Manila" time zone

### ISSUE THREAD

**Issue by lawrencepit** [rails/rails#40234]
The Philippines has a population of 100+ million, time zone `Manila` should be supported. It is defined as `Asia/Manila` in the tz-info gem.

https://github.com/rails/rails/blob/10d95e68485db70b53e6414da9ffa7340cbe7e74/activesupport/lib/active_support/values/time_zone.rb#L31

**Comment by tilo** [comment]
https://github.com/rails/rails/pull/40236

**Comment by eileencodes** [comment]
Hey @lawrencepit thanks for the issue! The MAPPING list is frozen and we don't accept PRs to update it. We've had this policy for some time now see #22440 for past PRs.

**Comment by lawrencepit** [comment]
@eileencodes Please reopen this issue. The policy should be reconsidered. The world is moving, a frozen list is left behind.

In the PR you reference the concern of that PR has not been addressed at all.

@pixeltrix  wrote in that PR:
> thanks for the offer, but ActiveSupport::TimeZone::MAPPING is not meant to be a definitive list of all time zone offsets, just a convenient short list of the major cities, etc.

Manila has a population of 14 million. It is far more major than _any_ major city in Europe and the U.S.

If rails is going to be this opinionated about that list, at least offer a clean API so that the list can be customized.

**Comment by simi** [comment]
@lawrencepit I think you can still use "Asia/Manila" directly. That list is just list of shortcuts.
