### ISSUE TITLE
Deploying to a sub-directory does not use config.relative_url_root

### ISSUE THREAD

**Issue by MarkMT** [rails/rails#40237]
This is mainly a documentation issue but may also have code implications...

According to the [Guides ](https://guides.rubyonrails.org/configuring.html#deploy-to-a-subdirectory-relative-url-root), in order to deploy an application to a sub-directory, we set:
```
config.relative_url_root = "/app1"
```
and doing so causes Rails to prepend '/app1' when generating links.

However this does not appear to be the case. I have deployed an app to a subdirectory without setting `relative_url_root` (I'm using nginx/passenger, so there is also [some configuration](https://www.phusionpassenger.com/library/deploy/nginx/deploy/ruby/#deploying-an-app-to-a-sub-uri-or-subdirectory) needed there) and links are generated correctly.

I'm not deeply familiar with Rails internals, but from what I've been able to glean from the code, the url helper methods are defined in `ActionDispatch::Routing::Routeset` via the method `url_for`, which passes a set of options to the `url_strategy` lambda. Within the options hash, `options[:script_name]` is the value that is actually used to define the path prefix and this can be derived in a number of ways. If a SCRIPT_NAME header variable is present in the request it will be used (See method `url_options` in `ActionController::UrlFor`). In my production environment, this variable is present (presumably set by nginx?) and so this is what is used to set the path prefix. However if the header value is not present, it looks for either `options[:relative_url_root]` or the value returned by the method `relative_url_root`. But as far as I can tell, neither of these are derived from the application's `config.relative_url_root`. 

The RouteSet's `relative_url_root` method returns the value of `@config.relative_url_root`, where `@config` is set when the RouteSet is instantiated. A config object is passed to the constructor the first time the application's `routes` method (Engine#routes) is called and if a `relative_url_root` is present in that object it is copied into the default RouteSet-specific config stored in `@config`. 

However in practice this happens in the engine's `:add_routing_paths` initializer, which is run _before_ the `:load_environment_config` initializer that loads the environment configuration file where one would typically define `config.relative_url_root`. So it seems that in the normal course of events, `@config.relative_url_root` in the RouteSet object will always be nil regardless of any explicit configuration setting.

The fact that the path prefix is derived from the request header is not a problem in terms of generating correct urls in the view or the controller; in fact it simplifies things if `relative_url_root` doesn't need to be set explicitly. However there can be cases where urls are needed outside of the view or controller - e.g. google "rails url helpers in model" or "rails url helpers in console". The standard answer to these questions typically found e.g. on stackoverflow is either to include the module given by `Rails.application.routes.url_helpers` into the class where they are needed or to call the required helper on that module directly.

In my experience, up until Rails 4.2.x, urls generated in this way would correctly prepend the deployment directory if `relative_url_root` was set in the environment configuration. After 4.2.x it appears they do not, evidently because RouteSet#relative_url_root is nil as outlined above. It appears that the key change may have occurred in commit 798a14a6388ac525109e550d72bba0b1118e5e2e, which introduced the config argument into the RouteSet constuctor. Prior to this, `relative_url_root` was mutable from outside the class via
```
mattr_accessor :relative_url_root
```
and its value was set using the value in `config.relative_url_root` by the `"action_dispatch.configure"` initializer defined in the ActionDispatch railtie. Because that initializer is run after `:load_environment_config`, it correctly set the value used by `RouteSet#relative_url_root` which made it able to be used to correctly generate urls in contexts where a request script_name header does not exist.

In Rails >=5.0, on the other hand, I'm not able to generate correct urls in these situations by setting `config.relative_url_root`, but I can instead set `Rails.application.routes.default_url_options[:relative_url_root]` and everything works fine, since this ends up being `options[:relative_url_root]` in the hash passed to `url_strategy` 

It's possible that there are flaws in my interpretation of what's going on. But if my analysis is correct, there probably needs to be some change to the [guides](https://guides.rubyonrails.org/configuring.html#deploy-to-a-subdirectory-relative-url-root). As far as I can tell, setting `config.relative_url_root` does not cause correct urls to be generated in the view. And if urls are needed outside of the view-controller, setting `Rails.application.routes.default_url_options[:relative_url_root]` will allow helper methods called on `Rails.application.routes.url_helpers` to generate the correct values.

However I'm also curious what the circumstances are in which a RouteSet would be initialized with a config object that does have  a `relative_url_root` set so that RouteSet#relative_url_root evaluates to something other than nil. I presume there is a good reason for this method to exist, but what it is is not obvious to me.

**Comment by ijdickinson** [comment]
I've just found myself facing the same situation, and the workaround by @MarkMT to set the `default_url_options` was really helpful (thanks @MarkMT!)
