### ISSUE TITLE
Add API to customize Rails TimeZone mapping list

### ISSUE THREAD

**Issue by lawrencepit** [rails/rails#40243]
RFC: Offer an API that allows the list `ActiveSupport::TimeZone::MAPPING` to be customized.

---- 

For background see #40234 and #22440. Apparently there is a policy that says that the list `ActiveSupport::TimeZone::MAPPING` is frozen.

@pixeltrix wrote in #22440:

> ... ActiveSupport::TimeZone::MAPPING is not meant to be a definitive list of all time zone offsets, just a convenient short list of the major cities, etc.

Manila has a population of 14 million. It is far more major than any major city in Europe and the U.S.

Also the concern of #22440 has not been addressed. People want to add time zones that are not covered by any time zone in that list.

I suggest to offer an API that allows the list to be customized. 

----

PS. As a workaround I found that for example this can be defined in an initializer file:

`ActiveSupport::TimeZone::MAPPING['Manila'] = 'Asia/Manila'`

I don't believe this is guaranteed to work for everyone though, given how `ActiveSupport::TimeZone` uses caches and there's no guarantee those caches are filled only after the initializer has run.

**Comment by simi** [comment]
@lawrencepit GitHub issues is not the right place to suggest features. https://guides.rubyonrails.org/contributing_to_ruby_on_rails.html#what-about-feature-requests-questionmark

Anyway I think you can still use `Asia/Manila` directly, right? Missing `Manila` in `ActiveSupport::TimeZone::MAPPING` does not prevent you from using Manila time zone at all IMHO.

**Comment by composerinteralia** [comment]
I agree that the the [rails-core mailing list](https://discuss.rubyonrails.org/c/rubyonrails-core/5) would be the appropriate place to discuss new features. You could also try opening a PR that adds the API you are looking for. I'm going to close this issue for now. Thank you!
