### ISSUE TITLE
Postgres advisory lock tests fail often on rails/rails CI

### ISSUE THREAD

**Issue by eileencodes** [rails/rails#40268]
I noticed that the advisory lock tests on postgres for rails/rails fail often. Here's the most recent one I saw https://buildkite.com/rails/rails/builds/71696#ee1d447f-9226-4685-a823-f737b31cfece/954-965

Here's another one https://buildkite.com/rails/rails/builds/71589#66cb0d9b-e63a-4d95-93f0-d6621323d3f1/1025-1036

```
Failure:
  | MigrationTest#test_with_advisory_lock_closes_connection [/rails/activerecord/test/cases/migration_test.rb:948]:
  | #<Proc:0x000055ab732c2878 /rails/activerecord/test/cases/migration_test.rb:948 (lambda)> changed.
  | Expected: 2
  | Actual: 3
```

cc/ @tgxworld I wonder if this is related to https://github.com/rails/rails/pull/39758 or https://github.com/rails/rails/pull/40101

**Comment by tgxworld** [comment]
You can assign this to me, I’ll have a look 👍

**Comment by eugeneius** [comment]
Here's the new failure after https://github.com/rails/rails/pull/40285:

```
Failure:
MigrationTest#test_with_advisory_lock_closes_connection [/rails/activerecord/test/cases/migration_test.rb:947]:
#<Proc:0x000055b2f3c34c80@/rails/activerecord/test/cases/migration_test.rb:947 (lambda)> changed.
--- expected
+++ actual
@@ -1 +1 @@
-["ROLLBACK", "ROLLBACK", "ROLLBACK", "ROLLBACK", "SELECT pg_advisory_unlock(2582488309082152590)"]
+["ROLLBACK", "ROLLBACK", "ROLLBACK", "ROLLBACK", "SELECT pg_advisory_unlock(2582488309082152590)", "SELECT 1"]
```
