### ISSUE TITLE
before_validations wont happen before enum

### ISSUE THREAD

**Issue by amolpujari** [rails/rails#40269]
### Steps to reproduce
````
class Foo < ApplicationRecord
  enum: kind: [:abc, :xyz]

  before_validation :something

  def something
    self.kind = :abc if self.kind == :pqr
  end
end

Foo.new kind: :pqr
````

There is no way to handle this at model level, I dont find before_new or before_initialization etc hooks, how about having a very very first hook of object initiliazation

### Expected behavior
Foo.new kind: :pqr  
=> {Foo kind: :abc}

### Actual behavior
ArgumentError: 'pqr' is not a valid kind

### System configuration
**Rails version**: any

**Ruby version**: any

**Comment by rafaelfranca** [comment]
Thank you for the issue. Enums are validated when the value is set to the attribute, so it is true that when the validations are run, the enum already raised the error. We have no plan to change this behavior.

**Comment by amolpujari** [comment]
Thanks for quick reply.

For now i have to handle it outside model all over as it cannot be handled inside model and there is what my concern was.

**Comment by ryder12345** [comment]
Anyone know where I left my tax papers

________________________________

**Comment by jsierles** [comment]
Did any behavior around enum validations in Rails 6.1? I ran into an issue during the upgrade. Given this scope:

`scope :any_major, -> { where(certification_kind: %w(major partial_major)) }`

and

`Certification.any_major.new`

Rails 6.0 allows this, but 6.1 will issue

`ArgumentError Exception: '["major", "partial_major"]' is not a valid certification_kind`
