### ISSUE TITLE
ActiveRecord won't take array of tuples as param for `IN` clause

### ISSUE THREAD

**Issue by qmx** [rails/rails#40273]
### Steps to reproduce

```ruby
# frozen_string_literal: true

require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  gem "rails", github: "rails/rails"
  gem "sqlite3"
end

require "active_record"
require "minitest/autorun"
require "logger"

# This connection will do for database-independent bug reports.
ActiveRecord::Base.establish_connection(adapter: "sqlite3", database: ":memory:")
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :posts, force: true do |t|
  end

  create_table :authors, force: true do |t|
  end

  create_table :comments, force: true do |t|
    t.integer :post_id
  end

  create_table :reviews, force: true do |t|
    t.integer :post_id
    t.integer :author_id
  end
end

class Post < ActiveRecord::Base
  has_many :comments
end

class Author < ActiveRecord::Base
  has_many :reviews
end

class Comment < ActiveRecord::Base
  belongs_to :post
end

class Review <ActiveRecord::Base
  belongs_to :author
end

class BugTest < Minitest::Test
  def test_in_query
    post = Post.create!
    post.comments << Comment.create!

    author = Author.create!

    assert_equal 'SELECT "reviews".* FROM "reviews" WHERE ("reviews".post_id, "reviews".author_id) IN ((1,1),(2,3))' , Review.where("(post_id, author_id)" => [[1,1],[2,3]]).to_sql # not trying to be prescriptive with the SQL format, that's vaguely what I expect to be the output
  end
end

```

### Expected behavior

Not error out, properly accept an array of tuples for `IN` clause

### Actual behavior

This errors out with `TypeError: can't quote Array`

### System configuration
**Rails version**: master@364c215

**Ruby version**: ruby 2.7.1p83 (2020-03-31) [x86_64-darwin17]

**Comment by anujmiddha** [comment]
I tried to reproduce your error, but could not. I instead get a test failure because the expected and actual strings are different, which is the correct output imo.

Here's my output,
```
F

Failure:
BugTest#test_in_query [40273.rb:62]:
--- expected
+++ actual
@@ -1 +1 @@
-"SELECT \"reviews\".* FROM \"reviews\" WHERE (\"reviews\".post_id, \"reviews\".author_id) IN ((1,1),(2,3))"
+"SELECT \"reviews\".* FROM \"reviews\" WHERE \"reviews\".\"(post_id, author_id)\" IN (1, 1)"
```
and config
```
ruby 2.7.1p83 (2020-03-31 revision a0c7c23c9c) [x86_64-darwin19]
```
Perhaps there's another issue, or there's something I missed?

**Comment by qmx** [comment]
@anujmiddha copy pasta fail (updated the reproducer)

Relevant line:
```ruby
Review.where("(post_id, author_id)" => [[1,1],[2,3]]).to_sql
```

**Comment by anujmiddha** [comment]
I believe `where` doesn't really support multiple columns in the way that is being expected here. This is further validated by the SQL statement that is generated
```
Review.where("(post_id, author_id)" => [[1,1]])
=> "SELECT \"reviews\".* FROM \"reviews\" WHERE \"reviews\".\"(post_id, author_id)\" IN (1, 1)"
```
where the resultant query is expecting `(post_id, author_id)` to be the name of a single column.

This being a relatively less used query, and the fact that we can achieve this by using [pure string conditions](https://guides.rubyonrails.org/active_record_querying.html#pure-string-conditions) in the where clause, I am not sure if it is a good idea to add support for such queries (multi column set queries?) in Arel. Happy to discuss.

**Comment by aniketstiwari** [comment]
@qmx 

I have used a Follower model in which I will use follower_id & followee_id
```
Follow Load (50.4ms)  SELECT "follows".* FROM "follows" ORDER BY "follows"."id" ASC LIMIT $1  [["LIMIT", 1]]
 => #<Follow id: 1, follower_id: 5, followee_id: 6, created_at: "2020-09-26 06:32:13", updated_at: "2020-09-26 06:32:13">
```

Now let's discuss the problem. When you fire the query the way you have provided
```
Follow.where("(follower_id, followee_id)" => [5,6])

Follow Load (1.8ms)  SELECT "follows".* FROM "follows" WHERE "follows"."(follower_id, followee_id)" IN ($1, $2) LIMIT $3  [["(follower_id, followee_id)", 5], ["(follower_id, followee_id)", 6], ["LIMIT", 11]]
```

ActiveRecord::StatementInvalid (PG::UndefinedColumn: ERROR:  column follows.(follower_id, followee_id) does not exist

The problem is table (follows) is not able to identify the follower_id & followee_id column

In raw Sql you need to write like this

```
SELECT follows.* FROM follows WHERE (follower_id, followee_id) IN ((5, 6));

 id | follower_id | followee_id |         created_at         |         updated_at         
----+-------------+-------------+----------------------------+----------------------------
  1 |           5 |           6 | 2020-09-26 06:32:13.875478 | 2020-09-26 06:32:13.875478
```

Now to achieve the same thing in rails you can write like this

```
1st way

2.5.3 :014 > Follow.where("follower_id IN (?)", 5).where("followee_id IN (?)", 6)
  Follow Load (1.3ms)  SELECT "follows".* FROM "follows" WHERE (follower_id IN (5)) AND (followee_id IN (6)) LIMIT $1  [["LIMIT", 11]]
 => #<ActiveRecord::Relation [#<Follow id: 1, follower_id: 5, followee_id: 6, created_at: "2020-09-26 06:32:13", updated_at: "2020-09-26 06:32:13">]> 
```
```
2nd way

2.5.3 :041 > Follow.where("follower_id IN (?) AND followee_id IN (?)", 5, 6)
  Follow Load (1.3ms)  SELECT "follows".* FROM "follows" WHERE (follower_id IN (5) AND followee_id IN (6)) LIMIT $1  [["LIMIT", 11]]
 => #<ActiveRecord::Relation [#<Follow id: 1, follower_id: 5, followee_id: 6, created_at: "2020-09-26 06:32:13", updated_at: "2020-09-26 06:32:13">]> 
```

**Comment by anujmiddha** [comment]
@aniketstiwari This will not work when you are searching for multiple combinations. For example, if I wanted to search for the combinations `(5, 6), (6, 7), (7, 8)`, and I use the query
```
Follow.where("follower_id IN (?)", [5,6,7]).where("followee_id IN (?)", [6,7,8])
```
it will also return rows with follower_id 5 and followee_id 7.

**Comment by rafaelfranca** [comment]
Related to https://github.com/rails/rails/pull/36003

**Comment by aniketstiwari** [comment]
@anujmiddha  I am able to search for multiple combinations

```
Follow.where("follower_id IN (?)", [5,2]).where("followee_id IN (?)", [6,4])
  Follow Load (1.2ms)  SELECT "follows".* FROM "follows" WHERE (follower_id IN (5,2)) AND (followee_id IN (6,4)) LIMIT $1  [["LIMIT", 11]]
 => #<ActiveRecord::Relation [#<Follow id: 1, follower_id: 5, followee_id: 6, created_at: "2020-09-26 06:32:13", updated_at: "2020-09-26 06:32:13">, #<Follow id: 2, follower_id: 2, followee_id: 4, created_at: "2020-10-06 08:21:39", updated_at: "2020-10-06 08:21:39">]> 
```

Can you please more ellaborate where it will not work.

**Comment by aniketstiwari** [comment]
@rafaelfranca I tried with few solutions from the above link which you provided but it gives me syntax error.
Follow.where({ [:follower_id, :followee_id] => [[5, 2], [6,4]] })
Traceback (most recent call last):
TypeError (can't cast Array)

Database: Postgres

**Comment by anujmiddha** [comment]
@aniketstiwari Let's say you have the following `Follows`,

Follower id | Followee id
----------- |  ------------
5 | 6
2 | 4
5 | 4
2 | 6

Now if you want to get the specific combinations (5,6) and (2,4), your query will not be able to get these. It will return all the 4 rows. To get the specific combinations, you'll have to do something like,

```
Follow.where("(follower_id,followee_id) IN ((5,6),(2,4))")
```
which checks for the exact pairs.

**Comment by lxxxvi** [comment]
Probably not the main topic here, but just in case someone is confused by this.

The `WHERE (a, b) IN (...)`-syntax is slightly different in database engines:

In SQLite you have to use `VALUES`, in MySQL you may not use it. Postgres handles both.

| | `(a, b) IN (VALUES (5, 6), (2, 4))` | `(a, b) IN ((5, 6), (2, 4))` |
|:--|:--:|:--:|
| SQLite |  ✅ | ❌ |
| MySQL |  ❌ | ✅ |
| Postgres |  ✅ | ✅ |

Also, the argument for `IN` could be a `SELECT` again, like:

```sql
(a, b) IN (SELECT a, b FROM other_table)
```

**Comment by aniketstiwari** [comment]
I believe we can close these issues since we already got the answer from @anujmiddha

**Comment by nvasilevski** [comment]
Hey folks, if anyone still follows this issue I wanted to share that Rails 7.1 will include the "query by tuple" syntax https://github.com/rails/rails/pull/47729 which provides capabilities similar to ones requested here. So it will be possible to query records using `columns_set => values_sets` mapping.
Example: `Review.where([:post_id, :author_id] => [[1,1],[2,3]]).to_a` 

The new syntax produces a series of `OR` statements for each values set which is not the same as the `(co1, col2) IN ((1,1), (2,3))` row-constructor syntax that was proposed here however it's a suitable equivalent that returns the same dataset and performance difference may not be noticeable on small values sets
