### ISSUE TITLE
Calling preload overwrites non persisted associations

### ISSUE THREAD

**Issue by TheRusskiy** [rails/rails#40298]
### Steps to reproduce
This behavior happened after Rails 5.2 -> Rails 6 upgrade.
Here's the minimal example you can execute to reproduce:
```
order = Order.new
order.order_items.new
ActiveRecord::Base::Preloader.new.preload(order, order_items: {})
order.order_items
=> #<ActiveRecord::Associations::CollectionProxy []>
```

Now, here's a twist, if you do
```
order = Order.new
order.order_items.new
order.order_items.to_a # NEW, force evaluation of the association
ActiveRecord::Base::Preloader.new.preload(order, order_items: {})
order.order_items
=> #<ActiveRecord::Associations::CollectionProxy [#<OrderItem id: nil ... >]>
```
You don't need to call `to_a`, it can be `pp` or just REPL evaluation of it.

### Expected behavior
Newly created records should be kept during preload.

### Actual behavior
Newly created records are overwritten during preload.

### System configuration
**Rails version**:
    rails (6.0.3.3)
      actioncable (= 6.0.3.3)
      actionmailbox (= 6.0.3.3)
      actionmailer (= 6.0.3.3)
      actionpack (= 6.0.3.3)
      actiontext (= 6.0.3.3)
      actionview (= 6.0.3.3)
      activejob (= 6.0.3.3)
      activemodel (= 6.0.3.3)
      activerecord (= 6.0.3.3)
      activestorage (= 6.0.3.3)
      activesupport (= 6.0.3.3)
      bundler (>= 1.3.0)
      railties (= 6.0.3.3)
**Ruby version**:
2.6.3

**Comment by composerinteralia** [comment]
The `Preloader` class is not part of the public API (note the nodoc comment), 

https://github.com/rails/rails/blob/18187a95dc0eb81753044cf7d18cd31618b6f1e8/activerecord/lib/active_record/associations/preloader.rb#L45

so it isn't necessarily meant to be stable from one version to another. Is this something you can reproduce by public, documented methods?

**Comment by TheRusskiy** [comment]
@composerinteralia you are right, technically this class is undocumented in Rails, however, Preloader is very widely used in the community: there are blog posts about it and some gems use it.
I don't think this is the worst must-fix bug, but it does have subtle, hard to detect implications.

**Comment by composerinteralia** [comment]
> Preloader is very widely used in the community

Got it. Let's get someone on the core team to weigh in on whether we would like to publicly document the class. If we do that we may also want to add some additional test coverage (like the tests below). Right now I think the only test covering the `Preloader` class directly is https://github.com/rails/rails/blob/3524dd9789e445a11e20f2b8fbb559003d82c13b/activerecord/test/cases/associations_test.rb#L358-L370.

A failing test for this particular regression might look like:

```rb
  def test_preload_with_unpersisted_associations
    post = posts(:welcome)
    new_comment = post.comments.new

    preloader = ActiveRecord::Associations::Preloader.new
    preloader.preload([post], :comments)

    assert_predicate post.comments, :loaded?
    assert_equal [new_comment, comments(:greetings), comments(:more_greetings)], post.comments
  end
```

I can get this test passing by changing the line where we associate the preloaded comments back with the owner to concatenate instead of overwrite:

https://github.com/rails/rails/blob/7503ef9490583f7b2c3a475edd2bb1b7de0afcac/activerecord/lib/active_record/associations/preloader/association.rb#L73-L80

```diff
- association.target = records
+ association.target += records
```

However, that change gets strange if we are preloading with a scope. It would make this test pass, and I am not sure it makes sense for it to pass:

```rb
  def test_preload_with_unpersisted_associations_and_scope
    post = posts(:welcome)
    new_comment = post.comments.new

    preloader = ActiveRecord::Associations::Preloader.new
    preloader.preload([post], :comments, Comment.where(body: "Thank you for the welcome"))

    assert_predicate post.comments, :loaded?
    # Should new_comment be in this list if we preloaded with a scope???
    assert_equal [new_comment, comments(:greetings)], post.comments
  end
```

**Comment by kaspth** [comment]
> technically this class is undocumented in Rails

That means it's private API, which we don't maintain backwardscompatibility for on neither major nor minor versions. Use is at your own risk, even if you heard about it in a blog post.

Until something like https://github.com/rails/rails/pull/32136 gets merged and we decide to make the Preloader public, there's nothing to fix on our end.

**Comment by TheRusskiy** [comment]
@kaspth this was given a different treatment: https://github.com/rails/rails/issues/36638

**Comment by kaspth** [comment]
Yeah, there's rules and there's exceptions. Maybe someone will send a PR, but for now, no bueno.

This will be the end of it for me 👍
