### ISSUE TITLE
Inaccurate comment in ApplicationJob template

### ISSUE THREAD

**Issue by ce07c3** [rails/rails#40318]
https://github.com/rails/rails/blob/6-0-stable/activejob/lib/rails/generators/job/templates/application_job.rb.tt:

```rb
# Most jobs are safe to ignore if the underlying records are no longer available
# discard_on ActiveJob::DeserializationError
```

This error is raised for any errors during deserialization, not exclusively for AR records that are no longer available.

https://github.com/rails/rails/blob/6-0-stable/activejob/lib/active_job/arguments.rb:

```rb
   # Deserializes a set of arguments. Intrinsic types that can safely be
    # deserialized without mutation are returned as-is. Arrays/Hashes are
    # deserialized element by element. All other types are deserialized using
    # GlobalID.
    def deserialize(arguments)
      arguments.map { |argument| deserialize_argument(argument) }
    rescue
      raise DeserializationError
    end
```

Say the database is slow to respond and the query times out, then this would raise a `DeserializationError` error as well.

**Comment by p8** [comment]
If the database is slow to respond an `AdapterTimeout` is raised. https://github.com/rails/rails/blob/397bfb0e83af5de6fa725c5e2a83f5a998258fa7/activerecord/lib/active_record/errors.rb#L398
`AdapterTimeout` inherits from `StandardError` which is rescued by the default `rescue`. I think this is a bug and not by design.

**Comment by ce07c3** [comment]
Still an issue.

**Comment by ce07c3** [comment]
Still an issue.

**Comment by ghiculescu** [comment]
> Say the database is slow to respond and the query times out, then this would raise a `DeserializationError` error as well.

While true, this is unlikely given the database query would be a `Model.find` query via GlobalID.

@ce07c3 how do you propose this be fixed? Is it an issue with the code comments or is there a change to functionality you think should be made?

**Comment by ce07c3** [comment]
> > Say the database is slow to respond and the query times out, then this would raise a `DeserializationError` error as well.
> 
> While true, this is unlikely given the database query would be a `Model.find` query via GlobalID. I think the comment is correct 99+% of the time and that feels fine, particularly as the `discard_on` statement is not enabled by default.

It's just an example. Even if that were the only problem, if it's 99%, it's still not _generally true_, unfortunately, which the documentation should strive for.

There are other deserialization errors that can occur.

> https://github.com/rails/rails/blob/21243aab93811ef6737951a68d3915f17b1d0280/activejob/lib/rails/generators/job/templates/application_job.rb.tt#L7
> 
> @ce07c3 how do you propose this be improved? Is it an issue with the code comments or is there a change to functionality you think should be made?

I believe all that needs to be changed is the comment.

**Comment by ghiculescu** [comment]
> I believe all that needs to be changed is the comment.

Okay, I see your point - do you want to propose new wording? https://guides.rubyonrails.org/contributing_to_ruby_on_rails.html runs you through how to make a PR with your proposed changes 👍
