### ISSUE TITLE
 TypeError:no implicit conversion of Array into String in csrf_token_hmac method

### ISSUE THREAD

**Issue by virajchheda** [rails/rails#40322]
### Below file is giving error

file name: - **app/views/layouts/application.html.erb**
`
<!DOCTYPE html>

<html>

  <head>

    <title>App</title>

    <%= csrf_meta_tags %>#this line giving error

    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

  </head>

</html>
`

### Expected behavior

Should not give error. i.e load a page

### Actual behavior

Error: **no implicit conversion of Array into String** on method **csrf_token_hmac**
![error](https://user-images.githubusercontent.com/38850138/94965471-2ea7c400-0519-11eb-8721-edd40aa525b6.png)

### System configuration
**Rails version**:
rails (5.2.4.4)
**Ruby version**:
ruby (2.5.7)

Please provide way to fix this. Thanks in advance!

**Comment by p8** [comment]
Looking at the implementation of `csrf_meta_tags` it should always return a String instead of an array:
https://github.com/rails/rails/blob/5-2-stable/actionview/lib/action_view/helpers/csrf_helper.rb#L22-L29
Did you overrride csrf_meta_tags? What happens if you inspect the output?
```<%= debug csrf_meta_tags %>```
