### ISSUE TITLE
Make the `rake` passthrough less surprising

### ISSUE THREAD

**Issue by avdi** [rails/rails#40330]
Something I've watched my in-house Rails newbie do:

1. Misremember/guess at a `rails` subcommand, e.g. `rails serve` instead of `rails server`
2. `rails` doesn't recognize it... so it passes it through to `rake`, which then offers a list of `rake` tasks... which does NOT include the subcommand she was looking for (`rails server`), because it's a list of Rake tasks, not a list of `rails` subcommands.
3. Newbie yells something unprintable.

I love the concept behind the `rake` pass-through... but it's one of those things that needs to work consistently to be more useful than confusing. Right now it's in an uncanny valley state that feels super unfriendly to newbies.

Suggested behavior:

Pass through only rake tasks that appear in `rake -T`. If a subcommand isn't recognized and it isn't in `rake -T`, suggest "did you mean..." based on the combined set of `rails` subcommands and documented Rake tasks.

**Comment by p8** [comment]
hi @avdi. I've explored this in https://github.com/rails/rails/pull/39524
