### ISSUE TITLE
`rails dev:cache` is documented in Guides but hidden from command listings

### ISSUE THREAD

**Issue by avdi** [rails/rails#40331]
The [Rails Caching guide ](https://guides.rubyonrails.org/caching_with_rails.html#caching-in-development) documents the `rails dev:cache` command, but this command isn't listed in either `rails --help` or `rake -T`. `rake -T cache -A` finds it, but reveals nothing about it.

If this is public command (as indicated by the guide), maybe it should be listed and documented in the Rake output?

**Comment by abhaynikam** [comment]
@avdi I could see the command listed when `rails --help | grep dev:cache` is used but `rake -T` doesn't list it. Maybe because `dev:cache` is not a rake task 😊 

<img width="1587" alt="zsh 2020-10-05 10-51-52" src="https://user-images.githubusercontent.com/7736232/95042944-ff4fad80-06f8-11eb-9029-3dfd9a123eb7.png">

**Comment by avdi** [comment]
```shell
$ bundle info rails
The dependency tzinfo-data (>= 0) will be unused by any of the platforms Bundler is installing for. Bundler is installing for ruby but the dependency is only for x86-mingw32, x86-mswin32, x64-mingw32, java. To add those platforms to the bundle, run `bundle lock --add-platform x86-mingw32 x86-mswin32 x64-mingw32 java`.
  * rails (6.0.3.3)
        Summary: Full-stack web application framework.
        Homepage: https://rubyonrails.org
        Path: /devcache/gems/gems/rails-6.0.3.3
$ rake -T dev:cache -A 
rake dev:cache  #
```

Rake will only show you undocumented tasks if you specify `-A`.

However, I was wrong about one thing: `rake --help` _does_ include `dev:cache` in its long, undocumented "In addition..." list at the end of output.
