### ISSUE TITLE
Tables with dot in name recognizes as tables from another database

### ISSUE THREAD

**Issue by ksilex** [rails/rails#40335]
Example:
I'm using database called "blog" and table in it named "Posts.archived". If I will try, for example: "rake db:schema:dump" Rails will throw access denied, pointing on "Posts.archived" and telling that it can't access database called "Posts" and 
will stop populating "schema.rb" after "Posts.archived" table.

**Comment by lxxxvi** [comment]
I guess you cannot have tables with dots in it.

```ruby
create_table "with.dot" do |t|
  t.string 'name'
end
```

**SQLite3**

```
SQLite3::SQLException: unknown database "with"
```

**Postgres**

```
ERROR:  schema "with" does not exist
LINE 1: CREATE TABLE "with"."dot" ("id" bigserial primary key, "name...
```

**MySQL**

```
Mysql2::Error: Unknown database 'with'
```

---

However, these database engines actually support table names with dots in them, but I think it's better to not do that (my personal opinion). [This comment on StackOverflow](https://stackoverflow.com/a/41948522/2137007) has some good arguments why.

**Comment by tahsin352** [comment]
as the doc said, you should mention schema name or database name like below for postgresql
```ruby
create_table "public.with.dot" do |t|
  t.string 'name'
end
```
here public is schema name.
