### ISSUE TITLE
Bug: ActiveStorage method "attach" not work if model have validation errors

### ISSUE THREAD

**Issue by nPaul** [rails/rails#40333]
please fix it

example:
```
avatar = { io: StringIO.new(Base64.decode64(photo)), filename: "avatar" }
employee = Employee.new name: 'name'
employee.save!(validate: false) # have validation errors
puts employee.persisted?
true
res = employee.avatar.attach(avatar)
puts res
false

puts employee.errors.messages
{:chief=>["must exist"]}
employee.reload
puts employee.avatar.attached?
false
```

**Comment by abhaynikam** [comment]
@nPaul Active Storage attach tries to re-save the Active Record. Refer: https://github.com/rails/rails/blob/master/activestorage/lib/active_storage/attached/one.rb#L33

Not sure if attach should accept the argument like `validate: false` to resolve this issue so not trying to raise a fix for it. But in case that is approved by some Rails team member I can raise a patch for it.

The work-around could be as follows: 
```
avatar = { io: StringIO.new(Base64.decode64(photo)), filename: "avatar" }
employee = Employee.new name: 'name'
employee.avatar.attach(avatar)
employee.save!(validate: false)
```

**Comment by nPaul** [comment]
> @nPaul Active Storage attach tries to re-save the Active Record. Refer: https://github.com/rails/rails/blob/master/activestorage/lib/active_storage/attached/one.rb#L33
> 
> Not sure if attach should accept the argument like `validate: false` to resolve this issue so not trying to raise a fix for it. But in case that is approved by some Rails team member I can raise a patch for it.
> 
> The work-around could be as follows:
> 
> ```
> avatar = { io: StringIO.new(Base64.decode64(photo)), filename: "avatar" }
> employee = Employee.new name: 'name'
> employee.avatar.attach(avatar)
> employee.save!(validate: false)
> ```

Yes it works

But i think it is bug, or not obviously

For example
I have more records with no valid records, created long ago time.
Now i want attach them avatars, but i cant do it. 
`employee = Employee.find(id)
employee.avatar.attach(avatar)
`

i think method
[](https://github.com/rails/rails/blob/master/activestorage/lib/active_storage/attached/one.rb#L30)
must using save!(validate: false)
as default
he shouldn't care about valid or invalid model

**Comment by vasaf** [comment]
Finding myself needing validate: false on attach as well.
