### ISSUE TITLE
form_with sometimes generate strange text in the first hidden_field/hidden_field_tag

### ISSUE THREAD

**Issue by iggant** [rails/rails#40343]
### Steps to reproduce
      <%= form_with model: @document, url: admin_client_documents_path(@client), multipart: true, local: false,
        html: {class: 'pane-section flex'} do |f| %>
        <%= hidden_field_tag :tratata2 %>
        <%= hidden_field_tag :tratata %>
      <% end %>

### Expected behavior
```
<form enctype="multipart/form-data" action="/admin/b/clients/41/documents" accept-charset="UTF-8" data-remote="true" method="post" class="pane-section flex">
<input type="hidden" name="authenticity_token" value="tvXcoOmiB9ys3EMHEt9xjhCLCQbVFAfy1f8UYsjXtEdt/sj/9gkA5X5kp65Ode24x0ecUnsl08jjSBey7fP+sw=="> 
<input type="hidden" name="tratata2" id="tratata2" value=""> 
<input type="hidden" name="tratata" id="tratata"> 
<input type="hidden" value="raw" name="document[doc_type]" id="document_doc_type"> 
</form>
```

### Actual behavior
```
<form enctype="multipart/form-data" action="/admin/clients/1/documents" accept-charset="UTF-8" data-remote="true" method="post" class="pane-section flex">
<input type="hidden" name="authenticity_token" value="tvXcoOmiB9ys3EMHEt9xjhCLCQbVFAfy1f8UYsjXtEdt/sj/9gkA5X5kp65Ode24x0ecUnsl08jjSBey7fP+sw=="> 
<input type="hidden" name="tratata2" id="tratata2" value="UhAQQOLw2/mVlarIZDVXzmrPBfRu/8ginc5RMnsIE1eJGwQf/VvcwEctTmE4n8v4vQOQoMDOHBireVLiXixZow=="> 
<input type="hidden" name="tratata" id="tratata"> 
<input type="hidden" value="raw" name="document[doc_type]" id="document_doc_type"> 
</form>
```

### System configuration
**Rails version**:
   6.0.3.2
**Ruby version**:
   ruby 2.6.5p114

But I can't reproduce it constantly after I restart rails s (puma) everything start doing fine. 
every 1000th run (very rarely we have this on dev/production.

**Comment by jonathanhefner** [comment]
@iggant Are you using Firefox?  If so, I think you may be experiencing [this Firefox bug](https://bugzilla.mozilla.org/show_bug.cgi?id=520561).  Unfortunately, it has been marked as inactive.

Related discussion: https://discuss.rubyonrails.org/t/form-with-first-field-value-is-overriden-with-a-token-like-string/74861

**Comment by yoones** [comment]
@iggant out of curiosity, would it be helpful to turn off autocomplete in your case? I'm not sure whether it applies to hidden fields or not.

`<%= hidden_field_tag :tratata2, autocomplete: 'off' %>`

**Comment by iggant** [comment]
@yoones this bug is so strange, so for now I can't reproduce it, so can't check your suggestion with autocomplete

so I'm going to close this one
