### ISSUE TITLE
Wrong number of argument Error on initialising an activerecord object

### ISSUE THREAD

**Issue by subashkc** [rails/rails#40340]
### Steps to reproduce

1. Create a new rails app
2. Generate any scaffold (e.g. photo) and run the db migrations
3. Add a empty initialise method in the photo model,

       class Photo < ApplicationRecord  
         def initialize
         end  
       end

4. In rails console type, `Photo.new` and it'll throw this error,

> Traceback (most recent call last):
        2: from (irb):1
        1: from app/models/photo.rb:2:in `initialize'
ArgumentError (wrong number of arguments (given 1, expected 0))

### System configuration
**Rails version**:
Rails 6.0.3.3

**Ruby version**:
ruby 2.7.1p83

**Comment by esparta** [comment]
Not sure, but what is your expected behavior here?

If you overwrite the initialize method of any ruby class expecting a parameter and not provide a `super()` call, you will have this problem. Is not something RoR maintainers can do something about it, and is not how it's documented to work with ActiveRecord.

**Comment by subashkc** [comment]
@esparta I was trying to simplify the example, my method does have the `super` call in it, it was working fine with `rails 5.1.4` doesn't with `rails 6.0.3.3`

**Comment by aniketstiwari** [comment]
@subashkc  I am not able to reproduce the issue in rails 6.0.3.3.. Can you provide the repository link

**Comment by subashkc** [comment]
@aniketstiwari https://github.com/subashkc/test_rails6_activerecord

**Comment by louim** [comment]
@subashkc ActiveRecord expect to receive an attribute hash as the argument when calling `super`. If you call `super` without any parameter, you will get the error you mentioned. Either don't call `super` if you don't need attribute initialization, or pass a hash of parameters to the `super` call.

See the documentation here: https://api.rubyonrails.org/classes/ActiveModel/Model.html. Your initialize method should look like this:
```ruby
def initialize(attributes={})
  super
  #more custom code here
end
```

**Comment by jonathanhefner** [comment]
@subashkc  What @louim said is correct:

> Your initialize method should look like this:
> 
> ```ruby
> def initialize(attributes={})
>   super
>   #more custom code here
> end
> ```

Specifically though, `initialize` must accept an argument, regardless of how it calls `super`.

**Comment by subashkc** [comment]
Thanks @louim and @jonathanhefner, I'll change the method to accept an attribute hash, was pre-existing legacy code so wanted to be sure before changing it. I was wondering if something changed between rails 5 and 6 because the guide for rails 5 https://api.rubyonrails.org/v5.1.4/classes/ActiveModel/Model.html says the same thing about passing an attribute hash to the `initialize` method but it didn't raise the warning on just doing a `.new` without any arguments.
