### ISSUE TITLE
Records in the different shards are randomly regarded as the same

### ISSUE THREAD

**Issue by sekiyama58** [rails/rails#40358]
### Steps to reproduce
In the horizontal sharding setup, the ActiveRecord instances in the different shards, which have different data, can be regarded as the same object randomly.

For example, if you have the `User` model with auto-incremental `id` and `name` column, and shards `group1` and `group2` for the `User` model:

```ruby
users = []

ActiveRecord::Base.connected_to(shard: :group1, role: :writing) do
  users << User.create!(name: "Alice")
  users << User.create!(name: "Bob")
end
ActiveRecord::Base.connected_to(shard: :group2, role: :writing) do
  users << User.create!(name: "Charlie")
end

users #=> [#<User id: 1, name: "Alice">, #<User id: 2, name: "Bob">, #<User id: 1, name: "Charlie">]

users.uniq #=> [#<User id: 1, name: "Alice">, #<User id: 2, name: "Bob">>]  # Charlie is removed...

users[0] == users[1]  #=> false
users[0] == users[2]  #=> true
users[1] == users[2]  #=> false
```

Because only the auto-incremental id is considered for record comparizon in current implementation of ActiveRecord, the different `users` might be regarded as the same.

### Expected behavior
`ActiveRecord::Core.==` should return false on comparing records in the different shards, which store independent data.

Note that, records in the different roles and the same shard should be equal, becuase they are concidered as replicated.

### Actual behavior
When the primary key is the same, records in different shards are regarded as equal.

### System configuration
**Rails version**:
6.1.0alpha ( commit 9492339979e9457 )

**Ruby version**:
2.7..0

**Comment by eileencodes** [comment]
Hey @sekiyama58 thanks for the report! Can you make a new app that uses tests or a script to reproduce? That will help us debug.

**Comment by sekiyama58** [comment]
@eileencodes thanks, I have added a repo to reproduce this issue: https://github.com/sekiyama58/rails61-sharding-test
After `db:migrate:reset` (and `rm -f db/group*` if you need), if you run the test by `rake` multiple times, it will returns different results.

**Comment by tahsin352** [comment]
@sekiyama58 could you please try this pr https://github.com/rails/rails/pull/40361?

**Comment by sekiyama58** [comment]
@tahsin352 Thanks for working on this. I have tested with your pr, but it didn't solved the issue.
Both "Alice" and "Charlie" are `User` class in this case, so I think `comparison_object.class.current_shard == self.class.current_shard` means `User.current_shard == User.current_shard`, that is always true.

**Comment by tahsin352** [comment]
Each shard will have User class, right? So, each object should have it's own shard attribute, right?

**Comment by sekiyama58** [comment]
> Each shard will have User class, right?
The User class itself is shared among shards.

> each object should have it's own shard attribute
I think that will be helpful to solve this issue.

**Comment by sekiyama58** [comment]
Adding the link to my comment in tahsin352's PR here too: https://github.com/rails/rails/pull/40361#issuecomment-707453891

I'd like to discuss how ActiveRecord should compare the object from different shards.
> Without sharding, the primary key is what to be used to distiinguish unique records.
> However, once sharding is introduced, the system may have the same primary key in multiple DB, so the single primary key is not enough to specify the record. Shard key, like :default or :shard_one is also required.
> 
> It is possible to choose a design that ignores the shard key in an ActiveRecord instance and puts the responsibility to distinguish Alice and Charlie on the user, although that is, I think, confusing. IMHO, the instance should keep track with the shard key and use it to distinguish records, as well the primary key.

There could be various solution for this ( adding custom comparator to app, using uuid, introducomg unique id sequencer over shards, etc. ), and I'd like to know what will be a recommended solution.
