### ISSUE TITLE
ActiveStorage: variant(convert: ...) doesn't work

### ISSUE THREAD

**Issue by kirkas** [rails/rails#40356]
https://github.com/rails/rails/issues/32063 and https://github.com/rails/rails/pull/40226 seem to be suggesting that ActiveStorage support images conversion, but it doesn't seem to work.

### Steps to reproduce
Add an attachment to any model, in my example I have something like

```ruby
class Company < ActiveRecord::Base
    # ...
    has_one_attached :logo
end
```

Then attach a png or jpeg to your model.

### Expected behavior
I expect `company.logo` to return the original format (in this case, *png*) and `company.logo.variant(convert: :jpeg)` to return a jpeg format.

### Actual behavior
The format stays the same

```ruby
> polymorphic_url(company.logo)
=> ".../rails/active_storage/blobs/[BLOB_HASH]/essex_farm_logo.png"

> polymorphic_url(company.logo.variant(convert: :jpg))
=> ".../rails/active_storage/representations/[BLOB_HASH]/[REPRESENTATION_HASH]/essex_farm_logo.png"

> polymorphic_url(company.logo.variant(convert: :jpg).processed)
=> ".../rails/active_storage/representations/[BLOB_HASH]/[REPRESENTATION_HASH]/essex_farm_logo.png"

> polymorphic_url(company.logo.blob.variant(convert: :jpg).processed)
=> ".../rails/active_storage/representations/[BLOB_HASH]/[REPRESENTATION_HASH]/essex_farm_logo.png"

polymorphic_url(company.logo.variant(format: :jpg))
=> ".../rails/active_storage/representations/[BLOB_HASH]/[REPRESENTATION_HASH]/essex_farm_logo.png"
```

And sometimes it produces an error:
```
> polymorphic_url(company.logo.variant(format: :jpg).processed)
Disk Storage (0.1ms) Checked if file exists at key: variants/yewnbh9pcelode7o2ub82x4h55jx/2222255258486b227c3b33abaaddcf2b8b0a032f63a13b3c9e7ac6743a17c392 (no)
  Disk Storage (0.4ms) Downloaded file from key: yewnbh9pcelode7o2ub82x4h55jx
Traceback (most recent call last):
        1: from (irb):124
TypeError (no implicit conversion of Symbol into String)
```

I've tried various source image (png, webp, jpeg, jpg) and 
company.logo.variant(convert: :webp)

### System configuration
**Rails version**:
Rails 6.0.3.4

**Ruby version**:
ruby-2.6.5

**Comment by georgeclaghorn** [comment]
A few things:

* The option implemented in #40266 is `:format`, not `:convert`. I don’t remember if `:convert` sometimes worked before, but it wasn’t intended to.
* It’s in master, due for release in 6.1.0—not in 6.0.3.
* The format in the URL doesn’t change due to Reasons. (For one, Previews for non-image blobs don’t know what type of image the Previewer will eventually produce, even though it happens to be PNG for all in-tree Previewers right now.) URLs contain the original blob’s filename, not the filename of the image representation.

**Comment by kirkas** [comment]
Thanks for your reply, I've tried both `:format` and `:convert`, on both `company.logo` and `company.logo.blob`, with no luck.

I understand the filename would stay the same, but it seems counter-intuitive that the file extension and the content-type also stays the same.

Note: The [ImageProcessing](https://github.com/janko/image_processing) gem upon which ActiveStorage relies seems to change the file extension correctly.

Question: Do we know when it 6.1.0 is due for release?

**Comment by tosbourn** [comment]
> Question: Do we know when it 6.1.0 is due for release?

It is out now :-)

I can confirm that with Rails 6.1 `format: :webp` etc works.
