### ISSUE TITLE
Unable to load ActionText::Attachable due to ActiveSupport::MessageVerifier::InvalidSignature despite same secret_key_base

### ISSUE THREAD

**Issue by lylo** [rails/rails#40352]
### Steps to reproduce

In my ActionText editor I have added a content attachment (an `ActionText::Attachable`) which relates to an ActiveRecord object via `sgid`. I can embed an IFRAME (retrived via oembed in my case) so that it renders correctly and displays the embedded HMTL. It's based on this approach from the recent RailsConf: https://www.railsconf.org/2020/video/chris-oliver-advanced-actiontext-attaching-any-model-in-rich-text.

While this works fine I've noticed that the SGID isn't "portable" to a different server despite the `SECRET_KEY_BASE` of both instances being identical, and the databases for each being identical (one was a restore of the other and record IDs are all idential etc).

I wondered if someone might be able to help either identify an bug, or point me towards the error of my ways! Thanks.

### Expected behavior

Given a Rails instance on two different servers, each with a _copy_ of the same database and each with identical secret key base value, I would expect a SGID to be successfully deserialised on each one.

### Actual behavior

On my original server, given the ActionText node sgid, I can verify the SGID:

```ruby
SignedGlobalID.send(:pick_verifier, for: "attachable").verify(node["sgid"])
=> {"gid"=>"gid://myapp/Model/1?expires_in", "purpose"=>"attachable", "expires_at"=>nil}
```

On my duplicate server, given the same ActionText node sgid, the verification fails:

```ruby 
SignedGlobalID.send(:pick_verifier, for: "attachable").verify(node["sgid"])
=> ActiveSupport::MessageVerifier::InvalidSignature (ActiveSupport::MessageVerifier::InvalidSignature)
```

`node["sgid"]` is indentical on both servers and `Model.find(1)` works on both instances as the databases are identical. 

I would expect it to work the same on both instances. However it seems like perhaps there's an issue with the secret? Maybe my understanding isn't correct but I thought Rails uses the secret key base value for the verifiers, therefore if this was the same the verification should work?

### System configuration
**Rails version**:

6.1 alpha - currently at `1eafed13e3b6a5475a3dcf3e7efd83d7e3224548`

**Ruby version**:

2.7.1

**Comment by lylo** [comment]
Ok, apologies but it turns out that despite `Rails.application.credentials.secret_key_base` being defined the same on both servers, one of them (Heroku) had also defined a different `SECRET_KEY_BASE` environment variable which seems to take precedence. Once I define this on the new sever, the SGID works fine.

It does make me concerned now that I can never change my secret key base without breaking all my ActionText::Attachments. Is this a cause for concern?

**Comment by tahsin352** [comment]
you can use `rotate` to use old secrets. for example:

`verifier.rotate old_secret, digest: "SHA256", serializer: Marshal`

**Comment by lylo** [comment]
That's great, thanks. Will this actually be possible as the SGID values are stored in the HTML in the database by ActionText? Or will that work somehow?

Will need to do some testing.

**Comment by lylo** [comment]
Given that `ActionText::Attachment` stores SGID in a database, won't rotating the secrets result in these being invalidated?

**Comment by composerinteralia** [comment]
> SECRET_KEY_BASE environment variable which seems to take precedence

That is correct:

https://github.com/rails/rails/blob/18187a95dc0eb81753044cf7d18cd31618b6f1e8/railties/lib/rails/application.rb#L431

Since it seems like this issue has been resolved, I'm going to close it. Thank you!

**Comment by goulvench** [comment]
One last thing to note: **[in development and test environments, the `secret_key_base` in `tmp/development_secret.txt` takes precedence over the one defined in `credentials.yml.enc`](https://github.com/rails/rails/blob/18187a95dc0eb81753044cf7d18cd31618b6f1e8/railties/lib/rails/application.rb#L427)**. 
So if you grab a copy of the production database, ensure all credentials and ENV vars are the same, but still get MissingAttachment errors, replace the contents of `tmp/development_secret.txt` with the `secret_key_base` used in production environment (loaded from ENV, credentials, or secrets).

I wasted a few hours trying to understand why attachments would not load after copying the database, master.key and ENV vars, now it finally works.
