### ISSUE TITLE
Setting action_dispatch.return_only_media_type_on_content_type has no effect on the application

### ISSUE THREAD

**Issue by spaghetticode** [rails/rails#40376]
### Steps to reproduce

* create a new rails app
* add `Rails.application.config.action_dispatch.return_only_media_type_on_content_type = true` in a initializer file
* `curl -I` any URL and verify that the content type header still includes the charset `Content-Type: text/plain; charset=utf-8`
See https://github.com/spaghetticode/rails_6_content_type_issue

### Expected behavior
When`Rails.application.config.action_dispatch.return_only_media_type_on_content_type` is set to `true`, the content_type header should not include the charset, like this: `Content-Type: text/plain`

### Actual behavior
When`Rails.application.config.action_dispatch.return_only_media_type_on_content_type` is set to `true`, the content_type header still includes the charset: `Content-Type: text/plain; charset=utf-8`

### System configuration
**Rails version**:
6.0.3.3, master (Rails 6.1.0.alpha)

**Ruby version**:
2.6.3

**Comment by eugeneius** [comment]
`return_only_media_type_on_content_type` only affects the result of calling the `content_type` method e.g. in a controller, not the actual response header.
