### ISSUE TITLE
delegate_missing_to

### ISSUE THREAD

**Issue by DevHachi** [rails/rails#40375]
### Steps to reproduce
install rails 6.0.3.4
put in some Model this method:
`delegate_missing_to :asset, allow_nil: true`

### Expected behavior
getting nil instead of ArgumentError

### Actual behavior
I am getting this error:  `delegate_missing_to': wrong number of arguments (given 2, expected 1) (ArgumentError)

### System configuration
**Rails version**: 6.0.3.4

**Ruby version**: 2.6.5

Is there a newer version of rails, because on your master branch the method definition looks like this.
`delegate_missing_to(target, allow_nil: nil)`

but in my downloaded gem it looks like the following:
`delegate_missing_to(target)`

**Comment by eugeneius** [comment]
That feature will be released in Rails 6.1.
