### ISSUE TITLE
ActiveRecord#read_attribute_before_type_cast returns wrong value

### ISSUE THREAD

**Issue by kvokka** [rails/rails#40374]
### Steps to reproduce

```ruby
class Foo < ActiveRecord::Base
  self.table_name = 'foos'
  enum duration: { something: 1, another: 2 }
end

q= Foo.new(duration: :something)
q.read_attribute_before_type_cast :duration # => :something

```

### Expected behavior

it should return `1` for this case, [docs link](https://apidock.com/rails/ActiveRecord/AttributeMethods/BeforeTypeCast/read_attribute_before_type_cast)

### Actual behavior

just returns casted value

### System configuration
**Rails version**: 6.0.3.4

**Ruby version**: MRI 2.7.1

**Comment by ttilberg** [comment]
Reading through the referenced docs, I would expect it to return `:duration`, as that was the unmodified input for the attribute. Working out the enum value is a form of typecasting: [Link to supporting source](https://github.com/rails/rails/blob/b5b078cd99b0107fd8e31ff619578e5321182e0a/activerecord/lib/active_record/enum.rb#L126).

**Comment by eugeneius** [comment]
Exactly: `:something` is the value of the attribute before typecasting was applied.

**Comment by YassineDM** [comment]
@eugeneius I actually was wondering the same thing so maybe this helps:
```ruby
q= Foo.new(duration: :something)
q.read_attribute_before_type_cast :duration # => :something
q.save # => true
q.read_attribute_before_type_cast :duration # => 1
```

But I think this could be a workaround when record is not yet persisted:
```ruby
q= Foo.new(duration: :something)
q.read_attribute_before_type_cast :duration # => :something
Foo.durations[q.duration] # => 1
```
