### ISSUE TITLE
Performance regression on ActiveSupport::SafeBuffer#gsub, sub, gsub!, sub! methods when called with block

### ISSUE THREAD

**Issue by shioyama** [rails/rails#40389]
https://github.com/rails/rails/pull/34405 caused a performance regression on `gsub`, `gsub!`, `sub` and `sub!` methods when called on an `ActiveSupport::SafeBuffer` with a block.

I noticed this because we were running some middleware doing swaps with `gsub`. Converting the `SafeBuffer` to a `String` with `to_str` fixed the problem for that particular case, but that does not fix the problem for anyone who is not aware of it.

### Steps to reproduce

I created a gist: https://gist.github.com/shioyama/07d0d92fd3ab58385010b12af4ac734c

Run with `String#gsub`:

```
❯ ruby gsub_benchmark.rb -i 10000
String Class: String
ActiveSupport is not loaded.
Max: 0.3570000000000517 ms
Min: 0.11299999999991872 ms
Average: 0.14096810000000023 ms
Median: 0.13699999999960966 ms
```

Run with `ActiveSupport::SafeBuffer#gsub` and ActiveSupport v6.0.3.2

```
❯ ruby gsub_benchmark.rb -i 10000 -a 6.0.3.2
String Class: ActiveSupport::SafeBuffer
ActiveSupport version: 6.0.3.2.
Max: 4.517999999999134 ms
Min: 1.1769999999997616 ms
Average: 1.906966700000005 ms
Median: 1.843000000000039 ms
```

Run with `ActiveSupport::SafeBuffer#gsub` and ActiveSupport v5.2

```
❯ ruby gsub_benchmark.rb -i 10000 -a 5.2
String Class: ActiveSupport::SafeBuffer
ActiveSupport version: 5.2.
Max: 0.7739999999998304 ms
Min: 0.11699999999947863 ms
Average: 0.14751879999999976 ms
Median: 0.14099999999994672 ms
```

So:

Avg gsub time (ms) | ActiveSupport version |
--- | --- |
0.141 | No AS |
1.907 | 6.0.3.2 |
0.148 | 5.2 |

### Expected behavior

Expect `gsub` and friends to perform similarly fast on `ActiveSupport::SafeBuffer` as they do on `String`.

### Actual behavior

10x+ slowdown compared with `String#gsub`

### System configuration
**Rails version**: >= 6.0
**Ruby version**: 2.7.1

cc @shugo, @fxn, @rafaelfranca

**Comment by fxn** [comment]
Let me /cc @matthewd too.

**Comment by shioyama** [comment]
FWIW, the impact of https://github.com/rails/rails/pull/34405 is felt in the number of times the block is called, which equals the number of matches. So I was calling with 100 matches, which is quite a lot, but if you run with `-m 10` (only inserting 10 matches into the string) the slowdown is smaller but still quite visible:

Without `gsub` patches, with 10 matches:

```
~/test/gsub_benchmarking/07d0d92fd3ab58385010b12af4ac734c master* ⇣
❯ ruby gsub_benchmark.rb -i 10000 -m 10
String Class: String
ActiveSupport is not loaded.
Max: 0.32300000000007323 ms
Min: 0.09399999999981645 ms
Average: 0.11290519999999857 ms
Median: 0.11300000000002974 ms
```

With `gsub` patches, with 10 matches:

```
❯ ruby gsub_benchmark.rb -i 10000 -a 6.0.1 -m 10
String Class: ActiveSupport::SafeBuffer
ActiveSupport version: 6.0.1.
Max: 0.9609999999997676 ms
Min: 0.23299999999970566 ms
Average: 0.30249939999999864 ms
Median: 0.28799999999984394 ms
```

So roughly a 3x slowdown.

**Comment by shioyama** [comment]
Also (as I mentioned in #40391), the problem is this line:

https://github.com/rails/rails/blob/b5b078cd99b0107fd8e31ff619578e5321182e0a/activesupport/lib/active_support/core_ext/string/output_safety.rb#L269

If that line is removed, the performance regression disappears. I don't see anyway to do it faster, though.

**Comment by matthewd** [comment]
Yeah... I think this is a known/expected consequence of the behaviour improvement in that PR, unfortunately.

If it's safe for you to drop the safety via `to_str`, you can buy back the performance, but we're left defaulting to the slower-but-safer option. This particular case is a perf regression because `gsub` was previously unavoidably unsafe, but (while this one is particularly expensive) it's generally expected that SafeBuffer is slower than the equivalent operation performed on a raw String.

I wonder if there's an upstream API we could request that might allow us to regain the performance in future 🤔

(It briefly occurs to me that we could examine the supplied block to determine whether it references any of the regexp magic vars, and skip doing the slow thing if it doesn't... but that seems very likely to be even slower in its own right, and while kinda cacheable, that would also be.. nontrivial)

**Comment by shioyama** [comment]
> This particular case is a perf regression because `gsub` was previously unavoidably unsafe, but (while this one is particularly expensive) it's generally expected that SafeBuffer is slower than the equivalent operation performed on a raw String.

But it seems to me that previous to https://github.com/rails/rails/pull/34405, `gsub` on a `SafeBuffer` was _safe_ but did not work with back references.

Based on the results here, my reading is that that PR traded performance to regain that back reference functionality. I'm not sure that's a tradeoff everyone would be happy with. As you noted, if you're using the block format and not using back references, you're getting worse performance for no actual gain.

**Comment by shioyama** [comment]
> I wonder if there's an upstream API we could request that might allow us to regain the performance in future thinking

Yeah this is what I was thinking of as well... seems like the only way out of this.

**Comment by matthewd** [comment]
I guess we could possibly skip doing the thing if the block has a non-`-1` arity, making a slightly-risky assumption that that implies you're not also using the magic vars? 🤷🏻‍♂️

(Was that the case in your instance?)

**Comment by shioyama** [comment]
> I guess we could possibly skip doing the thing if the block has a non-`-1` arity, making a slightly-risky assumption that that implies you're not also using the magic vars? 🤷🏻‍♂️

Hmm in our case the proc had arity `1` but we were also referencing `Regexp.last_match`, because that made the logic simpler. I think it's probably better not to make simplifying assumptions, since anyway I'm sure that there is now lots of code out "in the wild" that depends on these back-references working.

But still, the regression is pretty significant in some situations (frequent block calls)...

**Comment by shioyama** [comment]
@matthewd I think we can at least fix this for the case where the argument passed to `gsub`/`sub` is a string, in which case back references are unnecessary.

Working on a fix for that case here: https://github.com/rails/rails/pull/40398
