### ISSUE TITLE
Feature proposal: Activerecord connections TTL

### ISSUE THREAD

**Issue by gleopoldo** [rails/rails#40394]
### Steps to reproduce
Hello, guys!

This feature proposal comes in a moment where I'm currently struggling to fix a memory leak in a multi-tenant postgres database running with more than 450 connections, more than 7K schemas and almost 3TB of data. After digging onto the problem, I discovered that this memory increase is closely related to the postgres' internal process/memory management model, where each connection caches tables oid metadata, no matter how much memory dedicated to `work_mem` or `shared_buffers` in postgres configuration. So, there are great chances that all connections are duplicating caches as they visit the same schemas tables.

I reached this conclusion after reading [this awesome article](https://techcommunity.microsoft.com/t5/azure-database-for-postgresql/analyzing-the-limits-of-connection-scalability-in-postgres/ba-p/1757266), which proves my point and has a few examples too.

In several places that I searched, the common recommendation is to recycle my old connections, and right now I hadn't found built-in support for this in activerecord itself. In this way, I'm thinking on killing connections in the pool that are older than 1 day. Do you guys think that this feature could be added in the future to the project?

### Expected behavior
I thought on having something like this :point_down: , but I'm open to suggestions:

```
# in my config/database.yml
.default: &postgres-defaults
  adapter: postgresql
  encoding: unicode
  pool: '<%= ENV.fetch("DATABASE_POOL", "10") %>'
  host: '<%= ENV.fetch("DATABASE_HOST", "localhost") %>'
  port: '<%= ENV.fetch("DATABASE_PORT", "5432") %>'
  username: '<%= ENV.fetch("DATABASE_USER", "postgres") %>'
  password: '<%= ENV.fetch("DATABASE_PASSWORD", "") %>'
  database: '<%= ENV.fetch("DATABASE_NAME", "saas_smtp") %>'
  prepared_statements: false
  # A first approach
  drop_older_connections_than: <%= 1.day %> 
  # or we can assume this value to be given in hours
  drop_older_connections_than: 24 # hours
```

This configuration could reset the connections in the pool older than the given amount of hours in that configuration. This setup prevents some complex architecture designs (IMHO) using pgbouncer (https://www.pgbouncer.org/), which I think that limits my options when dealing with the database (I lose the ability to create and manage temp tables, for example).

### Actual behavior

I didn't find support for this reading the rails guides, so I think that it's a new feature.

### System configuration
**Rails version**: This app doesn't use rails, but `activerecord` 6.0.3

**Ruby version**: 2.6.5

**Comment by composerinteralia** [comment]
Thank you! Our preferred place to discuss feature requests is the mailing list (see the [contribution guide](https://edgeguides.rubyonrails.org/contributing_to_ruby_on_rails.html#what-about-feature-requests-questionmark) for details), so I am going to close this issue.
