### ISSUE TITLE
Enum before_type_cast inconsistent return value with default

### ISSUE THREAD

**Issue by goalaleo** [rails/rails#40397]
### Steps to reproduce
Add an integer column with a default value to back an enum
```ruby
add_column :posts, :status, :integer, null: false, default: 0
```
Add an enum to the model
```ruby
enum status: { draft: 0, published: 10 }
```
Then check the value of `status_before_type_cast` of `new` record
```ruby
Post.new.status_before_type_cast
```

### Expected behavior
The default value is returned as an integer
```ruby
=> 0
```

### Actual behavior
The default value is returned as a string
```ruby
=> "0"
```
This is inconsistent with what the method returns for a persisted record
```ruby
p1 = Post.new.save
p2 = Post.new

p1.status_before_type_cast == p2.status_before_type_cast # 0 == "0"
=> false
```
### System configuration
**Rails version**: rails (6.0.3.3)

**Ruby version**: ruby (2.7.1)

**Comment by tahsin352** [comment]
Assuming this accurately describes the issue you reported, I'm unable to reproduce it.
```ruby
# frozen_string_literal: true

begin
  require "bundler/inline"
rescue LoadError => e
  $stderr.puts "Bundler version 1.10 or later is required. Please update your Bundler"
  raise e
end

gemfile(true) do
  source "https://rubygems.org"

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  # Activate the gem you are reporting the issue against.
  gem "rails", github: "rails/rails"
  gem "sqlite3"
  gem 'pry'
end

require "active_record"
require "minitest/autorun"
require "logger"

# Ensure backward compatibility with Minitest 4
Minitest::Test = MiniTest::Unit::TestCase unless defined?(Minitest::Test)

# This connection will do for database-independent bug reports.
ActiveRecord::Base.establish_connection(adapter: "sqlite3", database: ":memory:")
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :posts, force: true do |t|
    t.integer :status, :default => 0, index: true, null: false
  end
end

class Post < ActiveRecord::Base
  enum status: [ :open, :closed, :pending ]

  before_update :check_status_cast

  private

  def check_status_cast
    raise unless status_before_type_cast.is_a?(Integer)
  end

end

class BugTest < Minitest::Test
  def test_enum_cast
    post = Post.create!
    assert post.update_attributes(:status => 1)
  end
end

```

**Comment by yoelblum** [comment]
It doesn't seem to be related to enum, I took the same script and removed the enum attribute completely but the status_before_type_cast is still an Integer.

`# frozen_string_literal: true

begin
  require "bundler/inline"
rescue LoadError => e
  $stderr.puts "Bundler version 1.10 or later is required. Please update your Bundler"
  raise e
end

gemfile(true) do
  source "https://rubygems.org"

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  # Activate the gem you are reporting the issue against.
  gem "rails", github: "rails/rails"
  gem "sqlite3"
  gem 'pry'
end

require "active_record"
require "minitest/autorun"
require "logger"

# Ensure backward compatibility with Minitest 4
Minitest::Test = MiniTest::Unit::TestCase unless defined?(Minitest::Test)

# This connection will do for database-independent bug reports.
ActiveRecord::Base.establish_connection(adapter: "sqlite3", database: ":memory:")
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :posts, force: true do |t|
    t.integer :status, :default => 0, index: true, null: false
  end
end

class Post < ActiveRecord::Base


  before_update :check_status_cast

  private

  def check_status_cast
    raise unless status_before_type_cast.is_a?(Integer)
  end

end

class BugTest < Minitest::Test
  def test_enum_cast
    post = Post.create!
    assert(Post.new.status_before_type_cast.is_a? Integer)
  end
end
----`

**Comment by yoelblum** [comment]
Update: For Sqlite, his is how Sqlite works; it returns the default_value as type text https://www.oreilly.com/library/view/using-sqlite/9781449394592/re205.html  

> The default value (dflt_value) will be given as a text representation of the literal value representation. For example, a default text value includes the single quotes.

And since ActiveRecord isn't casting that value to anything, we end up with a string

@goalaleo Can you tell us which database this bug happened in? 

In any case, I suggest we change this bug description or open a new one, this isn't about enums at all.

**Comment by goalaleo** [comment]
I was using PostgreSQL 10.13. I'll try to see if I can write a script that reproduces this

**Comment by eugeneius** [comment]
An attribute's value before type cast is just that: the unmodified value, whether it was assigned, loaded from the database, or extracted from the schema. It doesn't try to—and fundamentally can't—return a consistent type. 

It seems like what you want is a way to get the integer value of an enum attribute. If so, the [docs](https://api.rubyonrails.org/classes/ActiveRecord/Enum.html) cover how to do that.

**Comment by goalaleo** [comment]
Thanks for the reply. I just found it weird that the `value_before_type_cast` is set to a string representation of the integer rather than an actual integer even though the default is specified to be the integer `0`

**Comment by eugeneius** [comment]
I agree that it's not particularly intuitive. I closed this issue because it's not a bug in Rails (`attribute_before_type_cast` is behaving as expected); if there's an alternative way to get the default value from the database with the correct type that might be an acceptable enhancement, but it's hard to know without looking at a patch.

Incidentally, https://github.com/rails/rails/pull/40456 was just opened and proposes an easier way to read an enum attribute's integer value.
