### ISSUE TITLE
Undefined method `partial_writes?' for ActiveRecord

### ISSUE THREAD

**Issue by kiawizard** [rails/rails#40408]
### Steps to reproduce
1) Launch production environment Rails application on nginx & Passenger latest, CentOS 8, Ruby 2.7.1p83
2) Wait several days

### Expected behavior
The application runs without errors

### Actual behavior
An exception randomly starts to happen: NoMethodError (undefined method `partial_writes?' for #<User:0x00000000059c88f8>
User is an ActiveRecord model

### System configuration
**Rails version**: 6.0.3.3

**Ruby version**: ruby 2.7.1p83 (2020-03-31 revision a0c7c23c9c) [x86_64-linux]

I suppose this is the same as https://github.com/rails/rails/issues/37768 (now closed)

**Comment by eileencodes** [comment]
Like I said on the previous issue we don't have enough information to debug here. Neither report has provided a stack trace or a way to reproduce. Do you have one?

**Comment by kiawizard** [comment]
Hi Eileen!
I'd be glad to gather any required information, but unfortunately, I cannot imagine any way to reproduce this on demand. The stack trace consists only of 1 call in my controller:
user.update_attribute(:last_access, Time.now)

which results in NoMethodError (undefined method `partial_writes?' for #<User:0x00000000066bf570>)

After restarting server it works just fine for a long time, and we have never faced this issue in development environment or in tests. Maybe you can give me any hint on how to find some valuable info on this?

**Comment by eileencodes** [comment]
Can you paste the entire stack?

**Comment by kiawizard** [comment]
Unfortunately, for some unknown reason, I cannot find this exact stacktrace in stderr, but there are others similar (ActiveRecord starts missing some core methods):

App 331201 output: Error: The application encountered the following error: undefined method `time_zone_aware_attributes=' for #<Class:0x00007f9e302fe498> (NoMethodError)
App 331201 output:     /usr/local/rvm/gems/ruby-2.7.1/gems/activerecord-6.0.3.3/lib/active_record/dynamic_matchers.rb:22:in `method_missing'
App 331201 output:     /usr/local/rvm/gems/ruby-2.7.1/gems/activerecord-6.0.3.3/lib/active_record/railtie.rb:71:in `block (2 levels) in <class:Railtie>'
App 331201 output:     /usr/local/rvm/gems/ruby-2.7.1/gems/activesupport-6.0.3.3/lib/active_support/lazy_load_hooks.rb:71:in `class_eval'
App 331201 output:     /usr/local/rvm/gems/ruby-2.7.1/gems/activesupport-6.0.3.3/lib/active_support/lazy_load_hooks.rb:71:in `block in execute_hook'
App 331201 output:     /usr/local/rvm/gems/ruby-2.7.1/gems/activesupport-6.0.3.3/lib/active_support/lazy_load_hooks.rb:61:in `with_execution_control'
App 331201 output:     /usr/local/rvm/gems/ruby-2.7.1/gems/activesupport-6.0.3.3/lib/active_support/lazy_load_hooks.rb:66:in `execute_hook'
App 331201 output:     /usr/local/rvm/gems/ruby-2.7.1/gems/activesupport-6.0.3.3/lib/active_support/lazy_load_hooks.rb:52:in `block in run_load_hooks'
App 331201 output:     /usr/local/rvm/gems/ruby-2.7.1/gems/activesupport-6.0.3.3/lib/active_support/lazy_load_hooks.rb:51:in `each'
App 331201 output:     /usr/local/rvm/gems/ruby-2.7.1/gems/activesupport-6.0.3.3/lib/active_support/lazy_load_hooks.rb:51:in `run_load_hooks'
App 331201 output:     /usr/local/rvm/gems/ruby-2.7.1/gems/activerecord-6.0.3.3/lib/active_record/base.rb:327:in `<module:ActiveRecord>'
App 331201 output:     /usr/local/rvm/gems/ruby-2.7.1/gems/activerecord-6.0.3.3/lib/active_record/base.rb:27:in `<top (required)>'
App 331201 output:     /usr/local/rvm/gems/ruby-2.7.1/gems/activesupport-6.0.3.3/lib/active_support/dependencies.rb:324:in `require'
App 331201 output:     /usr/local/rvm/gems/ruby-2.7.1/gems/activesupport-6.0.3.3/lib/active_support/dependencies.rb:324:in `block in require'
App 331201 output:     /usr/local/rvm/gems/ruby-2.7.1/gems/activesupport-6.0.3.3/lib/active_support/dependencies.rb:291:in `load_dependency'
App 331201 output:     /usr/local/rvm/gems/ruby-2.7.1/gems/activesupport-6.0.3.3/lib/active_support/dependencies.rb:324:in `require'
App 331201 output:     /usr/local/rvm/gems/ruby-2.7.1/gems/activestorage-6.0.3.3/app/models/active_storage/attachment.rb:8:in `<top (required)>'
App 331201 output:     /usr/local/rvm/gems/ruby-2.7.1/gems/activesupport-6.0.3.3/lib/active_support/dependencies.rb:324:in `require'
App 331201 output:     /usr/local/rvm/gems/ruby-2.7.1/gems/activesupport-6.0.3.3/lib/active_support/dependencies.rb:324:in `block in require'
App 331201 output:     /usr/local/rvm/gems/ruby-2.7.1/gems/activesupport-6.0.3.3/lib/active_support/dependencies.rb:291:in `load_dependency'
App 331201 output:     /usr/local/rvm/gems/ruby-2.7.1/gems/activesupport-6.0.3.3/lib/active_support/dependencies.rb:324:in `require'
App 331201 output:     /usr/local/rvm/gems/ruby-2.7.1/gems/activesupport-6.0.3.3/lib/active_support/dependencies.rb:411:in `block in require_or_load'
App 331201 output:     /usr/local/rvm/gems/ruby-2.7.1/gems/activesupport-6.0.3.3/lib/active_support/dependencies.rb:40:in `block in load_interlock'
App 331201 output:     /usr/local/rvm/gems/ruby-2.7.1/gems/activesupport-6.0.3.3/lib/active_support/dependencies/interlock.rb:14:in `block in loading'
App 331201 output:     /usr/local/rvm/gems/ruby-2.7.1/gems/activesupport-6.0.3.3/lib/active_support/concurrency/share_lock.rb:151:in `exclusive'
App 331201 output:     /usr/local/rvm/gems/ruby-2.7.1/gems/activesupport-6.0.3.3/lib/active_support/dependencies/interlock.rb:13:in `loading'
App 331201 output:     /usr/local/rvm/gems/ruby-2.7.1/gems/activesupport-6.0.3.3/lib/active_support/dependencies.rb:40:in `load_interlock'
App 331201 output:     /usr/local/rvm/gems/ruby-2.7.1/gems/activesupport-6.0.3.3/lib/active_support/dependencies.rb:389:in `require_or_load'
App 331201 output:     /usr/local/rvm/gems/ruby-2.7.1/gems/activesupport-6.0.3.3/lib/active_support/dependencies.rb:367:in `depend_on'
App 331201 output:     /usr/local/rvm/gems/ruby-2.7.1/gems/activesupport-6.0.3.3/lib/active_support/dependencies.rb:280:in `require_dependency'
App 331201 output:     /usr/local/rvm/gems/ruby-2.7.1/gems/railties-6.0.3.3/lib/rails/engine.rb:481:in `block (2 levels) in eager_load!'
App 331201 output:     /usr/local/rvm/gems/ruby-2.7.1/gems/railties-6.0.3.3/lib/rails/engine.rb:480:in `each'
App 331201 output:     /usr/local/rvm/gems/ruby-2.7.1/gems/railties-6.0.3.3/lib/rails/engine.rb:480:in `block in eager_load!'
App 331201 output:     /usr/local/rvm/gems/ruby-2.7.1/gems/railties-6.0.3.3/lib/rails/engine.rb:477:in `each'
App 331201 output:     /usr/local/rvm/gems/ruby-2.7.1/gems/railties-6.0.3.3/lib/rails/engine.rb:477:in `eager_load!'
App 331201 output:     /usr/local/rvm/gems/ruby-2.7.1/gems/railties-6.0.3.3/lib/rails/engine.rb:356:in `eager_load!'
App 331201 output:     /usr/local/rvm/gems/ruby-2.7.1/gems/railties-6.0.3.3/lib/rails/application/finisher.rb:123:in `each'
App 331201 output:     /usr/local/rvm/gems/ruby-2.7.1/gems/railties-6.0.3.3/lib/rails/application/finisher.rb:123:in `block in <module:Finisher>'
App 331201 output:     /usr/local/rvm/gems/ruby-2.7.1/gems/railties-6.0.3.3/lib/rails/initializable.rb:32:in `instance_exec'
App 331201 output:     /usr/local/rvm/gems/ruby-2.7.1/gems/railties-6.0.3.3/lib/rails/initializable.rb:32:in `run'
App 331201 output:     /usr/local/rvm/gems/ruby-2.7.1/gems/railties-6.0.3.3/lib/rails/initializable.rb:61:in `block in run_initializers'
App 331201 output:     /usr/local/rvm/rubies/ruby-2.7.1/lib/ruby/2.7.0/tsort.rb:228:in `block in tsort_each'
App 331201 output:     /usr/local/rvm/rubies/ruby-2.7.1/lib/ruby/2.7.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
App 331201 output:     /usr/local/rvm/rubies/ruby-2.7.1/lib/ruby/2.7.0/tsort.rb:431:in `each_strongly_connected_component_from'
App 331201 output:     /usr/local/rvm/rubies/ruby-2.7.1/lib/ruby/2.7.0/tsort.rb:349:in `block in each_strongly_connected_component'
App 331201 output:     /usr/local/rvm/rubies/ruby-2.7.1/lib/ruby/2.7.0/tsort.rb:347:in `each'
App 331201 output:     /usr/local/rvm/rubies/ruby-2.7.1/lib/ruby/2.7.0/tsort.rb:347:in `call'
App 331201 output:     /usr/local/rvm/rubies/ruby-2.7.1/lib/ruby/2.7.0/tsort.rb:347:in `each_strongly_connected_component'
App 331201 output:     /usr/local/rvm/rubies/ruby-2.7.1/lib/ruby/2.7.0/tsort.rb:226:in `tsort_each'
App 331201 output:     /usr/local/rvm/rubies/ruby-2.7.1/lib/ruby/2.7.0/tsort.rb:205:in `tsort_each'
App 331201 output:     /usr/local/rvm/gems/ruby-2.7.1/gems/railties-6.0.3.3/lib/rails/initializable.rb:60:in `run_initializers'
App 331201 output:     /usr/local/rvm/gems/ruby-2.7.1/gems/railties-6.0.3.3/lib/rails/application.rb:363:in `initialize!'
App 331201 output:     /backup/web/proton/production/releases/2010151703/config/environment.rb:20:in `<top (required)>'
App 331201 output:     config.ru:3:in `require_relative'
App 331201 output:     config.ru:3:in `block in <main>'
App 331201 output:     /usr/local/rvm/gems/ruby-2.7.1/gems/rack-2.2.3/lib/rack/builder.rb:125:in `instance_eval'
App 331201 output:     /usr/local/rvm/gems/ruby-2.7.1/gems/rack-2.2.3/lib/rack/builder.rb:125:in `initialize'
App 331201 output:     config.ru:1:in `new'
App 331201 output:     config.ru:1:in `<main>'
App 331201 output:     /usr/local/rvm/gems/ruby-2.7.1/gems/passenger-6.0.4/src/helper-scripts/rack-preloader.rb:101:in `eval'
App 331201 output:     /usr/local/rvm/gems/ruby-2.7.1/gems/passenger-6.0.4/src/helper-scripts/rack-preloader.rb:101:in `preload_app'
App 331201 output:     /usr/local/rvm/gems/ruby-2.7.1/gems/passenger-6.0.4/src/helper-scripts/rack-preloader.rb:189:in `block in <module:App>'
App 331201 output:     /usr/local/rvm/gems/ruby-2.7.1/gems/passenger-6.0.4/src/ruby_supportlib/phusion_passenger/loader_shared_helpers.rb:380:in `run_block_and_record_step_progress'
App 331201 output:     /usr/local/rvm/gems/ruby-2.7.1/gems/passenger-6.0.4/src/helper-scripts/rack-preloader.rb:188:in `<module:App>'
App 331201 output:     /usr/local/rvm/gems/ruby-2.7.1/gems/passenger-6.0.4/src/helper-scripts/rack-preloader.rb:30:in `<module:PhusionPassenger>'
App 331201 output:     /usr/local/rvm/gems/ruby-2.7.1/gems/passenger-6.0.4/src/helper-scripts/rack-preloader.rb:29:in `<main>'

**Comment by kiawizard** [comment]
Or another one:

App 29371 output: Error: The application encountered the following error: undefined method `serialize' for #<Class:0x0000000006c71c70> (NoMethodError)
App 29371 output:     /usr/local/rvm/gems/ruby-2.7.1/gems/activerecord-6.0.3.3/lib/active_record/dynamic_matchers.rb:22:in `method_missing'
App 29371 output:     /usr/local/rvm/gems/ruby-2.7.1/gems/activerecord-6.0.3.3/lib/active_record/store.rb:105:in `store'
App 29371 output:     /usr/local/rvm/gems/ruby-2.7.1/gems/activestorage-6.0.3.3/app/models/active_storage/blob.rb:33:in `<class:Blob>'
App 29371 output:     /usr/local/rvm/gems/ruby-2.7.1/gems/activestorage-6.0.3.3/app/models/active_storage/blob.rb:19:in `<top (required)>'
App 29371 output:     /usr/local/rvm/gems/ruby-2.7.1/gems/activesupport-6.0.3.3/lib/active_support/dependencies.rb:324:in `require'
App 29371 output:     /usr/local/rvm/gems/ruby-2.7.1/gems/activesupport-6.0.3.3/lib/active_support/dependencies.rb:324:in `block in require'
App 29371 output:     /usr/local/rvm/gems/ruby-2.7.1/gems/activesupport-6.0.3.3/lib/active_support/dependencies.rb:291:in `load_dependency'
App 29371 output:     /usr/local/rvm/gems/ruby-2.7.1/gems/activesupport-6.0.3.3/lib/active_support/dependencies.rb:324:in `require'
App 29371 output:     /usr/local/rvm/gems/ruby-2.7.1/gems/activesupport-6.0.3.3/lib/active_support/dependencies.rb:411:in `block in require_or_load'
App 29371 output:     /usr/local/rvm/gems/ruby-2.7.1/gems/activesupport-6.0.3.3/lib/active_support/dependencies.rb:40:in `block in load_interlock'
App 29371 output:     /usr/local/rvm/gems/ruby-2.7.1/gems/activesupport-6.0.3.3/lib/active_support/dependencies/interlock.rb:14:in `block in loading'
App 29371 output:     /usr/local/rvm/gems/ruby-2.7.1/gems/activesupport-6.0.3.3/lib/active_support/concurrency/share_lock.rb:151:in `exclusive'
App 29371 output:     /usr/local/rvm/gems/ruby-2.7.1/gems/activesupport-6.0.3.3/lib/active_support/dependencies/interlock.rb:13:in `loading'
App 29371 output:     /usr/local/rvm/gems/ruby-2.7.1/gems/activesupport-6.0.3.3/lib/active_support/dependencies.rb:40:in `load_interlock'
App 29371 output:     /usr/local/rvm/gems/ruby-2.7.1/gems/activesupport-6.0.3.3/lib/active_support/dependencies.rb:389:in `require_or_load'
App 29371 output:     /usr/local/rvm/gems/ruby-2.7.1/gems/activesupport-6.0.3.3/lib/active_support/dependencies.rb:367:in `depend_on'
App 29371 output:     /usr/local/rvm/gems/ruby-2.7.1/gems/activesupport-6.0.3.3/lib/active_support/dependencies.rb:280:in `require_dependency'
App 29371 output:     /usr/local/rvm/gems/ruby-2.7.1/gems/railties-6.0.3.3/lib/rails/engine.rb:481:in `block (2 levels) in eager_load!'
App 29371 output:     /usr/local/rvm/gems/ruby-2.7.1/gems/railties-6.0.3.3/lib/rails/engine.rb:480:in `each'
App 29371 output:     /usr/local/rvm/gems/ruby-2.7.1/gems/railties-6.0.3.3/lib/rails/engine.rb:480:in `block in eager_load!'
App 29371 output:     /usr/local/rvm/gems/ruby-2.7.1/gems/railties-6.0.3.3/lib/rails/engine.rb:477:in `each'
App 29371 output:     /usr/local/rvm/gems/ruby-2.7.1/gems/railties-6.0.3.3/lib/rails/engi
App 29371 output: ne.rb:477:in `eager_load!'
App 29371 output:     /usr/local/rvm/gems/ruby-2.7.1/gems/railties-6.0.3.3/lib/rails/engine.rb:356:in `eager_load!'
App 29371 output:     /usr/local/rvm/gems/ruby-2.7.1/gems/railties-6.0.3.3/lib/rails/application/finisher.rb:123:in `each'
App 29371 output:     /usr/local/rvm/gems/ruby-2.7.1/gems/railties-6.0.3.3/lib/rails/application/finisher.rb:123:in `block in <module:Finisher>'
App 29371 output:     /usr/local/rvm/gems/ruby-2.7.1/gems/railties-6.0.3.3/lib/rails/initializable.rb:32:in `instance_exec'
App 29371 output:     /usr/local/rvm/gems/ruby-2.7.1/gems/railties-6.0.3.3/lib/rails/initializable.rb:32:in `run'
App 29371 output:     /usr/local/rvm/gems/ruby-2.7.1/gems/railties-6.0.3.3/lib/rails/initializable.rb:61:in `block in run_initializers'
App 29371 output:     /usr/local/rvm/rubies/ruby-2.7.1/lib/ruby/2.7.0/tsort.rb:228:in `block in tsort_each'
App 29371 output:     /usr/local/rvm/rubies/ruby-2.7.1/lib/ruby/2.7.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
App 29371 output:     /usr/local/rvm/rubies/ruby-2.7.1/lib/ruby/2.7.0/tsort.rb:431:in `each_strongly_connected_component_from'
App 29371 output:     /usr/local/rvm/rubies/ruby-2.7.1/lib/ruby/2.7.0/tsort.rb:349:in `block in each_strongly_connected_component'
App 29371 output:     /usr/local/rvm/rubies/ruby-2.7.1/lib/ruby/2.7.0/tsort.rb:347:in `each'
App 29371 output:     /usr/local/rvm/rubies/ruby-2.7.1/lib/ruby/2.7.0/tsort.rb:347:in `call'
App 29371 output:     /usr/local/rvm/rubies/ruby-2.7.1/lib/ruby/2.7.0/tsort.rb:347:in `each_strongly_connected_component'
App 29371 output:     /usr/local/rvm/rubies/ruby-2.7.1/lib/ruby/2.7.0/tsort.rb:226:in `tsort_each'
App 29371 output:     /usr/local/rvm/rubies/ruby-2.7.1/lib/ruby/2.7.0/tsort.rb:205:in `tsort_each'
App 29371 output:     /usr/local/rvm/gems/ruby-2.7.1/gems/railties-6.0.3.3/lib/rails/initializable.rb:60:in `run_initializers'
App 29371 output:     /usr/local/rvm/gems/ruby-2.7.1/gems/railties-6.0.3.3/lib/rails/application.rb:363:in `initialize!'
App 29371 output:     /backup/web/proton/production/releases/2010151703/config/environment.rb:20:in `<top (required)>'
App 29371 output:     config.ru:3:in `require_relative'
App 29371 output:     config.ru:3:in `block in <main>'
App 29371 output:     /usr/local/rvm/gems/ruby-2.7.1/gems/rack-2.2.3/lib/rack/builder.rb:125:in `instance_eval'
App 29371 output:     /usr/local/rvm/gems/ruby-2.7.1/gems/rack-2.2.3/lib/rack/builder.rb:125:in `initialize'
App 29371 output:     config.ru:1:in `new'
App 29371 output:     config.ru:1:in `<main>'
App 29371 output:     /usr/local/rvm/gems/ruby-2.7.1/gems/passenger-6.0.4/src/helper-scripts/rack-preloader.rb:101:in `eval'
App 29371 output:     /usr/local/rvm/gems/ruby-2.7.1/gems/passenger-6.0.4/src/helper-scripts/rack-preloader.rb:101:in `preload_app'
App 29371 output:     /usr/local/rvm/gems/ruby-2.7.1/gems/passenger-6.0.4/src/helper-scripts/rack-preloader.rb:189:in `block in <module:App>'
App 29371 output:     /usr/local/rvm/gems/ruby-2.7.1/gems/passenger-6.0.4/src/ruby_supportlib/phusion_passenger/loader_shared_helpers.rb:380:in `run_block_and_record_step_progress'
App 29371 output:     /usr/local/rvm/gems/ruby-2.7.1/gems/passenger-6.0.4/src/helper-scripts/rack-preloader.rb:188:in `<module:App>'
App 29371 output:     /usr/local/rvm/gems/ruby-2.7.1/gems/passenger-6.0.4/src/helper-scripts/rack-preloader.rb:30:in `<module:PhusionPassenger>'
App 29371 output:     /usr/local/rvm/gems/ruby-2.7.1/gems/passenger-6.0.4/src/helper-scripts/rack-preloader.rb:29:in `<main>'

**Comment by kiawizard** [comment]
Does it make sense trying to upgrade Passenger from 6.0.4 to 6.0.6? It seems to me that some kind of corruption occurs somewhere in its worker processes, AR loses its methods

**Comment by p8** [comment]
Anything special configured at `/backup/web/proton/production/releases/2010151703/config/environment.rb:20`?

**Comment by kiawizard** [comment]
> Anything special configured at `/backup/web/proton/production/releases/2010151703/config/environment.rb:20`?
Nothing special, just
  Rails.application.initialize!
wrapped in loading time measuring block

**Comment by p8** [comment]
It seems that in both cases it somehow requires ActiveStorage too early:
`/usr/local/rvm/gems/ruby-2.7.1/gems/activestorage-6.0.3.3/app/models/active_storage/attachment.rb:8:in `<top (required)>'`
`/usr/local/rvm/gems/ruby-2.7.1/gems/activestorage-6.0.3.3/app/models/active_storage/blob.rb:19:in `<top (required)>'`
