### ISSUE TITLE
Update Puma Gemfile entry?

### ISSUE THREAD

**Issue by nateberkopec** [rails/rails#40400]
What's the policy on when/how entries to the default Gemfile are updated?

I'd like to update the `rails new` Gemfile to `puma ~> 5.0` and change the shipped config files a bit to match our new defaults too. Is that legal to do for 6.1?

**Comment by rafaelfranca** [comment]
Yes. Please go for it. Just make `puma >= 5.0` since we don't put upper bounds in any of the Rails projects.

**Comment by nateberkopec** [comment]
Cool! I'll do it soon.
