### ISSUE TITLE
Arel::Collectors::SQLString.new always returns ?

### ISSUE THREAD

**Issue by akhilravuri1** [rails/rails#40410]
### Steps to reproduce

I have overloaded visit_Arel_Nodes_SelectStatement function in arel::visitors::ToSql.
```
def visit_Arel_Nodes_SelectStatement(o, collector)
    if o.limit
      limcoll = Arel::Collectors::SQLString.new
      visit o.limit, limcoll
      puts "#{limcoll}"
    end
end
```
Using this I used to get the limit value till rails 4 but when I upgraded to the latest rails 6.0.3.4 it returns 1.

### Expected behavior

Should print the limit value.

### Actual behavior

But prints ?

### System configuration
**Rails version**: 6.0.3.4

**Ruby version**: 2.6.5

**Comment by p8** [comment]
@akhilravuri1 You might want to compare your implementation with:
The old Arel implementation:
https://github.com/rails/arel/tree/7-1-stable/lib/arel/visitors 
The current Rails implementation:
https://github.com/rails/rails/tree/master/activerecord/lib/arel/visitors

**Comment by akhilravuri1** [comment]
Sorry If I am wrong.

Even with the latest implementation, the visit_Arel_Nodes_Limit function is the same so changes are done after that.
Like Vvisit_Arel_Nodes_BindParam has changed. Does this change my result?

Thanks,
Akhil

**Comment by p8** [comment]
Sorry, can't help you there. My Arel knowledge is limited.

**Comment by akhilravuri1** [comment]
Thank you for giving a try.

**Comment by simi** [comment]
`visit_Arel_Nodes_SelectStatement` is deeply hidden private method. I think there is nothing we can do for you in here other to suggest to rely on public API instead.

**Comment by akhilravuri1** [comment]
Hi @simi 

Thanks for the information but when writing a rails adapter, people override some of the existing functionalities to make use of it most. In this case, I am just trying to get the limit and offset values so that I can add them to use it for between statements.

Thanks,
Akhil
