### ISSUE TITLE
Bug in handling empty url string in database.yml

### ISSUE THREAD

**Issue by kvokka** [rails/rails#40416]
### Steps to reproduce

```bash
$ rails new dbyml && cd dbyml
$ echo "  url: \"\"" >> config/database.yml
$ rake db:version
rake aborted!
Database URL cannot be empty
/Users/mike/proj/tmp/dbyml/Rakefile:6:in `<top (required)>'
(See full trace by running task with --trace)
```

In the real-world example it was a <del>`url: "<%= ENV['DB_URL', 'some_stub'] %>"`</del> `url: "<%= ENV.fetch['DB_URL', 'some_stub'] %>"`, and the quotes around ERB fragment looks natural (keep in mind that for things like helm charts it is best practice to put them rather than not) and the error message is absolutely misleading.

Note, that the error appears in `development` env, while the "problem" in the configuration was in `production`.

Bugfix will follow

### Expected behavior

```bash
$ rake db:version
Current version: 0
```

### System configuration
**Rails version**:
```bash
$ rails --version 
Rails 6.0.3.4
# the same with 6.1.0.alpha on current master
```

**Ruby version**: 2.6.3

Connect replaygaming/replaypoker#5104
Connect replaygaming/replaypoker#4860

**Comment by sinsoku** [comment]
This code raises an error.

```ruby
ENV['DB_URL', 'some_stub']
#=> ArgumentError (wrong number of arguments (given 2, expected 1))
```

Maybe `ENV#fetch`?

```ruby
ENV.fetch('DB_URL', 'some_stub')
#=> "some_stub"
```

**Comment by sinsoku** [comment]
@kvokka 
If users unintentionally specify an empty string (such as a misconfiguration), it is a problem for the server to start without an error.
I think it's better to print an error message so that users notice that there is a problem with the production configuration.

**Comment by kvokka** [comment]
> This code raises an error.
> 
> ```ruby
> ENV['DB_URL', 'some_stub']
> #=> ArgumentError (wrong number of arguments (given 2, expected 1))
> ```

@sinsoku 

Thank u! fixed it in the issue description also.

Even if take approach with raising an error, it should be managed differently, cos now, for example running specs the developer may get an error from DB setting on staging with the message: `Database URL cannot be empty`. I do not see any reason how current env can be affected by another isolated env (which should not event exist at the moment).
