### ISSUE TITLE
Calling Time.zone.at on a TimeWithZone can have different behavior than calling Time.zone.at on a Time

### ISSUE THREAD

**Issue by LandonSchropp** [rails/rails#40413]
### Steps to reproduce

We ran across this tricky bug in our application. The behavior for a time at the end of a month changes based upon whether it's a `Time` or a `TimeWithZone`.

```
require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  git_source(:github) { |repo| "https://github.com/#{ repo }.git" }

  # Activate the gem you are reporting the issue against.
  gem "activesupport", "6.0.3"
end

require "active_support"
require "active_support/core_ext"
require "minitest/autorun"

class BugTest < Minitest::Test
  def test_stuff
    Time.zone = "Etc/UTC"

    end_of_january_without_time_zone = "2019-01-01 00:00:00Z".to_time.end_of_month
    end_of_january_with_time_zone = end_of_january_without_time_zone.in_time_zone

    puts "Time objects:"
    p end_of_january_with_time_zone
    p end_of_january_without_time_zone
    puts

    puts "Calling Time.zone.at on time objects:"
    p Time.zone.at(end_of_january_with_time_zone)
    p Time.zone.at(end_of_january_without_time_zone)
    puts

    assert_equal(
      Time.zone.at(end_of_january_with_time_zone),
      Time.zone.at(end_of_january_without_time_zone)
    )
  end
end
```

### Expected behavior

The two times returned from `Time.zone.at` should be identical.

### Actual behavior

Somewhere along the way, the `TimeWithZone` is getting rounded up.

### System configuration

**Rails version**: 6.0.3
**Ruby version**: 2.7.1p83

**Comment by LandonSchropp** [comment]
(I added the print statements to help clarify the problem. They're not necessary for the spec to fail.)

**Comment by BKSpurgeon** [comment]
Am far from an expert in dealing with Time, but here are my thoughts. [ActiveSupport::TimeZone Reference](https://github.com/rails/rails/blob/fe76a95b0d252a2d7c25e69498b720c96b243ea2/activesupport/lib/active_support/values/time_zone.rb#L363)

Let's work through the source code via `rails console`:

```ruby

# let's set it up
Time.zone = "Etc/UTC"
end_of_january_without_time_zone = "2019-01-01 00:00:00Z".to_time.end_of_month
end_of_january_with_time_zone = end_of_january_without_time_zone.in_time_zone

# I prefer these variable names
without_zone = end_of_january_without_time_zone
zoned = end_of_january_with_time_zone

## We're dealing with slightly different objects
without_zone.class    # => Time
without_zone.zone    # => nil
zoned.class               # => ActiveSupport::TimeWithZone
zoned.zone               # => UTC # (as expected)

# Both have the same epoch
without_zone.to_i      # => 1548979199  
zoned.to_i                 # => 1548979199

# If they have the same epoch, I would expect them both to be equal?

Time.at(without_zone)  # => 2019-01-31 23:59:59 +0000    
Time.at(zoned)            # => 2019-02-01 11:00:00 +1100  # (no prizes for guessing my TimeZone :) -- but hang on, didn't we set the zone to Etc/UTC before!?! In any case, shouldn't it be 10:59:59 ? )

Time.at(without_zone).utc     # => 2019-01-31 23:59:59 UTC # presumably defaults to UTC?
Time.at(zoned).utc               # => 2019-02-01 00:00:00 UTC # but the damage was done above.
```

**Comment by LandonSchropp** [comment]
@BKSpurgeon Yep, all of that looks correct to me. I realize this seems like a strange test case to bring up, but we ran into a real-world scenario that's triggered by this. Our tests were passing for `Time` objects that we were creating, but the code was failing from the API because it was passing in `TimeWithZone`.

The test case I posted above was my attempt to simplify this problem so it was reproducible.

**Comment by LandonSchropp** [comment]
I *think* `Time.at` may default to parsing the time zone in whatever the current `Time.zone` is. Without explicitly setting it to `Etc/UTC`, it's returning in `-0500` for me.

**Comment by BKSpurgeon** [comment]
# This is where the [rounding off seems to occur](https://github.com/rails/rails/blob/fe76a95b0d252a2d7c25e69498b720c96b243ea2/activesupport/lib/active_support/core_ext/time/calculations.rb#L51):

```ruby
at_without_coercion(time_or_number.to_f).getlocal  
# time_or_number.to_f => 1548939600.0   # which is not what we want, per se.
```

**Comment by eugeneius** [comment]
Fixed by https://github.com/rails/rails/pull/40448.

**Comment by LandonSchropp** [comment]
@eugeneius Awesome! Thank you so much. 🙂
