### ISSUE TITLE
Deploying to staging causes error with Spring binstub in boot.rb

### ISSUE THREAD

**Issue by Pugio** [rails/rails#40428]
### Steps to reproduce
`config/boot.rb` attempts to load spring with
```ruby
begin
  load File.expand_path("../bin/spring", __dir__)
rescue LoadError => e
  raise unless e.path.end_with?("/bin/spring")
end
```

Since this is production (and spring is development only), that load command generates an error:
`Gem::LoadError: spring is not part of the bundle. Add it to your Gemfile.`

That `LoadError` instance *does not* contain a public `#path` var/method, which causes the `.end_with?` to fail with: `NoMethodError: undefined method 'end_with?' for nil:NilClass` because `.path` ends up being nil.

I tried looking through the source (at `rails/railties/lib/rails/generators/rails/app/templates/config/boot.rb.tt`) and am stuck with a "but how did it ever work?"

```bash
rails new tester
cd tester
bundle config --local without development:test
bundle install
bundle exec rake assets:precompile # or any other command which loads the environment
```

### Expected behavior
`e.path` should be a string.

### Actual behavior
`e.path` is `nil`.

### System configuration
**Rails version**: Master 8183963bcd6fd6bb6bc0e4dd4361b86d064fe70f

**Ruby version**: 2.7.1

**Comment by jonathanhefner** [comment]
Thank you for bringing this up.  This is due to #39632.  #39746 has an explanation and a fix.

Related discussion: https://github.com/rails/rails/issues/39622#issuecomment-649850312
