### ISSUE TITLE
ActiveStorage's Proxy controller cannot serve video files to Safari

### ISSUE THREAD

**Issue by brenogazzola** [rails/rails#40422]
### Steps to reproduce
1 - Upload an mp4 file to active storage using the S3 service.
2 - Render it on a view using a `video` tag and the `rails_storage_proxy_url` helper.
3 - Open It on Safari

It's possible to see this in action the fiddle below, which uses a link from my app (500kb MP4 of an illustrated bear, without sound)
https://jsfiddle.net/wuf9b1c4/1/

### Expected behavior
The video tag should be visible and video playable, like on Chrome

### Actual behavior
Either a blank screen, or a broken video player. Checking the network tab and looking for the video file you can see an error message written "Byte Range". 

It seems 3 things are missing for safari: the `Accept-Ranges` and `Content-Length` headers, as well as a 206 instead of 200 return.

### System configuration
**Rails version**: Master (0a608bd987fde4f9bc5bcf4bcebdb181d199cf4f)
**Ruby version**: 2.7.2

**Comment by brenogazzola** [comment]
@fleck Have you noticed this behaviour before? Am I missing some sort of setting in active storage?

**Comment by fleck** [comment]
I haven't used ActiveStorage for audio or video files. Doing a quick search it looks as though Rails doesn't support byteranges: https://www.reddit.com/r/rails/comments/avwg8j/rails_byterange_request_support/ehk9sjs/ 

Possible options would be:

- If you aren't caching the HTML you can use `rails_storage_redirect_path`
- if you need to cache the HTML, but don't need to proxy the file through Rails you could probably use this feature: https://github.com/rails/rails/commit/feab7031b57040afa2b2f5f78f9251dbad6cbdf8 so you get a permanent URL that's safe to cache in HTML
- if you want this to proxy through Rails you'll have to dig into the proxy controller and see if it's possible to get it to support byteranges and patch it for your application and optionally open a PR if you wanna get that into Rails

**Comment by brenogazzola** [comment]
That's too bad. I am actually relying on a custom controller, based on your proxy controller, to have SEO friendly urls for our art assets, and I would like those to be cached. I was hoping I could get this solved on active storage itself, or on my own controller, but if Rails does not support it... changing that is a bit beyond my skill set.

Anyway, thanks for taking the time to answer

**Comment by hoshinotsuyoshi** [comment]
Maybe related to https://github.com/rails/rails/pull/41437
