### ISSUE TITLE
Option to generate new Rails 6 project using Sprockets instead of Webpacker

### ISSUE THREAD

**Issue by chrisma** [rails/rails#40438]
### Steps to reproduce
* `rails new nowebpack --skip-webpack-install --no-rc --skip-bundle` (no  `--skip-webpacker` / `--use-sprockets` option, unfortunately)
* `grep "gem 'webpacker'" Gemfile ` (webpacker gem still included, as only `webpacker:install` is skipped)
* `grep "//= link_directory ../javascripts .js" nowebpack/app/assets/config/manifest.js` (`manifest.js` is missing required config)
* `grep "javascript_pack_tag" nowebpack/app/views/layouts/application.html.erb` (still includes webpack reference, instead of `javascript_include_tag`)
* `cat nowebpack/app/javascript/packs/application.js` (webpacker configuration is generated)

### Expected behavior
**When running `rails new`, it would be helpful to have a `--skip-webpacker` option (similar to `--skip-turbolinks` or `--skip-bootsnap`) or a `--use-sprockets` / `--use-asset-pipeline` option.
Ideally, it would be possible to create a Rails 6 application on the command line  (without manual fixes) that relies on Sprockets instead of Webpack and creates the correct configuration.**

Alternatively, when running `rails new` with the  `--skip-webpack-install` option, showing a link to a page with the required changes for running with sprockets would help.

### Actual behavior
There is no option to generate the required files for using Rails 6 with Sprockets instead of webpacker using the `rails new` command.
When running `rails new` with the `--skip-webpack-install` option, the `webpacker` gem is still included and webpacker configuration is still created (see #35484), resulting in a Rails application state that is not running (e.g., `rails s` fails, see #36280). 
Manual changes are necessary, that could be automated with a new option:
* `sed -i 's/javascript_pack_tag/javascript_include_tag/g' nowebpack/app/views/layouts/application.html.erb`
* `mkdir -p nowebpack/app/assets/javascripts/`
* `touch nowebpack/app/assets/javascripts/application.js` (create missing file, contents, e.g. [here](https://github.com/chrisma/rails6-github-actions/blob/main/default/app/assets/javascripts/application.js))
* `echo '//= link_directory ../javascripts .js' >> blog/app/assets/config/manifest.js`

### System configuration
**Rails version**: Rails 6.0.3.4

**Ruby version**: ruby 2.7.2p137 (2020-10-01 revision 5445e04352) [x86_64-linux]

**Comment by composerinteralia** [comment]
We use the issue tracker primarily for bug reports, and not feature requests, so I am going to close this issue. Please check out the [contribution guide](https://edgeguides.rubyonrails.org/contributing_to_ruby_on_rails.html#what-about-feature-requests-questionmark) for details on how to approach new features. Thank you!
