### ISSUE TITLE
Bugs due to Leaky Abstraction of in_time_zone

### ISSUE THREAD

**Issue by imamfzn** [rails/rails#40454]
There is a bug in rails `4.2.11` due to leaky abstraction of `in_time_zone` method.

### Steps to reproduce

In rails 4.2.7.1:
![Screenshot from 2020-10-26 08-50-44](https://user-images.githubusercontent.com/8236772/97126755-57168d00-176a-11eb-9122-aceaddd2b1f1.png)

In rails 4.2.11.1
![Screenshot from 2020-10-26 08-54-02](https://user-images.githubusercontent.com/8236772/97126765-609ff500-176a-11eb-98f8-d159677540a3.png)

It caused by https://github.com/rails/rails/commit/bcda029a47b414a86d196eeae19c651ea3ca9be changes.

From that changes, we had:
```
DateTime + in_time_zone -> DateTime
Time + in_time_zone -> Time
```

Rails have different behaviour of `end_of_day` method in `Time` and `DateTime` class:

- In `DateTime`, `end_of_day` will change hour, minute, second (https://github.com/rails/rails/blob/v4.2.11.1/activesupport/lib/active_support/core_ext/date_time/calculations.rb#L120)
- In `Time`, `end_of_day` will change hour, minute, second and ms (https://github.com/rails/rails/blob/v4.2.11.1/activesupport/lib/active_support/core_ext/time/calculations.rb#L180)

It will make bugs because of different behaviour from `4.2.7` from using `in_time_zone.end_of_day` from `DateTime` instance. Because that value will be wrong to compare.

Have any suggestion how to handle this issue ? Can we use same behaviour in `4.2.11` like before https://github.com/rails/rails/commit/bcda029a47b414a86d196eeae19c651ea3ca9be1 implementation.

### Expected behavior

Same as 4.2.7 that `in_time_zone` will return depending on how the `ActiveSupport::TimeWithZone` instance had
been constructed.

### Actual behavior

`in_time_zone` returns `Time`. It make `end_of_day` from `DateTime` instance will set 9999 on milliseconds.

### System configuration
**Rails version**:
From: 4.2.7.1
To: 4.2.11.1

**Ruby version**:
ruby 2.3.0

**Comment by louim** [comment]
Hey! I'm not able to reproduce using Rails 6 (6.0.3.4):
```
irb(main):004:0> now_eod = DateTime.now.in_time_zone.end_of_day
=> Mon, 26 Oct 2020 23:59:59 UTC +00:00
irb(main):005:0> now_eod.to_time
=> 2020-10-26 23:59:59 +0000
```
You should probably try to update to a more recent version, [rails 4.2 is not supported anymore](https://guides.rubyonrails.org/maintenance_policy.html#bug-fixes).
