### ISSUE TITLE
Should I allow public access to ActiveStorage routes?

### ISSUE THREAD

**Issue by NobodysNightmare** [rails/rails#40462]
Hello,

I've been starting to learn how ActiveStorage works and I am really happy how easy it is to get a simple file upload that "just works".

However, when we implemented it in our application we noticed that `/rails/activestorage/blobs` needs to be accessible (e.g. no middleware forcing a login) for anyone to be able to use the uploaded file (e.g. if we put the `url_for(user.avatar)`) into an email.

So far so good, that sounds expectable. However, this made me wonder, which expectations I should be having for these routes and whether I can read up more on that elsewhere (or alternatively: whether this should be part of the docs).

Questions I have in mind:

* Would it be fine for `/rails/activestorage/blobs` to be publicly accessible (e.g. no login), even if storing confidential attachments?
* Since the links generated by `url_for` are permanent links according to the docs, is there a way to generate temporary links through ActiveStorage?
    * To be clear: I see that the links that AS redirects to are temporary by default, but since those are generated from a permalink, this doesn't help much in the case of `/rails/activestorage/blobs` being public
* Even if a login is required, different users might be allowed to see different files as per my application's logic. Is there anything AS-specific to be considered here?

I think those questions could also be summarized as:

**As per design of ActiveStorage: Should  `/rails/activestorage/blobs` (and other routes under  `/rails/activestorage/*`) be protected by additional security measures (e.g. file-level authorization), or can they safely be left publicly accessible?**

I can _imagine_ the latter being the case, because I see signed ids being necessary in most places, but then again, imagination is not one of the best tools in assessing how to use a framework securely.

Thanks a lot for your help.

**Comment by adeeb1** [comment]
I can't speak to the first question, but just now I needed to figure out how to make images accessible without using Rails routes. Active Storage can generate a temporary, signed URL from your cloud storage provider with the `blob.url` method ([source](https://github.com/rails/rails/blob/ad0b10f6c3af83623ab418c68693b4c432a0b2dd/activestorage/app/models/active_storage/blob.rb#L190)). You can set the expiration time. That way, you can still have private resources and create publicly accessible links.

**Comment by composerinteralia** [comment]
You may find this [comment in the redirect controller](https://github.com/rails/rails/blob/ad0b10f6c3af83623ab418c68693b4c432a0b2dd/activestorage/app/controllers/active_storage/blobs/redirect_controller.rb#L4-L6) helpful. Basically it depends on what sort of security your application requires.

Since we use the issue track primarily for bug reports, rather than more open ended questions, I am going to close this. A better place to discuss this would be on the [rubyonrails-talk discussion board](https://discuss.rubyonrails.org/c/rubyonrails-talk/7). Thank you!

**Comment by NobodysNightmare** [comment]
Thanks a lot for your response, I think that's helpful. The "issue part" of my question is of course that I am planning to propose an extension of the docs for this :)

But thanks for pointing me to the discussion board, because honestly: I wasn't aware that this exists :D
